xtrngpsv.h
XTRNGPSV_SEC_STRENGTH_BYTES
Security strength in bytes.
Referenced by XTrngpsv_DF, XTrngpsv_Generate.
XTRNGPSV_SEC_STRENGTH_LEN
Security strength in Words.
XTRNGPSV_PERS_STR_LEN
Personalization string length in dwords.
Referenced by XTrngpsv_Uninstantiate.
XTRNGPSV_PERS_STR_LEN_BYTES
Personalization string length in bytes.
Referenced by XTrngpsv_DF, XTrngpsv_RunKAT.
XTRNGPSV_SEED_LEN
Seed length in dwords.
Referenced by XTrngpsv_Uninstantiate.
XTRNGPSV_SEED_LEN_BYTES
Seed length in bytes.
Referenced by XTrngpsv_DF, XTrngpsv_Reseed, XTrngpsv_RunKAT.
XTRNGPSV_GEN_LEN_BYTES
No.
of bytes per Generate request
Referenced by XTrngpsv_DF, XTrngpsv_RunKAT.
RAND_BUF_LEN
No.
of 32 bit words
MAX_PRE_DF_LEN_BYTES
With max DFLenMul of 9 (9+1)*128= 1280 bits.
MAX_PRE_DF_LEN_WORDS
With max DFLenMul of 9 (9+1)*128= 1280 bits.
DF_SEED
to indicate DF called for seed
Referenced by XTrngpsv_DF.
DF_RAND
to indicate DF called for random number
Referenced by XTrngpsv_Generate.
DF_IP_IV_LEN
Input IV Length for DF.
BYTES_PER_BLOCK
No.
of bytes per block, equivalent to 128 bits
Referenced by XTrngpsv_Generate, XTrngpsv_RunKAT.
DF_PAD_DATA_LEN
Length of Padding data used for DF calculation.
XTRNGPSV_SUCCESS
SUCCESS definition of TRNGPSV driver.
Referenced by XTrngpsv_CfgInitialize, XTrngpsv_DF, XTrngpsv_Generate, XTrngpsv_Instantiate, XTrngpsv_Reseed, XTrngpsv_RunHealthTest, XTrngpsv_RunKAT, XTrngpsv_Uninstantiate.
XTRNGPSV_FAILURE
FAILURE definition of TRNGPSV driver.
Referenced by XTrngpsv_CfgInitialize, XTrngpsv_DF, XTrngpsv_Generate, XTrngpsv_Instantiate, XTrngpsv_Reseed, XTrngpsv_RunHealthTest, XTrngpsv_RunKAT, XTrngpsv_Uninstantiate.
XTRNGPSV_TRUE
Boolean TRUE definition of TRNGPSV driver.
Referenced by XTrngpsv_Generate, XTrngpsv_Instantiate, XTrngpsv_Reseed, XTrngpsv_RunKAT.
XTRNGPSV_FALSE
Boolean FALSE definition of TRNGPSV driver.
Referenced by XTrngpsv_Generate, XTrngpsv_Instantiate, XTrngpsv_Reseed, XTrngpsv_RunHealthTest, XTrngpsv_RunKAT.
XTRNGPSV_SWAP_ENDIAN
Macro to swap endianness of 32 bit data.
Referenced by XTrngpsv_DF.
XTrngpsv_ErrorCodes
0x10 - Invalid parameter passed to function
XTrngpsv_State
0 - Driver is not in Initialized state
XTrngpsv_Mode
0 - Hybrid RNG
XTrngpsv_Config XTrngpsv_ConfigTable[][]
XTrngpsv_Config * XTrngpsv_LookupConfig(UINTPTR BaseAddress)
This function returns a reference to an XTrng_Config structure based on the DeviceId.
The return value will refer to an entry in the device configuration table defined in the xtrng_g.c file. DeviceId is the unique device ID of the device being lookedup. XTrng_LookupConfig returns a reference to a config record in the configuration table (in xtrngpsv.c) corresponding to DeviceId, or NULL if no match is found.
s32 XTrngpsv_CfgInitialize(XTrngpsv *InstancePtr, const XTrngpsv_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the TRNGPSV instance/driver.
This function must be called prior to using the driver. Initialization includes only setting up the device id and base address. All the remaining parameters of the Instance will be initialized in Instantiate function. InstancePtr is a pointer to the XTrngpsv instance to be worked on. CfgPtr points to the configuration structure associated with the TRNGPSV driver. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XTRNGPSV_SUCCESS if initialization was successful.XTRNGPSV_ERROR_INVALID_PARAM if invalid parameter passed to this function.
References XTRNGPSV_ERROR, XTRNGPSV_ERROR_INVALID_PARAM, XTRNGPSV_FAILURE, XTRNGPSV_SUCCESS, XTRNGPSV_UNINITIALIZED.
s32 XTrngpsv_Instantiate(XTrngpsv *InstancePtr, const XTrngpsv_UsrCfg *ConfigurValues)
This function further initializes i.e.
instantiates the TRNGPSV instance/driver with user configuration, resets the TRNG core and reseeds with initial seed and personalization string provided during Instantiation. Switching to a new state of attributes or changing any attributes (configured during Instantiation) requires UnInstantiation of the current instance and instantiation of a new instance. After successful Instantiation, State of the driver is changed to Healthy. InstancePtr is a pointer to the XTrngpsv instance to be worked on. ConfigurValues points to the user configuration structure associated with the TRNGPSV driver. XTRNGPSV_SUCCESS if Instantiation was successful.XTRNGPSV_ERROR_INVALID_PARAM if invalid parameter(s) passed to this function.XTRNGPSV_ERROR_NOT_UNINSTANTIATED if the driver is not uninstantiated earlier.XTRNGPSV_ERROR_INVALID_USRCFG_MODE if invalid Mode parameter.XTRNGPSV_ERROR_INVALID_USRCFG_SEEDLIFE if SeedLife parameter is invalidXTRNGPSV_ERROR_INVALID_USRCFG_PREDRES if invalid Prediction Resistance parameter.XTRNGPSV_ERROR_INVALID_USRCFG_PERSPRES if PersStrPresent parameter is invalid.XTRNGPSV_ERROR_INVALID_USRCFG_SEEDPRES if InitSeedPresent parameter is invalid.XTRNGPSV_ERROR_NO_SEED_INSTANTIATE if no seed passed for DRNG mode.XTRNGPSV_ERROR_UNNECESSARY_PARAM_INSTANTIATE if seed passed for HRNG mode or if unnecessary seed related parameter passed for PTRNG mode.XTRNGPSV_ERROR_INVALID_USRCFG_DFDIS if DFDisable parameter is invalid.XTRNGPSV_ERROR_INVALID_USRCFG_DFLENMUL if DFLenMul parameter is invalid.XTRNGPSV_ERROR_USRCFG_CPY if error during copy of ConfigurValues structure.Other error codes from the called functions as defined in XTrngpsv_ErrorCodes.
References XTrngpsv_UsrCfg::DFDisable, XTrngpsv_UsrCfg::DFLenMul, XTrngpsv_UsrCfg::InitSeed, XTrngpsv_UsrCfg::InitSeedPresent, XTrngpsv_UsrCfg::Mode, XTrngpsv_UsrCfg::PersString, XTrngpsv_UsrCfg::PersStrPresent, XTrngpsv_UsrCfg::PredResistanceEn, XTrngpsv::RandBitBuf, XTrngpsv_UsrCfg::SeedLife, XTrngpsv::State, XTrngpsv::UsrCfg, XTRNGPSV_DRNG, XTRNGPSV_ERROR, XTRNGPSV_ERROR_INVALID_PARAM, XTRNGPSV_ERROR_INVALID_USRCFG_DFDIS, XTRNGPSV_ERROR_INVALID_USRCFG_DFLENMUL, XTRNGPSV_ERROR_INVALID_USRCFG_MODE, XTRNGPSV_ERROR_INVALID_USRCFG_PERSPRES, XTRNGPSV_ERROR_INVALID_USRCFG_PREDRES, XTRNGPSV_ERROR_INVALID_USRCFG_SEEDLIFE, XTRNGPSV_ERROR_INVALID_USRCFG_SEEDPRES, XTRNGPSV_ERROR_NO_SEED_INSTANTIATE, XTRNGPSV_ERROR_NOT_UNINSTANTIATED, XTRNGPSV_ERROR_UNNECESSARY_PARAM_INSTANTIATE, XTRNGPSV_ERROR_USRCFG_CPY, XTRNGPSV_FAILURE, XTRNGPSV_FALSE, XTRNGPSV_HEALTHY, XTRNGPSV_HRNG, XTRNGPSV_MAX_DFLENMUL, XTRNGPSV_MAX_SEEDLIFE, XTRNGPSV_MIN_DFLENMUL, XTRNGPSV_MIN_SEEDLIFE, XTRNGPSV_PTRNG, XTRNGPSV_SUCCESS, XTRNGPSV_TRUE, XTRNGPSV_UNINITIALIZED.
Referenced by XTrngpsv_RunHealthTest, XTrngpsv_RunKAT.
s32 XTrngpsv_Reseed(XTrngpsv *InstancePtr, const u8 *ExtSeedPtr, u32 DFLenMul)
This function reseeds the TRNG in DRNG, HRNG modes.
This function will be called by random number consuming application. This is just a wrapper function calling XTrng_ReseedInternal() which passes NULL as personalization string. InstancePtr is a pointer to the XTrngpsv instance to be worked on. ExtSeedPtr points to the byte array containing external seed. This shall be NULL for HRNG case. DFLenMul is DF Length multiplier used to determine number of bits on the input of the DF construct which is (DFLenMul + 1)*128 bits. This indicates the size of the seed pointed by ExtSeedPtr. This shall be 0 for Non-DF case. XTRNGPSV_SUCCESS if Reseed was successful.XTRNGPSV_ERROR_INVALID_PARAM if invalid parameter(s) passed to this function.XTRNGPSV_ERROR_INVALID_STATE if driver is not Healthy state before invoking this.XTRNGPSV_ERROR_SEED_INVALID_MODE if this is called in PTRNG mode.XTRNGPSV_ERROR_NO_SEED if no seed passed for DRNG mode.XTRNGPSV_ERROR_UNNECESSARY_PARAM if seed passed for non-DRNG mode.XTRNGPSV_ERROR_INVALID_RESEED_DFLENMUL if invalid DFLenMul parameter passed.XTRNGPSV_ERROR_SAME_SEED if same seed passed for both Instantiation and Reseed.Other error codes from the called functions as defined in XTrngpsv_ErrorCodes.
References XTrngpsv_UsrCfg::DFDisable, XTrngpsv::EntropySize, XTrngpsv_UsrCfg::InitSeed, XTrngpsv_UsrCfg::Mode, XTrngpsv::State, XTrngpsv::UsrCfg, XTRNGPSV_DRNG, XTRNGPSV_ERROR, XTRNGPSV_ERROR_INVALID_PARAM, XTRNGPSV_ERROR_INVALID_RESEED_DFLENMUL, XTRNGPSV_ERROR_INVALID_STATE, XTRNGPSV_ERROR_NO_SEED, XTRNGPSV_ERROR_SAME_SEED, XTRNGPSV_ERROR_SEED_INVALID_MODE, XTRNGPSV_ERROR_UNNECESSARY_PARAM, XTRNGPSV_FAILURE, XTRNGPSV_FALSE, XTRNGPSV_HEALTHY, XTRNGPSV_HRNG, XTRNGPSV_MAX_DFLENMUL, XTRNGPSV_SEED_LEN_BYTES, XTRNGPSV_SUCCESS, XTRNGPSV_TRUE.
Referenced by XTrngpsv_RunKAT.
s32 XTrngpsv_Generate(XTrngpsv *InstancePtr, u8 *RandBufPtr, u32 RandBufSize, u8 PredResistanceEn)
This the function which actually generates and provides random bits to the caller.
Number of bits generated per call is 256 bits. If user needs more bits of random data, this API can be called multiple times accordingly. InstancePtr is a pointer to the XTrngpsv instance to be worked on. RandBufPtr points to memory address where generated random data will be stored and the memory address should be word aligned. RandBufSize is size of the buffer to which RandBufPtr points to and it should be always greater than or equal to XTRNGPSV_SEC_STRENGTH_BYTES. PredResistanceEn is the flag that controls Generate level Prediction Resistance. When enabled, it mandates fresh seed for every Generate operation. XTRNGPSV_SUCCESS if Random number generation was successful.XTRNGPSV_ERROR_INVALID_PARAM if invalid parameter(s) passed to this function.XTRNGPSV_ERROR_INVALID_STATE if driver is not Healthy state before invoking this.XTRNGPSV_ERROR_INSUFFICIENT_RANDBUF if length of Buffer passed is insufficient.XTRNGPSV_ERROR_INVALID_GEN_PREDRES if Prediction Resistance set for PTRNG mode.XTRNGPSV_ERROR_PREDRES_MISMATCH if Pred Resistance not set during Instantiate but set now.XTRNGPSV_ERROR_RESEEDING_REQUIRED if SeedLife elapsed.XTRNGPSV_ERROR_RESEED_REQD_PREDRES if seed is consumed and has Pred Resistance.XTRNGPSV_ERROR_GLITCH if error caused due to glitch conditions.Other error codes from the called functions as defined in XTrngpsv_ErrorCodes.
References XTrngpsv_Config::BaseAddress, BYTES_PER_BLOCK, XTrngpsv::Config, DF_RAND, XTrngpsv_UsrCfg::DFDisable, XTrngpsv::DFInput, XTrngpsv_UsrCfg::DFLenMul, XTrngpsv_Stats::ElapsedSeedLife, XTrngpsv_DFInput::EntropyData, XTrngpsv::EntropySize, XTrngpsv_UsrCfg::Mode, XTrngpsv_UsrCfg::PredResistanceEn, PRNGMODE_GEN, XTrngpsv_Stats::RandBytes, XTrngpsv_Stats::RandBytesReseed, XTrngpsv_UsrCfg::SeedLife, XTrngpsv::State, TRNG_CTRL, TRNG_CTRL_EUMODE_MASK, TRNG_CTRL_PRNGXS_MASK, TRNG_CTRL_TRSSEN_MASK, TRNG_OSC_EN, TRNG_OSC_EN_VAL_MASK, XTrngpsv::TrngStats, XTrngpsv::UsrCfg, XTRNGPSV_CATASTROPHIC, XTrngpsv_DF, XTRNGPSV_DRNG, XTRNGPSV_ERROR, XTRNGPSV_ERROR_GLITCH, XTRNGPSV_ERROR_INSUFFICIENT_RANDBUF, XTRNGPSV_ERROR_INVALID_GEN_PREDRES, XTRNGPSV_ERROR_INVALID_PARAM, XTRNGPSV_ERROR_INVALID_RANDBUF_ADDR, XTRNGPSV_ERROR_INVALID_STATE, XTRNGPSV_ERROR_PREDRES_MISMATCH, XTRNGPSV_ERROR_RESEED_REQD_PREDRES, XTRNGPSV_ERROR_RESEEDING_REQUIRED, XTRNGPSV_FAILURE, XTRNGPSV_FALSE, XTRNGPSV_HEALTHY, XTRNGPSV_HRNG, XTRNGPSV_PTRNG, XTRNGPSV_SEC_STRENGTH_BYTES, XTRNGPSV_SUCCESS, XTRNGPSV_TRUE, XTRNGPSV_WORD_ALIGN_MASK.
Referenced by XTrngpsv_RunKAT.
s32 XTrngpsv_Uninstantiate(XTrngpsv *InstancePtr)
This function is used to put the TRNG in reset state, and clear the instance data including configuration, status.
InstancePtr is a pointer to the XTrngpsv instance to be worked on. XTRNGPSV_SUCCESS if Uninstantiation was successful.XTRNGPSV_ERROR_INVALID_PARAM if invalid parameter(s) passed to this function.XTRNGPSV_ERROR_INVALID_STATE if driver is not Healthy state before invoking this.XTRNGPSV_ERROR_GLITCH if error caused due to glitch conditions.
References XTrngpsv::Config, XTrngpsv::State, TRNG_EXT_SEED_0, TRNG_PER_STRNG_0, XTRNGPSV_ERROR, XTRNGPSV_ERROR_INVALID_PARAM, XTRNGPSV_ERROR_INVALID_STATE, XTRNGPSV_FAILURE, XTRNGPSV_PERS_STR_LEN, XTRNGPSV_SEED_LEN, XTRNGPSV_SUCCESS, XTRNGPSV_UNINITIALIZED.
Referenced by XTrngpsv_RunHealthTest, XTrngpsv_RunKAT.
s32 XTrngpsv_DF(XTrngpsv *InstancePtr, u8 *DFOutput, u32 DF_Flag, const u8 *PersStrPtr)
This function implements the Derivative Function (per NIST SP80090A) by distilling the entropy available in a lot of bits at its input (DFInput) into a smaller number of bits on the output (DFOutput), thus bringing entropy per bit to 1.
Actual length of input to DF need to be provided to the core (block cipher)algorithm for DF, based on if personalization string is present or not and based on actual length of input entropy, the buffer needs to adjusted by pushing all the unused bytes to the end. The Block Cipher algorithm invoked here is as per sections 10.3.2 and 10.3.3 of the NIST.SP.800-90Ar1 document. InstancePtr is a pointer to the XTrngpsv instance to be worked on. DFOutput points to the buffer to which output of DF operation is stored. DF_Flag is the flag used to indicate if this function is used to generate seed or random number (used in the PTRNG mode) PersStrPtr is the pointer to Personalization string. If no personalization string is present, it should be NULL. XTRNGPSV_SUCCESS if successful.XTRNGPSV_ERROR_DF_CPY if MemCpy failureXTRNGPSV_ERROR_GLITCH if error caused due to glitch conditions.
References DF_KEY_LEN, DF_PAD_VAL, DF_SEED, XTrngpsv::DFInput, XTrngpsv::DFOutput, XTrngpsv_DFInput::EntropyData, XTrngpsv::EntropySize, XTrngpsv_DFInput::InputLen, XTrngpsv_DFInput::IvCounter, XTrngpsv_DFInput::PadData, XTrngpsv_DFInput::PersString, XTrngpsv_DFInput::PostDfLen, XTRNGPSV_ERROR_DF_CPY, XTRNGPSV_ERROR_DF_MEMMOVE, XTRNGPSV_ERROR_DF_MEMSET, XTRNGPSV_ERROR_DF_SETUP_KEY_FAILED, XTRNGPSV_ERROR_GLITCH, XTRNGPSV_FAILURE, XTRNGPSV_GEN_LEN_BYTES, XTRNGPSV_PERS_STR_LEN_BYTES, XTRNGPSV_SEC_STRENGTH_BYTES, XTRNGPSV_SEED_LEN_BYTES, XTRNGPSV_SUCCESS, XTRNGPSV_SWAP_ENDIAN.
Referenced by XTrngpsv_Generate.
s32 XTrngpsv_RunKAT(XTrngpsv *InstancePtr)
KAT can be run at startup and on demand.
256 bits are generated and ignored. This test can be run when the TRNG is configured in DRNG and HRNG modes. For HRNG mode too, tests should be run in DRNG mode. If KAT fails, driver has to be put in Error state. InstancePtr is a pointer to the XTrngpsv instance to be worked on. XTRNGPSV_SUCCESS if KAT is successful.XTRNGPSV_ERROR_INVALID_PARAM if invalid parameter passed to this function.XTRNGPSV_ERROR_USRCFG_CPY_KAT if copy of seed/personalization string failed.XTRNGPSV_ERROR_KAT_MISMATCH if KAT result doesn't match with expected output (OR) other error codes from the called functions as defined in XTrngpsv_ErrorCodes.
References BYTES_PER_BLOCK, XTrngpsv_UsrCfg::DFDisable, XTrngpsv_UsrCfg::DFLenMul, XTrngpsv_UsrCfg::InitSeed, XTrngpsv_UsrCfg::InitSeedPresent, XTrngpsv_UsrCfg::Mode, XTrngpsv_UsrCfg::PersString, XTrngpsv_UsrCfg::PersStrPresent, XTrngpsv_UsrCfg::PredResistanceEn, XTrngpsv_UsrCfg::SeedLife, XTrngpsv::State, XTRNGPSV_DRNG, XTRNGPSV_ERROR, XTRNGPSV_ERROR_INVALID_PARAM, XTRNGPSV_ERROR_KAT_MISMATCH, XTRNGPSV_ERROR_USRCFG_CPY_KAT, XTRNGPSV_FAILURE, XTRNGPSV_FALSE, XTRNGPSV_GEN_LEN_BYTES, XTrngpsv_Generate, XTrngpsv_Instantiate, XTRNGPSV_PERS_STR_LEN_BYTES, XTrngpsv_Reseed, XTRNGPSV_SEED_LEN_BYTES, XTRNGPSV_SUCCESS, XTRNGPSV_TRUE, XTrngpsv_Uninstantiate.
s32 XTrngpsv_RunHealthTest(XTrngpsv *InstancePtr)
Health tests are entropy tests and hence should be run when the configured mode is of PTRNG or HRNG mode.
1024 bits of entropy data to be generated and the CTF flag to be monitored. TRNG configured in HRNG + DF serves this purpose ((7+1)*128 = 1024 bits). Since this flag is monitored for every reseed, no need to monitor CTF explicitly in this test. This API is to be called at startup, after instantiation (and reseeding). Even for PTRNG mode, for this test, mode to be configured as HRNG (as there is no reseed operation involved in PTRNG mode). InstancePtr is a pointer to the XTrngpsv instance to be worked on. XTRNGPSV_SUCCESS if Health tests are successfully run.XTRNGPSV_ERROR_INVALID_PARAM if invalid parameter passed to this function (OR) other error codes from the called functions as defined in XTrngpsv_ErrorCodes.
References XTrngpsv_UsrCfg::DFDisable, XTrngpsv_UsrCfg::DFLenMul, HEALTH_TEST_SEEDLIFE, XTrngpsv_UsrCfg::InitSeedPresent, XTrngpsv_UsrCfg::Mode, XTrngpsv_UsrCfg::PersStrPresent, XTrngpsv_UsrCfg::PredResistanceEn, XTrngpsv_UsrCfg::SeedLife, XTrngpsv::State, XTRNGPSV_ERROR, XTRNGPSV_ERROR_INVALID_PARAM, XTRNGPSV_FAILURE, XTRNGPSV_FALSE, XTRNGPSV_HRNG, XTrngpsv_Instantiate, XTRNGPSV_SUCCESS, XTrngpsv_Uninstantiate.