xtrngpsv.c
XTRNGPSV_BURST_SIZE
QCNT of 4 * 4 bytes (reg width)= 16 bytes.
XTRNGPSV_NUM_INIT_REGS
No.
of SEED and PERS STRING registers each
XTRNGPSV_BYTES_PER_REG
Number of bytes register (i.e.
32/8)
XTRNGPSV_ENTROPY_SEED_LEN_BYTES
Entropy SEED length in terms of security strength.
XTRNGPSV_SEC_STRENGTH_SHIFT
Shift value in terms of security strength.
XTRNGPSV_MAX_QCNT_MASK
Mask value for maximum QCNT (i.e 4U << 9U)
XTRNGPSV_WORD_ALIGN_MASK
Mask to check whether the address is word aligned.
Referenced by XTrngpsv_Generate.
XTRNGPSV_RESEED_TIMEOUT
Reseed timeout in micro-seconds.
XTRNGPSV_GENERATE_TIMEOUT
Generate timeout in micro-seconds.
PRNGMODE_RESEED
PRNG in Reseed mode.
PRNGMODE_GEN
PRNG in Generate mode.
Referenced by XTrngpsv_Generate.
XTRNGPSV_MIN_SEEDLIFE
Minimum seed life.
Referenced by XTrngpsv_Instantiate.
XTRNGPSV_MAX_SEEDLIFE
Maximum seed life 2^^48.
Referenced by XTrngpsv_Instantiate.
XTRNGPSV_MIN_DFLENMUL
Minimum DF Length Multiplier.
This assumes additional multiplier of 1 for nonce
Referenced by XTrngpsv_Instantiate.
XTRNGPSV_MAX_DFLENMUL
Maximum DF Length Multiplier.
Referenced by XTrngpsv_Instantiate, XTrngpsv_Reseed.
ALL_A_PATTERN_32
Pattern of 10101010...
ALL_5_PATTERN_32
Pattern of 01010101...
RESET_DELAY
Delay used in Reset operations.
static void XTrngpsv_Reset(const XTrngpsv *InstancePtr)
This API is used to reset the TRNG.
There are two resets involved (RESET register and TRNG_CTRL.PRNGsrst), both of which are asserted and de-asserted again after a delay. InstancePtr is a pointer to the XTrngpsv instance to be worked on.
static void XTrngpsv_SoftReset(const XTrngpsv *InstancePtr)
This API is used to issue soft reset the TRNG (TRNG_CTRL.PRNGsrst)
InstancePtr is a pointer to the XTrngpsv instance to be worked on.
static void XTrngpsv_HoldReset(const XTrngpsv *InstancePtr)
This API is used to keep the TRNG in reset state.
There are two resets involved (RESET register and TRNG_CTRL.PRNGsrst), both of which are asserted. InstancePtr is a pointer to the XTrngpsv instance to be worked on.
static s32 XTrngpsv_CollectRandData(XTrngpsv *InstancePtr, u32 *RandGenBuf, u32 NumOfRandBytes)
This is the function in which actually generation of random data is started and collected random data is returned to calling function.
InstancePtr is a pointer to the XTrngpsv instance to be worked on. RandGenBuf points to the address of the buffer in to which the random data generated has to be copied. NumOfRandBytes is number of bytes to be collected. XTRNGPSV_SUCCESS if Random number collection was successful.XTRNGPSV_ERROR_GENERATE_TIMEOUT if timeout occurred waiting for QCNT to become 4.XTRNGPSV_ERROR_CATASTROPHIC_DTF if DTF bit asserted in STATUS register.XTRNGPSV_ERROR_CATASTROPHIC_DTF_SW if DTF error detected in software.XTRNGPSV_ERROR_GLITCH if error caused due to glitch conditions. In case of entropy data collection mode this function utilizes the additional 4 words of EntropyData buffer when NumOfRandBytes is not 32byte aligned.
static s32 XTrngpsv_ReseedInternal(XTrngpsv *InstancePtr, const u8 *ExtSeedPtr, u8 *PersStrPtr, u32 DFLenMul)
This is the actual reseed function.
This function will be called by XTrng_Reseed and during Generate operation. Instantiation too calls this function. InstancePtr is a pointer to the XTrngpsv instance to be worked on. ExtSeedPtr points to the byte array containing external seed. This shall be NULL for HRNG case. PersStrPtr points to Personalization string (which is recommended) in addition to seed. This is needed only during Instantiation. DFLenMul is DF Length multiplier used to determine number of bits on the input of the DF construct which is (DFLenMul +1)*128 bits. This indicates the size of the seed pointed by ExtSeedPtr. This shall be 0 for Non-DF case. XTRNGPSV_SUCCESS if Reseed was successful.XTRNGPSV_ERROR_CERTF_SW_A5_PATTERN if entropy source outputs all 5s or all As.XTRNGPSV_ERROR_CPY_RESEED if error encountered during seed copy.XTRNGPSV_ERROR_RESEED_TIMEOUT if timeout occurred waiting for done of reseeding.XTRNGPSV_ERROR_CERTF if CTF flag is set in STATUS register.XTRNGPSV_ERROR_GLITCH if error caused due to glitch conditions.Other error codes from the called functions as defined in XTrngpsv_ErrorCodes.
static s32 XTrngpsv_WriteRegs(const XTrngpsv *InstancePtr, u32 StartRegOffset, u32 NumRegs, const u8 *InitBuf)
Write to the register.
Write a byte array InitBuf as a sequence of words into an array of register locations starting with StartRegOffset. The first byte from InitBuf is stored in last byte of target register, the second byte to last but one byte of target register.. and so on. If InitBuf is NULL, the target registers are filled with all 0s. InstancePtr is a pointer to the XTrngpsv instance to be worked on StartRegOffset contains the offset from the base address of the device from where register writes to be done NumRegs is number of registers to be programmed InitBuf is the source of buffer from where data will be written to registers. XTRNGPSV_SUCCESS if Write to Registers is successfulXTRNGPSV_ERROR_GLITCH if write and read values are differentXTRNGPSV_FAILURE if any other failure
static s32 XTrngpsv_CheckSeedPattern(u8 *EntropyData, u32 EntropyLength)
Checks the value of seed against certain patterns, which are invalid.
EntropyData is a pointer to the data from where data has to be checked against. EntropyLength is number of bytes for which patterns has to be checked. None. 0xAAAAAAAA and 0x55555555 are treated as invalid.
static u32 XTrngpsv_ReadReg(UINTPTR BaseAddress, u32 RegOffset)
Read from the register.
BaseAddress contains the base address of the device. RegOffset contains the offset from the base address of the device. The value read from the register.
static void XTrngpsv_WriteReg(UINTPTR BaseAddress, u32 RegOffset, u32 RegValue)
Write to the register.
BaseAddress contains the base address of the device. RegOffset contains the offset from the base address of the device. RegValue is the value to be written to the register.
static void XTrngpsv_RMW32(UINTPTR BaseAddress, u32 RegOffset, u32 RegMask, u32 RegValue)
Read-Modify-Write register.
BaseAddress contains the base address of the device. RegOffset contains the offset from the base address of the device. RegMask indicates the bits to be modified. RegValue is the value to be written to the register.
static s32 XTrngpsv_WaitForEvent(UINTPTR BaseAddr, u32 RegOffset, u32 EventMask, u32 Event, u32 Timeout)
Waits for an event to occur for a certain timeout duration.
BaseAddr is address of register to be checked for event(s) occurrence. RegOffset is offset of register from base address. EventMask is mask indicating event(s) to be checked. Event is specific event(s) value to be checked. Timeout is max number of microseconds to wait for an event(s). XTRNGPSV_SUCCESS - On occurrence of the event(s). XTRNGPSV_FAILURE - Event did not occur before counter reaches 0.
static void XTrngpsv_ChangeEndianness(u32 *SrcBuf)
This function changes the endianness of each word in source buffer.
SrcBuf points to the address of the buffer in which random data is stored.
static s32 XTrngpsv_CheckRandDataPattern(XTrngpsv *InstancePtr, u32 *RandBuf)
This function detects the back to back same burst pattern and stores the last burst in to the RandBitBuf buffer so that it can be compared with next generated burst.
InstancePtr is a pointer to the XTrngpsv instance to be worked on. RandBuf points to the address of the buffer in to which the random data generated has to be copied. XTRNGPSV_SUCCESS if Random pattern check was successful.XTRNGPSV_ERROR_CATASTROPHIC_DTF_SW if DTF error detected in software.
static s32 XTrngpsv_WaitForData(const XTrngpsv *InstancePtr)
This function waits for 4 words of data to be available in core output.
InstancePtr is a pointer to the XTrngpsv instance to be worked on XTRNGPSV_SUCCESS if event occurred.XTRNGPSV_FAILURE if timeout occurred.
static s32 XTrngpsv_WaitAndCollectData(const XTrngpsv *InstancePtr, u32 *RandBuf, u32 CtrlVal)
This function waits and collects 256-bit random data from core output.
InstancePtr is a pointer to the XTrngpsv instance to be worked on. RandBuf points to the address of the buffer in to which the random data generated has to be copied. CtrlVal contains the value that needs to be written in to TRNG_CTRL register i.e After collection of 256-bit data it will de-assert the generate bit when prediction resistance is enabled. XTRNGPSV_SUCCESS if random data is copied successfully.XTRNGPSV_ERROR_GENERATE_TIMEOUT if timeout occurred waiting for QCNT to become 4.
s32 XTrngpsv_CfgInitialize(XTrngpsv *InstancePtr, const XTrngpsv_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the TRNGPSV instance/driver.
This function must be called prior to using the driver. Initialization includes only setting up the device id and base address. All the remaining parameters of the Instance will be initialized in Instantiate function. InstancePtr is a pointer to the XTrngpsv instance to be worked on. CfgPtr points to the configuration structure associated with the TRNGPSV driver. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XTRNGPSV_SUCCESS if initialization was successful.XTRNGPSV_ERROR_INVALID_PARAM if invalid parameter passed to this function.
References XTRNGPSV_ERROR, XTRNGPSV_ERROR_INVALID_PARAM, XTRNGPSV_FAILURE, XTRNGPSV_SUCCESS, XTRNGPSV_UNINITIALIZED.
s32 XTrngpsv_Instantiate(XTrngpsv *InstancePtr, const XTrngpsv_UsrCfg *ConfigurValues)
This function further initializes i.e.
instantiates the TRNGPSV instance/driver with user configuration, resets the TRNG core and reseeds with initial seed and personalization string provided during Instantiation. Switching to a new state of attributes or changing any attributes (configured during Instantiation) requires UnInstantiation of the current instance and instantiation of a new instance. After successful Instantiation, State of the driver is changed to Healthy. InstancePtr is a pointer to the XTrngpsv instance to be worked on. ConfigurValues points to the user configuration structure associated with the TRNGPSV driver. XTRNGPSV_SUCCESS if Instantiation was successful.XTRNGPSV_ERROR_INVALID_PARAM if invalid parameter(s) passed to this function.XTRNGPSV_ERROR_NOT_UNINSTANTIATED if the driver is not uninstantiated earlier.XTRNGPSV_ERROR_INVALID_USRCFG_MODE if invalid Mode parameter.XTRNGPSV_ERROR_INVALID_USRCFG_SEEDLIFE if SeedLife parameter is invalidXTRNGPSV_ERROR_INVALID_USRCFG_PREDRES if invalid Prediction Resistance parameter.XTRNGPSV_ERROR_INVALID_USRCFG_PERSPRES if PersStrPresent parameter is invalid.XTRNGPSV_ERROR_INVALID_USRCFG_SEEDPRES if InitSeedPresent parameter is invalid.XTRNGPSV_ERROR_NO_SEED_INSTANTIATE if no seed passed for DRNG mode.XTRNGPSV_ERROR_UNNECESSARY_PARAM_INSTANTIATE if seed passed for HRNG mode or if unnecessary seed related parameter passed for PTRNG mode.XTRNGPSV_ERROR_INVALID_USRCFG_DFDIS if DFDisable parameter is invalid.XTRNGPSV_ERROR_INVALID_USRCFG_DFLENMUL if DFLenMul parameter is invalid.XTRNGPSV_ERROR_USRCFG_CPY if error during copy of ConfigurValues structure.Other error codes from the called functions as defined in XTrngpsv_ErrorCodes.
References XTrngpsv_UsrCfg::DFDisable, XTrngpsv_UsrCfg::DFLenMul, XTrngpsv_UsrCfg::InitSeed, XTrngpsv_UsrCfg::InitSeedPresent, XTrngpsv_UsrCfg::Mode, XTrngpsv_UsrCfg::PersString, XTrngpsv_UsrCfg::PersStrPresent, XTrngpsv_UsrCfg::PredResistanceEn, XTrngpsv::RandBitBuf, XTrngpsv_UsrCfg::SeedLife, XTrngpsv::State, XTrngpsv::UsrCfg, XTRNGPSV_DRNG, XTRNGPSV_ERROR, XTRNGPSV_ERROR_INVALID_PARAM, XTRNGPSV_ERROR_INVALID_USRCFG_DFDIS, XTRNGPSV_ERROR_INVALID_USRCFG_DFLENMUL, XTRNGPSV_ERROR_INVALID_USRCFG_MODE, XTRNGPSV_ERROR_INVALID_USRCFG_PERSPRES, XTRNGPSV_ERROR_INVALID_USRCFG_PREDRES, XTRNGPSV_ERROR_INVALID_USRCFG_SEEDLIFE, XTRNGPSV_ERROR_INVALID_USRCFG_SEEDPRES, XTRNGPSV_ERROR_NO_SEED_INSTANTIATE, XTRNGPSV_ERROR_NOT_UNINSTANTIATED, XTRNGPSV_ERROR_UNNECESSARY_PARAM_INSTANTIATE, XTRNGPSV_ERROR_USRCFG_CPY, XTRNGPSV_FAILURE, XTRNGPSV_FALSE, XTRNGPSV_HEALTHY, XTRNGPSV_HRNG, XTRNGPSV_MAX_DFLENMUL, XTRNGPSV_MAX_SEEDLIFE, XTRNGPSV_MIN_DFLENMUL, XTRNGPSV_MIN_SEEDLIFE, XTRNGPSV_PTRNG, XTRNGPSV_SUCCESS, XTRNGPSV_TRUE, XTRNGPSV_UNINITIALIZED.
Referenced by XTrngpsv_RunHealthTest, XTrngpsv_RunKAT.
s32 XTrngpsv_Reseed(XTrngpsv *InstancePtr, const u8 *ExtSeedPtr, u32 DFLenMul)
This function reseeds the TRNG in DRNG, HRNG modes.
This function will be called by random number consuming application. This is just a wrapper function calling XTrng_ReseedInternal() which passes NULL as personalization string. InstancePtr is a pointer to the XTrngpsv instance to be worked on. ExtSeedPtr points to the byte array containing external seed. This shall be NULL for HRNG case. DFLenMul is DF Length multiplier used to determine number of bits on the input of the DF construct which is (DFLenMul + 1)*128 bits. This indicates the size of the seed pointed by ExtSeedPtr. This shall be 0 for Non-DF case. XTRNGPSV_SUCCESS if Reseed was successful.XTRNGPSV_ERROR_INVALID_PARAM if invalid parameter(s) passed to this function.XTRNGPSV_ERROR_INVALID_STATE if driver is not Healthy state before invoking this.XTRNGPSV_ERROR_SEED_INVALID_MODE if this is called in PTRNG mode.XTRNGPSV_ERROR_NO_SEED if no seed passed for DRNG mode.XTRNGPSV_ERROR_UNNECESSARY_PARAM if seed passed for non-DRNG mode.XTRNGPSV_ERROR_INVALID_RESEED_DFLENMUL if invalid DFLenMul parameter passed.XTRNGPSV_ERROR_SAME_SEED if same seed passed for both Instantiation and Reseed.Other error codes from the called functions as defined in XTrngpsv_ErrorCodes.
References XTrngpsv_UsrCfg::DFDisable, XTrngpsv::EntropySize, XTrngpsv_UsrCfg::InitSeed, XTrngpsv_UsrCfg::Mode, XTrngpsv::State, XTrngpsv::UsrCfg, XTRNGPSV_DRNG, XTRNGPSV_ERROR, XTRNGPSV_ERROR_INVALID_PARAM, XTRNGPSV_ERROR_INVALID_RESEED_DFLENMUL, XTRNGPSV_ERROR_INVALID_STATE, XTRNGPSV_ERROR_NO_SEED, XTRNGPSV_ERROR_SAME_SEED, XTRNGPSV_ERROR_SEED_INVALID_MODE, XTRNGPSV_ERROR_UNNECESSARY_PARAM, XTRNGPSV_FAILURE, XTRNGPSV_FALSE, XTRNGPSV_HEALTHY, XTRNGPSV_HRNG, XTRNGPSV_MAX_DFLENMUL, XTRNGPSV_SEED_LEN_BYTES, XTRNGPSV_SUCCESS, XTRNGPSV_TRUE.
Referenced by XTrngpsv_RunKAT.
s32 XTrngpsv_Generate(XTrngpsv *InstancePtr, u8 *RandBufPtr, u32 RandBufSize, u8 PredResistanceEn)
This the function which actually generates and provides random bits to the caller.
Number of bits generated per call is 256 bits. If user needs more bits of random data, this API can be called multiple times accordingly. InstancePtr is a pointer to the XTrngpsv instance to be worked on. RandBufPtr points to memory address where generated random data will be stored and the memory address should be word aligned. RandBufSize is size of the buffer to which RandBufPtr points to and it should be always greater than or equal to XTRNGPSV_SEC_STRENGTH_BYTES. PredResistanceEn is the flag that controls Generate level Prediction Resistance. When enabled, it mandates fresh seed for every Generate operation. XTRNGPSV_SUCCESS if Random number generation was successful.XTRNGPSV_ERROR_INVALID_PARAM if invalid parameter(s) passed to this function.XTRNGPSV_ERROR_INVALID_STATE if driver is not Healthy state before invoking this.XTRNGPSV_ERROR_INSUFFICIENT_RANDBUF if length of Buffer passed is insufficient.XTRNGPSV_ERROR_INVALID_GEN_PREDRES if Prediction Resistance set for PTRNG mode.XTRNGPSV_ERROR_PREDRES_MISMATCH if Pred Resistance not set during Instantiate but set now.XTRNGPSV_ERROR_RESEEDING_REQUIRED if SeedLife elapsed.XTRNGPSV_ERROR_RESEED_REQD_PREDRES if seed is consumed and has Pred Resistance.XTRNGPSV_ERROR_GLITCH if error caused due to glitch conditions.Other error codes from the called functions as defined in XTrngpsv_ErrorCodes.
References XTrngpsv_Config::BaseAddress, BYTES_PER_BLOCK, XTrngpsv::Config, DF_RAND, XTrngpsv_UsrCfg::DFDisable, XTrngpsv::DFInput, XTrngpsv_UsrCfg::DFLenMul, XTrngpsv_Stats::ElapsedSeedLife, XTrngpsv_DFInput::EntropyData, XTrngpsv::EntropySize, XTrngpsv_UsrCfg::Mode, XTrngpsv_UsrCfg::PredResistanceEn, PRNGMODE_GEN, XTrngpsv_Stats::RandBytes, XTrngpsv_Stats::RandBytesReseed, XTrngpsv_UsrCfg::SeedLife, XTrngpsv::State, TRNG_CTRL, TRNG_CTRL_EUMODE_MASK, TRNG_CTRL_PRNGXS_MASK, TRNG_CTRL_TRSSEN_MASK, TRNG_OSC_EN, TRNG_OSC_EN_VAL_MASK, XTrngpsv::TrngStats, XTrngpsv::UsrCfg, XTRNGPSV_CATASTROPHIC, XTrngpsv_DF, XTRNGPSV_DRNG, XTRNGPSV_ERROR, XTRNGPSV_ERROR_GLITCH, XTRNGPSV_ERROR_INSUFFICIENT_RANDBUF, XTRNGPSV_ERROR_INVALID_GEN_PREDRES, XTRNGPSV_ERROR_INVALID_PARAM, XTRNGPSV_ERROR_INVALID_RANDBUF_ADDR, XTRNGPSV_ERROR_INVALID_STATE, XTRNGPSV_ERROR_PREDRES_MISMATCH, XTRNGPSV_ERROR_RESEED_REQD_PREDRES, XTRNGPSV_ERROR_RESEEDING_REQUIRED, XTRNGPSV_FAILURE, XTRNGPSV_FALSE, XTRNGPSV_HEALTHY, XTRNGPSV_HRNG, XTRNGPSV_PTRNG, XTRNGPSV_SEC_STRENGTH_BYTES, XTRNGPSV_SUCCESS, XTRNGPSV_TRUE, XTRNGPSV_WORD_ALIGN_MASK.
Referenced by XTrngpsv_RunKAT.
s32 XTrngpsv_Uninstantiate(XTrngpsv *InstancePtr)
This function is used to put the TRNG in reset state, and clear the instance data including configuration, status.
InstancePtr is a pointer to the XTrngpsv instance to be worked on. XTRNGPSV_SUCCESS if Uninstantiation was successful.XTRNGPSV_ERROR_INVALID_PARAM if invalid parameter(s) passed to this function.XTRNGPSV_ERROR_INVALID_STATE if driver is not Healthy state before invoking this.XTRNGPSV_ERROR_GLITCH if error caused due to glitch conditions.
References XTrngpsv::Config, XTrngpsv::State, TRNG_EXT_SEED_0, TRNG_PER_STRNG_0, XTRNGPSV_ERROR, XTRNGPSV_ERROR_INVALID_PARAM, XTRNGPSV_ERROR_INVALID_STATE, XTRNGPSV_FAILURE, XTRNGPSV_PERS_STR_LEN, XTRNGPSV_SEED_LEN, XTRNGPSV_SUCCESS, XTRNGPSV_UNINITIALIZED.
Referenced by XTrngpsv_RunHealthTest, XTrngpsv_RunKAT.