intc
XIN_SVC_SGL_ISR_OPTION
XIN_SVC_SGL_ISR_OPTION Service the highest priority pending interrupt and then return. XIN_SVC_ALL_ISRS_OPTION Service all of the pending interrupts and then return.
Referenced by XIntc_DeviceInterruptHandler, XIntc_Initialize, XIntc_SetOptions.
XIN_SVC_ALL_ISRS_OPTION
XIN_SIMULATION_MODE
Simulation only mode, no hardware interrupts recognized.
Referenced by SetUpInterruptSystem, XIntc_Start.
XIN_REAL_MODE
Real mode, no simulation allowed, hardware interrupts recognized.
Referenced by IntcInterruptSetup, XIntc_Start.
XIN_INTC_NOCASCADE
XIN_INTC_PRIMARY
XIN_INTC_SECONDARY
XIN_INTC_LAST
XIN_CONTROLLER_MAX_INTRS
XINTC_STANDARD_VECTOR_ADDRESS_WIDTH
XIN_CASCADE_IRQ_MASK
Bitmask for the cascade interrupt input (bit 31) used by PRIMARY and SECONDARY controllers to chain to the next controller in cascade mode.
Referenced by XIntc_Enable.
XINTC_MAX_CASCADE_CONTROLLERS
Maximum number of interrupt controllers that can be daisy-chained together in cascade mode.
Limited to 8 because the driver API uses u8 for global interrupt IDs (max 255), and each controller owns 32 interrupt positions (8 * 32 = 256).
Referenced by XIntc_Enable.
XINTC_INTR_PARENT_MASK
Mask used to extract the parent controller base address from IntrParent by clearing the LSB which encodes the parent type (GIC vs INTC).
XINTC_NO_PARENT
Sentinel value indicating that an interrupt controller has no parent controller (i.e.
it is the root of the interrupt hierarchy).
typedef void(* XFastInterruptHandler)(void))(void)
u32 XIntc_BitPosMask[XIN_CONTROLLER_MAX_INTRS][XIN_CONTROLLER_MAX_INTRS]
XIntc_Config XIntc_ConfigTable[][]
This table contains configuration information for each intc device in the system.
The XIntc driver must know when to acknowledge the interrupt. The entry which specifies this as a bit mask where each bit corresponds to a specific interrupt. A bit set indicates to ack it before servicing it. Generally, acknowledge before service is used when the interrupt signal is edge-sensitive, and after when the signal is level-sensitive.Refer to the XIntc_Config data structure in xintc.h for details on how this table should be initialized.
Referenced by LookupConfigByBaseAddress, XIntc_DeviceInterruptHandler, XIntc_GetPrimaryController, XIntc_LookupConfig, XIntc_SetIntrSvcOption, XIntc_SetOptions, XIntc_Start.
XIntc_Config XIntc_ConfigTable[XPAR_XINTC_NUM_INSTANCES][XPAR_XINTC_NUM_INSTANCES]
This table contains configuration information for each intc device in the system.
The XIntc driver must know when to acknowledge the interrupt. The entry which specifies this as a bit mask where each bit corresponds to a specific interrupt. A bit set indicates to ack it before servicing it. Generally, acknowledge before service is used when the interrupt signal is edge-sensitive, and after when the signal is level-sensitive.Refer to the XIntc_Config data structure in xintc.h for details on how this table should be initialized.
Referenced by LookupConfigByBaseAddress, XIntc_DeviceInterruptHandler, XIntc_GetPrimaryController, XIntc_LookupConfig, XIntc_SetIntrSvcOption, XIntc_SetOptions, XIntc_Start.
u32 XIntc_BitPosMask[][]
XIntc_Config XIntc_ConfigTable[][]
This table contains configuration information for each intc device in the system.
The XIntc driver must know when to acknowledge the interrupt. The entry which specifies this as a bit mask where each bit corresponds to a specific interrupt. A bit set indicates to ack it before servicing it. Generally, acknowledge before service is used when the interrupt signal is edge-sensitive, and after when the signal is level-sensitive.Refer to the XIntc_Config data structure in xintc.h for details on how this table should be initialized.
static void StubHandler(void *CallBackRef)
A stub for the asynchronous callback.
The stub is here in case the upper layers forget to set the handler. CallBackRef is a pointer to the upper layer callback reference None. None.
static void XIntc_InitializeSlaves(XIntc *InstancePtr)
Initializes Slave controllers in Cascade mode.
The initialization entails: Initial vector table with stub function callsAll interrupt sources are disabled for last controller.All interrupt sources are disabled except sources to 31 pin of primary and secondary controllersInterrupt outputs are disabled InstancePtr is a pointer to the XIntc instance to be worked on. None None.
static XIntc_Config * XIntc_FindControllerByAddr(UINTPTR BaseAddr)
Find controller by base address (used for parent lookup in SDT cascade mode).
BaseAddr Base address to search for (LSB may be set for encoding) Pointer to controller config, or NULL if not found
static XIntc_Config * XIntc_FindControllerForId(u8 Id, u8 *LocalId)
Find the controller that owns an interrupt ID and return local interrupt number.
In SDT mode, builds cascade chain via BFS using interrupt-parent links. In non-SDT mode, uses sequential config table order. Id Global interrupt ID (0-N across all controllers) LocalId Output parameter for local interrupt ID (0-31) on found controller Pointer to controller config that owns this interrupt, or NULL if not found
XIntc_Config * XIntc_GetPrimaryController(void)
Find the PRIMARY controller in the config table.
Pointer to primary controller config, or NULL if not found
References XIntc_ConfigTable.
int XIntc_Initialize(XIntc *InstancePtr, UINTPTR BaseAddr)
Initialize a specific interrupt controller instance/driver.
The initialization entails: - Initialize fields of the XIntc structure - Initial vector table with stub function calls - All interrupt sources are disabled - Interrupt output is disabled InstancePtr is a pointer to the XIntc instance to be worked on. BaseAddr is the base address of the device XST_SUCCESS if initialization was successfulXST_DEVICE_IS_STARTED if the device has already been startedXST_DEVICE_NOT_FOUND if device configuration information was not found for a device with the supplied device ID/BaseAddress. In Cascade mode this function calls XIntc_InitializeSlaves to initialize Slave Interrupt controllers. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XIntc_Config::BaseAddress, XIntc::BaseAddress, XIntc::CfgPtr, XIntc_Config::FastIntr, XIntc_Config::HandlerTable, XIntc_Config::IntcType, XIntc::IsReady, XIntc::IsStarted, XIntc_Config::NumberofIntrs, XIntc_Config::NumberofSwIntrs, XIntc_Config::Options, XIntc_Config::VectorAddrWidth, XIN_SVC_SGL_ISR_OPTION, XIntc_LookupConfig.
Referenced by IntcExample, IntcInterruptSetup, IntcSelfTestExample.
int XIntc_Start(XIntc *InstancePtr, u8 Mode)
Starts the interrupt controller by enabling the output from the controller to the processor.
Interrupts may be generated by the interrupt controller after this function is called.It is necessary for the caller to connect the interrupt handler of this component to the proper interrupt source. This function also starts Slave controllers in Cascade mode. InstancePtr is a pointer to the XIntc instance to be worked on. Mode determines if software is allowed to simulate interrupts or real interrupts are allowed to occur. Note that these modes are mutually exclusive. The interrupt controller hardware resets in a mode that allows software to simulate interrupts until this mode is exited. It cannot be reentered once it has been exited. One of the following values should be used for the mode. XIN_SIMULATION_MODE enables simulation of interrupts onlyXIN_REAL_MODE enables hardware interrupts only XST_SUCCESS if the device was started successfullyXST_FAILURE if simulation mode was specified and it could not be set because real mode has already been entered. Must be called after XIntc initialization is completed.
References XIntc::BaseAddress, XIntc::CfgPtr, XIntc_Config::IntcType, XIntc::IsReady, XIntc::IsStarted, XIN_REAL_MODE, XIN_SIMULATION_MODE, XIntc_ConfigTable.
Referenced by IntcInterruptSetup, SetUpInterruptSystem.
void XIntc_Stop(XIntc *InstancePtr)
Stops the interrupt controller by disabling the output from the controller so that no interrupts will be caused by the interrupt controller.
InstancePtr is a pointer to the XIntc instance to be worked on. None. None.
References XIntc::BaseAddress, XIntc::IsReady, XIntc::IsStarted.
int XIntc_Connect(XIntc *InstancePtr, u8 Id, XInterruptHandler Handler, void *CallBackRef)
Makes the connection between the Id of the interrupt source and the associated handler that is to run when the interrupt is recognized.
The argument provided in this call as the Callbackref is used as the argument for the handler when it is called. In Cascade mode, connects handler to Slave controller handler table depending on the interrupt Id. InstancePtr is a pointer to the XIntc instance to be worked on. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_INTC_MAX_NUM_INTR_INPUTS - 1 with 0 being the highest priority interrupt. Handler to the handler for that interrupt. CallBackRef is the callback reference, usually the instance pointer of the connecting driver. - XST_SUCCESS if the handler was connected correctly. WARNING: The handler provided as an argument will overwrite any handler that was previously connected.
References XIntc::CfgPtr, XIntc_Config::HandlerTable, XIntc::IsReady.
Referenced by SetUpInterruptSystem.
void XIntc_Disconnect(XIntc *InstancePtr, u8 Id)
Updates the interrupt table with the Null Handler and NULL arguments at the location pointed at by the Id.
This effectively disconnects that interrupt source from any handler. The interrupt is disabled also. In Cascade mode, disconnects handler from Slave controller handler table depending on the interrupt Id. InstancePtr is a pointer to the XIntc instance to be worked on. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_INTC_MAX_NUM_INTR_INPUTS - 1 with 0 being the highest priority interrupt. None. None.
References XIntc_Config::BaseAddress, XIntc::BaseAddress, XIntc::CfgPtr, XIntc_Config::HandlerTable, XIntc::IsReady.
void XIntc_Enable(XIntc *InstancePtr, u8 Id)
Enables the interrupt source provided as the argument Id.
Any pending interrupt condition for the specified Id will occur after this function is called. In Cascade mode, enables corresponding interrupt of Slave controllers depending on the Id. InstancePtr is a pointer to the XIntc instance to be worked on. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_INTC_MAX_NUM_INTR_INPUTS - 1 with 0 being the highest priority interrupt. None. None.
References XIntc_Config::BaseAddress, XIntc::BaseAddress, XIntc::CfgPtr, XIntc_Config::IntcType, XIntc_Config::IntrParent, XIntc::IsReady, XIN_CASCADE_IRQ_MASK, XINTC_MAX_CASCADE_CONTROLLERS.
Referenced by SetUpInterruptSystem, XIntc_ConnectFastHandler, XIntc_SetNormalIntrMode.
void XIntc_Disable(XIntc *InstancePtr, u8 Id)
Disables the interrupt source provided as the argument Id such that the interrupt controller will not cause interrupts for the specified Id.
The interrupt controller will continue to hold an interrupt condition for the Id, but will not cause an interrupt.In Cascade mode, disables corresponding interrupt of Slave controllers depending on the Id. InstancePtr is a pointer to the XIntc instance to be worked on. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_INTC_MAX_NUM_INTR_INPUTS - 1 with 0 being the highest priority interrupt. None. None.
References XIntc_Config::BaseAddress, XIntc::BaseAddress, XIntc::IsReady.
Referenced by XIntc_ConnectFastHandler, XIntc_SetNormalIntrMode.
void XIntc_Acknowledge(XIntc *InstancePtr, u8 Id)
Acknowledges the interrupt source provided as the argument Id.
When the interrupt is acknowledged, it causes the interrupt controller to clear its interrupt condition.In Cascade mode, acknowledges corresponding interrupt source of Slave controllers depending on the Id. InstancePtr is a pointer to the XIntc instance to be worked on. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_INTC_MAX_NUM_INTR_INPUTS - 1 with 0 being the highest priority interrupt. None. None.
References XIntc_Config::BaseAddress, XIntc::BaseAddress, XIntc::IsReady.
XIntc_Config * XIntc_LookupConfig(UINTPTR BaseAddr)
Looks up the device configuration based on the unique device ID/BaseAddress.
A table contains the configuration info for each device in the system. BaseAddr contains the base address of the device A pointer to the XIntc configuration structure for the specified device, or NULL if the device ID/BaseAddress was not found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XIntc_ConfigTable.
Referenced by XIntc_Initialize, XIntc_RegisterFastHandler, XIntc_RegisterHandler, XIntc_SetIntrSvcOption, XIntc_SetOptions, XIntc_SimulateIntr.
int XIntc_ConnectFastHandler(XIntc *InstancePtr, u8 Id, XFastInterruptHandler Handler)
Makes the connection between the Id of the interrupt source and the associated handler that is to run when the interrupt is recognized.In Cascade mode, connects handler to corresponding Slave controller IVAR/IVEAR register depending on the Id and sets all interrupt sources of the Slave controller as fast interrupts.
InstancePtr is a pointer to the XIntc instance to be worked on. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_INTC_MAX_NUM_INTR_INPUTS - 1 with 0 being the highest priority interrupt. Handler for specified interrupt id. It must be declared with "fast_interrupt" attribute. e.g. static void MyHandler(void) attribute ((fast_interrupt)); XST_SUCCESS Slave controllers in Cascade Mode should have all as Fast interrupts or Normal interrupts, mixed interrupts are not supported WARNING: The handler provided as an argument will overwrite any handler that was previously connected.
References XIntc_Config::BaseAddress, XIntc::BaseAddress, XIntc::CfgPtr, XIntc_Config::FastIntr, XIntc::IsReady, XIntc_Config::VectorAddrWidth, XIntc_Disable, XIntc_Enable.
void XIntc_SetNormalIntrMode(XIntc *InstancePtr, u8 Id)
Sets the normal interrupt mode for the specified interrupt in the Interrupt Mode Register.
In Cascade mode disconnects handler from corresponding Slave controller IVAR/IVEAR register depending on the Id and sets all interrupt sources of the Slave controller as normal interrupts. InstancePtr is a pointer to the XIntc instance to be worked on. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_INTC_MAX_NUM_INTR_INPUTS - 1 with 0 being the highest priority interrupt. None. Slave controllers in Cascade Mode should have all as Fast interrupts or Normal interrupts, mixed interrupts are not supported
References XIntc_Config::BaseAddress, XIntc::BaseAddress, XIntc::CfgPtr, XIntc_Config::FastIntr, XIntc::IsReady, XIntc_Config::VectorAddrWidth, XIntc_Disable, XIntc_Enable.
int XIntc_TriggerSwIntr(XIntc *InstancePtr, u8 Id)
Allows software to trigger software interrupt.
This function will only be successful when the interrupt controller has been configured with software interrupt in HW design InstancePtr is a pointer to the XIntc instance to be worked on. Id is the interrupt ID to be triggered XST_SUCCESS if successful XST_FAILURE if the instance pointer is invalid if interrupt id does not belongs to software interrupt HW design must have software interrupts and interrupt id passed should be of software interrupt type. Interrupt id's for software interrupts for specific HW design can be found in xparameters.h file.
References XIntc_Config::BaseAddress, XIntc::BaseAddress, XIntc::IsReady.
XIntc_Config * LookupConfigByBaseAddress(UINTPTR BaseAddress)
Looks up the device configuration based on the base address of the device.
A table contains the configuration info for each device in the system. BaseAddress is the unique identifier for a device. A pointer to the configuration structure for the specified device, or NULL if the device was not found.None.
References XIntc_ConfigTable.
Referenced by IntcLowLevelExample, XIntc_DeviceInterruptHandler, XIntc_RegisterHandler, XIntc_SetIntrSvcOption.
void XIntc_VoidInterruptHandler(void)
void XIntc_InterruptHandler(XIntc *InstancePtr)
Interrupt handler for the driver used when there can be no argument passed to the handler.
This function is provided mostly for backward compatibility. The user should use XIntc_DeviceInterruptHandler(), defined in xintc_l.c, if possible.The user must connect this function to the interrupt system such that it is called whenever the devices which are connected to it cause an interrupt.None. The constant XPAR_INTC_SINGLE_DEVICE_ID must be defined for this handler to be included in the driver compilation.The interrupt handler for the driver. This function is provided mostly for backward compatibility. The user should use XIntc_DeviceInterruptHandler(), defined in xintc_l.c when possible and pass the device ID of the interrupt controller device as its argument.The user must connect this function to the interrupt system such that it is called whenever the devices which are connected to it cause an interrupt. InstancePtr is a pointer to the XIntc instance to be worked on. None. None.
References XIntc_Config::BaseAddress, XIntc::CfgPtr, XIntc_DeviceInterruptHandler.
Referenced by SetUpInterruptSystem.
int XIntc_SetOptions(XIntc *InstancePtr, u32 Options)
Set the options for the interrupt controller driver.
In Cascade mode same Option is set to Slave controllers. InstancePtr is a pointer to the XIntc instance to be worked on. Options to be set. The available options are described in xintc.h. XST_SUCCESS if the options were set successfullyXST_INVALID_PARAM if the specified option was not valid None.
References XIntc::CfgPtr, XIntc_Config::IntcType, XIntc::IsReady, XIntc_Config::Options, XIN_SVC_SGL_ISR_OPTION, XIntc_ConfigTable, XIntc_LookupConfig.
u32 XIntc_GetOptions(XIntc *InstancePtr)
Return the currently set options.
InstancePtr is a pointer to the XIntc instance to be worked on. The currently set options. The options are described in xintc.h. None.
References XIntc::CfgPtr, XIntc::IsReady, XIntc_Config::Options.
int XIntc_SelfTest(XIntc *InstancePtr)
Run a self-test on the driver/device.
This is a destructive test.This involves forcing interrupts into the controller and verifying that they are recognized and can be acknowledged. This test will not succeed if the interrupt controller has been started in real mode such that interrupts cannot be forced. InstancePtr is a pointer to the XIntc instance to be worked on. XST_SUCCESS if self-test is successful.XST_INTC_FAIL_SELFTEST if the Interrupt controller fails the self-test. It will fail the self test if the device has previously been started in real mode. None.
References XIntc::BaseAddress, XIntc::IsReady.
Referenced by IntcExample, IntcInterruptSetup, IntcSelfTestExample.
int XIntc_SimulateIntr(XIntc *InstancePtr, u8 Id)
Allows software to simulate an interrupt in the interrupt controller.
This function will only be successful when the interrupt controller has been started in simulation mode. Once it has been started in real mode, interrupts cannot be simulated. A simulated interrupt allows the interrupt controller to be tested without any device to drive an interrupt input signal into it. In Cascade mode writes to ISR of appropriate Slave controller depending on Id. InstancePtr is a pointer to the XIntc instance to be worked on. Id is the interrupt ID for which to simulate an interrupt. XST_SUCCESS if successful XST_FAILURE if the interrupt could not be simulated because the interrupt controller is or has previously been in real mode. None.
References XIntc_Config::BaseAddress, XIntc::BaseAddress, XIntc::IsReady, XIntc_LookupConfig.
Referenced by IntcExample.
static void XIntc_CascadeHandler(void *DeviceId)
void XIntc_DeviceInterruptHandler(void *DeviceId)
This function is the primary interrupt handler for the driver.
It must be connected to the interrupt source such that is called when an interrupt of the interrupt controller is active. It will resolve which interrupts are active and enabled and call the appropriate interrupt handler. It uses the AckBeforeService flag in the configuration data to determine when to acknowledge the interrupt. Highest priority interrupts are serviced first. This function assumes that an interrupt vector table has been previously initialized.It does not verify that entries in the table are valid before calling an interrupt handler. In Cascade mode this function calls XIntc_CascadeHandler to handle interrupts of Master and Slave controllers. This functions also handles interrupts nesting by saving and restoring link register of Microblaze and Interrupt Level register of interrupt controller properly. DeviceId is the zero-based device ID defined in xparameters.h of the interrupting interrupt controller. It is used as a direct index into the configuration data, which contains the vector table for the interrupt controller. Note that even though the argument is a void pointer, the value is not a pointer but the actual device ID. The void pointer type is necessary to meet the XInterruptHandler typedef for interrupt handlers. None. For nested interrupts, this function saves microblaze r14 register on entry and restores on exit. This is required since compiler does not support nesting. This function enables Microblaze interrupts after blocking further interrupts from the current interrupt number and interrupts below current interrupt priority by writing to Interrupt Level Register of INTC on entry. On exit, it disables microblaze interrupts and restores ILR register default value(0xFFFFFFFF)back. It is recommended to increase STACK_SIZE in linker script for nested interrupts.
References XIntc_Config::AckBeforeService, XIntc_Config::BaseAddress, XIntc_Config::FastIntr, XIntc_Config::HandlerTable, XIntc_Config::IntcType, LookupConfigByBaseAddress, XIntc_Config::NumberofIntrs, XIntc_Config::NumberofSwIntrs, XIntc_Config::Options, XIN_SVC_SGL_ISR_OPTION, XIntc_AckIntr, XIntc_ConfigTable, XIntc_GetIntrStatus.
Referenced by IntcInterruptSetup, SetupInterruptSystem, XIntc_InterruptHandler.
void XIntc_SetIntrSvcOption(UINTPTR BaseAddress, int Option)
Set the interrupt service option, which can configure the driver so that it services only a single interrupt at a time when an interrupt occurs, or services all pending interrupts when an interrupt occurs.
The default behavior when using the driver interface given in xintc.h file is to service only a single interrupt, whereas the default behavior when using the driver interface given in this file is to service all outstanding interrupts when an interrupt occurs. In Cascade mode same Option is set to Slave controllers. BaseAddress is the unique identifier for a device. Option is XIN_SVC_SGL_ISR_OPTION if you want only a single interrupt serviced when an interrupt occurs, or XIN_SVC_ALL_ISRS_OPTION if you want all pending interrupts serviced when an interrupt occurs. None. Note that this function has no effect if the input base address is invalid.
References XIntc_Config::IntcType, LookupConfigByBaseAddress, XIntc_Config::Options, XIntc_ConfigTable, XIntc_LookupConfig.
void XIntc_RegisterHandler(UINTPTR BaseAddress, int InterruptId, XInterruptHandler Handler, void *CallBackRef)
Register a handler function for a specific interrupt ID.
The vector table of the interrupt controller is updated, overwriting any previous handler. The handler function will be called when an interrupt occurs for the given interrupt ID.This function can also be used to remove a handler from the vector table by passing in the XIntc_DefaultHandler() as the handler and NULL as the callback reference. In Cascade mode Interrupt Id is used to set Handler for corresponding Slave Controller BaseAddress is the base address of the interrupt controller whose vector table will be modified. InterruptId is the interrupt ID to be associated with the input handler. Handler is the function pointer that will be added to the vector table for the given interrupt ID. CallBackRef is the argument that will be passed to the new handler function when it is called. This is user-specific. None. This function has no effect if the input base address is invalid. Following fields in XIntc_Config impacts interrupt handling, AckBeforeService: If 1, primary interrupt handler acks interrupt before servicing it, else it would ack interrupt after servicing it (after calling interrupt ID specific handler)Options: XIN_SVC_SGL_ISR_OPTION - primary interrupt handler services the highest priority pending interrupt and return XIN_SVC_ALL_ISRS_OPTION - primary interrupt handler services all of the pending interrupts and then return
References XIntc_Config::HandlerTable, LookupConfigByBaseAddress, XIntc_LookupConfig.
Referenced by IntcLowLevelExample.
void XIntc_RegisterFastHandler(UINTPTR BaseAddress, u8 Id, XFastInterruptHandler FastHandler)
Register a fast handler function for a specific interrupt ID.
The handler function will be called when an interrupt occurs for the given interrupt ID. In Cascade mode Interrupt Id is used to set Handler for corresponding Slave Controller BaseAddress is the base address of the interrupt controller whose vector table will be modified. InterruptId is the interrupt ID to be associated with the input handler. FastHandler is the function pointer that will be called when interrupt occurs None. Note that this function has no effect if the input base address is invalid.
References XIntc_Config::BaseAddress, XIntc_Config::VectorAddrWidth, XIntc_LookupConfig.
static UINTPTR XIntc_GetChildBaseAddress(UINTPTR ParentBaseAddr)
This function is called by primary interrupt handler for the driver to handle all Controllers in Cascade mode.It will resolve which interrupts are active and enabled and call the appropriate interrupt handler.
It uses the AckBeforeService flag in the configuration data to determine when to acknowledge the interrupt. Highest priority interrupts are serviced first. This function assumes that an interrupt vector table has been previously initialized. It does not verify that entries in the table are valid before calling an interrupt handler.This function calls itself recursively to handle all interrupt controllers. DeviceId is the zero-based device ID defined in xparameters.h of the interrupting interrupt controller. It is used as a direct index into the configuration data, which contains the vector table for the interrupt controller. None.
void XIntc_LowLevelInterruptHandler(void)
XINTC_H
XINTC_I_H
XINTC_L_H
XPAR_XINTC_USE_DCR_BRIDGE
XIN_ISR_OFFSET
XIN_IPR_OFFSET
XIN_IER_OFFSET
XIN_IAR_OFFSET
XIN_SIE_OFFSET
XIN_CIE_OFFSET
XIN_IVR_OFFSET
XIN_MER_OFFSET
XIN_IMR_OFFSET
XIN_ILR_OFFSET
XIN_IVAR_OFFSET
XIN_IVEAR_OFFSET
XIN_INT_MASTER_ENABLE_MASK
XIN_INT_HARDWARE_ENABLE_MASK
XIntc_In32
XIntc_Out32
XIntc_Out64
XIntc_MasterEnable
Enable all interrupts in the Master Enable register of the interrupt controller.
The interrupt controller defaults to all interrupts disabled from reset such that this macro must be used to enable interrupts. BaseAddress is the base address of the device. None. C-style signature: void XIntc_MasterEnable(u32 BaseAddress);
XIntc_MasterDisable
Disable all interrupts in the Master Enable register of the interrupt controller.
BaseAddress is the base address of the device. None. C-style signature: void XIntc_MasterDisable(u32 BaseAddress);
XIntc_EnableIntr
Enable specific interrupt(s) in the interrupt controller.
BaseAddress is the base address of the device EnableMask is the 32-bit value to write to the enable register. Each bit of the mask corresponds to an interrupt input signal that is connected to the interrupt controller (INT0 = LSB). Only the bits which are set in the mask will enable interrupts. None. C-style signature: void XIntc_EnableIntr(u32 BaseAddress, u32 EnableMask);
Referenced by IntcLowLevelExample.
XIntc_DisableIntr
Disable specific interrupt(s) in the interrupt controller.
BaseAddress is the base address of the device DisableMask is the 32-bit value to write to the enable register. Each bit of the mask corresponds to an interrupt input signal that is connected to the interrupt controller (INT0 = LSB). Only the bits which are set in the mask will disable interrupts. None. C-style signature: void XIntc_DisableIntr(u32 BaseAddress, u32 DisableMask);
XIntc_AckIntr
Acknowledge specific interrupt(s) in the interrupt controller.
BaseAddress is the base address of the device AckMask is the 32-bit value to write to the acknowledge register. Each bit of the mask corresponds to an interrupt input signal that is connected to the interrupt controller (INT0 = LSB). Only the bits which are set in the mask will acknowledge interrupts. None. C-style signature: void XIntc_AckIntr(u32 BaseAddress, u32 AckMask);
Referenced by XIntc_DeviceInterruptHandler.
XIntc_GetIntrStatus
Get the interrupt status from the interrupt controller which indicates which interrupts are active and enabled.
BaseAddress is the base address of the device The 32-bit contents of the interrupt status register. Each bit corresponds to an interrupt input signal that is connected to the interrupt controller (INT0 = LSB). Bits which are set indicate an active interrupt which is also enabled. C-style signature: u32 XIntc_GetIntrStatus(u32 BaseAddress);
Referenced by XIntc_DeviceInterruptHandler.
XIN_TEST_MASK