xintc.h
XIN_SVC_SGL_ISR_OPTION
XIN_SVC_SGL_ISR_OPTION Service the highest priority pending interrupt and then return. XIN_SVC_ALL_ISRS_OPTION Service all of the pending interrupts and then return.
Referenced by XIntc_DeviceInterruptHandler, XIntc_Initialize, XIntc_SetOptions.
XIN_SVC_ALL_ISRS_OPTION
XIN_SIMULATION_MODE
Simulation only mode, no hardware interrupts recognized.
Referenced by SetUpInterruptSystem, XIntc_Start.
XIN_REAL_MODE
Real mode, no simulation allowed, hardware interrupts recognized.
Referenced by IntcInterruptSetup, XIntc_Start.
XIN_INTC_NOCASCADE
XIN_INTC_PRIMARY
XIN_INTC_SECONDARY
XIN_INTC_LAST
XIN_CONTROLLER_MAX_INTRS
XINTC_STANDARD_VECTOR_ADDRESS_WIDTH
XIN_CASCADE_IRQ_MASK
Bitmask for the cascade interrupt input (bit 31) used by PRIMARY and SECONDARY controllers to chain to the next controller in cascade mode.
Referenced by XIntc_Enable.
XINTC_MAX_CASCADE_CONTROLLERS
Maximum number of interrupt controllers that can be daisy-chained together in cascade mode.
Limited to 8 because the driver API uses u8 for global interrupt IDs (max 255), and each controller owns 32 interrupt positions (8 * 32 = 256).
Referenced by XIntc_Enable.
XINTC_INTR_PARENT_MASK
Mask used to extract the parent controller base address from IntrParent by clearing the LSB which encodes the parent type (GIC vs INTC).
XINTC_NO_PARENT
Sentinel value indicating that an interrupt controller has no parent controller (i.e.
it is the root of the interrupt hierarchy).
XINTC_H
XIntc_Config XIntc_ConfigTable[][]
This table contains configuration information for each intc device in the system.
The XIntc driver must know when to acknowledge the interrupt. The entry which specifies this as a bit mask where each bit corresponds to a specific interrupt. A bit set indicates to ack it before servicing it. Generally, acknowledge before service is used when the interrupt signal is edge-sensitive, and after when the signal is level-sensitive.Refer to the XIntc_Config data structure in xintc.h for details on how this table should be initialized.
Referenced by LookupConfigByBaseAddress, XIntc_DeviceInterruptHandler, XIntc_GetPrimaryController, XIntc_LookupConfig, XIntc_SetIntrSvcOption, XIntc_SetOptions, XIntc_Start.
int XIntc_Initialize(XIntc *InstancePtr, UINTPTR BaseAddr)
Initialize a specific interrupt controller instance/driver.
The initialization entails: - Initialize fields of the XIntc structure - Initial vector table with stub function calls - All interrupt sources are disabled - Interrupt output is disabled InstancePtr is a pointer to the XIntc instance to be worked on. BaseAddr is the base address of the device XST_SUCCESS if initialization was successfulXST_DEVICE_IS_STARTED if the device has already been startedXST_DEVICE_NOT_FOUND if device configuration information was not found for a device with the supplied device ID/BaseAddress. In Cascade mode this function calls XIntc_InitializeSlaves to initialize Slave Interrupt controllers. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XIntc_Config::BaseAddress, XIntc::BaseAddress, XIntc::CfgPtr, XIntc_Config::FastIntr, XIntc_Config::HandlerTable, XIntc_Config::IntcType, XIntc::IsReady, XIntc::IsStarted, XIntc_Config::NumberofIntrs, XIntc_Config::NumberofSwIntrs, XIntc_Config::Options, XIntc_Config::VectorAddrWidth, XIN_SVC_SGL_ISR_OPTION, XIntc_LookupConfig.
Referenced by IntcExample, IntcInterruptSetup, IntcSelfTestExample.
int XIntc_Start(XIntc *InstancePtr, u8 Mode)
Starts the interrupt controller by enabling the output from the controller to the processor.
Interrupts may be generated by the interrupt controller after this function is called.It is necessary for the caller to connect the interrupt handler of this component to the proper interrupt source. This function also starts Slave controllers in Cascade mode. InstancePtr is a pointer to the XIntc instance to be worked on. Mode determines if software is allowed to simulate interrupts or real interrupts are allowed to occur. Note that these modes are mutually exclusive. The interrupt controller hardware resets in a mode that allows software to simulate interrupts until this mode is exited. It cannot be reentered once it has been exited. One of the following values should be used for the mode. XIN_SIMULATION_MODE enables simulation of interrupts onlyXIN_REAL_MODE enables hardware interrupts only XST_SUCCESS if the device was started successfullyXST_FAILURE if simulation mode was specified and it could not be set because real mode has already been entered. Must be called after XIntc initialization is completed.
References XIntc::BaseAddress, XIntc::CfgPtr, XIntc_Config::IntcType, XIntc::IsReady, XIntc::IsStarted, XIN_REAL_MODE, XIN_SIMULATION_MODE, XIntc_ConfigTable.
Referenced by IntcInterruptSetup, SetUpInterruptSystem.
void XIntc_Stop(XIntc *InstancePtr)
Stops the interrupt controller by disabling the output from the controller so that no interrupts will be caused by the interrupt controller.
InstancePtr is a pointer to the XIntc instance to be worked on. None. None.
References XIntc::BaseAddress, XIntc::IsReady, XIntc::IsStarted.
int XIntc_Connect(XIntc *InstancePtr, u8 Id, XInterruptHandler Handler, void *CallBackRef)
Makes the connection between the Id of the interrupt source and the associated handler that is to run when the interrupt is recognized.
The argument provided in this call as the Callbackref is used as the argument for the handler when it is called. In Cascade mode, connects handler to Slave controller handler table depending on the interrupt Id. InstancePtr is a pointer to the XIntc instance to be worked on. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_INTC_MAX_NUM_INTR_INPUTS - 1 with 0 being the highest priority interrupt. Handler to the handler for that interrupt. CallBackRef is the callback reference, usually the instance pointer of the connecting driver. - XST_SUCCESS if the handler was connected correctly. WARNING: The handler provided as an argument will overwrite any handler that was previously connected.
References XIntc::CfgPtr, XIntc_Config::HandlerTable, XIntc::IsReady.
Referenced by SetUpInterruptSystem.
void XIntc_Disconnect(XIntc *InstancePtr, u8 Id)
Updates the interrupt table with the Null Handler and NULL arguments at the location pointed at by the Id.
This effectively disconnects that interrupt source from any handler. The interrupt is disabled also. In Cascade mode, disconnects handler from Slave controller handler table depending on the interrupt Id. InstancePtr is a pointer to the XIntc instance to be worked on. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_INTC_MAX_NUM_INTR_INPUTS - 1 with 0 being the highest priority interrupt. None. None.
References XIntc_Config::BaseAddress, XIntc::BaseAddress, XIntc::CfgPtr, XIntc_Config::HandlerTable, XIntc::IsReady.
void XIntc_Enable(XIntc *InstancePtr, u8 Id)
Enables the interrupt source provided as the argument Id.
Any pending interrupt condition for the specified Id will occur after this function is called. In Cascade mode, enables corresponding interrupt of Slave controllers depending on the Id. InstancePtr is a pointer to the XIntc instance to be worked on. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_INTC_MAX_NUM_INTR_INPUTS - 1 with 0 being the highest priority interrupt. None. None.
References XIntc_Config::BaseAddress, XIntc::BaseAddress, XIntc::CfgPtr, XIntc_Config::IntcType, XIntc_Config::IntrParent, XIntc::IsReady, XIN_CASCADE_IRQ_MASK, XINTC_MAX_CASCADE_CONTROLLERS.
Referenced by SetUpInterruptSystem, XIntc_ConnectFastHandler, XIntc_SetNormalIntrMode.
void XIntc_Disable(XIntc *InstancePtr, u8 Id)
Disables the interrupt source provided as the argument Id such that the interrupt controller will not cause interrupts for the specified Id.
The interrupt controller will continue to hold an interrupt condition for the Id, but will not cause an interrupt.In Cascade mode, disables corresponding interrupt of Slave controllers depending on the Id. InstancePtr is a pointer to the XIntc instance to be worked on. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_INTC_MAX_NUM_INTR_INPUTS - 1 with 0 being the highest priority interrupt. None. None.
References XIntc_Config::BaseAddress, XIntc::BaseAddress, XIntc::IsReady.
Referenced by XIntc_ConnectFastHandler, XIntc_SetNormalIntrMode.
void XIntc_Acknowledge(XIntc *InstancePtr, u8 Id)
Acknowledges the interrupt source provided as the argument Id.
When the interrupt is acknowledged, it causes the interrupt controller to clear its interrupt condition.In Cascade mode, acknowledges corresponding interrupt source of Slave controllers depending on the Id. InstancePtr is a pointer to the XIntc instance to be worked on. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_INTC_MAX_NUM_INTR_INPUTS - 1 with 0 being the highest priority interrupt. None. None.
References XIntc_Config::BaseAddress, XIntc::BaseAddress, XIntc::IsReady.
XIntc_Config * XIntc_LookupConfig(UINTPTR BaseAddr)
Looks up the device configuration based on the unique device ID/BaseAddress.
A table contains the configuration info for each device in the system. BaseAddr contains the base address of the device A pointer to the XIntc configuration structure for the specified device, or NULL if the device ID/BaseAddress was not found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XIntc_ConfigTable.
Referenced by XIntc_Initialize, XIntc_RegisterFastHandler, XIntc_RegisterHandler, XIntc_SetIntrSvcOption, XIntc_SetOptions, XIntc_SimulateIntr.
XIntc_Config * LookupConfigByBaseAddress(UINTPTR BaseAddress)
Looks up the device configuration based on the base address of the device.
A table contains the configuration info for each device in the system. BaseAddress is the unique identifier for a device. A pointer to the configuration structure for the specified device, or NULL if the device was not found.None.
References XIntc_ConfigTable.
Referenced by IntcLowLevelExample, XIntc_DeviceInterruptHandler, XIntc_RegisterHandler, XIntc_SetIntrSvcOption.
XIntc_Config * XIntc_GetPrimaryController(void)
Find the PRIMARY controller in the config table.
Pointer to primary controller config, or NULL if not found
References XIntc_ConfigTable.
int XIntc_ConnectFastHandler(XIntc *InstancePtr, u8 Id, XFastInterruptHandler Handler)
Makes the connection between the Id of the interrupt source and the associated handler that is to run when the interrupt is recognized.In Cascade mode, connects handler to corresponding Slave controller IVAR/IVEAR register depending on the Id and sets all interrupt sources of the Slave controller as fast interrupts.
InstancePtr is a pointer to the XIntc instance to be worked on. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_INTC_MAX_NUM_INTR_INPUTS - 1 with 0 being the highest priority interrupt. Handler for specified interrupt id. It must be declared with "fast_interrupt" attribute. e.g. static void MyHandler(void) attribute ((fast_interrupt)); XST_SUCCESS Slave controllers in Cascade Mode should have all as Fast interrupts or Normal interrupts, mixed interrupts are not supported WARNING: The handler provided as an argument will overwrite any handler that was previously connected.
References XIntc_Config::BaseAddress, XIntc::BaseAddress, XIntc::CfgPtr, XIntc_Config::FastIntr, XIntc::IsReady, XIntc_Config::VectorAddrWidth, XIntc_Disable, XIntc_Enable.
void XIntc_SetNormalIntrMode(XIntc *InstancePtr, u8 Id)
Sets the normal interrupt mode for the specified interrupt in the Interrupt Mode Register.
In Cascade mode disconnects handler from corresponding Slave controller IVAR/IVEAR register depending on the Id and sets all interrupt sources of the Slave controller as normal interrupts. InstancePtr is a pointer to the XIntc instance to be worked on. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_INTC_MAX_NUM_INTR_INPUTS - 1 with 0 being the highest priority interrupt. None. Slave controllers in Cascade Mode should have all as Fast interrupts or Normal interrupts, mixed interrupts are not supported
References XIntc_Config::BaseAddress, XIntc::BaseAddress, XIntc::CfgPtr, XIntc_Config::FastIntr, XIntc::IsReady, XIntc_Config::VectorAddrWidth, XIntc_Disable, XIntc_Enable.
int XIntc_TriggerSwIntr(XIntc *InstancePtr, u8 Id)
Allows software to trigger software interrupt.
This function will only be successful when the interrupt controller has been configured with software interrupt in HW design InstancePtr is a pointer to the XIntc instance to be worked on. Id is the interrupt ID to be triggered XST_SUCCESS if successful XST_FAILURE if the instance pointer is invalid if interrupt id does not belongs to software interrupt HW design must have software interrupts and interrupt id passed should be of software interrupt type. Interrupt id's for software interrupts for specific HW design can be found in xparameters.h file.
References XIntc_Config::BaseAddress, XIntc::BaseAddress, XIntc::IsReady.
void XIntc_VoidInterruptHandler(void)
void XIntc_InterruptHandler(XIntc *InstancePtr)
Interrupt handler for the driver used when there can be no argument passed to the handler.
This function is provided mostly for backward compatibility. The user should use XIntc_DeviceInterruptHandler(), defined in xintc_l.c, if possible.The user must connect this function to the interrupt system such that it is called whenever the devices which are connected to it cause an interrupt.None. The constant XPAR_INTC_SINGLE_DEVICE_ID must be defined for this handler to be included in the driver compilation.The interrupt handler for the driver. This function is provided mostly for backward compatibility. The user should use XIntc_DeviceInterruptHandler(), defined in xintc_l.c when possible and pass the device ID of the interrupt controller device as its argument.The user must connect this function to the interrupt system such that it is called whenever the devices which are connected to it cause an interrupt. InstancePtr is a pointer to the XIntc instance to be worked on. None. None.
References XIntc_Config::BaseAddress, XIntc::CfgPtr, XIntc_DeviceInterruptHandler.
Referenced by SetUpInterruptSystem.
int XIntc_SetOptions(XIntc *InstancePtr, u32 Options)
Set the options for the interrupt controller driver.
In Cascade mode same Option is set to Slave controllers. InstancePtr is a pointer to the XIntc instance to be worked on. Options to be set. The available options are described in xintc.h. XST_SUCCESS if the options were set successfullyXST_INVALID_PARAM if the specified option was not valid None.
References XIntc::CfgPtr, XIntc_Config::IntcType, XIntc::IsReady, XIntc_Config::Options, XIN_SVC_SGL_ISR_OPTION, XIntc_ConfigTable, XIntc_LookupConfig.
u32 XIntc_GetOptions(XIntc *InstancePtr)
Return the currently set options.
InstancePtr is a pointer to the XIntc instance to be worked on. The currently set options. The options are described in xintc.h. None.
References XIntc::CfgPtr, XIntc::IsReady, XIntc_Config::Options.
int XIntc_SelfTest(XIntc *InstancePtr)
Run a self-test on the driver/device.
This is a destructive test.This involves forcing interrupts into the controller and verifying that they are recognized and can be acknowledged. This test will not succeed if the interrupt controller has been started in real mode such that interrupts cannot be forced. InstancePtr is a pointer to the XIntc instance to be worked on. XST_SUCCESS if self-test is successful.XST_INTC_FAIL_SELFTEST if the Interrupt controller fails the self-test. It will fail the self test if the device has previously been started in real mode. None.
References XIntc::BaseAddress, XIntc::IsReady.
Referenced by IntcExample, IntcInterruptSetup, IntcSelfTestExample.
int XIntc_SimulateIntr(XIntc *InstancePtr, u8 Id)
Allows software to simulate an interrupt in the interrupt controller.
This function will only be successful when the interrupt controller has been started in simulation mode. Once it has been started in real mode, interrupts cannot be simulated. A simulated interrupt allows the interrupt controller to be tested without any device to drive an interrupt input signal into it. In Cascade mode writes to ISR of appropriate Slave controller depending on Id. InstancePtr is a pointer to the XIntc instance to be worked on. Id is the interrupt ID for which to simulate an interrupt. XST_SUCCESS if successful XST_FAILURE if the interrupt could not be simulated because the interrupt controller is or has previously been in real mode. None.
References XIntc_Config::BaseAddress, XIntc::BaseAddress, XIntc::IsReady, XIntc_LookupConfig.
Referenced by IntcExample.