xintc_l.c
static void XIntc_CascadeHandler(void *DeviceId)
void XIntc_DeviceInterruptHandler(void *DeviceId)
This function is the primary interrupt handler for the driver.
It must be connected to the interrupt source such that is called when an interrupt of the interrupt controller is active. It will resolve which interrupts are active and enabled and call the appropriate interrupt handler. It uses the AckBeforeService flag in the configuration data to determine when to acknowledge the interrupt. Highest priority interrupts are serviced first. This function assumes that an interrupt vector table has been previously initialized.It does not verify that entries in the table are valid before calling an interrupt handler. In Cascade mode this function calls XIntc_CascadeHandler to handle interrupts of Master and Slave controllers. This functions also handles interrupts nesting by saving and restoring link register of Microblaze and Interrupt Level register of interrupt controller properly. DeviceId is the zero-based device ID defined in xparameters.h of the interrupting interrupt controller. It is used as a direct index into the configuration data, which contains the vector table for the interrupt controller. Note that even though the argument is a void pointer, the value is not a pointer but the actual device ID. The void pointer type is necessary to meet the XInterruptHandler typedef for interrupt handlers. None. For nested interrupts, this function saves microblaze r14 register on entry and restores on exit. This is required since compiler does not support nesting. This function enables Microblaze interrupts after blocking further interrupts from the current interrupt number and interrupts below current interrupt priority by writing to Interrupt Level Register of INTC on entry. On exit, it disables microblaze interrupts and restores ILR register default value(0xFFFFFFFF)back. It is recommended to increase STACK_SIZE in linker script for nested interrupts.
References XIntc_Config::AckBeforeService, XIntc_Config::BaseAddress, XIntc_Config::FastIntr, XIntc_Config::HandlerTable, XIntc_Config::IntcType, LookupConfigByBaseAddress, XIntc_Config::NumberofIntrs, XIntc_Config::NumberofSwIntrs, XIntc_Config::Options, XIN_SVC_SGL_ISR_OPTION, XIntc_AckIntr, XIntc_ConfigTable, XIntc_GetIntrStatus.
Referenced by IntcInterruptSetup, SetupInterruptSystem, XIntc_InterruptHandler.
void XIntc_SetIntrSvcOption(UINTPTR BaseAddress, int Option)
Set the interrupt service option, which can configure the driver so that it services only a single interrupt at a time when an interrupt occurs, or services all pending interrupts when an interrupt occurs.
The default behavior when using the driver interface given in xintc.h file is to service only a single interrupt, whereas the default behavior when using the driver interface given in this file is to service all outstanding interrupts when an interrupt occurs. In Cascade mode same Option is set to Slave controllers. BaseAddress is the unique identifier for a device. Option is XIN_SVC_SGL_ISR_OPTION if you want only a single interrupt serviced when an interrupt occurs, or XIN_SVC_ALL_ISRS_OPTION if you want all pending interrupts serviced when an interrupt occurs. None. Note that this function has no effect if the input base address is invalid.
References XIntc_Config::IntcType, LookupConfigByBaseAddress, XIntc_Config::Options, XIntc_ConfigTable, XIntc_LookupConfig.
void XIntc_RegisterHandler(UINTPTR BaseAddress, int InterruptId, XInterruptHandler Handler, void *CallBackRef)
Register a handler function for a specific interrupt ID.
The vector table of the interrupt controller is updated, overwriting any previous handler. The handler function will be called when an interrupt occurs for the given interrupt ID.This function can also be used to remove a handler from the vector table by passing in the XIntc_DefaultHandler() as the handler and NULL as the callback reference. In Cascade mode Interrupt Id is used to set Handler for corresponding Slave Controller BaseAddress is the base address of the interrupt controller whose vector table will be modified. InterruptId is the interrupt ID to be associated with the input handler. Handler is the function pointer that will be added to the vector table for the given interrupt ID. CallBackRef is the argument that will be passed to the new handler function when it is called. This is user-specific. None. This function has no effect if the input base address is invalid. Following fields in XIntc_Config impacts interrupt handling, AckBeforeService: If 1, primary interrupt handler acks interrupt before servicing it, else it would ack interrupt after servicing it (after calling interrupt ID specific handler)Options: XIN_SVC_SGL_ISR_OPTION - primary interrupt handler services the highest priority pending interrupt and return XIN_SVC_ALL_ISRS_OPTION - primary interrupt handler services all of the pending interrupts and then return
References XIntc_Config::HandlerTable, LookupConfigByBaseAddress, XIntc_LookupConfig.
Referenced by IntcLowLevelExample.
XIntc_Config * LookupConfigByBaseAddress(UINTPTR BaseAddress)
Looks up the device configuration based on the base address of the device.
A table contains the configuration info for each device in the system. BaseAddress is the unique identifier for a device. A pointer to the configuration structure for the specified device, or NULL if the device was not found.None.
References XIntc_ConfigTable.
Referenced by IntcLowLevelExample, XIntc_DeviceInterruptHandler, XIntc_RegisterHandler, XIntc_SetIntrSvcOption.
void XIntc_RegisterFastHandler(UINTPTR BaseAddress, u8 Id, XFastInterruptHandler FastHandler)
Register a fast handler function for a specific interrupt ID.
The handler function will be called when an interrupt occurs for the given interrupt ID. In Cascade mode Interrupt Id is used to set Handler for corresponding Slave Controller BaseAddress is the base address of the interrupt controller whose vector table will be modified. InterruptId is the interrupt ID to be associated with the input handler. FastHandler is the function pointer that will be called when interrupt occurs None. Note that this function has no effect if the input base address is invalid.
References XIntc_Config::BaseAddress, XIntc_Config::VectorAddrWidth, XIntc_LookupConfig.
static UINTPTR XIntc_GetChildBaseAddress(UINTPTR ParentBaseAddr)
This function is called by primary interrupt handler for the driver to handle all Controllers in Cascade mode.It will resolve which interrupts are active and enabled and call the appropriate interrupt handler.
It uses the AckBeforeService flag in the configuration data to determine when to acknowledge the interrupt. Highest priority interrupts are serviced first. This function assumes that an interrupt vector table has been previously initialized. It does not verify that entries in the table are valid before calling an interrupt handler.This function calls itself recursively to handle all interrupt controllers. DeviceId is the zero-based device ID defined in xparameters.h of the interrupting interrupt controller. It is used as a direct index into the configuration data, which contains the vector table for the interrupt controller. None.