xintc_selftest.c
XIN_TEST_MASK
int XIntc_SelfTest(XIntc *InstancePtr)
Run a self-test on the driver/device.
This is a destructive test.This involves forcing interrupts into the controller and verifying that they are recognized and can be acknowledged. This test will not succeed if the interrupt controller has been started in real mode such that interrupts cannot be forced. InstancePtr is a pointer to the XIntc instance to be worked on. XST_SUCCESS if self-test is successful.XST_INTC_FAIL_SELFTEST if the Interrupt controller fails the self-test. It will fail the self test if the device has previously been started in real mode. None.
References XIntc::BaseAddress, XIntc::IsReady.
Referenced by IntcExample, IntcInterruptSetup, IntcSelfTestExample.
int XIntc_SimulateIntr(XIntc *InstancePtr, u8 Id)
Allows software to simulate an interrupt in the interrupt controller.
This function will only be successful when the interrupt controller has been started in simulation mode. Once it has been started in real mode, interrupts cannot be simulated. A simulated interrupt allows the interrupt controller to be tested without any device to drive an interrupt input signal into it. In Cascade mode writes to ISR of appropriate Slave controller depending on Id. InstancePtr is a pointer to the XIntc instance to be worked on. Id is the interrupt ID for which to simulate an interrupt. XST_SUCCESS if successful XST_FAILURE if the interrupt could not be simulated because the interrupt controller is or has previously been in real mode. None.
References XIntc_Config::BaseAddress, XIntc::BaseAddress, XIntc::IsReady, XIntc_LookupConfig.
Referenced by IntcExample.