xintc_example.c
INTC_DEVICE_INT_ID
INTC_BASEADDR
XIntc InterruptController
volatile int InterruptProcessed
int IntcExample(UINTPTR BaseAddr)
This function is an example of how to use the interrupt controller driver component (XIntc) and the hardware device.
This function is designed to work without any hardware devices to cause interrupts. It may not return if the interrupt controller is not properly connected to the processor in either software or hardware.This function relies on the fact that the interrupt controller hardware has come out of the reset state such that it will allow interrupts to be simulated by the software. BaseAddr is the base address of the Interrupt Controller device XST_SUCCESS to indicate success, otherwise XST_FAILURE. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References SetUpInterruptSystem, XIntc_Initialize, XIntc_SelfTest, XIntc_SimulateIntr.
Referenced by main.
int SetUpInterruptSystem(XIntc *XIntcInstancePtr)
This function connects the interrupt handler of the interrupt controller to the processor.
This function is separate to allow it to be customized for each application. Each processor or RTOS may require unique processing to connect the interrupt handler. None. None. None.
References XIntc::CfgPtr, DeviceDriverHandler, XIntc_Config::IntrId, XIntc_Config::IntrParent, XIN_SIMULATION_MODE, XIntc_Connect, XIntc_Enable, XIntc_InterruptHandler, XIntc_Start.
Referenced by IntcExample.
void DeviceDriverHandler(void *CallbackRef)
This function is designed to look like an interrupt handler in a device driver.
This is typically a 2nd level handler that is called from the interrupt controller interrupt handler. This handler would typically perform device specific processing such as reading and writing the registers of the device to clear the interrupt condition and pass any data to an application using the device driver. Many drivers already provide this handler and the user is not required to create it. CallbackRef is passed back to the device driver's interrupt handler by the XIntc driver. It was given to the XIntc driver in the XIntc_Connect() function call. It is typically a pointer to the device driver instance variable if using the Xilinx Level 1 device drivers. In this example, we do not care about the callback reference, so we passed it a 0 when connecting the handler to the XIntc driver and we make no use of it here. None. None. This is typically a 2nd level handler that is called from the interrupt controller interrupt handler. This handler would typically perform device specific processing such as reading and writing the registers of the device to clear the interrupt condition and pass any data to an application using the device driver. CallbackRef is passed back to the device driver's interrupt handler by the XIntc driver. It was given to the XIntc driver in the XIntc_Connect() function call. It is typically a pointer to the device driver instance variable if using the Xilinx Level 1 device drivers. In this example, we do not care about the callback reference, so we passed it a 0 when connecting the handler to the XIntc driver and we make no use of it here. None. None.
Referenced by IntcLowLevelExample, SetUpInterruptSystem.
int main(void)
This is the main function for the Interrupt Controller example.
None. XST_SUCCESS to indicate success, otherwise XST_FAILURE. None.
References IntcExample.