xintc.c
u32 XIntc_BitPosMask[XIN_CONTROLLER_MAX_INTRS][XIN_CONTROLLER_MAX_INTRS]
static void StubHandler(void *CallBackRef)
A stub for the asynchronous callback.
The stub is here in case the upper layers forget to set the handler. CallBackRef is a pointer to the upper layer callback reference None. None.
static void XIntc_InitializeSlaves(XIntc *InstancePtr)
Initializes Slave controllers in Cascade mode.
The initialization entails: Initial vector table with stub function callsAll interrupt sources are disabled for last controller.All interrupt sources are disabled except sources to 31 pin of primary and secondary controllersInterrupt outputs are disabled InstancePtr is a pointer to the XIntc instance to be worked on. None None.
static XIntc_Config * XIntc_FindControllerByAddr(UINTPTR BaseAddr)
Find controller by base address (used for parent lookup in SDT cascade mode).
BaseAddr Base address to search for (LSB may be set for encoding) Pointer to controller config, or NULL if not found
static XIntc_Config * XIntc_FindControllerForId(u8 Id, u8 *LocalId)
Find the controller that owns an interrupt ID and return local interrupt number.
In SDT mode, builds cascade chain via BFS using interrupt-parent links. In non-SDT mode, uses sequential config table order. Id Global interrupt ID (0-N across all controllers) LocalId Output parameter for local interrupt ID (0-31) on found controller Pointer to controller config that owns this interrupt, or NULL if not found
XIntc_Config * XIntc_GetPrimaryController(void)
Find the PRIMARY controller in the config table.
Pointer to primary controller config, or NULL if not found
References XIntc_ConfigTable.
int XIntc_Initialize(XIntc *InstancePtr, UINTPTR BaseAddr)
Initialize a specific interrupt controller instance/driver.
The initialization entails: - Initialize fields of the XIntc structure - Initial vector table with stub function calls - All interrupt sources are disabled - Interrupt output is disabled InstancePtr is a pointer to the XIntc instance to be worked on. BaseAddr is the base address of the device XST_SUCCESS if initialization was successfulXST_DEVICE_IS_STARTED if the device has already been startedXST_DEVICE_NOT_FOUND if device configuration information was not found for a device with the supplied device ID/BaseAddress. In Cascade mode this function calls XIntc_InitializeSlaves to initialize Slave Interrupt controllers. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XIntc_Config::BaseAddress, XIntc::BaseAddress, XIntc::CfgPtr, XIntc_Config::FastIntr, XIntc_Config::HandlerTable, XIntc_Config::IntcType, XIntc::IsReady, XIntc::IsStarted, XIntc_Config::NumberofIntrs, XIntc_Config::NumberofSwIntrs, XIntc_Config::Options, XIntc_Config::VectorAddrWidth, XIN_SVC_SGL_ISR_OPTION, XIntc_LookupConfig.
Referenced by IntcExample, IntcInterruptSetup, IntcSelfTestExample.
int XIntc_Start(XIntc *InstancePtr, u8 Mode)
Starts the interrupt controller by enabling the output from the controller to the processor.
Interrupts may be generated by the interrupt controller after this function is called.It is necessary for the caller to connect the interrupt handler of this component to the proper interrupt source. This function also starts Slave controllers in Cascade mode. InstancePtr is a pointer to the XIntc instance to be worked on. Mode determines if software is allowed to simulate interrupts or real interrupts are allowed to occur. Note that these modes are mutually exclusive. The interrupt controller hardware resets in a mode that allows software to simulate interrupts until this mode is exited. It cannot be reentered once it has been exited. One of the following values should be used for the mode. XIN_SIMULATION_MODE enables simulation of interrupts onlyXIN_REAL_MODE enables hardware interrupts only XST_SUCCESS if the device was started successfullyXST_FAILURE if simulation mode was specified and it could not be set because real mode has already been entered. Must be called after XIntc initialization is completed.
References XIntc::BaseAddress, XIntc::CfgPtr, XIntc_Config::IntcType, XIntc::IsReady, XIntc::IsStarted, XIN_REAL_MODE, XIN_SIMULATION_MODE, XIntc_ConfigTable.
Referenced by IntcInterruptSetup, SetUpInterruptSystem.
void XIntc_Stop(XIntc *InstancePtr)
Stops the interrupt controller by disabling the output from the controller so that no interrupts will be caused by the interrupt controller.
InstancePtr is a pointer to the XIntc instance to be worked on. None. None.
References XIntc::BaseAddress, XIntc::IsReady, XIntc::IsStarted.
int XIntc_Connect(XIntc *InstancePtr, u8 Id, XInterruptHandler Handler, void *CallBackRef)
Makes the connection between the Id of the interrupt source and the associated handler that is to run when the interrupt is recognized.
The argument provided in this call as the Callbackref is used as the argument for the handler when it is called. In Cascade mode, connects handler to Slave controller handler table depending on the interrupt Id. InstancePtr is a pointer to the XIntc instance to be worked on. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_INTC_MAX_NUM_INTR_INPUTS - 1 with 0 being the highest priority interrupt. Handler to the handler for that interrupt. CallBackRef is the callback reference, usually the instance pointer of the connecting driver. - XST_SUCCESS if the handler was connected correctly. WARNING: The handler provided as an argument will overwrite any handler that was previously connected.
References XIntc::CfgPtr, XIntc_Config::HandlerTable, XIntc::IsReady.
Referenced by SetUpInterruptSystem.
void XIntc_Disconnect(XIntc *InstancePtr, u8 Id)
Updates the interrupt table with the Null Handler and NULL arguments at the location pointed at by the Id.
This effectively disconnects that interrupt source from any handler. The interrupt is disabled also. In Cascade mode, disconnects handler from Slave controller handler table depending on the interrupt Id. InstancePtr is a pointer to the XIntc instance to be worked on. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_INTC_MAX_NUM_INTR_INPUTS - 1 with 0 being the highest priority interrupt. None. None.
References XIntc_Config::BaseAddress, XIntc::BaseAddress, XIntc::CfgPtr, XIntc_Config::HandlerTable, XIntc::IsReady.
void XIntc_Enable(XIntc *InstancePtr, u8 Id)
Enables the interrupt source provided as the argument Id.
Any pending interrupt condition for the specified Id will occur after this function is called. In Cascade mode, enables corresponding interrupt of Slave controllers depending on the Id. InstancePtr is a pointer to the XIntc instance to be worked on. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_INTC_MAX_NUM_INTR_INPUTS - 1 with 0 being the highest priority interrupt. None. None.
References XIntc_Config::BaseAddress, XIntc::BaseAddress, XIntc::CfgPtr, XIntc_Config::IntcType, XIntc_Config::IntrParent, XIntc::IsReady, XIN_CASCADE_IRQ_MASK, XINTC_MAX_CASCADE_CONTROLLERS.
Referenced by SetUpInterruptSystem, XIntc_ConnectFastHandler, XIntc_SetNormalIntrMode.
void XIntc_Disable(XIntc *InstancePtr, u8 Id)
Disables the interrupt source provided as the argument Id such that the interrupt controller will not cause interrupts for the specified Id.
The interrupt controller will continue to hold an interrupt condition for the Id, but will not cause an interrupt.In Cascade mode, disables corresponding interrupt of Slave controllers depending on the Id. InstancePtr is a pointer to the XIntc instance to be worked on. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_INTC_MAX_NUM_INTR_INPUTS - 1 with 0 being the highest priority interrupt. None. None.
References XIntc_Config::BaseAddress, XIntc::BaseAddress, XIntc::IsReady.
Referenced by XIntc_ConnectFastHandler, XIntc_SetNormalIntrMode.
void XIntc_Acknowledge(XIntc *InstancePtr, u8 Id)
Acknowledges the interrupt source provided as the argument Id.
When the interrupt is acknowledged, it causes the interrupt controller to clear its interrupt condition.In Cascade mode, acknowledges corresponding interrupt source of Slave controllers depending on the Id. InstancePtr is a pointer to the XIntc instance to be worked on. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_INTC_MAX_NUM_INTR_INPUTS - 1 with 0 being the highest priority interrupt. None. None.
References XIntc_Config::BaseAddress, XIntc::BaseAddress, XIntc::IsReady.
XIntc_Config * XIntc_LookupConfig(UINTPTR BaseAddr)
Looks up the device configuration based on the unique device ID/BaseAddress.
A table contains the configuration info for each device in the system. BaseAddr contains the base address of the device A pointer to the XIntc configuration structure for the specified device, or NULL if the device ID/BaseAddress was not found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XIntc_ConfigTable.
Referenced by XIntc_Initialize, XIntc_RegisterFastHandler, XIntc_RegisterHandler, XIntc_SetIntrSvcOption, XIntc_SetOptions, XIntc_SimulateIntr.
int XIntc_ConnectFastHandler(XIntc *InstancePtr, u8 Id, XFastInterruptHandler Handler)
Makes the connection between the Id of the interrupt source and the associated handler that is to run when the interrupt is recognized.In Cascade mode, connects handler to corresponding Slave controller IVAR/IVEAR register depending on the Id and sets all interrupt sources of the Slave controller as fast interrupts.
InstancePtr is a pointer to the XIntc instance to be worked on. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_INTC_MAX_NUM_INTR_INPUTS - 1 with 0 being the highest priority interrupt. Handler for specified interrupt id. It must be declared with "fast_interrupt" attribute. e.g. static void MyHandler(void) attribute ((fast_interrupt)); XST_SUCCESS Slave controllers in Cascade Mode should have all as Fast interrupts or Normal interrupts, mixed interrupts are not supported WARNING: The handler provided as an argument will overwrite any handler that was previously connected.
References XIntc_Config::BaseAddress, XIntc::BaseAddress, XIntc::CfgPtr, XIntc_Config::FastIntr, XIntc::IsReady, XIntc_Config::VectorAddrWidth, XIntc_Disable, XIntc_Enable.
void XIntc_SetNormalIntrMode(XIntc *InstancePtr, u8 Id)
Sets the normal interrupt mode for the specified interrupt in the Interrupt Mode Register.
In Cascade mode disconnects handler from corresponding Slave controller IVAR/IVEAR register depending on the Id and sets all interrupt sources of the Slave controller as normal interrupts. InstancePtr is a pointer to the XIntc instance to be worked on. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_INTC_MAX_NUM_INTR_INPUTS - 1 with 0 being the highest priority interrupt. None. Slave controllers in Cascade Mode should have all as Fast interrupts or Normal interrupts, mixed interrupts are not supported
References XIntc_Config::BaseAddress, XIntc::BaseAddress, XIntc::CfgPtr, XIntc_Config::FastIntr, XIntc::IsReady, XIntc_Config::VectorAddrWidth, XIntc_Disable, XIntc_Enable.
int XIntc_TriggerSwIntr(XIntc *InstancePtr, u8 Id)
Allows software to trigger software interrupt.
This function will only be successful when the interrupt controller has been configured with software interrupt in HW design InstancePtr is a pointer to the XIntc instance to be worked on. Id is the interrupt ID to be triggered XST_SUCCESS if successful XST_FAILURE if the instance pointer is invalid if interrupt id does not belongs to software interrupt HW design must have software interrupts and interrupt id passed should be of software interrupt type. Interrupt id's for software interrupts for specific HW design can be found in xparameters.h file.
References XIntc_Config::BaseAddress, XIntc::BaseAddress, XIntc::IsReady.