i2srx
XI2s_Rx_HandlerType
AES Block Complete Handler.
XI2s_Rx_ChannelId
Channel 0.
XI2S_RX_AES_STS_USE_OF_CH_STS_BLK_SHIFT
Use of Channel Status Block bit shift.
XI2S_RX_AES_STS_LINEAR_PCM_ID_SHIFT
Linear PCM Identification bit shift.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_AUDIO_SIG_PRE_EMPH_SHIFT
Audio signal pre-emphasis bit shift.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_LOCK_INDICATION_SHIFT
lock indication bit shift
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_SAMPLING_FREQ_E_SHIFT
Sampling Frequency 0 bit shift.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_CH_MODE_SHIFT
Channel mode bit shift.
XI2S_RX_AES_STS_USR_BITS_MGMT_SHIFT
User Bits Management bit shift.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_USEOF_AUX_SMPL_BITS_SHIFT
Use of auxiliary sample bits bit shift.
XI2S_RX_AES_STS_SRC_WORD_LENGTH_SHIFT
Source word length bit shift.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_INDICATE_ALIGN_LEVEL_SHIFT
Indication of Alignment level bit shift.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_CH_NUM0_SHIFT
Channel Number (0) bit shift.
XI2S_RX_AES_STS_MC_CH_MODE_SHIFT
Multi-channel mode bit shift.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_CH_NUM1_SHIFT
Channel Number (1) bit shift.
XI2S_RX_AES_STS_MC_CH_MODE_NUM_SHIFT
Multi-channel mode number bit shift.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_RSVD_BUT_UNDEF0_SHIFT
Reserved but undefined (0) bit shift.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_SAMPLING_FREQ_Q_SHIFT
Sampling Frequency (1) bit shift.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_SAMPLING_FREQ_SCALE_FLAG_SHIFT
Sampling Frequency scaling flag bit shift.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_RSVD_BUT_UNDEF1_SHIFT
Reserved but undefined (1) bit shift.
XI2S_RX_AES_STS_ALPHANUM_CH_ORG_DATA_BYTEO_MASK
Alphanumeric channel origin data register(s) byte0 mask.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_ALPHANUM_CH_ORG_DATA_BYTE1_MASK
Alphanumeric channel origin data register(s) byte1 mask.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_ALPHANUM_CH_ORG_DATA_BYTE1_SHIFT
Alphanumeric channel origin data register(s) byte1 shift.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_ALPHANUM_CH_ORG_DATA_BYTE2_MASK
Alphanumeric channel origin data register(s) byte2 mask.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_ALPHANUM_CH_ORG_DATA_BYTE2_SHIFT
Alphanumeric channel origin data register(s) byte2 shift.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_ALPHANUM_CH_ORG_DATA_BYTE3_MASK
Alphanumeric channel origin data register(s) byte3 mask.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_ALPHANUM_CH_ORG_DATA_BYTE3_SHIFT
Alphanumeric channel origin data register(s) byte3 shift.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_ALPHANUM_CH_DEST_DATA_BYTEO_MASK
Alphanumeric channel destination data register(s) byte0 mask.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_ALPHANUM_CH_DEST_DATA_BYTE1_MASK
Alphanumeric channel destination data register(s) byte1 mask.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_ALPHANUM_CH_DEST_DATA_BYTE1_SHIFT
Alphanumeric channel destination data register(s) byte1 shift.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_ALPHANUM_CH_DEST_DATA_BYTE2_MASK
Alphanumeric channel destination data register(s) byte2 mask.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_ALPHANUM_CH_DEST_DATA_BYTE2_SHIFT
Alphanumeric channel destination data register(s) byte2 shift.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_ALPHANUM_CH_DEST_DATA_BYTE3_MASK
Alphanumeric channel destination data register(s) byte3 mask.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_ALPHANUM_CH_DEST_DATA_BYTE3_SHIFT
Alphanumeric channel destination data register(s) byte3 shift.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_LOCAL_SAMPLE_ADDRESS_CODE_BYTEO_MASK
Local sample address code register(s) byte0 mask.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_LOCAL_SAMPLE_ADDRESS_CODE_BYTE1_MASK
Local sample address code register(s) byte1 mask.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_LOCAL_SAMPLE_ADDRESS_CODE_BYTE1_SHIFT
Local sample address code register(s) byte1 shift.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_LOCAL_SAMPLE_ADDRESS_CODE_BYTE2_MASK
Local sample address code register(s) byte2 mask.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_LOCAL_SAMPLE_ADDRESS_CODE_BYTE2_SHIFT
Local sample address code register(s) byte2 shift.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_LOCAL_SAMPLE_ADDRESS_CODE_BYTE3_MASK
Local sample address code register(s) byte3 mask.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_LOCAL_SAMPLE_ADDRESS_CODE_BYTE3_SHIFT
Local sample address code register(s) byte3 shift.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_TIME_OF_DAY_SAMPLE_ADDRESS_CODE_BYTEO_MASK
Time-of-day sample address code register(s) byte0 mask.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_TIME_OF_DAY_SAMPLE_ADDRESS_CODE_BYTE1_MASK
Time-of-day sample address code register(s) byte1 mask.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_TIME_OF_DAY_SAMPLE_ADDRESS_CODE_BYTE1_SHIFT
Time-of-day sample address code register(s) byte1 shift.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_TIME_OF_DAY_SAMPLE_ADDRESS_CODE_BYTE2_MASK
Time-of-day sample address code register(s) byte2 mask.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_TIME_OF_DAY_SAMPLE_ADDRESS_CODE_BYTE2_SHIFT
Time-of-day sample address code register(s) byte2 shift.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_TIME_OF_DAY_SAMPLE_ADDRESS_CODE_BYTE3_MASK
Time-of-day sample address code register(s) byte3 mask.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_AES_STS_TIME_OF_DAY_SAMPLE_ADDRESS_CODE_BYTE3_SHIFT
Time-of-day sample address code register(s) byte3 shift.
Referenced by XI2s_Rx_SetAesChStat.
XI2S_RX_LOG_ITEM_BUFFER_SIZE
@ name Log Item Buffer Size
XI2s_Rx_LogEvt
AES Block Complete Event.
XI2S_RX_CORE_VER_OFFSET
Core Version Register.
XI2S_RX_CORE_CFG_OFFSET
Core Configuration Register.
XI2S_RX_CORE_CTRL_OFFSET
Core Control Register.
Referenced by XI2s_Rx_Enable, XI2s_Rx_Justify, XI2s_Rx_JustifyEnable, XI2s_Rx_LatchAesChannelStatus.
XI2S_RX_IRQCTRL_OFFSET
Interrupt Control Register.
Referenced by XI2s_Rx_IntrDisable, XI2s_Rx_IntrEnable, XI2s_Rx_IntrHandler.
XI2S_RX_IRQSTS_OFFSET
Interrupt Status Register.
Referenced by XI2s_Rx_IntrHandler.
XI2S_RX_TMR_CTRL_OFFSET
XI2S Timing Control Register.
Referenced by XI2s_Rx_SetSclkOutDiv.
XI2S_RX_CH01_OFFSET
Audio Channel 0/1 Control Register.
Referenced by XI2s_Rx_SetChMux.
XI2S_RX_CH23_OFFSET
Audio Channel 2/3 Control Register.
XI2S_RX_CH45_OFFSET
Audio Channel 4/5 Control Register.
XI2S_RX_CH67_OFFSET
Audio Channel 6/7 Control Register.
XI2S_RX_AES_CHSTS0_OFFSET
AES Channel Status 0 Register.
Referenced by XI2s_Rx_ClrAesChStatRegs, XI2s_Rx_SetAesChStatus.
XI2S_RX_AES_CHSTS1_OFFSET
AES Channel Status 1 Register.
Referenced by XI2s_Rx_ClrAesChStatRegs.
XI2S_RX_AES_CHSTS2_OFFSET
AES Channel Status 2 Register.
Referenced by XI2s_Rx_ClrAesChStatRegs.
XI2S_RX_AES_CHSTS3_OFFSET
AES Channel Status 3 Register.
Referenced by XI2s_Rx_ClrAesChStatRegs.
XI2S_RX_AES_CHSTS4_OFFSET
AES Channel Status 4 Register.
Referenced by XI2s_Rx_ClrAesChStatRegs.
XI2S_RX_AES_CHSTS5_OFFSET
AES Channel Status 5 Register.
Referenced by XI2s_Rx_ClrAesChStatRegs.
XI2S_RX_REG_CFG_MSTR_SHIFT
Is XI2S Master bit shift.
XI2S_RX_REG_CFG_MSTR_MASK
Is XI2S Master mask.
XI2S_RX_REG_CFG_NUM_CH_SHIFT
Maximum number of channels bit shift.
XI2S_RX_REG_CFG_NUM_CH_MASK
Maximum number of channels mask.
XI2S_RX_REG_CFG_DWDTH_SHIFT
XI2S Data Width bit shift.
XI2S_RX_REG_CFG_DWDTH_MASK
XI2S Data Width mask.
XI2S_RX_REG_CTRL_EN_SHIFT
Module Enable bit shift.
XI2S_RX_REG_CTRL_EN_MASK
Module Enable mask.
Referenced by XI2s_Rx_Enable.
XI2S_RX_REG_CTRL_JFE_SHIFT
Justification Enable or Disable shift.
XI2S_RX_REG_CTRL_JFE_MASK
Justification Enable or Disable mask.
Referenced by XI2s_Rx_JustifyEnable.
XI2S_RX_REG_CTRL_LORJF_SHIFT
Left or Right Justification shift.
XI2S_RX_REG_CTRL_LORJF_MASK
Left or Right Justification mask.
Referenced by XI2s_Rx_Justify.
XI2S_RX_REG_CTRL_LATCH_CHSTS_SHIFT
Latch AES Channel Status bit shift.
XI2S_RX_REG_CTRL_LATCH_CHSTS_MASK
Latch AES Channel Status mask.
Referenced by XI2s_Rx_LatchAesChannelStatus.
XI2S_RX_INTR_AES_BLKCMPLT_SHIFT
AES Block Complete Interrupt bit shift.
XI2S_RX_INTR_AES_BLKCMPLT_MASK
AES Block Complete Interrupt mask.
Referenced by XI2s_Rx_IntrHandler.
XI2S_RX_INTR_AUDOVRFLW_SHIFT
Audio Overflow Detected Interrupt bit shift.
XI2S_RX_INTR_AUDOVRFLW_MASK
Audio Overflow Detected Interrupt mask.
Referenced by XI2s_Rx_IntrHandler.
XI2S_RX_GINTR_EN_SHIFT
Global Interrupt Enable bit shift.
XI2S_RX_GINTR_EN_MASK
Global Interrupt Enable mask.
XI2S_RX_REG_TMR_SCLKDIV_SHIFT
SClk Divider bit shift.
XI2S_RX_REG_TMR_SCLKDIV_MASK
SClk Divider mask.
XI2S_RX_REG_CHCTRL_CHMUX_SHIFT
Channel MUX bit shift.
XI2S_RX_REG_CHCTRL_CHMUX_MASK
Channel MUX mask.
XI2s_Rx_In32
Input Operations.
XI2s_Rx_Out32
Output Operations.
XI2s_Rx_ReadReg
This macro reads a value from a XI2s Receiver register.
A 32 bit read is performed. If the component is implemented in a smaller width, only the least significant data is read from the register. The most significant data will be read as 0. BaseAddress is the base address of the XI2s Receiver core instance. RegOffset is the register offset of the register (defined at the top of this file). The 32-bit value of the register. C-style signature: u32 XI2s_Rx_ReadReg(u32 BaseAddress, u32 RegOffset)
Referenced by XI2s_Rx_Enable, XI2s_Rx_IntrDisable, XI2s_Rx_IntrEnable, XI2s_Rx_IntrHandler, XI2s_Rx_Justify, XI2s_Rx_JustifyEnable, XI2s_Rx_LatchAesChannelStatus.
XI2s_Rx_WriteReg
This macro writes a value to a XI2s Receiver register.
A 32 bit write is performed. If the component is implemented in a smaller width, only the least significant data is written. BaseAddress is the base address of the XI2s Receiver core instance. RegOffset is the register offset of the register (defined at the top of this file) to be written. Data is the 32-bit value to write into the register. None. C-style signature: void XI2s_Rx_WriteReg(u32 BaseAddress, u32 RegOffset, u32 Data)
Referenced by XI2s_Rx_ClrAesChStatRegs, XI2s_Rx_Enable, XI2s_Rx_IntrDisable, XI2s_Rx_IntrEnable, XI2s_Rx_Justify, XI2s_Rx_JustifyEnable, XI2s_Rx_LatchAesChannelStatus, XI2s_Rx_SetAesChStatus, XI2s_Rx_SetChMux, XI2s_Rx_SetSclkOutDiv.
XI2s_Rx_ChMuxInput
Channel disabled.
XI2s_Rx_Justification
Left Justification is enabled.
typedef void(* XI2s_Rx_Callback)(void *CallbackRef))(void *CallbackRef)
Callback function pointer type for I2S RX events.
This typedef defines the signature for callback functions that handle I2S receiver (RX) events. The callback is invoked when specific I2S RX events occur during operation. CallbackRef A void pointer to user-defined callback reference data. This pointer is typically used to pass context or state information to the callback handler. The actual callback implementation should cast CallbackRef to the appropriate data type as needed for application-specific processing.
XI2srx_Config XI2srx_ConfigTable[][]
int XI2s_Rx_CfgInitialize(XI2s_Rx *InstancePtr, XI2srx_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the XI2s Receiver.
This function must be called prior to using the core. Initialization of the XI2s Receiver includes setting up the instance data, and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the XI2s Receiver instance. CfgPtr points to the configuration structure associated with the XI2s Receiver. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS : if successful.XST_FAILURE : if version mismatched. None.
References XI2s_Rx::Config, XI2s_Rx::IsReady, XI2s_Rx_Enable, XI2s_Rx_SelfTest.
Referenced by I2srx_SelfTest_Example, XI2s_Rx_Initialize.
void XI2s_Rx_Enable(XI2s_Rx *InstancePtr, u8 Enable)
This function enables/disables the XI2s Receiver.
InstancePtr is a pointer to the XI2s Receiver instance. Enable specifies TRUE/FALSE value to either enable or disable the XI2s Receiver.
References XI2s_Rx::Config, XI2s_Rx::IsStarted, XI2S_RX_CORE_CTRL_OFFSET, XI2s_Rx_ReadReg, XI2S_RX_REG_CTRL_EN_MASK, XI2s_Rx_WriteReg.
Referenced by XI2s_Rx_CfgInitialize.
void XI2s_Rx_LatchAesChannelStatus(XI2s_Rx *InstancePtr)
This function requests the XI2s Receiver to latch the AES Channel Status bits from the registers.
InstancePtr is a pointer to the XI2s Receiver instance.
References XI2s_Rx::Config, XI2S_RX_CORE_CTRL_OFFSET, XI2s_Rx_ReadReg, XI2S_RX_REG_CTRL_LATCH_CHSTS_MASK, XI2s_Rx_WriteReg.
void XI2s_Rx_IntrEnable(XI2s_Rx *InstancePtr, u32 Mask)
This function enables the specified interrupt of the XI2s Receiver.
InstancePtr is a pointer to the XI2s Receiver instance. Mask is a bit mask of the interrupts to be enabled. XI2srx_HW for the available interrupt masks.
References XI2s_Rx::Config, XI2S_RX_IRQCTRL_OFFSET, XI2s_Rx_ReadReg, XI2s_Rx_WriteReg.
void XI2s_Rx_IntrDisable(XI2s_Rx *InstancePtr, u32 Mask)
This function disables the specified interrupt of the XI2s Receiver.
InstancePtr is a pointer to the XI2s Receiver instance. Mask is a bit mask of the interrupts to be disabled. XI2s_Receiver_HW for the available interrupt masks.
References XI2s_Rx::Config, XI2S_RX_IRQCTRL_OFFSET, XI2s_Rx_ReadReg, XI2s_Rx_WriteReg.
int XI2s_Rx_SetChMux(XI2s_Rx *InstancePtr, XI2s_Rx_ChannelId ChID, XI2s_Rx_ChMuxInput InputSource)
This function sets the input source for the specified AXI-Stream channel pair.
InstancePtr is a pointer to the XI2s Receiver instance. ChID specifies the AXI-Stream channel pair 0 : AXI-Stream channel 0 and 11 : AXI-Stream channel 2 and 32 : AXI-Stream channel 4 and 53 : AXI-Stream channel 6 and 7 InputSource specifies the input source XST_SUCCESS : if successful.XST_FAILURE : if the AXI-Stream channel pair is invalid.
References XI2s_Rx::Config, XI2S_RX_CH01_OFFSET, XI2S_RX_CHMUX_WAVEGEN, XI2S_RX_CHMUX_XI2S_01, XI2S_RX_CHMUX_XI2S_23, XI2S_RX_CHMUX_XI2S_45, XI2S_RX_CHMUX_XI2S_67, XI2S_RX_NUM_CHANNELS, XI2s_Rx_WriteReg.
u32 XI2s_Rx_SetSclkOutDiv(XI2s_Rx *InstancePtr, u32 MClk, u32 Fs)
This function calculates the SCLK Output divider value of the I2s timing generator.
InstancePtr is a pointer to the I2s Receiver instance. MClk is the frequency of the MClk. Fs is the sampling frequency of the system. Divider value for the SCLK generation MCLK/SCLK = SCLKOUT_DIV x 2 i.e. MCLK = 384xFs, SCLK = 48xFs (2x24bits) -> SCLKOUT_DIV = MCLK/SCLK/2 = 4 Valid values are 1 through 15. - XST_FAILURE if SCLK Output divider is not calculated to be a positive integer. XST_SUCCESS, otherwise.
References XI2s_Rx::Config, XI2srx_Config::DWidth, XI2S_RX_TMR_CTRL_OFFSET, XI2s_Rx_WriteReg.
void XI2s_Rx_SetAesChStatus(XI2s_Rx *InstancePtr, u8 *AesChStatusBuf)
This function sets the AES Channel Status bits to insert.
InstancePtr is a pointer to the XI2s Receiver instance. AesChStatusBuf is a pointer to a buffer containing the AES channel status bits.
References XI2s_Rx::Config, XI2S_RX_AES_CHSTS0_OFFSET, XI2s_Rx_WriteReg.
void XI2s_Rx_ClrAesChStatRegs(XI2s_Rx *InstancePtr)
This function clears the captured AES Channel Status bits.
This will clear all the 6 channel status registers. InstancePtr is a pointer to the XI2s_Rx core instance.
References XI2S_RX_AES_CHSTS0_OFFSET, XI2S_RX_AES_CHSTS1_OFFSET, XI2S_RX_AES_CHSTS2_OFFSET, XI2S_RX_AES_CHSTS3_OFFSET, XI2S_RX_AES_CHSTS4_OFFSET, XI2S_RX_AES_CHSTS5_OFFSET, XI2s_Rx_WriteReg.
void XI2s_Rx_JustifyEnable(XI2s_Rx *InstancePtr, u8 Enable)
This function enables/disables the justification.
InstancePtr is a pointer to the XI2s Receiver instance. Enable specifies TRUE/FALSE value to either enable or disable the justification.
References XI2s_Rx::Config, XI2S_RX_CORE_CTRL_OFFSET, XI2s_Rx_ReadReg, XI2S_RX_REG_CTRL_JFE_MASK, XI2s_Rx_WriteReg.
void XI2s_Rx_Justify(XI2s_Rx *InstancePtr, XI2s_Rx_Justification Justify)
This function is to enable right/left justification.
InstancePtr is a pointer to the XI2s Receiver instance. Justify is a enum to select the left or right justification. XI2S_RX_JUSTIFY_LEFT : Left justificationXI2S_RX_JUSTIFY_RIGHT : Right justification
References XI2s_Rx::Config, XI2S_RX_CORE_CTRL_OFFSET, XI2s_Rx_ReadReg, XI2S_RX_REG_CTRL_LORJF_MASK, XI2s_Rx_WriteReg.
static u32 XI2s_Rx_GetVersion(XI2s_Rx *InstancePtr)
This inline function reads the XI2s Receiver version.
InstancePtr is a pointer to the XI2s_Rx core instance. Version.
static void XI2s_Rx_IntrClear(XI2s_Rx *InstancePtr, u32 Mask)
This inline function clears the specified interrupt of the XI2s Receiver.
InstancePtr is a pointer to the XI2s_Rx core instance. Mask is a bit mask of the interrupts to be cleared. None. XI2srx_HW for the available interrupt masks.
static void XI2s_Rx_LogEnable(XI2s_Rx *InstancePtr)
This inline function enables the XI2s Receiver logging.
InstancePtr is a pointer to the XI2s_Rx core instance. None.
static void XI2s_Rx_LogDisable(XI2s_Rx *InstancePtr)
This inline function disables the XI2s Receiver logging.
InstancePtr is a pointer to the XI2s_Rx core instance. None.
int XI2s_Rx_SelfTest(XI2s_Rx *InstancePtr)
Runs a self-test on the driver/device.
The self-test reads the version register, data width , max channels, Master or slave configuration and verifies the values InstancePtr is a pointer to the XI2s_Rx instance. XST_SUCCESS if successful i.e. if the self test passes.XST_FAILURE if unsuccessful i.e. if the self test fails None.
References XI2s_Rx_GetMaxChannels, XI2s_Rx_IsXI2sMaster.
Referenced by XI2s_Rx_CfgInitialize.
XI2srx_Config * XI2s_Rx_LookupConfig(UINTPTR BaseAddress)
This function returns a reference to an XI2srx_Config structure based on the core id, DeviceId.
The return value will refer to an entry in the device configuration table defined in the xi2srx_g.c file. DeviceId is the unique core ID of the XI2s Receiver core for the lookup operation. returns a reference to a config record in the configuration table corresponding to DeviceId, or NULL if no match is found. None.
Referenced by I2srx_SelfTest_Example, XI2s_Rx_Initialize.
int XI2s_Rx_Initialize(XI2s_Rx *InstancePtr, u16 DeviceId)
Initializes a specific XI2s_Rx instance such that the driver is ready to use.
InstancePtr is a pointer to the XI2s_Rx instance to be worked on. DeviceId is the unique id of the device controlled by this XI2s_Rx instance. Passing in a device id associates the generic XI2s_Rx instance to a specific device, as chosen by the caller or application developer. XST_SUCCESS if successful.XST_DEVICE_NOT_FOUND if the device was not found in the configuration such that initialization could not be accomplished.XST_INVALID_VERSION if version mismatched
References XI2s_Rx_CfgInitialize, XI2s_Rx_LookupConfig.
void XI2s_Rx_IntrHandler(void *InstancePtr)
This function is the interrupt handler for the XI2s Receiver driver.
This handler reads the pending interrupt from the XI2s Receiver peripheral, determines the source of the interrupts, clears the interrupts and calls callbacks accordingly. InstancePtr is a pointer to the XI2s_Rx instance. None.
References XI2s_Rx::AudOverflowHandler, XI2s_Rx::Config, XI2s_Rx::IsReady, XI2S_RX_AES_BLKCMPLT_EVT, XI2S_RX_AUD_OVERFLOW_EVT, XI2S_RX_INTR_AES_BLKCMPLT_MASK, XI2S_RX_INTR_AUDOVRFLW_MASK, XI2S_RX_IRQCTRL_OFFSET, XI2S_RX_IRQSTS_OFFSET, XI2s_Rx_LogWrite, XI2s_Rx_ReadReg.
int XI2s_Rx_SetHandler(XI2s_Rx *InstancePtr, XI2s_Rx_HandlerType HandlerType, XI2s_Rx_Callback FuncPtr, void *CallbackRef)
This function installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function -------------------------------- ---------------------------------- (XI2S_RX_HANDLER_AES_BLKCMPLT) AesBlkCmpltHandler (XI2S_RX_HANDLER_AUD_OVERFLOW) AudOverflowHandler InstancePtr is a pointer to the XI2s_Rx core instance. HandlerType specifies the type of handler. FuncPtr is a pointer to the callback function. CallbackRef is a reference pointer passed on actual calling of the callback function. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XI2s_Rx::AudOverflowHandler, XI2S_RX_HANDLER_AES_BLKCMPLT, XI2S_RX_HANDLER_AUD_OVRFLW, XI2S_RX_NUM_HANDLERS.
void XI2s_Rx_LogDisplay(XI2s_Rx *InstancePtr)
This function prints the contents of the logging buffer.
InstancePtr is a pointer to the XI2s_Rx instance. None.
References XI2s_Rx::Config, XI2s_Rx_LogItem::Event, XI2S_RX_AES_BLKCMPLT_EVT, XI2S_RX_AUD_OVERFLOW_EVT, XI2S_RX_LOG_EVT_INVALID, XI2s_Rx_LogRead.
void XI2s_Rx_LogReset(XI2s_Rx *InstancePtr)
This function clears the contents of the logging buffer.
InstancePtr is a pointer to the XI2s_Rx instance. None.
References XI2s_Rx_Log::Head, XI2s_Rx_Log::IsEnabled, XI2s_Rx::Log, XI2s_Rx_Log::Tail.
void XI2s_Rx_LogWrite(XI2s_Rx *InstancePtr, XI2s_Rx_LogEvt Event, u8 Data)
This function writes XI2s Receiver logs into the buffer.
InstancePtr is a pointer to the XI2s_Rx instance. Event is the log event type. Data is the log data. Log write is done only if the log is enabled.
References XI2s_Rx_LogItem::Data, XI2s_Rx_LogItem::Event, XI2s_Rx_Log::Head, XI2s_Rx_Log::IsEnabled, XI2s_Rx_Log::Items, XI2s_Rx::Log, XI2s_Rx_Log::Tail, XI2S_RX_LOG_EVT_INVALID.
Referenced by XI2s_Rx_IntrHandler.
XI2s_Rx_LogItem * XI2s_Rx_LogRead(XI2s_Rx *InstancePtr)
This function returns the next item in the logging buffer.
InstancePtr is a pointer to the XI2s_Rx instance. When the buffer is filled, the next log item is returned. When the buffer is empty, NULL is returned. None.
References XI2s_Rx_Log::Head, XI2s_Rx_Log::Items, XI2s_Rx::Log, XI2s_Rx_Log::Tail.
Referenced by XI2s_Rx_LogDisplay.
void XI2s_Rx_SetAesChStat(u32 I2srx_SrcBuf[], u8 I2srx_DstBuf[])
This function reads the source buffer and writes to a destination buffer.
Before calling this API user application should write 192 bits i.e. 24 bytes to the array I2srx_SrcBuf. I2srx_SrcBuf is the source buffer which has 192 channel status bits. I2srx_DstBuf is the destination buffer to store the 24 bytes.
References XI2S_RX_AES_STS_ALPHANUM_CH_DEST_DATA_BYTE1_MASK, XI2S_RX_AES_STS_ALPHANUM_CH_DEST_DATA_BYTE1_SHIFT, XI2S_RX_AES_STS_ALPHANUM_CH_DEST_DATA_BYTE2_MASK, XI2S_RX_AES_STS_ALPHANUM_CH_DEST_DATA_BYTE2_SHIFT, XI2S_RX_AES_STS_ALPHANUM_CH_DEST_DATA_BYTE3_MASK, XI2S_RX_AES_STS_ALPHANUM_CH_DEST_DATA_BYTE3_SHIFT, XI2S_RX_AES_STS_ALPHANUM_CH_DEST_DATA_BYTEO_MASK, XI2S_RX_AES_STS_ALPHANUM_CH_ORG_DATA_BYTE1_MASK, XI2S_RX_AES_STS_ALPHANUM_CH_ORG_DATA_BYTE1_SHIFT, XI2S_RX_AES_STS_ALPHANUM_CH_ORG_DATA_BYTE2_MASK, XI2S_RX_AES_STS_ALPHANUM_CH_ORG_DATA_BYTE2_SHIFT, XI2S_RX_AES_STS_ALPHANUM_CH_ORG_DATA_BYTE3_MASK, XI2S_RX_AES_STS_ALPHANUM_CH_ORG_DATA_BYTE3_SHIFT, XI2S_RX_AES_STS_ALPHANUM_CH_ORG_DATA_BYTEO_MASK, XI2S_RX_AES_STS_AUDIO_SIG_PRE_EMPH_SHIFT, XI2S_RX_AES_STS_INDICATE_ALIGN_LEVEL_SHIFT, XI2S_RX_AES_STS_LINEAR_PCM_ID_SHIFT, XI2S_RX_AES_STS_LOCAL_SAMPLE_ADDRESS_CODE_BYTE1_MASK, XI2S_RX_AES_STS_LOCAL_SAMPLE_ADDRESS_CODE_BYTE1_SHIFT, XI2S_RX_AES_STS_LOCAL_SAMPLE_ADDRESS_CODE_BYTE2_MASK, XI2S_RX_AES_STS_LOCAL_SAMPLE_ADDRESS_CODE_BYTE2_SHIFT, XI2S_RX_AES_STS_LOCAL_SAMPLE_ADDRESS_CODE_BYTE3_MASK, XI2S_RX_AES_STS_LOCAL_SAMPLE_ADDRESS_CODE_BYTE3_SHIFT, XI2S_RX_AES_STS_LOCAL_SAMPLE_ADDRESS_CODE_BYTEO_MASK, XI2S_RX_AES_STS_LOCK_INDICATION_SHIFT, XI2S_RX_AES_STS_MC_CH_MODE_NUM_SHIFT, XI2S_RX_AES_STS_MC_CH_MODE_SHIFT, XI2S_RX_AES_STS_RSVD_BUT_UNDEF0_SHIFT, XI2S_RX_AES_STS_SAMPLING_FREQ_E_SHIFT, XI2S_RX_AES_STS_SAMPLING_FREQ_Q_SHIFT, XI2S_RX_AES_STS_SAMPLING_FREQ_SCALE_FLAG_SHIFT, XI2S_RX_AES_STS_SRC_WORD_LENGTH_SHIFT, XI2S_RX_AES_STS_TIME_OF_DAY_SAMPLE_ADDRESS_CODE_BYTE1_MASK, XI2S_RX_AES_STS_TIME_OF_DAY_SAMPLE_ADDRESS_CODE_BYTE1_SHIFT, XI2S_RX_AES_STS_TIME_OF_DAY_SAMPLE_ADDRESS_CODE_BYTE2_MASK, XI2S_RX_AES_STS_TIME_OF_DAY_SAMPLE_ADDRESS_CODE_BYTE2_SHIFT, XI2S_RX_AES_STS_TIME_OF_DAY_SAMPLE_ADDRESS_CODE_BYTE3_MASK, XI2S_RX_AES_STS_TIME_OF_DAY_SAMPLE_ADDRESS_CODE_BYTE3_SHIFT, XI2S_RX_AES_STS_TIME_OF_DAY_SAMPLE_ADDRESS_CODE_BYTEO_MASK, XI2S_RX_AES_STS_USR_BITS_MGMT_SHIFT.
static u32 XI2s_Rx_GetXI2sDataWidth(XI2s_Rx *InstancePtr)
This inline function returns the XI2s data width.
InstancePtr is a pointer to the XI2s_Rx core instance. The XI2s data width in number of bits
XI2S_RX_CLK_MASK
XI2S_RX_CORE_VER
XI2s_Rx_GetMaxChannels
This macro reads the maximum number of XI2s channels available.
InstancePtr is a pointer to the XI2s_Rx core instance. Maximum number of XI2s Channels. C-style signature: u32 XI2s_Rx_GetMaxChannels(XI2s_Rx *InstancePtr)
Referenced by XI2s_Rx_SelfTest.
XI2s_Rx_IsXI2sMaster
This macro returns the XI2s operating mode.
InstancePtr is a pointer to the XI2s_Rx core instance. TRUE : is XI2s MasterFALSE : is XI2s Slave C-style signature: u8 XI2s_Rx_IsXI2sMaster(XI2s_Rx *InstancePtr)
Referenced by XI2s_Rx_SelfTest.