xi2srx.c
XI2S_RX_CLK_MASK
int XI2s_Rx_CfgInitialize(XI2s_Rx *InstancePtr, XI2srx_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the XI2s Receiver.
This function must be called prior to using the core. Initialization of the XI2s Receiver includes setting up the instance data, and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the XI2s Receiver instance. CfgPtr points to the configuration structure associated with the XI2s Receiver. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS : if successful.XST_FAILURE : if version mismatched. None.
References XI2s_Rx::Config, XI2s_Rx::IsReady, XI2s_Rx_Enable, XI2s_Rx_SelfTest.
Referenced by I2srx_SelfTest_Example, XI2s_Rx_Initialize.
void XI2s_Rx_Enable(XI2s_Rx *InstancePtr, u8 Enable)
This function enables/disables the XI2s Receiver.
InstancePtr is a pointer to the XI2s Receiver instance. Enable specifies TRUE/FALSE value to either enable or disable the XI2s Receiver.
References XI2s_Rx::Config, XI2s_Rx::IsStarted, XI2S_RX_CORE_CTRL_OFFSET, XI2s_Rx_ReadReg, XI2S_RX_REG_CTRL_EN_MASK, XI2s_Rx_WriteReg.
Referenced by XI2s_Rx_CfgInitialize.
void XI2s_Rx_LatchAesChannelStatus(XI2s_Rx *InstancePtr)
This function requests the XI2s Receiver to latch the AES Channel Status bits from the registers.
InstancePtr is a pointer to the XI2s Receiver instance.
References XI2s_Rx::Config, XI2S_RX_CORE_CTRL_OFFSET, XI2s_Rx_ReadReg, XI2S_RX_REG_CTRL_LATCH_CHSTS_MASK, XI2s_Rx_WriteReg.
void XI2s_Rx_IntrEnable(XI2s_Rx *InstancePtr, u32 Mask)
This function enables the specified interrupt of the XI2s Receiver.
InstancePtr is a pointer to the XI2s Receiver instance. Mask is a bit mask of the interrupts to be enabled. XI2srx_HW for the available interrupt masks.
References XI2s_Rx::Config, XI2S_RX_IRQCTRL_OFFSET, XI2s_Rx_ReadReg, XI2s_Rx_WriteReg.
void XI2s_Rx_IntrDisable(XI2s_Rx *InstancePtr, u32 Mask)
This function disables the specified interrupt of the XI2s Receiver.
InstancePtr is a pointer to the XI2s Receiver instance. Mask is a bit mask of the interrupts to be disabled. XI2s_Receiver_HW for the available interrupt masks.
References XI2s_Rx::Config, XI2S_RX_IRQCTRL_OFFSET, XI2s_Rx_ReadReg, XI2s_Rx_WriteReg.
int XI2s_Rx_SetChMux(XI2s_Rx *InstancePtr, XI2s_Rx_ChannelId ChID, XI2s_Rx_ChMuxInput InputSource)
This function sets the input source for the specified AXI-Stream channel pair.
InstancePtr is a pointer to the XI2s Receiver instance. ChID specifies the AXI-Stream channel pair 0 : AXI-Stream channel 0 and 11 : AXI-Stream channel 2 and 32 : AXI-Stream channel 4 and 53 : AXI-Stream channel 6 and 7 InputSource specifies the input source XST_SUCCESS : if successful.XST_FAILURE : if the AXI-Stream channel pair is invalid.
References XI2s_Rx::Config, XI2S_RX_CH01_OFFSET, XI2S_RX_CHMUX_WAVEGEN, XI2S_RX_CHMUX_XI2S_01, XI2S_RX_CHMUX_XI2S_23, XI2S_RX_CHMUX_XI2S_45, XI2S_RX_CHMUX_XI2S_67, XI2S_RX_NUM_CHANNELS, XI2s_Rx_WriteReg.
u32 XI2s_Rx_SetSclkOutDiv(XI2s_Rx *InstancePtr, u32 MClk, u32 Fs)
This function calculates the SCLK Output divider value of the I2s timing generator.
InstancePtr is a pointer to the I2s Receiver instance. MClk is the frequency of the MClk. Fs is the sampling frequency of the system. Divider value for the SCLK generation MCLK/SCLK = SCLKOUT_DIV x 2 i.e. MCLK = 384xFs, SCLK = 48xFs (2x24bits) -> SCLKOUT_DIV = MCLK/SCLK/2 = 4 Valid values are 1 through 15. - XST_FAILURE if SCLK Output divider is not calculated to be a positive integer. XST_SUCCESS, otherwise.
References XI2s_Rx::Config, XI2srx_Config::DWidth, XI2S_RX_TMR_CTRL_OFFSET, XI2s_Rx_WriteReg.
void XI2s_Rx_SetAesChStatus(XI2s_Rx *InstancePtr, u8 *AesChStatusBuf)
This function sets the AES Channel Status bits to insert.
InstancePtr is a pointer to the XI2s Receiver instance. AesChStatusBuf is a pointer to a buffer containing the AES channel status bits.
References XI2s_Rx::Config, XI2S_RX_AES_CHSTS0_OFFSET, XI2s_Rx_WriteReg.
void XI2s_Rx_ClrAesChStatRegs(XI2s_Rx *InstancePtr)
This function clears the captured AES Channel Status bits.
This will clear all the 6 channel status registers. InstancePtr is a pointer to the XI2s_Rx core instance.
References XI2S_RX_AES_CHSTS0_OFFSET, XI2S_RX_AES_CHSTS1_OFFSET, XI2S_RX_AES_CHSTS2_OFFSET, XI2S_RX_AES_CHSTS3_OFFSET, XI2S_RX_AES_CHSTS4_OFFSET, XI2S_RX_AES_CHSTS5_OFFSET, XI2s_Rx_WriteReg.
void XI2s_Rx_JustifyEnable(XI2s_Rx *InstancePtr, u8 Enable)
This function enables/disables the justification.
InstancePtr is a pointer to the XI2s Receiver instance. Enable specifies TRUE/FALSE value to either enable or disable the justification.
References XI2s_Rx::Config, XI2S_RX_CORE_CTRL_OFFSET, XI2s_Rx_ReadReg, XI2S_RX_REG_CTRL_JFE_MASK, XI2s_Rx_WriteReg.
void XI2s_Rx_Justify(XI2s_Rx *InstancePtr, XI2s_Rx_Justification Justify)
This function is to enable right/left justification.
InstancePtr is a pointer to the XI2s Receiver instance. Justify is a enum to select the left or right justification. XI2S_RX_JUSTIFY_LEFT : Left justificationXI2S_RX_JUSTIFY_RIGHT : Right justification
References XI2s_Rx::Config, XI2S_RX_CORE_CTRL_OFFSET, XI2s_Rx_ReadReg, XI2S_RX_REG_CTRL_LORJF_MASK, XI2s_Rx_WriteReg.