dsi
XDSI_CCR_OFFSET
Core Configuration Register Offset.
XDSI_PCR_OFFSET
Protocol Configuration Register Offset.
Referenced by XDsi_DefaultConfigure, XDsi_GetConfigParams, XDsi_SelfTest, XDsi_SetCustomVideoInterfaceTiming, XDsi_SetVideoInterfaceTiming.
XDSI_GIER_OFFSET
Global Interrupt Register Offset.
XDSI_ISR_OFFSET
Interrupt Status Register.
XDSI_IER_OFFSET
Interrupt Enable Register.
XDSI_STATUS_OFFSET
Status Register.
XDSI_COMMAND_OFFSET
Packet Entry to command Queue.
Referenced by XDsi_SendShortPacket.
XDSI_DATA_OFFSET
Packet Data to data Queue.
Referenced by XDsi_SendLongPacket.
XDSI_TIME1_OFFSET
Time 1 Offset.
Referenced by XDsi_GetConfigParams, XDsi_SetCustomVideoInterfaceTiming, XDsi_SetVideoInterfaceTiming.
XDSI_TIME2_OFFSET
Time 2 Offset.
Referenced by XDsi_GetConfigParams, XDsi_SetCustomVideoInterfaceTiming, XDsi_SetVideoInterfaceTiming.
XDSI_TIME3_OFFSET
Time 3 Offset.
Referenced by XDsi_GetConfigParams, XDsi_SetCustomVideoInterfaceTiming, XDsi_SetVideoInterfaceTiming.
XDSI_TIME4_OFFSET
Time 4 Offset.
Referenced by XDsi_GetConfigParams, XDsi_SetCustomVideoInterfaceTiming, XDsi_SetVideoInterfaceTiming.
XDSI_LTIME_OFFSET
Total Line Timing Offset.
Referenced by XDsi_GetConfigParams.
XDSI_BLLP_TIME_OFFSET
BLLP Time duration Offset.
Referenced by XDsi_GetConfigParams.
XDSI_TIME5_OFFSET
Time 5 Offset.
Referenced by XDsi_GetConfigParams, XDsi_SetCustomVideoInterfaceTiming, XDsi_SetVideoInterfaceTiming.
XDSI_CCR_RESET_CMD_FIFO_MASK
Command FIFO Reset bit Mask.
XDSI_CCR_RESET_DATA_FIFO_MASK
Data FIFO Reset bit Mask.
XDSI_CCR_CRREADY_MASK
Controller Ready bit Mask.
XDSI_CCR_SOFTRESET_MASK
Soft Reset core bit Mask.
XDSI_CCR_COREENB_MASK
Enable/Disable core Mask.
XDSI_CCR_CORECMDMODE_MASK
Enable/Disable Command/video mode Mask.
XDSI_CCR_CORECMDMODE_SHIFT
Shift for selection of command/video mode.
XDSI_CCR_CRREADY_SHIFT
Shift for Controller Ready.
XDSI_CCR_SOFTRESET_SHIFT
Shift for Soft reset.
XDSI_CCR_COREENB_SHIFT
Shift for Core Enable.
XDSI_PCR_EOTPENABLE_MASK
End of Transmission Mask bit.
Referenced by XDsi_DefaultConfigure, XDsi_GetConfigParams.
XDSI_PCR_PIXELFORMAT_MASK
Pixel Format Type Bit Mask.
XDSI_PCR_BLLPMODE_MASK
Blank packet Mode Bit Mask.
Referenced by XDsi_DefaultConfigure, XDsi_GetConfigParams.
XDSI_PCR_BLLPTYPE_MASK
Blank packet type Bit Mask.
Referenced by XDsi_DefaultConfigure, XDsi_GetConfigParams.
XDSI_PCR_VIDEOMODE_MASK
Video mode Type Bit Mask.
Referenced by XDsi_DefaultConfigure, XDsi_GetConfigParams, XDsi_SetCustomVideoInterfaceTiming, XDsi_SetVideoInterfaceTiming.
XDSI_PCR_ACTLANES_MASK
Active lanes in core.
Referenced by XDsi_SelfTest.
XDSI_PCR_EOTPENABLE_SHIFT
Shift for EOTP Enable.
Referenced by XDsi_DefaultConfigure, XDsi_GetConfigParams.
XDSI_PCR_PIXELFORMAT_SHIFT
Shift for pixel format.
XDSI_PCR_BLLPMODE_SHIFT
Shift for Blank packet Type.
Referenced by XDsi_DefaultConfigure, XDsi_GetConfigParams.
XDSI_PCR_BLLPTYPE_SHIFT
Shift for Blank packet Type.
Referenced by XDsi_DefaultConfigure, XDsi_GetConfigParams.
XDSI_PCR_VIDEOMODE_SHIFT
Shift for Max Lanes.
Referenced by XDsi_DefaultConfigure, XDsi_GetConfigParams, XDsi_SetCustomVideoInterfaceTiming, XDsi_SetVideoInterfaceTiming.
XDSI_PCR_ACTLANES_SHIFT
Shift for Active Lanes.
Referenced by XDsi_SelfTest.
XDSI_UNDER_PROCESS_MASK
Command Underprocess.
XDSI_INPOGRESS_MASK
Command InProgress.
XDSI_WAIT_FOR_DATA_MASK
Wait for Long packet data.
XDSI_FIFO_EMPTY_MASK
FIFO EMPTY.
XDSI_FIFO_FULL_MASK
FIFO FULL.
XDSI_RDY_FOR_LONG_MASK
Readiness for Long packet.
XDSI_RDY_FOR_SHORT_MASK
Readiness for short packet.
XDSI_CMDQ_MASK
Command Queue Vacancy.
XDSI_UNDER_PROCESS_SHIFT
Command Underprocess.
XDSI_INPOGRESS_SHIFT
Command InProgress.
XDSI_WAIT_FOR_DATA_SHIFT
Wait for Long packet data.
XDSI_FIFO_EMPTY_SHIFT
FIFO EMPTY.
XDSI_FIFO_FULL_SHIFT
FIFO FULL.
XDSI_RDY_FOR_LONGPKT_SHIFT
Readiness for Long packet.
XDSI_RDY_FOR_SHORTPKT_SHIFT
Command Queue Vacancy.
XDSI_CMDQ_SHIFT
Shift for Command Queue.
XDSI_TIME1_HSA_MASK
Horizontal timing parameter HSA mask.
Referenced by XDsi_GetConfigParams, XDsi_SetCustomVideoInterfaceTiming, XDsi_SetVideoInterfaceTiming.
XDSI_TIME1_BLLP_BURST_MASK
BLLP Packet size Mask bit.
Referenced by XDsi_GetConfigParams, XDsi_SetCustomVideoInterfaceTiming, XDsi_SetVideoInterfaceTiming.
XDSI_TIME1_HSA_SHIFT
Shift for HSA.
Referenced by XDsi_GetConfigParams, XDsi_SetCustomVideoInterfaceTiming, XDsi_SetVideoInterfaceTiming.
XDSI_TIME1_BLLP_BURST_SHIFT
Shift for BLLP.
Referenced by XDsi_GetConfigParams, XDsi_SetCustomVideoInterfaceTiming, XDsi_SetVideoInterfaceTiming.
XDSI_TIME2_HACT_MASK
Horizontal timing parameter HACT Bit Mask.
Referenced by XDsi_GetConfigParams, XDsi_SetCustomVideoInterfaceTiming, XDsi_SetVideoInterfaceTiming.
XDSI_TIME2_VACT_MASK
Vertical timing parameter VACT.
Referenced by XDsi_GetConfigParams, XDsi_SetCustomVideoInterfaceTiming, XDsi_SetVideoInterfaceTiming.
XDSI_TIME2_HACT_SHIFT
Shift for HACT.
Referenced by XDsi_GetConfigParams, XDsi_SetCustomVideoInterfaceTiming, XDsi_SetVideoInterfaceTiming.
XDSI_TIME2_VACT_SHIFT
Shift for VACT.
Referenced by XDsi_GetConfigParams, XDsi_SetCustomVideoInterfaceTiming, XDsi_SetVideoInterfaceTiming.
XDSI_TIME3_HBP_MASK
Horizontal timing parameter HBP Bit Mask.
Referenced by XDsi_GetConfigParams, XDsi_SetCustomVideoInterfaceTiming, XDsi_SetVideoInterfaceTiming.
XDSI_TIME3_HFP_MASK
Horizontal timing parameter HFP.
Referenced by XDsi_GetConfigParams, XDsi_SetCustomVideoInterfaceTiming, XDsi_SetVideoInterfaceTiming.
XDSI_TIME3_HBP_SHIFT
Shift for HBP.
Referenced by XDsi_GetConfigParams, XDsi_SetCustomVideoInterfaceTiming, XDsi_SetVideoInterfaceTiming.
XDSI_TIME3_HFP_SHIFT
Shift for HFP.
Referenced by XDsi_GetConfigParams, XDsi_SetCustomVideoInterfaceTiming, XDsi_SetVideoInterfaceTiming.
XDSI_TIME4_VSA_MASK
Time 4 Vertical Sync Active Mask.
Referenced by XDsi_GetConfigParams, XDsi_SetCustomVideoInterfaceTiming, XDsi_SetVideoInterfaceTiming.
XDSI_TIME4_VBP_MASK
Vertical timing parameter1 VBP.
Referenced by XDsi_GetConfigParams, XDsi_SetCustomVideoInterfaceTiming, XDsi_SetVideoInterfaceTiming.
XDSI_TIME4_VFP_MASK
Vertical timing parameter1 VFP.
Referenced by XDsi_GetConfigParams, XDsi_SetCustomVideoInterfaceTiming, XDsi_SetVideoInterfaceTiming.
XDSI_TIME4_VSA_SHIFT
Shift for VSA.
Referenced by XDsi_GetConfigParams, XDsi_SetCustomVideoInterfaceTiming, XDsi_SetVideoInterfaceTiming.
XDSI_TIME4_VBP_SHIFT
Shift for VBP.
Referenced by XDsi_GetConfigParams, XDsi_SetCustomVideoInterfaceTiming, XDsi_SetVideoInterfaceTiming.
XDSI_TIME4_VFP_SHIFT
Shift for VFP.
Referenced by XDsi_GetConfigParams, XDsi_SetCustomVideoInterfaceTiming, XDsi_SetVideoInterfaceTiming.
XDSI_TIME5_VFP_MASK
Vertical extended timing parameter1 VFP.
Referenced by XDsi_GetConfigParams, XDsi_SetCustomVideoInterfaceTiming, XDsi_SetVideoInterfaceTiming.
XDSI_TIME5_VFP_SHIFT
Shift for VFP.
Referenced by XDsi_GetConfigParams, XDsi_SetCustomVideoInterfaceTiming, XDsi_SetVideoInterfaceTiming.
XDSI_GIER_GIE_MASK
Global Interrupt Enable bit.
XDSI_GIER_GIE_SHIFT
Shift bits for Global Interrupt Enable.
XDSI_GIER_SET
Enable the Global Interrupts.
XDSI_GIER_RESET
Disable the Global Interrupts.
XDSI_ISR_CMDQ_FIFO_FULL_MASK
Command queue vacancy full.
XDSI_ISR_DATA_ID_ERR_MASK
Unsupported datatype Error.
XDSI_ISR_PXL_UNDR_RUN_MASK
Pixel under run error.
XDSI_ISR_ALLINTR_MASK
All interrupts mask.
XDSI_ISR_DATA_ID_ERR_SHIFT
Shift for Unsupported Data Type.
XDSI_ISR_PXL_UNDR_RUN_SHIFT
Shift for Pixel under run.
XDSI_IER_CMDQ_FIFO_FULL_MASK
Command queue vacancy full.
Referenced by XDsi_IntrHandler.
XDSI_IER_DATA_ID_ERR_MASK
Un supported data type.
Referenced by XDsi_IntrHandler.
XDSI_IER_PXL_UNDR_RUN_MASK
Pixel Under run.
Referenced by XDsi_IntrHandler.
XDSI_IER_ALLINTR_MASK
All interrupts mask.
Referenced by XDsi_InterruptClear, XDsi_InterruptDisable, XDsi_InterruptEnable.
XDSI_IER_DATA_ID_ERR_SHIFT
Shift for Unsupported data type.
XDSI_IER_PXL_UNDR_RUN_SHIFT
Shift for Pixel under run.
XDSI_SPKTR_DT_MASK
Data Type.
XDSI_SPKTR_VC_MASK
Virtual channel number.
XDSI_SPKTR_BYTE1_MASK
BYTE1 mask.
XDSI_SPKTR_BYTE2_MASK
BYTE2 mask.
XDSI_SPKTR_DT_SHIFT
Shift for DataType.
XDSI_SPKTR_VC_SHIFT
Shift for VC.
Referenced by XDsi_SendShortPacket.
XDSI_SPKTR_BYTE1_SHIFT
Shift for BYTE1.
Referenced by XDsi_SendShortPacket.
XDSI_SPKTR_BYTE2_SHIFT
Shift for BYTE2.
Referenced by XDsi_SendShortPacket.
XDSI_LTIME_MASK
Total Line time.
Referenced by XDsi_GetConfigParams.
XDSI_LTIME_SHIFT
Shift for DataType.
Referenced by XDsi_GetConfigParams.
XDSI_BLLP_TIME_MASK
BLLP Size.
Referenced by XDsi_GetConfigParams.
XDSI_BLLP_TIME_SHIFT
Shift for BLLP.
Referenced by XDsi_GetConfigParams.
XDSI_MAX_LANES
Max Lanes supported by DSI.
XDsi_Selection
DSI Tx controller Disable.
XDsi_DsiModeType
Video mode.
XDsi_CmdModePktType
Command mode short packet.
XDsi_VideoMode
Non-burst mode with sync pulses.
typedef void(* XDsi_Callback)(void *CallBackRef, u32 Mask))(void *CallBackRef, u32 Mask)
Callback type for all interrupts defined.
CallBackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. Mask is a bit mask indicating the cause of the event. For current core version, this parameter is "OR" of 0 or more XDSI_ISR_*_MASK constants defined in xdsi_hw.h. None. None.
static void StubErrCallback(void *CallbackRef, u32 ErrorMask)
This routine is a stub for the asynchronous error interrupt callback.
The stub is here in case the upper layer forgot to set the handler. On initialization, Error interrupt handler is set to this callback. It is considered an error for this handler to be invoked. CallbackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. ErrorMask is a bit mask indicating the cause of the error. Its value equals 'OR'ing one or more XDSI_ISR_*_MASK values defined in xdsi_hw.h. None.
u32 XDsi_CfgInitialize(XDsi *InstancePtr, XDsi_Config *CfgPtr, UINTPTR EffectiveAddr)
Initialize the XDsi instance provided by the caller based on the given Config structure.
Initializes the DSI controller instance with hardware configuration information and sets up default callback handlers. InstancePtr is the XDsi instance to operate on. CfgPtr is the device configuration structure containing information about a specific DSI controller (base address, lanes, FIFO size, etc.) EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if initialization was successful.XST_FAILURE if initialization failed. All callback handlers are initialized to stub functions that will assert on invocation. Application must set actual callback handlers using XDsi_SetCallback() if interrupt handling is required. XDsi_SetCallback
References XDsi_Config::BaseAddr, XDsi::CmdQFIFOFullCallback, XDsi::Config, XDsi::ErrorCallback, XDsi::IsReady, XDsi::PixelDataUnderrunCallback, XDsi::UnSupportedDataTypeCallback.
Referenced by DsiSelfTestExample.
void XDsi_Reset(XDsi *InstancePtr)
Perform a soft reset of the DSI controller.
Resets the DSI controller including interrupt status registers, command queue FIFO, and state machine. The controller gracefully waits for current operations to complete before resetting. After reset is released, controller starts from VSS (Vertical Sync Start) packet (new video frame). InstancePtr is the XDsi instance to operate on. None.
u32 XDsi_DefaultConfigure(XDsi *InstancePtr)
Configure default DSI protocol settings.
Configures the DSI controller protocol register with video mode, blank packet mode, blank packet type, and End-of-Transmission (EoTP) packet settings based on the instance parameters. This function sets up the Protocol Control Register (PCR) with the instance VideoMode, BlankPacketType, BLLPMode, and EoTp configuration values. InstancePtr is the XDsi instance to operate on. The instance must have been initialized via XDsi_CfgInitialize(). XST_SUCCESS if configuration was successful. This function assumes the instance is already initialized. The instance member variables (VideoMode, BlankPacketType, BLLPMode, EoTp) must be set before calling this function or it will use default/uninitialized values. XDsi_CfgInitialize, XDsi_Activate
References XDsi::BlankPacketType, XDsi::BLLPMode, XDsi::EoTp, XDsi::IsReady, XDsi::VideoMode, XDSI_PCR_BLLPMODE_MASK, XDSI_PCR_BLLPMODE_SHIFT, XDSI_PCR_BLLPTYPE_MASK, XDSI_PCR_BLLPTYPE_SHIFT, XDSI_PCR_EOTPENABLE_MASK, XDSI_PCR_EOTPENABLE_SHIFT, XDSI_PCR_OFFSET, XDSI_PCR_VIDEOMODE_MASK, XDSI_PCR_VIDEOMODE_SHIFT.
u32 XDsi_Activate(XDsi *InstancePtr, XDsi_Selection Flag)
Enable or disable the DSI controller core.
Activates or deactivates the DSI controller IP core. When enabling (Flag=XDSI_ENABLE), the global interrupt output is set and the core is enabled for packet processing. When disabling (Flag=XDSI_DISABLE), the global interrupt is reset and the core is disabled. InstancePtr is the XDsi instance to operate on. The instance must have been initialized via XDsi_CfgInitialize(). Flag indicates the desired action: XDSI_ENABLE: Enable global interrupt and activate DSI coreXDSI_DISABLE: Reset global interrupt and disable DSI core XST_SUCCESS if enable/disable operation was successful. XST_INVALID_PARAM if an invalid Flag value is provided. Must be called after XDsi_CfgInitialize() and XDsi_DefaultConfigure(). The core must be configured with video mode or command mode settings before activation. XDsi_CfgInitialize, XDsi_DefaultConfigure, XDsi_SetMode
References XDsi::IsReady, XDSI_DISABLE.
void XDsi_SendShortPacket(XDsi *InstancePtr, XDsi_ShortPacket *ShortPacket)
Send a DSI short packet to the controller.
Sends a DSI short packet (up to 2 data bytes) to the DSI controller via the Generic Short Packet Register. The function packs the Virtual Channel ID, Data Type, and two data bytes into the command register format and writes to the XDSI_COMMAND_OFFSET register. Short packets are typically used for commands and status updates. InstancePtr is the XDsi instance to operate on. The instance must have been initialized and activated. ShortPacket is a pointer to the XDsi_ShortPacket structure containing: VcId: Virtual channel identifier (0-3)DataType: DSI data type code for the packetData0: First data byteData1: Second data byte This function does not wait for transmission to complete. The caller must check controller status if synchronization is needed. Only valid for sending up to 2 bytes of data; use XDsi_SendLongPacket() for longer payloads. XDsi_SendLongPacket, XDsi_SendCmdModePkt
References XDsi_Config::BaseAddr, XDsi::Config, XDsi_ShortPacket::Data0, XDsi_ShortPacket::Data1, XDsi_ShortPacket::DataType, XDsi_ShortPacket::VcId, XDSI_COMMAND_OFFSET, XDSI_SPKTR_BYTE1_SHIFT, XDSI_SPKTR_BYTE2_SHIFT, XDSI_SPKTR_VC_SHIFT.
Referenced by XDsi_SendCmdModePkt, XDsi_SendLongPacket.
void XDsi_SendLongPacket(XDsi *InstancePtr, XDsiTx_CmdModePkt *CmdPacket)
Send a DSI long packet to the controller.
Sends a DSI long packet (>2 data bytes, up to 255 bytes) to the DSI controller. The function writes the payload data to the XDSI_DATA_OFFSET register in 32-bit chunks, then sends the packet header as a short packet. Long packets are used for bulk data transfers such as image data or command sequences in command mode. InstancePtr is the XDsi instance to operate on. The instance must have been initialized and activated. CmdPacket is a pointer to the XDsiTx_CmdModePkt structure containing: LongPktData[]: Array of up to 64 32-bit words with payload dataSpktData: Short packet header with VcId, DataType, and packet info Payload size must be specified in CmdPacket->SpktData.Data0 (word count). The function calculates the number of 32-bit writes needed. Data is padded automatically to 32-bit boundary. Maximum payload is 255 bytes (64 32-bit words). XDsi_SendShortPacket, XDsi_SendCmdModePkt
References XDsi_Config::BaseAddr, XDsi::Config, XDsi_ShortPacket::Data0, XDsiTx_CmdModePkt::LongPktData, XDsiTx_CmdModePkt::SpktData, XDSI_DATA_OFFSET, XDsi_SendShortPacket.
Referenced by XDsi_SendCmdModePkt.
int XDsi_SendCmdModePkt(XDsi *InstancePtr, XDsiTx_CmdModePkt *CmdPktData)
Send a DSI command mode packet (short or long).
Sends a DSI packet in command mode. This function supports both short packets (up to 2 bytes) and long packets (up to 255 bytes). It waits for the controller to be ready for the appropriate packet type before transmission. For short packets, waits on XDSI_GetReadyForShortPkt(); for long packets, waits on XDSI_GetReadyForLongPkt(). InstancePtr is the XDsi instance to operate on. The instance must have been initialized, activated, and switched to command mode via XDsi_SetMode(XDSI_COMMAND_MODE). CmdPktData is a pointer to the XDsiTx_CmdModePkt structure specifying: CmdPkt: Packet type (XDSI_CMD_MODE_SHORT_PKT or XDSI_CMD_MODE_LONG_PKT)SpktData: Short packet header informationLongPktData: Payload for long packets XST_SUCCESS if the DSI packet was successfully sent.XST_FAILURE if DSI is not enabled or not in command mode. This function blocks waiting for the controller to be ready. Ensure controller is in command mode before calling. The appropriate packet type must be selected in CmdPktData->CmdPkt. XDsi_SetMode, XDsi_SendShortPacket, XDsi_SendLongPacket
References XDsiTx_CmdModePkt::CmdPkt, XDsiTx_CmdModePkt::SpktData, XDSI_CMD_MODE_SHORT_PKT, XDsi_SendLongPacket, XDsi_SendShortPacket.
int XDsi_SetMode(XDsi *InstancePtr, XDsi_DsiModeType mode)
Switch DSI controller between video and command modes.
Configures the DSI controller to operate in either video mode or command mode. In video mode, the controller processes continuous video frame data streams with synchronization packets. In command mode, the controller accepts individual short and long packets sent by the application. Transitions between modes include appropriate waits for pending operations to complete. InstancePtr is the XDsi instance to operate on. The instance must have been initialized via XDsi_CfgInitialize(). mode is the desired DSI mode: XDSI_VIDEO_MODE: Configure for continuous video stream processingXDSI_COMMAND_MODE: Configure for packet-based command transmission XST_SUCCESS if mode switch was successful.XST_INVALID_PARAM if the requested mode is invalid or an invalid transition is attempted. Certain mode transitions are not allowed by the hardware. For example, cannot switch from video mode to command mode directly while in progress. The function waits for XDsi_GetInProgress() to clear before switching. XDsi_CfgInitialize, XDsi_SendCmdModePkt
References XDSI_COMMAND_MODE, XDSI_VIDEO_MODE.
void XDsi_GetConfigParams(XDsi *InstancePtr, XDsi_ConfigParameters *ConfigInfo)
Read current DSI controller configuration parameters.
Reads the current configuration settings from the DSI controller hardware registers and the driver instance. This includes the protocol control settings (video mode, blank packet type, BLLP mode, EoTP), timing parameters (HSA, VACT, blanking intervals, etc.), and line/BLLP timing. All settings are populated into the provided ConfigInfo structure. InstancePtr is the XDsi instance to operate on. The instance must have been initialized via XDsi_CfgInitialize(). ConfigInfo is a pointer to the XDsi_ConfigParameters structure to be filled with current configuration. The structure will contain: Config: GUI configuration settingsVideoMode: Current video transmission modeBlankPacketType: Blanking packet type for BLLPBLLPMode: Blank packet mode selectionEoTp: End-of-Transmission packet enable statusTiming: All horizontal/vertical timing parametersLineTime, BLLPTime: Total line and BLLP timing values This function performs multiple register reads. The caller must ensure the controller is in a stable state before reading. Timing parameters reflect current register values which may differ from hard-coded configuration if modified at runtime. XDsi_CfgInitialize, XDsi_DefaultConfigure
References XDsi_Config::BaseAddr, XDsi_ConfigParameters::BlankPacketType, XDsi_VideoTiming::BLLPBurst, XDsi_ConfigParameters::BLLPMode, XDsi_ConfigParameters::BLLPTime, XDsi_ConfigParameters::Config, XDsi::Config, XDsi_ConfigParameters::EoTp, XDsi_VideoTiming::HActive, XDsi_VideoTiming::HBackPorch, XDsi_VideoTiming::HFrontPorch, XDsi_VideoTiming::HSyncWidth, XDsi_ConfigParameters::LineTime, XDsi_ConfigParameters::Timing, XDsi_VideoTiming::VActive, XDsi_VideoTiming::VBackPorch, XDsi_VideoTiming::VFrontPorch, XDsi_ConfigParameters::VideoMode, XDsi_VideoTiming::VSyncWidth, XDSI_BLLP_TIME_MASK, XDSI_BLLP_TIME_OFFSET, XDSI_BLLP_TIME_SHIFT, XDSI_LTIME_MASK, XDSI_LTIME_OFFSET, XDSI_LTIME_SHIFT, XDSI_PCR_BLLPMODE_MASK, XDSI_PCR_BLLPMODE_SHIFT, XDSI_PCR_BLLPTYPE_MASK, XDSI_PCR_BLLPTYPE_SHIFT, XDSI_PCR_EOTPENABLE_MASK, XDSI_PCR_EOTPENABLE_SHIFT, XDSI_PCR_OFFSET, XDSI_PCR_VIDEOMODE_MASK, XDSI_PCR_VIDEOMODE_SHIFT, XDSI_TIME1_BLLP_BURST_MASK, XDSI_TIME1_BLLP_BURST_SHIFT, XDSI_TIME1_HSA_MASK, XDSI_TIME1_HSA_SHIFT, XDSI_TIME1_OFFSET, XDSI_TIME2_HACT_MASK, XDSI_TIME2_HACT_SHIFT, XDSI_TIME2_OFFSET, XDSI_TIME2_VACT_MASK, XDSI_TIME2_VACT_SHIFT, XDSI_TIME3_HBP_MASK, XDSI_TIME3_HBP_SHIFT, XDSI_TIME3_HFP_MASK, XDSI_TIME3_HFP_SHIFT, XDSI_TIME3_OFFSET, XDSI_TIME4_OFFSET, XDSI_TIME4_VBP_MASK, XDSI_TIME4_VBP_SHIFT, XDSI_TIME4_VFP_MASK, XDSI_TIME4_VFP_SHIFT, XDSI_TIME4_VSA_MASK, XDSI_TIME4_VSA_SHIFT, XDSI_TIME5_OFFSET, XDSI_TIME5_VFP_MASK, XDSI_TIME5_VFP_SHIFT.
s32 XDsi_SetVideoInterfaceTiming(XDsi *InstancePtr, XDsi_VideoMode VideoMode, XVidC_VideoMode Resolution, u16 BurstPacketSize)
Configure video interface timing based on standard resolution.
Sets the DSI controller video interface timing parameters based on a specified video mode and standard resolution. Looks up timing parameters from the video common library (XVidC_GetVideoModeData), including horizontal and vertical synchronization, active regions, and blanking intervals. The burst packet size is set for burst mode operations. This function is typically called for standard video resolutions (e.g., 1920x1080@60Hz). InstancePtr is the XDsi instance to operate on. The instance must have been initialized via XDsi_CfgInitialize(). VideoMode specifies the DSI video transmission mode: XDSI_VM_NON_BURST_SYNC_PULSES: Non-burst with sync pulsesXDSI_VM_NON_BURST_SYNC_EVENT: Non-burst with sync eventsXDSI_VM_BURST_MODE: Burst mode transmission Resolution specifies the video resolution to configure (e.g., XVIDC_VM_1920x1080_60_P for 1920x1080@60Hz progressive). BurstPacketSize specifies the packet size for burst mode blanking. XST_SUCCESS if video interface timing was successfully configured.XST_FAILURE if the requested resolution is not supported or timing information cannot be retrieved. This function looks up timing data from the video common library. The requested resolution must be supported by the library. For custom resolutions not in the library, use XDsi_SetCustomVideoInterfaceTiming(). XDsi_SetCustomVideoInterfaceTiming, XVidC_GetVideoModeData
References XDsi_Config::BaseAddr, XDsi::Config, XDSI_PCR_OFFSET, XDSI_PCR_VIDEOMODE_MASK, XDSI_PCR_VIDEOMODE_SHIFT, XDSI_TIME1_BLLP_BURST_MASK, XDSI_TIME1_BLLP_BURST_SHIFT, XDSI_TIME1_HSA_MASK, XDSI_TIME1_HSA_SHIFT, XDSI_TIME1_OFFSET, XDSI_TIME2_HACT_MASK, XDSI_TIME2_HACT_SHIFT, XDSI_TIME2_OFFSET, XDSI_TIME2_VACT_MASK, XDSI_TIME2_VACT_SHIFT, XDSI_TIME3_HBP_MASK, XDSI_TIME3_HBP_SHIFT, XDSI_TIME3_HFP_MASK, XDSI_TIME3_HFP_SHIFT, XDSI_TIME3_OFFSET, XDSI_TIME4_OFFSET, XDSI_TIME4_VBP_MASK, XDSI_TIME4_VBP_SHIFT, XDSI_TIME4_VFP_MASK, XDSI_TIME4_VFP_SHIFT, XDSI_TIME4_VSA_MASK, XDSI_TIME4_VSA_SHIFT, XDSI_TIME5_OFFSET, XDSI_TIME5_VFP_MASK, XDSI_TIME5_VFP_SHIFT, XDSI_VM_NUM_SUPPORTED.
s32 XDsi_SetCustomVideoInterfaceTiming(XDsi *InstancePtr, XDsi_VideoMode VideoMode, XDsi_VideoTiming *Timing)
Configure video interface timing with custom parameters.
Sets the DSI controller video interface timing parameters using user-provided custom timing values. Unlike XDsi_SetVideoInterfaceTiming() which uses standard resolutions from the video library, this function allows arbitrary custom timing configurations. Horizontal and vertical synchronization, active region, and blanking parameters are all configurable. Burst packet size is only applied in burst mode. InstancePtr is the XDsi instance to operate on. The instance must have been initialized via XDsi_CfgInitialize(). VideoMode specifies the DSI video transmission mode: XDSI_VM_NON_BURST_SYNC_PULSES: Non-burst with sync pulsesXDSI_VM_NON_BURST_SYNC_EVENT: Non-burst with sync eventsXDSI_VM_BURST_MODE: Burst mode (burst packet size applies) Timing is a pointer to the XDsi_VideoTiming structure containing custom timing parameters: HActive: Active horizontal pixels/bytes per lineHFrontPorch, HSyncWidth, HBackPorch: Horizontal blanking intervalsVActive: Active vertical linesVFrontPorch, VSyncWidth, VBackPorch: Vertical blanking intervalsBLLPBurst: Burst packet size (only used in burst mode) XST_SUCCESS if video interface timing was successfully configured. This function allows maximum flexibility but does not validate timing parameters for spec compliance. Burst packet size is only written in burst mode; non-burst modes override it to 0. Ensure custom timing values comply with DSI and display controller specifications. XDsi_SetVideoInterfaceTiming
References XDsi_Config::BaseAddr, XDsi_VideoTiming::BLLPBurst, XDsi::Config, XDsi_VideoTiming::HActive, XDsi_VideoTiming::HBackPorch, XDsi_VideoTiming::HFrontPorch, XDsi_VideoTiming::HSyncWidth, XDsi_VideoTiming::VActive, XDsi_VideoTiming::VBackPorch, XDsi_VideoTiming::VFrontPorch, XDsi_VideoTiming::VSyncWidth, XDSI_PCR_OFFSET, XDSI_PCR_VIDEOMODE_MASK, XDSI_PCR_VIDEOMODE_SHIFT, XDSI_TIME1_BLLP_BURST_MASK, XDSI_TIME1_BLLP_BURST_SHIFT, XDSI_TIME1_HSA_MASK, XDSI_TIME1_HSA_SHIFT, XDSI_TIME1_OFFSET, XDSI_TIME2_HACT_MASK, XDSI_TIME2_HACT_SHIFT, XDSI_TIME2_OFFSET, XDSI_TIME2_VACT_MASK, XDSI_TIME2_VACT_SHIFT, XDSI_TIME3_HBP_MASK, XDSI_TIME3_HBP_SHIFT, XDSI_TIME3_HFP_MASK, XDSI_TIME3_HFP_SHIFT, XDSI_TIME3_OFFSET, XDSI_TIME4_OFFSET, XDSI_TIME4_VBP_MASK, XDSI_TIME4_VBP_SHIFT, XDSI_TIME4_VFP_MASK, XDSI_TIME4_VFP_SHIFT, XDSI_TIME4_VSA_MASK, XDSI_TIME4_VSA_SHIFT, XDSI_TIME5_OFFSET, XDSI_TIME5_VFP_MASK, XDSI_TIME5_VFP_SHIFT, XDSI_VM_BURST_MODE, XDSI_VM_NUM_SUPPORTED.
static void XDsi_BitSet(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask)
This function is used to set bit in a register.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitMask is the part of the bitname before _MASK None None
static void XDsi_BitReset(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask)
This function is used to reset bit in a register.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitMask is the part of the bitname before _MASK None None
static u32 XDsi_GetBitField(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask, u32 BitShift)
This function is used to get the value of bitfield from register.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitMask is the part of the bitname before _MASK BitShift is the part of the bitname before _SHIFT Bit Field Value in u32 format None
static void XDsi_SetBitField(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask, u32 BitShift, u32 Value)
This function is used to set the value of bitfield from register.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitMask is the part of the bitname before _MASK BitShift is the part of the bitname before _SHIFT Value is to be set. Passed in u32 format. None None
static void XDsi_SetSoftReset(XDsi *InstancePtr)
This function is used to start the soft reset process by setting the soft reset bit in the Core Configuration Register.
InstancePtr is a pointer to the DSI2 instance to be worked on. None None
static u32 XDsi_IsControllerReady(XDsi *InstancePtr)
This function is used to check if a controller is ready or still in reset stage.
InstancePtr is a pointer to the DSI Instance to be worked on. TRUE or FALSE None
static void XDsi_ClearSoftReset(XDsi *InstancePtr)
This function is used to stop the soft reset process by resetting the soft reset bit in the Core Configuration Register.This is done usually after Reset in Progress is 0.
InstancePtr is a pointer to the DSI Instance to be worked on. None None
static void XDsi_Disable(XDsi *InstancePtr)
This function is used to stop the packet processing by resetting Enable core bit in the Core Configuration Register.
InstancePtr is a pointer to the DSI Instance to be worked on. None None
static void XDsi_Enable(XDsi *InstancePtr)
This function is used to start the packet processing by setting Enable core bit in the Core Configuration Register.This is done after the configuration of active lanes, interrupt masks, etc.
InstancePtr is a pointer to the DSI Instance to be worked on. None None
static void XDsi_ResetCmdFifo(XDsi *InstancePtr)
This function is used to reset the command fifo by setting Command FIFO Reset bit in the Core Configuration Register.
InstancePtr is a pointer to the DSI Instance to be worked on. None None
static void XDsi_ClearCmdFifo(XDsi *InstancePtr)
This function is used to reset the command fifo by clearing Command FIFO Reset in the Core Configuration Register.
InstancePtr is a pointer to the DSI Instance to be worked on. None None
static void XDsi_ResetDataFifo(XDsi *InstancePtr)
This function is used to reset the command fifo by setting Data FIFO Reset bit in the Core Configuration Register.
InstancePtr is a pointer to the DSI Instance to be worked on. None None
static void XDsi_ClearDataFifo(XDsi *InstancePtr)
This function is used to reset the command fifo by clearing Data FIFO Reset bit in the Core Configuration Register.
InstancePtr is a pointer to the DSI Instance to be worked on. None None
static u32 XDsi_IsEnabled(XDsi *InstancePtr)
This function is used to check if the Core is enabled by checking the core enable bit.
InstancePtr is a pointer to the DSI Instance to be worked on. SET or RESET in u32 format None
static u32 XDsi_IsModeEnabled(XDsi *InstancePtr)
This function is used to check if the Command/video mode is enabled by checking Command Mode bit in the Core Configuration Register.
InstancePtr is a pointer to the DSI Instance to be worked on. SET (for command mode) or RESET(for video mode) in u32 format None
static void XDsi_CmdModeEnable(XDsi *InstancePtr)
This function is used to set Command Mode bit in the Core Configuration Register.
InstancePtr is a pointer to the DSI Instance to be worked on. None None
static void XDsi_VideoModeEnable(XDsi *InstancePtr)
This function is used to clear Command Mode bit in the Core Configuration Register.
InstancePtr is a pointer to the DSI Instance to be worked on. None None
static void XDsi_SetGlobalInterrupt(XDsi *InstancePtr)
This function is used to enable the global interrupts.
This is used after setting the interrupts mask before enabling the core. InstancePtr is a pointer to the DSI Instance to be worked on. None None
static void XDsi_ResetGlobalInterrupt(XDsi *InstancePtr)
This function is used to disable the global interrupts.
This is done after disabling the core. InstancePtr is a pointer to the DSI Instance to be worked on. None None
static void XDsi_IntrEnable(XDsi *InstancePtr, u32 Mask)
This function is used to set interrupt mask to enable interrupts.
This is done before enabling the core. InstancePtr is a pointer to the DSI Instance to be worked on. Mask Interrupts to be enabled. None None
static u32 XDsi_GetIntrEnableStatus(XDsi *InstancePtr)
This function is used to find out which interrupts are registered for.
InstancePtr is a pointer to the DSI Instance to be worked on. Bit Mask in u32 format None
static void XDsi_IntrDisable(XDsi *InstancePtr, u32 Mask)
This function is used to disable interrupts.
InstancePtr is a pointer to the DSI Instance to be worked on. Mask Interrupts to be disabled. None None
static u32 XDsi_GetIntrStatus(XDsi *InstancePtr)
This function is used to find out which events have triggered the interrupt source, presently DSI supporting Undefined data type and pixel under flow error, the ISR register bits will set when respective interrupt triggers.
InstancePtr is a pointer to the DSI Instance to be worked on. Bit Mask in u32 format None
static void XDsi_IntrClear(XDsi *InstancePtr, u32 Value)
This function is used to acknowledge/clear the events.
Once the interrupt occur the same value need to write in ISR register InstancePtr is a pointer to the DSI Instance to be worked on. Value is Bit Mask for ack of interrupts None None
static u32 XDsi_GetPixelFormat(XDsi *InstancePtr)
This function is used to get pixel format.
InstancePtr is a pointer to the DSI Instance to be worked on. 0x0E – Packed RGB565 0x1E- packed RGB666 0x2E – Loosely packed RGB666 0x3E- Packed RGB888 0x0B- Compressed Pixel Stream None
static u32 XDsi_GetCmdQVacancy(XDsi *InstancePtr)
This function is used to get Command queue Vacancy.
InstancePtr is a pointer to the DSI Instance to be worked on. Number of command queue entries can be safely written to Command queue FIFO, before it goes full. None
static u32 XDsi_GetReadyForShortPkt(XDsi *InstancePtr)
This function is used to get readiness status to short packet.
InstancePtr is a pointer to the DSI Instance to be worked on. SET(ready to send short packet) or RESET(not ready to send short packet) in u32 format None
static u32 XDsi_GetReadyForLongPkt(XDsi *InstancePtr)
This function is used to get readiness status to Long packet.
InstancePtr is a pointer to the DSI Instance to be worked on. SET(ready to send short packet) or RESET(not ready to send short packet) in u32 format None
static u32 XDsi_GetFIFOFull(XDsi *InstancePtr)
This function is used to get Data FIFO full status.
InstancePtr is a pointer to the DSI Instance to be worked on. SET(FIFO is full) or RESET(FIFO is not full) in u32 format None
static u32 XDsi_GetFIFOEmpty(XDsi *InstancePtr)
This function is used to get Data FIFO Empty status.
InstancePtr is a pointer to the DSI Instance to be worked on. SET(FIFO is Empty) or RESET(FIFO is not Empty) in u32 format None
static u32 XDsi_GetWaitForData(XDsi *InstancePtr)
This function is used to get wait status for data to process long command.
InstancePtr is a pointer to the DSI Instance to be worked on. SET(long command is in progress) or RESET(Long command is processed) in u32 format None
static u32 XDsi_GetInProgress(XDsi *InstancePtr)
This function is used to get in progress status for Short/Long Commands.
InstancePtr is a pointer to the DSI Instance to be worked on. SET(Long command) or RESET(short command) in u32 format None
static u32 XDsi_GetUnderProgress(XDsi *InstancePtr)
This function is used to get under process status for Short/Long Commands.
InstancePtr is a pointer to the DSI Instance to be worked on. SET(Long command) or RESET(short command) in u32 format None
XDsi_Config * XDsi_LookupConfig(UINTPTR BaseAddress)
Look up the hardware configuration for a device instance.
DeviceId is the unique device ID of the device to lookup for The reference to the configuration record in the configuration table (in xdsi_g.c) corresponding to the Device ID or if not found, a NULL pointer is returned. None
Referenced by DsiSelfTestExample.
u32 XDsi_SelfTest(XDsi *InstancePtr)
Runs a self-test on the driver/device.
This test checks if the LaneCount present in register matches the one from the generated file. InstancePtr is a pointer to the XDsi instance. XST_SUCCESS if self-test was successfulXST_FAILURE if the read value was not equal to GUI parameter None
References XDsi_Config::BaseAddr, XDsi::Config, XDsi_Config::DsiLanes, XDsi::IsReady, XDSI_PCR_ACTLANES_MASK, XDSI_PCR_ACTLANES_SHIFT, XDSI_PCR_OFFSET.
Referenced by DsiSelfTestExample.
s32 XDsi_SetCallback(XDsi *InstancePtr, u32 HandleType, void *CallbackFunc, void *CallbackRef)
This routine installs an asynchronous callback function for the given HandlerType:
HandlerType Invoked by this driver when: ----------------------- -------------------------------------------------- XDSI_HANDLER_UNSUPPORT_DATATYPE Un support data type detected XDSI_HANDLER_PIXELDATA_UNDERRUN Byte stream FIFO starves for Pixel during HACT transmission XDSI_HANDLER_OTHERERROR Any other type of interrupt has occurred like Stream Line Buffer Full, Incorrect Lanes, etc XDSI_HANDLER_CMDQ_FIFOFULL Command queue FIFO full InstancePtr is the XDsi instance to operate on HandleType is the type of call back to be registered. CallbackFunc is the pointer to a call back function which is called when a particular event occurs. CallbackRef is a void pointer to data to be referenced to by the CallbackFunc XST_SUCCESS when handler is installed. XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XDsi::CmdQFIFOFullCallback, XDsi::CmdQFIFOFullRef, XDsi::ErrorCallback, XDsi::ErrRef, XDsi::IsReady, XDsi::PixelDataUnderrunCallback, XDsi::PixelDataUnderrundRef, XDsi::UnsupportDataTypeRef, XDsi::UnSupportedDataTypeCallback, XDSI_HANDLER_CMDQ_FIFOFULL, XDSI_HANDLER_OTHERERROR, XDSI_HANDLER_PIXELDATA_UNDERRUN, XDSI_HANDLER_UNSUPPORT_DATATYPE.
static u32 XDsi_ReadReg(UINTPTR BaseAddress, u32 RegOffset)
Inline function to read DSI controller register.
BaseAddress is the base address of DSI RegOffset is the register offset. Value of the register. None
static void XDsi_WriteReg(UINTPTR BaseAddress, u32 RegOffset, u32 Data)
Inline Function to write to DSI controller register.
BaseAddress is the base address of DSI RegOffset is the register offset. Data is the value to be written to the register. None. None
void XDsi_InterruptEnable(XDsi *InstancePtr, u32 Mask)
This function will enable the interrupts present in the interrupt mask passed onto the function.
InstancePtr is the XDsi instance to operate on Mask is the interrupt mask which need to be enabled in core None
References XDSI_IER_ALLINTR_MASK.
void XDsi_InterruptDisable(XDsi *InstancePtr, u32 Mask)
This function will disable the interrupts present in the interrupt mask passed onto the function.
InstancePtr is the XDsi instance to operate on Mask is the interrupt mask which need to be enabled in core None
References XDSI_IER_ALLINTR_MASK.
u32 XDsi_InterruptGetEnabled(XDsi *InstancePtr)
This function will get the interrupt mask set (enabled) in the DSI core.
InstancePtr is the XDsi instance to operate on Interrupt Mask with bits set for corresponding interrupt in Interrupt enable register None
u32 XDsi_InterruptGetStatus(XDsi *InstancePtr)
This function will get the list of interrupts Invoked in the Interrupt Status Register of the DSI core.
InstancePtr is the XDsi instance to operate on Interrupt Mask with bits set for corresponding interrupt in Interrupt Status register None
Referenced by XDsi_IntrHandler.
void XDsi_InterruptClear(XDsi *InstancePtr, u32 Mask)
This function will clear the interrupts set in the Interrupt Status Register of the DSI core.
InstancePtr is the XDsi instance to operate on Mask is Interrupt Mask with bits set for corresponding interrupt to be cleared in the Interrupt Status register None
References XDSI_IER_ALLINTR_MASK.
Referenced by XDsi_IntrHandler.
void XDsi_IntrHandler(void *InstancePtr)
This function is the interrupt handler for the DSI core.
This handler reads the Invoked interrupt from the Interrupt Status register determines the source of the interrupts and calls the respective callbacks for the interrupts that are enabled in Interrupt Enable register and finally clears the interrupts.The application is responsible for connecting this function to the interrupt system. Application beyond this core is also responsible for providing callbacks to handle interrupts and installing the callbacks using XDsi_SetCallback() during initialization phase. InstancePtr is a pointer to the XDsi core instance. Interrupt should be enabled to execute interrupt handler.
References XDsi::CmdQFIFOFullCallback, XDsi::CmdQFIFOFullRef, XDsi::IsReady, XDsi::PixelDataUnderrunCallback, XDsi::PixelDataUnderrundRef, XDsi::UnsupportDataTypeRef, XDsi::UnSupportedDataTypeCallback, XDSI_IER_CMDQ_FIFO_FULL_MASK, XDSI_IER_DATA_ID_ERR_MASK, XDSI_IER_PXL_UNDR_RUN_MASK, XDsi_InterruptClear, XDsi_InterruptGetStatus.
XDSI_HANDLER_UNSUPPORT_DATATYPE
Interrupt handler type for unsupported data type.
Referenced by XDsi_SetCallback.
XDSI_HANDLER_PIXELDATA_UNDERRUN
Interrupt handler type for pixel data underrun.
Referenced by XDsi_SetCallback.
XDSI_HANDLER_OTHERERROR
Interrupt handler type for other errors.
Referenced by XDsi_SetCallback.
XDSI_HANDLER_CMDQ_FIFOFULL
Interrupt handler type for command queue FIFO full.
Referenced by XDsi_SetCallback.
NUM_PACKETS
Number of packets for long packet data in command mode.