xdsi.c
static void StubErrCallback(void *CallbackRef, u32 ErrorMask)
This routine is a stub for the asynchronous error interrupt callback.
The stub is here in case the upper layer forgot to set the handler. On initialization, Error interrupt handler is set to this callback. It is considered an error for this handler to be invoked. CallbackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. ErrorMask is a bit mask indicating the cause of the error. Its value equals 'OR'ing one or more XDSI_ISR_*_MASK values defined in xdsi_hw.h. None.
u32 XDsi_CfgInitialize(XDsi *InstancePtr, XDsi_Config *CfgPtr, UINTPTR EffectiveAddr)
Initialize the XDsi instance provided by the caller based on the given Config structure.
Initializes the DSI controller instance with hardware configuration information and sets up default callback handlers. InstancePtr is the XDsi instance to operate on. CfgPtr is the device configuration structure containing information about a specific DSI controller (base address, lanes, FIFO size, etc.) EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if initialization was successful.XST_FAILURE if initialization failed. All callback handlers are initialized to stub functions that will assert on invocation. Application must set actual callback handlers using XDsi_SetCallback() if interrupt handling is required. XDsi_SetCallback
References XDsi_Config::BaseAddr, XDsi::CmdQFIFOFullCallback, XDsi::Config, XDsi::ErrorCallback, XDsi::IsReady, XDsi::PixelDataUnderrunCallback, XDsi::UnSupportedDataTypeCallback.
Referenced by DsiSelfTestExample.
void XDsi_Reset(XDsi *InstancePtr)
Perform a soft reset of the DSI controller.
Resets the DSI controller including interrupt status registers, command queue FIFO, and state machine. The controller gracefully waits for current operations to complete before resetting. After reset is released, controller starts from VSS (Vertical Sync Start) packet (new video frame). InstancePtr is the XDsi instance to operate on. None.
u32 XDsi_DefaultConfigure(XDsi *InstancePtr)
Configure default DSI protocol settings.
Configures the DSI controller protocol register with video mode, blank packet mode, blank packet type, and End-of-Transmission (EoTP) packet settings based on the instance parameters. This function sets up the Protocol Control Register (PCR) with the instance VideoMode, BlankPacketType, BLLPMode, and EoTp configuration values. InstancePtr is the XDsi instance to operate on. The instance must have been initialized via XDsi_CfgInitialize(). XST_SUCCESS if configuration was successful. This function assumes the instance is already initialized. The instance member variables (VideoMode, BlankPacketType, BLLPMode, EoTp) must be set before calling this function or it will use default/uninitialized values. XDsi_CfgInitialize, XDsi_Activate
References XDsi::BlankPacketType, XDsi::BLLPMode, XDsi::EoTp, XDsi::IsReady, XDsi::VideoMode, XDSI_PCR_BLLPMODE_MASK, XDSI_PCR_BLLPMODE_SHIFT, XDSI_PCR_BLLPTYPE_MASK, XDSI_PCR_BLLPTYPE_SHIFT, XDSI_PCR_EOTPENABLE_MASK, XDSI_PCR_EOTPENABLE_SHIFT, XDSI_PCR_OFFSET, XDSI_PCR_VIDEOMODE_MASK, XDSI_PCR_VIDEOMODE_SHIFT.
u32 XDsi_Activate(XDsi *InstancePtr, XDsi_Selection Flag)
Enable or disable the DSI controller core.
Activates or deactivates the DSI controller IP core. When enabling (Flag=XDSI_ENABLE), the global interrupt output is set and the core is enabled for packet processing. When disabling (Flag=XDSI_DISABLE), the global interrupt is reset and the core is disabled. InstancePtr is the XDsi instance to operate on. The instance must have been initialized via XDsi_CfgInitialize(). Flag indicates the desired action: XDSI_ENABLE: Enable global interrupt and activate DSI coreXDSI_DISABLE: Reset global interrupt and disable DSI core XST_SUCCESS if enable/disable operation was successful. XST_INVALID_PARAM if an invalid Flag value is provided. Must be called after XDsi_CfgInitialize() and XDsi_DefaultConfigure(). The core must be configured with video mode or command mode settings before activation. XDsi_CfgInitialize, XDsi_DefaultConfigure, XDsi_SetMode
References XDsi::IsReady, XDSI_DISABLE.
void XDsi_SendShortPacket(XDsi *InstancePtr, XDsi_ShortPacket *ShortPacket)
Send a DSI short packet to the controller.
Sends a DSI short packet (up to 2 data bytes) to the DSI controller via the Generic Short Packet Register. The function packs the Virtual Channel ID, Data Type, and two data bytes into the command register format and writes to the XDSI_COMMAND_OFFSET register. Short packets are typically used for commands and status updates. InstancePtr is the XDsi instance to operate on. The instance must have been initialized and activated. ShortPacket is a pointer to the XDsi_ShortPacket structure containing: VcId: Virtual channel identifier (0-3)DataType: DSI data type code for the packetData0: First data byteData1: Second data byte This function does not wait for transmission to complete. The caller must check controller status if synchronization is needed. Only valid for sending up to 2 bytes of data; use XDsi_SendLongPacket() for longer payloads. XDsi_SendLongPacket, XDsi_SendCmdModePkt
References XDsi_Config::BaseAddr, XDsi::Config, XDsi_ShortPacket::Data0, XDsi_ShortPacket::Data1, XDsi_ShortPacket::DataType, XDsi_ShortPacket::VcId, XDSI_COMMAND_OFFSET, XDSI_SPKTR_BYTE1_SHIFT, XDSI_SPKTR_BYTE2_SHIFT, XDSI_SPKTR_VC_SHIFT.
Referenced by XDsi_SendCmdModePkt, XDsi_SendLongPacket.
void XDsi_SendLongPacket(XDsi *InstancePtr, XDsiTx_CmdModePkt *CmdPacket)
Send a DSI long packet to the controller.
Sends a DSI long packet (>2 data bytes, up to 255 bytes) to the DSI controller. The function writes the payload data to the XDSI_DATA_OFFSET register in 32-bit chunks, then sends the packet header as a short packet. Long packets are used for bulk data transfers such as image data or command sequences in command mode. InstancePtr is the XDsi instance to operate on. The instance must have been initialized and activated. CmdPacket is a pointer to the XDsiTx_CmdModePkt structure containing: LongPktData[]: Array of up to 64 32-bit words with payload dataSpktData: Short packet header with VcId, DataType, and packet info Payload size must be specified in CmdPacket->SpktData.Data0 (word count). The function calculates the number of 32-bit writes needed. Data is padded automatically to 32-bit boundary. Maximum payload is 255 bytes (64 32-bit words). XDsi_SendShortPacket, XDsi_SendCmdModePkt
References XDsi_Config::BaseAddr, XDsi::Config, XDsi_ShortPacket::Data0, XDsiTx_CmdModePkt::LongPktData, XDsiTx_CmdModePkt::SpktData, XDSI_DATA_OFFSET, XDsi_SendShortPacket.
Referenced by XDsi_SendCmdModePkt.
int XDsi_SendCmdModePkt(XDsi *InstancePtr, XDsiTx_CmdModePkt *CmdPktData)
Send a DSI command mode packet (short or long).
Sends a DSI packet in command mode. This function supports both short packets (up to 2 bytes) and long packets (up to 255 bytes). It waits for the controller to be ready for the appropriate packet type before transmission. For short packets, waits on XDSI_GetReadyForShortPkt(); for long packets, waits on XDSI_GetReadyForLongPkt(). InstancePtr is the XDsi instance to operate on. The instance must have been initialized, activated, and switched to command mode via XDsi_SetMode(XDSI_COMMAND_MODE). CmdPktData is a pointer to the XDsiTx_CmdModePkt structure specifying: CmdPkt: Packet type (XDSI_CMD_MODE_SHORT_PKT or XDSI_CMD_MODE_LONG_PKT)SpktData: Short packet header informationLongPktData: Payload for long packets XST_SUCCESS if the DSI packet was successfully sent.XST_FAILURE if DSI is not enabled or not in command mode. This function blocks waiting for the controller to be ready. Ensure controller is in command mode before calling. The appropriate packet type must be selected in CmdPktData->CmdPkt. XDsi_SetMode, XDsi_SendShortPacket, XDsi_SendLongPacket
References XDsiTx_CmdModePkt::CmdPkt, XDsiTx_CmdModePkt::SpktData, XDSI_CMD_MODE_SHORT_PKT, XDsi_SendLongPacket, XDsi_SendShortPacket.
int XDsi_SetMode(XDsi *InstancePtr, XDsi_DsiModeType mode)
Switch DSI controller between video and command modes.
Configures the DSI controller to operate in either video mode or command mode. In video mode, the controller processes continuous video frame data streams with synchronization packets. In command mode, the controller accepts individual short and long packets sent by the application. Transitions between modes include appropriate waits for pending operations to complete. InstancePtr is the XDsi instance to operate on. The instance must have been initialized via XDsi_CfgInitialize(). mode is the desired DSI mode: XDSI_VIDEO_MODE: Configure for continuous video stream processingXDSI_COMMAND_MODE: Configure for packet-based command transmission XST_SUCCESS if mode switch was successful.XST_INVALID_PARAM if the requested mode is invalid or an invalid transition is attempted. Certain mode transitions are not allowed by the hardware. For example, cannot switch from video mode to command mode directly while in progress. The function waits for XDsi_GetInProgress() to clear before switching. XDsi_CfgInitialize, XDsi_SendCmdModePkt
References XDSI_COMMAND_MODE, XDSI_VIDEO_MODE.
void XDsi_GetConfigParams(XDsi *InstancePtr, XDsi_ConfigParameters *ConfigInfo)
Read current DSI controller configuration parameters.
Reads the current configuration settings from the DSI controller hardware registers and the driver instance. This includes the protocol control settings (video mode, blank packet type, BLLP mode, EoTP), timing parameters (HSA, VACT, blanking intervals, etc.), and line/BLLP timing. All settings are populated into the provided ConfigInfo structure. InstancePtr is the XDsi instance to operate on. The instance must have been initialized via XDsi_CfgInitialize(). ConfigInfo is a pointer to the XDsi_ConfigParameters structure to be filled with current configuration. The structure will contain: Config: GUI configuration settingsVideoMode: Current video transmission modeBlankPacketType: Blanking packet type for BLLPBLLPMode: Blank packet mode selectionEoTp: End-of-Transmission packet enable statusTiming: All horizontal/vertical timing parametersLineTime, BLLPTime: Total line and BLLP timing values This function performs multiple register reads. The caller must ensure the controller is in a stable state before reading. Timing parameters reflect current register values which may differ from hard-coded configuration if modified at runtime. XDsi_CfgInitialize, XDsi_DefaultConfigure
References XDsi_Config::BaseAddr, XDsi_ConfigParameters::BlankPacketType, XDsi_VideoTiming::BLLPBurst, XDsi_ConfigParameters::BLLPMode, XDsi_ConfigParameters::BLLPTime, XDsi_ConfigParameters::Config, XDsi::Config, XDsi_ConfigParameters::EoTp, XDsi_VideoTiming::HActive, XDsi_VideoTiming::HBackPorch, XDsi_VideoTiming::HFrontPorch, XDsi_VideoTiming::HSyncWidth, XDsi_ConfigParameters::LineTime, XDsi_ConfigParameters::Timing, XDsi_VideoTiming::VActive, XDsi_VideoTiming::VBackPorch, XDsi_VideoTiming::VFrontPorch, XDsi_ConfigParameters::VideoMode, XDsi_VideoTiming::VSyncWidth, XDSI_BLLP_TIME_MASK, XDSI_BLLP_TIME_OFFSET, XDSI_BLLP_TIME_SHIFT, XDSI_LTIME_MASK, XDSI_LTIME_OFFSET, XDSI_LTIME_SHIFT, XDSI_PCR_BLLPMODE_MASK, XDSI_PCR_BLLPMODE_SHIFT, XDSI_PCR_BLLPTYPE_MASK, XDSI_PCR_BLLPTYPE_SHIFT, XDSI_PCR_EOTPENABLE_MASK, XDSI_PCR_EOTPENABLE_SHIFT, XDSI_PCR_OFFSET, XDSI_PCR_VIDEOMODE_MASK, XDSI_PCR_VIDEOMODE_SHIFT, XDSI_TIME1_BLLP_BURST_MASK, XDSI_TIME1_BLLP_BURST_SHIFT, XDSI_TIME1_HSA_MASK, XDSI_TIME1_HSA_SHIFT, XDSI_TIME1_OFFSET, XDSI_TIME2_HACT_MASK, XDSI_TIME2_HACT_SHIFT, XDSI_TIME2_OFFSET, XDSI_TIME2_VACT_MASK, XDSI_TIME2_VACT_SHIFT, XDSI_TIME3_HBP_MASK, XDSI_TIME3_HBP_SHIFT, XDSI_TIME3_HFP_MASK, XDSI_TIME3_HFP_SHIFT, XDSI_TIME3_OFFSET, XDSI_TIME4_OFFSET, XDSI_TIME4_VBP_MASK, XDSI_TIME4_VBP_SHIFT, XDSI_TIME4_VFP_MASK, XDSI_TIME4_VFP_SHIFT, XDSI_TIME4_VSA_MASK, XDSI_TIME4_VSA_SHIFT, XDSI_TIME5_OFFSET, XDSI_TIME5_VFP_MASK, XDSI_TIME5_VFP_SHIFT.
s32 XDsi_SetVideoInterfaceTiming(XDsi *InstancePtr, XDsi_VideoMode VideoMode, XVidC_VideoMode Resolution, u16 BurstPacketSize)
Configure video interface timing based on standard resolution.
Sets the DSI controller video interface timing parameters based on a specified video mode and standard resolution. Looks up timing parameters from the video common library (XVidC_GetVideoModeData), including horizontal and vertical synchronization, active regions, and blanking intervals. The burst packet size is set for burst mode operations. This function is typically called for standard video resolutions (e.g., 1920x1080@60Hz). InstancePtr is the XDsi instance to operate on. The instance must have been initialized via XDsi_CfgInitialize(). VideoMode specifies the DSI video transmission mode: XDSI_VM_NON_BURST_SYNC_PULSES: Non-burst with sync pulsesXDSI_VM_NON_BURST_SYNC_EVENT: Non-burst with sync eventsXDSI_VM_BURST_MODE: Burst mode transmission Resolution specifies the video resolution to configure (e.g., XVIDC_VM_1920x1080_60_P for 1920x1080@60Hz progressive). BurstPacketSize specifies the packet size for burst mode blanking. XST_SUCCESS if video interface timing was successfully configured.XST_FAILURE if the requested resolution is not supported or timing information cannot be retrieved. This function looks up timing data from the video common library. The requested resolution must be supported by the library. For custom resolutions not in the library, use XDsi_SetCustomVideoInterfaceTiming(). XDsi_SetCustomVideoInterfaceTiming, XVidC_GetVideoModeData
References XDsi_Config::BaseAddr, XDsi::Config, XDSI_PCR_OFFSET, XDSI_PCR_VIDEOMODE_MASK, XDSI_PCR_VIDEOMODE_SHIFT, XDSI_TIME1_BLLP_BURST_MASK, XDSI_TIME1_BLLP_BURST_SHIFT, XDSI_TIME1_HSA_MASK, XDSI_TIME1_HSA_SHIFT, XDSI_TIME1_OFFSET, XDSI_TIME2_HACT_MASK, XDSI_TIME2_HACT_SHIFT, XDSI_TIME2_OFFSET, XDSI_TIME2_VACT_MASK, XDSI_TIME2_VACT_SHIFT, XDSI_TIME3_HBP_MASK, XDSI_TIME3_HBP_SHIFT, XDSI_TIME3_HFP_MASK, XDSI_TIME3_HFP_SHIFT, XDSI_TIME3_OFFSET, XDSI_TIME4_OFFSET, XDSI_TIME4_VBP_MASK, XDSI_TIME4_VBP_SHIFT, XDSI_TIME4_VFP_MASK, XDSI_TIME4_VFP_SHIFT, XDSI_TIME4_VSA_MASK, XDSI_TIME4_VSA_SHIFT, XDSI_TIME5_OFFSET, XDSI_TIME5_VFP_MASK, XDSI_TIME5_VFP_SHIFT, XDSI_VM_NUM_SUPPORTED.
s32 XDsi_SetCustomVideoInterfaceTiming(XDsi *InstancePtr, XDsi_VideoMode VideoMode, XDsi_VideoTiming *Timing)
Configure video interface timing with custom parameters.
Sets the DSI controller video interface timing parameters using user-provided custom timing values. Unlike XDsi_SetVideoInterfaceTiming() which uses standard resolutions from the video library, this function allows arbitrary custom timing configurations. Horizontal and vertical synchronization, active region, and blanking parameters are all configurable. Burst packet size is only applied in burst mode. InstancePtr is the XDsi instance to operate on. The instance must have been initialized via XDsi_CfgInitialize(). VideoMode specifies the DSI video transmission mode: XDSI_VM_NON_BURST_SYNC_PULSES: Non-burst with sync pulsesXDSI_VM_NON_BURST_SYNC_EVENT: Non-burst with sync eventsXDSI_VM_BURST_MODE: Burst mode (burst packet size applies) Timing is a pointer to the XDsi_VideoTiming structure containing custom timing parameters: HActive: Active horizontal pixels/bytes per lineHFrontPorch, HSyncWidth, HBackPorch: Horizontal blanking intervalsVActive: Active vertical linesVFrontPorch, VSyncWidth, VBackPorch: Vertical blanking intervalsBLLPBurst: Burst packet size (only used in burst mode) XST_SUCCESS if video interface timing was successfully configured. This function allows maximum flexibility but does not validate timing parameters for spec compliance. Burst packet size is only written in burst mode; non-burst modes override it to 0. Ensure custom timing values comply with DSI and display controller specifications. XDsi_SetVideoInterfaceTiming
References XDsi_Config::BaseAddr, XDsi_VideoTiming::BLLPBurst, XDsi::Config, XDsi_VideoTiming::HActive, XDsi_VideoTiming::HBackPorch, XDsi_VideoTiming::HFrontPorch, XDsi_VideoTiming::HSyncWidth, XDsi_VideoTiming::VActive, XDsi_VideoTiming::VBackPorch, XDsi_VideoTiming::VFrontPorch, XDsi_VideoTiming::VSyncWidth, XDSI_PCR_OFFSET, XDSI_PCR_VIDEOMODE_MASK, XDSI_PCR_VIDEOMODE_SHIFT, XDSI_TIME1_BLLP_BURST_MASK, XDSI_TIME1_BLLP_BURST_SHIFT, XDSI_TIME1_HSA_MASK, XDSI_TIME1_HSA_SHIFT, XDSI_TIME1_OFFSET, XDSI_TIME2_HACT_MASK, XDSI_TIME2_HACT_SHIFT, XDSI_TIME2_OFFSET, XDSI_TIME2_VACT_MASK, XDSI_TIME2_VACT_SHIFT, XDSI_TIME3_HBP_MASK, XDSI_TIME3_HBP_SHIFT, XDSI_TIME3_HFP_MASK, XDSI_TIME3_HFP_SHIFT, XDSI_TIME3_OFFSET, XDSI_TIME4_OFFSET, XDSI_TIME4_VBP_MASK, XDSI_TIME4_VBP_SHIFT, XDSI_TIME4_VFP_MASK, XDSI_TIME4_VFP_SHIFT, XDSI_TIME4_VSA_MASK, XDSI_TIME4_VSA_SHIFT, XDSI_TIME5_OFFSET, XDSI_TIME5_VFP_MASK, XDSI_TIME5_VFP_SHIFT, XDSI_VM_BURST_MODE, XDSI_VM_NUM_SUPPORTED.