xdsi.h
XDSI_HANDLER_UNSUPPORT_DATATYPE
Interrupt handler type for unsupported data type.
Referenced by XDsi_SetCallback.
XDSI_HANDLER_PIXELDATA_UNDERRUN
Interrupt handler type for pixel data underrun.
Referenced by XDsi_SetCallback.
XDSI_HANDLER_OTHERERROR
Interrupt handler type for other errors.
Referenced by XDsi_SetCallback.
XDSI_HANDLER_CMDQ_FIFOFULL
Interrupt handler type for command queue FIFO full.
Referenced by XDsi_SetCallback.
NUM_PACKETS
Number of packets for long packet data in command mode.
XDsi_Selection
DSI Tx controller Disable.
XDsi_DsiModeType
Video mode.
XDsi_CmdModePktType
Command mode short packet.
XDsi_VideoMode
Non-burst mode with sync pulses.
typedef void(* XDsi_Callback)(void *CallBackRef, u32 Mask))(void *CallBackRef, u32 Mask)
Callback type for all interrupts defined.
CallBackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. Mask is a bit mask indicating the cause of the event. For current core version, this parameter is "OR" of 0 or more XDSI_ISR_*_MASK constants defined in xdsi_hw.h. None. None.
static void XDsi_BitSet(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask)
This function is used to set bit in a register.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitMask is the part of the bitname before _MASK None None
static void XDsi_BitReset(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask)
This function is used to reset bit in a register.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitMask is the part of the bitname before _MASK None None
static u32 XDsi_GetBitField(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask, u32 BitShift)
This function is used to get the value of bitfield from register.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitMask is the part of the bitname before _MASK BitShift is the part of the bitname before _SHIFT Bit Field Value in u32 format None
static void XDsi_SetBitField(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask, u32 BitShift, u32 Value)
This function is used to set the value of bitfield from register.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitMask is the part of the bitname before _MASK BitShift is the part of the bitname before _SHIFT Value is to be set. Passed in u32 format. None None
static void XDsi_SetSoftReset(XDsi *InstancePtr)
This function is used to start the soft reset process by setting the soft reset bit in the Core Configuration Register.
InstancePtr is a pointer to the DSI2 instance to be worked on. None None
static u32 XDsi_IsControllerReady(XDsi *InstancePtr)
This function is used to check if a controller is ready or still in reset stage.
InstancePtr is a pointer to the DSI Instance to be worked on. TRUE or FALSE None
static void XDsi_ClearSoftReset(XDsi *InstancePtr)
This function is used to stop the soft reset process by resetting the soft reset bit in the Core Configuration Register.This is done usually after Reset in Progress is 0.
InstancePtr is a pointer to the DSI Instance to be worked on. None None
static void XDsi_Disable(XDsi *InstancePtr)
This function is used to stop the packet processing by resetting Enable core bit in the Core Configuration Register.
InstancePtr is a pointer to the DSI Instance to be worked on. None None
static void XDsi_Enable(XDsi *InstancePtr)
This function is used to start the packet processing by setting Enable core bit in the Core Configuration Register.This is done after the configuration of active lanes, interrupt masks, etc.
InstancePtr is a pointer to the DSI Instance to be worked on. None None
static void XDsi_ResetCmdFifo(XDsi *InstancePtr)
This function is used to reset the command fifo by setting Command FIFO Reset bit in the Core Configuration Register.
InstancePtr is a pointer to the DSI Instance to be worked on. None None
static void XDsi_ClearCmdFifo(XDsi *InstancePtr)
This function is used to reset the command fifo by clearing Command FIFO Reset in the Core Configuration Register.
InstancePtr is a pointer to the DSI Instance to be worked on. None None
static void XDsi_ResetDataFifo(XDsi *InstancePtr)
This function is used to reset the command fifo by setting Data FIFO Reset bit in the Core Configuration Register.
InstancePtr is a pointer to the DSI Instance to be worked on. None None
static void XDsi_ClearDataFifo(XDsi *InstancePtr)
This function is used to reset the command fifo by clearing Data FIFO Reset bit in the Core Configuration Register.
InstancePtr is a pointer to the DSI Instance to be worked on. None None
static u32 XDsi_IsEnabled(XDsi *InstancePtr)
This function is used to check if the Core is enabled by checking the core enable bit.
InstancePtr is a pointer to the DSI Instance to be worked on. SET or RESET in u32 format None
static u32 XDsi_IsModeEnabled(XDsi *InstancePtr)
This function is used to check if the Command/video mode is enabled by checking Command Mode bit in the Core Configuration Register.
InstancePtr is a pointer to the DSI Instance to be worked on. SET (for command mode) or RESET(for video mode) in u32 format None
static void XDsi_CmdModeEnable(XDsi *InstancePtr)
This function is used to set Command Mode bit in the Core Configuration Register.
InstancePtr is a pointer to the DSI Instance to be worked on. None None
static void XDsi_VideoModeEnable(XDsi *InstancePtr)
This function is used to clear Command Mode bit in the Core Configuration Register.
InstancePtr is a pointer to the DSI Instance to be worked on. None None
static void XDsi_SetGlobalInterrupt(XDsi *InstancePtr)
This function is used to enable the global interrupts.
This is used after setting the interrupts mask before enabling the core. InstancePtr is a pointer to the DSI Instance to be worked on. None None
static void XDsi_ResetGlobalInterrupt(XDsi *InstancePtr)
This function is used to disable the global interrupts.
This is done after disabling the core. InstancePtr is a pointer to the DSI Instance to be worked on. None None
static void XDsi_IntrEnable(XDsi *InstancePtr, u32 Mask)
This function is used to set interrupt mask to enable interrupts.
This is done before enabling the core. InstancePtr is a pointer to the DSI Instance to be worked on. Mask Interrupts to be enabled. None None
static u32 XDsi_GetIntrEnableStatus(XDsi *InstancePtr)
This function is used to find out which interrupts are registered for.
InstancePtr is a pointer to the DSI Instance to be worked on. Bit Mask in u32 format None
static void XDsi_IntrDisable(XDsi *InstancePtr, u32 Mask)
This function is used to disable interrupts.
InstancePtr is a pointer to the DSI Instance to be worked on. Mask Interrupts to be disabled. None None
static u32 XDsi_GetIntrStatus(XDsi *InstancePtr)
This function is used to find out which events have triggered the interrupt source, presently DSI supporting Undefined data type and pixel under flow error, the ISR register bits will set when respective interrupt triggers.
InstancePtr is a pointer to the DSI Instance to be worked on. Bit Mask in u32 format None
static void XDsi_IntrClear(XDsi *InstancePtr, u32 Value)
This function is used to acknowledge/clear the events.
Once the interrupt occur the same value need to write in ISR register InstancePtr is a pointer to the DSI Instance to be worked on. Value is Bit Mask for ack of interrupts None None
static u32 XDsi_GetPixelFormat(XDsi *InstancePtr)
This function is used to get pixel format.
InstancePtr is a pointer to the DSI Instance to be worked on. 0x0E – Packed RGB565 0x1E- packed RGB666 0x2E – Loosely packed RGB666 0x3E- Packed RGB888 0x0B- Compressed Pixel Stream None
static u32 XDsi_GetCmdQVacancy(XDsi *InstancePtr)
This function is used to get Command queue Vacancy.
InstancePtr is a pointer to the DSI Instance to be worked on. Number of command queue entries can be safely written to Command queue FIFO, before it goes full. None
static u32 XDsi_GetReadyForShortPkt(XDsi *InstancePtr)
This function is used to get readiness status to short packet.
InstancePtr is a pointer to the DSI Instance to be worked on. SET(ready to send short packet) or RESET(not ready to send short packet) in u32 format None
static u32 XDsi_GetReadyForLongPkt(XDsi *InstancePtr)
This function is used to get readiness status to Long packet.
InstancePtr is a pointer to the DSI Instance to be worked on. SET(ready to send short packet) or RESET(not ready to send short packet) in u32 format None
static u32 XDsi_GetFIFOFull(XDsi *InstancePtr)
This function is used to get Data FIFO full status.
InstancePtr is a pointer to the DSI Instance to be worked on. SET(FIFO is full) or RESET(FIFO is not full) in u32 format None
static u32 XDsi_GetFIFOEmpty(XDsi *InstancePtr)
This function is used to get Data FIFO Empty status.
InstancePtr is a pointer to the DSI Instance to be worked on. SET(FIFO is Empty) or RESET(FIFO is not Empty) in u32 format None
static u32 XDsi_GetWaitForData(XDsi *InstancePtr)
This function is used to get wait status for data to process long command.
InstancePtr is a pointer to the DSI Instance to be worked on. SET(long command is in progress) or RESET(Long command is processed) in u32 format None
static u32 XDsi_GetInProgress(XDsi *InstancePtr)
This function is used to get in progress status for Short/Long Commands.
InstancePtr is a pointer to the DSI Instance to be worked on. SET(Long command) or RESET(short command) in u32 format None
static u32 XDsi_GetUnderProgress(XDsi *InstancePtr)
This function is used to get under process status for Short/Long Commands.
InstancePtr is a pointer to the DSI Instance to be worked on. SET(Long command) or RESET(short command) in u32 format None
XDsi_Config * XDsi_LookupConfig(UINTPTR BaseAddress)
Look up the hardware configuration for a device instance.
DeviceId is the unique device ID of the device to lookup for The reference to the configuration record in the configuration table (in xdsi_g.c) corresponding to the Device ID or if not found, a NULL pointer is returned. None
Referenced by DsiSelfTestExample.
u32 XDsi_CfgInitialize(XDsi *InstancePtr, XDsi_Config *CfgPtr, UINTPTR EffectiveAddr)
Initialize the XDsi instance provided by the caller based on the given Config structure.
Initializes the DSI controller instance with hardware configuration information and sets up default callback handlers. InstancePtr is the XDsi instance to operate on. CfgPtr is the device configuration structure containing information about a specific DSI controller (base address, lanes, FIFO size, etc.) EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if initialization was successful.XST_FAILURE if initialization failed. All callback handlers are initialized to stub functions that will assert on invocation. Application must set actual callback handlers using XDsi_SetCallback() if interrupt handling is required. XDsi_SetCallback
References XDsi_Config::BaseAddr, XDsi::CmdQFIFOFullCallback, XDsi::Config, XDsi::ErrorCallback, XDsi::IsReady, XDsi::PixelDataUnderrunCallback, XDsi::UnSupportedDataTypeCallback.
Referenced by DsiSelfTestExample.
u32 XDsi_Activate(XDsi *InstancePtr, XDsi_Selection Flag)
Enable or disable the DSI controller core.
Activates or deactivates the DSI controller IP core. When enabling (Flag=XDSI_ENABLE), the global interrupt output is set and the core is enabled for packet processing. When disabling (Flag=XDSI_DISABLE), the global interrupt is reset and the core is disabled. InstancePtr is the XDsi instance to operate on. The instance must have been initialized via XDsi_CfgInitialize(). Flag indicates the desired action: XDSI_ENABLE: Enable global interrupt and activate DSI coreXDSI_DISABLE: Reset global interrupt and disable DSI core XST_SUCCESS if enable/disable operation was successful. XST_INVALID_PARAM if an invalid Flag value is provided. Must be called after XDsi_CfgInitialize() and XDsi_DefaultConfigure(). The core must be configured with video mode or command mode settings before activation. XDsi_CfgInitialize, XDsi_DefaultConfigure, XDsi_SetMode
References XDsi::IsReady, XDSI_DISABLE.
void XDsi_Reset(XDsi *InstancePtr)
Perform a soft reset of the DSI controller.
Resets the DSI controller including interrupt status registers, command queue FIFO, and state machine. The controller gracefully waits for current operations to complete before resetting. After reset is released, controller starts from VSS (Vertical Sync Start) packet (new video frame). InstancePtr is the XDsi instance to operate on. None.
u32 XDsi_DefaultConfigure(XDsi *InstancePtr)
Configure default DSI protocol settings.
Configures the DSI controller protocol register with video mode, blank packet mode, blank packet type, and End-of-Transmission (EoTP) packet settings based on the instance parameters. This function sets up the Protocol Control Register (PCR) with the instance VideoMode, BlankPacketType, BLLPMode, and EoTp configuration values. InstancePtr is the XDsi instance to operate on. The instance must have been initialized via XDsi_CfgInitialize(). XST_SUCCESS if configuration was successful. This function assumes the instance is already initialized. The instance member variables (VideoMode, BlankPacketType, BLLPMode, EoTp) must be set before calling this function or it will use default/uninitialized values. XDsi_CfgInitialize, XDsi_Activate
References XDsi::BlankPacketType, XDsi::BLLPMode, XDsi::EoTp, XDsi::IsReady, XDsi::VideoMode, XDSI_PCR_BLLPMODE_MASK, XDSI_PCR_BLLPMODE_SHIFT, XDSI_PCR_BLLPTYPE_MASK, XDSI_PCR_BLLPTYPE_SHIFT, XDSI_PCR_EOTPENABLE_MASK, XDSI_PCR_EOTPENABLE_SHIFT, XDSI_PCR_OFFSET, XDSI_PCR_VIDEOMODE_MASK, XDSI_PCR_VIDEOMODE_SHIFT.
u32 XDsi_SelfTest(XDsi *InstancePtr)
Runs a self-test on the driver/device.
This test checks if the LaneCount present in register matches the one from the generated file. InstancePtr is a pointer to the XDsi instance. XST_SUCCESS if self-test was successfulXST_FAILURE if the read value was not equal to GUI parameter None
References XDsi_Config::BaseAddr, XDsi::Config, XDsi_Config::DsiLanes, XDsi::IsReady, XDSI_PCR_ACTLANES_MASK, XDSI_PCR_ACTLANES_SHIFT, XDSI_PCR_OFFSET.
Referenced by DsiSelfTestExample.
void XDsi_SendShortPacket(XDsi *InstancePtr, XDsi_ShortPacket *ShortPacket)
Send a DSI short packet to the controller.
Sends a DSI short packet (up to 2 data bytes) to the DSI controller via the Generic Short Packet Register. The function packs the Virtual Channel ID, Data Type, and two data bytes into the command register format and writes to the XDSI_COMMAND_OFFSET register. Short packets are typically used for commands and status updates. InstancePtr is the XDsi instance to operate on. The instance must have been initialized and activated. ShortPacket is a pointer to the XDsi_ShortPacket structure containing: VcId: Virtual channel identifier (0-3)DataType: DSI data type code for the packetData0: First data byteData1: Second data byte This function does not wait for transmission to complete. The caller must check controller status if synchronization is needed. Only valid for sending up to 2 bytes of data; use XDsi_SendLongPacket() for longer payloads. XDsi_SendLongPacket, XDsi_SendCmdModePkt
References XDsi_Config::BaseAddr, XDsi::Config, XDsi_ShortPacket::Data0, XDsi_ShortPacket::Data1, XDsi_ShortPacket::DataType, XDsi_ShortPacket::VcId, XDSI_COMMAND_OFFSET, XDSI_SPKTR_BYTE1_SHIFT, XDSI_SPKTR_BYTE2_SHIFT, XDSI_SPKTR_VC_SHIFT.
Referenced by XDsi_SendCmdModePkt, XDsi_SendLongPacket.
int XDsi_SendCmdModePkt(XDsi *InstancePtr, XDsiTx_CmdModePkt *CmdPktData)
Send a DSI command mode packet (short or long).
Sends a DSI packet in command mode. This function supports both short packets (up to 2 bytes) and long packets (up to 255 bytes). It waits for the controller to be ready for the appropriate packet type before transmission. For short packets, waits on XDSI_GetReadyForShortPkt(); for long packets, waits on XDSI_GetReadyForLongPkt(). InstancePtr is the XDsi instance to operate on. The instance must have been initialized, activated, and switched to command mode via XDsi_SetMode(XDSI_COMMAND_MODE). CmdPktData is a pointer to the XDsiTx_CmdModePkt structure specifying: CmdPkt: Packet type (XDSI_CMD_MODE_SHORT_PKT or XDSI_CMD_MODE_LONG_PKT)SpktData: Short packet header informationLongPktData: Payload for long packets XST_SUCCESS if the DSI packet was successfully sent.XST_FAILURE if DSI is not enabled or not in command mode. This function blocks waiting for the controller to be ready. Ensure controller is in command mode before calling. The appropriate packet type must be selected in CmdPktData->CmdPkt. XDsi_SetMode, XDsi_SendShortPacket, XDsi_SendLongPacket
References XDsiTx_CmdModePkt::CmdPkt, XDsiTx_CmdModePkt::SpktData, XDSI_CMD_MODE_SHORT_PKT, XDsi_SendLongPacket, XDsi_SendShortPacket.
int XDsi_SetMode(XDsi *InstancePtr, XDsi_DsiModeType mode)
Switch DSI controller between video and command modes.
Configures the DSI controller to operate in either video mode or command mode. In video mode, the controller processes continuous video frame data streams with synchronization packets. In command mode, the controller accepts individual short and long packets sent by the application. Transitions between modes include appropriate waits for pending operations to complete. InstancePtr is the XDsi instance to operate on. The instance must have been initialized via XDsi_CfgInitialize(). mode is the desired DSI mode: XDSI_VIDEO_MODE: Configure for continuous video stream processingXDSI_COMMAND_MODE: Configure for packet-based command transmission XST_SUCCESS if mode switch was successful.XST_INVALID_PARAM if the requested mode is invalid or an invalid transition is attempted. Certain mode transitions are not allowed by the hardware. For example, cannot switch from video mode to command mode directly while in progress. The function waits for XDsi_GetInProgress() to clear before switching. XDsi_CfgInitialize, XDsi_SendCmdModePkt
References XDSI_COMMAND_MODE, XDSI_VIDEO_MODE.
void XDsi_GetConfigParams(XDsi *InstancePtr, XDsi_ConfigParameters *ConfigInfo)
Read current DSI controller configuration parameters.
Reads the current configuration settings from the DSI controller hardware registers and the driver instance. This includes the protocol control settings (video mode, blank packet type, BLLP mode, EoTP), timing parameters (HSA, VACT, blanking intervals, etc.), and line/BLLP timing. All settings are populated into the provided ConfigInfo structure. InstancePtr is the XDsi instance to operate on. The instance must have been initialized via XDsi_CfgInitialize(). ConfigInfo is a pointer to the XDsi_ConfigParameters structure to be filled with current configuration. The structure will contain: Config: GUI configuration settingsVideoMode: Current video transmission modeBlankPacketType: Blanking packet type for BLLPBLLPMode: Blank packet mode selectionEoTp: End-of-Transmission packet enable statusTiming: All horizontal/vertical timing parametersLineTime, BLLPTime: Total line and BLLP timing values This function performs multiple register reads. The caller must ensure the controller is in a stable state before reading. Timing parameters reflect current register values which may differ from hard-coded configuration if modified at runtime. XDsi_CfgInitialize, XDsi_DefaultConfigure
References XDsi_Config::BaseAddr, XDsi_ConfigParameters::BlankPacketType, XDsi_VideoTiming::BLLPBurst, XDsi_ConfigParameters::BLLPMode, XDsi_ConfigParameters::BLLPTime, XDsi_ConfigParameters::Config, XDsi::Config, XDsi_ConfigParameters::EoTp, XDsi_VideoTiming::HActive, XDsi_VideoTiming::HBackPorch, XDsi_VideoTiming::HFrontPorch, XDsi_VideoTiming::HSyncWidth, XDsi_ConfigParameters::LineTime, XDsi_ConfigParameters::Timing, XDsi_VideoTiming::VActive, XDsi_VideoTiming::VBackPorch, XDsi_VideoTiming::VFrontPorch, XDsi_ConfigParameters::VideoMode, XDsi_VideoTiming::VSyncWidth, XDSI_BLLP_TIME_MASK, XDSI_BLLP_TIME_OFFSET, XDSI_BLLP_TIME_SHIFT, XDSI_LTIME_MASK, XDSI_LTIME_OFFSET, XDSI_LTIME_SHIFT, XDSI_PCR_BLLPMODE_MASK, XDSI_PCR_BLLPMODE_SHIFT, XDSI_PCR_BLLPTYPE_MASK, XDSI_PCR_BLLPTYPE_SHIFT, XDSI_PCR_EOTPENABLE_MASK, XDSI_PCR_EOTPENABLE_SHIFT, XDSI_PCR_OFFSET, XDSI_PCR_VIDEOMODE_MASK, XDSI_PCR_VIDEOMODE_SHIFT, XDSI_TIME1_BLLP_BURST_MASK, XDSI_TIME1_BLLP_BURST_SHIFT, XDSI_TIME1_HSA_MASK, XDSI_TIME1_HSA_SHIFT, XDSI_TIME1_OFFSET, XDSI_TIME2_HACT_MASK, XDSI_TIME2_HACT_SHIFT, XDSI_TIME2_OFFSET, XDSI_TIME2_VACT_MASK, XDSI_TIME2_VACT_SHIFT, XDSI_TIME3_HBP_MASK, XDSI_TIME3_HBP_SHIFT, XDSI_TIME3_HFP_MASK, XDSI_TIME3_HFP_SHIFT, XDSI_TIME3_OFFSET, XDSI_TIME4_OFFSET, XDSI_TIME4_VBP_MASK, XDSI_TIME4_VBP_SHIFT, XDSI_TIME4_VFP_MASK, XDSI_TIME4_VFP_SHIFT, XDSI_TIME4_VSA_MASK, XDSI_TIME4_VSA_SHIFT, XDSI_TIME5_OFFSET, XDSI_TIME5_VFP_MASK, XDSI_TIME5_VFP_SHIFT.
s32 XDsi_SetVideoInterfaceTiming(XDsi *InstancePtr, XDsi_VideoMode VideoMode, XVidC_VideoMode Resolution, u16 BurstPacketSize)
Configure video interface timing based on standard resolution.
Sets the DSI controller video interface timing parameters based on a specified video mode and standard resolution. Looks up timing parameters from the video common library (XVidC_GetVideoModeData), including horizontal and vertical synchronization, active regions, and blanking intervals. The burst packet size is set for burst mode operations. This function is typically called for standard video resolutions (e.g., 1920x1080@60Hz). InstancePtr is the XDsi instance to operate on. The instance must have been initialized via XDsi_CfgInitialize(). VideoMode specifies the DSI video transmission mode: XDSI_VM_NON_BURST_SYNC_PULSES: Non-burst with sync pulsesXDSI_VM_NON_BURST_SYNC_EVENT: Non-burst with sync eventsXDSI_VM_BURST_MODE: Burst mode transmission Resolution specifies the video resolution to configure (e.g., XVIDC_VM_1920x1080_60_P for 1920x1080@60Hz progressive). BurstPacketSize specifies the packet size for burst mode blanking. XST_SUCCESS if video interface timing was successfully configured.XST_FAILURE if the requested resolution is not supported or timing information cannot be retrieved. This function looks up timing data from the video common library. The requested resolution must be supported by the library. For custom resolutions not in the library, use XDsi_SetCustomVideoInterfaceTiming(). XDsi_SetCustomVideoInterfaceTiming, XVidC_GetVideoModeData
References XDsi_Config::BaseAddr, XDsi::Config, XDSI_PCR_OFFSET, XDSI_PCR_VIDEOMODE_MASK, XDSI_PCR_VIDEOMODE_SHIFT, XDSI_TIME1_BLLP_BURST_MASK, XDSI_TIME1_BLLP_BURST_SHIFT, XDSI_TIME1_HSA_MASK, XDSI_TIME1_HSA_SHIFT, XDSI_TIME1_OFFSET, XDSI_TIME2_HACT_MASK, XDSI_TIME2_HACT_SHIFT, XDSI_TIME2_OFFSET, XDSI_TIME2_VACT_MASK, XDSI_TIME2_VACT_SHIFT, XDSI_TIME3_HBP_MASK, XDSI_TIME3_HBP_SHIFT, XDSI_TIME3_HFP_MASK, XDSI_TIME3_HFP_SHIFT, XDSI_TIME3_OFFSET, XDSI_TIME4_OFFSET, XDSI_TIME4_VBP_MASK, XDSI_TIME4_VBP_SHIFT, XDSI_TIME4_VFP_MASK, XDSI_TIME4_VFP_SHIFT, XDSI_TIME4_VSA_MASK, XDSI_TIME4_VSA_SHIFT, XDSI_TIME5_OFFSET, XDSI_TIME5_VFP_MASK, XDSI_TIME5_VFP_SHIFT, XDSI_VM_NUM_SUPPORTED.
s32 XDsi_SetCustomVideoInterfaceTiming(XDsi *InstancePtr, XDsi_VideoMode VideoMode, XDsi_VideoTiming *Timing)
Configure video interface timing with custom parameters.
Sets the DSI controller video interface timing parameters using user-provided custom timing values. Unlike XDsi_SetVideoInterfaceTiming() which uses standard resolutions from the video library, this function allows arbitrary custom timing configurations. Horizontal and vertical synchronization, active region, and blanking parameters are all configurable. Burst packet size is only applied in burst mode. InstancePtr is the XDsi instance to operate on. The instance must have been initialized via XDsi_CfgInitialize(). VideoMode specifies the DSI video transmission mode: XDSI_VM_NON_BURST_SYNC_PULSES: Non-burst with sync pulsesXDSI_VM_NON_BURST_SYNC_EVENT: Non-burst with sync eventsXDSI_VM_BURST_MODE: Burst mode (burst packet size applies) Timing is a pointer to the XDsi_VideoTiming structure containing custom timing parameters: HActive: Active horizontal pixels/bytes per lineHFrontPorch, HSyncWidth, HBackPorch: Horizontal blanking intervalsVActive: Active vertical linesVFrontPorch, VSyncWidth, VBackPorch: Vertical blanking intervalsBLLPBurst: Burst packet size (only used in burst mode) XST_SUCCESS if video interface timing was successfully configured. This function allows maximum flexibility but does not validate timing parameters for spec compliance. Burst packet size is only written in burst mode; non-burst modes override it to 0. Ensure custom timing values comply with DSI and display controller specifications. XDsi_SetVideoInterfaceTiming
References XDsi_Config::BaseAddr, XDsi_VideoTiming::BLLPBurst, XDsi::Config, XDsi_VideoTiming::HActive, XDsi_VideoTiming::HBackPorch, XDsi_VideoTiming::HFrontPorch, XDsi_VideoTiming::HSyncWidth, XDsi_VideoTiming::VActive, XDsi_VideoTiming::VBackPorch, XDsi_VideoTiming::VFrontPorch, XDsi_VideoTiming::VSyncWidth, XDSI_PCR_OFFSET, XDSI_PCR_VIDEOMODE_MASK, XDSI_PCR_VIDEOMODE_SHIFT, XDSI_TIME1_BLLP_BURST_MASK, XDSI_TIME1_BLLP_BURST_SHIFT, XDSI_TIME1_HSA_MASK, XDSI_TIME1_HSA_SHIFT, XDSI_TIME1_OFFSET, XDSI_TIME2_HACT_MASK, XDSI_TIME2_HACT_SHIFT, XDSI_TIME2_OFFSET, XDSI_TIME2_VACT_MASK, XDSI_TIME2_VACT_SHIFT, XDSI_TIME3_HBP_MASK, XDSI_TIME3_HBP_SHIFT, XDSI_TIME3_HFP_MASK, XDSI_TIME3_HFP_SHIFT, XDSI_TIME3_OFFSET, XDSI_TIME4_OFFSET, XDSI_TIME4_VBP_MASK, XDSI_TIME4_VBP_SHIFT, XDSI_TIME4_VFP_MASK, XDSI_TIME4_VFP_SHIFT, XDSI_TIME4_VSA_MASK, XDSI_TIME4_VSA_SHIFT, XDSI_TIME5_OFFSET, XDSI_TIME5_VFP_MASK, XDSI_TIME5_VFP_SHIFT, XDSI_VM_BURST_MODE, XDSI_VM_NUM_SUPPORTED.
s32 XDsi_SetCallback(XDsi *InstancePtr, u32 HandleType, void *CallbackFunc, void *CallbackRef)
This routine installs an asynchronous callback function for the given HandlerType:
HandlerType Invoked by this driver when: ----------------------- -------------------------------------------------- XDSI_HANDLER_UNSUPPORT_DATATYPE Un support data type detected XDSI_HANDLER_PIXELDATA_UNDERRUN Byte stream FIFO starves for Pixel during HACT transmission XDSI_HANDLER_OTHERERROR Any other type of interrupt has occurred like Stream Line Buffer Full, Incorrect Lanes, etc XDSI_HANDLER_CMDQ_FIFOFULL Command queue FIFO full InstancePtr is the XDsi instance to operate on HandleType is the type of call back to be registered. CallbackFunc is the pointer to a call back function which is called when a particular event occurs. CallbackRef is a void pointer to data to be referenced to by the CallbackFunc XST_SUCCESS when handler is installed. XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XDsi::CmdQFIFOFullCallback, XDsi::CmdQFIFOFullRef, XDsi::ErrorCallback, XDsi::ErrRef, XDsi::IsReady, XDsi::PixelDataUnderrunCallback, XDsi::PixelDataUnderrundRef, XDsi::UnsupportDataTypeRef, XDsi::UnSupportedDataTypeCallback, XDSI_HANDLER_CMDQ_FIFOFULL, XDSI_HANDLER_OTHERERROR, XDSI_HANDLER_PIXELDATA_UNDERRUN, XDSI_HANDLER_UNSUPPORT_DATATYPE.