spdif
XSpdif_HandlerType
Transmitter or Receiver FIFO Full Handler.
XSPDIF_AES_STS_USE_OF_CH_STS_BLK_SHIFT
Use of Channel Status Block bit shift.
XSPDIF_AES_STS_USE_OF_CH_STS_BLK_MASK
Use of Channel Status Block mask.
Referenced by XSpdif_Decode_ChStat.
XSPDIF_AES_STS_LINEAR_PCM_ID_SHIFT
Linear PCM Identification bit shift.
Referenced by XSpdif_Decode_ChStat.
XSPDIF_AES_STS_LINEAR_PCM_ID_MASK
Linear PCM Identification mask.
Referenced by XSpdif_Decode_ChStat.
XSPDIF_AES_STS_AUDIO_SIG_PRE_EMPH_SHIFT
Audio signal pre- emphasis bit shift.
Referenced by XSpdif_Decode_ChStat.
XSPDIF_AES_STS_AUDIO_SIG_PRE_EMPH_MASK
Audio signal pre-emphasis mask.
Referenced by XSpdif_Decode_ChStat.
XSPDIF_AES_STS_LOCK_INDICATION_SHIFT
lock indication bit shift
Referenced by XSpdif_Decode_ChStat.
XSPDIF_AES_STS_LOCK_INDICATION_MASK
Lock indication mask.
Referenced by XSpdif_Decode_ChStat.
XSPDIF_AES_STS_SAMPLING_FREQ_E_SHIFT
Sampling Frequency 0 bit shift.
Referenced by XSpdif_Decode_ChStat.
XSPDIF_AES_STS_SAMPLING_FREQ_E_MASK
Sampling Frequency 0 mask.
Referenced by XSpdif_Decode_ChStat.
XSPDIF_AES_STS_CH_MODE_SHIFT
Channel mode bit shift.
XSPDIF_AES_STS_CH_MODE_MASK
Channel mode mask.
Referenced by XSpdif_Decode_ChStat.
XSPDIF_AES_STS_USR_BITS_MGMT_SHIFT
User Bits Management bit shift.
Referenced by XSpdif_Decode_ChStat.
XSPDIF_AES_STS_USR_BITS_MGMT_MASK
User Bits Management mask.
Referenced by XSpdif_Decode_ChStat.
XSPDIF_AES_STS_USEOF_AUX_SMPL_BITS_SHIFT
Use of auxiliary sample bits bit shift.
XSPDIF_AES_STS_USEOF_AUX_SMPL_BITS_MASK
Use of Auxiliary sample bits mask.
Referenced by XSpdif_Decode_ChStat.
XSPDIF_AES_STS_SRC_WORD_LENGTH_SHIFT
Source word length bit shift.
Referenced by XSpdif_Decode_ChStat.
XSPDIF_AES_STS_SRC_WORD_LENGTH_MASK
Source word length mask.
Referenced by XSpdif_Decode_ChStat.
XSPDIF_AES_STS_INDICATE_ALIGN_LEVEL_SHIFT
Indication of Alignment level bit shift.
Referenced by XSpdif_Decode_ChStat.
XSPDIF_AES_STS_INDICATE_ALIGN_LEVEL_MASK
Indication of Alignment level mask.
Referenced by XSpdif_Decode_ChStat.
XSPDIF_AES_STS_CH_NUM0_SHIFT
Channel Number (0) bit shift.
XSPDIF_AES_STS_CH_NUM0_MASK
Channel Number (0) mask.
Referenced by XSpdif_Decode_ChStat.
XSPDIF_AES_STS_MC_CH_MODE_SHIFT
Multichannel mode bit shift.
Referenced by XSpdif_Decode_ChStat.
XSPDIF_AES_STS_MC_CH_MODE_MASK
Multichannel mode mask.
Referenced by XSpdif_Decode_ChStat.
XSPDIF_AES_STS_CH_NUM1_SHIFT
Channel Number (1) bit shift.
XSPDIF_AES_STS_CH_NUM1_MASK
Channel Number (1) mask.
Referenced by XSpdif_Decode_ChStat.
XSPDIF_AES_STS_MC_CH_MODE_NUM_SHIFT
Multichannel mode number bit shift.
Referenced by XSpdif_Decode_ChStat.
XSPDIF_AES_STS_MC_CH_MODE_NUM_MASK
Multichannel mode number mask.
Referenced by XSpdif_Decode_ChStat.
XSPDIF_AES_STS_DIGITAL_AUDIO_REF_SIG_SHIFT
Digital Reference Audio signal bit shift.
Referenced by XSpdif_Decode_ChStat.
XSPDIF_AES_STS_DIGITAL_AUDIO_REF_SIG_MASK
Digital Reference Audio signal mask.
Referenced by XSpdif_Decode_ChStat.
XSPDIF_AES_STS_RSVD_BUT_UNDEF0_SHIFT
Reserved but undefined (0) bit shift.
Referenced by XSpdif_Decode_ChStat.
XSPDIF_AES_STS_RSVD_BUT_UNDEF0_MASK
Reserved but undefined (0) mask.
Referenced by XSpdif_Decode_ChStat.
XSPDIF_AES_STS_SAMPLING_FREQ_Q_SHIFT
Sampling Frequency (1) bit shift.
Referenced by XSpdif_Decode_ChStat.
XSPDIF_AES_STS_SAMPLING_FREQ_Q_MASK
Sampling Frequency (1) mask.
Referenced by XSpdif_Decode_ChStat.
XSPDIF_AES_STS_SAMPLING_FREQ_SCALE_FLAG_SHIFT
Sampling Frequency scaling flag bit shift.
Referenced by XSpdif_Decode_ChStat.
XSPDIF_AES_STS_SAMPLING_FREQ_SCALE_FLAG_MASK
Sampling Frequency scaling flag mask.
Referenced by XSpdif_Decode_ChStat.
XSPDIF_AES_STS_RSVD_BUT_UNDEF1_SHIFT
Reserved but undefined (1) bit shift.
XSPDIF_AES_STS_RSVD_BUT_UNDEF1_MASK
Reserved but undefined (1) mask.
Referenced by XSpdif_Decode_ChStat.
XSPDIF_AES_STS_ALPHANUM_CH_ORG_DATA_OFFSET
Alphanumeric channel origin data register(s) offset.
XSPDIF_AES_STS_ALPHANUM_CH_DEST_DATA_OFFSET
Alphanumeric channel destination data bit shift.
XSPDIF_AES_STS_LOCAL_SAMPLE_ADDRCODE_OFFSET
Local sample address code register(s) offset.
XSPDIF_AES_STS_TIMEOFDAY_SAMPLE_ADDRCODE_OFFSET
Time-of-day sample address code register(s) offset.
XSPDIF_AES_STS_RELIABLE_FLAGS_OFFSET
Reliability flags bit shift.
Referenced by XSpdif_Decode_ChStat.
XSPDIF_AES_STS_CRC_CHAR_OFFSET
Cyclic redundancy check character bit shift.
Referenced by XSpdif_Decode_ChStat.
XSPDIF_GLOBAL_INTERRUPT_ENABLE_OFFSET
Device Global interrupt enable register.
XSPDIF_INTERRUPT_STATUS_REGISTER_OFFSET
IP Interrupt Status Register.
Referenced by XSpdif_IntrHandler.
XSPDIF_INTERRUPT_ENABLE_REGISTER_OFFSET
IP interrupt enable Register.
Referenced by XSpdif_IntrHandler.
XSPDIF_SOFT_RESET_REGISTER_OFFSET
Soft Reset Register.
Referenced by XSpdif_SoftReset.
XSPDIF_CONTROL_REGISTER_OFFSET
Control Register.
Referenced by XSpdif_Enable, XSpdif_ResetFifo, XSpdif_SelfTest, XSpdif_SetClkConfig.
XSPDIF_STATUS_REGISTER_OFFSET
Status Register.
Referenced by XSpdif_GetFs.
XSPDIF_CHANNEL_STATUS_REGISTER0_OFFSET
Audio Channel Status bits 0 to 31.
Referenced by XSpdif_Rx_GetChStat.
XSPDIF_CHANNEL_A_USER_DATA_REGISTER0_OFFSET
Channel A user data bits 0 to 31.
Referenced by XSpdif_Rx_GetChA_UserData.
XSPDIF_CHANNEL_B_USER_DATA_REGISTER0_OFFSET
Channel B user data bits 0 to 31.
Referenced by XSpdif_Rx_GetChB_UserData.
XSPDIF_CORE_ENABLE_SHIFT
Is XSPDIF Core Enable bit shift.
XSPDIF_CORE_ENABLE_MASK
Is XSPDIF Core Enable bit mask.
Referenced by XSpdif_Enable, XSpdif_ResetFifo.
XSPDIF_FIFO_FLUSH_SHIFT
Is XSPDIF Reset FIFO bit shift.
XSPDIF_FIFO_FLUSH_MASK
Is XSPDIF Reset FIFO bit mask.
XSPDIF_CLOCK_CONFIG_BITS_SHIFT
Is XSPDIF clock configuration bits shift.
Referenced by XSpdif_SetClkConfig.
XSPDIF_CLOCK_CONFIG_BITS_MASK
Is XSPDIF clock configuration bits mask.
Referenced by XSpdif_SetClkConfig.
XSPDIF_SAMPLE_CLOCK_COUNT_SHIFT
XSPDIF sample clock count shift.
XSPDIF_SAMPLE_CLOCK_COUNT_MASK
XSPDIF sample clock count mask.
Referenced by XSpdif_GetFs.
XSPDIF_TX_OR_RX_FIFO_FULL_SHIFT
Transmitter or Receiver FIFO Full Interrupt bit shift.
XSPDIF_TX_OR_RX_FIFO_FULL_MASK
Transmitter or Receiver FIFO Full Interrupt bit mask.
Referenced by XSpdif_IntrHandler.
XSPDIF_TX_OR_RX_FIFO_EMPTY_SHIFT
Transmitter or Receiver FIFO Empty Interrupt bit shift.
XSPDIF_TX_OR_RX_FIFO_EMPTY_MASK
Transmitter or Receiver FIFO Empty Interrupt bit mask.
Referenced by XSpdif_IntrHandler.
XSPDIF_START_OF_BLOCK_SHIFT
Start of Block Interrupt bit mask ( in Receive mode)
XSPDIF_START_OF_BLOCK_MASK
Transmitter or Receiver FIFO Full Interrupt bit shift.
Referenced by XSpdif_IntrHandler.
XSPDIF_BMC_ERROR_SHIFT
BMC Error Interrupt bit shift.
XSPDIF_BMC_ERROR_MASK
BMC Error Interrupt bit mask.
Referenced by XSpdif_IntrHandler.
XSPDIF_PREAMBLE_ERROR_SHIFT
Preamble error Interrupt bit shift.
XSPDIF_PREAMBLE_ERROR_MASK
Preamble error Interrupt bit mask.
Referenced by XSpdif_IntrHandler.
XSPDIF_GINTR_ENABLE_SHIFT
Global interrupt enable bit shift.
XSPDIF_GINTR_ENABLE_MASK
Global interrupt enable bit mask.
XSpdif_In32
Input Operations.
XSpdif_Out32
Output Operations.
XSpdif_ReadReg
This macro reads a value from a XSpdif register.
A 32 bit read is performed. If the component is implemented in a smaller width, only the least significant data is read from the register. The most significant data will be read as 0. BaseAddress is the base address of the XSpdif core instance. RegOffset is the register offset of the register (defined at the top of this file). The 32-bit value of the register. C-style signature: u32 XSpdif_ReadReg(u32 BaseAddress, u32 RegOffset)
Referenced by XSpdif_Enable, XSpdif_GetFs, XSpdif_IntrHandler, XSpdif_ResetFifo, XSpdif_Rx_GetChA_UserData, XSpdif_Rx_GetChB_UserData, XSpdif_Rx_GetChStat, XSpdif_SelfTest, XSpdif_SetClkConfig.
XSpdif_WriteReg
This macro writes a value to a XSpdif register.
A 32 bit write is performed. If the component is implemented in a smaller width, only the least significant data is written. BaseAddress is the base address of the XSpdif core instance. RegOffset is the register offset of the register (defined at the top of this file) to be written. Data is the 32-bit value to write into the register. None. C-style signature: void XSpdif_WriteReg(u32 BaseAddress, u32 RegOffset, u32 Data)
Referenced by XSpdif_Enable, XSpdif_ResetFifo, XSpdif_SetClkConfig, XSpdif_SoftReset.
XSpdif_Callback)(void *CallbackRef)
Callback function pointer type for SPDIF driver events.
This typedef defines the function signature for callback functions used by the SPDIF driver to notify the application of asynchronous events. CallbackRef A void pointer to user-defined callback reference data. This parameter is typically used to pass context information or a pointer to the instance structure associated with the callback. The callback function should complete execution promptly to avoid blocking interrupt processing. XSpdif_SetCallback
XSpdif_Config XSpdif_ConfigTable[][]
int XSpdif_CfgInitialize(XSpdif *InstancePtr, XSpdif_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the XSpdif.
This function must be called prior to using the core. Initialization of the XSpdif includes setting up the instance data, and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the XSpdif instance. CfgPtr points to the configuration structure associated with the XSpdif. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS : if successful.XST_FAILURE : if version mismatched. None.
References XSpdif_Config::BaseAddress, XSpdif::Config, XSpdif::IsReady, XSpdif_Enable, XSpdif_SelfTest.
Referenced by SpdifSelfTestExample, XSpdif_Initialize.
void XSpdif_Enable(XSpdif *InstancePtr, u8 Enable)
This function enables/disables the XSpdif.
InstancePtr is a pointer to the XSpdif instance. Enable specifies TRUE/FALSE value to either enable or disable the XSpdif.
References XSpdif_Config::BaseAddress, XSpdif::Config, XSpdif::IsStarted, XSPDIF_CONTROL_REGISTER_OFFSET, XSPDIF_CORE_ENABLE_MASK, XSpdif_ReadReg, XSpdif_WriteReg.
Referenced by XSpdif_CfgInitialize, XSpdif_SelfTest.
void XSpdif_SoftReset(XSpdif *InstancePtr)
This function is used to soft reset the interrupt registers.
InstancePtr is a pointer to the XSPDIF instance.
References XSpdif_Config::BaseAddress, XSpdif::Config, XSPDIF_SOFT_RESET_REGISTER_OFFSET, XSPDIF_SOFT_RESET_REGISTER_VALUE, XSpdif_WriteReg.
Referenced by XSpdif_SelfTest.
void XSpdif_ResetFifo(XSpdif *InstancePtr)
This function resets the Fifo.
InstancePtr is a pointer to the XSpdif instance.
References XSpdif_Config::BaseAddress, XSpdif::Config, XSPDIF_CONTROL_REGISTER_OFFSET, XSPDIF_CORE_ENABLE_MASK, XSpdif_ReadReg, XSpdif_WriteReg.
void XSpdif_SetClkConfig(XSpdif *InstancePtr, u8 Clk_DivNum)
This function sets the clock configuration bits.
InstancePtr is a pointer to the Spdif instance. Clk_DivNum is the clock division number. Clk_DivNum value can be only 4,8,16,24,32,48,or 64.
References XSpdif_Config::BaseAddress, XSpdif::Config, XSPDIF_CLK_16, XSPDIF_CLK_24, XSPDIF_CLK_32, XSPDIF_CLK_4, XSPDIF_CLK_48, XSPDIF_CLK_64, XSPDIF_CLK_8, XSPDIF_CLOCK_CONFIG_BITS_MASK, XSPDIF_CLOCK_CONFIG_BITS_SHIFT, XSPDIF_CONTROL_REGISTER_OFFSET, XSpdif_ReadReg, XSpdif_WriteReg.
u32 XSpdif_GetFs(XSpdif *InstancePtr, u32 AudClk)
This function calculates the Sampling Frequency (Fs) and returns it's value.
InstancePtr is a pointer to the XSpdif instance. AudClk is the audio clock frequency value in Hz. - Returns the sampling frequency value in Hz.
References XSpdif_Config::BaseAddress, XSpdif::Config, XSpdif_ReadReg, XSPDIF_SAMPLE_CLOCK_COUNT_MASK, XSPDIF_STATUS_REGISTER_OFFSET.
void XSpdif_Rx_GetChStat(XSpdif *InstancePtr, u8 *ChStatBuf)
This function reads all the Channel Status registers and writes to a buffer.
InstancePtr is a pointer to the XSpdif instance. ChStatBuf is a pointer to a buffer.
References XSpdif_Config::BaseAddress, XSpdif::Config, XSPDIF_CHANNEL_STATUS_REGISTER0_OFFSET, XSpdif_ReadReg.
void XSpdif_Rx_GetChA_UserData(XSpdif *InstancePtr, u8 *ChA_UserDataBuf)
This function reads the Channel A user data and writes to a buffer.
InstancePtr is a pointer to the XSPDIF instance. ChA_UserDataBuf is a pointer to a buffer.
References XSpdif_Config::BaseAddress, XSpdif::Config, XSPDIF_CHANNEL_A_USER_DATA_REGISTER0_OFFSET, XSpdif_ReadReg.
void XSpdif_Rx_GetChB_UserData(XSpdif *InstancePtr, u8 *ChB_UserDataBuf)
This function reads the Channel B user data and writes to a buffer.
InstancePtr is a pointer to the XSPDIF instance. ChB_UserDataBuf is a pointer to a buffer.
References XSpdif_Config::BaseAddress, XSpdif::Config, XSPDIF_CHANNEL_B_USER_DATA_REGISTER0_OFFSET, XSpdif_ReadReg.
XSpdif_Config * XSpdif_LookupConfig(UINTPTR BaseAddress)
This function returns a reference to an XSpdif_Config structure based on the core id, DeviceId.
The return value will refer to an entry in the device configuration table defined in the xspdif_g.c file. DeviceId is the unique core ID of the XSpdif core for the lookup operation. returns a reference to a config record in the configuration table corresponding to DeviceId, or NULL if no match is found. None.
Referenced by SpdifSelfTestExample, XSpdif_Initialize.
int XSpdif_Initialize(XSpdif *InstancePtr, UINTPTR BaseAddress)
Initializes a specific Xspdif instance such that the driver is ready to use.
InstancePtr is a pointer to the XSpdif instance to be worked on. DeviceId is the unique id of the device controlled by this XSpdif instance. Passing in a device id associates the generic XSpdif instance to a specific device, as chosen by the caller or application developer. XST_SUCCESS if successful.XST_DEVICE_NOT_FOUND if the device was not found in the configuration such that initialization could not be accomplished.XST_FAILURE if version mismatched
References XSpdif_Config::BaseAddress, XSpdif_CfgInitialize, XSpdif_LookupConfig.
static void XSpdif_IntrClear(XSpdif *InstancePtr, u32 Mask)
This function clears the specified interrupt of the XSpdif.
InstancePtr is a pointer to the XSpdif core instance. Mask is a bit mask of the interrupts to be cleared. xspdif_hw.h file for the available interrupt masks.
static void XSpdif_Global_IntEnable(XSpdif *InstancePtr)
This function globally enables the final interrupt out to the system.
InstancePtr is a pointer to the XSpdif instance.
static void XSpdif_IntrDisable(XSpdif *InstancePtr, u32 Mask)
This function disables the specified interrupt of the XSpdif.
InstancePtr is a pointer to the XSpdif instance. Mask is a bit mask of the interrupts to be disabled. None. xspdif_hw.h file for the available interrupt masks.
static void XSpdif_IntrEnable(XSpdif *InstancePtr, u32 Mask)
This function enables the specified interrupt of the XSpdif.
InstancePtr is a pointer to the XSpdif instance. Mask is a bit mask of the interrupts to be enabled. None. xspdf_hw.h file for the available interrupt masks.
void XSpdif_IntrHandler(void *InstancePtr)
This function is the interrupt handler for the XSpdif driver.
This handler reads the pending interrupt from the XSpdif peripheral, determines the source of the interrupts, clears the interrupts and calls call backs accordingly. InstancePtr is a pointer to the XSpdif instance. None.
References XSpdif_Config::BaseAddress, XSpdif::BmcErrHandler, XSpdif::BmcErrHandlerRef, XSpdif::Config, XSpdif::IsReady, XSpdif::PreambleErrHandler, XSpdif::PreambleErrHandlerRef, XSpdif::StartOfBlockHandler, XSpdif::StartOfBlockHandlerRef, XSpdif::TxOrRxFifoEmptyHandler, XSpdif::TxOrRxFifoEmptyHandlerRef, XSpdif::TxOrRxFifoFullHandler, XSpdif::TxOrRxFifoFullHandlerRef, XSPDIF_BMC_ERROR_MASK, XSPDIF_INTERRUPT_ENABLE_REGISTER_OFFSET, XSPDIF_INTERRUPT_STATUS_REGISTER_OFFSET, XSPDIF_PREAMBLE_ERROR_MASK, XSpdif_ReadReg, XSPDIF_START_OF_BLOCK_MASK, XSPDIF_TX_OR_RX_FIFO_EMPTY_MASK, XSPDIF_TX_OR_RX_FIFO_FULL_MASK.
int XSpdif_SetHandler(XSpdif *InstancePtr, XSpdif_HandlerType HandlerType, XSpdif_Callback FuncPtr, void *CallbackRef)
This function installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function -------------------------------- ---------------------------------- (XSPDIF_HANDLER_START_OF_BLOCK) StartOfBlockHandler (XSPDIF_HANDLE_PREAMBLE_ERROR) PreambleErrHandler (XSPDIF_HANDLE_BMC_ERROR) BmcErrHandler (XSPDIF_HANDLER_TX_OR_RX_FIFO_EMPTY) TxOrRxFifoEmptyHandler (XSPDIF_HANDLER_TX_OR_RX_FIFO_FULL) TxOrRxFifoFullHandler InstancePtr is a pointer to the XSpdif core instance. HandlerType specifies the type of handler. FuncPtr is a pointer to the callback function. CallbackRef is a reference pointer passed on actual calling of the callback function. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XSpdif::BmcErrHandler, XSpdif::BmcErrHandlerRef, XSpdif::PreambleErrHandler, XSpdif::PreambleErrHandlerRef, XSpdif::StartOfBlockHandler, XSpdif::StartOfBlockHandlerRef, XSpdif::TxOrRxFifoEmptyHandler, XSpdif::TxOrRxFifoEmptyHandlerRef, XSpdif::TxOrRxFifoFullHandler, XSpdif::TxOrRxFifoFullHandlerRef, XSPDIF_HANDLER_BMC_ERROR, XSPDIF_HANDLER_PREAMBLE_ERROR, XSPDIF_HANDLER_START_OF_BLOCK, XSPDIF_HANDLER_TX_OR_RX_FIFO_EMPTY, XSPDIF_HANDLER_TX_OR_RX_FIFO_FULL, XSPDIF_NUM_HANDLERS.
int XSpdif_SelfTest(XSpdif *InstancePtr)
Performs a self-test on the SPDIF instance.
This function executes a series of self-tests on the specified SPDIF (Sony/Philips Digital Interface Format) instance to verify that the hardware is functioning correctly. InstancePtr Pointer to the XSpdif instance to be tested. This parameter must not be NULL. Returns XST_SUCCESS if the self-test passes successfully. Returns an error code (XST_FAILURE or other error constants) if the self-test fails. The instance must be initialized before calling this function. This function may temporarily affect the state of the SPDIF device during testing. XSpdif_Initialize() for instance initialization.
References XSpdif_Config::BaseAddress, XSpdif::Config, XSpdif::IsStarted, XSPDIF_CONTROL_REGISTER_OFFSET, XSpdif_Enable, XSpdif_ReadReg, XSpdif_SoftReset.
Referenced by XSpdif_CfgInitialize.
void XSpdif_Decode_ChStat(u8 Spdif_SrcBuf[24])
This function reads the array i.e.
Spdif_SrcBuffer which has the values of all the six Spdif AES status registers, extracts the required bits and displays them. Note: Call XSpdif_Rx_GetChStat API before calling XSpdif_Decode_ChStat API Spdif_SrcBuf is an array that contains the values of all the the AES Status registers.It contains 24 bytes i.e. 192 status bits.
References XSPDIF_AES_STS_AUDIO_SIG_PRE_EMPH_MASK, XSPDIF_AES_STS_AUDIO_SIG_PRE_EMPH_SHIFT, XSPDIF_AES_STS_CH_MODE_MASK, XSPDIF_AES_STS_CH_NUM0_MASK, XSPDIF_AES_STS_CH_NUM1_MASK, XSPDIF_AES_STS_CRC_CHAR_OFFSET, XSPDIF_AES_STS_DIGITAL_AUDIO_REF_SIG_MASK, XSPDIF_AES_STS_DIGITAL_AUDIO_REF_SIG_SHIFT, XSPDIF_AES_STS_INDICATE_ALIGN_LEVEL_MASK, XSPDIF_AES_STS_INDICATE_ALIGN_LEVEL_SHIFT, XSPDIF_AES_STS_LINEAR_PCM_ID_MASK, XSPDIF_AES_STS_LINEAR_PCM_ID_SHIFT, XSPDIF_AES_STS_LOCK_INDICATION_MASK, XSPDIF_AES_STS_LOCK_INDICATION_SHIFT, XSPDIF_AES_STS_MC_CH_MODE_MASK, XSPDIF_AES_STS_MC_CH_MODE_NUM_MASK, XSPDIF_AES_STS_MC_CH_MODE_NUM_SHIFT, XSPDIF_AES_STS_MC_CH_MODE_SHIFT, XSPDIF_AES_STS_RELIABLE_FLAGS_OFFSET, XSPDIF_AES_STS_RSVD_BUT_UNDEF0_MASK, XSPDIF_AES_STS_RSVD_BUT_UNDEF0_SHIFT, XSPDIF_AES_STS_RSVD_BUT_UNDEF1_MASK, XSPDIF_AES_STS_SAMPLING_FREQ_E_MASK, XSPDIF_AES_STS_SAMPLING_FREQ_E_SHIFT, XSPDIF_AES_STS_SAMPLING_FREQ_Q_MASK, XSPDIF_AES_STS_SAMPLING_FREQ_Q_SHIFT, XSPDIF_AES_STS_SAMPLING_FREQ_SCALE_FLAG_MASK, XSPDIF_AES_STS_SAMPLING_FREQ_SCALE_FLAG_SHIFT, XSPDIF_AES_STS_SRC_WORD_LENGTH_MASK, XSPDIF_AES_STS_SRC_WORD_LENGTH_SHIFT, XSPDIF_AES_STS_USE_OF_CH_STS_BLK_MASK, XSPDIF_AES_STS_USEOF_AUX_SMPL_BITS_MASK, XSPDIF_AES_STS_USR_BITS_MGMT_MASK, XSPDIF_AES_STS_USR_BITS_MGMT_SHIFT.
XSPDIF_SOFT_RESET_REGISTER_VALUE
Soft Reset Register value to reset.
Referenced by XSpdif_SoftReset.
XSPDIF_CLK_4
Clock divide by 4.
Referenced by XSpdif_SetClkConfig.
XSPDIF_CLK_8
Clock divide by 8.
Referenced by XSpdif_SetClkConfig.
XSPDIF_CLK_16
Clock divide by 16.
Referenced by XSpdif_SetClkConfig.
XSPDIF_CLK_24
Clock divide by 24.
Referenced by XSpdif_SetClkConfig.
XSPDIF_CLK_32
Clock divide by 32.
Referenced by XSpdif_SetClkConfig.
XSPDIF_CLK_48
Clock divide by 48.
Referenced by XSpdif_SetClkConfig.
XSPDIF_CLK_64
Clock divide by 64.
Referenced by XSpdif_SetClkConfig.