xspdif.c
XSPDIF_SOFT_RESET_REGISTER_VALUE
Soft Reset Register value to reset.
Referenced by XSpdif_SoftReset.
int XSpdif_CfgInitialize(XSpdif *InstancePtr, XSpdif_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the XSpdif.
This function must be called prior to using the core. Initialization of the XSpdif includes setting up the instance data, and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the XSpdif instance. CfgPtr points to the configuration structure associated with the XSpdif. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS : if successful.XST_FAILURE : if version mismatched. None.
References XSpdif_Config::BaseAddress, XSpdif::Config, XSpdif::IsReady, XSpdif_Enable, XSpdif_SelfTest.
Referenced by SpdifSelfTestExample, XSpdif_Initialize.
void XSpdif_Enable(XSpdif *InstancePtr, u8 Enable)
This function enables/disables the XSpdif.
InstancePtr is a pointer to the XSpdif instance. Enable specifies TRUE/FALSE value to either enable or disable the XSpdif.
References XSpdif_Config::BaseAddress, XSpdif::Config, XSpdif::IsStarted, XSPDIF_CONTROL_REGISTER_OFFSET, XSPDIF_CORE_ENABLE_MASK, XSpdif_ReadReg, XSpdif_WriteReg.
Referenced by XSpdif_CfgInitialize, XSpdif_SelfTest.
void XSpdif_SoftReset(XSpdif *InstancePtr)
This function is used to soft reset the interrupt registers.
InstancePtr is a pointer to the XSPDIF instance.
References XSpdif_Config::BaseAddress, XSpdif::Config, XSPDIF_SOFT_RESET_REGISTER_OFFSET, XSPDIF_SOFT_RESET_REGISTER_VALUE, XSpdif_WriteReg.
Referenced by XSpdif_SelfTest.
void XSpdif_ResetFifo(XSpdif *InstancePtr)
This function resets the Fifo.
InstancePtr is a pointer to the XSpdif instance.
References XSpdif_Config::BaseAddress, XSpdif::Config, XSPDIF_CONTROL_REGISTER_OFFSET, XSPDIF_CORE_ENABLE_MASK, XSpdif_ReadReg, XSpdif_WriteReg.
void XSpdif_SetClkConfig(XSpdif *InstancePtr, u8 Clk_DivNum)
This function sets the clock configuration bits.
InstancePtr is a pointer to the Spdif instance. Clk_DivNum is the clock division number. Clk_DivNum value can be only 4,8,16,24,32,48,or 64.
References XSpdif_Config::BaseAddress, XSpdif::Config, XSPDIF_CLK_16, XSPDIF_CLK_24, XSPDIF_CLK_32, XSPDIF_CLK_4, XSPDIF_CLK_48, XSPDIF_CLK_64, XSPDIF_CLK_8, XSPDIF_CLOCK_CONFIG_BITS_MASK, XSPDIF_CLOCK_CONFIG_BITS_SHIFT, XSPDIF_CONTROL_REGISTER_OFFSET, XSpdif_ReadReg, XSpdif_WriteReg.
u32 XSpdif_GetFs(XSpdif *InstancePtr, u32 AudClk)
This function calculates the Sampling Frequency (Fs) and returns it's value.
InstancePtr is a pointer to the XSpdif instance. AudClk is the audio clock frequency value in Hz. - Returns the sampling frequency value in Hz.
References XSpdif_Config::BaseAddress, XSpdif::Config, XSpdif_ReadReg, XSPDIF_SAMPLE_CLOCK_COUNT_MASK, XSPDIF_STATUS_REGISTER_OFFSET.
void XSpdif_Rx_GetChStat(XSpdif *InstancePtr, u8 *ChStatBuf)
This function reads all the Channel Status registers and writes to a buffer.
InstancePtr is a pointer to the XSpdif instance. ChStatBuf is a pointer to a buffer.
References XSpdif_Config::BaseAddress, XSpdif::Config, XSPDIF_CHANNEL_STATUS_REGISTER0_OFFSET, XSpdif_ReadReg.
void XSpdif_Rx_GetChA_UserData(XSpdif *InstancePtr, u8 *ChA_UserDataBuf)
This function reads the Channel A user data and writes to a buffer.
InstancePtr is a pointer to the XSPDIF instance. ChA_UserDataBuf is a pointer to a buffer.
References XSpdif_Config::BaseAddress, XSpdif::Config, XSPDIF_CHANNEL_A_USER_DATA_REGISTER0_OFFSET, XSpdif_ReadReg.
void XSpdif_Rx_GetChB_UserData(XSpdif *InstancePtr, u8 *ChB_UserDataBuf)
This function reads the Channel B user data and writes to a buffer.
InstancePtr is a pointer to the XSPDIF instance. ChB_UserDataBuf is a pointer to a buffer.
References XSpdif_Config::BaseAddress, XSpdif::Config, XSPDIF_CHANNEL_B_USER_DATA_REGISTER0_OFFSET, XSpdif_ReadReg.