oslayer.h
_OSLAYER_STATUS
typedef enum _OSLAYER_STATUS OSLAYER_STATUS
Status codes of OS Abstraction Layer operation.
typedef struct _osFile osFile
File object of OS Abstraction Layer.
void* osMalloc(uint32_t size)
Allocate a continuous block of memory.
size Size of memory block to be allocated
References osMemPoolPrintStats.
Referenced by IsiSensorDrvHandleRegisterIss, osFopen, osFread, osMemPoolVerify, VsiCamDeviceSensorMapping.
int32_t osFree(void *p)
Free a continuous block of memory.
p Pointer to previously allocated memory block always OSLAYER_OK
Referenced by fifo_buffer_free, IsiSensorDrvHandleRegisterIss, IsiSensorDrvHandleUnRegisterIss, osFclose, osFopen, osFread, osMemPoolVerify.
int32_t osMemPoolVerify(void)
Verify memory pool initialization and perform basic tests.
OSLAYER_OK on success, OSLAYER_ERROR on failure
References osFree, osMalloc, osMemPoolPrintStats.
int32_t osMemPoolGetStats(uint32_t *pUsedBlocks, uint32_t *pFreeBlocks, uint32_t *pTotalMemory, uint32_t *pUsedMemory)
Get memory pool statistics.
pUsedBlocks Pointer to store number of used blocks pFreeBlocks Pointer to store number of free blocks pTotalMemory Pointer to store total memory size pUsedMemory Pointer to store used memory size OSLAYER_OK on success
Referenced by osMemPoolPrintStats.
int32_t osMemPoolPrintStats(void)
Print memory pool statistics (debug function)
OSLAYER_OK on success
References osMemPoolGetStats.
Referenced by osMalloc, osMemPoolVerify.
int32_t osSleep(uint32_t msec)
osFile* osFopen(const char *filename, const char *mode)
Opens a file using the specified filename and mode.
This function allocates and initializes an osFile structure, opens the file with the given filename and mode, and associates the resulting FILE/FIL* with the osFile structure. filename The name of the file to be opened. mode The mode in which the file is to be opened (e.g., "r", "w"). A pointer to the opened osFile structure, or NULL if an error occurred during file opening or memory allocation.
References osFree, osMalloc.
void osFclose(osFile *pVsiFile)
Closes the file associated with the given osFile structure.
This function closes the file associated with the given osFile structure, frees the allocated memory for the structure, and performs necessary cleanup. file A pointer to the osFile structure representing the file.
References osFree.
size_t osFread(void *ptr, size_t size, size_t count, osFile *pVsiFile)
Read data from a file into a specified buffer.
This function reads data from a file associated with the given osFile structure into the specified buffer. ptr Pointer to the buffer where the read data will be stored. size Size of each data item to be read (in bytes). count Number of data items to read. file Pointer to the osFile structure representing the file. Number of data items actually read. If the return value is less than count, it may indicate reaching the end of the file or encountering an error.
References osFree, osMalloc.
size_t osFwrite(const void *ptr, size_t size, size_t count, osFile *pVsiFile)
Write data from a specified buffer to a file.
This function writes data from the specified buffer into the file associated with the given osFile structure. ptr Pointer to the buffer containing the data to be written to the file. size Size of each data item to be written (in bytes). count Number of data items to write. file Pointer to the osFile structure representing the file. Number of data items actually written to the file. If the return value is less than count, it may indicate disk full or encountering an error.
int osFseek(osFile *pVsiFile, long int offset, int origin)
Set the file position indicator for the specified file.
This function sets the file position indicator for the file associated with the given osFile structure. The new position is determined by adding offset bytes to the position specified by origin. file Pointer to the osFile structure representing the file. offset Number of bytes to offset from origin. origin Position from where offset is added (SEEK_SET, SEEK_CUR, SEEK_END). 0 if successful, non-zero on error.
long int osFtell(osFile *pVsiFile)
Get the current file position indicator for the specified file.
This function gets the current file position indicator for the file associated with the given osFile structure. file Pointer to the osFile structure representing the file. Current file position indicator if successful, -1 on error.
long int osFileSize(osFile *pVsiFile)
Get the size of the file associated with the specified osFile structure.
This function returns the size of the file associated with the given osFile structure. file Pointer to the osFile structure representing the file. Size of the file if successful, -1 on error.
int osFeof(osFile *pVsiFile)
Check if the end-of-file indicator is set for the specified file.
This function checks whether the end-of-file indicator is set for the file associated with the given osFile structure. file Pointer to the osFile structure representing the file. Non-zero value if the end-of-file indicator is set, 0 otherwise.
Referenced by osFgetc.
int osFerror(osFile *pVsiFile)
Check if an error indicator is set for the specified file.
This function checks whether an error indicator is set for the file associated with the given osFile structure. file Pointer to the osFile structure representing the file. Non-zero value if an error indicator is set, 0 otherwise.
int osFgetc(osFile *pVsiFile)
Read a character from the specified file.
This function reads a character from the file associated with the given osFile structure. It returns when either a character is read, the end-of-file is reached, or an error occurs, whichever comes first. file Pointer to the osFile structure representing the file. Integer of the read character on success, -1 on failure or end-of-file.
References osFeof.
char* osFgets(char *str, int size, osFile *pVsiFile)
Read a line from the specified file into the specified buffer.
This function reads a line from the file associated with the given osFile structure into the specified buffer. It stops when either (n-1) characters are read, the newline character is encountered, or the end-of-file is reached, whichever comes first. The newline character, if encountered, is included in the buffer. str Pointer to the buffer where the line will be stored. size Maximum number of characters to be read (including the null terminator). file Pointer to the osFile structure representing the file. Pointer to the read line on success, NULL on failure or end-of-file.
int osFputs(const char *str, osFile *file)
Read a line from the specified file into the specified buffer.
This function writes a string to the file associated with the given osFile structure str Pointer to the string which will be written into the file. file Pointer to the osFile structure representing the file. 0 if successful, non-zero on error.
int osFscanf(osFile *pVsiFile, const char *format,...)
Read formatted data from the specified file.
This function reads formatted data from the file associated with the given osFile structure, under the control of the format string format. The variable arguments must correspond to the placeholders in the format string. file Pointer to the osFile structure representing the file. format Format string that specifies the expected format of the input. ... Variable arguments corresponding to the placeholders in the format string. Number of input items successfully matched and assigned, or EOF if an error occurs.
int osFprintf(osFile *pVsiFile, const char *format,...)
Write formatted data to the specified file.
This function writes formatted data to the file associated with the given osFile structure, under the control of the format string format. The variable arguments must correspond to the placeholders in the format string. file Pointer to the osFile structure representing the file. format Format string that specifies the expected format of the output. ... Variable arguments corresponding to the placeholders in the format string. Number of characters written, or a negative value if an error occurs.
void osUSleep(unsigned int microseconds)
Sleeps the program for the specified number of microseconds.
This function is used to make the program sleep for the specified number of microseconds. microseconds The number of microseconds to sleep.
int32_t osTimeStampUs(int64_t *pTimeStamp)
Returns a 64-bit timestamp [us].
pTimeStamp Reference of the timestamp object Status of operation OSLAYER_OK Event successfully created
int32_t osTimeStampNs(float32_t *pTimeStamp)
Returns a 64-bit timestamp [ns].
pTimeStamp Reference of the timestamp object Status of operation OSLAYER_OK Event successfully created