mipi_rx_phy
XMIPI_RX_PHY_MODE_MIN
Lower limit for Mode.
XMIPI_RX_PHY_LOW_POWER_MODE
Lane in Low Power Mode.
XMIPI_RX_PHY_HIGH_POWER_MODE
Lane in High Power Mode.
XMIPI_RX_PHY_ESCAPE_MODE
Lane in Escape Mode.
XMIPI_RX_PHY_MODE_MAX
Upper Limit for mode.
XMIPI_RX_PHY_MAX_LANES_V10
V1.0 supports 4 Lanes.
XMIPI_RX_PHY_HANDLE_MIN
Lower Bound for XMIPI_RX_PHY_HANDLE.
XMIPI_RX_PHY_HANDLE_IDELAY
Handle for IDELAY Reg.
XMIPI_RX_PHY_HANDLE_INIT_TIMER
Handle for Initialization Timer.
Referenced by XMipi_Rx_Phy_Configure, XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_HANDLE_WAKEUP
Handle for Wakeup timer.
XMIPI_RX_PHY_HANDLE_HSTIMEOUT
Handle for HS Timeout.
Referenced by XMipi_Rx_Phy_Configure, XMipi_Rx_Phy_GetInfo, XMipi_Rx_Phy_SelfTest.
XMIPI_RX_PHY_HANDLE_ESCTIMEOUT
Handle for Escape Timeout.
Referenced by XMipi_Rx_Phy_Configure, XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_HANDLE_CLKLANE
Handle for Clock Lane.
Referenced by XMipi_Rx_Phy_Configure, XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_HANDLE_DLANE0
Handle for Data Lane 0.
Referenced by XMipi_Rx_Phy_Configure, XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_HANDLE_DLANE1
Handle for Data Lane 1.
Referenced by XMipi_Rx_Phy_Configure, XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_HANDLE_DLANE2
Handle for Data Lane 2.
Referenced by XMipi_Rx_Phy_Configure, XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_HANDLE_DLANE3
Handle for Data Lane 3.
Referenced by XMipi_Rx_Phy_Configure, XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_HANDLE_HSSETTLE0
Handle for HS SETTLE L0.
Referenced by XMipi_Rx_Phy_Configure, XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_HANDLE_HSSETTLE1
Handle for HS SETTLE L1.
Referenced by XMipi_Rx_Phy_Configure, XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_HANDLE_HSSETTLE2
Handle for HS SETTLE L2.
Referenced by XMipi_Rx_Phy_Configure, XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_HANDLE_HSSETTLE3
Handle for HS SETTLE L3.
Referenced by XMipi_Rx_Phy_Configure, XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_HANDLE_MAX
Upper Bound for XMIPI_RX_PHY_HANDLE.
Referenced by XMipi_Rx_Phy_Configure, XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_LINERATE_MIN
Minimum line rate in Mbps.
Referenced by XMipi_Rx_Phy_DynamicLineRateConfig.
XMIPI_RX_PHY_LINERATE_MAX
Maximum line rate in Mbps.
Referenced by XMipi_Rx_Phy_DynamicLineRateConfig.
XMIPI_RX_PHY_HS_TIMEOUT_MIN_VALUE
Min HS timeout value.
Referenced by XMipi_Rx_Phy_Configure.
XMIPI_RX_PHY_HS_TIMEOUT_MAX_VALUE
Max HS timeout value.
Referenced by XMipi_Rx_Phy_Configure.
XMIPI_RX_PHY_HS_SETTLE_MAX_VALUE
Max HS settle value.
Referenced by XMipi_Rx_Phy_Configure.
XMIPI_RX_PHY_ENABLE_FLAG
Flag to enable core.
Referenced by XMipi_Rx_Phy_Activate, XMipi_Rx_Phy_DynamicLineRateConfig.
XMIPI_RX_PHY_DISABLE_FLAG
Flag to disable core.
Referenced by XMipi_Rx_Phy_Activate, XMipi_Rx_Phy_DynamicLineRateConfig.
XMIPI_RX_PHY_CTRL_REG_OFFSET
Control Register.
Referenced by XMipi_Rx_Phy_Activate, XMipi_Rx_Phy_Reset.
XMIPI_RX_PHY_VERSION_REG_OFFSET
Core Version Register.
Referenced by XMipi_Rx_Phy_GetVersionReg.
XMIPI_RX_PHY_INIT_TIMER_REG_OFFSET
Initialization Timer Register.
Referenced by XMipi_Rx_Phy_Configure, XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_HSTIMEOUT_REG_OFFSET
Watchdog timeout in HS mode Register.
Referenced by XMipi_Rx_Phy_Configure, XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_ESCTIMEOUT_REG_OFFSET
Goto Stop state on timeout timer Register.
Referenced by XMipi_Rx_Phy_Configure, XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_CLSTATUS_REG_OFFSET
Clk lane PHY error Status Register.
Referenced by XMipi_Rx_Phy_GetClkLaneStatus, XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_DL0STATUS_REG_OFFSET
Data lane 0 PHY error Status Register.
Referenced by XMipi_Rx_Phy_ClearDataLane, XMipi_Rx_Phy_GetDataLaneStatus, XMipi_Rx_Phy_GetDLCalibStatus, XMipi_Rx_Phy_GetInfo, XMipi_Rx_Phy_GetPacketCount.
XMIPI_RX_PHY_DL1STATUS_REG_OFFSET
Data lane 1 PHY error Status Register.
Referenced by XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_DL2STATUS_REG_OFFSET
Data lane 2 PHY error Status Register.
Referenced by XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_DL3STATUS_REG_OFFSET
Data lane 3 PHY error Status Register.
Referenced by XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_DYNAMIC_LINERATE_REG_OFFSET
Dynamic Line Rate Register.
XMIPI_RX_PHY_HSSETTLE0_REG_OFFSET
HS Settle Register L0.
Referenced by XMipi_Rx_Phy_Configure, XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_MMCM_MULT_REG_OFFSET
MMCM Multiplier Register.
XMIPI_RX_PHY_MMCM_FRACT_MULT_REG_OFFSET
MMCM Fractional Multiplier Register.
XMIPI_RX_PHY_MMCM_DIV_REG_OFFSET
MMCM Divider Register.
XMIPI_RX_PHY_MMCM_O_REG_OFFSET
MMCM Output Divider Register.
XMIPI_RX_PHY_HSSETTLE1_REG_OFFSET
HS Settle Register L1.
Referenced by XMipi_Rx_Phy_Configure, XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_HSSETTLE2_REG_OFFSET
HS Settle Register L2.
Referenced by XMipi_Rx_Phy_Configure, XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_HSSETTLE3_REG_OFFSET
HS Settle Register L3.
Referenced by XMipi_Rx_Phy_Configure, XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_DYNAMIC_LINERATE_REG_LINERATE_MASK
Current Line Rate.
XMIPI_RX_PHY_CTRL_REG_SOFTRESET_MASK
Soft Reset.
Referenced by XMipi_Rx_Phy_Reset.
XMIPI_RX_PHY_CTRL_REG_PHYEN_MASK
Enable/Disable controller.
Referenced by XMipi_Rx_Phy_Activate.
XMIPI_RX_PHY_CTRL_REG_SOFTRESET_OFFSET
Bit offset for Soft Reset.
XMIPI_RX_PHY_CTRL_REG_PHYEN_OFFSET
Bit offset for PHY Enable.
XMIPI_RX_PHY_INIT_REG_VAL_MASK
Init Timer value in ns.
XMIPI_RX_PHY_INIT_REG_VAL_OFFSET
Bit offset for Init Timer.
XMIPI_RX_PHY_HSTIMEOUT_REG_TIMEOUT_MASK
HS_RX_TIMEOUT Received.
XMIPI_RX_PHY_HSTIMEOUT_REG_TIMEOUT_OFFSET
Bit offset for Timeout.
XMIPI_RX_PHY_ESCTIMEOUT_REG_VAL_MASK
Escape Timeout Value.
XMIPI_RX_PHY_ESCTIMEOUT_REG_VAL_OFFSET
Bit offset for Escape Timeout.
XMIPI_RX_PHY_CLSTATUS_REG_ERRCTRL_MASK
Clock lane control error.
Only for RX
XMIPI_RX_PHY_CLSTATUS_REG_STOPSTATE_MASK
Clock lane stop state.
XMIPI_RX_PHY_CLSTATUS_REG_INITDONE_MASK
Initialization done bit.
XMIPI_RX_PHY_CLSTATUS_REG_ULPS_MASK
Set in ULPS mode.
XMIPI_RX_PHY_CLSTATUS_REG_MODE_MASK
Low, High, Esc mode.
Referenced by XMipi_Rx_Phy_GetClkLaneMode.
XMIPI_RX_PHY_CLSTATUS_ALLMASK
All clock lane status mask.
XMIPI_RX_PHY_CLSTATUS_REG_ERRCTRL_OFFSET
Bit offset for Control Error on Clock.
XMIPI_RX_PHY_CLSTATUS_REG_STOPSTATE_OFFSET
Bit offset for Stop State on Clock.
XMIPI_RX_PHY_CLSTATUS_REG_INITDONE_OFFSET
Bit offset for Initialization Done.
XMIPI_RX_PHY_CLSTATUS_REG_ULPS_OFFSET
Bit offset for ULPS.
XMIPI_RX_PHY_CLSTATUS_REG_MODE_OFFSET
Bit offset for Mode bits.
XMIPI_RX_PHY_DLXSTATUS_REG_PACKETCOUNT_MASK
Packet Count.
Referenced by XMipi_Rx_Phy_GetPacketCount.
XMIPI_RX_PHY_DLXSTATUS_REG_CALIB_STATUS_MASK
Calib status.
Referenced by XMipi_Rx_Phy_GetDLCalibStatus.
XMIPI_RX_PHY_DLXSTATUS_REG_CALIB_COMPLETE_MASK
Calib complete.
Referenced by XMipi_Rx_Phy_GetDLCalibStatus.
XMIPI_RX_PHY_DLXSTATUS_REG_STOP_MASK
Stop State on data lane.
XMIPI_RX_PHY_DLXSTATUS_REG_ESCABRT_MASK
Set on Data Lane Esc timeout occurs.
Referenced by XMipi_Rx_Phy_ClearDataLane.
XMIPI_RX_PHY_DLXSTATUS_REG_HSABRT_MASK
Set on Data Lane HS timeout.
Referenced by XMipi_Rx_Phy_ClearDataLane.
XMIPI_RX_PHY_DLXSTATUS_REG_INITDONE_MASK
Set after initialization.
XMIPI_RX_PHY_DLXSTATUS_REG_ULPS_MASK
Set when MIPI_RX_PHY in ULPS mode.
XMIPI_RX_PHY_DLXSTATUS_REG_MODE_MASK
Control Mode (Esc, Low, High) of Data Lane.
Referenced by XMipi_Rx_Phy_GetDataLaneMode.
XMIPI_RX_PHY_DLXSTATUS_ALLMASK
All data lane status mask.
XMIPI_RX_PHY_DLXSTATUS_REG_PACKCOUNT_OFFSET
Bit offset packet count.
Referenced by XMipi_Rx_Phy_GetPacketCount.
XMIPI_RX_PHY_DLXSTATUS_REG_CALIB_STATUS_OFFSET
Bit offset calib status.
XMIPI_RX_PHY_DLXSTATUS_REG_CALIB_COMPLETE_OFFSET
Bit offset Calib complete.
XMIPI_RX_PHY_DLXSTATUS_REG_STOP_OFFSET
Bit offset for Stop State.
XMIPI_RX_PHY_DLXSTATUS_REG_ESCABRT_OFFSET
Bit offset for Escape Abort.
XMIPI_RX_PHY_DLXSTATUS_REG_HSABRT_OFFSET
Bit offset for High Speed Abort.
XMIPI_RX_PHY_DLXSTATUS_REG_INITDONE_OFFSET
Bit offset for Initialization done.
XMIPI_RX_PHY_DLXSTATUS_REG_ULPS_OFFSET
Bit offset for ULPS.
XMIPI_RX_PHY_DLXSTATUS_REG_MODE_OFFSET
Bit offset for Modes.
XMIPI_RX_PHY_HSSETTLE_REG_TIMEOUT_MASK
HS_SETTLE value.
XMIPI_RX_PHY_HSSETTLE_REG_TIMEOUT_OFFSET
Bit offset for HS_SETTLE.
XMIPI_RX_PHY_MMCM_FIN_MHZ
Input clock frequency in MHz.
XMIPI_RX_PHY_MMCM_D_FIXED
Fixed input divider.
XMIPI_RX_PHY_MMCM_VCO_MIN_MHZ
Minimum VCO frequency in MHz.
XMIPI_RX_PHY_MMCM_VCO_MAX_MHZ
Maximum VCO frequency in MHz.
XMIPI_RX_PHY_MMCM_O_MIN
Minimum output divider.
XMIPI_RX_PHY_MMCM_O_MAX
Maximum output divider.
XMIPI_RX_PHY_MMCM_M_MIN
Minimum multiplier.
XMIPI_RX_PHY_MMCM_M_MAX
Maximum multiplier.
XMIPI_RX_PHY_MMCM_FRAC_RESOLUTION
Fractional M resolution (1/64 steps)
XMIPI_RX_PHY_MMCM_VCO_MID_MHZ
VCO mid-band target for tie-break.
XMIPI_RX_PHY_LINERATE_RANGE1_MIN
Range 1 minimum (K=4)
XMIPI_RX_PHY_LINERATE_RANGE1_MAX
Range 1 maximum (K=4)
XMIPI_RX_PHY_LINERATE_RANGE2_MIN
Range 2 minimum (K=8)
XMIPI_RX_PHY_LINERATE_RANGE2_MAX
Range 2 maximum (K=8)
XMIPI_RX_PHY_LINERATE_RANGE3_MIN
Range 3 minimum (K=11)
XMIPI_RX_PHY_LINERATE_RANGE3_MAX
Range 3 maximum (K=11)
XMIPI_RX_PHY_LINERATE_RANGE4_MIN
Range 4 minimum (K=16)
XMIPI_RX_PHY_LINERATE_RANGE4_MAX
Range 4 maximum (K=16)
XMIPI_RX_PHY_LINERATE_RANGE5_MIN
Range 5 minimum (K=22)
XMIPI_RX_PHY_LINERATE_RANGE5_MAX
Range 5 maximum (K=22)
XMIPI_RX_PHY_K_FACTOR_RANGE1
K factor for 400-1080 Mbps.
XMIPI_RX_PHY_K_FACTOR_RANGE2
K factor for 1081-2160 Mbps.
XMIPI_RX_PHY_K_FACTOR_RANGE3
K factor for 2161-2250 Mbps.
XMIPI_RX_PHY_K_FACTOR_RANGE4
K factor for 2251-4320 Mbps.
XMIPI_RX_PHY_K_FACTOR_RANGE5
K factor for 4321-4500 Mbps.
XMIPI_RX_PHY_CLKOUT_EVEN_NO_EDGE
CLKOUT0 Reg1: even divide, no edge.
XMIPI_RX_PHY_CLKOUT_EVEN_EDGE
CLKOUT0 Reg1: even divide, edge bit set.
XMIPI_RX_PHY_CLKOUT_ODD_NO_EDGE
CLKOUT0 Reg1: odd divide, no edge.
XMIPI_RX_PHY_CLKOUT_ODD_EDGE
CLKOUT0 Reg1: odd divide, edge bit set.
XMIPI_RX_PHY_MMCM_MULT_ODD_FLAG
MULT Reg1 for odd M_int.
XMIPI_RX_PHY_MMCM_MULT_EVEN_FLAG
MULT Reg1 for even M_int.
XMIPI_RX_PHY_MMCM_FRAC_ENABLE
Fractional M enable bit.
XMIPI_RX_PHY_MMCM_FRAC_MASK
Fractional M value mask (6 bits)
XMIPI_RX_PHY_MMCM_DIV_D5_REG1
DIV Reg1 encoding for D=5.
XMIPI_RX_PHY_MMCM_DIV_D5_HTLT_VAL
DIV Reg2 HT/LT value for D=5.
XMIPI_RX_PHY_HTLT_HIGH_SHIFT
High-time bit shift.
XMIPI_RX_PHY_HTLT_BYTE_MASK
Byte mask for HT/LT fields.
XMIPI_RX_PHY_SCORE_PPM_WEIGHT
PPM error weight in score.
XMIPI_RX_PHY_SCORE_O_WEIGHT
Output divider weight in score.
XMIPI_RX_PHY_SCORE_FRAC_PENALTY
Penalty for fractional M in score.
XMIPI_RX_PHY_PPM_SCALE
PPM scale factor.
XMIPI_RX_PHY_SCORE_INIT
Initial best score (very large)
XMIPI_RX_PHY_ABS
Absolute value of x.
XMIPI_RX_PHY_ROUND_S32
Round double to nearest s32 integer.
XMIPI_RX_PHY_ROUND_DBL
Round double to nearest integer returned as double.
XMIPI_RX_PHY_FLOOR
Floor of x returned as double.
XPLL_REG_PCSR_MASK_OFFSET
PLL PCSR Mask Register.
XPLL_REG_PCSR_CONTROL_OFFSET
PLL PCSR Control Register.
XPLL_REG_PCSR_LOCK_OFFSET
PLL PCSR Lock Register.
XPLL_REG_2_M_OFFSET
PLL Config Register 2.
XPLL_REG_3_M_OFFSET
PLL Config Register 3.
XPLL_REG_4_O1_OFFSET
PLL Output 1 Config Register 4.
XPLL_REG_5_O1_OFFSET
PLL Output 1 Config Register 5.
XPLL_REG_6_O0_OFFSET
PLL Output 0 Config Register 6.
XPLL_REG_7_O0_OFFSET
PLL Output 0 Config Register 7.
XPLL_REG_22_D_OFFSET
PLL Divider Config Register 22.
XPLL_REG_23_D_OFFSET
PLL Divider Config Register 23.
XMIPI_RX_PHY_PLL_UNLOCK_VAL
PLL Unlock Value.
XMIPI_RX_PHY_PLL_LOCK_VAL
PLL Lock Value.
XMIPI_RX_PHY_PLL_MASK_VAL
PLL Mask Value (APB + FABRIC_EN)
XMIPI_RX_PHY_PLL_CONTROL_CONFIG_VAL
PLL Control Config Value.
XMIPI_RX_PHY_PLL_CONTROL_LOCK_VAL
PLL Control Lock Value.
XMIPI_RX_PHY_PLL_EN_ODISABLE_VAL
PLL Enable Output Disable Value.
XMIPI_RX_PHY_PLL_DIS_ODISABLE
PLL Disable Output Disable Value.
XMIPI_RX_PHY_PLL_EN_INITSTATE_VAL
PLL Enable Init State Value.
XMIPI_RX_PHY_PLL_DIS_INITSTATE
PLL Disable Init State Value.
XMIPI_RX_PHY_LINERATE_NUM_BUCKETS
Number of line rate buckets.
const u32 XMipi_Rx_Phy_PllRegOffsets[XMIPI_RX_PHY_PLL_NUM_REGS][XMIPI_RX_PHY_PLL_NUM_REGS]
PLL register index to offset mapping (used in programming loop):
const XMipi_Rx_Phy_Dynamic_LineRate XMipi_Rx_Phy_Dynamic_LineRateCfg[XMIPI_RX_PHY_LINERATE_NUM_BUCKETS][XMIPI_RX_PHY_LINERATE_NUM_BUCKETS]
Line rate bucket look-up table.
PllVals order: REG_2_M, REG_3_M, REG_4_O1, REG_5_O1, REG_6_O0, REG_7_O0, REG_22_D, REG_23_D
u32 XMipi_Rx_Phy_CfgInitialize(XMipi_Rx_Phy *InstancePtr, XMipi_Rx_Phy_Config *CfgPtr, UINTPTR EffectiveAddr)
Initialize the XMipi_Rx_Phy instance provided by the caller based on the given Config structure.
InstancePtr is the XMipi_Rx_Phy instance to operate on. CfgPtr is the device configuration structure containing information about a specific Mipi_Rx_Phy instance. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS Initialization was successful. None.
References XMipi_Rx_Phy_Config::BaseAddr, XMipi_Rx_Phy::Config, XMipi_Rx_Phy::IsReady.
Referenced by Mipi_Rx_PhySelfTestExample.
u32 XMipi_Rx_Phy_Configure(XMipi_Rx_Phy *InstancePtr, u8 Handle, u32 Value)
Configure the registers of the Mipi_Rx_Phy instance.
InstancePtr is the XMipi_Rx_Phy instance to operate on. Handle to one of the registers to be configured Value to be set for the particular Handle of the Mipi_Rx_Phy instance XST_SUCCESS on successful register update.XST_FAILURE If incorrect handle was passed There is a limit on the minimum and maximum values of the HS Timeout register.
References XMipi_Rx_Phy::Config, XMipi_Rx_Phy_Config::EnableTimeOutRegs, XMipi_Rx_Phy_Config::IsDphy, XMipi_Rx_Phy_Config::IsRegisterPresent, XMIPI_RX_PHY_ESCTIMEOUT_REG_OFFSET, XMIPI_RX_PHY_HANDLE_CLKLANE, XMIPI_RX_PHY_HANDLE_DLANE0, XMIPI_RX_PHY_HANDLE_DLANE1, XMIPI_RX_PHY_HANDLE_DLANE2, XMIPI_RX_PHY_HANDLE_DLANE3, XMIPI_RX_PHY_HANDLE_ESCTIMEOUT, XMIPI_RX_PHY_HANDLE_HSSETTLE0, XMIPI_RX_PHY_HANDLE_HSSETTLE1, XMIPI_RX_PHY_HANDLE_HSSETTLE2, XMIPI_RX_PHY_HANDLE_HSSETTLE3, XMIPI_RX_PHY_HANDLE_HSTIMEOUT, XMIPI_RX_PHY_HANDLE_INIT_TIMER, XMIPI_RX_PHY_HANDLE_MAX, XMIPI_RX_PHY_HS_SETTLE_MAX_VALUE, XMIPI_RX_PHY_HS_TIMEOUT_MAX_VALUE, XMIPI_RX_PHY_HS_TIMEOUT_MIN_VALUE, XMIPI_RX_PHY_HSSETTLE0_REG_OFFSET, XMIPI_RX_PHY_HSSETTLE1_REG_OFFSET, XMIPI_RX_PHY_HSSETTLE2_REG_OFFSET, XMIPI_RX_PHY_HSSETTLE3_REG_OFFSET, XMIPI_RX_PHY_HSTIMEOUT_REG_OFFSET, XMIPI_RX_PHY_INIT_TIMER_REG_OFFSET.
u8 XMipi_Rx_Phy_GetRegIntfcPresent(XMipi_Rx_Phy *InstancePtr)
Get if register interface is present from the config structure for specified Mipi_Rx_Phy instance.
InstancePtr is the XMipi_Rx_Phy instance to operate on. 1 if register interface is present0 if register interface is absent None.
References XMipi_Rx_Phy::Config, XMipi_Rx_Phy_Config::IsRegisterPresent.
Referenced by Mipi_Rx_PhySelfTestExample.
u32 XMipi_Rx_Phy_GetInfo(XMipi_Rx_Phy *InstancePtr, u8 Handle)
Get information stored in the Mipi_Rx_Phy instance based on the handle passed.
InstancePtr is the XMipi_Rx_Phy instance to operate on. Handle to one of the registers to be configured The value stored in the corresponding register None.
References XMipi_Rx_Phy::Config, XMipi_Rx_Phy_Config::EnableTimeOutRegs, XMipi_Rx_Phy_Config::EscTimeout, XMipi_Rx_Phy_Config::HSTimeOut, XMipi_Rx_Phy_Config::IsDphy, XMipi_Rx_Phy_Config::IsRegisterPresent, XMIPI_RX_PHY_CLSTATUS_REG_OFFSET, XMIPI_RX_PHY_DL0STATUS_REG_OFFSET, XMIPI_RX_PHY_DL1STATUS_REG_OFFSET, XMIPI_RX_PHY_DL2STATUS_REG_OFFSET, XMIPI_RX_PHY_DL3STATUS_REG_OFFSET, XMIPI_RX_PHY_ESCTIMEOUT_REG_OFFSET, XMIPI_RX_PHY_HANDLE_CLKLANE, XMIPI_RX_PHY_HANDLE_DLANE0, XMIPI_RX_PHY_HANDLE_DLANE1, XMIPI_RX_PHY_HANDLE_DLANE2, XMIPI_RX_PHY_HANDLE_DLANE3, XMIPI_RX_PHY_HANDLE_ESCTIMEOUT, XMIPI_RX_PHY_HANDLE_HSSETTLE0, XMIPI_RX_PHY_HANDLE_HSSETTLE1, XMIPI_RX_PHY_HANDLE_HSSETTLE2, XMIPI_RX_PHY_HANDLE_HSSETTLE3, XMIPI_RX_PHY_HANDLE_HSTIMEOUT, XMIPI_RX_PHY_HANDLE_INIT_TIMER, XMIPI_RX_PHY_HANDLE_MAX, XMIPI_RX_PHY_HSSETTLE0_REG_OFFSET, XMIPI_RX_PHY_HSSETTLE1_REG_OFFSET, XMIPI_RX_PHY_HSSETTLE2_REG_OFFSET, XMIPI_RX_PHY_HSSETTLE3_REG_OFFSET, XMIPI_RX_PHY_HSTIMEOUT_REG_OFFSET, XMIPI_RX_PHY_INIT_TIMER_REG_OFFSET.
Referenced by XMipi_Rx_Phy_SelfTest.
void XMipi_Rx_Phy_Reset(XMipi_Rx_Phy *InstancePtr)
This is used to do a soft reset of the Mipi_Rx_Phy IP instance.
The reset takes approx 20 core clock cycles to become effective. InstancePtr is the XMipi_Rx_Phy instance to operate on. None None.
References XMipi_Rx_Phy::Config, XMipi_Rx_Phy::IsReady, XMipi_Rx_Phy_Config::IsRegisterPresent, XMIPI_RX_PHY_CTRL_REG_OFFSET, XMIPI_RX_PHY_CTRL_REG_SOFTRESET_MASK.
void XMipi_Rx_Phy_ClearDataLane(XMipi_Rx_Phy *InstancePtr, u8 DataLane, u32 Mask)
This is used to clear the Abort Error (Escape or High Speed) bits in the Data Lane 0 through 3.
InstancePtr is the XMipi_Rx_Phy instance to operate on. DataLane represents which Data Lane to act upon Mask contains information about which bits to reset None None.
References XMipi_Rx_Phy_Config::BaseAddr, XMipi_Rx_Phy::Config, XMipi_Rx_Phy_Config::IsRegisterPresent, XMIPI_RX_PHY_DL0STATUS_REG_OFFSET, XMIPI_RX_PHY_DLXSTATUS_REG_ESCABRT_MASK, XMIPI_RX_PHY_DLXSTATUS_REG_HSABRT_MASK.
u32 XMipi_Rx_Phy_GetClkLaneStatus(XMipi_Rx_Phy *InstancePtr)
This is used to get information about Clock Lane status.
InstancePtr is the XMipi_Rx_Phy instance to operate on. Bitmask containing which of the events have occurred along with the mode of the Clock Lane in Phy None.
References XMipi_Rx_Phy_Config::BaseAddr, XMipi_Rx_Phy::Config, XMipi_Rx_Phy_Config::IsDphy, XMipi_Rx_Phy_Config::IsRegisterPresent, XMIPI_RX_PHY_CLSTATUS_REG_OFFSET.
Referenced by XMipi_Rx_Phy_GetClkLaneMode.
u32 XMipi_Rx_Phy_GetClkLaneMode(XMipi_Rx_Phy *InstancePtr)
This is used to get specific Lane mode information about Clock Lane.
InstancePtr is the XMipi_Rx_Phy instance to operate on. Bitmask containing mode in which the Clock Lane in Mipi_Rx_Phy is in. None.
References XMipi_Rx_Phy::Config, XMipi_Rx_Phy_Config::IsDphy, XMipi_Rx_Phy_Config::IsRegisterPresent, XMIPI_RX_PHY_CLSTATUS_REG_MODE_MASK, XMipi_Rx_Phy_GetClkLaneStatus.
u32 XMipi_Rx_Phy_GetDataLaneStatus(XMipi_Rx_Phy *InstancePtr, u8 DataLane)
This is used to get information about a Data Lane status.
InstancePtr is the XMipi_Rx_Phy instance to operate on. DataLane for which the status is sought for. Bitmask containing which of the events have occurred along with the mode of the Data Lane in Phy None.
References XMipi_Rx_Phy_Config::BaseAddr, XMipi_Rx_Phy::Config, XMipi_Rx_Phy_Config::IsRegisterPresent, XMIPI_RX_PHY_DL0STATUS_REG_OFFSET.
Referenced by XMipi_Rx_Phy_GetDataLaneMode.
u8 XMipi_Rx_Phy_GetDLCalibStatus(XMipi_Rx_Phy *InstancePtr, u8 DataLane)
This is used to get Data Lane Calibration status.
InstancePtr is the XMipi_Rx_Phy instance to operate on. DataLane for which the calib status is sought for. XST_SUCCESS - Calibration Complete, Calibration packet received XST_NO_DATA - Calibration Complete, Calibration packet is not received XST_FAILURE - Calibration failed None.
References XMipi_Rx_Phy_Config::BaseAddr, XMipi_Rx_Phy::Config, DL_LANE_OFFSET, XMipi_Rx_Phy_Config::IsRegisterPresent, XMIPI_RX_PHY_DL0STATUS_REG_OFFSET, XMIPI_RX_PHY_DLXSTATUS_REG_CALIB_COMPLETE_MASK, XMIPI_RX_PHY_DLXSTATUS_REG_CALIB_STATUS_MASK.
u32 XMipi_Rx_Phy_GetDataLaneMode(XMipi_Rx_Phy *InstancePtr, u8 DataLane)
This is used to get specific Lane mode information about a Data Lane.
InstancePtr is the XMipi_Rx_Phy instance to operate on. DataLane for which the mode info is requested. Bitmask containing mode in which the Data Lane in Mipi_Rx_Phy is in. None.
References XMipi_Rx_Phy::Config, XMipi_Rx_Phy_Config::IsRegisterPresent, XMIPI_RX_PHY_DLXSTATUS_REG_MODE_MASK, XMipi_Rx_Phy_GetDataLaneStatus.
u16 XMipi_Rx_Phy_GetPacketCount(XMipi_Rx_Phy *InstancePtr, u8 DataLane)
This is used to get count of packets received on each lane.
InstancePtr is the XMipi_Rx_Phy instance to operate on. DataLane for which the mode info is requested. Bitmask containing mode in which the Data Lane in Mipi_Rx_Phy is in. None.
References XMipi_Rx_Phy_Config::BaseAddr, XMipi_Rx_Phy::Config, XMipi_Rx_Phy_Config::IsRegisterPresent, XMIPI_RX_PHY_DL0STATUS_REG_OFFSET, XMIPI_RX_PHY_DLXSTATUS_REG_PACKCOUNT_OFFSET, XMIPI_RX_PHY_DLXSTATUS_REG_PACKETCOUNT_MASK.
u32 XMipi_Rx_Phy_GetVersionReg(XMipi_Rx_Phy *InstancePtr)
This is used to get Mipi_Rx_Phy Version.
InstancePtr is the XMipi_Rx_Phy instance to operate on. Returns major and minor Version number of this Mipi_Rx_Phy IP None.
References XMipi_Rx_Phy_Config::BaseAddr, XMipi_Rx_Phy::Config, XMipi_Rx_Phy_Config::IsRegisterPresent, XMIPI_RX_PHY_VERSION_REG_OFFSET.
void XMipi_Rx_Phy_Activate(XMipi_Rx_Phy *InstancePtr, u8 Flag)
This function is used to enable or disable the Mipi_Rx_Phy core.
InstancePtr is the XMipi_Rx_Phy instance to operate on. Flag denoting whether to enable or disable the Mipi_Rx_Phy core None. None.
References XMipi_Rx_Phy_Config::BaseAddr, XMipi_Rx_Phy::Config, XMipi_Rx_Phy_Config::IsRegisterPresent, XMIPI_RX_PHY_CTRL_REG_OFFSET, XMIPI_RX_PHY_CTRL_REG_PHYEN_MASK, XMIPI_RX_PHY_DISABLE_FLAG, XMIPI_RX_PHY_ENABLE_FLAG.
Referenced by XMipi_Rx_Phy_DynamicLineRateConfig.
u32 XMipi_Rx_Phy_DynamicLineRateConfig(XMipi_Rx_Phy *InstancePtr, UINTPTR PllBaseAddr, u32 LineRate)
This function configures the dynamic line rate for the MIPI RX PHY by programming the MMCM registers and NPI X5PLL registers.
The driver disables the PHY, programs the MMCM via XMipi_Rx_Phy_MmcmConfig, delegates the PLL register programming to XMipi_Rx_Phy_XPllConfig, and re-enables the PHY. InstancePtr is the XMipi_Rx_Phy instance to operate on. PllBaseAddr is the base address of the X5PLL register space. LineRate is the desired line rate in Mbps (400-4500 Mbps). XST_SUCCESS if line rate configuration is successful.XST_FAILURE if the line rate is out of supported range or dynamic line rate is not enabled in hardware. The PHY is disabled before MMCM and PLL reprogramming and re-enabled after the sequence completes to ensure a clean transition.
References XMipi_Rx_Phy::Config, XMipi_Rx_Phy_Config::IsDphy, XMipi_Rx_Phy_Config::IsDynamicLineRate, XMipi_Rx_Phy_Activate, XMIPI_RX_PHY_DISABLE_FLAG, XMIPI_RX_PHY_ENABLE_FLAG, XMIPI_RX_PHY_LINERATE_MAX, XMIPI_RX_PHY_LINERATE_MIN, XMipi_Rx_Phy_MmcmConfig, XMipi_Rx_Phy_XPllConfig.
static void XMipi_Rx_Phy_BitSet(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask)
This inline function is used to set bit in a mipi_rx_phy register space.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitMask of bit field to be set None None
static void XMipi_Rx_Phy_BitReset(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask)
This inline function is used to reset bit in a mipi_rx_phy register space.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitMask of bit field to be reset None None
static u32 XMipi_Rx_Phy_GetBitField(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask, u32 BitShift)
This function is used to get the value of bitfield from mipi_rx_phy register space.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitMask of bit field whose value needs to be obtained BitShift is offset of bit field Bit Field Value in u32 format None
static void XMipi_Rx_Phy_SetBitField(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask, u32 BitShift, u32 Value)
This function is used to set the value of bitfield from mipi_rx_phy register space.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitMask of bit field whose value needs to be updated BitShift is offset of bit field Value to be set. Passed in u32 format. None None
XMipi_Rx_Phy_Config * XMipi_Rx_Phy_LookupConfig(UINTPTR BaseAddress)
Look up the hardware configuration for a device instance.
BaseAddress is the BaseAddress of the device to lookup for The reference to the configuration record in the configuration table (in xmipi_rx_phy_g.c) corresponding to the BaseAddr or if not found,a NULL pointer is returned. None
Referenced by Mipi_Rx_PhySelfTestExample.
u32 XMipi_Rx_Phy_XPllConfig(UINTPTR PllBaseAddr, u32 LineRate)
This function programs the X5PLL registers for a given line rate.
It looks up the matching bucket from the line rate table, then performs the PLL unlock -> configure -> re-lock sequence. PllBaseAddr is the base address of the X5PLL register space. LineRate is the desired line rate in Mbps (400-4500 Mbps). XST_SUCCESS if PLL programming is successful.XST_FAILURE if no matching line rate bucket is found. None.
Referenced by XMipi_Rx_Phy_DynamicLineRateConfig.
u32 XMipi_Rx_Phy_MmcmConfig(XMipi_Rx_Phy *InstancePtr, u32 LineRate)
This function configures the MMCM registers in the RX PHY for a given line rate.
It computes the optimal MMCM parameters (M, D, O) and writes the corresponding values to the PHY MMCM registers. InstancePtr is the XMipi_Rx_Phy instance to operate on. LineRate is the desired line rate in Mbps (400-4500 Mbps). XST_SUCCESS if MMCM programming is successful.XST_FAILURE if no valid MMCM solution is found. None.
Referenced by XMipi_Rx_Phy_DynamicLineRateConfig.
u32 XMipi_Rx_Phy_SelfTest(XMipi_Rx_Phy *InstancePtr)
Runs a self-test on the driver/device.
This test checks if HS Timeout value present in register matches the one from the generated file. InstancePtr is a pointer to the XMipi_Rx_Phy instance. XST_SUCCESS if self-test was successful XST_FAILURE if the read value was not equal to _g.c file None.
References XMipi_Rx_Phy::Config, XMipi_Rx_Phy_Config::HSTimeOut, XMipi_Rx_Phy_GetInfo, XMIPI_RX_PHY_HANDLE_HSTIMEOUT.
Referenced by Mipi_Rx_PhySelfTestExample.
static u32 XMipi_Rx_Phy_ReadReg(UINTPTR BaseAddress, u32 RegOffset)
This function reads a value from a MIPI_RX_PHY register space.
A 32 bit read is performed. If the component is implemented in a smaller width, only the least significant data is read from the register. The most significant data will be read as 0. BaseAddress is the base address of the XCsiSs core instance. RegOffset is the register offset of the register (defined at the top of this file). The 32-bit value of the register. None.
static void XMipi_Rx_Phy_WriteReg(UINTPTR BaseAddress, u32 RegOffset, u32 Data)
This function writes a value to a MIPI_RX_PHY register space A 32 bit write is performed.
If the component is implemented in a smaller width, only the least significant data is written. BaseAddress is the base address of the XCsiSs core instance. RegOffset is the register offset of the register (defined at the top of this file) to be written. Data is the 32-bit value to write into the register. None. None.
static u32 XMipi_Rx_Phy_MmcmDeriveK(u32 LineRate)
Derive the K factor from the line rate.
The K factor maps line rate ranges to a divider used to compute the target output frequency: Fout = LineRate / K. LineRate is the desired line rate in Mbps. K factor, or 0 if line rate is out of range. None.
static u16 XMipi_Rx_Phy_MmcmPackHtLt(u32 HighTime, u32 LowTime)
Pack high-time and low-time values into a 16-bit register value.
HighTime is the high-time count (bits [15:8]). LowTime is the low-time count (bits [7:0]). Packed 16-bit value. None.
static void XMipi_Rx_Phy_MmcmClkout0Regs(u32 OutputDivider, u16 *ClkoutReg1, u16 *ClkoutReg2)
Compute CLKOUT0 register values from the output divider.
OutputDivider is the integer output divider. ClkoutReg1 is a pointer to store the first register value. ClkoutReg2 is a pointer to store the second register value. None. OutputDivider is assumed to be integer only.
static XMipi_Rx_Phy_MmcmResult XMipi_Rx_Phy_MmcmCompute(u32 LineRate)
Compute the MMCM parameters and DRP writes for a given line rate.
LineRate is the desired line rate in Mbps. MmcmResult structure with Valid set if a solution was found. Uses double-precision floating point arithmetic matching the reference MMCM C-code algorithm.
static void XPll_WriteReg(UINTPTR BaseAddress, u32 RegOffset, u32 Data)
This function writes a value to a X5PLL register space.
A 32 bit write is performed. If the component is implemented in a smaller width, only the least significant data is written. BaseAddress is the base address of the X5PLL instance. RegOffset is the register offset of the register to be written. Data is the 32-bit value to write into the register. None. None.
XMIPI_RX_PHY_SOFTRESET_TIMEOUT
XMIPI_RX_PHY_H_
Prevent circular inclusions by using protection macros.
XMIPI_RX_PHY_HW_H_
Prevent circular inclusions by using protection macros.
DL_LANE_OFFSET
Data lane register offset spacing.
Referenced by XMipi_Rx_Phy_GetDLCalibStatus.
XMIPI_RX_PHY_PLL_NUM_REGS
Number of PLL registers programmed per bucket.