xmipi_rx_phy.h
XMIPI_RX_PHY_MODE_MIN
Lower limit for Mode.
XMIPI_RX_PHY_LOW_POWER_MODE
Lane in Low Power Mode.
XMIPI_RX_PHY_HIGH_POWER_MODE
Lane in High Power Mode.
XMIPI_RX_PHY_ESCAPE_MODE
Lane in Escape Mode.
XMIPI_RX_PHY_MODE_MAX
Upper Limit for mode.
XMIPI_RX_PHY_MAX_LANES_V10
V1.0 supports 4 Lanes.
XMIPI_RX_PHY_HANDLE_MIN
Lower Bound for XMIPI_RX_PHY_HANDLE.
XMIPI_RX_PHY_HANDLE_IDELAY
Handle for IDELAY Reg.
XMIPI_RX_PHY_HANDLE_INIT_TIMER
Handle for Initialization Timer.
Referenced by XMipi_Rx_Phy_Configure, XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_HANDLE_WAKEUP
Handle for Wakeup timer.
XMIPI_RX_PHY_HANDLE_HSTIMEOUT
Handle for HS Timeout.
Referenced by XMipi_Rx_Phy_Configure, XMipi_Rx_Phy_GetInfo, XMipi_Rx_Phy_SelfTest.
XMIPI_RX_PHY_HANDLE_ESCTIMEOUT
Handle for Escape Timeout.
Referenced by XMipi_Rx_Phy_Configure, XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_HANDLE_CLKLANE
Handle for Clock Lane.
Referenced by XMipi_Rx_Phy_Configure, XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_HANDLE_DLANE0
Handle for Data Lane 0.
Referenced by XMipi_Rx_Phy_Configure, XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_HANDLE_DLANE1
Handle for Data Lane 1.
Referenced by XMipi_Rx_Phy_Configure, XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_HANDLE_DLANE2
Handle for Data Lane 2.
Referenced by XMipi_Rx_Phy_Configure, XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_HANDLE_DLANE3
Handle for Data Lane 3.
Referenced by XMipi_Rx_Phy_Configure, XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_HANDLE_HSSETTLE0
Handle for HS SETTLE L0.
Referenced by XMipi_Rx_Phy_Configure, XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_HANDLE_HSSETTLE1
Handle for HS SETTLE L1.
Referenced by XMipi_Rx_Phy_Configure, XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_HANDLE_HSSETTLE2
Handle for HS SETTLE L2.
Referenced by XMipi_Rx_Phy_Configure, XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_HANDLE_HSSETTLE3
Handle for HS SETTLE L3.
Referenced by XMipi_Rx_Phy_Configure, XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_HANDLE_MAX
Upper Bound for XMIPI_RX_PHY_HANDLE.
Referenced by XMipi_Rx_Phy_Configure, XMipi_Rx_Phy_GetInfo.
XMIPI_RX_PHY_LINERATE_MIN
Minimum line rate in Mbps.
Referenced by XMipi_Rx_Phy_DynamicLineRateConfig.
XMIPI_RX_PHY_LINERATE_MAX
Maximum line rate in Mbps.
Referenced by XMipi_Rx_Phy_DynamicLineRateConfig.
XMIPI_RX_PHY_HS_TIMEOUT_MIN_VALUE
Min HS timeout value.
Referenced by XMipi_Rx_Phy_Configure.
XMIPI_RX_PHY_HS_TIMEOUT_MAX_VALUE
Max HS timeout value.
Referenced by XMipi_Rx_Phy_Configure.
XMIPI_RX_PHY_HS_SETTLE_MAX_VALUE
Max HS settle value.
Referenced by XMipi_Rx_Phy_Configure.
XMIPI_RX_PHY_ENABLE_FLAG
Flag to enable core.
Referenced by XMipi_Rx_Phy_Activate, XMipi_Rx_Phy_DynamicLineRateConfig.
XMIPI_RX_PHY_DISABLE_FLAG
Flag to disable core.
Referenced by XMipi_Rx_Phy_Activate, XMipi_Rx_Phy_DynamicLineRateConfig.
XMIPI_RX_PHY_H_
Prevent circular inclusions by using protection macros.
static void XMipi_Rx_Phy_BitSet(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask)
This inline function is used to set bit in a mipi_rx_phy register space.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitMask of bit field to be set None None
static void XMipi_Rx_Phy_BitReset(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask)
This inline function is used to reset bit in a mipi_rx_phy register space.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitMask of bit field to be reset None None
static u32 XMipi_Rx_Phy_GetBitField(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask, u32 BitShift)
This function is used to get the value of bitfield from mipi_rx_phy register space.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitMask of bit field whose value needs to be obtained BitShift is offset of bit field Bit Field Value in u32 format None
static void XMipi_Rx_Phy_SetBitField(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask, u32 BitShift, u32 Value)
This function is used to set the value of bitfield from mipi_rx_phy register space.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitMask of bit field whose value needs to be updated BitShift is offset of bit field Value to be set. Passed in u32 format. None None
XMipi_Rx_Phy_Config * XMipi_Rx_Phy_LookupConfig(UINTPTR BaseAddress)
Look up the hardware configuration for a device instance.
BaseAddress is the BaseAddress of the device to lookup for The reference to the configuration record in the configuration table (in xmipi_rx_phy_g.c) corresponding to the BaseAddr or if not found,a NULL pointer is returned. None
Referenced by Mipi_Rx_PhySelfTestExample.
u32 XMipi_Rx_Phy_CfgInitialize(XMipi_Rx_Phy *InstancePtr, XMipi_Rx_Phy_Config *CfgPtr, UINTPTR EffectiveAddr)
Initialize the XMipi_Rx_Phy instance provided by the caller based on the given Config structure.
InstancePtr is the XMipi_Rx_Phy instance to operate on. CfgPtr is the device configuration structure containing information about a specific Mipi_Rx_Phy instance. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS Initialization was successful. None.
References XMipi_Rx_Phy_Config::BaseAddr, XMipi_Rx_Phy::Config, XMipi_Rx_Phy::IsReady.
Referenced by Mipi_Rx_PhySelfTestExample.
u32 XMipi_Rx_Phy_Configure(XMipi_Rx_Phy *InstancePtr, u8 Handle, u32 Value)
Configure the registers of the Mipi_Rx_Phy instance.
InstancePtr is the XMipi_Rx_Phy instance to operate on. Handle to one of the registers to be configured Value to be set for the particular Handle of the Mipi_Rx_Phy instance XST_SUCCESS on successful register update.XST_FAILURE If incorrect handle was passed There is a limit on the minimum and maximum values of the HS Timeout register.
References XMipi_Rx_Phy::Config, XMipi_Rx_Phy_Config::EnableTimeOutRegs, XMipi_Rx_Phy_Config::IsDphy, XMipi_Rx_Phy_Config::IsRegisterPresent, XMIPI_RX_PHY_ESCTIMEOUT_REG_OFFSET, XMIPI_RX_PHY_HANDLE_CLKLANE, XMIPI_RX_PHY_HANDLE_DLANE0, XMIPI_RX_PHY_HANDLE_DLANE1, XMIPI_RX_PHY_HANDLE_DLANE2, XMIPI_RX_PHY_HANDLE_DLANE3, XMIPI_RX_PHY_HANDLE_ESCTIMEOUT, XMIPI_RX_PHY_HANDLE_HSSETTLE0, XMIPI_RX_PHY_HANDLE_HSSETTLE1, XMIPI_RX_PHY_HANDLE_HSSETTLE2, XMIPI_RX_PHY_HANDLE_HSSETTLE3, XMIPI_RX_PHY_HANDLE_HSTIMEOUT, XMIPI_RX_PHY_HANDLE_INIT_TIMER, XMIPI_RX_PHY_HANDLE_MAX, XMIPI_RX_PHY_HS_SETTLE_MAX_VALUE, XMIPI_RX_PHY_HS_TIMEOUT_MAX_VALUE, XMIPI_RX_PHY_HS_TIMEOUT_MIN_VALUE, XMIPI_RX_PHY_HSSETTLE0_REG_OFFSET, XMIPI_RX_PHY_HSSETTLE1_REG_OFFSET, XMIPI_RX_PHY_HSSETTLE2_REG_OFFSET, XMIPI_RX_PHY_HSSETTLE3_REG_OFFSET, XMIPI_RX_PHY_HSTIMEOUT_REG_OFFSET, XMIPI_RX_PHY_INIT_TIMER_REG_OFFSET.
u32 XMipi_Rx_Phy_GetInfo(XMipi_Rx_Phy *InstancePtr, u8 Handle)
Get information stored in the Mipi_Rx_Phy instance based on the handle passed.
InstancePtr is the XMipi_Rx_Phy instance to operate on. Handle to one of the registers to be configured The value stored in the corresponding register None.
References XMipi_Rx_Phy::Config, XMipi_Rx_Phy_Config::EnableTimeOutRegs, XMipi_Rx_Phy_Config::EscTimeout, XMipi_Rx_Phy_Config::HSTimeOut, XMipi_Rx_Phy_Config::IsDphy, XMipi_Rx_Phy_Config::IsRegisterPresent, XMIPI_RX_PHY_CLSTATUS_REG_OFFSET, XMIPI_RX_PHY_DL0STATUS_REG_OFFSET, XMIPI_RX_PHY_DL1STATUS_REG_OFFSET, XMIPI_RX_PHY_DL2STATUS_REG_OFFSET, XMIPI_RX_PHY_DL3STATUS_REG_OFFSET, XMIPI_RX_PHY_ESCTIMEOUT_REG_OFFSET, XMIPI_RX_PHY_HANDLE_CLKLANE, XMIPI_RX_PHY_HANDLE_DLANE0, XMIPI_RX_PHY_HANDLE_DLANE1, XMIPI_RX_PHY_HANDLE_DLANE2, XMIPI_RX_PHY_HANDLE_DLANE3, XMIPI_RX_PHY_HANDLE_ESCTIMEOUT, XMIPI_RX_PHY_HANDLE_HSSETTLE0, XMIPI_RX_PHY_HANDLE_HSSETTLE1, XMIPI_RX_PHY_HANDLE_HSSETTLE2, XMIPI_RX_PHY_HANDLE_HSSETTLE3, XMIPI_RX_PHY_HANDLE_HSTIMEOUT, XMIPI_RX_PHY_HANDLE_INIT_TIMER, XMIPI_RX_PHY_HANDLE_MAX, XMIPI_RX_PHY_HSSETTLE0_REG_OFFSET, XMIPI_RX_PHY_HSSETTLE1_REG_OFFSET, XMIPI_RX_PHY_HSSETTLE2_REG_OFFSET, XMIPI_RX_PHY_HSSETTLE3_REG_OFFSET, XMIPI_RX_PHY_HSTIMEOUT_REG_OFFSET, XMIPI_RX_PHY_INIT_TIMER_REG_OFFSET.
Referenced by XMipi_Rx_Phy_SelfTest.
void XMipi_Rx_Phy_Reset(XMipi_Rx_Phy *InstancePtr)
This is used to do a soft reset of the Mipi_Rx_Phy IP instance.
The reset takes approx 20 core clock cycles to become effective. InstancePtr is the XMipi_Rx_Phy instance to operate on. None None.
References XMipi_Rx_Phy::Config, XMipi_Rx_Phy::IsReady, XMipi_Rx_Phy_Config::IsRegisterPresent, XMIPI_RX_PHY_CTRL_REG_OFFSET, XMIPI_RX_PHY_CTRL_REG_SOFTRESET_MASK.
void XMipi_Rx_Phy_ClearDataLane(XMipi_Rx_Phy *InstancePtr, u8 DataLane, u32 Mask)
This is used to clear the Abort Error (Escape or High Speed) bits in the Data Lane 0 through 3.
InstancePtr is the XMipi_Rx_Phy instance to operate on. DataLane represents which Data Lane to act upon Mask contains information about which bits to reset None None.
References XMipi_Rx_Phy_Config::BaseAddr, XMipi_Rx_Phy::Config, XMipi_Rx_Phy_Config::IsRegisterPresent, XMIPI_RX_PHY_DL0STATUS_REG_OFFSET, XMIPI_RX_PHY_DLXSTATUS_REG_ESCABRT_MASK, XMIPI_RX_PHY_DLXSTATUS_REG_HSABRT_MASK.
u32 XMipi_Rx_Phy_GetClkLaneStatus(XMipi_Rx_Phy *InstancePtr)
This is used to get information about Clock Lane status.
InstancePtr is the XMipi_Rx_Phy instance to operate on. Bitmask containing which of the events have occurred along with the mode of the Clock Lane in Phy None.
References XMipi_Rx_Phy_Config::BaseAddr, XMipi_Rx_Phy::Config, XMipi_Rx_Phy_Config::IsDphy, XMipi_Rx_Phy_Config::IsRegisterPresent, XMIPI_RX_PHY_CLSTATUS_REG_OFFSET.
Referenced by XMipi_Rx_Phy_GetClkLaneMode.
u32 XMipi_Rx_Phy_GetClkLaneMode(XMipi_Rx_Phy *InstancePtr)
This is used to get specific Lane mode information about Clock Lane.
InstancePtr is the XMipi_Rx_Phy instance to operate on. Bitmask containing mode in which the Clock Lane in Mipi_Rx_Phy is in. None.
References XMipi_Rx_Phy::Config, XMipi_Rx_Phy_Config::IsDphy, XMipi_Rx_Phy_Config::IsRegisterPresent, XMIPI_RX_PHY_CLSTATUS_REG_MODE_MASK, XMipi_Rx_Phy_GetClkLaneStatus.
u32 XMipi_Rx_Phy_GetDataLaneStatus(XMipi_Rx_Phy *InstancePtr, u8 DataLane)
This is used to get information about a Data Lane status.
InstancePtr is the XMipi_Rx_Phy instance to operate on. DataLane for which the status is sought for. Bitmask containing which of the events have occurred along with the mode of the Data Lane in Phy None.
References XMipi_Rx_Phy_Config::BaseAddr, XMipi_Rx_Phy::Config, XMipi_Rx_Phy_Config::IsRegisterPresent, XMIPI_RX_PHY_DL0STATUS_REG_OFFSET.
Referenced by XMipi_Rx_Phy_GetDataLaneMode.
u16 XMipi_Rx_Phy_GetPacketCount(XMipi_Rx_Phy *InstancePtr, u8 DataLane)
This is used to get count of packets received on each lane.
InstancePtr is the XMipi_Rx_Phy instance to operate on. DataLane for which the mode info is requested. Bitmask containing mode in which the Data Lane in Mipi_Rx_Phy is in. None.
References XMipi_Rx_Phy_Config::BaseAddr, XMipi_Rx_Phy::Config, XMipi_Rx_Phy_Config::IsRegisterPresent, XMIPI_RX_PHY_DL0STATUS_REG_OFFSET, XMIPI_RX_PHY_DLXSTATUS_REG_PACKCOUNT_OFFSET, XMIPI_RX_PHY_DLXSTATUS_REG_PACKETCOUNT_MASK.
u8 XMipi_Rx_Phy_GetDLCalibStatus(XMipi_Rx_Phy *InstancePtr, u8 DataLane)
This is used to get Data Lane Calibration status.
InstancePtr is the XMipi_Rx_Phy instance to operate on. DataLane for which the calib status is sought for. XST_SUCCESS - Calibration Complete, Calibration packet received XST_NO_DATA - Calibration Complete, Calibration packet is not received XST_FAILURE - Calibration failed None.
References XMipi_Rx_Phy_Config::BaseAddr, XMipi_Rx_Phy::Config, DL_LANE_OFFSET, XMipi_Rx_Phy_Config::IsRegisterPresent, XMIPI_RX_PHY_DL0STATUS_REG_OFFSET, XMIPI_RX_PHY_DLXSTATUS_REG_CALIB_COMPLETE_MASK, XMIPI_RX_PHY_DLXSTATUS_REG_CALIB_STATUS_MASK.
u32 XMipi_Rx_Phy_GetDataLaneMode(XMipi_Rx_Phy *InstancePtr, u8 DataLane)
This is used to get specific Lane mode information about a Data Lane.
InstancePtr is the XMipi_Rx_Phy instance to operate on. DataLane for which the mode info is requested. Bitmask containing mode in which the Data Lane in Mipi_Rx_Phy is in. None.
References XMipi_Rx_Phy::Config, XMipi_Rx_Phy_Config::IsRegisterPresent, XMIPI_RX_PHY_DLXSTATUS_REG_MODE_MASK, XMipi_Rx_Phy_GetDataLaneStatus.
void XMipi_Rx_Phy_Activate(XMipi_Rx_Phy *InstancePtr, u8 Flag)
This function is used to enable or disable the Mipi_Rx_Phy core.
InstancePtr is the XMipi_Rx_Phy instance to operate on. Flag denoting whether to enable or disable the Mipi_Rx_Phy core None. None.
References XMipi_Rx_Phy_Config::BaseAddr, XMipi_Rx_Phy::Config, XMipi_Rx_Phy_Config::IsRegisterPresent, XMIPI_RX_PHY_CTRL_REG_OFFSET, XMIPI_RX_PHY_CTRL_REG_PHYEN_MASK, XMIPI_RX_PHY_DISABLE_FLAG, XMIPI_RX_PHY_ENABLE_FLAG.
Referenced by XMipi_Rx_Phy_DynamicLineRateConfig.
u8 XMipi_Rx_Phy_GetRegIntfcPresent(XMipi_Rx_Phy *InstancePtr)
Get if register interface is present from the config structure for specified Mipi_Rx_Phy instance.
InstancePtr is the XMipi_Rx_Phy instance to operate on. 1 if register interface is present0 if register interface is absent None.
References XMipi_Rx_Phy::Config, XMipi_Rx_Phy_Config::IsRegisterPresent.
Referenced by Mipi_Rx_PhySelfTestExample.
u32 XMipi_Rx_Phy_DynamicLineRateConfig(XMipi_Rx_Phy *InstancePtr, UINTPTR PllBaseAddr, u32 LineRate)
This function configures the dynamic line rate for the MIPI RX PHY by programming the MMCM registers and NPI X5PLL registers.
The driver disables the PHY, programs the MMCM via XMipi_Rx_Phy_MmcmConfig, delegates the PLL register programming to XMipi_Rx_Phy_XPllConfig, and re-enables the PHY. InstancePtr is the XMipi_Rx_Phy instance to operate on. PllBaseAddr is the base address of the X5PLL register space. LineRate is the desired line rate in Mbps (400-4500 Mbps). XST_SUCCESS if line rate configuration is successful.XST_FAILURE if the line rate is out of supported range or dynamic line rate is not enabled in hardware. The PHY is disabled before MMCM and PLL reprogramming and re-enabled after the sequence completes to ensure a clean transition.
References XMipi_Rx_Phy::Config, XMipi_Rx_Phy_Config::IsDphy, XMipi_Rx_Phy_Config::IsDynamicLineRate, XMipi_Rx_Phy_Activate, XMIPI_RX_PHY_DISABLE_FLAG, XMIPI_RX_PHY_ENABLE_FLAG, XMIPI_RX_PHY_LINERATE_MAX, XMIPI_RX_PHY_LINERATE_MIN, XMipi_Rx_Phy_MmcmConfig, XMipi_Rx_Phy_XPllConfig.
u32 XMipi_Rx_Phy_XPllConfig(UINTPTR PllBaseAddr, u32 LineRate)
This function programs the X5PLL registers for a given line rate.
It looks up the matching bucket from the line rate table, then performs the PLL unlock -> configure -> re-lock sequence. PllBaseAddr is the base address of the X5PLL register space. LineRate is the desired line rate in Mbps (400-4500 Mbps). XST_SUCCESS if PLL programming is successful.XST_FAILURE if no matching line rate bucket is found. None.
Referenced by XMipi_Rx_Phy_DynamicLineRateConfig.
u32 XMipi_Rx_Phy_MmcmConfig(XMipi_Rx_Phy *InstancePtr, u32 LineRate)
This function configures the MMCM registers in the RX PHY for a given line rate.
It computes the optimal MMCM parameters (M, D, O) and writes the corresponding values to the PHY MMCM registers. InstancePtr is the XMipi_Rx_Phy instance to operate on. LineRate is the desired line rate in Mbps (400-4500 Mbps). XST_SUCCESS if MMCM programming is successful.XST_FAILURE if no valid MMCM solution is found. None.
Referenced by XMipi_Rx_Phy_DynamicLineRateConfig.
u32 XMipi_Rx_Phy_SelfTest(XMipi_Rx_Phy *InstancePtr)
Runs a self-test on the driver/device.
This test checks if HS Timeout value present in register matches the one from the generated file. InstancePtr is a pointer to the XMipi_Rx_Phy instance. XST_SUCCESS if self-test was successful XST_FAILURE if the read value was not equal to _g.c file None.
References XMipi_Rx_Phy::Config, XMipi_Rx_Phy_Config::HSTimeOut, XMipi_Rx_Phy_GetInfo, XMIPI_RX_PHY_HANDLE_HSTIMEOUT.
Referenced by Mipi_Rx_PhySelfTestExample.