xocp_mailbox_apis
int XOcp_ClientInit(XOcp_ClientInstance *const InstancePtr, XMailbox *const MailboxPtr)
This function sets the instance of mailbox.
InstancePtr - Pointer to the client instance MailboxPtr - Pointer to the mailbox instance XST_SUCCESS - On successful initializationXST_FAILURE - On failure
References XOcp_ClientInstance::MailboxPtr.
Referenced by main.
int XOcp_ProcessMailbox(XMailbox *MailboxPtr, u32 *MsgPtr, u32 MsgLen)
This function sends IPI request to the target module and gets the response from it.
MailboxPtr - Pointer to mailbox instance MsgPtr - Pointer to the payload message MsgLen - Length of the message XST_SUCCESS - If the IPI send and receive is successfulXST_FAILURE - If there is a failure Payload consists of API id and call arguments to be written in IPI buffer
Referenced by XOcp_ClientAttestWithDevAk, XOcp_ClientAttestWithKeyWrapDevAk, XOcp_ExtendHwPcr, XOcp_ExtendSwPcr, XOcp_GenDmeResp, XOcp_GenSharedSecretWithDevAk, XOcp_GetHwPcr, XOcp_GetHwPcrLog, XOcp_GetSwPcr, XOcp_GetSwPcrData, XOcp_GetSwPcrLog, XOcp_GetX509Cert.