uartps
XUARTPS_OPTION_SET_BREAK
These constants specify the options that may be set or retrieved with the driver, each is a unique bit mask such that multiple options may be specified.
These constants indicate the available options in active state.Starts break transmission
Referenced by XUartPs_SetOptions.
XUARTPS_OPTION_STOP_BREAK
Stops break transmission.
XUARTPS_OPTION_RESET_TMOUT
Reset the receive timeout.
XUARTPS_OPTION_RESET_TX
Reset the transmitter.
XUARTPS_OPTION_RESET_RX
Reset the receiver.
XUARTPS_OPTION_ASSERT_RTS
Assert the RTS bit.
XUARTPS_OPTION_ASSERT_DTR
Assert the DTR bit.
XUARTPS_OPTION_SET_FCM
Turn on flow control mode.
XUARTPS_OPER_MODE_NORMAL
Normal Mode.
Referenced by UartPsIntrExample, UartPsPolledExample, XUartPs_GetOperMode, XUartPs_SetOperMode.
XUARTPS_OPER_MODE_AUTO_ECHO
Auto Echo Mode.
Referenced by XUartPs_GetOperMode, XUartPs_SetOperMode.
XUARTPS_OPER_MODE_LOCAL_LOOP
Local Loopback Mode.
Referenced by UartPsIntrExample, UartPsPolledExample, XUartPs_GetOperMode, XUartPs_SetOperMode.
XUARTPS_OPER_MODE_REMOTE_LOOP
Remote Loopback Mode.
Referenced by XUartPs_GetOperMode, XUartPs_SetOperMode.
XUARTPS_FORMAT_8_BITS
8 data bits
XUARTPS_FORMAT_7_BITS
7 data bits
XUARTPS_FORMAT_6_BITS
6 data bits
Referenced by XUartPs_SetDataFormat.
XUARTPS_FORMAT_NO_PARITY
No parity.
Referenced by XUartPs_SetDataFormat.
XUARTPS_FORMAT_MARK_PARITY
Mark parity.
XUARTPS_FORMAT_SPACE_PARITY
parity
XUARTPS_FORMAT_ODD_PARITY
Odd parity.
XUARTPS_FORMAT_EVEN_PARITY
Even parity.
XUARTPS_FORMAT_2_STOP_BIT
2 stop bits
Referenced by XUartPs_SetDataFormat.
XUARTPS_FORMAT_1_5_STOP_BIT
1.5 stop bits
XUARTPS_FORMAT_1_STOP_BIT
1 stop bit
XUARTPS_EVENT_RECV_DATA
Data receiving done.
XUARTPS_EVENT_RECV_TOUT
A receive timeout occurred.
XUARTPS_EVENT_SENT_DATA
Data transmission done.
XUARTPS_EVENT_RECV_ERROR
A receive error detected.
XUARTPS_EVENT_MODEM
Modem status changed.
XUARTPS_EVENT_PARE_FRAME_BRKE
A receive parity, frame, break error detected.
XUARTPS_EVENT_RECV_ORERR
A receive overrun error detected.
XUARTPS_CR_OFFSET
Control Register [8:0].
Referenced by UartPsEchoExample, XUartPs_ResetHw, XUartPs_SetBaudRate, XUartPs_SetRecvTimeout.
XUARTPS_MR_OFFSET
Mode Register [9:0].
Referenced by XUartPs_CfgInitialize, XUartPs_GetDataFormat, XUartPs_GetOperMode, XUartPs_ResetHw, XUartPs_SelfTest, XUartPs_SetBaudRate, XUartPs_SetDataFormat, XUartPs_SetOperMode.
XUARTPS_IER_OFFSET
Interrupt Enable [12:0].
Referenced by XUartPs_Recv, XUartPs_SelfTest, XUartPs_SetInterruptMask.
XUARTPS_IDR_OFFSET
Interrupt Disable [12:0].
Referenced by XUartPs_CfgInitialize, XUartPs_Recv, XUartPs_ResetHw, XUartPs_SelfTest, XUartPs_Send, XUartPs_SetInterruptMask.
XUARTPS_IMR_OFFSET
Interrupt Mask [12:0].
Referenced by XUartPs_GetInterruptMask, XUartPs_InterruptHandler, XUartPs_Recv, XUartPs_SelfTest.
XUARTPS_ISR_OFFSET
Interrupt Status [12:0].
Referenced by XUartPs_InterruptHandler, XUartPs_ResetHw.
XUARTPS_BAUDGEN_OFFSET
Baud Rate Generator [15:0].
Referenced by XUartPs_ResetHw, XUartPs_SetBaudRate.
XUARTPS_RXTOUT_OFFSET
RX Timeout [7:0].
Referenced by XUartPs_CfgInitialize, XUartPs_GetRecvTimeout, XUartPs_ResetHw, XUartPs_SetRecvTimeout.
XUARTPS_RXWM_OFFSET
RX FIFO Trigger Level [5:0].
Referenced by XUartPs_CfgInitialize, XUartPs_GetFifoThreshold, XUartPs_ResetHw, XUartPs_SetFifoThreshold.
XUARTPS_MODEMCR_OFFSET
Modem Control [5:0].
XUARTPS_MODEMSR_OFFSET
Modem Status [8:0].
Referenced by XUartPs_GetModemStatus.
XUARTPS_SR_OFFSET
Channel Status [14:0].
Referenced by XUartPs_IsSending, XUartPs_SelfTest.
XUARTPS_FIFO_OFFSET
FIFO [7:0].
Referenced by UartPsEchoExample, XUartPs_RecvByte, XUartPs_SendByte.
XUARTPS_BAUDDIV_OFFSET
Baud Rate Divider [7:0].
Referenced by XUartPs_ResetHw, XUartPs_SetBaudRate.
XUARTPS_FLOWDEL_OFFSET
Flow Delay [5:0].
Referenced by XUartPs_GetFlowDelay, XUartPs_SetFlowDelay.
XUARTPS_TXWM_OFFSET
TX FIFO Trigger Level [5:0].
Referenced by XUartPs_ResetHw.
XUARTPS_RXBS_OFFSET
RX FIFO Byte Status [11:0].
XUARTPS_CR_STOPBRK
Stop transmission of break.
Referenced by XUartPs_ResetHw, XUartPs_SetOptions.
XUARTPS_CR_STARTBRK
Set break.
XUARTPS_CR_TORST
RX timeout counter restart.
Referenced by XUartPs_SetRecvTimeout.
XUARTPS_CR_TX_DIS
TX disabled.
Referenced by XUartPs_ResetHw.
XUARTPS_CR_TX_EN
TX enabled.
Referenced by UartPsEchoExample.
XUARTPS_CR_RX_DIS
RX disabled.
Referenced by XUartPs_ResetHw.
XUARTPS_CR_RX_EN
RX enabled.
Referenced by UartPsEchoExample.
XUARTPS_CR_EN_DIS_MASK
Enable/disable Mask.
Referenced by UartPsEchoExample.
XUARTPS_CR_TXRST
TX logic reset.
Referenced by XUartPs_ResetHw, XUartPs_SetBaudRate.
XUARTPS_CR_RXRST
RX logic reset.
Referenced by XUartPs_ResetHw, XUartPs_SetBaudRate.
XUARTPS_MR_CCLK
Input clock selection.
XUARTPS_MR_CHMODE_R_LOOP
Remote loopback mode.
Referenced by XUartPs_GetOperMode, XUartPs_SetOperMode.
XUARTPS_MR_CHMODE_L_LOOP
Local loopback mode.
Referenced by XUartPs_GetOperMode, XUartPs_SelfTest, XUartPs_SetOperMode.
XUARTPS_MR_CHMODE_ECHO
Auto echo mode.
Referenced by XUartPs_GetOperMode, XUartPs_SetOperMode.
XUARTPS_MR_CHMODE_NORM
Normal mode.
Referenced by XUartPs_GetOperMode, XUartPs_ResetHw, XUartPs_SetOperMode.
XUARTPS_MR_CHMODE_SHIFT
Mode shift.
Referenced by XUartPs_GetOperMode.
XUARTPS_MR_CHMODE_MASK
Mode mask.
Referenced by XUartPs_GetOperMode, XUartPs_SelfTest, XUartPs_SetOperMode.
XUARTPS_MR_STOPMODE_2_BIT
2 stop bits
XUARTPS_MR_STOPMODE_1_5_BIT
1.5 stop bits
XUARTPS_MR_STOPMODE_1_BIT
1 stop bit
Referenced by XUartPs_CfgInitialize.
XUARTPS_MR_STOPMODE_SHIFT
Stop bits shift.
Referenced by XUartPs_GetDataFormat, XUartPs_SetDataFormat.
XUARTPS_MR_STOPMODE_MASK
Stop bits mask.
Referenced by XUartPs_CfgInitialize, XUartPs_GetDataFormat, XUartPs_SetDataFormat.
XUARTPS_MR_PARITY_NONE
No parity mode.
Referenced by XUartPs_CfgInitialize.
XUARTPS_MR_PARITY_MARK
Mark parity mode.
XUARTPS_MR_PARITY_SPACE
Space parity mode.
XUARTPS_MR_PARITY_ODD
Odd parity mode.
XUARTPS_MR_PARITY_EVEN
Even parity mode.
XUARTPS_MR_PARITY_SHIFT
Parity setting shift.
Referenced by XUartPs_GetDataFormat, XUartPs_SetDataFormat.
XUARTPS_MR_PARITY_MASK
Parity mask.
Referenced by XUartPs_CfgInitialize, XUartPs_GetDataFormat, XUartPs_SetDataFormat.
XUARTPS_MR_CHARLEN_6_BIT
6 bits data
XUARTPS_MR_CHARLEN_7_BIT
7 bits data
XUARTPS_MR_CHARLEN_8_BIT
8 bits data
Referenced by XUartPs_CfgInitialize.
XUARTPS_MR_CHARLEN_SHIFT
Data Length shift.
Referenced by XUartPs_GetDataFormat, XUartPs_SetDataFormat.
XUARTPS_MR_CHARLEN_MASK
Data length mask.
Referenced by XUartPs_CfgInitialize, XUartPs_GetDataFormat, XUartPs_SetDataFormat.
XUARTPS_MR_CLKSEL
Input clock selection.
Referenced by XUartPs_SetBaudRate.
XUARTPS_IXR_RBRK
Rx FIFO break detect interrupt.
Referenced by UartPsIntrExample, XUartPs_InterruptHandler.
XUARTPS_IXR_TOVR
Tx FIFO Overflow interrupt.
XUARTPS_IXR_TNFUL
Tx FIFO Nearly Full interrupt.
XUARTPS_IXR_TTRIG
Tx Trig interrupt.
XUARTPS_IXR_DMS
Modem status change interrupt.
Referenced by XUartPs_InterruptHandler.
XUARTPS_IXR_TOUT
Timeout error interrupt.
Referenced by UartPsIntrExample, XUartPs_InterruptHandler.
XUARTPS_IXR_PARITY
Parity error interrupt.
Referenced by UartPsIntrExample, XUartPs_InterruptHandler.
XUARTPS_IXR_FRAMING
Framing error interrupt.
Referenced by UartPsIntrExample, XUartPs_InterruptHandler.
XUARTPS_IXR_OVER
Overrun error interrupt.
Referenced by UartPsIntrExample, XUartPs_InterruptHandler.
XUARTPS_IXR_TXFULL
TX FIFO full interrupt.
Referenced by XUartPs_InterruptHandler, XUartPs_Send.
XUARTPS_IXR_TXEMPTY
TX FIFO empty interrupt.
Referenced by UartPsIntrExample, XUartPs_InterruptHandler, XUartPs_Send.
XUARTPS_IXR_RXFULL
RX FIFO full interrupt.
Referenced by UartPsIntrExample, XUartPs_InterruptHandler.
XUARTPS_IXR_RXEMPTY
RX FIFO empty interrupt.
Referenced by XUartPs_InterruptHandler.
XUARTPS_IXR_RXOVR
RX FIFO trigger interrupt.
Referenced by UartPsIntrExample, XUartPs_InterruptHandler.
XUARTPS_IXR_MASK
Valid bit mask.
Referenced by XUartPs_CfgInitialize, XUartPs_Recv, XUartPs_ResetHw, XUartPs_SelfTest, XUartPs_SetInterruptMask.
XUARTPS_BAUDGEN_DISABLE
Disable clock.
XUARTPS_BAUDGEN_MASK
Valid bits mask.
XUARTPS_BAUDGEN_RESET_VAL
Reset value.
Referenced by XUartPs_ResetHw.
XUARTPS_BAUDDIV_MASK
8 bit baud divider mask
XUARTPS_BAUDDIV_RESET_VAL
Reset value.
Referenced by XUartPs_ResetHw.
XUARTPS_RXTOUT_DISABLE
Disable time out.
Referenced by XUartPs_ResetHw.
XUARTPS_RXTOUT_MASK
Valid bits mask.
Referenced by XUartPs_GetRecvTimeout, XUartPs_SetRecvTimeout.
XUARTPS_RXWM_DISABLE
Disable RX trigger interrupt.
XUARTPS_RXWM_MASK
Valid bits mask.
Referenced by XUartPs_GetFifoThreshold, XUartPs_SetFifoThreshold.
XUARTPS_RXWM_RESET_VAL
Reset value.
Referenced by XUartPs_ResetHw.
XUARTPS_TXWM_MASK
Valid bits mask.
XUARTPS_TXWM_RESET_VAL
Reset value.
Referenced by XUartPs_ResetHw.
XUARTPS_MODEMCR_FCM
Flow control mode.
XUARTPS_MODEMCR_RTS
Request to send.
XUARTPS_MODEMCR_DTR
Data terminal ready.
XUARTPS_MODEMSR_FCMS
Flow control mode (FCMS)
XUARTPS_MODEMSR_DCD
Complement of DCD input.
XUARTPS_MODEMSR_RI
Complement of RI input.
XUARTPS_MODEMSR_DSR
Complement of DSR input.
XUARTPS_MODEMSR_CTS
Complement of CTS input.
XUARTPS_MODEMSR_DDCD
Delta DCD indicator.
XUARTPS_MODEMSR_TERI
Trailing Edge Ring Indicator.
XUARTPS_MODEMSR_DDSR
Change of DSR.
XUARTPS_MODEMSR_DCTS
Change of CTS.
XUARTPS_SR_TNFUL
TX FIFO Nearly Full Status.
XUARTPS_SR_TTRIG
TX FIFO Trigger Status.
XUARTPS_SR_FLOWDEL
RX FIFO fill over flow delay.
XUARTPS_SR_TACTIVE
TX active.
Referenced by XUartPs_IsSending.
XUARTPS_SR_RACTIVE
RX active.
XUARTPS_SR_TXFULL
TX FIFO full.
XUARTPS_SR_TXEMPTY
TX FIFO empty.
Referenced by XUartPs_IsSending.
XUARTPS_SR_RXFULL
RX FIFO full.
XUARTPS_SR_RXEMPTY
RX FIFO empty.
Referenced by XUartPs_SelfTest.
XUARTPS_SR_RXOVR
RX FIFO fill over trigger.
XUARTPS_FLOWDEL_MASK
Valid bit mask.
Referenced by XUartPs_GetFlowDelay, XUartPs_SetFlowDelay.
XUARTPS_RXBS_BYTE3_BRKE
Byte3 Break Error.
XUARTPS_RXBS_BYTE3_FRME
Byte3 Frame Error.
XUARTPS_RXBS_BYTE3_PARE
Byte3 Parity Error.
XUARTPS_RXBS_BYTE2_BRKE
Byte2 Break Error.
XUARTPS_RXBS_BYTE2_FRME
Byte2 Frame Error.
XUARTPS_RXBS_BYTE2_PARE
Byte2 Parity Error.
XUARTPS_RXBS_BYTE1_BRKE
Byte1 Break Error.
XUARTPS_RXBS_BYTE1_FRME
Byte1 Frame Error.
XUARTPS_RXBS_BYTE1_PARE
Byte1 Parity Error.
XUARTPS_RXBS_BYTE0_BRKE
Byte0 Break Error.
XUARTPS_RXBS_BYTE0_FRME
Byte0 Frame Error.
XUARTPS_RXBS_BYTE0_PARE
Byte0 Parity Error.
XUARTPS_RXBS_MASK
3 bit RX byte status mask
typedef void(* XUartPs_Handler)(void *CallBackRef, u32 Event, u32 EventData))(void *CallBackRef, u32 Event, u32 EventData)
This data type defines a handler that an application defines to communicate with interrupt system to retrieve state information about an application.
CallBackRef is a callback reference passed in by the upper layer when setting the handler, and is passed back to the upper layer when the handler is called. It is used to find the device driver instance. Event contains one of the event constants indicating events that have occurred. EventData contains the number of bytes sent or received at the time of the call for send and receive events and contains the modem status for modem events.
void Handler)(XUartPs *InstancePtr)
This function is the handler which performs processing to handle data events from the device.
It is called from an interrupt context. so the amount of processing should be minimal.This handler provides an example of how to handle data for the device and is application specific. CallBackRef contains a callback reference from the driver, in this case it is the instance pointer for the XUartPs driver. Event contains the specific kind of event that has occurred. EventData contains the number of bytes sent or received for sent and receive events. None. None.
XUartPs_Config XUartPs_ConfigTable[XPAR_XUARTPS_NUM_INSTANCES][XPAR_XUARTPS_NUM_INSTANCES]
Each XUartPs device in the system has an entry in this table.
Mapping OptionsTable[][]
u8 TestString[XUARTPS_TOTAL_BYTES][XUARTPS_TOTAL_BYTES]
u8 ReturnString[XUARTPS_TOTAL_BYTES][XUARTPS_TOTAL_BYTES]
XUartPs_Config XUartPs_ConfigTable[][]
Each XUartPs device in the system has an entry in this table.
static void XUartPs_StubHandler(void *CallBackRef, u32 Event, u32 ByteCount)
This function is a stub handler that is the default handler such that if the application has not set the handler when interrupts are enabled, this function will be called.
CallBackRef is unused by this function. Event is unused by this function. ByteCount is unused by this function. None. None.
u32 XUartPs_SendBuffer(XUartPs *InstancePtr)
u32 XUartPs_ReceiveBuffer(XUartPs *InstancePtr)
s32 XUartPs_CfgInitialize(XUartPs *InstancePtr, XUartPs_Config *Config, u32 EffectiveAddr)
Initializes a specific XUartPs instance such that it is ready to be used.
The data format of the device is setup for 8 data bits, 1 stop bit, and no parity by default. The baud rate is set to a default value specified by Config->DefaultBaudRate if set, otherwise it is set to 19.2K baud. The receive FIFO threshold is set for 8 bytes. The default operating mode of the driver is polled mode. InstancePtr is a pointer to the XUartPs instance. Config is a reference to a structure containing information about a specific XUartPs driver. EffectiveAddr is the device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, pass in the physical address instead. - XST_SUCCESS if initialization was successful - XST_UART_BAUD_ERROR if the baud rate is not possible because the inputclock frequency is not divisible with an acceptable amount of error The default configuration for the UART after initialization is: 19,200 bps or XPAR_DFT_BAUDRATE if defined8 data bits1 stop bitno parityFIFO's are enabled with a receive threshold of 8 bytesThe RX timeout is enabled with a timeout of 1 (4 char times)All interrupts are disabled.
References XUartPs_Config::BaseAddress, XUartPs_Config::InputClockHz, XUartPs_Config::IntrId, XUartPs_Config::IntrParent, XUartPs_Config::ModemPinsConnected, XUartPs_Config::RefClk, XUARTPS_IDR_OFFSET, XUARTPS_IXR_MASK, XUARTPS_MR_CHARLEN_8_BIT, XUARTPS_MR_CHARLEN_MASK, XUARTPS_MR_OFFSET, XUARTPS_MR_PARITY_MASK, XUARTPS_MR_PARITY_NONE, XUARTPS_MR_STOPMODE_1_BIT, XUARTPS_MR_STOPMODE_MASK, XUartPs_ReadReg, XUARTPS_RXTOUT_OFFSET, XUARTPS_RXWM_OFFSET, XUartPs_SetBaudRate, XUartPs_WriteReg.
Referenced by UartPsHelloWorldExample, UartPsIntrExample, UartPsPolledExample, UartPsSelfTestExample.
u32 XUartPs_Send(XUartPs *InstancePtr, u8 *BufferPtr, u32 NumBytes)
This functions sends the specified buffer using the device in either polled or interrupt driven mode.
This function is non-blocking, if the device is busy sending data, it will return and indicate zero bytes were sent. Otherwise, it fills the TX FIFO as much as it can, and return the number of bytes sent.In a polled mode, this function will only send as much data as TX FIFO can buffer. The application may need to call it repeatedly to send the entire buffer.In interrupt mode, this function will start sending the specified buffer, then the interrupt handler will continue sending data until the entire buffer has been sent. A callback function, as specified by the application, will be called to indicate the completion of sending. InstancePtr is a pointer to the XUartPs instance. BufferPtr is pointer to a buffer of data to be sent. NumBytes contains the number of bytes to be sent. A value of zero will stop a previous send operation that is in progress in interrupt mode. Any data that was already put into the transmit FIFO will be sent. The number of bytes actually sent. The number of bytes is not asserted so that this function may be called with a value of zero to stop an operation that is already in progress.
References XUartPs_Config::BaseAddress, XUartPs_Config::RefClk, XUARTPS_IDR_OFFSET, XUARTPS_IXR_TXEMPTY, XUARTPS_IXR_TXFULL, XUartPs_WriteReg.
Referenced by UartPsHelloWorldExample, UartPsIntrExample, UartPsPolledExample, XUartPs_SelfTest.
u32 XUartPs_Recv(XUartPs *InstancePtr, u8 *BufferPtr, u32 NumBytes)
This function attempts to receive a specified number of bytes of data from the device and store it into the specified buffer.
This function works for both polled or interrupt driven modes. It is non-blocking.In a polled mode, this function will only receive the data already in the RX FIFO. The application may need to call it repeatedly to receive the entire buffer. Polled mode is the default mode of operation for the device.In interrupt mode, this function will start the receiving, if not the entire buffer has been received, the interrupt handler will continue receiving data until the entire buffer has been received. A callback function, as specified by the application, will be called to indicate the completion of the receiving or error conditions. InstancePtr is a pointer to the XUartPs instance BufferPtr is pointer to buffer for data to be received into NumBytes is the number of bytes to be received. A value of zero will stop a previous receive operation that is in progress in interrupt mode. The number of bytes received. The number of bytes is not asserted so that this function may be called with a value of zero to stop an operation that is already in progress.
References XUartPs_Config::BaseAddress, XUartPs_Config::RefClk, XUARTPS_IDR_OFFSET, XUARTPS_IER_OFFSET, XUARTPS_IMR_OFFSET, XUARTPS_IXR_MASK, XUartPs_ReadReg, XUartPs_WriteReg.
Referenced by UartPsIntrExample, UartPsPolledExample, XUartPs_SelfTest.
s32 XUartPs_SetBaudRate(XUartPs *InstancePtr, u32 BaudRate)
Sets the baud rate for the device.
Checks the input value for validity and also verifies that the requested rate can be configured to within the maximum error range specified by XUARTPS_MAX_BAUD_ERROR_RATE. If the provided rate is not possible, the current setting is unchanged. InstancePtr is a pointer to the XUartPs instance BaudRate to be set XST_SUCCESS if everything configured as expectedXST_UART_BAUD_ERROR if the requested rate is not available because there was too much error None.
References XUartPs_Config::BaseAddress, XUartPs_Config::InputClockHz, TIMEOUT_VAL, XUARTPS_BAUDDIV_OFFSET, XUARTPS_BAUDGEN_OFFSET, XUARTPS_CR_OFFSET, XUARTPS_CR_RXRST, XUARTPS_CR_TXRST, XUartPs_DisableUart, XUartPs_EnableUart, XUARTPS_MR_CLKSEL, XUARTPS_MR_OFFSET, XUartPs_ReadReg, XUartPs_WriteReg.
Referenced by UartPsHelloWorldExample, XUartPs_CfgInitialize, XUartPs_SetDataFormat.
XUartPs_Config * XUartPs_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XUartPs_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xuartps.h for the definition of XUartPs_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XUartPs_Config::Name.
Referenced by UartPsHelloWorldExample, UartPsIntrExample, UartPsPolledExample, UartPsSelfTestExample.
void XUartPs_SetOptions(XUartPs *InstancePtr, u16 Options)
Sets the options for the specified driver instance.
The options are implemented as bit masks such that multiple options may be enabled or disabled simultaneously.The GetOptions function may be called to retrieve the currently enabled options. The result is ORed in the desired new settings to be enabled and ANDed with the inverse to clear the settings to be disabled. The resulting value is then used as the options for the SetOption function call. InstancePtr is a pointer to the XUartPs instance. Options contains the options to be set which are bit masks contained in the file xuartps.h and named XUARTPS_OPTION_*. None. None.
References XUartPs_Config::BaseAddress, XUARTPS_CR_STOPBRK, XUARTPS_OPTION_SET_BREAK, XUartPs_ReadReg, XUartPs_WriteReg.
u16 XUartPs_GetOptions(XUartPs *InstancePtr)
Gets the options for the specified driver instance.
The options are implemented as bit masks such that multiple options may be enabled or disabled simultaneously. InstancePtr is a pointer to the XUartPs instance. The current options for the UART. The options are bit masks that are contained in the file xuartps.h and named XUARTPS_OPTION_*.None.
References XUartPs_Config::BaseAddress, XUartPs_ReadReg.
void XUartPs_SetFifoThreshold(XUartPs *InstancePtr, u8 TriggerLevel)
This functions sets the receive FIFO trigger level.
The receive trigger level specifies the number of bytes in the receive FIFO that cause a receive data event (interrupt) to be generated. InstancePtr is a pointer to the XUartPs instance. TriggerLevel contains the trigger level to set. None None.
References XUartPs_Config::BaseAddress, XUARTPS_RXWM_MASK, XUARTPS_RXWM_OFFSET, XUartPs_WriteReg.
u8 XUartPs_GetFifoThreshold(XUartPs *InstancePtr)
This function gets the receive FIFO trigger level.
The receive trigger level indicates the number of bytes in the receive FIFO that cause a receive data event (interrupt) to be generated. InstancePtr is a pointer to the XUartPs instance. The current receive FIFO trigger level. This is a value from 0-31. None.
References XUartPs_Config::BaseAddress, XUartPs_ReadReg, XUARTPS_RXWM_MASK, XUARTPS_RXWM_OFFSET.
u16 XUartPs_GetModemStatus(XUartPs *InstancePtr)
This function gets the modem status from the specified UART.
The modem status indicates any changes of the modem signals. This function allows the modem status to be read in a polled mode. The modem status is updated whenever it is read such that reading it twice may not yield the same results. InstancePtr is a pointer to the XUartPs instance. The modem status which are bit masks that are contained in the file xuartps.h and named XUARTPS_MODEM_*. The bit masks used for the modem status are the exact bits of the modem status register with no abstraction.
References XUartPs_Config::BaseAddress, XUARTPS_MODEMSR_OFFSET, XUartPs_ReadReg.
u32 XUartPs_IsSending(XUartPs *InstancePtr)
This function determines if the specified UART is sending data.
InstancePtr is a pointer to the XUartPs instance. TRUE if the UART is sending dataFALSE if UART is not sending data None.
References XUartPs_Config::BaseAddress, XUartPs_Config::RefClk, XUartPs_ReadReg, XUARTPS_SR_OFFSET, XUARTPS_SR_TACTIVE, XUARTPS_SR_TXEMPTY.
Referenced by UartPsPolledExample.
u8 XUartPs_GetOperMode(XUartPs *InstancePtr)
This function gets the operational mode of the UART.
The UART can operate in one of four modes: Normal, Local Loopback, Remote Loopback, or automatic echo. InstancePtr is a pointer to the XUartPs instance. The operational mode is specified by constants defined in xuartps.h. The constants are named XUARTPS_OPER_MODE_*None.
References XUartPs_Config::BaseAddress, XUARTPS_MR_CHMODE_ECHO, XUARTPS_MR_CHMODE_L_LOOP, XUARTPS_MR_CHMODE_MASK, XUARTPS_MR_CHMODE_NORM, XUARTPS_MR_CHMODE_R_LOOP, XUARTPS_MR_CHMODE_SHIFT, XUARTPS_MR_OFFSET, XUARTPS_OPER_MODE_AUTO_ECHO, XUARTPS_OPER_MODE_LOCAL_LOOP, XUARTPS_OPER_MODE_NORMAL, XUARTPS_OPER_MODE_REMOTE_LOOP, XUartPs_ReadReg.
void XUartPs_SetOperMode(XUartPs *InstancePtr, u8 OperationMode)
This function sets the operational mode of the UART.
The UART can operate in one of four modes: Normal, Local Loopback, Remote Loopback, or automatic echo. InstancePtr is a pointer to the XUartPs instance. OperationMode is the mode of the UART. None. None.
References XUartPs_Config::BaseAddress, XUARTPS_MR_CHMODE_ECHO, XUARTPS_MR_CHMODE_L_LOOP, XUARTPS_MR_CHMODE_MASK, XUARTPS_MR_CHMODE_NORM, XUARTPS_MR_CHMODE_R_LOOP, XUARTPS_MR_OFFSET, XUARTPS_OPER_MODE_AUTO_ECHO, XUARTPS_OPER_MODE_LOCAL_LOOP, XUARTPS_OPER_MODE_NORMAL, XUARTPS_OPER_MODE_REMOTE_LOOP, XUartPs_ReadReg, XUartPs_WriteReg.
Referenced by UartPsIntrExample, UartPsPolledExample.
u8 XUartPs_GetFlowDelay(XUartPs *InstancePtr)
This function sets the Flow Delay.
0 - 3: Flow delay inactive 4 - 32: If Flow Control mode is enabled, UART_rtsN is deactivated when the receive FIFO fills to this level. InstancePtr is a pointer to the XUartPs instance. The Flow Delay is specified by constants defined in xuartps_hw.h. The constants are named XUARTPS_FLOWDEL*None.
References XUartPs_Config::BaseAddress, XUARTPS_FLOWDEL_MASK, XUARTPS_FLOWDEL_OFFSET, XUartPs_ReadReg.
void XUartPs_SetFlowDelay(XUartPs *InstancePtr, u8 FlowDelayValue)
This function sets the Flow Delay.
0 - 3: Flow delay inactive 4 - 63: If Flow Control mode is enabled, UART_rtsN is deactivated when the receive FIFO fills to this level. InstancePtr is a pointer to the XUartPs instance. FlowDelayValue is the Setting for the flow delay. None. None.
References XUartPs_Config::BaseAddress, XUARTPS_FLOWDEL_MASK, XUARTPS_FLOWDEL_OFFSET, XUartPs_WriteReg.
u8 XUartPs_GetRecvTimeout(XUartPs *InstancePtr)
This function gets the Receive Timeout of the UART.
InstancePtr is a pointer to the XUartPs instance. The current setting for receive time out. None.
References XUartPs_Config::BaseAddress, XUartPs_ReadReg, XUARTPS_RXTOUT_MASK, XUARTPS_RXTOUT_OFFSET.
void XUartPs_SetRecvTimeout(XUartPs *InstancePtr, u8 RecvTimeout)
This function sets the Receive Timeout of the UART.
InstancePtr is a pointer to the XUartPs instance. RecvTimeout setting allows the UART to detect an idle connection on the receiver data line. Timeout duration = RecvTimeout x 4 x Bit Period. 0 disables the timeout function. None. None.
References XUartPs_Config::BaseAddress, XUARTPS_CR_OFFSET, XUARTPS_CR_TORST, XUartPs_ReadReg, XUARTPS_RXTOUT_MASK, XUARTPS_RXTOUT_OFFSET, XUartPs_WriteReg.
Referenced by UartPsIntrExample.
s32 XUartPs_SetDataFormat(XUartPs *InstancePtr, XUartPsFormat *FormatPtr)
Sets the data format for the device.
The data format includes the baud rate, number of data bits, number of stop bits, and parity. It is the caller's responsibility to ensure that the UART is not sending or receiving data when this function is called. InstancePtr is a pointer to the XUartPs instance. FormatPtr is a pointer to a format structure containing the data format to be set. XST_SUCCESS if the data format was successfully set.XST_UART_BAUD_ERROR indicates the baud rate could not be set because of the amount of error with the baud rate and the input clock frequency.XST_INVALID_PARAM if one of the parameters was not valid. The data types in the format type, data bits and parity, are 32 bit fields to prevent a compiler warning. The asserts in this function will cause a warning if these fields are bytes.
References XUartPs_Config::BaseAddress, XUartPsFormat::BaudRate, XUartPsFormat::DataBits, XUartPsFormat::Parity, XUartPsFormat::StopBits, XUARTPS_FORMAT_2_STOP_BIT, XUARTPS_FORMAT_6_BITS, XUARTPS_FORMAT_NO_PARITY, XUARTPS_MR_CHARLEN_MASK, XUARTPS_MR_CHARLEN_SHIFT, XUARTPS_MR_OFFSET, XUARTPS_MR_PARITY_MASK, XUARTPS_MR_PARITY_SHIFT, XUARTPS_MR_STOPMODE_MASK, XUARTPS_MR_STOPMODE_SHIFT, XUartPs_ReadReg, XUartPs_SetBaudRate, XUartPs_WriteReg.
void XUartPs_GetDataFormat(XUartPs *InstancePtr, XUartPsFormat *FormatPtr)
Gets the data format for the specified UART.
The data format includes the baud rate, number of data bits, number of stop bits, and parity. InstancePtr is a pointer to the XUartPs instance. FormatPtr is a pointer to a format structure that will contain the data format after this call completes. None. None.
References XUartPs_Config::BaseAddress, XUartPsFormat::BaudRate, XUartPsFormat::DataBits, XUartPsFormat::Parity, XUartPsFormat::StopBits, XUARTPS_MR_CHARLEN_MASK, XUARTPS_MR_CHARLEN_SHIFT, XUARTPS_MR_OFFSET, XUARTPS_MR_PARITY_MASK, XUARTPS_MR_PARITY_SHIFT, XUARTPS_MR_STOPMODE_MASK, XUARTPS_MR_STOPMODE_SHIFT, XUartPs_ReadReg.
u32 XUartPs_GetInterruptMask(XUartPs *InstancePtr)
This function gets the interrupt mask.
InstancePtr is a pointer to the XUartPs instance. The current interrupt mask. The mask indicates which interrupts are enabled. None.
References XUartPs_Config::BaseAddress, XUARTPS_IMR_OFFSET, XUartPs_ReadReg.
void XUartPs_SetInterruptMask(XUartPs *InstancePtr, u32 Mask)
This function sets the interrupt mask.
InstancePtr is a pointer to the XUartPs instance Mask contains the interrupts to be enabled or disabled. A '1' enables an interrupt, and a '0' disables. None. None.
References XUartPs_Config::BaseAddress, XUARTPS_IDR_OFFSET, XUARTPS_IER_OFFSET, XUARTPS_IXR_MASK, XUartPs_WriteReg.
Referenced by UartPsIntrExample.
void XUartPs_InterruptHandler(XUartPs *InstancePtr)
This function is the interrupt handler for the driver.
It must be connected to an interrupt system by the application such that it can be called when an interrupt occurs. InstancePtr contains a pointer to the driver instance None. None.
References XUartPs_Config::BaseAddress, XUARTPS_IMR_OFFSET, XUARTPS_ISR_OFFSET, XUARTPS_IXR_DMS, XUARTPS_IXR_FRAMING, XUARTPS_IXR_OVER, XUARTPS_IXR_PARITY, XUARTPS_IXR_RBRK, XUARTPS_IXR_RXEMPTY, XUARTPS_IXR_RXFULL, XUARTPS_IXR_RXOVR, XUARTPS_IXR_TOUT, XUARTPS_IXR_TXEMPTY, XUARTPS_IXR_TXFULL, XUartPs_ReadReg, XUartPs_WriteReg.
Referenced by UartPsIntrExample.
void XUartPs_SetHandler(XUartPs *InstancePtr, XUartPs_Handler FuncPtr, void *CallBackRef)
This function sets the handler that will be called when an event (interrupt) occurs that needs application's attention.
InstancePtr is a pointer to the XUartPs instance FuncPtr is the pointer to the callback function. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. None. There is no assert on the CallBackRef since the driver doesn't know what it is (nor should it)
Referenced by UartPsIntrExample.
s32 XUartPs_SelfTest(XUartPs *InstancePtr)
This function runs a self-test on the driver and hardware device.
This self test performs a local loopback and verifies data can be sent and received.The time for this test is proportional to the baud rate that has been set prior to calling this function.The mode and control registers are restored before return. InstancePtr is a pointer to the XUartPs instance XST_SUCCESS if the test was successful XST_UART_TEST_FAIL if the test failed looping back the data This function can hang if the hardware is not functioning properly.
References XUartPs_Config::BaseAddress, XUartPs_Config::RefClk, TIMEOUT_VAL, XUARTPS_IDR_OFFSET, XUARTPS_IER_OFFSET, XUARTPS_IMR_OFFSET, XUARTPS_IXR_MASK, XUARTPS_MR_CHMODE_L_LOOP, XUARTPS_MR_CHMODE_MASK, XUARTPS_MR_OFFSET, XUartPs_ReadReg, XUartPs_Recv, XUartPs_Send, XUARTPS_SR_OFFSET, XUARTPS_SR_RXEMPTY, XUartPs_WriteReg.
Referenced by UartPsIntrExample, UartPsPolledExample, UartPsSelfTestExample.
void XUartPs_SendByte(u32 BaseAddress, u8 Data)
This function sends one byte using the device.
This function operates in polled mode and blocks until the data has been put into the TX FIFO register. BaseAddress contains the base address of the device. Data contains the byte to be sent. None. None.
References XUARTPS_FIFO_OFFSET, XUartPs_IsTransmitFull, XUartPs_WriteReg.
u8 XUartPs_RecvByte(u32 BaseAddress)
This function receives a byte from the device.
It operates in polled mode and blocks until a byte has received. BaseAddress contains the base address of the device. The data byte received. None.
References XUARTPS_FIFO_OFFSET, XUartPs_IsReceiveData, XUartPs_ReadReg.
void XUartPs_ResetHw(u32 BaseAddress)
This function resets UART.
BaseAddress contains the base address of the device. None None.
References XUARTPS_BAUDDIV_OFFSET, XUARTPS_BAUDDIV_RESET_VAL, XUARTPS_BAUDGEN_OFFSET, XUARTPS_BAUDGEN_RESET_VAL, XUARTPS_CR_OFFSET, XUARTPS_CR_RX_DIS, XUARTPS_CR_RXRST, XUARTPS_CR_STOPBRK, XUARTPS_CR_TX_DIS, XUARTPS_CR_TXRST, XUARTPS_IDR_OFFSET, XUARTPS_ISR_OFFSET, XUARTPS_IXR_MASK, XUARTPS_MR_CHMODE_NORM, XUARTPS_MR_OFFSET, XUARTPS_RXTOUT_DISABLE, XUARTPS_RXTOUT_OFFSET, XUARTPS_RXWM_OFFSET, XUARTPS_RXWM_RESET_VAL, XUARTPS_TXWM_OFFSET, XUARTPS_TXWM_RESET_VAL, XUartPs_WriteReg.
void XUartPs_WaitTransmitDone(u32 BaseAddress)
This function waits for transmission to complete.
None None.
References XUartPs_IsTransmitActive, XUartPs_IsTransmitFifoEmpty.
static void ReceiveDataHandler(XUartPs *InstancePtr)
This function handles the interrupt when data is in RX FIFO.
InstancePtr is a pointer to the XUartPs instance None. None.
static void SendDataHandler(XUartPs *InstancePtr, u32 IsrStatus)
This function handles the interrupt when data has been sent, the transmit FIFO is empty (transmitter holding register).
InstancePtr is a pointer to the XUartPs instance IsrStatus is the register value for channel status register None. None.
static void ReceiveErrorHandler(XUartPs *InstancePtr, u32 IsrStatus)
static void ReceiveTimeoutHandler(XUartPs *InstancePtr)
This function handles the receive timeout interrupt.
This interrupt occurs whenever a number of bytes have been present in the RX FIFO and the receive data line has been idle for at lease 4 or more character times, (the timeout is set using XUartPs_SetrecvTimeout() function). InstancePtr is a pointer to the XUartPs instance None. None.
static void ModemHandler(XUartPs *InstancePtr)
This function handles modem interrupts.
It does not do any processing except to call the application handler to indicate a modem event. InstancePtr is a pointer to the XUartPs instance None. None.
XUARTPS_MAX_BAUD_ERROR_RATE
XUARTPS_H
XUARTPS_MAX_RATE
XUARTPS_MIN_RATE
XUARTPS_DFT_BAUDRATE
TIMEOUT_VAL
Wait for 1 sec in worst case.
Referenced by XUartPs_SelfTest, XUartPs_SetBaudRate.
XUartPs_GetChannelStatus
Get the UART Channel Status Register.
InstancePtr is a pointer to the XUartPs instance. The value read from the register. C-Style signature: u16 XUartPs_GetChannelStatus(XUartPs *InstancePtr)
XUartPs_GetModeControl
Get the UART Mode Control Register.
InstancePtr is a pointer to the XUartPs instance. The value read from the register. C-Style signature: u32 XUartPs_GetControl(XUartPs *InstancePtr)
XUartPs_SetModeControl
Set the UART Mode Control Register.
InstancePtr is a pointer to the XUartPs instance. RegisterValue is the value to be written to the register. None. C-Style signature: void XUartPs_SetModeControl(XUartPs *InstancePtr, u16 RegisterValue)
XUartPs_EnableUart
Enable the transmitter and receiver of the UART.
InstancePtr is a pointer to the XUartPs instance. None. C-Style signature: void XUartPs_EnableUart(XUartPs *InstancePtr)
Referenced by XUartPs_SetBaudRate.
XUartPs_DisableUart
Disable the transmitter and receiver of the UART.
InstancePtr is a pointer to the XUartPs instance. None. C-Style signature: void XUartPs_DisableUart(XUartPs *InstancePtr)
Referenced by XUartPs_SetBaudRate.
XUartPs_IsTransmitEmpty
Determine if the transmitter FIFO is empty.
InstancePtr is a pointer to the XUartPs instance. TRUE if a byte can be sentFALSE if the Transmitter Fifo is not empty C-Style signature: u32 XUartPs_IsTransmitEmpty(XUartPs InstancePtr)
XUARTPS_HW_H
XUARTPS_MEDEMSR_DCDX
XUARTPS_MEDEMSR_RIX
XUARTPS_MEDEMSR_DSRX
XUARTPS_MEDEMSR_CTSX
XUartPs_ReadReg
Read a UART register.
BaseAddress contains the base address of the device. RegOffset contains the offset from the base address of the device. The value read from the register. C-Style signature: u32 XUartPs_ReadReg(u32 BaseAddress, int RegOffset)
Referenced by UartPsEchoExample, XUartPs_CfgInitialize, XUartPs_GetDataFormat, XUartPs_GetFifoThreshold, XUartPs_GetFlowDelay, XUartPs_GetInterruptMask, XUartPs_GetModemStatus, XUartPs_GetOperMode, XUartPs_GetOptions, XUartPs_GetRecvTimeout, XUartPs_InterruptHandler, XUartPs_IsSending, XUartPs_Recv, XUartPs_RecvByte, XUartPs_SelfTest, XUartPs_SetBaudRate, XUartPs_SetDataFormat, XUartPs_SetOperMode, XUartPs_SetOptions, XUartPs_SetRecvTimeout.
XUartPs_WriteReg
Write a UART register.
BaseAddress contains the base address of the device. RegOffset contains the offset from the base address of the device. RegisterValue is the value to be written to the register. None. C-Style signature: void XUartPs_WriteReg(u32 BaseAddress, int RegOffset, u16 RegisterValue)
Referenced by UartPsEchoExample, XUartPs_CfgInitialize, XUartPs_InterruptHandler, XUartPs_Recv, XUartPs_ResetHw, XUartPs_SelfTest, XUartPs_Send, XUartPs_SendByte, XUartPs_SetBaudRate, XUartPs_SetDataFormat, XUartPs_SetFifoThreshold, XUartPs_SetFlowDelay, XUartPs_SetInterruptMask, XUartPs_SetOperMode, XUartPs_SetOptions, XUartPs_SetRecvTimeout.
XUartPs_IsReceiveData
Determine if there is receive data in the receiver and/or FIFO.
BaseAddress contains the base address of the device. TRUE if there is receive data, FALSE otherwise. C-Style signature: u32 XUartPs_IsReceiveData(u32 BaseAddress)
Referenced by UartPsEchoExample, XUartPs_RecvByte.
XUartPs_IsTransmitFull
Determine if a byte of data can be sent with the transmitter.
BaseAddress contains the base address of the device. TRUE if the TX FIFO is full, FALSE if a byte can be put in the FIFO. C-Style signature: u32 XUartPs_IsTransmitFull(u32 BaseAddress)
Referenced by UartPsEchoExample, XUartPs_SendByte.
XUartPs_IsTransmitFifoEmpty
Check if transmission FIFO is empty.
TRUE if the TX FIFO is empty, FALSE if Tx FIFO is not empty C-Style signature: u32 XUartPs_IsTransmitFifoEmpty(u32 BaseAddress)
Referenced by XUartPs_WaitTransmitDone.
XUartPs_IsTransmitActive
Check if transmission state machine is active.
TRUE if the TX state machine is active, FALSE if Tx state machine is In-active C-Style signature: u32 XUartPs_IsTransmitActive(u32 BaseAddress)
Referenced by XUartPs_WaitTransmitDone.
XUARTPS_NUM_OPTIONS
XUARTPS_TOTAL_BYTES