xuartps_intr.c
void Handler)(XUartPs *InstancePtr)
This function is the handler which performs processing to handle data events from the device.
It is called from an interrupt context. so the amount of processing should be minimal.This handler provides an example of how to handle data for the device and is application specific. CallBackRef contains a callback reference from the driver, in this case it is the instance pointer for the XUartPs driver. Event contains the specific kind of event that has occurred. EventData contains the number of bytes sent or received for sent and receive events. None. None.
static void ReceiveDataHandler(XUartPs *InstancePtr)
This function handles the interrupt when data is in RX FIFO.
InstancePtr is a pointer to the XUartPs instance None. None.
static void SendDataHandler(XUartPs *InstancePtr, u32 IsrStatus)
This function handles the interrupt when data has been sent, the transmit FIFO is empty (transmitter holding register).
InstancePtr is a pointer to the XUartPs instance IsrStatus is the register value for channel status register None. None.
static void ReceiveErrorHandler(XUartPs *InstancePtr, u32 IsrStatus)
static void ReceiveTimeoutHandler(XUartPs *InstancePtr)
This function handles the receive timeout interrupt.
This interrupt occurs whenever a number of bytes have been present in the RX FIFO and the receive data line has been idle for at lease 4 or more character times, (the timeout is set using XUartPs_SetrecvTimeout() function). InstancePtr is a pointer to the XUartPs instance None. None.
static void ModemHandler(XUartPs *InstancePtr)
This function handles modem interrupts.
It does not do any processing except to call the application handler to indicate a modem event. InstancePtr is a pointer to the XUartPs instance None. None.
u32 XUartPs_ReceiveBuffer(XUartPs *InstancePtr)
u32 XUartPs_SendBuffer(XUartPs *InstancePtr)
u32 XUartPs_GetInterruptMask(XUartPs *InstancePtr)
This function gets the interrupt mask.
InstancePtr is a pointer to the XUartPs instance. The current interrupt mask. The mask indicates which interrupts are enabled. None.
References XUartPs_Config::BaseAddress, XUARTPS_IMR_OFFSET, XUartPs_ReadReg.
void XUartPs_SetInterruptMask(XUartPs *InstancePtr, u32 Mask)
This function sets the interrupt mask.
InstancePtr is a pointer to the XUartPs instance Mask contains the interrupts to be enabled or disabled. A '1' enables an interrupt, and a '0' disables. None. None.
References XUartPs_Config::BaseAddress, XUARTPS_IDR_OFFSET, XUARTPS_IER_OFFSET, XUARTPS_IXR_MASK, XUartPs_WriteReg.
Referenced by UartPsIntrExample.
void XUartPs_SetHandler(XUartPs *InstancePtr, XUartPs_Handler FuncPtr, void *CallBackRef)
This function sets the handler that will be called when an event (interrupt) occurs that needs application's attention.
InstancePtr is a pointer to the XUartPs instance FuncPtr is the pointer to the callback function. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. None. There is no assert on the CallBackRef since the driver doesn't know what it is (nor should it)
Referenced by UartPsIntrExample.
void XUartPs_InterruptHandler(XUartPs *InstancePtr)
This function is the interrupt handler for the driver.
It must be connected to an interrupt system by the application such that it can be called when an interrupt occurs. InstancePtr contains a pointer to the driver instance None. None.
References XUartPs_Config::BaseAddress, XUARTPS_IMR_OFFSET, XUARTPS_ISR_OFFSET, XUARTPS_IXR_DMS, XUARTPS_IXR_FRAMING, XUARTPS_IXR_OVER, XUARTPS_IXR_PARITY, XUARTPS_IXR_RBRK, XUARTPS_IXR_RXEMPTY, XUARTPS_IXR_RXFULL, XUARTPS_IXR_RXOVR, XUARTPS_IXR_TOUT, XUARTPS_IXR_TXEMPTY, XUARTPS_IXR_TXFULL, XUartPs_ReadReg, XUartPs_WriteReg.
Referenced by UartPsIntrExample.