xuartps.c
XUARTPS_MAX_BAUD_ERROR_RATE
static void XUartPs_StubHandler(void *CallBackRef, u32 Event, u32 ByteCount)
This function is a stub handler that is the default handler such that if the application has not set the handler when interrupts are enabled, this function will be called.
CallBackRef is unused by this function. Event is unused by this function. ByteCount is unused by this function. None. None.
u32 XUartPs_SendBuffer(XUartPs *InstancePtr)
u32 XUartPs_ReceiveBuffer(XUartPs *InstancePtr)
s32 XUartPs_CfgInitialize(XUartPs *InstancePtr, XUartPs_Config *Config, u32 EffectiveAddr)
Initializes a specific XUartPs instance such that it is ready to be used.
The data format of the device is setup for 8 data bits, 1 stop bit, and no parity by default. The baud rate is set to a default value specified by Config->DefaultBaudRate if set, otherwise it is set to 19.2K baud. The receive FIFO threshold is set for 8 bytes. The default operating mode of the driver is polled mode. InstancePtr is a pointer to the XUartPs instance. Config is a reference to a structure containing information about a specific XUartPs driver. EffectiveAddr is the device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, pass in the physical address instead. - XST_SUCCESS if initialization was successful - XST_UART_BAUD_ERROR if the baud rate is not possible because the inputclock frequency is not divisible with an acceptable amount of error The default configuration for the UART after initialization is: 19,200 bps or XPAR_DFT_BAUDRATE if defined8 data bits1 stop bitno parityFIFO's are enabled with a receive threshold of 8 bytesThe RX timeout is enabled with a timeout of 1 (4 char times)All interrupts are disabled.
References XUartPs_Config::BaseAddress, XUartPs_Config::InputClockHz, XUartPs_Config::IntrId, XUartPs_Config::IntrParent, XUartPs_Config::ModemPinsConnected, XUartPs_Config::RefClk, XUARTPS_IDR_OFFSET, XUARTPS_IXR_MASK, XUARTPS_MR_CHARLEN_8_BIT, XUARTPS_MR_CHARLEN_MASK, XUARTPS_MR_OFFSET, XUARTPS_MR_PARITY_MASK, XUARTPS_MR_PARITY_NONE, XUARTPS_MR_STOPMODE_1_BIT, XUARTPS_MR_STOPMODE_MASK, XUartPs_ReadReg, XUARTPS_RXTOUT_OFFSET, XUARTPS_RXWM_OFFSET, XUartPs_SetBaudRate, XUartPs_WriteReg.
Referenced by UartPsHelloWorldExample, UartPsIntrExample, UartPsPolledExample, UartPsSelfTestExample.
u32 XUartPs_Send(XUartPs *InstancePtr, u8 *BufferPtr, u32 NumBytes)
This functions sends the specified buffer using the device in either polled or interrupt driven mode.
This function is non-blocking, if the device is busy sending data, it will return and indicate zero bytes were sent. Otherwise, it fills the TX FIFO as much as it can, and return the number of bytes sent.In a polled mode, this function will only send as much data as TX FIFO can buffer. The application may need to call it repeatedly to send the entire buffer.In interrupt mode, this function will start sending the specified buffer, then the interrupt handler will continue sending data until the entire buffer has been sent. A callback function, as specified by the application, will be called to indicate the completion of sending. InstancePtr is a pointer to the XUartPs instance. BufferPtr is pointer to a buffer of data to be sent. NumBytes contains the number of bytes to be sent. A value of zero will stop a previous send operation that is in progress in interrupt mode. Any data that was already put into the transmit FIFO will be sent. The number of bytes actually sent. The number of bytes is not asserted so that this function may be called with a value of zero to stop an operation that is already in progress.
References XUartPs_Config::BaseAddress, XUartPs_Config::RefClk, XUARTPS_IDR_OFFSET, XUARTPS_IXR_TXEMPTY, XUARTPS_IXR_TXFULL, XUartPs_WriteReg.
Referenced by UartPsHelloWorldExample, UartPsIntrExample, UartPsPolledExample, XUartPs_SelfTest.
u32 XUartPs_Recv(XUartPs *InstancePtr, u8 *BufferPtr, u32 NumBytes)
This function attempts to receive a specified number of bytes of data from the device and store it into the specified buffer.
This function works for both polled or interrupt driven modes. It is non-blocking.In a polled mode, this function will only receive the data already in the RX FIFO. The application may need to call it repeatedly to receive the entire buffer. Polled mode is the default mode of operation for the device.In interrupt mode, this function will start the receiving, if not the entire buffer has been received, the interrupt handler will continue receiving data until the entire buffer has been received. A callback function, as specified by the application, will be called to indicate the completion of the receiving or error conditions. InstancePtr is a pointer to the XUartPs instance BufferPtr is pointer to buffer for data to be received into NumBytes is the number of bytes to be received. A value of zero will stop a previous receive operation that is in progress in interrupt mode. The number of bytes received. The number of bytes is not asserted so that this function may be called with a value of zero to stop an operation that is already in progress.
References XUartPs_Config::BaseAddress, XUartPs_Config::RefClk, XUARTPS_IDR_OFFSET, XUARTPS_IER_OFFSET, XUARTPS_IMR_OFFSET, XUARTPS_IXR_MASK, XUartPs_ReadReg, XUartPs_WriteReg.
Referenced by UartPsIntrExample, UartPsPolledExample, XUartPs_SelfTest.
s32 XUartPs_SetBaudRate(XUartPs *InstancePtr, u32 BaudRate)
Sets the baud rate for the device.
Checks the input value for validity and also verifies that the requested rate can be configured to within the maximum error range specified by XUARTPS_MAX_BAUD_ERROR_RATE. If the provided rate is not possible, the current setting is unchanged. InstancePtr is a pointer to the XUartPs instance BaudRate to be set XST_SUCCESS if everything configured as expectedXST_UART_BAUD_ERROR if the requested rate is not available because there was too much error None.
References XUartPs_Config::BaseAddress, XUartPs_Config::InputClockHz, TIMEOUT_VAL, XUARTPS_BAUDDIV_OFFSET, XUARTPS_BAUDGEN_OFFSET, XUARTPS_CR_OFFSET, XUARTPS_CR_RXRST, XUARTPS_CR_TXRST, XUartPs_DisableUart, XUartPs_EnableUart, XUARTPS_MR_CLKSEL, XUARTPS_MR_OFFSET, XUartPs_ReadReg, XUartPs_WriteReg.
Referenced by UartPsHelloWorldExample, XUartPs_CfgInitialize, XUartPs_SetDataFormat.