xuartps_options.c
XUARTPS_NUM_OPTIONS
Mapping OptionsTable[][]
u16 XUartPs_GetOptions(XUartPs *InstancePtr)
Gets the options for the specified driver instance.
The options are implemented as bit masks such that multiple options may be enabled or disabled simultaneously. InstancePtr is a pointer to the XUartPs instance. The current options for the UART. The options are bit masks that are contained in the file xuartps.h and named XUARTPS_OPTION_*.None.
References XUartPs_Config::BaseAddress, XUartPs_ReadReg.
void XUartPs_SetOptions(XUartPs *InstancePtr, u16 Options)
Sets the options for the specified driver instance.
The options are implemented as bit masks such that multiple options may be enabled or disabled simultaneously.The GetOptions function may be called to retrieve the currently enabled options. The result is ORed in the desired new settings to be enabled and ANDed with the inverse to clear the settings to be disabled. The resulting value is then used as the options for the SetOption function call. InstancePtr is a pointer to the XUartPs instance. Options contains the options to be set which are bit masks contained in the file xuartps.h and named XUARTPS_OPTION_*. None. None.
References XUartPs_Config::BaseAddress, XUARTPS_CR_STOPBRK, XUARTPS_OPTION_SET_BREAK, XUartPs_ReadReg, XUartPs_WriteReg.
u8 XUartPs_GetFifoThreshold(XUartPs *InstancePtr)
This function gets the receive FIFO trigger level.
The receive trigger level indicates the number of bytes in the receive FIFO that cause a receive data event (interrupt) to be generated. InstancePtr is a pointer to the XUartPs instance. The current receive FIFO trigger level. This is a value from 0-31. None.
References XUartPs_Config::BaseAddress, XUartPs_ReadReg, XUARTPS_RXWM_MASK, XUARTPS_RXWM_OFFSET.
void XUartPs_SetFifoThreshold(XUartPs *InstancePtr, u8 TriggerLevel)
This functions sets the receive FIFO trigger level.
The receive trigger level specifies the number of bytes in the receive FIFO that cause a receive data event (interrupt) to be generated. InstancePtr is a pointer to the XUartPs instance. TriggerLevel contains the trigger level to set. None None.
References XUartPs_Config::BaseAddress, XUARTPS_RXWM_MASK, XUARTPS_RXWM_OFFSET, XUartPs_WriteReg.
u16 XUartPs_GetModemStatus(XUartPs *InstancePtr)
This function gets the modem status from the specified UART.
The modem status indicates any changes of the modem signals. This function allows the modem status to be read in a polled mode. The modem status is updated whenever it is read such that reading it twice may not yield the same results. InstancePtr is a pointer to the XUartPs instance. The modem status which are bit masks that are contained in the file xuartps.h and named XUARTPS_MODEM_*. The bit masks used for the modem status are the exact bits of the modem status register with no abstraction.
References XUartPs_Config::BaseAddress, XUARTPS_MODEMSR_OFFSET, XUartPs_ReadReg.
u32 XUartPs_IsSending(XUartPs *InstancePtr)
This function determines if the specified UART is sending data.
InstancePtr is a pointer to the XUartPs instance. TRUE if the UART is sending dataFALSE if UART is not sending data None.
References XUartPs_Config::BaseAddress, XUartPs_Config::RefClk, XUartPs_ReadReg, XUARTPS_SR_OFFSET, XUARTPS_SR_TACTIVE, XUARTPS_SR_TXEMPTY.
Referenced by UartPsPolledExample.
u8 XUartPs_GetOperMode(XUartPs *InstancePtr)
This function gets the operational mode of the UART.
The UART can operate in one of four modes: Normal, Local Loopback, Remote Loopback, or automatic echo. InstancePtr is a pointer to the XUartPs instance. The operational mode is specified by constants defined in xuartps.h. The constants are named XUARTPS_OPER_MODE_*None.
References XUartPs_Config::BaseAddress, XUARTPS_MR_CHMODE_ECHO, XUARTPS_MR_CHMODE_L_LOOP, XUARTPS_MR_CHMODE_MASK, XUARTPS_MR_CHMODE_NORM, XUARTPS_MR_CHMODE_R_LOOP, XUARTPS_MR_CHMODE_SHIFT, XUARTPS_MR_OFFSET, XUARTPS_OPER_MODE_AUTO_ECHO, XUARTPS_OPER_MODE_LOCAL_LOOP, XUARTPS_OPER_MODE_NORMAL, XUARTPS_OPER_MODE_REMOTE_LOOP, XUartPs_ReadReg.
void XUartPs_SetOperMode(XUartPs *InstancePtr, u8 OperationMode)
This function sets the operational mode of the UART.
The UART can operate in one of four modes: Normal, Local Loopback, Remote Loopback, or automatic echo. InstancePtr is a pointer to the XUartPs instance. OperationMode is the mode of the UART. None. None.
References XUartPs_Config::BaseAddress, XUARTPS_MR_CHMODE_ECHO, XUARTPS_MR_CHMODE_L_LOOP, XUARTPS_MR_CHMODE_MASK, XUARTPS_MR_CHMODE_NORM, XUARTPS_MR_CHMODE_R_LOOP, XUARTPS_MR_OFFSET, XUARTPS_OPER_MODE_AUTO_ECHO, XUARTPS_OPER_MODE_LOCAL_LOOP, XUARTPS_OPER_MODE_NORMAL, XUARTPS_OPER_MODE_REMOTE_LOOP, XUartPs_ReadReg, XUartPs_WriteReg.
Referenced by UartPsIntrExample, UartPsPolledExample.
u8 XUartPs_GetFlowDelay(XUartPs *InstancePtr)
This function sets the Flow Delay.
0 - 3: Flow delay inactive 4 - 32: If Flow Control mode is enabled, UART_rtsN is deactivated when the receive FIFO fills to this level. InstancePtr is a pointer to the XUartPs instance. The Flow Delay is specified by constants defined in xuartps_hw.h. The constants are named XUARTPS_FLOWDEL*None.
References XUartPs_Config::BaseAddress, XUARTPS_FLOWDEL_MASK, XUARTPS_FLOWDEL_OFFSET, XUartPs_ReadReg.
void XUartPs_SetFlowDelay(XUartPs *InstancePtr, u8 FlowDelayValue)
This function sets the Flow Delay.
0 - 3: Flow delay inactive 4 - 63: If Flow Control mode is enabled, UART_rtsN is deactivated when the receive FIFO fills to this level. InstancePtr is a pointer to the XUartPs instance. FlowDelayValue is the Setting for the flow delay. None. None.
References XUartPs_Config::BaseAddress, XUARTPS_FLOWDEL_MASK, XUARTPS_FLOWDEL_OFFSET, XUartPs_WriteReg.
u8 XUartPs_GetRecvTimeout(XUartPs *InstancePtr)
This function gets the Receive Timeout of the UART.
InstancePtr is a pointer to the XUartPs instance. The current setting for receive time out. None.
References XUartPs_Config::BaseAddress, XUartPs_ReadReg, XUARTPS_RXTOUT_MASK, XUARTPS_RXTOUT_OFFSET.
void XUartPs_SetRecvTimeout(XUartPs *InstancePtr, u8 RecvTimeout)
This function sets the Receive Timeout of the UART.
InstancePtr is a pointer to the XUartPs instance. RecvTimeout setting allows the UART to detect an idle connection on the receiver data line. Timeout duration = RecvTimeout x 4 x Bit Period. 0 disables the timeout function. None. None.
References XUartPs_Config::BaseAddress, XUARTPS_CR_OFFSET, XUARTPS_CR_TORST, XUartPs_ReadReg, XUARTPS_RXTOUT_MASK, XUARTPS_RXTOUT_OFFSET, XUartPs_WriteReg.
Referenced by UartPsIntrExample.
s32 XUartPs_SetDataFormat(XUartPs *InstancePtr, XUartPsFormat *FormatPtr)
Sets the data format for the device.
The data format includes the baud rate, number of data bits, number of stop bits, and parity. It is the caller's responsibility to ensure that the UART is not sending or receiving data when this function is called. InstancePtr is a pointer to the XUartPs instance. FormatPtr is a pointer to a format structure containing the data format to be set. XST_SUCCESS if the data format was successfully set.XST_UART_BAUD_ERROR indicates the baud rate could not be set because of the amount of error with the baud rate and the input clock frequency.XST_INVALID_PARAM if one of the parameters was not valid. The data types in the format type, data bits and parity, are 32 bit fields to prevent a compiler warning. The asserts in this function will cause a warning if these fields are bytes.
References XUartPs_Config::BaseAddress, XUartPsFormat::BaudRate, XUartPsFormat::DataBits, XUartPsFormat::Parity, XUartPsFormat::StopBits, XUARTPS_FORMAT_2_STOP_BIT, XUARTPS_FORMAT_6_BITS, XUARTPS_FORMAT_NO_PARITY, XUARTPS_MR_CHARLEN_MASK, XUARTPS_MR_CHARLEN_SHIFT, XUARTPS_MR_OFFSET, XUARTPS_MR_PARITY_MASK, XUARTPS_MR_PARITY_SHIFT, XUARTPS_MR_STOPMODE_MASK, XUARTPS_MR_STOPMODE_SHIFT, XUartPs_ReadReg, XUartPs_SetBaudRate, XUartPs_WriteReg.
void XUartPs_GetDataFormat(XUartPs *InstancePtr, XUartPsFormat *FormatPtr)
Gets the data format for the specified UART.
The data format includes the baud rate, number of data bits, number of stop bits, and parity. InstancePtr is a pointer to the XUartPs instance. FormatPtr is a pointer to a format structure that will contain the data format after this call completes. None. None.
References XUartPs_Config::BaseAddress, XUartPsFormat::BaudRate, XUartPsFormat::DataBits, XUartPsFormat::Parity, XUartPsFormat::StopBits, XUARTPS_MR_CHARLEN_MASK, XUARTPS_MR_CHARLEN_SHIFT, XUARTPS_MR_OFFSET, XUARTPS_MR_PARITY_MASK, XUARTPS_MR_PARITY_SHIFT, XUARTPS_MR_STOPMODE_MASK, XUARTPS_MR_STOPMODE_SHIFT, XUartPs_ReadReg.