xuartps_selftest.c
XUARTPS_TOTAL_BYTES
u8 TestString[XUARTPS_TOTAL_BYTES][XUARTPS_TOTAL_BYTES]
u8 ReturnString[XUARTPS_TOTAL_BYTES][XUARTPS_TOTAL_BYTES]
s32 XUartPs_SelfTest(XUartPs *InstancePtr)
This function runs a self-test on the driver and hardware device.
This self test performs a local loopback and verifies data can be sent and received.The time for this test is proportional to the baud rate that has been set prior to calling this function.The mode and control registers are restored before return. InstancePtr is a pointer to the XUartPs instance XST_SUCCESS if the test was successful XST_UART_TEST_FAIL if the test failed looping back the data This function can hang if the hardware is not functioning properly.
References XUartPs_Config::BaseAddress, XUartPs_Config::RefClk, TIMEOUT_VAL, XUARTPS_IDR_OFFSET, XUARTPS_IER_OFFSET, XUARTPS_IMR_OFFSET, XUARTPS_IXR_MASK, XUARTPS_MR_CHMODE_L_LOOP, XUARTPS_MR_CHMODE_MASK, XUARTPS_MR_OFFSET, XUartPs_ReadReg, XUartPs_Recv, XUartPs_Send, XUARTPS_SR_OFFSET, XUARTPS_SR_RXEMPTY, XUartPs_WriteReg.
Referenced by UartPsIntrExample, UartPsPolledExample, UartPsSelfTestExample.