xuartps_sinit.c
XUartPs_Config XUartPs_ConfigTable[][]
Each XUartPs device in the system has an entry in this table.
XUartPs_Config * XUartPs_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XUartPs_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xuartps.h for the definition of XUartPs_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XUartPs_Config::Name.
Referenced by UartPsHelloWorldExample, UartPsIntrExample, UartPsPolledExample, UartPsSelfTestExample.