rtcpsu
XRTCPSU_EVENT_ALARM_GEN
Alarm generated event.
Referenced by Handler, XRtcPsu_InterruptHandler.
XRTCPSU_EVENT_SECS_GEN
A new second generated event.
Referenced by XRtcPsu_InterruptHandler.
XRTC_SET_TIME_WR_OFFSET
Register: XrtcSetTimeWr.
XRTC_SET_TIME_WR_RSTVAL
XRTC_SET_TIME_WR_VAL_SHIFT
XRTC_SET_TIME_WR_VAL_WIDTH
XRTC_SET_TIME_WR_VAL_MASK
XRTC_SET_TIME_WR_VAL_DEFVAL
XRTC_SET_TIME_RD_OFFSET
Register: XrtcSetTimeRd.
XRTC_SET_TIME_RD_RSTVAL
XRTC_SET_TIME_RD_VAL_SHIFT
XRTC_SET_TIME_RD_VAL_WIDTH
XRTC_SET_TIME_RD_VAL_MASK
XRTC_SET_TIME_RD_VAL_DEFVAL
XRTC_CALIB_WR_OFFSET
Register: XrtcCalibWr.
Referenced by XRtcPsu_CfgInitialize.
XRTC_CALIB_WR_RSTVAL
XRTC_CALIB_WR_FRACTN_EN_SHIFT
XRTC_CALIB_WR_FRACTN_EN_WIDTH
XRTC_CALIB_WR_FRACTN_EN_MASK
XRTC_CALIB_WR_FRACTN_EN_DEFVAL
XRTC_CALIB_WR_FRACTN_DATA_SHIFT
XRTC_CALIB_WR_FRACTN_DATA_WIDTH
XRTC_CALIB_WR_FRACTN_DATA_MASK
XRTC_CALIB_WR_FRACTN_DATA_DEFVAL
XRTC_CALIB_WR_MAX_TCK_SHIFT
XRTC_CALIB_WR_MAX_TCK_WIDTH
XRTC_CALIB_WR_MAX_TCK_MASK
XRTC_CALIB_WR_MAX_TCK_DEFVAL
XRTC_CALIB_RD_OFFSET
Register: XrtcCalibRd.
XRTC_CALIB_RD_RSTVAL
XRTC_CALIB_RD_FRACTN_EN_SHIFT
XRTC_CALIB_RD_FRACTN_EN_WIDTH
XRTC_CALIB_RD_FRACTN_EN_MASK
XRTC_CALIB_RD_FRACTN_EN_DEFVAL
XRTC_CALIB_RD_FRACTN_DATA_SHIFT
XRTC_CALIB_RD_FRACTN_DATA_WIDTH
XRTC_CALIB_RD_FRACTN_DATA_MASK
XRTC_CALIB_RD_FRACTN_DATA_DEFVAL
XRTC_CALIB_RD_MAX_TCK_SHIFT
XRTC_CALIB_RD_MAX_TCK_WIDTH
XRTC_CALIB_RD_MAX_TCK_MASK
XRTC_CALIB_RD_MAX_TCK_DEFVAL
XRTC_CUR_TIME_OFFSET
Register: XrtcCurTime.
XRTC_CUR_TIME_RSTVAL
XRTC_CUR_TIME_VAL_SHIFT
XRTC_CUR_TIME_VAL_WIDTH
XRTC_CUR_TIME_VAL_MASK
XRTC_CUR_TIME_VAL_DEFVAL
XRTC_CUR_TCK_OFFSET
Register: XrtcCurTck.
XRTC_CUR_TCK_RSTVAL
XRTC_CUR_TCK_VAL_SHIFT
XRTC_CUR_TCK_VAL_WIDTH
XRTC_CUR_TCK_VAL_MASK
XRTC_CUR_TCK_VAL_DEFVAL
XRTC_ALRM_OFFSET
Register: XrtcAlrm.
Referenced by XRtcPsu_SetAlarm.
XRTC_ALRM_RSTVAL
XRTC_ALRM_VAL_SHIFT
XRTC_ALRM_VAL_WIDTH
XRTC_ALRM_VAL_MASK
XRTC_ALRM_VAL_DEFVAL
XRTC_INT_STS_OFFSET
Register: XrtcIntSts.
Referenced by XRtcPsu_CfgInitialize, XRtcPsu_GetCurrentTime, XRtcPsu_InterruptHandler, XRtcPsu_IsAlarmEventGenerated, XRtcPsu_IsSecondsEventGenerated, XRtcPsu_SetInterruptMask, XRtcPsu_SetTime.
XRTC_INT_STS_RSTVAL
XRTC_INT_STS_ALRM_SHIFT
XRTC_INT_STS_ALRM_WIDTH
XRTC_INT_STS_ALRM_MASK
XRTC_INT_STS_ALRM_DEFVAL
XRTC_INT_STS_SECS_SHIFT
XRTC_INT_STS_SECS_WIDTH
XRTC_INT_STS_SECS_MASK
XRTC_INT_STS_SECS_DEFVAL
XRTC_INT_MSK_OFFSET
Register: XrtcIntMsk.
Referenced by XRtcPsu_GetCurrentTime, XRtcPsu_InterruptHandler.
XRTC_INT_MSK_RSTVAL
XRTC_INT_MSK_ALRM_SHIFT
XRTC_INT_MSK_ALRM_WIDTH
XRTC_INT_MSK_ALRM_MASK
XRTC_INT_MSK_ALRM_DEFVAL
XRTC_INT_MSK_SECS_SHIFT
XRTC_INT_MSK_SECS_WIDTH
XRTC_INT_MSK_SECS_MASK
XRTC_INT_MSK_SECS_DEFVAL
XRTC_INT_EN_OFFSET
Register: XrtcIntEn.
Referenced by XRtcPsu_SetInterruptMask.
XRTC_INT_EN_RSTVAL
XRTC_INT_EN_ALRM_SHIFT
XRTC_INT_EN_ALRM_WIDTH
XRTC_INT_EN_ALRM_MASK
XRTC_INT_EN_ALRM_DEFVAL
XRTC_INT_EN_SECS_SHIFT
XRTC_INT_EN_SECS_WIDTH
XRTC_INT_EN_SECS_MASK
XRTC_INT_EN_SECS_DEFVAL
XRTC_INT_DIS_OFFSET
Register: XrtcIntDis.
Referenced by XRtcPsu_CfgInitialize, XRtcPsu_ClearInterruptMask.
XRTC_INT_DIS_RSTVAL
XRTC_INT_DIS_ALRM_SHIFT
XRTC_INT_DIS_ALRM_WIDTH
XRTC_INT_DIS_ALRM_MASK
XRTC_INT_DIS_ALRM_DEFVAL
XRTC_INT_DIS_SECS_SHIFT
XRTC_INT_DIS_SECS_WIDTH
XRTC_INT_DIS_SECS_MASK
XRTC_INT_DIS_SECS_DEFVAL
XRTC_ADD_ERR_OFFSET
Register: XrtcAddErr.
XRTC_ADD_ERR_RSTVAL
XRTC_ADD_ERR_STS_SHIFT
XRTC_ADD_ERR_STS_WIDTH
XRTC_ADD_ERR_STS_MASK
XRTC_ADD_ERR_STS_DEFVAL
XRTC_ADD_ERR_INT_MSK_OFFSET
Register: XrtcAddErrIntMsk.
XRTC_ADD_ERR_INT_MSK_RSTVAL
XRTC_ADD_ERR_INT_MSK_SHIFT
XRTC_ADD_ERR_INT_MSK_WIDTH
XRTC_ADD_ERR_INT_MSK_MASK
XRTC_ADD_ERR_INT_MSK_DEFVAL
XRTC_ADD_ERR_INT_EN_OFFSET
Register: XrtcAddErrIntEn.
XRTC_ADD_ERR_INT_EN_RSTVAL
XRTC_ADD_ERR_INT_EN_MSK_SHIFT
XRTC_ADD_ERR_INT_EN_MSK_WIDTH
XRTC_ADD_ERR_INT_EN_MSK_MASK
XRTC_ADD_ERR_INT_EN_MSK_DEFVAL
XRTC_ADD_ERR_INT_DIS_OFFSET
Register: XrtcAddErrIntDis.
XRTC_ADD_ERR_INT_DIS_RSTVAL
XRTC_ADD_ERR_INT_DIS_MSK_SHIFT
XRTC_ADD_ERR_INT_DIS_MSK_WIDTH
XRTC_ADD_ERR_INT_DIS_MSK_MASK
XRTC_ADD_ERR_INT_DIS_MSK_DEFVAL
XRTC_CTL_OFFSET
Register: XrtcCtl.
Referenced by XRtcPsu_CfgInitialize.
XRTC_CTL_RSTVAL
XRTC_CTL_BATTERY_EN_SHIFT
XRTC_CTL_BATTERY_EN_WIDTH
XRTC_CTL_BATTERY_EN_MASK
XRTC_CTL_BATTERY_EN_DEFVAL
XRTC_CTL_OSC_SHIFT
XRTC_CTL_OSC_WIDTH
XRTC_CTL_OSC_MASK
XRTC_CTL_OSC_DEFVAL
XRTC_CTL_SLVERR_EN_SHIFT
XRTC_CTL_SLVERR_EN_WIDTH
XRTC_CTL_SLVERR_EN_MASK
XRTC_CTL_SLVERR_EN_DEFVAL
XRTC_SFTY_CHK_OFFSET
Register: XrtcSftyChk.
Referenced by XRtcPsu_SelfTest.
XRTC_SFTY_CHK_RSTVAL
XRTC_SFTY_CHK_REG_SHIFT
XRTC_SFTY_CHK_REG_WIDTH
XRTC_SFTY_CHK_REG_MASK
XRTC_SFTY_CHK_REG_DEFVAL
XRTC_ECO_OFFSET
Register: XrtcEco.
XRTC_ECO_RSTVAL
XRTC_ECO_REG_SHIFT
XRTC_ECO_REG_WIDTH
XRTC_ECO_REG_MASK
XRTC_ECO_REG_DEFVAL
typedef void(* XRtcPsu_Handler)(void *CallBackRef, u32 Event))(void *CallBackRef, u32 Event)
This data type defines a handler that an application defines to communicate with interrupt system to retrieve state information about an application.
CallBackRef is a callback reference passed in by the upper layer when setting the handler, and is passed back to the upper layer when the handler is called. It is used to find the device driver instance. Event contains one of the event constants indicating events that have occurred.
const u32 DaysInMonth[][]
XRtcPsu_Config XRtcPsu_ConfigTable[][]
This table contains configuration information for RTC device in the system.
Referenced by XRtcPsu_LookupConfig.
XRtcPsu_Config XRtcPsu_ConfigTable[XPAR_XRTCPSU_NUM_INSTANCES][XPAR_XRTCPSU_NUM_INSTANCES]
This table contains configuration information for RTC device in the system.
Referenced by XRtcPsu_LookupConfig.
static void XRtcPsu_StubHandler(void *CallBackRef, u32 Event)
This function is a stub handler that is the default handler such that if the application has not set the handler when interrupts are enabled, this function will be called.
CallBackRef is unused by this function. Event is unused by this function. None. None.
s32 XRtcPsu_CfgInitialize(XRtcPsu *InstancePtr, XRtcPsu_Config *ConfigPtr, UINTPTR EffectiveAddr)
This function initializes a XRtcPsu instance/driver.
The initialization entails: Initialize all members of the XRtcPsu structure. InstancePtr is a pointer to the XRtcPsu instance. ConfigPtr points to the XRtcPsu device configuration structure. EffectiveAddr is the device base address in the virtual memory address space. If the address translation is not used then the physical address is passed. Unexpected errors may occur if the address mapping is changed after this function is invoked. XST_SUCCESS always. None.
References XRtcPsu_Config::BaseAddr, XRtcPsu::CalibrationValue, XRtcPsu::CurrTimeUpdated, XRtcPsu::Handler, XRtcPsu::IsPeriodicAlarm, XRtcPsu::IsReady, XRtcPsu::OscillatorFreq, XRtcPsu::RtcConfig, XRtcPsu::TimeUpdated, XRTC_CALIB_WR_OFFSET, XRTC_CALIBRATION_VALUE, XRTC_CTL_OFFSET, XRTC_INT_DIS_OFFSET, XRTC_INT_STS_OFFSET, XRTC_TYPICAL_OSC_FREQ, XRTCPSU_CRYSTAL_OSC_EN, XRtcPsu_ReadReg, XRtcPsu_WriteReg.
Referenced by RtcPsuAlarmIntrExample, RtcPsuAlarmPolledExample, RtcPsuPeriodicAlarmIntrExample, RtcPsuSecondsIntrExample, RtcPsuSecondsPolledExample, RtcPsuSetCalibrationExample, RtcPsuSetTimeExample.
void XRtcPsu_SetTime(XRtcPsu *InstancePtr, u32 Time)
This function sets the RTC time by writing into rtc write register.
InstancePtr is a pointer to the XRtcPsu instance. Time that should be updated into RTC write register. None. None.
References XRtcPsu_Config::BaseAddr, XRtcPsu::CurrTimeUpdated, XRtcPsu::RtcConfig, XRtcPsu::TimeUpdated, XRTC_INT_STS_OFFSET, XRtcPsu_WriteReg, XRtcPsu_WriteSetTime.
Referenced by RtcPsuSetCalibrationExample, RtcPsuSetTimeExample.
u32 XRtcPsu_GetCurrentTime(XRtcPsu *InstancePtr)
This function gets the current RTC time.
InstancePtr is a pointer to the XRtcPsu instance. RTC Current time. None.
References XRtcPsu_Config::BaseAddr, XRtcPsu::CurrTimeUpdated, XRtcPsu::RtcConfig, XRtcPsu::TimeUpdated, XRTC_INT_MSK_OFFSET, XRTC_INT_STS_OFFSET, XRtcPsu_GetLastSetTime, XRtcPsu_ReadCurrentTime, XRtcPsu_ReadReg.
Referenced by RtcPsuAlarmIntrExample, RtcPsuAlarmPolledExample, RtcPsuPeriodicAlarmIntrExample, RtcPsuSetTimeExample, XRtcPsu_CalculateCalibration, XRtcPsu_InterruptHandler, XRtcPsu_SetAlarm.
void XRtcPsu_SetAlarm(XRtcPsu *InstancePtr, u32 Alarm, u32 Periodic)
This function sets the alarm value of RTC device.
InstancePtr is a pointer to the XRtcPsu instance Alarm is the desired alarm time for RTC. Periodic says whether the alarm need to set at periodic Intervals or a one-time alarm. None. None.
References XRtcPsu_Config::BaseAddr, XRtcPsu::IsPeriodicAlarm, XRtcPsu::IsReady, XRtcPsu::PeriodicAlarmTime, XRtcPsu::RtcConfig, XRTC_ALRM_OFFSET, XRtcPsu_GetCurrentTime, XRtcPsu_WriteReg.
Referenced by RtcPsuAlarmIntrExample, RtcPsuAlarmPolledExample, RtcPsuPeriodicAlarmIntrExample, XRtcPsu_InterruptHandler.
void XRtcPsu_SecToDateTime(u32 Seconds, XRtcPsu_DT *dt)
This function translates time in seconds to a YEAR:MON:DAY HR:MIN:SEC format and saves it in the DT structure variable.
It also reports the weekday. Seconds is the time value that has to be shown in DateTime format. dt is the DateTime format variable that stores the translated time. None. This API uses Unix epoch (1970-01-01 00:00:00 UTC) as reference. Supports years from 1970 to 2106 (unsigned 32-bit limit). WEEKDAY CONVENTION: WeekDay field follows POSIX standard: 0=Sunday, 1=Monday, 2=Tuesday, 3=Wednesday, 4=Thursday, 5=Friday, 6=Saturday 1970-01-01 (epoch) was Thursday, so WeekDay = 4.For u32 input, overflow is impossible. Maximum timestamp (0xFFFFFFFF) correctly converts to 2106-02-07 06:28:15.
References XRtcPsu_DT::Day, EPOCH_WDAY, EPOCH_YEAR, XRtcPsu_DT::Hour, IS_LEAP_YEAR, XRtcPsu_DT::Min, XRtcPsu_DT::Month, XRtcPsu_DT::Sec, XRtcPsu_DT::WeekDay, XRtcPsu_DT::Year.
Referenced by RtcPsuAlarmIntrExample, RtcPsuAlarmPolledExample, RtcPsuPeriodicAlarmIntrExample, RtcPsuSetTimeExample.
u32 XRtcPsu_DateTimeToSec(XRtcPsu_DT *dt)
This function translates time in YEAR:MON:DAY HR:MIN:SEC format to seconds since Unix epoch (1970-01-01 00:00:00 UTC).
dt is a pointer to a DateTime format structure variable of time that has to be converted to seconds. Seconds value since Unix epoch (1970-01-01). This API uses Unix epoch (1970-01-01 00:00:00 UTC) as reference. Input must be in range 1970-2106. The input structure is not modified. This is the inverse of XRtcPsu_SecToDateTime().
References XRtcPsu_DT::Day, EPOCH_YEAR, XRtcPsu_DT::Hour, IS_LEAP_YEAR, XRtcPsu_DT::Min, XRtcPsu_DT::Month, XRtcPsu_DT::Sec, XRtcPsu_DT::Year.
Referenced by RtcPsuSetCalibrationExample, RtcPsuSetTimeExample.
void XRtcPsu_CalculateCalibration(XRtcPsu *InstancePtr, u32 TimeReal, u32 CrystalOscFreq)
This function calculates the calibration value depending on the actual realworld time and also helps in deriving new calibration value if the user wishes to change his oscillator frequency.
TimeReal should be the accurate reference time in seconds since Unix epoch (1970-01-01 00:00:00 UTC). This matches standard internet time sources (NTP, GPS, etc.) and can be used directly without conversion. InstancePtr is a pointer to the XRtcPsu instance. TimeReal is the actual realworld time in seconds since Unix epoch (1970-01-01). This can be obtained from network time protocols (NTP) or other accurate time sources. The value must be greater than the RTC's current time for calibration to work correctly. CrystalOscFreq is the Oscillator new frequency. If using the typical 32768Hz crystal, then input the same frequency value. None. After calculating the calibration register value, user / application must call CfgInitialize API again to apply the new calibration into effect.
References XRtcPsu::CalibrationValue, XRtcPsu::OscillatorFreq, XRtcPsu_GetCalibration, XRtcPsu_GetCurrentTime, XRtcPsu_GetLastSetTime, XRtcPsu_RoundOff.
Referenced by RtcPsuSetCalibrationExample.
u32 XRtcPsu_IsSecondsEventGenerated(XRtcPsu *InstancePtr)
This function returns the seconds event status by reading interrupt status register.
InstancePtr is a pointer to the XRtcPsu instance. Returns 1 if a new second event is generated.Else 0.. This API is used in polled mode operation of RTC. This also clears interrupt status seconds bit.
References XRtcPsu_Config::BaseAddr, XRtcPsu::RtcConfig, XRTC_INT_STS_OFFSET, XRtcPsu_ReadReg, XRtcPsu_WriteReg.
Referenced by RtcPsuSecondsPolledExample.
u32 XRtcPsu_IsAlarmEventGenerated(XRtcPsu *InstancePtr)
This function returns the alarm event status by reading interrupt status register.
InstancePtr is a pointer to the XRtcPsu instance. Returns 1 if the alarm event is generated.Else 0. This API is used in polled mode operation of RTC. This also clears interrupt status alarm bit.
References XRtcPsu_Config::BaseAddr, XRtcPsu::RtcConfig, XRTC_INT_STS_OFFSET, XRtcPsu_ReadReg, XRtcPsu_WriteReg.
Referenced by RtcPsuAlarmPolledExample.
void XRtcPsu_SetInterruptMask(XRtcPsu *InstancePtr, u32 Mask)
This function sets the interrupt mask.
InstancePtr is a pointer to the XRtcPsu instance Mask contains the interrupts to be enabled. A '1' enables an interrupt, and a '0' disables. None. None.
References XRtcPsu_Config::BaseAddr, XRtcPsu::RtcConfig, XRTC_INT_EN_OFFSET, XRTC_INT_STS_OFFSET, XRtcPsu_WriteReg.
Referenced by RtcPsuAlarmIntrExample, RtcPsuPeriodicAlarmIntrExample, RtcPsuSecondsIntrExample.
void XRtcPsu_ClearInterruptMask(XRtcPsu *InstancePtr, u32 Mask)
This function clears the interrupt mask.
InstancePtr is a pointer to the XRtcPsu instance Mask contains the interrupts to be disabled. A '1' enables an interrupt, and a '0' disables. None. None.
References XRtcPsu_Config::BaseAddr, XRtcPsu::RtcConfig, XRTC_INT_DIS_OFFSET, XRtcPsu_WriteReg.
Referenced by RtcPsuAlarmIntrExample, RtcPsuPeriodicAlarmIntrExample, RtcPsuSecondsIntrExample.
void XRtcPsu_InterruptHandler(XRtcPsu *InstancePtr)
This function is the interrupt handler for the driver.
It must be connected to an interrupt system by the application such that it can be called when an interrupt occurs. InstancePtr contains a pointer to the driver instance None. None.
References XRtcPsu_Config::BaseAddr, XRtcPsu::CallBackRef, XRtcPsu::CurrTimeUpdated, XRtcPsu::Handler, XRtcPsu::IsPeriodicAlarm, XRtcPsu::IsReady, XRtcPsu::PeriodicAlarmTime, XRtcPsu::RtcConfig, XRtcPsu::TimeUpdated, XRTC_INT_MSK_OFFSET, XRTC_INT_STS_OFFSET, XRTCPSU_EVENT_ALARM_GEN, XRTCPSU_EVENT_SECS_GEN, XRtcPsu_GetCurrentTime, XRtcPsu_ReadReg, XRtcPsu_SetAlarm, XRtcPsu_WriteReg.
Referenced by RtcPsuAlarmIntrExample, RtcPsuPeriodicAlarmIntrExample, RtcPsuSecondsIntrExample.
void XRtcPsu_SetHandler(XRtcPsu *InstancePtr, XRtcPsu_Handler FunctionPtr, void *CallBackRef)
This function sets the handler that will be called when an event (interrupt) occurs that needs application's attention.
InstancePtr is a pointer to the XRtcPsu instance FunctionPtr is the pointer to the callback function. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. None. There is no assert on the CallBackRef since the driver doesn't know what it is (nor should it)
References XRtcPsu::CallBackRef, XRtcPsu::Handler, XRtcPsu::IsReady.
Referenced by RtcPsuAlarmIntrExample, RtcPsuPeriodicAlarmIntrExample, RtcPsuSecondsIntrExample.
s32 XRtcPsu_SelfTest(XRtcPsu *InstancePtr)
This function runs a self-test on the driver and hardware device.
This self test writes reset value into safety check register and read backs the same. If mismatch offers, returns the failure. InstancePtr is a pointer to the XRtcPsu instance XST_SUCCESS if the test was successful This function can hang if the hardware is not functioning properly.
References XRtcPsu_Config::BaseAddr, XRtcPsu::IsReady, XRtcPsu::RtcConfig, XRTC_SFTY_CHK_OFFSET, XRtcPsu_ReadReg, XRtcPsu_WriteReg.
Referenced by RtcPsuAlarmIntrExample, RtcPsuAlarmPolledExample, RtcPsuPeriodicAlarmIntrExample, RtcPsuSecondsIntrExample, RtcPsuSecondsPolledExample, RtcPsuSetCalibrationExample, RtcPsuSetTimeExample.
XRtcPsu_Config * XRtcPsu_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XRtcPsu_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xrtcpsu.h for the definition of XRtcPsu_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XRtcPsu_Config::Name, XRtcPsu_ConfigTable.
Referenced by RtcPsuAlarmIntrExample, RtcPsuAlarmPolledExample, RtcPsuPeriodicAlarmIntrExample, RtcPsuSecondsIntrExample, RtcPsuSecondsPolledExample, RtcPsuSetCalibrationExample, RtcPsuSetTimeExample.
XRTC_H_
< prevent circular inclusions
by using protection macros
XRTCPSU_CRYSTAL_OSC_EN
Separate Mask for Crystal oscillator bit Enable.
Referenced by XRtcPsu_CfgInitialize.
EPOCH_YEAR
Unix epoch year (1970-01-01 00:00:00 UTC)
Referenced by XRtcPsu_DateTimeToSec, XRtcPsu_SecToDateTime.
EPOCH_WDAY
Weekday of epoch (0=Sun, 1=Mon, 2=Tue, 3=Wed, 4=Thu, 5=Fri, 6=Sat)
Referenced by XRtcPsu_SecToDateTime.
IS_LEAP_YEAR
Check if a year is a leap year using complete Gregorian calendar rules:
Divisible by 4: leap yearException: Divisible by 100: not a leap yearException to exception: Divisible by 400: leap year Examples: 2000 (leap), 2004 (leap), 2100 (not leap)
Referenced by XRtcPsu_DateTimeToSec, XRtcPsu_SecToDateTime.
XRTC_CALIBRATION_VALUE
Calibration value.
Referenced by XRtcPsu_CfgInitialize.
XRTC_TYPICAL_OSC_FREQ
Oscillator frequency.
Referenced by XRtcPsu_CfgInitialize.
XRtcPsu_WriteSetTime
This macro updates the current time of RTC device.
InstancePtr is a pointer to the XRtcPsu instance. Time is the desired time for RTC in seconds. None. C-Style signature: void XRtcPsu_SetTime(XRtcPsu *InstancePtr, u32 Time)
Referenced by XRtcPsu_SetTime.
XRtcPsu_GetLastSetTime
This macro returns the last set time of RTC device.
Whenever a reset happens, the last set time will be zeroth day first sec. InstancePtr is a pointer to the XRtcPsu instance. The last set time in seconds. C-Style signature: u32 XRtcPsu_GetLastSetTime(XRtcPsu *InstancePtr)
Referenced by RtcPsuSetTimeExample, XRtcPsu_CalculateCalibration, XRtcPsu_GetCurrentTime.
XRtcPsu_GetCalibration
This macro returns the calibration value of RTC device.
InstancePtr is a pointer to the XRtcPsu instance. Calibration value for RTC. C-Style signature: u32 XRtcPsu_GetCalibration(XRtcPsu *InstancePtr)
Referenced by XRtcPsu_CalculateCalibration.
XRtcPsu_ReadCurrentTime
This macro returns the current time of RTC device.
InstancePtr is a pointer to the XRtcPsu instance. Current Time. This current time will be in seconds. C-Style signature: u32 XRtcPsu_ReadCurrentTime(XRtcPsu *InstancePtr)
Referenced by XRtcPsu_GetCurrentTime.
XRtcPsu_SetControlRegister
This macro sets the control register value of RTC device.
InstancePtr is a pointer to the XRtcPsu instance. Value is the desired control register value for RTC. None. C-Style signature: void XRtcPsu_SetControlRegister(XRtcPsu *InstancePtr, u32 Value)
XRtcPsu_GetSafetyCheck
This macro returns the safety check register value of RTC device.
InstancePtr is a pointer to the XRtcPsu instance. Safety check register value. C-Style signature: u32 XRtcPsu_GetSafetyCheck(XRtcPsu *InstancePtr)
XRtcPsu_SetSafetyCheck
This macro sets the safety check register value of RTC device.
InstancePtr is a pointer to the XRtcPsu instance. Value is a safety check value to be written in register. None. C-Style signature: void XRtcPsu_SetSafetyCheck(XRtcPsu *InstancePtr, u32 Value)
XRtcPsu_ResetAlarm
This macro resets the alarm register.
InstancePtr is a pointer to the XRtcPsu instance. None. C-Style signature: u32 XRtcPsu_ResetAlarm(XRtcPsu *InstancePtr)
Referenced by RtcPsuPeriodicAlarmIntrExample.
XRtcPsu_RoundOff
This macro rounds off the given number.
Number is the one that needs to be rounded off.. The rounded off value of the input number. C-Style signature: u32 XRtcPsu_RoundOff(float Number)
Referenced by XRtcPsu_CalculateCalibration.
XRTC_HW_H_
< prevent circular inclusions
by using protection macros
XRTC_BASEADDR
Xrtc Base Address.
XRtcPsu_ReadReg
This macro reads the given register.
RegisterAddr is the register address in the address space of the RTC device. The 32-bit value of the register None.
Referenced by XRtcPsu_CfgInitialize, XRtcPsu_GetCurrentTime, XRtcPsu_InterruptHandler, XRtcPsu_IsAlarmEventGenerated, XRtcPsu_IsSecondsEventGenerated, XRtcPsu_SelfTest.
XRtcPsu_WriteReg
This macro writes the given register.
RegisterAddr is the register address in the address space of the RTC device. Data is the 32-bit value to write to the register. None. None.
Referenced by XRtcPsu_CfgInitialize, XRtcPsu_ClearInterruptMask, XRtcPsu_InterruptHandler, XRtcPsu_IsAlarmEventGenerated, XRtcPsu_IsSecondsEventGenerated, XRtcPsu_SelfTest, XRtcPsu_SetAlarm, XRtcPsu_SetInterruptMask, XRtcPsu_SetTime.