xrtcpsu_sinit.c
XRtcPsu_Config * XRtcPsu_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XRtcPsu_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xrtcpsu.h for the definition of XRtcPsu_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XRtcPsu_Config::Name, XRtcPsu_ConfigTable.
Referenced by RtcPsuAlarmIntrExample, RtcPsuAlarmPolledExample, RtcPsuPeriodicAlarmIntrExample, RtcPsuSecondsIntrExample, RtcPsuSecondsPolledExample, RtcPsuSetCalibrationExample, RtcPsuSetTimeExample.