xrtcpsu_intr.c
void XRtcPsu_SetInterruptMask(XRtcPsu *InstancePtr, u32 Mask)
This function sets the interrupt mask.
InstancePtr is a pointer to the XRtcPsu instance Mask contains the interrupts to be enabled. A '1' enables an interrupt, and a '0' disables. None. None.
References XRtcPsu_Config::BaseAddr, XRtcPsu::RtcConfig, XRTC_INT_EN_OFFSET, XRTC_INT_STS_OFFSET, XRtcPsu_WriteReg.
Referenced by RtcPsuAlarmIntrExample, RtcPsuPeriodicAlarmIntrExample, RtcPsuSecondsIntrExample.
void XRtcPsu_ClearInterruptMask(XRtcPsu *InstancePtr, u32 Mask)
This function clears the interrupt mask.
InstancePtr is a pointer to the XRtcPsu instance Mask contains the interrupts to be disabled. A '1' enables an interrupt, and a '0' disables. None. None.
References XRtcPsu_Config::BaseAddr, XRtcPsu::RtcConfig, XRTC_INT_DIS_OFFSET, XRtcPsu_WriteReg.
Referenced by RtcPsuAlarmIntrExample, RtcPsuPeriodicAlarmIntrExample, RtcPsuSecondsIntrExample.
void XRtcPsu_SetHandler(XRtcPsu *InstancePtr, XRtcPsu_Handler FunctionPtr, void *CallBackRef)
This function sets the handler that will be called when an event (interrupt) occurs that needs application's attention.
InstancePtr is a pointer to the XRtcPsu instance FunctionPtr is the pointer to the callback function. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. None. There is no assert on the CallBackRef since the driver doesn't know what it is (nor should it)
References XRtcPsu::CallBackRef, XRtcPsu::Handler, XRtcPsu::IsReady.
Referenced by RtcPsuAlarmIntrExample, RtcPsuPeriodicAlarmIntrExample, RtcPsuSecondsIntrExample.
void XRtcPsu_InterruptHandler(XRtcPsu *InstancePtr)
This function is the interrupt handler for the driver.
It must be connected to an interrupt system by the application such that it can be called when an interrupt occurs. InstancePtr contains a pointer to the driver instance None. None.
References XRtcPsu_Config::BaseAddr, XRtcPsu::CallBackRef, XRtcPsu::CurrTimeUpdated, XRtcPsu::Handler, XRtcPsu::IsPeriodicAlarm, XRtcPsu::IsReady, XRtcPsu::PeriodicAlarmTime, XRtcPsu::RtcConfig, XRtcPsu::TimeUpdated, XRTC_INT_MSK_OFFSET, XRTC_INT_STS_OFFSET, XRTCPSU_EVENT_ALARM_GEN, XRTCPSU_EVENT_SECS_GEN, XRtcPsu_GetCurrentTime, XRtcPsu_ReadReg, XRtcPsu_SetAlarm, XRtcPsu_WriteReg.
Referenced by RtcPsuAlarmIntrExample, RtcPsuPeriodicAlarmIntrExample, RtcPsuSecondsIntrExample.