xrtcpsu.c
const u32 DaysInMonth[][]
static void XRtcPsu_StubHandler(void *CallBackRef, u32 Event)
This function is a stub handler that is the default handler such that if the application has not set the handler when interrupts are enabled, this function will be called.
CallBackRef is unused by this function. Event is unused by this function. None. None.
s32 XRtcPsu_CfgInitialize(XRtcPsu *InstancePtr, XRtcPsu_Config *ConfigPtr, UINTPTR EffectiveAddr)
This function initializes a XRtcPsu instance/driver.
The initialization entails: Initialize all members of the XRtcPsu structure. InstancePtr is a pointer to the XRtcPsu instance. ConfigPtr points to the XRtcPsu device configuration structure. EffectiveAddr is the device base address in the virtual memory address space. If the address translation is not used then the physical address is passed. Unexpected errors may occur if the address mapping is changed after this function is invoked. XST_SUCCESS always. None.
References XRtcPsu_Config::BaseAddr, XRtcPsu::CalibrationValue, XRtcPsu::CurrTimeUpdated, XRtcPsu::Handler, XRtcPsu::IsPeriodicAlarm, XRtcPsu::IsReady, XRtcPsu::OscillatorFreq, XRtcPsu::RtcConfig, XRtcPsu::TimeUpdated, XRTC_CALIB_WR_OFFSET, XRTC_CALIBRATION_VALUE, XRTC_CTL_OFFSET, XRTC_INT_DIS_OFFSET, XRTC_INT_STS_OFFSET, XRTC_TYPICAL_OSC_FREQ, XRTCPSU_CRYSTAL_OSC_EN, XRtcPsu_ReadReg, XRtcPsu_WriteReg.
Referenced by RtcPsuAlarmIntrExample, RtcPsuAlarmPolledExample, RtcPsuPeriodicAlarmIntrExample, RtcPsuSecondsIntrExample, RtcPsuSecondsPolledExample, RtcPsuSetCalibrationExample, RtcPsuSetTimeExample.
void XRtcPsu_SetTime(XRtcPsu *InstancePtr, u32 Time)
This function sets the RTC time by writing into rtc write register.
InstancePtr is a pointer to the XRtcPsu instance. Time that should be updated into RTC write register. None. None.
References XRtcPsu_Config::BaseAddr, XRtcPsu::CurrTimeUpdated, XRtcPsu::RtcConfig, XRtcPsu::TimeUpdated, XRTC_INT_STS_OFFSET, XRtcPsu_WriteReg, XRtcPsu_WriteSetTime.
Referenced by RtcPsuSetCalibrationExample, RtcPsuSetTimeExample.
u32 XRtcPsu_GetCurrentTime(XRtcPsu *InstancePtr)
This function gets the current RTC time.
InstancePtr is a pointer to the XRtcPsu instance. RTC Current time. None.
References XRtcPsu_Config::BaseAddr, XRtcPsu::CurrTimeUpdated, XRtcPsu::RtcConfig, XRtcPsu::TimeUpdated, XRTC_INT_MSK_OFFSET, XRTC_INT_STS_OFFSET, XRtcPsu_GetLastSetTime, XRtcPsu_ReadCurrentTime, XRtcPsu_ReadReg.
Referenced by RtcPsuAlarmIntrExample, RtcPsuAlarmPolledExample, RtcPsuPeriodicAlarmIntrExample, RtcPsuSetTimeExample, XRtcPsu_CalculateCalibration, XRtcPsu_InterruptHandler, XRtcPsu_SetAlarm.
void XRtcPsu_SetAlarm(XRtcPsu *InstancePtr, u32 Alarm, u32 Periodic)
This function sets the alarm value of RTC device.
InstancePtr is a pointer to the XRtcPsu instance Alarm is the desired alarm time for RTC. Periodic says whether the alarm need to set at periodic Intervals or a one-time alarm. None. None.
References XRtcPsu_Config::BaseAddr, XRtcPsu::IsPeriodicAlarm, XRtcPsu::IsReady, XRtcPsu::PeriodicAlarmTime, XRtcPsu::RtcConfig, XRTC_ALRM_OFFSET, XRtcPsu_GetCurrentTime, XRtcPsu_WriteReg.
Referenced by RtcPsuAlarmIntrExample, RtcPsuAlarmPolledExample, RtcPsuPeriodicAlarmIntrExample, XRtcPsu_InterruptHandler.
void XRtcPsu_SecToDateTime(u32 Seconds, XRtcPsu_DT *dt)
This function translates time in seconds to a YEAR:MON:DAY HR:MIN:SEC format and saves it in the DT structure variable.
It also reports the weekday. Seconds is the time value that has to be shown in DateTime format. dt is the DateTime format variable that stores the translated time. None. This API uses Unix epoch (1970-01-01 00:00:00 UTC) as reference. Supports years from 1970 to 2106 (unsigned 32-bit limit). WEEKDAY CONVENTION: WeekDay field follows POSIX standard: 0=Sunday, 1=Monday, 2=Tuesday, 3=Wednesday, 4=Thursday, 5=Friday, 6=Saturday 1970-01-01 (epoch) was Thursday, so WeekDay = 4.For u32 input, overflow is impossible. Maximum timestamp (0xFFFFFFFF) correctly converts to 2106-02-07 06:28:15.
References XRtcPsu_DT::Day, EPOCH_WDAY, EPOCH_YEAR, XRtcPsu_DT::Hour, IS_LEAP_YEAR, XRtcPsu_DT::Min, XRtcPsu_DT::Month, XRtcPsu_DT::Sec, XRtcPsu_DT::WeekDay, XRtcPsu_DT::Year.
Referenced by RtcPsuAlarmIntrExample, RtcPsuAlarmPolledExample, RtcPsuPeriodicAlarmIntrExample, RtcPsuSetTimeExample.
u32 XRtcPsu_DateTimeToSec(XRtcPsu_DT *dt)
This function translates time in YEAR:MON:DAY HR:MIN:SEC format to seconds since Unix epoch (1970-01-01 00:00:00 UTC).
dt is a pointer to a DateTime format structure variable of time that has to be converted to seconds. Seconds value since Unix epoch (1970-01-01). This API uses Unix epoch (1970-01-01 00:00:00 UTC) as reference. Input must be in range 1970-2106. The input structure is not modified. This is the inverse of XRtcPsu_SecToDateTime().
References XRtcPsu_DT::Day, EPOCH_YEAR, XRtcPsu_DT::Hour, IS_LEAP_YEAR, XRtcPsu_DT::Min, XRtcPsu_DT::Month, XRtcPsu_DT::Sec, XRtcPsu_DT::Year.
Referenced by RtcPsuSetCalibrationExample, RtcPsuSetTimeExample.
void XRtcPsu_CalculateCalibration(XRtcPsu *InstancePtr, u32 TimeReal, u32 CrystalOscFreq)
This function calculates the calibration value depending on the actual realworld time and also helps in deriving new calibration value if the user wishes to change his oscillator frequency.
TimeReal should be the accurate reference time in seconds since Unix epoch (1970-01-01 00:00:00 UTC). This matches standard internet time sources (NTP, GPS, etc.) and can be used directly without conversion. InstancePtr is a pointer to the XRtcPsu instance. TimeReal is the actual realworld time in seconds since Unix epoch (1970-01-01). This can be obtained from network time protocols (NTP) or other accurate time sources. The value must be greater than the RTC's current time for calibration to work correctly. CrystalOscFreq is the Oscillator new frequency. If using the typical 32768Hz crystal, then input the same frequency value. None. After calculating the calibration register value, user / application must call CfgInitialize API again to apply the new calibration into effect.
References XRtcPsu::CalibrationValue, XRtcPsu::OscillatorFreq, XRtcPsu_GetCalibration, XRtcPsu_GetCurrentTime, XRtcPsu_GetLastSetTime, XRtcPsu_RoundOff.
Referenced by RtcPsuSetCalibrationExample.
u32 XRtcPsu_IsSecondsEventGenerated(XRtcPsu *InstancePtr)
This function returns the seconds event status by reading interrupt status register.
InstancePtr is a pointer to the XRtcPsu instance. Returns 1 if a new second event is generated.Else 0.. This API is used in polled mode operation of RTC. This also clears interrupt status seconds bit.
References XRtcPsu_Config::BaseAddr, XRtcPsu::RtcConfig, XRTC_INT_STS_OFFSET, XRtcPsu_ReadReg, XRtcPsu_WriteReg.
Referenced by RtcPsuSecondsPolledExample.
u32 XRtcPsu_IsAlarmEventGenerated(XRtcPsu *InstancePtr)
This function returns the alarm event status by reading interrupt status register.
InstancePtr is a pointer to the XRtcPsu instance. Returns 1 if the alarm event is generated.Else 0. This API is used in polled mode operation of RTC. This also clears interrupt status alarm bit.
References XRtcPsu_Config::BaseAddr, XRtcPsu::RtcConfig, XRTC_INT_STS_OFFSET, XRtcPsu_ReadReg, XRtcPsu_WriteReg.
Referenced by RtcPsuAlarmPolledExample.