xrtcpsu_selftest.c
s32 XRtcPsu_SelfTest(XRtcPsu *InstancePtr)
This function runs a self-test on the driver and hardware device.
This self test writes reset value into safety check register and read backs the same. If mismatch offers, returns the failure. InstancePtr is a pointer to the XRtcPsu instance XST_SUCCESS if the test was successful This function can hang if the hardware is not functioning properly.
References XRtcPsu_Config::BaseAddr, XRtcPsu::IsReady, XRtcPsu::RtcConfig, XRTC_SFTY_CHK_OFFSET, XRtcPsu_ReadReg, XRtcPsu_WriteReg.
Referenced by RtcPsuAlarmIntrExample, RtcPsuAlarmPolledExample, RtcPsuPeriodicAlarmIntrExample, RtcPsuSecondsIntrExample, RtcPsuSecondsPolledExample, RtcPsuSetCalibrationExample, RtcPsuSetTimeExample.