dprxss
XDpRxSs_In32
Input Operations.
XDpRxSs_Out32
Output Operations.
XDpRxSs_ReadReg
This macro reads a value from a DisplayPort Receiver Subsystem register.
A 32 bit read is performed. If the component is implemented in a smaller width, only the least significant data is read from the register. The most significant data will be read as 0. BaseAddress is the base address of the XDpRxSs core instance. RegOffset is the register offset of the register (defined at the top of this file). The 32-bit value of the register. C-style signature: u32 XDpRxSs_ReadReg(UINTPTR BaseAddress, u32 RegOffset)
Referenced by XDpRxSs_Get_Dec_Clk_Lock, XDpRxSs_GetLinkRate, XDpRxSs_GetVblank, XDpRxSs_GetVtotal, XDpRxSs_MaskAdaptiveIntr, XDpRxSs_ReportLinkInfo, XDpRxSs_ReportMsaInfo, XDpRxSs_SetAdaptiveSyncCaps, XDpRxSs_UnMaskAdaptiveIntr.
XDpRxSs_WriteReg
This macro writes a value to a DisplayPort Receiver Subsystem register.
A 32 bit write is performed. If the component is implemented in a smaller width, only the least significant data is written. BaseAddress is the base address of the XDpRxSs core instance. RegOffset is the register offset of the register (defined at the top of this file) to be written. Data is the 32-bit value to write into the register. None. C-style signature: void XDpRxSs_WriteReg(UINTPTR BaseAddress, u32 RegOffset, u32 Data)
Referenced by XDpRxSs_Get_Dec_Clk_Lock, XDpRxSs_MaskAdaptiveIntr, XDpRxSs_Reset, XDpRxSs_SetAdaptiveSyncCaps, XDpRxSs_UnMaskAdaptiveIntr.
XDpRxSs_HdcpProtocol
No content protection.
XDpRxSs_HandlerType
Video mode change event interrupt type for DisplayPort core.
typedef void(* XDpRxSs_Callback)(void *InstancePtr))(void *InstancePtr)
Callback type which represents the handler for events.
InstancePtr is a pointer to the XDpRxSs instance. None.
u8 GenEdid[128][128]
u8 GenDpcd[][]
XDpRxSs_SubCores DpRxSsSubCores[XPAR_XDPRXSS_NUM_INSTANCES][XPAR_XDPRXSS_NUM_INSTANCES]
static void DpRxSs_GetIncludedSubCores(XDpRxSs *InstancePtr, UINTPTR BaseAddress)
This function reports list of cores included in DisplayPort RX Subsystem.
InstancePtr is a pointer to the XDpRxSs core instance. None.
static void DpRxSs_PopulateDpRxPorts(XDpRxSs *InstancePtr)
This function sets up the downstream topology that will be used by the DisplayPort RX to respond to down requests coming from the TX.
Sinks equal to number of streams (each with its own global unique identifier) are exposed to LINK_ADDRESS sideband messages.The extended display identification data (EDID) will be set to a generic EDID (GenEdid) for each of the sinks. REMOTE_I2C_READ sideband messages on address 0x50 will be replied to with the contents set by XDp_RxSetIicMapEntry for 0x50.REMOTE_DPCD_READ sideband messages will be responded to with the contents set for the sink using XDp_RxSetDpcdMap. All sinks are given the a generic DPCD (GenDpcd).ENUM_PATH_RESOURCES sideband messages will be responded to with the value set by XDp_RxMstSetPbn (or 0 if the sink already has a stream allocated to it). InstancePtr is a pointer to the XDpRxSs core instance. None.
static void DpRxSs_EnableTrainingInterrupts(XDp *DpPtr)
This function enables all training related interrupts for the DisplayPort RX Subsystem.
DpPtr is a pointer to the XDp instance. This is a common operation used during initialization and after unplug events.
static void StubTp1Callback(void *InstancePtr)
This routine is a stub for the asynchronous training pattern 1 interrupt callback.
On initialization, training pattern 1 interrupt handler is set to this callback. It is considered as an training pattern 1 for this handler to be invoked. InstancePtr is a pointer to the XDpRxSs core instance. None.
static void StubTp2Callback(void *InstancePtr)
This routine is a stub for the asynchronous training pattern 2 interrupt callback.
On initialization, training pattern 2 interrupt handler is set to this callback. It is considered as an training pattern 2 for this handler to be invoked. InstancePtr is a pointer to the XDpRxSs core instance. None.
static void StubUnplugCallback(void *InstancePtr)
This routine is a stub for the asynchronous unplug interrupt callback.
On initialization, unplug interrupt handler is set to this callback. It is considered as an unplug for this handler to be invoked. InstancePtr is a pointer to the XDpRxSs core instance. None.
static void StubAccessLaneSetCallback(void *InstancePtr)
This routine is a stub for the asynchronous access lane set interrupt callback.
On initialization, access lane set interrupt handler is set to this callback. InstancePtr is a pointer to the XDpRxSs core instance. None.
static void XDpRxSs_StubTrainingDoneCallback(void *InstancePtr)
Stub callback function for DisplayPort training done event.
This function is called when DisplayPort link training is completed. It resets the Display Timing Generator (DTG) by disabling and then re-enabling it to ensure proper synchronization with the newly trained link parameters. InstancePtr Pointer to the XDpRxSs instance. Must be a valid pointer to an XDpRxSs structure, otherwise an assertion failure will occur. This is a static stub function intended to be used as a default callback handler for training done events. The function assumes the InstancePtr is properly initialized.
static void XDpRxSs_StubTrainingLostCallback(void *InstancePtr)
Stub callback function for handling training lost events in DisplayPort RX Subsystem.
This function serves as a default callback handler when DisplayPort link training is lost. It generates an HPD (Hot Plug Detect) interrupt and disables audio output to properly handle the loss of link training. InstancePtr Pointer to the XDpRxSs instance. This pointer is cast to XDpRxSs type internally and must not be NULL. None This function performs the following actions: Validates that the instance pointer is not NULL using assertionGenerates a 750us HPD interrupt pulse to signal the sourceDisables audio output in the DisplayPort RX Subsystem The InstancePtr parameter must be a valid pointer to an XDpRxSs structure, otherwise an assertion failure will occur in debug builds.
static void XDpRxSs_StubVBlankCallback(void *InstancePtr)
This function is the stub callback for VBlank interrupts.
Driver invokes user callback, then conditionally disables interrupt based on VBlankCount threshold to prevent excessive interrupts. InstancePtr is a pointer to the XDpRxSs core instance. Disables VBLANK interrupt after VBlankCount exceeds threshold.
static void XDpRxSs_StubInfoPacketCallback(void *InstancePtr)
This function is the stub callback for InfoPacket interrupts.
Driver invokes user callback which manages packet processing. InstancePtr is a pointer to the XDpRxSs core instance. User callback manages frame_count and interrupt disable logic.
static void XDpRxSs_StubPayloadAllocCallback(void *InstancePtr)
This function is the stub callback for Payload Allocation interrupts.
Driver enables ACT_RX interrupt after invoking user callback for MST setup. InstancePtr is a pointer to the XDpRxSs core instance. Enables ACT_RX interrupt for MST stream synchronization.
static void XDpRxSs_StubNoVideoCallback(void *InstancePtr)
This function is the stub callback for NoVideo interrupts.
Driver performs interrupt management operations before invoking user callback. InstancePtr is a pointer to the XDpRxSs core instance. Enables VBLANK and INFO_PKT interrupts needed after video loss.
static void XDpRxSs_Set_Dec_Clk(XDpRxSs *InstancePtr)
This function sets the decoder clock for the DP RX Subsystem.
InstancePtr is a pointer to the XDpRxSs instance. None.
u32 XDpRxSs_CfgInitialize(XDpRxSs *InstancePtr, XDpRxSs_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the DisplayPort Receiver Subsystem core.
This function must be called prior to using the core. Initialization of the core includes setting up the instance data and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the XDpRxSs core instance. CfgPtr points to the configuration structure associated with the DisplayPort RX Subsystem core. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_DEVICE_NOT_FOUND if sub-core not found.XST_FAILURE if sub-core initialization failed.XST_SUCCESS if XDpRxSs_CfgInitialize successful. None.
References XDpRxSs_Config::BaseAddress, XDpRxSs_UsrOpt::Bpc, XDpRxSs::clk_wiz_abs_addr, XDpRxSs_Config::ClkWizSubCore, XDpRxSs::Config, XDpRxSs_DpSubCore::DpConfig, XDpRxSs::DpPtr, XDpRxSs_Config::DpSubCore, XDpRxSs_Hdcp1xSubCore::Hdcp1xConfig, XDpRxSs_Config::Hdcp1xSubCore, XDpRxSs_Config::Hdcp22Enable, XDpRxSs_Config::HdcpEnable, XDpRxSs_Config::IicSubCore, XDpRxSs_Config::IncludeAxiIic, XDpRxSs_Config::IncludeClkWiz, XDpRxSs::IsReady, XDpRxSs_UsrOpt::LaneCount, XDpRxSs_UsrOpt::LinkRate, XDpRxSs_Config::MaxBpc, XDpRxSs_Config::MaxLaneCount, XDpRxSs_UsrOpt::MstSupport, XDpRxSs_Config::MstSupport, XDpRxSs_Config::NumMstStreams, XDpRxSs_UsrOpt::NumOfStreams, XDpRxSs_Config::TmrCtrSubCore, XDpRxSs::UsrOpt, XDPRXSS_DRV_HANDLER_DP_NO_VID_EVENT, XDPRXSS_DRV_HANDLER_DP_PWR_CHG_EVENT, XDPRXSS_DRV_HANDLER_DP_VID_EVENT, XDpRxSs_DrvNoVideoHandler, XDpRxSs_DrvPowerChangeHandler, XDpRxSs_DrvVideoHandler, XDPRXSS_HDCP_14, XDPRXSS_HDCP_22, XDPRXSS_LANE_COUNT_SET_4, XDPRXSS_LINK_BW_SET_810GBPS, XDpRxSs_SetCallBack, XDpRxSs_SetLaneCount, XDpRxSs_SetLinkRate, XDpRxSs_Start, XDPRXSS_TMRCTR_RST_VAL.
Referenced by DpRxSs_Main.
void XDpRxSs_Reset(XDpRxSs *InstancePtr)
This function resets the DisplayPort Receiver Subsystem including all sub-cores.
InstancePtr is a pointer to the XDpRxSs core instance. IIC needs to be reinitialized after reset.
References XDpRxSs::Config, XDpRxSs::DpPtr, XDpRxSs_Config::HdcpEnable, XDpRxSs_Config::IncludeAxiIic, XDpRxSs_WriteReg.
Referenced by Dp21RxSs_Pt_Setup.
u32 XDpRxSs_Start(XDpRxSs *InstancePtr)
This function starts the DisplayPort Receiver Subsystem including all sub-cores.
InstancePtr is a pointer to the XDpRxSs core instance. XST_SUCCESS, if DP RX Subsystem and its included sub-cores configured successfully.XST_FAILURE, otherwise. None.
References XDpRxSs::DpPtr, XDpRxSs_UsrOpt::MstSupport, XDpRxSs::UsrOpt.
Referenced by Dp21RxSs_Pt_Setup, XDpRxSs_CfgInitialize.
static void DpRxSs_SetEdid(XDpRxSs *InstancePtr)
This static function sets the EDID data to the EDID memory.
InstancePtr is a pointer to the XDpRxSs instance. None.
void XDpRxSs_Setup(XDpRxSs *InstancePtr, XDpRxSs_UserConfig *UserConfigPtr)
This function setup the DisplayPort Receiver Subsystem.
InstancePtr is a pointer to the XDpRxSs core instance. UserConfigPtr is a pointer to the XDpRxSs_UserConfig instance. None.
References XDpRxSs::DpPtr, DpRxSs_RxEnable, XDPRXSS_ALL_INTR_MASK, XDPRXSS_CHANNEL_CODING_OFFSET.
Referenced by DpRxSs_Main.
void DpRxSs_UpdatePrbsErrCouters(XDpRxSs *InstancePtr, u16 Lane0, u16 Lane1, u16 Lane2, u16 Lane3)
This function updates the PRBS error counters of DpRxss.
InstancePtr is a pointer to the XDpRxSs instance. Lane0 is PRBS error counter value of Lane0. Lane1 is PRBS error counter value of Lane1. Lane2 is PRBS error counter value of Lane2. Lane3 is PRBS error counter value of Lane3. None.
References XDpRxSs::DpPtr, XDPRXSS_DPC_L01_PRBS_CNTR_OFFSET, XDPRXSS_DPC_L23_PRBS_CNTR_OFFSET, XDPRXSS_DPC_LANE_PRBS_CNTR_VALID_MASK.
u32 XDpRxSs_SetLinkRate(XDpRxSs *InstancePtr, u8 LinkRate)
This function sets the data rate to be used by the DisplayPort RX Subsystem core.
InstancePtr is a pointer to the XDpRxSs instance. LinkRate is the rate at which link needs to be driven. XDPRXSS_LINK_BW_SET_162GBPS = 0x06(for a 1.62 Gbps data rate)XDPRXSS_LINK_BW_SET_270GBPS = 0x0A(for a 2.70 Gbps data rate)XDPRXSS_LINK_BW_SET_540GBPS = 0x14(for a 5.40 Gbps data rate) XST_SUCCESS if setting the new lane rate was successful.XST_FAILURE otherwise. None.
References XDpRxSs::DpPtr, XDpRxSs_UsrOpt::LinkRate, XDpRxSs::UsrOpt.
Referenced by Dp21RxSs_Pt_Setup, XDpRxSs_CfgInitialize.
u32 XDpRxSs_SetLaneCount(XDpRxSs *InstancePtr, u8 LaneCount)
This function sets the number of lanes to be used by DisplayPort RX Subsystem core.
InstancePtr is a pointer to the XDpRxSs instance. LaneCount is the number of lanes to be used. 1 = XDPRXSS_LANE_COUNT_SET_12 = XDPRXSS_LANE_COUNT_SET_24 = XDPRXSS_LANE_COUNT_SET_4 XST_SUCCESS if setting the new lane count was successful.XST_FAILURE otherwise. None.
References XDpRxSs::DpPtr, XDpRxSs_UsrOpt::LaneCount, XDpRxSs::UsrOpt, XDPRXSS_LANE_COUNT_SET_1, XDPRXSS_LANE_COUNT_SET_2, XDPRXSS_LANE_COUNT_SET_4.
Referenced by Dp21RxSs_Pt_Setup, XDpRxSs_CfgInitialize.
u32 XDpRxSs_ExposePort(XDpRxSs *InstancePtr, u8 Port)
This function allows the user to select number of ports to be exposed when replying to a LINK_ADDRESS sideband message and hides rest of the ports.
InstancePtr is a pointer to the XDpRxSs core instance. Port specifies the number of ports to be exposed within the range 1 to 4. XST_SUCCESS, if ports exposed successfully.XST_FAILURE, if exposing ports which are already exposed or ports are exceeding total number of stream supported by the system. Number of ports are equal to number of streams.
References XDpRxSs::Config, XDpRxSs::DpPtr, XDpRxSs_UsrOpt::MstSupport, XDpRxSs_Config::NumMstStreams, XDpRxSs_UsrOpt::NumOfStreams, XDpRxSs::UsrOpt.
u32 XDpRxSs_CheckLinkStatus(XDpRxSs *InstancePtr)
This function checks if the receiver's DisplayPort Configuration Data (DPCD) indicates that the receiver has achieved clock recovery, channel equalization, symbol lock, and interlane alignment for all lanes currently in use.
InstancePtr is a pointer to the XDpRxSs core instance. XST_SUCCESS if the RX device has achieved clock recovery, channel equalization, symbol lock, and interlane alignment.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_FAILURE otherwise. None.
References XDpRxSs::DpPtr.
void XDpRxSs_SetUserPixelWidth(XDpRxSs *InstancePtr, u8 UserPixelWidth)
This function configures the number of pixels output through the user data interface.
InstancePtr is a pointer to the XDpRxSs core instance. UserPixelWidth is the user pixel width to be configured. None.
References XDpRxSs::DpPtr.
u8 XDpRxss_GetBpc(XDpRxSs *InstancePtr, u8 Stream)
This function extracts the bits per color from MISC0 or VSC SDP packet based on whether reception of colorimetry information through VSC SDP packets or through MISC registers of the stream.
InstancePtr is a pointer to the XDpRxSs core instance. Stream is the stream number to make the calculations for. The bits per color for the stream. RX clock must be stable.
References XDpRxSs::DpPtr.
Referenced by XDpRxss_GetMsa.
u8 XDpRxss_GetInterlace(XDpRxSs *InstancePtr, u8 Stream)
This function extracts the incoming video stream is Progressive or Interlace mode.
InstancePtr is a pointer to the XDpRxSs core instance. Stream is the stream number to make the calculations for. Video timing is Progressive or Interlace. RX clock must be stable.
References XDpRxSs::DpPtr, XDP_RX_STREAM_MSA_OFFSET.
Referenced by XDpRxss_GetMsa, XDpRxSs_GetVideoStream.
u8 XDpRxss_GetColorComponent(XDpRxSs *InstancePtr, u8 Stream)
This function extracts the color component format from MISC0 or VSC SDP packet based on whether reception of colorimetry information through VSC SDP packets or through MISC registers of the stream.
InstancePtr is a pointer to the XDpRxSs core instance. Stream is the stream number to make the calculations for. The color component for the stream. RX clock must be stable.
References XDpRxSs::DpPtr.
Referenced by CalculateCRC, Dp21RxSs_Pt_CalculateCRC, XDpRxss_GetMsa.
u8 XDpRxss_GetColorimetry(XDpRxSs *InstancePtr, u8 Stream)
This function extracts the YCbCrColorimetry from MISC0 or VSC SDP packet based on whether reception of colorimetry information through VSC SDP packets or through MISC registers of the stream.
InstancePtr is a pointer to the XDpRxSs core instance. Stream is the stream number to make the calculations for. The colorimetry format for the stream. RX clock must be stable.
References XDpRxSs::DpPtr.
Referenced by XDpRxss_GetMsa.
u8 XDpRxss_GetDynamicRange(XDpRxSs *InstancePtr, u8 Stream)
This function extracts the dynamic range from MISC0 or VSC SDP packet based on whether reception of colorimetry information through VSC SDP packets or through MISC registers of the stream.
InstancePtr is a pointer to the XDpRxSs core instance. Stream is the stream number to make the calculations for. The dynamic range value for the stream. RX clock must be stable.
References XDpRxSs::DpPtr.
Referenced by XDpRxss_GetMsa.
XDp_MainStreamAttributes * XDpRxss_GetMsa(XDpRxSs *DpRxSsInst)
This function gives the main stream attributes (MSA).
DpRxSsInst is a pointer to the XDpRxSs instance. MSA Config structure
References XDpRxSs::Config, XDpRxSs::DpPtr, XDpRxSs::link_up_trigger, XDpRxSs_UsrOpt::LinkRate, XDpRxSs_Config::NumMstStreams, XDpRxSs::UsrOpt, XDP_RX_STREAM_MSA_OFFSET, XDpRxss_GetBpc, XDpRxss_GetColorComponent, XDpRxss_GetColorimetry, XDpRxss_GetDynamicRange, XDpRxss_GetInterlace.
Referenced by DpRxSs_Main, XDpRxSs_GetVideoStream.
int XDpRxSs_GetVideoStream(XDpRxSs *InstancePtr, XVidC_VideoStream *VideoStream, u8 Stream)
This function retrieves the VideoStream Parameters from the incoming video stream.
InstancePtr is a pointer to the XDpRxSs core instance. VideoStream Pointer to an XVidC_VideoStream structure that will be populated with the extracted video stream information for the requested stream. On success, this function updates (at minimum) the following fields: Timing, FrameRate, VmIdPixPerClk (derived from lane count)ColorDepth, ColorFormatId, ColorStd, DynamicRangeBaseFrameRate, BaseTiming, UncompressedTimingIsInterlaced Stream Stream is the stream number to get the Video data. SUCCESS when video data extraction is success
References XDpRxSs::DpPtr, XDpRxSs_UsrOpt::LaneCount, XDpRxSs::UsrOpt, XDpRxss_GetInterlace, XDpRxss_GetMsa.
u32 XDpRxSs_HandleDownReq(XDpRxSs *InstancePtr)
This function handles incoming sideband messages.
It will 1) Read the contents of the down request registers, 2) Delegate control depending on the request type, and 3) Send a down reply. InstancePtr is a pointer to the XDpRxSs core instance. XST_SUCCESS if the entire message was sent successfully.XST_DEVICE_NOT_FOUND if no device is connected.XST_ERROR_COUNT_MAX if sending one of the message fragments timed out.XST_FAILURE otherwise. None.
References XDpRxSs::DpPtr.
void XDpRxSs_HandleActRxInterrupts(XDpRxSs *InstancePtr)
This function handles ACT (Allocation Change Trigger) received interrupt.
It performs driver-level interrupt management for MST stream changes. InstancePtr is a pointer to the XDpRxSs core instance. This is a driver-level function that manages interrupt enables/disables when ACT sequence is received for MST payload allocation changes.
References XDpRxSs::DpPtr, XDpRxSs::IsReady, XDPRXSS_INTERRUPT1_MASK_MST_ALL.
void XDpRxSs_SetAdaptiveSyncCaps(XDpRxSs *InstancePtr, u32 Enable)
This function sets Adaptive-Sync capabilities to DisplayPort RX Subsystem.
InstancePtr is a pointer to the XDpRxSs instance. Enable is to enable/disable the Adaptive-Sync capabilities in DisplayPort Rx Subsystem None.
References XDpRxSs::DpPtr, XDpRxSs_ReadReg, XDpRxSs_WriteReg.
void XDpRxSs_MaskAdaptiveIntr(XDpRxSs *InstancePtr, u32 Mask)
This function masks the Adaptive-Sync interrupts from DisplayPort RX Subsystem.
InstancePtr is a pointer to the XDpRxSs instance. Mask is a variable contains of Masked value None.
References XDpRxSs::DpPtr, XDpRxSs_ReadReg, XDpRxSs_WriteReg.
void XDpRxSs_UnMaskAdaptiveIntr(XDpRxSs *InstancePtr, u32 Mask)
This function unmasks Adaptive-Sync interrupt from DisplayPort RX Subsystem.
InstancePtr is a pointer to the XDpRxSs instance. Mask to unmask None.
References XDpRxSs::DpPtr, XDpRxSs_ReadReg, XDpRxSs_WriteReg.
int XDpRxSs_GetVblank(XDpRxSs *InstancePtr, u8 Stream)
This function retrieves the current vblank value of the incoming video stream.
InstancePtr is a pointer to the XDpRxSs core instance. Stream Stream is the stream number to get the vblank. The current vblank value This function has to be called after assertion of Bit-30 of XDP_RX_INTERRUPT_CAUSE_2 register
References XDpRxSs::DpPtr, XDpRxSs_ReadReg.
int XDpRxSs_GetVtotal(XDpRxSs *InstancePtr, u8 Stream)
This function retrieves the current VTotal value of the incoming video stream.
InstancePtr is a pointer to the XDpRxSs core instance. Stream is the stream number to get the vtotal. Note: This function has to be called after assertion Bit-30 of XDP_RX_INTERRUPT_CAUSE_2 register The current VTotal value This function has to be called after assertion of Bit-30 of XDP_RX_INTERRUPT_CAUSE_2 register
References XDpRxSs::DpPtr, XDpRxSs_ReadReg.
int XDpRxSs_Get_Dec_Clk_Lock(XDpRxSs *InstancePtr)
This function waits for the decoder clock to lock.
InstancePtr is a pointer to the XDpRxSs instance. XST_SUCCESS if clock is locked, XST_FAILURE otherwise. None.
References XDpRxSs::clk_wiz_abs_addr, XCLK_WIZ_STATUS_OFFSET, XCLK_WIZ_STATUS_RETRY, XCLK_WIZ_STATUS_WAIT, XCLK_WIZ_SWRST_OFFSET, XCLK_WIZ_SWRST_VAL, XDpRxSs_ReadReg, XDpRxSs_WriteReg.
void XDpRxSs_MstEnable(XDpRxSs *InstancePtr, u8 Enable)
Enable/Disable MST mode.
InstancePtr is a pointer to the XDpRxSs instance. Enable is to Enable/Disable Mst mode. If Mst mode is disabled, DpRxss will be in SST mode.
References XDpRxSs::DpPtr.
Referenced by DpRxSs_Main.
u32 XDpRxSs_GetLinkRate(XDpRxSs *InstancePtr)
Get the current link rate from DPCD register.
InstancePtr is a pointer to the XDpRxSs instance. Link rate value read from DPCD_LINK_BW_SET register. None.
References XDpRxSs::DpPtr, XDPRXSS_DPCD_LINK_BW_SET, XDpRxSs_ReadReg.
Referenced by PrintLinkInfo.
XDpRxSs_Config * XDpRxSs_LookupConfig(UINTPTR BaseAddress)
This function returns a reference to an XDpRxSs_Config structure based on the core id, DeviceId.
The return value will refer to an entry in the device configuration table defined in the xdprxss_g.c file. DeviceId is the unique core ID of the XDpRxSs core for the lookup operation. XDpRxSs_LookupConfig returns a reference to a config record in the configuration table (in xdprxss_g.c) corresponding to DeviceId, or NULL if no match is found. None.
Referenced by DpRxSs_Main.
u32 XDpRxSs_GetDrvIndex(UINTPTR BaseAddress)
This function returns the Index number of config table using BaseAddress.
Base address of the instance Index number of the config table
void XDpRxSs_ReportCoreInfo(XDpRxSs *InstancePtr)
Reports information about the DisplayPort RX Subsystem cores.
This function reports list of sub-cores included in DisplayPort RX Subsystem. InstancePtr is a pointer to the XDpRxSs core instance. None.
References XDpRxSs_Config::ColorFormat, XDpRxSs::Config, XDpRxSs::DpPtr, XDpRxSs_Config::HdcpEnable, XDpRxSs_Config::IncludeAxiIic, XDpRxSs_Config::MaxBpc, XDpRxSs_Config::MaxLaneCount, XDpRxSs_Config::MaxNumAudioCh, XDpRxSs_UsrOpt::MstSupport, XDpRxSs_Config::MstSupport, XDpRxSs_Config::NumMstStreams, XDpRxSs_UsrOpt::NumOfStreams, XDpRxSs_Config::SecondaryChEn, XDpRxSs::UsrOpt.
Referenced by DpRxSs_Main.
void XDpRxSs_ReportLinkInfo(XDpRxSs *InstancePtr)
Reports information about the current link status.
This function prints the link status, selected resolution, link rate /lane count symbol error. InstancePtr is a pointer to the XDpRxSs core instance. None.
References XDpRxSs::DpPtr, XDpRxSs_ReadReg.
Referenced by Dp21RxSs_Pt_Setup, DpRxSs_Main.
void XDpRxSs_ReportMsaInfo(XDpRxSs *InstancePtr)
Reports Main Stream Attribute (MSA) information.
This function prints the current main stream attributes from the DisplayPort RX core. InstancePtr is a pointer to the XDpRxSs core instance. None.
References XDpRxSs::Config, XDpRxSs::DpPtr, XDpRxSs_Config::NumMstStreams, XDpRxSs_ReadReg.
Referenced by Dp21RxSs_Pt_Setup, DpRxSs_Main.
void XDpRxSs_ReportDp159BitErrCount(XDpRxSs *InstancePtr)
Reports DP159 bit error count.
InstancePtr is a pointer to the XDpRxSs core instance.
void XDpRxSs_ReportHdcpInfo(XDpRxSs *InstancePtr)
Reports HDCP information and status.
This function prints the debug display info of the HDCP interface. InstancePtr is a pointer to the XDpRxSs core instance. None.
Referenced by Dp21RxSs_Pt_Setup.
u32 XDpRxSs_SelfTest(XDpRxSs *InstancePtr)
Runs a self-test on the DisplayPort RX Subsystem.
This function performs self test on DisplayPort Receiver Subsystem sub-cores. InstancePtr is a pointer to the XDpRxSs core instance. XST_SUCCESS if self test passed.Otherwise, prints self test failed message. None.
References XDpRxSs::Config, XDpRxSs::DpPtr, XDpRxSs_Config::HdcpEnable, XDpRxSs_Config::IncludeAxiIic.
void XDpRxSs_DpIntrHandler(void *InstancePtr)
This function is the interrupt handler for the DisplayPort RX core operating in RX mode.
The application is responsible for connecting this function to the interrupt system. Application beyond this driver is also responsible for providing callbacks to handle interrupts and installing the callbacks using XDpRxSs_SetCallBack() during initialization phase. InstancePtr is a pointer to the XDpRxSs core instance that just interrupted. None.
References XDpRxSs::DpPtr, XDpRxSs::IsReady.
Referenced by Dp21RxSs_Pt_SetupIntrSystem, DpSs_SetupIntrSystem.
u32 XDpRxSs_SetCallBack(XDpRxSs *InstancePtr, u32 HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function Type ---------------------------------------- ----------------------------------- XDPRXSS_HANDLER_DP_VM_CHG_EVENT XDp_RxSetIntrVmChangeHandler XDPRXSS_HANDLER_DP_PWR_CHG_EVENT XDp_RxSetIntrPowerStateHandler XDPRXSS_HANDLER_DP_NO_VID_EVENT XDp_RxSetIntrNoVideoHandler XDPRXSS_HANDLER_DP_VBLANK_EVENT XDp_RxSetIntrVBlankHandler XDPRXSS_HANDLER_DP_TLOST_EVENT XDp_RxSetIntrTrainingLostHandler XDPRXSS_HANDLER_DP_VID_EVENT XDp_RxSetIntrVideoHandler XDPRXSS_HANDLER_DP_INFO_PKT_EVENT XDp_RxSetIntrInfoPktHandler XDPRXSS_HANDLER_DP_EXT_PKT_EVENT XDp_RxSetIntrExtPktHandler XDPRXSS_HANDLER_DP_TDONE_EVENT XDp_RxSetIntrTrainingDoneHandler XDPRXSS_HANDLER_DP_BW_CHG_EVENT XDp_RxSetIntrBwChangeHandler XDPRXSS_HANDLER_DP_DWN_REQ_EVENT XDp_RxSetIntrDownReqHandler XDPRXSS_HANDLER_DP_DWN_REP_EVENT XDp_RxSetIntrDownReplyHandler XDPRXSS_HANDLER_DP_AUD_OVRFLW_EVENT XDp_RxSetIntrAudioOverHandler XDPRXSS_HANDLER_DP_PAYLOAD_ALLOC_EVENT XDp_RxSetIntrPayloadAllocHandler XDPRXSS_HANDLER_DP_ACT_RX_EVENT XDp_RxSetIntrActRxHandler XDPRXSS_HANDLER_DP_CRC_TEST_EVENT XDp_RxSetIntrCrcTestHandler XDPRXSS_HANDLER_HDCP_RPTR_TDSA_EVENT XHdcp1x_SetCallBack XDPRXSS_HANDLER_UNPLUG_EVENT UnplugCallback XDPRXSS_HANDLER_LINKBW_EVENT LinkBwCallback XDPRXSS_HANDLER_PLL_RESET_EVENT PllResetCallback InstancePtr is a pointer to the XDpRxSs core instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XDpRxSs::DpPtr, XDpRxSs::IsReady, XDpRxSs::LinkBwCallback, XDpRxSs::LinkBwRef, XDpRxSs::PllResetCallback, XDpRxSs::PllResetRef, XDpRxSs::UnplugCallback, XDpRxSs::UnplugRef, XDPRXSS_DRV_HANDLER_DP_NO_VID_EVENT, XDPRXSS_DRV_HANDLER_DP_PWR_CHG_EVENT, XDPRXSS_DRV_HANDLER_DP_VID_EVENT, XDPRXSS_HANDLER_DP_ACT_RX_EVENT, XDPRXSS_HANDLER_DP_AUD_OVRFLW_EVENT, XDPRXSS_HANDLER_DP_BW_CHG_EVENT, XDPRXSS_HANDLER_DP_CRC_TEST_EVENT, XDPRXSS_HANDLER_DP_DWN_REP_EVENT, XDPRXSS_HANDLER_DP_DWN_REQ_EVENT, XDPRXSS_HANDLER_DP_EXT_PKT_EVENT, XDPRXSS_HANDLER_DP_EXT_PKT_STREAM_2_EVENT, XDPRXSS_HANDLER_DP_EXT_PKT_STREAM_3_EVENT, XDPRXSS_HANDLER_DP_EXT_PKT_STREAM_4_EVENT, XDPRXSS_HANDLER_DP_INFO_PKT_EVENT, XDPRXSS_HANDLER_DP_INFO_PKT_STREAM_2_EVENT, XDPRXSS_HANDLER_DP_INFO_PKT_STREAM_3_EVENT, XDPRXSS_HANDLER_DP_INFO_PKT_STREAM_4_EVENT, XDPRXSS_HANDLER_DP_NO_VID_EVENT, XDPRXSS_HANDLER_DP_NO_VID_STREAM_2_EVENT, XDPRXSS_HANDLER_DP_NO_VID_STREAM_3_EVENT, XDPRXSS_HANDLER_DP_NO_VID_STREAM_4_EVENT, XDPRXSS_HANDLER_DP_PAYLOAD_ALLOC_EVENT, XDPRXSS_HANDLER_DP_PWR_CHG_EVENT, XDPRXSS_HANDLER_DP_TDONE_EVENT, XDPRXSS_HANDLER_DP_TLOST_EVENT, XDPRXSS_HANDLER_DP_VBLANK_EVENT, XDPRXSS_HANDLER_DP_VBLANK_STREAM_2_EVENT, XDPRXSS_HANDLER_DP_VBLANK_STREAM_3_EVENT, XDPRXSS_HANDLER_DP_VBLANK_STREAM_4_EVENT, XDPRXSS_HANDLER_DP_VID_EVENT, XDPRXSS_HANDLER_DP_VID_STREAM_2_EVENT, XDPRXSS_HANDLER_DP_VID_STREAM_3_EVENT, XDPRXSS_HANDLER_DP_VID_STREAM_4_EVENT, XDPRXSS_HANDLER_DP_VM_CHG_EVENT, XDPRXSS_HANDLER_DP_VM_CHG_STREAM_2_EVENT, XDPRXSS_HANDLER_DP_VM_CHG_STREAM_3_EVENT, XDPRXSS_HANDLER_DP_VM_CHG_STREAM_4_EVENT, XDPRXSS_HANDLER_LINKBW_EVENT, XDPRXSS_HANDLER_PLL_RESET_EVENT, XDPRXSS_HANDLER_UNPLUG_EVENT.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_CfgInitialize, XDpRxSs_SetUserCallBackHandlers.
void XDpRxSs_SetUserTimerHandler(XDpRxSs *InstancePtr, XDpRxSs_TimerHandler CallbackFunc, void *CallbackRef)
This function installs a custom delay/sleep function to be used by the DisplayPort RX Subsystem.
InstancePtr is a pointer to the XDpRxSs core instance. CallbackFunc is the address to the callback function. CallbackRef is the user data item (microseconds to delay) that will be passed to the custom sleep/delay function when it is invoked. None.
References XDpRxSs::DpPtr.
Referenced by DpRxSs_SetupIntrSystem.
void XDpRxSs_DrvNoVideoHandler(void *InstancePtr)
This function is the interrupt handler for No Video.
InstancePtr is a pointer to the XDpRxSs core instance that just interrupted. None.
References XDpRxSs::DpPtr, XDpRxSs::IsReady.
Referenced by XDpRxSs_CfgInitialize.
void XDpRxSs_DrvVideoHandler(void *InstancePtr)
This function is for the video interrupt handler.
InstancePtr is a pointer to the XDpRxSs core instance that just interrupted. None.
References XDpRxSs::DpPtr, XDpRxSs::IsReady.
Referenced by XDpRxSs_CfgInitialize.
void XDpRxSs_DrvPowerChangeHandler(void *InstancePtr)
This function is for the power change interrupt handler.
InstancePtr is a pointer to the XDpRxSs core instance that just interrupted. None.
References XDpRxSs::DpPtr, XDpRxSs::IsReady.
Referenced by XDpRxSs_CfgInitialize.
EDID_IIC_ADDRESS
EDID IIC slave address.
EDID_SIZE_BYTES
EDID total size in bytes.
EDID_BLOCK_SIZE
EDID block size.
EDID_WORD_SIZE
EDID word size in bytes.
XCLK_WIZ_SWRST_OFFSET
Clock Wizard software reset register offset.
Referenced by XDpRxSs_Get_Dec_Clk_Lock.
XCLK_WIZ_SWRST_VAL
Clock Wizard software reset value.
Referenced by XDpRxSs_Get_Dec_Clk_Lock.
XCLK_WIZ_STATUS_OFFSET
Clock Wizard status register offset.
Referenced by XDpRxSs_Get_Dec_Clk_Lock.
XCLK_WIZ_ISR_OFFSET
Clock Wizard interrupt status register offset.
XCLK_WIZ_IER_OFFSET
Clock Wizard interrupt enable register offset.
XCLK_WIZ_RECONFIG_OFFSET
Clock Wizard reconfiguration register offset.
XCLK_WIZ_RECONFIG_VAL
Clock Wizard reconfiguration value.
XCLK_WIZ_REG1_OFFSET
Clock Wizard register 1 offset.
XCLK_WIZ_REG2_OFFSET
Clock Wizard register 2 offset.
XCLK_WIZ_REG3_OFFSET
Clock Wizard register 3 offset.
XCLK_WIZ_REG4_OFFSET
Clock Wizard register 4 offset.
XCLK_WIZ_REG12_OFFSET
Clock Wizard register 12 offset.
XCLK_WIZ_REG13_OFFSET
Clock Wizard register 13 offset.
XCLK_WIZ_REG11_OFFSET
Clock Wizard register 11 offset.
XCLK_WIZ_REG11_VAL
Clock Wizard register 11 value.
XCLK_WIZ_REG14_OFFSET
Clock Wizard register 14 offset.
XCLK_WIZ_REG14_VAL
Clock Wizard register 14 value.
XCLK_WIZ_REG15_OFFSET
Clock Wizard register 15 offset.
XCLK_WIZ_REG15_VAL
Clock Wizard register 15 value.
XCLK_WIZ_REG16_OFFSET
Clock Wizard register 16 offset.
XCLK_WIZ_REG16_VAL
Clock Wizard register 16 value.
XCLK_WIZ_REG17_OFFSET
Clock Wizard register 17 offset.
XCLK_WIZ_REG17_VAL
Clock Wizard register 17 value.
XCLK_WIZ_REG19_OFFSET
Clock Wizard register 19 offset.
XCLK_WIZ_REG25_OFFSET
Clock Wizard register 25 offset.
XCLK_WIZ_REG26_OFFSET
Clock Wizard register 26 offset.
XCLK_WIZ_REG26_VAL
Clock Wizard register 26 value.
XCLK_WIZ_LOCK
Clock Wizard lock bit.
XCLK_WIZ_REG3_PREDIV2
Clock Wizard register 3 pre-divider 2 bit.
XCLK_WIZ_REG3_USED
Clock Wizard register 3 used bit.
XCLK_WIZ_REG3_MX
Clock Wizard register 3 MX bit.
XCLK_WIZ_REG1_PREDIV2
Clock Wizard register 1 pre-divider 2 bit.
XCLK_WIZ_REG1_EN
Clock Wizard register 1 enable bit.
XCLK_WIZ_REG1_MX
Clock Wizard register 1 MX bit.
XCLK_WIZ_RECONFIG_LOAD
Clock Wizard reconfiguration load bit.
XCLK_WIZ_RECONFIG_SADDR
Clock Wizard reconfiguration start address bit.
XCLK_WIZ_REG1_EDGE_MASK
Clock Wizard register 1 edge mask.
XCLK_WIZ_CLKOUT0_PREDIV2_SHIFT
Clock Wizard CLKOUT0 pre-divider 2 shift.
XCLK_WIZ_CLKOUT0_MX_SHIFT
Clock Wizard CLKOUT0 MX shift.
XCLK_WIZ_CLKOUT0_P5EN_SHIFT
Clock Wizard CLKOUT0 P5 enable shift.
XCLK_WIZ_CLKOUT0_P5FEDGE_SHIFT
Clock Wizard CLKOUT0 P5 falling edge shift.
XCLK_WIZ_REG12_EDGE_SHIFT
Clock Wizard register 12 edge shift.
M_VAL_405
M value for 4.05 Gbps link rate.
M_VAL_270
M value for 2.70 Gbps link rate.
M_VAL_135
M value for 1.35 Gbps link rate.
M_VAL_81
M value for 0.81 Gbps link rate.
D_VAL_ALL
D value for all link rates.
XCLK_WIZ_STATUS_RETRY
Clock Wizard status check retry count.
Referenced by XDpRxSs_Get_Dec_Clk_Lock.
XCLK_WIZ_STATUS_WAIT
Clock Wizard status check wait time in microseconds.
Referenced by XDpRxSs_Get_Dec_Clk_Lock.
VBLANK_WAIT_COUNT_THRESHOLD
VBlank interrupt disable threshold.
XDPRXSS_H_
Prevent circular inclusions by using protection macros.
XDPRXSS_DPCD_LINK_BW_SET
DPCD link bandwidth set register.
Referenced by XDpRxSs_GetLinkRate.
XDPRXSS_USER_FIFO_OVERFLOW
User FIFO overflow register.
XDPRXSS_LINE_RESET_DISABLE
Line reset disable register.
XDPRXSS_MIN_VOLTAGE_SWING
Minimum voltage swing register.
XDPRXSS_CDR_CONTROL_CONFIG
CDR control configuration register.
XDPRXSS_MSA_MISC0
MSA MISC0 register.
Referenced by CalculateCRC.
XDPRXSS_INTERRUPT_MASK_INFO_PKT_MASK
Info packet interrupt mask.
XDPRXSS_INTERRUPT_MASK_VBLANK_MASK
Vertical blanking interrupt mask.
Referenced by DpRxSs_Main.
XDPRXSS_INTERRUPT_MASK_ACT_RX_MASK
ACT RX interrupt mask.
XDPRXSS_INTERRUPT_MASK_ALL_MASK
All interrupts mask.
XDPRXSS_INTERRUPT1_MASK_MST_ALL
MST stream interrupts (all 18 bits)
Referenced by XDpRxSs_HandleActRxInterrupts.
XDPRXSS_CDR_CONTROL_CONFIG_TDLOCK_DP159
CDR control config TDLOCK DP159.
Referenced by DpRxSs_Main.
XDpRxSs_TimerHandler
Callback type which represents a custom timer wait handler.
XDpRxSs_DtgEnable
This function macro enables the display timing generator (DTG).
InstancePtr is a pointer to the XDpRxSs core instance. C-style signature: void XDpRxSs_DtgEnable(XDpRxSs *InstancePtr)
Referenced by DpRxSs_Main.
XDpRxSs_DtgDisable
This function macro disables the display timing generator (DTG).
InstancePtr is a pointer to the XDpRxSs core instance. C-style signature: void XDpRxSs_DtgDisable(XDpRxSs *InstancePtr)
Referenced by DpRxSs_Main.
XDpRxSs_AudioEnable
This function macro enables audio stream packets on the main link.
InstancePtr is a pointer to the XDpRxSs core instance. C-style signature: void XDpRxSs_AudioEnable(XDpRxSs *InstancePtr)
Referenced by DpRxSs_Main.
XDpRxSs_AudioDisable
This function macro disables audio stream packets on the main link.
InstancePtr is a pointer to the XDpRxSs core instance. C-style signature: void XDpRxSs_AudioDisable(XDpRxSs *InstancePtr)
Referenced by DpRxSs_Main, DpRxSs_TrainingLostHandler.
XDpRxSs_AudioReset
This function macro resets the reception of audio stream packets on the main link.
InstancePtr is a pointer to the XDpRxSs core instance. C-style signature: void XDpRxSs_AudioReset(XDpRxSs *InstancePtr)
XDP_RX_STREAM_MSA_OFFSET
This function macro enable the stream address.
StreamId is zero for SST, veries for MST. C-style signature: XDP_RX_STREAM_MSA_OFFSET(StreamNumber) i
Referenced by XDpRxss_GetInterlace, XDpRxss_GetMsa.
XDpRxSs_Mst_AudioEnable
This function macro enables MST audio on a given stream on the main link.
InstancePtr is a pointer to the XDpRxSs core instance. StreamId to be enabled audio C-style signature: void XDpRxSs_Mst_AudioEnable(XDpRxSs *InstancePtr, u8 StreamId)
XDpRxSs_Mst_AudioDisable
This function macro disables audio on a given stream on the main link.
InstancePtr is a pointer to the XDpRxSs core instance. None. C-style signature: void XDpRxSs_Mst_AudioDisable(XDpRxSs *InstancePtr)
XDpRxSs_WaitUs
This function macro is the delay/sleep function for the XDpRxSs driver.
InstancePtr is a pointer to the XDpRxSs core instance. MicroSeconds is the number of microseconds to delay/sleep for. C-style signature: void XDpRxSs_WaitUs(XDpRxSs *InstancePtr, u32 MicroSeconds)
DpRxSs_RxEnable
This function macro Enables/Disables the Dp Rx link.
InstancePtr is a pointer to the XDpRxSs core instance. Enable is to enable/disable the Dp Rx link. None. C-style signature: void DpRxSs_RxEnable(XDpRxSs *InstancePtr, u32 Enable)
Referenced by XDpRxSs_Setup.
DpRxSs_GetLinkQualLane
This function macro provides link Quality of Dp Rx lane.
InstancePtr is a pointer to the XDpRxSs core instance. Link quality of lane. C-style signature: u8 DpRxSs_GetLinkQualLane(XDpRxSs *InstancePtr)
XDpRxSs_UserFifoOverflowStatus
This function macro provides user fifo overflow status.
InstancePtr is a pointer to the XDpRxSs core instance. user fifo overflow status. C-style signature: u8 XDpRxSs_UserFifoOverflowStatus(XDpRxSs *InstancePtr)
Referenced by CalculateCRC, DpRxSs_Main.
XDpRxSs_GetRxResetDisable
This function macro provides RX line reset disable status.
InstancePtr is a pointer to the XDpRxSs core instance. RX line reset disable status. C-style signature: u32 XDpRxSs_GetRxResetDisable(XDpRxSs *InstancePtr)
Referenced by DpRxSs_Main.
XDpRxSs_GetRxMstAlloc
This function macro provides the contents of DPCD registers.
InstancePtr is a pointer to the XDpRxSs core instance. DPCD registers content. C-style signature: u8 XDpRxSs_GetRxMstAlloc(XDpRxSs *InstancePtr)
DpRxSs_GetRxAudioInfo
This function macro provides Rx Audio info data.
InstancePtr is a pointer to the XDpRxSs core instance. Index of the registers. Rx audio info. C-style signature: u32 DpRxSs_GetRxAudioInfo(XDpRxSs *InstancePtr, u8 Index)
DpRxSs_GetRxAudioExtInfo
This function macro provides Rx Audio Extension packet data.
InstancePtr is a pointer to the XDpRxSs core instance. Index of the registers. Rx Audio Extension packet data. C-style signature: u32 DpRxSs_GetRxAudioExtInfo(InstancePtr, Index)
DpRxSs_UpdateCdrConfig
This function macro Update the CDR config value of Dp Rx.
InstancePtr is a pointer to the XDpRxSs core instance. CdrConfig is combined value of CDR timeout and timeout disable. None. C-style signature: void DpRxSs_UpdateCdrConfig(XDpRxSs *InstancePtr, u32 CdrConfig)
XDpRxSs_UpdateCdrTimeOutVal
This function macro updates the CDR timeout value (bits [19:0]) without disturbing the Disable Training Timeout bit (bit 30).
InstancePtr is a pointer to the XDpRxSs core instance. TimeOutVal is the timeout value to be set (20-bit value). None. C-style signature: void XDpRxSs_UpdateCdrTimeOutVal(XDpRxSs *InstancePtr, u32 TimeOutVal)
Referenced by DpRxSs_Main.
XDpRxSs_CdrDisableTimeout
This function macro controls the CDR Disable Training Timeout bit (bit 30).
InstancePtr is a pointer to the XDpRxSs core instance. Disable is 1 to disable training timeout, 0 to enable it. None. C-style signature: void XDpRxSs_CdrDisableTimeout(XDpRxSs *InstancePtr, u8 Disable)
Referenced by DpRxSs_Main.
XDpRxSs_AuxReset
This function macro Reset the AUX logic from Dp RX.
InstancePtr is a pointer to the XDpRxSs core instance. AuxReset is AUX logic reset value. None. C-style signature: void XDpRxSs_AuxReset(XDpRxSs *InstancePtr, u8 AuxReset)
Referenced by DpRxSs_Main.
XDpRxSs_GenerateHpdInterrupt
This function macro generates HPD (Hot-Plug-Detect) pulse interrupt.
InstancePtr is a pointer to the XDpRxSs core instance. DurationUs is the duration of the HPD pulse in microseconds. None. C-style signature: void XDpRxSs_GenerateHpdInterrupt(XDpRxSs *InstancePtr, u32 DurationUs)
Referenced by DpRxSs_Main.
XDpRxSs_RxInterruptEnable
This function macro enables RX interrupt.
InstancePtr is a pointer to the XDpRxSs core instance. Mask is the interrupt mask to enable. None. C-style signature: void XDpRxSs_RxInterruptEnable(XDpRxSs *InstancePtr, u32 Mask)
XDpRxSs_RxInterruptDisable
This function macro disables RX interrupt.
InstancePtr is a pointer to the XDpRxSs core instance. Mask is the interrupt mask to disable. None. C-style signature: void XDpRxSs_RxInterruptDisable(XDpRxSs *InstancePtr, u32 Mask)
Referenced by DpRxSs_Main.
XDpRxSs_RxInterruptEnable1
This function macro enables RX interrupt (Interrupt Enable 1 register).
InstancePtr is a pointer to the XDpRxSs core instance. Mask is the interrupt mask to enable. None. C-style signature: void XDpRxSs_RxInterruptEnable1(XDpRxSs *InstancePtr, u32 Mask)
XDpRxSs_RxInterruptDisable1
This function macro disables RX interrupt (Interrupt Enable 1 register).
InstancePtr is a pointer to the XDpRxSs core instance. Mask is the interrupt mask to disable. None. C-style signature: void XDpRxSs_RxInterruptDisable1(XDpRxSs *InstancePtr, u32 Mask)
XDpRxSs_RxAllocatePayloadStream
This function macro allocates payload stream for MST mode.
InstancePtr is a pointer to the XDpRxSs core instance. None. C-style signature: void XDpRxSs_RxAllocatePayloadStream(XDpRxSs *InstancePtr)
XDPRXSS_HW_H_
Prevent circular inclusions by using protection macros.
XDPRXSS_LINK_BW_SET_162GBPS
1.62 Gbps link rate.
XDPRXSS_LINK_BW_SET_270GBPS
2.70 Gbps link rate.
XDPRXSS_LINK_BW_SET_540GBPS
5.40 Gbps link rate.
XDPRXSS_LINK_BW_SET_810GBPS
8.10 Gbps link rate.
Referenced by XDpRxSs_CfgInitialize.
XDPRXSS_LANE_COUNT_SET_1
Lane count of 1.
Referenced by XDpRxSs_SetLaneCount.
XDPRXSS_LANE_COUNT_SET_2
Lane count of 2.
Referenced by XDpRxSs_SetLaneCount.
XDPRXSS_LANE_COUNT_SET_4
Lane count of 4.
Referenced by XDpRxSs_CfgInitialize, XDpRxSs_SetLaneCount.
XDPRXSS_RX_PHY_CONFIG
PHY reset and config.
XDPRXSS_PHY_POWER_DOWN
PHY power down.
XDPRXSS_MSA_HRES
Number of active pixels per line (the horizontal resolution).
XDPRXSS_MSA_VRES
Number of active lines (the vertical resolution).
XDPRXSS_DPCD_LINK_BW_SET
DPCD link bandwidth setting register offset.
XDPRXSS_DPCD_LANE_COUNT_SET
DPCD lane count setting register offset.
XDPRXSS_DPCD_LANE01_STATUS
DPCD lane 0 and lane 1 status register offset.
XDPRXSS_DPCD_LANE23_STATUS
DPCD lane 2 and lane 3 status register offset.
XDPRXSS_INTR_VBLANK_MASK
Interrupt mask for vertical blanking period.
XDPRXSS_NUM_STREAMS
Maximum number of streams supported.
XDPRXSS_MAX_NPORTS
Maximum number of RX ports.
XDPRXSS_GUID_NBYTES
Number of bytes for GUID.
XDPRXSS_TMRCTR_RST_VAL
Timer Counter reset value.
Referenced by XDpRxSs_CfgInitialize.
XDPRXSS_ALL_INTR_MASK
All interrupt mask - enables all interrupts.
Referenced by XDpRxSs_Setup.
XDPRXSS_CHANNEL_CODING_OFFSET
Channel coding register offset.
Referenced by XDpRxSs_Setup.
XDPRXSS_8B10B_CHANNEL_CODING
8b/10b channel coding value
Referenced by DpRxSs_Main.
XDPRXSS_128B132B_CHANNEL_CODING
128b/132b channel coding value
XDPRXSS_CRC_CONFIG
CRC configuration register offset.
XDPRXSS_CRC_COMP0
CRC component 0 register offset.
XDPRXSS_CRC_COMP1
CRC component 1 register offset.
XDPRXSS_CRC_COMP2
CRC component 2 register offset.
XDPRXSS_CRC_ENABLE_SHIFT
CRC enable bit shift position.
XDPRXSS_CRC_CONFIG_MASK
CRC configuration register mask.
XDPRXSS_DPC_LINK_QUAL_CONFIG
Link quality configuration register offset.
XDPRXSS_DPC_L01_PRBS_CNTR_OFFSET
Lanes 0-1 PRBS counter register offset.
Referenced by DpRxSs_UpdatePrbsErrCouters.
XDPRXSS_DPC_L23_PRBS_CNTR_OFFSET
Lanes 2-3 PRBS counter register offset.
Referenced by DpRxSs_UpdatePrbsErrCouters.
XDPRXSS_DPC_LANE_PRBS_CNTR_VALID_MASK
Lane PRBS counter valid bit mask.
Referenced by DpRxSs_UpdatePrbsErrCouters.
XDPRXSS_DPC_LINK_QUAL_PRBS_MASK
Link quality PRBS mode mask.
XDPRXSS_DPC_LINK_QUAL_PRBS
Link quality PRBS mode value.
XDPRXSS_CDR_TIMEOUT_MASK
CDR timeout mask.
XDPRXSS_USER_FIFO_OVERFLOW_STREAM1_MASK
User FIFO overflow for stream 1 mask.
Referenced by CalculateCRC.
XDPRXSS_SOFT_RESET_AUX_SHIFT
Soft reset AUX bit shift position.
XDPRXSS_VFreqL_OFFSET
Vertical frequency low register offset.
XDPRXSS_VFreqH_OFFSET
Vertical frequency high register offset.