hdcp/main.h
XPAR_XV_FRMBUFRD_NUM_INSTANCES
XPAR_XV_FRMBUFWR_NUM_INSTANCES
USE_EEPROM_HDCP_KEYS
ENABLE_HDCP_IN_DESIGN
ENABLE_HDCP22_IN_RX
ENABLE_HDCP1x_IN_RX
ENABLE_HDCP_RX
KEYMGMT_BASEADDR_RX
ENABLE_HDCP22_IN_TX
ENABLE_HDCP1x_IN_TX
ENABLE_HDCP_TX
KEYMGMT_BASEADDR_TX
ENABLE_AUDIO
PT
Rxo
Txo
XINTC_DEVICE_ID
XINTC_HANDLER
XDPRXSS_DEVICE_ID
XVPHY_DEVICE_ID
XTIMER0_DEVICE_ID
TX_CLK_RST_ADDR
VIDEO_CRC_BASEADDR
UARTLITE_BASEADDR
VID_EDID_BASEADDR
IIC_DEVICE_ID
IIC_BASE_ADDR
VIDEO_FRAME_CRC_TX_BASEADDR
VIDEO_FRAME_CRC_RX_BASEADDR
AXI_SYSTEM_CLOCK_FREQ_HZ
TIMER_RESET_VALUE
XDP_RX_CRC_CONFIG
XDP_RX_CRC_COMP0
XDP_RX_CRC_COMP1
XDP_RX_CRC_COMP2
XDP_RX_DPC_LINK_QUAL_CONFIG
XDP_RX_DPC_L01_PRBS_CNTR
XDP_RX_DPC_L23_PRBS_CNTR
XDP_RX_DPCD_LINK_QUAL_PRBS
XVPHY_GTHE4_PREEMP_DP_L0
XVPHY_GTHE4_PREEMP_DP_L1
XVPHY_GTHE4_PREEMP_DP_L2
XVPHY_GTHE4_PREEMP_DP_L3
XVPHY_GTHE4_DIFF_SWING_DP_V0P0
XVPHY_GTHE4_DIFF_SWING_DP_V0P1
XVPHY_GTHE4_DIFF_SWING_DP_V0P2
XVPHY_GTHE4_DIFF_SWING_DP_V0P3
XVPHY_GTHE4_DIFF_SWING_DP_V1P0
XVPHY_GTHE4_DIFF_SWING_DP_V1P1
XVPHY_GTHE4_DIFF_SWING_DP_V1P2
XVPHY_GTHE4_DIFF_SWING_DP_V2P0
XVPHY_GTHE4_DIFF_SWING_DP_V2P1
XVPHY_GTHE4_DIFF_SWING_DP_V3P0
XVPHY_GTHE4_DIFF_SWING_DP_DP20
DP_BS_IDLE_TIMEOUT
VBLANK_WAIT_COUNT
AUX_DEFER_COUNT
AUX_DEFER_COUNT_PHY
PRBS_ERRCNTR_CLEAR_ON_READ
LINK_TRAINING_DEBUG
audio_clk_Hz
SI570_EEPROM_TEST_START_ADDRESS
PAGE_SIZE
NUM_MODES
NUM_CLOCK_REGS
AUXFIFOSIZE
AXIMMWIDTH
XVPHY_DP_LINK_RATE_HZ_1000GBPS
XVPHY_DP_LINK_RATE_HZ_1350GBPS
XVPHY_DP_LINK_RATE_HZ_2000GBPS
XVPHY_DP_REF_CLK_FREQ_HZ_400
ANSI_COLOR_RED
ANSI_COLOR_GREEN
ANSI_COLOR_YELLOW
ANSI_COLOR_BLUE
ANSI_COLOR_MAGENTA
ANSI_COLOR_CYAN
ANSI_COLOR_WHITE
ANSI_COLOR_RESET
XVIDC_CUSTOM_MODES
u32 DpSs_Main()
u32 DpSs_PlatformInit(void)
This function initialize required platform specific peripherals.
None. XST_SUCCESS if required peripherals are initialized and configured successfully.XST_FAILURE, otherwise. None.
References TmrCtr, XTIMER0_DEVICE_ID, TIMER_RESET_VALUE, PS_IIC_CLK, VideoFMC_Init.
void frameBuffer_stop(void)
void frameBuffer_stop_wr(void)
void frameBuffer_stop_rd(void)
void PLLRefClkSel(XVphy *InstancePtr, u8 link_rate, XVphy_ChannelId Channel)
void ReportVideoCRC()
This function reports CRC values of Video components.
None. None. None. None.
Referenced by DpRxSs_Main.
void CalculateCRC(void)
This function Calculates CRC values of Video components.
None. None. None. None.
References Video_CRC_Config::TEST_CRC_CNT, XDpRxSs::DpPtr, Video_CRC_Config::TEST_CRC_SUPPORTED, XDpRxss_GetColorComponent, Video_CRC_Config::Mode_422, CustomWaitUs, XDPRXSS_MSA_MISC0, VIDEO_CRC_BASEADDR, XDpRxSs_UserFifoOverflowStatus, XDPRXSS_USER_FIFO_OVERFLOW_STREAM1_MASK, Video_CRC_Config::Pixel_r, Video_CRC_Config::Pixel_g, Video_CRC_Config::Pixel_b.
Referenced by DpRxSs_Main.
char XUartPs_RecvByte_NonBlocking()
This function is a non-blocking UART return byte.
None. None. None. Received byte from UART. None.
void CustomWaitUs(void *InstancePtr, u32 MicroSeconds)
This function is called when DisplayPort Subsystem core requires delay or sleep.
It provides timer with predefined amount of loop iterations. InstancePtr is a pointer to the XDp instance. MicroSeconds is the delay time in microseconds. None. It provides timer with predefined amount of loop iterations. InstancePtr is a pointer to the XDp instance. None.
int VideoFMC_Init(void)
This function initializes VFMC.
XST_SUCCESS if initialization was successful.XST_FAILURE if an error occurs. None. None. None. None.
References ConfigPtr_IIC, IicInstance, I2C_MUX_ADDR, XIIC_BASEADDRESS.
Referenced by DpSs_PlatformInit, DpRxSs_PlatformInit.
u32 DpSs_SetupIntrSystem(void)
This function sets up the interrupt system so interrupts can occur for the DisplayPort TX Subsystem core.
The function is application-specific since the actual system may or may not have an interrupt controller. The DPTX Subsystem core could be directly connected to a processor without an interrupt controller. The user should modify this function to fit the application. None XST_SUCCESS if interrupt setup was successful.A specific error code defined in "xstatus.h" if an error occurs. None.
References DpTxSsInst, DpRxSs_SetupIntrSystem, XDpRxSs_DpIntrHandler, XDpRxSs::Config.
int TI_LMK03318_PowerDown(u32 I2CBaseAddress, u8 I2CSlaveAddress)
int TI_LMK03318_SetRegister(u32 I2CBaseAddress, u8 I2CSlaveAddress, u8 RegisterAddress, u8 Value)
char xil_getc(u32 timeout_ms)
This function to get uart input from user.
timeout_ms received character None. timeout_ms received charactor None.
void operationMenu(void)
void frameBuffer_start_wr(XDpTxSs_MainStreamAttributes Msa[4])
void frameBuffer_start_rd(XDpTxSs_MainStreamAttributes Msa[4])
void DpPt_ffe_adjustHandler(void *InstancePtr)
u32 xil_gethex(u8 num_chars)
This function to convert integer to hex.
timeout_ms received character None. timeout_ms received charactor None.
int i2c_write_freq(u32 I2CBaseAddress, u8 I2CSlaveAddress, u8 RegisterAddress, u32 Value)
u8 i2c_read_freq(u32 I2CBaseAddress, u8 I2CSlaveAddress, u16 RegisterAddress)
u8 i2c_read_tdp2004(u32 I2CBaseAddress, u8 I2CSlaveAddress, u16 RegisterAddress)
int i2c_write_tdp2004(u32 I2CBaseAddress, u8 I2CSlaveAddress, u8 RegisterAddress, u8 Value)
u32 config_phy(XVphy *InstancePtr, int LineRate_init_tx, XVphy_PllType Pll, XVphy_ChannelId Channel, XVphy_DirectionType Dir)
This function sets VPHY based on the link rate.
user_config_struct. Status. None.
References VPHY_REFCLK_SEL_270, PLLRefClkSel.
Referenced by DpRxSs_LinkBandwidthHandler.
void Gen_vid_clk(XDp *InstancePtr, u8 Stream)
void Hdcp1xExample_Poll(void)
This function polls the hdcp example module.
void This function is intended to be called from within the main loop of the software utilizing this module.