mst/rx.h
XDPRXSS_DEVICE_ID
< XPAR_INTC_0_DEVICE_ID
VIDEO_CRC_BASEADDR
UARTLITE_BASEADDR
VIDPHY_BASEADDR
VID_EDID_BASEADDR
IIC_DEVICE_ID
DPRXSS_LINK_RATE
DPRXSS_LANE_COUNT
XDP_RX_CRC_CONFIG
XDP_RX_CRC_COMP0
XDP_RX_CRC_COMP1
XDP_RX_CRC_COMP2
XDP_RX_DPC_LINK_QUAL_CONFIG
XDP_RX_DPC_L01_PRBS_CNTR
XDP_RX_DPC_L23_PRBS_CNTR
XDP_RX_DPCD_LINK_QUAL_PRBS
XVPHY_RX_SYM_ERR_CNTR_CH1_2_REG
XVPHY_RX_SYM_ERR_CNTR_CH3_4_REG
XVPHY_DRP_CPLL_FBDIV
XVPHY_DRP_CPLL_REFCLK_DIV
XVPHY_DRP_RXOUT_DIV
XVPHY_DRP_RXCLK25
XVPHY_DRP_TXCLK25
XVPHY_DRP_TXOUT_DIV
XVPHY_DRP_RX_DATA_WIDTH
XVPHY_DRP_RX_INT_DATA_WIDTH
XVPHY_DRP_GTHE4_PRBS_ERR_CNTR_LOWER
XVPHY_DRP_GTHE4_PRBS_ERR_CNTR_UPPER
TIMER_RESET_VALUE
XACR_WriteReg
XACR_ReadReg
RXACR_MODE
RXACR_MAUD
RXACR_NAUD
RXACR_DIV
RXACR_ENABLE
void DpRxSs_Main(void)
u32 DpRxSs_Setup(void)
This function configures DisplayPort RX Subsystem.
None. XST_SUCCESS if DP RX Subsystem configured successfully.XST_FAILURE, otherwise. None.
u32 DpRxSs_SetupIntrSystem(void)
This function sets up the interrupt system so interrupts can occur for the DisplayPort RX Subsystem core.
The function is application-specific since the actual system may or may not have an interrupt controller. The DPRX Subsystem core could be directly connected to a processor without an interrupt controller. The user should modify this function to fit the application. None XST_SUCCESS if interrupt setup was successful.A specific error code defined in "xstatus.h" if an error occurs. None. The function is application-specific since the actual system may or may not have an interrupt controller. The DPRX Subsystem core could be directly connected to a processor without an interrupt controller. The user should modify this function to fit the application. XST_SUCCESS if interrupt setup was successful.A specific error code defined in "xstatus.h" if an error occurs. None. The function is application-specific since the actual system may or may not have an interrupt controller. The DPRX Subsystem core could be directly connected to a processor without an interrupt controller. The user should modify this function to fit the application. None XST_SUCCESS if interrupt setup was successful.A specific error code defined in "xstatus.h" if an error occurs. None. The function is application-specific since the actual system may or may not have an interrupt controller. The DPRX Subsystem core could be directly connected to a processor without an interrupt controller. The user should modify this function to fit the application. XST_SUCCESS if interrupt setup was successful.A specific error code defined in "xstatus.h" if an error occurs. None.
References XDpRxSs_SetCallBack, XDPRXSS_DRV_HANDLER_DP_VID_EVENT, XDPRXSS_HANDLER_DP_PWR_CHG_EVENT, DpRxSs_PowerChangeHandler, XDPRXSS_HANDLER_DP_NO_VID_EVENT, DpRxSs_NoVideoHandler, XDPRXSS_HANDLER_DP_VM_CHG_EVENT, XDPRXSS_HANDLER_DP_VBLANK_EVENT, DpRxSs_VerticalBlankHandler, XDPRXSS_HANDLER_DP_TLOST_EVENT, DpRxSs_TrainingLostHandler, XDPRXSS_HANDLER_DP_VID_EVENT, DpRxSs_VideoHandler, XDPRXSS_HANDLER_DP_TDONE_EVENT, DpRxSs_TrainingDoneHandler, XDPRXSS_HANDLER_UNPLUG_EVENT, DpRxSs_UnplugHandler, XDPRXSS_HANDLER_LINKBW_EVENT, DpRxSs_LinkBandwidthHandler, XDPRXSS_HANDLER_PLL_RESET_EVENT, DpRxSs_PllResetHandler, XDPRXSS_HANDLER_DP_BW_CHG_EVENT, DpRxSs_BWChangeHandler, XDPRXSS_HANDLER_ACCESS_LINK_QUAL_EVENT, DpRxSs_AccessLinkQualHandler, XDPRXSS_HANDLER_ACCESS_ERROR_COUNTER_EVENT, DpRxSs_AccessErrorCounterHandler, XDPRXSS_HANDLER_DP_CRC_TEST_EVENT, DpRxSs_CRCTestEventHandler, XDPRXSS_HANDLER_DP_INFO_PKT_EVENT, DpRxSs_InfoPacketHandler, XDPRXSS_HANDLER_DP_EXT_PKT_EVENT, DpRxSs_ExtPacketHandler, XDPRXSS_HANDLER_DP_DWN_REQ_EVENT, Dprx_InterruptHandlerDownReq, XDPRXSS_HANDLER_DP_DWN_REP_EVENT, Dprx_InterruptHandlerDownReply, XDPRXSS_HANDLER_DP_PAYLOAD_ALLOC_EVENT, Dprx_InterruptHandlerPayloadAlloc, XDPRXSS_HANDLER_DP_ACT_RX_EVENT, Dprx_InterruptHandlerActRx, XDpRxSs_SetUserTimerHandler, CustomWaitUs, TmrCtr.
Referenced by DpSs_SetupIntrSystem, DpRxSs_Main.
void DpRxSs_VideoValidHandler(void *InstancePtr)
This function is the callback function for when the power state interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_PowerChangeHandler(void *InstancePtr)
This function is the callback function for when the power state interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None. InstancePtr is a pointer to the XDpRxSs instance. None. InstancePtr is a pointer to the XDpRxSs instance. None. None. InstancePtr is a pointer to the XDpRxSs instance. None.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void DpRxSs_NoVideoHandler(void *InstancePtr)
This function is the callback function for when a no video interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None. InstancePtr is a pointer to the XDpRxSs instance. None. InstancePtr is a pointer to the XDpRxSs instance. None. None. InstancePtr is a pointer to the XDpRxSs instance. None.
References XDpRxSs::VBlankCount, XDpRxSs::DpPtr, Video_CRC_Config::TEST_CRC_CNT, Video_CRC_Config::TEST_CRC_SUPPORTED, XDpRxSs::no_video_trigger.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void DpRxSs_VmChangeHandler(void *InstancePtr)
This function is the callback function for when a video mode change interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_VerticalBlankHandler(void *InstancePtr)
This function is the callback function for when a vertical blank interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None. InstancePtr is a pointer to the XDpRxSs instance. None. InstancePtr is a pointer to the XDpRxSs instance. None. None. InstancePtr is a pointer to the XDpRxSs instance. None.
References XDpRxSs::VBlankCount, XDpRxSs::DpPtr, DpTxSsInst.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void DpRxSs_VerticalBlank1Handler(void *InstancePtr)
void DpRxSs_VerticalBlank2Handler(void *InstancePtr)
void DpRxSs_VerticalBlank3Handler(void *InstancePtr)
void DpRxSs_TrainingLostHandler(void *InstancePtr)
This function is the callback function for when a training lost interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None. InstancePtr is a pointer to the XDpRxSs instance. None. InstancePtr is a pointer to the XDpRxSs instance. None. None. InstancePtr is a pointer to the XDpRxSs instance. None.
References DpTxSsInst, Video_CRC_Config::TEST_CRC_CNT, XDpRxSs::DpPtr, Video_CRC_Config::TEST_CRC_SUPPORTED, XDpRxSs_AudioDisable, XDpRxSs::link_up_trigger, XDpRxSs::VBlankCount.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void DpRxSs_VideoHandler(void *InstancePtr)
This function is the callback function for when a valid video interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None. InstancePtr is a pointer to the XDpRxSs instance. None. InstancePtr is a pointer to the XDpRxSs instance. None. None. InstancePtr is a pointer to the XDpRxSs instance. None.
References XDpRxSs::DpPtr.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void DpRxSs_InfoPacketHandler(void *InstancePtr)
This function is the callback function for Info Packet Handling.
InstancePtr is a pointer to the XDpRxSs instance. None. None. InstancePtr is a pointer to the XDpRxSs instance. None. InstancePtr is a pointer to the XDpRxSs instance. None. None. InstancePtr is a pointer to the XDpRxSs instance. None.
References infofifo, XDpRxSs::DpPtr.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void DpRxSs_ExtPacketHandler(void *InstancePtr)
This function is the callback function for Generic Packet Handling of 32-Bytes payload.
InstancePtr is a pointer to the XDpRxSs instance. None. None. InstancePtr is a pointer to the XDpRxSs instance. None. InstancePtr is a pointer to the XDpRxSs instance. None. None. InstancePtr is a pointer to the XDpRxSs instance. None.
References XDpRxSs::DpPtr.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void DpRxSs_TrainingDoneHandler(void *InstancePtr)
This function is the callback function for when the training done interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None. InstancePtr is a pointer to the XDpRxSs instance. None. InstancePtr is a pointer to the XDpRxSs instance. None. None. InstancePtr is a pointer to the XDpRxSs instance. None.
References XDpRxSs::UsrOpt, XDpRxSs_UsrOpt::LaneCount, XDPRXSS_HDCP_14, XDpRxSs::DpPtr, XDpRxSs::link_up_trigger, XDpRxSs::VBlankCount.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void DpRxSs_UnplugHandler(void *InstancePtr)
This function is the callback function for when the unplug event occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None. InstancePtr is a pointer to the XDpRxSs instance. None. InstancePtr is a pointer to the XDpRxSs instance. None. None. InstancePtr is a pointer to the XDpRxSs instance. None.
References XDpRxSs::DpPtr, XDpRxSs::link_up_trigger, XDpRxSs::VBlankCount, XDpRxSs::no_video_trigger, DpTxSsInst.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void DpRxSs_LinkBandwidthHandler(void *InstancePtr)
This function is the callback function for when the link bandwidth change occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None. InstancePtr is a pointer to the XDpRxSs instance. None. InstancePtr is a pointer to the XDpRxSs instance. None. None. InstancePtr is a pointer to the XDpRxSs instance. None.
References config_phy, VPhyInst, XDpRxSs::UsrOpt, XDpRxSs_UsrOpt::LinkRate, XDpRxSs::link_up_trigger, XDpRxSs::VBlankCount, XDpRxSs::no_video_trigger.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void DpRxSs_PllResetHandler(void *InstancePtr)
This function is the callback function for PLL reset request.
InstancePtr is a pointer to the XDpRxSs instance. None. None. InstancePtr is a pointer to the XDpRxSs instance. None. InstancePtr is a pointer to the XDpRxSs instance. None. None. InstancePtr is a pointer to the XDpRxSs instance. None.
References XDpRxSs::DpPtr, AUX_DEFER_COUNT, VPhyInst, XDpRxSs::no_video_trigger.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void DpRxSs_BWChangeHandler(void *InstancePtr)
This function is the callback function for PLL reset request.
InstancePtr is a pointer to the XDpRxSs instance. None. None. InstancePtr is a pointer to the XDpRxSs instance. None. InstancePtr is a pointer to the XDpRxSs instance. None. None. InstancePtr is a pointer to the XDpRxSs instance. None.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void DpRxSs_AccessLaneSetHandler(void *InstancePtr)
This function is the callback function for Access lane set request.
InstancePtr is a pointer to the XDpRxSs instance. None. None. InstancePtr is a pointer to the XDpRxSs instance. None. InstancePtr is a pointer to the XDpRxSs instance. None. None. InstancePtr is a pointer to the XDpRxSs instance. None.
void DpRxSs_AccessLinkQualHandler(void *InstancePtr)
This function is the callback function for Access link qual request.
InstancePtr is a pointer to the XDpRxSs instance. None. None. InstancePtr is a pointer to the XDpRxSs instance. None. InstancePtr is a pointer to the XDpRxSs instance. None. None. InstancePtr is a pointer to the XDpRxSs instance. None.
References XDpRxSs::DpPtr, VPhyInst.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void DpRxSs_AccessErrorCounterHandler(void *InstancePtr)
This function is the callback function for Access prbs error count.
InstancePtr is a pointer to the XDpRxSs instance. None. None. InstancePtr is a pointer to the XDpRxSs instance. None. InstancePtr is a pointer to the XDpRxSs instance. None. None. InstancePtr is a pointer to the XDpRxSs instance. None.
References VIDPHY_BASEADDR, XVPHY_RX_SYM_ERR_CNTR_CH1_2_REG, XVPHY_RX_SYM_ERR_CNTR_CH3_4_REG, VPhyInst, XVPHY_DRP_GTHE4_PRBS_ERR_CNTR_LOWER, XVPHY_DRP_GTHE4_PRBS_ERR_CNTR_UPPER, XDpRxSs::DpPtr.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void DpRxSs_CRCTestEventHandler(void *InstancePtr)
This function is the callback function for Test CRC Event request.
InstancePtr is a pointer to the XDpRxSs instance. None. None. InstancePtr is a pointer to the XDpRxSs instance. None. InstancePtr is a pointer to the XDpRxSs instance. None. None. InstancePtr is a pointer to the XDpRxSs instance. None.
References XDpRxSs::DpPtr, XDpRxSs::Config, XDpRxSs_Config::BaseAddress.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void XDp_RxInterruptDisable1(XDp *InstancePtr, u32 Mask)
void XDp_RxInterruptEnable1(XDp *InstancePtr, u32 Mask)
void Dprx_InterruptHandlerDownReq(void *InstancePtr)
This function handles MST Down Request interrupt.
InstancePtr is a pointer to the XDpRxSs instance. None.
References XDpRxSs::DpPtr.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void Dprx_InterruptHandlerDownReply(void *InstancePtr)
This function handles MST Down Reply interrupt.
InstancePtr is a pointer to the XDpRxSs instance. None.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void Dprx_InterruptHandlerPayloadAlloc(void *InstancePtr)
This function handles MST payload allocation interrupt.
InstancePtr is a pointer to the XDpRxSs instance. None.
References XDpRxSs::DpPtr.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void Dprx_InterruptHandlerActRx(void *InstancePtr)
This function handles MST ACT (Allocation Change Trigger) interrupt.
InstancePtr is a pointer to the XDpRxSs instance. None.
References XDpRxSs::DpPtr.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.