mst/main.h
XPAR_XV_FRMBUFRD_NUM_INSTANCES
XPAR_XV_FRMBUFWR_NUM_INSTANCES
PT
< XPAR_INTC_0_DEVICE_ID
Passthrough Enable Rx
Rx
Enable Tx.
Tx
AXIMMWIDTH
XINTC_DEVICE_ID
XINTC_HANDLER
XDPRXSS_DEVICE_ID
XVPHY_DEVICE_ID
XTIMER0_DEVICE_ID
VIDEO_CRC_BASEADDR
UARTLITE_BASEADDR
VID_EDID_BASEADDR
IIC_DEVICE_ID
IIC_BASE_ADDR
VIDEO_FRAME_CRC_TX_BASEADDR
VIDEO_FRAME_CRC_TX1_BASEADDR
VIDEO_FRAME_CRC_TX2_BASEADDR
VIDEO_FRAME_CRC_TX3_BASEADDR
VIDEO_FRAME_CRC_RX_BASEADDR
VIDEO_FRAME_CRC_RX_BASEADDR_1
VIDEO_FRAME_CRC_RX_BASEADDR_2
VIDEO_FRAME_CRC_RX_BASEADDR_3
VIDEO_FRAME_CRC_RX_BASEADDR_4
AXI_SYSTEM_CLOCK_FREQ_HZ
XDP_RX_CRC_CONFIG
XDP_RX_CRC_COMP0
XDP_RX_CRC_COMP1
XDP_RX_CRC_COMP2
XDP_RX_DPC_LINK_QUAL_CONFIG
XDP_RX_DPC_L01_PRBS_CNTR
XDP_RX_DPC_L23_PRBS_CNTR
XDP_RX_DPCD_LINK_QUAL_PRBS
XVPHY_GTHE4_PREEMP_DP_L0
XVPHY_GTHE4_PREEMP_DP_L1
XVPHY_GTHE4_PREEMP_DP_L2
XVPHY_GTHE4_PREEMP_DP_L3
XVPHY_GTHE4_DIFF_SWING_DP_V0P0
XVPHY_GTHE4_DIFF_SWING_DP_V0P1
XVPHY_GTHE4_DIFF_SWING_DP_V0P2
XVPHY_GTHE4_DIFF_SWING_DP_V0P3
XVPHY_GTHE4_DIFF_SWING_DP_V1P0
XVPHY_GTHE4_DIFF_SWING_DP_V1P1
XVPHY_GTHE4_DIFF_SWING_DP_V1P2
XVPHY_GTHE4_DIFF_SWING_DP_V2P0
XVPHY_GTHE4_DIFF_SWING_DP_V2P1
XVPHY_GTHE4_DIFF_SWING_DP_V3P0
XVPHY_GTHE4_DIFF_SWING_DP_DP20
DP_BS_IDLE_TIMEOUT
VBLANK_WAIT_COUNT
AUX_DEFER_COUNT
AUX_DEFER_COUNT_PHY
PRBS_ERRCNTR_CLEAR_ON_READ
LINK_TRAINING_DEBUG
RATE_162
RATE_270
RATE_540
RATE_810
RATE_1000
RATE_1350
RATE_2000
XVPHY_DP_LINK_RATE_HZ_1000GBPS
XVPHY_DP_LINK_RATE_HZ_1350GBPS
XVPHY_DP_LINK_RATE_HZ_2000GBPS
XVPHY_DP_REF_CLK_FREQ_HZ_400
ANSI_COLOR_RED
ANSI_COLOR_GREEN
ANSI_COLOR_YELLOW
ANSI_COLOR_BLUE
ANSI_COLOR_MAGENTA
ANSI_COLOR_CYAN
ANSI_COLOR_WHITE
ANSI_COLOR_RESET
XVIDC_CUSTOM_MODES
u32 Dp21RxSs_PtMst_Main()
u32 Dp21RxSs_PtMst_PlatformInit(void)
This function initialize required platform specific peripherals.
None. XST_SUCCESS if required peripherals are initialized and configured successfully.XST_FAILURE, otherwise. None.
void Dp21RxSs_PtMst_FbStop(void)
void Dp21RxSs_PtMst_WrFbStop(void)
void Dp21RxSs_PtMst_RdFbStop(void)
void Dp21RxSs_PtMst_PLLRefClkSel(XVphy *InstancePtr, u8 link_rate, XVphy_ChannelId Channel)
void ReportVideoCRC(u8 select)
This function reports CRC values of Video components.
None. None. None.
void Dp21RxSs_PtMst_CalculateCRC(u8 Stream)
This function Calculates CRC values of Video components.
None. None. None.
char XUartPs_RecvByte_NonBlocking()
This function is a non-blocking UART return byte.
None. None. None. Received byte from UART. None.
Referenced by xil_getc.
void CustomWaitUs(void *InstancePtr, u32 MicroSeconds)
This function is called when DisplayPort Subsystem core requires delay or sleep.
It provides timer with predefined amount of loop iterations. InstancePtr is a pointer to the XDp instance. None. It provides timer with predefined amount of loop iterations. InstancePtr is a pointer to the XDp instance. MicroSeconds is the delay time in microseconds. None.
Referenced by DpRxSs_SetupIntrSystem, CalculateCRC.
int Dp21RxSs_PtMst_VideoFMC_Init(void)
This function initializes VFMC.
None. None. None.
u32 Dp21RxSs_PtMst_SetupIntrSystem(void)
This function sets up the interrupt system so interrupts can occur for the DisplayPort TX Subsystem core.
The function is application-specific since the actual system may or may not have an interrupt controller. The DPTX Subsystem core could be directly connected to a processor without an interrupt controller. The user should modify this function to fit the application. None XST_SUCCESS if interrupt setup was successful.A specific error code defined in "xstatus.h" if an error occurs. None.
int Vpg_StreamSrcConfigure(XDp *InstancePtr, u8 VSplitMode, u8 first_time)
This function updates required timing values in Video Pattern Generator core.
InstancePtr is a pointer to the XDp instance. VSplitMode specifies vertical split mode to be used for splitting resolution vertically. XST_SUCCESS if Video pattern configured successfully. None.
References Vpg_VidgenSetTestPattern, XPatGen_WriteReg.
int TI_LMK03318_PowerDown(u32 I2CBaseAddress, u8 I2CSlaveAddress)
int TI_LMK03318_SetRegister(u32 I2CBaseAddress, u8 I2CSlaveAddress, u8 RegisterAddress, u8 Value)
char Dp21RxSs_PtMst_Getc(u32 timeout_ms)
This function to get uart input from user.
timeout_ms received character None.
void Dp21RxSs_PtMst_OperationMenu(void)
void Dp21RxSs_PtMst_WrFbStart(XDpTxSs_MainStreamAttributes Msa[4], u8 Stream)
void Dp21RxSs_PtMst_RdFbStart(XDpTxSs_MainStreamAttributes Msa[4], u8 Stream)
void DpPt_ffe_adjustHandler(void *InstancePtr)
u32 Dp21RxSs_PtMst_Gethex(u8 num_chars)
This function to convert integer to hex.
timeout_ms received character None.
int Dp21RxSs_PtMst_I2cWriteFreq(u32 I2CBaseAddress, u8 I2CSlaveAddress, u8 RegisterAddress, u32 Value)
u8 Dp21RxSs_PtMst_I2cReadFreq(u32 I2CBaseAddress, u8 I2CSlaveAddress, u16 RegisterAddress)
u8 Dp21RxSs_PtMst_I2cReadTdp2004(u32 I2CBaseAddress, u8 I2CSlaveAddress, u16 RegisterAddress)
int Dp21RxSs_PtMst_I2cWriteTdp2004(u32 I2CBaseAddress, u8 I2CSlaveAddress, u8 RegisterAddress, u8 Value)
u32 Dp21RxSs_PtMst_PhyConfig(XVphy *InstancePtr, int LineRate_init_tx, XVphy_PllType Pll, XVphy_ChannelId Channel, XVphy_DirectionType Dir)
This function sets VPHY based on the linerate.
InstancePtr is a pointer to the XVphy instance. LineRate is link rate value. Pll is an instance to the XVphy_PllType. Channel is an instance to the XVphy_ChannelId. Dir is an instance to the XVphy_DirectionType. Status. None.
u32 Dp21RxSs_PtMst_Read(u32 BaseAddress, u32 RegOffset)
This function reads a register value using XDp_ReadReg for MST operations.
BaseAddress - The base address of the DP core RegOffset - The register offset to read from The 32-bit value read from the register This is a wrapper function for XDp_ReadReg specifically for MST-related register reads
void Dp21RxSs_PtMst_Write(u32 BaseAddress, u32 RegOffset, u32 Data)
This function writes a register value using XDp_WriteReg for MST operations.
BaseAddress - The base address of the DP core RegOffset - The register offset to write to Data - The 32-bit value to write to the register None This is a wrapper function for XDp_WriteReg specifically for MST-related register writes
void Read_EDID(void *InstancePtr, u8 enable_print)
void Set_EDID(u8 edid_monitor[384])
void main_loop(void)
void Gen_vid_clk(XDp *InstancePtr, u8 Stream)
void Vpg_Reset(void)
This function stops audio pattern generator.
None. None.
References XPatGen_WriteReg, Audio_Control.
u32 DpRxSs_Setup(void)
This function configures DisplayPort RX Subsystem.
None. XST_SUCCESS if DP RX Subsystem configured successfully.XST_FAILURE, otherwise. None.
void Dp21RxSs_PtMst_RxTracking(void)