xdprxss_intr.c
void XDpRxSs_DpIntrHandler(void *InstancePtr)
This function is the interrupt handler for the DisplayPort RX core operating in RX mode.
The application is responsible for connecting this function to the interrupt system. Application beyond this driver is also responsible for providing callbacks to handle interrupts and installing the callbacks using XDpRxSs_SetCallBack() during initialization phase. InstancePtr is a pointer to the XDpRxSs core instance that just interrupted. None.
References XDpRxSs::DpPtr, XDpRxSs::IsReady.
Referenced by Dp21RxSs_Pt_SetupIntrSystem, DpSs_SetupIntrSystem.
void XDpRxSs_DrvNoVideoHandler(void *InstancePtr)
This function is the interrupt handler for No Video.
InstancePtr is a pointer to the XDpRxSs core instance that just interrupted. None.
References XDpRxSs::DpPtr, XDpRxSs::IsReady.
Referenced by XDpRxSs_CfgInitialize.
void XDpRxSs_DrvVideoHandler(void *InstancePtr)
This function is for the video interrupt handler.
InstancePtr is a pointer to the XDpRxSs core instance that just interrupted. None.
References XDpRxSs::DpPtr, XDpRxSs::IsReady.
Referenced by XDpRxSs_CfgInitialize.
void XDpRxSs_DrvPowerChangeHandler(void *InstancePtr)
This function is for the power change interrupt handler.
InstancePtr is a pointer to the XDpRxSs core instance that just interrupted. None.
References XDpRxSs::DpPtr, XDpRxSs::IsReady.
Referenced by XDpRxSs_CfgInitialize.
u32 XDpRxSs_SetCallBack(XDpRxSs *InstancePtr, u32 HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function Type ---------------------------------------- ----------------------------------- XDPRXSS_HANDLER_DP_VM_CHG_EVENT XDp_RxSetIntrVmChangeHandler XDPRXSS_HANDLER_DP_PWR_CHG_EVENT XDp_RxSetIntrPowerStateHandler XDPRXSS_HANDLER_DP_NO_VID_EVENT XDp_RxSetIntrNoVideoHandler XDPRXSS_HANDLER_DP_VBLANK_EVENT XDp_RxSetIntrVBlankHandler XDPRXSS_HANDLER_DP_TLOST_EVENT XDp_RxSetIntrTrainingLostHandler XDPRXSS_HANDLER_DP_VID_EVENT XDp_RxSetIntrVideoHandler XDPRXSS_HANDLER_DP_INFO_PKT_EVENT XDp_RxSetIntrInfoPktHandler XDPRXSS_HANDLER_DP_EXT_PKT_EVENT XDp_RxSetIntrExtPktHandler XDPRXSS_HANDLER_DP_TDONE_EVENT XDp_RxSetIntrTrainingDoneHandler XDPRXSS_HANDLER_DP_BW_CHG_EVENT XDp_RxSetIntrBwChangeHandler XDPRXSS_HANDLER_DP_DWN_REQ_EVENT XDp_RxSetIntrDownReqHandler XDPRXSS_HANDLER_DP_DWN_REP_EVENT XDp_RxSetIntrDownReplyHandler XDPRXSS_HANDLER_DP_AUD_OVRFLW_EVENT XDp_RxSetIntrAudioOverHandler XDPRXSS_HANDLER_DP_PAYLOAD_ALLOC_EVENT XDp_RxSetIntrPayloadAllocHandler XDPRXSS_HANDLER_DP_ACT_RX_EVENT XDp_RxSetIntrActRxHandler XDPRXSS_HANDLER_DP_CRC_TEST_EVENT XDp_RxSetIntrCrcTestHandler XDPRXSS_HANDLER_HDCP_RPTR_TDSA_EVENT XHdcp1x_SetCallBack XDPRXSS_HANDLER_UNPLUG_EVENT UnplugCallback XDPRXSS_HANDLER_LINKBW_EVENT LinkBwCallback XDPRXSS_HANDLER_PLL_RESET_EVENT PllResetCallback InstancePtr is a pointer to the XDpRxSs core instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XDpRxSs::DpPtr, XDpRxSs::IsReady, XDpRxSs::LinkBwCallback, XDpRxSs::LinkBwRef, XDpRxSs::PllResetCallback, XDpRxSs::PllResetRef, XDpRxSs::UnplugCallback, XDpRxSs::UnplugRef, XDPRXSS_DRV_HANDLER_DP_NO_VID_EVENT, XDPRXSS_DRV_HANDLER_DP_PWR_CHG_EVENT, XDPRXSS_DRV_HANDLER_DP_VID_EVENT, XDPRXSS_HANDLER_DP_ACT_RX_EVENT, XDPRXSS_HANDLER_DP_AUD_OVRFLW_EVENT, XDPRXSS_HANDLER_DP_BW_CHG_EVENT, XDPRXSS_HANDLER_DP_CRC_TEST_EVENT, XDPRXSS_HANDLER_DP_DWN_REP_EVENT, XDPRXSS_HANDLER_DP_DWN_REQ_EVENT, XDPRXSS_HANDLER_DP_EXT_PKT_EVENT, XDPRXSS_HANDLER_DP_EXT_PKT_STREAM_2_EVENT, XDPRXSS_HANDLER_DP_EXT_PKT_STREAM_3_EVENT, XDPRXSS_HANDLER_DP_EXT_PKT_STREAM_4_EVENT, XDPRXSS_HANDLER_DP_INFO_PKT_EVENT, XDPRXSS_HANDLER_DP_INFO_PKT_STREAM_2_EVENT, XDPRXSS_HANDLER_DP_INFO_PKT_STREAM_3_EVENT, XDPRXSS_HANDLER_DP_INFO_PKT_STREAM_4_EVENT, XDPRXSS_HANDLER_DP_NO_VID_EVENT, XDPRXSS_HANDLER_DP_NO_VID_STREAM_2_EVENT, XDPRXSS_HANDLER_DP_NO_VID_STREAM_3_EVENT, XDPRXSS_HANDLER_DP_NO_VID_STREAM_4_EVENT, XDPRXSS_HANDLER_DP_PAYLOAD_ALLOC_EVENT, XDPRXSS_HANDLER_DP_PWR_CHG_EVENT, XDPRXSS_HANDLER_DP_TDONE_EVENT, XDPRXSS_HANDLER_DP_TLOST_EVENT, XDPRXSS_HANDLER_DP_VBLANK_EVENT, XDPRXSS_HANDLER_DP_VBLANK_STREAM_2_EVENT, XDPRXSS_HANDLER_DP_VBLANK_STREAM_3_EVENT, XDPRXSS_HANDLER_DP_VBLANK_STREAM_4_EVENT, XDPRXSS_HANDLER_DP_VID_EVENT, XDPRXSS_HANDLER_DP_VID_STREAM_2_EVENT, XDPRXSS_HANDLER_DP_VID_STREAM_3_EVENT, XDPRXSS_HANDLER_DP_VID_STREAM_4_EVENT, XDPRXSS_HANDLER_DP_VM_CHG_EVENT, XDPRXSS_HANDLER_DP_VM_CHG_STREAM_2_EVENT, XDPRXSS_HANDLER_DP_VM_CHG_STREAM_3_EVENT, XDPRXSS_HANDLER_DP_VM_CHG_STREAM_4_EVENT, XDPRXSS_HANDLER_LINKBW_EVENT, XDPRXSS_HANDLER_PLL_RESET_EVENT, XDPRXSS_HANDLER_UNPLUG_EVENT.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_CfgInitialize, XDpRxSs_SetUserCallBackHandlers.
void XDpRxSs_SetUserTimerHandler(XDpRxSs *InstancePtr, XDpRxSs_TimerHandler CallbackFunc, void *CallbackRef)
This function installs a custom delay/sleep function to be used by the DisplayPort RX Subsystem.
InstancePtr is a pointer to the XDpRxSs core instance. CallbackFunc is the address to the callback function. CallbackRef is the user data item (microseconds to delay) that will be passed to the custom sleep/delay function when it is invoked. None.
References XDpRxSs::DpPtr.
Referenced by DpRxSs_SetupIntrSystem.