xdprxss.c
EDID_IIC_ADDRESS
EDID IIC slave address.
EDID_SIZE_BYTES
EDID total size in bytes.
EDID_BLOCK_SIZE
EDID block size.
EDID_WORD_SIZE
EDID word size in bytes.
XCLK_WIZ_SWRST_OFFSET
Clock Wizard software reset register offset.
Referenced by XDpRxSs_Get_Dec_Clk_Lock.
XCLK_WIZ_SWRST_VAL
Clock Wizard software reset value.
Referenced by XDpRxSs_Get_Dec_Clk_Lock.
XCLK_WIZ_STATUS_OFFSET
Clock Wizard status register offset.
Referenced by XDpRxSs_Get_Dec_Clk_Lock.
XCLK_WIZ_ISR_OFFSET
Clock Wizard interrupt status register offset.
XCLK_WIZ_IER_OFFSET
Clock Wizard interrupt enable register offset.
XCLK_WIZ_RECONFIG_OFFSET
Clock Wizard reconfiguration register offset.
XCLK_WIZ_RECONFIG_VAL
Clock Wizard reconfiguration value.
XCLK_WIZ_REG1_OFFSET
Clock Wizard register 1 offset.
XCLK_WIZ_REG2_OFFSET
Clock Wizard register 2 offset.
XCLK_WIZ_REG3_OFFSET
Clock Wizard register 3 offset.
XCLK_WIZ_REG4_OFFSET
Clock Wizard register 4 offset.
XCLK_WIZ_REG12_OFFSET
Clock Wizard register 12 offset.
XCLK_WIZ_REG13_OFFSET
Clock Wizard register 13 offset.
XCLK_WIZ_REG11_OFFSET
Clock Wizard register 11 offset.
XCLK_WIZ_REG11_VAL
Clock Wizard register 11 value.
XCLK_WIZ_REG14_OFFSET
Clock Wizard register 14 offset.
XCLK_WIZ_REG14_VAL
Clock Wizard register 14 value.
XCLK_WIZ_REG15_OFFSET
Clock Wizard register 15 offset.
XCLK_WIZ_REG15_VAL
Clock Wizard register 15 value.
XCLK_WIZ_REG16_OFFSET
Clock Wizard register 16 offset.
XCLK_WIZ_REG16_VAL
Clock Wizard register 16 value.
XCLK_WIZ_REG17_OFFSET
Clock Wizard register 17 offset.
XCLK_WIZ_REG17_VAL
Clock Wizard register 17 value.
XCLK_WIZ_REG19_OFFSET
Clock Wizard register 19 offset.
XCLK_WIZ_REG25_OFFSET
Clock Wizard register 25 offset.
XCLK_WIZ_REG26_OFFSET
Clock Wizard register 26 offset.
XCLK_WIZ_REG26_VAL
Clock Wizard register 26 value.
XCLK_WIZ_LOCK
Clock Wizard lock bit.
XCLK_WIZ_REG3_PREDIV2
Clock Wizard register 3 pre-divider 2 bit.
XCLK_WIZ_REG3_USED
Clock Wizard register 3 used bit.
XCLK_WIZ_REG3_MX
Clock Wizard register 3 MX bit.
XCLK_WIZ_REG1_PREDIV2
Clock Wizard register 1 pre-divider 2 bit.
XCLK_WIZ_REG1_EN
Clock Wizard register 1 enable bit.
XCLK_WIZ_REG1_MX
Clock Wizard register 1 MX bit.
XCLK_WIZ_RECONFIG_LOAD
Clock Wizard reconfiguration load bit.
XCLK_WIZ_RECONFIG_SADDR
Clock Wizard reconfiguration start address bit.
XCLK_WIZ_REG1_EDGE_MASK
Clock Wizard register 1 edge mask.
XCLK_WIZ_CLKOUT0_PREDIV2_SHIFT
Clock Wizard CLKOUT0 pre-divider 2 shift.
XCLK_WIZ_CLKOUT0_MX_SHIFT
Clock Wizard CLKOUT0 MX shift.
XCLK_WIZ_CLKOUT0_P5EN_SHIFT
Clock Wizard CLKOUT0 P5 enable shift.
XCLK_WIZ_CLKOUT0_P5FEDGE_SHIFT
Clock Wizard CLKOUT0 P5 falling edge shift.
XCLK_WIZ_REG12_EDGE_SHIFT
Clock Wizard register 12 edge shift.
M_VAL_405
M value for 4.05 Gbps link rate.
M_VAL_270
M value for 2.70 Gbps link rate.
M_VAL_135
M value for 1.35 Gbps link rate.
M_VAL_81
M value for 0.81 Gbps link rate.
D_VAL_ALL
D value for all link rates.
XCLK_WIZ_STATUS_RETRY
Clock Wizard status check retry count.
Referenced by XDpRxSs_Get_Dec_Clk_Lock.
XCLK_WIZ_STATUS_WAIT
Clock Wizard status check wait time in microseconds.
Referenced by XDpRxSs_Get_Dec_Clk_Lock.
VBLANK_WAIT_COUNT_THRESHOLD
VBlank interrupt disable threshold.
u8 GenEdid[128][128]
u8 GenDpcd[][]
XDpRxSs_SubCores DpRxSsSubCores[XPAR_XDPRXSS_NUM_INSTANCES][XPAR_XDPRXSS_NUM_INSTANCES]
static void DpRxSs_GetIncludedSubCores(XDpRxSs *InstancePtr, UINTPTR BaseAddress)
This function reports list of cores included in DisplayPort RX Subsystem.
InstancePtr is a pointer to the XDpRxSs core instance. None.
static void DpRxSs_PopulateDpRxPorts(XDpRxSs *InstancePtr)
This function sets up the downstream topology that will be used by the DisplayPort RX to respond to down requests coming from the TX.
Sinks equal to number of streams (each with its own global unique identifier) are exposed to LINK_ADDRESS sideband messages.The extended display identification data (EDID) will be set to a generic EDID (GenEdid) for each of the sinks. REMOTE_I2C_READ sideband messages on address 0x50 will be replied to with the contents set by XDp_RxSetIicMapEntry for 0x50.REMOTE_DPCD_READ sideband messages will be responded to with the contents set for the sink using XDp_RxSetDpcdMap. All sinks are given the a generic DPCD (GenDpcd).ENUM_PATH_RESOURCES sideband messages will be responded to with the value set by XDp_RxMstSetPbn (or 0 if the sink already has a stream allocated to it). InstancePtr is a pointer to the XDpRxSs core instance. None.
static void DpRxSs_EnableTrainingInterrupts(XDp *DpPtr)
This function enables all training related interrupts for the DisplayPort RX Subsystem.
DpPtr is a pointer to the XDp instance. This is a common operation used during initialization and after unplug events.
static void StubTp1Callback(void *InstancePtr)
This routine is a stub for the asynchronous training pattern 1 interrupt callback.
On initialization, training pattern 1 interrupt handler is set to this callback. It is considered as an training pattern 1 for this handler to be invoked. InstancePtr is a pointer to the XDpRxSs core instance. None.
static void StubTp2Callback(void *InstancePtr)
This routine is a stub for the asynchronous training pattern 2 interrupt callback.
On initialization, training pattern 2 interrupt handler is set to this callback. It is considered as an training pattern 2 for this handler to be invoked. InstancePtr is a pointer to the XDpRxSs core instance. None.
static void StubUnplugCallback(void *InstancePtr)
This routine is a stub for the asynchronous unplug interrupt callback.
On initialization, unplug interrupt handler is set to this callback. It is considered as an unplug for this handler to be invoked. InstancePtr is a pointer to the XDpRxSs core instance. None.
static void StubAccessLaneSetCallback(void *InstancePtr)
This routine is a stub for the asynchronous access lane set interrupt callback.
On initialization, access lane set interrupt handler is set to this callback. InstancePtr is a pointer to the XDpRxSs core instance. None.
static void XDpRxSs_StubTrainingDoneCallback(void *InstancePtr)
Stub callback function for DisplayPort training done event.
This function is called when DisplayPort link training is completed. It resets the Display Timing Generator (DTG) by disabling and then re-enabling it to ensure proper synchronization with the newly trained link parameters. InstancePtr Pointer to the XDpRxSs instance. Must be a valid pointer to an XDpRxSs structure, otherwise an assertion failure will occur. This is a static stub function intended to be used as a default callback handler for training done events. The function assumes the InstancePtr is properly initialized.
static void XDpRxSs_StubTrainingLostCallback(void *InstancePtr)
Stub callback function for handling training lost events in DisplayPort RX Subsystem.
This function serves as a default callback handler when DisplayPort link training is lost. It generates an HPD (Hot Plug Detect) interrupt and disables audio output to properly handle the loss of link training. InstancePtr Pointer to the XDpRxSs instance. This pointer is cast to XDpRxSs type internally and must not be NULL. None This function performs the following actions: Validates that the instance pointer is not NULL using assertionGenerates a 750us HPD interrupt pulse to signal the sourceDisables audio output in the DisplayPort RX Subsystem The InstancePtr parameter must be a valid pointer to an XDpRxSs structure, otherwise an assertion failure will occur in debug builds.
static void XDpRxSs_StubVBlankCallback(void *InstancePtr)
This function is the stub callback for VBlank interrupts.
Driver invokes user callback, then conditionally disables interrupt based on VBlankCount threshold to prevent excessive interrupts. InstancePtr is a pointer to the XDpRxSs core instance. Disables VBLANK interrupt after VBlankCount exceeds threshold.
static void XDpRxSs_StubInfoPacketCallback(void *InstancePtr)
This function is the stub callback for InfoPacket interrupts.
Driver invokes user callback which manages packet processing. InstancePtr is a pointer to the XDpRxSs core instance. User callback manages frame_count and interrupt disable logic.
static void XDpRxSs_StubPayloadAllocCallback(void *InstancePtr)
This function is the stub callback for Payload Allocation interrupts.
Driver enables ACT_RX interrupt after invoking user callback for MST setup. InstancePtr is a pointer to the XDpRxSs core instance. Enables ACT_RX interrupt for MST stream synchronization.
static void XDpRxSs_StubNoVideoCallback(void *InstancePtr)
This function is the stub callback for NoVideo interrupts.
Driver performs interrupt management operations before invoking user callback. InstancePtr is a pointer to the XDpRxSs core instance. Enables VBLANK and INFO_PKT interrupts needed after video loss.
static void XDpRxSs_Set_Dec_Clk(XDpRxSs *InstancePtr)
This function sets the decoder clock for the DP RX Subsystem.
InstancePtr is a pointer to the XDpRxSs instance. None.
u32 XDpRxSs_CfgInitialize(XDpRxSs *InstancePtr, XDpRxSs_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the DisplayPort Receiver Subsystem core.
This function must be called prior to using the core. Initialization of the core includes setting up the instance data and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the XDpRxSs core instance. CfgPtr points to the configuration structure associated with the DisplayPort RX Subsystem core. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_DEVICE_NOT_FOUND if sub-core not found.XST_FAILURE if sub-core initialization failed.XST_SUCCESS if XDpRxSs_CfgInitialize successful. None.
References XDpRxSs_Config::BaseAddress, XDpRxSs_UsrOpt::Bpc, XDpRxSs::clk_wiz_abs_addr, XDpRxSs_Config::ClkWizSubCore, XDpRxSs::Config, XDpRxSs_DpSubCore::DpConfig, XDpRxSs::DpPtr, XDpRxSs_Config::DpSubCore, XDpRxSs_Hdcp1xSubCore::Hdcp1xConfig, XDpRxSs_Config::Hdcp1xSubCore, XDpRxSs_Config::Hdcp22Enable, XDpRxSs_Config::HdcpEnable, XDpRxSs_Config::IicSubCore, XDpRxSs_Config::IncludeAxiIic, XDpRxSs_Config::IncludeClkWiz, XDpRxSs::IsReady, XDpRxSs_UsrOpt::LaneCount, XDpRxSs_UsrOpt::LinkRate, XDpRxSs_Config::MaxBpc, XDpRxSs_Config::MaxLaneCount, XDpRxSs_UsrOpt::MstSupport, XDpRxSs_Config::MstSupport, XDpRxSs_Config::NumMstStreams, XDpRxSs_UsrOpt::NumOfStreams, XDpRxSs_Config::TmrCtrSubCore, XDpRxSs::UsrOpt, XDPRXSS_DRV_HANDLER_DP_NO_VID_EVENT, XDPRXSS_DRV_HANDLER_DP_PWR_CHG_EVENT, XDPRXSS_DRV_HANDLER_DP_VID_EVENT, XDpRxSs_DrvNoVideoHandler, XDpRxSs_DrvPowerChangeHandler, XDpRxSs_DrvVideoHandler, XDPRXSS_HDCP_14, XDPRXSS_HDCP_22, XDPRXSS_LANE_COUNT_SET_4, XDPRXSS_LINK_BW_SET_810GBPS, XDpRxSs_SetCallBack, XDpRxSs_SetLaneCount, XDpRxSs_SetLinkRate, XDpRxSs_Start, XDPRXSS_TMRCTR_RST_VAL.
Referenced by DpRxSs_Main.
void XDpRxSs_Reset(XDpRxSs *InstancePtr)
This function resets the DisplayPort Receiver Subsystem including all sub-cores.
InstancePtr is a pointer to the XDpRxSs core instance. IIC needs to be reinitialized after reset.
References XDpRxSs::Config, XDpRxSs::DpPtr, XDpRxSs_Config::HdcpEnable, XDpRxSs_Config::IncludeAxiIic, XDpRxSs_WriteReg.
Referenced by Dp21RxSs_Pt_Setup.
u32 XDpRxSs_Start(XDpRxSs *InstancePtr)
This function starts the DisplayPort Receiver Subsystem including all sub-cores.
InstancePtr is a pointer to the XDpRxSs core instance. XST_SUCCESS, if DP RX Subsystem and its included sub-cores configured successfully.XST_FAILURE, otherwise. None.
References XDpRxSs::DpPtr, XDpRxSs_UsrOpt::MstSupport, XDpRxSs::UsrOpt.
Referenced by Dp21RxSs_Pt_Setup, XDpRxSs_CfgInitialize.
static void DpRxSs_SetEdid(XDpRxSs *InstancePtr)
This static function sets the EDID data to the EDID memory.
InstancePtr is a pointer to the XDpRxSs instance. None.
void XDpRxSs_Setup(XDpRxSs *InstancePtr, XDpRxSs_UserConfig *UserConfigPtr)
This function setup the DisplayPort Receiver Subsystem.
InstancePtr is a pointer to the XDpRxSs core instance. UserConfigPtr is a pointer to the XDpRxSs_UserConfig instance. None.
References XDpRxSs::DpPtr, DpRxSs_RxEnable, XDPRXSS_ALL_INTR_MASK, XDPRXSS_CHANNEL_CODING_OFFSET.
Referenced by DpRxSs_Main.
void DpRxSs_UpdatePrbsErrCouters(XDpRxSs *InstancePtr, u16 Lane0, u16 Lane1, u16 Lane2, u16 Lane3)
This function updates the PRBS error counters of DpRxss.
InstancePtr is a pointer to the XDpRxSs instance. Lane0 is PRBS error counter value of Lane0. Lane1 is PRBS error counter value of Lane1. Lane2 is PRBS error counter value of Lane2. Lane3 is PRBS error counter value of Lane3. None.
References XDpRxSs::DpPtr, XDPRXSS_DPC_L01_PRBS_CNTR_OFFSET, XDPRXSS_DPC_L23_PRBS_CNTR_OFFSET, XDPRXSS_DPC_LANE_PRBS_CNTR_VALID_MASK.
u32 XDpRxSs_SetLinkRate(XDpRxSs *InstancePtr, u8 LinkRate)
This function sets the data rate to be used by the DisplayPort RX Subsystem core.
InstancePtr is a pointer to the XDpRxSs instance. LinkRate is the rate at which link needs to be driven. XDPRXSS_LINK_BW_SET_162GBPS = 0x06(for a 1.62 Gbps data rate)XDPRXSS_LINK_BW_SET_270GBPS = 0x0A(for a 2.70 Gbps data rate)XDPRXSS_LINK_BW_SET_540GBPS = 0x14(for a 5.40 Gbps data rate) XST_SUCCESS if setting the new lane rate was successful.XST_FAILURE otherwise. None.
References XDpRxSs::DpPtr, XDpRxSs_UsrOpt::LinkRate, XDpRxSs::UsrOpt.
Referenced by Dp21RxSs_Pt_Setup, XDpRxSs_CfgInitialize.
u32 XDpRxSs_SetLaneCount(XDpRxSs *InstancePtr, u8 LaneCount)
This function sets the number of lanes to be used by DisplayPort RX Subsystem core.
InstancePtr is a pointer to the XDpRxSs instance. LaneCount is the number of lanes to be used. 1 = XDPRXSS_LANE_COUNT_SET_12 = XDPRXSS_LANE_COUNT_SET_24 = XDPRXSS_LANE_COUNT_SET_4 XST_SUCCESS if setting the new lane count was successful.XST_FAILURE otherwise. None.
References XDpRxSs::DpPtr, XDpRxSs_UsrOpt::LaneCount, XDpRxSs::UsrOpt, XDPRXSS_LANE_COUNT_SET_1, XDPRXSS_LANE_COUNT_SET_2, XDPRXSS_LANE_COUNT_SET_4.
Referenced by Dp21RxSs_Pt_Setup, XDpRxSs_CfgInitialize.
u32 XDpRxSs_ExposePort(XDpRxSs *InstancePtr, u8 Port)
This function allows the user to select number of ports to be exposed when replying to a LINK_ADDRESS sideband message and hides rest of the ports.
InstancePtr is a pointer to the XDpRxSs core instance. Port specifies the number of ports to be exposed within the range 1 to 4. XST_SUCCESS, if ports exposed successfully.XST_FAILURE, if exposing ports which are already exposed or ports are exceeding total number of stream supported by the system. Number of ports are equal to number of streams.
References XDpRxSs::Config, XDpRxSs::DpPtr, XDpRxSs_UsrOpt::MstSupport, XDpRxSs_Config::NumMstStreams, XDpRxSs_UsrOpt::NumOfStreams, XDpRxSs::UsrOpt.
u32 XDpRxSs_CheckLinkStatus(XDpRxSs *InstancePtr)
This function checks if the receiver's DisplayPort Configuration Data (DPCD) indicates that the receiver has achieved clock recovery, channel equalization, symbol lock, and interlane alignment for all lanes currently in use.
InstancePtr is a pointer to the XDpRxSs core instance. XST_SUCCESS if the RX device has achieved clock recovery, channel equalization, symbol lock, and interlane alignment.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_FAILURE otherwise. None.
References XDpRxSs::DpPtr.
void XDpRxSs_SetUserPixelWidth(XDpRxSs *InstancePtr, u8 UserPixelWidth)
This function configures the number of pixels output through the user data interface.
InstancePtr is a pointer to the XDpRxSs core instance. UserPixelWidth is the user pixel width to be configured. None.
References XDpRxSs::DpPtr.
u8 XDpRxss_GetBpc(XDpRxSs *InstancePtr, u8 Stream)
This function extracts the bits per color from MISC0 or VSC SDP packet based on whether reception of colorimetry information through VSC SDP packets or through MISC registers of the stream.
InstancePtr is a pointer to the XDpRxSs core instance. Stream is the stream number to make the calculations for. The bits per color for the stream. RX clock must be stable.
References XDpRxSs::DpPtr.
Referenced by XDpRxss_GetMsa.
u8 XDpRxss_GetInterlace(XDpRxSs *InstancePtr, u8 Stream)
This function extracts the incoming video stream is Progressive or Interlace mode.
InstancePtr is a pointer to the XDpRxSs core instance. Stream is the stream number to make the calculations for. Video timing is Progressive or Interlace. RX clock must be stable.
References XDpRxSs::DpPtr, XDP_RX_STREAM_MSA_OFFSET.
Referenced by XDpRxss_GetMsa, XDpRxSs_GetVideoStream.
u8 XDpRxss_GetColorComponent(XDpRxSs *InstancePtr, u8 Stream)
This function extracts the color component format from MISC0 or VSC SDP packet based on whether reception of colorimetry information through VSC SDP packets or through MISC registers of the stream.
InstancePtr is a pointer to the XDpRxSs core instance. Stream is the stream number to make the calculations for. The color component for the stream. RX clock must be stable.
References XDpRxSs::DpPtr.
Referenced by CalculateCRC, Dp21RxSs_Pt_CalculateCRC, XDpRxss_GetMsa.
u8 XDpRxss_GetColorimetry(XDpRxSs *InstancePtr, u8 Stream)
This function extracts the YCbCrColorimetry from MISC0 or VSC SDP packet based on whether reception of colorimetry information through VSC SDP packets or through MISC registers of the stream.
InstancePtr is a pointer to the XDpRxSs core instance. Stream is the stream number to make the calculations for. The colorimetry format for the stream. RX clock must be stable.
References XDpRxSs::DpPtr.
Referenced by XDpRxss_GetMsa.
u8 XDpRxss_GetDynamicRange(XDpRxSs *InstancePtr, u8 Stream)
This function extracts the dynamic range from MISC0 or VSC SDP packet based on whether reception of colorimetry information through VSC SDP packets or through MISC registers of the stream.
InstancePtr is a pointer to the XDpRxSs core instance. Stream is the stream number to make the calculations for. The dynamic range value for the stream. RX clock must be stable.
References XDpRxSs::DpPtr.
Referenced by XDpRxss_GetMsa.
XDp_MainStreamAttributes * XDpRxss_GetMsa(XDpRxSs *DpRxSsInst)
This function gives the main stream attributes (MSA).
DpRxSsInst is a pointer to the XDpRxSs instance. MSA Config structure
References XDpRxSs::Config, XDpRxSs::DpPtr, XDpRxSs::link_up_trigger, XDpRxSs_UsrOpt::LinkRate, XDpRxSs_Config::NumMstStreams, XDpRxSs::UsrOpt, XDP_RX_STREAM_MSA_OFFSET, XDpRxss_GetBpc, XDpRxss_GetColorComponent, XDpRxss_GetColorimetry, XDpRxss_GetDynamicRange, XDpRxss_GetInterlace.
Referenced by DpRxSs_Main, XDpRxSs_GetVideoStream.
int XDpRxSs_GetVideoStream(XDpRxSs *InstancePtr, XVidC_VideoStream *VideoStream, u8 Stream)
This function retrieves the VideoStream Parameters from the incoming video stream.
InstancePtr is a pointer to the XDpRxSs core instance. VideoStream Pointer to an XVidC_VideoStream structure that will be populated with the extracted video stream information for the requested stream. On success, this function updates (at minimum) the following fields: Timing, FrameRate, VmIdPixPerClk (derived from lane count)ColorDepth, ColorFormatId, ColorStd, DynamicRangeBaseFrameRate, BaseTiming, UncompressedTimingIsInterlaced Stream Stream is the stream number to get the Video data. SUCCESS when video data extraction is success
References XDpRxSs::DpPtr, XDpRxSs_UsrOpt::LaneCount, XDpRxSs::UsrOpt, XDpRxss_GetInterlace, XDpRxss_GetMsa.
u32 XDpRxSs_HandleDownReq(XDpRxSs *InstancePtr)
This function handles incoming sideband messages.
It will 1) Read the contents of the down request registers, 2) Delegate control depending on the request type, and 3) Send a down reply. InstancePtr is a pointer to the XDpRxSs core instance. XST_SUCCESS if the entire message was sent successfully.XST_DEVICE_NOT_FOUND if no device is connected.XST_ERROR_COUNT_MAX if sending one of the message fragments timed out.XST_FAILURE otherwise. None.
References XDpRxSs::DpPtr.
void XDpRxSs_HandleActRxInterrupts(XDpRxSs *InstancePtr)
This function handles ACT (Allocation Change Trigger) received interrupt.
It performs driver-level interrupt management for MST stream changes. InstancePtr is a pointer to the XDpRxSs core instance. This is a driver-level function that manages interrupt enables/disables when ACT sequence is received for MST payload allocation changes.
References XDpRxSs::DpPtr, XDpRxSs::IsReady, XDPRXSS_INTERRUPT1_MASK_MST_ALL.
void XDpRxSs_SetAdaptiveSyncCaps(XDpRxSs *InstancePtr, u32 Enable)
This function sets Adaptive-Sync capabilities to DisplayPort RX Subsystem.
InstancePtr is a pointer to the XDpRxSs instance. Enable is to enable/disable the Adaptive-Sync capabilities in DisplayPort Rx Subsystem None.
References XDpRxSs::DpPtr, XDpRxSs_ReadReg, XDpRxSs_WriteReg.
void XDpRxSs_MaskAdaptiveIntr(XDpRxSs *InstancePtr, u32 Mask)
This function masks the Adaptive-Sync interrupts from DisplayPort RX Subsystem.
InstancePtr is a pointer to the XDpRxSs instance. Mask is a variable contains of Masked value None.
References XDpRxSs::DpPtr, XDpRxSs_ReadReg, XDpRxSs_WriteReg.
void XDpRxSs_UnMaskAdaptiveIntr(XDpRxSs *InstancePtr, u32 Mask)
This function unmasks Adaptive-Sync interrupt from DisplayPort RX Subsystem.
InstancePtr is a pointer to the XDpRxSs instance. Mask to unmask None.
References XDpRxSs::DpPtr, XDpRxSs_ReadReg, XDpRxSs_WriteReg.
int XDpRxSs_GetVblank(XDpRxSs *InstancePtr, u8 Stream)
This function retrieves the current vblank value of the incoming video stream.
InstancePtr is a pointer to the XDpRxSs core instance. Stream Stream is the stream number to get the vblank. The current vblank value This function has to be called after assertion of Bit-30 of XDP_RX_INTERRUPT_CAUSE_2 register
References XDpRxSs::DpPtr, XDpRxSs_ReadReg.
int XDpRxSs_GetVtotal(XDpRxSs *InstancePtr, u8 Stream)
This function retrieves the current VTotal value of the incoming video stream.
InstancePtr is a pointer to the XDpRxSs core instance. Stream is the stream number to get the vtotal. Note: This function has to be called after assertion Bit-30 of XDP_RX_INTERRUPT_CAUSE_2 register The current VTotal value This function has to be called after assertion of Bit-30 of XDP_RX_INTERRUPT_CAUSE_2 register
References XDpRxSs::DpPtr, XDpRxSs_ReadReg.
int XDpRxSs_Get_Dec_Clk_Lock(XDpRxSs *InstancePtr)
This function waits for the decoder clock to lock.
InstancePtr is a pointer to the XDpRxSs instance. XST_SUCCESS if clock is locked, XST_FAILURE otherwise. None.
References XDpRxSs::clk_wiz_abs_addr, XCLK_WIZ_STATUS_OFFSET, XCLK_WIZ_STATUS_RETRY, XCLK_WIZ_STATUS_WAIT, XCLK_WIZ_SWRST_OFFSET, XCLK_WIZ_SWRST_VAL, XDpRxSs_ReadReg, XDpRxSs_WriteReg.
void XDpRxSs_MstEnable(XDpRxSs *InstancePtr, u8 Enable)
Enable/Disable MST mode.
InstancePtr is a pointer to the XDpRxSs instance. Enable is to Enable/Disable Mst mode. If Mst mode is disabled, DpRxss will be in SST mode.
References XDpRxSs::DpPtr.
Referenced by DpRxSs_Main.
u32 XDpRxSs_GetLinkRate(XDpRxSs *InstancePtr)
Get the current link rate from DPCD register.
InstancePtr is a pointer to the XDpRxSs instance. Link rate value read from DPCD_LINK_BW_SET register. None.
References XDpRxSs::DpPtr, XDPRXSS_DPCD_LINK_BW_SET, XDpRxSs_ReadReg.
Referenced by PrintLinkInfo.