xdprxss_dp21_rx.c
XPAR_IIC_0_BASEADDR
INTRNAME_DPRX
XINTC_DPRXSS_DP_INTERRUPT_ID
DPRX subsystem DP interrupt ID for ARM platforms.
XINTC
Interrupt controller type for ARM platforms.
XINTC_DEVICE_ID
Interrupt controller device ID for ARM platforms.
XINTC_HANDLER
Interrupt controller handler for ARM platforms.
XDPRXSS_DEVICE_ID
DP RX Subsystem device ID.
Referenced by main.
XVPHY_DEVICE_ID
Video PHY Controller device ID.
Referenced by DpRxSs_Main.
XTIMER0_DEVICE_ID
Timer Counter device ID.
Referenced by Dp21RxSs_Pt_PlatformInit, DpRxSs_PlatformInit, DpSs_PlatformInit.
VIDEO_CRC_BASEADDR
Video Frame CRC base address.
Referenced by CalculateCRC.
UARTLITE_BASEADDR
UART Lite base address.
VIDPHY_BASEADDR
Video PHY Controller base address.
Referenced by DpRxSs_AccessErrorCounterHandler, DpRxSs_Main.
VID_EDID_BASEADDR
Video EDID base address.
Referenced by DpRxSs_Main.
XIIC_BASEADDRESS
IIC base address for SDT builds.
Referenced by VideoFMC_Init.
DPRXSS_LINK_RATE
Default DP RX link rate configuration.
Referenced by Dp21RxSs_Pt_Setup.
DPRXSS_LANE_COUNT
Default DP RX lane count configuration.
Referenced by Dp21RxSs_Pt_Setup.
DP_BS_IDLE_TIMEOUT
DP blank screen idle timeout value.
Referenced by DpRxSs_Main.
VBLANK_WAIT_COUNT
Vertical blank wait count.
Referenced by DpRxSs_Main.
AUX_DEFER_COUNT
AUX defer count for compliance/interop.
Referenced by DpRxSs_Main, DpRxSs_PllResetHandler.
XVPHY_RX_SYM_ERR_CNTR_CH1_2_REG
Video PHY RX symbol error counter for channels 1 and 2 register offset.
Referenced by DpRxSs_AccessErrorCounterHandler, DpRxSs_Main.
XVPHY_RX_SYM_ERR_CNTR_CH3_4_REG
Video PHY RX symbol error counter for channels 3 and 4 register offset.
Referenced by DpRxSs_AccessErrorCounterHandler, DpRxSs_Main.
XVPHY_DRP_CPLL_FBDIV
Video PHY DRP CPLL feedback divider register address.
Referenced by DpRxSs_Main.
XVPHY_DRP_CPLL_REFCLK_DIV
Video PHY DRP CPLL reference clock divider register address.
Referenced by DpRxSs_Main.
XVPHY_DRP_RXOUT_DIV
Video PHY DRP RX output divider register address.
Referenced by DpRxSs_Main.
XVPHY_DRP_RXCLK25
Video PHY DRP RX clock 25 register address.
XVPHY_DRP_TXCLK25
Video PHY DRP TX clock 25 register address.
XVPHY_DRP_TXOUT_DIV
Video PHY DRP TX output divider register address.
Referenced by DpRxSs_Main.
XVPHY_DRP_RX_DATA_WIDTH
Video PHY DRP RX data width register address.
XVPHY_DRP_RX_INT_DATA_WIDTH
Video PHY DRP RX internal data width register address.
XVPHY_DRP_GTHE4_PRBS_ERR_CNTR_LOWER
Video PHY DRP GTHE4 PRBS error counter lower register address.
Referenced by DpRxSs_AccessErrorCounterHandler, DpRxSs_Main.
XVPHY_DRP_GTHE4_PRBS_ERR_CNTR_UPPER
Video PHY DRP GTHE4 PRBS error counter upper register address.
Referenced by DpRxSs_AccessErrorCounterHandler, DpRxSs_Main.
POLARITY_MASK
Polarity mask for lane polarity configuration.
TIMER_RESET_VALUE
Timer reset value in microseconds.
Referenced by Dp21RxSs_Pt_PlatformInit, DpRxSs_PlatformInit, DpSs_PlatformInit.
XVPHY_DP_LINK_RATE_HZ_1000GBPS
Video PHY DP link rate for 10.0 Gbps.
Referenced by PLLRefClkSel.
XVPHY_DP_LINK_RATE_HZ_1350GBPS
Video PHY DP link rate for 13.5 Gbps.
Referenced by PLLRefClkSel.
XVPHY_DP_LINK_RATE_HZ_2000GBPS
Video PHY DP link rate for 20.0 Gbps.
Referenced by PLLRefClkSel.
XVPHY_DP_REF_CLK_FREQ_HZ_400
Video PHY DP reference clock frequency for 400 MHz.
Referenced by PLLRefClkSel.
PS_IIC_CLK
PS IIC clock frequency in Hz.
Referenced by Dp21RxSs_Pt_PlatformInit, DpRxSs_PlatformInit, DpSs_PlatformInit.
XVphy_PllRefClkSelType VPHY_REFCLK_SEL_270
< VCU118 (270Mhz on REFCLK0, 400Mhz on REFCLK1)
< ZCU102 (270Mhz on REFCLK0, 400Mhz on NORTHREFCLK0)
XVphy_PllRefClkSelType VPHY_REFCLK_SEL_400
XilAudioInfoFrame AudioinfoFrame
XilAudioExtFrame SdpExtFrame
XilAudioExtFrame SdpExtFrame_q
XIicPs Ps_Iic0
XIicPs_Config* XIic0Ps_ConfigPtr
u32 overflow_count
u32 missed_count
XDpRxSs DpRxSsInst
The DPRX Subsystem instance.
XINTC IntcInst
The interrupt controller instance.
XVphy VPhyInst
The DPRX Subsystem instance.
XTmrCtr TmrCtr
Timer instance.
Video_CRC_Config VidFrameCRC
Video Frame CRC instance.
XIic IicInstance
I2C bus for MC6000.
I2C bus for MC6000 and IDT.8K30, 8K24, 5K, 4K120, 4K100 + Audio
unsigned char DpRxEdid[384][384]
u32 DpRxSs_Main(u32 BaseAddress)
This function is the main entry point for the design example using the XDpRxSs driver.
This function will setup the system with interrupts handlers. DeviceId is the unique device ID of the DisplayPort RX Subsystem core. XST_FAILURE if the system setup failed.XST_SUCCESS should never return since this function, if setup was successful, is blocking. If system setup was successful, this function is blocking in order to illustrate interrupt handling taking place for different types interrupts. Refer xdprxss.h file for more info.
References AppHelp, AUX_DEFER_COUNT, XDpRxSs_Config::BaseAddress, CalculateCRC, XDpRxSs::Config, DP_BS_IDLE_TIMEOUT, DpRxSs_PlatformInit, DpRxSs_SetupIntrSystem, DpRxSs_VideoPhyInit, XDpRxSs::EdidBaseAddr, XDpRxSs::EdidDataPtr, XDpRxSs_Config::MstSupport, Print_ExtPkt, Print_InfoPkt, PrintLinkInfo, ReportVideoCRC, Video_CRC_Config::TEST_CRC_SUPPORTED, VBLANK_WAIT_COUNT, XDpRxSs::VBlankCount, VID_EDID_BASEADDR, VIDPHY_BASEADDR, VPhyInst, XDPRXSS_8B10B_CHANNEL_CODING, XDpRxSs_AudioDisable, XDpRxSs_AudioEnable, XDpRxSs_AuxReset, XDPRXSS_CDR_CONTROL_CONFIG_TDLOCK_DP159, XDpRxSs_CdrDisableTimeout, XDpRxSs_CfgInitialize, XDpRxSs_DtgDisable, XDpRxSs_DtgEnable, XDpRxSs_GenerateHpdInterrupt, XDpRxss_GetMsa, XDpRxSs_GetRxResetDisable, XDPRXSS_INTERRUPT_MASK_VBLANK_MASK, XDpRxSs_LookupConfig, XDpRxSs_MstEnable, XDpRxSs_ReportCoreInfo, XDpRxSs_ReportLinkInfo, XDpRxSs_ReportMsaInfo, XDpRxSs_RxInterruptDisable, XDpRxSs_Setup, XDpRxSs_UpdateCdrTimeOutVal, XDpRxSs_UserFifoOverflowStatus, xil_getc, XVPHY_DEVICE_ID, XVPHY_DRP_CPLL_FBDIV, XVPHY_DRP_CPLL_REFCLK_DIV, XVPHY_DRP_GTHE4_PRBS_ERR_CNTR_LOWER, XVPHY_DRP_GTHE4_PRBS_ERR_CNTR_UPPER, XVPHY_DRP_RXOUT_DIV, XVPHY_DRP_TXOUT_DIV, XVPHY_RX_SYM_ERR_CNTR_CH1_2_REG, XVPHY_RX_SYM_ERR_CNTR_CH3_4_REG.
Referenced by main.
u32 DpRxSs_PlatformInit(void)
This function initialize required platform specific peripherals.
XST_SUCCESS if required peripherals are initialized and configured successfully.XST_FAILURE, otherwise. None.
References PS_IIC_CLK, TIMER_RESET_VALUE, TmrCtr, VideoFMC_Init, XTIMER0_DEVICE_ID.
Referenced by DpRxSs_Main.
u32 DpRxSs_VideoPhyInit(u32 Baseaddress)
This function configures Video Phy.
DeviceId is the Video PHY device ID or base address. XST_SUCCESS if Video Phy configured successfully.XST_FAILURE, otherwise. None.
References PLLRefClkSel, VPhyInst.
Referenced by DpRxSs_Main.
void PLLRefClkSel(XVphy *InstancePtr, u8 link_rate)
This function sets proper ref clk frequency and line rate.
InstancePtr is a pointer to the Video PHY instance. link_rate is the link rate to be configured. None.
References VPHY_REFCLK_SEL_270, XVPHY_DP_LINK_RATE_HZ_1000GBPS, XVPHY_DP_LINK_RATE_HZ_1350GBPS, XVPHY_DP_LINK_RATE_HZ_2000GBPS, XVPHY_DP_REF_CLK_FREQ_HZ_400.
Referenced by config_phy, DpRxSs_VideoPhyInit, DpSs_PhyInit.
void AppHelp()
This function prints Menu.
None.
Referenced by DpRxSs_Main.
void ReportVideoCRC()
This function reports CRC values of Video components.
None.
Referenced by DpRxSs_Main.
void CalculateCRC(void)
This function Calculates CRC values of Video components.
None.
References CustomWaitUs, XDpRxSs::DpPtr, Video_CRC_Config::Mode_422, Video_CRC_Config::Pixel_b, Video_CRC_Config::Pixel_g, Video_CRC_Config::Pixel_r, Video_CRC_Config::TEST_CRC_CNT, VIDEO_CRC_BASEADDR, XDPRXSS_MSA_MISC0, XDPRXSS_USER_FIFO_OVERFLOW_STREAM1_MASK, XDpRxSs_UserFifoOverflowStatus.
char XUartPs_RecvByte_NonBlocking()
This function is a non-blocking UART return byte.
Received byte from UART. None.
Referenced by xil_getc.
void CustomWaitUs(void *InstancePtr, u32 MicroSeconds)
This function is called when DisplayPort Subsystem core requires delay or sleep.
It provides timer with predefined amount of loop iterations. InstancePtr is a pointer to the XDp instance. MicroSeconds is the delay time in microseconds. None.
char xil_getc(u32 timeout_ms)
This function to get uart input from user.
timeout_ms received character None.
References TmrCtr, XUartPs_RecvByte_NonBlocking.
Referenced by Dp21RxSs_Pt_Setup, DpRxSs_Main.
u32 DpRxSs_SetupIntrSystem(void)
This function sets up the interrupt system so interrupts can occur for the DisplayPort RX Subsystem core.
The function is application-specific since the actual system may or may not have an interrupt controller. The DPRX Subsystem core could be directly connected to a processor without an interrupt controller. The user should modify this function to fit the application. XST_SUCCESS if interrupt setup was successful.A specific error code defined in "xstatus.h" if an error occurs. None.
References CustomWaitUs, Dprx_InterruptHandlerActRx, Dprx_InterruptHandlerDownReply, Dprx_InterruptHandlerDownReq, Dprx_InterruptHandlerPayloadAlloc, DpRxSs_AccessErrorCounterHandler, DpRxSs_AccessLinkQualHandler, DpRxSs_BWChangeHandler, DpRxSs_CRCTestEventHandler, DpRxSs_ExtPacketHandler, DpRxSs_InfoPacketHandler, DpRxSs_LinkBandwidthHandler, DpRxSs_NoVideoHandler, DpRxSs_PllResetHandler, DpRxSs_PowerChangeHandler, DpRxSs_TrainingDoneHandler, DpRxSs_TrainingLostHandler, DpRxSs_UnplugHandler, DpRxSs_VerticalBlankHandler, DpRxSs_VideoHandler, TmrCtr, XDPRXSS_DRV_HANDLER_DP_VID_EVENT, XDPRXSS_HANDLER_ACCESS_ERROR_COUNTER_EVENT, XDPRXSS_HANDLER_ACCESS_LINK_QUAL_EVENT, XDPRXSS_HANDLER_DP_ACT_RX_EVENT, XDPRXSS_HANDLER_DP_BW_CHG_EVENT, XDPRXSS_HANDLER_DP_CRC_TEST_EVENT, XDPRXSS_HANDLER_DP_DWN_REP_EVENT, XDPRXSS_HANDLER_DP_DWN_REQ_EVENT, XDPRXSS_HANDLER_DP_EXT_PKT_EVENT, XDPRXSS_HANDLER_DP_INFO_PKT_EVENT, XDPRXSS_HANDLER_DP_NO_VID_EVENT, XDPRXSS_HANDLER_DP_PAYLOAD_ALLOC_EVENT, XDPRXSS_HANDLER_DP_PWR_CHG_EVENT, XDPRXSS_HANDLER_DP_TDONE_EVENT, XDPRXSS_HANDLER_DP_TLOST_EVENT, XDPRXSS_HANDLER_DP_VBLANK_EVENT, XDPRXSS_HANDLER_DP_VID_EVENT, XDPRXSS_HANDLER_DP_VM_CHG_EVENT, XDPRXSS_HANDLER_LINKBW_EVENT, XDPRXSS_HANDLER_PLL_RESET_EVENT, XDPRXSS_HANDLER_UNPLUG_EVENT, XDpRxSs_SetCallBack, XDpRxSs_SetUserTimerHandler.
Referenced by DpRxSs_Main, DpSs_SetupIntrSystem.
void DpRxSs_PowerChangeHandler(void *InstancePtr)
This function is the callback function for when the power state interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void DpRxSs_NoVideoHandler(void *InstancePtr)
This function is the callback function for when a no video interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None.
References XDpRxSs::DpPtr, XDpRxSs::no_video_trigger, Video_CRC_Config::TEST_CRC_CNT, Video_CRC_Config::TEST_CRC_SUPPORTED, XDpRxSs::VBlankCount.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void DpRxSs_VerticalBlankHandler(void *InstancePtr)
This function is the callback function for when a vertical blank interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None.
References XDpRxSs::DpPtr, DpTxSsInst, XDpRxSs::VBlankCount.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void DpRxSs_TrainingLostHandler(void *InstancePtr)
This function is the callback function for when a training lost interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None.
References XDpRxSs::DpPtr, DpTxSsInst, XDpRxSs::link_up_trigger, Video_CRC_Config::TEST_CRC_CNT, Video_CRC_Config::TEST_CRC_SUPPORTED, XDpRxSs::VBlankCount, XDpRxSs_AudioDisable.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void DpRxSs_VideoHandler(void *InstancePtr)
This function is the callback function for when a valid video interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None.
References XDpRxSs::DpPtr.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void DpRxSs_InfoPacketHandler(void *InstancePtr)
This function is the callback function for Info Packet Handling.
InstancePtr is a pointer to the XDpRxSs instance. None.
References XDpRxSs::DpPtr, infofifo.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void DpRxSs_ExtPacketHandler(void *InstancePtr)
This function is the callback function for Generic Packet Handling of 32-Bytes payload.
InstancePtr is a pointer to the XDpRxSs instance. None.
References XDpRxSs::DpPtr.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void DpRxSs_TrainingDoneHandler(void *InstancePtr)
This function is the callback function for when the training done interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None.
References XDpRxSs::DpPtr, XDpRxSs_UsrOpt::LaneCount, XDpRxSs::link_up_trigger, XDpRxSs::UsrOpt, XDpRxSs::VBlankCount, XDPRXSS_HDCP_14.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void DpRxSs_UnplugHandler(void *InstancePtr)
This function is the callback function for when the unplug event occurs.
InstancePtr is a pointer to the XDpRxSs instance. None.
References XDpRxSs::DpPtr, DpTxSsInst, XDpRxSs::link_up_trigger, XDpRxSs::no_video_trigger, XDpRxSs::VBlankCount.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void DpRxSs_LinkBandwidthHandler(void *InstancePtr)
This function is the callback function for when the link bandwidth change occurs.
InstancePtr is a pointer to the XDpRxSs instance. None.
References config_phy, XDpRxSs::link_up_trigger, XDpRxSs_UsrOpt::LinkRate, XDpRxSs::no_video_trigger, XDpRxSs::UsrOpt, XDpRxSs::VBlankCount, VPhyInst.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void DpRxSs_PllResetHandler(void *InstancePtr)
This function is the callback function for PLL reset request.
InstancePtr is a pointer to the XDpRxSs instance. None.
References AUX_DEFER_COUNT, XDpRxSs::DpPtr, XDpRxSs::no_video_trigger, VPhyInst.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void DpRxSs_BWChangeHandler(void *InstancePtr)
This function is the callback function for PLL reset request.
InstancePtr is a pointer to the XDpRxSs instance. None.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void DpRxSs_AccessLaneSetHandler(void *InstancePtr)
This function is the callback function for Access lane set request.
InstancePtr is a pointer to the XDpRxSs instance. None.
void DpRxSs_AccessLinkQualHandler(void *InstancePtr)
This function is the callback function for Access link qual request.
InstancePtr is a pointer to the XDpRxSs instance. None.
References XDpRxSs::DpPtr, VPhyInst.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void DpRxSs_AccessErrorCounterHandler(void *InstancePtr)
This function is the callback function for Access prbs error count.
InstancePtr is a pointer to the XDpRxSs instance. None.
References XDpRxSs::DpPtr, VIDPHY_BASEADDR, VPhyInst, XVPHY_DRP_GTHE4_PRBS_ERR_CNTR_LOWER, XVPHY_DRP_GTHE4_PRBS_ERR_CNTR_UPPER, XVPHY_RX_SYM_ERR_CNTR_CH1_2_REG, XVPHY_RX_SYM_ERR_CNTR_CH3_4_REG.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void DpRxSs_CRCTestEventHandler(void *InstancePtr)
This function is the callback function for Test CRC Event request.
InstancePtr is a pointer to the XDpRxSs instance. None.
References XDpRxSs_Config::BaseAddress, XDpRxSs::Config, XDpRxSs::DpPtr.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void Dprx_InterruptHandlerDownReq(void *InstancePtr)
This function handles MST Down Request interrupt.
InstancePtr is a pointer to the XDpRxSs instance. None.
References XDpRxSs::DpPtr.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void Dprx_InterruptHandlerDownReply(void *InstancePtr)
This function handles MST Down Reply interrupt.
InstancePtr is a pointer to the XDpRxSs instance. None.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void Dprx_InterruptHandlerPayloadAlloc(void *InstancePtr)
This function handles MST payload allocation interrupt.
InstancePtr is a pointer to the XDpRxSs instance. None.
References XDpRxSs::DpPtr.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
void Dprx_InterruptHandlerActRx(void *InstancePtr)
This function handles MST ACT (Allocation Change Trigger) interrupt.
InstancePtr is a pointer to the XDpRxSs instance. None.
References XDpRxSs::DpPtr.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_SetUserCallBackHandlers.
int VideoFMC_Init(void)
This function initializes VFMC.
XST_SUCCESS if initialization was successful.XST_FAILURE if an error occurs. None.
References ConfigPtr_IIC, I2C_MUX_ADDR, IicInstance, XIIC_BASEADDRESS.
void Print_InfoPkt()
This function is the callback function for Info Packet Handling.
None.
Referenced by DpRxSs_Main.
void Print_ExtPkt()
This function is the callback function for Ext Packet Handling.
None.
Referenced by DpRxSs_Main.
void enable_caches()
This function enables instruction and data caches.
None.
Referenced by main.
void disable_caches()
This function disables instruction and data caches.
None.
Referenced by main.
int main()
This is the main function for XDpRxSs interrupt example.
If the DpRxSs_Main function which setup the system succeeds, this function will wait for the interrupts.XST_SUCCESS if successful, XST_FAILURE if unsuccessful. Unless setup failed, main will never return since DpRxSs_Main is blocking (it is waiting on interrupts).
References disable_caches, DpRxSs_Main, enable_caches, XDPRXSS_DEVICE_ID.
void PrintLinkInfo()
This function prints the DisplayPort link information.
None.
References XDpRxSs::DpPtr, XDpRxSs_UsrOpt::LaneCount, XDpRxSs::UsrOpt, XDpRxSs_GetLinkRate.
Referenced by DpRxSs_Main.
void XDpRxSs_SetUserCallBackHandlers(void)
This function sets user callback handlers for DP RX Subsystem events.
None.
References Dprx_InterruptHandlerActRx, Dprx_InterruptHandlerDownReply, Dprx_InterruptHandlerDownReq, Dprx_InterruptHandlerPayloadAlloc, DpRxSs_AccessErrorCounterHandler, DpRxSs_AccessLinkQualHandler, DpRxSs_BWChangeHandler, DpRxSs_CRCTestEventHandler, DpRxSs_ExtPacketHandler, DpRxSs_InfoPacketHandler, DpRxSs_LinkBandwidthHandler, DpRxSs_NoVideoHandler, DpRxSs_PllResetHandler, DpRxSs_PowerChangeHandler, DpRxSs_TrainingDoneHandler, DpRxSs_TrainingLostHandler, DpRxSs_UnplugHandler, DpRxSs_VerticalBlankHandler, DpRxSs_VideoHandler, XDPRXSS_HANDLER_ACCESS_ERROR_COUNTER_EVENT, XDPRXSS_HANDLER_ACCESS_LINK_QUAL_EVENT, XDPRXSS_HANDLER_DP_ACT_RX_EVENT, XDPRXSS_HANDLER_DP_BW_CHG_EVENT, XDPRXSS_HANDLER_DP_CRC_TEST_EVENT, XDPRXSS_HANDLER_DP_DWN_REP_EVENT, XDPRXSS_HANDLER_DP_DWN_REQ_EVENT, XDPRXSS_HANDLER_DP_EXT_PKT_EVENT, XDPRXSS_HANDLER_DP_INFO_PKT_EVENT, XDPRXSS_HANDLER_DP_NO_VID_EVENT, XDPRXSS_HANDLER_DP_PAYLOAD_ALLOC_EVENT, XDPRXSS_HANDLER_DP_PWR_CHG_EVENT, XDPRXSS_HANDLER_DP_TDONE_EVENT, XDPRXSS_HANDLER_DP_TLOST_EVENT, XDPRXSS_HANDLER_DP_VBLANK_EVENT, XDPRXSS_HANDLER_DP_VID_EVENT, XDPRXSS_HANDLER_LINKBW_EVENT, XDPRXSS_HANDLER_PLL_RESET_EVENT, XDPRXSS_HANDLER_UNPLUG_EVENT, XDpRxSs_SetCallBack.
void I2C_Scan(u32 BaseAddress)
This function scans VFMC- IIC.
BaseAddress is the IIC base address. None.