xdprxss.h
XDPRXSS_H_
Prevent circular inclusions by using protection macros.
XDPRXSS_DPCD_LINK_BW_SET
DPCD link bandwidth set register.
Referenced by XDpRxSs_GetLinkRate.
XDPRXSS_USER_FIFO_OVERFLOW
User FIFO overflow register.
XDPRXSS_LINE_RESET_DISABLE
Line reset disable register.
XDPRXSS_MIN_VOLTAGE_SWING
Minimum voltage swing register.
XDPRXSS_CDR_CONTROL_CONFIG
CDR control configuration register.
XDPRXSS_MSA_MISC0
MSA MISC0 register.
Referenced by CalculateCRC.
XDPRXSS_INTERRUPT_MASK_INFO_PKT_MASK
Info packet interrupt mask.
XDPRXSS_INTERRUPT_MASK_VBLANK_MASK
Vertical blanking interrupt mask.
Referenced by DpRxSs_Main.
XDPRXSS_INTERRUPT_MASK_ACT_RX_MASK
ACT RX interrupt mask.
XDPRXSS_INTERRUPT_MASK_ALL_MASK
All interrupts mask.
XDPRXSS_INTERRUPT1_MASK_MST_ALL
MST stream interrupts (all 18 bits)
Referenced by XDpRxSs_HandleActRxInterrupts.
XDPRXSS_CDR_CONTROL_CONFIG_TDLOCK_DP159
CDR control config TDLOCK DP159.
Referenced by DpRxSs_Main.
XDpRxSs_TimerHandler
Callback type which represents a custom timer wait handler.
XDpRxSs_DtgEnable
This function macro enables the display timing generator (DTG).
InstancePtr is a pointer to the XDpRxSs core instance. C-style signature: void XDpRxSs_DtgEnable(XDpRxSs *InstancePtr)
Referenced by DpRxSs_Main.
XDpRxSs_DtgDisable
This function macro disables the display timing generator (DTG).
InstancePtr is a pointer to the XDpRxSs core instance. C-style signature: void XDpRxSs_DtgDisable(XDpRxSs *InstancePtr)
Referenced by DpRxSs_Main.
XDpRxSs_AudioEnable
This function macro enables audio stream packets on the main link.
InstancePtr is a pointer to the XDpRxSs core instance. C-style signature: void XDpRxSs_AudioEnable(XDpRxSs *InstancePtr)
Referenced by DpRxSs_Main.
XDpRxSs_AudioDisable
This function macro disables audio stream packets on the main link.
InstancePtr is a pointer to the XDpRxSs core instance. C-style signature: void XDpRxSs_AudioDisable(XDpRxSs *InstancePtr)
Referenced by DpRxSs_Main, DpRxSs_TrainingLostHandler.
XDpRxSs_AudioReset
This function macro resets the reception of audio stream packets on the main link.
InstancePtr is a pointer to the XDpRxSs core instance. C-style signature: void XDpRxSs_AudioReset(XDpRxSs *InstancePtr)
XDP_RX_STREAM_MSA_OFFSET
This function macro enable the stream address.
StreamId is zero for SST, veries for MST. C-style signature: XDP_RX_STREAM_MSA_OFFSET(StreamNumber) i
Referenced by XDpRxss_GetInterlace, XDpRxss_GetMsa.
XDpRxSs_Mst_AudioEnable
This function macro enables MST audio on a given stream on the main link.
InstancePtr is a pointer to the XDpRxSs core instance. StreamId to be enabled audio C-style signature: void XDpRxSs_Mst_AudioEnable(XDpRxSs *InstancePtr, u8 StreamId)
XDpRxSs_Mst_AudioDisable
This function macro disables audio on a given stream on the main link.
InstancePtr is a pointer to the XDpRxSs core instance. None. C-style signature: void XDpRxSs_Mst_AudioDisable(XDpRxSs *InstancePtr)
XDpRxSs_WaitUs
This function macro is the delay/sleep function for the XDpRxSs driver.
InstancePtr is a pointer to the XDpRxSs core instance. MicroSeconds is the number of microseconds to delay/sleep for. C-style signature: void XDpRxSs_WaitUs(XDpRxSs *InstancePtr, u32 MicroSeconds)
DpRxSs_RxEnable
This function macro Enables/Disables the Dp Rx link.
InstancePtr is a pointer to the XDpRxSs core instance. Enable is to enable/disable the Dp Rx link. None. C-style signature: void DpRxSs_RxEnable(XDpRxSs *InstancePtr, u32 Enable)
Referenced by XDpRxSs_Setup.
DpRxSs_GetLinkQualLane
This function macro provides link Quality of Dp Rx lane.
InstancePtr is a pointer to the XDpRxSs core instance. Link quality of lane. C-style signature: u8 DpRxSs_GetLinkQualLane(XDpRxSs *InstancePtr)
XDpRxSs_UserFifoOverflowStatus
This function macro provides user fifo overflow status.
InstancePtr is a pointer to the XDpRxSs core instance. user fifo overflow status. C-style signature: u8 XDpRxSs_UserFifoOverflowStatus(XDpRxSs *InstancePtr)
Referenced by CalculateCRC, DpRxSs_Main.
XDpRxSs_GetRxResetDisable
This function macro provides RX line reset disable status.
InstancePtr is a pointer to the XDpRxSs core instance. RX line reset disable status. C-style signature: u32 XDpRxSs_GetRxResetDisable(XDpRxSs *InstancePtr)
Referenced by DpRxSs_Main.
XDpRxSs_GetRxMstAlloc
This function macro provides the contents of DPCD registers.
InstancePtr is a pointer to the XDpRxSs core instance. DPCD registers content. C-style signature: u8 XDpRxSs_GetRxMstAlloc(XDpRxSs *InstancePtr)
DpRxSs_GetRxAudioInfo
This function macro provides Rx Audio info data.
InstancePtr is a pointer to the XDpRxSs core instance. Index of the registers. Rx audio info. C-style signature: u32 DpRxSs_GetRxAudioInfo(XDpRxSs *InstancePtr, u8 Index)
DpRxSs_GetRxAudioExtInfo
This function macro provides Rx Audio Extension packet data.
InstancePtr is a pointer to the XDpRxSs core instance. Index of the registers. Rx Audio Extension packet data. C-style signature: u32 DpRxSs_GetRxAudioExtInfo(InstancePtr, Index)
DpRxSs_UpdateCdrConfig
This function macro Update the CDR config value of Dp Rx.
InstancePtr is a pointer to the XDpRxSs core instance. CdrConfig is combined value of CDR timeout and timeout disable. None. C-style signature: void DpRxSs_UpdateCdrConfig(XDpRxSs *InstancePtr, u32 CdrConfig)
XDpRxSs_UpdateCdrTimeOutVal
This function macro updates the CDR timeout value (bits [19:0]) without disturbing the Disable Training Timeout bit (bit 30).
InstancePtr is a pointer to the XDpRxSs core instance. TimeOutVal is the timeout value to be set (20-bit value). None. C-style signature: void XDpRxSs_UpdateCdrTimeOutVal(XDpRxSs *InstancePtr, u32 TimeOutVal)
Referenced by DpRxSs_Main.
XDpRxSs_CdrDisableTimeout
This function macro controls the CDR Disable Training Timeout bit (bit 30).
InstancePtr is a pointer to the XDpRxSs core instance. Disable is 1 to disable training timeout, 0 to enable it. None. C-style signature: void XDpRxSs_CdrDisableTimeout(XDpRxSs *InstancePtr, u8 Disable)
Referenced by DpRxSs_Main.
XDpRxSs_AuxReset
This function macro Reset the AUX logic from Dp RX.
InstancePtr is a pointer to the XDpRxSs core instance. AuxReset is AUX logic reset value. None. C-style signature: void XDpRxSs_AuxReset(XDpRxSs *InstancePtr, u8 AuxReset)
Referenced by DpRxSs_Main.
XDpRxSs_GenerateHpdInterrupt
This function macro generates HPD (Hot-Plug-Detect) pulse interrupt.
InstancePtr is a pointer to the XDpRxSs core instance. DurationUs is the duration of the HPD pulse in microseconds. None. C-style signature: void XDpRxSs_GenerateHpdInterrupt(XDpRxSs *InstancePtr, u32 DurationUs)
Referenced by DpRxSs_Main.
XDpRxSs_RxInterruptEnable
This function macro enables RX interrupt.
InstancePtr is a pointer to the XDpRxSs core instance. Mask is the interrupt mask to enable. None. C-style signature: void XDpRxSs_RxInterruptEnable(XDpRxSs *InstancePtr, u32 Mask)
XDpRxSs_RxInterruptDisable
This function macro disables RX interrupt.
InstancePtr is a pointer to the XDpRxSs core instance. Mask is the interrupt mask to disable. None. C-style signature: void XDpRxSs_RxInterruptDisable(XDpRxSs *InstancePtr, u32 Mask)
Referenced by DpRxSs_Main.
XDpRxSs_RxInterruptEnable1
This function macro enables RX interrupt (Interrupt Enable 1 register).
InstancePtr is a pointer to the XDpRxSs core instance. Mask is the interrupt mask to enable. None. C-style signature: void XDpRxSs_RxInterruptEnable1(XDpRxSs *InstancePtr, u32 Mask)
XDpRxSs_RxInterruptDisable1
This function macro disables RX interrupt (Interrupt Enable 1 register).
InstancePtr is a pointer to the XDpRxSs core instance. Mask is the interrupt mask to disable. None. C-style signature: void XDpRxSs_RxInterruptDisable1(XDpRxSs *InstancePtr, u32 Mask)
XDpRxSs_RxAllocatePayloadStream
This function macro allocates payload stream for MST mode.
InstancePtr is a pointer to the XDpRxSs core instance. None. C-style signature: void XDpRxSs_RxAllocatePayloadStream(XDpRxSs *InstancePtr)
XDpRxSs_HdcpProtocol
No content protection.
XDpRxSs_HandlerType
Video mode change event interrupt type for DisplayPort core.
typedef void(* XDpRxSs_Callback)(void *InstancePtr))(void *InstancePtr)
Callback type which represents the handler for events.
InstancePtr is a pointer to the XDpRxSs instance. None.
XDpRxSs_Config * XDpRxSs_LookupConfig(UINTPTR BaseAddress)
This function returns a reference to an XDpRxSs_Config structure based on the core id, DeviceId.
The return value will refer to an entry in the device configuration table defined in the xdprxss_g.c file. DeviceId is the unique core ID of the XDpRxSs core for the lookup operation. XDpRxSs_LookupConfig returns a reference to a config record in the configuration table (in xdprxss_g.c) corresponding to DeviceId, or NULL if no match is found. None.
Referenced by DpRxSs_Main.
u32 XDpRxSs_GetDrvIndex(UINTPTR BaseAddress)
This function returns the Index number of config table using BaseAddress.
Base address of the instance Index number of the config table
u32 XDpRxSs_CfgInitialize(XDpRxSs *InstancePtr, XDpRxSs_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the DisplayPort Receiver Subsystem core.
This function must be called prior to using the core. Initialization of the core includes setting up the instance data and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the XDpRxSs core instance. CfgPtr points to the configuration structure associated with the DisplayPort RX Subsystem core. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_DEVICE_NOT_FOUND if sub-core not found.XST_FAILURE if sub-core initialization failed.XST_SUCCESS if XDpRxSs_CfgInitialize successful. None.
References XDpRxSs_Config::BaseAddress, XDpRxSs_UsrOpt::Bpc, XDpRxSs::clk_wiz_abs_addr, XDpRxSs_Config::ClkWizSubCore, XDpRxSs::Config, XDpRxSs_DpSubCore::DpConfig, XDpRxSs::DpPtr, XDpRxSs_Config::DpSubCore, XDpRxSs_Hdcp1xSubCore::Hdcp1xConfig, XDpRxSs_Config::Hdcp1xSubCore, XDpRxSs_Config::Hdcp22Enable, XDpRxSs_Config::HdcpEnable, XDpRxSs_Config::IicSubCore, XDpRxSs_Config::IncludeAxiIic, XDpRxSs_Config::IncludeClkWiz, XDpRxSs::IsReady, XDpRxSs_UsrOpt::LaneCount, XDpRxSs_UsrOpt::LinkRate, XDpRxSs_Config::MaxBpc, XDpRxSs_Config::MaxLaneCount, XDpRxSs_UsrOpt::MstSupport, XDpRxSs_Config::MstSupport, XDpRxSs_Config::NumMstStreams, XDpRxSs_UsrOpt::NumOfStreams, XDpRxSs_Config::TmrCtrSubCore, XDpRxSs::UsrOpt, XDPRXSS_DRV_HANDLER_DP_NO_VID_EVENT, XDPRXSS_DRV_HANDLER_DP_PWR_CHG_EVENT, XDPRXSS_DRV_HANDLER_DP_VID_EVENT, XDpRxSs_DrvNoVideoHandler, XDpRxSs_DrvPowerChangeHandler, XDpRxSs_DrvVideoHandler, XDPRXSS_HDCP_14, XDPRXSS_HDCP_22, XDPRXSS_LANE_COUNT_SET_4, XDPRXSS_LINK_BW_SET_810GBPS, XDpRxSs_SetCallBack, XDpRxSs_SetLaneCount, XDpRxSs_SetLinkRate, XDpRxSs_Start, XDPRXSS_TMRCTR_RST_VAL.
Referenced by DpRxSs_Main.
u32 XDpRxSs_Start(XDpRxSs *InstancePtr)
This function starts the DisplayPort Receiver Subsystem including all sub-cores.
InstancePtr is a pointer to the XDpRxSs core instance. XST_SUCCESS, if DP RX Subsystem and its included sub-cores configured successfully.XST_FAILURE, otherwise. None.
References XDpRxSs::DpPtr, XDpRxSs_UsrOpt::MstSupport, XDpRxSs::UsrOpt.
Referenced by Dp21RxSs_Pt_Setup, XDpRxSs_CfgInitialize.
void XDpRxSs_Setup(XDpRxSs *InstancePtr, XDpRxSs_UserConfig *UserConfigPtr)
This function setup the DisplayPort Receiver Subsystem.
InstancePtr is a pointer to the XDpRxSs core instance. UserConfigPtr is a pointer to the XDpRxSs_UserConfig instance. None.
References XDpRxSs::DpPtr, DpRxSs_RxEnable, XDPRXSS_ALL_INTR_MASK, XDPRXSS_CHANNEL_CODING_OFFSET.
Referenced by DpRxSs_Main.
void DpRxSs_UpdatePrbsErrCouters(XDpRxSs *InstancePtr, u16 Lane0, u16 Lane1, u16 Lane2, u16 Lane3)
This function updates the PRBS error counters of DpRxss.
InstancePtr is a pointer to the XDpRxSs instance. Lane0 is PRBS error counter value of Lane0. Lane1 is PRBS error counter value of Lane1. Lane2 is PRBS error counter value of Lane2. Lane3 is PRBS error counter value of Lane3. None.
References XDpRxSs::DpPtr, XDPRXSS_DPC_L01_PRBS_CNTR_OFFSET, XDPRXSS_DPC_L23_PRBS_CNTR_OFFSET, XDPRXSS_DPC_LANE_PRBS_CNTR_VALID_MASK.
void XDpRxSs_Reset(XDpRxSs *InstancePtr)
This function resets the DisplayPort Receiver Subsystem including all sub-cores.
InstancePtr is a pointer to the XDpRxSs core instance. IIC needs to be reinitialized after reset.
References XDpRxSs::Config, XDpRxSs::DpPtr, XDpRxSs_Config::HdcpEnable, XDpRxSs_Config::IncludeAxiIic, XDpRxSs_WriteReg.
Referenced by Dp21RxSs_Pt_Setup.
u32 XDpRxSs_SetLinkRate(XDpRxSs *InstancePtr, u8 LinkRate)
This function sets the data rate to be used by the DisplayPort RX Subsystem core.
InstancePtr is a pointer to the XDpRxSs instance. LinkRate is the rate at which link needs to be driven. XDPRXSS_LINK_BW_SET_162GBPS = 0x06(for a 1.62 Gbps data rate)XDPRXSS_LINK_BW_SET_270GBPS = 0x0A(for a 2.70 Gbps data rate)XDPRXSS_LINK_BW_SET_540GBPS = 0x14(for a 5.40 Gbps data rate) XST_SUCCESS if setting the new lane rate was successful.XST_FAILURE otherwise. None.
References XDpRxSs::DpPtr, XDpRxSs_UsrOpt::LinkRate, XDpRxSs::UsrOpt.
Referenced by Dp21RxSs_Pt_Setup, XDpRxSs_CfgInitialize.
u32 XDpRxSs_SetLaneCount(XDpRxSs *InstancePtr, u8 LaneCount)
This function sets the number of lanes to be used by DisplayPort RX Subsystem core.
InstancePtr is a pointer to the XDpRxSs instance. LaneCount is the number of lanes to be used. 1 = XDPRXSS_LANE_COUNT_SET_12 = XDPRXSS_LANE_COUNT_SET_24 = XDPRXSS_LANE_COUNT_SET_4 XST_SUCCESS if setting the new lane count was successful.XST_FAILURE otherwise. None.
References XDpRxSs::DpPtr, XDpRxSs_UsrOpt::LaneCount, XDpRxSs::UsrOpt, XDPRXSS_LANE_COUNT_SET_1, XDPRXSS_LANE_COUNT_SET_2, XDPRXSS_LANE_COUNT_SET_4.
Referenced by Dp21RxSs_Pt_Setup, XDpRxSs_CfgInitialize.
u32 XDpRxSs_ExposePort(XDpRxSs *InstancePtr, u8 Port)
This function allows the user to select number of ports to be exposed when replying to a LINK_ADDRESS sideband message and hides rest of the ports.
InstancePtr is a pointer to the XDpRxSs core instance. Port specifies the number of ports to be exposed within the range 1 to 4. XST_SUCCESS, if ports exposed successfully.XST_FAILURE, if exposing ports which are already exposed or ports are exceeding total number of stream supported by the system. Number of ports are equal to number of streams.
References XDpRxSs::Config, XDpRxSs::DpPtr, XDpRxSs_UsrOpt::MstSupport, XDpRxSs_Config::NumMstStreams, XDpRxSs_UsrOpt::NumOfStreams, XDpRxSs::UsrOpt.
u32 XDpRxSs_CheckLinkStatus(XDpRxSs *InstancePtr)
This function checks if the receiver's DisplayPort Configuration Data (DPCD) indicates that the receiver has achieved clock recovery, channel equalization, symbol lock, and interlane alignment for all lanes currently in use.
InstancePtr is a pointer to the XDpRxSs core instance. XST_SUCCESS if the RX device has achieved clock recovery, channel equalization, symbol lock, and interlane alignment.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_FAILURE otherwise. None.
References XDpRxSs::DpPtr.
u32 XDpRxSs_HandleDownReq(XDpRxSs *InstancePtr)
This function handles incoming sideband messages.
It will 1) Read the contents of the down request registers, 2) Delegate control depending on the request type, and 3) Send a down reply. InstancePtr is a pointer to the XDpRxSs core instance. XST_SUCCESS if the entire message was sent successfully.XST_DEVICE_NOT_FOUND if no device is connected.XST_ERROR_COUNT_MAX if sending one of the message fragments timed out.XST_FAILURE otherwise. None.
References XDpRxSs::DpPtr.
void XDpRxSs_HandleActRxInterrupts(XDpRxSs *InstancePtr)
This function handles ACT (Allocation Change Trigger) received interrupt.
It performs driver-level interrupt management for MST stream changes. InstancePtr is a pointer to the XDpRxSs core instance. This is a driver-level function that manages interrupt enables/disables when ACT sequence is received for MST payload allocation changes.
References XDpRxSs::DpPtr, XDpRxSs::IsReady, XDPRXSS_INTERRUPT1_MASK_MST_ALL.
void XDpRxSs_SetUserPixelWidth(XDpRxSs *InstancePtr, u8 UserPixelWidth)
This function configures the number of pixels output through the user data interface.
InstancePtr is a pointer to the XDpRxSs core instance. UserPixelWidth is the user pixel width to be configured. None.
References XDpRxSs::DpPtr.
u8 XDpRxss_GetBpc(XDpRxSs *InstancePtr, u8 Stream)
This function extracts the bits per color from MISC0 or VSC SDP packet based on whether reception of colorimetry information through VSC SDP packets or through MISC registers of the stream.
InstancePtr is a pointer to the XDpRxSs core instance. Stream is the stream number to make the calculations for. The bits per color for the stream. RX clock must be stable.
References XDpRxSs::DpPtr.
Referenced by XDpRxss_GetMsa.
u8 XDpRxss_GetColorComponent(XDpRxSs *InstancePtr, u8 Stream)
This function extracts the color component format from MISC0 or VSC SDP packet based on whether reception of colorimetry information through VSC SDP packets or through MISC registers of the stream.
InstancePtr is a pointer to the XDpRxSs core instance. Stream is the stream number to make the calculations for. The color component for the stream. RX clock must be stable.
References XDpRxSs::DpPtr.
Referenced by CalculateCRC, Dp21RxSs_Pt_CalculateCRC, XDpRxss_GetMsa.
u8 XDpRxss_GetColorimetry(XDpRxSs *InstancePtr, u8 Stream)
This function extracts the YCbCrColorimetry from MISC0 or VSC SDP packet based on whether reception of colorimetry information through VSC SDP packets or through MISC registers of the stream.
InstancePtr is a pointer to the XDpRxSs core instance. Stream is the stream number to make the calculations for. The colorimetry format for the stream. RX clock must be stable.
References XDpRxSs::DpPtr.
Referenced by XDpRxss_GetMsa.
u8 XDpRxss_GetDynamicRange(XDpRxSs *InstancePtr, u8 Stream)
This function extracts the dynamic range from MISC0 or VSC SDP packet based on whether reception of colorimetry information through VSC SDP packets or through MISC registers of the stream.
InstancePtr is a pointer to the XDpRxSs core instance. Stream is the stream number to make the calculations for. The dynamic range value for the stream. RX clock must be stable.
References XDpRxSs::DpPtr.
Referenced by XDpRxss_GetMsa.
void XDpRxSs_ReportCoreInfo(XDpRxSs *InstancePtr)
Reports information about the DisplayPort RX Subsystem cores.
This function reports list of sub-cores included in DisplayPort RX Subsystem. InstancePtr is a pointer to the XDpRxSs core instance. None.
References XDpRxSs_Config::ColorFormat, XDpRxSs::Config, XDpRxSs::DpPtr, XDpRxSs_Config::HdcpEnable, XDpRxSs_Config::IncludeAxiIic, XDpRxSs_Config::MaxBpc, XDpRxSs_Config::MaxLaneCount, XDpRxSs_Config::MaxNumAudioCh, XDpRxSs_UsrOpt::MstSupport, XDpRxSs_Config::MstSupport, XDpRxSs_Config::NumMstStreams, XDpRxSs_UsrOpt::NumOfStreams, XDpRxSs_Config::SecondaryChEn, XDpRxSs::UsrOpt.
Referenced by DpRxSs_Main.
void XDpRxSs_ReportLinkInfo(XDpRxSs *InstancePtr)
Reports information about the current link status.
This function prints the link status, selected resolution, link rate /lane count symbol error. InstancePtr is a pointer to the XDpRxSs core instance. None.
References XDpRxSs::DpPtr, XDpRxSs_ReadReg.
Referenced by Dp21RxSs_Pt_Setup, DpRxSs_Main.
void XDpRxSs_ReportMsaInfo(XDpRxSs *InstancePtr)
Reports Main Stream Attribute (MSA) information.
This function prints the current main stream attributes from the DisplayPort RX core. InstancePtr is a pointer to the XDpRxSs core instance. None.
References XDpRxSs::Config, XDpRxSs::DpPtr, XDpRxSs_Config::NumMstStreams, XDpRxSs_ReadReg.
Referenced by Dp21RxSs_Pt_Setup, DpRxSs_Main.
void XDpRxSs_ReportDp159BitErrCount(XDpRxSs *InstancePtr)
Reports DP159 bit error count.
InstancePtr is a pointer to the XDpRxSs core instance.
void XDpRxSs_ReportHdcpInfo(XDpRxSs *InstancePtr)
Reports HDCP information and status.
This function prints the debug display info of the HDCP interface. InstancePtr is a pointer to the XDpRxSs core instance. None.
Referenced by Dp21RxSs_Pt_Setup.
u32 XDpRxSs_GetLinkRate(XDpRxSs *InstancePtr)
Get the current link rate from DPCD register.
InstancePtr is a pointer to the XDpRxSs instance. Link rate value read from DPCD_LINK_BW_SET register. None.
References XDpRxSs::DpPtr, XDPRXSS_DPCD_LINK_BW_SET, XDpRxSs_ReadReg.
Referenced by PrintLinkInfo.
u32 XDpRxSs_SelfTest(XDpRxSs *InstancePtr)
Runs a self-test on the DisplayPort RX Subsystem.
This function performs self test on DisplayPort Receiver Subsystem sub-cores. InstancePtr is a pointer to the XDpRxSs core instance. XST_SUCCESS if self test passed.Otherwise, prints self test failed message. None.
References XDpRxSs::Config, XDpRxSs::DpPtr, XDpRxSs_Config::HdcpEnable, XDpRxSs_Config::IncludeAxiIic.
void XDpRxSs_DpIntrHandler(void *InstancePtr)
This function is the interrupt handler for the DisplayPort RX core operating in RX mode.
The application is responsible for connecting this function to the interrupt system. Application beyond this driver is also responsible for providing callbacks to handle interrupts and installing the callbacks using XDpRxSs_SetCallBack() during initialization phase. InstancePtr is a pointer to the XDpRxSs core instance that just interrupted. None.
References XDpRxSs::DpPtr, XDpRxSs::IsReady.
Referenced by Dp21RxSs_Pt_SetupIntrSystem, DpSs_SetupIntrSystem.
u32 XDpRxSs_SetCallBack(XDpRxSs *InstancePtr, u32 HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function Type ---------------------------------------- ----------------------------------- XDPRXSS_HANDLER_DP_VM_CHG_EVENT XDp_RxSetIntrVmChangeHandler XDPRXSS_HANDLER_DP_PWR_CHG_EVENT XDp_RxSetIntrPowerStateHandler XDPRXSS_HANDLER_DP_NO_VID_EVENT XDp_RxSetIntrNoVideoHandler XDPRXSS_HANDLER_DP_VBLANK_EVENT XDp_RxSetIntrVBlankHandler XDPRXSS_HANDLER_DP_TLOST_EVENT XDp_RxSetIntrTrainingLostHandler XDPRXSS_HANDLER_DP_VID_EVENT XDp_RxSetIntrVideoHandler XDPRXSS_HANDLER_DP_INFO_PKT_EVENT XDp_RxSetIntrInfoPktHandler XDPRXSS_HANDLER_DP_EXT_PKT_EVENT XDp_RxSetIntrExtPktHandler XDPRXSS_HANDLER_DP_TDONE_EVENT XDp_RxSetIntrTrainingDoneHandler XDPRXSS_HANDLER_DP_BW_CHG_EVENT XDp_RxSetIntrBwChangeHandler XDPRXSS_HANDLER_DP_DWN_REQ_EVENT XDp_RxSetIntrDownReqHandler XDPRXSS_HANDLER_DP_DWN_REP_EVENT XDp_RxSetIntrDownReplyHandler XDPRXSS_HANDLER_DP_AUD_OVRFLW_EVENT XDp_RxSetIntrAudioOverHandler XDPRXSS_HANDLER_DP_PAYLOAD_ALLOC_EVENT XDp_RxSetIntrPayloadAllocHandler XDPRXSS_HANDLER_DP_ACT_RX_EVENT XDp_RxSetIntrActRxHandler XDPRXSS_HANDLER_DP_CRC_TEST_EVENT XDp_RxSetIntrCrcTestHandler XDPRXSS_HANDLER_HDCP_RPTR_TDSA_EVENT XHdcp1x_SetCallBack XDPRXSS_HANDLER_UNPLUG_EVENT UnplugCallback XDPRXSS_HANDLER_LINKBW_EVENT LinkBwCallback XDPRXSS_HANDLER_PLL_RESET_EVENT PllResetCallback InstancePtr is a pointer to the XDpRxSs core instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XDpRxSs::DpPtr, XDpRxSs::IsReady, XDpRxSs::LinkBwCallback, XDpRxSs::LinkBwRef, XDpRxSs::PllResetCallback, XDpRxSs::PllResetRef, XDpRxSs::UnplugCallback, XDpRxSs::UnplugRef, XDPRXSS_DRV_HANDLER_DP_NO_VID_EVENT, XDPRXSS_DRV_HANDLER_DP_PWR_CHG_EVENT, XDPRXSS_DRV_HANDLER_DP_VID_EVENT, XDPRXSS_HANDLER_DP_ACT_RX_EVENT, XDPRXSS_HANDLER_DP_AUD_OVRFLW_EVENT, XDPRXSS_HANDLER_DP_BW_CHG_EVENT, XDPRXSS_HANDLER_DP_CRC_TEST_EVENT, XDPRXSS_HANDLER_DP_DWN_REP_EVENT, XDPRXSS_HANDLER_DP_DWN_REQ_EVENT, XDPRXSS_HANDLER_DP_EXT_PKT_EVENT, XDPRXSS_HANDLER_DP_EXT_PKT_STREAM_2_EVENT, XDPRXSS_HANDLER_DP_EXT_PKT_STREAM_3_EVENT, XDPRXSS_HANDLER_DP_EXT_PKT_STREAM_4_EVENT, XDPRXSS_HANDLER_DP_INFO_PKT_EVENT, XDPRXSS_HANDLER_DP_INFO_PKT_STREAM_2_EVENT, XDPRXSS_HANDLER_DP_INFO_PKT_STREAM_3_EVENT, XDPRXSS_HANDLER_DP_INFO_PKT_STREAM_4_EVENT, XDPRXSS_HANDLER_DP_NO_VID_EVENT, XDPRXSS_HANDLER_DP_NO_VID_STREAM_2_EVENT, XDPRXSS_HANDLER_DP_NO_VID_STREAM_3_EVENT, XDPRXSS_HANDLER_DP_NO_VID_STREAM_4_EVENT, XDPRXSS_HANDLER_DP_PAYLOAD_ALLOC_EVENT, XDPRXSS_HANDLER_DP_PWR_CHG_EVENT, XDPRXSS_HANDLER_DP_TDONE_EVENT, XDPRXSS_HANDLER_DP_TLOST_EVENT, XDPRXSS_HANDLER_DP_VBLANK_EVENT, XDPRXSS_HANDLER_DP_VBLANK_STREAM_2_EVENT, XDPRXSS_HANDLER_DP_VBLANK_STREAM_3_EVENT, XDPRXSS_HANDLER_DP_VBLANK_STREAM_4_EVENT, XDPRXSS_HANDLER_DP_VID_EVENT, XDPRXSS_HANDLER_DP_VID_STREAM_2_EVENT, XDPRXSS_HANDLER_DP_VID_STREAM_3_EVENT, XDPRXSS_HANDLER_DP_VID_STREAM_4_EVENT, XDPRXSS_HANDLER_DP_VM_CHG_EVENT, XDPRXSS_HANDLER_DP_VM_CHG_STREAM_2_EVENT, XDPRXSS_HANDLER_DP_VM_CHG_STREAM_3_EVENT, XDPRXSS_HANDLER_DP_VM_CHG_STREAM_4_EVENT, XDPRXSS_HANDLER_LINKBW_EVENT, XDPRXSS_HANDLER_PLL_RESET_EVENT, XDPRXSS_HANDLER_UNPLUG_EVENT.
Referenced by DpRxSs_SetupIntrSystem, XDpRxSs_CfgInitialize, XDpRxSs_SetUserCallBackHandlers.
void XDpRxSs_SetUserTimerHandler(XDpRxSs *InstancePtr, XDpRxSs_TimerHandler CallbackFunc, void *CallbackRef)
This function installs a custom delay/sleep function to be used by the DisplayPort RX Subsystem.
InstancePtr is a pointer to the XDpRxSs core instance. CallbackFunc is the address to the callback function. CallbackRef is the user data item (microseconds to delay) that will be passed to the custom sleep/delay function when it is invoked. None.
References XDpRxSs::DpPtr.
Referenced by DpRxSs_SetupIntrSystem.
void XDpRxSs_DrvNoVideoHandler(void *InstancePtr)
This function is the interrupt handler for No Video.
InstancePtr is a pointer to the XDpRxSs core instance that just interrupted. None.
References XDpRxSs::DpPtr, XDpRxSs::IsReady.
Referenced by XDpRxSs_CfgInitialize.
void XDpRxSs_DrvVideoHandler(void *InstancePtr)
This function is for the video interrupt handler.
InstancePtr is a pointer to the XDpRxSs core instance that just interrupted. None.
References XDpRxSs::DpPtr, XDpRxSs::IsReady.
Referenced by XDpRxSs_CfgInitialize.
void XDpRxSs_DrvPowerChangeHandler(void *InstancePtr)
This function is for the power change interrupt handler.
InstancePtr is a pointer to the XDpRxSs core instance that just interrupted. None.
References XDpRxSs::DpPtr, XDpRxSs::IsReady.
Referenced by XDpRxSs_CfgInitialize.
void XDpRxSs_SetAdaptiveSyncCaps(XDpRxSs *InstancePtr, u32 Enable)
This function sets Adaptive-Sync capabilities to DisplayPort RX Subsystem.
InstancePtr is a pointer to the XDpRxSs instance. Enable is to enable/disable the Adaptive-Sync capabilities in DisplayPort Rx Subsystem None.
References XDpRxSs::DpPtr, XDpRxSs_ReadReg, XDpRxSs_WriteReg.
void XDpRxSs_MaskAdaptiveIntr(XDpRxSs *InstancePtr, u32 Mask)
This function masks the Adaptive-Sync interrupts from DisplayPort RX Subsystem.
InstancePtr is a pointer to the XDpRxSs instance. Mask is a variable contains of Masked value None.
References XDpRxSs::DpPtr, XDpRxSs_ReadReg, XDpRxSs_WriteReg.
void XDpRxSs_UnMaskAdaptiveIntr(XDpRxSs *InstancePtr, u32 Mask)
This function unmasks Adaptive-Sync interrupt from DisplayPort RX Subsystem.
InstancePtr is a pointer to the XDpRxSs instance. Mask to unmask None.
References XDpRxSs::DpPtr, XDpRxSs_ReadReg, XDpRxSs_WriteReg.
int XDpRxSs_GetVblank(XDpRxSs *InstancePtr, u8 Stream)
This function retrieves the current vblank value of the incoming video stream.
InstancePtr is a pointer to the XDpRxSs core instance. Stream Stream is the stream number to get the vblank. The current vblank value This function has to be called after assertion of Bit-30 of XDP_RX_INTERRUPT_CAUSE_2 register
References XDpRxSs::DpPtr, XDpRxSs_ReadReg.
int XDpRxSs_GetVtotal(XDpRxSs *InstancePtr, u8 Stream)
This function retrieves the current VTotal value of the incoming video stream.
InstancePtr is a pointer to the XDpRxSs core instance. Stream is the stream number to get the vtotal. Note: This function has to be called after assertion Bit-30 of XDP_RX_INTERRUPT_CAUSE_2 register The current VTotal value This function has to be called after assertion of Bit-30 of XDP_RX_INTERRUPT_CAUSE_2 register
References XDpRxSs::DpPtr, XDpRxSs_ReadReg.
XDp_MainStreamAttributes * XDpRxss_GetMsa(XDpRxSs *DpRxSsInst)
This function gives the main stream attributes (MSA).
DpRxSsInst is a pointer to the XDpRxSs instance. MSA Config structure
References XDpRxSs::Config, XDpRxSs::DpPtr, XDpRxSs::link_up_trigger, XDpRxSs_UsrOpt::LinkRate, XDpRxSs_Config::NumMstStreams, XDpRxSs::UsrOpt, XDP_RX_STREAM_MSA_OFFSET, XDpRxss_GetBpc, XDpRxss_GetColorComponent, XDpRxss_GetColorimetry, XDpRxss_GetDynamicRange, XDpRxss_GetInterlace.
Referenced by DpRxSs_Main, XDpRxSs_GetVideoStream.
int XDpRxSs_GetVideoStream(XDpRxSs *InstancePtr, XVidC_VideoStream *VideoStream, u8 Stream)
This function retrieves the VideoStream Parameters from the incoming video stream.
InstancePtr is a pointer to the XDpRxSs core instance. VideoStream Pointer to an XVidC_VideoStream structure that will be populated with the extracted video stream information for the requested stream. On success, this function updates (at minimum) the following fields: Timing, FrameRate, VmIdPixPerClk (derived from lane count)ColorDepth, ColorFormatId, ColorStd, DynamicRangeBaseFrameRate, BaseTiming, UncompressedTimingIsInterlaced Stream Stream is the stream number to get the Video data. SUCCESS when video data extraction is success
References XDpRxSs::DpPtr, XDpRxSs_UsrOpt::LaneCount, XDpRxSs::UsrOpt, XDpRxss_GetInterlace, XDpRxss_GetMsa.
u8 XDpRxss_GetInterlace(XDpRxSs *InstancePtr, u8 Stream)
This function extracts the incoming video stream is Progressive or Interlace mode.
InstancePtr is a pointer to the XDpRxSs core instance. Stream is the stream number to make the calculations for. Video timing is Progressive or Interlace. RX clock must be stable.
References XDpRxSs::DpPtr, XDP_RX_STREAM_MSA_OFFSET.
Referenced by XDpRxss_GetMsa, XDpRxSs_GetVideoStream.
void XDpRxSs_MstEnable(XDpRxSs *InstancePtr, u8 Enable)
Enable/Disable MST mode.
InstancePtr is a pointer to the XDpRxSs instance. Enable is to Enable/Disable Mst mode. If Mst mode is disabled, DpRxss will be in SST mode.
References XDpRxSs::DpPtr.
Referenced by DpRxSs_Main.
int XDpRxSs_Get_Dec_Clk_Lock(XDpRxSs *InstancePtr)
This function waits for the decoder clock to lock.
InstancePtr is a pointer to the XDpRxSs instance. XST_SUCCESS if clock is locked, XST_FAILURE otherwise. None.
References XDpRxSs::clk_wiz_abs_addr, XCLK_WIZ_STATUS_OFFSET, XCLK_WIZ_STATUS_RETRY, XCLK_WIZ_STATUS_WAIT, XCLK_WIZ_SWRST_OFFSET, XCLK_WIZ_SWRST_VAL, XDpRxSs_ReadReg, XDpRxSs_WriteReg.