xvid_pat_gen.c
XILINX_DISPLAYPORT_VID_BASE_ADDRESS
XILINX_DISPLAYPORT_VID2_BASE_ADDRESS_OFFSET
XILINX_DISPLAYPORT_VID3_BASE_ADDRESS_OFFSET
XILINX_DISPLAYPORT_VID4_BASE_ADDRESS_OFFSET
PatternGeneratorEnable
0 - Pattern Generator Enable
VsyncPolarity
0 Vsync Polarity
HsyncPolarity
0 - Hsync Polarity
DataEnablePolarity
0 - Data Enable Polarity
VsyncWidth
13:0 - Vsync Width
VerticalBackPorch
13:0 - Vertical Back Porch
VerticalFrontPorch
13:0 - Vertical Front Porch
VerticalResolution
13:0 - Vertical Resolution
HsyncWidth
13:0 - Hsync Width
HorizontalBackPorch
13:0 - Horizontal Back Porch
HorizontalFrontPorch
13:0 - Horizontal Front Porch
HorizontalResolution
13:0 - Horizontal Resolution
Framelock_Enable_Delay
31 - Frame lock Enable 10:0 - Frame lock Delay
FrameLock_AlignHsync_LineFrac
16: Frame Lock Align Hsync
10:0 - Frame lock Line Frac
HdColorBarCfg
2:0 - hd color bar cfg
HSBLANK
13:0 - HSBLANK
HSSYNC
13:0 - HSSYNC
HESYNC
13:0 - HESYNC
HEBLNK
13:0 - HEBLNK
VSBLNK
13:0 - VSBLNK
VSSYNC
13:0 - VSSYNC
VESYNC
13:0 - VESYNC
VEBLNK
13:0 - VEBLNK
MISC0
7:0 - MISC0
MISC1
7:0 - MISC1
TestPatternControl
2:0 Test Pattern 4 - En Sw Pattern 8 - Dual Pixel Mode 9 - Quad Pixel Mode
Audio_Control
0: Audio Reset 1: Audio Start 2: Audio Drop
Referenced by Vpg_Reset.
AudioSampleRate_Chcount
3:0 - Audio Sample Rate 11:8 - Audio Channel Count
AudioPatternCH1
AudioPatternCH2
AudioPatternCH3
AudioPatternCH4
AudioPatternCH5
AudioPatternCH6
AudioPatternCH7
AudioPatternCH8
AudioCHStatus1
AudioCHStatus2
AudioCheckStart
0 - Audio check start
Timer
31:0 - Timer
DualPixelMode
QuadPixelMode
OctaPixelMode
PIXEL_MODE
MicrosecToWait
to avoid hang in A53
u32 StreamOffset[4][4]
u8 StreamPattern_vpg[5][5]
static void VidgenSetConfig(XDp *InstancePtr, Vpg_VidgenConfig *VidgenConfig, u8 Stream, u8 VSplitMode, u8 first_time)
This function calculates video pattern generator parameters.
InstancePtr is a pointer to the XDp instance. VidgenConfig is a pointer to Vpg_VidgenConfig that will be used to timing parameters. Stream is the stream number that will be used to ret rive MSA parameters. VSplitMode specifies vertical split mode to be used for splitting resolution vertically. None. None.
static void VidgenWriteConfig(XDp *InstancePtr, Vpg_VidgenConfig *VidgenConfig, u8 Stream)
This function writes timing parameters to Video Pattern Generator core.
InstancePtr is a pointer to the XDp instance. VidgenConfig is a pointer to Vpg_VidgenConfig that will be used to write parameter values into Video Pattern Generator core registers. Stream is the stream number used to identify the steam for which parameters to be written. None. None.
void Vpg_VidgenSetTestPattern(XDp *InstancePtr, u8 Stream)
This function sets pattern to generate in Video Pattern Generator core.
InstancePtr is a pointer to the XDp instance. Stream is the stream number for which to set the pattern. None. None.
Referenced by Vpg_StreamSrcConfigure.
void Vpg_Reset(void)
This function stops audio pattern generator.
None. None.
References Audio_Control, XPatGen_WriteReg.
void Vpg_Audio_start(void)
This function starts audio pattern generator.
None. None.
void Vpg_Audio_stop(void)
This function stops audio pattern generator.
None. None.
Referenced by Dp21RxSs_Pt_Setup.
int Vpg_StreamSrcConfigure(XDp *InstancePtr, u8 VSplitMode, u8 first_time)
This function updates required timing values in Video Pattern Generator core.
InstancePtr is a pointer to the XDp instance. VSplitMode specifies vertical split mode to be used for splitting resolution vertically. XST_SUCCESS if Video pattern configured successfully. None.
References Vpg_VidgenSetTestPattern, XPatGen_WriteReg.
void Vpg_VidgenSetUserPattern(XDp *InstancePtr, u8 Pattern)
This function sets user pattern.
InstancePtr is a pointer to the XDp instance. Pattern number to set with. None. None.
Referenced by Dp21RxSs_Pt_Setup.