dptxss
XDpTxSs_In32
Input Operations.
XDpTxSs_Out32
Output Operations.
XDpTxSs_ReadReg
This macro reads a value from a DisplayPort Transmitter Subsystem register.
A 32 bit read is performed. If the component is implemented in a smaller width, only the least significant data is read from the register. The most significant data will be read as 0. BaseAddress is the base address of the XDpTxSs core instance. RegOffset is the register offset of the register (defined at the top of this file). The 32-bit value of the register. C-style signature: u32 XDpTxSs_ReadReg(UINTPTR BaseAddress, u32 RegOffset)
XDpTxSs_WriteReg
This macro writes a value to a DisplayPort Transmitter Subsystem register.
A 32 bit write is performed. If the component is implemented in a smaller width, only the least significant data is written. BaseAddress is the base address of the XDpTxSs core instance. RegOffset is the register offset of the register (defined at the top of this file) to be written. Data is the 32-bit value to write into the register. None. C-style signature: void XDpTxSs_WriteReg(UINTPTR BaseAddress, u32 RegOffset, u32 Data)
Referenced by XDpTxSs_Reset.
XDpTxSs_HandlerType
A HPD event interrupt type for DisplayPort core.
XDpTxSs_HdcpProtocol
No content protection.
XDpTxSs_HdcpContentStreamType
HDCP Stream Type 0.
XDpTxSs_DisplayIdType7Category
Preferred timing (Options bit 7 set)
XDpTxSs_SubCores DpTxSsSubCores[XPAR_XDPTXSS_NUM_INSTANCES][XPAR_XDPTXSS_NUM_INSTANCES]
XDpTxSs_Config XDpTxSs_ConfigTable[XPAR_XDPTXSS_NUM_INSTANCES][XPAR_XDPTXSS_NUM_INSTANCES]
static void DpTxSs_GetIncludedSubCores(XDpTxSs *InstancePtr, UINTPTR BaseAddress)
This function reports list of cores included in DisplayPort TX Subsystem.
InstancePtr is a pointer to the XDpTxSs core instance. None.
static void DpTxSs_CalculateMsa(XDpTxSs *InstancePtr, u8 Stream)
This function computes multi-stream attribute and populates frame rate, pixel clock and so on.
InstancePtr is a pointer to the XDpTxSs core instance. Stream is the stream number for which the MSA values will be computed for. None. None.
static u32 DpTxSs_CheckRxDeviceMode(XDpTxSs *InstancePtr)
This function checks whether RX device in multi-stream (MST) / Single Stream transport mode.
InstancePtr is a pointer to the XDpTxSs core instance. XST_FAILURE if DisplayPort TX initialization failed or RX device is not connected.XST_SUCCESS if RX device check is successful. None.
static u32 DpTxSs_SetupSubCores(XDpTxSs *InstancePtr)
This function configures DisplayPort TX subsystem sub-cores.
InstancePtr is a pointer to the XDpTxSs core instance. XST_FAILURE if all sub-cores configuration failed.XST_SUCCESS if all sub-cores configuration was successful. None.
u32 XDpTxSs_CfgInitialize(XDpTxSs *InstancePtr, XDpTxSs_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the DisplayPort Transmitter Subsystem core.
This function must be called prior to using the core. Initialization of the core includes setting up the instance data and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the XDpTxSs core instance. CfgPtr points to the configuration structure associated with the DisplayPort TX Subsystem core. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_DEVICE_NOT_FOUND if sub-core not found.XST_FAILURE if sub-core initialization failed.XST_SUCCESS if XDpTxSs_CfgInitialize successful. None.
References XDpTxSs_Config::BaseAddress, XDpTxSs_UsrOpt::Bpc, XDpTxSs::Config, XDpTxSs_DpSubCore::DpConfig, XDpTxSs::DpPtr, XDpTxSs_Config::DpSubCore, XDpTxSs_Config::Hdcp22Enable, XDpTxSs::IsReady, XDpTxSs_Config::MaxBpc, XDpTxSs_UsrOpt::MstSupport, XDpTxSs_Config::MstSupport, XDpTxSs_Config::NumMstStreams, XDpTxSs_UsrOpt::NumOfStreams, XDpTxSs_TmrCtrSubCore::TmrCtrConfig, XDpTxSs_Config::TmrCtrSubCore, XDpTxSs::UsrOpt, XDpTxSs_UsrOpt::VmId, XDpTxSs_UsrOpt::VtcAdjustBs, XDpTxSs_VtcSubCore::VtcConfig, XDpTxSs::VtcPtr, XDpTxSs_Config::VtcSubCore, XDPTXSS_DRV_HANDLER_DP_EXT_PKT_EVENT, XDPTXSS_DRV_HANDLER_DP_HPD_EVENT, XDPTXSS_DRV_HANDLER_DP_HPD_PULSE, XDPTXSS_HDCP_1X, XDPTXSS_HDCP_22, XDPTXSS_HDCP_BOTH, XDpTxSs_HpdEventProcess, XDpTxSs_HpdPulseProcess, XDpTxSs_SetCallBack, XDpTxSs_VtcSetup, XDpTxSs_WriteVscExtPktProcess.
Referenced by DpTxSs_Main.
void XDpTxSs_Reset(XDpTxSs *InstancePtr)
This function resets the DisplayPort Transmitter Subsystem including all sub-cores.
InstancePtr is a pointer to the XDpTxSs core instance. None.
References XDpTxSs::Config, XDpTxSs_DpSubCore::DpConfig, XDpTxSs_Config::DpSubCore, XDpTxSs_Config::NumMstStreams, XDpTxSs::VtcPtr, XDpTxSs_WriteReg.
Referenced by main_loop.
u32 XDpTxSs_Start(XDpTxSs *InstancePtr)
This function starts the DisplayPort Transmitter Subsystem including all sub-cores.
InstancePtr is a pointer to the XDpTxSs core instance. XST_SUCCESS, if DP TX Subsystem and its included sub-cores configured successfully.XST_FAILURE, otherwise. None.
References XDpTxSs_UsrOpt::Bpc, XDpTxSs::DpPtr, XDpTxSs_UsrOpt::MstSupport, XDpTxSs::UsrOpt, XDpTxSs_UsrOpt::VmId, XDpTxSs_DpTxStart, XDPTXSS_INTERRUPT_MASK_ALL_MASK, XDPTXSS_INTERRUPT_MASK_NORMAL_MASK.
Referenced by DpTxSs_HpdPulseCon, DpTxSs_StartTx.
u32 XDpTxSs_StartCustomMsa(XDpTxSs *InstancePtr, XDpTxSs_MainStreamAttributes *MsaConfigCustom)
This function starts the DisplayPort Transmitter Subsystem with custom multi-stream attributes (MSA)including all sub-cores.
InstancePtr is a pointer to the XDpTxSs core instance. MsaConfigCustom is the structure that will be used to copy the main stream attributes from (into InstancePtr->DpPtr->TxInstance.MsaConfig). XST_SUCCESS, if DP TX Subsystem and its included sub-cores configured successfully.XST_FAILURE, otherwise. None.
References XDpTxSs_UsrOpt::Bpc, XDpTxSs::DpPtr, XDpTxSs_UsrOpt::MstSupport, XDpTxSs_UsrOpt::NumOfStreams, XDpTxSs::UsrOpt, XDpTxSs_UsrOpt::VmId, XDpTxSs_DpTxStart, XDpTxSs_MainStreamAttributes.
void XDpTxSs_Stop(XDpTxSs *InstancePtr)
This function disables the DisplayPort Transmitter Subsystem sub-cores.
InstancePtr is a pointer to the XDpTxSs core instance. None.
References XDpTxSs::Config, XDpTxSs::DpPtr, XDpTxSs_Config::NumMstStreams, XDpTxSs::VtcPtr.
Referenced by main_loop.
void XDpTxSs_VtcAdjustBSTimingEnable(XDpTxSs *InstancePtr)
This function enables special timing mode for BS equal timing.
InstancePtr is a pointer to the XDpTxSs core instance. None.
References XDpTxSs::UsrOpt, XDpTxSs_UsrOpt::VtcAdjustBs.
void XDpTxSs_VtcAdjustBSTimingDisable(XDpTxSs *InstancePtr)
This function disables special timing mode for BS equal timing.
InstancePtr is a pointer to the XDpTxSs core instance. None.
References XDpTxSs::UsrOpt, XDpTxSs_UsrOpt::VtcAdjustBs.
u32 XDpTxSs_SetBpc(XDpTxSs *InstancePtr, u8 Bpc)
This function sets the bits per color value of the video stream.
InstancePtr is a pointer to the XDpTxSs instance. Bpc is the new number of bits per color that needs to be set. 6 = XVIDC_BPC_6,8 = XVIDC_BPC_8,10 = XVIDC_BPC_10,12 = XVIDC_BPC_12,16 = XVIDC_BPC_16, XST_SUCCESS, if bits per color set successfully.XST_FAILURE, if bits per color set failed. None.
References XDpTxSs_UsrOpt::Bpc, XDpTxSs::DpPtr, XDpTxSs::UsrOpt.
Referenced by DpTxSs_StartTx, XDpTxSs_SetVideoStream.
u32 XDPTxss_GetMsa(XDpTxSs *InstancePtr, XDpTxSs_MainStreamAttributes *msa_tx)
This function gets the MSA values for the specified video format.
InstancePtr is a pointer to the XDpTxSs instance. msa_tx is the structure that will be used to copy the main stream attributes into (from InstancePtr->DpPtr->TxInstance.MsaConfig). XST_SUCCESS, if MSA values read successfully.XST_FAILURE, if MSA values read failed. Refer xvidc.h for enumerated standard video modes.
References XDpTxSs::DpPtr, XDpTxSs_UsrOpt::NumOfStreams, XDpTxSs::UsrOpt, XDpTxSs_MainStreamAttributes.
u32 XDPTxss_SetMsa(XDpTxSs *InstancePtr, XVidC_VideoStream *VidStream, u8 Stream)
This function sets the MSA values for the specified video format.
InstancePtr is a pointer to the XDpTxSs instance. VidStream is one of the enumerated standard video modes that is used to determine the MSA values to be used. Stream number XST_SUCCESS, if video mode set successfully.XST_FAILURE, if video mode set failed. Refer xvidc.h for enumerated standard video modes.
References XDpTxSs::DpPtr, XDpTxSs_MainStreamAttributes.
Referenced by XDpTxSs_SetVideoStream.
u32 XDpTxSs_SetVideoStream(XDpTxSs *InstancePtr, XVidC_VideoStream *VidStream, u8 Stream)
This function sets the VideoStream structure for the specified video format.
InstancePtr is a pointer to the XDpTxSs instance. VidStream is one of the enumerated standard video modes that is used to determine the MSA values to be used. Stream Streamnumber to set the video params XST_SUCCESS, if video mode set successfully.XST_FAILURE, if video mode set failed. Refer xvidc.h for enumerated standard video modes.
References XDpTxSs_SetBpc, XDPTxss_SetMsa, XDpTxSs_SetVidMode.
u32 XDpTxSs_SetVidMode(XDpTxSs *InstancePtr, XVidC_VideoMode VidMode)
This function sets the standard display mode.
InstancePtr is a pointer to the XDpTxSs instance. VidMode is one of the enumerated standard video modes that is used to determine the MSA values to be used. XST_SUCCESS, if video mode set successfully.XST_FAILURE, if video mode set failed. Refer xvidc.h for enumerated standard video modes.
References XDpTxSs::Config, XDpTxSs_DpSubCore::DpConfig, XDpTxSs_Config::DpSubCore, XDpTxSs_UsrOpt::MstSupport, XDpTxSs::UsrOpt, XDpTxSs_UsrOpt::VmId.
Referenced by DpTxSs_StartTx, XDpTxSs_SetVideoStream.
void XDpTxSs_OverrideSyncPolarity(XDpTxSs *InstancePtr, u8 Stream)
This function overrides the Polarity for Horizontal and Vertical Sync signals.
InstancePtr is a pointer to the XDpTxSs instance. Stream is the stream number for which to change the Polarity. None.
References XDpTxSs::DpPtr.
u32 XDpTxSs_GetLinkRate(XDpTxSs *InstancePtr)
This function gets the data rate to be used by the DisplayPort TX Subsystem core.
InstancePtr is a pointer to the XDpTxSs instance. XST_SUCCESS if setting the new lane rate was successful.XST_FAILURE otherwise. Maximum supported link rate is used if given link rate is greater than the maximum supported link rate.
References XDpTxSs::DpPtr.
Referenced by get_LineRate.
static u8 DpTxSs_EncodeLinkBandwidth(XDpTxSs *InstancePtr, u8 LinkRate)
u32 DpTxSs_SetRepeaterMode(XDpTxSs *InstancePtr, XDp_Tx_LttprMode RepeaterMode)
This function sets the Repeater mode to be used by the DisplayPort TX Subsystem core.
InstancePtr is a pointer to the XDpTxSs instance. RepeaterMode is the rate at which link needs to be driven. XDP_TX_LTTPR_TRANSPARENTXDP_TX_LTTPR_NON_TRANSPARENT XST_SUCCESS if setting the new lane rate was successful.XST_FAILURE otherwise.
References XDpTxSs::DpPtr.
u32 XDpTxSs_SetLinkRate(XDpTxSs *InstancePtr, u8 LinkRate)
This function sets the data rate to be used by the DisplayPort TX Subsystem core.
InstancePtr is a pointer to the XDpTxSs instance. LinkRate is the rate at which link needs to be driven. XDPTXSS_LINK_BW_SET_162GBPS = 0x06(for a 1.62 Gbps data rate)XDPTXSS_LINK_BW_SET_270GBPS = 0x0A(for a 2.70 Gbps data rate)XDPTXSS_LINK_BW_SET_540GBPS = 0x14(for a 5.40 Gbps data rate) XST_SUCCESS if setting the new lane rate was successful.XST_FAILURE otherwise. Maximum supported link rate is used if given link rate is greater than the maximum supported link rate.
References XDpTxSs::DpPtr, XDPTXSS_LINK_BW_SET_10GBPS, XDPTXSS_LINK_BW_SET_135GBPS, XDPTXSS_LINK_BW_SET_162GBPS, XDPTXSS_LINK_BW_SET_20GBPS, XDPTXSS_LINK_BW_SET_270GBPS, XDPTXSS_LINK_BW_SET_540GBPS, XDPTXSS_LINK_BW_SET_810GBPS, XDPTXSS_LINK_BW_SET_SW_10GBPS, XDPTXSS_LINK_BW_SET_SW_135GBPS, XDPTXSS_LINK_BW_SET_SW_20GBPS.
Referenced by DpTxSs_HpdPulseCon, DpTxSs_Main, DpTxSs_StartTx.
u32 XDpTxSs_SetLaneCount(XDpTxSs *InstancePtr, u8 LaneCount)
This function sets the number of lanes to be used by DisplayPort TX Subsystem core.
InstancePtr is a pointer to the XDpTxSs instance. LaneCount is the number of lanes to be used. 1 = XDPTXSS_LANE_COUNT_SET_12 = XDPTXSS_LANE_COUNT_SET_24 = XDPTXSS_LANE_COUNT_SET_4 XST_SUCCESS if setting the new lane count was successful.XST_FAILURE otherwise. Maximum supported lane count is used if given lane count is greater than the maximum supported lane count.
References XDpTxSs::DpPtr, XDPTXSS_LANE_COUNT_SET_1, XDPTXSS_LANE_COUNT_SET_2, XDPTXSS_LANE_COUNT_SET_4.
Referenced by DpTxSs_HpdPulseCon, DpTxSs_Main, DpTxSs_StartTx.
u32 XDpTxSs_SetTransportMode(XDpTxSs *InstancePtr, u8 Mode)
This function sets transport mode (SST/MST).
InstancePtr is a pointer to the XDpTxSs core instance. Mode specifies the type of transport mode that will be set. 0 = Single-Stream Transport mode,1 = Multi-Stream Transport mode, XST_SUCCESS, if transport mode is set successfully to either MST or SST when RX device is MST and mode is less than or equal to supported mode.XST_FAILURE, if setting to already set mode or mode is greater than supported mode. Transport mode is set to either MST or SST when system is MST and RX device is MST capable.
References XDpTxSs::DpPtr, XDpTxSs_UsrOpt::MstSupport, XDpTxSs::UsrOpt.
u32 XDpTxSs_GetRxCapabilities(XDpTxSs *InstancePtr)
This function retrieves the RX device's capabilities from the RX device's DisplayPort Configuration Data (DPCD).
InstancePtr is a pointer to the XDpTxSs core instance. XST_SUCCESS if the DisplayPort Configuration Data was read successfully.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_FAILURE otherwise. None.
References XDpTxSs::DpPtr.
u32 XDpTxSs_GetSinkCapabilities(XDpTxSs *InstancePtr, u8 *SinkCap, u8 *SinkExtendedCap, u8 *MaxLinkrate_128B)
This function retrieves the Sink device's capabilities from the RX device's DisplayPort Configuration Data (DPCD).
InstancePtr is a pointer to the XDp instance. SinkCap Downstream Capabilities. SinkExtendedCap Downstream Extended Capabilities. MaxLinkrate_128B Maximum Link Rate supported by Sink. XST_SUCCESS if the DisplayPort Configuration Data was read successfully.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_FAILURE otherwise. None.
References XDpTxSs::DpPtr.
u32 XDpTxSs_GetEdid(XDpTxSs *InstancePtr, u8 *Edid)
This function retrieves an immediately connected RX device's Extended Display Identification Data (EDID) structure.
InstancePtr is a pointer to the XDpTxSs core instance. Edid is a pointer to the Edid buffer to save to. XST_SUCCESS if the I2C transactions to read the EDID were successful.XST_ERROR_COUNT_MAX if the EDID read request timed out.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_FAILURE otherwise. None.
References XDpTxSs::DpPtr, XDpTxSs::IsReady.
u32 XDpTxSs_GetRemoteEdid(XDpTxSs *InstancePtr, u8 SinkNum, u8 *Edid)
This function retrieves a remote RX device's Extended Display Identification Data (EDID) structure.
InstancePtr is a pointer to the XDpTxSs core instance. SinkNum is the Sink ID in the sink list within the range [0 to 3]. Edid is a pointer to the Edid buffer to save to. XST_SUCCESS if the I2C transactions to read the EDID were successful.XST_ERROR_COUNT_MAX if the EDID read request timed out.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_FAILURE otherwise. None.
References XDpTxSs::DpPtr, XDpTxSs::IsReady.
u32 XDpTxSs_IsConnected(XDpTxSs *InstancePtr)
This function checks if there is a connected RX device to DisplayPort TX Subsystem.
InstancePtr is a pointer to the XDpTxSs core instance. TRUE if there is a connection.FALSE if there is no connection. None.
References XDpTxSs::DpPtr.
Referenced by DpTxSs_HpdEventHandler, DpTxSs_Main, DpTxSs_Setup, XDpTxSs_get_full_edid.
u32 XDpTxSs_CheckLinkStatus(XDpTxSs *InstancePtr)
This function checks if the receiver's DisplayPort Configuration Data (DPCD) indicates the receiver has achieved and maintained clock recovery, channel equalization, symbol lock, and interlane alignment for all lanes currently in use.
InstancePtr is a pointer to the XDpTxSs core instance. XST_SUCCESS if the RX device has maintained clock recovery, channel equalization, symbol lock, and interlane alignment.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_FAILURE otherwise. None.
References XDpTxSs::DpPtr.
Referenced by DpTxSs_StartTx, main_loop.
void XDpTxSs_SetUserPixelWidth(XDpTxSs *InstancePtr, u8 UserPixelWidth, u8 StreamId)
This function configures the number of pixels output through the user data interface.
InstancePtr is a pointer to the XDpTxSs core instance. UserPixelWidth is the user pixel width to be configured. StreamId is the stream number. None.
References XDpTxSs::DpPtr.
u32 XDpTxSs_IsMstCapable(XDpTxSs *InstancePtr)
This function determines whether downstream RX device is MST/SST capable.
InstancePtr is a pointer to the XDpTxSs core instance. XST_SUCCESS if the RX device is MST enabled.XST_FAILURE if the RX device is SST enabled. None.
References XDpTxSs::DpPtr.
u8 XDpTxSs_GetNumOfMstStreams(XDpTxSs *InstancePtr)
This function returns number of downstream MST sink devices enumerated and available for payload allocation .
InstancePtr is a pointer to the XDpTxSs core instance. Number of MST sinks to be enabled for payload allocation None.
References XDpTxSs::DpPtr.
u32 XDpTxSs_CheckVscColorimetrySupport(XDpTxSs *InstancePtr)
This function will check if the immediate downstream RX device capable of receiving colorimetry information through VSC extended SDP packet.
InstancePtr is a pointer to the XDp instance. XST_SUCCESS if the RX device is capable of VSC extended packet.XST_NO_FEATURE if the RX device does not capable of VSC extended packet. None.
References XDpTxSs::DpPtr.
u32 XDpTxSs_SetVscExtendedPacket(XDpTxSs *InstancePtr, XDp_TxVscExtPacket VscPkt)
This function decodes the extended packet payload data bytes and fills up the driver extended packet structure members.
And also copies extended packet header information to the driver structure. InstancePtr is a pointer to the XDp instance. VscPkt is a driver extended packet structure XST_SUCCESS if VSC extended packet is set.XST_FAILURE if VSC extended packet is not set. None.
References XDpTxSs::DpPtr.
void XDpTxss_EnableVscColorimetry(XDpTxSs *InstancePtr, u8 Enable)
This function Enable / Disable the mechanism of sending colorimetry information through VSC extended packet.
InstancePtr is a pointer to the XDp instance. Enable specifies to enable the flag 0 = Disable the sending colorimetry through VSC packet else enable Enable the sending colorimetry through VSC packet None.
References XDpTxSs::DpPtr.
void XDpTxSs_SetHasRedriverInPath(XDpTxSs *InstancePtr, u8 Set)
This function sets software switch that specify whether or not a redriver exits on the DisplayPort output path.
InstancePtr is a pointer to the XDpTxSs core instance. Set establishes that a redriver exists in the DisplayPort output path. 1 = Set redriver in the DisplayPort output path. 0 = Unset redriver in the DisplayPort output path. Set the redriver in the DisplayPort output path before starting the training.
References XDpTxSs::DpPtr.
void XDpTxSs_SendAudioInfoFrame(XDpTxSs *InstancePtr, XDp_TxAudioInfoFrame *xilInfoFrame)
This function sends audio infoframe and configures audio parameters including MAUD/NAUD values based on the current link rate.
InstancePtr is a pointer to the XDpTxSs instance. xilInfoFrame is a pointer to the audio infoframe structure. This function performs the following operations: Disables audioConfigures the audio infoframe packetCalculates and sets MAUD/NAUD based on link rate Enables Audio
References XDpTxSs::DpPtr.
Referenced by main_loop.
XDpTxSs_Config * XDpTxSs_LookupConfig(UINTPTR BaseAddress)
This function returns a reference to an XDptxss_Config structure based on the core id, DeviceId.
The return value will refer to an entry in the device configuration table defined in the xdptxss_g.c file. DeviceId is the unique core ID of the XDpTxSs core for the lookup operation. XDptxss_LookupConfig returns a reference to a config record in the configuration table (in xdptxss_g.c) corresponding to DeviceId, or NULL if no match is found. None.
Referenced by DpTxSs_Main.
u32 XDpTxSs_GetDrvIndex(UINTPTR BaseAddress)
This function returns the Index number of config table using BaseAddress.
Base address of the instance Index number of the config table
void XDpTxSs_ReportCoreInfo(XDpTxSs *InstancePtr)
This function reports list of sub-cores included in DisplayPort TX Subsystem.
InstancePtr is a pointer to the XDpTxSs core instance. None.
References XDpTxSs::Config, XDpTxSs::DpPtr, XDpTxSs_Config::HdcpEnable, XDpTxSs_Config::MaxBpc, XDpTxSs_Config::MaxLaneCount, XDpTxSs_UsrOpt::MstSupport, XDpTxSs_Config::MstSupport, XDpTxSs_Config::NumMstStreams, XDpTxSs_Config::SecondaryChEn, XDpTxSs::UsrOpt, XDpTxSs::VtcPtr.
void XDpTxSs_ReportLinkInfo(XDpTxSs *InstancePtr)
This function prints the link status, selected resolution, bits per color and link/lane count symbol error.
InstancePtr is a pointer to the XDpTxSs core instance. None.
References XDpTxSs_UsrOpt::Bpc, XDpTxSs::DpPtr, XDpTxSs::UsrOpt, XDpTxSs_UsrOpt::VmId.
Referenced by main_loop.
void XDpTxSs_ReportMsaInfo(XDpTxSs *InstancePtr)
This function prints the current main stream attributes from the DisplayPort TX core.
InstancePtr is a pointer to the XDpTxSs core instance. None.
References XDpTxSs::Config, XDpTxSs::DpPtr, XDpTxSs_Config::NumMstStreams.
Referenced by main_loop.
void XDpTxSs_ReportSinkCapInfo(XDpTxSs *InstancePtr)
This function prints the capabilities of the DisplayPort sink.
InstancePtr is a pointer to the XDpTxSs core instance. None.
References XDpTxSs::DpPtr.
Referenced by main_loop.
void XDpTxSs_ReportSplitterInfo(XDpTxSs *InstancePtr)
This function prints the current Dual Splitter information.
InstancePtr is a pointer to the XDpTxSs core instance. None.
void XDpTxSs_ReportVtcInfo(XDpTxSs *InstancePtr)
This function prints the current VTC timing information.
InstancePtr is a pointer to the XDpTxSs core instance. None.
References XDpTxSs::Config, XDpTxSs_Config::NumMstStreams, XDpTxSs::VtcPtr.
Referenced by main_loop.
void XDpTxSs_ReportHdcpInfo(XDpTxSs *InstancePtr)
This function prints the debug display info of the HDCP interface.
InstancePtr is a pointer to the XDpTxSs core instance. None.
u32 XDpTxSs_SelfTest(XDpTxSs *InstancePtr)
This function performs self test on DisplayPort Transmitter Subsystem sub-cores.
InstancePtr is a pointer to the XDpTxSs core instance. XST_SUCCESS if self test passed.XST_FAILURE if self test failed. None.
References XDpTxSs::Config, XDpTxSs::DpPtr, XDpTxSs_Config::HdcpEnable, XDpTxSs_Config::NumMstStreams, XDpTxSs::VtcPtr.
void XDpTxSs_DpIntrHandler(void *InstancePtr)
This function is the interrupt handler for the DisplayPort TX core operating in TX mode.
The application is responsible for connecting this function to the interrupt system. Application beyond this driver is also responsible for providing callbacks to handle interrupts and installing the callbacks using XDpTxSs_SetCallBack() during initialization phase. InstancePtr is a pointer to the XDpTxSs core instance that just interrupted. None.
References XDpTxSs::DpPtr, XDpTxSs::IsReady.
Referenced by DpTxSs_SetupIntrSystem.
u32 XDpTxSs_SetCallBack(XDpTxSs *InstancePtr, u32 HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function HandlerType ---------------------------------------- ------------------------------------ (XDPTXSS_HANDLER_DP_HPD_EVENT) XDP_TX_HANDLER_HPDEVENT (XDPTXSS_HANDLER_DP_HPD_PULSE) XDP_TX_HANDLER_HPDPULSE (XDPTXSS_HANDLER_DP_LANE_COUNT_CHG) XDP_TX_HANDLER_LANECNTCHANGE (XDPTXSS_HANDLER_DP_LINK_RATE_CHG) XDP_TX_HANDLER_LINKRATECHANGE (XDPTXSS_HANDLER_DP_PE_VS_ADJUST) XDP_TX_HANDLER_PEVSADJUST (XDPTXSS_HANDLER_DP_EXT_PKT_EVENT) XDP_TX_HANDLER_EXTPKT_TXD (XDPTXSS_DRV_HANDLER_DP_EXT_PKT_EVENT) XDP_TX_HANDLER_DRV_EXTPKT_TXD (XDPTXSS_HANDLER_DP_VSYNC) XDP_TX_HANDLER_VSYNC (XDPTXSS_HANDLER_HDCP_RPTR_EXCHG) XHdcp1x_SetCallBack (XDPTXSS_HANDLER_DP_SET_MSA) XDP_TX_HANDLER_SETMSA InstancePtr is a pointer to the XDpTxSs core instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XDpTxSs::DpPtr, XDpTxSs::IsReady, XDPTXSS_DRV_HANDLER_DP_EXT_PKT_EVENT, XDPTXSS_DRV_HANDLER_DP_HPD_EVENT, XDPTXSS_DRV_HANDLER_DP_HPD_PULSE, XDPTXSS_HANDLER_DP_EXT_PKT_EVENT, XDPTXSS_HANDLER_DP_FFE_PRESET_ADJUST, XDPTXSS_HANDLER_DP_HPD_EVENT, XDPTXSS_HANDLER_DP_HPD_PULSE, XDPTXSS_HANDLER_DP_LANE_COUNT_CHG, XDPTXSS_HANDLER_DP_LINK_RATE_CHG, XDPTXSS_HANDLER_DP_PE_VS_ADJUST, XDPTXSS_HANDLER_DP_SET_MSA, XDPTXSS_HANDLER_DP_VSYNC.
Referenced by XDpTxSs_CfgInitialize.
void XDpTxSs_SetUserTimerHandler(XDpTxSs *InstancePtr, XDpTxSs_TimerHandler CallbackFunc, void *CallbackRef)
This function installs a custom delay/sleep function to be used by the DisplayPort TX Subsystem.
InstancePtr is a pointer to the XDpTxSs instance. CallbackFunc is the address to the callback function. CallbackRef is the user data item (microseconds to delay) that will be passed to the custom sleep/delay function when it is invoked. None.
References XDpTxSs::DpPtr.
void XDpTxSs_HpdEventProcess(void *InstancePtr)
This function is process some DP driver read as per DP spec on HPD EVENT.
InstancePtr is a pointer to the XDpTxSs core instance that just interrupted. None.
References XDpTxSs::DpPtr, XDpTxSs::IsReady, XDpTxSs::UsrHpdEventData.
Referenced by XDpTxSs_CfgInitialize.
void XDpTxSs_HpdPulseProcess(void *InstancePtr)
This function is process some DP driver read as per DP spec on HPD Pulse.
InstancePtr is a pointer to the XDpTxSs core instance that just interrupted. None.
References XDpTxSs::DpPtr, XDpTxSs::IsReady, XDpTxSs::UsrHpdPulseData.
Referenced by XDpTxSs_CfgInitialize.
void XDpTxSs_WriteVscExtPktProcess(void *InstancePtr)
This function writes the pixel encoding format and colorimetry formats in to the extended packet registers at DP TX offset addresses "0x0330 to 0x0350".
InstancePtr is a pointer to the XDpTxSs core instance that just interrupted. None.
References XDpTxSs::DpPtr.
Referenced by XDpTxSs_CfgInitialize.
int XDpTxSs_get_full_edid(XDpTxSs *InstancePtr, XDpTxSs_Sink_AV_Capabilities *AVCaps)
This function reads the full EDID (base block + all extensions) from the connected monitor, validates header and checksum, and stores it in the AVCaps structure's embedded buffer.
InstancePtr is a pointer to the XDpTxSs instance. AVCaps is a pointer to XDpTxSs_Sink_AV_Capabilities structure where EDID will be stored in AVCaps->EdidBuffer and extension count in AVCaps->extensions_count. XST_SUCCESS if all EDID blocks read and Base block validated successfully. XST_FAILURE if instance/structure pointer invalid, monitor not connected, EDID read fails, or EDID header/checksum invalid. This function validates base EDID header and checksum. Extension count is limited to MAX_EXTENSIONS_SUPPORTED. Each EDID block is 128 bytes.
References XDpTxSs::DpPtr, XDpTxSs_Sink_AV_Capabilities::EdidBuffer, XDpTxSs_Sink_AV_Capabilities::extensions_count, MAX_EXTENSIONS_SUPPORTED, XDpTxSs_IsConnected.
int XDpTxSs_get_sink_AV_Capabilities(XDpTxSs_Sink_AV_Capabilities *AVCaps)
This function parses complete Audio/Video capabilities and timings from embedded EDID buffer by aggregating data from base EDID, CTA-861, and DisplayID extension blocks.
AVCaps is a pointer to XDpTxSs_Sink_AV_Capabilities structure with EDID already loaded in AVCaps->EdidBuffer. On return, AVCaps->checksum_failures will contain the count of extension blocks with checksum errors (0 if all blocks valid). XST_SUCCESS if all blocks are parsed successfully XST_FAILURE if any error is encountered EDID must be loaded via XDpTxSs_get_full_edid() before calling. Maximum SAD_count is limited to MAX_SAD_COUNT. Maximum timing count is limited to EDID_MAX_TIMINGS. CTA-861 blocks are optional (success returned if none found). DisplayID blocks are optional (success returned if none found). Speaker allocation is OR'd across all CTA-861 blocks. If arrays fill up, parsing continues but additional entries ignored. Video timings are parsed by calling XDpTxSs_GetVideoTimingsFromEdid() internally and stored in AVCaps->TimingList[] in priority order. Parse statistics from both CTA-861 and DisplayID blocks are accumulated and reported in the summary.
References XDpTxSs_AudioSAD::AudioFormatCode, XDpTxSs_AudioSAD::BitDepthFlags, XDpTxSs_Sink_AV_Capabilities::checksum_failures, CTA861_AUDIO_DATA_BLOCK, CTA861_EXTENSION_TAG, CTA861_SPKR_ALLOC_DATA_BLOCK, XDpTxSs_Sink_AV_Capabilities::EdidBuffer, XDpTxSs_Sink_AV_Capabilities::extensions_count, XDpTxSs_AudioSAD::FormatDependent, XDpTxSs_ParseResult::InvalidBlockCount, MAX_SAD_COUNT, XDpTxSs_AudioSAD::MaxBitrate, XDpTxSs_Sink_AV_Capabilities::MaxBpc, XDpTxSs_AudioSAD::MaxChannels, XDpTxSs_SinkAudioCfg::SAD_array, SAD_AUDIO_FORMAT_MASK, SAD_AUDIO_FORMAT_SHIFT, SAD_BIT_DEPTH_MASK, XDpTxSs_SinkAudioCfg::SAD_count, SAD_MAX_BITRATE_MASK, SAD_MAX_CHANNELS_MASK, SAD_SAMPLING_FREQ_MASK, XDpTxSs_AudioSAD::SamplingFreqFlags, XDpTxSs_Sink_AV_Capabilities::SinkAudioCfg, XDpTxSs_SinkAudioCfg::Speaker_channel_allocation, XDpTxSs_Sink_AV_Capabilities::SupportedColorFormats, XDpTxSs_Sink_AV_Capabilities::TimingCount, XDpTxSs_ParseResult::TotalBlockCount, XDpTxSs_GetVideoTimingsFromEdid.
static void XDpTxSs_FillEstablishedTiming(XDpTxSs_VideoTimingParam *Timing, u16 HActive, u16 VActive, u8 RefreshRate)
Helper function to fill established timing with known values and zero-fill unavailable parameters.
Timing is the XDpTxSs_VideoTimingParam structure to populate. HActive is the horizontal active pixels. VActive is the vertical active lines. RefreshRate is the refresh rate in Hz.
static void XDpTxSs_FillStandardTiming(XDpTxSs_VideoTimingParam *Timing, u16 HActive, u16 VActive, u8 AspectRatio, u8 RefreshRate)
Helper function to fill standard timing with known values and zero-fill unavailable parameters.
Timing is the XDpTxSs_VideoTimingParam structure to populate. HActive is the horizontal active pixels. VActive is the vertical active lines. AspectRatio is the aspect ratio code (0-3). RefreshRate is the refresh rate in Hz.
static void XDpTxSs_ConvertTimingParamToVideoTiming(const XV_VidC_TimingParam *TimingParam, XDpTxSs_VideoTimingParam *VideoTiming)
This function converts XV_VidC_TimingParam to XDpTxSs_VideoTimingParam format.
TimingParam is the source timing parameter structure. VideoTiming is the destination XDpTxSs_VideoTimingParam structure.
static XDpTxSs_ParseResult XDpTxSs_ValidateDisplayId2_0Blocks(XDpTxSs_Sink_AV_Capabilities *AVCaps)
This function validates all DisplayID 2.0 extension blocks by checking checksums.
Called once to count total and invalid DisplayID blocks. AVCaps is a pointer to the AV capabilities structure with EDID in AVCaps->EdidBuffer. XDpTxSs_ParseResult with TotalBlockCount and InvalidBlockCount.
static int XDpTxSs_ParseDisplayIdType7(XDpTxSs_Sink_AV_Capabilities *AVCaps, XDpTxSs_DisplayIdType7Category Category)
This function parses DisplayID 2.0 extension blocks and extracts Type VII detailed timings based on the specified category filter (Preferred/Native/Remaining).
This function assumes that blocks have been pre-validated. AVCaps is a pointer to the AV capabilities structure with EDID in AVCaps->EdidBuffer. Timings will be stored in AVCaps->TimingList[] and AVCaps->TimingCount is updated with the number of timings added. Category specifies which timing category to extract: DISPLAYID_TYPE7_PREFERRED: Timings with Preferred flag (Options bit 7)DISPLAYID_TYPE7_NATIVE: Timings with Native flag (Options bit 6, Preferred clear)DISPLAYID_TYPE7_REMAINING: All other timings (both flags clear) XST_SUCCESS if parsing completed. XST_FAILURE if AVCaps pointer is invalid. This function does NOT validate checksums - caller must validate first. DisplayID 2.0 Type VII Timing Descriptor Structure (20 bytes)
XDpTxSs_ParseResult XDpTxSs_GetVideoTimingsFromEdid(XDpTxSs_Sink_AV_Capabilities *AVCaps)
This function extracts video timings from an EDID structure and populates the timing list within an AV capabilities structure in priority order.
Index 0 contains the highest priority timing (preferred timing) from the sink.Priority order (EdidTimingPriority enum): PRIORITY_DISPLAYID_PREFERRED - DisplayID 2.0 Type VII PreferredPRIORITY_BASE_DTD1_PREFERRED - Base EDID DTD #1 (EDID spec mandated preferred)PRIORITY_DISPLAYID_NATIVE - DisplayID 2.0 Type VII NativePRIORITY_DISPLAYID_DTD_OTHER - DisplayID 2.0 Type VII (remaining DTDs)PRIORITY_BASE_DTD_OTHER - Base EDID DTD #2-4PRIORITY_STANDARD_TIMINGS - Base EDID Standard TimingsPRIORITY_ESTABLISHED_TIMINGS - Base EDID Established Timings AVCaps is a pointer to the XDpTxSs_Sink_AV_Capabilities structure with EDID loaded in AVCaps->EdidBuffer. Timings are stored in AVCaps->TimingList[] (max EDID_MAX_TIMINGS) and count in AVCaps->TimingCount. XDpTxSs_ParseResult structure with parse statistic This function is typically called internally by XDpTxSs_get_sink_AV_Capabilities(). The caller must ensure the base EDID header and checksum have been validated before calling. The AVCaps structure must be allocated by the caller.
References DISPLAYID_TYPE7_NATIVE, DISPLAYID_TYPE7_PREFERRED, DISPLAYID_TYPE7_REMAINING, EDID_DTD_SIZE, EDID_MAX_TIMINGS, XDpTxSs_Sink_AV_Capabilities::EdidBuffer, XDpTxSs_ParseResult::InvalidBlockCount, XDpTxSs_Sink_AV_Capabilities::TimingCount, XDpTxSs_Sink_AV_Capabilities::TimingList, XDpTxSs_ParseResult::TotalBlockCount.
Referenced by XDpTxSs_get_sink_AV_Capabilities.
void XDpTxSs_PrintVideoTiming(const XDpTxSs_VideoTimingParam *Timing, u8 Index)
This function prints debug information about a video timing.
Timing is the video timing structure to print. Index is the index number to display.
References XDpTxSs_VideoTimingParam::AspectRatio, XDpTxSs_VideoTimingParam::F0PVBackPorch, XDpTxSs_VideoTimingParam::F0PVFrontPorch, XDpTxSs_VideoTimingParam::F0PVSyncWidth, XDpTxSs_VideoTimingParam::F0PVTotal, XDpTxSs_VideoTimingParam::HActive, XDpTxSs_VideoTimingParam::HBackPorch, XDpTxSs_VideoTimingParam::HFrontPorch, XDpTxSs_VideoTimingParam::HSyncPolarity, XDpTxSs_VideoTimingParam::HSyncWidth, XDpTxSs_VideoTimingParam::HTotal, XDpTxSs_VideoTimingParam::PixelClockHz, XDpTxSs_VideoTimingParam::RefreshRate, XDpTxSs_VideoTimingParam::TimingSource, XDpTxSs_VideoTimingParam::VActive, XDpTxSs_VideoTimingParam::VSyncPolarity.
XDPTXSS_H_
Prevent circular inclusions by using protection macros.
XPAR_XHDCP_NUM_INSTANCES
XDPTXSS_REG_ENHANCED_FRAME_EN_STREAM_1
Enhanced frame enable for stream 1.
XDPTXSS_REG_ENHANCED_FRAME_EN_STREAM_2
Enhanced frame enable for stream 2.
XDPTXSS_REG_TRAINING_PATTERN_STREAM_3
Training pattern for stream 3.
XDPTXSS_REG_TRAINING_PATTERN_STREAM_4
Training pattern for stream 4.
XDPTXSS_REG_STREAM_ZERO
No stream encryption.
XDPTXSS_REG_ALL_STREAMS_ENCRYPT
Encrypt all streams.
XDpTxSs_TimerHandler
Callback type which represents a custom timer wait handler.
XDpTxSs_MainStreamAttributes
Main-Stream attributes.
Referenced by XDPTxss_GetMsa, XDPTxss_SetMsa, XDpTxSs_StartCustomMsa.
XDpTxSs_CfgMsaEnSynchClkMode
This function enables or disables synchronous clock mode for a video stream.
InstancePtr is a pointer to the XDp instance. Stream is the stream number for which to enable or disable synchronous clock mode. Enable if set to 1, will enable synchronous clock mode. Otherwise, if set to 0, synchronous clock mode will be disabled. None. C-style signature: void XDp_TxCfgMsaEnSynchClkMode(XDpTxSs *InstancePtr, u8 Stream, u8 Enable)
XDpTxSs_Mst_AudioEnable
This function macro enables MST-TX audio on a given stream on the main link.
InstancePtr is a pointer to the XDpTxSs core instance. StreamId to be enabled audio None. C-style signature: void XDpTxSs_Mst_AudioEnable(XDpTxSs *InstancePtr, u8 StreamId)
XDpTxSs_Mst_AudioDisable
This function macro disables audio on a given stream on the main link.
InstancePtr is a pointer to the XDpTxSs core instance. None. C-style signature: void XDpTxSs_Mst_AudioDisable(XDpTxSs *InstancePtr)
EDID_DEBUG
Enable verbose EDID parsing debug output (0=disabled, 1=enabled)
EDID_MAX_TIMINGS
Maximum number of timings to return.
Referenced by XDpTxSs_GetVideoTimingsFromEdid.
EDID_DTD_SIZE
EDID Detailed Timing Descriptor size in bytes (18 bytes)
Referenced by XDpTxSs_GetVideoTimingsFromEdid.
MAX_EXTENSIONS_SUPPORTED
EDID parsing limits.
Maximum EDID extension blocks to process
Referenced by XDpTxSs_get_full_edid.
MAX_SAD_COUNT
Maximum Short Audio Descriptors to store.
Referenced by XDpTxSs_get_sink_AV_Capabilities.
CTA861_EXTENSION_TAG
CTA-861 extension block tag (0x02) for audio/video capability data.
Referenced by XDpTxSs_get_sink_AV_Capabilities.
DISPLAYID_2_0_EXTENSION_TAG
DisplayID 2.0 extension block tag (0x70) for detailed timing data.
DISPLAYID_TYPE_VII_TAG
DisplayID Type VII timing descriptor tag (0x22)
CTA861_AUDIO_DATA_BLOCK
CTA-861 audio data block tag (0x01) containing Short Audio Descriptors.
Referenced by XDpTxSs_get_sink_AV_Capabilities.
CTA861_SPKR_ALLOC_DATA_BLOCK
CTA-861 speaker allocation data block tag (0x04) for channel mapping.
Referenced by XDpTxSs_get_sink_AV_Capabilities.
TIMING_SOURCE_DTD
Timing Source Definitions.
Detailed Timing Descriptor
TIMING_SOURCE_STANDARD
Standard Timing.
TIMING_SOURCE_ESTABLISHED
Established Timing.
SAD_AUDIO_FORMAT_SHIFT
Bit shift value (3) to extract audio format code from SAD byte 0.
Referenced by XDpTxSs_get_sink_AV_Capabilities.
SAD_AUDIO_FORMAT_MASK
Bitmask (0x1F) for audio format code field in SAD byte 0 (bits 3-7)
Referenced by XDpTxSs_get_sink_AV_Capabilities.
SAD_MAX_CHANNELS_MASK
Bitmask (0x07) for maximum channel count in SAD byte 0 (bits 0-2)
Referenced by XDpTxSs_get_sink_AV_Capabilities.
SAD_SAMPLING_FREQ_MASK
Bitmask (0x7F) for supported sampling frequencies in SAD byte 1.
Referenced by XDpTxSs_get_sink_AV_Capabilities.
SAD_BIT_DEPTH_MASK
Bitmask (0x07) for LPCM bit depth flags in SAD byte 2 (16/20/24-bit)
Referenced by XDpTxSs_get_sink_AV_Capabilities.
SAD_MAX_BITRATE_MASK
Bitmask (0xFF) for maximum bitrate in SAD byte 2 (compressed formats)
Referenced by XDpTxSs_get_sink_AV_Capabilities.
XDPTXSS_HW_H_
Prevent circular inclusions by using protection macros.
XDPTXSS_LINK_BW_SET_162GBPS
1.62 Gbps link rate.
Referenced by XDpTxSs_SetLinkRate.
XDPTXSS_LINK_BW_SET_270GBPS
2.70 Gbps link rate.
Referenced by XDpTxSs_SetLinkRate.
XDPTXSS_LINK_BW_SET_540GBPS
5.40 Gbps link rate.
Referenced by XDpTxSs_SetLinkRate.
XDPTXSS_LINK_BW_SET_810GBPS
8.10 Gbps link rate.
Referenced by XDpTxSs_SetLinkRate.
XDPTXSS_LINK_BW_SET_10GBPS
10 Gbps link rate.
Referenced by XDpTxSs_SetLinkRate.
XDPTXSS_LINK_BW_SET_20GBPS
20 Gbps link rate.
Referenced by XDpTxSs_SetLinkRate.
XDPTXSS_LINK_BW_SET_135GBPS
13.5 Gbps link rate.
Referenced by XDpTxSs_SetLinkRate.
XDPTXSS_LINK_BW_SET_SW_10GBPS
10 Gbps link rate.
internal reference
Referenced by XDpTxSs_SetLinkRate.
XDPTXSS_LINK_BW_SET_SW_20GBPS
20 Gbps link rate.
internal reference
Referenced by XDpTxSs_SetLinkRate.
XDPTXSS_LINK_BW_SET_SW_135GBPS
13.5 Gbps link rate.
internal reference
Referenced by XDpTxSs_SetLinkRate.
XDPTXSS_LANE_COUNT_SET_1
Lane count of 1.
Referenced by XDpTxSs_SetLaneCount.
XDPTXSS_LANE_COUNT_SET_2
Lane count of 2.
Referenced by XDpTxSs_SetLaneCount.
XDPTXSS_LANE_COUNT_SET_4
Lane count of 4.
Referenced by XDpTxSs_SetLaneCount.
XDPTXSS_INTERRUPT_MASK
Masks the specified interrupt sources.
XDPTXSS_INTERRUPT_MASK_HPD_PULSE_DETECTED_MASK
Mask HPD pulse detected interrupt.
XDPTXSS_INTERRUPT_MASK_HPD_EVENT_MASK
Mask HPD event interrupt.
XDPTXSS_INTERRUPT_MASK_ALL_MASK
Mask all interrupts.
Referenced by XDpTxSs_Start.
XDPTXSS_INTERRUPT_MASK_NORMAL_MASK
Mask for normal TX operation (HPD + IRQ enabled)
Referenced by XDpTxSs_Start.
XDPTXSS_NUM_STREAMS
Maximum number of streams supported.