xdptxss.c
XDpTxSs_SubCores DpTxSsSubCores[XPAR_XDPTXSS_NUM_INSTANCES][XPAR_XDPTXSS_NUM_INSTANCES]
static void DpTxSs_GetIncludedSubCores(XDpTxSs *InstancePtr, UINTPTR BaseAddress)
This function reports list of cores included in DisplayPort TX Subsystem.
InstancePtr is a pointer to the XDpTxSs core instance. None.
static void DpTxSs_CalculateMsa(XDpTxSs *InstancePtr, u8 Stream)
This function computes multi-stream attribute and populates frame rate, pixel clock and so on.
InstancePtr is a pointer to the XDpTxSs core instance. Stream is the stream number for which the MSA values will be computed for. None. None.
static u32 DpTxSs_CheckRxDeviceMode(XDpTxSs *InstancePtr)
This function checks whether RX device in multi-stream (MST) / Single Stream transport mode.
InstancePtr is a pointer to the XDpTxSs core instance. XST_FAILURE if DisplayPort TX initialization failed or RX device is not connected.XST_SUCCESS if RX device check is successful. None.
static u32 DpTxSs_SetupSubCores(XDpTxSs *InstancePtr)
This function configures DisplayPort TX subsystem sub-cores.
InstancePtr is a pointer to the XDpTxSs core instance. XST_FAILURE if all sub-cores configuration failed.XST_SUCCESS if all sub-cores configuration was successful. None.
u32 XDpTxSs_CfgInitialize(XDpTxSs *InstancePtr, XDpTxSs_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the DisplayPort Transmitter Subsystem core.
This function must be called prior to using the core. Initialization of the core includes setting up the instance data and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the XDpTxSs core instance. CfgPtr points to the configuration structure associated with the DisplayPort TX Subsystem core. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_DEVICE_NOT_FOUND if sub-core not found.XST_FAILURE if sub-core initialization failed.XST_SUCCESS if XDpTxSs_CfgInitialize successful. None.
References XDpTxSs_Config::BaseAddress, XDpTxSs_UsrOpt::Bpc, XDpTxSs::Config, XDpTxSs_DpSubCore::DpConfig, XDpTxSs::DpPtr, XDpTxSs_Config::DpSubCore, XDpTxSs_Config::Hdcp22Enable, XDpTxSs::IsReady, XDpTxSs_Config::MaxBpc, XDpTxSs_UsrOpt::MstSupport, XDpTxSs_Config::MstSupport, XDpTxSs_Config::NumMstStreams, XDpTxSs_UsrOpt::NumOfStreams, XDpTxSs_TmrCtrSubCore::TmrCtrConfig, XDpTxSs_Config::TmrCtrSubCore, XDpTxSs::UsrOpt, XDpTxSs_UsrOpt::VmId, XDpTxSs_UsrOpt::VtcAdjustBs, XDpTxSs_VtcSubCore::VtcConfig, XDpTxSs::VtcPtr, XDpTxSs_Config::VtcSubCore, XDPTXSS_DRV_HANDLER_DP_EXT_PKT_EVENT, XDPTXSS_DRV_HANDLER_DP_HPD_EVENT, XDPTXSS_DRV_HANDLER_DP_HPD_PULSE, XDPTXSS_HDCP_1X, XDPTXSS_HDCP_22, XDPTXSS_HDCP_BOTH, XDpTxSs_HpdEventProcess, XDpTxSs_HpdPulseProcess, XDpTxSs_SetCallBack, XDpTxSs_VtcSetup, XDpTxSs_WriteVscExtPktProcess.
Referenced by DpTxSs_Main.
void XDpTxSs_Reset(XDpTxSs *InstancePtr)
This function resets the DisplayPort Transmitter Subsystem including all sub-cores.
InstancePtr is a pointer to the XDpTxSs core instance. None.
References XDpTxSs::Config, XDpTxSs_DpSubCore::DpConfig, XDpTxSs_Config::DpSubCore, XDpTxSs_Config::NumMstStreams, XDpTxSs::VtcPtr, XDpTxSs_WriteReg.
Referenced by main_loop.
u32 XDpTxSs_Start(XDpTxSs *InstancePtr)
This function starts the DisplayPort Transmitter Subsystem including all sub-cores.
InstancePtr is a pointer to the XDpTxSs core instance. XST_SUCCESS, if DP TX Subsystem and its included sub-cores configured successfully.XST_FAILURE, otherwise. None.
References XDpTxSs_UsrOpt::Bpc, XDpTxSs::DpPtr, XDpTxSs_UsrOpt::MstSupport, XDpTxSs::UsrOpt, XDpTxSs_UsrOpt::VmId, XDpTxSs_DpTxStart, XDPTXSS_INTERRUPT_MASK_ALL_MASK, XDPTXSS_INTERRUPT_MASK_NORMAL_MASK.
Referenced by DpTxSs_HpdPulseCon, DpTxSs_StartTx.
u32 XDpTxSs_StartCustomMsa(XDpTxSs *InstancePtr, XDpTxSs_MainStreamAttributes *MsaConfigCustom)
This function starts the DisplayPort Transmitter Subsystem with custom multi-stream attributes (MSA)including all sub-cores.
InstancePtr is a pointer to the XDpTxSs core instance. MsaConfigCustom is the structure that will be used to copy the main stream attributes from (into InstancePtr->DpPtr->TxInstance.MsaConfig). XST_SUCCESS, if DP TX Subsystem and its included sub-cores configured successfully.XST_FAILURE, otherwise. None.
References XDpTxSs_UsrOpt::Bpc, XDpTxSs::DpPtr, XDpTxSs_UsrOpt::MstSupport, XDpTxSs_UsrOpt::NumOfStreams, XDpTxSs::UsrOpt, XDpTxSs_UsrOpt::VmId, XDpTxSs_DpTxStart, XDpTxSs_MainStreamAttributes.
void XDpTxSs_Stop(XDpTxSs *InstancePtr)
This function disables the DisplayPort Transmitter Subsystem sub-cores.
InstancePtr is a pointer to the XDpTxSs core instance. None.
References XDpTxSs::Config, XDpTxSs::DpPtr, XDpTxSs_Config::NumMstStreams, XDpTxSs::VtcPtr.
Referenced by main_loop.
void XDpTxSs_VtcAdjustBSTimingEnable(XDpTxSs *InstancePtr)
This function enables special timing mode for BS equal timing.
InstancePtr is a pointer to the XDpTxSs core instance. None.
References XDpTxSs::UsrOpt, XDpTxSs_UsrOpt::VtcAdjustBs.
void XDpTxSs_VtcAdjustBSTimingDisable(XDpTxSs *InstancePtr)
This function disables special timing mode for BS equal timing.
InstancePtr is a pointer to the XDpTxSs core instance. None.
References XDpTxSs::UsrOpt, XDpTxSs_UsrOpt::VtcAdjustBs.
u32 XDpTxSs_SetBpc(XDpTxSs *InstancePtr, u8 Bpc)
This function sets the bits per color value of the video stream.
InstancePtr is a pointer to the XDpTxSs instance. Bpc is the new number of bits per color that needs to be set. 6 = XVIDC_BPC_6,8 = XVIDC_BPC_8,10 = XVIDC_BPC_10,12 = XVIDC_BPC_12,16 = XVIDC_BPC_16, XST_SUCCESS, if bits per color set successfully.XST_FAILURE, if bits per color set failed. None.
References XDpTxSs_UsrOpt::Bpc, XDpTxSs::DpPtr, XDpTxSs::UsrOpt.
Referenced by DpTxSs_StartTx, XDpTxSs_SetVideoStream.
u32 XDPTxss_GetMsa(XDpTxSs *InstancePtr, XDpTxSs_MainStreamAttributes *msa_tx)
This function gets the MSA values for the specified video format.
InstancePtr is a pointer to the XDpTxSs instance. msa_tx is the structure that will be used to copy the main stream attributes into (from InstancePtr->DpPtr->TxInstance.MsaConfig). XST_SUCCESS, if MSA values read successfully.XST_FAILURE, if MSA values read failed. Refer xvidc.h for enumerated standard video modes.
References XDpTxSs::DpPtr, XDpTxSs_UsrOpt::NumOfStreams, XDpTxSs::UsrOpt, XDpTxSs_MainStreamAttributes.
u32 XDPTxss_SetMsa(XDpTxSs *InstancePtr, XVidC_VideoStream *VidStream, u8 Stream)
This function sets the MSA values for the specified video format.
InstancePtr is a pointer to the XDpTxSs instance. VidStream is one of the enumerated standard video modes that is used to determine the MSA values to be used. Stream number XST_SUCCESS, if video mode set successfully.XST_FAILURE, if video mode set failed. Refer xvidc.h for enumerated standard video modes.
References XDpTxSs::DpPtr, XDpTxSs_MainStreamAttributes.
Referenced by XDpTxSs_SetVideoStream.
u32 XDpTxSs_SetVideoStream(XDpTxSs *InstancePtr, XVidC_VideoStream *VidStream, u8 Stream)
This function sets the VideoStream structure for the specified video format.
InstancePtr is a pointer to the XDpTxSs instance. VidStream is one of the enumerated standard video modes that is used to determine the MSA values to be used. Stream Streamnumber to set the video params XST_SUCCESS, if video mode set successfully.XST_FAILURE, if video mode set failed. Refer xvidc.h for enumerated standard video modes.
References XDpTxSs_SetBpc, XDPTxss_SetMsa, XDpTxSs_SetVidMode.
u32 XDpTxSs_SetVidMode(XDpTxSs *InstancePtr, XVidC_VideoMode VidMode)
This function sets the standard display mode.
InstancePtr is a pointer to the XDpTxSs instance. VidMode is one of the enumerated standard video modes that is used to determine the MSA values to be used. XST_SUCCESS, if video mode set successfully.XST_FAILURE, if video mode set failed. Refer xvidc.h for enumerated standard video modes.
References XDpTxSs::Config, XDpTxSs_DpSubCore::DpConfig, XDpTxSs_Config::DpSubCore, XDpTxSs_UsrOpt::MstSupport, XDpTxSs::UsrOpt, XDpTxSs_UsrOpt::VmId.
Referenced by DpTxSs_StartTx, XDpTxSs_SetVideoStream.
void XDpTxSs_OverrideSyncPolarity(XDpTxSs *InstancePtr, u8 Stream)
This function overrides the Polarity for Horizontal and Vertical Sync signals.
InstancePtr is a pointer to the XDpTxSs instance. Stream is the stream number for which to change the Polarity. None.
References XDpTxSs::DpPtr.
u32 XDpTxSs_GetLinkRate(XDpTxSs *InstancePtr)
This function gets the data rate to be used by the DisplayPort TX Subsystem core.
InstancePtr is a pointer to the XDpTxSs instance. XST_SUCCESS if setting the new lane rate was successful.XST_FAILURE otherwise. Maximum supported link rate is used if given link rate is greater than the maximum supported link rate.
References XDpTxSs::DpPtr.
Referenced by get_LineRate.
static u8 DpTxSs_EncodeLinkBandwidth(XDpTxSs *InstancePtr, u8 LinkRate)
u32 DpTxSs_SetRepeaterMode(XDpTxSs *InstancePtr, XDp_Tx_LttprMode RepeaterMode)
This function sets the Repeater mode to be used by the DisplayPort TX Subsystem core.
InstancePtr is a pointer to the XDpTxSs instance. RepeaterMode is the rate at which link needs to be driven. XDP_TX_LTTPR_TRANSPARENTXDP_TX_LTTPR_NON_TRANSPARENT XST_SUCCESS if setting the new lane rate was successful.XST_FAILURE otherwise.
References XDpTxSs::DpPtr.
u32 XDpTxSs_SetLinkRate(XDpTxSs *InstancePtr, u8 LinkRate)
This function sets the data rate to be used by the DisplayPort TX Subsystem core.
InstancePtr is a pointer to the XDpTxSs instance. LinkRate is the rate at which link needs to be driven. XDPTXSS_LINK_BW_SET_162GBPS = 0x06(for a 1.62 Gbps data rate)XDPTXSS_LINK_BW_SET_270GBPS = 0x0A(for a 2.70 Gbps data rate)XDPTXSS_LINK_BW_SET_540GBPS = 0x14(for a 5.40 Gbps data rate) XST_SUCCESS if setting the new lane rate was successful.XST_FAILURE otherwise. Maximum supported link rate is used if given link rate is greater than the maximum supported link rate.
References XDpTxSs::DpPtr, XDPTXSS_LINK_BW_SET_10GBPS, XDPTXSS_LINK_BW_SET_135GBPS, XDPTXSS_LINK_BW_SET_162GBPS, XDPTXSS_LINK_BW_SET_20GBPS, XDPTXSS_LINK_BW_SET_270GBPS, XDPTXSS_LINK_BW_SET_540GBPS, XDPTXSS_LINK_BW_SET_810GBPS, XDPTXSS_LINK_BW_SET_SW_10GBPS, XDPTXSS_LINK_BW_SET_SW_135GBPS, XDPTXSS_LINK_BW_SET_SW_20GBPS.
Referenced by DpTxSs_HpdPulseCon, DpTxSs_Main, DpTxSs_StartTx.
u32 XDpTxSs_SetLaneCount(XDpTxSs *InstancePtr, u8 LaneCount)
This function sets the number of lanes to be used by DisplayPort TX Subsystem core.
InstancePtr is a pointer to the XDpTxSs instance. LaneCount is the number of lanes to be used. 1 = XDPTXSS_LANE_COUNT_SET_12 = XDPTXSS_LANE_COUNT_SET_24 = XDPTXSS_LANE_COUNT_SET_4 XST_SUCCESS if setting the new lane count was successful.XST_FAILURE otherwise. Maximum supported lane count is used if given lane count is greater than the maximum supported lane count.
References XDpTxSs::DpPtr, XDPTXSS_LANE_COUNT_SET_1, XDPTXSS_LANE_COUNT_SET_2, XDPTXSS_LANE_COUNT_SET_4.
Referenced by DpTxSs_HpdPulseCon, DpTxSs_Main, DpTxSs_StartTx.
u32 XDpTxSs_SetTransportMode(XDpTxSs *InstancePtr, u8 Mode)
This function sets transport mode (SST/MST).
InstancePtr is a pointer to the XDpTxSs core instance. Mode specifies the type of transport mode that will be set. 0 = Single-Stream Transport mode,1 = Multi-Stream Transport mode, XST_SUCCESS, if transport mode is set successfully to either MST or SST when RX device is MST and mode is less than or equal to supported mode.XST_FAILURE, if setting to already set mode or mode is greater than supported mode. Transport mode is set to either MST or SST when system is MST and RX device is MST capable.
References XDpTxSs::DpPtr, XDpTxSs_UsrOpt::MstSupport, XDpTxSs::UsrOpt.
u32 XDpTxSs_GetRxCapabilities(XDpTxSs *InstancePtr)
This function retrieves the RX device's capabilities from the RX device's DisplayPort Configuration Data (DPCD).
InstancePtr is a pointer to the XDpTxSs core instance. XST_SUCCESS if the DisplayPort Configuration Data was read successfully.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_FAILURE otherwise. None.
References XDpTxSs::DpPtr.
u32 XDpTxSs_GetSinkCapabilities(XDpTxSs *InstancePtr, u8 *SinkCap, u8 *SinkExtendedCap, u8 *MaxLinkrate_128B)
This function retrieves the Sink device's capabilities from the RX device's DisplayPort Configuration Data (DPCD).
InstancePtr is a pointer to the XDp instance. SinkCap Downstream Capabilities. SinkExtendedCap Downstream Extended Capabilities. MaxLinkrate_128B Maximum Link Rate supported by Sink. XST_SUCCESS if the DisplayPort Configuration Data was read successfully.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_FAILURE otherwise. None.
References XDpTxSs::DpPtr.
u32 XDpTxSs_GetEdid(XDpTxSs *InstancePtr, u8 *Edid)
This function retrieves an immediately connected RX device's Extended Display Identification Data (EDID) structure.
InstancePtr is a pointer to the XDpTxSs core instance. Edid is a pointer to the Edid buffer to save to. XST_SUCCESS if the I2C transactions to read the EDID were successful.XST_ERROR_COUNT_MAX if the EDID read request timed out.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_FAILURE otherwise. None.
References XDpTxSs::DpPtr, XDpTxSs::IsReady.
u32 XDpTxSs_GetRemoteEdid(XDpTxSs *InstancePtr, u8 SinkNum, u8 *Edid)
This function retrieves a remote RX device's Extended Display Identification Data (EDID) structure.
InstancePtr is a pointer to the XDpTxSs core instance. SinkNum is the Sink ID in the sink list within the range [0 to 3]. Edid is a pointer to the Edid buffer to save to. XST_SUCCESS if the I2C transactions to read the EDID were successful.XST_ERROR_COUNT_MAX if the EDID read request timed out.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_FAILURE otherwise. None.
References XDpTxSs::DpPtr, XDpTxSs::IsReady.
u32 XDpTxSs_IsConnected(XDpTxSs *InstancePtr)
This function checks if there is a connected RX device to DisplayPort TX Subsystem.
InstancePtr is a pointer to the XDpTxSs core instance. TRUE if there is a connection.FALSE if there is no connection. None.
References XDpTxSs::DpPtr.
Referenced by DpTxSs_HpdEventHandler, DpTxSs_Main, DpTxSs_Setup, XDpTxSs_get_full_edid.
u32 XDpTxSs_CheckLinkStatus(XDpTxSs *InstancePtr)
This function checks if the receiver's DisplayPort Configuration Data (DPCD) indicates the receiver has achieved and maintained clock recovery, channel equalization, symbol lock, and interlane alignment for all lanes currently in use.
InstancePtr is a pointer to the XDpTxSs core instance. XST_SUCCESS if the RX device has maintained clock recovery, channel equalization, symbol lock, and interlane alignment.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_FAILURE otherwise. None.
References XDpTxSs::DpPtr.
Referenced by DpTxSs_StartTx, main_loop.
void XDpTxSs_SetUserPixelWidth(XDpTxSs *InstancePtr, u8 UserPixelWidth, u8 StreamId)
This function configures the number of pixels output through the user data interface.
InstancePtr is a pointer to the XDpTxSs core instance. UserPixelWidth is the user pixel width to be configured. StreamId is the stream number. None.
References XDpTxSs::DpPtr.
u32 XDpTxSs_IsMstCapable(XDpTxSs *InstancePtr)
This function determines whether downstream RX device is MST/SST capable.
InstancePtr is a pointer to the XDpTxSs core instance. XST_SUCCESS if the RX device is MST enabled.XST_FAILURE if the RX device is SST enabled. None.
References XDpTxSs::DpPtr.
u8 XDpTxSs_GetNumOfMstStreams(XDpTxSs *InstancePtr)
This function returns number of downstream MST sink devices enumerated and available for payload allocation .
InstancePtr is a pointer to the XDpTxSs core instance. Number of MST sinks to be enabled for payload allocation None.
References XDpTxSs::DpPtr.
u32 XDpTxSs_CheckVscColorimetrySupport(XDpTxSs *InstancePtr)
This function will check if the immediate downstream RX device capable of receiving colorimetry information through VSC extended SDP packet.
InstancePtr is a pointer to the XDp instance. XST_SUCCESS if the RX device is capable of VSC extended packet.XST_NO_FEATURE if the RX device does not capable of VSC extended packet. None.
References XDpTxSs::DpPtr.
u32 XDpTxSs_SetVscExtendedPacket(XDpTxSs *InstancePtr, XDp_TxVscExtPacket VscPkt)
This function decodes the extended packet payload data bytes and fills up the driver extended packet structure members.
And also copies extended packet header information to the driver structure. InstancePtr is a pointer to the XDp instance. VscPkt is a driver extended packet structure XST_SUCCESS if VSC extended packet is set.XST_FAILURE if VSC extended packet is not set. None.
References XDpTxSs::DpPtr.
void XDpTxss_EnableVscColorimetry(XDpTxSs *InstancePtr, u8 Enable)
This function Enable / Disable the mechanism of sending colorimetry information through VSC extended packet.
InstancePtr is a pointer to the XDp instance. Enable specifies to enable the flag 0 = Disable the sending colorimetry through VSC packet else enable Enable the sending colorimetry through VSC packet None.
References XDpTxSs::DpPtr.
void XDpTxSs_SetHasRedriverInPath(XDpTxSs *InstancePtr, u8 Set)
This function sets software switch that specify whether or not a redriver exits on the DisplayPort output path.
InstancePtr is a pointer to the XDpTxSs core instance. Set establishes that a redriver exists in the DisplayPort output path. 1 = Set redriver in the DisplayPort output path. 0 = Unset redriver in the DisplayPort output path. Set the redriver in the DisplayPort output path before starting the training.
References XDpTxSs::DpPtr.
void XDpTxSs_SendAudioInfoFrame(XDpTxSs *InstancePtr, XDp_TxAudioInfoFrame *xilInfoFrame)
This function sends audio infoframe and configures audio parameters including MAUD/NAUD values based on the current link rate.
InstancePtr is a pointer to the XDpTxSs instance. xilInfoFrame is a pointer to the audio infoframe structure. This function performs the following operations: Disables audioConfigures the audio infoframe packetCalculates and sets MAUD/NAUD based on link rate Enables Audio
References XDpTxSs::DpPtr.
Referenced by main_loop.