xdptxss_dptx.h
XDPTXSS_DPTX_H_
Prevent circular inclusions by using protection macros.
XDPTXSS_DPTX_MST
Multi-Stream Transport.
Referenced by XDpTxSs_DpTxStart.
XDPTXSS_DPTX_SST
Single Stream Transport.
Referenced by XDpTxSs_DpTxStart.
XDPTXSS_EXT_DATA_2ND_TO_9TH_WORD
DP_LINK_RATE_HZ_162GBPS
DP lane rates.
DP_LINK_RATE_HZ_270GBPS
DP_LINK_RATE_HZ_540GBPS
DP_LINK_RATE_HZ_810GBPS
u32 XDpTxSs_DpTxStart(XDp *InstancePtr, u8 TransportMode, u8 Bpc, XVidC_VideoMode VidMode)
This function configures DisplayPort sub-core with preferred resolution read from sink or user set resolution, bits per color in SST/MST mode.
In MST mode, if sinks are more than two, it re-orders the sinks if belongs to same tiled display topology. It trains the link and allocates stream payloads for single stream (SST) or multi-stream transport mode (MST). In MST mode, discovers the topology and finds the actual number of sinks to which associates streams. InstancePtr is a pointer to the XDp instance. TransportMode specifies whether multiple/single steam to be sent over the main link. TransportMode = 1 (for Multi-Stream Transport)TransportMode = 0 (for Single Stream Transport) Bpc is the new number of bits per color to use. VidMode is one of the enumerated standard video modes defined in xvidc.h file. XST_SUCCESS DisplayPort configured successfully.XST_FAILURE if DisplayPort configuration failed. None.
References XDPTXSS_DPTX_MST, XDPTXSS_DPTX_SST, XDpTxSs_DpTxStartLink.
Referenced by XDpTxSs_Start, XDpTxSs_StartCustomMsa.
u32 XDpTxSs_DpTxStartLink(XDp *InstancePtr, u8 TrainMaxCap)
This function checks if the link needs training and runs the training sequence if training is required based on the flags, indicates to use maximum RX capabilities or user specified link rate, lane count during training.
InstancePtr is a pointer to the XDp instance. TrainMaxCap is a flag indicates whether maximum capabilities to be used during link training. TRUE - Use maximum RX capabilities.FALSE - Use custom capabilities. XST_SUCCESS the if main link was successfully established.XST_FAILURE otherwise. None.
Referenced by XDpTxSs_DpTxStart.