xdptxss.h
XDPTXSS_H_
Prevent circular inclusions by using protection macros.
XPAR_XHDCP_NUM_INSTANCES
XDPTXSS_REG_ENHANCED_FRAME_EN_STREAM_1
Enhanced frame enable for stream 1.
XDPTXSS_REG_ENHANCED_FRAME_EN_STREAM_2
Enhanced frame enable for stream 2.
XDPTXSS_REG_TRAINING_PATTERN_STREAM_3
Training pattern for stream 3.
XDPTXSS_REG_TRAINING_PATTERN_STREAM_4
Training pattern for stream 4.
XDPTXSS_REG_STREAM_ZERO
No stream encryption.
XDPTXSS_REG_ALL_STREAMS_ENCRYPT
Encrypt all streams.
XDpTxSs_TimerHandler
Callback type which represents a custom timer wait handler.
XDpTxSs_MainStreamAttributes
Main-Stream attributes.
Referenced by XDPTxss_GetMsa, XDPTxss_SetMsa, XDpTxSs_StartCustomMsa.
XDpTxSs_CfgMsaEnSynchClkMode
This function enables or disables synchronous clock mode for a video stream.
InstancePtr is a pointer to the XDp instance. Stream is the stream number for which to enable or disable synchronous clock mode. Enable if set to 1, will enable synchronous clock mode. Otherwise, if set to 0, synchronous clock mode will be disabled. None. C-style signature: void XDp_TxCfgMsaEnSynchClkMode(XDpTxSs *InstancePtr, u8 Stream, u8 Enable)
XDpTxSs_Mst_AudioEnable
This function macro enables MST-TX audio on a given stream on the main link.
InstancePtr is a pointer to the XDpTxSs core instance. StreamId to be enabled audio None. C-style signature: void XDpTxSs_Mst_AudioEnable(XDpTxSs *InstancePtr, u8 StreamId)
XDpTxSs_Mst_AudioDisable
This function macro disables audio on a given stream on the main link.
InstancePtr is a pointer to the XDpTxSs core instance. None. C-style signature: void XDpTxSs_Mst_AudioDisable(XDpTxSs *InstancePtr)
XDpTxSs_HandlerType
A HPD event interrupt type for DisplayPort core.
XDpTxSs_HdcpProtocol
No content protection.
XDpTxSs_HdcpContentStreamType
HDCP Stream Type 0.
XDpTxSs_Config * XDpTxSs_LookupConfig(UINTPTR BaseAddress)
This function returns a reference to an XDptxss_Config structure based on the core id, DeviceId.
The return value will refer to an entry in the device configuration table defined in the xdptxss_g.c file. DeviceId is the unique core ID of the XDpTxSs core for the lookup operation. XDptxss_LookupConfig returns a reference to a config record in the configuration table (in xdptxss_g.c) corresponding to DeviceId, or NULL if no match is found. None.
Referenced by DpTxSs_Main.
u32 XDpTxSs_GetDrvIndex(UINTPTR BaseAddress)
This function returns the Index number of config table using BaseAddress.
Base address of the instance Index number of the config table
u32 XDpTxSs_CfgInitialize(XDpTxSs *InstancePtr, XDpTxSs_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the DisplayPort Transmitter Subsystem core.
This function must be called prior to using the core. Initialization of the core includes setting up the instance data and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the XDpTxSs core instance. CfgPtr points to the configuration structure associated with the DisplayPort TX Subsystem core. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_DEVICE_NOT_FOUND if sub-core not found.XST_FAILURE if sub-core initialization failed.XST_SUCCESS if XDpTxSs_CfgInitialize successful. None.
References XDpTxSs_Config::BaseAddress, XDpTxSs_UsrOpt::Bpc, XDpTxSs::Config, XDpTxSs_DpSubCore::DpConfig, XDpTxSs::DpPtr, XDpTxSs_Config::DpSubCore, XDpTxSs_Config::Hdcp22Enable, XDpTxSs::IsReady, XDpTxSs_Config::MaxBpc, XDpTxSs_UsrOpt::MstSupport, XDpTxSs_Config::MstSupport, XDpTxSs_Config::NumMstStreams, XDpTxSs_UsrOpt::NumOfStreams, XDpTxSs_TmrCtrSubCore::TmrCtrConfig, XDpTxSs_Config::TmrCtrSubCore, XDpTxSs::UsrOpt, XDpTxSs_UsrOpt::VmId, XDpTxSs_UsrOpt::VtcAdjustBs, XDpTxSs_VtcSubCore::VtcConfig, XDpTxSs::VtcPtr, XDpTxSs_Config::VtcSubCore, XDPTXSS_DRV_HANDLER_DP_EXT_PKT_EVENT, XDPTXSS_DRV_HANDLER_DP_HPD_EVENT, XDPTXSS_DRV_HANDLER_DP_HPD_PULSE, XDPTXSS_HDCP_1X, XDPTXSS_HDCP_22, XDPTXSS_HDCP_BOTH, XDpTxSs_HpdEventProcess, XDpTxSs_HpdPulseProcess, XDpTxSs_SetCallBack, XDpTxSs_VtcSetup, XDpTxSs_WriteVscExtPktProcess.
Referenced by DpTxSs_Main.
u32 XDpTxSs_Start(XDpTxSs *InstancePtr)
This function starts the DisplayPort Transmitter Subsystem including all sub-cores.
InstancePtr is a pointer to the XDpTxSs core instance. XST_SUCCESS, if DP TX Subsystem and its included sub-cores configured successfully.XST_FAILURE, otherwise. None.
References XDpTxSs_UsrOpt::Bpc, XDpTxSs::DpPtr, XDpTxSs_UsrOpt::MstSupport, XDpTxSs::UsrOpt, XDpTxSs_UsrOpt::VmId, XDpTxSs_DpTxStart, XDPTXSS_INTERRUPT_MASK_ALL_MASK, XDPTXSS_INTERRUPT_MASK_NORMAL_MASK.
Referenced by DpTxSs_HpdPulseCon, DpTxSs_StartTx.
u32 XDpTxSs_StartCustomMsa(XDpTxSs *InstancePtr, XDpTxSs_MainStreamAttributes *MsaConfigCustom)
This function starts the DisplayPort Transmitter Subsystem with custom multi-stream attributes (MSA)including all sub-cores.
InstancePtr is a pointer to the XDpTxSs core instance. MsaConfigCustom is the structure that will be used to copy the main stream attributes from (into InstancePtr->DpPtr->TxInstance.MsaConfig). XST_SUCCESS, if DP TX Subsystem and its included sub-cores configured successfully.XST_FAILURE, otherwise. None.
References XDpTxSs_UsrOpt::Bpc, XDpTxSs::DpPtr, XDpTxSs_UsrOpt::MstSupport, XDpTxSs_UsrOpt::NumOfStreams, XDpTxSs::UsrOpt, XDpTxSs_UsrOpt::VmId, XDpTxSs_DpTxStart, XDpTxSs_MainStreamAttributes.
void XDpTxSs_Stop(XDpTxSs *InstancePtr)
This function disables the DisplayPort Transmitter Subsystem sub-cores.
InstancePtr is a pointer to the XDpTxSs core instance. None.
References XDpTxSs::Config, XDpTxSs::DpPtr, XDpTxSs_Config::NumMstStreams, XDpTxSs::VtcPtr.
Referenced by main_loop.
void XDpTxSs_Reset(XDpTxSs *InstancePtr)
This function resets the DisplayPort Transmitter Subsystem including all sub-cores.
InstancePtr is a pointer to the XDpTxSs core instance. None.
References XDpTxSs::Config, XDpTxSs_DpSubCore::DpConfig, XDpTxSs_Config::DpSubCore, XDpTxSs_Config::NumMstStreams, XDpTxSs::VtcPtr, XDpTxSs_WriteReg.
Referenced by main_loop.
void XDpTxSs_VtcAdjustBSTimingEnable(XDpTxSs *InstancePtr)
This function enables special timing mode for BS equal timing.
InstancePtr is a pointer to the XDpTxSs core instance. None.
References XDpTxSs::UsrOpt, XDpTxSs_UsrOpt::VtcAdjustBs.
void XDpTxSs_VtcAdjustBSTimingDisable(XDpTxSs *InstancePtr)
This function disables special timing mode for BS equal timing.
InstancePtr is a pointer to the XDpTxSs core instance. None.
References XDpTxSs::UsrOpt, XDpTxSs_UsrOpt::VtcAdjustBs.
void XDpTxSs_OverrideSyncPolarity(XDpTxSs *InstancePtr, u8 Stream)
This function overrides the Polarity for Horizontal and Vertical Sync signals.
InstancePtr is a pointer to the XDpTxSs instance. Stream is the stream number for which to change the Polarity. None.
References XDpTxSs::DpPtr.
u32 XDpTxSs_SetBpc(XDpTxSs *InstancePtr, u8 Bpc)
This function sets the bits per color value of the video stream.
InstancePtr is a pointer to the XDpTxSs instance. Bpc is the new number of bits per color that needs to be set. 6 = XVIDC_BPC_6,8 = XVIDC_BPC_8,10 = XVIDC_BPC_10,12 = XVIDC_BPC_12,16 = XVIDC_BPC_16, XST_SUCCESS, if bits per color set successfully.XST_FAILURE, if bits per color set failed. None.
References XDpTxSs_UsrOpt::Bpc, XDpTxSs::DpPtr, XDpTxSs::UsrOpt.
Referenced by DpTxSs_StartTx, XDpTxSs_SetVideoStream.
u32 XDpTxSs_SetVidMode(XDpTxSs *InstancePtr, XVidC_VideoMode VidMode)
This function sets the standard display mode.
InstancePtr is a pointer to the XDpTxSs instance. VidMode is one of the enumerated standard video modes that is used to determine the MSA values to be used. XST_SUCCESS, if video mode set successfully.XST_FAILURE, if video mode set failed. Refer xvidc.h for enumerated standard video modes.
References XDpTxSs::Config, XDpTxSs_DpSubCore::DpConfig, XDpTxSs_Config::DpSubCore, XDpTxSs_UsrOpt::MstSupport, XDpTxSs::UsrOpt, XDpTxSs_UsrOpt::VmId.
Referenced by DpTxSs_StartTx, XDpTxSs_SetVideoStream.
u32 XDpTxSs_SetLinkRate(XDpTxSs *InstancePtr, u8 LinkRate)
This function sets the data rate to be used by the DisplayPort TX Subsystem core.
InstancePtr is a pointer to the XDpTxSs instance. LinkRate is the rate at which link needs to be driven. XDPTXSS_LINK_BW_SET_162GBPS = 0x06(for a 1.62 Gbps data rate)XDPTXSS_LINK_BW_SET_270GBPS = 0x0A(for a 2.70 Gbps data rate)XDPTXSS_LINK_BW_SET_540GBPS = 0x14(for a 5.40 Gbps data rate) XST_SUCCESS if setting the new lane rate was successful.XST_FAILURE otherwise. Maximum supported link rate is used if given link rate is greater than the maximum supported link rate.
References XDpTxSs::DpPtr, XDPTXSS_LINK_BW_SET_10GBPS, XDPTXSS_LINK_BW_SET_135GBPS, XDPTXSS_LINK_BW_SET_162GBPS, XDPTXSS_LINK_BW_SET_20GBPS, XDPTXSS_LINK_BW_SET_270GBPS, XDPTXSS_LINK_BW_SET_540GBPS, XDPTXSS_LINK_BW_SET_810GBPS, XDPTXSS_LINK_BW_SET_SW_10GBPS, XDPTXSS_LINK_BW_SET_SW_135GBPS, XDPTXSS_LINK_BW_SET_SW_20GBPS.
Referenced by DpTxSs_HpdPulseCon, DpTxSs_Main, DpTxSs_StartTx.
u32 XDpTxSs_GetLinkRate(XDpTxSs *InstancePtr)
This function gets the data rate to be used by the DisplayPort TX Subsystem core.
InstancePtr is a pointer to the XDpTxSs instance. XST_SUCCESS if setting the new lane rate was successful.XST_FAILURE otherwise. Maximum supported link rate is used if given link rate is greater than the maximum supported link rate.
References XDpTxSs::DpPtr.
Referenced by get_LineRate.
u32 XDpTxSs_SetLaneCount(XDpTxSs *InstancePtr, u8 LaneCount)
This function sets the number of lanes to be used by DisplayPort TX Subsystem core.
InstancePtr is a pointer to the XDpTxSs instance. LaneCount is the number of lanes to be used. 1 = XDPTXSS_LANE_COUNT_SET_12 = XDPTXSS_LANE_COUNT_SET_24 = XDPTXSS_LANE_COUNT_SET_4 XST_SUCCESS if setting the new lane count was successful.XST_FAILURE otherwise. Maximum supported lane count is used if given lane count is greater than the maximum supported lane count.
References XDpTxSs::DpPtr, XDPTXSS_LANE_COUNT_SET_1, XDPTXSS_LANE_COUNT_SET_2, XDPTXSS_LANE_COUNT_SET_4.
Referenced by DpTxSs_HpdPulseCon, DpTxSs_Main, DpTxSs_StartTx.
u32 XDpTxSs_SetTransportMode(XDpTxSs *InstancePtr, u8 Mode)
This function sets transport mode (SST/MST).
InstancePtr is a pointer to the XDpTxSs core instance. Mode specifies the type of transport mode that will be set. 0 = Single-Stream Transport mode,1 = Multi-Stream Transport mode, XST_SUCCESS, if transport mode is set successfully to either MST or SST when RX device is MST and mode is less than or equal to supported mode.XST_FAILURE, if setting to already set mode or mode is greater than supported mode. Transport mode is set to either MST or SST when system is MST and RX device is MST capable.
References XDpTxSs::DpPtr, XDpTxSs_UsrOpt::MstSupport, XDpTxSs::UsrOpt.
u32 XDpTxSs_IsConnected(XDpTxSs *InstancePtr)
This function checks if there is a connected RX device to DisplayPort TX Subsystem.
InstancePtr is a pointer to the XDpTxSs core instance. TRUE if there is a connection.FALSE if there is no connection. None.
References XDpTxSs::DpPtr.
Referenced by DpTxSs_HpdEventHandler, DpTxSs_Main, DpTxSs_Setup, XDpTxSs_get_full_edid.
u32 XDpTxSs_CheckLinkStatus(XDpTxSs *InstancePtr)
This function checks if the receiver's DisplayPort Configuration Data (DPCD) indicates the receiver has achieved and maintained clock recovery, channel equalization, symbol lock, and interlane alignment for all lanes currently in use.
InstancePtr is a pointer to the XDpTxSs core instance. XST_SUCCESS if the RX device has maintained clock recovery, channel equalization, symbol lock, and interlane alignment.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_FAILURE otherwise. None.
References XDpTxSs::DpPtr.
Referenced by DpTxSs_StartTx, main_loop.
u32 XDpTxSs_IsMstCapable(XDpTxSs *InstancePtr)
This function determines whether downstream RX device is MST/SST capable.
InstancePtr is a pointer to the XDpTxSs core instance. XST_SUCCESS if the RX device is MST enabled.XST_FAILURE if the RX device is SST enabled. None.
References XDpTxSs::DpPtr.
u32 XDpTxSs_GetRxCapabilities(XDpTxSs *InstancePtr)
This function retrieves the RX device's capabilities from the RX device's DisplayPort Configuration Data (DPCD).
InstancePtr is a pointer to the XDpTxSs core instance. XST_SUCCESS if the DisplayPort Configuration Data was read successfully.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_FAILURE otherwise. None.
References XDpTxSs::DpPtr.
u32 XDpTxSs_GetEdid(XDpTxSs *InstancePtr, u8 *Edid)
This function retrieves an immediately connected RX device's Extended Display Identification Data (EDID) structure.
InstancePtr is a pointer to the XDpTxSs core instance. Edid is a pointer to the Edid buffer to save to. XST_SUCCESS if the I2C transactions to read the EDID were successful.XST_ERROR_COUNT_MAX if the EDID read request timed out.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_FAILURE otherwise. None.
References XDpTxSs::DpPtr, XDpTxSs::IsReady.
u32 XDpTxSs_GetRemoteEdid(XDpTxSs *InstancePtr, u8 SinkNum, u8 *Edid)
This function retrieves a remote RX device's Extended Display Identification Data (EDID) structure.
InstancePtr is a pointer to the XDpTxSs core instance. SinkNum is the Sink ID in the sink list within the range [0 to 3]. Edid is a pointer to the Edid buffer to save to. XST_SUCCESS if the I2C transactions to read the EDID were successful.XST_ERROR_COUNT_MAX if the EDID read request timed out.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_FAILURE otherwise. None.
References XDpTxSs::DpPtr, XDpTxSs::IsReady.
u32 XDPTxss_GetMsa(XDpTxSs *InstancePtr, XDpTxSs_MainStreamAttributes *msa_tx)
This function gets the MSA values for the specified video format.
InstancePtr is a pointer to the XDpTxSs instance. msa_tx is the structure that will be used to copy the main stream attributes into (from InstancePtr->DpPtr->TxInstance.MsaConfig). XST_SUCCESS, if MSA values read successfully.XST_FAILURE, if MSA values read failed. Refer xvidc.h for enumerated standard video modes.
References XDpTxSs::DpPtr, XDpTxSs_UsrOpt::NumOfStreams, XDpTxSs::UsrOpt, XDpTxSs_MainStreamAttributes.
void XDpTxSs_SetHasRedriverInPath(XDpTxSs *InstancePtr, u8 Set)
This function sets software switch that specify whether or not a redriver exits on the DisplayPort output path.
InstancePtr is a pointer to the XDpTxSs core instance. Set establishes that a redriver exists in the DisplayPort output path. 1 = Set redriver in the DisplayPort output path. 0 = Unset redriver in the DisplayPort output path. Set the redriver in the DisplayPort output path before starting the training.
References XDpTxSs::DpPtr.
void XDpTxSs_SetUserPixelWidth(XDpTxSs *InstancePtr, u8 UserPixelWidth, u8 StreamId)
This function configures the number of pixels output through the user data interface.
InstancePtr is a pointer to the XDpTxSs core instance. UserPixelWidth is the user pixel width to be configured. StreamId is the stream number. None.
References XDpTxSs::DpPtr.
u32 XDpTxSs_SetVideoStream(XDpTxSs *InstancePtr, XVidC_VideoStream *VidStream, u8 Stream)
This function sets the VideoStream structure for the specified video format.
InstancePtr is a pointer to the XDpTxSs instance. VidStream is one of the enumerated standard video modes that is used to determine the MSA values to be used. Stream Streamnumber to set the video params XST_SUCCESS, if video mode set successfully.XST_FAILURE, if video mode set failed. Refer xvidc.h for enumerated standard video modes.
References XDpTxSs_SetBpc, XDPTxss_SetMsa, XDpTxSs_SetVidMode.
u8 XDpTxSs_GetNumOfMstStreams(XDpTxSs *InstancePtr)
This function returns number of downstream MST sink devices enumerated and available for payload allocation .
InstancePtr is a pointer to the XDpTxSs core instance. Number of MST sinks to be enabled for payload allocation None.
References XDpTxSs::DpPtr.
u32 XDpTxSs_GetSinkCapabilities(XDpTxSs *InstancePtr, u8 *SinkCap, u8 *SinkExtendedCap, u8 *MaxLinkrate_128B)
This function retrieves the Sink device's capabilities from the RX device's DisplayPort Configuration Data (DPCD).
InstancePtr is a pointer to the XDp instance. SinkCap Downstream Capabilities. SinkExtendedCap Downstream Extended Capabilities. MaxLinkrate_128B Maximum Link Rate supported by Sink. XST_SUCCESS if the DisplayPort Configuration Data was read successfully.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_FAILURE otherwise. None.
References XDpTxSs::DpPtr.
void XDpTxSs_SendAudioInfoFrame(XDpTxSs *InstancePtr, XDp_TxAudioInfoFrame *xilInfoFrame)
This function sends audio infoframe and configures audio parameters including MAUD/NAUD values based on the current link rate.
InstancePtr is a pointer to the XDpTxSs instance. xilInfoFrame is a pointer to the audio infoframe structure. This function performs the following operations: Disables audioConfigures the audio infoframe packetCalculates and sets MAUD/NAUD based on link rate Enables Audio
References XDpTxSs::DpPtr.
Referenced by main_loop.
void XDpTxSs_ReportCoreInfo(XDpTxSs *InstancePtr)
This function reports list of sub-cores included in DisplayPort TX Subsystem.
InstancePtr is a pointer to the XDpTxSs core instance. None.
References XDpTxSs::Config, XDpTxSs::DpPtr, XDpTxSs_Config::HdcpEnable, XDpTxSs_Config::MaxBpc, XDpTxSs_Config::MaxLaneCount, XDpTxSs_UsrOpt::MstSupport, XDpTxSs_Config::MstSupport, XDpTxSs_Config::NumMstStreams, XDpTxSs_Config::SecondaryChEn, XDpTxSs::UsrOpt, XDpTxSs::VtcPtr.
void XDpTxSs_ReportLinkInfo(XDpTxSs *InstancePtr)
This function prints the link status, selected resolution, bits per color and link/lane count symbol error.
InstancePtr is a pointer to the XDpTxSs core instance. None.
References XDpTxSs_UsrOpt::Bpc, XDpTxSs::DpPtr, XDpTxSs::UsrOpt, XDpTxSs_UsrOpt::VmId.
Referenced by main_loop.
void XDpTxSs_ReportMsaInfo(XDpTxSs *InstancePtr)
This function prints the current main stream attributes from the DisplayPort TX core.
InstancePtr is a pointer to the XDpTxSs core instance. None.
References XDpTxSs::Config, XDpTxSs::DpPtr, XDpTxSs_Config::NumMstStreams.
Referenced by main_loop.
void XDpTxSs_ReportSinkCapInfo(XDpTxSs *InstancePtr)
This function prints the capabilities of the DisplayPort sink.
InstancePtr is a pointer to the XDpTxSs core instance. None.
References XDpTxSs::DpPtr.
Referenced by main_loop.
void XDpTxSs_ReportSplitterInfo(XDpTxSs *InstancePtr)
This function prints the current Dual Splitter information.
InstancePtr is a pointer to the XDpTxSs core instance. None.
void XDpTxSs_ReportVtcInfo(XDpTxSs *InstancePtr)
This function prints the current VTC timing information.
InstancePtr is a pointer to the XDpTxSs core instance. None.
References XDpTxSs::Config, XDpTxSs_Config::NumMstStreams, XDpTxSs::VtcPtr.
Referenced by main_loop.
void XDpTxSs_ReportHdcpInfo(XDpTxSs *InstancePtr)
This function prints the debug display info of the HDCP interface.
InstancePtr is a pointer to the XDpTxSs core instance. None.
u32 XDpTxSs_SelfTest(XDpTxSs *InstancePtr)
This function performs self test on DisplayPort Transmitter Subsystem sub-cores.
InstancePtr is a pointer to the XDpTxSs core instance. XST_SUCCESS if self test passed.XST_FAILURE if self test failed. None.
References XDpTxSs::Config, XDpTxSs::DpPtr, XDpTxSs_Config::HdcpEnable, XDpTxSs_Config::NumMstStreams, XDpTxSs::VtcPtr.
void XDpTxSs_DpIntrHandler(void *InstancePtr)
This function is the interrupt handler for the DisplayPort TX core operating in TX mode.
The application is responsible for connecting this function to the interrupt system. Application beyond this driver is also responsible for providing callbacks to handle interrupts and installing the callbacks using XDpTxSs_SetCallBack() during initialization phase. InstancePtr is a pointer to the XDpTxSs core instance that just interrupted. None.
References XDpTxSs::DpPtr, XDpTxSs::IsReady.
Referenced by DpTxSs_SetupIntrSystem.
u32 XDpTxSs_SetCallBack(XDpTxSs *InstancePtr, u32 HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function HandlerType ---------------------------------------- ------------------------------------ (XDPTXSS_HANDLER_DP_HPD_EVENT) XDP_TX_HANDLER_HPDEVENT (XDPTXSS_HANDLER_DP_HPD_PULSE) XDP_TX_HANDLER_HPDPULSE (XDPTXSS_HANDLER_DP_LANE_COUNT_CHG) XDP_TX_HANDLER_LANECNTCHANGE (XDPTXSS_HANDLER_DP_LINK_RATE_CHG) XDP_TX_HANDLER_LINKRATECHANGE (XDPTXSS_HANDLER_DP_PE_VS_ADJUST) XDP_TX_HANDLER_PEVSADJUST (XDPTXSS_HANDLER_DP_EXT_PKT_EVENT) XDP_TX_HANDLER_EXTPKT_TXD (XDPTXSS_DRV_HANDLER_DP_EXT_PKT_EVENT) XDP_TX_HANDLER_DRV_EXTPKT_TXD (XDPTXSS_HANDLER_DP_VSYNC) XDP_TX_HANDLER_VSYNC (XDPTXSS_HANDLER_HDCP_RPTR_EXCHG) XHdcp1x_SetCallBack (XDPTXSS_HANDLER_DP_SET_MSA) XDP_TX_HANDLER_SETMSA InstancePtr is a pointer to the XDpTxSs core instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XDpTxSs::DpPtr, XDpTxSs::IsReady, XDPTXSS_DRV_HANDLER_DP_EXT_PKT_EVENT, XDPTXSS_DRV_HANDLER_DP_HPD_EVENT, XDPTXSS_DRV_HANDLER_DP_HPD_PULSE, XDPTXSS_HANDLER_DP_EXT_PKT_EVENT, XDPTXSS_HANDLER_DP_FFE_PRESET_ADJUST, XDPTXSS_HANDLER_DP_HPD_EVENT, XDPTXSS_HANDLER_DP_HPD_PULSE, XDPTXSS_HANDLER_DP_LANE_COUNT_CHG, XDPTXSS_HANDLER_DP_LINK_RATE_CHG, XDPTXSS_HANDLER_DP_PE_VS_ADJUST, XDPTXSS_HANDLER_DP_SET_MSA, XDPTXSS_HANDLER_DP_VSYNC.
Referenced by XDpTxSs_CfgInitialize.
void XDpTxSs_SetUserTimerHandler(XDpTxSs *InstancePtr, XDpTxSs_TimerHandler CallbackFunc, void *CallbackRef)
This function installs a custom delay/sleep function to be used by the DisplayPort TX Subsystem.
InstancePtr is a pointer to the XDpTxSs instance. CallbackFunc is the address to the callback function. CallbackRef is the user data item (microseconds to delay) that will be passed to the custom sleep/delay function when it is invoked. None.
References XDpTxSs::DpPtr.
u32 XDpTxSs_CheckVscColorimetrySupport(XDpTxSs *InstancePtr)
This function will check if the immediate downstream RX device capable of receiving colorimetry information through VSC extended SDP packet.
InstancePtr is a pointer to the XDp instance. XST_SUCCESS if the RX device is capable of VSC extended packet.XST_NO_FEATURE if the RX device does not capable of VSC extended packet. None.
References XDpTxSs::DpPtr.
u32 XDpTxSs_SetVscExtendedPacket(XDpTxSs *InstancePtr, XDp_TxVscExtPacket VscPkt)
This function decodes the extended packet payload data bytes and fills up the driver extended packet structure members.
And also copies extended packet header information to the driver structure. InstancePtr is a pointer to the XDp instance. VscPkt is a driver extended packet structure XST_SUCCESS if VSC extended packet is set.XST_FAILURE if VSC extended packet is not set. None.
References XDpTxSs::DpPtr.
void XDpTxss_EnableVscColorimetry(XDpTxSs *InstancePtr, u8 Enable)
This function Enable / Disable the mechanism of sending colorimetry information through VSC extended packet.
InstancePtr is a pointer to the XDp instance. Enable specifies to enable the flag 0 = Disable the sending colorimetry through VSC packet else enable Enable the sending colorimetry through VSC packet None.
References XDpTxSs::DpPtr.
void XDpTxSs_HpdEventProcess(void *InstancePtr)
This function is process some DP driver read as per DP spec on HPD EVENT.
InstancePtr is a pointer to the XDpTxSs core instance that just interrupted. None.
References XDpTxSs::DpPtr, XDpTxSs::IsReady, XDpTxSs::UsrHpdEventData.
Referenced by XDpTxSs_CfgInitialize.
void XDpTxSs_HpdPulseProcess(void *InstancePtr)
This function is process some DP driver read as per DP spec on HPD Pulse.
InstancePtr is a pointer to the XDpTxSs core instance that just interrupted. None.
References XDpTxSs::DpPtr, XDpTxSs::IsReady, XDpTxSs::UsrHpdPulseData.
Referenced by XDpTxSs_CfgInitialize.
void XDpTxSs_WriteVscExtPktProcess(void *InstancePtr)
This function writes the pixel encoding format and colorimetry formats in to the extended packet registers at DP TX offset addresses "0x0330 to 0x0350".
InstancePtr is a pointer to the XDpTxSs core instance that just interrupted. None.
References XDpTxSs::DpPtr.
Referenced by XDpTxSs_CfgInitialize.