xdptxss_dp21_tx.c
INTRNAME_DPTX
PS_IIC_CLK
XVPHY_DP_LINK_RATE_HZ_1000GBPS
XVPHY_DP_LINK_RATE_HZ_1350GBPS
XVPHY_DP_LINK_RATE_HZ_2000GBPS
XTmrCtr TmrCtr
Timer instance.
Referenced by DpTxSs_PlatformInit, xil_getc.
XIic_Config* ConfigPtr_IIC
Pointer to configuration data.
Referenced by DpTxSs_PlatformInit.
XVphy VPhyInst
The DPRX Subsystem instance.
Referenced by DpTxSs_Ffe_AdjustHandler, DpTxSs_HpdEventHandler, DpTxSs_Main, DpTxSs_PhyConfig, DpTxSs_PhyInit, main_loop.
XIic IicInstance
I2C bus for Si570.
Referenced by DpTxSs_PlatformInit, VideoFMC_Init.
volatile u8 HpdPulseConEvent
This variable triggers DpTxSs_HpdPulseCon.
Referenced by DpTxSs_HpdPulseHandler, main_loop.
volatile u8 PrevLineRate
This previous line rate to keep previous info to compare with new line rate request.
Referenced by DpTxSs_LinkrateChgHandler, DpTxSs_PhyInit, main_loop.
XScuGic IntcInst
XDpTxSs DpTxSsInst
The DPTX Subsystem instance.
MODIFICATION HISTORY:Ver Who Date Changes - ----- -----------------------------------------------. 1.00 ND 18/10/22 Common DP 2.1 tx only application for zcu102 and vcu118 1.01 ND 26/02/24 Added support for 13.5 and 20G 2.7 GM 01/05/26 Improved formatting.
XIicPs Ps_Iic1
XIicPs_Config* XIic1Ps_ConfigPtr
volatile u8 TxReconnected
Video_CRC_Config VidFrameCRC
Video Frame CRC instance.
Referenced by DpTxSs_PlatformInit.
XVphy_PllRefClkSelType VPHY_TX_REFCLK_SEL_270
< VCU118 (270Mhz on REFCLK0, 400Mhz on REFCLK1)
< ZCU102 (270Mhz on REFCLK0, 400Mhz on NORTHREFCLK0)
Referenced by DpTxSs_PhyConfig, DpTxSs_PhyInit, PLLRefClkSel.
XVphy_PllRefClkSelType VPHY_TX_REFCLK_SEL_400
u32 DpTxSs_Main(UINTPTR BaseAddress)
This function is the main entry point for the interrupt example using the XDpTxSs driver.
This function will set up the system with interrupts and set up Hot-Plug-Event (HPD) handlers. DeviceId is the unique device ID of the DisplayPort TX Subsystem core. XST_FAILURE if the system setup failed.XST_SUCCESS should never return since this function, if setup was successful, is blocking. If system setup was successful, this function is blocking in order to illustrate interrupt handling taking place for HPD events.
References XDpTxSs_Config::BaseAddress, XDpTxSs::DpPtr, DpTxSs_PhyConfig, DpTxSs_PhyInit, DpTxSs_PlatformInit, DpTxSs_Setup, DpTxSs_SetupIntrSystem, DpTxSs_Sink_PowerCycle, DpTxSs_StartTx, main_loop, XDpTxSs_UsrOpt::MstSupport, XDpTxSs::UsrOpt, VideoFMC_Init, VPhyInst, XDpTxSs_CfgInitialize, XDpTxSs_IsConnected, XDpTxSs_LookupConfig, XDpTxSs_SetLaneCount, XDpTxSs_SetLinkRate.
Referenced by main.
u32 DpTxSs_PlatformInit(void)
This function initialize required platform-specifc peripherals.
None. XST_SUCCESS if required peripherals are initialized and configured successfully.XST_FAILURE, otherwise. None.
References ConfigPtr_IIC, IicInstance, TmrCtr, VidFrameCRC, XVidFrameCrc_Initialize.
Referenced by DpTxSs_Main.
void DpTxSs_HpdEventHandler(void *InstancePtr)
This function takes care HPD event.
None. None.
References XDpTxSs::DpPtr, DpTxSs_Sink_PowerDown, DpTxSs_Sink_PowerUp, VPhyInst, XDpTxSs_IsConnected.
void DpTxSs_HpdPulseHandler(void *InstancePtr)
This function takes care HPD pulse interrupt.
None. None.
References XDpTxSs::DpPtr, DpTxSs_HpdPulseCon, HpdPulseConEvent.
void DpTxSs_LinkrateChgHandler(void *InstancePtr)
This function sets link line rate.
@return None. None.
References DpTxSs_PhyConfig, get_Lanecounts, get_LineRate, PrevLineRate.
void DpTxSs_Pe_Vs_AdjustHandler(void *InstancePtr)
void DpTxSs_Ffe_AdjustHandler(void *InstancePtr)
References XDpTxSs::DpPtr, VPhyInst.
void DpTxSs_ExtPkt_Handler(void *InstancePtr)
void DpTxSs_Vblank_Handler(void *InstancePtr)
u32 DpTxSs_SetupIntrSystem(void)
This function sets up the interrupt system so interrupts can occur for the DisplayPort TX Subsystem core.
The function is application-specific since the actual system may or may not have an interrupt controller. The DPTX Subsystem core could be directly connected to a processor without an interrupt controller. The user should modify this function to fit the application. None XST_SUCCESS if interrupt setup was successful.A specific error code defined in "xstatus.h" if an error occurs. None.
References XDpTxSs::Config, XDpTxSs_DpIntrHandler.
Referenced by DpTxSs_Main.
u32 DpTxSs_PhyInit(UINTPTR BaseAddress)
This function configures Video Phy.
None. XST_SUCCESS if Video Phy configured successfully.XST_FAILURE, otherwise. None.
References PLLRefClkSel, PrevLineRate, VPHY_TX_REFCLK_SEL_270, VPhyInst.
Referenced by DpTxSs_Main.
void DpTxSs_CustomWaitUs(void *InstancePtr, u32 MicroSeconds)
void DpTxSs_Setup(u8 *LineRate_init, u8 *LaneCount_init, u8 Edid_org[128], u8 Edid1_org[128])
This function sets up DPTxSubsystem.
LineRate LaneCount edid 1st block edid 2nd block None. None.
References XDpTxSs::DpPtr, DpTxSs_Sink_PowerCycle, XDpTxSs_IsConnected.
Referenced by DpTxSs_Main.
void PLLRefClkSel(XVphy *InstancePtr, u8 link_rate, XVphy_ChannelId Tx_Channel)
This function sets proper ref clk frequency and line rate.
InstancePtr is a pointer to the Video PHY instance. None. None.
References VPHY_TX_REFCLK_SEL_270.
Referenced by DpTxSs_PhyConfig, DpTxSs_PhyInit.
void ClkWiz_Locked(void)
This function to check MMCM lock status.
None. None. None.
Referenced by DpTxSs_StartTx.
void DpTxSs_HpdPulseCon(XDpTxSs *InstancePtr)
This function is the main hpd pulse process.
None. None.
References XDpTxSs::DpPtr, XDpTxSs::UsrHpdPulseData, XDpTxSs_SetLaneCount, XDpTxSs_SetLinkRate, XDpTxSs_Start.
Referenced by DpTxSs_HpdPulseHandler.
void Gen_vid_clk(XDp *InstancePtr, u8 Stream)
int Vpg_StreamSrcConfigure(XDp *InstancePtr, u8 VSplitMode, u8 first_time)
This function updates required timing values in Video Pattern Generator core.
InstancePtr is a pointer to the XDp instance. VSplitMode specifies vertical split mode to be used for splitting resolution vertically. XST_SUCCESS if Video pattern configured successfully. None.
References Vpg_VidgenSetTestPattern.
Referenced by DpTxSs_StartTx.
void Vpg_VidgenSetUserPattern(XDp *InstancePtr, u8 Pattern)
This function sets user pattern.
InstancePtr is a pointer to the XDp instance. Pattern number to set with None. None.
Referenced by DpTxSs_StartTx, main_loop.
static u8 CalculateChecksum(u8 *Data, u8 Size)
This function to calculate EDID checksum.
edid data size of the edid data checksum number None.
XVidC_VideoMode GetPreferredVm(u8 *EdidPtr, u8 cap, u8 lane)
This function to find out preferred Video Mode ID.
pointer to edid data maximum capability of line speed number of lane Video Mode ID None.
Referenced by DpTxSs_HpdCon.
void ReportVideoCRC(void)
void main_loop(void)
References XDpTxSs::Config, XDpTxSs::DpPtr, DpTxSs_HpdCon, DpTxSs_Sink_PowerCycle, DpTxSs_Sink_PowerDown, DpTxSs_Sink_PowerUp, DpTxSs_StartTx, get_Lanecounts, get_LineRate, HpdPulseConEvent, XDpTxSs_Config::MaxLaneCount, PrevLineRate, Vpg_Audio_start, Vpg_Audio_stop, Vpg_VidgenSetUserPattern, VPhyInst, XDpTxSs_CheckLinkStatus, XDpTxSs_ReportLinkInfo, XDpTxSs_ReportMsaInfo, XDpTxSs_ReportSinkCapInfo, XDpTxSs_ReportVtcInfo, XDpTxSs_Reset, XDpTxSs_SendAudioInfoFrame, XDpTxSs_Stop, xil_getc, XVidFrameCrc_Report.
Referenced by DpTxSs_Main.
int Si570_Write(u8 *UpdateBuffer)
void enable_caches()
void disable_caches()
int main()
This is the main function for XDpTxSs interrupt example.
If the DpTxSs_IntrExample function which sets up the system succeeds, this function will wait for the interrupts. Once a connection event or pulse is detected, DpTxSs will RX device capabilities and re-start the subsystem. None. XST_FAILURE if the interrupt example was unsuccessful. Unless setup failed, main will never return since DpTxSs_IntrExample is blocking (it is waiting on interrupts for Hot-Plug-Detect (HPD) events.
References DpTxSs_Main.
int I2cMux_Ps(u8 Data)
static int DpTxSs_ConfigAudioClock(u32 AudioClkHz)
void DpTxSs_SetUserCallBackHandlers(void)
u32 DpTxSs_StartTx(u8 line_rate, u8 lane_count, user_config_struct user_config)
This function starts tx process.
line rate lane counts pointer to resolution table bit per components video pattern to output XST_SUCCESS if interrupt setup was successful.A specific error code defined in "xstatus.h" if an error occurs. None.
References ClkWiz_Locked, XDpTxSs::DpPtr, DpTxSs_Sink_PowerCycle, XDpTxSs::UsrOpt, Vpg_StreamSrcConfigure, Vpg_VidgenSetUserPattern, XDpTxSs_UsrOpt::VtcAdjustBs, XDpTxSs::VtcPtr, XDpTxSs_CheckLinkStatus, XDpTxSs_SetBpc, XDpTxSs_SetLaneCount, XDpTxSs_SetLinkRate, XDpTxSs_SetVidMode, XDpTxSs_Start, XDpTxSs_VtcSetup, XVidFrameCrc_Reset.
Referenced by DpTxSs_HpdCon, DpTxSs_Main, main_loop.
void DpTxSs_HpdCon(XDpTxSs *InstancePtr, u8 Edid_org[128], u16 ResUpdate)
This function is called when a Hot-Plug-Detect (HPD) event is received by the DisplayPort TX Subsystem core.
InstancePtr is a pointer to the XDpTxSs instance. None. Use the XDpTxSs_SetCallback driver function to set this function as the handler for HPD event.
References XDpTxSs::DpPtr, DpTxSs_PhyConfig, DpTxSs_StartTx, GetPreferredVm, XDpTxSs::UsrHpdEventData.
Referenced by main_loop.
void DpTxSs_Sink_PowerDown(void)
This function powers down sink.
None. None. None.
References XDpTxSs::DpPtr.
Referenced by DpTxSs_HpdEventHandler, DpTxSs_Sink_PowerCycle, main_loop.
void DpTxSs_Sink_PowerUp(void)
This function powers up sink.
None. None. None.
References XDpTxSs::DpPtr.
Referenced by DpTxSs_HpdEventHandler, DpTxSs_Sink_PowerCycle, main_loop.
u8 get_LineRate(void)
This function returns current line rate.
None. None. None.
References XDpTxSs_GetLinkRate.
Referenced by DpTxSs_LinkrateChgHandler, main_loop.
u8 get_Lanecounts(void)
This function returns current lane counts.
None. None. None.
References XDpTxSs::DpPtr.
Referenced by DpTxSs_LinkrateChgHandler, main_loop.
u32 DpTxSs_PhyConfig(int LineRate_init_tx, XVphy_PllType Tx_Pll, XVphy_ChannelId Tx_Channel)
This function sets VPHY based on the linerate.
LineRate_init_tx - Linerate LaneCount_init_tx - Lanecount Status. None.
References PLLRefClkSel, VPHY_TX_REFCLK_SEL_270, VPhyInst.
Referenced by DpTxSs_HpdCon, DpTxSs_LinkrateChgHandler, DpTxSs_Main.
void DpTxSs_Sink_PowerCycle(void)
This function power cycle the sink.
user_config_struct. Status. None.
References DpTxSs_Sink_PowerDown, DpTxSs_Sink_PowerUp.
Referenced by DpTxSs_Main, DpTxSs_Setup, DpTxSs_StartTx, main_loop.
int VideoFMC_Init(void)
References I2C_MUX_ADDR, IicInstance.
Referenced by DpTxSs_Main.
void I2C_Scan(u32 BaseAddress)
int i2c_write_freq(u32 I2CBaseAddress, u8 I2CSlaveAddress, u8 RegisterAddress, u32 Value)
u8 i2c_read_freq(u32 I2CBaseAddress, u8 I2CSlaveAddress, u16 RegisterAddress)
int i2c_write_tdp2004(u32 I2CBaseAddress, u8 I2CSlaveAddress, u8 RegisterAddress, u8 Value)
u8 i2c_read_tdp2004(u32 I2CBaseAddress, u8 I2CSlaveAddress, u16 RegisterAddress)