xdptxss_dp21_tx.h
XINTC_DPTXSS_DP_INTERRUPT_ID
XINTC
XINTC_HANDLER
XDPTXSS_DEVICE_ID
VIDEO_CRC_BASEADDR
DPTXSS_MST
DPTXSS_LINK_RATE
DPTXSS_LANE_COUNT
PARRETO_FMC
LINK_TRAINING_DEBUG
DP12_EDID_ENABLED
DPTXSS_VID_MODE
DPTXSS_BPC
SET_TX_TO_2BYTE
TIMER_RESET_VALUE
is_TX_CPLL
CLK135MHz_DIVIDER
CLK270MHz_DIVIDER
CLK162MHz_DIVIDER
ENABLE_AUDIO
AV_PAT_GEN_BASE
audio_clk_Hz
EEPROM_TEST_START_ADDRESS
PAGE_SIZE
NUM_MODES
NUM_CLOCK_REGS
XINTC_DEVICE_ID
XVPHY_DEVICE_ID
IIC_BASE_ADDR
IIC_DEVICE_ID
PE_VS_ADJUST
XVPHY_DRP_CPLL_FBDIV
XVPHY_DRP_CPLL_REFCLK_DIV
XVPHY_DRP_RXOUT_DIV
XVPHY_DRP_RXCLK25
XVPHY_DRP_TXCLK25
XVPHY_DRP_TXOUT_DIV
XVPHY_DRP_PROGDIV
DIVIDER_162
DIVIDER_270
DIVIDER_540
DIVIDER_810
XVPHY_GTHE4_PREEMP_DP_L0
XVPHY_GTHE4_PREEMP_DP_L1
XVPHY_GTHE4_PREEMP_DP_L2
XVPHY_GTHE4_PREEMP_DP_L3
XVPHY_GTHE4_DIFF_SWING_DP_V0P0
XVPHY_GTHE4_DIFF_SWING_DP_V0P1
XVPHY_GTHE4_DIFF_SWING_DP_V0P2
XVPHY_GTHE4_DIFF_SWING_DP_V0P3
XVPHY_GTHE4_DIFF_SWING_DP_V1P0
XVPHY_GTHE4_DIFF_SWING_DP_V1P1
XVPHY_GTHE4_DIFF_SWING_DP_V1P2
XVPHY_GTHE4_DIFF_SWING_DP_V2P0
XVPHY_GTHE4_DIFF_SWING_DP_V2P1
XVPHY_GTHE4_DIFF_SWING_DP_V3P0
XVPHY_GTHE4_DIFF_SWING_DP_DP20
COLOR_FORMAT_SHIFT
BPC_SHIFT
DYNAMIC_RANGE_SHIFT
CRC_CFG
void DpTxSs_HpdCon(XDpTxSs *InstancePtr, u8 Edid_org[128], u16 res_update)
This function is called when a Hot-Plug-Detect (HPD) event is received by the DisplayPort TX Subsystem core.
InstancePtr is a pointer to the XDpTxSs instance. None. Use the XDpTxSs_SetCallback driver function to set this function as the handler for HPD event.
References XDpTxSs::DpPtr, DpTxSs_PhyConfig, DpTxSs_StartTx, GetPreferredVm, XDpTxSs::UsrHpdEventData.
Referenced by main_loop.
void DpTxSs_HpdPulseCon(XDpTxSs *InstancePtr)
This function is the main hpd pulse process.
None. None.
References XDpTxSs::DpPtr, XDpTxSs::UsrHpdPulseData, XDpTxSs_SetLaneCount, XDpTxSs_SetLinkRate, XDpTxSs_Start.
Referenced by DpTxSs_HpdPulseHandler.
char xil_getc(u32 timeout_ms)
This function to get uart input from user.
timeout_ms received character None.
References TmrCtr.
Referenced by main_loop.
void Vpg_Audio_start(void)
This function starts audio pattern generator.
None. None.
Referenced by main_loop.
void Vpg_Audio_stop(void)
This function stops audio pattern generator.
None. None.
Referenced by main_loop.
u32 DpTxSs_StartTx(u8 line_rate, u8 lane_count, user_config_struct user_config)
This function starts tx process.
line rate lane counts pointer to resolution table bit per components video pattern to output XST_SUCCESS if interrupt setup was successful.A specific error code defined in "xstatus.h" if an error occurs. None.
References ClkWiz_Locked, XDpTxSs::DpPtr, DpTxSs_Sink_PowerCycle, XDpTxSs::UsrOpt, Vpg_StreamSrcConfigure, Vpg_VidgenSetUserPattern, XDpTxSs_UsrOpt::VtcAdjustBs, XDpTxSs::VtcPtr, XDpTxSs_CheckLinkStatus, XDpTxSs_SetBpc, XDpTxSs_SetLaneCount, XDpTxSs_SetLinkRate, XDpTxSs_SetVidMode, XDpTxSs_Start, XDpTxSs_VtcSetup, XVidFrameCrc_Reset.
Referenced by DpTxSs_HpdCon, DpTxSs_Main, main_loop.
u32 DpTxSs_PhyConfig(int LineRate_init_tx, XVphy_PllType Tx_Pll, XVphy_ChannelId Tx_Channel)
This function sets VPHY based on the linerate.
LineRate_init_tx - Linerate LaneCount_init_tx - Lanecount Status. None.
References PLLRefClkSel, VPHY_TX_REFCLK_SEL_270, VPhyInst.
Referenced by DpTxSs_HpdCon, DpTxSs_LinkrateChgHandler, DpTxSs_Main.
int i2c_write_freq(u32 I2CBaseAddress, u8 I2CSlaveAddress, u8 RegisterAddress, u32 Value)
u8 i2c_read_freq(u32 I2CBaseAddress, u8 I2CSlaveAddress, u16 RegisterAddress)
u8 i2c_read_tdp2004(u32 I2CBaseAddress, u8 I2CSlaveAddress, u16 RegisterAddress)
int i2c_write_tdp2004(u32 I2CBaseAddress, u8 I2CSlaveAddress, u8 RegisterAddress, u8 Value)
void Vpg_VidgenSetUserPattern(XDp *InstancePtr, u8 Pattern)
This function sets user pattern.
InstancePtr is a pointer to the XDp instance. Pattern number to set with None. None.
void DpTxSs_Sink_PowerDown(void)
This function powers down sink.
None. None. None.
References XDpTxSs::DpPtr.
Referenced by DpTxSs_HpdEventHandler, DpTxSs_Sink_PowerCycle, main_loop.
void DpTxSs_Sink_PowerUp(void)
This function powers up sink.
None. None. None.
References XDpTxSs::DpPtr.
Referenced by DpTxSs_HpdEventHandler, DpTxSs_Sink_PowerCycle, main_loop.
u8 get_LineRate(void)
This function returns current line rate.
None. None. None.
References XDpTxSs_GetLinkRate.
Referenced by DpTxSs_LinkrateChgHandler, main_loop.
u8 get_Lanecounts(void)
This function returns current lane counts.
None. None. None.
References XDpTxSs::DpPtr.
Referenced by DpTxSs_LinkrateChgHandler, main_loop.
void DpTxSs_Sink_PowerCycle(void)
This function power cycle the sink.
user_config_struct. Status. None.
References DpTxSs_Sink_PowerDown, DpTxSs_Sink_PowerUp.
Referenced by DpTxSs_Main, DpTxSs_Setup, DpTxSs_StartTx, main_loop.
void DpTxSs_Pe_Vs_AdjustHandler(void *InstancePtr)
int VideoFMC_Init(void)
References I2C_MUX_ADDR, IicInstance.
Referenced by DpTxSs_Main.