xvidframe_crc.h
XVidFrameCrc_In32
XVidFrameCrc_Out32
XPAR_VIDEO_FRAME_CRC_BASEADDR
VIDEO_FRAME_CRC_CONFIG
VIDEO_FRAME_CRC_VALUE_G_R
VIDEO_FRAME_CRC_VALUE_B
VIDEO_FRAME_CRC_ACTIVE_COUNTS
VIDEO_FRAME_CRC_CLEAR
VIDEO_FRAME_CRC_PXLMODE_MASK
VIDEO_FRAME_CRC_R_Y_COMP_MASK
VIDEO_FRAME_CRC_G_CR_COMP_MASK
VIDEO_FRAME_CRC_B_CB_COMP_MASK
VIDEO_FRAME_CRC_G_CR_COMP_SHIFT
XVidFrameCrc_ReadReg
This is a low-level function that reads from the specified register.
BaseAddress is the base address of the device. RegOffset is the register offset to be read from. The 32-bit value of the specified register. C-style signature: u32 XVidFrameCrc_ReadReg(u32 BaseAddress, u32 RegOffset)
Referenced by XVidFrameCrc_Report, XVidFrameCrc_Reset.
XVidFrameCrc_WriteReg
This is a low-level function that writes to the specified register.
BaseAddress is the base address of the device. RegOffset is the register offset to write to. Data is the 32-bit data to write to the specified register. None. C-style signature: void XVidFrameCrc_WriteReg(u32 BaseAddress, u32 RegOffset, u32 Data)
Referenced by XVidFrameCrc_Initialize, XVidFrameCrc_Reset.
int XVidFrameCrc_Initialize(Video_CRC_Config *VidFrameCRC)
This function is used to initialize the Video Frame CRC instance.
None - XST_SUCCESS or XST_FAILURE None.
References XVidFrameCrc_WriteReg.
Referenced by DpTxSs_PlatformInit.
void XVidFrameCrc_Reset(void)
This function is used to initialize the Video Frame CRC instance.
None - XST_SUCCESS or XST_FAILURE None.
References XVidFrameCrc_ReadReg, XVidFrameCrc_WriteReg.
Referenced by DpTxSs_StartTx.
void XVidFrameCrc_Report(void)
This function reports CRC values of Video components.
None. None. None.
References XVidFrameCrc_ReadReg.
Referenced by main_loop.