xdfeofdm_examples.c
int XDfeSi570_SetMgtOscillator(double CurrentFrequency, double NewFrequency)
This function: initialize I2C bus, reads current state of si570, calculates parameters for si570 MGT oscillator new frequency, writes them to si570 and resets PL to use the new frequency.
CurrentFrequency MGT oscillator current frequency. NewFrequency MGT oscillator new frequency. None None
References XST_FAILURE, XST_SUCCESS.
Referenced by main.
int XDfeOfdm_AddCCExample()
This function runs the DFE OFDM device using the driver APIs.
This function does the following tasks: Create and system initialize the device driver instance.Read SW and HW version numbers.Reset the device.Configure the device.Initialize the device.Set the triggersActivate the device.Add CC.DeActivate the device. XST_SUCCESS if the example has completed successfully.XST_FAILURE if the example has failed.//! [testexample1]
References XST_SUCCESS, XST_FAILURE, XDfeOfdm_InstanceInit, XDfeOfdm_GetVersions, XDfeOfdm_Version::Major, XDfeOfdm_Version::Minor, XDfeOfdm_Reset, XDfeOfdm_Configure, XDfeOfdm_Init::CCSequenceLength, XDfeOfdm_Initialize, XDfeOfdm_TriggerCfg::Activate, XDfeOfdm_Trigger::Mode, XDfeOfdm_Trigger::TuserEdgeLevel, XDfeOfdm_Trigger::TUSERBit, XDfeOfdm_TriggerCfg::CCUpdate, XDfeOfdm_SetTriggersCfg, XDfeOfdm_Activate, XDfeOfdm::NodeName, XDfeOfdm::Config, XDfeOfdm_Config::BaseAddr, XDfeOfdm_Config::NumAntenna, XDfeOfdm_Config::AntennaInterleave, XDfeOfdm_Cfg::Version, XDfeOfdm_Version::Revision, XDfeOfdm_Version::Patch, XDfeOfdm_Cfg::ModelParams, XDfeOfdm_ModelParameters::NumAntenna, XDfeOfdm_ModelParameters::AntennaInterleave, XDfeOfdm_Status::SaturationCCID, XDfeOfdm_Status::SaturationCount, XDfeOfdm_Status::CCUpdate, XDfeOfdm_Status::FTCCSequenceError, XDfeOfdm_Status::Saturation, XDfeOfdm_ClearEventStatus, XDfeOfdm_CarrierCfg::Numerology, XDfeOfdm_CarrierCfg::FftSize, XDfeOfdm_CarrierCfg::NumSubcarriers, XDfeOfdm_CarrierCfg::ScaleFactor, XDfeOfdm_CarrierCfg::CommsStandard, XDfeOfdm_CarrierCfg::OutputDelay, XDfeOfdm_FTSequence::Length, XDfeOfdm_Deactivate, XDfeOfdm_InstanceClose.
Referenced by main.
int XDfeOfdm_MultiAddCCExample()
This function runs the DFE OFDM device using the driver APIs.
This function does the following tasks: Create and system initialize the device driver instance.Read SW and HW version numbers.Reset the device.Configure the device.Initialize the device.Set the triggersActivate the device.Add CC.Deactivate the device. XST_SUCCESS if the example has completed successfully.XST_FAILURE if the example has failed.//! [testexample2]
References XST_SUCCESS, XST_FAILURE, XDfeOfdm_InstanceInit, XDfeOfdm_GetVersions, XDfeOfdm_Version::Major, XDfeOfdm_Version::Minor, XDfeOfdm_Reset, XDfeOfdm_Configure, XDfeOfdm_Init::CCSequenceLength, XDfeOfdm_Initialize, XDfeOfdm_TriggerCfg::Activate, XDfeOfdm_Trigger::Mode, XDfeOfdm_Trigger::TuserEdgeLevel, XDfeOfdm_Trigger::TUSERBit, XDfeOfdm_TriggerCfg::CCUpdate, XDfeOfdm_SetTriggersCfg, XDfeOfdm_Activate, XDfeOfdm::NodeName, XDfeOfdm::Config, XDfeOfdm_Config::BaseAddr, XDfeOfdm_Config::NumAntenna, XDfeOfdm_Config::AntennaInterleave, XDfeOfdm_Cfg::Version, XDfeOfdm_Version::Revision, XDfeOfdm_Version::Patch, XDfeOfdm_Cfg::ModelParams, XDfeOfdm_ModelParameters::NumAntenna, XDfeOfdm_ModelParameters::AntennaInterleave, XDfeOfdm_Status::SaturationCCID, XDfeOfdm_Status::SaturationCount, XDfeOfdm_Status::CCUpdate, XDfeOfdm_Status::FTCCSequenceError, XDfeOfdm_Status::Saturation, XDfeOfdm_ClearEventStatus, XDfeOfdm_GetCurrentCCCfg, XDfeOfdm_CarrierCfg::Numerology, XDfeOfdm_CarrierCfg::FftSize, XDfeOfdm_CarrierCfg::NumSubcarriers, XDfeOfdm_CarrierCfg::ScaleFactor, XDfeOfdm_CarrierCfg::CommsStandard, XDfeOfdm_CarrierCfg::OutputDelay, XDfeOfdm_FTSequence::Length, XDfeOfdm_AddCCtoCCCfg, XDfeOfdm_SetNextCCCfgAndTrigger, XDfeOfdm_Deactivate, XDfeOfdm_InstanceClose.
Referenced by main.
int main(void)
Main function that invokes the polled example in this file.
None. XST_SUCCESS if the example has completed successfully.XST_FAILURE if the example has failed.
References XDfeOfdm_AddCCExample, XDfeOfdm_MultiAddCCExample, XDfeSi570_SetMgtOscillator, XST_FAILURE, XST_SUCCESS.