hdcp22_tx
XHdcp22_Tx_HandlerType
XHdcp22_Tx_StateType
No Rx Attached.
XHdcp22_Tx_AuthenticationType
A HDCP2 compatible receiver is not found.
XHdcp22_Tx_ContentStreamType
Type 0 Content Stream.
Stream may be transmitted to all HDCP devices.
XHdcp22_Tx_LogEvt
Log Event None.
XHdcp22_Tx_Protocol
HDMI protocol.
XHdcp22_Tx_Mode
Module acts as a HDCP 2.2 transmitter.
XHdcp22_Tx_TopologyField
XHdcp22_Tx_TestMode
Testmode is disabled.
XHdcp22_Tx_LogDebugValue
typedef XHdcp22_Tx_StateType XHdcp22Tx_StateFuncType(XHdcp22_Tx *InstancePtr)(XHdcp22_Tx *InstancePtr)
Pointer to the state handling functions.
InstancePtr is a pointer to the XHdcp22_Tx core instance. The next state that should be executed. None.
typedef void XHdcp22_Tx_TransitionFuncType(XHdcp22_Tx *InstancePtr)(XHdcp22_Tx *InstancePtr)
Pointer to the transition functions going from one state to the next.
InstancePtr is a pointer to the XHdcp22_Tx core instance. None.
typedef void(* XHdcp22_Tx_Callback)(void *HandlerRef))(void *CallbackRef)
Callback type for status.
Callback type used for pointer to single input function. CallbackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. None. None.
typedef int(* XHdcp22_Tx_DdcHandler)(u8 DeviceAddress, u16 ByteCount, u8 *BufferPtr, u8 Stop, void *RefPtr))(u8 DeviceAddress, u16 ByteCount, u8 *BufferPtr, u8 Stop, void *RefPtr)
Callback type used for calling DDC read and write functions.
DeviceAddress is the (i2c) device address of the HDCP port. ByteCount is the amount of data bytes in the buffer to read or write. BufferPtr is a pointer to a buffer that is used for reading or writing. Stop is a flag to control if a stop token is set or not. RefPtr is a callback reference passed in by the upper layer when setting the DDC reading and writing functions, and passed back to the upper layer when the callback is invoked. XST_SUCCESS The read action was successful.XST_FAILURE The read action failed. None.
XHdcp22Tx_StateFuncType* const XHdcp22_Tx_StateTable[XHDCP22_TX_NUM_STATES][XHDCP22_TX_NUM_STATES]
This table contains the function pointers for all possible states.
The order of elements must match the XHdcp22_Tx_StateType enumerator definitions.
Referenced by XHdcp22Tx_Poll.
XHdcp22_Tx_TransitionFuncType* transition_table[XHDCP22_TX_NUM_STATES][XHDCP22_TX_NUM_STATES][XHDCP22_TX_NUM_STATES][XHDCP22_TX_NUM_STATES]
This table is a matrix that contains the function pointers for functions to execute on state transition.
It is filled dynamically. A NULL value is used if no transition is required.
const u8 XHdcp22_Tx_KpubDcp[XHDCP22_TX_KPUB_DCP_LLC_N_SIZE+XHDCP22_TX_KPUB_DCP_LLC_E_SIZE][XHDCP22_TX_KPUB_DCP_LLC_N_SIZE+XHDCP22_TX_KPUB_DCP_LLC_E_SIZE]
const u8 XHdcp22_Tx_TxCaps[][]
This array contains the capabilities of the HDCP22 TX core, and is transmitted during authentication as part of the AKE_Init message.
static int XHdcp22Tx_InitializeTimer(XHdcp22_Tx *InstancePtr)
This function is a called to initialize the hardware timer.
InstancePtr is a pointer to the XHdcp22Tx core instance. XST_SUCCESS if authenticated is started successfully.XST_FAIL if the state machine is disabled. None.
static int XHdcp22Tx_InitializeCipher(XHdcp22_Tx *InstancePtr)
This function is a called to initialize the cipher.
InstancePtr is a pointer to the XHdcp22Tx core instance. XST_SUCCESS if authenticated is started successfully.XST_FAIL if the state machine is disabled. None.
static int XHdcp22Tx_InitializeRng(XHdcp22_Tx *InstancePtr)
This function is a called to initialize the hardware random generator.
InstancePtr is a pointer to the XHdcp22Tx core instance. XST_SUCCESS if authenticated is started successfully.XST_FAIL if the state machine is disabled. None.
static int XHdcp22Tx_ComputeBaseAddress(UINTPTR BaseAddress, UINTPTR SubcoreOffset, UINTPTR *SubcoreAddressPtr)
This function computes the subcore absolute address on axi-lite interface Subsystem is mapped at an absolute address and all included sub-cores are at pre-defined offset from the subsystem base address.
To access the subcore register map from host CPU an absolute address is required. BaseAddress is the base address of the subsystem instance SubcoreOffset is the offset of the the subcore instance SubcoreAddressPtr is the computed base address of the subcore instance XST_SUCCESS if base address computation is successful and within subsystem address range else XST_FAILURE
static int XHdcp22Tx_StubDdc(u8 DeviceAddress, u16 ByteCount, u8 *BufferPtr, u8 Stop, void *RefPtr)
This function is a dummy called as long as there is no valid ddc handler set.
It always returns an error. DeviceAddress is the DDC (i2c) device address. ByteCount is the number of bytes in the buffer. BufferPtr is the buffer that stores the data to be written or read. Stop is a flag to signal i2c stop condition. RefPtr is the reference pointer for the handler. XST_FAILURE None.
static void XHdcp22Tx_StubCallback(void *RefPtr)
This function is a dummy called as long as there is no valid authenticated handler set.
It always returns an error. RefPtr is the reference pointer for the handler. XST_FAILURE None.
static XHdcp22_Tx_StateType XHdcp22Tx_StateH0(XHdcp22_Tx *InstancePtr)
This function is the implementation of the HDCP transmit H0 state.
According protocol this is the reset state that is entered initially. As soon as hot plug is detected and Rx is available, a transition to state h1 is performed. Since hotplug detect is controlled by the user, the next state is always state H1. InstancePtr is a pointer to the XHdcp22Tx core instance. XHDCP22_TX_STATE_H1 None.
static XHdcp22_Tx_StateType XHdcp22Tx_StateH1(XHdcp22_Tx *InstancePtr)
This function is the implementation of the HDCP transmit H1 state.
As soon as hot plug is detected and Rx is available, a transition to this state is performed. Hotplug detection if controlled by the user of this core. This means that this state is practically the entry state. InstancePtr is a pointer to the XHDCP22 TX core instance. XHDCP22_TX_STATE_A0 if the attached receiver is HDCP2 capable.XHDCP22_TX_STATE_H1 if the attached receiver is NOT HDCP2 capable. None.
static XHdcp22_Tx_StateType XHdcp22Tx_StateA0(XHdcp22_Tx *InstancePtr)
This function is the implementation of the HDCP transmit A0 state.
If content protection not desired, return to H1 state. InstancePtr is a pointer to the XHDCP22 TX core instance. XHDCP22_TX_STATE_H1 if state machine is set to disabled (content protection NOT desired).XHDCP22_TX_STATE_A1 if authentication must start. None.
static XHdcp22_Tx_StateType XHdcp22Tx_StateA1(XHdcp22_Tx *InstancePtr)
This function executes the first part of the A1 state of the HDCP2.2 TX protocol.
InstancePtr is a pointer to the XHdcp22Tx core instance. XHDCP22_TX_STATE_A1_1 None.
XHdcp22_Tx_StateType Xhdcp22Tx_StateA1_1(XHdcp22_Tx *InstancePtr)
This function executes a part of the A1 state functionality of the HDCP2.2 TX protocol.
It receives the certificate and decides if it should continue to a 'no stored km' or 'stored Km'intermediate state. InstancePtr is a pointer to the XHdcp22Tx core instance. XHDCP22_TX_STATE_A0 on errors.XHDCP22_TX_STATE_A1_1 if busy waiting for the XHDCP22_TX_AKE_SEND_CERT message.XHDCP22_TX_STATE_A1_SK0 for a 'Stored Km' scenario.XHDCP22_TX_STATE_A1_NSK0 for a 'Non Stored Km' scenario. None.
static XHdcp22_Tx_StateType Xhdcp22Tx_StateA1_Nsk0(XHdcp22_Tx *InstancePtr)
This function executes a part of the A1 state functionality of the HDCP2.2 TX protocol.
It handles a part of the 'No Stored Km' scenario and receives and verifies H' InstancePtr is a pointer to the XHdcp22Tx core instance. XHDCP22_TX_STATE_A0 on errors.XHDCP22_TX_STATE_A1_NSK0 if busy waiting for the XHDCP22_TX_AKE_SEND_H_PRIME message.XHDCP22_TX_STATE_A1_NSK1 for the next part of the 'Stored Km' scenario. None.
static XHdcp22_Tx_StateType Xhdcp22Tx_StateA1_Nsk1(XHdcp22_Tx *InstancePtr)
This function executes a part of the A1 state functionality of the HDCP2.2 TX protocol.
It handles a part of the 'No Stored Km' scenario and receives and stores pairing info. InstancePtr is a pointer to the XHdcp22Tx core instance. XHDCP22_TX_STATE_A0 on errors.XHDCP22_TX_STATE_A1_NSK1 if busy waiting for the XHDCP22_TX_AKE_SEND_PAIRING_INFO message.XHDCP22_TX_STATE_A2 if authentication is done. None.
static XHdcp22_Tx_StateType Xhdcp22Tx_StateA1_Sk0(XHdcp22_Tx *InstancePtr)
This function executes a part of the A1 state functionality of the HDCP2.2 TX protocol.
It handles a part of the 'Stored Km' scenario and receives and verifies H'. InstancePtr is a pointer to the XHdcp22Tx core instance. XHDCP22_TX_STATE_A0 on errors.XHDCP22_TX_STATE_A1_SK0 if busy waiting for theXHDCP22_TX_AKE_SEND_H_PRIME message.XHDCP22_TX_STATE_A2 if authentication is done. None.
static XHdcp22_Tx_StateType XHdcp22Tx_StateA2(XHdcp22_Tx *InstancePtr)
This function executes the A2 state of the HDCP2.2 TX protocol.
InstancePtr is a pointer to the XHdcp22Tx core instance. The next state to execute. None.
static XHdcp22_Tx_StateType XHdcp22Tx_StateA2_1(XHdcp22_Tx *InstancePtr)
This function executes a part of the A2 state functionality of the HDCP2.2 TX protocol.
It receives and verifies L' (locality check). InstancePtr is a pointer to the XHdcp22Tx core instance. XHDCP22_TX_STATE_A2_1 if busy waiting for the XHDCP22_TX_AKE_SEND_L_PRIME message.XHDCP22_TX_STATE_A3 if authentication is done. None.
static XHdcp22_Tx_StateType XHdcp22Tx_StateA3(XHdcp22_Tx *InstancePtr)
This function executes the A3 state of the HDCP2.2 TX protocol.
InstancePtr is a pointer to the XHdcp22Tx core instance. The next state to execute. None.
static XHdcp22_Tx_StateType XHdcp22Tx_StateA4(XHdcp22_Tx *InstancePtr)
This function executes the A4 state of the HDCP2.2 TX protocol.
InstancePtr is a pointer to the XHdcp22Tx core instance. The next state to execute. None.
static XHdcp22_Tx_StateType XHdcp22Tx_StateA5(XHdcp22_Tx *InstancePtr)
This function executes the A5 state of the HDCP2.2 TX protocol.
Before authentication is granted, a 200 ms mandatory wait is added, so the integrating application does not start the cipher premature. InstancePtr is a pointer to the XHdcp22Tx core instance. The next state to execute. None.
static XHdcp22_Tx_StateType XHdcp22Tx_StateA6_A7_A8(XHdcp22_Tx *InstancePtr)
This function executes the states A6, A7 and A8 of the HDCP2.2 TX protocol.
Within these states the HDCP2.2 TX receives and verifies the receiver ID list. The HDCP2.2 TX is required to send a response within 2 seconds after the HDCP2.2 repeater has made the receiver ID list available. These states have been grouped in order to guarantee that the HDCP2.2 TX responds as fast as it can. InstancePtr is a pointer to the XHdcp22Tx core instance. The next state to execute. None.
static XHdcp22_Tx_StateType XHdcp22Tx_StateA6(XHdcp22_Tx *InstancePtr)
This function executes the A6 state of the HDCP2.2 TX protocol.
InstancePtr is a pointer to the XHdcp22Tx core instance. The next state to execute. None.
static XHdcp22_Tx_StateType XHdcp22Tx_StateA7(XHdcp22_Tx *InstancePtr)
This function executes the A7 state of the HDCP2.2 TX protocol.
InstancePtr is a pointer to the XHdcp22Tx core instance. The next state to execute. None.
static XHdcp22_Tx_StateType XHdcp22Tx_StateA8(XHdcp22_Tx *InstancePtr)
This function executes the A8 state of the HDCP2.2 TX protocol.
InstancePtr is a pointer to the XHdcp22Tx core instance. The next state to execute. None.
static XHdcp22_Tx_StateType XHdcp22Tx_StateA9(XHdcp22_Tx *InstancePtr)
This function executes the first portion of the A9 state of the HDCP2.2 TX protocol.
InstancePtr is a pointer to the XHdcp22Tx core instance. The next state to execute. None.
static XHdcp22_Tx_StateType XHdcp22Tx_StateA9_1(XHdcp22_Tx *InstancePtr)
This function executes the second portion of the A9 state of the HDCP2.2 TX protocol.
InstancePtr is a pointer to the XHdcp22Tx core instance. The next state to execute. None.
static void XHdcp22Tx_A1A0(XHdcp22_Tx *InstancePtr)
This function executes on transition from state A1 or one of its sub states to A0, which means that an error in authentication has occurred.
InstancePtr is a pointer to the XHdcp22Tx core instance. None. None.
static void XHdcp22Tx_A1A2(XHdcp22_Tx *InstancePtr)
This function executes on transition from state A1_SK0 or A1_NSK1 to A2, which means that state A2 is executed for the first time.
The locality check counter is initialized. Subsequent locality checks are then executed for an extra 1023 times. InstancePtr is a pointer to the XHdcp22Tx core instance. None. None.
static void XHdcp22Tx_A2A0(XHdcp22_Tx *InstancePtr)
This function executes on transition from state A2 or one of its substates to A0, which means that an error in authentication has occurred.
InstancePtr is a pointer to the XHdcp22Tx core instance. None. None.
static void XHdcp22Tx_A3A0(XHdcp22_Tx *InstancePtr)
This function executes on transition from state A3 to A0, which means that an error in authentication has occurred.
InstancePtr is a pointer to the XHdcp22Tx core instance. None. None.
static void XHdcp22Tx_A3A4(XHdcp22_Tx *InstancePtr)
This function executes on transition from state A3 to A4, which means that the Session Key Exchange (SKE) has completed.
InstancePtr is a pointer to the XHdcp22Tx core instance. None. None.
static void XHdcp22Tx_A4A5(XHdcp22_Tx *InstancePtr)
This function executes on transition from state A4 to A5, which means that an authentication has succeeded and state A5 is executed the first time.
InstancePtr is a pointer to the XHdcp22Tx core instance. None. None.
static void XHdcp22Tx_A6A7A0(XHdcp22_Tx *InstancePtr)
This function executes on transition from state A6 or A7 to A0, which means that an error in authentication has occurred.
InstancePtr is a pointer to the XHdcp22Tx core instance. None. None.
static void XHdcp22Tx_A9A0(XHdcp22_Tx *InstancePtr)
This function executes on transition from state A9 to A0, which means that an error in the content stream management has occurred.
InstancePtr is a pointer to the XHdcp22Tx core instance. None. None.
static int XHdcp22Tx_WriteAKEInit(XHdcp22_Tx *InstancePtr)
This function issues a AKE_Init message.
InstancePtr is a pointer to the XHdcp22Tx core instance. MsgBufferPtr the buffer to use for messaging. XST_SUCCESS if writing succeededXST_FAILURE if failed to write. None.
static int XHdcp22Tx_WriteAKENoStoredKm(XHdcp22_Tx *InstancePtr, const XHdcp22_Tx_PairingInfo *PairingInfoPtr, const XHdcp22_Tx_CertRx *CertificatePtr)
This function issues a AKE_No_Stored_km message.
InstancePtr is a pointer to the XHdcp22Tx core instance. MsgBufferPtr the buffer containing the certificate and re-used for sending the message. XST_SUCCESS if writing succeededXST_FAILURE if failed to write None.
static int XHdcp22Tx_WriteAKEStoredKm(XHdcp22_Tx *InstancePtr, const XHdcp22_Tx_PairingInfo *PairingInfoPtr)
This function issues a AKE_Stored_km message.
InstancePtr is a pointer to the XHdcp22Tx core instance. MsgBufferPtr the buffer to use for messaging. XST_SUCCESS if writing succeededXST_FAILURE if failed to write None.
static int XHdcp22Tx_WriteLcInit(XHdcp22_Tx *InstancePtr, const u8 *RnPtr)
This function write a locality check has value.
InstancePtr is a pointer to the XHdcp22Tx core instance. RnPtr is a pointer to the XHdcp22Tx core instance. XST_SUCCESS if writing succeededXST_FAILURE if failed to write None.
static int XHdcp22Tx_WriteSkeSendEks(XHdcp22_Tx *InstancePtr, const u8 *EdkeyKsPtr, const u8 *RivPtr)
This function sends the session key to the receiver.
InstancePtr is a pointer to the XHdcp22Tx core instance. EdkeyKsPtr is a pointer to the encrypted session key. RivPtr is a pointer to the random IV pair. XST_SUCCESS if writing succeededXST_FAILURE if failed to write None.
static int XHdcp22Tx_WriteRepeaterAuth_Send_Ack(XHdcp22_Tx *InstancePtr, const u8 *VPtr)
This function sends the Receiver ID List acknowledgement to the repeater.
InstancePtr is a pointer to the XHdcp22Tx core instance. VPtr is a pointer to the least significant 128-bits of V. XST_SUCCESS if writing succeededXST_FAILURE if failed to write None.
static int XHdcp22Tx_WriteRepeaterAuth_Stream_Manage(XHdcp22_Tx *InstancePtr)
This function sends the Content Stream Type to the repeater.
InstancePtr is a pointer to the XHdcp22Tx core instance. XST_SUCCESS if writing succeededXST_FAILURE if failed to write None.
static int XHdcp22Tx_ReceiveMsg(XHdcp22_Tx *InstancePtr, u8 MessageId, u32 MessageSize)
This function receives a message send by HDCP22 RX.
InstancePtr is a pointer to the XHdcp22Tx core instance. MessageId the message Id of the expected message. MessageSize the size of the expected message. XST_SUCCESS if the message size and id are as expected.XST_FAILURE if if the message size and id are incorrect. None.
static void XHdcp22Tx_GenerateRtx(XHdcp22_Tx *InstancePtr, u8 *RtxPtr)
This function returns a pseudo random 64-bit value for Rtx as part of the HDCP22 TX initiation message.
If appropriate it is overwritten with a test vector. InstancePtr is a pointer to the XHdcp22Tx core instance. RtxPtr is a 64-bit random value; None. None.
static void XHdcp22Tx_GenerateKm(XHdcp22_Tx *InstancePtr, u8 *KmPtr)
This function returns a pseudo random 128-bit value for Km as part of the HDCP22 TX initiation message.
If appropriate it is overwritten with a test vector. InstancePtr is a pointer to the XHdcp22Tx core instance. KmPtr is a pointer to a 128 bits random value. None. None.
static void XHdcp22Tx_GenerateKmMaskingSeed(XHdcp22_Tx *InstancePtr, u8 *SeedPtr)
This function returns a pseudo random 64-bit value for Rn as part of the locality check.
If appropriate it is overwritten with a test vector. InstancePtr is a pointer to the XHdcp22Tx core instance. KmPtr is a pointer to a 256 bits random seed value. None. None.
static void XHdcp22Tx_GenerateRn(XHdcp22_Tx *InstancePtr, u8 *RnPtr)
This function returns a pseudo random 64-bit value for Rn as part of the HDCP22 TX locality check.
If appropriate it is overwritten with a test vector. InstancePtr is a pointer to the XHdcp22Tx core instance. RnPtr is a pointer to a 64 bits random value. None. None.
static void XHdcp22Tx_GenerateRiv(XHdcp22_Tx *InstancePtr, u8 *RivPtr)
This function returns a pseudo random 64-bit value for Riv as part of the HDCP22 TX session key exchange message.
If appropriate it is overwritten with a test vector. InstancePtr is a pointer to the XHdcp22Tx core instance. RivPtr is a 64-bit random value; None. None.
static void XHdcp22Tx_GenerateKs(XHdcp22_Tx *InstancePtr, u8 *KsPtr)
This function returns a pseudo random 128-bit value for Ks as part of the HDCP22 TX session key exchange message.
If appropriate it is overwritten with a test vector. InstancePtr is a pointer to the XHdcp22Tx core instance. KsPtr is a 128-bit random value; None. None.
static const u8 * XHdcp22Tx_GetKPubDpc(XHdcp22_Tx *InstancePtr)
This function returns the DCP LLC public key If appropriate it returns a test vector.
InstancePtr is a pointer to the XHdcp22Tx core instance. RivPtr is a 64-bit random value; None. None.
static XHdcp22_Tx_PairingInfo * XHdcp22Tx_GetPairingInfo(XHdcp22_Tx *InstancePtr, const u8 *ReceiverId)
This function gets a stored pairing info entry from the storage.
ReceiverId is a pointer to a 5-byte receiver Id. A pointer to the found ReceiverId or NULL if the pairing info wasn't stored yet. None.
static void XHdcp22Tx_InvalidatePairingInfo(XHdcp22_Tx *InstancePtr, const u8 *ReceiverId)
This function invalidates a pairing info structure.
ReceiverId is a pointer to a 5-byte receiver Id. None. None.
static XHdcp22_Tx_PairingInfo * XHdcp22Tx_UpdatePairingInfo(XHdcp22_Tx *InstancePtr, const XHdcp22_Tx_PairingInfo *PairingInfo, u8 Ready)
This function updates a pairing info entry in the storage.
PairingInfo is a pointer to a pairing info structure. XST_SUCCESS if there was enough roomXST_FAILURE if there was no room for this receiver None.
static void XHdcp22Tx_TimerHandler(void *CallbackRef, u8 TmrCntNumber)
This function handles timer interrupts.
CallbackRef refers to a XHdcp22_Tx structure TmrCntNumber the number of used timer. None. None.
static int XHdcp22Tx_StartTimer(XHdcp22_Tx *InstancePtr, u32 TimeOut_mSec, u8 ReasonId)
This function starts the timer needed for checking the HDCP22 Receive status register.
In case the timer is started to receive a message, the MsgAvailable flag is reset. InstancePtr is a pointer to the XHdcp22Tx core instance. TimeOut_mSec is the timeout for the next status update. XST_SUCCESS or XST_FAILURE. None.
static int XHdcp22Tx_WaitForReceiver(XHdcp22_Tx *InstancePtr, int ExpectedSize, u8 ReadyBit)
This function waits for receiving expected messages from the receiver.
If the timer is not started, it will be started. This has to be used to avoid blocking waits, and allows polling to return to allow the main thread to continue handling other requests. Some receivers require to read status as soon as possible otherwise the receiver may request for a re-authentication so we must poll! InstancePtr is a pointer to the XHdcp22Tx core instance. ExpectedSize indicates the expected message size in bytes. ReadyBit indicates if the repeater ready bit from RxStatus register should be used or the specified ExpectedSize. TRUE Ready bit from RxStatus is used. ExpectedSize will be ignored.FALSE ExpectedSize is used. Ready bit from RxStatus will be ignored. XST_SUCCESS if no problemsXST_FAILURE if the receiver has timed out None.
static u32 XHdcp22Tx_GetTimerCount(XHdcp22_Tx *InstancePtr)
This function returns the current timer count value of the expiration timer.
register. InstancePtr is a pointer to the XHdcp22Tx core instance. TimeOut_mSec is the timeout for the next status update. XST_SUCCESS if the timer count could be acquired.XST_FAILURE if not. None.
static void XHdcp22Tx_ReadRxStatus(XHdcp22_Tx *InstancePtr)
This function reads RxStatus from the DDC channel.
If the read is not successful it will default to an RxStatus value of 0xFFFF to initiate re-authentication. InstancePtr is a pointer to the XHdcp22Tx core instance. MsgBufferPtr the buffer to use for messaging. None. None.
static void XHdcp22Tx_HandleAuthenticationFailed(XHdcp22_Tx *InstancePtr)
This function handles authentication failures.
InstancePtr is a pointer to the XHdcp22Tx core instance. None. None.
static void XHdcp22Tx_HandleReauthenticationRequest(XHdcp22_Tx *InstancePtr)
This function handles reauthentication requests.
InstancePtr is a pointer to the XHdcp22Tx core instance. None. None.
static u32 XHdcp22Tx_GetTopologyDepth(XHdcp22_Tx *InstancePtr)
This function returns the DEPTH in the repeater topology structure.
InstancePtr is a pointer to the XHdcp22_Tx core instance. Repeater topology DEPTH. None.
static u32 XHdcp22Tx_GetTopologyDeviceCnt(XHdcp22_Tx *InstancePtr)
This function returns the DEVICE_COUNT in the repeater topology structure.
InstancePtr is a pointer to the XHdcp22_Tx core instance. DEVICE_COUNT in the repeater topology structure. None.
static u32 XHdcp22Tx_GetTopologyMaxDevsExceeded(XHdcp22_Tx *InstancePtr)
This function returns the MAX_DEVICS_EXCEEDED flag in the repeater topology structure.
InstancePtr is a pointer to the XHdcp22_Tx core instance. MAX_DEVICS_EXCEEDED flag in the repeater structure. None.
static u32 XHdcp22Tx_GetTopologyMaxCascadeExceeded(XHdcp22_Tx *InstancePtr)
This function returns the MAX_CASCADE_EXCEEDED flag in the repeater topology structure.
InstancePtr is a pointer to the XHdcp22_Tx core instance. MAX_CASCADE_EXCEEDED flag in the repeater structure. None.
static u32 XHdcp22Tx_GetTopologyHdcp2LegacyDeviceDownstream(XHdcp22_Tx *InstancePtr)
This function returns the HDCP2_LEGACY_DEVICE_DOWNSTREAM flag in the repeater topology structure.
InstancePtr is a pointer to the XHdcp22_Tx core instance. HDCP2_LEGACY_DEVICE_DOWNSTREAM flag in the repeater structure. None.
static u32 XHdcp22Tx_GetTopologyHdcp1DeviceDownstream(XHdcp22_Tx *InstancePtr)
This function returns the HDCP1_DEVICE_DOWNSTREAM flag in the repeater topology structure.
InstancePtr is a pointer to the XHdcp22_Tx core instance. HDCP1_DEVICE_DOWNSTREAM flag in the repeater structure. None.
int XHdcp22Tx_CfgInitialize(XHdcp22_Tx *InstancePtr, XHdcp22_Tx_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the HDCP22 TX core.
This function must be called prior to using the HDCP TX core. Initialization of the HDCP TX includes setting up the instance data and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the XHdcp22_Tx core instance. CfgPtr points to the configuration structure associated with the HDCP TX core. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS Initialization was successful.XST_FAILURE Initialization of the internal timer failed or there was a HDCP TX PIO ID mismatch. None.
References XHdcp22_Tx::AuthenticatedCallback, XHdcp22_Tx_Info::AuthenticationStatus, XHdcp22_Tx_Config::BaseAddress, XHdcp22_Tx::Config, XHdcp22_Tx_Info::ContentStreamType, XHdcp22_Tx_Info::CurrentState, XHdcp22_Tx::DdcRead, XHdcp22_Tx::DdcWrite, XHdcp22_Tx::DownstreamTopologyAvailableCallback, XHdcp22_Tx::Info, XHdcp22_Tx_Timer::InitialTicks, XHdcp22_Tx::IsAuthenticatedCallbackSet, XHdcp22_Tx_Info::IsContentStreamTypeSet, XHdcp22_Tx::IsDdcReadSet, XHdcp22_Tx::IsDdcWriteSet, XHdcp22_Tx::IsDownstreamTopologyAvailableCallbackSet, XHdcp22_Tx_Info::IsEnabled, XHdcp22_Tx::IsReady, XHdcp22_Tx_Info::IsReceiverHDCP2Capable, XHdcp22_Tx_Info::IsRevocationListValid, XHdcp22_Tx_Info::IsTopologyAvailable, XHdcp22_Tx::IsUnauthenticatedCallbackSet, XHdcp22_Tx_Info::MsgAvailable, XHdcp22_Tx_Info::PollingValue, XHdcp22_Tx_Info::Protocol, XHdcp22_Tx_Info::PrvState, XHdcp22_Tx_Timer::ReasonId, XHdcp22_Tx_Info::ReceivedFirstSeqNum_V, XHdcp22_Tx::RevocationList, XHdcp22_Tx_Info::StateContext, XHdcp22_Tx::Timer, XHdcp22_Tx_Timer::TimerExpired, XHdcp22_Tx::UnauthenticatedCallback, XHDCP22_STREAMTYPE_0, XHDCP22_TX_DEFAULT_RX_STATUS_POLLVALUE, XHDCP22_TX_HDMI, XHDCP22_TX_STATE_A0, XHDCP22_TX_STATE_A1, XHDCP22_TX_STATE_A1_1, XHDCP22_TX_STATE_A1_NSK0, XHDCP22_TX_STATE_A1_NSK1, XHDCP22_TX_STATE_A1_SK0, XHDCP22_TX_STATE_A2, XHDCP22_TX_STATE_A2_1, XHDCP22_TX_STATE_A3, XHDCP22_TX_STATE_A4, XHDCP22_TX_STATE_A5, XHDCP22_TX_STATE_A6_A7_A8, XHDCP22_TX_STATE_A9, XHDCP22_TX_STATE_H0, XHDCP22_TX_TS_UNDEFINED, XHDCP22_TX_UNAUTHENTICATED, XHdcp22Tx_ClearPairingInfo, XHdcp22Tx_LogReset.
void XHdcp22Tx_LoadLc128(XHdcp22_Tx *InstancePtr, const u8 *Lc128Ptr)
This function is used to load the Lc128 value by copying the contents of the array referenced by Lc128Ptr into the cipher.
InstancePtr is a pointer to the XHdcp22_Tx core instance. Lc128Ptr is a pointer to an array. None.
References XHdcp22_Tx::Cipher, XHDCP22_TX_LC128_SIZE.
int XHdcp22Tx_LoadRevocationTable(XHdcp22_Tx *InstancePtr, const u8 *SrmPtr)
This function is used to load the system renewability messages (SRMs) which carries the Receiver ID revocation list.
InstancePtr is a pointer to the XHdcp22_Tx core instance. SrmPtr is a pointer to an array. XST_SUCCESS if loaded SRM successfully.XST_FAILURE if SRM signature verification failed. None.
References XHdcp22_Tx::Info, XHdcp22_Tx_Info::IsRevocationListValid, XHDCP22_TX_KPUB_DCP_LLC_E_SIZE, XHDCP22_TX_KPUB_DCP_LLC_N_SIZE, XHDCP22_TX_REVOCATION_LIST_MAX_DEVICES, XHDCP22_TX_SRM_RCVID_SIZE, XHdcp22Tx_GetRevocationReceiverIdList, XHdcp22Tx_VerifySRM.
u8 XHdcp22Tx_IsDeviceRevoked(XHdcp22_Tx *InstancePtr, u8 *RecvIdPtr)
This function searches for the specified ReceiverID in the revocation list.
InstancePtr is a pointer to the XHdcp22_Tx core instance. RecvIdPtr is a pointer to the ReceiverID to lookup TRUE if Receiver ID was found in the revocation listFALSE if Receiver ID was not found in the revocation list None.
References XHDCP22_TX_SRM_RCVID_SIZE, XHdcp22Tx_GetRevocationReceiverIdList.
Referenced by XHdcp22Tx_RevokeReceiverId.
XHdcp22_Tx_RevocationList * XHdcp22Tx_GetRevocationReceiverIdList(XHdcp22_Tx *InstancePtr)
This function returns a pointer to the Revocation Receiver ID list.
InstancePtr is a pointer to the XHdcp22_Tx instance. Pointer to the XHdcp22_Tx_RevocationList instance.
References XHdcp22_Tx::RevocationList.
Referenced by XHdcp22Tx_IsDeviceRevoked, XHdcp22Tx_LoadRevocationTable, XHdcp22Tx_RevokeReceiverId.
XHdcp22_Tx_Topology * XHdcp22Tx_GetTopology(XHdcp22_Tx *InstancePtr)
This function returns a pointer to the downstream topology structure.
InstancePtr is a pointer to the XHdcp22_Tx core instance. A pointer to the XHdcp22_Tx_Topology structure or NULL when the topology info is invalid. None.
References XHdcp22_Tx::Info, XHdcp22_Tx_Info::IsTopologyAvailable, XHdcp22_Tx::Topology.
u8 * XHdcp22Tx_GetTopologyReceiverIdList(XHdcp22_Tx *InstancePtr)
This function returns a pointer to the ReceiverID list in the repeater topology structure.
InstancePtr is a pointer to the XHdcp22_Tx core instance. A pointer to the ReceiverID list in the topology structure. None.
References XHdcp22_Tx_Topology::ReceiverId, XHdcp22_Tx::Topology.
u32 XHdcp22Tx_GetTopologyField(XHdcp22_Tx *InstancePtr, XHdcp22_Tx_TopologyField Field)
This function is used to get various fields inside the topology structure.
InstancePtr is a pointer to the XHdcp22_Tx core instance. Field indicates what field of the topology structure to get. Value associated to field inside the topology structure. None.
void XHdcp22Tx_SetContentStreamType(XHdcp22_Tx *InstancePtr, XHdcp22_Tx_ContentStreamType StreamType)
This function sets the Content Stream Type.
InstancePtr is a pointer to the XHdcp22_Tx instance. StreamType specifies the content stream type.
References XHdcp22_Tx_Info::ContentStreamType, XHdcp22_Tx::Info, XHdcp22_Tx_Info::IsContentStreamTypeSet.
u32 XHdcp22Tx_GetVersion(XHdcp22_Tx *InstancePtr)
This function reads the version.
InstancePtr is a pointer to the XHdcp22_Tx core instance. Returns the version register of the cipher. None.
References XHdcp22_Tx::Cipher.
int XHdcp22Tx_Authenticate(XHdcp22_Tx *InstancePtr)
This function is a called to start authentication.
InstancePtr is a pointer to the XHdcp22Tx core instance. XST_SUCCESS if authenticated is started successfully.XST_FAIL if the state machine is disabled. None.
References XHdcp22_Tx_Info::AuthenticationStatus, XHdcp22_Tx_Info::CurrentState, XHdcp22_Tx::Info, XHdcp22_Tx_Info::IsContentStreamTypeSet, XHdcp22_Tx_Info::IsEnabled, XHdcp22_Tx_Info::IsReceiverHDCP2Capable, XHdcp22_Tx_Info::IsTopologyAvailable, XHdcp22_Tx_Info::PrvState, XHDCP22_TX_AUTHENTICATION_BUSY, XHDCP22_TX_STATE_H0, XHdcp22Tx_IsRepeater.
int XHdcp22Tx_Poll(XHdcp22_Tx *InstancePtr)
This function is a executed every time to trigger the state machine.
The user of HDCP22 TX is responsible to call this function on a regular base. InstancePtr is a pointer to the XHdcp22Tx core instance. Enumerated authentication status defined in XHdcp22_Tx_AuthenticationType. None.
References XHdcp22_Tx_Info::AuthenticationStatus, XHdcp22_Tx_Info::CurrentState, XHdcp22_Tx::Info, XHdcp22_Tx_Info::IsEnabled, XHdcp22_Tx_Info::PrvState, XHdcp22_Tx::Timer, XHdcp22_Tx_Timer::TimerExpired, XHDCP22_TX_AUTHENTICATION_BUSY, XHDCP22_TX_LOG_EVT_POLL_RESULT, XHdcp22_Tx_StateTable, XHdcp22Tx_LogWr.
int XHdcp22Tx_Reset(XHdcp22_Tx *InstancePtr)
This function resets the state machine.
InstancePtr is a pointer to the XHdcp22Tx core instance. XST_SUCCESS None.
References XHdcp22_Tx_Info::AuthenticationStatus, XHdcp22_Tx_Info::AuthRequestCnt, XHdcp22_Tx::Cipher, XHdcp22_Tx_Info::CurrentState, XHdcp22_Tx::Info, XHdcp22_Tx_Info::IsTopologyAvailable, XHdcp22_Tx::IsUnauthenticatedCallbackSet, XHdcp22_Tx_Info::PrvState, XHdcp22_Tx_Info::ReauthRequestCnt, XHdcp22_Tx::Timer, XHdcp22_Tx_Timer::TmrCtr, XHdcp22_Tx::UnauthenticatedCallback, XHDCP22_TX_AUTHENTICATED, XHDCP22_TX_LOG_EVT_RESET, XHDCP22_TX_STATE_H0, XHDCP22_TX_TIMER_CNTR_0, XHDCP22_TX_UNAUTHENTICATED, XHdcp22Tx_DisableEncryption, XHdcp22Tx_LogWr.
int XHdcp22Tx_Enable(XHdcp22_Tx *InstancePtr)
This function enables the state machine and acts as a resume.
InstancePtr is a pointer to the XHdcp22Tx core instance. XST_SUCCESS None.
References XHdcp22_Tx::Cipher, XHdcp22_Tx::Info, XHdcp22_Tx_Info::IsEnabled, XHdcp22_Tx::Timer, XHdcp22_Tx_Timer::TmrCtr, XHDCP22_TX_LOG_EVT_ENABLED, XHDCP22_TX_TIMER_CNTR_0, XHdcp22Tx_LogWr.
int XHdcp22Tx_Disable(XHdcp22_Tx *InstancePtr)
This function disables the state machine and acts as a pause.
InstancePtr is a pointer to the XHdcp22Tx core instance. XST_SUCCESS. None.
References XHdcp22_Tx::Cipher, XHdcp22_Tx::Info, XHdcp22_Tx_Info::IsEnabled, XHDCP22_TX_LOG_EVT_ENABLED, XHdcp22Tx_LogWr.
int XHdcp22Tx_EnableEncryption(XHdcp22_Tx *InstancePtr)
This function enables HDMI stream encryption by enabling the cipher.
InstancePtr is a pointer to the XHdcp22Tx core instance. - XST_SUCCESS if authenticated is started successfully. XST_FAIL if the state machine is disabled. None.
References XHdcp22_Tx::Cipher, XHDCP22_TX_LOG_EVT_ENCR_ENABLED, XHdcp22Tx_IsAuthenticated, XHdcp22Tx_LogWr.
int XHdcp22Tx_DisableEncryption(XHdcp22_Tx *InstancePtr)
This function disables HDMI stream encryption by disabling the cipher.
InstancePtr is a pointer to the XHdcp22Tx core instance. XST_SUCCESS. None.
References XHdcp22_Tx::Cipher, XHDCP22_TX_LOG_EVT_ENCR_ENABLED, XHdcp22Tx_LogWr.
Referenced by XHdcp22Tx_Reset.
void XHdcp22Tx_EnableBlank(XHdcp22_Tx *InstancePtr)
This function enables the blank output for the cipher.
InstancePtr is a pointer to the XHdcp22Tx core instance. None.
References XHdcp22_Tx::Cipher.
void XHdcp22Tx_DisableBlank(XHdcp22_Tx *InstancePtr)
This function disables the blank output for the cipher.
InstancePtr is a pointer to the XHdcp22Tx core instance. None.
References XHdcp22_Tx::Cipher.
u8 XHdcp22Tx_IsRepeater(XHdcp22_Tx *InstancePtr)
This function returns the current repeater mode status.
InstancePtr is a pointer to the XHdcp22_Tx instance. TRUE if the HDCP 2.2 instance is part of the downstream port of a repeaterFALSE if the HDCP 2.2 instance is a transmitter
References XHdcp22_Tx::Config, XHdcp22_Tx_Config::Mode, XHDCP22_TX_TRANSMITTER.
Referenced by XHdcp22Tx_Authenticate, XHdcp22Tx_Info.
void XHdcp22Tx_SetRepeater(XHdcp22_Tx *InstancePtr, u8 Set)
This function sets the repeater mode status.
InstancePtr is a pointer to the XHdcp22_Tx instance. Set is TRUE to enable the repeater mode and FALSE to disable.
References XHdcp22_Tx::Config, XHdcp22_Tx_Config::Mode, XHDCP22_TX_REPEATER, XHDCP22_TX_TRANSMITTER.
u8 XHdcp22Tx_IsEnabled(XHdcp22_Tx *InstancePtr)
This function returns the current enabled state.
InstancePtr is a pointer to the XHdcp22Tx core instance. TRUE if enabled otherwise FALSE. None.
References XHdcp22_Tx::Info, XHdcp22_Tx_Info::IsEnabled.
Referenced by XHdcp22Tx_Info.
u8 XHdcp22Tx_IsEncryptionEnabled(XHdcp22_Tx *InstancePtr)
This function returns the current encryption enabled state.
InstancePtr is a pointer to the XHdcp22Tx core instance. TRUE if encryption is enabled otherwise FALSE. None.
References XHdcp22_Tx::Cipher.
Referenced by XHdcp22Tx_Info.
u8 XHdcp22Tx_IsInProgress(XHdcp22_Tx *InstancePtr)
This function returns the current progress state.
InstancePtr is a pointer to the XHdcp22Tx core instance. TRUE if authentication is in progress otherwise FALSE. None.
References XHdcp22_Tx_Info::AuthenticationStatus, XHdcp22_Tx::Info, XHDCP22_TX_UNAUTHENTICATED.
u8 XHdcp22Tx_IsAuthenticated(XHdcp22_Tx *InstancePtr)
This function returns the current authenticated state.
InstancePtr is a pointer to the XHdcp22Tx core instance. TRUE if authenticated otherwise FALSE. None.
References XHdcp22_Tx_Info::AuthenticationStatus, XHdcp22_Tx::Info, XHDCP22_TX_AUTHENTICATED.
Referenced by XHdcp22Tx_EnableEncryption.
u8 XHdcp22Tx_IsDwnstrmCapable(XHdcp22_Tx *InstancePtr)
This function checks if the downstream device HDCP2Version register is set.
InstancePtr is a pointer to the XHdcp22Tx core instance. - TRUE if downstream device is HDCP 2.2 capable. FALSE if downstream device is not HDCP 2.2 capable. None.
References XHdcp22_Tx::DdcHandlerRef, XHdcp22_Tx::DdcRead, XHdcp22_Tx::DdcWrite, XHdcp22_Tx::IsReceiverHDCP2Capable, XHDCP22_TX_DDC_BASE_ADDRESS, XHDCP22_TX_HDCPPORT_VERSION_OFFSET.
int XHdcp22Tx_SetCallback(XHdcp22_Tx *InstancePtr, XHdcp22_Tx_HandlerType HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs callback functions for the given HandlerType:
HandlerType Callback Function Type ------------------------- --------------------------- (XHDCP22_TX_HANDLER_DDC_WRITE) DdcWrite (XHDCP22_TX_HANDLER_DDC_READ) DdcRead (XHDCP22_TX_HANDLER_AUTHENTICATED) AuthenticatedCallback (XHDCP22_TX_HANDLER_UNAUTHENTICATED) UnauthenticatedCallback (XHDCP22_TX_HANDLER_DOWNSTREAM_TOPOLOGY_AVAILABLE) DownstreamTopologyAvailableCallback InstancePtr is a pointer to the HDMI RX core instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XHdcp22_Tx::AuthenticatedCallback, XHdcp22_Tx::DdcHandlerRef, XHdcp22_Tx::DdcRead, XHdcp22_Tx::DdcWrite, XHdcp22_Tx::DownstreamTopologyAvailableCallback, XHdcp22_Tx::IsAuthenticatedCallbackSet, XHdcp22_Tx::IsDdcReadSet, XHdcp22_Tx::IsDdcWriteSet, XHdcp22_Tx::IsDownstreamTopologyAvailableCallbackSet, XHdcp22_Tx::IsUnauthenticatedCallbackSet, XHdcp22_Tx::UnauthenticatedCallback.
XTmrCtr * XHdcp22Tx_GetTimer(XHdcp22_Tx *InstancePtr)
This function returns the pointer to the internal timer control instance needed for connecting the timer interrupt to an interrupt controller.
InstancePtr is a pointer to the XHdcp22Tx core instance. A pointer to the internal timer control instance. None.
References XHdcp22_Tx::Timer, XHdcp22_Tx_Timer::TmrCtr.
void XHdcp22Tx_SetMessagePollingValue(XHdcp22_Tx *InstancePtr, u32 PollingValue)
This function can be used to change the polling value.
The polling value is the amount of time in milliseconds to wait between successive reads of the RxStatus register. The RxStatus register is polled to determine when a message is available for reading during authentication or during the link integrity check phase to determine when to issue re-authentication. The polling value needs to be at most 20ms to account for the locality check. InstancePtr is a pointer to the XHdcp22Tx core instance. PollingValue is the polling interval defined in milliseconds 0 : Always Poll1 : Poll after 1ms2 : Poll after 2ms3 : Poll after 3ms etc... None.
References XHdcp22_Tx::Info, XHdcp22_Tx_Info::PollingValue.
int XHdcp22Tx_ClearPairingInfo(XHdcp22_Tx *InstancePtr)
This function clear the global pairing info structure, so every HDCP2.2 receiver will have to go through the 'no stored km' sequence to authenticate.
InstancePtr is a pointer to the XHdcp22Tx core instance. XST_SUCCESS None.
References XHdcp22_Tx::Info.
Referenced by XHdcp22Tx_CfgInitialize.
void XHdcp22Tx_RevokeReceiverId(XHdcp22_Tx *InstancePtr, u8 *ReceiverIdPtr)
This function adds a ReceiverID to RevocationList.
InstancePtr is a pointer to the XHdcp22Tx core instance. ReceiverIdPtr is a pointer to a 5-byte receiver Id. Supposed to be called by Upstream Content Control Function
References XHdcp22_Tx_Info::AuthenticationStatus, XHdcp22_Tx::Config, XHdcp22_Tx_Info::CurrentState, XHdcp22_Tx::Info, XHdcp22_Tx_Info::IsDeviceRevoked, XHdcp22_Tx_Info::IsRevocationListValid, XHdcp22_Tx_Config::Mode, XHDCP22_TX_DEVICE_IS_REVOKED, XHDCP22_TX_SRM_RCVID_SIZE, XHDCP22_TX_STATE_A0, XHDCP22_TX_TRANSMITTER, XHdcp22Tx_GetRevocationReceiverIdList, XHdcp22Tx_IsDeviceRevoked.
void XHdcp22Tx_LogReset(XHdcp22_Tx *InstancePtr, u8 Verbose)
This function clears the log pointers.
InstancePtr is a pointer to the XHdcp22_Tx core instance. Verbose allows to add debug logging. None.
References XHdcp22_Tx_Log::Head, XHdcp22_Tx::Log, XHdcp22_Tx_Log::Tail, XHdcp22_Tx::Timer, XHdcp22_Tx_Timer::TmrCtr, XHdcp22_Tx_Log::Verbose, XHDCP22_TX_TIMER_CNTR_1.
Referenced by XHdcp22Tx_CfgInitialize.
u32 XHdcp22Tx_LogGetTimeUSecs(XHdcp22_Tx *InstancePtr)
This function returns the time expired since a log reset was called.
InstancePtr is a pointer to the XHdcp22_Tx core instance. The expired logging time in useconds. None.
References XHdcp22_Tx::Timer, XHdcp22_Tx_Timer::TmrCtr, XHDCP22_TX_TIMER_CNTR_1.
Referenced by XHdcp22Tx_LogWr.
void XHdcp22Tx_LogWr(XHdcp22_Tx *InstancePtr, XHdcp22_Tx_LogEvt Evt, u16 Data)
This function writes HDCP TX logs into buffer.
InstancePtr is a pointer to the XHdcp22_Tx core instance. Evt specifies an action to be carried out. Please refer XHdcp22_Tx_LogEvt enum in xhdcp22_tx.h. Data specifies the information that gets written into log buffer. None.
References XHdcp22_Tx_LogItem::Data, XHdcp22_Tx_Log::Head, XHdcp22_Tx::Log, XHdcp22_Tx_LogItem::LogEvent, XHdcp22_Tx_Log::LogItems, XHdcp22_Tx_Log::Tail, XHdcp22_Tx_LogItem::TimeStamp, XHdcp22_Tx_Log::Verbose, XHDCP22_TX_LOG_BUFFER_SIZE, XHDCP22_TX_LOG_EVT_DBG, XHDCP22_TX_LOG_INVALID, XHdcp22Tx_LogGetTimeUSecs.
Referenced by XHdcp22Tx_Disable, XHdcp22Tx_DisableEncryption, XHdcp22Tx_Enable, XHdcp22Tx_EnableEncryption, XHdcp22Tx_Poll, XHdcp22Tx_Reset.
XHdcp22_Tx_LogItem * XHdcp22Tx_LogRd(XHdcp22_Tx *InstancePtr)
This function provides the log information from the log buffer.
InstancePtr is a pointer to the XHdcp22_Tx core instance. Content of log buffer if log pointers are not equal.Otherwise Zero. None.
References XHdcp22_Tx_LogItem::Data, XHdcp22_Tx_Log::Head, XHdcp22_Tx::Log, XHdcp22_Tx_LogItem::LogEvent, XHdcp22_Tx_Log::LogItems, XHdcp22_Tx_Log::Tail, XHdcp22_Tx_LogItem::TimeStamp, XHDCP22_TX_LOG_BUFFER_SIZE, XHDCP22_TX_LOG_EVT_NONE.
Referenced by XHdcp22Tx_LogDisplay.
void XHdcp22Tx_LogDisplay(XHdcp22_Tx *InstancePtr)
This function prints the content of log buffer.
InstancePtr is a pointer to the HDCP22 TX core instance. None.
References XHdcp22_Tx_LogItem::Data, XHdcp22_Tx_LogItem::LogEvent, XHdcp22_Tx_LogItem::TimeStamp, XHDCP22_TX_AKE_NO_STORED_KM, XHDCP22_TX_AUTHENTICATED, XHDCP22_TX_AUTHENTICATION_BUSY, XHDCP22_TX_CASE_TO_STR_PRE, XHDCP22_TX_INCOMPATIBLE_RX, XHDCP22_TX_LOG_EVT_DBG, XHDCP22_TX_LOG_EVT_ENABLED, XHDCP22_TX_LOG_EVT_ENCR_ENABLED, XHDCP22_TX_LOG_EVT_LCCHK_COUNT, XHDCP22_TX_LOG_EVT_NONE, XHDCP22_TX_LOG_EVT_POLL_RESULT, XHDCP22_TX_LOG_EVT_RESET, XHDCP22_TX_LOG_EVT_STATE, XHDCP22_TX_LOG_EVT_STRMMNGCHK_COUNT, XHDCP22_TX_LOG_EVT_TEST_ERROR, XHDCP22_TX_LOG_EVT_USER, XHDCP22_TX_MSG_UNDEFINED, XHDCP22_TX_REAUTHENTICATE_REQUESTED, XHDCP22_TX_SKE_SEND_EKS, XHDCP22_TX_TESTMODE_UNIT, XHDCP22_TX_UNAUTHENTICATED, XHdcp22Tx_LogRd.
void XHdcp22Tx_Info(XHdcp22_Tx *InstancePtr)
This function prints the state machine information.
InstancePtr is a pointer to the HDCP22 TX core instance. None.
References XHdcp22_Tx_Info::AuthenticationStatus, XHdcp22_Tx_Info::AuthRequestCnt, XHdcp22_Tx_Info::ContentStreamType, XHdcp22_Tx_Topology::Depth, XHdcp22_Tx_Topology::DeviceCnt, XHdcp22_Tx_Topology::Hdcp1DeviceDownstream, XHdcp22_Tx_Topology::Hdcp2LegacyDeviceDownstream, XHdcp22_Tx::Info, XHdcp22_Tx_Topology::MaxCascadeExceeded, XHdcp22_Tx_Topology::MaxDevsExceeded, XHdcp22_Tx_Info::PollingValue, XHdcp22_Tx_Info::ReauthRequestCnt, XHdcp22_Tx::Topology, XHDCP22_TX_AUTHENTICATED, XHDCP22_TX_AUTHENTICATION_BUSY, XHDCP22_TX_DEVICE_IS_REVOKED, XHDCP22_TX_INCOMPATIBLE_RX, XHDCP22_TX_NO_SRM_LOADED, XHDCP22_TX_REAUTHENTICATE_REQUESTED, XHDCP22_TX_UNAUTHENTICATED, XHdcp22Tx_IsEnabled, XHdcp22Tx_IsEncryptionEnabled, XHdcp22Tx_IsRepeater.
XHdcp22_Tx_Config * XHdcp22Tx_LookupConfig(UINTPTR BaseAddress)
This function returns a reference to an XHdcp22_Tx_Config structure based on the core id, DeviceId.
The return value will refer to an entry in the device configuration table defined in the xhdcp22_tx_g.c file. DeviceId is the unique core ID of the HDCP2.2 TX core for the lookup operation. XHdcp22Tx_LookupConfig returns a reference to a config record in the configuration table (in xhdcp22_tx_g.c) corresponding to DeviceId, or NULL if no match is found. None.
static int XHdcp22Tx_Mgf1(const u8 *Seed, unsigned int Seedlen, u8 *Mask, unsigned int MaskLen)
This function is the RSA OAEP masking function.
Seed is the masking seed to use. Seedlen is the size of the masking seed . Mask is the output mask. MaskLen is size of the mask. XST_SUCCESS None.
static int XHdcp22Tx_RsaOaepEncrypt(const u8 *KeyPubNPtr, int KeyPubNSize, const u8 *KeyPubEPtr, int KeyEPubSize, const u8 *Message, const u32 MessageLen, const u8 *MaskingSeed, u8 *EncryptedMessage)
This function implements the RSAES-OAEP-Encrypt operation.
The message is encoded using EME-OAEP and then encrypted with the public key using RSAEP.Reference: PKCS#1 v2.1, Section 7.1.1 KeyPubNPtr is the public certificate modulus. KeyPubNSize is the size public certificate modulus. KeyPubEPtr is the public certificate exponent. KeyEPubSize is the public certificate exponent size. Message is the octet string to be encrypted. MessageLen is the length of octet string to be encrypted and must be less than or equal to (nLen - 2*hLen - 2) MaskingSeed is the random octet string seed of length hLen used by EME-OAEP encoding function. XST_SUCCESS or XST_FAILURE. None.
static int XHdcp22Tx_Pkcs1EmeOaepEncode(const u8 *Message, const u32 MessageLen, const u8 *MaskingSeed, u8 *EncodedMessage)
This function implements EME-OAEP encoding.
The label L is the empty string and the underlying hash function is SHA256.Reference: PKCS#1 v2.1, Section 7.1.1, Part 2 Message is the octet string to be encoded MessageLen is the length of the octet string to be encoded. MaskingSeed is the random octet string seed of length hLen. EncodedMessage is the 128 byte encoded octet string. XST_SUCCESS or XST_FAILURE. None.
static int XHdcp22Tx_RsaEncryptMsg(const u8 *KeyPubNPtr, int KeyPubNSize, const u8 *KeyPubEPtr, int KeyPubESize, const u8 *MsgPtr, int MsgSize, u8 *EncryptedMsgPtr)
RSA verification primitive recovers the message representative from the signature representative under the control of a public key.
This is the same as encryption, but it in a totally different context. KeyPubNPtr is the RSA public key modulus part. KeyPubNSize is size of the RSA public key modulus in bytes. KeyPubEPtr is the RSA public key E (exponential) part. KeyEPubSize is the sizeof the RSA public key E (exponential) part in bytes. MsgPtr is the data to verify (for example a cryptographic signature). MsgSize is the size of the data to verify. EncodedMsgPtr is the resulting data for verification. XST_SUCCESS if encryption succeeds.XST_FAILURE if the message buffer size != key size. Note: Verification with a public key is the same as RSA encoding.
static int XHdcp22Tx_RsaSignatureVerify(const u8 *MessagePtr, int MessageSize, const u8 *SignaturePtr, const u8 *KpubDcpNPtr, int KpubDcpNSize, const u8 *KpubDcpEPtr, int KpubDcpESize)
This function implements RSASSA-PKCS1-v1_5-Verify for signature verification.
The encoding scheme used to generate EM is EMSA-PKCS1-v1_5. The signature size is assumed to be 3072 bits. The underlying hash function is SHA256.Reference: PKCS#1 v2.1, Section 8.2.2 and Section 9.2 MessagePtr is a pointer to the start of the message to be hashed. MessageSize is the size of the message to be hashed. SignaturePtr is a pointer to the start of the DCP generated signature. KpubDcpNPtr is a pointer to the N-value of the certificate signature. KpubDcpNSize is the size of the N-value of the certificates signature. KpubDcpEPtr iis a pointer to the E-value of the certificate signature. KpubDcpESize is the size of the E-value of the certificates signature. XST_SUCCESS if the certificate is valid.XST_FAILURE if the certificate is invalid. None.
void XHdcp22Tx_GenerateRandom(XHdcp22_Tx *InstancePtr, int NumOctets, u8 *RandomNumberPtr)
This function generates random octets.
Otherwise it uses offloading from hardware. InstancePtr is a pointer to the XHdcp22_Tx core instance. NumOctets is the number of octets in the random number. RandomNumberPtr is a pointer to the random number. None.
References XHdcp22_Tx::Rng.
int XHdcp22Tx_VerifyCertificate(const XHdcp22_Tx_CertRx *CertificatePtr, const u8 *KpubDcpNPtr, int KpubDcpNSize, const u8 *KpubDcpEPtr, int KpubDcpESize)
This function verifies the HDCP receivers certificate.
CertificatePtr is a pointer to the certificate from the HDCP2.2 receiver. KpubDcpNPtr is a pointer to the N-value of the certificate signature. KpubDcpNSize is the size of the N-value of the certificates signature. KpubDcpEPtr iis a pointer to the E-value of the certificate signature. KpubDcpESize is the size of the E-value of the certificates signature. XST_SUCCESS if the certificate is valid.XST_FAILURE if the certificate is invalid. None.
int XHdcp22Tx_VerifySRM(const u8 *SrmPtr, int SrmSize, const u8 *KpubDcpNPtr, int KpubDcpNSize, const u8 *KpubDcpEPtr, int KpubDcpESize)
This function verifies a HDCP2 system renewability message (SRM) block.
SrmPtr is a pointer to the SRM. SrmSize is the size of the SRM in bytes. KpubDcpNPtr is a pointer to the N-value of the DCP LLC key. KpubDcpNSize is the size of the N-value of the DCP LLC key. KpubDcpEPtr iis a pointer to the E-value of the DCP LLC key. KpubDcpESize is the size of the E-value of the DCP LLC key. XST_SUCCESS if the SRM block is valid.XST_FAILURE if the SRM block is invalid. None.
References XHDCP22_TX_SRM_SIGNATURE_SIZE.
Referenced by XHdcp22Tx_LoadRevocationTable.
void XHdcp22Tx_ComputeHPrime(const u8 *Rrx, const u8 *RxCaps, const u8 *Rtx, const u8 *TxCaps, const u8 *Km, u8 *HPrime)
This function computes HPrime.
Rrx is the Rx random generated value on start of authentication. RxCaps are the capabilities of the receiver. Rtx is the Tx random generated value start of authentication. TxCaps are the capabilities of the receiver. Km is the master key generated by tx. HPrime is a pointer to the HPrime hash from the HDCP2.2 receiver. None.
References XHDCP22_TX_AES128_SIZE, XHDCP22_TX_RRX_SIZE, XHDCP22_TX_RTX_SIZE, XHDCP22_TX_RXCAPS_SIZE, XHDCP22_TX_TXCAPS_SIZE.
void XHdcp22Tx_ComputeEdkeyKs(const u8 *Rn, const u8 *Km, const u8 *Ks, const u8 *Rrx, const u8 *Rtx, u8 *EdkeyKs)
This function computes EdkeyKs.
Kd is calculated as in XHdcp22Tx_ComputeHPrime, but could also be stored the first time. This could save some computing time. According protocol however, only Rrx and Rtx are supposed to be stored. Rn is a pseudo-random nonce. Km is the master key generated by tx.. See also XHdcp22Tx_ComputeHPrime Ks is the session key. Rrx is the random value generated by rx. Rtx is the random value generated by tx. EdkeyKs is the encrypted Ks output. None.
References XHDCP22_TX_AES128_SIZE, XHDCP22_TX_EDKEY_KS_SIZE, XHDCP22_TX_KS_SIZE, XHDCP22_TX_RN_SIZE, XHDCP22_TX_RRX_SIZE, XHDCP22_TX_RTX_SIZE, XHdcp22Tx_MemXor.
void XHdcp22Tx_ComputeLPrime(const u8 *Rn, const u8 *Km, const u8 *Rrx, const u8 *Rtx, u8 *LPrime)
This function computes LPrime.
Kd is calculated as in XHdcp22Tx_ComputeHPrime, but could also be stored the first time. This could save some computing time. According protocol however, only Rrx and Rtx are supposed to be stored. Rn is a pseudo-random nonce. Km is the master key generated by tx and previouslyd stored. Rrx is the random value generated by rx. Rtx is the random value generated by tx. LPrime is a pointer to the computed LPrime hash. None.
References XHDCP22_TX_AES128_SIZE, XHDCP22_TX_RN_SIZE, XHDCP22_TX_RRX_SIZE, XHDCP22_TX_RTX_SIZE, XHDCP22_TX_SHA256_HASH_SIZE, XHdcp22Tx_MemXor.
void XHdcp22Tx_ComputeV(const u8 *Rn, const u8 *Rrx, const u8 *RxInfo, const u8 *Rtx, const u8 *RecvIDList, const u8 RecvIDCount, const u8 *SeqNum_V, const u8 *Km, u8 *V)
void XHdcp22Tx_ComputeM(const u8 *Rn, const u8 *Rrx, const u8 *Rtx, const u8 *StreamIDType, const u8 *k, const u8 *SeqNum_M, const u8 *Km, u8 *M)
Computes the M hash value for HDCP 2.2 authentication.
This function calculates the M parameter used in the HDCP 2.2 protocol by processing the input parameters through a cryptographic hash function. Rn Pointer to the Rn random number. Rrx Pointer to the Rrx receiver random number. Rtx Pointer to the Rtx transmitter random number. StreamIDType Pointer to the Stream ID Type value. k Pointer to the k parameter. SeqNum_M Pointer to the sequence number for M. Km Pointer to the Km master key. M Pointer to the output buffer where computed M hash will be stored.. The caller must ensure all input pointers are valid and point to buffers of appropriate size. The output buffer M must be pre-allocated with sufficient size to store the computed hash value.
References XHDCP22_TX_AES128_SIZE, XHDCP22_TX_RCVID_SIZE, XHDCP22_TX_REPEATER_MAX_DEVICE_COUNT, XHDCP22_TX_RRX_SIZE, XHDCP22_TX_RTX_SIZE, XHDCP22_TX_RXINFO_SIZE, XHDCP22_TX_SEQ_NUM_M_SIZE, XHDCP22_TX_SHA256_HASH_SIZE, XHDCP22_TX_STREAMID_TYPE_SIZE.
int XHdcp22Tx_EncryptKm(const XHdcp22_Tx_CertRx *CertificatePtr, const u8 *KmPtr, u8 *MaskingSeedPtr, u8 *EncryptedKmPtr)
This function encrypts the Km value with the receivers public key into Ekh(Km)
CertificatePtr is a pointer to the certificate from the HDCP2.2 receiver. KmPtr is the random master key. MaskingSeedPtr is a pointer to a 32 byte seed for masking in the MGF1 function used in RSA-OEAP encryption. EncryptedKmPtr output of the encryption with a 128 byte (1024 bit) size. XST_SUCCESS if encryption succeeded.XST_FAILURE if encryption failed. None.
References XHDCP22_TX_CERT_PUB_KEY_E_SIZE, XHDCP22_TX_CERT_PUB_KEY_N_SIZE.
void XHdcp22Tx_MemXor(u8 *Output, const u8 *InputA, const u8 *InputB, unsigned int Size)
This function calculates a XOR on a array.
Output is the XOR of the input arrays. InputA is a input array. InputB is a input array. Size is the size of the buffers to XOR. None.
Referenced by XHdcp22Tx_ComputeEdkeyKs, XHdcp22Tx_ComputeLPrime.
void XHdcp22Tx_Dump(const char *string, const u8 *m, u32 mlen)
void XHdcp22Tx_LogWrNoInst(XHdcp22_Tx_LogEvt Evt, u16 Data)
XHDCP22_TX_INVALID_RXSTATUS
RxStatus value used to force re-authentication.
XHDCP22_TX_CASE_TO_STR_PRE
Case replacement to copy a case Id to a string with a pre-lead.
Referenced by XHdcp22Tx_LogDisplay.
XHDCP22_TX_H
prevent circular inclusions by using protection macros
XHDCP22_TX_DEFAULT_RX_STATUS_POLLVALUE
This value is the default polling interval defined in milliseconds.
The polling interval defines the amount of time to wait between successive reads of the RxStatus register.
Referenced by XHdcp22Tx_CfgInitialize.
XHDCP22_TX_MAX_MESSAGE_SIZE
Needed storage to transmit/receive messages to the HDCP2.2 receiver This includes 1 extra byte for the DDC address used.
XHDCP22_TX_REVOCATION_LIST_MAX_DEVICES
Needed storage for the Device IDs in the revocation list.
Referenced by XHdcp22Tx_LoadRevocationTable.
XHDCP22_TX_MAX_STORED_PAIRINGINFO
The list of maximum pairing info items to store.
XHDCP22_TX_LOG_BUFFER_SIZE
The size of the log buffer.
Referenced by XHdcp22Tx_LogRd, XHdcp22Tx_LogWr.
BD_MAX_MOD_SIZE
Size RSA encryption parameters to support 384 byte maximum modulus size.
XHDCP22_TX_I_H
prevent circular inclusions by using protection macros.
XHDCP22_TX_MAX_ALLOWED_LOCALITY_CHECKS
Maximum allowed re-checking locality, prescribed by LLC.
XHDCP22_TX_MAX_ALLOWED_STREAM_MANAGE_CHECKS
Maximum allowed re-checking content stream management.
XHDCP22_TX_LC128_SIZE
Lc128 global constant size.
Referenced by XHdcp22Tx_LoadLc128.
XHDCP22_TX_RCVID_SIZE
Unique receiver Id size in bytes.
Referenced by XHdcp22Tx_ComputeM.
XHDCP22_TX_REPEATER_MAX_DEVICE_COUNT
Max number of downstream devices allowed.
Referenced by XHdcp22Tx_ComputeM.
XHDCP22_TX_REPEATER_MAX_CASCADE_DEPTH
Max cascade depth.
XHDCP22_TX_MSG_UNDEFINED
Undefined.
Referenced by XHdcp22Tx_LogDisplay.
XHDCP22_TX_AKE_INIT
AKE Init message.
XHDCP22_TX_AKE_INIT_SIZE
AKE Init message size.
XHDCP22_TX_AKE_SEND_CERT
AKE Send Certificate message.
XHDCP22_TX_AKE_SEND_CERT_SIZE
AKE Send Certificate message size.
XHDCP22_TX_AKE_NO_STORED_KM
AKE No Stored Km message.
Referenced by XHdcp22Tx_LogDisplay.
XHDCP22_TX_AKE_NO_STORED_KM_SIZE
AKE No Stored Km message size.
XHDCP22_TX_AKE_STORED_KM
AKE Stored Km message size.
XHDCP22_TX_AKE_STORED_KM_SIZE
AKE Stored Km message size.
XHDCP22_TX_AKE_SEND_H_PRIME
AKE H' message.
XHDCP22_TX_AKE_SEND_H_PRIME_SIZE
AKE H' message size.
XHDCP22_TX_AKE_SEND_PAIRING_INFO
AKE Pairing info message.
XHDCP22_TX_AKE_SEND_PAIRING_INFO_SIZE
AKE Pairing info message size.
XHDCP22_TX_LC_INIT
LC Init message.
XHDCP22_TX_LC_INIT_SIZE
LC Init message size.
XHDCP22_TX_LC_SEND_L_PRIME
Send L' message.
XHDCP22_TX_LC_SEND_L_PRIME_SIZE
Send L' message size.
XHDCP22_TX_SKE_SEND_EKS
Send Eks message.
Referenced by XHdcp22Tx_LogDisplay.
XHDCP22_TX_SKE_SEND_EKS_SIZE
Send Eks message size.
XHDCP22_TX_REPEATAUTH_SEND_RECVID_LIST
Repeater Auth send receiver ID list message.
XHDCP22_TX_REPEATAUTH_SEND_RECVID_LIST_SIZE
Repeater Auth send receiver ID list maximum message size.
XHDCP22_TX_REPEATAUTH_SEND_ACK
RepeaterAuth send ack message.
XHDCP22_TX_REPEATAUTH_SEND_ACK_SIZE
RepeaterAuth send ack message size in bytes.
XHDCP22_TX_REPEATAUTH_STREAM_MANAGE
RepeaterAuth stream manage message.
XHDCP22_TX_REPEATAUTH_STREAM_MANAGE_SIZE
RepeaterAuth stream manage message size in bytes.
XHDCP22_TX_REPEATAUTH_STREAM_READY
RepeaterAuth stream ready message.
XHDCP22_TX_REPEATAUTH_STREAM_READY_SIZE
RepeaterAuth stream ready message size in bytes.
XHDCP22_TX_TS_UNDEFINED
Reason why the timer was started: Undefined.
Referenced by XHdcp22Tx_CfgInitialize.
XHDCP22_TX_TS_WAIT_FOR_STREAM_TYPE
Reason why the timer was started: Waiting for Content Stream Type to be set when in repeater mode.
: The message ids also double as a reason identifier. Thus, the value of this define should NOT overlap a message Id.
XHDCP22_TX_TS_WAIT_FOR_CIPHER
Reason why the timer was started: Mandatory wait of 200 ms before the cipher may be activated.
Authenticated flag is only set after this period has expired. : The message ids also double as a reason identifier. Thus, the value of this define should NOT overlap a message Id.
XHDCP22_TX_TS_RX_REAUTH_CHECK
Reason why the timer was started: Status checking.
: The message ids also double as a reason identifier. Thus, the value of this define should NOT overlap a message Id.
XHDCP22_TX_TIMER_CNTR_0
Internal used timer counter for timeout checking.
Referenced by XHdcp22Tx_Enable, XHdcp22Tx_Reset.
XHDCP22_TX_TIMER_CNTR_1
Internal used timer counter for logging.
Referenced by XHdcp22Tx_LogGetTimeUSecs, XHdcp22Tx_LogReset.
XHDCP22_TX_HDCPPORT_VERSION_OFFSET
DDC version offset.
Referenced by XHdcp22Tx_IsDwnstrmCapable.
XHDCP22_TX_HDCPPORT_WRITE_MSG_OFFSET
DDC write message buffer offset.
XHDCP22_TX_HDCPPORT_RXSTATUS_OFFSET
DDC RX status offset.
XHDCP22_TX_HDCPPORT_READ_MSG_OFFSET
DDC read message buffer offset.
XHDCP22_TX_RXSTATUS_REAUTH_REQ_MASK
HDCP Port DDC Rx status register masks.
RX status REAUTHENTICATION bit.
XHDCP22_TX_RXSTATUS_READY_MASK
RX status READY bit.
XHDCP22_TX_RXSTATUS_AVAIL_BYTES_MASK
RX status available bytes in read message buffer.
XHDCP22_TX_CERT_RCVID_SIZE
RX certificate and Tx public key sizes in bytes.
Unique receiver Id size in the RX certificate.
XHDCP22_TX_CERT_PUB_KEY_N_SIZE
Public key-N size in the RX certificate.
Referenced by XHdcp22Tx_EncryptKm.
XHDCP22_TX_CERT_PUB_KEY_E_SIZE
Public key-E size in the RX certificate.
Referenced by XHdcp22Tx_EncryptKm.
XHDCP22_TX_CERT_RSVD_SIZE
Reserved size in the RX certificate.
XHDCP22_TX_CERT_SIGNATURE_SIZE
Signature size in the RX certificate.
XHDCP22_TX_CERT_SIZE
Total size of the RX certificate.
XHDCP22_TX_RXCAPS_SIZE
RX capabilities size.
Referenced by XHdcp22Tx_ComputeHPrime.
XHDCP22_TX_TXCAPS_SIZE
TX capabilities size.
Referenced by XHdcp22Tx_ComputeHPrime.
XHDCP22_TX_KPUB_DCP_LLC_N_SIZE
LLC public key-N size.
Referenced by XHdcp22Tx_LoadRevocationTable.
XHDCP22_TX_KPUB_DCP_LLC_E_SIZE
LLC public key-E size.
Referenced by XHdcp22Tx_LoadRevocationTable.
XHDCP22_TX_SHA256_HASH_SIZE
SHA256 hash size in bytes.
Referenced by XHdcp22Tx_ComputeLPrime, XHdcp22Tx_ComputeM.
XHDCP22_TX_AES128_SIZE
AES128 keys in bytes.
Referenced by XHdcp22Tx_ComputeEdkeyKs, XHdcp22Tx_ComputeHPrime, XHdcp22Tx_ComputeLPrime, XHdcp22Tx_ComputeM.
XHDCP22_TX_RTX_SIZE
64 bits.
Referenced by XHdcp22Tx_ComputeEdkeyKs, XHdcp22Tx_ComputeHPrime, XHdcp22Tx_ComputeLPrime, XHdcp22Tx_ComputeM.
XHDCP22_TX_RRX_SIZE
64 bits.
Referenced by XHdcp22Tx_ComputeEdkeyKs, XHdcp22Tx_ComputeHPrime, XHdcp22Tx_ComputeLPrime, XHdcp22Tx_ComputeM.
XHDCP22_TX_KM_SIZE
XHDCP22_TX_E_KPUB_KM_SIZE
1024 bits.
XHDCP22_TX_H_PRIME_SIZE
256 bits.
XHDCP22_TX_EKH_KM_SIZE
128 bits.
XHDCP22_TX_KM_MSK_SEED_SIZE
XHDCP22_TX_RN_SIZE
64-bits.
Referenced by XHdcp22Tx_ComputeEdkeyKs, XHdcp22Tx_ComputeLPrime.
XHDCP22_TX_RIV_SIZE
64-bits.
XHDCP22_TX_L_PRIME_SIZE
256 bits.
XHDCP22_TX_KS_SIZE
128 bits.
Referenced by XHdcp22Tx_ComputeEdkeyKs.
XHDCP22_TX_EDKEY_KS_SIZE
128 bits.
Referenced by XHdcp22Tx_ComputeEdkeyKs.
XHDCP22_TX_SRM_RCVID_SIZE
Receiver Id size in the SRM block.
Referenced by XHdcp22Tx_IsDeviceRevoked, XHdcp22Tx_LoadRevocationTable, XHdcp22Tx_RevokeReceiverId.
XHDCP22_TX_SRM_SIGNATURE_SIZE
Signature size in the SRM block.
Referenced by XHdcp22Tx_VerifySRM.
XHDCP22_TX_RXINFO_SIZE
RxInfo size in bytes.
Referenced by XHdcp22Tx_ComputeM.
XHDCP22_TX_SEQ_NUM_V_SIZE
Seq_num_v size in bytes.
XHDCP22_TX_V_SIZE
V size in bytes.
XHDCP22_TX_V_PRIME_SIZE
VPrime size in bytes.
XHDCP22_TX_SEQ_NUM_M_SIZE
Seq_num_m size in bytes.
Referenced by XHdcp22Tx_ComputeM.
XHDCP22_TX_K_SIZE
K size in bytes.
XHDCP22_TX_STREAMID_TYPE_SIZE
Stream ID and Type size in bytes.
Referenced by XHdcp22Tx_ComputeM.
XHDCP22_TX_M_PRIME_SIZE
MPrime size in bytes.
XHDCP22_TX_TEST_CERT_RX
Use a certificate test vector.
XHDCP22_TX_TEST_H1
Use a H_Prime test vector.
XHDCP22_TX_TEST_L1
Use a L_Prime test vector.
XHDCP22_TX_TEST_EKH_KM
Use a pairing info Ekh(Km) test vector, use i.c.w XHDCP22_TX_TEST_RCV_TIMEOUT.
XHDCP22_TX_TEST_INVALID_VALUE
Invalidate a value.
XHDCP22_TX_TEST_RCV_TIMEOUT
Timeout on a received message.
XHDCP22_TX_TEST_V1
Use a V_Prime test vector.
XHDCP22_TX_TEST_M1
Use a M_Prime test vector.
XHDCP22_TX_TEST_STORED_KM
AKE is forced using a stored Km scenario.
Pairing info is pre-loaded with test vectors that forces Stored Km scenario.
XHDCP22_TX_TEST_NO_TIMEOUT
Disable timeout checking.
this is mainly used to check the HDCP RX core in loopback mode in case it cannot meet timing requirements (no offloading to hardware) and reponsetimes need to be logged.
XHDCP22_TX_TEST_CLR_PAIRINGINFO
Pairing info is cleared, to force a non-stored Km scenario.
XHDCP22_TX_TEST_USE_TEST_VECTOR_R1
Use testvectors for receiver R1.
XHDCP22_TX_DDC_BASE_ADDRESS
DDC base address (0x74 >> 1)
Referenced by XHdcp22Tx_IsDwnstrmCapable.
XPAR_XHDCP22_TX_NUM_INSTANCES