xhdcp22_tx_crypt.c
BD_MAX_MOD_SIZE
Size RSA encryption parameters to support 384 byte maximum modulus size.
static int XHdcp22Tx_Mgf1(const u8 *Seed, unsigned int Seedlen, u8 *Mask, unsigned int MaskLen)
This function is the RSA OAEP masking function.
Seed is the masking seed to use. Seedlen is the size of the masking seed . Mask is the output mask. MaskLen is size of the mask. XST_SUCCESS None.
static int XHdcp22Tx_RsaOaepEncrypt(const u8 *KeyPubNPtr, int KeyPubNSize, const u8 *KeyPubEPtr, int KeyEPubSize, const u8 *Message, const u32 MessageLen, const u8 *MaskingSeed, u8 *EncryptedMessage)
This function implements the RSAES-OAEP-Encrypt operation.
The message is encoded using EME-OAEP and then encrypted with the public key using RSAEP.Reference: PKCS#1 v2.1, Section 7.1.1 KeyPubNPtr is the public certificate modulus. KeyPubNSize is the size public certificate modulus. KeyPubEPtr is the public certificate exponent. KeyEPubSize is the public certificate exponent size. Message is the octet string to be encrypted. MessageLen is the length of octet string to be encrypted and must be less than or equal to (nLen - 2*hLen - 2) MaskingSeed is the random octet string seed of length hLen used by EME-OAEP encoding function. XST_SUCCESS or XST_FAILURE. None.
static int XHdcp22Tx_Pkcs1EmeOaepEncode(const u8 *Message, const u32 MessageLen, const u8 *MaskingSeed, u8 *EncodedMessage)
This function implements EME-OAEP encoding.
The label L is the empty string and the underlying hash function is SHA256.Reference: PKCS#1 v2.1, Section 7.1.1, Part 2 Message is the octet string to be encoded MessageLen is the length of the octet string to be encoded. MaskingSeed is the random octet string seed of length hLen. EncodedMessage is the 128 byte encoded octet string. XST_SUCCESS or XST_FAILURE. None.
static int XHdcp22Tx_RsaEncryptMsg(const u8 *KeyPubNPtr, int KeyPubNSize, const u8 *KeyPubEPtr, int KeyPubESize, const u8 *MsgPtr, int MsgSize, u8 *EncryptedMsgPtr)
RSA verification primitive recovers the message representative from the signature representative under the control of a public key.
This is the same as encryption, but it in a totally different context. KeyPubNPtr is the RSA public key modulus part. KeyPubNSize is size of the RSA public key modulus in bytes. KeyPubEPtr is the RSA public key E (exponential) part. KeyEPubSize is the sizeof the RSA public key E (exponential) part in bytes. MsgPtr is the data to verify (for example a cryptographic signature). MsgSize is the size of the data to verify. EncodedMsgPtr is the resulting data for verification. XST_SUCCESS if encryption succeeds.XST_FAILURE if the message buffer size != key size. Note: Verification with a public key is the same as RSA encoding.
static int XHdcp22Tx_RsaSignatureVerify(const u8 *MessagePtr, int MessageSize, const u8 *SignaturePtr, const u8 *KpubDcpNPtr, int KpubDcpNSize, const u8 *KpubDcpEPtr, int KpubDcpESize)
This function implements RSASSA-PKCS1-v1_5-Verify for signature verification.
The encoding scheme used to generate EM is EMSA-PKCS1-v1_5. The signature size is assumed to be 3072 bits. The underlying hash function is SHA256.Reference: PKCS#1 v2.1, Section 8.2.2 and Section 9.2 MessagePtr is a pointer to the start of the message to be hashed. MessageSize is the size of the message to be hashed. SignaturePtr is a pointer to the start of the DCP generated signature. KpubDcpNPtr is a pointer to the N-value of the certificate signature. KpubDcpNSize is the size of the N-value of the certificates signature. KpubDcpEPtr iis a pointer to the E-value of the certificate signature. KpubDcpESize is the size of the E-value of the certificates signature. XST_SUCCESS if the certificate is valid.XST_FAILURE if the certificate is invalid. None.
void XHdcp22Tx_GenerateRandom(XHdcp22_Tx *InstancePtr, int NumOctets, u8 *RandomNumberPtr)
This function generates random octets.
Otherwise it uses offloading from hardware. InstancePtr is a pointer to the XHdcp22_Tx core instance. NumOctets is the number of octets in the random number. RandomNumberPtr is a pointer to the random number. None.
References XHdcp22_Tx::Rng.
int XHdcp22Tx_VerifyCertificate(const XHdcp22_Tx_CertRx *CertificatePtr, const u8 *KpubDcpNPtr, int KpubDcpNSize, const u8 *KpubDcpEPtr, int KpubDcpESize)
This function verifies the HDCP receivers certificate.
CertificatePtr is a pointer to the certificate from the HDCP2.2 receiver. KpubDcpNPtr is a pointer to the N-value of the certificate signature. KpubDcpNSize is the size of the N-value of the certificates signature. KpubDcpEPtr iis a pointer to the E-value of the certificate signature. KpubDcpESize is the size of the E-value of the certificates signature. XST_SUCCESS if the certificate is valid.XST_FAILURE if the certificate is invalid. None.
int XHdcp22Tx_VerifySRM(const u8 *SrmPtr, int SrmSize, const u8 *KpubDcpNPtr, int KpubDcpNSize, const u8 *KpubDcpEPtr, int KpubDcpESize)
This function verifies a HDCP2 system renewability message (SRM) block.
SrmPtr is a pointer to the SRM. SrmSize is the size of the SRM in bytes. KpubDcpNPtr is a pointer to the N-value of the DCP LLC key. KpubDcpNSize is the size of the N-value of the DCP LLC key. KpubDcpEPtr iis a pointer to the E-value of the DCP LLC key. KpubDcpESize is the size of the E-value of the DCP LLC key. XST_SUCCESS if the SRM block is valid.XST_FAILURE if the SRM block is invalid. None.
References XHDCP22_TX_SRM_SIGNATURE_SIZE.
Referenced by XHdcp22Tx_LoadRevocationTable.
void XHdcp22Tx_ComputeHPrime(const u8 *Rrx, const u8 *RxCaps, const u8 *Rtx, const u8 *TxCaps, const u8 *Km, u8 *HPrime)
This function computes HPrime.
Rrx is the Rx random generated value on start of authentication. RxCaps are the capabilities of the receiver. Rtx is the Tx random generated value start of authentication. TxCaps are the capabilities of the receiver. Km is the master key generated by tx. HPrime is a pointer to the HPrime hash from the HDCP2.2 receiver. None.
References XHDCP22_TX_AES128_SIZE, XHDCP22_TX_RRX_SIZE, XHDCP22_TX_RTX_SIZE, XHDCP22_TX_RXCAPS_SIZE, XHDCP22_TX_TXCAPS_SIZE.
void XHdcp22Tx_ComputeEdkeyKs(const u8 *Rn, const u8 *Km, const u8 *Ks, const u8 *Rrx, const u8 *Rtx, u8 *EdkeyKs)
This function computes EdkeyKs.
Kd is calculated as in XHdcp22Tx_ComputeHPrime, but could also be stored the first time. This could save some computing time. According protocol however, only Rrx and Rtx are supposed to be stored. Rn is a pseudo-random nonce. Km is the master key generated by tx.. See also XHdcp22Tx_ComputeHPrime Ks is the session key. Rrx is the random value generated by rx. Rtx is the random value generated by tx. EdkeyKs is the encrypted Ks output. None.
References XHDCP22_TX_AES128_SIZE, XHDCP22_TX_EDKEY_KS_SIZE, XHDCP22_TX_KS_SIZE, XHDCP22_TX_RN_SIZE, XHDCP22_TX_RRX_SIZE, XHDCP22_TX_RTX_SIZE, XHdcp22Tx_MemXor.
void XHdcp22Tx_ComputeLPrime(const u8 *Rn, const u8 *Km, const u8 *Rrx, const u8 *Rtx, u8 *LPrime)
This function computes LPrime.
Kd is calculated as in XHdcp22Tx_ComputeHPrime, but could also be stored the first time. This could save some computing time. According protocol however, only Rrx and Rtx are supposed to be stored. Rn is a pseudo-random nonce. Km is the master key generated by tx and previouslyd stored. Rrx is the random value generated by rx. Rtx is the random value generated by tx. LPrime is a pointer to the computed LPrime hash. None.
References XHDCP22_TX_AES128_SIZE, XHDCP22_TX_RN_SIZE, XHDCP22_TX_RRX_SIZE, XHDCP22_TX_RTX_SIZE, XHDCP22_TX_SHA256_HASH_SIZE, XHdcp22Tx_MemXor.
void XHdcp22Tx_ComputeV(const u8 *Rn, const u8 *Rrx, const u8 *RxInfo, const u8 *Rtx, const u8 *RecvIDList, const u8 RecvIDCount, const u8 *SeqNum_V, const u8 *Km, u8 *V)
void XHdcp22Tx_ComputeM(const u8 *Rn, const u8 *Rrx, const u8 *Rtx, const u8 *StreamIDType, const u8 *k, const u8 *SeqNum_M, const u8 *Km, u8 *M)
Computes the M hash value for HDCP 2.2 authentication.
This function calculates the M parameter used in the HDCP 2.2 protocol by processing the input parameters through a cryptographic hash function. Rn Pointer to the Rn random number. Rrx Pointer to the Rrx receiver random number. Rtx Pointer to the Rtx transmitter random number. StreamIDType Pointer to the Stream ID Type value. k Pointer to the k parameter. SeqNum_M Pointer to the sequence number for M. Km Pointer to the Km master key. M Pointer to the output buffer where computed M hash will be stored.. The caller must ensure all input pointers are valid and point to buffers of appropriate size. The output buffer M must be pre-allocated with sufficient size to store the computed hash value.
References XHDCP22_TX_AES128_SIZE, XHDCP22_TX_RCVID_SIZE, XHDCP22_TX_REPEATER_MAX_DEVICE_COUNT, XHDCP22_TX_RRX_SIZE, XHDCP22_TX_RTX_SIZE, XHDCP22_TX_RXINFO_SIZE, XHDCP22_TX_SEQ_NUM_M_SIZE, XHDCP22_TX_SHA256_HASH_SIZE, XHDCP22_TX_STREAMID_TYPE_SIZE.
int XHdcp22Tx_EncryptKm(const XHdcp22_Tx_CertRx *CertificatePtr, const u8 *KmPtr, u8 *MaskingSeedPtr, u8 *EncryptedKmPtr)
This function encrypts the Km value with the receivers public key into Ekh(Km)
CertificatePtr is a pointer to the certificate from the HDCP2.2 receiver. KmPtr is the random master key. MaskingSeedPtr is a pointer to a 32 byte seed for masking in the MGF1 function used in RSA-OEAP encryption. EncryptedKmPtr output of the encryption with a 128 byte (1024 bit) size. XST_SUCCESS if encryption succeeded.XST_FAILURE if encryption failed. None.
References XHDCP22_TX_CERT_PUB_KEY_E_SIZE, XHDCP22_TX_CERT_PUB_KEY_N_SIZE.
void XHdcp22Tx_MemXor(u8 *Output, const u8 *InputA, const u8 *InputB, unsigned int Size)
This function calculates a XOR on a array.
Output is the XOR of the input arrays. InputA is a input array. InputB is a input array. Size is the size of the buffers to XOR. None.
Referenced by XHdcp22Tx_ComputeEdkeyKs, XHdcp22Tx_ComputeLPrime.