xhdcp22_tx_i.h
XHDCP22_TX_I_H
prevent circular inclusions by using protection macros.
XHDCP22_TX_MAX_ALLOWED_LOCALITY_CHECKS
Maximum allowed re-checking locality, prescribed by LLC.
XHDCP22_TX_MAX_ALLOWED_STREAM_MANAGE_CHECKS
Maximum allowed re-checking content stream management.
XHDCP22_TX_LC128_SIZE
Lc128 global constant size.
Referenced by XHdcp22Tx_LoadLc128.
XHDCP22_TX_RCVID_SIZE
Unique receiver Id size in bytes.
Referenced by XHdcp22Tx_ComputeM.
XHDCP22_TX_REPEATER_MAX_DEVICE_COUNT
Max number of downstream devices allowed.
Referenced by XHdcp22Tx_ComputeM.
XHDCP22_TX_REPEATER_MAX_CASCADE_DEPTH
Max cascade depth.
XHDCP22_TX_MSG_UNDEFINED
Undefined.
Referenced by XHdcp22Tx_LogDisplay.
XHDCP22_TX_AKE_INIT
AKE Init message.
XHDCP22_TX_AKE_INIT_SIZE
AKE Init message size.
XHDCP22_TX_AKE_SEND_CERT
AKE Send Certificate message.
XHDCP22_TX_AKE_SEND_CERT_SIZE
AKE Send Certificate message size.
XHDCP22_TX_AKE_NO_STORED_KM
AKE No Stored Km message.
Referenced by XHdcp22Tx_LogDisplay.
XHDCP22_TX_AKE_NO_STORED_KM_SIZE
AKE No Stored Km message size.
XHDCP22_TX_AKE_STORED_KM
AKE Stored Km message size.
XHDCP22_TX_AKE_STORED_KM_SIZE
AKE Stored Km message size.
XHDCP22_TX_AKE_SEND_H_PRIME
AKE H' message.
XHDCP22_TX_AKE_SEND_H_PRIME_SIZE
AKE H' message size.
XHDCP22_TX_AKE_SEND_PAIRING_INFO
AKE Pairing info message.
XHDCP22_TX_AKE_SEND_PAIRING_INFO_SIZE
AKE Pairing info message size.
XHDCP22_TX_LC_INIT
LC Init message.
XHDCP22_TX_LC_INIT_SIZE
LC Init message size.
XHDCP22_TX_LC_SEND_L_PRIME
Send L' message.
XHDCP22_TX_LC_SEND_L_PRIME_SIZE
Send L' message size.
XHDCP22_TX_SKE_SEND_EKS
Send Eks message.
Referenced by XHdcp22Tx_LogDisplay.
XHDCP22_TX_SKE_SEND_EKS_SIZE
Send Eks message size.
XHDCP22_TX_REPEATAUTH_SEND_RECVID_LIST
Repeater Auth send receiver ID list message.
XHDCP22_TX_REPEATAUTH_SEND_RECVID_LIST_SIZE
Repeater Auth send receiver ID list maximum message size.
XHDCP22_TX_REPEATAUTH_SEND_ACK
RepeaterAuth send ack message.
XHDCP22_TX_REPEATAUTH_SEND_ACK_SIZE
RepeaterAuth send ack message size in bytes.
XHDCP22_TX_REPEATAUTH_STREAM_MANAGE
RepeaterAuth stream manage message.
XHDCP22_TX_REPEATAUTH_STREAM_MANAGE_SIZE
RepeaterAuth stream manage message size in bytes.
XHDCP22_TX_REPEATAUTH_STREAM_READY
RepeaterAuth stream ready message.
XHDCP22_TX_REPEATAUTH_STREAM_READY_SIZE
RepeaterAuth stream ready message size in bytes.
XHDCP22_TX_TS_UNDEFINED
Reason why the timer was started: Undefined.
Referenced by XHdcp22Tx_CfgInitialize.
XHDCP22_TX_TS_WAIT_FOR_STREAM_TYPE
Reason why the timer was started: Waiting for Content Stream Type to be set when in repeater mode.
: The message ids also double as a reason identifier. Thus, the value of this define should NOT overlap a message Id.
XHDCP22_TX_TS_WAIT_FOR_CIPHER
Reason why the timer was started: Mandatory wait of 200 ms before the cipher may be activated.
Authenticated flag is only set after this period has expired. : The message ids also double as a reason identifier. Thus, the value of this define should NOT overlap a message Id.
XHDCP22_TX_TS_RX_REAUTH_CHECK
Reason why the timer was started: Status checking.
: The message ids also double as a reason identifier. Thus, the value of this define should NOT overlap a message Id.
XHDCP22_TX_TIMER_CNTR_0
Internal used timer counter for timeout checking.
Referenced by XHdcp22Tx_Enable, XHdcp22Tx_Reset.
XHDCP22_TX_TIMER_CNTR_1
Internal used timer counter for logging.
Referenced by XHdcp22Tx_LogGetTimeUSecs, XHdcp22Tx_LogReset.
XHDCP22_TX_HDCPPORT_VERSION_OFFSET
DDC version offset.
Referenced by XHdcp22Tx_IsDwnstrmCapable.
XHDCP22_TX_HDCPPORT_WRITE_MSG_OFFSET
DDC write message buffer offset.
XHDCP22_TX_HDCPPORT_RXSTATUS_OFFSET
DDC RX status offset.
XHDCP22_TX_HDCPPORT_READ_MSG_OFFSET
DDC read message buffer offset.
XHDCP22_TX_RXSTATUS_REAUTH_REQ_MASK
HDCP Port DDC Rx status register masks.
RX status REAUTHENTICATION bit.
XHDCP22_TX_RXSTATUS_READY_MASK
RX status READY bit.
XHDCP22_TX_RXSTATUS_AVAIL_BYTES_MASK
RX status available bytes in read message buffer.
XHDCP22_TX_CERT_RCVID_SIZE
RX certificate and Tx public key sizes in bytes.
Unique receiver Id size in the RX certificate.
XHDCP22_TX_CERT_PUB_KEY_N_SIZE
Public key-N size in the RX certificate.
Referenced by XHdcp22Tx_EncryptKm.
XHDCP22_TX_CERT_PUB_KEY_E_SIZE
Public key-E size in the RX certificate.
Referenced by XHdcp22Tx_EncryptKm.
XHDCP22_TX_CERT_RSVD_SIZE
Reserved size in the RX certificate.
XHDCP22_TX_CERT_SIGNATURE_SIZE
Signature size in the RX certificate.
XHDCP22_TX_CERT_SIZE
Total size of the RX certificate.
XHDCP22_TX_RXCAPS_SIZE
RX capabilities size.
Referenced by XHdcp22Tx_ComputeHPrime.
XHDCP22_TX_TXCAPS_SIZE
TX capabilities size.
Referenced by XHdcp22Tx_ComputeHPrime.
XHDCP22_TX_KPUB_DCP_LLC_N_SIZE
LLC public key-N size.
Referenced by XHdcp22Tx_LoadRevocationTable.
XHDCP22_TX_KPUB_DCP_LLC_E_SIZE
LLC public key-E size.
Referenced by XHdcp22Tx_LoadRevocationTable.
XHDCP22_TX_SHA256_HASH_SIZE
SHA256 hash size in bytes.
Referenced by XHdcp22Tx_ComputeLPrime, XHdcp22Tx_ComputeM.
XHDCP22_TX_AES128_SIZE
AES128 keys in bytes.
Referenced by XHdcp22Tx_ComputeEdkeyKs, XHdcp22Tx_ComputeHPrime, XHdcp22Tx_ComputeLPrime, XHdcp22Tx_ComputeM.
XHDCP22_TX_RTX_SIZE
64 bits.
Referenced by XHdcp22Tx_ComputeEdkeyKs, XHdcp22Tx_ComputeHPrime, XHdcp22Tx_ComputeLPrime, XHdcp22Tx_ComputeM.
XHDCP22_TX_RRX_SIZE
64 bits.
Referenced by XHdcp22Tx_ComputeEdkeyKs, XHdcp22Tx_ComputeHPrime, XHdcp22Tx_ComputeLPrime, XHdcp22Tx_ComputeM.
XHDCP22_TX_KM_SIZE
XHDCP22_TX_E_KPUB_KM_SIZE
1024 bits.
XHDCP22_TX_H_PRIME_SIZE
256 bits.
XHDCP22_TX_EKH_KM_SIZE
128 bits.
XHDCP22_TX_KM_MSK_SEED_SIZE
XHDCP22_TX_RN_SIZE
64-bits.
Referenced by XHdcp22Tx_ComputeEdkeyKs, XHdcp22Tx_ComputeLPrime.
XHDCP22_TX_RIV_SIZE
64-bits.
XHDCP22_TX_L_PRIME_SIZE
256 bits.
XHDCP22_TX_KS_SIZE
128 bits.
Referenced by XHdcp22Tx_ComputeEdkeyKs.
XHDCP22_TX_EDKEY_KS_SIZE
128 bits.
Referenced by XHdcp22Tx_ComputeEdkeyKs.
XHDCP22_TX_SRM_RCVID_SIZE
Receiver Id size in the SRM block.
Referenced by XHdcp22Tx_IsDeviceRevoked, XHdcp22Tx_LoadRevocationTable, XHdcp22Tx_RevokeReceiverId.
XHDCP22_TX_SRM_SIGNATURE_SIZE
Signature size in the SRM block.
Referenced by XHdcp22Tx_VerifySRM.
XHDCP22_TX_RXINFO_SIZE
RxInfo size in bytes.
Referenced by XHdcp22Tx_ComputeM.
XHDCP22_TX_SEQ_NUM_V_SIZE
Seq_num_v size in bytes.
XHDCP22_TX_V_SIZE
V size in bytes.
XHDCP22_TX_V_PRIME_SIZE
VPrime size in bytes.
XHDCP22_TX_SEQ_NUM_M_SIZE
Seq_num_m size in bytes.
Referenced by XHdcp22Tx_ComputeM.
XHDCP22_TX_K_SIZE
K size in bytes.
XHDCP22_TX_STREAMID_TYPE_SIZE
Stream ID and Type size in bytes.
Referenced by XHdcp22Tx_ComputeM.
XHDCP22_TX_M_PRIME_SIZE
MPrime size in bytes.
XHDCP22_TX_TEST_CERT_RX
Use a certificate test vector.
XHDCP22_TX_TEST_H1
Use a H_Prime test vector.
XHDCP22_TX_TEST_L1
Use a L_Prime test vector.
XHDCP22_TX_TEST_EKH_KM
Use a pairing info Ekh(Km) test vector, use i.c.w XHDCP22_TX_TEST_RCV_TIMEOUT.
XHDCP22_TX_TEST_INVALID_VALUE
Invalidate a value.
XHDCP22_TX_TEST_RCV_TIMEOUT
Timeout on a received message.
XHDCP22_TX_TEST_V1
Use a V_Prime test vector.
XHDCP22_TX_TEST_M1
Use a M_Prime test vector.
XHDCP22_TX_TEST_STORED_KM
AKE is forced using a stored Km scenario.
Pairing info is pre-loaded with test vectors that forces Stored Km scenario.
XHDCP22_TX_TEST_NO_TIMEOUT
Disable timeout checking.
this is mainly used to check the HDCP RX core in loopback mode in case it cannot meet timing requirements (no offloading to hardware) and reponsetimes need to be logged.
XHDCP22_TX_TEST_CLR_PAIRINGINFO
Pairing info is cleared, to force a non-stored Km scenario.
XHDCP22_TX_TEST_USE_TEST_VECTOR_R1
Use testvectors for receiver R1.
XHDCP22_TX_DDC_BASE_ADDRESS
DDC base address (0x74 >> 1)
Referenced by XHdcp22Tx_IsDwnstrmCapable.
XHdcp22_Tx_TestMode
Testmode is disabled.
XHdcp22_Tx_LogDebugValue
void XHdcp22Tx_MemXor(u8 *Output, const u8 *InputA, const u8 *InputB, unsigned int Size)
This function calculates a XOR on a array.
Output is the XOR of the input arrays. InputA is a input array. InputB is a input array. Size is the size of the buffers to XOR. None.
Referenced by XHdcp22Tx_ComputeEdkeyKs, XHdcp22Tx_ComputeLPrime.
int XHdcp22Tx_VerifyCertificate(const XHdcp22_Tx_CertRx *CertificatePtr, const u8 *KpubDcpNPtr, int KpubDcpNSize, const u8 *KpubDcpEPtr, int KpubDcpESize)
This function verifies the HDCP receivers certificate.
CertificatePtr is a pointer to the certificate from the HDCP2.2 receiver. KpubDcpNPtr is a pointer to the N-value of the certificate signature. KpubDcpNSize is the size of the N-value of the certificates signature. KpubDcpEPtr iis a pointer to the E-value of the certificate signature. KpubDcpESize is the size of the E-value of the certificates signature. XST_SUCCESS if the certificate is valid.XST_FAILURE if the certificate is invalid. None.
int XHdcp22Tx_VerifySRM(const u8 *SrmPtr, int SrmSize, const u8 *KpubDcpNPtr, int KpubDcpNSize, const u8 *KpubDcpEPtr, int KpubDcpESize)
This function verifies a HDCP2 system renewability message (SRM) block.
SrmPtr is a pointer to the SRM. SrmSize is the size of the SRM in bytes. KpubDcpNPtr is a pointer to the N-value of the DCP LLC key. KpubDcpNSize is the size of the N-value of the DCP LLC key. KpubDcpEPtr iis a pointer to the E-value of the DCP LLC key. KpubDcpESize is the size of the E-value of the DCP LLC key. XST_SUCCESS if the SRM block is valid.XST_FAILURE if the SRM block is invalid. None.
References XHDCP22_TX_SRM_SIGNATURE_SIZE.
Referenced by XHdcp22Tx_LoadRevocationTable.
void XHdcp22Tx_ComputeHPrime(const u8 *Rrx, const u8 *RxCaps, const u8 *Rtx, const u8 *TxCaps, const u8 *Km, u8 *HPrime)
This function computes HPrime.
Rrx is the Rx random generated value on start of authentication. RxCaps are the capabilities of the receiver. Rtx is the Tx random generated value start of authentication. TxCaps are the capabilities of the receiver. Km is the master key generated by tx. HPrime is a pointer to the HPrime hash from the HDCP2.2 receiver. None.
References XHDCP22_TX_AES128_SIZE, XHDCP22_TX_RRX_SIZE, XHDCP22_TX_RTX_SIZE, XHDCP22_TX_RXCAPS_SIZE, XHDCP22_TX_TXCAPS_SIZE.
void XHdcp22Tx_ComputeLPrime(const u8 *Rn, const u8 *Km, const u8 *Rrx, const u8 *Rtx, u8 *LPrime)
This function computes LPrime.
Kd is calculated as in XHdcp22Tx_ComputeHPrime, but could also be stored the first time. This could save some computing time. According protocol however, only Rrx and Rtx are supposed to be stored. Rn is a pseudo-random nonce. Km is the master key generated by tx and previouslyd stored. Rrx is the random value generated by rx. Rtx is the random value generated by tx. LPrime is a pointer to the computed LPrime hash. None.
References XHDCP22_TX_AES128_SIZE, XHDCP22_TX_RN_SIZE, XHDCP22_TX_RRX_SIZE, XHDCP22_TX_RTX_SIZE, XHDCP22_TX_SHA256_HASH_SIZE, XHdcp22Tx_MemXor.
void XHdcp22Tx_ComputeV(const u8 *Rn, const u8 *Rrx, const u8 *RxInfo, const u8 *Rtx, const u8 *RecvIDList, const u8 RecvIDCount, const u8 *SeqNum_V, const u8 *Km, u8 *V)
void XHdcp22Tx_ComputeM(const u8 *Rn, const u8 *Rrx, const u8 *Rtx, const u8 *StreamIDType, const u8 *k, const u8 *SeqNum_M, const u8 *Km, u8 *M)
Computes the M hash value for HDCP 2.2 authentication.
This function calculates the M parameter used in the HDCP 2.2 protocol by processing the input parameters through a cryptographic hash function. Rn Pointer to the Rn random number. Rrx Pointer to the Rrx receiver random number. Rtx Pointer to the Rtx transmitter random number. StreamIDType Pointer to the Stream ID Type value. k Pointer to the k parameter. SeqNum_M Pointer to the sequence number for M. Km Pointer to the Km master key. M Pointer to the output buffer where computed M hash will be stored.. The caller must ensure all input pointers are valid and point to buffers of appropriate size. The output buffer M must be pre-allocated with sufficient size to store the computed hash value.
References XHDCP22_TX_AES128_SIZE, XHDCP22_TX_RCVID_SIZE, XHDCP22_TX_REPEATER_MAX_DEVICE_COUNT, XHDCP22_TX_RRX_SIZE, XHDCP22_TX_RTX_SIZE, XHDCP22_TX_RXINFO_SIZE, XHDCP22_TX_SEQ_NUM_M_SIZE, XHDCP22_TX_SHA256_HASH_SIZE, XHDCP22_TX_STREAMID_TYPE_SIZE.
void XHdcp22Tx_ComputeEdkeyKs(const u8 *Rn, const u8 *Km, const u8 *Ks, const u8 *Rrx, const u8 *Rtx, u8 *EdkeyKs)
This function computes EdkeyKs.
Kd is calculated as in XHdcp22Tx_ComputeHPrime, but could also be stored the first time. This could save some computing time. According protocol however, only Rrx and Rtx are supposed to be stored. Rn is a pseudo-random nonce. Km is the master key generated by tx.. See also XHdcp22Tx_ComputeHPrime Ks is the session key. Rrx is the random value generated by rx. Rtx is the random value generated by tx. EdkeyKs is the encrypted Ks output. None.
References XHDCP22_TX_AES128_SIZE, XHDCP22_TX_EDKEY_KS_SIZE, XHDCP22_TX_KS_SIZE, XHDCP22_TX_RN_SIZE, XHDCP22_TX_RRX_SIZE, XHDCP22_TX_RTX_SIZE, XHdcp22Tx_MemXor.
int XHdcp22Tx_EncryptKm(const XHdcp22_Tx_CertRx *CertificatePtr, const u8 *KmPtr, u8 *MaskingSeedPtr, u8 *EncryptedKmPtr)
This function encrypts the Km value with the receivers public key into Ekh(Km)
CertificatePtr is a pointer to the certificate from the HDCP2.2 receiver. KmPtr is the random master key. MaskingSeedPtr is a pointer to a 32 byte seed for masking in the MGF1 function used in RSA-OEAP encryption. EncryptedKmPtr output of the encryption with a 128 byte (1024 bit) size. XST_SUCCESS if encryption succeeded.XST_FAILURE if encryption failed. None.
References XHDCP22_TX_CERT_PUB_KEY_E_SIZE, XHDCP22_TX_CERT_PUB_KEY_N_SIZE.
void XHdcp22Tx_GenerateRandom(XHdcp22_Tx *InstancePtr, int NumOctets, u8 *RandomNumberPtr)
This function generates random octets.
Otherwise it uses offloading from hardware. InstancePtr is a pointer to the XHdcp22_Tx core instance. NumOctets is the number of octets in the random number. RandomNumberPtr is a pointer to the random number. None.
References XHdcp22_Tx::Rng.
void XHdcp22Tx_Dump(const char *string, const u8 *m, u32 mlen)
void XHdcp22Tx_LogWrNoInst(XHdcp22_Tx_LogEvt Evt, u16 Data)