
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2021.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* Copyright (c) 2022 - 2025, Advanced Micro Devices, Inc.  All rights reserved.
* SPDX-License-Identifier: MIT

*
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xcframe.h"

/*
* The configuration table for devices
*/

XCframe_Config XCframe_ConfigTable[XPAR_XCFRAME_NUM_INSTANCES] =
{
	{
		XPAR_PSV_PMC_CFI_CFRAME_0_DEVICE_ID,
		XPAR_PSV_PMC_CFI_CFRAME_0_BASEADDR
	}
};
