
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.1
* DO NOT EDIT.
*
* Copyright (c) 2010 - 2022 Xilinx, Inc. All Rights Reserved.
* Copyright (c) 2022 - 2025, Advanced Micro Devices, Inc.  All rights reserved.
* SPDX-License-Identifier: MIT

*
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xrtcpsu.h"

/*
* The configuration table for devices
*/

XRtcPsu_Config XRtcPsu_ConfigTable[XPAR_XRTCPSU_NUM_INSTANCES] =
{
	{
		XPAR_PSV_PMC_RTC_0_DEVICE_ID,
		XPAR_PSV_PMC_RTC_0_BASEADDR
	}
};
