can
XCAN_MODE_CONFIG
Configuration mode.
Referenced by main, XCan_EnterMode, XCan_GetMode, XCan_SelfTest, XCan_SetBaudRatePrescaler, XCan_SetBitTiming, XCanPolledExample.
XCAN_MODE_NORMAL
Normal mode.
Referenced by XCan_EnterMode, XCan_GetMode.
XCAN_MODE_LOOPBACK
Loop Back mode.
Referenced by main, XCan_EnterMode, XCan_GetMode, XCan_SelfTest, XCanPolledExample.
XCAN_MODE_SLEEP
Sleep mode.
Referenced by XCan_EnterMode, XCan_GetMode.
XCAN_HANDLER_SEND
Handler type for frame sending interrupt.
Referenced by main, XCan_SetHandler.
XCAN_HANDLER_RECV
Handler type for frame reception interrupt.
Referenced by main, XCan_SetHandler.
XCAN_HANDLER_ERROR
Handler type for error interrupt.
Referenced by main, XCan_SetHandler.
XCAN_HANDLER_EVENT
Handler type for all other interrupts.
Referenced by main, XCan_SetHandler.
XCAN_SRR_OFFSET
Software Reset Register.
Referenced by XCan_EnterMode, XCan_Reset.
XCAN_MSR_OFFSET
Mode Select Register.
Referenced by XCan_EnterMode.
XCAN_BRPR_OFFSET
Baud Rate Prescaler Register.
Referenced by XCan_GetBaudRatePrescaler, XCan_SetBaudRatePrescaler.
XCAN_BTR_OFFSET
Bit Timing Register.
Referenced by XCan_GetBitTiming, XCan_SetBitTiming.
XCAN_ECR_OFFSET
Error Counter Register.
Referenced by XCan_GetBusErrorCounter.
XCAN_ESR_OFFSET
Error Status Register.
Referenced by XCan_ClearBusErrorStatus, XCan_GetBusErrorStatus.
XCAN_SR_OFFSET
Status Register.
Referenced by XCan_GetStatus.
XCAN_ISR_OFFSET
Interrupt Status Register.
Referenced by XCan_InterruptGetStatus.
XCAN_IER_OFFSET
Interrupt Enable Register.
Referenced by XCan_InterruptDisable, XCan_InterruptEnable, XCan_InterruptGetEnabled.
XCAN_ICR_OFFSET
Interrupt Clear Register.
Referenced by XCan_InterruptClear.
XCAN_TXFIFO_ID_OFFSET
TX FIFO ID.
Referenced by XCan_Send.
XCAN_TXFIFO_DLC_OFFSET
TX FIFO DLC.
Referenced by XCan_Send.
XCAN_TXFIFO_DW1_OFFSET
TX FIFO Data Word 1.
Referenced by XCan_Send.
XCAN_TXFIFO_DW2_OFFSET
TX FIFO Data Word 2.
Referenced by XCan_Send.
XCAN_TXBUF_ID_OFFSET
TX High Priority Buffer ID.
Referenced by XCan_SendHighPriority.
XCAN_TXBUF_DLC_OFFSET
TX High Priority Buffer DLC.
Referenced by XCan_SendHighPriority.
XCAN_TXBUF_DW1_OFFSET
TX High Priority Buf Data Word 1.
Referenced by XCan_SendHighPriority.
XCAN_TXBUF_DW2_OFFSET
TX High Priority Buf Data Word 2.
Referenced by XCan_SendHighPriority.
XCAN_RXFIFO_ID_OFFSET
RX FIFO ID.
Referenced by XCan_Recv.
XCAN_RXFIFO_DLC_OFFSET
RX FIFO DLC.
Referenced by XCan_Recv.
XCAN_RXFIFO_DW1_OFFSET
RX FIFO Data Word 1.
Referenced by XCan_Recv.
XCAN_RXFIFO_DW2_OFFSET
RX FIFO Data Word 2.
Referenced by XCan_Recv.
XCAN_AFR_OFFSET
Acceptance Filter Register.
Referenced by XCan_AcceptFilterDisable, XCan_AcceptFilterEnable, XCan_AcceptFilterGetEnabled.
XCAN_AFMR1_OFFSET
Acceptance Filter Mask Register 1.
Referenced by XCan_AcceptFilterGet, XCan_AcceptFilterSet.
XCAN_AFIR1_OFFSET
Acceptance Filter ID Register 1.
Referenced by XCan_AcceptFilterGet, XCan_AcceptFilterSet.
XCAN_AFMR2_OFFSET
Acceptance Filter Mask Register 2.
Referenced by XCan_AcceptFilterGet, XCan_AcceptFilterSet.
XCAN_AFIR2_OFFSET
Acceptance Filter ID Register 2.
Referenced by XCan_AcceptFilterGet, XCan_AcceptFilterSet.
XCAN_AFMR3_OFFSET
Acceptance Filter Mask Register 3.
Referenced by XCan_AcceptFilterGet, XCan_AcceptFilterSet.
XCAN_AFIR3_OFFSET
Acceptance Filter ID Register 3.
Referenced by XCan_AcceptFilterGet, XCan_AcceptFilterSet.
XCAN_AFMR4_OFFSET
Acceptance Filter Mask Register 4.
Referenced by XCan_AcceptFilterGet, XCan_AcceptFilterSet.
XCAN_AFIR4_OFFSET
Acceptance Filter ID Register 4.
Referenced by XCan_AcceptFilterGet, XCan_AcceptFilterSet.
XCAN_ECC_CFG_OFFSET
ECC Configuration register.
Referenced by XCan_ResetECC.
XCAN_TXTLFIFO_ECC_OFFSET
TXTL FIFO ECC error counter.
Referenced by XCan_GetECCCount.
XCAN_TXOLFIFO_ECC_OFFSET
TXOL FIFO ECC error counter.
Referenced by XCan_GetECCCount.
XCAN_RXFIFO_ECC_OFFSET
RX FIFO ECC error counter.
Referenced by XCan_GetECCCount.
XCAN_SRR_CEN_MASK
Can Enable Mask.
Referenced by XCan_EnterMode.
XCAN_SRR_SRST_MASK
Reset Mask.
Referenced by XCan_Reset.
XCAN_MSR_LBACK_MASK
Loop Back Mode Select Mask.
Referenced by XCan_EnterMode.
XCAN_MSR_SLEEP_MASK
Sleep Mode Select Mask.
Referenced by XCan_EnterMode.
XCAN_BRPR_BRP_MASK
Baud Rate Prescaler Mask.
XCAN_BTR_SJW_MASK
Sync Jump Width Mask.
Referenced by XCan_GetBitTiming, XCan_SetBitTiming.
XCAN_BTR_SJW_SHIFT
Sync Jump Width Shift.
Referenced by XCan_GetBitTiming, XCan_SetBitTiming.
XCAN_BTR_TS2_MASK
Time Segment 2 Mask.
Referenced by XCan_GetBitTiming, XCan_SetBitTiming.
XCAN_BTR_TS2_SHIFT
Time Segment 2 Shift.
Referenced by XCan_GetBitTiming, XCan_SetBitTiming.
XCAN_BTR_TS1_MASK
Time Segment 1 Mask.
Referenced by XCan_GetBitTiming, XCan_SetBitTiming.
XCAN_ECR_REC_MASK
Receive Error Counter Mask.
Referenced by XCan_GetBusErrorCounter.
XCAN_ECR_REC_SHIFT
Receive Error Counter Shift.
Referenced by XCan_GetBusErrorCounter.
XCAN_ECR_TEC_MASK
Transmit Error Counter Mask.
Referenced by XCan_GetBusErrorCounter.
XCAN_ESR_ACKER_MASK
ACK Error Mask.
Referenced by main.
XCAN_ESR_BERR_MASK
Bit Error Mask.
Referenced by main.
XCAN_ESR_STER_MASK
Stuff Error Mask.
Referenced by main.
XCAN_ESR_FMER_MASK
Form Error Mask.
Referenced by main.
XCAN_ESR_CRCER_MASK
CRC Error Mask.
Referenced by main.
XCAN_SR_ACFBSY_MASK
Acceptance Filter busy Mask.
XCAN_SR_TXFLL_MASK
TX FIFO is full Mask.
XCAN_SR_TXBFLL_MASK
TX High Priority Buffer full.
XCAN_SR_ESTAT_MASK
Error Status Mask.
XCAN_SR_ESTAT_SHIFT
Error Status Shift.
XCAN_SR_ERRWRN_MASK
Error Warning Mask.
XCAN_SR_BBSY_MASK
Bus Busy Mask.
XCAN_SR_BIDLE_MASK
Bus Idle Mask.
XCAN_SR_NORMAL_MASK
Normal Mode Mask.
Referenced by XCan_GetMode.
XCAN_SR_SLEEP_MASK
Sleep Mode Mask.
Referenced by XCan_GetMode.
XCAN_SR_LBACK_MASK
Loop Back Mode Mask.
XCAN_SR_CONFIG_MASK
Configuration Mode Mask.
Referenced by XCan_GetMode.
XCAN_IXR_E2BERX_MASK
RX FIFO two bit ECC error.
Referenced by XCan_GetECCCount.
XCAN_IXR_E1BERX_MASK
RX FIFO one bit ECC error.
Referenced by XCan_GetECCCount.
XCAN_IXR_E2BETXOL_MASK
TXOL FIFO two bit ECC error.
Referenced by XCan_GetECCCount.
XCAN_IXR_E1BETXOL_MASK
TXOL FIFO one bit ECC error.
Referenced by XCan_GetECCCount.
XCAN_IXR_E2BETXTL_MASK
TXTL FIFO two bit ECC error.
Referenced by XCan_GetECCCount.
XCAN_IXR_E1BETXTL_MASK
TXTL FIFO one bit ECC error.
Referenced by XCan_GetECCCount.
XCAN_IXR_WKUP_MASK
Wake up Interrupt Mask.
Referenced by main, XCan_IntrHandler.
XCAN_IXR_SLP_MASK
Sleep Interrupt Mask.
Referenced by main, XCan_IntrHandler.
XCAN_IXR_BSOFF_MASK
Bus Off Interrupt Mask.
Referenced by main, XCan_IntrHandler.
XCAN_IXR_ERROR_MASK
Error Interrupt Mask.
Referenced by XCan_IntrHandler.
XCAN_IXR_RXNEMP_MASK
RX FIFO Not Empty Intr Mask.
Referenced by XCan_IntrHandler, XCan_Recv.
XCAN_IXR_RXOFLW_MASK
RX FIFO Overflow Intr Mask.
Referenced by main, XCan_IntrHandler.
XCAN_IXR_RXUFLW_MASK
RX FIFO Underflow Intr Mask.
Referenced by main, XCan_IntrHandler.
XCAN_IXR_RXOK_MASK
New Message Received Intr.
XCAN_IXR_TXBFLL_MASK
TX High Priority Buf Full.
Referenced by main, XCan_IntrHandler.
XCAN_IXR_TXFLL_MASK
TX FIFO Full Interrupt Mask.
Referenced by main, XCan_IntrHandler.
XCAN_IXR_TXOK_MASK
TX Successful Interrupt Mask.
Referenced by XCan_IntrHandler.
XCAN_IXR_ARBLST_MASK
Arbitration Lost Intr Mask.
Referenced by main, XCan_IntrHandler.
XCAN_IXR_ECC_MASK
Mask for ECC interrupts.
Referenced by main, XCan_IntrHandler.
XCAN_IXR_ALL
Mask for basic interrupts.
Referenced by main.
XCAN_IDR_ID1_MASK
Standard Messg Ident Mask.
XCAN_IDR_ID1_SHIFT
Standard Messg Ident Shift.
XCAN_IDR_SRR_MASK
Substitute Remote TX Req.
XCAN_IDR_SRR_SHIFT
Shift Value for SRR.
XCAN_IDR_IDE_MASK
Identifier Extension Mask.
XCAN_IDR_IDE_SHIFT
Identifier Extension Shift.
XCAN_IDR_ID2_MASK
Extended Message Ident Mask.
XCAN_IDR_ID2_SHIFT
Extended Message Ident Shift.
XCAN_IDR_RTR_MASK
Remote TX Request Mask.
XCAN_DLCR_DLC_MASK
Data Length Code Mask.
XCAN_DLCR_DLC_SHIFT
Data Length Code Shift.
XCAN_DW1R_DB0_MASK
Data Byte 0 Mask.
XCAN_DW1R_DB0_SHIFT
Data Byte 0 Shift.
XCAN_DW1R_DB1_MASK
Data Byte 1 Mask.
XCAN_DW1R_DB1_SHIFT
Data Byte 1 Shift.
XCAN_DW1R_DB2_MASK
Data Byte 2 Mask.
XCAN_DW1R_DB2_SHIFT
Data Byte 2 Shift.
XCAN_DW1R_DB3_MASK
Data Byte 3 Mask.
XCAN_DW2R_DB4_MASK
Data Byte 4 Mask.
XCAN_DW2R_DB4_SHIFT
Data Byte 4 Shift.
XCAN_DW2R_DB5_MASK
Data Byte 5 Mask.
XCAN_DW2R_DB5_SHIFT
Data Byte 5 Shift.
XCAN_DW2R_DB6_MASK
Data Byte 6 Mask.
XCAN_DW2R_DB6_SHIFT
Data Byte 6 Shift.
XCAN_DW2R_DB7_MASK
Data Byte 7.
XCAN_AFR_UAF4_MASK
Use Acceptance Filter No.4.
Referenced by XCan_AcceptFilterGet, XCan_AcceptFilterSet.
XCAN_AFR_UAF3_MASK
Use Acceptance Filter No.3.
Referenced by XCan_AcceptFilterGet, XCan_AcceptFilterSet.
XCAN_AFR_UAF2_MASK
Use Acceptance Filter No.2.
Referenced by XCan_AcceptFilterGet, XCan_AcceptFilterSet.
XCAN_AFR_UAF1_MASK
Use Acceptance Filter No.1.
Referenced by XCan_AcceptFilterGet, XCan_AcceptFilterSet.
XCAN_AFR_UAF_ALL_MASK
Mask for Acceptance Filters.
Referenced by XCan_AcceptFilterDisable, XCan_AcceptFilterEnable.
XCAN_ECC_CFG_RST_MASK
Reset Mask for ECC configuration register.
Referenced by XCan_ResetECC.
XCAN_ECC_CFG_REECRX_MASK
Reset RX FIFO ECC error counters.
XCAN_ECC_CFG_REECTXOL_MASK
Reset TXOL FIFO ECC error counters.
XCAN_ECC_CFG_REECTXTL_MASK
Reset TXTL FIFO ECC error counters.
XCAN_ECC_2BIT_SHIFT
ECC 2bit error counter shift.
Referenced by XCan_GetECCCount.
XCAN_MAX_FRAME_SIZE
Maximum CAN frame length in bytes.
XCAN_MASK_LOW_16BITS
Mask to obtain lower 16bits.
Referenced by XCan_GetECCCount.
XCAN_MASK_HIGH_16BITS
Mask to obtain higher 16bits.
Referenced by XCan_GetECCCount.
typedef void(* XCan_SendRecvHandler)(void *CallBackRef))(void *CallBackRef)
Callback type for frame sending and reception interrupts.
CallBackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked.
typedef void(* XCan_ErrorHandler)(void *CallBackRef, u32 ErrorMask))(void *CallBackRef, u32 ErrorMask)
Callback type for error interrupt.
CallBackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. ErrorMask is a bit mask indicating the cause of the error. Its value equals 'OR'ing one or more XCAN_ESR_* values defined in xcan_l.h
typedef void(* XCan_EventHandler)(void *CallBackRef, u32 Mask))(void *CallBackRef, u32 Mask)
Callback type for all kinds of interrupts except sending frame interrupt, receiving frame interrupt, and error interrupt.
CallBackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. Mask is a bit mask indicating the pending interrupts. Its value equals 'OR'ing one or more XCAN_IXR_* defined in xcan_l.h
XCan_Config XCan_ConfigTable[][]
This table contains configuration information for each CAN device in the system.
XCan_Config XCan_ConfigTable[XPAR_XCAN_NUM_INSTANCES][XPAR_XCAN_NUM_INSTANCES]
This table contains configuration information for each CAN device in the system.
u32 TxFrame[XCAN_MAX_FRAME_SIZE_IN_WORDS][XCAN_MAX_FRAME_SIZE_IN_WORDS]
TxFrame Buffer.
u32 RxFrame[XCAN_MAX_FRAME_SIZE_IN_WORDS][XCAN_MAX_FRAME_SIZE_IN_WORDS]
RxFrame Buffer.
static void Initialize(XCan *InstancePtr, XCan_Config *ConfigPtr)
This function initializes a XCan instance/driver.
This function is utilized by XCan_Initialize() or XCan_VmInitialize(), depending on if Virtual Memory support is wanted or not.The initialization entails: Initialize all members of the XCan structure, except BaseAddress. BaseAddress should be taken care of by XCan_Initialize() or XCan_VmInitialize(), before they call this function.Reset the CAN device. The CAN device will enter Configuration Mode immediately after the reset is finished. InstancePtr is a pointer to the XCan instance to be worked on. ConfigPtr points to the a configuration structure the XCan instance should be associated with. None. None.
static void StubHandler(void)
This routine is a stub for the asynchronous callbacks.
The stub is here in case the upper layer forgot to set the handler(s). On initialization, all handlers are set to this callback. It is considered an error for this handler to be invoked.None. None.
int XCan_Initialize(XCan *InstancePtr, UINTPTR BaseAddress)
This routine initializes a specific XCan instance/driver.
This function should only be used when no Virtual Memory support is needed. To use virtual memory, the caller should invoke XCan_VmInitialize(). See the description of XCan_VmInitialize() for detailed information.This initialization entails: Search for device configuration based on the unique device ID/BaseAddress.Initialize Base Address field of the XCan structure using the device address in the found device configuration.Populate all other data fields in the XCan structureReset the device. InstancePtr is a pointer to the XCan instance to be worked on. BaseAddress contains the base address of the device XST_SUCCESS if initialization was successfulXST_DEVICE_NOT_FOUND if device configuration information was not found for a device with the supplied device ID/BaseAddress. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XCan_Config::BaseAddress, XCan::BaseAddress, XCan_LookupConfig.
Referenced by main, XCanPolledExample.
int XCan_VmInitialize(XCan *InstancePtr, UINTPTR BaseAddress, UINTPTR VirtAddr)
This routine initializes of a specific XCan instance/driver.
This function should only be used if Virtual Memory support is necessary. The caller is responsible for calculating the correct device base address in Virtual memory address space and passing it into this function.This initialization entails: Search for device configuration based on the unique device ID/BaseAddress.Initialize Base Address field of the XCan structure using the given virtual address parameter value.Populate all other data fields in the XCan structure.Reset the device. InstancePtr is a pointer to the XCan instance to be worked on. BaseAddress contains the base address of the device VirtAddr is the device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from VirtAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. XST_SUCCESS if initialization was successfulXST_DEVICE_NOT_FOUND if device configuration information was not found for a device with the supplied device ID/BaseAddress. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XCan::BaseAddress, XCan_LookupConfig.
void XCan_Reset(XCan *InstancePtr)
This function resets the CAN device.
Calling this function resets the device immediately, and any pending transmission or reception is terminated at once. Both Object Layer and Transfer Layer are reset. This function does not reset the Physical Layer. All registers are reset to the default values, and no previous status will be restored. TX FIFO, RX FIFO and TX High Priority Buffer are also reset.When a reset is required due to an internal error, the driver notifies the upper layer software of this need through the error status code or interrupts The upper layer software is responsible for calling this Reset function and then re-configuring the device.The CAN device will be in Configuration Mode immediately after this function returns. InstancePtr is a pointer to the XCan instance to be worked on. None. None.
References XCan::BaseAddress, XCan::IsReady, XCAN_SRR_OFFSET, XCAN_SRR_SRST_MASK, XCan_WriteReg.
Referenced by main, XCan_SelfTest.
u8 XCan_GetMode(XCan *InstancePtr)
This routine returns current operation mode the CAN device is in.
InstancePtr is a pointer to the XCan instance to be worked on. XCAN_MODE_CONFIG if the device is in Configuration Mode.XCAN_MODE_SLEEP if the device is in Sleep Mode.XCAN_MODE_NORMAL if the device is in Normal Mode.XCAN_MODE_LOOPBACK if the device is in Loop Back Mode. None.
References XCan::IsReady, XCan_GetStatus, XCAN_MODE_CONFIG, XCAN_MODE_LOOPBACK, XCAN_MODE_NORMAL, XCAN_MODE_SLEEP, XCAN_SR_CONFIG_MASK, XCAN_SR_NORMAL_MASK, XCAN_SR_SLEEP_MASK.
Referenced by main, XCan_EnterMode, XCan_SelfTest, XCan_SetBaudRatePrescaler, XCan_SetBitTiming, XCanPolledExample.
void XCan_EnterMode(XCan *InstancePtr, u8 OperationMode)
This function allows the CAN device to enter one of the following operation modes:
Configuration Mode: Pass in parameter XCAN_MODE_CONFIGSleep Mode: Pass in parameter XCAN_MODE_SLEEPNormal Mode: Pass in parameter XCAN_MODE_NORMALLoop Back Mode: Pass in parameter XCAN_MODE_LOOPBACK. Read xcan.h and device specification for detailed description of each operation mode. InstancePtr is a pointer to the XCan instance to be worked on. OperationMode specify which operation mode to enter. Valid value is any of XCAN_MODE_* defined in xcan.h. Please note no multiple modes could be entered at the same time. None. This function does NOT ensure CAN device enters the specified operation mode before returns the control to the caller. The caller is responsible for checking current operation mode using XCan_GetMode().
References XCan::BaseAddress, XCan::IsReady, XCan_GetMode, XCAN_MODE_CONFIG, XCAN_MODE_LOOPBACK, XCAN_MODE_NORMAL, XCAN_MODE_SLEEP, XCAN_MSR_LBACK_MASK, XCAN_MSR_OFFSET, XCAN_MSR_SLEEP_MASK, XCAN_SRR_CEN_MASK, XCAN_SRR_OFFSET, XCan_WriteReg.
Referenced by main, XCan_SelfTest, XCanPolledExample.
u32 XCan_GetStatus(XCan *InstancePtr)
This function returns Status value from Status Register (SR).
Use the XCAN_SR_* constants defined in xcan_l.h to interpret the returned value. InstancePtr is a pointer to the XCan instance to be worked on. The 32-bit value read from Status Register. None.
References XCan::BaseAddress, XCan::IsReady, XCan_ReadReg, XCAN_SR_OFFSET.
Referenced by XCan_GetMode.
void XCan_GetBusErrorCounter(XCan *InstancePtr, u8 *RxErrorCount, u8 *TxErrorCount)
This function reads Receive and Transmit error counters.
InstancePtr is a pointer to the XCan instance to be worked on. RxErrorCount will contain Receive Error Counter value after this function returns. TxErrorCount will contain Transmit Error Counter value after this function returns. None. None.
References XCan::BaseAddress, XCan::IsReady, XCAN_ECR_OFFSET, XCAN_ECR_REC_MASK, XCAN_ECR_REC_SHIFT, XCAN_ECR_TEC_MASK, XCan_ReadReg.
u32 XCan_GetBusErrorStatus(XCan *InstancePtr)
This function reads Error Status value from Error Status Register (ESR).
Use the XCAN_ESR_* constants defined in xcan_l.h to interpret the returned value. InstancePtr is a pointer to the XCan instance to be worked on. The 32-bit value read from Error Status Register. None.
References XCan::BaseAddress, XCan::IsReady, XCAN_ESR_OFFSET, XCan_ReadReg.
Referenced by XCan_IntrHandler.
void XCan_ClearBusErrorStatus(XCan *InstancePtr, u32 Mask)
This function clears Error Status bit(s) previously set in Error Status Register (ESR).
Use the XCAN_ESR_* constants defined in xcan_l.h to create the value to pass in. If a bit was cleared in Error Status Register before this function is called, it will not be touched. InstancePtr is a pointer to the XCan instance to be worked on. Mask is he 32-bit mask used to clear bits in Error Status Register. Multiple XCAN_ESR_* values could be 'OR'ed to clear multiple bits None.
References XCan::BaseAddress, XCan::IsReady, XCAN_ESR_OFFSET, XCan_WriteReg.
Referenced by XCan_IntrHandler.
int XCan_Send(XCan *InstancePtr, u32 *FramePtr)
This function sends a CAN Frame.
This function first checks if TX FIFO is full. If not, it then writes the given frame into the TX FIFO; otherwise, it returns error code immediately. This function does not wait for the given frame being sent to CAN bus. InstancePtr is a pointer to the XCan instance to be worked on. FramePtr is a pointer to a 32-bit aligned buffer containing the CAN frame to be sent. XST_SUCCESS if TX FIFO was not full and the given frame was written into the FIFO;XST_FIFO_NO_ROOM if there is no room in the TX FIFO for the given frame None.
References XCan::BaseAddress, XCan::IsReady, XCan_IsTxFifoFull, XCAN_TXFIFO_DLC_OFFSET, XCAN_TXFIFO_DW1_OFFSET, XCAN_TXFIFO_DW2_OFFSET, XCAN_TXFIFO_ID_OFFSET, XCan_WriteReg.
Referenced by main, XCan_SelfTest.
int XCan_Recv(XCan *InstancePtr, u32 *FramePtr)
This function receives a CAN Frame.
This function first checks if RX FIFO is empty, if not, it then reads a frame from the RX FIFO into the given buffer. This function returns error code immediately if there is no frame in the RX FIFO. InstancePtr is a pointer to the XCan instance to be worked on. FramePtr is a pointer to a 32-bit aligned buffer where the CAN frame to be written. XST_SUCCESS if RX FIFO was not empty and a frame was read from RX FIFO successfully and written into the given buffer;XST_NO_DATA if there is no frame to be received from the FIFO None.
References XCan::BaseAddress, XCan::IsReady, XCan_InterruptClear, XCan_IsRxEmpty, XCAN_IXR_RXNEMP_MASK, XCan_ReadReg, XCAN_RXFIFO_DLC_OFFSET, XCAN_RXFIFO_DW1_OFFSET, XCAN_RXFIFO_DW2_OFFSET, XCAN_RXFIFO_ID_OFFSET.
Referenced by main, XCan_SelfTest.
int XCan_SendHighPriority(XCan *InstancePtr, u32 *FramePtr)
This routine sends a CAN High Priority frame.
This function first checks if TX High Priority Buffer is empty. If yes, it then writes the given frame into the Buffer. If not, This function returns immediately. This function does not wait for the given frame being sent to CAN bus. InstancePtr is a pointer to the XCan instance to be worked on. FramePtr is a pointer to a 32-bit aligned buffer containing the CAN High Priority frame to be sent. XST_SUCCESS if TX High Priority Buffer was not full and the given frame was written into the buffer;XST_FIFO_NO_ROOM if there is no room in the TX High Priority Buffer for this frame. If the frame needs to be sent immediately and not delayed by processor's interrupts handling, the caller should disable interrupt at processor level before invoking this function.
References XCan::BaseAddress, XCan::IsReady, XCan_IsHighPriorityBufFull, XCAN_TXBUF_DLC_OFFSET, XCAN_TXBUF_DW1_OFFSET, XCAN_TXBUF_DW2_OFFSET, XCAN_TXBUF_ID_OFFSET, XCan_WriteReg.
void XCan_AcceptFilterEnable(XCan *InstancePtr, u32 FilterIndexes)
This routine enables individual acceptance filters.
Up to 4 filters could be enabled. InstancePtr is a pointer to the XCan instance to be worked on. FilterIndexes specifies which filter(s) to enable. Use any XCAN_AFR_UAF*_MASK to enable one filter, and "Or" multiple XCAN_AFR_UAF*_MASK values if multiple filters need to be enabled. Any filter not specified in this parameter will keep its previous enable/disable setting. None. Acceptance Filter Register is an optional register in Xilinx CAN device. If it is NOT existing in the device, this function should NOT be used. Calling this function in this case will cause an assertion failure.
References XCan::BaseAddress, XCan::IsReady, XCan::NumOfAcceptFilters, XCAN_AFR_OFFSET, XCAN_AFR_UAF_ALL_MASK, XCan_ReadReg, XCan_WriteReg.
void XCan_AcceptFilterDisable(XCan *InstancePtr, u32 FilterIndexes)
This routine disables individual acceptance filters.
Up to 4 filters could be disabled. If all acceptance filters are disabled then all received frames are stored in the RX FIFO. InstancePtr is a pointer to the XCan instance to be worked on. FilterIndexes specifies which filter(s) to disable. Use any XCAN_AFR_UAF*_MASK to disable one filter, and "Or" multiple XCAN_AFR_UAF*_MASK values if multiple filters need to be disabled. Any filter not specified in this parameter will keep its previous enable/disable setting. If all acceptance filters are disabled then all received frames are stored in the RX FIFO. None. Acceptance Filter Register is an optional register in Xilinx CAN device. If it is NOT existing in the device, this function should NOT be used. Calling this function in this case will cause an assertion failure.
References XCan::BaseAddress, XCan::IsReady, XCan::NumOfAcceptFilters, XCAN_AFR_OFFSET, XCAN_AFR_UAF_ALL_MASK, XCan_ReadReg, XCan_WriteReg.
u32 XCan_AcceptFilterGetEnabled(XCan *InstancePtr)
This function returns enabled acceptance filters.
Use XCAN_AFR_UAF*_MASK defined in xcan_l.h to interpret the returned value. If no acceptance filters are enabled then all received frames are stored in the RX FIFO. InstancePtr is a pointer to the XCan instance to be worked on. The value stored in Acceptance Filter Register. Acceptance Filter Register is an optional register in Xilinx CAN device. If it is NOT existing in the device, this function should NOT be used. Calling this function in this case will cause an assertion failure.
References XCan::BaseAddress, XCan::IsReady, XCan::NumOfAcceptFilters, XCAN_AFR_OFFSET, XCan_ReadReg.
Referenced by XCan_AcceptFilterSet.
int XCan_AcceptFilterSet(XCan *InstancePtr, u32 FilterIndex, u32 MaskValue, u32 IdValue)
This function sets values to the Acceptance Filter Mask Register (AFMR) and Acceptance Filter ID Register (AFIR) for the specified Acceptance Filter.
Use XCAN_IDR_* defined in xcan_l.h to create the values to set the filter. Read xcan.h and device specification for details.This function should be called only after: The given filter is disabled by calling XCan_AcceptFilterDisable();And the CAN device is ready to accept writes to AFMR and AFIR, i.e., XCan_IsAcceptFilterBusy() returns FALSE. InstancePtr is a pointer to the XCan instance to be worked on. FilterIndex defines which Acceptance Filter Mask and ID Register to set. Use any single XCAN_AFR_UAF*_MASK value. MaskValue is the value to write to the chosen Acceptance Filter Mask Register. IdValue is the value to write to the chosen Acceptance Filter ID Register. XST_SUCCESS if the values were set successfully.XST_FAILURE if the given filter was not disabled, or the CAN device was not ready to accept writes to AFMR and AFIR. Acceptance Filter Mask and ID Registers are optional registers in Xilinx CAN device. If they are NOT existing in the device, this function should NOT be used. Calling this function in this case will cause an assertion failure.
References XCan::BaseAddress, XCan::IsReady, XCan::NumOfAcceptFilters, XCan_AcceptFilterGetEnabled, XCAN_AFIR1_OFFSET, XCAN_AFIR2_OFFSET, XCAN_AFIR3_OFFSET, XCAN_AFIR4_OFFSET, XCAN_AFMR1_OFFSET, XCAN_AFMR2_OFFSET, XCAN_AFMR3_OFFSET, XCAN_AFMR4_OFFSET, XCAN_AFR_UAF1_MASK, XCAN_AFR_UAF2_MASK, XCAN_AFR_UAF3_MASK, XCAN_AFR_UAF4_MASK, XCan_IsAcceptFilterBusy, XCan_WriteReg.
void XCan_AcceptFilterGet(XCan *InstancePtr, u32 FilterIndex, u32 *MaskValue, u32 *IdValue)
This function reads the values of the Acceptance Filter Mask and ID Register for the specified Acceptance Filter.
Use XCAN_IDR_* defined in xcan_l.h to interpret the values. Read xcan.h and device specification for details. InstancePtr is a pointer to the XCan instance to be worked on. FilterIndex defines which Acceptance Filter Mask Register to get Mask and ID from. Use any single XCAN_FILTER_* value. MaskValue will store the Mask value read from the chosen Acceptance Filter Mask Register after this function returns. IdValue will store the ID value read from the chosen Acceptance Filter ID Register after this function returns. None. Acceptance Filter Mask and ID Registers are optional registers in Xilinx CAN device. If they are NOT existing in the device, this function should NOT be used. Calling this function in this case will cause an assertion failure.
References XCan::BaseAddress, XCan::IsReady, XCan::NumOfAcceptFilters, XCAN_AFIR1_OFFSET, XCAN_AFIR2_OFFSET, XCAN_AFIR3_OFFSET, XCAN_AFIR4_OFFSET, XCAN_AFMR1_OFFSET, XCAN_AFMR2_OFFSET, XCAN_AFMR3_OFFSET, XCAN_AFMR4_OFFSET, XCAN_AFR_UAF1_MASK, XCAN_AFR_UAF2_MASK, XCAN_AFR_UAF3_MASK, XCAN_AFR_UAF4_MASK, XCan_ReadReg.
XCan_Config * XCan_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XCan_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xcan.h for the definition of XCan_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XCan_Config::Name.
Referenced by main, XCan_Initialize, XCan_VmInitialize.
XCan_Config * XCan_GetConfig(unsigned int InstanceIndex)
This function looks for the device configuration based on the device index.
The table XCan_ConfigTable[] contains the configuration information for each device in the system. InstanceIndex is a 0-based integer indexing all CAN devices in the system. A pointer to the configuration table entry corresponding to the given device ID, or NULL if no match is found. None.
References XCan_Config::Name.
void XCan_ResetECC(XCan *InstancePtr)
This function resets the ECC counters.
Calling this function resets all the ECC counters immediately. The register is reset to default value, and no previous status will be restored. InstancePtr is a pointer to the XCan instance to be worked on. None. None.
References XCan::BaseAddress, XCan::IsReady, XCAN_ECC_CFG_OFFSET, XCAN_ECC_CFG_RST_MASK, XCan_WriteReg.
Referenced by XCan_IntrHandler.
void XCan_GetECCCount(XCan *InstancePtr)
This function gets the count of ECC error count for one and two bit error in TX_TL FIFO, TX_OL FIFO, RX FIFO.
InstancePtr is a pointer to the XCan instance to be worked on. None. None.
References XCan::BaseAddress, XCan::ecc_1bit_txolfifo_cnt, XCan::ecc_1bit_txtlfifo_cnt, XCan::ecc_2bit_rxfifo_cnt, XCan::ecc_2bit_txolfifo_cnt, XCan::ecc_2bit_txtlfifo_cnt, XCan::IsReady, XCAN_ECC_2BIT_SHIFT, XCan_InterruptGetStatus, XCAN_IXR_E1BERX_MASK, XCAN_IXR_E1BETXOL_MASK, XCAN_IXR_E1BETXTL_MASK, XCAN_IXR_E2BERX_MASK, XCAN_IXR_E2BETXOL_MASK, XCAN_IXR_E2BETXTL_MASK, XCAN_MASK_HIGH_16BITS, XCAN_MASK_LOW_16BITS, XCan_ReadReg, XCAN_RXFIFO_ECC_OFFSET, XCAN_TXOLFIFO_ECC_OFFSET, XCAN_TXTLFIFO_ECC_OFFSET.
Referenced by XCan_IntrHandler.
int XCan_SetBaudRatePrescaler(XCan *InstancePtr, u8 Prescaler)
This routine sets Baud Rate Prescaler value.
The system clock for the CAN controller is divided by (Prescaler + 1) to generate the quantum clock needed for sampling and synchronization. Read the device specification for details.Baud Rate Prescaler could be set only after CAN device entered Configuration Mode. So please call XCan_EnterMode() to enter Configuration Mode before using this function. InstancePtr is a pointer to the XCan instance to be worked on. Prescaler is the value to set. Valid values are from 0 to 255. XST_SUCCESS if the Baud Rate Prescaler value is set successfully.XST_FAILURE if CAN device is not in Configuration Mode. None.
References XCan::BaseAddress, XCan::IsReady, XCAN_BRPR_OFFSET, XCan_GetMode, XCAN_MODE_CONFIG, XCan_WriteReg.
Referenced by main, XCan_SelfTest, XCanPolledExample.
u8 XCan_GetBaudRatePrescaler(XCan *InstancePtr)
This routine gets Baud Rate Prescaler value.
The system clock for the CAN controller is divided by (Prescaler + 1) to generate the quantum clock needed for sampling and synchronization. Read the device specification for details. InstancePtr is a pointer to the XCan instance to be worked on. Current used Baud Rate Prescaler value. The value's range is from 0 to 255. None.
References XCan::BaseAddress, XCan::IsReady, XCAN_BRPR_OFFSET, XCan_ReadReg.
int XCan_SetBitTiming(XCan *InstancePtr, u8 SyncJumpWidth, u8 TimeSegment2, u8 TimeSegment1)
This routine sets Bit time.
Time segment 1, Time segment 2 and Synchronization Jump Width are set in this function. Device specification requires the values passed into this function be one less than the actual values of these fields. Read the device specification for details.Bit time could be set only after CAN device entered Configuration Mode. Please call XCan_EnterMode() to enter Configuration Mode before using this function. InstancePtr is a pointer to the XCan instance to be worked on. SyncJumpWidth is the Synchronization Jump Width value to set. Valid values are from 0 to 3. TimeSegment2 is the Time Segment 2 value to set. Valid values are from 0 to 7. TimeSegment1 is the Time Segment 1 value to set. Valid values are from 0 to 15. XST_SUCCESS if the Bit time is set successfully.XST_FAILURE if CAN device is not in Configuration Mode. XST_INVALID_PARAM if any value of SyncJumpWidth, TimeSegment2 and TimeSegment1 is invalid. None.
References XCan::BaseAddress, XCan::IsReady, XCAN_BTR_OFFSET, XCAN_BTR_SJW_MASK, XCAN_BTR_SJW_SHIFT, XCAN_BTR_TS1_MASK, XCAN_BTR_TS2_MASK, XCAN_BTR_TS2_SHIFT, XCan_GetMode, XCAN_MODE_CONFIG, XCan_WriteReg.
Referenced by main, XCan_SelfTest, XCanPolledExample.
void XCan_GetBitTiming(XCan *InstancePtr, u8 *SyncJumpWidth, u8 *TimeSegment2, u8 *TimeSegment1)
This routine gets Bit time.
Time segment 1, Time segment 2 and Synchronization Jump Width values are read in this function. According to device specification, the actual value of each of these fields is one more than the value read. Read the device specification for details. InstancePtr is a pointer to the XCan instance to be worked on. SyncJumpWidth will store the Synchronization Jump Width value after this function returns. Its value ranges from 0 to 3. TimeSegment2 will store the Time Segment 2 value after this function returns. Its value ranges from 0 to 7. TimeSegment1 will store the Time Segment 1 value after this function returns. Its value ranges from 0 to 15. None. None.
References XCan::BaseAddress, XCan::IsReady, XCAN_BTR_OFFSET, XCAN_BTR_SJW_MASK, XCAN_BTR_SJW_SHIFT, XCAN_BTR_TS1_MASK, XCAN_BTR_TS2_MASK, XCAN_BTR_TS2_SHIFT, XCan_ReadReg.
int XCan_SelfTest(XCan *InstancePtr)
This function runs a self-test on the CAN driver/device.
The test resets the device, sets up the Loop Back mode, sends a standard frame, receives the frame, verifies the contents, and resets the device again.Note that this is a destructive test in that resets of the device are performed. Refer to the device specification for the device status after the reset operation. InstancePtr is a pointer to the XCan instance to be worked on. XST_SUCCESS if the self-test passed. i.e., the frame received via the internal loop back has the same contents as the sent frame. XST_FAILURE Otherwise. If the CAN device does not work properly, this function may enter an infinite loop and will never return to the caller. If XST_FAILURE is returned, the device is not reset so that the caller could have a chance to check reason(s) causing the failure.
References XCan::IsReady, TEST_CAN_DLC, TEST_MESSAGE_ID, XCan_CreateDlcValue, XCan_CreateIdValue, XCan_EnterMode, XCan_GetMode, XCan_IsRxEmpty, XCAN_MAX_FRAME_SIZE_IN_WORDS, XCAN_MODE_CONFIG, XCAN_MODE_LOOPBACK, XCan_Recv, XCan_Reset, XCan_Send, XCan_SetBaudRatePrescaler, XCan_SetBitTiming.
Referenced by main, XCanPolledExample.
void XCan_InterruptEnable(XCan *InstancePtr, u32 Mask)
This routine enables interrupt(s).
Use the XCAN_IXR_* constants defined in xcan_l.h to create the bit-mask to enable interrupts. InstancePtr is a pointer to the XCan instance to be worked on. Mask is the mask to enable. Bit positions of 1 will be enabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XCAN_IXR_* bits defined in xcan_l.h. None. None.
References XCan::BaseAddress, XCan::IsReady, XCAN_IER_OFFSET, XCan_WriteReg.
Referenced by main.
void XCan_InterruptDisable(XCan *InstancePtr, u32 Mask)
This routine disables interrupt(s).
Use the XCAN_IXR_* constants defined in xcan_l.h to create the bit-mask to disable interrupt(s). InstancePtr is a pointer to the XCan instance to be worked on. Mask is the mask to disable. Bit positions of 1 will be disabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XCAN_IXR_* bits defined in xcan_l.h. None. None.
References XCan::BaseAddress, XCan::IsReady, XCAN_IER_OFFSET, XCan_InterruptGetEnabled, XCan_WriteReg.
u32 XCan_InterruptGetEnabled(XCan *InstancePtr)
This routine returns enabled interrupt(s).
Use the XCAN_IXR_* constants defined in xcan_l.h to interpret the returned value. InstancePtr is a pointer to the XCan instance to be worked on. Enabled interrupt(s) in a 32-bit format. None.
References XCan::BaseAddress, XCan::IsReady, XCAN_IER_OFFSET, XCan_ReadReg.
Referenced by XCan_InterruptDisable, XCan_IntrHandler.
u32 XCan_InterruptGetStatus(XCan *InstancePtr)
This routine returns interrupt status read from Interrupt Status Register.
Use the XCAN_IXR_* constants defined in xcan_l.h to interpret the returned value. InstancePtr is a pointer to the XCan instance to be worked on. The value stored in Interrupt Status Register. None.
References XCan::BaseAddress, XCan::IsReady, XCAN_ISR_OFFSET, XCan_ReadReg.
Referenced by XCan_GetECCCount, XCan_InterruptClear, XCan_IntrHandler.
void XCan_InterruptClear(XCan *InstancePtr, u32 Mask)
This function clears interrupt(s).
Every bit set in Interrupt Status Register indicates that a specific type of interrupt is occurring, and this function clears one or more interrupts by writing a bit mask to Interrupt Clear Register. InstancePtr is a pointer to the XCan instance to be worked on. Mask is the mask to clear. Bit positions of 1 will be cleared. Bit positions of 0 will not change the previous interrupt status. This mask is formed by OR'ing XCAN_IXR_* bits defined in xcan_l.h. None.
References XCan::BaseAddress, XCan::IsReady, XCAN_ICR_OFFSET, XCan_InterruptGetStatus, XCan_WriteReg.
Referenced by XCan_IntrHandler, XCan_Recv.
void XCan_IntrHandler(void *InstancePtr)
This routine is the interrupt handler for the CAN driver.
This handler reads the interrupt status from the ISR, determines the source of the interrupts, calls according callbacks, and finally clears the interrupts.Application beyond this driver is responsible for providing callbacks to handle interrupts and installing the callbacks using XCan_SetHandler() during initialization phase. An example delivered with this driver demonstrates how this could be done. InstancePtr is a pointer to the XCan instance that just interrupted. None. None.
References XCan::EnableECC, XCan::ErrorHandler, XCan::ErrorRef, XCan::EventHandler, XCan::EventRef, XCan::IsReady, XCan::RecvHandler, XCan::RecvRef, XCan::SendHandler, XCan::SendRef, XCan_ClearBusErrorStatus, XCan_GetBusErrorStatus, XCan_GetECCCount, XCan_InterruptClear, XCan_InterruptGetEnabled, XCan_InterruptGetStatus, XCAN_IXR_ARBLST_MASK, XCAN_IXR_BSOFF_MASK, XCAN_IXR_ECC_MASK, XCAN_IXR_ERROR_MASK, XCAN_IXR_RXNEMP_MASK, XCAN_IXR_RXOFLW_MASK, XCAN_IXR_RXUFLW_MASK, XCAN_IXR_SLP_MASK, XCAN_IXR_TXBFLL_MASK, XCAN_IXR_TXFLL_MASK, XCAN_IXR_TXOK_MASK, XCAN_IXR_WKUP_MASK, XCan_ResetECC.
Referenced by main.
int XCan_SetHandler(XCan *InstancePtr, u32 HandlerType, void *CallBackFunc, void *CallBackRef)
This routine installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function Type ----------------------- --------------------------- XCAN_HANDLER_SEND XCan_SendRecvHandler XCAN_HANDLER_RECV XCan_SendRecvHandler XCAN_HANDLER_ERROR XCan_ErrorHandler XCAN_HANDLER_EVENT XCan_EventHandlerHandlerType Invoked by this driver when: ----------------------- -------------------------------------------------- XCAN_HANDLER_SEND A frame transmitted by a call to XCan_Send() has been sent successfully.XCAN_HANDLER_RECV A frame has been received and is sitting in the RX FIFO.XCAN_HANDLER_ERROR An error interrupt is occurring.XCAN_HANDLER_EVENT Any other kind of interrupt is occurring. InstancePtr is a pointer to the XCan instance to be worked on. HandlerType specifies which handler is to be attached. CallBackFunc is the address of the callback function. CallBackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS when handler is installed.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XCan::ErrorHandler, XCan::ErrorRef, XCan::EventHandler, XCan::EventRef, XCan::IsReady, XCan::RecvHandler, XCan::RecvRef, XCan::SendHandler, XCan::SendRef, XCAN_HANDLER_ERROR, XCAN_HANDLER_EVENT, XCAN_HANDLER_RECV, XCAN_HANDLER_SEND.
Referenced by main.
XCAN_H
by using protection macros
XCan_IsTxDone
This macro checks if the transmission is complete.
InstancePtr is a pointer to the XCan instance to be worked on. TRUE if the transmission is done (completed).FALSE if the transmission is not completed. C-Style signature: int XCan_IsTxDone(XCan *InstancePtr);
XCan_IsTxFifoFull
This macro checks if the transmission FIFO is full.
InstancePtr is a pointer to the XCan instance to be worked on. TRUE if TX FIFO is full.FALSE if TX FIFO is not full. C-Style signature: int XCan_IsTxFifoFull(XCan *InstancePtr);
Referenced by main, XCan_Send.
XCan_IsHighPriorityBufFull
This macro checks if the Transmission High Priority Buffer is full.
InstancePtr is a pointer to the XCan instance to be worked on. TRUE if TX High Priority Buffer is full.FALSE if TX High Priority Buffer is not full. C-Style signature: int XCan_IsHighPriorityBufFull(XCan *InstancePtr);
Referenced by XCan_SendHighPriority.
XCan_IsRxEmpty
This macro checks if the receive FIFO is empty.
InstancePtr is a pointer to the XCan instance to be worked on. TRUE if RX FIFO is empty.FALSE if RX FIFO is not empty. C-Style signature: int XCan_IsRxEmpty(XCan *InstancePtr);
Referenced by XCan_Recv, XCan_SelfTest.
XCan_IsAcceptFilterBusy
This macro checks if the CAN device is ready for the driver to change Acceptance Filter Identifier Registers (AFIR) and Acceptance Filter Mask Registers (AFMR).
AFIR and AFMR for a filter are changeable only after the filter is disabled and this routine returns FALSE. InstancePtr is a pointer to the XCan instance to be worked on. TRUE if the device is busy and NOT ready to accept writes to AFIR and AFMR.FALSE if the device is ready to accept writes to AFIR and AFMR. C-Style signature: int XCan_IsAcceptFilterBusy(XCan *InstancePtr);
Referenced by XCan_AcceptFilterSet.
XCan_CreateIdValue
This macro calculates CAN message identifier value given identifier field values.
StandardId contains Standard Message ID value. SubRemoteTransReq contains Substitute Remote Transmission Request value. IdExtension contains Identifier Extension value. ExtendedId contains Extended Message ID value. RemoteTransReq contains Remote Transmission Request value. Message Identifier value. C-Style signature: u32 XCan_CreateIdValue(u32 StandardId, u32 SubRemoteTransReq, u32 IdExtension, u32 ExtendedId, u32 RemoteTransReq); Read the CAN specification for meaning of each parameter.
Referenced by main, XCan_SelfTest.
XCan_CreateDlcValue
This macro calculates value for Data Length Code register given Data Length Code value.
DataLengCode indicates Data Length Code value. Value that can be assigned to Data Length Code register. C-Style signature: u32 XCan_CreateDlcValue(u32 DataLengCode); Read the CAN specification for meaning of Data Length Code.
Referenced by main, XCan_SelfTest.
XCAN_L_H
by using protection macros
XCan_ReadReg
This macro reads the given register.
BaseAddress is the base address of the device RegOffset is the register offset to be read The 32-bit value of the register C-Style signature: u32 XCan_ReadReg(u32 BaseAddress, u32 RegOffset);
Referenced by XCan_AcceptFilterDisable, XCan_AcceptFilterEnable, XCan_AcceptFilterGet, XCan_AcceptFilterGetEnabled, XCan_GetBaudRatePrescaler, XCan_GetBitTiming, XCan_GetBusErrorCounter, XCan_GetBusErrorStatus, XCan_GetECCCount, XCan_GetStatus, XCan_InterruptGetEnabled, XCan_InterruptGetStatus, XCan_Recv.
XCan_WriteReg
This macro writes the given register.
BaseAddress is the base address of the device RegOffset is the register offset to be written Data is the 32-bit value to write to the register None. C-Style signature: u32 XCan_WriteReg(u32 BaseAddress, u32 RegOffset, u32 Data);
Referenced by XCan_AcceptFilterDisable, XCan_AcceptFilterEnable, XCan_AcceptFilterSet, XCan_ClearBusErrorStatus, XCan_EnterMode, XCan_InterruptClear, XCan_InterruptDisable, XCan_InterruptEnable, XCan_Reset, XCan_ResetECC, XCan_Send, XCan_SendHighPriority, XCan_SetBaudRatePrescaler, XCan_SetBitTiming.
XCAN_MAX_FRAME_SIZE_IN_WORDS
Max Frame Size.
Referenced by XCan_SelfTest.
TEST_MESSAGE_ID
Message ID.
Referenced by main, XCan_SelfTest.
TEST_CAN_DLC
DLC length.
Referenced by XCan_SelfTest.