xcan.c
XCan_Config XCan_ConfigTable[][]
This table contains configuration information for each CAN device in the system.
static void Initialize(XCan *InstancePtr, XCan_Config *ConfigPtr)
This function initializes a XCan instance/driver.
This function is utilized by XCan_Initialize() or XCan_VmInitialize(), depending on if Virtual Memory support is wanted or not.The initialization entails: Initialize all members of the XCan structure, except BaseAddress. BaseAddress should be taken care of by XCan_Initialize() or XCan_VmInitialize(), before they call this function.Reset the CAN device. The CAN device will enter Configuration Mode immediately after the reset is finished. InstancePtr is a pointer to the XCan instance to be worked on. ConfigPtr points to the a configuration structure the XCan instance should be associated with. None. None.
static void StubHandler(void)
This routine is a stub for the asynchronous callbacks.
The stub is here in case the upper layer forgot to set the handler(s). On initialization, all handlers are set to this callback. It is considered an error for this handler to be invoked.None. None.
int XCan_Initialize(XCan *InstancePtr, UINTPTR BaseAddress)
This routine initializes a specific XCan instance/driver.
This function should only be used when no Virtual Memory support is needed. To use virtual memory, the caller should invoke XCan_VmInitialize(). See the description of XCan_VmInitialize() for detailed information.This initialization entails: Search for device configuration based on the unique device ID/BaseAddress.Initialize Base Address field of the XCan structure using the device address in the found device configuration.Populate all other data fields in the XCan structureReset the device. InstancePtr is a pointer to the XCan instance to be worked on. BaseAddress contains the base address of the device XST_SUCCESS if initialization was successfulXST_DEVICE_NOT_FOUND if device configuration information was not found for a device with the supplied device ID/BaseAddress. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XCan_Config::BaseAddress, XCan::BaseAddress, XCan_LookupConfig.
Referenced by main, XCanPolledExample.
int XCan_VmInitialize(XCan *InstancePtr, UINTPTR BaseAddress, UINTPTR VirtAddr)
This routine initializes of a specific XCan instance/driver.
This function should only be used if Virtual Memory support is necessary. The caller is responsible for calculating the correct device base address in Virtual memory address space and passing it into this function.This initialization entails: Search for device configuration based on the unique device ID/BaseAddress.Initialize Base Address field of the XCan structure using the given virtual address parameter value.Populate all other data fields in the XCan structure.Reset the device. InstancePtr is a pointer to the XCan instance to be worked on. BaseAddress contains the base address of the device VirtAddr is the device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from VirtAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. XST_SUCCESS if initialization was successfulXST_DEVICE_NOT_FOUND if device configuration information was not found for a device with the supplied device ID/BaseAddress. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XCan::BaseAddress, XCan_LookupConfig.
void XCan_Reset(XCan *InstancePtr)
This function resets the CAN device.
Calling this function resets the device immediately, and any pending transmission or reception is terminated at once. Both Object Layer and Transfer Layer are reset. This function does not reset the Physical Layer. All registers are reset to the default values, and no previous status will be restored. TX FIFO, RX FIFO and TX High Priority Buffer are also reset.When a reset is required due to an internal error, the driver notifies the upper layer software of this need through the error status code or interrupts The upper layer software is responsible for calling this Reset function and then re-configuring the device.The CAN device will be in Configuration Mode immediately after this function returns. InstancePtr is a pointer to the XCan instance to be worked on. None. None.
References XCan::BaseAddress, XCan::IsReady, XCAN_SRR_OFFSET, XCAN_SRR_SRST_MASK, XCan_WriteReg.
Referenced by main, XCan_SelfTest.
u8 XCan_GetMode(XCan *InstancePtr)
This routine returns current operation mode the CAN device is in.
InstancePtr is a pointer to the XCan instance to be worked on. XCAN_MODE_CONFIG if the device is in Configuration Mode.XCAN_MODE_SLEEP if the device is in Sleep Mode.XCAN_MODE_NORMAL if the device is in Normal Mode.XCAN_MODE_LOOPBACK if the device is in Loop Back Mode. None.
References XCan::IsReady, XCan_GetStatus, XCAN_MODE_CONFIG, XCAN_MODE_LOOPBACK, XCAN_MODE_NORMAL, XCAN_MODE_SLEEP, XCAN_SR_CONFIG_MASK, XCAN_SR_NORMAL_MASK, XCAN_SR_SLEEP_MASK.
Referenced by main, XCan_EnterMode, XCan_SelfTest, XCan_SetBaudRatePrescaler, XCan_SetBitTiming, XCanPolledExample.
void XCan_EnterMode(XCan *InstancePtr, u8 OperationMode)
This function allows the CAN device to enter one of the following operation modes:
Configuration Mode: Pass in parameter XCAN_MODE_CONFIGSleep Mode: Pass in parameter XCAN_MODE_SLEEPNormal Mode: Pass in parameter XCAN_MODE_NORMALLoop Back Mode: Pass in parameter XCAN_MODE_LOOPBACK. Read xcan.h and device specification for detailed description of each operation mode. InstancePtr is a pointer to the XCan instance to be worked on. OperationMode specify which operation mode to enter. Valid value is any of XCAN_MODE_* defined in xcan.h. Please note no multiple modes could be entered at the same time. None. This function does NOT ensure CAN device enters the specified operation mode before returns the control to the caller. The caller is responsible for checking current operation mode using XCan_GetMode().
References XCan::BaseAddress, XCan::IsReady, XCan_GetMode, XCAN_MODE_CONFIG, XCAN_MODE_LOOPBACK, XCAN_MODE_NORMAL, XCAN_MODE_SLEEP, XCAN_MSR_LBACK_MASK, XCAN_MSR_OFFSET, XCAN_MSR_SLEEP_MASK, XCAN_SRR_CEN_MASK, XCAN_SRR_OFFSET, XCan_WriteReg.
Referenced by main, XCan_SelfTest, XCanPolledExample.
u32 XCan_GetStatus(XCan *InstancePtr)
This function returns Status value from Status Register (SR).
Use the XCAN_SR_* constants defined in xcan_l.h to interpret the returned value. InstancePtr is a pointer to the XCan instance to be worked on. The 32-bit value read from Status Register. None.
References XCan::BaseAddress, XCan::IsReady, XCan_ReadReg, XCAN_SR_OFFSET.
Referenced by XCan_GetMode.
void XCan_GetBusErrorCounter(XCan *InstancePtr, u8 *RxErrorCount, u8 *TxErrorCount)
This function reads Receive and Transmit error counters.
InstancePtr is a pointer to the XCan instance to be worked on. RxErrorCount will contain Receive Error Counter value after this function returns. TxErrorCount will contain Transmit Error Counter value after this function returns. None. None.
References XCan::BaseAddress, XCan::IsReady, XCAN_ECR_OFFSET, XCAN_ECR_REC_MASK, XCAN_ECR_REC_SHIFT, XCAN_ECR_TEC_MASK, XCan_ReadReg.
u32 XCan_GetBusErrorStatus(XCan *InstancePtr)
This function reads Error Status value from Error Status Register (ESR).
Use the XCAN_ESR_* constants defined in xcan_l.h to interpret the returned value. InstancePtr is a pointer to the XCan instance to be worked on. The 32-bit value read from Error Status Register. None.
References XCan::BaseAddress, XCan::IsReady, XCAN_ESR_OFFSET, XCan_ReadReg.
Referenced by XCan_IntrHandler.
void XCan_ClearBusErrorStatus(XCan *InstancePtr, u32 Mask)
This function clears Error Status bit(s) previously set in Error Status Register (ESR).
Use the XCAN_ESR_* constants defined in xcan_l.h to create the value to pass in. If a bit was cleared in Error Status Register before this function is called, it will not be touched. InstancePtr is a pointer to the XCan instance to be worked on. Mask is he 32-bit mask used to clear bits in Error Status Register. Multiple XCAN_ESR_* values could be 'OR'ed to clear multiple bits None.
References XCan::BaseAddress, XCan::IsReady, XCAN_ESR_OFFSET, XCan_WriteReg.
Referenced by XCan_IntrHandler.
int XCan_Send(XCan *InstancePtr, u32 *FramePtr)
This function sends a CAN Frame.
This function first checks if TX FIFO is full. If not, it then writes the given frame into the TX FIFO; otherwise, it returns error code immediately. This function does not wait for the given frame being sent to CAN bus. InstancePtr is a pointer to the XCan instance to be worked on. FramePtr is a pointer to a 32-bit aligned buffer containing the CAN frame to be sent. XST_SUCCESS if TX FIFO was not full and the given frame was written into the FIFO;XST_FIFO_NO_ROOM if there is no room in the TX FIFO for the given frame None.
References XCan::BaseAddress, XCan::IsReady, XCan_IsTxFifoFull, XCAN_TXFIFO_DLC_OFFSET, XCAN_TXFIFO_DW1_OFFSET, XCAN_TXFIFO_DW2_OFFSET, XCAN_TXFIFO_ID_OFFSET, XCan_WriteReg.
Referenced by main, XCan_SelfTest.
int XCan_Recv(XCan *InstancePtr, u32 *FramePtr)
This function receives a CAN Frame.
This function first checks if RX FIFO is empty, if not, it then reads a frame from the RX FIFO into the given buffer. This function returns error code immediately if there is no frame in the RX FIFO. InstancePtr is a pointer to the XCan instance to be worked on. FramePtr is a pointer to a 32-bit aligned buffer where the CAN frame to be written. XST_SUCCESS if RX FIFO was not empty and a frame was read from RX FIFO successfully and written into the given buffer;XST_NO_DATA if there is no frame to be received from the FIFO None.
References XCan::BaseAddress, XCan::IsReady, XCan_InterruptClear, XCan_IsRxEmpty, XCAN_IXR_RXNEMP_MASK, XCan_ReadReg, XCAN_RXFIFO_DLC_OFFSET, XCAN_RXFIFO_DW1_OFFSET, XCAN_RXFIFO_DW2_OFFSET, XCAN_RXFIFO_ID_OFFSET.
Referenced by main, XCan_SelfTest.
int XCan_SendHighPriority(XCan *InstancePtr, u32 *FramePtr)
This routine sends a CAN High Priority frame.
This function first checks if TX High Priority Buffer is empty. If yes, it then writes the given frame into the Buffer. If not, This function returns immediately. This function does not wait for the given frame being sent to CAN bus. InstancePtr is a pointer to the XCan instance to be worked on. FramePtr is a pointer to a 32-bit aligned buffer containing the CAN High Priority frame to be sent. XST_SUCCESS if TX High Priority Buffer was not full and the given frame was written into the buffer;XST_FIFO_NO_ROOM if there is no room in the TX High Priority Buffer for this frame. If the frame needs to be sent immediately and not delayed by processor's interrupts handling, the caller should disable interrupt at processor level before invoking this function.
References XCan::BaseAddress, XCan::IsReady, XCan_IsHighPriorityBufFull, XCAN_TXBUF_DLC_OFFSET, XCAN_TXBUF_DW1_OFFSET, XCAN_TXBUF_DW2_OFFSET, XCAN_TXBUF_ID_OFFSET, XCan_WriteReg.
void XCan_AcceptFilterEnable(XCan *InstancePtr, u32 FilterIndexes)
This routine enables individual acceptance filters.
Up to 4 filters could be enabled. InstancePtr is a pointer to the XCan instance to be worked on. FilterIndexes specifies which filter(s) to enable. Use any XCAN_AFR_UAF*_MASK to enable one filter, and "Or" multiple XCAN_AFR_UAF*_MASK values if multiple filters need to be enabled. Any filter not specified in this parameter will keep its previous enable/disable setting. None. Acceptance Filter Register is an optional register in Xilinx CAN device. If it is NOT existing in the device, this function should NOT be used. Calling this function in this case will cause an assertion failure.
References XCan::BaseAddress, XCan::IsReady, XCan::NumOfAcceptFilters, XCAN_AFR_OFFSET, XCAN_AFR_UAF_ALL_MASK, XCan_ReadReg, XCan_WriteReg.
void XCan_AcceptFilterDisable(XCan *InstancePtr, u32 FilterIndexes)
This routine disables individual acceptance filters.
Up to 4 filters could be disabled. If all acceptance filters are disabled then all received frames are stored in the RX FIFO. InstancePtr is a pointer to the XCan instance to be worked on. FilterIndexes specifies which filter(s) to disable. Use any XCAN_AFR_UAF*_MASK to disable one filter, and "Or" multiple XCAN_AFR_UAF*_MASK values if multiple filters need to be disabled. Any filter not specified in this parameter will keep its previous enable/disable setting. If all acceptance filters are disabled then all received frames are stored in the RX FIFO. None. Acceptance Filter Register is an optional register in Xilinx CAN device. If it is NOT existing in the device, this function should NOT be used. Calling this function in this case will cause an assertion failure.
References XCan::BaseAddress, XCan::IsReady, XCan::NumOfAcceptFilters, XCAN_AFR_OFFSET, XCAN_AFR_UAF_ALL_MASK, XCan_ReadReg, XCan_WriteReg.
u32 XCan_AcceptFilterGetEnabled(XCan *InstancePtr)
This function returns enabled acceptance filters.
Use XCAN_AFR_UAF*_MASK defined in xcan_l.h to interpret the returned value. If no acceptance filters are enabled then all received frames are stored in the RX FIFO. InstancePtr is a pointer to the XCan instance to be worked on. The value stored in Acceptance Filter Register. Acceptance Filter Register is an optional register in Xilinx CAN device. If it is NOT existing in the device, this function should NOT be used. Calling this function in this case will cause an assertion failure.
References XCan::BaseAddress, XCan::IsReady, XCan::NumOfAcceptFilters, XCAN_AFR_OFFSET, XCan_ReadReg.
Referenced by XCan_AcceptFilterSet.
int XCan_AcceptFilterSet(XCan *InstancePtr, u32 FilterIndex, u32 MaskValue, u32 IdValue)
This function sets values to the Acceptance Filter Mask Register (AFMR) and Acceptance Filter ID Register (AFIR) for the specified Acceptance Filter.
Use XCAN_IDR_* defined in xcan_l.h to create the values to set the filter. Read xcan.h and device specification for details.This function should be called only after: The given filter is disabled by calling XCan_AcceptFilterDisable();And the CAN device is ready to accept writes to AFMR and AFIR, i.e., XCan_IsAcceptFilterBusy() returns FALSE. InstancePtr is a pointer to the XCan instance to be worked on. FilterIndex defines which Acceptance Filter Mask and ID Register to set. Use any single XCAN_AFR_UAF*_MASK value. MaskValue is the value to write to the chosen Acceptance Filter Mask Register. IdValue is the value to write to the chosen Acceptance Filter ID Register. XST_SUCCESS if the values were set successfully.XST_FAILURE if the given filter was not disabled, or the CAN device was not ready to accept writes to AFMR and AFIR. Acceptance Filter Mask and ID Registers are optional registers in Xilinx CAN device. If they are NOT existing in the device, this function should NOT be used. Calling this function in this case will cause an assertion failure.
References XCan::BaseAddress, XCan::IsReady, XCan::NumOfAcceptFilters, XCan_AcceptFilterGetEnabled, XCAN_AFIR1_OFFSET, XCAN_AFIR2_OFFSET, XCAN_AFIR3_OFFSET, XCAN_AFIR4_OFFSET, XCAN_AFMR1_OFFSET, XCAN_AFMR2_OFFSET, XCAN_AFMR3_OFFSET, XCAN_AFMR4_OFFSET, XCAN_AFR_UAF1_MASK, XCAN_AFR_UAF2_MASK, XCAN_AFR_UAF3_MASK, XCAN_AFR_UAF4_MASK, XCan_IsAcceptFilterBusy, XCan_WriteReg.
void XCan_AcceptFilterGet(XCan *InstancePtr, u32 FilterIndex, u32 *MaskValue, u32 *IdValue)
This function reads the values of the Acceptance Filter Mask and ID Register for the specified Acceptance Filter.
Use XCAN_IDR_* defined in xcan_l.h to interpret the values. Read xcan.h and device specification for details. InstancePtr is a pointer to the XCan instance to be worked on. FilterIndex defines which Acceptance Filter Mask Register to get Mask and ID from. Use any single XCAN_FILTER_* value. MaskValue will store the Mask value read from the chosen Acceptance Filter Mask Register after this function returns. IdValue will store the ID value read from the chosen Acceptance Filter ID Register after this function returns. None. Acceptance Filter Mask and ID Registers are optional registers in Xilinx CAN device. If they are NOT existing in the device, this function should NOT be used. Calling this function in this case will cause an assertion failure.
References XCan::BaseAddress, XCan::IsReady, XCan::NumOfAcceptFilters, XCAN_AFIR1_OFFSET, XCAN_AFIR2_OFFSET, XCAN_AFIR3_OFFSET, XCAN_AFIR4_OFFSET, XCAN_AFMR1_OFFSET, XCAN_AFMR2_OFFSET, XCAN_AFMR3_OFFSET, XCAN_AFMR4_OFFSET, XCAN_AFR_UAF1_MASK, XCAN_AFR_UAF2_MASK, XCAN_AFR_UAF3_MASK, XCAN_AFR_UAF4_MASK, XCan_ReadReg.
XCan_Config * XCan_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XCan_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xcan.h for the definition of XCan_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XCan_Config::Name.
Referenced by main, XCan_Initialize, XCan_VmInitialize.
XCan_Config * XCan_GetConfig(unsigned int InstanceIndex)
This function looks for the device configuration based on the device index.
The table XCan_ConfigTable[] contains the configuration information for each device in the system. InstanceIndex is a 0-based integer indexing all CAN devices in the system. A pointer to the configuration table entry corresponding to the given device ID, or NULL if no match is found. None.
References XCan_Config::Name.
void XCan_ResetECC(XCan *InstancePtr)
This function resets the ECC counters.
Calling this function resets all the ECC counters immediately. The register is reset to default value, and no previous status will be restored. InstancePtr is a pointer to the XCan instance to be worked on. None. None.
References XCan::BaseAddress, XCan::IsReady, XCAN_ECC_CFG_OFFSET, XCAN_ECC_CFG_RST_MASK, XCan_WriteReg.
Referenced by XCan_IntrHandler.
void XCan_GetECCCount(XCan *InstancePtr)
This function gets the count of ECC error count for one and two bit error in TX_TL FIFO, TX_OL FIFO, RX FIFO.
InstancePtr is a pointer to the XCan instance to be worked on. None. None.
References XCan::BaseAddress, XCan::ecc_1bit_txolfifo_cnt, XCan::ecc_1bit_txtlfifo_cnt, XCan::ecc_2bit_rxfifo_cnt, XCan::ecc_2bit_txolfifo_cnt, XCan::ecc_2bit_txtlfifo_cnt, XCan::IsReady, XCAN_ECC_2BIT_SHIFT, XCan_InterruptGetStatus, XCAN_IXR_E1BERX_MASK, XCAN_IXR_E1BETXOL_MASK, XCAN_IXR_E1BETXTL_MASK, XCAN_IXR_E2BERX_MASK, XCAN_IXR_E2BETXOL_MASK, XCAN_IXR_E2BETXTL_MASK, XCAN_MASK_HIGH_16BITS, XCAN_MASK_LOW_16BITS, XCan_ReadReg, XCAN_RXFIFO_ECC_OFFSET, XCAN_TXOLFIFO_ECC_OFFSET, XCAN_TXTLFIFO_ECC_OFFSET.
Referenced by XCan_IntrHandler.