xcan_intr.c
void XCan_InterruptEnable(XCan *InstancePtr, u32 Mask)
This routine enables interrupt(s).
Use the XCAN_IXR_* constants defined in xcan_l.h to create the bit-mask to enable interrupts. InstancePtr is a pointer to the XCan instance to be worked on. Mask is the mask to enable. Bit positions of 1 will be enabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XCAN_IXR_* bits defined in xcan_l.h. None. None.
References XCan::BaseAddress, XCan::IsReady, XCAN_IER_OFFSET, XCan_WriteReg.
Referenced by main.
void XCan_InterruptDisable(XCan *InstancePtr, u32 Mask)
This routine disables interrupt(s).
Use the XCAN_IXR_* constants defined in xcan_l.h to create the bit-mask to disable interrupt(s). InstancePtr is a pointer to the XCan instance to be worked on. Mask is the mask to disable. Bit positions of 1 will be disabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XCAN_IXR_* bits defined in xcan_l.h. None. None.
References XCan::BaseAddress, XCan::IsReady, XCAN_IER_OFFSET, XCan_InterruptGetEnabled, XCan_WriteReg.
u32 XCan_InterruptGetEnabled(XCan *InstancePtr)
This routine returns enabled interrupt(s).
Use the XCAN_IXR_* constants defined in xcan_l.h to interpret the returned value. InstancePtr is a pointer to the XCan instance to be worked on. Enabled interrupt(s) in a 32-bit format. None.
References XCan::BaseAddress, XCan::IsReady, XCAN_IER_OFFSET, XCan_ReadReg.
Referenced by XCan_InterruptDisable, XCan_IntrHandler.
u32 XCan_InterruptGetStatus(XCan *InstancePtr)
This routine returns interrupt status read from Interrupt Status Register.
Use the XCAN_IXR_* constants defined in xcan_l.h to interpret the returned value. InstancePtr is a pointer to the XCan instance to be worked on. The value stored in Interrupt Status Register. None.
References XCan::BaseAddress, XCan::IsReady, XCAN_ISR_OFFSET, XCan_ReadReg.
Referenced by XCan_GetECCCount, XCan_InterruptClear, XCan_IntrHandler.
void XCan_InterruptClear(XCan *InstancePtr, u32 Mask)
This function clears interrupt(s).
Every bit set in Interrupt Status Register indicates that a specific type of interrupt is occurring, and this function clears one or more interrupts by writing a bit mask to Interrupt Clear Register. InstancePtr is a pointer to the XCan instance to be worked on. Mask is the mask to clear. Bit positions of 1 will be cleared. Bit positions of 0 will not change the previous interrupt status. This mask is formed by OR'ing XCAN_IXR_* bits defined in xcan_l.h. None.
References XCan::BaseAddress, XCan::IsReady, XCAN_ICR_OFFSET, XCan_InterruptGetStatus, XCan_WriteReg.
Referenced by XCan_IntrHandler, XCan_Recv.
void XCan_IntrHandler(void *InstancePtr)
This routine is the interrupt handler for the CAN driver.
This handler reads the interrupt status from the ISR, determines the source of the interrupts, calls according callbacks, and finally clears the interrupts.Application beyond this driver is responsible for providing callbacks to handle interrupts and installing the callbacks using XCan_SetHandler() during initialization phase. An example delivered with this driver demonstrates how this could be done. InstancePtr is a pointer to the XCan instance that just interrupted. None. None.
References XCan::EnableECC, XCan::ErrorHandler, XCan::ErrorRef, XCan::EventHandler, XCan::EventRef, XCan::IsReady, XCan::RecvHandler, XCan::RecvRef, XCan::SendHandler, XCan::SendRef, XCan_ClearBusErrorStatus, XCan_GetBusErrorStatus, XCan_GetECCCount, XCan_InterruptClear, XCan_InterruptGetEnabled, XCan_InterruptGetStatus, XCAN_IXR_ARBLST_MASK, XCAN_IXR_BSOFF_MASK, XCAN_IXR_ECC_MASK, XCAN_IXR_ERROR_MASK, XCAN_IXR_RXNEMP_MASK, XCAN_IXR_RXOFLW_MASK, XCAN_IXR_RXUFLW_MASK, XCAN_IXR_SLP_MASK, XCAN_IXR_TXBFLL_MASK, XCAN_IXR_TXFLL_MASK, XCAN_IXR_TXOK_MASK, XCAN_IXR_WKUP_MASK, XCan_ResetECC.
Referenced by main.
int XCan_SetHandler(XCan *InstancePtr, u32 HandlerType, void *CallBackFunc, void *CallBackRef)
This routine installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function Type ----------------------- --------------------------- XCAN_HANDLER_SEND XCan_SendRecvHandler XCAN_HANDLER_RECV XCan_SendRecvHandler XCAN_HANDLER_ERROR XCan_ErrorHandler XCAN_HANDLER_EVENT XCan_EventHandlerHandlerType Invoked by this driver when: ----------------------- -------------------------------------------------- XCAN_HANDLER_SEND A frame transmitted by a call to XCan_Send() has been sent successfully.XCAN_HANDLER_RECV A frame has been received and is sitting in the RX FIFO.XCAN_HANDLER_ERROR An error interrupt is occurring.XCAN_HANDLER_EVENT Any other kind of interrupt is occurring. InstancePtr is a pointer to the XCan instance to be worked on. HandlerType specifies which handler is to be attached. CallBackFunc is the address of the callback function. CallBackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS when handler is installed.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XCan::ErrorHandler, XCan::ErrorRef, XCan::EventHandler, XCan::EventRef, XCan::IsReady, XCan::RecvHandler, XCan::RecvRef, XCan::SendHandler, XCan::SendRef, XCAN_HANDLER_ERROR, XCAN_HANDLER_EVENT, XCAN_HANDLER_RECV, XCAN_HANDLER_SEND.
Referenced by main.