xcan_config.c
int XCan_SetBaudRatePrescaler(XCan *InstancePtr, u8 Prescaler)
This routine sets Baud Rate Prescaler value.
The system clock for the CAN controller is divided by (Prescaler + 1) to generate the quantum clock needed for sampling and synchronization. Read the device specification for details.Baud Rate Prescaler could be set only after CAN device entered Configuration Mode. So please call XCan_EnterMode() to enter Configuration Mode before using this function. InstancePtr is a pointer to the XCan instance to be worked on. Prescaler is the value to set. Valid values are from 0 to 255. XST_SUCCESS if the Baud Rate Prescaler value is set successfully.XST_FAILURE if CAN device is not in Configuration Mode. None.
References XCan::BaseAddress, XCan::IsReady, XCAN_BRPR_OFFSET, XCan_GetMode, XCAN_MODE_CONFIG, XCan_WriteReg.
Referenced by main, XCan_SelfTest, XCanPolledExample.
u8 XCan_GetBaudRatePrescaler(XCan *InstancePtr)
This routine gets Baud Rate Prescaler value.
The system clock for the CAN controller is divided by (Prescaler + 1) to generate the quantum clock needed for sampling and synchronization. Read the device specification for details. InstancePtr is a pointer to the XCan instance to be worked on. Current used Baud Rate Prescaler value. The value's range is from 0 to 255. None.
References XCan::BaseAddress, XCan::IsReady, XCAN_BRPR_OFFSET, XCan_ReadReg.
int XCan_SetBitTiming(XCan *InstancePtr, u8 SyncJumpWidth, u8 TimeSegment2, u8 TimeSegment1)
This routine sets Bit time.
Time segment 1, Time segment 2 and Synchronization Jump Width are set in this function. Device specification requires the values passed into this function be one less than the actual values of these fields. Read the device specification for details.Bit time could be set only after CAN device entered Configuration Mode. Please call XCan_EnterMode() to enter Configuration Mode before using this function. InstancePtr is a pointer to the XCan instance to be worked on. SyncJumpWidth is the Synchronization Jump Width value to set. Valid values are from 0 to 3. TimeSegment2 is the Time Segment 2 value to set. Valid values are from 0 to 7. TimeSegment1 is the Time Segment 1 value to set. Valid values are from 0 to 15. XST_SUCCESS if the Bit time is set successfully.XST_FAILURE if CAN device is not in Configuration Mode. XST_INVALID_PARAM if any value of SyncJumpWidth, TimeSegment2 and TimeSegment1 is invalid. None.
References XCan::BaseAddress, XCan::IsReady, XCAN_BTR_OFFSET, XCAN_BTR_SJW_MASK, XCAN_BTR_SJW_SHIFT, XCAN_BTR_TS1_MASK, XCAN_BTR_TS2_MASK, XCAN_BTR_TS2_SHIFT, XCan_GetMode, XCAN_MODE_CONFIG, XCan_WriteReg.
Referenced by main, XCan_SelfTest, XCanPolledExample.
void XCan_GetBitTiming(XCan *InstancePtr, u8 *SyncJumpWidth, u8 *TimeSegment2, u8 *TimeSegment1)
This routine gets Bit time.
Time segment 1, Time segment 2 and Synchronization Jump Width values are read in this function. According to device specification, the actual value of each of these fields is one more than the value read. Read the device specification for details. InstancePtr is a pointer to the XCan instance to be worked on. SyncJumpWidth will store the Synchronization Jump Width value after this function returns. Its value ranges from 0 to 3. TimeSegment2 will store the Time Segment 2 value after this function returns. Its value ranges from 0 to 7. TimeSegment1 will store the Time Segment 1 value after this function returns. Its value ranges from 0 to 15. None. None.
References XCan::BaseAddress, XCan::IsReady, XCAN_BTR_OFFSET, XCAN_BTR_SJW_MASK, XCAN_BTR_SJW_SHIFT, XCAN_BTR_TS1_MASK, XCAN_BTR_TS2_MASK, XCAN_BTR_TS2_SHIFT, XCan_ReadReg.