xi3cpsx.c
s32 XI3cPsx_CfgInitialize(XI3cPsx *InstancePtr, XI3cPsx_Config *ConfigPtr, u32 EffectiveAddr)
Initializes a specific XI3cPsx instance such that the driver is ready to use.
InstancePtr is a pointer to the XI3cPsx instance. ConfigPtr is a reference to a structure containing information about a specific I3C device. This function initializes an InstancePtr object for a specific device specified by the contents of Config. EffectiveAddr is the device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, use ConfigPtr->BaseAddress for this parameter, passing the physical address instead. XST_SUCCESS if successful. XST_DEVICE_IS_STARTED if the instance is already initialized. XST_FAILURE if SCL clock programming or bus initialization fails (master mode only). None.
References XI3cPsx_Config::BaseAddress, XI3cPsx::Config, XI3cPsx_Config::DeviceCount, XI3cPsx_Config::InputClockHz, XI3cPsx::IsReady, XI3cPsx::SclkHz, XI3cPsx_BusInit, XI3cPsx_Reset, XI3cPsx_ResetFifos, XI3cPsx_SetSClk.
Referenced by I3cPsxMasterIntrExample, I3cPsxMasterPolledExample, I3cPsxSlaveLoopbackExample.
void XI3cPsx_WrTxFifo(XI3cPsx *InstancePtr, u32 *TxBuf, u16 TxLen)
Fill I3CPsx Write Tx FIFO.
InstancePtr is a pointer to the XI3cPsx instance. TxBuf is the pointer to the send buffer. TxLen is the number of bytes to be sent. None. None.
References XI3cPsx_Config::BaseAddress, XI3cPsx::Config, XI3cPsx::SendBufferPtr, XI3cPsx::SendByteCount, XI3CPSX_TX_RX_DATA_PORT, XI3cPsx_WriteReg.
Referenced by XI3cPsx_MasterInterruptHandler, XI3cPsx_MasterSend, XI3cPsx_MasterSendPolled, XI3cPsx_SlaveSendPolled.
void XI3cPsx_WrCmdFifo(XI3cPsx *InstancePtr, XI3cPsx_Cmd *Cmd)
Fill I3CPsx Command FIFO.
InstancePtr is a pointer to the XI3cPsx instance. Cmd is a pointer to the XI3cPsx_Cmd structure. None. None.
References XI3cPsx_Config::BaseAddress, XI3cPsx::Config, XI3CPSX_COMMAND_QUEUE_PORT, XI3cPsx_WriteReg.
Referenced by XI3cPsx_MasterRecv, XI3cPsx_MasterRecvPolled, XI3cPsx_MasterSend, XI3cPsx_MasterSendPolled, XI3cPsx_SlaveSendPolled.
void XI3cPsx_RdRxFifo(XI3cPsx *InstancePtr, u32 *RxBuf, u16 RxLen)
Read I3CPsx Rx FIFO.
InstancePtr is a pointer to the XI3cPsx instance. RxBuf is the pointer to the recv buffer. RxLen is the number of bytes to be recv. None. None.
References XI3cPsx_Config::BaseAddress, XI3cPsx::Config, XI3cPsx::RecvBufferPtr, XI3cPsx::RecvByteCount, XI3cPsx_ReadReg, XI3CPSX_TX_RX_DATA_PORT.
Referenced by XI3cPsx_MasterInterruptHandler, XI3cPsx_MasterRecvPolled, XI3cPsx_SlaveRecvPolled.
s32 XI3cPsx_SendTransferCmd(XI3cPsx *InstancePtr, struct CmdInfo *CmdCCC)
This function sends the transfer command.
InstancePtr is a pointer to the XI3cPsx instance. CmdCCC is a pointer to the Command Info. XST_SUCCESS if everything went well.XST_FAILURE if any error.
References XI3cPsx_MasterRecvPolled, XI3cPsx_MasterSendPolled.
Referenced by XI3cPsx_BusInit.
s32 XI3cPsx_SendAddrAssignCmd(XI3cPsx *InstancePtr, struct CmdInfo *CmdCCC)
This function sends the Address Assignment command.
InstancePtr is a pointer to the XI3cPsx instance. CmdCCC is a pointer to the Command Info. XST_SUCCESS if everything went well.XST_FAILURE if any error.
References XI3cPsx::Config, XI3cPsx_Config::DeviceCount, XI3cPsx_MasterSendPolled.
Referenced by XI3cPsx_BusInit.