xi3cpsx_master.c
TX_MAX_LOOPCNT
Used to wait in polled function.
typedef char XI3cPsx_DynaAddrListSizeCheck[(XI3CPSX_ARRAY_SIZE(XI3C_DynaAddrList)==XI3CPSX_MAX_DAT_ENTRIES)?1:-1][(XI3CPSX_ARRAY_SIZE(XI3C_DynaAddrList)==XI3CPSX_MAX_DAT_ENTRIES)?1:-1]
const u32 XI3C_DynaAddrList[XI3CPSX_MAX_DAT_ENTRIES]
Dynamic addresses available for I3C devices.
Referenced by XI3cPsx_BusInit.
static s32 XI3cPsx_SetDynamicAddr(XI3cPsx *InstancePtr, const u32 *Addr, u32 Devices)
This function sends dynamic Address Assignment for available devices.
InstancePtr is a pointer to the XI3cPsx instance. Addr is an array of dynamic addresses. Devices is the number of slave devices present. XST_SUCCESS if everything went well.XST_FAILURE if any error. None.
s32 XI3cPsx_BusInit(XI3cPsx *InstancePtr)
Initializes the I3c bus by configuring the device address table, resets and assigns the dynamic address to the slave devices.
InstancePtr is a pointer to the XI3cPsx instance. XST_SUCCESS if everything went well.XST_FAILURE if any error. SCL timing must be programmed before calling this function. Call XI3cPsx_SetSClk() or XI3cPsx_SetSClkRate() first so that the RSTDAA and ENTDAA bus transactions issued here run at the intended clock rate. XI3cPsx_CfgInitialize() handles this sequence automatically; callers invoking XI3cPsx_BusInit() directly are responsible for calling XI3cPsx_SetSClk() first.
References XI3cPsx_Config::BaseAddress, XI3cPsx::Config, XI3cPsx_Config::DeviceCount, XI3C_DynaAddrList, XI3CPSX_DEVICE_ADDR, XI3cPsx_SendAddrAssignCmd, XI3cPsx_SendTransferCmd, XI3cPsx_WriteReg.
Referenced by XI3cPsx_CfgInitialize.
s32 XI3cPsx_MasterSend(XI3cPsx *InstancePtr, u8 *MsgPtr, s32 ByteCount, XI3cPsx_Cmd Cmds)
This function initiates an interrupt-driven send in master mode.
It tries to send the first FIFO-full of data, then lets the interrupt handler to handle the rest of the data if there is any. InstancePtr is a pointer to the XI3cPsx instance. MsgPtr is the pointer to the send buffer. ByteCount is the number of bytes to be sent. Cmds is the instance of XI3cPsx_Cmd. XST_SUCCESS if everything went well. This send routine is for interrupt-driven transfer only.
References XI3cPsx_Config::BaseAddress, XI3cPsx::Config, XI3cPsx::SendBufferPtr, XI3cPsx::SendByteCount, XI3cPsx_EnableInterrupts, XI3CPSX_INTR_RESP_READY, XI3CPSX_INTR_TX_THLD, XI3cPsx_WrCmdFifo, XI3cPsx_WrFifoLevel, XI3cPsx_WrTxFifo.
Referenced by I3cPsxMasterIntrExample.
s32 XI3cPsx_MasterRecv(XI3cPsx *InstancePtr, u8 *MsgPtr, s32 ByteCount, XI3cPsx_Cmd *Cmds)
This function initiates an interrupt-driven receive in master mode.
It sets the transfer size register so the slave can send data to us. The rest of the work is managed by interrupt handler. InstancePtr is a pointer to the XI3cPsx instance. MsgPtr is the pointer to the receive buffer. ByteCount is the number of bytes to be received. Cmds is a pointer to the XI3cPsx_Cmd instance. XST_SUCCESS if everything went well.XST_FAILURE if any error. This receive routine is for interrupt-driven transfer only.
References XI3cPsx_Config::BaseAddress, XI3cPsx::Config, XI3cPsx::RecvBufferPtr, XI3cPsx::RecvByteCount, XI3cPsx_EnableInterrupts, XI3CPSX_INTR_RESP_READY, XI3CPSX_INTR_RX_THLD, XI3cPsx_WrCmdFifo.
Referenced by I3cPsxMasterIntrExample.
s32 XI3cPsx_MasterSendPolled(XI3cPsx *InstancePtr, u8 *MsgPtr, s32 ByteCount, XI3cPsx_Cmd Cmds)
This function initiates a polled mode send in master mode.
It sends data to the FIFO and waits for the slave to pick them up. If master fails to send data due arbitration lost, will stop transfer and with arbitration lost status If slave fails to remove data from FIFO, the send fails with time out. InstancePtr is a pointer to the XI3cPsx instance. MsgPtr is the pointer to the send buffer. ByteCount is the number of bytes to be sent. Cmds is a pointer to the XI3cPsx_Cmd instance. XST_SUCCESS if everything went well. This send routine is for polled mode transfer only. All the FIFO operations are in terms of words.
References XI3cPsx_Config::BaseAddress, XI3cPsx::Config, XI3cPsx::SendBufferPtr, XI3cPsx::SendByteCount, XI3cPsx_DisableInterrupts, XI3cPsx_EnableInterrupts, XI3CPSX_INTR_RESP_READY, XI3CPSX_INTR_STATUS, XI3cPsx_ReadReg, XI3cPsx_WrCmdFifo, XI3cPsx_WrFifoLevel, XI3cPsx_WrTxFifo.
Referenced by I3cPsxMasterPolledExample, I3cPsxSlaveLoopbackExample, XI3cPsx_SendAddrAssignCmd, XI3cPsx_SendTransferCmd.
s32 XI3cPsx_MasterRecvPolled(XI3cPsx *InstancePtr, u8 *MsgPtr, s32 ByteCount, XI3cPsx_Cmd *Cmds)
This function initiates a polled mode receive in master mode.
It repeatedly sets the transfer size register so the slave can send data to us. It polls the data register for data to come in. If master fails to read data due arbitration lost, will return with arbitration lost status. If slave fails to send us data, it fails with time out. InstancePtr is a pointer to the XI3cPsx instance. MsgPtr is the pointer to the receive buffer. ByteCount is the number of bytes to be received. Cmds is a pointer to the XI3cPsx_Cmd instance. XST_SUCCESS if everything went well.XST_FAILURE if any error. This receive routine is for polled mode transfer only.
References XI3cPsx_Config::BaseAddress, XI3cPsx::Config, XI3cPsx::RecvBufferPtr, XI3cPsx::RecvByteCount, XI3cPsx_DisableInterrupts, XI3cPsx_EnableInterrupts, XI3CPSX_INTR_RESP_READY, XI3CPSX_INTR_STATUS, XI3cPsx_RdFifoLevel, XI3cPsx_RdRxFifo, XI3cPsx_ReadReg, XI3cPsx_WrCmdFifo.
Referenced by I3cPsxMasterPolledExample, XI3cPsx_SendTransferCmd.
void XI3cPsx_SetStatusHandler(XI3cPsx *InstancePtr, void *CallBackRef, XI3cPsx_IntrHandler FunctionPtr)
This function sets the status handler, which the driver calls when it encounters conditions that should be reported to the higher layer software.
The handler executes in an interrupt context, so the amount of processing should be minimized InstancePtr is a pointer to the XI3c instance. FunctionPtr is the pointer to the callback function. None. The handler is called within interrupt context, so it should finish its work quickly.
References XI3cPsx::CallBackRef, XI3cPsx::IsReady, XI3cPsx::StatusHandler.
Referenced by I3cPsxMasterIntrExample.
void XI3cPsx_MasterInterruptHandler(XI3cPsx *InstancePtr)
The interrupt handler for the master mode.
It does the protocol handling for the interrupt-driven transfers.If the Master is receiving data then the data is read from the FIFO and the Master has to request for more data (if there is more data to receive). If all the data has been received then a completion event is signalled to the upper layer by calling the callback handler. It is an error if the amount of received data is more than expected. InstancePtr is a pointer to the XI3cPsx instance. None. None.
References XI3cPsx_Config::BaseAddress, XI3cPsx::CallBackRef, XI3cPsx::Config, XI3cPsx::IsReady, XI3cPsx::RecvBufferPtr, XI3cPsx::RecvByteCount, XI3cPsx::SendBufferPtr, XI3cPsx::SendByteCount, XI3cPsx::StatusHandler, XI3cPsx_DisableInterrupts, XI3CPSX_INTR_RESP_READY, XI3CPSX_INTR_RX_THLD, XI3CPSX_INTR_STATUS, XI3CPSX_INTR_TX_THLD, XI3cPsx_RdFifoLevel, XI3cPsx_RdRxFifo, XI3cPsx_ReadReg, XI3CPSX_RESPONSE_QUEUE_PORT, XI3cPsx_WrFifoLevel, XI3cPsx_WriteReg, XI3cPsx_WrTxFifo.
Referenced by I3cPsxMasterIntrExample.