xi3cpsx.h
XI3CPSX_EVENT_CRC
CRC Event.
XI3CPSX_EVENT_PARITY
Parity Event.
XI3CPSX_EVENT_FRAME
Frame Errors.
XI3CPSX_EVENT_IBA_NACK
IBA NACK.
XI3CPSX_EVENT_ADDRESS_NACK
Address NACK.
XI3CPSX_EVENT_TXOVR_OR_RXUNF
Receive Buffer Underflow or Transmit buffer Overflow.
XI3CPSX_EVENT_TRANSF_ABORT
Transfer abort.
XI3CPSX_EVENT_SLV_WR_NACK
I2C Slave write data NACK.
XI3CPSX_EVENT_PEC
PEC.
XI3CPSX_H
by using protection macros
SENDING_ROLE
name Role constants
These constants are used to pass into the device setup routines to set up the device according to transfer direction.Transfer direction is sending
RECVING_ROLE
Transfer direction is receiving.
XI3CPSX_MAX_TRANSFER_SIZE
Max transfer size.
XI3CPSX_CEIL_DIV
XI3CPSX_WORD_TO_BYTES
XI3CPSX_DATA_LEN
Data length.
XI3CPSX_TRANSFER_ERROR
Error.
XI3CPSX_TIMEOUT_COUNTER
Wait for 2 sec in worst case.
XI3CPSX_MAX_DAT_ENTRIES
Maximum number of entries in the Device Address Table (DAT) supported by the controller and tracked by the driver.
XI3CPSX_ARRAY_SIZE
Compile-time array element count helper.
XI3cPsx_SendByte
Place one byte into the transmit FIFO.
InstancePtr is the instance of IIC None. C-Style signature: void XI3cPsx_SendByte(XI3cPsx *InstancePtr)
XI3cPsx_RecvByte
Receive one byte from FIFO.
InstancePtr is the instance of IIC None. C-Style signature: u8 XI3cPsx_RecvByte(XI3cPsx *InstancePtr)
typedef void(* XI3cPsx_IntrHandler)(void *CallBackRef, u32 StatusEvent))(void *CallBackRef, u32 StatusEvent)
The handler data type allows the user to define a callback function to respond to interrupt events in the system.
This function is executed in interrupt context, so amount of processing should be minimized. CallBackRef is the callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. Its type is not important to the driver, so it is a void pointer. StatusEvent indicates one or more status events that occurred.
XI3cPsx_Config XI3cPsx_ConfigTable[][]
Configuration table.
Configuration table.
static u8 XI3cPsx_OddParity7(u8 Addr)
Compute the I3C odd-parity bit for a 7-bit dynamic address.
Per the I3C spec and the DEV_ADDR_TABLE_LOC*n*.DEV_DYNAMIC_ADDR field, bit[7] of the 8-bit encoded value must be the odd parity of bits[6:0], i.e. parity = ~XOR(addr[6:0]). The controller transmits this 8-bit value verbatim during ENTDAA, so a raw address write with bit[7]=0 produces wrong parity for any 7-bit address that has an even number of 1-bits (e.g. 0x09, 0x0A, 0x0C, 0x0F, 0x11, 0x12, ...) and the slave NACKs the address assignment, hanging the controller. Addr is the 7-bit dynamic address (only bits[6:0] are used). 0 or 1 — the odd-parity bit to place in bit[7]. C-Style signature: u8 XI3cPsx_OddParity7(u8 Addr)
static void XI3cPsx_Enable(XI3cPsx *InstancePtr)
This function enables the controller.
InstancePtr is a pointer to the XI3cPsx instance. None.
void XI3cPsx_Resume(XI3cPsx *InstancePtr)
This function enables the controller.
InstancePtr is a pointer to the XI3cPsx instance. None.
static s32 XI3cPsx_GetResponse(XI3cPsx *InstancePtr)
This function reads the response.
It waits for the response from slave and reads the response. InstancePtr is a pointer to the XI3cPsx instance. Response code on success.XST_TIMEOUT on timeout.
static void XI3cPsx_SetRespThreshold(XI3cPsx *InstancePtr, u32 Val)
static void XI3cPsx_SetCmdEmptyThreshold(XI3cPsx *InstancePtr, u32 Val)
static void XI3cPsx_SetRxThreshold(XI3cPsx *InstancePtr, u32 Val)
static void XI3cPsx_SetTxThreshold(XI3cPsx *InstancePtr, u32 Val)
static void XI3cPsx_SetRxStartThreshold(XI3cPsx *InstancePtr, u32 Val)
static void XI3cPsx_SetTxStartThreshold(XI3cPsx *InstancePtr, u32 Val)
XI3cPsx_Config* XI3cPsx_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XI3cPsx_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xi3cpsx.h for the definition of XI3cPsx_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
s32 XI3cPsx_CfgInitialize(XI3cPsx *InstancePtr, XI3cPsx_Config *ConfigPtr, u32 EffectiveAddr)
Initializes a specific XI3cPsx instance such that the driver is ready to use.
InstancePtr is a pointer to the XI3cPsx instance. ConfigPtr is a reference to a structure containing information about a specific I3C device. This function initializes an InstancePtr object for a specific device specified by the contents of Config. EffectiveAddr is the device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, use ConfigPtr->BaseAddress for this parameter, passing the physical address instead. XST_SUCCESS if successful. XST_DEVICE_IS_STARTED if the instance is already initialized. XST_FAILURE if SCL clock programming or bus initialization fails (master mode only). None.
References XI3cPsx::IsReady, XI3cPsx::Config, XI3cPsx_Config::BaseAddress, XI3cPsx_Config::DeviceCount, XI3cPsx_Config::InputClockHz, XI3cPsx_Reset, XI3cPsx_ResetFifos, XI3cPsx::SclkHz, XI3cPsx_SetSClk, XI3cPsx_BusInit.
Referenced by I3cPsxMasterIntrExample, I3cPsxMasterPolledExample, I3cPsxSlaveLoopbackExample.
void XI3cPsx_Abort(XI3cPsx *InstancePtr)
void XI3cPsx_Reset(XI3cPsx *InstancePtr)
Resets the IIC device.
Reset must only be called after the driver has been initialized. The configuration of the device after reset is the same as its configuration after initialization. Any data transfer that is in progress is aborted.The upper layer software is responsible for re-configuring (if necessary) and reenabling interrupts for the IIC device after the reset. InstancePtr is a pointer to the XIicPs instance. None. None.
References XI3cPsx_WriteReg, XI3cPsx::Config, XI3cPsx_Config::BaseAddress, XI3CPSX_RESET_CTRL.
Referenced by XI3cPsx_CfgInitialize.
void XI3cPsx_ResetFifos(XI3cPsx *InstancePtr)
Resets the IIC device.
Reset must only be called after the driver has been initialized. The configuration of the device after reset is the same as its configuration after initialization. Any data transfer that is in progress is aborted.The upper layer software is responsible for re-configuring (if necessary) and reenabling interrupts for the IIC device after the reset. InstancePtr is a pointer to the XIicPs instance. None. None.
References XI3cPsx::IsReady, XI3cPsx_WriteReg, XI3cPsx::Config, XI3cPsx_Config::BaseAddress, XI3CPSX_RESET_CTRL.
Referenced by XI3cPsx_CfgInitialize, I3cPsxMasterIntrExample, I3cPsxMasterPolledExample, I3cPsxSlaveLoopbackExample.
s32 XI3cPsx_BusIsBusy(XI3cPsx *InstancePtr)
s32 XI3cPsx_TransmitFifoFill(XI3cPsx *InstancePtr)
void XI3cPsx_WrCmdFifo(XI3cPsx *InstancePtr, XI3cPsx_Cmd *Cmd)
Fill I3CPsx Command FIFO.
InstancePtr is a pointer to the XI3cPsx instance. Cmd is a pointer to the XI3cPsx_Cmd structure. None. None.
References XI3cPsx_WriteReg, XI3cPsx::Config, XI3cPsx_Config::BaseAddress, XI3CPSX_COMMAND_QUEUE_PORT.
Referenced by XI3cPsx_MasterSend, XI3cPsx_MasterRecv, XI3cPsx_MasterSendPolled, XI3cPsx_MasterRecvPolled, XI3cPsx_SlaveSendPolled.
void XI3cPsx_WrTxFifo(XI3cPsx *InstancePtr, u32 *TxBuf, u16 TxLen)
Fill I3CPsx Write Tx FIFO.
InstancePtr is a pointer to the XI3cPsx instance. TxBuf is the pointer to the send buffer. TxLen is the number of bytes to be sent. None. None.
References XI3cPsx::SendByteCount, XI3cPsx::SendBufferPtr, XI3cPsx_WriteReg, XI3cPsx::Config, XI3cPsx_Config::BaseAddress, XI3CPSX_TX_RX_DATA_PORT.
Referenced by XI3cPsx_MasterSend, XI3cPsx_MasterSendPolled, XI3cPsx_MasterInterruptHandler, XI3cPsx_SlaveSendPolled.
void XI3cPsx_RdRxFifo(XI3cPsx *InstancePtr, u32 *RxBuf, u16 RxLen)
Read I3CPsx Rx FIFO.
InstancePtr is a pointer to the XI3cPsx instance. RxBuf is the pointer to the recv buffer. RxLen is the number of bytes to be recv. None. None.
References XI3cPsx::RecvByteCount, XI3cPsx_ReadReg, XI3cPsx::Config, XI3cPsx_Config::BaseAddress, XI3CPSX_TX_RX_DATA_PORT, XI3cPsx::RecvBufferPtr.
Referenced by XI3cPsx_MasterRecvPolled, XI3cPsx_MasterInterruptHandler, XI3cPsx_SlaveRecvPolled.
s32 XI3cPsx_SendTransferCmd(XI3cPsx *InstancePtr, struct CmdInfo *CmdCCC)
This function sends the transfer command.
InstancePtr is a pointer to the XI3cPsx instance. CmdCCC is a pointer to the Command Info. XST_SUCCESS if everything went well.XST_FAILURE if any error.
References XI3cPsx_MasterRecvPolled, XI3cPsx_MasterSendPolled.
Referenced by XI3cPsx_BusInit.
s32 XI3cPsx_SendAddrAssignCmd(XI3cPsx *InstancePtr, struct CmdInfo *CmdCCC)
This function sends the Address Assignment command.
InstancePtr is a pointer to the XI3cPsx instance. CmdCCC is a pointer to the Command Info. XST_SUCCESS if everything went well.XST_FAILURE if any error.
References XI3cPsx::Config, XI3cPsx_Config::DeviceCount, XI3cPsx_MasterSendPolled.
Referenced by XI3cPsx_BusInit.
s32 XI3cPsx_BusInit(XI3cPsx *InstancePtr)
Initializes the I3c bus by configuring the device address table, resets and assigns the dynamic address to the slave devices.
InstancePtr is a pointer to the XI3cPsx instance. XST_SUCCESS if everything went well.XST_FAILURE if any error. SCL timing must be programmed before calling this function. Call XI3cPsx_SetSClk() or XI3cPsx_SetSClkRate() first so that the RSTDAA and ENTDAA bus transactions issued here run at the intended clock rate. XI3cPsx_CfgInitialize() handles this sequence automatically; callers invoking XI3cPsx_BusInit() directly are responsible for calling XI3cPsx_SetSClk() first.
References XI3cPsx_WriteReg, XI3cPsx::Config, XI3cPsx_Config::BaseAddress, XI3CPSX_DEVICE_ADDR, XI3C_DynaAddrList, XI3cPsx_Config::DeviceCount, XI3cPsx_SendTransferCmd, XI3cPsx_SendAddrAssignCmd.
Referenced by XI3cPsx_CfgInitialize.
void XI3cPsx_SetStatusHandler(XI3cPsx *InstancePtr, void *CallBackRef, XI3cPsx_IntrHandler FunctionPtr)
This function sets the status handler, which the driver calls when it encounters conditions that should be reported to the higher layer software.
The handler executes in an interrupt context, so the amount of processing should be minimized InstancePtr is a pointer to the XI3c instance. FunctionPtr is the pointer to the callback function. None. The handler is called within interrupt context, so it should finish its work quickly.
References XI3cPsx::IsReady, XI3cPsx::StatusHandler, XI3cPsx::CallBackRef.
Referenced by I3cPsxMasterIntrExample.
s32 XI3cPsx_MasterSend(XI3cPsx *InstancePtr, u8 *MsgPtr, s32 ByteCount, XI3cPsx_Cmd Cmds)
This function initiates an interrupt-driven send in master mode.
It tries to send the first FIFO-full of data, then lets the interrupt handler to handle the rest of the data if there is any. InstancePtr is a pointer to the XI3cPsx instance. MsgPtr is the pointer to the send buffer. ByteCount is the number of bytes to be sent. Cmds is the instance of XI3cPsx_Cmd. XST_SUCCESS if everything went well. This send routine is for interrupt-driven transfer only.
References XI3cPsx::SendByteCount, XI3cPsx::SendBufferPtr, XI3cPsx_WrFifoLevel, XI3cPsx_WrTxFifo, XI3CPSX_INTR_TX_THLD, XI3CPSX_INTR_RESP_READY, XI3cPsx_EnableInterrupts, XI3cPsx::Config, XI3cPsx_Config::BaseAddress, XI3cPsx_WrCmdFifo.
Referenced by I3cPsxMasterIntrExample.
s32 XI3cPsx_MasterRecv(XI3cPsx *InstancePtr, u8 *MsgPtr, s32 ByteCount, XI3cPsx_Cmd *Cmds)
This function initiates an interrupt-driven receive in master mode.
It sets the transfer size register so the slave can send data to us. The rest of the work is managed by interrupt handler. InstancePtr is a pointer to the XI3cPsx instance. MsgPtr is the pointer to the receive buffer. ByteCount is the number of bytes to be received. Cmds is a pointer to the XI3cPsx_Cmd instance. XST_SUCCESS if everything went well.XST_FAILURE if any error. This receive routine is for interrupt-driven transfer only.
References XI3cPsx::RecvByteCount, XI3cPsx::RecvBufferPtr, XI3CPSX_INTR_RX_THLD, XI3CPSX_INTR_RESP_READY, XI3cPsx_EnableInterrupts, XI3cPsx::Config, XI3cPsx_Config::BaseAddress, XI3cPsx_WrCmdFifo.
Referenced by I3cPsxMasterIntrExample.
s32 XI3cPsx_MasterSendPolled(XI3cPsx *InstancePtr, u8 *MsgPtr, s32 ByteCount, XI3cPsx_Cmd Cmds)
This function initiates a polled mode send in master mode.
It sends data to the FIFO and waits for the slave to pick them up. If master fails to send data due arbitration lost, will stop transfer and with arbitration lost status If slave fails to remove data from FIFO, the send fails with time out. InstancePtr is a pointer to the XI3cPsx instance. MsgPtr is the pointer to the send buffer. ByteCount is the number of bytes to be sent. Cmds is a pointer to the XI3cPsx_Cmd instance. XST_SUCCESS if everything went well. This send routine is for polled mode transfer only. All the FIFO operations are in terms of words.
References XI3cPsx_EnableInterrupts, XI3cPsx::Config, XI3cPsx_Config::BaseAddress, XI3CPSX_INTR_RESP_READY, XI3cPsx::SendByteCount, XI3cPsx::SendBufferPtr, XI3cPsx_WrFifoLevel, XI3cPsx_WrTxFifo, XI3cPsx_WrCmdFifo, XI3cPsx_ReadReg, XI3CPSX_INTR_STATUS, XI3cPsx_DisableInterrupts.
Referenced by XI3cPsx_SendTransferCmd, XI3cPsx_SendAddrAssignCmd, I3cPsxMasterPolledExample, I3cPsxSlaveLoopbackExample.
s32 XI3cPsx_MasterRecvPolled(XI3cPsx *InstancePtr, u8 *MsgPtr, s32 ByteCount, XI3cPsx_Cmd *Cmds)
This function initiates a polled mode receive in master mode.
It repeatedly sets the transfer size register so the slave can send data to us. It polls the data register for data to come in. If master fails to read data due arbitration lost, will return with arbitration lost status. If slave fails to send us data, it fails with time out. InstancePtr is a pointer to the XI3cPsx instance. MsgPtr is the pointer to the receive buffer. ByteCount is the number of bytes to be received. Cmds is a pointer to the XI3cPsx_Cmd instance. XST_SUCCESS if everything went well.XST_FAILURE if any error. This receive routine is for polled mode transfer only.
References XI3cPsx::RecvByteCount, XI3cPsx::RecvBufferPtr, XI3cPsx_EnableInterrupts, XI3cPsx::Config, XI3cPsx_Config::BaseAddress, XI3CPSX_INTR_RESP_READY, XI3cPsx_WrCmdFifo, XI3cPsx_RdFifoLevel, XI3cPsx_RdRxFifo, XI3cPsx_ReadReg, XI3CPSX_INTR_STATUS, XI3cPsx_DisableInterrupts.
Referenced by XI3cPsx_SendTransferCmd, I3cPsxMasterPolledExample.
void XI3cPsx_MasterInterruptHandler(XI3cPsx *InstancePtr)
The interrupt handler for the master mode.
It does the protocol handling for the interrupt-driven transfers.If the Master is receiving data then the data is read from the FIFO and the Master has to request for more data (if there is more data to receive). If all the data has been received then a completion event is signalled to the upper layer by calling the callback handler. It is an error if the amount of received data is more than expected. InstancePtr is a pointer to the XI3cPsx instance. None. None.
References XI3cPsx::IsReady, XI3cPsx_ReadReg, XI3cPsx::Config, XI3cPsx_Config::BaseAddress, XI3CPSX_INTR_STATUS, XI3cPsx_WriteReg, XI3CPSX_INTR_TX_THLD, XI3cPsx_WrFifoLevel, XI3cPsx::SendByteCount, XI3cPsx_WrTxFifo, XI3cPsx::SendBufferPtr, XI3cPsx_DisableInterrupts, XI3CPSX_INTR_RX_THLD, XI3cPsx_RdFifoLevel, XI3cPsx_RdRxFifo, XI3cPsx::RecvBufferPtr, XI3cPsx::RecvByteCount, XI3CPSX_INTR_RESP_READY, XI3CPSX_RESPONSE_QUEUE_PORT, XI3cPsx::StatusHandler, XI3cPsx::CallBackRef.
Referenced by I3cPsxMasterIntrExample.
void XI3cPsx_SetupSlave(XI3cPsx *InstancePtr, u16 SlaveAddr)
This function sets up the device to be a slave.
InstancePtr is a pointer to the XI3cPsx instance. SlaveAddr is the static address of the slave we are receiving from. None. Interrupt is always enabled no matter the transfer is interrupt- driven or polled mode. Whether device will be interrupted or not depends on whether the device is connected to an interrupt controller and interrupt for the device is enabled.
References XI3cPsx::IsReady, XI3cPsx_WriteReg, XI3cPsx::Config, XI3cPsx_Config::BaseAddress, XI3CPSX_DEVICE_ADDR, XI3cPsx_ReadReg, XI3CPSX_DEVICE_CTRL, XI3CPSX_DEVICE_CTRL_EXTENDED, XI3CPSX_BUS_FREE_AVAIL_TIMING, XI3CPSX_SLV_CHAR_CTRL, XI3CPSX_SLV_MIPI_ID_VALUE.
Referenced by I3cPsxSlaveLoopbackExample.
void XI3cPsx_SlaveSend(XI3cPsx *InstancePtr, u8 *MsgPtr, s32 ByteCount)
void XI3cPsx_SlaveRecv(XI3cPsx *InstancePtr, u8 *MsgPtr, s32 ByteCount)
This function setup a slave interrupt-driven receive.
Data processing for the receive is handled by the interrupt handler. InstancePtr is a pointer to the XI3cPsx instance. MsgPtr is the pointer to the receive buffer. ByteCount is the number of bytes to be received. None. This routine is for interrupt-driven transfer only.
References XI3cPsx::IsReady.
s32 XI3cPsx_SlaveSendPolled(XI3cPsx *InstancePtr, u8 *MsgPtr, s32 ByteCount, XI3cPsx_Cmd Cmds)
This function sends a buffer in polled mode as a slave.
InstancePtr is a pointer to the XI3cPsx instance. MsgPtr is the pointer to the send buffer. ByteCount is the number of bytes to be sent. Cmds is the instance of XI3cPsx_Cmd. XST_SUCCESS if everything went well.XST_FAILURE if master sends us data or master terminates the transfer before all data has sent out. This send routine is for polled mode transfer only.
References XI3cPsx::IsReady, XI3cPsx_EnableInterrupts, XI3cPsx::Config, XI3cPsx_Config::BaseAddress, XI3CPSX_INTR_RESP_READY, XI3cPsx::SendByteCount, XI3cPsx::SendBufferPtr, XI3cPsx_WrFifoLevel, XI3cPsx_WrTxFifo, XI3cPsx_WrCmdFifo, XI3cPsx_ReadReg, XI3CPSX_INTR_STATUS, XI3CPSX_RESPONSE_QUEUE_PORT, XI3cPsx_DisableInterrupts.
s32 XI3cPsx_SlaveRecvPolled(XI3cPsx *InstancePtr, u8 *MsgPtr)
This function receives a buffer in polled mode as a slave.
InstancePtr is a pointer to the XI3cPsx instance. MsgPtr is the pointer to the receive buffer. XST_SUCCESS if everything went well.XST_FAILURE if timed out. This receive routine is for polled mode transfer only. All the FIFO operations are in terms of words.
References XI3cPsx::IsReady, XI3cPsx::RecvBufferPtr, XI3cPsx_EnableInterrupts, XI3cPsx::Config, XI3cPsx_Config::BaseAddress, XI3CPSX_INTR_RESP_READY, XI3cPsx_ReadReg, XI3CPSX_INTR_STATUS, XI3cPsx_RdFifoLevel, XI3cPsx::RecvByteCount, XI3cPsx_RdRxFifo, XI3CPSX_RESPONSE_QUEUE_PORT, XI3cPsx_DisableInterrupts.
Referenced by I3cPsxSlaveLoopbackExample.
void XI3cPsx_SlaveInterruptHandler(XI3cPsx *InstancePtr)
The interrupt handler for slave mode.
It does the protocol handling for the interrupt-driven transfers.Completion events and errors are signaled to upper layer for proper handling.The interrupts that are handled are: DATA If the instance is sending, it means that the master wants to read more data from us. Send more data, and check whether we are done with this send.If the instance is receiving, it means that the master has written more data to us. Receive more data, and check whether we are done with with this receive.COMP This marks that stop sequence has been sent from the master, transfer is about to terminate. However, for receiving, the master may have written us some data, so receive that first.It is an error if the amount of transferred data is less than expected.NAK This marks that master does not want our data. It is for send only.Other interrupts These interrupts are marked as error. InstancePtr is a pointer to the XIicPs instance. None. None.
References XI3cPsx::IsReady.
s32 XI3cPsx_SelfTest(XI3cPsx *InstancePtr)
s32 XI3cPsx_SetSClk(XI3cPsx *InstancePtr)
Sets I3C Scl clock frequency.
InstancePtr is a pointer to the XI3cPsx instance. XST_SUCCESS if successful, XST_FAILURE if any computed timing count falls outside [SCL_I3C_TIMING_CNT_MIN, SCL_I3C_TIMING_CNT_MAX], indicating the input clock and SCL rate combination is not representable in the hardware timing registers. The SCL frequency is read from InstancePtr->SclkHz. To configure a custom SCL frequency, use XI3cPsx_SetSClkRate.
References XI3cPsx::IsReady, XI3cPsx::Config, XI3cPsx_Config::InputClockHz, XI3cPsx::SclkHz, XI3cPsx_Config::BaseAddress, SCL_I3C_TIMING_CNT_MAX, XI3cPsx_WriteReg, XI3CPSX_SCL_I3C_PP_TIMING, XI3CPSX_SCL_I3C_OD_TIMING.
Referenced by XI3cPsx_CfgInitialize, XI3cPsx_SetSClkRate.
s32 XI3cPsx_SetSClkRate(XI3cPsx *InstancePtr, u32 SclkHz)
Sets a custom I3C SCL clock frequency by updating the instance SCL rate and configuring the hardware registers accordingly.
InstancePtr is a pointer to the XI3cPsx instance. SclkHz is the desired SCL clock frequency in Hz. XST_SUCCESS if successful, XST_FAILURE if the requested SCL rate cannot be represented in the hardware timing registers for the given input clock. This updates InstancePtr->SclkHz and programs the hardware. For default SCL rate set during initialization, use XI3cPsx_SetSClk instead.
References XI3cPsx::SclkHz, XI3cPsx_SetSClk.
u32 XI3cPsx_GetSClk(const XI3cPsx *InstancePtr)
Returns the SCL clock frequency currently configured in the instance.
InstancePtr is a pointer to the XI3cPsx instance. The SCL clock frequency in Hz as last successfully programmed by XI3cPsx_SetSClk() or XI3cPsx_SetSClkRate(). This returns the software-stored rate, which is always kept in sync with the hardware. If XI3cPsx_SetSClkRate() fails, the previous valid rate is preserved and returned here.
References XI3cPsx::IsReady, XI3cPsx::SclkHz.