xi3cpsx_hw.c
void XI3cPsx_Reset(XI3cPsx *InstancePtr)
Resets the IIC device.
Reset must only be called after the driver has been initialized. The configuration of the device after reset is the same as its configuration after initialization. Any data transfer that is in progress is aborted.The upper layer software is responsible for re-configuring (if necessary) and reenabling interrupts for the IIC device after the reset. InstancePtr is a pointer to the XIicPs instance. None. None.
References XI3cPsx_Config::BaseAddress, XI3cPsx::Config, XI3CPSX_RESET_CTRL, XI3cPsx_WriteReg.
Referenced by XI3cPsx_CfgInitialize.
void XI3cPsx_ResetFifos(XI3cPsx *InstancePtr)
Resets the IIC device.
Reset must only be called after the driver has been initialized. The configuration of the device after reset is the same as its configuration after initialization. Any data transfer that is in progress is aborted.The upper layer software is responsible for re-configuring (if necessary) and reenabling interrupts for the IIC device after the reset. InstancePtr is a pointer to the XIicPs instance. None. None.
References XI3cPsx_Config::BaseAddress, XI3cPsx::Config, XI3cPsx::IsReady, XI3CPSX_RESET_CTRL, XI3cPsx_WriteReg.
Referenced by I3cPsxMasterIntrExample, I3cPsxMasterPolledExample, I3cPsxSlaveLoopbackExample, XI3cPsx_CfgInitialize.