audio_formatter
XAudioFormatter_BitDepth
XAudioFormatter_ChannelId
XAudioFormatter_HandlerType
typedef void(* XAudioFormatter_Callback)(void *CallbackRef))(void *CallbackRef)
XAudioFormatter_Config XAudioFormatter_ConfigTable[][]
void XAudioFormatterDMAReset(XAudioFormatter *InstancePtr)
This function soft resets the audio formatter DMA core.
InstancePtr is a pointer to the XAudioFormatter instance. None.
Referenced by XAudioFormatter_CfgInitialize.
u32 XAudioFormatter_CfgInitialize(XAudioFormatter *InstancePtr, XAudioFormatter_Config *CfgPtr)
This function initializes the audio formatter core instance.
InstancePtr is a pointer to the XAudioFormatter instance. CfgPtr is a reference to a structure containing information about a specific XAudioFormatter instance. XST_SUCCESS if initialization was successful. None.
References XAudioFormatter_Config::BaseAddress, XAudioFormatter::Config, XAudioFormatter::IsReady, XAudioFormatterDMAReset.
Referenced by AFSelfTestExample.
void XAudioFormatter_InterruptClear(XAudioFormatter *InstancePtr, u32 mask)
This function clears the interrupts for audio formatter core.
InstancePtr is a pointer to the XAudioFormatter instance. mask is the interrupt mask. None.
References XAudioFormatter::IsReady.
void XAudioFormatter_InterruptEnable(XAudioFormatter *InstancePtr, u32 Mask)
This function enables the interrupts for audio formatter core.
InstancePtr is a pointer to the XAudioFormatter instance. Mask is the interrupt mask. None.
References XAudioFormatter::IsReady.
void XAudioFormatter_InterruptDisable(XAudioFormatter *InstancePtr, u32 Mask)
This function disables the interrupts for audio formatter core.
InstancePtr is a pointer to the XAudioFormatter instance. Mask is the interrupt mask. None.
References XAudioFormatter::IsReady.
void XAudioFormatterDMAStart(XAudioFormatter *InstancePtr)
This function starts the dma for audio formatter core.
InstancePtr is a pointer to the XAudioFormatter instance. None.
References XAudioFormatter::IsReady.
void XAudioFormatterDMAStop(XAudioFormatter *InstancePtr)
This function stops the dma for audio formatter core.
InstancePtr is a pointer to the XAudioFormatter instance. None.
References XAudioFormatter::IsReady.
void XAudioFormatterSetHwParams(XAudioFormatter *InstancePtr, XAudioFormatterHwParams *hw_params)
This function sets the hw params for audio formatter core.
InstancePtr is a pointer to the XAudioFormatter instance. hw_params is a pointer to the XAudioFormatterHwParams structure which contains the no. of channels, bit width, no. of periods, bytes per period, bytes per channel and buffer address. None.
References XAudioFormatter::Config, XAudioFormatter::IsReady, XAudioFormatter_Config::MaxChannelsMM2S, XAudioFormatter_Config::MaxChannelsS2MM.
u32 XAudioFormatterGetDMATransferCount(XAudioFormatter *InstancePtr)
This function returns the No.
of bytes of data read from memory.. InstancePtr is a pointer to the Audio Formatter instance. - No. of bytes of data read from memory.
References XAudioFormatter::IsReady.
void XAudioFormatterSetS2MMTimeOut(XAudioFormatter *InstancePtr, u32 TimeOut)
This function sets the S2MM timeout.
InstancePtr is a pointer to the Audio Formatter instance. TimeOut is the Timeout value after which all the data is flushed to memory if there is no incoming data from any channel.
References XAudioFormatter::IsReady.
void XAudioFormatterSetFsMultiplier(XAudioFormatter *InstancePtr, u32 Mclk, u32 Fs)
This function calculates the Fs multiplier value.
InstancePtr is a pointer to the Audio Formatter instance. Mclk is the frequency of the MMclk. Fs is the sampling frequency of the system.
References XAudioFormatter::IsReady.
void XSdiAud_GetChStat(XAudioFormatter *InstancePtr, u8 *ChStatBuf)
This function reads all the Channel Status registers and writes to a buffer.
InstancePtr is a pointer to the Audio Formatter instance. ChStatBuf is a pointer to a buffer.
References XAudioFormatter_Config::BaseAddress, XAudioFormatter::Config.
XAudioFormatter_Config * XAudioFormatter_LookupConfig(UINTPTR BaseAddress)
XAudioFormatter_LookupConfig returns a reference to an XAudioFormatter_Config structure based on the unique device id, DeviceId.
The return value will refer to an entry in the device configuration table defined in the xaudioformatter_g.c file. DeviceId is the unique device ID of the device for the lookup operation. CfgPtr is a reference to a config record in the configuration table (in xaudioformatter_g.c) corresponding to DeviceId, or NULL if no match is found. None.
Referenced by AFSelfTestExample.
u32 XAudioFormatter_Initialize(XAudioFormatter *InstancePtr, UINTPTR BaseAddress)
void XAudioFormatter_SetS2MMCallback(XAudioFormatter *InstancePtr, XAudioFormatter_HandlerType handler_type, void *CallbackFunc, void *CallbackRef)
void XAudioFormatter_SetMM2SCallback(XAudioFormatter *InstancePtr, XAudioFormatter_HandlerType handler_type, void *CallbackFunc, void *CallbackRef)
void* XAudioFormatterS2MMIntrHandler(void *InstancePtr)
void* XAudioFormatterMM2SIntrHandler(void *InstancePtr)
XAUD_CHSTAT_NUMBER_OF_BYTES
XAUDFMT_H_
Prevent circular inclusions by using protection macros.