prd
XPRD_CTRL_OFFSET
Control register Offset and status register is also mappped to same address as Control register.
Referenced by XPrd_GetDecouplerState, XPrd_SelfTest, XPrd_SetDecouplerState.
XPRD_CTRL_DECOUPLER_MASK
Decoupler Mask.
Referenced by XPrd_GetDecouplerState.
XPrd_State
Decoupler Off.
XPrd_Config XPrd_ConfigTable[][]
s32 XPrd_CfgInitialize(XPrd *InstancePtr, XPrd_Config *ConfigPtr, u32 EffectiveAddress)
This function initializes a XPrd instance/driver.
InstancePtr is a pointer to the XPrd instance. ConfigPtr points to the XPrd device configuration structure. EffectiveAddress is the device base address in the virtual memory address space. If the address translation is not used then the physical address is passed. XST_SUCCESS if initialization was successful. None.
References XPrd::Config, XPrd::IsReady.
Referenced by XPrd_Example, XPrd_SelfTestExample.
void XPrd_SetDecouplerState(XPrd *InstancePtr, XPrd_State DecouplerValue)
This function is used to set Decoupler On or Off.
InstancePtr is a pointer to the XPrd instance. DecouplerValue is to set Decoupler On or Off. Value can be either 0 or 1. Values are XPRD_DECOUPLER_OFF(0) if Decoupler is OffXPRD_DECOUPLER_ON(1) if Decoupler is On None When Decoupler is On then it separates the Reconfigurable partition from static logic while Partial Reconfiguration occurs.
References XPrd::Config, XPrd::IsReady, XPRD_CTRL_OFFSET, XPRD_DECOUPLER_OFF, XPRD_DECOUPLER_ON, XPrd_WriteReg.
Referenced by XPrd_TestDecouplerState.
XPrd_State XPrd_GetDecouplerState(XPrd *InstancePtr)
This function is used to read the state of the Decoupler.
InstancePtr is a pointer to the XPrd instance. Returns decoupler state. XPRD_DECOUPLER_ON(1) if Decoupler is enabled.XPRD_DECOUPLER_OFF(0) if Decoupler is disabled. None.
References XPrd::Config, XPrd::IsReady, XPRD_CTRL_DECOUPLER_MASK, XPRD_CTRL_OFFSET, XPRD_DECOUPLER_OFF, XPRD_DECOUPLER_ON, XPrd_ReadReg.
Referenced by XPrd_TestDecouplerState.
XPrd_Config * XPrd_LookupConfig(UINTPTR BaseAddress)
This function looks for the device configuration based on the unique device ID/BaseAddress.
The table XPrd_ConfigTable[] contains the configuration information for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration table entry corresponding to the given device ID/BaseAddress, or NULL if no match is found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
Referenced by XPrd_Example, XPrd_SelfTestExample.
s32 XPrd_SelfTest(XPrd *InstancePtr)
This function runs a self-test for the PRD driver.
This self test reads the value from the status register. InstancePtr is a pointer to the XPrd instance. XST_SUCCESS if the test was successful. None.
References XPrd::Config, XPrd::IsReady, XPRD_CTRL_OFFSET, XPrd_ReadReg, XPrd_WriteReg.
Referenced by XPrd_Example, XPrd_SelfTestExample.
XPRD_H_
XPRD_HW_H_
XPrd_ReadReg
This macro reads a value from the given register.
Address is the address of the register to read from. The 32-bit value read from register. None.
Referenced by XPrd_GetDecouplerState, XPrd_SelfTest.
XPrd_WriteReg
This macro writes a value to the given register.
Address is the address of the register to write to. Data is the 32-bit value to write to the register. None. None.
Referenced by XPrd_SelfTest, XPrd_SetDecouplerState.