xtrngpsx.h
XTRNGPSX_PERS_STRING_LEN_IN_WORDS
Personalization string length in words.
XTRNGPSX_PERS_STRING_LEN_IN_BYTES
Personalization string length in bytes.
Referenced by XTrngpsx_DRBGKat.
XTRNGPSX_SEC_STRENGTH_IN_BYTES
security strength in Bytes
Referenced by XTrngpsx_DRBGKat, XTrngpsx_Generate.
XTRNGPSX_USER_CFG_SEED_LIFE
Default seed life configuration.
Referenced by XTrngpsx_HealthTest.
XTRNGPSX_USER_CFG_DF_LENGTH
Default DF (Derivation Function) length.
Referenced by XTrngpsx_HealthTest.
XTRNGPSX_USER_CFG_ADAPT_TEST_CUTOFF
Default adaptive proportion test cutoff value.
Referenced by XTrngpsx_HealthTest.
XTRNGPSX_USER_CFG_REP_TEST_CUTOFF
Default repetition count test cutoff value.
Referenced by XTrngpsx_HealthTest.
XTrngpsx_Mode
Deterministic Random Number Generator mode.
XTrngpsx_ErrorState
Unhealthy state.
XTrngpsx_State
Default state.
XTrngpsx_ErrorCodes
0x0 - Invalid argument
XTrngpsx_Config XTrngpsx_ConfigTable[][]
XTrngpsx_Config * XTrngpsx_LookupConfig(UINTPTR BaseAddress)
This function returns a reference to an XTrngpsx_Config structure based on the DeviceId.
The return value will refer to an entry in the device configuration table defined in the xtrngpsx_g.c file. DeviceId is the unique device ID of the device being lookedup. XTrngpsx_LookupConfig returns a reference to a config record in the configuration table (in xtrngpsx.c) corresponding to DeviceId, or NULL if no match is found.
int XTrngpsx_CfgInitialize(XTrngpsx_Instance *InstancePtr, const XTrngpsx_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the TRNGPSV instance/driver.
This function must be called prior to using the driver. Initialization includes only setting up the device id and base address. All the remaining parameters of the Instance will be initialized in Instantiate function. InstancePtr is a pointer to the XTrngpsx instance. CfgPtr points to the configuration structure associated with the TRNGPSX driver. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if initialization was successful.XTRNGPSX_INVALID_PARAM if invalid parameter passed to this function.
References XTrngpsx_Config::BaseAddress, XTrngpsx_Instance::Config, XTrngpsx_Instance::ErrorState, XTrngpsx_Instance::State, XTRNGPSX_ERROR, XTRNGPSX_INVALID_PARAM, XTRNGPSX_UNINITIALIZED_STATE.
int XTrngpsx_Instantiate(XTrngpsx_Instance *InstancePtr, const u8 *Seed, u32 SeedLength, const u8 *PersStr, const XTrngpsx_UserConfig *UserCfg)
This function instantiates the TRNG instance with user configure values.
InstancePtr Pointer to the XTrngpsx_Instance. Seed Pointer to the seed input SeedLength Seed length in bytes PersStr Pointer to the personalization string input UserCfg Pointer to the XTrngpsx_UserConfig XST_SUCCESS On successful instantiationXTRNGPSX_INVALID_PARAM If invalid parameter(s) passed to this function.XTRNGPSX_INVALID_SEED_VALUE If provide seed is NULL in DRBG modeXTRNGPSX_INVALID_STATE If state is not in uninstantiate stateXTRNGPSX_UNHEALTHY_STATE If TRNG KAT failsXTRNGPSX_INVALID_MODE If invalid mode is passed to this functionXTRNGPSX_INVALID_DF_LENGTH If invalid DF input length is passed as a functionXTRNGPSX_INVALID_SEED_LENGTH If provide seed length doesn't match with given DF lengthXTRNGPSX_INVALID_SEED_LIFE If invalid seed life is providedXTRNGPSX_INVALID_ADAPTPROPTEST_CUTOFF_VALUE If invalid cutoff value is providedXTRNGPSX_INVALID_REPCOUNTTEST_CUTOFF_VALUE If invalid repetitive test cutoff value is providedXTRNGPSX_USER_CFG_COPY_ERROR If error occurred during copy of XTrngpsx_UserConfig structureXTRNGPSX_TIMEOUT_ERROR If timeout occurred waiting for done bitXTRNGPSX_CATASTROPHIC_CTF_ERROR If CTF bit asserted in STATUS register.XTRNGPSX_ERROR_WRITE On write failureXTRNGPSX_INVALID_BLOCKING_MODE If invalid blocking mode is chosenXST_FAILURE On unexpected failure
References XTrngpsx_UserConfig::AdaptPropTestCutoff, XTrngpsx_UserConfig::DFLength, XTrngpsx_Instance::ErrorState, XTrngpsx_UserConfig::IsBlocking, XTrngpsx_UserConfig::Mode, XTrngpsx_UserConfig::RepCountTestCutoff, XTrngpsx_UserConfig::SeedLife, XTrngpsx_Instance::State, TRNG_CTRL_2_DIT_DEFVAL, XTrngpsx_Instance::UserCfg, XTRNGPSX_ADAPTPROPTESTCUTOFF_MAX_VAL, XTRNGPSX_BLOCK_LEN_IN_BYTES, XTRNGPSX_CATASTROPHIC, XTRNGPSX_DF_MAX_LENGTH, XTRNGPSX_DF_MIN_LENGTH, XTRNGPSX_DRNG_MODE, XTRNGPSX_ERROR, XTRNGPSX_HEALTHY, XTRNGPSX_HRNG_MODE, XTRNGPSX_INSTANTIATE_STATE, XTRNGPSX_INVALID_ADAPTPROPTEST_CUTOFF_VALUE, XTRNGPSX_INVALID_BLOCKING_MODE, XTRNGPSX_INVALID_DF_LENGTH, XTRNGPSX_INVALID_MODE, XTRNGPSX_INVALID_PARAM, XTRNGPSX_INVALID_REPCOUNTTEST_CUTOFF_VALUE, XTRNGPSX_INVALID_SEED_LENGTH, XTRNGPSX_INVALID_SEED_LIFE, XTRNGPSX_INVALID_SEED_VALUE, XTRNGPSX_INVALID_STATE, XTRNGPSX_MAX_SEEDLIFE, XTRNGPSX_MIN_SEEDLIFE, XTRNGPSX_PTRNG_MODE, XTRNGPSX_REPCOUNTTESTCUTOFF_MAX_VAL, XTRNGPSX_TEMPORAL_CHECK, XTRNGPSX_UNINITIALIZED_STATE, XTRNGPSX_USER_CFG_COPY_ERROR.
Referenced by XTrngpsx_DRBGKat, XTrngpsx_HealthTest.
int XTrngpsx_Reseed(XTrngpsx_Instance *InstancePtr, const u8 *Seed, u8 DLen)
This function triggers and reseeds the DRBG module.
InstancePtr Pointer to XTrngpsx_Instance. Seed Pointer to the seed input DLen Seed length in TRNG block size XST_SUCCESS On successful reseedXTRNGPSX_INVALID_PARAM If invalid parameter(s) passed to this function.XTRNGPSX_INVALID_SEED_VALUE If provide seed is NULL in DRBG/HRNG modeXTRNGPSX_INVALID_MODE If invalid mode is passed to this functionXTRNGPSX_INVALID_DF_LENGTH If invalid DF input length is passed as a functionXTRNGPSX_INVALID_STATE If state is not sequenced correctlyXTRNGPSX_UNHEALTHY_STATE If TRNG is in failure state, needs an uninstantiation or KAT should be run if the error is catastrophicXTRNGPSX_TIMEOUT_ERROR If timeout occurred waiting for done bitXTRNGPSX_CATASTROPHIC_CTF_ERROR If CTF bit asserted in STATUS register.XTRNGPSX_ERROR_WRITE On write failureXST_FAILURE On unexpected failure
References XTrngpsx_Instance::ErrorState, XTrngpsx_UserConfig::IsBlocking, XTrngpsx_UserConfig::Mode, XTrngpsx_Instance::State, XTrngpsx_Instance::UserCfg, XTRNGPSX_DF_MAX_LENGTH, XTRNGPSX_DF_MIN_LENGTH, XTRNGPSX_DRNG_MODE, XTRNGPSX_HEALTHY, XTRNGPSX_HRNG_MODE, XTRNGPSX_INVALID_DF_LENGTH, XTRNGPSX_INVALID_MODE, XTRNGPSX_INVALID_PARAM, XTRNGPSX_INVALID_SEED_VALUE, XTRNGPSX_INVALID_STATE, XTRNGPSX_PTRNG_MODE, XTRNGPSX_RESEED_STATE, XTRNGPSX_STARTUP_TEST, XTRNGPSX_TEMPORAL_CHECK, XTRNGPSX_UNHEALTHY_STATE, XTRNGPSX_UNINITIALIZED_STATE.
Referenced by XTrngpsx_DRBGKat, XTrngpsx_Generate.
int XTrngpsx_Generate(XTrngpsx_Instance *InstancePtr, u8 *RandBuf, u32 RandBufSize, u8 PredResistance)
This function generates and collects random data in to a buffer.
InstancePtr Pointer to XTrngpsx_Instance RandBuf Pointer to buffer in which random data is stored. RandBufSize Size of the buffer in which random data is stored. PredResistance is the flag that controls Generate level Prediction Resistance. When enabled, it mandates fresh seed for every Generate operation. XST_SUCCESS On successful generate of random numberXTRNGPSX_INVALID_PARAM If invalid parameter(s) passed to this function.XTRNGPSX_INVALID_STATE If state is not sequenced correctlyXTRNGPSX_INVALID_MODE If invalid mode is passed to this functionXTRNGPSX_INVALID_BUF_SIZE If buffer is less that 256 bytes or NULLXTRNGPSX_INVALID_PREDRES_VALUE If invalid predication resistance value is passed to this functionXTRNGPSX_UNHEALTHY_STATE If TRNG is in failure state, needs an uninstantiation or KAT should be run if error is catastrophicXTRNGPSX_RESEED_REQUIRED_ERROR If elapsed seed life exceeds the requested seed life in DRBG modeXTRNGPSX_TIMEOUT_ERROR If timeout occurred waiting for QCNT to become 4.XTRNGPSX_CATASTROPHIC_DTF_ERROR If DTF bit asserted in STATUS register.XTRNGPSX_ERROR_WRITE On write failureXST_FAILURE On unexpected failure
References XTrngpsx_Config::BaseAddress, XTrngpsx_Instance::Config, XTrngpsx_UserConfig::DFLength, XTrngpsx_Status::ElapsedSeedLife, XTrngpsx_Instance::ErrorState, XTrngpsx_UserConfig::IsBlocking, XTrngpsx_UserConfig::Mode, XTrngpsx_UserConfig::PredResistance, XTrngpsx_UserConfig::SeedLife, XTrngpsx_Instance::State, XTrngpsx_Instance::Stats, TRNG_CTRL, TRNG_CTRL_EUMODE_MASK, TRNG_CTRL_PRNGXS_MASK, TRNG_CTRL_TRSSEN_MASK, TRNG_OSC_EN, TRNG_OSC_EN_VAL_MASK, XTrngpsx_Instance::UserCfg, XTRNG_PSX_INVALID_PREDRES_VALUE, XTRNGPSX_CATASTROPHIC, XTRNGPSX_DRNG_MODE, XTRNGPSX_ERROR, XTRNGPSX_GENERATE_STATE, XTRNGPSX_HEALTHY, XTRNGPSX_HRNG_MODE, XTRNGPSX_INSTANTIATE_STATE, XTRNGPSX_INVALID_BUF_SIZE, XTRNGPSX_INVALID_MODE, XTRNGPSX_INVALID_PARAM, XTRNGPSX_INVALID_STATE, XTRNGPSX_PTRNG_MODE, XTrngpsx_Reseed, XTRNGPSX_RESEED_REQUIRED_ERROR, XTRNGPSX_RESEED_STATE, XTRNGPSX_SEC_STRENGTH_IN_BYTES, XTRNGPSX_STARTUP_TEST, XTRNGPSX_TEMPORAL_CHECK, XTRNGPSX_UNHEALTHY_STATE, XTRNGPSX_WORD_LEN_IN_BYTES.
Referenced by XTrngpsx_DRBGKat.
int XTrngpsx_Uninstantiate(XTrngpsx_Instance *InstancePtr)
This function uninstantiates the TRNG instance.
InstancePtr Pointer to XTrngpsx_Instance. XST_SUCCESS if uninstantiation was successful.XTRNGPSX_INVALID_PARAM if invalid instance is passed to functionXTRNGPSX_ERROR_MEMSET_UNINSTANTIATE_ERROR if memset was not successfulXST_FAILURE On unexpected failure
References XTrngpsx_Config::BaseAddress, XTrngpsx_Instance::Config, XTrngpsx_Instance::ErrorState, XTrngpsx_Instance::State, TRNG_OSC_EN, TRNG_OSC_EN_VAL_DEFVAL, TRNG_OSC_EN_VAL_MASK, XTRNGPSX_INVALID_PARAM, XTRNGPSX_UNINITIALIZED_STATE.
Referenced by XTrngpsx_DRBGKat, XTrngpsx_HealthTest, XTrngpsx_PreOperationalSelfTests.
int XTrngpsx_DRBGKat(XTrngpsx_Instance *InstancePtr)
This function runs DRBG self test i.e DRBG full cycle Instantiate+Reseed, Reseed and Generate.
InstancePtr Pointer to XTrngpsx_Instance. XST_SUCCESS On successError Code On failure
References XTrngpsx_UserConfig::DFLength, XTrngpsx_UserConfig::IsBlocking, XTrngpsx_UserConfig::Mode, XTrngpsx_UserConfig::SeedLife, XTRNGPSX_DRNG_MODE, XTrngpsx_Generate, XTrngpsx_Instantiate, XTRNGPSX_KAT_DEFAULT_DF_lENGTH, XTRNGPSX_KAT_DEFAULT_SEED_LIFE, XTRNGPSX_KAT_FAILED_ERROR, XTRNGPSX_KAT_SEED_LEN_IN_BYTES, XTRNGPSX_PERS_STRING_LEN_IN_BYTES, XTrngpsx_Reseed, XTRNGPSX_SEC_STRENGTH_IN_BYTES, XTrngpsx_Uninstantiate.
Referenced by XTrngpsx_PreOperationalSelfTests.
int XTrngpsx_HealthTest(XTrngpsx_Instance *InstancePtr)
This function runs health tests.
InstancePtr Pointer to XTrngpsx_Instance. XST_SUCCESS On successError Code On failure
References XTrngpsx_UserConfig::AdaptPropTestCutoff, XTrngpsx_UserConfig::DFLength, XTrngpsx_UserConfig::IsBlocking, XTrngpsx_UserConfig::Mode, XTrngpsx_UserConfig::RepCountTestCutoff, XTrngpsx_UserConfig::SeedLife, XTRNGPSX_HRNG_MODE, XTrngpsx_Instantiate, XTrngpsx_Uninstantiate, XTRNGPSX_USER_CFG_ADAPT_TEST_CUTOFF, XTRNGPSX_USER_CFG_DF_LENGTH, XTRNGPSX_USER_CFG_REP_TEST_CUTOFF, XTRNGPSX_USER_CFG_SEED_LIFE.
Referenced by XTrngpsx_PreOperationalSelfTests.
int XTrngpsx_PreOperationalSelfTests(XTrngpsx_Instance *InstancePtr)
This function runs preoperational self tests and updates TRNG error state.
InstancePtr Pointer to XTrngpsx_Instance. XST_SUCCESS On successError Code On failure
References XTrngpsx_DRBGKat, XTrngpsx_HealthTest, XTrngpsx_Uninstantiate.