xtrngpsx.c
XTRNGPSX_RESEED_TIMEOUT
Reseed timeout in micro-seconds.
XTRNGPSX_GENERATE_TIMEOUT
Generate timeout in micro-seconds.
XTRNGPSX_WORD_LEN_IN_BYTES
Word length in bytes.
Referenced by XTrngpsx_Generate.
XTRNGPSX_BYTE_LEN_IN_BITS
Byte length in bits.
XTRNGPSX_BLOCK_LEN_IN_BYTES
TRNG block length length in bytes.
Referenced by XTrngpsx_Instantiate.
XTRNGPSX_MIN_SEEDLIFE
Minimum seed life.
Referenced by XTrngpsx_Instantiate.
XTRNGPSX_MAX_SEEDLIFE
Maximum seed life 2^19.
Referenced by XTrngpsx_Instantiate.
XTRNGPSX_SEC_STRENGTH_IN_BURSTS
Security strength in 128-bit bursts.
XTRNGPSX_BURST_SIZE_IN_WORDS
Burst size in words.
XTRNGPSX_DF_MIN_LENGTH
Minimum DF input length.
Referenced by XTrngpsx_Instantiate, XTrngpsx_Reseed.
XTRNGPSX_DF_MAX_LENGTH
Maximum DF input length.
Referenced by XTrngpsx_Instantiate, XTrngpsx_Reseed.
XTRNGPSX_DF_NUM_OF_BYTES_BEFORE_MIN_700CLKS_WAIT
Number of bytes to be written before wait.
XTRNGPSX_ADAPTPROPTESTCUTOFF_MAX_VAL
maximum adaptprpptest cutoff value
Referenced by XTrngpsx_Instantiate.
XTRNGPSX_REPCOUNTTESTCUTOFF_MAX_VAL
maximum repcounttest cutoff value
Referenced by XTrngpsx_Instantiate.
XTRNGPSX_RESET_DELAY_US
Reset delay.
XTRNGPSX_DF_700CLKS_WAIT
Delay after 4 bytes.
XTRNGPSX_DF_2CLKS_WAIT
Delay after 1 byte.
XTRNGPSX_STATUS_QCNT_VAL
QCNT value for single burst.
XTRNGPSX_TEMPORAL_IMPL
Temporal redundancy implementation macro for fault injection protection.
XTRNGPSX_TEMPORAL_CHECK
Temporal redundancy check macro with error handling for security-critical operations.
Referenced by XTrngpsx_Generate, XTrngpsx_Instantiate, XTrngpsx_Reseed.
static int XTrngpsx_ReseedInternal(XTrngpsx_Instance *InstancePtr, const u8 *Seed, u8 DLen, const u8 *PerStr, const u8 IsBlocking)
This function triggers and reseeds the DRBG module.
InstancePtr Pointer to XTrngpsx_Instance. Seed Pointer to the seed input DLen Seed length in multiples of TRNG block size PerStr Pointer to the personalization string IsBlocking Blocking or Non-blocking support for reseed operation XST_SUCCESS On successful reseedXTRNGPSX_ERROR_WRITE On write failure XTRNGPSX_TIMEOUT_ERROR If timeout occurred waiting for done bitXTRNGPSX_CATASTROPHIC_CTF_ERROR If CTF bit asserted in STATUS register.
static int XTrngpsx_WritePersString(XTrngpsx_Instance *InstancePtr, const u8 *PersString)
This function writes personalization string in to the registers.
InstancePtr Pointer to XTrngpsx_Instance. PersString Pointer to personalization string. -XST_SUCCESS On successful write -XST_FAILURE On failure
static int XTrngpsx_WaitForReseed(XTrngpsx_Instance *InstancePtr)
This function waits for the reseed done bit.
InstancePtr Pointer to XTrngpsx_Instance. XST_SUCCESS if Random number collection was successful.XTRNGPSX_TIMEOUT_ERROR if timeout occurred waiting for done bitXTRNGPSX_CATASTROPHIC_CTF_ERROR if CTF bit asserted in STATUS register.
static int XTrngpsx_CollectRandData(XTrngpsx_Instance *InstancePtr, u8 *RandBuf, u32 RandBufSize)
This function triggers Generate operation and collects random data in buffer.
InstancePtr Pointer to XTrngpsx_Instance. RandBuf Pointer to the buffer in which random data is stored. RandBufSize Buffer size in bytes. XST_SUCCESS if Random number collection was successful.XTRNGPSX_TIMEOUT_ERROR if timeout occurred waiting for QCNT to become 4.XTRNGPSX_CATASTROPHIC_DTF_ERROR if DTF bit asserted in STATUS register.
static int XTrngpsx_WriteSeed(XTrngpsx_Instance *InstancePtr, const u8 *Seed, u8 DLen)
This function writes seed to the derivative function.
InstancePtr Pointer to XTrngpsx_Instance. Seed Pointer to the seed input. DLen Seed length in multiples of TRNG block size -XST_SUCCESS On successful write -XST_FAILURE On failure
static int XTrngpsx_WaitForEvent(UINTPTR Addr, u32 EventMask, u32 Event, u32 Timeout)
Waits for an event to occur for a specified duration.
Addr Address of register to be checked for event(s) occurrence. EventMask Mask indicating event(s) to be checked. Event Specific event(s) value to be checked. Timeout Max number of microseconds to wait for an event(s). XST_SUCCESS - On occurrence of the event(s). XST_FAILURE - Event did not occur before counter reaches 0.
static void XTrngpsx_WriteReg(UINTPTR Address, u32 RegValue)
Write to the register.
Address is the address of the register to be written. RegValue is the value to be written to the register.
static u32 XTrngpsx_ReadReg(UINTPTR RegAddress)
Read from the register.
RegAddress Address of the register. The value read from the register.
static int XTrngpsx_UtilRMW32(UINTPTR RegAddress, u32 Mask, u32 Value)
This function reads, modifies and writes in to the register.
RegAddress Address of the register. Mask Indicates the bits to be modified Value Contains 32 bit Value to be written at the specified address -XST_SUCCESS On successful write -XST_FAILURE On failure
static int XTrngpsx_Set(XTrngpsx_Instance *InstancePtr)
This function brings TRNG core and prng unit out of reset.
InstancePtr Pointer to XTrngpsx_Instance. -XST_SUCCESS On success -XST_FAILURE On failure
static int XTrngpsx_Reset(XTrngpsx_Instance *InstancePtr)
This function sets TRNG core in to reset state.
InstancePtr Pointer to XTrngpsx_Instance. -XST_SUCCESS On success -XST_FAILURE On failure
static int XTrngpsx_PrngReset(XTrngpsx_Instance *InstancePtr)
This function sets PRNG unit in to reset state.
InstancePtr Pointer to XTrngpsx_Instance. -XST_SUCCESS On success -XST_FAILURE On failure
static int XTrngpsx_PrngSet(XTrngpsx_Instance *InstancePtr)
This function brings PRNG unit out of reset.
InstancePtr Pointer to XTrngpsx_Instance. -XST_SUCCESS On success -XST_FAILURE On failure
static int XTrngpsx_CfgDfLen(XTrngpsx_Instance *InstancePtr, u8 DfLen)
This function configures the DF input length.
InstancePtr Pointer to XTrngpsx_Instance. DfLen input DF length. -XST_SUCCESS On successful write -XST_FAILURE On failure
static int XTrngpsx_CfgAdaptPropTestCutoff(XTrngpsx_Instance *InstancePtr, u16 AdaptPropTestCutoff)
This function writes the cutoff value in to the register.
InstancePtr Pointer to XTrngpsx_Instance. AdaptPropTestCutoff cutoff value for adaptive count test. -XST_SUCCESS On successful write -XST_FAILURE On failure
static int XTrngpsx_CfgRepCountTestCutoff(XTrngpsx_Instance *InstancePtr, u16 RepCountTestCutoff)
This function writes the cutoff value in to the register.
InstancePtr Pointer to XTrngpsx_Instance. RepCountTestCutoff cutoff value for repetitive count test. -XST_SUCCESS On successful write -XST_FAILURE On failure
static int XTrngpsx_CfgDIT(XTrngpsx_Instance *InstancePtr, u8 DITValue)
This function writes the DIT value in to the register.
InstancePtr Pointer to XTrngpsx_Instance. DITValue Digitization interval time. -XST_SUCCESS On successful write -XST_FAILURE On failure
int XTrngpsx_CfgInitialize(XTrngpsx_Instance *InstancePtr, const XTrngpsx_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the TRNGPSV instance/driver.
This function must be called prior to using the driver. Initialization includes only setting up the device id and base address. All the remaining parameters of the Instance will be initialized in Instantiate function. InstancePtr is a pointer to the XTrngpsx instance. CfgPtr points to the configuration structure associated with the TRNGPSX driver. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if initialization was successful.XTRNGPSX_INVALID_PARAM if invalid parameter passed to this function.
References XTrngpsx_Config::BaseAddress, XTrngpsx_Instance::Config, XTrngpsx_Instance::ErrorState, XTrngpsx_Instance::State, XTRNGPSX_ERROR, XTRNGPSX_INVALID_PARAM, XTRNGPSX_UNINITIALIZED_STATE.
int XTrngpsx_Instantiate(XTrngpsx_Instance *InstancePtr, const u8 *Seed, u32 SeedLength, const u8 *PersStr, const XTrngpsx_UserConfig *UserCfg)
This function instantiates the TRNG instance with user configure values.
InstancePtr Pointer to the XTrngpsx_Instance. Seed Pointer to the seed input SeedLength Seed length in bytes PersStr Pointer to the personalization string input UserCfg Pointer to the XTrngpsx_UserConfig XST_SUCCESS On successful instantiationXTRNGPSX_INVALID_PARAM If invalid parameter(s) passed to this function.XTRNGPSX_INVALID_SEED_VALUE If provide seed is NULL in DRBG modeXTRNGPSX_INVALID_STATE If state is not in uninstantiate stateXTRNGPSX_UNHEALTHY_STATE If TRNG KAT failsXTRNGPSX_INVALID_MODE If invalid mode is passed to this functionXTRNGPSX_INVALID_DF_LENGTH If invalid DF input length is passed as a functionXTRNGPSX_INVALID_SEED_LENGTH If provide seed length doesn't match with given DF lengthXTRNGPSX_INVALID_SEED_LIFE If invalid seed life is providedXTRNGPSX_INVALID_ADAPTPROPTEST_CUTOFF_VALUE If invalid cutoff value is providedXTRNGPSX_INVALID_REPCOUNTTEST_CUTOFF_VALUE If invalid repetitive test cutoff value is providedXTRNGPSX_USER_CFG_COPY_ERROR If error occurred during copy of XTrngpsx_UserConfig structureXTRNGPSX_TIMEOUT_ERROR If timeout occurred waiting for done bitXTRNGPSX_CATASTROPHIC_CTF_ERROR If CTF bit asserted in STATUS register.XTRNGPSX_ERROR_WRITE On write failureXTRNGPSX_INVALID_BLOCKING_MODE If invalid blocking mode is chosenXST_FAILURE On unexpected failure
References XTrngpsx_UserConfig::AdaptPropTestCutoff, XTrngpsx_UserConfig::DFLength, XTrngpsx_Instance::ErrorState, XTrngpsx_UserConfig::IsBlocking, XTrngpsx_UserConfig::Mode, XTrngpsx_UserConfig::RepCountTestCutoff, XTrngpsx_UserConfig::SeedLife, XTrngpsx_Instance::State, TRNG_CTRL_2_DIT_DEFVAL, XTrngpsx_Instance::UserCfg, XTRNGPSX_ADAPTPROPTESTCUTOFF_MAX_VAL, XTRNGPSX_BLOCK_LEN_IN_BYTES, XTRNGPSX_CATASTROPHIC, XTRNGPSX_DF_MAX_LENGTH, XTRNGPSX_DF_MIN_LENGTH, XTRNGPSX_DRNG_MODE, XTRNGPSX_ERROR, XTRNGPSX_HEALTHY, XTRNGPSX_HRNG_MODE, XTRNGPSX_INSTANTIATE_STATE, XTRNGPSX_INVALID_ADAPTPROPTEST_CUTOFF_VALUE, XTRNGPSX_INVALID_BLOCKING_MODE, XTRNGPSX_INVALID_DF_LENGTH, XTRNGPSX_INVALID_MODE, XTRNGPSX_INVALID_PARAM, XTRNGPSX_INVALID_REPCOUNTTEST_CUTOFF_VALUE, XTRNGPSX_INVALID_SEED_LENGTH, XTRNGPSX_INVALID_SEED_LIFE, XTRNGPSX_INVALID_SEED_VALUE, XTRNGPSX_INVALID_STATE, XTRNGPSX_MAX_SEEDLIFE, XTRNGPSX_MIN_SEEDLIFE, XTRNGPSX_PTRNG_MODE, XTRNGPSX_REPCOUNTTESTCUTOFF_MAX_VAL, XTRNGPSX_TEMPORAL_CHECK, XTRNGPSX_UNINITIALIZED_STATE, XTRNGPSX_USER_CFG_COPY_ERROR.
Referenced by XTrngpsx_DRBGKat, XTrngpsx_HealthTest.
int XTrngpsx_Reseed(XTrngpsx_Instance *InstancePtr, const u8 *Seed, u8 DLen)
This function triggers and reseeds the DRBG module.
InstancePtr Pointer to XTrngpsx_Instance. Seed Pointer to the seed input DLen Seed length in TRNG block size XST_SUCCESS On successful reseedXTRNGPSX_INVALID_PARAM If invalid parameter(s) passed to this function.XTRNGPSX_INVALID_SEED_VALUE If provide seed is NULL in DRBG/HRNG modeXTRNGPSX_INVALID_MODE If invalid mode is passed to this functionXTRNGPSX_INVALID_DF_LENGTH If invalid DF input length is passed as a functionXTRNGPSX_INVALID_STATE If state is not sequenced correctlyXTRNGPSX_UNHEALTHY_STATE If TRNG is in failure state, needs an uninstantiation or KAT should be run if the error is catastrophicXTRNGPSX_TIMEOUT_ERROR If timeout occurred waiting for done bitXTRNGPSX_CATASTROPHIC_CTF_ERROR If CTF bit asserted in STATUS register.XTRNGPSX_ERROR_WRITE On write failureXST_FAILURE On unexpected failure
References XTrngpsx_Instance::ErrorState, XTrngpsx_UserConfig::IsBlocking, XTrngpsx_UserConfig::Mode, XTrngpsx_Instance::State, XTrngpsx_Instance::UserCfg, XTRNGPSX_DF_MAX_LENGTH, XTRNGPSX_DF_MIN_LENGTH, XTRNGPSX_DRNG_MODE, XTRNGPSX_HEALTHY, XTRNGPSX_HRNG_MODE, XTRNGPSX_INVALID_DF_LENGTH, XTRNGPSX_INVALID_MODE, XTRNGPSX_INVALID_PARAM, XTRNGPSX_INVALID_SEED_VALUE, XTRNGPSX_INVALID_STATE, XTRNGPSX_PTRNG_MODE, XTRNGPSX_RESEED_STATE, XTRNGPSX_STARTUP_TEST, XTRNGPSX_TEMPORAL_CHECK, XTRNGPSX_UNHEALTHY_STATE, XTRNGPSX_UNINITIALIZED_STATE.
Referenced by XTrngpsx_DRBGKat, XTrngpsx_Generate.
int XTrngpsx_Generate(XTrngpsx_Instance *InstancePtr, u8 *RandBuf, u32 RandBufSize, u8 PredResistance)
This function generates and collects random data in to a buffer.
InstancePtr Pointer to XTrngpsx_Instance RandBuf Pointer to buffer in which random data is stored. RandBufSize Size of the buffer in which random data is stored. PredResistance is the flag that controls Generate level Prediction Resistance. When enabled, it mandates fresh seed for every Generate operation. XST_SUCCESS On successful generate of random numberXTRNGPSX_INVALID_PARAM If invalid parameter(s) passed to this function.XTRNGPSX_INVALID_STATE If state is not sequenced correctlyXTRNGPSX_INVALID_MODE If invalid mode is passed to this functionXTRNGPSX_INVALID_BUF_SIZE If buffer is less that 256 bytes or NULLXTRNGPSX_INVALID_PREDRES_VALUE If invalid predication resistance value is passed to this functionXTRNGPSX_UNHEALTHY_STATE If TRNG is in failure state, needs an uninstantiation or KAT should be run if error is catastrophicXTRNGPSX_RESEED_REQUIRED_ERROR If elapsed seed life exceeds the requested seed life in DRBG modeXTRNGPSX_TIMEOUT_ERROR If timeout occurred waiting for QCNT to become 4.XTRNGPSX_CATASTROPHIC_DTF_ERROR If DTF bit asserted in STATUS register.XTRNGPSX_ERROR_WRITE On write failureXST_FAILURE On unexpected failure
References XTrngpsx_Config::BaseAddress, XTrngpsx_Instance::Config, XTrngpsx_UserConfig::DFLength, XTrngpsx_Status::ElapsedSeedLife, XTrngpsx_Instance::ErrorState, XTrngpsx_UserConfig::IsBlocking, XTrngpsx_UserConfig::Mode, XTrngpsx_UserConfig::PredResistance, XTrngpsx_UserConfig::SeedLife, XTrngpsx_Instance::State, XTrngpsx_Instance::Stats, TRNG_CTRL, TRNG_CTRL_EUMODE_MASK, TRNG_CTRL_PRNGXS_MASK, TRNG_CTRL_TRSSEN_MASK, TRNG_OSC_EN, TRNG_OSC_EN_VAL_MASK, XTrngpsx_Instance::UserCfg, XTRNG_PSX_INVALID_PREDRES_VALUE, XTRNGPSX_CATASTROPHIC, XTRNGPSX_DRNG_MODE, XTRNGPSX_ERROR, XTRNGPSX_GENERATE_STATE, XTRNGPSX_HEALTHY, XTRNGPSX_HRNG_MODE, XTRNGPSX_INSTANTIATE_STATE, XTRNGPSX_INVALID_BUF_SIZE, XTRNGPSX_INVALID_MODE, XTRNGPSX_INVALID_PARAM, XTRNGPSX_INVALID_STATE, XTRNGPSX_PTRNG_MODE, XTrngpsx_Reseed, XTRNGPSX_RESEED_REQUIRED_ERROR, XTRNGPSX_RESEED_STATE, XTRNGPSX_SEC_STRENGTH_IN_BYTES, XTRNGPSX_STARTUP_TEST, XTRNGPSX_TEMPORAL_CHECK, XTRNGPSX_UNHEALTHY_STATE, XTRNGPSX_WORD_LEN_IN_BYTES.
Referenced by XTrngpsx_DRBGKat.
int XTrngpsx_Uninstantiate(XTrngpsx_Instance *InstancePtr)
This function uninstantiates the TRNG instance.
InstancePtr Pointer to XTrngpsx_Instance. XST_SUCCESS if uninstantiation was successful.XTRNGPSX_INVALID_PARAM if invalid instance is passed to functionXTRNGPSX_ERROR_MEMSET_UNINSTANTIATE_ERROR if memset was not successfulXST_FAILURE On unexpected failure
References XTrngpsx_Config::BaseAddress, XTrngpsx_Instance::Config, XTrngpsx_Instance::ErrorState, XTrngpsx_Instance::State, TRNG_OSC_EN, TRNG_OSC_EN_VAL_DEFVAL, TRNG_OSC_EN_VAL_MASK, XTRNGPSX_INVALID_PARAM, XTRNGPSX_UNINITIALIZED_STATE.
Referenced by XTrngpsx_DRBGKat, XTrngpsx_HealthTest, XTrngpsx_PreOperationalSelfTests.