csi
XCSI_HANDLER_DPHY
D-PHY level error handler.
Referenced by XCsi_SetCallBack.
XCSI_HANDLER_PKTLVL
Packet level error handler.
Referenced by XCsi_SetCallBack.
XCSI_HANDLER_PROTLVL
Protocol level error handler.
Referenced by XCsi_SetCallBack.
XCSI_HANDLER_SHORTPACKET
Short packet handler.
Referenced by XCsi_SetCallBack.
XCSI_HANDLER_FRAMERECVD
Frame received handler.
Referenced by XCsi_SetCallBack.
XCSI_HANDLER_VCXERR
Virtual channel error handler.
Referenced by XCsi_SetCallBack.
XCSI_HANDLER_OTHERERROR
Other error handler.
Referenced by XCsi_SetCallBack.
XCSI_CCR_OFFSET
Core Configuration Register.
XCSI_PCR_OFFSET
Protocol Configuration Register.
Referenced by XCsi_SelfTest.
XCSI_CSR_OFFSET
Core Status Register.
XCSI_GIER_OFFSET
Global Interrupt Register.
Referenced by XCsi_Configure.
XCSI_ISR_OFFSET
Interrupt Status Register.
Referenced by XCsi_GetIntrStatus, XCsi_InterruptClear.
XCSI_IER_OFFSET
Interrupt Enable Register.
Referenced by XCsi_GetIntrEnable, XCsi_IntrDisable, XCsi_IntrEnable.
XCSI_VC_SEL_OFFSET
VC Selection Register.
Referenced by XCsi_GetVCSelection, XCsi_SetVCSelection.
XCSI_SPKTR_OFFSET
Generic Short Packet Register.
Referenced by XCsi_GetShortPacket.
XCSI_VCX_FE_OFFSET
VCx Frame Error Register.
Referenced by XCsi_IntrHandler.
XCSI_CLKINFR_OFFSET
Clock Lane Info Register.
Referenced by XCsi_GetClkLaneInfo.
XCSI_L0INFR_OFFSET
Lane Information Registers.
Lane 0 Info Register
Referenced by XCsi_GetDataLaneInfo.
XCSI_L1INFR_OFFSET
Lane 1 Info Register.
Referenced by XCsi_GetDataLaneInfo.
XCSI_L2INFR_OFFSET
Lane 2 Info Register.
Referenced by XCsi_GetDataLaneInfo.
XCSI_L3INFR_OFFSET
Lane 3 Info Register.
Referenced by XCsi_GetDataLaneInfo.
XCSI_VC0INF1R_OFFSET
Image Information Register for each Virtual Channel.
Virtual Channel 0 Image Information 1 Register
Referenced by XCsi_GetVCInfo.
XCSI_VC0INF2R_OFFSET
Virtual Channel 0 Image Information 2 Register.
XCSI_VC1INF1R_OFFSET
Virtual Channel 1 Image Information 1 Register.
Referenced by XCsi_GetVCInfo.
XCSI_VC1INF2R_OFFSET
Virtual Channel 1 Image Information 2 Register.
XCSI_VC2INF1R_OFFSET
Virtual Channel 2 Image Information 1 Register.
XCSI_VC2INF2R_OFFSET
Virtual Channel 2 Image Information 2 Register.
XCSI_VC3INF1R_OFFSET
Virtual Channel 3 Image Information 1 Register.
XCSI_VC3INF2R_OFFSET
Virtual Channel 3 Image Information 2 Register.
XCSI_VC4INF1R_OFFSET
Virtual Channel 4 Image Information 1 Register.
XCSI_VC4INF2R_OFFSET
Virtual Channel 4 Image Information 2 Register.
XCSI_VC5INF1R_OFFSET
Virtual Channel 5 Image Information 1 Register.
XCSI_VC5INF2R_OFFSET
Virtual Channel 5 Image Information 2 Register.
XCSI_VC6INF1R_OFFSET
Virtual Channel 6 Image Information 1 Register.
XCSI_VC6INF2R_OFFSET
Virtual Channel 6 Image Information 2 Register.
XCSI_VC7INF1R_OFFSET
Virtual Channel 7 Image Information 1 Register.
XCSI_VC7INF2R_OFFSET
Virtual Channel 7 Image Information 2 Register.
XCSI_VC8INF1R_OFFSET
Virtual Channel 8 Image Information 1 Register.
XCSI_VC8INF2R_OFFSET
Virtual Channel 8 Image Information 2 Register.
XCSI_VC9INF1R_OFFSET
Virtual Channel 9 Image Information 1 Register.
XCSI_VC9INF2R_OFFSET
Virtual Channel 9 Image Information 2 Register.
XCSI_VC10INF1R_OFFSET
Virtual Channel 10 Image Information 1 Register.
XCSI_VC10INF2R_OFFSET
Virtual Channel 10 Image Information 2 Register.
XCSI_VC11INF1R_OFFSET
Virtual Channel 11 Image Information 1 Register.
XCSI_VC11INF2R_OFFSET
Virtual Channel 11 Image Information 2 Register.
XCSI_VC12INF1R_OFFSET
Virtual Channel 12 Image Information 1 Register.
XCSI_VC12INF2R_OFFSET
Virtual Channel 12 Image Information 2 Register.
XCSI_VC13INF1R_OFFSET
Virtual Channel 13 Image Information 1 Register.
XCSI_VC13INF2R_OFFSET
Virtual Channel 13 Image Information 2 Register.
XCSI_VC14INF1R_OFFSET
Virtual Channel 14 Image Information 1 Register.
XCSI_VC14INF2R_OFFSET
Virtual Channel 14 Image Information 2 Register.
XCSI_VC15INF1R_OFFSET
Virtual Channel 15 Image Information 1 Register.
XCSI_VC15INF2R_OFFSET
Virtual Channel 15 Image Information 2 Register.
XCSI_CCR_SOFTRESET_MASK
Soft Reset the core.
XCSI_CCR_COREENB_MASK
Enable/Disable core.
XCSI_CCR_SOFTRESET_SHIFT
Shift bits for Soft reset.
XCSI_CCR_COREENB_SHIFT
Shift bits for Core Enable.
XCSI_PCR_MAXLANES_MASK
Maximum lanes in core.
Referenced by XCsi_SelfTest.
XCSI_PCR_ACTLANES_MASK
Active lanes in core.
XCSI_PCR_MAXLANES_SHIFT
Shift bits for Max Lanes.
Referenced by XCsi_SelfTest.
XCSI_PCR_ACTLANES_SHIFT
Shift bits for Active Lanes.
XCSI_CSR_PKTCOUNT_MASK
16-bit Packet Counter
XCSI_CSR_SPFIFOFULL_MASK
Short Packet FIFO Full.
XCSI_CSR_SPFIFONE_MASK
Short Packet FIFO Not Empty.
XCSI_CSR_SLBF_MASK
Stream Line Buffer Full.
XCSI_CSR_RIPCD_MASK
Reset in Progress OR Core Disabled.
XCSI_CSR_PKTCOUNT_SHIFT
Shift bits for Packet Counter.
XCSI_CSR_SPFIFOFULL_SHIFT
Shift bits for Short Packet FIFO Full.
XCSI_CSR_SPFIFONE_SHIFT
Shift bits for Short Packet Not Empty.
XCSI_CSR_SLBF_SHIFT
Shift bits for Stream Line Buffer Full.
XCSI_CSR_RIPCD_SHIFT
Bit Shift for Reset in Progress.
XCSI_GIER_GIE_MASK
Global Interrupt Enable bit.
XCSI_GIER_GIE_SHIFT
Shift bits for Global Interrupt Enable.
XCSI_GIER_SET
Enable the Global Interrupts.
XCSI_GIER_RESET
Disable the Global Interrupts.
XCSI_ISR_FR_MASK
Frame Received.
XCSI_ISR_VCXFE_MASK
VCX Frame Error.
XCSI_ISR_SKEWCALCHS_MASK
Skewcalhs Error.
XCSI_ISR_YUV420_MASK
YUV420 Word count Error.
XCSI_ISR_WC_MASK
Word count corruption.
XCSI_ISR_ILC_MASK
Incorrect Lanes Configured.
XCSI_ISR_SPFIFOF_MASK
Short Packet FIFO FULL.
XCSI_ISR_SPFIFONE_MASK
Short Packet FIFO Not Empty.
XCSI_ISR_SLBF_MASK
Stream Line Buffer Full.
XCSI_ISR_STOP_MASK
Detect Stop State.
XCSI_ISR_SOTERR_MASK
SoT Error.
XCSI_ISR_SOTSYNCERR_MASK
SoT Sync Error.
XCSI_ISR_ECC2BERR_MASK
ECC 2 bit Error.
XCSI_ISR_ECC1BERR_MASK
ECC 1 bit Error.
XCSI_ISR_CRCERR_MASK
CRC Error.
XCSI_ISR_DATAIDERR_MASK
Unknown data ID packet Error.
XCSI_ISR_VC3FSYNCERR_MASK
Frame Sync Error on Virtual Channel 3.
XCSI_ISR_VC3FLVLERR_MASK
Frame Level Error on Virtual Channel 3.
XCSI_ISR_VC2FSYNCERR_MASK
Frame Sync Error on Virtual Channel 2.
XCSI_ISR_VC2FLVLERR_MASK
Frame Level Error on Virtual Channel 2.
XCSI_ISR_VC1FSYNCERR_MASK
Frame Sync Error on Virtual Channel 1.
XCSI_ISR_VC1FLVLERR_MASK
Frame Level Error on Virtual Channel 1.
XCSI_ISR_VC0FSYNCERR_MASK
Frame Sync Error on Virtual Channel 0.
XCSI_ISR_VC0FLVLERR_MASK
Frame Level Error on Virtual Channel 0.
XCSI_ISR_ALLINTR_MASK
All interrupts mask.
Referenced by XCsi_InterruptClear.
XCSI_ISR_FR_SHIFT
Shift bits for Frame received interrupt.
XCSI_ISR_VCXFE_SHIFT
Shift bits for VCx Frame Error interrupt.
XCSI_ISR_SKEWCALCHS_SHIFT
Shift bits for skeecalchs Error interrupt.
XCSI_ISR_YUV420_SHIFT
Shift bits for YUV420 word count interrupt.
XCSI_ISR_WC_SHIFT
Shift bits for Word Count corruption.
XCSI_ISR_ILC_SHIFT
Shift bits for Incorrect Lanes configured.
XCSI_ISR_SPFIFOF_SHIFT
Shift bits for Short Packet FIFO Full.
XCSI_ISR_SPFIFONE_SHIFT
Shift bits for Short Packet FIFO Not Empty.
XCSI_ISR_SLBF_SHIFT
Shift bits for Stream Line Buffer Full.
XCSI_ISR_STOP_SHIFT
Shift bits for Stop State.
XCSI_ISR_SOTERR_SHIFT
Shift bits for Start of Transmission Error.
XCSI_ISR_SOTSYNCERR_SHIFT
Shift bits for Start of Transmission Sync Error.
XCSI_ISR_ECC2BERR_SHIFT
Shift bits for 2 bit ECC error.
XCSI_ISR_ECC1BERR_SHIFT
Shift bits for 1 bit ECC error.
XCSI_ISR_CRCERR_SHIFT
Shift bits for Packet CRC error.
XCSI_ISR_DATAIDERR_SHIFT
Shift bits for Unsupported Data ID error.
XCSI_ISR_VC3FSYNCERR_SHIFT
Shift bits for Virtual Channel 3 Frame Synchronisation Error.
XCSI_ISR_VC3FLVLERR_SHIFT
Shift bits for Virtual Channel 3 Frame Level Error.
XCSI_ISR_VC2FSYNCERR_SHIFT
Shift bits for Virtual Channel 2 Frame Synchronisation Error.
XCSI_ISR_VC2FLVLERR_SHIFT
Shift bits for Virtual Channel 2 Frame Level Error.
XCSI_ISR_VC1FSYNCERR_SHIFT
Shift bits for Virtual Channel 1 Frame Synchronisation Error.
XCSI_ISR_VC1FLVLERR_SHIFT
Shift bits for Virtual Channel 1 Frame Level Error.
XCSI_ISR_VC0FSYNCERR_SHIFT
Shift bits for Virtual Channel 0 Frame Synchronisation Error.
XCSI_ISR_VC0FLVLERR_SHIFT
Shift bits for Virtual Channel 0 Frame Level Error.
XCSI_INTR_PROT_MASK
Protocol decoding error mask for VC0-3.
Referenced by XCsi_IntrHandler.
XCSI_ISR_VC15FSYNCERR_MASK
Frame Sync Error on Virtual Channel 15.
XCSI_ISR_VC15FLVLERR_MASK
Frame Level Error on Virtual Channel 15.
XCSI_ISR_VC14FSYNCERR_MASK
Frame Sync Error on Virtual Channel 14.
XCSI_ISR_VC14FLVLERR_MASK
Frame Level Error on Virtual Channel 14.
XCSI_ISR_VC13FSYNCERR_MASK
Frame Sync Error on Virtual Channel 13.
XCSI_ISR_VC13FLVLERR_MASK
Frame Level Error on Virtual Channel 13.
XCSI_ISR_VC12FSYNCERR_MASK
Frame Sync Error on Virtual Channel 12.
XCSI_ISR_VC12FLVLERR_MASK
Frame Level Error on Virtual Channel 12.
XCSI_ISR_VC11FSYNCERR_MASK
Frame Sync Error on Virtual Channel 11.
XCSI_ISR_VC11FLVLERR_MASK
Frame Level Error on Virtual Channel 11.
XCSI_ISR_VC10FSYNCERR_MASK
Frame Sync Error on Virtual Channel 10.
XCSI_ISR_VC10FLVLERR_MASK
Frame Level Error on Virtual Channel 10.
XCSI_ISR_VC9FSYNCERR_MASK
Frame Sync Error on Virtual Channel 9.
XCSI_ISR_VC9FLVLERR_MASK
Frame Level Error on Virtual Channel 9.
XCSI_ISR_VC8FSYNCERR_MASK
Frame Sync Error on Virtual Channel 8.
XCSI_ISR_VC8FLVLERR_MASK
Frame Level Error on Virtual Channel 8.
XCSI_ISR_VC7FSYNCERR_MASK
Frame Sync Error on Virtual Channel 7.
XCSI_ISR_VC7FLVLERR_MASK
Frame Level Error on Virtual Channel 7.
XCSI_ISR_VC6FSYNCERR_MASK
Frame Sync Error on Virtual Channel 6.
XCSI_ISR_VC6FLVLERR_MASK
Frame Level Error on Virtual Channel 6.
XCSI_ISR_VC5FSYNCERR_MASK
Frame Sync Error on Virtual Channel 5.
XCSI_ISR_VC5FLVLERR_MASK
Frame Level Error on Virtual Channel 5.
XCSI_ISR_VC4FSYNCERR_MASK
Frame Sync Error on Virtual Channel 4.
XCSI_ISR_VC4FLVLERR_MASK
Frame Level Error on Virtual Channel 4.
XCSI_INTR_VCFE_MASK
Virtual channel frame error mask for VC4-15.
Referenced by XCsi_IntrHandler.
XCSI_INTR_PKTLVL_MASK
Packet level error interrupt mask.
Referenced by XCsi_IntrHandler.
XCSI_INTR_DPHY_MASK
D-PHY level error interrupt mask.
Referenced by XCsi_IntrHandler.
XCSI_INTR_SPKT_MASK
Short packet FIFO interrupt mask.
Referenced by XCsi_IntrHandler.
XCSI_INTR_FRAMERCVD_MASK
Frame received interrupt mask.
Referenced by XCsi_IntrHandler.
XCSI_INTR_VCXFE_MASK
VCX frame error interrupt mask.
Referenced by XCsi_IntrHandler.
XCSI_INTR_ERR_MASK
Other error interrupt mask.
Referenced by XCsi_IntrHandler.
XCSI_IER_FR_MASK
Frame Received.
XCSI_IER_VCXFE_MASK
VCX Frame Error.
XCSI_IER_SKEWCALHS_MASK
Skewcalchs State.
XCSI_IER_YUV420_MASK
YUV420 Word Count Error.
XCSI_IER_WC_MASK
Word Count Corruption.
XCSI_IER_ILC_MASK
Incorrect Lanes Configured.
XCSI_IER_SPFIFOF_MASK
Short Packet FIFO FULL.
XCSI_IER_SPFIFONE_MASK
Short Packet FIFO Not Empty.
XCSI_IER_SLBF_MASK
Stream Line Buffer Full.
XCSI_IER_STOP_MASK
Detect Stop State.
XCSI_IER_SOTERR_MASK
SoT Error.
XCSI_IER_SOTSYNCERR_MASK
SoT Sync Error.
XCSI_IER_ECC2BERR_MASK
ECC 2 bit Error.
XCSI_IER_ECC1BERR_MASK
ECC 1 bit Error.
XCSI_IER_CRCERR_MASK
CRC Error.
XCSI_IER_DATAIDERR_MASK
Unknown data ID packet Error.
XCSI_IER_VC3FSYNCERR_MASK
Frame Sync Error on Virtual Channel 3.
XCSI_IER_VC3FLVLERR_MASK
Frame Level Error on Virtual Channel 3.
XCSI_IER_VC2FSYNCERR_MASK
Frame Sync Error on Virtual Channel 2.
XCSI_IER_VC2FLVLERR_MASK
Frame Level Error on Virtual Channel 2.
XCSI_IER_VC1FSYNCERR_MASK
Frame Sync Error on Virtual Channel 1.
XCSI_IER_VC1FLVLERR_MASK
Frame Level Error on Virtual Channel 1.
XCSI_IER_VC0FSYNCERR_MASK
Frame Sync Error on Virtual Channel 0.
XCSI_IER_VC0FLVLERR_MASK
Frame Level Error on Virtual Channel 0.
XCSI_IER_ALLINTR_MASK
All interrupts mask.
Referenced by XCsi_InterruptClear, XCsi_IntrDisable, XCsi_IntrEnable.
XCSI_IER_FR_SHIFT
Shift bits for Frame received interrupt.
XCSI_IER_SKEWCALHS_SHIFT
Shift bits for skewcalhs status.
XCSI_IER_YUV420_SHIFT
Shift bits for YUV 420 Word Count error.
XCSI_IER_WC_SHIFT
Shift bits for Word count corruption.
XCSI_IER_ILC_SHIFT
Shift bits for Incorrect Lanes configured.
XCSI_IER_SPFIFOF_SHIFT
Shift bits for Short Packet FIFO Full.
XCSI_IER_SPFIFONE_SHIFT
Shift bits for Short Packet FIFO Not Empty.
XCSI_IER_SLBF_SHIFT
Shift bits for Stream Line Buffer Full.
XCSI_IER_STOP_SHIFT
Shift bits for Stop State.
XCSI_IER_SOTERR_SHIFT
Shift bits for Start of Transmission Error.
XCSI_IER_SOTSYNCERR_SHIFT
Shift bits for Start of Transmission Sync Error.
XCSI_IER_ECC2BERR_SHIFT
Shift bits for 2 bit ECC error.
XCSI_IER_ECC1BERR_SHIFT
Shift bits for 1 bit ECC error.
XCSI_IER_CRCERR_SHIFT
Shift bits for Packet CRC error.
XCSI_IER_DATAIDERR_SHIFT
Shift bits for Unsupported Data ID error.
XCSI_IER_VC3FSYNCERR_SHIFT
Shift bits for Virtual Channel 3 Frame Synchronisation Error.
XCSI_IER_VC3FLVLERR_SHIFT
Shift bits for Virtual Channel 3 Frame Level Error.
XCSI_IER_VC2FSYNCERR_SHIFT
Shift bits for Virtual Channel 2 Frame Synchronisation Error.
XCSI_IER_VC2FLVLERR_SHIFT
Shift bits for Virtual Channel 2 Frame Level Error.
XCSI_IER_VC1FSYNCERR_SHIFT
Shift bits for Virtual Channel 1 Frame Synchronisation Error.
XCSI_IER_VC1FLVLERR_SHIFT
Shift bits for Virtual Channel 1 Frame Level Error.
XCSI_IER_VC0FSYNCERR_SHIFT
Shift bits for Virtual Channel 0 Frame Synchronisation Error.
XCSI_IER_VC0FLVLERR_SHIFT
Shift bits for Virtual Channel 0 Frame Level Error.
XCSI_SPKTR_DATA_MASK
16 bit short packet data Received
Referenced by XCsi_GetShortPacket.
XCSI_SPKTR_VC_MASK
Virtual channel number.
Referenced by XCsi_GetShortPacket.
XCSI_SPKTR_DT_MASK
Data Type.
Referenced by XCsi_GetShortPacket.
XCSI_SPKTR_DATA_SHIFT
Shift bits for Short Packet Data.
Referenced by XCsi_GetShortPacket.
XCSI_SPKTR_VC_SHIFT
Shift bits for Short Packet Virtual Channel Data.
Referenced by XCsi_GetShortPacket.
XCSI_SPKTR_DT_SHIFT
Bit Shift for Short Packet Data Type.
Referenced by XCsi_GetShortPacket.
XCSI_CLKINFR_STOP_MASK
Stop State on clock lane.
Referenced by XCsi_GetClkLaneInfo.
XCSI_CLKINFR_STOP_SHIFT
Shift bits for Clock Lane Stop bit.
Referenced by XCsi_GetClkLaneInfo.
XCSI_LXINFR_STOP_MASK
Stop State on clock lane.
Referenced by XCsi_GetDataLaneInfo.
XCSI_LXINFR_SKEWCALHS_MASK
SkewcalHs State on clock lane.
Referenced by XCsi_GetDataLaneInfo.
XCSI_LXINFR_SOTERR_MASK
Detection of ErrSoTHS.
Referenced by XCsi_GetDataLaneInfo.
XCSI_LXINFR_SOTSYNCERR_MASK
Detection of ErrSoTSyncHS.
Referenced by XCsi_GetDataLaneInfo.
XCSI_LXINFR_STOP_SHIFT
Bit Shift for Data Lane Stop State.
Referenced by XCsi_GetDataLaneInfo.
XCSI_LXINFR_SKEWCALHS_SHIFT
Bit Shift for Data Lane SkewCalHs State.
Referenced by XCsi_GetDataLaneInfo.
XCSI_LXINFR_SOTERR_SHIFT
Bit Shift for Start of Transmission Error.
Referenced by XCsi_GetDataLaneInfo.
XCSI_LXINFR_SOTSYNCERR_SHIFT
Bit Shift for Start of Transmission Sync Error.
Referenced by XCsi_GetDataLaneInfo.
XCSI_VCXINF1R_LINECOUNT_MASK
Number of long packets written into line buffer.
Referenced by XCsi_GetVCInfo.
XCSI_VCXINF1R_BYTECOUNT_MASK
Byte count of current packet in process.
Referenced by XCsi_GetVCInfo.
XCSI_VCXINF1R_LINECOUNT_SHIFT
Shift bits for Virtual Channel Line Count bits.
Referenced by XCsi_GetVCInfo.
XCSI_VCXINF1R_BYTECOUNT_SHIFT
Shift bits for Virtual Channel Byte Count bits.
Referenced by XCsi_GetVCInfo.
XCSI_VCXINF2R_DATATYPE_MASK
Data type of current packet.
Referenced by XCsi_GetVCInfo.
XCSI_VCXINF2R_DATATYPE_SHIFT
Bit Shift for Virtual Channel Data Type.
Referenced by XCsi_GetVCInfo.
typedef void(* XCsi_CallBack)(void *CallBackRef, u32 Mask))(void *CallBackRef, u32 Mask)
Callback type for all interrupts defined.
CallBackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. Mask is a bit mask indicating the cause of the event. For current core version, this parameter is "OR" of 0 or more XCSI_ISR_*_MASK constants defined in xcsi_hw.h. None. None.
static void StubErrCallBack(void *Callbackref, u32 ErrorMask)
Stub callback function for asynchronous error interrupts.
This routine is a stub for the asynchronous error interrupt callback.Each of callback functions to be called on different types of interrupts. These stub functions are set during XCsi_CfgInitialize as default callback functions. If application is not registered any of the callback function, these functions will be called for doing nothing.The stub is here in case the upper layer forgot to set the handler. On initialization, Error interrupt handler is set to this callback. It is considered an error for this handler to be invoked. Callbackref is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. ErrorMask is a bit mask indicating the cause of the error. Its value equals 'OR'ing one or more XCSI_ISR_*_MASK values defined in xcsi_hw.h. None. None.
u32 XCsi_CfgInitialize(XCsi *InstancePtr, XCsi_Config *CfgPtr, UINTPTR EffectiveAddr)
Initialize the XCsi instance provided by the caller based on the given Config structure.
Initialize the CSI driver. InstancePtr is the XCsi instance to operate on. CfgPtr is the device configuration structure containing information about a specific CSI. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if initialization was successful. None. This function initializes the CSI driver/device. This function must be called prior to using the driver. Initialization includes setting up the instance data and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the XCsi instance. CfgPtr is a reference to a structure containing information about a specific XCsi instance. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if initialization was successful.XST_FAILURE if initialization failed. None.
References XCsi_Config::BaseAddr, XCsi::Config, XCsi::DPhyLvlErrCallBack, XCsi::ErrorCallBack, XCsi::FrameRecvdCallBack, XCsi::IsReady, XCsi::PktLvlErrCallBack, XCsi::ProtDecodeErrCallBack, XCsi::ShortPacketCallBack, XCsi::VCXErrCallBack.
Referenced by CsiSelfTestExample.
u32 XCsi_Reset(XCsi *InstancePtr)
This function will do a reset of the IP.
Reset the CSI controller.This will reset the values of all registers except Core Config and Protocol Config registers. InstancePtr is the XCsi instance to operate on. XST_SUCCESS on proper reset.XST_FAILURE on timeout and core being stuck in reset. None. This function resets the CSI controller. InstancePtr is a pointer to the XCsi instance. XST_SUCCESS if reset was successful.XST_FAILURE if reset failed. None.
References XCSI_RESET_TIMEOUT.
u32 XCsi_Activate(XCsi *InstancePtr, u8 Flag)
This function will enable/disable the IP Core to start processing.
Activate or deactivate the CSI controller. InstancePtr is the XCsi instance to operate on. Flag will be used to indicate Enable or Disable action. XST_SUCCESS on successful core enable or disable.XST_FAILURE if core disable times out. None. This function activates or deactivates the CSI controller based on the Flag parameter. InstancePtr is a pointer to the XCsi instance. Flag is the enable/disable flag. Set to 1 to enable, 0 to disable. XST_SUCCESS if operation was successful.XST_FAILURE if operation failed. None.
References XCsi::IsReady, XCSI_DISABLE, XCSI_ENABLE, XCSI_RESET_TIMEOUT.
u32 XCsi_Configure(XCsi *InstancePtr)
This function will configure the core with proper number of Active Lanes.
Configure the CSI controller. InstancePtr is the XCsi instance to operate on. XST_SUCCESS on configuring the core.XST_FAILURE if active lanes not set correctly. None. This function configures the CSI controller with the active lanes setting. InstancePtr is a pointer to the XCsi instance. XST_SUCCESS if configuration was successful.XST_FAILURE if configuration failed. None.
References XCsi::ActiveLanes, XCsi_Config::BaseAddr, XCsi::Config, XCsi_Config::FixedLanes, XCsi::IsReady, XCsi_GetIntrEnable, XCSI_GIER_OFFSET, XCsi_IntrEnable, XCsi_IsActiveLaneCountValid, XCSI_RESET_TIMEOUT.
void XCsi_SetVCSelection(XCsi *InstancePtr, u16 Value)
This function will control the virtual channels selection dynamically.
Set the virtual channel selection. InstancePtr is the XCsi instance to operate on. Value will set the virtual channels corresponding to each bit value. bit value 1: core processes packets with this VC, bit value 0: core filters packets with this VC. None. None. This function sets the virtual channel selection for filtering. InstancePtr is a pointer to the XCsi instance. Value is the virtual channel selection value to be set. None. None.
References XCsi_Config::BaseAddr, XCsi::Config, XCSI_VC_SEL_OFFSET.
u32 XCsi_GetVCSelection(XCsi *InstancePtr)
This function will return the virtual channels selected.
Get the virtual channel selection. InstancePtr is the XCsi instance to operate on. Value of selected VCs. None. This function returns the current virtual channel selection. InstancePtr is a pointer to the XCsi instance. Virtual channel selection value. None.
References XCsi_Config::BaseAddr, XCsi::Config, XCSI_VC_SEL_OFFSET.
void XCsi_GetShortPacket(XCsi *InstancePtr, XCsi_SPktData *ShortPacketStruct)
This function will get the short packet received in the FIFO from the Generic Short Packet Register and fill up the structure passed from caller.
Get short packet information. InstancePtr is the XCsi instance to operate on. ShortPacketStruct is going to be filled up by this function and returned to the caller. None. None. This function retrieves the short packet information from the controller. InstancePtr is a pointer to the XCsi instance. ShortPacketStruct is a pointer to the structure where short packet data will be stored. None. None.
References XCsi_Config::BaseAddr, XCsi::Config, XCsi_SPktData::Data, XCsi_SPktData::DataType, XCsi_SPktData::VirtualChannel, XCSI_SPKTR_DATA_MASK, XCSI_SPKTR_DATA_SHIFT, XCSI_SPKTR_DT_MASK, XCSI_SPKTR_DT_SHIFT, XCSI_SPKTR_OFFSET, XCSI_SPKTR_VC_MASK, XCSI_SPKTR_VC_SHIFT.
void XCsi_GetClkLaneInfo(XCsi *InstancePtr, XCsi_ClkLaneInfo *ClkLane)
This function will get the information about the state of the Clock Lane.
Get clock lane information. InstancePtr is the XCsi instance to operate on. ClkLane is going to be filled up by this function and returned to the caller. None. None. This function retrieves the clock lane information from the controller. InstancePtr is a pointer to the XCsi instance. ClkLane is a pointer to the structure where clock lane info will be stored. None. None.
References XCsi_Config::BaseAddr, XCsi::Config, XCsi_ClkLaneInfo::StopState, XCSI_CLKINFR_OFFSET, XCSI_CLKINFR_STOP_MASK, XCSI_CLKINFR_STOP_SHIFT.
void XCsi_GetDataLaneInfo(XCsi *InstancePtr, u8 Lane, XCsi_DataLaneInfo *DataLane)
This function will get the information about the state of a Data Lane.
Get data lane information. InstancePtr is the XCsi instance to operate on. Lane is the Lane number whose information is requested. DataLane is going to be filled up by this function and returned to the caller. None. None. This function retrieves the data lane information for a specific lane. InstancePtr is a pointer to the XCsi instance. Lane is the lane number (0 to 3) for which to get information. DataLane is a pointer to the structure where data lane info will be stored. None. None.
References XCsi_Config::BaseAddr, XCsi::Config, XCsi_DataLaneInfo::SkewCalHs, XCsi_DataLaneInfo::SoTErr, XCsi_DataLaneInfo::SoTSyncErr, XCsi_DataLaneInfo::StopState, XCSI_L0INFR_OFFSET, XCSI_L1INFR_OFFSET, XCSI_L2INFR_OFFSET, XCSI_L3INFR_OFFSET, XCSI_LXINFR_SKEWCALHS_MASK, XCSI_LXINFR_SKEWCALHS_SHIFT, XCSI_LXINFR_SOTERR_MASK, XCSI_LXINFR_SOTERR_SHIFT, XCSI_LXINFR_SOTSYNCERR_MASK, XCSI_LXINFR_SOTSYNCERR_SHIFT, XCSI_LXINFR_STOP_MASK, XCSI_LXINFR_STOP_SHIFT.
void XCsi_GetVCInfo(XCsi *InstancePtr, u8 Vc, XCsi_VCInfo *VCInfo)
This function will get the line count, byte count and data type information about a Virtual Channel.
Get virtual channel information. InstancePtr is the XCsi instance to operate on. Vc is the Virtual Channel number whose information is requested. VCInfo is going to be filled up by this function and returned to the caller. None. None. This function retrieves the virtual channel information. InstancePtr is a pointer to the XCsi instance. Vc is the virtual channel number for which to get information. VCInfo is a pointer to the structure where virtual channel info will be stored. None. None.
References XCsi_Config::BaseAddr, XCsi_VCInfo::ByteCount, XCsi::Config, XCsi_VCInfo::DataType, XCsi_VCInfo::LineCount, XCSI_MAX_VC, XCSI_VC0INF1R_OFFSET, XCSI_VC1INF1R_OFFSET, XCSI_VCXINF1R_BYTECOUNT_MASK, XCSI_VCXINF1R_BYTECOUNT_SHIFT, XCSI_VCXINF1R_LINECOUNT_MASK, XCSI_VCXINF1R_LINECOUNT_SHIFT, XCSI_VCXINF2R_DATATYPE_MASK, XCSI_VCXINF2R_DATATYPE_SHIFT.
u8 XCsi_IsActiveLaneCountValid(XCsi *InstancePtr, u8 ActiveLanesCount)
This function checks the validity of the active lanes parameter.
Check if active lane count is valid. InstancePtr is a pointer to the Subsystem instance to be worked on. ActiveLanesCount is the lane count to check if valid. 1 if specified Active Lanes is valid.0 otherwise, if the Active Lanes specified isn't valid as per spec and design. None. This function validates if the specified active lane count is valid for the current configuration. InstancePtr is a pointer to the XCsi instance. ActiveLanesCount is the active lane count to be validated. 1 if the active lane count is valid.0 if the active lane count is invalid. None.
References XCsi::Config, XCsi_Config::FixedLanes, XCsi_Config::MaxLanesPresent.
Referenced by XCsi_Configure.
static void XCsi_BitSet(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask)
This function is used to set bit in a register.
BaseAddress is a base address of IP. RegisterOffset is offset where the register is present. BitMask of bit to be set. None. None.
static void XCsi_BitReset(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask)
This function is used to reset bit in a register.
BaseAddress is a base address of IP. RegisterOffset is offset where the register is present. BitMask of bit to be reset. None. None.
static u32 XCsi_GetBitField(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask, u32 BitShift)
This function is used to get the value of bitfield from register.
BaseAddress is a base address of IP. RegisterOffset is offset where the register is present. BitMask of bit fields to be retrieved. BitShift is offset of the field in register. Bit Field Value in u32 format. None.
static void XCsi_SetBitField(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask, u32 BitShift, u32 Value)
This function is used to set the value of bitfield from register.
BaseAddress is a base address of IP. RegisterOffset is offset where the register is present. BitMask of bit fields to be retrieved. BitShift is offset of the field in register. Value is to be set. Passed in u32 format. None. None.
static void XCsi_SetSoftReset(XCsi *InstancePtr)
This function is used to start the soft reset process by setting the soft reset bit in the Core Configuration Register.
InstancePtr is a pointer to the CSI2 instance to be worked on. None. None.
static void XCsi_ClearSoftReset(XCsi *InstancePtr)
This function is used to stop the soft reset process by resetting the soft reset bit in the Core Configuration Register.
This is done usually after Reset in Progress is 0. InstancePtr is a pointer to the CSI Instance to be worked on. None. None.
static void XCsi_Disable(XCsi *InstancePtr)
This function is used to stop the packet processing by resetting Enable core bit in the Core Configuration Register.
InstancePtr is a pointer to the CSI Instance to be worked on. None. None.
static void XCsi_Enable(XCsi *InstancePtr)
This function is used to start the packet processing by setting Enable core bit in the Core Configuration Register.
This is done after the configuration of active lanes, interrupt masks, etc. InstancePtr is a pointer to the CSI Instance to be worked on. None. None.
static u32 XCsi_IsCsiEnabled(XCsi *InstancePtr)
This function is used to check if the Core is enabled by checking the core enable bit.
InstancePtr is a pointer to the CSI Instance to be worked on. 1 - If the CSI core is enabled.0 - If the CSI core is disabled. None.
static u32 XCsi_GetMaxLaneCount(XCsi *InstancePtr)
This function is used to get the number of lanes configured in the IP.
InstancePtr is a pointer to the CSI Instance to be worked on. Max number of lanes available in u32 format. None.
static u32 XCsi_GetActiveLaneCount(XCsi *InstancePtr)
This function is used to get the actual number of lanes being used by the IP to communicate with a CSI2 Tx.
This is lesser or equal to Max lanes. InstancePtr is a pointer to the CSI Instance to be worked on. Number of lanes being used in u32 format. None.
static void XCsi_SetActiveLaneCount(XCsi *InstancePtr, u32 Value)
This function is used to set the actual number of lanes to be used to communicate with a CSI2 Tx.
This is lesser than or equal to Max lanes. InstancePtr is a pointer to the CSI Instance to be worked on. Value is number of lanes to be made active. None. None.
static u32 XCsi_GetCurrentPacketCount(XCsi *InstancePtr)
This function is used to get the number of long packets received.
InstancePtr is a pointer to the CSI Instance to be worked on. Number of Packets received. None.
static u32 XCsi_IsShortPacketFIFOFull(XCsi *InstancePtr)
This function is used to check if the Short Packet FIFO is full or not.
InstancePtr is a pointer to the CSI Instance to be worked on. 1 - If the Short Packet FIFO Full.0 - If the Short Packet FIFO available. None.
static u32 XCsi_IsShortPacketFIFONotEmpty(XCsi *InstancePtr)
This function is used to check if the Short Packet FIFO is not empty.
InstancePtr is a pointer to the CSI Instance to be worked on. 1 - If the Short Packet FIFO is not Empty.0 - If the Short Packet FIFO is Empty. None.
static u32 XCsi_IsStreamLineBuffFull(XCsi *InstancePtr)
This function is used to check if the Stream Line Buffer is full or not.
InstancePtr is a pointer to the CSI Instance to be worked on. 1 - If the Stream line buffer is full.0 - If the Stream line buffer is not full. None.
static u32 XCsi_IsSoftResetInProgress(XCsi *InstancePtr)
This function is used to check if a reset is completed or is in progress.
InstancePtr is a pointer to the CSI Instance to be worked on. 1 - If the Soft reset operation is in progress.0 - If the Soft reset operation is completed. None.
static void XCsi_SetGlobalInterrupt(XCsi *InstancePtr)
This function is used to enable the global interrupts.
This is used after setting the interrupts mask before enabling the core. InstancePtr is a pointer to the CSI Instance to be worked on. None. None.
static void XCsi_ResetGlobalInterrupt(XCsi *InstancePtr)
This function is used to disable the global interrupts.
This is done after disabling the core. InstancePtr is a pointer to the CSI Instance to be worked on. None. None.
XCsi_Config * XCsi_LookupConfig(UINTPTR BaseAddress)
Lookup the device configuration based on the base address.
Look up the hardware configuration for a device instance.This function returns a reference to an XCsi_Config structure based on the base address. This function will return a NULL pointer if the base address is not found. BaseAddress is the base address of the device to lookup for. XCsi_Config reference if BaseAddress is found, NULL otherwise. None. DeviceId is the unique device ID of the device to lookup for The reference to the configuration record in the configuration table (in xcsi_g.c) corresponding to the Device ID or if not found,a NULL pointer is returned. None
Referenced by CsiSelfTestExample.
u32 XCsi_SelfTest(XCsi *InstancePtr)
Run a self-test on the CSI controller.
Runs a self-test on the driver/device.This function runs a self-test on the CSI controller/device. The self-test checks for proper functionality of the controller. InstancePtr is a pointer to the XCsi instance. XST_SUCCESS if self-test was successful.XST_FAILURE if self-test failed. None. This test checks if the LaneCount present in register matches the one from the generated file. InstancePtr is a pointer to the XCsi instance. XST_SUCCESS if self-test was successful XST_FAILURE if the read value was not equal to _g.c file None
References XCsi_Config::BaseAddr, XCsi::Config, XCsi::IsReady, XCsi_Config::MaxLanesPresent, XCSI_PCR_MAXLANES_MASK, XCSI_PCR_MAXLANES_SHIFT, XCSI_PCR_OFFSET.
Referenced by CsiSelfTestExample.
void XCsi_IntrHandler(void *InstancePtr)
Interrupt handler for the CSI controller.
This function is the interrupt handler for the CSI2 Rx core.This function is the interrupt handler for the CSI driver. It processes all pending interrupts and routes them to the appropriate callback handlers. InstancePtr is a pointer to the XCsi instance (passed as void *). None. This function should be connected to the interrupt system. This handler reads the pending interrupt from the Interrupt Status register, determines the source of the interrupts and calls the respective callbacks for the interrupts that are enabled in Interrupt Enable register, and finally clears the interrupts.The application is responsible for connecting this function to the interrupt system. Application beyond this core is also responsible for providing callbacks to handle interrupts and installing the callbacks using XCsi_SetCallBack() during initialization phase. InstancePtr is a pointer to the XCsi core instance. None. Interrupt should be enabled to execute interrupt handler.
References XCsi_Config::BaseAddr, XCsi::Config, XCsi::DPhyLvlErrCallBack, XCsi::DPhyLvlErrRef, XCsi::ErrorCallBack, XCsi::ErrRef, XCsi::FrameRecvdCallBack, XCsi::FrameRecvdRef, XCsi::IsReady, XCsi::PktLvlErrCallBack, XCsi::PktLvlErrRef, XCsi::ProtDecErrRef, XCsi::ProtDecodeErrCallBack, XCsi::ShortPacketCallBack, XCsi::ShortPacketRef, XCsi::VCXErrCallBack, XCsi::VCXErrRef, XCsi_GetIntrEnable, XCsi_GetIntrStatus, XCsi_InterruptClear, XCSI_INTR_DPHY_MASK, XCSI_INTR_ERR_MASK, XCSI_INTR_FRAMERCVD_MASK, XCSI_INTR_PKTLVL_MASK, XCSI_INTR_PROT_MASK, XCSI_INTR_SPKT_MASK, XCSI_INTR_VCFE_MASK, XCSI_INTR_VCXFE_MASK, XCSI_VCX_FE_OFFSET.
int XCsi_SetCallBack(XCsi *InstancePtr, u32 HandleType, void *Callbackfunc, void *Callbackref)
Set callback function for interrupt handling.
This routine installs an asynchronous callback function for the given HandlerType:This function sets a callback function for a specific interrupt handler type. The registered callback function will be called when the corresponding interrupt occurs. InstancePtr is a pointer to the XCsi instance. HandleType is the type of handler to register. It can be one of: XCSI_HANDLER_DPHYXCSI_HANDLER_PKTLVLXCSI_HANDLER_PROTLVLXCSI_HANDLER_SHORTPACKETXCSI_HANDLER_FRAMERECVDXCSI_HANDLER_VCXERRXCSI_HANDLER_OTHERERROR Callbackfunc is the address of the callback function. Callbackref is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback was successfully registered.XST_FAILURE if callback registration failed. None. HandlerType Callback Function Type ---------------------------- -------------------------------------------- (XCSI_HANDLER_DPHY) DPhyLvlErrCallBack (XCSI_HANDLER_PROTLVL) ProtDecodeErrCallBack (XCSI_HANDLER_PKTLVL) PktLvlErrCallBack (XCSI_HANDLER_SHORTPACKET) ShortPacketCallBack (XCSI_HANDLER_FRAMERECVD) FrameRecvdCallBack (XCSI_HANDLER_VCXERR) VCXErrCallBack (XCSI_HANDLER_OTHERERROR) ErrorCallBack InstancePtr is the XCsi instance to operate on HandleType is the type of call back to be registered. Callbackfunc is the pointer to a call back function which is called when a particular event occurs. Callbackref is a void pointer to data to be referenced to by the Callbackfunc XST_SUCCESS when handler is installed. XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XCsi::DPhyLvlErrCallBack, XCsi::DPhyLvlErrRef, XCsi::ErrorCallBack, XCsi::ErrRef, XCsi::FrameRecvdCallBack, XCsi::FrameRecvdRef, XCsi::IsReady, XCsi::PktLvlErrCallBack, XCsi::PktLvlErrRef, XCsi::ProtDecErrRef, XCsi::ProtDecodeErrCallBack, XCsi::ShortPacketCallBack, XCsi::ShortPacketRef, XCsi::VCXErrCallBack, XCsi::VCXErrRef, XCSI_HANDLER_DPHY, XCSI_HANDLER_FRAMERECVD, XCSI_HANDLER_OTHERERROR, XCSI_HANDLER_PKTLVL, XCSI_HANDLER_PROTLVL, XCSI_HANDLER_SHORTPACKET, XCSI_HANDLER_VCXERR.
u32 XCsi_GetIntrEnable(XCsi *InstancePtr)
Get the current interrupt enable mask.
This function will get the interrupt mask set (enabled) in the CSI2 Rx core.This function returns the current interrupt enable mask. InstancePtr is a pointer to the XCsi instance. Current interrupt enable mask. None. InstancePtr is the XCsi instance to operate on Interrupt Mask with bits set for corresponding interrupt in Interrupt enable register None
References XCsi_Config::BaseAddr, XCsi::Config, XCSI_IER_OFFSET.
Referenced by XCsi_Configure, XCsi_IntrHandler.
void XCsi_IntrEnable(XCsi *InstancePtr, u32 Mask)
Enable specific interrupts.
This function will enable the interrupts present in the interrupt mask passed onto the function.This function enables the specified interrupts in the CSI controller. InstancePtr is a pointer to the XCsi instance. Mask is the bit-mask of the interrupts to be enabled. None. None. InstancePtr is the XCsi instance to operate on Mask is the interrupt mask which need to be enabled in core None None
References XCsi_Config::BaseAddr, XCsi::Config, XCSI_IER_ALLINTR_MASK, XCSI_IER_OFFSET.
Referenced by XCsi_Configure.
void XCsi_IntrDisable(XCsi *InstancePtr, u32 Mask)
Disable specific interrupts.
This function will disable the interrupts present in the interrupt mask passed onto the function.This function disables the specified interrupts in the CSI controller. InstancePtr is a pointer to the XCsi instance. Mask is the bit-mask of the interrupts to be disabled. None. None. InstancePtr is the XCsi instance to operate on Mask is the interrupt mask which need to be enabled in core None None
References XCsi_Config::BaseAddr, XCsi::Config, XCSI_IER_ALLINTR_MASK, XCSI_IER_OFFSET.
u32 XCsi_GetIntrStatus(XCsi *InstancePtr)
Get the interrupt status.
This function will get the list of interrupts pending in the Interrupt Status Register of the CSI2 Rx core.This function returns the current interrupt status register value. InstancePtr is a pointer to the XCsi instance. Current interrupt status. None. InstancePtr is the XCsi instance to operate on Interrupt Mask with bits set for corresponding interrupt in Interrupt Status register None
References XCsi_Config::BaseAddr, XCsi::Config, XCSI_ISR_OFFSET.
Referenced by XCsi_IntrHandler.
void XCsi_InterruptClear(XCsi *InstancePtr, u32 Mask)
Clear specific interrupts.
This function will clear the interrupts set in the Interrupt Status Register of the CSI2 Rx core.This function clears the specified interrupts in the CSI controller. InstancePtr is a pointer to the XCsi instance. Mask is the bit-mask of the interrupts to be cleared. None. None. InstancePtr is the XCsi instance to operate on Mask is Interrupt Mask with bits set for corresponding interrupt to be cleared in the Interrupt Status register None None
References XCsi_Config::BaseAddr, XCsi::Config, XCSI_IER_ALLINTR_MASK, XCSI_ISR_ALLINTR_MASK, XCSI_ISR_OFFSET.
Referenced by XCsi_IntrHandler.
static u32 XCsi_ReadReg(UINTPTR BaseAddress, u32 RegOffset)
Static inline function to read data from CSI register space.
BaseAddress is the base address of CSI RegOffset is the register offset. Value of the register. None
static void XCsi_WriteReg(UINTPTR BaseAddress, u32 RegOffset, u32 Data)
Static inline function to write data to CSI register space.
BaseAddress is the base address of CSI RegOffset is the register offset. Data is the value to be written to the register. None. None.
XCSI_RESET_TIMEOUT
Timeout count for CSI soft reset.
Referenced by XCsi_Activate, XCsi_Configure, XCsi_Reset.
XCSI_H_
Prevent circular inclusions by using protection macros.
XCSI_ENABLE
Flag denoting enabling of CSI.
Referenced by XCsi_Activate.
XCSI_DISABLE
Flag denoting disabling of CSI.
Referenced by XCsi_Activate.
XCSI_MAX_LANES
Max Lanes supported by CSI.
XCSI_V10_MAX_VC
Max Virtual Channels supported for v1.0.
XCSI_V20_MAX_VC
Max Virtual Channels supported for v2.0.
XCSI_MAX_VC
Max Virtual Channels supported for CSI.
Referenced by XCsi_GetVCInfo.
XCSI_HW_H_
Prevent circular inclusions by using protection macros.