xcsi_intr.c
void XCsi_IntrEnable(XCsi *InstancePtr, u32 Mask)
Enable specific interrupts.
This function will enable the interrupts present in the interrupt mask passed onto the function.This function enables the specified interrupts in the CSI controller. InstancePtr is a pointer to the XCsi instance. Mask is the bit-mask of the interrupts to be enabled. None. None. InstancePtr is the XCsi instance to operate on Mask is the interrupt mask which need to be enabled in core None None
References XCsi_Config::BaseAddr, XCsi::Config, XCSI_IER_ALLINTR_MASK, XCSI_IER_OFFSET.
Referenced by XCsi_Configure.
void XCsi_IntrDisable(XCsi *InstancePtr, u32 Mask)
Disable specific interrupts.
This function will disable the interrupts present in the interrupt mask passed onto the function.This function disables the specified interrupts in the CSI controller. InstancePtr is a pointer to the XCsi instance. Mask is the bit-mask of the interrupts to be disabled. None. None. InstancePtr is the XCsi instance to operate on Mask is the interrupt mask which need to be enabled in core None None
References XCsi_Config::BaseAddr, XCsi::Config, XCSI_IER_ALLINTR_MASK, XCSI_IER_OFFSET.
u32 XCsi_GetIntrEnable(XCsi *InstancePtr)
Get the current interrupt enable mask.
This function will get the interrupt mask set (enabled) in the CSI2 Rx core.This function returns the current interrupt enable mask. InstancePtr is a pointer to the XCsi instance. Current interrupt enable mask. None. InstancePtr is the XCsi instance to operate on Interrupt Mask with bits set for corresponding interrupt in Interrupt enable register None
References XCsi_Config::BaseAddr, XCsi::Config, XCSI_IER_OFFSET.
Referenced by XCsi_Configure, XCsi_IntrHandler.
u32 XCsi_GetIntrStatus(XCsi *InstancePtr)
Get the interrupt status.
This function will get the list of interrupts pending in the Interrupt Status Register of the CSI2 Rx core.This function returns the current interrupt status register value. InstancePtr is a pointer to the XCsi instance. Current interrupt status. None. InstancePtr is the XCsi instance to operate on Interrupt Mask with bits set for corresponding interrupt in Interrupt Status register None
References XCsi_Config::BaseAddr, XCsi::Config, XCSI_ISR_OFFSET.
Referenced by XCsi_IntrHandler.
void XCsi_InterruptClear(XCsi *InstancePtr, u32 Mask)
Clear specific interrupts.
This function will clear the interrupts set in the Interrupt Status Register of the CSI2 Rx core.This function clears the specified interrupts in the CSI controller. InstancePtr is a pointer to the XCsi instance. Mask is the bit-mask of the interrupts to be cleared. None. None. InstancePtr is the XCsi instance to operate on Mask is Interrupt Mask with bits set for corresponding interrupt to be cleared in the Interrupt Status register None None
References XCsi_Config::BaseAddr, XCsi::Config, XCSI_IER_ALLINTR_MASK, XCSI_ISR_ALLINTR_MASK, XCSI_ISR_OFFSET.
Referenced by XCsi_IntrHandler.
int XCsi_SetCallBack(XCsi *InstancePtr, u32 HandleType, void *Callbackfunc, void *Callbackref)
Set callback function for interrupt handling.
This routine installs an asynchronous callback function for the given HandlerType:This function sets a callback function for a specific interrupt handler type. The registered callback function will be called when the corresponding interrupt occurs. InstancePtr is a pointer to the XCsi instance. HandleType is the type of handler to register. It can be one of: XCSI_HANDLER_DPHYXCSI_HANDLER_PKTLVLXCSI_HANDLER_PROTLVLXCSI_HANDLER_SHORTPACKETXCSI_HANDLER_FRAMERECVDXCSI_HANDLER_VCXERRXCSI_HANDLER_OTHERERROR Callbackfunc is the address of the callback function. Callbackref is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback was successfully registered.XST_FAILURE if callback registration failed. None. HandlerType Callback Function Type ---------------------------- -------------------------------------------- (XCSI_HANDLER_DPHY) DPhyLvlErrCallBack (XCSI_HANDLER_PROTLVL) ProtDecodeErrCallBack (XCSI_HANDLER_PKTLVL) PktLvlErrCallBack (XCSI_HANDLER_SHORTPACKET) ShortPacketCallBack (XCSI_HANDLER_FRAMERECVD) FrameRecvdCallBack (XCSI_HANDLER_VCXERR) VCXErrCallBack (XCSI_HANDLER_OTHERERROR) ErrorCallBack InstancePtr is the XCsi instance to operate on HandleType is the type of call back to be registered. Callbackfunc is the pointer to a call back function which is called when a particular event occurs. Callbackref is a void pointer to data to be referenced to by the Callbackfunc XST_SUCCESS when handler is installed. XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XCsi::DPhyLvlErrCallBack, XCsi::DPhyLvlErrRef, XCsi::ErrorCallBack, XCsi::ErrRef, XCsi::FrameRecvdCallBack, XCsi::FrameRecvdRef, XCsi::IsReady, XCsi::PktLvlErrCallBack, XCsi::PktLvlErrRef, XCsi::ProtDecErrRef, XCsi::ProtDecodeErrCallBack, XCsi::ShortPacketCallBack, XCsi::ShortPacketRef, XCsi::VCXErrCallBack, XCsi::VCXErrRef, XCSI_HANDLER_DPHY, XCSI_HANDLER_FRAMERECVD, XCSI_HANDLER_OTHERERROR, XCSI_HANDLER_PKTLVL, XCSI_HANDLER_PROTLVL, XCSI_HANDLER_SHORTPACKET, XCSI_HANDLER_VCXERR.
void XCsi_IntrHandler(void *InstancePtr)
Interrupt handler for the CSI controller.
This function is the interrupt handler for the CSI2 Rx core.This function is the interrupt handler for the CSI driver. It processes all pending interrupts and routes them to the appropriate callback handlers. InstancePtr is a pointer to the XCsi instance (passed as void *). None. This function should be connected to the interrupt system. This handler reads the pending interrupt from the Interrupt Status register, determines the source of the interrupts and calls the respective callbacks for the interrupts that are enabled in Interrupt Enable register, and finally clears the interrupts.The application is responsible for connecting this function to the interrupt system. Application beyond this core is also responsible for providing callbacks to handle interrupts and installing the callbacks using XCsi_SetCallBack() during initialization phase. InstancePtr is a pointer to the XCsi core instance. None. Interrupt should be enabled to execute interrupt handler.
References XCsi_Config::BaseAddr, XCsi::Config, XCsi::DPhyLvlErrCallBack, XCsi::DPhyLvlErrRef, XCsi::ErrorCallBack, XCsi::ErrRef, XCsi::FrameRecvdCallBack, XCsi::FrameRecvdRef, XCsi::IsReady, XCsi::PktLvlErrCallBack, XCsi::PktLvlErrRef, XCsi::ProtDecErrRef, XCsi::ProtDecodeErrCallBack, XCsi::ShortPacketCallBack, XCsi::ShortPacketRef, XCsi::VCXErrCallBack, XCsi::VCXErrRef, XCsi_GetIntrEnable, XCsi_GetIntrStatus, XCsi_InterruptClear, XCSI_INTR_DPHY_MASK, XCSI_INTR_ERR_MASK, XCSI_INTR_FRAMERCVD_MASK, XCSI_INTR_PKTLVL_MASK, XCSI_INTR_PROT_MASK, XCSI_INTR_SPKT_MASK, XCSI_INTR_VCFE_MASK, XCSI_INTR_VCXFE_MASK, XCSI_VCX_FE_OFFSET.