xilpki-api
Xpki_OpsType
ECC NIST P-192 signature generation.
XPki_EcdsaCrvType
NIST P-192 curve.
XPki_EcdsaCrv
ECC Binary curve.
void* XPki_Request_Info::PtrInputData
Pointer to the input data.
Referenced by XPki_EcdsaGenerateKeyPair, XPki_EcdsaPwct, XPki_EcdsaSignGenerateKat, XPki_EcdsaVerifySignKat.
void* XPki_Request_Info::PtrOutputData
Pointer to the output data.
Referenced by XPki_EcdsaGenerateKeyPair, XPki_EcdsaPwct, XPki_EcdsaSignGenerateKat.
Xpki_OpsType XPki_Request_Info::OpsType
ECC operation type.
Referenced by XilPki_EnQueue, XPki_EcdsaGenerateKeyPair, XPki_EcdsaPwct, XPki_EcdsaSignGenerateKat, XPki_EcdsaVerifySignKat.
void(* XPki_Request_Info::XPki_CompletionCallBack)(u32 RequestID, u32 Status))(u32 RequestID, u32 Status)
Request completion callback function pointer.
Referenced by XPki_EcdsaGenerateKeyPair, XPki_EcdsaPwct, XPki_EcdsaSignGenerateKat, XPki_EcdsaVerifySignKat.
static u32 XPki_GetLibVersion(void)
This function returns the version number of xilpki library.
32-bit version number
void XPki_Reset(void)
This function reset the PKI module.
Referenced by XPki_Initialize.
void XPki_SoftReset(void)
This function performs the PKI module soft reset.
Referenced by XPki_Initialize.
int XPki_Initialize(XPki_Instance *InstancePtr)
This function performs the PKI module initialization.
InstancePtr Pointer to the XPki instance XST_SUCCESS - On successXPKI_INVALID_PARAM - On invalid argumentXPKI_ERROR_UNALIGN_ADDR - On Request/Completion queue Address are not Word aligned.XST_FAILURE - On failure
References XPKI_INVALID_PARAM, XPki_Reset, XPki_SoftReset.
int XPki_EcdsaGenerateKeyPair(XPki_Instance *InstancePtr, XPki_EcdsaCrvType CrvType, XPki_EcdsaKey *PubKey, u8 *PrivKey)
This function Generate key pairs for the ECC curves NIST-P192, P256, P384, and P521.
InstancePtr Pointer to the XPki instance CrvType Type of ECC curve(NIST-P192,P256,P384, and P521) PubKey Pointer to the pulic-key buffer PrivKey Pointer to the private-key buffer XST_SUCCESS - when passesErrorcode - when fails
References ECC_NIST_P192, ECC_NIST_P256, ECC_NIST_P384, XPki_Request_Info::OpsType, PKI_ECC_NIST_P192_KEY_PRIV_GEN, PKI_ECC_NIST_P192_KEY_PUB_GEN, PKI_ECC_NIST_P256_KEY_PRIV_GEN, PKI_ECC_NIST_P256_KEY_PUB_GEN, PKI_ECC_NIST_P384_KEY_PRIV_GEN, PKI_ECC_NIST_P384_KEY_PUB_GEN, PKI_ECC_NIST_P521_KEY_PRIV_GEN, PKI_ECC_NIST_P521_KEY_PUB_GEN, XPki_Request_Info::PtrInputData, XPki_Request_Info::PtrOutputData, XilPki_DeQueue, XilPki_EnQueue, XPki_Request_Info::XPki_CompletionCallBack.
int XPki_EcdsaVerifySignKat(XPki_Instance *InstancePtr, XPki_EcdsaCrvInfo *CrvInfo)
This function performs ECC sign verify known answer test(KAT)
InstancePtr Pointer to the XPki instance CrvInfo Type of ECC curve class either prime/binary curve and curve type(NIST-P192,P256,P384, and P521) XST_SUCCESS - when KAT passesErrorcode - when KAT fails
References ECC_NIST_P192, ECC_NIST_P256, ECC_NIST_P384, XPki_Request_Info::OpsType, PKI_ECC_NIST_P192_SIGN_VERIFY, PKI_ECC_NIST_P256_SIGN_VERIFY, PKI_ECC_NIST_P384_SIGN_VERIFY, PKI_ECC_NIST_P521_SIGN_VERIFY, XPki_Request_Info::PtrInputData, XilPki_EnQueue, XPki_Request_Info::XPki_CompletionCallBack.
int XPki_EcdsaSignGenerateKat(XPki_Instance *InstancePtr, XPki_EcdsaCrvInfo *CrvInfo)
This function performs ECC sign generate known answer test(KAT)
InstancePtr Pointer to the XPki instance CrvInfo Type of ECC curve class either prime or binary class and curve type(NIST-P192,P256,P384, and P521) XST_SUCCESS - when KAT passesErrorcode - when KAT fails
References ECC_NIST_P192, ECC_NIST_P256, ECC_NIST_P384, XPki_Request_Info::OpsType, PKI_ECC_NIST_P192_SIGN, PKI_ECC_NIST_P256_SIGN, PKI_ECC_NIST_P384_SIGN, PKI_ECC_NIST_P521_SIGN, XPki_Request_Info::PtrInputData, XPki_Request_Info::PtrOutputData, XilPki_DeQueue, XilPki_EnQueue, XPki_Request_Info::XPki_CompletionCallBack.
int XPki_EcdsaPwct(XPki_Instance *InstancePtr, XPki_EcdsaCrvInfo *CrvInfo, XPki_EcdsaKey *PubKey, u8 *PrivKey)
This function performs ECC pairwise consistency test on ECC Curves.
InstancePtr Pointer to the XPki instance CrvInfo Type of ECC curve class either prime or binary class and curve type(NIST-P192,P256,P384, and P521) PubKey ECC public key PrivKey ECC private key XST_SUCCESS - when KAT passesErrorcode - when KAT fails
References ECC_NIST_P192, ECC_NIST_P256, ECC_NIST_P384, XPki_Request_Info::OpsType, PKI_ECC_NIST_P192_SIGN, PKI_ECC_NIST_P192_SIGN_VERIFY, PKI_ECC_NIST_P256_SIGN, PKI_ECC_NIST_P256_SIGN_VERIFY, PKI_ECC_NIST_P384_SIGN, PKI_ECC_NIST_P384_SIGN_VERIFY, PKI_ECC_NIST_P521_SIGN, PKI_ECC_NIST_P521_SIGN_VERIFY, XPki_Request_Info::PtrInputData, XPki_Request_Info::PtrOutputData, XilPki_DeQueue, XilPki_EnQueue, XPki_Request_Info::XPki_CompletionCallBack.
int XPki_TrngGenerateRandomNum(u8 GenSize, u8 *RandBuf)
This function is used to generate the Random number for the give size.
GenSize Required Random Number length in bytes. RandBuf Pointer to store the Random Number. XST_SUCCESS - On successXST_FAILURE - On failure
int XilPki_EnQueue(XPki_Instance *InstancePtr, XPki_Request_Info *Request_InfoPtr, u32 *RequestID)
This function is used to submit the crypto operation to the PKI Queue.
InstancePtr Pointer to the XPki instance Request_InfoPtr Pointer to the queue info structure RequestID Pointer to the RequestID. if the request is successfully submitted it filled with unique id XST_SUCCESS - On successXPKI_INVALID_PARAM - On invalid argumentXPKI_UNSUPPORTED_OPS - If the requested operation is not supported.XST_FAILURE - On failure
References XPki_Request_Info::OpsType, PKI_MAX_OPS, XPKI_INVALID_PARAM, XPKI_QUEUE_FULL, XPKI_UNSUPPORTED_OPS.
Referenced by XPki_EcdsaGenerateKeyPair, XPki_EcdsaPwct, XPki_EcdsaSignGenerateKat, XPki_EcdsaVerifySignKat.
int XilPki_DeQueue(XPki_Instance *InstancePtr, XPki_Request_Info *Request_InfoPtr, u32 RequestID)
This function is used to get the crypto operation results from the PKI Queue.
InstancePtr Pointer to the XPki instance Request_InfoPtr Pointer to the queue info structure RequestID Unique request ID Filled by the XilPki_EnQueue() API. XST_SUCCESS - On successXPKI_INVALID_PARAM - On invalid argumentXPKI_UNSUPPORTED_OPS - If the requested operation is not supported.XST_FAILURE - On failure
References XPKI_INVALID_PARAM.
Referenced by XPki_EcdsaGenerateKeyPair, XPki_EcdsaPwct, XPki_EcdsaSignGenerateKat.
void XPki_Close(void)
This function is used to disable access to the PKI Hardware.
static XPki_EcdsaKey* XPki_GetKatEccPublicKey(XPki_EcdsaCrvInfo *CrvInfo)
This function returns ECC public key to perform KAT.
CrvInfo Type of ECC curve class either prime or binary class and curve type(NIST-P192,P256,P384, and P521) ECC public key
static XPki_EcdsaSign* XPki_GetKatEccExpSign(XPki_EcdsaCrvInfo *CrvInfo)
This function returns ECC expected signature to perform KAT.
CrvInfo Type of ECC curve class either prime or binary class and curve type(NIST-P192,P256,P384, and P521) ECC expected signature
static const u8* XPki_GetKatEccPrivateKey(XPki_EcdsaCrvInfo *CrvInfo)
This function returns ECC private key to perform KAT.
CrvInfo Type of ECC curve class either prime or binary class and curve type(NIST-P192,P256,P384, and P521) ECC private key
static const u8* XPki_GetKatEccEphimeralKey(XPki_EcdsaCrvInfo *CrvInfo)
This function returns ECC ephemeral key to perform KAT.
CrvInfo Type of ECC curve class either prime or binary class and curve type(NIST-P192,P256,P384, and P521) ECC ephemeral key
static const u8* XPki_GetKatEccDataHash(XPki_EcdsaCrvInfo *CrvInfo)
This function returns ECC Data hash to perform KAT.
CrvInfo Type of ECC curve class either prime or binary class and curve type(NIST-P192,P256,P384, and P521) ECC Data hash
static u8 XPki_GetKatEccCurveLen(XPki_EcdsaCrvInfo *CrvInfo)
This function returns ECC Data length to perform KAT.
CrvInfo Type of ECC curve class either prime or binary class and curve type(NIST-P192,P256,P384, and P521) ECC Data length
static void XPki_SignVerify_CompletionCallBack(u32 RequestID, u32 Status)
It is a callback API for Signature Verification Request.
RequestID Unique ID for the submitted request Status Status of the request XST_SUCCESS - On successXST_FAILURE - On failure
static void XPki_SignGenerate_CompletionCallBack(u32 RequestID, u32 Status)
It is a callback API for Signature Generation Request.
RequestID Unique ID for the submitted request Status Status of the request XST_SUCCESS - On successXST_FAILURE - On failure
static void XPki_PrivKeyGen_CompletionCallBack(u32 RequestID, u32 Status)
It is a completion callback API for Private-key generation Request.
RequestID Unique ID for the submitted request Status Status of the Request XST_SUCCESS - On success-XST_FAILURE - On failure *
static void XPki_PubKeyGen_CompletionCallBack(u32 RequestID, u32 Status)
It is a completion callback API for Public-key generation request.
RequestID Unique ID for the submitted request Status Status of the request XST_SUCCESS - On successXST_FAILURE - On failure
XPKI_INVALID_PARAM
Error codes.
Invalid parameters
Referenced by XilPki_DeQueue, XilPki_EnQueue, XPki_Initialize.
XPKI_ERROR_UNALIGN_ADDR
For unaligned address.
XPKI_INVALID_QUEUE_ID
Invalid Queue ID.
XPKI_UNSUPPORTED_OPS
Unsupported operation.
Referenced by XilPki_EnQueue.
XPKI_QUEUE_FULL
Queue full.
Referenced by XilPki_EnQueue.
XPKI_SLOT_SIZE_ERR
For incompatible slot size.
XPKI_INVALID_REQ_ID
Invalid request ID.
XPKI_SIGN_COPY_ERR
Failed to copy the signature into the user pointed buffer.
XPKI_PRIV_KEY_COPY_ERR
Failed to copy the private-key into the user pointed buffer.
XPKI_PUB_KEY_COPY_ERR
Failed to copy the public-key into the user pointed buffer.
NIST_P192_LEN_BYTES
Bytes.
NIST_P384_LEN_BYTES
Bytes.
NIST_P256_LEN_BYTES
Bytes.
NIST_P521_LEN_BYTES
Bytes.