xilpki.c
XPKI_INTERRUPT_ID
XPKI_RESET_DELAY_US
XPKI_ASSERT_RESET
XPKI_DEASSERT_RESET
FPD_CLEAR_WRITE_PROTECT
XPKI_MUX_SELECT
XPKI_ADDR_WORD_ALIGN_MASK
XPKI_TRNG_INSTANCE
XPKI_TRNG_OFFSET
XPKI_TRNG_BUF_SIZE
XPKI_MAX_PRIV_KEY_LEN
XPKI_PAGE_SIZE
XPKI_INDEX_1_VAL
XPKI_INDEX_2_VAL
XPKI_RQ_CFG_PERMISSIONS_SAFE
XPKI_RQ_CFG_PAGE_SIZE_4096
XPKI_RQ_CFG_CQID
XPKI_CQ_CFG_SIZE_4096
XPKI_CQ_CFG_IRQ_ID_VAL
XPKI_RQ_CFG_QUEUE_DEPTH_VAL
XPKI_IRQ_ENABLE_VAL
XPKI_CQ_CTL_TRIGPOS_VAL
XPKI_MAX_CQ_REQ
XPKI_RID_MASK
DESC_TAG_START
DESC_TAG_TFRI
DESC_TAG_TFR0
DESC_TAG_NTFY
DESC_TAG_END
DESC_REQ_ID
NIST_P384_LEN_BYTES
NIST_P256_LEN_BYTES
NIST_P521_LEN_BYTES
P521_PADD_2_BYTES
P521_PADD_6_BYTES
SIGN_INPUT_OP_COUNT
SIGN_VERIFY_INPUT_OP_COUNT
PRIV_KEY_INPUT_OP_COUNT
PUB_KEY_INPUT_OP_COUNT
SIGN_OUTPUT_OP_COUNT
SIGN_VERIFY_OUTPUT_OP_COUNT
PRIV_KEY_OUTPUT_OP_COUNT
PUB_KEY_OUTPUT_OP_COUNT
PKI_ECC_NIST_P192_SIGN_CMD
PKI_ECC_NIST_P256_SIGN_CMD
PKI_ECC_NIST_P384_SIGN_CMD
PKI_ECC_NIST_P521_SIGN_CMD
PKI_ECC_NIST_P192_SIGN_VERIFY_CMD
PKI_ECC_NIST_P256_SIGN_VERIFY_CMD
PKI_ECC_NIST_P384_SIGN_VERIFY_CMD
PKI_ECC_NIST_P521_SIGN_VERIFY_CMD
PKI_ECC_NIST_P192_KEY_PRIV_GEN_CMD
PKI_ECC_NIST_P256_KEY_PRIV_GEN_CMD
PKI_ECC_NIST_P384_KEY_PRIV_GEN_CMD
PKI_ECC_NIST_P521_KEY_PRIV_GEN_CMD
PKI_ECC_NIST_P192_KEY_PUB_GEN_CMD
PKI_ECC_NIST_P256_KEY_PUB_GEN_CMD
PKI_ECC_NIST_P384_KEY_PUB_GEN_CMD
PKI_ECC_NIST_P521_KEY_PUB_GEN_CMD
XPKI_DESC_LEN_BYTES
XPKI_SIGN_P521_PADD_BYTES
XPKI_VERIFY_P521_PADD_BYTES
XPKI_ECDSA_NEW_REQUEST_MASK
OP_SIZE
INPUT_OP_SIZE
OUTPUT_OP_SIZE
GET_QUEUE_ID
GET_QUEUE_SLOT_ID
GET_QUEUE_PAGE_ADDR
XScuGic InterruptController
u8 PkiMemory[0x200000][0x200000]
The instance of the Interrupt Controller.
XPki_OpsInfo OpsInfo[][]
const u8 Order_P192[][]
const u8 Order_P256[][]
const u8 Order_P384[][]
const u8 Order_P521[][]
const u8 EcdsaGpoint_P192_Gx[][]
const u8 EcdsaGpoint_P192_Gy[][]
const u8 EcdsaGpoint_P256_Gx[][]
const u8 EcdsaGpoint_P256_Gy[][]
const u8 EcdsaGpoint_P384_Gx[][]
const u8 EcdsaGpoint_P384_Gy[][]
const u8 EcdsaGpoint_P521_Gx[][]
const u8 EcdsaGpoint_P521_Gy[][]
static int XPki_TrngInit(void)
This function is used to initialize the TRNG driver.
Error code on any error XST_SUCCESS on success
static XTrngpsx_Instance * XPki_Get_Trng_InstancePtr(u8 DeviceId)
This function is used to get the TRNG Instance.
NULL or Pointer to the TRNG Instance.
static int XPki_GetFreeSlot(XPki_Instance *InstancePtr, XPki_QueueID QueueID, u32 *FreeIndex)
This function is used to get the free slot ID from the request QueueID.
InstancePtr Pointer to the XPki instance QueueID QueueID(0/1/2/3) FreeIndex Pointer to the free slot index. XST_SUCCESS - On successXST_FAILURE - On failure
static int XPki_GetQueueID(XPki_Instance *InstancePtr, u32 OpSize, XPki_QueueID *QueueID)
This function is used to get the Queue ID.
InstancePtr Pointer to the XPki instance OpSize Crypto Operation size. QueueID Pointer to the QueueID(0/1/2/3) XST_SUCCESS - On successXST_FAILURE - On failure
static void XPki_PrepDescriptor(XPki_Instance *InstancePtr, Xpki_OpsType Ops, u32 RequestID, u32 *QDescPtr)
This function is used to prepare the descriptor data for the requested crypto operation.
InstancePtr Pointer to the XPki instance Ops Type of the crypto operation RequestID Unique ID QDescPtr Pointer to the descriptor buffer
static void XPki_UpdateQueueInfo(XPki_Instance *InstancePtr, XPki_Request_Info *Request_InfoPtr, u32 RequestID)
This function is used to update the Queue info for the EnQueued requests.
InstancePtr Pointer to the XPki instance Request_InfoPtr Pointer to the queue info structure RequestID Request ID for the EnQueued request API XST_SUCCESS - On successXPKI_UNSUPPORTED_OPS - If the requested operation is not supportedXST_FAILURE - On failure
static u8 XPki_GetEccCurveLen(XPki_EcdsaCrvType CrvType)
This function is used the get the ECC curve length.
CrvType Type of ECC curve (NIST-P192, 256, P384, and P521) ECC Curve length.
static int XPki_LoadInputData_EcdsaGenerateSign(XPki_EcdsaSignInputData *SignParams, UINTPTR Addr, u32 *DescPtr, u64 *EcdsaReqVal)
This function copy the user-pointed data into the Request queue buffer in the below order(as per the PKI Spec) to generate the signature.
-Private key -Ehimeral key -Data Hash -Signature Descriptor Data SignParams Pointer to the XPki_EcdsaSignInputData Addr Pointer to the Request queue input address DescPtr Pointer to the descriptor buffer EcdsaReqVal Pointer to the Generate Signature Descriptor Data offset XST_SUCCESS - On successXST_FAILURE - On failure
static int XPki_ValidateEcdsaGenerateSignParam(XPki_EcdsaSignInputData *SignParams)
This function is used to validate the elliptic curve signature generation input parameters.
SignParams Pointer to the XPki_EcdsaSignInputData XST_SUCCESS - On successXPKI_ECDSA_INVALID_PARAM - On invalid argumentXST_FAILURE - On failure
static void XPki_TrigQueueOps(XPki_QueueID QueueID, u64 TrigVal)
This function is used to initialize and trigger the PKI Operations.
QueueID Queue ID(PKI_QUEUE_ID_0/1/2/3) TrigVal RQ page offset value which points to Crypto OP descriptor buffer
static int XPki_LoadQueueData(XPki_Instance *InstancePtr, XPki_Request_Info *Request_InfoPtr, u32 *QDescPtr, u64 *TrigVal)
This function load the user-pointed crypto data (inputs) into the Request queue buffer (as per the PKI Spec).
InstancePtr Pointer to the XPki instance Request_InfoPtr Pointer to the queue info structure. QDescPtr Pointer to the descriptor buffer TrigVal Pointer to the Descriptor offset. XST_SUCCESS - On successXPKI_UNSUPPORTED_OPS - If the requested operation is not supported.XST_FAILURE - On failure
static int XPki_ValidateEcdsaVerifySignParam(XPki_EcdsaVerifyInputData *VerifyParams)
This function is used to validate the elliptic curve signature verification input parameters.
VerifyParams Pointer to the XPki_EcdsaVerifyInputData XST_SUCCESS - On successXPKI_ECDSA_NON_SUPPORTED_CRV - For Un-supported elliptic curvesXPKI_ECDSA_INVALID_PARAM - On invalid argumentXST_FAILURE - On failure
static int XPki_LoadInputData_EcdsaVerifySign(XPki_EcdsaVerifyInputData *VerifyParams, UINTPTR Addr, u32 *DescPtr, u64 *EcdsaReqVal)
This function copy the user-pointed data into the Request queue buffer in the below order(as per the PKI Spec) to validate the signature.
-Public key(Qx, Qy) -Signature(SignR, SignS) -Data Hash -Verify Signature Descriptor Data VerifyParams Pointer to the XPki_EcdsaVerifyInputData Addr Pointer to the Request queue input address DescPtr Pointer to the descriptor buffer EcdsaReqVal Pointer to the Verify Signature Descriptor Data offset XST_SUCCESS - On successXST_FAILURE - On failure
static const u8 * XPki_GetEccCurveOrder(XPki_EcdsaCrvType CrvType)
This function is used the get the ECC curve Order.
CrvType Type of ECC curve (NIST-P192, P256, P384, and P521) ECC Curve Order.
static int XPki_GenEccPrivateKey(XPki_EcdsaCrvType CrvType, UINTPTR Addr, u32 *DescPtr, u64 *EcdsaReqVal)
This function is used to fill the RQ to generate the Private key for the request curve.
CrvType Type of ECC curve (NIST-P192, P256, P384, and P521) Addr Pointer to the Request queue input address DescPtr Pointer to the descriptor buffer EcdsaReqVal Pointer to the Point-Multiplication Descriptor Data offset XST_SUCCESS - On successXST_FAILURE - On failure
static int XPki_LoadInputData_ModulusAdd(XPki_ModAddInputData *ModAddParams, UINTPTR Addr, u32 *DescPtr, u64 *EcdsaReqVal)
This function copy the user-pointed data into the Request queue buffer in the below order(as per the PKI Spec) to perform modulus addition.
- Curve Order - TRGN Generated Random value(A) - Value B = 1 -fixed - Modular addition Descriptor Data ModAddParams Pointer to the XPki_ModAddInputData Addr Pointer to the Request queue input address DescPtr Pointer to the descriptor buffer EcdsaReqVal Pointer to the modular addition Descriptor Data offset XST_SUCCESS - On successXST_FAILURE - On failure
static XPki_EcdsaGpoint * XPki_GetEccGpoint(XPki_EcdsaCrvType CrvType)
This function is used to get the ECC curve generator points.
CrvType Type of ECC curve (NIST-P192, P256, P384, and P521) ECC Generator Points(Gx, Gy)
static int XPki_GetEccCurveType(Xpki_OpsType OpsType, XPki_EcdsaCrvType *CrvType)
This function is used the get the ECC curve type for the given operation.
OpsType Crypto Operation type CrvType Type of ECC curve (NIST-P192, P256, P384, and P521) XST_SUCCESS - On successXST_FAILURE - On failure
static int XPki_EcdsaGenPubKey(XPki_EcdsaCrvType CrvType, u8 *PrivKey, UINTPTR Addr, u32 *DescPtr, u64 *EcdsaReqVa)
This function is used to fill the RQ to generate the Public key for the request curve.
CrvType Type of ECC curve (NIST-P192, P256, P384, and P521) PrivKey Pointer to the private-key buffer Addr Pointer to the Request queue input address DescPtr Pointer to the descriptor buffer EcdsaReqVa Pointer to the Point-Multiplication Descriptor Data offset XST_SUCCESS - On success XST_FAILURE - On failure
static int XPki_FreeQueueInfo(XPki_Instance *InstancePtr, u32 RequestID)
This function is used to free the Queue info for the DeQueued requests.
InstancePtr Pointer to the XPki instance RequestID Request ID for the DeQueued request API XST_SUCCESS - On successXST_FAILURE - On failure
static int XPki_DeQueueData(XPki_Instance *InstancePtr, XPki_Request_Info *Request_InfoPtr, u32 RequestID)
This function is used to get the crypto operation results from the PKI Queue.
InstancePtr Pointer to the XPki instance Request_InfoPtr Pointer to the queue info structure RequestID Unique request ID Filled by the XilPki_EnQueue() API XST_SUCCESS - On successXPKI_UNSUPPORTED_OPS - If the requested operation is not supportedXST_FAILURE - On failure
static int XPki_CopyEcdsaSigature(XPki_EcdsaCrvType CrvType, u8 *Addr, XPki_EcdsaSign *SignPtr)
This function copy the ecdsa generated signature data into the user-pointed buffer.
CrvType Type of ECC curve(NIST-P192, NIST-P256, P384 and P521) Addr Pointer to the Request queue out address. SignPtr Pointer to the XPki_EcdsaSign. XST_SUCCESS - On successXST_FAILURE - On failureXPKI_ECDSA_NON_SUPPORTED_CRV - On Un-supported elliptic curves
static int XPki_CopyEcdsaPubKey(XPki_EcdsaCrvType CrvType, u8 *Addr, XPki_EcdsaKey *PubKey)
This function copy the ecdsa generated signature data into the user-pointed buffer.
CrvType Type of ECC curve(NIST-P192, NIST-P256, P384 and P521) Addr Pointer to the Request queue out address PubKey Pointer to the pulic-key buffer XST_SUCCESS - On successXST_FAILURE - On failureXPKI_ECDSA_NON_SUPPORTED_CRV - On Un-supported elliptic curves
static int XPki_CopyEcdsaPrivKey(XPki_EcdsaCrvType CrvType, u8 *Addr, u8 *PrivKey)
This function copy the ecdsa generated signature data into the user-pointed buffer.
CrvType Type of ECC curve(NIST-P192, NIST-P256, P384 and P521) Addr Pointer to the Request queue out address PrivKey Pointer to the Private-key buffer XST_SUCCESS - On successXST_FAILURE - On failureXPKI_ECDSA_NON_SUPPORTED_CRV - On Un-supported elliptic curves
static void XPki_IntrHandler(XPki_Instance *InstancePtr)
This function implements the interrupt handler.
InstancePtr Pointer to the XPki instance
static int XPki_SetupInterruptSystem(XPki_Instance *InstancePtr)
This function setups the interrupt system such that interrupts can occur for the PKI.
InstancePtr Pointer to the instance of the PKI which is going to be connected to the interrupt controller. XST_SUCCESS if successful, otherwise XST_FAILURE.
static int XilPki_Queue_Init(XPki_Instance *InstancePtr, XPki_QueueID QueueID)
This function initialize the requested queue.
InstancePtr Pointer to the XPki instance QueueID Queue ID(PKI_QUEUE_ID_0/1/2/3). -XST_SUCCESS - On success -XPKI_INVALID_PARAM - On invalid argument -XPKI_ERROR_UNALIGN_ADDR - On Request/Completion queue Address are not Word aligned. -XPKI_INVALID_QUEUE_ID - If the provided QueueID is Invalid. -XST_FAILURE - On failure
static void XPki_IntrCallbackHandler(XPki_Instance *InstancePtr, XPki_QueueID Id)
This function is use to notify the user if the submitted request completed.
InstancePtr Pointer to the XPki instance Id Queue ID(0/1/2/3)
static int XPki_ValidateReqID(XPki_Instance *InstancePtr, u32 RequestID)
This function is used to validate the given request ID against with submitted request IDs.
InstancePtr Pointer to the XPki instance RequestID Unique ID provided by user XST_SUCCESS - On successXST_FAILURE - On failure
static void XilPki_Queue_MapPageAddr(XPki_Instance *InstancePtr)
This function is used to assign the page address to the PKI Queues.
InstancePtr Pointer to the XPki instance.
void XPki_Reset(void)
This function reset the PKI module.
Referenced by XPki_Initialize.
void XPki_SoftReset(void)
This function performs the PKI module soft reset.
Referenced by XPki_Initialize.
int XPki_Initialize(XPki_Instance *InstancePtr)
This function performs the PKI module initialization.
InstancePtr Pointer to the XPki instance XST_SUCCESS - On successXPKI_INVALID_PARAM - On invalid argumentXPKI_ERROR_UNALIGN_ADDR - On Request/Completion queue Address are not Word aligned.XST_FAILURE - On failure
References XPKI_INVALID_PARAM, XPki_Reset, XPki_SoftReset.
void XPki_Close(void)
This function is used to disable access to the PKI Hardware.
int XPki_TrngGenerateRandomNum(u8 GenSize, u8 *RandBuf)
This function is used to generate the Random number for the give size.
GenSize Required Random Number length in bytes. RandBuf Pointer to store the Random Number. XST_SUCCESS - On successXST_FAILURE - On failure
int XilPki_EnQueue(XPki_Instance *InstancePtr, XPki_Request_Info *Request_InfoPtr, u32 *RequestID)
This function is used to submit the crypto operation to the PKI Queue.
InstancePtr Pointer to the XPki instance Request_InfoPtr Pointer to the queue info structure RequestID Pointer to the RequestID. if the request is successfully submitted it filled with unique id XST_SUCCESS - On successXPKI_INVALID_PARAM - On invalid argumentXPKI_UNSUPPORTED_OPS - If the requested operation is not supported.XST_FAILURE - On failure
References XPKI_INVALID_PARAM, XPKI_QUEUE_FULL, XPki_Request_Info::OpsType, PKI_MAX_OPS, XPKI_UNSUPPORTED_OPS.
Referenced by XPki_EcdsaVerifySignKat, XPki_EcdsaSignGenerateKat, XPki_EcdsaPwct, XPki_EcdsaGenerateKeyPair.
int XilPki_DeQueue(XPki_Instance *InstancePtr, XPki_Request_Info *Request_InfoPtr, u32 RequestID)
This function is used to get the crypto operation results from the PKI Queue.
InstancePtr Pointer to the XPki instance Request_InfoPtr Pointer to the queue info structure RequestID Unique request ID Filled by the XilPki_EnQueue() API. XST_SUCCESS - On successXPKI_INVALID_PARAM - On invalid argumentXPKI_UNSUPPORTED_OPS - If the requested operation is not supported.XST_FAILURE - On failure
References XPKI_INVALID_PARAM.
Referenced by XPki_EcdsaSignGenerateKat, XPki_EcdsaPwct, XPki_EcdsaGenerateKeyPair.
static int XPki_LoadInputData_EcdsaPointMulti(XPki_EcdsaPointMultiInputData *PointMultiParams, UINTPTR Addr, u32 *DescPtr, u64 *EcdsaReqVal)
This function copy the user-pointed data into the Request queue buffer in the below order(as per the PKI Spec) to generate the Public-key.
-Private key -Generator points(Gx, Gy) -Point Multiplication Descriptor Data PointMultiParams Pointer to the XPki_EcdsaPointMultiInputData Addr Pointer to the request queue input address DescPtr Pointer to the descriptor buffer EcdsaReqVal Pointer to the Point-Multiplication Descriptor Data offset XST_SUCCESS - On successXST_FAILURE - On failure