dfeccf
XDfeCcf_StateId
Not ready state.
typedef __u32 u32
typedef __u16 u16
typedef __u8 u8
typedef __s32 s32
typedef __s16 s16
typedef __u64 u64
typedef __s64 s64
typedef __s8 s8
typedef enum XDfeCcf_StateId XDfeCcf_StateId
typedef XDfeCcf_Status XDfeCcf_InterruptMask
static void XDfeCcf_GetCurrentCCCfgLocal(const XDfeCcf *InstancePtr, XDfeCcf_CCCfg *CurrCCCfg)
XDfeCcf * XDfeCcf_InstanceInit(const char *DeviceNodeName)
Initialises one instance of a channel filter driver.
Traverses "/sys/bus/platform/device" directory (in Linux), to find registered CCF device with the name DeviceNodeName. The first available slot in the instances array XDfeCcf_ChFilter[] will be taken as a DeviceNodeName object. On success it moves the state machine to a Ready state, while on failure stays in a Not Ready state. DeviceNodeName Device node name. Pointer to the instance if successful.NULL on error.
References XDfeCcf::Device, XDfeCcf::NodeName, XDfeCcf::StateId, XDFECCF_NODE_NAME_MAX_LENGTH, XDFECCF_STATE_NOT_READY, XDFECCF_STATE_READY, XST_FAILURE, XST_SUCCESS.
Referenced by XDfeCcf_multiAddCC_1xNR100_3xNR20_Example, XDfeCcf_MultiInstancesExample, XDfeCcf_PassThroughExample.
void XDfeCcf_InstanceClose(XDfeCcf *InstancePtr)
Closes the instances of a channel filter driver and moves the state machine to a Not Ready state.
InstancePtr Pointer to the XDfeCcf instance.
References XDfeCcf::Device, XDfeCcf::NodeName, XDfeCcf::StateId, XDFECCF_STATE_NOT_READY.
Referenced by XDfeCcf_multiAddCC_1xNR100_3xNR20_Example, XDfeCcf_MultiInstancesExample, XDfeCcf_PassThroughExample.
void XDfeCcf_Reset(XDfeCcf *InstancePtr)
Resets channel filter and puts block into a reset state.
InstancePtr Pointer to the Ccf instance.
References XDfeCcf::StateId, XDFECCF_STATE_NOT_READY, XDFECCF_STATE_RESET.
Referenced by XDfeCcf_multiAddCC_1xNR100_3xNR20_Example, XDfeCcf_MultiInstancesExample, XDfeCcf_PassThroughExample.
void XDfeCcf_Configure(XDfeCcf *InstancePtr, XDfeCcf_Cfg *Cfg)
Reads configuration from device tree/xparameters.h and IP registers.
Removes S/W reset and moves the state machine to a Configured state. InstancePtr Pointer to the Ccf instance. Cfg Configuration data container.
References XDfeCcf_ModelParameters::AntennaInterleave, XDfeCcf_Config::AntennaInterleave, XDfeCcf::Config, XDfeCcf_Version::Major, XDfeCcf_Version::Minor, XDfeCcf_Cfg::ModelParams, XDfeCcf_ModelParameters::NumAntenna, XDfeCcf_Config::NumAntenna, XDfeCcf_ModelParameters::NumCCPerAntenna, XDfeCcf_Config::NumCCPerAntenna, XDfeCcf_Version::Patch, XDfeCcf_Version::Revision, XDfeCcf::StateId, XDfeCcf_ModelParameters::Switchable, XDfeCcf_Config::Switchable, XDfeCcf_Cfg::Version, XDFECCF_STATE_CONFIGURED, XDFECCF_STATE_RESET.
Referenced by XDfeCcf_multiAddCC_1xNR100_3xNR20_Example, XDfeCcf_MultiInstancesExample, XDfeCcf_PassThroughExample.
void XDfeCcf_Initialize(XDfeCcf *InstancePtr, XDfeCcf_Init *Init)
DFE Ccf driver one time initialisation, also moves the state machine to an Initialised state.
InstancePtr Pointer to the Ccf instance. Init Initialisation data container.
References XDfeCcf::Config, XDfeCcf_Init::GainStage, XDfeCcf_CCSequence::Length, XDfeCcf::NotUsedCCID, XDfeCcf::NotUsedCCID_UL, XDfeCcf_Init::Sequence, XDfeCcf::SequenceLength, XDfeCcf::StateId, XDfeCcf_Config::Switchable, XDfeCcf_Init::TuserSelect, XDFECCF_STATE_CONFIGURED, XDFECCF_STATE_INITIALISED.
Referenced by XDfeCcf_multiAddCC_1xNR100_3xNR20_Example, XDfeCcf_MultiInstancesExample, XDfeCcf_PassThroughExample.
void XDfeCcf_Activate(XDfeCcf *InstancePtr, bool EnableLowPower)
Activates channel filter and moves the state machine to an Activated state.
InstancePtr Pointer to the Ccf instance. EnableLowPower Flag indicating low power.
References XDfeCcf::Config, XDfeCcf::StateId, XDfeCcf_Config::Switchable, XDFECCF_STATE_INITIALISED, XDFECCF_STATE_OPERATIONAL.
Referenced by XDfeCcf_multiAddCC_1xNR100_3xNR20_Example, XDfeCcf_MultiInstancesExample, XDfeCcf_PassThroughExample.
void XDfeCcf_Deactivate(XDfeCcf *InstancePtr)
Deactivates channel filter and moves the state machine to Initialised state.
InstancePtr Pointer to the Ccf instance.
References XDfeCcf::Config, XDfeCcf::StateId, XDfeCcf_Config::Switchable, XDFECCF_STATE_INITIALISED, XDFECCF_STATE_OPERATIONAL.
Referenced by XDfeCcf_multiAddCC_1xNR100_3xNR20_Example, XDfeCcf_MultiInstancesExample, XDfeCcf_PassThroughExample.
XDfeCcf_StateId XDfeCcf_GetStateID(XDfeCcf *InstancePtr)
Gets a state machine state id.
InstancePtr Pointer to the Ccf instance. State machine StateID
References XDfeCcf::StateId.
void XDfeCcf_GetCurrentCCCfg(const XDfeCcf *InstancePtr, XDfeCcf_CCCfg *CurrCCCfg)
Returns the current CC configuration in non-switchable mode.
Not used slot ID in a sequence (Sequence.CCID[Index]) are represented as (-1), not the value in registers. InstancePtr Pointer to the Ccf instance. CurrCCCfg CC configuration container. For a sequence conversion see XDfeCcf_AddCCtoCCCfg() comment.
References XDfeCcf_CCSequence::NotUsedCCID, XDfeCcf::NotUsedCCID, XDfeCcf_CCCfg::Sequence.
Referenced by XDfeCcf_AddCC, XDfeCcf_GetTDataDelay, XDfeCcf_multiAddCC_1xNR100_3xNR20_Example, XDfeCcf_RemoveCC, XDfeCcf_UpdateAntenna, XDfeCcf_UpdateAntennaCfg, XDfeCcf_UpdateCC.
void XDfeCcf_GetCurrentCCCfgSwitchable(const XDfeCcf *InstancePtr, XDfeCcf_CCCfg *CCCfgDownlink, XDfeCcf_CCCfg *CCCfgUplink)
Returns the current CC configuration for Downlink and Uplink in switchable mode.
Not used slot ID in a sequence (Sequence.CCID[Index]) are represented as (-1), not the value in registers. InstancePtr Pointer to the Mixer instance. CCCfgDownlink Downlink CC configuration container. CCCfgUplink Uplink CC configuration container.
References XDfeCcf::Config, XDfeCcf_CCSequence::NotUsedCCID, XDfeCcf::NotUsedCCID, XDfeCcf::NotUsedCCID_UL, XDfeCcf_CCCfg::Sequence, XDfeCcf_Config::Switchable, XDfeCcf_SetRegBank.
Referenced by XDfeCcf_UpdateAntennaCfgSwitchable.
void XDfeCcf_GetEmptyCCCfg(const XDfeCcf *InstancePtr, XDfeCcf_CCCfg *CCCfg)
Returns configuration structure CCCfg with CCCfg->Sequence.Length value set in XDfeCcf_Configure(), array CCCfg->Sequence.CCID[] members are set to not used value (-1) and the other CCCfg members are set to 0.
InstancePtr Pointer to the Ccf instance. CCCfg CC configuration container.
References XDfeCcf_CCSequence::CCID, XDfeCcf_CCSequence::Length, XDfeCcf_CCCfg::Sequence, XDfeCcf::SequenceLength, XDFECCF_CC_NUM.
void XDfeCcf_GetCarrierCfg(const XDfeCcf *InstancePtr, XDfeCcf_CCCfg *CCCfg, s32 CCID, u32 *CCSeqBitmap, XDfeCcf_CarrierCfg *CarrierCfg)
Returns the current CCID carrier configuration.
InstancePtr Pointer to the Ccf instance. CCCfg Component carrier (CC) configuration container. CCID Channel ID for which configuration parameters are returned, range [0-15]. CCSeqBitmap CC slot position container. CarrierCfg CC configuration container.
References XDfeCcf_CCCfg::CarrierCfg, XDfeCcf_CCSequence::CCID, XDfeCcf_CarrierCfg::Gain, XDfeCcf_InternalCarrierCfg::Gain, XDfeCcf_CarrierCfg::ImagCoeffSet, XDfeCcf_InternalCarrierCfg::ImagCoeffSet, XDfeCcf_CCSequence::Length, XDfeCcf_CarrierCfg::RealCoeffSet, XDfeCcf_InternalCarrierCfg::RealCoeffSet, XDfeCcf_CCCfg::Sequence.
Referenced by XDfeCcf_GetTDataDelayFromCCCfg.
void XDfeCcf_SetAntennaCfgInCCCfg(const XDfeCcf *InstancePtr, XDfeCcf_CCCfg *CCCfg, XDfeCcf_AntennaCfg *AntennaCfg)
Set antenna configuration in CC configuration container.
InstancePtr Pointer to the Ccf instance. CCCfg CC configuration container. AntennaCfg Array of all antenna configurations.
References XDfeCcf_CCCfg::AntennaCfg.
u32 XDfeCcf_AddCCtoCCCfg(XDfeCcf *InstancePtr, XDfeCcf_CCCfg *CCCfg, s32 CCID, u32 CCSeqBitmap, const XDfeCcf_CarrierCfg *CarrierCfg)
Adds specified CCID, with specified configuration, to a local CC configuration structure.
If there is insufficient capacity for the new CC the function will return an error. Initiates CC update (enable CCUpdate trigger TUSER Single Shot).The returned CCCfg.Sequence is translated as there is no explicit indication that SEQUENCE[i] is not used - 0 can define the slot as either used or not used. Sequence data that is returned in the CCIDSequence is not the same as what is written in the registers. The translation is: CCIDSequence.CCID[i] = -1 - if [i] is unused slotCCIDSequence.CCID[i] = CCID - if [i] is used slota returned CCIDSequence->Length = length in register + 1 InstancePtr Pointer to the Ccf instance. CCCfg Component carrier (CC) configuration container. CCID CC ID. CCSeqBitmap CC slot position container. CarrierCfg CC configuration container. XST_SUCCESS if successful.XST_FAILURE if error occurs.
References XDfeCcf_CCCfg::CarrierCfg, XDfeCcf_InternalCarrierCfg::Enable, XDfeCcf_InternalCarrierCfg::Flush, XDfeCcf_CarrierCfg::Gain, XDfeCcf_InternalCarrierCfg::Gain, XDfeCcf_CarrierCfg::ImagCoeffSet, XDfeCcf_InternalCarrierCfg::ImagCoeffSet, XDfeCcf_InternalCarrierCfg::MappedId, XDfeCcf_CarrierCfg::RealCoeffSet, XDfeCcf_InternalCarrierCfg::RealCoeffSet, XDfeCcf_CCCfg::Sequence, XST_FAILURE, XST_SUCCESS.
Referenced by XDfeCcf_multiAddCC_1xNR100_3xNR20_Example.
void XDfeCcf_RemoveCCfromCCCfg(XDfeCcf *InstancePtr, XDfeCcf_CCCfg *CCCfg, s32 CCID)
Removes specified CCID from a local CC configuration structure.
InstancePtr Pointer to the Ccf instance. CCCfg Component carrier (CC) configuration container. CCID Channel ID to be removed, range [0-15]. For a sequence conversion see XDfeCcf_AddCCtoCCCfg comment.
References XDfeCcf_CCCfg::CarrierCfg, XDfeCcf_InternalCarrierCfg::Enable, XDfeCcf_InternalCarrierCfg::MappedId, XDfeCcf_CCCfg::Sequence.
void XDfeCcf_UpdateCCinCCCfg(const XDfeCcf *InstancePtr, XDfeCcf_CCCfg *CCCfg, s32 CCID, const XDfeCcf_CarrierCfg *CarrierCfg)
Updates specified CCID, with specified configuration to a local CC configuration structure.
If there is insufficient capacity for the new CC the function will return an error. InstancePtr Pointer to the Ccf instance. CCCfg Component carrier (CC) configuration container. CCID Channel ID to be updated, range [0-15]. CarrierCfg CC configuration container.
References XDfeCcf_CCCfg::CarrierCfg, XDfeCcf_InternalCarrierCfg::Flush, XDfeCcf_CarrierCfg::Gain, XDfeCcf_InternalCarrierCfg::Gain, XDfeCcf_CarrierCfg::ImagCoeffSet, XDfeCcf_InternalCarrierCfg::ImagCoeffSet, XDfeCcf_CarrierCfg::RealCoeffSet, XDfeCcf_InternalCarrierCfg::RealCoeffSet.
u32 XDfeCcf_SetNextCCCfgAndTrigger(XDfeCcf *InstancePtr, XDfeCcf_CCCfg *CCCfg)
Writes local CC configuration to the shadow (NEXT) registers and triggers copying from shadow to operational (CURRENT) registers.
InstancePtr Pointer to the Ccf instance. CCCfg CC configuration container. XST_SUCCESS if successful.XST_FAILURE if error occurs.
References XDfeCcf_CCSequence::NotUsedCCID, XDfeCcf::NotUsedCCID, XDfeCcf_CCCfg::Sequence, XST_FAILURE, XST_SUCCESS.
Referenced by XDfeCcf_AddCC, XDfeCcf_multiAddCC_1xNR100_3xNR20_Example, XDfeCcf_RemoveCC, XDfeCcf_UpdateAntenna, XDfeCcf_UpdateAntennaCfg, XDfeCcf_UpdateCC.
u32 XDfeCcf_SetNextCCCfgAndTriggerSwitchable(XDfeCcf *InstancePtr, XDfeCcf_CCCfg *CCCfgDownlink, XDfeCcf_CCCfg *CCCfgUplink)
Writes local CC configuration to the shadow (NEXT) registers and triggers copying from shadow to operational (CURRENT) registers for both Downlink and Upling in switchable mode.
InstancePtr Pointer to the Ccf instance. CCCfgDownlink Downlink CC configuration container. CCCfgUplink Uplink CC configuration container. XST_SUCCESS if successful.XST_FAILURE if error occurs.
References XDfeCcf::Config, XDfeCcf_CCSequence::NotUsedCCID, XDfeCcf::NotUsedCCID, XDfeCcf::NotUsedCCID_UL, XDfeCcf_CCCfg::Sequence, XDfeCcf_Config::Switchable, XDfeCcf_SetRegBank, XST_FAILURE, XST_SUCCESS.
Referenced by XDfeCcf_UpdateAntennaCfgSwitchable.
u32 XDfeCcf_AddCC(XDfeCcf *InstancePtr, s32 CCID, u32 CCSeqBitmap, const XDfeCcf_CarrierCfg *CarrierCfg)
Adds specified CCID, with specified configuration.
If there is insufficient capacity for the new CC the function will return an error. Initiates CC update (enable CCUpdate trigger TUSER Single Shot). InstancePtr Pointer to the Ccf instance. CCID CC ID. CCSeqBitmap - up to 16 defined slots into which a CC can be allocated. The number of slots can be from 1 to 16 depending on system initialization. The number of slots is defined by the "sequence length" parameter which is provided during initialization. The Bit offset within the CCSeqBitmap indicates the equivalent Slot number to allocate. e.g. 0x0003 means the caller wants the passed component carrier (CC) to be allocated to slots 0 and 1. CarrierCfg CC configuration container. XST_SUCCESS if successful.XST_FAILURE if error occurs. Clear event status with XDfeCcf_ClearEventStatus() before running this API.: This API is deprecated in the release 2023.2. The functionality of this API can be reproduced with the following API sequence: XDfeCcf_GetCurrentCCCfg(InstancePtr, CCCfg); XDfeCcf_AddCCtoCCCfg(InstancePtr, CCCfg, CCID, CCSeqBitmap, CarrierCfg); XDfeCcf_SetNextCCCfgAndTrigger(InstancePtr, CCCfg);
References XDfeCcf_CCCfg::CarrierCfg, XDfeCcf_InternalCarrierCfg::Enable, XDfeCcf_InternalCarrierCfg::Flush, XDfeCcf_CarrierCfg::Gain, XDfeCcf_InternalCarrierCfg::Gain, XDfeCcf_CarrierCfg::ImagCoeffSet, XDfeCcf_InternalCarrierCfg::ImagCoeffSet, XDfeCcf_CCSequence::Length, XDfeCcf_InternalCarrierCfg::MappedId, XDfeCcf_CarrierCfg::RealCoeffSet, XDfeCcf_InternalCarrierCfg::RealCoeffSet, XDfeCcf_CCCfg::Sequence, XDfeCcf::StateId, XDfeCcf_GetCurrentCCCfg, XDfeCcf_SetNextCCCfgAndTrigger, XDFECCF_STATE_OPERATIONAL, XST_FAILURE, XST_SUCCESS.
Referenced by XDfeCcf_PassThroughExample.
u32 XDfeCcf_RemoveCC(XDfeCcf *InstancePtr, s32 CCID)
Removes specified CCID.
Initiates CC update (enable CCUpdate trigger TUSER Single Shot). InstancePtr Pointer to the Ccf instance. CCID CC ID. XST_SUCCESS if successful.XST_FAILURE if error occurs. Clear event status with XDfeCcf_ClearEventStatus() before running this API.: This API is deprecated in the release 2023.2. The functionality of this API can be reproduced with the following API sequence: XDfeCcf_GetCurrentCCCfg(InstancePtr, CCCfg); XDfeCcf_RemoveCCfromCCCfg(InstancePtr, CCCfg, CCID); XDfeCcf_SetNextCCCfgAndTrigger(InstancePtr, CCCfg);
References XDfeCcf_CCCfg::CarrierCfg, XDfeCcf_InternalCarrierCfg::Enable, XDfeCcf_InternalCarrierCfg::MappedId, XDfeCcf_CCCfg::Sequence, XDfeCcf::StateId, XDfeCcf_GetCurrentCCCfg, XDfeCcf_SetNextCCCfgAndTrigger, XDFECCF_STATE_OPERATIONAL.
u32 XDfeCcf_UpdateCC(XDfeCcf *InstancePtr, s32 CCID, const XDfeCcf_CarrierCfg *CarrierCfg)
Updates specified CCID carrier configuration; change gain or filter coefficients set.
Initiates CC update (enable CCUpdate trigger TUSER Single Shot). InstancePtr Pointer to the Ccf instance. CCID CC ID. CarrierCfg CC configuration container. XST_SUCCESS if successful.XST_FAILURE if error occurs. Clear event status with XDfeCcf_ClearEventStatus() before running this API.: This API is deprecated in the release 2023.2. The functionality of this API can be reproduced with the following API sequence: XDfeCcf_GetCurrentCCCfg(InstancePtr, CCCfg); XDfeCcf_UpdateCCinCCCfg(InstancePtr, CCCfg, CCID, CarrierCfg); XDfeCcf_SetNextCCCfgAndTrigger(InstancePtr, CCCfg);
References XDfeCcf_CCCfg::CarrierCfg, XDfeCcf_InternalCarrierCfg::Flush, XDfeCcf_CarrierCfg::Gain, XDfeCcf_InternalCarrierCfg::Gain, XDfeCcf_CarrierCfg::ImagCoeffSet, XDfeCcf_InternalCarrierCfg::ImagCoeffSet, XDfeCcf_CarrierCfg::RealCoeffSet, XDfeCcf_InternalCarrierCfg::RealCoeffSet, XDfeCcf::StateId, XDfeCcf_GetCurrentCCCfg, XDfeCcf_SetNextCCCfgAndTrigger, XDFECCF_STATE_OPERATIONAL.
u32 XDfeCcf_UpdateAntenna(XDfeCcf *InstancePtr, u32 Ant, bool Enabled)
Updates specified antenna TDM slot enablement.
Initiates CC update (enable CCUpdate trigger one-shot). InstancePtr Pointer to the Ccf instance. Ant Antenna ID. Enabled Flag indicating enable status of the antenna. XST_SUCCESS if successful.XST_FAILURE if error occurs. Clear event status with XDfeCcf_ClearEventStatus() before running this API.
References XDfeCcf_CCCfg::AntennaCfg, XDfeCcf_AntennaCfg::Enable, XDfeCcf::StateId, XDfeCcf_GetCurrentCCCfg, XDfeCcf_SetNextCCCfgAndTrigger, XDFECCF_STATE_OPERATIONAL.
u32 XDfeCcf_UpdateAntennaCfg(XDfeCcf *InstancePtr, XDfeCcf_AntennaCfg *AntennaCfg)
Updates antenna configuration to all antennas.
InstancePtr Pointer to the Ccf instance. AntennaCfg Array of all antenna configurations. XST_SUCCESS if successful.XST_FAILURE if error occurs. Clear event status with XDfeCcf_ClearEventStatus() before running this API.
References XDfeCcf_CCCfg::AntennaCfg, XDfeCcf_GetCurrentCCCfg, XDfeCcf_SetNextCCCfgAndTrigger.
u32 XDfeCcf_UpdateAntennaCfgSwitchable(XDfeCcf *InstancePtr, XDfeCcf_AntennaCfg *AntennaCfgDownlink, XDfeCcf_AntennaCfg *AntennaCfgUplink)
Updates antenna configuration of all antennas.
Applies gain to downlink only in switchable mode. InstancePtr Pointer to the Ccf instance. AntennaCfgDownlink Array of all downlink antenna configurations. AntennaCfgUplink Array of all uplink antenna configurations. XST_SUCCESS if successful.XST_FAILURE if error occurs. Clear event status with XDfeCcf_ClearEventStatus() before running this API.
References XDfeCcf_CCCfg::AntennaCfg, XDfeCcf::Config, XDfeCcf_Config::Switchable, XDfeCcf_GetCurrentCCCfgSwitchable, XDfeCcf_SetNextCCCfgAndTriggerSwitchable.
void XDfeCcf_GetTriggersCfg(const XDfeCcf *InstancePtr, XDfeCcf_TriggerCfg *TriggerCfg)
Returns current trigger configuration.
InstancePtr Pointer to the Ccf instance. TriggerCfg Trigger configuration container.
References XDfeCcf_TriggerCfg::Activate, XDfeCcf_TriggerCfg::CCUpdate, XDfeCcf_TriggerCfg::LowPower, XDfeCcf_Trigger::Mode, XDfeCcf::StateId, XDfeCcf_Trigger::StateOutput, XDfeCcf_TriggerCfg::Switch, XDfeCcf_Trigger::TriggerEnable, XDfeCcf_Trigger::TUSERBit, XDfeCcf_Trigger::TuserEdgeLevel, XDFECCF_STATE_NOT_READY.
void XDfeCcf_SetTriggersCfg(const XDfeCcf *InstancePtr, XDfeCcf_TriggerCfg *TriggerCfg)
Sets trigger configuration.
InstancePtr Pointer to the Ccf instance. TriggerCfg Trigger configuration container.
References XDfeCcf_TriggerCfg::Activate, XDfeCcf_TriggerCfg::CCUpdate, XDfeCcf_TriggerCfg::LowPower, XDfeCcf_Trigger::Mode, XDfeCcf::StateId, XDfeCcf_Trigger::StateOutput, XDfeCcf_TriggerCfg::Switch, XDfeCcf_Trigger::TriggerEnable, XDfeCcf_Trigger::TUSERBit, XDfeCcf_Trigger::TuserEdgeLevel, XDFECCF_STATE_INITIALISED.
Referenced by XDfeCcf_multiAddCC_1xNR100_3xNR20_Example, XDfeCcf_PassThroughExample.
void XDfeCcf_GetCC(const XDfeCcf *InstancePtr, s32 CCID, XDfeCcf_CarrierCfg *CarrierCfg)
Gets specified CCID carrier configuration.
InstancePtr Pointer to the Ccf instance. CCID CC ID. CarrierCfg Trigger configuration container.
References XDfeCcf_CarrierCfg::Gain, XDfeCcf_CarrierCfg::ImagCoeffSet, XDfeCcf_CarrierCfg::RealCoeffSet.
void XDfeCcf_GetActiveSets(const XDfeCcf *InstancePtr, u32 *IsActive)
Returns a list indicating which coefficient sets are currently in use.
InstancePtr Pointer to the Ccf instance. IsActive Pointer indicating an activation status.
References XDfeCcf::SequenceLength, XDfeCcf::StateId, XDFECCF_ACTIVE_SET_NUM, XDFECCF_STATE_OPERATIONAL.
void XDfeCcf_LoadCoefficients(XDfeCcf *InstancePtr, u32 Set, u32 Shift, const XDfeCcf_Coefficients *Coeffs)
Writes the coefficient set defined into the register map and commit them to the hard block's internal coefficient memory for the specified Set.
InstancePtr Pointer to the Ccf instance. Set Coefficient set Id. Shift Coefficient shift value. Coeffs Array of filter coefficients.
References XDfeCcf_Coefficients::Num, XDfeCcf_Coefficients::Symmetric, XDfeCcf_Coefficients::Value, XDFECCF_NUM_COEFF.
Referenced by XDfeCcf_multiAddCC_1xNR100_3xNR20_Example, XDfeCcf_PassThroughExample.
void XDfeCcf_SetTUserDelay(const XDfeCcf *InstancePtr, u32 Delay)
Sets the delay, which will be added to TUSER and TLAST (delay matched through the IP).
InstancePtr Pointer to the Ccf instance. Delay Requested delay variable.
References XDfeCcf::StateId, XDFECCF_STATE_INITIALISED.
u32 XDfeCcf_GetTUserDelay(const XDfeCcf *InstancePtr)
Reads the delay, which will be added to TUSER and TLAST (delay matched through the IP).
InstancePtr Pointer to the Ccf instance. Delay value
u32 XDfeCcf_GetTDataDelay(XDfeCcf *InstancePtr, u32 Tap, s32 CCID, u32 Symmetric, u32 Num, u32 *TDataDelay)
Gets calculated TDataDelay value for CCID from current CC configuration.
InstancePtr Pointer to the Ccf instance. Tap Tap value. CCID CC ID. Symmetric Select symmetric (1) or non-symmetric (0) filter. Num Number of coefficients values. TDataDelay Data latency value. XST_SUCCESS if successful.XST_FAILURE if error occurs.
References XDfeCcf_GetCurrentCCCfg, XDfeCcf_GetTDataDelayFromCCCfg, XDFECCF_TAP_NUMBER_MAX.
u32 XDfeCcf_GetTDataDelayFromCCCfg(XDfeCcf *InstancePtr, u32 Tap, s32 CCID, XDfeCcf_CCCfg *CCCfg, u32 Symmetric, u32 Num, u32 *TDataDelay)
Gets calculated TDataDelay value for CCID.
InstancePtr Pointer to the Ccf instance. Tap Tap value. CCID CC ID. CCCfg Component carrier (CC) configuration container. Symmetric Select symmetric (1) or non-symmetric (0) filter. Num Number of coefficients values. TDataDelay Data latency value. XST_SUCCESS if successful.XST_FAILURE if error occurs.
References XDfeCcf::SequenceLength, XDfeCcf_GetCarrierCfg, XDFECCF_NUM_COEFF, XDFECCF_TAP_NUMBER_MAX, XST_FAILURE, XST_SUCCESS.
Referenced by XDfeCcf_GetTDataDelay.
void XDfeCcf_SetRegBank(const XDfeCcf *InstancePtr, u32 RegBank)
Sets uplink/downlink register bank.
InstancePtr Pointer to the Channel Filter instance. RegBank Register bank value to be set.
Referenced by XDfeCcf_GetCurrentCCCfgSwitchable, XDfeCcf_SetNextCCCfgAndTriggerSwitchable.
u32 XDfeCcf_GetIsCcfOperational(XDfeCcf *InstancePtr)
Retrieves the current operational state of CCF.
InstancePtr Pointer to the Ccf instance. XST_SUCCESS CCF is operational.XST_FAILURE CCF is NOT operational.
References XST_FAILURE, XST_SUCCESS.
Referenced by XDfeCcf_PassThroughExample.
void XDfeCcf_GetVersions(const XDfeCcf *InstancePtr, XDfeCcf_Version *SwVersion, XDfeCcf_Version *HwVersion)
This API is used to get the driver version.
SwVersion Driver version numbers. HwVersion HW version numbers.
References XDfeCcf_Version::Major, XDfeCcf_Version::Minor, XDfeCcf_Version::Patch, XDfeCcf_Version::Revision, XDfeCcf::StateId, XDFECCF_DRIVER_VERSION_MAJOR, XDFECCF_DRIVER_VERSION_MINOR, XDFECCF_STATE_NOT_READY.
Referenced by XDfeCcf_MultiInstancesExample, XDfeCcf_PassThroughExample.
void XDfeCcf_GetOverflowStatus(const XDfeCcf *InstancePtr, XDfeCcf_OverflowStatus *Status)
Gets overflow event status.
InstancePtr Pointer to the channel filter instance. Status Pointer to a returned overflow event status.
References XDfeCcf_OverflowStatus::OverflowAfterGainImag, XDfeCcf_OverflowStatus::OverflowAfterGainReal, XDfeCcf_OverflowStatus::OverflowAntenna, XDfeCcf_OverflowStatus::OverflowBeforeGainImag, XDfeCcf_OverflowStatus::OverflowBeforeGainReal, XDfeCcf_OverflowStatus::OverflowCCID, XDfeCcf_OverflowStatus::OverflowSwitch.
void XDfeCcf_GetEventStatus(const XDfeCcf *InstancePtr, XDfeCcf_Status *Status)
Gets event status.
InstancePtr Pointer to the channel filter instance. Status Pointer to a returned event status.
References XDfeCcf_Status::CCSequenceError, XDfeCcf_Status::CCUpdate, XDfeCcf_Status::Overflow.
void XDfeCcf_ClearEventStatus(const XDfeCcf *InstancePtr, const XDfeCcf_Status *Status)
Clears events status.
InstancePtr Pointer to the channel filter instance. Status Clear event status container. 0 - does not clear corresponding event status1 - clears corresponding event status
References XDfeCcf_Status::CCSequenceError, XDfeCcf_Status::CCUpdate, XDfeCcf_Status::Overflow.
Referenced by XDfeCcf_multiAddCC_1xNR100_3xNR20_Example, XDfeCcf_PassThroughExample.
void XDfeCcf_SetInterruptMask(const XDfeCcf *InstancePtr, const XDfeCcf_InterruptMask *Mask)
Sets interrupt masks.
InstancePtr Pointer to the channel filter instance. Mask Interrupt mask value. 0 - does not mask corresponding interrupt1 - masks corresponding interrupt
References XDfeCcf_Status::CCSequenceError, XDfeCcf_Status::CCUpdate, XDfeCcf_Status::Overflow.
void XDfeCcf_GetInterruptMask(const XDfeCcf *InstancePtr, XDfeCcf_InterruptMask *Mask)
Gets interrupt masks.
InstancePtr Pointer to the channel filter instance. Mask Interrupt mask value.
References XDfeCcf_Status::CCSequenceError, XDfeCcf_Status::CCUpdate, XDfeCcf_Status::Overflow.
int XDfeCcf_MultiInstancesExample()
This example runs two instances of DFE Channel Filter.
The example does the following tasks: Create and system initialize the device driver instance.Read SW and HW version numbers.Reset the device.Configure the device.Initialize the device.Activate the device.DeActivate the device. XST_SUCCESS if the example has completed successfully.XST_FAILURE if the example has failed.//! [testexample1]
References XDfeCcf_Version::Major, XDfeCcf_Version::Minor, XDfeCcf_Version::Patch, XDfeCcf_Version::Revision, XDfeCcf_Init::TuserSelect, XDfeCcf_Activate, XDfeCcf_Configure, XDfeCcf_Deactivate, XDfeCcf_GetVersions, XDfeCcf_Initialize, XDfeCcf_InstanceClose, XDfeCcf_InstanceInit, XDfeCcf_Reset, XST_FAILURE, XST_SUCCESS.
Referenced by main.
int XDfeCcf_multiAddCC_1xNR100_3xNR20_Example()
This example configures Channel Filter driver for one NR100 carrier and three NR20 whit multiAddCC API and at the end close and release the driver.
The example does the following: initialize driver from reset to activationconfigure filters with the pre-calculated coefficientsGet current configuration.add 4 carriers CCID={0,1,2,3}, 1xNR100(122.88Msps) and 3xNR20(30.72Msps)Trigger configuration update.at this point filters are set and ready to operateclose the driver XST_SUCCESS if the example has completed successfully.XST_FAILURE if the example has failed.//! [testexample3]
References XDfeCcf_Status::CCSequenceError, XDfeCcf_Status::CCUpdate, XDfeCcf_Status::Overflow, XDfeCcf_Activate, XDfeCcf_AddCCtoCCCfg, XDfeCcf_ClearEventStatus, XDfeCcf_Configure, XDfeCcf_Deactivate, XDfeCcf_GetCurrentCCCfg, XDfeCcf_Initialize, XDfeCcf_InstanceClose, XDfeCcf_InstanceInit, XDfeCcf_LoadCoefficients, XDfeCcf_Reset, XDfeCcf_SetNextCCCfgAndTrigger, XDfeCcf_SetTriggersCfg, XST_FAILURE, XST_SUCCESS.
Referenced by main.
XDFECCF_ACTIVE_SET_NUM
Maximum number of active sets.
Referenced by XDfeCcf_GetActiveSets.
XDFECCF_U32_NUM_BITS
Number of bits in register.
XDFECCF_TAP_NUMBER_MAX
Maximum tap number.
Referenced by XDfeCcf_GetTDataDelay, XDfeCcf_GetTDataDelayFromCCCfg.
XDFECCF_DRIVER_VERSION_MINOR
Driver's minor version number.
Referenced by XDfeCcf_GetVersions.
XDFECCF_DRIVER_VERSION_MAJOR
Driver's major version number.
Referenced by XDfeCcf_GetVersions.
XDFECCF_MAX_NUM_INSTANCES
Maximum number of driver instances running at the same time.
XDFECCF_INSTANCE_EXISTS
XST_SUCCESS
Success flag.
Referenced by main, XDfeCcf_AddCC, XDfeCcf_AddCCtoCCCfg, XDfeCcf_GetIsCcfOperational, XDfeCcf_GetTDataDelayFromCCCfg, XDfeCcf_InstanceInit, XDfeCcf_multiAddCC_1xNR100_3xNR20_Example, XDfeCcf_MultiInstancesExample, XDfeCcf_PassThroughExample, XDfeCcf_SetNextCCCfgAndTrigger, XDfeCcf_SetNextCCCfgAndTriggerSwitchable, XDfeSi570_SetMgtOscillator.
XST_FAILURE
Failure flag.
Referenced by main, XDfeCcf_AddCC, XDfeCcf_AddCCtoCCCfg, XDfeCcf_GetIsCcfOperational, XDfeCcf_GetTDataDelayFromCCCfg, XDfeCcf_InstanceInit, XDfeCcf_multiAddCC_1xNR100_3xNR20_Example, XDfeCcf_MultiInstancesExample, XDfeCcf_PassThroughExample, XDfeCcf_SetNextCCCfgAndTrigger, XDfeCcf_SetNextCCCfgAndTriggerSwitchable, XDfeSi570_SetMgtOscillator.
XDFECCF_NODE_NAME_MAX_LENGTH
Node name maximum length.
Referenced by XDfeCcf_InstanceInit.
XDFECCF_CC_NUM
Maximum CC number.
Referenced by XDfeCcf_GetEmptyCCCfg.
XDFECCF_ANT_NUM_MAX
Maximum anntena number.
XDFECCF_SEQ_LENGTH_MAX
Maximum sequence length.
XDFECCF_NUM_COEFF
Maximum number of coefficients.
Referenced by XDfeCcf_GetTDataDelayFromCCCfg, XDfeCcf_LoadCoefficients.
XDFECCF_COMPATIBLE_STRING
Device name property.
XDFECCF_PLATFORM_DEVICE_DIR
Device location in a file system.
XDFECCF_COMPATIBLE_PROPERTY
Device tree property.
XDFECCF_BUS_NAME
System bus name.
XDFECCF_BASEADDR_PROPERTY
Base address property.
XDFECCF_BASEADDR_SIZE
Base address bit-size.
XDFECCF_NUM_ANTENNA_CFG
Number of antenna property.
XDFECCF_NUM_CC_PER_ANTENNA_CFG
Maximum number of CC's per antenna.
XDFECCF_ANTENNA_INTERLEAVE_CFG
Number of Antenna TDM slots, per CC.
XDFECCF_SWITCHABLE_CFG
DL/UL switching support.
XDFECCF_TUSER_WIDTH_CFG
TUSER width property.