xdfeccf_examples.c
int XDfeSi570_SetMgtOscillator(double CurrentFrequency, double NewFrequency)
This function: initialize I2C bus, reads current state of si570, calculates parameters for si570 MGT oscillator new frequency, writes them to si570 and resets PL to use the new frequency.
CurrentFrequency MGT oscillator current frequency. NewFrequency MGT oscillator new frequency. None None
References XST_FAILURE, XST_SUCCESS.
Referenced by main.
int XDfeCcf_MultiInstancesExample()
This example runs two instances of DFE Channel Filter.
The example does the following tasks: Create and system initialize the device driver instance.Read SW and HW version numbers.Reset the device.Configure the device.Initialize the device.Activate the device.DeActivate the device. XST_SUCCESS if the example has completed successfully.XST_FAILURE if the example has failed.//! [testexample1]
References XST_SUCCESS, XST_FAILURE, XDfeCcf_InstanceInit, XDfeCcf_GetVersions, XDfeCcf_Version::Major, XDfeCcf_Version::Minor, XDfeCcf_Version::Revision, XDfeCcf_Version::Patch, XDfeCcf_Reset, XDfeCcf_Configure, XDfeCcf_Init::TuserSelect, XDfeCcf_Initialize, XDfeCcf_Activate, XDfeCcf_Deactivate, XDfeCcf_InstanceClose.
Referenced by main.
int XDfeCcf_PassThroughExample()
This function runs the DFE Channel Filter device using the driver APIs.
This function does the following tasks: Create and system initialize the device driver instance.Read SW and HW version numbers.Reset the device.Configure the device.Initialize the device.Set the triggersActivate the device.Load a channel filter coefficients.Add CC.DeActivate the device. XST_SUCCESS if the example has completed successfully.XST_FAILURE if the example has failed.
References XDfeCcf_TriggerCfg::Activate, XDfeCcf_Status::CCSequenceError, XDfeCcf_TriggerCfg::CCUpdate, XDfeCcf_Status::CCUpdate, XDfeCcf_CarrierCfg::Gain, XDfeCcf_Init::GainStage, XDfeCcf_CarrierCfg::ImagCoeffSet, XDfeCcf_CCSequence::Length, XDfeCcf_Version::Major, XDfeCcf_Version::Minor, XDfeCcf_Trigger::Mode, XDfeCcf_Coefficients::Num, XDfeCcf_Status::Overflow, XDfeCcf_Version::Patch, XDfeCcf_CarrierCfg::RealCoeffSet, XDfeCcf_Version::Revision, XDfeCcf_Init::Sequence, XDfeCcf_Coefficients::Symmetric, XDfeCcf_Trigger::TUSERBit, XDfeCcf_Trigger::TuserEdgeLevel, XDfeCcf_Init::TuserSelect, XDfeCcf_Coefficients::Value, XDfeCcf_Activate, XDfeCcf_AddCC, XDfeCcf_ClearEventStatus, XDfeCcf_Configure, XDfeCcf_Deactivate, XDfeCcf_GetIsCcfOperational, XDfeCcf_GetVersions, XDfeCcf_Initialize, XDfeCcf_InstanceClose, XDfeCcf_InstanceInit, XDfeCcf_LoadCoefficients, XDfeCcf_Reset, XDfeCcf_SetTriggersCfg, XST_FAILURE, XST_SUCCESS.
Referenced by main.
int XDfeCcf_1xNR100_3xNR20_Example()
int XDfeCcf_multiAddCC_1xNR100_3xNR20_Example()
This example configures Channel Filter driver for one NR100 carrier and three NR20 whit multiAddCC API and at the end close and release the driver.
The example does the following: initialize driver from reset to activationconfigure filters with the pre-calculated coefficientsGet current configuration.add 4 carriers CCID={0,1,2,3}, 1xNR100(122.88Msps) and 3xNR20(30.72Msps)Trigger configuration update.at this point filters are set and ready to operateclose the driver XST_SUCCESS if the example has completed successfully.XST_FAILURE if the example has failed.//! [testexample3]
References XST_SUCCESS, XST_FAILURE, XDfeCcf_InstanceInit, XDfeCcf_Reset, XDfeCcf_Configure, XDfeCcf_Initialize, XDfeCcf_SetTriggersCfg, XDfeCcf_Activate, XDfeCcf_LoadCoefficients, XDfeCcf_GetCurrentCCCfg, XDfeCcf_Status::Overflow, XDfeCcf_Status::CCUpdate, XDfeCcf_Status::CCSequenceError, XDfeCcf_ClearEventStatus, XDfeCcf_AddCCtoCCCfg, XDfeCcf_SetNextCCCfgAndTrigger, XDfeCcf_Deactivate, XDfeCcf_InstanceClose.
Referenced by main.
int main(void)
Main function that initialise si570 and runs examples.
None. XST_SUCCESS if the example has completed successfully.XST_FAILURE if the example has failed.
References XDfeCcf_multiAddCC_1xNR100_3xNR20_Example, XDfeCcf_MultiInstancesExample, XDfeCcf_PassThroughExample, XDfeSi570_SetMgtOscillator, XST_FAILURE, XST_SUCCESS.