xhdcp22_rx_dp.c
static int XHdcp22Rx_InitializeCipher(XHdcp22_Rx_Dp *InstancePtr)
This function is called to initialize the cipher.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. XST_SUCCESS or XST_FAILURE. None.
static int XHdcp22Rx_InitializeMmult(XHdcp22_Rx_Dp *InstancePtr)
This function is called to initialize the modular multiplier.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. XST_SUCCESS or XST_FAILURE. None.
static int XHdcp22Rx_InitializeRng(XHdcp22_Rx_Dp *InstancePtr)
This function is called to initialize the random number generator.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. XST_SUCCESS or XST_FAILURE. None.
static int XHdcp22Rx_ComputeBaseAddress(UINTPTR BaseAddress, UINTPTR SubcoreOffset, UINTPTR *SubcoreAddressPtr)
This function computes the subcore absolute address on axi-lite interface Subsystem is mapped at an absolute address and all included sub-cores are at pre-defined offset from the subsystem base address.
To access the subcore register map from host CPU an absolute address is required. BaseAddress is the base address of the subsystem instance SubcoreOffset is the offset of the the subcore instance SubcoreAddressPtr is the computed base address of the subcore instance XST_SUCCESS if base address computation is successful and within subsystem address range else XST_FAILURE
static int XHdcp22Rx_GenerateRrx(XHdcp22_Rx_Dp *InstancePtr, u8 *RrxPtr)
This function is used to get a random value Rrx of 64bits for AKEInit.
When the test mode is set to XHDCP22_RX_TESTMODE_NO_TX a preloaded test value is copied into the array with pointer RrxPtr. Otherwise, a random value is generated and copied. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. RrxPtr is a pointer to an array where the 64bit Rrx is to be copied. XST_SUCCESS or XST_FAILURE. None.
static u8 XHdcp22Rx_IsWriteMessageAvailable(XHdcp22_Rx_Dp *InstancePtr)
This function is used to check if a complete message is available in the write message buffer.
The DDC flag is cleared when a message available is detected. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. TRUE or FALSE. None.
static u8 XHdcp22Rx_IsReadMessageComplete(XHdcp22_Rx_Dp *InstancePtr)
This function is used to check if a complete message has been read out of the read message buffer, indicating that the buffer is empty.
The DDC flag is cleared when a read message complete has been detected. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. TRUE or FALSE. None.
static void XHdcp22Rx_SetRxStatus(XHdcp22_Rx_Dp *InstancePtr, u16 MessageSize, u8 ReauthReq, u8 TopologyReady)
This function sets the DDC RxStatus registers (0x70-0x71) MessageSize bits.
The HDCP22-RX state machine calls this function immediately after writing a complete message into the read message buffer. The repeater READY bit can also be updated in conjunction to the message size. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. MessageSize indicates the size in bytes of the message available in the read message buffer. ReauthReq is set to TRUE to assert the REAUTH_REQ bit. TopologyReady is set to TRUE to assert the READY bit. None. None.
static void XHdcp22Rx_SetDdcReauthReq(XHdcp22_Rx_Dp *InstancePtr)
This function sets the DDC RxStatus registers (0x70-0x71) ReauthReq bit and clears the link integrity error flag.
Setting the ReauthReq bit signals the transmitter to re-initiate authentication. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. None. None.
static void XHdcp22Rx_ResetDdc(XHdcp22_Rx_Dp *InstancePtr, u8 ClrWrBuffer, u8 ClrRdBuffer, u8 ClrReady, u8 ClrReauthReq)
This function resets the HDCP22-RX DDC registers to their default values and clears the read/write message buffers.
The DDC status flag is set to it's initial state and the DDC error flags are cleared. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. ClrWrBuffer is TRUE to clear the write message buffer. ClrRdBuffer is TRUE to clear the read message buffer. ClrReady is TRUE to clear the READY bit. ClrReauthReq is set to TRUE to clear the REAUTH_REQ bit. None. None.
static void XHdcp22Rx_ResetAfterError(XHdcp22_Rx_Dp *InstancePtr)
This function resets the HDCP22-RX system after an error event.
The driver calls this function when recovering from error conditions. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. None. None.
static void XHdcp22Rx_ResetParams(XHdcp22_Rx_Dp *InstancePtr)
This function resets the HDCP22-RX parameters stored in memory during the authentication process.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. None. This function is called each time an AKE_Init message is received.
static int XHdcp22Rx_PollMessage(XHdcp22_Rx_Dp *InstancePtr)
This function uses polling to read a complete message out of the read message buffer.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. Size of message read out of read message buffer. None.
static void XHdcp22Rx_StartTimer(XHdcp22_Rx_Dp *InstancePtr, u32 TimeOut_mSec, u8 ReasonId)
This function starts the count down timer needed for checking protocol timeouts.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. TimeOut_mSec is the timeout for the next status update. XST_SUCCESS or XST_FAILURE. None.
static void XHdcp22Rx_StopTimer(XHdcp22_Rx_Dp *InstancePtr)
This function stops the count down timer used for protocol timeouts.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. TimeOut_mSec is the timeout for the next status update. XST_SUCCESS or XST_FAILURE. None.
static void * XHdcp22Rx_StateB0(XHdcp22_Rx_Dp *InstancePtr)
This function implements the Receiver State B0 (Unauthenticated).
In this state the receiver is awaiting the reception of AKE_Init from the transmitter to trigger the authentication protocol. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. Pointer to the function that implements the next state. When an unexpected or malformed message is received the system is reset to a known state to allow graceful recovery from error.
static void * XHdcp22Rx_StateB1(XHdcp22_Rx_Dp *InstancePtr)
This function implements the Receiver State B1 (ComputeKm).
In this state the receiver makes the AKESendCert message available for reading by the transmitter in response to AKEInit. If AKENoStoredKm is received, the receiver decrypts Km with KprivRx and calculates HPrime. If AKEStoredKm is received it decrypts Ekh(Km) to derive Km and calculate HPrime. It makes AKESendHPrime message available for reading immediately after computation of HPrime to ensure that the message is received by the transmitter within the specified 1s timeout at the transmitter for NoStoredKm and 200ms timeout for StoredKm. When AKENoStoredKm is received the AKESendPairingInfo message is made available to the transmitter for reading after within 200ms after AKESendHPrime message is received by the transmitter. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. Pointer to the function that implements the next state. When an unexpected or malformed message is received the system is reset to the default state B0 to allow graceful recovery from error.
static void * XHdcp22Rx_StateB2(XHdcp22_Rx_Dp *InstancePtr)
This function implements the Receiver State B2 (Compute_LPrime).
The receiver computes LPrime required during locality check and makes LCSendLPrime message available for reading by the transmitter. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. Pointer to the function that implements the next state. When an unexpected or malformed message is received the system is reset to the default state B0 to allow graceful recovery from error.
static void * XHdcp22Rx_StateB3(XHdcp22_Rx_Dp *InstancePtr)
This function implements the Receiver State B3 (ComputeKs).
The receiver decrypts Edkey(Ks) to derive Ks. The cipher is updated with the session key and enabled within 200ms after the encrypted session key is received. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. Pointer to the function that implements the next state. When an unexpected or malformed message is received the system is reset to the default state B0 to allow graceful recovery from error.
static void * XHdcp22Rx_StateB4(XHdcp22_Rx_Dp *InstancePtr)
This function implements the Receiver State B4 (Authenticated).
The receiver has completed the authentication protocol. This function executes the XHDCP22_RX_HANDLER_AUTHENTICATED user callback function on transition to this state. An ongoing link integrity check is performed external to the HDCP22-RX system to detect synchronization mismatches between transmitter and receiver. RxStatus REAUTH_REQ bit is set if 50 consecutive data island CRC errors are detected. Setting the REAUTH_REQ bit signals the transmitter to re-initiate authentication. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. Pointer to the function that implements the next state. When an unexpected or malformed message is received the system is reset to the default state B0 to allow graceful recovery from error.
static void * XHdcp22Rx_StateC4(XHdcp22_Rx_Dp *InstancePtr)
This function implements the Repeater State C4 (WaitForDownstream).
In this state the receiver upstream is waiting for all downstream HDCP-protected interface ports of the HDCP Repeater to enter one of the following states: Unconnected (State P0), Unauthenticated (State P1), Authenticated (State F5), or ReceiverIdListAck (State F8). This state checks if the topology table is available for upstream propagation based on the flag set in the function XHdcp22Rx_Dp_SetTopologyUpdate by the higher level repeater function. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. Pointer to the function that implements the next state. If a link integrity problem is detected during this state then the REAUTH_REQ bit is set in the RxStatus register. If the RepeaterAuth_Stream_Manage message is received then transition to State C7 then return back to this state.
static void * XHdcp22Rx_StateC5(XHdcp22_Rx_Dp *InstancePtr)
This function implements the Repeater State C5 (AssembleReceiverIdList).
If MAX_DEVS_EXCEEDED or MAX_CASCADE_EXCEEDED is not set then this state calculates VPrime based on the Receiver ID List in the topology table. After VPrime is calculated the Repeaterauth_Send_ReceiverID_List message is populated based on the topology table, VPrime computation, and current seq_num_V counter value. seq_num_V is initialized to a value of zero after AKE_Init and is incremented by one after the transmission of every RepeaterAuth_Send_ReceiverID_List message. The upstream transmitter is responsible for detecting roll over of seq_num_V. The READY bit is asserted once the Repeaterauth_Send_ReceiverID_List message is made available to the upstream and a watchdog timer is set to detect if the acknowledgement arrives within a 2 second period. If the topology maximum flags are asserted in the topology table then the state machine transitions to StateC0 immediately after the Repeaterauth_Send_ReceiverID_List message is read, and the REAUTH_REQ bit is set the in the RxStatus register. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. Pointer to the function that implements the next state. If a link integrity problem is detected during this state then the REAUTH_REQ bit is set in the RxStatus register. If the RepeaterAuth_Stream_Manage message is received then transition to State C7 then return back to this state.
static void * XHdcp22Rx_StateC6(XHdcp22_Rx_Dp *InstancePtr)
This function implements the Repeater State C6 (VerifyReceiverIdListAck).
The RepeaterAuth_Send_Ack message should be available for the receiver upstream interface within two seconds from when the READY bit in the RxStatus register was set in State C5. If the message is not available within the two second window then the state machine transitions back into the un-authenticated state. If the message is received in-time and the least significant 128-bits of V and VPrime match, this indicated successful upstream transmission of topology information and triggers a transition to State C7. If there is a mismatch then the state machine transitions back to the un-authenticated state, and the REAUTH_REQ bit is set in the RxStatus Register. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. Pointer to the function that implements the next state. If a link integrity problem is detected during this state then the REAUTH_REQ bit is set in the RxStatus register. If the RepeaterAuth_Stream_Manage message is received then transition to State C7 then return back to this state.
static void * XHdcp22Rx_StateC7(XHdcp22_Rx_Dp *InstancePtr)
This function implements the Repeater State C7 (ContentStreamManagement).
This state waits to receive the RepeaterAuth_Stream_Manage message from the upstream transmitter. Once the message is received the MPrime value is computed and made available to the upstream transmitter to read as part of the RepeaterAuth_Stream_Ready message. Note that state executes in parallel with the upstream propagation of topology information (State C4, State C5, and State C6). A transition in to this state may occur from State C4, State C5, or State C6 if content stream management information is received from the upstream transmitter. Also, the transition from State C7 may return to the appropriate state to allow undisrupted operation. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. Pointer to the function that implements the next state. If a link integrity problem is detected during this state then the REAUTH_REQ bit is set in the RxStatus register. If the RepeaterAuth_Stream_Manage message is received then transition to State C7 then return back to this state.
static void * XHdcp22Rx_StateC8(XHdcp22_Rx_Dp *InstancePtr)
This function implements the Receiver State C8 (Authenticated).
The repeater has completed the authentication protocol. Upon detection of any changes to the topology a transition back to State C5 (AssembleReceiverIdList) occurs. Change to the topology occur when a repeater downstream port has transitioned to the following: authenticated, unauthenticated, or unconnected. This function executes the XHDCP22_RX_HANDLER_AUTHENTICATED user callback function on transition to this state. An ongoing link integrity check is performed external to the HDCP22-RX system to detect synchronization mismatches between transmitter and receiver. RxStatus REAUTH_REQ bit is set if 50 consecutive data island CRC errors are detected. Setting the REAUTH_REQ bit signals the transmitter to re-initiate authentication. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. Pointer to the function that implements the next state. When an unexpected or malformed message is received the system is reset to the default state B0 to allow graceful recovery from error.
static int XHdcp22Rx_ProcessMessageAKEInit(XHdcp22_Rx_Dp *InstancePtr)
This function processes the AKE_Init message received from the transmitter.
The stored authentication parameters are reset so that no state information is stored between authentication attempts. The DDC registers are reset to their default value including the REAUTH_REQ flag. The cipher is disabled. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. - XST_SUCCESS if message processed successfully. XST_FAILURE if message size is incorrect. None.
static int XHdcp22Rx_ProcessMessageAKENoStoredKm(XHdcp22_Rx_Dp *InstancePtr)
This function processes the AKE_No_Stored_km message received from the transmitter.
The RSAES-OAEP operation decrypts Km with the receiver private key. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. - XST_SUCCESS if message processed successfully. XST_FAILURE if message size is incorrect or Km decryption failed. None.
static int XHdcp22Rx_ProcessMessageAKEStoredKm(XHdcp22_Rx_Dp *InstancePtr)
This function processes the AKE_Stored_km message received from the transmitter.
Decrypts Ekh(Km) using AES with the received m as input and Kh as key into the AES module. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. - XST_SUCCESS if message processed successfully. XST_FAILURE if message size is incorrect. None.
static int XHdcp22Rx_ProcessMessageLCInit(XHdcp22_Rx_Dp *InstancePtr)
This function processes the LC_Init message received from the transmitter.
The locality check attempts is incremented for each LCInit message received. The random nonce Rn is recorded. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. - XST_SUCCESS if message processed successfully. XST_FAILURE if message size is incorrect. None.
static int XHdcp22Rx_ProcessMessageSKESendEks(XHdcp22_Rx_Dp *InstancePtr)
This function processes the SKE_Send_Eks message received from the transmitter.
The session key Ks is decrypted and written to the cipher. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. - XST_SUCCESS if message processed successfully. XST_FAILURE if message size is incorrect. The cipher must be enabled within 200ms after receiving SKESendEks.
static int XHdcp22Rx_ProcessMessageRepeaterAuthSendAck(XHdcp22_Rx_Dp *InstancePtr)
This function processes the RepeaterAuth_Send_Ack message received from the upstream transmitter.
The least significant 128-bits of the value V are compared against VPrime. The timer is stopped. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. - XST_SUCCESS when V and VPrime match. XST_FAILURE when V and VPrime do not match. The RepeaterAuth_Send_Ack message must be available for the repeater upstream interface within 2 seconds after asserting the READY bit in the RxStatus register.
static int XHdcp22Rx_ProcessMessageRepeaterAuthStreamManage(XHdcp22_Rx_Dp *InstancePtr)
This function processes the RepeaterAuth_Repeater_Manage message.
The message values seq_num_M and StreamID_Type are stored for later computation of MPrime. The user callback function type XHDCP22_RX_HANDLER_STREAM_MANAGE_REQUEST is executed. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. - XST_SUCCESS if message processed successfully. XST_FAILURE if message size is incorrect. After receiving RepeaterAuth_Repeater_Manage message the repeater upstream interface has 100ms to respond with the RepeaterAuth_Stream_Ready message. Detection of seq_num_M roll-over is the responsibility of the upstream transmitter.
static int XHdcp22Rx_SendMessageAKESendCert(XHdcp22_Rx_Dp *InstancePtr)
This function generates the AKE_Send_Cert message and writes it into the read message buffer.
After the complete message has been written to the buffer the MessageSize is set in the DDC RxStatus register signaling the transmitter that the message is available for reading. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. - XST_SUCCESS if message written successfully. XST_FAILURE if generation of random integer Rrx failed. This message must be available for the transmitter with 100ms after receiving AKEInit.
static int XHdcp22Rx_SendMessageAKESendHPrime(XHdcp22_Rx_Dp *InstancePtr)
This function computes HPrime, generates AKE_Send_H_prime message, and writes it into the read message buffer.
After the complete message has been written to the buffer the MessageSize is set in the DDC RxStatus register signaling the transmitter that the message is available for reading. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. XST_SUCCESS. This message must be available for the transmitter within 1s after receiving AKENoStoredKm or 200ms after receiving AKEStoredKm.
static int XHdcp22Rx_SendMessageAKESendPairingInfo(XHdcp22_Rx_Dp *InstancePtr)
This function computes Ekh(Km), generates AKE_Send_Pairing_Info message, and writes it into the read message buffer.
After the complete message has been written to the buffer the MessageSize is set in the DDC RxStatus register signaling the transmitter that the message is available for reading. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. XST_SUCCESS. The AKESendPairingInfo message is sent only in response to receiving AKENoStoredKm message. This message must be available for the transmitter within 200ms after sending AKESendHPrime.
static int XHdcp22Rx_SendMessageLCSendLPrime(XHdcp22_Rx_Dp *InstancePtr)
This function computes LPrime, generates LC_Send_L_prime message, and writes it into the read message buffer.
After the complete message has been written to the buffer the MessageSize is set in the DDC RxStatus register signaling the transmitter that the message is available for reading. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. XST_SUCCESS. The LCSendLPrime message must be available for the transmitter within 20ms after receiving LCInit.
static int XHdcp22Rx_SendMessageRepeaterAuthSendRxIdList(XHdcp22_Rx_Dp *InstancePtr)
This function generates the RepeaterAuth_Send_ReceiverID_List message and writes it into the read message buffer.
After the complete message has been written to the buffer the MessageSize and READY fields are set in the DDC RxStatus register signaling the transmitter that the message is available for reading. When the topology maximums are not exceeded VPrime is computed. seq_num_v is incremented after the transmission of each RepeaterAuth_Send_ReceiverID_List message. The READY bit in the RxStatus register is cleared automatically. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. - XST_SUCCESS if device count is equal to zero. XST_FAILURE if device count is greater than zero. The RepeaterAuth_Send_ReceiverID_List must be available and READY bit asserted in the RxStatus register for the upstream transmitter within 3 seconds.
static int XHdcp22Rx_SendMessageRepeaterAuthStreamReady(XHdcp22_Rx_Dp *InstancePtr)
This function computes MPrime and sends the RepeaterAuth_Stream_Ready message.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. XST_SUCCESS. None.
static void XHdcp22Rx_SetTopologyDepth(XHdcp22_Rx_Dp *InstancePtr, u8 Depth)
This function sets DEPTH in the repeater topology table.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. Depth is the Repeater cascade depth. This value gives the number of attached levels through the connection topology. The depth cannot cannot exceed 4 levels. None. None.
static void XHdcp22Rx_SetTopologyDeviceCnt(XHdcp22_Rx_Dp *InstancePtr, u8 DeviceCnt)
This function sets DEVICE_COUNT in the repeater topology table.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. DeviceCnt is the Total number of connected downstream devices. Always zero for HDCP Receivers. The device count does not include the HDCP Repeater itself, but only devices downstream from the HDCP Repeater. The device count cannot exceed 31 devices. None. None.
static void XHdcp22Rx_SetTopologyMaxDevsExceeded(XHdcp22_Rx_Dp *InstancePtr, u8 Value)
This function sets the MAX_DEVS_EXCEEDED error flag in the repeater topology table used to indicate a topology error.
Setting the flag indicates that more than 31 downstream devices are attached. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. Value is either TRUE or FALSE. None. None.
static void XHdcp22Rx_SetTopologyMaxCascadeExceeded(XHdcp22_Rx_Dp *InstancePtr, u8 Value)
This function sets the MAX_CASCADE_EXCEEDED flag in the repeater topology table used to indicate a topology error.
Setting the error flag indicates that more than four levels of repeaters have been cascaded together. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. Value is either TRUE or FALSE. None. None.
static void XHdcp22Rx_SetTopologyHdcp2LegacyDeviceDownstream(XHdcp22_Rx_Dp *InstancePtr, u8 Value)
This function sets the HDCP2_LEGACY_DEVICE_DOWNSTREAM flag in the repeater topology table used to indicate the presence of an HDCP2.0-compliant Device in the topology.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. Value is either TRUE or FALSE. None. None.
static void XHdcp22Rx_SetTopologyHdcp1DeviceDownstream(XHdcp22_Rx_Dp *InstancePtr, u8 Value)
This function sets the HDCP1_DEVICE_DOWNSTREAM flag in the repeater topology table used to indicate the presence of an HDCP1.x-compliant device in the topology.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. Value is either TRUE or FALSE. None. None.
static void XHdcp22_Rx_StubRunHandler(void *HandlerRef)
This function is a stub for the run handler.
The stub is here in case the upper layer forgot to set the handlers. On initialization, all handlers are set to this callback. It is considered an error for this handler to be invoked. HandlerRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. None. None.
static void XHdcp22_Rx_StubSetHandler(void *HandlerRef, u32 Data)
This function is a stub for the set handler.
The stub is here in case the upper layer forgot to set the handlers. On initialization, all handlers are set to this callback. It is considered an error for this handler to be invoked. HandlerRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. Data is a value to be set. None. None.
static u32 XHdcp22_Rx_StubGetHandler(void *HandlerRef)
This function is a stub for the set handler.
The stub is here in case the upper layer forgot to set the handlers. On initialization, all handlers are set to this callback. It is considered an error for this handler to be invoked. HandlerRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. Returns the get value. None.
static u32 XHdcp22_Rx_StubRdWrHandler(void *HandlerRef, u32 offset, u8 *buf, u32 size)
This function is a stub for the set handler.
The stub is here in case the upper layer forgot to set the handlers. On initialization, all handlers are set to this callback. It is considered an error for this handler to be invoked. HandlerRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. offset is a offset to be read/write from/to. buf is a pointer to the dat to be written/read into/from size is the size of data to be written/read size of data that is written/read. None.
static int XHdcp22Rx_Dp_Read_Dpcd_Msg(XHdcp22_Rx_Dp *InstancePtr)
This function reads a complete message out of the DPCD registers based on the DPCD flag.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. Size of message read out of read message buffer. For DP there are no msg_ids for all the HDCP msgs, But to make less changes in the already existed HDCP22 statmachine which is written for HDMI, Assigned msg_ids for each msg rcvd.
static int XHdcp22Rx_Dp_Write_Dpcd_Msg(XHdcp22_Rx_Dp *InstancePtr)
This function writes a complete message into the DPCD registers.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. Size of message read out of read message buffer. For DP there are no msg_ids for all the HDCP msgs, But to make less changes in the already existed HDCP22 statmachine which is written for HDMI, Assigned msg_ids for each msg rcvd.
int XHdcp22Rx_Dp_CfgInitialize(XHdcp22_Rx_Dp *InstancePtr, XHdcp22_Rx_Dp_Config *ConfigPtr, UINTPTR EffectiveAddr)
Initialize the instance provided by the caller based on the given configuration data.
InstancePtr is a pointer to an XHdcp22_Rx_Dp instance. The memory the pointer references must be pre-allocated by the caller. Further calls to manipulate the driver through the HDCP22-RX API must be made with this pointer. ConfigPtr is a reference to a structure containing information about a specific HDCP22-RX device. This function initializes an InstancePtr object for a specific device specified by the contents of Config. This function can initialize multiple instance objects with the use of multiple calls giving different Config information on each call. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS or XST_FAILURE. None.
References XHdcp22_Rx_Dp_Handles::AuthenticatedCallback, XHdcp22_Rx_Dp_Handles::AuthenticationRequestCallback, XHdcp22_Rx_Dp_Info::AuthenticationStatus, XHdcp22_Rx_Dp_Info::AuthRequestCnt, XHdcp22_Rx_Dp_Config::BaseAddress, XHdcp22_Rx_Dp::Config, XHdcp22_Rx_Dp_Info::CurrentState, XHdcp22_Rx_Dp_Handles::DdcClearReadBufferCallback, XHdcp22_Rx_Dp_Handles::DdcClearWriteBufferCallback, XHdcp22_Rx_Dp_Info::DdcErrorCnt, XHdcp22_Rx_Dp_Handles::DdcGetDataCallback, XHdcp22_Rx_Dp_Handles::DdcGetReadBufferSizeCallback, XHdcp22_Rx_Dp_Handles::DdcGetWriteBufferSizeCallback, XHdcp22_Rx_Dp_Handles::DdcIsReadBufferEmptyCallback, XHdcp22_Rx_Dp_Handles::DdcIsWriteBufferEmptyCallback, XHdcp22_Rx_Dp_Handles::DdcSetAddressCallback, XHdcp22_Rx_Dp_Handles::DdcSetDataCallback, XHdcp22_Rx_Dp_Info::ErrorFlag, XHdcp22_Rx_Dp_Info::ErrorFlagSticky, XHdcp22_Rx_Dp::Handles, XHdcp22_Rx_Dp_Info::HasStreamManagementInfo, XHdcp22_Rx_Dp::Info, XHdcp22_Rx_Dp_Handles::IsAuthenticatedCallbackSet, XHdcp22_Rx_Dp_Handles::IsAuthenticationRequestCallbackSet, XHdcp22_Rx_Dp_Handles::IsDdcAllCallbacksSet, XHdcp22_Rx_Dp_Handles::IsDdcClearReadBufferCallbackSet, XHdcp22_Rx_Dp_Handles::IsDdcClearWriteBufferCallbackSet, XHdcp22_Rx_Dp_Handles::IsDdcGetDataCallbackSet, XHdcp22_Rx_Dp_Handles::IsDdcGetReadBufferSizeCallbackRefSet, XHdcp22_Rx_Dp_Handles::IsDdcGetWriteBufferSizeCallbackSet, XHdcp22_Rx_Dp_Handles::IsDdcIsReadBufferEmptyCallbackSet, XHdcp22_Rx_Dp_Handles::IsDdcIsWriteBufferEmptyCallbackSet, XHdcp22_Rx_Dp_Handles::IsDdcSetAddressCallbackSet, XHdcp22_Rx_Dp_Handles::IsDdcSetDataCallbackSet, XHdcp22_Rx_Dp_Info::IsEnabled, XHdcp22_Rx_Dp_Info::IsEncrypted, XHdcp22_Rx_Dp_Info::IsNoStoredKm, XHdcp22_Rx_Dp::IsReady, XHdcp22_Rx_Dp_Handles::IsRxDpAuxReadCallbackSet, XHdcp22_Rx_Dp_Handles::IsRxDpAuxWriteCallbackSet, XHdcp22_Rx_Dp_Handles::IsRxDpCpIrqSetCallbackSet, XHdcp22_Rx_Dp_Handles::IsRxDpSetClearAuxDeferCallbackSet, XHdcp22_Rx_Dp_Handles::IsSke_Send_EksCallbackSet, XHdcp22_Rx_Dp_Handles::IsStreamManageRequestCallbackSet, XHdcp22_Rx_Dp_Handles::IsTopologyUpdateCallbackSet, XHdcp22_Rx_Dp_Info::IsTopologyValid, XHdcp22_Rx_Dp_Info::LCInitAttempts, XHdcp22_Rx_Dp_Info::LinkErrorCnt, XHdcp22_Rx_Dp_Config::Mode, XHdcp22_Rx_Dp_Info::NextState, XHdcp22_Rx_Dp_Info::ReauthReq, XHdcp22_Rx_Dp_Info::ReauthRequestCnt, XHdcp22_Rx_Dp_Info::ReturnState, XHdcp22_Rx_Dp::RxCaps, XHdcp22_Rx_Dp_Handles::RxDpAuxReadCallback, XHdcp22_Rx_Dp_Handles::RxDpAuxWriteCallback, XHdcp22_Rx_Dp_Handles::RxDpCpIrqSetCallback, XHdcp22_Rx_Dp_Handles::RxDpSetClearAuxDeferCallback, XHdcp22_Rx_Dp_Info::SeqNumV, XHdcp22_Rx_Dp_Handles::Ske_Send_EksCallback, XHdcp22_Rx_Dp_Info::SkipRead, XHdcp22_Rx_Dp::StateFunc, XHdcp22_Rx_Dp_Handles::StreamManageRequestCallback, XHdcp22_Rx_Dp_Info::TopologyReady, XHdcp22_Rx_Dp_Handles::TopologyUpdateCallback, XHDCP22_RX_ERROR_FLAG_NONE, XHDCP22_RX_RECEIVER, XHDCP22_RX_STATE_B0_WAIT_AKEINIT, XHDCP22_RX_STATE_UNDEFINED, XHDCP22_RX_UNAUTHENTICATED, XHdcp22Rx_Dp_LogReset.
int XHdcp22Rx_Dp_Reset(XHdcp22_Rx_Dp *InstancePtr)
This function resets the HDCP22-RX system to the default state.
The HDCP22-RX DDC registers are set to their default value and the message buffer is reset. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. XST_SUCCESS or XST_FAILURE. The DDC message handles must be assigned by the XHdcp22Rx_SetDdcHandles function prior to calling this reset function.
References XHdcp22_Rx_Dp_Info::AuthenticationStatus, XHdcp22_Rx_Dp_Info::AuthRequestCnt, XHdcp22_Rx_Dp::CipherInst, XHdcp22_Rx_Dp::Config, XHdcp22_Rx_Dp_Info::CurrentState, XHdcp22_Rx_Dp_Info::DdcErrorCnt, XHdcp22_Rx_Dp_Info::ErrorFlag, XHdcp22_Rx_Dp_Info::ErrorFlagSticky, XHdcp22_Rx_Dp::Handles, XHdcp22_Rx_Dp_Info::HasStreamManagementInfo, XHdcp22_Rx_Dp::Info, XHdcp22_Rx_Dp_Handles::IsDdcAllCallbacksSet, XHdcp22_Rx_Dp_Info::IsEncrypted, XHdcp22_Rx_Dp_Info::IsNoStoredKm, XHdcp22_Rx_Dp_Info::IsTopologyValid, XHdcp22_Rx_Dp_Handles::IsUnauthenticatedCallbackSet, XHdcp22_Rx_Dp_Info::LCInitAttempts, XHdcp22_Rx_Dp_Info::LinkErrorCnt, XHdcp22_Rx_Dp::MessageBuffer, XHdcp22_Rx_Dp::MessageSize, XHdcp22_Rx_Dp_Info::NextState, XHdcp22_Rx_Dp_Config::Protocol, XHdcp22_Rx_Dp_Info::ReauthReq, XHdcp22_Rx_Dp_Info::ReauthRequestCnt, XHdcp22_Rx_Dp_Info::ReturnState, XHdcp22_Rx_Dp_Info::SeqNumV, XHdcp22_Rx_Dp_Info::SkipRead, XHdcp22_Rx_Dp::StateFunc, XHdcp22_Rx_Dp::Topology, XHdcp22_Rx_Dp_Info::TopologyReady, XHdcp22_Rx_Dp_Handles::UnauthenticatedCallback, XHdcp22_Rx_Dp_Handles::UnauthenticatedCallbackRef, XHDCP22_RX_AUTHENTICATED, XHDCP22_RX_DP, XHDCP22_RX_ERROR_FLAG_NONE, XHDCP22_RX_LOG_EVT_INFO, XHDCP22_RX_LOG_INFO_RESET, XHDCP22_RX_STATE_B0_WAIT_AKEINIT, XHDCP22_RX_STATE_UNDEFINED, XHDCP22_RX_UNAUTHENTICATED, XHdcp22Rx_Dp_LogWr.
int XHdcp22Rx_Dp_Enable(XHdcp22_Rx_Dp *InstancePtr)
This function enables the HDCP22-RX state machine.
The HDCP2Version register is set to active. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. XST_SUCCESS or XST_FAILURE. Before enabling the state machine ensure that the instance has been initialized, DDC message handles have been assigned, and keys have been loaded.
References XHdcp22_Rx_Dp::CipherInst, XHdcp22_Rx_Dp::Config, XHdcp22_Rx_Dp::Handles, XHdcp22_Rx_Dp::Info, XHdcp22_Rx_Dp_Handles::IsDdcAllCallbacksSet, XHdcp22_Rx_Dp_Info::IsEnabled, XHdcp22_Rx_Dp::IsReady, XHdcp22_Rx_Dp::MmultInst, XHdcp22_Rx_Dp::PrivateKeyPtr, XHdcp22_Rx_Dp_Config::Protocol, XHdcp22_Rx_Dp::PublicCertPtr, XHdcp22_Rx_Dp::RngInst, XHdcp22_Rx_Dp::TimerInst, XHDCP22_RX_DP, XHDCP22_RX_LOG_EVT_INFO, XHDCP22_RX_LOG_INFO_ENABLE, XHdcp22Rx_Dp_LogWr.
int XHdcp22Rx_Dp_Disable(XHdcp22_Rx_Dp *InstancePtr)
This function disables the HDCP22-RX state machine.
The HDCP2Version register is cleared, and the ReauthReq bit is set in the RxStatus register to allow the transmitter to recover when it has already authenticated. Without setting the ReauthReq bit the transmitter will not know that HDCP 2.2 protocol has been disabled by the Receiver after it has already authenticated. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. XST_SUCCESS or XST_FAILURE. The HDCP22-RX cipher is disabled.
References XHdcp22_Rx_Dp_Info::AuthenticationStatus, XHdcp22_Rx_Dp::CipherInst, XHdcp22_Rx_Dp::Info, XHdcp22_Rx_Dp_Info::IsEnabled, XHdcp22_Rx_Dp::RngInst, XHDCP22_RX_AUTHENTICATED, XHDCP22_RX_LOG_EVT_INFO, XHDCP22_RX_LOG_INFO_DISABLE, XHdcp22Rx_Dp_LogWr.
int XHdcp22Rx_Dp_SetCallback(XHdcp22_Rx_Dp *InstancePtr, XHdcp22_Rx_Dp_HandlerType HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs callback functions for the given HandlerType:
HandlerType Callback Function Type ------------------------- --------------------------- (XHDCP22_RX_HANDLER_DDC_SETREGADDR) DdcSetAddressCallback (XHDCP22_RX_HANDLER_DDC_SETREGDATA) DdcSetDataCallback (XHDCP22_RX_HANDLER_DDC_GETREGDATA) DdcGetDataCallback (XHDCP22_RX_HANDLER_DDC_GETWBUFSIZE) DdcGetWriteBufferSizeCallback (XHDCP22_RX_HANDLER_DDC_GETRBUFSIZE) DdcGetReadBufferSizeCallback (XHDCP22_RX_HANDLER_DDC_ISWBUFEMPTY) DdcIsWriteBufferEmptyCallback (XHDCP22_RX_HANDLER_DDC_ISRBUFEMPTY) DdcIsReadBufferEmptyCallback (XHDCP22_RX_HANDLER_DDC_CLEARRBUF) DdcClearReadBufferCallback (XHDCP22_RX_HANDLER_DDC_CLEARWBUF) DdcClearWriteBufferCallback (XHDCP22_RX_HANDLER_AUTHENTICATED) AuthenticatedCallback (XHDCP22_RX_HANDLER_UNAUTHENTICATED) UnauthenticatedCallback (XHDCP22_RX_HANDLER_AUTHENTICATION_REQUEST) AuthenticationRequestCallback (XHDCP22_RX_HANDLER_STREAM_MANAGE_REQUEST) StreamManageRequestCallback (XHDCP22_RX_HANDLER_TOPOLOGY_UPDATE) TopologyUpdateCallback InstancePtr is a pointer to the HDMI RX core instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XHdcp22_Rx_Dp_Handles::AuthenticatedCallback, XHdcp22_Rx_Dp_Handles::AuthenticatedCallbackRef, XHdcp22_Rx_Dp_Handles::AuthenticationRequestCallback, XHdcp22_Rx_Dp_Handles::AuthenticationRequestCallbackRef, XHdcp22_Rx_Dp_Handles::DdcClearReadBufferCallback, XHdcp22_Rx_Dp_Handles::DdcClearReadBufferCallbackRef, XHdcp22_Rx_Dp_Handles::DdcClearWriteBufferCallback, XHdcp22_Rx_Dp_Handles::DdcClearWriteBufferCallbackRef, XHdcp22_Rx_Dp_Handles::DdcGetDataCallback, XHdcp22_Rx_Dp_Handles::DdcGetDataCallbackRef, XHdcp22_Rx_Dp_Handles::DdcGetReadBufferSizeCallback, XHdcp22_Rx_Dp_Handles::DdcGetReadBufferSizeCallbackRef, XHdcp22_Rx_Dp_Handles::DdcGetWriteBufferSizeCallback, XHdcp22_Rx_Dp_Handles::DdcGetWriteBufferSizeCallbackRef, XHdcp22_Rx_Dp_Handles::DdcIsReadBufferEmptyCallback, XHdcp22_Rx_Dp_Handles::DdcIsReadBufferEmptyCallbackRef, XHdcp22_Rx_Dp_Handles::DdcIsWriteBufferEmptyCallback, XHdcp22_Rx_Dp_Handles::DdcIsWriteBufferEmptyCallbackRef, XHdcp22_Rx_Dp_Handles::DdcSetAddressCallback, XHdcp22_Rx_Dp_Handles::DdcSetAddressCallbackRef, XHdcp22_Rx_Dp_Handles::DdcSetDataCallback, XHdcp22_Rx_Dp_Handles::DdcSetDataCallbackRef, XHdcp22_Rx_Dp_Handles::EncryptionStatusCallback, XHdcp22_Rx_Dp_Handles::EncryptionStatusCallbackRef, XHdcp22_Rx_Dp::Handles, XHdcp22_Rx_Dp_Handles::IsAuthenticatedCallbackSet, XHdcp22_Rx_Dp_Handles::IsAuthenticationRequestCallbackSet, XHdcp22_Rx_Dp_Handles::IsDdcAllCallbacksSet, XHdcp22_Rx_Dp_Handles::IsDdcClearReadBufferCallbackSet, XHdcp22_Rx_Dp_Handles::IsDdcClearWriteBufferCallbackSet, XHdcp22_Rx_Dp_Handles::IsDdcGetDataCallbackSet, XHdcp22_Rx_Dp_Handles::IsDdcGetReadBufferSizeCallbackRefSet, XHdcp22_Rx_Dp_Handles::IsDdcGetWriteBufferSizeCallbackSet, XHdcp22_Rx_Dp_Handles::IsDdcIsReadBufferEmptyCallbackSet, XHdcp22_Rx_Dp_Handles::IsDdcIsWriteBufferEmptyCallbackSet, XHdcp22_Rx_Dp_Handles::IsDdcSetAddressCallbackSet, XHdcp22_Rx_Dp_Handles::IsDdcSetDataCallbackSet, XHdcp22_Rx_Dp_Handles::IsEncryptionStatusCallbackSet, XHdcp22_Rx_Dp_Handles::IsRxDpAuxReadCallbackSet, XHdcp22_Rx_Dp_Handles::IsRxDpAuxWriteCallbackSet, XHdcp22_Rx_Dp_Handles::IsRxDpCpIrqSetCallbackSet, XHdcp22_Rx_Dp_Handles::IsSke_Send_EksCallbackSet, XHdcp22_Rx_Dp_Handles::IsStreamManageRequestCallbackSet, XHdcp22_Rx_Dp_Handles::IsTopologyUpdateCallbackSet, XHdcp22_Rx_Dp_Handles::IsUnauthenticatedCallbackSet, XHdcp22_Rx_Dp_Handles::RxDpAuxReadCallback, XHdcp22_Rx_Dp_Handles::RxDpAuxReadCallbackRef, XHdcp22_Rx_Dp_Handles::RxDpAuxWriteCallback, XHdcp22_Rx_Dp_Handles::RxDpAuxWriteCallbackRef, XHdcp22_Rx_Dp_Handles::RxDpCpIrqSetCallback, XHdcp22_Rx_Dp_Handles::RxDpCpIrqSetCallbackRef, XHdcp22_Rx_Dp_Handles::RxDpSetClearAuxDeferCallback, XHdcp22_Rx_Dp_Handles::RxDpSetClearAuxDeferCallbackRef, XHdcp22_Rx_Dp_Handles::Ske_Send_EksCallback, XHdcp22_Rx_Dp_Handles::Ske_Send_EksCallbackRef, XHdcp22_Rx_Dp_Handles::StreamManageRequestCallback, XHdcp22_Rx_Dp_Handles::StreamManageRequestCallbackRef, XHdcp22_Rx_Dp_Handles::TopologyUpdateCallback, XHdcp22_Rx_Dp_Handles::TopologyUpdateCallbackRef, XHdcp22_Rx_Dp_Handles::UnauthenticatedCallback, XHdcp22_Rx_Dp_Handles::UnauthenticatedCallbackRef, XHDCP22_RX_HANDLER_AUTHENTICATED, XHDCP22_RX_HANDLER_AUTHENTICATION_REQUEST, XHDCP22_RX_HANDLER_DDC_CLEARRBUF, XHDCP22_RX_HANDLER_DDC_CLEARWBUF, XHDCP22_RX_HANDLER_DDC_GETRBUFSIZE, XHDCP22_RX_HANDLER_DDC_GETREGDATA, XHDCP22_RX_HANDLER_DDC_GETWBUFSIZE, XHDCP22_RX_HANDLER_DDC_ISRBUFEMPTY, XHDCP22_RX_HANDLER_DDC_ISWBUFEMPTY, XHDCP22_RX_HANDLER_DDC_SETREGADDR, XHDCP22_RX_HANDLER_DDC_SETREGDATA, XHDCP22_RX_HANDLER_DP_AUX_DEFER_SET_CLR, XHDCP22_RX_HANDLER_DP_AUX_READ, XHDCP22_RX_HANDLER_DP_AUX_WRITE, XHDCP22_RX_HANDLER_DP_CP_IRQ_SET, XHDCP22_RX_HANDLER_ENCRYPTION_UPDATE, XHDCP22_RX_HANDLER_INVALID, XHDCP22_RX_HANDLER_SKE_SEND_EKS, XHDCP22_RX_HANDLER_STREAM_MANAGE_REQUEST, XHDCP22_RX_HANDLER_TOPOLOGY_UPDATE, XHDCP22_RX_HANDLER_UNAUTHENTICATED, XHDCP22_RX_HANDLER_UNDEFINED.
int XHdcp22Rx_Dp_Poll(XHdcp22_Rx_Dp *InstancePtr)
This function executes the HDCP22-RX state machine.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. None. State transitions are logged.
References XHdcp22_Rx_Dp_Info::AuthenticationStatus, XHdcp22_Rx_Dp_Info::CurrentState, XHdcp22_Rx_Dp::Info, XHdcp22_Rx_Dp_Info::IsEnabled, XHdcp22_Rx_Dp_Info::NextState, XHdcp22_Rx_Dp::StateFunc, XHDCP22_RX_LOG_EVT_INFO_STATE, XHdcp22Rx_Dp_LogWr.
u8 XHdcp22Rx_Dp_IsEnabled(XHdcp22_Rx_Dp *InstancePtr)
This function checks if the HDCP22-RX state machine is enabled.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. TRUE or FALSE. None.
References XHdcp22_Rx_Dp::Info, XHdcp22_Rx_Dp_Info::IsEnabled.
Referenced by XHdcp22Rx_Dp_Info.
u8 XHdcp22Rx_Dp_IsEncryptionEnabled(XHdcp22_Rx_Dp *InstancePtr)
This function checks if the HDCP22-RX cipher encryption is enabled.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. TRUE or FALSE. None.
References XHdcp22_Rx_Dp::CipherInst.
Referenced by XHdcp22Rx_Dp_Info.
u8 XHdcp22Rx_Dp_IsInProgress(XHdcp22_Rx_Dp *InstancePtr)
This function checks if the HDCP22-RX state machine is enabled but not yet in the Authenticated state.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. TRUE or FALSE. None.
References XHdcp22_Rx_Dp_Info::AuthenticationStatus, XHdcp22_Rx_Dp::Info, XHDCP22_RX_AUTHENTICATION_BUSY.
u8 XHdcp22Rx_Dp_IsAuthenticated(XHdcp22_Rx_Dp *InstancePtr)
This function checks if the HDCP22-RX state machine is in the Authenticated state.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. TRUE or FALSE. None.
References XHdcp22_Rx_Dp_Info::AuthenticationStatus, XHdcp22_Rx_Dp::Info, XHDCP22_RX_AUTHENTICATED.
u8 XHdcp22Rx_Dp_IsError(XHdcp22_Rx_Dp *InstancePtr)
This function checks if the HDCP22-RX state machine has detected an error condition.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. TRUE or FALSE. None.
References XHdcp22_Rx_Dp_Info::ErrorFlagSticky, XHdcp22_Rx_Dp::Info, XHDCP22_RX_ERROR_FLAG_NONE.
u8 XHdcp22Rx_Dp_IsRepeater(XHdcp22_Rx_Dp *InstancePtr)
This function returns the current repeater mode status.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. TRUE if the HDCP 2.2 instance is the upstream port of a repeaterFALSE if the HDCP 2.2 instance is a receiver
References XHdcp22_Rx_Dp::Config, XHdcp22_Rx_Dp_Config::Mode, XHDCP22_RX_RECEIVER.
Referenced by XHdcp22Rx_Dp_Info.
void XHdcp22Rx_Dp_SetRepeater(XHdcp22_Rx_Dp *InstancePtr, u8 Set)
This function sets the repeater mode status.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. Set is TRUE to enable repeater mode and FALSE to disable.
References XHdcp22_Rx_Dp::Config, XHdcp22_Rx_Dp_Config::Mode, XHdcp22_Rx_Dp::RxCaps, XHDCP22_RX_RECEIVER, XHDCP22_RX_REPEATER.
void XHdcp22Rx_Dp_SetLinkError(XHdcp22_Rx_Dp *InstancePtr)
This function is called when 50 consecutive data island ECC errors are detected indicating a link integrity problem.
The error flag is set indicating to the state machine that REAUTH_REQ bit in the RXSTATUS register be set. Setting this flag only takes effect when the authentication state machine is in the Authenticated state B4. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. This function can be registered as an asynchronous callback.
References XHdcp22_Rx_Dp_Info::ErrorFlag, XHdcp22_Rx_Dp::Info, XHdcp22_Rx_Dp_Info::LinkErrorCnt, XHDCP22_RX_ERROR_FLAG_LINK_INTEGRITY, XHDCP22_RX_LOG_EVT_ERROR, XHdcp22Rx_Dp_LogWr.
void XHdcp22Rx_Dp_SetDdcError(XHdcp22_Rx_Dp *InstancePtr)
This function is called when a DDC read/write burst stops prior to completing the expected message size.
This will cause the message buffers to be flushed and state machine reset. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. This function can be registered as an asynchronous callback.
References XHdcp22_Rx_Dp_Info::DdcErrorCnt, XHdcp22_Rx_Dp_Info::ErrorFlag, XHdcp22_Rx_Dp::Info, XHDCP22_RX_ERROR_FLAG_DDC_BURST, XHDCP22_RX_LOG_EVT_ERROR, XHdcp22Rx_Dp_LogWr.
void XHdcp22Rx_Dp_SetWriteMessageAvailable(XHdcp22_Rx_Dp *InstancePtr)
This function is called when a complete message is available in the write message buffer.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. This function can be registered as an asynchronous callback.
References XHdcp22_Rx_Dp_Info::DdcFlag, XHdcp22_Rx_Dp::Info, XHDCP22_RX_DDC_FLAG_WRITE_MESSAGE_READY, XHDCP22_RX_LOG_DEBUG_WRITE_MESSAGE_AVAILABLE, XHDCP22_RX_LOG_EVT_DEBUG, XHdcp22Rx_Dp_LogWr.
void XHdcp22Rx_Dp_SetReadMessageComplete(XHdcp22_Rx_Dp *InstancePtr)
This function is called when a message has been read out of the read message buffer.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. This function can be registered as an asynchronous callback.
References XHdcp22_Rx_Dp_Info::DdcFlag, XHdcp22_Rx_Dp::Info, XHDCP22_RX_DDC_FLAG_READ_MESSAGE_READY, XHDCP22_RX_LOG_DEBUG_READ_MESSAGE_COMPLETE, XHDCP22_RX_LOG_EVT_DEBUG, XHdcp22Rx_Dp_LogWr.
void XHdcp22Rx_Dp_LoadLc128(XHdcp22_Rx_Dp *InstancePtr, const u8 *Lc128Ptr)
This function is used to load the Lc128 value by copying the contents of the array referenced by Lc128Ptr into the cipher.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. Lc128Ptr is a pointer to an array. None.
References XHdcp22_Rx_Dp::CipherInst.
void XHdcp22Rx_Dp_LoadPublicCert(XHdcp22_Rx_Dp *InstancePtr, const u8 *PublicCertPtr)
This function is used to load the public certificate.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. PublicCertPtr is a pointer to an array. None.
References XHdcp22_Rx_Dp::PublicCertPtr.
int XHdcp22Rx_Dp_LoadPrivateKey(XHdcp22_Rx_Dp *InstancePtr, const u8 *PrivateKeyPtr)
This function is used to load the private key.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. PrivateKeyPtr is a pointer to an array. - XST_SUCCESS if MMULT keys are calculated correctly. XST_FAILURE if MMULT keys are not calculated correctly. None.
References XHdcp22_Rx_Dp::NPrimeP, XHdcp22_Rx_Dp::NPrimeQ, XHdcp22_Rx_Dp::PrivateKeyPtr, XHdcp22Rx_CalcMontNPrime.
u32 XHdcp22Rx_Dp_GetVersion(XHdcp22_Rx_Dp *InstancePtr)
This function reads the version.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. Returns the version register of the cipher. None.
References XHdcp22_Rx_Dp::CipherInst.
XTmrCtr * XHdcp22Rx_Dp_GetTimer(XHdcp22_Rx_Dp *InstancePtr)
This function returns the pointer to the internal timer control instance needed for connecting the timer interrupt to an interrupt controller.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. A pointer to the internal timer control instance. None.
References XHdcp22_Rx_Dp::TimerInst.
void XHdcp22Rx_Dp_SetTopology(XHdcp22_Rx_Dp *InstancePtr, const XHdcp22_Rx_Dp_Topology *TopologyPtr)
This function copies a complete repeater topology table into the instance repeater topology table.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. TopologyPtr is a pointer to the repeater topology table. None.
References XHdcp22_Rx_Dp::Topology.
void XHdcp22Rx_Dp_SetTopologyReceiverIdList(XHdcp22_Rx_Dp *InstancePtr, const u8 *ListPtr, u32 ListSize)
This function copies the RECEIVER_ID_LIST into the repeater topology table.
Receiver ID list is constructed by appending Receiver IDs in big-endian order. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. ListPtr is a pointer to the Receiver ID list. The list consists of a contiguous set of bytes stored in big-endian order, with each Receiver ID occuping five bytes with a maximum of 31 Receiver IDs. ListSize is the number of Receiver IDs in the list. The list size cannot exceed 31 devices. None.
References XHdcp22_Rx_Dp_Topology::ReceiverIdList, XHdcp22_Rx_Dp::Topology.
void XHdcp22Rx_Dp_SetTopologyField(XHdcp22_Rx_Dp *InstancePtr, XHdcp22_Rx_Dp_TopologyField Field, u8 Value)
This function is used to set various fields inside the topology structure.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. Field indicates what field of the topology structure to update. Value is the value assigned to the field of the topology structure. None.
void XHdcp22Rx_Dp_SetTopologyUpdate(XHdcp22_Rx_Dp *InstancePtr)
This function is used to indicate that the topology table has been updated and is ready for upstream propagation.
Before calling this function ensure that all the fields in the repeater topology table have been updated. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. None.
References XHdcp22_Rx_Dp::Info, XHdcp22_Rx_Dp_Info::IsTopologyValid, XHDCP22_RX_LOG_EVT_INFO, XHDCP22_RX_LOG_INFO_TOPOLOGY_UPDATE, XHdcp22Rx_Dp_LogWr.
u8 XHdcp22Rx_Dp_GetContentStreamType(XHdcp22_Rx_Dp *InstancePtr)
This function is gets the type information received from the RepeaterAuth_Stream_Manage message for downstream propagation of management information.
This function should be called only after the RepeaterAuth_Stream_Manage message has been received, and can be called inside the user callback function type XHDCP22_RX_HANDLER_STREAM_MANAGE_REQUEST. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. - 0x00: Type 0 Content Stream. May be transmitted by the HDCP Repeater to all HDCP Devices. 0x01: Type 1 Content Stream. Must not be transmitted by the HDCP Repeater to HDCP 1.x-compliant Devices and HDCP 2.1-compliant Devices.0x02-0xFF: Reserved for future use only. Content Streams with reserved Type values must be treated similar to Type 1 Content Streams. None.
References XHdcp22_Rx_Dp::Params.
Referenced by XHdcp22Rx_Dp_Info.
void XHdcp22Rx_Dp_TimerHandler(void *CallbackRef, u8 TmrCntNumber)
This function handles timer interrupts.
CallbackRef refers to a XHdcp22_Rx_Dp structure TmrCntNumber the number of used timer. For DP design this handler will be called from DpRxSs timer interrupt handler so it should be a public function.
References XHdcp22_Rx_Dp::Info, XHdcp22_Rx_Dp::IsReady, XHdcp22_Rx_Dp_Info::TimerExpired, XHDCP22_RX_LOG_DEBUG_TIMER_EXPIRED, XHDCP22_RX_LOG_EVT_DEBUG, XHdcp22Rx_Dp_LogWr.
void XHdcp22Rx_Dp_LogReset(XHdcp22_Rx_Dp *InstancePtr, u8 Verbose)
This function clears the log pointers.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. Verbose allows to add debug logging. None.
References XHdcp22_Rx_Dp_Log::Head, XHdcp22_Rx_Dp::Log, XHdcp22_Rx_Dp_Log::Tail, XHdcp22_Rx_Dp::TimerInst, XHdcp22_Rx_Dp_Log::Verbose.
Referenced by XHdcp22Rx_Dp_CfgInitialize.
u32 XHdcp22Rx_Dp_LogGetTimeUSecs(XHdcp22_Rx_Dp *InstancePtr)
This function returns the time expired since a log reset was called.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. The expired logging time in useconds. None.
References XHdcp22_Rx_Dp::TimerInst.
Referenced by XHdcp22Rx_Dp_LogWr.
void XHdcp22Rx_Dp_LogWr(XHdcp22_Rx_Dp *InstancePtr, u16 Evt, u16 Data)
This function writes HDCP22-RX log event into buffer.
If the log event is of type error, the sticky error flag is set. The sticky error flag is used to keep history of error conditions. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. Evt specifies an action to be carried out. Data specifies the information that gets written into log buffer. None.
References XHdcp22_Rx_Dp_LogItem::Data, XHdcp22_Rx_Dp_Info::ErrorFlagSticky, XHdcp22_Rx_Dp_Log::Head, XHdcp22_Rx_Dp::Info, XHdcp22_Rx_Dp::Log, XHdcp22_Rx_Dp_LogItem::LogEvent, XHdcp22_Rx_Dp_Log::LogItems, XHdcp22_Rx_Dp_Log::Tail, XHdcp22_Rx_Dp_LogItem::TimeStamp, XHdcp22_Rx_Dp_Log::Verbose, XHDCP22_RX_LOG_BUFFER_SIZE, XHDCP22_RX_LOG_EVT_DEBUG, XHDCP22_RX_LOG_EVT_ERROR, XHDCP22_RX_LOG_EVT_INFO_MESSAGE, XHDCP22_RX_LOG_EVT_INVALID, XHdcp22Rx_Dp_LogGetTimeUSecs.
Referenced by XHdcp22Rx_Dp_Disable, XHdcp22Rx_Dp_Enable, XHdcp22Rx_Dp_Poll, XHdcp22Rx_Dp_Reset, XHdcp22Rx_Dp_SetDdcError, XHdcp22Rx_Dp_SetDpcdMsgRdWrtAvailable, XHdcp22Rx_Dp_SetLinkError, XHdcp22Rx_Dp_SetReadMessageComplete, XHdcp22Rx_Dp_SetTopologyUpdate, XHdcp22Rx_Dp_SetWriteMessageAvailable, XHdcp22Rx_Dp_TimerHandler, XHdcp22Rx_RsaesOaepDecrypt.
XHdcp22_Rx_Dp_LogItem * XHdcp22Rx_Dp_LogRd(XHdcp22_Rx_Dp *InstancePtr)
This function provides the log information from the log buffer.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. Content of log buffer if log pointers are not equal.Otherwise Zero. None.
References XHdcp22_Rx_Dp_LogItem::Data, XHdcp22_Rx_Dp_Log::Head, XHdcp22_Rx_Dp::Log, XHdcp22_Rx_Dp_LogItem::LogEvent, XHdcp22_Rx_Dp_Log::LogItems, XHdcp22_Rx_Dp_Log::Tail, XHdcp22_Rx_Dp_LogItem::TimeStamp, XHDCP22_RX_LOG_BUFFER_SIZE.
Referenced by XHdcp22Rx_Dp_LogDisplay.
void XHdcp22Rx_Dp_LogDisplay(XHdcp22_Rx_Dp *InstancePtr)
This function prints the contents of the log buffer.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. None.
References XHdcp22_Rx_Dp_LogItem::Data, XHdcp22_Rx_Dp_LogItem::LogEvent, XHdcp22_Rx_Dp_LogItem::TimeStamp, XHDCP22_RX_ERROR_FLAG_DDC_BURST, XHDCP22_RX_ERROR_FLAG_EMPTY_REPEATER_TOPOLOGY, XHDCP22_RX_ERROR_FLAG_FORCE_RESET, XHDCP22_RX_ERROR_FLAG_LINK_INTEGRITY, XHDCP22_RX_ERROR_FLAG_MAX_LCINIT_ATTEMPTS, XHDCP22_RX_ERROR_FLAG_MAX_REPEATER_TOPOLOGY, XHDCP22_RX_ERROR_FLAG_MESSAGE_SIZE, XHDCP22_RX_ERROR_FLAG_PROCESSING_AKEINIT, XHDCP22_RX_ERROR_FLAG_PROCESSING_AKENOSTOREDKM, XHDCP22_RX_ERROR_FLAG_PROCESSING_AKESTOREDKM, XHDCP22_RX_ERROR_FLAG_PROCESSING_LCINIT, XHDCP22_RX_ERROR_FLAG_PROCESSING_REPEATERAUTHSENDACK, XHDCP22_RX_ERROR_FLAG_PROCESSING_REPEATERAUTHSTREAMMANAGE, XHDCP22_RX_ERROR_FLAG_PROCESSING_SKESENDEKS, XHDCP22_RX_LOG_DEBUG_COMPUTE_EKH, XHDCP22_RX_LOG_DEBUG_COMPUTE_EKH_DONE, XHDCP22_RX_LOG_DEBUG_COMPUTE_HPRIME, XHDCP22_RX_LOG_DEBUG_COMPUTE_HPRIME_DONE, XHDCP22_RX_LOG_DEBUG_COMPUTE_KM, XHDCP22_RX_LOG_DEBUG_COMPUTE_KM_DONE, XHDCP22_RX_LOG_DEBUG_COMPUTE_KS, XHDCP22_RX_LOG_DEBUG_COMPUTE_KS_DONE, XHDCP22_RX_LOG_DEBUG_COMPUTE_LPRIME, XHDCP22_RX_LOG_DEBUG_COMPUTE_LPRIME_DONE, XHDCP22_RX_LOG_DEBUG_COMPUTE_MPRIME, XHDCP22_RX_LOG_DEBUG_COMPUTE_MPRIME_DONE, XHDCP22_RX_LOG_DEBUG_COMPUTE_RSA, XHDCP22_RX_LOG_DEBUG_COMPUTE_RSA_DONE, XHDCP22_RX_LOG_DEBUG_COMPUTE_VPRIME, XHDCP22_RX_LOG_DEBUG_COMPUTE_VPRIME_DONE, XHDCP22_RX_LOG_DEBUG_READ_MESSAGE_COMPLETE, XHDCP22_RX_LOG_DEBUG_TIMER_EXPIRED, XHDCP22_RX_LOG_DEBUG_TIMER_START, XHDCP22_RX_LOG_DEBUG_WRITE_MESSAGE_AVAILABLE, XHDCP22_RX_LOG_EVT_DEBUG, XHDCP22_RX_LOG_EVT_ERROR, XHDCP22_RX_LOG_EVT_INFO, XHDCP22_RX_LOG_EVT_INFO_MESSAGE, XHDCP22_RX_LOG_EVT_INFO_STATE, XHDCP22_RX_LOG_EVT_USER, XHDCP22_RX_LOG_INFO_DISABLE, XHDCP22_RX_LOG_INFO_ENABLE, XHDCP22_RX_LOG_INFO_ENCRYPTION_ENABLE, XHDCP22_RX_LOG_INFO_REQAUTH_REQ, XHDCP22_RX_LOG_INFO_RESET, XHDCP22_RX_LOG_INFO_TOPOLOGY_UPDATE, XHDCP22_RX_MSG_ID_AKEINIT, XHDCP22_RX_MSG_ID_AKENOSTOREDKM, XHDCP22_RX_MSG_ID_AKESENDCERT, XHDCP22_RX_MSG_ID_AKESENDHPRIME, XHDCP22_RX_MSG_ID_AKESENDPAIRINGINFO, XHDCP22_RX_MSG_ID_AKESTOREDKM, XHDCP22_RX_MSG_ID_LCINIT, XHDCP22_RX_MSG_ID_LCSENDLPRIME, XHDCP22_RX_MSG_ID_REPEATERAUTHSENDACK, XHDCP22_RX_MSG_ID_REPEATERAUTHSENDRXIDLIST, XHDCP22_RX_MSG_ID_REPEATERAUTHSTREAMMANAGE, XHDCP22_RX_MSG_ID_REPEATERAUTHSTREAMREADY, XHDCP22_RX_MSG_ID_SKESENDEKS, XHDCP22_RX_STATE_B0_WAIT_AKEINIT, XHDCP22_RX_STATE_B1_SEND_AKESENDCERT, XHDCP22_RX_STATE_B1_SEND_AKESENDHPRIME, XHDCP22_RX_STATE_B1_SEND_AKESENDPAIRINGINFO, XHDCP22_RX_STATE_B1_WAIT_AKEKM, XHDCP22_RX_STATE_B1_WAIT_LCINIT, XHDCP22_RX_STATE_B2_SEND_LCSENDLPRIME, XHDCP22_RX_STATE_B2_WAIT_SKESENDEKS, XHDCP22_RX_STATE_B3_COMPUTE_KS, XHDCP22_RX_STATE_B4_AUTHENTICATED, XHDCP22_RX_STATE_C4_WAIT_FOR_DOWNSTREAM, XHDCP22_RX_STATE_C5_SEND_RECEIVERIDLIST, XHDCP22_RX_STATE_C5_SEND_RECEIVERIDLIST_DONE, XHDCP22_RX_STATE_C6_VERIFY_RECEIVERIDLISTACK, XHDCP22_RX_STATE_C7_SEND_STREAM_READY, XHDCP22_RX_STATE_C7_SEND_STREAM_READY_DONE, XHDCP22_RX_STATE_C7_WAIT_STREAM_MANAGEMENT, XHDCP22_RX_STATE_C8_AUTHENTICATED, XHdcp22Rx_Dp_LogRd.
void XHdcp22Rx_Dp_Info(XHdcp22_Rx_Dp *InstancePtr)
This function prints the state machine information.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. None.
References XHdcp22_Rx_Dp_Info::AuthenticationStatus, XHdcp22_Rx_Dp_Info::AuthRequestCnt, XHdcp22_Rx_Dp_Info::DdcErrorCnt, XHdcp22_Rx_Dp_Topology::Depth, XHdcp22_Rx_Dp_Topology::DeviceCnt, XHdcp22_Rx_Dp_Topology::Hdcp1DeviceDownstream, XHdcp22_Rx_Dp_Topology::Hdcp2LegacyDeviceDownstream, XHdcp22_Rx_Dp::Info, XHdcp22_Rx_Dp_Info::LinkErrorCnt, XHdcp22_Rx_Dp_Topology::MaxCascadeExceeded, XHdcp22_Rx_Dp_Topology::MaxDevsExceeded, XHdcp22_Rx_Dp_Info::ReauthRequestCnt, XHdcp22_Rx_Dp::Topology, XHDCP22_RX_AUTHENTICATED, XHDCP22_RX_AUTHENTICATION_BUSY, XHDCP22_RX_REAUTHENTICATE_REQUESTED, XHDCP22_RX_UNAUTHENTICATED, XHdcp22Rx_Dp_GetContentStreamType, XHdcp22Rx_Dp_IsEnabled, XHdcp22Rx_Dp_IsEncryptionEnabled, XHdcp22Rx_Dp_IsRepeater.
void XHdcp22Rx_Dp_SetDpcdMsgRdWrtAvailable(XHdcp22_Rx_Dp *InstancePtr, u32 type)
This function is to set the DPCD flag if any DPCD read/write interrupts occurred.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. type is the type of interrupt
References XHdcp22_Rx_Dp_Info::DpcdFlag, XHdcp22_Rx_Dp::Info, XHDCP22_RX_DPCD_FLAG_AKE_INIT_RCVD, XHDCP22_RX_LOG_DEBUG_WRITE_MESSAGE_AVAILABLE, XHDCP22_RX_LOG_EVT_DEBUG, XHdcp22Rx_Dp_LogWr.
void XHdcp22Rx_Dp_SetHdcp22OverProtocol(XHdcp22_Rx_Dp *InstancePtr, XHdcp22_Rx_Dp_Protocol protocol)
This function is to set the protocol (HDMI/DP) over which HDCP22 is happening.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. protocol is the protocol HDMI/DP.
References XHdcp22_Rx_Dp::Config, XHdcp22_Rx_Dp_Config::Protocol.
void XHdcp22_Dp_timer_attach(XHdcp22_Rx_Dp *InstancePtr, XTmrCtr *TmrCtrPtr)
This function is to attach the HDCP22 timer instance to DP RX subsystem's timer.
For the DP design the timer is being used from the DP subsystem. So the HDCP22 timer instance will be attached in DpSs initialization. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. TmrCtrPtr is the DpRx subsystem's timer instance.
References XHdcp22_Rx_Dp::TimerInst.
void XHdcp22_Dp_RxSetLaneCount(XHdcp22_Rx_Dp *InstancePtr, u8 LaneCount)
This function set the lane count of an hdcp22 interface.
InstancePtr is the receiver instance. LaneCount is the number of lanes of the interface. None.
References XHdcp22_Rx_Dp::CipherInst.
u32 XHdcp22_Dp_RxSetRxCaps(XHdcp22_Rx_Dp *InstancePtr, u8 enable)
This function sets the Rx_Caps in DPCD.
InstancePtr is the receiver instance. enable is to set or clear Rx_Caps. XST_SUCCESS or XST_FAILURE. None.
References XHdcp22_Rx_Dp::Handles, XHdcp22_Rx_Dp::RxCaps, XHdcp22_Rx_Dp_Handles::RxDpAuxWriteCallback, XHdcp22_Rx_Dp_Handles::RxDpAuxWriteCallbackRef.
void XHdcp22_Dp_RxSetStreamType(XHdcp22_Rx_Dp *InstancePtr)
This function sets Stream Type.
InstancePtr is the receiver instance. None.
References XHdcp22_Rx_Dp::CipherInst, XHdcp22_Rx_Dp::Handles, XHdcp22_Rx_Dp::Params, XHdcp22_Rx_Dp_Handles::RxDpAuxReadCallback, XHdcp22_Rx_Dp_Handles::RxDpAuxReadCallbackRef.
void XHdcp22_Dp_RxSetReauthReq(XHdcp22_Rx_Dp *InstancePtr)
This function sets Reauth Request for upstream device.
InstancePtr is the receiver instance. None.