xhdcp22_rx_dp.h
XHDCP22_RX_H
XHDCP22_RX_MAX_MESSAGE_SIZE
Maximum message size.
XHDCP22_RX_LOG_BUFFER_SIZE
The size of the log buffer.
Referenced by XHdcp22Rx_Dp_LogRd, XHdcp22Rx_Dp_LogWr.
XHDCP22_RX_ENCRYPTION_STATUS_INTERVAL
1sec encryption status check interval
XHDCP22_RX_REPEATERAUTH_ACK_INTERVAL
2sec RepeaterAuth Ack interval
R_TX_OFFSET
R_TX_SIZE
TX_CAPS_OFFSET
TX_CAPS_SIZE
CERT_RX_OFFSET
CERT_RX_SIZE
R_RX_OFFSET
R_RX_SIZE
RX_CAPS_OFFSET
RX_CAPS_SIZE
E_KPUB_KM_OFFSET
E_KPUB_KM_SIZE
E_KH_KM_OFFSET
E_KH_KM_SIZE
M_OFFSET
M_SIZE
H_PRIME_OFFSET
H_PRIME_SIZE
E_KH_KM_PAIRING_OFFSET
E_KH_KM_PAIRING_SIZE
R_N_OFFSET
R_N_SIZE
L_PRIME_OFFSET
L_PRIME_SIZE
E_DKEY_KS_OFFSET
E_DKEY_KS_SIZE
R_IV_OFFSET
R_IV_SIZE
RX_INFO_OFFSET
RX_INFO_SIZE
SEQ_NUM_V_OFFSET
SEQ_NUM_V_SIZE
V_PRIME_OFFSET
V_PRIME_SIZE
RCVID_LIST_OFFSET
RCVID_LIST_SIZE
V_OFFSET
V_SIZE
SEQ_NUM_M_OFFSET
SEQ_NUM_M_SIZE
K_OFFSET
K_SIZE
STREAMID_TYPE_OFFSET
STREAMID_TYPE_SIZE
M_PRIME_OFFSET
M_PRIME_SIZE
RX_STATUS_OFFSET
RX_STREAM_TYPE_OFFSET
Rx_STREAM_TYPE_SIZE
RX_STATUS_REPEATER_READY_AVAILABLE
RX_STATUS_H_PRIME_AVAILABLE
RX_STATUS_PAIRING_AVAILABLE
RX_STATUS_REAUTH_REQ
RX_STATUS_LINK_INTEGRITY_FAILURE
XHDCP22_RXCAPS_HDCP_ENABLE
XHDCP22_RXCAPS_REPEATER
XHdcp22_Rx_Dp_Protocol
HDCP22 over DP.
XHdcp22_Rx_Dp_Mode
HDCP22 receiver.
XHdcp22_Rx_Dp_HandlerType
Undefined.
XHdcp22_Rx_Dp_StateType
Undefined.
XHdcp22_Rx_Dp_AuthenticationType
Unauthenticated.
XHdcp22_Rx_Dp_LogEvt
XHdcp22_Rx_Dp_TopologyField
typedef void*(* XHdcp22_Rx_StateFunc)(void *InstancePtr))(void *InstancePtr)
Type for pointer to state function.
typedef void(* XHdcp22_Rx_RunHandler)(void *HandlerRef))(void *HandlerRef)
Type for pointer to single input function.
typedef void(* XHdcp22_Rx_SetHandler)(void *HandlerRef, u32 Data))(void *HandlerRef, u32 Data)
Type for pointer to two input function.
typedef u32(* XHdcp22_Rx_GetHandler)(void *HandlerRef))(void *HandlerRef)
Type for pointer to single input function with a return value.
typedef u32(* Xhdcp22_Rx_RdWrHandler)(void *HandlerRef, u32 offset, u8 *buf, u32 size))(void *HandlerRef, u32 offset, u8 *buf, u32 size)
Type for pointer to four input function with a return value.
XHdcp22_Rx_Dp_Config * XHdcp22Rx_Dp_LookupConfig(UINTPTR BaseAddress)
This function returns a reference to an XHdcp22_Rx_Dp_Config structure based on the core id, DeviceId.
The return value will refer to an entry in the device configuration table defined in the xhdcp22_rx_g.c file. DeviceId is the unique core ID of the HDCP RX core for the lookup operation. XHdcp22Rx_Dp_LookupConfig returns a reference to a config record in the configuration table (in xhdmi_tx_g.c) corresponding to DeviceId, or NULL if no match is found. None.
int XHdcp22Rx_Dp_CfgInitialize(XHdcp22_Rx_Dp *InstancePtr, XHdcp22_Rx_Dp_Config *ConfigPtr, UINTPTR EffectiveAddr)
Initialize the instance provided by the caller based on the given configuration data.
InstancePtr is a pointer to an XHdcp22_Rx_Dp instance. The memory the pointer references must be pre-allocated by the caller. Further calls to manipulate the driver through the HDCP22-RX API must be made with this pointer. ConfigPtr is a reference to a structure containing information about a specific HDCP22-RX device. This function initializes an InstancePtr object for a specific device specified by the contents of Config. This function can initialize multiple instance objects with the use of multiple calls giving different Config information on each call. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS or XST_FAILURE. None.
References XHdcp22_Rx_Dp_Handles::AuthenticatedCallback, XHdcp22_Rx_Dp_Handles::AuthenticationRequestCallback, XHdcp22_Rx_Dp_Info::AuthenticationStatus, XHdcp22_Rx_Dp_Info::AuthRequestCnt, XHdcp22_Rx_Dp_Config::BaseAddress, XHdcp22_Rx_Dp::Config, XHdcp22_Rx_Dp_Info::CurrentState, XHdcp22_Rx_Dp_Handles::DdcClearReadBufferCallback, XHdcp22_Rx_Dp_Handles::DdcClearWriteBufferCallback, XHdcp22_Rx_Dp_Info::DdcErrorCnt, XHdcp22_Rx_Dp_Handles::DdcGetDataCallback, XHdcp22_Rx_Dp_Handles::DdcGetReadBufferSizeCallback, XHdcp22_Rx_Dp_Handles::DdcGetWriteBufferSizeCallback, XHdcp22_Rx_Dp_Handles::DdcIsReadBufferEmptyCallback, XHdcp22_Rx_Dp_Handles::DdcIsWriteBufferEmptyCallback, XHdcp22_Rx_Dp_Handles::DdcSetAddressCallback, XHdcp22_Rx_Dp_Handles::DdcSetDataCallback, XHdcp22_Rx_Dp_Info::ErrorFlag, XHdcp22_Rx_Dp_Info::ErrorFlagSticky, XHdcp22_Rx_Dp::Handles, XHdcp22_Rx_Dp_Info::HasStreamManagementInfo, XHdcp22_Rx_Dp::Info, XHdcp22_Rx_Dp_Handles::IsAuthenticatedCallbackSet, XHdcp22_Rx_Dp_Handles::IsAuthenticationRequestCallbackSet, XHdcp22_Rx_Dp_Handles::IsDdcAllCallbacksSet, XHdcp22_Rx_Dp_Handles::IsDdcClearReadBufferCallbackSet, XHdcp22_Rx_Dp_Handles::IsDdcClearWriteBufferCallbackSet, XHdcp22_Rx_Dp_Handles::IsDdcGetDataCallbackSet, XHdcp22_Rx_Dp_Handles::IsDdcGetReadBufferSizeCallbackRefSet, XHdcp22_Rx_Dp_Handles::IsDdcGetWriteBufferSizeCallbackSet, XHdcp22_Rx_Dp_Handles::IsDdcIsReadBufferEmptyCallbackSet, XHdcp22_Rx_Dp_Handles::IsDdcIsWriteBufferEmptyCallbackSet, XHdcp22_Rx_Dp_Handles::IsDdcSetAddressCallbackSet, XHdcp22_Rx_Dp_Handles::IsDdcSetDataCallbackSet, XHdcp22_Rx_Dp_Info::IsEnabled, XHdcp22_Rx_Dp_Info::IsEncrypted, XHdcp22_Rx_Dp_Info::IsNoStoredKm, XHdcp22_Rx_Dp::IsReady, XHdcp22_Rx_Dp_Handles::IsRxDpAuxReadCallbackSet, XHdcp22_Rx_Dp_Handles::IsRxDpAuxWriteCallbackSet, XHdcp22_Rx_Dp_Handles::IsRxDpCpIrqSetCallbackSet, XHdcp22_Rx_Dp_Handles::IsRxDpSetClearAuxDeferCallbackSet, XHdcp22_Rx_Dp_Handles::IsSke_Send_EksCallbackSet, XHdcp22_Rx_Dp_Handles::IsStreamManageRequestCallbackSet, XHdcp22_Rx_Dp_Handles::IsTopologyUpdateCallbackSet, XHdcp22_Rx_Dp_Info::IsTopologyValid, XHdcp22_Rx_Dp_Info::LCInitAttempts, XHdcp22_Rx_Dp_Info::LinkErrorCnt, XHdcp22_Rx_Dp_Config::Mode, XHdcp22_Rx_Dp_Info::NextState, XHdcp22_Rx_Dp_Info::ReauthReq, XHdcp22_Rx_Dp_Info::ReauthRequestCnt, XHdcp22_Rx_Dp_Info::ReturnState, XHdcp22_Rx_Dp::RxCaps, XHdcp22_Rx_Dp_Handles::RxDpAuxReadCallback, XHdcp22_Rx_Dp_Handles::RxDpAuxWriteCallback, XHdcp22_Rx_Dp_Handles::RxDpCpIrqSetCallback, XHdcp22_Rx_Dp_Handles::RxDpSetClearAuxDeferCallback, XHdcp22_Rx_Dp_Info::SeqNumV, XHdcp22_Rx_Dp_Handles::Ske_Send_EksCallback, XHdcp22_Rx_Dp_Info::SkipRead, XHdcp22_Rx_Dp::StateFunc, XHdcp22_Rx_Dp_Handles::StreamManageRequestCallback, XHdcp22_Rx_Dp_Info::TopologyReady, XHdcp22_Rx_Dp_Handles::TopologyUpdateCallback, XHDCP22_RX_ERROR_FLAG_NONE, XHDCP22_RX_RECEIVER, XHDCP22_RX_STATE_B0_WAIT_AKEINIT, XHDCP22_RX_STATE_UNDEFINED, XHDCP22_RX_UNAUTHENTICATED, XHdcp22Rx_Dp_LogReset.
int XHdcp22Rx_Dp_Enable(XHdcp22_Rx_Dp *InstancePtr)
This function enables the HDCP22-RX state machine.
The HDCP2Version register is set to active. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. XST_SUCCESS or XST_FAILURE. Before enabling the state machine ensure that the instance has been initialized, DDC message handles have been assigned, and keys have been loaded.
References XHdcp22_Rx_Dp::CipherInst, XHdcp22_Rx_Dp::Config, XHdcp22_Rx_Dp::Handles, XHdcp22_Rx_Dp::Info, XHdcp22_Rx_Dp_Handles::IsDdcAllCallbacksSet, XHdcp22_Rx_Dp_Info::IsEnabled, XHdcp22_Rx_Dp::IsReady, XHdcp22_Rx_Dp::MmultInst, XHdcp22_Rx_Dp::PrivateKeyPtr, XHdcp22_Rx_Dp_Config::Protocol, XHdcp22_Rx_Dp::PublicCertPtr, XHdcp22_Rx_Dp::RngInst, XHdcp22_Rx_Dp::TimerInst, XHDCP22_RX_DP, XHDCP22_RX_LOG_EVT_INFO, XHDCP22_RX_LOG_INFO_ENABLE, XHdcp22Rx_Dp_LogWr.
int XHdcp22Rx_Dp_Disable(XHdcp22_Rx_Dp *InstancePtr)
This function disables the HDCP22-RX state machine.
The HDCP2Version register is cleared, and the ReauthReq bit is set in the RxStatus register to allow the transmitter to recover when it has already authenticated. Without setting the ReauthReq bit the transmitter will not know that HDCP 2.2 protocol has been disabled by the Receiver after it has already authenticated. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. XST_SUCCESS or XST_FAILURE. The HDCP22-RX cipher is disabled.
References XHdcp22_Rx_Dp_Info::AuthenticationStatus, XHdcp22_Rx_Dp::CipherInst, XHdcp22_Rx_Dp::Info, XHdcp22_Rx_Dp_Info::IsEnabled, XHdcp22_Rx_Dp::RngInst, XHDCP22_RX_AUTHENTICATED, XHDCP22_RX_LOG_EVT_INFO, XHDCP22_RX_LOG_INFO_DISABLE, XHdcp22Rx_Dp_LogWr.
int XHdcp22Rx_Dp_Reset(XHdcp22_Rx_Dp *InstancePtr)
This function resets the HDCP22-RX system to the default state.
The HDCP22-RX DDC registers are set to their default value and the message buffer is reset. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. XST_SUCCESS or XST_FAILURE. The DDC message handles must be assigned by the XHdcp22Rx_SetDdcHandles function prior to calling this reset function.
References XHdcp22_Rx_Dp_Info::AuthenticationStatus, XHdcp22_Rx_Dp_Info::AuthRequestCnt, XHdcp22_Rx_Dp::CipherInst, XHdcp22_Rx_Dp::Config, XHdcp22_Rx_Dp_Info::CurrentState, XHdcp22_Rx_Dp_Info::DdcErrorCnt, XHdcp22_Rx_Dp_Info::ErrorFlag, XHdcp22_Rx_Dp_Info::ErrorFlagSticky, XHdcp22_Rx_Dp::Handles, XHdcp22_Rx_Dp_Info::HasStreamManagementInfo, XHdcp22_Rx_Dp::Info, XHdcp22_Rx_Dp_Handles::IsDdcAllCallbacksSet, XHdcp22_Rx_Dp_Info::IsEncrypted, XHdcp22_Rx_Dp_Info::IsNoStoredKm, XHdcp22_Rx_Dp_Info::IsTopologyValid, XHdcp22_Rx_Dp_Handles::IsUnauthenticatedCallbackSet, XHdcp22_Rx_Dp_Info::LCInitAttempts, XHdcp22_Rx_Dp_Info::LinkErrorCnt, XHdcp22_Rx_Dp::MessageBuffer, XHdcp22_Rx_Dp::MessageSize, XHdcp22_Rx_Dp_Info::NextState, XHdcp22_Rx_Dp_Config::Protocol, XHdcp22_Rx_Dp_Info::ReauthReq, XHdcp22_Rx_Dp_Info::ReauthRequestCnt, XHdcp22_Rx_Dp_Info::ReturnState, XHdcp22_Rx_Dp_Info::SeqNumV, XHdcp22_Rx_Dp_Info::SkipRead, XHdcp22_Rx_Dp::StateFunc, XHdcp22_Rx_Dp::Topology, XHdcp22_Rx_Dp_Info::TopologyReady, XHdcp22_Rx_Dp_Handles::UnauthenticatedCallback, XHdcp22_Rx_Dp_Handles::UnauthenticatedCallbackRef, XHDCP22_RX_AUTHENTICATED, XHDCP22_RX_DP, XHDCP22_RX_ERROR_FLAG_NONE, XHDCP22_RX_LOG_EVT_INFO, XHDCP22_RX_LOG_INFO_RESET, XHDCP22_RX_STATE_B0_WAIT_AKEINIT, XHDCP22_RX_STATE_UNDEFINED, XHDCP22_RX_UNAUTHENTICATED, XHdcp22Rx_Dp_LogWr.
int XHdcp22Rx_Dp_Poll(XHdcp22_Rx_Dp *InstancePtr)
This function executes the HDCP22-RX state machine.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. None. State transitions are logged.
References XHdcp22_Rx_Dp_Info::AuthenticationStatus, XHdcp22_Rx_Dp_Info::CurrentState, XHdcp22_Rx_Dp::Info, XHdcp22_Rx_Dp_Info::IsEnabled, XHdcp22_Rx_Dp_Info::NextState, XHdcp22_Rx_Dp::StateFunc, XHDCP22_RX_LOG_EVT_INFO_STATE, XHdcp22Rx_Dp_LogWr.
int XHdcp22Rx_Dp_SetCallback(XHdcp22_Rx_Dp *InstancePtr, XHdcp22_Rx_Dp_HandlerType HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs callback functions for the given HandlerType:
HandlerType Callback Function Type ------------------------- --------------------------- (XHDCP22_RX_HANDLER_DDC_SETREGADDR) DdcSetAddressCallback (XHDCP22_RX_HANDLER_DDC_SETREGDATA) DdcSetDataCallback (XHDCP22_RX_HANDLER_DDC_GETREGDATA) DdcGetDataCallback (XHDCP22_RX_HANDLER_DDC_GETWBUFSIZE) DdcGetWriteBufferSizeCallback (XHDCP22_RX_HANDLER_DDC_GETRBUFSIZE) DdcGetReadBufferSizeCallback (XHDCP22_RX_HANDLER_DDC_ISWBUFEMPTY) DdcIsWriteBufferEmptyCallback (XHDCP22_RX_HANDLER_DDC_ISRBUFEMPTY) DdcIsReadBufferEmptyCallback (XHDCP22_RX_HANDLER_DDC_CLEARRBUF) DdcClearReadBufferCallback (XHDCP22_RX_HANDLER_DDC_CLEARWBUF) DdcClearWriteBufferCallback (XHDCP22_RX_HANDLER_AUTHENTICATED) AuthenticatedCallback (XHDCP22_RX_HANDLER_UNAUTHENTICATED) UnauthenticatedCallback (XHDCP22_RX_HANDLER_AUTHENTICATION_REQUEST) AuthenticationRequestCallback (XHDCP22_RX_HANDLER_STREAM_MANAGE_REQUEST) StreamManageRequestCallback (XHDCP22_RX_HANDLER_TOPOLOGY_UPDATE) TopologyUpdateCallback InstancePtr is a pointer to the HDMI RX core instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XHdcp22_Rx_Dp_Handles::AuthenticatedCallback, XHdcp22_Rx_Dp_Handles::AuthenticatedCallbackRef, XHdcp22_Rx_Dp_Handles::AuthenticationRequestCallback, XHdcp22_Rx_Dp_Handles::AuthenticationRequestCallbackRef, XHdcp22_Rx_Dp_Handles::DdcClearReadBufferCallback, XHdcp22_Rx_Dp_Handles::DdcClearReadBufferCallbackRef, XHdcp22_Rx_Dp_Handles::DdcClearWriteBufferCallback, XHdcp22_Rx_Dp_Handles::DdcClearWriteBufferCallbackRef, XHdcp22_Rx_Dp_Handles::DdcGetDataCallback, XHdcp22_Rx_Dp_Handles::DdcGetDataCallbackRef, XHdcp22_Rx_Dp_Handles::DdcGetReadBufferSizeCallback, XHdcp22_Rx_Dp_Handles::DdcGetReadBufferSizeCallbackRef, XHdcp22_Rx_Dp_Handles::DdcGetWriteBufferSizeCallback, XHdcp22_Rx_Dp_Handles::DdcGetWriteBufferSizeCallbackRef, XHdcp22_Rx_Dp_Handles::DdcIsReadBufferEmptyCallback, XHdcp22_Rx_Dp_Handles::DdcIsReadBufferEmptyCallbackRef, XHdcp22_Rx_Dp_Handles::DdcIsWriteBufferEmptyCallback, XHdcp22_Rx_Dp_Handles::DdcIsWriteBufferEmptyCallbackRef, XHdcp22_Rx_Dp_Handles::DdcSetAddressCallback, XHdcp22_Rx_Dp_Handles::DdcSetAddressCallbackRef, XHdcp22_Rx_Dp_Handles::DdcSetDataCallback, XHdcp22_Rx_Dp_Handles::DdcSetDataCallbackRef, XHdcp22_Rx_Dp_Handles::EncryptionStatusCallback, XHdcp22_Rx_Dp_Handles::EncryptionStatusCallbackRef, XHdcp22_Rx_Dp::Handles, XHdcp22_Rx_Dp_Handles::IsAuthenticatedCallbackSet, XHdcp22_Rx_Dp_Handles::IsAuthenticationRequestCallbackSet, XHdcp22_Rx_Dp_Handles::IsDdcAllCallbacksSet, XHdcp22_Rx_Dp_Handles::IsDdcClearReadBufferCallbackSet, XHdcp22_Rx_Dp_Handles::IsDdcClearWriteBufferCallbackSet, XHdcp22_Rx_Dp_Handles::IsDdcGetDataCallbackSet, XHdcp22_Rx_Dp_Handles::IsDdcGetReadBufferSizeCallbackRefSet, XHdcp22_Rx_Dp_Handles::IsDdcGetWriteBufferSizeCallbackSet, XHdcp22_Rx_Dp_Handles::IsDdcIsReadBufferEmptyCallbackSet, XHdcp22_Rx_Dp_Handles::IsDdcIsWriteBufferEmptyCallbackSet, XHdcp22_Rx_Dp_Handles::IsDdcSetAddressCallbackSet, XHdcp22_Rx_Dp_Handles::IsDdcSetDataCallbackSet, XHdcp22_Rx_Dp_Handles::IsEncryptionStatusCallbackSet, XHdcp22_Rx_Dp_Handles::IsRxDpAuxReadCallbackSet, XHdcp22_Rx_Dp_Handles::IsRxDpAuxWriteCallbackSet, XHdcp22_Rx_Dp_Handles::IsRxDpCpIrqSetCallbackSet, XHdcp22_Rx_Dp_Handles::IsSke_Send_EksCallbackSet, XHdcp22_Rx_Dp_Handles::IsStreamManageRequestCallbackSet, XHdcp22_Rx_Dp_Handles::IsTopologyUpdateCallbackSet, XHdcp22_Rx_Dp_Handles::IsUnauthenticatedCallbackSet, XHdcp22_Rx_Dp_Handles::RxDpAuxReadCallback, XHdcp22_Rx_Dp_Handles::RxDpAuxReadCallbackRef, XHdcp22_Rx_Dp_Handles::RxDpAuxWriteCallback, XHdcp22_Rx_Dp_Handles::RxDpAuxWriteCallbackRef, XHdcp22_Rx_Dp_Handles::RxDpCpIrqSetCallback, XHdcp22_Rx_Dp_Handles::RxDpCpIrqSetCallbackRef, XHdcp22_Rx_Dp_Handles::RxDpSetClearAuxDeferCallback, XHdcp22_Rx_Dp_Handles::RxDpSetClearAuxDeferCallbackRef, XHdcp22_Rx_Dp_Handles::Ske_Send_EksCallback, XHdcp22_Rx_Dp_Handles::Ske_Send_EksCallbackRef, XHdcp22_Rx_Dp_Handles::StreamManageRequestCallback, XHdcp22_Rx_Dp_Handles::StreamManageRequestCallbackRef, XHdcp22_Rx_Dp_Handles::TopologyUpdateCallback, XHdcp22_Rx_Dp_Handles::TopologyUpdateCallbackRef, XHdcp22_Rx_Dp_Handles::UnauthenticatedCallback, XHdcp22_Rx_Dp_Handles::UnauthenticatedCallbackRef, XHDCP22_RX_HANDLER_AUTHENTICATED, XHDCP22_RX_HANDLER_AUTHENTICATION_REQUEST, XHDCP22_RX_HANDLER_DDC_CLEARRBUF, XHDCP22_RX_HANDLER_DDC_CLEARWBUF, XHDCP22_RX_HANDLER_DDC_GETRBUFSIZE, XHDCP22_RX_HANDLER_DDC_GETREGDATA, XHDCP22_RX_HANDLER_DDC_GETWBUFSIZE, XHDCP22_RX_HANDLER_DDC_ISRBUFEMPTY, XHDCP22_RX_HANDLER_DDC_ISWBUFEMPTY, XHDCP22_RX_HANDLER_DDC_SETREGADDR, XHDCP22_RX_HANDLER_DDC_SETREGDATA, XHDCP22_RX_HANDLER_DP_AUX_DEFER_SET_CLR, XHDCP22_RX_HANDLER_DP_AUX_READ, XHDCP22_RX_HANDLER_DP_AUX_WRITE, XHDCP22_RX_HANDLER_DP_CP_IRQ_SET, XHDCP22_RX_HANDLER_ENCRYPTION_UPDATE, XHDCP22_RX_HANDLER_INVALID, XHDCP22_RX_HANDLER_SKE_SEND_EKS, XHDCP22_RX_HANDLER_STREAM_MANAGE_REQUEST, XHDCP22_RX_HANDLER_TOPOLOGY_UPDATE, XHDCP22_RX_HANDLER_UNAUTHENTICATED, XHDCP22_RX_HANDLER_UNDEFINED.
u32 XHdcp22Rx_Dp_GetVersion(XHdcp22_Rx_Dp *InstancePtr)
This function reads the version.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. Returns the version register of the cipher. None.
References XHdcp22_Rx_Dp::CipherInst.
XTmrCtr * XHdcp22Rx_Dp_GetTimer(XHdcp22_Rx_Dp *InstancePtr)
This function returns the pointer to the internal timer control instance needed for connecting the timer interrupt to an interrupt controller.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. A pointer to the internal timer control instance. None.
References XHdcp22_Rx_Dp::TimerInst.
u8 XHdcp22Rx_Dp_IsEnabled(XHdcp22_Rx_Dp *InstancePtr)
This function checks if the HDCP22-RX state machine is enabled.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. TRUE or FALSE. None.
References XHdcp22_Rx_Dp::Info, XHdcp22_Rx_Dp_Info::IsEnabled.
Referenced by XHdcp22Rx_Dp_Info.
u8 XHdcp22Rx_Dp_IsEncryptionEnabled(XHdcp22_Rx_Dp *InstancePtr)
This function checks if the HDCP22-RX cipher encryption is enabled.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. TRUE or FALSE. None.
References XHdcp22_Rx_Dp::CipherInst.
Referenced by XHdcp22Rx_Dp_Info.
u8 XHdcp22Rx_Dp_IsInProgress(XHdcp22_Rx_Dp *InstancePtr)
This function checks if the HDCP22-RX state machine is enabled but not yet in the Authenticated state.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. TRUE or FALSE. None.
References XHdcp22_Rx_Dp_Info::AuthenticationStatus, XHdcp22_Rx_Dp::Info, XHDCP22_RX_AUTHENTICATION_BUSY.
u8 XHdcp22Rx_Dp_IsAuthenticated(XHdcp22_Rx_Dp *InstancePtr)
This function checks if the HDCP22-RX state machine is in the Authenticated state.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. TRUE or FALSE. None.
References XHdcp22_Rx_Dp_Info::AuthenticationStatus, XHdcp22_Rx_Dp::Info, XHDCP22_RX_AUTHENTICATED.
u8 XHdcp22Rx_Dp_IsError(XHdcp22_Rx_Dp *InstancePtr)
This function checks if the HDCP22-RX state machine has detected an error condition.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. TRUE or FALSE. None.
References XHdcp22_Rx_Dp_Info::ErrorFlagSticky, XHdcp22_Rx_Dp::Info, XHDCP22_RX_ERROR_FLAG_NONE.
void XHdcp22Rx_Dp_Info(XHdcp22_Rx_Dp *InstancePtr)
This function prints the state machine information.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. None.
References XHdcp22_Rx_Dp_Info::AuthenticationStatus, XHdcp22_Rx_Dp_Info::AuthRequestCnt, XHdcp22_Rx_Dp_Info::DdcErrorCnt, XHdcp22_Rx_Dp_Topology::Depth, XHdcp22_Rx_Dp_Topology::DeviceCnt, XHdcp22_Rx_Dp_Topology::Hdcp1DeviceDownstream, XHdcp22_Rx_Dp_Topology::Hdcp2LegacyDeviceDownstream, XHdcp22_Rx_Dp::Info, XHdcp22_Rx_Dp_Info::LinkErrorCnt, XHdcp22_Rx_Dp_Topology::MaxCascadeExceeded, XHdcp22_Rx_Dp_Topology::MaxDevsExceeded, XHdcp22_Rx_Dp_Info::ReauthRequestCnt, XHdcp22_Rx_Dp::Topology, XHDCP22_RX_AUTHENTICATED, XHDCP22_RX_AUTHENTICATION_BUSY, XHDCP22_RX_REAUTHENTICATE_REQUESTED, XHDCP22_RX_UNAUTHENTICATED, XHdcp22Rx_Dp_GetContentStreamType, XHdcp22Rx_Dp_IsEnabled, XHdcp22Rx_Dp_IsEncryptionEnabled, XHdcp22Rx_Dp_IsRepeater.
void XHdcp22Rx_Dp_SetLinkError(XHdcp22_Rx_Dp *InstancePtr)
This function is called when 50 consecutive data island ECC errors are detected indicating a link integrity problem.
The error flag is set indicating to the state machine that REAUTH_REQ bit in the RXSTATUS register be set. Setting this flag only takes effect when the authentication state machine is in the Authenticated state B4. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. This function can be registered as an asynchronous callback.
References XHdcp22_Rx_Dp_Info::ErrorFlag, XHdcp22_Rx_Dp::Info, XHdcp22_Rx_Dp_Info::LinkErrorCnt, XHDCP22_RX_ERROR_FLAG_LINK_INTEGRITY, XHDCP22_RX_LOG_EVT_ERROR, XHdcp22Rx_Dp_LogWr.
void XHdcp22Rx_Dp_SetDdcError(XHdcp22_Rx_Dp *InstancePtr)
This function is called when a DDC read/write burst stops prior to completing the expected message size.
This will cause the message buffers to be flushed and state machine reset. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. This function can be registered as an asynchronous callback.
References XHdcp22_Rx_Dp_Info::DdcErrorCnt, XHdcp22_Rx_Dp_Info::ErrorFlag, XHdcp22_Rx_Dp::Info, XHDCP22_RX_ERROR_FLAG_DDC_BURST, XHDCP22_RX_LOG_EVT_ERROR, XHdcp22Rx_Dp_LogWr.
void XHdcp22Rx_Dp_SetWriteMessageAvailable(XHdcp22_Rx_Dp *InstancePtr)
This function is called when a complete message is available in the write message buffer.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. This function can be registered as an asynchronous callback.
References XHdcp22_Rx_Dp_Info::DdcFlag, XHdcp22_Rx_Dp::Info, XHDCP22_RX_DDC_FLAG_WRITE_MESSAGE_READY, XHDCP22_RX_LOG_DEBUG_WRITE_MESSAGE_AVAILABLE, XHDCP22_RX_LOG_EVT_DEBUG, XHdcp22Rx_Dp_LogWr.
void XHdcp22Rx_Dp_SetReadMessageComplete(XHdcp22_Rx_Dp *InstancePtr)
This function is called when a message has been read out of the read message buffer.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. This function can be registered as an asynchronous callback.
References XHdcp22_Rx_Dp_Info::DdcFlag, XHdcp22_Rx_Dp::Info, XHDCP22_RX_DDC_FLAG_READ_MESSAGE_READY, XHDCP22_RX_LOG_DEBUG_READ_MESSAGE_COMPLETE, XHDCP22_RX_LOG_EVT_DEBUG, XHdcp22Rx_Dp_LogWr.
void XHdcp22Rx_Dp_SetDpcdMsgRdWrtAvailable(XHdcp22_Rx_Dp *InstancePtr, u32 type)
This function is to set the DPCD flag if any DPCD read/write interrupts occurred.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. type is the type of interrupt
References XHdcp22_Rx_Dp_Info::DpcdFlag, XHdcp22_Rx_Dp::Info, XHDCP22_RX_DPCD_FLAG_AKE_INIT_RCVD, XHDCP22_RX_LOG_DEBUG_WRITE_MESSAGE_AVAILABLE, XHDCP22_RX_LOG_EVT_DEBUG, XHdcp22Rx_Dp_LogWr.
void XHdcp22Rx_Dp_SetHdcp22OverProtocol(XHdcp22_Rx_Dp *InstancePtr, XHdcp22_Rx_Dp_Protocol protocol)
This function is to set the protocol (HDMI/DP) over which HDCP22 is happening.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. protocol is the protocol HDMI/DP.
References XHdcp22_Rx_Dp::Config, XHdcp22_Rx_Dp_Config::Protocol.
void XHdcp22_Dp_timer_attach(XHdcp22_Rx_Dp *InstancePtr, XTmrCtr *TmrCtrPtr)
This function is to attach the HDCP22 timer instance to DP RX subsystem's timer.
For the DP design the timer is being used from the DP subsystem. So the HDCP22 timer instance will be attached in DpSs initialization. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. TmrCtrPtr is the DpRx subsystem's timer instance.
References XHdcp22_Rx_Dp::TimerInst.
void XHdcp22Rx_Dp_TimerHandler(void *CallbackRef, u8 TmrCntNumber)
This function handles timer interrupts.
CallbackRef refers to a XHdcp22_Rx_Dp structure TmrCntNumber the number of used timer. For DP design this handler will be called from DpRxSs timer interrupt handler so it should be a public function.
References XHdcp22_Rx_Dp::Info, XHdcp22_Rx_Dp::IsReady, XHdcp22_Rx_Dp_Info::TimerExpired, XHDCP22_RX_LOG_DEBUG_TIMER_EXPIRED, XHDCP22_RX_LOG_EVT_DEBUG, XHdcp22Rx_Dp_LogWr.
void XHdcp22_Dp_RxSetLaneCount(XHdcp22_Rx_Dp *InstancePtr, u8 LaneCount)
This function set the lane count of an hdcp22 interface.
InstancePtr is the receiver instance. LaneCount is the number of lanes of the interface. None.
References XHdcp22_Rx_Dp::CipherInst.
u32 XHdcp22_Dp_RxSetRxCaps(XHdcp22_Rx_Dp *InstancePtr, u8 enable)
This function sets the Rx_Caps in DPCD.
InstancePtr is the receiver instance. enable is to set or clear Rx_Caps. XST_SUCCESS or XST_FAILURE. None.
References XHdcp22_Rx_Dp::Handles, XHdcp22_Rx_Dp::RxCaps, XHdcp22_Rx_Dp_Handles::RxDpAuxWriteCallback, XHdcp22_Rx_Dp_Handles::RxDpAuxWriteCallbackRef.
void XHdcp22_Dp_RxSetStreamType(XHdcp22_Rx_Dp *InstancePtr)
This function sets Stream Type.
InstancePtr is the receiver instance. None.
References XHdcp22_Rx_Dp::CipherInst, XHdcp22_Rx_Dp::Handles, XHdcp22_Rx_Dp::Params, XHdcp22_Rx_Dp_Handles::RxDpAuxReadCallback, XHdcp22_Rx_Dp_Handles::RxDpAuxReadCallbackRef.
void XHdcp22Rx_Dp_LoadLc128(XHdcp22_Rx_Dp *InstancePtr, const u8 *Lc128Ptr)
This function is used to load the Lc128 value by copying the contents of the array referenced by Lc128Ptr into the cipher.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. Lc128Ptr is a pointer to an array. None.
References XHdcp22_Rx_Dp::CipherInst.
void XHdcp22Rx_Dp_LoadPublicCert(XHdcp22_Rx_Dp *InstancePtr, const u8 *PublicCertPtr)
This function is used to load the public certificate.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. PublicCertPtr is a pointer to an array. None.
References XHdcp22_Rx_Dp::PublicCertPtr.
int XHdcp22Rx_Dp_LoadPrivateKey(XHdcp22_Rx_Dp *InstancePtr, const u8 *PrivateKeyPtr)
This function is used to load the private key.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. PrivateKeyPtr is a pointer to an array. - XST_SUCCESS if MMULT keys are calculated correctly. XST_FAILURE if MMULT keys are not calculated correctly. None.
References XHdcp22_Rx_Dp::NPrimeP, XHdcp22_Rx_Dp::NPrimeQ, XHdcp22_Rx_Dp::PrivateKeyPtr, XHdcp22Rx_CalcMontNPrime.
void XHdcp22Rx_Dp_LogReset(XHdcp22_Rx_Dp *InstancePtr, u8 Verbose)
This function clears the log pointers.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. Verbose allows to add debug logging. None.
References XHdcp22_Rx_Dp_Log::Head, XHdcp22_Rx_Dp::Log, XHdcp22_Rx_Dp_Log::Tail, XHdcp22_Rx_Dp::TimerInst, XHdcp22_Rx_Dp_Log::Verbose.
Referenced by XHdcp22Rx_Dp_CfgInitialize.
u32 XHdcp22Rx_Dp_LogGetTimeUSecs(XHdcp22_Rx_Dp *InstancePtr)
This function returns the time expired since a log reset was called.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. The expired logging time in useconds. None.
References XHdcp22_Rx_Dp::TimerInst.
Referenced by XHdcp22Rx_Dp_LogWr.
void XHdcp22Rx_Dp_LogWr(XHdcp22_Rx_Dp *InstancePtr, u16 Evt, u16 Data)
This function writes HDCP22-RX log event into buffer.
If the log event is of type error, the sticky error flag is set. The sticky error flag is used to keep history of error conditions. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. Evt specifies an action to be carried out. Data specifies the information that gets written into log buffer. None.
References XHdcp22_Rx_Dp_LogItem::Data, XHdcp22_Rx_Dp_Info::ErrorFlagSticky, XHdcp22_Rx_Dp_Log::Head, XHdcp22_Rx_Dp::Info, XHdcp22_Rx_Dp::Log, XHdcp22_Rx_Dp_LogItem::LogEvent, XHdcp22_Rx_Dp_Log::LogItems, XHdcp22_Rx_Dp_Log::Tail, XHdcp22_Rx_Dp_LogItem::TimeStamp, XHdcp22_Rx_Dp_Log::Verbose, XHDCP22_RX_LOG_BUFFER_SIZE, XHDCP22_RX_LOG_EVT_DEBUG, XHDCP22_RX_LOG_EVT_ERROR, XHDCP22_RX_LOG_EVT_INFO_MESSAGE, XHDCP22_RX_LOG_EVT_INVALID, XHdcp22Rx_Dp_LogGetTimeUSecs.
Referenced by XHdcp22Rx_Dp_Disable, XHdcp22Rx_Dp_Enable, XHdcp22Rx_Dp_Poll, XHdcp22Rx_Dp_Reset, XHdcp22Rx_Dp_SetDdcError, XHdcp22Rx_Dp_SetDpcdMsgRdWrtAvailable, XHdcp22Rx_Dp_SetLinkError, XHdcp22Rx_Dp_SetReadMessageComplete, XHdcp22Rx_Dp_SetTopologyUpdate, XHdcp22Rx_Dp_SetWriteMessageAvailable, XHdcp22Rx_Dp_TimerHandler, XHdcp22Rx_RsaesOaepDecrypt.
XHdcp22_Rx_Dp_LogItem * XHdcp22Rx_Dp_LogRd(XHdcp22_Rx_Dp *InstancePtr)
This function provides the log information from the log buffer.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. Content of log buffer if log pointers are not equal.Otherwise Zero. None.
References XHdcp22_Rx_Dp_LogItem::Data, XHdcp22_Rx_Dp_Log::Head, XHdcp22_Rx_Dp::Log, XHdcp22_Rx_Dp_LogItem::LogEvent, XHdcp22_Rx_Dp_Log::LogItems, XHdcp22_Rx_Dp_Log::Tail, XHdcp22_Rx_Dp_LogItem::TimeStamp, XHDCP22_RX_LOG_BUFFER_SIZE.
Referenced by XHdcp22Rx_Dp_LogDisplay.
void XHdcp22Rx_Dp_LogDisplay(XHdcp22_Rx_Dp *InstancePtr)
This function prints the contents of the log buffer.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. None.
References XHdcp22_Rx_Dp_LogItem::Data, XHdcp22_Rx_Dp_LogItem::LogEvent, XHdcp22_Rx_Dp_LogItem::TimeStamp, XHDCP22_RX_ERROR_FLAG_DDC_BURST, XHDCP22_RX_ERROR_FLAG_EMPTY_REPEATER_TOPOLOGY, XHDCP22_RX_ERROR_FLAG_FORCE_RESET, XHDCP22_RX_ERROR_FLAG_LINK_INTEGRITY, XHDCP22_RX_ERROR_FLAG_MAX_LCINIT_ATTEMPTS, XHDCP22_RX_ERROR_FLAG_MAX_REPEATER_TOPOLOGY, XHDCP22_RX_ERROR_FLAG_MESSAGE_SIZE, XHDCP22_RX_ERROR_FLAG_PROCESSING_AKEINIT, XHDCP22_RX_ERROR_FLAG_PROCESSING_AKENOSTOREDKM, XHDCP22_RX_ERROR_FLAG_PROCESSING_AKESTOREDKM, XHDCP22_RX_ERROR_FLAG_PROCESSING_LCINIT, XHDCP22_RX_ERROR_FLAG_PROCESSING_REPEATERAUTHSENDACK, XHDCP22_RX_ERROR_FLAG_PROCESSING_REPEATERAUTHSTREAMMANAGE, XHDCP22_RX_ERROR_FLAG_PROCESSING_SKESENDEKS, XHDCP22_RX_LOG_DEBUG_COMPUTE_EKH, XHDCP22_RX_LOG_DEBUG_COMPUTE_EKH_DONE, XHDCP22_RX_LOG_DEBUG_COMPUTE_HPRIME, XHDCP22_RX_LOG_DEBUG_COMPUTE_HPRIME_DONE, XHDCP22_RX_LOG_DEBUG_COMPUTE_KM, XHDCP22_RX_LOG_DEBUG_COMPUTE_KM_DONE, XHDCP22_RX_LOG_DEBUG_COMPUTE_KS, XHDCP22_RX_LOG_DEBUG_COMPUTE_KS_DONE, XHDCP22_RX_LOG_DEBUG_COMPUTE_LPRIME, XHDCP22_RX_LOG_DEBUG_COMPUTE_LPRIME_DONE, XHDCP22_RX_LOG_DEBUG_COMPUTE_MPRIME, XHDCP22_RX_LOG_DEBUG_COMPUTE_MPRIME_DONE, XHDCP22_RX_LOG_DEBUG_COMPUTE_RSA, XHDCP22_RX_LOG_DEBUG_COMPUTE_RSA_DONE, XHDCP22_RX_LOG_DEBUG_COMPUTE_VPRIME, XHDCP22_RX_LOG_DEBUG_COMPUTE_VPRIME_DONE, XHDCP22_RX_LOG_DEBUG_READ_MESSAGE_COMPLETE, XHDCP22_RX_LOG_DEBUG_TIMER_EXPIRED, XHDCP22_RX_LOG_DEBUG_TIMER_START, XHDCP22_RX_LOG_DEBUG_WRITE_MESSAGE_AVAILABLE, XHDCP22_RX_LOG_EVT_DEBUG, XHDCP22_RX_LOG_EVT_ERROR, XHDCP22_RX_LOG_EVT_INFO, XHDCP22_RX_LOG_EVT_INFO_MESSAGE, XHDCP22_RX_LOG_EVT_INFO_STATE, XHDCP22_RX_LOG_EVT_USER, XHDCP22_RX_LOG_INFO_DISABLE, XHDCP22_RX_LOG_INFO_ENABLE, XHDCP22_RX_LOG_INFO_ENCRYPTION_ENABLE, XHDCP22_RX_LOG_INFO_REQAUTH_REQ, XHDCP22_RX_LOG_INFO_RESET, XHDCP22_RX_LOG_INFO_TOPOLOGY_UPDATE, XHDCP22_RX_MSG_ID_AKEINIT, XHDCP22_RX_MSG_ID_AKENOSTOREDKM, XHDCP22_RX_MSG_ID_AKESENDCERT, XHDCP22_RX_MSG_ID_AKESENDHPRIME, XHDCP22_RX_MSG_ID_AKESENDPAIRINGINFO, XHDCP22_RX_MSG_ID_AKESTOREDKM, XHDCP22_RX_MSG_ID_LCINIT, XHDCP22_RX_MSG_ID_LCSENDLPRIME, XHDCP22_RX_MSG_ID_REPEATERAUTHSENDACK, XHDCP22_RX_MSG_ID_REPEATERAUTHSENDRXIDLIST, XHDCP22_RX_MSG_ID_REPEATERAUTHSTREAMMANAGE, XHDCP22_RX_MSG_ID_REPEATERAUTHSTREAMREADY, XHDCP22_RX_MSG_ID_SKESENDEKS, XHDCP22_RX_STATE_B0_WAIT_AKEINIT, XHDCP22_RX_STATE_B1_SEND_AKESENDCERT, XHDCP22_RX_STATE_B1_SEND_AKESENDHPRIME, XHDCP22_RX_STATE_B1_SEND_AKESENDPAIRINGINFO, XHDCP22_RX_STATE_B1_WAIT_AKEKM, XHDCP22_RX_STATE_B1_WAIT_LCINIT, XHDCP22_RX_STATE_B2_SEND_LCSENDLPRIME, XHDCP22_RX_STATE_B2_WAIT_SKESENDEKS, XHDCP22_RX_STATE_B3_COMPUTE_KS, XHDCP22_RX_STATE_B4_AUTHENTICATED, XHDCP22_RX_STATE_C4_WAIT_FOR_DOWNSTREAM, XHDCP22_RX_STATE_C5_SEND_RECEIVERIDLIST, XHDCP22_RX_STATE_C5_SEND_RECEIVERIDLIST_DONE, XHDCP22_RX_STATE_C6_VERIFY_RECEIVERIDLISTACK, XHDCP22_RX_STATE_C7_SEND_STREAM_READY, XHDCP22_RX_STATE_C7_SEND_STREAM_READY_DONE, XHDCP22_RX_STATE_C7_WAIT_STREAM_MANAGEMENT, XHDCP22_RX_STATE_C8_AUTHENTICATED, XHdcp22Rx_Dp_LogRd.
void XHdcp22Rx_Dp_SetTopology(XHdcp22_Rx_Dp *InstancePtr, const XHdcp22_Rx_Dp_Topology *TopologyPtr)
This function copies a complete repeater topology table into the instance repeater topology table.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. TopologyPtr is a pointer to the repeater topology table. None.
References XHdcp22_Rx_Dp::Topology.
void XHdcp22Rx_Dp_SetTopologyReceiverIdList(XHdcp22_Rx_Dp *InstancePtr, const u8 *ListPtr, u32 ListSize)
This function copies the RECEIVER_ID_LIST into the repeater topology table.
Receiver ID list is constructed by appending Receiver IDs in big-endian order. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. ListPtr is a pointer to the Receiver ID list. The list consists of a contiguous set of bytes stored in big-endian order, with each Receiver ID occuping five bytes with a maximum of 31 Receiver IDs. ListSize is the number of Receiver IDs in the list. The list size cannot exceed 31 devices. None.
References XHdcp22_Rx_Dp_Topology::ReceiverIdList, XHdcp22_Rx_Dp::Topology.
void XHdcp22Rx_Dp_SetTopologyField(XHdcp22_Rx_Dp *InstancePtr, XHdcp22_Rx_Dp_TopologyField Field, u8 Value)
This function is used to set various fields inside the topology structure.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. Field indicates what field of the topology structure to update. Value is the value assigned to the field of the topology structure. None.
void XHdcp22Rx_Dp_SetTopologyUpdate(XHdcp22_Rx_Dp *InstancePtr)
This function is used to indicate that the topology table has been updated and is ready for upstream propagation.
Before calling this function ensure that all the fields in the repeater topology table have been updated. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. None.
References XHdcp22_Rx_Dp::Info, XHdcp22_Rx_Dp_Info::IsTopologyValid, XHDCP22_RX_LOG_EVT_INFO, XHDCP22_RX_LOG_INFO_TOPOLOGY_UPDATE, XHdcp22Rx_Dp_LogWr.
void XHdcp22Rx_Dp_SetRepeater(XHdcp22_Rx_Dp *InstancePtr, u8 Set)
This function sets the repeater mode status.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. Set is TRUE to enable repeater mode and FALSE to disable.
References XHdcp22_Rx_Dp::Config, XHdcp22_Rx_Dp_Config::Mode, XHdcp22_Rx_Dp::RxCaps, XHDCP22_RX_RECEIVER, XHDCP22_RX_REPEATER.
void XHdcp22_Dp_RxSetReauthReq(XHdcp22_Rx_Dp *InstancePtr)
This function sets Reauth Request for upstream device.
InstancePtr is the receiver instance. None.
u8 XHdcp22Rx_Dp_IsRepeater(XHdcp22_Rx_Dp *InstancePtr)
This function returns the current repeater mode status.
InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. TRUE if the HDCP 2.2 instance is the upstream port of a repeaterFALSE if the HDCP 2.2 instance is a receiver
References XHdcp22_Rx_Dp::Config, XHdcp22_Rx_Dp_Config::Mode, XHDCP22_RX_RECEIVER.
Referenced by XHdcp22Rx_Dp_Info.
u8 XHdcp22Rx_Dp_GetContentStreamType(XHdcp22_Rx_Dp *InstancePtr)
This function is gets the type information received from the RepeaterAuth_Stream_Manage message for downstream propagation of management information.
This function should be called only after the RepeaterAuth_Stream_Manage message has been received, and can be called inside the user callback function type XHDCP22_RX_HANDLER_STREAM_MANAGE_REQUEST. InstancePtr is a pointer to the XHdcp22_Rx_Dp core instance. - 0x00: Type 0 Content Stream. May be transmitted by the HDCP Repeater to all HDCP Devices. 0x01: Type 1 Content Stream. Must not be transmitted by the HDCP Repeater to HDCP 1.x-compliant Devices and HDCP 2.1-compliant Devices.0x02-0xFF: Reserved for future use only. Content Streams with reserved Type values must be treated similar to Type 1 Content Streams. None.
References XHdcp22_Rx_Dp::Params.
Referenced by XHdcp22Rx_Dp_Info.