dphy
XDPHY_MODE_MIN
Lower limit for Mode.
XDPHY_LOW_POWER_MODE
Lane in Low Power Mode.
XDPHY_HIGH_POWER_MODE
Lane in High Power Mode.
XDPHY_ESCAPE_MODE
Lane in Escape Mode.
XDPHY_MODE_MAX
Upper Limit for mode.
XDPHY_MAX_LANES_V10
V1.0 supports 4 Lanes.
Referenced by XDphy_Configure, XDphy_GetInfo.
XDPHY_HANDLE_MIN
Lower Bound for XDPHY_HANDLE.
XDPHY_HANDLE_IDELAY
Handle for IDELAY Reg.
Referenced by XDphy_Configure, XDphy_GetInfo.
XDPHY_HANDLE_INIT_TIMER
Handle for Initialization Timer.
Referenced by XDphy_Configure, XDphy_GetInfo.
XDPHY_HANDLE_WAKEUP
Handle for Wakeup timer.
Referenced by XDphy_Configure, XDphy_GetInfo.
XDPHY_HANDLE_HSTIMEOUT
Handle for HS Timeout.
Referenced by XDphy_Configure, XDphy_GetInfo, XDphy_SelfTest.
XDPHY_HANDLE_ESCTIMEOUT
Handle for Escape Timeout.
Referenced by XDphy_Configure, XDphy_GetInfo.
XDPHY_HANDLE_CLKLANE
Handle for Clock Lane.
Referenced by XDphy_Configure, XDphy_GetInfo.
XDPHY_HANDLE_DLANE0
Handle for Data Lane 0.
Referenced by XDphy_Configure, XDphy_GetInfo.
XDPHY_HANDLE_DLANE1
Handle for Data Lane 1.
Referenced by XDphy_Configure, XDphy_GetInfo.
XDPHY_HANDLE_DLANE2
Handle for Data Lane 2.
Referenced by XDphy_Configure, XDphy_GetInfo.
XDPHY_HANDLE_DLANE3
Handle for Data Lane 3.
Referenced by XDphy_Configure, XDphy_GetInfo.
XDPHY_HANDLE_HSSETTLE
Handle for HS SETTLE.
Referenced by XDphy_Configure, XDphy_GetInfo.
XDPHY_HANDLE_DLANE4
Handle for Data Lane 4.
Referenced by XDphy_Configure, XDphy_GetInfo.
XDPHY_HANDLE_DLANE5
Handle for Data Lane 5.
Referenced by XDphy_Configure, XDphy_GetInfo.
XDPHY_HANDLE_DLANE6
Handle for Data Lane 6.
Referenced by XDphy_Configure, XDphy_GetInfo.
XDPHY_HANDLE_DLANE7
Handle for Data Lane 7.
Referenced by XDphy_Configure, XDphy_GetInfo.
XDPHY_HANDLE_HSSETTLE1
Handle for HS SETTLE L1.
Referenced by XDphy_Configure, XDphy_GetInfo.
XDPHY_HANDLE_HSSETTLE2
Handle for HS SETTLE L2.
Referenced by XDphy_Configure, XDphy_GetInfo.
XDPHY_HANDLE_HSSETTLE3
Handle for HS SETTLE L3.
Referenced by XDphy_Configure, XDphy_GetInfo.
XDPHY_HANDLE_HSSETTLE4
Handle for HS SETTLE.
Referenced by XDphy_Configure, XDphy_GetInfo.
XDPHY_HANDLE_HSSETTLE5
Handle for HS SETTLE L1.
Referenced by XDphy_Configure, XDphy_GetInfo.
XDPHY_HANDLE_HSSETTLE6
Handle for HS SETTLE L2.
Referenced by XDphy_Configure, XDphy_GetInfo.
XDPHY_HANDLE_HSSETTLE7
Handle for HS SETTLE L3.
Referenced by XDphy_Configure, XDphy_GetInfo.
XDPHY_HANDLE_MAX
Upper Bound for XDPHY_HANDLE.
Referenced by XDphy_Configure, XDphy_GetInfo.
XDPHY_HS_TIMEOUT_MIN_VALUE
Minimum HS timeout value.
Referenced by XDphy_Configure.
XDPHY_HS_TIMEOUT_MAX_VALUE
Maximum HS timeout value.
Referenced by XDphy_Configure.
XDPHY_HS_SETTLE_MAX_VALUE
Maximum HS settle value.
Referenced by XDphy_Configure.
XDPHY_ENABLE_FLAG
Flag to enable DPHY core.
Referenced by XDphy_Activate.
XDPHY_DISABLE_FLAG
Flag to disable DPHY core.
Referenced by XDphy_Activate.
u32 XDphy_CfgInitialize(XDphy *InstancePtr, XDphy_Config *CfgPtr, UINTPTR EffectiveAddr)
Initialize the XDphy instance provided by the caller based on the given Config structure.
InstancePtr is the XDphy instance to operate on. CfgPtr is the device configuration structure containing information about a specific DPhy instance. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS Initialization was successful. None.
References XDphy_Config::BaseAddr, XDphy::Config, XDphy::IsReady.
Referenced by DphySelfTestExample.
u32 XDphy_Configure(XDphy *InstancePtr, u8 Handle, u32 Value)
Configure the registers of the Dphy instance.
InstancePtr is the XDphy instance to operate on. Handle to one of the registers to be configured Value to be set for the particular Handle of the DPHY instance XST_SUCCESS on successful register update.XST_FAILURE If incorrect handle was passed There is a limit on the minimum and maximum values of the HS Timeout register.
References XDphy::Config, XDphy_Config::EnableTimeOutRegs, XDphy_Config::IsRegisterPresent, XDphy_Config::IsRx, XDphy_Config::MaxLanesPresent, XDPHY_ESCTIMEOUT_REG_OFFSET, XDPHY_HANDLE_CLKLANE, XDPHY_HANDLE_DLANE0, XDPHY_HANDLE_DLANE1, XDPHY_HANDLE_DLANE2, XDPHY_HANDLE_DLANE3, XDPHY_HANDLE_DLANE4, XDPHY_HANDLE_DLANE5, XDPHY_HANDLE_DLANE6, XDPHY_HANDLE_DLANE7, XDPHY_HANDLE_ESCTIMEOUT, XDPHY_HANDLE_HSSETTLE, XDPHY_HANDLE_HSSETTLE1, XDPHY_HANDLE_HSSETTLE2, XDPHY_HANDLE_HSSETTLE3, XDPHY_HANDLE_HSSETTLE4, XDPHY_HANDLE_HSSETTLE5, XDPHY_HANDLE_HSSETTLE6, XDPHY_HANDLE_HSSETTLE7, XDPHY_HANDLE_HSTIMEOUT, XDPHY_HANDLE_IDELAY, XDPHY_HANDLE_INIT_TIMER, XDPHY_HANDLE_MAX, XDPHY_HANDLE_WAKEUP, XDPHY_HS_SETTLE_MAX_VALUE, XDPHY_HS_TIMEOUT_MAX_VALUE, XDPHY_HS_TIMEOUT_MIN_VALUE, XDPHY_HSEXIT_IDELAY_REG_OFFSET, XDPHY_HSEXIT_IDELAY_REG_TAP_MASK, XDPHY_HSSETTLE1_REG_OFFSET, XDPHY_HSSETTLE2_REG_OFFSET, XDPHY_HSSETTLE3_REG_OFFSET, XDPHY_HSSETTLE4_REG_OFFSET, XDPHY_HSSETTLE5_REG_OFFSET, XDPHY_HSSETTLE6_REG_OFFSET, XDPHY_HSSETTLE7_REG_OFFSET, XDPHY_HSSETTLE_REG_OFFSET, XDPHY_HSTIMEOUT_REG_OFFSET, XDPHY_IDELAY58_REG_OFFSET, XDPHY_INIT_REG_OFFSET, XDPHY_MAX_LANES_V10, XDPHY_WAKEUP_REG_OFFSET.
u8 XDphy_GetRegIntfcPresent(XDphy *InstancePtr)
Get if register interface is present from the config structure for specified DPHY instance.
InstancePtr is the XDphy instance to operate on. 1 if register interface is present0 if register interface is absent None.
References XDphy::Config, XDphy_Config::IsRegisterPresent.
Referenced by DphySelfTestExample.
u32 XDphy_GetInfo(XDphy *InstancePtr, u8 Handle)
Get information stored in the DPhy instance based on the handle passed.
InstancePtr is the XDphy instance to operate on. Handle to one of the registers to be configured The value stored in the corresponding register None.
References XDphy::Config, XDphy_Config::EnableTimeOutRegs, XDphy_Config::EscTimeout, XDphy_Config::HSTimeOut, XDphy_Config::IsRegisterPresent, XDphy_Config::IsRx, XDphy_Config::MaxLanesPresent, XDPHY_CLSTATUS_REG_OFFSET, XDPHY_DL0STATUS_REG_OFFSET, XDPHY_DL1STATUS_REG_OFFSET, XDPHY_DL2STATUS_REG_OFFSET, XDPHY_DL3STATUS_REG_OFFSET, XDPHY_DL4STATUS_REG_OFFSET, XDPHY_DL5STATUS_REG_OFFSET, XDPHY_DL6STATUS_REG_OFFSET, XDPHY_DL7STATUS_REG_OFFSET, XDPHY_ESCTIMEOUT_REG_OFFSET, XDPHY_HANDLE_CLKLANE, XDPHY_HANDLE_DLANE0, XDPHY_HANDLE_DLANE1, XDPHY_HANDLE_DLANE2, XDPHY_HANDLE_DLANE3, XDPHY_HANDLE_DLANE4, XDPHY_HANDLE_DLANE5, XDPHY_HANDLE_DLANE6, XDPHY_HANDLE_DLANE7, XDPHY_HANDLE_ESCTIMEOUT, XDPHY_HANDLE_HSSETTLE, XDPHY_HANDLE_HSSETTLE1, XDPHY_HANDLE_HSSETTLE2, XDPHY_HANDLE_HSSETTLE3, XDPHY_HANDLE_HSSETTLE4, XDPHY_HANDLE_HSSETTLE5, XDPHY_HANDLE_HSSETTLE6, XDPHY_HANDLE_HSSETTLE7, XDPHY_HANDLE_HSTIMEOUT, XDPHY_HANDLE_IDELAY, XDPHY_HANDLE_INIT_TIMER, XDPHY_HANDLE_MAX, XDPHY_HANDLE_WAKEUP, XDPHY_HSEXIT_IDELAY_REG_OFFSET, XDPHY_HSSETTLE1_REG_OFFSET, XDPHY_HSSETTLE2_REG_OFFSET, XDPHY_HSSETTLE3_REG_OFFSET, XDPHY_HSSETTLE4_REG_OFFSET, XDPHY_HSSETTLE5_REG_OFFSET, XDPHY_HSSETTLE6_REG_OFFSET, XDPHY_HSSETTLE7_REG_OFFSET, XDPHY_HSSETTLE_REG_OFFSET, XDPHY_HSTIMEOUT_REG_OFFSET, XDPHY_INIT_REG_OFFSET, XDPHY_MAX_LANES_V10, XDPHY_WAKEUP_REG_OFFSET.
Referenced by XDphy_SelfTest.
void XDphy_Reset(XDphy *InstancePtr)
This is used to do a soft reset of the DPhy IP instance.
The reset takes approx 20 core clock cycles to become effective. InstancePtr is the XDphy instance to operate on. None.
References XDphy::Config, XDphy::IsReady, XDphy_Config::IsRegisterPresent, XDPHY_CTRL_REG_OFFSET, XDPHY_CTRL_REG_SOFTRESET_MASK.
void XDphy_ClearDataLane(XDphy *InstancePtr, u8 DataLane, u32 Mask)
This is used to clear the Abort Error (Escape or High Speed) bits in the Data Lane 0 through 3.
InstancePtr is the XDphy instance to operate on. DataLane represents which Data Lane to act upon Mask contains information about which bits to reset None.
References XDphy_Config::BaseAddr, XDphy::Config, XDphy_Config::IsRegisterPresent, XDPHY_DL0STATUS_REG_OFFSET, XDPHY_DLXSTATUS_REG_ESCABRT_MASK, XDPHY_DLXSTATUS_REG_HSABRT_MASK.
u32 XDphy_GetClkLaneStatus(XDphy *InstancePtr)
This is used to get information about Clock Lane status.
InstancePtr is the XDphy instance to operate on. Bitmask containing which of the events have occurred along with the mode of the Clock Lane in DPhy None.
References XDphy_Config::BaseAddr, XDphy::Config, XDphy_Config::IsRegisterPresent, XDPHY_CLSTATUS_REG_OFFSET.
Referenced by XDphy_GetClkLaneMode.
u32 XDphy_GetClkLaneMode(XDphy *InstancePtr)
This is used to get specific Lane mode information about Clock Lane.
InstancePtr is the XDphy instance to operate on. Bitmask containing mode in which the Clock Lane in DPhy is in. None.
References XDphy::Config, XDphy_Config::IsRegisterPresent, XDPHY_CLSTATUS_REG_MODE_MASK, XDphy_GetClkLaneStatus.
u32 XDphy_GetDataLaneStatus(XDphy *InstancePtr, u8 DataLane)
This is used to get information about a Data Lane status.
InstancePtr is the XDphy instance to operate on. DataLane for which the status is sought for. Bitmask containing which of the events have occurred along with the mode of the Data Lane in DPhy None.
References XDphy_Config::BaseAddr, XDphy::Config, XDphy_Config::IsRegisterPresent, XDPHY_DL0STATUS_REG_OFFSET.
Referenced by XDphy_GetDataLaneMode.
u8 XDphy_GetDLCalibStatus(XDphy *InstancePtr, u8 DataLane)
This is used to get Data Lane Calibration status.
InstancePtr is the XDphy instance to operate on. DataLane for which the calib status is sought for. XST_SUCCESS - Calibration Complete, Calibration packet received XST_NO_DATA - Calibration Complete, Calibration packet is not received XST_FAILURE - Calibration failed None.
References XDphy_Config::BaseAddr, XDphy::Config, DL_LANE_OFFSET, XDphy_Config::IsRegisterPresent, XDPHY_DL0STATUS_REG_OFFSET, XDPHY_DLXSTATUS_REG_CALIB_COMPLETE_MASK, XDPHY_DLXSTATUS_REG_CALIB_STATUS_MASK.
u32 XDphy_GetDataLaneMode(XDphy *InstancePtr, u8 DataLane)
This is used to get specific Lane mode information about a Data Lane.
InstancePtr is the XDphy instance to operate on. DataLane for which the mode info is requested. Bitmask containing mode in which the Data Lane in DPhy is in. None.
References XDphy::Config, XDphy_Config::IsRegisterPresent, XDPHY_DLXSTATUS_REG_MODE_MASK, XDphy_GetDataLaneStatus.
u16 XDphy_GetPacketCount(XDphy *InstancePtr, u8 DataLane)
This is used to get count of packets received on each lane.
InstancePtr is the XDphy instance to operate on. DataLane for which the mode info is requested. Bitmask containing mode in which the Data Lane in DPhy is in. None.
References XDphy_Config::BaseAddr, XDphy::Config, XDphy_Config::IsRegisterPresent, XDPHY_DL0STATUS_REG_OFFSET, XDPHY_DLXSTATUS_REG_PACKCOUNT_OFFSET, XDPHY_DLXSTATUS_REG_PACKETCOUNT_MASK.
void XDphy_Activate(XDphy *InstancePtr, u8 Flag)
This function is used to enable or disable the DPhy core.
InstancePtr is the XDphy instance to operate on. Flag denoting whether to enable or disable the DPhy core None.
References XDphy_Config::BaseAddr, XDphy::Config, XDphy_Config::IsRegisterPresent, XDPHY_CTRL_REG_DPHYEN_MASK, XDPHY_CTRL_REG_OFFSET, XDPHY_DISABLE_FLAG, XDPHY_ENABLE_FLAG.
static void XDphy_BitSet(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask)
This inline function is used to set bit in a DPHY register space.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitMask of bit field to be set None None
static void XDphy_BitReset(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask)
This inline function is used to reset bit in a DPHY register space.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitMask of bit field to be reset None None
static u32 XDphy_GetBitField(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask, u32 BitShift)
This function is used to get the value of bitfield from DPHY register space.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitMask of bit field whose value needs to be obtained BitShift is offset of bit field Bit Field Value in u32 format None
static void XDphy_SetBitField(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask, u32 BitShift, u32 Value)
This function is used to set the value of bitfield from DPHY register space.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitMask of bit field whose value needs to be updated BitShift is offset of bit field Value to be set. Passed in u32 format. None None
XDphy_Config * XDphy_LookupConfig(UINTPTR BaseAddress)
Look up the hardware configuration for a device instance.
DeviceId is the unique device ID of the device to lookup for The reference to the configuration record in the configuration table (in xdphy_g.c) corresponding to the Device ID or if not found,a NULL pointer is returned. None
Referenced by DphySelfTestExample.
u32 XDphy_SelfTest(XDphy *InstancePtr)
Runs a self-test on the driver/device.
This test checks if HS Timeout value present in register matches the one from the generated file. InstancePtr is a pointer to the XDphy instance. XST_SUCCESS if self-test was successful XST_FAILURE if the read value was not equal to _g.c file None.
References XDphy::Config, XDphy_Config::HSTimeOut, XDphy_GetInfo, XDPHY_HANDLE_HSTIMEOUT.
Referenced by DphySelfTestExample.
XDPHY_SOFTRESET_TIMEOUT
XDPHY_H_
Prevent circular inclusions by using protection macros.