trafgen
XTG_MCNTL_OFFSET
Master Control.
XTG_SCNTL_OFFSET
Slave Control.
XTG_ERR_STS_OFFSET
Error Status.
XTG_ERR_EN_OFFSET
Error Enable.
XTG_MSTERR_INTR_OFFSET
Master Err Interrupt Enable.
XTG_CFG_STS_OFFSET
Config Status.
XTG_STREAM_CNTL_OFFSET
Streaming Control.
XTG_STREAM_CFG_OFFSET
Streaming Config.
XTG_STREAM_TL_OFFSET
Streaming Transfer Length.
XTG_STATIC_CNTL_OFFSET
Static Mode Register Descriptions.
Static Control
XTG_STATIC_LEN_OFFSET
Static Length.
XTG_PARAM_RAM_OFFSET
Parameter RAM Offset.
XTG_COMMAND_RAM_OFFSET
Command RAM Offset.
XTG_MASTER_RAM_OFFSET
Master RAM Offset.
XTG_COMMAND_RAM_MSB_OFFSET
Command RAM MSB Offset.
XTG_MCNTL_REV_MASK
Core Revision Mask.
XTG_MCNTL_MSTID_MASK
M_ID_WIDTH Mask.
XTG_MCNTL_MSTEN_MASK
Master Logic Enable Mask.
XTG_MCNTL_LOOPEN_MASK
Loop enable Mask.
XTG_MCNTL_REV_SHIFT
Core Rev shift.
XTG_MCNTL_MSTID_SHIFT
M_ID_WIDTH shift.
XTG_SCNTL_BLKRD_MASK
Enable Block Read.
XTG_SCNTL_DISEXCL_MASK
Disable Exclusive Access.
XTG_SCNTL_WORDR_MASK
Write Response Order Enable.
XTG_SCNTL_RORDR_MASK
Read Response Order Enable.
XTG_SCNTL_ERREN_MASK
Slv Error Interrupt Enable.
XTG_ERR_ALL_MSTERR_MASK
Master Errors Mask.
XTG_ERR_ALL_SLVERR_MASK
Slave Errors Mask.
XTG_ERR_ALL_ERR_MASK
All Errors Mask.
XTG_ERR_MSTCMP_MASK
Master Complete Mask.
XTG_ERR_RIDER_MASK
Master Invalid RVALID Mask.
XTG_ERR_WIDER_MASK
Master Invalid BVALID Mask.
XTG_ERR_WRSPER_MASK
MW Invalid RESP Mask.
XTG_ERR_RERRSP_MASK
MR Invalid RESP Mask.
XTG_ERR_RLENER_MASK
Master Read Length Mask.
XTG_ERR_SWSTRB_MASK
Slave WSTRB Illegal Mask.
XTG_ERR_SWLENER_MASK
Slave Read Length Mask.
typedef struct XTrafGen_CRamCmd XTrafGen_CRamCmd
Command Ram word fields.
typedef struct XTrafGen_PRamCmd XTrafGen_PRamCmd
Parameter Ram word fields.
typedef struct XTrafGen_Cmd XTrafGen_Cmd
Command structure exposed to user.
This structure should be updated by user with required configuration
typedef struct XTrafGen_CmdEntry XTrafGen_CmdEntry
Command Entry structure.
This structure denotes each entry of 256 commands.
typedef struct XTrafGen_Config XTrafGen_Config
The configuration structure for Traffic Generator device.
This structure passes the hardware building information to the driver
typedef struct XTrafGen_CmdInfo XTrafGen_CmdInfo
Command Information Structure.
This structure is maintained by the driver
typedef struct XTrafGen XTrafGen
The XTrafGen driver instance data.
An instance must be allocated for each Traffic Generator device in use.
XTrafGen_Config XTrafGen_ConfigTable[][]
static void XTrafGen_PrepCmdWords(XTrafGen *InstancePtr, XTrafGen_Cmd *CmdPtr, u32 *CmdWords)
Prepares all the four Command RAM Words.
The CMDRAM is divided into two 4 KB regions, one for reads and one for writes. Each region of CMDRAM can hold 256 commands each of 128 bits i.e. Four command words each of size 32 bits. This function prepares these command words from the user specified configuration. InstancePtr is a pointer to the Axi TrafGen instance to be worked on. CmdPtr is a pointer to Command structure. CmdWords is a pointer to an array of four command words.
static void XTrafGen_PrepParamWord(XTrafGen *InstancePtr, XTrafGen_Cmd *CmdPtr, u32 *ParamWord)
Prepares Parameter RAM Word.
The PARAMRAM extends the command programmability provided through command RAM, by adding extra 32 bits to the decode of each command. This function prepares this 32 bit Parameter RAM word. InstancePtr is a pointer to the Axi TrafGen instance to be worked on. CmdPtr is a pointer to Command structure. ParamWord is a pointer to an value of Parameter RAM word.
static int XTrafGen_ProgramCmdRam(XTrafGen *InstancePtr, u8 RdWrFlag)
Program Command RAM.
This function write the list of Command Words prepared by using *_AddCommand() to Command RAM till the last command entry added. InstancePtr is a pointer to the Axi TrafGen instance to be worked on. RdWrFlag specifies Read or Write Region XST_SUCCESS if successfulXST_FAILURE if no valid commands present
static int XTrafGen_ProgramParamRam(XTrafGen *InstancePtr, u8 RdWrFlag)
Program Parameter RAM.
This function write the list of Parameter Words prepared by using *_AddCommand() to Parameter RAM till the last command entry added. InstancePtr is a pointer to the Axi TrafGen instance to be worked on. RdWrFlag specifies Read or Write Region XST_SUCCESS if successfulXST_FAILURE if no valid commands present
int XTrafGen_CfgInitialize(XTrafGen *InstancePtr, XTrafGen_Config *Config, UINTPTR EffectiveAddress)
This function initializes a AXI Traffic Generator device.
This function must be called prior to using a AXI Traffic Generator Device. Initializing a engine includes setting up the register base address, setting up the instance data, and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the Axi Traffic Generator instance to be worked on. CfgPtr references the structure holding the hardware configuration for the Axi Traffic Generator core to initialize. EffectiveAddr is the device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, use Config->BaseAddress for this parameters, passing the physical address instead. XST_SUCCESS for successful initializationXST_INVALID_PARAM if pointer to the configuration structure is NULL
References XTrafGen_Config::AddressWidth, XTrafGen_Config::BaseAddress, XTrafGen_Config::BusType, XTrafGen::CmdInfo, XTrafGen::Config, XTrafGen_Config::IntId, XTrafGen_Config::IntrParent, XTrafGen::IsReady, XTrafGen_CmdInfo::LastRdValidIndex, XTrafGen_CmdInfo::LastWrValidIndex, XTrafGen::MasterWidth, XTrafGen_Config::Mode, XTrafGen_Config::ModeType, XTrafGen::OperatingMode, XTrafGen::SlaveWidth, XTG_CFG_STS_MBASIC_MASK, XTG_CFG_STS_MFULL_MASK, XTG_CFG_STS_MWIDTH_MASK, XTG_CFG_STS_MWIDTH_SHIFT, XTG_CFG_STS_SWIDTH_MASK, XTG_CFG_STS_SWIDTH_SHIFT, XTG_MODE_BASIC, XTG_MODE_FULL, XTG_MODE_STATIC, XTG_MODE_STREAMING, XTG_MODE_SYS_INIT, XTrafGen_ReadConfigStatus.
Referenced by XTrafGenInterruptExample, XTrafGenPollingExample, XTrafGenStaticModeExample, XTrafGenStremingModeMasterExample.
int XTrafGen_AddCommand(XTrafGen *InstancePtr, XTrafGen_Cmd *CmdPtr)
Add a command to the software list of commands.
This function prepares the four Command Words and one Parameter Word from the Command structure passed from the user application. It then adds to a list of commands (maintained in the software). Both CMDRAM and PARAMRAM are divided into two regions, one for reads and one for writes. Each region can hold 256 commands with each entry containing four Command RAM words and one Parameter RAM word. InstancePtr is a pointer to the Axi TrafGen instance to be worked on. CmdPtr is a pointer to Command structure. XST_SUCCESS if successfulXST_FAILURE if reached max number of command entries
References XTrafGen_CmdInfo::CmdEntry, XTrafGen_CmdEntry::CmdWords, XTrafGen_Cmd::CRamCmd, XTrafGen_CmdInfo::LastRdValidIndex, XTrafGen_CmdInfo::LastWrValidIndex, MAX_NUM_ENTRIES, XTrafGen_CmdEntry::ParamWord, XTrafGen_CmdInfo::RdIndex, XTrafGen_CmdInfo::RdIndexEnd, XTrafGen_Cmd::RdWrFlag, XTrafGen_CRamCmd::ValidCmd, XTrafGen_CmdInfo::WrIndex, XTrafGen_CmdInfo::WrIndexEnd, XTG_WRITE, XTrafGen_GetCmdInfo.
Referenced by XTrafGenInterruptExample, XTrafGenPollingExample.
int XTrafGen_GetLastValidIndex(XTrafGen *InstancePtr, u32 RdWrFlag)
Get last Valid Command Index of Write/Read region.
The last valid command index is used to set 'my_depend' and 'other_depend' fields of the Command RAM (Word 2). InstancePtr is a pointer to the Axi TrafGen instance to be worked on. RdWrFlag specifies a Read or Write Region Last Valid Command Index
References XTrafGen_CmdInfo::LastRdValidIndex, XTrafGen_CmdInfo::LastWrValidIndex, XTG_WRITE, XTrafGen_GetCmdInfo.
Referenced by XTrafGenInterruptExample, XTrafGenPollingExample.
int XTrafGen_WriteCmdsToHw(XTrafGen *InstancePtr)
Write Commands to internal Command and Parameter RAMs.
This function writes all the prepared commands to hardware. InstancePtr is a pointer to the Axi TrafGen instance to be worked on. XST_SUCCESS if successful XST_FAILURE if programming internal RAMs failed
References NUM_BLOCKS.
Referenced by XTrafGenInterruptExample, XTrafGenPollingExample.
int XTrafGen_EraseAllCommands(XTrafGen *InstancePtr)
Erase all Command Entry values.
This function erases all the 256 entries of both write and read regions with each entry containing four command words and parameter word. InstancePtr is a pointer to the Axi TrafGen instance to be worked on. XST_SUCCESS if successful XST_FAILURE if programming internal RAMs failed
References XTrafGen_CmdInfo::CmdEntry, XTrafGen_CmdInfo::LastRdValidIndex, XTrafGen_CmdInfo::LastWrValidIndex, MAX_NUM_ENTRIES, NUM_BLOCKS, XTrafGen_CmdInfo::RdIndex, XTrafGen_CmdInfo::RdIndexEnd, XTrafGen_CmdInfo::WrIndex, XTrafGen_CmdInfo::WrIndexEnd, XTrafGen_GetCmdInfo.
void XTrafGen_AccessMasterRam(XTrafGen *InstancePtr, u32 Offset, int Length, u8 RdWrFlag, u32 *Data)
Write or Read Master RAM.
The MSTRAM has 8 KB of internal RAM used for the following: Take data from this RAM for write transactionsStore data to this RAM for read transaction InstancePtr is a pointer to the Axi TrafGen instance to be worked on. Offset is the offset value in Master RAM. Length is the size of data to write/read. RdWrFlag specifies whether to write or read Data is the pointer to array which contains data to write or reads data into.
References XTrafGen_Config::BaseAddress, XTrafGen::Config, XTG_MASTER_RAM_SIZE, XTG_WRITE, XTrafGen_ReadMasterRam, XTrafGen_WriteMasterRam.
Referenced by XTrafGenInterruptExample, XTrafGenPollingExample.
void XTrafGen_PrintCmds(XTrafGen *InstancePtr)
Display Command Entry values.
This function prints all the 256 entries of both write and read regions with each entry containing four command words and parameter word. InstancePtr is a pointer to the Axi TrafGen instance to be worked on.
References XTrafGen_CmdInfo::CmdEntry, XTrafGen_CmdEntry::CmdWords, MAX_NUM_ENTRIES, XTrafGen_CmdEntry::ParamWord, XTrafGen_GetCmdInfo.
Referenced by XTrafGenInterruptExample, XTrafGenPollingExample.
XTrafGen_Config * XTrafGen_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XTrafGen_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xtrafgen.h for the definition of XTrafGen_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XTrafGen_Config::Name.
Referenced by XTrafGenInterruptExample, XTrafGenPollingExample, XTrafGenStaticModeExample, XTrafGenStremingModeMasterExample.
XTrafGen_GetCmdInfo
Get Command Info pointer.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. Pointer to the Command Info structure C-style signature: XTrafGen_CmdInfo *XTrafGen_GetCmdInfo(XTrafGen *InstancePtr)
Referenced by XTrafGen_AddCommand, XTrafGen_EraseAllCommands, XTrafGen_GetLastValidIndex, XTrafGen_PrintCmds.
XTRAFGEN_H
MAX_NUM_ENTRIES
Number of command entries per region.
Referenced by XTrafGen_AddCommand, XTrafGen_EraseAllCommands, XTrafGen_PrintCmds.
NUM_BLOCKS
Number of Read and write regions.
Referenced by XTrafGen_EraseAllCommands, XTrafGen_WriteCmdsToHw.
XTG_WRITE
Write Direction Flag.
Referenced by XTrafGen_AccessMasterRam, XTrafGen_AddCommand, XTrafGen_GetLastValidIndex, XTrafGenInterruptExample, XTrafGenPollingExample.
XTG_READ
Read Direction Flag.
Referenced by XTrafGenInterruptExample, XTrafGenPollingExample.
XTG_MODE_FULL
Full Mode.
Referenced by XTrafGen_CfgInitialize.
XTG_MODE_BASIC
Basic Mode.
Referenced by XTrafGen_CfgInitialize.
XTG_MODE_STATIC
Static Mode.
Referenced by XTrafGen_CfgInitialize, XTrafGenStaticModeExample.
XTG_MODE_STREAMING
Streaming Mode.
Referenced by XTrafGen_CfgInitialize, XTrafGenStremingModeMasterExample.
XTG_MODE_SYS_INIT
System Init Mode.
Referenced by XTrafGen_CfgInitialize.
XTG_MWIDTH_32
Master Width - 32.
XTG_MWIDTH_64
Master Width - 64.
XTG_SWIDTH_32
Slave Width - 32.
XTG_SWIDTH_64
Slave Width - 64.
XTG_PRM_RAM_BLOCK_SIZE
PARAM Block Size (1KB)
XTG_CMD_RAM_BLOCK_SIZE
Cmd RAM Block Size (4KB)
XTG_EXTCMD_RAM_BLOCK_SIZE
Extended CMDRAM Block Size (1KB)
XTG_PARAM_RAM_SIZE
Parameter RAM (2KB)
XTG_COMMAND_RAM_SIZE
Command RAM (8KB)
XTG_MASTER_RAM_SIZE
Master RAM (8KB)
Referenced by XTrafGen_AccessMasterRam.
ERROR_INTRID
Error Interrupt Handler.
Referenced by XTrafGenInterruptExample.
MASTER_INTRID
Master Complete Interrupt Handler.
Referenced by XTrafGenInterruptExample.
XTrafGen_ReadCoreRevision
XTrafGen_ReadCoreRevision reads revision of core.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. Core Revision Value C-style signature: u8 XTrafGen_ReadCoreRevision(XTrafGen *InstancePtr)
XTrafGen_ReadIdWidth
XTrafGen_ReadIdWidth reads M_ID_WIDTH.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. Value of M_ID_WIDTH C-style signature: u8 XTrafGen_ReadIdWidth(XTrafGen *InstancePtr)
XTrafGen_StartMasterLogic
XTrafGen_StartMasterLogic starts traffic generator master logic.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. None C-style signature: void XTrafGen_StartMasterLogic(XTrafGen *InstancePtr)
Referenced by XTrafGenInterruptExample, XTrafGenPollingExample.
XTrafGen_IsMasterLogicDone
XTrafGen_IsMasterLogicDone checks for traffic generator master logic completed bit.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. TRUE if master logic completed. FALSE if master logic not completed. C-style signature: u8 XTrafGen_IsMasterLogicDone(XTrafGen *InstancePtr)
Referenced by XTrafGenPollingExample.
XTrafGen_LoopEnable
XTrafGen_LoopEnable loops through the command set created using CMDRAM and PARAMRAM indefinitely in Advanced mode/Basic mode of ATG.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. None C-style signature: void XTrafGen_LoopEnable(XTrafGen *InstancePtr)
XTrafGen_LoopDisable
XTrafGen_LoopDisable Disables the loop bit in Master control regiset in Advanced mode/Basic mode of ATG.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. None C-style signature: void XTrafGen_LoopDisable(XTrafGen *InstancePtr)
XTrafGen_WriteSlaveControlReg
XTrafGen_WriteSlaveControlReg enables control bits of Slave Control Register.
This API will write the value passed from the user. InstancePtr is a pointer to the Axi TrafGen instance to be worked on. Value is the Slave Control Register value to set None C-style signature: void XTrafGen_WriteSlaveControlReg(XTrafGen *InstancePtr, u32 Value)
XTrafGen_CheckforMasterComplete
XTrafGen_CheckforMasterComplete checks for master complete.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. TRUE if master complete bit is set. FALSE if master complete bit is not set. C-style signature: u8 XTrafGen_CheckforMasterComplete(XTrafGen *InstancePtr)
XTrafGen_ReadErrors
XTrafGen_ReadErrors read master and slave errors.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. Both Master and Slave error value. C-style signature: u32 XTrafGen_ReadErrors(XTrafGen *InstancePtr)
Referenced by XTrafGenPollingExample.
XTrafGen_EnableMasterCmpInterrupt
XTrafGen_EnableMasterCmpInterrupt enables Master logic complete bit.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. None. C-style signature: void XTrafGen_EnableMasterCmpInterrupt(XTrafGen *InstancePtr)
Referenced by XTrafGenInterruptExample.
XTrafGen_ClearMasterCmpInterrupt
XTrafGen_ClearMasterCmpInterrupt clear Master logic complete interrupt bit.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. None. C-style signature: u8 XTrafGen_ClearMasterCmpInterrupt(XTrafGen *InstancePtr)
XTrafGen_ClearErrors
XTrafGen_ClearErrors clear errors specified in Mask.
The corresponding error for each bit set to 1 in Mask, will be enabled. InstancePtr is a pointer to the Axi TrafGen instance to be worked on. Mask contains a bit mask of the errors to clear. The mask can be formed using a set of bit wise or'd values from the definitions in xtrafgen_hw.h file. None. C-style signature: void XTrafGen_ClearErrors(XTrafGen *InstancePtr, u32 Mask)
Referenced by XTrafGenPollingExample.
XTrafGen_EnableErrors
XTrafGen_EnableErrors enable errors specified in Mask.
The corresponding error for each bit set to 1 in Mask, will be enabled. InstancePtr is a pointer to the Axi TrafGen instance to be worked on. Mask contains a bit mask of the errors to enable. The mask can be formed using a set of bit wise or'd values from the definitions in xtrafgen_hw.h file. None. C-style signature: void XTrafGen_EnableErrors(XTrafGen *InstancePtr, u32 Mask)
XTrafGen_MasterErrIntrEnable
XTrafGen_MasterErrIntrEnable enables Global Master error bit.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. None C-style signature: void XTrafGen_MasterErrIntrEnable(XTrafGen *InstancePtr)
XTrafGen_MasterErrIntrDisable
XTrafGen_MasterErrIntrDisable disables Global Master error bit.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. None C-style signature: void XTrafGen_MasterErrIntrDisable(XTrafGen *InstancePtr)
XTrafGen_SlaveErrIntrEnable
XTrafGen_SlaveErrIntrEnable enables Global Slave error bit.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. None C-style signature: void XTrafGen_SlaveErrIntrEnable(XTrafGen *InstancePtr)
XTrafGen_SlaveErrIntrDisable
XTrafGen_SlaveErrIntrDisable disables Global Slave error bit.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. None C-style signature: void XTrafGen_SlaveErrIntrDisable(XTrafGen *InstancePtr)
XTrafGen_ReadConfigStatus
XTrafGen_ReadConfigStatus reads Config status register.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. Config Status Register value C-style signature: u32 XTrafGen_ReadConfigStatus(XTrafGen *InstancePtr)
Referenced by XTrafGen_CfgInitialize.
XTrafGen_StaticEnable
XTrafGen_StaticEnable enable the traffic generation when the core is configured Static Mode.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. None. C-style signature: void XTrafGen_StaticEnable(XTrafGen *InstancePtr)
Referenced by XTrafGenStaticModeExample.
XTrafGen_StaticDisable
XTrafGen_StaticDisable disables the traffic generation on the Axi TrafGen when the core is configured in Static Mode.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. None. C-style signature: void XTrafGen_StaticDisable(XTrafGen *InstancePtr)
Referenced by XTrafGenStaticModeExample.
XTrafGen_StaticVersion
XTrafGen_StaticVersion returns the version value for the Axi TrafGen When configured in Static Mode.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. Static version value. C-style signature: u32 XTrafGen_StaticVersion(XTrafGen *InstancePtr)
XTrafGen_SetStaticBurstLen
XTrafGen_SetStaticBurstLen Configures the Burst Length for AxiTrafGen In Static Mode.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. Value is the Burst length to set in the Static length register. None. C-style signature: void XTrafGen_SetStaticBurstLen(XTrafGen *InstancePtr, u32 Value)
Referenced by XTrafGenStaticModeExample.
XTrafGen_GetStaticBurstLen
XTrafGen_GetStaticBurstLen Gets the Burst Length for AxiTrafGen in StaticMode.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. Burst length value. C-style signature: u32 XTrafGen_GetStaticBurstLen(XTrafGen *InstancePtr)
XTrafGen_GetStaticTransferDone
XTrafGen_GetStaticTransferDone gets the state of Transfer done bit in Control register When the TraficGen is configured in Static Mode.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. Value of the Transfer Done bit. C-style signature: u32 XTrafGen_GetStaticTransferDone(XTrafGen *InstancePtr)
Referenced by XTrafGenStaticModeExample.
XTrafGen_SetStaticTransferDone
XTrafGen_SetStaticTransferDone sets the Transfer done bit in Control register When AxiTrafGen is Configured in Static Mode.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. None. C-style signature: void XTrafGen_SetStaticTransferDone(XTrafGen *InstancePtr)
Referenced by XTrafGenStaticModeExample.
XTrafGen_IsStaticTransferDone
XTrafGen_IsStaticTransferDone checks for reset value When Static Traffic generation Completed by reading Control Register.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. TRUE if reset Success full FALSE if failed to reset C-style signature: u8 XTrafGen_IsStaticTransferDone(XTrafGen *InstancePtr)
Referenced by XTrafGenStaticModeExample.
XTrafGen_StreamEnable
XTrafGen_StreamEnable enable the traffic generation on the Axi TrafGen When the core is configured in Streaming Mode.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. None. C-style signature: void XTrafGen_StreamEnable(XTrafGen *InstancePtr)
Referenced by XTrafGenStremingModeMasterExample.
XTrafGen_StreamDisable
XTrafGen_StreamDisable Disable the traffic generation on the Axi TrafGen When core is configured in Streaming Mode.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. None. C-style signature: void XTrafGen_StreamDisable(XTrafGen *InstancePtr)
XTrafGen_StreamVersion
XTrafGen_StreamVersion returns the version value for the Axi TrafGen When configured in Streaming Mode.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. Streaming Version Value. C-style signature: u8 XTrafGen_StreamVersion(XTrafGen *InstancePtr)
XTrafGen_SetStreamingTransLen
XTrafGen_SetStreamingTransLen Configures the length of transaction for AxiTrafGen in Streaming Mode.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. Value is the transfer length to set in the transfer length Register. None. C-style signature: void XTrafGen_SetStreamingTransLen(XTrafGen *InstancePtr, u32 Value)
Referenced by XTrafGenStremingModeMasterExample.
XTrafGen_GetStreamingTransLen
XTrafGen_GetStreamingTransLen Gets the length of transaction for AxiTrafGen in Streaming Mode.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. Transfer Length value. C-style signature: u16 XTrafGen_GetStreamingTransLen(XTrafGen *InstancePtr)
Referenced by XTrafGenStremingModeMasterExample.
XTrafGen_GetStreamingTransCnt
XTrafGen_GetStreamingTransCnt Gets the transfer count for AxiTrafGen in Streaming Mode.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. Transfer Count value. C-style signature: u16 XTrafGen_GetStreamingTransCnt(XTrafGen *InstancePtr)
Referenced by XTrafGenStremingModeMasterExample.
XTrafGen_SetStreamingRandomLen
XTrafGen_SetStreamingRandomLen Configures the random transaction length for AxiTrafGen in Streaming Mode.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. Value is the random length that's need to be Configure in the Streaming Config register. None. C-style signature: void XTrafGen_SetStreamingRandomLen(XTrafGen *InstancePtr, u32 Value)
XTrafGen_GetStreamingProgDelay
XTrafGen_GetStreamingProgDelay Gets the Programmable Delay for AxiTrafGen in Streaming Mode.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. Propagation Delay Value C-style signature: u16 XTrafGen_GetProgDelay(XTrafGen *InstancePtr)
XTrafGen_SetStreamingTransCnt
XTrafGen_SetStreamingTransCnt Configures the transfer count for AxiTrafGen in Streaming Mode.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. Value is the transfer length that needs to be configured in Transfer length register. None. C-style signature: void XTrafGen_SetStreamingTransCnt(XTrafGen *InstancePtr, u32 Value)
Referenced by XTrafGenStremingModeMasterExample.
XTrafGen_SetStreamingProgDelay
XTrafGen_SetStreamingProgDelay Configures the Programmable Delay for AxiTrafGen in Streaming Mode.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. Value is the value that's need to be configure in the Stream Config Register. None. C-style signature: void XTrafGen_SetStreamingProgDelay(XTrafGen *InstancePtr, u32 Value)
XTrafGen_SetStreamingTdestPort
XTrafGen_SetStreamingTdestPort Configures the Value to drive on TDEST port for Axi TrafGen in Streaming Mode.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. Value is the Port value that's need to be set. None. C-style signature: void XTrafGen_SetStreamingTdestPort(XTrafGen *InstancePtr, u8 Value)
XTrafGen_SetStreamingTransferDone
XTrafGen_SetTransferDone sets the Transfer done bit in Control register When AxiTrafGen is Configured in Streaming Mode.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. None. C-style signature: void XTrafGen_SetStreamingTransferDone(XTrafGen *InstancePtr)
XTrafGen_IsStreamingTransferDone
XTrafGen_IsStreamingTransferDone checks for reset value When Streaming Traffic generation is Completed by reading Stream Control Register.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. TRUE if reset Success full FALSE if failed to reset C-style signature: u8 XTrafGen_IsStreamingTransferDone(XTrafGen *InstancePtr)
XTrafGen_ResetStreamingRandomLen
XTrafGen_ResetStreamingRandomLen resets the random transaction length for AxiTrafGen in Streaming Mode.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. None. C-style signature: void XTrafGen_ResetStreamingRandomLen(XTrafGen *InstancePtr)
Referenced by XTrafGenStremingModeMasterExample.
XTRAFGEN_HW_H