xtrafgen_sinit.c
XTrafGen_Config * XTrafGen_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XTrafGen_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xtrafgen.h for the definition of XTrafGen_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XTrafGen_Config::Name.
Referenced by XTrafGenInterruptExample, XTrafGenPollingExample, XTrafGenStaticModeExample, XTrafGenStremingModeMasterExample.