xtrafgen.c
XTrafGen_GetCmdInfo
Get Command Info pointer.
InstancePtr is a pointer to the Axi TrafGen instance to be worked on. Pointer to the Command Info structure C-style signature: XTrafGen_CmdInfo *XTrafGen_GetCmdInfo(XTrafGen *InstancePtr)
Referenced by XTrafGen_AddCommand, XTrafGen_EraseAllCommands, XTrafGen_GetLastValidIndex, XTrafGen_PrintCmds.
static void XTrafGen_PrepCmdWords(XTrafGen *InstancePtr, XTrafGen_Cmd *CmdPtr, u32 *CmdWords)
Prepares all the four Command RAM Words.
The CMDRAM is divided into two 4 KB regions, one for reads and one for writes. Each region of CMDRAM can hold 256 commands each of 128 bits i.e. Four command words each of size 32 bits. This function prepares these command words from the user specified configuration. InstancePtr is a pointer to the Axi TrafGen instance to be worked on. CmdPtr is a pointer to Command structure. CmdWords is a pointer to an array of four command words.
static void XTrafGen_PrepParamWord(XTrafGen *InstancePtr, XTrafGen_Cmd *CmdPtr, u32 *ParamWord)
Prepares Parameter RAM Word.
The PARAMRAM extends the command programmability provided through command RAM, by adding extra 32 bits to the decode of each command. This function prepares this 32 bit Parameter RAM word. InstancePtr is a pointer to the Axi TrafGen instance to be worked on. CmdPtr is a pointer to Command structure. ParamWord is a pointer to an value of Parameter RAM word.
static int XTrafGen_ProgramCmdRam(XTrafGen *InstancePtr, u8 RdWrFlag)
Program Command RAM.
This function write the list of Command Words prepared by using *_AddCommand() to Command RAM till the last command entry added. InstancePtr is a pointer to the Axi TrafGen instance to be worked on. RdWrFlag specifies Read or Write Region XST_SUCCESS if successfulXST_FAILURE if no valid commands present
static int XTrafGen_ProgramParamRam(XTrafGen *InstancePtr, u8 RdWrFlag)
Program Parameter RAM.
This function write the list of Parameter Words prepared by using *_AddCommand() to Parameter RAM till the last command entry added. InstancePtr is a pointer to the Axi TrafGen instance to be worked on. RdWrFlag specifies Read or Write Region XST_SUCCESS if successfulXST_FAILURE if no valid commands present
int XTrafGen_CfgInitialize(XTrafGen *InstancePtr, XTrafGen_Config *Config, UINTPTR EffectiveAddress)
This function initializes a AXI Traffic Generator device.
This function must be called prior to using a AXI Traffic Generator Device. Initializing a engine includes setting up the register base address, setting up the instance data, and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the Axi Traffic Generator instance to be worked on. CfgPtr references the structure holding the hardware configuration for the Axi Traffic Generator core to initialize. EffectiveAddr is the device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, use Config->BaseAddress for this parameters, passing the physical address instead. XST_SUCCESS for successful initializationXST_INVALID_PARAM if pointer to the configuration structure is NULL
References XTrafGen_Config::AddressWidth, XTrafGen_Config::BaseAddress, XTrafGen_Config::BusType, XTrafGen::CmdInfo, XTrafGen::Config, XTrafGen_Config::IntId, XTrafGen_Config::IntrParent, XTrafGen::IsReady, XTrafGen_CmdInfo::LastRdValidIndex, XTrafGen_CmdInfo::LastWrValidIndex, XTrafGen::MasterWidth, XTrafGen_Config::Mode, XTrafGen_Config::ModeType, XTrafGen::OperatingMode, XTrafGen::SlaveWidth, XTG_CFG_STS_MBASIC_MASK, XTG_CFG_STS_MFULL_MASK, XTG_CFG_STS_MWIDTH_MASK, XTG_CFG_STS_MWIDTH_SHIFT, XTG_CFG_STS_SWIDTH_MASK, XTG_CFG_STS_SWIDTH_SHIFT, XTG_MODE_BASIC, XTG_MODE_FULL, XTG_MODE_STATIC, XTG_MODE_STREAMING, XTG_MODE_SYS_INIT, XTrafGen_ReadConfigStatus.
Referenced by XTrafGenInterruptExample, XTrafGenPollingExample, XTrafGenStaticModeExample, XTrafGenStremingModeMasterExample.
int XTrafGen_AddCommand(XTrafGen *InstancePtr, XTrafGen_Cmd *CmdPtr)
Add a command to the software list of commands.
This function prepares the four Command Words and one Parameter Word from the Command structure passed from the user application. It then adds to a list of commands (maintained in the software). Both CMDRAM and PARAMRAM are divided into two regions, one for reads and one for writes. Each region can hold 256 commands with each entry containing four Command RAM words and one Parameter RAM word. InstancePtr is a pointer to the Axi TrafGen instance to be worked on. CmdPtr is a pointer to Command structure. XST_SUCCESS if successfulXST_FAILURE if reached max number of command entries
References XTrafGen_CmdInfo::CmdEntry, XTrafGen_CmdEntry::CmdWords, XTrafGen_Cmd::CRamCmd, XTrafGen_CmdInfo::LastRdValidIndex, XTrafGen_CmdInfo::LastWrValidIndex, MAX_NUM_ENTRIES, XTrafGen_CmdEntry::ParamWord, XTrafGen_CmdInfo::RdIndex, XTrafGen_CmdInfo::RdIndexEnd, XTrafGen_Cmd::RdWrFlag, XTrafGen_CRamCmd::ValidCmd, XTrafGen_CmdInfo::WrIndex, XTrafGen_CmdInfo::WrIndexEnd, XTG_WRITE, XTrafGen_GetCmdInfo.
Referenced by XTrafGenInterruptExample, XTrafGenPollingExample.
int XTrafGen_GetLastValidIndex(XTrafGen *InstancePtr, u32 RdWrFlag)
Get last Valid Command Index of Write/Read region.
The last valid command index is used to set 'my_depend' and 'other_depend' fields of the Command RAM (Word 2). InstancePtr is a pointer to the Axi TrafGen instance to be worked on. RdWrFlag specifies a Read or Write Region Last Valid Command Index
References XTrafGen_CmdInfo::LastRdValidIndex, XTrafGen_CmdInfo::LastWrValidIndex, XTG_WRITE, XTrafGen_GetCmdInfo.
Referenced by XTrafGenInterruptExample, XTrafGenPollingExample.
int XTrafGen_WriteCmdsToHw(XTrafGen *InstancePtr)
Write Commands to internal Command and Parameter RAMs.
This function writes all the prepared commands to hardware. InstancePtr is a pointer to the Axi TrafGen instance to be worked on. XST_SUCCESS if successful XST_FAILURE if programming internal RAMs failed
References NUM_BLOCKS.
Referenced by XTrafGenInterruptExample, XTrafGenPollingExample.
int XTrafGen_EraseAllCommands(XTrafGen *InstancePtr)
Erase all Command Entry values.
This function erases all the 256 entries of both write and read regions with each entry containing four command words and parameter word. InstancePtr is a pointer to the Axi TrafGen instance to be worked on. XST_SUCCESS if successful XST_FAILURE if programming internal RAMs failed
References XTrafGen_CmdInfo::CmdEntry, XTrafGen_CmdInfo::LastRdValidIndex, XTrafGen_CmdInfo::LastWrValidIndex, MAX_NUM_ENTRIES, NUM_BLOCKS, XTrafGen_CmdInfo::RdIndex, XTrafGen_CmdInfo::RdIndexEnd, XTrafGen_CmdInfo::WrIndex, XTrafGen_CmdInfo::WrIndexEnd, XTrafGen_GetCmdInfo.
void XTrafGen_AccessMasterRam(XTrafGen *InstancePtr, u32 Offset, int Length, u8 RdWrFlag, u32 *Data)
Write or Read Master RAM.
The MSTRAM has 8 KB of internal RAM used for the following: Take data from this RAM for write transactionsStore data to this RAM for read transaction InstancePtr is a pointer to the Axi TrafGen instance to be worked on. Offset is the offset value in Master RAM. Length is the size of data to write/read. RdWrFlag specifies whether to write or read Data is the pointer to array which contains data to write or reads data into.
References XTrafGen_Config::BaseAddress, XTrafGen::Config, XTG_MASTER_RAM_SIZE, XTG_WRITE, XTrafGen_ReadMasterRam, XTrafGen_WriteMasterRam.
Referenced by XTrafGenInterruptExample, XTrafGenPollingExample.
void XTrafGen_PrintCmds(XTrafGen *InstancePtr)
Display Command Entry values.
This function prints all the 256 entries of both write and read regions with each entry containing four command words and parameter word. InstancePtr is a pointer to the Axi TrafGen instance to be worked on.
References XTrafGen_CmdInfo::CmdEntry, XTrafGen_CmdEntry::CmdWords, MAX_NUM_ENTRIES, XTrafGen_CmdEntry::ParamWord, XTrafGen_GetCmdInfo.
Referenced by XTrafGenInterruptExample, XTrafGenPollingExample.