xtmr_manager_sinit.c
XTMR_Manager_Config * XTMR_Manager_LookupConfig(UINTPTR BaseAddr)
int XTMR_Manager_Initialize(XTMR_Manager *InstancePtr, UINTPTR BaseAddr)
Initialize a XTMR_Manager instance.
The receive and transmit FIFOs of the core are not flushed, so the user may want to flush them. The hardware device does not have any way to disable the receiver such that any valid data may be present in the receive FIFO. This function disables the core interrupt. The baudrate and format of the data are fixed in the hardware at hardware build time. InstancePtr is a pointer to the XTMR_Manager instance. DeviceId is the unique id of the device controlled by this XTMR_Manager instance. Passing in a device id associates the generic XTMR_Manager instance to a specific device, as chosen by the caller or application developer. XST_SUCCESS if everything starts up as expected.XST_DEVICE_NOT_FOUND if the device is not found in the configuration table. None.
References XTMR_Manager_Config::RegBaseAddr, XTMR_Manager_CfgInitialize.
Referenced by TMR_ManagerIntrExample, TMR_ManagerPolledExample, TMR_ManagerRecoveryExample, TMR_ManagerSelfTestExample.