xtmr_manager.h
XTMR_MANAGER_H
typedef void(* XTMR_Manager_Handler)(void *CallBackRef))(void *CallBackRef)
Callback function.
The first argument is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked.
int XTMR_Manager_Initialize(XTMR_Manager *InstancePtr, UINTPTR BaseAddr)
Initialize a XTMR_Manager instance.
The receive and transmit FIFOs of the core are not flushed, so the user may want to flush them. The hardware device does not have any way to disable the receiver such that any valid data may be present in the receive FIFO. This function disables the core interrupt. The baudrate and format of the data are fixed in the hardware at hardware build time. InstancePtr is a pointer to the XTMR_Manager instance. DeviceId is the unique id of the device controlled by this XTMR_Manager instance. Passing in a device id associates the generic XTMR_Manager instance to a specific device, as chosen by the caller or application developer. XST_SUCCESS if everything starts up as expected.XST_DEVICE_NOT_FOUND if the device is not found in the configuration table. None.
References XTMR_Manager_Config::RegBaseAddr, XTMR_Manager_CfgInitialize.
Referenced by TMR_ManagerIntrExample, TMR_ManagerPolledExample, TMR_ManagerRecoveryExample, TMR_ManagerSelfTestExample.
XTMR_Manager_Config * XTMR_Manager_LookupConfig(UINTPTR BaseAddr)
int XTMR_Manager_CfgInitialize(XTMR_Manager *InstancePtr, XTMR_Manager_Config *Config, UINTPTR EffectiveAddr)
Initialize a XTMR_Manager instance.
The receive and transmit FIFOs of the core are not flushed, so the user may want to flush them. The hardware device does not have any way to disable the receiver such that any valid data may be present in the receive FIFO. This function disables the core interrupt. The baudrate and format of the data are fixed in the hardware at hardware build time. InstancePtr is a pointer to the XTMR_Manager instance. Config is a reference to a structure containing information about a specific TMR Manager device. This function initializes an InstancePtr object for a specific device specified by the contents of Config. This function can initialize multiple instance objects with the use of multiple calls giving different Config information on each call. EffectiveAddr is the device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, use Config->BaseAddress for this parameters, passing the physical address instead. XST_SUCCESS if everything starts up as expected. The Config pointer argument is not used by this function, but is provided to keep the function signature consistent with other drivers.
References XTMR_Manager_Config::BrkDelayRstValue, XTMR_Manager_Config::BrkDelayWidth, XTMR_Manager_Config::ComparatorsMask, XTMR_Manager_Config::Magic1, XTMR_Manager_Config::MaskRstValue, XTMR_Manager_Config::SemInterface, XTMR_Manager_Config::TestComparator, XTMR_Manager_ClearStats, XTMR_Manager_WriteReg.
Referenced by XTMR_Manager_Initialize.
void XTMR_Manager_Configure_BrkDelay(XTMR_Manager *InstancePtr, u32 BrkDelay)
void XTMR_Manager_SetRecoveryHandler(XTMR_Manager *InstancePtr, XTMR_Manager_Handler FuncPtr, void *CallBackRef)
Set the user recovery handler, which can replace the pre-defined handler completely, to do custom recovery.
InstancePtr is a pointer to the XTMR_Manager instance. This function is run in interrupt context.
void XTMR_Manager_SetPreResetHandler(XTMR_Manager *InstancePtr, XTMR_Manager_Handler FuncPtr, void *CallBackRef)
Set the user pre-reset handler, which can be used to save context before reset in a recovery sequence.
InstancePtr is a pointer to the XTMR_Manager instance. This function is run in interrupt context.
Referenced by TMR_ManagerRecoveryExample.
void XTMR_Manager_SetPostResetHandler(XTMR_Manager *InstancePtr, XTMR_Manager_Handler FuncPtr, void *CallBackRef)
Set the user post-reset handler, which can be used to restore context after reset in a recovery sequence.
InstancePtr is a pointer to the XTMR_Manager instance. None.
void XTMR_Manager_RestartWdt(XTMR_Manager *InstancePtr)
u32 XTMR_Manager_IsWdtExpired(XTMR_Manager *InstancePtr)
void XTMR_Manager_GetStats(XTMR_Manager *InstancePtr, XTMR_Manager_Stats *StatsPtr)
Returns a snapshot of the current statistics in the structure specified.
InstancePtr is a pointer to the XTMR_Manager instance. StatsPtr is a pointer to a XTMR_ManagerStats structure to where the statistics are to be copied. None. None.
References XTMR_Manager_Stats::InterruptCount, XTMR_Manager_Stats::RecoveryCount.
void XTMR_Manager_ClearStats(XTMR_Manager *InstancePtr)
This function zeros the statistics for the given instance.
InstancePtr is a pointer to the XTMR_Manager instance. None. None.
References XTMR_Manager_Stats::InterruptCount, XTMR_Manager_Stats::RecoveryCount.
Referenced by XTMR_Manager_CfgInitialize.
void XTMR_Manager_SemCommand(XTMR_Manager *InstancePtr, char *command, char *response)
void XTMR_Manager_EnableInterrupt(XTMR_Manager *InstancePtr, u32 Mask)
This function enables the core interrupt such that an interrupt will occur when any of the SEM status signals indicated by the mask are changed.
This function enables the core interrupt such that an interrupt will occur when an unmasked SEM status input changes value. InstancePtr is a pointer to the XTMR_Manager instance. Mask is a mask indicating bits that should give an interrupt. None. None. InstancePtr is a pointer to the XTMR_Manager instance. None. None.
References XTMR_Manager_WriteReg.
Referenced by TMR_ManagerIntrExample.
void XTMR_Manager_DisableInterrupt(XTMR_Manager *InstancePtr)
This function disables the core interrupt.
After calling this function, data may still be received by the core but no interrupt will be generated since the hardware device has no way to disable the receiver. InstancePtr is a pointer to the XTMR_Manager instance. None. None.
References XTMR_Manager_WriteReg.
void XTMR_Manager_SetHandler(XTMR_Manager *InstancePtr, XTMR_Manager_Handler FuncPtr, void *CallBackRef)
This function sets the handler that will be called when an event (interrupt) occurs in the driver.
The purpose of the handler is to allow application specific processing to be performed. InstancePtr is a pointer to the XTMR_Manager instance. FuncPtr is the pointer to the callback function. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. None. There is no assert on the CallBackRef since the driver doesn't know what it is (nor should it) The purpose of the handler is to allow application specific processing to be performed. InstancePtr is a pointer to the XTMR_Manager instance . FuncPtr is the pointer to the callback function. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. None. There is no assert on the CallBackRef since the driver doesn't know what it is (nor should it)
int XTMR_Manager_SelfTest(XTMR_Manager *InstancePtr)
Runs a self-test on the device hardware.
Since there is no way to perform a loopback in the hardware, this test can only check the state of the status register to verify it is correct. This test assumes that the hardware device is still in its reset state, but has been initialized with the Initialize function. InstancePtr is a pointer to the XTMR_Manager instance. XST_SUCCESS if the self-test was successful.XST_FAILURE if the self-test failed, the status register value was not correct None.
References XTMR_Manager_ReadReg.
Referenced by TMR_ManagerIntrExample, TMR_ManagerPolledExample, TMR_ManagerRecoveryExample, TMR_ManagerSelfTestExample.