xtmr_manager_selftest.c
int XTMR_Manager_SelfTest(XTMR_Manager *InstancePtr)
Runs a self-test on the device hardware.
Since there is no way to perform a loopback in the hardware, this test can only check the state of the status register to verify it is correct. This test assumes that the hardware device is still in its reset state, but has been initialized with the Initialize function. InstancePtr is a pointer to the XTMR_Manager instance. XST_SUCCESS if the self-test was successful.XST_FAILURE if the self-test failed, the status register value was not correct None.
References XTMR_Manager_ReadReg.
Referenced by TMR_ManagerIntrExample, TMR_ManagerPolledExample, TMR_ManagerRecoveryExample, TMR_ManagerSelfTestExample.