xilskey_jscmd.h
JPROGRAM
< Constant definitions for instruction used in BBRAM key program and verify
ISC_NOOP
ISC_ENABLE
ISC_PROGRAM_KEY
ISC_PROGRAM
ISC_READ
ISC_DISABLE
BYPASS
SYSMON_DRP
CFG_OUT_SLRX
CFG_IN_SLRX
ISC_ENABLE_SLRX
ISC_PROGRAM_SLRX
XSC_PROGRAM_SLRX
ISC_READ_SLRX
FEEDTHROUGH
FUSE_CTS_SLRX
FUSE_KEY_SLRX
IRHEADER
< Pre and post pads definitions
IRTRAILER
DRHEADER
DRTRAILER
IRHEADER_BYP
< Pre and post pads for BYPASS in de-init definitions
IRTRAILER_BYP
DRHEADER_BYP
DRTRAILER_BYP
DR_EN
< Data register load after ISC_ENABLE definitions
CALC_SINGLE
CALC_ALL
CALC_MSTR
MIO_TDI
< MIO assignments definitions
MIO_TDO
MIO_TCK
MIO_TMS
MIO_MUX_SELECT
GPIO_TDI
< GPIO JTAG register definitions
GPIO_TDO
GPIO_TMS
GPIO_TCK
GPIO_HWM_START
< GPIO HWM register definitions
GPIO_HWM_READY
GPIO_HWM_END
TAP_IR_LENGTH
< IR length register definitions
ZYNQ_DAP_IR_LENGTH
ATOMIC_DR_SCAN
< ATOMIC scan for IR and DR
ATOMIC_IR_SCAN
GPIO_BASE_ADDR
< GPIO register offsets and definition
GPIO_MASK_VAL
GPIO_TDI_VAL
GPIO_TDO_VAL
GPIO_TCK_VAL
GPIO_TMS_VAL
GPIO_MUX_SEL_VAL
js_server_t* js_init_zynq(void)
< Prototype declarations for Xilskey jscmd APIs
References open_port.
Referenced by JtagServerInit, JtagServerInitBbram.
void initGPIO(void)
int jtag_setPreAndPostPads(js_port_t *port_arg, int irPrePadBits, int irPostPadBits, int drPrePadBits, int drPostPadBits)
This function sets Jtag Pre and Post Pads.
status value
Referenced by JtagWrite, JtagRead, Bbram_Init, Bbram_ProgramKey, Bbram_VerifyKey, Bbram_DeInit.
int jtag_navigate(js_port_t *port, js_state_t state)
This function performs Jtag navigate operation.
status value
References js_port_struct::root_node.
Referenced by open_port, JtagWrite, JtagRead, Bbram_Init, Bbram_ProgramKey, Bbram_VerifyKey, Bbram_DeInit, Jtag_Read_Sysmon, JtagWrite_Ultrascale, JtagRead_Ultrascale, JtagRead_Status_Ultrascale, JtagAES_Check_Ultrascale, Bbram_Close_Ultra.
int jtag_shift(js_port_t *port, unsigned char mode, int bits, unsigned char *wrBuffer, unsigned char *rdBuffer, js_state_t state)
This function takes care of padding Must be set up with pre/post ir/dr info.
status value
References js_port_struct::root_node, getByteCountFromBitCount.
Referenced by JtagWrite, JtagRead, Bbram_Init, Bbram_ProgramKey, Bbram_VerifyKey, Bbram_DeInit, Jtag_Read_Sysmon, JtagWrite_Ultrascale, JtagRead_Ultrascale, JtagRead_Status_Ultrascale, JtagAES_Check_Ultrascale, Bbram_Close_Ultra.
ZUPLUS_PL_IDCODE
zu+ pl_idcode instruction
DRLENGTH_FUSE
Data register length for fuse_cts.
DRLENGTH_PROGRAM
Data register lengths for program.
DRLENGTH_VERIFY
Data register lengths for verify.
DRLENGTH_EN
Data register lengths for data load after ISC_ENABLE.
XSK_EFUSEPL_GPIO_CH1
GPIO channel numbers of Ultrascale.
GPIO channel 1
XSK_EFUSEPL_GPIO_CH2
GPIO channel 2.
XSK_GPIO_PIN_MAX
Maximum valid GPIO number.
Maximum valid gpio pin number
XilSKey_ModuleSelection
For eFUSE.
unsigned int g_mio_jtag_tdi
unsigned int g_mio_jtag_tdo
unsigned int g_mio_jtag_tck
unsigned int g_mio_jtag_tms
unsigned int g_mio_jtag_mux_sel
unsigned int g_mux_sel_def_val
u32 GpioPinMasterJtagTDI
u32 GpioPinMasterJtagTDO
u32 GpioPinMasterJtagTMS
u32 GpioPinMasterJtagTCK
u32 GpioPinHwmStart
u32 GpioPinHwmEnd
u32 GpioPinHwmReady
u32 GpioInPutCh
u32 GpioOutPutCh
u32 GpioDeviceId