xilskey_efuse_example.c
REBOOT_STATUS_REG_ADDR
Address for the Reboot Status Register.
Referenced by main.
XSK_EFUSEPL_USER_KEY_SIZE_IN_BITS
user key size in bits
XSK_EFUSEPL_RSA_KEY_HASH_STRING_SIZE
PL eFUSE RSA key size in characters.
XSK_EFUSEPL_RSA_KEY_SIZE_IN_BITS
RSA Key size in Bytes.
XSK_EFUSEPL_USER_KEY_STRING_SIZE
PL eFuse user key size in characters.
XSK_EFUSEPS_STATUS_WP_BIT_LOW
XSK_EFUSEPS_STATUS_WP_BIT_HIGH
XSK_EFUSEPS_STATUS_RSA_EN
XSK_EFUSEPS_STATUS_ROM_128_CRC
XSK_EFUSEPS_STATUS_DFT_JTAG_DISABLE
XSK_EFUSEPS_STATUS_DFT_MODE_DISABLE
XSK_EFUSEPL_STATUS_FORCE_PCYCLE_RECONFIG
XSK_EFUSEPL_STATUS_DISABLE_KEY_WRITE
XSK_EFUSEPL_STATUS_DISABLE_AES_KEY_READ
XSK_EFUSEPL_STATUS_DISABLE_USER_KEY_READ
XSK_EFUSEPL_STATUS_DISABLE_FUSE_CNTRL_WRITE
XSK_EFUSEPL_STATUS_EFUSE_SEC_ENABLE
XSK_EFUSEPL_STATUS_JTAG_DISABLE
XSK_EFUSEPL_STATUS_BBRAM_KEY_DISABLE
XilSKey_EPl PlInstance
u32 XilSKey_Efuse_ConvertStringToHexLE(const char *Str, u8 *Buf, u32 Len)
Function used to convert the string to Hex in Little Endian format.
Function used to convert the string to Hex in Little Endian format. Ex: "abc123" -> {0x23, 0xc1, 0xab} Str is a Input String. Will support the lower and upper case values. Value should be between 0-9, a-f and A-F Buf is Output buffer. Len of the input string in bits and it should have even values XST_SUCCESS no errors occurred. XST_FAILURE an error when input parameters are not validan error when input buffer has invalid values TDD Test Cases: Initialization Len is odd Len is zero Str is NULL Buf is NULL Functionality Str input with only numbers Str input with All values in A-F Str input with All values in a-f Str input with values in a-f, 0-9, A-F Str input with values in a-z, 0-9, A-Z Boundary Cases Memory Bounds of buffer checking
References XSK_EFUSEPS_ERROR_INVALID_PARAM, XSK_EFUSEPS_ERROR_PARAMETER_NULL, XSK_EFUSEPS_ERROR_STRING_INVALID.
Referenced by main, XilSKey_EfusePl_InitData.
u32 XilSKey_Efuse_ConvertStringToHexBE(const char *Str, u8 *Buf, u32 Len)
Function used to convert the string to Hex in Little Endian format.
Function used to convert the string to Hex in Little Endian format. Ex: "abc123" -> {0xab, 0xc1, 0x23} Str is a Input String. Will support the lower and upper case values. Value should be between 0-9, a-f and A-F Buf is Output buffer. Len of the input string in bits and it should have even values XST_SUCCESS no errors occurred. XST_FAILURE an error when input parameters are not validan error when input buffer has invalid values TDD Test Cases: Initialization Len is odd Len is zero Str is NULL Buf is NULL Functionality Str input with only numbers Str input with All values in A-F Str input with All values in a-f Str input with values in a-f, 0-9, A-F Str input with values in a-z, 0-9, A-Z Boundary Cases Memory Bounds of buffer checking
References XSK_EFUSEPS_ERROR_INVALID_PARAM, XSK_EFUSEPS_ERROR_PARAMETER_NULL, XSK_EFUSEPS_ERROR_STRING_INVALID.
Referenced by XilSKey_Bbram_InitData, XilSKey_CrcCalculation, XilSKey_EfusePs_InitData.
u32 XilSKey_Efuse_ValidateKey(const char *Key, u32 Len)
Function used to validate the AES & RSA key provided as input.
Function used to validate the AES & RSA key provided as input. Key - Hash Key Len - Valid length of key XST_SUCCESS - In case of Success XST_FAILURE - In case of Failure
References XilSKey_Efuse_IsValidChar, XSK_EFUSEPL_ERROR_KEY_VALIDATION, XSK_EFUSEPL_ERROR_NONE, XSK_EFUSEPL_ERROR_NOT_VALID_KEY_CHAR, XSK_EFUSEPL_ERROR_NOT_VALID_KEY_LENGTH.
Referenced by XilSKey_EfusePl_InitData, XilSKey_EfusePs_InitData.
u32 XilSKey_EfusePs_InitData(XilSKey_EPs *PsInstancePtr)
Helper functions to properly initialize the PS eFUSE structure instance.
PsInstancePtr - Structure Address to update the structure elements - XST_SUCCESS - In case of Success - XST_FAILURE - If initialization fails
References XilSKey_Efuse_ConvertStringToHexBE, XilSKey_Efuse_ValidateKey, XSK_EFUSEPS_DISABLE_DFT_JTAG, XSK_EFUSEPS_DISABLE_DFT_MODE, XSK_EFUSEPS_ENABLE_ROM_128K_CRC, XSK_EFUSEPS_ENABLE_RSA_AUTH, XSK_EFUSEPS_ENABLE_RSA_KEY_HASH, XSK_EFUSEPS_ENABLE_WRITE_PROTECT.
Referenced by main.
u32 XilSKey_EfusePl_InitData(XilSKey_EPl *PlInstancePtr)
Helper functions to validate the keys to be written.
PlInstancePtr - Structure Address to update the structure elements SlrNum - Number to differentiate the data targeted to specific SLR - XST_SUCCESS - In case of Success - Error - If initialization fails Helper functions to properly initialize the PL eFUSE structure instance PlInstancePtr - Structure Address to update the structure elements - XST_SUCCESS - In case of Success - XST_FAILURE - If initialization fails
References XilSKey_EPl::AESKey, XilSKey_EPl::AESKeyExclusive, XilSKey_EPl::AESKeyRead, XilSKey_EPl::CheckAESKeyUltra, XilSKey_EPl::CtrlWrite, XilSKey_EPl::DecoderDisable, XilSKey_EPl::EncryptOnly, XilSKey_EPl::ForcePowerCycle, XilSKey_EPl::FuseObfusEn, XilSKey_EPl::GpioInputCh, XilSKey_EPl::GpioOutPutCh, XilSKey_EPl::HwmGpioEnd, XilSKey_EPl::HwmGpioReady, XilSKey_EPl::HwmGpioStart, XilSKey_EPl::IntTestAccessDisable, XilSKey_EPl::JtagDisable, XilSKey_EPl::JtagGpioID, XilSKey_EPl::JtagGpioTCK, XilSKey_EPl::JtagGpioTDI, XilSKey_EPl::JtagGpioTDO, XilSKey_EPl::JtagGpioTMS, XilSKey_EPl::JtagMioMuxSel, XilSKey_EPl::JtagMioTCK, XilSKey_EPl::JtagMioTDI, XilSKey_EPl::JtagMioTDO, XilSKey_EPl::JtagMioTMS, XilSKey_EPl::JtagMuxSelLineDefVal, XilSKey_EPl::KeyWrite, XilSKey_EPl::ProgAESandUserLowKey, XilSKey_EPl::ProgAESKeyUltra, XilSKey_EPl::ProgRSAKeyUltra, XilSKey_EPl::ProgUser128BitUltra, XilSKey_EPl::ProgUserHighKey, XilSKey_EPl::ProgUserKeyUltra, XilSKey_EPl::ReadRSAKeyUltra, XilSKey_EPl::ReadUser128BitUltra, XilSKey_EPl::ReadUserKeyUltra, XilSKey_EPl::RSAEnable, XilSKey_EPl::RSARead, XilSKey_EPl::RSAWrite, XilSKey_EPl::SecureRead, XilSKey_EPl::SecureWrite, XilSKey_EPl::SystemInitDone, XilSKey_EPl::UseAESOnly, XilSKey_EPl::User128BitWrite, XilSKey_EPl::UserKey, XilSKey_EPl::UserKeyRead, XilSKey_EPl::UserKeyWrite, XilSKey_Efuse_ConvertStringToHexLE, XilSKey_Efuse_ValidateKey, XSK_EFUSEPL_ALLOW_ENCRYPTED_ONLY, XSK_EFUSEPL_AXI_GPIO_DEVICE_ID, XSK_EFUSEPL_AXI_GPIO_HWM_END, XSK_EFUSEPL_AXI_GPIO_HWM_READY, XSK_EFUSEPL_AXI_GPIO_HWM_START, XSK_EFUSEPL_AXI_GPIO_JTAG_TCK, XSK_EFUSEPL_AXI_GPIO_JTAG_TDI, XSK_EFUSEPL_AXI_GPIO_JTAG_TDO, XSK_EFUSEPL_AXI_GPIO_JTAG_TMS, XSK_EFUSEPL_CHECK_AES_KEY_CRC, XSK_EFUSEPL_DISABLE_128BIT_USER_KEY_WRITE, XSK_EFUSEPL_DISABLE_AES_DECRYPTOR, XSK_EFUSEPL_DISABLE_AES_KEY_READ, XSK_EFUSEPL_DISABLE_FUSE_CNTRL_WRITE, XSK_EFUSEPL_DISABLE_JTAG_CHAIN, XSK_EFUSEPL_DISABLE_KEY_WRITE, XSK_EFUSEPL_DISABLE_RSA_HASH_WRITE, XSK_EFUSEPL_DISABLE_RSA_KEY_READ, XSK_EFUSEPL_DISABLE_SECURE_READ, XSK_EFUSEPL_DISABLE_SECURE_WRITE, XSK_EFUSEPL_DISABLE_TEST_ACCESS, XSK_EFUSEPL_DISABLE_USER_KEY_READ, XSK_EFUSEPL_DISABLE_USER_KEY_WRITE, XSK_EFUSEPL_ENABLE_OBFUSCATION_EFUSEAES, XSK_EFUSEPL_ENABLE_RSA_AUTH, XSK_EFUSEPL_FORCE_USE_FUSE_AES_ONLY, XSK_EFUSEPL_GPIO_INPUT_CH, XSK_EFUSEPL_GPIO_OUTPUT_CH, XSK_EFUSEPL_PROGRAM_AES_KEY, XSK_EFUSEPL_PROGRAM_RSA_KEY_HASH, XSK_EFUSEPL_PROGRAM_USER_KEY, XSK_EFUSEPL_PROGRAM_USER_KEY_128BIT, XSK_EFUSEPL_READ_RSA_KEY_HASH, XSK_EFUSEPL_READ_USER_KEY, XSK_EFUSEPL_READ_USER_KEY128_BIT.
Referenced by main.
u32 XilSKey_EfusePl_LoadData_Slr(XilSKey_EPl *PlInstancePtr, u32 SlrNum)
u32 XilSKey_EfusePl_ReadnCheck(XilSKey_EPl *PlInstancePtr)
Wrapper functions to program and read keys.
PlInstancePtr - Structure Address to update the structure elements SlrNum - Number to differentiate the data targeted to specific SLR - XST_SUCCESS - In case of Success - Error - If initialization fails Helper functions to validate the keys to be written PlInstancePtr - Structure Address to update the structure elements SlrNum - Number to differentiate the data targeted to specific SLR - XST_SUCCESS - In case of Success - Error - If initialization fails
References XilSKey_EPl::AESKeyMatched, XilSKey_EPl::AESKeyReadback, XilSKey_EPl::CrcOfAESKey, XilSKey_EPl::FpgaFlag, XilSKey_EPl::RSAHashReadback, XilSKey_EPl::User128BitReadBack, XilSKey_EPl::UserKeyReadback, XilSKey_EfusePl_ReadKey, XilSKey_EfusePl_ReadStatus, XSK_EFUSEPL_CHECK_AES_KEY_CRC, XSK_EFUSEPL_READ_RSA_KEY_HASH, XSK_EFUSEPL_READ_USER_KEY, XSK_EFUSEPL_READ_USER_KEY128_BIT.
Referenced by main.
u32 XilSKey_EfusePl_ReadorWrite(XilSKey_EPl *PlInstancePtr)
int main()
References XilSKey_EPl::NumSlr, REBOOT_STATUS_REG_ADDR, XilSKey_EPl::SlrConfigOrderIndex, XilSKey_EfusePl_InitData, XilSKey_EfusePl_Program, XilSKey_EfusePl_ReadnCheck, XilSKey_EfusePl_SystemInit, XilSKey_EfusePs_InitData, XilSKey_EfusePs_Read, XilSKey_EfusePs_ReadStatus, XilSKey_EfusePs_Write.