xilskey_eps_zynqmp_puf.h
u32 XilSKey_ZynqMp_EfusePs_WritePufHelprData(const XilSKey_Puf *InstancePtr)
This function programs the PS eFUSEs with the PUF helper data.
InstancePtr Pointer to the XilSKey_Puf instance. XST_SUCCESS if programs successfully.Errorcode on failure To generate PufSyndromeData please use XilSKey_Puf_Registration API
References XilSKey_Efuse_ConvertBitsToBytes, XilSKey_ZynqMp_EfusePs_Init, XilSKey_ZynqMp_EfusePs_SetWriteConditions, XilSKey_ZynqMp_EfusePs_Temp_Vol_Checks, XSK_EFUSEPS_ERROR_CONTROLLER_LOCK, XSK_ZYNQMP_EFUSEPS_PUF_ROW_UPPER_MASK.
Referenced by main.
u32 XilSKey_ZynqMp_EfusePs_ReadPufHelprData(u32 *Address)
This function reads the PUF helper data from eFUSE.
Address Pointer to data array which holds the PUF helper data read from eFUSEs. XST_SUCCESS if reads successfully.Errorcode on failure. This function only reads from eFUSE non-volatile memory. There is no option to read from Cache.
References XilSKey_ZynqMp_EfusePs_ReadRow, XilSKey_ZynqMp_EfusePs_SetTimerValues, XSK_EFUSEPS_ERROR_CONTROLLER_LOCK, XSK_ZYNQMP_EFUSEPS_PUF_ROW_UPPER_MASK.
Referenced by main.
u32 XilSKey_ZynqMp_EfusePs_WritePufChash(const XilSKey_Puf *InstancePtr)
This function programs eFUSE with CHash value.
InstancePtr Pointer to the XilSKey_Puf instance. XST_SUCCESS if chash is programmed successfully.An Error code on failure To generate the CHash value, please use XilSKey_Puf_Registration function.
References XilSKey_Efuse_ConvertBitsToBytes, XilSKey_ZynqMp_EfusePs_Init, XilSKey_ZynqMp_EfusePs_ReadPufChash, XilSKey_ZynqMp_EfusePs_SetWriteConditions, XilSKey_ZynqMp_EfusePs_Temp_Vol_Checks, XilSKey_ZynqMp_EfusePs_WriteAndVerifyBit, XSK_EFUSEPS_ERROR_CONTROLLER_LOCK, XSK_EFUSEPS_ERROR_PUF_CHASH_ALREADY_PROGRAMMED.
Referenced by main.
u32 XilSKey_ZynqMp_EfusePs_ReadPufChash(u32 *Address, u8 ReadOption)
This function reads eFUSE PUF CHash data from the eFUSE array or cache based on the user read option.
Address Pointer which holds the read back value of the chash. ReadOption Indicates whether or not to read from the actual eFUSE array or from the eFUSE cache. 0(XSK_EFUSEPS_READ_FROM_CACHE) Reads from cache1(XSK_EFUSEPS_READ_FROM_EFUSE) Reads from eFUSE array XST_SUCCESS if programs successfully.Errorcode on failure Cache reload is required for obtaining updated values for reading from cache..
References XSK_EFUSEPS_RD_FROM_EFUSE_NOT_ALLOWED, XSK_ZYNQMP_EFUSEPS_BASEADDR, XSK_ZYNQMP_EFUSEPS_PUF_CHASH_OFFSET.
Referenced by main, XilSKey_Puf_Regeneration, XilSKey_ZynqMp_EfusePs_WritePufChash.
u32 XilSKey_ZynqMp_EfusePs_WritePufAux(const XilSKey_Puf *InstancePtr)
This function programs eFUSE PUF auxiliary data.
InstancePtr Pointer to the XilSKey_Puf instance. XST_SUCCESS if the eFUSE is programmed successfully.Errorcode on failure To generate auxiliary data, please use XilSKey_Puf_Registration function.
References XilSKey_Efuse_ConvertBitsToBytes, XilSKey_ZynqMp_EfusePs_Init, XilSKey_ZynqMp_EfusePs_ReadPufAux, XilSKey_ZynqMp_EfusePs_SetWriteConditions, XilSKey_ZynqMp_EfusePs_Temp_Vol_Checks, XilSKey_ZynqMp_EfusePs_WriteAndVerifyBit, XSK_EFUSEPS_ERROR_CONTROLLER_LOCK, XSK_EFUSEPS_ERROR_PUF_AUX_ALREADY_PROGRAMMED.
Referenced by main.
u32 XilSKey_ZynqMp_EfusePs_ReadPufAux(u32 *Address, u8 ReadOption)
This function reads eFUSE PUF auxiliary data from eFUSE array or cache based on user read option.
Address Pointer which holds the read back value of PUF's auxiliary data. ReadOption Indicates whether or not to read from the actual eFUSE array or from the eFUSE cache. 0(XSK_EFUSEPS_READ_FROM_CACHE) Reads from cache1(XSK_EFUSEPS_READ_FROM_EFUSE) Reads from eFUSE array XST_SUCCESS if PUF auxiliary data is read successfully.Errorcode on failure Cache reload is required for obtaining updated values for reading from cache.
References XSK_EFUSEPS_RD_FROM_EFUSE_NOT_ALLOWED, XSK_ZYNQMP_EFUSEPS_BASEADDR, XSK_ZYNQMP_EFUSEPS_PUF_MISC_OFFSET.
Referenced by main, XilSKey_ZynqMp_EfusePs_WritePufAux.
u32 XilSKey_Write_Puf_EfusePs_SecureBits(const XilSKey_Puf_Secure *WriteSecureBits)
This function programs the eFUSE PUF secure bits.
WriteSecureBits Pointer to the XilSKey_Puf_Secure structure XST_SUCCESS if eFUSE PUF secure bits are programmed successfully.Errorcode on failure.
References XilSKey_ZynqMp_EfusePs_CacheLoad, XilSKey_ZynqMp_EfusePs_SetWriteConditions, XilSKey_ZynqMp_EfusePs_WriteAndVerifyBit, XSK_EFUSEPS_ERROR_CONTROLLER_LOCK, XSK_EFUSEPS_ERROR_WRITE_PUF_RESERVED_BIT, XSK_EFUSEPS_ERROR_WRITE_PUF_SYN_INVLD, XSK_EFUSEPS_ERROR_WRITE_PUF_SYN_REG_DIS, XSK_EFUSEPS_ERROR_WRITE_PUF_SYN_WRLK.
Referenced by main.
u32 XilSKey_Read_Puf_EfusePs_SecureBits(XilSKey_Puf_Secure *SecureBitsRead, u8 ReadOption)
This function is used to read the PS eFUSE PUF secure bits from cache or from eFUSE array.
SecureBitsRead - Pointer to the XilSKey_Puf_Secure structure which holds the read eFUSE secure bits from the PUF. ReadOption - Indicates whether or not to read from the actual eFUSE array or from the eFUSE cache. 0(XSK_EFUSEPS_READ_FROM_CACHE) Reads from cache1(XSK_EFUSEPS_READ_FROM_EFUSE) Reads from eFUSE array XST_SUCCESS if reads successfully.Errorcode on failure.
References XSK_EFUSEPS_RD_FROM_EFUSE_NOT_ALLOWED.
Referenced by main.
u32 XilSKey_Puf_Registration(XilSKey_Puf *InstancePtr)
This function performs registration of PUF which generates a new KEK and associated CHash, Auxiliary and PUF-syndrome data which are unique for each silicon.
InstancePtr Pointer to the XilSKey_Puf instance. XST_SUCCESS if registration/re-registration was successful.ERROR if registration was unsuccessful With the help of generated PUF syndrome data, it will be possible to re-generate same PUF KEK.
References XSK_EFUSEPS_ERROR_PUF_DATA_OVERFLOW, XSK_EFUSEPS_ERROR_PUF_DATA_UNDERFLOW, XSK_EFUSEPS_ERROR_PUF_INVALID_REG_MODE, XSK_EFUSEPS_ERROR_PUF_TIMEOUT, XSK_EFUSEPS_PUF_REGISTRATION_COMPLETE, XSK_EFUSEPS_PUF_REGISTRATION_STARTED, XSK_ZYNQMP_CSU_BASEADDR.
Referenced by main.
u32 XilSKey_Puf_Regeneration(const XilSKey_Puf *InstancePtr)
This function regenerates the PUF data so that the PUF's output can be used as the key source to the AES-GCM hardware cryptographic engine.
InstancePtr is a pointer to the XilSKey_Puf instance. XST_SUCCESS if regeneration was successful.ERROR if regeneration was unsuccessful
References XILSKEY_PUF_KEK_REGEN_RDY_TIMEOUT, XilSKey_ZynqMp_EfusePs_ReadPufChash, XSK_EFUSEPS_ERROR_PUF_ACCESS, XSK_EFUSEPS_ERROR_PUF_INVALID_REQUEST, XSK_ZYNQMP_CSU_BASEADDR.