xilskey_eps_zynqmp.c
static u32 XilSKey_ZynqMp_EfusePsWrite_Checks(XilSKey_ZynqMpEPs *InstancePtr)
< Prototype declarations for xilskey eps zynqmp API's
This function performs pre checks for programming all the specified bits. InstancePtr is the pointer to the XilSKey_ZynqMpEPs. XST_SUCCESS - if all the conditions for programming is satisfied Errorcode - if any of the conditions are not met
static u32 XilSKey_ZynqMp_EfusePs_WriteAndVerify_RowRange(const u8 *Data, u8 RowStart, u8 RowEnd, XskEfusePs_Type EfuseType)
This function programs and verifys the Row range provided with provided data array in bits.
Data is a pointer to an array which contains data to be programmed. RowStart holds the row number from which data programming has to be started. RowEnd holds the row number till which data programming has to be performed. EfuseType holds the type of the efuse in which programming rows resides in. XST_SUCCESS - On success XST_FAILURE - on Failure
static u32 XilSKey_ZynqMp_EfusePs_WriteAndVerify_RowData(const u32 *Data, u8 RowStart, u8 RowEnd, XskEfusePs_Type EfuseType)
This function programs and verifys the Row range provided with provided data array in bytes.
Data is a pointer to an array which contains data to be programmed. RowStart holds the row number from which data programming has to be started. RowEnd holds the row number till which data programming has to be performed. EfuseType holds the type of the efuse in which programming rows resides in. XST_SUCCESS - On success XST_FAILURE - on Failure
static u32 XilSKey_ZynqMp_EfusePs_WriteBit(u8 Row, u8 Column, XskEfusePs_Type EfuseType)
This function programs a particular bit.
Row specifies the row number to program. Column specifies the column number to program. EfuseType specifies the eFUSE type. XST_SUCCESS - On success ErrorCode - on Failure
static u32 XilSKey_ZynqMp_EfusePs_Write_SecCtrl(const XilSKey_ZynqMpEPs *InstancePtr)
This function programs secure control bits specified by user.
InstancePtr is an instance of efuseps of Zynq MP. XST_SUCCESS - On success ErrorCode - on Failure
static u32 XilSKey_ZynqMp_EfusePs_Write_SecCtrlBits(const XilSKey_ZynqMpEPs *InstancePtr)
This function programs secure control bits of eFUSE.
InstancePtr is an instance of efuseps of ZynqMp. XST_SUCCESS - On success ErrorCode - on Failure
static u32 XilSKey_ZynqMp_EfusePs_Write_UsrCtrlBits(const XilSKey_ZynqMpEPs *InstancePtr)
static void XilSKey_ZynqMp_EfusePs_ReadSecCtrlBits_Regs(XilSKey_SecCtrlBits *ReadBackSecCtrlBits)
This function is used to read the PS eFUSE secure control bits from cache or from eFUSE array based on user selection.
ReadBackSecCtrlBits is the pointer to the XilSKey_SecCtrlBits which holds the read secure control bits. XST_SUCCESS if reads successfullyXST_FAILURE if reading is failed It is highly recommended to read from eFuse cache. Because reading from efuse may reduce the life of the efuse. And Cache reload is required for obtaining updated values for ReadOption 0.
static u32 XilSKey_ZynqMp_EfusePs_CheckZeros_BfrPrgrmg(const XilSKey_ZynqMpEPs *InstancePtr)
This function is used verify eFUSE keys for Zeros before programming.
InstancePtr is a pointer to eFUSE ps instance. XST_SUCCESS if keys are not programmed ErrorCode if keys are already programmed.
static u32 XilSKey_ZynqMp_EfusePs_UserFuses_WriteChecks(const XilSKey_ZynqMpEPs *InstancePtr, XilSKey_UsrFuses *ToBePrgrmd)
This function throws an error if user requests already programmed User FUSE bit to revert, and copies the User FUSE bits which needs actually to be programmed into provided UserFuses_TobePrgrmd pointer.
InstancePtr is a pointer to eFUSE ps instance. ToBePrgrmd holds User FUSE bits which needs to be actually programmed. ErrorCode if user requests programmed bit to revert.XST_SUCCESS if user requests valid bits If user requests a non-zero bit for making to zero throws an error which is not possible
static u32 XilSKey_ZynqMp_EfusePs_UserFuses_TobeProgrammed(const u8 *UserFuses_Write, const u8 *UserFuses_Read, XilSKey_UsrFuses *UserFuses_ToBePrgrmd)
This function throws an error if user requests already programmed User FUSE bit to revert, and copies the bits to be programmed in particular row into provided UserFuses_TobePrgrmd pointer.
UserFuses_Write is a pointer to user requested programming bits of an User FUSE row. UserFuses_Read is a pointer to already programmed bits of User FUSE row on eFUSE. UserFuses_ToBePrgrmd holds User FUSE row bits which needs to be programmed actually. XST_FAILURE: Returns error if user requests programmed bit to revertXST_SUCCESS: If User requests valid bits. If user requests a non-zero bit for making to zero throws an error which is not possible
static u32 XilSKey_ZynqMp_EfusePs_Enable_Rsa(const u8 *SecBits_read)
This function programs RSA enable secure control bits of eFUSE.
SecBits_read is a pointer which holds 32 bits of secure control register. XST_SUCCESS - On success ErrorCode - on Failure For ZynqMP silicon version 1.0 and 2.0 RSA authentication is enabled only by programming 24 and 25 bits of SEC_CTRL register but from silicon V3.0 bits 11:25 should be programmed
static u32 XilSKey_ZynqMpEfuseRead(const u32 AddrHigh, const u32 AddrLow)
This function provides support to read eFUSE memory.
AddrHigh Higher 32-bit address of the XilSKey_Efuse structure. AddrLow Lower 32-bit address of the XilSKey_Efuse structure. XST_SUCCESS - On success ErrorCode - on Failure
static u32 XilSKey_ZynqMpEfuseWrite(const u32 AddrHigh, const u32 AddrLow)
This function provides support to program eFUSE memory.
AddrHigh Higher 32-bit address of the XilSKey_Efuse structure. AddrLow Lower 32-bit address of the XilSKey_Efuse structure. XST_SUCCESS - On success ErrorCode - on Failure
u32 XilSKey_ZynqMp_EfusePs_Write(XilSKey_ZynqMpEPs *InstancePtr)
This function is used to program the PS eFUSE of ZynqMP, based on user inputs.
InstancePtr Pointer to the XilSKey_ZynqMpEPs. XST_SUCCESS if programs successfully.Errorcode on failure After eFUSE programming is complete, the cache is automatically reloaded so all programmed eFUSE bits can be directly read from cache.
References XilSKey_ZynqMp_EfusePs_Init, XilSKey_ZynqMp_EfusePs_Temp_Vol_Checks, XSK_EFUSEPS_ERROR_CONTROLLER_LOCK, XSK_EFUSEPS_ERROR_BEFORE_PROGRAMMING, XilSKey_Efuse_ConvertBitsToBytes, XSK_ZYNQMP_EFUSEPS_BASEADDR, XSK_ZYNQMP_EFUSEPS_SPK_ID_OFFSET, XSK_EFUSEPS_ERROR_SPKID_BIT_CANT_REVERT, XilSKey_ZynqMp_EfusePs_ReadPpk0Hash, XilSKey_EfusePs_ConvertBytesBeToLe, XSK_EFUSEPS_ERROR_PPK0_BIT_CANT_REVERT, XilSKey_ZynqMp_EfusePs_ReadPpk1Hash, XSK_EFUSEPS_ERROR_PPK1_BIT_CANT_REVERT, XilSKey_ZynqMp_EfusePs_SetWriteConditions, XSK_EFUSEPS_ERROR_WRITE_AES_KEY, XilSKey_ZynqMp_EfusePs_CacheLoad, XSK_EFUSEPS_ERROR_VERIFICATION, XilSkey_CrcCalculation_AesKey, XilSKey_ZynqMp_EfusePs_CheckAesKeyCrc, XSK_EFUSEPS_ERROR_WRITE_USER0_FUSE, XSK_EFUSEPS_ERROR_WRITE_USER1_FUSE, XSK_EFUSEPS_ERROR_WRITE_USER2_FUSE, XSK_EFUSEPS_ERROR_WRITE_USER3_FUSE, XSK_EFUSEPS_ERROR_WRITE_USER4_FUSE, XSK_EFUSEPS_ERROR_WRITE_USER5_FUSE, XSK_EFUSEPS_ERROR_WRITE_USER6_FUSE, XSK_EFUSEPS_ERROR_WRITE_USER7_FUSE, XSK_EFUSEPS_ERROR_WRITE_SPK_ID, XSK_EFUSEPS_ERROR_WRITE_PPK0_HASH, XSK_EFUSEPS_ERROR_WRITE_PPK1_HASH, XSK_EFUSEPS_ERROR_CMPLTD_EFUSE_PRGRM_WITH_ERR.
u32 XilSKey_ZynqMp_EfusePs_ReadSecCtrlBits(XilSKey_SecCtrlBits *ReadBackSecCtrlBits, u8 ReadOption)
This function is used to read the PS eFUSE secure control bits from cache or eFUSE based on user input provided.
ReadBackSecCtrlBits Pointer to the XilSKey_SecCtrlBits which holds the read secure control bits. ReadOption Indicates whether or not to read from the actual eFUSE array or from the eFUSE cache. 0(XSK_EFUSEPS_READ_FROM_CACHE) Reads from eFUSE cache1(XSK_EFUSEPS_READ_FROM_EFUSE) Reads from eFUSE array XST_SUCCESS if reads successfullyXST_FAILURE if reading is failed It is highly recommended to read from eFuse cache. Because reading from efuse may reduce the life of the efuse. And Cache reload is required for obtaining updated values for ReadOption 0.
References XSK_EFUSEPS_RD_FROM_EFUSE_NOT_ALLOWED.
Referenced by main.
u32 XilSKey_ZynqMp_EfusePs_WriteAndVerifyBit(u8 Row, u8 Column, XskEfusePs_Type EfuseType)
This function programs and verifies the particular bit of eFUSE array.
Row specifies the row number. Column specifies the column number. EfuseType specifies the eFUSE type. XST_SUCCESS - On success ErrorCode - on Failure
References XSK_ZYNQMP_EFUSEPS_BASEADDR, XSK_ZYNQMP_EFUSEPS_CFG_OFFSET, XilSKey_ZynqMp_EfusePs_ReadRow, XSK_EFUSEPS_ERROR_VERIFICATION.
Referenced by XilSKey_ZynqMp_EfusePs_WritePufChash, XilSKey_ZynqMp_EfusePs_WritePufAux, XilSKey_Write_Puf_EfusePs_SecureBits.
u32 XilSKey_ZynqMp_EfusePs_ReadRow(u8 Row, XskEfusePs_Type EfuseType, u32 *RowData)
This function returns particular row data directly from eFUSE array.
Row specifies the row number to read. EfuseType specifies the eFUSE type. RowData is a pointer to 32 bit variable to hold the data read from provided data XST_SUCCESS - On success ErrorCode - on Failure
References XSK_ZYNQMP_EFUSEPS_BASEADDR, XSK_ZYNQMP_EFUSEPS_RD_ADDR_OFFSET, XSK_ZYNQMP_EFUSEPS_ISR_OFFSET, XSK_EFUSEPS_ERROR_READ, XSK_EFUSEPS_ERROR_READ_NOT_DONE, XSK_ZYNQMP_EFUSEPS_RD_DATA_OFFSET.
Referenced by XilSKey_ZynqMp_EfusePs_WriteAndVerifyBit, XilSKey_ZynqMp_EfusePs_CheckForZeros, XilSKey_ZynqMp_EfusePs_ReadPufHelprData.
u32 XilSKey_ZynqMp_EfusePs_CacheLoad(void)
This function reloads the cache of eFUSE so that can be directly read from cache.
XST_SUCCESS on successful cache reloadErrorCode on failure Not recommended to call this API frequently, if this API is called all the cache memory is reloded by reading eFUSE array, reading eFUSE bit multiple times may diminish the life time.
References XSK_ZYNQMP_EFUSEPS_BASEADDR, XSK_ZYNQMP_EFUSEPS_CACHE_LOAD_OFFSET, XSK_EFUSEPS_ERROR_CACHE_LOAD.
Referenced by XilSKey_ZynqMp_EfusePs_Write, XilSKey_Write_Puf_EfusePs_SecureBits.
u32 XilSKey_ZynqMp_EfusePs_SetWriteConditions(void)
This function sets all the required parameters to program eFUSE array.
XST_SUCCESS - On success ErrorCode - on Failure
References XilSKey_ZynqMp_EfusePs_SetTimerValues, XSK_EFUSEPS_ERROR_IN_TBIT_PATTERN.
Referenced by XilSKey_ZynqMp_EfusePs_Write, XilSKey_ZynqMp_EfusePs_WritePufHelprData, XilSKey_ZynqMp_EfusePs_WritePufChash, XilSKey_ZynqMp_EfusePs_WritePufAux, XilSKey_Write_Puf_EfusePs_SecureBits.
void XilSKey_ZynqMp_EfusePs_SetTimerValues(void)
This function sets timers for programming and reading from eFUSE.
References XSK_ZYNQMP_EFUSEPS_BASEADDR, XSK_ZYNQMP_EFUSEPS_CFG_OFFSET, XSK_ZYNQMP_EFUSEPS_TPGM_OFFSET, XSK_ZYNQMP_EFUSEPS_TRD_OFFSET, XSK_ZYNQMP_EFUSEPS_TSU_H_PS_OFFSET, XSK_ZYNQMP_EFUSEPS_TSU_H_PS_CS_OFFSET, XSK_ZYNQMP_EFUSEPS_TSU_H_CS_OFFSET.
Referenced by XilSKey_ZynqMp_EfusePs_SetWriteConditions, XilSKey_ZynqMp_EfusePs_CheckAesKeyCrc, XilSKey_ZynqMp_EfusePs_ReadPufHelprData.
u32 XilSKey_ZynqMp_EfusePs_CheckAesKeyCrc(u32 CrcValue)
This function performs the CRC check of AES key.
CrcValue A 32 bit CRC value of an expected AES key. XST_SUCCESS on successful CRC check.ErrorCode on failure For Calculating the CRC of the AES key use the XilSKey_CrcCalculation() function or XilSkey_CrcCalculation_AesKey() function
References XilSKey_ZynqMp_EfusePs_SetTimerValues, XSK_ZYNQMP_EFUSEPS_BASEADDR, XSK_ZYNQMP_EFUSEPS_AES_CRC_OFFSET.
Referenced by XilSKey_ZynqMp_EfusePs_Write.
u32 XilSKey_ZynqMp_EfusePs_ReadUserFuse(u32 *UseFusePtr, u8 UserFuse_Num, u8 ReadOption)
This function is used to read a user fuse from the eFUSE or cache.
UseFusePtr Pointer to an array which holds the readback user fuse. UserFuse_Num A variable which holds the user fuse number. Range is (User fuses: 0 to 7) ReadOption Indicates whether or not to read from the actual eFUSE array or from the eFUSE cache. 0(XSK_EFUSEPS_READ_FROM_CACHE) Reads from eFUSE cache1(XSK_EFUSEPS_READ_FROM_EFUSE) Reads from eFUSE array XST_SUCCESS on successful readErrorCode on failure It is highly recommended to read from eFuse cache. Because reading from efuse may reduce the life of the efuse. And Cache reload is required for obtaining updated values for ReadOption 0.
References XSK_ZYNQMP_EFUSEPS_BASEADDR, XSK_ZYNQMP_EFUSEPS_USER_0_OFFSET, XSK_EFUSEPS_RD_FROM_EFUSE_NOT_ALLOWED.
u32 XilSKey_ZynqMp_EfusePs_ReadPpk0Hash(u32 *Ppk0Hash, u8 ReadOption)
This function is used to read the PPK0 hash from an eFUSE or eFUSE cache.
Ppk0Hash A pointer to an array which holds the readback PPK0 hash. ReadOption Indicates whether or not to read from the actual eFUSE array or from the eFUSE cache. 0(XSK_EFUSEPS_READ_FROM_CACHE) Reads from eFUSE cache1(XSK_EFUSEPS_READ_FROM_EFUSE) Reads from eFUSE array XST_SUCCESS on successful readErrorCode on failure It is highly recommended to read from eFuse cache. Because reading from efuse may reduce the life of the efuse. And Cache reload is required for obtaining updated values for ReadOption 0.
References XSK_ZYNQMP_EFUSEPS_BASEADDR, XSK_ZYNQMP_EFUSEPS_PPK0_0_OFFSET, XilSKey_EfusePs_ConvertBytesBeToLe, XSK_EFUSEPS_RD_FROM_EFUSE_NOT_ALLOWED.
Referenced by XilSKey_ZynqMp_EfusePs_Write.
u32 XilSKey_ZynqMp_EfusePs_ReadPpk1Hash(u32 *Ppk1Hash, u8 ReadOption)
This function is used to read the PPK1 hash from eFUSE or cache.
Ppk1Hash Pointer to an array which holds the readback PPK1 hash. ReadOption Indicates whether or not to read from the actual eFUSE array or from the eFUSE cache. 0(XSK_EFUSEPS_READ_FROM_CACHE) Reads from eFUSE cache1(XSK_EFUSEPS_READ_FROM_EFUSE) Reads from eFUSE array XST_SUCCESS on successful readErrorCode on failure It is highly recommended to read from eFuse cache. Because reading from efuse may reduce the life of the efuse. And Cache reload is required for obtaining updated values for ReadOption 0.
References XSK_ZYNQMP_EFUSEPS_BASEADDR, XSK_ZYNQMP_EFUSEPS_PPK1_0_OFFSET, XilSKey_EfusePs_ConvertBytesBeToLe, XSK_EFUSEPS_RD_FROM_EFUSE_NOT_ALLOWED.
Referenced by XilSKey_ZynqMp_EfusePs_Write.
u32 XilSKey_ZynqMp_EfusePs_ReadSpkId(u32 *SpkId, u8 ReadOption)
This function is used to read SPKID from eFUSE or cache based on user's read option.
SpkId Pointer to a 32 bit variable which holds SPK ID. ReadOption Indicates whether or not to read from the actual eFUSE array or from the eFUSE cache. 0(XSK_EFUSEPS_READ_FROM_CACHE) Reads from eFUSE cache1(XSK_EFUSEPS_READ_FROM_EFUSE) Reads from eFUSE array XST_SUCCESS on successful readErrorCode on failure It is highly recommended to read from eFuse cache. Because reading from efuse may reduce the life of the efuse. And Cache reload is required for obtaining updated values for ReadOption 0.
References XSK_ZYNQMP_EFUSEPS_BASEADDR, XSK_ZYNQMP_EFUSEPS_SPK_ID_OFFSET, XSK_EFUSEPS_RD_FROM_EFUSE_NOT_ALLOWED.
void XilSKey_ZynqMp_EfusePs_ReadDna(u32 *DnaRead)
This function is used to read DNA from eFUSE.
DnaRead Pointer to an array of 3 x u32 words which holds the readback DNA.
References XSK_ZYNQMP_EFUSEPS_BASEADDR, XSK_ZYNQMP_EFUSEPS_DNA_0_OFFSET, XSK_ZYNQMP_EFUSEPS_DNA_1_OFFSET, XSK_ZYNQMP_EFUSEPS_DNA_2_OFFSET.
u32 XilSKey_ZynqMp_EfusePs_CheckForZeros(u8 RowStart, u8 RowEnd, XskEfusePs_Type EfuseType)
This function is used verify eFUSE keys for Zeros.
RowStart is row number from which verification has to be started. RowEnd is row number till which verification has to be ended. EfuseType is the type of the eFUSE in which these rows reside. XST_SUCCESS if keys are not programmed. Errorcode on failure.
References XilSKey_ZynqMp_EfusePs_ReadRow.
u32 XilSKey_ZynqMp_EfusePs_Init(void)
This function initializes sysmonpsu driver.
XST_SUCCESS - On success ErrorCode - on Failure
References XilSKey_EfusePs_XAdcInit.
Referenced by XilSKey_ZynqMp_EfusePs_Write, XilSKey_ZynqMp_EfusePs_WritePufHelprData, XilSKey_ZynqMp_EfusePs_WritePufChash, XilSKey_ZynqMp_EfusePs_WritePufAux.
u32 XilSkey_ZynqMpEfuseAccess(const u32 AddrHigh, const u32 AddrLow)
This function is used by PMUFW IPI call handler for programming eFUSE.
Register Read Write Size in bytes Offset Version YES NO 0x0 0x4 DNA YES NO 0xc 0xC User0 YES YES 0x4 0x20 User1 YES YES 0x4 0x24 User2 YES YES 0x4 0x28 User3 YES YES 0x4 0x2c User4 YES YES 0x4 0x30 User5 YES YES 0x4 0x34 User6 YES YES 0x4 0x38 User7 YES YES 0x4 0x3C Misc user YES YES 0x4 0x40 Secure control YES YES 0x4 0x58 SPK ID YES YES 0x4 0x5C AES key NO YES 0x20 0x60 PPK0 hash YES YES 0x30 0xA0 PPK1 hash YES YES 0x30 0xD0 AddrHigh Higher 32-bit address of the XilSKey_Efuse structure. AddrLow Lower 32-bit address of the XilSKey_Efuse structure. XST_SUCCESS - On success ErrorCode - on Failure
References XSK_EFUSEPS_ERROR_ADDR_ACCESS.