xilskey_utils.c
u32 TimerTicksfor100ns
Global static Variable to store ticks/100ns.
u32 TimerTicksfor1000ns
Global Variable for 10 micro secs for microblaze.
Referenced by JtagWrite_Ultrascale, XilSKey_Timer_Intialise.
static u32 XilSKey_EfusePs_ConvertCharToNibble(char InChar, u8 *Num)
Converts the char into the equivalent nibble.
Ex: 'a' -> 0xa, 'A' -> 0xa, '9'->0x9 InChar is input character. It has to be between 0-9,a-f,A-F Num is the output nibble. XST_SUCCESS no errors occurred. XST_FAILURE an error when input parameters are not valid
u32 XilSKey_EfusePs_XAdcInit(void)
This function is used to initialize the XADC driver.
XST_SUCCESS in case of no errors.XSK_EFUSEPS_ERROR_XADC_CONFIG Error occurred with XADC config.XSK_EFUSEPS_ERROR_XADC_INITIALIZE Error occurred while XADC initializationXSK_EFUSEPS_ERROR_XADC_SELF_TEST Error occurred in XADC self test. TDD Cases:
References XSK_EFUSEPS_ERROR_XADC_CONFIG, XSK_EFUSEPS_ERROR_XADC_INITIALIZE, XSK_EFUSEPS_ERROR_XADC_SELF_TEST.
Referenced by XilSKey_EfusePs_Read, XilSKey_EfusePs_Write, XilSKey_ZynqMp_EfusePs_Init.
void XilSKey_EfusePs_XAdcReadTemperatureAndVoltage(XSKEfusePs_XAdc *XAdcInstancePtr)
This function reads current value of the temperature from sysmon.
XAdcInstancePtr Pointer to the XSKEfusePs_XAdc. None Read temperature will be stored in XSKEfusePS_XAdc pointer's temperature This function is used to copy the min, max and current value of the temperature and voltage which are read from XADC. XAdcInstancePtr Pointer to the XSKEfusePs_XAdc. User has to fill the VType to specify the type of voltage. Valid values for VType are XSK_EFUSEPS_VPINTXSK_EFUSEPS_VPDROXSK_EFUSEPS_VPAUX XSK_EFUSEPS_VINTXSK_EFUSEPS_VAUX none TDD Cases:
References Jtag_Read_Sysmon.
u32 XilSKey_ZynqMp_EfusePs_Temp_Vol_Checks(void)
This function checks temperature and voltage ranges of ZynqMP to access PS eFUSE.
Error code: On failure XST_SUCCESS on Success This function returns XST_SUCCESS if we try to access eFUSE on the Remus, as Sysmon access is not permitted on Remus.
References XSK_EFUSEPS_ERROR_READ_TMEPERATURE_OUT_OF_RANGE, XSK_EFUSEPS_ERROR_READ_VCCPAUX_VOLTAGE_OUT_OF_RANGE, XSK_EFUSEPS_ERROR_READ_VCCPINT_VOLTAGE_OUT_OF_RANGE.
Referenced by XilSKey_ZynqMp_EfusePs_Write, XilSKey_ZynqMp_EfusePs_WritePufAux, XilSKey_ZynqMp_EfusePs_WritePufChash, XilSKey_ZynqMp_EfusePs_WritePufHelprData.
void XilSKey_Efuse_StartTimer(void)
Initializes the global timer & starts it.
Calculates the timer ticks for 1us. None None.
Referenced by JtagWrite_Ultrascale, XilSKey_EfusePs_Write.
u64 XilSKey_Efuse_GetTime(void)
Returns the timer ticks from start of timer to till now.
t - Timer ticks lapsed till now. None.
Referenced by XilSKey_Efuse_IsTimerExpired, XilSKey_Efuse_SetTimeOut.
void XilSKey_Efuse_SetTimeOut(volatile u64 *t, u64 us)
Calculates the timer ticks to wait to set the time out.
t - timer ticks to wait to set the timeout us - Timeout period in us None. None.
References XilSKey_Efuse_GetTime.
Referenced by Bbram_Init, JtagWrite, XilSKey_EfusePs_WriteEfuseBit.
u8 XilSKey_Efuse_IsTimerExpired(u64 t)
Checks whether the timer has been expired or not.
t - timeout value in us t_end - Returns the global timer value in case of timer expired None.
References XilSKey_Efuse_GetTime.
Referenced by Bbram_Init, JtagWrite, JtagWrite_Ultrascale, XilSKey_EfusePs_WriteEfuseBit.
u32 XilSKey_Efuse_ConvertStringToHexBE(const char *Str, u8 *Buf, u32 Len)
Converts the string into the equivalent Hex buffer.
Function used to convert the string to Hex in Little Endian format. Ex: "abc123" -> {0xab, 0xc1, 0x23} Str is a Input String. Will support the lower and upper case values. Value should be between 0-9, a-f and A-F Buf is Output buffer. Len of the input string in bits and it should have even values XST_SUCCESS no errors occurred. XST_FAILURE an error when input parameters are not validan error when input buffer has invalid values TDD Test Cases: Initialization Len is odd Len is zero Str is NULL Buf is NULL Functionality Str input with only numbers Str input with All values in A-F Str input with All values in a-f Str input with values in a-f, 0-9, A-F Str input with values in a-z, 0-9, A-Z Boundary Cases Memory Bounds of buffer checking
References XSK_EFUSEPS_ERROR_INVALID_PARAM, XSK_EFUSEPS_ERROR_PARAMETER_NULL, XSK_EFUSEPS_ERROR_STRING_INVALID.
Referenced by XilSKey_Bbram_InitData, XilSKey_CrcCalculation, XilSKey_EfusePs_InitData.
u32 XilSKey_Efuse_ConvertStringToHexLE(const char *Str, u8 *Buf, u32 Len)
Converts the string into the equivalent Hex buffer.
Function used to convert the string to Hex in Little Endian format. Ex: "abc123" -> {0x23, 0xc1, 0xab} Str is a Input String. Will support the lower and upper case values. Value should be between 0-9, a-f and A-F Buf is Output buffer. Len of the input string in bits and it should have even values XST_SUCCESS no errors occurred. XST_FAILURE an error when input parameters are not validan error when input buffer has invalid values TDD Test Cases: Initialization Len is odd Len is zero Str is NULL Buf is NULL Functionality Str input with only numbers Str input with All values in A-F Str input with All values in a-f Str input with values in a-f, 0-9, A-F Str input with values in a-z, 0-9, A-Z Boundary Cases Memory Bounds of buffer checking
References XSK_EFUSEPS_ERROR_INVALID_PARAM, XSK_EFUSEPS_ERROR_PARAMETER_NULL, XSK_EFUSEPS_ERROR_STRING_INVALID.
Referenced by main, XilSKey_EfusePl_InitData.
void XilSKey_EfusePs_ConvertBytesBeToLe(const u8 *Be, u8 *Le, u32 Len)
This function is used to convert the Big Endian Byte data to Little Endian Byte data For ex: 1234567890abcdef -> 78563412efcdab90.
Be Big endian data Le Little endian data Len Length of data to be converted and it should be in number of words (multiple of 4 bytes) None. TDD Test Cases:
Referenced by XilSKey_ZynqMp_EfusePs_ReadPpk0Hash, XilSKey_ZynqMp_EfusePs_ReadPpk1Hash, XilSKey_ZynqMp_EfusePs_Write.
void XilSKey_Efuse_ConvertBitsToBytes(const u8 *Bits, u8 *Bytes, u32 Len)
Convert the Bits to Bytes in Little Endian format Ex: 0x5C -> {0, 0, 1, 1, 1, 0, 1, 0}.
Bits Input Buffer. Bytes is Output buffer. Len of the input buffer in bits None Test Cases: Input with All Zeroes Input with All Ones Input Little Endian (General Cases ) Input Check Big Endian - False case Check for Len not a multiple of 8 Check for Len 0 Memory Bounds of buffer checking
Referenced by XilSKey_ZynqMp_EfusePs_Write, XilSKey_ZynqMp_EfusePs_WritePufAux, XilSKey_ZynqMp_EfusePs_WritePufChash, XilSKey_ZynqMp_EfusePs_WritePufHelprData.
void XilSKey_EfusePs_ConvertBytesToBits(const u8 *Bytes, u8 *Bits, u32 Len)
Convert the Bytes to Bits in little endian format 0th byte is LSB, 7th byte is MSB Ex: {0, 0, 1, 1, 1, 0, 1, 0} -> 0x5C.
Bytes Input Buffer. Bits is Output buffer. Len of the input buffer. None Test Cases: Input with All Zeroes Input with All Ones Input Little Endian (General Cases ) Input Check Big Endian - False case Check for Len not a multiple of 8 Check for Len 0 Memory Bounds of buffer checking
u32 XilSKey_Efuse_ValidateKey(const char *Key, u32 Len)
Validate the key for proper characters & proper length.
Function used to validate the AES & RSA key provided as input. Key - Hash Key Len - Valid length of key XST_SUCCESS - In case of Success XST_FAILURE - In case of Failure
References XilSKey_Efuse_IsValidChar, XSK_EFUSEPL_ERROR_KEY_VALIDATION, XSK_EFUSEPL_ERROR_NONE, XSK_EFUSEPL_ERROR_NOT_VALID_KEY_CHAR, XSK_EFUSEPL_ERROR_NOT_VALID_KEY_LENGTH.
Referenced by XilSKey_EfusePl_InitData, XilSKey_EfusePs_InitData.
u32 XilSKey_Efuse_IsValidChar(const char *c)
Checks whether the passed character is a valid hash key character.
c - Character to check proper value XST_SUCCESS - In case of Success XST_FAILURE - In case of Failure
Referenced by XilSKey_Efuse_ValidateKey.
u32 XilSKey_Timer_Intialise(void)
This API initializes the Timer based on platform.
RefClk will be returned. None.
References TimerTicksfor1000ns.
Referenced by XilSKey_EfusePs_Read, XilSKey_EfusePs_Write.
u32 XilSKey_CrcCalculation(const u8 *Key)
This function Calculates CRC value based on hexadecimal string passed.
Key Pointer to the string contains AES key in hexadecimal of length less than or equal to 64. On Success returns the Crc of AES key value.On failure returns the error code when string length is greater than 64 If the length of the string provided is less than 64, this function appends the string with zeros. For calculation of AES key's CRC one can use u32 XilSKey_CrcCalculation(u8 *Key) API or reverse polynomial 0x82F63B78.
References XSK_EFUSEPL_ERROR_NOT_VALID_KEY_LENGTH, XilSKey_Efuse_ConvertStringToHexBE, XilSKey_RowCrcCalculation.
u32 XilSKey_RowCrcCalculation(u32 PrevCRC, u32 Data, u32 Addr)
Calculates CRC value for each row of AES key.
PrevCRC holds the prev row's CRC. Data holds the present row's key. Addr stores the current row number. Crc of current row. None.
Referenced by XilSKey_CrcCalculation, XilSkey_CrcCalculation_AesKey.
u32 XilSKey_Efuse_ReverseHex(u32 Input)
This API reverse the value.
Input is a 32 bit variable Reverse the given value. None.
Referenced by JtagRead_Status_Ultrascale.
u32 XilSkey_CrcCalculation_AesKey(const u8 *Key)
Calculates CRC value of the provided key.
Key should be provided in hexa buffer. Key Pointer to an array of 32 bytes, which holds an AES key. Crc of provided AES key value. To calculate CRC on the AES key in string format please use XilSKey_CrcCalculation.
References XilSKey_RowCrcCalculation.
Referenced by XilSKey_ZynqMp_EfusePs_Write.