xilskey_bbram.c
XSK_BBRAM_P0_MASK
< DEF masks for calculating ECC of 28 bit 0f a control word
XSK_BBRAM_P1_MASK
XSK_BBRAM_P2_MASK
XSK_BBRAM_P3_MASK
XSK_BBRAM_P4_MASK
XSK_BBRAM_CTRL_ECC_MASK
Error detection mask.
XSK_BBRAM_CTRL_RSRVD_MASK
Reserved bits.
XSK_BBRAM_CTRL_BLACK_KEY_MASK
BLACK key mask.
XSK_BBRAM_CTRL_BLACK_KEY_SHIFT
BLACK key shift.
XSK_BBRAM_CTRL_MODE_MASK
DPA mode mask.
XSK_BBRAM_CTRL_MODE_SHIFT
DPA mode shift.
XSK_BBRAM_CTRL_DPA_PROTECT_MASK
DPA Protection mask.
XSK_BBRAM_CTRL_DPA_PROTECT_SHIFT
DPA protection shift.
XSK_BBRAM_CTRL_RD_DPA_COUNT_MASK
Redundant DPA count mask.
XSK_BBRAM_CTRL_RD_DPA_COUNT_SHIFT
Redundant DPA count shift.
XSK_BBRAM_CTRL_DPA_COUNT_MASK
DPA count mask.
XSK_BBRAM_CTRL_DPA_COUNT_SHIFT
DPA count shift.
XSK_BBRAM_CTRL_DEFAULT_VAL
Enable value.
XSK_BBRAM_CTRL_ENABLE_VAL
Value for default state.
XilSKey_JtagSlr XilSKeyJtag
JTAG Tap Instance.
Referenced by Bbram_Close_Ultra, Bbram_DeInit, Bbram_Init, Bbram_ProgramKey, Bbram_VerifyKey, calcInstr, Jtag_Read_Sysmon, JtagAES_Check_Ultrascale, JtagRead, JtagRead_Status_Ultrascale, JtagRead_Ultrascale, JtagServerInit, JtagServerInitBbram, JtagWrite, JtagWrite_Ultrascale.
int JtagServerInitBbram(XilSKey_Bbram *InstancePtr)
JTAG Server Initialization routine for Bbram.
JTAG Server Initialization routine for Bbram. InstancePtr - instance pointer - XST_FAILURE - In case of failure - XST_SUCCESS - In case of Success
References js_init_zynq, js_printf, JtagInitGpio, JtagValidateMioPins, XilSKeyJtag.
int Bbram_Init(void)
BBRAM Algorithm - Initialization.
BBRAM Algorithm - Initialization. - XST_FAILURE - In case of failure - XST_SUCCESS - In case of Success
References calcInstr, jtag_navigate, jtag_setPreAndPostPads, jtag_shift, XilSKey_Efuse_IsTimerExpired, XilSKey_Efuse_SetTimeOut, XilSKeyJtag.
int Bbram_ProgramKey(XilSKey_Bbram *InstancePtr)
BBRAM Algorithm - Program key.
BBRAM Algorithm - Program key. InstancePtr - instance pointer - XST_FAILURE - In case of failure - XST_SUCCESS - In case of Success
References calcInstr, jtag_navigate, jtag_setPreAndPostPads, jtag_shift, setPin, XilSKeyJtag.
int Bbram_VerifyKey(XilSKey_Bbram *InstancePtr)
BBRAM Algorithm - Verify key.
BBRAM Algorithm - Verify key.Program and verify key have to be done together; These API's cannot be used independently. InstancePtr - instance pointer - XST_FAILURE - In case of failure - XST_SUCCESS - In case of Success
References calcInstr, jtag_navigate, jtag_setPreAndPostPads, jtag_shift, setPin, XilSKeyJtag.
void Bbram_DeInit(void)
De-initialization.
De-initialization.none
References calcInstr, jtag_navigate, jtag_setPreAndPostPads, jtag_shift, XilSKeyJtag.
u32 XilSKey_RowCrcCalculation(u32 PrevCRC, u32 Data, u32 Addr)
Calculates CRC value for each row of AES key.
PrevCRC holds the prev row's CRC. Data holds the present row's key. Addr stores the current row number. Crc of current row. None.
Referenced by XilSKey_CrcCalculation, XilSkey_CrcCalculation_AesKey.
static int XilSKey_Bbram_Program_Zynq(XilSKey_Bbram *InstancePtr)
This API programs and verifies BBRAM of Zynq.
InstancePtr is BBRAM's instance. XST_SUCCESS if programming and verification of BBRAM is successful.XST_FAILURE if fails. None.
int XilSKey_Bbram_JTAGServerInit(XilSKey_Bbram *InstancePtr)
This function initializes JTAG server.
InstancePtr Pointer to XilSKey_Bbram - XST_FAILURE - In case of failure - XST_SUCCESS - In case of Success
int XilSKey_Bbram_Program(XilSKey_Bbram *InstancePtr)
This function implements the BBRAM algorithm for programming and verifying key.
The program and verify will only work together in and in that order. InstancePtr Pointer to XilSKey_Bbram - XST_FAILURE - In case of failure - XST_SUCCESS - In case of Success This function will program BBRAM of Ultrascale and Zynq as well.
Referenced by XilSKey_Bbram_ProgramSLR.