xilskey_epshw.h
XSK_EFUSEPS_HAMMING_LOOPS
< Hamming loops, data and length
XSK_EFUSEPS_HAMMING_LENGTH
XSK_EFUSEPS_HAMMING_DATA
XSK_EFUSEPS_SINGLE_MODE
< Mode types and definitions
Referenced by XilSKey_EfusePs_ControllerConfig, XilSKey_EfusePs_Write.
XSK_EFUSEPS_REDUNDANCY_MODE
XSK_EFUSEPS_READ_MODE_NORMAL
< ReadModes and definitions
Referenced by XilSKey_EfusePs_Read, XilSKey_EfusePs_Write.
XSK_EFUSEPS_READ_MODE_MARGIN_1
XSK_EFUSEPS_READ_MODE_MARGIN_2
XSK_EFUSEPS_ENABLE_PROGRAMMING
< EFUSE operation modes and definitions
Referenced by XilSKey_EfusePs_ControllerSetReadWriteEnable, XilSKey_EfusePs_Write.
XSK_EFUSEPS_ENABLE_READ
XSK_EFUSEPS_ENABLE_WRITE
XSK_EFUSEPS_REFCLK_LOW_FREQ
< EFUSE Reference Clock frequency definitions
Referenced by XilSKey_EfusePs_ControllerConfig.
XSK_EFUSEPS_REFCLK_HIGH_FREQ
XSK_EFUSEPS_CONFIG_MARGIN_RD
< eFuse read margin control: 00 normal, 01 margin 1, 10 margin 2, 11 - undefined
XSK_EFUSEPS_CONFIG_RD_NORMAL
XSK_EFUSEPS_CONFIG_RD_MARGIN_1
XSK_EFUSEPS_CONFIG_RD_MARGIN_2
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x20_OFFSET
< Xilinx reserved Tests bits in the First half of the eFUSE block offsets and definitions
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x41_OFFSET
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x62_OFFSET
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x83_OFFSET
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_xA4_OFFSET
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_xC5_OFFSET
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_xE6_OFFSET
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x107_OFFSET
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x128_OFFSET
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x149_OFFSET
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x23F_OFFSET
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x25E_OFFSET
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x27D_OFFSET
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x29C_OFFSET
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x2BB_OFFSET
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x2DA_OFFSET
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x2F9_OFFSET
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x318_OFFSET
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x337_OFFSET
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x356_OFFSET
XSK_EFUSEPS_APB_TRIM_BITS_END_ADDR_OFFSET
XSK_EFUSEPS_APB_XILINX_RSVD_BITS_START_ADDR_OFFSET
XSK_EFUSEPS_APB_XILINX_RSVD_BITS_END_ADDR_OFFSET
XSK_EFUSEPS_APB_BISR_BITS_START_ADDR_OFFSET
XSK_EFUSEPS_APB_BISR_BITS_END_ADDR_OFFSET
XSK_EFUSEPS_APB_TRIM_BITS_START_ADDR_2ND_HALF_OFFSET
< Xilinx reserved Tests bits in the Second half of the eFUSE block offsets
XSK_EFUSEPS_APB_TRIM_BITS_END_ADDR_2ND_HALF_OFFSET
XSK_EFUSEPS_APB_XILINX_RSVD_BITS_START_ADDR_2ND_HALF_OFFSET
XSK_EFUSEPS_APB_XILINX_RSVD_BITS_END_ADDR_2ND_HALF_OFFSET
XSK_EFUSEPS_APB_BISR_BITS_START_ADDR_2ND_HALF_OFFSET
XSK_EFUSEPS_APB_BISR_BITS_END_ADDR_2ND_HALF_OFFSET
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x20
< Xilinx reserved Tests bits in the First half of the eFUSE block address
Referenced by XilSKey_EfusePs_IsAddressXilRestricted.
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x41
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x62
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x83
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_xA4
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_xC5
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_xE6
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x107
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x128
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x149
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x23F
< Xilinx reserved Tests bits in the First half of the eFUSE block address
Referenced by XilSKey_EfusePs_IsAddressXilRestricted.
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x25E
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x27D
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x29C
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x2BB
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x2DA
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x2F9
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x318
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x337
XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x356
XSK_EFUSEPS_APB_TRIM_BITS_START_ADDR
< Xilinx reserved Tests bits in the First half of the eFUSE block address
Referenced by XilSKey_EfusePs_IsAddressXilRestricted.
XSK_EFUSEPS_APB_TRIM_BITS_END_ADDR
XSK_EFUSEPS_APB_XILINX_RSVD_BITS_START_ADDR
XSK_EFUSEPS_APB_XILINX_RSVD_BITS_END_ADDR
XSK_EFUSEPS_APB_BISR_BITS_START_ADDR
XSK_EFUSEPS_APB_BISR_BITS_END_ADDR
XSK_EFUSEPS_APB_TRIM_BITS_START_ADDR_2ND_HALF
< Xilinx reserved Tests bits in the Second half of the eFUSE block address
Referenced by XilSKey_EfusePs_IsAddressXilRestricted.
XSK_EFUSEPS_APB_TRIM_BITS_END_ADDR_2ND_HALF
XSK_EFUSEPS_APB_XILINX_RSVD_BITS_START_ADDR_2ND_HALF
XSK_EFUSEPS_APB_XILINX_RSVD_BITS_END_ADDR_2ND_HALF
XSK_EFUSEPS_APB_BISR_BITS_START_ADDR_2ND_HALF
XSK_EFUSEPS_APB_BISR_BITS_END_ADDR_2ND_HALF
XSK_EFUSEPS_RSA_KEY_HASH_LEN_BITS
Rsa Key hash length in bits.
XSK_EFUSEPS_RSA_HASH_LEN_ECC_CALC
Rsa Key hash length calculation.
XSK_EFUSEPS_PRGM_STROBE_WIDTH
Strobe width calculation.
Referenced by XilSKey_EfusePs_ControllerConfig.
XSK_EFUSEPS_RD_STROBE_WIDTH
Modified to have max of 32 bit value.
Referenced by XilSKey_EfusePs_ControllerConfig.
XSK_EFUSEPS_BASE_ADDRESS
PSS eFUSE Register addresses.
eFuse base address
XSK_EFUSEPS_WR_LOCK_REG_OFFSET
WR_LOCK Write lock offset.
XSK_EFUSEPS_WR_UNLOCK_REG_OFFSET
WR_UNLOCK Write 0xDF0D to allow write offset.
XSK_EFUSEPS_WR_LOCK_STATUS_REG_OFFSET
WR_LOCKSTA Write protection status offset.
XSK_EFUSEPS_CONFIG_REG_OFFSET
CFG Configuration register offset.
XSK_EFUSEPS_STATUS_REG_OFFSET
STATUS Status register offset.
XSK_EFUSEPS_CONTROL_REG_OFFSET
CONTROL Control register offset.
XSK_EFUSEPS_PGM_STBW_REG_OFFSET
PGM_STBW eFuse program strobe width register offset.
XSK_EFUSEPS_RD_STBW_REG_OFFSET
RD_STBW eFuse read strobe width register offset.
XSK_EFUSEPS_WR_LOCK_REG
WR_LOCK Write 0x767B to disallow write.
XSK_EFUSEPS_WR_UNLOCK_REG
WR_UNLOCK Write 0xDF0D to allow write.
XSK_EFUSEPS_WR_LOCK_STATUS_REG
WR_LOCKSTA Write protection status.
XSK_EFUSEPS_CONFIG_REG
CFG Configuration register.
Referenced by XilSKey_EfusePs_ControllerConfig.
XSK_EFUSEPS_STATUS_REG
STATUS Status register.
Referenced by XilSKey_EfusePs_ReadStatus.
XSK_EFUSEPS_CONTROL_REG
CONTROL Control register.
Referenced by XilSKey_EfusePs_ControllerSetReadWriteEnable.
XSK_EFUSEPS_PGM_STBW_REG
PGM_STBW eFuse program strobe width register.
Referenced by XilSKey_EfusePs_ControllerConfig.
XSK_EFUSEPS_RD_STBW_REG
RD_STBW eFuse read strobe width register.
PSS eFUSE register bit defines & description XSK_EFUSEPS_WR_LOCK_STATUS_REG (Write Protection Status Register)
Referenced by XilSKey_EfusePs_ControllerConfig.
XSK_EFUSEPS_WR_LOCK_STATUS_BIT
Current state of write protection mode of eFuse subsystem:- 0 Region is writable 1 Region is not writable.
Any attempted writes are ignored, but reads will complete as normal.XSK_EFUSEPS_CONFIG_REG (Configuration Register)
XSK_EFUSEPS_CONFIG_REDUNDANCY
Redundancy mode, if set, else single mode.
This bit only applies to APB access. BISR and eFuse reader always work in redundancy mode.
XSK_EFUSEPS_CONFIG_TSU_H_A
eFuse read/program setup/hold control between address and strobe assert 1 b0 1 ref clock cycle 1 b1 2 ref clock cycles
Referenced by XilSKey_EfusePs_ControllerConfig.
XSK_EFUSEPS_CONFIG_TSU_H_CS
eFuse read/program setup/hold control between csb and strobe assert 1 b0 1 ref clock cycle 1 b1 2 ref clock cycles
XSK_EFUSEPS_CONFIG_TSU_H_PS
eFuse program setup/hold control between ps and csb active
XSK_EFUSEPS_CONFIG_CLK_DIV
Reference clock scaler 2 b00 bypass clock divider 2 b01 div 2 2 b10 div 4 2 h11 div 8.
XSK_EFUSEPS_STATUS_REG (Status Register)
XSK_EFUSEPS_STATUS_BISR_DONE
Status Register containing BISR Controller status, trim value, and security debug info.
Build in self test finished at boot time
XSK_EFUSEPS_STATUS_BISR_GO
Build in self test finished successfully.
XSK_EFUSEPS_STATUS_BISR_BLANK
eFuse box is blank, i.e., not yet been written to, if set
XSK_EFUSEPS_STATUS_SDEBUG_DIS
Security debug status, with authentication 0 security debug enabled 1 security debug disabled.
XSK_EFUSEPS_STATUS_WR_PROTECT
eFuse write protection, if either bit is set, writes to the eFuse box are disabled
XSK_EFUSEPS_STATUS_TRIM
Analog trim value.
XSK_EFUSEPS_CONTROL_PS_EN
XSK_EFUSEPS_CONTROL_REG (Control register for eFuse program, read and write control) eFuse ps control, enable programming if set.
Referenced by XilSKey_EfusePs_ControllerSetReadWriteEnable.
XSK_EFUSEPS_CONTROL_WR_DIS
eFuse write disable, if set.
Referenced by XilSKey_EfusePs_ControllerSetReadWriteEnable.
XSK_EFUSEPS_CONTROL_RD_DIS
eFuse read disable, if set
Referenced by XilSKey_EfusePs_ControllerSetReadWriteEnable.
XSK_EFUSEPS_APB_START_ADDR_OFFSET
eFuse memory APB Customer key start address offset
XSK_EFUSEPS_APB_WRITE_PROTECTION_ADDR_1_OFFSET
eFuse memory APB Customer key first half start address offset
XSK_EFUSEPS_APB_WRITE_PROTECTION_ADDR_2_OFFSET
eFuse memory APB Customer key second half start address offset
XSK_EFUSEPS_APB_ROM_128K_CRC_ENABLE_OFFSET
eFUSE APB address for ROM 128k CRC enable offset
XSK_EFUSEPS_APB_RSA_AUTH_ENABLE_OFFSET
eFUSE APB address for RSA authentication enable offset
XSK_EFUSEPS_APB_DFT_JTAG_DISABLE_OFFSET
eFUSE DFT JTAG disable
XSK_EFUSEPS_APB_DFT_MODE_DISABLE_OFFSET
eFUSE DFT mode disable
XSK_EFUSEPS_APB_ROM_UART_STATUS_ENABLE_OFFSET
eFUSE APB address for RSA uart status enable on MIO48 offset
XSK_EFUSEPS_APB_ROM_NONSECURE_INITB_ENABLE_OFFSET
eFUSE APB address for non-secure INIT_B signaling offset
XSK_EFUSEPS_APB_CUSTOMER_KEY_FIRST_HALF_START_ADDR_OFFSET
eFUSE bits from 0 to 0x1F and 0x180 to 0x1FF in the First half, and bits from 0x200 to 0x21F and 0x380 to 0x3FF in the Second half(if Single mode is enabled)
If Redundant mode is enabled only First half addresses are valid. eFuse memory APB Customer key first half start address
XSK_EFUSEPS_APB_CUSTOMER_KEY_FIRST_HALF_END_ADDR_OFFSET
eFuse memory APB Customer key first half end address
XSK_EFUSEPS_APB_CUSTOMER_KEY_SECND_HALF_START_ADDR_OFFSET
If Single mode is enabled both First and Second half addresses are valid.
eFuse memory APB Customer key second half start address
XSK_EFUSEPS_APB_CUSTOMER_KEY_SECND_HALF_END_ADDR_OFFSET
eFuse memory APB Customer key second half end address
XSK_EFUSEPS_APB_MIRROR_ADDRESS
Mirror Address = addr + 2nd half start address + mirror offset.
XSK_EFUSEPS_APB_START_ADDR
eFuse memory APB start address
XSK_EFUSEPS_APB_WRITE_PROTECTION_ADDR_1
eFuse memory APB Customer key second half start address
Referenced by XilSKey_EfusePs_Write.
XSK_EFUSEPS_APB_WRITE_PROTECTION_ADDR_2
eFuse memory APB Customer key second half start address
Referenced by XilSKey_EfusePs_Write.
XSK_EFUSEPS_APB_ROM_128K_CRC_ENABLE
eFUSE APB address for ROM 128k CRC enable
Referenced by XilSKey_EfusePs_Write.
XSK_EFUSEPS_APB_RSA_AUTH_ENABLE
eFUSE APB address for RSA authentication enable
Referenced by XilSKey_EfusePs_Write.
XSK_EFUSEPS_APB_DFT_JTAG_DISABLE
eFuse DFT JTAG disable
Referenced by XilSKey_EfusePs_Write.
XSK_EFUSEPS_APB_DFT_MODE_DISABLE
eFuse DFT mode disable
Referenced by XilSKey_EfusePs_Write.
XSK_EFUSEPS_APB_ROM_UART_STATUS_ENABLE
eFUSE APB address for RSA uart status enable on MIO48
XSK_EFUSEPS_APB_ROM_NONSECURE_INITB_ENABLE
eFUSE APB address for non-secure INIT_B signaling
XSK_EFUSEPS_APB_CUSTOMER_KEY_FIRST_HALF_START_ADDR
eFUSE bits from 0 to 0x1F and 0x180 to 0x1FF in the First half, and bits from 0x200 to 0x21F and 0x380 to 0x3FF in the Second half(if Single mode is enabled)
If Redundant mode is enabled only First half addresses are valid.eFuse memory APB Customer key first half start address
XSK_EFUSEPS_APB_CUSTOMER_KEY_FIRST_HALF_END_ADDR
eFuse memory APB Customer key first half end address
XSK_EFUSEPS_APB_CUSTOMER_KEY_SECND_HALF_START_ADDR
If Single mode is enabled both First and Second half addresses are valid.
eFuse memory APB Customer key second half start address
XSK_EFUSEPS_APB_CUSTOMER_KEY_SECND_HALF_END_ADDR
eFuse memory APB Customer key second half end address
XSK_EFUSEPS_APB_MIRROR_ADDRESS
Mirror Address = addr + 2nd half start address + mirror offset.
XSK_EFUSEPS_CONTROLER_LOCK
This macro is used to lock the efuse controller.
Referenced by XilSKey_EfusePs_Read, XilSKey_EfusePs_Write.
XSK_EFUSEPS_CONTROLER_UNLOCK
This macro is used to unlock the efuse controller.
Referenced by XilSKey_EfusePs_Read, XilSKey_EfusePs_ReadStatus, XilSKey_EfusePs_Write.
XSK_EFUSEPS_CONTROLER_LOCK_STATUS
This macro is used to check the status whether eFuse controller is locked or not.
- TRUE if the 32 bit Value read from the specified input address FALSE if the 32 bit Value not read from the specified input address
Referenced by XilSKey_EfusePs_Read, XilSKey_EfusePs_ReadStatus, XilSKey_EfusePs_Write.
XSK_EFUSEPS_CONTROLER_OP_MODE
This macro is used to determine operation mode of efuse controller.
TRUE if eFuse controller mode is redundancy FALSE if eFuse controller mode is single
XilSKey_EfusePs_IsEfuseWriteProtected
This macro is used to check whether eFuse is write protected or not.
TRUE if eFuse is write protected. FALSE is eFuse is not write protected.
Referenced by XilSKey_EfusePs_Write.
void XilSKey_EfusePs_GenerateMatrixMap(void)
This function is used to generate the matrix map of the G and H for hamming code (31,26).
G is [31,5] and defined as [A|I], I is identity matrix of [5,5].None TDD Cases: Check the generated matrix Check the memory corruption of the generated matrix
References ErrorCodeIndex, Matrix.
u8 XilSKey_EfusePs_EccDecode(const u8 *Corrupt, u8 *Syndrome)
This function is used to decode the incoming encoded byte.
Corrupt is the input encoded data. It has 26 bit data with 5 bit parity data Syndrome is the output updated with the parity error information. position of the error in the data byte TDD Cases: Check the parameters Check the decode with out any error Check the decode with 1 bit error Check the decode with 2 bit error Check the decode for boundary cases Check for memory corruption
References ErrorCodeIndex, Matrix.
void XilSKey_EfusePs_EccEncode(const u8 *InData, u8 *Ecc)
This function is used to encode the incoming data byte.
It uses hamming (31,26) algorithm. 26 bits are encoded to 31 bits InData is 26 bit input data with each bit represented in one byte Ecc is the 31 bit encoded data with each bit represented in one byte None TDD Cases: Check the parameters Check the encoded data for different input data Check the input data for boundary cases Check for memory corruption
References Matrix.
u32 XilSKey_EfusePs_ControllerConfig(u8 CtrlMode, u32 RefClk, u8 ReadMode)
This function is used to set the controller mode, read mode along with the read and program strobe width values based on the reference clock.
CtrlMode is the mode of the controller XSK_EFUSEPS_REDUNDANCY_MODEXSK_EFUSEPS_SINGLE_MODE RefClk is the CPU 1x reference clock frequency. Clock frequency can be between 20MHz to 100MHz specified in Hz ReadMode is the read mode of the controller XSK_EFUSEPS_READ_MODE_NORMALXSK_EFUSEPS_READ_MODE_MARGIN_1XSK_EFUSEPS_READ_MODE_MARGIN_2 XST_SUCCESS no errors occurred. an error when controller mode is not supportedan error when reference clock is not supportedan error when read mode is not supported Test Cases: Check single mode in CFG Reg Check redundancy mode in CFG Reg Check strobe width values for write mode Check strobe width values for various read mode Check Normal Read mode setting in CFG Reg Check Margin 1 Read mode setting in CFG Reg Check Margin 2 Read mode setting in CFG Reg Boundary Conditions
References XSK_EFUSEPS_CONFIG_REG, XSK_EFUSEPS_CONFIG_TSU_H_A, XSK_EFUSEPS_ERROR_CONTROLLER_MODE, XSK_EFUSEPS_ERROR_READ_MODE, XSK_EFUSEPS_ERROR_REF_CLOCK, XSK_EFUSEPS_PGM_STBW_REG, XSK_EFUSEPS_PRGM_STROBE_WIDTH, XSK_EFUSEPS_RD_STBW_REG, XSK_EFUSEPS_RD_STROBE_WIDTH, XSK_EFUSEPS_REFCLK_LOW_FREQ, XSK_EFUSEPS_SINGLE_MODE.
Referenced by XilSKey_EfusePs_Read, XilSKey_EfusePs_Write.
u8 XilSKey_EfusePs_IsAddressXilRestricted(u32 Addr)
This function is used to check whether eFuse bit is xilinx reserved bit or not.
Addr is the address of the eFuse bit. XST_SUCCESS if address corresponds to restricted eFuse bit. XST_FAILURE is address corresponds to non-restricted eFuse bit. Test Cases: with different address values Boundary values for addr
References XSK_EFUSEPS_APB_TRIM_BITS_START_ADDR, XSK_EFUSEPS_APB_TRIM_BITS_START_ADDR_2ND_HALF, XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x20, XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x23F.
Referenced by XilSKey_EfusePs_ReadEfuseBit, XilSKey_EfusePs_WriteEfuseBit.
void XilSKey_EfusePs_ControllerSetReadWriteEnable(u32 ReadWriteEnable)
This function is used to enable the read/write/program the eFUSE array.
ReadWriteEnable 0x1 - Enable programming 0x2 - Enable read 0x4 - Enable write Test Cases
References XSK_EFUSEPS_CONTROL_PS_EN, XSK_EFUSEPS_CONTROL_RD_DIS, XSK_EFUSEPS_CONTROL_REG, XSK_EFUSEPS_CONTROL_WR_DIS, XSK_EFUSEPS_ENABLE_PROGRAMMING.
Referenced by XilSKey_EfusePs_Read, XilSKey_EfusePs_Write.
u32 XilSKey_EfusePs_ReadEfuseBit(u32 Addr, u8 *Data)
This function is used to read the eFuse bit value.
Before using this function set the controller mode and read mode as required. Also, strobe width values are to be set properly based on the reference clock for successful reading Addr is the address of the eFuse bit. Data has the read eFuse value stored in it. XST_SUCCESS for successfully reading the value. an error when addr is restricted Test Cases Read in Single mode Read in redundancy mode Read for restricted address Boundary Checks for address
References XilSKey_EfusePs_IsAddressXilRestricted, XSK_EFUSEPS_ERROR_ADDRESS_XIL_RESTRICTED.
u32 XilSKey_EfusePs_WriteEfuseBit(u32 Addr)
This function is used to program the eFuse bit value.
Before using this function set the controller mode and read mode as required. Also, strobe width values are to be set properly based on the reference clock for successful programming Addr is the address of the eFuse bit. XST_SUCCESS after successful writing. an error when addr is restricted Test Cases Write in Single mode Write in redundancy mode Write for restricted address Boundary Checks for address Strobe width are not proper (Check if it makes sense)
References XilSKey_Efuse_IsTimerExpired, XilSKey_Efuse_SetTimeOut, XilSKey_EfusePs_IsAddressXilRestricted, XSK_EFUSEPS_ERROR_ADDRESS_XIL_RESTRICTED.