xilskey_epl.c
u8 XilSKey_EfusePl_ProgramBit(u8 Row, u8 Bit)
< Prototype declarations for PL eFUSE interface functions
Programs a bit of PL eFUSE row. Row - row number Bit - bit position - XST_FAILURE - In case of failure - XST_SUCCESS - In case of Success Updates the global variable ErrorCode with error code(if any).
u8 XilSKey_EfusePl_ProgramRow(u8 Row, u8 *RowData)
Programs PL eFUSE row.
Row - row number RowData - row data pointer - XST_FAILURE - In case of failure - XST_SUCCESS - In case of Success Updates the global variable ErrorCode with error code(if any).
u8 XilSKey_EfusePl_ProgramControlRegister(u8 *CtrlData)
Programs PL eFUSE Control Register.
CtrlData - Control data pointer - XST_FAILURE - In case of failure - XST_SUCCESS - In case of Success Updates the global variable ErrorCode with error code(if any).
u8 XilSKey_EfusePl_ReadBit(u8 Row, u8 Bit, u8 MarginOption, u8 *BitData)
Reads a PL eFUSE bit & stores.
Row - row number Bit - bit position in the specified row MarginOption - Margin Option(One of the reading method of PLeFUSE) BitData - Place holder to store the read value - XST_FAILURE - In case of failure - XST_SUCCESS - In case of Success Updates the global variable ErrorCode with error code(if any).
u8 XilSKey_EfusePl_ReadRow(u32 Row, u8 MarginOption, u8 *RowDataBytes)
Reads row data of a specified row.
Row - row number MarginOption - Margin Option(One of the reading method of PLeFUSE) RowDataBytes - To store the read data bytes of specified row - XST_FAILURE - In case of failure - XST_SUCCESS - In case of Success Read data will be stored
u8 XilSKey_EfusePl_ReadControlRegister(u8 *CtrlData)
Reads PL eFUSE Control Register data.
CtrlData - Place holder to store the read data (control register) - XST_FAILURE - In case of failure - XST_SUCCESS - In case of Success Updates the global variable ErrorCode with error code (if any)
u8 XilSKey_EfusePl_VerifyBit(u8 Row, u8 Bit)
Verify the PL eFUSE bit blown by reading it back in all possible margin reads (Normal, Margin 1 and Margin 2).
Row - row number Bit - bit position of the specified row - XST_FAILURE - In case of failure - XST_SUCCESS - In case of Success Updates the global variable ErrorCode with error code(if any).
u8 XilSKey_EfusePl_IsVectorAllZeros(u8 *RowDataPtr)
Checks whether data bits (0-29) of an PL eFUSE row are all zeroes or not.
RowDataPtr - row data pointer - XST_FAILURE - In case of failure - XST_SUCCESS - In case of Success None.
void XilSKey_EfusePl_CalculateEcc(u8 *RowData, u8 *ECCData)
Calculates and stores the ECC data of row data.
RowData - Pointer to row data on which ECC will be calculated ECCData - Pointer to store the calculated ECC None None.
static u8 XilSKey_EfusePl_VerifyAES_Ultrascale(u32 CrcValue)
Verify's the AES key by passing the CRC of expected key.
CrcValue is CRC of expected AES key XST_FAILURE - In case of failureXST_SUCCESS - In case of Success None.
u32 XilSKey_EfusePl_Program_Zynq(XilSKey_EPl *InstancePtr)
Programs PL eFUSE of Zynq.
InstancePtr is an instance of EFuse PL of Zynq. XST_FAILURE - In case of failureXST_SUCCESS - In case of Success Updates the global variable ErrorCode with error code(if any).
static u32 XilSKey_EfusePl_Program_AesKey_ultra(void)
Programs a AES key rows for PL eFUSE of Ultrascale.
XST_FAILURE - In case of failureXST_SUCCESS - In case of Success Updates the global variable ErrorCode with error code(if any).
static u32 XilSKey_EfusePl_Program_RowRange_ultra(u8 RowStart, u8 RowEnd, u8 *DataPrgrmg, u8 Page)
Programs a range of rows for PL eFUSE of Ultrascale.
RowStart is the starting row to be programmed. RowEnd is the row till which need to be programmed. DataPrgrmg is the data to be programmed. Page is the Page to be programmed. XST_FAILURE - In case of failureXST_SUCCESS - In case of Success Updates the global variable ErrorCode with error code(if any).
static u32 XilSKey_EfusePl_GetRowData_Ultra(u8 Row, u8 *RowData, u8 Page)
This API gets the row data of Ored Normal and Redundant rows for EFUSE of Ultrascale.
Row is the row number. RowData is the ORed result of both rows. Page indicates row belongs to which page. XST_FAILURE - In case of failureXST_SUCCESS - In case of Success Updates the global variable ErrorCode with error code(if any).
static u32 XilSKey_EfusePl_GetDataRowRange_Ultra(u8 RowStart, u8 RowEnd, u8 *KeyRead, u8 Page)
This API gets the rows data of given range of FUSE's array of Ultrascale.
RowStart is the starting row to be programmed. RowEnd is the row till which need to be programmed. KeyRead is a pointer of array in which read data is updated. Page is the Page to be programmed. XST_FAILURE - In case of failureXST_SUCCESS - In case of Success Updates the global variable ErrorCode with error code(if any). Reads all the margin options.
static u32 XilSKey_EfusePl_ReadKey_Zynq(XilSKey_EPl *InstancePtr)
Reads the PL efuse key (AES and user) of Zynq.
InstancePtr - Input data to be written to PL eFUSE XST_FAILURE - In case of failureXST_SUCCESS - In case of Success Updates the global variable ErrorCode with error code(if any).
static u32 XilSKey_EfusePl_ReadKey_Checks(XilSKey_EPl *InstancePtr)
Reads control register and checks the conditions for reading keys.
InstancePtr is an instance of PL efuse of ultrascale ErrorCode - In case of failureXST_SUCCESS - In case of Success None.
static u32 XilSKey_EfusePl_Program_Checks(XilSKey_EPl *InstancePtr)
This function checks the conditions for keys programming.
InstancePtr is an instance of EFusePL of Ultrascale. ErrorCode - In case of failureXST_SUCCESS - In case of Success None.
static u8 XilSKey_EfusePl_ProgramBit_Ultra(u8 Row, u8 Bit, u8 Redundant, u8 Page)
Programs the bit of given normal or redundant row of PL efuse key for Ultrascale.
Row is the row number of Fuse array. Bit is the bit position to be read. Redundant is the option to be selected either redundant row or normal row. Page is the page of Fuse array in which row has to be read XST_FAILURE - In case of failureXST_SUCCESS - In case of Success Updates the global variable ErrorCode with error code(if any).
static u8 XilSKey_EfusePl_ProgramRow_Ultra(u8 Row, u8 *RowData, u8 Redundant, u8 Page)
Programs the entire row PL efuse key for Ultrascale.
Row is the row number of Fuse array. RowData is a pointer to a variable to program the row. Redundant is the option to be selected either redundant row or normal row. Page is the page of Fuse array in which row has to be read XST_FAILURE - In case of failureXST_SUCCESS - In case of Success Updates the global variable ErrorCode with error code(if any).
static u8 XilSKey_EfusePl_ReadSecRegister(u8 *SecData)
Programs PL eFUSE reads Secure Register of Ultrascale.
SecData is a pointer to which holds the data read from Secure register of Fuse. XST_FAILURE - In case of failureXST_SUCCESS - In case of Success Updates the global variable ErrorCode with error code(if any).
static u8 XilSKey_EfusePl_ProgramSecRegister(u8 *SecData)
Programs PL eFUSE Secure Register of Ultrascale.
SecData is a pointer to which holds the data to be programmed. XST_FAILURE - In case of failureXST_SUCCESS - In case of Success Updates the global variable ErrorCode with error code(if any).
static u8 XilSKey_EfusePl_ReadBit_Ultra(u8 Row, u8 Bit, u8 MarginOption, u8 *BitData, u8 Redundant, u8 Page)
Reads the bit of given normal or redundant row of PL efuse key for Ultrascale.
Row is the row number of Fuse array. Bit is the bit position to be read. MarginOption is the option to select in which mode read has to be happened BitData is a pointer to a variable to store the read value of given given bit in provided row. Redundant is the option to be selected either redundant row or normal row. Page is the page of Fuse array in which row has to be read XST_FAILURE - In case of failureXST_SUCCESS - In case of Success Updates the global variable ErrorCode with error code(if any). Using this API can't read AES key bits of rows(20-27) as they can't read directly.
static u8 XilSKey_EfusePl_ReadRow_Ultra(u32 Row, u8 MarginOption, u8 *RowDataBytes, u8 Redundant, u8 Page)
Reads the given normal or redundant row of PL efuse key for Ultrascale.
Row is the row number of Fuse array. MarginOption is the option to select in which mode read has to be happened RowDataBytes is a pointer to an array to store the read value of given row. Redundant is the option to be selected either redundant row or normal row. Page is the page of Fuse array in which row has to be read XST_FAILURE - In case of failureXST_SUCCESS - In case of Success Updates the global variable ErrorCode with error code(if any). Using this API can't read AES key rows(20-27) as they can't read directly.
static u8 XilSKey_EfusePl_ProgramControlReg_Ultra(u8 *CtrlData)
Programs PL eFUSE Control Register of Ultrascale.
CtrlData - Control data pointer - XST_FAILURE - In case of failure - XST_SUCCESS - In case of Success Updates the global variable ErrorCode with error code(if any).
static u8 XilSkey_EfusePl_VerifyBit_Ultra(u8 Row, u8 Bit, u8 Redundant, u8 Page)
Verifies PL eFUSE bit of Ultrascale.
Row specifies the row number to be verified. Bit specifies bit number to be verified. Redundant is the option to be selected either redundant row or normal row. Page is the page of Fuse array in which row has to be read - XST_FAILURE - In case of failure - XST_SUCCESS - In case of Success None.
static u32 XilSkey_EfusePl_UserFuses_TobeProgrammed(u8 *UserFuses_Write, u8 *UserFuses_TobePrgrmd, u8 Size)
This function throws an error if user requests already programmed User FUSE bit to revert, and copies the bits to be programmed in particular row into provided UserFuses_TobePrgrmd pointer.
UserFuses_Write is a pointer to user requested programming bits of an User FUSE row. UserFuses_TobePrgrmd holds User FUSE row bits which needs to be programmed actually. Size specifies the User key size. XST_FAILURE: Returns error if user requests programmed bit to revertXST_SUCCESS: If User requests valid bits. If user requests a non-zero bit for making to zero throws an error which is not possible.
static u8 XilSKey_EfusePl_ProgramControlReg_Ultra_Plus(u8 *CtrlData)
Programs PL eFUSE Control Register of Ultrascale.
CtrlData - Control data pointer - XST_FAILURE - In case of failure - XST_SUCCESS - In case of Success Updates the global variable ErrorCode with error code(if any).
static u8 XilSKey_EfusePl_Ultra_Check(u8 Row, u8 Bit, u8 Redundant, u8 Page)
This API checks whether the parameters passed for programming or reading is correct.
Row is the row number of Fuse array. Bit is the bit position to be read. Redundant is the option to be selected either redundant row or normal row. Page is the page of Fuse array in which row has to be read XST_FAILURE - In case of failureXST_SUCCESS - In case of Success Updates the global variable ErrorCode with error code(if any).
static u32 XilSKey_EfusePl_ReadRowData_Ultra(u8 Row, u8 *RowData, u8 Page)
This function gets the row data of Ored Normal and Redundant rows for EFUSE of Ultrascale and ultrascale plus.
For ultrascale plus, read row contains both redundant and normal bits upper 16 bits contains redundant bits and lower 16 bits contain normal bits, each row will have only 16 valid bits. Row is the row number. RowData is the ORed result of both rows. Page indicates row belongs to which page. XST_FAILURE - In case of failureXST_SUCCESS - In case of Success Updates the global variable ErrorCode with error code(if any).
XSK_EFUSEPL_ARRAY_FUSE_CNTRL_ROW
Fuse Ctrl Row.
XSK_EFUSEPL_ARRAY_FUSE_AES_KEY_SIZE
AES Key size.
XSK_EFUSEPL_ARRAY_FUSE_USER_KEY_SIZE
32 bit User key size
XSK_EFUSEPL_ARRAY_FUSE_128BIT_USER_SIZE
128 bit User key size
XSK_EFUSEPL_ARRAY_MAX_ROW
PLeFUSE Max Rows.
XSK_EFUSEPL_ARRAY_MAX_COL
PLeFUSE Max Columns.
XSK_EFUSEPL_ARRAY_AES_DATA_ROW_START
AES Data Start Row.
XSK_EFUSEPL_ARRAY_AES_DATA_ROW_END
AES Data End Row.
XSK_EFUSEPL_ARRAY_USER_DATA_START_ROW
User Data Start Row.
XSK_EFUSEPL_ARRAY_AES_DATA_BITS_IN_30th_ROW
AES Data bits count in 30th Row.
XSK_EFUSEPL_ARRAY_MAX_COL_ULTRA_PLUS
Ultrascale plus max bits in a row.
XSK_EFUSEPL_ARRAY_USER_DATA_BITS_IN_30th_ROW
User Data bits count in 30th Row.
XSK_EFUSEPL_ARRAY_MAX_PAYLAOD_BITS_IN_A_ROW
Max Pay load in Row.
XSK_EFUSEPL_ARRAY_MAX_ECC_BITS_IN_A_ROW
Max ECC bits in a Row.
XSK_EFUSEPL_ARRAY_ECC_START_BIT_IN_A_ROW
ECC Start Bit position in a Row.
XSK_EFUSEPL_ARRAY_ECC_END_BIT_IN_A_ROW
ECC End Bit position in a Row.
XSK_EFUSEPL_ARRAY_FUSE_CNTRL_MAX_BITS
Fuse Control max bits.
XSK_EFUSEPL_ARRAY_FUSE_CNTRL_REDUNDENT_INDEX
Redundant bit Index.
XSK_EFUSEPL_ARRAY_FUSE_CNTRL_START_BIT
Fuse Control Start bit.
XSK_EFUSEPL_ARRAY_FUSE_CNTRL_END_BIT
Fuse Control Start bit.
XSK_EFUSEPL_ARRAY_UNSUPPORTED_BIT6
Unsupported bit.
XSK_EFUSEPL_ARRAY_UNSUPPORTED_BIT7
Unsupporte bit.
XSK_EFUSEPL_ARRAY_FUSE_CNTRL_REDUNDENT_START_BIT
Redundant bit start Index.
XSK_EFUSEPL_ARRAY_UNSUPPORTED_RED_FOR_BIT6
Unsupported bit.
XSK_EFUSEPL_ARRAY_UNSUPPORTED_RED_FOR_BIT7
Unsupported bit.
XSK_EFUSEPL_ARRAY_FUSE_CNTRL_REDUNDENT_END_BIT
Redundant bit End Index.
XSK_EFUSEPL_MAX_REF_CLK_FREQ
Max Ref Clk Frequency.
< Unsupported bit in ctrl registerMax Ref Clk Frequency
XSK_EFUSEPL_MIN_REF_CLK_FREQ
Min Ref Clk Frequency.
XSK_EFUSEPL_CNTRL_ROW_ULTRA
Control row of FUSE for Ultrascale series.
XSK_EFUSEPL_DNA_ROW_ULTRA
DNA row of FUSE for Ultrascale series.
XSK_EFUSEPL_AES_ROW_START_ULTRA
AES key start row of FUSE for Ultrascale series.
XSK_EFUSEPL_AES_ROW_END_ULTRA
AES key end row of FUSE for Ultrascale series.
XSK_EFUSEPL_USER_ROW_ULTRA
USER key start row of FUSE for Ultrascale series.
XSK_EFUSEPL_SEC_ROW_ULTRA
Secure row of FUSE for Ultrascale series.
XSK_EFUSEPL_RSA_ROW_START_ULTRA
RSA start row of FUSE for Ultrascale series.
XSK_EFUSEPL_RSA_ROW_END_ULTRA
RSA end row of FUSE for Ultrascale series.
XSK_EFUSEPL_USER_128BIT_ROW_START_ULTRA
128 bit USER key start row of FUSE for Ultrascale series
XSK_EFUSEPL_USER_128BIT_ROW_END_ULTRA
128 bit USER key end row of FUSE for Ultrascale series
XSK_EFUSEPL_DNA_KEY_SIZE_ULTRA
DNA key size of Ultrascale series.
XSK_EFUSEPL_RSA_HASH_SIZE_ULTRA
RSA hash size of Ultrascale series.
XSK_EFUSEPL_SEC_MAX_BITS_ULTRA
Secure row max bits of Ultrascale series.
XSK_EFUSEPL_CNTRL_MAX_BITS_ULTRA
Fuse Control max bits of Ultrascale series.
XSK_EFUSEPL_MAX_BITS_IN_A_ROW_ULTRA
Max Pay load in Row.
XSK_EFUSEPL_END_BIT_IN_A_ROW_ULTRA
FUSE end bit in a row of Ultrascale series.
XSK_EFUSEPL_CTRL_ROW_END_BIT_ULTRA
Control row end bit of Ultrascale series.
XSK_EFUSEPL_SEC_ROW_END_BIT_ULTRA
Secure row end bit of Ultrascale series.
XSK_EFUSEPL_CNTRL_ROW_START_ULTRA_PLUS
Control row of FUSE for Ultrascale plus series.
XSK_EFUSEPL_CNTRL_ROW_END_ULTRA_PLUS
Control row of FUSE for Ultrascale plus series.
XSK_EFUSEPL_DNA_ROW_START_ULTRA_PLUS
DNA row of FUSE for Ultrascale plus series.
XSK_EFUSEPL_DNA_ROW_END_ULTRA_PLUS
DNA row of FUSE for Ultrascale plus series.
XSK_EFUSEPL_AES_ROW_START_ULTRA_PLUS
AES key start row of FUSE for Ultrascale plus series.
XSK_EFUSEPL_AES_ROW_END_ULTRA_PLUS
AES key end row of FUSE for Ultrascale series.
XSK_EFUSEPL_USER_ROW_START_ULTRA_PLUS
USER key start row of FUSE for Ultrascale plus series.
XSK_EFUSEPL_USER_ROW_END_ULTRA_PLUS
USER key start row of FUSE for Ultrascale plus series.
XSK_EFUSEPL_SEC_ROW_ULTRA_PLUS
Secure row of FUSE for Ultrascale series.
XSK_EFUSEPL_RSA_ROW_START_ULTRA_PLUS
RSA start row of FUSE for Ultrascale plus series.
XSK_EFUSEPL_RSA_ROW_END_ULTRA_PLUS
RSA end row of FUSE for Ultrascale plus series.
XSK_EFUSEPL_USER_128BIT_ROW_START_ULTRA_PLUS
128 bit USER key start row of FUSE for Ultrascale plus series
XSK_EFUSEPL_USER_128BIT_ROW_END_ULTRA_PLUS
128 bit USER key end row of FUSE for Ultrascale plus series
XSK_EFUSEPL_CTRL_ROW_UNSUPPORT_BIT3_ULTRA
Unsupported bits of Control register.
XSK_EFUSEPL_CTRL_ROW_UNSUPPORT_BIT4_ULTRA
< Unsupported bit in ctrl register
XSK_EFUSEPL_CTRL_ROW_UNSUPPORT_BIT_RANGE_START_ULTRA
< Unsupported bit in ctrl register
XSK_EFUSEPL_CTRL_ROW_UNSUPPORT_BIT_RANGE_END_ULTRA
< Unsupported bit in ctrl register
XSK_EFUSEPL_MAX_REF_CLK_FREQ
Max Ref Clk Frequency.
< Unsupported bit in ctrl registerMax Ref Clk Frequency
XSK_EFUSEPL_MIN_REF_CLK_FREQ
Min Ref Clk Frequency.
XSK_EFUSEPL_PAGE_0_ULTRA
Page 0 for Ultrascale series.
XSK_EFUSEPL_PAGE_1_ULTRA
Page 1 for Ultrascale series.
XSK_EFUSEPL_REDUNDANT_ULTRA
Redundant read selection for Ultrascale series.
XSK_EFUSEPL_NORMAL_ULTRA
Normal read selection for Ultrascale series.
XSK_WORD_SIZE_IN_BYTES
Size of a 32-bit word in bytes.
XSK_EfusePl_MarginOption
Margin 1.
XSKEfusePl_FuseCntrlBits
Bit1 of Fuse Ctrl Row.
XSKEfusePl_FuseCntrlBits_Ultra
Bit 0 of Fuse Ctrl row of Ultrascale.
XSKEfusePl_FuseSecureBits_Ultra
Bit 0 of Fuse Secure row of Ultrascale.
u32 ErrorCode
Global variable which holds the error key.
u8 AesDataInBytes[XSK_EFUSEPL_ARRAY_FUSE_AES_KEY_SIZE][XSK_EFUSEPL_ARRAY_FUSE_AES_KEY_SIZE]
u8 UserDataInBytes[XSK_EFUSEPL_ARRAY_FUSE_USER_KEY_SIZE][XSK_EFUSEPL_ARRAY_FUSE_USER_KEY_SIZE]
XSKEfusePl_Fpga PlFpgaFlag
For Storing Fpga series.
Referenced by JtagAES_Check_Ultrascale, JtagRead_Ultrascale, JtagWrite_Ultrascale.
u8 CtrlBitsUltra[XSK_EFUSEPL_ARRAY_MAX_ROW][XSK_EFUSEPL_ARRAY_MAX_ROW]
XilSKey_JtagSlr XilSKeyJtag
JTAG Tap Instance.
int JtagServerInit(XilSKey_EPl *PlInstancePtr)
JTAG Server Initialization routine.
void JtagWrite(unsigned char row, unsigned char bit)
JTAG Server Write routine.
void JtagRead(unsigned char row, unsigned int *row_data, unsigned char marginOption)
JTAG Server Read routine.
int JtagWrite_Ultrascale(u8 Row, u8 Bit, u8 Page, u8 Redundant)
This function blows the fuse of Ultrascale with provided parameters.
Row specifies the row number of EFUSE to blow. Bit Specifies the bit location in the given row. Page tell the page of EFUSE in which the given row is located. Redundant is a flag to specify the bit to be programmed is Normal bit or Redundant bit. Redundant - XSK_EFUSEPL_REDUNDANT_ULTRANormal - XSK_EFUSEPL_NORMAL_ULTRA None. None.
void JtagRead_Ultrascale(u8 Row, u32 *RowData, u8 MarginOption, u8 Page, u8 Redundant)
This function reads entire row of Ultrascale's EFUSE.
Row specifies the row number of EFUSE. MarginOption is a variable which tells the margin option in which read operation to be performed. Page tell the page of EFUSE in which the given row is located. Redundant is a flag to specify the bit to be programmed is Normal bit or Redundant bit. Redundant - XSK_EFUSEPL_REDUNDANT_ULTRANormal - XSK_EFUSEPL_NORMAL_ULTRA This variable is not valid for Ultrascale plus as each row contains both redundant and normal bits upper 16 are redundant. None. Method to read FUSE register in Direct Macro Access way. Go to TLR to clear FUSE_CTS Load FUSE_CTS instruction on IR Step to CDR/SDR to shift in 32-bits FUSE_CTS command word Shift in MAGIC_CTS_WRITE "FEED28AC" for ultrascale Read 64 bit data in IR read state.
void JtagRead_Status_Ultrascale(u32 *Rowdata)
This function reads the status row of Ultrascale's EFUSE and updates the pointer.
Rowdata is a pointer to a 32 bit variable which stores the status register value read from EFUSE status register. None. Method to read FUSE register in Direct Macro Access way. For reading the status values we need send the bitstream in shift DR state. Shift in MAGIC_CTS_WRITE "FEED28AC" for ultrascale Read 64 bit data in IR read state.
u32 JtagAES_Check_Ultrascale(u32 *Crc, u8 MarginOption)
This function verifies the AES key of Ultrascale's EFUSE with provided CRC value.
Crc is a pointer to a 32 bit variable which holds the expected AES key's CRC. MarginOption is a variable which tells the margin option in which read operation to be performed. Returns XST_FAILURE/XST_SUCCESS XST_SUCCESS - If CRC is correctXST_FAILURE - If CRC is wrong To verify AES key with provided CRC 256 bits need to be written with all ZEROS and last 32 bits with CRC. And then CTS word should be framed and read 9 rows. The keys are stored in 8 rows (20 to 27) but in UltraScale the device will read all 1s. On the 9th read (row 28), the CRC computation takes place. An extra read after the 9th read is required to read the computed CRC out (can use last row addr of 28 or row 0). The FPGA internally compares the computed CRC with the expected CRC loaded through the FUSE_KEY operation. If they match, then the expected CRC is read. If not, the FPGA will return all 1s.
u32 XilSKey_EfusePl_SystemInit(XilSKey_EPl *InstancePtr)
Initializes PL eFUSE with input data given.
InstancePtr - Input data to be written to PL eFUSE - XST_FAILURE - In case of failure - XST_SUCCESS - In case of Success Updates the global variable ErrorCode with error code(if any).
References XSK_EFUSEPL_ERROR_PL_STRUCT_NULL.
Referenced by main.
u32 XilSKey_EfusePl_Program(XilSKey_EPl *InstancePtr)
Programs PL eFUSE with input data given through InstancePtr.
InstancePtr - Pointer to PL eFUSE instance which holds the input data to be written to PL eFUSE. XST_FAILURE - In case of failureXST_SUCCESS - In case of Success When this API is called: Initializes the timer, XADC/xsysmon and JTAG server subsystems. Returns an error in the following cases, if the reference clock frequency is not in the range or if the PL DAP ID is not identified, if the system is not in a position to write the requested PL eFUSE bits (because the bits are already written or not allowed to write) if the temperature and voltage are not within range.
Referenced by main.
u32 XilSKey_EfusePl_ReadStatus(XilSKey_EPl *InstancePtr, u32 *StatusBits)
Reads the PL efuse status bits and gets all secure and control bits.
InstancePtr Pointer to PL eFUSE instance. StatusBits Buffer to store the status bits read. - XST_FAILURE - In case of failure - XST_SUCCESS - In case of Success
Referenced by XilSKey_EfusePl_ReadnCheck.
u32 XilSKey_EfusePl_ReadKey(XilSKey_EPl *InstancePtr)
Reads the PL efuse keys and stores them in the corresponding arrays in instance structure.
InstancePtr Pointer to PL eFUSE instance. - XST_FAILURE - In case of failure - XST_SUCCESS - In case of Success This function initializes the timer, XADC and JTAG server subsystems, if not already done so. In Zynq - Reads AES key and User keys. In Ultrascale - Reads 32 bit and 128 bit User keys and RSA hash But AES key cannot be read directly it can be verified with CRC check (for that we need to update the instance with 32 bit CRC value, API updates whether provided CRC value is matched with actuals or not). To calculate the CRC of expected AES key one can use any of the following APIs XilSKey_CrcCalculation() or XilSkey_CrcCalculation_AesKey()
Referenced by XilSKey_EfusePl_ReadnCheck.