xilskey_eps.c
u8 Matrix[31][5][31][5]
PS eFUSE Matrix.
Referenced by XilSKey_EfusePs_EccDecode, XilSKey_EfusePs_EccEncode, XilSKey_EfusePs_GenerateMatrixMap.
u8 ErrorCodeIndex[32][32]
Error Code Array.
Referenced by XilSKey_EfusePs_EccDecode, XilSKey_EfusePs_GenerateMatrixMap.
static u32 XilSKey_EfusePs_WriteWithXadcCheckAndVerify(u32 EfuseAddress, u32 RefClk)
This function is used to to write the Single eFUSE which checks for XADC temperature and voltage and verifies the written bit in the eFUSE Verification of the bit is done by reading the bit in margin 1 mode and normal mode.
Temperature and voltage are read from XADC and verified for the correct range EfuseAddress is the address of the eFUSE bit to be written RefClk is the reference clock frequency. Clock frequency can be between 20MHz to 60MHz specified in Hz XST_SUCCESS no errors occurred an error XSK_EFUSEPS_ERROR_WRITE_VCCPAUX_VOLTAGE_OUT_OF_RANGE when voltage not in rangean error XSK_EFUSEPS_ERROR_WRITE_TEMPERATURE_OUT_OF_RANGE when temperature not in rangeOther errors because of internal functions and can be checked in xilskey_utils.h
static u32 XilSKey_EfusePs_WriteRsaKeyHash(u8 *RsaKeyHashBuf, u32 RefClk)
This function is used to write the RSA hash in the eFUSE Array in Little Endian.
RsaKeyHashBuf is the buffer containing the RSA hash to be written to the eFUSE array. RefClk is the reference clock frequency. Clock frequency can be between 20MHz to 60MHz specified in Hz XST_SUCCESS no errors occurred. Other errors because of internal controller functions and can be checked in xilskey_utils.h
static u32 XilSKey_EfusePs_ReadRsaKeyHash(u8 *RsaKeyHashBuf, u32 RefClk)
This function is used to Read the RSA hash in the eFUSE Array in Little Endian.
RsaKeyHashBuf is the output buffer where RSA hash is copied from the eFUSE array after hamming decode. RefClk is the reference clock frequency. Clock frequency can be between 20MHz to 60MHz specified in Hz XST_SUCCESS no errors occurred. Other errors because of internal controller functions and can be checked in xeFUSEutils.h
static u32 XilSKey_EfusePs_ReadWithXadcCheck(u32 EfuseAddress, u32 RefClk, u8 *Data)
This function is used to read the PS eFUSE bit.
Reading of the eFUSE bit is done in NORMAL read mode. Temperature and voltage must be in specified range for reading. EfuseAddress is the address of the eFUSE bit RefClk is the reference clock frequency. Clock frequency can be between 20MHz to 60MHz specified in Hz Data is where the read data is stored. It will have values 0 or 1 XST_SUCCESS no errors occurred. an error XSK_EFUSEPS_ERROR_READ_VCCPAUX_VOLTAGE_OUT_OF_RANGE when voltage not in rangean error XSK_EFUSEPS_ERROR_READ_TMEPERATURE_OUT_OF_RANGE when temperature not in rangeOther errors because of internal controller functions and can be checked in xilskey_utils.h
static u32 XilSKey_EfusePs_VerifyWithXadcCheck(u32 EfuseAddress, u32 RefClk)
This function is used to verify the written eFUSE bit.
It is checked against the value of 1 only. Verification of the eFUSE bit is done by reading in MARGIN 2 mode which was highest margin. EfuseAddress is the address of the eFUSE bit RefClk is the reference clock frequency. Clock frequency can be between 20MHz to 60MHz specified in Hz XST_SUCCESS no errors occurred. XST_FAILURE an error occurred during verifying the PS eFUSE.an error XSK_EFUSEPS_ERROR_READ_VCCPAUX_VOLTAGE_OUT_OF_RANGE when voltage not in rangean error XSK_EFUSEPS_ERROR_READ_TMEPERATURE_OUT_OF_RANGE when temperature not in rangean error XSK_EFUSEPS_ERROR_VERIFICATION when verification failsOther errors because of internal controller functions and can be checked in xilskey_utils.h
static u32 XilSKey_EfusePs_CheckRsaHashForAllZeros(u32 RefClk)
This function is used to check the RSA Hash for all zeros.
RefClk is the reference clock frequency. Clock frequency can be between 20MHz to 60MHz specified in Hz XST_SUCCESS if RSA Hash eFUSE bits are all zeros. XSK_EFUSEPS_ERROR_RSA_HASH_ALREADY_PROGRAMMED if any RSA hash eFUSE bit is setOther errors because of internal controller functions and can be checked in xilskey_utils.h.
static void XilSKey_EfusePs_SetControllerMode(u8 Mode)
This function is used to set the controller mode to Redundancy/Single mode.
Mode is mode of the controller to the set. REDUNDANCY_MODESINGLE_MODE None
static void XilSKey_EfusePs_SetControllerReadMode(u8 ReadMode)
This function is used to set the controller read mode to Normal/Margin 1/Margin 2.
ReadMode is the read mode of the controller XSK_EFUSEPS_READ_MODE_NORMALXSK_EFUSEPS_READ_MODE_MARGIN_1XSK_EFUSEPS_READ_MODE_MARGIN_2 None
static u8 XilSKey_EfusePs_IsReadModeSupported(u8 ReadMode)
This function is used to check the read mode supported.
ReadMode is input read mode to be checked against XST_SUCCESS if read mode is supported XST_FAILURE if read mode is not supported
u32 XilSKey_EfusePs_Write(XilSKey_EPs *InstancePtr)
This function is used to write to the PS eFUSE.
PS eFUSE interface functions. InstancePtr - Pointer to the PsEfuseHandle which describes which PS eFUSE bit should be burned. XST_SUCCESS.In case of error, value is as defined in xilskey_utils.h Error value is a combination of Upper 8 bit value and Lower 8 bit value. For example, 0x8A03 should be checked in error.h as 0x8A00 and 0x03. Upper 8 bit value signifies the major error and lower 8 bit values tells more precisely. When called, this Initializes the timer, XADC subsystems. Unlocks the PS eFUSE controller.Configures the PS eFUSE controller. Writes the hash and control bits if requested. Programs the PS eFUSE to enable the RSA authentication if requested. Locks the PS eFUSE controller. Returns an error, if the reference clock frequency is not in between 20 and 60 MHz or if the system not in a position to write the requested PS eFUSE bits (because the bits are already written or not allowed to write) or if the temperature and voltage are not within range
References XSK_EFUSEPS_ERROR_PS_STRUCT_NULL, XilSKey_Timer_Intialise, XSK_EFUSEPS_ERROR_PS_PARAMETER_WRONG, XilSKey_EfusePs_XAdcInit, XSK_EFUSEPS_ERROR_XADC_INIT, XSK_EFUSEPS_CONTROLER_UNLOCK, XSK_EFUSEPS_CONTROLER_LOCK_STATUS, XSK_EFUSEPS_ERROR_CONTROLLER_LOCK, XilSKey_EfusePs_IsEfuseWriteProtected, XSK_EFUSEPS_ERROR_EFUSE_WRITE_PROTECTED, XilSKey_EfusePs_ControllerConfig, XSK_EFUSEPS_SINGLE_MODE, XSK_EFUSEPS_READ_MODE_NORMAL, XSK_EFUSEPS_ERROR_CONTROLLER_CONFIG, XilSKey_EfusePs_ControllerSetReadWriteEnable, XSK_EFUSEPS_ENABLE_PROGRAMMING, XilSKey_Efuse_StartTimer, XSK_EFUSEPS_APB_ROM_128K_CRC_ENABLE, XSK_EFUSEPS_ERROR_WRITE_128K_CRC_BIT, XSK_EFUSEPS_ERROR_READ_HASH_BEFORE_PROGRAMMING, XSK_EFUSEPS_ERROR_WRITE_RSA_HASH, XSK_EFUSEPS_APB_RSA_AUTH_ENABLE, XSK_EFUSEPS_ERROR_WRITE_RSA_AUTH_BIT, XSK_EFUSEPS_APB_DFT_JTAG_DISABLE, XSK_EFUSEPS_ERROR_WRTIE_DFT_JTAG_DIS_BIT, XSK_EFUSEPS_APB_DFT_MODE_DISABLE, XSK_EFUSEPS_ERROR_WRTIE_DFT_MODE_DIS_BIT, XSK_EFUSEPS_APB_WRITE_PROTECTION_ADDR_1, XSK_EFUSEPS_APB_WRITE_PROTECTION_ADDR_2, XSK_EFUSEPS_ERROR_WRITE_WRITE_PROTECT_BIT, XSK_EFUSEPS_CONTROLER_LOCK.
Referenced by main.
u32 XilSKey_EfusePs_Read(XilSKey_EPs *InstancePtr)
This function is used to read the PS eFUSE.
InstancePtr - Pointer to the PsEfuseHandle which describes which PS eFUSE should be burned. XST_SUCCESS no errors occurred.In case of error, value is as defined in xilskey_utils.h. Error value is a combination of Upper 8 bit value and Lower 8 bit value. For example, 0x8A03 should be checked in error.h as 0x8A00 and 0x03. Upper 8 bit value signifies the major error and lower 8 bit values tells more precisely. When called: This API initializes the timer, XADC subsystems. Unlocks the PS eFUSE Controller. Configures the PS eFUSE Controller and enables read-only mode. Reads the PS eFUSE (Hash Value), and enables read-only mode. Locks the PS eFUSE Controller. Returns an error, if the reference clock frequency is not in between 20 and 60MHz. or if unable to unlock PS eFUSE controller or requested address corresponds to restricted bits. or if the temperature and voltage are not within range
References XSK_EFUSEPS_ERROR_PS_STRUCT_NULL, XilSKey_Timer_Intialise, XSK_EFUSEPS_ERROR_PS_PARAMETER_WRONG, XilSKey_EfusePs_XAdcInit, XSK_EFUSEPS_ERROR_XADC_INIT, XSK_EFUSEPS_CONTROLER_UNLOCK, XSK_EFUSEPS_CONTROLER_LOCK_STATUS, XSK_EFUSEPS_ERROR_CONTROLLER_LOCK, XilSKey_EfusePs_ControllerConfig, XSK_EFUSEPS_READ_MODE_NORMAL, XSK_EFUSEPS_ERROR_CONTROLLER_CONFIG, XilSKey_EfusePs_ControllerSetReadWriteEnable, XSK_EFUSEPS_ERROR_READ_RSA_HASH, XSK_EFUSEPS_CONTROLER_LOCK.
Referenced by main.
void XilSKey_EfusePs_GenerateMatrixMap(void)
This function is used to generate the matrix map of the G and H for hamming code (31,26).
G is [31,5] and defined as [A|I], I is identity matrix of [5,5].None TDD Cases: Check the generated matrix Check the memory corruption of the generated matrix
References ErrorCodeIndex, Matrix.
void XilSKey_EfusePs_EccEncode(const u8 *InData, u8 *Ecc)
This function is used to encode the incoming data byte.
It uses hamming (31,26) algorithm. 26 bits are encoded to 31 bits InData is 26 bit input data with each bit represented in one byte Ecc is the 31 bit encoded data with each bit represented in one byte None TDD Cases: Check the parameters Check the encoded data for different input data Check the input data for boundary cases Check for memory corruption
References Matrix.
u8 XilSKey_EfusePs_EccDecode(const u8 *Corrupt, u8 *Syndrome)
This function is used to decode the incoming encoded byte.
Corrupt is the input encoded data. It has 26 bit data with 5 bit parity data Syndrome is the output updated with the parity error information. position of the error in the data byte TDD Cases: Check the parameters Check the decode with out any error Check the decode with 1 bit error Check the decode with 2 bit error Check the decode for boundary cases Check for memory corruption
References ErrorCodeIndex, Matrix.
u32 XilSKey_EfusePs_ControllerConfig(u8 CtrlMode, u32 RefClk, u8 ReadMode)
This function is used to set the controller mode, read mode along with the read and program strobe width values based on the reference clock.
CtrlMode is the mode of the controller XSK_EFUSEPS_REDUNDANCY_MODEXSK_EFUSEPS_SINGLE_MODE RefClk is the CPU 1x reference clock frequency. Clock frequency can be between 20MHz to 100MHz specified in Hz ReadMode is the read mode of the controller XSK_EFUSEPS_READ_MODE_NORMALXSK_EFUSEPS_READ_MODE_MARGIN_1XSK_EFUSEPS_READ_MODE_MARGIN_2 XST_SUCCESS no errors occurred. an error when controller mode is not supportedan error when reference clock is not supportedan error when read mode is not supported Test Cases: Check single mode in CFG Reg Check redundancy mode in CFG Reg Check strobe width values for write mode Check strobe width values for various read mode Check Normal Read mode setting in CFG Reg Check Margin 1 Read mode setting in CFG Reg Check Margin 2 Read mode setting in CFG Reg Boundary Conditions
References XSK_EFUSEPS_CONFIG_REG, XSK_EFUSEPS_CONFIG_TSU_H_A, XSK_EFUSEPS_ERROR_CONTROLLER_MODE, XSK_EFUSEPS_ERROR_READ_MODE, XSK_EFUSEPS_ERROR_REF_CLOCK, XSK_EFUSEPS_PGM_STBW_REG, XSK_EFUSEPS_PRGM_STROBE_WIDTH, XSK_EFUSEPS_RD_STBW_REG, XSK_EFUSEPS_RD_STROBE_WIDTH, XSK_EFUSEPS_REFCLK_LOW_FREQ, XSK_EFUSEPS_SINGLE_MODE.
Referenced by XilSKey_EfusePs_Read, XilSKey_EfusePs_Write.
u8 XilSKey_EfusePs_IsAddressXilRestricted(u32 Addr)
This function is used to check whether eFuse bit is xilinx reserved bit or not.
Addr is the address of the eFuse bit. XST_SUCCESS if address corresponds to restricted eFuse bit. XST_FAILURE is address corresponds to non-restricted eFuse bit. Test Cases: with different address values Boundary values for addr
References XSK_EFUSEPS_APB_TRIM_BITS_START_ADDR, XSK_EFUSEPS_APB_TRIM_BITS_START_ADDR_2ND_HALF, XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x20, XSK_EFUSEPS_APB_XILINX_RSVD_TEST_BIT_x23F.
Referenced by XilSKey_EfusePs_ReadEfuseBit, XilSKey_EfusePs_WriteEfuseBit.
void XilSKey_EfusePs_ControllerSetReadWriteEnable(u32 ReadWriteEnable)
This function is used to enable the read/write/program the eFUSE array.
ReadWriteEnable 0x1 - Enable programming 0x2 - Enable read 0x4 - Enable write Test Cases
References XSK_EFUSEPS_CONTROL_PS_EN, XSK_EFUSEPS_CONTROL_RD_DIS, XSK_EFUSEPS_CONTROL_REG, XSK_EFUSEPS_CONTROL_WR_DIS, XSK_EFUSEPS_ENABLE_PROGRAMMING.
Referenced by XilSKey_EfusePs_Read, XilSKey_EfusePs_Write.
u32 XilSKey_EfusePs_ReadEfuseBit(u32 Addr, u8 *Data)
This function is used to read the eFuse bit value.
Before using this function set the controller mode and read mode as required. Also, strobe width values are to be set properly based on the reference clock for successful reading Addr is the address of the eFuse bit. Data has the read eFuse value stored in it. XST_SUCCESS for successfully reading the value. an error when addr is restricted Test Cases Read in Single mode Read in redundancy mode Read for restricted address Boundary Checks for address
References XilSKey_EfusePs_IsAddressXilRestricted, XSK_EFUSEPS_ERROR_ADDRESS_XIL_RESTRICTED.
u32 XilSKey_EfusePs_WriteEfuseBit(u32 Addr)
This function is used to program the eFuse bit value.
Before using this function set the controller mode and read mode as required. Also, strobe width values are to be set properly based on the reference clock for successful programming Addr is the address of the eFuse bit. XST_SUCCESS after successful writing. an error when addr is restricted Test Cases Write in Single mode Write in redundancy mode Write for restricted address Boundary Checks for address Strobe width are not proper (Check if it makes sense)
References XilSKey_Efuse_IsTimerExpired, XilSKey_Efuse_SetTimeOut, XilSKey_EfusePs_IsAddressXilRestricted, XSK_EFUSEPS_ERROR_ADDRESS_XIL_RESTRICTED.
u32 XilSKey_EfusePs_ReadStatus(XilSKey_EPs *InstancePtr, u32 *StatusBits)
This function is used to read the PS efuse status register.
InstancePtr Pointer to the PS eFUSE instance. StatusBits Buffer to store the status register read. XST_SUCCESS.XST_FAILURE This API unlocks the controller and reads the Zynq PS eFUSE status register.
References XSK_EFUSEPS_ERROR_PS_STRUCT_NULL, XSK_EFUSEPS_CONTROLER_UNLOCK, XSK_EFUSEPS_CONTROLER_LOCK_STATUS, XSK_EFUSEPS_ERROR_CONTROLLER_LOCK, XSK_EFUSEPS_STATUS_REG.
Referenced by main.