xilskey_jscmd.c
int setPin(int pin, int value)
< Prototype declarations for Xilskey jscmd APIs
Referenced by Bbram_Close_Ultra, Bbram_ProgramKey, Bbram_VerifyKey, Jtag_Read_Sysmon, jtagShiftTDI, JtagWrite, JtagWrite_Ultrascale, navigateTAP, open_port.
int readPin(int pin)
js_printf
Dummy PRINTF.
Referenced by JtagInitGpio, JtagServerInit, JtagServerInitBbram, jtagShiftTDIBits, navigateTAP.
DEFAULT_FREQUENCY
Default frequency.
MAX_FREQUENCY
Maximum frequency.
ZYNQ_DAP_ID
DAP Id.
KINTEX_ULTRA_MB_DAP_ID
Kintex Ultrascale microblaze TAP ID.
KINTEX_ULTRAPLUS_DAP_ID
Kintex Ultrascale plus microblaze TAP ID.
VIRTEX110_ULTRA_MB_DAP_ID
VIRTEX 110 Ultrascale microblaze TAP id.
VIRTEX108_ULTRA_MB_DAP_ID
VIRTEX 108 Ultrascale microblaze TAP id.
VIRTEX_ULTRAPLUS_DAP_ID
VIRTEX Ultrascale plus microblaze TAP id.
VIRTEX_ULTRAPLUS_VC13P_DAP_ID
XCVU13P VIRTEX Ultrascale Plus microblaze TAP id.
ZYNQ_ULTRAPLUS_PL_DAP_ID
Zynq Ultrascale plus TAP ID.
set_last_error
Set last error.
Referenced by open_port.
typedef struct js_port_impl_struct js_port_impl_t
typedef struct js_command_impl_struct js_command_impl_t
typedef struct ftd_async_transfer_struct ftd_async_transfer_t
XilSKey_JtagSlr XilSKeyJtag
JTAG Tap Instance.
Referenced by Bbram_Close_Ultra, Bbram_DeInit, Bbram_Init, Bbram_ProgramKey, Bbram_VerifyKey, calcInstr, Jtag_Read_Sysmon, JtagAES_Check_Ultrascale, JtagRead, JtagRead_Status_Ultrascale, JtagRead_Ultrascale, JtagServerInit, JtagServerInitBbram, JtagWrite, JtagWrite_Ultrascale.
js_port_t* g_port
js_server_t* g_js
js_port_descr_t* g_useport
u32 GpoOutValue
XSKEfusePl_Fpga PlFpgaFlag
For Storing Fpga series.
Referenced by JtagAES_Check_Ultrascale, JtagRead_Ultrascale, JtagWrite_Ultrascale.
XGpio structXGpio
u32 Bbram_ReadKey[8][8]
const id_codes_t IDcodeArray[][]
const unsigned int JTAGNavigateTable[256][256]
File generated by JTAG.EXE.
This are the tms values and the corresponding bit counts to navigate quickly from any state to any state.
Referenced by getNavigateTAPValue.
void dummy_printf(const char *ctrl1,...)
function prototype of dummy_printf
static int JtagValidateMioPins_Efuse_Ultra(void)
This function validates GPIO pin connections of Master JTAG and hardware module for eFUSE programming.
None. None.
static int JtagValidateMioPins_Bbram_Ultra(void)
This function validates GPIO pin connections of Master JTAG and hardware module for BBRAM programming.
None. Hardware module is not required over here.
static u32 JtagGetZuPlusPlIdcode(void)
This function attempt to get the ZU+ PL_IDCODE via JTAG.
ZU+ PL IDCODE if it exists None.
static int close_port(js_lib_port_t *port_arg)
This function performs close port operation.
ret value
void GpioConfig(unsigned long addr, unsigned long mask, unsigned long val)
This function performs Gpio Configuration.
Referenced by JtagInitGpio.
void JtagInitGpio(XilSKey_ModuleSelection Module)
This function performs Gpio Jtag initialization.
References GpioConfig, js_printf.
Referenced by JtagServerInit, JtagServerInitBbram.
int getByteCountFromBitCount(int bitCount)
This function calculates ByteCount From BitCount.
ByteCount
Referenced by jtag_shift, jtagShiftTDIBits.
u32 calcInstr(u8 Instr, u8 cmd)
This function calculates instructions.
u32-bit val value
References XilSKeyJtag.
Referenced by Bbram_Close_Ultra, Bbram_DeInit, Bbram_Init, Bbram_ProgramKey, Bbram_VerifyKey, Jtag_Read_Sysmon, JtagAES_Check_Ultrascale, JtagRead, JtagRead_Status_Ultrascale, JtagRead_Ultrascale, JtagWrite, JtagWrite_Ultrascale.
unsigned int getNavigateTAPValue(unsigned char startState, unsigned char endState)
This function calculates Navigate TAPValue.
int tableValue
References JTAGNavigateTable.
Referenced by navigateTAP.
void navigateTAP(unsigned char startState, unsigned char endState)
This function performs NavigateTAP.
References getNavigateTAPValue, js_printf, setPin.
void jtagShiftTDI(unsigned char tdiData, unsigned char *tdoData, int clkCount, int exitState)
This function performs Jtag shift TDI operation.
References setPin.
Referenced by jtagShiftTDIBits.
int jtagShiftTDIBits(unsigned char *tdiBuf, unsigned char *tdoBuf, int bitCount, js_state_t endState, unsigned int flags)
This function will be used to shift long bits.
1 if shift state is to be exited. If tdoBuf != NULL, data will be read from device.
References getByteCountFromBitCount, js_printf, jtagShiftTDI.
int jtag_setPreAndPostPads(js_port_t *port_arg, int irPrePadBits, int irPostPadBits, int drPrePadBits, int drPostPadBits)
This function sets Jtag Pre and Post Pads.
status value
Referenced by Bbram_DeInit, Bbram_Init, Bbram_ProgramKey, Bbram_VerifyKey, JtagRead, JtagWrite.
int jtag_navigate(js_port_t *port, js_state_t state)
This function performs Jtag navigate operation.
status value
References js_port_struct::root_node.
Referenced by Bbram_Close_Ultra, Bbram_DeInit, Bbram_Init, Bbram_ProgramKey, Bbram_VerifyKey, Jtag_Read_Sysmon, JtagAES_Check_Ultrascale, JtagRead, JtagRead_Status_Ultrascale, JtagRead_Ultrascale, JtagWrite, JtagWrite_Ultrascale, open_port.
int jtag_shift(js_port_t *port_arg, unsigned char mode, int bits, unsigned char *wrBuffer, unsigned char *rdBuffer, js_state_t state)
This function takes care of padding Must be set up with pre/post ir/dr info.
status value
References getByteCountFromBitCount, js_port_struct::root_node.
Referenced by Bbram_Close_Ultra, Bbram_DeInit, Bbram_Init, Bbram_ProgramKey, Bbram_VerifyKey, Jtag_Read_Sysmon, JtagAES_Check_Ultrascale, JtagRead, JtagRead_Status_Ultrascale, JtagRead_Ultrascale, JtagWrite, JtagWrite_Ultrascale.
static int get_property(js_lib_port_t *port_arg, js_property_kind_t kind, js_property_value_t *valuep)
This function performs get property operation.
-1 value
static int set_property(js_lib_port_t *port_arg, js_property_kind_t kind, js_property_value_t value)
This function performs set property operation.
-1 value
static int run_command_sequence(js_lib_command_sequence_t *cmds)
This function performs run command sequence operation.
0 value
static int get_port_descr_list(js_lib_server_t *server, js_port_descr_t **port_listp)
This function performs get port description list operation.
1 value
int open_port(js_lib_server_t *server, js_port_descr_t *port_descr, js_lib_port_t **result)
This function performs open port operation.
-1 value
References js_lib_server_struct::base, js_node_struct::idcode, js_node_struct::is_active, js_node_struct::is_tap, jtag_navigate, js_node_struct::name, js_node_struct::port, set_last_error, setPin.
Referenced by js_init_zynq.
static void deinit_server(js_lib_server_t *server)
This function performs deinit server operation.
js_server_t* js_init_zynq()
< Prototype declarations for Xilskey jscmd APIs
References open_port.
Referenced by JtagServerInit, JtagServerInitBbram.
void JtagWrite(unsigned char row, unsigned char bit)
JTAG Server Write routine.
References calcInstr, jtag_navigate, jtag_setPreAndPostPads, jtag_shift, setPin, XilSKey_Efuse_IsTimerExpired, XilSKey_Efuse_SetTimeOut, XilSKeyJtag.
void JtagRead(unsigned char row, unsigned int *row_data, unsigned char marginOption)
JTAG Server Read routine.
References calcInstr, jtag_navigate, jtag_setPreAndPostPads, jtag_shift, XilSKeyJtag.
int JtagValidateMioPins(XilSKey_ModuleSelection Module)
This function validates MIO pins.
0 value none
Referenced by JtagServerInit, JtagServerInitBbram.
int JtagServerInit(XilSKey_EPl *InstancePtr)
JTAG Server Initialization routine.
References XilSKey_EPl::FpgaFlag, XilSKey_EPl::GpioInputCh, XilSKey_EPl::GpioOutPutCh, XilSKey_EPl::HwmGpioEnd, XilSKey_EPl::HwmGpioReady, XilSKey_EPl::HwmGpioStart, js_init_zynq, js_printf, XilSKey_EPl::JtagGpioID, XilSKey_EPl::JtagGpioTCK, XilSKey_EPl::JtagGpioTDI, XilSKey_EPl::JtagGpioTDO, XilSKey_EPl::JtagGpioTMS, JtagInitGpio, XilSKey_EPl::JtagMioMuxSel, XilSKey_EPl::JtagMioTCK, XilSKey_EPl::JtagMioTDI, XilSKey_EPl::JtagMioTDO, XilSKey_EPl::JtagMioTMS, XilSKey_EPl::JtagMuxSelLineDefVal, JtagValidateMioPins, XilSKey_EPl::MasterSlr, XilSKey_EPl::NumSlr, XilSKeyJtag.
int JtagServerInitBbram(XilSKey_Bbram *InstancePtr)
This function initializes JTAG server for use in BBRAM algorithm.
JTAG Server Initialization routine for Bbram. InstancePtr - instance pointer - XST_FAILURE - In case of failure - XST_SUCCESS - In case of Success
References js_init_zynq, js_printf, JtagInitGpio, JtagValidateMioPins, XilSKeyJtag.
int Bbram_Init(void)
This function implements the BBRAM algorithm initialization.
BBRAM Algorithm - Initialization. - XST_FAILURE - In case of failure - XST_SUCCESS - In case of Success
References calcInstr, jtag_navigate, jtag_setPreAndPostPads, jtag_shift, XilSKey_Efuse_IsTimerExpired, XilSKey_Efuse_SetTimeOut, XilSKeyJtag.
int Bbram_ProgramKey(XilSKey_Bbram *InstancePtr)
This function implements the BBRAM program key.
BBRAM Algorithm - Program key. InstancePtr - instance pointer - XST_FAILURE - In case of failure - XST_SUCCESS - In case of Success
References calcInstr, jtag_navigate, jtag_setPreAndPostPads, jtag_shift, setPin, XilSKeyJtag.
int Bbram_VerifyKey(XilSKey_Bbram *InstancePtr)
This function implements the BBRAM verify key.
BBRAM Algorithm - Verify key.Program and verify key have to be done together; These API's cannot be used independently. InstancePtr - instance pointer - XST_FAILURE - In case of failure - XST_SUCCESS - In case of Success
References calcInstr, jtag_navigate, jtag_setPreAndPostPads, jtag_shift, setPin, XilSKeyJtag.
void Bbram_DeInit(void)
This function does de-initialization.
De-initialization.none
References calcInstr, jtag_navigate, jtag_setPreAndPostPads, jtag_shift, XilSKeyJtag.
void Jtag_Read_Sysmon(u8 Row, u32 *Row_Data)
This function reads temperature and voltage of Ultrascale.
Row specifies the row number to read. Row_Data is a pointer to a variable, to store the read value of given row. None. None.
References calcInstr, jtag_navigate, jtag_shift, setPin, XilSKeyJtag.
Referenced by XilSKey_EfusePs_XAdcReadTemperatureAndVoltage.
int JtagWrite_Ultrascale(u8 Row, u8 Bit, u8 Page, u8 Redundant)
This function blows the fuse of Ultrascale with provided parameters.
Row specifies the row number of EFUSE to blow. Bit Specifies the bit location in the given row. Page tell the page of EFUSE in which the given row is located. Redundant is a flag to specify the bit to be programmed is Normal bit or Redundant bit. Redundant - XSK_EFUSEPL_REDUNDANT_ULTRANormal - XSK_EFUSEPL_NORMAL_ULTRA None. None.
References calcInstr, jtag_navigate, jtag_shift, PlFpgaFlag, setPin, TimerTicksfor1000ns, XilSKey_Efuse_IsTimerExpired, XilSKey_Efuse_StartTimer, XilSKeyJtag.
void JtagRead_Ultrascale(u8 Row, u32 *RowData, u8 MarginOption, u8 Page, u8 Redundant)
This function reads entire row of Ultrascale's EFUSE.
Row specifies the row number of EFUSE. MarginOption is a variable which tells the margin option in which read operation to be performed. Page tell the page of EFUSE in which the given row is located. Redundant is a flag to specify the bit to be programmed is Normal bit or Redundant bit. Redundant - XSK_EFUSEPL_REDUNDANT_ULTRANormal - XSK_EFUSEPL_NORMAL_ULTRA This variable is not valid for Ultrascale plus as each row contains both redundant and normal bits upper 16 are redundant. None. Method to read FUSE register in Direct Macro Access way. Go to TLR to clear FUSE_CTS Load FUSE_CTS instruction on IR Step to CDR/SDR to shift in 32-bits FUSE_CTS command word Shift in MAGIC_CTS_WRITE "FEED28AC" for ultrascale Read 64 bit data in IR read state.
References calcInstr, jtag_navigate, jtag_shift, PlFpgaFlag, XilSKeyJtag.
void JtagRead_Status_Ultrascale(u32 *Rowdata)
This function reads the status row of Ultrascale's EFUSE and updates the pointer.
Rowdata is a pointer to a 32 bit variable which stores the status register value read from EFUSE status register. None. Method to read FUSE register in Direct Macro Access way. For reading the status values we need send the bitstream in shift DR state. Shift in MAGIC_CTS_WRITE "FEED28AC" for ultrascale Read 64 bit data in IR read state.
References calcInstr, jtag_navigate, jtag_shift, XilSKey_Efuse_ReverseHex, XilSKeyJtag.
u32 JtagAES_Check_Ultrascale(u32 *Crc, u8 MarginOption)
This function verifies the AES key of Ultrascale's EFUSE with provided CRC value.
Crc is a pointer to a 32 bit variable which holds the expected AES key's CRC. MarginOption is a variable which tells the margin option in which read operation to be performed. Returns XST_FAILURE/XST_SUCCESS XST_SUCCESS - If CRC is correctXST_FAILURE - If CRC is wrong To verify AES key with provided CRC 256 bits need to be written with all ZEROS and last 32 bits with CRC. And then CTS word should be framed and read 9 rows. The keys are stored in 8 rows (20 to 27) but in UltraScale the device will read all 1s. On the 9th read (row 28), the CRC computation takes place. An extra read after the 9th read is required to read the computed CRC out (can use last row addr of 28 or row 0). The FPGA internally compares the computed CRC with the expected CRC loaded through the FUSE_KEY operation. If they match, then the expected CRC is read. If not, the FPGA will return all 1s.
References calcInstr, jtag_navigate, jtag_shift, PlFpgaFlag, XilSKeyJtag.
void Bbram_Close_Ultra(void)
This function close UltraScale.
none none
References calcInstr, jtag_navigate, jtag_shift, setPin, XilSKeyJtag.
Referenced by main.