xilskey_eps_zynqmp_puf.c
XILSKEY_PUF_STATUS_SYN_WRD_RDY_TIMEOUT
Status of PUF word syndrome ready timeout.
XILSKEY_PUF_KEK_REGEN_RDY_TIMEOUT
Delay added to wait for key_rdy bit to be set during PUF regeneration.
Referenced by XilSKey_Puf_Regeneration.
XilsKey_PufRegistrationState
0x0 - PUF registration started
static u32 XilSkey_Puf_Validate_Access_Rules(u8 RequestType)
Validates the PUF access rules.
RequestType is an input to validate the access rules against Registration, Re-registration, Testmode1 & Testmode2 XST_SUCCESS if validation was successful. ERROR if validation failed None
static u32 XilSKey_ZynqMp_EfusePs_CheckZeros_Puf(void)
This function checks whether PUF is already programmed or not.
XST_SUCCESS if all rows are zeroErrorcode if already programmed. None.
static u32 XilSKey_ZynqMp_EfusePs_PufRowWrite(u8 Row, const u8 *Data, XskEfusePs_Type EfuseType)
This API programs the given data into specified row of eFUSE.
Row specifies the row number to be programmed. Data is pointer to 32 bit variable which holds data to be programmed. XST_SUCCESS if programs successfully.Errorcode on failure None.
static void XilSKey_Read_Puf_EfusePs_SecureBits_Regs(XilSKey_Puf_Secure *SecureBits)
This function is used to read the PS eFUSE PUF secure bits from cache or from eFUSE array based on user selection.
SecureBits is the pointer to the XilSKey_Puf_Secure which holds the read eFUSE secure bits of PUF. None.
static u32 XilSKey_WaitForPufStatus(u32 *PufStatus)
This function will poll for syndrome word is ready in the PUF_WORD register or till the timeout occurs.
PufStatus Pointer to pufstatus. XST_SUCCESS - In case of Success XST_FAILURE - In case of Timeout. None.
u32 XilSKey_ZynqMp_EfusePs_WritePufHelprData(const XilSKey_Puf *InstancePtr)
This function programs the PS eFUSEs with the PUF helper data.
InstancePtr Pointer to the XilSKey_Puf instance. XST_SUCCESS if programs successfully.Errorcode on failure To generate PufSyndromeData please use XilSKey_Puf_Registration API
References XilSKey_ZynqMp_EfusePs_Init, XilSKey_ZynqMp_EfusePs_Temp_Vol_Checks, XSK_EFUSEPS_ERROR_CONTROLLER_LOCK, XilSKey_ZynqMp_EfusePs_SetWriteConditions, XSK_ZYNQMP_EFUSEPS_PUF_ROW_UPPER_MASK, XilSKey_Efuse_ConvertBitsToBytes.
Referenced by main.
u32 XilSKey_ZynqMp_EfusePs_ReadPufHelprData(u32 *Address)
This function reads the PUF helper data from eFUSE.
Address Pointer to data array which holds the PUF helper data read from eFUSEs. XST_SUCCESS if reads successfully.Errorcode on failure. This function only reads from eFUSE non-volatile memory. There is no option to read from Cache.
References XSK_EFUSEPS_ERROR_CONTROLLER_LOCK, XilSKey_ZynqMp_EfusePs_SetTimerValues, XilSKey_ZynqMp_EfusePs_ReadRow, XSK_ZYNQMP_EFUSEPS_PUF_ROW_UPPER_MASK.
Referenced by main.
u32 XilSKey_ZynqMp_EfusePs_WritePufChash(const XilSKey_Puf *InstancePtr)
This function programs eFUSE with CHash value.
InstancePtr Pointer to the XilSKey_Puf instance. XST_SUCCESS if chash is programmed successfully.An Error code on failure To generate the CHash value, please use XilSKey_Puf_Registration function.
References XilSKey_ZynqMp_EfusePs_Init, XilSKey_ZynqMp_EfusePs_Temp_Vol_Checks, XSK_EFUSEPS_ERROR_CONTROLLER_LOCK, XilSKey_ZynqMp_EfusePs_SetWriteConditions, XilSKey_ZynqMp_EfusePs_ReadPufChash, XSK_EFUSEPS_ERROR_PUF_CHASH_ALREADY_PROGRAMMED, XilSKey_Efuse_ConvertBitsToBytes, XilSKey_ZynqMp_EfusePs_WriteAndVerifyBit.
Referenced by main.
u32 XilSKey_ZynqMp_EfusePs_ReadPufChash(u32 *Address, u8 ReadOption)
This function reads eFUSE PUF CHash data from the eFUSE array or cache based on the user read option.
Address Pointer which holds the read back value of the chash. ReadOption Indicates whether or not to read from the actual eFUSE array or from the eFUSE cache. 0(XSK_EFUSEPS_READ_FROM_CACHE) Reads from cache1(XSK_EFUSEPS_READ_FROM_EFUSE) Reads from eFUSE array XST_SUCCESS if programs successfully.Errorcode on failure Cache reload is required for obtaining updated values for reading from cache..
References XSK_EFUSEPS_RD_FROM_EFUSE_NOT_ALLOWED, XSK_ZYNQMP_EFUSEPS_BASEADDR, XSK_ZYNQMP_EFUSEPS_PUF_CHASH_OFFSET.
Referenced by XilSKey_ZynqMp_EfusePs_WritePufChash, XilSKey_Puf_Regeneration, main.
u32 XilSKey_ZynqMp_EfusePs_WritePufAux(const XilSKey_Puf *InstancePtr)
This function programs eFUSE PUF auxiliary data.
InstancePtr Pointer to the XilSKey_Puf instance. XST_SUCCESS if the eFUSE is programmed successfully.Errorcode on failure To generate auxiliary data, please use XilSKey_Puf_Registration function.
References XilSKey_ZynqMp_EfusePs_Init, XilSKey_ZynqMp_EfusePs_Temp_Vol_Checks, XSK_EFUSEPS_ERROR_CONTROLLER_LOCK, XilSKey_ZynqMp_EfusePs_SetWriteConditions, XilSKey_ZynqMp_EfusePs_ReadPufAux, XSK_EFUSEPS_ERROR_PUF_AUX_ALREADY_PROGRAMMED, XilSKey_Efuse_ConvertBitsToBytes, XilSKey_ZynqMp_EfusePs_WriteAndVerifyBit.
Referenced by main.
u32 XilSKey_ZynqMp_EfusePs_ReadPufAux(u32 *Address, u8 ReadOption)
This function reads eFUSE PUF auxiliary data from eFUSE array or cache based on user read option.
Address Pointer which holds the read back value of PUF's auxiliary data. ReadOption Indicates whether or not to read from the actual eFUSE array or from the eFUSE cache. 0(XSK_EFUSEPS_READ_FROM_CACHE) Reads from cache1(XSK_EFUSEPS_READ_FROM_EFUSE) Reads from eFUSE array XST_SUCCESS if PUF auxiliary data is read successfully.Errorcode on failure Cache reload is required for obtaining updated values for reading from cache.
References XSK_EFUSEPS_RD_FROM_EFUSE_NOT_ALLOWED, XSK_ZYNQMP_EFUSEPS_BASEADDR, XSK_ZYNQMP_EFUSEPS_PUF_MISC_OFFSET.
Referenced by XilSKey_ZynqMp_EfusePs_WritePufAux, main.
u32 XilSKey_Puf_Registration(XilSKey_Puf *InstancePtr)
This function performs registration of PUF which generates a new KEK and associated CHash, Auxiliary and PUF-syndrome data which are unique for each silicon.
InstancePtr Pointer to the XilSKey_Puf instance. XST_SUCCESS if registration/re-registration was successful.ERROR if registration was unsuccessful With the help of generated PUF syndrome data, it will be possible to re-generate same PUF KEK.
References XSK_ZYNQMP_CSU_BASEADDR, XSK_EFUSEPS_ERROR_PUF_INVALID_REG_MODE, XSK_EFUSEPS_PUF_REGISTRATION_STARTED, XSK_EFUSEPS_ERROR_PUF_TIMEOUT, XSK_EFUSEPS_ERROR_PUF_DATA_OVERFLOW, XSK_EFUSEPS_ERROR_PUF_DATA_UNDERFLOW, XSK_EFUSEPS_PUF_REGISTRATION_COMPLETE.
Referenced by main.
u32 XilSKey_Puf_Regeneration(const XilSKey_Puf *InstancePtr)
This function regenerates the PUF data so that the PUF's output can be used as the key source to the AES-GCM hardware cryptographic engine.
InstancePtr is a pointer to the XilSKey_Puf instance. XST_SUCCESS if regeneration was successful.ERROR if regeneration was unsuccessful
References XilSKey_ZynqMp_EfusePs_ReadPufChash, XSK_EFUSEPS_ERROR_PUF_INVALID_REQUEST, XSK_ZYNQMP_CSU_BASEADDR, XILSKEY_PUF_KEK_REGEN_RDY_TIMEOUT, XSK_EFUSEPS_ERROR_PUF_ACCESS.
u32 XilSKey_Write_Puf_EfusePs_SecureBits(const XilSKey_Puf_Secure *WriteSecureBits)
This function programs the eFUSE PUF secure bits.
WriteSecureBits Pointer to the XilSKey_Puf_Secure structure XST_SUCCESS if eFUSE PUF secure bits are programmed successfully.Errorcode on failure.
References XSK_EFUSEPS_ERROR_CONTROLLER_LOCK, XilSKey_ZynqMp_EfusePs_SetWriteConditions, XilSKey_ZynqMp_EfusePs_WriteAndVerifyBit, XSK_EFUSEPS_ERROR_WRITE_PUF_SYN_INVLD, XSK_EFUSEPS_ERROR_WRITE_PUF_SYN_WRLK, XSK_EFUSEPS_ERROR_WRITE_PUF_SYN_REG_DIS, XSK_EFUSEPS_ERROR_WRITE_PUF_RESERVED_BIT, XilSKey_ZynqMp_EfusePs_CacheLoad.
Referenced by main.
u32 XilSKey_Read_Puf_EfusePs_SecureBits(XilSKey_Puf_Secure *SecureBitsRead, u8 ReadOption)
This function is used to read the PS eFUSE PUF secure bits from cache or from eFUSE array.
SecureBitsRead - Pointer to the XilSKey_Puf_Secure structure which holds the read eFUSE secure bits from the PUF. ReadOption - Indicates whether or not to read from the actual eFUSE array or from the eFUSE cache. 0(XSK_EFUSEPS_READ_FROM_CACHE) Reads from cache1(XSK_EFUSEPS_READ_FROM_EFUSE) Reads from eFUSE array XST_SUCCESS if reads successfully.Errorcode on failure.
References XSK_EFUSEPS_RD_FROM_EFUSE_NOT_ALLOWED.
Referenced by main.