APP = rfclk_example_app
LIBSOURCES=*.c
OUTS = rfclk_example_app
RFCLK_OBJS = xrfclk_example_app.o
INCLUDES =
BOARD_FLAG =
OBJS =

%.o: %.c
	$(CC) ${LDFLAGS} ${BOARD_FLAG} $(INCLUDES) ${CFLAGS} -c $(LIBSOURCES)

all: $(RFCLK_OBJS)
	$(CC) ${LDFLAGS} $(INCLUDES) $(OBJS) $(RFCLK_OBJS) -o $(OUTS) -lrfclk

clean:
	rm -rf $(OUTS) *.o
