function_prototype.c
IIC_FMC_BASE
IIC_ADAPTER_BASE
FMC_ADDRESS
ADAPTER_ADDRESS
SENSOR_ADDRESS
IIC_MUX_ADDRESS
IIC_FMC_CHANNEL
IIC_MUX_ENABLE
PAGE_SIZE
DSI_BASE
VDMA_BASE
XCSIRXSS_BASE
XDSITXSS_BASE
DEMOSAIC_DEVICE_ID
GPIO_CHANNEL
GPIO_0_DEVICE_ID
GPIO_1_DEVICE_ID
GPIO_2_DEVICE_ID
GPIO_3_DEVICE_ID
GPIO_4_DEVICE_ID
NO_BYTES_PER_PIXEL
HORIZONTAL_RESOLUTION
HORIZONTAL_RESOLUTION_BYTES
VERTICAL_RESOLUTION
FRAME_COUNTER
MM2S_HALT_SUCCESS
MM2S_HALT_FAILURE
S2MM_HALT_SUCCESS
S2MM_HALT_FAILURE
DSI_BYTES_PER_PIXEL
DSI_H_RES
DSI_V_RES
DSI_DISPLAY_HORI_VAL
DSI_DISPLAY_VERT_VAL
DSI_HBACK_PORCH
DSI_HFRONT_PORCH
DSI_VSYNC_WIDTH
DSI_VBACK_PORCH
DSI_VFRONT_PORCH
SET
VDMA_MM2S
VDMA_S2MM
TPG0_W
TPG0_H
SCLR_OW
SCLR_OH
S2MM
MM2S
VDMA_BASEADDR
typedef struct vdma_handle vdma_handle
typedef u8 AddressType
XDsiTxSs DsiTxSs
XCsiSs CsiRxSs
XVprocSs scaler_new_inst
XVprocSs csc_new_inst
XAxiVdma AxiVdma
XV_tpg_Config* tpg1_Config
XV_tpg tpg1
XVtc vtc
XVtc_Config* vtc_Config
XVtc_Timing vtc_timing
XV_demosaic InstancePtr
XV_demosaic_Config* demosaic_Config
XGpio Gpio
vdma_handle vdma_context[XPAR_XAXIVDMA_NUM_INSTANCES][XPAR_XAXIVDMA_NUM_INSTANCES]
unsigned int context_init
XIic IicFmc
XIic IicAdapter
XIic* IicFmcInstPtr
XIic * IicAdapterInstPtr
u8 WriteBuffer[sizeof(AddressType)+PAGE_SIZE][sizeof(AddressType)+PAGE_SIZE]
u8 ReadBuffer[PAGE_SIZE][PAGE_SIZE]
volatile u8 TransmitComplete
volatile u8 ReceiveComplete
u8 FmcIicAddr
u8 AdapterIicAddr
u8 SensorIicAddr
volatile u32* Mm2sStatusReg
volatile u32* S2mmStatusReg
volatile u32* VdmaParkPtrReg
volatile u32* VdmaS2MMCrReg
volatile u32* VdmaS2MMStatusReg
volatile u32* VdmaS2MMVertSizeReg
volatile u32* VdmaS2MMHoriSizeReg
volatile u32* VdmaS2MMFrmDlrStrideReg
volatile u32* VdmaS2MMFrameBuffer0Reg
volatile u32* VdmaMM2SCrReg
volatile u32* VdmaMMS2StatusReg
volatile u32* VdmaMM2SVertSizeReg
volatile u32* VdmaMM2SHoriSizeReg
volatile u32* VdmaMM2SFrmDlrStrideReg
volatile u32* VdmaMM2SFrameBuffer0Reg
unsigned int srcBuffer
static int ReadSetup(vdma_handle *vdma_context)
This function sets up the read channel.
vdma_context is the context pointer to the VDMA engine. XST_SUCCESS if the setup is successful, XST_FAILURE otherwise. None.
static int WriteSetup(vdma_handle *vdma_context)
This function sets up the write channel.
dma_context is the context pointer to the VDMA engine.. XST_SUCCESS if the setup is successful, XST_FAILURE otherwise. None.
static int StartTransfer(XAxiVdma *InstancePtr)
This function starts the DMA transfers.
Since the DMA engine is operating in circular buffer mode, video frames will be transferred continuously. InstancePtr points to the DMA engine instance XST_SUCCESS if both read and write start successfullyXST_FAILURE if one or both directions cannot be started None.
int driverInit()
void videoIpConfig(XVidC_VideoMode videoMode)
u32 SetupDSI(void)
This function programs MIPI DSI SS with the required timing parameters.
None. None.
Referenced by main.
u32 InitializeCsiRxSs(void)
This function programs MIPI CSI SS with the required timing parameters.
None. None.
Referenced by main.
void EnableCSI(void)
This function enables MIPI CSI IP None. None.
Referenced by main.
void InitDSI(void)
This function programs MIPI DSI SS with the required timing parameters.
None. None.
Referenced by main.
void DisableCSI(void)
This function disables MIPI CSI IP None. None.
Referenced by resetIp.
void DisableDSI(void)
This function disables MIPI DSI SS. None. None.
Referenced by resetIp.
void resetIp(void)
This function resets IPs.
None. None.
References DisableCSI, DisableDSI, resetVIP.
Referenced by main.
int demosaic()
This function programs colour space converter with the given width and height.
width is Hsize of a packet in pixels. height is number of lines of a packet. None. None.
Referenced by main.
void resetVIP(void)
* This function resets and releases IPs * * None. * * None. *
Referenced by resetIp.
int vtpg_hdmi()
int InitIIC()
This function writes, reads, and verifies the data to the IIC EEPROM.
It does the write as a single page write, performs a buffered read. None. XST_SUCCESS if successful else XST_FAILURE. None.
Referenced by main.
void SetupIICIntrHandlers()
void SendHandler(XIic *InstancePtr)
This Send handler is called asynchronously from an interrupt context and indicates that data in the specified buffer has been sent.
InstancePtr is not used, but contains a pointer to the IIC device driver instance which the handler is being called for. None. None.
Referenced by SetupIICIntrHandlers.
void ReceiveHandler(XIic *InstancePtr)
This Receive handler is called asynchronously from an interrupt context and indicates that data in the specified buffer has been Received.
InstancePtr is not used, but contains a pointer to the IIC device driver instance which the handler is being called for. None. None.
Referenced by SetupIICIntrHandlers.
void StatusHandler(XIic *InstancePtr, int Event)
This Status handler is called asynchronously from an interrupt context and indicates the events that have occurred.
InstancePtr is a pointer to the IIC driver instance for which the handler is being called for. Event indicates the condition that has occurred. None. None.
Referenced by SetupIICIntrHandlers.
int SetFmcIICAddress()
int SetAdapterIICAddress()
int AdapterWriteData(u16 ByteCount)
This function writes a buffer of data to the Adapter IIC.
ByteCount contains the number of bytes in the buffer to be written. XST_SUCCESS if successful else XST_FAILURE. The Byte count should not exceed the page size of the EEPROM as noted by the constant PAGE_SIZE.
void Sensor_Delay()
int WritetoReg(u8 buf1, u8 buf2, u8 buf3)
int SensorPreConfig(int pcam5c_mode)
void GPIOSelect(int dsi)
void CamReset(void)
void InitVprocSs_Scaler(int count)
int RunVDMA(XAxiVdma *InstancePtr, int DeviceId, int hsize, int vsize, int buf_base_addr, int number_frame_count, int enable_frm_cnt_intr)
RunVDMA API.
This API is the interface between application and other API. When application will call this API with right argument, This API will call rest of the API to configure the read and write path of VDMA,based on ID. After that it will start both the read and write path of VDMA InstancePtr is the handle to XAxiVdma data structure. DeviceId is the device ID of current VDMA hsize is the horizontal size of the frame. It will be in Pixels. The actual size of frame will be calculated by multiplying this with tdata width. vsize is the Vertical size of the frame. buf_base_addr is the buffer address where frames will be written and read by VDMA. number_frame_count specifies after how many frames the interrupt should come. enable_frm_cnt_intr is for enabling frame count interrupt when set to 1. XST_SUCCESS if example finishes successfullyXST_FAILURE if example fails.
s32 WaitForCompletion(s32 VdmaChannel, u32 *VdmaBaseAddr)
This function wait until the DMA channel halts.
VdmaChannel specifies VdmaChannel is MM2S or S2MM . VdmaBaseAddr VDMA base address MM2S_HALT_SUCCESS, S2MM_HALT_SUCCESS in success MM2S_HALT_FAILURE, S2MM_HALT_FAILURE on failure None.
void ResetVDMA()
This function ResetVDMA.
None None None.
void HaltVDMA()
void InitVprocSs_CSC(int count)
int vdma_dsi()
int vdma_hdmi()