function_prototype.h
int InitIIC()
This function writes, reads, and verifies the data to the IIC EEPROM.
It does the write as a single page write, performs a buffered read. None. XST_SUCCESS if successful else XST_FAILURE. None. This function writes, reads, and verifies the data to the IIC EEPROM.XST_SUCCESS if successful else XST_FAILURE. None.
int AdapterWriteData(u16 ByteCount)
This function writes a buffer of data to the Adapter IIC.
ByteCount contains the number of bytes in the buffer to be written. XST_SUCCESS if successful else XST_FAILURE. The Byte count should not exceed the page size of the EEPROM as noted by the constant PAGE_SIZE.
void SetupIICIntrHandlers()
This function sets send, receive and error handlers for IIC interrupts.
None. None.
int SetupFmcInterruptSystem(XIic *IicFmcInstPtr)
int SetupAdapterInterruptSystem(XIic *IicAdapterInstPtr)
void SendHandler(XIic *InstancePtr)
This Send handler is called asynchronously from an interrupt context and indicates that data in the specified buffer has been sent.
InstancePtr is not used, but contains a pointer to the IIC device driver instance which the handler is being called for. None. None.
Referenced by SetupIICIntrHandlers.
void ReceiveHandler(XIic *InstancePtr)
This Receive handler is called asynchronously from an interrupt context and indicates that data in the specified buffer has been Received.
InstancePtr is not used, but contains a pointer to the IIC device driver instance which the handler is being called for. None. None.
Referenced by SetupIICIntrHandlers.
void StatusHandler(XIic *InstancePtr, int Event)
This Status handler is called asynchronously from an interrupt context and indicates the events that have occurred.
InstancePtr is a pointer to the IIC driver instance for which the handler is being called for. Event indicates the condition that has occurred. None. None.
Referenced by SetupIICIntrHandlers.
int SetFmcIICAddress()
int SetAdapterIICAddress()
void Sensor_Delay()
void resetIp()
This function resets IPs.
None. None.
References DisableCSI, DisableDSI, resetVIP.
Referenced by main.
void resetVIP()
* This function resets and releases IPs * * None. * * None. *
Referenced by resetIp.
void HaltVDMA()
int RunVDMA()
int SensorPreConfig(int pcam5c_mode)
void GPIOSelect(int)
int vdma_dsi()
int vdma_hdmi()
int vtpg_hdmi()
int getchar()
void DisableDSI()
This function disables MIPI DSI SS.
This function disables MIPI DSI SS. None. None. None. None.
void DisableCSI()
This function disables MIPI CSI IP.
This function disables MIPI CSI IP None. None. None. None.
void EnableCSI()
This function enables MIPI CSI IP.
This function enables MIPI CSI IP None. None. None. None.
void InitDSI()
This function programs MIPI DSI SS with the required timing parameters.
None. None.
u32 SetupDSI(void)
This function programs MIPI DSI SS with the required timing parameters.
None. None. This function programs MIPI DSI SS with the required timing parameters.None. None.
u32 InitializeCsiRxSs(void)
This function programs MIPI CSI SS with the required timing parameters.
None. None. This function programs MIPI CSI SS with the required timing parameters.XST_SUCCESS if successful or else XST_FAILURE. None.
int WritetoReg(u8 buf1, u8 buf2, u8 buf3)
int demosaic()
This function programs colour space converter with the given width and height.
width is Hsize of a packet in pixels. height is number of lines of a packet. None. None.
Referenced by main.
void CamReset(void)
This function resets IMX274 camera sensor.
None. None. This function resets IMX274 camera sensor.None. None.
void InitVprocSs_Scaler(int count)
This function initializes and configures VProcSS IP for scalar mode with the given input and output width and height values.
count is a flag value to initialize IP only once. None. None.