pipeline_program.c
IIC_SENSOR_BASE
VPROCSSCSC_BASE
DEMOSAIC_BASE
VGAMMALUT_BASE
XCSIRXSS_BASE
XGPIO_STREAM_MUX_GPIO_BASE
PAGE_SIZE
EEPROM_TEST_START_ADDRESS
FRAME_BASE
CSIFrame
ScalerFrame
XVPROCSS_BASE
XDSITXSS_BASE
DSI_BYTES_PER_PIXEL
DSI_H_RES
DSI_V_RES
HDMI_H_RES
HDMI_V_RES
DSI_DISPLAY_HORI_VAL
DSI_DISPLAY_VERT_VAL
DSI_HBACK_PORCH
DSI_HFRONT_PORCH
DSI_VSYNC_WIDTH
DSI_VBACK_PORCH
DSI_VFRONT_PORCH
ACTIVE_LANES_1
ACTIVE_LANES_2
ACTIVE_LANES_3
ACTIVE_LANES_4
SENSOR_ADDR
IIC_MUX_ADDRESS
IIC_EEPROM_CHANNEL
DDR_BASEADDR
BUFFER_BASEADDR0
BUFFER_BASEADDR1
BUFFER_BASEADDR2
BUFFER_BASEADDR3
BUFFER_BASEADDR4
CHROMA_ADDR_OFFSET
typedef u8 AddressType
XDsiTxSs DsiTxSs
XGpio Gpio_Stream_Mux
XCsiSs CsiRxSs
XVprocSs scaler_new_inst
XVidC_VideoMode VideoMode
XVidC_VideoStream VidStream
XVidC_ColorFormat Cfmt
XVidC_VideoStream StreamOut
XV_FrmbufWr_l2 frmbufwr
XV_FrmbufRd_l2 frmbufrd
u8 SensorIicAddr
XIic IicSensor
volatile u8 TransmitComplete
volatile u8 ReceiveComplete
u8 WriteBuffer[sizeof(AddressType)+PAGE_SIZE][sizeof(AddressType)+PAGE_SIZE]
u8 ReadBuffer[PAGE_SIZE][PAGE_SIZE]
XPipeline_Cfg Pipeline_Cfg
u8 TxRestartColorbar
u32 frame_array[5][5]
u32 rd_ptr
u32 wr_ptr
u64 XVFRMBUFRD_BUFFER_BASEADDR
u64 XVFRMBUFWR_BUFFER_BASEADDR
u32 frmrd_start
u32 frm_cnt
u32 frm_cnt1
void ConfigDemosaicResolution(XVidC_VideoMode videomode)
void DisableDemosaicResolution()
static void SendHandler(XIic *InstancePtr)
This Send handler is called asynchronously from an interrupt context and indicates that data in the specified buffer has been sent.
InstancePtr is not used, but contains a pointer to the IIC device driver instance which the handler is being called for. None. None.
static int ConfigFrmbuf(u32 StrideInBytes, XVidC_ColorFormat Cfmt, XVidC_VideoStream *StreamPtr)
This function configures Frame Buffer for defined mode.
XST_SUCCESS if init is OK else XST_FAILURE
static void ReceiveHandler(XIic *InstancePtr)
This Receive handler is called asynchronously from an interrupt context and indicates that data in the specified buffer has been Received.
InstancePtr is not used, but contains a pointer to the IIC device driver instance which the handler is being called for. None. None.
static void StatusHandler(XIic *InstancePtr, int Event)
This Status handler is called asynchronously from an interrupt context and indicates the events that have occurred.
InstancePtr is a pointer to the IIC driver instance for which the handler is being called for. Event indicates the condition that has occurred. None. None.
int SensorWriteData(u16 ByteCount)
This function writes a buffer of data to the IIC serial sensor.
ByteCount is the number of bytes in the buffer to be written. XST_SUCCESS if successful else XST_FAILURE. None.
Referenced by SensorReadData, SetupCameraSensor, StartSensor.
int SensorReadData(u8 *BufferPtr, u16 ByteCount)
This function reads data from the IIC serial Camera Sensor into a specified buffer.
BufferPtr contains the address of the data buffer to be filled. ByteCount contains the number of bytes in the buffer to be read. XST_SUCCESS if successful else XST_FAILURE. None.
References SensorWriteData.
Referenced by SetupCameraSensor.
int SetupCameraSensor(void)
This function setup Camera sensor programming wrt resolution selected.
XST_SUCCESS if successful else XST_FAILURE. None.
Referenced by main.
int InitIIC(void)
This function initializes IIC controller and gets config parameters.
This function writes, reads, and verifies the data to the IIC EEPROM.XST_SUCCESS if successful else XST_FAILURE. None.
void SetupIICIntrHandlers(void)
This function sets send, receive and error handlers for IIC interrupts.
None. None.
References ReceiveHandler, SendHandler, StatusHandler.
void ConfigCSC(u32 width, u32 height)
This function programs colour space converter with the given width and height.
width is Hsize of a packet in pixels. height is number of lines of a packet. None. None.
Referenced by InitImageProcessingPipe.
void ConfigGammaLut(u32 width, u32 height)
This function programs colour space converter with the given width and height.
width is Hsize of a packet in pixels. height is number of lines of a packet. None. None.
Referenced by InitImageProcessingPipe.
void ConfigDemosaic(u32 width, u32 height)
This function programs colour space converter with the given width and height.
width is Hsize of a packet in pixels. height is number of lines of a packet. None. None.
Referenced by InitImageProcessingPipe.
void FrmbufwrDoneCallback(void *CallbackRef)
This function is called when a Frame Buffer Write Done has occurred.
CallbackRef is a callback function reference. None. None.
Referenced by config_csi_cap_path.
void FrmbufrdDoneCallback(void *CallbackRef)
This function is called when a Frame Buffer Read Done has occurred.
CallbackRef is a callback function reference. None. None.
Referenced by config_csi_cap_path.
void DisableImageProcessingPipe(void)
This function disables Demosaic, GammaLut and VProcSS IPs.
None. None.
static u32 CalcStride(XVidC_ColorFormat Cfmt, u16 AXIMMDataWidth, XVidC_VideoStream *StreamPtr)
This function calculates the stride.
stride in bytes
int start_csi_cap_pipe(XVidC_VideoMode VideoMode)
int config_csi_cap_path()
Main function to initialize the video pipeline and process user input.
XST_SUCCESS if MIPI example was successful else XST_FAILURE None.
Referenced by main.
void InitImageProcessingPipe(void)
This function Initializes Image Processing blocks wrt to selected resolution.
None. None.
References ConfigCSC, ConfigDemosaic, ConfigGammaLut.
Referenced by main.
void EnableCSI(void)
This function enables MIPI CSI IP.
None. None.
References XCsiSs_Activate, XCsiSs_Configure, XCsiSs_Reset.
void DisableCSI(void)
This function disables MIPI CSI IP.
None. None.
References XCsiSs_Reset.
int StartSensor(void)
This function starts camera sensor to transmit captured video.
XST_SUCCESS if successful else XST_FAILURE. None.
Referenced by main.
void InitVprocSs_Scaler(int count)
This function initializes and configures VProcSS IP for scalar mode with the given input and output width and height values.
count is a flag value to initialize IP only once. None. None.
void ResetVprocSs_Scaler(void)
This function resets VProcSS_scalar IP.
None. None.
void EnableDSI(void)
This function enables MIPI DSI SS.
None. None.
Referenced by main.
void DisableDSI(void)
This function disables MIPI DSI SS.
None. None.
void InitDSI(void)
This function programs MIPI DSI SS with the required timing parameters.
None. None.
u32 SetupDSI(void)
This function initializes MIPI DSI SS and gets config parameters.
This function programs MIPI DSI SS with the required timing parameters.None. None.
void SelectDSIOutput(void)
This function programs GPIO to 1 to select MIPI DSI SS Stream Path in AXI- Stream switch.
None. None.
Referenced by main.
void SelectHDMIOutput(void)
This function programs GPIO to '0' to select HDMI Stream path in AXI-Stream switch.
None. None.
Referenced by main.
void DisableScaler(void)
This function stops VProc_SS scalar IP.
None. None.
u32 InitStreamMuxGpio(void)
This function initializes GPIO IP for Stream Switch selection and gets config parameters.
XST_SUCCESS if successful or else XST_FAILURE. None.
Referenced by main.
u32 InitializeCsiRxSs(void)
This function initializes MIPI CSI2 RX SS and gets config parameters.
This function programs MIPI CSI SS with the required timing parameters.XST_SUCCESS if successful or else XST_FAILURE. None.
References XCsiSs_Config::BaseAddr, XCsiSs_CfgInitialize, XCsiSs_LookupConfig.
XVidC_ColorDepth GetColorDepth(u32 CsiDataFormat)
This function returns selected colour depth of MIPI CSI2 RX SS.
CsiDataFormat is video data format ColorDepth returns colour depth value. None.
Referenced by SetColorDepth.
void SetColorDepth(void)
This function sets colour depth value getting from MIPI CSI2 RX SS.
None. None.
Referenced by main.
void PrintPipeConfig(void)
This function prints the video pipeline information.
None. None.
Referenced by main.