pipeline_program.h
u32 SetupDSI(void)
This function programs MIPI DSI SS with the required timing parameters.
None. None. This function programs MIPI DSI SS with the required timing parameters.None. None.
Referenced by main.
u32 InitStreamMuxGpio(void)
This function initializes GPIO IP for Stream Switch selection and gets config parameters.
XST_SUCCESS if successful or else XST_FAILURE. None.
u32 InitializeCFA(void)
u32 InitializeCsiRxSs(void)
This function programs MIPI CSI SS with the required timing parameters.
None. None. This function programs MIPI CSI SS with the required timing parameters.XST_SUCCESS if successful or else XST_FAILURE. None.
References XCsiSs_Config::BaseAddr, XCsiSs_CfgInitialize, XCsiSs_LookupConfig.
Referenced by main.
u32 InitializeVdma(void)
void SetColorDepth(void)
This function sets colour depth value getting from MIPI CSI2 RX SS.
None. None.
References XCsiSs::Config, GetColorDepth, XCsiSs_Config::PixelFormat.
Referenced by main.
void SelectDSIOuptut(void)
void SelectHDMIOutput(void)
This function programs GPIO to '0' to select HDMI Stream path in AXI-Stream switch.
None. None. This function programs GPIO to '0' to select HDMI Stream path in AXI-Stream switch.None. None.
int InitIIC(void)
This function writes, reads, and verifies the data to the IIC EEPROM.
It does the write as a single page write, performs a buffered read. None. XST_SUCCESS if successful else XST_FAILURE. None. This function writes, reads, and verifies the data to the IIC EEPROM.XST_SUCCESS if successful else XST_FAILURE. None.
Referenced by main.
void SetupIICIntrHandlers(void)
This function sets send, receive and error handlers for IIC interrupts.
None. None.
References ReceiveHandler, SendHandler, StatusHandler.
int MuxInit(void)
int SetupIOExpander(void)
int SetupCameraSensor(void)
This function setup Camera sensor programming wrt resolution selected.
XST_SUCCESS if successful else XST_FAILURE. None.
References SensorReadData, SensorWriteData.
void InitDemosaicGammaCSC(void)
int StartSensor(void)
This function starts camera sensor to transmit captured video.
XST_SUCCESS if successful else XST_FAILURE. None.
References SensorWriteData.
int StopSensor(void)
void InitCSI2RxSS2CFA_Vdma(void)
void InitCSC2TPG_Vdma(void)
int ToggleSensorPattern(void)
void PrintPipeConfig(void)
This function prints the video pipeline information.
None. None.
Referenced by main.
void DisableCSI(void)
This function disables MIPI CSI IP.
This function disables MIPI CSI IP None. None. None. None.
References XCsiSs_Reset.
void DisableCFAVdma(void)
void DisableCFA(void)
void DisableTPGVdma(void)
void DisableScaler(void)
This function stops VProc_SS scalar IP.
None. None.
void DisableDSI(void)
This function disables MIPI DSI SS.
This function disables MIPI DSI SS. None. None. None. None.
Referenced by resetIp.
void InitDSI(void)
This function programs MIPI DSI SS with the required timing parameters.
None. None.
Referenced by main.
void InitVprocSs_Scaler(int count)
This function initializes and configures VProcSS IP for scalar mode with the given input and output width and height values.
count is a flag value to initialize IP only once. None. None.
void EnableCSI(void)
This function enables MIPI CSI IP.
This function enables MIPI CSI IP None. None. None. None.
References XCsiSs_Activate.