xcsiss.c
XCsiSs_SubCores CsiSsSubCores[XPAR_XMIPICSISS_NUM_INSTANCES][XPAR_XMIPICSISS_NUM_INSTANCES]
Driver instance array of all sub-cores included in the design.
This array holds the driver instances for all MIPI CSI Rx Subsystem instances in the system.
static void CsiSs_GetIncludedSubCores(XCsiSs *CsiSsPtr)
This function queries the subsystem instance configuration to determine the included sub-cores.
For each sub-core that is present in the design the sub-core driver instance is binded with the subsystem sub-core driver handle. CsiSsPtr is a pointer to the Subsystem instance to be worked. None. None.
static u32 CsiSs_SubCoreInitCsi(XCsiSs *CsiSsPtr)
This function initializes the included sub-core to it's static configuration.
CsiSsPtr is a pointer to the Subsystem instance to be worked. XST_SUCCESS If CSI sub core is initialised successfully.XST_FAILURE If CSI sub core initialization fails. None.
u32 XCsiSs_CfgInitialize(XCsiSs *InstancePtr, XCsiSs_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the MIPI CSI subsystem and included sub-cores.
Initialize the MIPI CSI Rx Subsystem driver.This function must be called prior to using the subsystem. Initialization includes setting up the instance data for top level as well as all included sub-core therein, and ensuring the hardware is in a known stable state. InstancePtr is a pointer to the Subsystem instance to be worked on. CfgPtr points to the configuration structure associated with the subsystem instance. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if initialization is successful.XST_FAILURE otherwise. None. This function initializes the MIPI CSI Rx Subsystem driver. This function must be called prior to using the driver. Initialization includes setting up the instance data and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the XCsiSs instance. CfgPtr is a reference to a structure containing information about a specific XCsiSs instance. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if initialization was successful.XST_FAILURE if initialization failed. None.
References XCsiSs_Config::BaseAddr, XCsiSs::Config, XCsiSs::CsiPtr, XCsiSs_Config::IsDphyRegIntfcPresent, XCsiSs::IsReady.
Referenced by CsiSs_IntrExample, CsiSs_SelfTestExample, InitializeCsiRxSs.
u32 XCsiSs_Configure(XCsiSs *InstancePtr, u8 ActiveLanes, u32 IntrMask)
This function is used to configure the CSI lanes and interrupts that are to be handled by the application.
Configure the MIPI CSI Rx Subsystem.Refer to XCsi.h for interrupt masks. InstancePtr is a pointer to the Subsystem instance to be worked on. ActiveLanes is no of active lanes to be configure. This value ranges between 1 and 4. In case Dynamic Active Lane config is enabled, this value can't exceed maximum lanes present. When Dynamic Active Lane config is disabled, it should be equal to maximum lanes. IntrMask Indicates Mask for enable interrupts. XST_SUCCESS on successful configuration of parameters.XST_FAILURE otherwise. When EnableActiveLanes is 0, then the ActiveLanes parameter passed should be equal to Max Lanes of design. This function configures the MIPI CSI Rx Subsystem with the specified active lanes and interrupt mask. InstancePtr is a pointer to the XCsiSs instance. ActiveLanes is the number of active lanes to be used. IntrMask is the interrupt mask to enable specific interrupts. XST_SUCCESS if configuration was successful.XST_FAILURE if configuration failed. None.
References XCsiSs::CsiPtr.
Referenced by CsiSs_IntrExample, EnableCSI.
u32 XCsiSs_Activate(XCsiSs *InstancePtr, u8 Flag)
This function is used to activate the CSI Subsystem.
Activate or deactivate the MIPI CSI Rx Subsystem.Internally it activates the DPHY and CSI. InstancePtr is a pointer to the Subsystem instance to be worked on. Flag is used to denote whether to enable or disable the subsystem. XST_SUCCESS on successful operation.XST_FAILURE on failed operation. None. This function activates or deactivates the MIPI CSI Rx Subsystem based on the Flag parameter. InstancePtr is a pointer to the XCsiSs instance. Flag is the enable/disable flag. TRUE to enable, FALSE to disable. XST_SUCCESS if operation was successful.XST_FAILURE if operation failed. None.
References XCsiSs::Config, XCsiSs::CsiPtr, XCsiSs_Config::IsDphyRegIntfcPresent.
Referenced by CsiSs_IntrExample, EnableCSI.
u32 XCsiSs_Reset(XCsiSs *InstancePtr)
This function is used to reset the CSI Subsystem.
Reset the MIPI CSI Rx Subsystem.Internally it resets the DPHY and CSI only as the IIC instance is separately handled by the application. InstancePtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS if all the sub core IP resets occur correctly.XST_FAILURE if reset fails for any sub core IP. None. This function resets the MIPI CSI Rx Subsystem. InstancePtr is a pointer to the XCsiSs instance. XST_SUCCESS if reset was successful.XST_FAILURE if reset failed. None.
References XCsiSs::CsiPtr.
Referenced by CsiSs_IntrExample, DisableCSI, EnableCSI.
void XCsiSs_ReportCoreInfo(XCsiSs *InstancePtr)
This function reports list of cores included.
Report the core information. InstancePtr is a pointer to the Subsystem instance to be worked on. None. None. This function reports the core information of the MIPI CSI Rx Subsystem. InstancePtr is a pointer to the XCsiSs instance. None. None.
References XCsiSs::Config, XCsiSs::CsiPtr, XCsiSs_Config::IsDphyRegIntfcPresent.
Referenced by CsiSs_IntrExample.
void XCsiSs_SetVCSelection(XCsiSs *InstancePtr, u16 Value)
This function will control the virtual channels selection dynamically.
Set the virtual channel selection. InstancePtr is a pointer to the Subsystem instance to be worked on. Value will set the virtual channels corresponding to each bit value. None. In order to use dynamic VC selection, 'Allowed VC to all' must be selected in IP Configuration. This function sets the virtual channel selection. InstancePtr is a pointer to the XCsiSs instance. Value is the virtual channel selection value to be set. None. None.
References XCsiSs::Config, XCsiSs::CsiPtr, XCsiSs_Config::EnableVCx, XCsiSs_Config::VcNo.
u32 XCsiSs_GetVCSelection(XCsiSs *InstancePtr)
This function will return the virtual channels selected.
Get the virtual channel selection. InstancePtr is a pointer to the Subsystem instance to be worked on. Value of selected VCs. In order to use dynamic VC selection, 'Allowed VC to all' must be selected in IP Configuration. This function returns the current virtual channel selection. InstancePtr is a pointer to the XCsiSs instance. Virtual channel selection value. None.
References XCsiSs::Config, XCsiSs::CsiPtr, XCsiSs_Config::EnableVCx, XCsiSs_Config::VcNo.
void XCsiSs_GetShortPacket(XCsiSs *InstancePtr)
This function gets the short packets.
Get short packet information. InstancePtr is a pointer to the Subsystem instance to be worked on. None. None. This function retrieves the short packet information from the MIPI CSI Rx Subsystem. InstancePtr is a pointer to the XCsiSs instance. None. None.
References XCsiSs::CsiPtr, XCsiSs::SpktData.
Referenced by CsiSs_SPktEventHandler.
void XCsiSs_GetLaneInfo(XCsiSs *InstancePtr)
This function gets the clk and data lane info.
Get lane information. InstancePtr is a pointer to the Subsystem instance to be worked on. None. None. This function retrieves the lane information from the MIPI CSI Rx Subsystem. InstancePtr is a pointer to the XCsiSs instance. None. None.
References XCsiSs::ClkInfo, XCsiSs::Config, XCsiSs::CsiPtr, XCsiSs::DLInfo, XCsiSs_Config::LanesPresent.
void XCsiSs_GetVCInfo(XCsiSs *InstancePtr)
This function gets the virtual channel information.
Get virtual channel information. InstancePtr is a pointer to the Subsystem instance to be worked on. None. None. This function retrieves the virtual channel information from the MIPI CSI Rx Subsystem. InstancePtr is a pointer to the XCsiSs instance. None. None.
References XCsiSs::Config, XCsiSs::CsiPtr, XCsiSs_Config::EnableVCx, XCsiSs::VCInfo.