xcsiss_intr_example.c
XCSISS_BASE
MAX_INTERRUPT_COUNT
XCsiSs CsiSsInst
XINTC IntcInst
volatile u32 interrupt_counts
u32 CsiSs_IntrExample(u32 DeviceId)
This function is the main entry point for the interrupt example using the XCsiSs driver.
This function will set up the system with interrupts handlers. DeviceId is the unique device ID of the MIPI CSI Rx Subsystem core. XST_FAILURE if the system setup failed.XST_SUCCESS should never return since this function, if setup was successful, is blocking. If system setup was successful, this function is blocking in order to illustrate interrupt handling.
References XCsiSs_Config::BaseAddr, XCsiSs::Config, CsiSs_CciInit, CsiSs_DphyEventHandler, CsiSs_ErrEventHandler, CsiSs_FrameRcvdEventHandler, CsiSs_PktLvlEventHandler, CsiSs_PlatformInit, CsiSs_ProtLvlEventHandler, CsiSs_SPktEventHandler, Delay, XCsiSs_Config::IntrId, XCsiSs_Config::IntrParent, XCsiSs_Activate, XCsiSs_CfgInitialize, XCsiSs_Configure, XCSISS_HANDLER_DPHY, XCSISS_HANDLER_FRAMERECVD, XCSISS_HANDLER_OTHERERROR, XCSISS_HANDLER_PKTLVL, XCSISS_HANDLER_PROTLVL, XCSISS_HANDLER_SHORTPACKET, XCsiSs_IntrHandler, XCSISS_ISR_ALLINTR_MASK, XCsiSs_LookupConfig, XCsiSs_ReportCoreInfo, XCsiSs_Reset, XCsiSs_SetCallBack.
Referenced by main.
u32 CsiSs_PlatformInit(void)
This function initialize required platform-specifc peripherals.
None. XST_SUCCESS if required peripherals are initialized and configured successfully.XST_FAILURE, otherwise. None.
Referenced by CsiSs_IntrExample.
u32 CsiSs_CciInit(void)
This function initialize required IIC instance to configure and control the camera.
None. XST_SUCCESS if required IIC is initialized and configured successfully.XST_FAILURE, otherwise. None.
Referenced by CsiSs_IntrExample.
u32 CsiSs_CciSetupIntrSystem(void)
This function setup interrupts of the IIC instance if used for the MIPI CSI Rx Subsystem.
None XST_SUCCESS if IIC interrupt is configured successfully.XST_FAILURE,if IIC interrupt is failed to configure None.
u32 CsiSs_SetupIntrSystem(void)
void CsiSs_DphyEventHandler(void *InstancePtr, u32 Mask)
This function is called when a DPHY level error event is received by the MIPI CSI Rx Subsystem core.
InstancePtr is a pointer to the XCsiSs instance. Mask of interrupt which caused this event None. Use the XCsiSs_SetCallback driver function to set this function as the handler for DPHY level error event.
References XCSISS_ISR_SOTERR_MASK, XCSISS_ISR_SOTSYNCERR_MASK.
Referenced by CsiSs_IntrExample.
void CsiSs_PktLvlEventHandler(void *InstancePtr, u32 Mask)
This function is called when a Packet level error event is received by the MIPI CSI Rx Subsystem core.
InstancePtr is a pointer to the XCsiSs instance. Mask of interrupt which caused this event None. Use the XCsiSs_SetCallback driver function to set this function as the handler for Packet level error event.
References XCSISS_ISR_CRCERR_MASK, XCSISS_ISR_DATAIDERR_MASK, XCSISS_ISR_ECC1BERR_MASK, XCSISS_ISR_ECC2BERR_MASK.
Referenced by CsiSs_IntrExample.
void CsiSs_ProtLvlEventHandler(void *InstancePtr, u32 Mask)
This function is called when a Protocol decoding level error event is received by the MIPI CSI Rx Subsystem core.
InstancePtr is a pointer to the XCsiSs instance. Mask of interrupt which caused this event None. Use the XCsiSs_SetCallback driver function to set this function as the handler for Protocol Decoding level error
References XCSISS_ISR_VC0FLVLERR_MASK, XCSISS_ISR_VC0FSYNCERR_MASK, XCSISS_ISR_VC1FLVLERR_MASK, XCSISS_ISR_VC1FSYNCERR_MASK, XCSISS_ISR_VC2FLVLERR_MASK, XCSISS_ISR_VC2FSYNCERR_MASK, XCSISS_ISR_VC3FLVLERR_MASK, XCSISS_ISR_VC3FSYNCERR_MASK.
Referenced by CsiSs_IntrExample.
void CsiSs_SPktEventHandler(void *InstancePtr, u32 Mask)
This function is called when a Short Packet FIFO event is received by the MIPI CSI Rx Subsystem core.
InstancePtr is a pointer to the XCsiSs instance. Mask of interrupt which caused this event None. Use the XCsiSs_SetCallback driver function to set this function as the handler for Short Packet FIFO error event.
References XCsiSs::SpktData, XCsiSs_GetShortPacket, XCSISS_ISR_SPFIFOF_MASK, XCSISS_ISR_SPFIFONE_MASK.
Referenced by CsiSs_IntrExample.
void CsiSs_ErrEventHandler(void *InstancePtr, u32 Mask)
This function is called when a Other errors event is received by the MIPI CSI Rx Subsystem core.
InstancePtr is a pointer to the XCsiSs instance. Mask of interrupt which caused this event None. Use the XCsiSs_SetCallback driver function to set this function as the handler for Other error event.
References XCSISS_ISR_ILC_MASK, XCSISS_ISR_SLBF_MASK, XCSISS_ISR_WC_MASK, XCSISS_ISR_YUV420_MASK.
Referenced by CsiSs_IntrExample.
void CsiSs_FrameRcvdEventHandler(void *InstancePtr, u32 Mask)
This function is called when a Frame is received by the MIPI CSI Rx Subsystem core.
InstancePtr is a pointer to the XCsiSs instance. Mask of interrupt which caused this event None. Use the XCsiSs_SetCallback driver function to set this function as the handler for Frame Received event.
Referenced by CsiSs_IntrExample.
void Delay(u32 Seconds)
For Microblaze we use an assembly loop that is roughly the same regardless of optimization level, although caches and memory access time can make the delay vary.
Just keep in mind that after resetting or updating the PHY modes, the PHY typically needs time to recover. Number of seconds to sleep None None
Referenced by CsiSs_IntrExample.
int main()
This is the main function for XCsiSs interrupt example.
If the CsiSs_IntrExample function which sets up the system succeeds, this function will wait for the interrupts. Once a connection event or pulse is detected, CsiSs will RX device capabilities and re-start the subsystem. None. XST_FAILURE if the interrupt example was unsuccessful. Unless setup failed, main will never return since CsiSs_IntrExample is blocking (it is waiting on interrupts for Hot-Plug-Detect (HPD) events.
References CsiSs_IntrExample.