xcsiss_intr.c
void XCsiSs_IntrHandler(void *InstancePtr)
Interrupt handler for the MIPI CSI Rx Subsystem.
This function is the interrupt handler for the MIPI CSI Rx Subsystem.This function is the interrupt handler for the MIPI CSI Rx Subsystem driver. It processes all pending interrupts and routes them to the appropriate callback handlers. InstancePtr is a pointer to the XCsiSs instance (passed as void *). None. This function should be connected to the interrupt system. The application is responsible for connecting this function to the interrupt system. Application beyond this driver is also responsible for providing callbacks to handle interrupts and installing the callbacks using XCsiSs_SetCallBack() during initialization phase. InstancePtr is a pointer to the XCsiSs core instance that just interrupted. None. None.
References XCsiSs::CsiPtr.
Referenced by CsiSs_IntrExample, main.
u32 XCsiSs_SetCallBack(XCsiSs *InstancePtr, u32 HandlerType, void *CallbackFunc, void *CallbackRef)
Set callback function for interrupt handling.
This routine installs an asynchronous callback function for the given HandlerType:This function sets a callback function for a specific interrupt handler type. The registered callback function will be called when the corresponding interrupt occurs. InstancePtr is a pointer to the XCsiSs instance. HandlerType is the type of handler to register. It can be one of: XCSISS_HANDLER_DPHYXCSISS_HANDLER_PKTLVLXCSISS_HANDLER_PROTLVLXCSISS_HANDLER_SHORTPACKETXCSISS_HANDLER_FRAMERECVDXCSISS_HANDLER_OTHERERRORXCSISS_HANDLER_VCX CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback was successfully registered.XST_FAILURE if callback registration failed. None. HandlerType Invoked by this driver when: ------------------------- -------------------------------------------------- XCSISS_HANDLER_DPHY A DPHY Level Error has been detected. XCSISS_HANDLER_PROTLVL A Protocol Level Error has been detected. XCSISS_HANDLER_PKTLVL A Packet Level Error has been detected. XCSISS_HANDLER_SHORTPACKET A Short packet has been received or the Short Packet FIFO is full. XCSISS_HANDLER_FRAMERECVD A Frame has been received XCSISS_HANDLER_OTHERERROR Any other type of interrupt has occurred like Stream Line Buffer Full, Incorrect Lanes, etc InstancePtr is the XCsi instance to operate on HandlerType is the type of call back to be registered. CallbackFunc is the pointer to a call back function which is called when a particular event occurs. CallbackRef is a void pointer to data to be referenced to by the CallBackFunc XST_SUCCESS when handler is installed.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XCsiSs::CsiPtr, XCsiSs::IsReady.
Referenced by CsiSs_IntrExample.
void XCsiSs_IntrDisable(XCsiSs *InstancePtr, u32 IntrMask)
Disable interrupts in the MIPI CSI Rx Subsystem.
This function is used to disable the interrupts in the CSI core.This function disables the specified interrupts in the MIPI CSI Rx Subsystem. InstancePtr is a pointer to the XCsiSs instance. IntrMask is the bit-mask of the interrupts to be disabled. None. None. InstancePtr is a pointer to the Subsystem instance to be worked on. IntrMask Indicates Mask for enable interrupts. None None
References XCsiSs::CsiPtr, XCSISS_ISR_ALLINTR_MASK.