xcsiss_sinit.c
XCsiSs_Config XCsiSs_ConfigTable[][]
MIPI CSI Rx Subsystem configuration table (SDT)
This table contains configuration information for each MIPI CSI Rx Subsystem instance in the system when using System Device Tree (SDT). Each entry describes the hardware configuration for a specific instance including sub-core presence and parameters.
XCsiSs_Config * XCsiSs_LookupConfig(UINTPTR BaseAddress)
Lookup the device configuration based on the base address.
This function looks for the device configuration based on the unique device ID.This function returns a reference to an XCsiSs_Config structure based on the base address. This function will return a NULL pointer if the base address is not found. BaseAddress is the base address of the device to lookup for. XCsiSs_Config reference if BaseAddress is found, NULL otherwise. None. The table XCsiSs_ConfigTable[] contains the configuration information for each instance of the device in the system. DeviceId is the unique device ID of the device being looked up A pointer to the configuration table entry corresponding to the given device ID, or NULL if no match is found None.
Referenced by CsiSs_IntrExample, CsiSs_SelfTestExample, InitializeCsiRxSs.
u32 XCsiSs_GetDrvIndex(UINTPTR BaseAddress)
Get the driver index based on the base address.
This function returns the Index number of config table using BaseAddress.This function returns the driver index based on the base address. BaseAddress is the base address of the device. Driver index. None. BaseAddress is base address of the instance Index number of the config table