xmipi_example.c
LOOPBACK_MODE_EN
XPAR_CPU_CORE_CLOCK_FREQ_HZ
UART_BASEADDR
I2C_MUX_ADDR
I2C Mux Address.
Referenced by I2cMux.
I2C_CLK_ADDR
I2C Clk Address.
Referenced by I2cClk, main.
IIC_SENSOR_INTR_ID
HDMI_TX_SS_DEVICE_ID
HDMI_TXSS_INTR_ID
HDMI_TX_SS_INTR_ID
GPIO_TPG_RESET_DEVICE_ID
V_TPG_DEVICE_ID
GPIO_SENSOR_BASE
GPIO_IP_RESET_BASE
GPIO_IP_RESET1_BASE
GPIO_IP_RESET2_BASE
XPAR_INTC_0_V_FRMBUF_WR_0_VEC_ID
XPAR_INTC_0_V_FRMBUF_RD_0_VEC_ID
u8 SinkReady
u8 IsStreamUp
u64 TxLineRate
XVphy Vphy
XV_HdmiTxSs HdmiTxSs
XV_HdmiTxSs_Config* XV_HdmiTxSs_ConfigPtr
XCsiSs CsiSs
XCsiSs_Config XCsiSs_ConfigPtr
XDsiTxSs DSITxSs
XDsiTxSs_Config XDsiTxSs_ConfigPtr
XScuGic Intc
XGpio Gpio_Tpg_resetn
XGpio_Config* Gpio_Tpg_resetn_ConfigPtr
XV_tpg Tpg
XV_tpg_Config* Tpg_ConfigPtr
XTpg_PatternId Pattern
Video pattern.
Referenced by main, XV_ConfigTpg.
u8 IsPassThrough
Demo mode 0-colorbar 1-pass through.
Referenced by EnableColorBar, main, TxConnectCallback, TxStreamUpCallback.
u8 StartTxAfterRxFlag
u8 TxBusy
u8 TxRestartColorbar
u32 Index
XHdmi_Menu HdmiMenu
XPipeline_Cfg Pipeline_Cfg
XPipeline_Cfg New_Cfg
XV_FrmbufWr_l2 frmbufwr
XV_FrmbufRd_l2 frmbufrd
XIic IicIoExpander
XIic IicSensor
XVprocSs scaler_new_inst
int I2cMux(void)
This function setup SI5324 clock generator over IIC.
The number of bytes sent. None. None. The number of bytes sent. None.
References I2C_MUX_ADDR.
int I2cClk(u32 InFreq, u32 OutFreq)
This function setup SI5324 clock generator either in free or locked mode.
InFreq specifies an input frequency for the si5324. OutFreq specifies the output frequency of si5324. Zero if error in programming external clock ele '1' if success None. Index specifies an index for selecting mode frequency. Mode specifies either free or locked mode. Zero if error in programming external clock.One if programmed external clock. None.
References I2C_CLK_ADDR.
Referenced by EnableColorBar, StartTxAfterRx.
void EnableColorBar(XVphy *VphyPtr, XV_HdmiTxSs *HdmiTxSsPtr, XVidC_VideoMode VideoMode, XVidC_ColorFormat ColorFormat, XVidC_ColorDepth Bpc)
This function enables the ColorBar.
VphyPtr is a pointer to the VPHY core instance. HdmiTxSsPtr is a pointer to the XV_HdmiTxSs instance. VideoMode is the resolution that is to be displayed ColorFormat that can be RGB888 or YUV422 or YUV420 Bpc is the Bits per color that can be 8 or 10 or 12 None. None.
References I2cClk, IsPassThrough.
Referenced by main.
u32 InitStreamMuxGpio(void)
This function initializes GPIO IP for Stream Switch selection and gets config parameters.
XST_SUCCESS if successful or else XST_FAILURE. None.
Referenced by main.
void Info(void)
This function outputs the video timing , Audio, Link Status, HDMI RX state of HDMI RX core.
In addition, it also prints information about HDMI TX, and HDMI GT cores.None. None. In addition, it also prints information about HDMI TX, and HDMI GT cores. None. None. None.
void CloneTxEdid(void)
This function clones the EDID of the connected sink device to the HDMI RX.
None. None.
void SendVSInfoframe(void)
void XV_ConfigTpg(XV_tpg *InstancePtr)
This function generates video pattern.
InstancePtr TPG Instance Pointer. None. None.
References Pattern.
Referenced by main, StartTxAfterRx.
void ResetTpg(void)
This function resets TPG IP.
None. None.
Referenced by main, StartTxAfterRx.
void EnableDSI()
This function enables MIPI DSI SS.
None. None.
void Shutdown_DSI()
void Reconfigure_DSI()
void Reconfigure_HDMI(void)
void SelectDSIOutput(void)
This function programs GPIO to 1 to select MIPI DSI SS Stream Path in AXI- Stream switch.
None. None. This function programs GPIO to 1 to select MIPI DSI SS Stream Path in AXI- Stream switch.None. None.
Referenced by main.
void SelectHDMIOutput(void)
This function programs GPIO to '0' to select HDMI Stream path in AXI-Stream switch.
None. None. This function programs GPIO to '0' to select HDMI Stream path in AXI-Stream switch.None. None.
Referenced by main.
void config_csi_cap_path()
Main function to initialize the video pipeline and process user input.
XST_SUCCESS if MIPI example was successful else XST_FAILURE None.
References FrmbufrdDoneCallback, FrmbufwrDoneCallback.
void ReportStreamMode(XV_HdmiTxSs *HdmiTxSsPtr, u8 IsPassThrough)
This function reports the stream mode.
HdmiTxSsPtr is a pointer to the XV_HdmiTxSs instance. IsPassThrough is a flag to represent passthrough or colorbar mode. None. None.
Referenced by TxStreamUpCallback.
void TxConnectCallback(void *CallbackRef)
This function is called when a TX connect event has occurred.
CallbackRef is a callback function reference. None. None.
References IsPassThrough.
Referenced by main.
void VphyHdmiTxInitCallback(void *CallbackRef)
This function is called when the GT TX reference input clock has changed.
CallbackRef is a callback function reference. None. None.
Referenced by main.
void VphyHdmiTxReadyCallback(void *CallbackRef)
This function is called when the GT TX has been initialized.
CallbackRef is a callback function reference. None. None.
Referenced by main.
void TxVsCallback(void *CallbackRef)
This function is called when a TX vsync has occurred.
CallbackRef is a callback function reference. None. None.
Referenced by main.
void TxStreamUpCallback(void *CallbackRef)
This function is called when the TX stream is up.
CallbackRef is a callback function reference. None. None.
References IsPassThrough, ReportStreamMode.
Referenced by main.
void TxStreamDownCallback(void *CallbackRef)
This function is called when the TX stream is down.
CallbackRef is a callback function reference. None. None.
void StartTxAfterRx(void)
This function is called to start the TX stream after the RX stream was up and running.
None. None.
References I2cClk, ResetTpg, XV_ConfigTpg.
void Xil_AssertCallbackRoutine(u8 *File, s32 Line)
This function asserts a callback error.
File is current file name. Line is line number of the asserted callback. None. None.
Referenced by main.
void CamReset(void)
This function resets IMX274 camera sensor.
None. None.
void Reset_IP_Pipe(void)
This function resets image processing pipe.
None. None.
Referenced by main.
int main(void)
Main function to initialize the video pipeline and process user input.
XST_SUCCESS if MIPI example was successful else XST_FAILURE None.
References XCsiSs::Config, config_csi_cap_path, EnableColorBar, EnableDSI, I2C_CLK_ADDR, InitDSI, InitializeCsiRxSs, InitIIC, InitImageProcessingPipe, InitStreamMuxGpio, XCsiSs_Config::IntrId, XCsiSs_Config::IntrParent, IsPassThrough, Pattern, PrintPipeConfig, Reset_IP_Pipe, ResetTpg, SelectDSIOutput, SelectHDMIOutput, SetColorDepth, SetupCameraSensor, SetupDSI, StartSensor, TxConnectCallback, TxStreamUpCallback, TxVsCallback, VphyHdmiTxInitCallback, VphyHdmiTxReadyCallback, XCsiSs_IntrHandler, Xil_AssertCallbackRoutine, XMipi_MenuInitialize, XMipi_MenuProcess, XV_ConfigTpg.