xmipi_menu.h
XMIPI_MENU_H_
Prevent circular inclusions by using protection macros.
XMipi_MenuType
void XMipi_MenuInitialize(XMipi_Menu *InstancePtr, u32 UartBaseAddress)
This function takes care of the MIPI menu initialization.
InstancePtr is a pointer to the XMipi_Menu instance. UartBaseAddress points to the base address of PS uart. None None
Referenced by main.
void XMipi_MenuProcess(XMipi_Menu *InstancePtr)
This function is called to trigger the MIPI menu state machine.
InstancePtr is a pointer to the XMipi_Menu instance. None None
Referenced by main.
void XMipi_MenuReset(XMipi_Menu *InstancePtr)
This function resets the menu to the main menu.
InstancePtr is a pointer to the XMipi_Menu instance. None None
void InitImageProcessingPipe(void)
This function Initializes Image Processing blocks wrt to selected resolution.
None. None.
References ConfigCSC, ConfigDemosaic, ConfigGammaLut.
Referenced by main.
void start_csi_cap_pipe(XVidC_VideoMode VideoMode)
void DisableImageProcessingPipe(void)
This function disables Demosaic, GammaLut and VProcSS IPs.
None. None.
void CamReset(void)
This function resets IMX274 camera sensor.
None. None. This function resets IMX274 camera sensor.None. None.
void Reset_IP_Pipe(void)
This function resets image processing pipe.
None. None.