xmipi_menu.c
typedef XMipi_MenuType XMipi_MenuFuncType(XMipi_Menu *InstancePtr, u8 Input)(XMipi_Menu *InstancePtr, u8 Input)
u8 Edid[][]
u8 TxRestartColorbar
XVprocSs scaler_new_inst
XPipeline_Cfg Pipeline_Cfg
XPipeline_Cfg New_Cfg
XV_FrmbufWr_l2 frmbufwr
XV_FrmbufRd_l2 frmbufrd
u32 rd_ptr
u32 wr_ptr
u32 frmrd_start
u32 frm_cnt
u32 frm_cnt1
XMipi_MenuFuncType* const XMipi_MenuTable[XMIPI_NUM_MENUS][XMIPI_NUM_MENUS]
This table contains the function pointers for all possible states.
The order of elements must match the XMipi_MenuType enumerator definitions.
XVphy Vphy
XV_HdmiTxSs HdmiTxSs
u8 IsPassThrough
Demo mode 0-colorbar 1-pass through.
u8 TxBusy
XV_tpg Tpg
XTpg_PatternId Pattern
Video pattern.
Referenced by main, XV_ConfigTpg.
static XMipi_MenuType XMipi_MainMenu(XMipi_Menu *InstancePtr, u8 Input)
This function implements the MIPI main menu state.
input is the value used for the next menu state decoder. The next menu state. None
static XMipi_MenuType XMipi_ResolutionMenu(XMipi_Menu *InstancePtr, u8 Input)
This function implements the MIPI resolution menu state.
input is the value used for the next menu state decoder. The next menu state. None
static XMipi_MenuType XMipi_LanesMenu(XMipi_Menu *InstancePtr, u8 Input)
This function implements the MIPI Lanes menu state.
input is the value used for the next menu state decoder. The next menu state. None
void XMipi_DisplayMainMenu(void)
This function displays the MIPI main menu.
None None
void XMipi_DisplayResolutionMenu(void)
This function displays the MIPI resolution menu.
None None
void XMipi_DisplayLanesMenu(void)
This function displays the CSI2 Rx Subsystem Lanes menu.
None None
void Info(void)
This function outputs the video timing , Audio, Link Status, HDMI RX state of HDMI RX core.
In addition, it also prints information about HDMI TX, and HDMI GT cores.None. None. In addition, it also prints information about HDMI TX, and HDMI GT cores. None. None. None. In addition, it also prints information about HDMI TX, and HDMI GT cores. None. None. None.
void EnableColorBar(XVphy *VphyPtr, XV_HdmiTxSs *HdmiTxSsPtr, XVidC_VideoMode VideoMode, XVidC_ColorFormat ColorFormat, XVidC_ColorDepth Bpc)
This function enables the ColorBar.
VphyPtr is a pointer to the VPHY core instance. HdmiTxSsPtr is a pointer to the XV_HdmiTxSs instance. VideoMode is the resolution that is to be displayed ColorFormat that can be RGB888 or YUV422 or YUV420 Bpc is the Bits per color that can be 8 or 10 or 12 None. None.
References I2cClk, IsPassThrough.
Referenced by main.
void XV_HdmiTxSs_ShowEdid(XV_HdmiTxSs *InstancePtr)
void CloneTxEdid(void)
This function clones the EDID of the connected sink device to the HDMI RX.
None. None.
void ResetTpg(void)
This function resets TPG IP.
None. None.
Referenced by main, StartTxAfterRx.
void XV_ConfigTpg(XV_tpg *InstancePtr)
This function generates video pattern.
InstancePtr TPG Instance Pointer. None. None.
References Pattern.
Referenced by main, StartTxAfterRx.
void EnableDSI()
This function enables MIPI DSI SS.
None. None.
Referenced by main.
void Reset_IP_Pipe(void)
This function resets image processing pipe.
None. None.
void CamReset(void)
This function resets IMX274 camera sensor.
None. None. This function resets IMX274 camera sensor.None. None.
void XMipi_MenuInitialize(XMipi_Menu *InstancePtr, u32 UartBaseAddress)
This function takes care of the MIPI menu initialization.
InstancePtr is a pointer to the XMipi_Menu instance. UartBaseAddress points to the base address of PS uart. None None
Referenced by main.
void XMipi_MenuReset(XMipi_Menu *InstancePtr)
This function resets the menu to the main menu.
InstancePtr is a pointer to the XMipi_Menu instance. None None
void XMipi_MenuProcess(XMipi_Menu *InstancePtr)
This function is called to trigger the MIPI menu state machine.
InstancePtr is a pointer to the XMipi_Menu instance. None None
Referenced by main.
void Shutdown_DSI(void)
void Reconfigure_DSI(void)
void Reconfigure_HDMI(void)