xgpiops_intr.c
void XGpioPs_IntrEnable(XGpioPs *InstancePtr, u8 Bank, u32 Mask)
This function enables the interrupts for the specified pins in the specified bank.
InstancePtr is a pointer to the XGpioPs instance. Bank is the bank number of the GPIO to operate on. Mask is the bit mask of the pins for which interrupts are to be enabled. Bit positions of 1 will be enabled. Bit positions of 0 will keep the previous setting. None. None.
References XGpioPs_Config::BaseAddr, XGpioPs::CoreIntrMask, XGpioPs::GpioConfig, XGpioPs::IsReady, XGpioPs::PmcGpio, XGPIOPS_INTEN_OFFSET, XGPIOPS_ONE, XGPIOPS_REG_MASK_OFFSET, XGPIOPS_TWO, XGpioPs_WriteReg.
Referenced by XGpioPs_SelfTest.
void XGpioPs_IntrEnablePin(XGpioPs *InstancePtr, u32 Pin)
This function enables the interrupt for the specified pin.
InstancePtr is a pointer to the XGpioPs instance. Pin is the pin number for which the interrupt is to be enabled. None. None.
References XGpioPs_Config::BaseAddr, XGpioPs::CoreIntrMask, XGpioPs::GpioConfig, XGpioPs::IsReady, XGpioPs_GetBankPin, XGPIOPS_INTEN_OFFSET, XGPIOPS_REG_MASK_OFFSET, XGpioPs_WriteReg.
void XGpioPs_IntrDisable(XGpioPs *InstancePtr, u8 Bank, u32 Mask)
This function disables the interrupts for the specified pins in the specified bank.
InstancePtr is a pointer to the XGpioPs instance. Bank is the bank number of the GPIO to operate on. Mask is the bit mask of the pins for which interrupts are to be disabled. Bit positions of 1 will be disabled. Bit positions of 0 will keep the previous setting. None. None.
References XGpioPs_Config::BaseAddr, XGpioPs::CoreIntrMask, XGpioPs::GpioConfig, XGpioPs::IsReady, XGpioPs::PmcGpio, XGPIOPS_INTDIS_OFFSET, XGPIOPS_ONE, XGPIOPS_REG_MASK_OFFSET, XGPIOPS_TWO, XGpioPs_WriteReg.
Referenced by XGpioPs_SelfTest.
void XGpioPs_IntrDisablePin(XGpioPs *InstancePtr, u32 Pin)
This function disables the interrupts for the specified pin.
InstancePtr is a pointer to the XGpioPs instance. Pin is the pin number for which the interrupt is to be disabled. None. None.
References XGpioPs_Config::BaseAddr, XGpioPs::CoreIntrMask, XGpioPs::GpioConfig, XGpioPs::IsReady, XGpioPs_GetBankPin, XGPIOPS_INTDIS_OFFSET, XGPIOPS_REG_MASK_OFFSET, XGpioPs_WriteReg.
u32 XGpioPs_IntrGetEnabled(const XGpioPs *InstancePtr, u8 Bank)
This function returns the interrupt enable status for a bank.
InstancePtr is a pointer to the XGpioPs instance. Bank is the bank number of the GPIO to operate on. Enabled interrupt(s) in a 32-bit format. Bit positions with 1 indicate that the interrupt for that pin is enabled, bit positions with 0 indicate that the interrupt for that pin is disabled. None.
References XGpioPs_Config::BaseAddr, XGpioPs::GpioConfig, XGpioPs::IsReady, XGpioPs::PmcGpio, XGPIOPS_INTMASK_OFFSET, XGPIOPS_ONE, XGpioPs_ReadReg, XGPIOPS_REG_MASK_OFFSET, XGPIOPS_TWO.
Referenced by XGpioPs_IntrHandler, XGpioPs_SelfTest.
u32 XGpioPs_IntrGetEnabledPin(const XGpioPs *InstancePtr, u32 Pin)
This function returns whether interrupts are enabled for the specified pin.
InstancePtr is a pointer to the XGpioPs instance. Pin is the pin number for which the interrupt enable status is to be known. TRUE if the interrupt is enabled.FALSE if the interrupt is disabled. None.
References XGpioPs_Config::BaseAddr, XGpioPs::GpioConfig, XGpioPs::IsReady, XGpioPs_GetBankPin, XGPIOPS_INTMASK_OFFSET, XGpioPs_ReadReg, XGPIOPS_REG_MASK_OFFSET.
u32 XGpioPs_IntrGetStatus(const XGpioPs *InstancePtr, u8 Bank)
This function returns interrupt status read from Interrupt Status Register.
InstancePtr is a pointer to the XGpioPs instance. Bank is the bank number of the GPIO to operate on. The value read from Interrupt Status Register. None.
References XGpioPs_Config::BaseAddr, XGpioPs::GpioConfig, XGpioPs::IsReady, XGpioPs::PmcGpio, XGPIOPS_INTSTS_OFFSET, XGPIOPS_ONE, XGpioPs_ReadReg, XGPIOPS_REG_MASK_OFFSET, XGPIOPS_TWO.
Referenced by XGpioPs_IntrHandler.
u32 XGpioPs_IntrGetStatusPin(const XGpioPs *InstancePtr, u32 Pin)
This function returns interrupt enable status of the specified pin.
InstancePtr is a pointer to the XGpioPs instance. Pin is the pin number for which the interrupt enable status is to be known. TRUE if the interrupt has occurred.FALSE if the interrupt has not occurred. None.
References XGpioPs_Config::BaseAddr, XGpioPs::GpioConfig, XGpioPs::IsReady, XGpioPs_GetBankPin, XGPIOPS_INTSTS_OFFSET, XGpioPs_ReadReg, XGPIOPS_REG_MASK_OFFSET.
void XGpioPs_IntrClear(const XGpioPs *InstancePtr, u8 Bank, u32 Mask)
This function clears pending interrupt(s) with the provided mask.
This function should be called after the software has serviced the interrupts that are pending. InstancePtr is a pointer to the XGpioPs instance. Bank is the bank number of the GPIO to operate on. Mask is the mask of the interrupts to be cleared. Bit positions of 1 will be cleared. Bit positions of 0 will not change the previous interrupt status. None.
References XGpioPs_Config::BaseAddr, XGpioPs::GpioConfig, XGpioPs::IsReady, XGpioPs::PmcGpio, XGPIOPS_INTSTS_OFFSET, XGPIOPS_ONE, XGPIOPS_REG_MASK_OFFSET, XGPIOPS_TWO, XGpioPs_WriteReg.
Referenced by XGpioPs_IntrHandler.
void XGpioPs_IntrClearPin(const XGpioPs *InstancePtr, u32 Pin)
This function clears the specified pending interrupt.
This function should be called after the software has serviced the interrupts that are pending. InstancePtr is a pointer to the XGpioPs instance. Pin is the pin number for which the interrupt status is to be cleared. None.
References XGpioPs_Config::BaseAddr, XGpioPs::GpioConfig, XGpioPs::IsReady, XGpioPs_GetBankPin, XGPIOPS_INTSTS_OFFSET, XGpioPs_ReadReg, XGPIOPS_REG_MASK_OFFSET, XGpioPs_WriteReg.
void XGpioPs_SetIntrType(const XGpioPs *InstancePtr, u8 Bank, u32 IntrType, u32 IntrPolarity, u32 IntrOnAny)
This function is used for setting the Interrupt Type, Interrupt Polarity and Interrupt On Any for the specified GPIO Bank pins.
InstancePtr is a pointer to an XGpioPs instance. Bank is the bank number of the GPIO to operate on. IntrType is the 32 bit mask of the interrupt type. 0 means Level Sensitive and 1 means Edge Sensitive. IntrPolarity is the 32 bit mask of the interrupt polarity. 0 means Active Low or Falling Edge and 1 means Active High or Rising Edge. IntrOnAny is the 32 bit mask of the interrupt trigger for edge triggered interrupts. 0 means trigger on single edge using the configured interrupt polarity and 1 means trigger on both edges. None. This function is used for setting the interrupt related properties of all the pins in the specified bank. The previous state of the pins is not maintained. To change the Interrupt properties of a single GPIO pin, use the function XGpioPs_SetPinIntrType().
References XGpioPs_Config::BaseAddr, XGpioPs::GpioConfig, XGpioPs::IsReady, XGpioPs::PmcGpio, XGPIOPS_INTANY_OFFSET, XGPIOPS_INTPOL_OFFSET, XGPIOPS_INTTYPE_OFFSET, XGPIOPS_ONE, XGPIOPS_REG_MASK_OFFSET, XGPIOPS_TWO, XGpioPs_WriteReg.
Referenced by XGpioPs_SelfTest.
void XGpioPs_GetIntrType(const XGpioPs *InstancePtr, u8 Bank, u32 *IntrType, u32 *IntrPolarity, u32 *IntrOnAny)
This function is used for getting the Interrupt Type, Interrupt Polarity and Interrupt On Any for the specified GPIO Bank pins.
InstancePtr is a pointer to an XGpioPs instance. Bank is the bank number of the GPIO to operate on. IntrType returns the 32 bit mask of the interrupt type. 0 means Level Sensitive and 1 means Edge Sensitive. IntrPolarity returns the 32 bit mask of the interrupt polarity. 0 means Active Low or Falling Edge and 1 means Active High or Rising Edge. IntrOnAny returns the 32 bit mask of the interrupt trigger for edge triggered interrupts. 0 means trigger on single edge using the configured interrupt polarity and 1 means trigger on both edges. None. None.
References XGpioPs_Config::BaseAddr, XGpioPs::GpioConfig, XGpioPs::IsReady, XGpioPs::PmcGpio, XGPIOPS_INTANY_OFFSET, XGPIOPS_INTPOL_OFFSET, XGPIOPS_INTTYPE_OFFSET, XGPIOPS_ONE, XGpioPs_ReadReg, XGPIOPS_REG_MASK_OFFSET, XGPIOPS_TWO.
Referenced by XGpioPs_SelfTest.
void XGpioPs_SetIntrTypePin(const XGpioPs *InstancePtr, u32 Pin, u8 IrqType)
This function is used for setting the IRQ Type of a single GPIO pin.
InstancePtr is a pointer to an XGpioPs instance. Pin is the pin number whose IRQ type is to be set. IrqType is the IRQ type for GPIO Pin. Use XGPIOPS_IRQ_TYPE_* defined in xgpiops.h to specify the IRQ type. None. None.
References XGpioPs_Config::BaseAddr, XGpioPs::GpioConfig, XGpioPs::IsReady, XGpioPs_GetBankPin, XGPIOPS_INTANY_OFFSET, XGPIOPS_INTPOL_OFFSET, XGPIOPS_INTTYPE_OFFSET, XGPIOPS_IRQ_TYPE_EDGE_BOTH, XGPIOPS_IRQ_TYPE_EDGE_FALLING, XGPIOPS_IRQ_TYPE_EDGE_RISING, XGPIOPS_IRQ_TYPE_LEVEL_HIGH, XGPIOPS_IRQ_TYPE_LEVEL_LOW, XGpioPs_ReadReg, XGPIOPS_REG_MASK_OFFSET, XGpioPs_WriteReg.
u8 XGpioPs_GetIntrTypePin(const XGpioPs *InstancePtr, u32 Pin)
This function returns the IRQ Type of a given GPIO pin.
InstancePtr is a pointer to an XGpioPs instance. Pin is the pin number whose IRQ type is to be obtained. None. Use XGPIOPS_IRQ_TYPE_* defined in xgpiops.h for the IRQ type returned by this function.
References XGpioPs_Config::BaseAddr, XGpioPs::GpioConfig, XGpioPs::IsReady, XGpioPs_GetBankPin, XGPIOPS_INTANY_OFFSET, XGPIOPS_INTPOL_OFFSET, XGPIOPS_INTTYPE_OFFSET, XGPIOPS_IRQ_TYPE_EDGE_BOTH, XGPIOPS_IRQ_TYPE_EDGE_FALLING, XGPIOPS_IRQ_TYPE_EDGE_RISING, XGPIOPS_IRQ_TYPE_LEVEL_HIGH, XGPIOPS_IRQ_TYPE_LEVEL_LOW, XGpioPs_ReadReg, XGPIOPS_REG_MASK_OFFSET.
void XGpioPs_SetCallbackHandler(XGpioPs *InstancePtr, void *CallBackRef, XGpioPs_Handler FuncPointer)
This function sets the status callback function.
The callback function is called by the XGpioPs_IntrHandler when an interrupt occurs. InstancePtr is a pointer to the XGpioPs instance. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. FuncPointer is the pointer to the callback function. None. The handler is called within interrupt context, so it should do its work quickly and queue potentially time-consuming work to a task-level thread.
References XGpioPs::CallBackRef, XGpioPs::Handler, XGpioPs::IsReady.
void XGpioPs_IntrHandler(const XGpioPs *InstancePtr)
This function is the interrupt handler for GPIO interrupts.It checks the interrupt status registers of all the banks to determine the actual bank in which an interrupt has been triggered.
It then calls the upper layer callback handler set by the function XGpioPs_SetBankHandler(). The callback is called when an interrupt InstancePtr is a pointer to the XGpioPs instance. None. This function does not save and restore the processor context such that the user must provide this processing.
References XGpioPs::CallBackRef, XGpioPs::CoreIntrMask, XGpioPs::Handler, XGpioPs::IsReady, XGpioPs::MaxBanks, XGpioPs::PmcGpio, XGpioPs_IntrClear, XGpioPs_IntrGetEnabled, XGpioPs_IntrGetStatus, XGPIOPS_ONE, XGPIOPS_TWO.