xgpiops.c
void StubHandler(void *CallBackRef, u32 Bank, u32 Status)
Stub handler.
This is a stub for the status callback.The stub is here in case the upper layers do not set the handler. CallBackRef is a pointer to the upper layer callback reference Bank is the GPIO Bank in which an interrupt occurred. Status is the Interrupt status of the GPIO bank. None. None.
Referenced by XGpioPs_CfgInitialize.
s32 XGpioPs_CfgInitialize(XGpioPs *InstancePtr, const XGpioPs_Config *ConfigPtr, UINTPTR EffectiveAddr)
This function initializes a XGpioPs instance/driver.
All members of the XGpioPs instance structure are initialized and StubHandlers are assigned to the Bank Status Handlers. InstancePtr is a pointer to the XGpioPs instance. ConfigPtr points to the XGpioPs device configuration structure. EffectiveAddr is the device base address in the virtual memory address space. If the address translation is not used then the physical address should be passed. Unexpected errors may occur if the address mapping is changed after this function is invoked. XST_SUCCESS always. None.
References XGpioPs_Config::BaseAddr, XGpioPs::CoreIntrMask, XGpioPs::GpioConfig, XGpioPs::Handler, XGpioPs::IsReady, XGpioPs::MaxBanks, XGpioPs::MaxPinNum, XGpioPs::Platform, XGpioPs::PmcGpio, StubHandler, XGPIOPS_INTDIS_OFFSET, XGPIOPS_ONE, XGPIOPS_REG_MASK_OFFSET, XGPIOPS_TWO, XGpioPs_WriteReg.
Referenced by GpioPolledExample.
u32 XGpioPs_Read(const XGpioPs *InstancePtr, u8 Bank)
Read the Data register of the specified GPIO bank.
InstancePtr is a pointer to the XGpioPs instance. Bank is the bank number of the GPIO to operate on. Current value of the Data register. This function is used for reading the state of all the GPIO pins of specified bank.
References XGpioPs_Config::BaseAddr, XGpioPs::GpioConfig, XGpioPs::IsReady, XGpioPs::PmcGpio, XGPIOPS_DATA_BANK_OFFSET, XGPIOPS_DATA_RO_OFFSET, XGPIOPS_ONE, XGpioPs_ReadReg, XGPIOPS_TWO.
u32 XGpioPs_ReadPin(const XGpioPs *InstancePtr, u32 Pin)
Read Data from the specified pin.
InstancePtr is a pointer to the XGpioPs instance. Pin is the pin number for which the data has to be read. Current value of the Pin (0 or 1). This function is used for reading the state of the specified GPIO pin.
References XGpioPs_Config::BaseAddr, XGpioPs::GpioConfig, XGpioPs::IsReady, XGPIOPS_DATA_BANK_OFFSET, XGPIOPS_DATA_RO_OFFSET, XGpioPs_GetBankPin, XGpioPs_ReadReg.
void XGpioPs_Write(const XGpioPs *InstancePtr, u8 Bank, u32 Data)
Write to the Data register of the specified GPIO bank.
InstancePtr is a pointer to the XGpioPs instance. Bank is the bank number of the GPIO to operate on. Data is the value to be written to the Data register. None. This function is used for writing to all the GPIO pins of the bank. The previous state of the pins is not maintained.
References XGpioPs_Config::BaseAddr, XGpioPs::GpioConfig, XGpioPs::IsReady, XGpioPs::PmcGpio, XGPIOPS_DATA_BANK_OFFSET, XGPIOPS_DATA_OFFSET, XGPIOPS_ONE, XGPIOPS_TWO, XGpioPs_WriteReg.
void XGpioPs_WritePin(const XGpioPs *InstancePtr, u32 Pin, u32 Data)
Write data to the specified pin.
InstancePtr is a pointer to the XGpioPs instance. Pin is the pin number to which the Data is to be written. Data is the data to be written to the specified pin (0 or 1). None. This function does a masked write to the specified pin of the specified GPIO bank. The previous state of other pins is maintained.
References XGpioPs_Config::BaseAddr, XGpioPs::GpioConfig, XGpioPs::IsReady, XGPIOPS_DATA_LSW_OFFSET, XGPIOPS_DATA_MASK_OFFSET, XGPIOPS_DATA_MSW_OFFSET, XGpioPs_GetBankPin, XGpioPs_WriteReg.
void XGpioPs_SetDirection(const XGpioPs *InstancePtr, u8 Bank, u32 Direction)
Set the Direction of the pins of the specified GPIO Bank.
InstancePtr is a pointer to the XGpioPs instance. Bank is the bank number of the GPIO to operate on. Direction is the 32 bit mask of the Pin direction to be set for all the pins in the Bank. Bits with 0 are set to Input mode, bits with 1 are set to Output Mode. None. This function is used for setting the direction of all the pins in the specified bank. The previous state of the pins is not maintained.
References XGpioPs_Config::BaseAddr, XGpioPs::GpioConfig, XGpioPs::IsReady, XGpioPs::PmcGpio, XGPIOPS_DIRM_OFFSET, XGPIOPS_ONE, XGPIOPS_REG_MASK_OFFSET, XGPIOPS_TWO, XGpioPs_WriteReg.
void XGpioPs_SetDirectionPin(const XGpioPs *InstancePtr, u32 Pin, u32 Direction)
Set the Direction of the specified pin.
InstancePtr is a pointer to the XGpioPs instance. Pin is the pin number to which the Data is to be written. Direction is the direction to be set for the specified pin. Valid values are 0 for Input Direction, 1 for Output Direction. None.
References XGpioPs_Config::BaseAddr, XGpioPs::GpioConfig, XGpioPs::IsReady, XGPIOPS_DIRM_OFFSET, XGpioPs_GetBankPin, XGpioPs_ReadReg, XGPIOPS_REG_MASK_OFFSET, XGpioPs_WriteReg.
u32 XGpioPs_GetDirection(const XGpioPs *InstancePtr, u8 Bank)
Get the Direction of the pins of the specified GPIO Bank.
InstancePtr is a pointer to the XGpioPs instance. Bank is the bank number of the GPIO to operate on. Returns a 32 bit mask of the Direction register. Bits with 0 are in Input mode, bits with 1 are in Output Mode. None.
References XGpioPs_Config::BaseAddr, XGpioPs::GpioConfig, XGpioPs::IsReady, XGpioPs::PmcGpio, XGPIOPS_DIRM_OFFSET, XGPIOPS_ONE, XGpioPs_ReadReg, XGPIOPS_REG_MASK_OFFSET, XGPIOPS_TWO.
u32 XGpioPs_GetDirectionPin(const XGpioPs *InstancePtr, u32 Pin)
Get the Direction of the specified pin.
InstancePtr is a pointer to the XGpioPs instance. Pin is the pin number for which the Direction is to be retrieved. Direction of the specified pin. 0 for Input Direction1 for Output Direction None.
References XGpioPs_Config::BaseAddr, XGpioPs::GpioConfig, XGpioPs::IsReady, XGPIOPS_DIRM_OFFSET, XGpioPs_GetBankPin, XGpioPs_ReadReg, XGPIOPS_REG_MASK_OFFSET.
void XGpioPs_SetOutputEnable(const XGpioPs *InstancePtr, u8 Bank, u32 OpEnable)
Set the Output Enable of the pins of the specified GPIO Bank.
InstancePtr is a pointer to the XGpioPs instance. Bank is the bank number of the GPIO to operate on. OpEnable is the 32 bit mask of the Output Enables to be set for all the pins in the Bank. The Output Enable of bits with 0 are disabled, the Output Enable of bits with 1 are enabled. None. This function is used for setting the Output Enables of all the pins in the specified bank. The previous state of the Output Enables is not maintained.
References XGpioPs_Config::BaseAddr, XGpioPs::GpioConfig, XGpioPs::IsReady, XGpioPs::PmcGpio, XGPIOPS_ONE, XGPIOPS_OUTEN_OFFSET, XGPIOPS_REG_MASK_OFFSET, XGPIOPS_TWO, XGpioPs_WriteReg.
void XGpioPs_SetOutputEnablePin(const XGpioPs *InstancePtr, u32 Pin, u32 OpEnable)
Set the Output Enable of the specified pin.
InstancePtr is a pointer to the XGpioPs instance. Pin is the pin number to which the Data is to be written. OpEnable specifies whether the Output Enable for the specified pin should be enabled. Valid values are 0 for Disabling Output Enable, 1 for Enabling Output Enable. None. None.
References XGpioPs_Config::BaseAddr, XGpioPs::GpioConfig, XGpioPs::IsReady, XGpioPs_GetBankPin, XGPIOPS_OUTEN_OFFSET, XGpioPs_ReadReg, XGPIOPS_REG_MASK_OFFSET, XGpioPs_WriteReg.
u32 XGpioPs_GetOutputEnable(const XGpioPs *InstancePtr, u8 Bank)
Get the Output Enable status of the pins of the specified GPIO Bank.
InstancePtr is a pointer to the XGpioPs instance. Bank is the bank number of the GPIO to operate on. Returns a a 32 bit mask of the Output Enable register. Bits with 0 are in Disabled state, bits with 1 are in Enabled State. None.
References XGpioPs_Config::BaseAddr, XGpioPs::GpioConfig, XGpioPs::IsReady, XGpioPs::PmcGpio, XGPIOPS_ONE, XGPIOPS_OUTEN_OFFSET, XGpioPs_ReadReg, XGPIOPS_REG_MASK_OFFSET, XGPIOPS_TWO.
u32 XGpioPs_GetOutputEnablePin(const XGpioPs *InstancePtr, u32 Pin)
Get the Output Enable status of the specified pin.
InstancePtr is a pointer to the XGpioPs instance. Pin is the pin number for which the Output Enable status is to be retrieved. Output Enable of the specified pin. 0 if Output Enable is disabled for this pin1 if Output Enable is enabled for this pin None.
References XGpioPs_Config::BaseAddr, XGpioPs::GpioConfig, XGpioPs::IsReady, XGpioPs_GetBankPin, XGPIOPS_OUTEN_OFFSET, XGpioPs_ReadReg, XGPIOPS_REG_MASK_OFFSET.
void XGpioPs_GetBankPin(u8 PinNumber, u8 *BankNumber, u8 *PinNumberInBank)
Get the Bank number and the Pin number in the Bank, for the given PinNumber in the GPIO device.
PinNumber is the Pin number in the GPIO device. BankNumber returns the Bank in which this GPIO pin is present. Valid values are 0 to XGPIOPS_MAX_BANKS - 1. PinNumberInBank returns the Pin Number within the Bank. None. None.
References XGpioPs::PmcGpio, XGPIOPS_FOUR, XGPIOPS_ONE, XGPIOPS_SIX, XGPIOPS_THREE, XGPIOPS_TWO, XGPIOPS_ZERO.
Referenced by XGpioPs_GetDirectionPin, XGpioPs_GetIntrTypePin, XGpioPs_GetOutputEnablePin, XGpioPs_IntrClearPin, XGpioPs_IntrDisablePin, XGpioPs_IntrEnablePin, XGpioPs_IntrGetEnabledPin, XGpioPs_IntrGetStatusPin, XGpioPs_ReadPin, XGpioPs_SetDirectionPin, XGpioPs_SetIntrTypePin, XGpioPs_SetOutputEnablePin, XGpioPs_WritePin.