xhdcp22_tx_dp.h
XHDCP22_TX_H
prevent circular inclusions by using protection macros
XHDCP22_TX_DEFAULT_RX_STATUS_POLLVALUE
This value is the default polling interval defined in milliseconds.
The polling interval defines the amount of time to wait between successive reads of the RxStatus register.
Referenced by XHdcp22Tx_Dp_CfgInitialize.
XHDCP22_TX_MAX_MESSAGE_SIZE
Needed storage to transmit/receive messages to the HDCP2.2 receiver This includes 1 extra byte for the DDC address used.
XHDCP22_TX_REVOCATION_LIST_MAX_DEVICES
Needed storage for the Device IDs in the revocation list.
Referenced by XHdcp22Tx_Dp_LoadRevocationTable.
XHDCP22_TX_MAX_STORED_PAIRINGINFO
The list of maximum pairing info items to store.
XHDCP22_TX_LOG_BUFFER_SIZE
The size of the log buffer.
Referenced by XHdcp22Tx_Dp_LogRd, XHdcp22Tx_Dp_LogWr.
XHDCP22_TX_DP_HDCPPORT_R_TX_OFFSET
XHDCP22_TX_DP_HDCPPORT_R_TX_SIZE
XHDCP22_TX_DP_HDCPPORT_TX_CAPS_OFFSET
XHDCP22_TX_DP_HDCPPORT_TX_CAPS_SIZE
XHDCP22_TX_DP_HDCPPORT_CERT_RX_OFFSET
XHDCP22_TX_DP_HDCPPORT_CERT_RX_SIZE
XHDCP22_TX_DP_HDCPPORT_R_RX_OFFSET
XHDCP22_TX_DP_HDCPPORT_R_RX_SIZE
XHDCP22_TX_DP_HDCPPORT_RX_CAPS_OFFSET
XHDCP22_TX_DP_HDCPPORT_RX_CAPS_SIZE
XHDCP22_TX_DP_HDCPPORT_E_KPUB_KM_OFFSET
XHDCP22_TX_DP_HDCPPORT_E_KPUB_KM_SIZE
XHDCP22_TX_DP_HDCPPORT_E_KH_KM_OFFSET
XHDCP22_TX_DP_HDCPPORT_E_KH_KM_SIZE
XHDCP22_TX_DP_HDCPPORT_M_OFFSET
XHDCP22_TX_DP_HDCPPORT_M_SIZE
XHDCP22_TX_DP_HDCPPORT_H_PRIME_OFFSET
XHDCP22_TX_DP_HDCPPORT_H_PRIME_SIZE
XHDCP22_TX_DP_HDCPPORT_E_KH_KM_PAIRING_OFFSET
XHDCP22_TX_DP_HDCPPORT_E_KH_KM_PAIRING_SIZE
XHDCP22_TX_DP_HDCPPORT_R_N_OFFSET
XHDCP22_TX_DP_HDCPPORT_R_N_SIZE
XHDCP22_TX_DP_HDCPPORT_L_PRIME_OFFSET
XHDCP22_TX_DP_HDCPPORT_L_PRIME_SIZE
XHDCP22_TX_DP_HDCPPORT_E_DKEY_KS_OFFSET
XHDCP22_TX_DP_HDCPPORT_E_DKEY_KS_SIZE
XHDCP22_TX_DP_HDCPPORT_R_IV_OFFSET
XHDCP22_TX_DP_HDCPPORT_R_IV_SIZE
XHDCP22_TX_DP_HDCPPORT_RX_INFO_OFFSET
XHDCP22_TX_DP_HDCPPORT_RX_INFO_SIZE
XHDCP22_TX_DP_HDCPPORT_SEQ_NUM_V_OFFSET
XHDCP22_TX_DP_HDCPPORT_SEQ_NUM_V_SIZE
XHDCP22_TX_DP_HDCPPORT_V_PRIME_OFFSET
XHDCP22_TX_DP_HDCPPORT_V_PRIME_SIZE
XHDCP22_TX_DP_HDCPPORT_RCVR_ID_LST_OFFSET
XHDCP22_TX_DP_HDCPPORT_RCVR_ID_LST_MAX_SIZE
XHDCP22_TX_DP_HDCPPORT_V_OFFSET
XHDCP22_TX_DP_HDCPPORT_V_SIZE
XHDCP22_TX_DP_HDCPPORT_SEQ_NUM_M_OFFSET
XHDCP22_TX_DP_HDCPPORT_SEQ_NUM_M_SIZE
XHDCP22_TX_DP_HDCPPORT_K_OFFSET
XHDCP22_TX_DP_HDCPPORT_K_SIZE
XHDCP22_TX_DP_HDCPPORT_STREAM_ID_TYPE_OFFSET
XHDCP22_TX_DP_HDCPPORT_STREAM_ID_TYPE_SIZE
XHDCP22_TX_DP_HDCPPORT_M_PRIME_OFFSET
XHDCP22_TX_DP_HDCPPORT_M_PRIME_SIZE
XHDCP22_TX_DP_HDCPPORT_RX_STATUS_OFFSET
XHDCP22_TX_DP_HDCPPORT_RX_STATUS_SIZE
XHDCP22_TX_DP_HDCPPORT_TYPE_VALUE_OFFSET
XHDCP22_TX_DP_HDCPPORT_TYPE_VALUE_SIZE
XHdcp22_Tx_Dp_HandlerType
XHdcp22_Tx_Dp_StateType
No Rx Attached.
XHdcp22_Tx_Dp_AuthenticationType
A HDCP2 compatible receiver is not found.
XHdcp22_Tx_Dp_ContentStreamType
Type 0 Content Stream.
Stream may be transmitted to all HDCP devices.
XHdcp22_Tx_Dp_LogEvt
Log Event None.
XHdcp22_Tx_Dp_Protocol
Display Port protocol.
XHdcp22_Tx_Dp_Mode
Module acts as a HDCP 2.2 transmitter.
XHdcp22_Tx_Dp_TopologyField
XHdcp22_Rx_Dp_Status
typedef void(* XHdcp22_Tx_Dp_Callback)(void *HandlerRef))(void *CallbackRef)
Callback type for status.
Callback type used for pointer to single input function. CallbackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. None. None.
typedef int(* XHdcp22_Tx_DdcHandler)(u8 DeviceAddress, u16 ByteCount, u8 *BufferPtr, u8 Stop, void *RefPtr))(u8 DeviceAddress, u16 ByteCount, u8 *BufferPtr, u8 Stop, void *RefPtr)
Callback type used for calling DDC read and write functions.
DeviceAddress is the (i2c) device address of the HDCP port. ByteCount is the amount of data bytes in the buffer to read or write. BufferPtr is a pointer to a buffer that is used for reading or writing. Stop is a flag to control if a stop token is set or not. RefPtr is a callback reference passed in by the upper layer when setting the DDC reading and writing functions, and passed back to the upper layer when the callback is invoked. XST_SUCCESS The read action was successful.XST_FAILURE The read action failed. None.
typedef u32(* Xhdcp22_Tx_Dp_RdWrHandler)(void *HandlerRef, u32 offset, u8 *buf, u32 size))(void *HandlerRef, u32 offset, u8 *buf, u32 size)
Type for pointer to four input function with a return value.
XHdcp22_Tx_Dp_Config * XHdcp22Tx_Dp_LookupConfig(UINTPTR BaseAddress)
This function returns a reference to an XHdcp22_Tx_Dp_Config structure based on the core id, DeviceId.
The return value will refer to an entry in the device configuration table defined in the xhdcp22_tx_g.c file. DeviceId is the unique core ID of the HDCP2.2 TX core for the lookup operation. XHdcp22Tx_Dp_LookupConfig returns a reference to a config record in the configuration table (in xhdcp22_tx_g.c) corresponding to DeviceId, or NULL if no match is found. None.
int XHdcp22Tx_Dp_CfgInitialize(XHdcp22_Tx_Dp *InstancePtr, XHdcp22_Tx_Dp_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the HDCP22 TX core.
This function must be called prior to using the HDCP TX core. Initialization of the HDCP TX includes setting up the instance data and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. CfgPtr points to the configuration structure associated with the HDCP TX core. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS Initialization was successful.XST_FAILURE Initialization of the internal timer failed or there was a HDCP TX PIO ID mismatch. None.
References XHdcp22_Tx_Dp::AuthenticatedCallback, XHdcp22_Tx_Dp_Info::AuthenticationStatus, XHdcp22_Tx_Dp_Config::BaseAddress, XHdcp22_Tx_Dp::Config, XHdcp22_Tx_Dp_Info::ContentStreamType, XHdcp22_Tx_Dp_Info::CurrentState, XHdcp22_Tx_Dp::DdcRead, XHdcp22_Tx_Dp::DdcWrite, XHdcp22_Tx_Dp::DownstreamTopologyAvailableCallback, XHdcp22_Tx_Dp::Info, XHdcp22_Tx_Dp_Timer::InitialTicks, XHdcp22_Tx_Dp::IsAuthenticatedCallbackSet, XHdcp22_Tx_Dp_Info::IsContentStreamTypeSet, XHdcp22_Tx_Dp::IsDdcReadSet, XHdcp22_Tx_Dp::IsDdcWriteSet, XHdcp22_Tx_Dp::IsDownstreamTopologyAvailableCallbackSet, XHdcp22_Tx_Dp_Info::IsEnabled, XHdcp22_Tx_Dp::IsReady, XHdcp22_Tx_Dp_Info::IsReceiverHDCP2Capable, XHdcp22_Tx_Dp_Info::IsRevocationListValid, XHdcp22_Tx_Dp_Info::IsTopologyAvailable, XHdcp22_Tx_Dp::IsUnauthenticatedCallbackSet, XHdcp22_Tx_Dp_Info::MsgAvailable, XHdcp22_Tx_Dp_Info::PollingValue, XHdcp22_Tx_Dp_Info::Protocol, XHdcp22_Tx_Dp_Info::PrvState, XHdcp22_Tx_Dp_Timer::ReasonId, XHdcp22_Tx_Dp_Info::ReceivedFirstSeqNum_V, XHdcp22_Tx_Dp::RevocationList, XHdcp22_Tx_Dp_Info::StateContext, XHdcp22_Tx_Dp::Timer, XHdcp22_Tx_Dp_Timer::TimerExpired, XHdcp22_Tx_Dp::UnauthenticatedCallback, XHDCP22_STREAMTYPE_0, XHDCP22_TX_DEFAULT_RX_STATUS_POLLVALUE, XHDCP22_TX_HDMI, XHDCP22_TX_STATE_A0, XHDCP22_TX_STATE_A1, XHDCP22_TX_STATE_A1_1, XHDCP22_TX_STATE_A1_NSK0, XHDCP22_TX_STATE_A1_NSK1, XHDCP22_TX_STATE_A1_SK0, XHDCP22_TX_STATE_A2, XHDCP22_TX_STATE_A2_1, XHDCP22_TX_STATE_A3, XHDCP22_TX_STATE_A4, XHDCP22_TX_STATE_A5, XHDCP22_TX_STATE_A6_A7_A8, XHDCP22_TX_STATE_A9, XHDCP22_TX_STATE_H0, XHDCP22_TX_TS_UNDEFINED, XHDCP22_TX_UNAUTHENTICATED, XHdcp22Tx_Dp_ClearPairingInfo, XHdcp22Tx_Dp_LogReset.
int XHdcp22Tx_Dp_Reset(XHdcp22_Tx_Dp *InstancePtr)
This function resets the state machine.
InstancePtr is a pointer to the XHdcp22Tx core instance. XST_SUCCESS None.
References XHdcp22_Tx_Dp_Info::AuthenticationStatus, XHdcp22_Tx_Dp_Info::AuthRequestCnt, XHdcp22_Tx_Dp::Cipher, XHdcp22_Tx_Dp_Info::CurrentState, XHdcp22_Tx_Dp::Info, XHdcp22_Tx_Dp_Info::IsTopologyAvailable, XHdcp22_Tx_Dp::IsUnauthenticatedCallbackSet, XHdcp22_Tx_Dp_Info::PrvState, XHdcp22_Tx_Dp_Info::ReauthRequestCnt, XHdcp22_Tx_Dp::Timer, XHdcp22_Tx_Dp_Timer::TmrCtr, XHdcp22_Tx_Dp::UnauthenticatedCallback, XHDCP22_TX_AUTHENTICATED, XHDCP22_TX_LOG_EVT_RESET, XHDCP22_TX_STATE_H0, XHDCP22_TX_TIMER_CNTR_0, XHDCP22_TX_UNAUTHENTICATED, XHdcp22Tx_Dp_DisableEncryption, XHdcp22Tx_Dp_LogWr.
int XHdcp22Tx_Dp_ClearPairingInfo(XHdcp22_Tx_Dp *InstancePtr)
This function clear the global pairing info structure, so every HDCP2.2 receiver will have to go through the 'no stored km' sequence to authenticate.
InstancePtr is a pointer to the XHdcp22Tx core instance. XST_SUCCESS None.
References XHdcp22_Tx_Dp::Info.
Referenced by XHdcp22Tx_Dp_CfgInitialize.
int XHdcp22Tx_Dp_Authenticate(XHdcp22_Tx_Dp *InstancePtr)
This function is a called to start authentication.
InstancePtr is a pointer to the XHdcp22Tx core instance. XST_SUCCESS if authenticated is started successfully.XST_FAIL if the state machine is disabled. None.
References XHdcp22_Tx_Dp_Info::AuthenticationStatus, XHdcp22_Tx_Dp_Info::CurrentState, XHdcp22_Tx_Dp::Info, XHdcp22_Tx_Dp_Info::IsContentStreamTypeSet, XHdcp22_Tx_Dp_Info::IsEnabled, XHdcp22_Tx_Dp_Info::IsReceiverHDCP2Capable, XHdcp22_Tx_Dp_Info::IsTopologyAvailable, XHdcp22_Tx_Dp_Info::PrvState, XHDCP22_TX_AUTHENTICATION_BUSY, XHDCP22_TX_STATE_H0, XHdcp22Tx_Dp_IsRepeater.
int XHdcp22Tx_Dp_Poll(XHdcp22_Tx_Dp *InstancePtr)
This function is a executed every time to trigger the state machine.
The user of HDCP22 TX is responsible to call this function on a regular base. InstancePtr is a pointer to the XHdcp22Tx core instance. Enumerated authentication status defined in XHdcp22_Tx_Dp_AuthenticationType. None.
References XHdcp22_Tx_Dp_Info::AuthenticationStatus, XHdcp22_Tx_Dp_Info::CurrentState, XHdcp22_Tx_Dp::Info, XHdcp22_Tx_Dp_Info::IsEnabled, XHdcp22_Tx_Dp_Info::PrvState, XHDCP22_TX_AUTHENTICATION_BUSY, XHDCP22_TX_LOG_EVT_POLL_RESULT, XHdcp22_Tx_StateTable, XHdcp22Tx_Dp_LogWr.
int XHdcp22Tx_Dp_Enable(XHdcp22_Tx_Dp *InstancePtr)
This function enables the state machine and acts as a resume.
InstancePtr is a pointer to the XHdcp22Tx core instance. XST_SUCCESS None.
References XHdcp22_Tx_Dp::Cipher, XHdcp22_Tx_Dp::Info, XHdcp22_Tx_Dp_Info::IsEnabled, XHdcp22_Tx_Dp::Timer, XHdcp22_Tx_Dp_Timer::TmrCtr, XHDCP22_TX_LOG_EVT_ENABLED, XHDCP22_TX_TIMER_CNTR_0, XHdcp22Tx_Dp_LogWr.
int XHdcp22Tx_Dp_Disable(XHdcp22_Tx_Dp *InstancePtr)
This function disables the state machine and acts as a pause.
InstancePtr is a pointer to the XHdcp22Tx core instance. XST_SUCCESS. None.
References XHdcp22_Tx_Dp::Cipher, XHdcp22_Tx_Dp::Info, XHdcp22_Tx_Dp_Info::IsEnabled, XHDCP22_TX_LOG_EVT_ENABLED, XHdcp22Tx_Dp_LogWr.
int XHdcp22Tx_Dp_EnableEncryption(XHdcp22_Tx_Dp *InstancePtr)
This function enables HDMI stream encryption by enabling the cipher.
InstancePtr is a pointer to the XHdcp22Tx core instance. - XST_SUCCESS if authenticated is started successfully. XST_FAIL if the state machine is disabled. None.
References XHdcp22_Tx_Dp::Cipher, XHDCP22_TX_LOG_EVT_ENCR_ENABLED, XHdcp22Tx_Dp_IsAuthenticated, XHdcp22Tx_Dp_LogWr.
int XHdcp22Tx_Dp_DisableEncryption(XHdcp22_Tx_Dp *InstancePtr)
This function disables HDMI stream encryption by disabling the cipher.
InstancePtr is a pointer to the XHdcp22Tx core instance. XST_SUCCESS. None.
References XHdcp22_Tx_Dp::Cipher, XHDCP22_TX_LOG_EVT_ENCR_ENABLED, XHdcp22Tx_Dp_LogWr.
Referenced by XHdcp22Tx_Dp_Reset.
void XHdcp22Tx_Dp_EnableBlank(XHdcp22_Tx_Dp *InstancePtr)
This function enables the blank output for the cipher.
InstancePtr is a pointer to the XHdcp22Tx core instance. None.
References XHdcp22_Tx_Dp::Cipher.
void XHdcp22Tx_Dp_DisableBlank(XHdcp22_Tx_Dp *InstancePtr)
This function disables the blank output for the cipher.
InstancePtr is a pointer to the XHdcp22Tx core instance. None.
References XHdcp22_Tx_Dp::Cipher.
u8 XHdcp22Tx_Dp_IsEnabled(XHdcp22_Tx_Dp *InstancePtr)
This function returns the current enabled state.
InstancePtr is a pointer to the XHdcp22Tx core instance. TRUE if enabled otherwise FALSE. None.
References XHdcp22_Tx_Dp::Info, XHdcp22_Tx_Dp_Info::IsEnabled.
Referenced by XHdcp22Tx_Dp_Info.
u8 XHdcp22Tx_Dp_IsEncryptionEnabled(XHdcp22_Tx_Dp *InstancePtr)
This function returns the current encryption enabled state.
InstancePtr is a pointer to the XHdcp22Tx core instance. TRUE if encryption is enabled otherwise FALSE. None.
References XHdcp22_Tx_Dp::Cipher.
Referenced by XHdcp22Tx_Dp_Info.
u8 XHdcp22Tx_Dp_IsInProgress(XHdcp22_Tx_Dp *InstancePtr)
This function returns the current progress state.
InstancePtr is a pointer to the XHdcp22Tx core instance. TRUE if authentication is in progress otherwise FALSE. None.
References XHdcp22_Tx_Dp_Info::AuthenticationStatus, XHdcp22_Tx_Dp::Info, XHDCP22_TX_UNAUTHENTICATED.
u8 XHdcp22Tx_Dp_IsAuthenticated(XHdcp22_Tx_Dp *InstancePtr)
This function returns the current authenticated state.
InstancePtr is a pointer to the XHdcp22Tx core instance. TRUE if authenticated otherwise FALSE. None.
References XHdcp22_Tx_Dp_Info::AuthenticationStatus, XHdcp22_Tx_Dp::Info, XHDCP22_TX_AUTHENTICATED.
Referenced by XHdcp22Tx_Dp_EnableEncryption.
u8 XHdcp22Tx_Dp_IsDwnstrmCapable(XHdcp22_Tx_Dp *InstancePtr)
This function checks if the downstream device HDCP2Version register is set.
InstancePtr is a pointer to the XHdcp22Tx core instance. - TRUE if downstream device is HDCP 2.2 capable. FALSE if downstream device is not HDCP 2.2 capable. None.
References XHdcp22_Tx_Dp::Config, XHdcp22_Tx_Dp::DdcHandlerRef, XHdcp22_Tx_Dp::DdcRead, XHdcp22_Tx_Dp::DdcWrite, XHdcp22_Tx_Dp::IsReceiverHDCP2Capable, XHdcp22_Tx_Dp_Config::Protocol, XHdcp22_Tx_Dp::TxDpAuxReadCallback, XHdcp22_Tx_Dp::TxDpAuxReadCallbackRef, XHDCP22_TX_DDC_BASE_ADDRESS, XHDCP22_TX_DP, XHDCP22_TX_HDCPPORT_VERSION_OFFSET.
u32 XHdcp22Tx_Dp_GetVersion(XHdcp22_Tx_Dp *InstancePtr)
This function reads the version.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. Returns the version register of the cipher. None.
References XHdcp22_Tx_Dp::Cipher.
int XHdcp22Tx_Dp_SetCallback(XHdcp22_Tx_Dp *InstancePtr, XHdcp22_Tx_Dp_HandlerType HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs callback functions for the given HandlerType:
HandlerType Callback Function Type ------------------------- --------------------------- (XHDCP22_TX_HANDLER_DDC_WRITE) DdcWrite (XHDCP22_TX_HANDLER_DDC_READ) DdcRead (XHDCP22_TX_HANDLER_AUTHENTICATED) AuthenticatedCallback (XHDCP22_TX_HANDLER_UNAUTHENTICATED) UnauthenticatedCallback (XHDCP22_TX_HANDLER_DOWNSTREAM_TOPOLOGY_AVAILABLE) DownstreamTopologyAvailableCallback InstancePtr is a pointer to the HDMI RX core instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XHdcp22_Tx_Dp::AuthenticatedCallback, XHdcp22_Tx_Dp::DdcHandlerRef, XHdcp22_Tx_Dp::DdcRead, XHdcp22_Tx_Dp::DdcWrite, XHdcp22_Tx_Dp::DownstreamTopologyAvailableCallback, XHdcp22_Tx_Dp::IsAuthenticatedCallbackSet, XHdcp22_Tx_Dp::IsDdcReadSet, XHdcp22_Tx_Dp::IsDdcWriteSet, XHdcp22_Tx_Dp::IsDownstreamTopologyAvailableCallbackSet, XHdcp22_Tx_Dp::IsTxDpAuxReadCallbackSet, XHdcp22_Tx_Dp::IsTxDpAuxWriteCallbackSet, XHdcp22_Tx_Dp::IsUnauthenticatedCallbackSet, XHdcp22_Tx_Dp::TxDpAuxReadCallback, XHdcp22_Tx_Dp::TxDpAuxReadCallbackRef, XHdcp22_Tx_Dp::TxDpAuxWriteCallback, XHdcp22_Tx_Dp::TxDpAuxWriteCallbackRef, XHdcp22_Tx_Dp::UnauthenticatedCallback, XHDCP22_TX_HANDLER_DP_AUX_READ, XHDCP22_TX_HANDLER_DP_AUX_WRITE.
XTmrCtr * XHdcp22Tx_Dp_GetTimer(XHdcp22_Tx_Dp *InstancePtr)
This function returns the pointer to the internal timer control instance needed for connecting the timer interrupt to an interrupt controller.
InstancePtr is a pointer to the XHdcp22Tx core instance. A pointer to the internal timer control instance. None.
References XHdcp22_Tx_Dp::Timer, XHdcp22_Tx_Dp_Timer::TmrCtr.
void XHdcp22Tx_Dp_LogReset(XHdcp22_Tx_Dp *InstancePtr, u8 Verbose)
This function clears the log pointers.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. Verbose allows to add debug logging. None.
References XHdcp22_Tx_Dp_Log::Head, XHdcp22_Tx_Dp::Log, XHdcp22_Tx_Dp_Log::Tail, XHdcp22_Tx_Dp::Timer, XHdcp22_Tx_Dp_Timer::TmrCtr, XHdcp22_Tx_Dp_Log::Verbose, XHDCP22_TX_TIMER_CNTR_1.
Referenced by XHdcp22Tx_Dp_CfgInitialize.
void XHdcp22Tx_Dp_LogWr(XHdcp22_Tx_Dp *InstancePtr, XHdcp22_Tx_Dp_LogEvt Evt, u16 Data)
This function writes HDCP TX logs into buffer.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. Evt specifies an action to be carried out. Please refer XHdcp22_Tx_Dp_LogEvt enum in xhdcp22_tx_dp.h. Data specifies the information that gets written into log buffer. None.
References XHdcp22_Tx_Dp_LogItem::Data, XHdcp22_Tx_Dp_Log::Head, XHdcp22_Tx_Dp::Log, XHdcp22_Tx_Dp_LogItem::LogEvent, XHdcp22_Tx_Dp_Log::LogItems, XHdcp22_Tx_Dp_Log::Tail, XHdcp22_Tx_Dp_LogItem::TimeStamp, XHdcp22_Tx_Dp_Log::Verbose, XHDCP22_TX_LOG_BUFFER_SIZE, XHDCP22_TX_LOG_EVT_DBG, XHDCP22_TX_LOG_INVALID, XHdcp22Tx_Dp_LogGetTimeUSecs.
Referenced by XHdcp22Tx_Dp_Disable, XHdcp22Tx_Dp_DisableEncryption, XHdcp22Tx_Dp_Enable, XHdcp22Tx_Dp_EnableEncryption, XHdcp22Tx_Dp_Poll, XHdcp22Tx_Dp_Reset.
XHdcp22_Tx_Dp_LogItem * XHdcp22Tx_Dp_LogRd(XHdcp22_Tx_Dp *InstancePtr)
This function provides the log information from the log buffer.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. Content of log buffer if log pointers are not equal.Otherwise Zero. None.
References XHdcp22_Tx_Dp_LogItem::Data, XHdcp22_Tx_Dp_Log::Head, XHdcp22_Tx_Dp::Log, XHdcp22_Tx_Dp_LogItem::LogEvent, XHdcp22_Tx_Dp_Log::LogItems, XHdcp22_Tx_Dp_Log::Tail, XHdcp22_Tx_Dp_LogItem::TimeStamp, XHDCP22_TX_LOG_BUFFER_SIZE, XHDCP22_TX_LOG_EVT_NONE.
Referenced by XHdcp22Tx_Dp_LogDisplay.
void XHdcp22Tx_Dp_LogDisplay(XHdcp22_Tx_Dp *InstancePtr)
This function prints the content of log buffer.
InstancePtr is a pointer to the HDCP22 TX core instance. None.
References XHdcp22_Tx_Dp_LogItem::Data, XHdcp22_Tx_Dp_LogItem::LogEvent, XHdcp22_Tx_Dp_LogItem::TimeStamp, XHDCP22_TX_AKE_NO_STORED_KM, XHDCP22_TX_AUTHENTICATED, XHDCP22_TX_AUTHENTICATION_BUSY, XHDCP22_TX_CASE_TO_STR_PRE, XHDCP22_TX_INCOMPATIBLE_RX, XHDCP22_TX_LOG_EVT_DBG, XHDCP22_TX_LOG_EVT_ENABLED, XHDCP22_TX_LOG_EVT_ENCR_ENABLED, XHDCP22_TX_LOG_EVT_LCCHK_COUNT, XHDCP22_TX_LOG_EVT_NONE, XHDCP22_TX_LOG_EVT_POLL_RESULT, XHDCP22_TX_LOG_EVT_RESET, XHDCP22_TX_LOG_EVT_STATE, XHDCP22_TX_LOG_EVT_STRMMNGCHK_COUNT, XHDCP22_TX_LOG_EVT_TEST_ERROR, XHDCP22_TX_LOG_EVT_USER, XHDCP22_TX_MSG_UNDEFINED, XHDCP22_TX_REAUTHENTICATE_REQUESTED, XHDCP22_TX_SKE_SEND_EKS, XHDCP22_TX_UNAUTHENTICATED, XHdcp22Tx_Dp_LogRd.
u32 XHdcp22Tx_Dp_LogGetTimeUSecs(XHdcp22_Tx_Dp *InstancePtr)
This function returns the time expired since a log reset was called.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. The expired logging time in useconds. None.
References XHdcp22_Tx_Dp::Timer, XHdcp22_Tx_Dp_Timer::TmrCtr, XHDCP22_TX_TIMER_CNTR_1.
Referenced by XHdcp22Tx_Dp_LogWr.
void XHdcp22Tx_Dp_SetMessagePollingValue(XHdcp22_Tx_Dp *InstancePtr, u32 PollingValue)
This function can be used to change the polling value.
The polling value is the amount of time in milliseconds to wait between successive reads of the RxStatus register. The RxStatus register is polled to determine when a message is available for reading during authentication or during the link integrity check phase to determine when to issue re-authentication. The polling value needs to be at most 20ms to account for the locality check. InstancePtr is a pointer to the XHdcp22Tx core instance. PollingValue is the polling interval defined in milliseconds 0 : Always Poll1 : Poll after 1ms2 : Poll after 2ms3 : Poll after 3ms etc... None.
References XHdcp22_Tx_Dp::Info, XHdcp22_Tx_Dp_Info::PollingValue.
void XHdcp22Tx_Dp_Info(XHdcp22_Tx_Dp *InstancePtr)
This function prints the state machine information.
InstancePtr is a pointer to the HDCP22 TX core instance. None.
References XHdcp22_Tx_Dp_Info::AuthenticationStatus, XHdcp22_Tx_Dp_Info::AuthRequestCnt, XHdcp22_Tx_Dp_Info::ContentStreamType, XHdcp22_Tx_Dp_Topology::Depth, XHdcp22_Tx_Dp_Topology::DeviceCnt, XHdcp22_Tx_Dp_Topology::Hdcp1DeviceDownstream, XHdcp22_Tx_Dp_Topology::Hdcp2LegacyDeviceDownstream, XHdcp22_Tx_Dp::Info, XHdcp22_Tx_Dp_Topology::MaxCascadeExceeded, XHdcp22_Tx_Dp_Topology::MaxDevsExceeded, XHdcp22_Tx_Dp_Info::PollingValue, XHdcp22_Tx_Dp_Info::ReauthRequestCnt, XHdcp22_Tx_Dp::Topology, XHDCP22_TX_AUTHENTICATED, XHDCP22_TX_AUTHENTICATION_BUSY, XHDCP22_TX_DEVICE_IS_REVOKED, XHDCP22_TX_INCOMPATIBLE_RX, XHDCP22_TX_NO_SRM_LOADED, XHDCP22_TX_REAUTHENTICATE_REQUESTED, XHDCP22_TX_UNAUTHENTICATED, XHdcp22Tx_Dp_IsEnabled, XHdcp22Tx_Dp_IsEncryptionEnabled, XHdcp22Tx_Dp_IsRepeater.
void XHdcp22Tx_Dp_LoadLc128(XHdcp22_Tx_Dp *InstancePtr, const u8 *Lc128Ptr)
This function is used to load the Lc128 value by copying the contents of the array referenced by Lc128Ptr into the cipher.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. Lc128Ptr is a pointer to an array. None.
References XHdcp22_Tx_Dp::Cipher, XHDCP22_TX_LC128_SIZE.
int XHdcp22Tx_Dp_LoadRevocationTable(XHdcp22_Tx_Dp *InstancePtr, const u8 *SrmPtr)
This function is used to load the system renewability messages (SRMs) which carries the Receiver ID revocation list.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. SrmPtr is a pointer to an array. XST_SUCCESS if loaded SRM successfully.XST_FAILURE if SRM signature verification failed. None.
References XHdcp22_Tx_Dp::Info, XHdcp22_Tx_Dp_Info::IsRevocationListValid, XHDCP22_TX_KPUB_DCP_LLC_E_SIZE, XHDCP22_TX_KPUB_DCP_LLC_N_SIZE, XHDCP22_TX_REVOCATION_LIST_MAX_DEVICES, XHDCP22_TX_SRM_RCVID_SIZE, XHdcp22Tx_Dp_GetRevocationReceiverIdList, XHdcp22Tx_VerifySRM.
XHdcp22_Tx_Dp_RevocationList * XHdcp22Tx_Dp_GetRevocationReceiverIdList(XHdcp22_Tx_Dp *InstancePtr)
This function returns a pointer to the Revocation Receiver ID list.
InstancePtr is a pointer to the XHdcp22_Tx_Dp instance. Pointer to the XHdcp22_Tx_Dp_RevocationList instance.
References XHdcp22_Tx_Dp::RevocationList.
Referenced by XHdcp22Tx_Dp_IsDeviceRevoked, XHdcp22Tx_Dp_LoadRevocationTable, XHdcp22Tx_Dp_RevokeReceiverId.
u8 XHdcp22Tx_Dp_IsDeviceRevoked(XHdcp22_Tx_Dp *InstancePtr, u8 *RecvIdPtr)
This function searches for the specified ReceiverID in the revocation list.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. RecvIdPtr is a pointer to the ReceiverID to lookup TRUE if Receiver ID was found in the revocation listFALSE if Receiver ID was not found in the revocation list None.
References XHDCP22_TX_SRM_RCVID_SIZE, XHdcp22Tx_Dp_GetRevocationReceiverIdList.
Referenced by XHdcp22Tx_Dp_RevokeReceiverId.
void XHdcp22Tx_Dp_RevokeReceiverId(XHdcp22_Tx_Dp *InstancePtr, u8 *ReceiverIdPtr)
This function adds a ReceiverID to RevocationList.
InstancePtr is a pointer to the XHdcp22Tx core instance. ReceiverIdPtr is a pointer to a 5-byte receiver Id. Supposed to be called by Upstream Content Control Function
References XHdcp22_Tx_Dp_Info::AuthenticationStatus, XHdcp22_Tx_Dp::Config, XHdcp22_Tx_Dp_Info::CurrentState, XHdcp22_Tx_Dp::Info, XHdcp22_Tx_Dp_Info::IsDeviceRevoked, XHdcp22_Tx_Dp_Info::IsRevocationListValid, XHdcp22_Tx_Dp_Config::Mode, XHDCP22_TX_DEVICE_IS_REVOKED, XHDCP22_TX_SRM_RCVID_SIZE, XHDCP22_TX_STATE_A0, XHDCP22_TX_TRANSMITTER, XHdcp22Tx_Dp_GetRevocationReceiverIdList, XHdcp22Tx_Dp_IsDeviceRevoked.
XHdcp22_Tx_Dp_Topology * XHdcp22Tx_Dp_GetTopology(XHdcp22_Tx_Dp *InstancePtr)
This function returns a pointer to the downstream topology structure.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. A pointer to the XHdcp22_Tx_Dp_Topology structure or NULL when the topology info is invalid. None.
References XHdcp22_Tx_Dp::Info, XHdcp22_Tx_Dp_Info::IsTopologyAvailable, XHdcp22_Tx_Dp::Topology.
u8 * XHdcp22Tx_Dp_GetTopologyReceiverIdList(XHdcp22_Tx_Dp *InstancePtr)
This function returns a pointer to the ReceiverID list in the repeater topology structure.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. A pointer to the ReceiverID list in the topology structure. None.
References XHdcp22_Tx_Dp_Topology::ReceiverId, XHdcp22_Tx_Dp::Topology.
u32 XHdcp22Tx_Dp_GetTopologyField(XHdcp22_Tx_Dp *InstancePtr, XHdcp22_Tx_Dp_TopologyField Field)
This function is used to get various fields inside the topology structure.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. Field indicates what field of the topology structure to get. Value associated to field inside the topology structure. None.
u8 XHdcp22Tx_Dp_IsRepeater(XHdcp22_Tx_Dp *InstancePtr)
This function returns the current repeater mode status.
InstancePtr is a pointer to the XHdcp22_Tx_Dp instance. TRUE if the HDCP 2.2 instance is part of the downstream port of a repeaterFALSE if the HDCP 2.2 instance is a transmitter
References XHdcp22_Tx_Dp::Config, XHdcp22_Tx_Dp_Config::Mode, XHDCP22_TX_TRANSMITTER.
Referenced by XHdcp22Tx_Dp_Authenticate, XHdcp22Tx_Dp_Info.
void XHdcp22Tx_Dp_SetRepeater(XHdcp22_Tx_Dp *InstancePtr, u8 Set)
This function sets the repeater mode status.
InstancePtr is a pointer to the XHdcp22_Tx_Dp instance. Set is TRUE to enable the repeater mode and FALSE to disable.
References XHdcp22_Tx_Dp::Config, XHdcp22_Tx_Dp_Config::Mode, XHDCP22_TX_REPEATER, XHDCP22_TX_TRANSMITTER.
void XHdcp22Tx_Dp_SetContentStreamType(XHdcp22_Tx_Dp *InstancePtr, XHdcp22_Tx_Dp_ContentStreamType StreamType)
This function sets the Content Stream Type.
InstancePtr is a pointer to the XHdcp22_Tx_Dp instance. StreamType specifies the content stream type.
References XHdcp22_Tx_Dp_Info::ContentStreamType, XHdcp22_Tx_Dp::Info, XHdcp22_Tx_Dp_Info::IsContentStreamTypeSet.
void XHdcp22Tx_Dp_timer_attach(XHdcp22_Tx_Dp *InstancePtr, XTmrCtr *TmrCtrPtr)
This function is to attach the HDCP22 timer instance to DP TX subsystem's timer.
For the DP design the timer is being used from the DP TX subsystem. So the HDCP22 timer instance will be attached in DpTxSs initialization. InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. TmrCtrPtr is the DpTx susbsystem's timer instance. For the DP design the timer is being used from the DP TX subsystem. So the HDCP22 timer instance will be attached in DpTxSs initialization.
References XHdcp22_Tx_Dp::Timer, XHdcp22_Tx_Dp_Timer::TmrCtr, XHDCP22_TX_TIMER_CNTR_0, XHDCP22_TX_TIMER_CNTR_1.
void XHdcp22Tx_Dp_SetHdcp22OverProtocol(XHdcp22_Tx_Dp *InstancePtr, XHdcp22_Tx_Dp_Protocol protocol)
This function is to set the protocol (HDMI/DP) over which HDCP22 is happening.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. protocol is the protocol HDMI/DP.
References XHdcp22_Tx_Dp::Config, XHdcp22_Tx_Dp_Config::Protocol.
void XHdcp22Tx_Dp_TimerHandler(void *CallbackRef, u8 TmrCntNumber)
This function handles timer interrupts.
CallbackRef refers to a XHdcp22_Tx_Dp structure TmrCntNumber the number of used timer. For dp design, this will be called form the Tx subsystem's timer handler so it should be a public function.
References XHdcp22_Tx_Dp::Info, XHdcp22_Tx_Dp_Info::IsEnabled, XHdcp22_Tx_Dp::IsReady, XHdcp22_Tx_Dp::Timer, XHdcp22_Tx_Dp_Timer::TimerExpired, XHDCP22_TX_TIMER_CNTR_1.
void XHdcp22Tx_Dp_Handle_Cp_Irq(XHdcp22_Tx_Dp *InstancePtr)
This function is to read the RX_STATUS when a cp_irq received.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. none
References XHdcp22_Tx_Dp_Info::Dp_RxStatus, XHdcp22_Tx_Dp::Info, XHdcp22_Tx_Dp::TxDpAuxReadCallback, XHdcp22_Tx_Dp::TxDpAuxReadCallbackRef.
int XHdcp22Tx_Dp_SetLaneCount(XHdcp22_Tx_Dp *InstancePtr, u8 LaneCount)
This function set the lane count of an hdcp22 interface.
InstancePtr is the transmitter instance. LaneCount is the number of lanes of the interface. XST_SUCCESS if successful. None.
References XHdcp22_Tx_Dp::Cipher.
int XHdcp22Tx_Dp_SetMst(XHdcp22_Tx_Dp *InstancePtr, u8 Mode)
This function set the MST mode of an hdcp22 interface.
InstancePtr is the transmitter instance. Mode enables the MST configuration of the interface. XST_SUCCESS if successful. None.
References XHdcp22_Tx_Dp::Cipher.