xhdcp22_tx_dp.c
XHDCP22_TX_INVALID_RXSTATUS
RxStatus value used to force re-authentication.
XHDCP22_TX_CASE_TO_STR_PRE
Case replacement to copy a case Id to a string with a pre-lead.
Referenced by XHdcp22Tx_Dp_LogDisplay.
XHDCP22_TX_DP_LC_SEND_L_PRIME_TIMEOUT
typedef XHdcp22_Tx_Dp_StateType XHdcp22Tx_StateFuncType(XHdcp22_Tx_Dp *InstancePtr)(XHdcp22_Tx_Dp *InstancePtr)
Pointer to the state handling functions.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. The next state that should be executed. None.
typedef void XHdcp22_Tx_TransitionFuncType(XHdcp22_Tx_Dp *InstancePtr)(XHdcp22_Tx_Dp *InstancePtr)
Pointer to the transition functions going from one state to the next.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. None.
XHdcp22Tx_StateFuncType* const XHdcp22_Tx_StateTable[XHDCP22_TX_NUM_STATES][XHDCP22_TX_NUM_STATES]
This table contains the function pointers for all possible states.
The order of elements must match the XHdcp22_Tx_Dp_StateType enumerator definitions.
Referenced by XHdcp22Tx_Dp_Poll.
XHdcp22_Tx_TransitionFuncType* transition_table[XHDCP22_TX_NUM_STATES][XHDCP22_TX_NUM_STATES][XHDCP22_TX_NUM_STATES][XHDCP22_TX_NUM_STATES]
This table is a matrix that contains the function pointers for functions to execute on state transition.
It is filled dynamically. A NULL value is used if no transition is required.
const u8 XHdcp22_Tx_KpubDcp[XHDCP22_TX_KPUB_DCP_LLC_N_SIZE+XHDCP22_TX_KPUB_DCP_LLC_E_SIZE][XHDCP22_TX_KPUB_DCP_LLC_N_SIZE+XHDCP22_TX_KPUB_DCP_LLC_E_SIZE]
const u8 XHdcp22_Tx_TxCaps[][]
This array contains the capabilities of the HDCP22 TX core, and is transmitted during authentication as part of the AKE_Init message.
static int XHdcp22Tx_InitializeCipher(XHdcp22_Tx_Dp *InstancePtr)
This function is a called to initialize the cipher.
InstancePtr is a pointer to the XHdcp22Tx core instance. XST_SUCCESS if authenticated is started successfully.XST_FAIL if the state machine is disabled. None.
static int XHdcp22Tx_InitializeRng(XHdcp22_Tx_Dp *InstancePtr)
This function is a called to initialize the hardware random generator.
InstancePtr is a pointer to the XHdcp22Tx core instance. XST_SUCCESS if authenticated is started successfully.XST_FAIL if the state machine is disabled. None.
static int XHdcp22Tx_ComputeBaseAddress(UINTPTR BaseAddress, UINTPTR SubcoreOffset, UINTPTR *SubcoreAddressPtr)
This function computes the subcore absolute address on axi-lite interface Subsystem is mapped at an absolute address and all included sub-cores are at pre-defined offset from the subsystem base address.
To access the subcore register map from host CPU an absolute address is required. BaseAddress is the base address of the subsystem instance SubcoreOffset is the offset of the the subcore instance SubcoreAddressPtr is the computed base address of the subcore instance XST_SUCCESS if base address computation is successful and within subsystem address range else XST_FAILURE
static int XHdcp22Tx_StubDdc(u8 DeviceAddress, u16 ByteCount, u8 *BufferPtr, u8 Stop, void *RefPtr)
This function is a dummy called as long as there is no valid ddc handler set.
It always returns an error. DeviceAddress is the DDC (i2c) device address. ByteCount is the number of bytes in the buffer. BufferPtr is the buffer that stores the data to be written or read. Stop is a flag to signal i2c stop condition. RefPtr is the reference pointer for the handler. XST_FAILURE None.
static void XHdcp22Tx_StubCallback(void *RefPtr)
This function is a dummy called as long as there is no valid authenticated handler set.
It always returns an error. RefPtr is the reference pointer for the handler. XST_FAILURE None.
static XHdcp22_Tx_Dp_StateType XHdcp22Tx_StateH0(XHdcp22_Tx_Dp *InstancePtr)
This function is the implementation of the HDCP transmit H0 state.
According protocol this is the reset state that is entered initially. As soon as hot plug is detected and Rx is available, a transition to state h1 is performed. Since hotplug detect is controlled by the user, the next state is always state H1. InstancePtr is a pointer to the XHdcp22Tx core instance. XHDCP22_TX_STATE_H1 None.
static XHdcp22_Tx_Dp_StateType XHdcp22Tx_StateH1(XHdcp22_Tx_Dp *InstancePtr)
This function is the implementation of the HDCP transmit H1 state.
As soon as hot plug is detected and Rx is available, a transition to this state is performed. Hotplug detection if controlled by the user of this core. This means that this state is practically the entry state. InstancePtr is a pointer to the XHDCP22 TX core instance. XHDCP22_TX_STATE_A0 if the attached receiver is HDCP2 capable.XHDCP22_TX_STATE_H1 if the attached receiver is NOT HDCP2 capable. None.
static XHdcp22_Tx_Dp_StateType XHdcp22Tx_StateA0(XHdcp22_Tx_Dp *InstancePtr)
This function is the implementation of the HDCP transmit A0 state.
If content protection not desired, return to H1 state. InstancePtr is a pointer to the XHDCP22 TX core instance. XHDCP22_TX_STATE_H1 if state machine is set to disabled (content protection NOT desired).XHDCP22_TX_STATE_A1 if authentication must start. None.
static XHdcp22_Tx_Dp_StateType XHdcp22Tx_StateA1(XHdcp22_Tx_Dp *InstancePtr)
This function executes the first part of the A1 state of the HDCP2.2 TX protocol.
InstancePtr is a pointer to the XHdcp22Tx core instance. XHDCP22_TX_STATE_A1_1 None.
XHdcp22_Tx_Dp_StateType Xhdcp22Tx_StateA1_1(XHdcp22_Tx_Dp *InstancePtr)
This function executes a part of the A1 state functionality of the HDCP2.2 TX protocol.
It receives the certificate and decides if it should continue to a 'no stored km' or 'stored Km'intermediate state. InstancePtr is a pointer to the XHdcp22Tx core instance. XHDCP22_TX_STATE_A0 on errors.XHDCP22_TX_STATE_A1_1 if busy waiting for the XHDCP22_TX_AKE_SEND_CERT message.XHDCP22_TX_STATE_A1_SK0 for a 'Stored Km' scenario.XHDCP22_TX_STATE_A1_NSK0 for a 'Non Stored Km' scenario. None.
static XHdcp22_Tx_Dp_StateType Xhdcp22Tx_StateA1_Nsk0(XHdcp22_Tx_Dp *InstancePtr)
This function executes a part of the A1 state functionality of the HDCP2.2 TX protocol.
It handles a part of the 'No Stored Km' scenario and receives and verifies H' InstancePtr is a pointer to the XHdcp22Tx core instance. XHDCP22_TX_STATE_A0 on errors.XHDCP22_TX_STATE_A1_NSK0 if busy waiting for the XHDCP22_TX_AKE_SEND_H_PRIME message.XHDCP22_TX_STATE_A1_NSK1 for the next part of the 'Stored Km' scenario. None.
static XHdcp22_Tx_Dp_StateType Xhdcp22Tx_StateA1_Nsk1(XHdcp22_Tx_Dp *InstancePtr)
This function executes a part of the A1 state functionality of the HDCP2.2 TX protocol.
It handles a part of the 'No Stored Km' scenario and receives and stores pairing info. InstancePtr is a pointer to the XHdcp22Tx core instance. XHDCP22_TX_STATE_A0 on errors.XHDCP22_TX_STATE_A1_NSK1 if busy waiting for the XHDCP22_TX_AKE_SEND_PAIRING_INFO message.XHDCP22_TX_STATE_A2 if authentication is done. None.
static XHdcp22_Tx_Dp_StateType Xhdcp22Tx_StateA1_Sk0(XHdcp22_Tx_Dp *InstancePtr)
This function executes a part of the A1 state functionality of the HDCP2.2 TX protocol.
It handles a part of the 'Stored Km' scenario and receives and verifies H'. InstancePtr is a pointer to the XHdcp22Tx core instance. XHDCP22_TX_STATE_A0 on errors.XHDCP22_TX_STATE_A1_SK0 if busy waiting for theXHDCP22_TX_AKE_SEND_H_PRIME message.XHDCP22_TX_STATE_A2 if authentication is done. None.
static XHdcp22_Tx_Dp_StateType XHdcp22Tx_StateA2(XHdcp22_Tx_Dp *InstancePtr)
This function executes the A2 state of the HDCP2.2 TX protocol.
InstancePtr is a pointer to the XHdcp22Tx core instance. The next state to execute. None.
static XHdcp22_Tx_Dp_StateType XHdcp22Tx_StateA2_1(XHdcp22_Tx_Dp *InstancePtr)
This function executes a part of the A2 state functionality of the HDCP2.2 TX protocol.
It receives and verifies L' (locality check). InstancePtr is a pointer to the XHdcp22Tx core instance. XHDCP22_TX_STATE_A2_1 if busy waiting for the XHDCP22_TX_AKE_SEND_L_PRIME message.XHDCP22_TX_STATE_A3 if authentication is done. None.
static XHdcp22_Tx_Dp_StateType XHdcp22Tx_StateA3(XHdcp22_Tx_Dp *InstancePtr)
This function executes the A3 state of the HDCP2.2 TX protocol.
InstancePtr is a pointer to the XHdcp22Tx core instance. The next state to execute. None.
static XHdcp22_Tx_Dp_StateType XHdcp22Tx_StateA4(XHdcp22_Tx_Dp *InstancePtr)
This function executes the A4 state of the HDCP2.2 TX protocol.
InstancePtr is a pointer to the XHdcp22Tx core instance. The next state to execute. None.
static XHdcp22_Tx_Dp_StateType XHdcp22Tx_StateA5(XHdcp22_Tx_Dp *InstancePtr)
This function executes the A5 state of the HDCP2.2 TX protocol.
Before authentication is granted, a 200 ms mandatory wait is added, so the integrating application does not start the cipher premature. InstancePtr is a pointer to the XHdcp22Tx core instance. The next state to execute. None.
static XHdcp22_Tx_Dp_StateType XHdcp22Tx_StateA6_A7_A8(XHdcp22_Tx_Dp *InstancePtr)
This function executes the states A6, A7 and A8 of the HDCP2.2 TX protocol.
Within these states the HDCP2.2 TX receives and verifies the receiver ID list. The HDCP2.2 TX is required to send a response within 2 seconds after the HDCP2.2 repeater has made the receiver ID list available. These states have been grouped in order to guarantee that the HDCP2.2 TX responds as fast as it can. InstancePtr is a pointer to the XHdcp22Tx core instance. The next state to execute. None.
static XHdcp22_Tx_Dp_StateType XHdcp22Tx_StateA6(XHdcp22_Tx_Dp *InstancePtr)
This function executes the A6 state of the HDCP2.2 TX protocol.
InstancePtr is a pointer to the XHdcp22Tx core instance. The next state to execute. None.
static XHdcp22_Tx_Dp_StateType XHdcp22Tx_StateA7(XHdcp22_Tx_Dp *InstancePtr)
This function executes the A7 state of the HDCP2.2 TX protocol.
InstancePtr is a pointer to the XHdcp22Tx core instance. The next state to execute. None.
static XHdcp22_Tx_Dp_StateType XHdcp22Tx_StateA8(XHdcp22_Tx_Dp *InstancePtr)
This function executes the A8 state of the HDCP2.2 TX protocol.
InstancePtr is a pointer to the XHdcp22Tx core instance. The next state to execute. None.
static XHdcp22_Tx_Dp_StateType XHdcp22Tx_StateA9(XHdcp22_Tx_Dp *InstancePtr)
This function executes the first portion of the A9 state of the HDCP2.2 TX protocol.
InstancePtr is a pointer to the XHdcp22Tx core instance. The next state to execute. None.
static XHdcp22_Tx_Dp_StateType XHdcp22Tx_StateA9_1(XHdcp22_Tx_Dp *InstancePtr)
This function executes the second portion of the A9 state of the HDCP2.2 TX protocol.
InstancePtr is a pointer to the XHdcp22Tx core instance. The next state to execute. None.
static void XHdcp22Tx_A1A0(XHdcp22_Tx_Dp *InstancePtr)
This function executes on transition from state A1 or one of its sub states to A0, which means that an error in authentication has occurred.
InstancePtr is a pointer to the XHdcp22Tx core instance. None. None.
static void XHdcp22Tx_A1A2(XHdcp22_Tx_Dp *InstancePtr)
This function executes on transition from state A1_SK0 or A1_NSK1 to A2, which means that state A2 is executed for the first time.
The locality check counter is initialized. Subsequent locality checks are then executed for an extra 1023 times. InstancePtr is a pointer to the XHdcp22Tx core instance. None. None.
static void XHdcp22Tx_A2A0(XHdcp22_Tx_Dp *InstancePtr)
This function executes on transition from state A2 or one of its substates to A0, which means that an error in authentication has occurred.
InstancePtr is a pointer to the XHdcp22Tx core instance. None. None.
static void XHdcp22Tx_A3A0(XHdcp22_Tx_Dp *InstancePtr)
This function executes on transition from state A3 to A0, which means that an error in authentication has occurred.
InstancePtr is a pointer to the XHdcp22Tx core instance. None. None.
static void XHdcp22Tx_A3A4(XHdcp22_Tx_Dp *InstancePtr)
This function executes on transition from state A3 to A4, which means that the Session Key Exchange (SKE) has completed.
InstancePtr is a pointer to the XHdcp22Tx core instance. None. None.
static void XHdcp22Tx_A4A5(XHdcp22_Tx_Dp *InstancePtr)
This function executes on transition from state A4 to A5, which means that an authentication has succeeded and state A5 is executed the first time.
InstancePtr is a pointer to the XHdcp22Tx core instance. None. None.
static void XHdcp22Tx_A6A7A0(XHdcp22_Tx_Dp *InstancePtr)
This function executes on transition from state A6 or A7 to A0, which means that an error in authentication has occurred.
InstancePtr is a pointer to the XHdcp22Tx core instance. None. None.
static void XHdcp22Tx_A9A0(XHdcp22_Tx_Dp *InstancePtr)
This function executes on transition from state A9 to A0, which means that an error in the content stream management has occurred.
InstancePtr is a pointer to the XHdcp22Tx core instance. None. None.
static int XHdcp22Tx_WriteAKEInit(XHdcp22_Tx_Dp *InstancePtr)
This function issues a AKE_Init message.
InstancePtr is a pointer to the XHdcp22Tx core instance. MsgBufferPtr the buffer to use for messaging. XST_SUCCESS if writing succeededXST_FAILURE if failed to write. None.
static int XHdcp22Tx_WriteAKENoStoredKm(XHdcp22_Tx_Dp *InstancePtr, const XHdcp22_Tx_Dp_PairingInfo *PairingInfoPtr, const XHdcp22_Tx_CertRx *CertificatePtr)
This function issues a AKE_No_Stored_km message.
InstancePtr is a pointer to the XHdcp22Tx core instance. MsgBufferPtr the buffer containing the certificate and re-used for sending the message. XST_SUCCESS if writing succeededXST_FAILURE if failed to write None.
static int XHdcp22Tx_WriteAKEStoredKm(XHdcp22_Tx_Dp *InstancePtr, const XHdcp22_Tx_Dp_PairingInfo *PairingInfoPtr)
This function issues a AKE_Stored_km message.
InstancePtr is a pointer to the XHdcp22Tx core instance. MsgBufferPtr the buffer to use for messaging. XST_SUCCESS if writing succeededXST_FAILURE if failed to write None.
static int XHdcp22Tx_WriteLcInit(XHdcp22_Tx_Dp *InstancePtr, const u8 *RnPtr)
This function write a locality check has value.
InstancePtr is a pointer to the XHdcp22Tx core instance. RnPtr is a pointer to the XHdcp22Tx core instance. XST_SUCCESS if writing succeededXST_FAILURE if failed to write None.
static int XHdcp22Tx_WriteSkeSendEks(XHdcp22_Tx_Dp *InstancePtr, const u8 *EdkeyKsPtr, const u8 *RivPtr)
This function sends the session key to the receiver.
InstancePtr is a pointer to the XHdcp22Tx core instance. EdkeyKsPtr is a pointer to the encrypted session key. RivPtr is a pointer to the random IV pair. XST_SUCCESS if writing succeededXST_FAILURE if failed to write None.
static int XHdcp22Tx_WriteTypeValue(XHdcp22_Tx_Dp *InstancePtr)
This function sends the Type Value to the receiver.
InstancePtr is a pointer to the XHdcp22Tx core instance. XST_SUCCESS if writing succeededXST_FAILURE if failed to write None.
static int XHdcp22Tx_WriteRepeaterAuth_Send_Ack(XHdcp22_Tx_Dp *InstancePtr, const u8 *VPtr)
This function sends the Receiver ID List acknowledgement to the repeater.
InstancePtr is a pointer to the XHdcp22Tx core instance. VPtr is a pointer to the least significant 128-bits of V. XST_SUCCESS if writing succeededXST_FAILURE if failed to write None.
static int XHdcp22Tx_WriteRepeaterAuth_Stream_Manage(XHdcp22_Tx_Dp *InstancePtr)
This function sends the Content Stream Type to the repeater.
InstancePtr is a pointer to the XHdcp22Tx core instance. XST_SUCCESS if writing succeededXST_FAILURE if failed to write None.
static int XHdcp22Tx_ReceiveMsg(XHdcp22_Tx_Dp *InstancePtr, u8 MessageId, u32 MessageSize)
This function receives a message send by HDCP22 RX.
InstancePtr is a pointer to the XHdcp22Tx core instance. MessageId the message Id of the expected message. MessageSize the size of the expected message. XST_SUCCESS if the message size and id are as expected.XST_FAILURE if if the message size and id are incorrect. None.
static void XHdcp22Tx_GenerateRtx(XHdcp22_Tx_Dp *InstancePtr, u8 *RtxPtr)
This function returns a pseudo random 64-bit value for Rtx as part of the HDCP22 TX initiation message.
If appropriate it is overwritten with a test vector. InstancePtr is a pointer to the XHdcp22Tx core instance. RtxPtr is a 64-bit random value; None. None.
static void XHdcp22Tx_GenerateKm(XHdcp22_Tx_Dp *InstancePtr, u8 *KmPtr)
This function returns a pseudo random 128-bit value for Km as part of the HDCP22 TX initiation message.
If appropriate it is overwritten with a test vector. InstancePtr is a pointer to the XHdcp22Tx core instance. KmPtr is a pointer to a 128 bits random value. None. None.
static void XHdcp22Tx_GenerateKmMaskingSeed(XHdcp22_Tx_Dp *InstancePtr, u8 *SeedPtr)
This function returns a pseudo random 64-bit value for Rn as part of the locality check.
If appropriate it is overwritten with a test vector. InstancePtr is a pointer to the XHdcp22Tx core instance. KmPtr is a pointer to a 256 bits random seed value. None. None.
static void XHdcp22Tx_GenerateRn(XHdcp22_Tx_Dp *InstancePtr, u8 *RnPtr)
This function returns a pseudo random 64-bit value for Rn as part of the HDCP22 TX locality check.
If appropriate it is overwritten with a test vector. InstancePtr is a pointer to the XHdcp22Tx core instance. RnPtr is a pointer to a 64 bits random value. None. None.
static void XHdcp22Tx_GenerateRiv(XHdcp22_Tx_Dp *InstancePtr, u8 *RivPtr)
This function returns a pseudo random 64-bit value for Riv as part of the HDCP22 TX session key exchange message.
If appropriate it is overwritten with a test vector. InstancePtr is a pointer to the XHdcp22Tx core instance. RivPtr is a 64-bit random value; None. None.
static void XHdcp22Tx_GenerateKs(XHdcp22_Tx_Dp *InstancePtr, u8 *KsPtr)
This function returns a pseudo random 128-bit value for Ks as part of the HDCP22 TX session key exchange message.
If appropriate it is overwritten with a test vector. InstancePtr is a pointer to the XHdcp22Tx core instance. KsPtr is a 128-bit random value; None. None.
static const u8 * XHdcp22Tx_GetKPubDpc(XHdcp22_Tx_Dp *InstancePtr)
This function returns the DCP LLC public key If appropriate it returns a test vector.
InstancePtr is a pointer to the XHdcp22Tx core instance. RivPtr is a 64-bit random value; None. None.
static XHdcp22_Tx_Dp_PairingInfo * XHdcp22Tx_GetPairingInfo(XHdcp22_Tx_Dp *InstancePtr, const u8 *ReceiverId)
This function gets a stored pairing info entry from the storage.
ReceiverId is a pointer to a 5-byte receiver Id. A pointer to the found ReceiverId or NULL if the pairing info wasn't stored yet. None.
static void XHdcp22Tx_InvalidatePairingInfo(XHdcp22_Tx_Dp *InstancePtr, const u8 *ReceiverId)
This function invalidates a pairing info structure.
ReceiverId is a pointer to a 5-byte receiver Id. None. None.
static XHdcp22_Tx_Dp_PairingInfo * XHdcp22Tx_UpdatePairingInfo(XHdcp22_Tx_Dp *InstancePtr, const XHdcp22_Tx_Dp_PairingInfo *PairingInfo, u8 Ready)
This function updates a pairing info entry in the storage.
PairingInfo is a pointer to a pairing info structure. XST_SUCCESS if there was enough roomXST_FAILURE if there was no room for this receiver None.
static int XHdcp22Tx_StartTimer(XHdcp22_Tx_Dp *InstancePtr, u32 TimeOut_mSec, u8 ReasonId)
This function starts the timer needed for checking the HDCP22 Receive status register.
In case the timer is started to receive a message, the MsgAvailable flag is reset. InstancePtr is a pointer to the XHdcp22Tx core instance. TimeOut_mSec is the timeout for the next status update. XST_SUCCESS or XST_FAILURE. None.
static int XHdcp22Tx_WaitForReceiver(XHdcp22_Tx_Dp *InstancePtr, int ExpectedSize, u8 ReadyBit)
This function waits for receiving expected messages from the receiver.
If the timer is not started, it will be started. This has to be used to avoid blocking waits, and allows polling to return to allow the main thread to continue handling other requests. Some receivers require to read status as soon as possible otherwise the receiver may request for a re-authentication so we must poll! InstancePtr is a pointer to the XHdcp22Tx core instance. ExpectedSize indicates the expected message size in bytes. ReadyBit indicates if the repeater ready bit from RxStatus register should be used or the specified ExpectedSize. TRUE Ready bit from RxStatus is used. ExpectedSize will be ignored.FALSE ExpectedSize is used. Ready bit from RxStatus will be ignored. XST_SUCCESS if no problemsXST_FAILURE if the receiver has timed out None.
static u32 XHdcp22Tx_GetTimerCount(XHdcp22_Tx_Dp *InstancePtr)
This function returns the current timer count value of the expiration timer.
register. InstancePtr is a pointer to the XHdcp22Tx core instance. TimeOut_mSec is the timeout for the next status update. XST_SUCCESS if the timer count could be acquired.XST_FAILURE if not. None.
static void XHdcp22Tx_ReadRxStatus(XHdcp22_Tx_Dp *InstancePtr)
This function reads RxStatus from the DDC channel.
If the read is not successful it will default to an RxStatus value of 0xFFFF to initiate re-authentication. InstancePtr is a pointer to the XHdcp22Tx core instance. MsgBufferPtr the buffer to use for messaging. None. None.
static void XHdcp22Tx_HandleAuthenticationFailed(XHdcp22_Tx_Dp *InstancePtr)
This function handles authentication failures.
InstancePtr is a pointer to the XHdcp22Tx core instance. None. None.
static void XHdcp22Tx_HandleReauthenticationRequest(XHdcp22_Tx_Dp *InstancePtr)
This function handles reauthentication requests.
InstancePtr is a pointer to the XHdcp22Tx core instance. None. None.
static u32 XHdcp22Tx_GetTopologyDepth(XHdcp22_Tx_Dp *InstancePtr)
This function returns the DEPTH in the repeater topology structure.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. Repeater topology DEPTH. None.
static u32 XHdcp22Tx_GetTopologyDeviceCnt(XHdcp22_Tx_Dp *InstancePtr)
This function returns the DEVICE_COUNT in the repeater topology structure.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. DEVICE_COUNT in the repeater topology structure. None.
static u32 XHdcp22Tx_GetTopologyMaxDevsExceeded(XHdcp22_Tx_Dp *InstancePtr)
This function returns the MAX_DEVICS_EXCEEDED flag in the repeater topology structure.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. MAX_DEVICS_EXCEEDED flag in the repeater structure. None.
static u32 XHdcp22Tx_GetTopologyMaxCascadeExceeded(XHdcp22_Tx_Dp *InstancePtr)
This function returns the MAX_CASCADE_EXCEEDED flag in the repeater topology structure.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. MAX_CASCADE_EXCEEDED flag in the repeater structure. None.
static u32 XHdcp22Tx_GetTopologyHdcp2LegacyDeviceDownstream(XHdcp22_Tx_Dp *InstancePtr)
This function returns the HDCP2_LEGACY_DEVICE_DOWNSTREAM flag in the repeater topology structure.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. HDCP2_LEGACY_DEVICE_DOWNSTREAM flag in the repeater structure. None.
static u32 XHdcp22Tx_GetTopologyHdcp1DeviceDownstream(XHdcp22_Tx_Dp *InstancePtr)
This function returns the HDCP1_DEVICE_DOWNSTREAM flag in the repeater topology structure.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. HDCP1_DEVICE_DOWNSTREAM flag in the repeater structure. None.
static int XHdcp22Tx_Dp_Write_Dpcd_Msg(XHdcp22_Tx_Dp *InstancePtr)
This function Writes a complete message into the DPCD registers of remote device.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. Size of message written. For DP there are no msg_ids for all the HDCP msgs, But to make less changes in the already existed HDCP22 statmachine which is written for HDMI, Assigned msg_ids for each msg.
static int XHdcp22Tx_Dp_ReadDpRxMsg(XHdcp22_Tx_Dp *InstancePtr, u8 MessageId)
This function reads requested MSG from DP RX.
InstancePtr is a pointer to the XHdcp22Tx core instance. MessageId the message Id of the expected message. XST_SUCCESS if the message size and id are as expected.XST_FAILURE if if the message size and id are incorrect. None.
int XHdcp22Tx_Dp_CfgInitialize(XHdcp22_Tx_Dp *InstancePtr, XHdcp22_Tx_Dp_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the HDCP22 TX core.
This function must be called prior to using the HDCP TX core. Initialization of the HDCP TX includes setting up the instance data and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. CfgPtr points to the configuration structure associated with the HDCP TX core. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS Initialization was successful.XST_FAILURE Initialization of the internal timer failed or there was a HDCP TX PIO ID mismatch. None.
References XHdcp22_Tx_Dp::AuthenticatedCallback, XHdcp22_Tx_Dp_Info::AuthenticationStatus, XHdcp22_Tx_Dp_Config::BaseAddress, XHdcp22_Tx_Dp::Config, XHdcp22_Tx_Dp_Info::ContentStreamType, XHdcp22_Tx_Dp_Info::CurrentState, XHdcp22_Tx_Dp::DdcRead, XHdcp22_Tx_Dp::DdcWrite, XHdcp22_Tx_Dp::DownstreamTopologyAvailableCallback, XHdcp22_Tx_Dp::Info, XHdcp22_Tx_Dp_Timer::InitialTicks, XHdcp22_Tx_Dp::IsAuthenticatedCallbackSet, XHdcp22_Tx_Dp_Info::IsContentStreamTypeSet, XHdcp22_Tx_Dp::IsDdcReadSet, XHdcp22_Tx_Dp::IsDdcWriteSet, XHdcp22_Tx_Dp::IsDownstreamTopologyAvailableCallbackSet, XHdcp22_Tx_Dp_Info::IsEnabled, XHdcp22_Tx_Dp::IsReady, XHdcp22_Tx_Dp_Info::IsReceiverHDCP2Capable, XHdcp22_Tx_Dp_Info::IsRevocationListValid, XHdcp22_Tx_Dp_Info::IsTopologyAvailable, XHdcp22_Tx_Dp::IsUnauthenticatedCallbackSet, XHdcp22_Tx_Dp_Info::MsgAvailable, XHdcp22_Tx_Dp_Info::PollingValue, XHdcp22_Tx_Dp_Info::Protocol, XHdcp22_Tx_Dp_Info::PrvState, XHdcp22_Tx_Dp_Timer::ReasonId, XHdcp22_Tx_Dp_Info::ReceivedFirstSeqNum_V, XHdcp22_Tx_Dp::RevocationList, XHdcp22_Tx_Dp_Info::StateContext, XHdcp22_Tx_Dp::Timer, XHdcp22_Tx_Dp_Timer::TimerExpired, XHdcp22_Tx_Dp::UnauthenticatedCallback, XHDCP22_STREAMTYPE_0, XHDCP22_TX_DEFAULT_RX_STATUS_POLLVALUE, XHDCP22_TX_HDMI, XHDCP22_TX_STATE_A0, XHDCP22_TX_STATE_A1, XHDCP22_TX_STATE_A1_1, XHDCP22_TX_STATE_A1_NSK0, XHDCP22_TX_STATE_A1_NSK1, XHDCP22_TX_STATE_A1_SK0, XHDCP22_TX_STATE_A2, XHDCP22_TX_STATE_A2_1, XHDCP22_TX_STATE_A3, XHDCP22_TX_STATE_A4, XHDCP22_TX_STATE_A5, XHDCP22_TX_STATE_A6_A7_A8, XHDCP22_TX_STATE_A9, XHDCP22_TX_STATE_H0, XHDCP22_TX_TS_UNDEFINED, XHDCP22_TX_UNAUTHENTICATED, XHdcp22Tx_Dp_ClearPairingInfo, XHdcp22Tx_Dp_LogReset.
void XHdcp22Tx_Dp_LoadLc128(XHdcp22_Tx_Dp *InstancePtr, const u8 *Lc128Ptr)
This function is used to load the Lc128 value by copying the contents of the array referenced by Lc128Ptr into the cipher.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. Lc128Ptr is a pointer to an array. None.
References XHdcp22_Tx_Dp::Cipher, XHDCP22_TX_LC128_SIZE.
int XHdcp22Tx_Dp_LoadRevocationTable(XHdcp22_Tx_Dp *InstancePtr, const u8 *SrmPtr)
This function is used to load the system renewability messages (SRMs) which carries the Receiver ID revocation list.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. SrmPtr is a pointer to an array. XST_SUCCESS if loaded SRM successfully.XST_FAILURE if SRM signature verification failed. None.
References XHdcp22_Tx_Dp::Info, XHdcp22_Tx_Dp_Info::IsRevocationListValid, XHDCP22_TX_KPUB_DCP_LLC_E_SIZE, XHDCP22_TX_KPUB_DCP_LLC_N_SIZE, XHDCP22_TX_REVOCATION_LIST_MAX_DEVICES, XHDCP22_TX_SRM_RCVID_SIZE, XHdcp22Tx_Dp_GetRevocationReceiverIdList, XHdcp22Tx_VerifySRM.
u8 XHdcp22Tx_Dp_IsDeviceRevoked(XHdcp22_Tx_Dp *InstancePtr, u8 *RecvIdPtr)
This function searches for the specified ReceiverID in the revocation list.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. RecvIdPtr is a pointer to the ReceiverID to lookup TRUE if Receiver ID was found in the revocation listFALSE if Receiver ID was not found in the revocation list None.
References XHDCP22_TX_SRM_RCVID_SIZE, XHdcp22Tx_Dp_GetRevocationReceiverIdList.
Referenced by XHdcp22Tx_Dp_RevokeReceiverId.
XHdcp22_Tx_Dp_RevocationList * XHdcp22Tx_Dp_GetRevocationReceiverIdList(XHdcp22_Tx_Dp *InstancePtr)
This function returns a pointer to the Revocation Receiver ID list.
InstancePtr is a pointer to the XHdcp22_Tx_Dp instance. Pointer to the XHdcp22_Tx_Dp_RevocationList instance.
References XHdcp22_Tx_Dp::RevocationList.
Referenced by XHdcp22Tx_Dp_IsDeviceRevoked, XHdcp22Tx_Dp_LoadRevocationTable, XHdcp22Tx_Dp_RevokeReceiverId.
XHdcp22_Tx_Dp_Topology * XHdcp22Tx_Dp_GetTopology(XHdcp22_Tx_Dp *InstancePtr)
This function returns a pointer to the downstream topology structure.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. A pointer to the XHdcp22_Tx_Dp_Topology structure or NULL when the topology info is invalid. None.
References XHdcp22_Tx_Dp::Info, XHdcp22_Tx_Dp_Info::IsTopologyAvailable, XHdcp22_Tx_Dp::Topology.
u8 * XHdcp22Tx_Dp_GetTopologyReceiverIdList(XHdcp22_Tx_Dp *InstancePtr)
This function returns a pointer to the ReceiverID list in the repeater topology structure.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. A pointer to the ReceiverID list in the topology structure. None.
References XHdcp22_Tx_Dp_Topology::ReceiverId, XHdcp22_Tx_Dp::Topology.
u32 XHdcp22Tx_Dp_GetTopologyField(XHdcp22_Tx_Dp *InstancePtr, XHdcp22_Tx_Dp_TopologyField Field)
This function is used to get various fields inside the topology structure.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. Field indicates what field of the topology structure to get. Value associated to field inside the topology structure. None.
void XHdcp22Tx_Dp_SetContentStreamType(XHdcp22_Tx_Dp *InstancePtr, XHdcp22_Tx_Dp_ContentStreamType StreamType)
This function sets the Content Stream Type.
InstancePtr is a pointer to the XHdcp22_Tx_Dp instance. StreamType specifies the content stream type.
References XHdcp22_Tx_Dp_Info::ContentStreamType, XHdcp22_Tx_Dp::Info, XHdcp22_Tx_Dp_Info::IsContentStreamTypeSet.
u32 XHdcp22Tx_Dp_GetVersion(XHdcp22_Tx_Dp *InstancePtr)
This function reads the version.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. Returns the version register of the cipher. None.
References XHdcp22_Tx_Dp::Cipher.
int XHdcp22Tx_Dp_Authenticate(XHdcp22_Tx_Dp *InstancePtr)
This function is a called to start authentication.
InstancePtr is a pointer to the XHdcp22Tx core instance. XST_SUCCESS if authenticated is started successfully.XST_FAIL if the state machine is disabled. None.
References XHdcp22_Tx_Dp_Info::AuthenticationStatus, XHdcp22_Tx_Dp_Info::CurrentState, XHdcp22_Tx_Dp::Info, XHdcp22_Tx_Dp_Info::IsContentStreamTypeSet, XHdcp22_Tx_Dp_Info::IsEnabled, XHdcp22_Tx_Dp_Info::IsReceiverHDCP2Capable, XHdcp22_Tx_Dp_Info::IsTopologyAvailable, XHdcp22_Tx_Dp_Info::PrvState, XHDCP22_TX_AUTHENTICATION_BUSY, XHDCP22_TX_STATE_H0, XHdcp22Tx_Dp_IsRepeater.
int XHdcp22Tx_Dp_Poll(XHdcp22_Tx_Dp *InstancePtr)
This function is a executed every time to trigger the state machine.
The user of HDCP22 TX is responsible to call this function on a regular base. InstancePtr is a pointer to the XHdcp22Tx core instance. Enumerated authentication status defined in XHdcp22_Tx_Dp_AuthenticationType. None.
References XHdcp22_Tx_Dp_Info::AuthenticationStatus, XHdcp22_Tx_Dp_Info::CurrentState, XHdcp22_Tx_Dp::Info, XHdcp22_Tx_Dp_Info::IsEnabled, XHdcp22_Tx_Dp_Info::PrvState, XHDCP22_TX_AUTHENTICATION_BUSY, XHDCP22_TX_LOG_EVT_POLL_RESULT, XHdcp22_Tx_StateTable, XHdcp22Tx_Dp_LogWr.
int XHdcp22Tx_Dp_Reset(XHdcp22_Tx_Dp *InstancePtr)
This function resets the state machine.
InstancePtr is a pointer to the XHdcp22Tx core instance. XST_SUCCESS None.
References XHdcp22_Tx_Dp_Info::AuthenticationStatus, XHdcp22_Tx_Dp_Info::AuthRequestCnt, XHdcp22_Tx_Dp::Cipher, XHdcp22_Tx_Dp_Info::CurrentState, XHdcp22_Tx_Dp::Info, XHdcp22_Tx_Dp_Info::IsTopologyAvailable, XHdcp22_Tx_Dp::IsUnauthenticatedCallbackSet, XHdcp22_Tx_Dp_Info::PrvState, XHdcp22_Tx_Dp_Info::ReauthRequestCnt, XHdcp22_Tx_Dp::Timer, XHdcp22_Tx_Dp_Timer::TmrCtr, XHdcp22_Tx_Dp::UnauthenticatedCallback, XHDCP22_TX_AUTHENTICATED, XHDCP22_TX_LOG_EVT_RESET, XHDCP22_TX_STATE_H0, XHDCP22_TX_TIMER_CNTR_0, XHDCP22_TX_UNAUTHENTICATED, XHdcp22Tx_Dp_DisableEncryption, XHdcp22Tx_Dp_LogWr.
int XHdcp22Tx_Dp_Enable(XHdcp22_Tx_Dp *InstancePtr)
This function enables the state machine and acts as a resume.
InstancePtr is a pointer to the XHdcp22Tx core instance. XST_SUCCESS None.
References XHdcp22_Tx_Dp::Cipher, XHdcp22_Tx_Dp::Info, XHdcp22_Tx_Dp_Info::IsEnabled, XHdcp22_Tx_Dp::Timer, XHdcp22_Tx_Dp_Timer::TmrCtr, XHDCP22_TX_LOG_EVT_ENABLED, XHDCP22_TX_TIMER_CNTR_0, XHdcp22Tx_Dp_LogWr.
int XHdcp22Tx_Dp_Disable(XHdcp22_Tx_Dp *InstancePtr)
This function disables the state machine and acts as a pause.
InstancePtr is a pointer to the XHdcp22Tx core instance. XST_SUCCESS. None.
References XHdcp22_Tx_Dp::Cipher, XHdcp22_Tx_Dp::Info, XHdcp22_Tx_Dp_Info::IsEnabled, XHDCP22_TX_LOG_EVT_ENABLED, XHdcp22Tx_Dp_LogWr.
int XHdcp22Tx_Dp_EnableEncryption(XHdcp22_Tx_Dp *InstancePtr)
This function enables HDMI stream encryption by enabling the cipher.
InstancePtr is a pointer to the XHdcp22Tx core instance. - XST_SUCCESS if authenticated is started successfully. XST_FAIL if the state machine is disabled. None.
References XHdcp22_Tx_Dp::Cipher, XHDCP22_TX_LOG_EVT_ENCR_ENABLED, XHdcp22Tx_Dp_IsAuthenticated, XHdcp22Tx_Dp_LogWr.
int XHdcp22Tx_Dp_DisableEncryption(XHdcp22_Tx_Dp *InstancePtr)
This function disables HDMI stream encryption by disabling the cipher.
InstancePtr is a pointer to the XHdcp22Tx core instance. XST_SUCCESS. None.
References XHdcp22_Tx_Dp::Cipher, XHDCP22_TX_LOG_EVT_ENCR_ENABLED, XHdcp22Tx_Dp_LogWr.
Referenced by XHdcp22Tx_Dp_Reset.
void XHdcp22Tx_Dp_EnableBlank(XHdcp22_Tx_Dp *InstancePtr)
This function enables the blank output for the cipher.
InstancePtr is a pointer to the XHdcp22Tx core instance. None.
References XHdcp22_Tx_Dp::Cipher.
void XHdcp22Tx_Dp_DisableBlank(XHdcp22_Tx_Dp *InstancePtr)
This function disables the blank output for the cipher.
InstancePtr is a pointer to the XHdcp22Tx core instance. None.
References XHdcp22_Tx_Dp::Cipher.
u8 XHdcp22Tx_Dp_IsRepeater(XHdcp22_Tx_Dp *InstancePtr)
This function returns the current repeater mode status.
InstancePtr is a pointer to the XHdcp22_Tx_Dp instance. TRUE if the HDCP 2.2 instance is part of the downstream port of a repeaterFALSE if the HDCP 2.2 instance is a transmitter
References XHdcp22_Tx_Dp::Config, XHdcp22_Tx_Dp_Config::Mode, XHDCP22_TX_TRANSMITTER.
Referenced by XHdcp22Tx_Dp_Authenticate, XHdcp22Tx_Dp_Info.
void XHdcp22Tx_Dp_SetRepeater(XHdcp22_Tx_Dp *InstancePtr, u8 Set)
This function sets the repeater mode status.
InstancePtr is a pointer to the XHdcp22_Tx_Dp instance. Set is TRUE to enable the repeater mode and FALSE to disable.
References XHdcp22_Tx_Dp::Config, XHdcp22_Tx_Dp_Config::Mode, XHDCP22_TX_REPEATER, XHDCP22_TX_TRANSMITTER.
u8 XHdcp22Tx_Dp_IsEnabled(XHdcp22_Tx_Dp *InstancePtr)
This function returns the current enabled state.
InstancePtr is a pointer to the XHdcp22Tx core instance. TRUE if enabled otherwise FALSE. None.
References XHdcp22_Tx_Dp::Info, XHdcp22_Tx_Dp_Info::IsEnabled.
Referenced by XHdcp22Tx_Dp_Info.
u8 XHdcp22Tx_Dp_IsEncryptionEnabled(XHdcp22_Tx_Dp *InstancePtr)
This function returns the current encryption enabled state.
InstancePtr is a pointer to the XHdcp22Tx core instance. TRUE if encryption is enabled otherwise FALSE. None.
References XHdcp22_Tx_Dp::Cipher.
Referenced by XHdcp22Tx_Dp_Info.
u8 XHdcp22Tx_Dp_IsInProgress(XHdcp22_Tx_Dp *InstancePtr)
This function returns the current progress state.
InstancePtr is a pointer to the XHdcp22Tx core instance. TRUE if authentication is in progress otherwise FALSE. None.
References XHdcp22_Tx_Dp_Info::AuthenticationStatus, XHdcp22_Tx_Dp::Info, XHDCP22_TX_UNAUTHENTICATED.
u8 XHdcp22Tx_Dp_IsAuthenticated(XHdcp22_Tx_Dp *InstancePtr)
This function returns the current authenticated state.
InstancePtr is a pointer to the XHdcp22Tx core instance. TRUE if authenticated otherwise FALSE. None.
References XHdcp22_Tx_Dp_Info::AuthenticationStatus, XHdcp22_Tx_Dp::Info, XHDCP22_TX_AUTHENTICATED.
Referenced by XHdcp22Tx_Dp_EnableEncryption.
u8 XHdcp22Tx_Dp_IsDwnstrmCapable(XHdcp22_Tx_Dp *InstancePtr)
This function checks if the downstream device HDCP2Version register is set.
InstancePtr is a pointer to the XHdcp22Tx core instance. - TRUE if downstream device is HDCP 2.2 capable. FALSE if downstream device is not HDCP 2.2 capable. None.
References XHdcp22_Tx_Dp::Config, XHdcp22_Tx_Dp::DdcHandlerRef, XHdcp22_Tx_Dp::DdcRead, XHdcp22_Tx_Dp::DdcWrite, XHdcp22_Tx_Dp::IsReceiverHDCP2Capable, XHdcp22_Tx_Dp_Config::Protocol, XHdcp22_Tx_Dp::TxDpAuxReadCallback, XHdcp22_Tx_Dp::TxDpAuxReadCallbackRef, XHDCP22_TX_DDC_BASE_ADDRESS, XHDCP22_TX_DP, XHDCP22_TX_HDCPPORT_VERSION_OFFSET.
int XHdcp22Tx_Dp_SetCallback(XHdcp22_Tx_Dp *InstancePtr, XHdcp22_Tx_Dp_HandlerType HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs callback functions for the given HandlerType:
HandlerType Callback Function Type ------------------------- --------------------------- (XHDCP22_TX_HANDLER_DDC_WRITE) DdcWrite (XHDCP22_TX_HANDLER_DDC_READ) DdcRead (XHDCP22_TX_HANDLER_AUTHENTICATED) AuthenticatedCallback (XHDCP22_TX_HANDLER_UNAUTHENTICATED) UnauthenticatedCallback (XHDCP22_TX_HANDLER_DOWNSTREAM_TOPOLOGY_AVAILABLE) DownstreamTopologyAvailableCallback InstancePtr is a pointer to the HDMI RX core instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XHdcp22_Tx_Dp::AuthenticatedCallback, XHdcp22_Tx_Dp::DdcHandlerRef, XHdcp22_Tx_Dp::DdcRead, XHdcp22_Tx_Dp::DdcWrite, XHdcp22_Tx_Dp::DownstreamTopologyAvailableCallback, XHdcp22_Tx_Dp::IsAuthenticatedCallbackSet, XHdcp22_Tx_Dp::IsDdcReadSet, XHdcp22_Tx_Dp::IsDdcWriteSet, XHdcp22_Tx_Dp::IsDownstreamTopologyAvailableCallbackSet, XHdcp22_Tx_Dp::IsTxDpAuxReadCallbackSet, XHdcp22_Tx_Dp::IsTxDpAuxWriteCallbackSet, XHdcp22_Tx_Dp::IsUnauthenticatedCallbackSet, XHdcp22_Tx_Dp::TxDpAuxReadCallback, XHdcp22_Tx_Dp::TxDpAuxReadCallbackRef, XHdcp22_Tx_Dp::TxDpAuxWriteCallback, XHdcp22_Tx_Dp::TxDpAuxWriteCallbackRef, XHdcp22_Tx_Dp::UnauthenticatedCallback, XHDCP22_TX_HANDLER_DP_AUX_READ, XHDCP22_TX_HANDLER_DP_AUX_WRITE.
XTmrCtr * XHdcp22Tx_Dp_GetTimer(XHdcp22_Tx_Dp *InstancePtr)
This function returns the pointer to the internal timer control instance needed for connecting the timer interrupt to an interrupt controller.
InstancePtr is a pointer to the XHdcp22Tx core instance. A pointer to the internal timer control instance. None.
References XHdcp22_Tx_Dp::Timer, XHdcp22_Tx_Dp_Timer::TmrCtr.
void XHdcp22Tx_Dp_TimerHandler(void *CallbackRef, u8 TmrCntNumber)
This function handles timer interrupts.
CallbackRef refers to a XHdcp22_Tx_Dp structure TmrCntNumber the number of used timer. For dp design, this will be called form the Tx subsystem's timer handler so it should be a public function.
References XHdcp22_Tx_Dp::Info, XHdcp22_Tx_Dp_Info::IsEnabled, XHdcp22_Tx_Dp::IsReady, XHdcp22_Tx_Dp::Timer, XHdcp22_Tx_Dp_Timer::TimerExpired, XHDCP22_TX_TIMER_CNTR_1.
void XHdcp22Tx_Dp_SetMessagePollingValue(XHdcp22_Tx_Dp *InstancePtr, u32 PollingValue)
This function can be used to change the polling value.
The polling value is the amount of time in milliseconds to wait between successive reads of the RxStatus register. The RxStatus register is polled to determine when a message is available for reading during authentication or during the link integrity check phase to determine when to issue re-authentication. The polling value needs to be at most 20ms to account for the locality check. InstancePtr is a pointer to the XHdcp22Tx core instance. PollingValue is the polling interval defined in milliseconds 0 : Always Poll1 : Poll after 1ms2 : Poll after 2ms3 : Poll after 3ms etc... None.
References XHdcp22_Tx_Dp::Info, XHdcp22_Tx_Dp_Info::PollingValue.
int XHdcp22Tx_Dp_ClearPairingInfo(XHdcp22_Tx_Dp *InstancePtr)
This function clear the global pairing info structure, so every HDCP2.2 receiver will have to go through the 'no stored km' sequence to authenticate.
InstancePtr is a pointer to the XHdcp22Tx core instance. XST_SUCCESS None.
References XHdcp22_Tx_Dp::Info.
Referenced by XHdcp22Tx_Dp_CfgInitialize.
void XHdcp22Tx_Dp_RevokeReceiverId(XHdcp22_Tx_Dp *InstancePtr, u8 *ReceiverIdPtr)
This function adds a ReceiverID to RevocationList.
InstancePtr is a pointer to the XHdcp22Tx core instance. ReceiverIdPtr is a pointer to a 5-byte receiver Id. Supposed to be called by Upstream Content Control Function
References XHdcp22_Tx_Dp_Info::AuthenticationStatus, XHdcp22_Tx_Dp::Config, XHdcp22_Tx_Dp_Info::CurrentState, XHdcp22_Tx_Dp::Info, XHdcp22_Tx_Dp_Info::IsDeviceRevoked, XHdcp22_Tx_Dp_Info::IsRevocationListValid, XHdcp22_Tx_Dp_Config::Mode, XHDCP22_TX_DEVICE_IS_REVOKED, XHDCP22_TX_SRM_RCVID_SIZE, XHDCP22_TX_STATE_A0, XHDCP22_TX_TRANSMITTER, XHdcp22Tx_Dp_GetRevocationReceiverIdList, XHdcp22Tx_Dp_IsDeviceRevoked.
void XHdcp22Tx_Dp_LogReset(XHdcp22_Tx_Dp *InstancePtr, u8 Verbose)
This function clears the log pointers.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. Verbose allows to add debug logging. None.
References XHdcp22_Tx_Dp_Log::Head, XHdcp22_Tx_Dp::Log, XHdcp22_Tx_Dp_Log::Tail, XHdcp22_Tx_Dp::Timer, XHdcp22_Tx_Dp_Timer::TmrCtr, XHdcp22_Tx_Dp_Log::Verbose, XHDCP22_TX_TIMER_CNTR_1.
Referenced by XHdcp22Tx_Dp_CfgInitialize.
u32 XHdcp22Tx_Dp_LogGetTimeUSecs(XHdcp22_Tx_Dp *InstancePtr)
This function returns the time expired since a log reset was called.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. The expired logging time in useconds. None.
References XHdcp22_Tx_Dp::Timer, XHdcp22_Tx_Dp_Timer::TmrCtr, XHDCP22_TX_TIMER_CNTR_1.
Referenced by XHdcp22Tx_Dp_LogWr.
void XHdcp22Tx_Dp_LogWr(XHdcp22_Tx_Dp *InstancePtr, XHdcp22_Tx_Dp_LogEvt Evt, u16 Data)
This function writes HDCP TX logs into buffer.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. Evt specifies an action to be carried out. Please refer XHdcp22_Tx_Dp_LogEvt enum in xhdcp22_tx_dp.h. Data specifies the information that gets written into log buffer. None.
References XHdcp22_Tx_Dp_LogItem::Data, XHdcp22_Tx_Dp_Log::Head, XHdcp22_Tx_Dp::Log, XHdcp22_Tx_Dp_LogItem::LogEvent, XHdcp22_Tx_Dp_Log::LogItems, XHdcp22_Tx_Dp_Log::Tail, XHdcp22_Tx_Dp_LogItem::TimeStamp, XHdcp22_Tx_Dp_Log::Verbose, XHDCP22_TX_LOG_BUFFER_SIZE, XHDCP22_TX_LOG_EVT_DBG, XHDCP22_TX_LOG_INVALID, XHdcp22Tx_Dp_LogGetTimeUSecs.
Referenced by XHdcp22Tx_Dp_Disable, XHdcp22Tx_Dp_DisableEncryption, XHdcp22Tx_Dp_Enable, XHdcp22Tx_Dp_EnableEncryption, XHdcp22Tx_Dp_Poll, XHdcp22Tx_Dp_Reset.
XHdcp22_Tx_Dp_LogItem * XHdcp22Tx_Dp_LogRd(XHdcp22_Tx_Dp *InstancePtr)
This function provides the log information from the log buffer.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. Content of log buffer if log pointers are not equal.Otherwise Zero. None.
References XHdcp22_Tx_Dp_LogItem::Data, XHdcp22_Tx_Dp_Log::Head, XHdcp22_Tx_Dp::Log, XHdcp22_Tx_Dp_LogItem::LogEvent, XHdcp22_Tx_Dp_Log::LogItems, XHdcp22_Tx_Dp_Log::Tail, XHdcp22_Tx_Dp_LogItem::TimeStamp, XHDCP22_TX_LOG_BUFFER_SIZE, XHDCP22_TX_LOG_EVT_NONE.
Referenced by XHdcp22Tx_Dp_LogDisplay.
void XHdcp22Tx_Dp_LogDisplay(XHdcp22_Tx_Dp *InstancePtr)
This function prints the content of log buffer.
InstancePtr is a pointer to the HDCP22 TX core instance. None.
References XHdcp22_Tx_Dp_LogItem::Data, XHdcp22_Tx_Dp_LogItem::LogEvent, XHdcp22_Tx_Dp_LogItem::TimeStamp, XHDCP22_TX_AKE_NO_STORED_KM, XHDCP22_TX_AUTHENTICATED, XHDCP22_TX_AUTHENTICATION_BUSY, XHDCP22_TX_CASE_TO_STR_PRE, XHDCP22_TX_INCOMPATIBLE_RX, XHDCP22_TX_LOG_EVT_DBG, XHDCP22_TX_LOG_EVT_ENABLED, XHDCP22_TX_LOG_EVT_ENCR_ENABLED, XHDCP22_TX_LOG_EVT_LCCHK_COUNT, XHDCP22_TX_LOG_EVT_NONE, XHDCP22_TX_LOG_EVT_POLL_RESULT, XHDCP22_TX_LOG_EVT_RESET, XHDCP22_TX_LOG_EVT_STATE, XHDCP22_TX_LOG_EVT_STRMMNGCHK_COUNT, XHDCP22_TX_LOG_EVT_TEST_ERROR, XHDCP22_TX_LOG_EVT_USER, XHDCP22_TX_MSG_UNDEFINED, XHDCP22_TX_REAUTHENTICATE_REQUESTED, XHDCP22_TX_SKE_SEND_EKS, XHDCP22_TX_UNAUTHENTICATED, XHdcp22Tx_Dp_LogRd.
void XHdcp22Tx_Dp_Info(XHdcp22_Tx_Dp *InstancePtr)
This function prints the state machine information.
InstancePtr is a pointer to the HDCP22 TX core instance. None.
References XHdcp22_Tx_Dp_Info::AuthenticationStatus, XHdcp22_Tx_Dp_Info::AuthRequestCnt, XHdcp22_Tx_Dp_Info::ContentStreamType, XHdcp22_Tx_Dp_Topology::Depth, XHdcp22_Tx_Dp_Topology::DeviceCnt, XHdcp22_Tx_Dp_Topology::Hdcp1DeviceDownstream, XHdcp22_Tx_Dp_Topology::Hdcp2LegacyDeviceDownstream, XHdcp22_Tx_Dp::Info, XHdcp22_Tx_Dp_Topology::MaxCascadeExceeded, XHdcp22_Tx_Dp_Topology::MaxDevsExceeded, XHdcp22_Tx_Dp_Info::PollingValue, XHdcp22_Tx_Dp_Info::ReauthRequestCnt, XHdcp22_Tx_Dp::Topology, XHDCP22_TX_AUTHENTICATED, XHDCP22_TX_AUTHENTICATION_BUSY, XHDCP22_TX_DEVICE_IS_REVOKED, XHDCP22_TX_INCOMPATIBLE_RX, XHDCP22_TX_NO_SRM_LOADED, XHDCP22_TX_REAUTHENTICATE_REQUESTED, XHDCP22_TX_UNAUTHENTICATED, XHdcp22Tx_Dp_IsEnabled, XHdcp22Tx_Dp_IsEncryptionEnabled, XHdcp22Tx_Dp_IsRepeater.
void XHdcp22Tx_Dp_SetHdcp22OverProtocol(XHdcp22_Tx_Dp *InstancePtr, XHdcp22_Tx_Dp_Protocol protocol)
This function is to set the protocol (HDMI/DP) over which HDCP22 is happening.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. protocol is the protocol HDMI/DP.
References XHdcp22_Tx_Dp::Config, XHdcp22_Tx_Dp_Config::Protocol.
void XHdcp22Tx_Dp_timer_attach(XHdcp22_Tx_Dp *InstancePtr, XTmrCtr *TmrCtrPtr)
This function is to attach the HDCP22 timer instance to DP TX subsystem's timer.
For the DP design the timer is being used from the DP TX subsystem. So the HDCP22 timer instance will be attached in DpTxSs initialization. InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. TmrCtrPtr is the DpTx susbsystem's timer instance. For the DP design the timer is being used from the DP TX subsystem. So the HDCP22 timer instance will be attached in DpTxSs initialization.
References XHdcp22_Tx_Dp::Timer, XHdcp22_Tx_Dp_Timer::TmrCtr, XHDCP22_TX_TIMER_CNTR_0, XHDCP22_TX_TIMER_CNTR_1.
void XHdcp22Tx_Dp_Handle_Cp_Irq(XHdcp22_Tx_Dp *InstancePtr)
This function is to read the RX_STATUS when a cp_irq received.
InstancePtr is a pointer to the XHdcp22_Tx_Dp core instance. none
References XHdcp22_Tx_Dp_Info::Dp_RxStatus, XHdcp22_Tx_Dp::Info, XHdcp22_Tx_Dp::TxDpAuxReadCallback, XHdcp22_Tx_Dp::TxDpAuxReadCallbackRef.
int XHdcp22Tx_Dp_SetLaneCount(XHdcp22_Tx_Dp *InstancePtr, u8 LaneCount)
This function set the lane count of an hdcp22 interface.
InstancePtr is the transmitter instance. LaneCount is the number of lanes of the interface. XST_SUCCESS if successful. None.
References XHdcp22_Tx_Dp::Cipher.
int XHdcp22Tx_Dp_SetMst(XHdcp22_Tx_Dp *InstancePtr, u8 Mode)
This function set the MST mode of an hdcp22 interface.
InstancePtr is the transmitter instance. Mode enables the MST configuration of the interface. XST_SUCCESS if successful. None.
References XHdcp22_Tx_Dp::Cipher.