dual_splitter
XDUSP_GENR_CTL_OFFSET
General Control register offset.
Referenced by XDualSplitter_Reset.
XDUSP_GENR_ERR_OFFSET
General Error register offset.
XDUSP_IRQ_EN_OFFSET
IRQ Enable register offset.
XDUSP_TIME_CTL_OFFSET
Time Control register offset.
Referenced by XDualSplitter_GetImageSize, XDualSplitter_SetImageSize.
XDUSP_CORE_CTL_OFFSET
Core Control register offset.
Referenced by XDualSplitter_GetImgParam, XDualSplitter_SetImgParam.
XDUSP_GENR_CTL_EN_MASK
Enable mask.
XDUSP_GENR_CTL_RUE_MASK
Register update enable mask.
XDUSP_GENR_CTL_RST_MASK
Reset mask.
Referenced by XDualSplitter_Reset.
XDUSP_ERR_EOL_EARLY_MASK
Error: End of line early mask.
XDUSP_ERR_EOL_LATE_MASK
Error: End of line late mask.
XDUSP_ERR_SOF_EARLY_MASK
Error: Start of frame early mask.
XDUSP_ERR_SOF_LATE_MASK
Error: Start of frame late mask.
XDUSP_ALL_ERR_MASK
All error mask.
Referenced by XDualSplitter_IntrHandler.
XDUSP_TIME_CTL_WIDTH_MASK
Image width mask.
Referenced by XDualSplitter_GetImageSize, XDualSplitter_SetImageSize.
XDUSP_TIME_CTL_HEIGHT_MASK
Image height mask.
Referenced by XDualSplitter_SetImageSize.
XDUSP_TIME_CTL_HEIGHT_SHIFT
Image height shift.
Referenced by XDualSplitter_GetImageSize, XDualSplitter_SetImageSize.
XDUSP_CORE_CTL_IN_SAMPLES_MASK
Input samples mask.
Referenced by XDualSplitter_GetImgParam, XDualSplitter_SetImgParam.
XDUSP_CORE_CTL_OUT_SAMPLES_MASK
Output samples mask.
Referenced by XDualSplitter_GetImgParam, XDualSplitter_SetImgParam.
XDUSP_CORE_CTL_IMG_SEG_MASK
No of image segments mask.
Referenced by XDualSplitter_GetImgParam, XDualSplitter_SetImgParam.
XDUSP_CORE_CTL_OVRLAP_SEG_MASK
No of over- lapping segments mask.
Referenced by XDualSplitter_GetImgParam, XDualSplitter_SetImgParam.
XDUSP_CORE_CTL_OUT_SAMPLES_SHIFT
Output samples shift.
Referenced by XDualSplitter_GetImgParam, XDualSplitter_SetImgParam.
XDUSP_CORE_CTL_IMG_SEG_SHIFT
No of image segments shift.
Referenced by XDualSplitter_GetImgParam, XDualSplitter_SetImgParam.
XDUSP_CORE_CTL_OVRLAP_SEG_SHIFT
No of overlapping segments shift.
Referenced by XDualSplitter_GetImgParam, XDualSplitter_SetImgParam.
XDualSplitter_In32
Input operation.
XDualSplitter_Out32
Output operation.
XDualSplitter_ReadReg
This macro reads a value from a Dual Splitter core's register.
A 32 bit read is performed. If the component is implemented in a smaller width, only the least significant data is read from the register. The most significant data will be read as 0. BaseAddress is the base address of the XDualSplitter core. RegOffset is the register offset of the register (defined at the top of this file). The 32-bit value of the register. C-style signature: u32 XDualSplitter_ReadReg(u32 BaseAddress, u32 RegOffset)
Referenced by XDualSplitter_GetImageSize, XDualSplitter_GetImgParam, XDualSplitter_Reset.
XDualSplitter_WriteReg
This macro writes a value into a Dual Splitter core's register.
A 32 bit write is performed. If the component is implemented in a smaller width, only the least significant data is written. BaseAddress is the base address of the XDualSplitter core. RegOffset is the register offset of the register (defined at the top of this file) to be written. Data is the 32-bit value to write into the register. None. C-style signature: void XDualSplitter_WriteReg(u32 BaseAddress, u32 RegOffset, u32 Data)
Referenced by XDualSplitter_Reset, XDualSplitter_SetImageSize, XDualSplitter_SetImgParam.
typedef void(* XDualSplitter_ErrCallback)(void *CallbackRef, u32 ErrorMask))(void *CallbackRef, u32 ErrorMask)
Callback type for error interrupt.
CallbackRef is a callback reference passed in by the upper layer when setting the callback functions and passed back to the upper layer when the callback is invoked. ErrorMask is a bit mask indicating the cause of the error. Its value equals 'OR'ing one or more XDUSP_ERR_*_MASK values defined in xdualsplitter_hw.h.
static void StubErrCallback(void *CallbackRef, u32 ErrorMask)
This routine is a stub for the asynchronous error interrupt callback.
The stub is here in case the upper layer forgot to set the handler. On initialization, error interrupt handler is set to this callback. It is considered as an error for this handler to be invoked. CallbackRef is a callback reference passed in by the upper layer when setting the callback functions and passed back to the upper layer when the callback is invoked. ErrorMask is a bit mask indicating the cause of the error. Its value equals 'OR'ing one or more XDUSP_ERR_*_MASK values defined in xdualsplitter_hw.h. None. None.
s32 XDualSplitter_CfgInitialize(XDualSplitter *InstancePtr, XDualSplitter_Config *CfgPtr, u32 EffectiveAddr)
This function initializes the Dual Splitter core.
This function must be called prior to using the Dual Splitter core. Initialization of the core includes setting up the instance data and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the XDualSplitter core instance. CfgPtr points to the configuration structure associated with the Dual Splitter core. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if XDualSplitter_CfgInitialize was successful. None.
References XDualSplitter_Config::BaseAddress, XDualSplitter::Config, XDualSplitter::ErrCallback, XDualSplitter::IsReady, XDualSplitter_Reset.
Referenced by XDualSplitterExample.
void XDualSplitter_Reset(XDualSplitter *InstancePtr)
This function resets the Dual Splitter core instance.
This reset effects the core immediately and may cause image tearing. InstancePtr is a pointer to the XDualSplitter core instance. None. None.
References XDualSplitter_Config::BaseAddress, XDualSplitter::Config, XDualSplitter_ReadReg, XDualSplitter_WriteReg, XDUSP_GENR_CTL_OFFSET, XDUSP_GENR_CTL_RST_MASK.
Referenced by XDualSplitter_CfgInitialize.
void XDualSplitter_SetImageSize(XDualSplitter *InstancePtr, u16 Height, u16 Width)
This function sets the image size (width x height) of the Dual Splitter core.
InstancePtr is a pointer to the XDualSplitter core instance. Height specifies the height of the input image that needs to be set within the range [0, 2160]. Width specifies the width of the input image that needs to be set within the range [0, 3840]. None. None.
References XDualSplitter_Config::BaseAddress, XDualSplitter::Config, XDualSplitter_WriteReg, XDUSP_MAX_IMG_HEIGHT, XDUSP_MAX_IMG_WIDTH, XDUSP_TIME_CTL_HEIGHT_MASK, XDUSP_TIME_CTL_HEIGHT_SHIFT, XDUSP_TIME_CTL_OFFSET, XDUSP_TIME_CTL_WIDTH_MASK.
Referenced by XDualSplitter_SelfTest, XDualSplitterExample.
void XDualSplitter_GetImageSize(XDualSplitter *InstancePtr, u16 *Height, u16 *Width)
This function gets the image size (width x height) of the Dual Splitter core.
InstancePtr is a pointer to the XDualSplitter core instance. Height specifies a pointer to the 16-bit variable that will be filled with height which is in the range [0, 2160]. Width specifies a pointer to the 16-bit variable that will be filled with width which is in the range [0, 3840]. None. None.
References XDualSplitter_Config::BaseAddress, XDualSplitter::Config, XDualSplitter_ReadReg, XDUSP_TIME_CTL_HEIGHT_SHIFT, XDUSP_TIME_CTL_OFFSET, XDUSP_TIME_CTL_WIDTH_MASK.
Referenced by XDualSplitter_SelfTest.
void XDualSplitter_SetImgParam(XDualSplitter *InstancePtr, u8 InputSamples, u8 OutputSamples, u8 ImageSegments, u8 Overlap)
This function sets the image parameters to split into multiple segments.
InstancePtr is a pointer to the XDualSplitter core instance. InputSamples specifies the number of input samples per clock that needs to be set within the range [0, 4]. OutputSamples specifies the number of output samples per clock that needs to be set within the range [0, 4]. ImageSegments specifies the number of image segments that needs to be set within the range [0, 4]. Overlap specifies the overlap of the samples in the segments. None. None.
References XDualSplitter_Config::BaseAddress, XDualSplitter::Config, XDualSplitter_WriteReg, XDUSP_CORE_CTL_IMG_SEG_MASK, XDUSP_CORE_CTL_IMG_SEG_SHIFT, XDUSP_CORE_CTL_IN_SAMPLES_MASK, XDUSP_CORE_CTL_OFFSET, XDUSP_CORE_CTL_OUT_SAMPLES_MASK, XDUSP_CORE_CTL_OUT_SAMPLES_SHIFT, XDUSP_CORE_CTL_OVRLAP_SEG_MASK, XDUSP_CORE_CTL_OVRLAP_SEG_SHIFT, XDUSP_MAX_INPUT_SAMPLES, XDUSP_MAX_OUTPUT_SAMPLES, XDUSP_MAX_SEGMENTS.
Referenced by XDualSplitterExample.
void XDualSplitter_GetImgParam(XDualSplitter *InstancePtr, u8 *InputSamples, u8 *OutputSamples, u8 *ImageSegments, u8 *Overlap)
This function gets the image parameters of the Dual Splitter core.
InstancePtr is a pointer to the XDualSplitter core instance. InputSamples specifies a pointer to the 8-bit variable that will be filled with number of input samples which is in the range [0, 4] OutputSamples specifies a pointer to the 8-bit variable that will be filled with number of output samples which is in the range [0, 4] ImageSegments specifies a pointer to the 8-bit variable that will be filled with number of image segments which is in the range [0, 4] Overlap specifies a pointer to the 8-bit variable that will be filled with number of samples overlapping the segments. None. None.
References XDualSplitter_Config::BaseAddress, XDualSplitter::Config, XDualSplitter_ReadReg, XDUSP_CORE_CTL_IMG_SEG_MASK, XDUSP_CORE_CTL_IMG_SEG_SHIFT, XDUSP_CORE_CTL_IN_SAMPLES_MASK, XDUSP_CORE_CTL_OFFSET, XDUSP_CORE_CTL_OUT_SAMPLES_MASK, XDUSP_CORE_CTL_OUT_SAMPLES_SHIFT, XDUSP_CORE_CTL_OVRLAP_SEG_MASK, XDUSP_CORE_CTL_OVRLAP_SEG_SHIFT.
XDualSplitter_Config * XDualSplitter_LookupConfig(UINTPTR BaseAddress)
This function returns a reference to the XDualSplitter_Config structure based on the core id, DeviceId.
The return value will refer to an entry in the device configuration table defined in the xdualsplitter_g.c file. DeviceId is the unique core ID of the Dual Splitter core for the lookup operation. XDualSplitter_LookupConfig returns a reference to a config record in the configuration table (in xdaulsplitter_g.c) corresponding to DeviceId, or NULL if no match is found. None.
Referenced by XDualSplitterExample.
s32 XDualSplitter_SelfTest(XDualSplitter *InstancePtr)
This function performs self test on DualSplitter core registers.
InstancePtr is a pointer to the XDualSplitter core instance. XST_SUCCESS if self test passed.XST_FAILURE if self test failed. None.
References XDualSplitter_GetImageSize, XDualSplitter_SetImageSize.
void XDualSplitter_IntrHandler(void *InstancePtr)
This function is the interrupt handler for the Dual Splitter core.
This handler reads the pending interrupt from the GENR_ERROR register, determines the source of the interrupts and calls the respective callbacks for the interrupts that are enabled in IRQ_ENABLE register, and finally clears the interrupts.The application is responsible for connecting this function to the interrupt system. Application beyond this core is also responsible for providing callbacks to handle interrupts and installing the callbacks using XDualSplitter_SetCallBack() during initialization phase. InstancePtr is a pointer to the XDualSplitter core instance. None. Interrupt should be enabled to execute interrupt handler.
References XDualSplitter::Config, XDualSplitter::ErrCallback, XDualSplitter::ErrRef, XDualSplitter_Config::HasIntrReq, XDualSplitter::IsReady, XDualSplitter_IntrClear, XDualSplitter_IntrGetPending, XDUSP_ALL_ERR_MASK.
void XDualSplitter_SetCallback(XDualSplitter *InstancePtr, void *CallbackFunc, void *CallbackRef)
This function installs an asynchronous callback function.
InstancePtr is a pointer to the XDualSplitter core instance. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. None. Invoking this function for a callback that already has been installed replaces it with the new callback.
References XDualSplitter::ErrCallback, XDualSplitter::ErrRef, XDualSplitter::IsReady.
XDUALSPLITTER_H_
Prevent circular inclusions by using protection macros.
XPAR_XDUALSPLITTER_NUM_INSTANCES
XDUSP_MAX_INPUT_SAMPLES
Maximum input samples per clock.
Referenced by XDualSplitter_SetImgParam.
XDUSP_MAX_OUTPUT_SAMPLES
Maximum output samples per clock.
Referenced by XDualSplitter_SetImgParam.
XDUSP_MAX_SEGMENTS
Maximum number of segments in an image.
Referenced by XDualSplitter_SetImgParam.
XDUSP_MAX_IMG_WIDTH
Maximum image width.
Referenced by XDualSplitter_SetImageSize.
XDUSP_MAX_IMG_HEIGHT
Maximum image height.
Referenced by XDualSplitter_SetImageSize.
XDualSplitter_RegUpdateEnable
This macro commits all the register value changes made so far by the software to the Dual Splitter core.
InstancePtr is a pointer to the XDualSplitter core instance. None. C-style signature: void XDualSplitter_RegUpdateEnable(XDualSplitter *InstancePtr)
Referenced by XDualSplitterExample.
XDualSplitter_RegUpdateDisable
This macro prevents the Dual Splitter core from committing recent changes made so far by the software.
When disabled, changes to other configuration registers are stored but do not effect the behavior of the core. InstancePtr is a pointer to the XDualSplitter core instance. None. C-style signature: void XDualSplitter_RegUpdateDisable(XDualSplitter *InstancePtr)
Referenced by XDualSplitterExample.
XDualSplitter_Enable
This macro enables the Dual Splitter core.
InstancePtr is a pointer to the XDualSplitter core instance. None. C-style signature: void XDualSplitter_Enable(XDualSplitter *InstancePtr)
Referenced by XDualSplitterExample.
XDualSplitter_Disable
This macro disables the Dual Splitter core.
InstancePtr is a pointer to the XDualSplitter core instance. None. C-style signature: void XDualSplitter_Disable(XDualSplitter *InstancePtr)
XDualSplitter_IntrEnable
This macro enables the given individual interrupt(s) on the Dual Splitter core.
InstancePtr is a pointer to the XDualSplitter core instance. IntrType is the bit-mask of the interrupts to be enabled. Bit positions of 1 will be enabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XDUSP_ERR_*_MASK bits defined in xdualsplitter_hw.h. None. The existing enabled interrupt(s) will remain enabled. C-style signature: void XDualSplitter_IntrEnable(XDualSplitter *InstancePtr, u32 IntrType)
XDualSplitter_IntrDisable
This macro disables the given individual interrupt(s) on the Dual Splitter core.
InstancePtr is a pointer to the XDualSplitter core instance. IntrType is the bit-mask of the interrupts to be disabled. Bit positions of 1 will be enabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XDUSP_ERR_*_MASK bits defined in xdualsplitter_hw.h. None. Any other interrupt not covered by parameter IntrType, if enabled before this macro is called, will remain enabled. C-style signature: void XDualSplitter_IntrDisable(XDualSplitter *InstancePtr, u32 IntrType)
XDualSplitter_IntrGetPending
This macro returns the pending interrupts of the Dual Splitter core.
InstancePtr is a pointer to the XDualSplitter core instance. The pending interrupts of the Dual Splitter. Use XDUSP_ERR_*_MASK constants defined in xdualsplitter_hw.h to interpret this value. The returned value is a logical AND of the contents of the GENR_ERROR Register and the IRQ_ENABLE Register. C-style signature: u32 XDualSplitter_IntrGetPending(XDualSplitter *InstancePtr)
Referenced by XDualSplitter_IntrHandler.
XDualSplitter_IntrClear
This macro clears/acknowledges pending interrupts of the Dual Splitter core.
in the General error register. Bit positions of 1 will be cleared. InstancePtr is a pointer to the XDualSplitter core instance. IntrType is the pending interrupts to clear/acknowledge. Use OR'ing of XDUSP_ERR_*_MASK constants defined in xdualsplitter_hw.h to create this parameter value. None. C-style signature: void XDualSplitter_IntrClear(XDualSplitter *InstancePtr, u32 IntrType)
Referenced by XDualSplitter_IntrHandler.
XDUALSPLITTER_HW_H_
Prevent circular inclusions by using protection macros.
XPAR_XDUAL_SPLITTER_NUM_INSTANCES