xdualsplitter.c
static void StubErrCallback(void *CallbackRef, u32 ErrorMask)
This routine is a stub for the asynchronous error interrupt callback.
The stub is here in case the upper layer forgot to set the handler. On initialization, error interrupt handler is set to this callback. It is considered as an error for this handler to be invoked. CallbackRef is a callback reference passed in by the upper layer when setting the callback functions and passed back to the upper layer when the callback is invoked. ErrorMask is a bit mask indicating the cause of the error. Its value equals 'OR'ing one or more XDUSP_ERR_*_MASK values defined in xdualsplitter_hw.h. None. None.
s32 XDualSplitter_CfgInitialize(XDualSplitter *InstancePtr, XDualSplitter_Config *CfgPtr, u32 EffectiveAddr)
This function initializes the Dual Splitter core.
This function must be called prior to using the Dual Splitter core. Initialization of the core includes setting up the instance data and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the XDualSplitter core instance. CfgPtr points to the configuration structure associated with the Dual Splitter core. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if XDualSplitter_CfgInitialize was successful. None.
References XDualSplitter_Config::BaseAddress, XDualSplitter::Config, XDualSplitter::ErrCallback, XDualSplitter::IsReady, XDualSplitter_Reset.
Referenced by XDualSplitterExample.
void XDualSplitter_Reset(XDualSplitter *InstancePtr)
This function resets the Dual Splitter core instance.
This reset effects the core immediately and may cause image tearing. InstancePtr is a pointer to the XDualSplitter core instance. None. None.
References XDualSplitter_Config::BaseAddress, XDualSplitter::Config, XDualSplitter_ReadReg, XDualSplitter_WriteReg, XDUSP_GENR_CTL_OFFSET, XDUSP_GENR_CTL_RST_MASK.
Referenced by XDualSplitter_CfgInitialize.
void XDualSplitter_SetImageSize(XDualSplitter *InstancePtr, u16 Height, u16 Width)
This function sets the image size (width x height) of the Dual Splitter core.
InstancePtr is a pointer to the XDualSplitter core instance. Height specifies the height of the input image that needs to be set within the range [0, 2160]. Width specifies the width of the input image that needs to be set within the range [0, 3840]. None. None.
References XDualSplitter_Config::BaseAddress, XDualSplitter::Config, XDualSplitter_WriteReg, XDUSP_MAX_IMG_HEIGHT, XDUSP_MAX_IMG_WIDTH, XDUSP_TIME_CTL_HEIGHT_MASK, XDUSP_TIME_CTL_HEIGHT_SHIFT, XDUSP_TIME_CTL_OFFSET, XDUSP_TIME_CTL_WIDTH_MASK.
Referenced by XDualSplitter_SelfTest, XDualSplitterExample.
void XDualSplitter_GetImageSize(XDualSplitter *InstancePtr, u16 *Height, u16 *Width)
This function gets the image size (width x height) of the Dual Splitter core.
InstancePtr is a pointer to the XDualSplitter core instance. Height specifies a pointer to the 16-bit variable that will be filled with height which is in the range [0, 2160]. Width specifies a pointer to the 16-bit variable that will be filled with width which is in the range [0, 3840]. None. None.
References XDualSplitter_Config::BaseAddress, XDualSplitter::Config, XDualSplitter_ReadReg, XDUSP_TIME_CTL_HEIGHT_SHIFT, XDUSP_TIME_CTL_OFFSET, XDUSP_TIME_CTL_WIDTH_MASK.
Referenced by XDualSplitter_SelfTest.
void XDualSplitter_SetImgParam(XDualSplitter *InstancePtr, u8 InputSamples, u8 OutputSamples, u8 ImageSegments, u8 Overlap)
This function sets the image parameters to split into multiple segments.
InstancePtr is a pointer to the XDualSplitter core instance. InputSamples specifies the number of input samples per clock that needs to be set within the range [0, 4]. OutputSamples specifies the number of output samples per clock that needs to be set within the range [0, 4]. ImageSegments specifies the number of image segments that needs to be set within the range [0, 4]. Overlap specifies the overlap of the samples in the segments. None. None.
References XDualSplitter_Config::BaseAddress, XDualSplitter::Config, XDualSplitter_WriteReg, XDUSP_CORE_CTL_IMG_SEG_MASK, XDUSP_CORE_CTL_IMG_SEG_SHIFT, XDUSP_CORE_CTL_IN_SAMPLES_MASK, XDUSP_CORE_CTL_OFFSET, XDUSP_CORE_CTL_OUT_SAMPLES_MASK, XDUSP_CORE_CTL_OUT_SAMPLES_SHIFT, XDUSP_CORE_CTL_OVRLAP_SEG_MASK, XDUSP_CORE_CTL_OVRLAP_SEG_SHIFT, XDUSP_MAX_INPUT_SAMPLES, XDUSP_MAX_OUTPUT_SAMPLES, XDUSP_MAX_SEGMENTS.
Referenced by XDualSplitterExample.
void XDualSplitter_GetImgParam(XDualSplitter *InstancePtr, u8 *InputSamples, u8 *OutputSamples, u8 *ImageSegments, u8 *Overlap)
This function gets the image parameters of the Dual Splitter core.
InstancePtr is a pointer to the XDualSplitter core instance. InputSamples specifies a pointer to the 8-bit variable that will be filled with number of input samples which is in the range [0, 4] OutputSamples specifies a pointer to the 8-bit variable that will be filled with number of output samples which is in the range [0, 4] ImageSegments specifies a pointer to the 8-bit variable that will be filled with number of image segments which is in the range [0, 4] Overlap specifies a pointer to the 8-bit variable that will be filled with number of samples overlapping the segments. None. None.
References XDualSplitter_Config::BaseAddress, XDualSplitter::Config, XDualSplitter_ReadReg, XDUSP_CORE_CTL_IMG_SEG_MASK, XDUSP_CORE_CTL_IMG_SEG_SHIFT, XDUSP_CORE_CTL_IN_SAMPLES_MASK, XDUSP_CORE_CTL_OFFSET, XDUSP_CORE_CTL_OUT_SAMPLES_MASK, XDUSP_CORE_CTL_OUT_SAMPLES_SHIFT, XDUSP_CORE_CTL_OVRLAP_SEG_MASK, XDUSP_CORE_CTL_OVRLAP_SEG_SHIFT.