xv_hdmirx.c
MAXSCDCADDRESS
static void StubCallback(void *CallbackRef)
This function is a stub for the asynchronous callback.
The stub is here in case the upper layer forgot to set the handlers. On initialization, all handlers are set to this callback. It is considered an error for this handler to be invoked. CallbackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. None. None.
int XV_HdmiRx_CfgInitialize(XV_HdmiRx *InstancePtr, XV_HdmiRx_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the HDMI RX core.
This function must be called prior to using the HDMI RX core. Initialization of the HDMI RX includes setting up the instance data, and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the XHdmiRx core instance. CfgPtr points to the configuration structure associated with the HDMI RX core. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if XV_HdmiRx_CfgInitialize was successful.XST_FAILURE if HDMI RX PIO ID mismatched. None.
References XV_HdmiRx::AudCallback, XV_HdmiRx::AuxCallback, XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HdmiRx::ConnectCallback, XV_HdmiRx::DdcCallback, XV_HdmiRx::HdcpCallback, XV_HdmiRx::IsAudCallbackSet, XV_HdmiRx::IsAuxCallbackSet, XV_HdmiRx::IsConnectCallbackSet, XV_HdmiRx_Stream::IsConnected, XV_HdmiRx::IsDdcCallbackSet, XV_HdmiRx::IsHdcpCallbackSet, XV_HdmiRx::IsLinkErrorCallbackSet, XV_HdmiRx::IsLnkStaCallbackSet, XV_HdmiRx::IsModeCallbackSet, XV_HdmiRx::IsPhyErrorCallbackSet, XV_HdmiRx::IsReady, XV_HdmiRx::IsStreamDownCallbackSet, XV_HdmiRx::IsStreamInitCallbackSet, XV_HdmiRx::IsStreamUpCallbackSet, XV_HdmiRx::IsSyncLossCallbackSet, XV_HdmiRx::IsTmdsClkRatioCallbackSet, XV_HdmiRx::IsVicErrorCallbackSet, XV_HdmiRx::LinkErrorCallback, XV_HdmiRx::LnkStaCallback, XV_HdmiRx::ModeCallback, XV_HdmiRx::PhyErrorCallback, XV_HdmiRx::Stream, XV_HdmiRx::StreamDownCallback, XV_HdmiRx::StreamInitCallback, XV_HdmiRx::StreamUpCallback, XV_HdmiRx::SyncLossCallback, XV_HdmiRx::TmdsClkRatioCallback, XV_HdmiRx::VicErrorCallback, XV_HdmiRx_AudioDisable, XV_HdmiRx_AudioIntrEnable, XV_HdmiRx_AuxDisable, XV_HdmiRx_AuxIntrEnable, XV_HdmiRx_Clear, XV_HdmiRx_DdcDisable, XV_HdmiRx_DdcEnable, XV_HdmiRx_DdcScdcClear, XV_HdmiRx_DdcScdcEnable, XV_HdmiRx_GetTime16Ms, XV_HdmiRx_LnkstaDisable, XV_HdmiRx_LnkstaEnable, XV_HDMIRX_MASK_16, XV_HDMIRX_PIO_ID, XV_HDMIRX_PIO_ID_OFFSET, XV_HDMIRX_PIO_IN_BRDG_OVERFLOW_MASK, XV_HDMIRX_PIO_IN_DET_MASK, XV_HDMIRX_PIO_IN_EVT_FE_OFFSET, XV_HDMIRX_PIO_IN_EVT_RE_OFFSET, XV_HDMIRX_PIO_IN_LNK_RDY_MASK, XV_HDMIRX_PIO_IN_MODE_MASK, XV_HDMIRX_PIO_IN_SCDC_SCRAMBLER_ENABLE_MASK, XV_HDMIRX_PIO_IN_SCDC_TMDS_CLOCK_RATIO_MASK, XV_HDMIRX_PIO_IN_VID_RDY_MASK, XV_HdmiRx_PioDisable, XV_HdmiRx_PioEnable, XV_HdmiRx_PioIntrDisable, XV_HdmiRx_PioIntrEnable, XV_HdmiRx_ReadReg, XV_HDMIRX_SCDC_BRAM_OFFSET, XV_HDMIRX_SHIFT_16, XV_HdmiRx_TmrDisable, XV_HdmiRx_TmrEnable, XV_HdmiRx_TmrIntrDisable, XV_HdmiRx_TmrIntrEnable, XV_HdmiRx_VtdDisable, XV_HdmiRx_VtdIntrDisable, XV_HdmiRx_VtdSetTimebase, XV_HdmiRx_WriteReg.
void XV_HdmiRx_Clear(XV_HdmiRx *InstancePtr)
This function clears the HDMI RX variables and sets them to the defaults.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. This is required after a reset or init.
References XV_HdmiRx_AudioStream::Active, XV_HdmiRx::AudCts, XV_HdmiRx::AudFormat, XV_HdmiRx_Stream::Audio, XV_HdmiRx::AudN, XV_HdmiRx::Aux, XV_HdmiRx_AudioStream::Channels, XV_HdmiRx_Stream::IsHdmi, XV_HdmiRx::IsStreamDownCallbackSet, XV_HdmiRx_Stream::State, XV_HdmiRx::Stream, XV_HdmiRx::StreamDownCallback, XV_HdmiRx::StreamDownRef, XV_HdmiRx_Stream::Vic, XV_HdmiRx_Stream::Video, XV_HDMIRX_STATE_STREAM_DOWN.
Referenced by XV_HdmiRx_CfgInitialize.
int XV_HdmiRx_SetStream(XV_HdmiRx *InstancePtr, XVidC_PixelsPerClock Ppc, u32 Clock)
This function sets the HDMI RX stream parameters.
InstancePtr is a pointer to the XV_HdmiRx core instance. Ppc specifies the pixel per clock. 1 = XVIDC_PPC_12 = XVIDC_PPC_24 = XVIDC_PPC_4 Clock specifies reference pixel clock frequency. XST_SUCCESS is always returned. None.
References XV_HdmiRx_Stream::RefClk, XV_HdmiRx::Stream, XV_HdmiRx_Stream::Video, XV_HdmiRx_SetPixelRate.
void XV_HdmiRx_INT_VRST(XV_HdmiRx *InstancePtr, u8 Reset)
This function asserts or releases the HDMI RX Internal VRST.
InstancePtr is a pointer to the XV_HdmiRx core instance. Reset specifies TRUE/FALSE value to either assert or release HDMI RX Internal VRST. None. The reset output of the PIO is inverted. When the system is in reset, the PIO output is cleared and this will reset the HDMI RX. Therefore, clearing the PIO reset output will assert the HDMI Internal video reset. C-style signature: void XV_HdmiRx_INT_VRST(XV_HdmiRx *InstancePtr, u8 Reset)
References XV_HDMIRX_PIO_OUT_CLR_OFFSET, XV_HDMIRX_PIO_OUT_INT_VRST_MASK, XV_HDMIRX_PIO_OUT_SET_OFFSET, XV_HdmiRx_WriteReg.
void XV_HdmiRx_INT_LRST(XV_HdmiRx *InstancePtr, u8 Reset)
This function asserts or releases the HDMI RX Internal LRST.
InstancePtr is a pointer to the XV_HdmiRx core instance. Reset specifies TRUE/FALSE value to either assert or release HDMI RX Internal LRST. None. The reset output of the PIO is inverted. When the system is in reset, the PIO output is cleared and this will reset the HDMI RX. Therefore, clearing the PIO reset output will assert the HDMI Internal link reset. C-style signature: void XV_HdmiRx_INT_VRST(XV_HdmiRx *InstancePtr, u8 Reset)
References XV_HDMIRX_PIO_OUT_CLR_OFFSET, XV_HDMIRX_PIO_OUT_INT_LRST_MASK, XV_HDMIRX_PIO_OUT_SET_OFFSET, XV_HdmiRx_WriteReg.
void XV_HdmiRx_EXT_VRST(XV_HdmiRx *InstancePtr, u8 Reset)
This function asserts or releases the HDMI RX External VRST.
InstancePtr is a pointer to the XV_HdmiRx core instance. Reset specifies TRUE/FALSE value to either assert or release HDMI RX External VRST. None. The reset output of the PIO is inverted. When the system is in reset, the PIO output is cleared and this will reset the HDMI RX. Therefore, clearing the PIO reset output will assert the HDMI external video reset. C-style signature: void XV_HdmiRx_EXT_VRST(XV_HdmiRx *InstancePtr, u8 Reset)
References XV_HDMIRX_PIO_OUT_CLR_OFFSET, XV_HDMIRX_PIO_OUT_EXT_VRST_MASK, XV_HDMIRX_PIO_OUT_SET_OFFSET, XV_HdmiRx_WriteReg.
void XV_HdmiRx_EXT_SYSRST(XV_HdmiRx *InstancePtr, u8 Reset)
This function asserts or releases the HDMI RX External SYSRST.
InstancePtr is a pointer to the XV_HdmiRx core instance. Reset specifies TRUE/FALSE value to either assert or release HDMI RX External SYSRST. None. The reset output of the PIO is inverted. When the system is in reset, the PIO output is cleared and this will reset the HDMI RX. Therefore, clearing the PIO reset output will assert the HDMI External system reset. C-style signature: void XV_HdmiRx_EXT_SYSRST(XV_HdmiRx *InstancePtr, u8 Reset)
References XV_HDMIRX_PIO_OUT_CLR_OFFSET, XV_HDMIRX_PIO_OUT_EXT_SYSRST_MASK, XV_HDMIRX_PIO_OUT_SET_OFFSET, XV_HdmiRx_WriteReg.
int XV_HdmiRx_SetPixelRate(XV_HdmiRx *InstancePtr)
This function sets the pixel rate.
InstancePtr is a pointer to the XV_HdmiRx core instance. XST_SUCCESS is always returned. None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HdmiRx::Stream, XV_HdmiRx_Stream::Video, XV_HDMIRX_PIO_OUT_MSK_OFFSET, XV_HDMIRX_PIO_OUT_OFFSET, XV_HDMIRX_PIO_OUT_PIXEL_RATE_MASK, XV_HDMIRX_PIO_OUT_PIXEL_RATE_SHIFT, XV_HdmiRx_WriteReg.
Referenced by XV_HdmiRx_SetStream.
void XV_HdmiRx_SetColorFormat(XV_HdmiRx *InstancePtr)
This function sets the color format.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HdmiRx::Stream, XV_HdmiRx_Stream::Video, XV_HDMIRX_PIO_OUT_COLOR_SPACE_MASK, XV_HDMIRX_PIO_OUT_COLOR_SPACE_SHIFT, XV_HDMIRX_PIO_OUT_MSK_OFFSET, XV_HDMIRX_PIO_OUT_OFFSET, XV_HdmiRx_WriteReg.
int XV_HdmiRx_SetHpd(XV_HdmiRx *InstancePtr, u8 SetClr)
This function enables/clear Hot-Plug-Detect.
InstancePtr is a pointer to the XV_HdmiRx core instance. SetClr specifies TRUE/FALSE value to either enable or clear HPD respectively. XST_SUCCESS is always returned. None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HdmiRx_DdcScdcClear, XV_HdmiRx_DdcScdcSet, XV_HDMIRX_PIO_OUT_CLR_OFFSET, XV_HDMIRX_PIO_OUT_HPD_MASK, XV_HDMIRX_PIO_OUT_SET_OFFSET, XV_HdmiRx_WriteReg.
void XV_HdmiRx_WriteScdcRegister(XV_HdmiRx *InstancePtr, u8 address, u8 data)
This function write data to SCDC register.
InstancePtr is a pointer to the XV_HdmiRx core instance. address specifies the SCDC register address to write to. data specifies the data to be written. None. SCDC register 0x01,0x02,0x10,0x20,0x21,0x40 are handled by H/W directly. These registers should not be written by User application.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HDMIRX_SCDC_BRAM_OFFSET, XV_HdmiRx_WriteReg.
u32 XV_HdmiRx_GetLinkStatus(XV_HdmiRx *InstancePtr, u8 Type)
This function provides status of the HDMI RX core Link Status peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. Type specifies one of the type for which status to be provided: 0 = Link error counter for channel 0.1 = Link error counter for channel 1.2 = Link error counter for channel 2. Link status of the HDMI RX core link. None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HDMIRX_LNKSTA_LNK_ERR0_OFFSET, XV_HdmiRx_ReadReg.
int XV_HdmiRx_IsLinkStatusErrMax(XV_HdmiRx *InstancePtr)
This function provides status of one of the link error counters reached the maximum value.
InstancePtr is a pointer to the XV_HdmiRx core instance. TRUE = Maximum error counter reached.FALSE = Maximum error counter not reached. None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HDMIRX_LNKSTA_STA_ERR_MAX_MASK, XV_HDMIRX_LNKSTA_STA_OFFSET, XV_HdmiRx_ReadReg.
void XV_HdmiRx_ClearLinkStatus(XV_HdmiRx *InstancePtr)
This function clears the link error counters.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HDMIRX_LNKSTA_CTRL_CLR_OFFSET, XV_HDMIRX_LNKSTA_CTRL_ERR_CLR_MASK, XV_HDMIRX_LNKSTA_CTRL_SET_OFFSET, XV_HdmiRx_WriteReg.
u32 XV_HdmiRx_GetAcrCts(XV_HdmiRx *InstancePtr)
This function provides audio clock regenerating CTS (Cycle-Time Stamp) value at the HDMI sink device.
InstancePtr is a pointer to the XV_HdmiRx core instance. Audio clock CTS value. None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HDMIRX_AUD_CTS_OFFSET, XV_HdmiRx_ReadReg.
u32 XV_HdmiRx_GetAcrN(XV_HdmiRx *InstancePtr)
This function provides audio clock regenerating factor N value.
InstancePtr is a pointer to the XV_HdmiRx core instance. ACR N value. None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HDMIRX_AUD_N_OFFSET, XV_HdmiRx_ReadReg.
u16 XV_HdmiRx_DdcGetEdidWords(XV_HdmiRx *InstancePtr)
This function gets the size of the EDID buffer of the DDC slave.
InstancePtr is a pointer to the XV_HdmiRx core instance. EDID buffer size None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HDMIRX_DDC_EDID_STA_OFFSET, XV_HDMIRX_DDC_STA_EDID_WORDS_MASK, XV_HDMIRX_DDC_STA_EDID_WORDS_SHIFT, XV_HdmiRx_ReadReg.
Referenced by XV_HdmiRx_DdcLoadEdid.
int XV_HdmiRx_DdcLoadEdid(XV_HdmiRx *InstancePtr, u8 *EdidData, u16 Length)
This function loads the EDID data into the DDC slave.
InstancePtr is a pointer to the XV_HdmiRx core instance. EdidData is a pointer to the EDID data array. Length is the length, in bytes, of the EDID array. XST_SUCCESS if the EDID data was loaded successfullyXST_FAILURE if the EDID data load failed None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HDMIRX_DDC_CTRL_EDID_EN_MASK, XV_HDMIRX_DDC_CTRL_SET_OFFSET, XV_HDMIRX_DDC_EDID_DATA_OFFSET, XV_HDMIRX_DDC_EDID_WP_OFFSET, XV_HdmiRx_DdcGetEdidWords, XV_HdmiRx_WriteReg.
void XV_HdmiRx_DdcHdcpSetAddress(XV_HdmiRx *InstancePtr, u32 Address)
This function sets the HDCP address in the DDC peripheral.
This is implemented as a function and not a macro, so the HDCP driver can bind the function call with a handler. InstancePtr is a pointer to the XHdmi_Rx core instance. Address is the HDCP address. None. C-style signature: void XHdmiRx_DdcHdcpSetAddress(XHdmi_Rx *InstancePtr, u8 Address)
References XV_HDMIRX_DDC_HDCP_ADDRESS_OFFSET, XV_HdmiRx_WriteReg.
void XV_HdmiRx_DdcHdcpWriteData(XV_HdmiRx *InstancePtr, u32 Data)
This function writes HDCP data in the DDC peripheral.
This is implemented as a function and not a macro, so the HDCP driver can bind the function call with a handler. InstancePtr is a pointer to the XHdmi_Rx core instance. Data is the HDCP data to be written. None. C-style signature: void XHdmiRx_DdcHdcpWriteData(XHdmi_Rx *InstancePtr, u8 Data)
References XV_HDMIRX_DDC_HDCP_DATA_OFFSET, XV_HdmiRx_WriteReg.
u32 XV_HdmiRx_DdcHdcpReadData(XV_HdmiRx *InstancePtr)
This function reads HDCP data from the DDC peripheral.
This is implemented as a function and not a macro, so the HDCP driver can bind the function call with a handler. InstancePtr is a pointer to the XHdmi_Rx core instance. Returns the HDCP data read from the DDC peripheral. C-style signature: u32 XHdmiRx_DdcHdcpReadData(XHdmi_Rx *InstancePtr)
References XV_HDMIRX_DDC_HDCP_DATA_OFFSET, XV_HdmiRx_ReadReg.
u16 XV_HdmiRx_DdcGetHdcpWriteMessageBufferWords(XV_HdmiRx *InstancePtr)
This function gets the number of bytes of the HDCP 2.2 write buffer in the DDC slave.
InstancePtr is a pointer to the XHdmi_Rx core instance. HDCP 2.2 write buffer words None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HDMIRX_DDC_HDCP_STA_OFFSET, XV_HDMIRX_DDC_STA_HDCP_WMSG_WORDS_MASK, XV_HDMIRX_DDC_STA_HDCP_WMSG_WORDS_SHIFT, XV_HdmiRx_ReadReg.
int XV_HdmiRx_DdcIsHdcpWriteMessageBufferEmpty(XV_HdmiRx *InstancePtr)
This function returns the status of the HDCP 2.2 write buffer in the DDC slave.
InstancePtr is a pointer to the XHdmi_Rx core instance. TRUE = HDCP 2.2 message buffer is empty.FALSE = HDCP 2.2 message buffer contains data. None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HDMIRX_DDC_HDCP_STA_OFFSET, XV_HDMIRX_DDC_STA_HDCP_WMSG_EP_MASK, XV_HdmiRx_ReadReg.
u16 XV_HdmiRx_DdcGetHdcpReadMessageBufferWords(XV_HdmiRx *InstancePtr)
This function gets the number of bytes of the HDCP 2.2 read buffer in the DDC slave.
InstancePtr is a pointer to the XHdmi_Rx core instance. HDCP 2.2 read buffer words None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HDMIRX_DDC_HDCP_STA_OFFSET, XV_HDMIRX_DDC_STA_HDCP_RMSG_WORDS_MASK, XV_HDMIRX_DDC_STA_HDCP_RMSG_WORDS_SHIFT, XV_HdmiRx_ReadReg.
int XV_HdmiRx_DdcIsHdcpReadMessageBufferEmpty(XV_HdmiRx *InstancePtr)
This function returns the status of the HDCP 2.2 read message buffer in the DDC slave.
InstancePtr is a pointer to the XHdmi_Rx core instance. TRUE = HDCP 2.2 message buffer is empty.FALSE = HDCP 2.2 message buffer contains data. None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HDMIRX_DDC_HDCP_STA_OFFSET, XV_HDMIRX_DDC_STA_HDCP_RMSG_EP_MASK, XV_HdmiRx_ReadReg.
void XV_HdmiRx_DebugInfo(XV_HdmiRx *InstancePtr)
This function prints stream and timing information on STDIO/Uart console.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. None.
References XV_HdmiRx::Stream, XV_HdmiRx_Stream::Video.
int XV_HdmiRx_IsStreamUp(XV_HdmiRx *InstancePtr)
This function provides status of the stream.
InstancePtr is a pointer to the XV_HdmiRx core instance. TRUE = Stream is up.FALSE = Stream is down. None.
References XV_HdmiRx_Stream::State, XV_HdmiRx::Stream, XV_HDMIRX_STATE_STREAM_UP.
int XV_HdmiRx_IsStreamScrambled(XV_HdmiRx *InstancePtr)
This function provides the stream scrambler status.
InstancePtr is a pointer to the XV_HdmiRx core instance. TRUE = Stream is scrambled.FALSE = Stream is not scrambled. None.
References XV_HdmiRx_Stream::IsScrambled, XV_HdmiRx::Stream.
int XV_HdmiRx_IsStreamConnected(XV_HdmiRx *InstancePtr)
This function provides the stream connected status.
InstancePtr is a pointer to the XV_HdmiRx core instance. TRUE = Stream is connected.FALSE = Stream is connected. None.
References XV_HdmiRx_Stream::IsConnected, XV_HdmiRx::Stream.
int XV_HdmiRx_GetTmdsClockRatio(XV_HdmiRx *InstancePtr)
This function gets the SCDC TMDS clock ratio bit.
InstancePtr is a pointer to the XV_HdmiRx core instance. TRUE = TMDS clock ratio bit is set.FALSE = TMDS clock ratio bit is cleared. None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HDMIRX_PIO_IN_OFFSET, XV_HDMIRX_PIO_IN_SCDC_TMDS_CLOCK_RATIO_MASK, XV_HdmiRx_ReadReg.
u8 XV_HdmiRx_GetAviVic(XV_HdmiRx *InstancePtr)
This function returns the AVI VIC (captured by the AUX peripheral)
InstancePtr is a pointer to the XV_HdmiRx core instance. The AVI VIC code. None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HDMIRX_AUX_STA_AVI_VIC_MASK, XV_HDMIRX_AUX_STA_AVI_VIC_SHIFT, XV_HDMIRX_AUX_STA_OFFSET, XV_HdmiRx_ReadReg.
Referenced by XV_HdmiRx_GetVideoProperties.
XVidC_ColorFormat XV_HdmiRx_GetAviColorSpace(XV_HdmiRx *InstancePtr)
This function returns the AVI colorspace (captured by the AUX peripheral)
InstancePtr is a pointer to the XV_HdmiRx core instance. The AVI colorspace value. None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HDMIRX_AUX_STA_AVI_CS_MASK, XV_HDMIRX_AUX_STA_AVI_CS_SHIFT, XV_HDMIRX_AUX_STA_OFFSET, XV_HdmiRx_ReadReg.
Referenced by XV_HdmiRx_GetVideoProperties.
XVidC_ColorDepth XV_HdmiRx_GetGcpColorDepth(XV_HdmiRx *InstancePtr)
This function returns the GCP color depth (captured by the AUX peripheral)
InstancePtr is a pointer to the XV_HdmiRx core instance. The GCP color depth. None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HDMIRX_AUX_STA_GCP_CD_MASK, XV_HDMIRX_AUX_STA_GCP_CD_SHIFT, XV_HDMIRX_AUX_STA_OFFSET, XV_HdmiRx_ReadReg.
Referenced by XV_HdmiRx_GetVideoProperties.
u32 XV_HdmiRx_Divide(u32 Dividend, u32 Divisor)
This function calculates the divider for the frame calculation.
Dividend is the dividend value to use in the calculation. Divisor is the divisor value to use in the calculation. The result of the calculation. None.
Referenced by XV_HdmiRx_GetVideoTiming.
XVidC_VideoMode XV_HdmiRx_LookupVmId(u8 Vic)
This function searches for the video mode based on the vic.
Vic Vic defined in the VIC table. None.
int XV_HdmiRx_GetVideoProperties(XV_HdmiRx *InstancePtr)
This function reads the video properties from the aux peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HdmiRx::Stream, XV_HdmiRx_Stream::Vic, XV_HdmiRx_Stream::Video, XV_HDMIRX_AUX_STA_AVI_MASK, XV_HDMIRX_AUX_STA_OFFSET, XV_HdmiRx_GetAviColorSpace, XV_HdmiRx_GetAviVic, XV_HdmiRx_GetGcpColorDepth, XV_HdmiRx_ReadReg.
int XV_HdmiRx_GetVideoTiming(XV_HdmiRx *InstancePtr)
This function reads the video timing from the VTD peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HdmiRx_Stream::PixelClk, XV_HdmiRx::Stream, XV_HdmiRx_Stream::Video, XV_HdmiRx_Divide, XV_HdmiRx_ReadReg, XV_HDMIRX_VTD_ACT_LIN_OFFSET, XV_HDMIRX_VTD_ACT_PIX_OFFSET, XV_HDMIRX_VTD_HBP_OFFSET, XV_HDMIRX_VTD_HFP_OFFSET, XV_HDMIRX_VTD_HSW_OFFSET, XV_HDMIRX_VTD_STA_FMT_MASK, XV_HDMIRX_VTD_STA_HS_POL_MASK, XV_HDMIRX_VTD_STA_OFFSET, XV_HDMIRX_VTD_STA_VS_POL_MASK, XV_HDMIRX_VTD_TOT_LIN_OFFSET, XV_HDMIRX_VTD_TOT_PIX_OFFSET, XV_HDMIRX_VTD_VBP_OFFSET, XV_HDMIRX_VTD_VFP_OFFSET, XV_HDMIRX_VTD_VSW_OFFSET.