xv_hdmirx.h
XV_HdmiRx_HandlerType
A connect event interrupt type.
XV_HDMIRX_H_
Prevent circular inclusions by using protection macros.
XV_HdmiRx_GetTime10Ms
This macro returns the clock cycles required to count up to 10MS with respect to AXI Lite Frequency.
InstancePtr is a pointer to the XV_HdmiRX core instance. None.
XV_HdmiRx_GetTime16Ms
This macro returns the clock cycles required to count up to 16MS with respect to AXI Lite Frequency.
InstancePtr is a pointer to the XV_HdmiRX core instance. None.
Referenced by XV_HdmiRx_CfgInitialize.
XV_HdmiRx_GetTime200Ms
This macro returns the clock cycles required to count up to 200MS with respect to AXI Lite Frequency.
InstancePtr is a pointer to the XV_HdmiRX core instance. None.
XV_HdmiRx_GetTime500Ms
This macro returns the clock cycles required to count up to 500MS with respect to AXI Lite Frequency.
InstancePtr is a pointer to the XV_HdmiRX core instance. None. None.
XV_HdmiRx_GetVersion
This macro reads the RX version.
InstancePtr is a pointer to the XHdmi_RX core instance. RX version. *note C-style signature: u32 XV_HdmiRx_GetVersion(XV_HdmiRx *InstancePtr)
XV_HdmiRx_Reset
This macro asserts or clears the HDMI RX reset.
InstancePtr is a pointer to the XV_HdmiRx core instance. Reset specifies TRUE/FALSE value to either assert or release HDMI RX reset. None. The reset output of the PIO is inverted. When the system is in reset, the PIO output is cleared and this will reset the HDMI RX. Therefore, clearing the PIO reset output will assert the HDMI link and video reset. C-style signature: void XV_HdmiRx_Reset(XV_HdmiRx *InstancePtr, u8 Reset)
XV_HdmiRx_LinkEnable
This macro asserts or clears the HDMI RX link enable.
InstancePtr is a pointer to the XV_HdmiRx core instance. SetClr specifies TRUE/FALSE value to either assert or release HDMI RX link enable. None. C-style signature: void XV_HdmiRx_Reset(XV_HdmiRx *InstancePtr, u8 SetClr)
XV_HdmiRx_VideoEnable
This macro asserts or clears the HDMI RX video enable.
InstancePtr is a pointer to the XV_HdmiRx core instance. SetClr specifies TRUE/FALSE value to either assert or release HDMI RX video enable. None. C-style signature: void XV_HdmiRx_Reset(XV_HdmiRx *InstancePtr, u8 SetClr)
XV_HdmiRx_SetScrambler
This macro controls the HDMI RX Scrambler.
InstancePtr is a pointer to the XHdmi_Rx core instance. SetClr specifies TRUE/FALSE value to either enable or disable the scrambler. None. C-style signature: void XV_HdmiRx_SetScrambler(XV_HdmiRx *InstancePtr, u8 SetClr)
XV_HdmiRx_Bridge_yuv420
This macro controls the YUV420 mode for video bridge.
InstancePtr is a pointer to the XHdmi_Rx core instance. SetClr specifies TRUE/FALSE value to either enable or disable the YUV 420 Support. None. C-style signature: void XV_HdmiRx_Bridge_yuv420(XV_HdmiRx *InstancePtr, u8 SetClr)
XV_HdmiRx_Bridge_pixel
This macro controls the Pixel Drop mode for video bridge.
InstancePtr is a pointer to the XHdmi_Rx core instance. SetClr specifies TRUE/FALSE value to either enable or disable the Pixel Repetition. None. C-style signature: void XV_HdmiRx_Bridge_pixel(XV_HdmiRx *InstancePtr, u8 SetClr)
XV_HdmiRx_AxisEnable
This macro asserts or clears the AXIS enable output port.
InstancePtr is a pointer to the XV_HdmiRx core instance. Enable specifies TRUE/FALSE value to either enable or disable the AXIS output. None. C-style signature: void XV_HdmiRx_AxisEnable(InstancePtr, Enable)
XV_HdmiRx_PioEnable
This macro enables the HDMI RX PIO peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. C-style signature: void XV_HdmiRx_PioEnable(XV_HdmiRx *InstancePtr)
Referenced by XV_HdmiRx_CfgInitialize.
XV_HdmiRx_PioDisable
This macro disables the HDMI RX PIO peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. C-style signature: void XV_HdmiRx_PioDisable(XV_HdmiRx *InstancePtr)
Referenced by XV_HdmiRx_CfgInitialize.
XV_HdmiRx_PioIntrEnable
This macro enables interrupts in the HDMI RX PIO peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. C-style signature: void XV_HdmiRx_PioIntrEnable(XV_HdmiRx *InstancePtr)
Referenced by XV_HdmiRx_CfgInitialize.
XV_HdmiRx_PioIntrDisable
This macro disables interrupts in the HDMI RX PIO peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. C-style signature: void XV_HdmiRx_PioIntrDisable(XV_HdmiRx *InstancePtr)
Referenced by XV_HdmiRx_CfgInitialize.
XV_HdmiRx_TmrEnable
This macro enables the HDMI RX timer peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. C-style signature: void XV_HdmiRx_TmrEnable(XV_HdmiRx *InstancePtr)
Referenced by XV_HdmiRx_CfgInitialize.
XV_HdmiRx_TmrDisable
This macro disables the HDMI RX timer peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. C-style signature: void XV_HdmiRx_TmrDisable(XV_HdmiRx *InstancePtr)
Referenced by XV_HdmiRx_CfgInitialize.
XV_HdmiRx_TmrIntrEnable
This macro enables interrupts in the HDMI RX timer peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. C-style signature: void XV_HdmiRx_TmrIntrEnable(XV_HdmiRx *InstancePtr)
Referenced by XV_HdmiRx_CfgInitialize.
XV_HdmiRx_TmrIntrDisable
This macro disables interrupt in the HDMI RX timer peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. C-style signature: void XV_HdmiRx_TmrIntrDisable(XV_HdmiRx *InstancePtr)
Referenced by XV_HdmiRx_CfgInitialize.
XV_HdmiRx_TmrStart
This macro starts the HDMI RX timer peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. Value is the timer counter value to load. None. C-style signature: void XV_HdmiRx_TmrStart(XV_HdmiRx *InstancePtr, u32 Value)
XV_HdmiRx_VtdEnable
This macro enables the HDMI RX Timing Detector peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. C-style signature: void XV_HdmiRx_VtdEnable(XV_HdmiRx *InstancePtr)
XV_HdmiRx_VtdDisable
This macro disables the HDMI RX Timing Detector peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. C-style signature: void XV_HdmiRx_VtdDisable(XV_HdmiRx *InstancePtr)
Referenced by XV_HdmiRx_CfgInitialize.
XV_HdmiRx_VtdIntrEnable
This macro enables interrupt in the HDMI RX Timing Detector peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. C-style signature: void XV_HdmiRx_VtdIntrEnable(XV_HdmiRx *InstancePtr)
XV_HdmiRx_VtdIntrDisable
This macro disables interrupt in the HDMI RX Timing Detector peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. C-style signature: void XV_HdmiRx_VtdIntrDisable(XV_HdmiRx *InstancePtr)
Referenced by XV_HdmiRx_CfgInitialize.
XV_HdmiRx_VtdSetTimebase
This macro sets the timebase in the HDMI RX Timing Detector peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. Value is the timebase value to set. None. C-style signature: void XV_HdmiRx_VtdSetTimebase(XV_HdmiRx *InstancePtr, u32 Value)
Referenced by XV_HdmiRx_CfgInitialize.
XV_HdmiRx_DdcEnable
This macro enables the HDMI RX Display Data Channel (DDC) peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. C-style signature: void XV_HdmiRx_DdcEnable(XV_HdmiRx *InstancePtr)
Referenced by XV_HdmiRx_CfgInitialize.
XV_HdmiRx_DdcScdcEnable
This macro enables the SCDC in the DDC peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. C-style signature: void XV_HdmiRx_DdcScdcEnable(XV_HdmiRx *InstancePtr)
Referenced by XV_HdmiRx_CfgInitialize.
XV_HdmiRx_DdcHdcpEnable
This macro enables the HDCP in the DDC peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. C-style signature: void XV_HdmiRx_DdcHdcpEnable(XV_HdmiRx *InstancePtr)
XV_HdmiRx_DdcHdcpDisable
XV_HdmiRx_DdcHdcp14Mode
This macro sets the DDC peripheral into HDCP 1.4 mode.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. C-style signature: void XV_HdmiRx_DdcHdcp14Mode(XV_HdmiRx *InstancePtr)
XV_HdmiRx_DdcHdcp22Mode
This macro sets the DDC peripheral into HDCP 2.2 mode.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. C-style signature: void XV_HdmiRx_DdcHdcp22Mode(XV_HdmiRx *InstancePtr)
XV_HdmiRx_DdcDisable
This macro disables the HDMI RX Display Data Channel (DDC) peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. C-style signature: void XV_HdmiRx_DdcDisable(XV_HdmiRx *InstancePtr)
Referenced by XV_HdmiRx_CfgInitialize.
XV_HdmiRx_DdcIntrEnable
This macro enables interrupts in the HDMI RX Display Data Channel (DDC) peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. C-style signature: void XV_HdmiRx_DdcIntrEnable(XV_HdmiRx *InstancePtr)
XV_HdmiRx_DdcIntrDisable
This macro disables interrupts in the HDMI RX Display Data Channel (DDC) peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. C-style signature: void XV_HdmiRx_DdcIntrDisable(XV_HdmiRx *InstancePtr)
XV_HdmiRx_DdcScdcClear
This macro clears the SCDC registers in the DDC peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. C-style signature: void XV_HdmiRx_DdcScdcClear(XV_HdmiRx *InstancePtr)
Referenced by XV_HdmiRx_CfgInitialize, XV_HdmiRx_SetHpd.
XV_HdmiRx_DdcScdcSet
This macro Sets the SCDC registers in the DDC peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. C-style signature: void XV_HdmiRx_DdcScdcClear(XV_HdmiRx *InstancePtr)
Referenced by XV_HdmiRx_SetHpd.
XV_HdmiRx_AuxEnable
This macro enables the HDMI RX Auxiliary (AUX) peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. C-style signature: void XV_HdmiRx_AuxEnable(XV_HdmiRx *InstancePtr)
XV_HdmiRx_AuxDisable
This macro disables the HDMI RX Auxiliary (AUX) peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. C-style signature: void XV_HdmiRx_AuxDisable(XV_HdmiRx *InstancePtr)
Referenced by XV_HdmiRx_CfgInitialize.
XV_HdmiRx_AuxIntrEnable
This macro enables interrupts in the HDMI RX Auxiliary (AUX) peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. C-style signature: void XV_HdmiRx_AuxIntrEnable(XV_HdmiRx *InstancePtr)
Referenced by XV_HdmiRx_CfgInitialize.
XV_HdmiRx_AuxIntrDisable
This macro disables interrupts in the HDMI RX Auxiliary (AUX) peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. C-style signature: void XV_HdmiRx_AuxIntrDisable(XV_HdmiRx *InstancePtr)
XV_HdmiRx_AudioEnable
This macro enables the HDMI RX Audio (AUD) peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. C-style signature: void XV_HdmiRx_AudioEnable(XV_HdmiRx *InstancePtr)
XV_HdmiRx_AudioDisable
This macro disables the HDMI RX Audio (AUD) peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. C-style signature: void XV_HdmiRx_AudioDisable(XV_HdmiRx *InstancePtr)
Referenced by XV_HdmiRx_CfgInitialize.
XV_HdmiRx_AudioIntrEnable
This macro enables interrupts in the HDMI RX Audio (AUD) peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. C-style signature: void XV_HdmiRx_AudioIntrEnable(XV_HdmiRx *InstancePtr)
Referenced by XV_HdmiRx_CfgInitialize.
XV_HdmiRx_AudioIntrDisable
This macro disables interrupts in the HDMI RX Audio (AUD) peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. C-style signature: void XV_HdmiRx_AudioIntrDisable(XV_HdmiRx *InstancePtr)
XV_HdmiRx_LnkstaEnable
This macro enables the HDMI RX Link Status (LNKSTA) peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. C-style signature: void XV_HdmiRx_LinkstaEnable(XV_HdmiRx *InstancePtr)
Referenced by XV_HdmiRx_CfgInitialize.
XV_HdmiRx_LnkstaDisable
This macro disables the HDMI RX Link Status (LNKSTA) peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. C-style signature: void XV_HdmiRx_LinkstaDisable(XV_HdmiRx *InstancePtr)
Referenced by XV_HdmiRx_CfgInitialize.
XV_HdmiRx_LinkIntrEnable
This macro enables interrupt in the HDMI RX Link Status (LNKSTA) peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. C-style signature: void XV_HdmiRx_LinkIntrEnable(XV_HdmiRx *InstancePtr)
XV_HdmiRx_LinkIntrDisable
This macro disable interrupt in the HDMI RX Link Status (LNKSTA) peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. C-style signature: void XV_HdmiRx_LinkIntrDisable(XV_HdmiRx *InstancePtr)
XV_HdmiRx_IsAudioActive
This macro returns true is the audio stream is active else false.
InstancePtr is a pointer to the XV_HdmiRx core instance. TRUE if the audio stream is active, FALSE if it is not. C-style signature: u32 XV_HdmiRx_IsAudioActive(XV_HdmiRx *InstancePtr)
XV_HdmiRx_GetAudioChannels
This macro returns the number of active audio channels.
InstancePtr is a pointer to the XV_HdmiRx core instance. Number of active audio channels. C-style signature: u32 XV_HdmiRx_GetAudioChannels(XV_HdmiRx *InstancePtr)
XV_HdmiRx_DdcHdcpClearWriteMessageBuffer
This macro clears the HDCP write message buffer in the DDC peripheral.
InstancePtr is a pointer to the XHdmi_Rx core instance. None. C-style signature: void XHdmiRx_DdcHdcpClearWriteMessageBuffer(XHdmi_Rx *InstancePtr)
XV_HdmiRx_DdcHdcpClearReadMessageBuffer
This macro clears the HDCP read message buffer in the DDC peripheral.
InstancePtr is a pointer to the XHdmi_Rx core instance. None. C-style signature: void XHdmiRx_DdcHdcpClearReadMessageBuffer(XHdmi_Rx *InstancePtr)
XV_HdmiRx_State
Stream down.
XV_HdmiRx_SyncStatus
Sync Loss.
XV_HdmiRx_AudioFormatType
Unknown audio format.
typedef void(* XV_HdmiRx_Callback)(void *CallbackRef))(void *CallbackRef)
Callback type for interrupt.
CallbackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. None. None.
typedef void(* XV_HdmiRx_HdcpCallback)(void *CallbackRef, int Data))(void *CallbackRef, int Data)
XV_HdmiRx_Config* XV_HdmiRx_LookupConfig(UINTPTR BaseAddress)
This function returns a reference to an XV_HdmiRx_Config structure based on the core id, DeviceId.
The return value will refer to an entry in the device configuration table defined in the xv_hdmirx_g.c file. DeviceId is the unique core ID of the HDMI RX core for the lookup operation. XV_HdmiRx_LookupConfig returns a reference to a config record in the configuration table (in xv_hdmirx_g.c) corresponding to DeviceId, or NULL if no match is found. None.
int XV_HdmiRx_CfgInitialize(XV_HdmiRx *InstancePtr, XV_HdmiRx_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the HDMI RX core.
This function must be called prior to using the HDMI RX core. Initialization of the HDMI RX includes setting up the instance data, and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the XHdmiRx core instance. CfgPtr points to the configuration structure associated with the HDMI RX core. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if XV_HdmiRx_CfgInitialize was successful.XST_FAILURE if HDMI RX PIO ID mismatched. None.
References XV_HdmiRx::AudCallback, XV_HdmiRx::AuxCallback, XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HdmiRx::ConnectCallback, XV_HdmiRx::DdcCallback, XV_HdmiRx::HdcpCallback, XV_HdmiRx::IsAudCallbackSet, XV_HdmiRx::IsAuxCallbackSet, XV_HdmiRx::IsConnectCallbackSet, XV_HdmiRx_Stream::IsConnected, XV_HdmiRx::IsDdcCallbackSet, XV_HdmiRx::IsHdcpCallbackSet, XV_HdmiRx::IsLinkErrorCallbackSet, XV_HdmiRx::IsLnkStaCallbackSet, XV_HdmiRx::IsModeCallbackSet, XV_HdmiRx::IsPhyErrorCallbackSet, XV_HdmiRx::IsReady, XV_HdmiRx::IsStreamDownCallbackSet, XV_HdmiRx::IsStreamInitCallbackSet, XV_HdmiRx::IsStreamUpCallbackSet, XV_HdmiRx::IsSyncLossCallbackSet, XV_HdmiRx::IsTmdsClkRatioCallbackSet, XV_HdmiRx::IsVicErrorCallbackSet, XV_HdmiRx::LinkErrorCallback, XV_HdmiRx::LnkStaCallback, XV_HdmiRx::ModeCallback, XV_HdmiRx::PhyErrorCallback, XV_HdmiRx::Stream, XV_HdmiRx::StreamDownCallback, XV_HdmiRx::StreamInitCallback, XV_HdmiRx::StreamUpCallback, XV_HdmiRx::SyncLossCallback, XV_HdmiRx::TmdsClkRatioCallback, XV_HdmiRx::VicErrorCallback, XV_HdmiRx_AudioDisable, XV_HdmiRx_AudioIntrEnable, XV_HdmiRx_AuxDisable, XV_HdmiRx_AuxIntrEnable, XV_HdmiRx_Clear, XV_HdmiRx_DdcDisable, XV_HdmiRx_DdcEnable, XV_HdmiRx_DdcScdcClear, XV_HdmiRx_DdcScdcEnable, XV_HdmiRx_GetTime16Ms, XV_HdmiRx_LnkstaDisable, XV_HdmiRx_LnkstaEnable, XV_HDMIRX_MASK_16, XV_HDMIRX_PIO_ID, XV_HDMIRX_PIO_ID_OFFSET, XV_HDMIRX_PIO_IN_BRDG_OVERFLOW_MASK, XV_HDMIRX_PIO_IN_DET_MASK, XV_HDMIRX_PIO_IN_EVT_FE_OFFSET, XV_HDMIRX_PIO_IN_EVT_RE_OFFSET, XV_HDMIRX_PIO_IN_LNK_RDY_MASK, XV_HDMIRX_PIO_IN_MODE_MASK, XV_HDMIRX_PIO_IN_SCDC_SCRAMBLER_ENABLE_MASK, XV_HDMIRX_PIO_IN_SCDC_TMDS_CLOCK_RATIO_MASK, XV_HDMIRX_PIO_IN_VID_RDY_MASK, XV_HdmiRx_PioDisable, XV_HdmiRx_PioEnable, XV_HdmiRx_PioIntrDisable, XV_HdmiRx_PioIntrEnable, XV_HdmiRx_ReadReg, XV_HDMIRX_SCDC_BRAM_OFFSET, XV_HDMIRX_SHIFT_16, XV_HdmiRx_TmrDisable, XV_HdmiRx_TmrEnable, XV_HdmiRx_TmrIntrDisable, XV_HdmiRx_TmrIntrEnable, XV_HdmiRx_VtdDisable, XV_HdmiRx_VtdIntrDisable, XV_HdmiRx_VtdSetTimebase, XV_HdmiRx_WriteReg.
void XV_HdmiRx_Clear(XV_HdmiRx *InstancePtr)
This function clears the HDMI RX variables and sets them to the defaults.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. This is required after a reset or init.
References XV_HdmiRx_AudioStream::Active, XV_HdmiRx::AudCts, XV_HdmiRx::AudFormat, XV_HdmiRx_Stream::Audio, XV_HdmiRx::AudN, XV_HdmiRx::Aux, XV_HdmiRx_AudioStream::Channels, XV_HdmiRx_Stream::IsHdmi, XV_HdmiRx::IsStreamDownCallbackSet, XV_HdmiRx_Stream::State, XV_HdmiRx::Stream, XV_HdmiRx::StreamDownCallback, XV_HdmiRx::StreamDownRef, XV_HdmiRx_Stream::Vic, XV_HdmiRx_Stream::Video, XV_HDMIRX_STATE_STREAM_DOWN.
Referenced by XV_HdmiRx_CfgInitialize.
int XV_HdmiRx_SetStream(XV_HdmiRx *InstancePtr, XVidC_PixelsPerClock Ppc, u32 Clock)
This function sets the HDMI RX stream parameters.
InstancePtr is a pointer to the XV_HdmiRx core instance. Ppc specifies the pixel per clock. 1 = XVIDC_PPC_12 = XVIDC_PPC_24 = XVIDC_PPC_4 Clock specifies reference pixel clock frequency. XST_SUCCESS is always returned. None.
References XV_HdmiRx_Stream::RefClk, XV_HdmiRx::Stream, XV_HdmiRx_Stream::Video, XV_HdmiRx_SetPixelRate.
int XV_HdmiRx_IsStreamUp(XV_HdmiRx *InstancePtr)
This function provides status of the stream.
InstancePtr is a pointer to the XV_HdmiRx core instance. TRUE = Stream is up.FALSE = Stream is down. None.
References XV_HdmiRx_Stream::State, XV_HdmiRx::Stream, XV_HDMIRX_STATE_STREAM_UP.
int XV_HdmiRx_IsStreamScrambled(XV_HdmiRx *InstancePtr)
This function provides the stream scrambler status.
InstancePtr is a pointer to the XV_HdmiRx core instance. TRUE = Stream is scrambled.FALSE = Stream is not scrambled. None.
References XV_HdmiRx_Stream::IsScrambled, XV_HdmiRx::Stream.
int XV_HdmiRx_IsStreamConnected(XV_HdmiRx *InstancePtr)
This function provides the stream connected status.
InstancePtr is a pointer to the XV_HdmiRx core instance. TRUE = Stream is connected.FALSE = Stream is connected. None.
References XV_HdmiRx_Stream::IsConnected, XV_HdmiRx::Stream.
int XV_HdmiRx_SetHpd(XV_HdmiRx *InstancePtr, u8 SetClr)
This function enables/clear Hot-Plug-Detect.
InstancePtr is a pointer to the XV_HdmiRx core instance. SetClr specifies TRUE/FALSE value to either enable or clear HPD respectively. XST_SUCCESS is always returned. None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HdmiRx_DdcScdcClear, XV_HdmiRx_DdcScdcSet, XV_HDMIRX_PIO_OUT_CLR_OFFSET, XV_HDMIRX_PIO_OUT_HPD_MASK, XV_HDMIRX_PIO_OUT_SET_OFFSET, XV_HdmiRx_WriteReg.
void XV_HdmiRx_INT_VRST(XV_HdmiRx *InstancePtr, u8 Reset)
This function asserts or releases the HDMI RX Internal VRST.
InstancePtr is a pointer to the XV_HdmiRx core instance. Reset specifies TRUE/FALSE value to either assert or release HDMI RX Internal VRST. None. The reset output of the PIO is inverted. When the system is in reset, the PIO output is cleared and this will reset the HDMI RX. Therefore, clearing the PIO reset output will assert the HDMI Internal video reset. C-style signature: void XV_HdmiRx_INT_VRST(XV_HdmiRx *InstancePtr, u8 Reset)
References XV_HDMIRX_PIO_OUT_CLR_OFFSET, XV_HDMIRX_PIO_OUT_INT_VRST_MASK, XV_HDMIRX_PIO_OUT_SET_OFFSET, XV_HdmiRx_WriteReg.
void XV_HdmiRx_INT_LRST(XV_HdmiRx *InstancePtr, u8 Reset)
This function asserts or releases the HDMI RX Internal LRST.
InstancePtr is a pointer to the XV_HdmiRx core instance. Reset specifies TRUE/FALSE value to either assert or release HDMI RX Internal LRST. None. The reset output of the PIO is inverted. When the system is in reset, the PIO output is cleared and this will reset the HDMI RX. Therefore, clearing the PIO reset output will assert the HDMI Internal link reset. C-style signature: void XV_HdmiRx_INT_VRST(XV_HdmiRx *InstancePtr, u8 Reset)
References XV_HDMIRX_PIO_OUT_CLR_OFFSET, XV_HDMIRX_PIO_OUT_INT_LRST_MASK, XV_HDMIRX_PIO_OUT_SET_OFFSET, XV_HdmiRx_WriteReg.
void XV_HdmiRx_EXT_VRST(XV_HdmiRx *InstancePtr, u8 Reset)
This function asserts or releases the HDMI RX External VRST.
InstancePtr is a pointer to the XV_HdmiRx core instance. Reset specifies TRUE/FALSE value to either assert or release HDMI RX External VRST. None. The reset output of the PIO is inverted. When the system is in reset, the PIO output is cleared and this will reset the HDMI RX. Therefore, clearing the PIO reset output will assert the HDMI external video reset. C-style signature: void XV_HdmiRx_EXT_VRST(XV_HdmiRx *InstancePtr, u8 Reset)
References XV_HDMIRX_PIO_OUT_CLR_OFFSET, XV_HDMIRX_PIO_OUT_EXT_VRST_MASK, XV_HDMIRX_PIO_OUT_SET_OFFSET, XV_HdmiRx_WriteReg.
void XV_HdmiRx_EXT_SYSRST(XV_HdmiRx *InstancePtr, u8 Reset)
This function asserts or releases the HDMI RX External SYSRST.
InstancePtr is a pointer to the XV_HdmiRx core instance. Reset specifies TRUE/FALSE value to either assert or release HDMI RX External SYSRST. None. The reset output of the PIO is inverted. When the system is in reset, the PIO output is cleared and this will reset the HDMI RX. Therefore, clearing the PIO reset output will assert the HDMI External system reset. C-style signature: void XV_HdmiRx_EXT_SYSRST(XV_HdmiRx *InstancePtr, u8 Reset)
References XV_HDMIRX_PIO_OUT_CLR_OFFSET, XV_HDMIRX_PIO_OUT_EXT_SYSRST_MASK, XV_HDMIRX_PIO_OUT_SET_OFFSET, XV_HdmiRx_WriteReg.
int XV_HdmiRx_SetPixelRate(XV_HdmiRx *InstancePtr)
This function sets the pixel rate.
InstancePtr is a pointer to the XV_HdmiRx core instance. XST_SUCCESS is always returned. None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HdmiRx::Stream, XV_HdmiRx_Stream::Video, XV_HDMIRX_PIO_OUT_MSK_OFFSET, XV_HDMIRX_PIO_OUT_OFFSET, XV_HDMIRX_PIO_OUT_PIXEL_RATE_MASK, XV_HDMIRX_PIO_OUT_PIXEL_RATE_SHIFT, XV_HdmiRx_WriteReg.
Referenced by XV_HdmiRx_SetStream.
void XV_HdmiRx_SetColorFormat(XV_HdmiRx *InstancePtr)
This function sets the color format.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HdmiRx::Stream, XV_HdmiRx_Stream::Video, XV_HDMIRX_PIO_OUT_COLOR_SPACE_MASK, XV_HDMIRX_PIO_OUT_COLOR_SPACE_SHIFT, XV_HDMIRX_PIO_OUT_MSK_OFFSET, XV_HDMIRX_PIO_OUT_OFFSET, XV_HdmiRx_WriteReg.
int XV_HdmiRx_IsLinkStatusErrMax(XV_HdmiRx *InstancePtr)
This function provides status of one of the link error counters reached the maximum value.
InstancePtr is a pointer to the XV_HdmiRx core instance. TRUE = Maximum error counter reached.FALSE = Maximum error counter not reached. None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HDMIRX_LNKSTA_STA_ERR_MAX_MASK, XV_HDMIRX_LNKSTA_STA_OFFSET, XV_HdmiRx_ReadReg.
void XV_HdmiRx_ClearLinkStatus(XV_HdmiRx *InstancePtr)
This function clears the link error counters.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HDMIRX_LNKSTA_CTRL_CLR_OFFSET, XV_HDMIRX_LNKSTA_CTRL_ERR_CLR_MASK, XV_HDMIRX_LNKSTA_CTRL_SET_OFFSET, XV_HdmiRx_WriteReg.
u32 XV_HdmiRx_GetLinkStatus(XV_HdmiRx *InstancePtr, u8 Type)
This function provides status of the HDMI RX core Link Status peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. Type specifies one of the type for which status to be provided: 0 = Link error counter for channel 0.1 = Link error counter for channel 1.2 = Link error counter for channel 2. Link status of the HDMI RX core link. None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HDMIRX_LNKSTA_LNK_ERR0_OFFSET, XV_HdmiRx_ReadReg.
u32 XV_HdmiRx_GetAcrCts(XV_HdmiRx *InstancePtr)
This function provides audio clock regenerating CTS (Cycle-Time Stamp) value at the HDMI sink device.
InstancePtr is a pointer to the XV_HdmiRx core instance. Audio clock CTS value. None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HDMIRX_AUD_CTS_OFFSET, XV_HdmiRx_ReadReg.
u32 XV_HdmiRx_GetAcrN(XV_HdmiRx *InstancePtr)
This function provides audio clock regenerating factor N value.
InstancePtr is a pointer to the XV_HdmiRx core instance. ACR N value. None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HDMIRX_AUD_N_OFFSET, XV_HdmiRx_ReadReg.
int XV_HdmiRx_DdcLoadEdid(XV_HdmiRx *InstancePtr, u8 *Data, u16 Length)
This function loads the EDID data into the DDC slave.
InstancePtr is a pointer to the XV_HdmiRx core instance. EdidData is a pointer to the EDID data array. Length is the length, in bytes, of the EDID array. XST_SUCCESS if the EDID data was loaded successfullyXST_FAILURE if the EDID data load failed None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HDMIRX_DDC_CTRL_EDID_EN_MASK, XV_HDMIRX_DDC_CTRL_SET_OFFSET, XV_HDMIRX_DDC_EDID_DATA_OFFSET, XV_HDMIRX_DDC_EDID_WP_OFFSET, XV_HdmiRx_DdcGetEdidWords, XV_HdmiRx_WriteReg.
void XV_HdmiRx_DdcHdcpSetAddress(XV_HdmiRx *InstancePtr, u32 Addr)
This function sets the HDCP address in the DDC peripheral.
This is implemented as a function and not a macro, so the HDCP driver can bind the function call with a handler. InstancePtr is a pointer to the XHdmi_Rx core instance. Address is the HDCP address. None. C-style signature: void XHdmiRx_DdcHdcpSetAddress(XHdmi_Rx *InstancePtr, u8 Address)
References XV_HDMIRX_DDC_HDCP_ADDRESS_OFFSET, XV_HdmiRx_WriteReg.
void XV_HdmiRx_DdcHdcpWriteData(XV_HdmiRx *InstancePtr, u32 Data)
This function writes HDCP data in the DDC peripheral.
This is implemented as a function and not a macro, so the HDCP driver can bind the function call with a handler. InstancePtr is a pointer to the XHdmi_Rx core instance. Data is the HDCP data to be written. None. C-style signature: void XHdmiRx_DdcHdcpWriteData(XHdmi_Rx *InstancePtr, u8 Data)
References XV_HDMIRX_DDC_HDCP_DATA_OFFSET, XV_HdmiRx_WriteReg.
u32 XV_HdmiRx_DdcHdcpReadData(XV_HdmiRx *InstancePtr)
This function reads HDCP data from the DDC peripheral.
This is implemented as a function and not a macro, so the HDCP driver can bind the function call with a handler. InstancePtr is a pointer to the XHdmi_Rx core instance. Returns the HDCP data read from the DDC peripheral. C-style signature: u32 XHdmiRx_DdcHdcpReadData(XHdmi_Rx *InstancePtr)
References XV_HDMIRX_DDC_HDCP_DATA_OFFSET, XV_HdmiRx_ReadReg.
u16 XV_HdmiRx_DdcGetHdcpWriteMessageBufferWords(XV_HdmiRx *InstancePtr)
This function gets the number of bytes of the HDCP 2.2 write buffer in the DDC slave.
InstancePtr is a pointer to the XHdmi_Rx core instance. HDCP 2.2 write buffer words None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HDMIRX_DDC_HDCP_STA_OFFSET, XV_HDMIRX_DDC_STA_HDCP_WMSG_WORDS_MASK, XV_HDMIRX_DDC_STA_HDCP_WMSG_WORDS_SHIFT, XV_HdmiRx_ReadReg.
int XV_HdmiRx_DdcIsHdcpWriteMessageBufferEmpty(XV_HdmiRx *InstancePtr)
This function returns the status of the HDCP 2.2 write buffer in the DDC slave.
InstancePtr is a pointer to the XHdmi_Rx core instance. TRUE = HDCP 2.2 message buffer is empty.FALSE = HDCP 2.2 message buffer contains data. None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HDMIRX_DDC_HDCP_STA_OFFSET, XV_HDMIRX_DDC_STA_HDCP_WMSG_EP_MASK, XV_HdmiRx_ReadReg.
u16 XV_HdmiRx_DdcGetHdcpReadMessageBufferWords(XV_HdmiRx *InstancePtr)
This function gets the number of bytes of the HDCP 2.2 read buffer in the DDC slave.
InstancePtr is a pointer to the XHdmi_Rx core instance. HDCP 2.2 read buffer words None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HDMIRX_DDC_HDCP_STA_OFFSET, XV_HDMIRX_DDC_STA_HDCP_RMSG_WORDS_MASK, XV_HDMIRX_DDC_STA_HDCP_RMSG_WORDS_SHIFT, XV_HdmiRx_ReadReg.
int XV_HdmiRx_DdcIsHdcpReadMessageBufferEmpty(XV_HdmiRx *InstancePtr)
This function returns the status of the HDCP 2.2 read message buffer in the DDC slave.
InstancePtr is a pointer to the XHdmi_Rx core instance. TRUE = HDCP 2.2 message buffer is empty.FALSE = HDCP 2.2 message buffer contains data. None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HDMIRX_DDC_HDCP_STA_OFFSET, XV_HDMIRX_DDC_STA_HDCP_RMSG_EP_MASK, XV_HdmiRx_ReadReg.
int XV_HdmiRx_GetTmdsClockRatio(XV_HdmiRx *InstancePtr)
This function gets the SCDC TMDS clock ratio bit.
InstancePtr is a pointer to the XV_HdmiRx core instance. TRUE = TMDS clock ratio bit is set.FALSE = TMDS clock ratio bit is cleared. None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HDMIRX_PIO_IN_OFFSET, XV_HDMIRX_PIO_IN_SCDC_TMDS_CLOCK_RATIO_MASK, XV_HdmiRx_ReadReg.
u8 XV_HdmiRx_GetAviVic(XV_HdmiRx *InstancePtr)
This function returns the AVI VIC (captured by the AUX peripheral)
InstancePtr is a pointer to the XV_HdmiRx core instance. The AVI VIC code. None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HDMIRX_AUX_STA_AVI_VIC_MASK, XV_HDMIRX_AUX_STA_AVI_VIC_SHIFT, XV_HDMIRX_AUX_STA_OFFSET, XV_HdmiRx_ReadReg.
Referenced by XV_HdmiRx_GetVideoProperties.
XVidC_ColorFormat XV_HdmiRx_GetAviColorSpace(XV_HdmiRx *InstancePtr)
This function returns the AVI colorspace (captured by the AUX peripheral)
InstancePtr is a pointer to the XV_HdmiRx core instance. The AVI colorspace value. None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HDMIRX_AUX_STA_AVI_CS_MASK, XV_HDMIRX_AUX_STA_AVI_CS_SHIFT, XV_HDMIRX_AUX_STA_OFFSET, XV_HdmiRx_ReadReg.
Referenced by XV_HdmiRx_GetVideoProperties.
XVidC_ColorDepth XV_HdmiRx_GetGcpColorDepth(XV_HdmiRx *InstancePtr)
This function returns the GCP color depth (captured by the AUX peripheral)
InstancePtr is a pointer to the XV_HdmiRx core instance. The GCP color depth. None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HDMIRX_AUX_STA_GCP_CD_MASK, XV_HDMIRX_AUX_STA_GCP_CD_SHIFT, XV_HDMIRX_AUX_STA_OFFSET, XV_HdmiRx_ReadReg.
Referenced by XV_HdmiRx_GetVideoProperties.
XVidC_VideoMode XV_HdmiRx_LookupVmId(u8 Vic)
This function searches for the video mode based on the vic.
Vic Vic defined in the VIC table. None.
int XV_HdmiRx_GetVideoProperties(XV_HdmiRx *InstancePtr)
This function reads the video properties from the aux peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HdmiRx::Stream, XV_HdmiRx_Stream::Vic, XV_HdmiRx_Stream::Video, XV_HDMIRX_AUX_STA_AVI_MASK, XV_HDMIRX_AUX_STA_OFFSET, XV_HdmiRx_GetAviColorSpace, XV_HdmiRx_GetAviVic, XV_HdmiRx_GetGcpColorDepth, XV_HdmiRx_ReadReg.
int XV_HdmiRx_GetVideoTiming(XV_HdmiRx *InstancePtr)
This function reads the video timing from the VTD peripheral.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HdmiRx_Stream::PixelClk, XV_HdmiRx::Stream, XV_HdmiRx_Stream::Video, XV_HdmiRx_Divide, XV_HdmiRx_ReadReg, XV_HDMIRX_VTD_ACT_LIN_OFFSET, XV_HDMIRX_VTD_ACT_PIX_OFFSET, XV_HDMIRX_VTD_HBP_OFFSET, XV_HDMIRX_VTD_HFP_OFFSET, XV_HDMIRX_VTD_HSW_OFFSET, XV_HDMIRX_VTD_STA_FMT_MASK, XV_HDMIRX_VTD_STA_HS_POL_MASK, XV_HDMIRX_VTD_STA_OFFSET, XV_HDMIRX_VTD_STA_VS_POL_MASK, XV_HDMIRX_VTD_TOT_LIN_OFFSET, XV_HDMIRX_VTD_TOT_PIX_OFFSET, XV_HDMIRX_VTD_VBP_OFFSET, XV_HDMIRX_VTD_VFP_OFFSET, XV_HDMIRX_VTD_VSW_OFFSET.
u32 XV_HdmiRx_Divide(u32 Dividend, u32 Divisor)
This function calculates the divider for the frame calculation.
Dividend is the dividend value to use in the calculation. Divisor is the divisor value to use in the calculation. The result of the calculation. None.
Referenced by XV_HdmiRx_GetVideoTiming.
void XV_HdmiRx_WriteScdcRegister(XV_HdmiRx *InstancePtr, u8 address, u8 data)
This function write data to SCDC register.
InstancePtr is a pointer to the XV_HdmiRx core instance. address specifies the SCDC register address to write to. data specifies the data to be written. None. SCDC register 0x01,0x02,0x10,0x20,0x21,0x40 are handled by H/W directly. These registers should not be written by User application.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HDMIRX_SCDC_BRAM_OFFSET, XV_HdmiRx_WriteReg.
void XV_HdmiRx_DebugInfo(XV_HdmiRx *InstancePtr)
This function prints stream and timing information on STDIO/Uart console.
InstancePtr is a pointer to the XV_HdmiRx core instance. None. None.
References XV_HdmiRx::Stream, XV_HdmiRx_Stream::Video.
int XV_HdmiRx_SelfTest(XV_HdmiRx *InstancePtr)
This function reads ID of PIO peripheral.
InstancePtr is a pointer to the HDMI RX core instance. XST_SUCCESS if PIO ID was matched.XST_FAILURE if PIO ID was mismatched. None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HDMIRX_MASK_16, XV_HDMIRX_PIO_ID, XV_HDMIRX_PIO_ID_OFFSET, XV_HdmiRx_ReadReg, XV_HDMIRX_SHIFT_16.
void XV_HdmiRx_IntrHandler(void *InstancePtr)
This function is the interrupt handler for the HDMI RX driver.
This handler reads the pending interrupt from PIO, DDC, TIMDET, AUX, AUD and LNKSTA peripherals, determines the source of the interrupts, clears the interrupts and calls callbacks accordingly.The application is responsible for connecting this function to the interrupt system. Application beyond this driver is also responsible for providing callbacks to handle interrupts and installing the callbacks using XV_HdmiRx_SetCallback() during initialization phase. An example delivered with this driver demonstrates how this could be done. InstancePtr is a pointer to the XV_HdmiRx instance that just interrupted. None. None.
References XV_HdmiRx_Config::BaseAddress, XV_HdmiRx::Config, XV_HdmiRx::IsReady, XV_HDMIRX_AUD_STA_IRQ_MASK, XV_HDMIRX_AUD_STA_OFFSET, XV_HDMIRX_AUX_STA_IRQ_MASK, XV_HDMIRX_AUX_STA_OFFSET, XV_HDMIRX_DDC_STA_IRQ_MASK, XV_HDMIRX_DDC_STA_OFFSET, XV_HDMIRX_LNKSTA_STA_IRQ_MASK, XV_HDMIRX_LNKSTA_STA_OFFSET, XV_HDMIRX_PIO_STA_IRQ_MASK, XV_HDMIRX_PIO_STA_OFFSET, XV_HdmiRx_ReadReg, XV_HDMIRX_TMR_STA_IRQ_MASK, XV_HDMIRX_TMR_STA_OFFSET, XV_HDMIRX_VTD_STA_IRQ_MASK, XV_HDMIRX_VTD_STA_OFFSET.
int XV_HdmiRx_SetCallback(XV_HdmiRx *InstancePtr, XV_HdmiRx_HandlerType HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function Type ------------------------- ----------------------------------------------- (XV_HDMIRX_HANDLER_VTD) VtdCallback (XV_HDMIRX_HANDLER_AUX) AuxCallback (XV_HDMIRX_HANDLER_AUD) AudCallback (XV_HDMIRX_HANDLER_LNKSTA) LnkStaCallback (XV_HDMIRX_HANDLER_PIO) PioCallback InstancePtr is a pointer to the HDMI RX core instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XV_HdmiRx::AudCallback, XV_HdmiRx::AudRef, XV_HdmiRx::AuxCallback, XV_HdmiRx::AuxRef, XV_HdmiRx::BrdgOverflowCallback, XV_HdmiRx::BrdgOverflowRef, XV_HdmiRx::ConnectCallback, XV_HdmiRx::ConnectRef, XV_HdmiRx::DdcCallback, XV_HdmiRx::DdcRef, XV_HdmiRx::Hdcp14ProtEvtCallback, XV_HdmiRx::Hdcp14ProtEvtRef, XV_HdmiRx::Hdcp22ProtEvtCallback, XV_HdmiRx::Hdcp22ProtEvtRef, XV_HdmiRx::HdcpCallback, XV_HdmiRx::HdcpRef, XV_HdmiRx::IsAudCallbackSet, XV_HdmiRx::IsAuxCallbackSet, XV_HdmiRx::IsBrdgOverflowCallbackSet, XV_HdmiRx::IsConnectCallbackSet, XV_HdmiRx::IsDdcCallbackSet, XV_HdmiRx::IsHdcp14ProtEvtCallbackSet, XV_HdmiRx::IsHdcp22ProtEvtCallbackSet, XV_HdmiRx::IsHdcpCallbackSet, XV_HdmiRx::IsLinkErrorCallbackSet, XV_HdmiRx::IsLnkStaCallbackSet, XV_HdmiRx::IsModeCallbackSet, XV_HdmiRx::IsPhyErrorCallbackSet, XV_HdmiRx::IsStreamDownCallbackSet, XV_HdmiRx::IsStreamInitCallbackSet, XV_HdmiRx::IsStreamUpCallbackSet, XV_HdmiRx::IsSyncLossCallbackSet, XV_HdmiRx::IsTmdsClkRatioCallbackSet, XV_HdmiRx::IsVicErrorCallbackSet, XV_HdmiRx::LinkErrorCallback, XV_HdmiRx::LinkErrorRef, XV_HdmiRx::LnkStaCallback, XV_HdmiRx::LnkStaRef, XV_HdmiRx::ModeCallback, XV_HdmiRx::ModeRef, XV_HdmiRx::PhyErrorCallback, XV_HdmiRx::PhyErrorRef, XV_HdmiRx::StreamDownCallback, XV_HdmiRx::StreamDownRef, XV_HdmiRx::StreamInitCallback, XV_HdmiRx::StreamInitRef, XV_HdmiRx::StreamUpCallback, XV_HdmiRx::StreamUpRef, XV_HdmiRx::SyncLossCallback, XV_HdmiRx::SyncLossRef, XV_HdmiRx::TmdsClkRatioCallback, XV_HdmiRx::TmdsClkRatioRef, XV_HdmiRx::VicErrorCallback, XV_HdmiRx::VicErrorRef, XV_HDMIRX_HANDLER_AUD, XV_HDMIRX_HANDLER_AUX, XV_HDMIRX_HANDLER_BRDG_OVERFLOW, XV_HDMIRX_HANDLER_CONNECT, XV_HDMIRX_HANDLER_DDC, XV_HDMIRX_HANDLER_DDC_HDCP_14_PROT, XV_HDMIRX_HANDLER_DDC_HDCP_22_PROT, XV_HDMIRX_HANDLER_HDCP, XV_HDMIRX_HANDLER_LINK_ERROR, XV_HDMIRX_HANDLER_LNKSTA, XV_HDMIRX_HANDLER_MODE, XV_HDMIRX_HANDLER_PHY_ERROR, XV_HDMIRX_HANDLER_STREAM_DOWN, XV_HDMIRX_HANDLER_STREAM_INIT, XV_HDMIRX_HANDLER_STREAM_UP, XV_HDMIRX_HANDLER_SYNC_LOSS, XV_HDMIRX_HANDLER_TMDS_CLK_RATIO, XV_HDMIRX_HANDLER_VIC_ERROR.
int XV_HdmiRx_VSIF_ParsePacket(XHdmiC_Aux *AuxPtr, XV_HdmiRx_VSIF *VSIFPtr)
This function parses a Vendor Specific InfoFrame (VSIF).
AuxPtr is a pointer to the XV_HdmiRx_Rx_Aux instance. VSIFPtr is a pointer to the XV_HdmiRx_VSIF instance. XST_SUCCESS if operation was successfulXST_FAILURE if an error was detected during parsing
References XV_HdmiRx_VSIF::Format, XV_HdmiRx_VSIF::HDMI_VIC, XV_HdmiRx_VSIF::IEEE_ID, XV_HdmiRx_VSIF::Info_3D, XV_HdmiRx_VSIF::Version, XV_HDMIRX_VSIF_VF_3D, XV_HDMIRX_VSIF_VF_EXTRES, XV_HDMIRX_VSIF_VF_NOINFO, XV_HDMIRX_VSIF_VIDEO_FORMAT_MASK, XV_HDMIRX_VSIF_VIDEO_FORMAT_SHIFT.
void XV_HdmiRx_VSIF_DisplayInfo(XV_HdmiRx_VSIF *VSIFPtr)
This function displays the contents of an XV_HdmiRx_VSIF instance.
VSIFPtr is a pointer to the XV_HdmiRx_VSIF instance. None.
References XV_HdmiRx_VSIF::Format, XV_HdmiRx_VSIF::HDMI_VIC, XV_HdmiRx_VSIF::Info_3D, XV_HdmiRx_3D_MetaData::IsPresent, XV_HdmiRx_3D_Info::MetaData, XV_HDMIRX_3D_STRUCT_SIDE_BY_SIDE_HALF, XV_HdmiRx_VSIF_3DSampMethodToString, XV_HdmiRx_VSIF_3DSampPosToString, XV_HdmiRx_VSIF_3DStructToString, XV_HDMIRX_VSIF_VF_3D, XV_HDMIRX_VSIF_VF_EXTRES.
char* XV_HdmiRx_VSIF_3DStructToString(XV_HdmiRx_3D_Struct_Field Item)
This function returns a string representation of the enumerated type XV_HdmiRx_3D_Struct_Field.
Item specifies the value to convert. Pointer to the converted string.
References XV_HDMIRX_3D_STRUCT_FIELD_ALTERNATIVE, XV_HDMIRX_3D_STRUCT_FRAME_PACKING, XV_HDMIRX_3D_STRUCT_L_DEPTH, XV_HDMIRX_3D_STRUCT_L_DEPTH_GRAPH_GDEPTH, XV_HDMIRX_3D_STRUCT_LINE_ALTERNATIVE, XV_HDMIRX_3D_STRUCT_SIDE_BY_SIDE_FULL, XV_HDMIRX_3D_STRUCT_SIDE_BY_SIDE_HALF, XV_HDMIRX_3D_STRUCT_TOP_AND_BOTTOM.
Referenced by XV_HdmiRx_VSIF_DisplayInfo.
char* XV_HdmiRx_VSIF_3DSampMethodToString(XV_HdmiRx_3D_Sampling_Method Item)
This function returns a string representation of the enumerated type XV_HdmiRx_3D_Sampling_Method.
Item specifies the value to convert. Pointer to the converted string.
References XV_HDMIRX_3D_SAMPLING_HORIZONTAL, XV_HDMIRX_3D_SAMPLING_QUINCUNX.
Referenced by XV_HdmiRx_VSIF_DisplayInfo.
char* XV_HdmiRx_VSIF_3DSampPosToString(XV_HdmiRx_3D_Sampling_Position Item)
This function returns a string representation of the enumerated type XV_HdmiRx_3D_Sampling_Position.
Item specifies the value to convert. Pointer to the converted string.
References XV_HDMIRX_3D_SAMPPOS_ELER, XV_HDMIRX_3D_SAMPPOS_ELOR, XV_HDMIRX_3D_SAMPPOS_OLER, XV_HDMIRX_3D_SAMPPOS_OLOR.
Referenced by XV_HdmiRx_VSIF_DisplayInfo.