xv_hdmirx_vsif.c
int XV_HdmiRx_VSIF_Extract3DInfo(u8 *VSIFRaw, XV_HdmiRx_3D_Info *InstancePtr)
This function extracts the 3D information from the Vendor Specific InfoFrame (VSIF).
VSIFRaw is a pointer to the VSIF payload. InstancePtr is a pointer to the XV_HdmiRx_3D_Info instance. XST_SUCCESS if operation was successfulXST_FAILURE if an error was detected during parsing
static XV_HdmiRx_3D_Struct_Field XV_HdmiRx_VSIF_Conv3DInfoTo3DStruct(XVidC_3DInfo *InfoPtr)
This function extracts the 3D format from XVidC_3DInfo and returns a XV_HdmiRx_3D_Struct_Field type.
InfoPtr is a pointer to the XVidC_3DInfo instance. The extracted value.
static XV_HdmiRx_3D_Sampling_Method XV_HdmiRx_VSIF_Conv3DInfoTo3DSampMethod(XVidC_3DInfo *InfoPtr)
This function extracts the sampling method info from XVidC_3DInfo and returns a XV_HdmiRx_3D_Sampling_Method type.
InfoPtr is a pointer to the XVidC_3DInfo instance. The extracted value.
static XV_HdmiRx_3D_Sampling_Position XV_HdmiRx_VSIF_Conv3DInfoTo3DSampPos(XVidC_3DInfo *InfoPtr)
This function extracts the sampling position info from XVidC_3DInfo and returns a XV_HdmiRx_3D_Sampling_Position type.
InfoPtr is a pointer to the XVidC_3DInfo instance. The extracted value.
static XVidC_3DFormat XV_HdmiRx_VSIF_Conv3DStructTo3DFormat(XV_HdmiRx_3D_Struct_Field Value)
This function converts a XV_HdmiRx_3D_Struct_Field type to a XVidC_3DFormat type.
Value is the value to convert. The converted value.
static XVidC_3DSamplingMethod XV_HdmiRx_VSIF_Conv3DSampMethodTo3DSampMethod(XV_HdmiRx_3D_Sampling_Method Value)
This function converts a XV_HdmiRx_3D_Sampling_Method type to a XVidC_3DSamplingMethod type.
Value is the value to convert. The converted value.
static XVidC_3DSamplingPosition XV_HdmiRx_VSIF_Conv3DSampPosTo3DSampPos(XV_HdmiRx_3D_Sampling_Position Value)
This function converts a XV_HdmiRx_3D_Sampling_Position type to a XVidC_3DSamplingPosition type.
Value is the value to convert. The converted value.
int XV_HdmiRx_VSIF_ParsePacket(XHdmiC_Aux *AuxPtr, XV_HdmiRx_VSIF *VSIFPtr)
This function parses a Vendor Specific InfoFrame (VSIF).
AuxPtr is a pointer to the XV_HdmiRx_Rx_Aux instance. VSIFPtr is a pointer to the XV_HdmiRx_VSIF instance. XST_SUCCESS if operation was successfulXST_FAILURE if an error was detected during parsing
References XV_HdmiRx_VSIF::Format, XV_HdmiRx_VSIF::HDMI_VIC, XV_HdmiRx_VSIF::IEEE_ID, XV_HdmiRx_VSIF::Info_3D, XV_HdmiRx_VSIF::Version, XV_HDMIRX_VSIF_VF_3D, XV_HDMIRX_VSIF_VF_EXTRES, XV_HDMIRX_VSIF_VF_NOINFO, XV_HDMIRX_VSIF_VIDEO_FORMAT_MASK, XV_HDMIRX_VSIF_VIDEO_FORMAT_SHIFT.
void XV_HdmiRx_VSIF_DisplayInfo(XV_HdmiRx_VSIF *VSIFPtr)
This function displays the contents of an XV_HdmiRx_VSIF instance.
VSIFPtr is a pointer to the XV_HdmiRx_VSIF instance. None.
References XV_HdmiRx_VSIF::Format, XV_HdmiRx_VSIF::HDMI_VIC, XV_HdmiRx_VSIF::Info_3D, XV_HdmiRx_3D_MetaData::IsPresent, XV_HdmiRx_3D_Info::MetaData, XV_HDMIRX_3D_STRUCT_SIDE_BY_SIDE_HALF, XV_HdmiRx_VSIF_3DSampMethodToString, XV_HdmiRx_VSIF_3DSampPosToString, XV_HdmiRx_VSIF_3DStructToString, XV_HDMIRX_VSIF_VF_3D, XV_HDMIRX_VSIF_VF_EXTRES.
char* XV_HdmiRx_VSIF_3DStructToString(XV_HdmiRx_3D_Struct_Field Item)
This function returns a string representation of the enumerated type XV_HdmiRx_3D_Struct_Field.
Item specifies the value to convert. Pointer to the converted string.
References XV_HDMIRX_3D_STRUCT_FIELD_ALTERNATIVE, XV_HDMIRX_3D_STRUCT_FRAME_PACKING, XV_HDMIRX_3D_STRUCT_L_DEPTH, XV_HDMIRX_3D_STRUCT_L_DEPTH_GRAPH_GDEPTH, XV_HDMIRX_3D_STRUCT_LINE_ALTERNATIVE, XV_HDMIRX_3D_STRUCT_SIDE_BY_SIDE_FULL, XV_HDMIRX_3D_STRUCT_SIDE_BY_SIDE_HALF, XV_HDMIRX_3D_STRUCT_TOP_AND_BOTTOM.
Referenced by XV_HdmiRx_VSIF_DisplayInfo.
char* XV_HdmiRx_VSIF_3DSampMethodToString(XV_HdmiRx_3D_Sampling_Method Item)
This function returns a string representation of the enumerated type XV_HdmiRx_3D_Sampling_Method.
Item specifies the value to convert. Pointer to the converted string.
References XV_HDMIRX_3D_SAMPLING_HORIZONTAL, XV_HDMIRX_3D_SAMPLING_QUINCUNX.
Referenced by XV_HdmiRx_VSIF_DisplayInfo.
char* XV_HdmiRx_VSIF_3DSampPosToString(XV_HdmiRx_3D_Sampling_Position Item)
This function returns a string representation of the enumerated type XV_HdmiRx_3D_Sampling_Position.
Item specifies the value to convert. Pointer to the converted string.
References XV_HDMIRX_3D_SAMPPOS_ELER, XV_HDMIRX_3D_SAMPPOS_ELOR, XV_HDMIRX_3D_SAMPPOS_OLER, XV_HDMIRX_3D_SAMPPOS_OLOR.
Referenced by XV_HdmiRx_VSIF_DisplayInfo.