axipmon
XAPM_MAX_COUNTERS
Maximum number of Counters.
Referenced by XAxiPmon_GetIncrementer, XAxiPmon_GetIncrementerRange, XAxiPmon_GetLogEnableRanges, XAxiPmon_GetMetrics, XAxiPmon_GetSampledIncrementer, XAxiPmon_SetIncrementerRange, XAxiPmon_SetLogEnableRanges, XAxiPmon_SetMetrics.
XAPM_MAX_COUNTERS_PROFILE
Maximum number of Counters.
Referenced by XAxiPmon_GetMetricCounter, XAxiPmon_GetSampledMetricCounter.
XAPM_METRIC_COUNTER_0
Metric Counter 0 Register Index.
Referenced by ApmMetricConfig, AxiPmonInterruptExample, AxiPmonPolledExample, OcmTransaction.
XAPM_METRIC_COUNTER_1
Metric Counter 1 Register Index.
Referenced by ApmMetricConfig, OcmTransaction.
XAPM_METRIC_COUNTER_2
Metric Counter 2 Register Index.
XAPM_METRIC_COUNTER_3
Metric Counter 3 Register Index.
XAPM_METRIC_COUNTER_4
Metric Counter 4 Register Index.
XAPM_METRIC_COUNTER_5
Metric Counter 5 Register Index.
XAPM_METRIC_COUNTER_6
Metric Counter 6 Register Index.
XAPM_METRIC_COUNTER_7
Metric Counter 7 Register Index.
XAPM_METRIC_COUNTER_8
Metric Counter 8 Register Index.
XAPM_METRIC_COUNTER_9
Metric Counter 9 Register Index.
XAPM_INCREMENTER_0
Metric Counter 0 Register Index.
Referenced by AxiPmonInterruptExample, AxiPmonPolledExample, XAxiPmon_SelfTest.
XAPM_INCREMENTER_1
Metric Counter 0 Register Index.
XAPM_INCREMENTER_2
Metric Counter 0 Register Index.
XAPM_INCREMENTER_3
Metric Counter 0 Register Index.
XAPM_INCREMENTER_4
Metric Counter 0 Register Index.
XAPM_INCREMENTER_5
Metric Counter 0 Register Index.
XAPM_INCREMENTER_6
Metric Counter 0 Register Index.
XAPM_INCREMENTER_7
Metric Counter 0 Register Index.
XAPM_INCREMENTER_8
Metric Counter 0 Register Index.
XAPM_INCREMENTER_9
Metric Counter 0 Register Index.
XAPM_METRIC_SET_0
Write Transaction Count.
Referenced by AxiPmonInterruptExample, AxiPmonPolledExample, OcmTransaction, XAxiPmon_GetMetricName.
XAPM_METRIC_SET_1
Read Transaction Count.
Referenced by OcmTransaction, XAxiPmon_GetMetricName.
XAPM_METRIC_SET_2
Write Byte Count.
Referenced by OcmTransaction, XAxiPmon_GetMetricName.
XAPM_METRIC_SET_3
Read Byte Count.
Referenced by OcmTransaction, XAxiPmon_GetMetricName.
XAPM_METRIC_SET_4
Write Beat Count.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_5
Total Read Latency.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_6
Total Write Latency.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_7
Slv_Wr_Idle_Cnt.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_8
Mst_Rd_Idle_Cnt.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_9
Num_BValids.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_10
Num_WLasts.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_11
Num_RLasts.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_12
Minimum Write Latency.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_13
Maximum Write Latency.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_14
Minimum Read Latency.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_15
Maximum Read Latency.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_16
Transfer Cycle Count.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_17
Packet Count.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_18
Data Byte Count.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_19
Position Byte Count.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_20
Null Byte Count.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_21
Slv_Idle_Cnt.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_22
Mst_Idle_Cnt.
Referenced by XAxiPmon_GetMetricName, XAxiPmon_SetMetrics.
XAPM_METRIC_SET_30
External event count.
Referenced by XAxiPmon_GetMetricName, XAxiPmon_SetMetrics.
XAPM_MAX_AGENTS
Maximum number of Agents.
Referenced by XAxiPmon_SetMetrics.
XAPM_FLAG_WRADDR
Write Address Flag.
XAPM_FLAG_FIRSTWR
First Write Flag.
XAPM_FLAG_LASTWR
Last Write Flag.
XAPM_FLAG_RESPONSE
Response Flag.
XAPM_FLAG_RDADDR
Read Address Flag.
XAPM_FLAG_FIRSTRD
First Read Flag.
XAPM_FLAG_LASTRD
Last Read Flag.
XAPM_FLAG_SWDATA
Software-written Data Flag.
XAPM_FLAG_EVENT
Last Read Flag.
XAPM_FLAG_EVNTSTOP
Last Read Flag.
XAPM_FLAG_EVNTSTART
Last Read Flag.
XAPM_FLAG_GCCOVF
Global Clock Counter Overflow Flag.
XAPM_FLAG_SCLAPSE
Sample Counter Lapse Flag.
XAPM_FLAG_MC0
Metric Counter 0 Flag.
XAPM_FLAG_MC1
Metric Counter 1 Flag.
XAPM_FLAG_MC2
Metric Counter 2 Flag.
XAPM_FLAG_MC3
Metric Counter 3 Flag.
XAPM_FLAG_MC4
Metric Counter 4 Flag.
XAPM_FLAG_MC5
Metric Counter 5 Flag.
XAPM_FLAG_MC6
Metric Counter 6 Flag.
XAPM_FLAG_MC7
Metric Counter 7 Flag.
XAPM_FLAG_MC8
Metric Counter 8 Flag.
XAPM_FLAG_MC9
Metric Counter 9 Flag.
XAPM_LATENCY_ADDR_ISSUE
Address Issue as start point for Latency calculation.
Referenced by XAxiPmon_GetRdLatencyStart, XAxiPmon_GetWrLatencyStart.
XAPM_LATENCY_ADDR_ACCEPT
Address Acceptance as start point for Latency calculation.
Referenced by XAxiPmon_GetRdLatencyStart, XAxiPmon_GetWrLatencyStart, XAxiPmon_SetRdLatencyStart, XAxiPmon_SetWrLatencyStart.
XAPM_LATENCY_LASTRD
Last Read as end point for Latency calculation.
Referenced by XAxiPmon_GetRdLatencyEnd.
XAPM_LATENCY_LASTWR
Last Write as end point for Latency calculation.
Referenced by XAxiPmon_GetWrLatencyEnd.
XAPM_LATENCY_FIRSTRD
First Read as end point for Latency calculation.
Referenced by XAxiPmon_GetRdLatencyEnd, XAxiPmon_SetRdLatencyEnd.
XAPM_LATENCY_FIRSTWR
First Write as end point for Latency calculation.
Referenced by XAxiPmon_GetWrLatencyEnd, XAxiPmon_SetWrLatencyEnd.
XAPM_MODE_TRACE
APM in Trace mode.
Referenced by XAxiPmon_CfgInitialize, XAxiPmon_DisableMetricCounterTrigger, XAxiPmon_EnableEventLog, XAxiPmon_EnableMetricCounterTrigger, XAxiPmon_GetMetricCounter, XAxiPmon_GetSampledMetricCounter, XAxiPmon_GetSampleInterval, XAxiPmon_ResetMetricCounter, XAxiPmon_SetSampleInterval, XAxiPmon_StartEventLog, XAxiPmon_StopEventLog.
XAPM_MODE_PROFILE
APM in Profile mode.
Referenced by XAxiPmon_CfgInitialize, XAxiPmon_DisableEventLogTrigger, XAxiPmon_DisableMetricsCounter, XAxiPmon_EnableEventLogTrigger, XAxiPmon_EnableMetricsCounter, XAxiPmon_GetSampledMetricCounter, XAxiPmon_ResetFifo, XAxiPmon_StartCounters, XAxiPmon_StopCounters.
XAPM_MODE_ADVANCED
APM in Advanced mode.
Referenced by XAxiPmon_CfgInitialize, XAxiPmon_DisableMetricsCounter, XAxiPmon_EnableEventLog, XAxiPmon_EnableMetricsCounter, XAxiPmon_GetGlobalClkCounter, XAxiPmon_GetIncrementer, XAxiPmon_GetIncrementerRange, XAxiPmon_GetLogEnableRanges, XAxiPmon_GetMetrics, XAxiPmon_GetSampledIncrementer, XAxiPmon_GetSampledMetricCounter, XAxiPmon_ResetFifo, XAxiPmon_ResetGlobalClkCounter, XAxiPmon_SetIncrementerRange, XAxiPmon_SetLogEnableRanges, XAxiPmon_SetMetrics, XAxiPmon_StartCounters, XAxiPmon_StartEventLog, XAxiPmon_StopCounters, XAxiPmon_StopEventLog.
XAPM_GCC_HIGH_OFFSET
Global Clock Counter 32 to 63 bits.
Referenced by XAxiPmon_GetGlobalClkCounter.
XAPM_GCC_LOW_OFFSET
Global Clock Counter Lower 0-31 bits.
Referenced by XAxiPmon_GetGlobalClkCounter.
XAPM_SI_HIGH_OFFSET
Sample Interval MSB.
XAPM_SI_LOW_OFFSET
Sample Interval LSB.
Referenced by XAxiPmon_GetSampleInterval, XAxiPmon_SetSampleInterval.
XAPM_SICR_OFFSET
Sample Interval Control Register.
XAPM_SR_OFFSET
Sample Register.
XAPM_GIE_OFFSET
Global Interrupt Enable Register.
XAPM_IE_OFFSET
Interrupt Enable Register.
XAPM_IS_OFFSET
Interrupt Status Register.
XAPM_MSR0_OFFSET
Metric Selector 0 Register.
Referenced by XAxiPmon_GetMetrics, XAxiPmon_SetMetrics.
XAPM_MSR1_OFFSET
Metric Selector 1 Register.
Referenced by XAxiPmon_GetMetrics, XAxiPmon_SetMetrics.
XAPM_MSR2_OFFSET
Metric Selector 2 Register.
Referenced by XAxiPmon_GetMetrics, XAxiPmon_SetMetrics.
XAPM_MC0_OFFSET
Metric Counter 0 Register.
Referenced by XAxiPmon_GetMetricCounter.
XAPM_INC0_OFFSET
Incrementer 0 Register.
Referenced by XAxiPmon_GetIncrementer.
XAPM_RANGE0_OFFSET
Range 0 Register.
Referenced by XAxiPmon_GetIncrementerRange, XAxiPmon_SetIncrementerRange.
XAPM_MC0LOGEN_OFFSET
Metric Counter 0 Log Enable Register.
Referenced by XAxiPmon_GetLogEnableRanges, XAxiPmon_SetLogEnableRanges.
XAPM_MC1_OFFSET
Metric Counter 1 Register.
XAPM_INC1_OFFSET
Incrementer 1 Register.
XAPM_RANGE1_OFFSET
Range 1 Register.
XAPM_MC1LOGEN_OFFSET
Metric Counter 1 Log Enable Register.
XAPM_MC2_OFFSET
Metric Counter 2 Register.
XAPM_INC2_OFFSET
Incrementer 2 Register.
XAPM_RANGE2_OFFSET
Range 2 Register.
XAPM_MC2LOGEN_OFFSET
Metric Counter 2 Log Enable Register.
XAPM_MC3_OFFSET
Metric Counter 3 Register.
XAPM_INC3_OFFSET
Incrementer 3 Register.
XAPM_RANGE3_OFFSET
Range 3 Register.
XAPM_MC3LOGEN_OFFSET
Metric Counter 3 Log Enable Register.
XAPM_MC4_OFFSET
Metric Counter 4 Register.
XAPM_INC4_OFFSET
Incrementer 4 Register.
XAPM_RANGE4_OFFSET
Range 4 Register.
XAPM_MC4LOGEN_OFFSET
Metric Counter 4 Log Enable Register.
XAPM_MC5_OFFSET
Metric Counter 5 Register.
XAPM_INC5_OFFSET
Incrementer 5 Register.
XAPM_RANGE5_OFFSET
Range 5 Register.
XAPM_MC5LOGEN_OFFSET
Metric Counter 5 Log Enable Register.
XAPM_MC6_OFFSET
Metric Counter 6 Register.
XAPM_INC6_OFFSET
Incrementer 6 Register.
XAPM_RANGE6_OFFSET
Range 6 Register.
XAPM_MC6LOGEN_OFFSET
Metric Counter 6 Log Enable Register.
XAPM_MC7_OFFSET
Metric Counter 7 Register.
XAPM_INC7_OFFSET
Incrementer 7 Register.
XAPM_RANGE7_OFFSET
Range 7 Register.
XAPM_MC7LOGEN_OFFSET
Metric Counter 7 Log Enable Register.
XAPM_MC8_OFFSET
Metric Counter 8 Register.
XAPM_INC8_OFFSET
Incrementer 8 Register.
XAPM_RANGE8_OFFSET
Range 8 Register.
XAPM_MC8LOGEN_OFFSET
Metric Counter 8 Log Enable Register.
XAPM_MC9_OFFSET
Metric Counter 9 Register.
XAPM_INC9_OFFSET
Incrementer 9 Register.
XAPM_RANGE9_OFFSET
Range 9 Register.
XAPM_MC9LOGEN_OFFSET
Metric Counter 9 Log Enable Register.
XAPM_SMC0_OFFSET
Sampled Metric Counter 0 Register.
Referenced by XAxiPmon_GetSampledMetricCounter.
XAPM_SINC0_OFFSET
Sampled Incrementer 0 Register.
Referenced by XAxiPmon_GetSampledIncrementer.
XAPM_SMC1_OFFSET
Sampled Metric Counter 1 Register.
XAPM_SINC1_OFFSET
Sampled Incrementer 1 Register.
XAPM_SMC2_OFFSET
Sampled Metric Counter 2 Register.
XAPM_SINC2_OFFSET
Sampled Incrementer 2 Register.
XAPM_SMC3_OFFSET
Sampled Metric Counter 3 Register.
XAPM_SINC3_OFFSET
Sampled Incrementer 3 Register.
XAPM_SMC4_OFFSET
Sampled Metric Counter 4 Register.
XAPM_SINC4_OFFSET
Sampled Incrementer 4 Register.
XAPM_SMC5_OFFSET
Sampled Metric Counter 5 Register.
XAPM_SINC5_OFFSET
Sampled Incrementer 5 Register.
XAPM_SMC6_OFFSET
Sampled Metric Counter 6 Register.
XAPM_SINC6_OFFSET
Sampled Incrementer 6 Register.
XAPM_SMC7_OFFSET
Sampled Metric Counter 7 Register.
XAPM_SINC7_OFFSET
Sampled Incrementer 7 Register.
XAPM_SMC8_OFFSET
Sampled Metric Counter 8 Register.
XAPM_SINC8_OFFSET
Sampled Incrementer 8 Register.
XAPM_SMC9_OFFSET
Sampled Metric Counter 9 Register.
XAPM_SINC9_OFFSET
Sampled Incrementer 9 Register.
XAPM_MC10_OFFSET
Metric Counter 10 Register.
Referenced by XAxiPmon_GetMetricCounter.
XAPM_MC11_OFFSET
Metric Counter 11 Register.
XAPM_MC12_OFFSET
Metric Counter 12 Register.
Referenced by XAxiPmon_GetMetricCounter.
XAPM_MC13_OFFSET
Metric Counter 13 Register.
XAPM_MC14_OFFSET
Metric Counter 14 Register.
XAPM_MC15_OFFSET
Metric Counter 15 Register.
XAPM_MC16_OFFSET
Metric Counter 16 Register.
XAPM_MC17_OFFSET
Metric Counter 17 Register.
XAPM_MC18_OFFSET
Metric Counter 18 Register.
XAPM_MC19_OFFSET
Metric Counter 19 Register.
XAPM_MC20_OFFSET
Metric Counter 20 Register.
XAPM_MC21_OFFSET
Metric Counter 21 Register.
XAPM_MC22_OFFSET
Metric Counter 22 Register.
XAPM_MC23_OFFSET
Metric Counter 23 Register.
XAPM_MC24_OFFSET
Metric Counter 24 Register.
Referenced by XAxiPmon_GetMetricCounter.
XAPM_MC25_OFFSET
Metric Counter 25 Register.
XAPM_MC26_OFFSET
Metric Counter 26 Register.
XAPM_MC27_OFFSET
Metric Counter 27 Register.
XAPM_MC28_OFFSET
Metric Counter 28 Register.
XAPM_MC29_OFFSET
Metric Counter 29 Register.
XAPM_MC30_OFFSET
Metric Counter 30 Register.
XAPM_MC31_OFFSET
Metric Counter 31 Register.
XAPM_MC32_OFFSET
Metric Counter 32 Register.
XAPM_MC33_OFFSET
Metric Counter 33 Register.
XAPM_MC34_OFFSET
Metric Counter 34 Register.
XAPM_MC35_OFFSET
Metric Counter 35 Register.
XAPM_MC36_OFFSET
Metric Counter 36 Register.
Referenced by XAxiPmon_GetMetricCounter.
XAPM_MC37_OFFSET
Metric Counter 37 Register.
XAPM_MC38_OFFSET
Metric Counter 38 Register.
XAPM_MC39_OFFSET
Metric Counter 39 Register.
XAPM_MC40_OFFSET
Metric Counter 40 Register.
XAPM_MC41_OFFSET
Metric Counter 41 Register.
XAPM_MC42_OFFSET
Metric Counter 42 Register.
XAPM_MC43_OFFSET
Metric Counter 43 Register.
XAPM_MC44_OFFSET
Metric Counter 44 Register.
XAPM_MC45_OFFSET
Metric Counter 45 Register.
XAPM_MC46_OFFSET
Metric Counter 46 Register.
XAPM_MC47_OFFSET
Metric Counter 47 Register.
XAPM_SMC10_OFFSET
Sampled Metric Counter 10 Register.
Referenced by XAxiPmon_GetSampledMetricCounter.
XAPM_SMC11_OFFSET
Sampled Metric Counter 11 Register.
XAPM_SMC12_OFFSET
Sampled Metric Counter 12 Register.
Referenced by XAxiPmon_GetSampledMetricCounter.
XAPM_SMC13_OFFSET
Sampled Metric Counter 13 Register.
XAPM_SMC14_OFFSET
Sampled Metric Counter 14 Register.
XAPM_SMC15_OFFSET
Sampled Metric Counter 15 Register.
XAPM_SMC16_OFFSET
Sampled Metric Counter 16 Register.
XAPM_SMC17_OFFSET
Sampled Metric Counter 17 Register.
XAPM_SMC18_OFFSET
Sampled Metric Counter 18 Register.
XAPM_SMC19_OFFSET
Sampled Metric Counter 19 Register.
XAPM_SMC20_OFFSET
Sampled Metric Counter 20 Register.
XAPM_SMC21_OFFSET
Sampled Metric Counter 21 Register.
XAPM_SMC22_OFFSET
Sampled Metric Counter 22 Register.
XAPM_SMC23_OFFSET
Sampled Metric Counter 23 Register.
XAPM_SMC24_OFFSET
Sampled Metric Counter 24 Register.
Referenced by XAxiPmon_GetSampledMetricCounter.
XAPM_SMC25_OFFSET
Sampled Metric Counter 25 Register.
XAPM_SMC26_OFFSET
Sampled Metric Counter 26 Register.
XAPM_SMC27_OFFSET
Sampled Metric Counter 27 Register.
XAPM_SMC28_OFFSET
Sampled Metric Counter 28 Register.
XAPM_SMC29_OFFSET
Sampled Metric Counter 29 Register.
XAPM_SMC30_OFFSET
Sampled Metric Counter 30 Register.
XAPM_SMC31_OFFSET
Sampled Metric Counter 31 Register.
XAPM_SMC32_OFFSET
Sampled Metric Counter 32 Register.
XAPM_SMC33_OFFSET
Sampled Metric Counter 33 Register.
XAPM_SMC34_OFFSET
Sampled Metric Counter 34 Register.
XAPM_SMC35_OFFSET
Sampled Metric Counter 35 Register.
XAPM_SMC36_OFFSET
Sampled Metric Counter 36 Register.
Referenced by XAxiPmon_GetSampledMetricCounter.
XAPM_SMC37_OFFSET
Sampled Metric Counter 37 Register.
XAPM_SMC38_OFFSET
Sampled Metric Counter 38 Register.
XAPM_SMC39_OFFSET
Sampled Metric Counter 39 Register.
XAPM_SMC40_OFFSET
Sampled Metric Counter 40 Register.
XAPM_SMC41_OFFSET
Sampled Metric Counter 41 Register.
XAPM_SMC42_OFFSET
Sampled Metric Counter 42 Register.
XAPM_SMC43_OFFSET
Sampled Metric Counter 43 Register.
XAPM_SMC44_OFFSET
Sampled Metric Counter 44 Register.
XAPM_SMC45_OFFSET
Sampled Metric Counter 45 Register.
XAPM_SMC46_OFFSET
Sampled Metric Counter 46 Register.
XAPM_SMC47_OFFSET
Sampled Metric Counter 47 Register.
XAPM_CTL_OFFSET
Control Register.
Referenced by XAxiPmon_DisableEventLogTrigger, XAxiPmon_DisableMetricCounterTrigger, XAxiPmon_DisableMetricsCounter, XAxiPmon_EnableEventLog, XAxiPmon_EnableEventLogTrigger, XAxiPmon_EnableMetricCounterTrigger, XAxiPmon_EnableMetricsCounter, XAxiPmon_GetRdLatencyEnd, XAxiPmon_GetRdLatencyStart, XAxiPmon_GetWrLatencyEnd, XAxiPmon_GetWrLatencyStart, XAxiPmon_ResetFifo, XAxiPmon_ResetGlobalClkCounter, XAxiPmon_ResetMetricCounter, XAxiPmon_SetRdLatencyEnd, XAxiPmon_SetRdLatencyStart, XAxiPmon_SetWrLatencyEnd, XAxiPmon_SetWrLatencyStart, XAxiPmon_StartCounters, XAxiPmon_StartEventLog, XAxiPmon_StopCounters, XAxiPmon_StopEventLog.
XAPM_ID_OFFSET
Latency ID Register.
Referenced by XAxiPmon_GetReadId, XAxiPmon_GetWriteId, XAxiPmon_SetReadId, XAxiPmon_SetWriteId.
XAPM_IDMASK_OFFSET
ID Mask Register.
Referenced by XAxiPmon_GetReadIdMask, XAxiPmon_GetWriteIdMask, XAxiPmon_SetReadIdMask, XAxiPmon_SetWriteIdMask.
XAPM_RID_OFFSET
Latency Write ID Register.
Referenced by XAxiPmon_GetReadId, XAxiPmon_SetReadId.
XAPM_RIDMASK_OFFSET
Read ID Mask Register.
Referenced by XAxiPmon_GetReadIdMask, XAxiPmon_SetReadIdMask.
XAPM_FEC_OFFSET
Flag Enable Control Register.
Referenced by XAxiPmon_StartEventLog.
XAPM_SWD_OFFSET
Software-written Data Register.
Referenced by XAxiPmon_GetSwDataReg, XAxiPmon_SetSwDataReg.
XAPM_SICR_MCNTR_RST_MASK
Enable the Metric Counter Reset.
XAPM_SICR_LOAD_MASK
Load the Sample Interval Register Value into the counter.
XAPM_SICR_ENABLE_MASK
Enable the downcounter.
XAPM_IXR_MC9_OVERFLOW_MASK
Metric Counter 9 Overflow>
XAPM_IXR_MC8_OVERFLOW_MASK
Metric Counter 8 Overflow>
XAPM_IXR_MC7_OVERFLOW_MASK
Metric Counter 7 Overflow>
XAPM_IXR_MC6_OVERFLOW_MASK
Metric Counter 6 Overflow>
XAPM_IXR_MC5_OVERFLOW_MASK
Metric Counter 5 Overflow>
XAPM_IXR_MC4_OVERFLOW_MASK
Metric Counter 4 Overflow>
XAPM_IXR_MC3_OVERFLOW_MASK
Metric Counter 3 Overflow>
XAPM_IXR_MC2_OVERFLOW_MASK
Metric Counter 2 Overflow>
XAPM_IXR_MC1_OVERFLOW_MASK
Metric Counter 1 Overflow>
XAPM_IXR_MC0_OVERFLOW_MASK
Metric Counter 0 Overflow>
XAPM_IXR_FIFO_FULL_MASK
Event Log FIFO full>
XAPM_IXR_SIC_OVERFLOW_MASK
Sample Interval Counter Overflow>
Referenced by AxiPmonInterruptExample.
XAPM_IXR_GCC_OVERFLOW_MASK
Global Clock Counter Overflow>
XAPM_IXR_ALL_MASK
XAPM_CR_FIFO_RESET_MASK
FIFO Reset.
Referenced by XAxiPmon_ResetFifo.
XAPM_CR_GCC_RESET_MASK
Global Clk Counter Reset.
Referenced by XAxiPmon_ResetGlobalClkCounter.
XAPM_CR_GCC_ENABLE_MASK
Global Clk Counter Enable.
Referenced by XAxiPmon_StartCounters, XAxiPmon_StopCounters.
XAPM_CR_EVTLOG_EXTTRIGGER_MASK
Enable External trigger to start event Log
Referenced by XAxiPmon_DisableEventLogTrigger, XAxiPmon_EnableEventLogTrigger.
XAPM_CR_EVENTLOG_ENABLE_MASK
Event Log Enable.
Referenced by XAxiPmon_EnableEventLog, XAxiPmon_StartEventLog, XAxiPmon_StopEventLog.
XAPM_CR_RDLATENCY_END_MASK
Write Latency End point.
Referenced by XAxiPmon_GetRdLatencyEnd, XAxiPmon_SetRdLatencyEnd.
XAPM_CR_RDLATENCY_START_MASK
Read Latency Start point.
Referenced by XAxiPmon_GetRdLatencyStart, XAxiPmon_SetRdLatencyStart.
XAPM_CR_WRLATENCY_END_MASK
Write Latency End point.
Referenced by XAxiPmon_GetWrLatencyEnd, XAxiPmon_SetWrLatencyEnd.
XAPM_CR_WRLATENCY_START_MASK
Write Latency Start point.
Referenced by XAxiPmon_GetWrLatencyStart, XAxiPmon_SetWrLatencyStart.
XAPM_CR_IDFILTER_ENABLE_MASK
ID Filter Enable.
XAPM_CR_MCNTR_EXTTRIGGER_MASK
Enable External trigger to start Metric Counters.
Referenced by XAxiPmon_DisableMetricCounterTrigger, XAxiPmon_EnableMetricCounterTrigger.
XAPM_CR_MCNTR_RESET_MASK
Metrics Counter Reset.
Referenced by XAxiPmon_ResetMetricCounter.
XAPM_CR_MCNTR_ENABLE_MASK
Metrics Counter Enable.
Referenced by XAxiPmon_DisableMetricsCounter, XAxiPmon_EnableMetricsCounter, XAxiPmon_StartCounters, XAxiPmon_StopCounters.
XAPM_ID_RID_MASK
Read ID.
Referenced by XAxiPmon_GetReadId, XAxiPmon_SetReadId.
XAPM_ID_WID_MASK
Write ID.
Referenced by XAxiPmon_GetWriteId, XAxiPmon_SetWriteId.
XAPM_MASKID_RID_MASK
Read ID Mask.
Referenced by XAxiPmon_GetReadIdMask, XAxiPmon_SetReadIdMask.
XAPM_MASKID_WID_MASK
Write ID Mask.
Referenced by XAxiPmon_GetWriteIdMask, XAxiPmon_SetWriteIdMask.
XAxiPmon_Config XAxiPmon_ConfigTable[XPAR_XAXIPMON_NUM_INSTANCES][XPAR_XAXIPMON_NUM_INSTANCES]
This table contains configuration information for each System Monitor/ADC device in the system.
XAxiPmon_Config XAxiPmon_ConfigTable[][]
This table contains configuration information for each System Monitor/ADC device in the system.
s32 XAxiPmon_CfgInitialize(XAxiPmon *InstancePtr, XAxiPmon_Config *ConfigPtr, UINTPTR EffectiveAddr)
This function initializes a specific XAxiPmon device/instance.
Functions in xaxipmon.c.This function must be called prior to using the AXI Performance Monitor device. InstancePtr is a pointer to the XAxiPmon instance. ConfigPtr points to the XAxiPmon device configuration structure. EffectiveAddr is the device base address in the virtual memory address space. If the address translation is not used then the physical address is passed. Unexpected errors may occur if the address mapping is changed after this function is invoked. XST_SUCCESS if successful. The user needs to first call the XAxiPmon_LookupConfig() API which returns the Configuration structure pointer which is passed as a parameter to the XAxiPmon_CfgInitialize() API.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::FifoDepth, XAxiPmon_Config::FifoWidth, XAxiPmon_Config::GlobalClkCounterWidth, XAxiPmon_Config::HaveSampledCounters, XAxiPmon_Config::IntId, XAxiPmon_Config::IntrParent, XAxiPmon_Config::Is32BitFiltering, XAxiPmon_Config::IsEventCount, XAxiPmon_Config::IsEventLog, XAxiPmon::IsReady, XAxiPmon_Config::MetricSampleCounterWidth, XAxiPmon::Mode, XAxiPmon_Config::ModeAdvanced, XAxiPmon_Config::ModeProfile, XAxiPmon_Config::ModeTrace, XAxiPmon_Config::NumberofCounters, XAxiPmon_Config::NumberofSlots, XAxiPmon_Config::ScaleFactor, XAxiPmon_Config::TidWidth, XAPM_MODE_ADVANCED, XAPM_MODE_PROFILE, XAPM_MODE_TRACE, XAxiPmon_ResetFifo, XAxiPmon_ResetGlobalClkCounter, XAxiPmon_ResetMetricCounter.
Referenced by AxiPmonInterruptExample, AxiPmonPolledExample, main.
s32 XAxiPmon_ResetMetricCounter(XAxiPmon *InstancePtr)
This function resets all Metric Counters and Sampled Metric Counters of AXI Performance Monitor.
InstancePtr is a pointer to the XAxiPmon instance. XST_SUCCESS None.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_CR_MCNTR_RESET_MASK, XAPM_CTL_OFFSET, XAPM_MODE_TRACE, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
Referenced by ApmMetricConfig, XAxiPmon_CfgInitialize, XAxiPmon_SelfTest.
void XAxiPmon_ResetGlobalClkCounter(XAxiPmon *InstancePtr)
This function resets Global Clock Counter of AXI Performance Monitor.
InstancePtr is a pointer to the XAxiPmon instance. None. None.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_CR_GCC_RESET_MASK, XAPM_CTL_OFFSET, XAPM_MODE_ADVANCED, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
Referenced by ApmMetricConfig, XAxiPmon_CfgInitialize, XAxiPmon_SelfTest.
s32 XAxiPmon_ResetFifo(XAxiPmon *InstancePtr)
This function resets Streaming FIFO of AXI Performance Monitor.
InstancePtr is a pointer to the XAxiPmon instance. XST_SUCCESS None.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::IsEventLog, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_CR_FIFO_RESET_MASK, XAPM_CTL_OFFSET, XAPM_MODE_ADVANCED, XAPM_MODE_PROFILE, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
Referenced by XAxiPmon_CfgInitialize.
void XAxiPmon_SetIncrementerRange(XAxiPmon *InstancePtr, u8 IncrementerNum, u16 RangeUpper, u16 RangeLower)
This function sets Ranges for Incrementers depending on parameters passed.
InstancePtr is a pointer to the XAxiPmon instance. IncrementerNum specifies the Incrementer for which Ranges need to be set RangeUpper specifies the Upper limit in 32 bit Register RangeLower specifies the Lower limit in 32 bit Register None. None
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_MAX_COUNTERS, XAPM_MODE_ADVANCED, XAPM_RANGE0_OFFSET, XAxiPmon_WriteReg.
Referenced by AxiPmonInterruptExample, AxiPmonPolledExample, XAxiPmon_SelfTest.
void XAxiPmon_GetIncrementerRange(XAxiPmon *InstancePtr, u8 IncrementerNum, u16 *RangeUpper, u16 *RangeLower)
This function returns the Ranges of Incrementers Registers.
InstancePtr is a pointer to the XAxiPmon instance. IncrementerNum specifies the Incrementer for which Ranges need to be returned. RangeUpper specifies the user reference variable which returns the Upper Range Value of the specified Incrementer. RangeLower specifies the user reference variable which returns the Lower Range Value of the specified Incrementer. None. None
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_MAX_COUNTERS, XAPM_MODE_ADVANCED, XAPM_RANGE0_OFFSET, XAxiPmon_ReadReg.
Referenced by XAxiPmon_SelfTest.
void XAxiPmon_SetSampleInterval(XAxiPmon *InstancePtr, u32 SampleInterval)
This function sets the Sample Interval Register.
InstancePtr is a pointer to the XAxiPmon instance. SampleInterval is the Sample Interval value to be set None None.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_MODE_TRACE, XAPM_SI_LOW_OFFSET, XAxiPmon_WriteReg.
Referenced by AxiPmonInterruptExample, XAxiPmon_StartCounters.
void XAxiPmon_GetSampleInterval(XAxiPmon *InstancePtr, u32 *SampleInterval)
This function returns the contents of Sample Interval Register.
InstancePtr is a pointer to the XAxiPmon instance. SampleInterval is a pointer where the Sample Interval Counter value is returned. None. None.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_MODE_TRACE, XAPM_SI_LOW_OFFSET, XAxiPmon_ReadReg.
s32 XAxiPmon_SetMetrics(XAxiPmon *InstancePtr, u8 Slot, u8 Metrics, u8 CounterNum)
This function sets Metrics for specified Counter in the corresponding Metric Selector Register.
InstancePtr is a pointer to the XAxiPmon instance. Slot is the slot ID for which specified counter has to be connected. Metrics is one of the Metric Sets. User has to use XAPM_METRIC_SET_* macros in xaxipmon.h for this parameter CounterNum is the Counter Number. The valid values are 0 to 9. XST_SUCCESS if Success XST_FAILURE if Failure None.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_MAX_AGENTS, XAPM_MAX_COUNTERS, XAPM_METRIC_SET_22, XAPM_METRIC_SET_30, XAPM_MODE_ADVANCED, XAPM_MSR0_OFFSET, XAPM_MSR1_OFFSET, XAPM_MSR2_OFFSET, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
Referenced by ApmMetricConfig, AxiPmonInterruptExample, AxiPmonPolledExample.
s32 XAxiPmon_GetMetrics(XAxiPmon *InstancePtr, u8 CounterNum, u8 *Metrics, u8 *Slot)
This function returns Metrics in the specified Counter from the corresponding Metric Selector Register.
InstancePtr is a pointer to the XAxiPmon instance. CounterNum is the Counter Number. The valid values are 0 to 9. Metrics is a reference parameter from application where metrics of specified counter is filled. Slot is a reference parameter in which slot Id of specified counter is filled XST_SUCCESS if Success XST_FAILURE if Failure None.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_MAX_COUNTERS, XAPM_MODE_ADVANCED, XAPM_MSR0_OFFSET, XAPM_MSR1_OFFSET, XAPM_MSR2_OFFSET, XAxiPmon_ReadReg.
void XAxiPmon_GetGlobalClkCounter(XAxiPmon *InstancePtr, u32 *CntHighValue, u32 *CntLowValue)
This function returns the contents of the Global Clock Counter Register.
InstancePtr is a pointer to the XAxiPmon instance. CntHighValue is the user space pointer with which upper 32 bits of Global Clock Counter has to be filled CntLowValue is the user space pointer with which lower 32 bits of Global Clock Counter has to be filled None. None.
References XAxiPmon::Config, XAxiPmon_Config::GlobalClkCounterWidth, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_GCC_HIGH_OFFSET, XAPM_GCC_LOW_OFFSET, XAPM_MODE_ADVANCED, XAxiPmon_ReadReg.
Referenced by AxiPmonPolledExample.
u32 XAxiPmon_GetMetricCounter(XAxiPmon *InstancePtr, u32 CounterNum)
This function returns the contents of the Metric Counter Register.
InstancePtr is a pointer to the XAxiPmon instance. CounterNum is the number of the Metric Counter to be read. Use the XAPM_METRIC_COUNTER* defines for the counter number in xaxipmon.h. The valid values are 0 (XAPM_METRIC_COUNTER_0) to 47(XAPM_METRIC_COUNTER_47). RegValue is the content of specified Metric Counter. None.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_MAX_COUNTERS_PROFILE, XAPM_MC0_OFFSET, XAPM_MC10_OFFSET, XAPM_MC12_OFFSET, XAPM_MC24_OFFSET, XAPM_MC36_OFFSET, XAPM_MODE_TRACE, XAxiPmon_ReadReg.
Referenced by AxiPmonPolledExample, ReadMetrics.
u32 XAxiPmon_GetSampledMetricCounter(XAxiPmon *InstancePtr, u32 CounterNum)
This function returns the contents of the Sampled Metric Counter Register.
InstancePtr is a pointer to the XAxiPmon instance. CounterNum is the number of the Sampled Metric Counter to read. Use the XAPM_METRIC_COUNTER* defines for the counter number in xaxipmon.h. The valid values are 0 (XAPM_METRIC_COUNTER_0) to 47(XAPM_METRIC_COUNTER_47). RegValue is the content of specified Sampled Metric Counter. None.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::HaveSampledCounters, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_MAX_COUNTERS_PROFILE, XAPM_MODE_ADVANCED, XAPM_MODE_PROFILE, XAPM_MODE_TRACE, XAPM_SMC0_OFFSET, XAPM_SMC10_OFFSET, XAPM_SMC12_OFFSET, XAPM_SMC24_OFFSET, XAPM_SMC36_OFFSET, XAxiPmon_ReadReg.
Referenced by AxiPmonInterruptExample.
u32 XAxiPmon_GetIncrementer(XAxiPmon *InstancePtr, u32 IncrementerNum)
This function returns the contents of the Incrementer Register.
InstancePtr is a pointer to the XAxiPmon instance. IncrementerNum is the number of the Incrementer register to read.Use the XAPM_INCREMENTER_* defines for the Incrementer number.The valid values are 0 (XAPM_INCREMENTER_0) to 9 (XAPM_INCREMENTER_9). IncrementerNum is the number of the specified Incrementer register RegValue is content of specified Metric Incrementer register. None.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::IsEventCount, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_INC0_OFFSET, XAPM_MAX_COUNTERS, XAPM_MODE_ADVANCED, XAxiPmon_ReadReg.
u32 XAxiPmon_GetSampledIncrementer(XAxiPmon *InstancePtr, u32 IncrementerNum)
This function returns the contents of the Sampled Incrementer Register.
InstancePtr is a pointer to the XAxiPmon instance. IncrementerNum is the number of the Sampled Incrementer register to read.Use the XAPM_INCREMENTER_* defines for the Incrementer number.The valid values are 0 (XAPM_INCREMENTER_0) to 9 (XAPM_INCREMENTER_9). IncrementerNum is the number of the specified Sampled Incrementer register RegValue is content of specified Sampled Incrementer register. None.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::HaveSampledCounters, XAxiPmon_Config::IsEventCount, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_MAX_COUNTERS, XAPM_MODE_ADVANCED, XAPM_SINC0_OFFSET, XAxiPmon_ReadReg.
void XAxiPmon_SetSwDataReg(XAxiPmon *InstancePtr, u32 SwData)
This function sets Software-written Data Register.
InstancePtr is a pointer to the XAxiPmon instance. SwData is the Software written Data. None. None.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAPM_SWD_OFFSET, XAxiPmon_WriteReg.
u32 XAxiPmon_GetSwDataReg(XAxiPmon *InstancePtr)
This function returns contents of Software-written Data Register.
InstancePtr is a pointer to the XAxiPmon instance. SwData. None.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAPM_SWD_OFFSET, XAxiPmon_ReadReg.
s32 XAxiPmon_StartEventLog(XAxiPmon *InstancePtr, u32 FlagEnables)
This function enables the following in the AXI Performance Monitor:
Event logging InstancePtr is a pointer to the XAxiPmon instance. FlagEnables is a value to write to the flag enables register defined by XAPM_FEC_OFFSET. It is recommended to use the XAPM_FEC_*_MASK mask bits to generate. A value of 0x0 will disable all events to the event log streaming FIFO. XST_SUCCESS None
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::IsEventLog, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_CR_EVENTLOG_ENABLE_MASK, XAPM_CTL_OFFSET, XAPM_FEC_OFFSET, XAPM_MODE_ADVANCED, XAPM_MODE_TRACE, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
s32 XAxiPmon_StopEventLog(XAxiPmon *InstancePtr)
This function disables the following in the AXI Performance Monitor:
Event logging InstancePtr is a pointer to the XAxiPmon instance. XST_SUCCESS None
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::IsEventLog, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_CR_EVENTLOG_ENABLE_MASK, XAPM_CTL_OFFSET, XAPM_MODE_ADVANCED, XAPM_MODE_TRACE, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
s32 XAxiPmon_StartCounters(XAxiPmon *InstancePtr, u32 SampleInterval)
This function enables the following in the AXI Performance Monitor:
Global clock counterAll metric countersAll sampled metric counters InstancePtr is a pointer to the XAxiPmon instance. SampleInterval is the sample interval for the sampled metric counters XST_SUCCESS None
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::IsEventCount, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_CR_GCC_ENABLE_MASK, XAPM_CR_MCNTR_ENABLE_MASK, XAPM_CTL_OFFSET, XAPM_MODE_ADVANCED, XAPM_MODE_PROFILE, XAxiPmon_EnableSampleIntervalCounter, XAxiPmon_LoadSampleIntervalCounter, XAxiPmon_ReadReg, XAxiPmon_SetSampleInterval, XAxiPmon_WriteReg.
Referenced by ApmMetricConfig.
s32 XAxiPmon_StopCounters(XAxiPmon *InstancePtr)
This function disables the following in the AXI Performance Monitor:
Global clock counterAll metric counters InstancePtr is a pointer to the XAxiPmon instance. XST_SUCCESS None
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::IsEventCount, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_CR_GCC_ENABLE_MASK, XAPM_CR_MCNTR_ENABLE_MASK, XAPM_CTL_OFFSET, XAPM_MODE_ADVANCED, XAPM_MODE_PROFILE, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
Referenced by ReadMetrics.
void XAxiPmon_EnableMetricsCounter(XAxiPmon *InstancePtr)
This function enables Metric Counters.
InstancePtr is a pointer to the XAxiPmon instance. None None
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::IsEventCount, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_CR_MCNTR_ENABLE_MASK, XAPM_CTL_OFFSET, XAPM_MODE_ADVANCED, XAPM_MODE_PROFILE, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
Referenced by ApmMetricConfig, AxiPmonInterruptExample, AxiPmonPolledExample.
void XAxiPmon_DisableMetricsCounter(XAxiPmon *InstancePtr)
This function disables the Metric Counters.
InstancePtr is a pointer to the XAxiPmon instance. None None
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::IsEventCount, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_CR_MCNTR_ENABLE_MASK, XAPM_CTL_OFFSET, XAPM_MODE_ADVANCED, XAPM_MODE_PROFILE, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
Referenced by AxiPmonInterruptExample, AxiPmonPolledExample, main.
void XAxiPmon_SetLogEnableRanges(XAxiPmon *InstancePtr, u32 CounterNum, u16 RangeUpper, u16 RangeLower)
This function sets the Upper and Lower Ranges for specified Metric Counter Log Enable Register.Event Logging starts when corresponding Metric Counter value falls in between these ranges.
InstancePtr is a pointer to the XAxiPmon instance. CounterNum is the Metric Counter number for which Ranges are to be assigned.Use the XAPM_METRIC_COUNTER* defines for the counter number in xaxipmon.h. The valid values are 0 (XAPM_METRIC_COUNTER_0) to 9 (XAPM_METRIC_COUNTER_9). RangeUpper specifies the Upper limit in 32 bit Register RangeLower specifies the Lower limit in 32 bit Register None None.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::IsEventCount, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_MAX_COUNTERS, XAPM_MC0LOGEN_OFFSET, XAPM_MODE_ADVANCED, XAxiPmon_WriteReg.
void XAxiPmon_GetLogEnableRanges(XAxiPmon *InstancePtr, u32 CounterNum, u16 *RangeUpper, u16 *RangeLower)
This function returns the Ranges of specified Metric Counter Log Enable Register.
InstancePtr is a pointer to the XAxiPmon instance. CounterNum is the Metric Counter number for which Ranges are to be returned.Use the XAPM_METRIC_COUNTER* defines for the counter number in xaxipmon.h. The valid values are 0 (XAPM_METRIC_COUNTER_0) to 9 (XAPM_METRIC_COUNTER_9). RangeUpper specifies the user reference variable which returns the Upper Range Value of the specified Metric Counter Log Enable Register. RangeLower specifies the user reference variable which returns the Lower Range Value of the specified Metric Counter Log Enable Register. None.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::IsEventCount, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_MAX_COUNTERS, XAPM_MC0LOGEN_OFFSET, XAPM_MODE_ADVANCED, XAxiPmon_ReadReg.
void XAxiPmon_EnableEventLog(XAxiPmon *InstancePtr)
This function enables Event Logging.
InstancePtr is a pointer to the XAxiPmon instance. None None
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::IsEventLog, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_CR_EVENTLOG_ENABLE_MASK, XAPM_CTL_OFFSET, XAPM_MODE_ADVANCED, XAPM_MODE_TRACE, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
void XAxiPmon_EnableMetricCounterTrigger(XAxiPmon *InstancePtr)
This function enables External trigger pulse so that Metric Counters can be started on external trigger pulse for a Slot.
InstancePtr is a pointer to the XAxiPmon instance. None None
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_CR_MCNTR_EXTTRIGGER_MASK, XAPM_CTL_OFFSET, XAPM_MODE_TRACE, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
void XAxiPmon_DisableMetricCounterTrigger(XAxiPmon *InstancePtr)
This function disables the External trigger pulse used to start Metric Counters on external trigger pulse for a Slot.
InstancePtr is a pointer to the XAxiPmon instance. None None
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_CR_MCNTR_EXTTRIGGER_MASK, XAPM_CTL_OFFSET, XAPM_MODE_TRACE, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
void XAxiPmon_EnableEventLogTrigger(XAxiPmon *InstancePtr)
This function enables External trigger pulse for Event Log so that Event Logging can be started on external trigger pulse for a Slot.
InstancePtr is a pointer to the XAxiPmon instance. None None
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_CR_EVTLOG_EXTTRIGGER_MASK, XAPM_CTL_OFFSET, XAPM_MODE_PROFILE, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
void XAxiPmon_DisableEventLogTrigger(XAxiPmon *InstancePtr)
This function disables the External trigger pulse used to start Event Log on external trigger pulse for a Slot.
InstancePtr is a pointer to the XAxiPmon instance. None None
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_CR_EVTLOG_EXTTRIGGER_MASK, XAPM_CTL_OFFSET, XAPM_MODE_PROFILE, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
const char * XAxiPmon_GetMetricName(u8 Metrics)
This function returns a name for a given Metric.
Metrics is one of the Metric Sets. User has to use XAPM_METRIC_SET_* macros in xaxipmon.h for this parameter const char * None
References XAPM_METRIC_SET_0, XAPM_METRIC_SET_1, XAPM_METRIC_SET_10, XAPM_METRIC_SET_11, XAPM_METRIC_SET_12, XAPM_METRIC_SET_13, XAPM_METRIC_SET_14, XAPM_METRIC_SET_15, XAPM_METRIC_SET_16, XAPM_METRIC_SET_17, XAPM_METRIC_SET_18, XAPM_METRIC_SET_19, XAPM_METRIC_SET_2, XAPM_METRIC_SET_20, XAPM_METRIC_SET_21, XAPM_METRIC_SET_22, XAPM_METRIC_SET_3, XAPM_METRIC_SET_30, XAPM_METRIC_SET_4, XAPM_METRIC_SET_5, XAPM_METRIC_SET_6, XAPM_METRIC_SET_7, XAPM_METRIC_SET_8, XAPM_METRIC_SET_9.
void XAxiPmon_SetWriteId(XAxiPmon *InstancePtr, u32 WriteId)
This function sets Write ID in ID register.
InstancePtr is a pointer to the XAxiPmon instance. WriteId is the Write ID to be written in ID register. None. If ID filtering for write is of 32 bits(for Zynq MP APM) width then WriteID is written to XAPM_ID_OFFSET or if it is 16 bit width then lower 16 bits of WriteID are written to XAPM_ID_OFFSET.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::Is32BitFiltering, XAxiPmon::IsReady, XAPM_ID_OFFSET, XAPM_ID_WID_MASK, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
void XAxiPmon_SetReadId(XAxiPmon *InstancePtr, u32 ReadId)
This function sets Read ID in ID register.
InstancePtr is a pointer to the XAxiPmon instance. ReadId is the Read ID to be written in ID register. None. If ID filtering for read is of 32 bits(for Zynq MP APM) width then ReadId is written to XAPM_RID_OFFSET or if it is 16 bit width then lower 16 bits of ReadId are written to XAPM_ID_OFFSET.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::Is32BitFiltering, XAxiPmon::IsReady, XAPM_ID_OFFSET, XAPM_ID_RID_MASK, XAPM_RID_OFFSET, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
u32 XAxiPmon_GetWriteId(XAxiPmon *InstancePtr)
This function returns Write ID in ID register.
InstancePtr is a pointer to the XAxiPmon instance. WriteId is the required Write ID in ID register. None. If ID filtering for write is of 32 bits(for Zynq MP APM) width then 32 bit XAPM_ID_OFFSET contents are returned or if it is 16 bit width then lower 16 bits of XAPM_ID_OFFSET register are returned.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::Is32BitFiltering, XAxiPmon::IsReady, XAPM_ID_OFFSET, XAPM_ID_WID_MASK, XAxiPmon_ReadReg.
u32 XAxiPmon_GetReadId(XAxiPmon *InstancePtr)
This function returns Read ID in ID register.
InstancePtr is a pointer to the XAxiPmon instance. ReadId is the required Read ID in ID register. None. If ID filtering for write is of 32 bits(for Zynq MP APM) width then 32 bit XAPM_RID_OFFSET contents are returned or if it is 16 bit width then higher 16 bits of XAPM_ID_OFFSET register are returned.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::Is32BitFiltering, XAxiPmon::IsReady, XAPM_ID_OFFSET, XAPM_ID_RID_MASK, XAPM_RID_OFFSET, XAxiPmon_ReadReg.
void XAxiPmon_SetWrLatencyStart(XAxiPmon *InstancePtr, u8 Param)
This function sets Latency Start point to calculate write latency.
InstancePtr is a pointer to the XAxiPmon instance. Param is XAPM_LATENCY_ADDR_ISSUE or XAPM_LATENCY_ADDR_ACCEPT in xaxipmon.h. None Param can be 0 - XAPM_LATENCY_ADDR_ISSUE or 1 - XAPM_LATENCY_ADDR_ACCEPT
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAPM_CR_WRLATENCY_START_MASK, XAPM_CTL_OFFSET, XAPM_LATENCY_ADDR_ACCEPT, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
void XAxiPmon_SetWrLatencyEnd(XAxiPmon *InstancePtr, u8 Param)
This function sets Latency End point to calculate write latency.
InstancePtr is a pointer to the XAxiPmon instance. Param is XAPM_LATENCY_LASTWR or XAPM_LATENCY_FIRSTWR in xaxipmon.h. None Param can be 0 - XAPM_LATENCY_LASTWR or 1 - XAPM_LATENCY_FIRSTWR
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAPM_CR_WRLATENCY_END_MASK, XAPM_CTL_OFFSET, XAPM_LATENCY_FIRSTWR, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
void XAxiPmon_SetRdLatencyStart(XAxiPmon *InstancePtr, u8 Param)
This function sets Latency Start point to calculate read latency.
InstancePtr is a pointer to the XAxiPmon instance. Param is XAPM_LATENCY_ADDR_ISSUE or XAPM_LATENCY_ADDR_ACCEPT in xaxipmon.h. None Param can be 0 - XAPM_LATENCY_ADDR_ISSUE or 1 - XAPM_LATENCY_ADDR_ACCEPT
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAPM_CR_RDLATENCY_START_MASK, XAPM_CTL_OFFSET, XAPM_LATENCY_ADDR_ACCEPT, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
void XAxiPmon_SetRdLatencyEnd(XAxiPmon *InstancePtr, u8 Param)
This function sets Latency End point to calculate read latency.
InstancePtr is a pointer to the XAxiPmon instance. Param is XAPM_LATENCY_LASTRD or XAPM_LATENCY_FIRSTRD in xaxipmon.h. None Param can be 0 - XAPM_LATENCY_LASTRD or 1 - XAPM_LATENCY_FIRSTRD
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAPM_CR_RDLATENCY_END_MASK, XAPM_CTL_OFFSET, XAPM_LATENCY_FIRSTRD, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
u8 XAxiPmon_GetWrLatencyStart(XAxiPmon *InstancePtr)
This function returns Write Latency Start point.
InstancePtr is a pointer to the XAxiPmon instance. Returns 0 - XAPM_LATENCY_ADDR_ISSUE or 1 - XAPM_LATENCY_ADDR_ACCEPT None
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAPM_CR_WRLATENCY_START_MASK, XAPM_CTL_OFFSET, XAPM_LATENCY_ADDR_ACCEPT, XAPM_LATENCY_ADDR_ISSUE, XAxiPmon_ReadReg.
u8 XAxiPmon_GetWrLatencyEnd(XAxiPmon *InstancePtr)
This function returns Write Latency End point.
InstancePtr is a pointer to the XAxiPmon instance. Returns 0 - XAPM_LATENCY_LASTWR or 1 - XAPM_LATENCY_FIRSTWR. None
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAPM_CR_WRLATENCY_END_MASK, XAPM_CTL_OFFSET, XAPM_LATENCY_FIRSTWR, XAPM_LATENCY_LASTWR, XAxiPmon_ReadReg.
u8 XAxiPmon_GetRdLatencyStart(XAxiPmon *InstancePtr)
This function returns read Latency Start point.
InstancePtr is a pointer to the XAxiPmon instance. Returns 0 - XAPM_LATENCY_ADDR_ISSUE or 1 - XAPM_LATENCY_ADDR_ACCEPT None
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAPM_CR_RDLATENCY_START_MASK, XAPM_CTL_OFFSET, XAPM_LATENCY_ADDR_ACCEPT, XAPM_LATENCY_ADDR_ISSUE, XAxiPmon_ReadReg.
u8 XAxiPmon_GetRdLatencyEnd(XAxiPmon *InstancePtr)
This function returns Read Latency End point.
InstancePtr is a pointer to the XAxiPmon instance. Returns 0 - XAPM_LATENCY_LASTRD or 1 - XAPM_LATENCY_FIRSTRD. None
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAPM_CR_RDLATENCY_END_MASK, XAPM_CTL_OFFSET, XAPM_LATENCY_FIRSTRD, XAPM_LATENCY_LASTRD, XAxiPmon_ReadReg.
void XAxiPmon_SetWriteIdMask(XAxiPmon *InstancePtr, u32 WrMask)
This function sets Write ID Mask in ID Mask register.
InstancePtr is a pointer to the XAxiPmon instance. WrMask is the Write ID mask to be written in ID register. None. If ID masking for write is of 32 bits(for Zynq MP APM) width then WrMask is written to XAPM_IDMASK_OFFSET or if it is 16 bit width then lower 16 bits of WrMask are written to XAPM_IDMASK_OFFSET.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::Is32BitFiltering, XAxiPmon::IsReady, XAPM_IDMASK_OFFSET, XAPM_MASKID_WID_MASK, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
void XAxiPmon_SetReadIdMask(XAxiPmon *InstancePtr, u32 RdMask)
This function sets Read ID Mask in ID Mask register.
InstancePtr is a pointer to the XAxiPmon instance. RdMask is the Read ID mask to be written in ID Mask register. None. If ID masking for read is of 32 bits(for Zynq MP APM) width then RdMask is written to XAPM_RIDMASK_OFFSET or if it is 16 bit width then lower 16 bits of RdMask are written to XAPM_IDMASK_OFFSET.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::Is32BitFiltering, XAxiPmon::IsReady, XAPM_IDMASK_OFFSET, XAPM_MASKID_RID_MASK, XAPM_RIDMASK_OFFSET, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
u32 XAxiPmon_GetWriteIdMask(XAxiPmon *InstancePtr)
This function returns Write ID Mask in ID Mask register.
InstancePtr is a pointer to the XAxiPmon instance. WrMask is the required Write ID Mask in ID Mask register. If ID masking for write is of 32 bits(for Zynq MP APM) width then 32 bit XAPM_IDMASK_OFFSET contents are returned or if it is 16 bit width then lower 16 bits of XAPM_IDMASK_OFFSET register are returned.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::Is32BitFiltering, XAxiPmon::IsReady, XAPM_IDMASK_OFFSET, XAPM_MASKID_WID_MASK, XAxiPmon_ReadReg.
u32 XAxiPmon_GetReadIdMask(XAxiPmon *InstancePtr)
This function returns Read ID Mask in ID Mask register.
InstancePtr is a pointer to the XAxiPmon instance. RdMask is the required Read ID Mask in ID Mask register. If ID masking for read is of 32 bits(for Zynq MP APM) width then 32 bit XAPM_RIDMASK_OFFSET contents are returned or if it is 16 bit width then higher 16 bits of XAPM_IDMASK_OFFSET register are returned.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::Is32BitFiltering, XAxiPmon::IsReady, XAPM_IDMASK_OFFSET, XAPM_MASKID_RID_MASK, XAPM_RIDMASK_OFFSET, XAxiPmon_ReadReg.
XAxiPmon_Config * XAxiPmon_LookupConfig(UINTPTR BaseAddress)
Functions in xaxipmon_sinit.c.
Looks up the device configuration based on the unique device ID/BaseAddress.The XAxiPmon_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xaxipmon.h for the definition of XAxiPmon_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XAxiPmon_Config::Name.
Referenced by AxiPmonInterruptExample, AxiPmonPolledExample, main.
s32 XAxiPmon_SelfTest(XAxiPmon *InstancePtr)
Functions in xaxipmon_selftest.c.
Run a self-test on the driver/device.The test Resets the device,Writes a value into the Range Registers of Incrementer 0 and reads it back for comparison.Resets the device again. InstancePtr is a pointer to the XAxiPmon instance. XST_SUCCESS if the value read from the Range Register of Incrementer 0 is the same as the value written.XST_FAILURE Otherwise This is a destructive test in that resets of the device are performed. Refer to the device specification for the device status after the reset operation.
References XAxiPmon::IsReady, XAPM_INCREMENTER_0, XAPM_TEST_RANGELOWER_VALUE, XAPM_TEST_RANGEUPPER_VALUE, XAxiPmon_GetIncrementerRange, XAxiPmon_ResetGlobalClkCounter, XAxiPmon_ResetMetricCounter, XAxiPmon_SetIncrementerRange.
Referenced by AxiPmonInterruptExample, AxiPmonPolledExample.
XAXIPMON_H
XAxiPmon_IntrGlobalEnable
This routine enables the Global Interrupt.
InstancePtr is a pointer to the XAxiPmon instance. None. C-Style signature: void XAxiPmon_IntrGlobalEnable(XAxiPmon *InstancePtr)
Referenced by AxiPmonInterruptExample.
XAxiPmon_IntrGlobalDisable
This routine disables the Global Interrupt.
InstancePtr is a pointer to the XAxiPmon instance. None. C-Style signature: void XAxiPmon_IntrGlobalDisable(XAxiPmon *InstancePtr)
Referenced by AxiPmonInterruptExample.
XAxiPmon_IntrEnable
This routine enables interrupt(s).
Use the XAPM_IXR_* constants defined in xaxipmon_hw.h to create the bit-mask to enable interrupts. InstancePtr is a pointer to the XAxiPmon instance. Mask is the mask to enable. Bit positions of 1 will be enabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XAPM_IXR__* bits defined in xaxipmon_hw.h. None. C-Style signature: void XAxiPmon_IntrEnable(XAxiPmon *InstancePtr, u32 Mask)
Referenced by AxiPmonInterruptExample.
XAxiPmon_IntrDisable
This routine disable interrupt(s).
Use the XAPM_IXR_* constants defined in xaxipmon_hw.h to create the bit-mask to disable interrupts. InstancePtr is a pointer to the XAxiPmon instance. Mask is the mask to disable. Bit positions of 1 will be disabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XAPM_IXR_* bits defined in xaxipmon_hw.h. None. C-Style signature: void XAxiPmon_IntrEnable(XAxiPmon *InstancePtr, u32 Mask)
Referenced by AxiPmonInterruptExample.
XAxiPmon_IntrClear
This routine clears the specified interrupt(s).
InstancePtr is a pointer to the XAxiPmon instance. Mask is the mask to clear. Bit positions of 1 will be cleared. This mask is formed by OR'ing XAPM_IXR_* bits defined in xaxipmon_hw.h. None. C-Style signature: void XAxiPmon_IntrClear(XAxiPmon *InstancePtr, u32 Mask)
XAxiPmon_IntrGetStatus
This routine returns the Interrupt Status Register.
InstancePtr is a pointer to the XAxiPmon instance. Interrupt Status Register contents C-Style signature: void XAxiPmon_IntrClear(XAxiPmon *InstancePtr)
XAxiPmon_EnableGlobalClkCounter
This function enables the Global Clock Counter.
InstancePtr is a pointer to the XAxiPmon instance. None C-Style signature: void XAxiPmon_EnableGlobalClkCounter(XAxiPmon *InstancePtr)
Referenced by AxiPmonPolledExample.
XAxiPmon_DisableGlobalClkCounter
This function disbles the Global Clock Counter.
InstancePtr is a pointer to the XAxiPmon instance. None C-Style signature: void XAxiPmon_DisableGlobalClkCounter(XAxiPmon *InstancePtr)
Referenced by AxiPmonPolledExample.
XAxiPmon_EnableFlag
This function enables the specified flag in Flag Control Register.
InstancePtr is a pointer to the XAxiPmon instance. Flag is one of the XAPM_FLAG_* masks defined in xaxipmon.h None C-Style signature: void XAxiPmon_EnableFlag(XAxiPmon *InstancePtr)
XAxiPmon_DisableFlag
This function disables the specified flag in Flag Control Register.
InstancePtr is a pointer to the XAxiPmon instance. Flag is one of the XAPM_FLAG_* masks defined in xaxipmon.h* None C-Style signature: void XAxiPmon_DisableFlag(XAxiPmon *InstancePtr)
XAxiPmon_LoadSampleIntervalCounter
This function loads the sample interval register value into the sample interval counter.
InstancePtr is a pointer to the XAxiPmon instance. None C-Style signature: void XAxiPmon_LoadSampleIntervalCounter(XAxiPmon *InstancePtr)
Referenced by AxiPmonInterruptExample, XAxiPmon_StartCounters.
XAxiPmon_EnableSampleIntervalCounter
This enables the down count of the sample interval counter.
InstancePtr is a pointer to the XAxiPmon instance. None C-Style signature: void XAxiPmon_EnableSampleIntervalCounter(XAxiPmon *InstancePtr)
Referenced by AxiPmonInterruptExample, XAxiPmon_StartCounters.
XAxiPmon_DisableSampleIntervalCounter
This disables the down count of the sample interval counter.
InstancePtr is a pointer to the XAxiPmon instance. None C-Style signature: void XAxiPmon_DisableSampleIntervalCounter(XAxiPmon *InstancePtr)
Referenced by AxiPmonInterruptExample.
XAxiPmon_EnableMetricCounterReset
This enables Reset of Metric Counters when Sample Interval Counter lapses.
InstancePtr is a pointer to the XAxiPmon instance. None C-Style signature: void XAxiPmon_EnableMetricCounterReset(XAxiPmon *InstancePtr)
XAxiPmon_DisableMetricCounterReset
This disables the down count of the sample interval counter.
InstancePtr is a pointer to the XAxiPmon instance. None C-Style signature: void XAxiPmon_DisableMetricCounterReset(XAxiPmon *InstancePtr)
XAxiPmon_EnableIDFilter
This function enables the ID Filter Masking.
InstancePtr is a pointer to the XAxiPmon instance. None C-Style signature: void XAxiPmon_EnableIDFilter(XAxiPmon *InstancePtr)
XAxiPmon_DisableIDFilter
This function disbles the ID Filter masking.
InstancePtr is a pointer to the XAxiPmon instance. None C-Style signature: void XAxiPmon_DisableIDFilter(XAxiPmon *InstancePtr)
XAxiPmon_SampleMetrics
This function samples Metric Counters to Sampled Metric Counters by reading Sample Register and also returns interval.
i.e. the number of clocks in between previous read to the current read of sample register. InstancePtr is a pointer to the XAxiPmon instance. Interval. i.e. the number of clocks in between previous read to the current read of sample register. C-Style signature: u32 XAxiPmon_SampleMetrics(XAxiPmon *InstancePtr)
XAXIPMON_HW_H
XAxiPmon_ReadReg
Read a register of the AXI Performance Monitor device.
This macro provides register access to all registers using the register offsets defined above. BaseAddress contains the base address of the device. RegOffset is the offset of the register to read. The contents of the register. C-style Signature: u32 XAxiPmon_ReadReg(u32 BaseAddress, u32 RegOffset);
Referenced by XAxiPmon_DisableEventLogTrigger, XAxiPmon_DisableMetricCounterTrigger, XAxiPmon_DisableMetricsCounter, XAxiPmon_EnableEventLog, XAxiPmon_EnableEventLogTrigger, XAxiPmon_EnableMetricCounterTrigger, XAxiPmon_EnableMetricsCounter, XAxiPmon_GetGlobalClkCounter, XAxiPmon_GetIncrementer, XAxiPmon_GetIncrementerRange, XAxiPmon_GetLogEnableRanges, XAxiPmon_GetMetricCounter, XAxiPmon_GetMetrics, XAxiPmon_GetRdLatencyEnd, XAxiPmon_GetRdLatencyStart, XAxiPmon_GetReadId, XAxiPmon_GetReadIdMask, XAxiPmon_GetSampledIncrementer, XAxiPmon_GetSampledMetricCounter, XAxiPmon_GetSampleInterval, XAxiPmon_GetSwDataReg, XAxiPmon_GetWriteId, XAxiPmon_GetWriteIdMask, XAxiPmon_GetWrLatencyEnd, XAxiPmon_GetWrLatencyStart, XAxiPmon_ResetFifo, XAxiPmon_ResetGlobalClkCounter, XAxiPmon_ResetMetricCounter, XAxiPmon_SetMetrics, XAxiPmon_SetRdLatencyEnd, XAxiPmon_SetRdLatencyStart, XAxiPmon_SetReadId, XAxiPmon_SetReadIdMask, XAxiPmon_SetWriteId, XAxiPmon_SetWriteIdMask, XAxiPmon_SetWrLatencyEnd, XAxiPmon_SetWrLatencyStart, XAxiPmon_StartCounters, XAxiPmon_StartEventLog, XAxiPmon_StopCounters, XAxiPmon_StopEventLog.
XAxiPmon_WriteReg
Write a register of the AXI Performance Monitor device.
This macro provides register access to all registers using the register offsets defined above. BaseAddress contains the base address of the device. RegOffset is the offset of the register to write. Data is the value to write to the register. None. C-style Signature: void XAxiPmon_WriteReg(u32 BaseAddress, u32 RegOffset,u32 Data)
Referenced by XAxiPmon_DisableEventLogTrigger, XAxiPmon_DisableMetricCounterTrigger, XAxiPmon_DisableMetricsCounter, XAxiPmon_EnableEventLog, XAxiPmon_EnableEventLogTrigger, XAxiPmon_EnableMetricCounterTrigger, XAxiPmon_EnableMetricsCounter, XAxiPmon_ResetFifo, XAxiPmon_ResetGlobalClkCounter, XAxiPmon_ResetMetricCounter, XAxiPmon_SetIncrementerRange, XAxiPmon_SetLogEnableRanges, XAxiPmon_SetMetrics, XAxiPmon_SetRdLatencyEnd, XAxiPmon_SetRdLatencyStart, XAxiPmon_SetReadId, XAxiPmon_SetReadIdMask, XAxiPmon_SetSampleInterval, XAxiPmon_SetSwDataReg, XAxiPmon_SetWriteId, XAxiPmon_SetWriteIdMask, XAxiPmon_SetWrLatencyEnd, XAxiPmon_SetWrLatencyStart, XAxiPmon_StartCounters, XAxiPmon_StartEventLog, XAxiPmon_StopCounters, XAxiPmon_StopEventLog.
XAPM_TEST_RANGEUPPER_VALUE
Test Value for Upper Range.
Referenced by XAxiPmon_SelfTest.
XAPM_TEST_RANGELOWER_VALUE
Test Value for Lower Range.
Referenced by XAxiPmon_SelfTest.