xaxipmon_sinit.c
XAxiPmon_Config XAxiPmon_ConfigTable[][]
This table contains configuration information for each System Monitor/ADC device in the system.
XAxiPmon_Config * XAxiPmon_LookupConfig(UINTPTR BaseAddress)
Functions in xaxipmon_sinit.c.
Looks up the device configuration based on the unique device ID/BaseAddress.The XAxiPmon_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xaxipmon.h for the definition of XAxiPmon_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XAxiPmon_Config::Name.
Referenced by AxiPmonInterruptExample, AxiPmonPolledExample, main.