xaxipmon.h
XAPM_MAX_COUNTERS
Maximum number of Counters.
Referenced by XAxiPmon_GetIncrementer, XAxiPmon_GetIncrementerRange, XAxiPmon_GetLogEnableRanges, XAxiPmon_GetMetrics, XAxiPmon_GetSampledIncrementer, XAxiPmon_SetIncrementerRange, XAxiPmon_SetLogEnableRanges, XAxiPmon_SetMetrics.
XAPM_MAX_COUNTERS_PROFILE
Maximum number of Counters.
Referenced by XAxiPmon_GetMetricCounter, XAxiPmon_GetSampledMetricCounter.
XAPM_METRIC_COUNTER_0
Metric Counter 0 Register Index.
Referenced by ApmMetricConfig, AxiPmonInterruptExample, AxiPmonPolledExample, OcmTransaction.
XAPM_METRIC_COUNTER_1
Metric Counter 1 Register Index.
Referenced by ApmMetricConfig, OcmTransaction.
XAPM_METRIC_COUNTER_2
Metric Counter 2 Register Index.
XAPM_METRIC_COUNTER_3
Metric Counter 3 Register Index.
XAPM_METRIC_COUNTER_4
Metric Counter 4 Register Index.
XAPM_METRIC_COUNTER_5
Metric Counter 5 Register Index.
XAPM_METRIC_COUNTER_6
Metric Counter 6 Register Index.
XAPM_METRIC_COUNTER_7
Metric Counter 7 Register Index.
XAPM_METRIC_COUNTER_8
Metric Counter 8 Register Index.
XAPM_METRIC_COUNTER_9
Metric Counter 9 Register Index.
XAPM_INCREMENTER_0
Metric Counter 0 Register Index.
Referenced by AxiPmonInterruptExample, AxiPmonPolledExample, XAxiPmon_SelfTest.
XAPM_INCREMENTER_1
Metric Counter 0 Register Index.
XAPM_INCREMENTER_2
Metric Counter 0 Register Index.
XAPM_INCREMENTER_3
Metric Counter 0 Register Index.
XAPM_INCREMENTER_4
Metric Counter 0 Register Index.
XAPM_INCREMENTER_5
Metric Counter 0 Register Index.
XAPM_INCREMENTER_6
Metric Counter 0 Register Index.
XAPM_INCREMENTER_7
Metric Counter 0 Register Index.
XAPM_INCREMENTER_8
Metric Counter 0 Register Index.
XAPM_INCREMENTER_9
Metric Counter 0 Register Index.
XAPM_METRIC_SET_0
Write Transaction Count.
Referenced by AxiPmonInterruptExample, AxiPmonPolledExample, OcmTransaction, XAxiPmon_GetMetricName.
XAPM_METRIC_SET_1
Read Transaction Count.
Referenced by OcmTransaction, XAxiPmon_GetMetricName.
XAPM_METRIC_SET_2
Write Byte Count.
Referenced by OcmTransaction, XAxiPmon_GetMetricName.
XAPM_METRIC_SET_3
Read Byte Count.
Referenced by OcmTransaction, XAxiPmon_GetMetricName.
XAPM_METRIC_SET_4
Write Beat Count.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_5
Total Read Latency.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_6
Total Write Latency.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_7
Slv_Wr_Idle_Cnt.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_8
Mst_Rd_Idle_Cnt.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_9
Num_BValids.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_10
Num_WLasts.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_11
Num_RLasts.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_12
Minimum Write Latency.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_13
Maximum Write Latency.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_14
Minimum Read Latency.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_15
Maximum Read Latency.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_16
Transfer Cycle Count.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_17
Packet Count.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_18
Data Byte Count.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_19
Position Byte Count.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_20
Null Byte Count.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_21
Slv_Idle_Cnt.
Referenced by XAxiPmon_GetMetricName.
XAPM_METRIC_SET_22
Mst_Idle_Cnt.
Referenced by XAxiPmon_GetMetricName, XAxiPmon_SetMetrics.
XAPM_METRIC_SET_30
External event count.
Referenced by XAxiPmon_GetMetricName, XAxiPmon_SetMetrics.
XAPM_MAX_AGENTS
Maximum number of Agents.
Referenced by XAxiPmon_SetMetrics.
XAPM_FLAG_WRADDR
Write Address Flag.
XAPM_FLAG_FIRSTWR
First Write Flag.
XAPM_FLAG_LASTWR
Last Write Flag.
XAPM_FLAG_RESPONSE
Response Flag.
XAPM_FLAG_RDADDR
Read Address Flag.
XAPM_FLAG_FIRSTRD
First Read Flag.
XAPM_FLAG_LASTRD
Last Read Flag.
XAPM_FLAG_SWDATA
Software-written Data Flag.
XAPM_FLAG_EVENT
Last Read Flag.
XAPM_FLAG_EVNTSTOP
Last Read Flag.
XAPM_FLAG_EVNTSTART
Last Read Flag.
XAPM_FLAG_GCCOVF
Global Clock Counter Overflow Flag.
XAPM_FLAG_SCLAPSE
Sample Counter Lapse Flag.
XAPM_FLAG_MC0
Metric Counter 0 Flag.
XAPM_FLAG_MC1
Metric Counter 1 Flag.
XAPM_FLAG_MC2
Metric Counter 2 Flag.
XAPM_FLAG_MC3
Metric Counter 3 Flag.
XAPM_FLAG_MC4
Metric Counter 4 Flag.
XAPM_FLAG_MC5
Metric Counter 5 Flag.
XAPM_FLAG_MC6
Metric Counter 6 Flag.
XAPM_FLAG_MC7
Metric Counter 7 Flag.
XAPM_FLAG_MC8
Metric Counter 8 Flag.
XAPM_FLAG_MC9
Metric Counter 9 Flag.
XAPM_LATENCY_ADDR_ISSUE
Address Issue as start point for Latency calculation.
Referenced by XAxiPmon_GetRdLatencyStart, XAxiPmon_GetWrLatencyStart.
XAPM_LATENCY_ADDR_ACCEPT
Address Acceptance as start point for Latency calculation.
Referenced by XAxiPmon_GetRdLatencyStart, XAxiPmon_GetWrLatencyStart, XAxiPmon_SetRdLatencyStart, XAxiPmon_SetWrLatencyStart.
XAPM_LATENCY_LASTRD
Last Read as end point for Latency calculation.
Referenced by XAxiPmon_GetRdLatencyEnd.
XAPM_LATENCY_LASTWR
Last Write as end point for Latency calculation.
Referenced by XAxiPmon_GetWrLatencyEnd.
XAPM_LATENCY_FIRSTRD
First Read as end point for Latency calculation.
Referenced by XAxiPmon_GetRdLatencyEnd, XAxiPmon_SetRdLatencyEnd.
XAPM_LATENCY_FIRSTWR
First Write as end point for Latency calculation.
Referenced by XAxiPmon_GetWrLatencyEnd, XAxiPmon_SetWrLatencyEnd.
XAPM_MODE_TRACE
APM in Trace mode.
Referenced by XAxiPmon_CfgInitialize, XAxiPmon_DisableMetricCounterTrigger, XAxiPmon_EnableEventLog, XAxiPmon_EnableMetricCounterTrigger, XAxiPmon_GetMetricCounter, XAxiPmon_GetSampledMetricCounter, XAxiPmon_GetSampleInterval, XAxiPmon_ResetMetricCounter, XAxiPmon_SetSampleInterval, XAxiPmon_StartEventLog, XAxiPmon_StopEventLog.
XAPM_MODE_PROFILE
APM in Profile mode.
Referenced by XAxiPmon_CfgInitialize, XAxiPmon_DisableEventLogTrigger, XAxiPmon_DisableMetricsCounter, XAxiPmon_EnableEventLogTrigger, XAxiPmon_EnableMetricsCounter, XAxiPmon_GetSampledMetricCounter, XAxiPmon_ResetFifo, XAxiPmon_StartCounters, XAxiPmon_StopCounters.
XAPM_MODE_ADVANCED
APM in Advanced mode.
Referenced by XAxiPmon_CfgInitialize, XAxiPmon_DisableMetricsCounter, XAxiPmon_EnableEventLog, XAxiPmon_EnableMetricsCounter, XAxiPmon_GetGlobalClkCounter, XAxiPmon_GetIncrementer, XAxiPmon_GetIncrementerRange, XAxiPmon_GetLogEnableRanges, XAxiPmon_GetMetrics, XAxiPmon_GetSampledIncrementer, XAxiPmon_GetSampledMetricCounter, XAxiPmon_ResetFifo, XAxiPmon_ResetGlobalClkCounter, XAxiPmon_SetIncrementerRange, XAxiPmon_SetLogEnableRanges, XAxiPmon_SetMetrics, XAxiPmon_StartCounters, XAxiPmon_StartEventLog, XAxiPmon_StopCounters, XAxiPmon_StopEventLog.
XAXIPMON_H
XAxiPmon_IntrGlobalEnable
This routine enables the Global Interrupt.
InstancePtr is a pointer to the XAxiPmon instance. None. C-Style signature: void XAxiPmon_IntrGlobalEnable(XAxiPmon *InstancePtr)
Referenced by AxiPmonInterruptExample.
XAxiPmon_IntrGlobalDisable
This routine disables the Global Interrupt.
InstancePtr is a pointer to the XAxiPmon instance. None. C-Style signature: void XAxiPmon_IntrGlobalDisable(XAxiPmon *InstancePtr)
Referenced by AxiPmonInterruptExample.
XAxiPmon_IntrEnable
This routine enables interrupt(s).
Use the XAPM_IXR_* constants defined in xaxipmon_hw.h to create the bit-mask to enable interrupts. InstancePtr is a pointer to the XAxiPmon instance. Mask is the mask to enable. Bit positions of 1 will be enabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XAPM_IXR__* bits defined in xaxipmon_hw.h. None. C-Style signature: void XAxiPmon_IntrEnable(XAxiPmon *InstancePtr, u32 Mask)
Referenced by AxiPmonInterruptExample.
XAxiPmon_IntrDisable
This routine disable interrupt(s).
Use the XAPM_IXR_* constants defined in xaxipmon_hw.h to create the bit-mask to disable interrupts. InstancePtr is a pointer to the XAxiPmon instance. Mask is the mask to disable. Bit positions of 1 will be disabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XAPM_IXR_* bits defined in xaxipmon_hw.h. None. C-Style signature: void XAxiPmon_IntrEnable(XAxiPmon *InstancePtr, u32 Mask)
Referenced by AxiPmonInterruptExample.
XAxiPmon_IntrClear
This routine clears the specified interrupt(s).
InstancePtr is a pointer to the XAxiPmon instance. Mask is the mask to clear. Bit positions of 1 will be cleared. This mask is formed by OR'ing XAPM_IXR_* bits defined in xaxipmon_hw.h. None. C-Style signature: void XAxiPmon_IntrClear(XAxiPmon *InstancePtr, u32 Mask)
XAxiPmon_IntrGetStatus
This routine returns the Interrupt Status Register.
InstancePtr is a pointer to the XAxiPmon instance. Interrupt Status Register contents C-Style signature: void XAxiPmon_IntrClear(XAxiPmon *InstancePtr)
XAxiPmon_EnableGlobalClkCounter
This function enables the Global Clock Counter.
InstancePtr is a pointer to the XAxiPmon instance. None C-Style signature: void XAxiPmon_EnableGlobalClkCounter(XAxiPmon *InstancePtr)
Referenced by AxiPmonPolledExample.
XAxiPmon_DisableGlobalClkCounter
This function disbles the Global Clock Counter.
InstancePtr is a pointer to the XAxiPmon instance. None C-Style signature: void XAxiPmon_DisableGlobalClkCounter(XAxiPmon *InstancePtr)
Referenced by AxiPmonPolledExample.
XAxiPmon_EnableFlag
This function enables the specified flag in Flag Control Register.
InstancePtr is a pointer to the XAxiPmon instance. Flag is one of the XAPM_FLAG_* masks defined in xaxipmon.h None C-Style signature: void XAxiPmon_EnableFlag(XAxiPmon *InstancePtr)
XAxiPmon_DisableFlag
This function disables the specified flag in Flag Control Register.
InstancePtr is a pointer to the XAxiPmon instance. Flag is one of the XAPM_FLAG_* masks defined in xaxipmon.h* None C-Style signature: void XAxiPmon_DisableFlag(XAxiPmon *InstancePtr)
XAxiPmon_LoadSampleIntervalCounter
This function loads the sample interval register value into the sample interval counter.
InstancePtr is a pointer to the XAxiPmon instance. None C-Style signature: void XAxiPmon_LoadSampleIntervalCounter(XAxiPmon *InstancePtr)
Referenced by AxiPmonInterruptExample, XAxiPmon_StartCounters.
XAxiPmon_EnableSampleIntervalCounter
This enables the down count of the sample interval counter.
InstancePtr is a pointer to the XAxiPmon instance. None C-Style signature: void XAxiPmon_EnableSampleIntervalCounter(XAxiPmon *InstancePtr)
Referenced by AxiPmonInterruptExample, XAxiPmon_StartCounters.
XAxiPmon_DisableSampleIntervalCounter
This disables the down count of the sample interval counter.
InstancePtr is a pointer to the XAxiPmon instance. None C-Style signature: void XAxiPmon_DisableSampleIntervalCounter(XAxiPmon *InstancePtr)
Referenced by AxiPmonInterruptExample.
XAxiPmon_EnableMetricCounterReset
This enables Reset of Metric Counters when Sample Interval Counter lapses.
InstancePtr is a pointer to the XAxiPmon instance. None C-Style signature: void XAxiPmon_EnableMetricCounterReset(XAxiPmon *InstancePtr)
XAxiPmon_DisableMetricCounterReset
This disables the down count of the sample interval counter.
InstancePtr is a pointer to the XAxiPmon instance. None C-Style signature: void XAxiPmon_DisableMetricCounterReset(XAxiPmon *InstancePtr)
XAxiPmon_EnableIDFilter
This function enables the ID Filter Masking.
InstancePtr is a pointer to the XAxiPmon instance. None C-Style signature: void XAxiPmon_EnableIDFilter(XAxiPmon *InstancePtr)
XAxiPmon_DisableIDFilter
This function disbles the ID Filter masking.
InstancePtr is a pointer to the XAxiPmon instance. None C-Style signature: void XAxiPmon_DisableIDFilter(XAxiPmon *InstancePtr)
XAxiPmon_SampleMetrics
This function samples Metric Counters to Sampled Metric Counters by reading Sample Register and also returns interval.
i.e. the number of clocks in between previous read to the current read of sample register. InstancePtr is a pointer to the XAxiPmon instance. Interval. i.e. the number of clocks in between previous read to the current read of sample register. C-Style signature: u32 XAxiPmon_SampleMetrics(XAxiPmon *InstancePtr)
XAxiPmon_Config * XAxiPmon_LookupConfig(UINTPTR BaseAddress)
Functions in xaxipmon_sinit.c.
Looks up the device configuration based on the unique device ID/BaseAddress.The XAxiPmon_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xaxipmon.h for the definition of XAxiPmon_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XAxiPmon_Config::Name.
Referenced by AxiPmonInterruptExample, AxiPmonPolledExample, main.
s32 XAxiPmon_CfgInitialize(XAxiPmon *InstancePtr, XAxiPmon_Config *ConfigPtr, UINTPTR EffectiveAddr)
This function initializes a specific XAxiPmon device/instance.
Functions in xaxipmon.c.This function must be called prior to using the AXI Performance Monitor device. InstancePtr is a pointer to the XAxiPmon instance. ConfigPtr points to the XAxiPmon device configuration structure. EffectiveAddr is the device base address in the virtual memory address space. If the address translation is not used then the physical address is passed. Unexpected errors may occur if the address mapping is changed after this function is invoked. XST_SUCCESS if successful. The user needs to first call the XAxiPmon_LookupConfig() API which returns the Configuration structure pointer which is passed as a parameter to the XAxiPmon_CfgInitialize() API.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::FifoDepth, XAxiPmon_Config::FifoWidth, XAxiPmon_Config::GlobalClkCounterWidth, XAxiPmon_Config::HaveSampledCounters, XAxiPmon_Config::IntId, XAxiPmon_Config::IntrParent, XAxiPmon_Config::Is32BitFiltering, XAxiPmon_Config::IsEventCount, XAxiPmon_Config::IsEventLog, XAxiPmon::IsReady, XAxiPmon_Config::MetricSampleCounterWidth, XAxiPmon::Mode, XAxiPmon_Config::ModeAdvanced, XAxiPmon_Config::ModeProfile, XAxiPmon_Config::ModeTrace, XAxiPmon_Config::NumberofCounters, XAxiPmon_Config::NumberofSlots, XAxiPmon_Config::ScaleFactor, XAxiPmon_Config::TidWidth, XAPM_MODE_ADVANCED, XAPM_MODE_PROFILE, XAPM_MODE_TRACE, XAxiPmon_ResetFifo, XAxiPmon_ResetGlobalClkCounter, XAxiPmon_ResetMetricCounter.
Referenced by AxiPmonInterruptExample, AxiPmonPolledExample, main.
s32 XAxiPmon_ResetMetricCounter(XAxiPmon *InstancePtr)
This function resets all Metric Counters and Sampled Metric Counters of AXI Performance Monitor.
InstancePtr is a pointer to the XAxiPmon instance. XST_SUCCESS None.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_CR_MCNTR_RESET_MASK, XAPM_CTL_OFFSET, XAPM_MODE_TRACE, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
Referenced by ApmMetricConfig, XAxiPmon_CfgInitialize, XAxiPmon_SelfTest.
void XAxiPmon_ResetGlobalClkCounter(XAxiPmon *InstancePtr)
This function resets Global Clock Counter of AXI Performance Monitor.
InstancePtr is a pointer to the XAxiPmon instance. None. None.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_CR_GCC_RESET_MASK, XAPM_CTL_OFFSET, XAPM_MODE_ADVANCED, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
Referenced by ApmMetricConfig, XAxiPmon_CfgInitialize, XAxiPmon_SelfTest.
s32 XAxiPmon_ResetFifo(XAxiPmon *InstancePtr)
This function resets Streaming FIFO of AXI Performance Monitor.
InstancePtr is a pointer to the XAxiPmon instance. XST_SUCCESS None.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::IsEventLog, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_CR_FIFO_RESET_MASK, XAPM_CTL_OFFSET, XAPM_MODE_ADVANCED, XAPM_MODE_PROFILE, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
Referenced by XAxiPmon_CfgInitialize.
void XAxiPmon_SetIncrementerRange(XAxiPmon *InstancePtr, u8 IncrementerNum, u16 RangeUpper, u16 RangeLower)
This function sets Ranges for Incrementers depending on parameters passed.
InstancePtr is a pointer to the XAxiPmon instance. IncrementerNum specifies the Incrementer for which Ranges need to be set RangeUpper specifies the Upper limit in 32 bit Register RangeLower specifies the Lower limit in 32 bit Register None. None
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_MAX_COUNTERS, XAPM_MODE_ADVANCED, XAPM_RANGE0_OFFSET, XAxiPmon_WriteReg.
Referenced by AxiPmonInterruptExample, AxiPmonPolledExample, XAxiPmon_SelfTest.
void XAxiPmon_GetIncrementerRange(XAxiPmon *InstancePtr, u8 IncrementerNum, u16 *RangeUpper, u16 *RangeLower)
This function returns the Ranges of Incrementers Registers.
InstancePtr is a pointer to the XAxiPmon instance. IncrementerNum specifies the Incrementer for which Ranges need to be returned. RangeUpper specifies the user reference variable which returns the Upper Range Value of the specified Incrementer. RangeLower specifies the user reference variable which returns the Lower Range Value of the specified Incrementer. None. None
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_MAX_COUNTERS, XAPM_MODE_ADVANCED, XAPM_RANGE0_OFFSET, XAxiPmon_ReadReg.
Referenced by XAxiPmon_SelfTest.
void XAxiPmon_SetSampleInterval(XAxiPmon *InstancePtr, u32 SampleInterval)
This function sets the Sample Interval Register.
InstancePtr is a pointer to the XAxiPmon instance. SampleInterval is the Sample Interval value to be set None None.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_MODE_TRACE, XAPM_SI_LOW_OFFSET, XAxiPmon_WriteReg.
Referenced by AxiPmonInterruptExample, XAxiPmon_StartCounters.
void XAxiPmon_GetSampleInterval(XAxiPmon *InstancePtr, u32 *SampleInterval)
This function returns the contents of Sample Interval Register.
InstancePtr is a pointer to the XAxiPmon instance. SampleInterval is a pointer where the Sample Interval Counter value is returned. None. None.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_MODE_TRACE, XAPM_SI_LOW_OFFSET, XAxiPmon_ReadReg.
s32 XAxiPmon_SetMetrics(XAxiPmon *InstancePtr, u8 Slot, u8 Metrics, u8 CounterNum)
This function sets Metrics for specified Counter in the corresponding Metric Selector Register.
InstancePtr is a pointer to the XAxiPmon instance. Slot is the slot ID for which specified counter has to be connected. Metrics is one of the Metric Sets. User has to use XAPM_METRIC_SET_* macros in xaxipmon.h for this parameter CounterNum is the Counter Number. The valid values are 0 to 9. XST_SUCCESS if Success XST_FAILURE if Failure None.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_MAX_AGENTS, XAPM_MAX_COUNTERS, XAPM_METRIC_SET_22, XAPM_METRIC_SET_30, XAPM_MODE_ADVANCED, XAPM_MSR0_OFFSET, XAPM_MSR1_OFFSET, XAPM_MSR2_OFFSET, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
Referenced by ApmMetricConfig, AxiPmonInterruptExample, AxiPmonPolledExample.
s32 XAxiPmon_GetMetrics(XAxiPmon *InstancePtr, u8 CounterNum, u8 *Metrics, u8 *Slot)
This function returns Metrics in the specified Counter from the corresponding Metric Selector Register.
InstancePtr is a pointer to the XAxiPmon instance. CounterNum is the Counter Number. The valid values are 0 to 9. Metrics is a reference parameter from application where metrics of specified counter is filled. Slot is a reference parameter in which slot Id of specified counter is filled XST_SUCCESS if Success XST_FAILURE if Failure None.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_MAX_COUNTERS, XAPM_MODE_ADVANCED, XAPM_MSR0_OFFSET, XAPM_MSR1_OFFSET, XAPM_MSR2_OFFSET, XAxiPmon_ReadReg.
void XAxiPmon_GetGlobalClkCounter(XAxiPmon *InstancePtr, u32 *CntHighValue, u32 *CntLowValue)
This function returns the contents of the Global Clock Counter Register.
InstancePtr is a pointer to the XAxiPmon instance. CntHighValue is the user space pointer with which upper 32 bits of Global Clock Counter has to be filled CntLowValue is the user space pointer with which lower 32 bits of Global Clock Counter has to be filled None. None.
References XAxiPmon::Config, XAxiPmon_Config::GlobalClkCounterWidth, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_GCC_HIGH_OFFSET, XAPM_GCC_LOW_OFFSET, XAPM_MODE_ADVANCED, XAxiPmon_ReadReg.
Referenced by AxiPmonPolledExample.
u32 XAxiPmon_GetMetricCounter(XAxiPmon *InstancePtr, u32 CounterNum)
This function returns the contents of the Metric Counter Register.
InstancePtr is a pointer to the XAxiPmon instance. CounterNum is the number of the Metric Counter to be read. Use the XAPM_METRIC_COUNTER* defines for the counter number in xaxipmon.h. The valid values are 0 (XAPM_METRIC_COUNTER_0) to 47(XAPM_METRIC_COUNTER_47). RegValue is the content of specified Metric Counter. None.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_MAX_COUNTERS_PROFILE, XAPM_MC0_OFFSET, XAPM_MC10_OFFSET, XAPM_MC12_OFFSET, XAPM_MC24_OFFSET, XAPM_MC36_OFFSET, XAPM_MODE_TRACE, XAxiPmon_ReadReg.
Referenced by AxiPmonPolledExample, ReadMetrics.
u32 XAxiPmon_GetSampledMetricCounter(XAxiPmon *InstancePtr, u32 CounterNum)
This function returns the contents of the Sampled Metric Counter Register.
InstancePtr is a pointer to the XAxiPmon instance. CounterNum is the number of the Sampled Metric Counter to read. Use the XAPM_METRIC_COUNTER* defines for the counter number in xaxipmon.h. The valid values are 0 (XAPM_METRIC_COUNTER_0) to 47(XAPM_METRIC_COUNTER_47). RegValue is the content of specified Sampled Metric Counter. None.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::HaveSampledCounters, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_MAX_COUNTERS_PROFILE, XAPM_MODE_ADVANCED, XAPM_MODE_PROFILE, XAPM_MODE_TRACE, XAPM_SMC0_OFFSET, XAPM_SMC10_OFFSET, XAPM_SMC12_OFFSET, XAPM_SMC24_OFFSET, XAPM_SMC36_OFFSET, XAxiPmon_ReadReg.
Referenced by AxiPmonInterruptExample.
u32 XAxiPmon_GetIncrementer(XAxiPmon *InstancePtr, u32 IncrementerNum)
This function returns the contents of the Incrementer Register.
InstancePtr is a pointer to the XAxiPmon instance. IncrementerNum is the number of the Incrementer register to read.Use the XAPM_INCREMENTER_* defines for the Incrementer number.The valid values are 0 (XAPM_INCREMENTER_0) to 9 (XAPM_INCREMENTER_9). IncrementerNum is the number of the specified Incrementer register RegValue is content of specified Metric Incrementer register. None.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::IsEventCount, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_INC0_OFFSET, XAPM_MAX_COUNTERS, XAPM_MODE_ADVANCED, XAxiPmon_ReadReg.
u32 XAxiPmon_GetSampledIncrementer(XAxiPmon *InstancePtr, u32 IncrementerNum)
This function returns the contents of the Sampled Incrementer Register.
InstancePtr is a pointer to the XAxiPmon instance. IncrementerNum is the number of the Sampled Incrementer register to read.Use the XAPM_INCREMENTER_* defines for the Incrementer number.The valid values are 0 (XAPM_INCREMENTER_0) to 9 (XAPM_INCREMENTER_9). IncrementerNum is the number of the specified Sampled Incrementer register RegValue is content of specified Sampled Incrementer register. None.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::HaveSampledCounters, XAxiPmon_Config::IsEventCount, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_MAX_COUNTERS, XAPM_MODE_ADVANCED, XAPM_SINC0_OFFSET, XAxiPmon_ReadReg.
void XAxiPmon_SetSwDataReg(XAxiPmon *InstancePtr, u32 SwData)
This function sets Software-written Data Register.
InstancePtr is a pointer to the XAxiPmon instance. SwData is the Software written Data. None. None.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAPM_SWD_OFFSET, XAxiPmon_WriteReg.
u32 XAxiPmon_GetSwDataReg(XAxiPmon *InstancePtr)
This function returns contents of Software-written Data Register.
InstancePtr is a pointer to the XAxiPmon instance. SwData. None.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAPM_SWD_OFFSET, XAxiPmon_ReadReg.
s32 XAxiPmon_StartEventLog(XAxiPmon *InstancePtr, u32 FlagEnables)
This function enables the following in the AXI Performance Monitor:
Event logging InstancePtr is a pointer to the XAxiPmon instance. FlagEnables is a value to write to the flag enables register defined by XAPM_FEC_OFFSET. It is recommended to use the XAPM_FEC_*_MASK mask bits to generate. A value of 0x0 will disable all events to the event log streaming FIFO. XST_SUCCESS None
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::IsEventLog, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_CR_EVENTLOG_ENABLE_MASK, XAPM_CTL_OFFSET, XAPM_FEC_OFFSET, XAPM_MODE_ADVANCED, XAPM_MODE_TRACE, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
s32 XAxiPmon_StopEventLog(XAxiPmon *InstancePtr)
This function disables the following in the AXI Performance Monitor:
Event logging InstancePtr is a pointer to the XAxiPmon instance. XST_SUCCESS None
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::IsEventLog, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_CR_EVENTLOG_ENABLE_MASK, XAPM_CTL_OFFSET, XAPM_MODE_ADVANCED, XAPM_MODE_TRACE, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
s32 XAxiPmon_StartCounters(XAxiPmon *InstancePtr, u32 SampleInterval)
This function enables the following in the AXI Performance Monitor:
Global clock counterAll metric countersAll sampled metric counters InstancePtr is a pointer to the XAxiPmon instance. SampleInterval is the sample interval for the sampled metric counters XST_SUCCESS None
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::IsEventCount, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_CR_GCC_ENABLE_MASK, XAPM_CR_MCNTR_ENABLE_MASK, XAPM_CTL_OFFSET, XAPM_MODE_ADVANCED, XAPM_MODE_PROFILE, XAxiPmon_EnableSampleIntervalCounter, XAxiPmon_LoadSampleIntervalCounter, XAxiPmon_ReadReg, XAxiPmon_SetSampleInterval, XAxiPmon_WriteReg.
Referenced by ApmMetricConfig.
s32 XAxiPmon_StopCounters(XAxiPmon *InstancePtr)
This function disables the following in the AXI Performance Monitor:
Global clock counterAll metric counters InstancePtr is a pointer to the XAxiPmon instance. XST_SUCCESS None
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::IsEventCount, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_CR_GCC_ENABLE_MASK, XAPM_CR_MCNTR_ENABLE_MASK, XAPM_CTL_OFFSET, XAPM_MODE_ADVANCED, XAPM_MODE_PROFILE, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
Referenced by ReadMetrics.
void XAxiPmon_EnableMetricsCounter(XAxiPmon *InstancePtr)
This function enables Metric Counters.
InstancePtr is a pointer to the XAxiPmon instance. None None
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::IsEventCount, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_CR_MCNTR_ENABLE_MASK, XAPM_CTL_OFFSET, XAPM_MODE_ADVANCED, XAPM_MODE_PROFILE, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
Referenced by ApmMetricConfig, AxiPmonInterruptExample, AxiPmonPolledExample.
void XAxiPmon_DisableMetricsCounter(XAxiPmon *InstancePtr)
This function disables the Metric Counters.
InstancePtr is a pointer to the XAxiPmon instance. None None
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::IsEventCount, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_CR_MCNTR_ENABLE_MASK, XAPM_CTL_OFFSET, XAPM_MODE_ADVANCED, XAPM_MODE_PROFILE, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
Referenced by AxiPmonInterruptExample, AxiPmonPolledExample, main.
void XAxiPmon_SetLogEnableRanges(XAxiPmon *InstancePtr, u32 CounterNum, u16 RangeUpper, u16 RangeLower)
This function sets the Upper and Lower Ranges for specified Metric Counter Log Enable Register.Event Logging starts when corresponding Metric Counter value falls in between these ranges.
InstancePtr is a pointer to the XAxiPmon instance. CounterNum is the Metric Counter number for which Ranges are to be assigned.Use the XAPM_METRIC_COUNTER* defines for the counter number in xaxipmon.h. The valid values are 0 (XAPM_METRIC_COUNTER_0) to 9 (XAPM_METRIC_COUNTER_9). RangeUpper specifies the Upper limit in 32 bit Register RangeLower specifies the Lower limit in 32 bit Register None None.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::IsEventCount, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_MAX_COUNTERS, XAPM_MC0LOGEN_OFFSET, XAPM_MODE_ADVANCED, XAxiPmon_WriteReg.
void XAxiPmon_GetLogEnableRanges(XAxiPmon *InstancePtr, u32 CounterNum, u16 *RangeUpper, u16 *RangeLower)
This function returns the Ranges of specified Metric Counter Log Enable Register.
InstancePtr is a pointer to the XAxiPmon instance. CounterNum is the Metric Counter number for which Ranges are to be returned.Use the XAPM_METRIC_COUNTER* defines for the counter number in xaxipmon.h. The valid values are 0 (XAPM_METRIC_COUNTER_0) to 9 (XAPM_METRIC_COUNTER_9). RangeUpper specifies the user reference variable which returns the Upper Range Value of the specified Metric Counter Log Enable Register. RangeLower specifies the user reference variable which returns the Lower Range Value of the specified Metric Counter Log Enable Register. None.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::IsEventCount, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_MAX_COUNTERS, XAPM_MC0LOGEN_OFFSET, XAPM_MODE_ADVANCED, XAxiPmon_ReadReg.
void XAxiPmon_EnableEventLog(XAxiPmon *InstancePtr)
This function enables Event Logging.
InstancePtr is a pointer to the XAxiPmon instance. None None
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::IsEventLog, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_CR_EVENTLOG_ENABLE_MASK, XAPM_CTL_OFFSET, XAPM_MODE_ADVANCED, XAPM_MODE_TRACE, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
void XAxiPmon_EnableMetricCounterTrigger(XAxiPmon *InstancePtr)
This function enables External trigger pulse so that Metric Counters can be started on external trigger pulse for a Slot.
InstancePtr is a pointer to the XAxiPmon instance. None None
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_CR_MCNTR_EXTTRIGGER_MASK, XAPM_CTL_OFFSET, XAPM_MODE_TRACE, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
void XAxiPmon_DisableMetricCounterTrigger(XAxiPmon *InstancePtr)
This function disables the External trigger pulse used to start Metric Counters on external trigger pulse for a Slot.
InstancePtr is a pointer to the XAxiPmon instance. None None
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_CR_MCNTR_EXTTRIGGER_MASK, XAPM_CTL_OFFSET, XAPM_MODE_TRACE, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
void XAxiPmon_EnableEventLogTrigger(XAxiPmon *InstancePtr)
This function enables External trigger pulse for Event Log so that Event Logging can be started on external trigger pulse for a Slot.
InstancePtr is a pointer to the XAxiPmon instance. None None
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_CR_EVTLOG_EXTTRIGGER_MASK, XAPM_CTL_OFFSET, XAPM_MODE_PROFILE, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
void XAxiPmon_DisableEventLogTrigger(XAxiPmon *InstancePtr)
This function disables the External trigger pulse used to start Event Log on external trigger pulse for a Slot.
InstancePtr is a pointer to the XAxiPmon instance. None None
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAxiPmon::Mode, XAPM_CR_EVTLOG_EXTTRIGGER_MASK, XAPM_CTL_OFFSET, XAPM_MODE_PROFILE, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
const char * XAxiPmon_GetMetricName(u8 Metrics)
This function returns a name for a given Metric.
Metrics is one of the Metric Sets. User has to use XAPM_METRIC_SET_* macros in xaxipmon.h for this parameter const char * None
References XAPM_METRIC_SET_0, XAPM_METRIC_SET_1, XAPM_METRIC_SET_10, XAPM_METRIC_SET_11, XAPM_METRIC_SET_12, XAPM_METRIC_SET_13, XAPM_METRIC_SET_14, XAPM_METRIC_SET_15, XAPM_METRIC_SET_16, XAPM_METRIC_SET_17, XAPM_METRIC_SET_18, XAPM_METRIC_SET_19, XAPM_METRIC_SET_2, XAPM_METRIC_SET_20, XAPM_METRIC_SET_21, XAPM_METRIC_SET_22, XAPM_METRIC_SET_3, XAPM_METRIC_SET_30, XAPM_METRIC_SET_4, XAPM_METRIC_SET_5, XAPM_METRIC_SET_6, XAPM_METRIC_SET_7, XAPM_METRIC_SET_8, XAPM_METRIC_SET_9.
void XAxiPmon_SetWriteId(XAxiPmon *InstancePtr, u32 WriteId)
This function sets Write ID in ID register.
InstancePtr is a pointer to the XAxiPmon instance. WriteId is the Write ID to be written in ID register. None. If ID filtering for write is of 32 bits(for Zynq MP APM) width then WriteID is written to XAPM_ID_OFFSET or if it is 16 bit width then lower 16 bits of WriteID are written to XAPM_ID_OFFSET.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::Is32BitFiltering, XAxiPmon::IsReady, XAPM_ID_OFFSET, XAPM_ID_WID_MASK, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
void XAxiPmon_SetReadId(XAxiPmon *InstancePtr, u32 ReadId)
This function sets Read ID in ID register.
InstancePtr is a pointer to the XAxiPmon instance. ReadId is the Read ID to be written in ID register. None. If ID filtering for read is of 32 bits(for Zynq MP APM) width then ReadId is written to XAPM_RID_OFFSET or if it is 16 bit width then lower 16 bits of ReadId are written to XAPM_ID_OFFSET.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::Is32BitFiltering, XAxiPmon::IsReady, XAPM_ID_OFFSET, XAPM_ID_RID_MASK, XAPM_RID_OFFSET, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
u32 XAxiPmon_GetWriteId(XAxiPmon *InstancePtr)
This function returns Write ID in ID register.
InstancePtr is a pointer to the XAxiPmon instance. WriteId is the required Write ID in ID register. None. If ID filtering for write is of 32 bits(for Zynq MP APM) width then 32 bit XAPM_ID_OFFSET contents are returned or if it is 16 bit width then lower 16 bits of XAPM_ID_OFFSET register are returned.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::Is32BitFiltering, XAxiPmon::IsReady, XAPM_ID_OFFSET, XAPM_ID_WID_MASK, XAxiPmon_ReadReg.
u32 XAxiPmon_GetReadId(XAxiPmon *InstancePtr)
This function returns Read ID in ID register.
InstancePtr is a pointer to the XAxiPmon instance. ReadId is the required Read ID in ID register. None. If ID filtering for write is of 32 bits(for Zynq MP APM) width then 32 bit XAPM_RID_OFFSET contents are returned or if it is 16 bit width then higher 16 bits of XAPM_ID_OFFSET register are returned.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::Is32BitFiltering, XAxiPmon::IsReady, XAPM_ID_OFFSET, XAPM_ID_RID_MASK, XAPM_RID_OFFSET, XAxiPmon_ReadReg.
void XAxiPmon_SetWrLatencyStart(XAxiPmon *InstancePtr, u8 Param)
This function sets Latency Start point to calculate write latency.
InstancePtr is a pointer to the XAxiPmon instance. Param is XAPM_LATENCY_ADDR_ISSUE or XAPM_LATENCY_ADDR_ACCEPT in xaxipmon.h. None Param can be 0 - XAPM_LATENCY_ADDR_ISSUE or 1 - XAPM_LATENCY_ADDR_ACCEPT
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAPM_CR_WRLATENCY_START_MASK, XAPM_CTL_OFFSET, XAPM_LATENCY_ADDR_ACCEPT, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
void XAxiPmon_SetWrLatencyEnd(XAxiPmon *InstancePtr, u8 Param)
This function sets Latency End point to calculate write latency.
InstancePtr is a pointer to the XAxiPmon instance. Param is XAPM_LATENCY_LASTWR or XAPM_LATENCY_FIRSTWR in xaxipmon.h. None Param can be 0 - XAPM_LATENCY_LASTWR or 1 - XAPM_LATENCY_FIRSTWR
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAPM_CR_WRLATENCY_END_MASK, XAPM_CTL_OFFSET, XAPM_LATENCY_FIRSTWR, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
void XAxiPmon_SetRdLatencyStart(XAxiPmon *InstancePtr, u8 Param)
This function sets Latency Start point to calculate read latency.
InstancePtr is a pointer to the XAxiPmon instance. Param is XAPM_LATENCY_ADDR_ISSUE or XAPM_LATENCY_ADDR_ACCEPT in xaxipmon.h. None Param can be 0 - XAPM_LATENCY_ADDR_ISSUE or 1 - XAPM_LATENCY_ADDR_ACCEPT
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAPM_CR_RDLATENCY_START_MASK, XAPM_CTL_OFFSET, XAPM_LATENCY_ADDR_ACCEPT, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
void XAxiPmon_SetRdLatencyEnd(XAxiPmon *InstancePtr, u8 Param)
This function sets Latency End point to calculate read latency.
InstancePtr is a pointer to the XAxiPmon instance. Param is XAPM_LATENCY_LASTRD or XAPM_LATENCY_FIRSTRD in xaxipmon.h. None Param can be 0 - XAPM_LATENCY_LASTRD or 1 - XAPM_LATENCY_FIRSTRD
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAPM_CR_RDLATENCY_END_MASK, XAPM_CTL_OFFSET, XAPM_LATENCY_FIRSTRD, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
u8 XAxiPmon_GetWrLatencyStart(XAxiPmon *InstancePtr)
This function returns Write Latency Start point.
InstancePtr is a pointer to the XAxiPmon instance. Returns 0 - XAPM_LATENCY_ADDR_ISSUE or 1 - XAPM_LATENCY_ADDR_ACCEPT None
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAPM_CR_WRLATENCY_START_MASK, XAPM_CTL_OFFSET, XAPM_LATENCY_ADDR_ACCEPT, XAPM_LATENCY_ADDR_ISSUE, XAxiPmon_ReadReg.
u8 XAxiPmon_GetWrLatencyEnd(XAxiPmon *InstancePtr)
This function returns Write Latency End point.
InstancePtr is a pointer to the XAxiPmon instance. Returns 0 - XAPM_LATENCY_LASTWR or 1 - XAPM_LATENCY_FIRSTWR. None
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAPM_CR_WRLATENCY_END_MASK, XAPM_CTL_OFFSET, XAPM_LATENCY_FIRSTWR, XAPM_LATENCY_LASTWR, XAxiPmon_ReadReg.
u8 XAxiPmon_GetRdLatencyStart(XAxiPmon *InstancePtr)
This function returns read Latency Start point.
InstancePtr is a pointer to the XAxiPmon instance. Returns 0 - XAPM_LATENCY_ADDR_ISSUE or 1 - XAPM_LATENCY_ADDR_ACCEPT None
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAPM_CR_RDLATENCY_START_MASK, XAPM_CTL_OFFSET, XAPM_LATENCY_ADDR_ACCEPT, XAPM_LATENCY_ADDR_ISSUE, XAxiPmon_ReadReg.
u8 XAxiPmon_GetRdLatencyEnd(XAxiPmon *InstancePtr)
This function returns Read Latency End point.
InstancePtr is a pointer to the XAxiPmon instance. Returns 0 - XAPM_LATENCY_LASTRD or 1 - XAPM_LATENCY_FIRSTRD. None
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon::IsReady, XAPM_CR_RDLATENCY_END_MASK, XAPM_CTL_OFFSET, XAPM_LATENCY_FIRSTRD, XAPM_LATENCY_LASTRD, XAxiPmon_ReadReg.
void XAxiPmon_SetWriteIdMask(XAxiPmon *InstancePtr, u32 WrMask)
This function sets Write ID Mask in ID Mask register.
InstancePtr is a pointer to the XAxiPmon instance. WrMask is the Write ID mask to be written in ID register. None. If ID masking for write is of 32 bits(for Zynq MP APM) width then WrMask is written to XAPM_IDMASK_OFFSET or if it is 16 bit width then lower 16 bits of WrMask are written to XAPM_IDMASK_OFFSET.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::Is32BitFiltering, XAxiPmon::IsReady, XAPM_IDMASK_OFFSET, XAPM_MASKID_WID_MASK, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
void XAxiPmon_SetReadIdMask(XAxiPmon *InstancePtr, u32 RdMask)
This function sets Read ID Mask in ID Mask register.
InstancePtr is a pointer to the XAxiPmon instance. RdMask is the Read ID mask to be written in ID Mask register. None. If ID masking for read is of 32 bits(for Zynq MP APM) width then RdMask is written to XAPM_RIDMASK_OFFSET or if it is 16 bit width then lower 16 bits of RdMask are written to XAPM_IDMASK_OFFSET.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::Is32BitFiltering, XAxiPmon::IsReady, XAPM_IDMASK_OFFSET, XAPM_MASKID_RID_MASK, XAPM_RIDMASK_OFFSET, XAxiPmon_ReadReg, XAxiPmon_WriteReg.
u32 XAxiPmon_GetWriteIdMask(XAxiPmon *InstancePtr)
This function returns Write ID Mask in ID Mask register.
InstancePtr is a pointer to the XAxiPmon instance. WrMask is the required Write ID Mask in ID Mask register. If ID masking for write is of 32 bits(for Zynq MP APM) width then 32 bit XAPM_IDMASK_OFFSET contents are returned or if it is 16 bit width then lower 16 bits of XAPM_IDMASK_OFFSET register are returned.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::Is32BitFiltering, XAxiPmon::IsReady, XAPM_IDMASK_OFFSET, XAPM_MASKID_WID_MASK, XAxiPmon_ReadReg.
u32 XAxiPmon_GetReadIdMask(XAxiPmon *InstancePtr)
This function returns Read ID Mask in ID Mask register.
InstancePtr is a pointer to the XAxiPmon instance. RdMask is the required Read ID Mask in ID Mask register. If ID masking for read is of 32 bits(for Zynq MP APM) width then 32 bit XAPM_RIDMASK_OFFSET contents are returned or if it is 16 bit width then higher 16 bits of XAPM_IDMASK_OFFSET register are returned.
References XAxiPmon_Config::BaseAddress, XAxiPmon::Config, XAxiPmon_Config::Is32BitFiltering, XAxiPmon::IsReady, XAPM_IDMASK_OFFSET, XAPM_MASKID_RID_MASK, XAPM_RIDMASK_OFFSET, XAxiPmon_ReadReg.
s32 XAxiPmon_SelfTest(XAxiPmon *InstancePtr)
Functions in xaxipmon_selftest.c.
Run a self-test on the driver/device.The test Resets the device,Writes a value into the Range Registers of Incrementer 0 and reads it back for comparison.Resets the device again. InstancePtr is a pointer to the XAxiPmon instance. XST_SUCCESS if the value read from the Range Register of Incrementer 0 is the same as the value written.XST_FAILURE Otherwise This is a destructive test in that resets of the device are performed. Refer to the device specification for the device status after the reset operation.
References XAxiPmon::IsReady, XAPM_INCREMENTER_0, XAPM_TEST_RANGELOWER_VALUE, XAPM_TEST_RANGEUPPER_VALUE, XAxiPmon_GetIncrementerRange, XAxiPmon_ResetGlobalClkCounter, XAxiPmon_ResetMetricCounter, XAxiPmon_SetIncrementerRange.
Referenced by AxiPmonInterruptExample, AxiPmonPolledExample.