xaxipmon_ocm_example.c
SAMPLE_INTERVAL
OCM_WRITE_ADDRESS
OCM_READ_ADDRESS
XAxiPmon AxiPmonInst
u32 MetricsBuffer[6][6]
int ApmCheck(u32 *BufferPtr, u16 Wtx, u16 Wbc, u16 Rtx, u16 Rbc)
Checks the metrics passed to this function are same as collected by APM.
BufferPtr is pointer to buffer containing captured metrics. Wtx is Write transaction count value to be checked. Wbc is Write byte count value to be checked. Rtx is Read transaction count value to be checked. Rbc is Read byte count value to be checked. XST_SUCCESS if metrics passed are equal to metrics collected by APM.XST_FAILURE if any of the metrics passed is not equal to metrics collected by APM. None.
Referenced by main.
void OcmTransaction()
Generates write and read transcations to OCM and reads metrics captured by APM.
None. None. None.
References ApmMetricConfig, ReadMetrics, XAPM_METRIC_COUNTER_0, XAPM_METRIC_COUNTER_1, XAPM_METRIC_SET_0, XAPM_METRIC_SET_1, XAPM_METRIC_SET_2, XAPM_METRIC_SET_3.
Referenced by main.
int ApmMetricConfig(XAxiPmon *InstancePtr, u8 slot, u8 Metric1, u8 Metric2)
Sets Counter 0 and Counter 1 for collecting the passed metrics.
InstancePtr is pointer to APM instance. Slot is APM slot. Metric1 is Metric to be captured by Counter 1 Metric2 is Metric to be captured by Counter 2 XST_SUCCESS on success.XST_FAILURE on failure. None.
References XAPM_METRIC_COUNTER_0, XAPM_METRIC_COUNTER_1, XAxiPmon_EnableMetricsCounter, XAxiPmon_ResetGlobalClkCounter, XAxiPmon_ResetMetricCounter, XAxiPmon_SetMetrics, XAxiPmon_StartCounters.
Referenced by OcmTransaction.
void ReadMetrics(XAxiPmon *InstancePtr, u32 *BufferPtr, u8 Counter1, u8 Counter2)
Reads metrics from APM counters to buffer.
InstancePtr is pointer to APM instance. BufferPtr is pointer to buffer. Counter1 is counter number. Counter2 is counter number. None. None.
References XAxiPmon_GetMetricCounter, XAxiPmon_StopCounters.
Referenced by OcmTransaction.
int main(void)
Main function that invokes the example in this file.
None. XST_SUCCESS if the example has completed successfully.XST_FAILURE if the example has failed. None.
References ApmCheck, XAxiPmon_Config::BaseAddress, OcmTransaction, XAxiPmon_CfgInitialize, XAxiPmon_DisableMetricsCounter, XAxiPmon_LookupConfig.