xadcps_intr.c
void XAdcPs_IntrEnable(XAdcPs *InstancePtr, u32 Mask)
Functions in xadcps_intr.c.
This function enables the specified interrupts in the device. InstancePtr is a pointer to the XAdcPs instance. Mask is the bit-mask of the interrupts to be enabled. Bit positions of 1 will be enabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XADCPS_INTX_* bits defined in xadcps_hw.h. None. None.
References XAdcPs_Config::BaseAddress, XAdcPs::Config, XAdcPs::IsReady, XADCPS_INT_MASK_OFFSET, XADCPS_INTX_ALL_MASK, XAdcPs_ReadReg, XAdcPs_WriteReg.
Referenced by XAdcIntrExample.
void XAdcPs_IntrDisable(XAdcPs *InstancePtr, u32 Mask)
This function disables the specified interrupts in the device.
InstancePtr is a pointer to the XAdcPs instance. Mask is the bit-mask of the interrupts to be disabled. Bit positions of 1 will be disabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XADCPS_INTX_* bits defined in xadcps_hw.h. None. None
References XAdcPs_Config::BaseAddress, XAdcPs::Config, XAdcPs::IsReady, XADCPS_INT_MASK_OFFSET, XADCPS_INTX_ALL_MASK, XAdcPs_ReadReg, XAdcPs_WriteReg.
u32 XAdcPs_IntrGetEnabled(XAdcPs *InstancePtr)
This function returns the enabled interrupts read from the Interrupt Mask Register (IPIER).
Use the XADCPS_IPIXR_* constants defined in xadcps_hw.h to interpret the returned value. InstancePtr is a pointer to the XAdcPs instance. A 32-bit value representing the contents of the I. None.
References XAdcPs_Config::BaseAddress, XAdcPs::Config, XAdcPs::IsReady, XADCPS_INT_MASK_OFFSET, XADCPS_INTX_ALL_MASK, XAdcPs_ReadReg.
u32 XAdcPs_IntrGetStatus(XAdcPs *InstancePtr)
This function returns the interrupt status read from Interrupt Status Register(IPISR).
Use the XADCPS_IPIXR_* constants defined in xadcps_hw.h to interpret the returned value. InstancePtr is a pointer to the XAdcPs instance. A 32-bit value representing the contents of the IPISR. The device must be configured at hardware build time to include interrupt component for this function to work.
References XAdcPs_Config::BaseAddress, XAdcPs::Config, XAdcPs::IsReady, XADCPS_INT_STS_OFFSET, XADCPS_INTX_ALL_MASK, XAdcPs_ReadReg.
Referenced by XAdcIntrExample.
void XAdcPs_IntrClear(XAdcPs *InstancePtr, u32 Mask)
This function clears the specified interrupts in the Interrupt Status Register (IPISR).
InstancePtr is a pointer to the XAdcPs instance. Mask is the bit-mask of the interrupts to be cleared. Bit positions of 1 will be cleared. Bit positions of 0 will not change the previous interrupt status. This mask is formed by OR'ing XADCPS_IPIXR_* bits which are defined in xadcps_hw.h. None. None.
References XAdcPs_Config::BaseAddress, XAdcPs::Config, XAdcPs::IsReady, XADCPS_INT_STS_OFFSET, XADCPS_INTX_ALL_MASK, XAdcPs_ReadReg, XAdcPs_WriteReg.
Referenced by XAdcIntrExample.