xadcps.h
XADCPS_CH_TEMP
On Chip Temperature.
Referenced by XAdcIntrExample.
XADCPS_CH_VCCINT
VCCINT.
XADCPS_CH_VCCAUX
VCCAUX.
XADCPS_CH_VPVN
VP/VN Dedicated analog inputs.
Referenced by XAdcPs_SetSingleChParams.
XADCPS_CH_VREFP
VREFP.
XADCPS_CH_VREFN
VREFN.
XADCPS_CH_VBRAM
On-chip VBRAM Data Reg, 7 series.
Referenced by XAdcPs_GetAdcData, XAdcPs_SetSingleChParams.
XADCPS_CH_SUPPLY_CALIB
Supply Calib Data Reg.
XADCPS_CH_ADC_CALIB
ADC Offset Channel Reg.
Referenced by XAdcPs_SetSingleChParams.
XADCPS_CH_GAINERR_CALIB
Gain Error Channel Reg.
XADCPS_CH_VCCPINT
On-chip PS VCCPINT Channel , Zynq.
Referenced by XAdcPs_GetAdcData, XAdcPs_SetSingleChParams.
XADCPS_CH_VCCPAUX
On-chip PS VCCPAUX Channel , Zynq.
Referenced by XAdcIntrExample.
XADCPS_CH_VCCPDRO
On-chip PS VCCPDRO Channel , Zynq.
XADCPS_CH_AUX_MIN
Channel number for 1st Aux Channel.
Referenced by XAdcPs_SetSingleChParams.
XADCPS_CH_AUX_MAX
Channel number for Last Aux channel.
Referenced by XAdcPs_GetAdcData, XAdcPs_SetSingleChParams.
XADCPS_CALIB_SUPPLY_COEFF
Supply Offset Calib Coefficient.
XADCPS_CALIB_ADC_COEFF
ADC Offset Calib Coefficient.
XADCPS_CALIB_GAIN_ERROR_COEFF
Gain Error Calib Coefficient.
Referenced by XAdcPs_GetCalibCoefficient.
XADCPS_MAX_TEMP
Maximum Temperature Data.
XADCPS_MAX_VCCINT
Maximum VCCINT Data.
XADCPS_MAX_VCCAUX
Maximum VCCAUX Data.
XADCPS_MAX_VBRAM
Maximum VBRAM Data.
XADCPS_MIN_TEMP
Minimum Temperature Data.
XADCPS_MIN_VCCINT
Minimum VCCINT Data.
XADCPS_MIN_VCCAUX
Minimum VCCAUX Data.
XADCPS_MIN_VBRAM
Minimum VBRAM Data.
XADCPS_MAX_VCCPINT
Maximum VCCPINT Register , Zynq.
XADCPS_MAX_VCCPAUX
Maximum VCCPAUX Register , Zynq.
XADCPS_MAX_VCCPDRO
Maximum VCCPDRO Register , Zynq.
Referenced by XAdcPs_GetMinMaxMeasurement.
XADCPS_MIN_VCCPINT
Minimum VCCPINT Register , Zynq.
Referenced by XAdcPs_GetMinMaxMeasurement.
XADCPS_MIN_VCCPAUX
Minimum VCCPAUX Register , Zynq.
XADCPS_MIN_VCCPDRO
Minimum VCCPDRO Register , Zynq.
Referenced by XAdcPs_GetMinMaxMeasurement.
XADCPS_ATR_TEMP_UPPER
High user Temperature.
Referenced by XAdcIntrExample.
XADCPS_ATR_VCCINT_UPPER
VCCINT high voltage limit register.
Referenced by XAdcPs_SelfTest.
XADCPS_ATR_VCCAUX_UPPER
VCCAUX high voltage limit register.
XADCPS_ATR_OT_UPPER
Over Temperature upper limit.
XADCPS_ATR_TEMP_LOWER
Temperature lower alarm.
Referenced by XAdcIntrExample.
XADCPS_ATR_VCCINT_LOWER
VCCINT low voltage limit register.
XADCPS_ATR_VCCAUX_LOWER
VCCAUX low voltage limit register.
XADCPS_ATR_OT_LOWER
Lower Over Temperature limit.
XADCPS_ATR_VBRAM_UPPER_
VRBAM Upper Alarm Reg, 7 Series.
XADCPS_ATR_VCCPINT_UPPER
VCCPINT Upper Alarm Reg, Zynq.
XADCPS_ATR_VCCPAUX_UPPER
VCCPAUX Upper Alarm Reg, Zynq.
Referenced by XAdcIntrExample.
XADCPS_ATR_VCCPDRO_UPPER
VCCPDRO Upper Alarm Reg, Zynq.
XADCPS_ATR_VBRAM_LOWER
VRBAM Lower Alarm Reg, 7 Series.
XADCPS_ATR_VCCPINT_LOWER
VCCPINT Lower Alarm Reg , Zynq.
XADCPS_ATR_VCCPAUX_LOWER
VCCPAUX Lower Alarm Reg , Zynq.
Referenced by XAdcIntrExample.
XADCPS_ATR_VCCPDRO_LOWER
VCCPDRO Lower Alarm Reg , Zynq.
Referenced by XAdcPs_GetAlarmThreshold, XAdcPs_SetAlarmThreshold.
XADCPS_AVG_0_SAMPLES
No Averaging.
XADCPS_AVG_16_SAMPLES
Average 16 samples.
XADCPS_AVG_64_SAMPLES
Average 64 samples.
XADCPS_AVG_256_SAMPLES
Average 256 samples.
Referenced by XAdcPs_SetAvg.
XADCPS_SEQ_MODE_SAFE
Default Safe Mode.
Referenced by XAdcIntrExample, XAdcPs_SetSeqAcqTime, XAdcPs_SetSeqAvgEnables, XAdcPs_SetSeqChEnables, XAdcPs_SetSeqInputMode.
XADCPS_SEQ_MODE_ONEPASS
Onepass through Sequencer.
XADCPS_SEQ_MODE_CONTINPASS
Continuous Cycling Sequencer.
XADCPS_SEQ_MODE_SINGCHAN
Single channel -No Sequencing.
Referenced by XAdcPs_SetSingleChParams.
XADCPS_SEQ_MODE_SIMUL_SAMPLING
Simultaneous sampling.
Referenced by XAdcPs_SetSequencerMode.
XADCPS_SEQ_MODE_INDEPENDENT
Independent mode.
Referenced by XAdcIntrExample, XAdcPs_SetSequencerMode.
XADCPS_PD_MODE_NONE
No Power Down.
XADCPS_PD_MODE_ADCB
Power Down ADC B.
XADCPS_PD_MODE_XADC
Power Down ADC A and ADC B.
Referenced by XAdcPs_SetPowerdownMode.
XADCPS_H
XAdcPs_IsEventSamplingModeSet
This macro checks if the XADC device is in Event Sampling mode.
InstancePtr is a pointer to the XAdcPs instance. TRUE if the device is in Event Sampling Mode.FALSE if the device is in Continuous Sampling Mode. C-Style signature: int XAdcPs_IsEventSamplingMode(XAdcPs *InstancePtr);
XAdcPs_IsExternalMuxModeSet
This macro checks if the XADC device is in External Mux mode.
InstancePtr is a pointer to the XAdcPs instance. TRUE if the device is in External Mux Mode.FALSE if the device is NOT in External Mux Mode. C-Style signature: int XAdcPs_IsExternalMuxMode(XAdcPs *InstancePtr);
XAdcPs_RawToTemperature
This macro converts XADC Raw Data to Temperature(centigrades).
AdcData is the Raw ADC Data from XADC. The Temperature in centigrades. C-Style signature: float XAdcPs_RawToTemperature(u32 AdcData);
Referenced by XAdcIntrExample.
XAdcPs_RawToVoltage
This macro converts XADC/ADC Raw Data to Voltage(volts).
AdcData is the XADC/ADC Raw Data. The Voltage in volts. C-Style signature: float XAdcPs_RawToVoltage(u32 AdcData);
XAdcPs_TemperatureToRaw
This macro converts Temperature in centigrades to XADC/ADC Raw Data.
Temperature is the Temperature in centigrades to be converted to XADC/ADC Raw Data. The XADC/ADC Raw Data. C-Style signature: int XAdcPs_TemperatureToRaw(float Temperature);
XAdcPs_VoltageToRaw
This macro converts Voltage in Volts to XADC/ADC Raw Data.
Voltage is the Voltage in volts to be converted to XADC/ADC Raw Data. The XADC/ADC Raw Data. C-Style signature: int XAdcPs_VoltageToRaw(float Voltage);
XAdcPs_WriteFifo
This macro is used for writing to the XADC Registers using the command FIFO.
InstancePtr is a pointer to the XAdcPs instance. Data is the value to be written to XADC register. None. C-Style signature: void XAdcPs_WriteFifo(XAdcPs *InstancePtr, u32 Data);
Referenced by XAdcPs_ReadInternalReg, XAdcPs_WriteInternalReg.
XAdcPs_ReadFifo
This macro is used for reading from the XADC Registers using the data FIFO.
InstancePtr is a pointer to the XAdcPs instance. Data read from the FIFO C-Style signature: u32 XAdcPs_ReadFifo(XAdcPs *InstancePtr);
Referenced by XAdcPs_ReadInternalReg, XAdcPs_WriteInternalReg.
XAdcPs_Config * XAdcPs_LookupConfig(u32 BaseAddress)
Functions in xadcps_sinit.c.
This function looks up the device configuration based on the unique device ID.The table XAdcPs_ConfigTable contains the configuration info for each device in the system. DeviceId contains the ID of the device for which the device configuration pointer is to be returned. A pointer to the configuration found.NULL if the specified device ID was not found. None.
Referenced by XAdcIntrExample.
int XAdcPs_CfgInitialize(XAdcPs *InstancePtr, XAdcPs_Config *ConfigPtr, u32 EffectiveAddr)
This function initializes a specific XAdcPs device/instance.
Functions in xadcps.c.This function must be called prior to using the XADC device. InstancePtr is a pointer to the XAdcPs instance. ConfigPtr points to the XAdcPs device configuration structure. EffectiveAddr is the device base address in the virtual memory address space. If the address translation is not used then the physical address is passed. Unexpected errors may occur if the address mapping is changed after this function is invoked. XST_SUCCESS if successful. The user needs to first call the XAdcPs_LookupConfig() API which returns the Configuration structure pointer which is passed as a parameter to the XAdcPs_CfgInitialize() API.
References XAdcPs_Config::BaseAddress, XAdcPs::Config, XAdcPs::IsReady, XADCPS_CFG_CFIFOTH_MASK, XADCPS_CFG_DFIFOTH_MASK, XADCPS_CFG_ENABLE_MASK, XADCPS_CFG_OFFSET, XADCPS_MCTL_OFFSET, XAdcPs_ReadReg, XADCPS_UNLK_OFFSET, XADCPS_UNLK_VALUE, XAdcPs_WriteReg.
Referenced by XAdcIntrExample.
void XAdcPs_SetConfigRegister(XAdcPs *InstancePtr, u32 Data)
The functions sets the contents of the Config Register.
InstancePtr is a pointer to the XAdcPs instance. Data is the 32 bit data to be written to the Register. None. None.
References XAdcPs::IsReady, XADCPS_CFG_OFFSET, XAdcPs_WriteReg.
u32 XAdcPs_GetConfigRegister(XAdcPs *InstancePtr)
The functions reads the contents of the Config Register.
InstancePtr is a pointer to the XAdcPs instance. A 32-bit value representing the contents of the Config Register. Use the XADCPS_SR_*_MASK constants defined in xadcps_hw.h to interpret the returned value. None.
References XAdcPs::IsReady, XADCPS_CFG_OFFSET, XAdcPs_ReadReg.
u32 XAdcPs_GetMiscStatus(XAdcPs *InstancePtr)
The functions reads the contents of the Miscellaneous Status Register.
InstancePtr is a pointer to the XAdcPs instance. A 32-bit value representing the contents of the Miscellaneous Status Register. Use the XADCPS_MSTS_*_MASK constants defined in xadcps_hw.h to interpret the returned value. None.
References XAdcPs::IsReady, XADCPS_MSTS_OFFSET, XAdcPs_ReadReg.
void XAdcPs_SetMiscCtrlRegister(XAdcPs *InstancePtr, u32 Data)
The functions sets the contents of the Miscellaneous Control register.
InstancePtr is a pointer to the XAdcPs instance. Data is the 32 bit data to be written to the Register. None. None.
References XAdcPs::IsReady, XADCPS_MCTL_OFFSET, XAdcPs_WriteReg.
u32 XAdcPs_GetMiscCtrlRegister(XAdcPs *InstancePtr)
The functions reads the contents of the Miscellaneous control register.
InstancePtr is a pointer to the XAdcPs instance. A 32-bit value representing the contents of the Config Register. Use the XADCPS_SR_*_MASK constants defined in xadcps_hw.h to interpret the returned value. None.
References XAdcPs::IsReady, XADCPS_MCTL_OFFSET, XAdcPs_ReadReg.
void XAdcPs_Reset(XAdcPs *InstancePtr)
This function resets the XADC Hard Macro in the device.
InstancePtr is a pointer to the Xxadc instance. None. None.
References XAdcPs::IsReady, XADCPS_MCTL_OFFSET, XAdcPs_WriteReg.
Referenced by XAdcPs_SelfTest.
u16 XAdcPs_GetAdcData(XAdcPs *InstancePtr, u8 Channel)
Get the ADC converted data for the specified channel.
InstancePtr is a pointer to the XAdcPs instance. Channel is the channel number. Use the XADCPS_CH_* defined in the file xadcps.h. The valid channels are 0 to 613 to 31 A 16-bit value representing the ADC converted data for the specified channel. The XADC Monitor/ADC device guarantees a 10 bit resolution for the ADC converted data and data is the 10 MSB bits of the 16 data read from the device. The channels 7,8,9 are used for calibration of the device and hence there is no associated data with this channel.
References XAdcPs::IsReady, XADCPS_CH_AUX_MAX, XADCPS_CH_VBRAM, XADCPS_CH_VCCPINT, XAdcPs_ReadInternalReg, XADCPS_TEMP_OFFSET.
Referenced by XAdcIntrExample.
u16 XAdcPs_GetCalibCoefficient(XAdcPs *InstancePtr, u8 CoeffType)
This function gets the calibration coefficient data for the specified parameter.
InstancePtr is a pointer to the XAdcPs instance. CoeffType specifies the calibration coefficient to be read. Use XADCPS_CALIB_* constants defined in xadcps.h to specify the calibration coefficient to be read. A 16-bit value representing the calibration coefficient. The XADC device guarantees a 10 bit resolution for the ADC converted data and data is the 10 MSB bits of the 16 data read from the device. None.
References XAdcPs::IsReady, XADCPS_ADC_A_SUPPLY_CALIB_OFFSET, XADCPS_CALIB_GAIN_ERROR_COEFF, XAdcPs_ReadInternalReg.
u16 XAdcPs_GetMinMaxMeasurement(XAdcPs *InstancePtr, u8 MeasurementType)
This function reads the Minimum/Maximum measurement for one of the specified parameters.
Use XADCPS_MAX_* and XADCPS_MIN_* constants defined in xadcps.h to specify the parameters (Temperature, VccInt, VccAux, VBram, VccPInt, VccPAux and VccPDro). InstancePtr is a pointer to the XAdcPs instance. MeasurementType specifies the parameter for which the Minimum/Maximum measurement has to be read. Use XADCPS_MAX_* and XADCPS_MIN_* constants defined in xadcps.h to specify the data to be read. A 16-bit value representing the maximum/minimum measurement for specified parameter. The XADC device guarantees a 10 bit resolution for the ADC converted data and data is the 10 MSB bits of the 16 data read from the device. None.
References XAdcPs::IsReady, XADCPS_MAX_TEMP_OFFSET, XADCPS_MAX_VCCPDRO, XADCPS_MIN_VCCPDRO, XADCPS_MIN_VCCPINT, XAdcPs_ReadInternalReg.
void XAdcPs_SetAvg(XAdcPs *InstancePtr, u8 Average)
This function sets the number of samples of averaging that is to be done for all the channels in both the single channel mode and sequence mode of operations.
InstancePtr is a pointer to the XAdcPs instance. Average is the number of samples of averaging programmed to the Configuration Register 0. Use the XADCPS_AVG_* definitions defined in xadcps.h file : XADCPS_AVG_0_SAMPLES for no averagingXADCPS_AVG_16_SAMPLES for 16 samples of averagingXADCPS_AVG_64_SAMPLES for 64 samples of averagingXADCPS_AVG_256_SAMPLES for 256 samples of averaging None. None.
References XAdcPs::IsReady, XADCPS_AVG_256_SAMPLES, XADCPS_CFR0_AVG_SHIFT, XADCPS_CFR0_AVG_VALID_MASK, XADCPS_CFR0_OFFSET, XAdcPs_ReadInternalReg, XAdcPs_WriteInternalReg.
u8 XAdcPs_GetAvg(XAdcPs *InstancePtr)
This function returns the number of samples of averaging configured for all the channels in the Configuration Register 0.
InstancePtr is a pointer to the XAdcPs instance. The averaging read from the Configuration Register 0 is returned. Use the XADCPS_AVG_* bit definitions defined in xadcps.h file to interpret the returned value : XADCPS_AVG_0_SAMPLES means no averagingXADCPS_AVG_16_SAMPLES means 16 samples of averagingXADCPS_AVG_64_SAMPLES means 64 samples of averagingXADCPS_AVG_256_SAMPLES means 256 samples of averaging None.
References XAdcPs::IsReady, XADCPS_CFR0_AVG_SHIFT, XADCPS_CFR0_AVG_VALID_MASK, XADCPS_CFR0_OFFSET, XAdcPs_ReadInternalReg.
int XAdcPs_SetSingleChParams(XAdcPs *InstancePtr, u8 Channel, int IncreaseAcqCycles, int IsEventMode, int IsDifferentialMode)
The function sets the given parameters in the Configuration Register 0 in the single channel mode.
InstancePtr is a pointer to the XAdcPs instance. Channel is the channel number for the single channel mode. The valid channels are 0 to 6, 8, and 13 to 31. If the external Mux is used then this specifies the channel oonnected to the external Mux. Please read the Device Spec to know which channels are valid. IncreaseAcqCycles is a boolean parameter which specifies whether the Acquisition time for the external channels has to be increased to 10 ADCCLK cycles (specify TRUE) or remain at the default 4 ADCCLK cycles (specify FALSE). This parameter is only valid for the external channels. IsEventMode specifies whether the operation of the ADC is Event driven or Continuous mode. IsDifferentialMode is a boolean parameter which specifies unipolar(specify FALSE) or differential mode (specify TRUE) for the analog inputs. The input mode is only valid for the external channels. XST_SUCCESS if the given values were written successfully to the Configuration Register 0.XST_FAILURE if the channel sequencer is enabled or the input parameters are not valid for the selected channel. The number of samples for the averaging for all the channels is set by using the function XAdcPs_SetAvg.The calibration of the device is done by doing a ADC conversion on the calibration channel(channel 8). The input parameters IncreaseAcqCycles, IsDifferentialMode and IsEventMode are not valid for this channel
References XAdcPs::IsReady, XADCPS_CFR0_ACQ_MASK, XADCPS_CFR0_AVG_VALID_MASK, XADCPS_CFR0_CHANNEL_MASK, XADCPS_CFR0_DU_MASK, XADCPS_CFR0_EC_MASK, XADCPS_CFR0_OFFSET, XADCPS_CH_ADC_CALIB, XADCPS_CH_AUX_MAX, XADCPS_CH_AUX_MIN, XADCPS_CH_VBRAM, XADCPS_CH_VCCPINT, XADCPS_CH_VPVN, XAdcPs_GetSequencerMode, XAdcPs_ReadInternalReg, XADCPS_SEQ_MODE_SINGCHAN, XAdcPs_WriteInternalReg.
void XAdcPs_SetAlarmEnables(XAdcPs *InstancePtr, u16 AlmEnableMask)
This function enables the alarm outputs for the specified alarms in the Configuration Register 1.
InstancePtr is a pointer to the XAdcPs instance. AlmEnableMask is the bit-mask of the alarm outputs to be enabled in the Configuration Register 1. Bit positions of 1 will be enabled. Bit positions of 0 will be disabled. This mask is formed by OR'ing XADCPS_CFR1_ALM_*_MASK and XADCPS_CFR1_OT_MASK masks defined in xadcps_hw.h. None. The implementation of the alarm enables in the Configuration register 1 is such that the alarms for bit positions of 1 will be disabled and alarms for bit positions of 0 will be enabled. The alarm outputs specified by the AlmEnableMask are negated before writing to the Configuration Register 1.
References XAdcPs::IsReady, XADCPS_CFR1_ALM_ALL_MASK, XADCPS_CFR1_OFFSET, XAdcPs_ReadInternalReg, XAdcPs_WriteInternalReg.
Referenced by XAdcIntrExample.
u16 XAdcPs_GetAlarmEnables(XAdcPs *InstancePtr)
This function gets the status of the alarm output enables in the Configuration Register 1.
InstancePtr is a pointer to the XAdcPs instance. This is the bit-mask of the enabled alarm outputs in the Configuration Register 1. Use the masks XADCPS_CFR1_ALM*_* and XADCPS_CFR1_OT_MASK defined in xadcps_hw.h to interpret the returned value. Bit positions of 1 indicate that the alarm output is enabled. Bit positions of 0 indicate that the alarm output is disabled. The implementation of the alarm enables in the Configuration register 1 is such that alarms for the bit positions of 1 will be disabled and alarms for bit positions of 0 will be enabled. The enabled alarm outputs returned by this function is the negated value of the the data read from the Configuration Register 1.
References XAdcPs::IsReady, XADCPS_CFR1_ALM_ALL_MASK, XADCPS_CFR1_OFFSET, XAdcPs_ReadInternalReg.
void XAdcPs_SetCalibEnables(XAdcPs *InstancePtr, u16 Calibration)
This function enables the specified calibration in the Configuration Register 1 :
XADCPS_CFR1_CAL_ADC_OFFSET_MASK : Calibration 0 -ADC offset correctionXADCPS_CFR1_CAL_ADC_GAIN_OFFSET_MASK : Calibration 1 -ADC gain and offset correctionXADCPS_CFR1_CAL_PS_OFFSET_MASK : Calibration 2 -Power Supply sensor offset correctionXADCPS_CFR1_CAL_PS_GAIN_OFFSET_MASK : Calibration 3 -Power Supply sensor gain and offset correctionXADCPS_CFR1_CAL_DISABLE_MASK : No Calibration InstancePtr is a pointer to the XAdcPs instance. Calibration is the Calibration to be applied. Use XADCPS_CFR1_CAL*_* bits defined in xadcps_hw.h. Multiple calibrations can be enabled at a time by oring the XADCPS_CFR1_CAL_ADC_* and XADCPS_CFR1_CAL_PS_* bits. Calibration can be disabled by specifying XADCPS_CFR1_CAL_DISABLE_MASK; None. None.
References XAdcPs::IsReady, XADCPS_CFR1_CAL_ADC_OFFSET_MASK, XADCPS_CFR1_CAL_DISABLE_MASK, XADCPS_CFR1_CAL_VALID_MASK, XADCPS_CFR1_OFFSET, XAdcPs_ReadInternalReg, XAdcPs_WriteInternalReg.
u16 XAdcPs_GetCalibEnables(XAdcPs *InstancePtr)
This function reads the value of the calibration enables from the Configuration Register 1.
InstancePtr is a pointer to the XAdcPs instance. The value of the calibration enables in the Configuration Register 1 : XADCPS_CFR1_CAL_ADC_OFFSET_MASK : ADC offset correctionXADCPS_CFR1_CAL_ADC_GAIN_OFFSET_MASK : ADC gain and offset correctionXADCPS_CFR1_CAL_PS_OFFSET_MASK : Power Supply sensor offset correctionXADCPS_CFR1_CAL_PS_GAIN_OFFSET_MASK : Power Supply sensor gain and offset correctionXADCPS_CFR1_CAL_DISABLE_MASK : No Calibration None.
References XAdcPs::IsReady, XADCPS_CFR1_CAL_VALID_MASK, XADCPS_CFR1_OFFSET, XAdcPs_ReadInternalReg.
void XAdcPs_SetSequencerMode(XAdcPs *InstancePtr, u8 SequencerMode)
This function sets the specified Channel Sequencer Mode in the Configuration Register 1 :
- Default safe mode (XADCPS_SEQ_MODE_SAFE) - One pass through sequence (XADCPS_SEQ_MODE_ONEPASS) - Continuous channel sequencing (XADCPS_SEQ_MODE_CONTINPASS) - Single Channel/Sequencer off (XADCPS_SEQ_MODE_SINGCHAN) - Simultaneous sampling mode (XADCPS_SEQ_MODE_SIMUL_SAMPLING) - Independent mode (XADCPS_SEQ_MODE_INDEPENDENT) InstancePtr is a pointer to the XAdcPs instance. SequencerMode is the sequencer mode to be set. Use XADCPS_SEQ_MODE_* bits defined in xadcps.h. None. Only one of the modes can be enabled at a time. Please read the Spec of the XADC for further information about the sequencer modes.
References XAdcPs::IsReady, XADCPS_CFR1_OFFSET, XADCPS_CFR1_SEQ_SHIFT, XADCPS_CFR1_SEQ_VALID_MASK, XAdcPs_ReadInternalReg, XADCPS_SEQ_MODE_INDEPENDENT, XADCPS_SEQ_MODE_SIMUL_SAMPLING, XAdcPs_WriteInternalReg.
Referenced by XAdcIntrExample.
u8 XAdcPs_GetSequencerMode(XAdcPs *InstancePtr)
This function gets the channel sequencer mode from the Configuration Register 1.
InstancePtr is a pointer to the XAdcPs instance. The channel sequencer mode : XADCPS_SEQ_MODE_SAFE : Default safe modeXADCPS_SEQ_MODE_ONEPASS : One pass through sequenceXADCPS_SEQ_MODE_CONTINPASS : Continuous channel sequencingXADCPS_SEQ_MODE_SINGCHAN : Single channel/Sequencer offXADCPS_SEQ_MODE_SIMUL_SAMPLING : Simultaneous sampling modeXADCPS_SEQ_MODE_INDEPENDENT : Independent mode None.
References XAdcPs::IsReady, XADCPS_CFR1_OFFSET, XADCPS_CFR1_SEQ_SHIFT, XADCPS_CFR1_SEQ_VALID_MASK, XAdcPs_ReadInternalReg.
Referenced by XAdcPs_SetSeqAcqTime, XAdcPs_SetSeqAvgEnables, XAdcPs_SetSeqChEnables, XAdcPs_SetSeqInputMode, XAdcPs_SetSingleChParams.
void XAdcPs_SetAdcClkDivisor(XAdcPs *InstancePtr, u8 Divisor)
The function sets the frequency of the ADCCLK by configuring the DCLK to ADCCLK ratio in the Configuration Register #2.
InstancePtr is a pointer to the XAdcPs instance. Divisor is clock divisor used to derive ADCCLK from DCLK. Valid values of the divisor are 0 to 255. Values 0, 1, 2 are all mapped to 2. Refer to the device specification for more details None. - The ADCCLK is an internal clock used by the ADC and is synchronized to the DCLK clock. The ADCCLK is equal to DCLK divided by the user selection in the Configuration Register 2. There is no Assert on the minimum value of the Divisor.
References XAdcPs::IsReady, XADCPS_CFR2_CD_SHIFT, XADCPS_CFR2_OFFSET, XAdcPs_WriteInternalReg.
u8 XAdcPs_GetAdcClkDivisor(XAdcPs *InstancePtr)
The function gets the ADCCLK divisor from the Configuration Register 2.
InstancePtr is a pointer to the XAdcPs instance. The divisor read from the Configuration Register 2. The ADCCLK is an internal clock used by the ADC and is synchronized to the DCLK clock. The ADCCLK is equal to DCLK divided by the user selection in the Configuration Register 2.
References XAdcPs::IsReady, XADCPS_CFR2_CD_SHIFT, XADCPS_CFR2_OFFSET, XAdcPs_ReadInternalReg.
int XAdcPs_SetSeqChEnables(XAdcPs *InstancePtr, u32 ChEnableMask)
This function enables the specified channels in the ADC Channel Selection Sequencer Registers.
The sequencer must be disabled before writing to these registers. InstancePtr is a pointer to the XAdcPs instance. ChEnableMask is the bit mask of all the channels to be enabled. Use XADCPS_SEQ_CH__* defined in xadcps_hw.h to specify the Channel numbers. Bit masks of 1 will be enabled and bit mask of 0 will be disabled. The ChEnableMask is a 32 bit mask that is written to the two 16 bit ADC Channel Selection Sequencer Registers. XST_SUCCESS if the given values were written successfully to the ADC Channel Selection Sequencer Registers.XST_FAILURE if the channel sequencer is enabled. None
References XAdcPs::IsReady, XAdcPs_GetSequencerMode, XADCPS_SEQ00_CH_VALID_MASK, XADCPS_SEQ00_OFFSET, XADCPS_SEQ01_CH_VALID_MASK, XADCPS_SEQ01_OFFSET, XADCPS_SEQ_CH_AUX_SHIFT, XADCPS_SEQ_MODE_SAFE, XAdcPs_WriteInternalReg.
u32 XAdcPs_GetSeqChEnables(XAdcPs *InstancePtr)
This function gets the channel enable bits status from the ADC Channel Selection Sequencer Registers.
InstancePtr is a pointer to the XAdcPs instance. Gets the channel enable bits. Use XADCPS_SEQ_CH__* defined in xadcps_hw.h to interpret the Channel numbers. Bit masks of 1 are the channels that are enabled and bit mask of 0 are the channels that are disabled.None None
References XAdcPs::IsReady, XAdcPs_ReadInternalReg, XADCPS_SEQ00_CH_VALID_MASK, XADCPS_SEQ00_OFFSET, XADCPS_SEQ01_CH_VALID_MASK, XADCPS_SEQ01_OFFSET, XADCPS_SEQ_CH_AUX_SHIFT.
int XAdcPs_SetSeqAvgEnables(XAdcPs *InstancePtr, u32 AvgEnableChMask)
This function enables the averaging for the specified channels in the ADC Channel Averaging Enable Sequencer Registers.
The sequencer must be disabled before writing to these registers. InstancePtr is a pointer to the XAdcPs instance. AvgEnableChMask is the bit mask of all the channels for which averaging is to be enabled. Use XADCPS_SEQ_CH__* defined in xadcps_hw.h to specify the Channel numbers. Averaging will be enabled for bit masks of 1 and disabled for bit mask of 0. The AvgEnableChMask is a 32 bit mask that is written to the two 16 bit ADC Channel Averaging Enable Sequencer Registers. XST_SUCCESS if the given values were written successfully to the ADC Channel Averaging Enables Sequencer Registers.XST_FAILURE if the channel sequencer is enabled. None
References XAdcPs::IsReady, XAdcPs_GetSequencerMode, XADCPS_SEQ02_CH_VALID_MASK, XADCPS_SEQ02_OFFSET, XADCPS_SEQ03_CH_VALID_MASK, XADCPS_SEQ03_OFFSET, XADCPS_SEQ_CH_AUX_SHIFT, XADCPS_SEQ_MODE_SAFE, XAdcPs_WriteInternalReg.
u32 XAdcPs_GetSeqAvgEnables(XAdcPs *InstancePtr)
This function returns the channels for which the averaging has been enabled in the ADC Channel Averaging Enables Sequencer Registers.
InstancePtr is a pointer to the XAdcPs instance. The status of averaging (enabled/disabled) for all the channels. Use XADCPS_SEQ_CH__* defined in xadcps_hw.h to interpret the Channel numbers. Bit masks of 1 are the channels for which averaging is enabled and bit mask of 0 are the channels for averaging is disabled None
References XAdcPs::IsReady, XAdcPs_ReadInternalReg, XADCPS_SEQ02_CH_VALID_MASK, XADCPS_SEQ02_OFFSET, XADCPS_SEQ03_CH_VALID_MASK, XADCPS_SEQ03_OFFSET, XADCPS_SEQ_CH_AUX_SHIFT.
int XAdcPs_SetSeqInputMode(XAdcPs *InstancePtr, u32 InputModeChMask)
This function sets the Analog input mode for the specified channels in the ADC Channel Analog-Input Mode Sequencer Registers.
The sequencer must be disabled before writing to these registers. InstancePtr is a pointer to the XAdcPs instance. InputModeChMask is the bit mask of all the channels for which the input mode is differential mode. Use XADCPS_SEQ_CH__* defined in xadcps_hw.h to specify the channel numbers. Differential input mode will be set for bit masks of 1 and unipolar input mode for bit masks of 0. The InputModeChMask is a 32 bit mask that is written to the two 16 bit ADC Channel Analog-Input Mode Sequencer Registers. XST_SUCCESS if the given values were written successfully to the ADC Channel Analog-Input Mode Sequencer Registers.XST_FAILURE if the channel sequencer is enabled. None
References XAdcPs::IsReady, XAdcPs_GetSequencerMode, XADCPS_SEQ04_CH_VALID_MASK, XADCPS_SEQ04_OFFSET, XADCPS_SEQ05_CH_VALID_MASK, XADCPS_SEQ05_OFFSET, XADCPS_SEQ_CH_AUX_SHIFT, XADCPS_SEQ_MODE_SAFE, XAdcPs_WriteInternalReg.
u32 XAdcPs_GetSeqInputMode(XAdcPs *InstancePtr)
This function gets the Analog input mode for all the channels from the ADC Channel Analog-Input Mode Sequencer Registers.
InstancePtr is a pointer to the XAdcPs instance. The input mode for all the channels. Use XADCPS_SEQ_CH_* defined in xadcps_hw.h to interpret the Channel numbers. Bit masks of 1 are the channels for which input mode is differential and bit mask of 0 are the channels for which input mode is unipolar. None.
References XAdcPs::IsReady, XAdcPs_ReadInternalReg, XADCPS_SEQ04_CH_VALID_MASK, XADCPS_SEQ04_OFFSET, XADCPS_SEQ05_CH_VALID_MASK, XADCPS_SEQ05_OFFSET, XADCPS_SEQ_CH_AUX_SHIFT.
int XAdcPs_SetSeqAcqTime(XAdcPs *InstancePtr, u32 AcqCyclesChMask)
This function sets the number of Acquisition cycles in the ADC Channel Acquisition Time Sequencer Registers.
The sequencer must be disabled before writing to these registers. InstancePtr is a pointer to the XAdcPs instance. AcqCyclesChMask is the bit mask of all the channels for which the number of acquisition cycles is to be extended. Use XADCPS_SEQ_CH__* defined in xadcps_hw.h to specify the Channel numbers. Acquisition cycles will be extended to 10 ADCCLK cycles for bit masks of 1 and will be the default 4 ADCCLK cycles for bit masks of 0. The AcqCyclesChMask is a 32 bit mask that is written to the two 16 bit ADC Channel Acquisition Time Sequencer Registers. XST_SUCCESS if the given values were written successfully to the Channel Sequencer Registers.XST_FAILURE if the channel sequencer is enabled. None.
References XAdcPs::IsReady, XAdcPs_GetSequencerMode, XADCPS_SEQ06_CH_VALID_MASK, XADCPS_SEQ06_OFFSET, XADCPS_SEQ07_CH_VALID_MASK, XADCPS_SEQ07_OFFSET, XADCPS_SEQ_CH_AUX_SHIFT, XADCPS_SEQ_MODE_SAFE, XAdcPs_WriteInternalReg.
u32 XAdcPs_GetSeqAcqTime(XAdcPs *InstancePtr)
This function gets the status of acquisition from the ADC Channel Acquisition Time Sequencer Registers.
InstancePtr is a pointer to the XAdcPs instance. The acquisition time for all the channels. Use XADCPS_SEQ_CH__* defined in xadcps_hw.h to interpret the Channel numbers. Bit masks of 1 are the channels for which acquisition cycles are extended and bit mask of 0 are the channels for which acquisition cycles are not extended. None
References XAdcPs::IsReady, XAdcPs_ReadInternalReg, XADCPS_SEQ06_CH_VALID_MASK, XADCPS_SEQ06_OFFSET, XADCPS_SEQ07_CH_VALID_MASK, XADCPS_SEQ07_OFFSET, XADCPS_SEQ_CH_AUX_SHIFT.
void XAdcPs_SetAlarmThreshold(XAdcPs *InstancePtr, u8 AlarmThrReg, u16 Value)
This functions sets the contents of the given Alarm Threshold Register.
InstancePtr is a pointer to the XAdcPs instance. AlarmThrReg is the index of an Alarm Threshold Register to be set. Use XADCPS_ATR_* constants defined in xadcps.h to specify the index. Value is the 16-bit threshold value to write into the register. None. Use XAdcPs_SetOverTemp() to set the Over Temperature upper threshold value.
References XAdcPs::IsReady, XADCPS_ATR_TEMP_UPPER_OFFSET, XADCPS_ATR_VCCPDRO_LOWER, XAdcPs_WriteInternalReg.
Referenced by XAdcIntrExample, XAdcPs_SelfTest.
u16 XAdcPs_GetAlarmThreshold(XAdcPs *InstancePtr, u8 AlarmThrReg)
This function returns the contents of the specified Alarm Threshold Register.
InstancePtr is a pointer to the XAdcPs instance. AlarmThrReg is the index of an Alarm Threshold Register to be read. Use XADCPS_ATR_* constants defined in xadcps_hw.h to specify the index. A 16-bit value representing the contents of the selected Alarm Threshold Register. None.
References XAdcPs::IsReady, XADCPS_ATR_TEMP_UPPER_OFFSET, XADCPS_ATR_VCCPDRO_LOWER, XAdcPs_ReadInternalReg.
Referenced by XAdcPs_SelfTest.
void XAdcPs_EnableUserOverTemp(XAdcPs *InstancePtr)
This function enables programming of the powerdown temperature for the OverTemp signal in the OT Powerdown register.
InstancePtr is a pointer to the XAdcPs instance. None. None.
References XAdcPs::IsReady, XADCPS_ATR_OT_UPPER_ENB_MASK, XADCPS_ATR_OT_UPPER_ENB_VAL, XADCPS_ATR_OT_UPPER_OFFSET, XAdcPs_ReadInternalReg, XAdcPs_WriteInternalReg.
void XAdcPs_DisableUserOverTemp(XAdcPs *InstancePtr)
This function disables programming of the powerdown temperature for the OverTemp signal in the OT Powerdown register.
InstancePtr is a pointer to the XAdcPs instance. None. None.
References XAdcPs::IsReady, XADCPS_ATR_OT_UPPER_ENB_MASK, XADCPS_ATR_OT_UPPER_OFFSET, XAdcPs_ReadInternalReg, XAdcPs_WriteInternalReg.
void XAdcPs_SetSequencerEvent(XAdcPs *InstancePtr, int IsEventMode)
The function enables the Event mode or Continuous mode in the sequencer mode.
InstancePtr is a pointer to the XAdcPs instance. IsEventMode is a boolean parameter that specifies continuous sampling (specify FALSE) or event driven sampling mode (specify TRUE) for the given channel. None. None.
References XAdcPs::IsReady, XADCPS_CFR0_EC_MASK, XADCPS_CFR0_OFFSET, XAdcPs_ReadInternalReg, XAdcPs_WriteInternalReg.
int XAdcPs_GetSamplingMode(XAdcPs *InstancePtr)
This function returns the sampling mode.
InstancePtr is a pointer to the XAdcPs instance. The sampling mode 0 specifies continuous sampling1 specifies event driven sampling mode None.
References XAdcPs::IsReady, XADCPS_CFR0_EC_MASK, XADCPS_CFR0_OFFSET, XAdcPs_ReadInternalReg.
void XAdcPs_SetMuxMode(XAdcPs *InstancePtr, int MuxMode, u8 Channel)
This function sets the External Mux mode.
InstancePtr is a pointer to the XAdcPs instance. MuxMode specifies whether External Mux is used FALSE specifies NO external MUXTRUE specifies External Mux is used Channel specifies the channel to be used for the external Mux. Please read the Device Spec for which channels are valid for which mode. None. There is no Assert in this function for checking the channel number if the external Mux is used. The user should provide a valid channel number.
References XAdcPs::IsReady, XADCPS_CFR0_CHANNEL_MASK, XADCPS_CFR0_MUX_MASK, XADCPS_CFR0_OFFSET, XAdcPs_ReadInternalReg, XAdcPs_WriteInternalReg.
void XAdcPs_SetPowerdownMode(XAdcPs *InstancePtr, u32 Mode)
This function sets the Power Down mode.
InstancePtr is a pointer to the XAdcPs instance. Mode specifies the Power Down Mode XADCPS_PD_MODE_NONE specifies NO Power Down (Both ADC A and ADC B are enabled)XADCPS_PD_MODE_ADCB specifies the Power Down of ADC BXADCPS_PD_MODE_XADC specifies the Power Down of both ADC A and ADC B. None. None.
References XAdcPs::IsReady, XADCPS_CFR2_OFFSET, XADCPS_CFR2_PD_MASK, XADCPS_CFR2_PD_SHIFT, XADCPS_PD_MODE_XADC, XAdcPs_ReadInternalReg, XAdcPs_WriteInternalReg.
u32 XAdcPs_GetPowerdownMode(XAdcPs *InstancePtr)
This function gets the Power Down mode.
InstancePtr is a pointer to the XAdcPs instance. Mode specifies the Power Down Mode XADCPS_PD_MODE_NONE specifies NO Power Down (Both ADC A and ADC B are enabled)XADCPS_PD_MODE_ADCB specifies the Power Down of ADC BXADCPS_PD_MODE_XADC specifies the Power Down of both ADC A and ADC B. None.
References XAdcPs::IsReady, XADCPS_CFR2_OFFSET, XADCPS_CFR2_PD_MASK, XADCPS_CFR2_PD_SHIFT, XAdcPs_ReadInternalReg.
int XAdcPs_SelfTest(XAdcPs *InstancePtr)
Functions in xadcps_selftest.c.
Run a self-test on the driver/device.The test Resets the device,Writes a value into the Alarm Threshold register and reads it back for comparison.Resets the device again. InstancePtr is a pointer to the XAdcPs instance. XST_SUCCESS if the value read from the Alarm Threshold register is the same as the value written.XST_FAILURE Otherwise This is a destructive test in that resets of the device are performed. Refer to the device specification for the device status after the reset operation.
References XAdcPs::IsReady, XADCPS_ATR_VCCINT_UPPER, XAdcPs_GetAlarmThreshold, XAdcPs_Reset, XAdcPs_SetAlarmThreshold.
Referenced by XAdcIntrExample.
void XAdcPs_IntrEnable(XAdcPs *InstancePtr, u32 Mask)
Functions in xadcps_intr.c.
This function enables the specified interrupts in the device. InstancePtr is a pointer to the XAdcPs instance. Mask is the bit-mask of the interrupts to be enabled. Bit positions of 1 will be enabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XADCPS_INTX_* bits defined in xadcps_hw.h. None. None.
References XAdcPs_Config::BaseAddress, XAdcPs::Config, XAdcPs::IsReady, XADCPS_INT_MASK_OFFSET, XADCPS_INTX_ALL_MASK, XAdcPs_ReadReg, XAdcPs_WriteReg.
Referenced by XAdcIntrExample.
void XAdcPs_IntrDisable(XAdcPs *InstancePtr, u32 Mask)
This function disables the specified interrupts in the device.
InstancePtr is a pointer to the XAdcPs instance. Mask is the bit-mask of the interrupts to be disabled. Bit positions of 1 will be disabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XADCPS_INTX_* bits defined in xadcps_hw.h. None. None
References XAdcPs_Config::BaseAddress, XAdcPs::Config, XAdcPs::IsReady, XADCPS_INT_MASK_OFFSET, XADCPS_INTX_ALL_MASK, XAdcPs_ReadReg, XAdcPs_WriteReg.
u32 XAdcPs_IntrGetEnabled(XAdcPs *InstancePtr)
This function returns the enabled interrupts read from the Interrupt Mask Register (IPIER).
Use the XADCPS_IPIXR_* constants defined in xadcps_hw.h to interpret the returned value. InstancePtr is a pointer to the XAdcPs instance. A 32-bit value representing the contents of the I. None.
References XAdcPs_Config::BaseAddress, XAdcPs::Config, XAdcPs::IsReady, XADCPS_INT_MASK_OFFSET, XADCPS_INTX_ALL_MASK, XAdcPs_ReadReg.
u32 XAdcPs_IntrGetStatus(XAdcPs *InstancePtr)
This function returns the interrupt status read from Interrupt Status Register(IPISR).
Use the XADCPS_IPIXR_* constants defined in xadcps_hw.h to interpret the returned value. InstancePtr is a pointer to the XAdcPs instance. A 32-bit value representing the contents of the IPISR. The device must be configured at hardware build time to include interrupt component for this function to work.
References XAdcPs_Config::BaseAddress, XAdcPs::Config, XAdcPs::IsReady, XADCPS_INT_STS_OFFSET, XADCPS_INTX_ALL_MASK, XAdcPs_ReadReg.
Referenced by XAdcIntrExample.
void XAdcPs_IntrClear(XAdcPs *InstancePtr, u32 Mask)
This function clears the specified interrupts in the Interrupt Status Register (IPISR).
InstancePtr is a pointer to the XAdcPs instance. Mask is the bit-mask of the interrupts to be cleared. Bit positions of 1 will be cleared. Bit positions of 0 will not change the previous interrupt status. This mask is formed by OR'ing XADCPS_IPIXR_* bits which are defined in xadcps_hw.h. None. None.
References XAdcPs_Config::BaseAddress, XAdcPs::Config, XAdcPs::IsReady, XADCPS_INT_STS_OFFSET, XADCPS_INTX_ALL_MASK, XAdcPs_ReadReg, XAdcPs_WriteReg.
Referenced by XAdcIntrExample.