scutimer
XSCUTIMER_LOAD_OFFSET
Timer Load Register.
Referenced by XScuTimer_SelfTest.
XSCUTIMER_COUNTER_OFFSET
Timer Counter Register.
XSCUTIMER_CONTROL_OFFSET
Timer Control Register.
Referenced by XScuTimer_GetPrescaler, XScuTimer_SelfTest, XScuTimer_SetPrescaler, XScuTimer_Start, XScuTimer_Stop.
XSCUTIMER_ISR_OFFSET
Timer Interrupt Status Register.
XSCUTIMER_CONTROL_PRESCALER_MASK
Prescaler.
Referenced by XScuTimer_GetPrescaler, XScuTimer_SetPrescaler.
XSCUTIMER_CONTROL_PRESCALER_SHIFT
XSCUTIMER_CONTROL_IRQ_ENABLE_MASK
Intr enable.
XSCUTIMER_CONTROL_AUTO_RELOAD_MASK
Auto-reload.
XSCUTIMER_CONTROL_ENABLE_MASK
Timer enable.
Referenced by XScuTimer_SelfTest, XScuTimer_Start, XScuTimer_Stop.
XSCUTIMER_ISR_EVENT_FLAG_MASK
Event flag.
XScuTimer_Config XScuTimer_ConfigTable[XPAR_XSCUTIMER_NUM_INSTANCES][XPAR_XSCUTIMER_NUM_INSTANCES]
This table contains configuration information for each timer device in the system.
XScuTimer_Config XScuTimer_ConfigTable[][]
This table contains configuration information for each timer device in the system.
s32 XScuTimer_CfgInitialize(XScuTimer *InstancePtr, XScuTimer_Config *ConfigPtr, u32 EffectiveAddress)
Initialize a specific timer instance/driver.
This function must be called before other functions of the driver are called. InstancePtr is a pointer to the XScuTimer instance. ConfigPtr points to the XScuTimer configuration structure. EffectiveAddress is the base address for the device. It could be a virtual address if address translation is supported in the system, otherwise it is the physical address. XST_SUCCESS if initialization was successful.XST_DEVICE_IS_STARTED if the device has already been started. None.
References XScuTimer_Config::BaseAddr, XScuTimer::Config, XScuTimer::IsReady, XScuTimer::IsStarted.
Referenced by ScuTimerIntrExample, ScuTimerPolledExample.
void XScuTimer_Start(XScuTimer *InstancePtr)
Start the timer.
InstancePtr is a pointer to the XScuTimer instance. None. None.
References XScuTimer_Config::BaseAddr, XScuTimer::Config, XScuTimer::IsReady, XScuTimer::IsStarted, XSCUTIMER_CONTROL_ENABLE_MASK, XSCUTIMER_CONTROL_OFFSET, XScuTimer_ReadReg, XScuTimer_WriteReg.
Referenced by ScuTimerIntrExample, ScuTimerPolledExample.
void XScuTimer_Stop(XScuTimer *InstancePtr)
Stop the timer.
InstancePtr is a pointer to the XScuTimer instance. None. None.
References XScuTimer_Config::BaseAddr, XScuTimer::Config, XScuTimer::IsReady, XScuTimer::IsStarted, XSCUTIMER_CONTROL_ENABLE_MASK, XSCUTIMER_CONTROL_OFFSET, XScuTimer_ReadReg, XScuTimer_WriteReg.
Referenced by ScuTimerIntrExample, ScuTimerPolledExample.
void XScuTimer_SetPrescaler(XScuTimer *InstancePtr, u8 PrescalerValue)
This function sets the prescaler bits in the timer control register.
InstancePtr is a pointer to the XScuTimer instance. PrescalerValue is a 8 bit value that sets the prescaler to use. None None
References XScuTimer_Config::BaseAddr, XScuTimer::Config, XScuTimer::IsReady, XSCUTIMER_CONTROL_OFFSET, XSCUTIMER_CONTROL_PRESCALER_MASK, XScuTimer_ReadReg, XScuTimer_WriteReg.
u8 XScuTimer_GetPrescaler(XScuTimer *InstancePtr)
This function returns the current prescaler value.
InstancePtr is a pointer to the XScuTimer instance. The prescaler value. None.
References XScuTimer_Config::BaseAddr, XScuTimer::Config, XScuTimer::IsReady, XSCUTIMER_CONTROL_OFFSET, XSCUTIMER_CONTROL_PRESCALER_MASK, XScuTimer_ReadReg.
XScuTimer_Config * XScuTimer_LookupConfig(UINTPTR BaseAddr)
Lookup the device configuration based on the unique device ID/BaseAddress.
The table contains the configuration info for each device in the system. BaseAddr contains the base address of the device A pointer to the configuration table entry corresponding to the given device ID/BaseAddress, or NULL if no match is found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
Referenced by ScuTimerIntrExample, ScuTimerPolledExample.
s32 XScuTimer_SelfTest(XScuTimer *InstancePtr)
Run a self-test on the timer.
This test clears the timer enable bit in the control register, writes to the timer load register and verifies the value read back matches the value written and restores the control register and the timer load register. InstancePtr is a pointer to the XScuTimer instance. XST_SUCCESS if self-test was successful.XST_FAILURE if self test was not successful. None.
References XScuTimer_Config::BaseAddr, XScuTimer::Config, XScuTimer::IsReady, XSCUTIMER_CONTROL_ENABLE_MASK, XSCUTIMER_CONTROL_OFFSET, XSCUTIMER_LOAD_OFFSET, XScuTimer_LoadTimer, XScuTimer_ReadReg, XScuTimer_WriteReg.
Referenced by ScuTimerIntrExample.
XSCUTIMER_H
XScuTimer_IsExpired
Check if the timer has expired.
InstancePtr is a pointer to the XScuTimer instance. TRUE if the timer has expired.FALSE if the timer has not expired. C-style signature: int XScuTimer_IsExpired(XScuTimer *InstancePtr)
XScuTimer_RestartTimer
Re-start the timer.
This macro will read the timer load register and writes the same value to load register to update the counter register. InstancePtr is a pointer to the XScuTimer instance. None. C-style signature: void XScuTimer_RestartTimer(XScuTimer *InstancePtr)
XScuTimer_LoadTimer
Write to the timer load register.
This will also update the timer counter register with the new value. This macro can be used to change the time-out value. InstancePtr is a pointer to the XScuTimer instance. Value is the count to be loaded in to the load register. None. C-style signature: void XScuTimer_LoadTimer(XScuTimer *InstancePtr, u32 Value)
Referenced by ScuTimerIntrExample, ScuTimerPolledExample, XScuTimer_SelfTest.
XScuTimer_GetCounterValue
Returns the current timer counter register value.
It can be called at any time. InstancePtr is a pointer to the XScuTimer instance. Contents of the timer counter register. C-style signature: u32 XScuTimer_GetCounterValue(XScuTimer *InstancePtr)
Referenced by ScuTimerPolledExample.
XScuTimer_EnableAutoReload
Enable auto-reload mode.
InstancePtr is a pointer to the XScuTimer instance. None. C-style signature: void XScuTimer_EnableAutoReload(XScuTimer *InstancePtr)
Referenced by ScuTimerIntrExample.
XScuTimer_DisableAutoReload
Disable auto-reload mode.
InstancePtr is a pointer to the XScuTimer instance. None. C-style signature: void XScuTimer_DisableAutoReload(XScuTimer *InstancePtr)
XScuTimer_EnableInterrupt
Enable the Timer interrupt.
InstancePtr is a pointer to the XScuTimer instance. None. C-style signature: void XScuTimer_EnableInterrupt(XScuTimer *InstancePtr)
Referenced by ScuTimerIntrExample.
XScuTimer_DisableInterrupt
Disable the Timer interrupt.
InstancePtr is a pointer to the XScuTimer instance. None. C-style signature: void XScuTimer_DisableInterrupt(XScuTimer *InstancePtr)
XScuTimer_GetInterruptStatus
This function reads the interrupt status.
InstancePtr is a pointer to the XScuTimer instance. None. C-style signature: void XScuTimer_GetInterruptStatus(XScuTimer *InstancePtr)
XScuTimer_ClearInterruptStatus
This function clears the interrupt status.
InstancePtr is a pointer to the XScuTimer instance. None. C-style signature: void XScuTimer_ClearInterruptStatus(XScuTimer *InstancePtr)
XSCUTIMER_HW_H
XScuTimer_SetLoadReg
Write to the timer load register.
This will also update the timer counter register with the new value. This macro can be used to change the time-out value. BaseAddr is the base address of the scu timer. Value is the count to be loaded in to the load register. None. C-style signature: void XScuTimer_SetLoadReg(u32 BaseAddr, u32 Value)
XScuTimer_GetLoadReg
Returns the current timer load register value.
BaseAddr is the base address of the scu timer. Contents of the timer load register. C-style signature: u32 XScuTimer_GetLoadReg(u32 BaseAddr)
XScuTimer_SetCounterReg
Write to the timer counter register.
BaseAddr is the base address of the scu timer. Value is the count to be loaded in to the counter register. None. C-style signature: void XScuTimer_SetCounterReg(u32 BaseAddr, u32 Value)
XScuTimer_GetCounterReg
Returns the current timer counter register value.
BaseAddr is the base address of the scu timer. Contents of the timer counter register. C-style signature: u32 XScuTimer_GetCounterReg(u32 BaseAddr)
XScuTimer_SetControlReg
Write to the timer load register.
This will also update the timer counter register with the new value. This macro can be used to change the time-out value. BaseAddr is the base address of the scu timer. Value is the count to be loaded in to the load register. None. C-style signature: void XScuTimer_SetControlReg(u32 BaseAddr, u32 Value)
XScuTimer_GetControlReg
Returns the current timer load register value.
BaseAddr is the base address of the scu timer. Contents of the timer load register. C-style signature: u32 XScuTimer_GetControlReg(u32 BaseAddr)
XScuTimer_SetIntrReg
Write to the timer counter register.
BaseAddr is the base address of the scu timer. Value is the count to be loaded in to the counter register. None. C-style signature: void XScuTimer_SetIntrReg(u32 BaseAddr, u32 Value)
XScuTimer_GetIntrReg
Returns the current timer counter register value.
BaseAddr is the base address of the scu timer. Contents of the timer counter register. C-style signature: u32 XScuTimer_GetIntrReg(u32 BaseAddr)
XScuTimer_ReadReg
Read from the given Timer register.
BaseAddr is the base address of the device RegOffset is the register offset to be read The 32-bit value of the register C-style signature: u32 XScuTimer_ReadReg(u32 BaseAddr, u32 RegOffset)
Referenced by XScuTimer_GetPrescaler, XScuTimer_SelfTest, XScuTimer_SetPrescaler, XScuTimer_Start, XScuTimer_Stop.
XScuTimer_WriteReg
Write to the given Timer register.
BaseAddr is the base address of the device RegOffset is the register offset to be written Data is the 32-bit value to write to the register None. C-style signature: void XScuTimer_WriteReg(u32 BaseAddr, u32 RegOffset, u32 Data)
Referenced by XScuTimer_SelfTest, XScuTimer_SetPrescaler, XScuTimer_Start, XScuTimer_Stop.
XSCUTIMER_SELFTEST_VALUE