xscutimer.c
s32 XScuTimer_CfgInitialize(XScuTimer *InstancePtr, XScuTimer_Config *ConfigPtr, u32 EffectiveAddress)
Initialize a specific timer instance/driver.
This function must be called before other functions of the driver are called. InstancePtr is a pointer to the XScuTimer instance. ConfigPtr points to the XScuTimer configuration structure. EffectiveAddress is the base address for the device. It could be a virtual address if address translation is supported in the system, otherwise it is the physical address. XST_SUCCESS if initialization was successful.XST_DEVICE_IS_STARTED if the device has already been started. None.
References XScuTimer_Config::BaseAddr, XScuTimer::Config, XScuTimer::IsReady, XScuTimer::IsStarted.
Referenced by ScuTimerIntrExample, ScuTimerPolledExample.
void XScuTimer_Start(XScuTimer *InstancePtr)
Start the timer.
InstancePtr is a pointer to the XScuTimer instance. None. None.
References XScuTimer_Config::BaseAddr, XScuTimer::Config, XScuTimer::IsReady, XScuTimer::IsStarted, XSCUTIMER_CONTROL_ENABLE_MASK, XSCUTIMER_CONTROL_OFFSET, XScuTimer_ReadReg, XScuTimer_WriteReg.
Referenced by ScuTimerIntrExample, ScuTimerPolledExample.
void XScuTimer_Stop(XScuTimer *InstancePtr)
Stop the timer.
InstancePtr is a pointer to the XScuTimer instance. None. None.
References XScuTimer_Config::BaseAddr, XScuTimer::Config, XScuTimer::IsReady, XScuTimer::IsStarted, XSCUTIMER_CONTROL_ENABLE_MASK, XSCUTIMER_CONTROL_OFFSET, XScuTimer_ReadReg, XScuTimer_WriteReg.
Referenced by ScuTimerIntrExample, ScuTimerPolledExample.
void XScuTimer_SetPrescaler(XScuTimer *InstancePtr, u8 PrescalerValue)
This function sets the prescaler bits in the timer control register.
InstancePtr is a pointer to the XScuTimer instance. PrescalerValue is a 8 bit value that sets the prescaler to use. None None
References XScuTimer_Config::BaseAddr, XScuTimer::Config, XScuTimer::IsReady, XSCUTIMER_CONTROL_OFFSET, XSCUTIMER_CONTROL_PRESCALER_MASK, XScuTimer_ReadReg, XScuTimer_WriteReg.
u8 XScuTimer_GetPrescaler(XScuTimer *InstancePtr)
This function returns the current prescaler value.
InstancePtr is a pointer to the XScuTimer instance. The prescaler value. None.
References XScuTimer_Config::BaseAddr, XScuTimer::Config, XScuTimer::IsReady, XSCUTIMER_CONTROL_OFFSET, XSCUTIMER_CONTROL_PRESCALER_MASK, XScuTimer_ReadReg.