xv_warp_filter.h
XV_warp_filter_WriteReg
Macro to write a 32-bit value to a register.
Referenced by XV_warp_filter_DisableAutoRestart, XV_warp_filter_EnableAutoRestart, XV_warp_filter_InterruptClear, XV_warp_filter_InterruptDisable, XV_warp_filter_InterruptEnable, XV_warp_filter_InterruptGlobalDisable, XV_warp_filter_InterruptGlobalEnable, XV_warp_filter_Set_desc_addr, XV_warp_filter_Set_maxi_read, XV_warp_filter_Set_maxi_read1, XV_warp_filter_Set_maxi_read1s, XV_warp_filter_Set_maxi_reads, XV_warp_filter_Set_maxi_write, XV_warp_filter_Set_maxi_write1, XV_warp_filter_SetFlushbit, XV_warp_filter_Start.
XV_warp_filter_ReadReg
Macro to read a 32-bit value from a register.
Referenced by XV_warp_filter_Get_desc_addr, XV_warp_filter_Get_FlushDone, XV_warp_filter_Get_maxi_read, XV_warp_filter_Get_maxi_read1, XV_warp_filter_Get_maxi_read1s, XV_warp_filter_Get_maxi_reads, XV_warp_filter_Get_maxi_write, XV_warp_filter_Get_maxi_write1, XV_warp_filter_InterruptDisable, XV_warp_filter_InterruptEnable, XV_warp_filter_InterruptGetEnabled, XV_warp_filter_InterruptGetStatus, XV_warp_filter_IsDone, XV_warp_filter_IsIdle, XV_warp_filter_IsReady, XV_warp_filter_SetFlushbit, XV_warp_filter_Start.
typedef void(* XV_warp_filter_Callback)(void *CallbackRef))(void *CallbackRef)
Callback function type for frame done event.
typedef u32 word_type
Word type definition for register access.
s32 XV_warp_filter_Initialize(XV_warp_filter *InstancePtr, UINTPTR BaseAddress)
Initializes the Warp Filter instance using base address.
This function looks up the configuration for the specified base address and initializes the instance using the configuration found. InstancePtr Pointer to the XV_warp_filter instance to initialize. BaseAddress Base address of the Warp Filter control interface. XST_SUCCESS if initialization is successful. XST_DEVICE_NOT_FOUND if the base address is not found. This function is only available when SDT is defined. InstancePtr must not be NULL.
References XV_warp_filter::IsReady, XV_warp_filter_CfgInitialize, XV_warp_filter_LookupConfig.
XV_warp_filter_Config* XV_warp_filter_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the base address.
This function searches the configuration table for a device matching the specified base address and returns a pointer to its configuration structure. If BaseAddress is 0, returns the first configuration entry. BaseAddress Base address of the device to search for, or 0 for first entry. Pointer to the configuration structure if found, NULL otherwise. This function is only available when SDT is defined.
References XV_warp_filter_Config::Name.
Referenced by XV_warp_filter_Initialize.
s32 XV_warp_filter_CfgInitialize(XV_warp_filter *InstancePtr, XV_warp_filter_Config *ConfigPtr)
Initializes the Warp Filter driver instance.
This function initializes the driver instance with the provided configuration structure. It sets up the base address, marks the instance as ready, and initializes descriptor-related fields. InstancePtr Pointer to the XV_warp_filter instance. ConfigPtr Pointer to the configuration structure. XST_SUCCESS indicating successful initialization. This function is only available when not compiling for Linux. Both InstancePtr and ConfigPtr must not be NULL.
References XV_warp_filter::config, XV_warp_filter_Config::Control_BaseAddress, XV_warp_filter::Control_BaseAddress, XV_warp_filter::IsReady, XV_warp_filter::NumDescriptors, XV_warp_filter::WarpFilterDesc_BaseAddr.
Referenced by XV_warp_filter_Initialize.
void XV_warp_filter_Start(XV_warp_filter *InstancePtr)
Starts the Warp Filter core.
This function triggers the start of the Warp Filter processing by setting the AP_START bit in the control register while preserving the auto-restart bit. InstancePtr Pointer to the XV_warp_filter instance. None InstancePtr must not be NULL and must be in the ready state.
References XV_warp_filter::Control_BaseAddress, XV_warp_filter::IsReady, XV_WARP_FILTER_CONTROL_ADDR_AP_CTRL, XV_warp_filter_ReadReg, XV_warp_filter_WriteReg.
Referenced by XVWarpFilter_Start.
u32 XV_warp_filter_IsDone(XV_warp_filter *InstancePtr)
Checks if the Warp Filter core has finished processing.
This function reads the AP_DONE bit from the control register to determine if the core has completed its current operation. InstancePtr Pointer to the XV_warp_filter instance. 1 if processing is done, 0 otherwise. InstancePtr must not be NULL and must be in the ready state.
References XV_warp_filter::Control_BaseAddress, XV_warp_filter::IsReady, XV_WARP_FILTER_CONTROL_ADDR_AP_CTRL, XV_warp_filter_ReadReg.
u32 XV_warp_filter_IsIdle(XV_warp_filter *InstancePtr)
Checks if the Warp Filter core is idle.
This function reads the AP_IDLE bit from the control register to determine if the core is currently idle. InstancePtr Pointer to the XV_warp_filter instance. 1 if the core is idle, 0 otherwise. InstancePtr must not be NULL and must be in the ready state.
References XV_warp_filter::Control_BaseAddress, XV_warp_filter::IsReady, XV_WARP_FILTER_CONTROL_ADDR_AP_CTRL, XV_warp_filter_ReadReg.
u32 XV_warp_filter_IsReady(XV_warp_filter *InstancePtr)
Checks if the Warp Filter core is ready for next input.
This function checks the AP_START bit to determine if the core is ready to accept new input data. InstancePtr Pointer to the XV_warp_filter instance. 1 if the core is ready for next input, 0 otherwise. InstancePtr must not be NULL and must be in the ready state.
References XV_warp_filter::Control_BaseAddress, XV_warp_filter::IsReady, XV_WARP_FILTER_CONTROL_ADDR_AP_CTRL, XV_warp_filter_ReadReg.
void XV_warp_filter_EnableAutoRestart(XV_warp_filter *InstancePtr)
Enables auto-restart mode for the Warp Filter core.
This function enables the auto-restart feature by setting the appropriate bit in the control register, allowing the core to automatically restart after completing each frame. InstancePtr Pointer to the XV_warp_filter instance. None InstancePtr must not be NULL and must be in the ready state.
References XV_warp_filter::Control_BaseAddress, XV_warp_filter::IsReady, XV_WARP_FILTER_CONTROL_ADDR_AP_CTRL, XV_warp_filter_WriteReg.
void XV_warp_filter_DisableAutoRestart(XV_warp_filter *InstancePtr)
Disables auto-restart mode for the Warp Filter core.
This function disables the auto-restart feature by clearing the control register, requiring manual start for each frame. InstancePtr Pointer to the XV_warp_filter instance. None InstancePtr must not be NULL and must be in the ready state.
References XV_warp_filter::Control_BaseAddress, XV_warp_filter::IsReady, XV_WARP_FILTER_CONTROL_ADDR_AP_CTRL, XV_warp_filter_WriteReg.
Referenced by XVWarpFilter_Stop.
void XV_warp_filter_SetFlushbit(XV_warp_filter *InstancePtr)
Sets the flush bit to flush the Warp Filter pipeline.
This function sets the flush bit in the control register to initiate flushing of the internal pipeline. This is typically used to clear pending operations. InstancePtr Pointer to the XV_warp_filter instance. None InstancePtr must not be NULL and must be in the ready state.
References AP_CTRL_BITS_FLUSH_BIT, XV_warp_filter::Control_BaseAddress, XV_warp_filter::IsReady, XV_WARP_FILTER_CONTROL_ADDR_AP_CTRL, XV_warp_filter_ReadReg, XV_warp_filter_WriteReg.
Referenced by XVWarpFilter_Stop.
u32 XV_warp_filter_Get_FlushDone(XV_warp_filter *InstancePtr)
Gets the flush done status.
This function reads the flush done status bit from the control register to determine if the flush operation has completed. InstancePtr Pointer to the XV_warp_filter instance. Flush done status bit value (non-zero if flush is complete). InstancePtr must not be NULL and must be in the ready state.
References AP_CTRL_BITS_FLUSH_STATUSBIT, XV_warp_filter::Control_BaseAddress, XV_warp_filter::IsReady, XV_WARP_FILTER_CONTROL_ADDR_AP_CTRL, XV_warp_filter_ReadReg.
Referenced by XVWarpFilter_Stop.
void XV_warp_filter_Set_desc_addr(XV_warp_filter *InstancePtr, u64 Data)
Sets the descriptor address for the Warp Filter.
This function writes the 64-bit descriptor address to the control registers, specifying the location of the descriptor structure in memory. InstancePtr Pointer to the XV_warp_filter instance. Data 64-bit descriptor address. None InstancePtr must not be NULL and must be in the ready state.
References XV_warp_filter::Control_BaseAddress, XV_warp_filter::IsReady, XV_WARP_FILTER_CONTROL_ADDR_DESC_ADDR_DATA, XV_warp_filter_WriteReg.
Referenced by XVWarpFilter_ProgramDescriptor, XVWarpFilter_update_dst_frame_addr, XVWarpFilter_update_src_frame_addr.
u64 XV_warp_filter_Get_desc_addr(XV_warp_filter *InstancePtr)
Gets the descriptor address from the Warp Filter.
This function reads the 64-bit descriptor address from the control registers. InstancePtr Pointer to the XV_warp_filter instance. 64-bit descriptor address. InstancePtr must not be NULL and must be in the ready state.
References XV_warp_filter::Control_BaseAddress, XV_warp_filter::IsReady, XV_WARP_FILTER_CONTROL_ADDR_DESC_ADDR_DATA, XV_warp_filter_ReadReg.
void XV_warp_filter_Set_maxi_read(XV_warp_filter *InstancePtr, u64 Data)
Sets the AXI master read interface base address.
This function writes the 64-bit base address for the AXI master read interface to the control registers. InstancePtr Pointer to the XV_warp_filter instance. Data 64-bit base address for AXI master read. None InstancePtr must not be NULL and must be in the ready state.
References XV_warp_filter::Control_BaseAddress, XV_warp_filter::IsReady, XV_WARP_FILTER_CONTROL_ADDR_MAXI_READ_DATA, XV_warp_filter_WriteReg.
u64 XV_warp_filter_Get_maxi_read(XV_warp_filter *InstancePtr)
Gets the AXI master read interface base address.
This function reads the 64-bit base address for the AXI master read interface from the control registers. InstancePtr Pointer to the XV_warp_filter instance. 64-bit base address for AXI master read. InstancePtr must not be NULL and must be in the ready state.
References XV_warp_filter::Control_BaseAddress, XV_warp_filter::IsReady, XV_WARP_FILTER_CONTROL_ADDR_MAXI_READ_DATA, XV_warp_filter_ReadReg.
void XV_warp_filter_Set_maxi_reads(XV_warp_filter *InstancePtr, u64 Data)
Sets the AXI master read interface address for segment table.
This function writes the 64-bit address for reading segment table data via the AXI master interface. InstancePtr Pointer to the XV_warp_filter instance. Data 64-bit address for segment table read. None InstancePtr must not be NULL and must be in the ready state.
References XV_warp_filter::Control_BaseAddress, XV_warp_filter::IsReady, XV_WARP_FILTER_CONTROL_ADDR_MAXI_READS_DATA, XV_warp_filter_WriteReg.
u64 XV_warp_filter_Get_maxi_reads(XV_warp_filter *InstancePtr)
Gets the AXI master read interface address for segment table.
This function reads the 64-bit address for reading segment table data from the control registers. InstancePtr Pointer to the XV_warp_filter instance. 64-bit address for segment table read. InstancePtr must not be NULL and must be in the ready state.
References XV_warp_filter::Control_BaseAddress, XV_warp_filter::IsReady, XV_WARP_FILTER_CONTROL_ADDR_MAXI_READS_DATA, XV_warp_filter_ReadReg.
void XV_warp_filter_Set_maxi_write(XV_warp_filter *InstancePtr, u64 Data)
Sets the AXI master write interface base address.
This function writes the 64-bit base address for the AXI master write interface to the control registers. InstancePtr Pointer to the XV_warp_filter instance. Data 64-bit base address for AXI master write. None InstancePtr must not be NULL and must be in the ready state.
References XV_warp_filter::Control_BaseAddress, XV_warp_filter::IsReady, XV_WARP_FILTER_CONTROL_ADDR_MAXI_WRITE_DATA, XV_warp_filter_WriteReg.
u64 XV_warp_filter_Get_maxi_write(XV_warp_filter *InstancePtr)
Gets the AXI master write interface base address.
This function reads the 64-bit base address for the AXI master write interface from the control registers. InstancePtr Pointer to the XV_warp_filter instance. 64-bit base address for AXI master write. InstancePtr must not be NULL and must be in the ready state.
References XV_warp_filter::Control_BaseAddress, XV_warp_filter::IsReady, XV_WARP_FILTER_CONTROL_ADDR_MAXI_WRITE_DATA, XV_warp_filter_ReadReg.
void XV_warp_filter_Set_maxi_read1(XV_warp_filter *InstancePtr, u64 Data)
Sets the secondary AXI master read interface base address.
This function writes the 64-bit base address for the secondary AXI master read interface (used for multi-plane formats) to the control registers. InstancePtr Pointer to the XV_warp_filter instance. Data 64-bit base address for secondary AXI master read. None InstancePtr must not be NULL and must be in the ready state.
References XV_warp_filter::Control_BaseAddress, XV_warp_filter::IsReady, XV_WARP_FILTER_CONTROL_ADDR_MAXI_READ1_DATA, XV_warp_filter_WriteReg.
u64 XV_warp_filter_Get_maxi_read1(XV_warp_filter *InstancePtr)
Gets the secondary AXI master read interface base address.
This function reads the 64-bit base address for the secondary AXI master read interface from the control registers. InstancePtr Pointer to the XV_warp_filter instance. 64-bit base address for secondary AXI master read. InstancePtr must not be NULL and must be in the ready state.
References XV_warp_filter::Control_BaseAddress, XV_warp_filter::IsReady, XV_WARP_FILTER_CONTROL_ADDR_MAXI_READ1_DATA, XV_warp_filter_ReadReg.
void XV_warp_filter_Set_maxi_read1s(XV_warp_filter *InstancePtr, u64 Data)
Sets the secondary segment table read address.
This function writes the 64-bit address for reading secondary segment table data via the AXI master interface. InstancePtr Pointer to the XV_warp_filter instance. Data 64-bit address for secondary segment table read. None InstancePtr must not be NULL and must be in the ready state.
References XV_warp_filter::Control_BaseAddress, XV_warp_filter::IsReady, XV_WARP_FILTER_CONTROL_ADDR_MAXI_READ1S_DATA, XV_warp_filter_WriteReg.
u64 XV_warp_filter_Get_maxi_read1s(XV_warp_filter *InstancePtr)
Gets the secondary segment table read address.
This function reads the 64-bit address for reading secondary segment table data from the control registers. InstancePtr Pointer to the XV_warp_filter instance. 64-bit address for secondary segment table read. InstancePtr must not be NULL and must be in the ready state.
References XV_warp_filter::Control_BaseAddress, XV_warp_filter::IsReady, XV_WARP_FILTER_CONTROL_ADDR_MAXI_READ1S_DATA, XV_warp_filter_ReadReg.
void XV_warp_filter_Set_maxi_write1(XV_warp_filter *InstancePtr, u64 Data)
Sets the secondary AXI master write interface base address.
This function writes the 64-bit base address for the secondary AXI master write interface (used for multi-plane formats) to the control registers. InstancePtr Pointer to the XV_warp_filter instance. Data 64-bit base address for secondary AXI master write. None InstancePtr must not be NULL and must be in the ready state.
References XV_warp_filter::Control_BaseAddress, XV_warp_filter::IsReady, XV_WARP_FILTER_CONTROL_ADDR_MAXI_WRITE1_DATA, XV_warp_filter_WriteReg.
u64 XV_warp_filter_Get_maxi_write1(XV_warp_filter *InstancePtr)
Gets the secondary AXI master write interface base address.
This function reads the 64-bit base address for the secondary AXI master write interface from the control registers. InstancePtr Pointer to the XV_warp_filter instance. 64-bit base address for secondary AXI master write. InstancePtr must not be NULL and must be in the ready state.
References XV_warp_filter::Control_BaseAddress, XV_warp_filter::IsReady, XV_WARP_FILTER_CONTROL_ADDR_MAXI_WRITE1_DATA, XV_warp_filter_ReadReg.
void XV_warp_filter_InterruptGlobalEnable(XV_warp_filter *InstancePtr)
Enables global interrupts for the Warp Filter.
This function enables the global interrupt enable (GIE) bit, allowing the core to generate interrupts. InstancePtr Pointer to the XV_warp_filter instance. None InstancePtr must not be NULL and must be in the ready state.
References XV_warp_filter::Control_BaseAddress, XV_warp_filter::IsReady, XV_WARP_FILTER_CONTROL_ADDR_GIE, XV_warp_filter_WriteReg.
Referenced by XVWarpFilter_InterruptEnable.
void XV_warp_filter_InterruptGlobalDisable(XV_warp_filter *InstancePtr)
Disables global interrupts for the Warp Filter.
This function disables the global interrupt enable (GIE) bit, preventing the core from generating interrupts. InstancePtr Pointer to the XV_warp_filter instance. None InstancePtr must not be NULL and must be in the ready state.
References XV_warp_filter::Control_BaseAddress, XV_warp_filter::IsReady, XV_WARP_FILTER_CONTROL_ADDR_GIE, XV_warp_filter_WriteReg.
Referenced by XVWarpFilter_InterruptDisable.
void XV_warp_filter_InterruptEnable(XV_warp_filter *InstancePtr, u32 Mask)
Enables specific interrupts for the Warp Filter.
This function enables the interrupt sources specified by the Mask parameter in the interrupt enable register. InstancePtr Pointer to the XV_warp_filter instance. Mask Bit mask of interrupts to enable. None InstancePtr must not be NULL and must be in the ready state.
References XV_warp_filter::Control_BaseAddress, XV_warp_filter::IsReady, XV_WARP_FILTER_CONTROL_ADDR_IER, XV_warp_filter_ReadReg, XV_warp_filter_WriteReg.
Referenced by XVWarpFilter_InterruptEnable.
void XV_warp_filter_InterruptDisable(XV_warp_filter *InstancePtr, u32 Mask)
Disables specific interrupts for the Warp Filter.
This function disables the interrupt sources specified by the Mask parameter in the interrupt enable register. InstancePtr Pointer to the XV_warp_filter instance. Mask Bit mask of interrupts to disable. None InstancePtr must not be NULL and must be in the ready state.
References XV_warp_filter::Control_BaseAddress, XV_warp_filter::IsReady, XV_WARP_FILTER_CONTROL_ADDR_IER, XV_warp_filter_ReadReg, XV_warp_filter_WriteReg.
Referenced by XVWarpFilter_InterruptDisable.
void XV_warp_filter_InterruptClear(XV_warp_filter *InstancePtr, u32 Mask)
Clears pending interrupts for the Warp Filter.
This function clears the interrupt status bits specified by the Mask parameter by writing to the interrupt status register. InstancePtr Pointer to the XV_warp_filter instance. Mask Bit mask of interrupts to clear. None InstancePtr must not be NULL and must be in the ready state.
References XV_warp_filter::Control_BaseAddress, XV_warp_filter::IsReady, XV_WARP_FILTER_CONTROL_ADDR_ISR, XV_warp_filter_WriteReg.
Referenced by XVWarpFilter_IntrHandler.
u32 XV_warp_filter_InterruptGetEnabled(XV_warp_filter *InstancePtr)
Gets the enabled interrupt mask.
This function reads the interrupt enable register to determine which interrupt sources are currently enabled. InstancePtr Pointer to the XV_warp_filter instance. Bit mask of enabled interrupts. InstancePtr must not be NULL and must be in the ready state.
References XV_warp_filter::Control_BaseAddress, XV_warp_filter::IsReady, XV_WARP_FILTER_CONTROL_ADDR_IER, XV_warp_filter_ReadReg.
u32 XV_warp_filter_InterruptGetStatus(XV_warp_filter *InstancePtr)
Gets the pending interrupt status.
This function reads the interrupt status register to determine which interrupts are currently pending. InstancePtr Pointer to the XV_warp_filter instance. Bit mask of pending interrupts. InstancePtr must not be NULL and must be in the ready state.
References XV_warp_filter::Control_BaseAddress, XV_warp_filter::IsReady, XV_WARP_FILTER_CONTROL_ADDR_ISR, XV_warp_filter_ReadReg.
Referenced by XVWarpFilter_IntrHandler.