diskio.h
USE_WRITE
1: Enable disk_write function
USE_IOCTL
1: Enable disk_ioctl function
STA_NOINIT
Drive not initialized.
STA_NODISK
No medium in the drive.
STA_PROTECT
Write protected.
CTRL_SYNC
Complete pending write process (needed at FF_FS_READONLY == 0)
GET_SECTOR_COUNT
Get media size (needed at FF_USE_MKFS == 1)
GET_SECTOR_SIZE
Get sector size (needed at FF_MAX_SS != FF_MIN_SS)
GET_BLOCK_SIZE
Get erase block size (needed at FF_USE_MKFS == 1)
CTRL_TRIM
Inform device that the data on the block of sectors is no longer used (needed at FF_USE_TRIM == 1)
CTRL_POWER
Get/Set power status.
CTRL_LOCK
Lock/Unlock media removal.
CTRL_EJECT
Eject media.
CTRL_FORMAT
Create physical format on the media.
MMC_GET_TYPE
Get card type.
MMC_GET_CSD
Get CSD.
MMC_GET_CID
Get CID.
MMC_GET_OCR
Get OCR.
MMC_GET_SDSTAT
Get SD status.
ISDIO_READ
Read data form SD iSDIO register.
ISDIO_WRITE
Write data to SD iSDIO register.
ISDIO_MRITE
Masked write data to SD iSDIO register.
ATA_GET_REV
Get F/W revision.
ATA_GET_MODEL
Get model name.
ATA_GET_SN
Get serial number.
DRESULT
0: Successful
typedef BYTE DSTATUS
DSTATUS disk_initialize(BYTE pdrv)
Initializes the drive.
In case of SD, it initializes the host controller and the card. This function also selects additional settings such as bus width, speed and block size. pdrv - Drive number s - which contains an OR of the following information STA_NODISK Disk is not present STA_NOINIT Drive not initialized STA_PROTECT Drive is write protected 0 or only STA_PROTECT both indicate successful initialization.
References disk_status, XSDPS_NUM_INSTANCES.
DSTATUS disk_status(BYTE pdrv)
Gets the status of the disk.
In case of SD, it checks whether card is present or not. pdrv - Drive number 0 Status ok STA_NOINIT Drive not initialized STA_NODISK No medium in the drive STA_PROTECT Write protected In case Card detect signal is not connected, this function will not be able to check if card is present.
References XSDPS_NUM_INSTANCES.
Referenced by disk_initialize, disk_read, disk_ioctl, disk_write.
DRESULT disk_read(BYTE pdrv, BYTE *buff, LBA_t sector, UINT count)
Reads the drive In case of SD, it reads the SD card using ADMA2 in polled mode.
pdrv - Drive number buff - Pointer to the data buffer to store read data sector - Start sector number count - Sector count RES_OK Read successful STA_NOINIT Drive not initialized RES_ERROR Read not successful
References disk_status, XSDPS_NUM_INSTANCES, XUFSPSXC_START_INDEX.
DRESULT disk_write(BYTE pdrv, const BYTE *buff, LBA_t sector, UINT count)
Reads the drive In case of SD, it reads the SD card using ADMA2 in polled mode.
pdrv - Drive number buff - Pointer to the data to be written sector - Sector address count - Sector count RES_OK Read successful STA_NOINIT Drive not initialized RES_ERROR Read not successful
References disk_status, XSDPS_NUM_INSTANCES, XUFSPSXC_START_INDEX.
DRESULT disk_ioctl(BYTE pdrv, BYTE cmd, void *buff)
List specific features and do miscellaneous functions on device.
In case of SD, it control device specific features and miscellaneous functions other than generic read/write. pdrv - Drive number cmd - Command code buff - Pointer to the parameter depends on the command code. RES_OK Command successful RES_PARERR Command is invalid RES_NOTRDY Drive not initialized RES_ERROR Error occurred
References disk_status, XSDPS_NUM_INSTANCES, XUFSPSXC_START_INDEX.