diskio.c
XSDPS_NUM_INSTANCES
Number of SD instances.
Referenced by disk_initialize, disk_ioctl, disk_read, disk_status, disk_write.
XUFSPSXC_START_INDEX
Start index of UFS instances.
Referenced by disk_ioctl, disk_read, disk_write.
DSTATUS Stat[XSDPS_NUM_INSTANCES][XSDPS_NUM_INSTANCES]
DSTATUS disk_status(BYTE pdrv)
Gets the status of the disk.
In case of SD, it checks whether card is present or not. pdrv - Drive number 0 Status ok STA_NOINIT Drive not initialized STA_NODISK No medium in the drive STA_PROTECT Write protected In case Card detect signal is not connected, this function will not be able to check if card is present.
References XSDPS_NUM_INSTANCES.
Referenced by disk_initialize, disk_ioctl, disk_read, disk_write.
DSTATUS disk_initialize(BYTE pdrv)
Initializes the drive.
In case of SD, it initializes the host controller and the card. This function also selects additional settings such as bus width, speed and block size. pdrv - Drive number s - which contains an OR of the following information STA_NODISK Disk is not present STA_NOINIT Drive not initialized STA_PROTECT Drive is write protected 0 or only STA_PROTECT both indicate successful initialization.
References disk_status, XSDPS_NUM_INSTANCES.
DRESULT disk_read(BYTE pdrv, BYTE *buff, LBA_t sector, UINT count)
Reads the drive In case of SD, it reads the SD card using ADMA2 in polled mode.
pdrv - Drive number buff - Pointer to the data buffer to store read data sector - Start sector number count - Sector count RES_OK Read successful STA_NOINIT Drive not initialized RES_ERROR Read not successful
References disk_status, XSDPS_NUM_INSTANCES, XUFSPSXC_START_INDEX.
DRESULT disk_ioctl(BYTE pdrv, BYTE cmd, void *buff)
List specific features and do miscellaneous functions on device.
In case of SD, it control device specific features and miscellaneous functions other than generic read/write. pdrv - Drive number cmd - Command code buff - Pointer to the parameter depends on the command code. RES_OK Command successful RES_PARERR Command is invalid RES_NOTRDY Drive not initialized RES_ERROR Error occurred
References disk_status, XSDPS_NUM_INSTANCES, XUFSPSXC_START_INDEX.
DWORD get_fattime(void)
This function is User Provided Timer Function for FatFs module.
DWORD None
DRESULT disk_write(BYTE pdrv, const BYTE *buff, LBA_t sector, UINT count)
Reads the drive In case of SD, it reads the SD card using ADMA2 in polled mode.
pdrv - Drive number buff - Pointer to the data to be written sector - Sector address count - Sector count RES_OK Read successful STA_NOINIT Drive not initialized RES_ERROR Read not successful
References disk_status, XSDPS_NUM_INSTANCES, XUFSPSXC_START_INDEX.