xhwicap_sinit.c
XHwIcap_Config XHwIcap_ConfigTable[][]
The configuration table for opb_hwicap devices.
XHwIcap_Config * XHwIcap_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID.
A table contains the configuration info for each device in the system. DeviceId contains the ID of the device for which the device configuration pointer is to be returned. A pointer to the configuration found.NULL if the specified device ID was not found. None.
Referenced by HwIcapIntrExample, HwIcapReadConfigRegExample, HwIcapReadFramePolledExample, HwIcapTestAppExample.