xhwicap.h
XHWICAP_H_
DEVICE_TYPE_7SERIES
DEVICE_TYPE_ULTRA
DEVICE_TYPE_ULTRA_PLUS
NUM_7SERIES_IDCODES
NUM_ULTRA_SERIES_IDCODES
NUM_ULTRA_PLUS_SERIES_IDCODES
PCAP_CR_OFFSET
PCAP CR Register.
Referenced by XHwIcap_CfgInitialize.
XHwIcap_FifoWrite
Write data to the Write FIFO.
InstancePtr is a pointer to the XHwIcap instance. Data is the 32-bit value to be written to the FIFO. None. C-style Signature: void XHwIcap_FifoWrite(XHwIcap *InstancePtr, u32 Data);
Referenced by XHwIcap_DeviceWrite, XHwIcap_IntrHandler.
XHwIcap_FifoRead
Read data from the Read FIFO.
InstancePtr is a pointer to the XHwIcap instance. The 32-bit Data read from the FIFO. C-style Signature: u32 XHwIcap_FifoRead(XHwIcap *InstancePtr);
Referenced by XHwIcap_DeviceRead.
XHwIcap_SetSizeReg
Set the number of words to be read from the Icap in the Size register.
The Size Register holds the number of 32 bit words to transfer from the the Icap to the Read FIFO of the HwIcap device. InstancePtr is a pointer to the XHwIcap instance. Data is the size in words. None. C-style Signature: void XHwIcap_SetSizeReg(XHwIcap *InstancePtr, u32 Data);
Referenced by XHwIcap_DeviceRead.
XHwIcap_GetControlReg
Get the contents of the Control register.
InstancePtr is a pointer to the XHwIcap instance. A 32-bit value representing the contents of the Control register. u32 XHwIcap_GetControlReg(XHwIcap *InstancePtr);
XHwIcap_StartConfig
Set the Control Register to initiate a configuration (write) to the device.
InstancePtr is a pointer to the XHwIcap instance. None. C-style Signature: void XHwIcap_StartConfig(XHwIcap *InstancePtr);
Referenced by XHwIcap_DeviceWrite, XHwIcap_IntrHandler.
XHwIcap_StartReadBack
Set the Control Register to initiate a ReadBack from the device.
InstancePtr is a pointer to the XHwIcap instance. None. C-style Signature: void XHwIcap_StartReadBack(XHwIcap *InstancePtr);
Referenced by XHwIcap_DeviceRead.
XHwIcap_GetStatusReg
Get the contents of the status register.
InstancePtr is a pointer to the XHwIcap instance. A 32-bit value representing the contents of the status register. u32 XHwIcap_GetStatusReg(XHwIcap *InstancePtr);
XHwIcap_IsTransferDone
This macro checks if the last Read/Write of the data to the Read/Write FIFO of the HwIcap device is completed.
InstancePtr is a pointer to the XHwIcap instance. TRUE if the Read/Write to the FIFO's is completed.FALSE if the Read/Write to the FIFO's is NOT completed.. C-Style signature: int XHwIcap_IsTransferDone(XHwIcap *InstancePtr);
Referenced by XHwIcap_DeviceRead, XHwIcap_DeviceWrite.
XHwIcap_IsDeviceBusy
This macro checks if the last Read/Write to the ICAP device in the FPGA is completed.
InstancePtr is a pointer to the XHwIcap instance. TRUE if the last Read/Write(Config) to the ICAP is NOT completed.FALSE if the Read/Write(Config) to the ICAP is completed.. C-Style signature: int XHwIcap_IsDeviceBusy(XHwIcap *InstancePtr);
Referenced by XHwIcap_DeviceRead, XHwIcap_DeviceReadFrame, XHwIcap_DeviceWrite, XHwIcap_GetConfigReg.
XHwIcap_IntrGlobalEnable
This macro enables the global interrupt in the Global Interrupt Enable Register (GIER) so that the interrupt output from the HwIcap device is enabled.
Interrupts enabled using XHwIcap_IntrEnable() will not occur until the global interrupt enable bit is set by using this macro. InstancePtr is a pointer to the HwIcap instance. None. C-Style signature: void XHwIcap_IntrGlobalEnable(InstancePtr)
Referenced by XHwIcap_DeviceWrite.
XHwIcap_IntrGlobalDisable
This macro disables the global interrupt in the Global Interrupt Enable Register (GIER) so that the interrupt output from the HwIcap device is disabled.
InstancePtr is a pointer to the HwIcap instance. None. C-Style signature: void XHwIcap_IntrGlobalDisable(InstancePtr)
Referenced by XHwIcap_DeviceWrite, XHwIcap_IntrHandler, XHwIcap_SelfTest.
XHwIcap_IntrGetStatus
This macro returns the interrupt status read from Interrupt Status Register(IPISR).
Use the XHI_IPIXR_* constants defined in xhwicap_l.h to interpret the returned value. InstancePtr is a pointer to the HwIcap instance. The contents read from the Interrupt Status Register. C-Style signature: u32 XHwIcap_IntrGetStatus(InstancePtr)
Referenced by XHwIcap_DeviceWrite, XHwIcap_IntrHandler.
XHwIcap_IntrDisable
This macro disables the specified interrupts in the Interrupt Enable Register.
It is non-destructive in that the register is read and only the interrupts specified is changed. InstancePtr is a pointer to the HwIcap instance. IntrMask is the bit-mask of the interrupts to be disabled. Bit positions of 1 will be disabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XHI_IPIXR_*_MASK bits defined in xhwicap_l.h. None. Signature: void XHwIcap_IntrDisable(XHwIcap *InstancePtr, u32 IntrMask)
Referenced by XHwIcap_SelfTest.
XHwIcap_IntrEnable
This macro enables the specified interrupts in the Interrupt Enable Register.
It is non-destructive in that the register is read and only the interrupts specified is changed. InstancePtr is a pointer to the HwIcap instance. IntrMask is the bit-mask of the interrupts to be enabled. Bit positions of 1 will be enabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XHI_IPIXR_*_MASK bits defined in xhwicap_l.h. None. Signature: void XHwIcap_IntrEnable(XHwIcap *InstancePtr, u32 IntrMask)
Referenced by HwIcapIntrExample, XHwIcap_SelfTest.
XHwIcap_IntrGetEnabled
This macro returns the interrupt status read from Interrupt Enable Register(IIER).
Use the XHI_IPIXR_* constants defined in xhwicap_l.h to interpret the returned value. InstancePtr is a pointer to the HwIcap instance. The contents read from the Interrupt Enable Register. C-Style signature: u32 XHwIcap_IntrGetEnabled(InstancePtr)
Referenced by XHwIcap_SelfTest.
XHwIcap_IntrClear
This macro clears the specified interrupts in the Interrupt Status Register (IPISR).
InstancePtr is a pointer to the HwIcap instance. IntrMask contains the interrupts to be cleared. None. Signature: void XHwIcap_DisableIntr(XHwIcap *InstancePtr, u32 IntrMask)
Referenced by XHwIcap_DeviceWrite, XHwIcap_IntrHandler.
XHwIcap_GetWrFifoVacancy
This macro returns the vacancy of the Write FIFO.
This indicates the number of words that can be written to the Write FIFO before it becomes full. InstancePtr is a pointer to the HwIcap instance. The contents read from the Write FIFO Vacancy Register. C-Style signature: u32 XHwIcap_GetWrFifoVacancy(InstancePtr)
Referenced by XHwIcap_DeviceWrite, XHwIcap_IntrHandler.
XHwIcap_GetRdFifoOccupancy
This macro returns the occupancy of the Read FIFO.
InstancePtr is a pointer to the HwIcap instance. The contents read from the Read FIFO Occupancy Register. C-Style signature: u32 XHwIcap_GetRdFifoOccupancy(InstancePtr)
Referenced by XHwIcap_DeviceRead.
typedef void(* XHwIcap_StatusHandler)(void *CallBackRef, u32 StatusEvent, u32 WordCount))(void *CallBackRef, u32 StatusEvent, u32 WordCount)
The handler data type allows the user to define a callback function to handle the asynchronous processing of the HwIcap driver.
The application using this driver is expected to define a handler of this type to support interrupt driven mode. The handler executes in an interrupt context such that minimal processing should be performed. CallBackRef is a callback reference passed in by the application layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. Its type is unimportant to the driver component, so it is a void pointer. StatusEvent indicates one or more status events that occurred. See the XHwIcap_SetInterruptHandler for details on the status events that can be passed in the callback. WordCount indicates how many words of data were successfully transferred. This may be less than the number of words requested if there was an error.
int XHwIcap_CfgInitialize(XHwIcap *InstancePtr, XHwIcap_Config *ConfigPtr, UINTPTR EffectiveAddr)
This function initializes a specific XHwIcap instance.
The IDCODE is read from the FPGA and based on the IDCODE the information about the resources in the FPGA is filled in the instance structure.The HwIcap device will be in put in a reset state before exiting this function. InstancePtr is a pointer to the XHwIcap instance. ConfigPtr points to the XHwIcap device configuration structure. EffectiveAddr is the device base address in the virtual memory address space. If the address translation is not used then the physical address is passed. Unexpected errors may occur if the address mapping is changed after this function is invoked. XST_SUCCESS else XST_FAILURE None.
References XHwIcap_Config::BaseAddress, XHwIcap::BytesPerFrame, XHwIcap::DeviceFamily, XHwIcap::HwIcapConfig, XHwIcap_Config::IcapWidth, XHwIcap_Config::IsLiteMode, XHwIcap::IsPolled, XHwIcap::IsReady, XHwIcap::IsTransferInProgress, PCAP_CR_OFFSET, XHwIcap::StatusHandler, XHwIcap::WordsPerFrame, XHwIcap_CommandDesync, XHwIcap_GetConfigReg, XHwIcap_Reset.
Referenced by HwIcapIntrExample, HwIcapReadConfigRegExample, HwIcapReadFramePolledExample, HwIcapTestAppExample.
int XHwIcap_DeviceWrite(XHwIcap *InstancePtr, u32 *FrameBuffer, u32 NumWords)
This function writes the given user data to the Write FIFO in both the polled mode and the interrupt mode and starts the transfer of the data to the ICAP device.
In the polled mode, this function will write the specified number of words into the FIFO before returning.In the interrupt mode, this function will write the words up to the size of the Write FIFO and starts the transfer, then subsequent transfer of the data is performed by the interrupt service routine until the entire buffer has been transferred. The status callback function is called when the entire buffer has been sent. In order to use interrupts, it is necessary for the user to connect the driver interrupt handler, XHwIcap_IntrHandler(), to the interrupt system of the application and enable the interrupts associated with the Write FIFO. The user has to enable the interrupts each time this function is called using the XHwIcap_IntrEnable macro. InstancePtr is a pointer to the XHwIcap instance. FrameBuffer is a pointer to the data to be written to the ICAP device. NumWords is the number of words (16 bit for S6 and 32 bit for all other devices)to write to the ICAP device. XST_SUCCESS or XST_FAILURE This function is a blocking for the polled mode of operation and is non-blocking for the interrupt mode of operation. Use the function XHwIcap_DeviceWriteFrame for writing a frame of data to the ICAP device.
References XHwIcap_Config::BaseAddress, XHwIcap::HwIcapConfig, XHwIcap_Config::IcapWidth, XHwIcap::IsPolled, XHwIcap::IsReady, XHwIcap::IsTransferInProgress, XHwIcap::RemainingWords, XHwIcap::RequestedWords, XHI_CR_OFFSET, XHI_CR_WRITE_MASK, XHwIcap_FifoWrite, XHwIcap_GetWrFifoVacancy, XHwIcap_IntrClear, XHwIcap_IntrGetStatus, XHwIcap_IntrGlobalDisable, XHwIcap_IntrGlobalEnable, XHwIcap_IsDeviceBusy, XHwIcap_IsTransferDone, XHwIcap_ReadReg, XHwIcap_StartConfig.
Referenced by HwIcapIntrExample, XHwIcap_CommandCapture, XHwIcap_CommandDesync, XHwIcap_DeviceReadFrame, XHwIcap_DeviceWriteFrame, XHwIcap_GetConfigReg.
int XHwIcap_DeviceRead(XHwIcap *InstancePtr, u32 *FrameBuffer, u32 NumWords)
This function reads the specified number of words from the ICAP device in the polled mode.
Interrupt mode is not supported in reading data from the ICAP device. InstancePtr is a pointer to the XHwIcap instance. FrameBuffer is a pointer to the memory where the frame read from the ICAP device is stored. NumWords is the number of words (16 bit for S6 and 32 bit for all other devices) to write to the ICAP device. XST_SUCCESS if the specified number of words have been read from the ICAP deviceXST_FAILURE if the device is busy with the last Read/Write or if the requested number of words have not been read from the ICAP device, or there is a timeout. This is a blocking function.
References XHwIcap_Config::BaseAddress, XHwIcap::HwIcapConfig, XHwIcap_Config::IcapWidth, XHwIcap::IsReady, XHwIcap::IsTransferInProgress, XHwIcap::RemainingWords, XHwIcap::RequestedWords, XHI_CR_OFFSET, XHI_CR_READ_MASK, XHwIcap_FifoRead, XHwIcap_GetRdFifoOccupancy, XHwIcap_IsDeviceBusy, XHwIcap_IsTransferDone, XHwIcap_ReadReg, XHwIcap_SetSizeReg, XHwIcap_StartReadBack.
Referenced by XHwIcap_DeviceReadFrame, XHwIcap_GetConfigReg.
void XHwIcap_Reset(XHwIcap *InstancePtr)
This function forces the software reset of the complete HWICAP device.
All the registers will return to the default value and the FIFO is also flushed as a part of this software reset. InstancePtr is a pointer to the XHwIcap instance. None. None.
References XHwIcap_Config::BaseAddress, XHwIcap::HwIcapConfig, XHwIcap::IsReady, XHI_CR_OFFSET, XHI_CR_SW_RESET_MASK, XHwIcap_ReadReg, XHwIcap_WriteReg.
Referenced by XHwIcap_CfgInitialize.
void XHwIcap_FlushFifo(XHwIcap *InstancePtr)
This function flushes the FIFOs in the device.
InstancePtr is a pointer to the XHwIcap instance. None. None.
References XHwIcap_Config::BaseAddress, XHwIcap::HwIcapConfig, XHwIcap::IsReady, XHI_CR_FIFO_CLR_MASK, XHI_CR_OFFSET, XHwIcap_ReadReg, XHwIcap_WriteReg.
void XHwIcap_Abort(XHwIcap *InstancePtr)
This function initiates the Abort Sequence by setting the Abort bit in the control register.
InstancePtr is a pointer to the XHwIcap instance. None. None.
References XHwIcap_Config::BaseAddress, XHwIcap::HwIcapConfig, XHwIcap::IsReady, XHI_CR_OFFSET, XHI_CR_SW_ABORT_MASK, XHwIcap_ReadReg, XHwIcap_WriteReg.
XHwIcap_Config * XHwIcap_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID.
A table contains the configuration info for each device in the system. DeviceId contains the ID of the device for which the device configuration pointer is to be returned. A pointer to the configuration found.NULL if the specified device ID was not found. None.
Referenced by HwIcapIntrExample, HwIcapReadConfigRegExample, HwIcapReadFramePolledExample, HwIcapTestAppExample.
int XHwIcap_CommandDesync(XHwIcap *InstancePtr)
Sends a DESYNC command to the ICAP port.
InstancePtr - a pointer to the XHwIcap instance to be worked on XST_SUCCESS else XST_FAILURE None.
References XHwIcap::IsReady, XHwIcap_DeviceWrite, XHwIcap_Type1Write.
Referenced by XHwIcap_CfgInitialize, XHwIcap_DeviceReadFrame, XHwIcap_DeviceWriteFrame.
int XHwIcap_CommandCapture(XHwIcap *InstancePtr)
Sends a CAPTURE command to the ICAP port.
This command captures all of the flip flop states so they will be available during readback. One can use this command instead of enabling the CAPTURE block in the design. InstancePtr is a pointer to the XHwIcap instance. XST_SUCCESS or XST_FAILURE None.
References XHwIcap::IsReady, XHwIcap_DeviceWrite, XHwIcap_Type1Write.
u32 XHwIcap_GetConfigReg(XHwIcap *InstancePtr, u32 ConfigReg, u32 *RegData)
This function returns the value of the specified configuration register.
InstancePtr is a pointer to the XHwIcap instance. ConfigReg is a constant which represents the configuration register value to be returned. Constants specified in xhwicap_i.h. Examples: XHI_IDCODE, XHI_FLR. RegData is the value of the specified configuration register. XST_SUCCESS or XST_FAILURE This is a blocking call.
References XHwIcap_Config::BaseAddress, XHwIcap::HwIcapConfig, XHwIcap::IsReady, XHI_CR_OFFSET, XHI_CR_WRITE_MASK, XHI_SR_EOS_MASK, XHI_SR_OFFSET, XHwIcap_DeviceRead, XHwIcap_DeviceWrite, XHwIcap_IsDeviceBusy, XHwIcap_ReadReg, XHwIcap_Type1Read.
Referenced by HwIcapReadConfigRegExample, HwIcapTestAppExample, XHwIcap_CfgInitialize.
int XHwIcap_SelfTest(XHwIcap *InstancePtr)
Run a self-test on the driver/device.
The test Writes to the Interrupt Enable Register and reads it back for comparison. InstancePtr is a pointer to the XHwIcap instance. XST_SUCCESS if the value read from the register is the same as the value written.XST_FAILURE otherwise None.
References XHwIcap_Config::BaseAddress, XHwIcap::HwIcapConfig, XHwIcap::IsReady, XHI_GIER_OFFSET, XHI_IPIXR_ALL_MASK, XHI_IPIXR_RDP_MASK, XHI_IPIXR_WEMPTY_MASK, XHwIcap_IntrDisable, XHwIcap_IntrEnable, XHwIcap_IntrGetEnabled, XHwIcap_IntrGlobalDisable, XHwIcap_ReadReg, XHwIcap_WriteReg.
Referenced by HwIcapIntrExample, HwIcapReadConfigRegExample, HwIcapReadFramePolledExample, HwIcapTestAppExample.
void XHwIcap_IntrHandler(void *InstancePtr)
The interrupt handler for HwIcap interrupts.
This function must be connected by the user to an interrupt source. InstancePtr is a pointer to the XHwIcap instance. None. The interrupts are being used only while writing data to the ICAP device. The reading of the data from the ICAP device is done in polled mode. In a worst case scenario the interrupt handler can be busy writing large amount of data to the Write FIFO.
References XHwIcap::IsTransferInProgress, XHwIcap::RemainingWords, XHwIcap::RequestedWords, XHwIcap::StatusHandler, XHwIcap::StatusRef, XHI_IPIXR_WRP_MASK, XHwIcap_FifoWrite, XHwIcap_GetWrFifoVacancy, XHwIcap_IntrClear, XHwIcap_IntrGetStatus, XHwIcap_IntrGlobalDisable, XHwIcap_StartConfig.
Referenced by HwIcapIntrExample.
void XHwIcap_SetInterruptHandler(XHwIcap *InstancePtr, void *CallBackRef, XHwIcap_StatusHandler FuncPtr)
Sets the status callback function, the status handler, which the driver calls when it encounters conditions that should be reported to the higher layer software.
The handler executes in an interrupt context, so it must minimize the amount of processing performed such as transferring data to a thread context. One of the following status events is passed to the status handler. InstancePtr is a pointer to the XHwIcap instance. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. FuncPtr is the pointer to the callback function. None. The handler is called within interrupt context, so it should do its work quickly and queue potentially time-consuming work to a task-level thread.
References XHwIcap::IsReady, XHwIcap::StatusHandler, XHwIcap::StatusRef.
Referenced by HwIcapIntrExample.
int XHwIcap_DeviceReadFrame(XHwIcap *InstancePtr, long Top, long Block, long HClkRow, long MajorFrame, long MinorFrame, u32 *FrameBuffer)
Reads one frame from the device and puts it in memory specified by the user.
InstancePtr - a pointer to the XHwIcap instance to be worked on. Top - top (0) or bottom (1) half of device Block - Block Address (XHI_FAR_CLB_BLOCK, XHI_FAR_BRAM_BLOCK, XHI_FAR_BRAM_INT_BLOCK) HClkRow - selects the HClk Row MajorFrame - selects the column MinorFrame - selects frame inside column FrameBuffer is a pointer to the memory where the frame read from the device is stored XST_SUCCESS else XST_FAILURE. This is a blocking call.
References XHwIcap::DeviceFamily, XHwIcap::IsReady, XHwIcap::WordsPerFrame, XHwIcap_CommandDesync, XHwIcap_DeviceRead, XHwIcap_DeviceWrite, XHwIcap_IsDeviceBusy, XHwIcap_Type1Read, XHwIcap_Type1Write.
Referenced by HwIcapReadFramePolledExample.
int XHwIcap_DeviceWriteFrame(XHwIcap *InstancePtr, long Top, long Block, long HClkRow, long MajorFrame, long MinorFrame, u32 *FrameData)
Writes one frame from the specified buffer and puts it in the device (ICAP).
InstancePtr is a pointer to the XHwIcap instance. Top - top (0) or bottom (1) half of device Block - Block Address (XHI_FAR_CLB_BLOCK, XHI_FAR_BRAM_BLOCK, XHI_FAR_BRAM_INT_BLOCK) HClkRow - selects the HClk Row MajorFrame - selects the column MinorFrame - selects frame inside column FrameData is a pointer to the frame that is to be written to the device. XST_SUCCESS else XST_FAILURE. This is a blocking function. This function is used in conjunction with the function XHwIcap_DeviceReadFrame. This function is used to write back the frame of data read using the XHwIcap_DeviceReadFrame.
References XHwIcap::DeviceIdCode, XHwIcap::IsReady, XHwIcap::WordsPerFrame, XHwIcap_CommandDesync, XHwIcap_DeviceWrite, XHwIcap_Type1Write.