xhwicap_selftest.c
int XHwIcap_SelfTest(XHwIcap *InstancePtr)
Run a self-test on the driver/device.
The test Writes to the Interrupt Enable Register and reads it back for comparison. InstancePtr is a pointer to the XHwIcap instance. XST_SUCCESS if the value read from the register is the same as the value written.XST_FAILURE otherwise None.
References XHwIcap_Config::BaseAddress, XHwIcap::HwIcapConfig, XHwIcap::IsReady, XHI_GIER_OFFSET, XHI_IPIXR_ALL_MASK, XHI_IPIXR_RDP_MASK, XHI_IPIXR_WEMPTY_MASK, XHwIcap_IntrDisable, XHwIcap_IntrEnable, XHwIcap_IntrGetEnabled, XHwIcap_IntrGlobalDisable, XHwIcap_ReadReg, XHwIcap_WriteReg.
Referenced by HwIcapIntrExample, HwIcapReadConfigRegExample, HwIcapReadFramePolledExample, HwIcapTestAppExample.