xhwicap.c
DEVICE_7SERIES_WORDS_PER_FRAME
DEVICE_ULTRA_WORDS_PER_FRAME
DEVICE_ULTRA_PLUS_WORDS_PER_FRAME
u32 series_7idcodes[NUM_7SERIES_IDCODES][NUM_7SERIES_IDCODES]
u32 series_ultra_idcodes[NUM_ULTRA_SERIES_IDCODES][NUM_ULTRA_SERIES_IDCODES]
u32 series_ultra_plus_idcodes[NUM_ULTRA_PLUS_SERIES_IDCODES][NUM_ULTRA_PLUS_SERIES_IDCODES]
static void StubStatusHandler(void *CallBackRef, u32 StatusEvent, u32 ByteCount)
This is a stub for the status callback.
The stub is here in case the upper layers forget to set the handler. CallBackRef is a pointer to the upper layer callback reference StatusEvent is the event that just occurred. WordCount is the number of words (32 bit) transferred up until the event occurred. None. None.
static u32 FindDeviceType(u32 IdCode)
int XHwIcap_CfgInitialize(XHwIcap *InstancePtr, XHwIcap_Config *ConfigPtr, UINTPTR EffectiveAddr)
This function initializes a specific XHwIcap instance.
The IDCODE is read from the FPGA and based on the IDCODE the information about the resources in the FPGA is filled in the instance structure.The HwIcap device will be in put in a reset state before exiting this function. InstancePtr is a pointer to the XHwIcap instance. ConfigPtr points to the XHwIcap device configuration structure. EffectiveAddr is the device base address in the virtual memory address space. If the address translation is not used then the physical address is passed. Unexpected errors may occur if the address mapping is changed after this function is invoked. XST_SUCCESS else XST_FAILURE None.
References XHwIcap_Config::BaseAddress, XHwIcap::BytesPerFrame, XHwIcap::DeviceFamily, XHwIcap::HwIcapConfig, XHwIcap_Config::IcapWidth, XHwIcap_Config::IsLiteMode, XHwIcap::IsPolled, XHwIcap::IsReady, XHwIcap::IsTransferInProgress, PCAP_CR_OFFSET, XHwIcap::StatusHandler, XHwIcap::WordsPerFrame, XHwIcap_CommandDesync, XHwIcap_GetConfigReg, XHwIcap_Reset.
Referenced by HwIcapIntrExample, HwIcapReadConfigRegExample, HwIcapReadFramePolledExample, HwIcapTestAppExample.
int XHwIcap_DeviceWrite(XHwIcap *InstancePtr, u32 *FrameBuffer, u32 NumWords)
This function writes the given user data to the Write FIFO in both the polled mode and the interrupt mode and starts the transfer of the data to the ICAP device.
In the polled mode, this function will write the specified number of words into the FIFO before returning.In the interrupt mode, this function will write the words up to the size of the Write FIFO and starts the transfer, then subsequent transfer of the data is performed by the interrupt service routine until the entire buffer has been transferred. The status callback function is called when the entire buffer has been sent. In order to use interrupts, it is necessary for the user to connect the driver interrupt handler, XHwIcap_IntrHandler(), to the interrupt system of the application and enable the interrupts associated with the Write FIFO. The user has to enable the interrupts each time this function is called using the XHwIcap_IntrEnable macro. InstancePtr is a pointer to the XHwIcap instance. FrameBuffer is a pointer to the data to be written to the ICAP device. NumWords is the number of words (16 bit for S6 and 32 bit for all other devices)to write to the ICAP device. XST_SUCCESS or XST_FAILURE This function is a blocking for the polled mode of operation and is non-blocking for the interrupt mode of operation. Use the function XHwIcap_DeviceWriteFrame for writing a frame of data to the ICAP device.
References XHwIcap_Config::BaseAddress, XHwIcap::HwIcapConfig, XHwIcap_Config::IcapWidth, XHwIcap::IsPolled, XHwIcap::IsReady, XHwIcap::IsTransferInProgress, XHwIcap::RemainingWords, XHwIcap::RequestedWords, XHI_CR_OFFSET, XHI_CR_WRITE_MASK, XHwIcap_FifoWrite, XHwIcap_GetWrFifoVacancy, XHwIcap_IntrClear, XHwIcap_IntrGetStatus, XHwIcap_IntrGlobalDisable, XHwIcap_IntrGlobalEnable, XHwIcap_IsDeviceBusy, XHwIcap_IsTransferDone, XHwIcap_ReadReg, XHwIcap_StartConfig.
Referenced by HwIcapIntrExample, XHwIcap_CommandCapture, XHwIcap_CommandDesync, XHwIcap_DeviceReadFrame, XHwIcap_DeviceWriteFrame, XHwIcap_GetConfigReg.
int XHwIcap_DeviceRead(XHwIcap *InstancePtr, u32 *FrameBuffer, u32 NumWords)
This function reads the specified number of words from the ICAP device in the polled mode.
Interrupt mode is not supported in reading data from the ICAP device. InstancePtr is a pointer to the XHwIcap instance. FrameBuffer is a pointer to the memory where the frame read from the ICAP device is stored. NumWords is the number of words (16 bit for S6 and 32 bit for all other devices) to write to the ICAP device. XST_SUCCESS if the specified number of words have been read from the ICAP deviceXST_FAILURE if the device is busy with the last Read/Write or if the requested number of words have not been read from the ICAP device, or there is a timeout. This is a blocking function.
References XHwIcap_Config::BaseAddress, XHwIcap::HwIcapConfig, XHwIcap_Config::IcapWidth, XHwIcap::IsReady, XHwIcap::IsTransferInProgress, XHwIcap::RemainingWords, XHwIcap::RequestedWords, XHI_CR_OFFSET, XHI_CR_READ_MASK, XHwIcap_FifoRead, XHwIcap_GetRdFifoOccupancy, XHwIcap_IsDeviceBusy, XHwIcap_IsTransferDone, XHwIcap_ReadReg, XHwIcap_SetSizeReg, XHwIcap_StartReadBack.
Referenced by XHwIcap_DeviceReadFrame, XHwIcap_GetConfigReg.
void XHwIcap_Reset(XHwIcap *InstancePtr)
This function forces the software reset of the complete HWICAP device.
All the registers will return to the default value and the FIFO is also flushed as a part of this software reset. InstancePtr is a pointer to the XHwIcap instance. None. None.
References XHwIcap_Config::BaseAddress, XHwIcap::HwIcapConfig, XHwIcap::IsReady, XHI_CR_OFFSET, XHI_CR_SW_RESET_MASK, XHwIcap_ReadReg, XHwIcap_WriteReg.
Referenced by XHwIcap_CfgInitialize.
void XHwIcap_FlushFifo(XHwIcap *InstancePtr)
This function flushes the FIFOs in the device.
InstancePtr is a pointer to the XHwIcap instance. None. None.
References XHwIcap_Config::BaseAddress, XHwIcap::HwIcapConfig, XHwIcap::IsReady, XHI_CR_FIFO_CLR_MASK, XHI_CR_OFFSET, XHwIcap_ReadReg, XHwIcap_WriteReg.
void XHwIcap_Abort(XHwIcap *InstancePtr)
This function initiates the Abort Sequence by setting the Abort bit in the control register.
InstancePtr is a pointer to the XHwIcap instance. None. None.
References XHwIcap_Config::BaseAddress, XHwIcap::HwIcapConfig, XHwIcap::IsReady, XHI_CR_OFFSET, XHI_CR_SW_ABORT_MASK, XHwIcap_ReadReg, XHwIcap_WriteReg.