xhwicap_srp.c
DESYNC_COMMAND_SIZE
CAPTURE_COMMAND_SIZE
READ_CFG_REG_COMMAND_SIZE
int XHwIcap_CommandDesync(XHwIcap *InstancePtr)
Sends a DESYNC command to the ICAP port.
InstancePtr - a pointer to the XHwIcap instance to be worked on XST_SUCCESS else XST_FAILURE None.
References XHwIcap::IsReady, XHwIcap_DeviceWrite, XHwIcap_Type1Write.
Referenced by XHwIcap_CfgInitialize, XHwIcap_DeviceReadFrame, XHwIcap_DeviceWriteFrame.
int XHwIcap_CommandCapture(XHwIcap *InstancePtr)
Sends a CAPTURE command to the ICAP port.
This command captures all of the flip flop states so they will be available during readback. One can use this command instead of enabling the CAPTURE block in the design. InstancePtr is a pointer to the XHwIcap instance. XST_SUCCESS or XST_FAILURE None.
References XHwIcap::IsReady, XHwIcap_DeviceWrite, XHwIcap_Type1Write.
u32 XHwIcap_GetConfigReg(XHwIcap *InstancePtr, u32 ConfigReg, u32 *RegData)
This function returns the value of the specified configuration register.
InstancePtr is a pointer to the XHwIcap instance. ConfigReg is a constant which represents the configuration register value to be returned. Constants specified in xhwicap_i.h. Examples: XHI_IDCODE, XHI_FLR. RegData is the value of the specified configuration register. XST_SUCCESS or XST_FAILURE This is a blocking call.
References XHwIcap_Config::BaseAddress, XHwIcap::HwIcapConfig, XHwIcap::IsReady, XHI_CR_OFFSET, XHI_CR_WRITE_MASK, XHI_SR_EOS_MASK, XHI_SR_OFFSET, XHwIcap_DeviceRead, XHwIcap_DeviceWrite, XHwIcap_IsDeviceBusy, XHwIcap_ReadReg, XHwIcap_Type1Read.
Referenced by HwIcapReadConfigRegExample, HwIcapTestAppExample, XHwIcap_CfgInitialize.