scugic_api
EFUSE_STATUS_OFFSET
EFUSE_STATUS_CPU_MASK
ARMA9
ARMA9 macro to identify cortexA9.
XScuGic_Config XScuGic_ConfigTable[][]
Config table.
Config table.The XScuGic driver must know when to acknowledge the interrupt. The entry which specifies this as a bit mask where each bit corresponds to a specific interrupt. A bit set indicates to ACK it before servicing it. Generally, acknowledge before service is used when the interrupt signal is edge-sensitive, and after when the signal is level-sensitive.Refer to the XScuGic_Config data structure in xscugic.h for details on how this table should be initialized.
Referenced by XScuGic_DeviceInterruptHandler, XScuGic_LookupConfig.
s32 XScuGic_CfgInitialize(XScuGic *InstancePtr, XScuGic_Config *ConfigPtr, u32 EffectiveAddr)
CfgInitialize a specific interrupt controller instance/driver.
The initialization entails: Initialize fields of the XScuGic structureInitial vector table with stub function callsAll interrupt sources are disabled InstancePtr Pointer to the XScuGic instance. ConfigPtr Pointer to a config table for the particular device this driver is associated with. EffectiveAddr Device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, use Config->BaseAddress for this parameters, passing the physical address instead. XST_SUCCESS if initialization was successful
References XScuGic::Config, XScuGic_Config::DistBaseAddress, XScuGic_Config::HandlerTable, XScuGic::IsReady, XSCUGIC_MAX_NUM_INTR_INPUTS, XScuGic_Stop.
Referenced by ScuGicExample, ScuGicInterruptSetup, ScuGicSelfTestExample.
s32 XScuGic_Connect(XScuGic *InstancePtr, u32 Int_Id, Xil_InterruptHandler Handler, void *CallBackRef)
Makes the connection between the Int_Id of the interrupt source and the associated handler that is to run when the interrupt is recognized.
The argument provided in this call as the Callbackref is used as the argument for the handler when it is called. InstancePtr Pointer to the XScuGic instance. Int_Id contains the ID of the interrupt source and should be in the range of 0 to XSCUGIC_MAX_NUM_INTR_INPUTS - 1 Handler Handler for interrupt. CallBackRef Instance pointer of the connecting driver. - XST_SUCCESS if the handler was connected correctly. WARNING: The handler provided as an argument will overwrite any handler that was previously connected.
References XScuGic::Config, XScuGic_Config::HandlerTable, XScuGic::IsReady.
Referenced by ScuGicExample.
void XScuGic_Disconnect(XScuGic *InstancePtr, u32 Int_Id)
Updates the interrupt table with the Null Handler and NULL arguments at the location pointed at by the Int_Id.
This effectively disconnects that interrupt source from any handler. The interrupt is disabled also. InstancePtr Pointer to the XScuGic instance to be worked on. Int_Id Contains the ID of the interrupt source and should be in the range of 0 to XSCUGIC_MAX_NUM_INTR_INPUTS - 1 None.
References XScuGic::Config, XScuGic_Config::HandlerTable, XScuGic::IsReady, XSCUGIC_DISABLE_OFFSET, XScuGic_DistWriteReg.
void XScuGic_Enable(XScuGic *InstancePtr, u32 Int_Id)
Enables the interrupt source provided as the argument Int_Id.
Any pending interrupt condition for the specified Int_Id will occur after this function is called. This API also maps the interrupt to the requesting CPU. InstancePtr Pointer to the XScuGic instance. Int_Id Contains the ID of the interrupt source and should be in the range of 0 to XSCUGIC_MAX_NUM_INTR_INPUTS - 1 None.
References XScuGic::IsReady, XScuGic_DistWriteReg, XSCUGIC_ENABLE_SET_OFFSET, XScuGic_InterruptMaptoCpu, XSCUGIC_SPI_INT_ID_START.
Referenced by ScuGicExample.
void XScuGic_Disable(XScuGic *InstancePtr, u32 Int_Id)
Disables the interrupt source provided as the argument Int_Id such that the interrupt controller will not cause interrupts for the specified Int_Id.
The interrupt controller will continue to hold an interrupt condition for the Int_Id, but will not cause an interrupt. This API also unmaps the interrupt for the requesting CPU. InstancePtr Pointer to the XScuGic instance. Int_Id Contains the ID of the interrupt source and should be in the range of 0 to XSCUGIC_MAX_NUM_INTR_INPUTS - 1 None.
References XScuGic::IsReady, XSCUGIC_DISABLE_OFFSET, XScuGic_DistWriteReg, XScuGic_InterruptUnmapFromCpu, XSCUGIC_SPI_INT_ID_START.
s32 XScuGic_SoftwareIntr(XScuGic *InstancePtr, u32 Int_Id, u32 Cpu_Identifier)
Allows software to simulate an interrupt in the interrupt controller.
This function will only be successful when the interrupt controller has been started in simulation mode. A simulated interrupt allows the interrupt controller to be tested without any device to drive an interrupt input signal into it. InstancePtr Pointer to the XScuGic instance. Int_Id Software interrupt ID to simulate an interrupt. Cpu_Identifier List of CPUs to send the interrupt. For VERSAL_NET bits 0-7 specifies core ID to send the interrupt. bits 8-15 specifies the cluster id. XST_SUCCESS if successful, or XST_FAILURE if the interrupt could not be simulated
References XScuGic::IsReady, XScuGic_DistWriteReg, XSCUGIC_SFI_TRIG_CPU_MASK, XSCUGIC_SFI_TRIG_INTID_MASK, XSCUGIC_SFI_TRIG_OFFSET.
Referenced by ScuGicExample.
void XScuGic_SetPriorityTriggerType(XScuGic *InstancePtr, u32 Int_Id, u8 Priority, u8 Trigger)
Sets the interrupt priority and trigger type for the specificd IRQ source.
InstancePtr Pointer to the instance to be worked on. Int_Id IRQ source number to modify. Priority New priority for the IRQ source. 0 is highest priority, 0xF8(248) is lowest. There are 32 priority levels supported with a step of 8. Hence the supported priorities are 0, 8, 16, 32, 40 ..., 248. Trigger New trigger type for the IRQ source. Each bit pair describes the configuration for an INT_ID. SFI Read Only b10 always PPI Read Only depending on how the PPIs are configured. b01 Active HIGH level sensitive b11 Rising edge sensitive SPI LSB is read only. b01 Active HIGH level sensitive b11 Rising edge sensitive/ None.
References XScuGic::IsReady, XScuGic_DistReadReg, XScuGic_DistWriteReg, XSCUGIC_INT_CFG_MASK, XSCUGIC_INT_CFG_OFFSET_CALC, XSCUGIC_INTR_PRIO_MASK, XSCUGIC_MAX_INTR_PRIO_VAL, XSCUGIC_PRIORITY_MASK, XSCUGIC_PRIORITY_OFFSET_CALC, XSCUGIC_RDIST_INT_CONFIG_OFFSET_CALC, XSCUGIC_RDIST_INT_PRIORITY_OFFSET_CALC, XSCUGIC_SPI_INT_ID_START.
void XScuGic_GetPriorityTriggerType(XScuGic *InstancePtr, u32 Int_Id, u8 *Priority, u8 *Trigger)
Gets the interrupt priority and trigger type for the specificd IRQ source.
InstancePtr Pointer to the instance to be worked on. Int_Id IRQ source number to modify. Priority Pointer to the value of the priority of the IRQ source. This is a return value. Trigger Pointer to the value of the trigger of the IRQ source. Pointer to the value of the trigger of the IRQ source.
References XScuGic::IsReady, XScuGic_DistReadReg, XSCUGIC_INT_CFG_MASK, XSCUGIC_INT_CFG_OFFSET_CALC, XSCUGIC_PRIORITY_MASK, XSCUGIC_PRIORITY_OFFSET_CALC, XSCUGIC_RDIST_INT_CONFIG_OFFSET_CALC, XSCUGIC_RDIST_INT_PRIORITY_OFFSET_CALC, XSCUGIC_SPI_INT_ID_START.
void XScuGic_InterruptMaptoCpu(XScuGic *InstancePtr, u8 Cpu_Identifier, u32 Int_Id)
Sets the target CPU for the interrupt of a peripheral.
InstancePtr Pointer to the instance to be worked on. Cpu_Identifier CPU number for which the interrupt has to be targeted For VERSAL_NET APU: 0 t0 3 bits specifies core id and 4 to 7 bits specifies cluster id of the targeted core. Int_Id IRQ source number to modify. None.
References XScuGic_DistReadReg, XScuGic_DistWriteReg, XSCUGIC_IROUTER_OFFSET_CALC, XSCUGIC_SPI_INT_ID_START, XSCUGIC_SPI_TARGET_OFFSET_CALC.
Referenced by XScuGic_Enable.
void XScuGic_InterruptUnmapFromCpu(XScuGic *InstancePtr, u8 Cpu_Identifier, u32 Int_Id)
Unmaps specific SPI interrupt from the target CPU.
InstancePtr Pointer to the instance to be worked on. Cpu_Identifier CPU number from which the interrupt has to be unmapped. For VERSAL_NET APU: 0 t0 3 bits specifies core id and 4 to 7 bits specifies cluster id of the targeted core. Int_Id IRQ source number to modify None.
References XScuGic_DistReadReg, XScuGic_DistWriteReg, XSCUGIC_SPI_INT_ID_START, XSCUGIC_SPI_TARGET_OFFSET_CALC.
Referenced by XScuGic_Disable.
void XScuGic_UnmapAllInterruptsFromCpu(XScuGic *InstancePtr, u8 Cpu_Identifier)
Unmaps all SPI interrupts from the target CPU.
InstancePtr Pointer to the instance to be worked on. Cpu_Identifier CPU number from which the interrupts has to be unmapped. None.
References XScuGic_DistReadReg, XScuGic_DistWriteReg, XSCUGIC_MAX_NUM_INTR_INPUTS, XSCUGIC_SPI_TARGET_OFFSET_CALC.
void XScuGic_Stop(XScuGic *InstancePtr)
Checks if the interrupt target register contains all interrupts to be targeted for current CPU.
If they are programmed to be forwarded to current cpu, this API disable all interrupts and disable GIC distributor. This API also removes current CPU from interrupt target registers for all interrupt. InstancePtr Pointer to the instance to be worked on. None.
References XSCUGIC_DISABLE_OFFSET, XSCUGIC_DIST_EN_OFFSET, XScuGic_DistReadReg, XScuGic_DistWriteReg, XSCUGIC_EN_DIS_OFFSET_CALC, XSCUGIC_EN_INT_MASK, XSCUGIC_IROUTER_OFFSET_CALC, XSCUGIC_MAX_NUM_INTR_INPUTS, XSCUGIC_SPI_TARGET_OFFSET_CALC.
Referenced by XScuGic_CfgInitialize.
void XScuGic_SetCpuID(u32 CpuCoreId)
Updates the CpuId global variable.
CpuCoreId CPU core number. None.
u32 XScuGic_GetCpuID(void)
Returns the CpuId variable.
The CPU core number.
Referenced by XScuGic_DisableIntr, XScuGic_EnableIntr.
u8 XScuGic_IsInitialized(u32 BaseAddress)
Checks whether the XScGic is initialized or not given the device ID/BaseAddress.
BaseAddress is the base address of the device Returns 1 if initialized otherwise 0. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XScuGic_Config::DistBaseAddress, XSCUGIC_DIST_EN_OFFSET, XSCUGIC_EN_INT_MASK, XScuGic_LookupConfig, XScuGic_ReadReg.
XScuGic_Config * XScuGic_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
A table contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the XScuGic configuration structure for the specified device, or NULL if the device ID/BaseAddress is not found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XScuGic_Config::Name, XScuGic_ConfigTable.
Referenced by ScuGicExample, ScuGicInterruptSetup, ScuGicSelfTestExample, XScuGic_DeviceInitialize, XScuGic_IsInitialized.
void XScuGic_InterruptHandler(XScuGic *InstancePtr)
This function is the primary interrupt handler for the driver.
It must be connected to the interrupt source such that it is called when an interrupt of the interrupt controller is active. It will resolve which interrupts are active and enabled and call the appropriate interrupt handler. It uses the Interrupt Type information to determine when to acknowledge the interrupt. Highest priority interrupts are serviced first.This function assumes that an interrupt vector table has been previously initialized. It does not verify that entries in the table are valid before calling an interrupt handler. InstancePtr Pointer to the XScuGic instance. None.
References XScuGic::Config, XScuGic_Config::HandlerTable, XSCUGIC_ACK_INTID_MASK, XScuGic_CPUReadReg, XScuGic_CPUWriteReg, XSCUGIC_EOI_OFFSET, XSCUGIC_INT_ACK_OFFSET, XSCUGIC_MAX_NUM_INTR_INPUTS.
Referenced by ScuGicInterruptSetup, SetUpInterruptSystem.
s32 XScuGic_SelfTest(XScuGic *InstancePtr)
Runs a self-test on the driver/device.
This test reads the ID registers and compares them. InstancePtr Pointer to the XScuGic instance. -XST_SUCCESS if self-test is successful. -XST_FAILURE if the self-test is not successful.
References XScuGic::IsReady, XScuGic_DistReadReg, XSCUGIC_PCELL_ID, XSCUGIC_PCELLID_OFFSET.
Referenced by ScuGicExample.
XSCUGIC500_DCTLR_ARE_NS_ENABLE
XSCUGIC500_DCTLR_ARE_S_ENABLE
XScuGic_CPUWriteReg
Writes the given CPU Interface register.
InstancePtr Pointer to the instance to be worked on. RegOffset Register offset to be written. Data 32-bit value to write to the register. None. C-style signature: void XScuGic_CPUWriteReg(XScuGic *InstancePtr, u32 RegOffset, u32 Data)
Referenced by XScuGic_InterruptHandler.
XScuGic_CPUReadReg
Reads the given CPU Interface register.
InstancePtr Pointer to the instance to be worked on. RegOffset Rregister offset to be read. 32-bit value of the register C-style signature: u32 XScuGic_CPUReadReg(XScuGic *InstancePtr, u32 RegOffset)
Referenced by XScuGic_InterruptHandler.
XScuGic_DistWriteReg
Writes the given Distributor Interface register.
InstancePtr Pointer to the instance to be worked on. RegOffset Register offset to be written. Data 32-bit value to write to the register. None. C-style signature: void XScuGic_DistWriteReg(XScuGic *InstancePtr, u32 RegOffset, u32 Data)
Referenced by XScuGic_Disable, XScuGic_Disconnect, XScuGic_Enable, XScuGic_InterruptMaptoCpu, XScuGic_InterruptUnmapFromCpu, XScuGic_SetPriorityTriggerType, XScuGic_SoftwareIntr, XScuGic_Stop, XScuGic_UnmapAllInterruptsFromCpu.
XScuGic_DistReadReg
Reads the given Distributor Interface register.
InstancePtr Pointer to the instance to be worked on. RegOffset Register offset to be read. The 32-bit value of the register. C-style signature: u32 XScuGic_DistReadReg(XScuGic *InstancePtr, u32 RegOffset)
Referenced by XScuGic_GetPriorityTriggerType, XScuGic_InterruptMaptoCpu, XScuGic_InterruptUnmapFromCpu, XScuGic_SelfTest, XScuGic_SetPriorityTriggerType, XScuGic_Stop, XScuGic_UnmapAllInterruptsFromCpu.
XSCUGIC_DIST_EN_OFFSET
Distributor Enable Register.
Referenced by XScuGic_IsInitialized, XScuGic_Stop.
XSCUGIC_IC_TYPE_OFFSET
Interrupt Controller Type Register.
XSCUGIC_DIST_IDENT_OFFSET
Implementer ID Register.
XSCUGIC_SECURITY_OFFSET
Interrupt Security Register.
XSCUGIC_ENABLE_SET_OFFSET
Enable Set Register.
Referenced by XScuGic_Enable, XScuGic_EnableIntr.
XSCUGIC_DISABLE_OFFSET
Enable Clear Register.
Referenced by XScuGic_Disable, XScuGic_DisableIntr, XScuGic_Disconnect, XScuGic_Stop.
XSCUGIC_PENDING_SET_OFFSET
Pending Set Register.
XSCUGIC_PENDING_CLR_OFFSET
Pending Clear Register.
XSCUGIC_ACTIVE_OFFSET
Active Status Register.
XSCUGIC_PRIORITY_OFFSET
Priority Level Register.
XSCUGIC_SPI_TARGET_OFFSET
SPI Target Register 0x800-0x8FB.
XSCUGIC_INT_CFG_OFFSET
Interrupt Configuration Register 0xC00-0xCFC.
XSCUGIC_PPI_STAT_OFFSET
PPI Status Register.
XSCUGIC_SPI_STAT_OFFSET
SPI Status Register 0xd04-0xd7C.
XSCUGIC_AHB_CONFIG_OFFSET
AHB Configuration Register.
XSCUGIC_SFI_TRIG_OFFSET
Software Triggered Interrupt Register.
Referenced by XScuGic_SoftwareIntr.
XSCUGIC_PERPHID_OFFSET
Peripheral ID Reg.
XSCUGIC_PCELLID_OFFSET
Pcell ID Register.
Referenced by XScuGic_SelfTest.
XSCUGIC_EN_INT_MASK
Interrupt In Enable.
Referenced by XScuGic_IsInitialized, XScuGic_Stop.
XSCUGIC_LSPI_MASK
Number of Lockable Shared Peripheral Interrupts.
XSCUGIC_DOMAIN_MASK
Number os Security domains.
XSCUGIC_CPU_NUM_MASK
Number of CPU Interfaces.
XSCUGIC_NUM_INT_MASK
Number of Interrupt IDs.
XSCUGIC_REV_MASK
Revision Number.
XSCUGIC_IMPL_MASK
Implementer.
XSCUGIC_INT_NS_MASK
Each bit corresponds to an INT_ID.
XSCUGIC_INT_EN_MASK
Each bit corresponds to an INT_ID.
XSCUGIC_INT_CLR_MASK
Each bit corresponds to an INT_ID.
XSCUGIC_PEND_SET_MASK
Each bit corresponds to an INT_ID.
XSCUGIC_PEND_CLR_MASK
Each bit corresponds to an INT_ID.
XSCUGIC_ACTIVE_MASK
Each bit corresponds to an INT_ID.
XSCUGIC_PRIORITY_MASK
Each Byte corresponds to an INT_ID.
Referenced by XScuGic_GetPriorityTriggerType, XScuGic_GetPriTrigTypeByDistAddr, XScuGic_SetPriorityTriggerType, XScuGic_SetPriTrigTypeByDistAddr.
XSCUGIC_PRIORITY_MAX
Highest value of a priority actually the lowest priority.
XSCUGIC_SPI_CPU7_MASK
CPU 7 Mask.
XSCUGIC_SPI_CPU6_MASK
CPU 6 Mask.
XSCUGIC_SPI_CPU5_MASK
CPU 5 Mask.
XSCUGIC_SPI_CPU4_MASK
CPU 4 Mask.
XSCUGIC_SPI_CPU3_MASK
CPU 3 Mask.
XSCUGIC_SPI_CPU2_MASK
CPU 2 Mask.
XSCUGIC_SPI_CPU1_MASK
CPU 1 Mask.
XSCUGIC_SPI_CPU0_MASK
CPU 0 Mask.
Referenced by ScuGicExample.
XSCUGIC_INT_CFG_MASK
Interrupt configuration Mask.
Referenced by XScuGic_GetPriorityTriggerType, XScuGic_GetPriTrigTypeByDistAddr, XScuGic_SetPriorityTriggerType, XScuGic_SetPriTrigTypeByDistAddr.
XSCUGIC_PPI_C15_MASK
PPI Status.
XSCUGIC_PPI_C14_MASK
PPI Status.
XSCUGIC_PPI_C13_MASK
PPI Status.
XSCUGIC_PPI_C12_MASK
PPI Status.
XSCUGIC_PPI_C11_MASK
PPI Status.
XSCUGIC_PPI_C10_MASK
PPI Status.
XSCUGIC_PPI_C09_MASK
PPI Status.
XSCUGIC_PPI_C08_MASK
PPI Status.
XSCUGIC_PPI_C07_MASK
PPI Status.
XSCUGIC_PPI_C06_MASK
PPI Status.
XSCUGIC_PPI_C05_MASK
PPI Status.
XSCUGIC_PPI_C04_MASK
PPI Status.
XSCUGIC_PPI_C03_MASK
PPI Status.
XSCUGIC_PPI_C02_MASK
PPI Status.
XSCUGIC_PPI_C01_MASK
PPI Status.
XSCUGIC_PPI_C00_MASK
PPI Status.
XSCUGIC_SPI_N_MASK
Each bit corresponds to an SPI input.
XSCUGIC_AHB_END_MASK
0-GIC uses little Endian, 1-GIC uses Big Endian
XSCUGIC_AHB_ENDOVR_MASK
0-Uses CFGBIGEND control, 1-use the AHB_END bit
XSCUGIC_AHB_TIE_OFF_MASK
State of CFGBIGEND.
XSCUGIC_SFI_SELFTRIG_MASK
XSCUGIC_SFI_TRIG_TRGFILT_MASK
Target List filter b00-Use the target List b01-All CPUs except requester b10-To Requester b11-reserved.
XSCUGIC_SFI_TRIG_CPU_MASK
CPU Target list.
Referenced by XScuGic_SoftwareIntr.
XSCUGIC_SFI_TRIG_SATT_MASK
0= Use a secure interrupt
XSCUGIC_SFI_TRIG_INTID_MASK
Set to the INTID signaled to the CPU.
Referenced by XScuGic_SoftwareIntr.
XSCUGIC_CONTROL_OFFSET
CPU Interface Control Register.
XSCUGIC_CPU_PRIOR_OFFSET
Priority Mask Reg.
XSCUGIC_BIN_PT_OFFSET
Binary Point Register.
XSCUGIC_INT_ACK_OFFSET
Interrupt ACK Reg.
Referenced by LowInterruptHandler, XScuGic_DeviceInterruptHandler, XScuGic_InterruptHandler.
XSCUGIC_EOI_OFFSET
End of Interrupt Reg.
Referenced by LowInterruptHandler, XScuGic_DeviceInterruptHandler, XScuGic_InterruptHandler.
XSCUGIC_RUN_PRIOR_OFFSET
Running Priority Reg.
XSCUGIC_HI_PEND_OFFSET
Highest Pending Interrupt Register.
XSCUGIC_ALIAS_BIN_PT_OFFSET
Aliased non-Secure Binary Point Register.
0x00000020 to 0x00000FBC are reserved and should not be read or written to.
XSCUGIC_CNTR_SBPR_MASK
Secure Binary Pointer, 0=separate registers, 1=both use bin_pt_s.
XSCUGIC_CNTR_FIQEN_MASK
Use nFIQ_C for secure interrupts, 0= use IRQ for both, 1=Use FIQ for secure, IRQ for non.
XSCUGIC_CNTR_ACKCTL_MASK
Ack control for secure or non secure.
XSCUGIC_CNTR_EN_NS_MASK
Non Secure enable.
XSCUGIC_CNTR_EN_S_MASK
Secure enable, 0=Disabled, 1=Enabled.
XSCUGIC_BIN_PT_MASK
Binary point mask value Value Secure Non-secure b000 0xFE 0xFF b001 0xFC 0xFE b010 0xF8 0xFC b011 0xF0 0xF8 b100 0xE0 0xF0 b101 0xC0 0xE0 b110 0x80 0xC0 b111 0x00 0x80.
XSCUGIC_ACK_INTID_MASK
Interrupt ID.
Referenced by LowInterruptHandler, XScuGic_DeviceInterruptHandler, XScuGic_InterruptHandler.
XSCUGIC_CPUID_MASK
CPU ID.
XSCUGIC_EOI_INTID_MASK
Interrupt ID.
XSCUGIC_RUN_PRIORITY_MASK
Interrupt Priority.
u32 CpuId
CPU Core identifier.
Xil_InterruptHandler XScuGic_VectorTableEntry::Handler
Interrupt Handler.
void* XScuGic_VectorTableEntry::CallBackRef
CallBackRef is the callback reference passed in by the upper layer when setting the Interrupt handler for specific interrupt ID, and it will passed back to Interrupt handler when it is invoked.
char* XScuGic_Config::Name
Compatible string.
Referenced by XScuGic_LookupConfig.
UINTPTR XScuGic_Config::DistBaseAddress
Distributor Register base address.
Referenced by XScuGic_CfgInitialize, XScuGic_IsInitialized.
UINTPTR XScuGic_Config::CpuBaseAddress
CPU Interface Register base address.
Referenced by ScuGicExample, ScuGicInterruptSetup, ScuGicSelfTestExample, SetupInterruptSystem.
XScuGic_VectorTableEntry XScuGic_Config::HandlerTable[XSCUGIC_MAX_NUM_INTR_INPUTS][XSCUGIC_MAX_NUM_INTR_INPUTS]
Vector table of interrupt handlers.
Referenced by XScuGic_CfgInitialize, XScuGic_Connect, XScuGic_Disconnect, XScuGic_InterruptHandler, XScuGic_RegisterHandler.
XScuGic_Config* XScuGic::Config
Configuration table entry.
Referenced by XScuGic_CfgInitialize, XScuGic_Connect, XScuGic_Disconnect, XScuGic_InterruptHandler.
u32 XScuGic::IsReady
Device is initialized and ready.
Referenced by XScuGic_CfgInitialize, XScuGic_Connect, XScuGic_Disable, XScuGic_Disconnect, XScuGic_Enable, XScuGic_GetPriorityTriggerType, XScuGic_SelfTest, XScuGic_SetPriorityTriggerType, XScuGic_SoftwareIntr.
u32 XScuGic::UnhandledInterrupts
Intc Statistics.
XScuGic_Config XScuGic_ConfigTable[XPAR_XSCUGIC_NUM_INSTANCES][XPAR_XSCUGIC_NUM_INSTANCES]
This table contains configuration information for each GIC device in the system.
Config table.The XScuGic driver must know when to acknowledge the interrupt. The entry which specifies this as a bit mask where each bit corresponds to a specific interrupt. A bit set indicates to ACK it before servicing it. Generally, acknowledge before service is used when the interrupt signal is edge-sensitive, and after when the signal is level-sensitive.Refer to the XScuGic_Config data structure in xscugic.h for details on how this table should be initialized.
Referenced by XScuGic_DeviceInterruptHandler, XScuGic_LookupConfig.
static void StubHandler(void *CallBackRef)
A stub for the asynchronous callback.
The stub is here in case the upper layers forget to set the handler. CallBackRef Pointer to the upper layer callback reference. None.
static void DoDistributorInit(const XScuGic *InstancePtr)
DoDistributorInit initializes the distributor of the GIC.
The initialization entails: Write the trigger mode, priorityAll interrupt sources are disabledEnable the distributor InstancePtr Pointer to the XScuGic instance. None
static void DistributorInit(XScuGic *InstancePtr)
DistributorInit initializes the distributor of the GIC.
It calls DoDistributorInit to finish the initialization. InstancePtr Pointer to the XScuGic instance. None
static void CPUInitialize(const XScuGic *InstancePtr)
CPUInitialize initializes the CPU Interface of the GIC.
The initialization entails: - Set the priority of the CPU - Enable the CPU interface InstancePtr Pointer to the XScuGic instance. None
static void DistInit(const XScuGic_Config *Config)
DistInit initializes the distributor of the GIC.
The initialization entails: Write the trigger mode, priority and target CPUAll interrupt sources are disabledEnable the distributor None
static void CPUInit(const XScuGic_Config *Config)
CPUInit initializes the CPU Interface of the GIC.
The initialization entails: Set the priority of the CPU.Enable the CPU interface None
static XScuGic_Config * LookupConfigByBaseAddress(UINTPTR CpuBaseAddress)
Looks up the device configuration based on the CPU interface base address of the device.
A table contains the configuration info for each device in the system. CpuBaseAddress CPU Interface Register base address. A pointer to the configuration structure for the specified device, or NULL if the device was not found.
s32 XScuGic_DeviceInitialize(u32 DistBaseAddr)
Initializes the GIC based on the device ID.
The initialization entails: Initialize distributor interfaceInitialize cpu interface DeviceId Device id to be worked on. XST_SUCCESS if initialization was successful
References XScuGic_LookupConfig.
void XScuGic_DeviceInterruptHandler(void *DeviceId)
This function is the primary interrupt handler for the driver.
It must be connected to the interrupt source such that it is called when an interrupt of the interrupt controller is active. It will resolve which interrupts are active and enabled and call the appropriate interrupt handler. It uses the Interrupt Type information to determine when to acknowledge the interrupt. Highest priority interrupts are serviced first.This function assumes that an interrupt vector table has been previously initialized. It does not verify that entries in the table are valid before calling an interrupt handler. DeviceId Unique identifier for the ScuGic device. None.
References XSCUGIC_ACK_INTID_MASK, XScuGic_ConfigTable, XSCUGIC_EOI_OFFSET, XSCUGIC_INT_ACK_OFFSET, XScuGic_ReadReg, XScuGic_WriteReg.
void XScuGic_RegisterHandler(UINTPTR BaseAddress, s32 InterruptID, Xil_InterruptHandler IntrHandler, void *CallBackRef)
Register a handler function for a specific interrupt ID.
The vector table of the interrupt controller is updated, overwriting any previous handler. The handler function will be called when an interrupt occurs for the given interrupt ID. BaseAddress CPU Interface Register base address of the interrupt controller whose vector table will be modified. InterruptID Interrupt ID to be associated with the input handler. IntrHandler Function pointer that will be added to the vector table for the given interrupt ID. CallBackRef Argument that will be passed to the new handler function when it is called. This is user-specific. None. This function has no effect if the input base address is invalid.
References XScuGic_Config::HandlerTable.
void XScuGic_SetPriTrigTypeByDistAddr(UINTPTR DistBaseAddress, u32 Int_Id, u8 Priority, u8 Trigger)
Sets the interrupt priority and trigger type for the specificd IRQ source.
DistBaseAddress Distributor base address Int_Id IRQ source number to modify Priority New priority for the IRQ source. 0 is highest priority, 0xF8(248) is lowest. There are 32 priority levels supported with a step of 8. Hence the supported priorities are 0, 8, 16, 32, 40 ..., 248. Trigger New trigger type for the IRQ source. Each bit pair describes the configuration for an INT_ID. SFI Read Only b10 always PPI Read Only depending on how the PPIs are configured. b01 Active HIGH level sensitive b11 Rising edge sensitive SPI LSB is read only. b01 Active HIGH level sensitive b11 Rising edge sensitive/ None. This API has the similar functionality of XScuGic_SetPriority TriggerType() and should be used when there is no InstancePtr.
References XSCUGIC_INT_CFG_MASK, XSCUGIC_INT_CFG_OFFSET_CALC, XSCUGIC_INTR_PRIO_MASK, XSCUGIC_MAX_INTR_PRIO_VAL, XSCUGIC_PRIORITY_MASK, XSCUGIC_PRIORITY_OFFSET_CALC, XSCUGIC_RDIST_INT_CONFIG_OFFSET_CALC, XSCUGIC_RDIST_INT_PRIORITY_OFFSET_CALC, XScuGic_ReadReg, XSCUGIC_SPI_INT_ID_START, XScuGic_WriteReg.
void XScuGic_GetPriTrigTypeByDistAddr(UINTPTR DistBaseAddress, u32 Int_Id, u8 *Priority, u8 *Trigger)
Gets the interrupt priority and trigger type for the specificd IRQ source.
DistBaseAddress Distributor base address Int_Id IRQ source number to modify Priority Pointer to the value of the priority of the IRQ source. This is a return value. Trigger Pointer to the value of the trigger of the IRQ source. This is a return value. None. This API has the similar functionality of XScuGic_GetPriority TriggerType() and should be used when there is no InstancePtr.
References XSCUGIC_INT_CFG_MASK, XSCUGIC_INT_CFG_OFFSET_CALC, XSCUGIC_PRIORITY_MASK, XSCUGIC_PRIORITY_OFFSET_CALC, XSCUGIC_RDIST_INT_CONFIG_OFFSET_CALC, XSCUGIC_RDIST_INT_PRIORITY_OFFSET_CALC, XScuGic_ReadReg, XSCUGIC_SPI_INT_ID_START.
void XScuGic_InterruptMapFromCpuByDistAddr(UINTPTR DistBaseAddress, u8 Cpu_Id, u32 Int_Id)
Sets the target CPU for the interrupt of a peripheral.
DistBaseAddress Device base address Cpu_Id CPU number from which the interrupt has to be unmapped Int_Id IRQ source number to modify None.
References XSCUGIC_IROUTER_OFFSET_CALC, XScuGic_ReadReg, XSCUGIC_SPI_INT_ID_START, XSCUGIC_SPI_TARGET_OFFSET_CALC, XScuGic_WriteReg.
Referenced by XScuGic_EnableIntr.
void XScuGic_InterruptUnmapFromCpuByDistAddr(UINTPTR DistBaseAddress, u8 Cpu_Id, u32 Int_Id)
Unmaps specific SPI interrupt from the target CPU.
DistBaseAddress Device base address Cpu_Id CPU number from which the interrupt has to be unmapped Int_Id IRQ source number to modify None
References XScuGic_ReadReg, XSCUGIC_SPI_INT_ID_START, XSCUGIC_SPI_TARGET_OFFSET_CALC, XScuGic_WriteReg.
Referenced by XScuGic_DisableIntr.
void XScuGic_UnmapAllInterruptsFromCpuByDistAddr(UINTPTR DistBaseAddress, u8 Cpu_Id)
Unmaps all SPI interrupts from the target CPU.
DistBaseAddress Device base address Cpu_Id CPU number from which the interrupts has to be unmapped None.
References XSCUGIC_MAX_NUM_INTR_INPUTS, XScuGic_ReadReg, XSCUGIC_SPI_TARGET_OFFSET_CALC, XScuGic_WriteReg.
void XScuGic_EnableIntr(UINTPTR DistBaseAddress, u32 Int_Id)
Enables the interrupt source provided as the argument Int_Id.
Any pending interrupt condition for the specified Int_Id will occur after this function is called. Int_Id Contains the ID of the interrupt source and should be in the range of 0 to XSCUGIC_MAX_NUM_INTR_INPUTS - 1. None.
References XSCUGIC_ENABLE_SET_OFFSET, XScuGic_GetCpuID, XScuGic_InterruptMapFromCpuByDistAddr, XScuGic_ReadReg, XSCUGIC_SPI_INT_ID_START, XScuGic_WriteReg.
void XScuGic_DisableIntr(UINTPTR DistBaseAddress, u32 Int_Id)
Disables the interrupt source provided as the argument Int_Id so that the interrupt controller will not cause interrupts for the specified Int_Id.
The interrupt controller will continue to hold an interrupt condition for the Int_Id, but will not cause an interrupt. Int_Id Contains the ID of the interrupt source and should be in the range of 0 to XSCUGIC_MAX_NUM_INTR_INPUTS - 1. None.
References XSCUGIC_DISABLE_OFFSET, XScuGic_GetCpuID, XScuGic_InterruptUnmapFromCpuByDistAddr, XScuGic_ReadReg, XSCUGIC_SPI_INT_ID_START, XScuGic_WriteReg.
DEFAULT_PRIORITY
Default value for priority_level register.
XSCUGIC_H
< prevent circular inclusions
by using protection macros
DEFAULT_PRIORITY
Default value for priority_level register.
XSCUGIC_HW_H
< prevent circular inclusions
by using protection macros
XSCUGIC_MAX_NUM_INTR_INPUTS
Maximum number of interrupt defined by Zynq Ultrascale Mp.
Referenced by LowInterruptHandler, XScuGic_CfgInitialize, XScuGic_InterruptHandler, XScuGic_Stop, XScuGic_UnmapAllInterruptsFromCpu, XScuGic_UnmapAllInterruptsFromCpuByDistAddr.
XSCUGIC_SPI_INT_ID_START
First Interrupt Id for SPI interrupts.
Referenced by XScuGic_Disable, XScuGic_DisableIntr, XScuGic_Enable, XScuGic_EnableIntr, XScuGic_GetPriorityTriggerType, XScuGic_GetPriTrigTypeByDistAddr, XScuGic_InterruptMapFromCpuByDistAddr, XScuGic_InterruptMaptoCpu, XScuGic_InterruptUnmapFromCpu, XScuGic_InterruptUnmapFromCpuByDistAddr, XScuGic_SetPriorityTriggerType, XScuGic_SetPriTrigTypeByDistAddr.
XSCUGIC_MAX_INTR_PRIO_VAL
The maximum priority value that can be used in the GIC.
Referenced by XScuGic_SetPriorityTriggerType, XScuGic_SetPriTrigTypeByDistAddr.
XSCUGIC_INTR_PRIO_MASK
The Interrupt priority mask value.
Referenced by XScuGic_SetPriorityTriggerType, XScuGic_SetPriTrigTypeByDistAddr.
XSCUGIC_PEND_INTID_MASK
Pending Interrupt ID.
XSCUGIC_PCELL_ID
PCELL ID value.
Referenced by XScuGic_SelfTest.