xscugic.h
EFUSE_STATUS_OFFSET
EFUSE_STATUS_CPU_MASK
ARMA9
ARMA9 macro to identify cortexA9.
XSCUGIC500_DCTLR_ARE_NS_ENABLE
XSCUGIC500_DCTLR_ARE_S_ENABLE
XScuGic_CPUWriteReg
Writes the given CPU Interface register.
InstancePtr Pointer to the instance to be worked on. RegOffset Register offset to be written. Data 32-bit value to write to the register. None. C-style signature: void XScuGic_CPUWriteReg(XScuGic *InstancePtr, u32 RegOffset, u32 Data)
Referenced by XScuGic_InterruptHandler.
XScuGic_CPUReadReg
Reads the given CPU Interface register.
InstancePtr Pointer to the instance to be worked on. RegOffset Rregister offset to be read. 32-bit value of the register C-style signature: u32 XScuGic_CPUReadReg(XScuGic *InstancePtr, u32 RegOffset)
Referenced by XScuGic_InterruptHandler.
XScuGic_DistWriteReg
Writes the given Distributor Interface register.
InstancePtr Pointer to the instance to be worked on. RegOffset Register offset to be written. Data 32-bit value to write to the register. None. C-style signature: void XScuGic_DistWriteReg(XScuGic *InstancePtr, u32 RegOffset, u32 Data)
Referenced by XScuGic_Disable, XScuGic_Disconnect, XScuGic_Enable, XScuGic_InterruptMaptoCpu, XScuGic_InterruptUnmapFromCpu, XScuGic_SetPriorityTriggerType, XScuGic_SoftwareIntr, XScuGic_Stop, XScuGic_UnmapAllInterruptsFromCpu.
XScuGic_DistReadReg
Reads the given Distributor Interface register.
InstancePtr Pointer to the instance to be worked on. RegOffset Register offset to be read. The 32-bit value of the register. C-style signature: u32 XScuGic_DistReadReg(XScuGic *InstancePtr, u32 RegOffset)
Referenced by XScuGic_GetPriorityTriggerType, XScuGic_InterruptMaptoCpu, XScuGic_InterruptUnmapFromCpu, XScuGic_SelfTest, XScuGic_SetPriorityTriggerType, XScuGic_Stop, XScuGic_UnmapAllInterruptsFromCpu.
XScuGic_Config XScuGic_ConfigTable[][]
Config table.
Config table.The XScuGic driver must know when to acknowledge the interrupt. The entry which specifies this as a bit mask where each bit corresponds to a specific interrupt. A bit set indicates to ACK it before servicing it. Generally, acknowledge before service is used when the interrupt signal is edge-sensitive, and after when the signal is level-sensitive.Refer to the XScuGic_Config data structure in xscugic.h for details on how this table should be initialized.
Referenced by XScuGic_DeviceInterruptHandler, XScuGic_LookupConfig.
s32 XScuGic_Connect(XScuGic *InstancePtr, u32 Int_Id, Xil_InterruptHandler Handler, void *CallBackRef)
Makes the connection between the Int_Id of the interrupt source and the associated handler that is to run when the interrupt is recognized.
The argument provided in this call as the Callbackref is used as the argument for the handler when it is called. InstancePtr Pointer to the XScuGic instance. Int_Id contains the ID of the interrupt source and should be in the range of 0 to XSCUGIC_MAX_NUM_INTR_INPUTS - 1 Handler Handler for interrupt. CallBackRef Instance pointer of the connecting driver. - XST_SUCCESS if the handler was connected correctly. WARNING: The handler provided as an argument will overwrite any handler that was previously connected.
References XScuGic::Config, XScuGic_Config::HandlerTable, XScuGic::IsReady.
Referenced by ScuGicExample.
void XScuGic_Disconnect(XScuGic *InstancePtr, u32 Int_Id)
Updates the interrupt table with the Null Handler and NULL arguments at the location pointed at by the Int_Id.
This effectively disconnects that interrupt source from any handler. The interrupt is disabled also. InstancePtr Pointer to the XScuGic instance to be worked on. Int_Id Contains the ID of the interrupt source and should be in the range of 0 to XSCUGIC_MAX_NUM_INTR_INPUTS - 1 None.
References XScuGic::Config, XScuGic_Config::HandlerTable, XScuGic::IsReady, XSCUGIC_DISABLE_OFFSET, XScuGic_DistWriteReg.
void XScuGic_Enable(XScuGic *InstancePtr, u32 Int_Id)
Enables the interrupt source provided as the argument Int_Id.
Any pending interrupt condition for the specified Int_Id will occur after this function is called. This API also maps the interrupt to the requesting CPU. InstancePtr Pointer to the XScuGic instance. Int_Id Contains the ID of the interrupt source and should be in the range of 0 to XSCUGIC_MAX_NUM_INTR_INPUTS - 1 None.
References XScuGic::IsReady, XScuGic_DistWriteReg, XSCUGIC_ENABLE_SET_OFFSET, XScuGic_InterruptMaptoCpu, XSCUGIC_SPI_INT_ID_START.
Referenced by ScuGicExample.
void XScuGic_Disable(XScuGic *InstancePtr, u32 Int_Id)
Disables the interrupt source provided as the argument Int_Id such that the interrupt controller will not cause interrupts for the specified Int_Id.
The interrupt controller will continue to hold an interrupt condition for the Int_Id, but will not cause an interrupt. This API also unmaps the interrupt for the requesting CPU. InstancePtr Pointer to the XScuGic instance. Int_Id Contains the ID of the interrupt source and should be in the range of 0 to XSCUGIC_MAX_NUM_INTR_INPUTS - 1 None.
References XScuGic::IsReady, XSCUGIC_DISABLE_OFFSET, XScuGic_DistWriteReg, XScuGic_InterruptUnmapFromCpu, XSCUGIC_SPI_INT_ID_START.
s32 XScuGic_CfgInitialize(XScuGic *InstancePtr, XScuGic_Config *ConfigPtr, u32 EffectiveAddr)
CfgInitialize a specific interrupt controller instance/driver.
The initialization entails: Initialize fields of the XScuGic structureInitial vector table with stub function callsAll interrupt sources are disabled InstancePtr Pointer to the XScuGic instance. ConfigPtr Pointer to a config table for the particular device this driver is associated with. EffectiveAddr Device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, use Config->BaseAddress for this parameters, passing the physical address instead. XST_SUCCESS if initialization was successful
References XScuGic::Config, XScuGic_Config::DistBaseAddress, XScuGic_Config::HandlerTable, XScuGic::IsReady, XSCUGIC_MAX_NUM_INTR_INPUTS, XScuGic_Stop.
Referenced by ScuGicExample, ScuGicInterruptSetup, ScuGicSelfTestExample.
s32 XScuGic_SoftwareIntr(XScuGic *InstancePtr, u32 Int_Id, u32 Cpu_Identifier)
Allows software to simulate an interrupt in the interrupt controller.
This function will only be successful when the interrupt controller has been started in simulation mode. A simulated interrupt allows the interrupt controller to be tested without any device to drive an interrupt input signal into it. InstancePtr Pointer to the XScuGic instance. Int_Id Software interrupt ID to simulate an interrupt. Cpu_Identifier List of CPUs to send the interrupt. For VERSAL_NET bits 0-7 specifies core ID to send the interrupt. bits 8-15 specifies the cluster id. XST_SUCCESS if successful, or XST_FAILURE if the interrupt could not be simulated
References XScuGic::IsReady, XScuGic_DistWriteReg, XSCUGIC_SFI_TRIG_CPU_MASK, XSCUGIC_SFI_TRIG_INTID_MASK, XSCUGIC_SFI_TRIG_OFFSET.
Referenced by ScuGicExample.
void XScuGic_GetPriorityTriggerType(XScuGic *InstancePtr, u32 Int_Id, u8 *Priority, u8 *Trigger)
Gets the interrupt priority and trigger type for the specificd IRQ source.
InstancePtr Pointer to the instance to be worked on. Int_Id IRQ source number to modify. Priority Pointer to the value of the priority of the IRQ source. This is a return value. Trigger Pointer to the value of the trigger of the IRQ source. Pointer to the value of the trigger of the IRQ source.
References XScuGic::IsReady, XScuGic_DistReadReg, XSCUGIC_INT_CFG_MASK, XSCUGIC_INT_CFG_OFFSET_CALC, XSCUGIC_PRIORITY_MASK, XSCUGIC_PRIORITY_OFFSET_CALC, XSCUGIC_RDIST_INT_CONFIG_OFFSET_CALC, XSCUGIC_RDIST_INT_PRIORITY_OFFSET_CALC, XSCUGIC_SPI_INT_ID_START.
void XScuGic_SetPriorityTriggerType(XScuGic *InstancePtr, u32 Int_Id, u8 Priority, u8 Trigger)
Sets the interrupt priority and trigger type for the specificd IRQ source.
InstancePtr Pointer to the instance to be worked on. Int_Id IRQ source number to modify. Priority New priority for the IRQ source. 0 is highest priority, 0xF8(248) is lowest. There are 32 priority levels supported with a step of 8. Hence the supported priorities are 0, 8, 16, 32, 40 ..., 248. Trigger New trigger type for the IRQ source. Each bit pair describes the configuration for an INT_ID. SFI Read Only b10 always PPI Read Only depending on how the PPIs are configured. b01 Active HIGH level sensitive b11 Rising edge sensitive SPI LSB is read only. b01 Active HIGH level sensitive b11 Rising edge sensitive/ None.
References XScuGic::IsReady, XScuGic_DistReadReg, XScuGic_DistWriteReg, XSCUGIC_INT_CFG_MASK, XSCUGIC_INT_CFG_OFFSET_CALC, XSCUGIC_INTR_PRIO_MASK, XSCUGIC_MAX_INTR_PRIO_VAL, XSCUGIC_PRIORITY_MASK, XSCUGIC_PRIORITY_OFFSET_CALC, XSCUGIC_RDIST_INT_CONFIG_OFFSET_CALC, XSCUGIC_RDIST_INT_PRIORITY_OFFSET_CALC, XSCUGIC_SPI_INT_ID_START.
void XScuGic_InterruptMaptoCpu(XScuGic *InstancePtr, u8 Cpu_Identifier, u32 Int_Id)
Sets the target CPU for the interrupt of a peripheral.
InstancePtr Pointer to the instance to be worked on. Cpu_Identifier CPU number for which the interrupt has to be targeted For VERSAL_NET APU: 0 t0 3 bits specifies core id and 4 to 7 bits specifies cluster id of the targeted core. Int_Id IRQ source number to modify. None.
References XScuGic_DistReadReg, XScuGic_DistWriteReg, XSCUGIC_IROUTER_OFFSET_CALC, XSCUGIC_SPI_INT_ID_START, XSCUGIC_SPI_TARGET_OFFSET_CALC.
Referenced by XScuGic_Enable.
void XScuGic_InterruptUnmapFromCpu(XScuGic *InstancePtr, u8 Cpu_Identifier, u32 Int_Id)
Unmaps specific SPI interrupt from the target CPU.
InstancePtr Pointer to the instance to be worked on. Cpu_Identifier CPU number from which the interrupt has to be unmapped. For VERSAL_NET APU: 0 t0 3 bits specifies core id and 4 to 7 bits specifies cluster id of the targeted core. Int_Id IRQ source number to modify None.
References XScuGic_DistReadReg, XScuGic_DistWriteReg, XSCUGIC_SPI_INT_ID_START, XSCUGIC_SPI_TARGET_OFFSET_CALC.
Referenced by XScuGic_Disable.
void XScuGic_UnmapAllInterruptsFromCpu(XScuGic *InstancePtr, u8 Cpu_Identifier)
Unmaps all SPI interrupts from the target CPU.
InstancePtr Pointer to the instance to be worked on. Cpu_Identifier CPU number from which the interrupts has to be unmapped. None.
References XScuGic_DistReadReg, XScuGic_DistWriteReg, XSCUGIC_MAX_NUM_INTR_INPUTS, XSCUGIC_SPI_TARGET_OFFSET_CALC.
void XScuGic_Stop(XScuGic *InstancePtr)
Checks if the interrupt target register contains all interrupts to be targeted for current CPU.
If they are programmed to be forwarded to current cpu, this API disable all interrupts and disable GIC distributor. This API also removes current CPU from interrupt target registers for all interrupt. InstancePtr Pointer to the instance to be worked on. None.
References XSCUGIC_DISABLE_OFFSET, XSCUGIC_DIST_EN_OFFSET, XScuGic_DistReadReg, XScuGic_DistWriteReg, XSCUGIC_EN_DIS_OFFSET_CALC, XSCUGIC_EN_INT_MASK, XSCUGIC_IROUTER_OFFSET_CALC, XSCUGIC_MAX_NUM_INTR_INPUTS, XSCUGIC_SPI_TARGET_OFFSET_CALC.
Referenced by XScuGic_CfgInitialize.
void XScuGic_SetCpuID(u32 CpuCoreId)
Updates the CpuId global variable.
CpuCoreId CPU core number. None.
u32 XScuGic_GetCpuID(void)
Returns the CpuId variable.
The CPU core number.
Referenced by XScuGic_DisableIntr, XScuGic_EnableIntr.
u8 XScuGic_IsInitialized(u32 BaseAddress)
Checks whether the XScGic is initialized or not given the device ID/BaseAddress.
BaseAddress is the base address of the device Returns 1 if initialized otherwise 0. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XScuGic_Config::DistBaseAddress, XSCUGIC_DIST_EN_OFFSET, XSCUGIC_EN_INT_MASK, XScuGic_LookupConfig, XScuGic_ReadReg.
XScuGic_Config * XScuGic_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
A table contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the XScuGic configuration structure for the specified device, or NULL if the device ID/BaseAddress is not found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XScuGic_Config::Name, XScuGic_ConfigTable.
Referenced by ScuGicExample, ScuGicInterruptSetup, ScuGicSelfTestExample, XScuGic_DeviceInitialize, XScuGic_IsInitialized.
void XScuGic_InterruptHandler(XScuGic *InstancePtr)
This function is the primary interrupt handler for the driver.
It must be connected to the interrupt source such that it is called when an interrupt of the interrupt controller is active. It will resolve which interrupts are active and enabled and call the appropriate interrupt handler. It uses the Interrupt Type information to determine when to acknowledge the interrupt. Highest priority interrupts are serviced first.This function assumes that an interrupt vector table has been previously initialized. It does not verify that entries in the table are valid before calling an interrupt handler. InstancePtr Pointer to the XScuGic instance. None.
References XScuGic::Config, XScuGic_Config::HandlerTable, XSCUGIC_ACK_INTID_MASK, XScuGic_CPUReadReg, XScuGic_CPUWriteReg, XSCUGIC_EOI_OFFSET, XSCUGIC_INT_ACK_OFFSET, XSCUGIC_MAX_NUM_INTR_INPUTS.
Referenced by ScuGicInterruptSetup, SetUpInterruptSystem.
s32 XScuGic_SelfTest(XScuGic *InstancePtr)
Runs a self-test on the driver/device.
This test reads the ID registers and compares them. InstancePtr Pointer to the XScuGic instance. -XST_SUCCESS if self-test is successful. -XST_FAILURE if the self-test is not successful.
References XScuGic::IsReady, XScuGic_DistReadReg, XSCUGIC_PCELL_ID, XSCUGIC_PCELLID_OFFSET.
Referenced by ScuGicExample.
XSCUGIC_H
< prevent circular inclusions
by using protection macros