xscugic_example.c
XSCUGiC_DIST_BASEADDR
INTC_DEVICE_INT_ID
XSCUGIC_SPI_CPU_MASK
XSCUGIC_SW_TIMEOUT_VAL
XScuGic InterruptController
volatile u32 InterruptProcessed
int ScuGicExample(void)
This function is an example of how to use the interrupt controller driver (XScuGic) and the hardware device.
This function is designed to work without any hardware devices to cause interrupts. It may not return if the interrupt controller is not properly connected to the processor in either software or hardware.This function relies on the fact that the interrupt controller hardware has come out of the reset state such that it will allow interrupts to be simulated by the software. None XST_SUCCESS to indicate success, otherwise XST_FAILURE In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XScuGic_Config::CpuBaseAddress, DeviceDriverHandler, SetUpInterruptSystem, XScuGic_CfgInitialize, XScuGic_Connect, XScuGic_Enable, XScuGic_LookupConfig, XScuGic_SelfTest, XScuGic_SoftwareIntr, XSCUGIC_SPI_CPU0_MASK.
Referenced by main.
int SetUpInterruptSystem(XScuGic *XScuGicInstancePtr)
This function connects the interrupt handler of the interrupt controller to the processor.
This function is separate to allow it to be customized for each application. Each processor or RTOS may require unique processing to connect the interrupt handler. XScuGicInstancePtr is the instance of the interrupt controller that needs to be worked on. None. None.
References XScuGic_InterruptHandler.
Referenced by ScuGicExample.
void DeviceDriverHandler(void *CallbackRef)
This function is designed to look like an interrupt handler in a device driver.
This is typically a 2nd level handler that is called from the interrupt controller interrupt handler. This handler would typically perform device specific processing such as reading and writing the registers of the device to clear the interrupt condition and pass any data to an application using the device driver. Many drivers already provide this handler and the user is not required to create it. CallbackRef is passed back to the device driver's interrupt handler by the XScuGic driver. It was given to the XScuGic driver in the XScuGic_Connect() function call. It is typically a pointer to the device driver instance variable. In this example, we do not care about the callback reference, so we passed it a 0 when connecting the handler to the XScuGic driver and we make no use of it here. None. None.
Referenced by ScuGicExample.
static void AssertPrint(const char8 *FilenamePtr, s32 LineNumber)
int main(void)
This is the main function for the Interrupt Controller example.
None. XST_SUCCESS to indicate success, otherwise XST_FAILURE. None.
References ScuGicExample.