xscugic_sinit.c
XScuGic_Config * XScuGic_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
A table contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the XScuGic configuration structure for the specified device, or NULL if the device ID/BaseAddress is not found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XScuGic_Config::Name, XScuGic_ConfigTable.
Referenced by ScuGicExample, ScuGicInterruptSetup, ScuGicSelfTestExample, XScuGic_DeviceInitialize, XScuGic_IsInitialized.