xv_sditx.h
XV_SdiTx_HandlerType
XV_SdiTx_State
XV_SdiTx_StreamSelId
XV_SdiTx_DebugSelId
XV_SdiTx_CoreSelId
XV_SdiTx_MuxPattern
XV_SdiTx_PayloadLineNum1
XV_SdiTx_PayloadLineNum2
XV_SdiTx_Config* XV_SdiTx_LookupConfig(UINTPTR BaseAddress)
This function returns a reference to an XV_SdiTx_Config structure based on the core id, DeviceId.
The return value will refer to an entry in the device configuration table defined in the xv_sditx_g.c file. DeviceId is the unique core ID of the SDI TX core for the lookup operation. XV_SdiTx_LookupConfig returns a reference to a config record in the configuration table (in xv_sditx_g.c) corresponding to DeviceId, or NULL if no match is found. None.
Referenced by XV_SdiTxSelfTestExample.
int XV_SdiTx_CfgInitialize(XV_SdiTx *InstancePtr, XV_SdiTx_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the SDI TX core.
This function must be called prior to using the SDI TX core. Initialization of the SDI TX includes setting up the instance data and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the XV_SdiTx core instance. CfgPtr points to the configuration structure associated with the SDI TX core. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if XV_SdiTx_CfgInitialize was successful.XST_FAILURE if SDI TX initialization failed None.
References XV_SdiTx::Axi4sVidLockCallback, XV_SdiTx_Config::BaseAddress, XV_SdiTx::CeAlignErrCallback, XV_SdiTx::Config, XV_SdiTx::GtRstDoneCallback, XV_SdiTx::IsReady, XV_SdiTx::OverFlowCallback, XV_SdiTx::State, XV_SdiTx::UnderFlowCallback, XV_SdiTx_Reset, XV_SdiTx_SetCoreSettings, XV_SdiTx_StopSdi.
Referenced by XV_SdiTxSelfTestExample.
void XV_SdiTx_Reset(XV_SdiTx *InstancePtr)
This function clears the SDI TX core registers and sets them to the defaults.
InstancePtr is a pointer to the XV_SdiTx core instance. This is required after a reset or init.
References XV_SdiTx_ClearPayloadId.
Referenced by XV_SdiTx_CfgInitialize.
void XV_SdiTx_ClearPayloadId(XV_SdiTx *InstancePtr)
This function clears the SDI TX PayloadId.
InstancePtr is a pointer to the XV_SdiTx core instance. This is required after a reset or init.
References XV_SdiTx_SetPayloadId.
Referenced by XV_SdiTx_Reset.
u32 XV_SdiTx_SetStream(XV_SdiTx *InstancePtr, XV_SdiTx_StreamSelId SelId, u32 Data, u8 StreamId)
This function sets the SDI TX stream parameters.
InstancePtr is a pointer to the XV_SdiTx core instance. SelId specifies which parameter of the stream to be set. 0 = XV_SDITX_STREAMSELID_VMID1 = XV_SDITX_STREAMSELID_COLORFORMAT2 = XV_SDITX_STREAMSELID_BPC3 = XV_SDITX_STREAMSELID_PPC4 = XV_SDITX_STREAMSELID_ASPECTRATIO5 = XV_SDITX_STREAMSELID_STANDARD6 = XV_SDITX_STREAMSELID_STREAMINTERLACE7 = XV_SDITX_STREAMSELID_CHANNEL Data specifies what data to be set for the selected parameter. StreamId specifies which of the streams to be set. XST_SUCCESS on successful Set stream XST_FAILURE if TimingPtr is not derived None.
References XV_SdiTx_Stream::CAssignment, XV_SdiTx::Stream, XV_SdiTx_Stream::Video.
void XV_SdiTx_StreamStart(XV_SdiTx *InstancePtr)
This function starts the TX SDI stream.
InstancePtr is a pointer to the XV_SdiTx core instance. None.
References XV_SdiTx_Config::BaseAddress, XV_SdiTx::bitdepth, XV_SdiTx::Config, XV_SdiTx::State, XV_SdiTx::Stream, XV_SdiTx::Transport, XV_SdiTx_Stream::Video, XV_SdiTx_ClearYCbCr444_RGB_10bit, XV_SdiTx_ReadReg, XV_SdiTx_SetPayloadId, XV_SdiTx_SetYCbCr444_RGB_10bit, XV_SdiTx_StartSdi.
void XV_SdiTx_StartSdi(XV_SdiTx *InstancePtr, XSdiVid_TransMode SdiMode, XSdiVid_BitRate IsFractional, XV_SdiTx_MuxPattern MuxPattern)
This function starts the SDI TX core.
InstancePtr is a pointer to the XV_SdiTx core instance. SdiMode specifies the SDI mode of the SDI TX. IsFractional specifies the bitrate of the SDI TX. MuxPattern specifies the data stream interleaving pattern to be used. None.
References XV_SdiTx_Config::BaseAddress, XV_SdiTx::Config, XV_SdiTx::Stream, XV_SdiTx_Stream::Video, XV_SdiTx_ClearDetectedError, XV_SdiTx_ReadReg, XV_SdiTx_WriteReg.
Referenced by XV_SdiTx_StreamStart.
int XV_SdiTx_StopSdi(XV_SdiTx *InstancePtr)
This function disables the SDI TX core.
InstancePtr is a pointer to the XV_SdiTx core instance. XST_SUCCESS if register write is successful for SDI stopXST_FAILURE if SDI stop write is failed None.
References XV_SdiTx_Config::BaseAddress, XV_SdiTx::Config, XV_SdiTx_ReadReg, XV_SdiTx_WriteReg.
Referenced by XV_SdiTx_CfgInitialize, XV_SdiTx_SelfTest.
int XV_SdiTx_SetVidFormat(XV_SdiTx *InstancePtr, XVidC_ColorFormat ColorFormat)
Sets the video format for the SDI transmitter.
InstancePtr Pointer to the XV_SdiTx instance. ColorFormat The color format to set. Status code indicating success or failure.
void XV_SdiTx_ReportDetectedError(XV_SdiTx *InstancePtr)
This function reports the detected error by the TX core.
InstancePtr is a pointer to the XV_SdiTx core instance. None.
References XV_SdiTx_Config::BaseAddress, XV_SdiTx::Config, XV_SdiTx_ReadReg.
void XV_SdiTx_ClearDetectedError(XV_SdiTx *InstancePtr)
This function clears the detected error flag and counter.
InstancePtr is a pointer to the XV_SdiTx core instance. None.
References XV_SdiTx_Config::BaseAddress, XV_SdiTx::Config, XV_SdiTx_ReadReg, XV_SdiTx_WriteReg.
Referenced by XV_SdiTx_StartSdi.
u32 XV_SdiTx_GetPayloadEotf(XV_SdiTx *InstancePtr, XVidC_Eotf Eotf, XVidC_ColorStd Colorimetry)
This function updates the eotf and colorimetry fields of st352 payload value for all SDI modes.
InstancePtr is a pointer to the XV_SdiTx core instance. Eotf is a variable of type XVidC_Eotf Colorimetry is a variable of type XVidC_ColorStd Updated payload value. This function depends on sdi mode(Transport.TMode) being set, to correctly calculate the payload
References XV_SdiTx::Transport.
Referenced by XV_SdiTx_GetPayload.
u32 XV_SdiTx_GetPayload(XV_SdiTx *InstancePtr, XVidC_VideoMode VideoMode, XSdiVid_TransMode SdiMode, u8 DataStream)
This function calculates the final st352 payload value for all SDI modes with given video mode and SDI data stream number.
InstancePtr is a pointer to the XV_SdiTx core instance. VideoMode is a variable of type XVidC_VideoMode. SdiMode is a variable of type XSdiVid_TransMode. DataStream is the stream number for which payload is calculated. XST_SUCCESS / XST_FAILURE. None.
References XV_SdiTx::bitdepth, XV_SdiTx_Stream::CAssignment, XV_SdiTx::Stream, XV_SdiTx::Transport, XV_SdiTx_Stream::Video, XV_SdiTx_GetPayloadAspectRatio, XV_SdiTx_GetPayloadByte1, XV_SdiTx_GetPayloadColorFormat, XV_SdiTx_GetPayloadEotf, XV_SdiTx_GetPayloadFrameRate, XV_SdiTx_GetPayloadIsInterlaced.
void XV_SdiTx_SetPayloadId(XV_SdiTx *InstancePtr, u8 DataStream, u32 Payload)
This function sets the payload id to be sent out by the TX core.
InstancePtr is a pointer to the XV_SdiTx core instance. DataStream specifies the stream which ST352 payload id is to be inserted. Payload specifies the data to be sent out as ST352 payload id. None.
References XV_SdiTx_WriteReg.
Referenced by XV_SdiTx_ClearPayloadId, XV_SdiTx_StreamStart.
void XV_SdiTx_SetPayloadLineNum(XV_SdiTx *InstancePtr, XV_SdiTx_PayloadLineNum1 Field1LineNum, XV_SdiTx_PayloadLineNum2 Field2LineNum, u8 Field2En)
This function sets the line number of which the HANC space will be inserted with ST 352 packets.
InstancePtr is a pointer to the XV_SdiTx core instance. Field1LineNum specifies the field 1 line number of which ST352 packets are to be inserted Field2LineNum specifies the field 2 line number of which ST352 packets are to be inserted Field2En specifies whether the TX core will send out ST352 packets in field 2 line number or not. None.
References XV_SdiTx_Config::BaseAddress, XV_SdiTx::Config, XV_SdiTx_ReadReg, XV_SdiTx_WriteReg.
void XV_SdiTx_SetCoreSettings(XV_SdiTx *InstancePtr, XV_SdiTx_CoreSelId SelId, u8 Data)
This function sets the SDI TX core settings.
InstancePtr is a pointer to the XV_SdiTx core instance. SelId specifies which parameter of the stream to be set. 0 = XV_SDITX_CORESELID_INSERTCRC1 = XV_SDITX_CORESELID_INSERTST3522 = XV_SDITX_CORESELID_ST352OVERWRITE3 = XV_SDITX_CORESELID_INSERTSYNCBIT4 = XV_SDITX_CORESELID_SDBITREPBYPASS5 = XV_SDITX_CORESELID_USEANCIN6 = XV_SDITX_CORESELID_INSERTLN7 = XV_SDITX_CORESELID_INSERTEDH Data specifies what data to be set for the selected parameter. None.
References XV_SdiTx_Config::BaseAddress, XV_SdiTx::Config, XV_SdiTx_ReadReg, XV_SdiTx_WriteReg.
Referenced by XV_SdiTx_CfgInitialize.
u8 XV_SdiTx_GetPayloadFrameRate(XVidC_FrameRate FrameRateValid, XSdiVid_BitRate BitRate)
This function calculates the equivalent payload nibble for Framerate.
FrameRateValid is a calculated framerate based on interlaced or progressive video. BitRate is a variable of type XSdiVid_BitRate. returns 4-bit value None.
Referenced by XV_SdiTx_GetPayload.
u8 XV_SdiTx_GetPayloadIsInterlaced(XVidC_VideoFormat VideoFormat)
This function calculates the equivalent payload bit for given VideoFormat.
VideoFormat is a variable of type XVidC_VideoFormat. returns 1-bit value None.
Referenced by XV_SdiTx_GetPayload.
u8 XV_SdiTx_GetPayloadAspectRatio(XVidC_AspectRatio AspectRatio)
This function calculates the equivalent payload bit for given AspectRatio.
AspectRatio is a variable of type XVidC_AspectRatio. returns 0 for 4x3 aspect ratioreturns 1 for 16x9 aspect ratio None.
Referenced by XV_SdiTx_GetPayload.
u32 XV_SdiTx_GetPayloadByte1(u16 VActiveValid, XSdiVid_TransMode SdiMode, u8 *Data)
This function calculates the 2nd byte of the Payload packet for all SDI modes.
VActiveValid is a variable for number of active vertical lines. SdiMode is a variable to the XSdiVid_TransMode. Data is a pointer to populate the Byte1 of ST352 payload. returns 8-bit value None.
Referenced by XV_SdiTx_GetPayload.
u8 XV_SdiTx_GetPayloadColorFormat(XSdiVid_TransMode SdiMode, XVidC_ColorFormat ColorFormatId)
This function calculates the Color Format for 3rd byte of the Payload packet for all SDI modes.
SdiMode is a variable to the XSdiVid_TransMode. ColorFormatId is a variable of type XVidC_ColorFormat. returns 8-bit value None.
Referenced by XV_SdiTx_GetPayload.
int XV_SdiTx_SetColorFormat(XV_SdiTx *InstancePtr, XVidC_ColorFormat ColorFormat)
This function Set the video format of the SDI TX core.
InstancePtr is a pointer to the XV_SdiTx core instance. ColorFormat is a variable of type XVidC_ColorFormat. XST_SUCCESS if register write is successful for SDI stopXST_FAILURE if SDI stop write is failed None.
References XV_SdiTx_Config::BaseAddress, XV_SdiTx::Config, XV_SdiTx::Transport, XV_SdiTx_ReadReg, XV_SdiTx_WriteReg.
void XV_SdiTx_ST352CStreamEnable(XV_SdiTx *InstancePtr)
This function enables the insertion of ST352 in C stream of the SDI TX Ss core.
InstancePtr is a pointer to the XV_SdiTx core instance. None.
References XV_SdiTx_Config::BaseAddress, XV_SdiTx::Config, XV_SdiTx_ReadReg, XV_SdiTx_WriteReg.
void XV_SdiTx_ST352CSwitch3GA(XV_SdiTx *InstancePtr)
This function enables the ST352 value to be used from DS2 instead of DS3 register in C stream of the SDI TX Ss core.
InstancePtr is a pointer to the XV_SdiTx core instance. None.
References XV_SdiTx_Config::BaseAddress, XV_SdiTx::Config, XV_SdiTx_ReadReg, XV_SdiTx_WriteReg.
void XV_SdiTx_VidBridgeEnable(XV_SdiTx *InstancePtr)
This function enables the video bridge.
InstancePtr is a pointer to the XV_SdiTx core instance. None.
References XV_SdiTx_Config::BaseAddress, XV_SdiTx::Config, XV_SdiTx_ReadReg, XV_SdiTx_WriteReg.
void XV_SdiTx_VidBridgeDisable(XV_SdiTx *InstancePtr)
This function disables the video bridge.
InstancePtr is a pointer to the XV_SdiTx core instance. None.
References XV_SdiTx_Config::BaseAddress, XV_SdiTx::Config, XV_SdiTx_ReadReg, XV_SdiTx_WriteReg.
void XV_SdiTx_Axi4sBridgeVtcEnable(XV_SdiTx *InstancePtr)
This function enables the AXI4S Bridge.
InstancePtr is a pointer to the XV_SdiTx core instance. None.
References XV_SdiTx_Config::BaseAddress, XV_SdiTx::Config, XV_SdiTx_ReadReg, XV_SdiTx_WriteReg.
void XV_SdiTx_Axi4sBridgeVtcDisable(XV_SdiTx *InstancePtr)
This function disables the AXI4S Bridge.
InstancePtr is a pointer to the XV_SdiTx core instance. None.
References XV_SdiTx_Config::BaseAddress, XV_SdiTx::Config, XV_SdiTx_ReadReg, XV_SdiTx_WriteReg.
void XV_SdiTx_SetVidBridgeMode(XV_SdiTx *InstancePtr, XSdiVid_TransMode Mode)
This function sets the video bridge mode.
InstancePtr is a pointer to the XV_SdiTx core instance. Mode specifies the SDI bridge mode. None.
References XV_SdiTx_Config::BaseAddress, XV_SdiTx::Config, XV_SdiTx::Transport, XV_SdiTx_ReadReg, XV_SdiTx_WriteReg.
void XV_SdiTx_DebugInfo(XV_SdiTx *InstancePtr, XV_SdiTx_DebugSelId SelId)
This function prints stream and timing information on STDIO/Uart console.
InstancePtr is a pointer to the XV_SdiTx core instance. SelId specifies which debug information to be printed out None.
References XV_SdiTx_Config::BaseAddress, XV_SdiTx::Config, XV_SdiTx::Stream, XV_SdiTx::Transport, XV_SdiTx_Stream::Video, XV_SdiTx_ReadReg.
u32 XV_SdiTx_SelfTest(XV_SdiTx *InstancePtr)
Runs a self-test on the driver/device.
This test checks if the mode control register values have the default values. InstancePtr is a pointer to the XV_SdiTx instance. XST_SUCCESS if self-test was successfulXST_FAILURE if the read value was not equal to _g.c file None
References XV_SdiTx::IsReady, XV_SdiTx_StopSdi, XV_SdiTx_ReadReg, XV_SdiTx::Config, XV_SdiTx_Config::BaseAddress.
Referenced by XV_SdiTxSelfTestExample.
u32 XV_SdiTx_GetIntrEnable(XV_SdiTx *InstancePtr)
This function will get the interrupt mask set (enabled) in the SDI Tx core.
InstancePtr is the XV_SdiTx instance to operate on Interrupt Mask with bits set for corresponding interrupt in Interrupt enable register None
References XV_SdiTx_Config::BaseAddress, XV_SdiTx::Config, XV_SdiTx_ReadReg.
u32 XV_SdiTx_GetIntrStatus(XV_SdiTx *InstancePtr)
This function will get the list of interrupts pending in the Interrupt Status Register of the SDI Tx core.
InstancePtr is the XV_SdiTx instance to operate on Interrupt Mask with bits set for corresponding interrupt in Interrupt Status register None
References XV_SdiTx_Config::BaseAddress, XV_SdiTx::Config, XV_SdiTx_ReadReg.
Referenced by XV_SdiTx_IntrHandler.
void XV_SdiTx_InterruptClear(XV_SdiTx *InstancePtr, u32 Mask)
This function will clear the interrupts set in the Interrupt Status Register of the SDI Tx core.
InstancePtr is the XV_SdiTx instance to operate on Mask is Interrupt Mask with bits set for corresponding interrupt to be cleared in the Interrupt Status register None
References XV_SdiTx_Config::BaseAddress, XV_SdiTx::Config, XV_SdiTx_ReadReg, XV_SdiTx_WriteReg.
Referenced by XV_SdiTx_IntrHandler.
void XV_SdiTx_IntrHandler(void *InstancePtr)
This function is the interrupt handler for the SDI TX driver.
This handler reads the pending interrupt for GT reset done interrupt from Tx IP, determines the source of the interrupts, clears the interrupts and calls callbacks accordingly.The application is responsible for connecting this function to the interrupt system. Application beyond this driver is also responsible for providing callbacks to handle interrupts and installing the callbacks using XV_SdiTx_SetCallback() during initialization phase. An example delivered with this driver demonstrates how this could be done. InstancePtr is a pointer to the XV_SdiTx instance that just interrupted. None.
References XV_SdiTx_Config::BaseAddress, XV_SdiTx::Config, XV_SdiTx::IsReady, XV_SdiTx_GetIntrStatus, XV_SdiTx_InterruptClear, XV_SdiTx_ReadReg.
int XV_SdiTx_SetCallback(XV_SdiTx *InstancePtr, u32 HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function Type ------------------------- ------------------------------------------- (XV_SDITX_HANDLER_GTRESET_DONE) GtRstDoneCallback (XV_SDITX_HANDLER_OVERFLOW) OverFlowCallback (XV_SDITX_HANDLER_UNDERFLOW) UnderFlowCallback InstancePtr is a pointer to the SDI TX core instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XV_SdiTx::Axi4sVidLockCallback, XV_SdiTx::Axi4sVidLockRef, XV_SdiTx::CeAlignErrCallback, XV_SdiTx::CeAlignErrRef, XV_SdiTx::GtRstDoneCallback, XV_SdiTx::GtRstDoneRef, XV_SdiTx::OverFlowCallback, XV_SdiTx::OverFlowRef, XV_SdiTx::UnderFlowCallback, XV_SdiTx::UnderFlowRef.
void XV_SdiTx_IntrDisable(XV_SdiTx *InstancePtr, u32 Mask)
This function disables the selected interrupt.
InstancePtr is a pointer to the XV_SdiTx core instance. Mask to be disabled. None.
References XV_SdiTx_Config::BaseAddress, XV_SdiTx::Config, XV_SdiTx_WriteReg.
void XV_SdiTx_IntrEnable(XV_SdiTx *InstancePtr, u32 Mask)
This function enables the selected interrupt.
InstancePtr is a pointer to the XV_SdiTx core instance. Mask to be enabled. None.
References XV_SdiTx_Config::BaseAddress, XV_SdiTx::Config, XV_SdiTx_ReadReg, XV_SdiTx_WriteReg.
void XV_SdiTx_SetYCbCr444_RGB_10bit(XV_SdiTx *InstancePtr)
This function enables 10bit YUV444 color format support for SDI Tx.
InstancePtr is a pointer to the XV_SdiTx core instance.
References XV_SdiTx_Config::BaseAddress, XV_SdiTx::Config, XV_SdiTx_ReadReg, XV_SdiTx_WriteReg.
Referenced by XV_SdiTx_StreamStart.
void XV_SdiTx_ClearYCbCr444_RGB_10bit(XV_SdiTx *InstancePtr)
This function disables 10bit YUV444 color format support for SDI Tx.
InstancePtr is a pointer to the XV_SdiTx core instance.
References XV_SdiTx_Config::BaseAddress, XV_SdiTx::Config, XV_SdiTx_ReadReg, XV_SdiTx_WriteReg.
Referenced by XV_SdiTx_StreamStart.
void XV_SdiTx_Set_Bpc(XV_SdiTx *InstancePtr, XVidC_ColorDepth bitdepth)
This function sets the video bit depth of SDI-TX and configures dynamic BPC support.
InstancePtr is a pointer to the XV_SdiTx core instance. bitdepth is the video bit depth to be set for SDI-TX. None.
References XV_SdiTx::bitdepth.
XV_SDITX_H_
Prevent circular inclusions by using protection macros.
XV_SDITX_MAX_DATASTREAM
XV_SDITX_COLORFORMAT
XV_SDITX_COLORDEPTH_10
XV_SDITX_COLORDEPTH_12
XV_SdiTx_GetVersion
This macro reads the TX version.
InstancePtr is a pointer to the XV_SdiTX core instance. None.
XV_SdiTx_VidLckIntrClr
This macro clears the video lock interrupt.
InstancePtr is a pointer to the XV_SdiTX core instance.
XV_SdiTx_VidUnlckIntrClr
This macro clears the video unlock interrupt.
InstancePtr is a pointer to the XV_SdiTX core instance.
typedef void(* XV_SdiTx_Callback)(void *CallbackRef))(void *CallbackRef)
Callback type for interrupt.
CallbackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. None. None.