v_sditxss
XV_SdiTxSs SdiTxSsInst
int XV_SdiTxSs_SubcoreInitSdiTx(XV_SdiTxSs *SdiTxSsPtr)
This function initializes the included sub-core to it's static configuration.
SdiTxSsPtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS/XST_FAILURE
References XV_SdiTxSs::Config, XV_SdiTxSs_Config::SdiTx, XV_SdiTxSs::SdiTxPtr, XV_SDITXSS_LOG_EVT_SDITX_INIT, XV_SdiTxSs_LogWrite.
Referenced by XV_SdiTxSs_CfgInitialize.
int XV_SdiTxSs_SubcoreInitVtc(XV_SdiTxSs *SdiTxSsPtr)
This function initializes the included sub-core to it's static configuration.
SdiTxSsPtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS/XST_FAILURE
References XV_SdiTxSs::Config, XV_SdiTxSs_Config::Vtc, XV_SdiTxSs::VtcPtr, XV_SDITXSS_LOG_EVT_VTC_INIT, XV_SdiTxSs_LogWrite.
Referenced by XV_SdiTxSs_CfgInitialize.
u32 XV_SdiTxSs_SelfTest(XV_SdiTxSs *InstancePtr)
This function performs self test on SDI Tx Subsystem sub-cores.
InstancePtr is a pointer to the XV_SdiTxSs core instance. XST_SUCCESS if self test passed.XST_FAILURE if self test failed. None.
References XV_SdiTxSs::SdiTxPtr.
Referenced by SdiTxSs_SelfTestExample.
u32 SdiTxSs_SelfTestExample(UINTPTR BaseAddress)
This function is the main entry point for the self test example using the XV_SdiTxSs driver.
This function check whether or not its sub-core drivers self test functions are in working state. DeviceId is the unique device ID of the SDI TX Subsystem core. XST_FAILURE if any of SDI TX Subsystem sub-core self test failed.XST_SUCCESS, if all of SDI TX Subsystem sub-core self test passed. None.
References XV_SdiTxSs_Config::BaseAddress, XV_SdiTxSs_CfgInitialize, XV_SdiTxSs_LookupConfig, XV_SdiTxSs_SelfTest.
Referenced by main.
int main(void)
This is the main function for XV_SdiTxSs self test example.
None. XST_SUCCESS if the self test example passed.XST_FAILURE if the self test example was unsuccessful. None.
References SdiTxSs_SelfTestExample.
XV_SDITXSS_COREINIT_H__