si570drv.c
PHASE_WORD_BYTE_6
PHASE_WORD_BYTE_8
PHASE_WORD_BYTE_10
MAX_REGISTERS
int Si570_DoSettings(u32 IICBaseAddress, u8 IICAddress1, u8 *BufPtr, int NumRegs)
Send a list of register settings to the Si570 clock generator.
IICBaseAddress contains the base address of the IIC master device. IICAddress1 contains the 7 bit IIC address of the Si570 device. BufPtr is a pointer to an array with alternating register addresses and register values to program into the Si570. The array length must be at least 2*NumRegs. NumRegs contains the number of registers to write. SI570_SUCCESS for successSI570_ERR_IIC for IIC access failure,SI570_ERR_FREQ when the requested frequency cannot be generatedSI570_ERR_PARM when the ClkSrc or ClkDest parameters are invalid or the ClkInFreq or ClkOutFreq are out of range. Private function. Does not modify the contents of the buffer pointed to by BufPtr.
References SI570_DEBUG, SI570_ERR_IIC, SI570_ERR_PARM, SI570_SUCCESS.
Referenced by Si570_SetClock.
int Si570_SetClock(u32 IICBaseAddress, u8 IICAddress1, u32 RxRefClk)
Set the output frequency of the Si570 clock generator.
IICBaseAddress contains the base address of the IIC master device. IICAddress1 contains the 7 bit IIC address of the Si570 device. RxRefClk contains the value to be written in Si570 register for that particular clock frequency. SI570_SUCCESS for successSI570_ERR_IIC for IIC access failure,SI570_ERR_FREQ when the requested frequency cannot be generatedSI570_ERR_PARM when the ClkSrc or ClkDest parameters are invalid or the ClkInFreq or ClkOutFreq are out of range.
References SI570_DEBUG, Si570_DoSettings.
Referenced by main, RxStreamUpCallback.