xsdi_example.c
PAGE_SIZE
I2C_MUX_ADDR
I2C Mux Address.
I2C_CLK_ADDR
I2C Clk Address.
I2C_CLK_ADDR_570
I2C Clk Address for Si570.
Referenced by main, RxStreamUpCallback.
FREQ_SI570_148_5_MHz
FREQ_297_MHz
FREQ_74_25_MHz
FREQ_27_MHz
FREQ_SI570_148_35_MHz
RX_GPIO_OFFSET
TX_GPIO_OFFSET
PICXO_GPIO_OFFSET
GT_GPIO_OFFSET
SI570_GPIO_OFFSET
DISABLE_GPIO
ENABLE_GPIO
DISABLE_FIFO
ENABLE_FIFO
DISABLE
ENABLE
ONE_US
TEN_US
HUNDERED_MS
MAX_STREAMS
XSDIAUD_QUAD_GROUP
UART_BASEADDR
typedef u8 AddressType
u8 WriteBuffer[sizeof(AddressType)+PAGE_SIZE][sizeof(AddressType)+PAGE_SIZE]
u8 ReadBuffer[PAGE_SIZE][PAGE_SIZE]
volatile u8 TransmitComplete
volatile u8 ReceiveComplete
unsigned int IntrReceived
XIicPs Iic
XGpio Gpio_AxisFifo_resetn
XGpio_Config* Gpio_AxisFifo_resetn_ConfigPtr
XGpio Gpio_Rx_resetn
XGpio_Config* Gpio_Rx_resetn_ConfigPtr
XGpio Gpio_Tx_resetn
XGpio_Config* Gpio_Tx_resetn_ConfigPtr
XGpio Gpio_Picxo_resetn
XGpio_Config* Gpio_Picxo_resetn_ConfigPtr
XGpio Gpio_si570
XGpio_Config* Gpio_si570_ConfigPtr
XV_SdiTxSs SdiTxSs
XV_SdiTxSs_Config* XV_SdiTxSs_ConfigPtr
XV_SdiRxSs SdiRxSs
XV_SdiRxSs_Config* XV_SdiRxSs_ConfigPtr
u8 StartTxAfterRxFlag
XSdi_Menu SdiMenu
Menu structure.
u32 Index
u32 MaxIndex
u8 PayloadStatus
void ClearScreen(void)
This function Clears Uart terminal screen.
None None.
Referenced by main.
static void GtReadyCallback(void *CallbackRef)
This function is called when the GT reset is done and it starts SDI Tx Subsystem.
CallbackRef is a callback function reference. None. None.
void RxStreamUpCallback(void *CallbackRef)
This function is called when the RX Lock occurs, it calculates the frequency wrt RxTransMode, programs SI570 with the calculated frequency and then enables Rx stream flow IPs.
CallbackRef is a callback function reference. None. None.
References I2C_CLK_ADDR_570, Si570_SetClock.
Referenced by main.
void RxStreamUp(void)
void RxStreamDownCallback(void *CallbackRef)
This function is called when the RX loses lock, and it stops SDI Tx Subsystem.
CallbackRef is a callback function reference. None. None.
References XV_SdiTxSs_Stop.
Referenced by main.
void Xil_AssertCallbackRoutine(u8 *File, s32 Line)
This function is called when assertion hits in the file.
File - File name where assertion occurred. Line - Line number in this file. None. None.
void StartTxAfterRx(void)
This function is called to start the TX stream after the RX stream was up and running.
None. None.
References XV_SdiTxSs_GetPayloadId, XV_SdiTxSs_GetTransport, XV_SdiTxSs_GetVideoStream, XV_SdiTxSs_StreamConfig.
Referenced by main.
static int I2cMux(void)
This function setups the interrupt system so interrupts can occur for the SDI cores.
The function is application-specific since the actual system may or may not have an interrupt controller. The SDI cores could be directly connected to a processor without an interrupt controller. The user should modify this function to fit the application. XST_SUCCESS if interrupt setup was successful.A specific error code defined in "xstatus.h" if an error occurs. This function assumes a Microblaze or ARM system and no operating system is used. This function setup SI570 clock generator over IIC.The number of bytes sent. None.
int Si570_SetClock(u32 IICBaseAddress, u8 IICAddress1, u32 RxRefClk)
Set the output frequency of the Si570 clock generator.
IICBaseAddress contains the base address of the IIC master device. IICAddress1 contains the 7 bit IIC address of the Si570 device. RxRefClk contains the value to be written in Si570 register for that particular clock frequency. SI570_SUCCESS for successSI570_ERR_IIC for IIC access failure,SI570_ERR_FREQ when the requested frequency cannot be generatedSI570_ERR_PARM when the ClkSrc or ClkDest parameters are invalid or the ClkInFreq or ClkOutFreq are out of range.
References SI570_DEBUG, Si570_DoSettings.
Referenced by main, RxStreamUpCallback.
void Info(void)
This function outputs the video information on TX and RX.
None. None.
References XV_SdiTxSs_ReportInfo.
void DebugInfo(void)
This function outputs the debug information.
None. None.
References XV_SdiTxSs_ReportDebugInfo.
int main(void)
Main function to call example with SDI TX and SDI RX drivers.
XST_SUCCESS if SDI example was successfully.XST_FAILURE if SDI example failed. None.
References XV_SdiTxSs_Config::BaseAddress, ClearScreen, XV_SdiTxSs::Config, I2C_CLK_ADDR_570, XV_SdiTxSs_Config::IntrId, XV_SdiTxSs_Config::IntrParent, XV_SdiTxSs::IsReady, RxStreamDownCallback, RxStreamUpCallback, Si570_SetClock, StartTxAfterRx, XSdi_MenuInitialize, XSdi_MenuProcess, XV_SdiTxSs_CfgInitialize, XV_SDITXSS_HANDLER_GTREADY, XV_SDITXSS_IER_ALLINTR_MASK, XV_SDITXSS_IER_GTTX_RSTDONE_MASK, XV_SdiTxSs_IntrDisable, XV_SdiTxSs_IntrEnable, XV_SdiTxSs_LookupConfig, XV_SdiTxSS_SdiTxIntrHandler, XV_SdiTxSs_SetCallback, XV_SdiTxSs_SetCoreSettings.