xv_sditxss.h
XV_SDITXSS_IER_GTTX_RSTDONE_MASK
GT TX reset done mask.
Referenced by main.
XV_SDITXSS_IER_TX_CE_ALIGN_ERR_MASK
TX CE align error mask.
XV_SDITXSS_IER_AXI4S_VID_LOCK_MASK
AXI4S video lock mask.
XV_SDITXSS_IER_OVERFLOW_MASK
Overflow mask.
XV_SDITXSS_IER_UNDERFLOW_MASK
Underflow mask.
XV_SDITXSS_IER_ALLINTR_MASK
All interrupts mask.
Referenced by main, XV_SdiTxSs_IntrDisable, XV_SdiTxSs_IntrEnable.
XV_SdiTxSs_LogEvent
Log event none.
XV_SdiTxSs_HandlerType
Handler for connect event.
XV_SdiTxSs_GetVersion
This macro reads the TX version.
InstancePtr is a pointer to the XV_SdiTX core instance. None.
XV_SdiTxSs_CoreSelId
XV_SdiTxSs_Config* XV_SdiTxSs_LookupConfig(UINTPTR BaseAddress)
This function looks for the device configuration based on the unique device ID.
The table XV_SdiTxSs_ConfigTable[] contains the configuration information for each instance of the device in the system. DeviceId is the unique device ID of the device being looked up A pointer to the configuration table entry corresponding to the given device ID, or NULL if no match is found
Referenced by main, SdiTxSs_SelfTestExample.
u32 XV_SdiTxSs_GetDrvIndex(XV_SdiTxSs *InstancePtr, UINTPTR BaseAddress)
This function returns the Index number of config table using BaseAddress.
A pointer to the instance structure Base address of the instance Index number of the config table
int XV_SdiTxSs_CfgInitialize(XV_SdiTxSs *InstancePtr, XV_SdiTxSs_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the video subsystem and included sub-cores.
This function must be called prior to using the subsystem. Initialization includes setting up the instance data for top level as well as all included sub-core therein, and ensuring the hardware is in a known stable state. InstancePtr is a pointer to the Subsystem instance to be worked on. CfgPtr points to the configuration structure associated with the subsystem instance. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if initialization is successful else XST_FAILURE
References XV_SdiTxSs_Config::BaseAddress, XV_SdiTxSs::Config, XV_SdiTxSs::IsReady, XV_SdiTxSs::SdiTxPtr, XV_SdiTxSs::VtcPtr, XV_SdiTxSs_SubcoreInitSdiTx, XV_SdiTxSs_SubcoreInitVtc.
Referenced by main, SdiTxSs_SelfTestExample.
void XV_SdiTxSS_SdiTxIntrHandler(XV_SdiTxSs *InstancePtr)
This function calls the interrupt handler for SDI TX.
InstancePtr is a pointer to the SDI TX Subsystem
References XV_SdiTxSs::SdiTxPtr.
Referenced by main.
int XV_SdiTxSs_SetCallback(XV_SdiTxSs *InstancePtr, u32 HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function Type ----------------------- --------------------------------------------- (XV_SDITXSS_HANDLER_GTREADY) GtReadyCallback (XV_SDITXSS_HANDLER_OVERFLOW) OverFlowCallback (XV_SDITXSS_HANDLER_UNDERFLOW) UnderFlowCallback (XV_SDITXSS_HANDLER_CEALIGN) CeAlignErrCallback (XV_SDITXSS_HANDLER_AXI4SVIDLOCK) Axi4sVidLockCallback InstancePtr is a pointer to the SDI TX Subsystem instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XV_SdiTxSs::Axi4sVidLockCallback, XV_SdiTxSs::Axi4sVidLockRef, XV_SdiTxSs::CeAlignErrCallback, XV_SdiTxSs::CeAlignErrRef, XV_SdiTxSs::GtReadyCallback, XV_SdiTxSs::GtReadyRef, XV_SdiTxSs::OverFlowCallback, XV_SdiTxSs::OverFlowRef, XV_SdiTxSs::UnderFlowCallback, XV_SdiTxSs::UnderFlowRef, XV_SDITXSS_HANDLER_AXI4SVIDLOCK, XV_SDITXSS_HANDLER_CEALIGN, XV_SDITXSS_HANDLER_GTREADY, XV_SDITXSS_HANDLER_OVERFLOW, XV_SDITXSS_HANDLER_UNDERFLOW.
Referenced by main.
void XV_SdiTxSs_StreamStart(XV_SdiTxSs *InstancePtr)
This function starts the SDI TX stream.
InstancePtr pointer to XV_SdiTxSs instance None.
References XV_SdiTxSs::Config, XV_SdiTxSs::SdiTxPtr, XV_SdiTxSs::VtcPtr, XV_SDITXSS_LOG_EVT_STREAMSTART, XV_SdiTxSs_LogWrite.
void XV_SdiTxSs_StreamConfig(XV_SdiTxSs *InstancePtr)
This function configures SDI TX stream.
InstancePtr pointer to XV_SdiTxSs instance None.
References XV_SdiTxSs::Config, XV_SdiTxSs::MaxDataStreams, XV_SdiTxSs::SdiTxPtr, XV_SdiTxSs_LogWrite.
Referenced by StartTxAfterRx.
void XV_SdiTxSs_Stop(XV_SdiTxSs *InstancePtr)
This macro disables the SDI TX peripheral.
InstancePtr is a pointer to the XV_SdiTxSs core instance. None.
References XV_SdiTxSs::IsStreamUp, XV_SdiTxSs::SdiTxPtr, XV_SDITXSS_LOG_EVT_STOP, XV_SdiTxSs_LogWrite.
Referenced by RxStreamDownCallback.
u32* XV_SdiTxSs_GetPayloadId(XV_SdiTxSs *InstancePtr, u8 StreamId)
This function returns the pointer to SDI TX SS video stream payload ID.
InstancePtr pointer to XV_SdiTxSs instance StreamId specifies which of the pointer of PayloadId to be returned u32 pointer None.
References XV_SdiTxSs::SdiTxPtr.
Referenced by StartTxAfterRx.
void XV_SdiTxSs_SetEotf(XV_SdiTxSs *InstancePtr, XVidC_Eotf Eotf, XVidC_ColorStd Colorimetry)
This function is used to update the Eotf and colorimetry fields of stream video structure.
If SDI TX is already streaming, then this function updates the payload registers. InstancePtr pointer to XV_SdiTxSs instance Eotf is a variable of type XVidC_Eotf Colorimetry is a variable of type XVidC_ColorStd None.
References XV_SdiTxSs::IsStreamUp, XV_SdiTxSs::SdiTxPtr.
XSdiVid_Transport* XV_SdiTxSs_GetTransport(XV_SdiTxSs *InstancePtr)
This function returns the pointer to SDI TX SS video transport.
InstancePtr pointer to XV_SdiTxSs instance XSdiVid_Transport pointer None.
References XV_SdiTxSs::SdiTxPtr.
Referenced by StartTxAfterRx.
XVidC_VideoStream* XV_SdiTxSs_GetVideoStream(XV_SdiTxSs *InstancePtr, u8 StreamId)
This function returns the pointer to SDI TX SS video stream.
InstancePtr pointer to XV_SdiTxSs instance StreamId specifies which video stream's pointer to be returned XVidC_VideoStream pointer None.
References XV_SdiTxSs::SdiTxPtr.
Referenced by StartTxAfterRx.
void XV_SdiTxSs_SetVideoStream(XV_SdiTxSs *InstancePtr, XVidC_VideoStream VidStream)
This function Sets the SDI TX SS video stream.
InstancePtr pointer to XV_SdiTxSs instance VidStream specifies the settings for the video stream None.
References XV_SdiTxSs::SdiTxPtr.
void XV_SdiTxSs_ReportInfo(XV_SdiTxSs *InstancePtr)
This function prints the SDI TX SS information.
InstancePtr pointer to XV_SdiTxSs instance None.
References XV_SdiTxSs::SdiTxPtr.
Referenced by Info.
void XV_SdiTxSs_ReportDebugInfo(XV_SdiTxSs *InstancePtr, u32 VtcFlag)
This function prints the SDI TX SS debug information.
InstancePtr pointer to XV_SdiTxSs instance VtcFlag specifies if VTC block is currently stable or not. A known issue on the VTC causes it to require a stable clock before the registers may be access. VtcFlag is used to decide whether VTC can be read or not.
References XV_SdiTxSs::SdiTxPtr, XV_SdiTxSs::VtcPtr.
Referenced by DebugInfo.
void XV_SdiTxSs_ReportStreamInfo(XV_SdiTxSs *InstancePtr)
This function prints the SDI TX SS stream information.
InstancePtr pointer to XV_SdiTxSs instance None.
References XV_SdiTxSs::SdiTxPtr.
void XV_SdiTxSs_ReportDetectedError(XV_SdiTxSs *InstancePtr)
This function reports stream errors detected.
InstancePtr pointer to XV_SdiTxSs instance None.
References XV_SdiTxSs::SdiTxPtr.
int XV_SdiTxSs_IsStreamUp(XV_SdiTxSs *InstancePtr)
This function checks if the video stream is up.
InstancePtr pointer to XV_SdiTxSs instance TRUE if stream is up.FALSE if stream is down. None.
References XV_SdiTxSs::IsStreamUp.
void XV_SdiTxSs_IntrEnable(XV_SdiTxSs *InstancePtr, u32 IntrMask)
This function is used to configure the SDI TX interrupts that are to be handled by the application.
Refer to xv_sditxss_hw.h for interrupt masks. InstancePtr pointer to XV_SdiTxSs instance IntrMask Indicates Mask for enable interrupts. None.
References XV_SdiTxSs::SdiTxPtr, XV_SDITXSS_IER_ALLINTR_MASK.
Referenced by main.
void XV_SdiTxSs_IntrDisable(XV_SdiTxSs *InstancePtr, u32 IntrMask)
This function is used to configure the SDI TX interrupts that are to be handled by the application.
Refer to xv_sditxss_hw.h for interrupt masks. InstancePtr pointer to XV_SdiTxSs instance IntrMask Indicates Mask for disabling interrupts. None.
References XV_SdiTxSs::SdiTxPtr, XV_SDITXSS_IER_ALLINTR_MASK.
Referenced by main.
u32 XV_SdiTxSs_GetPayload(XV_SdiTxSs *InstancePtr, XVidC_VideoMode VideoMode, XSdiVid_TransMode SdiMode, u8 DataStream)
This function calculates the final ST352 payload value for all SDI modes with given video mode and SDI data stream number.
InstancePtr is a pointer to the XV_SdiTxSs core instance. VideoMode is a variable of type XVidC_VideoMode. SdiMode is a variable of type XSdiVid_TransMode. DataStream is the stream number for which payload is calculated. XST_SUCCESS / XST_FAILURE. None.
References XV_SdiTxSs::SdiTxPtr.
u32 XV_SdiTxSs_SetStream(XV_SdiTxSs *InstancePtr, XV_SdiTx_StreamSelId SelId, u32 Data, u8 StreamId)
This function sets the SDI TXSs stream parameters.
InstancePtr is a pointer to the XV_SdiTxSs core instance. SelId specifies which parameter of the stream to be set. 0 = XV_SDITX_STREAMSELID_VMID1 = XV_SDITX_STREAMSELID_COLORFORMAT2 = XV_SDITX_STREAMSELID_BPC3 = XV_SDITX_STREAMSELID_PPC4 = XV_SDITX_STREAMSELID_ASPECTRATIO5 = XV_SDITX_STREAMSELID_STANDARD6 = XV_SDITX_STREAMSELID_STREAMINTERLACE7 = XV_SDITX_STREAMSELID_CHANNEL Data specifies what data to be set for the selected parameter. StreamId specifies which of the streams to be set. XST_SUCCESS on successful Set streamXST_FAILURE if TimingPtr is not derived None.
References XV_SdiTxSs::SdiTxPtr.
u32 XV_SdiTxSs_SelfTest(XV_SdiTxSs *InstancePtr)
This function performs self test on SDI Tx Subsystem sub-cores.
InstancePtr is a pointer to the XV_SdiTxSs core instance. XST_SUCCESS if self test passed.XST_FAILURE if self test failed. None.
References XV_SdiTxSs::SdiTxPtr.
Referenced by SdiTxSs_SelfTestExample.
void XV_SdiTxSs_LogReset(XV_SdiTxSs *InstancePtr)
This function will reset the driver's logging mechanism.
InstancePtr is a pointer to the xv_sditxss core instance. None.
References XV_SdiTxSs_Log::HeadIndex, XV_SdiTxSs::Log, XV_SdiTxSs_Log::TailIndex.
void XV_SdiTxSs_LogWrite(XV_SdiTxSs *InstancePtr, XV_SdiTxSs_LogEvent Evt, u8 Data)
This function will insert an event in the driver's logginc mechanism.
InstancePtr is a pointer to the XV_SdiTxSs core instance. Evt is the event type to log. Data is the associated data for the event. None.
References XV_SdiTxSs_Log::DataBuffer, XV_SdiTxSs_Log::HeadIndex, XV_SdiTxSs::Log, XV_SdiTxSs_Log::TailIndex, XV_SDITXSS_LOG_EVT_DUMMY.
Referenced by XV_SdiTxSs_Stop, XV_SdiTxSs_StreamConfig, XV_SdiTxSs_StreamStart, XV_SdiTxSs_SubcoreInitSdiTx, XV_SdiTxSs_SubcoreInitVtc.
u16 XV_SdiTxSs_LogRead(XV_SdiTxSs *InstancePtr)
This function will read the last event from the log.
InstancePtr is a pointer to the XV_SdiTxSs core instance. The log data. None.
References XV_SdiTxSs_Log::DataBuffer, XV_SdiTxSs_Log::HeadIndex, XV_SdiTxSs::Log, XV_SdiTxSs_Log::TailIndex.
Referenced by XV_SdiTxSs_LogDisplay.
void XV_SdiTxSs_LogDisplay(XV_SdiTxSs *InstancePtr)
This function will print the entire log.
InstancePtr is a pointer to the XV_SdiTxSs core instance. None.
References XV_SDITXSS_LOG_EVT_AXI4SVIDLOCK, XV_SDITXSS_LOG_EVT_CEALIGN, XV_SDITXSS_LOG_EVT_NONE, XV_SDITXSS_LOG_EVT_OVERFLOW, XV_SDITXSS_LOG_EVT_RESET, XV_SDITXSS_LOG_EVT_SDITX_INIT, XV_SDITXSS_LOG_EVT_START, XV_SDITXSS_LOG_EVT_STOP, XV_SDITXSS_LOG_EVT_STREAMDOWN, XV_SDITXSS_LOG_EVT_STREAMSTART, XV_SDITXSS_LOG_EVT_STREAMUP, XV_SDITXSS_LOG_EVT_UNDERFLOW, XV_SDITXSS_LOG_EVT_VTC_INIT, XV_SdiTxSs_LogRead.
int XV_SdiTxSs_SetColorFormat(XV_SdiTxSs *InstancePtr, XVidC_ColorFormat ColorFormat)
This function Set the video format of the SDI TX Ss core.
InstancePtr is a pointer to the XV_SdiTxSs core instance. ColorFormat is a variable of type XVidC_ColorFormat. XST_SUCCESS if successful, otherwise XST_FAILURE. None.
References XV_SdiTxSs::SdiTxPtr.
void XV_SdiTxSs_ST352CStreamEnable(XV_SdiTxSs *InstancePtr)
This function enables the insertion of ST352 in C stream of the SDI TX Ss core.
InstancePtr is a pointer to the XV_SdiTxSs core instance. None.
References XV_SdiTxSs::Config, XV_SdiTxSs_Config::InsertCSTRST352, XV_SdiTxSs::SdiTxPtr.
void XV_SdiTxSs_ST352CSwitch3GA(XV_SdiTxSs *InstancePtr)
This function enables the ST352 value to be used from DS2 instead of DS3 register in C stream of the SDI TX Ss core.
InstancePtr is a pointer to the XV_SdiTxSs core instance. None.
References XV_SdiTxSs::Config, XV_SdiTxSs_Config::InsertCSTRST352, XV_SdiTxSs::SdiTxPtr.
void XV_SdiTxSs_SetCoreSettings(XV_SdiTxSs *InstancePtr, XV_SdiTxSs_CoreSelId SelId, u8 Data)
This function sets the SDI TXSS core settings.
InstancePtr is a pointer to the XV_SdiTxSs core instance. SelId specifies which parameter of the stream to be set. 0 = XV_SDITXSS_CORESELID_INSERTCRC1 = XV_SDITXSS_CORESELID_INSERTST3522 = XV_SDITXSS_CORESELID_ST352OVERWRITE3 = XV_SDITXSS_CORESELID_INSERTSYNCBIT4 = XV_SDITXSS_CORESELID_SDBITREPBYPASS5 = XV_SDITXSS_CORESELID_USEANCIN6 = XV_SDITXSS_CORESELID_INSERTLN7 = XV_SDITXSS_CORESELID_INSERTEDH Data specifies what data to be set for the selected parameter. None.
References XV_SdiTxSs::SdiTxPtr.
Referenced by main.
void XV_SdiTxSs_SetYCbCr444_RGB_10bit(XV_SdiTxSs *InstancePtr)
This function enable the YUV444/RGB 10bit support SDI TX SS video stream.
InstancePtr pointer to XV_SdiTxSs instance
References XV_SdiTxSs::SdiTxPtr.
void XV_SdiTxSs_ClearYCbCr444_RGB_10bit(XV_SdiTxSs *InstancePtr)
This function disable the YUV444/RGB 10bit support SDI TX SS video stream.
InstancePtr pointer to XV_SdiTxSs instance
References XV_SdiTxSs::SdiTxPtr.
XV_SDITXSS_H_
Prevent circular inclusions by using protection macros.
typedef void(* XV_SdiTxSs_Callback)(void *CallbackRef))(void *CallbackRef)
Callback type for interrupt.
CallbackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. None. None.