xv_sditxss.c
XSDITXSS_LINE_RATE_3G
XSDITXSS_LINE_RATE_6G
XSDITXSS_LINE_RATE_12G8DS
AXI4_STREAM
NATIVE_VIDEO
NATIVE_SDI
XSDITXSS_XVTC_ASIZE_VERT_SHIFT
XSDITXSS_XVTC_ASIZE_VERT_MASK
XSDITXSS_XVTC_GASIZE_F1_OFFSET
XSDITXSS_SD_NTSC_F1_V_ACTIVE
XST352_PAYLOAD_BYTE_MASK
XST352_BYTE2_TS_TYPE_MASK
XST352_BYTE2_PIC_TYPE_MASK
XST352_BYTE1_ST372_DL_3GB
XST352_BYTE1_ST425_2008_1125L_3GA
XV_SdiTxSs_SubCores XV_SdiTxSs_SubCoreRepo[XPAR_XV_SDITXSS_NUM_INSTANCES][XPAR_XV_SDITXSS_NUM_INSTANCES]
Define Driver instance of all sub-core included in the design.
static int XV_SdiTxSs_VtcSetup(XVtc *XVtcPtr, XV_SdiTx *SdiTxPtr)
This function configures Video Timing Controller (VTC).
XVtcPtr is a pointer to the XVtc core instance. SdiTxPtr is a pointer to the XV_SdiTx core instance. XST_SUCCESS if successful, otherwise XST_FAILURE. None.
static void XV_SdiTxSs_ReportCoreInfo(XV_SdiTxSs *InstancePtr)
This function reports list of cores included in Video Processing Subsystem.
InstancePtr is a pointer to the Subsystem instance.
static void XV_SdiTxSs_ReportTiming(XV_SdiTxSs *InstancePtr)
This function prints the SDI TX SS timing information.
InstancePtr pointer to XV_SdiTxSs instance None.
static void XV_SdiTxSs_GtReadyCallback(void *CallbackRef)
This function is called when the GT is ready for TX configuration.
CallbackRef is a user data item that will be passed to the callback function when it is invoked. None.
static void XV_SdiTxSs_OverFlowCallback(void *CallbackRef)
This function is called when the Tx over flow happens.
CallbackRef is a user data item that will be passed to the callback function when it is invoked. None.
static void XV_SdiTxSs_UnderFlowCallback(void *CallbackRef)
This function is called when the Tx under flow happens.
CallbackRef is a user data item that will be passed to the callback function when it is invoked. None.
static void XV_SdiTxSs_CeAlignErrCallback(void *CallbackRef)
This function is called when the Tx CE align errors happens.
CallbackRef is a user data item that will be passed to the callback function when it is invoked. None.
static void XV_SdiTxSs_Axi4sVidLockCallback(void *CallbackRef)
This function is called when the Tx Axi4s video lock bridge happens.
CallbackRef is a user data item that will be passed to the callback function when it is invoked. None.
static int XV_SdiTxSs_RegisterSubsysCallbacks(XV_SdiTxSs *InstancePtr)
This function register's all sub-core ISR's with interrupt controller and any subsystem level call back function with requisite sub-core.
InstancePtr is a pointer to the Subsystem instance to be worked on.
static u8 XV_SdiTxSs_Is3GBDLor3GA1125L(XV_SdiTxSs *InstancePtr)
This function queries the subsystem instance if the current mode is 3GB DL or not.
SdiTxSsPtr is a pointer to the Subsystem instance to be worked on. TRUE - If current mode is 3GB DL FALSE - If current mode is not 3GB DL
void XV_SdiTxSS_SdiTxIntrHandler(XV_SdiTxSs *InstancePtr)
This function calls the interrupt handler for SDI TX.
InstancePtr is a pointer to the SDI TX Subsystem
References XV_SdiTxSs::SdiTxPtr.
Referenced by main.
static void XV_SdiTxSs_GetIncludedSubcores(XV_SdiTxSs *SdiTxSsPtr, UINTPTR BaseAddress)
This function queries the subsystem instance configuration to determine the included sub-cores.
For each sub-core that is present in the design the sub-core driver instance is binded with the subsystem sub-core driver handle SdiTxSsPtr is a pointer to the Subsystem instance to be worked on.
int XV_SdiTxSs_CfgInitialize(XV_SdiTxSs *InstancePtr, XV_SdiTxSs_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the video subsystem and included sub-cores.
This function must be called prior to using the subsystem. Initialization includes setting up the instance data for top level as well as all included sub-core therein, and ensuring the hardware is in a known stable state. InstancePtr is a pointer to the Subsystem instance to be worked on. CfgPtr points to the configuration structure associated with the subsystem instance. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if initialization is successful else XST_FAILURE
References XV_SdiTxSs_Config::BaseAddress, XV_SdiTxSs::Config, XV_SdiTxSs::IsReady, XV_SdiTxSs::SdiTxPtr, XV_SdiTxSs::VtcPtr, XV_SdiTxSs_SubcoreInitSdiTx, XV_SdiTxSs_SubcoreInitVtc.
Referenced by main, SdiTxSs_SelfTestExample.
int XV_SdiTxSs_SetCallback(XV_SdiTxSs *InstancePtr, u32 HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function Type ----------------------- --------------------------------------------- (XV_SDITXSS_HANDLER_GTREADY) GtReadyCallback (XV_SDITXSS_HANDLER_OVERFLOW) OverFlowCallback (XV_SDITXSS_HANDLER_UNDERFLOW) UnderFlowCallback (XV_SDITXSS_HANDLER_CEALIGN) CeAlignErrCallback (XV_SDITXSS_HANDLER_AXI4SVIDLOCK) Axi4sVidLockCallback InstancePtr is a pointer to the SDI TX Subsystem instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XV_SdiTxSs::Axi4sVidLockCallback, XV_SdiTxSs::Axi4sVidLockRef, XV_SdiTxSs::CeAlignErrCallback, XV_SdiTxSs::CeAlignErrRef, XV_SdiTxSs::GtReadyCallback, XV_SdiTxSs::GtReadyRef, XV_SdiTxSs::OverFlowCallback, XV_SdiTxSs::OverFlowRef, XV_SdiTxSs::UnderFlowCallback, XV_SdiTxSs::UnderFlowRef, XV_SDITXSS_HANDLER_AXI4SVIDLOCK, XV_SDITXSS_HANDLER_CEALIGN, XV_SDITXSS_HANDLER_GTREADY, XV_SDITXSS_HANDLER_OVERFLOW, XV_SDITXSS_HANDLER_UNDERFLOW.
Referenced by main.
void XV_SdiTxSs_Stop(XV_SdiTxSs *InstancePtr)
This macro disables the SDI TX peripheral.
InstancePtr is a pointer to the XV_SdiTxSs core instance. None.
References XV_SdiTxSs::IsStreamUp, XV_SdiTxSs::SdiTxPtr, XV_SDITXSS_LOG_EVT_STOP, XV_SdiTxSs_LogWrite.
Referenced by RxStreamDownCallback.
void XV_SdiTxSs_ST352CSwitch3GA(XV_SdiTxSs *InstancePtr)
This function enables the ST352 value to be used from DS2 instead of DS3 register in C stream of the SDI TX Ss core.
InstancePtr is a pointer to the XV_SdiTxSs core instance. None.
References XV_SdiTxSs::Config, XV_SdiTxSs_Config::InsertCSTRST352, XV_SdiTxSs::SdiTxPtr.
void XV_SdiTxSs_ST352CStreamEnable(XV_SdiTxSs *InstancePtr)
This function enables the insertion of ST352 in C stream of the SDI TX Ss core.
InstancePtr is a pointer to the XV_SdiTxSs core instance. None.
References XV_SdiTxSs::Config, XV_SdiTxSs_Config::InsertCSTRST352, XV_SdiTxSs::SdiTxPtr.
int XV_SdiTxSs_SetColorFormat(XV_SdiTxSs *InstancePtr, XVidC_ColorFormat ColorFormat)
This function Set the video format of the SDI TX Ss core.
InstancePtr is a pointer to the XV_SdiTxSs core instance. ColorFormat is a variable of type XVidC_ColorFormat. XST_SUCCESS if successful, otherwise XST_FAILURE. None.
References XV_SdiTxSs::SdiTxPtr.
void XV_SdiTxSs_StreamStart(XV_SdiTxSs *InstancePtr)
This function starts the SDI TX stream.
InstancePtr pointer to XV_SdiTxSs instance None.
References XV_SdiTxSs::Config, XV_SdiTxSs::SdiTxPtr, XV_SdiTxSs::VtcPtr, XV_SDITXSS_LOG_EVT_STREAMSTART, XV_SdiTxSs_LogWrite.
void XV_SdiTxSs_StreamConfig(XV_SdiTxSs *InstancePtr)
This function configures SDI TX stream.
InstancePtr pointer to XV_SdiTxSs instance None.
References XV_SdiTxSs::Config, XV_SdiTxSs::MaxDataStreams, XV_SdiTxSs::SdiTxPtr, XV_SdiTxSs_LogWrite.
Referenced by StartTxAfterRx.
u32* XV_SdiTxSs_GetPayloadId(XV_SdiTxSs *InstancePtr, u8 StreamId)
This function returns the pointer to SDI TX SS video stream payload ID.
InstancePtr pointer to XV_SdiTxSs instance StreamId specifies which of the pointer of PayloadId to be returned u32 pointer None.
References XV_SdiTxSs::SdiTxPtr.
Referenced by StartTxAfterRx.
XSdiVid_Transport* XV_SdiTxSs_GetTransport(XV_SdiTxSs *InstancePtr)
This function returns the pointer to SDI TX SS video transport.
InstancePtr pointer to XV_SdiTxSs instance XSdiVid_Transport pointer None.
References XV_SdiTxSs::SdiTxPtr.
Referenced by StartTxAfterRx.
XVidC_VideoStream* XV_SdiTxSs_GetVideoStream(XV_SdiTxSs *InstancePtr, u8 StreamId)
This function returns the pointer to SDI TX SS video stream.
InstancePtr pointer to XV_SdiTxSs instance StreamId specifies which video stream's pointer to be returned XVidC_VideoStream pointer None.
References XV_SdiTxSs::SdiTxPtr.
Referenced by StartTxAfterRx.
void XV_SdiTxSs_SetVideoStream(XV_SdiTxSs *InstancePtr, XVidC_VideoStream VidStream)
This function Sets the SDI TX SS video stream.
InstancePtr pointer to XV_SdiTxSs instance VidStream specifies the settings for the video stream None.
References XV_SdiTxSs::SdiTxPtr.
void XV_SdiTxSs_ReportDetectedError(XV_SdiTxSs *InstancePtr)
This function reports stream errors detected.
InstancePtr pointer to XV_SdiTxSs instance None.
References XV_SdiTxSs::SdiTxPtr.
void XV_SdiTxSs_ReportInfo(XV_SdiTxSs *InstancePtr)
This function prints the SDI TX SS information.
InstancePtr pointer to XV_SdiTxSs instance None.
References XV_SdiTxSs::SdiTxPtr.
Referenced by Info.
void XV_SdiTxSs_ReportDebugInfo(XV_SdiTxSs *InstancePtr, u32 VtcFlag)
This function prints the SDI TX SS debug information.
InstancePtr pointer to XV_SdiTxSs instance VtcFlag specifies if VTC block is currently stable or not. A known issue on the VTC causes it to require a stable clock before the registers may be access. VtcFlag is used to decide whether VTC can be read or not.
References XV_SdiTxSs::SdiTxPtr, XV_SdiTxSs::VtcPtr.
Referenced by DebugInfo.
void XV_SdiTxSs_ReportStreamInfo(XV_SdiTxSs *InstancePtr)
This function prints the SDI TX SS stream information.
InstancePtr pointer to XV_SdiTxSs instance None.
References XV_SdiTxSs::SdiTxPtr.
int XV_SdiTxSs_IsStreamUp(XV_SdiTxSs *InstancePtr)
This function checks if the video stream is up.
InstancePtr pointer to XV_SdiTxSs instance TRUE if stream is up.FALSE if stream is down. None.
References XV_SdiTxSs::IsStreamUp.
void XV_SdiTxSs_IntrEnable(XV_SdiTxSs *InstancePtr, u32 IntrMask)
This function is used to configure the SDI TX interrupts that are to be handled by the application.
Refer to xv_sditxss_hw.h for interrupt masks. InstancePtr pointer to XV_SdiTxSs instance IntrMask Indicates Mask for enable interrupts. None.
References XV_SdiTxSs::SdiTxPtr, XV_SDITXSS_IER_ALLINTR_MASK.
Referenced by main.
void XV_SdiTxSs_IntrDisable(XV_SdiTxSs *InstancePtr, u32 IntrMask)
This function is used to configure the SDI TX interrupts that are to be handled by the application.
Refer to xv_sditxss_hw.h for interrupt masks. InstancePtr pointer to XV_SdiTxSs instance IntrMask Indicates Mask for disabling interrupts. None.
References XV_SdiTxSs::SdiTxPtr, XV_SDITXSS_IER_ALLINTR_MASK.
Referenced by main.
void XV_SdiTxSs_SetEotf(XV_SdiTxSs *InstancePtr, XVidC_Eotf Eotf, XVidC_ColorStd Colorimetry)
This function is used to update the Eotf and colorimetry fields of stream video structure.
If SDI TX is already streaming, then this function updates the payload registers. InstancePtr pointer to XV_SdiTxSs instance Eotf is a variable of type XVidC_Eotf Colorimetry is a variable of type XVidC_ColorStd None.
References XV_SdiTxSs::IsStreamUp, XV_SdiTxSs::SdiTxPtr.
u32 XV_SdiTxSs_GetPayload(XV_SdiTxSs *InstancePtr, XVidC_VideoMode VideoMode, XSdiVid_TransMode SdiMode, u8 DataStream)
This function calculates the final ST352 payload value for all SDI modes with given video mode and SDI data stream number.
InstancePtr is a pointer to the XV_SdiTxSs core instance. VideoMode is a variable of type XVidC_VideoMode. SdiMode is a variable of type XSdiVid_TransMode. DataStream is the stream number for which payload is calculated. XST_SUCCESS / XST_FAILURE. None.
References XV_SdiTxSs::SdiTxPtr.
u32 XV_SdiTxSs_SetStream(XV_SdiTxSs *InstancePtr, XV_SdiTx_StreamSelId SelId, u32 Data, u8 StreamId)
This function sets the SDI TXSs stream parameters.
InstancePtr is a pointer to the XV_SdiTxSs core instance. SelId specifies which parameter of the stream to be set. 0 = XV_SDITX_STREAMSELID_VMID1 = XV_SDITX_STREAMSELID_COLORFORMAT2 = XV_SDITX_STREAMSELID_BPC3 = XV_SDITX_STREAMSELID_PPC4 = XV_SDITX_STREAMSELID_ASPECTRATIO5 = XV_SDITX_STREAMSELID_STANDARD6 = XV_SDITX_STREAMSELID_STREAMINTERLACE7 = XV_SDITX_STREAMSELID_CHANNEL Data specifies what data to be set for the selected parameter. StreamId specifies which of the streams to be set. XST_SUCCESS on successful Set streamXST_FAILURE if TimingPtr is not derived None.
References XV_SdiTxSs::SdiTxPtr.
void XV_SdiTxSs_SetCoreSettings(XV_SdiTxSs *InstancePtr, XV_SdiTxSs_CoreSelId SelId, u8 Data)
This function sets the SDI TXSS core settings.
InstancePtr is a pointer to the XV_SdiTxSs core instance. SelId specifies which parameter of the stream to be set. 0 = XV_SDITXSS_CORESELID_INSERTCRC1 = XV_SDITXSS_CORESELID_INSERTST3522 = XV_SDITXSS_CORESELID_ST352OVERWRITE3 = XV_SDITXSS_CORESELID_INSERTSYNCBIT4 = XV_SDITXSS_CORESELID_SDBITREPBYPASS5 = XV_SDITXSS_CORESELID_USEANCIN6 = XV_SDITXSS_CORESELID_INSERTLN7 = XV_SDITXSS_CORESELID_INSERTEDH Data specifies what data to be set for the selected parameter. None.
References XV_SdiTxSs::SdiTxPtr.
Referenced by main.
void XV_SdiTxSs_SetYCbCr444_RGB_10bit(XV_SdiTxSs *InstancePtr)
This function enable the YUV444/RGB 10bit support SDI TX SS video stream.
InstancePtr pointer to XV_SdiTxSs instance
References XV_SdiTxSs::SdiTxPtr.
void XV_SdiTxSs_ClearYCbCr444_RGB_10bit(XV_SdiTxSs *InstancePtr)
This function disable the YUV444/RGB 10bit support SDI TX SS video stream.
InstancePtr pointer to XV_SdiTxSs instance
References XV_SdiTxSs::SdiTxPtr.