xvphy
void XVphy_Ch2Ids(XVphy *InstancePtr, XVphy_ChannelId ChId, u8 *Id0, u8 *Id1)
This function will set the channel IDs to correspond with the supplied channel ID based on the protocol.
HDMI uses 3 channels; DP uses 4. This ID translation is done to allow other functions to operate iteratively over multiple channels. InstancePtr is a pointer to the XVphy core instance. ChId is the channel ID used to determine the indices. Id0 is a pointer to the start channel ID to set. Id1 is a pointer to the end channel ID to set. None. The contents of Id0 and Id1 will be set according to ChId.
References XVphy::Config, XVphy_Config::RxChannels, XVphy_Config::TxChannels, XVphy_Config::UseGtAsTxTmdsClk, XVphy_Config::XcvrType, XVphy_IsHDMI.
Referenced by XVphy_CfgLineRate, XVphy_CfgPllRefClkSel, XVphy_CfgSysClkDataSel, XVphy_CfgSysClkOutSel, XVphy_ClkCalcParams, XVphy_ClkReconfig, XVphy_DirReconfig, XVphy_OutDivReconfig, XVphy_PllCalculator, XVphy_PowerDownGtPll, XVphy_SetPrbsSel.
XVphy_SysClkDataSelType Pll2SysClkData(XVphy_PllType PllSelect)
This function will translate from XVphy_PllType to XVphy_SysClkDataSelType.
PllSelect is the PLL type to translate. The reference clock type based on the PLL selection. None.
Referenced by XVphy_PllInitialize.
XVphy_SysClkOutSelType Pll2SysClkOut(XVphy_PllType PllSelect)
This function will translate from XVphy_PllType to XVphy_SysClkOutSelType.
PllSelect is the PLL type to translate. The reference clock type based on the PLL selection. None.
Referenced by XVphy_PllInitialize.
u32 XVphy_PllCalculator(XVphy *InstancePtr, u8 QuadId, XVphy_ChannelId ChId, XVphy_DirectionType Dir, u32 PllClkInFreqHz)
This function will try to find the necessary PLL divisor values to produce the configured line rate given the specified PLL input frequency.
InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to calculate the PLL values for. ChId is the channel ID to calculate the PLL values for. Dir is an indicator for TX or RX. PllClkInFreqHz is the PLL input frequency on which to base the calculations on. A value of 0 indicates to use the currently configured quad PLL reference clock. A non-zero value indicates to ignore what is currently configured in SW, and use a custom frequency instead. XST_SUCCESS if valid PLL values were found to satisfy the constraints.XST_FAILURE otherwise. If successful, the channel's PllParams structure will be modified with the valid PLL parameters.
References XVphy::Config, XVphy_Channel::LineRateHz, XVphy::Quads, XVphy_Config::XcvrType, XVphy_Ch2Ids, XVphy_GetLineRateHz, XVphy_GetQuadRefClkFreq.
Referenced by XVphy_ClkCalcParams.
u32 XVphy_WriteCfgRefClkSelReg(XVphy *InstancePtr, u8 QuadId)
This function writes the current software configuration for the reference clock selections to hardware for the specified quad on all channels.
InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. XST_SUCCESS. None.
References XVphy_Config::BaseAddr, XVphy::Config, XVphy_Channel::CpllRefClkSel, XVphy::Quads, XVphy_Channel::RxDataRefClkSel, XVphy_Channel::RxOutRefClkSel, XVphy_Channel::TxDataRefClkSel, XVphy_Channel::TxOutRefClkSel, XVphy_Config::XcvrType, XVPHY_REF_CLK_SEL_CPLL_MASK, XVPHY_REF_CLK_SEL_CPLL_SHIFT, XVPHY_REF_CLK_SEL_QPLL0_MASK, XVPHY_REF_CLK_SEL_QPLL1_MASK, XVPHY_REF_CLK_SEL_QPLL1_SHIFT, XVPHY_REF_CLK_SEL_REG, XVPHY_REF_CLK_SEL_RXSYSCLKSEL_DATA_MASK, XVPHY_REF_CLK_SEL_RXSYSCLKSEL_DATA_SHIFT, XVPHY_REF_CLK_SEL_RXSYSCLKSEL_OUT_MASK, XVPHY_REF_CLK_SEL_RXSYSCLKSEL_OUT_SHIFT, XVPHY_REF_CLK_SEL_SYSCLKSEL_MASK, XVPHY_REF_CLK_SEL_TXSYSCLKSEL_DATA_MASK, XVPHY_REF_CLK_SEL_TXSYSCLKSEL_DATA_SHIFT, XVPHY_REF_CLK_SEL_TXSYSCLKSEL_OUT_MASK, XVPHY_REF_CLK_SEL_TXSYSCLKSEL_OUT_SHIFT, XVphy_WriteReg.
Referenced by XVphy_PllInitialize.
void XVphy_CfgPllRefClkSel(XVphy *InstancePtr, u8 QuadId, XVphy_ChannelId ChId, XVphy_PllRefClkSelType RefClkSel)
Configure the PLL reference clock selection for the specified channel(s).
This is applied to both direction to the software configuration only. InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. RefClkSel is the reference clock selection to configure. None. None.
References XVphy::Quads, XVphy_Ch2Ids.
Referenced by XVphy_PllInitialize.
void XVphy_CfgSysClkDataSel(XVphy *InstancePtr, u8 QuadId, XVphy_DirectionType Dir, XVphy_SysClkDataSelType SysClkDataSel)
Configure the SYSCLKDATA reference clock selection for the direction.
Same configuration applies to all channels in the quad. This is applied to the software configuration only. InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. SysClkDataSel is the reference clock selection to configure. None. None.
References XVphy::Quads, XVphy_Ch2Ids.
Referenced by XVphy_PllInitialize.
void XVphy_CfgSysClkOutSel(XVphy *InstancePtr, u8 QuadId, XVphy_DirectionType Dir, XVphy_SysClkOutSelType SysClkOutSel)
Configure the SYSCLKOUT reference clock selection for the direction.
Same configuration applies to all channels in the quad. This is applied to the software configuration only. InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. SysClkOutSel is the reference clock selection to configure. None. None.
References XVphy::Quads, XVphy_Ch2Ids.
Referenced by XVphy_PllInitialize.
u32 XVphy_ClkCalcParams(XVphy *InstancePtr, u8 QuadId, XVphy_ChannelId ChId, XVphy_DirectionType Dir, u32 PllClkInFreqHz)
This function will try to find the necessary PLL divisor values to produce the configured line rate given the specified PLL input frequency.
This will be done for all channels specified by ChId. This function is a wrapper for XVphy_PllCalculator. InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to calculate the PLL values for. ChId is the channel ID to calculate the PLL values for. Dir is an indicator for TX or RX. PllClkInFreqHz is the PLL input frequency on which to base the calculations on. A value of 0 indicates to use the currently configured quad PLL reference clock. A non-zero value indicates to ignore what is currently configured in SW, and use a custom frequency instead. XST_SUCCESS if valid PLL values were found to satisfy the constraints.XST_FAILURE otherwise. If successful, the channel's PllParams structure will be modified with the valid PLL parameters.
References XVphy_Ch2Ids, XVphy_PllCalculator.
u32 XVphy_OutDivReconfig(XVphy *InstancePtr, u8 QuadId, XVphy_ChannelId ChId, XVphy_DirectionType Dir)
This function will set the current output divider configuration over DRP.
InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID for which to write the settings for. Dir is an indicator for RX or TX. XST_SUCCESS if the configuration was successful.XST_FAILURE otherwise. None.
References XVphy_Ch2Ids, XVPHY_LOG_EVT_GT_RX_RECONFIG, XVPHY_LOG_EVT_GT_TX_RECONFIG.
u32 XVphy_DirReconfig(XVphy *InstancePtr, u8 QuadId, XVphy_ChannelId ChId, XVphy_DirectionType Dir)
This function will set the current RX/TX configuration over DRP.
InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID for which to write the settings for. Dir is an indicator for RX or TX. XST_SUCCESS if the configuration was successful.XST_FAILURE otherwise. None.
References XVphy::Config, XVphy_Config::RxProtocol, XVphy_Config::TxProtocol, XVphy_Config::XcvrType, XVphy_Ch2Ids, XVPHY_LOG_EVT_GT_RX_RECONFIG, XVPHY_LOG_EVT_GT_TX_RECONFIG.
u32 XVphy_ClkReconfig(XVphy *InstancePtr, u8 QuadId, XVphy_ChannelId ChId)
This function will set the current clocking settings for each channel to hardware based on the configuration stored in the driver's instance.
InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID for which to write the settings for. XST_SUCCESS if the configuration was successful.XST_FAILURE otherwise. None.
References XVphy::Config, XVphy::HdmiIsQpllPresent, XVphy_Config::XcvrType, XVphy_CfgErrIntr, XVphy_Ch2Ids, XVPHY_ERR_NO_QPLL, XVphy_ErrorHandler, XVphy_IsHDMI, XVPHY_LOG_EVT_CPLL_RECONFIG, XVPHY_LOG_EVT_NO_QPLL_ERR, XVPHY_LOG_EVT_PLL0_RECONFIG, XVPHY_LOG_EVT_PLL1_RECONFIG, XVPHY_LOG_EVT_QPLL_RECONFIG.
XVphy_ChannelId XVphy_GetRcfgChId(XVphy *InstancePtr, u8 QuadId, XVphy_DirectionType Dir, XVphy_PllType PllType)
Obtain the reconfiguration channel ID for given PLL type.
InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. PllType is the PLL type being used by the channel. The Channel ID to be used for reconfiguration None.
u32 XVphy_GetQuadRefClkFreq(XVphy *InstancePtr, u8 QuadId, XVphy_PllRefClkSelType RefClkType)
Obtain the current reference clock frequency for the quad based on the reference clock type.
InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. RefClkType is the type to obtain the clock selection for. The current reference clock frequency for the quad for the specified type selection. None.
References XVphy::Quads.
Referenced by XVphy_GetPllVcoFreqHz, XVphy_PllCalculator.
XVphy_SysClkDataSelType XVphy_GetSysClkDataSel(XVphy *InstancePtr, u8 QuadId, XVphy_DirectionType Dir, XVphy_ChannelId ChId)
Obtain the current [RT]XSYSCLKSEL[0] configuration.
InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. ChId is the channel ID which to operate on. The current [RT]XSYSCLKSEL[0] selection. None.
References XVphy_Config::BaseAddr, XVphy::Config, XVphy_Config::XcvrType, XVphy_ReadReg, XVPHY_REF_CLK_SEL_REG, XVPHY_REF_CLK_SEL_RXSYSCLKSEL_DATA_MASK, XVPHY_REF_CLK_SEL_RXSYSCLKSEL_DATA_SHIFT, XVPHY_REF_CLK_SEL_TXSYSCLKSEL_DATA_MASK, XVPHY_REF_CLK_SEL_TXSYSCLKSEL_DATA_SHIFT.
Referenced by XVphy_GetPllType, XVphy_IsBonded.
XVphy_SysClkOutSelType XVphy_GetSysClkOutSel(XVphy *InstancePtr, u8 QuadId, XVphy_DirectionType Dir, XVphy_ChannelId ChId)
Obtain the current [RT]XSYSCLKSEL[1] configuration.
InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. ChId is the channel ID which to operate on. The current [RT]XSYSCLKSEL[1] selection. None.
References XVphy_Config::BaseAddr, XVphy::Config, XVphy_Config::XcvrType, XVphy_ReadReg, XVPHY_REF_CLK_SEL_REG, XVPHY_REF_CLK_SEL_RXSYSCLKSEL_OUT_MASK, XVPHY_REF_CLK_SEL_RXSYSCLKSEL_OUT_SHIFT, XVPHY_REF_CLK_SEL_TXSYSCLKSEL_OUT_MASK, XVPHY_REF_CLK_SEL_TXSYSCLKSEL_OUT_SHIFT.
Referenced by XVphy_GetPllType, XVphy_IsBonded.
u32 XVphy_IsPllLocked(XVphy *InstancePtr, u8 QuadId, XVphy_ChannelId ChId)
This function will check the status of a PLL lock on the specified channel.
InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID which to operate on. XST_SUCCESS if the specified PLL is locked.XST_FAILURE otherwise. None.
References XVphy_Config::BaseAddr, XVphy::Config, XVphy_GetPllType, XVphy_IsHDMI, XVPHY_PLL_LOCK_STATUS_CPLL_ALL_MASK, XVPHY_PLL_LOCK_STATUS_CPLL_HDMI_MASK, XVPHY_PLL_LOCK_STATUS_CPLL_MASK, XVPHY_PLL_LOCK_STATUS_QPLL0_MASK, XVPHY_PLL_LOCK_STATUS_QPLL1_MASK, XVPHY_PLL_LOCK_STATUS_REG, XVphy_ReadReg.
u32 XVphy_GtUserRdyEnable(XVphy *InstancePtr, u8 QuadId, XVphy_ChannelId ChId, XVphy_DirectionType Dir, u8 Hold)
This function will reset and enable the Video PHY's user core logic.
InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID which to operate on. Dir is an indicator for TX or RX. Hold is an indicator whether to "hold" the reset if set to 1. If set to 0: reset, then enable. XST_SUCCESS. None.
References XVphy_Config::BaseAddr, XVphy::Config, XVphy_ReadReg, XVPHY_RX_INIT_REG, XVPHY_RX_INIT_USERRDY_ALL_MASK, XVPHY_RX_INIT_USERRDY_MASK, XVPHY_TX_INIT_REG, XVPHY_TX_INIT_USERRDY_ALL_MASK, XVPHY_TX_INIT_USERRDY_MASK, XVphy_WriteReg.
u32 XVphy_Gthe4CfgCpllCalPeriodandTol(XVphy *InstancePtr, u8 QuadId, XVphy_ChannelId ChId, XVphy_DirectionType Dir, u32 FreeRunClkFreq)
u32 XVphy_Gtye4CfgCpllCalPeriodandTol(XVphy *InstancePtr, u8 QuadId, XVphy_ChannelId ChId, XVphy_DirectionType Dir, u32 FreeRunClkFreq)
u32 XVphy_MmcmWriteParameters(XVphy *InstancePtr, u8 QuadId, XVphy_DirectionType Dir)
This function will write the mixed-mode clock manager (MMCM) values currently stored in the driver's instance structure to hardware .
InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. XST_SUCCESS if the MMCM write was successful.XST_FAILURE otherwise, if the configuration success bit did not go low. None.
References XVphy_Quad::Mmcm, XVphy::Quads, XVphy_DrpWr, XVphy_IsHDMI.
Referenced by XVphy_MmcmStart.
void XVphy_MmcmReset(XVphy *InstancePtr, u8 QuadId, XVphy_DirectionType Dir, u8 Hold)
This function will reset the mixed-mode clock manager (MMCM) core.
InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. Hold is an indicator whether to "hold" the reset if set to 1. If set to 0: reset, then enable. XST_SUCCESS. None.
References XVphy_Config::BaseAddr, XVphy::Config, XVPHY_MMCM_RXUSRCLK_CTRL_REG, XVPHY_MMCM_TXUSRCLK_CTRL_REG, XVphy_ReadReg, XVphy_WriteReg.
Referenced by XVphy_MmcmStart.
void XVphy_MmcmLockedMaskEnable(XVphy *InstancePtr, u8 QuadId, XVphy_DirectionType Dir, u8 Enable)
This function will reset the mixed-mode clock manager (MMCM) core.
InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. Enable is an indicator whether to "Enable" the locked mask if set to 1. If set to 0: reset, then disable. None. None.
References XVphy_Config::BaseAddr, XVphy::Config, XVPHY_MMCM_RXUSRCLK_CTRL_REG, XVPHY_MMCM_TXUSRCLK_CTRL_REG, XVphy_ReadReg, XVphy_WriteReg.
Referenced by XVphy_MmcmStart.
u8 XVphy_MmcmLocked(XVphy *InstancePtr, u8 QuadId, XVphy_DirectionType Dir)
This function will get the lock status of the mixed-mode clock manager (MMCM) core.
InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. TRUE if Locked else FALSE. None.
References XVphy_Config::BaseAddr, XVphy::Config, XVPHY_MMCM_RXUSRCLK_CTRL_REG, XVPHY_MMCM_TXUSRCLK_CTRL_REG, XVphy_ReadReg.
void XVphy_SetBufgGtDiv(XVphy *InstancePtr, XVphy_DirectionType Dir, u8 Div)
This function obtains the divider value of the BUFG_GT peripheral.
InstancePtr is a pointer to the XVphy core instance. Dir is an indicator for TX or RX Div 3-bit divider value None.
References XVphy_Config::BaseAddr, XVphy::Config, XVPHY_BUFGGT_RXUSRCLK_REG, XVPHY_BUFGGT_TXUSRCLK_REG, XVphy_ReadReg, XVphy_WriteReg.
u32 XVphy_PowerDownGtPll(XVphy *InstancePtr, u8 QuadId, XVphy_ChannelId ChId, u8 Hold)
This function will power down the specified GT PLL.
InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to power down the PLL for. Hold is an indicator whether to "hold" the power down if set to 1. If set to 0: power down, then power back up. XST_SUCCESS. None.
References XVphy_Config::BaseAddr, XVphy::Config, XVphy_Ch2Ids, XVPHY_POWERDOWN_CONTROL_CPLLPD_MASK, XVPHY_POWERDOWN_CONTROL_QPLL0PD_MASK, XVPHY_POWERDOWN_CONTROL_QPLL1PD_MASK, XVPHY_POWERDOWN_CONTROL_REG, XVphy_ReadReg, XVphy_WriteReg.
void XVphy_SetIntrHandler(XVphy *InstancePtr, XVphy_IntrHandlerType HandlerType, XVphy_IntrHandler CallbackFunc, void *CallbackRef)
This function installs a callback function for the specified handler type.
InstancePtr is a pointer to the XVPhy instance. HandlerType is the interrupt handler type which specifies which interrupt event to attach the callback for. CallbackFunc is the address to the callback function. CallbackRef is the user data item that will be passed to the callback function when it is invoked. None. None.
References XVphy::IntrCpllLockCallbackRef, XVphy::IntrCpllLockHandler, XVphy::IntrQpll1LockCallbackRef, XVphy::IntrQpll1LockHandler, XVphy::IntrQpllLockCallbackRef, XVphy::IntrQpllLockHandler, XVphy::IntrRxClkDetFreqChangeCallbackRef, XVphy::IntrRxClkDetFreqChangeHandler, XVphy::IntrRxMmcmLockCallbackRef, XVphy::IntrRxMmcmLockHandler, XVphy::IntrRxResetDoneCallbackRef, XVphy::IntrRxResetDoneHandler, XVphy::IntrRxTmrTimeoutCallbackRef, XVphy::IntrRxTmrTimeoutHandler, XVphy::IntrTxAlignDoneCallbackRef, XVphy::IntrTxAlignDoneHandler, XVphy::IntrTxClkDetFreqChangeCallbackRef, XVphy::IntrTxClkDetFreqChangeHandler, XVphy::IntrTxMmcmLockCallbackRef, XVphy::IntrTxMmcmLockHandler, XVphy::IntrTxResetDoneCallbackRef, XVphy::IntrTxResetDoneHandler, XVphy::IntrTxTmrTimeoutCallbackRef, XVphy::IntrTxTmrTimeoutHandler.
void XVphy_IntrEnable(XVphy *InstancePtr, XVphy_IntrHandlerType Intr)
This function enables interrupts associated with the specified interrupt type.
InstancePtr is a pointer to the XVphy instance. Intr is the interrupt type/mask to enable. None. None.
References XVphy_Config::BaseAddr, XVphy::Config, XVPHY_INTR_EN_REG, XVphy_ReadReg, XVphy_WriteReg.
void XVphy_IntrDisable(XVphy *InstancePtr, XVphy_IntrHandlerType Intr)
This function disabled interrupts associated with the specified interrupt type.
InstancePtr is a pointer to the XVphy instance. Intr is the interrupt type/mask to disable. None. None.
References XVphy_Config::BaseAddr, XVphy::Config, XVPHY_INTR_DIS_REG, XVphy_ReadReg, XVphy_WriteReg.
void XVphy_CfgErrIntr(XVphy *InstancePtr, XVphy_ErrType ErrIrq, u8 Set)
This function configures the error IRQ register based on the condition to generate an ERR_IRQ event.
InstancePtr is a pointer to the XVphy instance. ErrIrq is the IRQ type as defined in XVphy_ErrType. Set is the flag to set or clear the ErrIrq param. None. None.
References XVphy_Config::BaseAddr, XVphy::Config, XVPHY_ERR_IRQ, XVphy_ReadReg, XVphy_WriteReg.
Referenced by XVphy_ClkReconfig.
u64 XVphy_GetPllVcoFreqHz(XVphy *InstancePtr, u8 QuadId, XVphy_ChannelId ChId, XVphy_DirectionType Dir)
This function calculates the PLL VCO operating frequency.
InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to calculate the VCO frequency for. Dir is an indicator for TX or RX. PLL VCO frequency in Hz None.
References XVphy::HdmiRxDruIsEnabled, XVphy::HdmiRxRefClkHz, XVphy::HdmiTxRefClkHz, XVphy::Quads, XVphy_GetQuadRefClkFreq, XVphy_IsHDMI.
u8 XVphy_GetRefClkSourcesCount(XVphy *InstancePtr)
This function returns the number of active reference clock sources based in the CFG.
InstancePtr is a pointer to the XVphy core instance. No of active REFCLK sources None.
References XVphy::Config, XVphy_Config::DruIsPresent, XVphy_Config::DruRefClkSel, XVphy_Config::RxProtocol, XVphy_Config::RxRefClkSel, XVphy_Config::TxProtocol, XVphy_Config::TxRefClkSel.
u8 XVphy_IsHDMI(XVphy *InstancePtr, XVphy_DirectionType Dir)
This function checks if Instance is HDMI 2.0 or HDMI 2.1.
InstancePtr is a pointer to the VPHY instance. Dir is an indicator for RX or TX. TRUE if HDMI 2.0 or 2.1 else FALSE. None.
References XVphy::Config, XVphy_Config::RxProtocol, XVphy_Config::TxProtocol.
Referenced by XVphy_Ch2Ids, XVphy_ClkReconfig, XVphy_GetPllVcoFreqHz, XVphy_IsPllLocked, XVphy_MmcmStart, XVphy_MmcmWriteParameters.
void XVphy_HdmiTxTimerTimeoutHandler(XVphy *InstancePtr)
void XVphy_HdmiRxTimerTimeoutHandler(XVphy *InstancePtr)
void XVphy_ErrorHandler(XVphy *InstancePtr)
This function is the error condition handler.
InstancePtr is a pointer to the VPHY instance. None. None.
References XVphy::ErrorCallback, XVphy::ErrorRef.
Referenced by XVphy_ClkReconfig.