xvphy.h
XV_VPHY_LOG_ENABLE
XPAR_VPHY_0_TRANSCEIVER
XVPHY_CH2IDX
XVPHY_ISCH
XVPHY_ISCMN
XVPHY_ISTXMMCM
XVPHY_ISRXMMCM
XVphy_IsTxUsingQpll
XVphy_IsRxUsingQpll
XVphy_IsTxUsingCpll
XVphy_IsRxUsingCpll
XVPHY_GTXE2
XVPHY_GTHE2
XVPHY_GTPE2
XVPHY_GTHE3
XVPHY_GTHE4
XVPHY_GTYE4
XVPHY_GTYE4_CHANNEL_ADAPT_CFG1
XVPHY_GTYE4_CHANNEL_CKCAL1_CFG_0
XVPHY_GTYE4_CHANNEL_CKCAL1_CFG_1
XVPHY_GTYE4_CHANNEL_CKCAL2_CFG_0
XVPHY_GTYE4_CHANNEL_CKCAL2_CFG_1
XVPHY_GTYE4_CHANNEL_TXDRV_FREQBAND
XVPHY_GTYE4_CHANNEL_TXFE_CFG1
XVPHY_GTYE4_CHANNEL_TXFE_CFG2
XVPHY_GTYE4_CHANNEL_TXFE_CFG3
XVPHY_GTYE4_CHANNEL_TXPHDLY_CFG1
XVPHY_GTYE4_CHANNEL_TXPI_CFG0
XVPHY_GTYE4_CHANNEL_TXPI_CFG1
XVPHY_GTYE4_CHANNEL_TX_PI_BIASSET
XVPHY_GTYE4_CHANNEL_CH_HSPMUX
XVPHY_GTYE4_CHANNEL_TXOUT_DIV
XVPHY_GTYE4_CHANNEL_RTX_BUF_CML_CTRL
XVPHY_GTYE4_CHANNEL_TX_CLK25_DIV
XVphy_GtType
XVphy_ProtocolType
XVphy_DirectionType
XVphy_ClkPrimitive
XVphy_IntrHandlerType
XVphy_HdmiHandlerType
TX init handler.
XVphy_PllType
XVphy_ChannelId
XVphy_PllRefClkSelType
XVphy_SysClkDataSelType
XVphy_SysClkOutSelType
XVphy_OutClkSelType
XVphy_GtState
Idle state.
XVphy_LogEvent
Log event none.
XVphy_MmcmDivType
M - CLKFBOUT multiplier.
XVphy_ErrType
QPLL CFG not found.
XVphy_HdmiTx_Patgen
LR:Clock Ratio = 10.
XVphy_PrbsPattern
Pattern gen/mon OFF.
typedef void(* XVphy_IntrHandler)(void *InstancePtr))(void *InstancePtr)
Callback type which represents the handler for interrupts.
InstancePtr is a pointer to the XVphy instance. None.
typedef void(* XVphy_TimerHandler)(void *InstancePtr, u32 MicroSeconds))(void *InstancePtr, u32 MicroSeconds)
Callback type which represents a custom timer wait handler.
This is only used for Microblaze since it doesn't have a native sleep function. To avoid dependency on a hardware timer, the default wait functionality is implemented using loop iterations; this isn't too accurate. If a custom timer handler is used, the user may implement their own wait implementation using a hardware timer (see example/) for better accuracy. InstancePtr is a pointer to the XVphy instance. MicroSeconds is the number of microseconds to be passed to the timer function. None.
typedef void(* XVphy_Callback)(void *CallbackRef))(void *CallbackRef)
Generic callback type.
CallbackRef is a pointer to the callback reference. None.
typedef void(* XVphy_ErrorCallback)(void *CallbackRef))(void *CallbackRef)
Error callback type.
CallbackRef is a pointer to the callback reference. None.
void XVphy_CfgInitialize(XVphy *InstancePtr, XVphy_Config *ConfigPtr, UINTPTR EffectiveAddr)
This function retrieves the configuration for this Video PHY instance and fills in the InstancePtr->Config structure.
InstancePtr is a pointer to the XVphy instance. ConfigPtr is a pointer to the configuration structure that will be used to copy the settings from. EffectiveAddr is the device base address in the virtual memory space. If the address translation is not used, then the physical address is passed. None. Unexpected errors may occur if the address mapping is changed after this function is invoked.
References XVphy::IsReady, XVphy::Config, XVphy_Config::BaseAddr, XVphy_Config::XcvrType, XVphy_Config::TxSysPllClkSel, XVphy_Config::RxSysPllClkSel, XVphy_Config::TxRefClkSel, XVphy_Config::RxRefClkSel, XVphy_Config::DruRefClkSel.
u32 XVphy_PllInitialize(XVphy *InstancePtr, u8 QuadId, XVphy_ChannelId ChId, XVphy_PllRefClkSelType QpllRefClkSel, XVphy_PllRefClkSelType CpllxRefClkSel, XVphy_PllType TxPllSelect, XVphy_PllType RxPllSelect)
This function will initialize the PLL selection for a given channel.
InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. QpllRefClkSel is the QPLL reference clock selection for the quad. In GTP, this is used to hold PLL0 refclk selection. CpllRefClkSel is the CPLL reference clock selection for the quad. In GTP, this is used to hold PLL1 refclk selection. TxPllSelect is the reference clock selection for the quad's TX PLL dividers. RxPllSelect is the reference clock selection for the quad's RX PLL dividers. XST_SUCCESS. None.
References XVphy::Config, XVphy_Config::XcvrType, XVphy_CfgPllRefClkSel, XVphy_CfgSysClkDataSel, Pll2SysClkData, XVphy_CfgSysClkOutSel, Pll2SysClkOut, XVphy_WriteCfgRefClkSelReg.
u32 XVphy_GetVersion(XVphy *InstancePtr)
This function will obtian the IP version.
InstancePtr is a pointer to the XVphy core instance. The IP version of the Video PHY core. None.
References XVphy_ReadReg, XVphy::Config, XVphy_Config::BaseAddr, XVPHY_VERSION_REG.
void XVphy_WaitUs(XVphy *InstancePtr, u32 MicroSeconds)
This function is the delay/sleep function for the XVphy driver.
For the Zynq family, there exists native sleep functionality. For MicroBlaze however, there does not exist such functionality. In the MicroBlaze case, the default method for delaying is to use a predetermined amount of loop iterations. This method is prone to inaccuracy and dependent on system configuration; for greater accuracy, the user may supply their own delay/sleep handler, pointed to by InstancePtr->UserTimerWaitUs, which may have better accuracy if a hardware timer is used. InstancePtr is a pointer to the XVphy instance. MicroSeconds is the number of microseconds to delay/sleep for. None. None.
References XVphy::IsReady, XVphy::UserTimerWaitUs.
Referenced by XVphy_MmcmStart.
void XVphy_SetUserTimerHandler(XVphy *InstancePtr, XVphy_TimerHandler CallbackFunc, void *CallbackRef)
u32 XVphy_CfgLineRate(XVphy *InstancePtr, u8 QuadId, XVphy_ChannelId ChId, u64 LineRateHz)
Configure the channel's line rate.
This is a software only configuration and this value is used in the PLL calculator. InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. LineRateHz is the line rate in Hz to configure software. XST_SUCCESS if the reference clock type is valid.XST_FAILURE otherwise. None.
References XVphy_Ch2Ids, XVphy::Quads, XVphy_Channel::LineRateHz.
XVphy_PllType XVphy_GetPllType(XVphy *InstancePtr, u8 QuadId, XVphy_DirectionType Dir, XVphy_ChannelId ChId)
Obtain the channel's PLL reference clock selection.
InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. ChId is the channel ID which to operate on. The PLL type being used by the channel. None.
References XVphy_GetSysClkDataSel, XVphy_GetSysClkOutSel, XVphy::Config, XVphy_Config::XcvrType.
Referenced by XVphy_IsPllLocked.
u64 XVphy_GetLineRateHz(XVphy *InstancePtr, u8 QuadId, XVphy_ChannelId ChId)
This function will return the line rate in Hz for a given channel / quad.
InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to check. ChId is the channel ID for which to retrieve the line rate. The line rate in Hz. None.
References XVphy::Quads, XVphy_Channel::LineRateHz.
Referenced by XVphy_PllCalculator.
u32 XVphy_ResetGtPll(XVphy *InstancePtr, u8 QuadId, XVphy_ChannelId ChId, XVphy_DirectionType Dir, u8 Hold)
This function will reset the GT's PLL logic.
InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID which to operate on. Dir is an indicator for TX or RX. Hold is an indicator whether to "hold" the reset if set to 1. If set to 0: reset, then enable. XST_SUCCESS. None.
References XVPHY_TX_INIT_REG, XVPHY_RX_INIT_REG, XVPHY_TXRX_INIT_PLLGTRESET_ALL_MASK, XVPHY_TXRX_INIT_PLLGTRESET_MASK, XVphy_ReadReg, XVphy::Config, XVphy_Config::BaseAddr, XVphy_WriteReg.
u32 XVphy_ResetGtTxRx(XVphy *InstancePtr, u8 QuadId, XVphy_ChannelId ChId, XVphy_DirectionType Dir, u8 Hold)
This function will reset the GT's TX/RX logic.
InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID which to operate on. Dir is an indicator for TX or RX. Hold is an indicator whether to "hold" the reset if set to 1. If set to 0: reset, then enable. XST_SUCCESS. None.
References XVPHY_TX_INIT_REG, XVPHY_RX_INIT_REG, XVPHY_TXRX_INIT_GTRESET_ALL_MASK, XVPHY_TXRX_INIT_GTRESET_MASK, XVphy_ReadReg, XVphy::Config, XVphy_Config::BaseAddr, XVphy_WriteReg.
u32 XVphy_SetPolarity(XVphy *InstancePtr, u8 QuadId, XVphy_ChannelId ChId, XVphy_DirectionType Dir, u8 Polarity)
This function will set/clear the TX/RX polarity bit.
InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID which to operate on. Dir is an indicator for TX or RX. Polarity 0-Not inverted 1-Inverted XST_SUCCESS. None.
References XVPHY_TX_CONTROL_REG, XVPHY_RX_CONTROL_REG, XVphy_ReadReg, XVphy::Config, XVphy_Config::BaseAddr, XVphy_WriteReg.
u32 XVphy_SetPrbsSel(XVphy *InstancePtr, u8 QuadId, XVphy_ChannelId ChId, XVphy_DirectionType Dir, XVphy_PrbsPattern Pattern)
This function will set the TX/RXPRBSEL of the GT.
InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID which to operate on. Dir is an indicator for TX or RX. Pattern is the pattern XVphy_PrbsPattern XST_SUCCESS. None.
References XVPHY_TX_CONTROL_REG, XVPHY_RX_CONTROL_REG, XVphy_ReadReg, XVphy::Config, XVphy_Config::BaseAddr, XVphy_Ch2Ids, XVphy_WriteReg.
u32 XVphy_TxPrbsForceError(XVphy *InstancePtr, u8 QuadId, XVphy_ChannelId ChId, u8 ForceErr)
This function will set the TX/RXPRBSEL of the GT.
InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID which to operate on. ForceErr 0-No Error 1-Force Error XST_SUCCESS. None.
References XVphy_ReadReg, XVphy::Config, XVphy_Config::BaseAddr, XVPHY_TX_CONTROL_REG, XVphy_WriteReg.
void XVphy_SetTxVoltageSwing(XVphy *InstancePtr, u8 QuadId, XVphy_ChannelId ChId, u8 Vs)
This function will set the TX voltage swing value for a given channel.
InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. Vs is the voltage swing value to write. None. None.
References XVPHY_TX_DRIVER_CH12_REG, XVPHY_TX_DRIVER_CH34_REG, XVphy_ReadReg, XVphy::Config, XVphy_Config::BaseAddr, XVphy_WriteReg.
void XVphy_SetTxPreEmphasis(XVphy *InstancePtr, u8 QuadId, XVphy_ChannelId ChId, u8 Pe)
This function will set the TX pre-emphasis value for a given channel.
InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. Pe is the pre-emphasis value to write. None. None.
References XVPHY_TX_DRIVER_CH12_REG, XVPHY_TX_DRIVER_CH34_REG, XVphy_ReadReg, XVphy::Config, XVphy_Config::BaseAddr, XVphy_WriteReg.
void XVphy_SetTxPostCursor(XVphy *InstancePtr, u8 QuadId, XVphy_ChannelId ChId, u8 Pc)
This function will set the TX post-cursor value for a given channel.
InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. Pc is the post-cursor value to write. None. None.
References XVPHY_TX_DRIVER_CH12_REG, XVPHY_TX_DRIVER_CH34_REG, XVphy_ReadReg, XVphy::Config, XVphy_Config::BaseAddr, XVphy_WriteReg.
void XVphy_SetRxLpm(XVphy *InstancePtr, u8 QuadId, XVphy_ChannelId ChId, XVphy_DirectionType Dir, u8 Enable)
This function will enable or disable the LPM logic in the Video PHY core.
InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. Dir is an indicator for TX or RX. Enable will enable (if 1) or disable (if 0) the LPM logic. None. None.
References XVphy_ReadReg, XVphy::Config, XVphy_Config::BaseAddr, XVPHY_RX_EQ_CDR_REG, XVphy_WriteReg.
u32 XVphy_DrpWr(XVphy *InstancePtr, u8 QuadId, XVphy_ChannelId ChId, u16 Addr, u16 Val)
This function will initiate a write DRP transaction.
It is a wrapper around XVphy_DrpAccess. InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID on which to direct the DRP access. Addr is the DRP address to issue the DRP access to. Val is the value to write to the DRP address. XST_SUCCESS if the DRP access was successful.XST_FAILURE otherwise, if the busy bit did not go low, or if the ready bit did not go high. None.
Referenced by XVphy_MmcmWriteParameters.
u16 XVphy_DrpRd(XVphy *InstancePtr, u8 QuadId, XVphy_ChannelId ChId, u16 Addr, u16 *RetVal)
This function will initiate a read DRP transaction.
It is a wrapper around XVphy_DrpAccess. InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID on which to direct the DRP access. Addr is the DRP address to issue the DRP access to. RetVal is the DRP read_value returned implicitly. XST_SUCCESS if the DRP access was successful.XST_FAILURE otherwise, if the busy bit did not go low, or if the ready bit did not go high. None.
Referenced by XVphy_RegisterDebug.
void XVphy_MmcmPowerDown(XVphy *InstancePtr, u8 QuadId, XVphy_DirectionType Dir, u8 Hold)
This function will power down the mixed-mode clock manager (MMCM) core.
InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. Hold is an indicator whether to "hold" the power down if set to 1. If set to 0: power down, then power back up. XST_SUCCESS. None.
References XVPHY_MMCM_TXUSRCLK_CTRL_REG, XVPHY_MMCM_RXUSRCLK_CTRL_REG, XVphy_ReadReg, XVphy::Config, XVphy_Config::BaseAddr, XVphy_WriteReg.
Referenced by XVphy_MmcmStart.
void XVphy_MmcmStart(XVphy *InstancePtr, u8 QuadId, XVphy_DirectionType Dir)
This function will start the mixed-mode clock manager (MMCM) core.
InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. None. None.
References XVphy::Config, XVphy_Config::TxProtocol, XVphy_Config::RxProtocol, XVphy_MmcmPowerDown, XVphy_WaitUs, XVphy_MmcmReset, XVphy_MmcmWriteParameters, XVphy_IsHDMI, XVphy::Quads, XVphy_Quad::RxMmcm, XVphy_Quad::TxMmcm, XVphy_MmcmLockedMaskEnable, XVPHY_LOG_EVT_TXPLL_RECONFIG, XVPHY_LOG_EVT_RXPLL_RECONFIG.
void XVphy_IBufDsEnable(XVphy *InstancePtr, u8 QuadId, XVphy_DirectionType Dir, u8 Enable)
This function enables the TX or RX IBUFDS peripheral.
InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. Enable specifies TRUE/FALSE value to either enable or disable the IBUFDS, respectively. None.
References XVPHY_IBUFDS_GTXX_CTRL_REG, XVphy::Config, XVphy_Config::TxRefClkSel, XVphy_Config::RxRefClkSel, XVphy_Config::DruIsPresent, XVphy_Config::DruRefClkSel, XVPHY_IBUFDS_GTXX_CTRL_GTREFCLK0_CEB_MASK, XVPHY_IBUFDS_GTXX_CTRL_GTREFCLK1_CEB_MASK, XVPHY_MISC_TXUSRCLK_REG, XVPHY_MISC_RXUSRCLK_REG, XVphy_ReadReg, XVphy_Config::BaseAddr, XVphy_WriteReg.
void XVphy_Clkout1OBufTdsEnable(XVphy *InstancePtr, XVphy_DirectionType Dir, u8 Enable)
This function enables the TX or RX CLKOUT1 OBUFTDS peripheral.
InstancePtr is a pointer to the XVphy core instance. Dir is an indicator for TX or RX. Enable specifies TRUE/FALSE value to either enable or disable the OBUFTDS, respectively. None.
References XVPHY_MISC_TXUSRCLK_REG, XVPHY_MISC_RXUSRCLK_REG, XVphy_ReadReg, XVphy::Config, XVphy_Config::BaseAddr, XVphy_WriteReg.
u32 XVphy_IsBonded(XVphy *InstancePtr, u8 QuadId, XVphy_ChannelId ChId)
This function returns true when the RX and TX are bonded and are running from the same (RX) reference clock.
InstancePtr is a pointer to the XVphy core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to check. TRUE if the RX and TX are using the same PLL, FALSE otherwise. None.
References XVphy_GetSysClkDataSel, XVphy_GetSysClkOutSel.
void XVphy_SetErrorCallback(XVphy *InstancePtr, void *CallbackFunc, void *CallbackRef)
This function installs a callback function for the VPHY error conditions.
InstancePtr is a pointer to the XVPhy instance. CallbackFunc is the address to the callback function. CallbackRef is the user data item that will be passed to the callback function when it is invoked. None. The XVphy_ErrorHandler API calls the registered function in ErrorCallback and passes two arguments: 1) CallbackRef 2) Error Type as defined by XVphy_ErrType. Sample Function Call: CallbackFunc(CallbackRef, XVphy_ErrType);
References XVphy::ErrorCallback, XVphy::ErrorRef.
void XVphy_LogDisplay(XVphy *InstancePtr)
This function will print the entire log.
InstancePtr is a pointer to the XVphy core instance. None. None.
void XVphy_LogReset(XVphy *InstancePtr)
This function will reset the driver's logginc mechanism.
InstancePtr is a pointer to the XVphy core instance. None. None.
u16 XVphy_LogRead(XVphy *InstancePtr)
This function will read the last event from the log.
InstancePtr is a pointer to the XVphy core instance. The log data. None.
void XVphy_LogWrite(XVphy *InstancePtr, XVphy_LogEvent Evt, u8 Data)
This function will insert an event in the driver's logginc mechanism.
InstancePtr is a pointer to the XVphy core instance. Evt is the event type to log. Data is the associated data for the event. None. None.
void XVphy_InterruptHandler(XVphy *InstancePtr)
This function is the interrupt handler for the XVphy driver.
It will detect what kind of interrupt has happened, and will invoke the appropriate callback function. InstancePtr is a pointer to the XVphy instance. None. None.
References XVphy::IsReady, XVphy_ReadReg, XVphy::Config, XVphy_Config::BaseAddr, XVPHY_INTR_STS_REG, XVphy::IntrCpllLockHandler, XVphy::IntrCpllLockCallbackRef, XVphy::IntrQpllLockHandler, XVphy::IntrQpllLockCallbackRef, XVphy::IntrQpll1LockHandler, XVphy::IntrQpll1LockCallbackRef, XVphy::IntrTxResetDoneHandler, XVphy::IntrTxResetDoneCallbackRef, XVphy::IntrTxAlignDoneHandler, XVphy::IntrTxAlignDoneCallbackRef, XVphy::IntrRxResetDoneHandler, XVphy::IntrRxResetDoneCallbackRef, XVphy::IntrTxClkDetFreqChangeHandler, XVphy::IntrTxClkDetFreqChangeCallbackRef, XVphy::IntrRxClkDetFreqChangeHandler, XVphy::IntrRxClkDetFreqChangeCallbackRef, XVphy::IntrTxMmcmLockHandler, XVphy::IntrTxMmcmLockCallbackRef, XVphy::IntrRxMmcmLockHandler, XVphy::IntrRxMmcmLockCallbackRef, XVphy::IntrTxTmrTimeoutHandler, XVphy::IntrTxTmrTimeoutCallbackRef, XVphy::IntrRxTmrTimeoutHandler, XVphy::IntrRxTmrTimeoutCallbackRef.
u32 XVphy_SelfTest(XVphy *InstancePtr)
This function runs a self-test on the XVphy driver/device.
The sanity test checks whether or not all tested registers hold their default reset values. InstancePtr is a pointer to the XVphy instance. XST_SUCCESS if the self-test passed - all tested registers hold their default reset values.XST_FAILURE otherwise. None.
References XVphy_ReadReg, XVphy::Config, XVphy_Config::BaseAddr.
XVphy_Config* XVphy_LookupConfig(UINTPTR BaseAddress)
This function looks for the device configuration based on the unique device ID.
The table XVphy_ConfigTable[] contains the configuration information for each device in the system. DeviceId is the unique device ID of the device being looked up. A pointer to the configuration table entry corresponding to the given device ID, or NULL if no match is found. None.
u32 XVphy_DpInitialize(XVphy *InstancePtr, XVphy_Config *CfgPtr, u8 QuadId, XVphy_PllRefClkSelType CpllRefClkSel, XVphy_PllRefClkSelType QpllRefClkSel, XVphy_PllType TxPllSelect, XVphy_PllType RxPllSelect, u8 LinkRate)
u32 XVphy_Hdmi_CfgInitialize(XVphy *InstancePtr, u8 QuadId, XVphy_Config *CfgPtr)
u32 XVphy_SetHdmiTxParam(XVphy *InstancePtr, u8 QuadId, XVphy_ChannelId ChId, XVidC_PixelsPerClock Ppc, XVidC_ColorDepth Bpc, XVidC_ColorFormat ColorFormat)
u32 XVphy_SetHdmiRxParam(XVphy *InstancePtr, u8 QuadId, XVphy_ChannelId ChId)
u32 XVphy_HdmiCfgCalcMmcmParam(XVphy *InstancePtr, u8 QuadId, XVphy_ChannelId ChId, XVphy_DirectionType Dir, XVidC_PixelsPerClock Ppc, XVidC_ColorDepth Bpc)
void XVphy_HdmiUpdateClockSelection(XVphy *InstancePtr, u8 QuadId, XVphy_SysClkDataSelType TxSysPllClkSel, XVphy_SysClkDataSelType RxSysPllClkSel)
void XVphy_ClkDetFreqReset(XVphy *InstancePtr, u8 QuadId, XVphy_DirectionType Dir)
u32 XVphy_ClkDetGetRefClkFreqHz(XVphy *InstancePtr, XVphy_DirectionType Dir)
u32 XVphy_ClkDetGetRefClkFreqRawHz(XVphy *InstancePtr, XVphy_DirectionType Dir)
u32 XVphy_DruGetRefClkFreqHz(XVphy *InstancePtr)
u32 XVphy_DruGetRefClkFreqRawHz(XVphy *InstancePtr)
void XVphy_HdmiDebugInfo(XVphy *InstancePtr, u8 QuadId, XVphy_ChannelId ChId)
void XVphy_DpDebugInfo(XVphy *InstancePtr, u8 QuadId, XVphy_ChannelId ChId)
void XVphy_SetHdmiCallback(XVphy *InstancePtr, XVphy_HdmiHandlerType HandlerType, void *CallbackFunc, void *CallbackRef)
void XVphy_RegisterDebug(XVphy *InstancePtr)
This function prints out Video PHY register and GT Channel and Common DRP register contents.
InstancePtr is a pointer to the Vphy core instance. None. None.
References XVphy_ReadReg, XVphy::Config, XVphy_Config::BaseAddr, XVphy::HdmiIsQpllPresent, XVphy_Config::TxProtocol, XVphy_Config::RxProtocol, XVphy_DrpRd, XVphy_Config::XcvrType, XVphy_Config::RxChannels, XVphy_Config::TxChannels.