/*******************************************************************
* Copyright (c) 1986 - 2020 Xilinx, Inc. All rights reserved.
* SPDX-License-Identifier: MIT

*******************************************************************************/



#include "xparameters.h"
#include "xtpg.h"

/*
* The configuration table for devices
*/

XTpg_Config XTpg_ConfigTable[] =
{
	{
		XPAR_FMC_HDMI_INPUT_V_TPG_1_DEVICE_ID,
		XPAR_FMC_HDMI_INPUT_V_TPG_1_BASEADDR,
		XPAR_FMC_HDMI_INPUT_V_TPG_1_S_AXIS_VIDEO_FORMAT,
		XPAR_FMC_HDMI_INPUT_V_TPG_1_M_AXIS_VIDEO_FORMAT,
		XPAR_FMC_HDMI_INPUT_V_TPG_1_S_AXI_CLK_FREQ_HZ,
		XPAR_FMC_HDMI_INPUT_V_TPG_1_ACTIVE_ROWS,
		XPAR_FMC_HDMI_INPUT_V_TPG_1_ACTIVE_COLS,
		XPAR_FMC_HDMI_INPUT_V_TPG_1_PATTERN_CONTROL,
		XPAR_FMC_HDMI_INPUT_V_TPG_1_MOTION_SPEED,
		XPAR_FMC_HDMI_INPUT_V_TPG_1_CROSS_HAIRS,
		XPAR_FMC_HDMI_INPUT_V_TPG_1_ZPLATE_HOR_CONTROL,
		XPAR_FMC_HDMI_INPUT_V_TPG_1_ZPLATE_VER_CONTROL,
		XPAR_FMC_HDMI_INPUT_V_TPG_1_BOX_SIZE,
		XPAR_FMC_HDMI_INPUT_V_TPG_1_BOX_COLOR,
		XPAR_FMC_HDMI_INPUT_V_TPG_1_STUCK_PIXEL_THRESH,
		XPAR_FMC_HDMI_INPUT_V_TPG_1_NOISE_GAIN,
		XPAR_FMC_HDMI_INPUT_V_TPG_1_BAYER_PHASE,
		XPAR_FMC_HDMI_INPUT_V_TPG_1_HAS_INTC_IF,
		XPAR_FMC_HDMI_INPUT_V_TPG_1_ENABLE_MOTION
	},
	{
		XPAR_FMC_SENSOR_INPUT_V_TPG_1_DEVICE_ID,
		XPAR_FMC_SENSOR_INPUT_V_TPG_1_BASEADDR,
		XPAR_FMC_SENSOR_INPUT_V_TPG_1_S_AXIS_VIDEO_FORMAT,
		XPAR_FMC_SENSOR_INPUT_V_TPG_1_M_AXIS_VIDEO_FORMAT,
		XPAR_FMC_SENSOR_INPUT_V_TPG_1_S_AXI_CLK_FREQ_HZ,
		XPAR_FMC_SENSOR_INPUT_V_TPG_1_ACTIVE_ROWS,
		XPAR_FMC_SENSOR_INPUT_V_TPG_1_ACTIVE_COLS,
		XPAR_FMC_SENSOR_INPUT_V_TPG_1_PATTERN_CONTROL,
		XPAR_FMC_SENSOR_INPUT_V_TPG_1_MOTION_SPEED,
		XPAR_FMC_SENSOR_INPUT_V_TPG_1_CROSS_HAIRS,
		XPAR_FMC_SENSOR_INPUT_V_TPG_1_ZPLATE_HOR_CONTROL,
		XPAR_FMC_SENSOR_INPUT_V_TPG_1_ZPLATE_VER_CONTROL,
		XPAR_FMC_SENSOR_INPUT_V_TPG_1_BOX_SIZE,
		XPAR_FMC_SENSOR_INPUT_V_TPG_1_BOX_COLOR,
		XPAR_FMC_SENSOR_INPUT_V_TPG_1_STUCK_PIXEL_THRESH,
		XPAR_FMC_SENSOR_INPUT_V_TPG_1_NOISE_GAIN,
		XPAR_FMC_SENSOR_INPUT_V_TPG_1_BAYER_PHASE,
		XPAR_FMC_SENSOR_INPUT_V_TPG_1_HAS_INTC_IF,
		XPAR_FMC_SENSOR_INPUT_V_TPG_1_ENABLE_MOTION
	}
};


