xsrio.c
int XSrio_CfgInitialize(XSrio *InstancePtr, XSrio_Config *Config, UINTPTR EffectiveAddress)
Initialize the XSrio instance provided by the caller based on the given Config structure.
Initialization and Control functions in xsrio.c. InstancePtr is the XSrio instance to operate on. Config is the device configuration structure containing information about a specific SRIO Device. EffectiveAddress is the Physical address of the hardware in a Virtual Memory operating system environment.It is the Base Address in a stand alone environment. XST_SUCCESS Initialization was successful. None.
References XSrio_Config::BaseAddress, XSrio::Config, XSrio::IsReady, XSrio::PortWidth, XSRIO_PORT_N_CTL_CSR_OFFSET, XSRIO_PORT_N_CTL_CSR_PW_MASK, XSRIO_PORT_N_CTL_CSR_PW_SHIFT, XSrio_ReadReg.
Referenced by XSrioDmaLoopbackExample.
int XSrio_GetPortStatus(XSrio *InstancePtr)
XSrio_GetPortStatus will check the status of the port and returns the status of the port to the user.
InstancePtr is the XSrio instance to operate on. XSRIO_PORT_OK Port is initialized with no errors.XSRIO_PORT_UNINITIALIZED Port is not initialized. No Serial Rapidio link is present.XSRIO_PORT_HAS_ERRORS Port is initialized but has errors. : None.
References XSrio_Config::BaseAddress, XSrio::Config, XSRIO_PORT_HAS_ERRORS, XSRIO_PORT_N_ERR_STS_CSR_OFFSET, XSRIO_PORT_N_ERR_STS_CSR_PERR_MASK, XSRIO_PORT_N_ERR_STS_CSR_POK_MASK, XSRIO_PORT_N_ERR_STS_CSR_PUINT_MASK, XSRIO_PORT_OK, XSRIO_PORT_UNINITIALIZED, XSrio_ReadReg.
int XSrio_GetPEType(XSrio *InstancePtr)
XSrio_GetPEType API will check for the Processing Element type and return the type of type of Processing Element.
InstancePtr is the XSrio instance to operate on. XSRIO_IS_MEMORY if the core is configured as a memory XSRIO_IS_PROCESSOR if the core is configured as a processorXSRIO_IS_BRIDGE if the core is configured as a bridge. : None.
References XSrio_Config::BaseAddress, XSrio::Config, XSRIO_IS_BRIDGE, XSRIO_IS_MEMORY, XSRIO_IS_PROCESSOR, XSRIO_PEF_CAR_BRIDGE_MASK, XSRIO_PEF_CAR_MEMORY_MASK, XSRIO_PEF_CAR_OFFSET, XSRIO_PEF_CAR_PROCESSOR_MASK, XSrio_ReadReg.
Referenced by XSrioDmaLoopbackExample.
int XSrio_IsOperationSupported(XSrio *InstancePtr, u8 Operation, u8 Direction)
XSrio_IsOperationSupported tells whether the operation is supported by the SRIO Gen2 core or not.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Operation type is the operation type of the SRIO Packet Direction type XST_SUCCESS if the operation is supported by the core. XST_FAILURE if the operation is not supported by the core. None.
References XSRIO_DIR_TX, XSRIO_OP_MODE_ATOMIC, XSRIO_OP_MODE_DATA_MESSAGE, XSRIO_OP_MODE_DOORBELL, XSRIO_OP_MODE_NREAD, XSRIO_OP_MODE_NWRITE, XSRIO_OP_MODE_NWRITE_R, XSRIO_OP_MODE_SWRITE, XSrio_ReadDstOps, XSrio_ReadSrcOps, XSRIO_SRCDST_OPS_CAR_ATOMIC_SET_MASK, XSRIO_SRCDST_OPS_CAR_DATA_MSG_MASK, XSRIO_SRCDST_OPS_CAR_DOORBELL_MASK, XSRIO_SRCDST_OPS_CAR_READ_MASK, XSRIO_SRCDST_OPS_CAR_SWRITE_MASK, XSRIO_SRCDST_OPS_CAR_WRITE_MASK, XSRIO_SRCDST_OPS_CAR_WRITE_RESPONSE_MASK.
Referenced by XSrioDmaLoopbackExample.
void XSrio_SetWaterMark(XSrio *InstancePtr, u8 WaterMark0, u8 WaterMark1, u8 WaterMark2)
XSrio_SetWaterMark Configures the watermark to transfer a priority packet.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. WaterMark0 is the water mark value to transfer a priority 0 packet. WaterMark1 is the water mark value to transfer a priority 1 packet. WaterMark2 is the water mark value to transfer a priority 2 packet. None. None.
References XSrio_Config::BaseAddress, XSrio::Config, XSRIO_IMP_WCSR_OFFSET, XSRIO_IMP_WCSR_WM0_MASK, XSRIO_IMP_WCSR_WM1_MASK, XSRIO_IMP_WCSR_WM1_SHIFT, XSRIO_IMP_WCSR_WM2_MASK, XSRIO_IMP_WCSR_WM2_SHIFT, XSrio_ReadReg, XSrio_WriteReg.
Referenced by XSrioDmaLoopbackExample.
void XSrio_GetWaterMark(XSrio *InstancePtr, u8 *WaterMark0, u8 *WaterMark1, u8 *WaterMark2)
XSrio_GetWaterMark API reads the water mark values.
InstancePtr is the XSrio instance to operate on. WaterMark0 is a pointer to a variable where the driver will pass back the water mark 0 value. WaterMark1 is a pointer to a variable where the driver will pass back the water mark 1 value. WaterMark2 is a pointer to a variable where the driver will pass back the water mark 2 value. None. : None.
References XSrio_Config::BaseAddress, XSrio::Config, XSRIO_IMP_WCSR_OFFSET, XSRIO_IMP_WCSR_WM0_MASK, XSRIO_IMP_WCSR_WM1_MASK, XSRIO_IMP_WCSR_WM1_SHIFT, XSRIO_IMP_WCSR_WM2_MASK, XSRIO_IMP_WCSR_WM2_SHIFT, XSrio_ReadReg.