xsrio.h
XSRIO_H
XSRIO_IS_MEMORY
Core has physically addressable storage space.
Referenced by XSrio_GetPEType, XSrioDmaLoopbackExample.
XSRIO_IS_PROCESSOR
Core has a local processor that runs code.
Referenced by XSrio_GetPEType.
XSRIO_IS_BRIDGE
Core can be used as a bridge to another interface.
Referenced by XSrio_GetPEType.
XSRIO_OP_MODE_NREAD
Core supports read Operation.
Referenced by XSrio_IsOperationSupported.
XSRIO_OP_MODE_NWRITE
Core supports write Operation.
Referenced by XSrio_IsOperationSupported.
XSRIO_OP_MODE_SWRITE
Core supports streaming-write Operation.
Referenced by XSrio_IsOperationSupported, XSrioDmaLoopbackExample.
XSRIO_OP_MODE_NWRITE_R
Core supports write with Response operation.
Referenced by XSrio_IsOperationSupported.
XSRIO_OP_MODE_DATA_MESSAGE
Core supports data message Operation.
Referenced by XSrio_IsOperationSupported.
XSRIO_OP_MODE_DOORBELL
Core supports doorbell Operation.
Referenced by XSrio_IsOperationSupported.
XSRIO_OP_MODE_ATOMIC
Core supports atomic Operation.
Referenced by XSrio_IsOperationSupported.
XSRIO_PORT_OK
Port is initialized.
Referenced by XSrio_GetPortStatus.
XSRIO_PORT_UNINITIALIZED
Port is uninitialized.
Referenced by XSrio_GetPortStatus.
XSRIO_PORT_HAS_ERRORS
Port has errors.
Referenced by XSrio_GetPortStatus.
XSRIO_DIR_TX
Transmit Direction Flag.
Referenced by XSrio_IsOperationSupported, XSrioDmaLoopbackExample.
XSRIO_DIR_RX
Receive Direction Flag.
Referenced by XSrioDmaLoopbackExample.
XSrio_ReadDeviceVendorID
XSrio_ReadDeviceVendorID returns the Device Vendor Id of the core.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Device Vendor ID of the core. C-style signature: u16 XSrio_ReadDeviceVendorID(XSrio *InstancePtr)
XSrio_ReadDeviceID
XSrio_ReadDeviceID returns the Device Id of the core.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Device ID of the core. C-style signature: u16 XSrio_ReadDeviceID(XSrio *InstancePtr)
XSrio_ReadAsmVendorID
XSrio_ReadAsmVendorID returns the Assembly Vendor Id of the core.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Assembly Vendor ID of the core. C-style signature: u16 XSrio_ReadAsmVendorID(XSrio *InstancePtr)
XSrio_ReadAsmID
XSrio_ReadAsmID returns the Assembly Id of the SRIO Gen2 core.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Assembly ID of the core. C-style signature: u16 XSrio_ReadAsmID(XSrio *InstancePtr)
XSrio_GetExFeaturesPointer
XSrio_GetExFeaturesPointer gives the pointer to the Phy Register space of the SRIO Gen2 core.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Pointer to the Phy Register space of the core. C-style signature: u16 XSrio_GetExFeaturesPointer(XSrio *InstancePtr)
XSrio_ReadAsmRevision
XSrio_ReadAsmRevision returns the Assembly Revision value of the core.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Assembly revision of the core. C-style signature: u16 XSrio_ReadAsmRevision(XSrio *InstancePtr)
XSrio_IsLargeSystem
XSrio_IsLargeSystem checks whether PE(Processing Element) supports a large system (16-bit Device ids)
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. TRUE If the System Supports 16-bit Devices.FALSE If the System Supports 8-bit Devices. C-style signature: u8 XSrio_IsLargeSystem(XSrio *InstancePtr)
XSrio_IsCRFSupported
XSrio_IsCRFSupported checks whether the PE(Processing Element) supports CRF(Critical Request Flow indicator).
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. TRUE If the System Supports CRF.FALSE If the System Won't Support CRF. C-style signature: u8 XSrio_IsCRFSupported(XSrio *InstancePtr)
XSrio_ReadSrcOps
XSrio_ReadSrcOps returns the Source Operations CAR Register contents.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Contents of the Source Operations CAR Register. C-style signature: u32 XSrio_ReadSrcOps(XSrio *InstancePtr)
Referenced by XSrio_IsOperationSupported.
XSrio_ReadDstOps
XSrio_ReadDstOps returns the Destination Operations CAR Register contents.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Contents of the Destination Operations CAR Register. C-style signature: u32 XSrio_ReadDstOps(XSrio *InstancePtr)
Referenced by XSrio_IsOperationSupported.
XSrio_GetLCSBA
XSrio_GetLCSBA returns the Local Configuration Space Base Address(LCSBA) of the SRIO Gen2 core.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Contents of Local Configuration Space Base Address Register. C-style signature: u32 XSrio_GetLCSBA(XSrio *InstancePtr)
XSrio_SetLCSBA
XSrio_SetLCSBA Configures the Local Configuration Space Base Address of the SRIO Gen2 core.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Value is the Local Configuration Space Base Address that needs to be configured. None. C-style signature: void XSrio_SetLCSBA(XSrio *InstancePtr, u32 Value)
Referenced by XSrioDmaLoopbackExample.
XSrio_GetLargeBaseDeviceID
XSrio_GetLargeBaseDeviceID returns the 16-bit Device Id for an endpoint in a Large transport system.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. 16-bit Device Id. C-style signature: u16 XSrio_GetLargeBaseDeviceID(XSrio *InstancePtr)
XSrio_SetLargeBaseDeviceID
XSrio_SetLargeBaseDeviceID configures the 16-bit Device Id for an endpoint in a Large transport system.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. DeviceId is the Device ID that needs to be configured. None. C-style signature: void XSrio_SetLargeBaseDeviceID(XSrio *InstancePtr, u16 DeviceId)
XSrio_GetBaseDeviceID
XSrio_GetBaseDeviceID returns the 8-bit Device Id for an endpoint in a small Transport system.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. 8-bit Device Id. C-style signature: u8 XSrio_GetBaseDeviceID(XSrio *InstancePtr)
XSrio_SetBaseDeviceID
XSrio_SetBaseDeviceID configures the 8-bit Device Id for an endpoint in a small transport system.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. DeviceId is the Device ID that needs to be configured. None. C-style signature: void XSrio_SetBaseDeviceID(XSrio *InstancePtr, u8 DeviceId)
XSrio_GetHostBaseDevID_LockCSR
XSrio_GetHostBaseDevID_LockCSR returns the Device Id of the system host.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Device Id of the system host. C-style signature: u16 XSrio_GetHostBaseDevID_LockCSR(XSrio *InstancePtr)
XSrio_SetHostBaseDevID_LockCSR
XSrio_SetHostBaseDevID_LockCSR configures the Host Base Device Id of the SRIO gen2 Core.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. DeviceId is the Device ID that needs to be configured. None. C-style signature: void XSrio_SetHostBaseDevID_LockCSR(XSrio *InstancePtr, u16 DeviceId)
XSrio_GetComponentTagCSR
XSrio_GetComponentTagCSR returns the Component Tag Value set by the software during initialization.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Component Tag Value. C-style signature: u32 XSrio_GetComponentTagCSR(XSrio *InstancePtr)
XSrio_SetComponentTagCSR
XSrio_SetComponentTagCSR sets the Component Tag Value for SRIO Gen2 core.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Value is the Component Tag Value to be set. None. C-style signature: void XSrio_SetComponentTagCSR(XSrio *InstancePtr, u32 Value)
XSrio_GetExtFeaturesID
XSrio_GetExtFeaturesID returns the Extended Features Id value.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Extended Features ID Value. C-style signature: u16 XSrio_GetExtFeaturesID(XSrio *InstancePtr)
XSrio_GetSerialExtFeaturesPointer
XSrio_GetSerialExtFeaturesPointer returns the Extended Features Pointer which will point to the next extended features block if one exists.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Extended Features Pointer Address. C-style signature: u16 XSrio_GetSerialExtFeaturesPointer(XSrio *InstancePtr)
XSrio_GetPortLinkTimeOutValue
XSrio_GetPortLinkTimeOutValue returns the Port Link Timeout value for the SRIO Gen2 core.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Port link Timeout Value. C-style signature: u32 XSrio_GetPortLinkTimeOutValue(XSrio *InstancePtr)
XSrio_SetPortLinkTimeOutValue
XSrio_SetPortLinkTimeOutValue sets the Port Link Timeout value for the SRIO Gen2 core.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Value is the Port Link Timeout value to be set. None. C-style signature: void XSrio_SetPortLinkTimeOutValue(XSrio *InstancePtr, u16 Value)
XSrio_GetPortRespTimeOutValue
XSrio_GetPortRespTimeOutValue returns the Port Response Timeout value for the the SRIO Gen2 core.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Port Response Timeout value. C-style signature: u32 XSrio_GetPortRespTimeOutValue(XSrio *InstancePtr)
XSrio_SetPortRespTimeOutValue
XSrio_SetPortRespTimeOutValue sets the Port Response Timeout value for the The SRIO Gen2 core.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Value is the Port Response Timeout to be set. None. C-style signature: void XSrio_SetPortRespTimeOutValue(XSrio *InstancePtr, u16 Value)
Referenced by XSrioDmaLoopbackExample.
XSrio_IsPEDiscovered
XSrio_IsPEDiscovered checks whether the PE(Processing Element) is discovered or not.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. TRUE If the PE is Discovered.FALSE If the PE is not Discovered. C-style signature: u8 XSrio_IsPEDiscovered(XSrio *InstancePtr)
XSrio_SetDiscovered
XSrio_SetDiscovered configures the device as Discovered so that it is responsible for system exploration.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. None. C-style signature: void XSrio_SetDiscovered(XSrio *InstancePtr)
XSrio_IsMasterEnabled
XSrio_IsMasterEnabled checks whether PE(Processing Element) is allowed to issue request into the system.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. TRUE If the Master Enable bit is set.FALSE If the Master Enable bit is not set. C-style signature: u8 XSrio_IsMasterEnabled(XSrio *InstancePtr)
XSrio_SetMasterEnabled
XSrio_SetMasterEnabled configures the device so that it is allowed to issue requests into the system.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. None. C-style signature: void XSrio_SetMasterEnabled(XSrio *InstancePtr)
XSrio_IsHost
XSrio_IsHost checks whether PE(Processing Element) is responsible for system exploration.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. TRUE If the Host bit is set.FALSE If the Host bit is not set. C-style signature: u8 XSrio_IsHost(XSrio *InstancePtr)
XSrio_SetHostEnabled
XSrio_SetHostEnabled configures the device to be responsible for system exploration.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. None. C-style signature: void XSrio_SetHostEnabled(XSrio *InstancePtr)
XSrio_GetCommand
XSrio_GetCommand returns the command value that is sent on the Link-request Control symbol of the SRIO Gen2 core.
This api is available only if the software assisted error recovery option is enabled in the core. InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Command information of the link-request control symbol. C-style signature: u32 XSrio_GetCommand(XSrio *InstancePtr)
XSrio_SendCommand
XSrio_SendCommand sends the given command in the link-request control symbol of the SRIO Gen2 core.
This api is available only if the software assisted error recovery option is selected in the core. InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Value is the Command to be send. None. C-style signature: void XSrio_SendCommand(XSrio *InstancePtr, u8 Value)
XSrio_IsResponseValid
XSrio_IsResponseValid checks whether the link response is valid or not in the SRIO Gen2 Core.
This api is available only if the software assisted error recovery option is enabled in the core. InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. TRUE if the corresponding link request causes a link response.FALSE if the corresponding link request not causes a link response. C-style signature: u8 XSrio_IsResponseValid(XSrio *InstancePtr)
XSrio_GetOutboundAckID
XSrio_GetOutboundAckID returns the value of the next transmitted Ackid of the SRIO Gen2 Core.
This api is available only if the software assisted error recovery option is selected core. InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Outbound Ack ID value. C-style signature: u32 XSrio_GetOutboundAckID(XSrio *InstancePtr)
XSrio_SetOutboundAckID
XSrio_SetOutboundAckID sets value of the next transmitted Ackid of the SRIO Gen2 Core.
This api is available only if the software assisted error Recovery option is selected in the core. InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Value is the Outbound Ack Id to be set. None. C-style signature: void XSrio_SetOutboundAckID(XSrio *InstancePtr, u8 Value)
XSrio_GetInboundAckID
XSrio_GetInboundAckID returns the expected Ackid of the next received packet of the SRIO Gen2 core.
This api is available only if the software assisted error recovery option is selected in the core. InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Inbound Ack ID value. C-style signature: u32 XSrio_GetInboundAckID(XSrio *InstancePtr)
XSrio_SetInboundAckID
XSrio_SetInboundAckID sets the value of the next transmitted Ackid of the SRIO Gen2 core.
This api is available only if the software assisted error recovery option is selected in the core. InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Value is the InBound Ack Id to be set. None. C-style signature: void XSrio_SetInboundAckID(XSrio *InstancePtr, u8 Value) This api won't work if you call the XSrio_ClrOutStandingAckIDs before calling this api.
XSrio_ClrOutStandingAckIDs
XSrio_ClrOutStandingAckIDs clears all outstanding unacknowledged received packets of the SRIO Gen2 core.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. None. C-style signature: void XSrio_ClrOutStandingAckIDs(XSrio *InstancePtr)
XSrio_IsEnumerationBoundary
XSrio_IsEnumerationBoundary checks whether the enumeration boundary is available or not for the SRIO Gen2 core.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. TRUE if the EnumerationBoundary Enabled.FALSE if the EnumerationBoundary is not Enabled. C-style signature: u8 XSrio_IsEnumerationBoundary(XSrio *InstancePtr)
XSrio_ClrEnumerationBoundary
XSrio_ClrEnumerationBoundary clears the enumeration boundary of the SRIO Gen2 core.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. None. C-style signature: void XSrio_ClrEnumerationBoundary(XSrio *InstancePtr)
XSrio_GetPortwidthOverride
XSrio_GetPortwidthOverride returns the port width override value of the SRIO Gen2 core.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Port Width Override Value. C-style signature: u8 XSrio_GetPortwidthOverride(XSrio *InstancePtr)
XSrio_SetPortwidthOverride
XSrio_SetPortwidthOverride configures the port width override value of the SRIO Gen2 core.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Value is the port width override value needs to be set. None. C-style signature: void XSrio_SetPortwidthOverride(XSrio *InstancePtr, u8 Value)
XSrio_GetSerialLaneExtFeaturesPointer
XSrio_GetSerialLaneExtFeaturesPointer returns the extended features pointer For the serial lane which will point to the next extended features block If one exists.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Extended Features Pointer Address. C-style signature: u16 XSrio_GetSerialLaneExtFeaturesPointer(XSrio *InstancePtr)
XSrio_ClrDecodingErrors
XSrio_ClrDecodingErrors clears the 8B/10B decoding errors and return Result.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Lanenum is the Serial Lane-number(0,1,2,3). None C-style signature: int XSrio_ClrDecodingErrors(XSrio *InstancePtr, u8 Lanenum)
XSrio_GetRxSize
XSrio_GetRxSize returns the number of maximum-size packets the rx buffer holded.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Rx buffer size. C-style signature: u8 XSrio_GetRxSize(XSrio *InstancePtr)
XSrio_ForceRxFlowControl
XSrio_ForceRxFlowControl forces the Tx flow control enabled core to use Rx flow control.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. None. C-style signature: void XSrio_ForceRxFlowControl(XSrio *InstancePtr)
XSrio_GetTxSize
XSrio_GetTxSize returns the number of maximum-size packets the tx buffer holds.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Tx buffer size. C-style signature: u8 XSrio_GetTxSize(XSrio *InstancePtr)
XSrio_CheckforTxReqreorder
XSrio_CheckforTxReqreorder checks whether the transmit buffer has been configured to allow reordering of requests.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. TRUE If the Tx Request reorder is enabled in the core. FALSE If the Tx Request reorder is not enabled in the core. C-style signature: u8 XSrio_CheckforTxReqreorder(XSrio *InstancePtr)
XSrio_IsTxFlowControl
XSrio_IsTxFlowControl checks whether the BUF is currently operating in Tx flow control mode or not.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. TRUE If the Tx Flow Control is enabled in the core.FALSE If the Tx Flow Control is not enabled in the core. C-style signature: u8 XSrio_IsTxFlowControl(XSrio *InstancePtr)
XSrio_GetDestinationID
XSrio_GetDestinationID gets the destination id value which will be used for outgoing maintenance requests.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Destination ID value of the outgoing maintenance request. C-style signature: u8 XSrio_GetDestinationID(XSrio *InstancePtr)
XSrio_SetDestinationID
XSrio_SetDestinationID sets Device Id which will be used for Outgoing maintenance requests.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Value is the Device Id value. None. C-style signature: void XSrio_SetDestinationID(XSrio *InstancePtr, u8 Value)
XSrio_GetCRF
XSrio_GetCRF checks whether the CRF is enabled in the core or not which will be used for outgoing maintenance requests.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. CRF Value used for outgoing maintenance requests. C-style signature: u8 XSrio_GetCRF(XSrio *InstancePtr)
XSrio_SetCRF
XSrio_SetCRF sets CRF value that is used for outgoing maintenance requests.
This api will work only when the CRF support is enabled in the core InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. None. C-style signature: void XSrio_SetCRF(XSrio *InstancePtr)
XSrio_GetPriority
XSrio_GetPriority priority used for outgoing maintenance requests.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Priority value. C-style signature: u8 XSrio_GetPriority(XSrio *InstancePtr)
XSrio_SetPriority
XSrio_SetPriority sets the Priority which will be used for outgoing maintenance requests.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Value is the Priority value which will used for outgoing maintenance requests. None. C-style signature: void XSrio_SetPriority(XSrio *InstancePtr, u8 Value)
XSrio_RequestTID
XSrio_RequestTID gives the transfer id value which will be used for the next outgoing maintenance request.
This value will increment after each request is sent. InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Transfer ID value. C-style signature: u8 XSrio_RequestTID(XSrio *InstancePtr)
XSrio_SetTID
XSrio_SetTID sets the transfer id which will be used for the next outgoing maintenance request.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Value is the transfer id value which of the next outgoing maintenance request. None. C-style signature: void XSrio_SetTID(XSrio *InstancePtr, u8 Value)
XSrio_ClrPortError
XSrio_ClrPortError clears the Port Error specified by the Mask.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Mask is the mask for the Port Error to be cleared. None. C-style signature: void XSrio_ClrPortError(XSrio *InstancePtrm, u32 Mask)
XSrio_GetPortErrorStatus
XSrio_GetPortErrorStatus returns the mask for the port errors currently enabled in the SRIO Gen2 core.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. The bit mask for the port errors that are currently enabled. C-style signature: u32 XSrio_GetPortErrorStatus(XSrio *InstancePtr)
XSrio_SetPortControlStatus
XSrio_SetPortControlStatus Configures specific port specified by the Mask.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Mask is the mask for the port that needs to be enabled. None. C-style signature: void XSrio_SetPortControlStatus(XSrio *InstancePtrm, u32 Mask)
XSrio_GetPortControlStatus
XSrio_GetPortControlStatus returns the status of the port that is currently enabled in the SRIO Gen2 core.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. The bit mask for the ports that are currently enabled. C-style signature: u32 XSrio_GetPortControlStatus(XSrio *InstancePtr)
typedef struct XSrio_Config XSrio_Config
This typedef contains the configuration information for the device.
typedef struct XSrio XSrio
The XSrio driver instance data.
An instance must be allocated for each SRIO device in use.
int XSrio_CfgInitialize(XSrio *InstancePtr, XSrio_Config *Config, UINTPTR EffectiveAddress)
Initialize the XSrio instance provided by the caller based on the given Config structure.
Initialization and Control functions in xsrio.c. InstancePtr is the XSrio instance to operate on. Config is the device configuration structure containing information about a specific SRIO Device. EffectiveAddress is the Physical address of the hardware in a Virtual Memory operating system environment.It is the Base Address in a stand alone environment. XST_SUCCESS Initialization was successful. None.
References XSrio_Config::BaseAddress, XSrio::Config, XSrio::IsReady, XSrio::PortWidth, XSRIO_PORT_N_CTL_CSR_OFFSET, XSRIO_PORT_N_CTL_CSR_PW_MASK, XSRIO_PORT_N_CTL_CSR_PW_SHIFT, XSrio_ReadReg.
Referenced by XSrioDmaLoopbackExample.
XSrio_Config * XSrio_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID.
The table XSrio_ConfigTable contains the configuration info for each device in the system. DeviceId is the unique device ID of the device to lookup for The configuration structure for the device. If the device ID is not found,a NULL pointer is returned. None
References XSrio_Config::Name.
Referenced by XSrioDmaLoopbackExample.
int XSrio_GetPortStatus(XSrio *InstancePtr)
XSrio_GetPortStatus will check the status of the port and returns the status of the port to the user.
InstancePtr is the XSrio instance to operate on. XSRIO_PORT_OK Port is initialized with no errors.XSRIO_PORT_UNINITIALIZED Port is not initialized. No Serial Rapidio link is present.XSRIO_PORT_HAS_ERRORS Port is initialized but has errors. : None.
References XSrio_Config::BaseAddress, XSrio::Config, XSRIO_PORT_HAS_ERRORS, XSRIO_PORT_N_ERR_STS_CSR_OFFSET, XSRIO_PORT_N_ERR_STS_CSR_PERR_MASK, XSRIO_PORT_N_ERR_STS_CSR_POK_MASK, XSRIO_PORT_N_ERR_STS_CSR_PUINT_MASK, XSRIO_PORT_OK, XSRIO_PORT_UNINITIALIZED, XSrio_ReadReg.
int XSrio_GetPEType(XSrio *InstancePtr)
XSrio_GetPEType API will check for the Processing Element type and return the type of type of Processing Element.
InstancePtr is the XSrio instance to operate on. XSRIO_IS_MEMORY if the core is configured as a memory XSRIO_IS_PROCESSOR if the core is configured as a processorXSRIO_IS_BRIDGE if the core is configured as a bridge. : None.
References XSrio_Config::BaseAddress, XSrio::Config, XSRIO_IS_BRIDGE, XSRIO_IS_MEMORY, XSRIO_IS_PROCESSOR, XSRIO_PEF_CAR_BRIDGE_MASK, XSRIO_PEF_CAR_MEMORY_MASK, XSRIO_PEF_CAR_OFFSET, XSRIO_PEF_CAR_PROCESSOR_MASK, XSrio_ReadReg.
Referenced by XSrioDmaLoopbackExample.
int XSrio_IsOperationSupported(XSrio *InstancePtr, u8 Operation, u8 Direction)
XSrio_IsOperationSupported tells whether the operation is supported by the SRIO Gen2 core or not.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. Operation type is the operation type of the SRIO Packet Direction type XST_SUCCESS if the operation is supported by the core. XST_FAILURE if the operation is not supported by the core. None.
References XSRIO_DIR_TX, XSRIO_OP_MODE_ATOMIC, XSRIO_OP_MODE_DATA_MESSAGE, XSRIO_OP_MODE_DOORBELL, XSRIO_OP_MODE_NREAD, XSRIO_OP_MODE_NWRITE, XSRIO_OP_MODE_NWRITE_R, XSRIO_OP_MODE_SWRITE, XSrio_ReadDstOps, XSrio_ReadSrcOps, XSRIO_SRCDST_OPS_CAR_ATOMIC_SET_MASK, XSRIO_SRCDST_OPS_CAR_DATA_MSG_MASK, XSRIO_SRCDST_OPS_CAR_DOORBELL_MASK, XSRIO_SRCDST_OPS_CAR_READ_MASK, XSRIO_SRCDST_OPS_CAR_SWRITE_MASK, XSRIO_SRCDST_OPS_CAR_WRITE_MASK, XSRIO_SRCDST_OPS_CAR_WRITE_RESPONSE_MASK.
Referenced by XSrioDmaLoopbackExample.
void XSrio_SetWaterMark(XSrio *InstancePtr, u8 WaterMark0, u8 WaterMark1, u8 WaterMark2)
XSrio_SetWaterMark Configures the watermark to transfer a priority packet.
InstancePtr is a pointer to the SRIO Gen2 instance to be worked on. WaterMark0 is the water mark value to transfer a priority 0 packet. WaterMark1 is the water mark value to transfer a priority 1 packet. WaterMark2 is the water mark value to transfer a priority 2 packet. None. None.
References XSrio_Config::BaseAddress, XSrio::Config, XSRIO_IMP_WCSR_OFFSET, XSRIO_IMP_WCSR_WM0_MASK, XSRIO_IMP_WCSR_WM1_MASK, XSRIO_IMP_WCSR_WM1_SHIFT, XSRIO_IMP_WCSR_WM2_MASK, XSRIO_IMP_WCSR_WM2_SHIFT, XSrio_ReadReg, XSrio_WriteReg.
Referenced by XSrioDmaLoopbackExample.
void XSrio_GetWaterMark(XSrio *InstancePtr, u8 *WaterMark0, u8 *WaterMark1, u8 *WaterMark2)
XSrio_GetWaterMark API reads the water mark values.
InstancePtr is the XSrio instance to operate on. WaterMark0 is a pointer to a variable where the driver will pass back the water mark 0 value. WaterMark1 is a pointer to a variable where the driver will pass back the water mark 1 value. WaterMark2 is a pointer to a variable where the driver will pass back the water mark 2 value. None. : None.
References XSrio_Config::BaseAddress, XSrio::Config, XSRIO_IMP_WCSR_OFFSET, XSRIO_IMP_WCSR_WM0_MASK, XSRIO_IMP_WCSR_WM1_MASK, XSRIO_IMP_WCSR_WM1_SHIFT, XSRIO_IMP_WCSR_WM2_MASK, XSRIO_IMP_WCSR_WM2_SHIFT, XSrio_ReadReg.