dsitxss
XDSITXSS_HANDLER_UNSUPPORT_DATATYPE
Unsupported data type handler ID.
Referenced by DsiTxSs_IntrExample.
XDSITXSS_HANDLER_PIXELDATA_UNDERRUN
Pixel data underrun handler ID.
Referenced by DsiTxSs_IntrExample.
XDSITXSS_HANDLER_CMDQ_FIFOFULL
Command queue FIFO full handler ID.
Referenced by DsiTxSs_IntrExample.
XDSITXSS_HANDLER_OTHERERROR
Other error handler ID.
XDSITXSS_ISR_DATAIDERR_MASK
Data ID error interrupt status mask.
Referenced by DsiTxSs_UnSupportDataEventHandler.
XDSITXSS_ISR_PIXELUNDERRUN_MASK
Pixel underrun interrupt status mask.
Referenced by DsiTxSs_PixelUnderrunEventHandler.
XDSITXSS_ISR_CMDQ_FIFO_FULL_MASK
Command queue FIFO full interrupt status mask.
Referenced by DsiTxSs_CmdQFIFOFullEventHandler.
XDSITXSS_IER_DATAIDERR_MASK
Data ID error interrupt enable mask.
XDSITXSS_IER_PIXELUNDERRUN_MASK
Pixel underrun interrupt enable mask.
XDSITXSS_IER_CMDQ_FIFO_FULL_MASK
Command queue FIFO full interrupt enable mask.
XDSITXSS_IER_ALLINTR_MASK
Enable all supported interrupts mask.
Referenced by DsiTxSs_IntrExample.
XDsiSS_Selection
Disable DSI TX subsystem.
XDsiSS_Subcore
DSI Core.
typedef void(* XDsiTxSs_Callback)(void *CallbackRef, u32 Mask))(void *CallbackRef, u32 Mask)
Callback type for all interrupts defined.
CallbackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. Mask is a bit mask indicating the cause of the event. For current core version, this parameter is "OR" of 0 or more XDSITXSS_ISR_*_MASK constants defined in xdsitxss_hw.h. None. None.
XDsi XDsiTxSs_SubCores::DsiInst
DSI controller driver instance.
XDsiTxSs_SubCores DsiTxSsSubCores[XPAR_XDSITXSS_NUM_INSTANCES][XPAR_XDSITXSS_NUM_INSTANCES]
Global array of DSI TX Subsystem sub-core instances.
Each array element contains the driver instances for all sub-cores (DSI, MIPI TX PHY, DPHY) associated with an instance of the DSI TX Subsystem.
XDsiTxSs_Config XDsiTxSs_ConfigTable[][]
Configuration table containing hardware configuration information for each XDsiTxSs instance in the system.
This table is populated by the platform configuration tool and is referenced by XDsiTxSs_LookupConfig during device initialization.
static void XDsiTxSs_GetIncludedSubCores(XDsiTxSs *DsiTxSsPtr)
This function queries the subsystem instance configuration to determine the included sub-cores.
For each sub-core that is present in the design the sub-core driver instance is binded with the subsystem sub-core driver handle DsiTxSsPtr is a pointer to the Subsystem instance None None
static s32 XDsiTxSs_SubCoreInitDsi(XDsiTxSs *DsiTxSsPtr)
This function initializes the DSI sub-core initialization.
DsiTxSsPtr is a pointer to the Subsystem instance XST_SUCCESS on DSI sub core initializationXST_FAILURE on DSI fail initialization None
s32 XDsiTxSs_CfgInitialize(XDsiTxSs *InstancePtr, XDsiTxSs_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the MIPI DSI TX subsystem and included sub-cores.
This function must be called prior to using the subsystem. Initialization includes setting up the instance data for top level as well as all included sub-core therein, and ensuring the hardware is in a known stable state InstancePtr is a pointer to the Subsystem instance to be worked on. CfgPtr points to the configuration structure associated with the subsystem instance. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if initialization is successfulXST_FAILURE if initialization is failure None.
References XDsiTxSs_Config::BaseAddr, XDsiTxSs::Config, XDsiTxSs::DsiPtr, XDsiTxSs::IsReady.
Referenced by DsiTxSs_IntrExample, DsiTxSs_SelfTestExample, DsiTxSs_VideoTestExample.
u32 XDsiTxSs_DefaultConfigure(XDsiTxSs *InstancePtr)
This function is used to configure the DSI default parameters that are to be handled by the application.
It will configure protocol register with video mode, bllp mode,eotp InstancePtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS on successful configuration of parametersXST_FAILURE on failure scenraio None.
References XDsiTxSs::DsiPtr.
int XDsiTxSs_Activate(XDsiTxSs *InstancePtr, XDsiSS_Subcore core, u8 Flag)
This function is used to activate the DSI Subsystem.
Internally it activates the DPHY and DSI. Enable/Disable IP core to start processing InstancePtr is a pointer to the Subsystem instance to be worked on. core is used to denote the subcore of subsystem Flag is used to denote whether to enable or disable the subsystem XST_SUCCESS is returned if subcore(DSI/DPHY) was successfully enabled or disabled XST_INVALID_PARAM is returned if subsystem core is not found None.
References XDsiTxSs::Config, XDsiTxSs::DsiPtr, XDSITXSS_DSI, XDSITXSS_ENABLE, XDSITXSS_PHY.
Referenced by DsiTxSs_VideoTestExample.
void XDsiTxSs_Reset(XDsiTxSs *InstancePtr)
This function is used to reset the DSI Subsystem.
Internally it resets the DPHY and DSI InstancePtr is a pointer to the Subsystem instance to be worked on. None.
References XDsiTxSs::Config, XDsiTxSs::DsiPtr, XDsiTxSs_Config::IsDphyRegIntfcPresent.
Referenced by DsiTxSs_VideoTestExample.
void XDsiTxSs_ReportCoreInfo(XDsiTxSs *InstancePtr)
This function reports list of cores included in DSI TX Subsystem.
InstancePtr is a pointer to the DSI TX Subsystem instance. None.
References XDsiTxSs::Config, XDsiTxSs_Config::DphyInfo, XDsiTxSs::DsiPtr, DsiTxSsSubCore::IsPresent.
int XDsiTxSs_SetDSIMode(XDsiTxSs *InstancePtr, XDsi_DsiModeType mode)
This function sets the mode to send short packet. InstancePtr is the XDsiTxSs instance to operate on mode is the DSI mode (video or command) to operate on None None.
References XDsiTxSs::DsiPtr.
int XDsiTxSs_SendCmdModePacket(XDsiTxSs *InstancePtr)
This function will send the short packet to controller in command modeGeneric Short Packet Register and fill up the structure passed from caller. InstancePtr is the XDsiTxSs instance to operate on XST_SUCCESS on successful packet transmissionXST_FAILURE on failure in packet transmission None.
References XDsiTxSs::CmdPkt, XDsiTxSs::DsiPtr.
void XDsiTxSs_SendShortPacket(XDsiTxSs *InstancePtr)
This function will send the short packet to controller Generic Short Packet Register and fill up the structure passed from caller.
like to turn on/off peripheral, change color mode InstancePtr is the XDsiTxSs instance to operate on None.
References XDsiTxSs::DsiPtr, XDsiTxSs::SpktData.
void XDsiTxSs_GetConfigParams(XDsiTxSs *InstancePtr)
This function will get the information from the GUI settings.
InstancePtr is the XDsi instance to operate on None.
References XDsiTxSs::ConfigInfo, XDsiTxSs::DsiPtr.
u32 XDsiTxSs_IsControllerReady(XDsiTxSs *InstancePtr)
This function will get the information from the GUI settings.
InstancePtr is the XDsiTxss instance to operate on Controller ready status None.
References XDsiTxSs::DsiPtr.
u32 XDsiTxSs_GetPixelFormat(XDsiTxSs *InstancePtr)
This function is used to get pixel format.
InstancePtr is a pointer to the DsiTxSs Instance to be worked on. 0x0E – Packed RGB565 0x1E- packed RGB666 0x2E – Loosely packed RGB666 0x3E- Packed RGB888 0x0B- Compressed Pixel Stream None
References XDsiTxSs::DsiPtr.
u32 XDsiTxSs_GetCmdQVacancy(XDsiTxSs *InstancePtr)
This function is used to get Command queue Vacancy.
InstancePtr is a pointer to the DSITxSs Instance to be worked on. Number of command queue entries can be safely written to Command queue FIFO, before it goes full. None
References XDsiTxSs::DsiPtr.
s32 XDsiTxSs_SetVideoInterfaceTiming(XDsiTxSs *InstancePtr, XDsi_VideoMode VideoMode, XVidC_VideoMode Resolution, u16 BurstPacketSize)
This function Set Timing mode and Resolution.
As per user resolution selection it will get populate Periperal Timing Parameters from video common Library InstancePtr is the XDsi instance to operate on VideoMode Specifies mode of Interfacing Resolution sets the resolution BurstPacketSize sets the packet size XST_SUCCESS is return Video interfacing set was successfulXST_INVALID_PARAM indicates an invalid parameter was specified. None.
References XDsiTxSs::DsiPtr.
s32 XDsiTxSs_SetCustomVideoInterfaceTiming(XDsiTxSs *InstancePtr, XDsi_VideoMode VideoMode, XDsi_VideoTiming *Timing)
This function Set Timning mode and Resolution as per user inputs.
InstancePtr is the XDsi instance to operate on VideoMode Specifies mode of Interfacing Timing Video Timing parameters XST_SUCCESS is return Video interfacing was successfully setXST_INVALID_PARAM indicates an invalid parameter was specified. None
References XDsiTxSs::DsiPtr.
Referenced by DsiTxSs_VideoTestExample.
XDsiTxSs_Config * XDsiTxSs_LookupConfig(UINTPTR BaseAddress)
This function looks for the device configuration based on the unique device ID.
The table XDsiTxSs_ConfigTable[] contains the configuration information for each instance of the device in the system. DeviceId is the unique device ID of the device being looked up A pointer to the configuration table entry corresponding to the given device ID, or NULL if no match is found None.
Referenced by DsiTxSs_IntrExample, DsiTxSs_SelfTestExample, DsiTxSs_VideoTestExample.
u32 XDsiTxSs_GetDrvIndex(XDsiTxSs *InstancePtr, UINTPTR BaseAddress)
This function returns the Index number of config table using BaseAddress.
InstancePtr pointer to the instance structure BaseAddress address of the instance Index number of the config table
u32 XDsiTxSs_SelfTest(XDsiTxSs *InstancePtr)
This function performs self test on MIPI DSI Tx Subsystem sub-cores.
InstancePtr is a pointer to the XDsiTxSs core instance. XST_SUCCESS if self test passed.XST_FAILURE if self test failed. None.
References XDsiTxSs::Config, XDsiTxSs_Config::DphyInfo, XDsiTxSs::DsiPtr, DsiTxSsSubCore::IsPresent.
Referenced by DsiTxSs_IntrExample, DsiTxSs_SelfTestExample, DsiTxSs_VideoTestExample.
u32 XDsiTxSs_SetCallback(XDsiTxSs *InstancePtr, u32 HandlerType, void *CallbackFunc, void *CallbackRef)
This routine installs an asynchronous callback function for the given HandlerType:
HandlerType Invoked by this driver when: ----------------------- -------------------------------------------------- XDSI_HANDLER_UNSUPPORT_DATATYPE Un support data type detected XDSI_HANDLER_PIXELDATA_UNDERRUN Byte Stream FIFO starves for Pixel during HACT transmission XDSI_HANDLER_OTHERERROR Any other type of interrupt has occurred like Stream Line Buffer Full, Incorrect Lanes, etc XDSI_HANDLER_CMDQ_FIFOFULL Command queue FIFO Full InstancePtr is the XDsi instance to operate on HandlerType is the type of call back to be registered. CallbackFunc is the pointer to a call back function which is called when a particular event occurs. CallbackRef is a void pointer to data to be referenced to by the CallbackFunc XST_SUCCESS when handler is installed. XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XDsiTxSs::DsiPtr, XDsiTxSs::IsReady.
Referenced by DsiTxSs_IntrExample.
void XDsiTxSs_IntrHandler(void *InstancePtr)
This function is the interrupt handler for the MIPI DSI Tx Subsystem.
The application is responsible for connecting this function to the interrupt system. Application beyond this driver is also responsible for providing callbacks to handle interrupts and installing the callbacks using XDsiTxSs_SetCallback() during initialization phase. InstancePtr is a pointer to the XDsiTxSs core instance that just interrupted. None.
References XDsiTxSs::DsiPtr.
static u32 XDsiTxSs_ReadReg(UINTPTR BaseAddress, u32 RegOffset)
This function reads a value from a MIPI DSI Tx Subsystem register.
A 32 bit read is performed. If the component is implemented in a smaller width, only the least significant data is read from the register. The most significant data will be read as 0. BaseAddress is the base address of the XDsiTxSs core instance. RegOffset is the register offset of the register (defined at the top of this file). The 32-bit value of the register. None
static void XDsiTxSs_WriteReg(UINTPTR BaseAddress, u32 RegOffset, u32 Data)
This function writes a value to a MIPI DSI Tx Subsystem register.
A 32 bit write is performed. If the component is implemented in a smaller width, only the least significant data is written. BaseAddress is the base address of the XDsiTxSs core instance. RegOffset is the register offset of the register (defined at the top of this file) to be written. Data is the 32-bit value to write into the register. None. None
void XDsi_IntrHandler(void *InstancePtr)
void XDsi_InterruptEnable(void *InstancePtr, u32 Mask)
void XDsiTxSs_SetGlobalInterrupt(void *InstancePtr)
This function will enable the interrupts present in the interrupt mask passed onto the function.
InstancePtr is the XDsiTxSs instance to operate on. None.
References XDsiTxSs::DsiPtr.
void XDsiTxSs_InterruptEnable(void *InstancePtr, u32 Mask)
This function will enable the interrupts present in the interrupt mask passed onto the function.
InstancePtr is the XDsiTxSs instance to operate on Mask is the interrupt mask which need to be enabled in core
References XDsiTxSs::DsiPtr.
Referenced by DsiTxSs_IntrExample.
XDSITXSS_HW_H_
Prevent circular inclusions by using protection macros.
XDsiTxSs_In32
XDsiTxSs_Out32