xdsitxss_intr_example.c
XDSITXSS_BASE
XDsiTxSs DsiTxSs
XIntc InterruptController
volatile u8 data_err_flag
volatile u8 pixel_underrun_flag
volatile u8 cmdq_fifo_full_flag
u32 DsiTxSs_IntrExample(u32 DeviceId)
This function is the main entry point for the interrupt example using the DsiTxSs driver.
This function will set up the system with interrupts handlers. DeviceId is the unique device ID of the MIPI DSI Subsystem core. XST_FAILURE if the system setup failed.XST_SUCCESS should never return since this function, if setup was successful, is blocking. If system setup was successful, this function is blocking in order to illustrate interrupt handling taking place for HPD events.
References XDsiTxSs_Config::BaseAddr, Delay, DsiTxSs_CmdQFIFOFullEventHandler, DsiTxSs_PixelUnderrunEventHandler, DsiTxSs_UnSupportDataEventHandler, XDsiTxSs_CfgInitialize, XDSITXSS_HANDLER_CMDQ_FIFOFULL, XDSITXSS_HANDLER_PIXELDATA_UNDERRUN, XDSITXSS_HANDLER_UNSUPPORT_DATATYPE, XDSITXSS_IER_ALLINTR_MASK, XDsiTxSs_InterruptEnable, XDsiTxSs_LookupConfig, XDsiTxSs_SelfTest, XDsiTxSs_SetCallback.
Referenced by main.
u32 DsiTxSs_SetupIntrSystem(void)
void XDsiTxSs_IntrHandler(void *InstancePtr)
This function is the interrupt handler for the MIPI DSI Tx Subsystem.
The application is responsible for connecting this function to the interrupt system. Application beyond this driver is also responsible for providing callbacks to handle interrupts and installing the callbacks using XDsiTxSs_SetCallback() during initialization phase. InstancePtr is a pointer to the XDsiTxSs core instance that just interrupted. None.
References XDsiTxSs::DsiPtr.
u32 XDsiTxSs_SetCallback(XDsiTxSs *InstancePtr, u32 HandlerType, void *CallbackFunc, void *CallbackRef)
This routine installs an asynchronous callback function for the given HandlerType:
HandlerType Invoked by this driver when: ----------------------- -------------------------------------------------- XDSI_HANDLER_UNSUPPORT_DATATYPE Un support data type detected XDSI_HANDLER_PIXELDATA_UNDERRUN Byte Stream FIFO starves for Pixel during HACT transmission XDSI_HANDLER_OTHERERROR Any other type of interrupt has occurred like Stream Line Buffer Full, Incorrect Lanes, etc XDSI_HANDLER_CMDQ_FIFOFULL Command queue FIFO Full InstancePtr is the XDsi instance to operate on HandlerType is the type of call back to be registered. CallbackFunc is the pointer to a call back function which is called when a particular event occurs. CallbackRef is a void pointer to data to be referenced to by the CallbackFunc XST_SUCCESS when handler is installed. XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XDsiTxSs::IsReady, XDsiTxSs::DsiPtr.
Referenced by DsiTxSs_IntrExample.
void XDsiTxSs_SetGlobalInterrupt(void *InstancePtr)
This function will enable the interrupts present in the interrupt mask passed onto the function.
InstancePtr is the XDsiTxSs instance to operate on. None.
References XDsiTxSs::DsiPtr.
void XDsiTxSs_InterruptEnable(void *InstancePtr, u32 Mask)
This function will enable the interrupts present in the interrupt mask passed onto the function.
InstancePtr is the XDsiTxSs instance to operate on Mask is the interrupt mask which need to be enabled in core
References XDsiTxSs::DsiPtr.
Referenced by DsiTxSs_IntrExample.
void DsiTxSs_PixelUnderrunEventHandler(void *CallbackRef, u32 Mask)
This function is called when a Packet level error event is received by the MIPI DSI Tx Subsystem core.
CallbackRef is a pointer to the DsiTxSs instance. Mask of interrupt which caused this event None. Use the DsiTxSs_PixelUnderrunEventHandler driver function to set this function as the handler for Packet level error event.
References XDSITXSS_ISR_PIXELUNDERRUN_MASK.
Referenced by DsiTxSs_IntrExample.
void DsiTxSs_UnSupportDataEventHandler(void *CallbackRef, u32 Mask)
This function is called when a DPHY level error event is received by the MIPI DSI Rx Subsystem core.
CallbackRef is a pointer to the DsiTxSs instance. Mask of interrupt which caused this event None. Use the DsiTxSs_UnSupportDataEventHandler driver function to set this function as the handler for Unsupported data error event.
References XDSITXSS_ISR_DATAIDERR_MASK.
Referenced by DsiTxSs_IntrExample.
void DsiTxSs_CmdQFIFOFullEventHandler(void *CallbackRef, u32 Mask)
This function is called when a Command Queue FIFO full error event is received by the MIPI DSI Tx Subsystem core.
CallbackRef is a pointer to the DsiTxSs instance. Mask of interrupt which caused this event None. Use the DsiTxSs_CmdQFIFOFullEventHandler driver function to set this function as the handler for Command Queue FIFO Full error event.
References XDSITXSS_ISR_CMDQ_FIFO_FULL_MASK.
Referenced by DsiTxSs_IntrExample.
s32 main()
This is the main function for XDsiTxSs interrupt example.
If the DsiTxSs_IntrExample function which sets up the system succeeds, this function will wait for the interrupts. Notify the events None. XST_FAILURE if the interrupt example was unsuccessful. Unless setup failed, main will never return since DsiTxSs_IntrExample is blocking (it is waiting on interrupts for Hot-Plug-Detect (HPD) events.
References DsiTxSs_IntrExample.
void Delay(u32 Seconds)
For Microblaze we use an assembly loop that is roughly the same regardless of optimization level, although caches and memory access time can make the delay vary.
Just keep in mind that after resetting or updating the PHY modes, the PHY typically needs time to recover. Number of seconds to sleep None None
Referenced by DsiTxSs_IntrExample.