xdsitxss_video_test_example.c
XDSITXSS_DEVICE_ID
DMA_DEVICE_ID
BRAM_0_ADDRESS
BRAM_1_ADDRESS
NO_BYTES_PER_PIXEL
HORIZONTAL_RESOLUTION
HORIZONTAL_RESOLUTION_BYTES
VERTICAL_RESOLUTION
FRAME_COUNTER
STRIDE
HACT_VALUE
HSA_VALUE
HFP_VALUE
HBP_VALUE
VACT_VALUE
VSA_VALUE
VFP_VALUE
VBP_VALUE
BLLP_BURST_VALUE
VDMA_S2MM
VDMA_MM2S
MM2S_HALT_SUCCESS
MM2S_HALT_FAILURE
S2MM_HALT_SUCCESS
S2MM_HALT_FAILURE
ENABLE_FRAME_COUNT
ENABLE_CIRCULAR_MODE
START_VDMA
VDMA_BASEADDR
u8* SrcBuffer
u8* DstBuffer
XDsiTxSs DsiTxSsInst
volatile u32* Mm2sStatusReg
volatile u32* S2mmStatusReg
volatile u32* VdmaParkPtrReg
volatile u32* VdmaS2MMCrReg
volatile u32* VdmaS2MMStatusReg
volatile u32* VdmaS2MMVertSizeReg
volatile u32* VdmaS2MMHoriSizeReg
volatile u32* VdmaS2MMFrmDlrStrideReg
volatile u32* VdmaS2MMFrameBuffer0Reg
volatile u32* VdmaMM2SCrReg
volatile u32* VdmaMMS2StatusReg
volatile u32* VdmaMM2SVertSizeReg
volatile u32* VdmaMM2SHoriSizeReg
volatile u32* VdmaMM2SFrmDlrStrideReg
volatile u32* VdmaMM2SFrameBuffer0Reg
u32 DsiTxSs_VideoTestExample(u32 DeviceId)
This function is the main entry point for the video test example using the XDsiTxSs driver.
DeviceId is the unique device ID of the MIPI DSI RX Subsystem core. XST_FAILURE if any of MIPI DSI RX Subsystem sub-core self test failed.XST_SUCCESS, if all of MIPI DSI RX Subsystem sub-core self test passed. None.
References XDsiTxSs_Config::BaseAddr, ConfigureChannel, ResetVDMA, SetupVdmaCR, StartChannel, WaitForCompletion, XDsiTxSs_Activate, XDsiTxSs_CfgInitialize, XDSITXSS_ENABLE, XDsiTxSs_LookupConfig, XDsiTxSs_Reset, XDsiTxSs_SelfTest, XDsiTxSs_SetCustomVideoInterfaceTiming.
Referenced by main.
s32 WaitForCompletion(s32 VdmaChannel, u32 *VdmaBaseAddr)
This function wait until the DMA channel halts.
VdmaChannel specifies VdmaChannel is MM2S or S2MM . VdmaBaseAddr VDMA base address MM2S_HALT_SUCCESS, S2MM_HALT_SUCCESS in success MM2S_HALT_FAILURE, S2MM_HALT_FAILURE on failure None.
Referenced by DsiTxSs_VideoTestExample.
void ResetVDMA()
This function ResetVDMA.
None None None.
Referenced by DsiTxSs_VideoTestExample.
void ConfigureChannel(u32 VdmaChannel)
This function to setup Horizontal size and stride.
VdmaChannel specifies VdmaChannel is MM2S or S2MM None None.
Referenced by DsiTxSs_VideoTestExample.
void SetupVdmaCR(s32 VdmaChannel, s32 FrameCount)
This function to setup the VDMA Control Register.
VdmaChannel specifies VdmaChannel is MM2S or S2MM FrameCount specifies number of frames to transfer None None.
Referenced by DsiTxSs_VideoTestExample.
void StartChannel(s32 VdmaChannel, s32 VerticalSize)
This function to start mm2s or s2mm VdmaChannel - write the vertical size.
VdmaChannel specifies VdmaChannel is MM2S or S2MM VerticalSize specifies No of lines None None.
Referenced by DsiTxSs_VideoTestExample.
s32 main()
This is the main function for XDsiTxSs self test example.
None. XST_SUCCESS if the self test example passed.XST_FAILURE if the self test example was unsuccessful. None.
References DsiTxSs_VideoTestExample.