xdsitxss_sinit.c
XDsiTxSs_Config XDsiTxSs_ConfigTable[][]
Configuration table containing hardware configuration information for each XDsiTxSs instance in the system.
This table is populated by the platform configuration tool and is referenced by XDsiTxSs_LookupConfig during device initialization.
XDsiTxSs_Config * XDsiTxSs_LookupConfig(UINTPTR BaseAddress)
This function looks for the device configuration based on the unique device ID.
The table XDsiTxSs_ConfigTable[] contains the configuration information for each instance of the device in the system. DeviceId is the unique device ID of the device being looked up A pointer to the configuration table entry corresponding to the given device ID, or NULL if no match is found None.
Referenced by DsiTxSs_IntrExample, DsiTxSs_SelfTestExample, DsiTxSs_VideoTestExample.
u32 XDsiTxSs_GetDrvIndex(XDsiTxSs *InstancePtr, UINTPTR BaseAddress)
This function returns the Index number of config table using BaseAddress.
InstancePtr pointer to the instance structure BaseAddress address of the instance Index number of the config table