xdsitxss_selftest.c
u32 XDsiTxSs_SelfTest(XDsiTxSs *InstancePtr)
This function performs self test on MIPI DSI Tx Subsystem sub-cores.
InstancePtr is a pointer to the XDsiTxSs core instance. XST_SUCCESS if self test passed.XST_FAILURE if self test failed. None.
References XDsiTxSs::Config, XDsiTxSs_Config::DphyInfo, XDsiTxSs::DsiPtr, DsiTxSsSubCore::IsPresent.
Referenced by DsiTxSs_IntrExample, DsiTxSs_SelfTestExample, DsiTxSs_VideoTestExample.