/**
 * (c) 2013 Xilinx Inc.
 * XREGDB v0.91
 * XREGCHDR v0.15
 *
 * Generated on: 2018-11-11
 *
 * @file: slave_boot.h
 *
 *
 * This file contains confidential and proprietary information
 * of Xilinx, Inc. and is protected under U.S. and
 * international copyright and other intellectual property
 * laws.
 *
 * DISCLAIMER
 * This disclaimer is not a license and does not grant any
 * rights to the materials distributed herewith. Except as
 * otherwise provided in a valid license issued to you by
 * Xilinx, and to the maximum extent permitted by applicable
 * law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
 * WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
 * AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
 * BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
 * INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
 * (2) Xilinx shall not be liable (whether in contract or tort,
 * including negligence, or under any other theory of
 * liability) for any loss or damage of any kind or nature
 * related to, arising under or in connection with these
 * materials, including for any direct, or any indirect,
 * special, incidental, or consequential loss or damage
 * (including loss of data, profits, goodwill, or any type of
 * loss or damage suffered as a result of any action brought
 * by a third party) even if such damage or loss was
 * reasonably foreseeable or Xilinx had been advised of the
 * possibility of the same.
 *
 * CRITICAL APPLICATIONS
 * Xilinx products are not designed or intended to be fail-
 * safe, or for use in any application requiring fail-safe
 * performance, such as life-support or safety devices or
 * systems, Class III medical devices, nuclear facilities,
 * applications related to the deployment of airbags, or any
 * other applications that could lead to death, personal
 * injury, or severe property or environmental damage
 * (individually and collectively, "Critical
 * Applications"). Customer assumes the sole risk and
 * liability of any use of Xilinx products in Critical
 * Applications, subject only to applicable laws and
 * regulations governing limitations on product liability.
 *
 * THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
 * PART OF THIS FILE AT ALL TIMES.
 *
 * Naming Convention: <MODULE>_<REGISTER>[_<FIELD>[_<DESC>]]
 *     <MODULE>       Module name (e.g. can or usb)
 *     <REGISTER>     Register within the current module
 *     [_<FIELD>]     Bit field within a register
 *     [_<DESC>]      Type of bit field define:
 *         SHIFT:     Least significant bit for the field
 *         WIDTH:     Size of field in bites
 *         MASK:      A masking over a range of bits or a bit to
 *                    be used for setting or clearing
 *
 */

#ifndef _SLAVE_BOOT_H_
#define _SLAVE_BOOT_H_

#ifdef __cplusplus
extern "C" {
#endif

/**
 * SLAVE_BOOT Base Address
 */
#define SLAVE_BOOT_BASEADDR      0XF1220000

/**
 * Register: SLAVE_BOOT_SBI_MODE
 */
#define SLAVE_BOOT_SBI_MODE    ( ( SLAVE_BOOT_BASEADDR ) + 0X00000000 )

#define SLAVE_BOOT_SBI_MODE_JTAG_SHIFT   1
#define SLAVE_BOOT_SBI_MODE_JTAG_WIDTH   1
#define SLAVE_BOOT_SBI_MODE_JTAG_MASK    0X00000002

#define SLAVE_BOOT_SBI_MODE_SELECT_SHIFT   0
#define SLAVE_BOOT_SBI_MODE_SELECT_WIDTH   1
#define SLAVE_BOOT_SBI_MODE_SELECT_MASK    0X00000001

/**
 * Register: SLAVE_BOOT_SBI_CTRL
 */
#define SLAVE_BOOT_SBI_CTRL    ( ( SLAVE_BOOT_BASEADDR ) + 0X00000004 )

#define SLAVE_BOOT_SBI_CTRL_APB_ERR_RES_SHIFT   5
#define SLAVE_BOOT_SBI_CTRL_APB_ERR_RES_WIDTH   1
#define SLAVE_BOOT_SBI_CTRL_APB_ERR_RES_MASK    0X00000020

#define SLAVE_BOOT_SBI_CTRL_INTERFACE_SHIFT   2
#define SLAVE_BOOT_SBI_CTRL_INTERFACE_WIDTH   3
#define SLAVE_BOOT_SBI_CTRL_INTERFACE_MASK    0X0000001C

#define SLAVE_BOOT_SBI_CTRL_SOFT_RST_SHIFT   1
#define SLAVE_BOOT_SBI_CTRL_SOFT_RST_WIDTH   1
#define SLAVE_BOOT_SBI_CTRL_SOFT_RST_MASK    0X00000002

#define SLAVE_BOOT_SBI_CTRL_ENABLE_SHIFT   0
#define SLAVE_BOOT_SBI_CTRL_ENABLE_WIDTH   1
#define SLAVE_BOOT_SBI_CTRL_ENABLE_MASK    0X00000001

/**
 * Register: SLAVE_BOOT_SMAP_CTRL
 */
#define SLAVE_BOOT_SMAP_CTRL    ( ( SLAVE_BOOT_BASEADDR ) + 0X00000008 )

#define SLAVE_BOOT_SMAP_CTRL_BURST_SIZE_SHIFT   1
#define SLAVE_BOOT_SMAP_CTRL_BURST_SIZE_WIDTH   2
#define SLAVE_BOOT_SMAP_CTRL_BURST_SIZE_MASK    0X00000006

#define SLAVE_BOOT_SMAP_CTRL_MODE_SHIFT   0
#define SLAVE_BOOT_SMAP_CTRL_MODE_WIDTH   1
#define SLAVE_BOOT_SMAP_CTRL_MODE_MASK    0X00000001

/**
 * Register: SLAVE_BOOT_SBI_STATUS
 */
#define SLAVE_BOOT_SBI_STATUS    ( ( SLAVE_BOOT_BASEADDR ) + 0X0000000C )

#define SLAVE_BOOT_SBI_STATUS_JTAG_DOUT_FIFO_SPACE_SHIFT   28
#define SLAVE_BOOT_SBI_STATUS_JTAG_DOUT_FIFO_SPACE_WIDTH   4
#define SLAVE_BOOT_SBI_STATUS_JTAG_DOUT_FIFO_SPACE_MASK    0XF0000000

#define SLAVE_BOOT_SBI_STATUS_JTAG_DIN_FIFO_SPACE_SHIFT   24
#define SLAVE_BOOT_SBI_STATUS_JTAG_DIN_FIFO_SPACE_WIDTH   4
#define SLAVE_BOOT_SBI_STATUS_JTAG_DIN_FIFO_SPACE_MASK    0X0F000000

#define SLAVE_BOOT_SBI_STATUS_SMAP_DOUT_FIFO_SPACE_SHIFT   20
#define SLAVE_BOOT_SBI_STATUS_SMAP_DOUT_FIFO_SPACE_WIDTH   4
#define SLAVE_BOOT_SBI_STATUS_SMAP_DOUT_FIFO_SPACE_MASK    0X00F00000

#define SLAVE_BOOT_SBI_STATUS_SMAP_DIN_FIFO_SPACE_SHIFT   13
#define SLAVE_BOOT_SBI_STATUS_SMAP_DIN_FIFO_SPACE_WIDTH   7
#define SLAVE_BOOT_SBI_STATUS_SMAP_DIN_FIFO_SPACE_MASK    0X000FE000

#define SLAVE_BOOT_SBI_STATUS_CMN_BUF_SPACE_SHIFT   3
#define SLAVE_BOOT_SBI_STATUS_CMN_BUF_SPACE_WIDTH   10
#define SLAVE_BOOT_SBI_STATUS_CMN_BUF_SPACE_MASK    0X00001FF8

#define SLAVE_BOOT_SBI_STATUS_SMAP_WD_X32_SHIFT   2
#define SLAVE_BOOT_SBI_STATUS_SMAP_WD_X32_WIDTH   1
#define SLAVE_BOOT_SBI_STATUS_SMAP_WD_X32_MASK    0X00000004

#define SLAVE_BOOT_SBI_STATUS_SMAP_WD_X16_SHIFT   1
#define SLAVE_BOOT_SBI_STATUS_SMAP_WD_X16_WIDTH   1
#define SLAVE_BOOT_SBI_STATUS_SMAP_WD_X16_MASK    0X00000002

#define SLAVE_BOOT_SBI_STATUS_SMAP_WD_X8_SHIFT   0
#define SLAVE_BOOT_SBI_STATUS_SMAP_WD_X8_WIDTH   1
#define SLAVE_BOOT_SBI_STATUS_SMAP_WD_X8_MASK    0X00000001

/**
 * Register: SLAVE_BOOT_SBI_RDBK
 */
#define SLAVE_BOOT_SBI_RDBK    ( ( SLAVE_BOOT_BASEADDR ) + 0X00000100 )

#define SLAVE_BOOT_SBI_RDBK_DIS_SHIFT   0
#define SLAVE_BOOT_SBI_RDBK_DIS_WIDTH   1
#define SLAVE_BOOT_SBI_RDBK_DIS_MASK    0X00000001

/**
 * Register: SLAVE_BOOT_SBI_IRQ_STATUS
 */
#define SLAVE_BOOT_SBI_IRQ_STATUS    ( ( SLAVE_BOOT_BASEADDR ) + 0X00000300 )

#define SLAVE_BOOT_SBI_IRQ_STATUS_SMAP_CONFIG_ERR_SHIFT   5
#define SLAVE_BOOT_SBI_IRQ_STATUS_SMAP_CONFIG_ERR_WIDTH   1
#define SLAVE_BOOT_SBI_IRQ_STATUS_SMAP_CONFIG_ERR_MASK    0X00000020

#define SLAVE_BOOT_SBI_IRQ_STATUS_HSDP_SLVERR_SHIFT   4
#define SLAVE_BOOT_SBI_IRQ_STATUS_HSDP_SLVERR_WIDTH   1
#define SLAVE_BOOT_SBI_IRQ_STATUS_HSDP_SLVERR_MASK    0X00000010

#define SLAVE_BOOT_SBI_IRQ_STATUS_AXI_SLVERR_SHIFT   3
#define SLAVE_BOOT_SBI_IRQ_STATUS_AXI_SLVERR_WIDTH   1
#define SLAVE_BOOT_SBI_IRQ_STATUS_AXI_SLVERR_MASK    0X00000008

#define SLAVE_BOOT_SBI_IRQ_STATUS_DATA_RDY_SHIFT   2
#define SLAVE_BOOT_SBI_IRQ_STATUS_DATA_RDY_WIDTH   1
#define SLAVE_BOOT_SBI_IRQ_STATUS_DATA_RDY_MASK    0X00000004

#define SLAVE_BOOT_SBI_IRQ_STATUS_SMAP_ABORT_SHIFT   1
#define SLAVE_BOOT_SBI_IRQ_STATUS_SMAP_ABORT_WIDTH   1
#define SLAVE_BOOT_SBI_IRQ_STATUS_SMAP_ABORT_MASK    0X00000002

#define SLAVE_BOOT_SBI_IRQ_STATUS_INV_APB_SHIFT   0
#define SLAVE_BOOT_SBI_IRQ_STATUS_INV_APB_WIDTH   1
#define SLAVE_BOOT_SBI_IRQ_STATUS_INV_APB_MASK    0X00000001

/**
 * Register: SLAVE_BOOT_SBI_IRQ_MASK
 */
#define SLAVE_BOOT_SBI_IRQ_MASK    ( ( SLAVE_BOOT_BASEADDR ) + 0X00000304 )

#define SLAVE_BOOT_SBI_IRQ_MASK_SMAP_CONFIG_ERR_SHIFT   5
#define SLAVE_BOOT_SBI_IRQ_MASK_SMAP_CONFIG_ERR_WIDTH   1
#define SLAVE_BOOT_SBI_IRQ_MASK_SMAP_CONFIG_ERR_MASK    0X00000020

#define SLAVE_BOOT_SBI_IRQ_MASK_HSDP_SLVERR_SHIFT   4
#define SLAVE_BOOT_SBI_IRQ_MASK_HSDP_SLVERR_WIDTH   1
#define SLAVE_BOOT_SBI_IRQ_MASK_HSDP_SLVERR_MASK    0X00000010

#define SLAVE_BOOT_SBI_IRQ_MASK_AXI_SLVERR_SHIFT   3
#define SLAVE_BOOT_SBI_IRQ_MASK_AXI_SLVERR_WIDTH   1
#define SLAVE_BOOT_SBI_IRQ_MASK_AXI_SLVERR_MASK    0X00000008

#define SLAVE_BOOT_SBI_IRQ_MASK_DATA_RDY_SHIFT   2
#define SLAVE_BOOT_SBI_IRQ_MASK_DATA_RDY_WIDTH   1
#define SLAVE_BOOT_SBI_IRQ_MASK_DATA_RDY_MASK    0X00000004

#define SLAVE_BOOT_SBI_IRQ_MASK_SMAP_ABORT_SHIFT   1
#define SLAVE_BOOT_SBI_IRQ_MASK_SMAP_ABORT_WIDTH   1
#define SLAVE_BOOT_SBI_IRQ_MASK_SMAP_ABORT_MASK    0X00000002

#define SLAVE_BOOT_SBI_IRQ_MASK_INV_APB_SHIFT   0
#define SLAVE_BOOT_SBI_IRQ_MASK_INV_APB_WIDTH   1
#define SLAVE_BOOT_SBI_IRQ_MASK_INV_APB_MASK    0X00000001

/**
 * Register: SLAVE_BOOT_SBI_IRQ_ENABLE
 */
#define SLAVE_BOOT_SBI_IRQ_ENABLE    ( ( SLAVE_BOOT_BASEADDR ) + 0X00000308 )

#define SLAVE_BOOT_SBI_IRQ_ENABLE_SMAP_CONFIG_ERR_SHIFT   5
#define SLAVE_BOOT_SBI_IRQ_ENABLE_SMAP_CONFIG_ERR_WIDTH   1
#define SLAVE_BOOT_SBI_IRQ_ENABLE_SMAP_CONFIG_ERR_MASK    0X00000020

#define SLAVE_BOOT_SBI_IRQ_ENABLE_HSDP_SLVERR_SHIFT   4
#define SLAVE_BOOT_SBI_IRQ_ENABLE_HSDP_SLVERR_WIDTH   1
#define SLAVE_BOOT_SBI_IRQ_ENABLE_HSDP_SLVERR_MASK    0X00000010

#define SLAVE_BOOT_SBI_IRQ_ENABLE_AXI_SLVERR_SHIFT   3
#define SLAVE_BOOT_SBI_IRQ_ENABLE_AXI_SLVERR_WIDTH   1
#define SLAVE_BOOT_SBI_IRQ_ENABLE_AXI_SLVERR_MASK    0X00000008

#define SLAVE_BOOT_SBI_IRQ_ENABLE_DATA_RDY_SHIFT   2
#define SLAVE_BOOT_SBI_IRQ_ENABLE_DATA_RDY_WIDTH   1
#define SLAVE_BOOT_SBI_IRQ_ENABLE_DATA_RDY_MASK    0X00000004

#define SLAVE_BOOT_SBI_IRQ_ENABLE_SMAP_ABORT_SHIFT   1
#define SLAVE_BOOT_SBI_IRQ_ENABLE_SMAP_ABORT_WIDTH   1
#define SLAVE_BOOT_SBI_IRQ_ENABLE_SMAP_ABORT_MASK    0X00000002

#define SLAVE_BOOT_SBI_IRQ_ENABLE_INV_APB_SHIFT   0
#define SLAVE_BOOT_SBI_IRQ_ENABLE_INV_APB_WIDTH   1
#define SLAVE_BOOT_SBI_IRQ_ENABLE_INV_APB_MASK    0X00000001

/**
 * Register: SLAVE_BOOT_SBI_IRQ_DISABLE
 */
#define SLAVE_BOOT_SBI_IRQ_DISABLE    ( ( SLAVE_BOOT_BASEADDR ) + 0X0000030C )

#define SLAVE_BOOT_SBI_IRQ_DISABLE_SMAP_CONFIG_ERR_SHIFT   5
#define SLAVE_BOOT_SBI_IRQ_DISABLE_SMAP_CONFIG_ERR_WIDTH   1
#define SLAVE_BOOT_SBI_IRQ_DISABLE_SMAP_CONFIG_ERR_MASK    0X00000020

#define SLAVE_BOOT_SBI_IRQ_DISABLE_HSDP_SLVERR_SHIFT   4
#define SLAVE_BOOT_SBI_IRQ_DISABLE_HSDP_SLVERR_WIDTH   1
#define SLAVE_BOOT_SBI_IRQ_DISABLE_HSDP_SLVERR_MASK    0X00000010

#define SLAVE_BOOT_SBI_IRQ_DISABLE_AXI_SLVERR_SHIFT   3
#define SLAVE_BOOT_SBI_IRQ_DISABLE_AXI_SLVERR_WIDTH   1
#define SLAVE_BOOT_SBI_IRQ_DISABLE_AXI_SLVERR_MASK    0X00000008

#define SLAVE_BOOT_SBI_IRQ_DISABLE_DATA_RDY_SHIFT   2
#define SLAVE_BOOT_SBI_IRQ_DISABLE_DATA_RDY_WIDTH   1
#define SLAVE_BOOT_SBI_IRQ_DISABLE_DATA_RDY_MASK    0X00000004

#define SLAVE_BOOT_SBI_IRQ_DISABLE_SMAP_ABORT_SHIFT   1
#define SLAVE_BOOT_SBI_IRQ_DISABLE_SMAP_ABORT_WIDTH   1
#define SLAVE_BOOT_SBI_IRQ_DISABLE_SMAP_ABORT_MASK    0X00000002

#define SLAVE_BOOT_SBI_IRQ_DISABLE_INV_APB_SHIFT   0
#define SLAVE_BOOT_SBI_IRQ_DISABLE_INV_APB_WIDTH   1
#define SLAVE_BOOT_SBI_IRQ_DISABLE_INV_APB_MASK    0X00000001

/**
 * Register: SLAVE_BOOT_SBI_IRQ_TRIGGER
 */
#define SLAVE_BOOT_SBI_IRQ_TRIGGER    ( ( SLAVE_BOOT_BASEADDR ) + 0X00000310 )

#define SLAVE_BOOT_SBI_IRQ_TRIGGER_HSDP_SLVERR_SHIFT   4
#define SLAVE_BOOT_SBI_IRQ_TRIGGER_HSDP_SLVERR_WIDTH   1
#define SLAVE_BOOT_SBI_IRQ_TRIGGER_HSDP_SLVERR_MASK    0X00000010

#define SLAVE_BOOT_SBI_IRQ_TRIGGER_AXI_SLVERR_SHIFT   3
#define SLAVE_BOOT_SBI_IRQ_TRIGGER_AXI_SLVERR_WIDTH   1
#define SLAVE_BOOT_SBI_IRQ_TRIGGER_AXI_SLVERR_MASK    0X00000008

#define SLAVE_BOOT_SBI_IRQ_TRIGGER_DATA_RDY_SHIFT   2
#define SLAVE_BOOT_SBI_IRQ_TRIGGER_DATA_RDY_WIDTH   1
#define SLAVE_BOOT_SBI_IRQ_TRIGGER_DATA_RDY_MASK    0X00000004

#define SLAVE_BOOT_SBI_IRQ_TRIGGER_SMAP_ABORT_SHIFT   1
#define SLAVE_BOOT_SBI_IRQ_TRIGGER_SMAP_ABORT_WIDTH   1
#define SLAVE_BOOT_SBI_IRQ_TRIGGER_SMAP_ABORT_MASK    0X00000002

#define SLAVE_BOOT_SBI_IRQ_TRIGGER_INV_APB_SHIFT   0
#define SLAVE_BOOT_SBI_IRQ_TRIGGER_INV_APB_WIDTH   1
#define SLAVE_BOOT_SBI_IRQ_TRIGGER_INV_APB_MASK    0X00000001

/**
 * Register: SLAVE_BOOT_SBI_RAM
 */
#define SLAVE_BOOT_SBI_RAM    ( ( SLAVE_BOOT_BASEADDR ) + 0X00000500 )

#define SLAVE_BOOT_SBI_RAM_EMASA_SHIFT   6
#define SLAVE_BOOT_SBI_RAM_EMASA_WIDTH   1
#define SLAVE_BOOT_SBI_RAM_EMASA_MASK    0X00000040

#define SLAVE_BOOT_SBI_RAM_EMAB_SHIFT   3
#define SLAVE_BOOT_SBI_RAM_EMAB_WIDTH   3
#define SLAVE_BOOT_SBI_RAM_EMAB_MASK    0X00000038

#define SLAVE_BOOT_SBI_RAM_EMAA_SHIFT   0
#define SLAVE_BOOT_SBI_RAM_EMAA_WIDTH   3
#define SLAVE_BOOT_SBI_RAM_EMAA_MASK    0X00000007

/**
 * Register: SLAVE_BOOT_SBI_ECO
 */
#define SLAVE_BOOT_SBI_ECO    ( ( SLAVE_BOOT_BASEADDR ) + 0X00001000 )

#define SLAVE_BOOT_SBI_ECO_VAL_SHIFT   0
#define SLAVE_BOOT_SBI_ECO_VAL_WIDTH   32
#define SLAVE_BOOT_SBI_ECO_VAL_MASK    0XFFFFFFFF

#ifdef __cplusplus
}
#endif


#endif /* _SLAVE_BOOT_H_ */
