i2stx
XI2s_Tx_HandlerType
AES Block Complete Handler.
XI2s_Tx_ChMuxInput
Channel disabled.
XI2S_TX_AES_STS_USE_OF_CH_STS_BLK_SHIFT
Use of Channel Status Block bit shift.
XI2S_TX_AES_STS_USE_OF_CH_STS_BLK_MASK
Use of Channel Status Block mask.
Referenced by XI2s_Tx_ReslveAesChStat.
XI2S_TX_AES_STS_LINEAR_PCM_ID_SHIFT
Linear PCM Identification bit shift.
Referenced by XI2s_Tx_ReslveAesChStat.
XI2S_TX_AES_STS_LINEAR_PCM_ID_MASK
Linear PCM Identification mask.
Referenced by XI2s_Tx_ReslveAesChStat.
XI2S_TX_AES_STS_AUDIO_SIG_PRE_EMPH_SHIFT
Audio signal pre- emphasis bit shift.
Referenced by XI2s_Tx_ReslveAesChStat.
XI2S_TX_AES_STS_AUDIO_SIG_PRE_EMPH_MASK
Audio signal pre-emphasis mask.
Referenced by XI2s_Tx_ReslveAesChStat.
XI2S_TX_AES_STS_LOCK_INDICATION_SHIFT
lock indication bit shift
Referenced by XI2s_Tx_ReslveAesChStat.
XI2S_TX_AES_STS_LOCK_INDICATION_MASK
Lock indication mask.
Referenced by XI2s_Tx_ReslveAesChStat.
XI2S_TX_AES_STS_SAMPLING_FREQ_E_SHIFT
Sampling Frequency 0 bit shift.
Referenced by XI2s_Tx_ReslveAesChStat.
XI2S_TX_AES_STS_SAMPLING_FREQ_E_MASK
Sampling Frequency 0 mask.
Referenced by XI2s_Tx_ReslveAesChStat.
XI2S_TX_AES_STS_CH_MODE_SHIFT
Channel mode bit shift.
XI2S_TX_AES_STS_CH_MODE_MASK
Channel mode mask.
Referenced by XI2s_Tx_ReslveAesChStat.
XI2S_TX_AES_STS_USR_BITS_MGMT_SHIFT
User Bits Management bit shift.
Referenced by XI2s_Tx_ReslveAesChStat.
XI2S_TX_AES_STS_USR_BITS_MGMT_MASK
User Bits Management mask.
Referenced by XI2s_Tx_ReslveAesChStat.
XI2S_TX_AES_STS_USEOF_AUX_SMPL_BITS_SHIFT
Use of auxiliary sample bits bit shift.
XI2S_TX_AES_STS_USEOF_AUX_SMPL_BITS_MASK
Use of Auxiliary sample bits mask.
Referenced by XI2s_Tx_ReslveAesChStat.
XI2S_TX_AES_STS_SRC_WORD_LENGTH_SHIFT
Source word length bit shift.
Referenced by XI2s_Tx_ReslveAesChStat.
XI2S_TX_AES_STS_SRC_WORD_LENGTH_MASK
Source word length mask.
Referenced by XI2s_Tx_ReslveAesChStat.
XI2S_TX_AES_STS_INDICATE_ALIGN_LEVEL_SHIFT
Indication of Alignment level bit shift.
Referenced by XI2s_Tx_ReslveAesChStat.
XI2S_TX_AES_STS_INDICATE_ALIGN_LEVEL_MASK
Indication of Alignment level mask.
Referenced by XI2s_Tx_ReslveAesChStat.
XI2S_TX_AES_STS_CH_NUM0_SHIFT
Channel Number (0) bit shift.
XI2S_TX_AES_STS_CH_NUM0_MASK
Channel Number (0) mask.
Referenced by XI2s_Tx_ReslveAesChStat.
XI2S_TX_AES_STS_MC_CH_MODE_SHIFT
Multichannel mode bit shift.
Referenced by XI2s_Tx_ReslveAesChStat.
XI2S_TX_AES_STS_MC_CH_MODE_MASK
Multichannel mode mask.
Referenced by XI2s_Tx_ReslveAesChStat.
XI2S_TX_AES_STS_CH_NUM1_SHIFT
Channel Number (1) bit shift.
XI2S_TX_AES_STS_CH_NUM1_MASK
Channel Number (1) mask.
Referenced by XI2s_Tx_ReslveAesChStat.
XI2S_TX_AES_STS_MC_CH_MODE_NUM_SHIFT
Multichannel mode number bit shift.
Referenced by XI2s_Tx_ReslveAesChStat.
XI2S_TX_AES_STS_MC_CH_MODE_NUM_MASK
Multichannel mode number mask.
Referenced by XI2s_Tx_ReslveAesChStat.
XI2S_TX_AES_STS_DIGITAL_AUDIO_REF_SIG_SHIFT
Digital Reference Audio signal bit shift.
Referenced by XI2s_Tx_ReslveAesChStat.
XI2S_TX_AES_STS_DIGITAL_AUDIO_REF_SIG_MASK
Digital Reference Audio signal mask.
Referenced by XI2s_Tx_ReslveAesChStat.
XI2S_TX_AES_STS_RSVD_BUT_UNDEF0_SHIFT
Reserved but undefined (0) bit shift.
Referenced by XI2s_Tx_ReslveAesChStat.
XI2S_TX_AES_STS_RSVD_BUT_UNDEF0_MASK
Reserved but undefined (0) mask.
Referenced by XI2s_Tx_ReslveAesChStat.
XI2S_TX_AES_STS_SAMPLING_FREQ_Q_SHIFT
Sampling Frequency (1) bit shift.
Referenced by XI2s_Tx_ReslveAesChStat.
XI2S_TX_AES_STS_SAMPLING_FREQ_Q_MASK
Sampling Frequency (1) mask.
Referenced by XI2s_Tx_ReslveAesChStat.
XI2S_TX_AES_STS_SAMPLING_FREQ_SCALE_FLAG_SHIFT
Sampling Frequency scaling flag bit shift.
Referenced by XI2s_Tx_ReslveAesChStat.
XI2S_TX_AES_STS_SAMPLING_FREQ_SCALE_FLAG_MASK
Sampling Frequency scaling flag mask.
Referenced by XI2s_Tx_ReslveAesChStat.
XI2S_TX_AES_STS_RSVD_BUT_UNDEF1_SHIFT
Reserved but undefined (1) bit shift.
XI2S_TX_AES_STS_RSVD_BUT_UNDEF1_MASK
Reserved but undefined (1) mask.
Referenced by XI2s_Tx_ReslveAesChStat.
XI2S_TX_AES_STS_ALPHANUM_CH_ORG_DATA_OFFSET
Alphanumeric channel origin data register(s) offset.
XI2S_TX_AES_STS_ALPHANUM_CH_DEST_DATA_OFFSET
Alphanumeric channel destination data bit shift.
XI2S_TX_AES_STS_LOCAL_SAMPLE_ADDRCODE_OFFSET
Local sample address code register(s) offset.
XI2S_TX_AES_STS_TIMEOFDAY_SAMPLE_ADDRCODE_OFFSET
Time-of-day sample address code register(s) offset.
XI2S_TX_AES_STS_RELIABLE_FLAGS_OFFSET
Reliability flags bit shift.
Referenced by XI2s_Tx_ReslveAesChStat.
XI2S_TX_AES_STS_CRC_CHAR_OFFSET
Cyclic redundancy check character bit shift.
Referenced by XI2s_Tx_ReslveAesChStat.
XI2S_TX_LOG_ITEM_BUFFER_SIZE
@ name Log Item Buffer Size
XI2s_Tx_LogEvt
AES Block Complete Event.
XI2S_TX_CORE_VER_OFFSET
Core Version Register.
XI2S_TX_CORE_CFG_OFFSET
Core Configuration Register.
XI2S_TX_CORE_CTRL_OFFSET
Core Control Register.
Referenced by XI2s_Tx_Enable, XI2s_Tx_Justify, XI2s_Tx_JustifyEnable.
XI2S_TX_IRQCTRL_OFFSET
Interrupt Control Register.
Referenced by XI2s_Tx_IntrDisable, XI2s_Tx_IntrEnable, XI2s_Tx_IntrHandler.
XI2S_TX_IRQSTS_OFFSET
Interrupt Status Register.
Referenced by XI2s_Tx_IntrHandler.
XI2S_TX_TMR_CTRL_OFFSET
I2S Timing Control Register.
Referenced by XI2s_Tx_SetSclkOutDiv.
XI2S_TX_CH01_OFFSET
Audio Channel 0/1 Control Register.
Referenced by XI2s_Tx_SetChMux.
XI2S_TX_CH23_OFFSET
Audio Channel 2/3 Control Register.
XI2S_TX_CH45_OFFSET
Audio Channel 4/5 Control Register.
XI2S_TX_CH67_OFFSET
Audio Channel 6/7 Control Register.
XI2S_TX_AES_CHSTS0_OFFSET
AES Channel Status 0 Register.
Referenced by XI2s_Tx_ClrAesChStatRegs, XI2s_Tx_GetAesChStatus.
XI2S_TX_AES_CHSTS1_OFFSET
AES Channel Status 1 Register.
Referenced by XI2s_Tx_ClrAesChStatRegs.
XI2S_TX_AES_CHSTS2_OFFSET
AES Channel Status 2 Register.
Referenced by XI2s_Tx_ClrAesChStatRegs.
XI2S_TX_AES_CHSTS3_OFFSET
AES Channel Status 3 Register.
Referenced by XI2s_Tx_ClrAesChStatRegs.
XI2S_TX_AES_CHSTS4_OFFSET
AES Channel Status 4 Register.
Referenced by XI2s_Tx_ClrAesChStatRegs.
XI2S_TX_AES_CHSTS5_OFFSET
AES Channel Status 5 Register.
Referenced by XI2s_Tx_ClrAesChStatRegs.
XI2S_TX_REG_CFG_MSTR_SHIFT
Is I2S Master bit shift.
XI2S_TX_REG_CFG_MSTR_MASK
Is I2S Master mask.
XI2S_TX_REG_CFG_NUM_CH_SHIFT
Maximum number of channels bit shift.
XI2S_TX_REG_CFG_NUM_CH_MASK
Maximum number of channels mask.
XI2S_TX_REG_CFG_DWDTH_SHIFT
I2S Data Width bit shift.
XI2S_TX_REG_CFG_DWDTH_MASK
I2S Data Width mask.
XI2S_TX_REG_CTRL_EN_SHIFT
Module Enable bit shift.
XI2S_TX_REG_CTRL_EN_MASK
Module Enable mask.
Referenced by XI2s_Tx_Enable.
XI2S_TX_REG_CTRL_JFE_SHIFT
Justification Enable or Disable shift.
XI2S_TX_REG_CTRL_JFE_MASK
Justification Enable or Disable mask.
Referenced by XI2s_Tx_JustifyEnable.
XI2S_TX_REG_CTRL_LORJF_SHIFT
Left or Right Justification shift.
XI2S_TX_REG_CTRL_LORJF_MASK
Left or Right Justification mask.
Referenced by XI2s_Tx_Justify.
XI2S_TX_INTR_AES_BLKCMPLT_SHIFT
AES Block Complete Interrupt bit shift.
XI2S_TX_INTR_AES_BLKCMPLT_MASK
AES Block Complete Interrupt mask.
Referenced by XI2s_Tx_IntrHandler.
XI2S_TX_INTR_AES_BLKSYNCERR_SHIFT
AES Block Synchronization Error Interrupt bit shift.
XI2S_TX_INTR_AES_BLKSYNCERR_MASK
AES Block Synchronization Error Interrupt mask.
Referenced by XI2s_Tx_IntrHandler.
XI2S_TX_INTR_AES_CHSTSUPD_SHIFT
AES Channel Status Updated Interrupt bit shift.
XI2S_TX_INTR_AES_CHSTSUPD_MASK
AES Channel Status Updated Interrupt mask.
Referenced by XI2s_Tx_IntrHandler.
XI2S_TX_INTR_AUDUNDRFLW_SHIFT
Audio Underflow Detected Interrupt bit shift.
XI2S_TX_INTR_AUDUNDRFLW_MASK
Audio Underflow Detected Interrupt mask.
Referenced by XI2s_Tx_IntrHandler.
XI2S_TX_GINTR_EN_SHIFT
Global Interrupt Enable bit shift.
XI2S_TX_GINTR_EN_MASK
Global Interrupt Enable mask.
XI2S_TX_REG_TMR_SCLKDIV_SHIFT
SClk Divider bit shift.
XI2S_TX_REG_TMR_SCLKDIV_MASK
SClk Divider mask.
XI2S_TX_REG_CHCTRL_CHMUX_SHIFT
Channel MUX bit shift.
XI2S_TX_REG_CHCTRL_CHMUX_MASK
Channel MUX mask.
XI2s_Tx_In32
Input Operations.
XI2s_Tx_Out32
Output Operations.
XI2s_Tx_ReadReg
This macro reads a value from a I2S Transmitter register.
A 32 bit read is performed. If the component is implemented in a smaller width, only the least significant data is read from the register. The most significant data will be read as 0. BaseAddress is the base address of the I2S Transmitter core instance. RegOffset is the register offset of the register (defined at the top of this file). The 32-bit value of the register. C-style signature: u32 XI2S_Tx_ReadReg(u32 BaseAddress, u32 RegOffset)
Referenced by XI2s_Tx_Enable, XI2s_Tx_GetAesChStatus, XI2s_Tx_IntrDisable, XI2s_Tx_IntrEnable, XI2s_Tx_IntrHandler, XI2s_Tx_Justify, XI2s_Tx_JustifyEnable.
XI2s_Tx_WriteReg
This macro writes a value to a I2S Transmitter register.
A 32 bit write is performed. If the component is implemented in a smaller width, only the least significant data is written. BaseAddress is the base address of the I2S Transmitter core instance. RegOffset is the register offset of the register (defined at the top of this file) to be written. Data is the 32-bit value to write into the register. None. C-style signature: void XI2S_Tx_WriteReg(u32 BaseAddress, u32 RegOffset, u32 Data)
Referenced by XI2s_Tx_ClrAesChStatRegs, XI2s_Tx_Enable, XI2s_Tx_IntrDisable, XI2s_Tx_IntrEnable, XI2s_Tx_Justify, XI2s_Tx_JustifyEnable, XI2s_Tx_SetChMux, XI2s_Tx_SetSclkOutDiv.
XI2s_Tx_ChannelId
Channel 0.
XI2s_Tx_Justification
Left Justification is enabled.
XI2s_Tx_Callback)(void *CallbackRef)
Callback function pointer type for I2S Transmitter events.
This typedef defines the signature for callback functions that are invoked in response to I2S transmitter events or interrupts. CallbackRef A void pointer to user-defined callback reference data. This parameter allows the callback to access context-specific information passed during callback registration. The callback function should not perform blocking operations or lengthy computations, as it may be called from an interrupt context. XI2s_Tx_SetCallback
XI2stx_Config XI2stx_ConfigTable[][]
int XI2s_Tx_CfgInitialize(XI2s_Tx *InstancePtr, XI2stx_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the I2S Transmitter.
This function must be called prior to using the core. Initialization of the I2S Transmitter includes setting up the instance data, and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the I2s Transmitter instance. CfgPtr points to the configuration structure associated with the I2s Transmitter. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS : if successful.XST_FAILURE : otherwise. None.
References XI2stx_Config::BaseAddress, XI2s_Tx::Config, XI2s_Tx::IsReady, XI2s_Tx_Enable, XI2s_Tx_SelfTest.
Referenced by I2sSelfTestExample.
void XI2s_Tx_Enable(XI2s_Tx *InstancePtr, u8 Enable)
This function enables/disables the I2s Transmitter.
InstancePtr is a pointer to the I2s Transmitter instance. Enable specifies TRUE/FALSE value to either enable or disable the I2s Transmitter.
References XI2stx_Config::BaseAddress, XI2s_Tx::Config, XI2s_Tx::IsStarted, XI2S_TX_CORE_CTRL_OFFSET, XI2s_Tx_ReadReg, XI2S_TX_REG_CTRL_EN_MASK, XI2s_Tx_WriteReg.
Referenced by XI2s_Tx_CfgInitialize.
void XI2s_Tx_IntrEnable(XI2s_Tx *InstancePtr, u32 Mask)
This function enables the specified interrupt of the I2s Transmitter.
InstancePtr is a pointer to the I2s Transmitter instance. Mask is a bit mask of the interrupts to be enabled. XI2stx_hw.h for the available interrupt masks.
References XI2stx_Config::BaseAddress, XI2s_Tx::Config, XI2S_TX_IRQCTRL_OFFSET, XI2s_Tx_ReadReg, XI2s_Tx_WriteReg.
void XI2s_Tx_IntrDisable(XI2s_Tx *InstancePtr, u32 Mask)
Disables interrupts for the I2S Transmitter instance.
This function disables one or more interrupts for the specified I2S Transmitter instance based on the provided interrupt mask. InstancePtr Pointer to the XI2s_Tx instance to be worked on. Mask A bitmask specifying which interrupts to disable. Each bit in the mask corresponds to a specific interrupt source. The caller is responsible for ensuring that InstancePtr is a valid pointer to an initialized XI2s_Tx instance.
References XI2stx_Config::BaseAddress, XI2s_Tx::Config, XI2S_TX_IRQCTRL_OFFSET, XI2s_Tx_ReadReg, XI2s_Tx_WriteReg.
int XI2s_Tx_SetChMux(XI2s_Tx *InstancePtr, XI2s_Tx_ChannelId ChID, XI2s_Tx_ChMuxInput InputSource)
This function sets the input source for the specified I2s channel.
InstancePtr is a pointer to the I2s Transmitter instance. ChID specifies the I2s channel InputSource specifies the input source XST_SUCCESS : if successful.XST_FAILURE : if the I2s channel is invalid.
References XI2stx_Config::BaseAddress, XI2s_Tx::Config, XI2S_TX_CH01_OFFSET, XI2S_TX_CHMUX_AXIS_01, XI2S_TX_CHMUX_AXIS_23, XI2S_TX_CHMUX_AXIS_45, XI2S_TX_CHMUX_AXIS_67, XI2S_TX_CHMUX_WAVEGEN, XI2S_TX_NUM_CHANNELS, XI2s_Tx_WriteReg.
u32 XI2s_Tx_SetSclkOutDiv(XI2s_Tx *InstancePtr, u32 MClk, u32 Fs)
This function calculates the SCLK Output divider value of the I2S timing generator.
InstancePtr is a pointer to the I2s Transmitter instance. MClk is the frequency of the MClk. Fs is the sampling frequency of the system. Divider value for the SCLK generation, MCLK/SCLK = SCLKOUT_DIV x 2 i.e. MCLK = 384xFs, SCLK = 48xFs (2x24bits) -> SCLKOUT_DIV = MCLK/SCLK/2 = 4 Valid values are 1 through 15. - XST_FAILURE if SCLK Output divider is not calculated to be a positive integer. XST_SUCCESS, otherwise.
References XI2stx_Config::BaseAddress, XI2s_Tx::Config, XI2stx_Config::DWidth, XI2S_TX_TMR_CTRL_OFFSET, XI2s_Tx_WriteReg.
void XI2s_Tx_GetAesChStatus(XI2s_Tx *InstancePtr, u8 *AesChStatusBuf)
This function gets the captured AES Channel Status bits.
InstancePtr is a pointer to the I2s Transmitter instance. AesChStatusBuf is a pointer to a buffer that is used for writing the AES Channel Status bits, this needs to be allocated by user application
References XI2stx_Config::BaseAddress, XI2s_Tx::Config, XI2S_TX_AES_CHSTS0_OFFSET, XI2s_Tx_ReadReg.
void XI2s_Tx_ClrAesChStatRegs(XI2s_Tx *InstancePtr)
This function clears the captured AES Channel Status bits.
This will clear all the 6 channel status registers. InstancePtr is a pointer to the XI2s_Tx core instance.
References XI2S_TX_AES_CHSTS0_OFFSET, XI2S_TX_AES_CHSTS1_OFFSET, XI2S_TX_AES_CHSTS2_OFFSET, XI2S_TX_AES_CHSTS3_OFFSET, XI2S_TX_AES_CHSTS4_OFFSET, XI2S_TX_AES_CHSTS5_OFFSET, XI2s_Tx_WriteReg.
void XI2s_Tx_JustifyEnable(XI2s_Tx *InstancePtr, u8 Enable)
This function enables/disables the justification.
InstancePtr is a pointer to the XI2s Transmitter instance. Enable specifies TRUE/FALSE value to either enable or disable the justification.
References XI2stx_Config::BaseAddress, XI2s_Tx::Config, XI2S_TX_CORE_CTRL_OFFSET, XI2s_Tx_ReadReg, XI2S_TX_REG_CTRL_JFE_MASK, XI2s_Tx_WriteReg.
void XI2s_Tx_Justify(XI2s_Tx *InstancePtr, XI2s_Tx_Justification Justify)
This function is to enable right/left justification.
InstancePtr is a pointer to the XI2s Transmitter instance. Justify is a enum to select the left or right justification. XI2S_TX_JUSTIFY_LEFT : Left justificationXI2S_TX_JUSTIFY_RIGHT : Right justification
References XI2stx_Config::BaseAddress, XI2s_Tx::Config, XI2S_TX_CORE_CTRL_OFFSET, XI2s_Tx_ReadReg, XI2S_TX_REG_CTRL_LORJF_MASK, XI2s_Tx_WriteReg.
static u32 XI2s_Tx_GetVersion(XI2s_Tx *InstancePtr)
This inline function reads the I2s Transmitter version.
InstancePtr is a pointer to the XI2s_Tx core instance. I2sTx_Version
static void XI2s_Tx_IntrClear(XI2s_Tx *InstancePtr, u32 Mask)
This inline function clears the specified interrupt of the XI2s Transmitter.
InstancePtr is a pointer to the XI2s_Tx core instance. Mask is a bit mask of the interrupts to be cleared. None. XI2stx_hw.h file for the available interrupt masks.
static void XI2s_Tx_LogEnable(XI2s_Tx *InstancePtr)
This inline function enables the I2s Transmitter logging.
InstancePtr is a pointer to the XI2s_Tx core instance. None.
static void XI2s_Tx_LogDisable(XI2s_Tx *InstancePtr)
This inline function disables the I2s Transmitter logging.
InstancePtr is a pointer to the XI2s_Tx core instance. None.
int XI2s_Tx_SelfTest(XI2s_Tx *InstancePtr)
Runs a self-test on the driver/device.
The self-test is reads the version register, configuration registers and verifies the values InstancePtr is a pointer to the XI2s_Tx instance. XST_SUCCESS if successful i.e. if the self test passes.XST_FAILURE if unsuccessful i.e. if the self test fails None.
References XI2s_Tx_GetMaxChannels, XI2s_Tx_IsI2sMaster.
Referenced by I2sSelfTestExample, XI2s_Tx_CfgInitialize.
XI2stx_Config * XI2s_Tx_LookupConfig(UINTPTR BaseAddress)
This function returns a reference to an XI2stx_Config structure based on the core id, DeviceId.
The return value will refer to an entry in the device configuration table defined in the xi2stx_g.c file. DeviceId is the unique core ID of the I2S Transmitter core for the lookup operation. returns a reference to a config record in the configuration table corresponding to DeviceId, or NULL if no match is found. None.
Referenced by I2sSelfTestExample.
void XI2S_Tx_IntrDisable(XI2s_Tx *InstancePtr, u32 Mask)
Disables interrupts for the I2S Transmitter instance.
This function disables one or more interrupts for the specified I2S Transmitter instance based on the provided interrupt mask. InstancePtr Pointer to the XI2s_Tx instance to be worked on. Mask A bitmask specifying which interrupts to disable. Each bit in the mask corresponds to a specific interrupt source. The caller is responsible for ensuring that InstancePtr is a valid pointer to an initialized XI2s_Tx instance.
void XI2s_Tx_IntrHandler(void *InstancePtr)
This function is the interrupt handler for the I2S Transmitter driver.
This handler reads the pending interrupt from the I2S Transmitter peripheral, determines the source of the interrupts, clears the interrupts and calls callbacks accordingly. InstancePtr is a pointer to the XI2s_Tx instance. None.
References XI2s_Tx::AesBlkCmpltHandler, XI2s_Tx::AesBlkSyncErrHandler, XI2s_Tx::AudUndrflwHandler, XI2stx_Config::BaseAddress, XI2s_Tx::Config, XI2s_Tx::IsReady, XI2S_TX_AES_BLKCMPLT_EVT, XI2S_TX_AES_BLKSYNCERR_EVT, XI2S_TX_AES_CHSTSUPD_EVT, XI2S_TX_AUD_UNDRFLW_EVT, XI2S_TX_INTR_AES_BLKCMPLT_MASK, XI2S_TX_INTR_AES_BLKSYNCERR_MASK, XI2S_TX_INTR_AES_CHSTSUPD_MASK, XI2S_TX_INTR_AUDUNDRFLW_MASK, XI2S_TX_IRQCTRL_OFFSET, XI2S_TX_IRQSTS_OFFSET, XI2s_Tx_LogWrite, XI2s_Tx_ReadReg.
int XI2s_Tx_SetHandler(XI2s_Tx *InstancePtr, XI2s_Tx_HandlerType HandlerType, XI2s_Tx_Callback FuncPtr, void *CallbackRef)
This function installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function -------------------------------- ------------------------- (XI2S_TX_HANDLER_AES_BLKCMPLT) AesBlkCmpltHandler (XI2S_TX_HANDLER_AES_BLKSYNCERR) AesBlkSyncErrHandler (XI2S_TX_HANDLER_AES_CHSTSUPD) AesChStsUpdHandler (XI2S_TX_HANDLER_AUD_UNDRFLW) AudUndrflwHandler InstancePtr is a pointer to the XI2s_Tx core instance. HandlerType specifies the type of handler. FuncPtr is a pointer to the callback function. CallbackRef is a reference pointer passed on actual calling of the callback function. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XI2s_Tx::AesBlkCmpltHandler, XI2s_Tx::AesBlkSyncErrHandler, XI2s_Tx::AudUndrflwHandler, XI2S_TX_HANDLER_AES_BLKCMPLT, XI2S_TX_HANDLER_AES_BLKSYNCERR, XI2S_TX_HANDLER_AES_CHSTSUPD, XI2S_TX_HANDLER_AUD_UNDRFLW, XI2S_TX_NUM_HANDLERS.
void XI2s_Tx_LogDisplay(XI2s_Tx *InstancePtr)
This function prints the contents of the logging buffer.
InstancePtr is a pointer to the XI2s_Tx instance. None.
References XI2stx_Config::BaseAddress, XI2s_Tx::Config, XI2s_Tx_LogItem::Event, XI2S_TX_AES_BLKCMPLT_EVT, XI2S_TX_AES_BLKSYNCERR_EVT, XI2S_TX_AES_CHSTSUPD_EVT, XI2S_TX_AUD_UNDRFLW_EVT, XI2S_TX_LOG_EVT_INVALID, XI2s_Tx_LogRead.
void XI2s_Tx_LogWrite(XI2s_Tx *InstancePtr, XI2s_Tx_LogEvt Event, u8 Data)
This function writes I2S Transmitter logs into the buffer.
InstancePtr is a pointer to the XI2s_Tx instance. Event is the log event type. Data is the log data. Log write can be done only if the log is enabled.
References XI2s_Tx_LogItem::Data, XI2s_Tx_LogItem::Event, XI2s_Tx_Log::Head, XI2s_Tx_Log::IsEnabled, XI2s_Tx_Log::Items, XI2s_Tx::Log, XI2s_Tx_Log::Tail, XI2S_TX_LOG_EVT_INVALID.
Referenced by XI2s_Tx_IntrHandler.
XI2s_Tx_LogItem * XI2s_Tx_LogRead(XI2s_Tx *InstancePtr)
This function returns the next item in the logging buffer.
InstancePtr is a pointer to the XI2s_Tx instance. When the buffer is filled, the next log item is returned. When the buffer is empty, NULL is returned. None.
References XI2s_Tx_Log::Head, XI2s_Tx_Log::Items, XI2s_Tx::Log, XI2s_Tx_Log::Tail.
Referenced by XI2s_Tx_LogDisplay.
void XI2s_Tx_LogReset(XI2s_Tx *InstancePtr)
This function clears the contents of the logging buffer.
InstancePtr is a pointer to the XI2s_Tx instance. None.
References XI2s_Tx_Log::Head, XI2s_Tx_Log::IsEnabled, XI2s_Tx::Log, XI2s_Tx_Log::Tail.
void XI2s_Tx_ReslveAesChStat(u8 I2stx_SrcBuf[])
This function reads the array I2stx_SrcBuf which has the values of all the I2S Transmitter AES status registers, extracts the required bits and prints them.
Before calling this API, Call API XI2s_Tx_GetAesChStatus. I2stx_SrcBuf is an array that contains the values of all the the AES Status registers.
References XI2S_TX_AES_STS_AUDIO_SIG_PRE_EMPH_MASK, XI2S_TX_AES_STS_AUDIO_SIG_PRE_EMPH_SHIFT, XI2S_TX_AES_STS_CH_MODE_MASK, XI2S_TX_AES_STS_CH_NUM0_MASK, XI2S_TX_AES_STS_CH_NUM1_MASK, XI2S_TX_AES_STS_CRC_CHAR_OFFSET, XI2S_TX_AES_STS_DIGITAL_AUDIO_REF_SIG_MASK, XI2S_TX_AES_STS_DIGITAL_AUDIO_REF_SIG_SHIFT, XI2S_TX_AES_STS_INDICATE_ALIGN_LEVEL_MASK, XI2S_TX_AES_STS_INDICATE_ALIGN_LEVEL_SHIFT, XI2S_TX_AES_STS_LINEAR_PCM_ID_MASK, XI2S_TX_AES_STS_LINEAR_PCM_ID_SHIFT, XI2S_TX_AES_STS_LOCK_INDICATION_MASK, XI2S_TX_AES_STS_LOCK_INDICATION_SHIFT, XI2S_TX_AES_STS_MC_CH_MODE_MASK, XI2S_TX_AES_STS_MC_CH_MODE_NUM_MASK, XI2S_TX_AES_STS_MC_CH_MODE_NUM_SHIFT, XI2S_TX_AES_STS_MC_CH_MODE_SHIFT, XI2S_TX_AES_STS_RELIABLE_FLAGS_OFFSET, XI2S_TX_AES_STS_RSVD_BUT_UNDEF0_MASK, XI2S_TX_AES_STS_RSVD_BUT_UNDEF0_SHIFT, XI2S_TX_AES_STS_RSVD_BUT_UNDEF1_MASK, XI2S_TX_AES_STS_SAMPLING_FREQ_E_MASK, XI2S_TX_AES_STS_SAMPLING_FREQ_E_SHIFT, XI2S_TX_AES_STS_SAMPLING_FREQ_Q_MASK, XI2S_TX_AES_STS_SAMPLING_FREQ_Q_SHIFT, XI2S_TX_AES_STS_SAMPLING_FREQ_SCALE_FLAG_MASK, XI2S_TX_AES_STS_SAMPLING_FREQ_SCALE_FLAG_SHIFT, XI2S_TX_AES_STS_SRC_WORD_LENGTH_MASK, XI2S_TX_AES_STS_SRC_WORD_LENGTH_SHIFT, XI2S_TX_AES_STS_USE_OF_CH_STS_BLK_MASK, XI2S_TX_AES_STS_USEOF_AUX_SMPL_BITS_MASK, XI2S_TX_AES_STS_USR_BITS_MGMT_MASK, XI2S_TX_AES_STS_USR_BITS_MGMT_SHIFT.
static u32 XI2s_Tx_GetXI2sDataWidth(XI2s_Tx *InstancePtr)
This macro returns the I2S data width.
InstancePtr is a pointer to the XI2s_Tx core instance. The I2s data width in number of bits C-style signature: u8 XI2s_Tx_GetI2sDataWidth(XI2s_Tx *InstancePtr)
XI2S_TX_CLK_MASK
XI2S_TX_CORE_VER
XI2s_Tx_GetMaxChannels
This macro reads the maximum number of I2S channels available.
InstancePtr is a pointer to the XI2s_Tx core instance. Maximum number of I2S Channels. C-style signature: u32 XI2s_Tx_GetMaxChannels(XI2s_Tx *InstancePtr)
Referenced by XI2s_Tx_SelfTest.
XI2s_Tx_IsI2sMaster
This macro returns the I2S operating mode.
InstancePtr is a pointer to the XI2s_Tx core instance. TRUE : is I2S MasterFALSE : is I2S Slave C-style signature: u8 XI2s_Tx_IsI2sMaster(XI2s_Tx *InstancePtr)
Referenced by XI2s_Tx_SelfTest.