xhdmiphy1
XHDMIPHY1_VERSION_REG
Version register.
Referenced by XHdmiphy1_GetVersion.
XHDMIPHY1_BANK_SELECT_REG
Bank select register.
XHDMIPHY1_REF_CLK_SEL_REG
Reference clock select register.
Referenced by XHdmiphy1_GetSysClkDataSel, XHdmiphy1_GetSysClkOutSel, XHdmiphy1_WriteCfgRefClkSelReg.
XHDMIPHY1_PLL_RESET_REG
PLL reset register.
XHDMIPHY1_COMMON_INIT_REG
Common initialization register.
XHDMIPHY1_PLL_LOCK_STATUS_REG
PLL lock status register.
Referenced by XHdmiphy1_IsPllLocked.
XHDMIPHY1_TX_INIT_REG
Transmitter initialization register.
Referenced by XHdmiphy1_GtUserRdyEnable, XHdmiphy1_HdmiGtTxResetDoneLockHandler, XHdmiphy1_HdmiTxClkDetFreqChangeHandler, XHdmiphy1_ResetGtPll, XHdmiphy1_ResetGtTxRx.
XHDMIPHY1_TX_INIT_STATUS_REG
Transmitter initialization status register.
XHDMIPHY1_RX_INIT_REG
Receiver initialization register.
Referenced by XHdmiphy1_GtUserRdyEnable, XHdmiphy1_HdmiGtRxResetDoneLockHandler, XHdmiphy1_HdmiRxClkDetFreqChangeHandler, XHdmiphy1_ResetGtPll, XHdmiphy1_ResetGtTxRx.
XHDMIPHY1_RX_INIT_STATUS_REG
Receiver initialization status register.
XHDMIPHY1_IBUFDS_GTXX_CTRL_REG
IBUFDS GT control register.
Referenced by XHdmiphy1_IBufDsEnable.
XHDMIPHY1_POWERDOWN_CONTROL_REG
Power down control register.
Referenced by XHdmiphy1_PowerDownGtPll.
XHDMIPHY1_LOOPBACK_CONTROL_REG
Loopback control register.
XHDMIPHY1_DRP_CONTROL_CH1_REG
DRP control register for channel 1 (0x040)
XHDMIPHY1_DRP_CONTROL_CH2_REG
DRP control register for channel 2 (0x044)
XHDMIPHY1_DRP_CONTROL_CH3_REG
DRP control register for channel 3 (0x048)
XHDMIPHY1_DRP_CONTROL_CH4_REG
DRP control register for channel 4 (0x04C)
XHDMIPHY1_DRP_STATUS_CH1_REG
DRP status register for channel 1 (0x050)
XHDMIPHY1_DRP_STATUS_CH2_REG
DRP status register for channel 2 (0x054)
XHDMIPHY1_DRP_STATUS_CH3_REG
DRP status register for channel 3 (0x058)
XHDMIPHY1_DRP_STATUS_CH4_REG
DRP status register for channel 4 (0x05C)
XHDMIPHY1_DRP_CONTROL_COMMON_REG
DRP control register for common (0x060)
XHDMIPHY1_DRP_STATUS_COMMON_REG
DRP status register for common (0x064)
XHDMIPHY1_DRP_CONTROL_TXMMCM_REG
DRP control register for TX MMCM (0x124)
XHDMIPHY1_DRP_STATUS_TXMMCM_REG
DRP status register for TX MMCM (0x128)
XHDMIPHY1_DRP_CONTROL_RXMMCM_REG
DRP control register for RX MMCM (0x144)
XHDMIPHY1_DRP_STATUS_RXMMCM_REG
DRP status register for RX MMCM (0x148)
XHDMIPHY1_CPLL_CAL_PERIOD_REG
CPLL calibration period register (0x068)
XHDMIPHY1_CPLL_CAL_TOL_REG
CPLL calibration tolerance register (0x06C)
XHDMIPHY1_GT_DBG_GPI_REG
GT debug GPI register (0x068)
XHDMIPHY1_GT_DBG_GPO_REG
GT debug GPO register (0x06C)
XHDMIPHY1_TX_CONTROL_REG
TX control register (0x070)
Referenced by XHdmiphy1_SetPolarity, XHdmiphy1_SetPrbsSel, XHdmiphy1_TxPrbsForceError.
XHDMIPHY1_TX_BUFFER_BYPASS_REG
TX buffer bypass register (0x074)
Referenced by XHdmiphy1_TxAlignReset, XHdmiphy1_TxAlignStart.
XHDMIPHY1_TX_STATUS_REG
TX status register (0x078)
XHDMIPHY1_TX_DRIVER_CH12_REG
TX driver register for channels 1 and 2 (0x07C)
Referenced by XHdmiphy1_SetTxPostCursor, XHdmiphy1_SetTxPreEmphasis, XHdmiphy1_SetTxVoltageSwing.
XHDMIPHY1_TX_DRIVER_CH34_REG
TX driver register for channels 3 and 4 (0x080)
Referenced by XHdmiphy1_SetTxPostCursor, XHdmiphy1_SetTxPreEmphasis, XHdmiphy1_SetTxVoltageSwing.
XHDMIPHY1_TX_DRIVER_EXT_REG
TX driver extended register (0x084)
Referenced by XHdmiphy1_SetTxVoltageSwing.
XHDMIPHY1_TX_RATE_CH12_REG
TX rate register for channels 1 and 2 (0x08C)
XHDMIPHY1_TX_RATE_CH34_REG
TX rate register for channels 3 and 4 (0x090)
XHDMIPHY1_RX_RATE_CH12_REG
RX rate register for channels 1 and 2 (0x98)
XHDMIPHY1_RX_RATE_CH34_REG
RX rate register for channels 3 and 4 (0x9C)
XHDMIPHY1_RX_CONTROL_REG
RX control register (0x100)
Referenced by XHdmiphy1_SetPolarity, XHdmiphy1_SetPrbsSel.
XHDMIPHY1_RX_STATUS_REG
RX status register (0x104)
XHDMIPHY1_RX_EQ_CDR_REG
RX equalization and CDR register (0x108)
Referenced by XHdmiphy1_HdmiGtDruModeEnable, XHdmiphy1_SetRxLpm.
XHDMIPHY1_RX_TDLOCK_REG
RX TDLOCK register (0x10C)
XHDMIPHY1_INTR_EN_REG
Interrupt enable register (0x110)
Referenced by XHdmiphy1_IntrEnable.
XHDMIPHY1_INTR_DIS_REG
Interrupt disable register (0x114)
Referenced by XHdmiphy1_IntrDisable.
XHDMIPHY1_INTR_MASK_REG
Interrupt mask register (0x118)
XHDMIPHY1_INTR_STS_REG
Interrupt status register (0x11C)
Referenced by XHdmiphy1_Hdmi_CfgInitialize, XHdmiphy1_InterruptHandler.
XHDMIPHY1_MMCM_TXUSRCLK_CTRL_REG
MMCM TX user clock control register (0x0120)
Referenced by XHdmiphy1_MmcmLocked, XHdmiphy1_MmcmLockedMaskEnable, XHdmiphy1_MmcmPowerDown, XHdmiphy1_MmcmReset, XHdmiphy1_MmcmSetClkinsel.
XHDMIPHY1_MMCM_TXUSRCLK_REG1
MMCM TX user clock register 1 (0x0124)
XHDMIPHY1_MMCM_TXUSRCLK_REG2
MMCM TX user clock register 2 (0x0128)
XHDMIPHY1_MMCM_TXUSRCLK_REG3
MMCM TX user clock register 3 (0x012C)
XHDMIPHY1_MMCM_TXUSRCLK_REG4
MMCM TX user clock register 4 (0x0130)
XHDMIPHY1_BUFGGT_TXUSRCLK_REG
BUFGGT TX user clock register (0x0134)
Referenced by XHdmiphy1_SetBufgGtDiv.
XHDMIPHY1_MISC_TXUSRCLK_REG
Miscellaneous TX user clock register (0x0138)
Referenced by XHdmiphy1_Clkout1OBufTdsEnable, XHdmiphy1_IBufDsEnable.
XHDMIPHY1_MMCM_RXUSRCLK_CTRL_REG
MMCM RX user clock control register (0x0140)
Referenced by XHdmiphy1_MmcmLocked, XHdmiphy1_MmcmLockedMaskEnable, XHdmiphy1_MmcmPowerDown, XHdmiphy1_MmcmReset, XHdmiphy1_MmcmSetClkinsel.
XHDMIPHY1_MMCM_RXUSRCLK_REG1
MMCM RX user clock register 1 (0x0144)
XHDMIPHY1_MMCM_RXUSRCLK_REG2
MMCM RX user clock register 2 (0x0148)
XHDMIPHY1_MMCM_RXUSRCLK_REG3
MMCM RX user clock register 3 (0x014C)
XHDMIPHY1_MMCM_RXUSRCLK_REG4
MMCM RX user clock register 4 (0x0150)
XHDMIPHY1_BUFGGT_RXUSRCLK_REG
BUFGGT RX user clock register (0x0154)
Referenced by XHdmiphy1_SetBufgGtDiv.
XHDMIPHY1_MISC_RXUSRCLK_REG
Miscellaneous RX user clock register (0x0158)
Referenced by XHdmiphy1_Clkout1OBufTdsEnable, XHdmiphy1_IBufDsEnable.
XHDMIPHY1_CLKDET_CTRL_REG
Clock detector control register (0x0200)
Referenced by XHdmiphy1_ClkDetAccuracyRange, XHdmiphy1_ClkDetEnable, XHdmiphy1_ClkDetFreqReset, XHdmiphy1_ClkDetSetFreqLockThreshold, XHdmiphy1_ClkDetTimerClear.
XHDMIPHY1_CLKDET_STAT_REG
Clock detector status register (0x0204)
XHDMIPHY1_CLKDET_FREQ_TMR_TO_REG
Clock detector frequency timer timeout register (0x0208)
Referenced by XHdmiphy1_ClkDetSetFreqTimeout.
XHDMIPHY1_CLKDET_FREQ_TX_REG
Clock detector TX frequency register (0x020C)
Referenced by XHdmiphy1_ClkDetGetRefClkFreqHz.
XHDMIPHY1_CLKDET_FREQ_RX_REG
Clock detector RX frequency register (0x0210)
Referenced by XHdmiphy1_ClkDetGetRefClkFreqHz.
XHDMIPHY1_CLKDET_TMR_TX_REG
Clock detector TX timer register (0x0214)
Referenced by XHdmiphy1_ClkDetTimerLoad.
XHDMIPHY1_CLKDET_TMR_RX_REG
Clock detector RX timer register (0x0218)
Referenced by XHdmiphy1_ClkDetTimerLoad.
XHDMIPHY1_CLKDET_FREQ_DRU_REG
Clock detector DRU frequency register (0x021C)
Referenced by XHdmiphy1_DruGetRefClkFreqHz.
XHDMIPHY1_CLKDET_FREQ_TX_RAW_REG
Clock detector TX raw frequency register (0x0220)
Referenced by XHdmiphy1_ClkDetGetRefClkFreqHzRaw.
XHDMIPHY1_CLKDET_FREQ_RX_RAW_REG
Clock detector RX raw frequency register (0x0224)
Referenced by XHdmiphy1_ClkDetGetRefClkFreqHzRaw.
XHDMIPHY1_CLKDET_FREQ_DRU_RAW_REG
Clock detector DRU raw frequency register (0x0228)
Referenced by XHdmiphy1_DruGetRefClkFreqHzRaw.
XHDMIPHY1_CLKDET_FREQ_TX_FRL_REG
Clock detector TX FRL frequency register (0x0230)
Referenced by XHdmiphy1_ClkDetGetRefClkFreqHz.
XHDMIPHY1_CLKDET_FREQ_RX_FRL_REG
Clock detector RX FRL frequency register (0x0234)
Referenced by XHdmiphy1_ClkDetGetRefClkFreqHz.
XHDMIPHY1_DRU_CTRL_REG
DRU control register (0x0300)
Referenced by XHdmiphy1_DruEnable, XHdmiphy1_DruReset.
XHDMIPHY1_DRU_STAT_REG
DRU status register (0x0304)
Referenced by XHdmiphy1_ClkDetCheckFreqZero, XHdmiphy1_DruGetVersion.
XHDMIPHY1_DRU_CFREQ_L_REG
DRU Center Frequency Lower register address calculation.
Ch Channel number (1-4). Register address for the specified channel.
Referenced by XHdmiphy1_DruSetCenterFreqHz, XHdmiphy1_HdmiDebugInfo.
XHDMIPHY1_DRU_CFREQ_H_REG
DRU Center Frequency Higher register address calculation.
Ch Channel number (1-4). Register address for the specified channel.
Referenced by XHdmiphy1_DruSetCenterFreqHz, XHdmiphy1_HdmiDebugInfo.
XHDMIPHY1_DRU_GAIN_REG
DRU Gain register address calculation.
Ch Channel number (1-4). Register address for the specified channel.
Referenced by XHdmiphy1_HdmiDebugInfo.
XHDMIPHY1_PATGEN_CTRL_REG
PATGEN control register (0x0340)
Referenced by XHdmiphy1_PatgenEnable, XHdmiphy1_PatgenSetRatio.
XHDMIPHY1_VERSION_INTER_REV_MASK
Internal revision.
XHDMIPHY1_VERSION_CORE_PATCH_MASK
Core patch details.
XHDMIPHY1_VERSION_CORE_PATCH_SHIFT
Shift bits for core patch details.
XHDMIPHY1_VERSION_CORE_VER_REV_MASK
Core version revision.
XHDMIPHY1_VERSION_CORE_VER_REV_SHIFT
Shift bits for core version revision.
XHDMIPHY1_VERSION_CORE_VER_MNR_MASK
Core minor version.
XHDMIPHY1_VERSION_CORE_VER_MNR_SHIFT
Shift bits for core minor version.
XHDMIPHY1_VERSION_CORE_VER_MJR_MASK
Core major version.
XHDMIPHY1_VERSION_CORE_VER_MJR_SHIFT
Shift bits for core major version.
XHDMIPHY1_BANK_SELECT_TX_MASK
TX bank select mask (0x00F)
XHDMIPHY1_BANK_SELECT_RX_MASK
RX bank select mask (0xF00)
XHDMIPHY1_BANK_SELECT_RX_SHIFT
RX bank select shift (8)
XHDMIPHY1_REF_CLK_SEL_QPLL0_MASK
QPLL0 reference clock select mask (0x0000000F)
Referenced by XHdmiphy1_WriteCfgRefClkSelReg.
XHDMIPHY1_REF_CLK_SEL_CPLL_MASK
CPLL reference clock select mask (0x000000F0)
Referenced by XHdmiphy1_WriteCfgRefClkSelReg.
XHDMIPHY1_REF_CLK_SEL_CPLL_SHIFT
CPLL reference clock select shift (4)
Referenced by XHdmiphy1_WriteCfgRefClkSelReg.
XHDMIPHY1_REF_CLK_SEL_QPLL1_MASK
QPLL1 reference clock select mask (0x00000F00)
Referenced by XHdmiphy1_WriteCfgRefClkSelReg.
XHDMIPHY1_REF_CLK_SEL_QPLL1_SHIFT
QPLL1 reference clock select shift (8)
Referenced by XHdmiphy1_WriteCfgRefClkSelReg.
XHDMIPHY1_REF_CLK_SEL_XPLL_GTREFCLK0
GT reference clock 0 selection value (1)
XHDMIPHY1_REF_CLK_SEL_XPLL_GTREFCLK1
GT reference clock 1 selection value (2)
XHDMIPHY1_REF_CLK_SEL_XPLL_GTNORTHREFCLK0
GT north reference clock 0 selection value (3)
XHDMIPHY1_REF_CLK_SEL_XPLL_GTNORTHREFCLK1
GT north reference clock 1 selection value (4)
XHDMIPHY1_REF_CLK_SEL_XPLL_GTSOUTHREFCLK0
GT south reference clock 0 selection value (5)
XHDMIPHY1_REF_CLK_SEL_XPLL_GTSOUTHREFCLK1
GT south reference clock 1 selection value (6)
XHDMIPHY1_REF_CLK_SEL_XPLL_GTEASTREFCLK0
GT east reference clock 0 selection value (3)
XHDMIPHY1_REF_CLK_SEL_XPLL_GTEASTREFCLK1
GT east reference clock 1 selection value (4)
XHDMIPHY1_REF_CLK_SEL_XPLL_GTWESTREFCLK0
GT west reference clock 0 selection value (5)
XHDMIPHY1_REF_CLK_SEL_XPLL_GTWESTREFCLK1
GT west reference clock 1 selection value (6)
XHDMIPHY1_REF_CLK_SEL_XPLL_GTGREFCLK
GT global reference clock selection value (7)
XHDMIPHY1_REF_CLK_SEL_SYSCLKSEL_MASK
System clock select mask (0x0F000000)
Referenced by XHdmiphy1_WriteCfgRefClkSelReg.
XHDMIPHY1_REF_CLK_SEL_SYSCLKSEL_SHIFT
System clock select shift (24)
XHDMIPHY1_REF_CLK_SEL_XXSYSCLKSEL_DATA_PLL0
System clock data PLL0 selection value (0)
XHDMIPHY1_REF_CLK_SEL_XXSYSCLKSEL_DATA_PLL1
System clock data PLL1 selection value (1)
XHDMIPHY1_REF_CLK_SEL_XXSYSCLKSEL_DATA_CPLL
System clock data CPLL selection value (0)
XHDMIPHY1_REF_CLK_SEL_XXSYSCLKSEL_DATA_QPLL
System clock data QPLL selection value (1)
XHDMIPHY1_REF_CLK_SEL_XXSYSCLKSEL_DATA_QPLL0
System clock data QPLL0 selection value (3)
XHDMIPHY1_REF_CLK_SEL_XXSYSCLKSEL_DATA_QPLL1
System clock data QPLL1 selection value (2)
XHDMIPHY1_REF_CLK_SEL_XXSYSCLKSEL_OUT_CH
System clock output channel selection value (0)
XHDMIPHY1_REF_CLK_SEL_XXSYSCLKSEL_OUT_CMN
System clock output common selection value (1)
XHDMIPHY1_REF_CLK_SEL_XXSYSCLKSEL_OUT_CMN0
System clock output common 0 selection value (2)
XHDMIPHY1_REF_CLK_SEL_XXSYSCLKSEL_OUT_CMN1
System clock output common 1 selection value (3)
XHDMIPHY1_REF_CLK_SEL_RXSYSCLKSEL_OUT_MASK
RX System Clock Select Output mask based on GT type.
G GT type (GTHE4, GTYE4, GTYE5, GTYP). Mask value for the specified GT type.
Referenced by XHdmiphy1_GetSysClkOutSel, XHdmiphy1_WriteCfgRefClkSelReg.
XHDMIPHY1_REF_CLK_SEL_TXSYSCLKSEL_OUT_MASK
TX System Clock Select Output mask based on GT type.
G GT type (GTHE4, GTYE4, GTYE5, GTYP). Mask value for the specified GT type.
Referenced by XHdmiphy1_GetSysClkOutSel, XHdmiphy1_WriteCfgRefClkSelReg.
XHDMIPHY1_REF_CLK_SEL_RXSYSCLKSEL_DATA_MASK
RX System Clock Select Data mask based on GT type.
G GT type (GTHE4, GTYE4, GTYE5, GTYP). Mask value for the specified GT type.
Referenced by XHdmiphy1_GetSysClkDataSel, XHdmiphy1_WriteCfgRefClkSelReg.
XHDMIPHY1_REF_CLK_SEL_TXSYSCLKSEL_DATA_MASK
TX System Clock Select Data mask based on GT type.
G GT type (GTHE4, GTYE4, GTYE5, GTYP). Mask value for the specified GT type.
Referenced by XHdmiphy1_GetSysClkDataSel, XHdmiphy1_WriteCfgRefClkSelReg.
XHDMIPHY1_REF_CLK_SEL_RXSYSCLKSEL_OUT_SHIFT
RX System Clock Select Output shift based on GT type.
G GT type (GTHE4, GTYE4, GTYE5, GTYP). Shift value for the specified GT type.
Referenced by XHdmiphy1_GetSysClkOutSel, XHdmiphy1_WriteCfgRefClkSelReg.
XHDMIPHY1_REF_CLK_SEL_TXSYSCLKSEL_OUT_SHIFT
TX System Clock Select Output shift based on GT type.
G GT type (GTHE4, GTYE4, GTYE5, GTYP). Shift value for the specified GT type.
Referenced by XHdmiphy1_GetSysClkOutSel, XHdmiphy1_WriteCfgRefClkSelReg.
XHDMIPHY1_REF_CLK_SEL_RXSYSCLKSEL_DATA_SHIFT
RX System Clock Select Data shift based on GT type.
G GT type (GTHE4, GTYE4, GTYE5, GTYP). Shift value for the specified GT type.
Referenced by XHdmiphy1_GetSysClkDataSel, XHdmiphy1_WriteCfgRefClkSelReg.
XHDMIPHY1_REF_CLK_SEL_TXSYSCLKSEL_DATA_SHIFT
TX System Clock Select Data shift based on GT type.
G GT type (GTHE4, GTYE4, GTYE5, GTYP). Shift value for the specified GT type.
Referenced by XHdmiphy1_GetSysClkDataSel, XHdmiphy1_WriteCfgRefClkSelReg.
XHDMIPHY1_PLL_RESET_CPLL_MASK
CPLL reset mask (0x1)
XHDMIPHY1_PLL_RESET_QPLL0_MASK
QPLL0 reset mask (0x2)
XHDMIPHY1_PLL_RESET_QPLL1_MASK
QPLL1 reset mask (0x4)
XHDMIPHY1_GTWIZ_RESET_ALL_MASK
GT wizard reset all mask (0x1)
XHDMIPHY1_PCIERST_ALL_CH_MASK
PCIe reset all channels mask (0x2)
XHDMIPHY1_PLL_LOCK_STATUS_CPLL_MASK
CPLL lock status mask for specific channel.
Ch Channel number (1-4). Lock status mask for the specified channel.
Referenced by XHdmiphy1_IsPllLocked.
XHDMIPHY1_PLL_LOCK_STATUS_QPLL0_MASK
QPLL0 lock status mask (0x10)
Referenced by XHdmiphy1_IsPllLocked.
XHDMIPHY1_PLL_LOCK_STATUS_QPLL1_MASK
QPLL1 lock status mask (0x20)
Referenced by XHdmiphy1_IsPllLocked.
XHDMIPHY1_PLL_LOCK_STATUS_CPLL_ALL_MASK
CPLL lock status mask for all channels.
Referenced by XHdmiphy1_IsPllLocked.
XHDMIPHY1_PLL_LOCK_STATUS_CPLL_HDMI_MASK
CPLL lock status mask for HDMI channels (1-3)
Referenced by XHdmiphy1_IsPllLocked.
XHDMIPHY1_PLL_LOCK_STATUS_RPLL_MASK
RPLL lock status mask (0xC0)
Referenced by XHdmiphy1_IsPllLocked.
XHDMIPHY1_PLL_LOCK_STATUS_LCPLL_MASK
LCPLL lock status mask (0x300)
Referenced by XHdmiphy1_IsPllLocked.
XHDMIPHY1_TXRX_INIT_GTRESET_MASK
GT reset mask for specific channel.
Ch Channel number (1-4). GT reset mask for the specified channel.
Referenced by XHdmiphy1_ResetGtTxRx.
XHDMIPHY1_TXRX_INIT_PMARESET_MASK
PMA reset mask for specific channel.
Ch Channel number (1-4). PMA reset mask for the specified channel.
XHDMIPHY1_TXRX_INIT_PCSRESET_MASK
PCS reset mask for specific channel.
Ch Channel number (1-4). PCS reset mask for the specified channel.
XHDMIPHY1_TX_INIT_USERRDY_MASK
TX user ready mask for specific channel.
Ch Channel number (1-4). TX user ready mask for the specified channel.
Referenced by XHdmiphy1_GtUserRdyEnable.
XHDMIPHY1_TXRX_LNKRDY_SB_MASK
Link ready sideband mask for specific channel.
Ch Channel number (1-4). Link ready sideband mask for the specified channel.
XHDMIPHY1_TXRX_MSTRESET_MASK
Master reset mask for specific channel.
Ch Channel number (1-4). Master reset mask for the specified channel.
XHDMIPHY1_RX_INIT_USERRDY_MASK
RX user ready mask for specific channel.
Ch Channel number (1-4). RX user ready mask for the specified channel.
Referenced by XHdmiphy1_GtUserRdyEnable.
XHDMIPHY1_TXRX_INIT_PLLGTRESET_MASK
PLL GT reset mask for specific channel.
Ch Channel number (1-4). PLL GT reset mask for the specified channel.
Referenced by XHdmiphy1_ResetGtPll.
XHDMIPHY1_TXRX_INIT_GTRESET_ALL_MASK
GT reset mask for all channels.
Referenced by XHdmiphy1_ResetGtTxRx.
XHDMIPHY1_TXRX_LNKRDY_SB_ALL_MASK
Link ready sideband mask for all channels.
XHDMIPHY1_TXRX_MSTRESET_ALL_MASK
Master reset mask for all channels.
XHDMIPHY1_TX_INIT_USERRDY_ALL_MASK
TX User Ready initialization mask for all channels.
Referenced by XHdmiphy1_GtUserRdyEnable.
XHDMIPHY1_RX_INIT_USERRDY_ALL_MASK
RX User Ready initialization mask for all channels.
Referenced by XHdmiphy1_GtUserRdyEnable.
XHDMIPHY1_TXRX_INIT_PLLGTRESET_ALL_MASK
TX/RX PLL GT reset initialization mask for all channels.
Referenced by XHdmiphy1_ResetGtPll.
XHDMIPHY1_TXRX_INIT_STATUS_RESETDONE_MASK
TX/RX initialization status reset done mask for specific channel.
Ch Channel number (1-4). Reset done status mask for the specified channel.
XHDMIPHY1_TXRX_INIT_STATUS_PMARESETDONE_MASK
TX/RX initialization status PMA reset done mask for specific channel.
Ch Channel number (1-4). PMA reset done status mask for the specified channel.
XHDMIPHY1_TXRX_INIT_STATUS_POWERGOOD_MASK
TX/RX initialization status power good mask for specific channel.
Ch Channel number (1-4). Power good status mask for the specified channel.
XHDMIPHY1_TXRX_INIT_STATUS_RESETDONE_ALL_MASK
TX/RX initialization status reset done mask for all channels.
XHDMIPHY1_TXRX_INIT_STATUS_PMARESETDONE_ALL_MASK
TX/RX initialization status PMA reset done mask for all channels.
XHDMIPHY1_IBUFDS_GTXX_CTRL_GTREFCLK0_CEB_MASK
IBUFDS GT reference clock 0 CEB (Clock Enable Bar) control mask.
Referenced by XHdmiphy1_IBufDsEnable.
XHDMIPHY1_IBUFDS_GTXX_CTRL_GTREFCLK1_CEB_MASK
IBUFDS GT reference clock 1 CEB (Clock Enable Bar) control mask.
Referenced by XHdmiphy1_IBufDsEnable.
XHDMIPHY1_POWERDOWN_CONTROL_CPLLPD_MASK
CPLL power down mask for specific channel.
Ch Channel number (1-4). CPLL power down mask for the specified channel.
Referenced by XHdmiphy1_PowerDownGtPll.
XHDMIPHY1_POWERDOWN_CONTROL_QPLL0PD_MASK
QPLL0 power down mask for specific channel.
Ch Channel number (1-4). QPLL0 power down mask for the specified channel.
Referenced by XHdmiphy1_PowerDownGtPll.
XHDMIPHY1_POWERDOWN_CONTROL_QPLL1PD_MASK
QPLL1 power down mask for specific channel.
Ch Channel number (1-4). QPLL1 power down mask for the specified channel.
Referenced by XHdmiphy1_PowerDownGtPll.
XHDMIPHY1_POWERDOWN_CONTROL_RXPD_MASK
RX power down mask for specific channel.
Ch Channel number (1-4). RX power down mask for the specified channel.
XHDMIPHY1_POWERDOWN_CONTROL_RXPD_SHIFT
RX power down shift for specific channel.
Ch Channel number (1-4). RX power down shift for the specified channel.
XHDMIPHY1_POWERDOWN_CONTROL_TXPD_MASK
TX power down mask for specific channel.
Ch Channel number (1-4). TX power down mask for the specified channel.
XHDMIPHY1_POWERDOWN_CONTROL_TXPD_SHIFT
TX power down shift for specific channel.
Ch Channel number (1-4). TX power down shift for the specified channel.
XHDMIPHY1_LOOPBACK_CONTROL_CH_MASK
Loopback control channel mask for specific channel.
Ch Channel number (1-4). Loopback control mask for the specified channel.
XHDMIPHY1_LOOPBACK_CONTROL_CH_SHIFT
Loopback control channel shift for specific channel.
Ch Channel number (1-4). Loopback control shift for the specified channel.
XHDMIPHY1_DRP_CONTROL_DRPADDR_MASK
DRP control address mask.
XHDMIPHY1_DRP_CONTROL_DRPEN_MASK
DRP control enable mask.
XHDMIPHY1_DRP_CONTROL_DRPWE_MASK
DRP control write enable mask.
XHDMIPHY1_DRP_CONTROL_DRPRESET_MASK
DRP control reset mask.
XHDMIPHY1_DRP_CONTROL_DRPDI_MASK
DRP control data input mask.
XHDMIPHY1_DRP_CONTROL_DRPDI_SHIFT
DRP control data input shift.
XHDMIPHY1_DRP_STATUS_DRPO_MASK
DRP status data output mask.
XHDMIPHY1_DRP_STATUS_DRPRDY_MASK
DRP status ready mask.
XHDMIPHY1_DRP_STATUS_DRPBUSY_MASK
DRP status busy mask.
XHDMIPHY1_CPLL_CAL_PERIOD_MASK
CPLL calibration period mask.
XHDMIPHY1_CPLL_CAL_TOL_MASK
CPLL calibration tolerance mask.
XHDMIPHY1_TX_GPI_MASK
TX GPI mask for specific channel.
Ch Channel number (1-4). TX GPI mask for the specified channel.
XHDMIPHY1_RX_GPI_MASK
RX GPI mask for specific channel.
Ch Channel number (1-4). RX GPI mask for the specified channel.
XHDMIPHY1_TX_GPO_MASK
TX GPO mask for specific channel.
Ch Channel number (1-4). TX GPO mask for the specified channel.
XHDMIPHY1_TX_GPO_MASK_ALL
TX GPO mask for all channels based on number of channels.
NCh Number of channels (3 or 4). TX GPO mask for all channels.
XHDMIPHY1_TX_GPO_SHIFT
TX GPO shift value.
TX GPO shift value.
XHDMIPHY1_RX_GPO_MASK
RX GPO mask for specific channel.
Ch Channel number (1-4). RX GPO mask for the specified channel.
XHDMIPHY1_RX_GPO_MASK_ALL
RX GPO mask for all channels based on number of channels.
NCh Number of channels (3 or 4). RX GPO mask for all channels.
XHDMIPHY1_RX_GPO_SHIFT
RX GPO bit shift offset.
XHDMIPHY1_TX_CONTROL_TX8B10BEN_MASK
TX 8B/10B enable mask for specific channel.
Ch Channel number (1-4). TX 8B/10B enable mask for the specified channel.
XHDMIPHY1_TX_CONTROL_TX8B10BEN_ALL_MASK
TX 8B/10B enable mask for all channels.
XHDMIPHY1_TX_CONTROL_TXPOLARITY_MASK
TX polarity mask for specific channel.
Ch Channel number (1-4). TX polarity mask for the specified channel.
Referenced by XHdmiphy1_SetPolarity.
XHDMIPHY1_TX_CONTROL_TXPOLARITY_ALL_MASK
TX polarity mask for all channels.
Referenced by XHdmiphy1_SetPolarity.
XHDMIPHY1_TX_CONTROL_TXPRBSSEL_MASK
TX PRBS select mask for specific channel.
Ch Channel number (1-4). TX PRBS select mask for the specified channel.
Referenced by XHdmiphy1_SetPrbsSel.
XHDMIPHY1_TX_CONTROL_TXPRBSSEL_ALL_MASK
TX PRBS select mask for all channels.
Referenced by XHdmiphy1_SetPrbsSel.
XHDMIPHY1_TX_CONTROL_TXPRBSSEL_SHIFT
TX PRBS select shift for specific channel.
Ch Channel number (1-4). TX PRBS select shift for the specified channel.
Referenced by XHdmiphy1_SetPrbsSel.
XHDMIPHY1_TX_CONTROL_TXPRBSFORCEERR_MASK
TX PRBS force error mask for specific channel.
Ch Channel number (1-4). TX PRBS force error mask for the specified channel.
Referenced by XHdmiphy1_TxPrbsForceError.
XHDMIPHY1_TX_CONTROL_TXPRBSFORCEERR_ALL_MASK
TX PRBS force error mask for all channels.
Referenced by XHdmiphy1_TxPrbsForceError.
XHDMIPHY1_TX_BUFFER_BYPASS_TXPHDLYRESET_MASK
TX phase delay reset mask for specific channel.
Ch Channel number (1-4). TX phase delay reset mask for the specified channel.
Referenced by XHdmiphy1_TxAlignReset.
XHDMIPHY1_TX_BUFFER_BYPASS_TXPHALIGN_MASK
TX phase align mask for specific channel.
Ch Channel number (1-4). TX phase align mask for the specified channel.
Referenced by XHdmiphy1_TxAlignStart.
XHDMIPHY1_TX_BUFFER_BYPASS_TXPHALIGNEN_MASK
TX phase align enable mask for specific channel.
Ch Channel number (1-4). TX phase align enable mask for the specified channel.
XHDMIPHY1_TX_BUFFER_BYPASS_TXPHDLYPD_MASK
TX phase delay power down mask for specific channel.
Ch Channel number (1-4). TX phase delay power down mask for the specified channel.
XHDMIPHY1_TX_BUFFER_BYPASS_TXPHINIT_MASK
TX phase initialize mask for specific channel.
Ch Channel number (1-4). TX phase initialize mask for the specified channel.
XHDMIPHY1_TX_BUFFER_BYPASS_TXDLYRESET_MASK
TX delay reset mask for specific channel.
Ch Channel number (1-4). TX delay reset mask for the specified channel.
XHDMIPHY1_TX_BUFFER_BYPASS_TXDLYBYPASS_MASK
TX delay bypass mask for specific channel.
Ch Channel number (1-4). TX delay bypass mask for the specified channel.
XHDMIPHY1_TX_BUFFER_BYPASS_TXDLYEN_MASK
TX delay enable mask for specific channel.
Ch Channel number (1-4). TX delay enable mask for the specified channel.
XHDMIPHY1_TX_STATUS_TXPHALIGNDONE_MASK
TX phase align done mask for specific channel.
Ch Channel number (1-4). TX phase align done mask for the specified channel.
XHDMIPHY1_TX_STATUS_TXPHINITDONE_MASK
TX phase initialize done mask for specific channel.
Ch Channel number (1-4). TX phase initialize done mask for the specified channel.
XHDMIPHY1_TX_STATUS_TXDLYRESETDONE_MASK
TX delay reset done mask for specific channel.
Ch Channel number (1-4). TX delay reset done mask for the specified channel.
XHDMIPHY1_TX_STATUS_TXBUFSTATUS_MASK
TX buffer status mask for specific channel.
Ch Channel number (1-4). TX buffer status mask for the specified channel.
XHDMIPHY1_TX_STATUS_TXBUFSTATUS_SHIFT
TX buffer status shift for specific channel.
Ch Channel number (1-4). TX buffer status shift for the specified channel.
XHDMIPHY1_TX_DRIVER_TXDIFFCTRL_MASK
TX differential control mask for specific channel.
Ch Channel number (1-4). TX differential control mask for the specified channel.
Referenced by XHdmiphy1_SetTxVoltageSwing.
XHDMIPHY1_TX_DRIVER_TXDIFFCTRL_SHIFT
TX differential control shift for specific channel.
Ch Channel number (1-4). TX differential control shift for the specified channel.
Referenced by XHdmiphy1_SetTxVoltageSwing.
XHDMIPHY1_TX_DRIVER_TXELECIDLE_MASK
TX electrical idle mask for specific channel.
Ch Channel number (1-4). TX electrical idle mask for the specified channel.
XHDMIPHY1_TX_DRIVER_TXELECIDLE_SHIFT
TX electrical idle shift for specific channel.
Ch Channel number (1-4). TX electrical idle shift for the specified channel.
XHDMIPHY1_TX_DRIVER_TXINHIBIT_MASK
TX inhibit mask for specific channel.
Ch Channel number (1-4). TX inhibit mask for the specified channel.
XHDMIPHY1_TX_DRIVER_TXINHIBIT_SHIFT
TX inhibit shift for specific channel.
Ch Channel number (1-4). TX inhibit shift for the specified channel.
XHDMIPHY1_TX_DRIVER_TXPOSTCURSOR_MASK
TX post-cursor mask for specific channel.
Ch Channel number (1-4). TX post-cursor mask for the specified channel.
Referenced by XHdmiphy1_SetTxPostCursor.
XHDMIPHY1_TX_DRIVER_TXPOSTCURSOR_SHIFT
TX post-cursor shift for specific channel.
Ch Channel number (1-4). TX post-cursor shift for the specified channel.
Referenced by XHdmiphy1_SetTxPostCursor.
XHDMIPHY1_TX_DRIVER_TXPRECURSOR_MASK
TX pre-cursor mask for specific channel.
Ch Channel number (1-4). TX pre-cursor mask for the specified channel.
Referenced by XHdmiphy1_SetTxPreEmphasis.
XHDMIPHY1_TX_DRIVER_TXPRECURSOR_SHIFT
TX pre-cursor shift for specific channel.
Ch Channel number (1-4). TX pre-cursor shift for the specified channel.
Referenced by XHdmiphy1_SetTxPreEmphasis.
XHDMIPHY1_TX_DRIVER_EXT_TXDIFFCTRL_MASK
TX extended differential control mask for specific channel.
Ch Channel number (1-4). TX extended differential control mask for the specified channel.
Referenced by XHdmiphy1_SetTxVoltageSwing.
XHDMIPHY1_TX_DRIVER_EXT_TXDIFFCTRL_SHIFT
TX extended differential control shift for specific channel.
Ch Channel number (1-4). TX extended differential control shift for the specified channel.
Referenced by XHdmiphy1_SetTxVoltageSwing.
XHDMIPHY1_TX_RATE_MASK
TX rate mask for specific channel.
Ch Channel number (1-4). TX rate mask for the specified channel.
XHDMIPHY1_TX_RATE_SHIFT
TX rate shift for specific channel.
Ch Channel number (1-4). TX rate shift for the specified channel.
XHDMIPHY1_RX_RATE_MASK
RX rate mask for specific channel.
Ch Channel number (1-4). RX rate mask for the specified channel.
XHDMIPHY1_RX_RATE_SHIFT
RX rate shift for specific channel.
Ch Channel number (1-4). RX rate shift for the specified channel.
XHDMIPHY1_RX_CONTROL_RX8B10BEN_MASK
RX 8B/10B enable mask for specific channel.
Ch Channel number (1-4). RX 8B/10B enable mask for the specified channel.
XHDMIPHY1_RX_CONTROL_RX8B10BEN_ALL_MASK
RX 8B/10B enable mask for all channels.
XHDMIPHY1_RX_CONTROL_RXPOLARITY_MASK
RX polarity mask for specific channel.
Ch Channel number (1-4). RX polarity mask for the specified channel.
Referenced by XHdmiphy1_SetPolarity.
XHDMIPHY1_RX_CONTROL_RXPOLARITY_ALL_MASK
RX polarity mask for all channels.
Referenced by XHdmiphy1_SetPolarity.
XHDMIPHY1_RX_CONTROL_RXPRBSCNTRESET_MASK
RX PRBS counter reset mask for specific channel.
Ch Channel number (1-4). RX PRBS counter reset mask for the specified channel.
XHDMIPHY1_RX_CONTROL_RXPRBSSEL_MASK
RX PRBS select mask for specific channel.
Ch Channel number (1-4). RX PRBS select mask for the specified channel.
Referenced by XHdmiphy1_SetPrbsSel.
XHDMIPHY1_RX_CONTROL_RXPRBSSEL_ALL_MASK
RX PRBS select mask for all channels.
Referenced by XHdmiphy1_SetPrbsSel.
XHDMIPHY1_RX_CONTROL_RXPRBSSEL_SHIFT
RX PRBS select shift for specific channel.
Ch Channel number (1-4). RX PRBS select shift for the specified channel.
Referenced by XHdmiphy1_SetPrbsSel.
XHDMIPHY1_RX_STATUS_RXCDRLOCK_MASK
RX CDR lock mask for specific channel.
Ch Channel number (1-4). RX CDR lock mask for the specified channel.
XHDMIPHY1_RX_STATUS_RXBUFSTATUS_MASK
RX buffer status mask for specific channel.
Ch Channel number (1-4). RX buffer status mask for the specified channel.
XHDMIPHY1_RX_STATUS_RXBUFSTATUS_SHIFT
RX buffer status shift for specific channel.
Ch Channel number (1-4). RX buffer status shift for the specified channel.
XHDMIPHY1_RX_CONTROL_RXLPMEN_MASK
RX LPM enable mask for specific channel.
Ch Channel number (1-4). RX LPM enable mask for the specified channel.
Referenced by XHdmiphy1_SetRxLpm.
XHDMIPHY1_RX_STATUS_RXCDRHOLD_MASK
RX CDR hold mask for specific channel.
Ch Channel number (1-4). RX CDR hold mask for the specified channel.
Referenced by XHdmiphy1_HdmiGtDruModeEnable.
XHDMIPHY1_RX_STATUS_RXOSOVRDEN_MASK
RX OS override enable mask for specific channel.
Ch Channel number (1-4). RX OS override enable mask for the specified channel.
Referenced by XHdmiphy1_HdmiGtDruModeEnable.
XHDMIPHY1_RX_STATUS_RXLPMLFKLOVRDEN_MASK
RX LPM LFK override enable mask for specific channel.
Ch Channel number (1-4). RX LPM LFK override enable mask for the specified channel.
Referenced by XHdmiphy1_HdmiGtDruModeEnable.
XHDMIPHY1_RX_STATUS_RXLPMHFOVRDEN_MASK
RX LPM HF override enable mask for specific channel.
Ch Channel number (1-4). RX LPM HF override enable mask for the specified channel.
Referenced by XHdmiphy1_HdmiGtDruModeEnable.
XHdmiphy1_GtType
XHdmiphy1_ProtocolType
XHdmiphy1_DirectionType
XHdmiphy1_ClkPrimitive
XHdmiphy1_IntrHandlerType
XHdmiphy1_HdmiHandlerType
TX init handler.
XHdmiphy1_PllType
XHdmiphy1_ChannelId
XHdmiphy1_PllRefClkSelType
XHdmiphy1_SysClkDataSelType
XHdmiphy1_SysClkOutSelType
XHdmiphy1_OutClkSelType
XHdmiphy1_GtState
Idle state.
XHdmiphy1_LogEvent
Log event none.
XHdmiphy1_MmcmDivType
XHdmiphy1_MmcmClkinsel
XHdmiphy1_HdmiTx_Patgen
LR:Clock Ratio = 10.
XHdmiphy1_PrbsPattern
Pattern gen/mon OFF.
typedef void(* XHdmiphy1_IntrHandler)(void *InstancePtr))(void *InstancePtr)
Callback type which represents the handler for interrupts.
InstancePtr is a pointer to the XHdmiphy1 instance. None.
typedef void(* XHdmiphy1_TimerHandler)(void *InstancePtr, u32 MicroSeconds))(void *InstancePtr, u32 MicroSeconds)
Callback type which represents a custom timer wait handler.
This is only used for Microblaze since it doesn't have a native sleep function. To avoid dependency on a hardware timer, the default wait functionality is implemented using loop iterations; this isn't too accurate. If a custom timer handler is used, the user may implement their own wait implementation using a hardware timer (see example/) for better accuracy. InstancePtr is a pointer to the XHdmiphy1 instance. MicroSeconds is the number of microseconds to be passed to the timer function. None.
typedef void(* XHdmiphy1_Callback)(void *CallbackRef))(void *CallbackRef)
Generic callback type.
CallbackRef is a pointer to the callback reference. None.
typedef u64(* XHdmiphy1_LogCallback)(void *CallbackRef))(void *CallbackRef)
Generic callback type.
CallbackRef is a pointer to the callback reference. u8 value.
typedef void(* XHdmiphy1_ErrorCallback)(void *CallbackRef))(void *CallbackRef)
Error callback type.
CallbackRef is a pointer to the callback reference. None.
typedef struct XHdmiphy1_GtConfigS XHdmiphy1_GtConfig
void XHdmiphy1_CfgInitialize(XHdmiphy1 *InstancePtr, XHdmiphy1_Config *ConfigPtr, UINTPTR EffectiveAddr)
This function retrieves the configuration for this Video PHY instance and fills in the InstancePtr->Config structure.
InstancePtr is a pointer to the XHdmiphy1 instance. ConfigPtr is a pointer to the configuration structure that will be used to copy the settings from. EffectiveAddr is the device base address in the virtual memory space. If the address translation is not used, then the physical address is passed. None. Unexpected errors may occur if the address mapping is changed after this function is invoked.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_Config::DruRefClkSel, XHdmiphy1::IsReady, XHdmiphy1_Config::RxFrlRefClkSel, XHdmiphy1_Config::RxRefClkSel, XHdmiphy1_Config::RxSysPllClkSel, XHdmiphy1_Config::TxFrlRefClkSel, XHdmiphy1_Config::TxRefClkSel, XHdmiphy1_Config::TxSysPllClkSel, XHdmiphy1_Config::XcvrType.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
u32 XHdmiphy1_PllInitialize(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_PllRefClkSelType QpllRefClkSel, XHdmiphy1_PllRefClkSelType CpllxRefClkSel, XHdmiphy1_PllType TxPllSelect, XHdmiphy1_PllType RxPllSelect)
This function will initialize the PLL selection for a given channel.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. QpllRefClkSel is the QPLL reference clock selection for the quad. CpllRefClkSel is the CPLL reference clock selection for the quad. TxPllSelect is the reference clock selection for the quad's TX PLL dividers. RxPllSelect is the reference clock selection for the quad's RX PLL dividers. XST_SUCCESS. None.
References XHdmiphy1_CfgPllRefClkSel, XHdmiphy1_CfgSysClkDataSel, XHdmiphy1_CfgSysClkOutSel, XHdmiphy1_Pll2SysClkData, XHdmiphy1_Pll2SysClkOut, XHdmiphy1_WriteCfgRefClkSelReg.
u32 XHdmiphy1_GetVersion(XHdmiphy1 *InstancePtr)
This function will obtian the IP version.
InstancePtr is a pointer to the XHdmiphy1 core instance. The IP version of the Video PHY core. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_ReadReg, XHDMIPHY1_VERSION_REG.
void XHdmiphy1_WaitUs(XHdmiphy1 *InstancePtr, u32 MicroSeconds)
This function is the delay/sleep function for the XHdmiphy1 driver.
For the Zynq family, there exists native sleep functionality. For MicroBlaze however, there does not exist such functionality. In the MicroBlaze case, the default method for delaying is to use a predetermined amount of loop iterations. This method is prone to inaccuracy and dependent on system configuration; for greater accuracy, the user may supply their own delay/sleep handler, pointed to by InstancePtr->UserTimerWaitUs, which may have better accuracy if a hardware timer is used. InstancePtr is a pointer to the XHdmiphy1 instance. MicroSeconds is the number of microseconds to delay/sleep for. None. None.
References XHdmiphy1::IsReady, XHdmiphy1::UserTimerWaitUs.
void XHdmiphy1_SetUserTimerHandler(XHdmiphy1 *InstancePtr, XHdmiphy1_TimerHandler CallbackFunc, void *CallbackRef)
u32 XHdmiphy1_CfgLineRate(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, u64 LineRateHz)
Configure the channel's line rate.
This is a software only configuration and this value is used in the PLL calculator. InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. LineRateHz is the line rate to configure software. XST_SUCCESS if the reference clock type is valid.XST_FAILURE otherwise. None.
References XHdmiphy1_Channel::LineRateHz, XHdmiphy1::Quads, XHdmiphy1_Ch2Ids, XHDMIPHY1_CH2IDX.
Referenced by XHdmiphy1_HdmiCpllParam, XHdmiphy1_HdmiQpllParam.
XHdmiphy1_PllType XHdmiphy1_GetPllType(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir, XHdmiphy1_ChannelId ChId)
Obtain the channel's PLL reference clock selection.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. ChId is the channel ID which to operate on. The PLL type being used by the channel. None.
References XHdmiphy1::Config, XHdmiphy1_Config::RxSysPllClkSel, XHdmiphy1_Config::TxSysPllClkSel, XHdmiphy1_GetSysClkDataSel, XHdmiphy1_GetSysClkOutSel.
Referenced by XHdmiphy1_Hdmi20Config, XHdmiphy1_Hdmi21Config, XHdmiphy1_HdmiCfgCalcMmcmParam, XHdmiphy1_HdmiCpllLockHandler, XHdmiphy1_HdmiGtTxResetDoneLockHandler, XHdmiphy1_HdmiQpllLockHandler, XHdmiphy1_HdmiRxClkDetFreqChangeHandler, XHdmiphy1_HdmiRxTimerTimeoutHandler, XHdmiphy1_HdmiTxClkDetFreqChangeHandler, XHdmiphy1_HdmiTxTimerTimeoutHandler, XHdmiphy1_IsPllLocked, XHdmiphy1_SetHdmiRxParam.
u64 XHdmiphy1_GetLineRateHz(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId)
This function will return the line rate in Hz for a given channel / quad.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to check. ChId is the channel ID for which to retrieve the line rate. The line rate in Hz. None.
References XHdmiphy1_Channel::LineRateHz, XHdmiphy1::Quads.
Referenced by XHdmiphy1_HdmiCpllParam, XHdmiphy1_HdmiGtTxResetDoneLockHandler, XHdmiphy1_HdmiQpllParam.
u32 XHdmiphy1_ResetGtPll(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir, u8 Hold)
This function will reset the GT's PLL logic.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID which to operate on. Dir is an indicator for TX or RX. Hold is an indicator whether to "hold" the reset if set to 1. If set to 0: reset, then enable. XST_SUCCESS. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_ReadReg, XHDMIPHY1_RX_INIT_REG, XHDMIPHY1_TX_INIT_REG, XHDMIPHY1_TXRX_INIT_PLLGTRESET_ALL_MASK, XHDMIPHY1_TXRX_INIT_PLLGTRESET_MASK, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize, XHdmiphy1_HdmiRxClkDetFreqChangeHandler, XHdmiphy1_HdmiRxTimerTimeoutHandler, XHdmiphy1_HdmiTxClkDetFreqChangeHandler, XHdmiphy1_HdmiTxTimerTimeoutHandler, XHdmiphy1_HdmiUpdateClockSelection.
u32 XHdmiphy1_ResetGtTxRx(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir, u8 Hold)
This function will reset the GT's TX/RX logic.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID which to operate on. Dir is an indicator for TX or RX. Hold is an indicator whether to "hold" the reset if set to 1. If set to 0: reset, then enable. XST_SUCCESS. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_ReadReg, XHDMIPHY1_RX_INIT_REG, XHDMIPHY1_TX_INIT_REG, XHDMIPHY1_TXRX_INIT_GTRESET_ALL_MASK, XHDMIPHY1_TXRX_INIT_GTRESET_MASK, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_HdmiCpllLockHandler, XHdmiphy1_HdmiQpllLockHandler.
u32 XHdmiphy1_SetPolarity(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir, u8 Polarity)
This function will set/clear the TX/RX polarity bit.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID which to operate on. Dir is an indicator for TX or RX. Polarity 0-Not inverted 1-Inverted XST_SUCCESS. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_ReadReg, XHDMIPHY1_RX_CONTROL_REG, XHDMIPHY1_RX_CONTROL_RXPOLARITY_ALL_MASK, XHDMIPHY1_RX_CONTROL_RXPOLARITY_MASK, XHDMIPHY1_TX_CONTROL_REG, XHDMIPHY1_TX_CONTROL_TXPOLARITY_ALL_MASK, XHDMIPHY1_TX_CONTROL_TXPOLARITY_MASK, XHdmiphy1_WriteReg.
u32 XHdmiphy1_SetPrbsSel(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir, XHdmiphy1_PrbsPattern Pattern)
This function will set the TX/RXPRBSEL of the GT.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID which to operate on. Dir is an indicator for TX or RX. Pattern is the pattern XHdmiphy1_PrbsPattern XST_SUCCESS. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_Ch2Ids, XHdmiphy1_ReadReg, XHDMIPHY1_RX_CONTROL_REG, XHDMIPHY1_RX_CONTROL_RXPRBSSEL_ALL_MASK, XHDMIPHY1_RX_CONTROL_RXPRBSSEL_MASK, XHDMIPHY1_RX_CONTROL_RXPRBSSEL_SHIFT, XHDMIPHY1_TX_CONTROL_REG, XHDMIPHY1_TX_CONTROL_TXPRBSSEL_ALL_MASK, XHDMIPHY1_TX_CONTROL_TXPRBSSEL_MASK, XHDMIPHY1_TX_CONTROL_TXPRBSSEL_SHIFT, XHdmiphy1_WriteReg.
u32 XHdmiphy1_TxPrbsForceError(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, u8 ForceErr)
This function will force an error in the TX PRBS pattern for the GT.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID which to operate on. ForceErr 0-No Error 1-Force Error XST_SUCCESS. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_ReadReg, XHDMIPHY1_TX_CONTROL_REG, XHDMIPHY1_TX_CONTROL_TXPRBSFORCEERR_ALL_MASK, XHDMIPHY1_TX_CONTROL_TXPRBSFORCEERR_MASK, XHdmiphy1_WriteReg.
void XHdmiphy1_SetTxVoltageSwing(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, u8 Vs)
This function will set the TX voltage swing value for a given channel.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. Vs is the voltage swing value to write. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_ReadReg, XHDMIPHY1_TX_DRIVER_CH12_REG, XHDMIPHY1_TX_DRIVER_CH34_REG, XHDMIPHY1_TX_DRIVER_EXT_REG, XHDMIPHY1_TX_DRIVER_EXT_TXDIFFCTRL_MASK, XHDMIPHY1_TX_DRIVER_EXT_TXDIFFCTRL_SHIFT, XHDMIPHY1_TX_DRIVER_TXDIFFCTRL_MASK, XHDMIPHY1_TX_DRIVER_TXDIFFCTRL_SHIFT, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
void XHdmiphy1_SetTxPreEmphasis(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, u8 Pe)
This function will set the TX pre-emphasis value for a given channel.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. Pe is the pre-emphasis value to write. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_ReadReg, XHDMIPHY1_TX_DRIVER_CH12_REG, XHDMIPHY1_TX_DRIVER_CH34_REG, XHDMIPHY1_TX_DRIVER_TXPRECURSOR_MASK, XHDMIPHY1_TX_DRIVER_TXPRECURSOR_SHIFT, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
void XHdmiphy1_SetTxPostCursor(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, u8 Pc)
This function will set the TX post-cursor value for a given channel.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. Pc is the post-cursor value to write. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_ReadReg, XHDMIPHY1_TX_DRIVER_CH12_REG, XHDMIPHY1_TX_DRIVER_CH34_REG, XHDMIPHY1_TX_DRIVER_TXPOSTCURSOR_MASK, XHDMIPHY1_TX_DRIVER_TXPOSTCURSOR_SHIFT, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
void XHdmiphy1_SetRxLpm(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir, u8 Enable)
This function will enable or disable the LPM logic in the Video PHY core.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. Dir is an indicator for TX or RX. Enable will enable (if 1) or disable (if 0) the LPM logic. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_ReadReg, XHDMIPHY1_RX_CONTROL_RXLPMEN_ALL_MASK, XHDMIPHY1_RX_CONTROL_RXLPMEN_MASK, XHDMIPHY1_RX_EQ_CDR_REG, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
u32 XHdmiphy1_DrpWr(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, u16 Addr, u16 Val)
This function will initiate a write DRP transaction.
It is a wrapper around XHdmiphy1_DrpAccess. InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID on which to direct the DRP access. Addr is the DRP address to issue the DRP access to. Val is the value to write to the DRP address. XST_SUCCESS if the DRP access was successful.XST_FAILURE otherwise, if the busy bit did not go low, or if the ready bit did not go high. None.
u16 XHdmiphy1_DrpRd(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, u16 Addr, u16 *RetVal)
This function will initiate a read DRP transaction.
It is a wrapper around XHdmiphy1_DrpAccess. InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID on which to direct the DRP access. Addr is the DRP address to issue the DRP access to. RetVal is the DRP read_value returned implicitly. XST_SUCCESS if the DRP access was successful.XST_FAILURE otherwise, if the busy bit did not go low, or if the ready bit did not go high. None.
Referenced by XHdmiphy1_RegisterDebug.
void XHdmiphy1_MmcmPowerDown(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir, u8 Hold)
This function will power down the mixed-mode clock manager (MMCM) core.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. Hold is an indicator whether to "hold" the power down if set to 1. If set to 0: power down, then power back up. XST_SUCCESS. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_MMCM_RXUSRCLK_CTRL_REG, XHDMIPHY1_MMCM_TXUSRCLK_CTRL_REG, XHDMIPHY1_MMCM_USRCLK_CTRL_PWRDWN_MASK, XHdmiphy1_ReadReg, XHdmiphy1_WriteReg.
void XHdmiphy1_MmcmStart(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir)
This function will start the mixed-mode clock manager (MMCM) core.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. None. None.
References XHdmiphy1::Config, XHdmiphy1::Quads, XHdmiphy1_Config::RxClkPrimitive, XHdmiphy1_Quad::RxMmcm, XHdmiphy1_Config::TxClkPrimitive, XHdmiphy1_Quad::TxMmcm, XHDMIPHY1_LOG_EVT_RXPLL_RECONFIG, XHDMIPHY1_LOG_EVT_TXPLL_RECONFIG, XHdmiphy1_LogWrite, XHdmiphy1_MmcmLockedMaskEnable, XHdmiphy1_MmcmReset.
Referenced by XHdmiphy1_Hdmi21Config, XHdmiphy1_HdmiRxTimerTimeoutHandler, XHdmiphy1_HdmiTxTimerTimeoutHandler.
void XHdmiphy1_IBufDsEnable(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir, u8 Enable)
This function enables the TX or RX IBUFDS peripheral.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. Enable specifies TRUE/FALSE value to either enable or disable the IBUFDS, respectively. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_Config::DruIsPresent, XHdmiphy1_Config::DruRefClkSel, XHdmiphy1_Config::RxRefClkSel, XHdmiphy1_Config::TxRefClkSel, XHDMIPHY1_IBUFDS_GTXX_CTRL_GTREFCLK0_CEB_MASK, XHDMIPHY1_IBUFDS_GTXX_CTRL_GTREFCLK1_CEB_MASK, XHDMIPHY1_IBUFDS_GTXX_CTRL_REG, XHDMIPHY1_MISC_RXUSRCLK_REG, XHDMIPHY1_MISC_TXUSRCLK_REG, XHDMIPHY1_MISC_XXUSRCLK_REFCLK_CEB_MASK, XHdmiphy1_ReadReg, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
void XHdmiphy1_Clkout1OBufTdsEnable(XHdmiphy1 *InstancePtr, XHdmiphy1_DirectionType Dir, u8 Enable)
This function enables the TX or RX CLKOUT1 OBUFTDS peripheral.
InstancePtr is a pointer to the XHdmiphy1 core instance. Dir is an indicator for TX or RX. Enable specifies TRUE/FALSE value to either enable or disable the OBUFTDS, respectively. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_MISC_RXUSRCLK_REG, XHDMIPHY1_MISC_TXUSRCLK_REG, XHDMIPHY1_MISC_XXUSRCLK_CKOUT1_OEN_MASK, XHdmiphy1_ReadReg, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi21Config.
void XHdmiphy1_SetErrorCallback(XHdmiphy1 *InstancePtr, void *CallbackFunc, void *CallbackRef)
This function installs a callback function for the HDMIPHY error conditions.
InstancePtr is a pointer to the XHdmiphy1 instance. CallbackFunc is the address to the callback function. CallbackRef is the user data item that will be passed to the callback function when it is invoked. None. The XHdmiphy1_ErrorHandler API calls the registered function in ErrorCallback and passes two arguments: 1) CallbackRef 2) Error Type as defined by XHdmiphy1_ErrType. Sample Function Call: CallbackFunc(CallbackRef, XHdmiphy1_ErrType);
References XHdmiphy1::ErrorCallback, XHdmiphy1::ErrorRef.
void XHdmiphy1_SetLogCallback(XHdmiphy1 *InstancePtr, u64 *CallbackFunc, void *CallbackRef)
This function installs an asynchronous callback function for the LogWrite API:
InstancePtr is a pointer to the XHdmiphy1 instance. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. None.
References XHdmiphy1::LogWriteCallback, XHdmiphy1::LogWriteRef.
void XHdmiphy1_LogDisplay(XHdmiphy1 *InstancePtr)
This function will print the entire log.
InstancePtr is a pointer to the XHdmiphy1 core instance. None. None.
References XHdmiphy1::Log, XHdmiphy1::LogWriteCallback, XHdmiphy1_Log::TailIndex, XHdmiphy1_Log::TimeRecord, XHDMIPHY1_LOG_EVT_1PPC_ERR, XHDMIPHY1_LOG_EVT_CPLL_EN, XHDMIPHY1_LOG_EVT_CPLL_LOCK, XHDMIPHY1_LOG_EVT_CPLL_RECONFIG, XHDMIPHY1_LOG_EVT_CPLL_RST, XHDMIPHY1_LOG_EVT_DRU_CLK_ERR, XHDMIPHY1_LOG_EVT_DRU_EN, XHDMIPHY1_LOG_EVT_FRL_RECONFIG, XHDMIPHY1_LOG_EVT_GT_CPLL_CFG_ERR, XHDMIPHY1_LOG_EVT_GT_LCPLL_CFG_ERR, XHDMIPHY1_LOG_EVT_GT_QPLL_CFG_ERR, XHDMIPHY1_LOG_EVT_GT_RECONFIG, XHDMIPHY1_LOG_EVT_GT_RPLL_CFG_ERR, XHDMIPHY1_LOG_EVT_GT_RX_RECONFIG, XHDMIPHY1_LOG_EVT_GT_TX_RECONFIG, XHDMIPHY1_LOG_EVT_GTRX_RST, XHDMIPHY1_LOG_EVT_GTTX_RST, XHDMIPHY1_LOG_EVT_HDMI20_ERR, XHDMIPHY1_LOG_EVT_INIT, XHDMIPHY1_LOG_EVT_LCPLL_LOCK, XHDMIPHY1_LOG_EVT_MMCM_ERR, XHDMIPHY1_LOG_EVT_NO_DRU, XHDMIPHY1_LOG_EVT_NO_QPLL_ERR, XHDMIPHY1_LOG_EVT_NONE, XHDMIPHY1_LOG_EVT_PPC_MSMTCH_ERR, XHDMIPHY1_LOG_EVT_QPLL_EN, XHDMIPHY1_LOG_EVT_QPLL_LOCK, XHDMIPHY1_LOG_EVT_QPLL_RECONFIG, XHDMIPHY1_LOG_EVT_QPLL_RST, XHDMIPHY1_LOG_EVT_RPLL_LOCK, XHDMIPHY1_LOG_EVT_RX_FREQ, XHDMIPHY1_LOG_EVT_RX_RST_DONE, XHDMIPHY1_LOG_EVT_RX_TMR, XHDMIPHY1_LOG_EVT_RXGPO_RE, XHDMIPHY1_LOG_EVT_RXPLL_EN, XHDMIPHY1_LOG_EVT_RXPLL_LOCK, XHDMIPHY1_LOG_EVT_RXPLL_RECONFIG, XHDMIPHY1_LOG_EVT_RXPLL_RST, XHDMIPHY1_LOG_EVT_SPDGRDE_ERR, XHDMIPHY1_LOG_EVT_TMDS_RECONFIG, XHDMIPHY1_LOG_EVT_TX_ALIGN, XHDMIPHY1_LOG_EVT_TX_ALIGN_TMOUT, XHDMIPHY1_LOG_EVT_TX_FREQ, XHDMIPHY1_LOG_EVT_TX_RST_DONE, XHDMIPHY1_LOG_EVT_TX_TMR, XHDMIPHY1_LOG_EVT_TXGPO_RE, XHDMIPHY1_LOG_EVT_TXPLL_EN, XHDMIPHY1_LOG_EVT_TXPLL_LOCK, XHDMIPHY1_LOG_EVT_TXPLL_RECONFIG, XHDMIPHY1_LOG_EVT_TXPLL_RST, XHDMIPHY1_LOG_EVT_USRCLK_ERR, XHDMIPHY1_LOG_EVT_VD_NOT_SPRTD_ERR, XHDMIPHY1_LOG_EVT_VDCLK_HIGH_ERR, XHDMIPHY1_LOG_EVT_VID_RX_RST, XHDMIPHY1_LOG_EVT_VID_TX_RST, XHdmiphy1_LogRead.
void XHdmiphy1_LogReset(XHdmiphy1 *InstancePtr)
This function will reset the driver's logging mechanism.
InstancePtr is a pointer to the XHdmiphy1 core instance. None. None.
References XHdmiphy1_Log::HeadIndex, XHdmiphy1::Log, XHdmiphy1_Log::TailIndex.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
u16 XHdmiphy1_LogRead(XHdmiphy1 *InstancePtr)
This function will read the last event from the log.
InstancePtr is a pointer to the XHdmiphy1 core instance. The log data. None.
References XHdmiphy1_Log::DataBuffer, XHdmiphy1_Log::HeadIndex, XHdmiphy1::Log, XHdmiphy1_Log::TailIndex.
Referenced by XHdmiphy1_LogDisplay.
void XHdmiphy1_LogWrite(XHdmiphy1 *InstancePtr, XHdmiphy1_LogEvent Evt, u8 Data)
This function will insert an event in the driver's logging mechanism.
InstancePtr is a pointer to the XHdmiphy1 core instance. Evt is the event type to log. Data is the associated data for the event. None. None.
References XHdmiphy1_Log::DataBuffer, XHdmiphy1_Log::HeadIndex, XHdmiphy1::Log, XHdmiphy1::LogWriteCallback, XHdmiphy1::LogWriteRef, XHdmiphy1_Log::TailIndex, XHdmiphy1_Log::TimeRecord, XHDMIPHY1_LOG_EVT_DUMMY.
Referenced by XHdmiphy1_ClkReconfig, XHdmiphy1_DirReconfig, XHdmiphy1_Hdmi20Config, XHdmiphy1_Hdmi21Config, XHdmiphy1_Hdmi_CfgInitialize, XHdmiphy1_HdmiCfgCalcMmcmParam, XHdmiphy1_HdmiCpllLockHandler, XHdmiphy1_HdmiCpllParam, XHdmiphy1_HdmiGtDruModeEnable, XHdmiphy1_HdmiGtRxResetDoneLockHandler, XHdmiphy1_HdmiGtTxAlignDoneLockHandler, XHdmiphy1_HdmiGtTxResetDoneLockHandler, XHdmiphy1_HdmiQpllLockHandler, XHdmiphy1_HdmiQpllParam, XHdmiphy1_HdmiRxClkDetFreqChangeHandler, XHdmiphy1_HdmiRxMmcmLockHandler, XHdmiphy1_HdmiRxTimerTimeoutHandler, XHdmiphy1_HdmiTxClkDetFreqChangeHandler, XHdmiphy1_HdmiTxMmcmLockHandler, XHdmiphy1_HdmiTxTimerTimeoutHandler, XHdmiphy1_MmcmStart, XHdmiphy1_OutDivReconfig, XHdmiphy1_SetHdmiTxParam.
void XHdmiphy1_InterruptHandler(XHdmiphy1 *InstancePtr)
This function is the interrupt handler for the XHdmiphy1 driver.
It will detect what kind of interrupt has happened, and will invoke the appropriate callback function. InstancePtr is a pointer to the XHdmiphy1 instance. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1::IntrCpllLockCallbackRef, XHdmiphy1::IntrCpllLockHandler, XHdmiphy1::IntrQpll1LockCallbackRef, XHdmiphy1::IntrQpll1LockHandler, XHdmiphy1::IntrQpllLockCallbackRef, XHdmiphy1::IntrQpllLockHandler, XHdmiphy1::IntrRxClkDetFreqChangeCallbackRef, XHdmiphy1::IntrRxClkDetFreqChangeHandler, XHdmiphy1::IntrRxMmcmLockCallbackRef, XHdmiphy1::IntrRxMmcmLockHandler, XHdmiphy1::IntrRxResetDoneCallbackRef, XHdmiphy1::IntrRxResetDoneHandler, XHdmiphy1::IntrRxTmrTimeoutCallbackRef, XHdmiphy1::IntrRxTmrTimeoutHandler, XHdmiphy1::IntrTxAlignDoneCallbackRef, XHdmiphy1::IntrTxAlignDoneHandler, XHdmiphy1::IntrTxClkDetFreqChangeCallbackRef, XHdmiphy1::IntrTxClkDetFreqChangeHandler, XHdmiphy1::IntrTxMmcmLockCallbackRef, XHdmiphy1::IntrTxMmcmLockHandler, XHdmiphy1::IntrTxResetDoneCallbackRef, XHdmiphy1::IntrTxResetDoneHandler, XHdmiphy1::IntrTxTmrTimeoutCallbackRef, XHdmiphy1::IntrTxTmrTimeoutHandler, XHdmiphy1::IsReady, XHDMIPHY1_INTR_CPLL_LOCK_MASK, XHDMIPHY1_INTR_LCPLL_LOCK_MASK, XHDMIPHY1_INTR_QPLL1_LOCK_MASK, XHDMIPHY1_INTR_QPLL_LOCK_MASK, XHDMIPHY1_INTR_RPLL_LOCK_MASK, XHDMIPHY1_INTR_RXCLKDETFREQCHANGE_MASK, XHDMIPHY1_INTR_RXGPO_RE_MASK, XHDMIPHY1_INTR_RXMMCMUSRCLK_LOCK_MASK, XHDMIPHY1_INTR_RXRESETDONE_MASK, XHDMIPHY1_INTR_RXTMRTIMEOUT_MASK, XHDMIPHY1_INTR_STS_REG, XHDMIPHY1_INTR_TXALIGNDONE_MASK, XHDMIPHY1_INTR_TXCLKDETFREQCHANGE_MASK, XHDMIPHY1_INTR_TXGPO_RE_MASK, XHDMIPHY1_INTR_TXMMCMUSRCLK_LOCK_MASK, XHDMIPHY1_INTR_TXRESETDONE_MASK, XHDMIPHY1_INTR_TXTMRTIMEOUT_MASK, XHdmiphy1_ReadReg.
u32 XHdmiphy1_SelfTest(XHdmiphy1 *InstancePtr)
This function runs a self-test on the XHdmiphy1 driver/device.
The sanity test checks whether or not all tested registers hold their default reset values. InstancePtr is a pointer to the XHdmiphy1 instance. XST_SUCCESS if the self-test passed - all tested registers hold their default reset values.XST_FAILURE otherwise. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_ReadReg.
XHdmiphy1_Config* XHdmiphy1_LookupConfig(UINTPTR BaseAddress)
This function looks for the device configuration based on the unique device ID.
The table XHdmiphy1_ConfigTable[] contains the configuration information for each device in the system. DeviceId is the unique device ID of the device being looked up. A pointer to the configuration table entry corresponding to the given device ID, or NULL if no match is found. None. This function looks for the device configuration based on the base address. The table XHdmiphy1_ConfigTable[] contains the configuration information for each device in the system. BaseAddress is the base address of the device being looked up. A pointer to the configuration table entry corresponding to the given base address, or NULL if no match is found. None.
u32 XHdmiphy1_GetDrvIndex(XHdmiphy1 *InstancePtr, UINTPTR BaseAddress)
u32 XHdmiphy1_Hdmi_CfgInitialize(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_Config *CfgPtr)
This function initializes the Video PHY for HDMI.
InstancePtr is a pointer to the XHdmiphy1 instance. CfgPtr is a pointer to the configuration structure that will be used to copy the settings from. QuadId is the GT quad ID to operate on. None. None.
References XHdmiphy1_Config::AxiLiteClkFreq, XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_Config::DruIsPresent, XHdmiphy1::HdmiIsQpllPresent, XHdmiphy1::IsReady, XHdmiphy1::Quads, XHdmiphy1_Channel::RxState, XHdmiphy1_Config::TransceiverWidth, XHdmiphy1_Channel::TxState, XHdmiphy1_Config::XcvrType, XHdmiphy1_CfgInitialize, XHdmiphy1_Ch2Ids, XHDMIPHY1_CH2IDX, XHdmiphy1_ClkDetAccuracyRange, XHdmiphy1_ClkDetEnable, XHdmiphy1_ClkDetSetFreqLockThreshold, XHdmiphy1_ClkDetSetFreqTimeout, XHdmiphy1_DruEnable, XHdmiphy1_DruReset, XHDMIPHY1_GT_STATE_IDLE, XHdmiphy1_HdmiIntrHandlerCallbackInit, XHdmiphy1_IBufDsEnable, XHDMIPHY1_INTR_STS_REG, XHdmiphy1_IntrDisable, XHdmiphy1_IntrEnable, XHdmiphy1_IsHDMI, XHdmiphy1_IsRxUsingQpll, XHdmiphy1_IsTxUsingQpll, XHDMIPHY1_LOG_EVT_INIT, XHdmiphy1_LogReset, XHdmiphy1_LogWrite, XHdmiphy1_MmcmReset, XHdmiphy1_PowerDownGtPll, XHdmiphy1_ResetGtPll, XHdmiphy1_SetBufgGtDiv, XHdmiphy1_SetRxLpm, XHdmiphy1_SetTxPostCursor, XHdmiphy1_SetTxPreEmphasis, XHdmiphy1_SetTxVoltageSwing, XHdmiphy1_WriteReg.
u32 XHdmiphy1_SetHdmiTxParam(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XVidC_PixelsPerClock Ppc, XVidC_ColorDepth Bpc, XVidC_ColorFormat ColorFormat)
This function update/set the HDMI TX parameter.
InstancePtr is a pointer to the Hdmiphy core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. Ppc is the pixels per clock to set. Bpc is the bits per color to set. ColorFormat is the color format to set. XST_SUCCESS if TX parameters set/updated.XST_FAILURE if low resolution video not supported. None.
References XHdmiphy1::Config, XHdmiphy1_Hdmi21Cfg::IsEnabled, XHdmiphy1_Config::Ppc, XHdmiphy1::TxHdmi21Cfg, XHdmiphy1_ErrorHandler, XHdmiphy1_HdmiCfgCalcMmcmParam, XHdmiphy1_HdmiCpllParam, XHdmiphy1_HdmiQpllParam, XHdmiphy1_IsTxUsingCpll, XHDMIPHY1_LOG_EVT_PPC_MSMTCH_ERR, XHdmiphy1_LogWrite, XHdmiphy1_WriteCfgRefClkSelReg.
Referenced by XHdmiphy1_Hdmi21Config.
u32 XHdmiphy1_SetHdmiRxParam(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId)
This function update/set the HDMI RX parameter.
InstancePtr is a pointer to the Hdmiphy core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. XST_SUCCESS if RX parameters set/updated.XST_FAILURE if low resolution video not supported. None.
References XHdmiphy1::HdmiRxDruIsEnabled, XHdmiphy1_DruCalcCenterFreqHz, XHdmiphy1_DruSetCenterFreqHz, XHdmiphy1_GetPllType, XHdmiphy1_GetRcfgChId, XHdmiphy1_HdmiCpllParam, XHdmiphy1_HdmiQpllParam, XHdmiphy1_IsRxUsingCpll, XHdmiphy1_WriteCfgRefClkSelReg.
Referenced by XHdmiphy1_HdmiRxTimerTimeoutHandler.
u32 XHdmiphy1_HdmiCfgCalcMmcmParam(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir, XVidC_PixelsPerClock Ppc, XVidC_ColorDepth Bpc)
This function calculates the HDMI MMCM parameters.
InstancePtr is a pointer to the Hdmiphy core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. Dir is an indicator for RX or TX. Ppc specifies the total number of pixels per clock. 1 = XVIDC_PPC_12 = XVIDC_PPC_24 = XVIDC_PPC_4 Bpc specifies the color depth/bits per color component. 6 = XVIDC_BPC_68 = XVIDC_BPC_810 = XVIDC_BPC_1012 = XVIDC_BPC_1216 = XVIDC_BPC_16 XST_SUCCESS if calculated PLL parameters updated successfully.XST_FAILURE if parameters not updated. None.
References XHdmiphy1::Config, XHdmiphy1::HdmiRxRefClkHz, XHdmiphy1::HdmiRxTmdsClockRatio, XHdmiphy1::HdmiTxRefClkHz, XHdmiphy1::HdmiTxSampleRate, XHdmiphy1_Channel::LineRateHz, XHdmiphy1::Quads, XHdmiphy1_Config::RxClkPrimitive, XHdmiphy1_Quad::RxMmcm, XHdmiphy1_Config::TransceiverWidth, XHdmiphy1_Config::TxClkPrimitive, XHdmiphy1_Quad::TxMmcm, XHdmiphy1_ErrorHandler, XHdmiphy1_GetPllType, XHDMIPHY1_LOG_EVT_1PPC_ERR, XHdmiphy1_LogWrite.
Referenced by XHdmiphy1_SetHdmiTxParam.
void XHdmiphy1_HdmiUpdateClockSelection(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_SysClkDataSelType TxSysPllClkSel, XHdmiphy1_SysClkDataSelType RxSysPllClkSel)
This function Updates the HDMIPHY clocking.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. TxSysPllClkSel is the SYSCLKDATA selection for TX. RxSysPllClkSel is the SYSCLKDATA selection for RX. None. None.
References XHdmiphy1::Config, XHdmiphy1::Quads, XHdmiphy1_Channel::RxState, XHdmiphy1_Config::RxSysPllClkSel, XHdmiphy1_Channel::TxState, XHdmiphy1_Config::TxSysPllClkSel, XHdmiphy1_Ch2Ids, XHDMIPHY1_CH2IDX, XHDMIPHY1_GT_STATE_IDLE, XHdmiphy1_ResetGtPll.
void XHdmiphy1_ClkDetFreqReset(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir)
This function resets clock detector TX/RX frequency.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for RX or TX. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_CLKDET_CTRL_REG, XHDMIPHY1_CLKDET_CTRL_RX_FREQ_RST_MASK, XHDMIPHY1_CLKDET_CTRL_TX_FREQ_RST_MASK, XHdmiphy1_ReadReg, XHdmiphy1_WriteReg.
u32 XHdmiphy1_ClkDetGetRefClkFreqHz(XHdmiphy1 *InstancePtr, XHdmiphy1_DirectionType Dir)
This function returns the frequency of the RX/TX reference clock as measured by the clock detector peripheral.
InstancePtr is a pointer to the XHdmiphy1 core instance. Dir is an indicator for RX or TX. The measured frequency of the RX/TX reference clock. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_Hdmi21Cfg::IsEnabled, XHdmiphy1_Config::RxFrlRefClkSel, XHdmiphy1::RxHdmi21Cfg, XHdmiphy1_Config::RxRefClkSel, XHdmiphy1_Config::TxFrlRefClkSel, XHdmiphy1::TxHdmi21Cfg, XHdmiphy1_Config::TxRefClkSel, XHDMIPHY1_CLKDET_FREQ_RX_FRL_REG, XHDMIPHY1_CLKDET_FREQ_RX_REG, XHDMIPHY1_CLKDET_FREQ_TX_FRL_REG, XHDMIPHY1_CLKDET_FREQ_TX_REG, XHdmiphy1_ReadReg.
Referenced by XHdmiphy1_DruCalcCenterFreqHz, XHdmiphy1_HdmiRxClkDetFreqChangeHandler, XHdmiphy1_HdmiTxClkDetFreqChangeHandler.
u32 XHdmiphy1_ClkDetGetRefClkFreqHzRaw(XHdmiphy1 *InstancePtr, XHdmiphy1_DirectionType Dir)
This function returns the raw (unconditional) frequency of the RX/TX reference clock as measured by the clock detector peripheral.
Unlike XHdmiphy1_ClkDetGetRefClkFreqHz, this function always returns the measured value regardless of lock status - useful for debugging. InstancePtr is a pointer to the XHdmiphy1 core instance. Dir is an indicator for RX or TX. The raw measured frequency of the RX/TX reference clock. This function returns the actual measured frequency value even when lock conditions are not met. Use this for debugging to determine if a clock is present vs not locked.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_CLKDET_FREQ_RX_RAW_REG, XHDMIPHY1_CLKDET_FREQ_TX_RAW_REG, XHdmiphy1_ReadReg.
u32 XHdmiphy1_DruGetRefClkFreqHz(XHdmiphy1 *InstancePtr)
This function returns the frequency of the DRU reference clock as measured by the clock detector peripheral.
InstancePtr is a pointer to the XHdmiphy1 core instance. The measured frequency of the DRU reference clock. The design must have a DRU for this function to return a valid value.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1::versal_2ve_2vm, XHdmiphy1_Config::XcvrType, XHDMIPHY1_CLKDET_FREQ_DRU_REG, XHdmiphy1_ReadReg.
Referenced by XHdmiphy1_DruCalcCenterFreqHz, XHdmiphy1_GetPllVcoFreqHz, XHdmiphy1_HdmiCpllParam, XHdmiphy1_HdmiQpllParam.
u32 XHdmiphy1_DruGetRefClkFreqHzRaw(XHdmiphy1 *InstancePtr)
This function returns the raw (unconditional) frequency of the DRU reference clock as measured by the clock detector peripheral.
Unlike XHdmiphy1_DruGetRefClkFreqHz, this function always returns the measured value without any range checking - useful for debugging. InstancePtr is a pointer to the XHdmiphy1 core instance. The raw measured frequency of the DRU reference clock. This function returns the actual measured frequency value without range validation. Use this for debugging to see the raw DRU clock measurement independent of expected frequency ranges.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_CLKDET_FREQ_DRU_RAW_REG, XHdmiphy1_ReadReg.
void XHdmiphy1_HdmiDebugInfo(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId)
This function prints Video PHY debug information related to HDMI.
InstancePtr is a pointer to the Hdmiphy core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_Config::DruIsPresent, XHdmiphy1::HdmiRxDruIsEnabled, XHdmiphy1::Quads, XHdmiphy1_Config::RxClkPrimitive, XHdmiphy1_Channel::RxDataRefClkSel, XHdmiphy1_Quad::RxMmcm, XHdmiphy1_Channel::RxOutDiv, XHdmiphy1_Config::TxClkPrimitive, XHdmiphy1_Channel::TxDataRefClkSel, XHdmiphy1_Quad::TxMmcm, XHdmiphy1_Channel::TxOutDiv, XHDMIPHY1_CH2IDX, XHDMIPHY1_DRU_CFREQ_H_REG, XHDMIPHY1_DRU_CFREQ_L_REG, XHDMIPHY1_DRU_GAIN_G1_MASK, XHDMIPHY1_DRU_GAIN_G1_P_MASK, XHDMIPHY1_DRU_GAIN_G1_P_SHIFT, XHDMIPHY1_DRU_GAIN_G2_MASK, XHDMIPHY1_DRU_GAIN_G2_SHIFT, XHDMIPHY1_DRU_GAIN_REG, XHdmiphy1_DruGetVersion, XHDMIPHY1_GT_STATE_ALIGN, XHDMIPHY1_GT_STATE_GPO_RE, XHDMIPHY1_GT_STATE_IDLE, XHDMIPHY1_GT_STATE_LOCK, XHDMIPHY1_GT_STATE_READY, XHDMIPHY1_GT_STATE_RESET, XHdmiphy1_IsHDMI, XHdmiphy1_IsRxUsingCpll, XHdmiphy1_IsRxUsingQpll, XHdmiphy1_IsTxUsingCpll, XHdmiphy1_IsTxUsingQpll, XHdmiphy1_ReadReg.
void XHdmiphy1_SetHdmiCallback(XHdmiphy1 *InstancePtr, XHdmiphy1_HdmiHandlerType HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs an HDMI callback function for the specified handler type.
InstancePtr is a pointer to the XHdmiphy1 instance. HandlerType is the interrupt handler type which specifies which interrupt event to attach the callback for. CallbackFunc is the address to the callback function. CallbackRef is the user data item that will be passed to the callback function when it is invoked. None. None.
References XHdmiphy1::HdmiRxInitCallback, XHdmiphy1::HdmiRxInitRef, XHdmiphy1::HdmiRxReadyCallback, XHdmiphy1::HdmiRxReadyRef, XHdmiphy1::HdmiTxInitCallback, XHdmiphy1::HdmiTxInitRef, XHdmiphy1::HdmiTxReadyCallback, XHdmiphy1::HdmiTxReadyRef, XHDMIPHY1_HDMI_HANDLER_RXINIT, XHDMIPHY1_HDMI_HANDLER_RXREADY, XHDMIPHY1_HDMI_HANDLER_TXINIT, XHDMIPHY1_HDMI_HANDLER_TXREADY.
u32 XHdmiphy1_Hdmi20Config(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir)
This function will configure the HDMIPHY to HDMI 2.0 mode.
InstancePtr is a pointer to the Hdmiphy core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for RX or TX. XST_SUCCESS if TX parameters set/updated.XST_FAILURE if low resolution video not supported. None.
References XHdmiphy1::Config, XHdmiphy1_Hdmi21Cfg::IsEnabled, XHdmiphy1_Hdmi21Cfg::LineRate, XHdmiphy1_Hdmi21Cfg::NChannels, XHdmiphy1::RxHdmi21Cfg, XHdmiphy1_Config::RxRefClkSel, XHdmiphy1::TxHdmi21Cfg, XHdmiphy1_Config::TxRefClkSel, XHdmiphy1_CfgPllRefClkSel, XHdmiphy1_GetPllType, XHdmiphy1_IntrEnable, XHDMIPHY1_LOG_EVT_TMDS_RECONFIG, XHdmiphy1_LogWrite, XHdmiphy1_MmcmSetClkinsel, XHdmiphy1_WriteCfgRefClkSelReg.
u32 XHdmiphy1_Hdmi21Config(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir, u64 LineRate, u8 NChannels)
This function will configure the GT for HDMI 2.1 operation.
InstancePtr is a pointer to the Hdmiphy core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for RX or TX. LineRate is the line rate for HDMI 2.1 operation. NChannels is the number of channels for HDMI 2.1 operation. XST_SUCCESS if TX parameters set/updated.XST_FAILURE if low resolution video not supported. None.
References XHdmiphy1::Config, XHdmiphy1::HdmiRxRefClkHz, XHdmiphy1::HdmiTxRefClkHz, XHdmiphy1_Hdmi21Cfg::IsEnabled, XHdmiphy1_Hdmi21Cfg::LineRate, XHdmiphy1_Hdmi21Cfg::NChannels, XHdmiphy1_Config::Ppc, XHdmiphy1_Config::RxFrlRefClkSel, XHdmiphy1::RxHdmi21Cfg, XHdmiphy1_Config::RxRefClkSel, XHdmiphy1_Config::TxFrlRefClkSel, XHdmiphy1::TxHdmi21Cfg, XHdmiphy1_Config::TxRefClkSel, XHdmiphy1_CfgPllRefClkSel, XHdmiphy1_Clkout1OBufTdsEnable, XHdmiphy1_ErrorHandler, XHdmiphy1_GetPllType, XHdmiphy1_HdmiRxTimerTimeoutHandler, XHdmiphy1_HdmiTxTimerTimeoutHandler, XHdmiphy1_IntrDisable, XHDMIPHY1_LOG_EVT_FRL_RECONFIG, XHDMIPHY1_LOG_EVT_SPDGRDE_ERR, XHdmiphy1_LogWrite, XHdmiphy1_MmcmLockedMaskEnable, XHdmiphy1_MmcmSetClkinsel, XHdmiphy1_MmcmStart, Xhdmiphy1_RefClkValue, XHdmiphy1_SetHdmiTxParam, XHdmiphy1_WriteCfgRefClkSelReg.
void XHdmiphy1_RegisterDebug(XHdmiphy1 *InstancePtr)
This function prints out Video PHY register and GT Channel and Common DRP register contents.
InstancePtr is a pointer to the Hdmiphy core instance. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1::HdmiIsQpllPresent, XHdmiphy1_Config::RxChannels, XHdmiphy1_Config::TxChannels, XHdmiphy1_Config::XcvrType, XHdmiphy1_DrpRd, XHdmiphy1_ReadReg.
u32 XHdmiphy1_HdmiTxPllParam(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId)
u32 XHdmiphy1_HdmiRxPllParam(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId)
void XHdmiphy1_ClkDetEnable(XHdmiphy1 *InstancePtr, u8 Enable)
This function enables the HDMIPHY's detector peripheral.
InstancePtr is a pointer to the XHdmiphy1 core instance. Enable specifies TRUE/FALSE value to either enable or disable the clock detector respectively. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_CLKDET_CTRL_REG, XHDMIPHY1_CLKDET_CTRL_RUN_MASK, XHdmiphy1_ReadReg, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
void XHdmiphy1_ClkDetTimerClear(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir)
This function clears the clock detector TX/RX timer.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for RX or TX. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_CLKDET_CTRL_REG, XHDMIPHY1_CLKDET_CTRL_RX_TMR_CLR_MASK, XHDMIPHY1_CLKDET_CTRL_TX_TMR_CLR_MASK, XHdmiphy1_ReadReg, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_HdmiRxClkDetFreqChangeHandler, XHdmiphy1_HdmiTxClkDetFreqChangeHandler.
void XHdmiphy1_ClkDetSetFreqLockThreshold(XHdmiphy1 *InstancePtr, u16 ThresholdVal)
This function sets the clock detector frequency lock counter threshold value.
InstancePtr is a pointer to the XHdmiphy1 core instance. ThresholdVal is the threshold value to be set. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_CLKDET_CTRL_FREQ_LOCK_THRESH_SHIFT, XHDMIPHY1_CLKDET_CTRL_REG, XHDMIPHY1_CLKDET_CTRL_RX_FREQ_RST_MASK, XHdmiphy1_ReadReg, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
void XHdmiphy1_ClkDetAccuracyRange(XHdmiphy1 *InstancePtr, u16 ThresholdVal)
This function sets the clock detector accuracy range value.
InstancePtr is a pointer to the XHdmiphy1 core instance. ThresholdVal is the threshold value to be set. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_CLKDET_CTRL_ACCURACY_RANGE_MASK, XHDMIPHY1_CLKDET_CTRL_ACCURACY_RANGE_SHIFT, XHDMIPHY1_CLKDET_CTRL_REG, XHdmiphy1_ReadReg, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
u8 XHdmiphy1_ClkDetCheckFreqZero(XHdmiphy1 *InstancePtr, XHdmiphy1_DirectionType Dir)
This function checks clock detector RX/TX frequency zero indicator bit.
InstancePtr is a pointer to the XHdmiphy1 core instance. Dir is an indicator for RX or TX. - TRUE if zero frequency. FALSE otherwise, if non-zero frequency. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_CLKDET_STAT_RX_FREQ_ZERO_MASK, XHDMIPHY1_CLKDET_STAT_TX_FREQ_ZERO_MASK, XHDMIPHY1_DRU_STAT_REG, XHdmiphy1_ReadReg.
void XHdmiphy1_ClkDetSetFreqTimeout(XHdmiphy1 *InstancePtr, u32 TimeoutVal)
This function sets clock detector frequency lock counter threshold value.
InstancePtr is a pointer to the XHdmiphy1 core instance. TimeoutVal is the timeout value and is normally the system clock frequency. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_CLKDET_FREQ_TMR_TO_REG, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
void XHdmiphy1_ClkDetTimerLoad(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir, u32 TimeoutVal)
This function loads the timer to TX/RX in the clock detector.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for RX or TX. TimeoutVal is the timeout value to store in the clock detector. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_CLKDET_TMR_RX_REG, XHDMIPHY1_CLKDET_TMR_TX_REG, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_HdmiRxClkDetFreqChangeHandler, XHdmiphy1_HdmiTxClkDetFreqChangeHandler.
void XHdmiphy1_DruReset(XHdmiphy1 *InstancePtr, XHdmiphy1_ChannelId ChId, u8 Reset)
This function resets the DRU in the HDMIPHY.
InstancePtr is a pointer to the XHdmiphy1 core instance. ChId is the channel ID to operate on. Reset specifies TRUE/FALSE value to either enable or disable the DRU respectively. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_Ch2Ids, XHDMIPHY1_DRU_CTRL_REG, XHDMIPHY1_DRU_CTRL_RST_MASK, XHdmiphy1_ReadReg, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize, XHdmiphy1_HdmiGtRxResetDoneLockHandler, XHdmiphy1_HdmiRxClkDetFreqChangeHandler.
void XHdmiphy1_DruEnable(XHdmiphy1 *InstancePtr, XHdmiphy1_ChannelId ChId, u8 Enable)
This function enabled/disables the DRU in the HDMIPHY.
InstancePtr is a pointer to the XHdmiphy1 core instance. ChId is the channel ID to operate on. Enable specifies TRUE/FALSE value to either enable or disable the DRU, respectively. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_Ch2Ids, XHDMIPHY1_DRU_CTRL_EN_MASK, XHDMIPHY1_DRU_CTRL_REG, XHdmiphy1_ReadReg, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize, XHdmiphy1_HdmiRxClkDetFreqChangeHandler, XHdmiphy1_HdmiRxTimerTimeoutHandler.
u16 XHdmiphy1_DruGetVersion(XHdmiphy1 *InstancePtr)
This function gets the DRU version.
InstancePtr is a pointer to the XHdmiphy1 core instance. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_DRU_STAT_REG, XHDMIPHY1_DRU_STAT_VERSION_MASK, XHDMIPHY1_DRU_STAT_VERSION_SHIFT, XHdmiphy1_ReadReg.
Referenced by XHdmiphy1_HdmiDebugInfo.
void XHdmiphy1_DruSetCenterFreqHz(XHdmiphy1 *InstancePtr, XHdmiphy1_ChannelId ChId, u64 CenterFreqHz)
This function sets the DRU center frequency.
InstancePtr is a pointer to the XHdmiphy1 core instance. ChId specifies the channel ID. CenterFreqHz is the frequency value to set. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_Ch2Ids, XHDMIPHY1_DRU_CFREQ_H_MASK, XHDMIPHY1_DRU_CFREQ_H_REG, XHDMIPHY1_DRU_CFREQ_L_REG, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_SetHdmiRxParam.
u64 XHdmiphy1_DruCalcCenterFreqHz(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId)
This function calculates the center frequency value for the DRU.
InstancePtr is a pointer to the XHdmiphy1 GT core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. The calculated DRU Center frequency value. According to XAPP1240: Center_f = fDIN * (2^32)/fdruclk The DRU clock is derived from the measured reference clock and the current QPLL settings.
References XHdmiphy1::Quads, XHdmiphy1_Channel::RxOutDiv, XHDMIPHY1_CH2IDX, XHdmiphy1_ClkDetGetRefClkFreqHz, XHdmiphy1_DruGetRefClkFreqHz.
Referenced by XHdmiphy1_SetHdmiRxParam.
void XHdmiphy1_HdmiGtDruModeEnable(XHdmiphy1 *InstancePtr, u8 Enable)
This function sets the GT RX CDR and Equalization for DRU mode.
InstancePtr is a pointer to the XHdmiphy1 core instance. Enable enables the DRU logic (when 1), or disables (when 0). None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_Ch2Ids, XHDMIPHY1_LOG_EVT_DRU_EN, XHdmiphy1_LogWrite, XHdmiphy1_ReadReg, XHDMIPHY1_RX_EQ_CDR_REG, XHDMIPHY1_RX_STATUS_RXCDRHOLD_MASK, XHDMIPHY1_RX_STATUS_RXLPMHFOVRDEN_MASK, XHDMIPHY1_RX_STATUS_RXLPMLFKLOVRDEN_MASK, XHDMIPHY1_RX_STATUS_RXOSOVRDEN_MASK, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_HdmiRxTimerTimeoutHandler.
void XHdmiphy1_PatgenSetRatio(XHdmiphy1 *InstancePtr, u8 QuadId, u64 TxLineRate)
This function sets the Pattern Generator for the GT Channel 4 when it is used to generate the TX TMDS Clock.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. TxLineRate in Mbps. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1::HdmiTxSampleRate, XHDMIPHY1_PATGEN_CTRL_RATIO_MASK, XHDMIPHY1_PATGEN_CTRL_REG, XHDMIPHY1_Patgen_Ratio_40, XHdmiphy1_ReadReg, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_HdmiGtTxResetDoneLockHandler.
void XHdmiphy1_PatgenEnable(XHdmiphy1 *InstancePtr, u8 QuadId, u8 Enable)
This function enables or disables the Pattern Generator for the GT Channel 4 when it isused to generate the TX TMDS Clock.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Enable TRUE/FALSE None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_PATGEN_CTRL_ENABLE_MASK, XHDMIPHY1_PATGEN_CTRL_REG, XHdmiphy1_ReadReg, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_HdmiGtTxResetDoneLockHandler, XHdmiphy1_HdmiTxClkDetFreqChangeHandler.
void XHdmiphy1_HdmiIntrHandlerCallbackInit(XHdmiphy1 *InstancePtr)
This function sets the appropriate HDMI interrupt handlers.
InstancePtr is a pointer to the HDMIPHY instance. None. None.
References XHdmiphy1_SetIntrHandler.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
void XHdmiphy1_Ch2Ids(XHdmiphy1 *InstancePtr, XHdmiphy1_ChannelId ChId, u8 *Id0, u8 *Id1)
This function will set the channel IDs to correspond with the supplied channel ID based on the protocol.
HDMI uses 3 channels; This ID translation is done to allow other functions to operate iteratively over multiple channels. InstancePtr is a pointer to the XHdmiphy1 core instance. ChId is the channel ID used to determine the indices. Id0 is a pointer to the start channel ID to set. Id1 is a pointer to the end channel ID to set. None. The contents of Id0 and Id1 will be set according to ChId.
References XHdmiphy1::Config, XHdmiphy1_Config::RxChannels, XHdmiphy1_Config::RxProtocol, XHdmiphy1_Config::TxChannels, XHdmiphy1_Config::TxProtocol, XHdmiphy1_Config::UseGtAsTxTmdsClk, XHdmiphy1_Config::XcvrType, XHdmiphy1_IsHDMI.
u32 XHdmiphy1_DirReconfig(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir)
This function will set the current RX/TX configuration over DRP.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID for which to write the settings for. Dir is an indicator for RX or TX. XST_SUCCESS if the configuration was successful.XST_FAILURE otherwise. None.
References XHdmiphy1_Ch2Ids, XHDMIPHY1_LOG_EVT_GT_RX_RECONFIG, XHDMIPHY1_LOG_EVT_GT_TX_RECONFIG, XHdmiphy1_LogWrite, XHdmiphy1_RxChReconfig, XHdmiphy1_TxChReconfig.
Referenced by XHdmiphy1_HdmiRxTimerTimeoutHandler, XHdmiphy1_HdmiTxTimerTimeoutHandler.
XHdmiphy1_SysClkDataSelType XHdmiphy1_Pll2SysClkData(XHdmiphy1_PllType PllSelect)
This function will translate from XHdmiphy1_PllType to XHdmiphy1_SysClkDataSelType.
PllSelect is the PLL type to translate. The reference clock type based on the PLL selection. None.
Referenced by XHdmiphy1_PllInitialize.
XHdmiphy1_SysClkOutSelType XHdmiphy1_Pll2SysClkOut(XHdmiphy1_PllType PllSelect)
This function will translate from XHdmiphy1_PllType to XHdmiphy1_SysClkOutSelType.
PllSelect is the PLL type to translate. The reference clock type based on the PLL selection. None.
Referenced by XHdmiphy1_PllInitialize.
u32 XHdmiphy1_PllCalculator(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir, u32 PllClkInFreqHz)
This function will try to find the necessary PLL divisor values to produce the configured line rate given the specified PLL input frequency.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to calculate the PLL values for. ChId is the channel ID to calculate the PLL values for. Dir is an indicator for TX or RX. PllClkInFreqHz is the PLL input frequency on which to base the calculations on. A value of 0 indicates to use the currently configured quad PLL reference clock. A non-zero value indicates to ignore what is currently configured in SW, and use a custom frequency instead. XST_SUCCESS if valid PLL values were found to satisfy the constraints.XST_FAILURE otherwise. If successful, the channel's PllParams structure will be modified with the valid PLL parameters.
References XHdmiphy1_Channel::LineRateHz, XHdmiphy1::Quads, XHdmiphy1_CfgSetCdr, XHdmiphy1_Ch2Ids, XHDMIPHY1_CH2IDX, XHdmiphy1_CheckPllOpRange, XHdmiphy1_GetQuadRefClkFreq, XHDMIPHY1_ISCH, XHDMIPHY1_ISCMN.
Referenced by XHdmiphy1_ClkCalcParams.
u32 XHdmiphy1_WriteCfgRefClkSelReg(XHdmiphy1 *InstancePtr, u8 QuadId)
This function writes the current software configuration for the reference clock selections to hardware for the specified quad on all channels.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. XST_SUCCESS. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_Channel::CpllRefClkSel, XHdmiphy1::Quads, XHdmiphy1_Channel::RxDataRefClkSel, XHdmiphy1_Channel::RxOutRefClkSel, XHdmiphy1_Channel::TxDataRefClkSel, XHdmiphy1_Channel::TxOutRefClkSel, XHdmiphy1_Config::XcvrType, XHDMIPHY1_REF_CLK_SEL_CPLL_MASK, XHDMIPHY1_REF_CLK_SEL_CPLL_SHIFT, XHDMIPHY1_REF_CLK_SEL_QPLL0_MASK, XHDMIPHY1_REF_CLK_SEL_QPLL1_MASK, XHDMIPHY1_REF_CLK_SEL_QPLL1_SHIFT, XHDMIPHY1_REF_CLK_SEL_REG, XHDMIPHY1_REF_CLK_SEL_RXSYSCLKSEL_DATA_MASK, XHDMIPHY1_REF_CLK_SEL_RXSYSCLKSEL_DATA_SHIFT, XHDMIPHY1_REF_CLK_SEL_RXSYSCLKSEL_OUT_MASK, XHDMIPHY1_REF_CLK_SEL_RXSYSCLKSEL_OUT_SHIFT, XHDMIPHY1_REF_CLK_SEL_SYSCLKSEL_MASK, XHDMIPHY1_REF_CLK_SEL_TXSYSCLKSEL_DATA_MASK, XHDMIPHY1_REF_CLK_SEL_TXSYSCLKSEL_DATA_SHIFT, XHDMIPHY1_REF_CLK_SEL_TXSYSCLKSEL_OUT_MASK, XHDMIPHY1_REF_CLK_SEL_TXSYSCLKSEL_OUT_SHIFT, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi20Config, XHdmiphy1_Hdmi21Config, XHdmiphy1_HdmiRxTimerTimeoutHandler, XHdmiphy1_HdmiTxTimerTimeoutHandler, XHdmiphy1_PllInitialize, XHdmiphy1_SetHdmiRxParam, XHdmiphy1_SetHdmiTxParam.
void XHdmiphy1_CfgPllRefClkSel(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_PllRefClkSelType RefClkSel)
Configure the PLL reference clock selection for the specified channel(s).
This is applied to both direction to the software configuration only. InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. RefClkSel is the reference clock selection to configure. None. None.
References XHdmiphy1::Quads, XHdmiphy1_Ch2Ids, XHDMIPHY1_CH2IDX.
Referenced by XHdmiphy1_Hdmi20Config, XHdmiphy1_Hdmi21Config, XHdmiphy1_HdmiRxTimerTimeoutHandler, XHdmiphy1_PllInitialize.
void XHdmiphy1_CfgSysClkDataSel(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir, XHdmiphy1_SysClkDataSelType SysClkDataSel)
Configure the SYSCLKDATA reference clock selection for the direction.
Same configuration applies to all channels in the quad. This is applied to the software configuration only. InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. SysClkDataSel is the reference clock selection to configure. None. None.
References XHdmiphy1::Quads, XHdmiphy1_Ch2Ids, XHDMIPHY1_CH2IDX.
Referenced by XHdmiphy1_HdmiQpllParam, XHdmiphy1_PllInitialize.
void XHdmiphy1_CfgSysClkOutSel(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir, XHdmiphy1_SysClkOutSelType SysClkOutSel)
Configure the SYSCLKOUT reference clock selection for the direction.
Same configuration applies to all channels in the quad. This is applied to the software configuration only. InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. SysClkOutSel is the reference clock selection to configure. None. None.
References XHdmiphy1::Quads, XHdmiphy1_Ch2Ids, XHDMIPHY1_CH2IDX.
Referenced by XHdmiphy1_HdmiQpllParam, XHdmiphy1_PllInitialize.
u32 XHdmiphy1_ClkCalcParams(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir, u32 PllClkInFreqHz)
This function will try to find the necessary PLL divisor values to produce the configured line rate given the specified PLL input frequency.
This will be done for all channels specified by ChId. This function is a wrapper for XHdmiphy1_PllCalculator. InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to calculate the PLL values for. ChId is the channel ID to calculate the PLL values for. Dir is an indicator for TX or RX. PllClkInFreqHz is the PLL input frequency on which to base the calculations on. A value of 0 indicates to use the currently configured quad PLL reference clock. A non-zero value indicates to ignore what is currently configured in SW, and use a custom frequency instead. XST_SUCCESS if valid PLL values were found to satisfy the constraints.XST_FAILURE otherwise. If successful, the channel's PllParams structure will be modified with the valid PLL parameters.
References XHdmiphy1_Ch2Ids, XHdmiphy1_PllCalculator.
Referenced by XHdmiphy1_HdmiCpllParam, XHdmiphy1_HdmiQpllParam.
u32 XHdmiphy1_OutDivReconfig(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir)
This function will set the current output divider configuration over DRP.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID for which to write the settings for. Dir is an indicator for RX or TX. XST_SUCCESS if the configuration was successful.XST_FAILURE otherwise. None.
References XHdmiphy1_Ch2Ids, XHDMIPHY1_ISCH, XHDMIPHY1_LOG_EVT_GT_RX_RECONFIG, XHDMIPHY1_LOG_EVT_GT_TX_RECONFIG, XHdmiphy1_LogWrite, XHdmiphy1_OutDivChReconfig.
Referenced by XHdmiphy1_HdmiRxTimerTimeoutHandler, XHdmiphy1_HdmiTxTimerTimeoutHandler.
u32 XHdmiphy1_ClkReconfig(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId)
This function will set the current clocking settings for each channel to hardware based on the configuration stored in the driver's instance.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID for which to write the settings for. XST_SUCCESS if the configuration was successful.XST_FAILURE otherwise. None.
References XHdmiphy1::HdmiIsQpllPresent, XHdmiphy1_Ch2Ids, XHdmiphy1_ClkChReconfig, XHdmiphy1_ClkCmnReconfig, XHdmiphy1_ErrorHandler, XHDMIPHY1_ISCH, XHDMIPHY1_ISCMN, XHdmiphy1_IsHDMI, XHDMIPHY1_LOG_EVT_CPLL_RECONFIG, XHDMIPHY1_LOG_EVT_NO_QPLL_ERR, XHDMIPHY1_LOG_EVT_QPLL_RECONFIG, XHdmiphy1_LogWrite.
Referenced by XHdmiphy1_HdmiRxTimerTimeoutHandler, XHdmiphy1_HdmiTxTimerTimeoutHandler.
XHdmiphy1_ChannelId XHdmiphy1_GetRcfgChId(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir, XHdmiphy1_PllType PllType)
Obtain the reconfiguration channel ID for given PLL type.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. PllType is the PLL type being used by the channel. The Channel ID to be used for reconfiguration None.
Referenced by XHdmiphy1_HdmiCpllLockHandler, XHdmiphy1_HdmiGtTxResetDoneLockHandler, XHdmiphy1_HdmiQpllLockHandler, XHdmiphy1_HdmiRxTimerTimeoutHandler, XHdmiphy1_HdmiTxTimerTimeoutHandler, XHdmiphy1_SetHdmiRxParam.
u32 XHdmiphy1_IsPllLocked(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId)
This function will check the status of a PLL lock on the specified channel.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID which to operate on. XST_SUCCESS if the specified PLL is locked.XST_FAILURE otherwise. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_GetPllType, XHdmiphy1_IsHDMI, XHDMIPHY1_PLL_LOCK_STATUS_CPLL_ALL_MASK, XHDMIPHY1_PLL_LOCK_STATUS_CPLL_HDMI_MASK, XHDMIPHY1_PLL_LOCK_STATUS_CPLL_MASK, XHDMIPHY1_PLL_LOCK_STATUS_LCPLL_MASK, XHDMIPHY1_PLL_LOCK_STATUS_QPLL0_MASK, XHDMIPHY1_PLL_LOCK_STATUS_QPLL1_MASK, XHDMIPHY1_PLL_LOCK_STATUS_REG, XHDMIPHY1_PLL_LOCK_STATUS_RPLL_MASK, XHdmiphy1_ReadReg.
Referenced by XHdmiphy1_HdmiCpllLockHandler, XHdmiphy1_HdmiQpllLockHandler.
u32 XHdmiphy1_GetQuadRefClkFreq(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_PllRefClkSelType RefClkType)
Obtain the current reference clock frequency for the quad based on the reference clock type.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. RefClkType is the type to obtain the clock selection for. The current reference clock frequency for the quad for the specified type selection. None.
References XHdmiphy1::Quads.
Referenced by XHdmiphy1_GetPllVcoFreqHz, XHdmiphy1_PllCalculator.
XHdmiphy1_SysClkDataSelType XHdmiphy1_GetSysClkDataSel(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir, XHdmiphy1_ChannelId ChId)
Obtain the current [RT]XSYSCLKSEL[0] configuration.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. ChId is the channel ID which to operate on. The current [RT]XSYSCLKSEL[0] selection. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_Config::XcvrType, XHdmiphy1_ReadReg, XHDMIPHY1_REF_CLK_SEL_REG, XHDMIPHY1_REF_CLK_SEL_RXSYSCLKSEL_DATA_MASK, XHDMIPHY1_REF_CLK_SEL_RXSYSCLKSEL_DATA_SHIFT, XHDMIPHY1_REF_CLK_SEL_TXSYSCLKSEL_DATA_MASK, XHDMIPHY1_REF_CLK_SEL_TXSYSCLKSEL_DATA_SHIFT.
Referenced by XHdmiphy1_GetPllType.
XHdmiphy1_SysClkOutSelType XHdmiphy1_GetSysClkOutSel(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir, XHdmiphy1_ChannelId ChId)
Obtain the current [RT]XSYSCLKSEL[1] configuration.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. ChId is the channel ID which to operate on. The current [RT]XSYSCLKSEL[1] selection. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_Config::XcvrType, XHdmiphy1_ReadReg, XHDMIPHY1_REF_CLK_SEL_REG, XHDMIPHY1_REF_CLK_SEL_RXSYSCLKSEL_OUT_MASK, XHDMIPHY1_REF_CLK_SEL_RXSYSCLKSEL_OUT_SHIFT, XHDMIPHY1_REF_CLK_SEL_TXSYSCLKSEL_OUT_MASK, XHDMIPHY1_REF_CLK_SEL_TXSYSCLKSEL_OUT_SHIFT.
Referenced by XHdmiphy1_GetPllType.
u32 XHdmiphy1_GtUserRdyEnable(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir, u8 Hold)
This function will reset and enable the Video PHY's user core logic.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID which to operate on. Dir is an indicator for TX or RX. Hold is an indicator whether to "hold" the reset if set to 1. If set to 0: reset, then enable. XST_SUCCESS. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_ReadReg, XHDMIPHY1_RX_INIT_REG, XHDMIPHY1_RX_INIT_USERRDY_ALL_MASK, XHDMIPHY1_RX_INIT_USERRDY_MASK, XHDMIPHY1_TX_INIT_REG, XHDMIPHY1_TX_INIT_USERRDY_ALL_MASK, XHDMIPHY1_TX_INIT_USERRDY_MASK, XHdmiphy1_WriteReg.
u32 XHdmiphy1_Gthe4CfgCpllCalPeriodandTol(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir, u32 FreeRunClkFreq)
u32 XHdmiphy1_Gtye4CfgCpllCalPeriodandTol(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir, u32 FreeRunClkFreq)
u32 XHdmiphy1_MmcmWriteParameters(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir)
u32 XHdmiphy1_DpllWriteParameters(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir)
void XHdmiphy1_MmcmReset(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir, u8 Hold)
This function will reset the mixed-mode clock manager (MMCM) core.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. Hold is an indicator whether to "hold" the reset if set to 1. If set to 0: reset, then enable. XST_SUCCESS. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_MMCM_RXUSRCLK_CTRL_REG, XHDMIPHY1_MMCM_TXUSRCLK_CTRL_REG, XHDMIPHY1_MMCM_USRCLK_CTRL_RST_MASK, XHdmiphy1_ReadReg, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize, XHdmiphy1_MmcmStart.
void XHdmiphy1_MmcmLockedMaskEnable(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir, u8 Enable)
This function will reset the mixed-mode clock manager (MMCM) core.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. Enable is an indicator whether to "Enable" the locked mask if set to 1. If set to 0: reset, then disable. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_MMCM_RXUSRCLK_CTRL_REG, XHDMIPHY1_MMCM_TXUSRCLK_CTRL_REG, XHDMIPHY1_MMCM_USRCLK_CTRL_LOCKED_MASK_MASK, XHdmiphy1_ReadReg, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi21Config, XHdmiphy1_HdmiRxClkDetFreqChangeHandler, XHdmiphy1_HdmiTxClkDetFreqChangeHandler, XHdmiphy1_MmcmStart.
u8 XHdmiphy1_MmcmLocked(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir)
This function will get the lock status of the mixed-mode clock manager (MMCM) core.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. TRUE if Locked else FALSE. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_MMCM_RXUSRCLK_CTRL_REG, XHDMIPHY1_MMCM_TXUSRCLK_CTRL_REG, XHDMIPHY1_MMCM_USRCLK_CTRL_LOCKED_MASK, XHdmiphy1_ReadReg.
void XHdmiphy1_MmcmSetClkinsel(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir, XHdmiphy1_MmcmClkinsel Sel)
This function will set the CLKINSEL port of the MMCM.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. Sel CLKINSEL value 0 - CLKIN1 1 - CLKIN2 None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_MMCM_RXUSRCLK_CTRL_REG, XHDMIPHY1_MMCM_TXUSRCLK_CTRL_REG, XHDMIPHY1_MMCM_USRCLK_CTRL_CLKINSEL_MASK, XHdmiphy1_ReadReg, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi20Config, XHdmiphy1_Hdmi21Config, XHdmiphy1_HdmiRxTimerTimeoutHandler.
void XHdmiphy1_SetBufgGtDiv(XHdmiphy1 *InstancePtr, XHdmiphy1_DirectionType Dir, u8 Div)
This function obtains the divider value of the BUFG_GT peripheral.
InstancePtr is a pointer to the XHdmiphy1 core instance. Dir is an indicator for TX or RX Div 3-bit divider value None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_BUFGGT_RXUSRCLK_REG, XHDMIPHY1_BUFGGT_TXUSRCLK_REG, XHDMIPHY1_BUFGGT_XXUSRCLK_DIV_MASK, XHDMIPHY1_BUFGGT_XXUSRCLK_DIV_SHIFT, XHdmiphy1_ReadReg, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize, XHdmiphy1_HdmiTxTimerTimeoutHandler.
u32 XHdmiphy1_PowerDownGtPll(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, u8 Hold)
This function will power down the specified GT PLL.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to power down the PLL for. Hold is an indicator whether to "hold" the power down if set to 1. If set to 0: power down, then power back up. XST_SUCCESS. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_Ch2Ids, XHDMIPHY1_ISCH, XHDMIPHY1_POWERDOWN_CONTROL_CPLLPD_MASK, XHDMIPHY1_POWERDOWN_CONTROL_QPLL0PD_MASK, XHDMIPHY1_POWERDOWN_CONTROL_QPLL1PD_MASK, XHDMIPHY1_POWERDOWN_CONTROL_REG, XHdmiphy1_ReadReg, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize, XHdmiphy1_HdmiRxClkDetFreqChangeHandler, XHdmiphy1_HdmiRxTimerTimeoutHandler, XHdmiphy1_HdmiTxClkDetFreqChangeHandler, XHdmiphy1_HdmiTxTimerTimeoutHandler.
void XHdmiphy1_SetIntrHandler(XHdmiphy1 *InstancePtr, XHdmiphy1_IntrHandlerType HandlerType, XHdmiphy1_IntrHandler CallbackFunc, void *CallbackRef)
This function installs a callback function for the specified handler type.
InstancePtr is a pointer to the XHdmiphy1 instance. HandlerType is the interrupt handler type which specifies which interrupt event to attach the callback for. CallbackFunc is the address to the callback function. CallbackRef is the user data item that will be passed to the callback function when it is invoked. None. None.
References XHdmiphy1::IntrCpllLockCallbackRef, XHdmiphy1::IntrCpllLockHandler, XHdmiphy1::IntrQpll1LockCallbackRef, XHdmiphy1::IntrQpll1LockHandler, XHdmiphy1::IntrQpllLockCallbackRef, XHdmiphy1::IntrQpllLockHandler, XHdmiphy1::IntrRxClkDetFreqChangeCallbackRef, XHdmiphy1::IntrRxClkDetFreqChangeHandler, XHdmiphy1::IntrRxMmcmLockCallbackRef, XHdmiphy1::IntrRxMmcmLockHandler, XHdmiphy1::IntrRxResetDoneCallbackRef, XHdmiphy1::IntrRxResetDoneHandler, XHdmiphy1::IntrRxTmrTimeoutCallbackRef, XHdmiphy1::IntrRxTmrTimeoutHandler, XHdmiphy1::IntrTxAlignDoneCallbackRef, XHdmiphy1::IntrTxAlignDoneHandler, XHdmiphy1::IntrTxClkDetFreqChangeCallbackRef, XHdmiphy1::IntrTxClkDetFreqChangeHandler, XHdmiphy1::IntrTxMmcmLockCallbackRef, XHdmiphy1::IntrTxMmcmLockHandler, XHdmiphy1::IntrTxResetDoneCallbackRef, XHdmiphy1::IntrTxResetDoneHandler, XHdmiphy1::IntrTxTmrTimeoutCallbackRef, XHdmiphy1::IntrTxTmrTimeoutHandler.
Referenced by XHdmiphy1_HdmiIntrHandlerCallbackInit.
void XHdmiphy1_IntrEnable(XHdmiphy1 *InstancePtr, XHdmiphy1_IntrHandlerType Intr)
This function enables interrupts associated with the specified interrupt type.
InstancePtr is a pointer to the XHdmiphy1 instance. Intr is the interrupt type/mask to enable. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_INTR_EN_REG, XHdmiphy1_ReadReg, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi20Config, XHdmiphy1_Hdmi_CfgInitialize.
void XHdmiphy1_IntrDisable(XHdmiphy1 *InstancePtr, XHdmiphy1_IntrHandlerType Intr)
This function disables interrupts associated with the specified interrupt type.
InstancePtr is a pointer to the XHdmiphy1 instance. Intr is the interrupt type/mask to disable. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_INTR_DIS_REG, XHdmiphy1_ReadReg, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi21Config, XHdmiphy1_Hdmi_CfgInitialize.
u64 XHdmiphy1_GetPllVcoFreqHz(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir)
This function calculates the PLL VCO operating frequency.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. Dir is an indicator for TX or RX. PLL VCO frequency in Hz None.
References XHdmiphy1::HdmiRxDruIsEnabled, XHdmiphy1::HdmiRxRefClkHz, XHdmiphy1::HdmiTxRefClkHz, XHdmiphy1::Quads, XHDMIPHY1_CH2IDX, XHdmiphy1_DruGetRefClkFreqHz, XHdmiphy1_GetQuadRefClkFreq, XHdmiphy1_IsHDMI.
u8 XHdmiphy1_GetRefClkSourcesCount(XHdmiphy1 *InstancePtr)
This function returns the number of active reference clock sources based in the CFG.
InstancePtr is a pointer to the XHdmiphy1 core instance. No of active REFCLK sources None.
References XHdmiphy1::Config, XHdmiphy1_Config::DruIsPresent, XHdmiphy1_Config::DruRefClkSel, XHdmiphy1_Config::RxFrlRefClkSel, XHdmiphy1_Config::RxProtocol, XHdmiphy1_Config::RxRefClkSel, XHdmiphy1_Config::TxFrlRefClkSel, XHdmiphy1_Config::TxProtocol, XHdmiphy1_Config::TxRefClkSel.
u8 XHdmiphy1_IsHDMI(XHdmiphy1 *InstancePtr, XHdmiphy1_DirectionType Dir)
This function checks if Instance is HDMI 2.0 or HDMI 2.1.
InstancePtr is a pointer to the HDMIPHY instance. Dir is an indicator for RX or TX. TRUE if HDMI 2.0 or 2.1 else FALSE. None.
References XHdmiphy1::Config, XHdmiphy1_Config::RxProtocol, XHdmiphy1_Config::TxProtocol.
Referenced by XHdmiphy1_Ch2Ids, XHdmiphy1_ClkReconfig, XHdmiphy1_GetPllVcoFreqHz, XHdmiphy1_Hdmi_CfgInitialize, XHdmiphy1_HdmiDebugInfo, XHdmiphy1_IsPllLocked.
void XHdmiphy1_HdmiTxTimerTimeoutHandler(XHdmiphy1 *InstancePtr)
This function is the handler for TX timer timeout events.
InstancePtr is a pointer to the HDMIPHY instance. None. None.
References XHdmiphy1::Config, XHdmiphy1_Hdmi21Cfg::IsEnabled, XHdmiphy1::Quads, XHdmiphy1::TxHdmi21Cfg, XHdmiphy1_Channel::TxOutDiv, XHdmiphy1_Channel::TxState, XHdmiphy1_Config::XcvrType, XHdmiphy1_Ch2Ids, XHDMIPHY1_CH2IDX, XHdmiphy1_ClkReconfig, XHdmiphy1_DirReconfig, XHdmiphy1_GetPllType, XHdmiphy1_GetRcfgChId, XHDMIPHY1_GT_STATE_GPO_RE, XHDMIPHY1_GT_STATE_LOCK, XHDMIPHY1_LOG_EVT_TX_TMR, XHdmiphy1_LogWrite, XHdmiphy1_MmcmStart, XHdmiphy1_OutDivReconfig, XHdmiphy1_PowerDownGtPll, XHdmiphy1_ResetGtPll, XHdmiphy1_SetBufgGtDiv, XHdmiphy1_TxAlignStart, XHdmiphy1_WriteCfgRefClkSelReg.
Referenced by XHdmiphy1_Hdmi21Config.
void XHdmiphy1_HdmiRxTimerTimeoutHandler(XHdmiphy1 *InstancePtr)
This function is the handler for RX timer timeout events.
InstancePtr is a pointer to the HDMIPHY instance. None. None.
References XHdmiphy1::Config, XHdmiphy1_Config::DruRefClkSel, XHdmiphy1::HdmiRxDruIsEnabled, XHdmiphy1_Hdmi21Cfg::IsEnabled, XHdmiphy1::Quads, XHdmiphy1_Config::RxFrlRefClkSel, XHdmiphy1::RxHdmi21Cfg, XHdmiphy1_Config::RxRefClkSel, XHdmiphy1_Channel::RxState, XHdmiphy1_CfgPllRefClkSel, XHdmiphy1_Ch2Ids, XHDMIPHY1_CH2IDX, XHdmiphy1_ClkReconfig, XHdmiphy1_DirReconfig, XHdmiphy1_DruEnable, XHdmiphy1_GetPllType, XHdmiphy1_GetRcfgChId, XHDMIPHY1_GT_STATE_GPO_RE, XHDMIPHY1_GT_STATE_IDLE, XHDMIPHY1_GT_STATE_LOCK, XHdmiphy1_HdmiGtDruModeEnable, XHDMIPHY1_LOG_EVT_RX_TMR, XHdmiphy1_LogWrite, XHdmiphy1_MmcmSetClkinsel, XHdmiphy1_MmcmStart, XHdmiphy1_OutDivReconfig, XHdmiphy1_PowerDownGtPll, XHdmiphy1_ResetGtPll, XHdmiphy1_SetHdmiRxParam, XHdmiphy1_WriteCfgRefClkSelReg.
Referenced by XHdmiphy1_Hdmi21Config.
void XHdmiphy1_ErrorHandler(XHdmiphy1 *InstancePtr)
This function is the error condition handler.
InstancePtr is a pointer to the HDMIPHY instance. None. None.
References XHdmiphy1::ErrorCallback, XHdmiphy1::ErrorRef.
Referenced by XHdmiphy1_ClkReconfig, XHdmiphy1_Hdmi21Config, XHdmiphy1_HdmiCfgCalcMmcmParam, XHdmiphy1_HdmiCpllParam, XHdmiphy1_HdmiQpllParam, XHdmiphy1_SetHdmiTxParam.
XV_HDMIPHY1_LOG_ENABLE
XPAR_HDMIPHY1_0_TRANSCEIVER
XPAR_HDMIPHY1_0_SPEEDGRADE_STR
XHDMIPHY1_GTHE4
XHDMIPHY1_GTYE4
XHDMIPHY1_GTYE5
XHDMIPHY1_GTYP
XHDMIPHY1_CH2IDX
Convert channel ID to array index.
This macro converts a channel ID to the corresponding array index by subtracting the base channel ID. Id Channel ID to convert. Array index corresponding to the channel ID.
Referenced by XHdmiphy1_CfgLineRate, XHdmiphy1_CfgPllRefClkSel, XHdmiphy1_CfgSysClkDataSel, XHdmiphy1_CfgSysClkOutSel, XHdmiphy1_DruCalcCenterFreqHz, XHdmiphy1_GetPllVcoFreqHz, XHdmiphy1_Hdmi_CfgInitialize, XHdmiphy1_HdmiCpllLockHandler, XHdmiphy1_HdmiCpllParam, XHdmiphy1_HdmiDebugInfo, XHdmiphy1_HdmiGtRxResetDoneLockHandler, XHdmiphy1_HdmiGtTxAlignDoneLockHandler, XHdmiphy1_HdmiGtTxResetDoneLockHandler, XHdmiphy1_HdmiQpllLockHandler, XHdmiphy1_HdmiQpllParam, XHdmiphy1_HdmiRxClkDetFreqChangeHandler, XHdmiphy1_HdmiRxTimerTimeoutHandler, XHdmiphy1_HdmiTxClkDetFreqChangeHandler, XHdmiphy1_HdmiTxTimerTimeoutHandler, XHdmiphy1_HdmiUpdateClockSelection, XHdmiphy1_PllCalculator.
XHDMIPHY1_ISCH
Check if channel ID is a regular channel.
This macro checks if the given channel ID represents a regular channel (channel A or channels 1-4). Id Channel ID to check. Non-zero if the ID is a regular channel, 0 otherwise.
Referenced by XHdmiphy1_ClkReconfig, XHdmiphy1_OutDivReconfig, XHdmiphy1_PllCalculator, XHdmiphy1_PowerDownGtPll.
XHDMIPHY1_ISCMN
Check if channel ID is a common channel.
This macro checks if the given channel ID represents a common channel (common channel A or common channels 0-1). Id Channel ID to check. Non-zero if the ID is a common channel, 0 otherwise.
Referenced by XHdmiphy1_ClkReconfig, XHdmiphy1_PllCalculator.
XHDMIPHY1_ISTXMMCM
Check if channel ID is the TX MMCM channel.
This macro checks if the given channel ID represents the transmit MMCM channel. Id Channel ID to check. Non-zero if the ID is the TX MMCM channel, 0 otherwise.
XHDMIPHY1_ISRXMMCM
Check if channel ID is the RX MMCM channel.
This macro checks if the given channel ID represents the receive MMCM channel. Id Channel ID to check. Non-zero if the ID is the RX MMCM channel, 0 otherwise.
XHdmiphy1_IsTxUsingQpll
Check if TX is using QPLL.
This macro checks if the transmit channel is using any QPLL type (QPLL, QPLL0, or QPLL1) for the specified channel. InstancePtr Pointer to the HDMI PHY instance. QuadId Quad ID. ChId Channel ID. Non-zero if TX is using QPLL, 0 otherwise.
Referenced by XHdmiphy1_Hdmi_CfgInitialize, XHdmiphy1_HdmiDebugInfo.
XHdmiphy1_IsRxUsingQpll
Check if RX is using QPLL.
This macro checks if the receive channel is using any QPLL type (QPLL, QPLL0, or QPLL1) for the specified channel. InstancePtr Pointer to the HDMI PHY instance. QuadId Quad ID. ChId Channel ID. Non-zero if RX is using QPLL, 0 otherwise.
Referenced by XHdmiphy1_Hdmi_CfgInitialize, XHdmiphy1_HdmiDebugInfo.
XHdmiphy1_IsTxUsingCpll
Check if TX is using CPLL.
This macro checks if the transmit channel is using CPLL for the specified channel. InstancePtr Pointer to the HDMI PHY instance. QuadId Quad ID. ChId Channel ID. Non-zero if TX is using CPLL, 0 otherwise.
Referenced by XHdmiphy1_HdmiDebugInfo, XHdmiphy1_SetHdmiTxParam.
XHdmiphy1_IsRxUsingCpll
Check if RX is using CPLL.
This macro checks if the receive channel is using CPLL for the specified channel. InstancePtr Pointer to the HDMI PHY instance. QuadId Quad ID. ChId Channel ID. Non-zero if RX is using CPLL, 0 otherwise.
Referenced by XHdmiphy1_HdmiDebugInfo, XHdmiphy1_SetHdmiRxParam.
XHdmiphy1_CfgSetCdr
Configure CDR settings (GT adaptor wrapper).
This macro provides a wrapper to call the GT adaptor's CfgSetCdr function. Ip Pointer to the HDMI PHY instance. ... Variable arguments passed to the GT adaptor function. Result from the GT adaptor's CfgSetCdr function.
Referenced by XHdmiphy1_PllCalculator.
XHdmiphy1_CheckPllOpRange
Check PLL operating range (GT adaptor wrapper).
This macro provides a wrapper to call the GT adaptor's CheckPllOpRange function. Ip Pointer to the HDMI PHY instance. ... Variable arguments passed to the GT adaptor function. Result from the GT adaptor's CheckPllOpRange function.
Referenced by XHdmiphy1_PllCalculator.
XHdmiphy1_OutDivChReconfig
Reconfigure output divider for channel (GT adaptor wrapper).
This macro provides a wrapper to call the GT adaptor's OutDivChReconfig function. Ip Pointer to the HDMI PHY instance. ... Variable arguments passed to the GT adaptor function. Result from the GT adaptor's OutDivChReconfig function.
Referenced by XHdmiphy1_OutDivReconfig.
XHdmiphy1_ClkChReconfig
Reconfigure channel clock (GT adaptor wrapper).
This macro provides a wrapper to call the GT adaptor's ClkChReconfig function. Ip Pointer to the HDMI PHY instance. ... Variable arguments passed to the GT adaptor function. Result from the GT adaptor's ClkChReconfig function.
Referenced by XHdmiphy1_ClkReconfig.
XHdmiphy1_ClkCmnReconfig
Reconfigure common clock (GT adaptor wrapper).
This macro provides a wrapper to call the GT adaptor's ClkCmnReconfig function. Ip Pointer to the HDMI PHY instance. ... Variable arguments passed to the GT adaptor function. Result from the GT adaptor's ClkCmnReconfig function.
Referenced by XHdmiphy1_ClkReconfig.
XHdmiphy1_RxChReconfig
Reconfigure RX channel (GT adaptor wrapper).
This macro provides a wrapper to call the GT adaptor's RxChReconfig function. Ip Pointer to the HDMI PHY instance. ... Variable arguments passed to the GT adaptor function. Result from the GT adaptor's RxChReconfig function.
Referenced by XHdmiphy1_DirReconfig.
XHdmiphy1_TxChReconfig
Reconfigure TX channel (GT adaptor wrapper).
This macro provides a wrapper to call the GT adaptor's TxChReconfig function. Ip Pointer to the HDMI PHY instance. ... Variable arguments passed to the GT adaptor function. Result from the GT adaptor's TxChReconfig function.
Referenced by XHdmiphy1_DirReconfig.
XHDMIPHY1_HDMI_GTYP_DRU_REFCLK
XHDMIPHY1_HDMI_GTYP_DRU_REFCLK_MIN
XHDMIPHY1_HDMI_GTYP_DRU_REFCLK_MAX
XHDMIPHY1_HDMI_GTYP_DRU_REFCLK1
XHDMIPHY1_HDMI_GTYP_DRU_REFCLK1_MIN
XHDMIPHY1_HDMI_GTYP_DRU_REFCLK1_MAX
XHDMIPHY1_HDMI_GTYP_DRU_REFCLK2
XHDMIPHY1_HDMI_GTYP_DRU_REFCLK2_MIN
XHDMIPHY1_HDMI_GTYP_DRU_REFCLK2_MAX
XHDMIPHY1_HDMI_GTYE5_DRU_LRATE
XHDMIPHY1_HDMI_GTYE5_DRU_REFCLK
XHDMIPHY1_HDMI_GTYE5_DRU_REFCLK_MIN
XHDMIPHY1_HDMI_GTYE5_DRU_REFCLK_MAX
XHDMIPHY1_HDMI_GTYE5_DRU_REFCLK1
XHDMIPHY1_HDMI_GTYE5_DRU_REFCLK1_MIN
XHDMIPHY1_HDMI_GTYE5_DRU_REFCLK1_MAX
XHDMIPHY1_HDMI_GTYE5_DRU_REFCLK2
XHDMIPHY1_HDMI_GTYE5_DRU_REFCLK2_MIN
XHDMIPHY1_HDMI_GTYE5_DRU_REFCLK2_MAX
XHDMIPHY1_HDMI_GTYE5_PLL_SCALE
XHDMIPHY1_HDMI_GTYE5_LCPLL_REFCLK_MIN
XHDMIPHY1_HDMI_GTYE5_RPLL_REFCLK_MIN
XHDMIPHY1_HDMI_GTYE5_TX_MMCM_SCALE
XHDMIPHY1_HDMI_GTYE5_TX_MMCM_FVCO_MIN
XHDMIPHY1_HDMI_GTYE5_TX_MMCM_FVCO_MAX
XHDMIPHY1_HDMI_GTYE5_RX_MMCM_SCALE
XHDMIPHY1_HDMI_GTYE5_RX_MMCM_FVCO_MIN
XHDMIPHY1_HDMI_GTYE5_RX_MMCM_FVCO_MAX
XHDMIPHY1_HDMI_GTYE4_DRU_LRATE
XHDMIPHY1_HDMI_GTYE4_DRU_REFCLK
XHDMIPHY1_HDMI_GTYE4_DRU_REFCLK_MIN
XHDMIPHY1_HDMI_GTYE4_DRU_REFCLK_MAX
XHDMIPHY1_HDMI_GTYE4_DRU_REFCLK2
XHDMIPHY1_HDMI_GTYE4_DRU_REFCLK2_MIN
XHDMIPHY1_HDMI_GTYE4_DRU_REFCLK2_MAX
XHDMIPHY1_HDMI_GTYE4_DRU_REFCLK3
XHDMIPHY1_HDMI_GTYE4_DRU_REFCLK3_MIN
XHDMIPHY1_HDMI_GTYE4_DRU_REFCLK3_MAX
XHDMIPHY1_HDMI_GTYE4_PLL_SCALE
XHDMIPHY1_HDMI_GTYE4_QPLL0_REFCLK_MIN
XHDMIPHY1_HDMI_GTYE4_QPLL1_REFCLK_MIN
XHDMIPHY1_HDMI_GTYE4_CPLL_REFCLK_MIN
XHDMIPHY1_HDMI_GTYE4_TX_MMCM_SCALE
XHDMIPHY1_HDMI_GTYE4_TX_MMCM_FVCO_MIN
XHDMIPHY1_HDMI_GTYE4_TX_MMCM_FVCO_MAX
XHDMIPHY1_HDMI_GTYE4_RX_MMCM_SCALE
XHDMIPHY1_HDMI_GTYE4_RX_MMCM_FVCO_MIN
XHDMIPHY1_HDMI_GTYE4_RX_MMCM_FVCO_MAX
XHDMIPHY1_HDMI_GTHE4_DRU_LRATE
XHDMIPHY1_HDMI_GTHE4_DRU_REFCLK
XHDMIPHY1_HDMI_GTHE4_DRU_REFCLK_MIN
XHDMIPHY1_HDMI_GTHE4_DRU_REFCLK_MAX
XHDMIPHY1_HDMI_GTHE4_DRU_REFCLK2
XHDMIPHY1_HDMI_GTHE4_DRU_REFCLK2_MIN
XHDMIPHY1_HDMI_GTHE4_DRU_REFCLK2_MAX
XHDMIPHY1_HDMI_GTHE4_DRU_REFCLK3
XHDMIPHY1_HDMI_GTHE4_DRU_REFCLK3_MIN
XHDMIPHY1_HDMI_GTHE4_DRU_REFCLK3_MAX
XHDMIPHY1_HDMI_GTHE4_PLL_SCALE
XHDMIPHY1_HDMI_GTHE4_QPLL0_REFCLK_MIN
XHDMIPHY1_HDMI_GTHE4_QPLL1_REFCLK_MIN
XHDMIPHY1_HDMI_GTHE4_CPLL_REFCLK_MIN
XHDMIPHY1_HDMI_GTHE4_TX_MMCM_SCALE
XHDMIPHY1_HDMI_GTHE4_TX_MMCM_FVCO_MIN
XHDMIPHY1_HDMI_GTHE4_TX_MMCM_FVCO_MAX
XHDMIPHY1_HDMI_GTHE4_RX_MMCM_SCALE
XHDMIPHY1_HDMI_GTHE4_RX_MMCM_FVCO_MIN
XHDMIPHY1_HDMI_GTHE4_RX_MMCM_FVCO_MAX
XHDMIPHY1_FRL_VIDCLK_MMCM_FBOUTMULT
XHDMIPHY1_FRL_VIDCLK_MMCM_DIVCLK
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT0DIV
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT1DIV
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT2DIV
XHDMIPHY1_FRL_VIDCLK_MMCM_FBOUTMULT10
XHDMIPHY1_FRL_VIDCLK_MMCM_DIVCLK10
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT0DIV10
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT1DIV10
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT2DIV10
XHDMIPHY1_FRL_VIDCLK_MMCM_FBOUTMULT8
XHDMIPHY1_FRL_VIDCLK_MMCM_DIVCLK8
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT0DIV8
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT1DIV8
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT2DIV8
XHDMIPHY1_FRL_VIDCLK_MMCM_FBOUTMULT6
XHDMIPHY1_FRL_VIDCLK_MMCM_DIVCLK6
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT0DIV6
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT1DIV6
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT2DIV6
XHDMIPHY1_FRL_VIDCLK_MMCM_FBOUTMULT6x3
XHDMIPHY1_FRL_VIDCLK_MMCM_DIVCLK6x3
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT0DIV6x3
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT1DIV6x3
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT2DIV6x3
XHDMIPHY1_FRL_VIDCLK_MMCM_FBOUTMULT3x3
XHDMIPHY1_FRL_VIDCLK_MMCM_DIVCLK3x3
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT0DIV3x3
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT1DIV3x3
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT2DIV3x3
XHDMIPHY1_RX_CONTROL_RXLPMEN_ALL_MASK
RX LPM enable mask for all channels.
Referenced by XHdmiphy1_SetRxLpm.
XHDMIPHY1_INTR_TXRESETDONE_MASK
TX reset done interrupt mask.
Referenced by XHdmiphy1_InterruptHandler.
XHDMIPHY1_INTR_RXRESETDONE_MASK
RX reset done interrupt mask.
Referenced by XHdmiphy1_InterruptHandler.
XHDMIPHY1_INTR_CPLL_LOCK_MASK
CPLL lock interrupt mask.
Referenced by XHdmiphy1_InterruptHandler.
XHDMIPHY1_INTR_QPLL0_LOCK_MASK
QPLL0 lock interrupt mask.
XHDMIPHY1_INTR_LCPLL_LOCK_MASK
LCPLL lock interrupt mask (alias for QPLL0)
Referenced by XHdmiphy1_InterruptHandler.
XHDMIPHY1_INTR_TXALIGNDONE_MASK
TX alignment done interrupt mask.
Referenced by XHdmiphy1_InterruptHandler.
XHDMIPHY1_INTR_QPLL1_LOCK_MASK
QPLL1 lock interrupt mask.
Referenced by XHdmiphy1_InterruptHandler.
XHDMIPHY1_INTR_RPLL_LOCK_MASK
RPLL lock interrupt mask (alias for QPLL1)
Referenced by XHdmiphy1_InterruptHandler.
XHDMIPHY1_INTR_TXCLKDETFREQCHANGE_MASK
TX clock detector frequency change interrupt mask.
Referenced by XHdmiphy1_InterruptHandler.
XHDMIPHY1_INTR_RXCLKDETFREQCHANGE_MASK
RX clock detector frequency change interrupt mask.
Referenced by XHdmiphy1_InterruptHandler.
XHDMIPHY1_INTR_TXMMCMUSRCLK_LOCK_MASK
TX MMCM user clock lock interrupt mask.
Referenced by XHdmiphy1_InterruptHandler.
XHDMIPHY1_INTR_RXMMCMUSRCLK_LOCK_MASK
RX MMCM user clock lock interrupt mask.
Referenced by XHdmiphy1_InterruptHandler.
XHDMIPHY1_INTR_TXGPO_RE_MASK
TX GPO rising edge interrupt mask.
Referenced by XHdmiphy1_InterruptHandler.
XHDMIPHY1_INTR_RXGPO_RE_MASK
RX GPO rising edge interrupt mask.
Referenced by XHdmiphy1_InterruptHandler.
XHDMIPHY1_INTR_TXTMRTIMEOUT_MASK
TX timer timeout interrupt mask.
Referenced by XHdmiphy1_InterruptHandler.
XHDMIPHY1_INTR_RXTMRTIMEOUT_MASK
RX timer timeout interrupt mask.
Referenced by XHdmiphy1_InterruptHandler.
XHDMIPHY1_INTR_QPLL_LOCK_MASK
QPLL lock interrupt mask (alias for QPLL0)
Referenced by XHdmiphy1_InterruptHandler.
XHDMIPHY1_MMCM_USRCLK_CTRL_CFG_NEW_MASK
MMCM user clock control configuration new mask.
XHDMIPHY1_MMCM_USRCLK_CTRL_RST_MASK
MMCM user clock control reset mask.
Referenced by XHdmiphy1_MmcmReset.
XHDMIPHY1_MMCM_USRCLK_CTRL_CFG_SUCCESS_MASK
MMCM user clock control configuration success mask.
XHDMIPHY1_MMCM_USRCLK_CTRL_LOCKED_MASK
MMCM user clock control locked mask.
Referenced by XHdmiphy1_MmcmLocked.
XHDMIPHY1_MMCM_USRCLK_CTRL_PWRDWN_MASK
MMCM user clock control power down mask.
Referenced by XHdmiphy1_MmcmPowerDown.
XHDMIPHY1_MMCM_USRCLK_CTRL_LOCKED_MASK_MASK
MMCM user clock control locked mask mask.
Referenced by XHdmiphy1_MmcmLockedMaskEnable.
XHDMIPHY1_MMCM_USRCLK_CTRL_CLKINSEL_MASK
MMCM user clock control clock input select mask.
Referenced by XHdmiphy1_MmcmSetClkinsel.
XHDMIPHY1_MMCM_USRCLK_REG1_DIVCLK_MASK
MMCM user clock register 1 divider clock mask.
XHDMIPHY1_MMCM_USRCLK_REG1_CLKFBOUT_MULT_MASK
MMCM user clock register 1 clock feedback output multiplier mask.
XHDMIPHY1_MMCM_USRCLK_REG1_CLKFBOUT_MULT_SHIFT
MMCM user clock register 1 clock feedback output multiplier shift.
XHDMIPHY1_MMCM_USRCLK_REG1_CLKFBOUT_FRAC_MASK
MMCM user clock register 1 clock feedback output fractional mask.
XHDMIPHY1_MMCM_USRCLK_REG1_CLKFBOUT_FRAC_SHIFT
MMCM user clock register 1 clock feedback output fractional shift.
XHDMIPHY1_MMCM_USRCLK_REG2_DIVCLK_MASK
MMCM user clock register 2 divider clock mask.
XHDMIPHY1_MMCM_USRCLK_REG2_CLKOUT0_FRAC_MASK
MMCM user clock register 2 clock output 0 fractional mask.
XHDMIPHY1_MMCM_USRCLK_REG2_CLKOUT0_FRAC_SHIFT
MMCM user clock register 2 clock output 0 fractional shift.
XHDMIPHY1_MMCM_USRCLK_REG34_DIVCLK_MASK
MMCM user clock register 3/4 divider clock mask.
XHDMIPHY1_BUFGGT_XXUSRCLK_CLR_MASK
BUFGGT user clock clear mask.
XHDMIPHY1_BUFGGT_XXUSRCLK_DIV_MASK
BUFGGT user clock divider mask.
Referenced by XHdmiphy1_SetBufgGtDiv.
XHDMIPHY1_BUFGGT_XXUSRCLK_DIV_SHIFT
BUFGGT user clock divider shift.
Referenced by XHdmiphy1_SetBufgGtDiv.
XHDMIPHY1_MISC_XXUSRCLK_CKOUT1_OEN_MASK
Miscellaneous user clock output 1 output enable mask.
Referenced by XHdmiphy1_Clkout1OBufTdsEnable.
XHDMIPHY1_MISC_XXUSRCLK_REFCLK_CEB_MASK
Miscellaneous user clock reference clock CEB (Clock Enable Bar) mask.
Referenced by XHdmiphy1_IBufDsEnable.
XHDMIPHY1_CLKDET_CTRL_RUN_MASK
Clock detector control run mask.
Referenced by XHdmiphy1_ClkDetEnable.
XHDMIPHY1_CLKDET_CTRL_TX_TMR_CLR_MASK
Clock detector control TX timer clear mask.
Referenced by XHdmiphy1_ClkDetTimerClear.
XHDMIPHY1_CLKDET_CTRL_RX_TMR_CLR_MASK
Clock detector control RX timer clear mask.
Referenced by XHdmiphy1_ClkDetTimerClear.
XHDMIPHY1_CLKDET_CTRL_TX_FREQ_RST_MASK
Clock detector control TX frequency reset mask.
Referenced by XHdmiphy1_ClkDetFreqReset.
XHDMIPHY1_CLKDET_CTRL_RX_FREQ_RST_MASK
Clock detector control RX frequency reset mask.
Referenced by XHdmiphy1_ClkDetFreqReset, XHdmiphy1_ClkDetSetFreqLockThreshold.
XHDMIPHY1_CLKDET_CTRL_FREQ_LOCK_THRESH_MASK
Clock detector control frequency lock threshold mask.
XHDMIPHY1_CLKDET_CTRL_FREQ_LOCK_THRESH_SHIFT
Clock detector control frequency lock threshold shift.
Referenced by XHdmiphy1_ClkDetSetFreqLockThreshold.
XHDMIPHY1_CLKDET_CTRL_ACCURACY_RANGE_MASK
Clock detector control accuracy range mask.
Referenced by XHdmiphy1_ClkDetAccuracyRange.
XHDMIPHY1_CLKDET_CTRL_ACCURACY_RANGE_SHIFT
Clock detector control accuracy range shift.
Referenced by XHdmiphy1_ClkDetAccuracyRange.
XHDMIPHY1_CLKDET_STAT_TX_FREQ_ZERO_MASK
Clock detector status TX frequency zero mask.
Referenced by XHdmiphy1_ClkDetCheckFreqZero.
XHDMIPHY1_CLKDET_STAT_RX_FREQ_ZERO_MASK
Clock detector status RX frequency zero mask.
Referenced by XHdmiphy1_ClkDetCheckFreqZero.
XHDMIPHY1_CLKDET_STAT_TX_REFCLK_LOCK_MASK
Clock detector status TX reference clock lock mask.
XHDMIPHY1_CLKDET_STAT_TX_REFCLK_LOCK_CAP_MASK
Clock detector status TX reference clock lock capture mask.
XHDMIPHY1_DRU_CTRL_RST_MASK
DRU control reset mask for specific channel.
Ch Channel number (1-4). DRU control reset mask for the specified channel.
Referenced by XHdmiphy1_DruReset.
XHDMIPHY1_DRU_CTRL_EN_MASK
DRU control enable mask for specific channel.
Ch Channel number (1-4). DRU control enable mask for the specified channel.
Referenced by XHdmiphy1_DruEnable.
XHDMIPHY1_DRU_STAT_ACTIVE_MASK
DRU status active mask for specific channel.
Ch Channel number (1-4). DRU status active mask for the specified channel.
XHDMIPHY1_DRU_STAT_VERSION_MASK
DRU status version mask.
Referenced by XHdmiphy1_DruGetVersion.
XHDMIPHY1_DRU_STAT_VERSION_SHIFT
DRU status version shift.
Referenced by XHdmiphy1_DruGetVersion.
XHDMIPHY1_DRU_CFREQ_H_MASK
DRU center frequency high mask.
Referenced by XHdmiphy1_DruSetCenterFreqHz.
XHDMIPHY1_DRU_GAIN_G1_MASK
DRU gain G1 mask.
Referenced by XHdmiphy1_HdmiDebugInfo.
XHDMIPHY1_DRU_GAIN_G1_SHIFT
DRU gain G1 shift.
XHDMIPHY1_DRU_GAIN_G1_P_MASK
DRU gain G1 P mask.
Referenced by XHdmiphy1_HdmiDebugInfo.
XHDMIPHY1_DRU_GAIN_G1_P_SHIFT
DRU gain G1 P shift.
Referenced by XHdmiphy1_HdmiDebugInfo.
XHDMIPHY1_DRU_GAIN_G2_MASK
DRU gain G2 mask.
Referenced by XHdmiphy1_HdmiDebugInfo.
XHDMIPHY1_DRU_GAIN_G2_SHIFT
DRU gain G2 shift.
Referenced by XHdmiphy1_HdmiDebugInfo.
XHDMIPHY1_PATGEN_CTRL_ENABLE_MASK
PATGEN control enable mask.
Referenced by XHdmiphy1_PatgenEnable.
XHDMIPHY1_PATGEN_CTRL_ENABLE_SHIFT
PATGEN control enable shift.
XHDMIPHY1_PATGEN_CTRL_RATIO_MASK
PATGEN control ratio mask.
Referenced by XHdmiphy1_PatgenSetRatio.
XHDMIPHY1_PATGEN_CTRL_RATIO_SHIFT
PATGEN control ratio shift.