xhdmiphy1_hdmi.c
void XHdmiphy1_Ch2Ids(XHdmiphy1 *InstancePtr, XHdmiphy1_ChannelId ChId, u8 *Id0, u8 *Id1)
This function will set the channel IDs to correspond with the supplied channel ID based on the protocol.
HDMI uses 3 channels; This ID translation is done to allow other functions to operate iteratively over multiple channels. InstancePtr is a pointer to the XHdmiphy1 core instance. ChId is the channel ID used to determine the indices. Id0 is a pointer to the start channel ID to set. Id1 is a pointer to the end channel ID to set. None. The contents of Id0 and Id1 will be set according to ChId.
Referenced by XHdmiphy1_CfgLineRate, XHdmiphy1_CfgPllRefClkSel, XHdmiphy1_CfgSysClkDataSel, XHdmiphy1_CfgSysClkOutSel, XHdmiphy1_ClkCalcParams, XHdmiphy1_ClkReconfig, XHdmiphy1_DirReconfig, XHdmiphy1_DruEnable, XHdmiphy1_DruReset, XHdmiphy1_DruSetCenterFreqHz, XHdmiphy1_Hdmi_CfgInitialize, XHdmiphy1_HdmiCpllLockHandler, XHdmiphy1_HdmiCpllParam, XHdmiphy1_HdmiGtDruModeEnable, XHdmiphy1_HdmiGtRxResetDoneLockHandler, XHdmiphy1_HdmiGtTxAlignDoneLockHandler, XHdmiphy1_HdmiGtTxResetDoneLockHandler, XHdmiphy1_HdmiQpllLockHandler, XHdmiphy1_HdmiQpllParam, XHdmiphy1_HdmiRxClkDetFreqChangeHandler, XHdmiphy1_HdmiRxTimerTimeoutHandler, XHdmiphy1_HdmiTxClkDetFreqChangeHandler, XHdmiphy1_HdmiTxTimerTimeoutHandler, XHdmiphy1_HdmiUpdateClockSelection, XHdmiphy1_OutDivReconfig, XHdmiphy1_PllCalculator, XHdmiphy1_PowerDownGtPll, XHdmiphy1_SetPrbsSel, XHdmiphy1_TxAlignReset, XHdmiphy1_TxAlignStart.
static const XHdmiphy1_GtHdmiChars * GetGtHdmiPtr(XHdmiphy1 *InstancePtr)
This function returns a pointer to the HDMI parameters based on the GT type.
InstancePtr is a pointer to the Hdmiphy core instance. A pointer to the HDMI GT characteristics.NULL if the GT type is unsupported. None.
static void XHdmiphy1_HdmiSetSystemClockSelection(XHdmiphy1 *InstancePtr, u8 QuadId)
This function Sets the System Clock Selection.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. None. None.
static void XHdmiphy1_MmcmParam(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir)
This function sets the MMCM programming values based on Max Rate.
InstancePtr is a pointer to the Hdmiphy core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for RX or TX. None Based on the MAX Rate set in the GUI, the MMCM values are selected. 3 -> Max Rate selected in GUI is 3G 6 -> Max Rate selected in GUI is 6G 8 -> Max Rate selected in GUI is 8G 10 -> Max Rate selected in GUI is 10G 12 -> Max Rate selected in GUI in 12G
u32 XHdmiphy1_Hdmi_CfgInitialize(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_Config *CfgPtr)
This function initializes the Video PHY for HDMI.
InstancePtr is a pointer to the XHdmiphy1 instance. CfgPtr is a pointer to the configuration structure that will be used to copy the settings from. QuadId is the GT quad ID to operate on. None. None.
References XHdmiphy1_LogWrite, XHDMIPHY1_LOG_EVT_INIT, XHdmiphy1_CfgInitialize, XHdmiphy1_Config::BaseAddr, XHdmiphy1_Ch2Ids, XHdmiphy1::Quads, XHDMIPHY1_CH2IDX, XHdmiphy1_Channel::TxState, XHDMIPHY1_GT_STATE_IDLE, XHdmiphy1_Channel::RxState, XHdmiphy1::Config, XHdmiphy1_Config::TransceiverWidth, XHdmiphy1_IntrDisable, XHdmiphy1_HdmiIntrHandlerCallbackInit, XHdmiphy1_ClkDetEnable, XHdmiphy1_ClkDetSetFreqTimeout, XHdmiphy1_Config::AxiLiteClkFreq, XHdmiphy1_ClkDetSetFreqLockThreshold, XHdmiphy1_ClkDetAccuracyRange, XHdmiphy1_LogReset, XHdmiphy1_IsTxUsingQpll, XHdmiphy1_IsHDMI, XHdmiphy1_IsRxUsingQpll, XHdmiphy1::HdmiIsQpllPresent, XHdmiphy1_Config::XcvrType, XHdmiphy1_SetBufgGtDiv, XHdmiphy1_PowerDownGtPll, XHdmiphy1_ResetGtPll, XHdmiphy1_MmcmReset, XHdmiphy1_IBufDsEnable, XHdmiphy1_Config::DruIsPresent, XHdmiphy1_DruReset, XHdmiphy1_DruEnable, XHdmiphy1_SetRxLpm, XHdmiphy1_SetTxVoltageSwing, XHdmiphy1_SetTxPreEmphasis, XHdmiphy1_SetTxPostCursor, XHdmiphy1_WriteReg, XHDMIPHY1_INTR_STS_REG, XHdmiphy1_IntrEnable, XHdmiphy1::IsReady.
void XHdmiphy1_HdmiUpdateClockSelection(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_SysClkDataSelType TxSysPllClkSel, XHdmiphy1_SysClkDataSelType RxSysPllClkSel)
This function Updates the HDMIPHY clocking.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. TxSysPllClkSel is the SYSCLKDATA selection for TX. RxSysPllClkSel is the SYSCLKDATA selection for RX. None. None.
References XHdmiphy1_ResetGtPll, XHdmiphy1_Ch2Ids, XHdmiphy1::Quads, XHDMIPHY1_CH2IDX, XHdmiphy1_Channel::TxState, XHDMIPHY1_GT_STATE_IDLE, XHdmiphy1_Channel::RxState, XHdmiphy1::Config, XHdmiphy1_Config::TxSysPllClkSel, XHdmiphy1_Config::RxSysPllClkSel.
void XHdmiphy1_TxAlignReset(XHdmiphy1 *InstancePtr, XHdmiphy1_ChannelId ChId, u8 Reset)
This function resets the GT TX alignment module.
InstancePtr is a pointer to the XHdmiphy1 core instance. ChId is the channel ID to operate on. Reset specifies TRUE/FALSE value to either assert or deassert reset on the TX alignment module, respectively. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_Ch2Ids, XHdmiphy1_ReadReg, XHDMIPHY1_TX_BUFFER_BYPASS_REG, XHDMIPHY1_TX_BUFFER_BYPASS_TXPHDLYRESET_MASK, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_HdmiGtTxResetDoneLockHandler.
void XHdmiphy1_TxAlignStart(XHdmiphy1 *InstancePtr, XHdmiphy1_ChannelId ChId, u8 Start)
This function resets the GT TX alignment module.
InstancePtr is a pointer to the XHdmiphy1 core instance. ChId is the channel ID to operate on. Start specifies TRUE/FALSE value to either start or ttop the TX alignment module, respectively. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_Ch2Ids, XHdmiphy1_ReadReg, XHDMIPHY1_TX_BUFFER_BYPASS_REG, XHDMIPHY1_TX_BUFFER_BYPASS_TXPHALIGN_MASK, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_HdmiGtTxResetDoneLockHandler, XHdmiphy1_HdmiTxClkDetFreqChangeHandler, XHdmiphy1_HdmiTxTimerTimeoutHandler.
void XHdmiphy1_ClkDetEnable(XHdmiphy1 *InstancePtr, u8 Enable)
This function enables the HDMIPHY's detector peripheral.
InstancePtr is a pointer to the XHdmiphy1 core instance. Enable specifies TRUE/FALSE value to either enable or disable the clock detector respectively. None. None.
References XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_CLKDET_CTRL_REG, XHDMIPHY1_CLKDET_CTRL_RUN_MASK, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
void XHdmiphy1_ClkDetTimerClear(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir)
This function clears the clock detector TX/RX timer.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for RX or TX. None. None.
References XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_CLKDET_CTRL_REG, XHDMIPHY1_CLKDET_CTRL_TX_TMR_CLR_MASK, XHDMIPHY1_CLKDET_CTRL_RX_TMR_CLR_MASK, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_HdmiTxClkDetFreqChangeHandler, XHdmiphy1_HdmiRxClkDetFreqChangeHandler.
void XHdmiphy1_ClkDetFreqReset(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir)
This function resets clock detector TX/RX frequency.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for RX or TX. None. None.
References XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_CLKDET_CTRL_REG, XHDMIPHY1_CLKDET_CTRL_TX_FREQ_RST_MASK, XHDMIPHY1_CLKDET_CTRL_RX_FREQ_RST_MASK, XHdmiphy1_WriteReg.
void XHdmiphy1_ClkDetSetFreqLockThreshold(XHdmiphy1 *InstancePtr, u16 ThresholdVal)
This function sets the clock detector frequency lock counter threshold value.
InstancePtr is a pointer to the XHdmiphy1 core instance. ThresholdVal is the threshold value to be set. None. None.
References XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_CLKDET_CTRL_REG, XHDMIPHY1_CLKDET_CTRL_RX_FREQ_RST_MASK, XHDMIPHY1_CLKDET_CTRL_FREQ_LOCK_THRESH_SHIFT, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
void XHdmiphy1_ClkDetAccuracyRange(XHdmiphy1 *InstancePtr, u16 ThresholdVal)
This function sets the clock detector accuracy range value.
InstancePtr is a pointer to the XHdmiphy1 core instance. ThresholdVal is the threshold value to be set. None. None.
References XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_CLKDET_CTRL_REG, XHDMIPHY1_CLKDET_CTRL_ACCURACY_RANGE_MASK, XHDMIPHY1_CLKDET_CTRL_ACCURACY_RANGE_SHIFT, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
u8 XHdmiphy1_ClkDetCheckFreqZero(XHdmiphy1 *InstancePtr, XHdmiphy1_DirectionType Dir)
This function checks clock detector RX/TX frequency zero indicator bit.
InstancePtr is a pointer to the XHdmiphy1 core instance. Dir is an indicator for RX or TX. - TRUE if zero frequency. FALSE otherwise, if non-zero frequency. None.
References XHDMIPHY1_CLKDET_STAT_TX_FREQ_ZERO_MASK, XHDMIPHY1_CLKDET_STAT_RX_FREQ_ZERO_MASK, XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_DRU_STAT_REG.
void XHdmiphy1_ClkDetSetFreqTimeout(XHdmiphy1 *InstancePtr, u32 TimeoutVal)
This function sets clock detector frequency lock counter threshold value.
InstancePtr is a pointer to the XHdmiphy1 core instance. TimeoutVal is the timeout value and is normally the system clock frequency. None. None.
References XHdmiphy1_WriteReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_CLKDET_FREQ_TMR_TO_REG.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
void XHdmiphy1_ClkDetTimerLoad(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir, u32 TimeoutVal)
This function loads the timer to TX/RX in the clock detector.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for RX or TX. TimeoutVal is the timeout value to store in the clock detector. None. None.
References XHDMIPHY1_CLKDET_TMR_TX_REG, XHDMIPHY1_CLKDET_TMR_RX_REG, XHdmiphy1_WriteReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr.
Referenced by XHdmiphy1_HdmiTxClkDetFreqChangeHandler, XHdmiphy1_HdmiRxClkDetFreqChangeHandler.
u32 XHdmiphy1_ClkDetGetRefClkFreqHz(XHdmiphy1 *InstancePtr, XHdmiphy1_DirectionType Dir)
This function returns the frequency of the RX/TX reference clock as measured by the clock detector peripheral.
InstancePtr is a pointer to the XHdmiphy1 core instance. Dir is an indicator for RX or TX. The measured frequency of the RX/TX reference clock. None.
References XHdmiphy1::TxHdmi21Cfg, XHdmiphy1_Hdmi21Cfg::IsEnabled, XHdmiphy1::Config, XHdmiphy1_Config::TxFrlRefClkSel, XHdmiphy1_Config::TxRefClkSel, XHDMIPHY1_CLKDET_FREQ_TX_REG, XHDMIPHY1_CLKDET_FREQ_TX_FRL_REG, XHdmiphy1::RxHdmi21Cfg, XHdmiphy1_Config::RxFrlRefClkSel, XHdmiphy1_Config::RxRefClkSel, XHDMIPHY1_CLKDET_FREQ_RX_REG, XHDMIPHY1_CLKDET_FREQ_RX_FRL_REG, XHdmiphy1_ReadReg, XHdmiphy1_Config::BaseAddr.
Referenced by XHdmiphy1_DruCalcCenterFreqHz, XHdmiphy1_HdmiTxClkDetFreqChangeHandler, XHdmiphy1_HdmiRxClkDetFreqChangeHandler.
u32 XHdmiphy1_ClkDetGetRefClkFreqHzRaw(XHdmiphy1 *InstancePtr, XHdmiphy1_DirectionType Dir)
This function returns the raw (unconditional) frequency of the RX/TX reference clock as measured by the clock detector peripheral.
Unlike XHdmiphy1_ClkDetGetRefClkFreqHz, this function always returns the measured value regardless of lock status - useful for debugging. InstancePtr is a pointer to the XHdmiphy1 core instance. Dir is an indicator for RX or TX. The raw measured frequency of the RX/TX reference clock. This function returns the actual measured frequency value even when lock conditions are not met. Use this for debugging to determine if a clock is present vs not locked.
References XHDMIPHY1_CLKDET_FREQ_TX_RAW_REG, XHDMIPHY1_CLKDET_FREQ_RX_RAW_REG, XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr.
u32 XHdmiphy1_DruGetRefClkFreqHz(XHdmiphy1 *InstancePtr)
This function returns the frequency of the DRU reference clock as measured by the clock detector peripheral.
InstancePtr is a pointer to the XHdmiphy1 core instance. The measured frequency of the DRU reference clock. The design must have a DRU for this function to return a valid value.
References XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_CLKDET_FREQ_DRU_REG, XHdmiphy1_Config::XcvrType, XHdmiphy1::versal_2ve_2vm.
Referenced by XHdmiphy1_DruCalcCenterFreqHz, XHdmiphy1_HdmiQpllParam, XHdmiphy1_HdmiCpllParam, XHdmiphy1_GetPllVcoFreqHz.
u32 XHdmiphy1_DruGetRefClkFreqHzRaw(XHdmiphy1 *InstancePtr)
This function returns the raw (unconditional) frequency of the DRU reference clock as measured by the clock detector peripheral.
Unlike XHdmiphy1_DruGetRefClkFreqHz, this function always returns the measured value without any range checking - useful for debugging. InstancePtr is a pointer to the XHdmiphy1 core instance. The raw measured frequency of the DRU reference clock. This function returns the actual measured frequency value without range validation. Use this for debugging to see the raw DRU clock measurement independent of expected frequency ranges.
References XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_CLKDET_FREQ_DRU_RAW_REG.
void XHdmiphy1_DruReset(XHdmiphy1 *InstancePtr, XHdmiphy1_ChannelId ChId, u8 Reset)
This function resets the DRU in the HDMIPHY.
InstancePtr is a pointer to the XHdmiphy1 core instance. ChId is the channel ID to operate on. Reset specifies TRUE/FALSE value to either enable or disable the DRU respectively. None.
References XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_DRU_CTRL_REG, XHdmiphy1_Ch2Ids, XHDMIPHY1_DRU_CTRL_RST_MASK, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize, XHdmiphy1_HdmiGtRxResetDoneLockHandler, XHdmiphy1_HdmiRxClkDetFreqChangeHandler.
void XHdmiphy1_DruEnable(XHdmiphy1 *InstancePtr, XHdmiphy1_ChannelId ChId, u8 Enable)
This function enabled/disables the DRU in the HDMIPHY.
InstancePtr is a pointer to the XHdmiphy1 core instance. ChId is the channel ID to operate on. Enable specifies TRUE/FALSE value to either enable or disable the DRU, respectively. None.
References XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_DRU_CTRL_REG, XHdmiphy1_Ch2Ids, XHDMIPHY1_DRU_CTRL_EN_MASK, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize, XHdmiphy1_HdmiRxClkDetFreqChangeHandler, XHdmiphy1_HdmiRxTimerTimeoutHandler.
u16 XHdmiphy1_DruGetVersion(XHdmiphy1 *InstancePtr)
This function gets the DRU version.
InstancePtr is a pointer to the XHdmiphy1 core instance. None.
References XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_DRU_STAT_REG, XHDMIPHY1_DRU_STAT_VERSION_MASK, XHDMIPHY1_DRU_STAT_VERSION_SHIFT.
Referenced by XHdmiphy1_HdmiDebugInfo.
void XHdmiphy1_DruSetCenterFreqHz(XHdmiphy1 *InstancePtr, XHdmiphy1_ChannelId ChId, u64 CenterFreqHz)
This function sets the DRU center frequency.
InstancePtr is a pointer to the XHdmiphy1 core instance. ChId specifies the channel ID. CenterFreqHz is the frequency value to set. None.
References XHDMIPHY1_DRU_CFREQ_H_MASK, XHdmiphy1_Ch2Ids, XHDMIPHY1_DRU_CFREQ_L_REG, XHdmiphy1_WriteReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_DRU_CFREQ_H_REG.
Referenced by XHdmiphy1_SetHdmiRxParam.
u64 XHdmiphy1_DruCalcCenterFreqHz(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId)
This function calculates the center frequency value for the DRU.
InstancePtr is a pointer to the XHdmiphy1 GT core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. The calculated DRU Center frequency value. According to XAPP1240: Center_f = fDIN * (2^32)/fdruclk The DRU clock is derived from the measured reference clock and the current QPLL settings.
References XHdmiphy1_ClkDetGetRefClkFreqHz, XHdmiphy1_DruGetRefClkFreqHz, XHdmiphy1::Quads, XHDMIPHY1_CH2IDX, XHdmiphy1_Channel::RxOutDiv.
Referenced by XHdmiphy1_SetHdmiRxParam.
void XHdmiphy1_HdmiGtDruModeEnable(XHdmiphy1 *InstancePtr, u8 Enable)
This function sets the GT RX CDR and Equalization for DRU mode.
InstancePtr is a pointer to the XHdmiphy1 core instance. Enable enables the DRU logic (when 1), or disables (when 0). None.
References XHdmiphy1_LogWrite, XHDMIPHY1_LOG_EVT_DRU_EN, XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_RX_EQ_CDR_REG, XHdmiphy1_Ch2Ids, XHDMIPHY1_RX_STATUS_RXCDRHOLD_MASK, XHDMIPHY1_RX_STATUS_RXOSOVRDEN_MASK, XHDMIPHY1_RX_STATUS_RXLPMLFKLOVRDEN_MASK, XHDMIPHY1_RX_STATUS_RXLPMHFOVRDEN_MASK, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_HdmiRxTimerTimeoutHandler.
u32 XHdmiphy1_HdmiCfgCalcMmcmParam(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir, XVidC_PixelsPerClock Ppc, XVidC_ColorDepth Bpc)
This function calculates the HDMI MMCM parameters.
InstancePtr is a pointer to the Hdmiphy core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. Dir is an indicator for RX or TX. Ppc specifies the total number of pixels per clock. 1 = XVIDC_PPC_12 = XVIDC_PPC_24 = XVIDC_PPC_4 Bpc specifies the color depth/bits per color component. 6 = XVIDC_BPC_68 = XVIDC_BPC_810 = XVIDC_BPC_1012 = XVIDC_BPC_1216 = XVIDC_BPC_16 XST_SUCCESS if calculated PLL parameters updated successfully.XST_FAILURE if parameters not updated. None.
References XHdmiphy1_GetPllType, XHdmiphy1::Quads, XHdmiphy1_Channel::LineRateHz, XHdmiphy1_LogWrite, XHDMIPHY1_LOG_EVT_1PPC_ERR, XHdmiphy1_ErrorHandler, XHdmiphy1::HdmiRxRefClkHz, XHdmiphy1_Quad::RxMmcm, XHdmiphy1::HdmiTxRefClkHz, XHdmiphy1_Quad::TxMmcm, XHdmiphy1::Config, XHdmiphy1_Config::RxClkPrimitive, XHdmiphy1_Config::TxClkPrimitive, XHdmiphy1_Config::TransceiverWidth, XHdmiphy1::HdmiTxSampleRate, XHdmiphy1::HdmiRxTmdsClockRatio.
Referenced by XHdmiphy1_SetHdmiTxParam.
u32 XHdmiphy1_HdmiQpllParam(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir)
This function calculates the QPLL parameters.
InstancePtr is a pointer to the HDMI GT core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. Dir is an indicator for RX or TX. XST_SUCCESS if calculated QPLL parameters updated successfully.XST_FAILURE if parameters not updated. None.
References XHdmiphy1::Config, XHdmiphy1_Config::DruIsPresent, XHdmiphy1::HdmiRxDruIsEnabled, XHdmiphy1::HdmiRxRefClkHz, XHdmiphy1::HdmiRxTmdsClockRatio, XHdmiphy1::HdmiTxRefClkHz, XHdmiphy1::HdmiTxSampleRate, XHdmiphy1_Hdmi21Cfg::IsEnabled, XHdmiphy1_Hdmi21Cfg::LineRate, XHdmiphy1::Quads, XHdmiphy1_Channel::RxDataWidth, XHdmiphy1::RxHdmi21Cfg, XHdmiphy1_Channel::RxIntDataWidth, XHdmiphy1_Config::TransceiverWidth, XHdmiphy1::TxHdmi21Cfg, XHdmiphy1_CfgLineRate, XHdmiphy1_CfgSysClkDataSel, XHdmiphy1_CfgSysClkOutSel, XHdmiphy1_Ch2Ids, XHDMIPHY1_CH2IDX, XHdmiphy1_ClkCalcParams, XHdmiphy1_DruGetRefClkFreqHz, XHdmiphy1_ErrorHandler, XHdmiphy1_GetLineRateHz, XHDMIPHY1_LOG_EVT_DRU_CLK_ERR, XHDMIPHY1_LOG_EVT_GT_QPLL_CFG_ERR, XHDMIPHY1_LOG_EVT_NO_DRU, XHDMIPHY1_LOG_EVT_USRCLK_ERR, XHdmiphy1_LogWrite.
Referenced by XHdmiphy1_SetHdmiRxParam, XHdmiphy1_SetHdmiTxParam.
u32 XHdmiphy1_HdmiCpllParam(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir)
This function calculates the CPLL parameters.
InstancePtr is a pointer to the HDMI GT core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. Dir is an indicator for RX or TX. XST_SUCCESS if calculated CPLL parameters updated successfully.XST_FAILURE if parameters not updated. None.
References XHdmiphy1::Config, XHdmiphy1_Config::DruIsPresent, XHdmiphy1::HdmiRxDruIsEnabled, XHdmiphy1::HdmiRxRefClkHz, XHdmiphy1::HdmiRxTmdsClockRatio, XHdmiphy1::HdmiTxRefClkHz, XHdmiphy1::HdmiTxSampleRate, XHdmiphy1_Hdmi21Cfg::IsEnabled, XHdmiphy1_Hdmi21Cfg::LineRate, XHdmiphy1::Quads, XHdmiphy1::RxHdmi21Cfg, XHdmiphy1_Config::TransceiverWidth, XHdmiphy1::TxHdmi21Cfg, XHdmiphy1_CfgLineRate, XHdmiphy1_Ch2Ids, XHDMIPHY1_CH2IDX, XHdmiphy1_ClkCalcParams, XHdmiphy1_DruGetRefClkFreqHz, XHdmiphy1_ErrorHandler, XHdmiphy1_GetLineRateHz, XHDMIPHY1_LOG_EVT_DRU_CLK_ERR, XHDMIPHY1_LOG_EVT_GT_CPLL_CFG_ERR, XHDMIPHY1_LOG_EVT_NO_DRU, XHDMIPHY1_LOG_EVT_USRCLK_ERR, XHDMIPHY1_LOG_EVT_VD_NOT_SPRTD_ERR, XHdmiphy1_LogWrite.
Referenced by XHdmiphy1_SetHdmiRxParam, XHdmiphy1_SetHdmiTxParam.
u32 XHdmiphy1_SetHdmiTxParam(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XVidC_PixelsPerClock Ppc, XVidC_ColorDepth Bpc, XVidC_ColorFormat ColorFormat)
This function update/set the HDMI TX parameter.
InstancePtr is a pointer to the Hdmiphy core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. Ppc is the pixels per clock to set. Bpc is the bits per color to set. ColorFormat is the color format to set. XST_SUCCESS if TX parameters set/updated.XST_FAILURE if low resolution video not supported. None.
References XHdmiphy1_IsTxUsingCpll, XHdmiphy1_HdmiCpllParam, XHdmiphy1_HdmiQpllParam, XHdmiphy1_WriteCfgRefClkSelReg, XHdmiphy1::Config, XHdmiphy1_Config::Ppc, XHdmiphy1_LogWrite, XHDMIPHY1_LOG_EVT_PPC_MSMTCH_ERR, XHdmiphy1_ErrorHandler, XHdmiphy1::TxHdmi21Cfg, XHdmiphy1_Hdmi21Cfg::IsEnabled, XHdmiphy1_HdmiCfgCalcMmcmParam.
Referenced by XHdmiphy1_Hdmi21Config.
u32 XHdmiphy1_SetHdmiRxParam(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId)
This function update/set the HDMI RX parameter.
InstancePtr is a pointer to the Hdmiphy core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. XST_SUCCESS if RX parameters set/updated.XST_FAILURE if low resolution video not supported. None.
References XHdmiphy1_IsRxUsingCpll, XHdmiphy1_HdmiCpllParam, XHdmiphy1_HdmiQpllParam, XHdmiphy1_WriteCfgRefClkSelReg, XHdmiphy1::HdmiRxDruIsEnabled, XHdmiphy1_GetPllType, XHdmiphy1_GetRcfgChId, XHdmiphy1_DruCalcCenterFreqHz, XHdmiphy1_DruSetCenterFreqHz.
Referenced by XHdmiphy1_HdmiRxTimerTimeoutHandler.
void XHdmiphy1_PatgenEnable(XHdmiphy1 *InstancePtr, u8 QuadId, u8 Enable)
This function enables or disables the Pattern Generator for the GT Channel 4 when it isused to generate the TX TMDS Clock.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Enable TRUE/FALSE None.
References XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_PATGEN_CTRL_REG, XHDMIPHY1_PATGEN_CTRL_ENABLE_MASK, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_HdmiGtTxResetDoneLockHandler, XHdmiphy1_HdmiTxClkDetFreqChangeHandler.
void XHdmiphy1_PatgenSetRatio(XHdmiphy1 *InstancePtr, u8 QuadId, u64 TxLineRate)
This function sets the Pattern Generator for the GT Channel 4 when it is used to generate the TX TMDS Clock.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. TxLineRate in Mbps. None.
References XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_PATGEN_CTRL_REG, XHDMIPHY1_PATGEN_CTRL_RATIO_MASK, XHdmiphy1::HdmiTxSampleRate, XHDMIPHY1_Patgen_Ratio_40, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_HdmiGtTxResetDoneLockHandler.
u32 XHdmiphy1_Hdmi20Config(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir)
This function will configure the HDMIPHY to HDMI 2.0 mode.
InstancePtr is a pointer to the Hdmiphy core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for RX or TX. XST_SUCCESS if TX parameters set/updated.XST_FAILURE if low resolution video not supported. None.
References XHdmiphy1_LogWrite, XHDMIPHY1_LOG_EVT_TMDS_RECONFIG, XHdmiphy1_GetPllType, XHdmiphy1::TxHdmi21Cfg, XHdmiphy1_Hdmi21Cfg::LineRate, XHdmiphy1_Hdmi21Cfg::NChannels, XHdmiphy1_Hdmi21Cfg::IsEnabled, XHdmiphy1::RxHdmi21Cfg, XHdmiphy1_MmcmSetClkinsel, XHdmiphy1_IntrEnable, XHdmiphy1_CfgPllRefClkSel, XHdmiphy1::Config, XHdmiphy1_Config::TxRefClkSel, XHdmiphy1_Config::RxRefClkSel, XHdmiphy1_WriteCfgRefClkSelReg.
u32 Xhdmiphy1_RefClkValue()
This function will configure the FRL REF CLK for HDMI 2.1 operation.
FRL Ref Clk value None.
Referenced by XHdmiphy1_Hdmi21Config, XHdmiphy1_HdmiRxClkDetFreqChangeHandler.
u32 XHdmiphy1_Hdmi21Config(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir, u64 LineRate, u8 NChannels)
This function will configure the GT for HDMI 2.1 operation.
InstancePtr is a pointer to the Hdmiphy core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for RX or TX. LineRate is the line rate for HDMI 2.1 operation. NChannels is the number of channels for HDMI 2.1 operation. XST_SUCCESS if TX parameters set/updated.XST_FAILURE if low resolution video not supported. None.
References XHdmiphy1_GetPllType, XHdmiphy1_LogWrite, XHDMIPHY1_LOG_EVT_SPDGRDE_ERR, XHdmiphy1_ErrorHandler, XHDMIPHY1_LOG_EVT_FRL_RECONFIG, XHdmiphy1::Config, XHdmiphy1_Config::TxRefClkSel, XHdmiphy1_Config::TxFrlRefClkSel, XHdmiphy1_IntrDisable, XHdmiphy1_Clkout1OBufTdsEnable, XHdmiphy1_Config::RxRefClkSel, XHdmiphy1_Config::RxFrlRefClkSel, XHdmiphy1_CfgPllRefClkSel, XHdmiphy1_WriteCfgRefClkSelReg, Xhdmiphy1_RefClkValue, XHdmiphy1::HdmiTxRefClkHz, XHdmiphy1::TxHdmi21Cfg, XHdmiphy1_Hdmi21Cfg::LineRate, XHdmiphy1_Hdmi21Cfg::NChannels, XHdmiphy1_Hdmi21Cfg::IsEnabled, XHdmiphy1_SetHdmiTxParam, XHdmiphy1_Config::Ppc, XHdmiphy1_MmcmLockedMaskEnable, XHdmiphy1_MmcmSetClkinsel, XHdmiphy1_HdmiTxTimerTimeoutHandler, XHdmiphy1::HdmiRxRefClkHz, XHdmiphy1::RxHdmi21Cfg, XHdmiphy1_MmcmStart, XHdmiphy1_HdmiRxTimerTimeoutHandler.
void XHdmiphy1_HdmiDebugInfo(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId)
This function prints Video PHY debug information related to HDMI.
InstancePtr is a pointer to the Hdmiphy core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. None. None.
References XHdmiphy1::Quads, XHdmiphy1_IsHDMI, XHdmiphy1_IsTxUsingCpll, XHdmiphy1_Channel::TxDataRefClkSel, XHdmiphy1_IsRxUsingCpll, XHdmiphy1_Channel::RxDataRefClkSel, XHDMIPHY1_CH2IDX, XHDMIPHY1_GT_STATE_IDLE, XHDMIPHY1_GT_STATE_LOCK, XHDMIPHY1_GT_STATE_RESET, XHDMIPHY1_GT_STATE_ALIGN, XHDMIPHY1_GT_STATE_READY, XHdmiphy1_Channel::RxOutDiv, XHdmiphy1_Channel::TxOutDiv, XHdmiphy1_IsTxUsingQpll, XHdmiphy1_IsRxUsingQpll, XHDMIPHY1_GT_STATE_GPO_RE, XHdmiphy1::Config, XHdmiphy1_Config::RxClkPrimitive, XHdmiphy1_Quad::RxMmcm, XHdmiphy1_Config::TxClkPrimitive, XHdmiphy1_Quad::TxMmcm, XHdmiphy1_Config::DruIsPresent, XHdmiphy1_DruGetVersion, XHdmiphy1::HdmiRxDruIsEnabled, XHdmiphy1_ReadReg, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_DRU_GAIN_REG, XHDMIPHY1_DRU_GAIN_G1_MASK, XHDMIPHY1_DRU_GAIN_G1_P_MASK, XHDMIPHY1_DRU_GAIN_G1_P_SHIFT, XHDMIPHY1_DRU_GAIN_G2_MASK, XHDMIPHY1_DRU_GAIN_G2_SHIFT, XHDMIPHY1_DRU_CFREQ_H_REG, XHDMIPHY1_DRU_CFREQ_L_REG.