xhdmiphy1.c
static u32 XHdmiphy1_DrpAccess(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir, u16 Addr, u16 *Val)
This function will initiate a DRP transaction (either read or write).
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID on which to direct the DRP access. Dir is an indicator for write (TX) or read (RX). Addr is the DRP address to issue the DRP access to. Val is a pointer to the data value. In write mode, this pointer will hold the value to write. In read mode, this pointer will be populated with the read value. XST_SUCCESS if the DRP access was successful.XST_FAILURE otherwise, if the busy bit did not go low, or if the ready bit did not go high. In read mode (Dir == XHDMIPHY1_DIR_RX), the data pointed to by Val will be populated with the u16 value that was read._
void XHdmiphy1_CfgInitialize(XHdmiphy1 *InstancePtr, XHdmiphy1_Config *ConfigPtr, UINTPTR EffectiveAddr)
This function retrieves the configuration for this Video PHY instance and fills in the InstancePtr->Config structure.
InstancePtr is a pointer to the XHdmiphy1 instance. ConfigPtr is a pointer to the configuration structure that will be used to copy the settings from. EffectiveAddr is the device base address in the virtual memory space. If the address translation is not used, then the physical address is passed. None. Unexpected errors may occur if the address mapping is changed after this function is invoked.
References XHdmiphy1::IsReady, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHdmiphy1_Config::XcvrType, XHdmiphy1_Config::TxSysPllClkSel, XHdmiphy1_Config::RxSysPllClkSel, XHdmiphy1_Config::TxRefClkSel, XHdmiphy1_Config::RxRefClkSel, XHdmiphy1_Config::TxFrlRefClkSel, XHdmiphy1_Config::RxFrlRefClkSel, XHdmiphy1_Config::DruRefClkSel.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
u32 XHdmiphy1_PllInitialize(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_PllRefClkSelType QpllRefClkSel, XHdmiphy1_PllRefClkSelType CpllRefClkSel, XHdmiphy1_PllType TxPllSelect, XHdmiphy1_PllType RxPllSelect)
This function will initialize the PLL selection for a given channel.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. QpllRefClkSel is the QPLL reference clock selection for the quad. CpllRefClkSel is the CPLL reference clock selection for the quad. TxPllSelect is the reference clock selection for the quad's TX PLL dividers. RxPllSelect is the reference clock selection for the quad's RX PLL dividers. XST_SUCCESS. None.
References XHdmiphy1_CfgPllRefClkSel, XHdmiphy1_CfgSysClkDataSel, XHdmiphy1_Pll2SysClkData, XHdmiphy1_CfgSysClkOutSel, XHdmiphy1_Pll2SysClkOut, XHdmiphy1_WriteCfgRefClkSelReg.
void XHdmiphy1_SetUserTimerHandler(XHdmiphy1 *InstancePtr, XHdmiphy1_TimerHandler CallbackFunc, void *CallbackRef)
void XHdmiphy1_WaitUs(XHdmiphy1 *InstancePtr, u32 MicroSeconds)
This function is the delay/sleep function for the XHdmiphy1 driver.
For the Zynq family, there exists native sleep functionality. For MicroBlaze however, there does not exist such functionality. In the MicroBlaze case, the default method for delaying is to use a predetermined amount of loop iterations. This method is prone to inaccuracy and dependent on system configuration; for greater accuracy, the user may supply their own delay/sleep handler, pointed to by InstancePtr->UserTimerWaitUs, which may have better accuracy if a hardware timer is used. InstancePtr is a pointer to the XHdmiphy1 instance. MicroSeconds is the number of microseconds to delay/sleep for. None. None.
References XHdmiphy1::IsReady, XHdmiphy1::UserTimerWaitUs.
u32 XHdmiphy1_GetVersion(XHdmiphy1 *InstancePtr)
This function will obtian the IP version.
InstancePtr is a pointer to the XHdmiphy1 core instance. The IP version of the Video PHY core. None.
References XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_VERSION_REG.
u32 XHdmiphy1_CfgLineRate(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, u64 LineRateHz)
Configure the channel's line rate.
This is a software only configuration and this value is used in the PLL calculator. InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. LineRateHz is the line rate to configure software. XST_SUCCESS if the reference clock type is valid.XST_FAILURE otherwise. None.
References XHdmiphy1_Ch2Ids, XHdmiphy1::Quads, XHDMIPHY1_CH2IDX, XHdmiphy1_Channel::LineRateHz.
Referenced by XHdmiphy1_HdmiQpllParam, XHdmiphy1_HdmiCpllParam.
XHdmiphy1_PllType XHdmiphy1_GetPllType(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir, XHdmiphy1_ChannelId ChId)
Obtain the channel's PLL reference clock selection.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. ChId is the channel ID which to operate on. The PLL type being used by the channel. None.
References XHdmiphy1_GetSysClkDataSel, XHdmiphy1_GetSysClkOutSel, XHdmiphy1::Config, XHdmiphy1_Config::TxSysPllClkSel, XHdmiphy1_Config::RxSysPllClkSel.
Referenced by XHdmiphy1_HdmiCfgCalcMmcmParam, XHdmiphy1_SetHdmiRxParam, XHdmiphy1_Hdmi20Config, XHdmiphy1_Hdmi21Config, XHdmiphy1_HdmiQpllLockHandler, XHdmiphy1_HdmiCpllLockHandler, XHdmiphy1_HdmiGtTxResetDoneLockHandler, XHdmiphy1_HdmiTxClkDetFreqChangeHandler, XHdmiphy1_HdmiRxClkDetFreqChangeHandler, XHdmiphy1_HdmiTxTimerTimeoutHandler, XHdmiphy1_HdmiRxTimerTimeoutHandler, XHdmiphy1_IsPllLocked.
u64 XHdmiphy1_GetLineRateHz(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId)
This function will return the line rate in Hz for a given channel / quad.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to check. ChId is the channel ID for which to retrieve the line rate. The line rate in Hz. None.
References XHdmiphy1::Quads, XHdmiphy1_Channel::LineRateHz.
Referenced by XHdmiphy1_HdmiQpllParam, XHdmiphy1_HdmiCpllParam, XHdmiphy1_HdmiGtTxResetDoneLockHandler.
u32 XHdmiphy1_ResetGtPll(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir, u8 Hold)
This function will reset the GT's PLL logic.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID which to operate on. Dir is an indicator for TX or RX. Hold is an indicator whether to "hold" the reset if set to 1. If set to 0: reset, then enable. XST_SUCCESS. None.
References XHDMIPHY1_TX_INIT_REG, XHDMIPHY1_RX_INIT_REG, XHDMIPHY1_TXRX_INIT_PLLGTRESET_ALL_MASK, XHDMIPHY1_TXRX_INIT_PLLGTRESET_MASK, XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize, XHdmiphy1_HdmiUpdateClockSelection, XHdmiphy1_HdmiTxClkDetFreqChangeHandler, XHdmiphy1_HdmiRxClkDetFreqChangeHandler, XHdmiphy1_HdmiTxTimerTimeoutHandler, XHdmiphy1_HdmiRxTimerTimeoutHandler.
u32 XHdmiphy1_ResetGtTxRx(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir, u8 Hold)
This function will reset the GT's TX/RX logic.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID which to operate on. Dir is an indicator for TX or RX. Hold is an indicator whether to "hold" the reset if set to 1. If set to 0: reset, then enable. XST_SUCCESS. None.
References XHDMIPHY1_TX_INIT_REG, XHDMIPHY1_RX_INIT_REG, XHDMIPHY1_TXRX_INIT_GTRESET_ALL_MASK, XHDMIPHY1_TXRX_INIT_GTRESET_MASK, XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_HdmiQpllLockHandler, XHdmiphy1_HdmiCpllLockHandler.
u32 XHdmiphy1_SetPolarity(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir, u8 Polarity)
This function will set/clear the TX/RX polarity bit.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID which to operate on. Dir is an indicator for TX or RX. Polarity 0-Not inverted 1-Inverted XST_SUCCESS. None.
References XHDMIPHY1_TX_CONTROL_REG, XHDMIPHY1_TX_CONTROL_TXPOLARITY_ALL_MASK, XHDMIPHY1_TX_CONTROL_TXPOLARITY_MASK, XHDMIPHY1_RX_CONTROL_REG, XHDMIPHY1_RX_CONTROL_RXPOLARITY_ALL_MASK, XHDMIPHY1_RX_CONTROL_RXPOLARITY_MASK, XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHdmiphy1_WriteReg.
u32 XHdmiphy1_SetPrbsSel(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir, XHdmiphy1_PrbsPattern Pattern)
This function will set the TX/RXPRBSEL of the GT.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID which to operate on. Dir is an indicator for TX or RX. Pattern is the pattern XHdmiphy1_PrbsPattern XST_SUCCESS. None.
References XHDMIPHY1_TX_CONTROL_REG, XHDMIPHY1_TX_CONTROL_TXPRBSSEL_ALL_MASK, XHDMIPHY1_TX_CONTROL_TXPRBSSEL_MASK, XHDMIPHY1_RX_CONTROL_REG, XHDMIPHY1_RX_CONTROL_RXPRBSSEL_ALL_MASK, XHDMIPHY1_RX_CONTROL_RXPRBSSEL_MASK, XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHdmiphy1_Ch2Ids, XHDMIPHY1_TX_CONTROL_TXPRBSSEL_SHIFT, XHDMIPHY1_RX_CONTROL_RXPRBSSEL_SHIFT, XHdmiphy1_WriteReg.
u32 XHdmiphy1_TxPrbsForceError(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, u8 ForceErr)
This function will force an error in the TX PRBS pattern for the GT.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID which to operate on. ForceErr 0-No Error 1-Force Error XST_SUCCESS. None.
References XHDMIPHY1_TX_CONTROL_TXPRBSFORCEERR_ALL_MASK, XHDMIPHY1_TX_CONTROL_TXPRBSFORCEERR_MASK, XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_TX_CONTROL_REG, XHdmiphy1_WriteReg.
void XHdmiphy1_SetTxVoltageSwing(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, u8 Vs)
This function will set the TX voltage swing value for a given channel.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. Vs is the voltage swing value to write. None. None.
References XHDMIPHY1_TX_DRIVER_CH12_REG, XHDMIPHY1_TX_DRIVER_CH34_REG, XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_TX_DRIVER_TXDIFFCTRL_MASK, XHDMIPHY1_TX_DRIVER_TXDIFFCTRL_SHIFT, XHdmiphy1_WriteReg, XHDMIPHY1_TX_DRIVER_EXT_REG, XHDMIPHY1_TX_DRIVER_EXT_TXDIFFCTRL_MASK, XHDMIPHY1_TX_DRIVER_EXT_TXDIFFCTRL_SHIFT.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
void XHdmiphy1_SetTxPreEmphasis(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, u8 Pe)
This function will set the TX pre-emphasis value for a given channel.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. Pe is the pre-emphasis value to write. None. None.
References XHDMIPHY1_TX_DRIVER_CH12_REG, XHDMIPHY1_TX_DRIVER_CH34_REG, XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_TX_DRIVER_TXPRECURSOR_MASK, XHDMIPHY1_TX_DRIVER_TXPRECURSOR_SHIFT, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
void XHdmiphy1_SetTxPostCursor(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, u8 Pc)
This function will set the TX post-cursor value for a given channel.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. Pc is the post-cursor value to write. None. None.
References XHDMIPHY1_TX_DRIVER_CH12_REG, XHDMIPHY1_TX_DRIVER_CH34_REG, XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_TX_DRIVER_TXPOSTCURSOR_MASK, XHDMIPHY1_TX_DRIVER_TXPOSTCURSOR_SHIFT, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
void XHdmiphy1_SetRxLpm(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir, u8 Enable)
This function will enable or disable the LPM logic in the Video PHY core.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. Dir is an indicator for TX or RX. Enable will enable (if 1) or disable (if 0) the LPM logic. None. None.
References XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_RX_EQ_CDR_REG, XHDMIPHY1_RX_CONTROL_RXLPMEN_ALL_MASK, XHDMIPHY1_RX_CONTROL_RXLPMEN_MASK, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
u32 XHdmiphy1_DrpWr(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, u16 Addr, u16 Val)
This function will initiate a write DRP transaction.
It is a wrapper around XHdmiphy1_DrpAccess. InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID on which to direct the DRP access. Addr is the DRP address to issue the DRP access to. Val is the value to write to the DRP address. XST_SUCCESS if the DRP access was successful.XST_FAILURE otherwise, if the busy bit did not go low, or if the ready bit did not go high. None.
u16 XHdmiphy1_DrpRd(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, u16 Addr, u16 *RetVal)
This function will initiate a read DRP transaction.
It is a wrapper around XHdmiphy1_DrpAccess. InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID on which to direct the DRP access. Addr is the DRP address to issue the DRP access to. RetVal is the DRP read_value returned implicitly. XST_SUCCESS if the DRP access was successful.XST_FAILURE otherwise, if the busy bit did not go low, or if the ready bit did not go high. None.
Referenced by XHdmiphy1_RegisterDebug.
void XHdmiphy1_MmcmPowerDown(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir, u8 Hold)
This function will power down the mixed-mode clock manager (MMCM) core.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. Hold is an indicator whether to "hold" the power down if set to 1. If set to 0: power down, then power back up. XST_SUCCESS. None.
References XHDMIPHY1_MMCM_TXUSRCLK_CTRL_REG, XHDMIPHY1_MMCM_RXUSRCLK_CTRL_REG, XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_MMCM_USRCLK_CTRL_PWRDWN_MASK, XHdmiphy1_WriteReg.
void XHdmiphy1_MmcmStart(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir)
This function will start the mixed-mode clock manager (MMCM) core.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. None. None.
References XHdmiphy1::Quads, XHdmiphy1_Quad::RxMmcm, XHdmiphy1_Quad::TxMmcm, XHdmiphy1::Config, XHdmiphy1_Config::RxClkPrimitive, XHdmiphy1_Config::TxClkPrimitive, XHdmiphy1_MmcmReset, XHdmiphy1_MmcmLockedMaskEnable, XHdmiphy1_LogWrite, XHDMIPHY1_LOG_EVT_TXPLL_RECONFIG, XHDMIPHY1_LOG_EVT_RXPLL_RECONFIG.
Referenced by XHdmiphy1_Hdmi21Config, XHdmiphy1_HdmiTxTimerTimeoutHandler, XHdmiphy1_HdmiRxTimerTimeoutHandler.
void XHdmiphy1_IBufDsEnable(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir, u8 Enable)
This function enables the TX or RX IBUFDS peripheral.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. Enable specifies TRUE/FALSE value to either enable or disable the IBUFDS, respectively. None.
References XHDMIPHY1_IBUFDS_GTXX_CTRL_REG, XHdmiphy1::Config, XHdmiphy1_Config::TxRefClkSel, XHdmiphy1_Config::RxRefClkSel, XHdmiphy1_Config::DruIsPresent, XHdmiphy1_Config::DruRefClkSel, XHDMIPHY1_IBUFDS_GTXX_CTRL_GTREFCLK0_CEB_MASK, XHDMIPHY1_IBUFDS_GTXX_CTRL_GTREFCLK1_CEB_MASK, XHDMIPHY1_MISC_TXUSRCLK_REG, XHDMIPHY1_MISC_RXUSRCLK_REG, XHDMIPHY1_MISC_XXUSRCLK_REFCLK_CEB_MASK, XHdmiphy1_ReadReg, XHdmiphy1_Config::BaseAddr, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
void XHdmiphy1_Clkout1OBufTdsEnable(XHdmiphy1 *InstancePtr, XHdmiphy1_DirectionType Dir, u8 Enable)
This function enables the TX or RX CLKOUT1 OBUFTDS peripheral.
InstancePtr is a pointer to the XHdmiphy1 core instance. Dir is an indicator for TX or RX. Enable specifies TRUE/FALSE value to either enable or disable the OBUFTDS, respectively. None.
References XHDMIPHY1_MISC_TXUSRCLK_REG, XHDMIPHY1_MISC_RXUSRCLK_REG, XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_MISC_XXUSRCLK_CKOUT1_OEN_MASK, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi21Config.
void XHdmiphy1_SetErrorCallback(XHdmiphy1 *InstancePtr, void *CallbackFunc, void *CallbackRef)
This function installs a callback function for the HDMIPHY error conditions.
InstancePtr is a pointer to the XHdmiphy1 instance. CallbackFunc is the address to the callback function. CallbackRef is the user data item that will be passed to the callback function when it is invoked. None. The XHdmiphy1_ErrorHandler API calls the registered function in ErrorCallback and passes two arguments: 1) CallbackRef 2) Error Type as defined by XHdmiphy1_ErrType. Sample Function Call: CallbackFunc(CallbackRef, XHdmiphy1_ErrType);
References XHdmiphy1::ErrorCallback, XHdmiphy1::ErrorRef.
void XHdmiphy1_SetLogCallback(XHdmiphy1 *InstancePtr, u64 *CallbackFunc, void *CallbackRef)
This function installs an asynchronous callback function for the LogWrite API:
InstancePtr is a pointer to the XHdmiphy1 instance. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. None.
References XHdmiphy1::LogWriteCallback, XHdmiphy1::LogWriteRef.
void XHdmiphy1_RegisterDebug(XHdmiphy1 *InstancePtr)
This function prints out Video PHY register and GT Channel and Common DRP register contents.
InstancePtr is a pointer to the Hdmiphy core instance. None. None.
References XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHdmiphy1::HdmiIsQpllPresent, XHdmiphy1_DrpRd, XHdmiphy1_Config::XcvrType, XHdmiphy1_Config::RxChannels, XHdmiphy1_Config::TxChannels.