xhdmiphy1_hdmi.h
XHDMIPHY1_HDMI_GTYP_DRU_REFCLK
XHDMIPHY1_HDMI_GTYP_DRU_REFCLK_MIN
XHDMIPHY1_HDMI_GTYP_DRU_REFCLK_MAX
XHDMIPHY1_HDMI_GTYP_DRU_REFCLK1
XHDMIPHY1_HDMI_GTYP_DRU_REFCLK1_MIN
XHDMIPHY1_HDMI_GTYP_DRU_REFCLK1_MAX
XHDMIPHY1_HDMI_GTYP_DRU_REFCLK2
XHDMIPHY1_HDMI_GTYP_DRU_REFCLK2_MIN
XHDMIPHY1_HDMI_GTYP_DRU_REFCLK2_MAX
XHDMIPHY1_HDMI_GTYE5_DRU_LRATE
XHDMIPHY1_HDMI_GTYE5_DRU_REFCLK
XHDMIPHY1_HDMI_GTYE5_DRU_REFCLK_MIN
XHDMIPHY1_HDMI_GTYE5_DRU_REFCLK_MAX
XHDMIPHY1_HDMI_GTYE5_DRU_REFCLK1
XHDMIPHY1_HDMI_GTYE5_DRU_REFCLK1_MIN
XHDMIPHY1_HDMI_GTYE5_DRU_REFCLK1_MAX
XHDMIPHY1_HDMI_GTYE5_DRU_REFCLK2
XHDMIPHY1_HDMI_GTYE5_DRU_REFCLK2_MIN
XHDMIPHY1_HDMI_GTYE5_DRU_REFCLK2_MAX
XHDMIPHY1_HDMI_GTYE5_PLL_SCALE
XHDMIPHY1_HDMI_GTYE5_LCPLL_REFCLK_MIN
XHDMIPHY1_HDMI_GTYE5_RPLL_REFCLK_MIN
XHDMIPHY1_HDMI_GTYE5_TX_MMCM_SCALE
XHDMIPHY1_HDMI_GTYE5_TX_MMCM_FVCO_MIN
XHDMIPHY1_HDMI_GTYE5_TX_MMCM_FVCO_MAX
XHDMIPHY1_HDMI_GTYE5_RX_MMCM_SCALE
XHDMIPHY1_HDMI_GTYE5_RX_MMCM_FVCO_MIN
XHDMIPHY1_HDMI_GTYE5_RX_MMCM_FVCO_MAX
XHDMIPHY1_HDMI_GTYE4_DRU_LRATE
XHDMIPHY1_HDMI_GTYE4_DRU_REFCLK
XHDMIPHY1_HDMI_GTYE4_DRU_REFCLK_MIN
XHDMIPHY1_HDMI_GTYE4_DRU_REFCLK_MAX
XHDMIPHY1_HDMI_GTYE4_DRU_REFCLK2
XHDMIPHY1_HDMI_GTYE4_DRU_REFCLK2_MIN
XHDMIPHY1_HDMI_GTYE4_DRU_REFCLK2_MAX
XHDMIPHY1_HDMI_GTYE4_DRU_REFCLK3
XHDMIPHY1_HDMI_GTYE4_DRU_REFCLK3_MIN
XHDMIPHY1_HDMI_GTYE4_DRU_REFCLK3_MAX
XHDMIPHY1_HDMI_GTYE4_PLL_SCALE
XHDMIPHY1_HDMI_GTYE4_QPLL0_REFCLK_MIN
XHDMIPHY1_HDMI_GTYE4_QPLL1_REFCLK_MIN
XHDMIPHY1_HDMI_GTYE4_CPLL_REFCLK_MIN
XHDMIPHY1_HDMI_GTYE4_TX_MMCM_SCALE
XHDMIPHY1_HDMI_GTYE4_TX_MMCM_FVCO_MIN
XHDMIPHY1_HDMI_GTYE4_TX_MMCM_FVCO_MAX
XHDMIPHY1_HDMI_GTYE4_RX_MMCM_SCALE
XHDMIPHY1_HDMI_GTYE4_RX_MMCM_FVCO_MIN
XHDMIPHY1_HDMI_GTYE4_RX_MMCM_FVCO_MAX
XHDMIPHY1_HDMI_GTHE4_DRU_LRATE
XHDMIPHY1_HDMI_GTHE4_DRU_REFCLK
XHDMIPHY1_HDMI_GTHE4_DRU_REFCLK_MIN
XHDMIPHY1_HDMI_GTHE4_DRU_REFCLK_MAX
XHDMIPHY1_HDMI_GTHE4_DRU_REFCLK2
XHDMIPHY1_HDMI_GTHE4_DRU_REFCLK2_MIN
XHDMIPHY1_HDMI_GTHE4_DRU_REFCLK2_MAX
XHDMIPHY1_HDMI_GTHE4_DRU_REFCLK3
XHDMIPHY1_HDMI_GTHE4_DRU_REFCLK3_MIN
XHDMIPHY1_HDMI_GTHE4_DRU_REFCLK3_MAX
XHDMIPHY1_HDMI_GTHE4_PLL_SCALE
XHDMIPHY1_HDMI_GTHE4_QPLL0_REFCLK_MIN
XHDMIPHY1_HDMI_GTHE4_QPLL1_REFCLK_MIN
XHDMIPHY1_HDMI_GTHE4_CPLL_REFCLK_MIN
XHDMIPHY1_HDMI_GTHE4_TX_MMCM_SCALE
XHDMIPHY1_HDMI_GTHE4_TX_MMCM_FVCO_MIN
XHDMIPHY1_HDMI_GTHE4_TX_MMCM_FVCO_MAX
XHDMIPHY1_HDMI_GTHE4_RX_MMCM_SCALE
XHDMIPHY1_HDMI_GTHE4_RX_MMCM_FVCO_MIN
XHDMIPHY1_HDMI_GTHE4_RX_MMCM_FVCO_MAX
XHDMIPHY1_FRL_VIDCLK_MMCM_FBOUTMULT
XHDMIPHY1_FRL_VIDCLK_MMCM_DIVCLK
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT0DIV
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT1DIV
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT2DIV
XHDMIPHY1_FRL_VIDCLK_MMCM_FBOUTMULT10
XHDMIPHY1_FRL_VIDCLK_MMCM_DIVCLK10
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT0DIV10
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT1DIV10
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT2DIV10
XHDMIPHY1_FRL_VIDCLK_MMCM_FBOUTMULT8
XHDMIPHY1_FRL_VIDCLK_MMCM_DIVCLK8
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT0DIV8
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT1DIV8
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT2DIV8
XHDMIPHY1_FRL_VIDCLK_MMCM_FBOUTMULT6
XHDMIPHY1_FRL_VIDCLK_MMCM_DIVCLK6
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT0DIV6
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT1DIV6
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT2DIV6
XHDMIPHY1_FRL_VIDCLK_MMCM_FBOUTMULT6x3
XHDMIPHY1_FRL_VIDCLK_MMCM_DIVCLK6x3
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT0DIV6x3
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT1DIV6x3
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT2DIV6x3
XHDMIPHY1_FRL_VIDCLK_MMCM_FBOUTMULT3x3
XHDMIPHY1_FRL_VIDCLK_MMCM_DIVCLK3x3
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT0DIV3x3
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT1DIV3x3
XHDMIPHY1_FRL_VIDCLK_MMCM_CLKOUT2DIV3x3
u32 XHdmiphy1_HdmiTxPllParam(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId)
u32 XHdmiphy1_HdmiRxPllParam(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId)
void XHdmiphy1_ClkDetEnable(XHdmiphy1 *InstancePtr, u8 Enable)
This function enables the HDMIPHY's detector peripheral.
InstancePtr is a pointer to the XHdmiphy1 core instance. Enable specifies TRUE/FALSE value to either enable or disable the clock detector respectively. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_CLKDET_CTRL_REG, XHDMIPHY1_CLKDET_CTRL_RUN_MASK, XHdmiphy1_ReadReg, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
void XHdmiphy1_ClkDetTimerClear(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir)
This function clears the clock detector TX/RX timer.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for RX or TX. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_CLKDET_CTRL_REG, XHDMIPHY1_CLKDET_CTRL_RX_TMR_CLR_MASK, XHDMIPHY1_CLKDET_CTRL_TX_TMR_CLR_MASK, XHdmiphy1_ReadReg, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_HdmiRxClkDetFreqChangeHandler, XHdmiphy1_HdmiTxClkDetFreqChangeHandler.
void XHdmiphy1_ClkDetSetFreqLockThreshold(XHdmiphy1 *InstancePtr, u16 ThresholdVal)
This function sets the clock detector frequency lock counter threshold value.
InstancePtr is a pointer to the XHdmiphy1 core instance. ThresholdVal is the threshold value to be set. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_CLKDET_CTRL_FREQ_LOCK_THRESH_SHIFT, XHDMIPHY1_CLKDET_CTRL_REG, XHDMIPHY1_CLKDET_CTRL_RX_FREQ_RST_MASK, XHdmiphy1_ReadReg, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
void XHdmiphy1_ClkDetAccuracyRange(XHdmiphy1 *InstancePtr, u16 ThresholdVal)
This function sets the clock detector accuracy range value.
InstancePtr is a pointer to the XHdmiphy1 core instance. ThresholdVal is the threshold value to be set. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_CLKDET_CTRL_ACCURACY_RANGE_MASK, XHDMIPHY1_CLKDET_CTRL_ACCURACY_RANGE_SHIFT, XHDMIPHY1_CLKDET_CTRL_REG, XHdmiphy1_ReadReg, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
u8 XHdmiphy1_ClkDetCheckFreqZero(XHdmiphy1 *InstancePtr, XHdmiphy1_DirectionType Dir)
This function checks clock detector RX/TX frequency zero indicator bit.
InstancePtr is a pointer to the XHdmiphy1 core instance. Dir is an indicator for RX or TX. - TRUE if zero frequency. FALSE otherwise, if non-zero frequency. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_CLKDET_STAT_RX_FREQ_ZERO_MASK, XHDMIPHY1_CLKDET_STAT_TX_FREQ_ZERO_MASK, XHDMIPHY1_DRU_STAT_REG, XHdmiphy1_ReadReg.
void XHdmiphy1_ClkDetSetFreqTimeout(XHdmiphy1 *InstancePtr, u32 TimeoutVal)
This function sets clock detector frequency lock counter threshold value.
InstancePtr is a pointer to the XHdmiphy1 core instance. TimeoutVal is the timeout value and is normally the system clock frequency. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_CLKDET_FREQ_TMR_TO_REG, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
void XHdmiphy1_ClkDetTimerLoad(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir, u32 TimeoutVal)
This function loads the timer to TX/RX in the clock detector.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for RX or TX. TimeoutVal is the timeout value to store in the clock detector. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_CLKDET_TMR_RX_REG, XHDMIPHY1_CLKDET_TMR_TX_REG, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_HdmiRxClkDetFreqChangeHandler, XHdmiphy1_HdmiTxClkDetFreqChangeHandler.
void XHdmiphy1_DruReset(XHdmiphy1 *InstancePtr, XHdmiphy1_ChannelId ChId, u8 Reset)
This function resets the DRU in the HDMIPHY.
InstancePtr is a pointer to the XHdmiphy1 core instance. ChId is the channel ID to operate on. Reset specifies TRUE/FALSE value to either enable or disable the DRU respectively. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_Ch2Ids, XHDMIPHY1_DRU_CTRL_REG, XHDMIPHY1_DRU_CTRL_RST_MASK, XHdmiphy1_ReadReg, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize, XHdmiphy1_HdmiGtRxResetDoneLockHandler, XHdmiphy1_HdmiRxClkDetFreqChangeHandler.
void XHdmiphy1_DruEnable(XHdmiphy1 *InstancePtr, XHdmiphy1_ChannelId ChId, u8 Enable)
This function enabled/disables the DRU in the HDMIPHY.
InstancePtr is a pointer to the XHdmiphy1 core instance. ChId is the channel ID to operate on. Enable specifies TRUE/FALSE value to either enable or disable the DRU, respectively. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_Ch2Ids, XHDMIPHY1_DRU_CTRL_EN_MASK, XHDMIPHY1_DRU_CTRL_REG, XHdmiphy1_ReadReg, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize, XHdmiphy1_HdmiRxClkDetFreqChangeHandler, XHdmiphy1_HdmiRxTimerTimeoutHandler.
u16 XHdmiphy1_DruGetVersion(XHdmiphy1 *InstancePtr)
This function gets the DRU version.
InstancePtr is a pointer to the XHdmiphy1 core instance. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_DRU_STAT_REG, XHDMIPHY1_DRU_STAT_VERSION_MASK, XHDMIPHY1_DRU_STAT_VERSION_SHIFT, XHdmiphy1_ReadReg.
Referenced by XHdmiphy1_HdmiDebugInfo.
void XHdmiphy1_DruSetCenterFreqHz(XHdmiphy1 *InstancePtr, XHdmiphy1_ChannelId ChId, u64 CenterFreqHz)
This function sets the DRU center frequency.
InstancePtr is a pointer to the XHdmiphy1 core instance. ChId specifies the channel ID. CenterFreqHz is the frequency value to set. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_Ch2Ids, XHDMIPHY1_DRU_CFREQ_H_MASK, XHDMIPHY1_DRU_CFREQ_H_REG, XHDMIPHY1_DRU_CFREQ_L_REG, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_SetHdmiRxParam.
u64 XHdmiphy1_DruCalcCenterFreqHz(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId)
This function calculates the center frequency value for the DRU.
InstancePtr is a pointer to the XHdmiphy1 GT core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. The calculated DRU Center frequency value. According to XAPP1240: Center_f = fDIN * (2^32)/fdruclk The DRU clock is derived from the measured reference clock and the current QPLL settings.
References XHdmiphy1::Quads, XHdmiphy1_Channel::RxOutDiv, XHDMIPHY1_CH2IDX, XHdmiphy1_ClkDetGetRefClkFreqHz, XHdmiphy1_DruGetRefClkFreqHz.
Referenced by XHdmiphy1_SetHdmiRxParam.
void XHdmiphy1_HdmiGtDruModeEnable(XHdmiphy1 *InstancePtr, u8 Enable)
This function sets the GT RX CDR and Equalization for DRU mode.
InstancePtr is a pointer to the XHdmiphy1 core instance. Enable enables the DRU logic (when 1), or disables (when 0). None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_Ch2Ids, XHDMIPHY1_LOG_EVT_DRU_EN, XHdmiphy1_LogWrite, XHdmiphy1_ReadReg, XHDMIPHY1_RX_EQ_CDR_REG, XHDMIPHY1_RX_STATUS_RXCDRHOLD_MASK, XHDMIPHY1_RX_STATUS_RXLPMHFOVRDEN_MASK, XHDMIPHY1_RX_STATUS_RXLPMLFKLOVRDEN_MASK, XHDMIPHY1_RX_STATUS_RXOSOVRDEN_MASK, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_HdmiRxTimerTimeoutHandler.
void XHdmiphy1_PatgenSetRatio(XHdmiphy1 *InstancePtr, u8 QuadId, u64 TxLineRate)
This function sets the Pattern Generator for the GT Channel 4 when it is used to generate the TX TMDS Clock.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. TxLineRate in Mbps. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1::HdmiTxSampleRate, XHDMIPHY1_PATGEN_CTRL_RATIO_MASK, XHDMIPHY1_PATGEN_CTRL_REG, XHDMIPHY1_Patgen_Ratio_40, XHdmiphy1_ReadReg, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_HdmiGtTxResetDoneLockHandler.
void XHdmiphy1_PatgenEnable(XHdmiphy1 *InstancePtr, u8 QuadId, u8 Enable)
This function enables or disables the Pattern Generator for the GT Channel 4 when it isused to generate the TX TMDS Clock.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Enable TRUE/FALSE None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_PATGEN_CTRL_ENABLE_MASK, XHDMIPHY1_PATGEN_CTRL_REG, XHdmiphy1_ReadReg, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_HdmiGtTxResetDoneLockHandler, XHdmiphy1_HdmiTxClkDetFreqChangeHandler.
void XHdmiphy1_HdmiIntrHandlerCallbackInit(XHdmiphy1 *InstancePtr)
This function sets the appropriate HDMI interrupt handlers.
InstancePtr is a pointer to the HDMIPHY instance. None. None.
References XHdmiphy1_SetIntrHandler.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.