xhdmiphy1.h
XV_HDMIPHY1_LOG_ENABLE
XPAR_HDMIPHY1_0_TRANSCEIVER
XPAR_HDMIPHY1_0_SPEEDGRADE_STR
XHDMIPHY1_GTHE4
XHDMIPHY1_GTYE4
XHDMIPHY1_GTYE5
XHDMIPHY1_GTYP
XHDMIPHY1_CH2IDX
Convert channel ID to array index.
This macro converts a channel ID to the corresponding array index by subtracting the base channel ID. Id Channel ID to convert. Array index corresponding to the channel ID.
Referenced by XHdmiphy1_CfgLineRate, XHdmiphy1_CfgPllRefClkSel, XHdmiphy1_CfgSysClkDataSel, XHdmiphy1_CfgSysClkOutSel, XHdmiphy1_DruCalcCenterFreqHz, XHdmiphy1_GetPllVcoFreqHz, XHdmiphy1_Hdmi_CfgInitialize, XHdmiphy1_HdmiCpllLockHandler, XHdmiphy1_HdmiCpllParam, XHdmiphy1_HdmiDebugInfo, XHdmiphy1_HdmiGtRxResetDoneLockHandler, XHdmiphy1_HdmiGtTxAlignDoneLockHandler, XHdmiphy1_HdmiGtTxResetDoneLockHandler, XHdmiphy1_HdmiQpllLockHandler, XHdmiphy1_HdmiQpllParam, XHdmiphy1_HdmiRxClkDetFreqChangeHandler, XHdmiphy1_HdmiRxTimerTimeoutHandler, XHdmiphy1_HdmiTxClkDetFreqChangeHandler, XHdmiphy1_HdmiTxTimerTimeoutHandler, XHdmiphy1_HdmiUpdateClockSelection, XHdmiphy1_PllCalculator.
XHDMIPHY1_ISCH
Check if channel ID is a regular channel.
This macro checks if the given channel ID represents a regular channel (channel A or channels 1-4). Id Channel ID to check. Non-zero if the ID is a regular channel, 0 otherwise.
Referenced by XHdmiphy1_ClkReconfig, XHdmiphy1_OutDivReconfig, XHdmiphy1_PllCalculator, XHdmiphy1_PowerDownGtPll.
XHDMIPHY1_ISCMN
Check if channel ID is a common channel.
This macro checks if the given channel ID represents a common channel (common channel A or common channels 0-1). Id Channel ID to check. Non-zero if the ID is a common channel, 0 otherwise.
Referenced by XHdmiphy1_ClkReconfig, XHdmiphy1_PllCalculator.
XHDMIPHY1_ISTXMMCM
Check if channel ID is the TX MMCM channel.
This macro checks if the given channel ID represents the transmit MMCM channel. Id Channel ID to check. Non-zero if the ID is the TX MMCM channel, 0 otherwise.
XHDMIPHY1_ISRXMMCM
Check if channel ID is the RX MMCM channel.
This macro checks if the given channel ID represents the receive MMCM channel. Id Channel ID to check. Non-zero if the ID is the RX MMCM channel, 0 otherwise.
XHdmiphy1_IsTxUsingQpll
Check if TX is using QPLL.
This macro checks if the transmit channel is using any QPLL type (QPLL, QPLL0, or QPLL1) for the specified channel. InstancePtr Pointer to the HDMI PHY instance. QuadId Quad ID. ChId Channel ID. Non-zero if TX is using QPLL, 0 otherwise.
Referenced by XHdmiphy1_Hdmi_CfgInitialize, XHdmiphy1_HdmiDebugInfo.
XHdmiphy1_IsRxUsingQpll
Check if RX is using QPLL.
This macro checks if the receive channel is using any QPLL type (QPLL, QPLL0, or QPLL1) for the specified channel. InstancePtr Pointer to the HDMI PHY instance. QuadId Quad ID. ChId Channel ID. Non-zero if RX is using QPLL, 0 otherwise.
Referenced by XHdmiphy1_Hdmi_CfgInitialize, XHdmiphy1_HdmiDebugInfo.
XHdmiphy1_IsTxUsingCpll
Check if TX is using CPLL.
This macro checks if the transmit channel is using CPLL for the specified channel. InstancePtr Pointer to the HDMI PHY instance. QuadId Quad ID. ChId Channel ID. Non-zero if TX is using CPLL, 0 otherwise.
Referenced by XHdmiphy1_HdmiDebugInfo, XHdmiphy1_SetHdmiTxParam.
XHdmiphy1_IsRxUsingCpll
Check if RX is using CPLL.
This macro checks if the receive channel is using CPLL for the specified channel. InstancePtr Pointer to the HDMI PHY instance. QuadId Quad ID. ChId Channel ID. Non-zero if RX is using CPLL, 0 otherwise.
Referenced by XHdmiphy1_HdmiDebugInfo, XHdmiphy1_SetHdmiRxParam.
XHdmiphy1_GtType
XHdmiphy1_ProtocolType
XHdmiphy1_DirectionType
XHdmiphy1_ClkPrimitive
XHdmiphy1_IntrHandlerType
XHdmiphy1_HdmiHandlerType
TX init handler.
XHdmiphy1_PllType
XHdmiphy1_ChannelId
XHdmiphy1_PllRefClkSelType
XHdmiphy1_SysClkDataSelType
XHdmiphy1_SysClkOutSelType
XHdmiphy1_OutClkSelType
XHdmiphy1_GtState
Idle state.
XHdmiphy1_LogEvent
Log event none.
XHdmiphy1_MmcmDivType
XHdmiphy1_MmcmClkinsel
XHdmiphy1_HdmiTx_Patgen
LR:Clock Ratio = 10.
XHdmiphy1_PrbsPattern
Pattern gen/mon OFF.
typedef void(* XHdmiphy1_IntrHandler)(void *InstancePtr))(void *InstancePtr)
Callback type which represents the handler for interrupts.
InstancePtr is a pointer to the XHdmiphy1 instance. None.
typedef void(* XHdmiphy1_TimerHandler)(void *InstancePtr, u32 MicroSeconds))(void *InstancePtr, u32 MicroSeconds)
Callback type which represents a custom timer wait handler.
This is only used for Microblaze since it doesn't have a native sleep function. To avoid dependency on a hardware timer, the default wait functionality is implemented using loop iterations; this isn't too accurate. If a custom timer handler is used, the user may implement their own wait implementation using a hardware timer (see example/) for better accuracy. InstancePtr is a pointer to the XHdmiphy1 instance. MicroSeconds is the number of microseconds to be passed to the timer function. None.
typedef void(* XHdmiphy1_Callback)(void *CallbackRef))(void *CallbackRef)
Generic callback type.
CallbackRef is a pointer to the callback reference. None.
typedef u64(* XHdmiphy1_LogCallback)(void *CallbackRef))(void *CallbackRef)
Generic callback type.
CallbackRef is a pointer to the callback reference. u8 value.
typedef void(* XHdmiphy1_ErrorCallback)(void *CallbackRef))(void *CallbackRef)
Error callback type.
CallbackRef is a pointer to the callback reference. None.
void XHdmiphy1_CfgInitialize(XHdmiphy1 *InstancePtr, XHdmiphy1_Config *ConfigPtr, UINTPTR EffectiveAddr)
This function retrieves the configuration for this Video PHY instance and fills in the InstancePtr->Config structure.
InstancePtr is a pointer to the XHdmiphy1 instance. ConfigPtr is a pointer to the configuration structure that will be used to copy the settings from. EffectiveAddr is the device base address in the virtual memory space. If the address translation is not used, then the physical address is passed. None. Unexpected errors may occur if the address mapping is changed after this function is invoked.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_Config::DruRefClkSel, XHdmiphy1::IsReady, XHdmiphy1_Config::RxFrlRefClkSel, XHdmiphy1_Config::RxRefClkSel, XHdmiphy1_Config::RxSysPllClkSel, XHdmiphy1_Config::TxFrlRefClkSel, XHdmiphy1_Config::TxRefClkSel, XHdmiphy1_Config::TxSysPllClkSel, XHdmiphy1_Config::XcvrType.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
u32 XHdmiphy1_PllInitialize(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_PllRefClkSelType QpllRefClkSel, XHdmiphy1_PllRefClkSelType CpllxRefClkSel, XHdmiphy1_PllType TxPllSelect, XHdmiphy1_PllType RxPllSelect)
This function will initialize the PLL selection for a given channel.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. QpllRefClkSel is the QPLL reference clock selection for the quad. CpllRefClkSel is the CPLL reference clock selection for the quad. TxPllSelect is the reference clock selection for the quad's TX PLL dividers. RxPllSelect is the reference clock selection for the quad's RX PLL dividers. XST_SUCCESS. None.
References XHdmiphy1_CfgPllRefClkSel, XHdmiphy1_CfgSysClkDataSel, XHdmiphy1_CfgSysClkOutSel, XHdmiphy1_Pll2SysClkData, XHdmiphy1_Pll2SysClkOut, XHdmiphy1_WriteCfgRefClkSelReg.
u32 XHdmiphy1_GetVersion(XHdmiphy1 *InstancePtr)
This function will obtian the IP version.
InstancePtr is a pointer to the XHdmiphy1 core instance. The IP version of the Video PHY core. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_ReadReg, XHDMIPHY1_VERSION_REG.
void XHdmiphy1_WaitUs(XHdmiphy1 *InstancePtr, u32 MicroSeconds)
This function is the delay/sleep function for the XHdmiphy1 driver.
For the Zynq family, there exists native sleep functionality. For MicroBlaze however, there does not exist such functionality. In the MicroBlaze case, the default method for delaying is to use a predetermined amount of loop iterations. This method is prone to inaccuracy and dependent on system configuration; for greater accuracy, the user may supply their own delay/sleep handler, pointed to by InstancePtr->UserTimerWaitUs, which may have better accuracy if a hardware timer is used. InstancePtr is a pointer to the XHdmiphy1 instance. MicroSeconds is the number of microseconds to delay/sleep for. None. None.
References XHdmiphy1::IsReady, XHdmiphy1::UserTimerWaitUs.
void XHdmiphy1_SetUserTimerHandler(XHdmiphy1 *InstancePtr, XHdmiphy1_TimerHandler CallbackFunc, void *CallbackRef)
u32 XHdmiphy1_CfgLineRate(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, u64 LineRateHz)
Configure the channel's line rate.
This is a software only configuration and this value is used in the PLL calculator. InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. LineRateHz is the line rate to configure software. XST_SUCCESS if the reference clock type is valid.XST_FAILURE otherwise. None.
References XHdmiphy1_Channel::LineRateHz, XHdmiphy1::Quads, XHdmiphy1_Ch2Ids, XHDMIPHY1_CH2IDX.
Referenced by XHdmiphy1_HdmiCpllParam, XHdmiphy1_HdmiQpllParam.
XHdmiphy1_PllType XHdmiphy1_GetPllType(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir, XHdmiphy1_ChannelId ChId)
Obtain the channel's PLL reference clock selection.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. ChId is the channel ID which to operate on. The PLL type being used by the channel. None.
References XHdmiphy1::Config, XHdmiphy1_Config::RxSysPllClkSel, XHdmiphy1_Config::TxSysPllClkSel, XHdmiphy1_GetSysClkDataSel, XHdmiphy1_GetSysClkOutSel.
Referenced by XHdmiphy1_Hdmi20Config, XHdmiphy1_Hdmi21Config, XHdmiphy1_HdmiCfgCalcMmcmParam, XHdmiphy1_HdmiCpllLockHandler, XHdmiphy1_HdmiGtTxResetDoneLockHandler, XHdmiphy1_HdmiQpllLockHandler, XHdmiphy1_HdmiRxClkDetFreqChangeHandler, XHdmiphy1_HdmiRxTimerTimeoutHandler, XHdmiphy1_HdmiTxClkDetFreqChangeHandler, XHdmiphy1_HdmiTxTimerTimeoutHandler, XHdmiphy1_IsPllLocked, XHdmiphy1_SetHdmiRxParam.
u64 XHdmiphy1_GetLineRateHz(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId)
This function will return the line rate in Hz for a given channel / quad.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to check. ChId is the channel ID for which to retrieve the line rate. The line rate in Hz. None.
References XHdmiphy1_Channel::LineRateHz, XHdmiphy1::Quads.
Referenced by XHdmiphy1_HdmiCpllParam, XHdmiphy1_HdmiGtTxResetDoneLockHandler, XHdmiphy1_HdmiQpllParam.
u32 XHdmiphy1_ResetGtPll(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir, u8 Hold)
This function will reset the GT's PLL logic.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID which to operate on. Dir is an indicator for TX or RX. Hold is an indicator whether to "hold" the reset if set to 1. If set to 0: reset, then enable. XST_SUCCESS. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_ReadReg, XHDMIPHY1_RX_INIT_REG, XHDMIPHY1_TX_INIT_REG, XHDMIPHY1_TXRX_INIT_PLLGTRESET_ALL_MASK, XHDMIPHY1_TXRX_INIT_PLLGTRESET_MASK, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize, XHdmiphy1_HdmiRxClkDetFreqChangeHandler, XHdmiphy1_HdmiRxTimerTimeoutHandler, XHdmiphy1_HdmiTxClkDetFreqChangeHandler, XHdmiphy1_HdmiTxTimerTimeoutHandler, XHdmiphy1_HdmiUpdateClockSelection.
u32 XHdmiphy1_ResetGtTxRx(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir, u8 Hold)
This function will reset the GT's TX/RX logic.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID which to operate on. Dir is an indicator for TX or RX. Hold is an indicator whether to "hold" the reset if set to 1. If set to 0: reset, then enable. XST_SUCCESS. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_ReadReg, XHDMIPHY1_RX_INIT_REG, XHDMIPHY1_TX_INIT_REG, XHDMIPHY1_TXRX_INIT_GTRESET_ALL_MASK, XHDMIPHY1_TXRX_INIT_GTRESET_MASK, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_HdmiCpllLockHandler, XHdmiphy1_HdmiQpllLockHandler.
u32 XHdmiphy1_SetPolarity(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir, u8 Polarity)
This function will set/clear the TX/RX polarity bit.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID which to operate on. Dir is an indicator for TX or RX. Polarity 0-Not inverted 1-Inverted XST_SUCCESS. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_ReadReg, XHDMIPHY1_RX_CONTROL_REG, XHDMIPHY1_RX_CONTROL_RXPOLARITY_ALL_MASK, XHDMIPHY1_RX_CONTROL_RXPOLARITY_MASK, XHDMIPHY1_TX_CONTROL_REG, XHDMIPHY1_TX_CONTROL_TXPOLARITY_ALL_MASK, XHDMIPHY1_TX_CONTROL_TXPOLARITY_MASK, XHdmiphy1_WriteReg.
u32 XHdmiphy1_SetPrbsSel(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir, XHdmiphy1_PrbsPattern Pattern)
This function will set the TX/RXPRBSEL of the GT.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID which to operate on. Dir is an indicator for TX or RX. Pattern is the pattern XHdmiphy1_PrbsPattern XST_SUCCESS. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_Ch2Ids, XHdmiphy1_ReadReg, XHDMIPHY1_RX_CONTROL_REG, XHDMIPHY1_RX_CONTROL_RXPRBSSEL_ALL_MASK, XHDMIPHY1_RX_CONTROL_RXPRBSSEL_MASK, XHDMIPHY1_RX_CONTROL_RXPRBSSEL_SHIFT, XHDMIPHY1_TX_CONTROL_REG, XHDMIPHY1_TX_CONTROL_TXPRBSSEL_ALL_MASK, XHDMIPHY1_TX_CONTROL_TXPRBSSEL_MASK, XHDMIPHY1_TX_CONTROL_TXPRBSSEL_SHIFT, XHdmiphy1_WriteReg.
u32 XHdmiphy1_TxPrbsForceError(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, u8 ForceErr)
This function will force an error in the TX PRBS pattern for the GT.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID which to operate on. ForceErr 0-No Error 1-Force Error XST_SUCCESS. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_ReadReg, XHDMIPHY1_TX_CONTROL_REG, XHDMIPHY1_TX_CONTROL_TXPRBSFORCEERR_ALL_MASK, XHDMIPHY1_TX_CONTROL_TXPRBSFORCEERR_MASK, XHdmiphy1_WriteReg.
void XHdmiphy1_SetTxVoltageSwing(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, u8 Vs)
This function will set the TX voltage swing value for a given channel.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. Vs is the voltage swing value to write. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_ReadReg, XHDMIPHY1_TX_DRIVER_CH12_REG, XHDMIPHY1_TX_DRIVER_CH34_REG, XHDMIPHY1_TX_DRIVER_EXT_REG, XHDMIPHY1_TX_DRIVER_EXT_TXDIFFCTRL_MASK, XHDMIPHY1_TX_DRIVER_EXT_TXDIFFCTRL_SHIFT, XHDMIPHY1_TX_DRIVER_TXDIFFCTRL_MASK, XHDMIPHY1_TX_DRIVER_TXDIFFCTRL_SHIFT, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
void XHdmiphy1_SetTxPreEmphasis(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, u8 Pe)
This function will set the TX pre-emphasis value for a given channel.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. Pe is the pre-emphasis value to write. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_ReadReg, XHDMIPHY1_TX_DRIVER_CH12_REG, XHDMIPHY1_TX_DRIVER_CH34_REG, XHDMIPHY1_TX_DRIVER_TXPRECURSOR_MASK, XHDMIPHY1_TX_DRIVER_TXPRECURSOR_SHIFT, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
void XHdmiphy1_SetTxPostCursor(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, u8 Pc)
This function will set the TX post-cursor value for a given channel.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. Pc is the post-cursor value to write. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_ReadReg, XHDMIPHY1_TX_DRIVER_CH12_REG, XHDMIPHY1_TX_DRIVER_CH34_REG, XHDMIPHY1_TX_DRIVER_TXPOSTCURSOR_MASK, XHDMIPHY1_TX_DRIVER_TXPOSTCURSOR_SHIFT, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
void XHdmiphy1_SetRxLpm(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir, u8 Enable)
This function will enable or disable the LPM logic in the Video PHY core.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. Dir is an indicator for TX or RX. Enable will enable (if 1) or disable (if 0) the LPM logic. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_ReadReg, XHDMIPHY1_RX_CONTROL_RXLPMEN_ALL_MASK, XHDMIPHY1_RX_CONTROL_RXLPMEN_MASK, XHDMIPHY1_RX_EQ_CDR_REG, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
u32 XHdmiphy1_DrpWr(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, u16 Addr, u16 Val)
This function will initiate a write DRP transaction.
It is a wrapper around XHdmiphy1_DrpAccess. InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID on which to direct the DRP access. Addr is the DRP address to issue the DRP access to. Val is the value to write to the DRP address. XST_SUCCESS if the DRP access was successful.XST_FAILURE otherwise, if the busy bit did not go low, or if the ready bit did not go high. None.
u16 XHdmiphy1_DrpRd(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, u16 Addr, u16 *RetVal)
This function will initiate a read DRP transaction.
It is a wrapper around XHdmiphy1_DrpAccess. InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID on which to direct the DRP access. Addr is the DRP address to issue the DRP access to. RetVal is the DRP read_value returned implicitly. XST_SUCCESS if the DRP access was successful.XST_FAILURE otherwise, if the busy bit did not go low, or if the ready bit did not go high. None.
Referenced by XHdmiphy1_RegisterDebug.
void XHdmiphy1_MmcmPowerDown(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir, u8 Hold)
This function will power down the mixed-mode clock manager (MMCM) core.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. Hold is an indicator whether to "hold" the power down if set to 1. If set to 0: power down, then power back up. XST_SUCCESS. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_MMCM_RXUSRCLK_CTRL_REG, XHDMIPHY1_MMCM_TXUSRCLK_CTRL_REG, XHDMIPHY1_MMCM_USRCLK_CTRL_PWRDWN_MASK, XHdmiphy1_ReadReg, XHdmiphy1_WriteReg.
void XHdmiphy1_MmcmStart(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir)
This function will start the mixed-mode clock manager (MMCM) core.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. None. None.
References XHdmiphy1::Config, XHdmiphy1::Quads, XHdmiphy1_Config::RxClkPrimitive, XHdmiphy1_Quad::RxMmcm, XHdmiphy1_Config::TxClkPrimitive, XHdmiphy1_Quad::TxMmcm, XHDMIPHY1_LOG_EVT_RXPLL_RECONFIG, XHDMIPHY1_LOG_EVT_TXPLL_RECONFIG, XHdmiphy1_LogWrite, XHdmiphy1_MmcmLockedMaskEnable, XHdmiphy1_MmcmReset.
Referenced by XHdmiphy1_Hdmi21Config, XHdmiphy1_HdmiRxTimerTimeoutHandler, XHdmiphy1_HdmiTxTimerTimeoutHandler.
void XHdmiphy1_IBufDsEnable(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir, u8 Enable)
This function enables the TX or RX IBUFDS peripheral.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. Enable specifies TRUE/FALSE value to either enable or disable the IBUFDS, respectively. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_Config::DruIsPresent, XHdmiphy1_Config::DruRefClkSel, XHdmiphy1_Config::RxRefClkSel, XHdmiphy1_Config::TxRefClkSel, XHDMIPHY1_IBUFDS_GTXX_CTRL_GTREFCLK0_CEB_MASK, XHDMIPHY1_IBUFDS_GTXX_CTRL_GTREFCLK1_CEB_MASK, XHDMIPHY1_IBUFDS_GTXX_CTRL_REG, XHDMIPHY1_MISC_RXUSRCLK_REG, XHDMIPHY1_MISC_TXUSRCLK_REG, XHDMIPHY1_MISC_XXUSRCLK_REFCLK_CEB_MASK, XHdmiphy1_ReadReg, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
void XHdmiphy1_Clkout1OBufTdsEnable(XHdmiphy1 *InstancePtr, XHdmiphy1_DirectionType Dir, u8 Enable)
This function enables the TX or RX CLKOUT1 OBUFTDS peripheral.
InstancePtr is a pointer to the XHdmiphy1 core instance. Dir is an indicator for TX or RX. Enable specifies TRUE/FALSE value to either enable or disable the OBUFTDS, respectively. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_MISC_RXUSRCLK_REG, XHDMIPHY1_MISC_TXUSRCLK_REG, XHDMIPHY1_MISC_XXUSRCLK_CKOUT1_OEN_MASK, XHdmiphy1_ReadReg, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi21Config.
void XHdmiphy1_SetErrorCallback(XHdmiphy1 *InstancePtr, void *CallbackFunc, void *CallbackRef)
This function installs a callback function for the HDMIPHY error conditions.
InstancePtr is a pointer to the XHdmiphy1 instance. CallbackFunc is the address to the callback function. CallbackRef is the user data item that will be passed to the callback function when it is invoked. None. The XHdmiphy1_ErrorHandler API calls the registered function in ErrorCallback and passes two arguments: 1) CallbackRef 2) Error Type as defined by XHdmiphy1_ErrType. Sample Function Call: CallbackFunc(CallbackRef, XHdmiphy1_ErrType);
References XHdmiphy1::ErrorCallback, XHdmiphy1::ErrorRef.
void XHdmiphy1_SetLogCallback(XHdmiphy1 *InstancePtr, u64 *CallbackFunc, void *CallbackRef)
This function installs an asynchronous callback function for the LogWrite API:
InstancePtr is a pointer to the XHdmiphy1 instance. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. None.
References XHdmiphy1::LogWriteCallback, XHdmiphy1::LogWriteRef.
void XHdmiphy1_LogDisplay(XHdmiphy1 *InstancePtr)
This function will print the entire log.
InstancePtr is a pointer to the XHdmiphy1 core instance. None. None.
References XHdmiphy1::Log, XHdmiphy1::LogWriteCallback, XHdmiphy1_Log::TailIndex, XHdmiphy1_Log::TimeRecord, XHDMIPHY1_LOG_EVT_1PPC_ERR, XHDMIPHY1_LOG_EVT_CPLL_EN, XHDMIPHY1_LOG_EVT_CPLL_LOCK, XHDMIPHY1_LOG_EVT_CPLL_RECONFIG, XHDMIPHY1_LOG_EVT_CPLL_RST, XHDMIPHY1_LOG_EVT_DRU_CLK_ERR, XHDMIPHY1_LOG_EVT_DRU_EN, XHDMIPHY1_LOG_EVT_FRL_RECONFIG, XHDMIPHY1_LOG_EVT_GT_CPLL_CFG_ERR, XHDMIPHY1_LOG_EVT_GT_LCPLL_CFG_ERR, XHDMIPHY1_LOG_EVT_GT_QPLL_CFG_ERR, XHDMIPHY1_LOG_EVT_GT_RECONFIG, XHDMIPHY1_LOG_EVT_GT_RPLL_CFG_ERR, XHDMIPHY1_LOG_EVT_GT_RX_RECONFIG, XHDMIPHY1_LOG_EVT_GT_TX_RECONFIG, XHDMIPHY1_LOG_EVT_GTRX_RST, XHDMIPHY1_LOG_EVT_GTTX_RST, XHDMIPHY1_LOG_EVT_HDMI20_ERR, XHDMIPHY1_LOG_EVT_INIT, XHDMIPHY1_LOG_EVT_LCPLL_LOCK, XHDMIPHY1_LOG_EVT_MMCM_ERR, XHDMIPHY1_LOG_EVT_NO_DRU, XHDMIPHY1_LOG_EVT_NO_QPLL_ERR, XHDMIPHY1_LOG_EVT_NONE, XHDMIPHY1_LOG_EVT_PPC_MSMTCH_ERR, XHDMIPHY1_LOG_EVT_QPLL_EN, XHDMIPHY1_LOG_EVT_QPLL_LOCK, XHDMIPHY1_LOG_EVT_QPLL_RECONFIG, XHDMIPHY1_LOG_EVT_QPLL_RST, XHDMIPHY1_LOG_EVT_RPLL_LOCK, XHDMIPHY1_LOG_EVT_RX_FREQ, XHDMIPHY1_LOG_EVT_RX_RST_DONE, XHDMIPHY1_LOG_EVT_RX_TMR, XHDMIPHY1_LOG_EVT_RXGPO_RE, XHDMIPHY1_LOG_EVT_RXPLL_EN, XHDMIPHY1_LOG_EVT_RXPLL_LOCK, XHDMIPHY1_LOG_EVT_RXPLL_RECONFIG, XHDMIPHY1_LOG_EVT_RXPLL_RST, XHDMIPHY1_LOG_EVT_SPDGRDE_ERR, XHDMIPHY1_LOG_EVT_TMDS_RECONFIG, XHDMIPHY1_LOG_EVT_TX_ALIGN, XHDMIPHY1_LOG_EVT_TX_ALIGN_TMOUT, XHDMIPHY1_LOG_EVT_TX_FREQ, XHDMIPHY1_LOG_EVT_TX_RST_DONE, XHDMIPHY1_LOG_EVT_TX_TMR, XHDMIPHY1_LOG_EVT_TXGPO_RE, XHDMIPHY1_LOG_EVT_TXPLL_EN, XHDMIPHY1_LOG_EVT_TXPLL_LOCK, XHDMIPHY1_LOG_EVT_TXPLL_RECONFIG, XHDMIPHY1_LOG_EVT_TXPLL_RST, XHDMIPHY1_LOG_EVT_USRCLK_ERR, XHDMIPHY1_LOG_EVT_VD_NOT_SPRTD_ERR, XHDMIPHY1_LOG_EVT_VDCLK_HIGH_ERR, XHDMIPHY1_LOG_EVT_VID_RX_RST, XHDMIPHY1_LOG_EVT_VID_TX_RST, XHdmiphy1_LogRead.
void XHdmiphy1_LogReset(XHdmiphy1 *InstancePtr)
This function will reset the driver's logging mechanism.
InstancePtr is a pointer to the XHdmiphy1 core instance. None. None.
References XHdmiphy1_Log::HeadIndex, XHdmiphy1::Log, XHdmiphy1_Log::TailIndex.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
u16 XHdmiphy1_LogRead(XHdmiphy1 *InstancePtr)
This function will read the last event from the log.
InstancePtr is a pointer to the XHdmiphy1 core instance. The log data. None.
References XHdmiphy1_Log::DataBuffer, XHdmiphy1_Log::HeadIndex, XHdmiphy1::Log, XHdmiphy1_Log::TailIndex.
Referenced by XHdmiphy1_LogDisplay.
void XHdmiphy1_LogWrite(XHdmiphy1 *InstancePtr, XHdmiphy1_LogEvent Evt, u8 Data)
This function will insert an event in the driver's logging mechanism.
InstancePtr is a pointer to the XHdmiphy1 core instance. Evt is the event type to log. Data is the associated data for the event. None. None.
References XHdmiphy1_Log::DataBuffer, XHdmiphy1_Log::HeadIndex, XHdmiphy1::Log, XHdmiphy1::LogWriteCallback, XHdmiphy1::LogWriteRef, XHdmiphy1_Log::TailIndex, XHdmiphy1_Log::TimeRecord, XHDMIPHY1_LOG_EVT_DUMMY.
Referenced by XHdmiphy1_ClkReconfig, XHdmiphy1_DirReconfig, XHdmiphy1_Hdmi20Config, XHdmiphy1_Hdmi21Config, XHdmiphy1_Hdmi_CfgInitialize, XHdmiphy1_HdmiCfgCalcMmcmParam, XHdmiphy1_HdmiCpllLockHandler, XHdmiphy1_HdmiCpllParam, XHdmiphy1_HdmiGtDruModeEnable, XHdmiphy1_HdmiGtRxResetDoneLockHandler, XHdmiphy1_HdmiGtTxAlignDoneLockHandler, XHdmiphy1_HdmiGtTxResetDoneLockHandler, XHdmiphy1_HdmiQpllLockHandler, XHdmiphy1_HdmiQpllParam, XHdmiphy1_HdmiRxClkDetFreqChangeHandler, XHdmiphy1_HdmiRxMmcmLockHandler, XHdmiphy1_HdmiRxTimerTimeoutHandler, XHdmiphy1_HdmiTxClkDetFreqChangeHandler, XHdmiphy1_HdmiTxMmcmLockHandler, XHdmiphy1_HdmiTxTimerTimeoutHandler, XHdmiphy1_MmcmStart, XHdmiphy1_OutDivReconfig, XHdmiphy1_SetHdmiTxParam.
void XHdmiphy1_InterruptHandler(XHdmiphy1 *InstancePtr)
This function is the interrupt handler for the XHdmiphy1 driver.
It will detect what kind of interrupt has happened, and will invoke the appropriate callback function. InstancePtr is a pointer to the XHdmiphy1 instance. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1::IntrCpllLockCallbackRef, XHdmiphy1::IntrCpllLockHandler, XHdmiphy1::IntrQpll1LockCallbackRef, XHdmiphy1::IntrQpll1LockHandler, XHdmiphy1::IntrQpllLockCallbackRef, XHdmiphy1::IntrQpllLockHandler, XHdmiphy1::IntrRxClkDetFreqChangeCallbackRef, XHdmiphy1::IntrRxClkDetFreqChangeHandler, XHdmiphy1::IntrRxMmcmLockCallbackRef, XHdmiphy1::IntrRxMmcmLockHandler, XHdmiphy1::IntrRxResetDoneCallbackRef, XHdmiphy1::IntrRxResetDoneHandler, XHdmiphy1::IntrRxTmrTimeoutCallbackRef, XHdmiphy1::IntrRxTmrTimeoutHandler, XHdmiphy1::IntrTxAlignDoneCallbackRef, XHdmiphy1::IntrTxAlignDoneHandler, XHdmiphy1::IntrTxClkDetFreqChangeCallbackRef, XHdmiphy1::IntrTxClkDetFreqChangeHandler, XHdmiphy1::IntrTxMmcmLockCallbackRef, XHdmiphy1::IntrTxMmcmLockHandler, XHdmiphy1::IntrTxResetDoneCallbackRef, XHdmiphy1::IntrTxResetDoneHandler, XHdmiphy1::IntrTxTmrTimeoutCallbackRef, XHdmiphy1::IntrTxTmrTimeoutHandler, XHdmiphy1::IsReady, XHDMIPHY1_INTR_CPLL_LOCK_MASK, XHDMIPHY1_INTR_LCPLL_LOCK_MASK, XHDMIPHY1_INTR_QPLL1_LOCK_MASK, XHDMIPHY1_INTR_QPLL_LOCK_MASK, XHDMIPHY1_INTR_RPLL_LOCK_MASK, XHDMIPHY1_INTR_RXCLKDETFREQCHANGE_MASK, XHDMIPHY1_INTR_RXGPO_RE_MASK, XHDMIPHY1_INTR_RXMMCMUSRCLK_LOCK_MASK, XHDMIPHY1_INTR_RXRESETDONE_MASK, XHDMIPHY1_INTR_RXTMRTIMEOUT_MASK, XHDMIPHY1_INTR_STS_REG, XHDMIPHY1_INTR_TXALIGNDONE_MASK, XHDMIPHY1_INTR_TXCLKDETFREQCHANGE_MASK, XHDMIPHY1_INTR_TXGPO_RE_MASK, XHDMIPHY1_INTR_TXMMCMUSRCLK_LOCK_MASK, XHDMIPHY1_INTR_TXRESETDONE_MASK, XHDMIPHY1_INTR_TXTMRTIMEOUT_MASK, XHdmiphy1_ReadReg.
u32 XHdmiphy1_SelfTest(XHdmiphy1 *InstancePtr)
This function runs a self-test on the XHdmiphy1 driver/device.
The sanity test checks whether or not all tested registers hold their default reset values. InstancePtr is a pointer to the XHdmiphy1 instance. XST_SUCCESS if the self-test passed - all tested registers hold their default reset values.XST_FAILURE otherwise. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_ReadReg.
XHdmiphy1_Config* XHdmiphy1_LookupConfig(UINTPTR BaseAddress)
This function looks for the device configuration based on the unique device ID.
The table XHdmiphy1_ConfigTable[] contains the configuration information for each device in the system. DeviceId is the unique device ID of the device being looked up. A pointer to the configuration table entry corresponding to the given device ID, or NULL if no match is found. None. This function looks for the device configuration based on the base address. The table XHdmiphy1_ConfigTable[] contains the configuration information for each device in the system. BaseAddress is the base address of the device being looked up. A pointer to the configuration table entry corresponding to the given base address, or NULL if no match is found. None.
u32 XHdmiphy1_GetDrvIndex(XHdmiphy1 *InstancePtr, UINTPTR BaseAddress)
u32 XHdmiphy1_Hdmi_CfgInitialize(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_Config *CfgPtr)
This function initializes the Video PHY for HDMI.
InstancePtr is a pointer to the XHdmiphy1 instance. CfgPtr is a pointer to the configuration structure that will be used to copy the settings from. QuadId is the GT quad ID to operate on. None. None.
References XHdmiphy1_Config::AxiLiteClkFreq, XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_Config::DruIsPresent, XHdmiphy1::HdmiIsQpllPresent, XHdmiphy1::IsReady, XHdmiphy1::Quads, XHdmiphy1_Channel::RxState, XHdmiphy1_Config::TransceiverWidth, XHdmiphy1_Channel::TxState, XHdmiphy1_Config::XcvrType, XHdmiphy1_CfgInitialize, XHdmiphy1_Ch2Ids, XHDMIPHY1_CH2IDX, XHdmiphy1_ClkDetAccuracyRange, XHdmiphy1_ClkDetEnable, XHdmiphy1_ClkDetSetFreqLockThreshold, XHdmiphy1_ClkDetSetFreqTimeout, XHdmiphy1_DruEnable, XHdmiphy1_DruReset, XHDMIPHY1_GT_STATE_IDLE, XHdmiphy1_HdmiIntrHandlerCallbackInit, XHdmiphy1_IBufDsEnable, XHDMIPHY1_INTR_STS_REG, XHdmiphy1_IntrDisable, XHdmiphy1_IntrEnable, XHdmiphy1_IsHDMI, XHdmiphy1_IsRxUsingQpll, XHdmiphy1_IsTxUsingQpll, XHDMIPHY1_LOG_EVT_INIT, XHdmiphy1_LogReset, XHdmiphy1_LogWrite, XHdmiphy1_MmcmReset, XHdmiphy1_PowerDownGtPll, XHdmiphy1_ResetGtPll, XHdmiphy1_SetBufgGtDiv, XHdmiphy1_SetRxLpm, XHdmiphy1_SetTxPostCursor, XHdmiphy1_SetTxPreEmphasis, XHdmiphy1_SetTxVoltageSwing, XHdmiphy1_WriteReg.
u32 XHdmiphy1_SetHdmiTxParam(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XVidC_PixelsPerClock Ppc, XVidC_ColorDepth Bpc, XVidC_ColorFormat ColorFormat)
This function update/set the HDMI TX parameter.
InstancePtr is a pointer to the Hdmiphy core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. Ppc is the pixels per clock to set. Bpc is the bits per color to set. ColorFormat is the color format to set. XST_SUCCESS if TX parameters set/updated.XST_FAILURE if low resolution video not supported. None.
References XHdmiphy1::Config, XHdmiphy1_Hdmi21Cfg::IsEnabled, XHdmiphy1_Config::Ppc, XHdmiphy1::TxHdmi21Cfg, XHdmiphy1_ErrorHandler, XHdmiphy1_HdmiCfgCalcMmcmParam, XHdmiphy1_HdmiCpllParam, XHdmiphy1_HdmiQpllParam, XHdmiphy1_IsTxUsingCpll, XHDMIPHY1_LOG_EVT_PPC_MSMTCH_ERR, XHdmiphy1_LogWrite, XHdmiphy1_WriteCfgRefClkSelReg.
Referenced by XHdmiphy1_Hdmi21Config.
u32 XHdmiphy1_SetHdmiRxParam(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId)
This function update/set the HDMI RX parameter.
InstancePtr is a pointer to the Hdmiphy core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. XST_SUCCESS if RX parameters set/updated.XST_FAILURE if low resolution video not supported. None.
References XHdmiphy1::HdmiRxDruIsEnabled, XHdmiphy1_DruCalcCenterFreqHz, XHdmiphy1_DruSetCenterFreqHz, XHdmiphy1_GetPllType, XHdmiphy1_GetRcfgChId, XHdmiphy1_HdmiCpllParam, XHdmiphy1_HdmiQpllParam, XHdmiphy1_IsRxUsingCpll, XHdmiphy1_WriteCfgRefClkSelReg.
Referenced by XHdmiphy1_HdmiRxTimerTimeoutHandler.
u32 XHdmiphy1_HdmiCfgCalcMmcmParam(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir, XVidC_PixelsPerClock Ppc, XVidC_ColorDepth Bpc)
This function calculates the HDMI MMCM parameters.
InstancePtr is a pointer to the Hdmiphy core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. Dir is an indicator for RX or TX. Ppc specifies the total number of pixels per clock. 1 = XVIDC_PPC_12 = XVIDC_PPC_24 = XVIDC_PPC_4 Bpc specifies the color depth/bits per color component. 6 = XVIDC_BPC_68 = XVIDC_BPC_810 = XVIDC_BPC_1012 = XVIDC_BPC_1216 = XVIDC_BPC_16 XST_SUCCESS if calculated PLL parameters updated successfully.XST_FAILURE if parameters not updated. None.
References XHdmiphy1::Config, XHdmiphy1::HdmiRxRefClkHz, XHdmiphy1::HdmiRxTmdsClockRatio, XHdmiphy1::HdmiTxRefClkHz, XHdmiphy1::HdmiTxSampleRate, XHdmiphy1_Channel::LineRateHz, XHdmiphy1::Quads, XHdmiphy1_Config::RxClkPrimitive, XHdmiphy1_Quad::RxMmcm, XHdmiphy1_Config::TransceiverWidth, XHdmiphy1_Config::TxClkPrimitive, XHdmiphy1_Quad::TxMmcm, XHdmiphy1_ErrorHandler, XHdmiphy1_GetPllType, XHDMIPHY1_LOG_EVT_1PPC_ERR, XHdmiphy1_LogWrite.
Referenced by XHdmiphy1_SetHdmiTxParam.
void XHdmiphy1_HdmiUpdateClockSelection(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_SysClkDataSelType TxSysPllClkSel, XHdmiphy1_SysClkDataSelType RxSysPllClkSel)
This function Updates the HDMIPHY clocking.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. TxSysPllClkSel is the SYSCLKDATA selection for TX. RxSysPllClkSel is the SYSCLKDATA selection for RX. None. None.
References XHdmiphy1::Config, XHdmiphy1::Quads, XHdmiphy1_Channel::RxState, XHdmiphy1_Config::RxSysPllClkSel, XHdmiphy1_Channel::TxState, XHdmiphy1_Config::TxSysPllClkSel, XHdmiphy1_Ch2Ids, XHDMIPHY1_CH2IDX, XHDMIPHY1_GT_STATE_IDLE, XHdmiphy1_ResetGtPll.
void XHdmiphy1_ClkDetFreqReset(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir)
This function resets clock detector TX/RX frequency.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for RX or TX. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_CLKDET_CTRL_REG, XHDMIPHY1_CLKDET_CTRL_RX_FREQ_RST_MASK, XHDMIPHY1_CLKDET_CTRL_TX_FREQ_RST_MASK, XHdmiphy1_ReadReg, XHdmiphy1_WriteReg.
u32 XHdmiphy1_ClkDetGetRefClkFreqHz(XHdmiphy1 *InstancePtr, XHdmiphy1_DirectionType Dir)
This function returns the frequency of the RX/TX reference clock as measured by the clock detector peripheral.
InstancePtr is a pointer to the XHdmiphy1 core instance. Dir is an indicator for RX or TX. The measured frequency of the RX/TX reference clock. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_Hdmi21Cfg::IsEnabled, XHdmiphy1_Config::RxFrlRefClkSel, XHdmiphy1::RxHdmi21Cfg, XHdmiphy1_Config::RxRefClkSel, XHdmiphy1_Config::TxFrlRefClkSel, XHdmiphy1::TxHdmi21Cfg, XHdmiphy1_Config::TxRefClkSel, XHDMIPHY1_CLKDET_FREQ_RX_FRL_REG, XHDMIPHY1_CLKDET_FREQ_RX_REG, XHDMIPHY1_CLKDET_FREQ_TX_FRL_REG, XHDMIPHY1_CLKDET_FREQ_TX_REG, XHdmiphy1_ReadReg.
Referenced by XHdmiphy1_DruCalcCenterFreqHz, XHdmiphy1_HdmiRxClkDetFreqChangeHandler, XHdmiphy1_HdmiTxClkDetFreqChangeHandler.
u32 XHdmiphy1_ClkDetGetRefClkFreqHzRaw(XHdmiphy1 *InstancePtr, XHdmiphy1_DirectionType Dir)
This function returns the raw (unconditional) frequency of the RX/TX reference clock as measured by the clock detector peripheral.
Unlike XHdmiphy1_ClkDetGetRefClkFreqHz, this function always returns the measured value regardless of lock status - useful for debugging. InstancePtr is a pointer to the XHdmiphy1 core instance. Dir is an indicator for RX or TX. The raw measured frequency of the RX/TX reference clock. This function returns the actual measured frequency value even when lock conditions are not met. Use this for debugging to determine if a clock is present vs not locked.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_CLKDET_FREQ_RX_RAW_REG, XHDMIPHY1_CLKDET_FREQ_TX_RAW_REG, XHdmiphy1_ReadReg.
u32 XHdmiphy1_DruGetRefClkFreqHz(XHdmiphy1 *InstancePtr)
This function returns the frequency of the DRU reference clock as measured by the clock detector peripheral.
InstancePtr is a pointer to the XHdmiphy1 core instance. The measured frequency of the DRU reference clock. The design must have a DRU for this function to return a valid value.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1::versal_2ve_2vm, XHdmiphy1_Config::XcvrType, XHDMIPHY1_CLKDET_FREQ_DRU_REG, XHdmiphy1_ReadReg.
Referenced by XHdmiphy1_DruCalcCenterFreqHz, XHdmiphy1_GetPllVcoFreqHz, XHdmiphy1_HdmiCpllParam, XHdmiphy1_HdmiQpllParam.
u32 XHdmiphy1_DruGetRefClkFreqHzRaw(XHdmiphy1 *InstancePtr)
This function returns the raw (unconditional) frequency of the DRU reference clock as measured by the clock detector peripheral.
Unlike XHdmiphy1_DruGetRefClkFreqHz, this function always returns the measured value without any range checking - useful for debugging. InstancePtr is a pointer to the XHdmiphy1 core instance. The raw measured frequency of the DRU reference clock. This function returns the actual measured frequency value without range validation. Use this for debugging to see the raw DRU clock measurement independent of expected frequency ranges.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHDMIPHY1_CLKDET_FREQ_DRU_RAW_REG, XHdmiphy1_ReadReg.
void XHdmiphy1_HdmiDebugInfo(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId)
This function prints Video PHY debug information related to HDMI.
InstancePtr is a pointer to the Hdmiphy core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_Config::DruIsPresent, XHdmiphy1::HdmiRxDruIsEnabled, XHdmiphy1::Quads, XHdmiphy1_Config::RxClkPrimitive, XHdmiphy1_Channel::RxDataRefClkSel, XHdmiphy1_Quad::RxMmcm, XHdmiphy1_Channel::RxOutDiv, XHdmiphy1_Config::TxClkPrimitive, XHdmiphy1_Channel::TxDataRefClkSel, XHdmiphy1_Quad::TxMmcm, XHdmiphy1_Channel::TxOutDiv, XHDMIPHY1_CH2IDX, XHDMIPHY1_DRU_CFREQ_H_REG, XHDMIPHY1_DRU_CFREQ_L_REG, XHDMIPHY1_DRU_GAIN_G1_MASK, XHDMIPHY1_DRU_GAIN_G1_P_MASK, XHDMIPHY1_DRU_GAIN_G1_P_SHIFT, XHDMIPHY1_DRU_GAIN_G2_MASK, XHDMIPHY1_DRU_GAIN_G2_SHIFT, XHDMIPHY1_DRU_GAIN_REG, XHdmiphy1_DruGetVersion, XHDMIPHY1_GT_STATE_ALIGN, XHDMIPHY1_GT_STATE_GPO_RE, XHDMIPHY1_GT_STATE_IDLE, XHDMIPHY1_GT_STATE_LOCK, XHDMIPHY1_GT_STATE_READY, XHDMIPHY1_GT_STATE_RESET, XHdmiphy1_IsHDMI, XHdmiphy1_IsRxUsingCpll, XHdmiphy1_IsRxUsingQpll, XHdmiphy1_IsTxUsingCpll, XHdmiphy1_IsTxUsingQpll, XHdmiphy1_ReadReg.
void XHdmiphy1_SetHdmiCallback(XHdmiphy1 *InstancePtr, XHdmiphy1_HdmiHandlerType HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs an HDMI callback function for the specified handler type.
InstancePtr is a pointer to the XHdmiphy1 instance. HandlerType is the interrupt handler type which specifies which interrupt event to attach the callback for. CallbackFunc is the address to the callback function. CallbackRef is the user data item that will be passed to the callback function when it is invoked. None. None.
References XHdmiphy1::HdmiRxInitCallback, XHdmiphy1::HdmiRxInitRef, XHdmiphy1::HdmiRxReadyCallback, XHdmiphy1::HdmiRxReadyRef, XHdmiphy1::HdmiTxInitCallback, XHdmiphy1::HdmiTxInitRef, XHdmiphy1::HdmiTxReadyCallback, XHdmiphy1::HdmiTxReadyRef, XHDMIPHY1_HDMI_HANDLER_RXINIT, XHDMIPHY1_HDMI_HANDLER_RXREADY, XHDMIPHY1_HDMI_HANDLER_TXINIT, XHDMIPHY1_HDMI_HANDLER_TXREADY.
u32 XHdmiphy1_Hdmi20Config(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir)
This function will configure the HDMIPHY to HDMI 2.0 mode.
InstancePtr is a pointer to the Hdmiphy core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for RX or TX. XST_SUCCESS if TX parameters set/updated.XST_FAILURE if low resolution video not supported. None.
References XHdmiphy1::Config, XHdmiphy1_Hdmi21Cfg::IsEnabled, XHdmiphy1_Hdmi21Cfg::LineRate, XHdmiphy1_Hdmi21Cfg::NChannels, XHdmiphy1::RxHdmi21Cfg, XHdmiphy1_Config::RxRefClkSel, XHdmiphy1::TxHdmi21Cfg, XHdmiphy1_Config::TxRefClkSel, XHdmiphy1_CfgPllRefClkSel, XHdmiphy1_GetPllType, XHdmiphy1_IntrEnable, XHDMIPHY1_LOG_EVT_TMDS_RECONFIG, XHdmiphy1_LogWrite, XHdmiphy1_MmcmSetClkinsel, XHdmiphy1_WriteCfgRefClkSelReg.
u32 XHdmiphy1_Hdmi21Config(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir, u64 LineRate, u8 NChannels)
This function will configure the GT for HDMI 2.1 operation.
InstancePtr is a pointer to the Hdmiphy core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for RX or TX. LineRate is the line rate for HDMI 2.1 operation. NChannels is the number of channels for HDMI 2.1 operation. XST_SUCCESS if TX parameters set/updated.XST_FAILURE if low resolution video not supported. None.
References XHdmiphy1::Config, XHdmiphy1::HdmiRxRefClkHz, XHdmiphy1::HdmiTxRefClkHz, XHdmiphy1_Hdmi21Cfg::IsEnabled, XHdmiphy1_Hdmi21Cfg::LineRate, XHdmiphy1_Hdmi21Cfg::NChannels, XHdmiphy1_Config::Ppc, XHdmiphy1_Config::RxFrlRefClkSel, XHdmiphy1::RxHdmi21Cfg, XHdmiphy1_Config::RxRefClkSel, XHdmiphy1_Config::TxFrlRefClkSel, XHdmiphy1::TxHdmi21Cfg, XHdmiphy1_Config::TxRefClkSel, XHdmiphy1_CfgPllRefClkSel, XHdmiphy1_Clkout1OBufTdsEnable, XHdmiphy1_ErrorHandler, XHdmiphy1_GetPllType, XHdmiphy1_HdmiRxTimerTimeoutHandler, XHdmiphy1_HdmiTxTimerTimeoutHandler, XHdmiphy1_IntrDisable, XHDMIPHY1_LOG_EVT_FRL_RECONFIG, XHDMIPHY1_LOG_EVT_SPDGRDE_ERR, XHdmiphy1_LogWrite, XHdmiphy1_MmcmLockedMaskEnable, XHdmiphy1_MmcmSetClkinsel, XHdmiphy1_MmcmStart, Xhdmiphy1_RefClkValue, XHdmiphy1_SetHdmiTxParam, XHdmiphy1_WriteCfgRefClkSelReg.
void XHdmiphy1_RegisterDebug(XHdmiphy1 *InstancePtr)
This function prints out Video PHY register and GT Channel and Common DRP register contents.
InstancePtr is a pointer to the Hdmiphy core instance. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1::HdmiIsQpllPresent, XHdmiphy1_Config::RxChannels, XHdmiphy1_Config::TxChannels, XHdmiphy1_Config::XcvrType, XHdmiphy1_DrpRd, XHdmiphy1_ReadReg.