xhdmiphy1_hdmi_intr.c
void XHdmiphy1_Ch2Ids(XHdmiphy1 *InstancePtr, XHdmiphy1_ChannelId ChId, u8 *Id0, u8 *Id1)
This function will set the channel IDs to correspond with the supplied channel ID based on the protocol.
HDMI uses 3 channels; This ID translation is done to allow other functions to operate iteratively over multiple channels. InstancePtr is a pointer to the XHdmiphy1 core instance. ChId is the channel ID used to determine the indices. Id0 is a pointer to the start channel ID to set. Id1 is a pointer to the end channel ID to set. None. The contents of Id0 and Id1 will be set according to ChId.
u32 Xhdmiphy1_RefClkValue(void)
This function will configure the FRL REF CLK for HDMI 2.1 operation.
FRL Ref Clk value None.
Referenced by XHdmiphy1_Hdmi21Config, XHdmiphy1_HdmiRxClkDetFreqChangeHandler.
void XHdmiphy1_HdmiGtHandler(XHdmiphy1 *InstancePtr)
This function is the interrupt handler for the GT events.
InstancePtr is a pointer to the HDMIPHY instance. None. None.
void XHdmiphy1_ClkDetHandler(XHdmiphy1 *InstancePtr)
This function is the interrupt handler for the clock detector events.
InstancePtr is a pointer to the HDMIPHY instance. None. None.
void XHdmiphy1_SetHdmiCallback(XHdmiphy1 *InstancePtr, XHdmiphy1_HdmiHandlerType HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs an HDMI callback function for the specified handler type.
InstancePtr is a pointer to the XHdmiphy1 instance. HandlerType is the interrupt handler type which specifies which interrupt event to attach the callback for. CallbackFunc is the address to the callback function. CallbackRef is the user data item that will be passed to the callback function when it is invoked. None. None.
References XHDMIPHY1_HDMI_HANDLER_TXINIT, XHDMIPHY1_HDMI_HANDLER_TXREADY, XHDMIPHY1_HDMI_HANDLER_RXINIT, XHDMIPHY1_HDMI_HANDLER_RXREADY, XHdmiphy1::HdmiTxInitCallback, XHdmiphy1::HdmiTxInitRef, XHdmiphy1::HdmiTxReadyCallback, XHdmiphy1::HdmiTxReadyRef, XHdmiphy1::HdmiRxInitCallback, XHdmiphy1::HdmiRxInitRef, XHdmiphy1::HdmiRxReadyCallback, XHdmiphy1::HdmiRxReadyRef.
void XHdmiphy1_HdmiIntrHandlerCallbackInit(XHdmiphy1 *InstancePtr)
This function sets the appropriate HDMI interrupt handlers.
InstancePtr is a pointer to the HDMIPHY instance. None. None.
References XHdmiphy1_SetIntrHandler.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
void XHdmiphy1_HdmiQpllLockHandler(XHdmiphy1 *InstancePtr)
This function is the handler for events triggered by QPLL lock done.
InstancePtr is a pointer to the HDMIPHY instance. None. None.
References XHdmiphy1::Quads, XHdmiphy1_Ch2Ids, XHDMIPHY1_CH2IDX, XHdmiphy1_GetPllType, XHdmiphy1_GetRcfgChId, XHDMIPHY1_GT_STATE_RESET, XHdmiphy1_IsPllLocked, XHDMIPHY1_LOG_EVT_QPLL_LOCK, XHdmiphy1_LogWrite, XHdmiphy1_ResetGtTxRx.
void XHdmiphy1_HdmiCpllLockHandler(XHdmiphy1 *InstancePtr)
This function is the handler for events triggered by CPLL lock done.
InstancePtr is a pointer to the HDMIPHY instance. None. None.
References XHdmiphy1::Quads, XHdmiphy1_Ch2Ids, XHDMIPHY1_CH2IDX, XHdmiphy1_GetPllType, XHdmiphy1_GetRcfgChId, XHDMIPHY1_GT_STATE_RESET, XHdmiphy1_IsPllLocked, XHDMIPHY1_LOG_EVT_CPLL_LOCK, XHdmiphy1_LogWrite, XHdmiphy1_ResetGtTxRx.
void XHdmiphy1_HdmiGtTxAlignDoneLockHandler(XHdmiphy1 *InstancePtr)
This function is the handler for events triggered by GT TX alignment done.
InstancePtr is a pointer to the HDMIPHY instance. None. None.
References XHdmiphy1::HdmiTxReadyCallback, XHdmiphy1::HdmiTxReadyRef, XHdmiphy1::Quads, XHdmiphy1_Channel::TxState, XHdmiphy1_Ch2Ids, XHDMIPHY1_CH2IDX, XHDMIPHY1_GT_STATE_READY, XHDMIPHY1_LOG_EVT_TX_ALIGN, XHdmiphy1_LogWrite.
void XHdmiphy1_HdmiGtTxResetDoneLockHandler(XHdmiphy1 *InstancePtr)
This function is the handler for events triggered by GT TX reset lock done.
InstancePtr is a pointer to the HDMIPHY instance. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1::HdmiTxReadyCallback, XHdmiphy1::HdmiTxReadyRef, XHdmiphy1_Hdmi21Cfg::IsEnabled, XHdmiphy1_Hdmi21Cfg::NChannels, XHdmiphy1::Quads, XHdmiphy1::TxHdmi21Cfg, XHdmiphy1_Channel::TxState, XHdmiphy1_Config::UseGtAsTxTmdsClk, XHdmiphy1_Config::XcvrType, XHdmiphy1_Ch2Ids, XHDMIPHY1_CH2IDX, XHdmiphy1_GetLineRateHz, XHdmiphy1_GetPllType, XHdmiphy1_GetRcfgChId, XHDMIPHY1_GT_STATE_ALIGN, XHDMIPHY1_GT_STATE_READY, XHDMIPHY1_LOG_EVT_TX_RST_DONE, XHdmiphy1_LogWrite, XHdmiphy1_PatgenEnable, XHdmiphy1_PatgenSetRatio, XHdmiphy1_ReadReg, XHDMIPHY1_TX_INIT_REG, XHdmiphy1_TxAlignReset, XHdmiphy1_TxAlignStart, XHdmiphy1_WriteReg.
void XHdmiphy1_HdmiGtRxResetDoneLockHandler(XHdmiphy1 *InstancePtr)
This function is the handler for events triggered by GT RX reset lock done.
InstancePtr is a pointer to the HDMIPHY instance. None. None.
References XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1::HdmiRxDruIsEnabled, XHdmiphy1::HdmiRxReadyCallback, XHdmiphy1::HdmiRxReadyRef, XHdmiphy1::Quads, XHdmiphy1_Channel::RxState, XHdmiphy1_Ch2Ids, XHDMIPHY1_CH2IDX, XHdmiphy1_DruReset, XHDMIPHY1_GT_STATE_READY, XHDMIPHY1_LOG_EVT_RX_RST_DONE, XHdmiphy1_LogWrite, XHdmiphy1_ReadReg, XHDMIPHY1_RX_INIT_REG, XHdmiphy1_WriteReg.
void XHdmiphy1_HdmiTxClkDetFreqChangeHandler(XHdmiphy1 *InstancePtr)
This function is the handler for events triggered by a change in TX frequency as detected by the HDMI clock detector logic.
InstancePtr is a pointer to the HDMIPHY instance. None. None.
References XHdmiphy1_Config::AxiLiteClkFreq, XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1::HdmiTxInitCallback, XHdmiphy1::HdmiTxInitRef, XHdmiphy1_Hdmi21Cfg::IsEnabled, XHdmiphy1_Hdmi21Cfg::NChannels, XHdmiphy1::Quads, XHdmiphy1_Config::TxFrlRefClkSel, XHdmiphy1::TxHdmi21Cfg, XHdmiphy1_Config::TxRefClkSel, XHdmiphy1_Channel::TxState, XHdmiphy1_Config::UseGtAsTxTmdsClk, XHdmiphy1_Ch2Ids, XHDMIPHY1_CH2IDX, XHdmiphy1_ClkDetGetRefClkFreqHz, XHdmiphy1_ClkDetTimerClear, XHdmiphy1_ClkDetTimerLoad, XHdmiphy1_GetPllType, XHDMIPHY1_GT_STATE_IDLE, XHDMIPHY1_LOG_EVT_TX_FREQ, XHdmiphy1_LogWrite, XHdmiphy1_MmcmLockedMaskEnable, XHdmiphy1_PatgenEnable, XHdmiphy1_PowerDownGtPll, XHdmiphy1_ReadReg, XHdmiphy1_ResetGtPll, XHDMIPHY1_TX_INIT_REG, XHdmiphy1_TxAlignStart, XHdmiphy1_WriteReg.
void XHdmiphy1_HdmiRxClkDetFreqChangeHandler(XHdmiphy1 *InstancePtr)
This function is the handler for events triggered by a change in RX frequency as detected by the HDMI clock detector logic.
InstancePtr is a pointer to the HDMIPHY instance. None. None.
References XHdmiphy1_Config::AxiLiteClkFreq, XHdmiphy1_Config::BaseAddr, XHdmiphy1::Config, XHdmiphy1_Config::DruIsPresent, XHdmiphy1::HdmiRxInitCallback, XHdmiphy1::HdmiRxInitRef, XHdmiphy1::HdmiRxRefClkHz, XHdmiphy1_Hdmi21Cfg::IsEnabled, XHdmiphy1::Quads, XHdmiphy1_Config::RxFrlRefClkSel, XHdmiphy1::RxHdmi21Cfg, XHdmiphy1_Config::RxRefClkSel, XHdmiphy1_Channel::RxState, XHdmiphy1_Ch2Ids, XHDMIPHY1_CH2IDX, XHdmiphy1_ClkDetGetRefClkFreqHz, XHdmiphy1_ClkDetTimerClear, XHdmiphy1_ClkDetTimerLoad, XHdmiphy1_DruEnable, XHdmiphy1_DruReset, XHdmiphy1_GetPllType, XHDMIPHY1_GT_STATE_IDLE, XHDMIPHY1_LOG_EVT_RX_FREQ, XHdmiphy1_LogWrite, XHdmiphy1_MmcmLockedMaskEnable, XHdmiphy1_PowerDownGtPll, XHdmiphy1_ReadReg, Xhdmiphy1_RefClkValue, XHdmiphy1_ResetGtPll, XHDMIPHY1_RX_INIT_REG, XHdmiphy1_WriteReg.
void XHdmiphy1_HdmiTxTimerTimeoutHandler(XHdmiphy1 *InstancePtr)
This function is the handler for TX timer timeout events.
InstancePtr is a pointer to the HDMIPHY instance. None. None.
References XHdmiphy1::TxHdmi21Cfg, XHdmiphy1_Hdmi21Cfg::IsEnabled, XHdmiphy1_LogWrite, XHDMIPHY1_LOG_EVT_TX_TMR, XHdmiphy1_GetPllType, XHdmiphy1_GetRcfgChId, XHdmiphy1_MmcmStart, XHdmiphy1_PowerDownGtPll, XHdmiphy1_WriteCfgRefClkSelReg, XHdmiphy1_ClkReconfig, XHdmiphy1_OutDivReconfig, XHdmiphy1::Config, XHdmiphy1_Config::XcvrType, XHdmiphy1_SetBufgGtDiv, XHdmiphy1::Quads, XHdmiphy1_Channel::TxOutDiv, XHdmiphy1_DirReconfig, XHdmiphy1_ResetGtPll, XHdmiphy1_TxAlignStart, XHdmiphy1_Ch2Ids, XHDMIPHY1_CH2IDX, XHdmiphy1_Channel::TxState, XHDMIPHY1_GT_STATE_LOCK, XHDMIPHY1_GT_STATE_GPO_RE.
Referenced by XHdmiphy1_Hdmi21Config.
void XHdmiphy1_HdmiRxTimerTimeoutHandler(XHdmiphy1 *InstancePtr)
This function is the handler for RX timer timeout events.
InstancePtr is a pointer to the HDMIPHY instance. None. None.
References XHdmiphy1::RxHdmi21Cfg, XHdmiphy1_Hdmi21Cfg::IsEnabled, XHdmiphy1_LogWrite, XHDMIPHY1_LOG_EVT_RX_TMR, XHdmiphy1::Config, XHdmiphy1_Config::RxRefClkSel, XHdmiphy1_Config::RxFrlRefClkSel, XHdmiphy1_MmcmSetClkinsel, XHdmiphy1_MmcmStart, XHdmiphy1_GetPllType, XHdmiphy1_GetRcfgChId, XHdmiphy1_Ch2Ids, XHdmiphy1_SetHdmiRxParam, XHdmiphy1::Quads, XHDMIPHY1_CH2IDX, XHdmiphy1_Channel::RxState, XHDMIPHY1_GT_STATE_IDLE, XHdmiphy1_DruEnable, XHdmiphy1::HdmiRxDruIsEnabled, XHdmiphy1_HdmiGtDruModeEnable, XHdmiphy1_PowerDownGtPll, XHdmiphy1_CfgPllRefClkSel, XHdmiphy1_Config::DruRefClkSel, XHdmiphy1_WriteCfgRefClkSelReg, XHdmiphy1_ClkReconfig, XHdmiphy1_OutDivReconfig, XHdmiphy1_DirReconfig, XHdmiphy1_ResetGtPll, XHDMIPHY1_GT_STATE_LOCK, XHDMIPHY1_GT_STATE_GPO_RE.
Referenced by XHdmiphy1_Hdmi21Config.
void XHdmiphy1_HdmiTxMmcmLockHandler(XHdmiphy1 *InstancePtr)
This function is the handler for TX MMCM Lock events.
InstancePtr is a pointer to the HDMIPHY instance. None. None.
References XHDMIPHY1_LOG_EVT_TXPLL_LOCK, XHdmiphy1_LogWrite.
void XHdmiphy1_HdmiRxMmcmLockHandler(XHdmiphy1 *InstancePtr)
This function is the handler for RX MMCM Lock events.
InstancePtr is a pointer to the HDMIPHY instance. None. None.
References XHDMIPHY1_LOG_EVT_RXPLL_LOCK, XHdmiphy1_LogWrite.