xhdmiphy1_log.c
ANSI_COLOR_RED
ANSI_COLOR_GREEN
ANSI_COLOR_YELLOW
ANSI_COLOR_BLUE
ANSI_COLOR_MAGENTA
ANSI_COLOR_CYAN
ANSI_COLOR_WHITE
ANSI_COLOR_RESET
void XHdmiphy1_LogReset(XHdmiphy1 *InstancePtr)
This function will reset the driver's logging mechanism.
InstancePtr is a pointer to the XHdmiphy1 core instance. None. None.
References XHdmiphy1::Log, XHdmiphy1_Log::HeadIndex, XHdmiphy1_Log::TailIndex.
Referenced by XHdmiphy1_Hdmi_CfgInitialize.
void XHdmiphy1_LogWrite(XHdmiphy1 *InstancePtr, XHdmiphy1_LogEvent Evt, u8 Data)
This function will insert an event in the driver's logging mechanism.
InstancePtr is a pointer to the XHdmiphy1 core instance. Evt is the event type to log. Data is the associated data for the event. None. None.
References XHdmiphy1::LogWriteCallback, XHdmiphy1::LogWriteRef, XHDMIPHY1_LOG_EVT_DUMMY, XHdmiphy1::Log, XHdmiphy1_Log::DataBuffer, XHdmiphy1_Log::HeadIndex, XHdmiphy1_Log::TimeRecord, XHdmiphy1_Log::TailIndex.
Referenced by XHdmiphy1_MmcmStart, XHdmiphy1_Hdmi_CfgInitialize, XHdmiphy1_HdmiGtDruModeEnable, XHdmiphy1_HdmiCfgCalcMmcmParam, XHdmiphy1_HdmiQpllParam, XHdmiphy1_HdmiCpllParam, XHdmiphy1_SetHdmiTxParam, XHdmiphy1_Hdmi20Config, XHdmiphy1_Hdmi21Config, XHdmiphy1_HdmiQpllLockHandler, XHdmiphy1_HdmiCpllLockHandler, XHdmiphy1_HdmiGtTxAlignDoneLockHandler, XHdmiphy1_HdmiGtTxResetDoneLockHandler, XHdmiphy1_HdmiGtRxResetDoneLockHandler, XHdmiphy1_HdmiTxClkDetFreqChangeHandler, XHdmiphy1_HdmiRxClkDetFreqChangeHandler, XHdmiphy1_HdmiTxTimerTimeoutHandler, XHdmiphy1_HdmiRxTimerTimeoutHandler, XHdmiphy1_HdmiTxMmcmLockHandler, XHdmiphy1_HdmiRxMmcmLockHandler, XHdmiphy1_DirReconfig, XHdmiphy1_OutDivReconfig, XHdmiphy1_ClkReconfig.
u16 XHdmiphy1_LogRead(XHdmiphy1 *InstancePtr)
This function will read the last event from the log.
InstancePtr is a pointer to the XHdmiphy1 core instance. The log data. None.
References XHdmiphy1::Log, XHdmiphy1_Log::TailIndex, XHdmiphy1_Log::HeadIndex, XHdmiphy1_Log::DataBuffer.
Referenced by XHdmiphy1_LogDisplay.
void XHdmiphy1_LogDisplay(XHdmiphy1 *InstancePtr)
This function will print the entire log.
InstancePtr is a pointer to the XHdmiphy1 core instance. None. None.
References XHdmiphy1::Log, XHdmiphy1_Log::TimeRecord, XHdmiphy1_Log::TailIndex, XHdmiphy1_LogRead, XHdmiphy1::LogWriteCallback, XHDMIPHY1_LOG_EVT_NONE, XHDMIPHY1_LOG_EVT_QPLL_EN, XHDMIPHY1_LOG_EVT_QPLL_RST, XHDMIPHY1_LOG_EVT_CPLL_EN, XHDMIPHY1_LOG_EVT_CPLL_RST, XHDMIPHY1_LOG_EVT_TXPLL_EN, XHDMIPHY1_LOG_EVT_TXPLL_RST, XHDMIPHY1_LOG_EVT_RXPLL_EN, XHDMIPHY1_LOG_EVT_RXPLL_RST, XHDMIPHY1_LOG_EVT_GTRX_RST, XHDMIPHY1_LOG_EVT_GTTX_RST, XHDMIPHY1_LOG_EVT_VID_TX_RST, XHDMIPHY1_LOG_EVT_VID_RX_RST, XHDMIPHY1_LOG_EVT_TX_ALIGN, XHDMIPHY1_LOG_EVT_TX_ALIGN_TMOUT, XHDMIPHY1_LOG_EVT_TX_TMR, XHDMIPHY1_LOG_EVT_RX_TMR, XHDMIPHY1_LOG_EVT_CPLL_RECONFIG, XHDMIPHY1_LOG_EVT_GT_RECONFIG, XHDMIPHY1_LOG_EVT_GT_TX_RECONFIG, XHDMIPHY1_LOG_EVT_GT_RX_RECONFIG, XHDMIPHY1_LOG_EVT_QPLL_RECONFIG, XHDMIPHY1_LOG_EVT_INIT, XHDMIPHY1_LOG_EVT_TXPLL_RECONFIG, XHDMIPHY1_LOG_EVT_RXPLL_RECONFIG, XHDMIPHY1_LOG_EVT_QPLL_LOCK, XHDMIPHY1_LOG_EVT_CPLL_LOCK, XHDMIPHY1_LOG_EVT_LCPLL_LOCK, XHDMIPHY1_LOG_EVT_RPLL_LOCK, XHDMIPHY1_LOG_EVT_RXPLL_LOCK, XHDMIPHY1_LOG_EVT_TXPLL_LOCK, XHDMIPHY1_LOG_EVT_TX_RST_DONE, XHDMIPHY1_LOG_EVT_RX_RST_DONE, XHDMIPHY1_LOG_EVT_TX_FREQ, XHDMIPHY1_LOG_EVT_RX_FREQ, XHDMIPHY1_LOG_EVT_DRU_EN, XHDMIPHY1_LOG_EVT_TXGPO_RE, XHDMIPHY1_LOG_EVT_RXGPO_RE, XHDMIPHY1_LOG_EVT_FRL_RECONFIG, XHDMIPHY1_LOG_EVT_TMDS_RECONFIG, XHDMIPHY1_LOG_EVT_1PPC_ERR, XHDMIPHY1_LOG_EVT_PPC_MSMTCH_ERR, XHDMIPHY1_LOG_EVT_VDCLK_HIGH_ERR, XHDMIPHY1_LOG_EVT_NO_DRU, XHDMIPHY1_LOG_EVT_GT_QPLL_CFG_ERR, XHDMIPHY1_LOG_EVT_GT_CPLL_CFG_ERR, XHDMIPHY1_LOG_EVT_GT_LCPLL_CFG_ERR, XHDMIPHY1_LOG_EVT_GT_RPLL_CFG_ERR, XHDMIPHY1_LOG_EVT_VD_NOT_SPRTD_ERR, XHDMIPHY1_LOG_EVT_MMCM_ERR, XHDMIPHY1_LOG_EVT_HDMI20_ERR, XHDMIPHY1_LOG_EVT_NO_QPLL_ERR, XHDMIPHY1_LOG_EVT_DRU_CLK_ERR, XHDMIPHY1_LOG_EVT_USRCLK_ERR, XHDMIPHY1_LOG_EVT_SPDGRDE_ERR.