xhdmiphy1_i.c
void XHdmiphy1_Ch2Ids(XHdmiphy1 *InstancePtr, XHdmiphy1_ChannelId ChId, u8 *Id0, u8 *Id1)
This function will set the channel IDs to correspond with the supplied channel ID based on the protocol.
HDMI uses 3 channels; This ID translation is done to allow other functions to operate iteratively over multiple channels. InstancePtr is a pointer to the XHdmiphy1 core instance. ChId is the channel ID used to determine the indices. Id0 is a pointer to the start channel ID to set. Id1 is a pointer to the end channel ID to set. None. The contents of Id0 and Id1 will be set according to ChId.
References XHdmiphy1_IsHDMI, XHdmiphy1::Config, XHdmiphy1_Config::TxProtocol, XHdmiphy1_Config::RxProtocol, XHdmiphy1_Config::UseGtAsTxTmdsClk, XHdmiphy1_Config::TxChannels, XHdmiphy1_Config::RxChannels, XHdmiphy1_Config::XcvrType.
Referenced by XHdmiphy1_CfgLineRate, XHdmiphy1_SetPrbsSel, XHdmiphy1_Hdmi_CfgInitialize, XHdmiphy1_HdmiUpdateClockSelection, XHdmiphy1_TxAlignReset, XHdmiphy1_TxAlignStart, XHdmiphy1_DruReset, XHdmiphy1_DruEnable, XHdmiphy1_DruSetCenterFreqHz, XHdmiphy1_HdmiGtDruModeEnable, XHdmiphy1_HdmiQpllParam, XHdmiphy1_HdmiCpllParam, XHdmiphy1_HdmiQpllLockHandler, XHdmiphy1_HdmiCpllLockHandler, XHdmiphy1_HdmiGtTxAlignDoneLockHandler, XHdmiphy1_HdmiGtTxResetDoneLockHandler, XHdmiphy1_HdmiGtRxResetDoneLockHandler, XHdmiphy1_HdmiTxClkDetFreqChangeHandler, XHdmiphy1_HdmiRxClkDetFreqChangeHandler, XHdmiphy1_HdmiTxTimerTimeoutHandler, XHdmiphy1_HdmiRxTimerTimeoutHandler, XHdmiphy1_DirReconfig, XHdmiphy1_CfgPllRefClkSel, XHdmiphy1_CfgSysClkDataSel, XHdmiphy1_CfgSysClkOutSel, XHdmiphy1_PowerDownGtPll, XHdmiphy1_ClkCalcParams, XHdmiphy1_OutDivReconfig, XHdmiphy1_ClkReconfig, XHdmiphy1_PllCalculator.
u32 XHdmiphy1_DirReconfig(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir)
This function will set the current RX/TX configuration over DRP.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID for which to write the settings for. Dir is an indicator for RX or TX. XST_SUCCESS if the configuration was successful.XST_FAILURE otherwise. None.
References XHdmiphy1_Ch2Ids, XHdmiphy1_TxChReconfig, XHdmiphy1_RxChReconfig, XHdmiphy1_LogWrite, XHDMIPHY1_LOG_EVT_GT_TX_RECONFIG, XHDMIPHY1_LOG_EVT_GT_RX_RECONFIG.
Referenced by XHdmiphy1_HdmiTxTimerTimeoutHandler, XHdmiphy1_HdmiRxTimerTimeoutHandler.
u32 XHdmiphy1_WriteCfgRefClkSelReg(XHdmiphy1 *InstancePtr, u8 QuadId)
This function writes the current software configuration for the reference clock selections to hardware for the specified quad on all channels.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. XST_SUCCESS. None.
References XHdmiphy1::Config, XHdmiphy1_Config::XcvrType, XHdmiphy1::Quads, XHDMIPHY1_REF_CLK_SEL_QPLL0_MASK, XHDMIPHY1_REF_CLK_SEL_CPLL_MASK, XHdmiphy1_Channel::CpllRefClkSel, XHDMIPHY1_REF_CLK_SEL_CPLL_SHIFT, XHDMIPHY1_REF_CLK_SEL_QPLL1_MASK, XHDMIPHY1_REF_CLK_SEL_QPLL1_SHIFT, XHDMIPHY1_REF_CLK_SEL_SYSCLKSEL_MASK, XHdmiphy1_Channel::TxDataRefClkSel, XHDMIPHY1_REF_CLK_SEL_TXSYSCLKSEL_DATA_SHIFT, XHDMIPHY1_REF_CLK_SEL_TXSYSCLKSEL_DATA_MASK, XHdmiphy1_Channel::RxDataRefClkSel, XHDMIPHY1_REF_CLK_SEL_RXSYSCLKSEL_DATA_SHIFT, XHDMIPHY1_REF_CLK_SEL_RXSYSCLKSEL_DATA_MASK, XHdmiphy1_Channel::TxOutRefClkSel, XHDMIPHY1_REF_CLK_SEL_TXSYSCLKSEL_OUT_SHIFT, XHDMIPHY1_REF_CLK_SEL_TXSYSCLKSEL_OUT_MASK, XHdmiphy1_Channel::RxOutRefClkSel, XHDMIPHY1_REF_CLK_SEL_RXSYSCLKSEL_OUT_SHIFT, XHDMIPHY1_REF_CLK_SEL_RXSYSCLKSEL_OUT_MASK, XHdmiphy1_WriteReg, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_REF_CLK_SEL_REG.
Referenced by XHdmiphy1_PllInitialize, XHdmiphy1_SetHdmiTxParam, XHdmiphy1_SetHdmiRxParam, XHdmiphy1_Hdmi20Config, XHdmiphy1_Hdmi21Config, XHdmiphy1_HdmiTxTimerTimeoutHandler, XHdmiphy1_HdmiRxTimerTimeoutHandler.
void XHdmiphy1_CfgPllRefClkSel(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_PllRefClkSelType RefClkSel)
Configure the PLL reference clock selection for the specified channel(s).
This is applied to both direction to the software configuration only. InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. RefClkSel is the reference clock selection to configure. None. None.
References XHdmiphy1_Ch2Ids, XHdmiphy1::Quads, XHDMIPHY1_CH2IDX.
Referenced by XHdmiphy1_PllInitialize, XHdmiphy1_Hdmi20Config, XHdmiphy1_Hdmi21Config, XHdmiphy1_HdmiRxTimerTimeoutHandler.
void XHdmiphy1_CfgSysClkDataSel(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir, XHdmiphy1_SysClkDataSelType SysClkDataSel)
Configure the SYSCLKDATA reference clock selection for the direction.
Same configuration applies to all channels in the quad. This is applied to the software configuration only. InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. SysClkDataSel is the reference clock selection to configure. None. None.
References XHdmiphy1_Ch2Ids, XHdmiphy1::Quads, XHDMIPHY1_CH2IDX.
Referenced by XHdmiphy1_PllInitialize, XHdmiphy1_HdmiQpllParam.
void XHdmiphy1_CfgSysClkOutSel(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir, XHdmiphy1_SysClkOutSelType SysClkOutSel)
Configure the SYSCLKOUT reference clock selection for the direction.
Same configuration applies to all channels in the quad. This is applied to the software configuration only. InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. SysClkOutSel is the reference clock selection to configure. None. None.
References XHdmiphy1_Ch2Ids, XHdmiphy1::Quads, XHDMIPHY1_CH2IDX.
Referenced by XHdmiphy1_PllInitialize, XHdmiphy1_HdmiQpllParam.
XHdmiphy1_ChannelId XHdmiphy1_GetRcfgChId(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir, XHdmiphy1_PllType PllType)
Obtain the reconfiguration channel ID for given PLL type.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. PllType is the PLL type being used by the channel. The Channel ID to be used for reconfiguration None.
Referenced by XHdmiphy1_SetHdmiRxParam, XHdmiphy1_HdmiQpllLockHandler, XHdmiphy1_HdmiCpllLockHandler, XHdmiphy1_HdmiGtTxResetDoneLockHandler, XHdmiphy1_HdmiTxTimerTimeoutHandler, XHdmiphy1_HdmiRxTimerTimeoutHandler.
u32 XHdmiphy1_IsPllLocked(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId)
This function will check the status of a PLL lock on the specified channel.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID which to operate on. XST_SUCCESS if the specified PLL is locked.XST_FAILURE otherwise. None.
References XHDMIPHY1_PLL_LOCK_STATUS_QPLL0_MASK, XHDMIPHY1_PLL_LOCK_STATUS_LCPLL_MASK, XHDMIPHY1_PLL_LOCK_STATUS_QPLL1_MASK, XHDMIPHY1_PLL_LOCK_STATUS_RPLL_MASK, XHDMIPHY1_PLL_LOCK_STATUS_CPLL_ALL_MASK, XHdmiphy1_GetPllType, XHdmiphy1_IsHDMI, XHDMIPHY1_PLL_LOCK_STATUS_CPLL_HDMI_MASK, XHDMIPHY1_PLL_LOCK_STATUS_CPLL_MASK, XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_PLL_LOCK_STATUS_REG.
Referenced by XHdmiphy1_HdmiQpllLockHandler, XHdmiphy1_HdmiCpllLockHandler.
u32 XHdmiphy1_GetQuadRefClkFreq(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_PllRefClkSelType RefClkType)
Obtain the current reference clock frequency for the quad based on the reference clock type.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. RefClkType is the type to obtain the clock selection for. The current reference clock frequency for the quad for the specified type selection. None.
References XHdmiphy1::Quads.
Referenced by XHdmiphy1_PllCalculator, XHdmiphy1_GetPllVcoFreqHz.
XHdmiphy1_SysClkDataSelType XHdmiphy1_GetSysClkDataSel(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir, XHdmiphy1_ChannelId ChId)
Obtain the current [RT]XSYSCLKSEL[0] configuration.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. ChId is the channel ID which to operate on. The current [RT]XSYSCLKSEL[0] selection. None.
References XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_REF_CLK_SEL_REG, XHDMIPHY1_REF_CLK_SEL_TXSYSCLKSEL_DATA_MASK, XHdmiphy1_Config::XcvrType, XHDMIPHY1_REF_CLK_SEL_TXSYSCLKSEL_DATA_SHIFT, XHDMIPHY1_REF_CLK_SEL_RXSYSCLKSEL_DATA_MASK, XHDMIPHY1_REF_CLK_SEL_RXSYSCLKSEL_DATA_SHIFT.
Referenced by XHdmiphy1_GetPllType.
XHdmiphy1_SysClkOutSelType XHdmiphy1_GetSysClkOutSel(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir, XHdmiphy1_ChannelId ChId)
Obtain the current [RT]XSYSCLKSEL[1] configuration.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. ChId is the channel ID which to operate on. The current [RT]XSYSCLKSEL[1] selection. None.
References XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_REF_CLK_SEL_REG, XHDMIPHY1_REF_CLK_SEL_TXSYSCLKSEL_OUT_MASK, XHdmiphy1_Config::XcvrType, XHDMIPHY1_REF_CLK_SEL_TXSYSCLKSEL_OUT_SHIFT, XHDMIPHY1_REF_CLK_SEL_RXSYSCLKSEL_OUT_MASK, XHDMIPHY1_REF_CLK_SEL_RXSYSCLKSEL_OUT_SHIFT.
Referenced by XHdmiphy1_GetPllType.
u32 XHdmiphy1_GtUserRdyEnable(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir, u8 Hold)
This function will reset and enable the Video PHY's user core logic.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID which to operate on. Dir is an indicator for TX or RX. Hold is an indicator whether to "hold" the reset if set to 1. If set to 0: reset, then enable. XST_SUCCESS. None.
References XHDMIPHY1_TX_INIT_REG, XHDMIPHY1_TX_INIT_USERRDY_ALL_MASK, XHDMIPHY1_TX_INIT_USERRDY_MASK, XHDMIPHY1_RX_INIT_REG, XHDMIPHY1_RX_INIT_USERRDY_ALL_MASK, XHDMIPHY1_RX_INIT_USERRDY_MASK, XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHdmiphy1_WriteReg.
void XHdmiphy1_MmcmReset(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir, u8 Hold)
This function will reset the mixed-mode clock manager (MMCM) core.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. Hold is an indicator whether to "hold" the reset if set to 1. If set to 0: reset, then enable. XST_SUCCESS. None.
References XHDMIPHY1_MMCM_TXUSRCLK_CTRL_REG, XHDMIPHY1_MMCM_RXUSRCLK_CTRL_REG, XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_MMCM_USRCLK_CTRL_RST_MASK, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_MmcmStart, XHdmiphy1_Hdmi_CfgInitialize.
void XHdmiphy1_MmcmLockedMaskEnable(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir, u8 Enable)
This function will reset the mixed-mode clock manager (MMCM) core.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. Enable is an indicator whether to "Enable" the locked mask if set to 1. If set to 0: reset, then disable. None. None.
References XHDMIPHY1_MMCM_TXUSRCLK_CTRL_REG, XHDMIPHY1_MMCM_RXUSRCLK_CTRL_REG, XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_MMCM_USRCLK_CTRL_LOCKED_MASK_MASK, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_MmcmStart, XHdmiphy1_Hdmi21Config, XHdmiphy1_HdmiTxClkDetFreqChangeHandler, XHdmiphy1_HdmiRxClkDetFreqChangeHandler.
u8 XHdmiphy1_MmcmLocked(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir)
This function will get the lock status of the mixed-mode clock manager (MMCM) core.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. TRUE if Locked else FALSE. None.
References XHDMIPHY1_MMCM_TXUSRCLK_CTRL_REG, XHDMIPHY1_MMCM_RXUSRCLK_CTRL_REG, XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_MMCM_USRCLK_CTRL_LOCKED_MASK.
void XHdmiphy1_MmcmSetClkinsel(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_DirectionType Dir, XHdmiphy1_MmcmClkinsel Sel)
This function will set the CLKINSEL port of the MMCM.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. Dir is an indicator for TX or RX. Sel CLKINSEL value 0 - CLKIN1 1 - CLKIN2 None. None.
References XHDMIPHY1_MMCM_TXUSRCLK_CTRL_REG, XHDMIPHY1_MMCM_RXUSRCLK_CTRL_REG, XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_MMCM_USRCLK_CTRL_CLKINSEL_MASK, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi20Config, XHdmiphy1_Hdmi21Config, XHdmiphy1_HdmiRxTimerTimeoutHandler.
void XHdmiphy1_SetBufgGtDiv(XHdmiphy1 *InstancePtr, XHdmiphy1_DirectionType Dir, u8 Div)
This function obtains the divider value of the BUFG_GT peripheral.
InstancePtr is a pointer to the XHdmiphy1 core instance. Dir is an indicator for TX or RX Div 3-bit divider value None.
References XHDMIPHY1_BUFGGT_TXUSRCLK_REG, XHDMIPHY1_BUFGGT_RXUSRCLK_REG, XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_BUFGGT_XXUSRCLK_DIV_MASK, XHDMIPHY1_BUFGGT_XXUSRCLK_DIV_SHIFT, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize, XHdmiphy1_HdmiTxTimerTimeoutHandler.
u32 XHdmiphy1_PowerDownGtPll(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, u8 Hold)
This function will power down the specified GT PLL.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to power down the PLL for. Hold is an indicator whether to "hold" the power down if set to 1. If set to 0: power down, then power back up. XST_SUCCESS. None.
References XHDMIPHY1_ISCH, XHdmiphy1_Ch2Ids, XHDMIPHY1_POWERDOWN_CONTROL_QPLL0PD_MASK, XHDMIPHY1_POWERDOWN_CONTROL_QPLL1PD_MASK, XHDMIPHY1_POWERDOWN_CONTROL_CPLLPD_MASK, XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_POWERDOWN_CONTROL_REG, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize, XHdmiphy1_HdmiTxClkDetFreqChangeHandler, XHdmiphy1_HdmiRxClkDetFreqChangeHandler, XHdmiphy1_HdmiTxTimerTimeoutHandler, XHdmiphy1_HdmiRxTimerTimeoutHandler.
u32 XHdmiphy1_ClkCalcParams(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir, u32 PllClkInFreqHz)
This function will try to find the necessary PLL divisor values to produce the configured line rate given the specified PLL input frequency.
This will be done for all channels specified by ChId. This function is a wrapper for XHdmiphy1_PllCalculator. InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to calculate the PLL values for. ChId is the channel ID to calculate the PLL values for. Dir is an indicator for TX or RX. PllClkInFreqHz is the PLL input frequency on which to base the calculations on. A value of 0 indicates to use the currently configured quad PLL reference clock. A non-zero value indicates to ignore what is currently configured in SW, and use a custom frequency instead. XST_SUCCESS if valid PLL values were found to satisfy the constraints.XST_FAILURE otherwise. If successful, the channel's PllParams structure will be modified with the valid PLL parameters.
References XHdmiphy1_Ch2Ids, XHdmiphy1_PllCalculator.
Referenced by XHdmiphy1_HdmiQpllParam, XHdmiphy1_HdmiCpllParam.
u32 XHdmiphy1_OutDivReconfig(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir)
This function will set the current output divider configuration over DRP.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID for which to write the settings for. Dir is an indicator for RX or TX. XST_SUCCESS if the configuration was successful.XST_FAILURE otherwise. None.
References XHDMIPHY1_ISCH, XHdmiphy1_LogWrite, XHDMIPHY1_LOG_EVT_GT_TX_RECONFIG, XHDMIPHY1_LOG_EVT_GT_RX_RECONFIG, XHdmiphy1_Ch2Ids, XHdmiphy1_OutDivChReconfig.
Referenced by XHdmiphy1_HdmiTxTimerTimeoutHandler, XHdmiphy1_HdmiRxTimerTimeoutHandler.
u32 XHdmiphy1_ClkReconfig(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId)
This function will set the current clocking settings for each channel to hardware based on the configuration stored in the driver's instance.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID for which to write the settings for. XST_SUCCESS if the configuration was successful.XST_FAILURE otherwise. None.
References XHdmiphy1_Ch2Ids, XHDMIPHY1_ISCH, XHdmiphy1_ClkChReconfig, XHDMIPHY1_ISCMN, XHdmiphy1_IsHDMI, XHdmiphy1::HdmiIsQpllPresent, XHdmiphy1_LogWrite, XHDMIPHY1_LOG_EVT_NO_QPLL_ERR, XHdmiphy1_ErrorHandler, XHdmiphy1_ClkCmnReconfig, XHDMIPHY1_LOG_EVT_CPLL_RECONFIG, XHDMIPHY1_LOG_EVT_QPLL_RECONFIG.
Referenced by XHdmiphy1_HdmiTxTimerTimeoutHandler, XHdmiphy1_HdmiRxTimerTimeoutHandler.
XHdmiphy1_SysClkDataSelType XHdmiphy1_Pll2SysClkData(XHdmiphy1_PllType PllSelect)
This function will translate from XHdmiphy1_PllType to XHdmiphy1_SysClkDataSelType.
PllSelect is the PLL type to translate. The reference clock type based on the PLL selection. None.
Referenced by XHdmiphy1_PllInitialize.
XHdmiphy1_SysClkOutSelType XHdmiphy1_Pll2SysClkOut(XHdmiphy1_PllType PllSelect)
This function will translate from XHdmiphy1_PllType to XHdmiphy1_SysClkOutSelType.
PllSelect is the PLL type to translate. The reference clock type based on the PLL selection. None.
Referenced by XHdmiphy1_PllInitialize.
u32 XHdmiphy1_PllCalculator(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir, u32 PllClkInFreqHz)
This function will try to find the necessary PLL divisor values to produce the configured line rate given the specified PLL input frequency.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to calculate the PLL values for. ChId is the channel ID to calculate the PLL values for. Dir is an indicator for TX or RX. PllClkInFreqHz is the PLL input frequency on which to base the calculations on. A value of 0 indicates to use the currently configured quad PLL reference clock. A non-zero value indicates to ignore what is currently configured in SW, and use a custom frequency instead. XST_SUCCESS if valid PLL values were found to satisfy the constraints.XST_FAILURE otherwise. If successful, the channel's PllParams structure will be modified with the valid PLL parameters.
References XHdmiphy1::Quads, XHDMIPHY1_CH2IDX, XHdmiphy1_GetQuadRefClkFreq, XHDMIPHY1_ISCH, XHdmiphy1_CheckPllOpRange, XHdmiphy1_Channel::LineRateHz, XHDMIPHY1_ISCMN, XHdmiphy1_Ch2Ids, XHdmiphy1_CfgSetCdr.
Referenced by XHdmiphy1_ClkCalcParams.
u64 XHdmiphy1_GetPllVcoFreqHz(XHdmiphy1 *InstancePtr, u8 QuadId, XHdmiphy1_ChannelId ChId, XHdmiphy1_DirectionType Dir)
This function calculates the PLL VCO operating frequency.
InstancePtr is a pointer to the XHdmiphy1 core instance. QuadId is the GT quad ID to operate on. ChId is the channel ID to operate on. Dir is an indicator for TX or RX. PLL VCO frequency in Hz None.
References XHdmiphy1::Quads, XHDMIPHY1_CH2IDX, XHdmiphy1_IsHDMI, XHdmiphy1::HdmiTxRefClkHz, XHdmiphy1_GetQuadRefClkFreq, XHdmiphy1::HdmiRxDruIsEnabled, XHdmiphy1_DruGetRefClkFreqHz, XHdmiphy1::HdmiRxRefClkHz.
u8 XHdmiphy1_GetRefClkSourcesCount(XHdmiphy1 *InstancePtr)
This function returns the number of active reference clock sources based in the CFG.
InstancePtr is a pointer to the XHdmiphy1 core instance. No of active REFCLK sources None.
References XHdmiphy1::Config, XHdmiphy1_Config::TxProtocol, XHdmiphy1_Config::TxRefClkSel, XHdmiphy1_Config::RxProtocol, XHdmiphy1_Config::RxRefClkSel, XHdmiphy1_Config::DruIsPresent, XHdmiphy1_Config::DruRefClkSel, XHdmiphy1_Config::TxFrlRefClkSel, XHdmiphy1_Config::RxFrlRefClkSel.
u8 XHdmiphy1_IsHDMI(XHdmiphy1 *InstancePtr, XHdmiphy1_DirectionType Dir)
This function checks if Instance is HDMI 2.0 or HDMI 2.1.
InstancePtr is a pointer to the HDMIPHY instance. Dir is an indicator for RX or TX. TRUE if HDMI 2.0 or 2.1 else FALSE. None.
References XHdmiphy1::Config, XHdmiphy1_Config::TxProtocol, XHdmiphy1_Config::RxProtocol.
Referenced by XHdmiphy1_Hdmi_CfgInitialize, XHdmiphy1_HdmiDebugInfo, XHdmiphy1_Ch2Ids, XHdmiphy1_IsPllLocked, XHdmiphy1_ClkReconfig, XHdmiphy1_GetPllVcoFreqHz.
void XHdmiphy1_ErrorHandler(XHdmiphy1 *InstancePtr)
This function is the error condition handler.
InstancePtr is a pointer to the HDMIPHY instance. None. None.
References XHdmiphy1::ErrorCallback, XHdmiphy1::ErrorRef.
Referenced by XHdmiphy1_HdmiCfgCalcMmcmParam, XHdmiphy1_HdmiQpllParam, XHdmiphy1_HdmiCpllParam, XHdmiphy1_SetHdmiTxParam, XHdmiphy1_Hdmi21Config, XHdmiphy1_ClkReconfig.