xhdmiphy1_intr.c
void XHdmiphy1_IntrEnable(XHdmiphy1 *InstancePtr, XHdmiphy1_IntrHandlerType Intr)
This function enables interrupts associated with the specified interrupt type.
InstancePtr is a pointer to the XHdmiphy1 instance. Intr is the interrupt type/mask to enable. None. None.
References XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_INTR_EN_REG, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize, XHdmiphy1_Hdmi20Config.
void XHdmiphy1_IntrDisable(XHdmiphy1 *InstancePtr, XHdmiphy1_IntrHandlerType Intr)
This function disables interrupts associated with the specified interrupt type.
InstancePtr is a pointer to the XHdmiphy1 instance. Intr is the interrupt type/mask to disable. None. None.
References XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_INTR_DIS_REG, XHdmiphy1_WriteReg.
Referenced by XHdmiphy1_Hdmi_CfgInitialize, XHdmiphy1_Hdmi21Config.
void XHdmiphy1_SetIntrHandler(XHdmiphy1 *InstancePtr, XHdmiphy1_IntrHandlerType HandlerType, XHdmiphy1_IntrHandler CallbackFunc, void *CallbackRef)
This function installs a callback function for the specified handler type.
InstancePtr is a pointer to the XHdmiphy1 instance. HandlerType is the interrupt handler type which specifies which interrupt event to attach the callback for. CallbackFunc is the address to the callback function. CallbackRef is the user data item that will be passed to the callback function when it is invoked. None. None.
References XHdmiphy1::IntrTxResetDoneHandler, XHdmiphy1::IntrTxResetDoneCallbackRef, XHdmiphy1::IntrRxResetDoneHandler, XHdmiphy1::IntrRxResetDoneCallbackRef, XHdmiphy1::IntrCpllLockHandler, XHdmiphy1::IntrCpllLockCallbackRef, XHdmiphy1::IntrQpllLockHandler, XHdmiphy1::IntrQpllLockCallbackRef, XHdmiphy1::IntrTxAlignDoneHandler, XHdmiphy1::IntrTxAlignDoneCallbackRef, XHdmiphy1::IntrQpll1LockHandler, XHdmiphy1::IntrQpll1LockCallbackRef, XHdmiphy1::IntrTxClkDetFreqChangeHandler, XHdmiphy1::IntrTxClkDetFreqChangeCallbackRef, XHdmiphy1::IntrRxClkDetFreqChangeHandler, XHdmiphy1::IntrRxClkDetFreqChangeCallbackRef, XHdmiphy1::IntrTxMmcmLockHandler, XHdmiphy1::IntrTxMmcmLockCallbackRef, XHdmiphy1::IntrRxMmcmLockHandler, XHdmiphy1::IntrRxMmcmLockCallbackRef, XHdmiphy1::IntrTxTmrTimeoutHandler, XHdmiphy1::IntrTxTmrTimeoutCallbackRef, XHdmiphy1::IntrRxTmrTimeoutHandler, XHdmiphy1::IntrRxTmrTimeoutCallbackRef.
Referenced by XHdmiphy1_HdmiIntrHandlerCallbackInit.
void XHdmiphy1_InterruptHandler(XHdmiphy1 *InstancePtr)
This function is the interrupt handler for the XHdmiphy1 driver.
It will detect what kind of interrupt has happened, and will invoke the appropriate callback function. InstancePtr is a pointer to the XHdmiphy1 instance. None. None.
References XHdmiphy1::IsReady, XHdmiphy1_ReadReg, XHdmiphy1::Config, XHdmiphy1_Config::BaseAddr, XHDMIPHY1_INTR_STS_REG, XHDMIPHY1_INTR_CPLL_LOCK_MASK, XHdmiphy1::IntrCpllLockHandler, XHdmiphy1::IntrCpllLockCallbackRef, XHDMIPHY1_INTR_QPLL_LOCK_MASK, XHdmiphy1::IntrQpllLockHandler, XHdmiphy1::IntrQpllLockCallbackRef, XHDMIPHY1_INTR_QPLL1_LOCK_MASK, XHdmiphy1::IntrQpll1LockHandler, XHdmiphy1::IntrQpll1LockCallbackRef, XHDMIPHY1_INTR_TXRESETDONE_MASK, XHdmiphy1::IntrTxResetDoneHandler, XHdmiphy1::IntrTxResetDoneCallbackRef, XHDMIPHY1_INTR_TXALIGNDONE_MASK, XHdmiphy1::IntrTxAlignDoneHandler, XHdmiphy1::IntrTxAlignDoneCallbackRef, XHDMIPHY1_INTR_TXGPO_RE_MASK, XHDMIPHY1_INTR_RXGPO_RE_MASK, XHDMIPHY1_INTR_LCPLL_LOCK_MASK, XHDMIPHY1_INTR_RPLL_LOCK_MASK, XHDMIPHY1_INTR_RXRESETDONE_MASK, XHdmiphy1::IntrRxResetDoneHandler, XHdmiphy1::IntrRxResetDoneCallbackRef, XHDMIPHY1_INTR_TXCLKDETFREQCHANGE_MASK, XHdmiphy1::IntrTxClkDetFreqChangeHandler, XHdmiphy1::IntrTxClkDetFreqChangeCallbackRef, XHDMIPHY1_INTR_RXCLKDETFREQCHANGE_MASK, XHdmiphy1::IntrRxClkDetFreqChangeHandler, XHdmiphy1::IntrRxClkDetFreqChangeCallbackRef, XHDMIPHY1_INTR_TXMMCMUSRCLK_LOCK_MASK, XHdmiphy1::IntrTxMmcmLockHandler, XHdmiphy1::IntrTxMmcmLockCallbackRef, XHDMIPHY1_INTR_RXMMCMUSRCLK_LOCK_MASK, XHdmiphy1::IntrRxMmcmLockHandler, XHdmiphy1::IntrRxMmcmLockCallbackRef, XHDMIPHY1_INTR_TXTMRTIMEOUT_MASK, XHdmiphy1::IntrTxTmrTimeoutHandler, XHdmiphy1::IntrTxTmrTimeoutCallbackRef, XHDMIPHY1_INTR_RXTMRTIMEOUT_MASK, XHdmiphy1::IntrRxTmrTimeoutHandler, XHdmiphy1::IntrRxTmrTimeoutCallbackRef.