
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT

*
* Description: Driver configuration
*
*******************************************************************/

#ifndef SDT
#include "xparameters.h"
#endif
#include "xv_warp_filter.h"

/*
* The configuration table for devices
*/

XV_warp_filter_Config XV_warp_filter_ConfigTable[] =
{
	{
		XPAR_V_WARP_FILTER_0_DEVICE_ID,
		XPAR_V_WARP_FILTER_0_S_AXI_CTRL_BASEADDR,
		XPAR_V_WARP_FILTER_0_MAX_COLS,
		XPAR_V_WARP_FILTER_0_MAX_ROWS,
		XPAR_V_WARP_FILTER_0_AXI_MM_READ_DATA_WIDTH,
		XPAR_V_WARP_FILTER_0_BITS_PER_COMPONENTS
	}
};
