xv_vcresampler.h
XV_vcresampler_WriteReg
XV_vcresampler_ReadReg
int XV_vcresampler_Initialize(XV_vcresampler *InstancePtr, UINTPTR BaseAddress)
This function looks up the configuration for the given base address, validates the instance pointer, and initializes the hardware instance with the configuration found.
If the configuration is not found, the function sets the instance as not ready and returns an error code. InstancePtr Pointer to the XV_vcresampler instance to be initialized. BaseAddress Base address of the device to initialize. XST_SUCCESS if initialization is successful.XST_DEVICE_NOT_FOUND if the configuration for the given base address is not found.
References XV_vcresampler_Config::BaseAddress, XV_vcresampler::IsReady, XV_vcresampler_CfgInitialize, XV_vcresampler_LookupConfig.
Referenced by XV_VcrsmplInitialize.
XV_vcresampler_Config* XV_vcresampler_LookupConfig(UINTPTR BaseAddress)
Looks up the configuration structure for the VCR resampler based on the provided base address.
This function searches the XV_vcresampler_ConfigTable for an entry whose BaseAddress matches the specified BaseAddress. If BaseAddress is zero, the first entry is returned. If a matching configuration is found, a pointer to the configuration structure is returned; otherwise, NULL is returned. BaseAddress The base address of the VCR resampler instance to look up. Pointer to the matching XV_vcresampler_Config structure if found, otherwise NULL.
Referenced by XV_vcresampler_Initialize.
int XV_vcresampler_CfgInitialize(XV_vcresampler *InstancePtr, XV_vcresampler_Config *ConfigPtr, UINTPTR EffectiveAddr)
Initializes a specific XV_vcresampler instance with the provided configuration and base address.
InstancePtr Pointer to the XV_vcresampler instance to be initialized. ConfigPtr Pointer to the configuration structure for the XV_vcresampler. EffectiveAddr Base address for the hardware instance. XST_SUCCESS if initialization is successful.
References XV_vcresampler_Config::BaseAddress, XV_vcresampler::Config, XV_vcresampler::IsReady.
Referenced by XV_vcresampler_Initialize.
void XV_vcresampler_Start(XV_vcresampler *InstancePtr)
Starts the VC resampler hardware.
This function asserts the validity of the instance pointer and its readiness, then writes to the control register to start the hardware operation. InstancePtr is a pointer to the XV_vcresampler instance. None.
References XV_vcresampler_Config::BaseAddress, XV_vcresampler::Config, XV_vcresampler::IsReady, XV_VCRESAMPLER_CTRL_ADDR_AP_CTRL.
Referenced by XV_VCrsmplStart.
u32 XV_vcresampler_IsDone(XV_vcresampler *InstancePtr)
Checks if the VC Resampler core has completed its operation.
InstancePtr Pointer to the XV_vcresampler instance. 1 if the operation is done.0 if the operation is not done.
References XV_vcresampler_Config::BaseAddress, XV_vcresampler::Config, XV_vcresampler::IsReady, XV_VCRESAMPLER_CTRL_ADDR_AP_CTRL.
Referenced by XV_VCrsmplDbgReportStatus.
u32 XV_vcresampler_IsIdle(XV_vcresampler *InstancePtr)
Checks if the XV_vcresampler core is idle.
InstancePtr is a pointer to the XV_vcresampler instance. Returns 1 if the core is idle, 0 otherwise.
References XV_vcresampler_Config::BaseAddress, XV_vcresampler::Config, XV_vcresampler::IsReady, XV_VCRESAMPLER_CTRL_ADDR_AP_CTRL.
Referenced by XV_VCrsmplDbgReportStatus.
u32 XV_vcresampler_IsReady(XV_vcresampler *InstancePtr)
Checks if the XV_vcresampler instance is ready for the next input.
InstancePtr is a pointer to the XV_vcresampler instance. 1 if the core is ready for the next input, 0 otherwise.
References XV_vcresampler_Config::BaseAddress, XV_vcresampler::Config, XV_vcresampler::IsReady, XV_VCRESAMPLER_CTRL_ADDR_AP_CTRL.
Referenced by XV_VCrsmplDbgReportStatus.
void XV_vcresampler_EnableAutoRestart(XV_vcresampler *InstancePtr)
This function enables auto-restart for the XV_vcresampler instance.
InstancePtr Pointer to the XV_vcresampler instance. None.
References XV_vcresampler_Config::BaseAddress, XV_vcresampler::Config, XV_vcresampler::IsReady, XV_VCRESAMPLER_CTRL_ADDR_AP_CTRL.
Referenced by XV_VCrsmplStart.
void XV_vcresampler_DisableAutoRestart(XV_vcresampler *InstancePtr)
This function disables auto-restart for the XV_vcresampler instance.
InstancePtr Pointer to the XV_vcresampler instance. None.
References XV_vcresampler_Config::BaseAddress, XV_vcresampler::Config, XV_vcresampler::IsReady, XV_VCRESAMPLER_CTRL_ADDR_AP_CTRL.
Referenced by XV_VCrsmplStop.
void XV_vcresampler_Set_HwReg_width(XV_vcresampler *InstancePtr, u32 Data)
This function sets the hardware register width.
InstancePtr Pointer to the XV_vcresampler instance. Data Width data to set. None.
References XV_vcresampler_Config::BaseAddress, XV_vcresampler::Config, XV_vcresampler::IsReady.
Referenced by XV_VCrsmplSetActiveSize.
u32 XV_vcresampler_Get_HwReg_width(XV_vcresampler *InstancePtr)
This function gets the hardware register width.
InstancePtr Pointer to the XV_vcresampler instance. Width data.
References XV_vcresampler_Config::BaseAddress, XV_vcresampler::Config, XV_vcresampler::IsReady.
Referenced by XV_VCrsmplDbgReportStatus.
void XV_vcresampler_Set_HwReg_height(XV_vcresampler *InstancePtr, u32 Data)
This function sets the hardware register height.
InstancePtr Pointer to the XV_vcresampler instance. Data Height data to set. None.
References XV_vcresampler_Config::BaseAddress, XV_vcresampler::Config, XV_vcresampler::IsReady.
Referenced by XV_VCrsmplSetActiveSize.
u32 XV_vcresampler_Get_HwReg_height(XV_vcresampler *InstancePtr)
This function gets the hardware register height.
InstancePtr Pointer to the XV_vcresampler instance. Height data.
References XV_vcresampler_Config::BaseAddress, XV_vcresampler::Config, XV_vcresampler::IsReady.
Referenced by XV_VCrsmplDbgReportStatus.
void XV_vcresampler_Set_HwReg_input_video_format(XV_vcresampler *InstancePtr, u32 Data)
This function sets the input video format.
InstancePtr Pointer to the XV_vcresampler instance. Data Input video format data to set. None.
References XV_vcresampler_Config::BaseAddress, XV_vcresampler::Config, XV_vcresampler::IsReady.
Referenced by XV_VCrsmplSetFormat.
u32 XV_vcresampler_Get_HwReg_input_video_format(XV_vcresampler *InstancePtr)
This function gets the input video format.
InstancePtr Pointer to the XV_vcresampler instance. Input video format data.
References XV_vcresampler_Config::BaseAddress, XV_vcresampler::Config, XV_vcresampler::IsReady.
Referenced by XV_VCrsmplDbgReportStatus.
void XV_vcresampler_Set_HwReg_output_video_format(XV_vcresampler *InstancePtr, u32 Data)
This function sets the output video format.
InstancePtr Pointer to the XV_vcresampler instance. Data Output video format data to set. None.
References XV_vcresampler_Config::BaseAddress, XV_vcresampler::Config, XV_vcresampler::IsReady.
Referenced by XV_VCrsmplSetFormat.
u32 XV_vcresampler_Get_HwReg_output_video_format(XV_vcresampler *InstancePtr)
This function gets the output video format.
InstancePtr Pointer to the XV_vcresampler instance. Output video format data.
References XV_vcresampler_Config::BaseAddress, XV_vcresampler::Config, XV_vcresampler::IsReady.
Referenced by XV_VCrsmplDbgReportStatus.
void XV_vcresampler_Set_HwReg_coefs_0_0(XV_vcresampler *InstancePtr, u32 Data)
This function sets the coefficients for the resampler.
InstancePtr Pointer to the XV_vcresampler instance. Data Coefficients data to set. None.
References XV_vcresampler_Config::BaseAddress, XV_vcresampler::Config, XV_vcresampler::IsReady.
u32 XV_vcresampler_Get_HwReg_coefs_0_0(XV_vcresampler *InstancePtr)
This function gets the coefficients for the resampler.
InstancePtr Pointer to the XV_vcresampler instance. Coefficients data.
References XV_vcresampler_Config::BaseAddress, XV_vcresampler::Config, XV_vcresampler::IsReady.
void XV_vcresampler_InterruptGlobalEnable(XV_vcresampler *InstancePtr)
This function enables global interrupts.
InstancePtr Pointer to the XV_vcresampler instance. None.
References XV_vcresampler_Config::BaseAddress, XV_vcresampler::Config, XV_vcresampler::IsReady.
void XV_vcresampler_InterruptGlobalDisable(XV_vcresampler *InstancePtr)
This function disables global interrupts.
InstancePtr Pointer to the XV_vcresampler instance. None.
References XV_vcresampler_Config::BaseAddress, XV_vcresampler::Config, XV_vcresampler::IsReady.
void XV_vcresampler_InterruptEnable(XV_vcresampler *InstancePtr, u32 Mask)
This function enables specific interrupts.
InstancePtr Pointer to the XV_vcresampler instance. Mask Interrupt mask to enable. None.
References XV_vcresampler_Config::BaseAddress, XV_vcresampler::Config, XV_vcresampler::IsReady.
void XV_vcresampler_InterruptDisable(XV_vcresampler *InstancePtr, u32 Mask)
Disable specific interrupts for the VC Resampler core.
This function disables the interrupts specified by the Mask parameter for the given VC Resampler instance. It reads the current interrupt enable register, clears the bits specified by Mask, and writes the updated value back to the register. InstancePtr Pointer to the XV_vcresampler instance. Mask Bitmask of interrupts to disable. None. The InstancePtr must be initialized and ready before calling this function.
References XV_vcresampler_Config::BaseAddress, XV_vcresampler::Config, XV_vcresampler::IsReady.
void XV_vcresampler_InterruptClear(XV_vcresampler *InstancePtr, u32 Mask)
Clears specific interrupt(s) for the VC resampler hardware.
This function writes the specified interrupt mask to the Interrupt Status Register (ISR) to clear the corresponding interrupt(s) for the VC resampler instance. InstancePtr Pointer to the XV_vcresampler instance. Mask Bitmask indicating which interrupt(s) to clear. The InstancePtr must be initialized and ready before calling this function.
References XV_vcresampler_Config::BaseAddress, XV_vcresampler::Config, XV_vcresampler::IsReady.
u32 XV_vcresampler_InterruptGetEnabled(XV_vcresampler *InstancePtr)
Retrieves the interrupt enable register value for the VC resampler instance.
This function checks that the provided instance pointer is valid and that the instance is ready. It then reads and returns the value of the interrupt enable register (IER) from the hardware. InstancePtr Pointer to the XV_vcresampler instance. The current value of the interrupt enable register.
References XV_vcresampler_Config::BaseAddress, XV_vcresampler::Config, XV_vcresampler::IsReady.
u32 XV_vcresampler_InterruptGetStatus(XV_vcresampler *InstancePtr)
XV_vcresampler_InterruptGetStatus - Retrieves the interrupt status of the VC resampler instance.
InstancePtr : Pointer to the XV_vcresampler instance. Must not be NULL and must be initialized. The current value of the Interrupt Status Register (ISR) for the VC resampler. This function asserts the validity of the instance pointer and its readiness, then reads and returns the interrupt status register value.
References XV_vcresampler_Config::BaseAddress, XV_vcresampler::Config, XV_vcresampler::IsReady.