xuartlite_i.h
XUARTLITE_I_H
XUartLite_UpdateStats
XUartLite_Config XUartLite_ConfigTable[][]
The configuration table for UART Lite devices.
unsigned int XUartLite_SendBuffer(XUartLite *InstancePtr)
This function sends a buffer that has been previously specified by setting up the instance variables of the instance.
This function is designed to be an internal function for the XUartLite component such that it may be called from a shell function that sets up the buffer or from an interrupt handler.This function sends the specified buffer of data to the UART in either polled or interrupt driven modes. This function is non-blocking such that it will return before the data has been sent by the UART.In a polled mode, this function will only send as much data as the UART can buffer, either in the transmitter or in the FIFO if present and enabled. The application may need to call it repeatedly to send a buffer.In interrupt mode, this function will start sending the specified buffer and then the interrupt handler of the driver will continue until the buffer has been sent. A callback function, as specified by the application, will be called to indicate the completion of sending the buffer. InstancePtr is a pointer to the XUartLite instance. NumBytes is the number of bytes actually sent (put into the UART transmitter and/or FIFO). None.
References XUartLite_Stats::CharactersTransmitted, XUartLite::SendBuffer, XUartLite_GetSR, XUartLite_WriteReg.
Referenced by XUartLite_Send.
unsigned int XUartLite_ReceiveBuffer(XUartLite *InstancePtr)
This function receives a buffer that has been previously specified by setting up the instance variables of the instance.
This function is designed to be an internal function for the XUartLite component such that it may be called from a shell function that sets up the buffer or from an interrupt handler.This function will attempt to receive a specified number of bytes of data from the UART and store it into the specified buffer. This function is designed for either polled or interrupt driven modes. It is non-blocking such that it will return if there is no data has already received by the UART.In a polled mode, this function will only receive as much data as the UART can buffer, either in the receiver or in the FIFO if present and enabled. The application may need to call it repeatedly to receive a buffer. Polled mode is the default mode of operation for the driver.In interrupt mode, this function will start receiving and then the interrupt handler of the driver will continue until the buffer has been received. A callback function, as specified by the application, will be called to indicate the completion of receiving the buffer or when any receive errors or timeouts occur. InstancePtr is a pointer to the XUartLite instance. The number of bytes received. None.
References XUartLite_Stats::CharactersReceived, XUartLite::ReceiveBuffer, XUartLite_GetSR, XUartLite_ReadReg, XUartLite_WriteReg.
Referenced by XUartLite_Recv.
u8 XUartLite_GetSR(XUartLite *InstancePtr)
This function reads the status register and updates the error stats, before returning the status register value.
The status register is a clear on read register, so the errors if occurred have to be recorded every time status register is read. This function is designed to be an internal function for the XUartLite component such that it may be called from wherever the status register needs to be read from the other driver functions. InstancePtr is a pointer to the XUartLite instance. The value of status register. None.
References XUartLite_GetStatusReg.
Referenced by XUartLite_InterruptHandler, XUartLite_IsSending, XUartLite_ReceiveBuffer, XUartLite_Recv, XUartLite_ResetFifos, XUartLite_SelfTest, XUartLite_Send, XUartLite_SendBuffer.