xuartlite_sinit.c
XUartLite_Config * XUartLite_LookupConfig(UINTPTR BaseAddress)
int XUartLite_Initialize(XUartLite *InstancePtr, UINTPTR BaseAddress)
Initialize a XUartLite instance.
The receive and transmit FIFOs of the UART are not flushed, so the user may want to flush them. The hardware device does not have any way to disable the receiver such that any valid data may be present in the receive FIFO. This function disables the UART interrupt. The baudrate and format of the data are fixed in the hardware at hardware build time. InstancePtr is a pointer to the XUartLite instance. BaseAddress contains the base address of the device XST_SUCCESS if everything starts up as expected.XST_DEVICE_NOT_FOUND if the device is not found in the configuration table. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XUartLite_Config::RegBaseAddr, XUartLite_CfgInitialize.
Referenced by UartLiteIntrExample, UartLitePolledExample, UartLiteSelfTestExample.