xuartlite_intr.c
typedef void(* Handler)(XUartLite *InstancePtr))(XUartLite *InstancePtr)
static void ReceiveDataHandler(XUartLite *InstancePtr)
This function handles the interrupt when data is received, either a single byte when FIFOs are not enabled, or multiple bytes with the FIFO.
InstancePtr is a pointer to the XUartLite instance. None. None.
static void SendDataHandler(XUartLite *InstancePtr)
This function handles the interrupt when data has been sent, the transmit FIFO is empty (transmitter holding register).
InstancePtr is a pointer to the XUartLite instance . None. None.
void XUartLite_SetRecvHandler(XUartLite *InstancePtr, XUartLite_Handler FuncPtr, void *CallBackRef)
This function sets the handler that will be called when an event (interrupt) occurs in the driver.
The purpose of the handler is to allow application specific processing to be performed. InstancePtr is a pointer to the XUartLite instance. FuncPtr is the pointer to the callback function. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. None. There is no assert on the CallBackRef since the driver doesn't know what it is (nor should it)
References XUartLite::RecvCallBackRef, XUartLite::RecvHandler.
Referenced by UartLiteIntrExample.
void XUartLite_SetSendHandler(XUartLite *InstancePtr, XUartLite_Handler FuncPtr, void *CallBackRef)
This function sets the handler that will be called when an event (interrupt) occurs in the driver.
The purpose of the handler is to allow application specific processing to be performed. InstancePtr is a pointer to the XUartLite instance . FuncPtr is the pointer to the callback function. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. None. There is no assert on the CallBackRef since the driver doesn't know what it is (nor should it)
References XUartLite::SendCallBackRef, XUartLite::SendHandler.
Referenced by UartLiteIntrExample.
void XUartLite_InterruptHandler(XUartLite *InstancePtr)
This function is the interrupt handler for the UART lite driver.
It must be connected to an interrupt system by the user such that it is called when an interrupt for any UART lite occurs. This function does not save or restore the processor context such that the user must ensure this occurs. InstancePtr contains a pointer to the instance of the UART that the interrupt is for. None. None.
References XUartLite::SendBuffer, XUartLite_GetSR.
Referenced by UartLiteIntrExample.
void XUartLite_DisableInterrupt(XUartLite *InstancePtr)
This function disables the UART interrupt.
After calling this function, data may still be received by the UART but no interrupt will be generated since the hardware device has no way to disable the receiver. InstancePtr is a pointer to the XUartLite instance. None. None.
References XUartLite_WriteReg.
void XUartLite_EnableInterrupt(XUartLite *InstancePtr)
This function enables the UART interrupt such that an interrupt will occur when data is received or data has been transmitted.
The device contains 16 byte receive and transmit FIFOs such that an interrupt is generated anytime there is data in the receive FIFO and when the transmit FIFO transitions from not empty to empty. InstancePtr is a pointer to the XUartLite instance. None. None.
References XUartLite_WriteReg.
Referenced by UartLiteIntrExample.