xuartlite_intr_example.c
XUARTLITE_BASEADDRESS
TEST_BUFFER_SIZE
XUartLite UartLite
u8 SendBuffer[TEST_BUFFER_SIZE][TEST_BUFFER_SIZE]
u8 ReceiveBuffer[TEST_BUFFER_SIZE][TEST_BUFFER_SIZE]
volatile int TotalReceivedCount
volatile int TotalSentCount
int UartLiteIntrExample(XUartLite *UartLiteInstPtr, UINTPTR BaseAddress)
This function does a minimal test on the UartLite device and driver as a design example.
The purpose of this function is to illustrate how to use the XUartLite component.This function sends data and expects to receive the same data through the UartLite. The user must provide a physical loopback such that data which is transmitted will be received.This function uses interrupt driver mode of the UartLite device. The calls to the UartLite driver in the handlers should only use the non-blocking calls. UartLiteInstPtr is a pointer to the instance of UartLite driver. BaseAddress contains the base address of the device XST_SUCCESS if successful, otherwise XST_FAILURE. - This function contains an infinite loop such that if interrupts are not working it may never return. In XSCT/classic flow, DeviceId is used to look up the device configuration. The purpose of this function is to illustrate how to use the XUartLite component.This function sends data through the UartLite.This function uses the interrupt driver mode of the UartLite. The calls to the UartLite driver in the interrupt handlers, should only use the non-blocking calls. UartLiteInstPtr is a pointer to the instance of UartLite driver. BaseAddress contains the base address of the device XST_SUCCESS if successful, otherwise XST_FAILURE. - In XSCT/classic flow, DeviceId is used to look up the device configuration. This function contains an infinite loop such that if interrupts are not working it may never return.
References XUartLite_Config::IntrId, XUartLite_Config::IntrParent, RecvHandler, SendHandler, XUartLite_EnableInterrupt, XUartLite_Initialize, XUartLite_InterruptHandler, XUartLite_Recv, XUartLite_SelfTest, XUartLite_Send, XUartLite_SetRecvHandler, XUartLite_SetSendHandler.
Referenced by main.
void SendHandler(void *CallBackRef, unsigned int EventData)
This function is the handler which performs processing to send data to the UartLite.
It is called from an interrupt context such that the amount of processing performed should be minimized. It is called when the transmit FIFO of the UartLite is empty and more data can be sent through the UartLite.This handler provides an example of how to handle data for the UartLite, but is application specific. CallBackRef contains a callback reference from the driver. In this case it is the instance pointer for the UartLite driver. EventData contains the number of bytes sent or received for sent and receive events. None. None.
Referenced by UartLiteIntrExample.
void RecvHandler(void *CallBackRef, unsigned int EventData)
This function is the handler which performs processing to receive data from the UartLite.
It is called from an interrupt context such that the amount of processing performed should be minimized. It is called data is present in the receive FIFO of the UartLite such that the data can be retrieved from the UartLite. The size of the data present in the FIFO is not known when this function is called.This handler provides an example of how to handle data for the UartLite, but is application specific. CallBackRef contains a callback reference from the driver, in this case it is the instance pointer for the UartLite driver. EventData contains the number of bytes sent or received for sent and receive events. None. None.
Referenced by UartLiteIntrExample.
int main(void)
Main function to call the UartLite interrupt example.
XST_SUCCESS if successful, XST_FAILURE if unsuccessful None
References UartLiteIntrExample.