xuartlite.c
static void StubHandler(void *CallBackRef, unsigned int ByteCount)
int XUartLite_CfgInitialize(XUartLite *InstancePtr, XUartLite_Config *Config, UINTPTR EffectiveAddr)
Initialize a XUartLite instance.
The receive and transmit FIFOs of the UART are not flushed, so the user may want to flush them. The hardware device does not have any way to disable the receiver such that any valid data may be present in the receive FIFO. This function disables the UART interrupt. The baudrate and format of the data are fixed in the hardware at hardware build time. InstancePtr is a pointer to the XUartLite instance. Config is a reference to a structure containing information about a specific UART Lite device. This function initializes an InstancePtr object for a specific device specified by the contents of Config. This function can initialize multiple instance objects with the use of multiple calls giving different Config information on each call. EffectiveAddr is the device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, use Config->BaseAddress for this parameters, passing the physical address instead. XST_SUCCESS if everything starts up as expected. The Config pointer argument is not used by this function, but is provided to keep the function signature consistent with other drivers.
References XUartLite::ReceiveBuffer, XUartLite::RecvHandler, XUartLite::SendBuffer, XUartLite::SendHandler, XUartLite_ClearStats, XUartLite_WriteReg.
Referenced by XUartLite_Initialize.
unsigned int XUartLite_Send(XUartLite *InstancePtr, u8 *DataBufferPtr, unsigned int NumBytes)
This functions sends the specified buffer of data using the UART in either polled or interrupt driven modes.
This function is non-blocking such that it will return before the data has been sent by the UART. If the UART is busy sending data, it will return and indicate zero bytes were sent.In a polled mode, this function will only send as much data as the UART can buffer in the FIFO. The application may need to call it repeatedly to send a buffer.In interrupt mode, this function will start sending the specified buffer and then the interrupt handler of the driver will continue sending data until the buffer has been sent. A callback function, as specified by the application, will be called to indicate the completion of sending the buffer. InstancePtr is a pointer to the XUartLite instance. DataBufferPtr is pointer to a buffer of data to be sent. NumBytes contains the number of bytes to be sent. A value of zero will stop a previous send operation that is in progress in interrupt mode. Any data that was already put into the transmit FIFO will be sent. The number of bytes actually sent. The number of bytes is not asserted so that this function may be called with a value of zero to stop an operation that is already in progress.
References XUartLite::SendBuffer, XUartLite_GetSR, XUartLite_SendBuffer, XUartLite_WriteReg.
Referenced by UartLiteIntrExample, UartLitePolledExample.
unsigned int XUartLite_Recv(XUartLite *InstancePtr, u8 *DataBufferPtr, unsigned int NumBytes)
This function will attempt to receive a specified number of bytes of data from the UART and store it into the specified buffer.
This function is designed for either polled or interrupt driven modes. It is non-blocking such that it will return if no data has already received by the UART.In a polled mode, this function will only receive as much data as the UART can buffer in the FIFO. The application may need to call it repeatedly to receive a buffer. Polled mode is the default mode of operation for the driver.In interrupt mode, this function will start receiving and then the interrupt handler of the driver will continue receiving data until the buffer has been received. A callback function, as specified by the application, will be called to indicate the completion of receiving the buffer or when any receive errors or timeouts occur. InstancePtr is a pointer to the XUartLite instance. DataBufferPtr is pointer to buffer for data to be received into. NumBytes is the number of bytes to be received. A value of zero will stop a previous receive operation that is in progress in interrupt mode. The number of bytes received. The number of bytes is not asserted so that this function may be called with a value of zero to stop an operation that is already in progress.
References XUartLite::ReceiveBuffer, XUartLite_GetSR, XUartLite_ReceiveBuffer, XUartLite_WriteReg.
Referenced by UartLiteIntrExample, UartLitePolledExample.
void XUartLite_ResetFifos(XUartLite *InstancePtr)
This function resets the FIFOs, both transmit and receive, of the UART such that they are emptied.
Since the UART does not have any way to disable it from receiving data, it may be necessary for the application to reset the FIFOs to get rid of any unwanted data. InstancePtr is a pointer to the XUartLite instance . None. None.
References XUartLite_GetSR, XUartLite_WriteReg.
Referenced by XUartLite_SelfTest.
int XUartLite_IsSending(XUartLite *InstancePtr)
This function determines if the specified UART is sending data.
If the transmitter register is not empty, it is sending data. InstancePtr is a pointer to the XUartLite instance. A value of TRUE if the UART is sending data, otherwise FALSE. None.
References XUartLite_GetSR.
unsigned int XUartLite_SendBuffer(XUartLite *InstancePtr)
This function sends a buffer that has been previously specified by setting up the instance variables of the instance.
This function is designed to be an internal function for the XUartLite component such that it may be called from a shell function that sets up the buffer or from an interrupt handler.This function sends the specified buffer of data to the UART in either polled or interrupt driven modes. This function is non-blocking such that it will return before the data has been sent by the UART.In a polled mode, this function will only send as much data as the UART can buffer, either in the transmitter or in the FIFO if present and enabled. The application may need to call it repeatedly to send a buffer.In interrupt mode, this function will start sending the specified buffer and then the interrupt handler of the driver will continue until the buffer has been sent. A callback function, as specified by the application, will be called to indicate the completion of sending the buffer. InstancePtr is a pointer to the XUartLite instance. NumBytes is the number of bytes actually sent (put into the UART transmitter and/or FIFO). None.
References XUartLite_Stats::CharactersTransmitted, XUartLite::SendBuffer, XUartLite_GetSR, XUartLite_WriteReg.
Referenced by XUartLite_Send.
unsigned int XUartLite_ReceiveBuffer(XUartLite *InstancePtr)
This function receives a buffer that has been previously specified by setting up the instance variables of the instance.
This function is designed to be an internal function for the XUartLite component such that it may be called from a shell function that sets up the buffer or from an interrupt handler.This function will attempt to receive a specified number of bytes of data from the UART and store it into the specified buffer. This function is designed for either polled or interrupt driven modes. It is non-blocking such that it will return if there is no data has already received by the UART.In a polled mode, this function will only receive as much data as the UART can buffer, either in the receiver or in the FIFO if present and enabled. The application may need to call it repeatedly to receive a buffer. Polled mode is the default mode of operation for the driver.In interrupt mode, this function will start receiving and then the interrupt handler of the driver will continue until the buffer has been received. A callback function, as specified by the application, will be called to indicate the completion of receiving the buffer or when any receive errors or timeouts occur. InstancePtr is a pointer to the XUartLite instance. The number of bytes received. None.
References XUartLite_Stats::CharactersReceived, XUartLite::ReceiveBuffer, XUartLite_GetSR, XUartLite_ReadReg, XUartLite_WriteReg.
Referenced by XUartLite_Recv.
u8 XUartLite_GetSR(XUartLite *InstancePtr)
This function reads the status register and updates the error stats, before returning the status register value.
The status register is a clear on read register, so the errors if occurred have to be recorded every time status register is read. This function is designed to be an internal function for the XUartLite component such that it may be called from wherever the status register needs to be read from the other driver functions. InstancePtr is a pointer to the XUartLite instance. The value of status register. None.
References XUartLite_GetStatusReg.
Referenced by XUartLite_InterruptHandler, XUartLite_IsSending, XUartLite_ReceiveBuffer, XUartLite_Recv, XUartLite_ResetFifos, XUartLite_SelfTest, XUartLite_Send, XUartLite_SendBuffer.