
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2021.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2021 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT

*
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xdppsu.h"

/*
* The configuration table for devices
*/

XDpPsu_Config XDpPsu_ConfigTable[XPAR_XDPPSU_NUM_INSTANCES] =
{
	{
		XPAR_PSU_DP_DEVICE_ID,
		XPAR_PSU_DP_BASEADDR
	}
};
