
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2020 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT

*
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xemacps.h"

/*
* The configuration table for devices
*/

XEmacPs_Config XEmacPs_ConfigTable[XPAR_XEMACPS_NUM_INSTANCES] =
{
	{
		XPAR_PSU_ETHERNET_3_DEVICE_ID,
		XPAR_PSU_ETHERNET_3_BASEADDR,
		XPAR_PSU_ETHERNET_3_IS_CACHE_COHERENT,
		XPAR_PSU_ETHERNET_3_ENET_SLCR_1000MBPS_DIV0,
		XPAR_PSU_ETHERNET_3_ENET_SLCR_1000MBPS_DIV1,
		XPAR_PSU_ETHERNET_3_ENET_SLCR_100MBPS_DIV0,
		XPAR_PSU_ETHERNET_3_ENET_SLCR_100MBPS_DIV1,
		XPAR_PSU_ETHERNET_3_ENET_SLCR_10MBPS_DIV0,
		XPAR_PSU_ETHERNET_3_ENET_SLCR_10MBPS_DIV1
	}
};
