xsysmonpsu.h
XSM_CH_TEMP
On Chip Temperature.
Referenced by SysMonPsuIntrExample, SysMonPsuPolledPrintfExample.
XSM_CH_SUPPLY1
SUPPLY1 VCC_PSINTLP.
Referenced by SysMonPsuIntrExample, SysMonPsuPolledPrintfExample, SysMonPsuSingleChannelIntrExample.
XSM_CH_SUPPLY2
SUPPLY2 VCC_PSINTFP.
XSM_CH_VPVN
VP/VN Dedicated analog inputs.
Referenced by XSysMonPsu_SetSingleChParams.
XSM_CH_VREFP
VREFP.
XSM_CH_VREFN
VREFN.
Referenced by XSysMonPsu_SetExtenalMux.
XSM_CH_SUPPLY3
SUPPLY3 VCC_PSAUX.
Referenced by SysMonPsuIntrExample, SysMonPsuPolledPrintfExample, XSysMonPsu_GetAdcData, XSysMonPsu_SetSingleChParams.
XSM_CH_SUPPLY_CALIB
Supply Calib Data Reg.
Referenced by XSysMonPsu_GetAdcData, XSysMonPsu_SetSingleChParams.
XSM_CH_ADC_CALIB
ADC Offset Channel Reg.
XSM_CH_GAINERR_CALIB
Gain Error Channel Reg.
Referenced by XSysMonPsu_GetAdcData, XSysMonPsu_SetSingleChParams.
XSM_CH_SUPPLY4
SUPPLY4 VCC_PSDDR_504.
Referenced by XSysMonPsu_GetAdcData, XSysMonPsu_SetSingleChParams.
XSM_CH_SUPPLY5
SUPPLY5 VCC_PSIO3_503.
XSM_CH_SUPPLY6
SUPPLY6 VCC_PSIO0_500.
XSM_CH_AUX_MIN
Channel number for 1st Aux Channel.
Referenced by XSysMonPsu_SetExtenalMux, XSysMonPsu_SetSingleChParams.
XSM_CH_AUX_MAX
Channel number for Last Aux channel.
Referenced by XSysMonPsu_GetAdcData, XSysMonPsu_SetExtenalMux, XSysMonPsu_SetSingleChParams.
XSM_CH_SUPPLY7
SUPPLY7 VCC_PSIO1_501.
Referenced by XSysMonPsu_GetAdcData.
XSM_CH_SUPPLY8
SUPPLY8 VCC_PSIO2_502.
XSM_CH_SUPPLY9
SUPPLY9 PS_MGTRAVCC.
XSM_CH_SUPPLY10
SUPPLY10 PS_MGTRAVTT.
XSM_CH_VCCAMS
VCCAMS.
XSM_CH_TEMP_REMTE
Temperature Remote.
Referenced by XSysMonPsu_GetAdcData, XSysMonPsu_SetSingleChParams.
XSM_CH_VCC_PSLL0
VCC_PSLL0.
Referenced by SysMonPsuAMSExample, XSysMonPsu_GetAdcData, XSysMonPsu_SetSingleChParams.
XSM_CH_VCC_PSLL3
VCC_PSLL3.
Referenced by SysMonPsuAMSExample.
XSM_CH_VCCINT
VCCINT.
Referenced by SysMonPsuAMSExample.
XSM_CH_VCCBRAM
VCCBRAM.
Referenced by SysMonPsuAMSExample.
XSM_CH_VCCAUX
VCCAUX.
Referenced by SysMonPsuAMSExample.
XSM_CH_VCC_PSDDRPLL
VCC_PSDDRPLL.
Referenced by SysMonPsuAMSExample.
XSM_CH_DDRPHY_VREF
DDRPHY_VREF.
Referenced by SysMonPsuAMSExample.
XSM_CH_RESERVE1
PSGT_AT0.
Referenced by SysMonPsuAMSExample, XSysMonPsu_GetAdcData, XSysMonPsu_SetSingleChParams.
XSM_CALIB_SUPPLY_OFFSET_COEFF
Supply Offset Calib Coefficient.
XSM_CALIB_ADC_OFFSET_COEFF
ADC Offset Calib Coefficient.
XSM_CALIB_GAIN_ERROR_COEFF
Gain Error Calib Coefficient.
Referenced by XSysMonPsu_GetCalibCoefficient.
XSM_MAX_TEMP
Maximum Temperature Data.
Referenced by SysMonPsuIntrExample, SysMonPsuPolledPrintfExample.
XSM_MAX_SUPPLY1
Maximum SUPPLY1 Data.
Referenced by SysMonPsuIntrExample, SysMonPsuPolledPrintfExample.
XSM_MAX_SUPPLY2
Maximum SUPPLY2 Data.
XSM_MAX_SUPPLY3
Maximum SUPPLY3 Data.
Referenced by SysMonPsuIntrExample, SysMonPsuPolledPrintfExample.
XSM_MIN_TEMP
Minimum Temperature Data.
Referenced by SysMonPsuIntrExample, SysMonPsuPolledPrintfExample.
XSM_MIN_SUPPLY1
Minimum SUPPLY1 Data.
Referenced by SysMonPsuIntrExample, SysMonPsuPolledPrintfExample.
XSM_MIN_SUPPLY2
Minimum SUPPLY2 Data.
XSM_MIN_SUPPLY3
Minimum SUPPLY3 Data.
Referenced by SysMonPsuIntrExample, SysMonPsuPolledPrintfExample.
XSM_MAX_SUPPLY4
Maximum SUPPLY4 Data.
XSM_MAX_SUPPLY5
Maximum SUPPLY5 Data.
XSM_MAX_SUPPLY6
Maximum SUPPLY6 Data.
Referenced by XSysMonPsu_GetMinMaxMeasurement.
XSM_MIN_SUPPLY4
Minimum SUPPLY4 Data.
Referenced by XSysMonPsu_GetMinMaxMeasurement.
XSM_MIN_SUPPLY5
Minimum SUPPLY5 Data.
XSM_MIN_SUPPLY6
Minimum SUPPLY6 Data.
Referenced by XSysMonPsu_GetMinMaxMeasurement.
XSM_MAX_SUPPLY7
Maximum SUPPLY7 Data.
Referenced by XSysMonPsu_GetMinMaxMeasurement.
XSM_MAX_SUPPLY8
Maximum SUPPLY8 Data.
XSM_MAX_SUPPLY9
Maximum SUPPLY9 Data.
XSM_MAX_SUPPLY10
Maximum SUPPLY10 Data.
XSM_MAX_VCCAMS
Maximum VCCAMS Data.
XSM_MAX_TEMP_REMOTE
Maximum Remote Temperature Data.
Referenced by XSysMonPsu_GetMinMaxMeasurement.
XSM_MIN_SUPPLY7
Minimum SUPPLY7 Data.
Referenced by XSysMonPsu_GetMinMaxMeasurement.
XSM_MIN_SUPPLY8
Minimum SUPPLY8 Data.
XSM_MIN_SUPPLY9
Minimum SUPPLY9 Data.
XSM_MIN_SUPPLY10
Minimum SUPPLY10 Data.
XSM_MIN_VCCAMS
Minimum VCCAMS Data.
XSM_MIN_TEMP_REMOTE
Minimum Remote Temperature Data.
Referenced by XSysMonPsu_GetMinMaxMeasurement.
XSM_AVG_0_SAMPLES
No Averaging.
XSM_AVG_16_SAMPLES
Average 16 samples.
Referenced by SysMonPsuIntrExample, SysMonPsuLowLevelExample, SysMonPsuPolledPrintfExample.
XSM_AVG_64_SAMPLES
Average 64 samples.
XSM_AVG_256_SAMPLES
Average 256 samples.
Referenced by XSysMonPsu_SetAvg.
XSM_SEQ_MODE_SAFE
Default Safe Mode.
Referenced by SysMonPsuIntrExample, SysMonPsuLowLevelExample, SysMonPsuPolledPrintfExample, XSysMonPsu_SetSeqAcqTime, XSysMonPsu_SetSeqAvgEnables, XSysMonPsu_SetSeqChEnables, XSysMonPsu_SetSeqInputMode.
XSM_SEQ_MODE_ONEPASS
Onepass through Sequencer.
XSM_SEQ_MODE_CONTINPASS
Continuous Cycling Seqquencer.
Referenced by SysMonPsuIntrExample, SysMonPsuLowLevelExample, SysMonPsuPolledPrintfExample.
XSM_SEQ_MODE_SINGCHAN
Single channel - No Sequencing.
Referenced by SysMonPsuAMSExample, SysMonPsuSingleChannelIntrExample, XSysMonPsu_SetSequencerMode, XSysMonPsu_SetSingleChParams.
XSM_SEQ_MODE_OYLMPUS
Olympus mode.
Referenced by XSysMonPsu_SetSequencerMode.
XSM_CLK_DIV_MIN
Minimum Clock Divisor value.
XSM_CLK_DIV_MAX
Maximum Clock Divisor value.
XSM_PWR_MODE_NORMAL
Normal operation.
XSM_PWR_MODE_PARTIAL_SLEEP
Partial sleep mode.
XSM_PWR_MODE_SLEEP
Full sleep mode.
XSM_ATR_TEMP_UPPER
High user Temperature limit.
Referenced by SysMonPsuIntrExample.
XSM_ATR_SUP1_UPPER
Supply1 high voltage limit.
Referenced by SysMonPsuIntrExample, SysMonPsuSingleChannelIntrExample, XSysMonPsu_SelfTest.
XSM_ATR_SUP2_UPPER
Supply2 high voltage limit.
XSM_ATR_OT_UPPER
Upper Over Temperature limit.
XSM_ATR_TEMP_LOWER
Low user Temperature.
Referenced by SysMonPsuIntrExample.
XSM_ATR_SUP1_LOWER
Suuply1 low voltage limit.
Referenced by SysMonPsuIntrExample, SysMonPsuSingleChannelIntrExample.
XSM_ATR_SUP2_LOWER
Supply2 low voltage limit.
XSM_ATR_OT_LOWER
Lower Over Temperature limit.
XSM_ATR_SUP3_UPPER
Supply3 high voltage limit.
Referenced by SysMonPsuIntrExample.
XSM_ATR_SUP4_UPPER
Supply4 high voltage limit.
XSM_ATR_SUP5_UPPER
Supply5 high voltage limit.
XSM_ATR_SUP6_UPPER
Supply6 high voltage limit.
XSM_ATR_SUP3_LOWER
Supply3 low voltage limit.
Referenced by SysMonPsuIntrExample.
XSM_ATR_SUP4_LOWER
Supply4 low voltage limit.
XSM_ATR_SUP5_LOWER
Supply5 low voltage limit.
XSM_ATR_SUP6_LOWER
Supply6 low voltage limit.
XSM_ATR_SUP7_UPPER
Supply7 high voltage limit.
XSM_ATR_SUP8_UPPER
Supply8 high voltage limit.
XSM_ATR_SUP9_UPPER
Supply9 high voltage limit.
XSM_ATR_SUP10_UPPER
Supply10 high voltage limit.
XSM_ATR_VCCAMS_UPPER
VCCAMS high voltage limit.
XSM_ATR_TEMP_RMTE_UPPER
High remote Temperature limit.
Referenced by XSysMonPsu_GetAlarmThreshold, XSysMonPsu_SetAlarmThreshold.
XSM_ATR_SUP7_LOWER
Supply7 low voltage limit.
Referenced by XSysMonPsu_GetAlarmThreshold, XSysMonPsu_SetAlarmThreshold.
XSM_ATR_SUP8_LOWER
Supply8 low voltage limit.
XSM_ATR_SUP9_LOWER
Supply9 low voltage limit.
XSM_ATR_SUP10_LOWER
Supply10 low voltage limit.
XSM_ATR_VCCAMS_LOWER
VCCAMS low voltage limit.
XSM_ATR_TEMP_RMTE_LOWER
Low remote Temperature limit.
Referenced by XSysMonPsu_GetAlarmThreshold, XSysMonPsu_SetAlarmThreshold.
XSM_CFR_ALM_SUPPLY13_MASK
Alarm 13 - FPD Temperature.
XSM_CFR_ALM_SUPPLY12_MASK
Alarm 12 - VCCAMS/VCCADC.
XSM_CFR_ALM_SUPPLY11_MASK
Alarm 11 - SUPPLY10.
XSM_CFR_ALM_SUPPLY10_MASK
Alarm 10 - SUPPLY9.
XSM_CFR_ALM_SUPPLY9_MASK
Alarm 9 - SUPPLY8.
XSM_CFR_ALM_SUPPLY8_MASK
Alarm 8 - SUPPLY7.
XSM_CFR_ALM_SUPPLY6_MASK
Alarm 6 - SUPPLY6.
XSM_CFR_ALM_SUPPLY5_MASK
Alarm 5 - SUPPLY5.
XSM_CFR_ALM_SUPPLY4_MASK
Alarm 4 - SUPPLY4.
XSM_CFR_ALM_SUPPLY3_MASK
Alarm 3 - SUPPLY3.
Referenced by SysMonPsuIntrExample.
XSM_CFR_ALM_SUPPLY2_MASK
Alarm 2 - SUPPLY2.
XSM_CFR_ALM_SUPPLY1_MASK
Alarm 1 - SUPPLY1.
Referenced by SysMonPsuIntrExample.
XSM_CFR_ALM_TEMP_MASK
Alarm 0 - Temperature.
Referenced by SysMonPsuIntrExample.
XSM_CFR_ALM_OT_MASK
Over Temperature Alarm.
XSYSMONPSU_H_
XSM_POLL_TIMEOUT
XSYSMON_PS
XSYSMON_PL
XSYSMON_AMS
XPS_BA_OFFSET
XPL_BA_OFFSET
XSM_ADC_CH_OFFSET
XSM_AMS_CH_OFFSET
XSM_MIN_MAX_CH_OFFSET
XSysMonPsu_RawToTemperature_OnChip
This macro converts System Monitor Raw Data to Temperature(centigrades) for On-Chip Sensors.
AdcData is the SysMon Raw ADC Data. The Temperature in centigrades. C-Style signature: float XSysMon_RawToTemperature_OnChip(u32 AdcData)
Referenced by SysMonPsuIntrExample, SysMonPsuPolledPrintfExample.
XSysMonPsu_RawToTemperature_OT_OnChip
This macro converts System Monitor 12-bit OT Raw Data to Temperature(centigrades) for On-Chip Sensors.
AdcData is the SysMon 12-bit Raw ADC Data. The Temperature in centigrades. C-Style signature: float XSysMonPsu_RawToTemperature_OT_OnChip(u32 AdcData)
XSysMonPsu_RawToTemperature_ExternalRef
This macro converts System Monitor Raw Data to Temperature(centigrades) for external reference.
AdcData is the SysMon Raw ADC Data. The Temperature in centigrades. C-Style signature: float XSysMon_RawToTemperature_ExternalRef(u32 AdcData)
XSysMonPsu_RawToTemperature_OT_ExternalRef
This macro converts System Monitor 12-bit OT Raw Data to Temperature(centigrades) for external reference.
AdcData is the SysMon 12-bit Raw ADC Data. The Temperature in centigrades. C-Style signature: float XSysMonPsu_RawToTemperature_OT_ExternalRef(u32 AdcData)
XSysMonPsu_VpVnRawToVoltage
This macro converts System Monitor Raw Data to Voltage(volts) for VpVn supply.
AdcData is the System Monitor ADC Raw Data. The Voltage in volts. C-Style signature: float XSysMon_VpVnRawToVoltage(u32 AdcData)
XSysMonPsu_RawToVoltage
This macro converts System Monitor Raw Data to Voltage(volts) other than VCCO_PSIO supply.
AdcData is the System Monitor ADC Raw Data. The Voltage in volts. C-Style signature: float XSysMon_RawToVoltage(u32 AdcData)
Referenced by SysMonPsuAMSExample, SysMonPsuIntrExample, SysMonPsuPolledPrintfExample.
XSysMonPsu_VccopsioRawToVoltage
This macro converts System Monitor Raw Data to Voltage(volts) for VCCO_PSIO supply.
AdcData is the System Monitor ADC Raw Data. The Voltage in volts. C-Style signature: float XSysMon_RawToVoltage(u32 AdcData)
XSysMonPsu_TemperatureToRaw_OnChip
This macro converts Temperature in centigrades to System Monitor Raw Data for On-Chip Sensors.
Temperature is the Temperature in centigrades to be converted to System Monitor ADC Raw Data. The System Monitor ADC Raw Data. C-Style signature: int XSysMon_TemperatureToRaw_OnChip(float Temperature)
Referenced by SysMonPsuIntrExample.
XSysMonPsu_TemperatureToRaw_OT_OnChip
This macro converts Temperature in centigrades to System Monitor 12-bit OT Raw Data for On-Chip Sensors.
Temperature is the Temperature in centigrades to be converted to System Monitor ADC 12-bit Raw Data. The System Monitor ADC 12-bit Raw Data. C-Style signature: int XSysMonPsu_TemperatureToRaw_OT_OnChip(float Temperature)
XSysMonPsu_TemperatureToRaw_ExternalRef
This macro converts Temperature in centigrades to System Monitor Raw Data for external reference.
Temperature is the Temperature in centigrades to be converted to System Monitor ADC Raw Data. The System Monitor ADC Raw Data. C-Style signature: int XSysMon_TemperatureToRaw_ExternalRef(float Temperature)
XSysMonPsu_TemperatureToRaw_OT_ExternalRef
This macro converts Temperature in centigrades to System Monitor 12-bit OT Raw Data for external reference.
Temperature is the Temperature in centigrades to be converted to System Monitor ADC 12-bit Raw Data. The System Monitor ADC 12-bit Raw Data. C-Style signature: int XSysMonPsu_TemperatureToRaw_OT_ExternalRef(float Temperature)
XSysMonPsu_VoltageToRaw
This macro converts Voltage in Volts to System Monitor Raw Data other than VCCO_PSIO supply.
Voltage is the Voltage in volts to be converted to System Monitor/ADC Raw Data. The System Monitor ADC Raw Data. C-Style signature: int XSysMon_VoltageToRaw(float Voltage)
Referenced by SysMonPsuIntrExample.
XSysMonPsu_VccopsioVoltageToRaw
This macro converts Voltage in Volts to System Monitor Raw Data for VCCO_PSIO supply.
Voltage is the Voltage in volts to be converted to System Monitor/ADC Raw Data. The System Monitor ADC Raw Data. C-Style signature: int XSysMon_VoltageToRaw(float Voltage)
typedef void(* XSysMonPsu_Handler)(void *CallBackRef))(void *CallBackRef)
This data type defines a handler that an application defines to communicate with interrupt system to retrieve state information about an application.
CallBackRef is a callback reference passed in by the upper layer when setting the handler, and is passed back to the upper layer when the handler is called. It is used to find the device driver instance.
static UINTPTR XSysMonPsu_GetEffBaseAddress(UINTPTR BaseAddress, u32 SysmonBlk)
This static inline macro calculates the effective baseaddress based on the Sysmon instance.
For PS Sysmon, use additional offset XPS_BA_OFFSET and For PL Sysmon, use additional offset XPL_BA_OFFSET. BaseAddress is the starting address of the SysMon block in register database. SysmonBlk is the value that tells whether it is for PS Sysmon block or PL Sysmon block or the AMS controller register region. Returns the effective baseaddress of the sysmon instance.
s32 XSysMonPsu_CfgInitialize(XSysMonPsu *InstancePtr, XSysMonPsu_Config *ConfigPtr, u32 EffectiveAddr)
This function initializes XSysMonPsu device/instance.
This function must be called prior to using the System Monitor device. InstancePtr is a pointer to the XSysMonPsu instance. ConfigPtr points to the XSysMonPsu device configuration structure. EffectiveAddr is the device base address in the virtual memory address space. If the address translation is not used then the physical address is passed. Unexpected errors may occur if the address mapping is changed after this function is invoked. XST_SUCCESS if successful. The user needs to first call the XSysMonPsu_LookupConfig() API which returns the Configuration structure pointer which is passed as a parameter to the XSysMonPsu_CfgInitialize() API.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu_Config::InputClockMHz, XSysMonPsu::IsPlAccessibleByPs, XSysMonPsu::IsReady, XSysMonPsu_IntrClear, XSysMonPsu_IntrGetStatus, XSYSMONPSU_PL_SYSMON_CSTS_OFFSET, XSYSMONPSU_PS_SYSMON_CSTS_OFFSET, XSysMonPsu_Reset, XSysMonPsu_UpdateAdcClkDivisor.
Referenced by SysMonPsuAMSExample, SysMonPsuIntrExample, SysMonPsuPolledPrintfExample, SysMonPsuSingleChannelIntrExample.
void XSysMonPsu_Reset(XSysMonPsu *InstancePtr)
This function resets the SystemMonitor.
InstancePtr is a pointer to the XSysMonPsu instance. None. Upon reset, all Maximum and Minimum status registers will be reset to their default values. Currently running and any averaging will restart. Refer to the device data sheet for the device status and register values after the reset.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSYSMONPSU_VP_VN_OFFSET.
Referenced by XSysMonPsu_CfgInitialize, XSysMonPsu_SelfTest.
u32 XSysMonPsu_GetStatus(XSysMonPsu *InstancePtr, u32 SysmonBlk)
This function reads the contents of the Status Register.
InstancePtr is a pointer to the XSysMonPsu instance. SysmonBlk is the value that tells whether it is for PS Sysmon block or PL Sysmon block register region. A 32-bit value representing the contents of the Status Register. Use the XSYSMONPSU_MON_STS_* constants defined in xsysmonpsu_hw.h to interpret the returned value. None.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSYSMONPSU_MON_STS_OFFSET.
void XSysMonPsu_StartAdcConversion(XSysMonPsu *InstancePtr)
This function starts the ADC conversion in the Single Channel event driven sampling mode.
The EOC bit in Status Register will be set once the conversion is finished. Refer to the device specification for more details. InstancePtr is a pointer to the XSysMonPsu instance. None. The default state of the CONVST bit is a logic 0. The conversion is started when the CONVST bit is set to 1 from 0. This bit is self-clearing so that the next conversion can be started by setting this bit.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSYSMONPSU_PS_SYSMON_CSTS_OFFSET.
u16 XSysMonPsu_GetAdcData(XSysMonPsu *InstancePtr, u8 Channel, u32 Block)
Get the ADC converted data for the specified channel.
InstancePtr is a pointer to the XSysMonPsu instance. Channel is the channel number. Use the XSM_CH_* defined in the file xsysmonpsu.h. The valid channels for PS / PL SysMon are 0 - 6, 8 - 10 and 13 - 37. For AMS, 38 - 53 channels are valid. Block is the value that tells whether it is for PS Sysmon block or PL Sysmon block or the AMS controller register region. A 16-bit value representing the ADC converted data for the specified channel. The System Monitor device guarantees a 10 bit resolution for the ADC converted data and data is the 10 MSB bits of the 16 data read from the device. Please make sure that the proper channel number is passed.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSM_CH_AUX_MAX, XSM_CH_GAINERR_CALIB, XSM_CH_RESERVE1, XSM_CH_SUPPLY3, XSM_CH_SUPPLY4, XSM_CH_SUPPLY7, XSM_CH_SUPPLY_CALIB, XSM_CH_TEMP_REMTE, XSM_CH_VCC_PSLL0.
Referenced by SysMonPsuAMSExample, SysMonPsuIntrExample, SysMonPsuPolledPrintfExample, SysMonPsuSingleChannelIntrExample.
u16 XSysMonPsu_GetCalibCoefficient(XSysMonPsu *InstancePtr, u8 CoeffType, u32 SysmonBlk)
This function gets the calibration coefficient data for the specified parameter.
InstancePtr is a pointer to the XSysMonPsu instance. CoeffType specifies the calibration coefficient to be read. Use XSM_CALIB_* constants defined in xsysmonpsu.h to specify the calibration coefficient to be read. SysmonBlk is the value that tells whether it is for PS Sysmon block or PL Sysmon block register region. A 16-bit value representing the calibration coefficient. The System Monitor device guarantees a 10 bit resolution for the ADC converted data and data is the 10 MSB bits of the 16 data read from the device. None.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSM_CALIB_GAIN_ERROR_COEFF, XSYSMONPSU_CAL_SUP_OFF_OFFSET.
u16 XSysMonPsu_GetMinMaxMeasurement(XSysMonPsu *InstancePtr, u8 MeasurementType, u32 SysmonBlk)
This function reads the Minimum/Maximum measurement for one of the XSM_MIN_* or XSM_MAX_* constants defined in xsysmonpsu.h.
InstancePtr is a pointer to the XSysMonPsu instance. MeasurementType specifies the parameter for which the Minimum/Maximum measurement has to be read. Use XSM_MAX_* and XSM_MIN_* constants defined in xsysmonpsu.h to specify the data to be read. SysmonBlk is the value that tells whether it is for PS Sysmon block or PL Sysmon block register region. A 16-bit value representing the maximum/minimum measurement for specified parameter. The System Monitor device guarantees a 10 bit resolution for the ADC converted data and data is the 10 MSB bits of 16 bit data read from the device.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSM_MAX_SUPPLY6, XSM_MAX_SUPPLY7, XSM_MAX_TEMP_REMOTE, XSM_MIN_SUPPLY4, XSM_MIN_SUPPLY6, XSM_MIN_SUPPLY7, XSM_MIN_TEMP_REMOTE.
Referenced by SysMonPsuIntrExample, SysMonPsuPolledPrintfExample.
void XSysMonPsu_SetAvg(XSysMonPsu *InstancePtr, u8 Average, u32 SysmonBlk)
This function sets the number of samples of averaging that is to be done for all the channels in both the single channel mode and sequence mode of operations.
InstancePtr is a pointer to the XSysMonPsu instance. Average is the number of samples of averaging programmed to the Configuration Register 0. Use the XSM_AVG_* definitions defined in xsysmonpsu.h file : XSM_AVG_0_SAMPLES for no averagingXSM_AVG_16_SAMPLES for 16 samples of averagingXSM_AVG_64_SAMPLES for 64 samples of averagingXSM_AVG_256_SAMPLES for 256 samples of averaging SysmonBlk is the value that tells whether it is for PS Sysmon block or PL Sysmon block register region. None. None.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSM_AVG_256_SAMPLES, XSYSMONPSU_CFG_REG0_OFFSET.
Referenced by SysMonPsuIntrExample, SysMonPsuPolledPrintfExample.
u8 XSysMonPsu_GetAvg(XSysMonPsu *InstancePtr, u32 SysmonBlk)
This function returns the number of samples of averaging configured for all the channels in the Configuration Register 0.
InstancePtr is a pointer to the XSysMonPsu instance. SysmonBlk is the value that tells whether it is for PS Sysmon block or PL Sysmon block register region. The averaging read from the Configuration Register 0 is returned. Use the XSM_AVG_* bit definitions defined in xsysmonpsu.h file to interpret the returned value : XSM_AVG_0_SAMPLES means no averagingXSM_AVG_16_SAMPLES means 16 samples of averagingXSM_AVG_64_SAMPLES means 64 samples of averagingXSM_AVG_256_SAMPLES means 256 samples of averaging None.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSYSMONPSU_CFG_REG0_OFFSET.
s32 XSysMonPsu_SetSingleChParams(XSysMonPsu *InstancePtr, u8 Channel, u32 IncreaseAcqCycles, u32 IsEventMode, u32 IsDifferentialMode, u32 SysmonBlk)
The function sets the given parameters in the Configuration Register 0 in the single channel mode.
InstancePtr is a pointer to the XSysMonPsu instance. Channel is the channel number for conversion. The valid channels are 0 - 6, 8 - 10, 13 - 37. IncreaseAcqCycles is a boolean parameter which specifies whether the Acquisition time for the external channels has to be increased to 10 ADCCLK cycles (specify TRUE) or remain at the default 4 ADCCLK cycles (specify FALSE). This parameter is only valid for the external channels. IsEventMode is a boolean parameter that specifies continuous sampling (specify FALSE) or event driven sampling mode (specify TRUE) for the given channel. IsDifferentialMode is a boolean parameter which specifies unipolar(specify FALSE) or differential mode (specify TRUE) for the analog inputs. The input mode is only valid for the external channels. SysmonBlk is the value that tells whether it is for PS Sysmon block or PL Sysmon block register region. XST_SUCCESS if the given values were written successfully to the Configuration Register 0.XST_FAILURE if the channel sequencer is enabled or the input parameters are not valid for the selected channel. The number of samples for the averaging for all the channels is set by using the function XSysMonPsu_SetAvg.The calibration of the device is done by doing a ADC conversion on the calibration channel(channel 8). The input parameters IncreaseAcqCycles, IsDifferentialMode and IsEventMode are not valid for this channel.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSM_CH_AUX_MAX, XSM_CH_AUX_MIN, XSM_CH_GAINERR_CALIB, XSM_CH_RESERVE1, XSM_CH_SUPPLY3, XSM_CH_SUPPLY4, XSM_CH_SUPPLY_CALIB, XSM_CH_TEMP_REMTE, XSM_CH_VCC_PSLL0, XSM_CH_VPVN, XSM_SEQ_MODE_SINGCHAN, XSYSMONPSU_CFG_REG0_OFFSET, XSysMonPsu_GetSequencerMode.
Referenced by SysMonPsuAMSExample, SysMonPsuSingleChannelIntrExample.
void XSysMonPsu_SetAlarmEnables(XSysMonPsu *InstancePtr, u32 AlmEnableMask, u32 SysmonBlk)
This function enables the alarm outputs for the specified alarms in the Configuration Registers 1:
- OT for Over Temperature (XSYSMONPSU_CFR_REG1_ALRM_OT_MASK) - ALM0 for On board Temperature (XSYSMONPSU_CFR_REG1_ALRM_TEMP_MASK) - ALM1 for SUPPLY1 (XSYSMONPSU_CFR_REG1_ALRM_SUPPLY1_MASK) - ALM2 for SUPPLY2 (XSYSMONPSU_CFR_REG1_ALRM_SUPPLY2_MASK) - ALM3 for SUPPLY3 (XSYSMONPSU_CFR_REG1_ALRM_SUPPLY3_MASK) - ALM4 for SUPPLY4 (XSYSMONPSU_CFR_REG1_ALRM__SUPPLY4_MASK) - ALM5 for SUPPLY5 (XSYSMONPSU_CFR_REG1_ALRM_SUPPLY5_MASK) - ALM6 for SUPPLY6 (XSYSMONPSU_CFR_REG1_ALRM_SUPPLY6_MASK) InstancePtr is a pointer to the XSysMonPsu instance. AlmEnableMask is the bit-mask of the alarm outputs to be enabled in the Configuration Registers 1 and 3. Bit positions of 1 will be enabled. Bit positions of 0 will be disabled. This mask is formed by OR'ing XSYSMONPSU_CFR_REG1_ALRM_*_MASK masks defined in xsysmonpsu.h, but XSM_CFR_ALM_SUPPLY8_MASK to XSM_CFR_ALM_SUPPLY13_MASK are applicable only for PS. SysmonBlk is the value that tells whether it is for PS Sysmon block or PL Sysmon block register region. None. The implementation of the alarm enables in the Configuration register 1 is such that the alarms for bit positions of 0 will be enabled and alarms for bit positions of 1 will be disabled. The alarm outputs specified by the AlmEnableMask are negated before writing to the Configuration Register 1 because it was Disable register bits. Upper 16 bits of AlmEnableMask are applicable only for PS.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSYSMONPSU_CFG_REG1_OFFSET.
Referenced by SysMonPsuIntrExample, SysMonPsuPolledPrintfExample, SysMonPsuSingleChannelIntrExample.
u32 XSysMonPsu_GetAlarmEnables(XSysMonPsu *InstancePtr, u32 SysmonBlk)
This function gets the status of the alarm output enables in the Configuration Register 1.
InstancePtr is a pointer to the XSysMonPsu instance. SysmonBlk is the value that tells whether it is for PS Sysmon block or PL Sysmon block register region. This is the bit-mask of the enabled alarm outputs in the Configuration Register 1. Use the masks XSYSMONPSU_CFG_REG1_ALRM_*_MASK masks defined in xsysmonpsu.h to interpret the returned value. Bit positions of 1 indicate that the alarm output is enabled. Bit positions of 0 indicate that the alarm output is disabled.The implementation of the alarm enables in the Configuration register 1 is such that alarms for the bit positions of 1 will be disabled and alarms for bit positions of 0 will be enabled. The enabled alarm outputs returned by this function is the negated value of the the data read from the Configuration Register 1. Upper 16 bits of return value are valid only if the channel selected is PS.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSYSMONPSU_CFG_REG1_OFFSET.
void XSysMonPsu_SetSequencerMode(XSysMonPsu *InstancePtr, u8 SequencerMode, u32 SysmonBlk)
This function sets the specified Channel Sequencer Mode in the Configuration Register 1 :
- Default safe mode (XSM_SEQ_MODE_SAFE) - One pass through sequence (XSM_SEQ_MODE_ONEPASS) - Continuous channel sequencing (XSM_SEQ_MODE_CONTINPASS) - Single Channel/Sequencer off (XSM_SEQ_MODE_SINGCHAN) - Olympus sampling mode (XSM_SEQ_MODE_OYLMPUS) InstancePtr is a pointer to the XSysMonPsu instance. SequencerMode is the sequencer mode to be set. Use XSM_SEQ_MODE_* bits defined in xsysmonpsu.h. SysmonBlk is the value that tells whether it is for PS Sysmon block or PL Sysmon block register region. None. Only one of the modes can be enabled at a time.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSM_SEQ_MODE_OYLMPUS, XSM_SEQ_MODE_SINGCHAN, XSYSMONPSU_CFG_REG1_OFFSET.
Referenced by SysMonPsuAMSExample, SysMonPsuIntrExample, SysMonPsuPolledPrintfExample, SysMonPsuSingleChannelIntrExample.
u8 XSysMonPsu_GetSequencerMode(XSysMonPsu *InstancePtr, u32 SysmonBlk)
This function gets the channel sequencer mode from the Configuration Register 1.
InstancePtr is a pointer to the XSysMonPsu instance. SysmonBlk is the value that tells whether it is for PS Sysmon block or PL Sysmon block register region. The channel sequencer mode : XSM_SEQ_MODE_SAFE : Default safe modeXSM_SEQ_MODE_ONEPASS : One pass through sequenceXSM_SEQ_MODE_CONTINPASS : Continuous channel sequencingXSM_SEQ_MODE_SINGCHAN : Single channel/Sequencer offXSM_SEQ_MODE_OLYMPUS : Olympus sampling mode None.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSYSMONPSU_CFG_REG1_OFFSET.
Referenced by XSysMonPsu_SetSeqAcqTime, XSysMonPsu_SetSeqAvgEnables, XSysMonPsu_SetSeqChEnables, XSysMonPsu_SetSeqInputMode, XSysMonPsu_SetSingleChParams.
void XSysMonPsu_SetSequencerEvent(XSysMonPsu *InstancePtr, u32 IsEventMode, u32 SysmonBlk)
The function enables the Event mode or Continuous mode in the sequencer mode.
InstancePtr is a pointer to the XSysMonPsu instance. IsEventMode is a boolean parameter that specifies continuous sampling (specify FALSE) or event driven sampling mode (specify TRUE) for the channel. SysmonBlk is the value that tells whether it is for PS Sysmon block or PL Sysmon block register region. None. None.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSYSMONPSU_CFG_REG0_OFFSET.
s32 XSysMonPsu_GetSequencerEvent(XSysMonPsu *InstancePtr, u32 SysmonBlk)
The function returns the mode of the sequencer.
InstancePtr is a pointer to the XSysMonPsu instance. SysmonBlk is the value that tells whether it is for PS Sysmon block or PL Sysmon block register region. Returns the Sequencer mode. XSYSMONPSU_EVENT_MODE for Event mode and XSYSMONPSU_CONTINUOUS_MODE for continuous mode. None.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSYSMONPSU_CFG_REG0_OFFSET.
void XSysMonPsu_SetExtenalMux(XSysMonPsu *InstancePtr, u8 Channel, u32 SysmonBlk)
The function enables the external mux and connects a channel to the mux.
InstancePtr is a pointer to the XSysMonPsu instance. Channel is the channel number used to connect to the external Mux. The valid channels are 0 to 5 and 16 to 31. SysmonBlk is the value that tells whether it is for PS Sysmon block or PL Sysmon block register region. XST_SUCCESS if the given values were written successfully to the Configuration Register 0.XST_FAILURE if the channel sequencer is enabled or the input parameters are not valid for the selected channel. None.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSM_CH_AUX_MAX, XSM_CH_AUX_MIN, XSM_CH_VREFN, XSYSMONPSU_CFG_REG0_OFFSET.
u32 XSysMonPsu_GetExtenalMux(XSysMonPsu *InstancePtr, u32 SysmonBlk)
The function returns the external mux channel.
InstancePtr is a pointer to the XSysMonPsu instance. SysmonBlk is the value that tells whether it is for PS Sysmon block or PL Sysmon block register region. Returns the channel number used to connect to the external Mux. The valid channels are 0 to 6, 8 to 16, and 31 to 36.. None.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSYSMONPSU_CFG_REG0_OFFSET.
void XSysMonPsu_SetAdcClkDivisor(XSysMonPsu *InstancePtr, u8 Divisor, u32 SysmonBlk)
The function sets the frequency of the ADCCLK by configuring the DCLK to ADCCLK ratio in the Configuration Register #2.
InstancePtr is a pointer to the XSysMonPsu instance. Divisor is clock divisor used to derive ADCCLK from DCLK. Valid values of the divisor are PS: 0 means divide by 8.1,2 means divide by 2.3 to 255 means divide by that value. PL:0,1,2 means divide by 2.3 to 255 means divide by that value. Refer to the device specification for more details. SysmonBlk is the value that tells whether it is for PS Sysmon block or PL Sysmon block register region. None. - The ADCCLK is an internal clock used by the ADC and is synchronized to the DCLK clock. The ADCCLK is equal to DCLK divided by the user selection in the Configuration Register 2. There is no Assert on the minimum value of the Divisor.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSYSMONPSU_CFG_REG2_OFFSET.
u8 XSysMonPsu_GetAdcClkDivisor(XSysMonPsu *InstancePtr, u32 SysmonBlk)
The function gets the ADCCLK divisor from the Configuration Register 2.
InstancePtr is a pointer to the XSysMon instance. SysmonBlk is the value that tells whether it is for PS Sysmon block or PL Sysmon block register region. The divisor read from the Configuration Register 2. The ADCCLK is an internal clock used by the ADC and is synchronized to the DCLK clock. The ADCCLK is equal to DCLK divided by the user selection in the Configuration Register 2.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSYSMONPSU_CFG_REG2_OFFSET.
u32 XSysMonPsu_UpdateAdcClkDivisor(XSysMonPsu *InstancePtr, u32 SysmonBlk, u8 *DivCode)
The function update the ADCCLK divisor to the Configuration Register 2.
InstancePtr is a pointer to the XSysMon instance. SysmonBlk is the value that tells whether it is for PS Sysmon block or PL Sysmon block register region. DivCode is a pointer to be populated with the divisor code. - XST_SUCCESS if valid divisor found and applied. XST_FAILURE if valid divisor does not exist. The ADCCLK is an internal clock used by the ADC and is synchronized to the DCLK clock. The ADCCLK is equal to DCLK divided by the user selection in the Configuration Register 2.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu_Config::InputClockMHz, XSYSMONPSU_CFG_REG2_OFFSET.
Referenced by XSysMonPsu_CfgInitialize.
s32 XSysMonPsu_SetSeqChEnables(XSysMonPsu *InstancePtr, u64 ChEnableMask, u32 SysmonBlk)
This function enables the specified channels in the ADC Channel Selection Sequencer Registers.
The sequencer must be in the Safe Mode before writing to these registers. InstancePtr is a pointer to the XSysMonPsu instance. ChEnableMask is the bit mask of all the channels to be enabled. Use XSYSMONPSU_SEQ_CH* defined in xsysmon_hw.h to specify the Channel numbers. Bit masks of 1 will be enabled and bit mask of 0 will be disabled. The ChEnableMask is a 64 bit mask that is written to the three 16 bit ADC Channel Selection Sequencer Registers. SysmonBlk is the value that tells whether it is for PS Sysmon block or PL Sysmon block register region. XST_SUCCESS if the given values were written successfully to the ADC Channel Selection Sequencer Registers.XST_FAILURE if the channel sequencer is enabled. None.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSM_SEQ_MODE_SAFE, XSysMonPsu_GetSequencerMode, XSYSMONPSU_SEQ_CH0_OFFSET, XSYSMONPSU_SEQ_CH1_OFFSET.
Referenced by SysMonPsuIntrExample, SysMonPsuPolledPrintfExample.
u64 XSysMonPsu_GetSeqAvgEnables(XSysMonPsu *InstancePtr, u32 SysmonBlk)
This function returns the channels for which the averaging has been enabled in the ADC Channel Averaging Enables Sequencer Registers.
InstancePtr is a pointer to the XSysMonPsu instance. SysmonBlk is the value that tells whether it is for PS Sysmon block or PL Sysmon block register region. The status of averaging (enabled/disabled) for all the channels. Use XSYSMONPSU_SEQ_AVERAGE* defined in xsysmonpsu_hw.h to interpret the Channel numbers. Bit masks of 1 are the channels for which averaging is enabled and bit mask of 0 are the channels for averaging is disabled. None.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSYSMONPSU_SEQ_AVERAGE0_OFFSET, XSYSMONPSU_SEQ_AVERAGE1_OFFSET.
u64 XSysMonPsu_GetSeqChEnables(XSysMonPsu *InstancePtr, u32 SysmonBlk)
This function gets the channel enable bits status from the ADC Channel Selection Sequencer Registers.
InstancePtr is a pointer to the XSysMonPsu instance. SysmonBlk is the value that tells whether it is for PS Sysmon block or PL Sysmon block register region. Gets the channel enable bits. Use XSYSMONPSU_SEQ_CH* defined in xsysmonpsu_hw.h to interpret the Channel numbers. Bit masks of 1 are the channels that are enabled and bit mask of 0 are the channels that are disabled.None. None.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSYSMONPSU_SEQ_CH0_OFFSET, XSYSMONPSU_SEQ_CH1_OFFSET.
s32 XSysMonPsu_SetSeqAvgEnables(XSysMonPsu *InstancePtr, u64 AvgEnableChMask, u32 SysmonBlk)
This function enables the averaging for the specified channels in the ADC Channel Averaging Enable Sequencer Registers.
The sequencer must be in the Safe Mode before writing to these registers. InstancePtr is a pointer to the XSysMonPsu instance. AvgEnableChMask is the bit mask of all the channels for which averaging is to be enabled. Use XSYSMONPSU_SEQ_AVERAGE* defined in xsysmonpsu_hw.h to specify the Channel numbers. Averaging will be enabled for bit masks of 1 and disabled for bit mask of 0. The AvgEnableChMask is a 64 bit mask that is written to the three 16 bit ADC Channel Averaging Enable Sequencer Registers. SysmonBlk is the value that tells whether it is for PS Sysmon block or PL Sysmon block register region. XST_SUCCESS if the given values were written successfully to the ADC Channel Averaging Enables Sequencer Registers.XST_FAILURE if the channel sequencer is enabled. None.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSM_SEQ_MODE_SAFE, XSysMonPsu_GetSequencerMode, XSYSMONPSU_SEQ_AVERAGE0_OFFSET, XSYSMONPSU_SEQ_AVERAGE1_OFFSET.
Referenced by SysMonPsuIntrExample, SysMonPsuPolledPrintfExample.
s32 XSysMonPsu_SetSeqInputMode(XSysMonPsu *InstancePtr, u64 InputModeChMask, u32 SysmonBlk)
This function sets the Analog input mode for the specified channels in the ADC Channel Analog-Input Mode Sequencer Registers.
The sequencer must be in the Safe Mode before writing to these registers. InstancePtr is a pointer to the XSysMonPsu instance. InputModeChMask is the bit mask of all the channels for which the input mode is differential mode. Use XSYSMONPSU_SEQ_INPUT_MDE* defined in xsysmonpsu_hw.h to specify the channel numbers. Differential or Bipolar input mode will be set for bit masks of 1 and unipolar input mode for bit masks of 0. The InputModeChMask is a 64 bit mask that is written to the three 16 bit ADC Channel Analog-Input Mode Sequencer Registers. SysmonBlk is the value that tells whether it is for PS Sysmon block or PL Sysmon block register region. XST_SUCCESS if the given values were written successfully to the ADC Channel Analog-Input Mode Sequencer Registers.XST_FAILURE if the channel sequencer is enabled. None.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSM_SEQ_MODE_SAFE, XSysMonPsu_GetSequencerMode, XSYSMONPSU_SEQ_INPUT_MDE0_OFFSET, XSYSMONPSU_SEQ_INPUT_MDE1_OFFSET.
u64 XSysMonPsu_GetSeqInputMode(XSysMonPsu *InstancePtr, u32 SysmonBlk)
This function gets the Analog input mode for all the channels from the ADC Channel Analog-Input Mode Sequencer Registers.
InstancePtr is a pointer to the XSysMonPsu instance. SysmonBlk is the value that tells whether it is for PS Sysmon block or PL Sysmon block register region. The input mode for all the channels. Use XSYSMONPSU_SEQ_INPUT_MDE* defined in xsysmonpsu_hw.h to interpret the Channel numbers. Bit masks of 1 are the channels for which input mode is differential/Bipolar and bit mask of 0 are the channels for which input mode is unipolar. None.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSYSMONPSU_SEQ_INPUT_MDE0_OFFSET, XSYSMONPSU_SEQ_INPUT_MDE1_OFFSET.
s32 XSysMonPsu_SetSeqAcqTime(XSysMonPsu *InstancePtr, u64 AcqCyclesChMask, u32 SysmonBlk)
This function sets the number of Acquisition cycles in the ADC Channel Acquisition Time Sequencer Registers.
The sequencer must be in the Safe Mode before writing to these registers. InstancePtr is a pointer to the XSysMonPsu instance. AcqCyclesChMask is the bit mask of all the channels for which the number of acquisition cycles is to be extended. Use XSYSMONPSU_SEQ_ACQ* defined in xsysmonpsu_hw.h to specify the Channel numbers. Acquisition cycles will be extended to 10 ADCCLK cycles for bit masks of 1 and will be the default 4 ADCCLK cycles for bit masks of 0. The AcqCyclesChMask is a 64 bit mask that is written to the three 16 bit ADC Channel Acquisition Time Sequencer Registers. SysmonBlk is the value that tells whether it is for PS Sysmon block or PL Sysmon block register region. XST_SUCCESS if the given values were written successfully to the Channel Sequencer Registers.XST_FAILURE if the channel sequencer is enabled. None.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSM_SEQ_MODE_SAFE, XSysMonPsu_GetSequencerMode, XSYSMONPSU_SEQ_ACQ0_OFFSET, XSYSMONPSU_SEQ_ACQ1_OFFSET, XSYSMONPSU_SEQ_ACQ2_OFFSET.
u64 XSysMonPsu_GetSeqAcqTime(XSysMonPsu *InstancePtr, u32 SysmonBlk)
This function gets the status of acquisition time from the ADC Channel Acquisition Time Sequencer Registers.
InstancePtr is a pointer to the XSysMonPsu instance. SysmonBlk is the value that tells whether it is for PS Sysmon block or PL Sysmon block register region. The acquisition time for all the channels. Use XSYSMONPSU_SEQ_ACQ* defined in xsysmonpsu_hw.h to interpret the Channel numbers. Bit masks of 1 are the channels for which acquisition cycles are extended and bit mask of 0 are the channels for which acquisition cycles are not extended. None.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSYSMONPSU_SEQ_ACQ0_OFFSET, XSYSMONPSU_SEQ_ACQ1_OFFSET, XSYSMONPSU_SEQ_ACQ2_OFFSET.
void XSysMonPsu_SetAlarmThreshold(XSysMonPsu *InstancePtr, u8 AlarmThrReg, u16 Value, u32 SysmonBlk)
This functions sets the contents of the given Alarm Threshold Register.
InstancePtr is a pointer to the XSysMonPsu instance. AlarmThrReg is the index of an Alarm Threshold Register to be set. Use XSM_ATR_* constants defined in xsysmonpsu.h to specify the index. Value is the 16-bit threshold value to write into the register. SysmonBlk is the value that tells whether it is for PS Sysmon block or PL Sysmon block register region. None. None.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSM_ATR_SUP7_LOWER, XSM_ATR_TEMP_RMTE_LOWER, XSM_ATR_TEMP_RMTE_UPPER, XSYSMONPSU_ALRM_OT_LWR_OFFSET, XSYSMONPSU_ALRM_OT_UPR_OFFSET, XSYSMONPSU_ALRM_TEMP_LWR_OFFSET, XSYSMONPSU_ALRM_TEMP_UPR_OFFSET, XSYSMONPSU_ALRM_TREMOTE_LWR_OFFSET.
Referenced by SysMonPsuIntrExample, SysMonPsuSingleChannelIntrExample, XSysMonPsu_SelfTest.
u16 XSysMonPsu_GetAlarmThreshold(XSysMonPsu *InstancePtr, u8 AlarmThrReg, u32 SysmonBlk)
This function returns the contents of the specified Alarm Threshold Register.
InstancePtr is a pointer to the XSysMonPsu instance. AlarmThrReg is the index of an Alarm Threshold Register to be read. Use XSM_ATR_* constants defined in xsysmonpsu.h to specify the index. SysmonBlk is the value that tells whether it is for PS Sysmon block or PL Sysmon block register region. A 16-bit value representing the contents of the selected Alarm Threshold Register. None.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSM_ATR_SUP7_LOWER, XSM_ATR_TEMP_RMTE_LOWER, XSM_ATR_TEMP_RMTE_UPPER, XSYSMONPSU_ALRM_OT_LWR_OFFSET, XSYSMONPSU_ALRM_OT_UPR_OFFSET, XSYSMONPSU_ALRM_TEMP_LWR_OFFSET, XSYSMONPSU_ALRM_TEMP_UPR_OFFSET, XSYSMONPSU_ALRM_TREMOTE_LWR_OFFSET.
Referenced by SysMonPsuIntrExample, XSysMonPsu_SelfTest.
void XSysMonPsu_SetPSAutoConversion(XSysMonPsu *InstancePtr)
This function sets the conversion to be automatic for PS SysMon.
InstancePtr is a pointer to the XSysMonPsu instance. None In the auto-trigger mode, sample rate is of 1 Million samples.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSYSMONPSU_PS_SYSMON_CSTS_OFFSET.
u32 XSysMonPsu_GetMonitorStatus(XSysMonPsu *InstancePtr)
This function gets the AMS monitor status.
InstancePtr is a pointer to the XSysMonPsu instance. Returns the monitor status. See XSYSMONPSU_MON_STS_*_MASK definitions present in xsysmonpsu_hw.h for knowing the status. None
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSYSMONPSU_MON_STS_OFFSET.
void XSysMonPsu_InitInstance(XSysMonPsu *InstancePtr, XSysMonPsu_Config *ConfigPtr)
This function initializes XSysMonPsu device/instance.
InstancePtr is a pointer to the XSysMonPsu instance. ConfigPtr points to the XSysMonPsu device configuration structure. None The user needs to first call the XSysMonPsu_LookupConfig() API which returns the Configuration structure pointer, this pointer is then passed as a parameter to the XSysMonPsu_InitInstance() API. Note that this function just initializes the instance and doesn't configure the System Monitor device.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady.
void XSysMonPsu_IntrEnable(XSysMonPsu *InstancePtr, u64 Mask)
This function enables the specified interrupts in the device.
InstancePtr is a pointer to the XSysMonPsu instance. Mask is the 64 bit-mask of the interrupts to be enabled. Bit positions of 1 will be enabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XSYSMONPSU_IER_0_* and XSYSMONPSU_IER_1_* bits defined in xsysmonpsu_hw.h. None. None.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSYSMONPSU_IER_0_OFFSET, XSYSMONPSU_IER_1_OFFSET.
Referenced by SysMonPsuIntrExample, SysMonPsuSingleChannelIntrExample.
void XSysMonPsu_IntrDisable(XSysMonPsu *InstancePtr, u64 Mask)
This function disables the specified interrupts in the device.
InstancePtr is a pointer to the XSysMonPsu instance. Mask is the 64 bit-mask of the interrupts to be disabled. Bit positions of 1 will be disabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XSYSMONPSU_IDR_0_* and XSYSMONPSU_IDR_1_* bits defined in xsysmonpsu_hw.h. None. None.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSYSMONPSU_IDR_0_OFFSET, XSYSMONPSU_IDR_1_OFFSET.
Referenced by SysMonPsuSingleChannelIntrExample.
u64 XSysMonPsu_IntrGetEnabled(XSysMonPsu *InstancePtr)
This function returns the enabled interrupts read from the Interrupt Enable Register (IER).
Use the XSYSMONPSU_IER_0_* and XSYSMONPSU_IER_1_* constants defined in xsysmonpsu_hw.h to interpret the returned value. InstancePtr is a pointer to the XSysMonPsu instance. A 64-bit value representing the contents of the Interrupt Mask Registers (IMR1 IMR0). None.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSYSMONPSU_IMR_0_OFFSET, XSYSMONPSU_IMR_1_OFFSET.
u64 XSysMonPsu_IntrGetStatus(XSysMonPsu *InstancePtr)
This function returns the interrupt status read from Interrupt Status Register(ISR).
Use the XSYSMONPSU_ISR_0_* and XSYSMONPSU_ISR_1_ constants defined in xsysmonpsu_hw.h to interpret the returned value. InstancePtr is a pointer to the XSysMonPsu instance. A 64-bit value representing the contents of the Interrupt Status Registers (ISR1 ISR0). None.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSYSMONPSU_ISR_0_OFFSET, XSYSMONPSU_ISR_1_OFFSET.
Referenced by SysMonPsuAMSExample, SysMonPsuIntrExample, SysMonPsuPolledPrintfExample, SysMonPsuSingleChannelIntrExample, XSysMonPsu_CfgInitialize.
void XSysMonPsu_IntrClear(XSysMonPsu *InstancePtr, u64 Mask)
This function clears the specified interrupts in the Interrupt Status Register (ISR).
InstancePtr is a pointer to the XSysMonPsu instance. Mask is the 64 bit-mask of the interrupts to be cleared. Bit positions of 1 will be cleared. Bit positions of 0 will not change the previous interrupt status. This mask is formed by OR'ing the XSYSMONPSU_ISR_0_* and XSYSMONPSU_ISR_1_* bits which are defined in xsysmonpsu_hw.h. None. None.
References XSysMonPsu_Config::BaseAddress, XSysMonPsu::Config, XSysMonPsu::IsReady, XSYSMONPSU_ISR_0_OFFSET, XSYSMONPSU_ISR_1_OFFSET.
Referenced by SysMonPsuAMSExample, SysMonPsuIntrExample, SysMonPsuPolledPrintfExample, SysMonPsuSingleChannelIntrExample, XSysMonPsu_CfgInitialize.
s32 XSysMonPsu_SelfTest(XSysMonPsu *InstancePtr)
Run a self-test on the driver/device.
The test Resets the device,Writes a value into the Alarm Threshold register and reads it back for comparison.Resets the device again. InstancePtr is a pointer to the XSysMonPsu instance. XST_SUCCESS if the value read from the Alarm Threshold register is the same as the value written.XST_FAILURE Otherwise This is a destructive test in that resets of the device are performed. Refer to the device specification for the device status after the reset operation.
References XSysMonPsu::IsReady, XSM_ATR_SUP1_UPPER, XSysMonPsu_GetAlarmThreshold, XSysMonPsu_Reset, XSysMonPsu_SetAlarmThreshold.
Referenced by SysMonPsuAMSExample, SysMonPsuIntrExample, SysMonPsuPolledPrintfExample, SysMonPsuSingleChannelIntrExample.
XSysMonPsu_Config* XSysMonPsu_LookupConfig(u32 BaseAddress)
This function looks for the device configuration based on the unique device ID.
The table XSysmonPsu_ConfigTable[] contains the configuration information for each device in the system. DeviceId is the unique device ID of the device being looked up. A pointer to the configuration table entry corresponding to the given device ID, or NULL if no match is found. None.
Referenced by SysMonPsuAMSExample, SysMonPsuIntrExample, SysMonPsuPolledPrintfExample, SysMonPsuSingleChannelIntrExample.