xsysmonpsu_sinit.c
XSysMonPsu_Config XSysMonPsu_ConfigTable[][]
This table contains configuration information for SYSMON device in the system.
XSysMonPsu_Config* XSysMonPsu_LookupConfig(u32 BaseAddress)
This function looks for the device configuration based on the unique device ID.
The table XSysmonPsu_ConfigTable[] contains the configuration information for each device in the system. DeviceId is the unique device ID of the device being looked up. A pointer to the configuration table entry corresponding to the given device ID, or NULL if no match is found. None.
Referenced by SysMonPsuAMSExample, SysMonPsuIntrExample, SysMonPsuPolledPrintfExample, SysMonPsuSingleChannelIntrExample.