core/rsa/xsecure_rsa_core.c
XSECURE_TIMEOUT_MAX
Recommended software timeout.
Referenced by XSecure_RsaOperation.
SIZEOF_INT_IN_BYTES
Size of integer om bytes.
const u8 XSecure_Silicon2_TPadSha3[][]
static void XSecure_RsaPutData(const XSecure_Rsa *InstancePtr)
This function writes all the RSA data used for decryption (Modulus, Exponent) at the corresponding offsets in RSA RAM.
InstancePtr Pointer to the XSecure_Rsa instance
static void XSecure_RsaWriteMem(const XSecure_Rsa *InstancePtr, u64 WrDataAddr, u8 RamOffset)
This function writes data to RSA RAM at a given offset.
InstancePtr Pointer to the XSecure_Aes instance WrDataAddr Address of the data to be written to RSA RAM RamOffset Offset for the data to be written in RSA RAM
static void XSecure_RsaMod32Inverse(const XSecure_Rsa *InstancePtr)
This function calculates the MINV value and put it into RSA core registers.
InstancePtr Pointer to XSeure_Rsa instance MINV is the 32-bit value of -M mod 2**32, where M is LSB 32 bits of the original modulus
static void XSecure_RsaGetData(const XSecure_Rsa *InstancePtr, u64 RdDataAddr)
This function reads back the resulting data from RSA RAM.
InstancePtr Pointer to the XSecure_Rsa instance RdDataAddr Address of the location where RSA output data will be written
static void XSecure_RsaDataLenCfg(const XSecure_Rsa *InstancePtr, u32 Cfg0, u32 Cfg1, u32 Cfg2, u32 Cfg5)
This function updates data length configuration.
InstancePtr Pointer to the XSecure_Rsa instance. Cfg0 QSEL, Multiplication passes. Cfg1 Number of Montgomery digits. Cfg2 Memory location size. Cfg5 Number of groups.
u32 XSecure_RsaCfgInitialize(XSecure_Rsa *InstancePtr)
This function stores the base address of RSA core registers.
InstancePtr Pointer to the XSecure_Rsa instance XST_SUCCESS - On successXSECURE_RSA_INVALID_PARAM - On invalid parameter
References XSecure_Rsa::BaseAddress, XSECURE_CORE_RSA_ECC, XSecure_CryptoCheck, XSECURE_ECDSA_RSA_BASEADDR, XSECURE_RSA_INVALID_PARAM.
Referenced by XSecure_RsaInitialize_64Bit.
int XSecure_RsaOperation(XSecure_Rsa *InstancePtr, u64 Input, u64 Result, XSecure_RsaOps RsaOp, u32 KeySize)
This function handles the Public encryption and private decryption of RSA operations with provided inputs.
InstancePtr Pointer to the XSecure_Rsa instance Input Address of the buffer which contains the input data to be encrypted/decrypted Result Address of buffer where resultant encrypted/decrypted data to be stored RsaOp Flag to inform the operation to be performed is either encryption/decryption KeySize Size of the key in bytes XST_SUCCESS - On successXSECURE_RSA_INVALID_PARAM - On invalid parameterXST_FAILURE - On failure
References XSecure_Rsa::BaseAddress, XSecure_Rsa::EncDec, XSecure_Rsa::ModExpoAddr, XSecure_Rsa::ModExtAddr, XSecure_Rsa::SizeInWords, XSECURE_ECDSA_RSA_CFG0_2048_VALUE, XSECURE_ECDSA_RSA_CFG0_3072_VALUE, XSECURE_ECDSA_RSA_CFG0_4096_VALUE, XSECURE_ECDSA_RSA_CFG1_2048_VALUE, XSECURE_ECDSA_RSA_CFG1_3072_VALUE, XSECURE_ECDSA_RSA_CFG1_4096_VALUE, XSECURE_ECDSA_RSA_CFG2_2048_VALUE, XSECURE_ECDSA_RSA_CFG2_3072_VALUE, XSECURE_ECDSA_RSA_CFG2_4096_VALUE, XSECURE_ECDSA_RSA_CFG5_2048_VALUE, XSECURE_ECDSA_RSA_CFG5_3072_VALUE, XSECURE_ECDSA_RSA_CFG5_4096_VALUE, XSECURE_ECDSA_RSA_CFG_OFFSET, XSECURE_ECDSA_RSA_CTRL_OFFSET, XSECURE_ECDSA_RSA_KEY_LEN_OFFSET, XSECURE_ECDSA_RSA_RESET_OFFSET, XSECURE_ECDSA_RSA_STATUS_OFFSET, XSecure_ReleaseReset, XSECURE_RSA_2048_KEY_SIZE, XSECURE_RSA_2048_SIZE_WORDS, XSECURE_RSA_3072_KEY_SIZE, XSECURE_RSA_3072_SIZE_WORDS, XSECURE_RSA_4096_KEY_SIZE, XSECURE_RSA_4096_SIZE_WORDS, XSECURE_RSA_CONTROL_EXP, XSECURE_RSA_CONTROL_EXP_PRE, XSECURE_RSA_INVALID_PARAM, XSECURE_RSA_PUBLIC_EXPO_SIZE, XSECURE_RSA_RAM_DIGEST, XSECURE_RSA_SIGN_DEC, XSECURE_RSA_SIGN_ENC, XSECURE_RSA_STATUS_DONE, XSECURE_RSA_STATUS_ERROR, XSecure_RsaZeroize, XSecure_SetReset, XSECURE_TIMEOUT_MAX, XSECURE_WORD_IN_BITS, XSECURE_WORD_SIZE.
Referenced by XSecure_RsaPrivateDecrypt_64Bit, XSecure_RsaPublicEncrypt_64Bit.
int XSecure_RsaZeroize(const XSecure_Rsa *InstancePtr)
This function clears whole RSA memory space.
This function clears stored exponent, modulus and exponentiation key components along with digest InstancePtr Pointer to the XSecure_Rsa instance XST_SUCCESS - On SuccessXSECURE_RSA_INVALID_PARAM - On invalid parameter
References XSecure_Rsa::BaseAddress, XSECURE_ECDSA_RSA_MINV_OFFSET, XSECURE_RSA_INVALID_PARAM, XSecure_RsaEcdsaZeroizeAndVerifyRam.
Referenced by XSecure_RsaOperation.
u8 * XSecure_RsaGetTPadding(void)
This function returns PKCS padding as per the silicon version.
XSecure_Silicon2_TPadSha3
Referenced by XSecure_RsaSignVerification_64Bit.
static int XSecure_RsaEcdsaZeroizeVerify(u32 BaseAddress)
This function verifies whole RSA or ECDSA memory space.
BaseAddress BaseAddress of RSA or ECDSA controller. XST_SUCCESS - On SuccessXST_FAILURE - On Failure
int XSecure_RsaEcdsaZeroizeAndVerifyRam(u32 BaseAddress)
This function clears and verifies whole RSA or ECDSA memory space.
BaseAddress BaseAddress of ECDSA or RSA controller. XST_SUCCESS - On SuccessXST_FAILURE - On Failure
References XSECURE_ECDSA_RSA_CTRL_OFFSET, XSECURE_ECDSA_RSA_RAM_ADDR_OFFSET, XSECURE_RSA_MAX_RD_WR_CNT, XSECURE_RSA_RAM_RES_Q.
Referenced by XSecure_RsaZeroize.