core/generic/xsecure_cryptochk.h
XSECURE_EFUSE_CACHE_IP_DISABLE0
< IP_DISABLE_0 register address and definitions
Referenced by XSecure_CryptoCheck.
XSECURE_EFUSE_CACHE_IP_DISABLE0_EXPORT_MASK
XSECURE_CFU_APB_CFU_FGCR
< CFU_FGCR register address and definitions
Referenced by XSecure_CryptoCheck.
XSECURE_CFU_APB_CFU_FGCR_EOS_MASK
XSECURE_CRP_RST_PS
< RST_PS register address and definitions
Referenced by XSecure_CryptoCheck.
XSECURE_CRP_RST_PS_PS_SRST_MASK
XSecure_CoreSrc
AES Core.
int XSecure_CryptoCheck(XSecure_CoreSrc CoreSrc)
This function checks if the EXPORT control eFuse is programmed and PL loading is done.
CoreSrc Crypto core source (AES, SHA, RSA) XST_SUCCESS - When crypto accelerators are enabledXSECURE_ERR_CRYPTO_ACCELERATOR_DISABLED - When crypto accelerators are disabled
References XSECURE_CFU_APB_CFU_FGCR, XSECURE_CRP_RST_PS, XSECURE_EFUSE_CACHE_IP_DISABLE0, XSECURE_ERR_CRYPTO_ACCELERATOR_DISABLED, XSecure_In32.
Referenced by XSecure_AesInitialize, XSecure_EcdhGetSecret, XSecure_EllipticGenerateKey_64Bit, XSecure_EllipticGenerateSignature_64Bit, XSecure_EllipticValidateKey_64Bit, XSecure_EllipticVerifySign_64Bit, XSecure_RsaCfgInitialize, XSecure_Sha3Start.