core/sha/sha_pmxc/xsecure_sha.h
int XSecure_ShaInitialize(XSecure_Sha *const InstancePtr, XPmcDma *DmaPtr)
This function initializes SHA instance so that it is ready to be used.
InstancePtr - Pointer to the SHA instance. DmaPtr - Pointer to the DMA instance. XST_SUCCESS - Upon Success.XST_FAILURE - Upon Failure.XSECURE_SHA_INVALID_PARAM_ERRORXSECURE_SHA_SSS_INIT_ERROR
References XSECURE_SHA_INVALID_PARAM.
int XSecure_ShaStart(XSecure_Sha *const InstancePtr, XSecure_ShaMode ShaMode)
This function validates the SHA Mode (refer XSecure_ShaMode enum) and configures SSS and start the SHA engine.
InstancePtr - Pointer to the SHA instance. ShaMode - Indicates SHA3/SHA2 shall be operated in which sha mode that is SHA-384/256/512 XST_SUCCESS - Upon Success.XSECURE_SHA_INVALID_PARAM - Invalid parameter (InstancePtr is NULL or invalid SHA mode)XSECURE_SHA_STATE_MISMATCH_ERROR - SHA engine is not in initialized stateXST_FAILURE - On crypto check failure
int XSecure_ShaUpdate(XSecure_Sha *const InstancePtr, u64 DataAddr, const u32 DataSize)
This function updates input data to SHA Engine to calculate Hash.
InstancePtr Pointer to the SHA instance. DataAddr Pointer to the input data for hashing. DataSize Size of the input data in bytes. XST_SUCCESS - Upon Success.XST_FAILURE - Upon Failure.XSECURE_SHA_INVALID_PARAM_ERRORXSECURE_SHA_NOT_STARTED_ERROR
References XSECURE_SHA_INVALID_PARAM.
int XSecure_ShaFinish(XSecure_Sha *const InstancePtr, u64 HashAddr, u32 HashBufSize)
This function calculates and reads the final hash of input data.
InstancePtr - Pointer to the SHA instance. HashAddr - Pointer which holds final hash. HashBufSize - Size allocated for Hash Buffer XST_SUCCESS - Upon Success.XST_FAILURE - Upon Failure.XSECURE_SHA_INVALID_PARAM_ERROR - Upon invalid input parameterXSECURE_SHA_STATE_MISMATCH_ERROR - Upon sha state mismatch
References XSECURE_SHA_INVALID_PARAM.
int XSecure_ShaDigest(XSecure_Sha *const InstancePtr, XSecure_ShaMode ShaMode, u64 DataAddr, u32 DataSize, u64 HashAddr, u32 HashBufSize)
This function calculates the SHA2/3 digest on the given input data.
InstancePtr Pointer to the SHA instance. ShaMode Indicates SHA3/SHA2 shall be operated in which sha mode that is SHA-384/256/512 DataAddr Pointer to the input data for hashing. DataSize Size of the input data in bytes. HashAddr Pointer which holds final hash. HashBufSize Size allocated for Hash Buffer XST_SUCCESS - Upon Success.XST_FAILURE - Upon Failure.XSECURE_SHA_INVALID_PARAM_ERRORXSECURE_SHA_NOT_INITIALIZED_ERROR
References XSECURE_SHA_INITIALIZED, XSECURE_SHA_INVALID_PARAM, XSECURE_SHA_STATE_MISMATCH_ERROR, XSecure_ShaFinish, XSecure_ShaLastUpdate, XSecure_ShaStart, XSecure_ShaUpdate, XSecure_ShaValidateModeAndCfgInstance.
int XSecure_ShaLastUpdate(XSecure_Sha *InstancePtr)
This function notifies the SHA driver at the end of the SHA data update.
Typically called before last XSecure_ShaUpdate. InstancePtr Pointer to the XSecure_Sha instance XST_SUCCESS - If last update can be acceptedXSECURE_SHA_INVALID_PARAM - On invalid parameterXSECURE_SHA_STATE_MISMATCH_ERROR - If State mismatch is occurred
References XSECURE_SHA_INVALID_PARAM.
int XSecure_ShaValidateModeAndCfgInstance(XSecure_Sha *const InstancePtr, XSecure_ShaMode ShaMode)
This function validates the SHA Mode and initialize SHA instance.
InstancePtr Pointer to the SHA instance. ShaMode SHA Mode XST_SUCCESS - Upon successXSECURE_SHA_INVALID_PARAM - Invalid SHA mode provided InstancePtr Pointer to the SHA instance. ShaMode SHA Mode. XST_SUCCESS Upon Success.XST_FAILURE Upon Failure.XSECURE_SHA_INVALID_MODE_ERROR In case of invalid sha mode config. InstancePtr Pointer to the SHA instance. ShaMode SHA Mode. XST_SUCCESS - Upon Success. XST_FAILURE - Upon Failure. XSECURE_SHA_INVALID_MODE_ERROR InstancePtr Pointer to the SHA instance. ShaMode SHA Mode XST_SUCCESS - Upon successXSECURE_SHA_INVALID_PARAM - Invalid SHA mode provided InstancePtr Pointer to the SHA instance. ShaMode SHA Mode. XST_SUCCESS Upon Success.XST_FAILURE Upon Failure.XSECURE_SHA_INVALID_MODE_ERROR In case of invalid sha mode config.
References XSECURE_SHA3_256, XSecure_ShaPlatConfig::ShaDigestSize, XSECURE_SHA3_256_HASH_LEN, XSecure_ShaPlatConfig::ShaMode, SHA256, XSECURE_SHAKE_256, XSECURE_SHAKE_256_HASH_LEN, SHAKE256, XSECURE_SHA3_384, XSECURE_SHA3_384_HASH_LEN, SHA384, XSECURE_SHA_INVALID_PARAM, XSECURE_SHA2_256_HASH_LEN, XSECURE_SHA2_384_HASH_LEN, XSECURE_SHA_512_HASH_LEN, SHA512.
Referenced by XSecure_ShaDigest.
int XSecure_ExtendedShaFinish(XSecure_Sha *const InstancePtr, u64 HashAddr, u32 HashBufSize, u32 ReqHashSize)
This function calculates and reads the final hash of input data with support for variable-length hash output.
InstancePtr Pointer to the SHA instance. HashAddr Pointer to the buffer where the final hash will be stored. HashBufSize Size allocated for the hash buffer in bytes. Must be at least as large as ReqHashSize to avoid buffer overflow. ReqHashSize Requested hash size in bytes to be read from the SHA digest. Must not exceed XSECURE_MAX_HASH_SIZE_IN_BYTES. XST_SUCCESS - Upon successful hash calculation and retrieval.XST_FAILURE - Upon failure during hash completion or digest read.XSECURE_SHA_INVALID_PARAM - When InstancePtr is NULL or HashBufSize is less than ReqHashSize.XSECURE_SHA_STATE_MISMATCH_ERROR - When SHA engine is in initialized state without any update.XSECURE_SHA_NIST_PADDING_ERROR - When NIST padding operation fails.XSECURE_SHA_MAX_HASH_SIZE_EXCEED_ERROR - When ReqHashSize exceeds XSECURE_MAX_HASH_SIZE_IN_BYTES.
References XSecure_ShaPlatConfig::AutoPaddingOffset, SHAKE256, SHAKE256_SLH_DSA_CHAIN, XSecure_ShaPlatConfig::ShaMode, XSECURE_MAX_HASH_SIZE_IN_BYTES, XSecure_SetReset, XSECURE_SHA_INITIALIZED, XSECURE_SHA_INVALID_PARAM, XSECURE_SHA_MAX_HASH_SIZE_EXCEED_ERROR, XSECURE_SHA_NIST_PADDING_ERROR, XSECURE_SHA_RESET_OFFSET, XSECURE_SHA_STATE_MISMATCH_ERROR, XSECURE_WORD_SIZE.
Referenced by XSecure_SlhdsaShake256sHashMsg.
u32 XSecure_ShaGetBlockLen(XSecure_ShaMode HashAlgo)
This function returns the block length for the given SHA algorithm.
HashAlgo SHA algorithm mode. Block length in bytes, or 0 for invalid algorithm.
References XSECURE_SHA2_256_BLOCK_LEN, XSECURE_SHA2_384_512_BLOCK_LEN, XSECURE_SHA3_256, XSECURE_SHA3_384, XSECURE_SHA3_384_BLOCK_LEN, XSECURE_SHA3_512_BLOCK_LEN, XSECURE_SHAKE_256, XSECURE_SHAKE_SHA3_256_BLOCK_LEN.
Referenced by XSecure_ShaDmaXfer.