core/rsa/xsecure_rsa_core.h
XSECURE_RSA_CONTROL_EXP
Exponentiation Opcode.
Referenced by XSecure_RsaOperation.
XSECURE_RSA_CONTROL_EXP_PRE
Expo.
using R*R mod M
Referenced by XSecure_RsaOperation.
XSECURE_ECDSA_RSA_CFG0_4096_VALUE
CFG0 4096 value.
Referenced by XSecure_RsaOperation.
XSECURE_ECDSA_RSA_CFG1_4096_VALUE
CFG1 4096 value.
Referenced by XSecure_RsaOperation.
XSECURE_ECDSA_RSA_CFG2_4096_VALUE
CFG2 4096 value.
Referenced by XSecure_RsaOperation.
XSECURE_ECDSA_RSA_CFG5_4096_VALUE
CFG3 4096 value.
Referenced by XSecure_RsaOperation.
XSECURE_ECDSA_RSA_CFG0_3072_VALUE
CFG0 3072 value.
Referenced by XSecure_RsaOperation.
XSECURE_ECDSA_RSA_CFG1_3072_VALUE
CFG1 3072 value.
Referenced by XSecure_RsaOperation.
XSECURE_ECDSA_RSA_CFG2_3072_VALUE
CFG2 3072 value.
Referenced by XSecure_RsaOperation.
XSECURE_ECDSA_RSA_CFG5_3072_VALUE
CFG3 3072 value.
Referenced by XSecure_RsaOperation.
XSECURE_ECDSA_RSA_CFG0_2048_VALUE
CFG0 2048 value.
Referenced by XSecure_RsaOperation.
XSECURE_ECDSA_RSA_CFG1_2048_VALUE
CFG1 2048 value.
Referenced by XSecure_RsaOperation.
XSECURE_ECDSA_RSA_CFG2_2048_VALUE
CFG2 2048 value.
Referenced by XSecure_RsaOperation.
XSECURE_ECDSA_RSA_CFG5_2048_VALUE
CFG3 2048 value.
Referenced by XSecure_RsaOperation.
XSECURE_RSA_STATUS_DONE
Operation Done.
Referenced by XSecure_RsaOperation.
XSECURE_RSA_STATUS_ERROR
Error.
Referenced by XSecure_RsaOperation.
XSECURE_RSA_ECDSA_ZEROIZE_ERROR
for RSA zeroization Error
XSECURE_RSA_MAX_BUFF
RSA RAM Write Buffers.
XSECURE_RSA_MAX_RD_WR_CNT
No of writes or reads to RSA RAM buffers.
Referenced by XSecure_RsaEcdsaZeroizeAndVerifyRam.
XSECURE_RSA_RAM_RES_Q
bit for RSA RAM Result(Q)
Referenced by XSecure_RsaEcdsaZeroizeAndVerifyRam.
XSECURE_RSA_DATA_VALUE_ERROR
for RSA private decryption data should be lesser than modulus
Referenced by XSecure_RsaPrivateDecrypt_64Bit.
XSECURE_HASH_TYPE_SHA3
SHA-3 hash size.
Referenced by XSecure_DataAuth, XSecure_PpkVerify, XSecure_RsaSignVerification_64Bit, XSecure_SpkAuthentication.
XSECURE_FSBL_SIG_SIZE
FSBL signature size.
Referenced by XSecure_RsaSignVerification_64Bit.
XSECURE_RSA_PUBLIC_EXPO_SIZE
Size of public key expo.
Referenced by XSecure_RsaOperation.
XSECURE_RSA_2048_KEY_SIZE
RSA 2048 key size.
Referenced by XSecure_RsaOperation, XSecure_RsaPrivateDecryptKat, XSecure_RsaPublicEncryptKat.
XSECURE_RSA_3072_KEY_SIZE
RSA 3072 key size.
Referenced by XSecure_RsaOperation.
XSECURE_RSA_4096_KEY_SIZE
RSA 4096 key size.
Referenced by XSecure_RsaOperation.
XSECURE_RSA_2048_SIZE_WORDS
RSA 2048 Size in words.
Referenced by XSecure_GetKatRsaPrivateExp, XSecure_RsaOperation, XSecure_RsaPrivateDecryptKat, XSecure_RsaPublicEncryptKat.
XSECURE_RSA_3072_SIZE_WORDS
RSA 3072 Size in words.
Referenced by XSecure_RsaOperation.
XSECURE_RSA_4096_SIZE_WORDS
RSA 4096 Size in words.
Referenced by XSecure_RsaInitialize_64Bit, XSecure_RsaOperation.
XSECURE_RSA_RAM_EXPO
bit for RSA RAM Exponent
XSECURE_RSA_RAM_MOD
bit for RSA RAM modulus
XSECURE_RSA_RAM_DIGEST
bit for RSA RAM Digest
Referenced by XSecure_RsaOperation.
XSECURE_RSA_RAM_RES_Y
bit for RSA RAM Result(Y)
XSecure_RsaState
0x0
XSecure_RsaOps
0x0
u32 XSecure_RsaCfgInitialize(XSecure_Rsa *InstancePtr)
This function stores the base address of RSA core registers.
InstancePtr Pointer to the XSecure_Rsa instance XST_SUCCESS - On successXSECURE_RSA_INVALID_PARAM - On invalid parameter
References XSecure_Rsa::BaseAddress, XSECURE_CORE_RSA_ECC, XSecure_CryptoCheck, XSECURE_ECDSA_RSA_BASEADDR, XSECURE_RSA_INVALID_PARAM.
Referenced by XSecure_RsaInitialize_64Bit.
int XSecure_RsaOperation(XSecure_Rsa *InstancePtr, u64 Input, u64 Result, XSecure_RsaOps RsaOp, u32 KeySize)
This function handles the Public encryption and private decryption of RSA operations with provided inputs.
InstancePtr Pointer to the XSecure_Rsa instance Input Address of the buffer which contains the input data to be encrypted/decrypted Result Address of buffer where resultant encrypted/decrypted data to be stored RsaOp Flag to inform the operation to be performed is either encryption/decryption KeySize Size of the key in bytes XST_SUCCESS - On successXSECURE_RSA_INVALID_PARAM - On invalid parameterXST_FAILURE - On failure
References XSecure_Rsa::BaseAddress, XSecure_Rsa::EncDec, XSecure_Rsa::ModExpoAddr, XSecure_Rsa::ModExtAddr, XSecure_Rsa::SizeInWords, XSECURE_ECDSA_RSA_CFG0_2048_VALUE, XSECURE_ECDSA_RSA_CFG0_3072_VALUE, XSECURE_ECDSA_RSA_CFG0_4096_VALUE, XSECURE_ECDSA_RSA_CFG1_2048_VALUE, XSECURE_ECDSA_RSA_CFG1_3072_VALUE, XSECURE_ECDSA_RSA_CFG1_4096_VALUE, XSECURE_ECDSA_RSA_CFG2_2048_VALUE, XSECURE_ECDSA_RSA_CFG2_3072_VALUE, XSECURE_ECDSA_RSA_CFG2_4096_VALUE, XSECURE_ECDSA_RSA_CFG5_2048_VALUE, XSECURE_ECDSA_RSA_CFG5_3072_VALUE, XSECURE_ECDSA_RSA_CFG5_4096_VALUE, XSECURE_ECDSA_RSA_CFG_OFFSET, XSECURE_ECDSA_RSA_CTRL_OFFSET, XSECURE_ECDSA_RSA_KEY_LEN_OFFSET, XSECURE_ECDSA_RSA_RESET_OFFSET, XSECURE_ECDSA_RSA_STATUS_OFFSET, XSecure_ReleaseReset, XSECURE_RSA_2048_KEY_SIZE, XSECURE_RSA_2048_SIZE_WORDS, XSECURE_RSA_3072_KEY_SIZE, XSECURE_RSA_3072_SIZE_WORDS, XSECURE_RSA_4096_KEY_SIZE, XSECURE_RSA_4096_SIZE_WORDS, XSECURE_RSA_CONTROL_EXP, XSECURE_RSA_CONTROL_EXP_PRE, XSECURE_RSA_INVALID_PARAM, XSECURE_RSA_PUBLIC_EXPO_SIZE, XSECURE_RSA_RAM_DIGEST, XSECURE_RSA_SIGN_DEC, XSECURE_RSA_SIGN_ENC, XSECURE_RSA_STATUS_DONE, XSECURE_RSA_STATUS_ERROR, XSecure_RsaZeroize, XSecure_SetReset, XSECURE_TIMEOUT_MAX, XSECURE_WORD_IN_BITS, XSECURE_WORD_SIZE.
Referenced by XSecure_RsaPrivateDecrypt_64Bit, XSecure_RsaPublicEncrypt_64Bit.
u8 * XSecure_RsaGetTPadding(void)
This function returns PKCS padding as per the silicon version.
XSecure_Silicon2_TPadSha3
Referenced by XSecure_RsaSignVerification_64Bit.
int XSecure_RsaZeroize(const XSecure_Rsa *InstancePtr)
This function clears whole RSA memory space.
This function clears stored exponent, modulus and exponentiation key components along with digest InstancePtr Pointer to the XSecure_Rsa instance XST_SUCCESS - On SuccessXSECURE_RSA_INVALID_PARAM - On invalid parameter
References XSecure_Rsa::BaseAddress, XSECURE_ECDSA_RSA_MINV_OFFSET, XSECURE_RSA_INVALID_PARAM, XSecure_RsaEcdsaZeroizeAndVerifyRam.
Referenced by XSecure_RsaOperation.
int XSecure_RsaEcdsaZeroizeAndVerifyRam(u32 BaseAddress)
This function clears and verifies whole RSA or ECDSA memory space.
BaseAddress BaseAddress of ECDSA or RSA controller. XST_SUCCESS - On SuccessXST_FAILURE - On Failure
References XSECURE_ECDSA_RSA_CTRL_OFFSET, XSECURE_ECDSA_RSA_RAM_ADDR_OFFSET, XSECURE_RSA_MAX_RD_WR_CNT, XSECURE_RSA_RAM_RES_Q.
Referenced by XSecure_RsaZeroize.