core/util/xsecure_utils.c
void XSecure_ReleaseReset(UINTPTR BaseAddress, u32 Offset)
This function takes the hardware core out of reset.
BaseAddress Base address of the core Offset Offset of the reset register
References XSECURE_RESET_SET, XSECURE_RESET_UNSET, XSECURE_SET_BIT.
Referenced by XSecure_AesReset, XSecure_EcdhGetSecret, XSecure_EllipticGenerateEphemeralKey, XSecure_EllipticGenerateKey_64Bit, XSecure_EllipticGenerateSignature_64Bit, XSecure_EllipticPrvtKeyGenerate, XSecure_EllipticValidateKey_64Bit, XSecure_EllipticVerifySign_64Bit, XSecure_MldsaSignGenerate, XSecure_MldsaSignVerify, XSecure_RsaOperation, XSecure_Sha3Start.
void XSecure_SetReset(UINTPTR BaseAddress, u32 Offset)
This function places the hardware core into the reset.
BaseAddress Base address of the core Offset Offset of the reset register
References XSECURE_CLEAR_BIT, XSECURE_RESET_SET.
Referenced by XSecure_AesDecrypt, XSecure_AesDecryptInit, XSecure_AesDecryptUpdate, XSecure_AesEcbDecrypt, XSecure_AesEncryptInit, XSecure_AesEncryptUpdate, XSecure_AesKeyUnwrap, XSecure_EcdhGetSecret, XSecure_EllipticGenerateEphemeralKey, XSecure_EllipticGenerateKey_64Bit, XSecure_EllipticGenerateSignature_64Bit, XSecure_EllipticPrvtKeyGenerate, XSecure_EllipticValidateKey_64Bit, XSecure_EllipticVerifySign_64Bit, XSecure_ExtendedShaFinish, XSecure_HmacFinal, XSecure_HmacInit, XSecure_HmacUpdate, XSecure_MldsaSignGenerate, XSecure_MldsaSignVerify, XSecure_RsaOperation, XSecure_SetDataContextLost, XSecure_Sha2256Kat, XSecure_Sha3Finish, XSecure_Sha3Kat, XSecure_Sha3Update, XSecure_Sha3Update64Bit, XSecure_ShakeKat.