core/generic/xsecure_cryptochk.c
int XSecure_CryptoCheck(XSecure_CoreSrc CoreSrc)
This function checks if the EXPORT control eFuse is programmed and PL loading is done.
CoreSrc Crypto core source (AES, SHA, RSA) XST_SUCCESS - When crypto accelerators are enabledXSECURE_ERR_CRYPTO_ACCELERATOR_DISABLED - When crypto accelerators are disabled
References XSECURE_CFU_APB_CFU_FGCR, XSECURE_CRP_RST_PS, XSECURE_EFUSE_CACHE_IP_DISABLE0, XSECURE_ERR_CRYPTO_ACCELERATOR_DISABLED, XSecure_In32.
Referenced by XSecure_AesInitialize, XSecure_EcdhGetSecret, XSecure_EllipticGenerateKey_64Bit, XSecure_EllipticGenerateSignature_64Bit, XSecure_EllipticValidateKey_64Bit, XSecure_EllipticVerifySign_64Bit, XSecure_RsaCfgInitialize, XSecure_Sha3Start.