core/util/xsecure_utils.h
XSecure_AssertVoid
< All asserts are under XSECDEBUG macro now
Referenced by XSecure_AesPmcDmaCfgEndianness.
XSecure_AssertNonvoid
XSECURE_RESET_SET
To set the core into reset.
Referenced by XSecure_ReleaseReset, XSecure_SetReset.
XSECURE_RESET_UNSET
To take the core out of reset.
Referenced by XSecure_ReleaseReset.
XSECURE_WORD_SIZE
WORD size in BYTES.
Referenced by XSecure_AesPlatPmcDmaCfgAndXfer, XSecure_AesValidateSize, XSecure_ExtendedShaFinish, XSecure_Hkdf, XSecure_MaskGenFunc, XSecure_MldsaSignGenerate, XSecure_MldsaSignVerify, XSecure_RsaOperation, XSecure_Sha3ReadHash, XSecure_ShaDmaXfer.
XSECURE_QWORD_SIZE
QWORD size in BYTES.
Referenced by XSecure_AesValidateSize.
XSECURE_WORD_IN_BITS
WORD size in BITS.
Referenced by XSecure_RsaOperation.
XSECURE_BYTE_IN_BITS
Byte size in BITS.
Referenced by XSecure_MldsaSignGenerate, XSecure_MldsaSignVerify, XSecure_RsaOaepDecrypt, XSecure_SlhdsaBase2b.
XSECURE_WORD_ALIGN_MASK
WORD alignment.
Referenced by XSecure_MemCpy64, XSecure_ShaDmaXfer.
XSECURE_SET_BIT
To set bit.
Referenced by XSecure_ReleaseReset.
XSECURE_CLEAR_BIT
To clear bit.
Referenced by XSecure_EllipticPrvtKeyGenerate, XSecure_SetReset.
XSECURE_VALUE_ONE
Integer value 1U.
Referenced by XSecure_MldsaSignGenerate, XSecure_MldsaSignVerify, XSecure_SlhdsaBase2b, XSecure_SlhdsaForsPkFromSig, XSecure_SlhdsaHtVerify, XSecure_SlhdsaXmssPkFromSign.
XSECURE_VALUE_TWO
Integer value 2U.
Referenced by XSecure_MldsaSignGenerate, XSecure_MldsaSignVerify, XSecure_SlhdsaShake256sHashMsg, XSecure_SlhdsaVerify.
XSECURE_VALUE_THREE
Integer value 3U.
XSECURE_ALLFS
To assign invalid value.
XSECURE_ZERO
To assign/compare to zero.
Referenced by XSecure_MldsaSignVerify, XSecure_RsaDestroyKeyInUse, XSecure_SlhdsaBase2b, XSecure_SlhdsaForsPkFromSig, XSecure_SlhdsaShake256sChain, XSecure_SlhdsaShake256sHashMsg, XSecure_SlhdsaWotsPkFromSign.
XSecure_MemCpy
Backward compatibility.
XSecure_MemCpy64
Backward compatibility.
XSecure_In32
Reads data from 32-bit address.
Referenced by SecureAesExample, XSecure_CryptoCheck, XSecure_InitiateASUKeyTransfer, XSecure_MldsaSignGenerate.
XSecure_Out32
Writes data to 32-bit address.
Referenced by XSecure_AesDecrypt, XSecure_AesDecryptInit, XSecure_AesEncryptInit, XSecure_InitiateASUKeyTransfer, XSecure_MldsaSignGenerate, XSecure_MldsaSignVerify, XSecure_RsaExp, XSecure_RsaExpCRT, XSecure_RsaExpopt.
XSecure_SecureOut32
Writes data to 32-bit address and checks for blind writes.
Referenced by XSecure_SssAes, XSecure_SssSha.
static u32 XSecure_ReadReg(UINTPTR BaseAddress, u16 RegOffset)
Read from the register.
BaseAddress Contains the base address of the device RegOffset Contains the offset from the base address of the device The value read from the register
static void XSecure_WriteReg(UINTPTR BaseAddress, u32 RegOffset, u32 RegisterValue)
Write to the register.
BaseAddress Contains the base address of the device RegOffset Contains the offset from the base address of the device RegisterValue Is the value to be written to the register
static u32 XSecure_In64(u64 Addr)
This function reads data from 64-bit address.
Addr is the address The value read from the provided address
static u8 XSecure_InByte64(u64 Addr)
This function reads a byte from 64-bit address.
Addr is the address The value read from the provided address
static void XSecure_Out64(u64 Addr, u32 Data)
This function writes data to 64-bit address.
Addr is the address Data is the value to be written
static void XSecure_OutWord64(u64 Addr, u32 Data)
This function writes 32 bit data to 64-bit address.
Addr is the address Data is the value to be written
static void XSecure_OutByte64(u64 Addr, u8 Data)
This function writes a byte to a 64-bit address.
Addr is the address Data is the value to be written
void XSecure_SetReset(UINTPTR BaseAddress, u32 Offset)
This function places the hardware core into the reset.
BaseAddress Base address of the core Offset Offset of the reset register
References XSECURE_CLEAR_BIT, XSECURE_RESET_SET.
Referenced by XSecure_AesDecrypt, XSecure_AesDecryptInit, XSecure_AesDecryptUpdate, XSecure_AesEcbDecrypt, XSecure_AesEncryptInit, XSecure_AesEncryptUpdate, XSecure_AesKeyUnwrap, XSecure_EcdhGetSecret, XSecure_EllipticGenerateEphemeralKey, XSecure_EllipticGenerateKey_64Bit, XSecure_EllipticGenerateSignature_64Bit, XSecure_EllipticPrvtKeyGenerate, XSecure_EllipticValidateKey_64Bit, XSecure_EllipticVerifySign_64Bit, XSecure_ExtendedShaFinish, XSecure_HmacFinal, XSecure_HmacInit, XSecure_HmacUpdate, XSecure_MldsaSignGenerate, XSecure_MldsaSignVerify, XSecure_RsaOperation, XSecure_SetDataContextLost, XSecure_Sha2256Kat, XSecure_Sha3Finish, XSecure_Sha3Kat, XSecure_Sha3Update, XSecure_Sha3Update64Bit, XSecure_ShakeKat.
void XSecure_ReleaseReset(UINTPTR BaseAddress, u32 Offset)
This function takes the hardware core out of reset.
BaseAddress Base address of the core Offset Offset of the reset register
References XSECURE_RESET_SET, XSECURE_RESET_UNSET, XSECURE_SET_BIT.
Referenced by XSecure_AesReset, XSecure_EcdhGetSecret, XSecure_EllipticGenerateEphemeralKey, XSecure_EllipticGenerateKey_64Bit, XSecure_EllipticGenerateSignature_64Bit, XSecure_EllipticPrvtKeyGenerate, XSecure_EllipticValidateKey_64Bit, XSecure_EllipticVerifySign_64Bit, XSecure_MldsaSignGenerate, XSecure_MldsaSignVerify, XSecure_RsaOperation, XSecure_Sha3Start.