core/util/xsecure_sss.c
static int XSecure_SssDmaSrc(u16 DmaId, XSecure_SssSrc *Resource)
This function sets the DMA source of type XSecure_SssSrc based on the provided DMA device ID.
DmaId Device ID of DMA Resource DMA source is updated into the pointer XST_SUCCESS - If DMA ID is correctXST_FAILURE - On wrong DMA ID
static int XSecure_SssCfg(const XSecure_Sss *InstancePtr, XSecure_SssSrc Resource, XSecure_SssSrc InputSrc, XSecure_SssSrc OutputSrc)
This function configures the secure stream switch.
InstancePtr Instance pointer to the XSecure_Sss Resource Resource for which input and output paths to be configured InputSrc Input source to be selected for the resource OutputSrc Output source to be selected for the resource XST_SUCCESS - On successful configuration of the switchXST_FAILURE - On unsuccessful configuration of the switch Resource, InputSrc, OutputSrc are of type XSecure_SssSrc
void XSecure_SssInitialize(XSecure_Sss *InstancePtr)
This function initializes the secure stream switch instance.
InstancePtr Instance pointer to the XSecure_Sss XST_SUCCESS - If initialization was successfulXSECURE_SSS_INVALID_PARAM - On invalid parameter InstancePtr Instance pointer to the XSecure_Sss.
References XSECURE_SSS_ADDRESS, XSECURE_SSS_INVALID_PARAM.
Referenced by XSecure_AesInitialize, XSecure_MemCopy, XSecure_Sha3Initialize.
int XSecure_SssAes(const XSecure_Sss *InstancePtr, XSecure_SssSrc InputSrc, XSecure_SssSrc OutputSrc)
This function configures the secure stream switch for AES engine.
InstancePtr Instance pointer to the XSecure_Sss InputSrc Input DMA to be selected for AES engine OutputSrc Output DMA to be selected for AES engine XST_SUCCESS - On successful configuration of the switchXSECURE_SSS_INVALID_PARAM - On invalid parameterXST_FAILURE - On failure to configure switch InputSrc, OutputSrc are of type XSecure_SssSrc
References XSecure_SecureOut32, XSECURE_SSS_AES, XSECURE_SSS_DMA0, XSECURE_SSS_DMA1, XSECURE_SSS_INVALID_PARAM, XSecure_SssMask.
Referenced by XSecure_AesDecrypt, XSecure_AesDecryptInit, XSecure_AesEncryptInit, XSecure_CfgSssAes.
int XSecure_SssSha(const XSecure_Sss *InstancePtr, u16 DmaId, XSecure_SssSrc Resource)
This function configures the secure stream switch for SHA hardware engine.
InstancePtr Instance pointer to the XSecure_Sss DmaId Device ID of DMA which is to be used as an input to the SHA engine Resource SHA resource for which input and output paths to be configured XST_SUCCESS - On successful configuration of the switchXSECURE_SSS_INVALID_PARAM - On invalid parameterXST_FAILURE - On failure to configure switch
References XSecure_SecureOut32, XSECURE_SSS_DMA0, XSECURE_SSS_DMA1, XSECURE_SSS_INVALID, XSECURE_SSS_INVALID_PARAM, XSecure_SssMask.
int XSecure_SssDmaLoopBack(const XSecure_Sss *InstancePtr, u16 DmaId)
This function configures secure stream switch to set DMA in loop back mode.
InstancePtr Instance pointer to the XSecure_Sss DmaId Device ID of DMA XST_SUCCESS - On successful configuration of the switchXSECURE_SSS_INVALID_PARAM - On invalid parameterXST_FAILURE - On failure to configure switch
References XSECURE_SSS_DMA0, XSECURE_SSS_DMA1, XSECURE_SSS_INVALID, XSECURE_SSS_INVALID_PARAM.
Referenced by XSecure_MemCopy.