xsecure_helper_server_apis
XSECURE_AES_KEY_CLEAR_OFFSET
< AES_KEY_CLEAR register offset and definitions
AES Key Clear register offset
XSECURE_AES_KEY_CLEAR_PUF_KEY_MASK
PUF key clear mask.
XSECURE_AES_KEY_CLEAR_BH_RED_KEY_MASK
BH Red key clear mask.
XSECURE_AES_KEY_CLEAR_BH_KEY_MASK
BH key clear mask.
XSECURE_AES_KEY_CLEAR_EFUSE_RED_KEY_MASK
eFUSE Red key clear mask
XSECURE_AES_KEY_CLEAR_EFUSE_KEY_MASK
eFUSE key clear mask
XSECURE_AES_KEY_CLEAR_USER_KEY_7_MASK
User key 7 clear mask.
XSECURE_AES_KEY_CLEAR_USER_KEY_6_MASK
User key 6 clear mask.
XSECURE_AES_KEY_CLEAR_USER_KEY_5_MASK
User key 5 clear mask.
XSECURE_AES_KEY_CLEAR_USER_KEY_4_MASK
User key 4 clear mask.
XSECURE_AES_KEY_CLEAR_USER_KEY_3_MASK
User key 3 clear mask.
XSECURE_AES_KEY_CLEAR_USER_KEY_2_MASK
User key 2 clear mask.
XSECURE_AES_KEY_CLEAR_USER_KEY_1_MASK
User key 1 clear mask.
XSECURE_AES_KEY_CLEAR_USER_KEY_0_MASK
User key 0 clear mask.
XSECURE_AES_KEY_CLEAR_KUP_KEY_MASK
KUP key clear mask.
XSECURE_AES_KEY_CLEAR_AES_KEY_ZEROIZE_MASK
AES key zeroize mask.
XSECURE_AES_KEY_CLR_REG_CLR_MASK
Key clear register clear mask.
XSECURE_AES_KEY_CLEAR_ALL_KEYS_MASK
Clear all keys mask.
XSECURE_AES_KEY_CLEAR_PUF_RED_EXPANDED_KEYS_MASK
PUF Red expanded keys clear mask.
XSECURE_AES_KEY_CLEAR_KUP_AND_EXP_KEYS_MASK
Combined mask to clear KUP key and expanded (zeroize) key simultaneously.
XSecure_AesKeySrc
BBRAM Key.
XSecure_SssSrc
DMA0.
XSecure_CoreSrc
AES Core.
XSecure_AesOp
Encrypt operation.
XSecure_EllipticCrvTyp
NIST P-192 curve value in Ecdsa.h.
XSecure_SssSrc
DMA0.
XSecure_SssSrc
DMA0.
XSecure_SssSrc
DMA0.
XSecure_SssSrc
DMA0.
XSecure_SssSrc
DMA0.
const XSecure_AesKeyLookup AesKeyLookupTbl[XSECURE_MAX_KEY_SOURCES][XSECURE_MAX_KEY_SOURCES]
TRNG related macros for SPARTANUPLUSAES1 device.
const u8 XSecure_SssLookupTable[XSECURE_SSS_MAX_SRCS][XSECURE_SSS_MAX_SRCS][XSECURE_SSS_MAX_SRCS][XSECURE_SSS_MAX_SRCS]
const XSecure_ShaConfig ShaConfigTable[XSECURE_SHA_NUM_OF_INSTANCES][XSECURE_SHA_NUM_OF_INSTANCES]
const u8 XSecure_SssLookupTable[XSECURE_SSS_MAX_SRCS][XSECURE_SSS_MAX_SRCS][XSECURE_SSS_MAX_SRCS][XSECURE_SSS_MAX_SRCS]
const XSecure_ShaConfig ShaConfigTable[XSECURE_SHA_NUM_OF_INSTANCES][XSECURE_SHA_NUM_OF_INSTANCES]
const u8 XSecure_SssLookupTable[XSECURE_SSS_MAX_SRCS][XSECURE_SSS_MAX_SRCS][XSECURE_SSS_MAX_SRCS][XSECURE_SSS_MAX_SRCS]
const XSecure_ShaConfig ShaConfigTable[XSECURE_SHA_NUM_OF_INSTANCES][XSECURE_SHA_NUM_OF_INSTANCES]
const u8 XSecure_SssLookupTable[XSECURE_SSS_MAX_SRCS][XSECURE_SSS_MAX_SRCS][XSECURE_SSS_MAX_SRCS][XSECURE_SSS_MAX_SRCS]
const XSecure_ShaConfig ShaConfigTable[XSECURE_SHA_NUM_OF_INSTANCES][XSECURE_SHA_NUM_OF_INSTANCES]
const u8 XSecure_SssLookupTable[XSECURE_SSS_MAX_SRCS][XSECURE_SSS_MAX_SRCS][XSECURE_SSS_MAX_SRCS][XSECURE_SSS_MAX_SRCS]
const XSecure_ShaConfig ShaConfigTable[XSECURE_SHA_NUM_OF_INSTANCES][XSECURE_SHA_NUM_OF_INSTANCES]
const u8 XSecure_SssLookupTable[XSECURE_SSS_MAX_SRCS][XSECURE_SSS_MAX_SRCS][XSECURE_SSS_MAX_SRCS][XSECURE_SSS_MAX_SRCS]
const XSecure_ShaConfig ShaConfigTable[XSECURE_SHA_NUM_OF_INSTANCES][XSECURE_SHA_NUM_OF_INSTANCES]
u32 XSecure_SssMask(XSecure_SssSrc InputSrc, XSecure_SssSrc OutputSrc, u32 Value)
This function masks the secure stream switch value.
InputSrc Input source to be selected for the resource OutputSrc Output source to be selected for the resource Value Register Value of SSS cfg register Mask - Mask value of corresponding InputSrc and OutputSrc InputSrc, OutputSrc are of type XSecure_SssSrc InputSrc Input source to be selected for the resource OutputSrc Output source to be selected for the resource Value Register Value of SSS cfg register Mask Mask value of corresponding InputSrc and OutputSrc InputSrc, OutputSrc are of type XSecure_SssSrc InputSrc Input source to be selected for the resource OutputSrc Output source to be selected for the resource Value Register Value of SSS cfg register Mask value of corresponding InputSrc and OutputSrc InputSrc, OutputSrc are of type XSecure_SssSrc InputSrc Input source to be selected for the resource. OutputSrc Output source to be selected for the resource. Value Register Value of SSS cfg register. Mask Mask value of corresponding InputSrc and OutputSrc InputSrc, OutputSrc are of type XSecure_SssSrc InputSrc Input source to be selected for the resource. OutputSrc Output source to be selected for the resource. Value Register Value of SSS cfg register. Mask Mask value of corresponding InputSrc and OutputSrc. InputSrc, OutputSrc are of type XSecure_SssSrc.
References XSECURE_SSS_AES_DMA0_VAL, XSECURE_SSS_AES_MASK, XSECURE_SSS_DMA0, XSECURE_SSS_DMA0_MASK, XSECURE_SSS_SBI_DMA0_VAL, XSECURE_SSS_SBI_MASK, XSECURE_SSS_SHA_DMA0_VAL, XSECURE_SSS_SHA_MASK.
Referenced by XSecure_SssAes, XSecure_SssSha.
int XSecure_AesValidateSize(u32 Size, u8 IsLastChunk)
This function validates the size.
This function validates whether all the intermediate updates to AES engine are Q-WORD aligned or not.This function validates if intermediate updates are 16-bytes aligned or not.This function is not applicable for Versal_2Ve_2Vm.This function validates whether size of the data is word aligned and if it is the last chunk size should be qword aligned. Size Size of data in bytes. IsLastChunk Last chunk indication XST_SUCCESS on successful validationError code on failure Size Size of data in bytes. IsLastChunk Last chunk indication XST_SUCCESS On successful valdationXSECURE_AES_UNALIGNED_SIZE_ERROR If unaligned size is given as input Size Size of data in bytes. IsLastChunk Last chunk indication XST_SUCCESS - On successXSECURE_AES_UNALIGNED_SIZE_ERROR - Size is not 16-byte aligned for non-last chunk Size Size of data in bytes. IsLastChunk Last chunk indication. XST_SUCCESS On successful valdation.XSECURE_AES_UNALIGNED_SIZE_ERROR If unaligned size is given as input. Size Size of data in bytes. IsLastChunk Last chunk indication. XST_SUCCESS If update is 16-bytes aligned.XSECURE_AES_UNALIGNED_SIZE_ERROR If update is not 16-bytes aligned. Size Size of data in bytes. IsLastChunk Last chunk indication XST_SUCCESS If the data is q-word aligned for intermediate updates XST_FAILURE If the data is not q-word aligned for intermediate updates
References XSECURE_AES_UNALIGNED_SIZE_ERROR, XSECURE_QWORD_SIZE, XSECURE_WORD_SIZE.
int XSecure_AesPlatPmcDmaCfgAndXfer(XPmcDma *PmcDmaPtr, const XSecure_AesDmaCfg *AesDmaCfg, u32 Size, UINTPTR BaseAddress)
This function configures the PMC DMA channels and transfers data.
This function sets the SRC and DEST channel endianness configurations of PMC DMA and transfers data. PmcDmaPtr Pointer to the XPmcDma instance. AesDmaCfg DMA SRC and DEST channel configuration Size Size of data in bytes. BaseAddress Not applicable for versal XST_SUCCESS on successful configurationError code on failure PmcDmaPtr Pointer to the XPmcDma instance. AesDmaCfg DMA SRC and DEST channel configuration Size Size of data in bytes. BaseAddress Not applicable for versal XST_SUCCESS On successful configurationXSECURE_AES_INVALID_PARAM If any input parameter is invalidXST_FAILURE On failure PmcDmaPtr Pointer to the XPmcDma instance. AesDmaCfg DMA SRC and DEST channel configuration. Size Size of data in bytes. BaseAddress Not applicable for versal_2vp. XST_SUCCESS On successful configurationXSECURE_AES_INVALID_PARAM If any input parameter is invalidXST_FAILURE On failure
References XSecure_AesDmaCfg::DestChannelCfg, XSecure_AesDmaCfg::DestDataAddr, XSecure_AesDmaCfg::IsLastChunkDest, XSecure_AesDmaCfg::IsLastChunkSrc, XSecure_AesDmaCfg::SrcChannelCfg, XSecure_AesDmaCfg::SrcDataAddr, XSECURE_ADDR_HIGH_SHIFT, XSECURE_AES_INVALID_PARAM, XSECURE_AES_NO_CFG_DST_DMA, XSECURE_WORD_SIZE.
void XSecure_AesPmcDmaCfgEndianness(XPmcDma *InstancePtr, XPmcDma_Channel Channel, u8 EndianType)
This is a helper function to enable/disable byte swapping feature of PMC DMA.
InstancePtr Pointer to the XPmcDma instance Channel Channel Type (XPMCDMA_SRC_CHANNEL or XPMCDMA_DST_CHANNEL) EndianType 1 to enable byte swapping, 0 to disable byte swapping InstancePtr Pointer to the XPmcDma instance. Channel Channel Type (XPMCDMA_SRC_CHANNEL or XPMCDMA_DST_CHANNEL) EndianType 1 to enable byte swapping, 0 to disable byte swapping InstancePtr Pointer to the XPmcDma instance Channel Channel type (XPMCDMA_SRC_CHANNEL or XPMCDMA_DST_CHANNEL) EndianType Endianness type: 1 to enable byte swapping, 0 to disable byte swapping
References XSecure_AssertVoid.
Referenced by XSecure_AesEncryptUpdate, XSecure_AesPlatPmcDmaCfgAndXfer.
int XSecure_ShaValidateModeAndCfgInstance(XSecure_Sha *const InstancePtr, XSecure_ShaMode ShaMode)
This function validates the SHA Mode and initialize SHA instance.
InstancePtr Pointer to the SHA instance. ShaMode SHA Mode. XST_SUCCESS - Upon Success. XST_FAILURE - Upon Failure. XSECURE_SHA_INVALID_MODE_ERROR InstancePtr Pointer to the SHA instance. ShaMode SHA Mode XST_SUCCESS - Upon successXSECURE_SHA_INVALID_PARAM - Invalid SHA mode provided InstancePtr Pointer to the SHA instance. ShaMode SHA Mode. XST_SUCCESS Upon Success.XST_FAILURE Upon Failure.XSECURE_SHA_INVALID_MODE_ERROR In case of invalid sha mode config.
References SHA256, SHA384, SHA512, XSecure_ShaPlatConfig::ShaDigestSize, SHAKE256, XSecure_ShaPlatConfig::ShaMode, XSECURE_SHA2_256_HASH_LEN, XSECURE_SHA2_384_HASH_LEN, XSECURE_SHA3_256, XSECURE_SHA3_256_HASH_LEN, XSECURE_SHA3_384, XSECURE_SHA3_384_HASH_LEN, XSECURE_SHA_512_HASH_LEN, XSECURE_SHA_INVALID_PARAM, XSECURE_SHAKE_256, XSECURE_SHAKE_256_HASH_LEN.
Referenced by XSecure_ShaDigest.
static int XSecure_ShaIssueDmaAndWait(XPmcDma *DmaPtr, u64 SrcAddr, u32 Words, u8 IsLast)
This function issues a single PMC-DMA SRC transfer to the SHA engine and waits for the DONE bit.
DmaPtr Pointer to the PMC-DMA instance. SrcAddr Word-aligned source address. Words Transfer length in 32-bit words. IsLast When TRUE, asserts data_inp_last on the final word. XST_SUCCESS - On DMA DONE asserted within timeout.XST_FAILURE - On DMA transfer timeout.
int XSecure_ShaDmaXfer(void *InstancePtr, u64 DataAddr, u32 Size, u8 IsLastUpdate)
This function transfers input data to the SHA engine via PMC-DMA, using PartialData[] as a small residue buffer for sub-word and sub-block leftovers between calls.
This function transfer data to SHA engine from DMA. If there is no prior residue and the caller address is word- aligned, the word-aligned portion is DMA'd directly from the caller buffer and any 0..3 trailing bytes are stashed into PartialData[] for the next call. Otherwise the caller bytes are staged through PartialData[] and DMA'd in fixed BlockLen chunks (one Keccak rate / SHA absorber block) sourced from &PartialData[0]; the trailing < BlockLen residue is deferred to SW NIST padding via XSecure_TransferNistPad. Constant DMA size and constant source address are required here to keep the PMC-DMA source channel stable across back-to-back transfers on Spartan UltraScale+. InstancePtr Pointer to the SHA instance. DataAddr Address of the input data. Size Size of the input data in bytes. IsLastUpdate Flag indicating if this is the last data transfer. XST_SUCCESS - Upon successful data transfer.XST_FAILURE - Upon DMA transfer failure.XSECURE_SHA_INVALID_PARAM - Upon invalid parameter. InstancePtr Pointer to the SHA instance. DataAddr Input data address Size Input data size in bytes. IsLastUpdate Last update flag XST_SUCCESS - Upon successXSECURE_SHA_INVALID_PARAM - Invalid parameter InstancePtr Pointer to the SHA instance. DataAddr Input data address. Size Input data size in bytes. IsLastUpdate Last update flag. XST_SUCCESS Upon Success.XST_FAILURE Upon Failure.
References XSecure_ShaPlatConfig::HashAlgo, XSecure_MemCpy64, XSECURE_SHA_INVALID_PARAM, XSecure_ShaGetBlockLen, XSECURE_WORD_ALIGN_MASK, XSECURE_WORD_SIZE.
int XSecure_CfgSssAes(XPmcDma *DmaPtr, const XSecure_Sss *SssInstance)
This function configures SSS to AES engine.
DmaPtr Pointer to the DMA instance SssInstance Pointer to SSS instance XST_SUCCESS on successful configurationError code on failure
References XSECURE_SSS_DMA0, XSECURE_SSS_DMA1, XSecure_SssAes.
int XSecure_CryptoCheck(XSecure_CoreSrc CoreSrc)
This function checks whether the requested crypto accelerator is enabled for the specified core.
CoreSrc Crypto core source (AES, SHA, RSA) XST_SUCCESS - When crypto accelerators are enabledXSECURE_ERR_CRYPTO_ACCELERATOR_DISABLED - When crypto accelerators are disabledXSECURE_ERR_INVALID_CORE - When invalid core is specified
References XSECURE_AES_CRYPTO_DIS_MASK, XSECURE_CORE_AES, XSECURE_CORE_RSA_ECC, XSECURE_CORE_SHA, XSECURE_EFUSE_CONTROLS_ADDRESS, XSECURE_EFUSE_EXPORT_CONTROL_MASK, XSECURE_ERR_CRYPTO_ACCELERATOR_DISABLED, XSECURE_ERR_INVALID_CORE, XSecure_In32, XSECURE_PMC_GLOBAL_CRYPTO_DIS_ADDRESS, XSECURE_SHA_CRYPTO_DIS_MASK.
static void XSecure_UpdateCryptoStatus(UINTPTR BaseAddress, u32 Op)
This function is not applicable for versal.
This function updates the crypto indicator bit of AES, SHA and ECC. BaseAddress Base address of the core Op To set or clear the bit BaseAddress Base address of the core. Op To set or clear the bit.
static void XSecure_SetRsaCryptoStatus(void)
This function is not applicable for versal.
This function updates RSA crypto indicator.
static int XSecure_RsaDecrypt(u32 SubsystemId, u32 SrcAddrLow, u32 SrcAddrHigh, u32 DstAddrLow, u32 DstAddrHigh)
This function handler calls XSecure_RsaInitialize and XSecure_RsaPrivateDecrypt server APIs.
SubsystemId - Subsystem ID. SrcAddrLow - Lower 32 bit address of the XSecure_RsaInParam structure SrcAddrHigh - Higher 32 bit address of the XSecure_RsaInParam structure DstAddrLow - Lower 32 bit address of the output data where decrypted data to be stored DstAddrHigh - Higher 32 bit address of the output data where decrypted data to be stored XST_SUCCESS If the Rsa decryption is successfulXST_FAILURE If there is a failure
int XSecure_PlatIpiHandler(XPlmi_Cmd *Cmd)
This function calls respective IPI handler based on the API_ID.
Cmd is a pointer to the command structure XST_SUCCESS If the handler execution is successfulXST_INVALID_PARAM If any input parameter is invalidXST_FAILURE If there is a failure Cmd Pointer to the command structure XST_SUCCESS - If the handler execution is successfulXST_INVALID_PARAM - If any input parameter is invalidXST_FAILURE - If there is a failure Cmd is a pointer to the command structure. XST_SUCCESS If the handler execution is successful.XST_INVALID_PARAM If any input parameter is invalid.XST_FAILURE If there is a failure. Cmd Pointer to the command structure. XST_SUCCESS If the handler execution is successful.XST_INVALID_PARAM If any input parameter is invalid.XST_FAILURE If there is a failure.
References XSECURE_API, XSECURE_API_ID_MASK, XSECURE_API_RSA_PRIVATE_DECRYPT, XSECURE_DEBUG_GENERAL, XSecure_Printf.
static void XSecure_UpdateEcdsaCryptoStatus(u32 Op)
This function updates ECC crypto indicator.
Op To set or clear the bit
void XSecure_UpdateTrngCryptoStatus(u32 Op)
This function updates TRNG crypto indicator.
Op To set or clear the bit. Op To set or clear the bit
Referenced by XSecure_EllipticPrvtKeyGenerate.
void XSecure_ConfigureDmaByteSwap(u32 Op)
This function configures DMA Byte Swap based on the user input.
Op Enable/Disable byte swapping.
References XSecure_GetAesInstance.
Referenced by XSecure_AesDecryptKat, XSecure_AesEncryptKat.
int XSecure_AesPlatPmcDmaCfgAndXfer(XPmcDma *PmcDmaPtr, XSecure_AesDmaCfg *AesDmaCfg, u32 Size, UINTPTR BaseAddress)
This function sets the SRC and DEST channel endianness configurations of PMC DMA and transfers data.
PmcDmaPtr Pointer to the XPmcDma instance. AesDmaCfg DMA SRC and DEST channel configuration Size Size of data in bytes. BaseAddress AES BaseAddress XST_SUCCESS - On successful configurationXSECURE_AES_INVALID_PARAM - Invalid input parameter providedXST_FAILURE - DMA transfer or timeout failure PmcDmaPtr Pointer to the XPmcDma instance. AesDmaCfg DMA SRC and DEST channel configuration. Size Size of data in bytes. BaseAddress AES BaseAddress. XST_SUCCESS On successful configuration. XSECURE_AES_INVALID_PARAM If any input parameter is invalid. XST_FAILURE On failure. PmcDmaPtr Pointer to the XPmcDma instance. AesDmaCfg DMA SRC and DEST channel configuration Size Size of data in bytes. BaseAddress AES BaseAddress XST_SUCCESS On successful configurationXSECURE_AES_INVALID_PARAM If any input parameter is invalid XST_FAILURE On failure
References XSecure_AesDmaCfg::DestChannelCfg, XSecure_AesDmaCfg::DestDataAddr, XSecure_AesDmaCfg::IsLastChunkDest, XSecure_AesDmaCfg::IsLastChunkSrc, XSecure_AesDmaCfg::SrcChannelCfg, XSecure_AesDmaCfg::SrcDataAddr, XSECURE_AES_INVALID_PARAM, XSECURE_AES_NO_CFG_DST_DMA, XSecure_AesPmcDmaCfgEndianness, XSECURE_DISABLE_BYTE_SWAP, XSECURE_ENABLE_BYTE_SWAP, XSecure_GetAesInstance.
int XSecure_GetRandomNum(u8 *Output, u32 Size)
This function generates random number of given size.
This function generates Random number of given size. Output Pointer to the output buffer Size Number of random bytes to be read XST_SUCCESS - On successXST_INVALID_PARAM - Invalid input parameter (size is 0 or output is NULL)XSECURE_ERR_GLITCH_DETECTED - Glitch detected during random number generationXST_FAILURE - TRNG operation failure Output is a pointer to the output buffer Size is the number of random bytes to be read XST_SUCCESS On SuccessXST_FAILURE On FailureXST_INVALID_PARAM - Invalid input parameter (size is 0 or output is NULL)XSECURE_ERR_GLITCH_DETECTED - Error when glitch is detected Output Pointer to the output buffer. Size Number of random bytes to be read. XST_SUCCESS On Success. XST_FAILURE On Failure.XST_INVALID_PARAM - Invalid input parameter (size is 0 or output is NULL) XSECURE_ERR_GLITCH_DETECTED - Error when glitch is detected. Output is a pointer to the output buffer Size is the number of random bytes to be read XST_SUCCESS On SuccessXST_FAILURE On FailureXST_INVALID_PARAM - Invalid input parameter (size is 0 or output is NULL)XSECURE_ERR_GLITCH_DETECTED - Error when glitch is detected.
References XSecure_ECCRandInit, XSECURE_ERR_GLITCH_DETECTED, XSecure_GetTrngInstance, XSECURE_TRNG_SEC_STRENGTH_IN_BYTES, XSecure_Uninstantiate.
Referenced by XSecure_EllipticGenerateEphemeralKey, XSecure_MldsaSignGenerate.
int XSecure_ECCRandInit(void)
This function initializes the trng in HRNG mode if it is not initialized and it is applicable only for Versal_2Ve_2Vm.
This function initializes the trng in HRNG mode if it is not initialized and it is applicable only for VersalNet.This function initializes the trng in HRNG mode if it is not initialized.This function initializes the trng in HRNG mode if it is not initialized and it is applicable only for Versal_2VP. XST_SUCCESS - On successful initializationXSECURE_ERR_IN_TRNG_SELF_TESTS - TRNG self-test failureXSECURE_ERR_TRNG_INIT_N_CONFIG - TRNG initialization and configuration failureXST_FAILURE - On any other failure XST_SUCCESS On Successful initializationXST_FAILURE On Failure XST_SUCCESS On Successful initialization.XST_FAILURE On Failure.
References XSECURE_ERR_IN_TRNG_SELF_TESTS, XSECURE_ERR_TRNG_INIT_N_CONFIG, XSecure_GetTrngInstance, XSecure_PreOperationalSelfTests, XSECURE_TRNG_HRNG_MODE, XSecure_TrngInitNCfgMode.
Referenced by XSecure_EcdhGetSecret, XSecure_EllipticGenerateKey_64Bit, XSecure_EllipticGenerateSignature_64Bit, XSecure_GetRandomNum.
int XSecure_InitiateASUKeyTransfer(void)
This function initiates the key transfer to ASU.
XST_SUCCESS - On successful key transferXSECURE_ERR_ASU_KTE_DONE_NOT_SET - Key transfer done bit not set within timeout
References XSECURE_AES_KTE_CNT_ADDRESS, XSECURE_AES_KTE_DONE_ADDRESS, XSECURE_AES_KTE_DONE_MASK, XSECURE_AES_KTE_DONE_POLL_TIMEOUT, XSECURE_AES_KTE_GO_ADDRESS, XSECURE_AES_KTE_GO_DISABLE, XSECURE_AES_KTE_GO_ENABLE, XSECURE_DEBUG_GENERAL, XSECURE_ERR_ASU_KTE_DONE_NOT_SET, XSecure_In32, XSecure_Out32, XSecure_Printf.
int XSecure_MemCpyAndChangeEndianness(u64 DestAddress, u64 SrcAddress, u32 Length)
This function can copy the content of memory from 64-bit address to 32-bit address and change endianness of destination data.
DestAddress The address of the destination where content of SrcAddr memory should be copied. SrcAddress The address of the source where copy should start from. Length Size of memory to be copied in bytes. XST_SUCCESS - On successXST_FAILURE - Memory copy or endianness reversal failure DestAddress The address of the destination where content of SrcAddr memory should be copied. SrcAddress The address of the source where copy should start from. Length Size of memory to be copied in bytes. XST_SUCCESS On success and error code on failure.XST_FAILURE In case of any failure. DestAddress is the address of the destination where content of SrcAddr memory should be copied. SrcAddress is the address of the source where copy should start from. Length is size of memory to be copied in bytes. XST_SUCCESS On successXST_FAILURE On failure
Referenced by XSecure_KeyUnwrap.
static int XSecure_RsaPrivateOperationIpi(u32 SubsystemId, u32 RsaParamAddrLow, u32 RsaParamAddrHigh, u32 DstAddrLow, u32 DstAddrHigh)
This function handler calls XSecure_RsaInitialize and XSecure_RsaExp server API.
SubsystemId Subsystem ID. RsaParamAddrLow Lower 32 bit address of the XSecure_RsaInParam structure RsaParamAddrHigh Higher 32 bit address of the XSecure_RsaInParam structure DstAddrLow Lower 32 bit address of the output data where decrypted data to be stored DstAddrHigh Higher 32 bit address of the output data where decrypted data to be stored XST_SUCCESS - If the Rsa decryption is successfulXST_INVALID_PARAM - If any input parameter is invalidXSECURE_RSA_GEN_SIGN_FAILED_ERROR - If RSA sign generation failsXST_FAILURE - If there is a failure
static int XSecure_RsaDecrypt(u32 SrcAddrLow, u32 SrcAddrHigh, u32 DstAddrLow, u32 DstAddrHigh)
This function handler calls XSecure_RsaInitialize and XSecure_RsaPrivateDecrypt server APIs.
SrcAddrLow Lower 32 bit address of the XSecure_RsaInParam structure. SrcAddrHigh Higher 32 bit address of the XSecure_RsaInParam structure. DstAddrLow Lower 32 bit address of the output data where decrypted data to be stored. DstAddrHigh Higher 32 bit address of the output data where decrypted data to be stored. XST_SUCCESS If the Rsa decryption is successful.XST_FAILURE If there is a failure.
static int XSecure_RsaPrivateOperationIpi(u32 RsaParamAddrLow, u32 RsaParamAddrHigh, u32 DstAddrLow, u32 DstAddrHigh)
This function handler calls XSecure_RsaInitialize and XSecure_RsaExp server API.
RsaParamAddrLow Lower 32 bit address of the XSecure_RsaInParam structure. RsaParamAddrHigh Higher 32 bit address of the XSecure_RsaInParam structure. DstAddrLow Lower 32 bit address of the output data where decrypted data to be stored. DstAddrHigh Higher 32 bit address of the output data where decrypted data to be stored. XST_SUCCESS If the Rsa decryption is successful.XST_INVALID_PARAM If any input parameter is invalid.XSECURE_RSA_GEN_SIGN_FAILED_ERROR If RSA sign generation fails.XST_FAILURE If there is a failure.
static int XSecure_AesPmcDmaByteXfer(XPmcDma *PmcDmaPtr, const XSecure_AesDmaCfg *AesDmaCfg, u32 Size, UINTPTR BaseAddress)
This function sets the SRC and DEST channel endianness configurations of PMC DMA and transfers non-qword aligned data.
PmcDmaPtr Pointer to the XPmcDma instance. AesDmaCfg DMA SRC and DEST channel configuration Size Size of data in bytes. BaseAddress Aes BaseAddress XST_SUCCESS On successful configurationXST_FAILURE On failure
static int XSecure_AesPmcDmaWordXfer(XPmcDma *PmcDmaPtr, const XSecure_AesDmaCfg *AesDmaCfg, u32 Size)
This function sets the SRC and DEST channel endianness configurations of PMC DMA and transfers qword aligned data.
PmcDmaPtr Pointer to the XPmcDma instance. AesDmaCfg DMA SRC and DEST channel configuration Size Size of data in bytes. XST_SUCCESS On successful configurationXST_FAILURE On failure
static void XSecure_AesDataEndiannessChange(u64 Address, u32 Size)
This function changes the endianness of particular size.
Address Endianness change data stored address Size Size of the data
static int XSecure_UpdateCryptoMask(XSecure_CryptoStatusOp CryptoOp, u32 CryptoMask, u32 CryptoVal)
This function sets or clears Crypto bit mask of given NodeId.
CryptoOp Operation to set or clear crypto bit mask CryptoMask Crypto Mask of the module CryptoVal Crypto value to be updated XST_SUCCESS If set or clear is successfulXST_FAILURE On failure
static int XSecure_KeyUnwrapIpi(u32 SubsystemId, u32 KeyWrapAddrLow, u32 KeyWrapAddrHigh)
This function unwraps the input wrapped key and copies to secure shell.
SubsystemId Subsystem ID. KeyWrapAddrLow Lower address of the XSecure_KeyWrapData structure. KeyWrapAddrHigh Higher address of the XSecure_KeyWrapData structure. XST_SUCCESS On SuccessXSECURE_ERR_INVALID_KEY_STORE_ADDR If key store address is 0XST_FAILURE On failure
XSECURE_ADDR_HIGH_SHIFT
High address shift for 64-bit addresses.
Referenced by XSecure_AesPlatPmcDmaCfgAndXfer.
XSECURE_AES_BASEADDR
AES base address.
XSECURE_SSS_ADDRESS
SSS base address.
Referenced by XSecure_SssInitialize.
XSECURE_SSS_MAX_SRCS
SSS Maximum resources.
XSECURE_SSS_SHA_MASK
SSS SHA3 instance 0 mask value.
Referenced by XSecure_SssMask.
XSECURE_SSS_SHA_DMA0_VAL
SSS SHA3 instance 0 DMA0 value.
Referenced by XSecure_SssMask.
XSECURE_AES_NO_CFG_DST_DMA
Not to configure Dst DMA at this address in AES.
Referenced by XSecure_AesPlatPmcDmaCfgAndXfer.
XSECURE_SSS_SBI_MASK
SSS SBI mask.
Referenced by XSecure_SssMask.
XSECURE_SSS_AES_MASK
SSS AES mask.
Referenced by XSecure_SssMask.
XSECURE_SSS_DMA0_MASK
SSS DMA0 mask.
Referenced by XSecure_SssMask.
XSECURE_SSS_SRC_SEL_MASK
SSS Source select mask.
XSECURE_SSS_SBI_DMA0_VAL
SSS SBI DMA0 value.
Referenced by XSecure_SssMask.
XSECURE_SSS_AES_DMA0_VAL
SSS AES DMA0 value.
Referenced by XSecure_SssMask.
XSECURE_AES_KEY_SEL_BH_KEY
BH Key.
XSECURE_AES_KEY_SEL_BH_RD_KEY
BH Read Key.
XSECURE_AES_KEY_SEL_EFUSE_KEY
eFUSE Key
XSECURE_AES_KEY_SEL_EFUSE_RED_KEY
eFUSE Red Key
XSECURE_AES_KEY_SEL_KUP_KEY
KUP Key.
XSECURE_AES_KEY_SEL_FAMILY_KEY
Family Key.
XSECURE_AES_KEY_SEL_PUF_KEY
PUF Key.
XSECURE_AES_KEY_SEL_USR_KEY_0
User Key 0.
XSECURE_AES_KEY_SEL_USR_KEY_1
User Key 1.
XSECURE_AES_KEY_SEL_USR_KEY_2
User Key 2.
XSECURE_AES_KEY_SEL_USR_KEY_3
User Key 3.
XSECURE_AES_KEY_SEL_USR_KEY_4
User Key 4.
XSECURE_AES_KEY_SEL_USR_KEY_5
User Key 5.
XSECURE_AES_KEY_SEL_USR_KEY_6
User Key 6.
XSECURE_AES_KEY_SEL_USR_KEY_7
User Key 7.
XSECURE_EFUSE_CONTROLS_ADDRESS
Efuse Controls base address.
Referenced by XSecure_CryptoCheck.
XSECURE_EFUSE_EXPORT_CONTROL_MASK
Export control efuse bit mask.
Referenced by XSecure_CryptoCheck.
XSECURE_PMC_GLOBAL_CRYPTO_DIS_ADDRESS
PMC Global Crypto Disable Address.
Referenced by XSecure_CryptoCheck.
XSECURE_AES_CRYPTO_DIS_MASK
AES Crypto Disable mask.
Referenced by XSecure_CryptoCheck.
XSECURE_SHA_CRYPTO_DIS_MASK
SHA Crypto Disable mask.
Referenced by XSecure_CryptoCheck.
XSECURE_AES_KEY_DEC_SEL_BH_RED
BH Red Key Decryption Source Select.
XSECURE_AES_KEY_DEC_SEL_EFUSE_RED
eFUSE Red Key Decryption Source Select
XSECURE_AES_INVALID_CFG
Invalid Configuration.
XSECURE_MAX_KEY_SOURCES
Max key source value.
XSECURE_SHA3_256_HASH_LEN
SHA3_256 block length.
Referenced by XSecure_ShaValidateModeAndCfgInstance.
XSECURE_SHA2_256_HASH_LEN
SHA2_256 hash length.
Referenced by XSecure_LmsLookupParamSet, XSecure_Sha2256Kat, XSecure_ShaValidateModeAndCfgInstance.
XSECURE_SHAKE_256_HASH_LEN
SHAKE_256 hash length.
Referenced by XSecure_LmsLookupParamSet, XSecure_ShakeKat, XSecure_ShaValidateModeAndCfgInstance.
SHA256
SHA256 mode.
Referenced by XSecure_ShaValidateModeAndCfgInstance.
SHAKE256
SHAKE256 mode.
Referenced by XSecure_ExtendedShaFinish, XSecure_ShaValidateModeAndCfgInstance.
XSECURE_SSS_ADDRESS
SSS base address.
XSECURE_SSS_MAX_SRCS
SSS Maximum resources.
XSECURE_SSS_SHA3_0_MASK
SSS SHA3 instance 0 mask value.
XSECURE_SSS_SHA3_0_DMA0_VAL
SSS SHA3 instance 0 DMA0 value.
XSECURE_SSS_SHA3_0_DMA1_VAL
SSS SHA3 instance 0 DMA1 value.
XSECURE_AES_NO_CFG_DST_DMA
Not to configure Dst DMA at this address in AES.
XSECURE_ENABLE_BYTE_SWAP
Enables data swap in AES.
Referenced by XSecure_AesDecryptKat, XSecure_AesEncryptKat, XSecure_AesPlatPmcDmaCfgAndXfer.
XSECURE_DISABLE_BYTE_SWAP
Disables data swap in AES.
Referenced by XSecure_AesEcbDecrypt, XSecure_AesEncryptUpdate, XSecure_AesKeyUnwrap, XSecure_AesPlatPmcDmaCfgAndXfer.
XSECURE_SSS_SBI_MASK
SSS SBI mask.
XSECURE_SSS_AES_MASK
SSS AES mask.
XSECURE_SSS_DMA1_MASK
SSS DMA1 mask.
XSECURE_SSS_DMA0_MASK
SSS DMA0 mask.
XSECURE_SSS_SRC_SEL_MASK
SSS Source Select mask.
XSECURE_SSS_SBI_DMA0_VAL
SSS SBI DMA0 value.
XSECURE_SSS_SBI_DMA1_VAL
SSS SBI DMA1 value.
XSECURE_SSS_AES_DMA0_VAL
SSS AES DMA0 value.
XSECURE_SSS_AES_DMA1_VAL
SSS AES DMA1 value.
XSECURE_AES_ADDRESS
AES BaseAddress.
XSECURE_SHA_ADDRESS
SHA BaseAddress.
XSECURE_RSA_ECDSA_RSA_ADDRESS
RSA ECDSA BaseAddress.
XSECURE_SSS_ADDRESS
SSS base address.
XSECURE_SSS_MAX_SRCS
Maximum resources.
XSECURE_SSS_SHA3_MASK
SSS SHA3 instance mask value.
XSECURE_SSS_SHA2_MASK
SSS SHA3 instance mask value.
XSECURE_SSS_SHA3_DMA0_VAL
SSS SHA3 instance DMA0 value.
XSECURE_SSS_SHA3_DMA1_VAL
SSS SHA3 instance DMA1 value.
XSECURE_SSS_SHA2_DMA0_VAL
SSS SHA2 instance DMA0 value.
XSECURE_SSS_SHA2_DMA1_VAL
SSS SHA2 instance DMA1 value.
XSECURE_ENABLE_BYTE_SWAP
Enables data swap in AES.
XSECURE_DISABLE_BYTE_SWAP
Disables data swap in AES.
XSECURE_TRNG_USER_CFG_SEED_LIFE
User configuration seed life.
XSECURE_TRNG_USER_CFG_DF_LENGTH
User configuration DF length.
XSECURE_TRNG_USER_CFG_ADAPT_TEST_CUTOFF
Adapt test cutoff.
XSECURE_TRNG_USER_CFG_REP_TEST_CUTOFF
Rep test cutoff.
XSECURE_AES_KTE_GO_ADDRESS
AES KTE GO address.
Referenced by XSecure_InitiateASUKeyTransfer.
XSECURE_AES_KTE_RESTART_ADDRESS
AES Key Transfer Engine Restart register.
XSECURE_AES_KTE_DONE_ADDRESS
AES Key Transfer Engine Done.
Referenced by XSecure_InitiateASUKeyTransfer.
XSECURE_AES_KTE_CNT_ADDRESS
AES Key Transfer Engine Count address.
Referenced by XSecure_InitiateASUKeyTransfer.
XSECURE_AES_KTE_GO_ENABLE
AES KTE GO enable.
Referenced by XSecure_InitiateASUKeyTransfer.
XSECURE_AES_KTE_GO_DISABLE
AES KTE GO disable.
Referenced by XSecure_InitiateASUKeyTransfer.
XSECURE_AES_KTE_DONE_MASK
AES Key Transfer Engine Done mask.
Referenced by XSecure_InitiateASUKeyTransfer.
XSECURE_AES_KTE_CNT_MASK
AES Key Transfer Engine Count value.
XSECURE_AES_KTE_DONE_POLL_TIMEOUT
AES Key Transfer complete poll timeout.
Referenced by XSecure_InitiateASUKeyTransfer.
XSECURE_SSS_SBI_MASK
SSS SBI mask.
XSECURE_SSS_AES_MASK
SSS AES mask.
XSECURE_SSS_DMA1_MASK
SSS DMA1 mask.
XSECURE_SSS_DMA0_MASK
SSS DMA0 mask.
XSECURE_SSS_SRC_SEL_MASK
SSS Source Select mask.
XSECURE_SSS_SBI_DMA0_VAL
SSS SBI DMA0 value.
XSECURE_SSS_SBI_DMA1_VAL
SSS SBI DMA1 value.
XSECURE_SSS_AES_DMA0_VAL
SSS AES DMA0 value.
XSECURE_SSS_AES_DMA1_VAL
SSS AES DMA1 value.
XCSUDMA_WORD_SIZE
WORD size.
XSECURE_SHA_512_HASH_LEN
SHA_512 block length.
Referenced by XSecure_ShaValidateModeAndCfgInstance.
XSECURE_SHA3_256_HASH_LEN
SHA3_256 block length.
XSECURE_SHA2_256_BLOCK_LEN
SHA2_256 block length.
XSECURE_SHA3_BLOCK_LEN
SHA3 block length.
Referenced by XSecure_HmacFinal, XSecure_HmacInit, XSecure_HmacUpdate, XSecure_Sha3Finish, XSecure_Sha3Start.
XSECURE_SHA2_384_BLOCK_LEN
SHA2_384 block length.
XSECURE_SHAKE_256_BLOCK_LEN
SHAKE_256 block length.
XSECURE_SHA3_384_HASH_LEN
SHA3_384 hash length.
Referenced by XSecure_ShaValidateModeAndCfgInstance.
XSECURE_SHA2_384_HASH_LEN
SHA2_384 hash length.
Referenced by XSecure_ShaValidateModeAndCfgInstance.
XSECURE_SHAKE_256_HASH_LEN
SHAKE_256 hash length.
XSECURE_SHA2_256_HASH_LEN
SHA2_256 hash length.
XSECURE_SHA3_384_HASH_WORD_LEN
SHA3_384 hash word length.
XSECURE_SHA2_384_HASH_WORD_LEN
SHA2_384 hash word length.
XSECURE_SHAKE_256_HASH_WORD_LEN
SHAKE_256 hash word length.
XSECURE_SHA2_256_HASH_WORD_LEN
SHA2_256 hash word length.
SHA256
SHA256 mode.
SHA384
SHA384 mode.
Referenced by XSecure_ShaValidateModeAndCfgInstance.
SHA512
SHA512 mode.
Referenced by XSecure_ShaValidateModeAndCfgInstance.
SHAKE256
SHAKE256 mode.
XSECURE_RSA_KEY_ADDRESS
Address to copy RSA input parameters.
XSECURE_RSA_PRIME_SIZE_DIVISOR
RSA prime factors P and Q are each half the modulus size (N = P × Q)
XSECURE_SSS_ADDRESS
SSS base address.
XSECURE_SSS_MAX_SRCS
SSS Maximum resources.
XSECURE_SSS_SHA3_0_MASK
SSS SHA3 instance 0 mask value.
XSECURE_SSS_SHA3_0_DMA0_VAL
SSS SHA3 instance 0 DMA0 value.
XSECURE_SSS_SHA3_0_DMA1_VAL
SSS SHA3 instance 0 DMA1 value.
XSECURE_AES_NO_CFG_DST_DMA
Not to configure Dst DMA at this address in AES.
XSECURE_ENABLE_BYTE_SWAP
Enables data swap in AES.
XSECURE_DISABLE_BYTE_SWAP
Disables data swap in AES.
XSECURE_SSS_SBI_MASK
SSS SBI mask.
XSECURE_SSS_AES_MASK
SSS AES mask.
XSECURE_SSS_DMA1_MASK
SSS DMA1 mask.
XSECURE_SSS_DMA0_MASK
SSS DMA0 mask.
XSECURE_SSS_SRC_SEL_MASK
SSS Source Select mask.
XSECURE_SSS_SBI_DMA0_VAL
SSS SBI DMA0 value.
XSECURE_SSS_SBI_DMA1_VAL
SSS SBI DMA1 value.
XSECURE_SSS_AES_DMA0_VAL
SSS AES DMA0 value.
XSECURE_SSS_AES_DMA1_VAL
SSS AES DMA1 value.
XSECURE_SSS_ADDRESS
SSS base address.
XSECURE_SSS_MAX_SRCS
Maximum resources.
XSECURE_SSS_SHA3_MASK
SSS SHA3 instance mask value.
XSECURE_SSS_SHA2_MASK
SSS SHA3 instance mask value.
XSECURE_SSS_SHA3_DMA0_VAL
SSS SHA3 instance DMA0 value.
XSECURE_SSS_SHA3_DMA1_VAL
SSS SHA3 instance DMA1 value.
XSECURE_SSS_SHA2_DMA0_VAL
SSS SHA2 instance DMA0 value.
XSECURE_SSS_SHA2_DMA1_VAL
SSS SHA2 instance DMA1 value.
XSECURE_ENABLE_BYTE_SWAP
Enables data swap in AES.
XSECURE_DISABLE_BYTE_SWAP
Disables data swap in AES.
XSECURE_TRNG_USER_CFG_SEED_LIFE
User configuration seed life.
XSECURE_TRNG_USER_CFG_DF_LENGTH
User configuration DF length.
XSECURE_TRNG_USER_CFG_ADAPT_TEST_CUTOFF
Adapt test cutoff.
XSECURE_TRNG_USER_CFG_REP_TEST_CUTOFF
Rep test cutoff.
XSECURE_AES_KTE_GO_ADDRESS
AES KTE GO address.
XSECURE_AES_KTE_RESTART_ADDRESS
AES Key Transfer Engine Restart register.
XSECURE_AES_KTE_DONE_ADDRESS
AES Key Transfer Engine Done.
XSECURE_AES_KTE_CNT_ADDRESS
AES Key Transfer Engine Count address.
XSECURE_AES_KTE_GO_ENABLE
AES KTE GO enable.
XSECURE_AES_KTE_GO_DISABLE
AES KTE GO disable.
XSECURE_AES_KTE_DONE_MASK
AES Key Transfer Engine Done mask.
XSECURE_AES_KTE_CNT_MASK
AES Key Transfer Engine Count value.
XSECURE_AES_KTE_DONE_POLL_TIMEOUT
AES Key Transfer complete poll timeout.
XSECURE_SSS_SBI_MASK
SSS SBI mask.
XSECURE_SSS_AES_MASK
SSS AES mask.
XSECURE_SSS_DMA1_MASK
SSS DMA1 mask.
XSECURE_SSS_DMA0_MASK
SSS DMA0 mask.
XSECURE_SSS_SRC_SEL_MASK
SSS Source Select mask.
XSECURE_SSS_SBI_DMA0_VAL
SSS SBI DMA0 value.
XSECURE_SSS_SBI_DMA1_VAL
SSS SBI DMA1 value.
XSECURE_SSS_AES_DMA0_VAL
SSS AES DMA0 value.
XSECURE_SSS_AES_DMA1_VAL
SSS AES DMA1 value.
XCSUDMA_WORD_SIZE
WORD size.
XSECURE_SHA_512_HASH_LEN
SHA_512 block length.
XSECURE_SHA3_256_HASH_LEN
SHA3_256 block length.
XSECURE_SHA2_256_BLOCK_LEN
SHA2_256 block length.
XSECURE_SHA3_BLOCK_LEN
SHA3 block length.
XSECURE_SHA2_384_BLOCK_LEN
SHA2_384 block length.
XSECURE_SHAKE_256_BLOCK_LEN
SHAKE_256 block length.
XSECURE_SHA3_384_HASH_LEN
SHA3_384 hash length.
XSECURE_SHA2_384_HASH_LEN
SHA2_384 hash length.
XSECURE_SHAKE_256_HASH_LEN
SHAKE_256 hash length.
XSECURE_SHA2_256_HASH_LEN
SHA2_256 hash length.
XSECURE_SHA3_384_HASH_WORD_LEN
SHA3_384 hash word length.
XSECURE_SHA2_384_HASH_WORD_LEN
SHA2_384 hash word length.
XSECURE_SHAKE_256_HASH_WORD_LEN
SHAKE_256 hash word length.
XSECURE_SHA2_256_HASH_WORD_LEN
SHA2_256 hash word length.
SHA256
SHA256 mode.
SHA384
SHA384 mode.
SHA512
SHA512 mode.
SHAKE256
SHAKE256 mode.
SHAKE256_SLH_DSA_CHAIN
SHAKE256 SLH-DSA Chain mode.
Referenced by XSecure_ExtendedShaFinish.
XSECURE_RSA_KEY_ADDRESS
Address to copy RSA input parameters.
XSECURE_AES_ADDRESS
AES BaseAddress.
XSECURE_SHA_ADDRESS
SHA BaseAddress.
XSECURE_RSA_ECDSA_RSA_ADDRESS
RSA ECDSA BaseAddress.
XSECURE_SSS_ADDRESS
SSS base address.
XSECURE_SSS_MAX_SRCS
Maximum resources.
XSECURE_SSS_SHA3_0_MASK
SSS SHA3 instance 0 mask value.
XSECURE_SSS_SHA3_1_MASK
SSS SHA3 instance 1 mask value.
XSECURE_SSS_SHA3_0_DMA0_VAL
SSS SHA3 instance 0 DMA0 value.
XSECURE_SSS_SHA3_0_DMA1_VAL
SSS SHA3 instance 0 DMA1 value.
XSECURE_SSS_SHA3_1_DMA0_VAL
SSS SHA3 instance 1 DMA0 value.
XSECURE_SSS_SHA3_1_DMA1_VAL
SSS SHA3 instance 1 DMA1 value.
XSECURE_AES_NO_CFG_DST_DMA
Not to configure Dst DMA at this address in AES.
XSECURE_ENABLE_BYTE_SWAP
Enables data swap in AES.
XSECURE_DISABLE_BYTE_SWAP
Disables data swap in AES.
XSECURE_AES_ECB_OFFSET
AES ECB offset.
Referenced by XSecure_AesEcbCfg, XSecure_AesEcbDecrypt, XSecure_AesKeyUnwrap.
XSECURE_TRNG_USER_CFG_SEED_LIFE
User configuration seed life.
XSECURE_TRNG_USER_CFG_DF_LENGTH
User configuration DF length.
XSECURE_TRNG_USER_CFG_ADAPT_TEST_CUTOFF
Adapt test cutoff.
XSECURE_TRNG_USER_CFG_REP_TEST_CUTOFF
Rep test cutoff.
XSECURE_SSS_SBI_MASK
SSS SBI mask.
XSECURE_SSS_AES_MASK
SSS AES mask.
XSECURE_SSS_DMA1_MASK
SSS DMA1 mask.
XSECURE_SSS_DMA0_MASK
SSS DMA0 mask.
XSECURE_SSS_SRC_SEL_MASK
SSS Source select mask.
XSECURE_SSS_SBI_DMA0_VAL
SSS SBI DMA0 value.
XSECURE_SSS_SBI_DMA1_VAL
SSS SBI DMA1 value.
XSECURE_SSS_AES_DMA0_VAL
SSS AES DMA0 value.
XSECURE_SSS_AES_DMA1_VAL
SSS AES DMA1 value.
XSECURE_RSA_KEY_ADDRESS
Address to copy RSA input parameters when the provided SyndromeAddr is 64-bit.