xsecure_mailbox_apis
int XSecure_ProcessMailbox(XMailbox *MailboxPtr, u32 *MsgPtr, u32 MsgLen)
This function sends IPI request to the target module and gets the response from it.
MailboxPtr Pointer to XMailbox MsgPtr Pointer to the payload message MsgLen Length of the message XST_SUCCESS If the IPI send and receive is successfulXST_FAILURE If there is a failureResponse received from server Payload consists of API ID and call arguments to be written in IPI buffer
Referenced by XSecure_AesPerformOperationAndZeroizeKey, XSecure_EllipticPrivateKeyGenerate, XSecure_GenSharedSecret, XSecure_KeyUnwrap, XSecure_MldsaSignGenerateClient, XSecure_MldsaSignVerifyClient, XSecure_ReleaseRsaKey, XSecure_SendRequest, XSecure_Sha2Kat, XSecure_Sha2Operation, XSecure_Sha3Operation, XSecure_SlhdsaSignVerifyClient, XSecure_TrngGenerateRandNum, XSecure_TrngKat.
int XSecure_ClientInit(XSecure_ClientInstance *const InstancePtr, XMailbox *const MailboxPtr)
This function sets the instance of mailbox.
InstancePtr Pointer to the client instance MailboxPtr Pointer to the mailbox instance XST_SUCCESS On successful initializationXST_FAILURE On failure
Referenced by main, XSecure_GetAlgInfo.
static int XSecure_SetSlrIndex(XSecure_ClientInstance *InstancePtr, u32 SlrIndex)
This function sets slr index in the Secure client instance.
InstancePtr Pointer to XSecure_ClientInstance SlrIndex Slr index to be set in instance XST_SUCCESS - On valid input SlrIndex.XST_FAILURE - On invalid SlrIndex. This function is applicable to only Versal