xsecure_aes_client_apis
XSecure_AesKeySource
Bbram key.
XSecure_AesKeySize
Key Length = 16 bytes = 128 bits.
void XSecure_AesGetCryptoAlgInfo(Xil_CryptoAlgInfo *AlgInfo)
This function returns the AES crypto algorithm information.
AlgInfo Pointer to memory for holding the crypto algorithm information None
References XSECURE_API_AES_INIT, XSecure_GetAlgInfo.
int XSecure_AesInitialize(XSecure_ClientInstance *InstancePtr)
This function sends IPI request to initialize the AES engine.
InstancePtr Pointer to the client instance XST_SUCCESS If the initialization is successfulXST_FAILURE If there is a failure
Referenced by SecureAesExample, XSecure_AesInit, XSecure_AesShaInit.
int XSecure_AesEncryptInit(XSecure_ClientInstance *InstancePtr, XSecure_AesKeySource KeySrc, u32 Size, u64 IvAddr)
This function sends IPI request to EncryptInit the AES engine.
InstancePtr Pointer to the client instance KeySrc Type of the Key Size Size of the Key IvAddr Address of the IV XST_SUCCESS If the Encrypt init is successfulXST_FAILURE If there is a failure
References XSECURE_ADDR_HIGH_SHIFT, XSECURE_API_AES_OP_INIT, XSecure_DCacheFlushRange, XSECURE_ENCRYPT, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
Referenced by XSecure_AesEncryptData, XSecure_AesEncryptKat.
int XSecure_AesDecryptInit(XSecure_ClientInstance *InstancePtr, XSecure_AesKeySource KeySrc, u32 Size, u64 IvAddr)
This function sends IPI request to DecryptInit the AES engine.
InstancePtr Pointer to the client instance KeySrc Type of the Key Size Size of the Key IvAddr Address of the IV XST_SUCCESS If the Decrypt init is successfulXST_FAILURE If there is a failure
References XSECURE_ADDR_HIGH_SHIFT, XSECURE_API_AES_OP_INIT, XSecure_DCacheFlushRange, XSECURE_DECRYPT, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
Referenced by XSecure_AesDecryptData, XSecure_AesDecryptKat.
int XSecure_AesUpdateAad(XSecure_ClientInstance *InstancePtr, u64 AadAddr, u32 AadSize)
This function sends IPI request to update AAD to AES engine.
InstancePtr Pointer to the client instance AadAddr Address of the Aad AadSize Size of the Aad data XST_SUCCESS If the Aad update is successfulXST_FAILURE If there is a failure
References XSecure_AesGmacUpdateAad.
Referenced by XSecure_AesDecryptKat, XSecure_AesEncryptKat.
int XSecure_AesGmacUpdateAad(XSecure_ClientInstance *InstancePtr, u64 AadAddr, u32 AadSize, u32 IsLastChunkSrc)
This function sends IPI request to update AAD data to AES engine.
InstancePtr Pointer to the client instance AadAddr Address of the Aad AadSize Size of the Aad data IsLastChunkSrc If this is the last update of data, this parameter should be set to TRUE otherwise FALSE XST_SUCCESS If the Aad update is successfulXST_FAILURE If there is a failure To generate GMAC, this API must be called by setting IsLastChunkSrc as TRUE for the last update followed by XSecure_AesEncryptFinal or XSecure_AesDecryptFinal API call to generate or validate GMAC tag
References XSECURE_ADDR_HIGH_SHIFT, XSECURE_API_AES_UPDATE_AAD, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
Referenced by XSecure_AesUpdateAad.
int XSecure_AesEncryptUpdate(XSecure_ClientInstance *InstancePtr, u64 InDataAddr, u64 OutDataAddr, u32 Size, u32 IsLast)
This function sends IPI request to update the input data to AES engine for encryption.
InstancePtr Pointer to the client instance InDataAddr Address of the input data which needs to be encrypted OutDataAddr Address of the buffer where the encrypted data to be updated Size Size of the input data to be encrypted IsLast If this is the last update of data to be encrypted, this parameter should be set to TRUE otherwise FALSE XST_SUCCESS On successful encryption of the dataXST_FAILURE On failure
References XSECURE_ADDR_HIGH_SHIFT, XSECURE_API_AES_ENCRYPT_UPDATE, XSecure_DCacheFlushRange, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
Referenced by XSecure_AesEncryptData, XSecure_AesEncryptKat.
int XSecure_AesEncryptFinal(XSecure_ClientInstance *InstancePtr, u64 GcmTagAddr)
This function sends IPI request to update the GcmTag Addr to AES engine.
InstancePtr Pointer to the client instance GcmTagAddr Address to the buffer of GCM tag size, where the API updates GCM tag XST_SUCCESS On successful encryption of the dataXST_FAILURE On failure
References XSECURE_ADDR_HIGH_SHIFT, XSECURE_API_AES_ENCRYPT_FINAL, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
Referenced by XSecure_AesEncryptKat, XSecure_AesPerformOperation.
int XSecure_AesDecryptUpdate(XSecure_ClientInstance *InstancePtr, u64 InDataAddr, u64 OutDataAddr, u32 Size, u32 IsLast)
This function sends IPI request to update the encrypted data to AES engine for decryption.
InstancePtr Pointer to the client instance InDataAddr Address of the encryped data which needs to be decrypted OutDataAddr Address of the buffer where the decrypted data to be updated Size Size of the input data to be decrypted IsLast If this is the last update of data to be decrypted, this parameter should be set to TRUE otherwise FALSE XST_SUCCESS On successful decryption of the dataXST_FAILURE On failure
References XSECURE_ADDR_HIGH_SHIFT, XSECURE_API_AES_DECRYPT_UPDATE, XSecure_DCacheFlushRange, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
Referenced by XSecure_AesDecryptData, XSecure_AesDecryptKat, XSecure_AesEcbDecrypt, XSecure_AesKeyUnwrap.
int XSecure_AesDecryptFinal(XSecure_ClientInstance *InstancePtr, u64 GcmTagAddr)
This function sends IPI request to verify the GcmTag provided for the data decrypted till the point.
InstancePtr Pointer to the client instance GcmTagAddr Address of a buffer which should holds GCM Tag XST_SUCCESS On successful encryption of the dataXST_FAILURE On failure
References XSECURE_ADDR_HIGH_SHIFT, XSECURE_API_AES_DECRYPT_FINAL, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
Referenced by XSecure_AesDecryptKat, XSecure_AesPerformOperation.
int XSecure_AesKeyZero(XSecure_ClientInstance *InstancePtr, XSecure_AesKeySource KeySrc)
This function sends IPI request to zeroize selected AES key storage register.
InstancePtr Pointer to the client instance KeySrc Select the key source which needs to be zeroized XST_SUCCESS When key zeroization is successXST_FAILURE On failure
References XSECURE_API_AES_KEY_ZERO, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
Referenced by XSecure_AesDecrypt, XSecure_AesDecryptCmKat, XSecure_AesDecryptInit, XSecure_AesDecryptKat, XSecure_AesDecryptUpdate, XSecure_AesEcbDecrypt, XSecure_AesEncryptInit, XSecure_AesEncryptKat, XSecure_AesEncryptUpdate, XSecure_AesKeyUnwrap, XSecure_AesKeyZeroize.
int XSecure_AesWriteKey(XSecure_ClientInstance *InstancePtr, XSecure_AesKeySource KeySrc, u32 Size, u64 KeyAddr)
This function sends IPI request to write the key provided into the specified AES key registers.
InstancePtr Pointer to the client instance KeySrc Key Source to be selected to which provided key should be updated Size Size of the input key to be written KeyAddr Address of a buffer which should contain the key to be written XST_SUCCESS On successful key written on AES registersXST_FAILURE On failure
References XSECURE_ADDR_HIGH_SHIFT, XSECURE_API_AES_WRITE_KEY, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
Referenced by XSecure_AesDecryptKat, XSecure_AesEcbDecrypt, XSecure_AesEncryptKat, XSecure_AesKeyUnwrap, XSecure_AesKeyWrite.
int XSecure_AesKekDecrypt(XSecure_ClientInstance *InstancePtr, u64 IvAddr, XSecure_AesKeySource DstKeySrc, XSecure_AesKeySource DecKeySrc, XSecure_AesKeySize Size)
This function sends IPI request to decrypt the key in KEK key form.
InstancePtr Pointer to the client instance IvAddr Address of IV holding buffer for decryption of the key DecKeySrc Select key source which holds KEK and needs to be decrypted DstKeySrc Select the key in which decrypted red key should be updated Size Size of the key XST_SUCCESS On successful key decryptionXSECURE_AES_INVALID_PARAM On invalid parameterXST_FAILURE If there is a failure
References XSECURE_ADDR_HIGH_SHIFT, XSECURE_AES_INVALID_PARAM, XSECURE_AES_KEY_SIZE_128, XSECURE_API_AES_KEK_DECRYPT, XSECURE_DST_KEY_SRC_SHIFT, XSECURE_KEY_SIZE_SHIFT, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
int XSecure_AesSetDpaCm(XSecure_ClientInstance *InstancePtr, u8 DpaCmCfg)
This function sends IPI request to enable/disable DpaCm in AES.
InstancePtr Pointer to the client instance DpaCmCfg User choice to enable/disable DPA CM XST_SUCCESS If configuration is successXST_FAILURE If there is a failure
References XSECURE_API_AES_SET_DPA_CM, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
int XSecure_AesEncryptData(XSecure_ClientInstance *InstancePtr, XSecure_AesKeySource KeySrc, u32 KeySize, u64 IvAddr, u64 InDataAddr, u64 OutDataAddr, u32 Size, u64 GcmTagAddr)
This function calls IPI request to encrypt a single block of data.
InstancePtr Pointer to the client instance KeySrc Type of the key KeySize Size of the key IvAddr Address of the IV InDataAddr Address of the data which needs to be encrypted OutDataAddr Address of output buffer where the encrypted data to be updated Size Size of data to be encrypted in bytes where number of bytes provided should be multiples of 4 GcmTagAddr Address to the buffer of GCM tag XST_SUCCESS On successXST_FAILURE On failure
References XSECURE_ADDR_HIGH_SHIFT, XSECURE_API_AES_PERFORM_OPERATION, XSecure_DCacheFlushRange, XSECURE_ENCRYPT, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
Referenced by XSecure_AesPerformOperation.
int XSecure_AesDecryptData(XSecure_ClientInstance *InstancePtr, XSecure_AesKeySource KeySrc, u32 KeySize, u64 IvAddr, u64 InDataAddr, u64 OutDataAddr, u32 Size, u64 GcmTagAddr)
This function calls IPI request to decrypt a single block of data.
InstancePtr Pointer to the client instance KeySrc Type of the key KeySize Size of the key IvAddr Address of the IV InDataAddr Address of the encrypted data which needs to be decrypted OutDataAddr Address of buffer where the decrypted data to be updated Size Size of input data to be decrypted GcmTagAddr Address to the buffer of GCM tag XST_SUCCESS On successXST_FAILURE On failure
References XSECURE_ADDR_HIGH_SHIFT, XSECURE_API_AES_PERFORM_OPERATION, XSecure_DCacheFlushRange, XSECURE_DECRYPT, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
Referenced by XSecure_AesPerformOperation.
int XSecure_AesPerformOperation(const XSecure_ClientInstance *InstancePtr, const XSecure_AesDataBlockParams *AesDataParams)
This function calls IPI request to encrypt/decrypt a single block of data along with update AAD/GMAC based on the user's choice.
InstancePtr Pointer to the client instance AesDataParams Pointer to the Aes parameters XST_SUCCESS On successXSECURE_AES_INVALID_PARAM On invalid parameterXST_FAILURE On failure
References XSecure_AesDataBlockParams::AadAddr, XSecure_AesDataBlockParams::AadSize, XSecure_AesDataBlockParams::GcmTagAddr, XSecure_AesDataBlockParams::InDataAddr, XSecure_AesDataBlockParams::IsGmacEnable, XSecure_AesDataBlockParams::IsUpdateAadEn, XSecure_AesDataBlockParams::IvAddr, XSecure_AesDataBlockParams::KeySize, XSecure_AesDataBlockParams::KeySrc, XSecure_AesDataBlockParams::OperationId, XSecure_AesDataBlockParams::OutDataAddr, XSecure_AesDataBlockParams::Size, XSECURE_ADDR_HIGH_SHIFT, XSECURE_AES_INVALID_PARAM, XSECURE_API_AES_PERFORM_OPERATION, XSecure_DCacheFlushRange, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
Referenced by XSecure_AesIpiHandler.
int XSecure_AesPerformOperationAndZeroizeKey(XSecure_ClientInstance *InstancePtr, u64 KeyAddr, const XSecure_AesDataBlockParams *AesDataParams)
This function calls IPI request to perform below operation:
- Write key into the key source provided by the user - Encrypt/decrypt a single block of data using the provided key - Zeroize the key once the AES operation is done InstancePtr Pointer to the XSecure_ClientInstance KeyAddr Address of the key to be used for AES operation AesDataParams Pointer to the XSecure_AesDataBlockParams structure variable XST_SUCCESS On successXST_FAILURE On failure
References XSecure_AesDataBlockParams::AadAddr, XSecure_AesDataBlockParams::AadSize, XSecure_AesDataBlockParams::GcmTagAddr, XSecure_AesDataBlockParams::InDataAddr, XSecure_AesDataBlockParams::IsGmacEnable, XSecure_AesDataBlockParams::IsUpdateAadEn, XSecure_AesDataBlockParams::IvAddr, XSecure_AesDataBlockParams::KeySize, XSecure_AesDataBlockParams::KeySrc, XSecure_AesDataBlockParams::OperationId, XSecure_AesDataBlockParams::OutDataAddr, XSecure_AesDataBlockParams::Size, XSECURE_ADDR_HIGH_SHIFT, XSECURE_API_AES_PERFORM_OPERATION_AND_ZEROIZE_KEY, XSecure_DCacheFlushRange, XSecure_ProcessMailbox.
Referenced by XSecure_PlatAesIpiHandler.
XSECURE_SLR_INDEX_SHIFT
SLR index shift.
Referenced by XSecure_AesDecryptCmKat, XSecure_AesDecryptData, XSecure_AesDecryptFinal, XSecure_AesDecryptInit, XSecure_AesDecryptKat, XSecure_AesDecryptUpdate, XSecure_AesEncryptData, XSecure_AesEncryptFinal, XSecure_AesEncryptInit, XSecure_AesEncryptKat, XSecure_AesEncryptUpdate, XSecure_AesGmacUpdateAad, XSecure_AesKekDecrypt, XSecure_AesKeyZero, XSecure_AesPerformOperation, XSecure_AesSetDpaCm, XSecure_AesWriteKey, XSecure_EllipticGenerateKey, XSecure_EllipticGenerateSign, XSecure_EllipticSignGenKat, XSecure_EllipticSignVerifyKat, XSecure_EllipticValidateKey, XSecure_EllipticVerifySign, XSecure_MldsaSignGenerateClient, XSecure_MldsaSignVerifyClient, XSecure_RsaPrivateDecKat, XSecure_RsaPrivateDecrypt, XSecure_RsaPublicEncKat, XSecure_RsaPublicEncrypt, XSecure_RsaSignVerification, XSecure_Sha2Kat, XSecure_Sha3Digest, XSecure_Sha3Finish, XSecure_Sha3Kat, XSecure_Sha3Update, XSecure_SlhdsaSignVerifyClient.
XSECURE_KEY_SIZE_SHIFT
Key size shift constant.
Referenced by XSecure_AesKekDecrypt.
XSECURE_DST_KEY_SRC_SHIFT
Destination key source shift constant.
Referenced by XSecure_AesKekDecrypt.
XSECURE_AES_INVALID_PARAM
Invalid Argument for AES.
Referenced by XSecure_AesCfgKupKeyNIv, XSecure_AesEcbCfg, XSecure_AesEncryptUpdate, XSecure_AesGetNxtBlkLen, XSecure_AesGmacCfg, XSecure_AesInitialize, XSecure_AesKekDecrypt, XSecure_AesKeyWrite, XSecure_AesKeyZero, XSecure_AesKeyZeroize, XSecure_AesPerformOperation, XSecure_AesPlatPmcDmaCfgAndXfer, XSecure_AesSetDpaCm, XSecure_AesUpdateAadAndValidate, XSecure_AesWriteKey.