xsecure_trng_server_apis
XSecureTrng_Mode
HRNG mode for TRNG.
XSecureTrng_Mode
HRNG mode for TRNG.
typedef XTrngpsv XSecure_TrngInstance
typedef XTrngpsv as XSecure_TrngInstance for compatibility
typedef XTrngpsx_Instance XSecure_TrngInstance
typedef XTrngpsx_Instance as XSecure_TrngInstance for compatibility
XSecure_TrngInstance * XSecure_GetTrngInstance(void)
This function provides the pointer to the common trng instance.
Pointer to the XSecure_TrngInstance instance
Referenced by XSecure_ECCRandInit, XSecure_EllipticPrvtKeyGenerate, XSecure_GetRandomNum.
int XSecure_TrngInitNCfgMode(int XSecureTrngMode, u8 *Seed, u32 SeedLength, u8 *PersStr)
This function initialize and configures the TRNG into DRNG/HRNG mode of operation.
XST_SUCCESS - Upon success.XST_FAILURE - On failure. XSecureTrngMode Trng Mode of operation Seed Holds the address of Seed buffer SeedLength Holds size Seed PersStr Personalization string XST_SUCCESS - Upon success.XST_FAILURE - On failure.
Referenced by XSecure_ECCRandInit, XSecure_EllipticPrvtKeyGenerate.
int XSecure_PreOperationalSelfTests(XSecure_TrngInstance *TrngInstance)
This function runs preoperational self tests and updates TRNG error state.
TrngInstance Pointer to XTrngpsv Instance. XST_SUCCESS - On successXST_FAILURE - On failure
Referenced by XSecure_ECCRandInit.
static u8 XSecure_TrngIsUninitialized(XSecure_TrngInstance *TrngInstance)
This is a wrapper function to check trngpsv initialization status.
TrngInstance Pointer to XTrngpsv instance. XST_SUCCESS If TRNGPSV is not initialized.XST_FAILURE If TRNGPSV is initialized.
static u8 XSecure_TrngIsHealthy(XSecure_TrngInstance *TrngInstance)
This is a wrapper function to check trngpsv health status.
TrngInstance Pointer to XTrngpsv instance. XST_SUCCESS If status of TRNGPSV is healthy.XST_FAILURE If status of TRNGPSV is not healthy.
static int XSecure_TrngGenerate(XSecure_TrngInstance *TrngInstance, u8 *RandBuf, u32 RandBufSize, u8 PredResistance)
This wrapper to generate random bits.
TrngInstance Pointer to the XTrngpsv instance. RandBuf Pointer to memory address where generated random data will be stored and the memory address should be word aligned. RandBufSize Size of the buffer to which RandBufPtr points to and it should be always greater than or equal to XTRNGPSV_SEC_STRENGTH_BYTES. PredResistance Flag that controls Generate level Prediction Resistance. When enabled, it mandates fresh seed for every Generate operation. XST_SUCCESS On success.ErrorCode On failure.
static int XSecure_TrngGenerateRandNum(u32 SrcAddrLow, u32 SrcAddrHigh, u32 Size)
This function handler extracts the payload params with respect to XSECURE_API_TRNG_GENERATE IPI command and calls XSecure_GetRandomNum server API to generate random number.
SrcAddrLow Lower 32 bit address of the random data buffer address. SrcAddrHigh Higher 32 bit address of the random data buffer address. Size Number of random bytes needs to be generated. XST_SUCCESS If the generate is successful.XST_FAILURE If there is a failure.
int XSecure_TrngIpiHandler(XPlmi_Cmd *Cmd)
This function calls respective IPI handler based on the API_ID.
Cmd Pointer to the command structure. XST_SUCCESS If the handler execution is successful.XST_INVALID_PARAM If any input parameter is invalid.XST_FAILURE If there is a failure. Cmd is a pointer to the command structure XST_SUCCESS - If the handler execution is successfulXST_INVALID_PARAM - If any input parameter is invalidXST_FAILURE - If there is a failure
References XSECURE_API, XSECURE_API_ID_MASK, XSECURE_API_TRNG_GENERATE, XSecure_TrngGenerateRandNum.
XSECURE_ECC_TRNG_DF_LENGTH
Default length of xilsecure ecc true random number generator.
XTRNGPSV_USER_CFG_DF_LENGTH
Default multiplier used to determine num of bits on the input of the DF construct.
XSECURE_TRNG_SEC_STRENGTH_IN_BYTES
Security strength in bytes for XTRNGPSV.
XSECURE_TRNG_PER_STRING_LEN_IN_BYTES
Personalization string length in bytes for XTRNGPSV.
XSECURE_TRNG_USER_CFG_SEED_LIFE
User config Seed life.
XSecure_Uninstantiate
Redefine XTrngpsv_Uninstantiate as XSecure_Uninstantiate for compatibility.
Referenced by XSecure_EllipticPrvtKeyGenerate, XSecure_GetRandomNum.
XSECURE_ECC_TRNG_DF_LENGTH
Default length of xilsecure ecc true random number generator.
XSECURE_TRNG_SEC_STRENGTH_IN_BYTES
Security strength in bytes for XTRNGPSX.
XSECURE_TRNG_PER_STRING_LEN_IN_BYTES
Personalization string length in bytes for XTRNGPSX.
XSecure_PreOperationalSelfTests
Redefine XTrngpsx_PreOperationalSelfTests as XSecure_PreOperationalSelfTests for compatibility.
XSecure_TrngGenerate
Redefine XTrngpsx_Generate as XSecure_TrngGenerate for compatibility.
Referenced by XSecure_EllipticPrvtKeyGenerate.
XSecure_Uninstantiate
Redefine XTrngpsx_Uninstantiate as XSecure_Uninstantiate for compatibility.