xsecure_ecdsa_server_apis
XSECURE_ECC_SUPPORT_NIST_P384
< Macros to enable /disable support of NIST P-384 curve
const u8 XSecure_EllipticNistP384_d0[][]
const u8 XSecure_EllipticNistP384_d1[][]
const u8 XSecure_EllipticNistP384_d2[][]
const u8 XSecure_EllipticNistP384_d3[][]
const u8 XSecure_EllipticNistP384_d4[][]
const u8 XSecure_EllipticNistP384_d5[][]
const u8 XSecure_EllipticNistP384_d6[][]
const u8 XSecure_EllipticNistP384_d7[][]
const u8 XSecure_EllipticNistP384_d8[][]
const u8 XSecure_EllipticNistP384_d9[][]
const u8 XSecure_EllipticNistP384_d10[][]
const u8 XSecure_EllipticNistP384_d11[][]
const u8 XSecure_EllipticNistP384_d12[][]
const u8 XSecure_EllipticNistP384_d13[][]
EcdsaCrvInfo XSecure_EllipticCrvsDb[][]
EcdsaCrvInfo XSecure_EllipticCrvsDb[][]
EcdsaCrvInfo * XSecure_EllipticGetCrvData(XSecure_EllipticCrvTyp CrvTyp)
This function gets the curve related information.
CrvTyp Type of the elliptic curve Crv Curve information
References XSECURE_ECC_NIST_P192, XSECURE_ECC_NIST_P224, XSECURE_ECC_NIST_P256, XSECURE_ECC_NIST_P384, XSECURE_ECC_NIST_P521, XSecure_EllipticCrvsGetCount.
Referenced by XSecure_EcdhGetSecret, XSecure_EllipticGenerateEphemeralKey, XSecure_EllipticGetCrvSize, XSecure_EllipticPrvtKeyGenerate.
int XSecure_EllipticPrvtKeyGenerate(XSecure_EllipticCrvTyp CrvType, XSecure_ElliptcPrivateKeyGen *PrivateKey)
This function generates 48-byte key for P-384 curve using TRNG.
CrvType specifies the type of the ECC curve. PrivateKey is the pointer to XSecure_ElliptcPrivateKeyGen XST_SUCCESS - On successXSECURE_ELLIPTIC_INVALID_PARAM - If any input parameter is invalidXST_FAILURE - On failure This API expects TRNG HW to be in HEALTHY state, This can be achieved by running preoperational health tests.
References XSecure_ElliptcPrivateKeyGen::KeyOutPutAddr, XSecure_ElliptcPrivateKeyGen::PerStringAddr, XSecure_ElliptcPrivateKeyGen::SeedAddr, XSecure_ElliptcPrivateKeyGen::SeedLength, XSECURE_CLEAR_BIT, XSECURE_ECC_NIST_P384, XSECURE_ECC_NIST_P521, XSECURE_ECC_P384_SIZE_IN_BYTES, XSECURE_ECC_PRVT_KEY_GEN_ERR, XSECURE_ECC_TRNG_RANDOM_NUM_GEN_LEN, XSECURE_ECDSA_RSA_BASEADDR, XSECURE_ECDSA_RSA_RESET_OFFSET, XSECURE_ELLIPTIC_INVALID_PARAM, XSecure_EllipticGetCrvData, XSecure_GetData, XSecure_GetTrngInstance, XSecure_ReleaseReset, XSecure_SetReset, XSECURE_TRNG_DRNG_MODE, XSECURE_TRNG_SEC_STRENGTH_IN_BYTES, XSecure_TrngGenerate, XSecure_TrngInitNCfgMode, XSecure_Uninstantiate, XSecure_UpdateTrngCryptoStatus.
int XSecure_EllipticGenerateEphemeralKey(XSecure_EllipticCrvTyp CrvType, u32 EphemeralKeyAddr)
This function generates 48-byte ephemeral key for P-384 curve using TRNG.
CrvType Specifies the type of the ECC curve. EphemeralKeyAddr Address of ephemeral key XST_SUCCESS - On successXSECURE_ELLIPTIC_INVALID_PARAM - If any input parameter is invalidXST_FAILURE - On failure This API expects TRNG HW to be in HEALTHY state, This can be achieved by running preoperational health tests.
References XSECURE_ECC_NIST_P384, XSECURE_ECC_NIST_P521, XSECURE_ECC_P384_SIZE_IN_BYTES, XSECURE_ECC_PRVT_KEY_GEN_ERR, XSECURE_ECC_TRNG_RANDOM_NUM_GEN_LEN, XSECURE_ECDSA_RSA_BASEADDR, XSECURE_ECDSA_RSA_RESET_OFFSET, XSECURE_ELLIPTIC_INVALID_PARAM, XSecure_EllipticGetCrvData, XSecure_GetData, XSecure_GetRandomNum, XSecure_ReleaseReset, XSecure_SetReset.
Referenced by XSecure_EllipticGenEphemeralNSign.
int XSecure_EllipticGenEphemeralNSign(XSecure_EllipticCrvTyp CrvType, const u8 *Hash, u32 HashLen, u8 *PrvtKey, u8 *Signature)
This function generates the signature on provided hash using ecc.
CrvType specifies the type of the ECC curve. Hash is the pointer to the hash of the data to be signed HashLen is the length of the hash. PrvtKey is the pointer to ECC private key. Signature is the pointer to the buffer where the ECC signature shall be stored. XST_SUCCESS - On successXSECURE_ELLIPTIC_INVALID_PARAM - If any input parameter is invalidXST_FAILURE - On failure
References XSECURE_ECC_NIST_P521, XSECURE_ECC_P384_SIZE_IN_BYTES, XSECURE_ELLIPTIC_INVALID_PARAM, XSecure_EllipticGenerateEphemeralKey, XSecure_EllipticGenerateSignature.
int XSecure_EcdhGetSecret(XSecure_EllipticCrvTyp CrvType, u64 PrvtKeyAddr, u64 PubKeyAddr, u64 SharedSecretAddr)
This is a wrapper function which calls the third-party API to perform ECDH and generate shared secret.
CrvType Curve Type of the keys used to generate shared secret PrvtKeyAddr 64-bit address of the private key PubKeyAddr 64-bit address of public key SharedSecretAddr 64-bit address of buffer for storing shared secret XST_SUCCESS - On successXSECURE_ELLIPTIC_INVALID_PARAM - If any input parameter is invalidXSECURE_ELLIPTIC_NON_SUPPORTED_CRV - If elliptic curve data received is NULLXST_FAILURE - On failure Shared secret is calculated by performing scalar multiplication on public key and private key provided as input.
References XSecure_EllipticKeyAddr::Qx, XSecure_EllipticKeyAddr::Qy, XSECURE_CORE_RSA_ECC, XSecure_CryptoCheck, XSECURE_ECC_NIST_P256, XSECURE_ECC_NIST_P384, XSECURE_ECC_NIST_P521, XSECURE_ECC_P256_SIZE_IN_BYTES, XSECURE_ECC_P384_SIZE_IN_BYTES, XSECURE_ECC_P521_SIZE_IN_BYTES, XSecure_ECCRandInit, XSECURE_ECDSA_P521_ALIGN_BYTES, XSECURE_ECDSA_RSA_BASEADDR, XSECURE_ECDSA_RSA_RESET_OFFSET, XSECURE_ELLIPTIC_INVALID_PARAM, XSecure_EllipticGetCrvData, XSecure_GetData, XSecure_PutData, XSecure_ReleaseReset, XSecure_SetReset.
static int XSecure_GenSharedSecret(u32 SrcAddrLow, u32 SrcAddrHigh)
This function handler extracts the payload params with respect to XSECURE_API_GEN_SHARED_SECRET IPI command and calls XSecure_EcdhGetSecret server API to generate the shared secret using ECDH.
SrcAddrLow Lower 32 bit address of the EcdhParams structure from client SrcAddrHigh Upper 32 bit address of the EcdhParams structure from client XST_SUCCESS - On SuccessXST_FAILURE - On failure
static int XSecure_EllipticPrivateKeyGen(u32 SubsystemId, u32 SrcAddrLow, u32 SrcAddrHigh, u32 ParamsSize)
This function performs Elliptic private key generation.
SubsystemId Subsystem ID. SrcAddrLow Lower 32 bit address of the XSecure_EccPrivateKeyParams structure. SrcAddrHigh Higher 32 bit address of the XSecure_EccPrivateKeyParams structure. ParamsSize Size in bytes of the XSecure_EccPrivateKeyParams structure as reported by the client. XST_SUCCESS On Success.XSECURE_ELLIPTIC_INVALID_PARAM If ParamsSize is invalid.XST_FAILURE On failure.
int XSecure_PlatEllipticIpiHandler(XPlmi_Cmd *Cmd)
This function calls respective IPI handler based on the API_ID.
Cmd is a pointer to the command structure XST_SUCCESS - If the handler execution is successfulXST_INVALID_PARAM - If any parameter is invalid.XST_FAILURE - If there is a failure
static u32 XSecure_EllipticValidateAndGetCrvInfo(XSecure_EllipticCrvTyp CrvType, EcdsaCrvInfo **Crv)
This function validates and gets curve info and curve size in bytes.
CrvType Is a type of elliptic curve Crv Pointer to EcdsaCrvInfo CrvSize Size of curve in bytes
int XSecure_EllipticGenerateKey_64Bit(XSecure_EllipticCrvTyp CrvType, const u64 DAddr, const XSecure_EllipticKeyAddr *KeyAddr)
This function generates Public Key for a given curve type using private key where both keys located at 64 bit address.
CrvType Is a type of elliptic curve DAddr Address of static private key KeyAddr Pointer to public key address XST_SUCCESS - On successXSECURE_ELLIPTIC_NON_SUPPORTED_CRV - When elliptic Curve is not supportedXSECURE_ELLIPTIC_INVALID_PARAM - On invalid argumentXSECURE_ELLIPTIC_GEN_KEY_ERR - Error in generating Public key
References XSecure_EllipticKeyAddr::Qx, XSecure_EllipticKeyAddr::Qy, XSECURE_CORE_RSA_ECC, XSecure_CryptoCheck, XSECURE_ECC_NIST_P521, XSECURE_ECC_P521_SIZE_IN_BYTES, XSecure_ECCRandInit, XSECURE_ECDSA_P521_ALIGN_BYTES, XSECURE_ECDSA_RSA_BASEADDR, XSECURE_ECDSA_RSA_RESET_OFFSET, XSECURE_ELLIPTIC_GEN_KEY_ERR, XSECURE_ELLIPTIC_INVALID_PARAM, XSecure_GetData, XSecure_PutData, XSecure_ReleaseReset, XSecure_SetReset.
Referenced by XSecure_EllipticGenerateKey.
int XSecure_EllipticGenerateKey(XSecure_EllipticCrvTyp CrvType, const u8 *D, const XSecure_EllipticKey *Key)
This function generates Public Key for a given curve type.
CrvType Is a type of elliptic curve D Pointer to static private key Key Pointer to public key XST_SUCCESS - On successXSECURE_ELLIPTIC_NON_SUPPORTED_CRV - When elliptic Curve is not supportedXSECURE_ELLIPTIC_INVALID_PARAM - On invalid argument
References XSecure_EllipticKey::Qx, XSecure_EllipticKeyAddr::Qx, XSecure_EllipticKey::Qy, XSecure_EllipticKeyAddr::Qy, XSECURE_ECC_NIST_P192, XSECURE_ECC_NIST_P224, XSECURE_ECC_NIST_P256, XSECURE_ECC_NIST_P384, XSECURE_ECC_NIST_P521, XSECURE_ELLIPTIC_INVALID_PARAM, XSecure_EllipticGenerateKey_64Bit.
int XSecure_EllipticGenerateSignature_64Bit(XSecure_EllipticCrvTyp CrvType, const XSecure_EllipticHashData *HashInfo, const u64 DAddr, const u64 KAddr, const XSecure_EllipticSignAddr *SignAddr)
This function generates signature for a given hash and curve type where data is located at 64-bit address.
CrvType Type of elliptic curve HashInfo Pointer to Hash Data i.e. Hash Address and length DAddr Address of the static private key KAddr Ephemeral private key SignAddr Pointer to signature address XST_SUCCESS - On successXSECURE_ELLIPTIC_INVALID_PARAM - On invalid argumentXSECURE_ELLIPTIC_NON_SUPPORTED_CRV - If curve data pointer is NULLXSECURE_ELLIPTIC_GEN_SIGN_BAD_RAND_NUM - When Bad random number used for sign generationXSECURE_ELLIPTIC_GEN_SIGN_INCORRECT_HASH_LEN Incorrect hash length for sign generationXST_FAILURE - On any other failures K, the ephemeral private key, shall be an unpredictable (cryptographically secure) random number unique for each signature Note that reuse or external predictability of this number generally breaks the security of ECDSA
References XSecure_EllipticHashData::Addr, EcdsaCrvInfo::Bits, XSecure_EllipticHashData::Len, XSecure_EllipticSignAddr::SignR, XSecure_EllipticSignAddr::SignS, XSECURE_CORE_RSA_ECC, XSecure_CryptoCheck, XSECURE_ECC_NIST_P521, XSECURE_ECC_P521_SIZE_IN_BYTES, XSecure_ECCRandInit, XSECURE_ECDSA_P521_ALIGN_BYTES, XSECURE_ECDSA_RSA_BASEADDR, XSECURE_ECDSA_RSA_RESET_OFFSET, XSECURE_ELLIPTIC_GEN_SIGN_BAD_RAND_NUM, XSECURE_ELLIPTIC_GEN_SIGN_INCORRECT_HASH_LEN, XSECURE_ELLIPTIC_INVALID_PARAM, XSecure_GetData, XSecure_PutData, XSecure_ReleaseReset, XSecure_SetReset.
Referenced by XSecure_EllipticGenerateSignature, XSecure_EllipticPwct.
int XSecure_EllipticGenerateSignature(XSecure_EllipticCrvTyp CrvType, const u8 *Hash, const u32 HashLen, const u8 *D, const u8 *K, const XSecure_EllipticSign *Sign)
This function generates signature for a given hash and curve type.
CrvType Type of elliptic curve Hash Pointer to the hash for which sign has to be generated HashLen Length of the hash in bytes D Pointer to the static private key K Ephemeral private key Sign Pointer to the signature XST_SUCCESS - On successXSECURE_ELLIPTIC_INVALID_PARAM - On invalid argument K, the ephemeral private key, shall be an unpredictable (cryptographically secure) random number unique for each signature Note that reuse or external predictability of this number generally breaks the security of ECDSA
References XSecure_EllipticHashData::Addr, XSecure_EllipticHashData::Len, XSecure_EllipticSign::SignR, XSecure_EllipticSignAddr::SignR, XSecure_EllipticSign::SignS, XSecure_EllipticSignAddr::SignS, XSECURE_ECC_NIST_P192, XSECURE_ECC_NIST_P224, XSECURE_ECC_NIST_P256, XSECURE_ECC_NIST_P384, XSECURE_ECC_NIST_P521, XSECURE_ECC_P521_SIZE_IN_BYTES, XSECURE_ELLIPTIC_INVALID_PARAM, XSecure_EllipticGenerateSignature_64Bit.
Referenced by XSecure_EllipticGenEphemeralNSign, XSecure_EllipticSignGenerateKat, XSecure_TestP384.
int XSecure_EllipticValidateKey_64Bit(XSecure_EllipticCrvTyp CrvType, const XSecure_EllipticKeyAddr *KeyAddr)
This function validates the public key for a given curve type where key is located at 64-bit address.
CrvType Type of elliptic curve KeyAddr Pointer to public key address XST_SUCCESS - On successXSECURE_ELLIPTIC_INVALID_PARAM - On invalid argumentXSECURE_ELLIPTIC_NON_SUPPORTED_CRV - If curve data pointer is NULLXSECURE_ELLIPTIC_KEY_ZERO - When Public key is zeroXSECURE_ELLIPTIC_KEY_WRONG_ORDER Wrong order of Public keyXSECURE_ELLIPTIC_KEY_NOT_ON_CRV - When Key is not found on the curveXST_FAILURE - On any other failures
References XSecure_EllipticKeyAddr::Qx, XSecure_EllipticKeyAddr::Qy, XSECURE_CORE_RSA_ECC, XSecure_CryptoCheck, XSECURE_ECC_NIST_P521, XSECURE_ECC_P521_SIZE_IN_BYTES, XSECURE_ECDSA_P521_ALIGN_BYTES, XSECURE_ECDSA_RSA_BASEADDR, XSECURE_ECDSA_RSA_RESET_OFFSET, XSECURE_ELLIPTIC_INVALID_PARAM, XSECURE_ELLIPTIC_KEY_NOT_ON_CRV, XSECURE_ELLIPTIC_KEY_WRONG_ORDER, XSECURE_ELLIPTIC_KEY_ZERO, XSecure_PutData, XSecure_ReleaseReset, XSecure_SetReset.
Referenced by XSecure_EllipticValidateKey.
int XSecure_EllipticValidateKey(XSecure_EllipticCrvTyp CrvType, const XSecure_EllipticKey *Key)
This function validates the public key for a given curve type.
CrvType Type of elliptic curve Key Pointer to the public key XST_SUCCESS - On successXSECURE_ELLIPTIC_INVALID_PARAM - On invalid argument
References XSecure_EllipticKey::Qx, XSecure_EllipticKeyAddr::Qx, XSecure_EllipticKey::Qy, XSecure_EllipticKeyAddr::Qy, XSECURE_ECC_NIST_P192, XSECURE_ECC_NIST_P224, XSECURE_ECC_NIST_P256, XSECURE_ECC_NIST_P384, XSECURE_ECC_NIST_P521, XSECURE_ELLIPTIC_INVALID_PARAM, XSecure_EllipticValidateKey_64Bit.
int XSecure_EllipticVerifySign_64Bit(XSecure_EllipticCrvTyp CrvType, const XSecure_EllipticHashData *HashInfo, const XSecure_EllipticKeyAddr *KeyAddr, const XSecure_EllipticSignAddr *SignAddr)
This function verifies the signature for a given hash, key and curve type where data is located at 64-bit address.
CrvType Type of elliptic curve HashInfo Pointer to Hash Data i.e. Hash Address and length KeyAddr Pointer to public key address SignAddr Pointer to signature address XST_SUCCESS - On successXSECURE_ELLIPTIC_INVALID_PARAM - On invalid argumentXSECURE_ELLIPTIC_NON_SUPPORTED_CRV - If curve data pointer is NULLXSECURE_ELLIPTIC_BAD_SIGN - When signature provided for verification is badXSECURE_ELLIPTIC_VER_SIGN_INCORRECT_HASH_LEN Incorrect hash length for sign verificationXSECURE_ELLIPTIC_VER_SIGN_R_ZERO R set to zeroXSECURE_ELLIPTIC_VER_SIGN_S_ZERO S set to zeroXSECURE_ELLIPTIC_VER_SIGN_R_ORDER_ERROR R is not within ECC orderXSECURE_ELLIPTIC_VER_SIGN_S_ORDER_ERROR S is not within ECC orderXST_FAILURE - On any other failures
References XSecure_EllipticHashData::Addr, EcdsaCrvInfo::Bits, XSecure_EllipticHashData::Len, XSecure_EllipticKeyAddr::Qx, XSecure_EllipticKeyAddr::Qy, XSecure_EllipticSignAddr::SignR, XSecure_EllipticSignAddr::SignS, XSECURE_CORE_RSA_ECC, XSecure_CryptoCheck, XSECURE_ECC_NIST_P521, XSECURE_ECC_P521_SIZE_IN_BYTES, XSECURE_ECDSA_P521_ALIGN_BYTES, XSECURE_ECDSA_RSA_BASEADDR, XSECURE_ECDSA_RSA_RESET_OFFSET, XSECURE_ELLIPTIC_BAD_SIGN, XSECURE_ELLIPTIC_INVALID_PARAM, XSECURE_ELLIPTIC_VER_SIGN_INCORRECT_HASH_LEN, XSECURE_ELLIPTIC_VER_SIGN_R_ORDER_ERROR, XSECURE_ELLIPTIC_VER_SIGN_R_ZERO, XSECURE_ELLIPTIC_VER_SIGN_S_ORDER_ERROR, XSECURE_ELLIPTIC_VER_SIGN_S_ZERO, XSecure_PutData, XSecure_ReleaseReset, XSecure_SetReset.
Referenced by XSecure_EllipticPwct, XSecure_EllipticVerifySign.
int XSecure_EllipticVerifySign(XSecure_EllipticCrvTyp CrvType, const u8 *Hash, const u32 HashLen, const XSecure_EllipticKey *Key, const XSecure_EllipticSign *Sign)
This function verifies the signature for a given hash, key and curve type.
CrvType Type of elliptic curve Hash Pointer to the hash for which sign has to be generated HashLen Length of hash in bytes Key Pointer to the public key Sign Pointer to the signature XST_SUCCESS - On successXSECURE_ELLIPTIC_INVALID_PARAM - On invalid argument
References XSecure_EllipticHashData::Addr, XSecure_EllipticHashData::Len, XSecure_EllipticKey::Qx, XSecure_EllipticKeyAddr::Qx, XSecure_EllipticKey::Qy, XSecure_EllipticKeyAddr::Qy, XSecure_EllipticSign::SignR, XSecure_EllipticSignAddr::SignR, XSecure_EllipticSign::SignS, XSecure_EllipticSignAddr::SignS, XSECURE_ECC_NIST_P192, XSECURE_ECC_NIST_P224, XSECURE_ECC_NIST_P256, XSECURE_ECC_NIST_P384, XSECURE_ECC_NIST_P521, XSECURE_ECC_P521_SIZE_IN_BYTES, XSECURE_ELLIPTIC_INVALID_PARAM, XSecure_EllipticVerifySign_64Bit.
void XSecure_PutData(const u32 Size, u8 *Dst, const u64 SrcAddr)
This function copies data from 32/64 bit address to local buffer.
Size Length of data in bytes Dst Pointer to the destination buffer SrcAddr Source address
References XSECURE_ELLIPTIC_LITTLE_ENDIAN.
Referenced by XSecure_EcdhGetSecret, XSecure_EllipticGenerateKey_64Bit, XSecure_EllipticGenerateSignature_64Bit, XSecure_EllipticValidateKey_64Bit, XSecure_EllipticVerifySign_64Bit.
void XSecure_GetData(const u32 Size, const u8 *Src, const u64 DstAddr)
This function copies data to 32/64 bit address from local buffer.
Size Length of data in bytes Src Pointer to the source buffer DstAddr Destination address
References XSECURE_ELLIPTIC_LITTLE_ENDIAN.
Referenced by XSecure_EcdhGetSecret, XSecure_EllipticGenerateEphemeralKey, XSecure_EllipticGenerateKey_64Bit, XSecure_EllipticGenerateSignature_64Bit, XSecure_EllipticPrvtKeyGenerate.
void XSecure_FixEndiannessNCopy(const u32 Size, u64 DstAddr, const u64 SrcAddr)
This function copies data to destination based on library endianness selection.
- Changes the endianness when library is operating in little endian - Copies data without changing any endianness when library is operating in big endain. Size Length of data in bytes SrcAddr Address of the source buffer DstAddr Destination address This is the helper function to convert the endianness as required.
References XSECURE_ELLIPTIC_LITTLE_ENDIAN.
u32 XSecure_EllipticGetCrvSize(const XSecure_EllipticCrvTyp CrvType)
This function gets curve size in bytes.
CrvType Is a type of elliptic curve CrvSize Size of curve in bytes
References EcdsaCrvInfo::Bits, XSECURE_ECDSA_ALGN_CRV_SIZE_IN_BYTES, XSECURE_ECDSA_BITS_IN_BYTES, XSecure_EllipticGetCrvData.
static int XSecure_EllipticGenKey(u32 SubsystemId, u32 CurveType, u32 SrcAddrLow, u32 SrcAddrHigh, u32 DstAddrLow, u32 DstAddrHigh)
This function handler extracts the payload params from the IPI command and calls XSecure_EllipticGenerateKey server API.
SubsystemId Subsystem ID. CurveType Is a type of elliptic curve SrcAddrLow Lower 32 bit address of the static private key SrcAddrHigh Higher 32 bit address of the static private key DstAddrLow Lower 32 bit address of the public key to be stored DstAddrHigh Higher 32 bit address of the public key to be stored XST_SUCCESS - If the elliptic key generation is successfulXSECURE_ELLIPTIC_NON_SUPPORTED_CRV - If curve size is 0XST_FAILURE - On failure
static int XSecure_EllipticGenSign(u32 SubsystemId, u32 SrcAddrLow, u32 SrcAddrHigh, u32 DstAddrLow, u32 DstAddrHigh)
This function handler extracts the payload params of the XSECURE_API_ELLIPTIC_GENERATE_SIGN IPI command and calls XSecure_EllipticGenerateSignature server API.
SubsystemId Subsystem ID. SrcAddrLow Lower 32 bit address of the XSecure_EllipticSignGenParams structure SrcAddrHigh Higher 32 bit address of the XSecure_EllipticSignGenParams structure DstAddrLow Lower 32 bit address of the signature to be stored DstAddrHigh Higher 32 bit address of the signature to be stored XST_SUCCESS - If the elliptic sign generation is successfulXST_INVALID_PARAM - If curve size is 0XST_FAILURE - If there is a failure
static int XSecure_EllipticValidatePubKey(u32 SubsystemId, u32 CurveType, u32 SrcAddrLow, u32 SrcAddrHigh)
This function handler extracts the payload params of XSECURE_API_ELLIPTIC_VALIDATE_KEY IPI command and calls XSecure_EllipticValidateKey server API.
SubsystemId Subsystem ID. CurveType Is a type of elliptic curve SrcAddrLow Lower 32 bit address of the public key SrcAddrHigh Higher 32 bit address of the public key XST_SUCCESS - If the elliptic key validation is successfulXST_INVALID_PARAM - If curve size is 0XST_FAILURE - If there is a failure
static int XSecure_EllipticVerifySignature(u32 SubsystemId, u32 SrcAddrLow, u32 SrcAddrHigh)
This function handler extracts the payload params with respect to XSECURE_API_ELLIPTIC_VERIFY_SIGN IPI command and calls XSecure_EllipticGenerateKey server API.
SubsystemId Subsystem ID. SrcAddrLow Lower 32 bit address of the XSecure_EllipticSignVerifyParams structure SrcAddrHigh Higher 32 bit address of the XSecure_EllipticSignVerifyParams structure XST_SUCCESS - If the elliptic sign verify is successfulXST_INVALID_PARAM - If curve size is 0XST_FAILURE - If there is a failure
int XSecure_EllipticIpiHandler(XPlmi_Cmd *Cmd)
This function calls respective IPI handler based on the API_ID.
Cmd is a pointer to the command structure XST_SUCCESS - If the handler execution is successfulXST_INVALID_PARAM - If Cmd is NULL or API ID is invalidXST_FAILURE - If there is a failure
References XSECURE_API, XSECURE_API_ELLIPTIC_GENERATE_KEY, XSECURE_API_ELLIPTIC_GENERATE_SIGN, XSECURE_API_ELLIPTIC_VALIDATE_KEY, XSECURE_API_ELLIPTIC_VERIFY_SIGN, XSECURE_API_ID_MASK, XSECURE_DEBUG_GENERAL, XSecure_Printf.
u32 XSecure_EllipticCrvsGetCount(void)
This function calculates the total number of curves supported.
Number of curves supported
Referenced by XSecure_EllipticGetCrvData.
XSECURE_ECC_TRNG_RANDOM_NUM_GEN_LEN
Length of xilsecure ecc true random number generator.
Referenced by XSecure_EllipticGenerateEphemeralKey, XSecure_EllipticPrvtKeyGenerate.
XSECURE_ECC_SEED_BUF_LEN
ECC key generation seed buffer size in bytes.
XSECURE_ECC_SEED_LEN
ECC key generation seed and personalization string length.
XSECURE_ECDSA_ALGN_CRV_SIZE_IN_BYTES
Align ECDSA curve size in bytes.
Referenced by XSecure_EllipticGetCrvSize.
XSECURE_ECDSA_BITS_IN_BYTES
Bits in bytes.
Referenced by XSecure_EllipticGetCrvSize.
XSECURE_ECC_P384_SIZE_IN_BYTES
Size of NIST P-384 curve in bytes.
Referenced by main, XSecure_EcdhGetSecret, XSecure_EllipticGenEphemeralNSign, XSecure_EllipticGenerateEphemeralKey, XSecure_EllipticPrvtKeyGenerate, XSecure_EllipticPwct, XSecure_EllipticSignGenerateKat, XSecure_GetKatEccExpSign, XSecure_GetKatEccPublicKey, XSecure_TestP384.
XSECURE_ECC_P521_SIZE_IN_BYTES
Size of NIST P-521 curve in bytes.
Referenced by XSecure_EcdhGetSecret, XSecure_EllipticGenerateKey_64Bit, XSecure_EllipticGenerateSignature, XSecure_EllipticGenerateSignature_64Bit, XSecure_EllipticPwct, XSecure_EllipticValidateKey_64Bit, XSecure_EllipticVerifySign, XSecure_EllipticVerifySign_64Bit.
XSECURE_ECC_P256_SIZE_IN_BYTES
Size of NIST P-256 curve in bytes.
Referenced by XSecure_EcdhGetSecret, XSecure_EllipticPwct.
XSECURE_ECC_P192_SIZE_IN_BYTES
Size of NIST P-192 curve in bytes.
Referenced by XSecure_EllipticPwct.
XSECURE_ECC_P224_SIZE_IN_BYTES
Size of NIST P-224 curve in bytes.
Referenced by XSecure_EllipticPwct.
XSECURE_ECDSA_P521_ALIGN_BYTES
Size of NIST P-521 curve is 66 bytes.
This macro is used to make the address word aligned
Referenced by XSecure_EcdhGetSecret, XSecure_EllipticGenerateKey_64Bit, XSecure_EllipticGenerateSignature_64Bit, XSecure_EllipticValidateKey_64Bit, XSecure_EllipticVerifySign_64Bit.
XSECURE_ELLIPTIC_LITTLE_ENDIAN
Operates APIs on little endian format.
Referenced by XSecure_FixEndiannessNCopy, XSecure_GetData, XSecure_PutData.
XSECURE_ELLIPTIC_MODULE_MAJOR_VERSION
Elliptic module major version.
XSECURE_ELLIPTIC_MODULE_MINOR_VERSION
Elliptic module minor version.
XSECURE_ECDH_MODULE_MAJOR_VERSION
ECDH module major version.
XSECURE_ECDH_MODULE_MINOR_VERSION
ECDH module minor version.
XSECURE_ELLIPTIC_MODULE_MAJOR_VERSION
Elliptic module major version.
XSECURE_ELLIPTIC_MODULE_MINOR_VERSION
Elliptic module minor version.
XSECURE_ECDH_MODULE_MAJOR_VERSION
ECDH module major version.
XSECURE_ECDH_MODULE_MINOR_VERSION
ECDH module minor version.
XSECURE_ELLIPTIC_MODULE_MAJOR_VERSION
Elliptic module major version.
XSECURE_ELLIPTIC_MODULE_MINOR_VERSION
Elliptic module minor version.