xsecure_ecdsa_client_apis
void XSecure_EcdhGetCryptoAlgInfo(Xil_CryptoAlgInfo *AlgInfo)
This function returns the ECDH crypto algorithm information.
AlgInfo Pointer to memory for holding the crypto algorithm information None
References XSECURE_API_GEN_SHARED_SECRET, XSecure_GetAlgInfo.
int XSecure_GenSharedSecret(XSecure_ClientInstance *InstancePtr, u32 CrvType, const u8 *PrivateKey, const u8 *PublicKey, u8 *SharedSecret)
This function sends IPI request to generate shared secret using Elliptic Curve Diffie–Hellman Key Exchange (ECDH)
InstancePtr Pointer to the client instance CrvType Type of elliptic curve PrivateKey Pointer to the private key buffer PublicKey Pointer to the public key buffer SharedSecret Pointer to the output buffer which shall be used to store shared secret XST_SUCCESS On SuccessXST_INVALID_PARAM If any input parameter is invalid.XST_FAILURE If there is a failure
References XSECURE_ADDR_HIGH_SHIFT, XSECURE_API_GEN_SHARED_SECRET, XSecure_DCacheFlushRange, XSecure_ProcessMailbox.
int XSecure_EllipticPrivateKeyGenerate(XSecure_ClientInstance *InstancePtr, const XSecure_EccPrivateKeyParams *ParamsPtr)
This function sends IPI request for ECC private key generation.
InstancePtr Pointer to the client instance. ParamsPtr Pointer to the XSecure_EccPrivateKeyParams structure. XST_SUCCESS On Success.XST_INVALID_PARAM If any input parameter is invalid.XST_FAILURE If there is a failure.
References XSECURE_ADDR_HIGH_SHIFT, XSECURE_API_ELLIPTIC_PRIVATE_KEY_GEN, XSecure_ProcessMailbox.
void XSecure_EllipticGetCryptoAlgInfo(Xil_CryptoAlgInfo *AlgInfo)
This function returns the Elliptic crypto algorithm information.
AlgInfo Pointer to memory for holding the crypto algorithm information None
References XSECURE_API_ELLIPTIC_VERIFY_SIGN, XSecure_GetAlgInfo.
int XSecure_EllipticGenerateSign(XSecure_ClientInstance *InstancePtr, u32 CurveType, u64 HashAddr, u32 Size, u64 PrivKeyAddr, u64 EPrivKeyAddr, u64 SignAddr)
This function sends IPI request to generate elliptic signature for a given hash and curve type.
InstancePtr Pointer to the client instance CurveType Type of elliptic curve HashAddr Address of the hash for which sign has to be generated Size Length of the hash in bytes PrivKeyAddr Address of the static private key EPrivKeyAddr Address of the Ephemeral private key SignAddr Address of the signature buffer XST_SUCCESS On successXST_FAILURE On failure
References XSECURE_ADDR_HIGH_SHIFT, XSECURE_API_ELLIPTIC_GENERATE_SIGN, XSecure_DCacheFlushRange, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
int XSecure_EllipticGenerateKey(XSecure_ClientInstance *InstancePtr, u32 CurveType, u64 PrivKeyAddr, u64 PubKeyAddr)
This function sends IPI request to generate Public Key for a given curve type.
InstancePtr Pointer to the client instance CurveType Type of elliptic curve PrivKeyAddr Address of the static private key PubKeyAddr Address of the buffer where public key to be stored. XST_SUCCESS On successXST_FAILURE On failure
References XSECURE_ADDR_HIGH_SHIFT, XSECURE_API_ELLIPTIC_GENERATE_KEY, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
Referenced by XSecure_TestP384.
int XSecure_EllipticValidateKey(XSecure_ClientInstance *InstancePtr, u32 CurveType, u64 KeyAddr)
This function sends IPI request to validate the public key for a given curve type.
InstancePtr Pointer to the client instance CurveType Type of elliptic curve KeyAddr Address of the public key to be validated XST_SUCCESS On successXST_FAILURE On failure
References XSECURE_ADDR_HIGH_SHIFT, XSECURE_API_ELLIPTIC_VALIDATE_KEY, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
Referenced by XSecure_EllipticVerifySignKat, XSecure_TestP384.
int XSecure_EllipticVerifySign(XSecure_ClientInstance *InstancePtr, u32 CurveType, u64 HashAddr, u32 Size, u64 PubKeyAddr, u64 SignAddr)
This function sends IPI request to verify signature for a given hash, key and curve type.
InstancePtr Pointer to the client instance CurveType Type of elliptic curve HashAddr Address of the hash for which sign has to be generated Size Length of the hash in bytes PubKeyAddr Address of the pubilc key SignAddr Address of the signature buffer XST_SUCCESS On successXST_FAILURE On failure
References XSECURE_ADDR_HIGH_SHIFT, XSECURE_API_ELLIPTIC_VERIFY_SIGN, XSecure_DCacheFlushRange, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
Referenced by XSecure_EllipticVerifySignKat, XSecure_TestP384.