xsecure_slhdsa_server_apis
XSecure_Slhdsa_n
16 bytes
XSecure_Slhdsa_h
63
XSecure_Slhdsa_d
7
XSecure_Slhdsa_hprime
3
XSecure_Slhdsa_a
6
XSecure_Slhdsa_k
14
XSecure_Slhdsa_lgw
4
XSecure_Slhdsa_m
30
static int XSecure_SlhdsaVerifyInternal(void)
Internal SLH-DSA signature verification (FIPS 205 Algorithm 20).
Gets signature and public key addresses from the instance structure. XST_SUCCESS On successful signature verification.ErrorCode On failure.
int XSecure_SlhdsaVerify(XSecure_Sha *ShaInstPtr, const XSecure_SlhdsaInputParams *const SlhdsaParams)
This function verifies an SLH-DSA signature for a given message using the provided public key.
It implements the pure SLH-DSA verification algorithm with optional context string support. ShaInstPtr Pointer to initialized SHA instance. SlhdsaParams Pointer to structure containing all SLH-DSA verification parameters: DataAddr: 64-bit address of message data buffer to be verifiedDataLen: Length of message data in bytesSignatureAddr: 64-bit address of signature buffer (R || SIG_FORS || SIG_HT)SignatureLen: Length of signature in bytesContextAddr: 64-bit address of optional context string buffer (can be 0)ContextLen: Length of context string in bytes (must be <= 255)PublicKeyAddr: 64-bit address of public key buffer (PK.seed || PK.root)PublicKeyLen: Length of public key in bytes (must be 2n) XST_SUCCESS On successful signature verification.ErrorCode On failure.
References XSecure_SlhdsaInputParams::ContextAddr, XSecure_SlhdsaInputParams::ContextLen, XSecure_SlhdsaInstance::Data1, XSecure_SlhdsaInstance::Data1Len, XSecure_SlhdsaInstance::DataAddr, XSecure_SlhdsaInputParams::DataAddr, XSecure_SlhdsaInstance::DataLen, XSecure_SlhdsaInputParams::DataLen, XSecure_SlhdsaParam::n, XSecure_SlhdsaInstance::Param, XSecure_SlhdsaInstance::PublicKeyAddr, XSecure_SlhdsaInputParams::PublicKeyAddr, XSecure_SlhdsaInputParams::PublicKeyLen, XSecure_SlhdsaInstance::ShaInstance, XSecure_SlhdsaInstance::SignatureAddr, XSecure_SlhdsaInputParams::SignatureAddr, XSecure_SlhdsaInstance::SignatureLen, XSecure_SlhdsaInputParams::SignatureLen, XSECURE_SLH_DSA_CTX_LEN_FIELD_LEN_BYTES, XSECURE_SLH_DSA_CTX_MAX_LEN_BYTES, XSECURE_SLH_DSA_DS_LEN_BYTES, XSECURE_SLH_DSA_PURE_SLH_VERIFY_DS, XSECURE_SLH_DSA_VERIFY_PREFIX_OFFSET_CTX, XSECURE_SLH_DSA_VERIFY_PREFIX_OFFSET_CTXLEN, XSECURE_SLH_DSA_VERIFY_PREFIX_OFFSET_DS, XSECURE_SLHDSA_CTX_LEN_ERROR, XSECURE_SLHDSA_INVALID_PARAM, XSECURE_SLHDSA_PK_LEN_ERROR, XSecure_SlhdsaGetInstance, XSECURE_VALUE_TWO.
void XSecure_SlhdsaBase2b(u32 *const BaseB, const u8 *const X, const u32 b, const u32 OutLen)
Computes the base 2^b representation of X, converts a byte string into an array of integers in the range [0, 2^b - 1].
BaseB Output array to store the base 2^b representation. X Input byte string (must have at least (OutLen*b)/8 bytes). b The base parameter (number of bits per output element). OutLen The number of output elements to generate.
References XSECURE_BYTE_IN_BITS, XSECURE_VALUE_ONE, XSECURE_ZERO.
Referenced by XSecure_SlhdsaForsPkFromSig.
int XSecure_SlhdsaForsPkFromSig(const u64 SignForsAddr, const u8 *const Md, const u64 PublicKeySeedAddr, u8 *const PkFors)
Computes a FORS public key from a FORS signature.
Implements Algorithm 17 (fors_pkFromSig) from FIPS 205. This function reconstructs the FORS public key using the provided signature, message digest, public seed, and address structure as specified in SLH-DSA.Algorithm Flow for SHAKE-256s (k=22, a=14, n=32): === SIGNATURE STRUCTURE === Each tree signature: [secret_value (32B)] || [auth[0] (32B)] || [auth[1] (32B)] || ... || [auth[13] (32B)] Total per tree: 32 + (14 × 32) = 480 bytesComplete FORS signature layout: ┌─────────────┬─────────────┬─────────────┬─────────────┐ │ Tree 0 Sig │ Tree 1 Sig │ ... │ Tree 21 Sig │ │ (480 bytes) │ (480 bytes) │ │ (480 bytes) │ └─────────────┴─────────────┴─────────────┴─────────────┘ Total: 22 × 480 = 10,560 bytesGiven: BaseB[5] = 12345 (from base_2b conversion), Binary: 0b11000000111001=== ADDRESS STRUCTURE PROGRESSION === Initial: ADRS.setTreeAddress(i), ADRS.setType(FORS_TREE)For each j iteration: ┌─────────────────────────────────────────────────────────┐ │ Step 9: ADRS.setTreeHeight(j+1) │ │ Step 11/14: ADRS.setTreeIndex(calculated_parent_index) │ │ Used in: H(PK.seed, ADRS, left_input || right_input) │ └─────────────────────────────────────────────────────────┘Final: ADRS.setType(FORS_ROOTS) for Step 24=== INITIAL SETUP === Tree Index (i=5): Idx = (5 << 14) + 12345 = 81920 + 12345 = 94265 NodePtr = &Data1[160], SignPtr = &SignFors[2400]=== FORS Tree Hierarchy (for SHAKE-256s): ===Height 0 (Leaves): 360,448 nodes (22 trees × 16,384 leaves each) Height 1: 180,224 nodes (360,448 ÷ 2) Height 2: 90,112 nodes (180,224 ÷ 2) Height 3: 45,056 nodes ... Height 13: 44 nodes Height 14 (Roots): 22 nodes (1 root per FORS tree)Each level has half the nodes of the level below.Tree 5 Range: Global indices 81920 to 98303Height 0: Leaves 81920-98303 (16,384 leaves) Height 1: Parents 40960-49151 (8,192 nodes) ✓ (81920>>1 to 98303>>1) Height 2: Parents 20480-24575 (4,096 nodes) ✓ (40960>>1 to 49151>>1) ... Height 14: Root = 5 (single root node)Leaf 94265 progression: Height 0: 94265 (leaf) Height 1: 47132 (parent) ✓ Height 2: 23566 (grandparent) Height 3: 11783 ... Height 14: 5 (Tree 5's root)=== LEAF COMPUTATION === Step 4-6: TreeHeight=0, TreeIndex=94265 NodePtr = F(PK.seed, ADRS, SignPtr[0:31]) SignPtr advances to auth[0]=== TREE TRAVERSAL TABLE === +-++++-++-+ | j | TreeHeight | TreeIndex | Bit | Path | Hash Operation | Alg Step | +-++++-++-+ | 0 | 1 | 47132 | 1 | ODD | auth[0] || node | Step 15 | | 1 | 2 | 23566 | 0 | EVEN | node || auth[1] | Step 12 | | 2 | 3 | 11783 | 0 | EVEN | node || auth[2] | Step 12 | | 3 | 4 | 5891 | 1 | ODD | auth[3] || node | Step 15 | | 4 | 5 | 2945 | 1 | ODD | auth[4] || node | Step 15 | | 5 | 6 | 1472 | 1 | ODD | auth[5] || node | Step 15 | | 6 | 7 | 736 | 0 | EVEN | node || auth[6] | Step 12 | | 7 | 8 | 368 | 0 | EVEN | node || auth[7] | Step 12 | | 8 | 9 | 184 | 0 | EVEN | node || auth[8] | Step 12 | | 9 | 10 | 92 | 0 | EVEN | node || auth[9] | Step 12 | | 10 | 11 | 46 | 0 | EVEN | node || auth[10] | Step 12 | | 11 | 12 | 23 | 1 | ODD | auth[11] || node | Step 15 | | 12 | 13 | 11 | 1 | ODD | auth[12] || node | Step 15 | | 13 | 14 | 5 | 1 | ODD | auth[13] || node | Step 15 | +-++++-++-+=== CALCULATION FORMULAS === TreeIndex = Idx >> (j+1) = 94265 >> (j+1) Bit = (BaseB[i] >> j) & 1 = (12345 >> j) & 1=== MEMORY LAYOUT === ++++ | Tree i | NodePtr Location | SignPtr Range (bytes) | ++++ | 0 | Data1[0:31] | [0:479] | | 1 | Data1[32:63] | [480:959] | | 2 | Data1[64:95] | [960:1439] | | 3 | Data1[96:127] | [1440:1919] | | 4 | Data1[128:159] | [1920:2399] | | 5 | Data1[160:191] | [2400:2879] <- | | ... | ... | ... | | 21 | Data1[672:703] | [10080:10559] | ++++=== FINAL COMPRESSION === Step 24: PkFors = T_k(PK.seed, forspkADRS, Data1[0:703]) Input: 704 bytes (22 roots × 32 bytes) Output: 32 bytes (Final FORS public key)=== PERFORMANCE CHARACTERISTICS === Computational Complexity: Hash operations: k × (1 + a) = 22 × 15 = 330 hash callsTime complexity: O(k × a × n) Memory Usage: Temporary storage: 704 bytes (22 roots)Signature input: 10,560 bytesWorking memory: Constant (reuses NodePtr) SignForsAddr 64-bit address of the FORS signature data (10,560 bytes for SHAKE-256s). Md Pointer to the message digest. PublicKeySeedAddr 64-bit address of the public key seed. PkFors Pointer to the buffer where the computed FORS public key will be stored. XST_SUCCESS if the public key is computed successfully.XSECURE_SLH_DSA_FORS_COMPUTE_LEAF_ERROR if FORS leaf computation fails.XSECURE_SLH_DSA_SIGN_VERIFY_FORS_NODE_ERROR if FORS tree node computation fails.XSECURE_SLH_DSA_FORS_ROOT_ERROR if FORS root computation fails.
References XSecure_SlhdsaParam::a, XSecure_SlhdsaInstance::Addr, XSecure_SlhdsaInstance::Data1, XSecure_SlhdsaInstance::Data4, XSecure_SlhdsaParam::k, XSecure_SlhdsaParam::n, XSecure_SlhdsaInstance::Param, XSECURE_ERR_GLITCH_DETECTED, XSECURE_IS_ODD, XSecure_SlhdsaBase2b, XSecure_SlhdsaGetInstance, XSecure_SlhdsaShake256sHashF, XSecure_SlhdsaShake256sHashH, XSecure_SlhdsaShake256sHashTl, XSECURE_VALUE_ONE, XSECURE_ZERO.
int XSecure_SlhdsaShake256sHashMsg(void)
This function computes the hash of the message as required by the SLH_DSA algorithm.
Gets signature and public key addresses from the instance structure for IPC compatibility. XST_SUCCESS if the operation was successful.Error code otherwise.
References XSecure_SlhdsaInstance::Data1, XSecure_SlhdsaInstance::Data1Len, XSecure_SlhdsaInstance::Data2, XSecure_SlhdsaInstance::DataAddr, XSecure_SlhdsaInstance::DataLen, XSecure_SlhdsaParam::m, XSecure_SlhdsaParam::n, XSecure_SlhdsaInstance::Param, XSecure_SlhdsaInstance::PublicKeyAddr, XSecure_SlhdsaInstance::ShaInstance, XSecure_SlhdsaInstance::SignatureAddr, XSecure_ExtendedShaFinish, XSECURE_SHAKE_256, XSecure_ShaLastUpdate, XSecure_ShaStart, XSecure_ShaUpdate, XSecure_SlhdsaGetInstance, XSECURE_VALUE_TWO, XSECURE_ZERO.
int XSecure_SlhdsaShake256sHashF(const u64 PublicKeyAddr, const u64 InputAddr, u8 *const Output)
This function generates a hash value based on the provided public key and input data, and stores the result in the output buffer.
It takes an n-byte message as input and produces an n-byte output. PublicKeyAddr 64-bit address of the public key buffer. InputAddr 64-bit address of the input data buffer to be hashed. Output Pointer to the buffer where the computed hash will be stored. XST_SUCCESS if the operation was successful.Error code otherwise.
References XSecure_SlhdsaInstance::Addr, XSecure_SlhdsaParam::n, XSecure_SlhdsaInstance::Param, XSecure_SlhdsaInstance::ShaInstance, XSecure_ShaFinish, XSECURE_SHAKE_256, XSecure_ShaLastUpdate, XSecure_ShaStart, XSecure_ShaUpdate, XSecure_SlhdsaGetInstance.
Referenced by XSecure_SlhdsaForsPkFromSig.
int XSecure_SlhdsaShake256sChain(const u64 InputAddr, const XSecure_SlhdsaChainConfig *const ChainConfig, const u64 PublicKeyAddr, u8 *const Output)
This function performs chained SLH_DSA hash operations on the input data, starting from the specified index and performing the given number of steps.
InputAddr 64-bit address of the input data buffer. ChainConfig Pointer to structure containing chain configuration: StartIdx: Index in the input buffer from where the chain operation should startSteps: Number of hash chain steps to perform PublicKeyAddr 64-bit address of the public key used for verification. Output Pointer to the buffer where the resulting hash will be stored. XST_SUCCESS if the operation was successful.Error code otherwise.
References XSecure_SlhdsaInstance::Addr, XSecure_SlhdsaParam::n, XSecure_SlhdsaInstance::Param, XSecure_SlhdsaInstance::ShaInstance, XSecure_SlhdsaChainConfig::StartIdx, XSecure_SlhdsaChainConfig::Steps, XSecure_MemCpy64, XSecure_ShaFinish, XSecure_ShaLastUpdate, XSecure_ShaStart, XSecure_ShaUpdate, XSecure_SlhdsaGetInstance, XSECURE_ZERO.
Referenced by XSecure_SlhdsaWotsPkFromSign.
int XSecure_SlhdsaShake256sHashTl(const u64 PublicKeyAddr, const u8 *const Input, u32 InputLen, u8 *const Output)
This function generates a hash value for the provided input data.
The hash is computed with respect to the given public key and the result is stored in the output buffer. PublicKeyAddr 64-bit address of the public key used for hashing. Input Pointer to the input data to be hashed. InputLen Length of the input data in bytes. Output Pointer to the buffer where the computed hash will be stored. XST_SUCCESS if the hash was computed successfully.Error code otherwise.
References XSecure_SlhdsaInstance::Addr, XSecure_SlhdsaParam::n, XSecure_SlhdsaInstance::Param, XSecure_SlhdsaInstance::ShaInstance, XSecure_ShaFinish, XSECURE_SHAKE_256, XSecure_ShaLastUpdate, XSecure_ShaStart, XSecure_ShaUpdate, XSecure_SlhdsaGetInstance.
Referenced by XSecure_SlhdsaForsPkFromSig, XSecure_SlhdsaWotsPkFromSign.
int XSecure_SlhdsaShake256sHashH(const u64 PublicKeyAddr, const u64 Data1Addr, const u64 Data2Addr, u8 *const Output)
This function generates a hash value for the provided input data.
The hash is computed with respect to the given public key and the result is stored in the output buffer. PublicKeyAddr 64-bit address of the public key used for hashing. Data1Addr 64-bit address of the first input data to be hashed. Data2Addr 64-bit address of the second input data to be hashed. Output Pointer to the buffer where the hash output will be stored. XST_SUCCESS if the hash was computed successfully.Error code otherwise.
References XSecure_SlhdsaInstance::Addr, XSecure_SlhdsaParam::n, XSecure_SlhdsaInstance::Param, XSecure_SlhdsaInstance::ShaInstance, XSecure_ShaFinish, XSECURE_SHAKE_256, XSecure_ShaLastUpdate, XSecure_ShaStart, XSecure_ShaUpdate, XSecure_SlhdsaGetInstance.
Referenced by XSecure_SlhdsaForsPkFromSig, XSecure_SlhdsaXmssPkFromSign.
int XSecure_SlhdsaHtVerify(const u8 *const M, const u64 SignHtAddr, const u64 PublicKeyAddr, const XSecure_SlhdsaHtIndices *const HtIndices)
This function verifies a SLH-DSA hypertree signature by traversing through multiple layers of XMSS trees, starting from the bottom layer and working up to the root layer, ultimately comparing the computed root with PK.root.
Algorithm Flow for SHAKE-256s (d=8, h'=8, len=67, n=32): Given: IdxTree=0x123456789ABCDEF0, IdxLeaf=0x87654321=== HYPERTREE STRUCTURE === SLH-DSA-SHAKE-256s uses a hypertree composed of d=8 layers of XMSS trees:Layer 7 (Top): 1 XMSS tree (contains PK.root) Layer 6: 2^8 = 256 XMSS trees Layer 5: 2^16 = 65,536 XMSS trees Layer 4: 2^24 = 16,777,216 XMSS trees Layer 3: 2^32 = 4,294,967,296 XMSS trees Layer 2: 2^40 = 1,099,511,627,776 XMSS trees Layer 1: 2^48 = 281,474,976,710,656 XMSS trees Layer 0 (Bottom): 2^56 = 72,057,594,037,927,936 XMSS trees (FORS trees connect here)Each XMSS tree has height h'=8 (2^8 = 256 leaves)=== TREE COUNT CALCULATION === At layer j, maximum tree index = 2^(56 - j×8) - 1 Layer 0: Max tree index = 2^56 - 1 (so 2^56 possible trees)Layer 1: Max tree index = 2^48 - 1 (so 2^48 possible trees)Layer 2: Max tree index = 2^40 - 1 (so 2^40 possible trees)Layer 3: Max tree index = 2^32 - 1 (so 2^32 possible trees)Layer 4: Max tree index = 2^24 - 1 (so 2^24 possible trees)Layer 5: Max tree index = 2^16 - 1 (so 2^16 possible trees)Layer 6: Max tree index = 2^8 - 1 (so 2^8 possible trees)Layer 7: Max tree index = 2^0 - 1 = 0 (so 1 possible tree) === TREE DIVERSITY DEMONSTRATION === Starting with IdxTree = 0x123456789ABCDEF0:Layer 0→1: IdxLeaf = 0x00, IdxTree = 0x123456789ABCDE00 >> 8 = 0x123456789ABCDE Layer 1→2: IdxLeaf = 0xDE, IdxTree = 0x123456789ABCDE >> 8 = 0x123456789ABC Layer 2→3: IdxLeaf = 0xBC, IdxTree = 0x123456789ABC >> 8 = 0x123456789A Layer 3→4: IdxLeaf = 0x9A, IdxTree = 0x123456789A >> 8 = 0x12345678 Layer 4→5: IdxLeaf = 0x78, IdxTree = 0x12345678 >> 8 = 0x123456 Layer 5→6: IdxLeaf = 0x56, IdxTree = 0x123456 >> 8 = 0x1234 Layer 6→7: IdxLeaf = 0x34, IdxTree = 0x1234 >> 8 = 0x12 Layer 7→END: IdxLeaf = 0x12, IdxTree = 0x12 >> 8 = 0x0 ✓=== TRAVERSAL TABLE === +-+-+-+-++-+ | j | Layer | IdxLeaf | IdxTree | XMSS Tree Accessed | Description | +-+-+-+-++-+ | - | 0 (init) | 0x21 | 0x123456789ABCDEF0| Tree F0 at Layer 0 | Initial tree | +-+-+-+-++-+ | 1 | 1 | 0xF0 | 0x123456789ABCDE | Tree DE at Layer 1 | Parent of F0 | +-+-+-+-++-+ | 2 | 2 | 0xDE | 0x123456789ABC | Tree BC at Layer 2 | Parent of DE | +-+-+-+-++-+ | 3 | 3 | 0xBC | 0x123456789A | Tree 9A at Layer 3 | Parent of BC | +-+-+-+-++-+ | 4 | 4 | 0x9A | 0x12345678 | Tree 78 at Layer 4 | Parent of 9A | +-+-+-+-++-+ | 5 | 5 | 0x78 | 0x123456 | Tree 56 at Layer 5 | Parent of 78 | +-+-+-+-++-+ | 6 | 6 | 0x56 | 0x1234 | Tree 34 at Layer 6 | Parent of 56 | +-+-+-+-++-+ | 7 | 7 | 0x34 | 0x12 | Tree 12 at Layer 7 | Root layer | | | | | | (leaf 0x34 in tree | (final check | | | | | | 0x12) | vs PK.root) | +-+-+-+-++-+=== CALCULATION FORMULAS === Step 6: IdxLeaf = IdxTree & ((1 << h') - 1) = IdxTree & 0xFF Step 7: IdxTree = IdxTree >> h' = IdxTree >> 8=== DETAILED INDEX PROGRESSION === Starting with IdxTree = 0x123456789ABCDEF0:Layer 0→1: IdxLeaf = 0xF0 & 0xFF = 0xF0 (240), IdxTree = 0x123456789ABCDEF0 >> 8 = 0x123456789ABCDE Layer 1→2: IdxLeaf = 0xDE & 0xFF = 0xDE (222), IdxTree = 0x123456789ABCDE >> 8 = 0x123456789ABC Layer 2→3: IdxLeaf = 0xBC & 0xFF = 0xBC (188), IdxTree = 0x123456789ABC >> 8 = 0x123456789A Layer 3→4: IdxLeaf = 0x9A & 0xFF = 0x9A (154), IdxTree = 0x123456789A >> 8 = 0x12345678 Layer 4→5: IdxLeaf = 0x78 & 0xFF = 0x78 (120), IdxTree = 0x12345678 >> 8 = 0x123456 Layer 5→6: IdxLeaf = 0x56 & 0xFF = 0x56 (86), IdxTree = 0x123456 >> 8 = 0x1234 Layer 6→7: IdxLeaf = 0x34 & 0xFF = 0x34 (52), IdxTree = 0x1234 >> 8 = 0x12 Layer 7→8: IdxLeaf = 0x12 & 0xFF = 0x12 (18), IdxTree = 0x12 >> 8 = 0x0=== TREE DIVERSITY DEMONSTRATION === This example shows access to different trees at each layer: Layer 0: Tree 0xF0 (240) out of 2^56 possible treesLayer 1: Tree 0xDE (222) out of 2^48 possible treesLayer 2: Tree 0xBC (188) out of 2^40 possible treesLayer 3: Tree 0x9A (154) out of 2^32 possible treesLayer 4: Tree 0x78 (120) out of 2^24 possible treesLayer 5: Tree 0x56 (86) out of 2^16 possible treesLayer 6: Tree 0x34 (52) out of 2^8 possible treesLayer 7: Tree 0x12 (18) out of 1 possible tree (but shows non-zero until final shift)Layer 8: Tree 0x0 (0) - The single root tree === SIGNATURE CONSUMPTION === SignHt progression through signature buffer: +-++-+ | j | SignHt Offset (bytes) | XMSS Signature Used | +-++-+ | - | 0 | SIG_HT[0:2399] | | 1 | 2400 | SIG_HT[2400:4799] | | 2 | 4800 | SIG_HT[4800:7199] | | 3 | 7200 | SIG_HT[7200:9599] | | 4 | 9600 | SIG_HT[9600:11999] | | 5 | 12000 | SIG_HT[12000:14399] | | 6 | 14400 | SIG_HT[14400:16799] | | 7 | 16800 | SIG_HT[16800:19199] | +-++-+=== XMSS VERIFICATION DETAILS === At each layer j: ADRS.setLayerAddress(j) - Identifies current layerADRS.setTreeAddress(IdxTree) - Identifies specific XMSS treexmss_pkFromSig() computes XMSS root using: IdxLeaf: Position within the XMSS treeSIGtmp: XMSS signature for this layerM: Message (FORS_PK for layer 0, previous root for others)PK.seed: Public seedADRS: Address structure for domain separation === FINAL VERIFICATION === Step 13: Compare computed root with PK.root Node contains final computed root (32 bytes)PK.root = PublicKey[32:63] (second 32 bytes of public key)Byte-by-byte comparison for constant-time verification === PERFORMANCE CHARACTERISTICS === Computational Complexity: XMSS verifications: d = 8 operationsTotal hash operations: d × (len + h') = 8 × 75 = 600 hash callsMemory usage: 2400 bytes working + 19200 bytes signature inputTime complexity: O(d × (len + h') × n) M Message to verify (FORS public key, 32 bytes). SignHtAddr 64-bit address of hypertree signature (19,200 bytes for SHAKE-256s). PublicKeyAddr 64-bit address of public key buffer (PK.seed || PK.root, 64 bytes). HtIndices Pointer to structure containing hypertree indices (IdxTree: tree index for hypertree verification, IdxLeaf: leaf index for hypertree verification) XST_SUCCESS if signature verification succeeds.XSECURE_SLHDSA_PK_ROOT_MISMATCH_ERROR if final root comparison fails.ErrorCode Otherwise.
References XSecure_SlhdsaInstance::Addr, XSecure_ChecksumParam::ChecksumLenInDigits, XSecure_SlhdsaParam::ChecksumParams, XSecure_SlhdsaParam::d, XSecure_SlhdsaInstance::Data3, XSecure_SlhdsaParam::hprime, XSecure_SlhdsaHtIndices::IdxLeaf, XSecure_SlhdsaHtIndices::IdxTree, XSecure_ChecksumParam::InputLenInDigits, XSecure_SlhdsaParam::n, XSecure_SlhdsaInstance::Param, XSECURE_DEBUG_GENERAL, XSECURE_ERR_GLITCH_DETECTED, XSecure_Printf, XSECURE_SLHDSA_PK_ROOT_MISMATCH_ERROR, XSecure_SlhdsaGetInstance, XSecure_SlhdsaXmssPkFromSign, XSECURE_VALUE_ONE.
XSecure_SlhdsaInstance * XSecure_SlhdsaGetInstance(void)
This function returns the XSecure_SlhdsaInstance instance.
SlhdsaInstance stores all required components for SLH-DSA signature verification. Returns pointer to XSecure_SlhdsaInstance instance
References XSecure_SlhdsaInstance::Addr, XSecure_SlhdsaInstance::Data1, XSecure_SlhdsaInstance::Data2, XSecure_SlhdsaInstance::Data3, XSecure_SlhdsaInstance::Data4, XSecure_SlhdsaParam::n, XSecure_SlhdsaInstance::Param, XSECURE_SLH_DSA_A_14, XSECURE_SLH_DSA_D_8, XSECURE_SLH_DSA_H_64, XSECURE_SLH_DSA_HPRIME_8, XSECURE_SLH_DSA_K_22, XSECURE_SLH_DSA_LGW_4, XSECURE_SLH_DSA_M_47, XSECURE_SLH_DSA_N_32, XSECURE_SLHDSA_CSUM_INPUT_LEN_IN_DIGITS, XSECURE_SLHDSA_CSUM_LEN_IN_DIGITS, XSECURE_SLHDSA_CSUM_SHIFT, XSECURE_SLHDSA_CSUM_SIZE_IN_BYTES, XSECURE_SLHDSA_MAX_DATA1_LEN_IN_BYTES, XSECURE_SLHDSA_MAX_DATA2_LEN_IN_BYTES, XSECURE_SLHDSA_MAX_DATA3_LEN_IN_BYTES, XSECURE_SLHDSA_MAX_DATA4_LEN_IN_WORDS, XSECURE_SLHDSA_NO_OF_INV_SIGN, XSECURE_SLHDSA_SHAKE_256S_SIGN_LEN.
Referenced by XSecure_SlhdsaForsPkFromSig, XSecure_SlhdsaHtVerify, XSecure_SlhdsaShake256sChain, XSecure_SlhdsaShake256sHashF, XSecure_SlhdsaShake256sHashH, XSecure_SlhdsaShake256sHashMsg, XSecure_SlhdsaShake256sHashTl, XSecure_SlhdsaVerify, XSecure_SlhdsaWotsPkFromSign, XSecure_SlhdsaXmssPkFromSign.
static int XSecure_SlhdsaSignVerifyIpi(u32 SlhdsaParamAddrLow, u32 SlhdsaParamAddrHigh)
This function handler calls XSecure_SlhdsaVerify server API.
SlhdsaParamAddrLow Lower 32 bit address of the XSecure_SlhdsaInputParams structure. SlhdsaParamAddrHigh Higher 32 bit address of the XSecure_SlhdsaInputParams structure. XST_SUCCESS If the SLHDSA signature verification is successful.XST_FAILURE If there is a failure.
int XSecure_SlhdsaIpiHandler(XPlmi_Cmd *Cmd)
This function calls respective IPI handler based on the API_ID.
Cmd Pointer to the command structure. XST_SUCCESS If the handler execution is successful.XST_INVALID_PARAM If any input parameter is invalid.XST_FAILURE If there is a failure.
References XSECURE_API, XSECURE_API_ID_MASK, XSECURE_API_SLHDSA_SIGN_VERIFY, XSecure_GetSha3Instance, XSecure_IpiEventHandling, XSecure_MakeResFree, XSECURE_SHA_0_DEVICE_ID, XSECURE_SHA_INITIALIZED.
static void XSecure_ComputeChecksum(const XSecure_ChecksumParam *const ChecksumParams, const u8 *const M, u32 *const Output)
This function computes WOTS+ checksum and combines with base-w message representation to create the complete message array used for WOTS+ signature verification.
ChecksumParams Pointer to checksum parameters structure containing: M Input message (n bytes, typically 32 bytes for SHAKE-256s) Output Output array to store combined message and checksum digits (len1 + len2 elements, typically 67 for SHAKE-256s)
int XSecure_SlhdsaWotsPkFromSign(u64 WotsSignAddr, u64 MAddr, u64 PublicKeyAddr, u8 *const WotsPk)
This function reconstructs the WOTS+ public key from the provided WOTS+ signature and message.
It computes the checksum, extends each signature chain to derive the public key elements, and then hashes all elements to produce the final WOTS+ public key.Algorithm Flow for SHAKE-256s (len=67, w=16, n=32): Given: M=FORS_PK (32 bytes), WotsSign=WOTS_signature (2144 bytes) Input message: M = [0x3A, 0x7F, 0x92, 0x1C, ...] (32 bytes)=== WOTS+ SIGNATURE STRUCTURE === WotsSign layout (2144 bytes total): ┌──────────────┬──────────────┬─────┬──────────────┬──────────────┬─────┬──────────────┐ │ sig[0] │ sig[1] │ ... │ sig[63] │ sig[64] │ ... │ sig[66] │ │ (32 bytes) │ (32 bytes) │ │ (32 bytes) │ (32 bytes) │ │ (32 bytes) │ │ Chain 0 │ Chain 1 │ │ Chain 63 │ Checksum 0 │ │ Checksum 2 │ └──────────────┴──────────────┴─────┴──────────────┴──────────────┴─────┴──────────────┘Message chains: sig[0] to sig[63] (64 chains for 32-byte message) Checksum chains: sig[64] to sig[66] (3 chains for checksum) Total: 67 chains × 32 bytes = 2144 bytes=== INITIAL SETUP === ADRS initialization: Type already set to WOTS_HASH for chain computationsKeyPairAddress inherited from caller === STEP 1-7: MESSAGE PROCESSING AND CHECKSUM === XSecure_SlhdsaWotsCheckSum(M, Data2[]) computes:Step 1: csum = 0 Step 2: msg = base_w(M, w, len1) - Convert message to base-16 digitsMessage conversion (first 4 bytes example): M[0] = 0x3A = 0011 1010 → base_w[0] = 3, base_w[1] = 10 M[1] = 0x7F = 0111 1111 → base_w[2] = 7, base_w[3] = 15 M[2] = 0x92 = 1001 0010 → base_w[4] = 9, base_w[5] = 2 M[3] = 0x1C = 0001 1100 → base_w[6] = 1, base_w[7] = 12 ...continuing for all 32 bytes → 64 base-16 digitsStep 3-5: Compute checksum for i from 0 to len1-1: csum += w-1-msg[i] csum += (15-3) + (15-10) + (15-7) + (15-15) + (15-9) + (15-2) + ... = sumStep 6-7: Convert checksum to base-16 and append csum_base_w = base_w(csum, w, len2) → 3 additional base-16 digits Final msg array: [msg[0]...msg[63], csum[0], csum[1], csum[2]]=== WOTS+ CHAIN COMPUTATION TABLE (WITH HW ACCELERATION) === ++-+-+-+++ | i | msg[i] | Chain | Iterations | HW Chain Operation | Result Location | ++-+-+-+++ | 0 | 3 | 0 | 15-3 = 12 | HW: sig[0] →(×12)→ | Data1[0:31] | | 1 | 10 | 1 | 15-10 = 5 | HW: sig[1] →(×5)→ | Data1[32:63] | | 2 | 7 | 2 | 15-7 = 8 | HW: sig[2] →(×8)→ | Data1[64:95] | | 3 | 15 | 3 | 15-15 = 0 | SKIP: sig[3] copied | Data1[96:127] | | 4 | 9 | 4 | 15-9 = 6 | HW: sig[4] →(×6)→ | Data1[128:159] | | ... | ... | ... | ... | ... | ... | | 63 | msg[63] | 63 | 15-msg[63] | HW: sig[63] →(×n)→ | Data1[2016:2047] | | 64 | csum[0] | 64 | 15-csum[0] | HW: sig[64] →(×n)→ | Data1[2048:2079] | | 65 | csum[1] | 65 | 15-csum[1] | HW: sig[65] →(×n)→ | Data1[2080:2111] | | 66 | csum[2] | 66 | 15-csum[2] | HW: sig[66] →(×n)→ | Data1[2112:2143] | ++-+-+-+++=== ADDRESS PROGRESSION === For each chain i: ++++ | i | ChainAddress(i) | HW Chain Operation | ++++ | 0 | 0 | HW: chain=0, iter=3→15 | | 1 | 1 | HW: chain=1, iter=10→15 | | 2 | 2 | HW: chain=2, iter=7→15 | | ... | ... | ... | | 66 | 66 | HW: chain=66, iter=x→15 | ++++=== FINAL PUBLIC KEY COMPUTATION === Step 12-13: Switch ADRS to WOTS_PK type XSecure_SlhdsaSetTypeClearNotKp(WOTS_PK)Step 15: Compute final WOTS+ public key WotsPk = Tlen(PK.seed, ADRS, Data1[0:2143])XSecure_SlhdsaShake256sHashTl computes: Input: All 67 public key elements (Data1, 2144 bytes total)Hash: SHAKE-256(PK.seed || ADRS || Data1[0:2143])Output: 32-byte WOTS+ public key (WotsPk) === MEMORY MANAGEMENT === Buffer Usage: Data1[2144]: Stores all 67 public key elements (67 × 32 bytes)Data2[67]: Stores base-w representation + checksumWotsPk[32]: Output buffer for final public keyTmpPtr: Tracks current position in signature buffer (increments by 32) Memory Layout during execution: ┌─────────────────────────────────────────────────────────────────────────┐ │ Data1: [pk_elem[0]][pk_elem[1]]...[pk_elem[66]] (2144 bytes) │ ├─────────────────────────────────────────────────────────────────────────┤ │ Data2: [msg[0]][msg[1]]...[msg[63]][csum[0]][csum[1]][csum[2]] (67 vals)│ └─────────────────────────────────────────────────────────────────────────┘Memory Usage: Input signature: 2144 bytesWorking buffers: 2144 + 67 = 2211 bytesOutput: 32 bytesTotal working memory: ~2.2 KB WotsSignAddr 64-bit address of WOTS+ signature (2144 bytes for SHAKE-256s). MAddr 64-bit address of message to verify (typically FORS public key, n bytes = 32 bytes). PublicKeyAddr 64-bit address of public key seed for hash computations (n bytes = 32 bytes). WotsPk Buffer to store computed WOTS+ public key (n bytes = 32 bytes). XST_SUCCESS if WOTS+ public key computation succeeds.ErrorCode Otherwise.
References XSecure_SlhdsaInstance::Addr, XSecure_ChecksumParam::ChecksumLenInDigits, XSecure_SlhdsaParam::ChecksumParams, XSecure_SlhdsaInstance::Data1, XSecure_SlhdsaInstance::Data4, XSecure_ChecksumParam::InputLenInDigits, XSecure_SlhdsaParam::n, XSecure_SlhdsaParam::NoOfInvSign, XSecure_SlhdsaInstance::Param, XSecure_SlhdsaChainConfig::StartIdx, XSecure_SlhdsaChainConfig::Steps, XSecure_SlhdsaGetInstance, XSecure_SlhdsaShake256sChain, XSecure_SlhdsaShake256sHashTl, XSECURE_ZERO.
Referenced by XSecure_SlhdsaXmssPkFromSign.
int XSecure_SlhdsaXmssPkFromSign(u64 IdxLeaf, u64 SignTmpAddr, u64 MAddr, u64 PublicKeyAddr, u8 *Node)
This function reconstructs the XMSS public key (tree root) using the provided XMSS signature, message, public seed, and address structure.
It first computes the WOTS+ public key from the WOTS+ signature, then uses the authentication path to compute the tree root.Algorithm Flow for SHAKE-256s (len=67, h'=8, n=32): Given: IdxLeaf=58, M=FORS_PK (32 bytes), SignTmp=XMSS_signature (2400 bytes) Binary: IdxLeaf=58 = 0b00111010=== XMSS SIGNATURE STRUCTURE === SignTmp layout (2400 bytes total): ┌─────────────────┬──────────────────────────────────────────────────┐ │ WOTS+ Signature │ XMSS Authentication Path │ │ (len × n bytes) │ (h' × n bytes) │ │ (67 × 32 = 2144)│ (8 × 32 = 256 bytes) │ └─────────────────┴──────────────────────────────────────────────────┘WOTS+ Sig: SignTmp[0:2143] - Used to compute leaf node AUTH Path: SignTmp[2144:2399] - Used to compute tree root=== INITIAL SETUP === Input indices: IdxLeaf = 58 (decimal) = 0b00111010 (binary)ADRS initialization: setTypeAndClear(WOTS_HASH) for WOTS+ computationsetKeyPairAddress(58) for leaf identification === WOTS+ PUBLIC KEY COMPUTATION === Step 5: node[0] = wots_pkFromSig(SignTmp[0:2143], M, PK.seed, ADRS) Result: 32-byte WOTS+ public key representing leaf 58=== TREE TRAVERSAL SETUP === Switch ADRS to TREE type for authentication path processing SignXmssOffset = &SignTmp[2144] (points to AUTH[0])=== XMSS TREE TRAVERSAL TABLE === +++++-+++ | k | TreeHeight | TreeIndex | Bit | Position | Hash Operation | AUTH Usage | +++++-+++ | 0 | 1 | 29 | 0 EVEN | LEFT | node || AUTH[0] | SignXmssOffset[0] | | 1 | 2 | 14 | 1 ODD | RIGHT | AUTH[1] || node | SignXmssOffset[32] | | 2 | 3 | 7 | 0 EVEN | LEFT | node || AUTH[2] | SignXmssOffset[64] | | 3 | 4 | 3 | 1 ODD | RIGHT | AUTH[3] || node | SignXmssOffset[96] | | 4 | 5 | 1 | 1 ODD | RIGHT | AUTH[4] || node | SignXmssOffset[128]| | 5 | 6 | 0 | 1 ODD | RIGHT | AUTH[5] || node | SignXmssOffset[160]| | 6 | 7 | 0 | 0 EVEN | LEFT | node || AUTH[6] | SignXmssOffset[192]| | 7 | 8 | 0 | 0 EVEN | LEFT | node || AUTH[7] | SignXmssOffset[224]| +++++-+++=== CALCULATION FORMULAS === TreeHeight = k + 1 TreeIndex = IdxLeaf >> (k + 1) = 58 >> (k + 1) Bit = (IdxLeaf >> k) & 1 = (58 >> k) & 1=== DETAILED BIT ANALYSIS === IdxLeaf = 58 = 0b00111010k=0: (58 >> 0) & 1 = 0 (EVEN) → node is LEFT child, AUTH[0] is RIGHT sibling → node || AUTH[0] k=1: (58 >> 1) & 1 = 1 (ODD) → node is RIGHT child, AUTH[1] is LEFT sibling → AUTH[1] || node k=2: (58 >> 2) & 1 = 0 (EVEN) → node is LEFT child, AUTH[2] is RIGHT sibling → node || AUTH[2] k=3: (58 >> 3) & 1 = 1 (ODD) → node is RIGHT child, AUTH[3] is LEFT sibling → AUTH[3] || node k=4: (58 >> 4) & 1 = 1 (ODD) → node is RIGHT child, AUTH[4] is LEFT sibling → AUTH[4] || node k=5: (58 >> 5) & 1 = 1 (ODD) → node is RIGHT child, AUTH[5] is LEFT sibling → AUTH[5] || node k=6: (58 >> 6) & 1 = 0 (EVEN) → node is LEFT child, AUTH[6] is RIGHT sibling → node || AUTH[6] k=7: (58 >> 7) & 1 = 0 (EVEN) → node is LEFT child, AUTH[7] is RIGHT sibling → node || AUTH[7]=== TREE STRUCTURE VISUALIZATION ===Height 8: [ROOT] / \ Height 7: node_7 AUTH[7] / \ Height 6: node_6 AUTH[6] / \ Height 5: node_5 AUTH[5] / \ Height 4: AUTH[4] node_4 / \ Height 3: AUTH[3] node_3 / \ Height 2: AUTH[2] node_2 / \ Height 1: AUTH[1] node_1 / \ Height 0: WOTS+[58] AUTH[0] <- Leaf level (IdxLeaf=58)Key: WOTS+[58] is at position 58 (EVEN), so it's the LEFT childAUTH[0] is the RIGHT sibling of WOTS+[58]Hash: WOTS+[58] || AUTH[0] (left || right) === ADDRESS PROGRESSION === Each iteration updates ADRS fields: ++++ | k | TreeHeight(k+1) | TreeIndex(IdxLeaf>>(k+1)) | ++++ | 0 | 1 | 29 (58>>1) | | 1 | 2 | 14 (58>>2) | | 2 | 3 | 7 (58>>3) | | 3 | 4 | 3 (58>>4) | | 4 | 5 | 1 (58>>5) | | 5 | 6 | 0 (58>>6) | | 6 | 7 | 0 (58>>7) | | 7 | 8 | 0 (58>>8) | ++++=== MEMORY MANAGEMENT === Node buffer usage (in-place updates): Initial: Contains WOTS+ public key (leaf value)k=0: Contains parent of leaf 58k=1: Contains grandparent...k=7: Contains final XMSS root (32 bytes) SignXmssOffset progression: k=0: &SignTmp[2144] → AUTH[0]k=1: &SignTmp[2176] → AUTH[1]k=2: &SignTmp[2208] → AUTH[2]...k=7: &SignTmp[2368] → AUTH[7] === PERFORMANCE CHARACTERISTICS === Computational Complexity: Tree traversal: h' hash operations = 8 hashesTime complexity: O(h' × n) = O(8 × 32) = O(256) per XMSS verification Memory Usage: Input XMSS signature: 2400 bytes total WOTS+ signature portion: 2144 bytesAuthentication path: 256 bytes (8 × 32) Working node buffer: 32 bytes (reused in-place)Authentication path access: Sequential, 32 bytes per iterationTotal XMSS memory: O(signature_size + n) IdxLeaf Leaf index within the XMSS tree (0 to 2^h'-1). SignTmpAddr 64-bit address of XMSS signature (2400 bytes for SHAKE-256s). MAddr 64-bit address of message to verify (typically FORS public key, 32 bytes). PublicKeyAddr 64-bit address of public key seed for hash computations. Node Buffer to store computed XMSS root (32 bytes). XST_SUCCESS if XMSS public key computation succeeds.ErrorCode if failure.
References XSecure_SlhdsaInstance::Addr, XSecure_ChecksumParam::ChecksumLenInDigits, XSecure_SlhdsaParam::ChecksumParams, XSecure_SlhdsaParam::hprime, XSecure_ChecksumParam::InputLenInDigits, XSecure_SlhdsaParam::n, XSecure_SlhdsaInstance::Param, XSECURE_ERR_GLITCH_DETECTED, XSECURE_IS_ODD, XSecure_SlhdsaGetInstance, XSecure_SlhdsaShake256sHashH, XSecure_SlhdsaWotsPkFromSign, XSECURE_VALUE_ONE.
Referenced by XSecure_SlhdsaHtVerify.
XSECURE_SLH_DSA_VERIFY_PREFIX_OFFSET_DS
Domain separation offset.
Referenced by XSecure_SlhdsaVerify.
XSECURE_SLH_DSA_VERIFY_PREFIX_OFFSET_CTXLEN
Context length offset.
Referenced by XSecure_SlhdsaVerify.
XSECURE_SLH_DSA_VERIFY_PREFIX_OFFSET_CTX
Context string offset.
Referenced by XSecure_SlhdsaVerify.
XSECURE_SLH_DSA_CTX_MAX_LEN_BYTES
Maximum possible context length.
Referenced by XSecure_SlhdsaVerify.
XSECURE_SLH_DSA_DS_LEN_BYTES
Domain separator length in bytes.
Referenced by XSecure_SlhdsaVerify.
XSECURE_SLH_DSA_CTX_LEN_FIELD_LEN_BYTES
Length of ctx length field.
Referenced by XSecure_SlhdsaVerify.
XSECURE_SLH_DSA_PURE_SLH_VERIFY_DS
Domain separator for pure SLH-DSA verification.
Referenced by XSecure_SlhdsaVerify.
XSECURE_SLHDSA_N_LEN
Output length in bytes for SLH-DSA-SHAKE-256s.
XSECURE_SLHDSA_SHAKE_256S_SIGN_LEN
Total signature length in bytes for SLH-DSA-SHAKE-256s.
Referenced by XSecure_SlhdsaGetInstance.
XSECURE_SLHDSA_MAX_DATA1_LEN_IN_BYTES
Maximum length of Data1 buffer in bytes (for WOTS+ chain values)
Referenced by XSecure_SlhdsaGetInstance.
XSECURE_SLHDSA_MAX_DATA2_LEN_IN_BYTES
Maximum length of Data2 buffer in bytes (for hash outputs and base conversions)
Referenced by XSecure_SlhdsaGetInstance.
XSECURE_SLHDSA_MAX_DATA3_LEN_IN_BYTES
Maximum length of Data3 buffer in bytes (for single hash outputs)
Referenced by XSecure_SlhdsaGetInstance.
XSECURE_SLHDSA_MAX_DATA4_LEN_IN_WORDS
Maximum length of Data4 buffer in words (for storing digits)
Referenced by XSecure_SlhdsaGetInstance.
XSECURE_SLHDSA_NO_OF_INV_SIGN
Number of invalid signature invocations allowed.
Referenced by XSecure_SlhdsaGetInstance.
XSECURE_SLHDSA_CSUM_INPUT_LEN_IN_DIGITS
Length of checksum input in digits for WOTS+.
Referenced by XSecure_SlhdsaGetInstance.
XSECURE_SLHDSA_CSUM_LEN_IN_DIGITS
Length of checksum in digits.
Referenced by XSecure_SlhdsaGetInstance.
XSECURE_SLHDSA_CSUM_SHIFT
Shift value for checksum calculation.
Referenced by XSecure_SlhdsaGetInstance.
XSECURE_SLHDSA_CSUM_SIZE_IN_BYTES
Size of checksum in bytes.
Referenced by XSecure_SlhdsaGetInstance.