xsecure_aes_server_apis
XSecure_AesKeySize
Key Length = 16 bytes = 128 bits.
static int XSecure_AesWaitForDone(const XSecure_Aes *InstancePtr)
This function waits for AES completion.
InstancePtr Pointer to the XSecure_Aes instance XST_SUCCESS - On successful key loadXST_FAILURE - On failure
static int XSecure_AesKeyLoad(const XSecure_Aes *InstancePtr, XSecure_AesKeySrc KeySrc, XSecure_AesKeySize KeySize)
This function configures and loads AES key from selected key source.
InstancePtr Pointer to the XSecure_Aes instance KeySrc Variable is of type XSecure_AesKeySrc which mentions the key source to be loaded into AES engine KeySize Size of the key selected XST_SUCCESS - On successful key loadXST_FAILURE - If a timeout has occurred
static int XSecure_AesKekWaitForDone(const XSecure_Aes *InstancePtr)
This function waits for AES key decryption completion.
InstancePtr Pointer to the XSecure_Aes instance XST_SUCCESS - On successXST_FAILURE - On failure
static int XSecure_AesOpInit(XSecure_Aes *InstancePtr, XSecure_AesKeySrc KeySrc, XSecure_AesKeySize KeySize, u64 IvAddr, u32 Mode)
This function validates and updates the mode of the AES and loads key and transfers IV to the AES engine.
InstancePtr Pointer to the XSecure_Aes instance KeySrc Key Source for decryption of the data KeySize Size of the AES key to be used for decryption: XSECURE_AES_KEY_SIZE_128 for 128 bit key size or XSECURE_AES_KEY_SIZE_256 for 256 bit key size IvAddr Address to the buffer holding IV Mode AES operation mode (XSECURE_AES_MODE_ENC for encryption or XSECURE_AES_MODE_DEC for decryption) XST_SUCCESS - On successful initXSECURE_AES_INVALID_PARAM - On invalid parameterXSECURE_AES_STATE_MISMATCH_ERROR - If State mismatch is occurredXST_FAILURE - On failure to configure switch
static int XSecure_AesPmcDmaCfgAndXfer(const XSecure_Aes *InstancePtr, XSecure_AesDmaCfg *AesDmaCfg, u32 Size)
This function configures the PMC DMA channels.
InstancePtr Pointer to the XSecure_Aes instance. AesDmaCfg DMA SRC and DEST channel configuration Size Size of data in bytes. XST_SUCCESS - On successful configurationXST_FAILURE - On failure
static int XSecureAesUpdate(const XSecure_Aes *InstancePtr, u64 InDataAddr, u64 OutDataAddr, u32 Size, u8 IsLastChunk)
This function is used to update the AES engine with provided input and output addresses.
InstancePtr Pointer to the XSecure_Aes instance InDataAddr Address of the input buffer. OutDataAddr Address of output buffer. Size Size of data to be updated by AES engine. IsLastChunk If this is the last update of data to be processed, this parameter should be set to TRUE otherwise FALSE XST_SUCCESS - On successXST_FAILURE - On failure
static int XSecure_AesIvXfer(const XSecure_Aes *InstancePtr, u64 IvAddr)
This function transfers IV to AES engine.
InstancePtr Pointer to the XSecure_Aes instance IvAddr Address to the buffer holding IV XST_SUCCESS - On successful transferXSECURE_AES_INVALID_PARAM - If Iv address is zeroXST_FAILURE - On failure
static int XSecure_AesKeyLoadandIvXfer(const XSecure_Aes *InstancePtr, XSecure_AesKeySrc KeySrc, XSecure_AesKeySize KeySize, u64 IvAddr)
This function initializes AES engine for encryption or decryption.
InstancePtr Pointer to the XSecure_Aes instance KeySrc Key Source for decryption of the data KeySize Size of the AES key to be used for decryption: XSECURE_AES_KEY_SIZE_128 for 128 bit key size or XSECURE_AES_KEY_SIZE_256 for 256 bit key size IvAddr Address to the buffer holding IV XST_SUCCESS - On successful initializationXST_FAILURE - On failure
static int XSecure_ValidateAndUpdateData(XSecure_Aes *InstancePtr, u64 InDataAddr, u64 OutDataAddr, u32 Size, u8 IsLastChunk)
This function is used to update the data to AES engine and stores the resultant data at specified address.
InstancePtr Pointer to the XSecure_Aes instance InDataAddr Address of the encrypted data which needs to be encrypted OutDataAddr Address of output buffer where the encrypted data to be updated Size Size of data to be decrypted in bytes, whereas number of bytes shall be aligned as follows: 16 byte aligned when it is not the last chunk or 4 byte aligned when the data is the last chunk IsLastChunk If this is the last update of data to be encrypted, this parameter should be set to TRUE otherwise FALSE XST_SUCCESS - On successful encryption of the dataXSECURE_AES_INVALID_PARAM - On invalid parameterXSECURE_AES_STATE_MISMATCH_ERROR - If State mismatch is occurredXST_FAILURE - On failure
static int XSecure_AesCopyGcmTag(const XSecure_Aes *InstancePtr, XSecure_AesDmaCfg *AesDmaCfg)
This function is used upon Last encrypt update.
AES engine also sends GCM tag along with encrypted data,copy the GCM tag to local buffer to properly flush the DMA to avoid data corruption,if the same DMA is used for different operation before AES encrypt final.This is also used to store the generated GCM Tag during AES update AAD in GMAC mode. InstancePtr Pointer to the XSecure_Aes instance AesDmaCfg DMA SRC and DEST channel configuration XST_SUCCESS - On successful copy of the GCM tagXST_FAILURE - On failure
int XSecure_AesInitialize(XSecure_Aes *InstancePtr, XPmcDma *PmcDmaPtr)
This function initializes the AES instance pointer.
InstancePtr Pointer to the XSecure_Aes instance PmcDmaPtr Pointer to the XPmcDma instance XST_SUCCESS - If initialization was successfulXSECURE_AES_INVALID_PARAM - Invalid parameterXSECURE_AES_DMA_COMPONENT_IS_NOT_READY - PMC DMA component is not readyXST_FAILURE - On SSS initialization failure All the inputs are accepted in little endian format, but AES engine accepts the data in big endianness, this will be taken care while passing data to AES engine
References XSECURE_AES_INVALID_PARAM.
int XSecure_AesSetDpaCm(const XSecure_Aes *InstancePtr, u32 DpaCmCfg)
This function enables or disables DPA counter measures in AES engine based on user input.
InstancePtr Pointer to the XSecure_Aes instance DpaCmCfg User choice to enable/disable DPA CM. Set to TRUE to enable AES DPA counter measure (Default setting) or FALSE to disable AES DPA counter measure XST_SUCCESS - If configuration is successXSECURE_AES_INVALID_PARAM - For invalid parameterXSECURE_AES_STATE_MISMATCH_ERROR - If State mismatch is occurredXSECURE_AES_DPA_CM_NOT_SUPPORTED - If DPA CM is disabled on chip (Enabling/Disabling in AES engine does not impact functionality)XST_FAILURE - On failure
References XSECURE_AES_INVALID_PARAM.
int XSecure_AesWriteKey(const XSecure_Aes *InstancePtr, XSecure_AesKeySrc KeySrc, XSecure_AesKeySize KeySize, u64 KeyAddr)
This function writes the key provided into the specified AES key registers.
InstancePtr Pointer to the XSecure_Aes instance KeySrc Key Source to be selected to which provided key should be updated: XSECURE_AES_USER_KEY_0, XSECURE_AES_USER_KEY_1, XSECURE_AES_USER_KEY_2, XSECURE_AES_USER_KEY_3, XSECURE_AES_USER_KEY_4, XSECURE_AES_USER_KEY_5, XSECURE_AES_USER_KEY_6, XSECURE_AES_USER_KEY_7, or XSECURE_AES_BH_KEY KeySize A variable of type XSecure_AesKeySize, which holds the size of the input key to be written: XSECURE_AES_KEY_SIZE_128 for 128 bit key size or XSECURE_AES_KEY_SIZE_256 for 256 bit key size KeyAddr Address of a buffer which should contain the key to be written XST_SUCCESS - On successful key written on AES registersXSECURE_AES_INVALID_PARAM - For invalid parameterXSECURE_AES_STATE_MISMATCH_ERROR - If State mismatch is occurredXST_FAILURE - On failure
References XSECURE_AES_INVALID_PARAM.
int XSecure_AesUpdateAad(XSecure_Aes *InstancePtr, u64 AadAddr, u32 AadSize)
This function is used to update the AES engine with Additional Authenticated Data(AAD).
InstancePtr Pointer to the XSecure_Aes instance AadAddr Address of the additional authenticated data AadSize Size of additional authenticated data in bytes, whereas number of bytes provided should be quad-word aligned(multiples of 16 bytes) for Versal For Versal Net, byte aligned data is accepted XST_SUCCESS - On successful update of AADXSECURE_AES_INVALID_PARAM - On invalid parameterXSECURE_AES_STATE_MISMATCH_ERROR - If State mismatch occursXST_FAILURE - On failure to update AAD The API must be called after XSecure_AesEncryptInit() or XSecure_AesDecryptInit()
int XSecure_AesKekDecrypt(const XSecure_Aes *InstancePtr, XSecure_AesKeySrc DecKeySrc, XSecure_AesKeySrc DstKeySrc, u64 IvAddr, XSecure_AesKeySize KeySize)
This function decrypts the KEK/obfuscated key which is found encrypted in boot header/eFUSE/BBRAM.
It then places it in the specified red key register. InstancePtr Pointer to the XSecure_Aes instance DecKeySrc Select key source which holds KEK and needs to be decrypted DstKeySrc Select the key in which decrypted red key should be updated IvAddr Address of IV holding buffer for decryption of the key KeySize A variable of type XSecure_AesKeySize, which specifies the size of the key: XSECURE_AES_KEY_SIZE_128 for 128 bit key size or XSECURE_AES_KEY_SIZE_256 for 256 bit key size XST_SUCCESS - On successful key decryptionXSECURE_AES_INVALID_PARAM - On invalid parameterXSECURE_AES_STATE_MISMATCH_ERROR - If State mismatch occursXST_FAILURE - If timeout has occurred
int XSecure_AesDecryptInit(XSecure_Aes *InstancePtr, XSecure_AesKeySrc KeySrc, XSecure_AesKeySize KeySize, u64 IvAddr)
This function initializes the AES engine for decryption.
InstancePtr Pointer to the XSecure_Aes instance KeySrc Key Source for decryption of the data KeySize Size of the AES key to be used for decryption (XSECURE_AES_KEY_SIZE_128 for 128 bit key size or XSECURE_AES_KEY_SIZE_256 for 256 bit key size) IvAddr Address to the buffer holding IV XST_SUCCESS - On successful initXSECURE_AES_INVALID_PARAM - On invalid parameterXSECURE_AES_STATE_MISMATCH_ERROR - If State mismatch is occurredXSECURE_AES_ZERO_PUF_KEY_NOT_ALLOWED - If keysrc is puf and puf key is zeroXST_FAILURE - On failure
int XSecure_AesDecryptUpdate(XSecure_Aes *InstancePtr, u64 InDataAddr, u64 OutDataAddr, u32 Size, u8 IsLastChunk)
This function is used to update the AES engine for decryption with provided data and stores the decrypted data at specified address.
InstancePtr Pointer to the XSecure_Aes instance InDataAddr Address of the encrypted data which needs to be decrypted OutDataAddr Address of output buffer where the decrypted to be updated Size Size of data to be decrypted in bytes, whereas number of bytes shall be aligned as follows for Versal: 16 byte aligned when it is not the last chunk or 4 byte aligned when the data is the last chunk. For Versal Net, byte aligned data is accepted IsLastChunk If this is the last update of data to be decrypted, this parameter should be set to TRUE otherwise FALSE XST_SUCCESS - On successful decryption of the dataXSECURE_AES_INVALID_PARAM - On invalid parameterXSECURE_AES_UNALIGNED_SIZE_ERROR - If input IsLastChunk is invalidXSECURE_AES_STATE_MISMATCH_ERROR - If State mismatch is occurredXST_FAILURE - On failure
int XSecure_AesDecryptFinal(XSecure_Aes *InstancePtr, u64 GcmTagAddr)
This function verifies the GCM tag provided for the data decrypted till the point.
InstancePtr Pointer to the XSecure_Aes instance GcmTagAddr Address of a buffer which should holds GCM Tag XST_SUCCESS - On successful GCM tag verificationXSECURE_AES_GCM_TAG_MISMATCH User provided GCM tag does not match calculated tagXSECURE_AES_INVALID_PARAM - Invalid parameterXSECURE_AES_INVALID_MODE Input mode is invalidXSECURE_AES_STATE_MISMATCH_ERROR - State mismatch occurredXSECURE_AES_KEY_CLEAR_ERROR - Key clear operation failedXST_FAILURE - On failure
int XSecure_AesDecryptData(XSecure_Aes *InstancePtr, u64 InDataAddr, u64 OutDataAddr, u32 Size, u64 GcmTagAddr)
This function decrypts the size (length) number of bytes of the passed in InDataAddr (source) buffer and stores the decrypted data in the OutDataAddr (destination) buffer and verifies GcmTagAddr.
InstancePtr Pointer to the XSecure_Aes instance InDataAddr Address of the encrypted data which needs to be decrypted OutDataAddr Address of output buffer where the decrypted to be updated Size Size of data to be decrypted in bytes, whereas number of bytes provided should be multiples of 4 for Versal For Versal Net, byte aligned data is acceptable GcmTagAddr Address of a buffer which should contain GCM Tag XST_SUCCESS - On successful decryption and GCM tag verificationXSECURE_AES_INVALID_PARAM - Invalid parameterXSECURE_AES_INVALID_MODE Input mode is invalidXSECURE_AES_STATE_MISMATCH_ERROR - State mismatch occurredXSECURE_AES_UNALIGNED_SIZE_ERROR - Size is not aligned for non-last chunkXSECURE_AES_GCM_TAG_MISMATCH GCM tag verification failedXSECURE_AES_KEY_CLEAR_ERROR - Key clear operation failedXST_FAILURE - On failure
int XSecure_AesEncryptInit(XSecure_Aes *InstancePtr, XSecure_AesKeySrc KeySrc, XSecure_AesKeySize KeySize, u64 IvAddr)
This function initializes the AES engine for encryption.
InstancePtr Pointer to the XSecure_Aes instance KeySrc Key Source for encryption KeySize Size of the AES key to be used for encryption (XSECURE_AES_KEY_SIZE_128 for 128 bit key size or XSECURE_AES_KEY_SIZE_256 for 256 bit key size) IvAddr Address to the buffer holding IV XST_SUCCESS - On successful initializationXSECURE_AES_INVALID_PARAM - On invalid parameterXSECURE_AES_STATE_MISMATCH_ERROR - If State mismatch is occurredXSECURE_AES_ZERO_PUF_KEY_NOT_ALLOWED - If keysrc is puf and puf key is zeroXST_FAILURE - On failure
int XSecure_AesEncryptUpdate(XSecure_Aes *InstancePtr, u64 InDataAddr, u64 OutDataAddr, u32 Size, u8 IsLastChunk)
This function is used to update the AES engine for encryption with provided data and stores the encrypted data at specified address.
InstancePtr Pointer to the XSecure_Aes instance InDataAddr Address of the data which needs to be encrypted OutDataAddr Address of output buffer where the encrypted data to be updated Size Size of data to be encrypted in bytes. For Versal, data shall be 16 byte aligned for non-last chunks and 4 byte aligned for the last chunk. For Versal Net, byte aligned data is acceptable IsLastChunk If this is the last update of data to be encrypted, this parameter should be set to TRUE otherwise FALSE XST_SUCCESS - On successful encryption of the dataXSECURE_AES_INVALID_PARAM - On invalid parameterXSECURE_AES_UNALIGNED_SIZE_ERROR - If input IsLastChunk is invalidXSECURE_AES_STATE_MISMATCH_ERROR - If State mismatch is occurredXST_FAILURE - On failure
References XSECURE_AES_INVALID_MODE, XSECURE_AES_INVALID_PARAM, XSECURE_AES_STATE_MISMATCH_ERROR, XSecure_AesPmcDmaCfgEndianness, XSECURE_DISABLE_BYTE_SWAP, XSecure_MemCpy64.
int XSecure_AesEncryptFinal(XSecure_Aes *InstancePtr, u64 GcmTagAddr)
This function updates the GCM tag for the encrypted data.
InstancePtr Pointer to the XSecure_Aes instance GcmTagAddr Address to the buffer of GCM tag size, where the API updates GCM tag XST_SUCCESS - On successful GCM tag updationXSECURE_AES_INVALID_PARAM - On invalid parameterXSECURE_AES_INVALID_MODE - If input mode is invalidXSECURE_AES_STATE_MISMATCH_ERROR - If State mismatch is occurredXST_FAILURE - On failure
int XSecure_AesEncryptData(XSecure_Aes *InstancePtr, u64 InDataAddr, u64 OutDataAddr, u32 Size, u64 GcmTagAddr)
This function encrypts size (length) number of bytes of the passed in InDataAddr (source) buffer and stores the encrypted data along with its associated 16 byte tag in the OutDataAddr (destination) buffer and GcmTagAddr (buffer) respectively.
InstancePtr Pointer to the XSecure_Aes instance InDataAddr Address of the data which needs to be encrypted OutDataAddr Address of output buffer where the encrypted data to be updated Size Size of data to be encrypted in bytes, whereas number of bytes provided should be multiples of 4 for Versal For Versal Net, byte aligned data is acceptable GcmTagAddr Address to the buffer of GCM tag size, where the API updates GCM tag XST_SUCCESS - On successful encryptionXSECURE_AES_INVALID_PARAM - Invalid parameterXSECURE_AES_INVALID_MODE Input mode is invalidXSECURE_AES_STATE_MISMATCH_ERROR - State mismatch occurredXSECURE_AES_UNALIGNED_SIZE_ERROR - Size is not aligned for non-last chunkXST_FAILURE - On failure
int XSecure_AesCfgKupKeyNIv(const XSecure_Aes *InstancePtr, u8 Config)
This function sets AES engine to update key and IV during decryption of secure header or footer of encrypted partition.
InstancePtr Pointer to the XSecure_Aes instance Config XSECURE_AES_ENABLE_KUP_IV_UPDATE to enable KUP and IV update, XSECURE_AES_DISABLE_KUP_IV_UPDATE to disable KUP and IV update XST_SUCCESS - On successful configurationXSECURE_AES_INVALID_PARAM - On invalid parameterXSECURE_AES_STATE_MISMATCH_ERROR - If State mismatch is occurredXST_FAILURE - On failure
References XSECURE_AES_INVALID_PARAM.
int XSecure_AesGetNxtBlkLen(const XSecure_Aes *InstancePtr, u32 *Size)
This function gives the AES next block length after decryption of PDI block.
InstancePtr Pointer to the XSecure_Aes instance Size Pointer to a 32 bit variable where next block length will be updated XST_SUCCESS - On successXSECURE_AES_INVALID_PARAM - On invalid parameterXSECURE_AES_STATE_MISMATCH_ERROR - If State mismatch is occurred
References XSECURE_AES_INVALID_PARAM.
int XSecure_AesKeyZero(const XSecure_Aes *InstancePtr, XSecure_AesKeySrc KeySrc)
This function zeroizes the selected AES key storage register.
InstancePtr Pointer to the XSecure_Aes instance KeySrc Select the key source which needs to be zeroized XST_SUCCESS - When key zeroization is successXST_INVALID_PARAM - if key source is invalidXSECURE_AES_INVALID_PARAM - On invalid parameterXSECURE_AES_STATE_MISMATCH_ERROR - If State mismatch is occurredXSECURE_AES_KEY_CLEAR_ERROR - AES key clear error
References XSECURE_AES_INVALID_PARAM.
int XSecure_AesDpaCmDecryptData(const XSecure_Aes *AesInstance, const u32 *KeyPtr, const u32 *DataPtr, u32 *OutputPtr)
This function updates data and key to the AES core in split mode with DPACM enabled.
AesInstance InstancePtr Pointer to the XSecure_Aes instance KeyPtr Key Pointer DataPtr Data Pointer OutputPtr Output where the decrypted data to be stored XST_SUCCESS - On successXSECURE_AESKAT_INVALID_PARAM - Invalid ArgumentXSECURE_AESDPACM_KAT_WRITE_KEY_FAILED_ERROR - Error when AESDPACM key write failsXSECURE_AESDPACM_KAT_KEYLOAD_FAILED_ERROR - Error when AESDPACM key load failsXSECURE_AESDPACM_SSS_CFG_FAILED_ERROR - Error when AESDPACM sss configuration failsXSECURE_AESDPACM_KAT_FAILED_ERROR - Error when AESDPACM KAT failsXST_FAILURE - On failure This function is used during DPACM KAT where key and data are updated in split mode with DPACM enabled
References XSECURE_AESKAT_INVALID_PARAM.
Referenced by XSecure_AesDecryptCmKat.
static int XSecure_AesWaitKeyLoad(const XSecure_Aes *InstancePtr)
This function waits for AES engine to complete key loading.
InstancePtr Pointer to the XSecure_Aes instance XST_SUCCESS - If the AES engine completes key loadingXST_FAILURE - If a timeout has occurred
int XSecure_AesGmacCfg(XSecure_Aes *InstancePtr, u32 IsGmacEn)
This function enables or disables the GMAC configuration.
InstancePtr Pointer to the XSecure_Aes instance IsGmacEn User choice to enable/disable GMAC XST_SUCCESS - On successful configurationXSECURE_AES_INVALID_PARAM - On invalid parameterXSECURE_AES_STATE_MISMATCH_ERROR - On state mismatch To generate GMAC on AAD data, this API must be called with IsGmacEn set to TRUE just before the last AAD update. After the last AAD update XSecure_AesEncryptFinal or XSecure_AesDecryptFinal must be called to generate or validate the GMAC tag.
References XSECURE_AES_INVALID_PARAM.
int XSecure_AesUpdateAadAndValidate(XSecure_Aes *InstancePtr, u64 AadAddr, u32 AadSize, u64 GcmTagAddr)
This function is used to update the AES engine with Additional Authenticated Data(AAD) and validate.
InstancePtr Pointer to the XSecure_Aes instance AadAddr Address of the additional authenticated data AadSize Size of additional authenticated data in bytes, whereas number of bytes provided should be multiples of 4 GcmTagAddr GCM tag of the additional authenticated data XST_SUCCESS AAD updation and validation is successXSECURE_AES_INVALID_PARAM - On invalid parameterXSECURE_AES_STATE_MISMATCH_ERROR - On state mismatchXSECURE_AES_GCM_TAG_MISMATCH User provided GCM tag does not match calculated tagXST_FAILURE - On failure
References XSECURE_AES_INVALID_PARAM.
int XSecure_CfgSssAes(XPmcDma *DmaPtr, const XSecure_Sss *SssInstance)
This function configures SSS to AES engine.
DmaPtr Pointer to the DMA instance SssInstance Pointer to SSS instance XST_SUCCESS On successful configurationXST_FAILURE On failure DmaPtr Pointer to the DMA instance SssInstance Pointer to SSS instance XST_SUCCESS on successful configurationError code on failure
References XSECURE_SSS_DMA0, XSECURE_SSS_DMA1, XSecure_SssAes.
static int XSecure_AesOperationInit(u32 SubsystemId, u32 SrcAddrLow, u32 SrcAddrHigh)
This function handler calls XSecure_AesEncryptInit or XSecure_AesDecryptInit server API based on the Operation type.
SubsystemId Subsystem ID. SrcAddrLow Lower 32 bit address of the XSecure_AesInitOps structure. SrcAddrHigh Higher 32 bit address of the XSecure_AesInitOps structure. XST_SUCCESS - If the initialization is successfulXST_FAILURE - On failure
static int XSecure_AesAadUpdate(u32 SubsystemId, u32 SrcAddrLow, u32 SrcAddrHigh, u32 Size, u32 IsGmacEn)
This function handler calls XSecure_AesGmacCfg and XSecure_AesUpdateAad server API.
SubsystemId Subsystem ID. SrcAddrLow Lower 32 bit address of the AAD data SrcAddrHigh Higher 32 bit address of the AAD data Size AAD Size IsGmacEn User choice to enable/disable GMAC XST_SUCCESS - If the AAD update is successfulXST_FAILURE - On failure
static int XSecure_AesEncUpdate(u32 SubsystemId, u32 SrcAddrLow, u32 SrcAddrHigh, u32 DstAddrLow, u32 DstAddrHigh)
This function handler calls XSecure_AesEncryptUpdate server API.
SubsystemId Subsystem ID. SrcAddrLow Lower 32 bit address of the XSecure_AesInParams structure. SrcAddrHigh Higher 32 bit address of the XSecure_AesInParams structure. DstAddrLow Lower 32 bit address of the Output buffer where encrypted data to be stored DstAddrHigh Higher 32 bit address of the output buffer where encrypted data to be stored XST_SUCCESS - If the encrypt update is successfulXST_FAILURE - On failure
static int XSecure_AesEncFinal(u32 SubsystemId, u32 DstAddrLow, u32 DstAddrHigh)
This function handler calls XSecure_AesEncryptFinal server API.
SubsystemId Subsystem ID. DstAddrLow Lower 32 bit address of the GCM-TAG to be stored. DstAddrHigh Higher 32 bit address of the GCM-TAG to be stored. XST_SUCCESS - If the encrypt final is successfulXST_FAILURE - On failure
static int XSecure_AesDecUpdate(u32 SubsystemId, u32 SrcAddrLow, u32 SrcAddrHigh, u32 DstAddrLow, u32 DstAddrHigh)
This function handler calls XSecure_AesDecryptUpdate server API.
SubsystemId Subsystem ID. SrcAddrLow Lower 32 bit address of the XSecure_AesInParams structure. SrcAddrHigh Higher 32 bit address of the XSecure_AesInParams structure. DstAddrLow Lower 32 bit address of the Output buffer where decrypted data to be stored DstAddrHigh Higher 32 bit address of the output buffer where decrypted data to be stored XST_SUCCESS - If the decrypt update is successfulXST_FAILURE - On failure
static int XSecure_AesDecFinal(u32 SubsystemId, u32 SrcAddrLow, u32 SrcAddrHigh)
This function handler calls XSecure_AesDecryptFinal server API.
SubsystemId Subsystem ID. SrcAddrLow Lower 32 bit address of the GCM-TAG SrcAddrHigh Higher 32 bit address of the GCM-TAG XST_SUCCESS - If the decrypt final is successfulXST_FAILURE - On failure
static int XSecure_AesDecryptKek(u32 SubsystemId, u32 KeyInfo, u32 IvAddrLow, u32 IvAddrHigh)
This function handler calls XSecure_AesDecryptKek server API.
SubsystemId Subsystem ID. KeyInfo KeyInfo contains KeySize, KeyDst and KeySrc IvAddrLow Lower 32 bit address of the IV IvAddrHigh Higher 32 bit address of the IV XST_SUCCESS - If the decryption is successfulXSECURE_AES_INVALID_PARAM - On invalid parameterXST_FAILURE - If timeout has occurred
static int XSecure_AesSetDpaCmConfig(u8 DpaCmCfg)
This function handler calls XSecure_AesSetDpaCm server API.
DpaCmCfg User DpaCmCfg configuration XST_SUCCESS - If the Set DpaCm is successfulXST_FAILURE - On failure
static int XSecure_IsKeySrcValid(u32 KeySrc)
This function checks for valid KeySrc.
KeySrc Aes key source XST_SUCCESS - If KeySrc is ValidXSECURE_AES_DEVICE_KEY_NOT_ALLOWED - If KeySrc is Invalid
static int XSecure_AesConfig(u32 OperationId, u32 KeySrc, u32 KeySize, u64 IvAddr)
This function is used to validate key source and initialise the encryption/decryption.
OperationId Decides whether operation is encryption/decryption KeySrc Aes key source KeySize Aes key size IvAddr Iv address XST_SUCCESS - If AES configured successfullyXST_FAILURE - On failure
int XSecure_AesIpiHandler(XPlmi_Cmd *Cmd)
This function calls respective IPI handler based on the API_ID.
Cmd is a pointer to the command structure XST_SUCCESS - If the handler execution is successfulXST_INVALID_PARAM - On invalid parameterXST_DEVICE_BUSY - If IPI channel is busy
References XSecure_AesKeyWrite, XSecure_AesKeyZeroize, XSecure_AesPerformOperation, XSECURE_API, XSECURE_API_AES_DECRYPT_FINAL, XSECURE_API_AES_DECRYPT_UPDATE, XSECURE_API_AES_ENCRYPT_FINAL, XSECURE_API_AES_ENCRYPT_UPDATE, XSECURE_API_AES_INIT, XSECURE_API_AES_KEK_DECRYPT, XSECURE_API_AES_KEY_ZERO, XSECURE_API_AES_OP_INIT, XSECURE_API_AES_PERFORM_OPERATION, XSECURE_API_AES_SET_DPA_CM, XSECURE_API_AES_UPDATE_AAD, XSECURE_API_AES_WRITE_KEY, XSECURE_API_ID_MASK, XSECURE_DEBUG_GENERAL, XSecure_GetAesInstance, XSecure_IpiEventHandling, XSecure_MakeResFree, XSecure_Printf.
int XSecure_AesInit(void)
This function handler calls XSecure_AesInitialize Server API.
XST_SUCCESS - If the initialization is successfulXST_FAILURE - If PMCDMA instance is NULL.
References XSecure_AesInitialize, XSecure_GetAesInstance, XSECURE_PMCDMA_DEVICEID.
int XSecure_AesKeyZeroize(u32 KeySrc)
This function handler calls XSecure_AesKeyZero server API.
KeySrc Key source to be zeroized XST_SUCCESS - If the key zeroize is successfulXSECURE_AES_INVALID_PARAM - On invalid parameterXST_FAILURE - On failure
References XSECURE_AES_EXPANDED_KEYS, XSECURE_AES_INVALID_PARAM, XSECURE_AES_KUP_KEY, XSECURE_AES_PUF_KEY, XSECURE_AES_USER_KEY_0, XSECURE_AES_USER_KEY_7, XSecure_AesKeyZero, XSecure_GetAesInstance.
Referenced by XSecure_AesIpiHandler.
int XSecure_AesKeyWrite(u32 SubsystemId, u8 KeySize, u8 KeySrc, u32 KeyAddrLow, u32 KeyAddrHigh)
This function handler calls XSecure_AesWriteKey server API.
SubsystemId Subsystem ID. KeySize Size of the key to specify 128/256 bit key KeySrc KeySrc to which key has to be written KeyAddrLow Lower 32 bit address of the Key KeyAddrHigh Higher 32 bit address of the Key XST_SUCCESS - If the key write is successfulXSECURE_AES_INVALID_PARAM - For invalid parameterXST_FAILURE - On failure
References XSECURE_AES_BH_KEY, XSECURE_AES_BH_RED_KEY, XSECURE_AES_INVALID_PARAM, XSecure_AesWriteKey, XSECURE_ERR_INVALID_ADDR_RANGE, XSecure_GetAesInstance.
Referenced by XSecure_AesIpiHandler.
int XSecure_AesPerformOperation(u32 SubsystemId, u32 SrcAddrLow, u32 SrcAddrHigh)
This function handler calls XSecure_AesPerformOperation.
SubsystemId Subsystem ID. SrcAddrLow Lower 32 bit address of the XSecure_AesDataBlockParams structure. SrcAddrHigh Higher 32 bit address of the XSecure_AesDataBlockParams structure. XST_SUCCESS - If the initialization is successfulXST_FAILURE - On failure
References XSecure_AesDecryptData, XSecure_AesDecryptFinal, XSecure_AesEncryptData, XSecure_AesEncryptFinal, XSECURE_ENCRYPT, XSECURE_ERR_INVALID_ADDR_RANGE, XSecure_GetAesInstance.
static int XSecure_AesEcbDecryptInit(XSecure_Aes *InstancePtr, XSecure_AesKeySrc KeySrc, XSecure_AesKeySize KeySize)
This function sets and initializes AES in ECB mode.
InstancePtr Pointer to the XSecure_Aes instance KeySrc Key Source for decryption of the data KeySize Size of the AES key to be used for decryption: XSECURE_AES_KEY_SIZE_128 for 128 bit key size or XSECURE_AES_KEY_SIZE_256 for 256 bit key size XST_SUCCESS - On SuccessXST_FAILURE - On Failure
int XSecure_AesEcbCfg(XSecure_Aes *InstancePtr, u32 EcbModeFlag)
This function sets AES ECB mode.
InstancePtr Pointer to the XSecure_Aes instance EcbModeFlag Flag to enable/disable ECB mode XST_SUCCESS - On SuccessXSECURE_AES_INVALID_PARAM - On invalid parameterXSECURE_AES_STATE_MISMATCH_ERROR - On state mismatch
References XSECURE_AES_ECB_MODE_DIS, XSECURE_AES_ECB_MODE_EN, XSECURE_AES_ECB_OFFSET, XSECURE_AES_INVALID_PARAM, XSECURE_AES_STATE_MISMATCH_ERROR.
int XSecure_AesEcbDecrypt(XSecure_Aes *InstancePtr, u64 KeyAddr, XSecure_AesKeySize KeySize, u64 InDataAddr, u64 OutDataAddr, u32 Size)
This function writes AES key into XSECURE_AES_USER_KEY_7 and decrypts the data in ECB mode.
InstancePtr Pointer to the XSecure_Aes instance KeyAddr Address of the key to be programmed in XSECURE_AES_USER_KEY_7 KeySize Size of the AES key to be used for decryption: XSECURE_AES_KEY_SIZE_128 for 128 bit key size or XSECURE_AES_KEY_SIZE_256 for 256 bit key size InDataAddr Address of the encrypted data which needs to be decrypted OutDataAddr Address of output buffer where the decrypted data to be updated Size Size of data to be decrypted in bytes. Data shall be 16 byte aligned for non-last chunks and 4 byte aligned when it is the last chunk XST_SUCCESS - On SuccessXST_FAILURE - On Failure
References XSECURE_AES_ECB_MODE_DIS, XSECURE_AES_ECB_OFFSET, XSECURE_AES_USER_KEY_7, XSecure_AesDecryptUpdate, XSecure_AesKeyZero, XSecure_AesWriteKey, XSECURE_DISABLE_BYTE_SWAP, XSecure_SetReset.
int XSecure_AesKeyUnwrap(XSecure_Aes *InstancePtr, u8 *EphAesKey, XSecure_AesKeySize KeySize, u8 *AesWrapKey, u64 OutDataAddr, u32 Size)
This function unwraps the given AES wrapped key.
InstancePtr Pointer to the XSecure_Aes instance EphAesKey Address of the key to be programmed in XSECURE_AES_USER_KEY_7 KeySize Size of the AES key to be used for decryption: XSECURE_AES_KEY_SIZE_128 for 128 bit key size or XSECURE_AES_KEY_SIZE_256 for 256 bit key size AesWrapKey Address of the wrapped key which needs to be decrypted OutDataAddr Address of output buffer where the decrypted data to be updated Size Size of data to be decrypted in bytes. Data shall be 16 byte aligned for non-last chunks and 4 byte aligned when it is the last chunk XST_SUCCESS - On success.XSECURE_ERR_AES_KEY_SIZE_NOT_SUPPORTED - If AES key size is invalid.XSECURE_ERR_AES_KEY_UNWRAP_FAILED_ERROR - If key unwrap is failed.XST_FAILURE - On failure.
References XSECURE_AES_128BIT_MAX_KEY_BLOCK_ROUNDS, XSECURE_AES_256BIT_MAX_KEY_BLOCK_ROUNDS, XSECURE_AES_64BIT_BLOCK_SIZE, XSECURE_AES_ECB_MODE_DIS, XSECURE_AES_ECB_OFFSET, XSECURE_AES_KEY_WRAP_INIT_DEF_VAL, XSECURE_AES_KEY_WRAP_MAX_ROUNDS, XSECURE_AES_USER_KEY_7, XSecure_AesDecryptUpdate, XSecure_AesKeyZero, XSecure_AesWriteKey, XSECURE_DISABLE_BYTE_SWAP, XSECURE_ERR_AES_KEY_SIZE_NOT_SUPPORTED, XSECURE_ERR_AES_KEY_UNWRAP_FAILED_ERROR, XSecure_SetReset.
Referenced by XSecure_KeyUnwrap.
static int XSecure_AesPerformOperationAndZeroizeKey(u32 SubsystemId, u32 AesParamsAddrLow, u32 AesParamsAddrHigh, u32 KeyAddrLow, u32 KeyAddrHigh)
This function performs below operation:
- Write key into the key source provided by the user - Encrypt/decrypt a single block of data using the provided key - Zeroize the key once the AES operation is done SubsystemId Subsystem ID. AesParamsAddrLow Lower 32 bit address of the XSecure_AesDataBlockParams structure. AesParamsAddrHigh Upper 32 bit address of the XSecure_AesDataBlockParams structure. KeyAddrLow Lower 32 bit address of the buffer which stores the key KeyAddrHigh Upper 32 bit address of the buffer which stores the key XST_SUCCESS In case of successXST_FAILURE In case of failure
int XSecure_PlatAesIpiHandler(XPlmi_Cmd *Cmd)
This function calls respective IPI handler based on the API_ID.
Cmd is a pointer to the command structure XST_SUCCESS - If the handler execution is successful.XST_INVALID_PARAM - If input parameter is invalid.XST_FAILURE - If there is a failure.
References XSecure_AesPerformOperationAndZeroizeKey, XSECURE_API, XSECURE_API_AES_PERFORM_OPERATION_AND_ZEROIZE_KEY, XSECURE_API_ID_MASK, XSECURE_DEBUG_GENERAL, XSecure_GetAesInstance, XSecure_IpiEventHandling, XSecure_MakeResFree, XSecure_Printf.
XSECURE_KEK_DEC_ENABLE
Triggers decryption operation for black key.
XSECURE_AES_DISABLE_KUP_IV_UPDATE
Disables IV and Key save features for KUP.
XSECURE_AES_ENABLE_KUP_IV_UPDATE
Enables IV and Key save features for KUP.
XSECURE_AES_AAD_ENABLE
Enables authentication of data pushed in AES engine.
XSECURE_AES_AAD_DISABLE
Disables authentication of data pushed in AES engine.
XSECURE_AES_DEC_KEY_SRC_MASK
AES decrypt key source mask for KEK decryption.
XSECURE_AES_DST_KEY_SRC_MASK
AES destination key source mask for KEK decryption.
XSECURE_AES_KEY_SIZE_MASK
Key Size mask.
XSECURE_PMCDMA_DEVICEID
AES destination key source mask for KEK decryption.
Referenced by XSecure_AesInit.
XSECURE_AES_KEY_WRAP_MAX_ROUNDS
AES key wrap maximum rounds.
Referenced by XSecure_AesKeyUnwrap.
XSECURE_AES_256BIT_MAX_KEY_BLOCK_ROUNDS
AES 256-bit number of blocks.
Referenced by XSecure_AesKeyUnwrap.
XSECURE_AES_128BIT_MAX_KEY_BLOCK_ROUNDS
AES 128-bit number of blocks.
Referenced by XSecure_AesKeyUnwrap.
XSECURE_AES_KEY_WRAP_INIT_DEF_VAL
AES init default value.
Referenced by XSecure_AesKeyUnwrap.
XSECURE_AES_ECB_MODE_EN
AES ECB Mode Enable.
Referenced by XSecure_AesEcbCfg.
XSECURE_AES_ECB_MODE_DIS
AES ECB Mode Enable.
Referenced by XSecure_AesEcbCfg, XSecure_AesEcbDecrypt, XSecure_AesKeyUnwrap.
XSECURE_AES_64BIT_BLOCK_SIZE
AES 64-bit block size in bytes.
Referenced by XSecure_AesKeyUnwrap, XSecure_KeyUnwrap.
XSECURE_AES_MODULE_MAJOR_VERSION
AES module major version.
XSECURE_AES_MODULE_MINOR_VERSION
AES module minor version.
XSECURE_AES_MODULE_MAJOR_VERSION
AES module major version.
XSECURE_AES_MODULE_MINOR_VERSION
AES module minor version.
XSECURE_AES_MODULE_MAJOR_VERSION
AES module major version.
XSECURE_AES_MODULE_MINOR_VERSION
AES module minor version.