xsecure_kat_client_apis
int XSecure_AesDecryptKat(XSecure_ClientInstance *InstancePtr)
This function sends IPI request to PLM to perform decrypt KAT on AES engine.
InstancePtr Pointer to the client instance XST_SUCCESS When KAT PassXST_FAILURE On failure
References XSECURE_API_AES_DECRYPT_KAT, XSECURE_API_KAT, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
int XSecure_AesDecryptCmKat(XSecure_ClientInstance *InstancePtr)
This function sends IPI request to PLM to perform KAT on AES DPA countermeasure KAT.
InstancePtr Pointer to the client instance XST_SUCCESS On successXST_INVALID_PARAM If input parameters are invalidXST_FAILURE On failure
References XSECURE_API_AES_DECRYPT_CM_KAT, XSECURE_API_KAT, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
int XSecure_RsaPublicEncKat(XSecure_ClientInstance *InstancePtr)
This function sends IPI request to PLM to perform RSA encrypt KAT.
InstancePtr Pointer to the client instance XST_SUCCESS On successXST_INVALID_PARAM If input parameters are invalidXST_FAILURE On failure
References XSECURE_API_KAT, XSECURE_API_RSA_PUB_ENC_KAT, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
Referenced by main.
int XSecure_Sha3Kat(XSecure_ClientInstance *InstancePtr)
This function sends IPI request to PLM to perform SHA3 KAT.
InstancePtr Pointer to the client instance XST_SUCCESS When KAT PassXST_INVALID_PARAM If input parameters are invalidXST_FAILURE On failure
References XSECURE_API_KAT, XSECURE_API_SHA3_KAT, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
int XSecure_EllipticSignVerifyKat(XSecure_ClientInstance *InstancePtr, XSecure_EccCrvClass CurveClass)
This function sends IPI request to PLM to perform ECC sign verify KAT.
InstancePtr Pointer to the client instance CurveClass Type of elliptic curve class(Prime - 0, Binary - 1) XST_SUCCESS On successXST_INVALID_PARAM If input parameters are invalidXST_FAILURE On failure
References XSECURE_API_ELLIPTIC_SIGN_VERIFY_KAT, XSECURE_API_KAT, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
Referenced by main, XSecure_KatIpiHandler.
int XSecure_AesEncryptKat(XSecure_ClientInstance *InstancePtr)
This function sends IPI request to PLM to perform encrypt KAT.
InstancePtr Pointer to the client instance XST_SUCCESS When KAT PassXST_INVALID_PARAM If input parameters are invalidXST_FAILURE On failure
References XSECURE_API_AES_ENCRYPT_KAT, XSECURE_API_KAT, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
int XSecure_RsaPrivateDecKat(XSecure_ClientInstance *InstancePtr)
This function sends IPI request to PLM to perform RSA private decrypt KAT.
InstancePtr Pointer to the client instance XST_SUCCESS On successXST_INVALID_PARAM If input parameters are invalidXST_FAILURE On failure
References XSECURE_API_KAT, XSECURE_API_RSA_PRIVATE_DEC_KAT, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
Referenced by XSecure_KatIpiHandler.
int XSecure_EllipticSignGenKat(XSecure_ClientInstance *InstancePtr, XSecure_EccCrvClass CurveClass)
This function sends IPI request to PLM to perform ECC sign generate KAT.
InstancePtr Pointer to the client instance CurveClass Type of elliptic curve class(Prime - 0, Binary - 1) XST_SUCCESS On successXST_INVALID_PARAM If input parameters are invalidXST_FAILURE On failure
References XSECURE_API_ELLIPTIC_SIGN_GEN_KAT, XSECURE_API_KAT, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
Referenced by main, XSecure_KatIpiHandler.
int XSecure_TrngKat(XSecure_ClientInstance *InstancePtr)
This function sends IPI request to PLM to perform TRNG KAT and health tests.
InstancePtr Pointer to the client instance XST_SUCCESS When KAT PassXST_INVALID_PARAM If any input parameter is invalid.XST_FAILURE If there is a failure InstancePtr Pointer to the client instance. XST_SUCCESS If KAT passes.XST_INVALID_PARAM If any input parameter is invalid.XST_FAILURE If there is a failure.
References XSECURE_API_KAT, XSECURE_API_TRNG_KAT, XSecure_ProcessMailbox.
Referenced by main, XSecure_KatPlatIpiHandler.
static int XSecure_UpdateKatStatus(XSecure_ClientInstance *InstancePtr, XSecure_KatOp KatOp, u32 KatMaskLen, u32 *KatMask, u32 ApiId)
This function sends IPI request to PLM to set or clear kat mask of HNIC.
InstancePtr Pointer to the client instance KatOp Operation to set or clear KAT mask KatMaskLen Length of the KAT mask KatMask KAT ApiId IPI request API ID XST_SUCCESS On SuccessXST_INVALID_PARAM If any input parameter is invalid.XST_FAILURE If there is a failure
int XSecure_UpdateHnicKatStatus(XSecure_ClientInstance *InstancePtr, XSecure_KatOp KatOp, u32 KatMaskLen, u32 *KatMask)
This function sends IPI request to PLM to set or clear kat mask of HNIC.
InstancePtr Pointer to the client instance KatOp Operation to set or clear KAT mask KatMaskLen Length of the KAT mask KatMask KAT mask XST_SUCCESS On SuccessXST_FAILURE On failure
References XSECURE_API_UPDATE_HNIC_KAT_STATUS, XSECURE_MIN_KAT_MASK_LEN.
int XSecure_UpdateCpm5NKatStatus(XSecure_ClientInstance *InstancePtr, XSecure_KatOp KatOp, u32 KatMaskLen, u32 *KatMask)
This function sends IPI request to PLM to set or clear kat mask of CPM5N.
InstancePtr Pointer to the client instance KatOp Operation to set or clear KAT mask KatMaskLen Length of the KAT mask KatMask KAT mask XST_SUCCESS On SuccessXST_FAILURE On failure
References XSECURE_API_UPDATE_CPM5N_KAT_STATUS, XSECURE_MIN_KAT_MASK_LEN.
int XSecure_UpdatePcideKatStatus(XSecure_ClientInstance *InstancePtr, XSecure_KatOp KatOp, u32 KatMaskLen, u32 *KatMask)
This function sends IPI request to PLM to set or clear kat mask of PCIDE.
InstancePtr Pointer to the client instance KatOp Operation to set or clear KAT mask KatMaskLen Length of the KAT mask KatMask KAT mask XST_SUCCESS On SuccessXST_FAILURE On failure
References XSECURE_API_UPDATE_PCIDE_KAT_STATUS, XSECURE_MIN_KAT_MASK_LEN.
int XSecure_UpdatePkiKatStatus(XSecure_ClientInstance *InstancePtr, XSecure_KatOp KatOp, u32 KatMaskLen, u32 *KatMask)
This function sets or clears KAT mask of PKI.
InstancePtr Pointer to the client instance KatOp Operation to set or clear KAT mask KatMaskLen Length of the KAT mask KatMask Pointer to the KAT mask XST_SUCCESS If set or clear is successfulXST_FAILURE On failure
References XSECURE_API_UPDATE_PKI_KAT_STATUS, XSECURE_MAX_KAT_MASK_LEN.