xsecure_sha_server_apis
R0
< R0, R1, R2, R3, R4 are the different intermediate operations used in SHA1 digest calculation
Referenced by XSecure_AesDecryptCmKat.
R1
R2
R3
R4
static int XSecure_Sha3WaitForDone(const XSecure_Sha3 *InstancePtr)
This inline function waits till SHA3 completes its operation.
InstancePtr Pointer to the XSecure_Sha3 instance XST_SUCCESS - If the SHA3 completes its operationXST_FAILURE - If a timeout has occurred
static int XSecure_Sha3DmaTransfer(const XSecure_Sha3 *InstancePtr, u64 InDataAddr, const u32 Size, u8 IsLastUpdate)
This function transfers data through DMA.
InstancePtr Pointer to the XSecure_Sha3 instance InDataAddr Starting address of the data which has to be updated to SHA engine Size Size of the input data in bytes IsLastUpdate Flag to indicate whether this is the last update or not XST_SUCCESS - If the update is successfulXST_FAILURE In case of an error
static int XSecure_Sha3DataUpdate(XSecure_Sha3 *InstancePtr, u64 InDataAddr, const u32 Size, u8 IsLastUpdate)
This function updates hash for data block of size <= 512MB.
InstancePtr Pointer to the XSecure_Sha3 instance InDataAddr Starting address of the data, which has to be updated to SHA engine Size Size of the input data in bytes IsLastUpdate Flag to indicate whether this is the last update or not XST_SUCCESS - If the update is successfulXST_FAILURE - If there is a failure
static int XSecure_Sha3NistPadd(u8 *Dst, u32 MsgLen)
Generate padding for the NIST SHA-3.
Dst Pointer to location where padding is to be applied MsgLen Is the length of padding in bytes XST_SUCCESS - On successfulXSECURE_SHA3_INVALID_PARAM - On invalid parameterXST_FAILURE - On failure
int XSecure_Sha3Initialize(XSecure_Sha3 *InstancePtr, XPmcDma *DmaPtr)
This function initializes a XSecure_Sha3 structure with the default values required for operating the SHA3 cryptographic engine.
InstancePtr Pointer to the XSecure_Sha3 instance DmaPtr Pointer to the XPmcDma instance XST_SUCCESS - If initialization was successfulXSECURE_SHA3_INVALID_PARAM - On invalid parameterXST_FAILURE - On failure
References XSECURE_SHA3_0_DEVICE_ID, XSECURE_SHA3_INVALID_PARAM, XSecure_Sha3LookupConfig, XSECURE_SHA_INITIALIZED, XSecure_SssInitialize.
s32 XSecure_Sha3LastUpdate(XSecure_Sha3 *InstancePtr)
This function notifies the SHA driver at the end of the SHA data update and last update includes padding also.
SHA3 Last Update Call Function.This function is called before XSecure_Sha3Finish to prevent driver adding the padding. InstancePtr Pointer to the XSecure_Sha3 instance XST_SUCCESS - If last update can be acceptedXSECURE_SHA3_INVALID_PARAM - On invalid parameterXSECURE_SHA3_STATE_MISMATCH_ERROR - If State mismatch is occurred
References XSECURE_SHA3_INVALID_PARAM, XSECURE_SHA3_STATE_MISMATCH_ERROR.
Referenced by XSecure_ShaLastUpdate.
void XSecure_Sha3Start(XSecure_Sha3 *InstancePtr)
This function configures Secure Stream Switch and starts the SHA-3 engine.
SHA3 Start Function. InstancePtr Pointer to the XSecure_Sha3 instance XST_SUCCESS - On successfulXSECURE_SHA3_INVALID_PARAM - On invalid parameterXSECURE_SHA3_STATE_MISMATCH_ERROR - If State mismatch is occurredXST_FAILURE - On failure
References XSECURE_CORE_SHA, XSecure_CryptoCheck, XSecure_ReleaseReset, XSECURE_SHA3_BLOCK_LEN, XSECURE_SHA3_INVALID_PARAM, XSECURE_SHA3_RESET_OFFSET, XSECURE_SHA3_START_OFFSET, XSECURE_SHA3_STATE_MISMATCH_ERROR, XSECURE_SHA_INITIALIZED.
Referenced by XSecure_Sha3Digest, XSecure_Sha3Hash, XSecure_ShaStart, XSecure_SpkAuthentication.
int XSecure_Sha3Update64Bit(XSecure_Sha3 *InstancePtr, u64 InDataAddr, const u32 Size)
This function updates the SHA3 engine with the input data located at a 64-bit address.
InstancePtr Pointer to the XSecure_Sha3 instance InDataAddr Starting 64 bit address of the data which has to be updated to SHA engine Size Size of the input data in bytes XST_SUCCESS - If the update is successfulXSECURE_SHA3_INVALID_PARAM - On invalid parameterXSECURE_SHA3_STATE_MISMATCH_ERROR - If State mismatch is occurredXST_FAILURE - If there is a failure in SSS configuration
References XSecure_SetReset, XSECURE_SHA3_INVALID_PARAM, XSECURE_SHA3_RESET_OFFSET, XSECURE_SHA3_STATE_MISMATCH_ERROR, XSECURE_SHA_INITIALIZED.
Referenced by XSecure_Sha3Update, XSecure_ShaUpdate.
int XSecure_Sha3Update(XSecure_Sha3 *InstancePtr, const u64 InDataAddr, const u32 Size)
This function updates the SHA3 engine with the input data.
InstancePtr Pointer to the XSecure_Sha3 instance InDataAddr Starting address of the data which has to be updated to SHA engine Size Size of the input data in bytes XST_SUCCESS - If the update is successfulXSECURE_SHA3_INVALID_PARAM - On invalid parameterXSECURE_SHA3_STATE_MISMATCH_ERROR - If State mismatch is occurredXST_FAILURE - If there is a failure in SSS configuration
References XSecure_Sha3Update64Bit.
int XSecure_Sha3Finish(XSecure_Sha3 *InstancePtr, XSecure_Sha3Hash *Sha3Hash)
This function updates SHA3 engine with final data which includes SHA3 padding and reads final hash on complete data.
InstancePtr Pointer to the XSecure_Sha3 instance Sha3Hash Pointer to XSecure_Sha3Hash structure, where output hash is stored into Hash which is a member of XSecure_Sha3Hash structure XST_SUCCESS - If finished without any errorsXSECURE_SHA3_INVALID_PARAM - On invalid parameterXSECURE_SHA3_STATE_MISMATCH_ERROR - If State mismatch is occurredXST_FAILURE - If Sha3PadType is other than KECCAK or NIST
References XSecure_SetReset, XSECURE_SHA3_BLOCK_LEN, XSECURE_SHA3_INVALID_PARAM, XSECURE_SHA3_RESET_OFFSET, XSECURE_SHA3_STATE_MISMATCH_ERROR, XSecure_Sha3ReadHash, XSecure_Sha3WaitForDone, XSECURE_SHA_INITIALIZED.
int XSecure_Sha3Digest(XSecure_Sha3 *InstancePtr, const u64 InDataAddr, const u32 Size, XSecure_Sha3Hash *Sha3Hash)
This function calculates the SHA-3 digest on the given input data.
InstancePtr Pointer to the XSecure_Sha3 instance InDataAddr Starting address of the data on which sha3 hash should be calculated Size Size of the input data Sha3Hash Pointer to XSecure_Sha3Hash structure, where output hash is stored into Hash which is a member of XSecure_Sha3Hash structure XST_SUCCESS - If digest calculation done successfullyXSECURE_SHA3_INVALID_PARAM - On invalid parameterXST_FAILURE - If any error from Sha3Update or Sha3Finish
References XSECURE_SHA3_INVALID_PARAM, XSecure_Sha3Finish, XSecure_Sha3Start, XSecure_Sha3Update.
int XSecure_Sha3ReadHash(const XSecure_Sha3 *InstancePtr, XSecure_Sha3Hash *Sha3Hash)
This function reads the SHA3 hash of the data and it can be called between calls to XSecure_Sha3Update.
InstancePtr Pointer to the XSecure_Sha3 instance Sha3Hash Pointer to XSecure_Sha3Hash structure, where output hash is stored into Hash which is a member of XSecure_Sha3Hash structure XST_SUCCESS - On successfulXSECURE_SHA3_INVALID_PARAM - On invalid parameterXSECURE_SHA3_STATE_MISMATCH_ERROR - If State mismatch is occurredXST_FAILURE - On failure
References XSECURE_SHA3_DIGEST_0_OFFSET, XSECURE_SHA3_INVALID_PARAM, XSECURE_WORD_SIZE.
Referenced by XSecure_Sha3Finish.
int XSecure_Sha3LookupConfig(XSecure_Sha3 *InstancePtr, u32 DeviceId)
This function assigns SHA3 configuration to the InstancePtr.
InstancePtr Pointer to XSecure_Sha3Instance DeviceId Deviceid of the SHA3 XST_SUCCESS - On successful initializationXST_FAILURE - On failure
References XSECURE_SHA3_NUM_OF_INSTANCES.
Referenced by XSecure_Sha3Initialize, XSecure_ShaLookupConfig.
int XSecure_ShaInitialize(XSecure_Sha *InstancePtr, XPmcDma *DmaPtr)
This function initializes a XSecure_Sha3 structure with the default values required for operating the SHA3 cryptographic engine.
InstancePtr Pointer to the XSecure_Sha3 instance DmaPtr Pointer to the XPmcDma instance XST_SUCCESS - If initialization was successfulXSECURE_SHA3_INVALID_PARAM - On invalid parameter
References XSecure_Sha3Initialize.
Referenced by XSecure_AesShaInit, XSecure_HssInit.
int XSecure_ShaStart(XSecure_Sha *InstancePtr, XSecure_ShaMode ShaMode)
This function configures Secure Stream Switch and starts the SHA-3 engine.
InstancePtr Pointer to the XSecure_Sha3 instance ShaMode SHA mode to be set XST_SUCCESS - On successfulXSECURE_SHA3_INVALID_PARAM - On invalid parameterXSECURE_SHA3_STATE_MISMATCH_ERROR - If State mismatch is occurred
References XSecure_Sha3Start.
Referenced by XSecure_HmacFinal, XSecure_HmacInit, XSecure_LmsHashMessage, XSecure_Sha3Kat, XSecure_ShaDigest, XSecure_ShakeKat, XSecure_SlhdsaShake256sChain, XSecure_SlhdsaShake256sHashF, XSecure_SlhdsaShake256sHashH, XSecure_SlhdsaShake256sHashMsg, XSecure_SlhdsaShake256sHashTl.
int XSecure_ShaUpdate(XSecure_Sha *InstancePtr, u64 DataAddr, const u32 DataSize)
This function updates the SHA3 engine with the input data located at a 64-bit address.
InstancePtr Pointer to the XSecure_Sha3 instance DataAddr Starting 64 bit address of the data which has to be updated to SHA engine DataSize Size of the input data in bytes XST_SUCCESS - If the update is successfulXSECURE_SHA3_INVALID_PARAM - On invalid parameterXSECURE_SHA3_STATE_MISMATCH_ERROR - If State mismatch is occurredXST_FAILURE - If there is a failure in SSS configuration
References XSecure_Sha3Update64Bit.
Referenced by XSecure_HmacFinal, XSecure_HmacInit, XSecure_HmacUpdate, XSecure_LmsHashMessage, XSecure_Sha3Kat, XSecure_ShaDigest, XSecure_ShakeKat, XSecure_SlhdsaShake256sChain, XSecure_SlhdsaShake256sHashF, XSecure_SlhdsaShake256sHashH, XSecure_SlhdsaShake256sHashMsg, XSecure_SlhdsaShake256sHashTl.
int XSecure_ShaLastUpdate(XSecure_Sha *InstancePtr)
This function notifies the SHA driver at the end of the SHA data update and last update includes padding also.
Typically called before XSecure_Sha3Finish to prevent driver adding the padding. InstancePtr Pointer to the XSecure_Sha3 instance XST_SUCCESS - If last update can be acceptedXSECURE_SHA3_INVALID_PARAM - On invalid parameterXSECURE_SHA3_STATE_MISMATCH_ERROR - If State mismatch is occurred
References XSecure_Sha3LastUpdate.
Referenced by XSecure_LmsHashMessage, XSecure_Sha3Kat, XSecure_ShaDigest, XSecure_ShakeKat, XSecure_SlhdsaShake256sChain, XSecure_SlhdsaShake256sHashF, XSecure_SlhdsaShake256sHashH, XSecure_SlhdsaShake256sHashMsg, XSecure_SlhdsaShake256sHashTl.
int XSecure_ShaFinish(XSecure_Sha *InstancePtr, u64 HashAddr, const u32 HashBufSize)
This function updates SHA3 engine with final data which includes SHA3 padding and reads final hash on complete data.
InstancePtr Pointer to the XSecure_Sha3 instance HashAddr Address of XSecure_Sha3Hash structure, where output hash is stored into Hash which is a member of XSecure_Sha3Hash structure HashBufSize Size of the hash in bytes XST_SUCCESS - If finished without any errorsXSECURE_SHA3_INVALID_PARAM - On invalid parameterXSECURE_SHA3_STATE_MISMATCH_ERROR - If State mismatch is occurredXST_FAILURE - If Sha3PadType is other than KECCAK or NIST
References XSecure_Sha3Finish, XSecure_Sha3Hash.
Referenced by XSecure_HmacFinal, XSecure_LmsHashMessage, XSecure_Sha3Kat, XSecure_ShaDigest, XSecure_ShakeKat, XSecure_SlhdsaShake256sChain, XSecure_SlhdsaShake256sHashF, XSecure_SlhdsaShake256sHashH, XSecure_SlhdsaShake256sHashTl.
int XSecure_ShaDigest(XSecure_Sha *InstancePtr, XSecure_ShaMode ShaMode, const u64 DataAddr, const u32 DataSize, u64 HashAddr, const u32 HashBufSize)
This wrapper function calls SHA3 digest on the given input data.
InstancePtr Pointer to the void ShaMode SHA mode DataAddr Starting address of the data on which sha3 hash should be calculated DataSize Size of the input data HashAddr Address of XSecure_Sha3Hash structure, where output hash is stored into Hash which is a member of XSecure_Sha3Hash structure HashBufSize Size of the hash in bytes XST_SUCCESS - If digest calculation done successfullyXST_FAILURE - If any error from Sha3Update or Sha3Finish
References XSecure_Sha3Digest, XSecure_Sha3Hash.
Referenced by XSecure_LmsSignatureVerification, XSecure_Sha2256Kat.
int XSecure_ShaLookupConfig(XSecure_Sha *InstancePtr, u32 DeviceId)
This function assigns SHA configuration to the InstancePtr.
InstancePtr Pointer to the void instance DeviceId DeviceId of Sha engine XST_SUCCESS - Upon SuccessXST_FAILURE - Upon Failure
References XSecure_Sha3LookupConfig.
Referenced by XSecure_AesShaInit.
static int XSecure_Sha3Init(void)
This function initializes SHA3 instance.
XST_SUCCESS - If the initialization is successfulXST_FAILURE - If there is a failure
static int XSecure_Sha3UpdateIpi(u32 SubsystemId, u32 SrcAddrLow, u32 SrcAddrHigh, u32 Size, u32 DstAddrLow, u32 DstAddrHigh)
This function handler calls XSecure_Sha3Update64Bit or XSecure_Sha3Finish based on the Continue bit in the command.
SubsystemId Subsystem ID. SrcAddrLow Lower 32 bit address of the input data on which hash has to be calculated SrcAddrHigh Higher 32 bit address of the input data on which hash has to be calculated Size Size of the input data in bytes to be updated DstAddrLow Lower 32 bit address of the output data where hash to be stored DstAddrHigh Higher 32 bit address of the output data where hash to be stored XST_SUCCESS - If the sha update/fnish is successfulXST_FAILURE - If there is a failure
static int XSecure_ShaOperation(const XPlmi_Cmd *Cmd)
This function is used for single sha3digest or for multiple sha3 updates based on the First packet bit and Continue bit in the command.
Cmd is a pointer to the command structure XST_SUCCESS - If the sha Update/Finish/Digest is successfulXST_FAILURE - If there is a failure
int XSecure_Sha3IpiHandler(XPlmi_Cmd *Cmd)
This function calls respective IPI handler based on the API_ID.
Cmd is a pointer to the command structure XST_SUCCESS - If the handler execution is successfulXST_INVALID_PARAM - If cmd is NULL or if invalid API ID is received.XST_DEVICE_BUSY - If IPI channel is busyXST_FAILURE - If there is a failure
References XSECURE_API, XSECURE_API_ID_MASK, XSECURE_API_SHA3_UPDATE, XSecure_GetSha3Instance, XSecure_IpiEventHandling, XSecure_MakeResFree, XSECURE_SHA_0_DEVICE_ID, XSECURE_SHA_INITIALIZED.
static s32 XSecure_Sha1Transform(XSecure_Sha1Ctx *const Ctx, const u8 *const Buffer)
Hash a single 512-bit block.
This is the core of the algorithm. Ctx Pointer to SHA1 context Buffer Pointer to 512-bit block data XST_FAILURE In case of failure in SHA1 transform function XST_SUCCESS In case of success in SHA1 transform function XST_GLITCH_ERROR In case of glitch detected in SHA1 calculation
static void XSecure_Sha1Init(XSecure_Sha1Ctx *Ctx)
Initializies the SHA1 context.
Ctx Pointer to SHA1 context
static s32 XSecure_ReadHash(const XSecure_Sha1Ctx *Ctx, u8 *const Hash)
Read calculated hash from the context and store in user provided memory.
Ctx Pointer to SHA1 context Hash Pointer to memory location where calculated hash to be stored XST_SUCCESS In case of successful read XST_FAILURE - Upon failure
static void XSecure_Sha1AddDataLenToPadding(u8 *const Buffer, u32 Len)
This function adds padding to data length.
Buffer Pointer to memory location where Length is to be padded Len SHA1 padding length field in bytes
s32 XSecure_Sha1Digest(const u8 *const Data, u32 Len, u8 *const Hash)
This function calculates SHA1 hash on given input data.
Data Pointer to input data Len Length of input data Hash Pointer to memory location where calculated hash to be stored XST_FAILURE In case of failure in SHA1 digest calculation XST_SUCCESS In case of successful calculation of SHA1 digest XSECURE_SHA1_TRANSFORM_ERROR In case of failure in SHA1 transform operationXST_GLITCH_ERROR In case of glitch detected in SHA1 calculation
References XSECURE_SHA1_HASH_BLK_SIZE, XSECURE_SHA1_LEN_FIELD_SIZE, XSECURE_SHA1_MIN_PADDING_LEN, XSECURE_SHA1_PADDING_MIDDLE, XSECURE_SHA1_PADDING_START, XSECURE_SHA1_TRANSFORM_ERROR.
XSECURE_SHA3_START_NIST_PADDING_MASK
Nist Start padding masks.
XSECURE_SHA3_END_NIST_PADDING_MASK
Nist End padding masks.
XSECURE_TYPE_PMC_DMA0
DMA0 type.
XSecure_Sha3Hash
Define XSecure_Sha3Hash with XSecure_Sha384Hash to maintain backward compatibility.
XSECURE_IPI_CONTINUE_MASK
IPI Continue Mask.
BYTE_SIZE_IN_BITS
Size of byte in bits.
WORD_SIZE_IN_BITS
Size of word in bits.
XSECURE_SHA1_HASH_BLK_SIZE
512-bits = 64 bytes
Referenced by XSecure_Sha1Digest.
XSECURE_SHA1_LEN_FIELD_SIZE
Size of Length field.
Referenced by XSecure_Sha1Digest.
XSECURE_SHA1_MIN_PADDING_LEN
Minimum padding length.
Referenced by XSecure_Sha1Digest.
XSECURE_SHA1_PADDING_START
Padding start byte.
Referenced by XSecure_Sha1Digest.
XSECURE_SHA1_PADDING_MIDDLE
Padding middle byte.
Referenced by XSecure_Sha1Digest.
XSECURE_SHA_TOTAL_NUM_OF_STATES
Total number of states.
K0
Constant K0.
Referenced by XSecure_HmacInit.
K1
Constant K1.
K2
Constant K2.
K3
Constant K3.
H0
Initial hash value H0.
H1
Initial hash value H1.
H2
Initial hash value H2.
H3
Initial hash value H3.
H4
Initial hash value H4.
RotateLeft32
Macro to Rotate left the 32-bit value.
BLK0
Macro for Block 0 expansion.
BLK
Macro for Block expansion.
CONVERT_BYTE_TO_BITS
Multiply 32-bit Len by 8 and store 64-bit result in LenHigh, LenLow.
GET_BYTE_FROM_U32
Extracts specified byte from 32-bit word.
Make sure ByteNo is between 0 to 3.
XSECURE_SHA1_HASH_SIZE
Size of SHA1 hash in bytes.
XSECURE_SHA_MODULE_MAJOR_VERSION
SHA module major version.
XSECURE_SHA_MODULE_MINOR_VERSION
SHA module minor version.
XSECURE_SHA_MODULE_MAJOR_VERSION
SHA module major version.
XSECURE_SHA_MODULE_MINOR_VERSION
SHA module minor version.
XSECURE_SHA_MODULE_MAJOR_VERSION
SHA module major version.
XSECURE_SHA_MODULE_MINOR_VERSION
SHA module minor version.