xsecure_sha_client_apis
XSecure_ShaState
SHA uninitialized state.
XSecure_ShaState Sha3State
void XSecure_Sha3GetCryptoAlgInfo(Xil_CryptoAlgInfo *AlgInfo)
This function returns the SHA crypto algorithm information.
AlgInfo Pointer to memory for holding the crypto algorithm information None
References XSECURE_API_SHA3_OPERATION, XSECURE_API_SHA3_UPDATE, XSecure_GetAlgInfo.
int XSecure_Sha3Initialize(void)
This function stores the Sha3 initialize state as initialized if the current state is uninitialized.
XST_SUCCESS If the Sha3 state is changed to initialized stateXST_FAILURE If the Sha3 is not in uninitialized state
References XSECURE_SHA_INITIALIZED.
Referenced by XSecure_PpkVerify, XSecure_Sha3Digest, XSecure_Sha3Hash, XSecure_ShaInitialize, XSecure_SpkAuthentication.
int XSecure_Sha3Update(XSecure_ClientInstance *InstancePtr, const u64 InDataAddr, u32 Size)
This function sends IPI request to update the SHA3 engine with the input data.
InstancePtr Pointer to the client instance InDataAddr Address of the output buffer to store the output hash Size Size of the data to be updated to SHA3 engine XST_SUCCESS If the update is successfulXST_FAILURE If there is a failure
References XSECURE_ADDR_HIGH_SHIFT, XSECURE_API_SHA3_UPDATE, XSECURE_DEBUG_GENERAL, XSecure_Printf, XSecure_SendRequest, XSECURE_SHA_FIRST_PACKET_SHIFT, XSECURE_SHA_INITIALIZED, XSECURE_SHA_UPDATE, XSECURE_SHA_UPDATE_CONTINUE_SHIFT, XSECURE_SLR_INDEX_SHIFT.
Referenced by XSecure_Sha3Digest, XSecure_Sha3Hash, XSecure_SpkAuthentication.
int XSecure_Sha3Finish(XSecure_ClientInstance *InstancePtr, const u64 OutDataAddr)
This function sends IPI request final data to SHA3 engine which includes SHA3 padding and reads final hash.
InstancePtr Pointer to the client instance OutDataAddr Address of the output buffer to store the output hash XST_SUCCESS If finished without any errorsXST_FAILURE If there is a failure
References XSECURE_ADDR_HIGH_SHIFT, XSECURE_API_SHA3_UPDATE, XSECURE_DEBUG_GENERAL, XSecure_Printf, XSecure_SendRequest, XSECURE_SHA_INITIALIZED, XSECURE_SHA_UNINITIALIZED, XSECURE_SHA_UPDATE, XSECURE_SLR_INDEX_SHIFT.
Referenced by XSecure_Sha3Digest, XSecure_Sha3Hash, XSecure_ShaFinish, XSecure_SpkAuthentication.
int XSecure_Sha3Digest(XSecure_ClientInstance *InstancePtr, const u64 InDataAddr, const u64 OutDataAddr, u32 Size)
This function sends IPI request to calculate hash on single block of data.
InstancePtr Pointer to the client instance InDataAddr Address of the input buffer where the input data is stored OutDataAddr Address of the output buffer to store the output hash Size Size of the data to be updated to SHA3 engine XST_SUCCESS If the sha3 hash calculation is successfulXST_FAILURE If there is a failure
References XSECURE_ADDR_HIGH_SHIFT, XSECURE_API_SHA3_UPDATE, XSECURE_DEBUG_GENERAL, XSecure_Printf, XSecure_SendRequest, XSecure_Sha3Initialize, XSECURE_SHA_FIRST_PACKET_SHIFT, XSECURE_SHA_UNINITIALIZED, XSECURE_SLR_INDEX_SHIFT.
Referenced by XSecure_PpkVerify, XSecure_ShaDigest.
XSECURE_SHA_FIRST_PACKET_SHIFT
SHA - First packet shift.
Referenced by XSecure_Sha3Digest, XSecure_Sha3Update.
XSECURE_SHA_UPDATE_CONTINUE_SHIFT
SHA - Update continue shift.
Referenced by XSecure_Sha3Update.