xsecure_sha3_zynqmp_apis
u32 XSecure_Sha3WaitForDone(XSecure_Sha3 *InstancePtr)
This inline function waits till SHA3 completes its operation.
SHA3 Wait To Complete Function. InstancePtr Pointer to the XSecure_Sha3 instance. XST_SUCCESS if the SHA3 completes its operation. XST_FAILURE if a timeout has occurred.
Referenced by XSecure_Sha3Finish.
static u32 XSecure_Sha3DmaTransfer(XSecure_Sha3 *InstancePtr, const u8 *Data, const u32 Size, u8 IsLast)
This function Transfers Data through Dma.
InstancePtr Pointer to the XSecure_Sha3 instance. Data Pointer to the input data need to be transferred. Size Size of the input data in bytes. IsLast To indicate last transfer. None
static u32 XSecure_Sha3DataUpdate(XSecure_Sha3 *InstancePtr, const u8 *Data, const u32 Size, u8 IsLastUpdate)
This function updates hash for data block of size <= 512MB.
InstancePtr Pointer to the XSecure_Sha3 instance. Data Pointer to the input data for hashing. Size Size of the input data in bytes. IsLastUpdate Indicates if this is the last update. None
static void XSecure_Sha3KeccakPadd(XSecure_Sha3 *InstancePtr, u8 *Dst, u32 MsgLen)
This function generates padding for the SHA-3 engine.
InstancePtr Pointer to the XSecure_Sha3 instance. Dst Pointer to location where padding is to be applied. MsgLen Length of padding in bytes. None
static void XSecure_Sha3NistPadd(XSecure_Sha3 *InstancePtr, u8 *Dst, u32 MsgLen)
Generate padding for the NIST SHA-3.
InstancePtr is a pointer to the XSecure_Sha3 instance. Dst is the pointer to location where padding is to be applied MsgLen is the length of padding in bytes None None
s32 XSecure_Sha3Initialize(XSecure_Sha3 *InstancePtr, XCsuDma *CsuDmaPtr)
This function initializes a XSecure_Sha3 structure with the default values required for operating the SHA3 cryptographic engine.
SHA3 Initialization Function. InstancePtr Pointer to the XSecure_Sha3 instance. CsuDmaPtr Pointer to the XCsuDma instance. XST_SUCCESS if initialization was successful The base address is initialized directly with value from xsecure_hw.h The default is NIST SHA3 padding, to change to KECCAK padding call XSecure_Sha3PadSelection() after XSecure_Sha3Initialize().
s32 XSecure_Sha3PadSelection(XSecure_Sha3 *InstancePtr, XSecure_Sha3PadType Sha3PadType)
This function provides an option to select the SHA-3 padding type to be used while calculating the hash.
SHA3 Padding Selection Function. InstancePtr Pointer to the XSecure_Sha3 instance. Sha3PadType Type of SHA3 padding to be used (XSECURE_CSU_NIST_SHA3 for NIST SHA-3 padding or XSECURE_CSU_KECCAK_SHA3 for KECCAK SHA-3 padding) XST_SUCCESS if pad selection is successful. XST_FAILURE if pad selection is failed. The default provides support for NIST SHA-3. If a user wants to change the padding to Keccak SHA-3, this function should be called after XSecure_Sha3Initialize()
Referenced by XSecure_PpkVerify, XSecure_SpkAuthentication.
s32 XSecure_Sha3LastUpdate(XSecure_Sha3 *InstancePtr)
This function is to notify this is the last update of data where sha padding is also been included along with the data in the next update call.
SHA3 Last Update Call Function. InstancePtr Pointer to the XSecure_Sha3 instance. XST_SUCCESS if last update can be accepted
void XSecure_Sha3Start(XSecure_Sha3 *InstancePtr)
This function configures Secure Stream Switch and starts the SHA-3 engine.
SHA3 Start Function. InstancePtr Pointer to the XSecure_Sha3 instance.
u32 XSecure_Sha3Update(XSecure_Sha3 *InstancePtr, const u8 *Data, const u32 Size)
This function updates the SHA3 engine with the input data.
SHA3 Data Transfer Function. InstancePtr Pointer to the XSecure_Sha3 instance. Data Pointer to the input data for hashing. Size Size of the input data in bytes. XST_SUCCESS if the update is successful XST_FAILURE if there is a failure in SSS config
References XSECURE_CSU_SHA3_RESET_OFFSET, XSecure_SetReset.
u32 XSecure_Sha3Finish(XSecure_Sha3 *InstancePtr, u8 *Hash)
This function updates SHA3 engine with final data which includes SHA3 padding and reads final hash on complete data.
SHA3 Finish Function. InstancePtr Pointer to the XSecure_Sha3 instance. Hash Pointer to location where resulting hash will be written XST_SUCCESS if finished without any errors XST_FAILURE if Sha3PadType is other than KECCAK or NIST
u32 XSecure_Sha3Digest(XSecure_Sha3 *InstancePtr, const u8 *In, const u32 Size, u8 *Out)
This function calculates the SHA-3 digest on the given input data.
SHA3 Complete Digest Calculation Function. InstancePtr Pointer to the XSecure_Sha3 instance. In Pointer to the input data for hashing Size Size of the input data Out Pointer to location where resulting hash will be written. XST_SUCCESS if digest calculation done successfully XST_FAILURE if any error from Sha3Update or Sha3Finish.
References XSecure_Sha3Finish, XSecure_Sha3Start, XSecure_Sha3Update.
void XSecure_Sha3_ReadHash(XSecure_Sha3 *InstancePtr, u8 *Hash)
This function reads the SHA3 hash of the data and it can be called between calls to XSecure_Sha3Update.
SHA3 Read Hash Function. InstancePtr Pointer to the XSecure_Sha3 instance. Hash Pointer to a buffer in which read hash will be stored.
XSECURE_CSU_SHA3_HASH_LENGTH_IN_BITS
CSU SHA3 hash length in bits.
XSECURE_CSU_SHA3_HASH_LENGTH_IN_WORDS
CSU SHA3 hash length in words.
XSECURE_CSU_SHA3_START_KECCAK_PADDING_MASK
Keccak and NIST padding masks.
CSU SHA3 start Keccak padding mask
XSECURE_CSU_SHA3_END_KECCAK_PADDING_MASK
CSU SHA3 end Keccak padding mask.
XSECURE_CSU_SHA3_START_NIST_PADDING_MASK
CSU SHA3 start NIST padding mask.
XSECURE_CSU_SHA3_END_NIST_PADDING_MASK
CSU SHA3 end NIST padding mask.