xsecure_lms_server_apis
XSecure_LmsType
Reserved.
XSecure_LmsTreeHeight
Unsupported tree height.
XSecure_LmsOtsType
Reserved.
XSecure_LmsOtsWIndex
Not Supported.
XSecure_LmsOtsuIndex
Not Supported.
XSecure_LmsOtsvIndex
Not Supported.
XSecure_LmsOtslsIndex
'ls' corresponding to 'w' = 2
XSecure_LmsOtspIndex
Not Supported.
typedef union XSecure_LmsPublicKey_ XSecure_LmsPublicKey
LMS Public key structure to access root value.
Size = 4 + 4 + 16 + H Len (32) = 56 Bytes
typedef union XSecure_LmsPubKeyTmp_ XSecure_LmsPubKeyTmp
Used to store data which is repeatedly sent to SHA engine, during LMS root value calculation.
Size = 16(I) + 4(node_number/2) + 2(D_INTR) + (32 * 2)
typedef union XSecure_LmsOtsPublicKey_ XSecure_LmsOtsPublicKey
LMS OTS Public key structure.
Size = 4 + 16 + 4 + H Len (32) = 56 Bytes
typedef union XSecure_LmsOtsHashPerDigit_ XSecure_LmsOtsHashPerDigit
Temporary buffer, used in LMS OTS signature verification, used in hash chain to arrive at values which will be concatenated and hashed to get public value.
Size = 1 + 16 + 4 + 2 + 1 + H Len (32) = 56 Bytes
typedef union XSecure_LmsOtsSignToPubKeyHash_ XSecure_LmsOtsSignToPubKeyHash
Structure used when validating LMS OTS, once hash chain is completed, result needs to be stored so that they can be further concatenated and hashed to get OTS public key, this provides a way to access members and fill data in a structured way.
Size = 16(I) + 4(q) + 2(D_PBLC) + (p * H Len (32))
typedef struct XSecure_LmsOtsSignature_ XSecure_LmsOtsSignature
Partial LMS OTS Signature structure.
struct Size = 4 + 32 Sign size = 4 + 32 + (p * n) = 4 + n * (p+1)
typedef union XSecure_LmsDataDigestFixedFields_ XSecure_LmsDataDigestFixedFields
Temporary buffer, used to send prefix fields to calculate digest for data to be authenticate.
Size = I (16) + q (4) + D_MESG (2) + C (32) = 54 Bytes
typedef union XSecure_LmsDataDigest_ XSecure_LmsDataDigest
Digest for message to be authenticated, along with checksum.
Size = Digest (32) + Check sum (2) = 34 Bytes
volatile XSecure_LmsPublicKey AuthenticatedKey
XSecure_LmsDataDigestFixedFields DigestPrefixFields
volatile u32 SignatureLengthConsumed
XSecure_LmsDataDigest DigestChecksum
u32 CurrentLmsQ
int XSecure_LmsLookupParamSet(XSecure_LmsType Type, XSecure_LmsParam **Parameters)
This function returns the parameters for the type of LMS type.
Type XSecure_LmsType, type of OTS algorithm selected Parameters Pointer to array location where all predefined parameter values are present XSecure_LmsParam XST_SUCCESS - Valid type is passed, and parameters are assignedXST_FAILURE - If not a valid type is passed
References XSecure_LmsParam::H, XSECURE_ALLFS, XSECURE_LMS_NOT_SUPPORTED, XSECURE_LMS_RESERVED, XSECURE_LMS_SHA256_M32_H10, XSECURE_LMS_SHA256_M32_H15, XSECURE_LMS_SHA256_M32_H20, XSECURE_LMS_SHA256_M32_H5, XSECURE_LMS_SHAKE_M32_H10, XSECURE_LMS_SHAKE_M32_H15, XSECURE_LMS_SHAKE_M32_H20, XSECURE_LMS_SHAKE_M32_H5, XSECURE_LMS_TREE_HEIGHT_H10, XSECURE_LMS_TREE_HEIGHT_H15, XSECURE_LMS_TREE_HEIGHT_H20, XSECURE_LMS_TREE_HEIGHT_H5, XSECURE_LMS_TREE_HEIGHT_UNSUPPORTED, XSECURE_LMS_TYPE_LOOKUP_GLITCH_ERROR, XSECURE_LMS_TYPE_MAX_SUPPORTED, XSECURE_LMS_TYPE_UNSUPPORTED_ERROR, XSECURE_SHA2_256_HASH_LEN, XSECURE_SHAKE_256, XSECURE_SHAKE_256_HASH_LEN.
Referenced by XSecure_GetLmsHashAlgo, XSecure_HssFinish, XSecure_HssInit, XSecure_HssSignatureVerification, XSecure_LmsSignatureVerification.
static int XSecure_LmsOtsSignatureCompute(XSecure_Sha *ShaInstPtr, XPmcDma *DmaPtr, u8 *Data, u32 DataLen, u32 PreHashedMsg, u8 *LmsOtsSignatureBuff, u32 LmsOtsSignatureLen, XSecure_LmsOtsType LmsOtsExpectedType, u8 *Kc)
This function takes in LMS OTS Signature and produces LMS OTS Public key, which in turn is used to calculate the root public key of Merkle tree.
ShaInstPtr Pointer to the SHA instance. DmaPtr Pointer to the DMA instance. Data Pointer to the data to be authenticated DataLen Length of data to be authenticated PreHashedMsg If TRUE, then Data contains digest, if FALSE contains raw msg to be authenticated LmsOtsSignatureBuff Pointer to OTS signature buffer LmsOtsSignatureLen Length of OTS signature buffer LmsOtsExpectedType Expected OTS signature type, value read from public key of this level XSecure_LmsOtsType Kc Buffer where the computed value of root needs to be copied, assumed that has enough place XST_SUCCESS - If operation succeedsXSECURE_LMS_INVALID_PARAM - If input parameters are invalidXSECURE_LMS_OTS_PUB_KEY_SIGN_TYPE_MISMATCH_ERROR - If signature type mismatchXSECURE_LMS_OTS_SIGN_UNSUPPORTED_TYPE_ERROR - If unsupported signature typeXSECURE_LMS_OTS_DIGEST_CHECKSUM_OP_FAILED_ERROR - If digest checksum operation failsXSECURE_AUTH_LMS_DIGEST_CHECKSUM_FAILED_ERROR - If checksum computation failsXSECURE_ERR_GLITCH_DETECTED - If outer digit loop glitch is detectedXST_FAILURE - On failure
static u32 XSecure_SwapBytes(const u8 *const source, size_t bytes)
This function get bytes from buffer, to a unsigned int value, Changes endianness.
source - pointer to source buffer bytes - number of bytes to be extracted Resultant value
int XSecure_LmsSignatureVerification(XSecure_Sha *ShaInstPtr, XPmcDma *DmaPtr, XSecure_LmsSignVerifyParams *LmsSignVerifyParams)
This function performs LMS level signature verification.
ShaInstPtr Pointer to SHA instance DmaPtr Pointer to DMA instance LmsSignVerifyParams Pointer to LMS signature verification parameters XST_SUCCESS - On successXSECURE_LMS_INVALID_PARAM - Invalid parameter providedXSECURE_LMS_PUB_KEY_UNSUPPORTED_TYPE_1_ERROR - Public key LMS type is unsupportedXSECURE_LMS_SIGN_EXPECTED_PUB_KEY_LEN_2_ERROR - Expected public key length mismatchXSECURE_LMS_SIGN_LEN_1_ERROR - Signature length is insufficientXSECURE_LMS_OTS_PUB_KEY_LMS_OTS_SIGN_TYPE_MISMATCH_ERROR - OTS signature type mismatch with public keyXSECURE_LMS_SIGN_UNSUPPORTED_OTS_TYPE_1_ERROR - OTS signature type is unsupportedXSECURE_LMS_SIGN_LEN_2_ERROR - Signature length error for OTS componentXSECURE_LMS_PUB_KEY_LMS_SIGN_TYPE_MISMATCH_ERROR - LMS signature type mismatch with public keyXSECURE_LMS_SIGN_UNSUPPORTED_TYPE_1_ERROR - LMS signature type is unsupportedXSECURE_LMS_SIGN_INVALID_NODE_NUMBER_ERROR - Invalid node number in signatureXSECURE_LMS_SIGN_LEN_3_ERROR - Total signature length mismatchXSECURE_LMS_SIGN_OTS_OP_ERROR - OTS signature computation operation failedXSECURE_LMS_SIGN_VERIF_SHA_DIGEST_LEAF_FAILED_ERROR - SHA digest failed for leaf nodeXSECURE_LMS_PUB_KEY_AUTHENTICATION_FAILED_ERROR - Public key authentication failedXSECURE_LMS_PUB_KEY_AUTHENTICATION_GLITCH_ERROR - Public key authentication glitch detectedXST_FAILURE - On any other failure
References XSecure_LmsPubKeyTmp_::D, XSecure_LmsSignVerifyParams::Data, XSecure_LmsSignVerifyParams::DataLen, XSecure_LmsSignVerifyParams::ExpectedPubKey, XSecure_LmsPubKeyTmp_::Fields, XSecure_LmsDataDigestFixedFields_::Fields, XSecure_LmsParam::h, XSecure_LmsOtsParam::H, XSecure_LmsPubKeyTmp_::half_node_number, XSecure_LmsPubKeyTmp_::I, XSecure_LmsDataDigestFixedFields_::I, XSecure_LmsSignVerifyParams::LmsSign, XSecure_LmsSignVerifyParams::LmsSignLen, XSecure_LmsParam::m, XSecure_LmsParam::mh, XSecure_LmsSignVerifyParams::PreHashedMsg, XSecure_LmsSignVerifyParams::PubKeyLen, XSecure_LmsDataDigestFixedFields_::q, XSecure_LmsOtsParam::SignLen, XSecure_LmsPubKeyTmp_::Tmp, XSECURE_DEBUG_GENERAL, XSECURE_IS_ODD, XSECURE_LMS_I_FIELD_SIZE, XSECURE_LMS_INVALID_PARAM, XSECURE_LMS_M_BYTE_FIELD_SIZE, XSECURE_LMS_MEM_COPY_ERROR, XSECURE_LMS_NOT_SUPPORTED, XSECURE_LMS_OTS_NOT_SUPPORTED, XSECURE_LMS_OTS_PUB_KEY_K_FIELD_SIZE, XSECURE_LMS_OTS_PUB_KEY_LMS_OTS_SIGN_TYPE_MISMATCH_ERROR, XSECURE_LMS_OTS_SIGN_TYPE_FIELD_OFFSET, XSECURE_LMS_OTS_TYPE_SIZE, XSECURE_LMS_PUB_KEY_AUTHENTICATION_FAILED_ERROR, XSECURE_LMS_PUB_KEY_AUTHENTICATION_GLITCH_ERROR, XSECURE_LMS_PUB_KEY_FIXED_FIELD_SIZE, XSECURE_LMS_PUB_KEY_I_OFFSET, XSECURE_LMS_PUB_KEY_LMS_SIGN_TYPE_MISMATCH_ERROR, XSECURE_LMS_PUB_KEY_OTS_TYPE_OFFSET, XSECURE_LMS_PUB_KEY_T_FIELD_SIZE, XSECURE_LMS_PUB_KEY_T_OFFSET, XSECURE_LMS_PUB_KEY_TMP_BUF_ADJ_NODE_VAL_INDEX, XSECURE_LMS_PUB_KEY_TMP_BUFFER_INTR_TOTAL_SIZE, XSECURE_LMS_PUB_KEY_TMP_BUFFER_LEAF_TOTAL_SIZE, XSECURE_LMS_PUB_KEY_TYPE_OFFSET, XSECURE_LMS_PUB_KEY_UNSUPPORTED_TYPE_1_ERROR, XSECURE_LMS_Q_FIELD_SIZE, XSECURE_LMS_SIGN_EXPECTED_PUB_KEY_LEN_2_ERROR, XSECURE_LMS_SIGN_INVALID_NODE_NUMBER_ERROR, XSECURE_LMS_SIGN_LEN_1_ERROR, XSECURE_LMS_SIGN_LEN_2_ERROR, XSECURE_LMS_SIGN_LEN_3_ERROR, XSECURE_LMS_SIGN_UNSUPPORTED_OTS_TYPE_1_ERROR, XSECURE_LMS_SIGN_UNSUPPORTED_TYPE_1_ERROR, XSECURE_LMS_SIGN_VERIF_SHA_DIGEST_INTR_EVEN_FAILED_ERROR, XSECURE_LMS_SIGN_VERIF_SHA_DIGEST_INTR_ODD_FAILED_ERROR, XSECURE_LMS_SIGNATURE_OTS_FIELD_OFFSET, XSECURE_LMS_SIGNATURE_Q_FIELD_OFFSET, XSECURE_LMS_TYPE_SIZE, XSecure_LmsLookupParamSet, XSecure_LmsOtsLookupParamSet, XSecure_Printf, XSecure_ShaDigest.
Referenced by XSecure_HssFinish, XSecure_HssInit, XSecure_LmsSha2256Kat, XSecure_LmsShake256Kat.
int XSecure_HssInit(XSecure_Sha *ShaInstPtr, XPmcDma *DmaPtr, XSecure_HssInitParams *HssInitParams)
This function Initiates LMS Signature verification process.
Completes all upper level Merkle trees verification and prepares for data's Digest calculation ShaInstPtr Pointer to SHA instance DmaPtr Pointer to DMA instance HssInitParams Pointer to HSS initialization parameters XST_SUCCESS - On successXSECURE_LMS_INVALID_PARAM - Invalid parameter providedXSECURE_LMS_HSS_PUB_KEY_INVALID_LEN_2_ERROR - HSS public key length is invalidXSECURE_LMS_HSS_SIGN_LEVEL_UNSUPPORTED_ERROR - HSS signature level is not supportedXSECURE_LMS_HSS_SIGN_PUB_KEY_LEVEL_MISMATCH_ERROR - HSS signature and public key level mismatchXSECURE_LMS_HSS_L0_PUB_KEY_LMS_TYPE_UNSUPPORTED_ERROR - Level 0 public key LMS type is unsupportedXSECURE_LMS_HSS_L0_PUB_KEY_LMS_OTS_TYPE_UNSUPPORTED_ERROR - Level 0 public key LMS OTS type is unsupportedXSECURE_LMS_SIGN_VERIFY_BH_AND_TYPE_SHA_ALGO_MISMATCH_L0_ERROR - SHA algorithm mismatch at level 0XSECURE_LMS_HSS_L0_SIGN_INVALID_LEN_2_ERROR - Level 0 signature length is invalidXSECURE_LMS_HSS_L0_PUB_KEY_AUTH_FAILED_ERROR - Level 0 public key authentication failedXSECURE_LMS_PUB_OP_FAILED_ERROR - Public key operation failedXSECURE_LMS_PUB_OP_FAILED_1_ERROR - Public key operation failedXSECURE_LMS_HSS_L1_PUB_KEY_LMS_TYPE_1_UNSUPPORTED_ERROR - Level 1 public key LMS type is unsupportedXST_FAILURE - On any other failure
References XSecure_LmsDataDigestFixedFields_::C, XSecure_LmsSignVerifyParams::Data, XSecure_LmsSignVerifyParams::DataLen, XSecure_LmsSignVerifyParams::ExpectedPubKey, XSecure_LmsPublicKey_::Fields, XSecure_LmsDataDigestFixedFields_::Fields, XSecure_LmsParam::H, XSecure_LmsOtsParam::H, XSecure_ShaPlatConfig::HashAlgo, XSecure_LmsPublicKey_::I, XSecure_LmsDataDigestFixedFields_::I, XSecure_LmsSignVerifyParams::LmsSign, XSecure_LmsSignVerifyParams::LmsSignLen, XSecure_LmsParam::mh, XSecure_LmsSignVerifyParams::PreHashedMsg, XSecure_LmsSignVerifyParams::PubKeyLen, XSecure_HssInitParams::PublicKey, XSecure_HssInitParams::PublicKeyLen, XSecure_LmsDataDigestFixedFields_::q, XSecure_HssInitParams::SignatureLen, XSecure_HssInitParams::SignBuff, XSecure_LmsOtsParam::SignLen, XSECURE_ALLFS, XSECURE_DEBUG_GENERAL, XSECURE_ERR_GLITCH_DETECTED, XSECURE_HSS_PUBLIC_KEY_LEVEL_FIELD_OFFSET, XSECURE_HSS_PUBLIC_KEY_LMS_FIELD_OFFSET, XSECURE_HSS_PUBLIC_KEY_TOTAL_SIZE, XSECURE_HSS_SIGN_LIST_LEVEL_FIELD_OFFSET, XSECURE_LMS_C_FIELD_SIZE, XSECURE_LMS_HSS_L0_PUB_KEY_LMS_OTS_TYPE_UNSUPPORTED_ERROR, XSECURE_LMS_HSS_L0_PUB_KEY_LMS_TYPE_UNSUPPORTED_ERROR, XSECURE_LMS_HSS_L0_SIGN_INVALID_LEN_2_ERROR, XSECURE_LMS_HSS_L1_PUB_KEY_LMS_TYPE_1_UNSUPPORTED_ERROR, XSECURE_LMS_HSS_LEVELS_FIELD_SIZE, XSECURE_LMS_HSS_MAX_LEVELS_SUPPORTED, XSECURE_LMS_HSS_MIN_LEVELS_SUPPORTED, XSECURE_LMS_HSS_PUB_KEY_INVALID_LEN_2_ERROR, XSECURE_LMS_HSS_SIGN_LEVEL_UNSUPPORTED_ERROR, XSECURE_LMS_HSS_SIGN_PUB_KEY_LEVEL_MISMATCH_ERROR, XSECURE_LMS_I_FIELD_SIZE, XSECURE_LMS_INVALID_PARAM, XSECURE_LMS_MEM_COPY_ERROR, XSECURE_LMS_NOT_SUPPORTED, XSECURE_LMS_OTS_NOT_SUPPORTED, XSECURE_LMS_OTS_SIGN_C_FIELD_OFFSET, XSECURE_LMS_OTS_TYPE_SIZE, XSECURE_LMS_PUB_KEY_OTS_TYPE_OFFSET, XSECURE_LMS_PUB_KEY_TOTAL_SIZE, XSECURE_LMS_PUB_KEY_TYPE_OFFSET, XSECURE_LMS_PUB_OP_FAILED_1_ERROR, XSECURE_LMS_PUB_OP_FAILED_ERROR, XSECURE_LMS_Q_FIELD_SIZE, XSECURE_LMS_SIGN_VERIFY_BH_AND_TYPE_SHA_ALGO_MISMATCH_L0_ERROR, XSECURE_LMS_SIGNATURE_OTS_FIELD_OFFSET, XSECURE_LMS_SIGNATURE_Q_FIELD_OFFSET, XSECURE_LMS_TYPE_SIZE, XSecure_LmsLookupParamSet, XSecure_LmsOtsLookupParamSet, XSecure_LmsSignatureVerification, XSecure_Printf, XSecure_ShaInitialize.
Referenced by XSecure_HssSha2256Kat, XSecure_HssShake256Kat, XSecure_HssSignatureVerification.
int XSecure_LmsHashMessage(XSecure_Sha *ShaInstPtr, u8 *Data, u32 DataLen, XSecure_ShaMode Mode)
This function calculates the Digest of data to authenticate to initiate the process of LMS verification.
ShaInstPtr Pointer to the SHA instance. Data Pointer to the data to be authenticated DataLen Length of data to be authenticated Mode Mode of the SHA operation XST_SUCCESS - On successXSECURE_LMS_HSS_L1_PUB_KEY_LMS_TYPE_1_UNSUPPORTED_ERROR - Level 1 public key LMS type is unsupportedXSECURE_LMS_HSS_L0_PUB_KEY_LMS_OTS_TYPE_UNSUPPORTED_ERROR - Level 0 public key LMS OTS type is unsupportedXST_FAILURE - On SHA operation failure
References XSecure_LmsDataDigestFixedFields_::D_MESG, XSecure_LmsDataDigestFixedFields_::Fields, XSECURE_LMS_DIGEST_SIZE, XSECURE_LMS_MESSAGE_TO_DIGEST_PREFIX_SIZE, XSecure_ShaFinish, XSecure_ShaLastUpdate, XSecure_ShaStart, XSecure_ShaUpdate.
Referenced by XSecure_HssSha2256Kat, XSecure_HssShake256Kat, XSecure_HssSignatureVerification.
int XSecure_HssFinish(XSecure_Sha *ShaInstPtr, XPmcDma *DmaPtr, u8 *SignBuff, u32 SignatureLen)
This function Completes LMS Signature verification process.
Data should have been pre-processed before calling this function, by calling @ref XSecure_HssInit & @ref XSecure_LmsHashMessage in sequence ShaInstPtr Pointer to the SHA instance. DmaPtr Pointer to the DMA instance. SignBuff Pointer to Signature buffer SignatureLen Length of signature buffer XST_SUCCESS - On successXSECURE_LMS_HSS_L1_PUB_KEY_LMS_TYPE_2_UNSUPPORTED_ERROR - Level 1 public key LMS type is unsupportedXSECURE_LMS_HSS_L1_PUB_KEY_LMS_OTS_TYPE_UNSUPPORTED_ERROR - Level 1 public key LMS OTS type is unsupportedXSECURE_LMS_HSS_OTS_SIGN_INVALID_LEN_1_ERROR - OTS signature length is invalidXSECURE_LMS_HSS_L1_SIGN_INVALID_LEN_2_ERROR - Level 1 signature length is invalidXSECURE_LMS_HSS_L0_PUB_KEY_AUTH_FAILED_ERROR - Level 0 public key authentication failedXST_FAILURE - On signature verification failure
References XSecure_LmsSignVerifyParams::Data, XSecure_LmsSignVerifyParams::DataLen, XSecure_LmsSignVerifyParams::ExpectedPubKey, XSecure_LmsSignVerifyParams::LmsSign, XSecure_LmsSignVerifyParams::LmsSignLen, XSecure_LmsParam::mh, XSecure_LmsSignVerifyParams::PreHashedMsg, XSecure_LmsSignVerifyParams::PubKeyLen, XSecure_LmsOtsParam::SignLen, XSECURE_DEBUG_GENERAL, XSECURE_LMS_HSS_L1_PUB_KEY_LMS_OTS_TYPE_UNSUPPORTED_ERROR, XSECURE_LMS_HSS_L1_PUB_KEY_LMS_TYPE_2_UNSUPPORTED_ERROR, XSECURE_LMS_HSS_L1_SIGN_INVALID_LEN_2_ERROR, XSECURE_LMS_HSS_OTS_SIGN_INVALID_LEN_1_ERROR, XSECURE_LMS_NOT_SUPPORTED, XSECURE_LMS_OTS_NOT_SUPPORTED, XSECURE_LMS_OTS_TYPE_SIZE, XSECURE_LMS_PUB_KEY_OTS_TYPE_OFFSET, XSECURE_LMS_PUB_KEY_TOTAL_SIZE, XSECURE_LMS_PUB_KEY_TYPE_OFFSET, XSECURE_LMS_Q_FIELD_SIZE, XSECURE_LMS_TYPE_SIZE, XSecure_LmsLookupParamSet, XSecure_LmsOtsLookupParamSet, XSecure_LmsSignatureVerification, XSecure_Printf.
Referenced by XSecure_HssSha2256Kat, XSecure_HssShake256Kat, XSecure_HssSignatureVerification.
int XSecure_HssSignatureVerification(XSecure_Sha *ShaInstPtr, XPmcDma *DmaPtr, XSecure_HssInitParams *HssInitParams, u8 *Data, u32 DataLen)
This function performs complete HSS signature verification in a single call.
It internally calls HssInit, LmsHashMessage, and HssFinish in sequence. The hash algorithm mode is automatically determined from the authenticated public key. ShaInstPtr Pointer to SHA instance DmaPtr Pointer to DMA instance HssInitParams Pointer to HSS initialization parameters (signature buffer, public key, and their lengths) Data Pointer to the data to be verified DataLen Length of data to be verified XST_SUCCESS - On successError codes from XSecure_HssInit, XSecure_LmsHashMessage, or XSecure_HssFinish on failure
References XSecure_LmsParam::H, XSecure_HssInitParams::SignatureLen, XSecure_HssInitParams::SignBuff, XSecure_HssFinish, XSecure_HssInit, XSECURE_LMS_INVALID_PARAM, XSECURE_LMS_PUB_KEY_TYPE_OFFSET, XSECURE_LMS_TYPE_SIZE, XSecure_LmsHashMessage, XSecure_LmsLookupParamSet.
int XSecure_GetLmsHashAlgo(u32 PubAlgo, const u8 *const PubKey, XSecure_ShaMode *SignAlgo)
This function returns public key LMS type.
PubAlgo Algorithm selected by current PDI PubKey Pointer to PPK location, PPK is used to detect the variant of LMS selected SignAlgo Pointer to store the extracted LMS hash algorithm XST_SUCCESS - On successXSECURE_LMS_HSS_L0_PUB_KEY_LMS_TYPE_UNSUPPORTED_ERROR - Level 0 public key LMS type is unsupportedXSECURE_LMS_INVALID_PARAM - Invalid public algorithm providedXST_FAILURE - On parameter lookup failure
References XSecure_LmsParam::H, XSECURE_DEBUG_GENERAL, XSECURE_HSS_PUBLIC_KEY_LMS_FIELD_OFFSET, XSECURE_LMS_HSS_L0_PUB_KEY_LMS_TYPE_UNSUPPORTED_ERROR, XSECURE_LMS_INVALID_PARAM, XSECURE_LMS_NOT_SUPPORTED, XSECURE_LMS_PUB_KEY_TYPE_OFFSET, XSECURE_LMS_TYPE_SIZE, XSecure_LmsLookupParamSet, XSecure_Printf.
static int XSecure_LmsSignVerifyIpi(XPlmi_Cmd *Cmd)
This function handler dispatches the request to either XSecure_LmsSignatureVerification (single-tree LMS) or XSecure_HssSignatureVerification (HSS, up to two levels) based on the public key length supplied by the client.
PubKeyLen == XSECURE_LMS_PUB_KEY_TOTAL_SIZE -> LMS PubKeyLen == XSECURE_HSS_PUBLIC_KEY_TOTAL_SIZE -> HSS Cmd Pointer to the command structure XST_SUCCESS On successful executionXSECURE_LMS_INVALID_PARAM If any input parameter is invalidXST_FAILURE If verification fails
int XSecure_LmsIpiHandler(XPlmi_Cmd *Cmd)
This function calls respective IPI handler based on the API_ID.
Cmd Pointer to the command structure XST_SUCCESS On successful executionXST_INVALID_PARAM If any input parameter is invalidXST_FAILURE If there is a failure
References XSECURE_API, XSECURE_API_ID_MASK, XSECURE_API_LMS_SIGN_VERIFY.
u32 XSecure_LmsOtsCoeff(u8 const *const Arr, const u32 ArrayIndex, const u32 w)
This function extracts the digits from the array for bytes.
S (represented in bits) = 0x1234 [0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0] ^ | coef(S, 7, 1) [1, 2, 3, 4] ^ | coef(S, 0, 4)If i is larger than the number of w-bit values in S, then coef(S, i, w) is undefined, this can't be checked here Arr Byte array from where the digit needs to be picked ArrayIndex When array is divided into array of digits, i represents the index of digit w Width in bits, for each digit allowed values digit value.
int XSecure_LmsOtsComputeChecksum(const u8 *const Array, const u32 ArrayLen, const u32 w, const u32 ls, u32 *const Checksum)
This function calculates the checksum for a given array.
Array Byte array ffor which checksum needs to be calculated ArrayLen Length of input array w Width in bits, for each digit allowed values ls Number of bits to left-shift the calculated checksum Checksum Pointer to address, where computed checksum needs to be copied XST_SUCCESS - On successXSECURE_LMS_OTS_CHECKSUM_BUFF_INVALID_LEN_ERROR - Invalid buffer length (zero length)
References XSECURE_LMS_OTS_CHECKSUM_BUFF_INVALID_LEN_ERROR.
int XSecure_LmsOtsLookupParamSet(XSecure_LmsOtsType Type, XSecure_LmsOtsParam **Parameters)
This function returns the parameters for the type of LMS OTS type.
Type XSecure_LmsOtsType, type of OTS algorithm selected Parameters Pointer to array location where all predefined parameter values are present XSecure_LmsOtsParam XST_SUCCESS - On successXSECURE_LMS_OTS_TYPE_UNSUPPORTED_ERROR - LMS OTS type is not supportedXSECURE_LMS_OTS_TYPE_LOOKUP_GLITCH_ERROR - Glitch detected during type lookup
References XSecure_LmsOtsParam::H, XSECURE_LMS_OTS_LS_NOT_SUPPORTED, XSECURE_LMS_OTS_P_NOT_SUPPORTED, XSECURE_LMS_OTS_U_NOT_SUPPORTED, XSECURE_LMS_OTS_V_NOT_SUPPORTED, XSECURE_LMS_OTS_W_NOT_SUPPORTED.
Referenced by XSecure_HssFinish, XSecure_HssInit, XSecure_LmsSignatureVerification.
XSECURE_IS_ODD
Check if a value is odd.
Referenced by XSecure_LmsSignatureVerification, XSecure_SlhdsaForsPkFromSig, XSecure_SlhdsaXmssPkFromSign.
XSECURE_LMS_TYPE_MAX_SUPPORTED
Max supported types, used for creating lookup table for parameters for types supported number should be max valid + 1 (as first slot will be for invalid parameters) XSecure_LmsType from 0 (unsupported) to XSECURE_LMS_SHAKE_M32_H20.
Referenced by XSecure_LmsLookupParamSet.
XSECURE_LMS_TYPE_SIZE
Length of type field.
Referenced by XSecure_GetLmsHashAlgo, XSecure_HssFinish, XSecure_HssInit, XSecure_HssSignatureVerification, XSecure_LmsSignatureVerification.
XSECURE_LMS_M_BYTE_FIELD_SIZE
Length of M byte field.
Referenced by XSecure_LmsSignatureVerification.
XSECURE_LMS_PUB_KEY_FIXED_FIELD_SIZE
Length of fixed part of public key.
Referenced by XSecure_LmsSignatureVerification.
XSECURE_LMS_PUB_KEY_T_FIELD_SIZE
Length of T field of public key.
Referenced by XSecure_LmsSignatureVerification.
XSECURE_LMS_PUB_KEY_TOTAL_SIZE
Length of total public key.
Referenced by XSecure_HssFinish, XSecure_HssInit, XSecure_LmsSha2256Kat, XSecure_LmsShake256Kat.
XSECURE_MERKLE_TREE_NODE_NUMBER_SIZE
Length of Merkle tree node number.
XSECURE_LMS_D_LEAF_FIELD_SIZE
Length of D leaf field.
XSECURE_LMS_D_INTR_FIELD_SIZE
Length of D internal field.
XSECURE_LMS_D_FIELD_SIZE
Length of D field.
XSECURE_LMS_PUB_KEY_TMP_BUFFER_LEAF_TOTAL_SIZE
Used for leaf node processing.
Referenced by XSecure_LmsSignatureVerification.
XSECURE_LMS_PUB_KEY_TMP_BUFFER_INTR_TOTAL_SIZE
Used for internal nodes processing.
Referenced by XSecure_LmsSignatureVerification.
XSECURE_LMS_PUB_KEY_TYPE_OFFSET
Offset of LmsType field in public key.
Referenced by XSecure_GetLmsHashAlgo, XSecure_HssFinish, XSecure_HssInit, XSecure_HssSignatureVerification, XSecure_LmsSignatureVerification.
XSECURE_LMS_PUB_KEY_OTS_TYPE_OFFSET
Offset of OtsType field in public key.
Referenced by XSecure_HssFinish, XSecure_HssInit, XSecure_LmsSignatureVerification.
XSECURE_LMS_PUB_KEY_I_OFFSET
Offset of I field in public key.
Referenced by XSecure_LmsSignatureVerification.
XSECURE_LMS_PUB_KEY_T_OFFSET
Offset of T field in public key.
Referenced by XSecure_LmsSignatureVerification.
XSECURE_LMS_SIGNATURE_Q_FIELD_OFFSET
Offset of Q field in LMS Signature.
Referenced by XSecure_HssInit, XSecure_LmsSignatureVerification.
XSECURE_LMS_SIGNATURE_OTS_FIELD_OFFSET
Offset of OTS field in LMS Signature.
Referenced by XSecure_HssInit, XSecure_LmsSignatureVerification.
XSECURE_LMS_PUB_KEY_TMP_BUF_ADJ_NODE_VAL_INDEX
LMS public key temporary buffer adjustment node value index.
Referenced by XSecure_LmsSignatureVerification.
XSECURE_BYTE_QUO
To Pick the byte in array.
XSECURE_BYTE_REM
Inside the byte interested value has to be right shifted.
XSECURE_BIT_MASK
Mask out rest of bits, only take w width back to caller invocations to get signature is equal to number of w width digits in a digest to get that, (2^w - 1), example w=8, Mask = 256.
XSECURE_BITS_PER_BYTE
Bits per byte.
XSECURE_LOWER_16_BIT_MASK
Lower 16 bit mask.
XSECURE_LMS_OTS_TYPE_MAX_SUPPORTED
Max supported types, used for creating lookup table for parameters for types supported number should be max valid + 1 (as first slot will be for invalid parameterXSecure_LmsOtsType XSecure_LmsOtsType.
XSECURE_ALLFS
32-bit value with all bits set
Referenced by XSecure_HssInit, XSecure_LmsLookupParamSet.
XSECURE_LMS_OTS_TYPE_SIZE
common lengths - they remain same irrespective of place they are used
Length of type field
Referenced by XSecure_HssFinish, XSecure_HssInit, XSecure_LmsSignatureVerification.
XSECURE_LMS_I_FIELD_SIZE
Length of I field.
Referenced by XSecure_HssInit, XSecure_LmsSignatureVerification.
XSECURE_LMS_Q_FIELD_SIZE
Length of q field.
Referenced by XSecure_HssFinish, XSecure_HssInit, XSecure_LmsSignatureVerification.
XSECURE_LMS_N_FIELD_SIZE
For now supported variants o/p length match.
XSECURE_LMS_C_FIELD_SIZE
32 byte random value for every msg to be authenticated
Referenced by XSecure_HssInit.
XSECURE_LMS_D_MESG_FIELD_SIZE
Size of XSECURE_D_MESG.
XSECURE_LMS_D_PBLC_FIELD_SIZE
Size of XSECURE_D_PBLC.
XSECURE_LMS_DIGEST_SIZE
Digest and Checksum related.
'n' bytes, output of SHA operation
Referenced by XSecure_LmsHashMessage.
XSECURE_LMS_CHECKSUM_FIELD_SIZE
Length of checksum field after digest.
XSECURE_LMS_DIGEST_CHECKSUM_SIZE
Digest of data to be authenticated concatenated with checksum value.
XSECURE_LMS_MESSAGE_TO_DIGEST_PREFIX_SIZE
Prefix fields length, before sending actual data to sha engine for digest.
Referenced by XSecure_LmsHashMessage.
XSECURE_LMS_OTS_PUB_KEY_FIXED_FIELD_SIZE
OTS public key sizes.
XSECURE_LMS_OTS_PUB_KEY_K_FIELD_SIZE
'n' bytes
Referenced by XSecure_LmsSignatureVerification.
XSECURE_LMS_OTS_PUB_KEY_TOTAL_SIZE
OTS Public key total size.
XSECURE_LMS_OTS_SIGN_VERIF_TMP_BUFF_i_SIZE
'i' Field, this causes different hash output for hash position in signature
XSECURE_LMS_OTS_SIGN_VERIF_TMP_BUFF_j_SIZE
'j' Field, this causes different hash output for per iteration (inner loop)
XSECURE_LMS_OTS_SIGN_VERIF_TMP_BUFF_Y_SIZE
Size of individual hash chain placed in sequence in signature
XSECURE_LMS_OTS_SIGN_VERIF_TMP_BUFF_TOTAL_SIZE
Total size of buffer, XSecure_LmsOtsHashPerDigit.
XSECURE_LMS_OTS_SIGN_VERIF_CHAIN_TMP_BUFF_CURR_z_SIZE
Used for calculating the size of z array, based on p value.
XSECURE_LMS_OTS_SIGN_VERIF_CHAIN_TMP_BUFF_z_SIZE
Max possible size as supported only till XSECURE_LMS_OTS_W2.
XSECURE_LMS_OTS_SIGN_VERIF_CHAIN_TMP_BUFF_TOTAL_SIZE
Total MAX Size of buffer used in OTS verification.
XSECURE_LMS_OTS_SIGN_VERIF_CHAIN_TMP_BUFF_CURRENT_SIZE
Total Size of buffer used in OTS verification, while considering current 'p' parameter.
XSECURE_LMS_OTS_PUBKEY_I_OFFSET
Offset of 'I' field in OTS Public key.
XSECURE_LMS_OTS_PUBKEY_Q_OFFSET
Offset of 'q' field in OTS Public key.
XSECURE_LMS_OTS_SIGN_TYPE_FIELD_OFFSET
Offset of 'Type' field in OTS Signature buffer.
Referenced by XSecure_LmsSignatureVerification.
XSECURE_LMS_OTS_SIGN_C_FIELD_OFFSET
Offset of 'C' field in OTS Signature buffer.
Referenced by XSecure_HssInit.
XSECURE_LMS_OTS_SIGN_Y_FIELD_OFFSET
Offset of 'Y' field in OTS Signature buffer.
XSECURE_LMS_OTS_SIGN_VERIF_TMP_BUFF_I_OFFSET
Offset of 'I' field in temporary buffer, where inner loops result are stored, for reprocessing during OTS operations.
XSECURE_LMS_OTS_SIGN_VERIF_TMP_BUFF_Q_OFFSET
Offset of 'q' field in temporary buffer, where inner loops result are stored, for reprocessing during OTS operations.
XSECURE_LMS_OTS_SIGN_VERIF_TMP_BUFF_i_OFFSET
Offset of 'i' field in temporary buffer, where inner loops result are stored, for reprocessing during OTS operations.
XSECURE_LMS_OTS_SIGN_VERIF_TMP_BUFF_j_OFFSET
Offset of 'j' field in temporary buffer, where inner loops result are stored, for reprocessing during OTS operations.
XSECURE_LMS_OTS_SIGN_VERIF_TMP_BUFF_Y_OFFSET
Offset of 'Y' field in temporary buffer, where inner loops result are stored, for reprocessing during OTS operations.
XSECURE_LMS_OTS_SIGN_VERIF_CHAIN_TMP_BUFF_I_OFFSET
Offset of 'I' field in temporary buffer, where inner loops result is concatenated during OTS operations.
XSECURE_LMS_OTS_SIGN_VERIF_CHAIN_TMP_BUFF_Q_OFFSET
Offset of 'q' field in temporary buffer, where inner loops result is concatenated during OTS operations.
XSECURE_LMS_OTS_SIGN_VERIF_CHAIN_TMP_BUFF_D_PBLC_OFFSET
Offset of D_PBLC field in temporary buffer, where inner loops result is concatenated during OTS operations.
XSECURE_LMS_OTS_SIGN_VERIF_CHAIN_TMP_BUFF_Z_OFFSET
Offset of 'z' field in temporary buffer, where inner loops result is concatenated during OTS operations.
XSECURE_LMS_MODULE_MAJOR_VERSION
LMS module major version.
XSECURE_LMS_MODULE_MINOR_VERSION
LMS module minor version.