xsecure_rsa_client_apis
const u8 P[XSECURE_PRIME_FACTOR_P_SIZE][XSECURE_PRIME_FACTOR_P_SIZE]
const u8 Q[XSECURE_PRIME_FACTOR_Q_SIZE][XSECURE_PRIME_FACTOR_Q_SIZE]
const u8 Tot[XSECURE_RSA_SIZE][XSECURE_RSA_SIZE]
const u8 DP[XSECURE_RSA_SIZE/2U][XSECURE_RSA_SIZE/2U]
const u8 DQ[XSECURE_RSA_SIZE/2U][XSECURE_RSA_SIZE/2U]
const u8 QInv[XSECURE_RSA_SIZE/2U][XSECURE_RSA_SIZE/2U]
const u8 RN[XSECURE_RSA_SIZE][XSECURE_RSA_SIZE]
const u8 RRN[XSECURE_RSA_SIZE][XSECURE_RSA_SIZE]
const u8 Data[XSECURE_RSA_SIZE][XSECURE_RSA_SIZE]
const u8 Modulus[XSECURE_RSA_SIZE][XSECURE_RSA_SIZE]
const u8 PrivateExp[XSECURE_RSA_SIZE][XSECURE_RSA_SIZE]
const u8 ExpectedSign[XSECURE_RSA_SIZE][XSECURE_RSA_SIZE]
const u32 PublicExp
u32 Size
u8 SharedMem[XSECURE_SHARED_BUF_SIZE][XSECURE_SHARED_BUF_SIZE]
XSecure_RsaKeyParam RsaKeyParam
const u8 Data[XSECURE_RSA_SIZE][XSECURE_RSA_SIZE]
const u8 Modulus[XSECURE_RSA_SIZE][XSECURE_RSA_SIZE]
const u8 PrivateExp[XSECURE_RSA_SIZE][XSECURE_RSA_SIZE]
const u8 ExpectedSign[XSECURE_RSA_SIZE][XSECURE_RSA_SIZE]
const u32 PublicExp
u32 Size
u8 SharedMem[XSECURE_SHARED_BUF_SIZE][XSECURE_SHARED_BUF_SIZE]
void XSecure_RsaGetCryptoAlgInfo(Xil_CryptoAlgInfo *AlgInfo)
This function returns the RSA crypto algorithm information.
AlgInfo Pointer to memory for holding the crypto algorithm information None
References XSECURE_API_RSA_SIGN_VERIFY, XSecure_GetAlgInfo.
int XSecure_RsaPrivateDecrypt(XSecure_ClientInstance *InstancePtr, const u64 KeyAddr, const u64 InDataAddr, const u32 Size, const u64 OutDataAddr)
This function sends IPI request to Perform RSA decryption with private key.
InstancePtr Pointer to the client instance KeyAddr Address of the Key InDataAddr Address of the data which has to be decrypted Size Key size in bytes, Input size also should be same as key size mentioned. Inputs supported are XSECURE_RSA_4096_KEY_SIZE, XSECURE_RSA_2048_KEY_SIZE, or XSECURE_RSA_3072_KEY_SIZE OutDataAddr Address of the buffer where resultant decrypted data to be stored XST_SUCCESS If the update is successfulXST_FAILURE If there is a failure
References XSECURE_ADDR_HIGH_SHIFT, XSECURE_API_RSA_PRIVATE_DECRYPT, XSecure_DCacheFlushRange, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
Referenced by XSecure_RsaCore, XSecure_RsaPrivateDecryptKat.
int XSecure_RsaPublicEncrypt(XSecure_ClientInstance *InstancePtr, const u64 KeyAddr, const u64 InDataAddr, const u32 Size, const u64 OutDataAddr)
This function sends IPI request to Perform RSA encryption with public key.
InstancePtr Pointer to the client instance KeyAddr Address of the Key InDataAddr Address of the data which has to be encrypted with public key Size Key size in bytes, Input size also should be same as key size mentioned. Inputs supported are XSECURE_RSA_4096_KEY_SIZE, XSECURE_RSA_2048_KEY_SIZE, or XSECURE_RSA_3072_KEY_SIZE OutDataAddr Address of the buffer where resultant decrypted data to be stored XST_SUCCESS If encryption was successfulXST_FAILURE If there is a failure
References XSECURE_ADDR_HIGH_SHIFT, XSECURE_API_RSA_PUBLIC_ENCRYPT, XSecure_DCacheFlushRange, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
Referenced by main, XSecure_DataAuth, XSecure_RsaCore, XSecure_RsaPublicEncryptKat, XSecure_SpkAuthentication.
int XSecure_RsaSignVerification(XSecure_ClientInstance *InstancePtr, const u64 SignAddr, const u64 HashAddr, const u32 Size)
This function sends IPI request to Perform RSA sign verification.
InstancePtr Pointer to the client instance SignAddr Address of the buffer which holds the decrypted RSA signature. HashAddr Address of the HashAddr which has the hash calculated on the data to be authenticated Size Length of Hash used For SHA3 it should be 48 bytes XST_SUCCESS If decryption was successfulXST_FAILURE In case of mismatch
References XSECURE_ADDR_HIGH_SHIFT, XSECURE_API_RSA_SIGN_VERIFY, XSecure_DCacheFlushRange, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
Referenced by XSecure_DataAuth, XSecure_SpkAuthentication.
static u32 SecureRsaExample(void)
This function authenticates boot image located in DDR using RSA-4096 algorithm.
The decrypted hash is matched against the calculated boot image hash. The purpose of this function is to illustrate how to use the XSecure_Rsa driver.- ErrorCode if RSA authentication is failed XST_SUCCESS if RSA authentication is successful. None.//! [RSA generic example]
static int XSecure_RsaCrtTest(XSecure_ClientInstance *SecureClientInstance)
This function does the RSA CRT test.
SecureClientInstance - Pointer to XSecure_ClientInstance - ErrorCode if RSA authentication is failed XST_SUCCESS if RSA authentication is successful.
static int XSecure_RsaExpoptTest(XSecure_ClientInstance *SecureClientInstance)
This function does the RSA private encryption using pre-calculated modulus.
SecureClientInstance - Pointer to XSecure_ClientInstance - ErrorCode if RSA authentication is failed XST_SUCCESS if RSA authentication is successful.
static int XSecure_RsaPublicEncryptTest(XSecure_ClientInstance *SecureClientInstance)
This function does RSA public encryption.
SecureClientInstance - Pointer to XSecure_ClientInstance - ErrorCode if RSA encryption is failed XST_SUCCESS if RSA encryption is successful.
int main(void)
This example illustrates the usage of RSA APIs to encrypt or decrypt the signature.
XST_SUCCESS if the boot image authentication is successful. ErrorCode if the boot image authentication Failed.
XSECURE_RSA_SIZE
512 bytes for 4096 bit data
XSECURE_RSA_SHARED_DATA_SIZE
XSECURE_SHARED_BUF_SIZE
XSECURE_PRIME_FACTOR_P_SIZE
256 bytes size of first prime factor(P)
XSECURE_PRIME_FACTOR_Q_SIZE
256 bytes size of first prime factor(Q)
SLR_INDEX
XSECURE_RSA_SIZE
512 bytes for 4096 bit data
XSECURE_RSA_SHARED_DATA_SIZE
XSECURE_SHARED_BUF_SIZE