xsecure_aes_zynqmp_apis
static u32 XSecure_Zeroize(u8 *DataPtr, u32 Length)
This function is used to zeroize the memory.
DataPtr Pointer to the memory which need to be zeroized. Length Length of the data. Final call of this API returns the status of Comparison. XSECURE_CSU_AES_ZEROIZATION_ERROR: If Zeroization is not Successful.XST_SUCCESS: If Zeroization is Successful.
static void XSecure_AesCsuDmaConfigureEndiannes(XCsuDma *InstancePtr, XCsuDma_Channel Channel, u8 EndianType)
This is a helper function to enable/disable byte swapping feature of CSU DMA.
InstancePtr Pointer to the XCsuDma instance. Channel Channel Type - XCSUDMA_SRC_CHANNEL XCSUDMA_DST_CHANNEL EndianType 1 : Enable Byte Swapping 0 : Disable Byte Swapping
static s32 XSecure_ReadNPassChunkToAes(XSecure_Aes *InstancePtr, const u8 *SrcAddr, const u8 *DestAddr, u32 Length, u8 EnLastFlag)
This API reads bitstream from flash device to destination address.
This API should be called while loading bitstream in chunks. InstancePtr is a pointer to the XSecure_Aes instance SrcAddr is address of encrypted data source location DestAddr is address of location where data will get copied Length Length of data to be copied in bytes EnLastFlag is to indicate end of data returns XST_SUCCESS if successful, or the relevant errorcode
static s32 XSecure_PassChunkToAes(XCsuDma *InstancePtr, const u8 *SrcAddr, u32 Length, u8 EnLastFlag)
This API triggers DMA at source address.
This API should be called while loading bitstream in chunks. InstancePtr is a pointer to the XCsuDma instance SrcAddr is address of encrypted data source location Length Length of data to be copied in bytes EnLastFlag is to indicate end of data returns XST_SUCCESS if successful, or the relevant errorcode
s32 XSecure_AesInitialize(XSecure_Aes *InstancePtr, XCsuDma *CsuDmaPtr, u32 KeySel, u32 *IvPtr, u32 *KeyPtr)
This function initializes the instance pointer.
InstancePtr Pointer to the XSecure_Aes instance. CsuDmaPtr Pointer to the XCsuDma instance. KeySel Key source for decryption, can be KUP/device key (XSECURE_CSU_AES_KEY_SRC_KUP for KUP key or XSECURE_CSU_AES_KEY_SRC_DEV for Device Key) IvPtr Pointer to the Initialization Vector for decryption KeyPtr Pointer to Aes key in case KUP key is used. Pass Null if the device key is to be used. XST_SUCCESS if initialization was successful. All the inputs are accepted in little endian format but the AES engine accepts the data in big endian format, The decryption and encryption functions in xsecure_aes handle the little endian to big endian conversion using few API's, Xil_Htonl (provided by Xilinx xil_io library) and XSecure_AesCsuDmaConfigureEndiannes for handling data endianness conversions. If higher performance is needed, users can strictly use data in big endian format and modify the xsecure_aes functions to remove the use of the Xil_Htonl and XSecure_AesCsuDmaConfigureEndiannes functions as required.
References XSecure_CryptoCheck, XSECURE_CSU_AES_BASE, XSecure_SssInitialize.
u32 XSecure_AesEncryptInit(XSecure_Aes *InstancePtr, u8 *EncData, u32 Size)
This function is used to initialize the AES engine for encryption.
InstancePtr Pointer to the XSecure_Aes instance. EncData Pointer of a buffer in which encrypted data along with GCM TAG will be stored. Buffer size should be Size of data plus 16 bytes. Size A 32 bit variable, which holds the size of the input data to be encrypted in bytes, whereas number of bytes provided should be multiples of 4. None If all of the data to be encrypted is available, the XSecure_AesEncryptData function can be used instead.
References XSecure_AesKeySelNLoad, XSecure_AesKeyZero, XSecure_AesReset, XSECURE_CSU_AES_CFG_OFFSET, XSECURE_CSU_AES_KEY_CLR_OFFSET, XSECURE_CSU_AES_KUP_0_OFFSET, XSECURE_CSU_AES_RESET_OFFSET, XSECURE_CSU_AES_START_MSG_OFFSET, XSecure_Out32, XSecure_SetReset, XSECURE_SSS_DMA0, XSecure_SssAes.
u32 XSecure_AesEncryptUpdate(XSecure_Aes *InstancePtr, const u8 *Data, u32 Size)
This function encrypts the clear-text data passed in and updates the GCM tag from any previous calls.
The size from XSecure_AesEncryptInit is decremented from the size passed into this function to determine when the final CSU DMA transfer of data to the AES-GCM cryptographic core. InstancePtr Pointer to the XSecure_Aes instance. Data Pointer to the data for which encryption should be performed. Size A 32 bit variable, which holds the size of the input data in bytes, whereas the number of bytes provided should be multiples of 4. None If all of the data to be encrypted is available, the XSecure_AesEncryptData function can be used instead.
References XSecure_AesKeyZero, XSecure_AesWaitForDone, XSECURE_CSU_AES_RESET_OFFSET, XSecure_SetReset.
u32 XSecure_AesEncryptData(XSecure_Aes *InstancePtr, u8 *Dst, const u8 *Src, u32 Len)
This function encrypts Len (length) number of bytes of the passed in Src (source) buffer and stores the encrypted data along with its associated 16 byte tag in the Dst (destination) buffer.
InstancePtr A pointer to the XSecure_Aes instance. Dst A pointer to a buffer where encrypted data along with GCM tag will be stored. The Size of buffer provided should be Size of the data plus 16 bytes Src A pointer to input data for encryption. Len Size of input data in bytes, whereas the number of bytes provided should be multiples of 4. None If data to be encrypted is not available in one buffer one can call XSecure_AesEncryptInit() and update the AES engine with data to be encrypted by calling XSecure_AesEncryptUpdate() API multiple times as required.
References XSecure_AesEncryptInit, XSecure_AesEncryptUpdate.
u32 XSecure_AesDecryptInit(XSecure_Aes *InstancePtr, u8 *DecData, u32 Size, u8 *GcmTagAddr)
This function initializes the AES engine for decryption and is required to be called before calling XSecure_AesDecryptUpdate.
InstancePtr Pointer to the XSecure_Aes instance. DecData Pointer in which decrypted data will be stored. Size Expected size of the data in bytes whereas the number of bytes provided should be multiples of 4. GcmTagAddr Pointer to the GCM tag which needs to be verified during decryption of the data. None If all of the data to be decrypted is available, the XSecure_AesDecryptData function can be used instead.
References XSecure_AesKeySelNLoad, XSecure_AesKeyZero, XSecure_AesReset, XSECURE_CSU_AES_CFG_OFFSET, XSECURE_CSU_AES_KEY_CLR_OFFSET, XSECURE_CSU_AES_KUP_0_OFFSET, XSECURE_CSU_AES_RESET_OFFSET, XSECURE_CSU_AES_START_MSG_OFFSET, XSecure_Out32, XSecure_SetReset, XSECURE_SSS_DMA0, XSecure_SssAes.
s32 XSecure_AesDecryptUpdate(XSecure_Aes *InstancePtr, u8 *EncData, u32 Size)
This function decrypts the encrypted data passed in and updates the GCM tag from any previous calls.
The size from XSecure_AesDecryptInit is decremented from the size passed into this function to determine when the GCM tag passed to XSecure_AesDecryptInit needs to be compared to the GCM tag calculated in the AES engine. InstancePtr Pointer to the XSecure_Aes instance. EncData Pointer to the encrypted data which needs to be decrypted. Size Expected size of data to be decrypted in bytes, whereas the number of bytes should be multiples of 4. Final call of this API returns the status of GCM tag matching. XSECURE_CSU_AES_GCM_TAG_MISMATCH: If GCM tag is mismatchedXSECURE_CSU_AES_ZEROIZATION_ERROR: If GCM tag is mismatched, zeroize the decrypted data and send the status of zeroization.XST_SUCCESS: If GCM tag is matching. When Size of the data equals to size of the remaining data that data will be treated as final data. This API can be called multpile times but sum of all Sizes should be equal to Size mention in init. Return of the final call of this API tells whether GCM tag is matching or not.
References XSecure_AesKeyZero, XSecure_AesWaitForDone, XSECURE_CSU_AES_IV_3_OFFSET, XSECURE_CSU_AES_RESET_OFFSET, XSECURE_CSU_AES_STS_OFFSET, XSecure_SetReset.
s32 XSecure_AesDecryptData(XSecure_Aes *InstancePtr, u8 *DecData, u8 *EncData, u32 Size, u8 *GcmTagAddr)
This function decrypts the encrypted data provided and updates the DecData buffer with decrypted data.
InstancePtr Pointer to the XSecure_Aes instance. DecData Pointer to a buffer in which decrypted data will be stored. EncData Pointer to the encrypted data which needs to be decrypted. Size Size of data to be decrypted in bytes, whereas the number of bytes should be multiples of 4. Size Size of data to be decrypted in bytes, whereas the number of bytes should be multiples of 4. GcmTagAddr Pointer to a buffer in which GCM tag address will be stored. This API returns the status of GCM tag matching. XSECURE_CSU_AES_GCM_TAG_MISMATCH: If GCM tag was mismatchedXST_SUCCESS: If GCM tag was matched. When using this function to decrypt data that was encrypted with XSecure_AesEncryptData, the GCM tag will be stored as the last sixteen (16) bytes of data in XSecure_AesEncryptData's Dst (destination) buffer and should be used as the GcmTagAddr's pointer.
References XSecure_AesDecryptInit, XSecure_AesDecryptUpdate.
void XSecure_AesSetChunking(XSecure_Aes *InstancePtr, u8 Chunking)
This API enables/disables data chunking.
Chunking will be used when complete encrypted data is not present at a single contiguous location (for eg. DDR less systems.) or the data source is not directly reachable through CSU DMA. InstancePtr Pointer to the XSecure_Aes instance. Chunking Used to enable or disable data chunking. None Chunking enable will be taken account only for XSecure_AesDecrypt() API usage.
void XSecure_AesSetChunkConfig(XSecure_Aes *InstancePtr, u8 *ReadBuffer, u32 ChunkSize, u32(*DeviceCopy)(u32, UINTPTR, u32))
This function sets the configuration for Data Chunking.
InstancePtr Pointer to the XSecure_Aes instance. ReadBuffer Buffer where the data will be written after copying. ChunkSize Length of the buffer in bytes. DeviceCopy Function pointer to copy data from FLASH to buffer. Arguments are: SrcAddress: Address of data in deviceDestAddress: Address where data will be copiedLength: Length of data in bytes. Return value should be 0 in case of success and 1 in case of failure. None This function should be used along with XSecure_AesSetChunkConfig() API, this feature is taken into account only for XSecure_AesDecrypt() API while decrypting the boot image's partition which is generated using bootgen.
void XSecure_AesReset(XSecure_Aes *InstancePtr)
This function sets and then clears the AES-GCM's reset line.
InstancePtr is a pointer to the XSecure_Aes instance.
References XSECURE_CSU_AES_RESET_OFFSET, XSecure_ReleaseReset.
Referenced by XSecure_AesDecrypt, XSecure_AesDecryptInit, XSecure_AesEncryptInit.
u32 XSecure_AesKeyZero(XSecure_Aes *InstancePtr)
This function resets the AES key storage registers.
InstancePtr Pointer to the XSecure_Aes instance. None
References XSECURE_CSU_AES_KEY_CLR_OFFSET, XSECURE_CSU_AES_STS_OFFSET.
u32 XSecure_AesKeySelNLoad(XSecure_Aes *InstancePtr)
This function configures and load AES key from selected key source.
InstancePtr Pointer to the XSecure_Aes instance. None
References XSecure_AesWaitKeyLoad, XSECURE_CSU_AES_KEY_LOAD_OFFSET, XSECURE_CSU_AES_KEY_SRC_OFFSET.
Referenced by XSecure_AesDecrypt, XSecure_AesDecryptInit, XSecure_AesEncryptInit.
static s32 XSecure_AesChunkDecrypt(XSecure_Aes *InstancePtr, const u8 *Src, u32 Len)
This is a helper function to decrypt chunked bitstream block and route to PCAP.
InstancePtr Pointer to the XSecure_Aes instance. Src Pointer to the encrypted bitstream block start. Len Length of bitstream data block in bytes, whereas the number of bytes should be multiples of 4. returns XST_SUCCESS if bitstream block is decrypted by AES.
s32 XSecure_AesDecryptBlk(XSecure_Aes *InstancePtr, u8 *Dst, const u8 *Src, const u8 *Tag, u32 Len, u32 Flag)
This function handles decryption using the AES engine.
InstancePtr Pointer to the XSecure_Aes instance. Dst Pointer to location where decrypted data will be written Src Pointer to encrypted input data Tag Pointer to the GCM tag used for authentication Len Length of the output data (in bytes)expected after decryption, whereas the number of bytes should be multiple of 4. Flag Denotes whether the block is Secure header or data block 0 : Secure Header 1 : Data Block / image returns XST_SUCCESS if GCM tag matching was successful
References XSecure_AesWaitForDone, XSECURE_CSU_AES_KUP_WR_OFFSET, XSECURE_CSU_AES_START_MSG_OFFSET, XSECURE_CSU_AES_STS_OFFSET.
Referenced by XSecure_AesDecrypt.
s32 XSecure_AesDecrypt(XSecure_Aes *InstancePtr, u8 *Dst, const u8 *Src, u32 Length)
This function will handle the AES-GCM Decryption.
InstancePtr Pointer to the XSecure_Aes instance. Src Pointer to encrypted data source location Dst Pointer to location where decrypted data will be written. Length Expected total length of decrypted image expected. returns XST_SUCCESS if successful, or the relevant errorcode. This function is used for decrypting the Image's partition encrypted by Bootgen
References XSecure_AesDecryptBlk, XSecure_AesKeySelNLoad, XSecure_AesKeyZero, XSecure_AesReset, XSECURE_CSU_AES_CFG_OFFSET, XSECURE_CSU_AES_IV_0_OFFSET, XSECURE_CSU_AES_IV_3_OFFSET, XSECURE_CSU_AES_KEY_CLR_OFFSET, XSECURE_CSU_AES_KUP_0_OFFSET, XSECURE_CSU_AES_RESET_OFFSET, XSecure_Out32, XSecure_SetReset, XSECURE_SSS_DMA0, XSecure_SssAes.
Referenced by SecureAesExample.
XSecure_AesWaitKeyLoad
This macro waits for AES engine to complete key loading.
InstancePtr Pointer to the XSecure_Aes instance. XST_SUCCESS if the AES engine completes key loading. XST_FAILURE if a timeout has occurred.
Referenced by XSecure_AesKeySelNLoad.
XSecure_AesWaitForDone
This macro waits for AES engine to complete configured operation.
InstancePtr Pointer to the XSecure_Aes instance. XST_SUCCESS if the AES engine completes configured operation. XST_FAILURE if a timeout has occurred.
Referenced by XSecure_AesDecryptBlk, XSecure_AesDecryptUpdate, XSecure_AesEncryptUpdate.