xsecure_kat_server_apis
XSECURE_KAT_AES_SPLIT_DATA_SIZE
< AES KAT parameters
XSECURE_KAT_KEY_SIZE_IN_WORDS
XSECURE_KAT_OPER_DATA_SIZE_IN_WORDS
const u32 Key0[XSECURE_KAT_KEY_SIZE_IN_WORDS][XSECURE_KAT_KEY_SIZE_IN_WORDS]
const u32 Data0[XSECURE_KAT_OPER_DATA_SIZE_IN_WORDS][XSECURE_KAT_OPER_DATA_SIZE_IN_WORDS]
const u32 Ct0[XSECURE_KAT_AES_SPLIT_DATA_SIZE][XSECURE_KAT_AES_SPLIT_DATA_SIZE]
const u32 MiC0[XSECURE_KAT_AES_SPLIT_DATA_SIZE][XSECURE_KAT_AES_SPLIT_DATA_SIZE]
const u8 KatMessage[XSECURE_KAT_MSG_LEN_IN_BYTES][XSECURE_KAT_MSG_LEN_IN_BYTES]
const u8 AesKey[XSECURE_KAT_KEY_SIZE_IN_BYTES][XSECURE_KAT_KEY_SIZE_IN_BYTES]
const u8 AesIv[XSECURE_KAT_IV_SIZE_IN_BYTES][XSECURE_KAT_IV_SIZE_IN_BYTES]
const u8 AesCt[XSECURE_KAT_MSG_LEN_IN_BYTES][XSECURE_KAT_MSG_LEN_IN_BYTES]
const u8 AesGcmTag[XSECURE_SECURE_GCM_TAG_SIZE][XSECURE_SECURE_GCM_TAG_SIZE]
const u8 AesAadData[XSECURE_KAT_AAD_SIZE_IN_BYTES][XSECURE_KAT_AAD_SIZE_IN_BYTES]
const u8 ExpSha3Hash[XSECURE_SHA_384_HASH_SIZE_IN_BYTES][XSECURE_SHA_384_HASH_SIZE_IN_BYTES]
const u32 RsaModulus[XSECURE_RSA_2048_SIZE_WORDS][XSECURE_RSA_2048_SIZE_WORDS]
const u32 RsaModExt[XSECURE_RSA_2048_SIZE_WORDS][XSECURE_RSA_2048_SIZE_WORDS]
const u32 RsaData[XSECURE_RSA_2048_SIZE_WORDS][XSECURE_RSA_2048_SIZE_WORDS]
const u32 RsaExpCtData[XSECURE_RSA_2048_SIZE_WORDS][XSECURE_RSA_2048_SIZE_WORDS]
const u8 Pubkey_P384[XSECURE_ECC_P384_SIZE_IN_BYTES+XSECURE_ECC_P384_SIZE_IN_BYTES][XSECURE_ECC_P384_SIZE_IN_BYTES+XSECURE_ECC_P384_SIZE_IN_BYTES]
const u8 Sign_P384[XSECURE_ECC_P384_SIZE_IN_BYTES+XSECURE_ECC_P384_SIZE_IN_BYTES][XSECURE_ECC_P384_SIZE_IN_BYTES+XSECURE_ECC_P384_SIZE_IN_BYTES]
const u8 D_P384[XSECURE_ECC_P384_SIZE_IN_BYTES][XSECURE_ECC_P384_SIZE_IN_BYTES]
const u8 K_P384[XSECURE_ECC_P384_SIZE_IN_BYTES][XSECURE_ECC_P384_SIZE_IN_BYTES]
const u8 ExpEccSha3Hash[XSECURE_KAT_ECC_P521_SHA3_HASH_SIZE_IN_BYTES][XSECURE_KAT_ECC_P521_SHA3_HASH_SIZE_IN_BYTES]
const u8 Sha256InputData[48][48]
const u8 ExpSha256Hash[XSECURE_SHA2_256_HASH_LEN][XSECURE_SHA2_256_HASH_LEN]
const u8 KatMessage[XSECURE_KAT_MSG_LEN_IN_BYTES][XSECURE_KAT_MSG_LEN_IN_BYTES]
const u8 ExpShakeHash[XSECURE_SHAKE_256_HASH_LEN][XSECURE_SHAKE_256_HASH_LEN]
u8 Signature_Shake256_l0h5w2[XSECURE_HSS_SIGNATURE_SIZE_BYTES][XSECURE_HSS_SIGNATURE_SIZE_BYTES]
u8 HssShake256PubKey[XSECURE_HSS_PUBLIC_KEY_TOTAL_SIZE][XSECURE_HSS_PUBLIC_KEY_TOTAL_SIZE]
levels = 1 LMS type = XSECURE_LMS_SHAKE_M32_H5 OTS type = XSECURE_LMS_OTS_SHAKE_N32_W2
u8 Shake_256HssData[XSECURE_LMS_DATA_SIZE_BYTES][XSECURE_LMS_DATA_SIZE_BYTES]
u8 Signature_HssSha2256_l0h5w2[XSECURE_HSS_SIGNATURE_SIZE_BYTES][XSECURE_HSS_SIGNATURE_SIZE_BYTES]
u8 HssSha2256PubKey[XSECURE_HSS_PUBLIC_KEY_TOTAL_SIZE][XSECURE_HSS_PUBLIC_KEY_TOTAL_SIZE]
levels = 2 LMS type = XSECURE_LMS_SHA256_M32_H5 OTS type = XSECURE_LMS_OTS_SHA256_N32_W2
u8 HssSha2_256LmsData[XSECURE_LMS_DATA_SIZE_BYTES][XSECURE_LMS_DATA_SIZE_BYTES]
u8 LmsSha2256PubKey[XSECURE_HSS_PUBLIC_KEY_TOTAL_SIZE][XSECURE_HSS_PUBLIC_KEY_TOTAL_SIZE]
levels = 2 LMS type = XSECURE_LMS_SHA256_M32_H5 OTS type = XSECURE_LMS_OTS_SHA256_N32_W2
u8 LmsSha2256Data[XSECURE_LMS_DATA_SIZE_BYTES][XSECURE_LMS_DATA_SIZE_BYTES]
u8 Signature_LmsSha256_h5w2[XSECURE_LMS_SIGNATURE_SIZE_BYTES][XSECURE_LMS_SIGNATURE_SIZE_BYTES]
u8 Signature_Shake256_h5w2[XSECURE_LMS_SIGNATURE_SIZE_BYTES][XSECURE_LMS_SIGNATURE_SIZE_BYTES]
u8 Shake_256LmsData[XSECURE_LMS_DATA_SIZE_BYTES][XSECURE_LMS_DATA_SIZE_BYTES]
levels = 1 LMS type = XSECURE_LMS_SHAKE_M32_H5 OTS type = XSECURE_LMS_OTS_SHAKE_N32_W2
u8 LmsShake256PubKey[XSECURE_LMS_PUB_KEY_TOTAL_SIZE][XSECURE_LMS_PUB_KEY_TOTAL_SIZE]
const u8 Sha256InputData[48][48]
const u8 ExpSha256Hash[XSECURE_SHA2_256_HASH_LEN][XSECURE_SHA2_256_HASH_LEN]
const u8 KatMessage[XSECURE_KAT_MSG_LEN_IN_BYTES][XSECURE_KAT_MSG_LEN_IN_BYTES]
const u8 ExpShakeHash[XSECURE_SHAKE_256_HASH_LEN][XSECURE_SHAKE_256_HASH_LEN]
u8 Signature_Shake256_l0h5w2[XSECURE_HSS_SIGNATURE_SIZE_BYTES][XSECURE_HSS_SIGNATURE_SIZE_BYTES]
u8 HssShake256PubKey[XSECURE_HSS_PUBLIC_KEY_TOTAL_SIZE][XSECURE_HSS_PUBLIC_KEY_TOTAL_SIZE]
levels = 1 LMS type = XSECURE_LMS_SHAKE_M32_H5 OTS type = XSECURE_LMS_OTS_SHAKE_N32_W2
u8 Shake_256HssData[XSECURE_LMS_DATA_SIZE_BYTES][XSECURE_LMS_DATA_SIZE_BYTES]
u8 Signature_HssSha2256_l0h5w2[XSECURE_HSS_SIGNATURE_SIZE_BYTES][XSECURE_HSS_SIGNATURE_SIZE_BYTES]
u8 HssSha2256PubKey[XSECURE_HSS_PUBLIC_KEY_TOTAL_SIZE][XSECURE_HSS_PUBLIC_KEY_TOTAL_SIZE]
levels = 2 LMS type = XSECURE_LMS_SHA256_M32_H5 OTS type = XSECURE_LMS_OTS_SHA256_N32_W2
u8 HssSha2_256LmsData[XSECURE_LMS_DATA_SIZE_BYTES][XSECURE_LMS_DATA_SIZE_BYTES]
u8 LmsSha2256PubKey[XSECURE_HSS_PUBLIC_KEY_TOTAL_SIZE][XSECURE_HSS_PUBLIC_KEY_TOTAL_SIZE]
levels = 2 LMS type = XSECURE_LMS_SHA256_M32_H5 OTS type = XSECURE_LMS_OTS_SHA256_N32_W2
u8 LmsSha2256Data[XSECURE_LMS_DATA_SIZE_BYTES][XSECURE_LMS_DATA_SIZE_BYTES]
u8 Signature_LmsSha256_h5w2[XSECURE_LMS_SIGNATURE_SIZE_BYTES][XSECURE_LMS_SIGNATURE_SIZE_BYTES]
u8 Signature_Shake256_h5w2[XSECURE_LMS_SIGNATURE_SIZE_BYTES][XSECURE_LMS_SIGNATURE_SIZE_BYTES]
u8 Shake_256LmsData[XSECURE_LMS_DATA_SIZE_BYTES][XSECURE_LMS_DATA_SIZE_BYTES]
levels = 1 LMS type = XSECURE_LMS_SHAKE_M32_H5 OTS type = XSECURE_LMS_OTS_SHAKE_N32_W2
u8 LmsShake256PubKey[XSECURE_LMS_PUB_KEY_TOTAL_SIZE][XSECURE_LMS_PUB_KEY_TOTAL_SIZE]
static int XSecure_AesDecCmChecks(const u32 *P, const u32 *Q, const u32 *R, const u32 *S)
This function performs checks for AES DPA CM KAT output.
P is the pointer to the data array of size 4 words. Q is the pointer to the data array of size 4 words. R is the pointer to the data array of size 4 words. S is the pointer to the data array of size 4 words. XST_SUCCESS - When check is passedXST_FAILURE - when check is failed
u8 * XSecure_GetKatMessage(void)
This function returns message to perform KAT.
Message to perform KAT
Referenced by XSecure_AesDecryptKat, XSecure_AesEncryptKat, XSecure_HmacKat, XSecure_RsaPwct, XSecure_Sha384Kat.
u8 * XSecure_GetKatAesKey(void)
This function returns AES key for KAT.
AES key for KAT
Referenced by XSecure_HmacKat.
u8 * XSecure_GetKatSha3ExpHash(void)
This function returns expected SHA3 hash for KAT.
Expected SHA3 hash for KAT
u32 * XSecure_GetKatRsaModulus(void)
This function returns modulus for RSA KAT.
RSA modulus for KAT
Referenced by XSecure_RsaPrivateDecryptKat.
u32 * XSecure_GetKatRsaModExt(void)
This function returns public pre-calculated exponential (R^2 Mod N) value for RSA KAT.
RSA pre-calculated exponential (R^2 Mod N) value for KAT
Referenced by XSecure_RsaPrivateDecryptKat.
u32 * XSecure_GetKatRsaData(void)
This function returns data for RSA KAT.
Input data to be encrypted for RSA KAT
Referenced by XSecure_RsaPrivateDecryptKat.
u32 * XSecure_GetKatRsaCtData(void)
This function returns cipher text data for RSA KAT.
Expected cipher text for RSA KAT
Referenced by XSecure_RsaPrivateDecryptKat.
u32 * XSecure_GetKatRsaPrivateExp(void)
This function returns private exponent for RSA KAT.
RSA private exponent for KAT
References XSECURE_RSA_2048_SIZE_WORDS.
Referenced by XSecure_RsaPrivateDecryptKat.
XSecure_EllipticKey * XSecure_GetKatEccPublicKey(XSecure_EllipticCrvClass CrvClass)
This function returns ECC public key to perform KAT.
CrvClass ECC curve class ECC public key
References XSecure_EllipticKey::Qx, XSecure_EllipticKey::Qy, XSECURE_ECC_P384_SIZE_IN_BYTES, XSECURE_ECC_PRIME.
Referenced by XSecure_EllipticVerifySignKat.
XSecure_EllipticSign * XSecure_GetKatEccExpSign(XSecure_EllipticCrvClass CrvClass)
This function returns ECC expected signature to perform KAT.
CrvClass ECC curve class ECC expected signature
References XSecure_EllipticSign::SignR, XSecure_EllipticSign::SignS, XSECURE_ECC_P384_SIZE_IN_BYTES, XSECURE_ECC_PRIME.
Referenced by XSecure_EllipticSignGenerateKat, XSecure_EllipticVerifySignKat.
u8 * XSecure_GetKatEccPrivateKey(XSecure_EllipticCrvClass CrvClass)
This function returns ECC private key to perform KAT.
CrvClass ECC curve class ECC private key
References XSECURE_ECC_PRIME.
Referenced by XSecure_EllipticSignGenerateKat.
u8 * XSecure_GetKatEccEphemeralKey(XSecure_EllipticCrvTyp CrvType)
This function returns ECC ephemeral key to perform KAT.
CrvType ECC curve type ECC ephemeral key
References XSECURE_ECC_NIST_P192, XSECURE_ECC_NIST_P224, XSECURE_ECC_NIST_P256, XSECURE_ECC_NIST_P384, XSECURE_ECC_NIST_P521.
Referenced by XSecure_EllipticPwct, XSecure_EllipticSignGenerateKat.
int XSecure_AesDecryptCmKat(const XSecure_Aes *AesInstance)
This function performs known answer test(KAT) on AES engine to confirm DPA counter measures is working fine.
AesInstance Pointer to the XSecure_Aes instance XST_SUCCESS - When KAT PassXSECURE_AESKAT_INVALID_PARAM - On invalid argumentXSECURE_AES_KAT_BUSY - when AES is busyXSECURE_AES_STATE_MISMATCH_ERROR - If AES state is mismatchedXSECURE_AESDPACM_KAT_CHECK1_FAILED_ERROR - Error when AESDPACM data not matched with expected dataXSECURE_AESDPACM_KAT_CHECK2_FAILED_ERROR - Error when AESDPACM data not matched with expected dataXSECURE_AESDPACM_KAT_CHECK3_FAILED_ERROR - Error when AESDPACM data not matched with expected dataXSECURE_AESDPACM_KAT_CHECK4_FAILED_ERROR - Error when AESDPACM data not matched with expected dataXSECURE_AESDPACM_KAT_CHECK5_FAILED_ERROR - Error when AESDPACM data not matched with expected dataXST_FAILURE - On failure
References R0, XSECURE_AES_KAT_BUSY, XSECURE_AES_STATE_MISMATCH_ERROR, XSECURE_AES_USER_KEY_7, XSECURE_AESDPACM_KAT_CHECK1_FAILED_ERROR, XSECURE_AESDPACM_KAT_CHECK2_FAILED_ERROR, XSECURE_AESDPACM_KAT_CHECK3_FAILED_ERROR, XSECURE_AESDPACM_KAT_CHECK4_FAILED_ERROR, XSECURE_AESDPACM_KAT_CHECK5_FAILED_ERROR, XSecure_AesDpaCmDecryptData, XSECURE_AESKAT_INVALID_PARAM, XSecure_AesKeyZero.
int XSecure_AesDecryptKat(XSecure_Aes *AesInstance)
This function performs decryption known answer test(KAT) on AES engine.
AesInstance Pointer to the XSecure_Aes instance XST_SUCCESS - When KAT PassXSECURE_AESKAT_INVALID_PARAM - Invalid ArgumentXSECURE_AES_KAT_BUSY - Error when AES is busyXSECURE_AES_STATE_MISMATCH_ERROR - Error when AES state is mismatchedXSECURE_AES_KAT_WRITE_KEY_FAILED_ERROR - Error when AES key write failsXSECURE_AES_KAT_DECRYPT_INIT_FAILED_ERROR - Error when AES decrypt init failsXSECURE_AES_KAT_UPDATE_AAD_FAILED_ERROR - Error when update AAD failsXSECURE_AES_KAT_DECRYPT_UPDATE_FAILED_ERROR - Error when decrypt update failsXSECURE_AES_KAT_GCM_TAG_MISMATCH_ERROR - Error when GCM tag not matched with user provided tagXSECURE_AES_KAT_DATA_MISMATCH_ERROR - Error when AES data not matched with expected data
References XSECURE_AES_KAT_BUSY, XSECURE_AES_KAT_DATA_MISMATCH_ERROR, XSECURE_AES_KAT_DECRYPT_INIT_FAILED_ERROR, XSECURE_AES_KAT_DECRYPT_UPDATE_FAILED_ERROR, XSECURE_AES_KAT_GCM_TAG_MISMATCH_ERROR, XSECURE_AES_KAT_UPDATE_AAD_FAILED_ERROR, XSECURE_AES_KAT_WRITE_KEY_FAILED_ERROR, XSECURE_AES_STATE_MISMATCH_ERROR, XSECURE_AES_USER_KEY_7, XSecure_AesDecryptFinal, XSecure_AesDecryptInit, XSecure_AesDecryptUpdate, XSECURE_AESKAT_INVALID_PARAM, XSecure_AesKeyZero, XSecure_AesUpdateAad, XSecure_AesWriteKey, XSecure_ConfigureDmaByteSwap, XSECURE_ENABLE_BYTE_SWAP, XSecure_GetKatMessage, XSECURE_KAT_AAD_SIZE_IN_BYTES, XSECURE_KAT_MSG_LEN_IN_BYTES, XSECURE_KAT_MSG_LEN_IN_WORDS.
int XSecure_AesEncryptKat(XSecure_Aes *AesInstance)
This function performs encryption known answer test(KAT) on AES engine.
AesInstance Pointer to the XSecure_Aes instance XST_SUCCESS - When KAT PassXSECURE_AESKAT_INVALID_PARAM - Invalid ArgumentXSECURE_AES_KAT_BUSY - Error when AES is busyXSECURE_AES_STATE_MISMATCH_ERROR - Error when AES state is mismatchedXSECURE_AES_KAT_WRITE_KEY_FAILED_ERROR - Error when AES key write failsXSECURE_AES_KAT_ENCRYPT_INIT_FAILED_ERROR - Error when AES encrypt init failsXSECURE_AES_KAT_UPDATE_AAD_FAILED_ERROR - Error when update AAD failsXSECURE_AES_KAT_ENCRYPT_UPDATE_FAILED_ERROR - Error when AES encrypt update failsXSECURE_AES_KAT_ENCRYPT_FINAL_FAILED_ERROR - Error when AES encrypt final failsXSECURE_KAT_GCM_TAG_MISMATCH_ERROR - Error when GCM tag not matched with user provided tagXSECURE_AES_KAT_DATA_MISMATCH_ERROR - Error when AES data not matched with expected data
References XSECURE_AES_KAT_BUSY, XSECURE_AES_KAT_DATA_MISMATCH_ERROR, XSECURE_AES_KAT_ENCRYPT_FINAL_FAILED_ERROR, XSECURE_AES_KAT_ENCRYPT_INIT_FAILED_ERROR, XSECURE_AES_KAT_ENCRYPT_UPDATE_FAILED_ERROR, XSECURE_AES_KAT_UPDATE_AAD_FAILED_ERROR, XSECURE_AES_KAT_WRITE_KEY_FAILED_ERROR, XSECURE_AES_STATE_MISMATCH_ERROR, XSECURE_AES_USER_KEY_7, XSecure_AesEncryptFinal, XSecure_AesEncryptInit, XSecure_AesEncryptUpdate, XSECURE_AESKAT_INVALID_PARAM, XSecure_AesKeyZero, XSecure_AesUpdateAad, XSecure_AesWriteKey, XSecure_ConfigureDmaByteSwap, XSECURE_ENABLE_BYTE_SWAP, XSecure_GetKatMessage, XSECURE_KAT_AAD_SIZE_IN_BYTES, XSECURE_KAT_GCM_TAG_MISMATCH_ERROR, XSECURE_KAT_MSG_LEN_IN_BYTES, XSECURE_KAT_MSG_LEN_IN_WORDS.
int XSecure_Sha3Kat(XSecure_Sha3 *SecureSha3)
This function performs known answer test(KAT) on SHA crypto engine.
SecureSha3 Pointer to the XSecure_Sha3 instance XST_SUCCESS - When KAT PassXSECURE_SHA3_INVALID_PARAM - On invalid argumentXSECURE_SHA3_KAT_BUSY - Error when SHA3 is busyXSECURE_SHA3_LAST_UPDATE_ERROR - Error when SHA3 last update failsXSECURE_SHA3_KAT_FAILED_ERROR - Error when SHA3 hash not matched with expected hashXSECURE_SHA3_PMC_DMA_UPDATE_ERROR - Error when DMA driver fails to update the data to SHA3XSECURE_SHA3_FINISH_ERROR - Error when SHA3 finish fails
References XSECURE_KAT_MSG_LEN_IN_BYTES, XSecure_SetReset, XSECURE_SHA3_384, XSECURE_SHA3_FINISH_ERROR, XSECURE_SHA3_INVALID_PARAM, XSECURE_SHA3_KAT_BUSY, XSECURE_SHA3_KAT_FAILED_ERROR, XSECURE_SHA3_PMC_DMA_UPDATE_ERROR, XSECURE_SHA3_RESET_OFFSET, XSecure_ShaFinish, XSecure_ShaLastUpdate, XSecure_ShaStart, XSecure_ShaUpdate.
int XSecure_RsaPublicEncryptKat(void)
This function performs KAT on RSA core.
XST_SUCCESS - On successXSECURE_RSA_KAT_INIT_ERROR - Error when RSA init failsXSECURE_RSA_KAT_ENCRYPT_FAILED_ERROR - When RSA KAT failsXSECURE_RSA_KAT_ENCRYPT_DATA_MISMATCH_ERROR - Error when RSA data not matched with expected data
References XSECURE_KAT_RSA_PUB_EXP, XSECURE_RSA_2048_KEY_SIZE, XSECURE_RSA_2048_SIZE_WORDS, XSECURE_RSA_KAT_ENCRYPT_DATA_MISMATCH_ERROR, XSECURE_RSA_KAT_ENCRYPT_FAILED_ERROR, XSECURE_RSA_KAT_INIT_ERROR, XSecure_RsaInitialize, XSecure_RsaPublicEncrypt.
int XSecure_EllipticVerifySignKat(XSecure_EllipticCrvClass CrvClass)
This function performs ECC sign verify known answer test(KAT) on ECC core.
CrvClass Type of ECC curve class either prime or binary curve XST_SUCCESS - On successXSECURE_ELLIPTIC_KAT_KEY_NOTVALID_ERROR - When elliptic key is invalidXSECURE_ELLIPTIC_KAT_INVLD_CRV_ERROR - Error when input is invalidXSECURE_ELLIPTIC_KAT_SIGN_VERIFY_ERROR - When signature is invalid
References XSecure_EllipticKey::Qx, XSecure_EllipticKey::Qy, XSecure_EllipticSign::SignR, XSecure_EllipticSign::SignS, XSECURE_ECC_NIST_P384, XSECURE_ELLIPTIC_KAT_INVLD_CRV_ERROR, XSECURE_ELLIPTIC_KAT_KEY_NOTVALID_ERROR, XSECURE_ELLIPTIC_KAT_SIGN_VERIFY_ERROR, XSecure_EllipticValidateKey, XSecure_EllipticVerifySign, XSecure_GetKatEccExpSign, XSecure_GetKatEccPublicKey.
int XSecure_EllipticSignGenerateKat(XSecure_EllipticCrvClass CrvClass)
This function performs ECC sign generate known answer test(KAT) on ECC core.
CrvClass Type of ECC curve class either prime or binary class XST_SUCCESS - When KAT passesXSECURE_ELLIPTIC_KAT_INVLD_CRV_ERROR - When input is invalid.XSECURE_ELLIPTIC_KAT_GENERATE_SIGN_ERROR - When generate sign failsXSECURE_ELLIPTIC_KAT_GENERATE_SIGNR_ERROR - When SignR is mismatched
References XSecure_EllipticSign::SignR, XSecure_EllipticSign::SignS, XSECURE_ECC_NIST_P384, XSECURE_ECC_P384_SIZE_IN_BYTES, XSECURE_ELLIPTIC_KAT_GENERATE_SIGN_ERROR, XSECURE_ELLIPTIC_KAT_GENERATE_SIGNR_ERROR, XSECURE_ELLIPTIC_KAT_INVLD_CRV_ERROR, XSecure_EllipticGenerateSignature, XSecure_GetKatEccEphemeralKey, XSecure_GetKatEccExpSign, XSecure_GetKatEccPrivateKey.
int XSecure_EllipticPwct(XSecure_EllipticCrvTyp Curvetype, u64 DAddr, XSecure_EllipticKeyAddr *PubKeyAddr)
This function performs ECC pairwise consistency test on ECC core.
Curvetype Type of ECC curve used for authentication DAddr Address of ECC private key PubKeyAddr Address of ECC public key XST_SUCCESS - When KAT passesXSECURE_ELLIPTIC_KAT_INVLD_CRV_ERROR - When input is invalidXSECURE_ELLIPTIC_KAT_GENERATE_SIGN_64BIT_ERROR - When generate signature failsXSECURE_ELLIPTIC_KAT_64BIT_SIGN_VERIFY_ERROR - When verify sign is invalid
References XSecure_EllipticHashData::Addr, XSecure_EllipticHashData::Len, XSecure_EllipticSignAddr::SignR, XSecure_EllipticSignAddr::SignS, XSECURE_ECC_NIST_P192, XSECURE_ECC_NIST_P224, XSECURE_ECC_NIST_P256, XSECURE_ECC_NIST_P384, XSECURE_ECC_NIST_P521, XSECURE_ECC_P192_SIZE_IN_BYTES, XSECURE_ECC_P224_SIZE_IN_BYTES, XSECURE_ECC_P256_SIZE_IN_BYTES, XSECURE_ECC_P384_SIZE_IN_BYTES, XSECURE_ECC_P521_SIZE_IN_BYTES, XSECURE_ELLIPTIC_KAT_64BIT_SIGN_VERIFY_ERROR, XSECURE_ELLIPTIC_KAT_GENERATE_SIGN_64BIT_ERROR, XSECURE_ELLIPTIC_KAT_INVLD_CRV_ERROR, XSecure_EllipticGenerateSignature_64Bit, XSecure_EllipticVerifySign_64Bit, XSecure_GetKatEccEphemeralKey.
static int XSecure_AesDecKat(void)
This function handler calls XSecure_AesDecryptKat server API and updates KAT status to XPLMI_RTCFG_PLM_KAT_ADDR address.
XST_SUCCESS - If the KAT is successfulXSECURE_AES_KAT_BUSY - If AES is busyXST_FAILURE - If there is a failure
static int XSecure_AesDecCmKat(void)
This function handler calls XSecure_AesDecryptCmKat server API and updates KAT status to XPLMI_RTCFG_PLM_KAT_ADDR address.
XST_SUCCESS - If the KAT is successfulXSECURE_AES_KAT_BUSY - If AES is busyXST_FAILURE - If there is a failure
static int XSecure_AesEncKat(void)
This function handler calls XSecure_AesEncryptKat server API and updates KAT status to XPLMI_RTCFG_PLM_KAT_ADDR address.
XST_SUCCESS - If the KAT is successfulXSECURE_AES_KAT_BUSY - If AES is busyXST_FAILURE - If there is a failure
static int XSecure_RsaPubEncKat(void)
This function handler calls XSecure_RsaPublicEncryptKat server API and updates KAT status to XPLMI_RTCFG_PLM_KAT_ADDR address.
XST_SUCCESS - If the Rsa Kat is successfulXST_FAILURE - If there is a failure
static int XSecure_RsaPrivateDecKat(void)
This function handler calls XSecure_RsaPrivateDecryptKat server API and updates KAT status to XPLMI_RTCFG_PLM_KAT_ADDR address.
XST_SUCCESS - If the Rsa Kat is successfulXST_FAILURE - If there is a failure
static int XSecure_EllipticSignGenKat(XSecure_EccCrvClass CurveClass)
This function handler calls XSecure_EllipticSignGenerateKat server API and updates KAT status to XPLMI_RTCFG_PLM_KAT_ADDR address.
CurveClass Is a class of elliptic curve XST_SUCCESS - If the elliptic KAT is successfulXST_FAILURE - If there is a failure
static int XSecure_EllipticSignVerifyKat(XSecure_EccCrvClass CurveClass)
This function handler calls XSecure_EllipticSignVerifyKat server API and updates KAT status to XPLMI_RTCFG_PLM_KAT_ADDR address.
CurveClass Is a class of elliptic curve XST_SUCCESS - If the elliptic KAT is successfulXST_FAILURE - If there is a failure
static int XSecure_ShaKat(void)
This function handler calls XSecure_ShaKat server API and and updates KAT status to XPLMI_RTCFG_PLM_KAT_ADDR address.
XST_SUCCESS - If the sha update/fnish is successfulXSECURE_SHA3_KAT_BUSY - If SHA3 is busyXST_FAILURE - If there is a failure
int XSecure_KatIpiHandler(XPlmi_Cmd *Cmd)
This function calls respective IPI handler based on the API_ID.
Cmd is a pointer to the command structure XST_SUCCESS - If the handler execution is successfulXST_INVALID_PARAM - If Cmd is NULL or invalid API ID is received.XST_FAILURE - If there is a failure
References XSECURE_API, XSECURE_API_AES_DECRYPT_CM_KAT, XSECURE_API_AES_DECRYPT_KAT, XSECURE_API_AES_ENCRYPT_KAT, XSECURE_API_ELLIPTIC_SIGN_GEN_KAT, XSECURE_API_ELLIPTIC_SIGN_VERIFY_KAT, XSECURE_API_ID_MASK, XSECURE_API_RSA_PRIVATE_DEC_KAT, XSECURE_API_RSA_PUB_ENC_KAT, XSECURE_API_SHA3_KAT, XSECURE_DEBUG_GENERAL, XSecure_EllipticSignGenKat, XSecure_EllipticSignVerifyKat, XSecure_GetAesInstance, XSecure_GetSha3Instance, XSecure_IpiEventHandling, XSecure_MakeResFree, XSecure_Printf, XSecure_RsaPrivateDecKat, XSECURE_SHA_0_DEVICE_ID, XSECURE_SHA_INITIALIZED.
Referenced by XSecure_KatPlatIpiHandler.
int XSecure_RsaPrivateDecryptKat(void)
This function performs private decrypt KAT on RSA core.
XST_SUCCESS On successXSECURE_RSA_KAT_INIT_ERROR When RSA initialization failsXSECURE_RSA_KAT_DECRYPT_FAILED_ERROR When RSA KAT failsXSECURE_RSA_KAT_DECRYPT_DATA_MISMATCH_ERROR Error when RSA data not matched with expected data XST_SUCCESS - On successXSECURE_RSA_KAT_DECRYPT_DATA_MISMATCH_ERROR - Error when RSA data not matched with expected dataXST_FAILURE - On failure XST_SUCCESS On success.XSECURE_RSA_KAT_INIT_ERROR When RSA initialization fails.XSECURE_RSA_KAT_DECRYPT_FAILED_ERROR When RSA KAT fails.XSECURE_RSA_KAT_DECRYPT_DATA_MISMATCH_ERROR Error when RSA data not matched with expected data. XST_SUCCESS On success.XSECURE_RSA_KAT_DECRYPT_DATA_MISMATCH_ERROR Error when RSA data not matched with expected data.XST_FAILURE On failure. XST_SUCCESS On successXSECURE_RSA_KAT_DECRYPT_DATA_MISMATCH_ERROR Error when RSA data not matched with expected dataXST_FAILURE On failure
References XSecure_GetKatRsaCtData, XSecure_GetKatRsaData, XSecure_GetKatRsaModExt, XSecure_GetKatRsaModulus, XSecure_GetKatRsaPrivateExp, XSECURE_RSA_2048_KEY_SIZE, XSECURE_RSA_2048_SIZE_WORDS, XSECURE_RSA_KAT_DECRYPT_DATA_MISMATCH_ERROR, XSECURE_RSA_KAT_DECRYPT_FAILED_ERROR, XSECURE_RSA_KAT_ENCRYPT_DATA_MISMATCH_ERROR, XSECURE_RSA_KAT_INIT_ERROR, XSecure_RsaInitialize, XSecure_RsaPrivateDecrypt.
int XSecure_HmacKat(XSecure_Sha *SecureSha3)
This function performs KAT on HMAC (SHA3-384).
SecureSha3 Pointer to SHA3 instance XST_SUCCESS - On successXSECURE_HMAC_KAT_INIT_ERROR - If HMAC init failsXSECURE_HMAC_KAT_UPDATE_ERROR - If HMAC update failsXSECURE_HMAC_KAT_FINAL_ERROR - If HMAC final failsXSECURE_HMAC_KAT_ERROR - If HMAC KAT fails SecureSha3 Pointer to SHA3 instance XST_SUCCESS On successXSECURE_HMAC_KAT_INIT_ERROR If HMAC init failsXSECURE_HMAC_KAT_UPDATE_ERROR If HMAC update failsXSECURE_HMAC_KAT_FINAL_ERROR If HMAC final failsXSECURE_HMAC_KAT_ERROR If HMAC KAT fails SecureSha Pointer to SHA3 instance. XST_SUCCESS On success.XSECURE_HMAC_KAT_INIT_ERROR If HMAC init fails.XSECURE_HMAC_KAT_UPDATE_ERROR If HMAC update fails.XSECURE_HMAC_KAT_FINAL_ERROR If HMAC final fails.XSECURE_HMAC_KAT_ERROR If HMAC KAT fails.
References XSecure_GetKatAesKey, XSecure_GetKatMessage, XSECURE_HMAC_KAT_ERROR, XSECURE_HMAC_KAT_FINAL_ERROR, XSECURE_HMAC_KAT_INIT_ERROR, XSECURE_HMAC_KAT_UPDATE_ERROR, XSecure_HmacFinal, XSecure_HmacInit, XSecure_HmacUpdate, XSECURE_KAT_KEY_SIZE_IN_BYTES, XSECURE_KAT_MSG_LEN_IN_BYTES.
int XSecure_Sha2256Kat(XSecure_Sha *SecureSha2)
This function performs known answer test(KAT) on SHA-2 crypto engine.
SecureSha2 Pointer to the XSecure_Sha instance XST_SUCCESS On success.XST_FAILURE On KAT failure. SecureSha2 Pointer to the XSecure_Sha instance. XST_SUCCESS On success.XST_FAILURE On KAT failure.
References XSecure_SetReset, XSECURE_SHA2_256_HASH_LEN, XSECURE_SHA_RESET_OFFSET, XSecure_ShaDigest.
int XSecure_ShakeKat(XSecure_Sha *SecureShake)
This function performs known answer test(KAT) on SHAKE crypto engine.
SecureShake Pointer to the XSecure_Sha instance XST_SUCCESS - On success.XST_FAILURE - On KAT failure. SecureShake Pointer to the XSecure_Sha instance. XST_SUCCESS On success.XST_FAILURE On KAT failure.
References XSecure_SetReset, XSECURE_SHA_RESET_OFFSET, XSecure_ShaFinish, XSECURE_SHAKE_256, XSECURE_SHAKE_256_HASH_LEN, XSecure_ShaLastUpdate, XSecure_ShaStart, XSecure_ShaUpdate.
int XSecure_HssSha2256Kat(XSecure_Sha *ShaInstPtr, XPmcDma *DmaPtr)
This function performs KAT on HSS SHA2 256.
ShaInstPtr Pointer to the XSecure_Sha instance DmaPtr Pointer to the XPmcDma instance XST_SUCCESS - If HSS SHA2 256 KAT is passed.XSECURE_HSS_SHA2_256_KAT_ERROR - HSS SHA2-256 KAT error ShaInstPtr Pointer to the XSecure_Sha instance. DmaPtr Pointer to the XPmcDma instance. XST_SUCCESS If HSS SHA2 256 KAT is passed.XSECURE_HSS_SHA2_256_KAT_ERROR HSS SHA2-256 KAT error.
References XSecure_HssInitParams::PublicKey, XSecure_HssInitParams::PublicKeyLen, XSecure_HssInitParams::SignatureLen, XSecure_HssInitParams::SignBuff, XSECURE_HSS_PUBLIC_KEY_TOTAL_SIZE, XSECURE_HSS_SHA2_256_KAT_ERROR, XSECURE_HSS_SIGNATURE_SIZE_BYTES, XSecure_HssFinish, XSecure_HssInit, XSECURE_LMS_DATA_SIZE_BYTES, XSecure_LmsHashMessage.
int XSecure_HssShake256Kat(XSecure_Sha *ShaInstPtr, XPmcDma *DmaPtr)
This function performs KAT on HSS SHAKE 256.
ShaInstPtr Pointer to the XSecure_Sha instance DmaPtr Pointer to the XPmcDma instance XST_SUCCESS - If HSS SHAKE256 KAT is passed.XSECURE_HSS_SHAKE_256_KAT_ERROR - HSS SHAKE 256 KAT error ShaInstPtr Pointer to the XSecure_Sha instance. DmaPtr Pointer to the XPmcDma instance. XST_SUCCESS If HSS SHAKE256 KAT is passed.XSECURE_HSS_SHAKE_256_KAT_ERROR HSS SHAKE 256 KAT error.
References XSecure_HssInitParams::PublicKey, XSecure_HssInitParams::PublicKeyLen, XSecure_HssInitParams::SignatureLen, XSecure_HssInitParams::SignBuff, XSECURE_HSS_PUBLIC_KEY_TOTAL_SIZE, XSECURE_HSS_SHAKE_256_KAT_ERROR, XSECURE_HSS_SIGNATURE_SIZE_BYTES, XSecure_HssFinish, XSecure_HssInit, XSECURE_LMS_DATA_SIZE_BYTES, XSecure_LmsHashMessage, XSECURE_SHAKE_256.
int XSecure_LmsSha2256Kat(XSecure_Sha *ShaInstPtr, XPmcDma *DmaPtr)
This function performs KAT on LMS - SHA2 256.
ShaInstPtr Pointer to the XSecure_Sha instance DmaPtr Pointer to the XPmcDma instance XST_SUCCESS - If LMS SHA2 256 KAT is passed. ShaInstPtr Pointer to the XSecure_Sha instance. DmaPtr Pointer to the XPmcDma instance. XST_SUCCESS If LMS SHA2 256 KAT is passed.ErrorCode Upon failure.
References XSecure_LmsSignVerifyParams::Data, XSecure_LmsSignVerifyParams::DataLen, XSecure_LmsSignVerifyParams::ExpectedPubKey, XSecure_LmsSignVerifyParams::LmsSign, XSecure_LmsSignVerifyParams::LmsSignLen, XSecure_LmsSignVerifyParams::PreHashedMsg, XSecure_LmsSignVerifyParams::PubKeyLen, XSECURE_LMS_DATA_SIZE_BYTES, XSECURE_LMS_PUB_KEY_TOTAL_SIZE, XSECURE_LMS_SIGNATURE_SIZE_BYTES, XSecure_LmsSignatureVerification.
int XSecure_LmsShake256Kat(XSecure_Sha *ShaInstPtr, XPmcDma *DmaPtr)
This function performs KAT on LMS SHAKE 256.
ShaInstPtr Pointer to the XSecure_Sha instance DmaPtr Pointer to the XPmcDma instance XST_SUCCESS - If LMS SHAKE256 KAT is passed. ShaInstPtr Pointer to the XSecure_Sha instance. DmaPtr Pointer to the XPmcDma instance. XST_SUCCESS If LMS SHAKE256 KAT is passed.ErrorCode Upon failure.
References XSecure_LmsSignVerifyParams::Data, XSecure_LmsSignVerifyParams::DataLen, XSecure_LmsSignVerifyParams::ExpectedPubKey, XSecure_LmsSignVerifyParams::LmsSign, XSecure_LmsSignVerifyParams::LmsSignLen, XSecure_LmsSignVerifyParams::PreHashedMsg, XSecure_LmsSignVerifyParams::PubKeyLen, XSECURE_LMS_DATA_SIZE_BYTES, XSECURE_LMS_PUB_KEY_TOTAL_SIZE, XSECURE_LMS_SIGNATURE_SIZE_BYTES, XSecure_LmsSignatureVerification.
int XSecure_Sha384Kat(void)
This function performs KAT on SHA-384.
XST_SUCCESS On successXSECURE_SHA384_KAT_ERROR If SHA384 KAT failsXST_FAILURE On failure
References XSecure_GetKatMessage, XSECURE_KAT_MSG_LEN_IN_BYTES, XSECURE_SHA384_KAT_ERROR, XSecure_Sha384Digest.
static int XSecure_TrngKat(void)
This function handler calls XSecure_TrngPreOperationalSelfTests server API and updates KAT status to XPLMI_RTCFG_PLM_KAT_ADDR address.
XST_SUCCESS - If the KAT is successfulXST_FAILURE - If there is a failure
static int XSecure_Sha2Kat(void)
This function handler calls XSecure_Sha2256Kat server API and and updates KAT status to XPLMI_RTCFG_PLM_KAT_ADDR address.
XST_SUCCESS - If the SHA2 KAT is successfulXST_FAILURE - If there is a failure
int XSecure_KatPlatIpiHandler(XPlmi_Cmd *Cmd)
This function calls respective IPI handler based on the API_ID.
Cmd is a pointer to the command structure XST_SUCCESS - If the handler execution is successfulXST_INVALID_PARAM - If any input parameter is invalidXST_FAILURE - If there is a failure Cmd Pointer to the command structure. XST_SUCCESS If the handler execution is successful.XST_INVALID_PARAM If any input parameter is invalid.XST_FAILURE If there is a failure. Cmd is a pointer to the command structure. XST_SUCCESS If the handler execution is successful.XST_INVALID_PARAM If any input parameter is invalid.XST_FAILURE If there is a failure. Cmd is a pointer to the command structure XST_SUCCESS If the handler execution is successfulXST_INVALID_PARAM If any input parameter is invalidXST_FAILURE If there is a failure
References XSECURE_API, XSECURE_API_ID_MASK, XSECURE_API_SHA2_KAT, XSECURE_API_TRNG_KAT, XSecure_GetSha2Instance, XSecure_IpiEventHandling, XSecure_KatIpiHandler, XSecure_MakeResFree, XSecure_Sha2Kat, XSECURE_SHA_1_DEVICE_ID, XSECURE_SHA_INITIALIZED, XSecure_TrngKat.
int XSecure_RsaPwct(XSecure_RsaPrivKey *PrivKey, XSecure_RsaPubKey *PubKey, void *ShaInstancePtr, XSecure_ShaMode Shatype)
This function performs pairwise consistency test for generated RSA key pair using OAEP encrypt and decrypt operation.
PrivKey Pointer to the XSecure_RsaKey PubKey Pointer to the XSecure_RsaPubKey ShaInstancePtr Pointer to the SHA instance used during OAEP encoding for MGF Shatype is SHA algorithm type used for MGF XST_SUCCESS On SuccessXST_INVALID_PARAM If any input parameter is invalidXSECURE_RSA_PWCT_MEM_CMP_FAILED_ERROR If RSA pwct comparison failsXST_FAILURE On Failure
References XSecure_RsaOaepParam::InputDataAddr, XSecure_RsaOaepParam::InputDataSize, XSecure_RsaPubKey::Mod, XSecure_RsaOaepParam::OutputDataAddr, XSecure_RsaOaepParam::OutputDataSize, XSecure_RsaPubKey::PubExp, XSecure_RsaOaepParam::ShaInstancePtr, XSecure_RsaOaepParam::ShaType, XSecure_GetKatMessage, XSECURE_KAT_MSG_LEN_IN_BYTES, XSECURE_RSA_KEY_GEN_SIZE_IN_BYTES, XSECURE_RSA_PUB_EXP_SIZE, XSECURE_RSA_PWCT_MEM_CMP_FAILED_ERROR, XSecure_RsaInitialize, XSecure_RsaOaepDecrypt, XSecure_RsaOaepEncrypt.
int XSecure_UpdateKatStatusIpiHandler(XPlmi_Cmd *Cmd)
This function calls respective IPI handler based on the API_ID.
Cmd is a pointer to the command structure XST_SUCCESS On SuccessXST_INVALID_PARAM If any input parameter is invalidXST_FAILURE On failure
References XSECURE_API, XSECURE_API_KAT_CLEAR, XSECURE_API_KAT_SET, XSECURE_API_UPDATE_CPM5N_KAT_STATUS, XSECURE_API_UPDATE_DDR_KAT_STATUS, XSECURE_API_UPDATE_HNIC_KAT_STATUS, XSECURE_API_UPDATE_PCIDE_KAT_STATUS, XSECURE_API_UPDATE_PKI_KAT_STATUS, XSECURE_DDR_KAT_MASK_MUL, XSECURE_DDR_MAX_SUPPORT, XSECURE_DEBUG_GENERAL, XSECURE_DEF_KAT_MASK, XSECURE_KAT_HDR_LEN, XSECURE_KAT_MAX_CMD_LEN, XSECURE_MAX_KAT_MASK_LEN, XSecure_Printf.
XSECURE_KAT_MSG_LEN_IN_BYTES
Message length of known answer test in bytes.
Referenced by XSecure_AesDecryptKat, XSecure_AesEncryptKat, XSecure_HmacKat, XSecure_RsaPwct, XSecure_Sha384Kat, XSecure_Sha3Kat.
XSECURE_KAT_AAD_SIZE_IN_BYTES
AAD size of known answer test in bytes.
Referenced by XSecure_AesDecryptKat, XSecure_AesEncryptKat.
XSECURE_KAT_IV_SIZE_IN_BYTES
IV size of known answer test in bytes.
XSECURE_KAT_KEY_SIZE_IN_BYTES
Key size of known answer test in bytes.
Referenced by XSecure_HmacKat.
XSECURE_KAT_MSG_LEN_IN_WORDS
Message length of known answer test in words.
Referenced by XSecure_AesDecryptKat, XSecure_AesEncryptKat.
XSECURE_KAT_RSA_PUB_EXP
RSA public exponent of known answer test.
Referenced by XSecure_RsaPublicEncryptKat.
XSECURE_KAT_ECC_P521_SHA3_HASH_SIZE_IN_BYTES
Hash size of ECC P521 and SHA3 in bytes.
XSECURE_LMS_DATA_SIZE_BYTES
LMS Data Size.
Referenced by XSecure_HssSha2256Kat, XSecure_HssShake256Kat, XSecure_LmsSha2256Kat, XSecure_LmsShake256Kat.
XSECURE_HSS_SIGNATURE_SIZE_BYTES
HSS Signature Size.
Referenced by XSecure_HssSha2256Kat, XSecure_HssShake256Kat.
XSECURE_LMS_SIGNATURE_SIZE_BYTES
LMS Signature Size.
Referenced by XSecure_LmsSha2256Kat, XSecure_LmsShake256Kat.
XSECURE_LMS_DATA_SIZE_BYTES
LMS Data Size.
XSECURE_HSS_SIGNATURE_SIZE_BYTES
HSS Signature Size.
XSECURE_LMS_SIGNATURE_SIZE_BYTES
LMS Signature Size.
XSECURE_KAT_MAX_CMD_LEN
Maximum command length.
Referenced by XSecure_UpdateKatStatusIpiHandler.
XSECURE_DDR_KAT_MASK_MUL
Multiplier to get DDR KAT mask.
Referenced by XSecure_UpdateKatStatusIpiHandler.
XSECURE_DDR_MAX_SUPPORT
Maximum supported DDR.
Referenced by XSecure_UpdateKatStatusIpiHandler.
XSECURE_DEF_KAT_MASK
KAT mask.
Referenced by XSecure_UpdateKatStatusIpiHandler.