xsecure_hmac_apis
static int XSecure_PreProcessKey(XSecure_Hmac *InstancePtr, u64 KeyAddr, u32 KeyLen, u32 KeyOut, u32 KeyOutLen)
This function pre process the key to SHA3 block length and the final key is been stored into the K0 array.
InstancePtr is the pointer to the XSecure_Hmac instance KeyAddr is the variable which holds the address of key for HMAC KeyLen variable holds the length of the key KeyOut is the variable which holds the output key buffer's address KeyOutLen is the variable which specifies the output key length based on SHA mode XST_SUCCESS - If initialization was successful.XST_FAILURE - On failure.
static void XSecure_HmacXor(const u32 *Data, const u8 Value, u32 *Result)
This function performs XOR operation on provided data of SHA3 block length with constant provided on whole bytes of data and result is been updated.
Data is the pointer which holds data to be XORed. Value with which XOR operation to be performed. Result is the pointer of SHA3 block length array which is been updated with the result.
int XSecure_HmacInit(XSecure_Hmac *InstancePtr, XSecure_Sha3 *Sha3InstancePtr, u64 KeyAddr, u32 KeyLen)
This function initializes the HMAC instance.
InstancePtr is the pointer to the XSecure_Hmac instance Sha3InstancePtr is the pointer to the XSecure_Sha3 instance. KeyAddr holds the address of HMAC key. KeyLen variable holds the length of the key. XST_SUCCESS - If initialization was successful.XSECURE_HMAC_INVALID_PARAM - If any input parameter is invalid.XST_FAILURE - On failure.
References K0, XSECURE_HMAC_INVALID_PARAM, XSECURE_HMAC_IPAD_VALUE, XSECURE_HMAC_OPAD_VALUE, XSecure_SetReset, XSECURE_SHA3_384, XSECURE_SHA3_BLOCK_LEN, XSECURE_SHA3_RESET_OFFSET, XSECURE_SHA_UNINITIALIZED, XSecure_ShaStart, XSecure_ShaUpdate.
Referenced by XSecure_Hkdf, XSecure_HmacKat.
int XSecure_HmacUpdate(XSecure_Hmac *InstancePtr, u64 DataAddr, u32 Len)
This function updates the data to be authenticated, which can be called repeatedly with chunks of the message to be authenticated (len bytes at data).
InstancePtr is the pointer to the XSecure_Hmac instance DataAddr holds the address of data to be updated. Len variable holds the length of data. XST_SUCCESS - If initialization was successful.XSECURE_HMAC_INVALID_PARAM - If any input parameter is invalid.XST_FAILURE - On failure.
References XSECURE_HMAC_INVALID_PARAM, XSecure_SetReset, XSECURE_SHA3_BLOCK_LEN, XSECURE_SHA3_RESET_OFFSET, XSecure_ShaUpdate.
Referenced by XSecure_Hkdf, XSecure_HmacKat.
int XSecure_HmacFinal(XSecure_Hmac *InstancePtr, XSecure_HmacRes *Hmac)
This function calculates the final HMAC.
InstancePtr is the pointer to the XSecure_Hmac instance Hmac is the pointer of 48 bits which holds the resultant HMAC. XST_SUCCESS - If initialization was successful.XSECURE_HMAC_INVALID_PARAM - If any input parameter is invalid.XST_FAILURE - On failure. Though HMAC can be truncated, as the truncation of data may lead to security implications, this function always fills the HMAC pointer with 48 bytes of data.
References XSECURE_HMAC_INVALID_PARAM, XSecure_SetReset, XSECURE_SHA3_384, XSECURE_SHA3_BLOCK_LEN, XSECURE_SHA3_RESET_OFFSET, XSecure_ShaFinish, XSecure_ShaStart, XSecure_ShaUpdate.
Referenced by XSecure_Hkdf, XSecure_HmacKat.
XSECURE_HMAC_8BIT_SHIFT
8 Bit shift for HMAC
XSECURE_HMAC_16BIT_SHIFT
16 Bit shift for HMAC
XSECURE_HMAC_24BIT_SHIFT
24 Bit shift for HMAC
XSECURE_HMAC_WORD_LEN
HMAC word length.
XSECURE_HMAC_IPAD_VALUE
HMAC IPAD value.
Referenced by XSecure_HmacInit.
XSECURE_HMAC_OPAD_VALUE
HMAC OPAD value.
Referenced by XSecure_HmacInit.
XSECURE_HMAC_MODULE_MAJOR_VERSION
HMAC module major version.
XSECURE_HMAC_MODULE_MINOR_VERSION
HMAC module minor version.
XSECURE_HMAC_MODULE_MAJOR_VERSION
HMAC module major version.
XSECURE_HMAC_MODULE_MINOR_VERSION
HMAC module minor version.