xsecure_rsa_server_apis
XSECURE_RSA_CONTROL_EXP
Exponentiation Opcode.
Referenced by XSecure_RsaOperation.
XSECURE_RSA_CONTROL_EXP_PRE
Expo.
using R*R mod M
Referenced by XSecure_RsaOperation.
XSECURE_ECDSA_RSA_CFG0_4096_VALUE
CFG0 4096 value.
Referenced by XSecure_RsaOperation.
XSECURE_ECDSA_RSA_CFG1_4096_VALUE
CFG1 4096 value.
Referenced by XSecure_RsaOperation.
XSECURE_ECDSA_RSA_CFG2_4096_VALUE
CFG2 4096 value.
Referenced by XSecure_RsaOperation.
XSECURE_ECDSA_RSA_CFG5_4096_VALUE
CFG3 4096 value.
Referenced by XSecure_RsaOperation.
XSECURE_ECDSA_RSA_CFG0_3072_VALUE
CFG0 3072 value.
Referenced by XSecure_RsaOperation.
XSECURE_ECDSA_RSA_CFG1_3072_VALUE
CFG1 3072 value.
Referenced by XSecure_RsaOperation.
XSECURE_ECDSA_RSA_CFG2_3072_VALUE
CFG2 3072 value.
Referenced by XSecure_RsaOperation.
XSECURE_ECDSA_RSA_CFG5_3072_VALUE
CFG3 3072 value.
Referenced by XSecure_RsaOperation.
XSECURE_ECDSA_RSA_CFG0_2048_VALUE
CFG0 2048 value.
Referenced by XSecure_RsaOperation.
XSECURE_ECDSA_RSA_CFG1_2048_VALUE
CFG1 2048 value.
Referenced by XSecure_RsaOperation.
XSECURE_ECDSA_RSA_CFG2_2048_VALUE
CFG2 2048 value.
Referenced by XSecure_RsaOperation.
XSECURE_ECDSA_RSA_CFG5_2048_VALUE
CFG3 2048 value.
Referenced by XSecure_RsaOperation.
XSECURE_RSA_STATUS_DONE
Operation Done.
Referenced by XSecure_RsaOperation.
XSECURE_RSA_STATUS_ERROR
Error.
Referenced by XSecure_RsaOperation.
XSecure_RsaKeyOpState
Default state.
XSecure_RsaKeyStatus
RSA key is free.
XSecure_RsaState
0x0
XSecure_RsaOps
0x0
typedef RsaKeyPair XSecure_RsaKeyPtr
const u8 XSecure_Silicon2_TPadSha3[][]
static int XSecure_RsaOaepEncode(XSecure_RsaOaepParam *OaepParam, u64 OutputAddr)
This function encodes the given message using PKCS #1 v2.0 RSA Optimal Asymmetric Encryption Padding scheme.
EM = 0x00 || maskedSeed || maskedDB OaepParam is a pointer to the XSecure_RsaOaepParam instance. OutputAddr is address where the encoded data is stored. XST_SUCCESS - On success.XSECURE_RSA_OAEP_INVALID_PARAM - On invalid parameter.XSECURE_RSA_OAEP_INVALID_MSG_LEN - On invalid message length.XST_FAILURE - On failure.
static int XSecure_RsaOaepDecode(XSecure_RsaOaepParam *OaepParam, u64 InputDataAddr)
This function decodes the given message which is encoded with RSA Optimal Asymmetric Encryption Padding scheme i.e.
EM = 0x00 || maskedSeed || maskedDB OaepParam is a pointer to the XSecure_RsaOaepParam instance. InputDataAddr is the address where decrypted output data is stored. XST_SUCCESS - On success.XSECURE_RSA_OAEP_INVALID_PARAM - On invalid parameter.XSECURE_RSA_OAEP_BYTE_MISMATCH_ERROR - If byte mismatch.XSECURE_RSA_OAEP_DATA_CPY_ERROR - If data copy fails.XSECURE_RSA_OAEP_DATA_CMP_ERROR - If data compare fails.XSECURE_RSA_OAEP_DB_MISMATCH_ERROR - If DB ia mismatched.XSECURE_RSA_OAEP_INVALID_MSG_LEN - On invalid message length.XST_FAILURE On failure.
static XSecure_RsaKeyMgmt * XSecure_GetRsaKeyMgmtInstance(void)
This function returns pointer to XSecure_RsaKeyMgmt instance.
RsaKeyMgmt is pointer to the XSecure_RsaKeyMgmt instances.
static int XSecure_GetRsaKeySlotIdx(u32 *RsaKeyIdx, u32 RsaKeyStatus)
This function returns RSA key index based on RsaKeyStatus.
RsaKeyIdx is a pointer to the variable containing RSA free index. RsaKeyStatus Key status to be checked. XST_SUCCESS - On success.XST_FAILURE - On failure.
static XSecure_RsaKeyGenParam * XSecure_GetRsaKeyGenParam(void)
This function returns RSA free key generation param.
Pointer to XSecure_RsaKeyGenParam or NULL otherwise.
static int XSecure_RsaKeyGenInit(XSecure_RsaKeyGenParam *RsaParam, XSecure_RsaKeyPtr *KeyPairState, u32 RsaKeyLen)
This function performs the RSA key initialization.
RsaParam is the pointer to XSecure_RsaKeyGenParam. KeyPairState is the pointer to XSecure_RsaKeyPtr which holds the state of key that needs to be generated. RsaKeyLen Length of RSA key length in bytes. XST_SUCCESS - On success.XSECURE_RSA_INVALID_PARAM - If input parameter is invalid.XST_FAILURE - On failure.
static int XSecure_RsaKeyGenerate(XSecure_RsaKeyPtr *KeyPairState, u32 QuantSize)
This function performs the RSA key generation in steps.
KeyPairState is a pointer to the XSecure_RsaKeyPtr. QuantSize Size of the key generation steps in terms of quant size i.e. Half-size RSA key. XST_SUCCESS - On success.XSECURE_RSA_INVALID_PARAM - If input parameter is invalid.XST_FAILURE - On failure.
static int XSecure_RemoveRsaKeyPairGenerationFromScheduler(void)
This function removes key pair generation task from scheduler.
XST_SUCCESS - On success.XSECURE_ERR_REMOVE_TASK_SCHEDULER - If failed to remove task from scheduler.
static int XSecure_GenerateRsaKeyPair(void *arg)
This function performs the RSA key generation.
XST_SUCCESS - On success.XSECURE_ERR_RSA_KEY_PAIR_GEN_SCHEDULER - If RSA key pair generation fails.XST_FAILURE - On failure.
int XSecure_RsaOaepEncrypt(XSecure_Rsa *InstancePtr, XSecure_RsaOaepParam *OaepParam)
This function encodes the given message using RSA OAEP and encrypts it.
InstancePtr is a pointer to the XSecure_Rsa instance. OaepParam is a pointer to the XSecure_RsaOaepParam instance. XST_SUCCESS - On success.XSECURE_RSA_OAEP_INVALID_PARAM - On invalid parameter.XST_FAILURE - On failure.
References XSecure_RsaOaepParam::OutputDataAddr, XSECURE_RSA_KEY_GEN_SIZE_IN_BYTES, XSECURE_RSA_OAEP_INVALID_PARAM, XSecure_RsaPublicEncrypt_64Bit.
Referenced by XSecure_RsaPwct.
int XSecure_RsaOaepDecrypt(XSecure_RsaPrivKey *PrivKey, XSecure_RsaOaepParam *OaepParam)
This function decodes the given message and decrypts it using RSA OAEP.
PrivKey is a pointer to the XSecure_RsaPrivKey instance. OaepParam is a pointer to the XSecure_RsaOaepParam instance. XST_SUCCESS - On success.XSECURE_RSA_OAEP_INVALID_PARAM - On invalid parameter.XST_FAILURE - On failure.
References XSecure_RsaPrivKey::DP, XSecure_RsaPrivKey::DQ, XSecure_RsaOaepParam::InputDataAddr, XSecure_RsaPrivKey::Mod, XSecure_RsaPrivKey::P, XSecure_RsaPrivKey::Q, XSecure_RsaPrivKey::QInv, XSECURE_BYTE_IN_BITS, XSECURE_RSA_KEY_GEN_SIZE_IN_BYTES, XSECURE_RSA_OAEP_INVALID_PARAM, XSecure_RsaExpCRT.
Referenced by XSecure_KeyUnwrap, XSecure_RsaPwct.
int XSecure_AddRsaKeyPairGenerationToScheduler(void)
This function adds periodic task of generation RSA key pair to scheduler.
XST_SUCCESS - On success.XSECURE_ERR_ADD_TASK_SCHEDULER - If failed to add task to scheduler.
References XSECURE_DEBUG_GENERAL, XSECURE_KEY_PAIR_GEN_POLL_INTERVAL, XSecure_Printf.
Referenced by XSecure_Init, XSecure_RsaDestroyKeyInUse.
u32 XSecure_GetRsaKeyInUseIdx(void)
This function returns RSA key inuse index.
API to destroy key pair that is in use. KeyInUse To indicate the key that is in use
References XSecure_RsaKeyMgmt::KeyInUse, XSECURE_RSA_KEY_AVAIL.
Referenced by XSecure_KeyUnwrap.
int XSecure_RsaDestroyKeyInUse(void)
This function destroys the RSA key in use.
API to add key pair generation to scheduler. XST_SUCCESS - On success.XST_FAILURE - On failure.
References XSecure_RsaKeyGenParam::IsRsaKeyAvail, XSecure_RsaKeyMgmt::Key, XSecure_RsaKeyMgmt::KeyInUse, XSecure_RsaKeyGenParam::KeyPair, XSecure_RsaKeyPair::PrivKey, XSecure_RsaKeyPair::PubKey, XSecure_AddRsaKeyPairGenerationToScheduler, XSECURE_RSA_KEY_AVAIL, XSECURE_RSA_MAX_KEY_GEN_SUPPORT, XSECURE_RTCA_RSA_KEY_STATUS_MASK, XSECURE_RTCA_RSA_KEY_STATUS_REG, XSECURE_ZERO.
XSecure_RsaPrivKey * XSecure_GetRsaPrivateKey(u32 RsaIdx)
This function returns RSA private key.
RsaIdx Index of the RSA key to retrieve. Pointer to XSecure_RsaPrivKey or NULL otherwise.
References XSECURE_RSA_MAX_KEY_GEN_SUPPORT.
Referenced by XSecure_KeyUnwrap.
XSecure_RsaPubKey * XSecure_GetRsaPublicKey(u32 RsaIdx)
This function returns RSA public key.
API to retrieve RSA KEY in use index. Pointer to XSecure_RsaPubKey or NULL otherwise.
References XSECURE_RSA_MAX_KEY_GEN_SUPPORT.
int XSecure_RsaInitialize_64Bit(XSecure_Rsa *InstancePtr, u64 Mod, u64 ModExt, u64 ModExpo)
This function initializes a a XSecure_Rsa structure with the default values located at a 64-bit address required for operating the RSA cryptographic engine.
InstancePtr Pointer to the XSecure_Rsa instance Mod Address of the key Modulus of key size ModExt Address of the pre-calculated exponential (R^2 Mod N) value, or 0 if user doesn't have pre-calculated R^2 Mod N value (control will take care of this calculation internally) ModExpo Address of the buffer which contains key exponent XST_SUCCESS - If initialization was successfulXSECURE_RSA_INVALID_PARAM - On invalid arguments Modulus, ModExt and ModExpo are part of partition signature when authenticated boot image is generated by bootgen, else the all of them should be extracted from the key
References XSecure_Rsa::Mod, XSecure_Rsa::ModAddr, XSecure_Rsa::ModExpo, XSecure_Rsa::ModExpoAddr, XSecure_Rsa::ModExt, XSecure_Rsa::ModExtAddr, XSecure_Rsa::RsaState, XSecure_Rsa::SizeInWords, XSECURE_RSA_4096_SIZE_WORDS, XSECURE_RSA_INITIALIZED, XSECURE_RSA_INVALID_PARAM, XSecure_RsaCfgInitialize.
Referenced by XSecure_RsaInitialize.
int XSecure_RsaInitialize(XSecure_Rsa *InstancePtr, u8 *Mod, u8 *ModExt, u8 *ModExpo)
This function initializes a a XSecure_Rsa structure with the default values required for operating the RSA cryptographic engine.
InstancePtr Pointer to the XSecure_Rsa instance Mod A character Pointer which contains the key Modulus of key size ModExt A Pointer to the pre-calculated exponential (R^2 Mod N) value, or NULL if user doesn't have pre-calculated R^2 Mod N value (control will take care of this calculation internally) ModExpo Pointer to the buffer which contains key exponent XST_SUCCESS - If initialization was successfulXSECURE_RSA_INVALID_PARAM - On invalid arguments Modulus, ModExt and ModExpo are part of partition signature when authenticated boot image is generated by bootgen, else the all of them should be extracted from the key
References XSecure_RsaInitialize_64Bit.
Referenced by XSecure_DataAuth, XSecure_RsaCore, XSecure_RsaPrivateDecryptKat, XSecure_RsaPublicEncryptKat, XSecure_RsaPwct, XSecure_SpkAuthentication.
int XSecure_RsaSignVerification_64Bit(const u64 Signature, const u64 Hash, u32 HashLen)
This function verifies the RSA decrypted data located at a 64-bit address provided is either matching with the provided expected hash by taking care of PKCS padding.
Signature Address of the buffer which holds the decrypted RSA signature Hash Address of the buffer which has the hash calculated on the data to be authenticated HashLen Length of Hash used For SHA3 it should be 48 bytes XST_SUCCESS - If decryption was successfulXSECURE_RSA_INVALID_PARAM - On invalid argumentsXST_FAILURE In case of mismatch Signature Address of the buffer which holds the decrypted RSA signature Hash Address of the buffer which has the hash calculated on the data to be authenticated HashLen Length of Hash used For SHA3 it should be 48 bytes XST_SUCCESS - If decryption was successfulXSECURE_RSA_INVALID_PARAM - On invalid argumentsXST_FAILURE - In case of mismatch
References XSECURE_FSBL_SIG_SIZE, XSECURE_HASH_TYPE_SHA3, XSECURE_RSA_BYTE_PAD1, XSECURE_RSA_BYTE_PAD2, XSECURE_RSA_BYTE_PAD3, XSECURE_RSA_BYTE_PAD_LENGTH, XSECURE_RSA_INVALID_PARAM, XSECURE_RSA_T_PAD_LENGTH, XSecure_RsaGetTPadding.
Referenced by XSecure_RsaSignVerification.
int XSecure_RsaSignVerification(const u8 *Signature, const u8 *Hash, u32 HashLen)
This function verifies the RSA decrypted data provided is either matching with the provided expected hash by taking care of PKCS padding.
Signature Pointer to the buffer which holds the decrypted RSA signature Hash Pointer to the buffer which has the hash calculated on the data to be authenticated HashLen Length of Hash used For SHA3 it should be 48 bytes XST_SUCCESS - If decryption was successfulXSECURE_RSA_INVALID_PARAM - On invalid argumentsXST_FAILURE In case of mismatch Signature Pointer to the buffer which holds the decrypted RSA signature Hash Pointer to the buffer which has the hash calculated on the data to be authenticated HashLen Length of Hash used For SHA3 it should be 48 bytes XST_SUCCESS - If decryption was successfulXSECURE_RSA_INVALID_PARAM - On invalid argumentsXST_FAILURE - In case of mismatch
References XSecure_RsaSignVerification_64Bit.
int XSecure_RsaPublicEncrypt_64Bit(XSecure_Rsa *InstancePtr, u64 Input, u32 Size, u64 Result)
This function handles the RSA encryption for data available at 64-bit address with the public key components provided when initializing the RSA cryptographic core with the XSecure_RsaInitialize function.
InstancePtr Pointer to the XSecure_Rsa instance Input Address of the buffer which contains the input data to be encrypted Size Key size in bytes, Input size also should be same as Key size mentioned. Inputs supported are XSECURE_RSA_4096_KEY_SIZE, XSECURE_RSA_2048_KEY_SIZE, or XSECURE_RSA_3072_KEY_SIZE Result Address of buffer where resultant decrypted data to be stored XST_SUCCESS - If encryption was successfulXSECURE_RSA_INVALID_PARAM - On invalid argumentsXSECURE_RSA_STATE_MISMATCH_ERROR - If State mismatch is occurred The Size passed here needs to match the key size used in the XSecure_RsaInitialize function
References XSecure_Rsa::RsaState, XSECURE_RSA_INITIALIZED, XSECURE_RSA_INVALID_PARAM, XSECURE_RSA_SIGN_ENC, XSECURE_RSA_STATE_MISMATCH_ERROR, XSecure_RsaOperation.
Referenced by XSecure_RsaOaepEncrypt, XSecure_RsaPublicEncrypt.
int XSecure_RsaPublicEncrypt(XSecure_Rsa *InstancePtr, u8 *Input, u32 Size, u8 *Result)
This function handles the RSA encryption with the public key components provided when initializing the RSA cryptographic core with the XSecure_RsaInitialize function.
InstancePtr Pointer to the XSecure_Rsa instance Input Pointer to the buffer which contains the input data to be encrypted Size Key size in bytes, Input size also should be same as Key size mentioned. Inputs supported are XSECURE_RSA_4096_KEY_SIZE, XSECURE_RSA_2048_KEY_SIZE, or XSECURE_RSA_3072_KEY_SIZE Result Pointer to the buffer where resultant decrypted data to be stored XST_SUCCESS - If encryption was successfulXSECURE_RSA_INVALID_PARAM - On invalid argumentsXSECURE_RSA_STATE_MISMATCH_ERROR - If State mismatch is occurred The Size passed here needs to match the key size used in the XSecure_RsaInitialize function InstancePtr Pointer to the XSecure_Rsa instance Input Pointer to the buffer which contains the input data to be encrypted Size Key size in bytes, Input size also should be same as Key size mentioned. Inputs supported are XSECURE_RSA_4096_KEY_SIZEXSECURE_RSA_2048_KEY_SIZEXSECURE_RSA_3072_KEY_SIZE Result Pointer to the buffer where resultant decrypted data to be stored XST_SUCCESS - If encryption was successfulXSECURE_RSA_INVALID_PARAM - On invalid argumentsXSECURE_RSA_STATE_MISMATCH_ERROR - If State mismatch is occurred The Size passed here needs to match the key size used in the XSecure_RsaInitialize function
References XSecure_RsaPublicEncrypt_64Bit.
int XSecure_RsaPrivateDecrypt_64Bit(XSecure_Rsa *InstancePtr, u64 Input, u32 Size, u64 Result)
This function handles the RSA decryption for data available at 64-bit address with the private key components provided when initializing the RSA cryptographic core with the XSecure_RsaInitialize function.
InstancePtr Pointer to the XSecure_Rsa instance Input Address of the buffer which contains the input data to be decrypted Size Key size in bytes, Input size also should be same as Key size mentioned. Inputs supported are XSECURE_RSA_4096_KEY_SIZE, XSECURE_RSA_2048_KEY_SIZE, or XSECURE_RSA_3072_KEY_SIZE Result Address of buffer where resultant decrypted data to be stored XST_SUCCESS - If decryption was successfulXSECURE_RSA_INVALID_PARAM - On invalid parametersXSECURE_RSA_DATA_VALUE_ERROR - If input data is greater than modulusXSECURE_RSA_STATE_MISMATCH_ERROR - If State mismatch is occurredXST_FAILURE - On RSA operation failure RSA private key decryption data should be less than modulus. InstancePtr Pointer to the XSecure_Rsa instance Input Address of the buffer which contains the input data to be decrypted Size Key size in bytes, Input size also should be same as Key size mentioned. Inputs supported are XSECURE_RSA_4096_KEY_SIZE, XSECURE_RSA_2048_KEY_SIZE, or XSECURE_RSA_3072_KEY_SIZE Result Address of buffer where resultant decrypted data to be stored XST_SUCCESS - If decryption was successfulXSECURE_RSA_DATA_VALUE_ERROR - If input data is greater than modulusXSECURE_RSA_STATE_MISMATCH_ERROR - If State mismatch is occurredXST_FAILURE - On RSA operation failure The Size passed here needs to match the key size used in the XSecure_RsaInitialize functionRSA private key decryption data should be lesser than modulus.
References XSecure_Rsa::Mod, XSecure_Rsa::ModAddr, XSecure_Rsa::RsaState, XSECURE_RSA_DATA_VALUE_ERROR, XSECURE_RSA_INITIALIZED, XSECURE_RSA_INVALID_PARAM, XSECURE_RSA_SIGN_DEC, XSECURE_RSA_STATE_MISMATCH_ERROR, XSecure_RsaOperation.
Referenced by XSecure_RsaPrivateDecrypt.
int XSecure_RsaPrivateDecrypt(XSecure_Rsa *InstancePtr, u8 *Input, u32 Size, u8 *Result)
This function handles the RSA decryption with the private key components provided when initializing the RSA cryptographic core with the XSecure_RsaInitialize function.
InstancePtr Pointer to the XSecure_Rsa instance Input Pointer to the buffer which contains the input data to be decrypted Size Key size in bytes, Input size also should be same as Key size mentioned. Inputs supported are XSECURE_RSA_4096_KEY_SIZE, XSECURE_RSA_2048_KEY_SIZE, or XSECURE_RSA_3072_KEY_SIZE Result Pointer to the buffer where resultant decrypted data to be stored XST_SUCCESS - If decryption was successfulXSECURE_RSA_INVALID_PARAM - On invalid parametersXSECURE_RSA_DATA_VALUE_ERROR - If input data is greater than modulusXSECURE_RSA_STATE_MISMATCH_ERROR - If State mismatch is occurredXST_FAILURE - On RSA operation failure RSA private key decryption data should be less than modulus. InstancePtr Pointer to the XSecure_Rsa instance Input Pointer to the buffer which contains the input data to be decrypted Size Key size in bytes, Input size also should be same as Key size mentioned. Inputs supported are XSECURE_RSA_4096_KEY_SIZE,XSECURE_RSA_2048_KEY_SIZEXSECURE_RSA_3072_KEY_SIZE Result Pointer to the buffer where resultant decrypted data to be stored XST_SUCCESS - If decryption was successfulXSECURE_RSA_DATA_VALUE_ERROR - If input data is greater than modulusXSECURE_RSA_STATE_MISMATCH_ERROR - If State mismatch is occurredXST_FAILURE - On RSA operation failure The Size passed here needs to match the key size used in the XSecure_RsaInitialize function
References XSecure_RsaPrivateDecrypt_64Bit.
static void XSecure_RsaPutData(const XSecure_Rsa *InstancePtr)
This function writes all the RSA data used for decryption (Modulus, Exponent) at the corresponding offsets in RSA RAM.
InstancePtr Pointer to the XSecure_Rsa instance
static void XSecure_RsaWriteMem(const XSecure_Rsa *InstancePtr, u64 WrDataAddr, u8 RamOffset)
This function writes data to RSA RAM at a given offset.
InstancePtr Pointer to the XSecure_Aes instance WrDataAddr Address of the data to be written to RSA RAM RamOffset Offset for the data to be written in RSA RAM
static void XSecure_RsaMod32Inverse(const XSecure_Rsa *InstancePtr)
This function calculates the MINV value and put it into RSA core registers.
InstancePtr Pointer to XSeure_Rsa instance MINV is the 32-bit value of -M mod 2**32, where M is LSB 32 bits of the original modulus
static void XSecure_RsaGetData(const XSecure_Rsa *InstancePtr, u64 RdDataAddr)
This function reads back the resulting data from RSA RAM.
InstancePtr Pointer to the XSecure_Rsa instance RdDataAddr Address of the location where RSA output data will be written
static void XSecure_RsaDataLenCfg(const XSecure_Rsa *InstancePtr, u32 Cfg0, u32 Cfg1, u32 Cfg2, u32 Cfg5)
This function updates data length configuration.
InstancePtr Pointer to the XSecure_Rsa instance. Cfg0 QSEL, Multiplication passes. Cfg1 Number of Montgomery digits. Cfg2 Memory location size. Cfg5 Number of groups.
u32 XSecure_RsaCfgInitialize(XSecure_Rsa *InstancePtr)
This function stores the base address of RSA core registers.
InstancePtr Pointer to the XSecure_Rsa instance XST_SUCCESS - On successXSECURE_RSA_INVALID_PARAM - On invalid parameter
References XSecure_Rsa::BaseAddress, XSECURE_CORE_RSA_ECC, XSecure_CryptoCheck, XSECURE_ECDSA_RSA_BASEADDR, XSECURE_RSA_INVALID_PARAM.
Referenced by XSecure_RsaInitialize_64Bit.
int XSecure_RsaOperation(XSecure_Rsa *InstancePtr, u64 Input, u64 Result, XSecure_RsaOps RsaOp, u32 KeySize)
This function handles the Public encryption and private decryption of RSA operations with provided inputs.
InstancePtr Pointer to the XSecure_Rsa instance Input Address of the buffer which contains the input data to be encrypted/decrypted Result Address of buffer where resultant encrypted/decrypted data to be stored RsaOp Flag to inform the operation to be performed is either encryption/decryption KeySize Size of the key in bytes XST_SUCCESS - On successXSECURE_RSA_INVALID_PARAM - On invalid parameterXST_FAILURE - On failure
References XSecure_Rsa::BaseAddress, XSecure_Rsa::EncDec, XSecure_Rsa::ModExpoAddr, XSecure_Rsa::ModExtAddr, XSecure_Rsa::SizeInWords, XSECURE_ECDSA_RSA_CFG0_2048_VALUE, XSECURE_ECDSA_RSA_CFG0_3072_VALUE, XSECURE_ECDSA_RSA_CFG0_4096_VALUE, XSECURE_ECDSA_RSA_CFG1_2048_VALUE, XSECURE_ECDSA_RSA_CFG1_3072_VALUE, XSECURE_ECDSA_RSA_CFG1_4096_VALUE, XSECURE_ECDSA_RSA_CFG2_2048_VALUE, XSECURE_ECDSA_RSA_CFG2_3072_VALUE, XSECURE_ECDSA_RSA_CFG2_4096_VALUE, XSECURE_ECDSA_RSA_CFG5_2048_VALUE, XSECURE_ECDSA_RSA_CFG5_3072_VALUE, XSECURE_ECDSA_RSA_CFG5_4096_VALUE, XSECURE_ECDSA_RSA_CFG_OFFSET, XSECURE_ECDSA_RSA_CTRL_OFFSET, XSECURE_ECDSA_RSA_KEY_LEN_OFFSET, XSECURE_ECDSA_RSA_RESET_OFFSET, XSECURE_ECDSA_RSA_STATUS_OFFSET, XSecure_ReleaseReset, XSECURE_RSA_2048_KEY_SIZE, XSECURE_RSA_2048_SIZE_WORDS, XSECURE_RSA_3072_KEY_SIZE, XSECURE_RSA_3072_SIZE_WORDS, XSECURE_RSA_4096_KEY_SIZE, XSECURE_RSA_4096_SIZE_WORDS, XSECURE_RSA_CONTROL_EXP, XSECURE_RSA_CONTROL_EXP_PRE, XSECURE_RSA_INVALID_PARAM, XSECURE_RSA_PUBLIC_EXPO_SIZE, XSECURE_RSA_RAM_DIGEST, XSECURE_RSA_SIGN_DEC, XSECURE_RSA_SIGN_ENC, XSECURE_RSA_STATUS_DONE, XSECURE_RSA_STATUS_ERROR, XSecure_RsaZeroize, XSecure_SetReset, XSECURE_TIMEOUT_MAX, XSECURE_WORD_IN_BITS, XSECURE_WORD_SIZE.
Referenced by XSecure_RsaPrivateDecrypt_64Bit, XSecure_RsaPublicEncrypt_64Bit.
int XSecure_RsaZeroize(const XSecure_Rsa *InstancePtr)
This function clears whole RSA memory space.
This function clears stored exponent, modulus and exponentiation key components along with digest InstancePtr Pointer to the XSecure_Rsa instance XST_SUCCESS - On SuccessXSECURE_RSA_INVALID_PARAM - On invalid parameter
References XSecure_Rsa::BaseAddress, XSECURE_ECDSA_RSA_MINV_OFFSET, XSECURE_RSA_INVALID_PARAM, XSecure_RsaEcdsaZeroizeAndVerifyRam.
Referenced by XSecure_RsaOperation.
u8 * XSecure_RsaGetTPadding(void)
This function returns PKCS padding as per the silicon version.
XSecure_Silicon2_TPadSha3
Referenced by XSecure_RsaSignVerification_64Bit.
static int XSecure_RsaEcdsaZeroizeVerify(u32 BaseAddress)
This function verifies whole RSA or ECDSA memory space.
BaseAddress BaseAddress of RSA or ECDSA controller. XST_SUCCESS - On SuccessXST_FAILURE - On Failure
int XSecure_RsaEcdsaZeroizeAndVerifyRam(u32 BaseAddress)
This function clears and verifies whole RSA or ECDSA memory space.
BaseAddress BaseAddress of ECDSA or RSA controller. XST_SUCCESS - On SuccessXST_FAILURE - On Failure
References XSECURE_ECDSA_RSA_CTRL_OFFSET, XSECURE_ECDSA_RSA_RAM_ADDR_OFFSET, XSECURE_RSA_MAX_RD_WR_CNT, XSECURE_RSA_RAM_RES_Q.
Referenced by XSecure_RsaZeroize.
static int XSecure_RsaEncrypt(u32 SubsystemId, u32 SrcAddrLow, u32 SrcAddrHigh, u32 DstAddrLow, u32 DstAddrHigh)
This function handler calls XSecure_RsaInitialize and XSecure_RsaPublicEncrypt server APIs.
SubsystemId Subsystem ID. SrcAddrLow Lower 32 bit address of the XSecure_RsaInParam structure SrcAddrHigh Higher 32 bit address of the XSecure_RsaInParam structure DstAddrLow Lower 32 bit address of the output data where encrypted data to be stored DstAddrHigh Higher 32 bit address of the output data where encrypted data to be stored XST_SUCCESS - If the Rsa encryption is successfulXST_FAILURE - If there is a failure
static int XSecure_RsaSignVerify(u32 SubsystemId, u32 SrcAddrLow, u32 SrcAddrHigh)
This function handler extracts the payload params with respect to XSECURE_API_RSA_SIGN_VERIFY IPI command and calls XSecure_RsaSignVerification_64Bit server API.
SubsystemId Subsystem ID. SrcAddrLow Lower 32 bit address of the XSecure_RsaSignParams structure SrcAddrHigh Higher 32 bit address of the XSecure_RsaSignParams structure XST_SUCCESS - If the Rsa sign verification is successfulXST_FAILURE - If there is a failure
int XSecure_RsaIpiHandler(XPlmi_Cmd *Cmd)
This function calls respective IPI handler based on the API_ID.
Cmd is a pointer to the command structure XST_SUCCESS - If the handler execution is successfulXST_INVALID_PARAM - If Cmd is NULL or API ID is invalidXST_FAILURE - If there is a failure
References XSECURE_API, XSECURE_API_ID_MASK, XSECURE_API_RSA_PUBLIC_ENCRYPT, XSECURE_API_RSA_SIGN_VERIFY, XSECURE_DEBUG_GENERAL, XSecure_Printf.
static int XSecure_IsNonZeroBuffer(u8 *Data, const u32 Size)
This function checks if the data in the provided buffer is non-zero.
Data - Pointer to the buffer which contains data to be validated Size - Size of the buffer in bytes XST_SUCCESS In case of non-zero bufferXST_FAILURE In case the buffer is all zeroes
XSECURE_RSA_MAX_MSG_SIZE_IN_BYTES
RSA maximum message size in bytes.
XSECURE_RSA_MAX_PS_SIZE_IN_BYTES
RSA maximum PS size in bytes.
XSECURE_RSA_MAX_DB_SIZE_IN_BYTES
RSA maximum DB size in bytes.
externC
For compilation in C++.
XSECURE_RSA_KEY_GEN_SIZE_IN_BYTES
RSA default key size in bytes.
Referenced by main, XSecure_KeyUnwrap, XSecure_RsaOaepDecrypt, XSecure_RsaOaepEncrypt, XSecure_RsaPwct.
XSECURE_RSA_KEY_GEN_SIZE_IN_WORDS
RSA key generation size in words.
XSECURE_RSA_MAX_KEY_GEN_SUPPORT
Maximum keys that needs to be generated.
Referenced by XSecure_GetRsaPrivateKey, XSecure_GetRsaPublicKey, XSecure_RsaDestroyKeyInUse.
XSECURE_RSA_KEY_STATUS_WAIT
RSA key status wait.
XSECURE_RSA_2048_QUANT_SIZE
RSA maximum quant size for 2048 bit key.
XSECURE_RSA_3072_QUANT_SIZE
RSA maximum quant size for 3072 bit key.
XSECURE_RSA_4096_QUANT_SIZE
RSA maximum quant size for 4096 bit key.
XSECURE_RSA_PUBLIC_EXPONENT
RSA public exponent value.
XSECURE_RSA_PUB_EXP_SIZE
RSA public exponent size.
Referenced by XSecure_RsaPwct.
XSECURE_KEY_PAIR_GEN_POLL_INTERVAL
Key pair generation poll interval.
Referenced by XSecure_AddRsaKeyPairGenerationToScheduler.
XSECURE_ECDSA_RSA_SOFT_RESET
ECDSA/RSA soft reset address.
Referenced by XSecure_RsaExp, XSecure_RsaExpCRT, XSecure_RsaExpopt.
XSECURE_RSA_SIZE_IN_BYTES
512 bytes for 4096 bit data
XSECURE_PRIME_FACTOR_P_SIZE
size of first prime factor(P)
XSECURE_PRIME_FACTOR_Q_SIZE
size of first prime factor(Q)
XSECURE_PRIME_FACTOR_MAX_P_SIZE
256 bytes size of first prime factor(P)
XSECURE_PRIME_FACTOR_MAX_Q_SIZE
256 bytes size of first prime factor(Q)
XSECURE_RSA_BYTE_PAD_LENGTH
PKCS Byte Padding.
Referenced by XSecure_RsaSignVerification_64Bit.
XSECURE_RSA_T_PAD_LENGTH
PKCS T Padding.
Referenced by XSecure_RsaSignVerification_64Bit.
XSECURE_RSA_BYTE_PAD1
PKCS T Padding Byte.
Referenced by XSecure_RsaSignVerification_64Bit.
XSECURE_RSA_BYTE_PAD2
PKCS T Padding Byte.
Referenced by XSecure_RsaSignVerification_64Bit.
XSECURE_RSA_BYTE_PAD3
PKCS T Padding Byte.
Referenced by XSecure_RsaSignVerification_64Bit.
XSECURE_RSA_INVALID_PARAM
Invalid Argument.
Referenced by XSecure_RsaCfgInitialize, XSecure_RsaInitialize_64Bit, XSecure_RsaOperation, XSecure_RsaPrivateDecrypt_64Bit, XSecure_RsaPublicEncrypt_64Bit, XSecure_RsaSignVerification_64Bit, XSecure_RsaZeroize.
XSECURE_RSA_STATE_MISMATCH_ERROR
State mismatch.
Referenced by XSecure_RsaPrivateDecrypt_64Bit, XSecure_RsaPublicEncrypt_64Bit.
XSECURE_TIMEOUT_MAX
Recommended software timeout.
Referenced by XSecure_RsaOperation.
SIZEOF_INT_IN_BYTES
Size of integer om bytes.
XSECURE_RSA_ECDSA_ZEROIZE_ERROR
for RSA zeroization Error
XSECURE_RSA_MAX_BUFF
RSA RAM Write Buffers.
XSECURE_RSA_MAX_RD_WR_CNT
No of writes or reads to RSA RAM buffers.
Referenced by XSecure_RsaEcdsaZeroizeAndVerifyRam.
XSECURE_RSA_RAM_RES_Q
bit for RSA RAM Result(Q)
Referenced by XSecure_RsaEcdsaZeroizeAndVerifyRam.
XSECURE_RSA_DATA_VALUE_ERROR
for RSA private decryption data should be lesser than modulus
Referenced by XSecure_RsaPrivateDecrypt_64Bit.
XSECURE_HASH_TYPE_SHA3
SHA-3 hash size.
Referenced by XSecure_DataAuth, XSecure_PpkVerify, XSecure_RsaSignVerification_64Bit, XSecure_SpkAuthentication.
XSECURE_FSBL_SIG_SIZE
FSBL signature size.
Referenced by XSecure_RsaSignVerification_64Bit.
XSECURE_RSA_PUBLIC_EXPO_SIZE
Size of public key expo.
Referenced by XSecure_RsaOperation.
XSECURE_RSA_2048_KEY_SIZE
RSA 2048 key size.
Referenced by XSecure_RsaOperation, XSecure_RsaPrivateDecryptKat, XSecure_RsaPublicEncryptKat.
XSECURE_RSA_3072_KEY_SIZE
RSA 3072 key size.
Referenced by XSecure_RsaOperation.
XSECURE_RSA_4096_KEY_SIZE
RSA 4096 key size.
Referenced by XSecure_RsaOperation.
XSECURE_RSA_2048_SIZE_WORDS
RSA 2048 Size in words.
Referenced by XSecure_GetKatRsaPrivateExp, XSecure_RsaOperation, XSecure_RsaPrivateDecryptKat, XSecure_RsaPublicEncryptKat.
XSECURE_RSA_3072_SIZE_WORDS
RSA 3072 Size in words.
Referenced by XSecure_RsaOperation.
XSECURE_RSA_4096_SIZE_WORDS
RSA 4096 Size in words.
Referenced by XSecure_RsaInitialize_64Bit, XSecure_RsaOperation.
XSECURE_RSA_RAM_EXPO
bit for RSA RAM Exponent
XSECURE_RSA_RAM_MOD
bit for RSA RAM modulus
XSECURE_RSA_RAM_DIGEST
bit for RSA RAM Digest
Referenced by XSecure_RsaOperation.
XSECURE_RSA_RAM_RES_Y
bit for RSA RAM Result(Y)
XSECURE_RSA_KEY_ADDR_SIZE
Size of public key expo.
XSECURE_RSA_MODULE_MAJOR_VERSION
RSA module major version.
XSECURE_RSA_MODULE_MINOR_VERSION
RSA module minor version.
XSECURE_RSA_MODULE_MAJOR_VERSION
RSA module major version.
XSECURE_RSA_MODULE_MINOR_VERSION
RSA module minor version.
XSECURE_RSA_MODULE_MAJOR_VERSION
RSA module major version.
XSECURE_RSA_MODULE_MINOR_VERSION
RSA module minor version.
XSECURE_RSA_PUBLIC_EXPO_SIZE
Size of public key expo.
XSECURE_RSA_BYTE_PAD_LENGTH
PKCS Byte Padding.
XSECURE_RSA_T_PAD_LENGTH
PKCS T Padding.
XSECURE_RSA_BYTE_PAD1
PKCS T Padding Byte.
XSECURE_RSA_BYTE_PAD2
PKCS T Padding Byte.
XSECURE_RSA_BYTE_PAD3
PKCS T Padding Byte.
XSECURE_RSA_INVALID_PARAM
Invalid Argument.
XSECURE_RSA_STATE_MISMATCH_ERROR
State mismatch.