xsecure_generic_server_apis
XSECURE_EFUSE_CACHE_IP_DISABLE0
< IP_DISABLE_0 register address and definitions
Referenced by XSecure_CryptoCheck.
XSECURE_EFUSE_CACHE_IP_DISABLE0_EXPORT_MASK
XSECURE_CFU_APB_CFU_FGCR
< CFU_FGCR register address and definitions
Referenced by XSecure_CryptoCheck.
XSECURE_CFU_APB_CFU_FGCR_EOS_MASK
XSECURE_CRP_RST_PS
< RST_PS register address and definitions
Referenced by XSecure_CryptoCheck.
XSECURE_CRP_RST_PS_PS_SRST_MASK
XSecure_AssertVoid
< All asserts are under XSECDEBUG macro now
Referenced by XSecure_AesPmcDmaCfgEndianness.
XSecure_AssertNonvoid
XSecure_CoreSrc
AES Core.
XSecure_Sha XSecure_ShaInstance[XSECURE_SHA_NUM_OF_INSTANCES][XSECURE_SHA_NUM_OF_INSTANCES]
u32 XSecure_ResIpiMask[XPLMI_MAX_CORE][XPLMI_MAX_CORE]
u32 XSecure_DataContextLost[XPLMI_MAX_CORE][XPLMI_MAX_CORE]
static XPlmi_Module XPlmi_Secure
XPlmi_ModuleCmd XSecure_Cmds[XSECURE_API_MAX][XSECURE_API_MAX]
XPlmi_AccessPerm_t XSecure_AccessPermBuff[XSECURE_API_MAX][XSECURE_API_MAX]
static XPlmi_Module XPlmi_Secure
XPlmi_ModuleCmd XSecure_Cmds[XSECURE_API_MAX][XSECURE_API_MAX]
XPlmi_AccessPerm_t XSecure_AccessPermBuff[XSECURE_API_MAX][XSECURE_API_MAX]
static XPlmi_Module XPlmi_Secure
XPlmi_ModuleCmd XSecure_Cmds[XSECURE_API_MAX][XSECURE_API_MAX]
XPlmi_AccessPerm_t XSecure_AccessPermBuff[XSECURE_API_MAX][XSECURE_API_MAX]
static XPlmi_Module XPlmi_Secure
XPlmi_ModuleCmd XSecure_Cmds[XSECURE_API_MAX][XSECURE_API_MAX]
XPlmi_AccessPerm_t XSecure_AccessPermBuff[XSECURE_API_MAX][XSECURE_API_MAX]
static XPlmi_Module XPlmi_Secure
XPlmi_ModuleCmd XSecure_Cmds[XSECURE_API_MAX][XSECURE_API_MAX]
XPlmi_AccessPerm_t XSecure_AccessPermBuff[XSECURE_API_MAX][XSECURE_API_MAX]
int XSecure_CryptoCheck(XSecure_CoreSrc CoreSrc)
This function checks if the EXPORT control eFuse is programmed and PL loading is done.
CoreSrc Crypto core source (AES, SHA, RSA) XST_SUCCESS - When crypto accelerators are enabledXSECURE_ERR_CRYPTO_ACCELERATOR_DISABLED - When crypto accelerators are disabled
References XSECURE_CFU_APB_CFU_FGCR, XSECURE_CRP_RST_PS, XSECURE_EFUSE_CACHE_IP_DISABLE0, XSECURE_ERR_CRYPTO_ACCELERATOR_DISABLED, XSecure_In32.
Referenced by XSecure_AesInitialize, XSecure_EcdhGetSecret, XSecure_EllipticGenerateKey_64Bit, XSecure_EllipticGenerateSignature_64Bit, XSecure_EllipticValidateKey_64Bit, XSecure_EllipticVerifySign_64Bit, XSecure_RsaCfgInitialize, XSecure_Sha3Start.
int XSecure_AesShaInit(void)
This function initializes AES and SHA hardware instances.
XST_SUCCESS - On successXST_FAILURE - On failure
References XSecure_AesInitialize, XSecure_GetAesInstance, XSecure_GetSha2Instance, XSecure_GetSha3Instance, XSECURE_SHA_0_DEVICE_ID, XSECURE_SHA_1_DEVICE_ID, XSecure_ShaInitialize, XSecure_ShaLookupConfig.
Referenced by XSecure_Init.
int XSecure_Init(XSecure_PartialPdiEventParams *PpdiEventParamsPtr)
This function registers the handlers for XilSecure IPI commands.
PpdiEventParamsPtr is the pointer to partial PDI event parameters XST_SUCCESS - On successXST_FAILURE - On failure
References XSecure_AddRsaKeyPairGenerationToScheduler, XSecure_AesShaInit, XSecure_CmdsInit.
XSecure_Sha * XSecure_GetSha3Instance(u32 DeviceId)
This function provides the pointer to the sha3 instance.
Pointer to the XSecure_Sha instance
References XSecure_GetShaInstance.
Referenced by XSecure_AesShaInit, XSecure_Hkdf, XSecure_HmacIpiHandler, XSecure_KatIpiHandler, XSecure_SetDataContextLost, XSecure_Sha3IpiHandler, XSecure_ShaIpiHandler, XSecure_SlhdsaIpiHandler.
XSecure_Sha * XSecure_GetSha2Instance(u32 DeviceId)
This function provides the pointer to the sha2 instance.
Pointer to the XSecure_Sha instance
References XSecure_GetShaInstance.
Referenced by XSecure_AesShaInit, XSecure_KatPlatIpiHandler, XSecure_ShaIpiHandler.
XSecure_Aes * XSecure_GetAesInstance(void)
This function provides the pointer to the common Aes instance which has to be used between PLM and xilsecure server.
Pointer to the XSecure_Aes instance
Referenced by XSecure_AesInit, XSecure_AesIpiHandler, XSecure_AesKeyWrite, XSecure_AesKeyZeroize, XSecure_AesPerformOperation, XSecure_AesPlatPmcDmaCfgAndXfer, XSecure_AesShaInit, XSecure_ConfigureDmaByteSwap, XSecure_KatIpiHandler, XSecure_KeyUnwrap, XSecure_PlatAesIpiHandler, XSecure_SetDataContextLost.
XSecure_Rsa * XSecure_GetRsaInstance(void)
This function provides the pointer to the common Rsa instance which has to be used between PLM and xilsecure server.
Pointer to the XSecure_Rsa instance
XSecure_Sha * XSecure_GetShaInstance(u32 DeviceId)
This function provides the pointer to the sha instance based on the DevieId.
Pointer to the XSecure_Sha instance
References XSECURE_SHA_NUM_OF_INSTANCES.
Referenced by XSecure_GetSha2Instance, XSecure_GetSha3Instance.
int XSecure_MakeResFree(XPlmi_CoreType Core)
The function frees AES/SHA resource.
Core is the resource which is to be freed Always returns XST_SUCCESS
References XSECURE_IPI_MASK_DEF_VAL.
Referenced by XSecure_AesIpiHandler, XSecure_HmacIpiHandler, XSecure_KatIpiHandler, XSecure_KatPlatIpiHandler, XSecure_PlatAesIpiHandler, XSecure_Sha3IpiHandler, XSecure_ShaIpiHandler, XSecure_SlhdsaIpiHandler.
int XSecure_IpiEventHandling(XPlmi_Cmd *Cmd, XPlmi_CoreType Core)
The function handles the SHA/AES IPI events.
Cmd is the pointer to received IPI command Core is the resource whose IPI events are to be handled XST_SUCCESS - On successXST_INVALID_PARAM - If Cmd is NULL or Core is invalidXST_DEVICE_BUSY - If device is busy with different IPI maskXST_DATA_LOST - If data context was lost
References XSECURE_DATACONTEXTLOST_CLR, XSECURE_DATACONTEXTLOST_SET, XSECURE_IPI_MASK_DEF_VAL.
Referenced by XSecure_AesIpiHandler, XSecure_HmacIpiHandler, XSecure_KatIpiHandler, XSecure_KatPlatIpiHandler, XSecure_PlatAesIpiHandler, XSecure_Sha3IpiHandler, XSecure_ShaIpiHandler, XSecure_SlhdsaIpiHandler.
int XSecure_SetDataContextLost(XPlmi_CoreType Core)
This function sets the status of data context of previous AES/SHA operation.
Core is the SHA/AES source whose data context status has to be set XST_SUCCESS - On successXST_INVALID_PARAM - If Core is invalid
References XSECURE_DATACONTEXTLOST_SET, XSecure_GetAesInstance, XSecure_GetSha3Instance, XSECURE_IPI_MASK_DEF_VAL, XSecure_SetReset, XSECURE_SHA3_RESET_OFFSET, XSECURE_SHA_0_DEVICE_ID, XSECURE_SHA_INITIALIZED.
static int XSecure_SssDmaSrc(u16 DmaId, XSecure_SssSrc *Resource)
This function sets the DMA source of type XSecure_SssSrc based on the provided DMA device ID.
DmaId Device ID of DMA Resource DMA source is updated into the pointer XST_SUCCESS - If DMA ID is correctXST_FAILURE - On wrong DMA ID
static int XSecure_SssCfg(const XSecure_Sss *InstancePtr, XSecure_SssSrc Resource, XSecure_SssSrc InputSrc, XSecure_SssSrc OutputSrc)
This function configures the secure stream switch.
InstancePtr Instance pointer to the XSecure_Sss Resource Resource for which input and output paths to be configured InputSrc Input source to be selected for the resource OutputSrc Output source to be selected for the resource XST_SUCCESS - On successful configuration of the switchXST_FAILURE - On unsuccessful configuration of the switch Resource, InputSrc, OutputSrc are of type XSecure_SssSrc
void XSecure_SssInitialize(XSecure_Sss *InstancePtr)
This function initializes the secure stream switch instance.
InstancePtr Instance pointer to the XSecure_Sss XST_SUCCESS - If initialization was successfulXSECURE_SSS_INVALID_PARAM - On invalid parameter InstancePtr Instance pointer to the XSecure_Sss.
References XSECURE_SSS_ADDRESS, XSECURE_SSS_INVALID_PARAM.
Referenced by XSecure_AesInitialize, XSecure_MemCopy, XSecure_Sha3Initialize.
int XSecure_SssAes(const XSecure_Sss *InstancePtr, XSecure_SssSrc InputSrc, XSecure_SssSrc OutputSrc)
This function configures the secure stream switch for AES engine.
InstancePtr Instance pointer to the XSecure_Sss InputSrc Input DMA to be selected for AES engine OutputSrc Output DMA to be selected for AES engine XST_SUCCESS - On successful configuration of the switchXSECURE_SSS_INVALID_PARAM - On invalid parameterXST_FAILURE - On failure to configure switch InputSrc, OutputSrc are of type XSecure_SssSrc
References XSecure_SecureOut32, XSECURE_SSS_AES, XSECURE_SSS_DMA0, XSECURE_SSS_DMA1, XSECURE_SSS_INVALID_PARAM, XSecure_SssMask.
Referenced by XSecure_AesDecrypt, XSecure_AesDecryptInit, XSecure_AesEncryptInit, XSecure_CfgSssAes.
int XSecure_SssSha(const XSecure_Sss *InstancePtr, u16 DmaId, XSecure_SssSrc Resource)
This function configures the secure stream switch for SHA hardware engine.
InstancePtr Instance pointer to the XSecure_Sss DmaId Device ID of DMA which is to be used as an input to the SHA engine Resource SHA resource for which input and output paths to be configured XST_SUCCESS - On successful configuration of the switchXSECURE_SSS_INVALID_PARAM - On invalid parameterXST_FAILURE - On failure to configure switch
References XSecure_SecureOut32, XSECURE_SSS_DMA0, XSECURE_SSS_DMA1, XSECURE_SSS_INVALID, XSECURE_SSS_INVALID_PARAM, XSecure_SssMask.
int XSecure_SssDmaLoopBack(const XSecure_Sss *InstancePtr, u16 DmaId)
This function configures secure stream switch to set DMA in loop back mode.
InstancePtr Instance pointer to the XSecure_Sss DmaId Device ID of DMA XST_SUCCESS - On successful configuration of the switchXSECURE_SSS_INVALID_PARAM - On invalid parameterXST_FAILURE - On failure to configure switch
References XSECURE_SSS_DMA0, XSECURE_SSS_DMA1, XSECURE_SSS_INVALID, XSECURE_SSS_INVALID_PARAM.
Referenced by XSecure_MemCopy.
void XSecure_ReleaseReset(UINTPTR BaseAddress, u32 Offset)
This function takes the hardware core out of reset.
BaseAddress Base address of the core Offset Offset of the reset register
References XSECURE_RESET_SET, XSECURE_RESET_UNSET, XSECURE_SET_BIT.
Referenced by XSecure_AesReset, XSecure_EcdhGetSecret, XSecure_EllipticGenerateEphemeralKey, XSecure_EllipticGenerateKey_64Bit, XSecure_EllipticGenerateSignature_64Bit, XSecure_EllipticPrvtKeyGenerate, XSecure_EllipticValidateKey_64Bit, XSecure_EllipticVerifySign_64Bit, XSecure_MldsaSignGenerate, XSecure_MldsaSignVerify, XSecure_RsaOperation, XSecure_Sha3Start.
void XSecure_SetReset(UINTPTR BaseAddress, u32 Offset)
This function places the hardware core into the reset.
BaseAddress Base address of the core Offset Offset of the reset register
References XSECURE_CLEAR_BIT, XSECURE_RESET_SET.
Referenced by XSecure_AesDecrypt, XSecure_AesDecryptInit, XSecure_AesDecryptUpdate, XSecure_AesEcbDecrypt, XSecure_AesEncryptInit, XSecure_AesEncryptUpdate, XSecure_AesKeyUnwrap, XSecure_EcdhGetSecret, XSecure_EllipticGenerateEphemeralKey, XSecure_EllipticGenerateKey_64Bit, XSecure_EllipticGenerateSignature_64Bit, XSecure_EllipticPrvtKeyGenerate, XSecure_EllipticValidateKey_64Bit, XSecure_EllipticVerifySign_64Bit, XSecure_ExtendedShaFinish, XSecure_HmacFinal, XSecure_HmacInit, XSecure_HmacUpdate, XSecure_MldsaSignGenerate, XSecure_MldsaSignVerify, XSecure_RsaOperation, XSecure_SetDataContextLost, XSecure_Sha2256Kat, XSecure_Sha3Finish, XSecure_Sha3Kat, XSecure_Sha3Update, XSecure_Sha3Update64Bit, XSecure_ShakeKat.
static u32 XSecure_ReadReg(UINTPTR BaseAddress, u16 RegOffset)
Read from the register.
BaseAddress Contains the base address of the device RegOffset Contains the offset from the base address of the device The value read from the register
static void XSecure_WriteReg(UINTPTR BaseAddress, u32 RegOffset, u32 RegisterValue)
Write to the register.
BaseAddress Contains the base address of the device RegOffset Contains the offset from the base address of the device RegisterValue Is the value to be written to the register
static u32 XSecure_In64(u64 Addr)
This function reads data from 64-bit address.
Addr is the address The value read from the provided address
static u8 XSecure_InByte64(u64 Addr)
This function reads a byte from 64-bit address.
Addr is the address The value read from the provided address
static void XSecure_Out64(u64 Addr, u32 Data)
This function writes data to 64-bit address.
Addr is the address Data is the value to be written
static void XSecure_OutWord64(u64 Addr, u32 Data)
This function writes 32 bit data to 64-bit address.
Addr is the address Data is the value to be written
static void XSecure_OutByte64(u64 Addr, u8 Data)
This function writes a byte to a 64-bit address.
Addr is the address Data is the value to be written
static int XSecure_InvalidCmdHandler(u32 *Payload, u32 *RespBuf)
This function calls the handler for invalid commands.
Payload is a pointer to IPI payload data RespBuf Buffer to store response of slaves XST_SUCCESS On successful communicationXPLMI_ERR_CMD_APIID On unregistered command ID.XPLMI_SSIT_INTR_NOT_ENABLED If interrupts are not enabled.
static int XSecure_FeaturesCmd(XPlmi_Cmd *Cmd)
This function checks if a particular Secure API ID is supported or not.
Cmd Pointer to the command structure XST_SUCCESS SuccessXST_INVALID_PARAM Unsupported API ID
static int XSecure_ProcessCmd(XPlmi_Cmd *Cmd)
This function processes XilSecure IPI commands.
Cmd Pointer to the command structure XST_SUCCESS Upon successXST_INVALID_PARAM If any input parameter is invalidXSECURE_KAT_MAJOR_ERROR If KAT fails
void XSecure_CmdsInit(void)
This function registers the XilSecure commands to the PLMI.
Referenced by XSecure_Init.
static int XSecure_FeaturesCmd(u32 ApiId)
This function checks if a particular Secure API ID is supported or not.
ApiId is API ID in the IPI request. XST_SUCCESS SuccessXST_INVALID_PARAM Unsupported API ID
XSECURE_DATACONTEXTLOST_SET
Set value of data context lost.
Referenced by XSecure_IpiEventHandling, XSecure_SetDataContextLost.
XSECURE_DATACONTEXTLOST_CLR
Clear value of data context lost.
Referenced by XSecure_IpiEventHandling.
XSECURE_IPI_FIRST_PACKET_MASK
IPI First packet Mask.
XSECURE_RESET_SET
To set the core into reset.
Referenced by XSecure_ReleaseReset, XSecure_SetReset.
XSECURE_RESET_UNSET
To take the core out of reset.
Referenced by XSecure_ReleaseReset.
XSECURE_WORD_SIZE
WORD size in BYTES.
Referenced by XSecure_AesPlatPmcDmaCfgAndXfer, XSecure_AesValidateSize, XSecure_ExtendedShaFinish, XSecure_Hkdf, XSecure_MaskGenFunc, XSecure_MldsaSignGenerate, XSecure_MldsaSignVerify, XSecure_RsaOperation, XSecure_Sha3ReadHash, XSecure_ShaDmaXfer.
XSECURE_QWORD_SIZE
QWORD size in BYTES.
Referenced by XSecure_AesValidateSize.
XSECURE_WORD_IN_BITS
WORD size in BITS.
Referenced by XSecure_RsaOperation.
XSECURE_BYTE_IN_BITS
Byte size in BITS.
Referenced by XSecure_MldsaSignGenerate, XSecure_MldsaSignVerify, XSecure_RsaOaepDecrypt, XSecure_SlhdsaBase2b.
XSECURE_WORD_ALIGN_MASK
WORD alignment.
Referenced by XSecure_MemCpy64, XSecure_ShaDmaXfer.
XSECURE_SET_BIT
To set bit.
Referenced by XSecure_ReleaseReset.
XSECURE_CLEAR_BIT
To clear bit.
Referenced by XSecure_EllipticPrvtKeyGenerate, XSecure_SetReset.
XSECURE_VALUE_ONE
Integer value 1U.
Referenced by XSecure_MldsaSignGenerate, XSecure_MldsaSignVerify, XSecure_SlhdsaBase2b, XSecure_SlhdsaForsPkFromSig, XSecure_SlhdsaHtVerify, XSecure_SlhdsaXmssPkFromSign.
XSECURE_VALUE_TWO
Integer value 2U.
Referenced by XSecure_MldsaSignGenerate, XSecure_MldsaSignVerify, XSecure_SlhdsaShake256sHashMsg, XSecure_SlhdsaVerify.
XSECURE_VALUE_THREE
Integer value 3U.
XSECURE_ALLFS
To assign invalid value.
XSECURE_ZERO
To assign/compare to zero.
Referenced by XSecure_MldsaSignVerify, XSecure_RsaDestroyKeyInUse, XSecure_SlhdsaBase2b, XSecure_SlhdsaForsPkFromSig, XSecure_SlhdsaShake256sChain, XSecure_SlhdsaShake256sHashMsg, XSecure_SlhdsaWotsPkFromSign.
XSecure_MemCpy
Backward compatibility.
XSecure_MemCpy64
Backward compatibility.
XSecure_In32
Reads data from 32-bit address.
Referenced by SecureAesExample, XSecure_CryptoCheck, XSecure_InitiateASUKeyTransfer, XSecure_MldsaSignGenerate.
XSecure_Out32
Writes data to 32-bit address.
Referenced by XSecure_AesDecrypt, XSecure_AesDecryptInit, XSecure_AesEncryptInit, XSecure_InitiateASUKeyTransfer, XSecure_MldsaSignGenerate, XSecure_MldsaSignVerify, XSecure_RsaExp, XSecure_RsaExpCRT, XSecure_RsaExpopt.
XSecure_SecureOut32
Writes data to 32-bit address and checks for blind writes.
Referenced by XSecure_SssAes, XSecure_SssSha.