xsecure_apis
XSECURE_EFUSE_SEC_CTRL
< eFuse secure control register offsets and definitions
Referenced by XSecure_IsEncOnlyEnabled, XSecure_IsRsaEnabled, XSecure_PpkVerify.
XSECURE_EFUSE_SEC_CTRL_PPK0_REVOKE
XSECURE_EFUSE_SEC_CTRL_PPK1_REVOKE
XSECURE_EFUSE_SEC_CTRL_RSA_ENABLE
XSECURE_EFUSE_SEC_CTRL_ENC_ONLY
XSecure_ShaPlatConfig ShaInitPlatConfig[XSECURE_SHA_NUM_OF_INSTANCES][XSECURE_SHA_NUM_OF_INSTANCES]
SHA platform configuration.
XSecure_Aes SecureAes
XSecure_Rsa Secure_Rsa
XSecure_Sha3 Sha3Instance
XCsuDma CsuDma
u32 XsecureIv[XSECURE_IV_LEN][XSECURE_IV_LEN]
const u8 CsuKey[][]
u8 CsuIv[][]
u32 ImageOffset
u32 DestinationAddr
XSecure_Aes Secure_Aes
XCsuDma CsuDma
u32 ImageOffset
u32 HeaderSrcOffset
u32 HeaderFsblTotalLenOffset
static int XSecure_ShaWaitForDone(const XSecure_Sha *InstancePtr)
This function check whether hash calculation is completed or not.
InstancePtr - Pointer to the SHA instance. XST_SUCCESS - Upon Success.XST_FAILURE - Upon Failure.
static int XSecure_TransferNistPad(XSecure_Sha *const InstancePtr)
This function performs NIST padding for different SHA algorithms according to their respective specifications and transfers the combined partial data + padding to the SHA engine via DMA.
Any data buffered in PartialData from XSecure_ShaDmaXfer is kept in place and the NIST padding is appended directly after it. The combined buffer is then DMA'd as a single transfer. InstancePtr - Pointer to the SHA instance. XST_SUCCESS - Upon Success.XST_FAILURE - Upon Failure.XSECURE_SHA_INVALID_PARAM - Upon invalid SHA algorithm parameter. This function applies algorithm-specific NIST padding: SHA2 - 0x80 start byte + zero padding + message length in bits (big-endian) SHA3 - 0x06 start byte + zero padding + 0x80 end byte SHAKE - 0x1F start byte + zero padding + 0x80 end byte
static int XSecure_ShaDmaTransfer(XSecure_Sha *const InstancePtr, u64 DataAddr, u32 Len, u32 IsLastUpdate)
This function transfers data to the SHA engine using DMA and manages the complete transfer process including SSS configuration.
InstancePtr - Pointer to the SHA instance. DataAddr - Address of the data to be transferred to SHA engine. Len - Length of the data to be transferred in bytes. IsLastUpdate - Flag indicating if this is the last data transfer. XST_SUCCESS - Upon successful data transfer completion.XST_FAILURE - Upon any failure during the transfer process.XSECURE_SHA_DMA_TRANSFER_ERROR - Upon any failure during the transfer process.
static const XSecure_ShaConfig* XSecure_ShaLookupConfig(u32 DeviceId)
This function returns a reference to an XSecure_ShaConfig structure based on the unique device id.
DeviceId Unique device ID of the device for the lookup operation. It returns CfgPtr which is a reference to a config record in the configuration tableIt returns NULL if no match is found.
int XSecure_ShaInitialize(XSecure_Sha *const InstancePtr, XPmcDma *DmaPtr)
This function initializes SHA instance so that it is ready to be used.
InstancePtr - Pointer to the SHA instance. DmaPtr - Pointer to the DMA instance. XST_SUCCESS - Upon Success.XST_FAILURE - Upon Failure.XSECURE_SHA_INVALID_PARAM_ERRORXSECURE_SHA_SSS_INIT_ERROR
References XSECURE_SHA_INVALID_PARAM.
int XSecure_ShaStart(XSecure_Sha *const InstancePtr, XSecure_ShaMode ShaMode)
This function validates the SHA Mode (refer XSecure_ShaMode enum) and configures SSS and start the SHA engine.
InstancePtr - Pointer to the SHA instance. ShaMode - Indicates SHA3/SHA2 shall be operated in which sha mode that is SHA-384/256/512 XST_SUCCESS - Upon Success.XSECURE_SHA_INVALID_PARAM - Invalid parameter (InstancePtr is NULL or invalid SHA mode)XSECURE_SHA_STATE_MISMATCH_ERROR - SHA engine is not in initialized stateXST_FAILURE - On crypto check failure
u32 XSecure_ShaGetBlockLen(XSecure_ShaMode HashAlgo)
This function returns the block length for the given SHA algorithm.
HashAlgo SHA algorithm mode. Block length in bytes, or 0 for invalid algorithm.
References XSECURE_SHA2_256_BLOCK_LEN, XSECURE_SHA2_384_512_BLOCK_LEN, XSECURE_SHA3_256, XSECURE_SHA3_384, XSECURE_SHA3_384_BLOCK_LEN, XSECURE_SHA3_512_BLOCK_LEN, XSECURE_SHAKE_256, XSECURE_SHAKE_SHA3_256_BLOCK_LEN.
Referenced by XSecure_ShaDmaXfer.
int XSecure_ShaUpdate(XSecure_Sha *const InstancePtr, u64 DataAddr, const u32 DataSize)
This function updates input data to SHA Engine to calculate Hash.
InstancePtr Pointer to the SHA instance. DataAddr Pointer to the input data for hashing. DataSize Size of the input data in bytes. XST_SUCCESS - Upon Success.XST_FAILURE - Upon Failure.XSECURE_SHA_INVALID_PARAM_ERRORXSECURE_SHA_NOT_STARTED_ERROR
References XSECURE_SHA_INVALID_PARAM.
int XSecure_ExtendedShaFinish(XSecure_Sha *const InstancePtr, u64 HashAddr, u32 HashBufSize, u32 ReqHashSize)
This function calculates and reads the final hash of input data with support for variable-length hash output.
InstancePtr Pointer to the SHA instance. HashAddr Pointer to the buffer where the final hash will be stored. HashBufSize Size allocated for the hash buffer in bytes. Must be at least as large as ReqHashSize to avoid buffer overflow. ReqHashSize Requested hash size in bytes to be read from the SHA digest. Must not exceed XSECURE_MAX_HASH_SIZE_IN_BYTES. XST_SUCCESS - Upon successful hash calculation and retrieval.XST_FAILURE - Upon failure during hash completion or digest read.XSECURE_SHA_INVALID_PARAM - When InstancePtr is NULL or HashBufSize is less than ReqHashSize.XSECURE_SHA_STATE_MISMATCH_ERROR - When SHA engine is in initialized state without any update.XSECURE_SHA_NIST_PADDING_ERROR - When NIST padding operation fails.XSECURE_SHA_MAX_HASH_SIZE_EXCEED_ERROR - When ReqHashSize exceeds XSECURE_MAX_HASH_SIZE_IN_BYTES.
References XSecure_ShaPlatConfig::AutoPaddingOffset, SHAKE256, SHAKE256_SLH_DSA_CHAIN, XSecure_ShaPlatConfig::ShaMode, XSECURE_MAX_HASH_SIZE_IN_BYTES, XSecure_SetReset, XSECURE_SHA_INITIALIZED, XSECURE_SHA_INVALID_PARAM, XSECURE_SHA_MAX_HASH_SIZE_EXCEED_ERROR, XSECURE_SHA_NIST_PADDING_ERROR, XSECURE_SHA_RESET_OFFSET, XSECURE_SHA_STATE_MISMATCH_ERROR, XSECURE_WORD_SIZE.
Referenced by XSecure_SlhdsaShake256sHashMsg.
int XSecure_ShaFinish(XSecure_Sha *const InstancePtr, u64 HashAddr, u32 HashBufSize)
This function calculates and reads the final hash of input data.
InstancePtr - Pointer to the SHA instance. HashAddr - Pointer which holds final hash. HashBufSize - Size allocated for Hash Buffer XST_SUCCESS - Upon Success.XST_FAILURE - Upon Failure.XSECURE_SHA_INVALID_PARAM_ERROR - Upon invalid input parameterXSECURE_SHA_STATE_MISMATCH_ERROR - Upon sha state mismatch
References XSECURE_SHA_INVALID_PARAM.
int XSecure_ShaDigest(XSecure_Sha *const InstancePtr, XSecure_ShaMode ShaMode, u64 DataAddr, u32 DataSize, u64 HashAddr, u32 HashBufSize)
This function calculates the SHA2/3 digest on the given input data.
InstancePtr Pointer to the SHA instance. ShaMode Indicates SHA3/SHA2 shall be operated in which sha mode that is SHA-384/256/512 DataAddr Pointer to the input data for hashing. DataSize Size of the input data in bytes. HashAddr Pointer which holds final hash. HashBufSize Size allocated for Hash Buffer XST_SUCCESS - Upon Success.XST_FAILURE - Upon Failure.XSECURE_SHA_INVALID_PARAM_ERRORXSECURE_SHA_NOT_INITIALIZED_ERROR
References XSECURE_SHA_INITIALIZED, XSECURE_SHA_INVALID_PARAM, XSECURE_SHA_STATE_MISMATCH_ERROR, XSecure_ShaFinish, XSecure_ShaLastUpdate, XSecure_ShaStart, XSecure_ShaUpdate, XSecure_ShaValidateModeAndCfgInstance.
int XSecure_ShaLastUpdate(XSecure_Sha *InstancePtr)
This function notifies the SHA driver at the end of the SHA data update.
Typically called before last XSecure_ShaUpdate. InstancePtr Pointer to the XSecure_Sha instance XST_SUCCESS - If last update can be acceptedXSECURE_SHA_INVALID_PARAM - On invalid parameterXSECURE_SHA_STATE_MISMATCH_ERROR - If State mismatch is occurred
References XSECURE_SHA_INVALID_PARAM.
static int XSecure_ShaOperation(u32 SubsystemId, XSecure_Sha *XSecureShaInstPtr, u32 AddrLow, u32 AddrHigh)
This function performs SHA operation based on operation flags provided in IPI payload and returns the result.
SubsystemId Subsystem ID. XSecureShaInstPtr Pointer to the SHA instance AddrLow Lower 32 bit address of XSecure_ShaOpParams structure AddrHigh upper 32 bit address of XSecure_ShaOpParams structure XST_SUCCESS - If the SHA operation is successfulXST_INVALID_PARAM - If XSecureShaInstPtr is NULLXSECURE_ERR_INVALID_ADDR_RANGE - If address range validation failsXST_FAILURE - On failure
int XSecure_ShaIpiHandler(XPlmi_Cmd *Cmd)
This function calls respective IPI handler based on the API_ID.
Cmd is a pointer to the command structure XST_SUCCESS - If the handler execution is successfulXST_INVALID_PARAM - If Cmd is NULL or invalid API IDXST_FAILURE - On failure
References XSECURE_API, XSECURE_API_ID_MASK, XSECURE_API_SHA2_OPERATION, XSECURE_API_SHA3_OPERATION, XSECURE_DEBUG_GENERAL, XSecure_GetSha2Instance, XSecure_GetSha3Instance, XSecure_IpiEventHandling, XSecure_MakeResFree, XSecure_Printf, XSECURE_SHA_0_DEVICE_ID, XSECURE_SHA_1_DEVICE_ID, XSECURE_SHA_INITIALIZED.
static u32 XSecure_BhdrValidation(XSecure_ImageInfo *ImageInfo)
This function validates boot header.
ImageInfo Pointer to XSecure_ImageInfo structure. Returns Status XST_SUCCESS on successful verification.Error code on failure.
static u32 XSecure_DecryptPartition(XSecure_ImageInfo *ImageHdrInfo, u8 *SrcAddr, u8 *KupKey, XSecure_DataAddr *Addr)
This function decrypts the image partition.
ImageHdrInfo Pointer to XSecure_ImageInfo structure SrcAddr Pointer to single partition non-bitstream image KupKey Pointer to User Key Addr Location of the secure image loaded after validation Returns Status XST_SUCCESS on successful verification.Error code on failure.
static u32 XSecure_DataAuthentication(XSecure_AuthParam *AuthParam)
This function performs authentication of a given data.
AuthParam Pointer to auhentication parameter structure. Returns Status XST_SUCCESS on successXST_FAILURE on failure
u32 XSecure_CsuDmaInit(void)
This function is used to initialize the DMA driver.
returns the error code on any error returns XST_SUCCESS on success
References XSECURE_CSUDMA_DEVICEID, XSECURE_ERROR_CSUDMA_INIT_FAIL.
Referenced by Xsecure_GetCsuDma, XSecure_SecureImage, XSecure_Sha3Hash.
XCsuDma * Xsecure_GetCsuDma(void)
This function is used to initialize CsuDma and return CsuDma pointer.
returns reference to a XCsuDma driver instance
References XSecure_CsuDmaInit.
u32 XSecure_Sha3Hash(u32 SrcAddrHigh, u32 SrcAddrLow, u32 SrcSize, u32 Flags)
This function access the xilsecure SHA3 hardware based on the flags provided to calculate the SHA3 hash.
SrcAddrHigh Higher 32-bit of the input or output address. SrcAddrLow Lower 32-bit of the input or output address. SrcSize Size of the data on which hash should be calculated. Flags : inputs for the operation requested BIT(0) - for initializing csudma driver and SHA3, (Here address and size inputs can be NULL) BIT(1) - To call Sha3_Update API which can be called multiple times when data is not contiguous. BIT(2) - to get final hash of the whole updated data. Hash will be overwritten at provided address with 48 bytes. Returns Status XST_SUCCESS on success and error code on failure.
References XSecure_CsuDmaInit, XSECURE_ERROR_CSUDMA_INIT_FAIL, XSECURE_INVALID_FLAG, XSECURE_SHA3_FINAL, XSECURE_SHA3_INIT, XSECURE_SHA3_INIT_FAIL, XSECURE_SHA3_MASK, XSECURE_SHA3_UPDATE_FAIL, XSecure_Sha3Finish, XSECURE_SHA3HASH_UPDATE, XSecure_Sha3Initialize, XSecure_Sha3Start, XSecure_Sha3Update.
Referenced by XSecure_ShaDigest, XSecure_ShaFinish.
u32 XSecure_RsaCore(u32 SrcAddrHigh, u32 SrcAddrLow, u32 SrcSize, u32 Flags)
This is the function to RSA decrypt or encrypt the provided data and load back to memory.
SrcAddrHigh Higher 32-bit Linear memory space from where CSUDMA will read the data SrcAddrLow Lower 32-bit Linear memory space from where CSUDMA will read the data SrcSize Number of bytes to be encrypted or decrypted. Flags Flags for operation, where BIT(0) indicates Encryption/Decryption (0 for RSA Private key Decryption or 1 for RSA Public key Encryption) Returns Status XST_SUCCESS on success and error code on failure. Data to be encrypted/Decrypted + Modulus + Exponent Modulus and Data should always be key size Exponent : private key's exponent is key size while decrypting the signature and 32 bit for public key for encrypting the signature In this API we are not taking exponentiation value.
References XSECURE_DEC, XSECURE_RSA_CORE_OPERATION, XSecure_RsaInitialize, XSecure_RsaPrivateDecrypt, XSecure_RsaPublicEncrypt.
static u32 XSecure_InitAes(u32 AddrHigh, u32 AddrLow)
This function initializes the AES-GCM engine with Key and Iv.
AddrHigh Higher 32 bit address of the XSecure_AesParams structure. AddrLow Lower 32 bit address of the XSecure_AesParams structure. Returns Status XST_SUCCESS on successError code on failure
static u32 XSecure_DecryptData(u32 AddrHigh, u32 AddrLow)
This function performs the AES decryption of the data-blob.
AddrHigh Higher 32 bit address of the XSecure_AesParams structure. AddrLow Lower 32 bit address of the XSecure_AesParams structure. Returns Status XST_SUCCESS on successError code on failure
static u32 XSecure_EncryptData(u32 AddrHigh, u32 AddrLow)
This function performs the AES encryption of the data-blob.
AddrHigh Higher 32 bit address of the XSecure_AesParams structure. AddrLow Lower 32 bit address of the XSecure_AesParams structure. Returns Status XST_SUCCESS on successError code on failure
u32 XSecure_AesOperation(u32 AddrHigh, u32 AddrLow)
This function checks for flags field of the XSecure_AesParams struct and resolves weather the request is encryption or decryption.
AddrHigh Higher 32 bit address of the XSecure_AesParams structure. AddrLow Lower 32 bit address of the XSecure_AesParams structure. Returns Status XST_SUCCESS on successError code on failure
References XSECURE_AES_KUP_KEY, XSECURE_DEC, XSECURE_DEC_WRONG_KEY_SOURCE, XSECURE_ENC, XSECURE_INVALID_FLAG, XSECURE_SIZE_ERR, XSECURE_WORD_LEN.
u32 XSecure_DataAuth(u8 *Signature, XSecure_RsaKey *KeyInst, u8 *Hash)
This function performs authentication of data by encrypting the signature with provided key and compares with hash of the data and returns success or failure.
Signature Pointer to the RSA signature of the data KeyInst Pointer to XSecure_RsaKey structure. Hash Pointer to the hash of the data to be authenticated. Returns Status XST_SUCCESS on successError code on failure
References XSecure_RsaKey::Exponent, XSecure_RsaKey::Exponentiation, XSecure_RsaKey::Modulus, XSECURE_AUTH_FAILURE, XSECURE_HASH_TYPE_SHA3, XSECURE_MOD_LEN, XSECURE_RSA_ENCRYPT_ERR, XSECURE_RSA_INIT_ERR, XSecure_RsaInitialize, XSecure_RsaPublicEncrypt, XSecure_RsaSignVerification, XSECURE_VERIFY_ERR.
u32 XSecure_PartitionAuthentication(XCsuDma *CsuDmaInstPtr, u8 *Data, u32 Size, u8 *AuthCertPtr)
This function performs authentication of a partition of an image.
CsuDmaInstPtr Pointer to the CSU DMA instance. Data Pointer to partition to be authenticated. Size Represents the size of the partition. AuthCertPtr Pointer to authentication certificate of the partition. Returns Status XST_SUCCESS on successError code on failure
References XSECURE_AUTH_CERT_PARTSIG_OFFSET, XSECURE_AUTH_FAILURE.
Referenced by XSecure_AuthenticationHeaders, XSecure_SecureImage.
static u32 XSecure_BhdrAuthentication(XCsuDma *CsuDmaInstPtr, u8 *Data, u32 Size, u8 *AuthCertPtr)
This function performs authentication of a boot header of the image.
CsuDmaInstPtr Pointer to the CSU DMA instance. Data pointer to boot header of the image. Size Size of the boot header. AuthCertPtr Pointer to authentication certificate. Returns Status XST_SUCCESS on successXST_FAILURE on failure
u32 XSecure_MemCopy(void *DestPtr, void *SrcPtr, u32 Size)
This function copies the data from specified source to destination using CSU DMA.
DestPtr Pointer to the destination address. SrcPtr Pointer to the source address. Size Data size to be copied. Returns Status XST_SUCCESS on successXST_FAILURE on failure
References XSecure_SssDmaLoopBack, XSecure_SssInitialize.
Referenced by XSecure_AuthenticationHeaders, XSecure_SecureImage.
u32 XSecure_VerifySpk(u8 *AcPtr, u32 EfuseRsaenable)
This function verifies SPK by authenticating SPK with PPK, also checks either SPK is revoked or not.if it is not boot header authentication.
AcPtr Pointer to the authentication certificate. EfuseRsaenable Input variable which holds efuse RSA authentication or boot header authentication (0 for Boot header authentication or 1 for RSA authentication) Returns Status XST_SUCCESS on successError code on failure
References XSecure_IsRsaEnabled, XSecure_SpkAuthentication, XSecure_SpkRevokeCheck.
Referenced by XSecure_SecureImage.
u32 XSecure_AuthenticationHeaders(u8 *StartAddr, XSecure_ImageInfo *ImageInfo)
This function authenticates the single partition image's boot header and image header, also copies all the required details to the ImageInfo pointer.
StartAddr Pointer to the single partition image. ImageInfo Pointer to XSecure_ImageInfo structure. Returns Status XST_SUCCESS on successError code on failure XSECURE_AUTH_NOT_ENABLED - represents image is not authenticated. Copies the header and authentication certificate to internal buffer.
References XSecure_PartitionHeader::NextPartitionOffset, XSECURE_AC_IMAGE_HDR_OFFSET, XSECURE_ARRAY_LENGTH, XSECURE_AUTH_CERT_MIN_SIZE, XSECURE_AUTH_ISCOMPULSORY, XSECURE_AUTH_NOT_ENABLED, XSECURE_BOOT_HDR_MAX_SIZE, XSECURE_BUFFER_SIZE, XSECURE_DEC_WRONG_KEY_SOURCE, XSECURE_ENC_ISCOMPULSORY, XSECURE_IMAGE_HDR_OFFSET, XSECURE_IMAGE_HEADER_SIZE_ERR, XSECURE_IMAGE_SYNC_WORD_OFFSET, XSECURE_IMAGE_WITH_MUL_PARTITIONS, XSECURE_IMG_HDR_FAIL, XSECURE_INVALID_IMAGE_ERROR, XSecure_IsEncOnlyEnabled, XSecure_IsRsaEnabled, XSECURE_IV_LEN, XSECURE_IV_OFFSET, XSECURE_KEY_SOURCE_OFFSET, XSECURE_KEY_SRC_BBRAM, XSECURE_KEY_SRC_BLACK_BH, XSECURE_KEY_SRC_GREY_BH, XSecure_MemCopy, XSecure_PartitionAuthentication, XSECURE_PH_ATTR_ENC_ENABLE, XSECURE_PH_IV_MASK, XSECURE_PH_OFFSET, XSECURE_PH_TABLE_OFFSET, XSECURE_WORD_LEN.
Referenced by XSecure_SecureImage.
u32 XSecure_SecureImage(u32 AddrHigh, u32 AddrLow, u32 KupAddrHigh, u32 KupAddrLow, XSecure_DataAddr *Addr)
This function process the secure image of single partition created by bootgen.
AddrHigh Higher 32-bit linear memory space of single partition non-bitstream image. AddrLow Lower 32-bit linear memory space of single partition non-bitstream image. KupAddrHigh Higher 32-bit linear memory space of KUP key. KupAddrLow lower 32-bit linear memory space of KUP key. Addr Location of the secure image loaded after validation. Returns Status XST_SUCCESS on successError code on failure
References XSECURE_AUTH_CERT_MIN_SIZE, XSECURE_AUTH_NOT_ENABLED, XSecure_AuthenticationHeaders, XSECURE_BUFFER_SIZE, XSecure_CsuDmaInit, XSECURE_DEC_WRONG_KEY_SOURCE, XSECURE_ENC_ISCOMPULSORY, XSECURE_ERROR_CSUDMA_INIT_FAIL, XSECURE_HDR_NOAUTH_PART_AUTH, XSecure_IsEncOnlyEnabled, XSECURE_ISNOT_SECURE_IMAGE, XSECURE_IV_LEN, XSECURE_IV_OFFSET, XSECURE_KEY_SOURCE_OFFSET, XSECURE_KEY_SRC_BBRAM, XSECURE_KEY_SRC_BLACK_BH, XSECURE_KEY_SRC_GREY_BH, XSECURE_KEY_SRC_KUP, XSecure_MemCopy, XSECURE_PARTITION_FAIL, XSecure_PartitionAuthentication, XSECURE_PH_ATTR_AUTH_ENABLE, XSECURE_PH_ATTR_ENC_ENABLE, XSECURE_PH_IV_MASK, XSECURE_PH_TABLE_OFFSET, XSECURE_PPK_SIZE, XSecure_VerifySpk, XSECURE_WORD_LEN, XSECURE_WORD_SHIFT.
u32 XSecure_IsRsaEnabled(void)
This function tells whether RSA authentication is enabled or not.
Returns Status XSECURE_ENABLED if RSA bit of efuse is programmedXSECURE_NOTENABLED if RSA bit of efuse is not programmed.
References XSECURE_EFUSE_SEC_CTRL, XSECURE_ENABLED, XSECURE_NOTENABLED.
Referenced by XSecure_AuthenticationHeaders, XSecure_VerifySpk.
u32 XSecure_IsEncOnlyEnabled(void)
This function tells whether encrypt only is enabled or not.
Returns Status XSECURE_ENABLED if enc_only bit of efuse is programmedXSECURE_NOTENABLED if enc_only bit of efuse is not programmed
References XSECURE_EFUSE_SEC_CTRL, XSECURE_ENABLED, XSECURE_NOTENABLED.
Referenced by XSecure_AuthenticationHeaders, XSecure_SecureImage.
u32 XSecure_PpkVerify(XCsuDma *CsuDmaInstPtr, u8 *AuthCert)
This function verifies the PPK hash with PPK programmed on efuse.
CsuDmaInstPtr Pointer to CSU DMA instance. AuthCert Pointer to authentication certificate. Returns Status XST_SUCCESS on successful verification.Error code on failure.
References XSECURE_AC_PPK_OFFSET, XSECURE_AH_ATTR_PPK_SEL_MASK, XSECURE_AH_ATTR_PPK_SEL_SHIFT, XSECURE_EFUSE_PPK0, XSECURE_EFUSE_PPK1, XSECURE_EFUSE_SEC_CTRL, XSECURE_HASH_TYPE_SHA3, XSECURE_KEY_SIZE, XSECURE_PPK_ERR, XSECURE_REVOKE_ERR, XSECURE_SEL_ERR, XSECURE_SHA3_INIT_FAIL, XSECURE_SHA3_PADSELECT_ERR, XSecure_Sha3Digest, XSecure_Sha3Initialize, XSecure_Sha3PadSelection, XSECURE_VERIFY_ERR, XSECURE_WORD_LEN.
u32 XSecure_SpkAuthentication(XCsuDma *CsuDmaInstPtr, u8 *AuthCert, u8 *Ppk)
This function authenticates SPK with provided PPK or PPK from authentication certificate.
CsuDmaInstPtr Pointer to CSU DMA instance. AuthCert Pointer to authentication certificate. Ppk Pointer to the PPK key, or NULL to use PPK from provided * authentication certificate. Returns Status XST_SUCCESS on successful verification.Error code on failure.
References XSECURE_AH_ATTR_SPK_ID_FUSE_SEL_MASK, XSECURE_AH_ATTR_SPKID_FUSESEL_SHIFT, XSECURE_AUTH_HEADER_SIZE, XSECURE_HASH_TYPE_SHA3, XSECURE_INVALID_EFUSE_SELECT, XSECURE_PPK_MOD_EXT_SIZE, XSECURE_PPK_MOD_SIZE, XSECURE_PPK_SIZE, XSECURE_RSA_AC_ALIGN, XSECURE_RSA_ENCRYPT_ERR, XSECURE_RSA_INIT_ERR, XSecure_RsaInitialize, XSecure_RsaPublicEncrypt, XSecure_RsaSignVerification, XSECURE_SHA3_INIT_FAIL, XSecure_Sha3Finish, XSecure_Sha3Initialize, XSecure_Sha3PadSelection, XSecure_Sha3Start, XSecure_Sha3Update, XSECURE_SPK_ERR, XSECURE_SPK_SIG_SIZE, XSECURE_SPK_SIZE, XSECURE_SPKID_EFUSE, XSECURE_USER_EFUSE, XSECURE_VERIFY_ERR.
Referenced by XSecure_VerifySpk.
u32 XSecure_SpkRevokeCheck(u8 *AuthCert)
This function checks whether SPK is been revoked or not.
AuthCert Pointer to authentication certificate. Returns Status XST_SUCCESS on successful verification.Error code on failure.
References XSECURE_AC_SPKID_OFFSET, XSECURE_AH_ATTR_SPK_ID_FUSE_SEL_MASK, XSECURE_AH_ATTR_SPKID_FUSESEL_SHIFT, XSECURE_EFUSE_SPKID, XSECURE_INVALID_EFUSE_SELECT, XSECURE_OUT_OF_RANGE_USER_EFUSE_ERROR, XSECURE_REVOKE_ERR, XSECURE_SPK_ERR, XSECURE_SPKID_EFUSE, XSECURE_USER_EFUSE, XSECURE_USER_EFUSE_MAX_VALUE, XSECURE_USER_EFUSE_MIN_VALUE, XSECURE_USER_EFUSE_START_ADDR, XSECURE_WORD_LEN, XSECURE_WORD_SHIFT.
Referenced by XSecure_VerifySpk.
int main(void)
Main function to call the SecureAesExample.
This example illustrates the usage of RSA APIs to encrypt or decrypt the signature.Main function to call the SecureAesExample function.Main function to call the SecureShaExample.Main function to call the SecureRsaExample. None XST_FAILURE if the Test Failed . None None XST_FAILURE if the boot image authentication Failed . None None XST_FAILURE if the SHA calculation failed. None None XST_SUCCESS if example runs successfully ErrorCode if the example fails. XST_SUCCESS if the boot image authentication is successful. ErrorCode if the boot image authentication Failed. XST_FAILURE if the SHA calculation failed.
References SecureAesExample.
static u32 SecureRsaExample(void)
This function authenticates boot image located in DDR using RSA-4096 algorithm.
The decrypted hash is matched against the calculated boot image hash. The purpose of this function is to illustrate how to use the XSecure_Rsa driver. XST_FAILURE if the authentication failed. None.//! [RSA example]
XSECURE_TYPE_PMC_DMA0
DMA0 type.
XSECURE_SHA2_START_NIST_PADDING_MASK
NIST start padding mask.
XSECURE_SHA3_START_NIST_PADDING_MASK
NIST start padding mask.
XSECURE_SHAKE_START_NIST_PADDING_MASK
NIST start padding mask.
XSECURE_SHA3_END_NIST_PADDING_MASK
NIST end padding mask.
XSECURE_MAX_PADDING_LENGTH
Maximum padding length for SHA.
XSECURE_SHA2_256_LENGTH_FIELD_SIZE
SHA2-256 length field size.
XSECURE_SHA2_384_512_LENGTH_FIELD_SIZE
SHA2 384 and 512 length field size.
XSECURE_SHA_PADDING_BYTE
Padding byte for SHA.
XSECURE_BYTES_TO_BITS_CONVERSION_SHIFT
Bytes to bits conversion value.
XSECURE_SHA2_384_512_BLOCK_LEN
SHA2 384 and 512 block length.
Referenced by XSecure_ShaGetBlockLen.
XSECURE_SHA2_256_BLOCK_LEN
SHA2 256 block length.
Referenced by XSecure_ShaGetBlockLen.
XSECURE_SHA3_384_BLOCK_LEN
SHA3 384 block length.
Referenced by XSecure_ShaGetBlockLen.
XSECURE_SHAKE_SHA3_256_BLOCK_LEN
SHAKE SHA3 256 block length.
Referenced by XSecure_ShaGetBlockLen.
XSECURE_SHA3_512_BLOCK_LEN
SHA3 512 block length.
Referenced by XSecure_ShaGetBlockLen.
XSECURE_ONE_BYTE_SHIFT_VALUE
One byte shift value for an integer.
XSECURE_LSB_MASK_VALUE
Mask to extract least significant byte from integer values.
XSECURE_BIG_ENDIAN_BYTE_START
Start index for big-endian byte processing.
XSECURE_SHA_NONE
For invalid SHA operation flag checks.
XSECURE_SHA_START
Operation flags for SHA start.
XSECURE_SHA_UPDATE
Operation flags for SHA update.
XSECURE_SHA_FINISH
Operation flags for SHA finish.
XSECURE_SHA_VALID_OP_FLAGS
Operation flags for all valid SHA operations.
XSECURE_AES
Flag indicates AES.
XSECURE_RSA
Flag indicates RSA.
XSECURE_RSA_AES
Flag indicates both RSA and AES.
XSECURE_SHA3_INIT
SHA3 Initialization.
Referenced by XSecure_Sha3Hash.
XSECURE_SHA3HASH_UPDATE
SHA3 hash update.
Referenced by XSecure_Sha3Hash.
XSECURE_SHA3_FINAL
SHA3 final.
Referenced by XSecure_Sha3Hash.
XSECURE_SHA3_MASK
SHA3 mask.
Referenced by XSecure_Sha3Hash.
XSECURE_SPKID_EFUSE
SPK ID eFUSE.
Referenced by XSecure_SpkAuthentication, XSecure_SpkRevokeCheck.
XSECURE_USER_EFUSE
User eFuse.
Referenced by XSecure_SpkAuthentication, XSecure_SpkRevokeCheck.
XSECURE_USER_EFUSE_MIN_VALUE
Minimum value of User eFuse.
Referenced by XSecure_SpkRevokeCheck.
XSECURE_USER_EFUSE_MAX_VALUE
Maximum value of User eFuse.
Referenced by XSecure_SpkRevokeCheck.
XSECURE_ENC
Encryption.
Referenced by XSecure_AesOperation.
XSECURE_DEC
Decryption.
Referenced by XSecure_AesOperation, XSecure_RsaCore.
XSECURE_AES_KUP_KEY
AES kup key.
Referenced by XSecure_AesKeyZeroize, XSecure_AesOperation.
XSECURE_RSA_CORE_OPERATION
RSA core operation.
Referenced by XSecure_RsaCore.
XSECURE_RSA_KEY_SELECT
RSA key select.
XSECURE_MASK
Flag indicates both RSA and AES.
XSECURE_KEY_STR_LEN
Key string length.
XSECURE_IV_STR_LEN
IV string length.
XSECURE_KEY_LEN
Key length.
XSECURE_IV_LEN
IV length.
Referenced by XSecure_AuthenticationHeaders, XSecure_SecureImage.
XSECURE_GCM_TAG_LEN
GCM tag length.
XSECURE_WORD_LEN
Word length.
XSECURE_MAX_NIBBLES
Maximum nibbles.
XSECURE_WORD_SHIFT
Word shift.
Referenced by XSecure_SecureImage, XSecure_SpkRevokeCheck.
XSECURE_ARRAY_LENGTH
Array length.
Referenced by XSecure_AuthenticationHeaders.
XSECURE_ERROR_CSUDMA_INIT_FAIL
CSUDMA initialization fail error.
Referenced by XSecure_CsuDmaInit, XSecure_SecureImage, XSecure_Sha3Hash.
XSECURE_STRING_INVALID_ERROR
Invalid string error.
XSECURE_INVALID_FLAG
Invalid flag.
Referenced by XSecure_AesOperation, XSecure_Sha3Hash.
XSECURE_ISNOT_SECURE_IMAGE
Non-secure Image flag.
Referenced by XSecure_SecureImage.
XSECURE_SHA3_INIT_FAIL
SHA3 initialization failure.
Referenced by XSecure_PpkVerify, XSecure_Sha3Hash, XSecure_SpkAuthentication.
XSECURE_SIZE_ERR
Size error.
Referenced by XSecure_AesOperation.
XSECURE_SEL_ERR
Selection error.
Referenced by XSecure_PpkVerify.
XSECURE_REVOKE_ERR
Revoke error.
Referenced by XSecure_PpkVerify, XSecure_SpkRevokeCheck.
XSECURE_VERIFY_ERR
Verify error.
Referenced by XSecure_DataAuth, XSecure_PpkVerify, XSecure_SpkAuthentication.
XSECURE_RSA_INIT_ERR
RSA initialization error.
Referenced by XSecure_DataAuth, XSecure_SpkAuthentication.
XSECURE_RSA_ENCRYPT_ERR
RSA encrypt error.
Referenced by XSecure_DataAuth, XSecure_SpkAuthentication.
XSECURE_SHA3_PADSELECT_ERR
SHA3 padding selection error.
Referenced by XSecure_PpkVerify.
XSECURE_IMAGE_WITH_MUL_PARTITIONS
Image with multiple partitions.
Referenced by XSecure_AuthenticationHeaders.
XSECURE_AUTH_ISCOMPULSORY
Authentication is compulsory.
Referenced by XSecure_AuthenticationHeaders.
XSECURE_ENC_ISCOMPULSORY
Encryption is compulsory.
Referenced by XSecure_AuthenticationHeaders, XSecure_SecureImage.
XSECURE_BHDR_AUTH_NOT_ALLOWED
Boot header authentication not allowed.
XSECURE_ONLY_BHDR_AUTH_ALLOWED
Only boot header authentication is allowed.
XSECURE_HDR_NOAUTH_PART_AUTH
No header authentication only partition authentication.
Referenced by XSecure_SecureImage.
XSECURE_DEC_WRONG_KEY_SOURCE
Decryption wrong key source.
Referenced by XSecure_AesOperation, XSecure_AuthenticationHeaders, XSecure_SecureImage.
XSECURE_KUP_KEY_NOT_PROVIDED
Kup key not provided.
XSECURE_KUP_KEY_NOT_REQUIRED
Kup key not required.
XSECURE_INVALID_EFUSE_SELECT
Invalid eFuse selection.
Referenced by XSecure_SpkAuthentication, XSecure_SpkRevokeCheck.
XSECURE_OUT_OF_RANGE_USER_EFUSE_ERROR
Out of range user eFuse error.
Referenced by XSecure_SpkRevokeCheck.
XSECURE_INVALID_IMAGE_ERROR
Invalid image error.
Referenced by XSecure_AuthenticationHeaders.
XSECURE_SHA3_UPDATE_FAIL
SHA3 update failure.
Referenced by XSecure_Sha3Hash.
XSECURE_IMAGE_HEADER_SIZE_ERR
Image header size error.
Referenced by XSecure_AuthenticationHeaders.
XSECURE_AES_ERROR
AES error.
XSECURE_RSA_INVALID_PARAM_RESERVED
Invalid reserved RSA parameter.
XSECURE_AUTH_NOT_ENABLED
Authentication not enabled.
Referenced by XSecure_AuthenticationHeaders, XSecure_SecureImage.
XSECURE_PPK_ERR
PPK error.
Referenced by XSecure_PpkVerify.
XSECURE_SPK_ERR
SPK error.
Referenced by XSecure_SpkAuthentication, XSecure_SpkRevokeCheck.
XSECURE_AUTH_FAILURE
Authentication failure.
Referenced by XSecure_DataAuth, XSecure_PartitionAuthentication.
XSECURE_AES_DECRYPTION_FAILURE
AES decryption failure.
XSECURE_BOOT_HDR_FAIL
Boot header failure.
XSECURE_IMG_HDR_FAIL
Image header failure.
Referenced by XSecure_AuthenticationHeaders.
XSECURE_PARTITION_FAIL
Partition failure.
Referenced by XSecure_SecureImage.
XSECURE_CSUDMA_DEVICEID
CSUDMA device Id.
Referenced by XSecure_CsuDmaInit.
XSECURE_MOD_LEN
Module length.
Referenced by XSecure_DataAuth.
XSECURE_PH_ATTR_AUTH_ENABLE
Attribute of authentication enabled partition header.
Referenced by XSecure_SecureImage.
XSECURE_PH_ATTR_ENC_ENABLE
Attribute of encryption enabled partition header.
Referenced by XSecure_AuthenticationHeaders, XSecure_SecureImage.
XSECURE_AH_ATTR_PPK_SEL_MASK
PPK select mask of authentication header.
Referenced by XSecure_PpkVerify.
XSECURE_AH_ATTR_PPK_SEL_SHIFT
PPK select shift of authentication header.
Referenced by XSecure_PpkVerify.
XSECURE_AH_ATTR_SPK_ID_FUSE_SEL_MASK
SPKID eFUSE select mask of authentication header.
Referenced by XSecure_SpkAuthentication, XSecure_SpkRevokeCheck.
XSECURE_AH_ATTR_SPKID_FUSESEL_SHIFT
SPKID eFUSE select shift of authentication header.
Referenced by XSecure_SpkAuthentication, XSecure_SpkRevokeCheck.
XSECURE_AC_SPKID_OFFSET
Offset of SPKID authentication certificate.
Referenced by XSecure_SpkRevokeCheck.
XSECURE_AC_PPK_OFFSET
Offset of PPK authentication certificate.
Referenced by XSecure_PpkVerify.
XSECURE_AC_SPK_OFFSET
Offset of SPK authentication certificate.
XSECURE_AC_SPK_SIG_OFFSET
Offset of SPK signature authentication certificate.
XSECURE_KEY_SIZE
Key size.
Referenced by main, XSecure_PpkVerify.
XSECURE_ENABLED
Enabled.
Referenced by XSecure_IsEncOnlyEnabled, XSecure_IsRsaEnabled.
XSECURE_NOTENABLED
Not enabled.
Referenced by XSecure_IsEncOnlyEnabled, XSecure_IsRsaEnabled.
XSECURE_EFUSE_BASEADDR
eFuse base address
XSECURE_USER_EFUSE_START_ADDR
User eFuse 0.
Referenced by XSecure_SpkRevokeCheck.
XSECURE_EFUSE_PPK0
Register PPK0_0.
Referenced by XSecure_PpkVerify.
XSECURE_EFUSE_PPK1
Register PPK1_0.
Referenced by XSecure_PpkVerify.
XSECURE_EFUSE_SPKID
Register SPK ID.
Referenced by XSecure_SpkRevokeCheck.
XSECURE_SPK_SIZE
SPK size.
Referenced by XSecure_SpkAuthentication.
XSECURE_PPK_SIZE
PPK size.
Referenced by XSecure_SecureImage, XSecure_SpkAuthentication.
XSECURE_PPK_MOD_SIZE
PPK module size.
Referenced by XSecure_SpkAuthentication.
XSECURE_PPK_MOD_EXT_SIZE
PPK module extension size.
Referenced by XSecure_SpkAuthentication.
XSECURE_SPK_MOD_SIZE
SPK module size.
XSECURE_SPK_MOD_EXT_SIZE
SPK module extension size.
XSECURE_SPK_SIG_SIZE
SPK signature size.
Referenced by XSecure_SpkAuthentication.
XSECURE_BHDR_SIG_SIZE
Boot header signature size.
XSECURE_PARTITION_SIG_SIZE
partition signature size
XSECURE_RSA_AC_ALIGN
Aligned RSA authentication certificate.
Referenced by XSecure_SpkAuthentication.
XSECURE_SPKID_AC_ALIGN
Aligned SPKID authentication certificate.
XSECURE_AUTH_HEADER_SIZE
Authentication header size.
Referenced by XSecure_SpkAuthentication.
XSECURE_AUTH_CERT_USER_DATA
Authentication certificate of user data.
XSECURE_AUTH_CERT_MIN_SIZE
Minimum size of authentication certificate.
Referenced by XSecure_AuthenticationHeaders, XSecure_SecureImage.
XSECURE_AUTH_CERT_BHDRSIG_OFFSET
Offset of authentication certificate boot header signature.
XSECURE_AUTH_CERT_PARTSIG_OFFSET
Offset of authentication certificate partition signature.
Referenced by XSecure_PartitionAuthentication.
XSECURE_BOOT_HDR_MIN_SIZE
Minimum size of boot header.
XSECURE_BOOT_HDR_MAX_SIZE
When boot header contains PUF helper data.
Referenced by XSecure_AuthenticationHeaders.
XSECURE_BUFFER_SIZE
Buffer size.
Referenced by XSecure_AuthenticationHeaders, XSecure_SecureImage.
XSECURE_IV_OFFSET
IV offset.
Referenced by XSecure_AuthenticationHeaders, XSecure_SecureImage.
XSECURE_PH_TABLE_OFFSET
Partition header table offset.
Referenced by XSecure_AuthenticationHeaders, XSecure_SecureImage.
XSECURE_IMAGE_HDR_OFFSET
Image header offset.
Referenced by XSecure_AuthenticationHeaders.
XSECURE_IMAGE_ATTR_OFFSET
Image attribute offset.
XSECURE_KEY_SOURCE_OFFSET
Key source offset.
Referenced by XSecure_AuthenticationHeaders, XSecure_SecureImage.
XSECURE_IMG_ATTR_BHDR_MASK
Boot header mask.
XSECURE_IMG_ATTR_PUFHD_MASK
PUFHd mask.
XSECURE_PH_OFFSET
Partition header offset.
Referenced by XSecure_AuthenticationHeaders.
XSECURE_AC_IMAGE_HDR_OFFSET
Authentication certificate image header offset.
Referenced by XSecure_AuthenticationHeaders.
XSECURE_IMAGE_SYNC_WORD_OFFSET
Image synchronize word offset.
Referenced by XSecure_AuthenticationHeaders.
XSECURE_PH_IV_MASK
Partition header IV mask.
Referenced by XSecure_AuthenticationHeaders, XSecure_SecureImage.
XSECURE_KEY_SRC_KUP
Kup key source.
Referenced by XSecure_SecureImage.
XSECURE_KEY_SRC_BBRAM
BBRAM key source.
Referenced by XSecure_AuthenticationHeaders, XSecure_SecureImage.
XSECURE_KEY_SRC_BLACK_BH
Boot header black key source.
Referenced by XSecure_AuthenticationHeaders, XSecure_SecureImage.
XSECURE_KEY_SRC_GREY_BH
Boot header grey key source.
Referenced by XSecure_AuthenticationHeaders, XSecure_SecureImage.
XSECURE_BHDR_PH_OFFSET
XSECURE_PH_PARTITION_OFFSET
XSECURE_PH_PARTITION_LEN_OFFSET
XSECURE_PH_PARTITION_IV_OFFSET
XSECURE_PH_PARTITION_IV_MASK
XSECURE_WORD_MUL
XSECURE_IV_INDEX
XSECURE_PPK_SIZE
XSECURE_SPK_SIZE
XSECURE_SPK_SIG_SIZE
XSECURE_BHDR_SIG_SIZE
XSECURE_RSA_KEY_LEN
XSECURE_RSA_BIG_ENDIAN
XSECURE_RSA_AC_ALIGN
XSECURE_AUTH_HEADER_SIZE
XSECURE_AUTH_CERT_USER_DATA
XSECURE_AUTH_CERT_MIN_SIZE
XSECURE_AUTH_CERT_MAX_SIZE
XSECURE_PARTIAL_AC_SIZE
XSECURE_IMAGE_VERIF_ERROR