spartanup/xsecure_plat.c
XSECURE_ADDR_HIGH_SHIFT
High address shift for 64-bit addresses.
Referenced by XSecure_AesPlatPmcDmaCfgAndXfer.
const XSecure_AesKeyLookup AesKeyLookupTbl[XSECURE_MAX_KEY_SOURCES][XSECURE_MAX_KEY_SOURCES]
TRNG related macros for SPARTANUPLUSAES1 device.
const u8 XSecure_SssLookupTable[XSECURE_SSS_MAX_SRCS][XSECURE_SSS_MAX_SRCS][XSECURE_SSS_MAX_SRCS][XSECURE_SSS_MAX_SRCS]
const XSecure_ShaConfig ShaConfigTable[XSECURE_SHA_NUM_OF_INSTANCES][XSECURE_SHA_NUM_OF_INSTANCES]
u32 XSecure_SssMask(XSecure_SssSrc InputSrc, XSecure_SssSrc OutputSrc, u32 Value)
This function masks the secure stream switch value.
InputSrc Input source to be selected for the resource OutputSrc Output source to be selected for the resource Value Register Value of SSS cfg register Mask - Mask value of corresponding InputSrc and OutputSrc InputSrc, OutputSrc are of type XSecure_SssSrc InputSrc Input source to be selected for the resource OutputSrc Output source to be selected for the resource Value Register Value of SSS cfg register Mask Mask value of corresponding InputSrc and OutputSrc InputSrc, OutputSrc are of type XSecure_SssSrc InputSrc Input source to be selected for the resource OutputSrc Output source to be selected for the resource Value Register Value of SSS cfg register Mask value of corresponding InputSrc and OutputSrc InputSrc, OutputSrc are of type XSecure_SssSrc InputSrc Input source to be selected for the resource. OutputSrc Output source to be selected for the resource. Value Register Value of SSS cfg register. Mask Mask value of corresponding InputSrc and OutputSrc InputSrc, OutputSrc are of type XSecure_SssSrc InputSrc Input source to be selected for the resource. OutputSrc Output source to be selected for the resource. Value Register Value of SSS cfg register. Mask Mask value of corresponding InputSrc and OutputSrc. InputSrc, OutputSrc are of type XSecure_SssSrc.
References XSECURE_SSS_AES_DMA0_VAL, XSECURE_SSS_AES_MASK, XSECURE_SSS_DMA0, XSECURE_SSS_DMA0_MASK, XSECURE_SSS_SBI_DMA0_VAL, XSECURE_SSS_SBI_MASK, XSECURE_SSS_SHA_DMA0_VAL, XSECURE_SSS_SHA_MASK.
Referenced by XSecure_SssAes, XSecure_SssSha.
int XSecure_AesValidateSize(u32 Size, u8 IsLastChunk)
This function validates the size.
This function validates whether all the intermediate updates to AES engine are Q-WORD aligned or not.This function validates if intermediate updates are 16-bytes aligned or not.This function is not applicable for Versal_2Ve_2Vm.This function validates whether size of the data is word aligned and if it is the last chunk size should be qword aligned. Size Size of data in bytes. IsLastChunk Last chunk indication XST_SUCCESS on successful validationError code on failure Size Size of data in bytes. IsLastChunk Last chunk indication XST_SUCCESS On successful valdationXSECURE_AES_UNALIGNED_SIZE_ERROR If unaligned size is given as input Size Size of data in bytes. IsLastChunk Last chunk indication XST_SUCCESS - On successXSECURE_AES_UNALIGNED_SIZE_ERROR - Size is not 16-byte aligned for non-last chunk Size Size of data in bytes. IsLastChunk Last chunk indication. XST_SUCCESS On successful valdation.XSECURE_AES_UNALIGNED_SIZE_ERROR If unaligned size is given as input. Size Size of data in bytes. IsLastChunk Last chunk indication. XST_SUCCESS If update is 16-bytes aligned.XSECURE_AES_UNALIGNED_SIZE_ERROR If update is not 16-bytes aligned. Size Size of data in bytes. IsLastChunk Last chunk indication XST_SUCCESS If the data is q-word aligned for intermediate updates XST_FAILURE If the data is not q-word aligned for intermediate updates
References XSECURE_AES_UNALIGNED_SIZE_ERROR, XSECURE_QWORD_SIZE, XSECURE_WORD_SIZE.
int XSecure_AesPlatPmcDmaCfgAndXfer(XPmcDma *PmcDmaPtr, const XSecure_AesDmaCfg *AesDmaCfg, u32 Size, UINTPTR BaseAddress)
This function configures the PMC DMA channels and transfers data.
This function sets the SRC and DEST channel endianness configurations of PMC DMA and transfers data. PmcDmaPtr Pointer to the XPmcDma instance. AesDmaCfg DMA SRC and DEST channel configuration Size Size of data in bytes. BaseAddress Not applicable for versal XST_SUCCESS on successful configurationError code on failure PmcDmaPtr Pointer to the XPmcDma instance. AesDmaCfg DMA SRC and DEST channel configuration Size Size of data in bytes. BaseAddress Not applicable for versal XST_SUCCESS On successful configurationXSECURE_AES_INVALID_PARAM If any input parameter is invalidXST_FAILURE On failure PmcDmaPtr Pointer to the XPmcDma instance. AesDmaCfg DMA SRC and DEST channel configuration. Size Size of data in bytes. BaseAddress Not applicable for versal_2vp. XST_SUCCESS On successful configurationXSECURE_AES_INVALID_PARAM If any input parameter is invalidXST_FAILURE On failure
References XSecure_AesDmaCfg::DestChannelCfg, XSecure_AesDmaCfg::DestDataAddr, XSecure_AesDmaCfg::IsLastChunkDest, XSecure_AesDmaCfg::IsLastChunkSrc, XSecure_AesDmaCfg::SrcChannelCfg, XSecure_AesDmaCfg::SrcDataAddr, XSECURE_ADDR_HIGH_SHIFT, XSECURE_AES_INVALID_PARAM, XSECURE_AES_NO_CFG_DST_DMA, XSECURE_WORD_SIZE.
void XSecure_AesPmcDmaCfgEndianness(XPmcDma *InstancePtr, XPmcDma_Channel Channel, u8 EndianType)
This is a helper function to enable/disable byte swapping feature of PMC DMA.
InstancePtr Pointer to the XPmcDma instance Channel Channel Type (XPMCDMA_SRC_CHANNEL or XPMCDMA_DST_CHANNEL) EndianType 1 to enable byte swapping, 0 to disable byte swapping InstancePtr Pointer to the XPmcDma instance. Channel Channel Type (XPMCDMA_SRC_CHANNEL or XPMCDMA_DST_CHANNEL) EndianType 1 to enable byte swapping, 0 to disable byte swapping InstancePtr Pointer to the XPmcDma instance Channel Channel type (XPMCDMA_SRC_CHANNEL or XPMCDMA_DST_CHANNEL) EndianType Endianness type: 1 to enable byte swapping, 0 to disable byte swapping
References XSecure_AssertVoid.
Referenced by XSecure_AesEncryptUpdate, XSecure_AesPlatPmcDmaCfgAndXfer.
int XSecure_ShaValidateModeAndCfgInstance(XSecure_Sha *const InstancePtr, XSecure_ShaMode ShaMode)
This function validates the SHA Mode and initialize SHA instance.
InstancePtr Pointer to the SHA instance. ShaMode SHA Mode. XST_SUCCESS - Upon Success. XST_FAILURE - Upon Failure. XSECURE_SHA_INVALID_MODE_ERROR InstancePtr Pointer to the SHA instance. ShaMode SHA Mode XST_SUCCESS - Upon successXSECURE_SHA_INVALID_PARAM - Invalid SHA mode provided InstancePtr Pointer to the SHA instance. ShaMode SHA Mode. XST_SUCCESS Upon Success.XST_FAILURE Upon Failure.XSECURE_SHA_INVALID_MODE_ERROR In case of invalid sha mode config.
References SHA256, SHA384, SHA512, XSecure_ShaPlatConfig::ShaDigestSize, SHAKE256, XSecure_ShaPlatConfig::ShaMode, XSECURE_SHA2_256_HASH_LEN, XSECURE_SHA2_384_HASH_LEN, XSECURE_SHA3_256, XSECURE_SHA3_256_HASH_LEN, XSECURE_SHA3_384, XSECURE_SHA3_384_HASH_LEN, XSECURE_SHA_512_HASH_LEN, XSECURE_SHA_INVALID_PARAM, XSECURE_SHAKE_256, XSECURE_SHAKE_256_HASH_LEN.
Referenced by XSecure_ShaDigest.
static int XSecure_ShaIssueDmaAndWait(XPmcDma *DmaPtr, u64 SrcAddr, u32 Words, u8 IsLast)
This function issues a single PMC-DMA SRC transfer to the SHA engine and waits for the DONE bit.
DmaPtr Pointer to the PMC-DMA instance. SrcAddr Word-aligned source address. Words Transfer length in 32-bit words. IsLast When TRUE, asserts data_inp_last on the final word. XST_SUCCESS - On DMA DONE asserted within timeout.XST_FAILURE - On DMA transfer timeout.
int XSecure_ShaDmaXfer(void *InstancePtr, u64 DataAddr, u32 Size, u8 IsLastUpdate)
This function transfers input data to the SHA engine via PMC-DMA, using PartialData[] as a small residue buffer for sub-word and sub-block leftovers between calls.
This function transfer data to SHA engine from DMA. If there is no prior residue and the caller address is word- aligned, the word-aligned portion is DMA'd directly from the caller buffer and any 0..3 trailing bytes are stashed into PartialData[] for the next call. Otherwise the caller bytes are staged through PartialData[] and DMA'd in fixed BlockLen chunks (one Keccak rate / SHA absorber block) sourced from &PartialData[0]; the trailing < BlockLen residue is deferred to SW NIST padding via XSecure_TransferNistPad. Constant DMA size and constant source address are required here to keep the PMC-DMA source channel stable across back-to-back transfers on Spartan UltraScale+. InstancePtr Pointer to the SHA instance. DataAddr Address of the input data. Size Size of the input data in bytes. IsLastUpdate Flag indicating if this is the last data transfer. XST_SUCCESS - Upon successful data transfer.XST_FAILURE - Upon DMA transfer failure.XSECURE_SHA_INVALID_PARAM - Upon invalid parameter. InstancePtr Pointer to the SHA instance. DataAddr Input data address Size Input data size in bytes. IsLastUpdate Last update flag XST_SUCCESS - Upon successXSECURE_SHA_INVALID_PARAM - Invalid parameter InstancePtr Pointer to the SHA instance. DataAddr Input data address. Size Input data size in bytes. IsLastUpdate Last update flag. XST_SUCCESS Upon Success.XST_FAILURE Upon Failure.
References XSecure_ShaPlatConfig::HashAlgo, XSecure_MemCpy64, XSECURE_SHA_INVALID_PARAM, XSecure_ShaGetBlockLen, XSECURE_WORD_ALIGN_MASK, XSECURE_WORD_SIZE.
int XSecure_CfgSssAes(XPmcDma *DmaPtr, const XSecure_Sss *SssInstance)
This function configures SSS to AES engine.
DmaPtr Pointer to the DMA instance SssInstance Pointer to SSS instance XST_SUCCESS on successful configurationError code on failure
References XSECURE_SSS_DMA0, XSECURE_SSS_DMA1, XSecure_SssAes.
int XSecure_CryptoCheck(XSecure_CoreSrc CoreSrc)
This function checks whether the requested crypto accelerator is enabled for the specified core.
CoreSrc Crypto core source (AES, SHA, RSA) XST_SUCCESS - When crypto accelerators are enabledXSECURE_ERR_CRYPTO_ACCELERATOR_DISABLED - When crypto accelerators are disabledXSECURE_ERR_INVALID_CORE - When invalid core is specified
References XSECURE_AES_CRYPTO_DIS_MASK, XSECURE_CORE_AES, XSECURE_CORE_RSA_ECC, XSECURE_CORE_SHA, XSECURE_EFUSE_CONTROLS_ADDRESS, XSECURE_EFUSE_EXPORT_CONTROL_MASK, XSECURE_ERR_CRYPTO_ACCELERATOR_DISABLED, XSECURE_ERR_INVALID_CORE, XSecure_In32, XSECURE_PMC_GLOBAL_CRYPTO_DIS_ADDRESS, XSECURE_SHA_CRYPTO_DIS_MASK.