trngpsx/xsecure_trng.h
XSECURE_TRNG_SEC_STRENGTH_IN_BYTES
Security strength in bytes for XTRNGPSX.
XSECURE_TRNG_PER_STRING_LEN_IN_BYTES
Personalization string length in bytes for XTRNGPSX.
XSecure_PreOperationalSelfTests
Redefine XTrngpsx_PreOperationalSelfTests as XSecure_PreOperationalSelfTests for compatibility.
XSecure_TrngGenerate
Redefine XTrngpsx_Generate as XSecure_TrngGenerate for compatibility.
Referenced by XSecure_EllipticPrvtKeyGenerate.
XSecure_Uninstantiate
Redefine XTrngpsx_Uninstantiate as XSecure_Uninstantiate for compatibility.
XSecureTrng_Mode
HRNG mode for TRNG.
typedef XTrngpsx_Instance XSecure_TrngInstance
typedef XTrngpsx_Instance as XSecure_TrngInstance for compatibility
int XSecure_GetRandomNum(u8 *Output, u32 Size)
This function generates Random number of given size.
This function generates random number of given size. Output is a pointer to the output buffer Size is the number of random bytes to be read XST_SUCCESS On SuccessXST_FAILURE On FailureXST_INVALID_PARAM - Invalid input parameter (size is 0 or output is NULL)XSECURE_ERR_GLITCH_DETECTED - Error when glitch is detected Output Pointer to the output buffer. Size Number of random bytes to be read. XST_SUCCESS On Success. XST_FAILURE On Failure.XST_INVALID_PARAM - Invalid input parameter (size is 0 or output is NULL) XSECURE_ERR_GLITCH_DETECTED - Error when glitch is detected. Output is a pointer to the output buffer Size is the number of random bytes to be read XST_SUCCESS On SuccessXST_FAILURE On FailureXST_INVALID_PARAM - Invalid input parameter (size is 0 or output is NULL)XSECURE_ERR_GLITCH_DETECTED - Error when glitch is detected. This function generates Random number of given size. Output Pointer to the output buffer Size Number of random bytes to be read XST_SUCCESS - On successXST_INVALID_PARAM - Invalid input parameter (size is 0 or output is NULL)XSECURE_ERR_GLITCH_DETECTED - Glitch detected during random number generationXST_FAILURE - TRNG operation failure Output is a pointer to the output buffer Size is the number of random bytes to be read XST_SUCCESS On SuccessXST_FAILURE On FailureXST_INVALID_PARAM - Invalid input parameter (size is 0 or output is NULL)XSECURE_ERR_GLITCH_DETECTED - Error when glitch is detected Output Pointer to the output buffer. Size Number of random bytes to be read. XST_SUCCESS On Success. XST_FAILURE On Failure.XST_INVALID_PARAM - Invalid input parameter (size is 0 or output is NULL) XSECURE_ERR_GLITCH_DETECTED - Error when glitch is detected. Output is a pointer to the output buffer Size is the number of random bytes to be read XST_SUCCESS On SuccessXST_FAILURE On FailureXST_INVALID_PARAM - Invalid input parameter (size is 0 or output is NULL)XSECURE_ERR_GLITCH_DETECTED - Error when glitch is detected.
References XSecure_GetTrngInstance, XSecure_ECCRandInit, XSECURE_ERR_GLITCH_DETECTED, XSecure_Uninstantiate, XSECURE_TRNG_SEC_STRENGTH_IN_BYTES.
Referenced by XSecure_EllipticGenerateEphemeralKey, XSecure_MldsaSignGenerate.
XSecure_TrngInstance * XSecure_GetTrngInstance(void)
This function provides the pointer to the common trng instance.
Pointer to the XSecure_TrngInstance instance
Referenced by XSecure_ECCRandInit, XSecure_EllipticPrvtKeyGenerate, XSecure_GetRandomNum.
int XSecure_TrngInitNCfgMode(int XSecureTrngMode, u8 *Seed, u32 SeedLength, u8 *PersStr)
This function initialize and configures the TRNG into DRNG/HRNG mode of operation.
XST_SUCCESS - Upon success.XST_FAILURE - On failure. XSecureTrngMode Trng Mode of operation Seed Holds the address of Seed buffer SeedLength Holds size Seed PersStr Personalization string XST_SUCCESS - Upon success.XST_FAILURE - On failure.
Referenced by XSecure_ECCRandInit, XSecure_EllipticPrvtKeyGenerate.
static u8 XSecure_TrngIsUninitialized(XSecure_TrngInstance *TrngInstance)
This is a wrapper function to check trngpsx initialization status.
TrngInstance Pointer to XTrngpsx Instance. XST_SUCCESS If TRNGPSX is not initialized.XST_FAILURE If TRNGPSX is initialized.
static u8 XSecure_TrngIsHealthy(XSecure_TrngInstance *TrngInstance)
This is a wrapper function to check trngpsx health status.
TrngInstance Pointer to XTrngpsx Instance. XST_SUCCESS If status of TRNGPSX is healthy.XST_FAILURE If status of TRNGPSX is not healthy.