trngpsv/xsecure_trng.c
XSECURE_ECC_TRNG_DF_LENGTH
Default length of xilsecure ecc true random number generator.
XTRNGPSV_USER_CFG_DF_LENGTH
Default multiplier used to determine num of bits on the input of the DF construct.
XSecure_TrngInstance * XSecure_GetTrngInstance(void)
This function provides the pointer to the common trng instance.
Pointer to the XSecure_TrngInstance instance
Referenced by XSecure_ECCRandInit, XSecure_EllipticPrvtKeyGenerate, XSecure_GetRandomNum.
int XSecure_TrngInitNCfgMode(int XSecureTrngMode, u8 *Seed, u32 SeedLength, u8 *PersStr)
This function initialize and configures the TRNG into DRNG/HRNG mode of operation.
XST_SUCCESS - Upon success.XST_FAILURE - On failure. XSecureTrngMode Trng Mode of operation Seed Holds the address of Seed buffer SeedLength Holds size Seed PersStr Personalization string XST_SUCCESS - Upon success.XST_FAILURE - On failure.
Referenced by XSecure_ECCRandInit, XSecure_EllipticPrvtKeyGenerate.
int XSecure_PreOperationalSelfTests(XSecure_TrngInstance *TrngInstance)
This function runs preoperational self tests and updates TRNG error state.
TrngInstance Pointer to XTrngpsv Instance. XST_SUCCESS - On successXST_FAILURE - On failure
Referenced by XSecure_ECCRandInit.