trngpsv/xsecure_trng.h
XSECURE_TRNG_SEC_STRENGTH_IN_BYTES
Security strength in bytes for XTRNGPSV.
XSECURE_TRNG_PER_STRING_LEN_IN_BYTES
Personalization string length in bytes for XTRNGPSV.
XSECURE_TRNG_USER_CFG_SEED_LIFE
User config Seed life.
XSecure_Uninstantiate
Redefine XTrngpsv_Uninstantiate as XSecure_Uninstantiate for compatibility.
Referenced by XSecure_EllipticPrvtKeyGenerate, XSecure_GetRandomNum.
XSecureTrng_Mode
HRNG mode for TRNG.
typedef XTrngpsv XSecure_TrngInstance
typedef XTrngpsv as XSecure_TrngInstance for compatibility
XSecure_TrngInstance * XSecure_GetTrngInstance(void)
This function provides the pointer to the common trng instance.
Pointer to the XSecure_TrngInstance instance
Referenced by XSecure_ECCRandInit, XSecure_EllipticPrvtKeyGenerate, XSecure_GetRandomNum.
int XSecure_TrngInitNCfgMode(int XSecureTrngMode, u8 *Seed, u32 SeedLength, u8 *PersStr)
This function initialize and configures the TRNG into DRNG/HRNG mode of operation.
XST_SUCCESS - Upon success.XST_FAILURE - On failure. XSecureTrngMode Trng Mode of operation Seed Holds the address of Seed buffer SeedLength Holds size Seed PersStr Personalization string XST_SUCCESS - Upon success.XST_FAILURE - On failure.
Referenced by XSecure_ECCRandInit, XSecure_EllipticPrvtKeyGenerate.
int XSecure_PreOperationalSelfTests(XSecure_TrngInstance *TrngInstance)
This function runs preoperational self tests and updates TRNG error state.
TrngInstance Pointer to XTrngpsv Instance. XST_SUCCESS - On successXST_FAILURE - On failure
Referenced by XSecure_ECCRandInit.
static u8 XSecure_TrngIsUninitialized(XSecure_TrngInstance *TrngInstance)
This is a wrapper function to check trngpsv initialization status.
TrngInstance Pointer to XTrngpsv instance. XST_SUCCESS If TRNGPSV is not initialized.XST_FAILURE If TRNGPSV is initialized.
static u8 XSecure_TrngIsHealthy(XSecure_TrngInstance *TrngInstance)
This is a wrapper function to check trngpsv health status.
TrngInstance Pointer to XTrngpsv instance. XST_SUCCESS If status of TRNGPSV is healthy.XST_FAILURE If status of TRNGPSV is not healthy.
static int XSecure_TrngGenerate(XSecure_TrngInstance *TrngInstance, u8 *RandBuf, u32 RandBufSize, u8 PredResistance)
This wrapper to generate random bits.
TrngInstance Pointer to the XTrngpsv instance. RandBuf Pointer to memory address where generated random data will be stored and the memory address should be word aligned. RandBufSize Size of the buffer to which RandBufPtr points to and it should be always greater than or equal to XTRNGPSV_SEC_STRENGTH_BYTES. PredResistance Flag that controls Generate level Prediction Resistance. When enabled, it mandates fresh seed for every Generate operation. XST_SUCCESS On success.ErrorCode On failure.