versal_2vp_p/xsecure_plat.c
const u8 XSecure_SssLookupTable[XSECURE_SSS_MAX_SRCS][XSECURE_SSS_MAX_SRCS][XSECURE_SSS_MAX_SRCS][XSECURE_SSS_MAX_SRCS]
const XSecure_ShaConfig ShaConfigTable[XSECURE_SHA_NUM_OF_INSTANCES][XSECURE_SHA_NUM_OF_INSTANCES]
u32 XSecure_SssMask(XSecure_SssSrc InputSrc, XSecure_SssSrc OutputSrc, u32 Value)
This function masks the secure stream switch value.
InputSrc Input source to be selected for the resource OutputSrc Output source to be selected for the resource Value Register Value of SSS cfg register Mask - Mask value of corresponding InputSrc and OutputSrc InputSrc, OutputSrc are of type XSecure_SssSrc InputSrc Input source to be selected for the resource OutputSrc Output source to be selected for the resource Value Register Value of SSS cfg register Mask Mask value of corresponding InputSrc and OutputSrc InputSrc, OutputSrc are of type XSecure_SssSrc InputSrc Input source to be selected for the resource OutputSrc Output source to be selected for the resource Value Register Value of SSS cfg register Mask value of corresponding InputSrc and OutputSrc InputSrc, OutputSrc are of type XSecure_SssSrc InputSrc Input source to be selected for the resource. OutputSrc Output source to be selected for the resource. Value Register Value of SSS cfg register. Mask Mask value of corresponding InputSrc and OutputSrc InputSrc, OutputSrc are of type XSecure_SssSrc InputSrc Input source to be selected for the resource. OutputSrc Output source to be selected for the resource. Value Register Value of SSS cfg register. Mask Mask value of corresponding InputSrc and OutputSrc. InputSrc, OutputSrc are of type XSecure_SssSrc.
References XSECURE_SSS_AES_DMA0_VAL, XSECURE_SSS_AES_MASK, XSECURE_SSS_DMA0, XSECURE_SSS_DMA0_MASK, XSECURE_SSS_SBI_DMA0_VAL, XSECURE_SSS_SBI_MASK, XSECURE_SSS_SHA_DMA0_VAL, XSECURE_SSS_SHA_MASK.
Referenced by XSecure_SssAes, XSecure_SssSha.
void XSecure_UpdateTrngCryptoStatus(u32 Op)
This function updates TRNG crypto indicator.
Op To set or clear the bit. Op To set or clear the bit
Referenced by XSecure_EllipticPrvtKeyGenerate.
static void XSecure_SetRsaCryptoStatus(void)
This function is not applicable for versal.
This function updates RSA crypto indicator.
static void XSecure_UpdateCryptoStatus(UINTPTR BaseAddress, u32 Op)
This function is not applicable for versal.
This function updates the crypto indicator bit of AES, SHA and ECC. BaseAddress Base address of the core Op To set or clear the bit BaseAddress Base address of the core. Op To set or clear the bit.
void XSecure_ConfigureDmaByteSwap(u32 Op)
This function configures DMA Byte Swap based on the user input.
Op Enable/Disable byte swapping.
References XSecure_GetAesInstance.
Referenced by XSecure_AesDecryptKat, XSecure_AesEncryptKat.
int XSecure_AesValidateSize(u32 Size, u8 IsLastChunk)
This function validates the size.
This function validates whether all the intermediate updates to AES engine are Q-WORD aligned or not.This function validates if intermediate updates are 16-bytes aligned or not.This function is not applicable for Versal_2Ve_2Vm.This function validates whether size of the data is word aligned and if it is the last chunk size should be qword aligned. Size Size of data in bytes. IsLastChunk Last chunk indication XST_SUCCESS on successful validationError code on failure Size Size of data in bytes. IsLastChunk Last chunk indication XST_SUCCESS On successful valdationXSECURE_AES_UNALIGNED_SIZE_ERROR If unaligned size is given as input Size Size of data in bytes. IsLastChunk Last chunk indication XST_SUCCESS - On successXSECURE_AES_UNALIGNED_SIZE_ERROR - Size is not 16-byte aligned for non-last chunk Size Size of data in bytes. IsLastChunk Last chunk indication. XST_SUCCESS On successful valdation.XSECURE_AES_UNALIGNED_SIZE_ERROR If unaligned size is given as input. Size Size of data in bytes. IsLastChunk Last chunk indication. XST_SUCCESS If update is 16-bytes aligned.XSECURE_AES_UNALIGNED_SIZE_ERROR If update is not 16-bytes aligned. Size Size of data in bytes. IsLastChunk Last chunk indication XST_SUCCESS If the data is q-word aligned for intermediate updates XST_FAILURE If the data is not q-word aligned for intermediate updates
References XSECURE_AES_UNALIGNED_SIZE_ERROR, XSECURE_QWORD_SIZE, XSECURE_WORD_SIZE.
int XSecure_AesPlatPmcDmaCfgAndXfer(XPmcDma *PmcDmaPtr, XSecure_AesDmaCfg *AesDmaCfg, u32 Size, UINTPTR BaseAddress)
This function sets the SRC and DEST channel endianness configurations of PMC DMA and transfers data.
PmcDmaPtr Pointer to the XPmcDma instance. AesDmaCfg DMA SRC and DEST channel configuration Size Size of data in bytes. BaseAddress AES BaseAddress XST_SUCCESS - On successful configurationXSECURE_AES_INVALID_PARAM - Invalid input parameter providedXST_FAILURE - DMA transfer or timeout failure PmcDmaPtr Pointer to the XPmcDma instance. AesDmaCfg DMA SRC and DEST channel configuration. Size Size of data in bytes. BaseAddress AES BaseAddress. XST_SUCCESS On successful configuration. XSECURE_AES_INVALID_PARAM If any input parameter is invalid. XST_FAILURE On failure. PmcDmaPtr Pointer to the XPmcDma instance. AesDmaCfg DMA SRC and DEST channel configuration Size Size of data in bytes. BaseAddress AES BaseAddress XST_SUCCESS On successful configurationXSECURE_AES_INVALID_PARAM If any input parameter is invalid XST_FAILURE On failure
References XSecure_AesDmaCfg::DestChannelCfg, XSecure_AesDmaCfg::DestDataAddr, XSecure_AesDmaCfg::IsLastChunkDest, XSecure_AesDmaCfg::IsLastChunkSrc, XSecure_AesDmaCfg::SrcChannelCfg, XSecure_AesDmaCfg::SrcDataAddr, XSECURE_AES_INVALID_PARAM, XSECURE_AES_NO_CFG_DST_DMA, XSecure_AesPmcDmaCfgEndianness, XSECURE_DISABLE_BYTE_SWAP, XSECURE_ENABLE_BYTE_SWAP, XSecure_GetAesInstance.
void XSecure_AesPmcDmaCfgEndianness(XPmcDma *InstancePtr, XPmcDma_Channel Channel, u8 EndianType)
This is a helper function to enable/disable byte swapping feature of PMC DMA.
InstancePtr Pointer to the XPmcDma instance Channel Channel Type (XPMCDMA_SRC_CHANNEL or XPMCDMA_DST_CHANNEL) EndianType 1 to enable byte swapping, 0 to disable byte swapping InstancePtr Pointer to the XPmcDma instance. Channel Channel Type (XPMCDMA_SRC_CHANNEL or XPMCDMA_DST_CHANNEL) EndianType 1 to enable byte swapping, 0 to disable byte swapping InstancePtr Pointer to the XPmcDma instance Channel Channel type (XPMCDMA_SRC_CHANNEL or XPMCDMA_DST_CHANNEL) EndianType Endianness type: 1 to enable byte swapping, 0 to disable byte swapping
References XSecure_AssertVoid.
Referenced by XSecure_AesEncryptUpdate, XSecure_AesPlatPmcDmaCfgAndXfer.
int XSecure_GetRandomNum(u8 *Output, u32 Size)
This function generates random number of given size.
This function generates Random number of given size. Output Pointer to the output buffer Size Number of random bytes to be read XST_SUCCESS - On successXST_INVALID_PARAM - Invalid input parameter (size is 0 or output is NULL)XSECURE_ERR_GLITCH_DETECTED - Glitch detected during random number generationXST_FAILURE - TRNG operation failure Output is a pointer to the output buffer Size is the number of random bytes to be read XST_SUCCESS On SuccessXST_FAILURE On FailureXST_INVALID_PARAM - Invalid input parameter (size is 0 or output is NULL)XSECURE_ERR_GLITCH_DETECTED - Error when glitch is detected Output Pointer to the output buffer. Size Number of random bytes to be read. XST_SUCCESS On Success. XST_FAILURE On Failure.XST_INVALID_PARAM - Invalid input parameter (size is 0 or output is NULL) XSECURE_ERR_GLITCH_DETECTED - Error when glitch is detected. Output is a pointer to the output buffer Size is the number of random bytes to be read XST_SUCCESS On SuccessXST_FAILURE On FailureXST_INVALID_PARAM - Invalid input parameter (size is 0 or output is NULL)XSECURE_ERR_GLITCH_DETECTED - Error when glitch is detected.
References XSecure_ECCRandInit, XSECURE_ERR_GLITCH_DETECTED, XSecure_GetTrngInstance, XSECURE_TRNG_SEC_STRENGTH_IN_BYTES, XSecure_Uninstantiate.
Referenced by XSecure_EllipticGenerateEphemeralKey, XSecure_MldsaSignGenerate.
int XSecure_ECCRandInit(void)
This function initializes the trng in HRNG mode if it is not initialized and it is applicable only for Versal_2Ve_2Vm.
This function initializes the trng in HRNG mode if it is not initialized and it is applicable only for VersalNet.This function initializes the trng in HRNG mode if it is not initialized.This function initializes the trng in HRNG mode if it is not initialized and it is applicable only for Versal_2VP. XST_SUCCESS - On successful initializationXSECURE_ERR_IN_TRNG_SELF_TESTS - TRNG self-test failureXSECURE_ERR_TRNG_INIT_N_CONFIG - TRNG initialization and configuration failureXST_FAILURE - On any other failure XST_SUCCESS On Successful initializationXST_FAILURE On Failure XST_SUCCESS On Successful initialization.XST_FAILURE On Failure.
References XSECURE_ERR_IN_TRNG_SELF_TESTS, XSECURE_ERR_TRNG_INIT_N_CONFIG, XSecure_GetTrngInstance, XSecure_PreOperationalSelfTests, XSECURE_TRNG_HRNG_MODE, XSecure_TrngInitNCfgMode.
Referenced by XSecure_EcdhGetSecret, XSecure_EllipticGenerateKey_64Bit, XSecure_EllipticGenerateSignature_64Bit, XSecure_GetRandomNum.
int XSecure_ShaValidateModeAndCfgInstance(XSecure_Sha *const InstancePtr, XSecure_ShaMode ShaMode)
This function validates the SHA Mode and initialize SHA instance.
InstancePtr Pointer to the SHA instance. ShaMode SHA Mode. XST_SUCCESS - Upon Success. XST_FAILURE - Upon Failure. XSECURE_SHA_INVALID_MODE_ERROR InstancePtr Pointer to the SHA instance. ShaMode SHA Mode XST_SUCCESS - Upon successXSECURE_SHA_INVALID_PARAM - Invalid SHA mode provided InstancePtr Pointer to the SHA instance. ShaMode SHA Mode. XST_SUCCESS Upon Success.XST_FAILURE Upon Failure.XSECURE_SHA_INVALID_MODE_ERROR In case of invalid sha mode config.
References SHA256, SHA384, SHA512, XSecure_ShaPlatConfig::ShaDigestSize, SHAKE256, XSecure_ShaPlatConfig::ShaMode, XSECURE_SHA2_256_HASH_LEN, XSECURE_SHA2_384_HASH_LEN, XSECURE_SHA3_256, XSECURE_SHA3_256_HASH_LEN, XSECURE_SHA3_384, XSECURE_SHA3_384_HASH_LEN, XSECURE_SHA_512_HASH_LEN, XSECURE_SHA_INVALID_PARAM, XSECURE_SHAKE_256, XSECURE_SHAKE_256_HASH_LEN.
Referenced by XSecure_ShaDigest.
int XSecure_ShaDmaXfer(void *InstancePtr, u64 DataAddr, u32 Size, u8 IsLastUpdate)
This function transfers input data to the SHA engine via PMC-DMA, using PartialData[] as a small residue buffer for sub-word and sub-block leftovers between calls.
This function transfer data to SHA engine from DMA. If there is no prior residue and the caller address is word- aligned, the word-aligned portion is DMA'd directly from the caller buffer and any 0..3 trailing bytes are stashed into PartialData[] for the next call. Otherwise the caller bytes are staged through PartialData[] and DMA'd in fixed BlockLen chunks (one Keccak rate / SHA absorber block) sourced from &PartialData[0]; the trailing < BlockLen residue is deferred to SW NIST padding via XSecure_TransferNistPad. Constant DMA size and constant source address are required here to keep the PMC-DMA source channel stable across back-to-back transfers on Spartan UltraScale+. InstancePtr Pointer to the SHA instance. DataAddr Address of the input data. Size Size of the input data in bytes. IsLastUpdate Flag indicating if this is the last data transfer. XST_SUCCESS - Upon successful data transfer.XST_FAILURE - Upon DMA transfer failure.XSECURE_SHA_INVALID_PARAM - Upon invalid parameter. InstancePtr Pointer to the SHA instance. DataAddr Input data address Size Input data size in bytes. IsLastUpdate Last update flag XST_SUCCESS - Upon successXSECURE_SHA_INVALID_PARAM - Invalid parameter InstancePtr Pointer to the SHA instance. DataAddr Input data address. Size Input data size in bytes. IsLastUpdate Last update flag. XST_SUCCESS Upon Success.XST_FAILURE Upon Failure.
References XSecure_ShaPlatConfig::HashAlgo, XSecure_MemCpy64, XSECURE_SHA_INVALID_PARAM, XSecure_ShaGetBlockLen, XSECURE_WORD_ALIGN_MASK, XSECURE_WORD_SIZE.
int XSecure_MemCpyAndChangeEndianness(u64 DestAddress, u64 SrcAddress, u32 Length)
This function can copy the content of memory from 64-bit address to 32-bit address and change endianness of destination data.
DestAddress The address of the destination where content of SrcAddr memory should be copied. SrcAddress The address of the source where copy should start from. Length Size of memory to be copied in bytes. XST_SUCCESS - On successXST_FAILURE - Memory copy or endianness reversal failure DestAddress The address of the destination where content of SrcAddr memory should be copied. SrcAddress The address of the source where copy should start from. Length Size of memory to be copied in bytes. XST_SUCCESS On success and error code on failure.XST_FAILURE In case of any failure. DestAddress is the address of the destination where content of SrcAddr memory should be copied. SrcAddress is the address of the source where copy should start from. Length is size of memory to be copied in bytes. XST_SUCCESS On successXST_FAILURE On failure
Referenced by XSecure_KeyUnwrap.