versal_2vp_p/xsecure_plat.h
XSECURE_SSS_ADDRESS
SSS base address.
XSECURE_SSS_MAX_SRCS
Maximum resources.
XSECURE_SSS_SHA3_MASK
SSS SHA3 instance mask value.
XSECURE_SSS_SHA2_MASK
SSS SHA3 instance mask value.
XSECURE_SSS_SHA3_DMA0_VAL
SSS SHA3 instance DMA0 value.
XSECURE_SSS_SHA3_DMA1_VAL
SSS SHA3 instance DMA1 value.
XSECURE_SSS_SHA2_DMA0_VAL
SSS SHA2 instance DMA0 value.
XSECURE_SSS_SHA2_DMA1_VAL
SSS SHA2 instance DMA1 value.
XSECURE_ENABLE_BYTE_SWAP
Enables data swap in AES.
XSECURE_DISABLE_BYTE_SWAP
Disables data swap in AES.
XSECURE_TRNG_USER_CFG_SEED_LIFE
User configuration seed life.
XSECURE_TRNG_USER_CFG_DF_LENGTH
User configuration DF length.
XSECURE_TRNG_USER_CFG_ADAPT_TEST_CUTOFF
Adapt test cutoff.
XSECURE_TRNG_USER_CFG_REP_TEST_CUTOFF
Rep test cutoff.
XSECURE_AES_KTE_GO_ADDRESS
AES KTE GO address.
XSECURE_AES_KTE_RESTART_ADDRESS
AES Key Transfer Engine Restart register.
XSECURE_AES_KTE_DONE_ADDRESS
AES Key Transfer Engine Done.
XSECURE_AES_KTE_CNT_ADDRESS
AES Key Transfer Engine Count address.
XSECURE_AES_KTE_GO_ENABLE
AES KTE GO enable.
XSECURE_AES_KTE_GO_DISABLE
AES KTE GO disable.
XSECURE_AES_KTE_DONE_MASK
AES Key Transfer Engine Done mask.
XSECURE_AES_KTE_CNT_MASK
AES Key Transfer Engine Count value.
XSECURE_AES_KTE_DONE_POLL_TIMEOUT
AES Key Transfer complete poll timeout.
XSECURE_SSS_SBI_MASK
SSS SBI mask.
XSECURE_SSS_AES_MASK
SSS AES mask.
XSECURE_SSS_DMA1_MASK
SSS DMA1 mask.
XSECURE_SSS_DMA0_MASK
SSS DMA0 mask.
XSECURE_SSS_SRC_SEL_MASK
SSS Source Select mask.
XSECURE_SSS_SBI_DMA0_VAL
SSS SBI DMA0 value.
XSECURE_SSS_SBI_DMA1_VAL
SSS SBI DMA1 value.
XSECURE_SSS_AES_DMA0_VAL
SSS AES DMA0 value.
XSECURE_SSS_AES_DMA1_VAL
SSS AES DMA1 value.
XCSUDMA_WORD_SIZE
WORD size.
XSECURE_SHA_512_HASH_LEN
SHA_512 block length.
XSECURE_SHA3_256_HASH_LEN
SHA3_256 block length.
XSECURE_SHA2_256_BLOCK_LEN
SHA2_256 block length.
XSECURE_SHA3_BLOCK_LEN
SHA3 block length.
XSECURE_SHA2_384_BLOCK_LEN
SHA2_384 block length.
XSECURE_SHAKE_256_BLOCK_LEN
SHAKE_256 block length.
XSECURE_SHA3_384_HASH_LEN
SHA3_384 hash length.
XSECURE_SHA2_384_HASH_LEN
SHA2_384 hash length.
XSECURE_SHAKE_256_HASH_LEN
SHAKE_256 hash length.
XSECURE_SHA2_256_HASH_LEN
SHA2_256 hash length.
XSECURE_SHA3_384_HASH_WORD_LEN
SHA3_384 hash word length.
XSECURE_SHA2_384_HASH_WORD_LEN
SHA2_384 hash word length.
XSECURE_SHAKE_256_HASH_WORD_LEN
SHAKE_256 hash word length.
XSECURE_SHA2_256_HASH_WORD_LEN
SHA2_256 hash word length.
SHA256
SHA256 mode.
SHA384
SHA384 mode.
SHA512
SHA512 mode.
SHAKE256
SHAKE256 mode.
SHAKE256_SLH_DSA_CHAIN
SHAKE256 SLH-DSA Chain mode.
Referenced by XSecure_ExtendedShaFinish.
XSecure_SssSrc
DMA0.
static void XSecure_SetRsaCryptoStatus(void)
This function is not applicable for versal.
This function updates RSA crypto indicator.
static void XSecure_UpdateCryptoStatus(UINTPTR BaseAddress, u32 Op)
This function is not applicable for versal.
This function updates the crypto indicator bit of AES, SHA and ECC. BaseAddress Base address of the core Op To set or clear the bit BaseAddress Base address of the core. Op To set or clear the bit.
void XSecure_UpdateTrngCryptoStatus(u32 Op)
This function updates TRNG crypto indicator.
Op To set or clear the bit. Op To set or clear the bit
Referenced by XSecure_EllipticPrvtKeyGenerate.
void XSecure_ConfigureDmaByteSwap(u32 Op)
This function configures DMA Byte Swap based on the user input.
Op Enable/Disable byte swapping.
References XSecure_GetAesInstance.
Referenced by XSecure_AesDecryptKat, XSecure_AesEncryptKat.
int XSecure_AesPlatPmcDmaCfgAndXfer(XPmcDma *PmcDmaPtr, XSecure_AesDmaCfg *AesDmaCfg, u32 Size, UINTPTR BaseAddress)
This function sets the SRC and DEST channel endianness configurations of PMC DMA and transfers data.
PmcDmaPtr Pointer to the XPmcDma instance. AesDmaCfg DMA SRC and DEST channel configuration Size Size of data in bytes. BaseAddress AES BaseAddress XST_SUCCESS - On successful configurationXSECURE_AES_INVALID_PARAM - Invalid input parameter providedXST_FAILURE - DMA transfer or timeout failure PmcDmaPtr Pointer to the XPmcDma instance. AesDmaCfg DMA SRC and DEST channel configuration. Size Size of data in bytes. BaseAddress AES BaseAddress. XST_SUCCESS On successful configuration. XSECURE_AES_INVALID_PARAM If any input parameter is invalid. XST_FAILURE On failure. PmcDmaPtr Pointer to the XPmcDma instance. AesDmaCfg DMA SRC and DEST channel configuration Size Size of data in bytes. BaseAddress AES BaseAddress XST_SUCCESS On successful configurationXSECURE_AES_INVALID_PARAM If any input parameter is invalid XST_FAILURE On failure
References XSecure_AesDmaCfg::DestChannelCfg, XSecure_AesDmaCfg::DestDataAddr, XSecure_AesDmaCfg::IsLastChunkDest, XSecure_AesDmaCfg::IsLastChunkSrc, XSecure_AesDmaCfg::SrcChannelCfg, XSecure_AesDmaCfg::SrcDataAddr, XSECURE_AES_INVALID_PARAM, XSECURE_AES_NO_CFG_DST_DMA, XSecure_AesPmcDmaCfgEndianness, XSECURE_DISABLE_BYTE_SWAP, XSECURE_ENABLE_BYTE_SWAP, XSecure_GetAesInstance.
void XSecure_AesPmcDmaCfgEndianness(XPmcDma *InstancePtr, XPmcDma_Channel Channel, u8 EndianType)
This is a helper function to enable/disable byte swapping feature of PMC DMA.
InstancePtr Pointer to the XPmcDma instance Channel Channel Type (XPMCDMA_SRC_CHANNEL or XPMCDMA_DST_CHANNEL) EndianType 1 to enable byte swapping, 0 to disable byte swapping InstancePtr Pointer to the XPmcDma instance. Channel Channel Type (XPMCDMA_SRC_CHANNEL or XPMCDMA_DST_CHANNEL) EndianType 1 to enable byte swapping, 0 to disable byte swapping InstancePtr Pointer to the XPmcDma instance Channel Channel type (XPMCDMA_SRC_CHANNEL or XPMCDMA_DST_CHANNEL) EndianType Endianness type: 1 to enable byte swapping, 0 to disable byte swapping
References XSecure_AssertVoid.
Referenced by XSecure_AesEncryptUpdate, XSecure_AesPlatPmcDmaCfgAndXfer.
int XSecure_AesValidateSize(u32 Size, u8 IsLastChunk)
This function validates the size.
This function validates whether all the intermediate updates to AES engine are Q-WORD aligned or not.This function validates if intermediate updates are 16-bytes aligned or not.This function is not applicable for Versal_2Ve_2Vm.This function validates whether size of the data is word aligned and if it is the last chunk size should be qword aligned. Size Size of data in bytes. IsLastChunk Last chunk indication XST_SUCCESS on successful validationError code on failure Size Size of data in bytes. IsLastChunk Last chunk indication XST_SUCCESS On successful valdationXSECURE_AES_UNALIGNED_SIZE_ERROR If unaligned size is given as input Size Size of data in bytes. IsLastChunk Last chunk indication XST_SUCCESS - On successXSECURE_AES_UNALIGNED_SIZE_ERROR - Size is not 16-byte aligned for non-last chunk Size Size of data in bytes. IsLastChunk Last chunk indication. XST_SUCCESS On successful valdation.XSECURE_AES_UNALIGNED_SIZE_ERROR If unaligned size is given as input. Size Size of data in bytes. IsLastChunk Last chunk indication. XST_SUCCESS If update is 16-bytes aligned.XSECURE_AES_UNALIGNED_SIZE_ERROR If update is not 16-bytes aligned. Size Size of data in bytes. IsLastChunk Last chunk indication XST_SUCCESS If the data is q-word aligned for intermediate updates XST_FAILURE If the data is not q-word aligned for intermediate updates
References XSECURE_AES_UNALIGNED_SIZE_ERROR, XSECURE_QWORD_SIZE, XSECURE_WORD_SIZE.
int XSecure_ECCRandInit(void)
This function initializes the trng in HRNG mode if it is not initialized and it is applicable only for Versal_2Ve_2Vm.
This function initializes the trng in HRNG mode if it is not initialized and it is applicable only for VersalNet.This function initializes the trng in HRNG mode if it is not initialized.This function initializes the trng in HRNG mode if it is not initialized and it is applicable only for Versal_2VP. XST_SUCCESS - On successful initializationXSECURE_ERR_IN_TRNG_SELF_TESTS - TRNG self-test failureXSECURE_ERR_TRNG_INIT_N_CONFIG - TRNG initialization and configuration failureXST_FAILURE - On any other failure XST_SUCCESS On Successful initializationXST_FAILURE On Failure XST_SUCCESS On Successful initialization.XST_FAILURE On Failure.
References XSECURE_ERR_IN_TRNG_SELF_TESTS, XSECURE_ERR_TRNG_INIT_N_CONFIG, XSecure_GetTrngInstance, XSecure_PreOperationalSelfTests, XSECURE_TRNG_HRNG_MODE, XSecure_TrngInitNCfgMode.
Referenced by XSecure_EcdhGetSecret, XSecure_EllipticGenerateKey_64Bit, XSecure_EllipticGenerateSignature_64Bit, XSecure_GetRandomNum.
int XSecure_InitiateASUKeyTransfer(void)
This function initiates the key transfer to ASU.
XST_SUCCESS - On successful key transferXSECURE_ERR_ASU_KTE_DONE_NOT_SET - Key transfer done bit not set within timeout
References XSECURE_AES_KTE_CNT_ADDRESS, XSECURE_AES_KTE_DONE_ADDRESS, XSECURE_AES_KTE_DONE_MASK, XSECURE_AES_KTE_DONE_POLL_TIMEOUT, XSECURE_AES_KTE_GO_ADDRESS, XSECURE_AES_KTE_GO_DISABLE, XSECURE_AES_KTE_GO_ENABLE, XSECURE_DEBUG_GENERAL, XSECURE_ERR_ASU_KTE_DONE_NOT_SET, XSecure_In32, XSecure_Out32, XSecure_Printf.
int XSecure_ShaDmaXfer(void *InstancePtr, u64 DataAddr, u32 Size, u8 IsLastUpdate)
This function transfers input data to the SHA engine via PMC-DMA, using PartialData[] as a small residue buffer for sub-word and sub-block leftovers between calls.
This function transfer data to SHA engine from DMA. If there is no prior residue and the caller address is word- aligned, the word-aligned portion is DMA'd directly from the caller buffer and any 0..3 trailing bytes are stashed into PartialData[] for the next call. Otherwise the caller bytes are staged through PartialData[] and DMA'd in fixed BlockLen chunks (one Keccak rate / SHA absorber block) sourced from &PartialData[0]; the trailing < BlockLen residue is deferred to SW NIST padding via XSecure_TransferNistPad. Constant DMA size and constant source address are required here to keep the PMC-DMA source channel stable across back-to-back transfers on Spartan UltraScale+. InstancePtr Pointer to the SHA instance. DataAddr Address of the input data. Size Size of the input data in bytes. IsLastUpdate Flag indicating if this is the last data transfer. XST_SUCCESS - Upon successful data transfer.XST_FAILURE - Upon DMA transfer failure.XSECURE_SHA_INVALID_PARAM - Upon invalid parameter. InstancePtr Pointer to the SHA instance. DataAddr Input data address Size Input data size in bytes. IsLastUpdate Last update flag XST_SUCCESS - Upon successXSECURE_SHA_INVALID_PARAM - Invalid parameter InstancePtr Pointer to the SHA instance. DataAddr Input data address. Size Input data size in bytes. IsLastUpdate Last update flag. XST_SUCCESS Upon Success.XST_FAILURE Upon Failure.
References XSecure_ShaPlatConfig::HashAlgo, XSecure_MemCpy64, XSECURE_SHA_INVALID_PARAM, XSecure_ShaGetBlockLen, XSECURE_WORD_ALIGN_MASK, XSECURE_WORD_SIZE.
int XSecure_MemCpyAndChangeEndianness(u64 DestAddress, u64 SrcAddress, u32 Length)
This function can copy the content of memory from 64-bit address to 32-bit address and change endianness of destination data.
DestAddress The address of the destination where content of SrcAddr memory should be copied. SrcAddress The address of the source where copy should start from. Length Size of memory to be copied in bytes. XST_SUCCESS - On successXST_FAILURE - Memory copy or endianness reversal failure DestAddress The address of the destination where content of SrcAddr memory should be copied. SrcAddress The address of the source where copy should start from. Length Size of memory to be copied in bytes. XST_SUCCESS On success and error code on failure.XST_FAILURE In case of any failure. DestAddress is the address of the destination where content of SrcAddr memory should be copied. SrcAddress is the address of the source where copy should start from. Length is size of memory to be copied in bytes. XST_SUCCESS On successXST_FAILURE On failure
Referenced by XSecure_KeyUnwrap.