versal_net/xsecure_plat.c
XSECURE_AES_ADDRESS
AES BaseAddress.
XSECURE_SHA_ADDRESS
SHA BaseAddress.
XSECURE_RSA_ECDSA_RSA_ADDRESS
RSA ECDSA BaseAddress.
const u8 XSecure_SssLookupTable[XSECURE_SSS_MAX_SRCS][XSECURE_SSS_MAX_SRCS][XSECURE_SSS_MAX_SRCS][XSECURE_SSS_MAX_SRCS]
const XSecure_ShaConfig ShaConfigTable[XSECURE_SHA_NUM_OF_INSTANCES][XSECURE_SHA_NUM_OF_INSTANCES]
static void XSecure_UpdateEcdsaCryptoStatus(u32 Op)
This function updates ECC crypto indicator.
Op To set or clear the bit
static int XSecure_AesPmcDmaByteXfer(XPmcDma *PmcDmaPtr, const XSecure_AesDmaCfg *AesDmaCfg, u32 Size, UINTPTR BaseAddress)
This function sets the SRC and DEST channel endianness configurations of PMC DMA and transfers non-qword aligned data.
PmcDmaPtr Pointer to the XPmcDma instance. AesDmaCfg DMA SRC and DEST channel configuration Size Size of data in bytes. BaseAddress Aes BaseAddress XST_SUCCESS On successful configurationXST_FAILURE On failure
static int XSecure_AesPmcDmaWordXfer(XPmcDma *PmcDmaPtr, const XSecure_AesDmaCfg *AesDmaCfg, u32 Size)
This function sets the SRC and DEST channel endianness configurations of PMC DMA and transfers qword aligned data.
PmcDmaPtr Pointer to the XPmcDma instance. AesDmaCfg DMA SRC and DEST channel configuration Size Size of data in bytes. XST_SUCCESS On successful configurationXST_FAILURE On failure
static void XSecure_AesDataEndiannessChange(u64 Address, u32 Size)
This function changes the endianness of particular size.
Address Endianness change data stored address Size Size of the data
u32 XSecure_SssMask(XSecure_SssSrc InputSrc, XSecure_SssSrc OutputSrc, u32 Value)
This function masks the secure stream switch value.
InputSrc Input source to be selected for the resource OutputSrc Output source to be selected for the resource Value Register Value of SSS cfg register Mask - Mask value of corresponding InputSrc and OutputSrc InputSrc, OutputSrc are of type XSecure_SssSrc InputSrc Input source to be selected for the resource OutputSrc Output source to be selected for the resource Value Register Value of SSS cfg register Mask Mask value of corresponding InputSrc and OutputSrc InputSrc, OutputSrc are of type XSecure_SssSrc InputSrc Input source to be selected for the resource OutputSrc Output source to be selected for the resource Value Register Value of SSS cfg register Mask value of corresponding InputSrc and OutputSrc InputSrc, OutputSrc are of type XSecure_SssSrc InputSrc Input source to be selected for the resource. OutputSrc Output source to be selected for the resource. Value Register Value of SSS cfg register. Mask Mask value of corresponding InputSrc and OutputSrc InputSrc, OutputSrc are of type XSecure_SssSrc InputSrc Input source to be selected for the resource. OutputSrc Output source to be selected for the resource. Value Register Value of SSS cfg register. Mask Mask value of corresponding InputSrc and OutputSrc. InputSrc, OutputSrc are of type XSecure_SssSrc.
References XSECURE_SSS_AES_DMA0_VAL, XSECURE_SSS_AES_MASK, XSECURE_SSS_DMA0, XSECURE_SSS_DMA0_MASK, XSECURE_SSS_SBI_DMA0_VAL, XSECURE_SSS_SBI_MASK, XSECURE_SSS_SHA_DMA0_VAL, XSECURE_SSS_SHA_MASK.
Referenced by XSecure_SssAes, XSecure_SssSha.
void XSecure_UpdateTrngCryptoStatus(u32 Op)
This function updates TRNG crypto indicator.
Op To set or clear the bit. Op To set or clear the bit
Referenced by XSecure_EllipticPrvtKeyGenerate.
static void XSecure_SetRsaCryptoStatus(void)
This function is not applicable for versal.
This function updates RSA crypto indicator.
static void XSecure_UpdateCryptoStatus(UINTPTR BaseAddress, u32 Op)
This function is not applicable for versal.
This function updates the crypto indicator bit of AES, SHA and ECC. BaseAddress Base address of the core Op To set or clear the bit BaseAddress Base address of the core. Op To set or clear the bit.
int XSecure_AesValidateSize(u32 Size, u8 IsLastChunk)
This function validates the size.
This function validates whether all the intermediate updates to AES engine are Q-WORD aligned or not.This function validates if intermediate updates are 16-bytes aligned or not.This function is not applicable for Versal_2Ve_2Vm.This function validates whether size of the data is word aligned and if it is the last chunk size should be qword aligned. Size Size of data in bytes. IsLastChunk Last chunk indication XST_SUCCESS on successful validationError code on failure Size Size of data in bytes. IsLastChunk Last chunk indication XST_SUCCESS On successful valdationXSECURE_AES_UNALIGNED_SIZE_ERROR If unaligned size is given as input Size Size of data in bytes. IsLastChunk Last chunk indication XST_SUCCESS - On successXSECURE_AES_UNALIGNED_SIZE_ERROR - Size is not 16-byte aligned for non-last chunk Size Size of data in bytes. IsLastChunk Last chunk indication. XST_SUCCESS On successful valdation.XSECURE_AES_UNALIGNED_SIZE_ERROR If unaligned size is given as input. Size Size of data in bytes. IsLastChunk Last chunk indication. XST_SUCCESS If update is 16-bytes aligned.XSECURE_AES_UNALIGNED_SIZE_ERROR If update is not 16-bytes aligned. Size Size of data in bytes. IsLastChunk Last chunk indication XST_SUCCESS If the data is q-word aligned for intermediate updates XST_FAILURE If the data is not q-word aligned for intermediate updates
References XSECURE_AES_UNALIGNED_SIZE_ERROR, XSECURE_QWORD_SIZE, XSECURE_WORD_SIZE.
int XSecure_AesPlatPmcDmaCfgAndXfer(XPmcDma *PmcDmaPtr, XSecure_AesDmaCfg *AesDmaCfg, u32 Size, UINTPTR BaseAddress)
This function sets the SRC and DEST channel endianness configurations of PMC DMA and transfers data.
PmcDmaPtr Pointer to the XPmcDma instance. AesDmaCfg DMA SRC and DEST channel configuration Size Size of data in bytes. BaseAddress AES BaseAddress XST_SUCCESS - On successful configurationXSECURE_AES_INVALID_PARAM - Invalid input parameter providedXST_FAILURE - DMA transfer or timeout failure PmcDmaPtr Pointer to the XPmcDma instance. AesDmaCfg DMA SRC and DEST channel configuration. Size Size of data in bytes. BaseAddress AES BaseAddress. XST_SUCCESS On successful configuration. XSECURE_AES_INVALID_PARAM If any input parameter is invalid. XST_FAILURE On failure. PmcDmaPtr Pointer to the XPmcDma instance. AesDmaCfg DMA SRC and DEST channel configuration Size Size of data in bytes. BaseAddress AES BaseAddress XST_SUCCESS On successful configurationXSECURE_AES_INVALID_PARAM If any input parameter is invalid XST_FAILURE On failure
References XSecure_AesDmaCfg::DestChannelCfg, XSecure_AesDmaCfg::DestDataAddr, XSecure_AesDmaCfg::IsLastChunkDest, XSecure_AesDmaCfg::IsLastChunkSrc, XSecure_AesDmaCfg::SrcChannelCfg, XSecure_AesDmaCfg::SrcDataAddr, XSECURE_AES_INVALID_PARAM, XSECURE_AES_NO_CFG_DST_DMA, XSecure_AesPmcDmaCfgEndianness, XSECURE_DISABLE_BYTE_SWAP, XSECURE_ENABLE_BYTE_SWAP, XSecure_GetAesInstance.
void XSecure_AesPmcDmaCfgEndianness(XPmcDma *InstancePtr, XPmcDma_Channel Channel, u8 EndianType)
This is a helper function to enable/disable byte swapping feature of PMC DMA.
InstancePtr Pointer to the XPmcDma instance Channel Channel Type (XPMCDMA_SRC_CHANNEL or XPMCDMA_DST_CHANNEL) EndianType 1 to enable byte swapping, 0 to disable byte swapping InstancePtr Pointer to the XPmcDma instance. Channel Channel Type (XPMCDMA_SRC_CHANNEL or XPMCDMA_DST_CHANNEL) EndianType 1 to enable byte swapping, 0 to disable byte swapping InstancePtr Pointer to the XPmcDma instance Channel Channel type (XPMCDMA_SRC_CHANNEL or XPMCDMA_DST_CHANNEL) EndianType Endianness type: 1 to enable byte swapping, 0 to disable byte swapping
References XSecure_AssertVoid.
Referenced by XSecure_AesEncryptUpdate, XSecure_AesPlatPmcDmaCfgAndXfer.
int XSecure_GetRandomNum(u8 *Output, u32 Size)
This function generates random number of given size.
This function generates Random number of given size. Output Pointer to the output buffer Size Number of random bytes to be read XST_SUCCESS - On successXST_INVALID_PARAM - Invalid input parameter (size is 0 or output is NULL)XSECURE_ERR_GLITCH_DETECTED - Glitch detected during random number generationXST_FAILURE - TRNG operation failure Output is a pointer to the output buffer Size is the number of random bytes to be read XST_SUCCESS On SuccessXST_FAILURE On FailureXST_INVALID_PARAM - Invalid input parameter (size is 0 or output is NULL)XSECURE_ERR_GLITCH_DETECTED - Error when glitch is detected Output Pointer to the output buffer. Size Number of random bytes to be read. XST_SUCCESS On Success. XST_FAILURE On Failure.XST_INVALID_PARAM - Invalid input parameter (size is 0 or output is NULL) XSECURE_ERR_GLITCH_DETECTED - Error when glitch is detected. Output is a pointer to the output buffer Size is the number of random bytes to be read XST_SUCCESS On SuccessXST_FAILURE On FailureXST_INVALID_PARAM - Invalid input parameter (size is 0 or output is NULL)XSECURE_ERR_GLITCH_DETECTED - Error when glitch is detected.
References XSecure_ECCRandInit, XSECURE_ERR_GLITCH_DETECTED, XSecure_GetTrngInstance, XSECURE_TRNG_SEC_STRENGTH_IN_BYTES, XSecure_Uninstantiate.
Referenced by XSecure_EllipticGenerateEphemeralKey, XSecure_MldsaSignGenerate.
int XSecure_ECCRandInit(void)
This function initializes the trng in HRNG mode if it is not initialized and it is applicable only for Versal_2Ve_2Vm.
This function initializes the trng in HRNG mode if it is not initialized and it is applicable only for VersalNet.This function initializes the trng in HRNG mode if it is not initialized.This function initializes the trng in HRNG mode if it is not initialized and it is applicable only for Versal_2VP. XST_SUCCESS - On successful initializationXSECURE_ERR_IN_TRNG_SELF_TESTS - TRNG self-test failureXSECURE_ERR_TRNG_INIT_N_CONFIG - TRNG initialization and configuration failureXST_FAILURE - On any other failure XST_SUCCESS On Successful initializationXST_FAILURE On Failure XST_SUCCESS On Successful initialization.XST_FAILURE On Failure.
References XSECURE_ERR_IN_TRNG_SELF_TESTS, XSECURE_ERR_TRNG_INIT_N_CONFIG, XSecure_GetTrngInstance, XSecure_PreOperationalSelfTests, XSECURE_TRNG_HRNG_MODE, XSecure_TrngInitNCfgMode.
Referenced by XSecure_EcdhGetSecret, XSecure_EllipticGenerateKey_64Bit, XSecure_EllipticGenerateSignature_64Bit, XSecure_GetRandomNum.
int XSecure_MemCpyAndChangeEndianness(u64 DestAddress, u64 SrcAddress, u32 Length)
This function can copy the content of memory from 64-bit address to 32-bit address and change endianness of destination data.
DestAddress The address of the destination where content of SrcAddr memory should be copied. SrcAddress The address of the source where copy should start from. Length Size of memory to be copied in bytes. XST_SUCCESS - On successXST_FAILURE - Memory copy or endianness reversal failure DestAddress The address of the destination where content of SrcAddr memory should be copied. SrcAddress The address of the source where copy should start from. Length Size of memory to be copied in bytes. XST_SUCCESS On success and error code on failure.XST_FAILURE In case of any failure. DestAddress is the address of the destination where content of SrcAddr memory should be copied. SrcAddress is the address of the source where copy should start from. Length is size of memory to be copied in bytes. XST_SUCCESS On successXST_FAILURE On failure
Referenced by XSecure_KeyUnwrap.