xsecure_plat_rsa.c
XSECURE_RSA_MAX_MSG_SIZE_IN_BYTES
RSA maximum message size in bytes.
XSECURE_RSA_MAX_PS_SIZE_IN_BYTES
RSA maximum PS size in bytes.
XSECURE_RSA_MAX_DB_SIZE_IN_BYTES
RSA maximum DB size in bytes.
static int XSecure_RsaOaepEncode(XSecure_RsaOaepParam *OaepParam, u64 OutputAddr)
This function encodes the given message using PKCS #1 v2.0 RSA Optimal Asymmetric Encryption Padding scheme.
EM = 0x00 || maskedSeed || maskedDB OaepParam is a pointer to the XSecure_RsaOaepParam instance. OutputAddr is address where the encoded data is stored. XST_SUCCESS - On success.XSECURE_RSA_OAEP_INVALID_PARAM - On invalid parameter.XSECURE_RSA_OAEP_INVALID_MSG_LEN - On invalid message length.XST_FAILURE - On failure.
static int XSecure_RsaOaepDecode(XSecure_RsaOaepParam *OaepParam, u64 InputDataAddr)
This function decodes the given message which is encoded with RSA Optimal Asymmetric Encryption Padding scheme i.e.
EM = 0x00 || maskedSeed || maskedDB OaepParam is a pointer to the XSecure_RsaOaepParam instance. InputDataAddr is the address where decrypted output data is stored. XST_SUCCESS - On success.XSECURE_RSA_OAEP_INVALID_PARAM - On invalid parameter.XSECURE_RSA_OAEP_BYTE_MISMATCH_ERROR - If byte mismatch.XSECURE_RSA_OAEP_DATA_CPY_ERROR - If data copy fails.XSECURE_RSA_OAEP_DATA_CMP_ERROR - If data compare fails.XSECURE_RSA_OAEP_DB_MISMATCH_ERROR - If DB ia mismatched.XSECURE_RSA_OAEP_INVALID_MSG_LEN - On invalid message length.XST_FAILURE On failure.
static XSecure_RsaKeyMgmt * XSecure_GetRsaKeyMgmtInstance(void)
This function returns pointer to XSecure_RsaKeyMgmt instance.
RsaKeyMgmt is pointer to the XSecure_RsaKeyMgmt instances.
static int XSecure_GetRsaKeySlotIdx(u32 *RsaKeyIdx, u32 RsaKeyStatus)
This function returns RSA key index based on RsaKeyStatus.
RsaKeyIdx is a pointer to the variable containing RSA free index. RsaKeyStatus Key status to be checked. XST_SUCCESS - On success.XST_FAILURE - On failure.
static XSecure_RsaKeyGenParam * XSecure_GetRsaKeyGenParam(void)
This function returns RSA free key generation param.
Pointer to XSecure_RsaKeyGenParam or NULL otherwise.
static int XSecure_RsaKeyGenInit(XSecure_RsaKeyGenParam *RsaParam, XSecure_RsaKeyPtr *KeyPairState, u32 RsaKeyLen)
This function performs the RSA key initialization.
RsaParam is the pointer to XSecure_RsaKeyGenParam. KeyPairState is the pointer to XSecure_RsaKeyPtr which holds the state of key that needs to be generated. RsaKeyLen Length of RSA key length in bytes. XST_SUCCESS - On success.XSECURE_RSA_INVALID_PARAM - If input parameter is invalid.XST_FAILURE - On failure.
static int XSecure_RsaKeyGenerate(XSecure_RsaKeyPtr *KeyPairState, u32 QuantSize)
This function performs the RSA key generation in steps.
KeyPairState is a pointer to the XSecure_RsaKeyPtr. QuantSize Size of the key generation steps in terms of quant size i.e. Half-size RSA key. XST_SUCCESS - On success.XSECURE_RSA_INVALID_PARAM - If input parameter is invalid.XST_FAILURE - On failure.
static int XSecure_RemoveRsaKeyPairGenerationFromScheduler(void)
This function removes key pair generation task from scheduler.
XST_SUCCESS - On success.XSECURE_ERR_REMOVE_TASK_SCHEDULER - If failed to remove task from scheduler.
static int XSecure_GenerateRsaKeyPair(void *arg)
This function performs the RSA key generation.
XST_SUCCESS - On success.XSECURE_ERR_RSA_KEY_PAIR_GEN_SCHEDULER - If RSA key pair generation fails.XST_FAILURE - On failure.
int XSecure_RsaOaepEncrypt(XSecure_Rsa *InstancePtr, XSecure_RsaOaepParam *OaepParam)
This function encodes the given message using RSA OAEP and encrypts it.
InstancePtr is a pointer to the XSecure_Rsa instance. OaepParam is a pointer to the XSecure_RsaOaepParam instance. XST_SUCCESS - On success.XSECURE_RSA_OAEP_INVALID_PARAM - On invalid parameter.XST_FAILURE - On failure.
References XSecure_RsaOaepParam::OutputDataAddr, XSECURE_RSA_KEY_GEN_SIZE_IN_BYTES, XSECURE_RSA_OAEP_INVALID_PARAM, XSecure_RsaPublicEncrypt_64Bit.
Referenced by XSecure_RsaPwct.
int XSecure_RsaOaepDecrypt(XSecure_RsaPrivKey *PrivKey, XSecure_RsaOaepParam *OaepParam)
This function decodes the given message and decrypts it using RSA OAEP.
PrivKey is a pointer to the XSecure_RsaPrivKey instance. OaepParam is a pointer to the XSecure_RsaOaepParam instance. XST_SUCCESS - On success.XSECURE_RSA_OAEP_INVALID_PARAM - On invalid parameter.XST_FAILURE - On failure.
References XSecure_RsaPrivKey::DP, XSecure_RsaPrivKey::DQ, XSecure_RsaOaepParam::InputDataAddr, XSecure_RsaPrivKey::Mod, XSecure_RsaPrivKey::P, XSecure_RsaPrivKey::Q, XSecure_RsaPrivKey::QInv, XSECURE_BYTE_IN_BITS, XSECURE_RSA_KEY_GEN_SIZE_IN_BYTES, XSECURE_RSA_OAEP_INVALID_PARAM, XSecure_RsaExpCRT.
Referenced by XSecure_KeyUnwrap, XSecure_RsaPwct.
int XSecure_AddRsaKeyPairGenerationToScheduler(void)
This function adds periodic task of generation RSA key pair to scheduler.
XST_SUCCESS - On success.XSECURE_ERR_ADD_TASK_SCHEDULER - If failed to add task to scheduler.
References XSECURE_DEBUG_GENERAL, XSECURE_KEY_PAIR_GEN_POLL_INTERVAL, XSecure_Printf.
Referenced by XSecure_Init, XSecure_RsaDestroyKeyInUse.
u32 XSecure_GetRsaKeyInUseIdx(void)
This function returns RSA key inuse index.
API to destroy key pair that is in use. KeyInUse To indicate the key that is in use
References XSecure_RsaKeyMgmt::KeyInUse, XSECURE_RSA_KEY_AVAIL.
Referenced by XSecure_KeyUnwrap.
int XSecure_RsaDestroyKeyInUse(void)
This function destroys the RSA key in use.
API to add key pair generation to scheduler. XST_SUCCESS - On success.XST_FAILURE - On failure.
References XSecure_RsaKeyGenParam::IsRsaKeyAvail, XSecure_RsaKeyMgmt::Key, XSecure_RsaKeyMgmt::KeyInUse, XSecure_RsaKeyGenParam::KeyPair, XSecure_RsaKeyPair::PrivKey, XSecure_RsaKeyPair::PubKey, XSecure_AddRsaKeyPairGenerationToScheduler, XSECURE_RSA_KEY_AVAIL, XSECURE_RSA_MAX_KEY_GEN_SUPPORT, XSECURE_RTCA_RSA_KEY_STATUS_MASK, XSECURE_RTCA_RSA_KEY_STATUS_REG, XSECURE_ZERO.
XSecure_RsaPrivKey * XSecure_GetRsaPrivateKey(u32 RsaIdx)
This function returns RSA private key.
RsaIdx Index of the RSA key to retrieve. Pointer to XSecure_RsaPrivKey or NULL otherwise.
References XSECURE_RSA_MAX_KEY_GEN_SUPPORT.
Referenced by XSecure_KeyUnwrap.
XSecure_RsaPubKey * XSecure_GetRsaPublicKey(u32 RsaIdx)
This function returns RSA public key.
API to retrieve RSA KEY in use index. Pointer to XSecure_RsaPubKey or NULL otherwise.
References XSECURE_RSA_MAX_KEY_GEN_SUPPORT.