xsecure_elliptic.c
XSECURE_ECDSA_ALGN_CRV_SIZE_IN_BYTES
Align ECDSA curve size in bytes.
Referenced by XSecure_EllipticGetCrvSize.
XSECURE_ECDSA_BITS_IN_BYTES
Bits in bytes.
Referenced by XSecure_EllipticGetCrvSize.
EcdsaCrvInfo * XSecure_EllipticGetCrvData(XSecure_EllipticCrvTyp CrvTyp)
This function gets the curve related information.
CrvTyp Type of the elliptic curve Crv Curve information
References XSECURE_ECC_NIST_P192, XSECURE_ECC_NIST_P224, XSECURE_ECC_NIST_P256, XSECURE_ECC_NIST_P384, XSECURE_ECC_NIST_P521, XSecure_EllipticCrvsGetCount.
Referenced by XSecure_EcdhGetSecret, XSecure_EllipticGenerateEphemeralKey, XSecure_EllipticGetCrvSize, XSecure_EllipticPrvtKeyGenerate.
static u32 XSecure_EllipticValidateAndGetCrvInfo(XSecure_EllipticCrvTyp CrvType, EcdsaCrvInfo **Crv)
This function validates and gets curve info and curve size in bytes.
CrvType Is a type of elliptic curve Crv Pointer to EcdsaCrvInfo CrvSize Size of curve in bytes
int XSecure_EllipticGenerateKey_64Bit(XSecure_EllipticCrvTyp CrvType, const u64 DAddr, const XSecure_EllipticKeyAddr *KeyAddr)
This function generates Public Key for a given curve type using private key where both keys located at 64 bit address.
CrvType Is a type of elliptic curve DAddr Address of static private key KeyAddr Pointer to public key address XST_SUCCESS - On successXSECURE_ELLIPTIC_NON_SUPPORTED_CRV - When elliptic Curve is not supportedXSECURE_ELLIPTIC_INVALID_PARAM - On invalid argumentXSECURE_ELLIPTIC_GEN_KEY_ERR - Error in generating Public key
References XSecure_EllipticKeyAddr::Qx, XSecure_EllipticKeyAddr::Qy, XSECURE_CORE_RSA_ECC, XSecure_CryptoCheck, XSECURE_ECC_NIST_P521, XSECURE_ECC_P521_SIZE_IN_BYTES, XSecure_ECCRandInit, XSECURE_ECDSA_P521_ALIGN_BYTES, XSECURE_ECDSA_RSA_BASEADDR, XSECURE_ECDSA_RSA_RESET_OFFSET, XSECURE_ELLIPTIC_GEN_KEY_ERR, XSECURE_ELLIPTIC_INVALID_PARAM, XSecure_GetData, XSecure_PutData, XSecure_ReleaseReset, XSecure_SetReset.
Referenced by XSecure_EllipticGenerateKey.
int XSecure_EllipticGenerateKey(XSecure_EllipticCrvTyp CrvType, const u8 *D, const XSecure_EllipticKey *Key)
This function generates Public Key for a given curve type.
CrvType Is a type of elliptic curve D Pointer to static private key Key Pointer to public key XST_SUCCESS - On successXSECURE_ELLIPTIC_NON_SUPPORTED_CRV - When elliptic Curve is not supportedXSECURE_ELLIPTIC_INVALID_PARAM - On invalid argument
References XSecure_EllipticKey::Qx, XSecure_EllipticKeyAddr::Qx, XSecure_EllipticKey::Qy, XSecure_EllipticKeyAddr::Qy, XSECURE_ECC_NIST_P192, XSECURE_ECC_NIST_P224, XSECURE_ECC_NIST_P256, XSECURE_ECC_NIST_P384, XSECURE_ECC_NIST_P521, XSECURE_ELLIPTIC_INVALID_PARAM, XSecure_EllipticGenerateKey_64Bit.
int XSecure_EllipticGenerateSignature_64Bit(XSecure_EllipticCrvTyp CrvType, const XSecure_EllipticHashData *HashInfo, const u64 DAddr, const u64 KAddr, const XSecure_EllipticSignAddr *SignAddr)
This function generates signature for a given hash and curve type where data is located at 64-bit address.
CrvType Type of elliptic curve HashInfo Pointer to Hash Data i.e. Hash Address and length DAddr Address of the static private key KAddr Ephemeral private key SignAddr Pointer to signature address XST_SUCCESS - On successXSECURE_ELLIPTIC_INVALID_PARAM - On invalid argumentXSECURE_ELLIPTIC_NON_SUPPORTED_CRV - If curve data pointer is NULLXSECURE_ELLIPTIC_GEN_SIGN_BAD_RAND_NUM - When Bad random number used for sign generationXSECURE_ELLIPTIC_GEN_SIGN_INCORRECT_HASH_LEN Incorrect hash length for sign generationXST_FAILURE - On any other failures K, the ephemeral private key, shall be an unpredictable (cryptographically secure) random number unique for each signature Note that reuse or external predictability of this number generally breaks the security of ECDSA
References XSecure_EllipticHashData::Addr, EcdsaCrvInfo::Bits, XSecure_EllipticHashData::Len, XSecure_EllipticSignAddr::SignR, XSecure_EllipticSignAddr::SignS, XSECURE_CORE_RSA_ECC, XSecure_CryptoCheck, XSECURE_ECC_NIST_P521, XSECURE_ECC_P521_SIZE_IN_BYTES, XSecure_ECCRandInit, XSECURE_ECDSA_P521_ALIGN_BYTES, XSECURE_ECDSA_RSA_BASEADDR, XSECURE_ECDSA_RSA_RESET_OFFSET, XSECURE_ELLIPTIC_GEN_SIGN_BAD_RAND_NUM, XSECURE_ELLIPTIC_GEN_SIGN_INCORRECT_HASH_LEN, XSECURE_ELLIPTIC_INVALID_PARAM, XSecure_GetData, XSecure_PutData, XSecure_ReleaseReset, XSecure_SetReset.
Referenced by XSecure_EllipticGenerateSignature, XSecure_EllipticPwct.
int XSecure_EllipticGenerateSignature(XSecure_EllipticCrvTyp CrvType, const u8 *Hash, const u32 HashLen, const u8 *D, const u8 *K, const XSecure_EllipticSign *Sign)
This function generates signature for a given hash and curve type.
CrvType Type of elliptic curve Hash Pointer to the hash for which sign has to be generated HashLen Length of the hash in bytes D Pointer to the static private key K Ephemeral private key Sign Pointer to the signature XST_SUCCESS - On successXSECURE_ELLIPTIC_INVALID_PARAM - On invalid argument K, the ephemeral private key, shall be an unpredictable (cryptographically secure) random number unique for each signature Note that reuse or external predictability of this number generally breaks the security of ECDSA
References XSecure_EllipticHashData::Addr, XSecure_EllipticHashData::Len, XSecure_EllipticSign::SignR, XSecure_EllipticSignAddr::SignR, XSecure_EllipticSign::SignS, XSecure_EllipticSignAddr::SignS, XSECURE_ECC_NIST_P192, XSECURE_ECC_NIST_P224, XSECURE_ECC_NIST_P256, XSECURE_ECC_NIST_P384, XSECURE_ECC_NIST_P521, XSECURE_ECC_P521_SIZE_IN_BYTES, XSECURE_ELLIPTIC_INVALID_PARAM, XSecure_EllipticGenerateSignature_64Bit.
Referenced by XSecure_EllipticGenEphemeralNSign, XSecure_EllipticSignGenerateKat, XSecure_TestP384.
int XSecure_EllipticValidateKey_64Bit(XSecure_EllipticCrvTyp CrvType, const XSecure_EllipticKeyAddr *KeyAddr)
This function validates the public key for a given curve type where key is located at 64-bit address.
CrvType Type of elliptic curve KeyAddr Pointer to public key address XST_SUCCESS - On successXSECURE_ELLIPTIC_INVALID_PARAM - On invalid argumentXSECURE_ELLIPTIC_NON_SUPPORTED_CRV - If curve data pointer is NULLXSECURE_ELLIPTIC_KEY_ZERO - When Public key is zeroXSECURE_ELLIPTIC_KEY_WRONG_ORDER Wrong order of Public keyXSECURE_ELLIPTIC_KEY_NOT_ON_CRV - When Key is not found on the curveXST_FAILURE - On any other failures
References XSecure_EllipticKeyAddr::Qx, XSecure_EllipticKeyAddr::Qy, XSECURE_CORE_RSA_ECC, XSecure_CryptoCheck, XSECURE_ECC_NIST_P521, XSECURE_ECC_P521_SIZE_IN_BYTES, XSECURE_ECDSA_P521_ALIGN_BYTES, XSECURE_ECDSA_RSA_BASEADDR, XSECURE_ECDSA_RSA_RESET_OFFSET, XSECURE_ELLIPTIC_INVALID_PARAM, XSECURE_ELLIPTIC_KEY_NOT_ON_CRV, XSECURE_ELLIPTIC_KEY_WRONG_ORDER, XSECURE_ELLIPTIC_KEY_ZERO, XSecure_PutData, XSecure_ReleaseReset, XSecure_SetReset.
Referenced by XSecure_EllipticValidateKey.
int XSecure_EllipticValidateKey(XSecure_EllipticCrvTyp CrvType, const XSecure_EllipticKey *Key)
This function validates the public key for a given curve type.
CrvType Type of elliptic curve Key Pointer to the public key XST_SUCCESS - On successXSECURE_ELLIPTIC_INVALID_PARAM - On invalid argument
References XSecure_EllipticKey::Qx, XSecure_EllipticKeyAddr::Qx, XSecure_EllipticKey::Qy, XSecure_EllipticKeyAddr::Qy, XSECURE_ECC_NIST_P192, XSECURE_ECC_NIST_P224, XSECURE_ECC_NIST_P256, XSECURE_ECC_NIST_P384, XSECURE_ECC_NIST_P521, XSECURE_ELLIPTIC_INVALID_PARAM, XSecure_EllipticValidateKey_64Bit.
int XSecure_EllipticVerifySign_64Bit(XSecure_EllipticCrvTyp CrvType, const XSecure_EllipticHashData *HashInfo, const XSecure_EllipticKeyAddr *KeyAddr, const XSecure_EllipticSignAddr *SignAddr)
This function verifies the signature for a given hash, key and curve type where data is located at 64-bit address.
CrvType Type of elliptic curve HashInfo Pointer to Hash Data i.e. Hash Address and length KeyAddr Pointer to public key address SignAddr Pointer to signature address XST_SUCCESS - On successXSECURE_ELLIPTIC_INVALID_PARAM - On invalid argumentXSECURE_ELLIPTIC_NON_SUPPORTED_CRV - If curve data pointer is NULLXSECURE_ELLIPTIC_BAD_SIGN - When signature provided for verification is badXSECURE_ELLIPTIC_VER_SIGN_INCORRECT_HASH_LEN Incorrect hash length for sign verificationXSECURE_ELLIPTIC_VER_SIGN_R_ZERO R set to zeroXSECURE_ELLIPTIC_VER_SIGN_S_ZERO S set to zeroXSECURE_ELLIPTIC_VER_SIGN_R_ORDER_ERROR R is not within ECC orderXSECURE_ELLIPTIC_VER_SIGN_S_ORDER_ERROR S is not within ECC orderXST_FAILURE - On any other failures
References XSecure_EllipticHashData::Addr, EcdsaCrvInfo::Bits, XSecure_EllipticHashData::Len, XSecure_EllipticKeyAddr::Qx, XSecure_EllipticKeyAddr::Qy, XSecure_EllipticSignAddr::SignR, XSecure_EllipticSignAddr::SignS, XSECURE_CORE_RSA_ECC, XSecure_CryptoCheck, XSECURE_ECC_NIST_P521, XSECURE_ECC_P521_SIZE_IN_BYTES, XSECURE_ECDSA_P521_ALIGN_BYTES, XSECURE_ECDSA_RSA_BASEADDR, XSECURE_ECDSA_RSA_RESET_OFFSET, XSECURE_ELLIPTIC_BAD_SIGN, XSECURE_ELLIPTIC_INVALID_PARAM, XSECURE_ELLIPTIC_VER_SIGN_INCORRECT_HASH_LEN, XSECURE_ELLIPTIC_VER_SIGN_R_ORDER_ERROR, XSECURE_ELLIPTIC_VER_SIGN_R_ZERO, XSECURE_ELLIPTIC_VER_SIGN_S_ORDER_ERROR, XSECURE_ELLIPTIC_VER_SIGN_S_ZERO, XSecure_PutData, XSecure_ReleaseReset, XSecure_SetReset.
Referenced by XSecure_EllipticPwct, XSecure_EllipticVerifySign.
int XSecure_EllipticVerifySign(XSecure_EllipticCrvTyp CrvType, const u8 *Hash, const u32 HashLen, const XSecure_EllipticKey *Key, const XSecure_EllipticSign *Sign)
This function verifies the signature for a given hash, key and curve type.
CrvType Type of elliptic curve Hash Pointer to the hash for which sign has to be generated HashLen Length of hash in bytes Key Pointer to the public key Sign Pointer to the signature XST_SUCCESS - On successXSECURE_ELLIPTIC_INVALID_PARAM - On invalid argument
References XSecure_EllipticHashData::Addr, XSecure_EllipticHashData::Len, XSecure_EllipticKey::Qx, XSecure_EllipticKeyAddr::Qx, XSecure_EllipticKey::Qy, XSecure_EllipticKeyAddr::Qy, XSecure_EllipticSign::SignR, XSecure_EllipticSignAddr::SignR, XSecure_EllipticSign::SignS, XSecure_EllipticSignAddr::SignS, XSECURE_ECC_NIST_P192, XSECURE_ECC_NIST_P224, XSECURE_ECC_NIST_P256, XSECURE_ECC_NIST_P384, XSECURE_ECC_NIST_P521, XSECURE_ECC_P521_SIZE_IN_BYTES, XSECURE_ELLIPTIC_INVALID_PARAM, XSecure_EllipticVerifySign_64Bit.
void XSecure_PutData(const u32 Size, u8 *Dst, const u64 SrcAddr)
This function copies data from 32/64 bit address to local buffer.
Size Length of data in bytes Dst Pointer to the destination buffer SrcAddr Source address
References XSECURE_ELLIPTIC_LITTLE_ENDIAN.
Referenced by XSecure_EcdhGetSecret, XSecure_EllipticGenerateKey_64Bit, XSecure_EllipticGenerateSignature_64Bit, XSecure_EllipticValidateKey_64Bit, XSecure_EllipticVerifySign_64Bit.
void XSecure_GetData(const u32 Size, const u8 *Src, const u64 DstAddr)
This function copies data to 32/64 bit address from local buffer.
Size Length of data in bytes Src Pointer to the source buffer DstAddr Destination address
References XSECURE_ELLIPTIC_LITTLE_ENDIAN.
Referenced by XSecure_EcdhGetSecret, XSecure_EllipticGenerateEphemeralKey, XSecure_EllipticGenerateKey_64Bit, XSecure_EllipticGenerateSignature_64Bit, XSecure_EllipticPrvtKeyGenerate.
void XSecure_FixEndiannessNCopy(const u32 Size, u64 DstAddr, const u64 SrcAddr)
This function copies data to destination based on library endianness selection.
- Changes the endianness when library is operating in little endian - Copies data without changing any endianness when library is operating in big endain. Size Length of data in bytes SrcAddr Address of the source buffer DstAddr Destination address This is the helper function to convert the endianness as required.
References XSECURE_ELLIPTIC_LITTLE_ENDIAN.
u32 XSecure_EllipticGetCrvSize(const XSecure_EllipticCrvTyp CrvType)
This function gets curve size in bytes.
CrvType Is a type of elliptic curve CrvSize Size of curve in bytes
References EcdsaCrvInfo::Bits, XSECURE_ECDSA_ALGN_CRV_SIZE_IN_BYTES, XSECURE_ECDSA_BITS_IN_BYTES, XSecure_EllipticGetCrvData.