xsecure_ellipticplat.c
XSECURE_ECC_TRNG_RANDOM_NUM_GEN_LEN
Length of xilsecure ecc true random number generator.
Referenced by XSecure_EllipticGenerateEphemeralKey, XSecure_EllipticPrvtKeyGenerate.
EcdsaCrvInfo * XSecure_EllipticGetCrvData(XSecure_EllipticCrvTyp CrvTyp)
This function gets the curve related information.
CrvTyp Type of the elliptic curve Crv Curve information
References XSECURE_ECC_NIST_P192, XSECURE_ECC_NIST_P224, XSECURE_ECC_NIST_P256, XSECURE_ECC_NIST_P384, XSECURE_ECC_NIST_P521, XSecure_EllipticCrvsGetCount.
Referenced by XSecure_EcdhGetSecret, XSecure_EllipticGenerateEphemeralKey, XSecure_EllipticGetCrvSize, XSecure_EllipticPrvtKeyGenerate.
int XSecure_EllipticPrvtKeyGenerate(XSecure_EllipticCrvTyp CrvType, XSecure_ElliptcPrivateKeyGen *PrivateKey)
This function generates 48-byte key for P-384 curve using TRNG.
CrvType specifies the type of the ECC curve. PrivateKey is the pointer to XSecure_ElliptcPrivateKeyGen XST_SUCCESS - On successXSECURE_ELLIPTIC_INVALID_PARAM - If any input parameter is invalidXST_FAILURE - On failure This API expects TRNG HW to be in HEALTHY state, This can be achieved by running preoperational health tests.
References XSecure_ElliptcPrivateKeyGen::KeyOutPutAddr, XSecure_ElliptcPrivateKeyGen::PerStringAddr, XSecure_ElliptcPrivateKeyGen::SeedAddr, XSecure_ElliptcPrivateKeyGen::SeedLength, XSECURE_CLEAR_BIT, XSECURE_ECC_NIST_P384, XSECURE_ECC_NIST_P521, XSECURE_ECC_P384_SIZE_IN_BYTES, XSECURE_ECC_PRVT_KEY_GEN_ERR, XSECURE_ECC_TRNG_RANDOM_NUM_GEN_LEN, XSECURE_ECDSA_RSA_BASEADDR, XSECURE_ECDSA_RSA_RESET_OFFSET, XSECURE_ELLIPTIC_INVALID_PARAM, XSecure_EllipticGetCrvData, XSecure_GetData, XSecure_GetTrngInstance, XSecure_ReleaseReset, XSecure_SetReset, XSECURE_TRNG_DRNG_MODE, XSECURE_TRNG_SEC_STRENGTH_IN_BYTES, XSecure_TrngGenerate, XSecure_TrngInitNCfgMode, XSecure_Uninstantiate, XSecure_UpdateTrngCryptoStatus.
int XSecure_EllipticGenerateEphemeralKey(XSecure_EllipticCrvTyp CrvType, u32 EphemeralKeyAddr)
This function generates 48-byte ephemeral key for P-384 curve using TRNG.
CrvType Specifies the type of the ECC curve. EphemeralKeyAddr Address of ephemeral key XST_SUCCESS - On successXSECURE_ELLIPTIC_INVALID_PARAM - If any input parameter is invalidXST_FAILURE - On failure This API expects TRNG HW to be in HEALTHY state, This can be achieved by running preoperational health tests.
References XSECURE_ECC_NIST_P384, XSECURE_ECC_NIST_P521, XSECURE_ECC_P384_SIZE_IN_BYTES, XSECURE_ECC_PRVT_KEY_GEN_ERR, XSECURE_ECC_TRNG_RANDOM_NUM_GEN_LEN, XSECURE_ECDSA_RSA_BASEADDR, XSECURE_ECDSA_RSA_RESET_OFFSET, XSECURE_ELLIPTIC_INVALID_PARAM, XSecure_EllipticGetCrvData, XSecure_GetData, XSecure_GetRandomNum, XSecure_ReleaseReset, XSecure_SetReset.
Referenced by XSecure_EllipticGenEphemeralNSign.
int XSecure_EllipticGenEphemeralNSign(XSecure_EllipticCrvTyp CrvType, const u8 *Hash, u32 HashLen, u8 *PrvtKey, u8 *Signature)
This function generates the signature on provided hash using ecc.
CrvType specifies the type of the ECC curve. Hash is the pointer to the hash of the data to be signed HashLen is the length of the hash. PrvtKey is the pointer to ECC private key. Signature is the pointer to the buffer where the ECC signature shall be stored. XST_SUCCESS - On successXSECURE_ELLIPTIC_INVALID_PARAM - If any input parameter is invalidXST_FAILURE - On failure
References XSECURE_ECC_NIST_P521, XSECURE_ECC_P384_SIZE_IN_BYTES, XSECURE_ELLIPTIC_INVALID_PARAM, XSecure_EllipticGenerateEphemeralKey, XSecure_EllipticGenerateSignature.
int XSecure_EcdhGetSecret(XSecure_EllipticCrvTyp CrvType, u64 PrvtKeyAddr, u64 PubKeyAddr, u64 SharedSecretAddr)
This is a wrapper function which calls the third-party API to perform ECDH and generate shared secret.
CrvType Curve Type of the keys used to generate shared secret PrvtKeyAddr 64-bit address of the private key PubKeyAddr 64-bit address of public key SharedSecretAddr 64-bit address of buffer for storing shared secret XST_SUCCESS - On successXSECURE_ELLIPTIC_INVALID_PARAM - If any input parameter is invalidXSECURE_ELLIPTIC_NON_SUPPORTED_CRV - If elliptic curve data received is NULLXST_FAILURE - On failure Shared secret is calculated by performing scalar multiplication on public key and private key provided as input.
References XSecure_EllipticKeyAddr::Qx, XSecure_EllipticKeyAddr::Qy, XSECURE_CORE_RSA_ECC, XSecure_CryptoCheck, XSECURE_ECC_NIST_P256, XSECURE_ECC_NIST_P384, XSECURE_ECC_NIST_P521, XSECURE_ECC_P256_SIZE_IN_BYTES, XSECURE_ECC_P384_SIZE_IN_BYTES, XSECURE_ECC_P521_SIZE_IN_BYTES, XSecure_ECCRandInit, XSECURE_ECDSA_P521_ALIGN_BYTES, XSECURE_ECDSA_RSA_BASEADDR, XSECURE_ECDSA_RSA_RESET_OFFSET, XSECURE_ELLIPTIC_INVALID_PARAM, XSecure_EllipticGetCrvData, XSecure_GetData, XSecure_PutData, XSecure_ReleaseReset, XSecure_SetReset.