xsecure_rsaclient.c
int XSecure_RsaPrivateDecrypt(XSecure_ClientInstance *InstancePtr, const u64 KeyAddr, const u64 InDataAddr, const u32 Size, const u64 OutDataAddr)
This function sends IPI request to Perform RSA decryption with private key.
InstancePtr Pointer to the client instance KeyAddr Address of the Key InDataAddr Address of the data which has to be decrypted Size Key size in bytes, Input size also should be same as key size mentioned. Inputs supported are XSECURE_RSA_4096_KEY_SIZE, XSECURE_RSA_2048_KEY_SIZE, or XSECURE_RSA_3072_KEY_SIZE OutDataAddr Address of the buffer where resultant decrypted data to be stored XST_SUCCESS If the update is successfulXST_FAILURE If there is a failure
References XSECURE_ADDR_HIGH_SHIFT, XSECURE_API_RSA_PRIVATE_DECRYPT, XSecure_DCacheFlushRange, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
Referenced by XSecure_RsaCore, XSecure_RsaPrivateDecryptKat.
int XSecure_RsaPublicEncrypt(XSecure_ClientInstance *InstancePtr, const u64 KeyAddr, const u64 InDataAddr, const u32 Size, const u64 OutDataAddr)
This function sends IPI request to Perform RSA encryption with public key.
InstancePtr Pointer to the client instance KeyAddr Address of the Key InDataAddr Address of the data which has to be encrypted with public key Size Key size in bytes, Input size also should be same as key size mentioned. Inputs supported are XSECURE_RSA_4096_KEY_SIZE, XSECURE_RSA_2048_KEY_SIZE, or XSECURE_RSA_3072_KEY_SIZE OutDataAddr Address of the buffer where resultant decrypted data to be stored XST_SUCCESS If encryption was successfulXST_FAILURE If there is a failure
References XSECURE_ADDR_HIGH_SHIFT, XSECURE_API_RSA_PUBLIC_ENCRYPT, XSecure_DCacheFlushRange, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
Referenced by main, XSecure_DataAuth, XSecure_RsaCore, XSecure_RsaPublicEncryptKat, XSecure_SpkAuthentication.
int XSecure_RsaSignVerification(XSecure_ClientInstance *InstancePtr, const u64 SignAddr, const u64 HashAddr, const u32 Size)
This function sends IPI request to Perform RSA sign verification.
InstancePtr Pointer to the client instance SignAddr Address of the buffer which holds the decrypted RSA signature. HashAddr Address of the HashAddr which has the hash calculated on the data to be authenticated Size Length of Hash used For SHA3 it should be 48 bytes XST_SUCCESS If decryption was successfulXST_FAILURE In case of mismatch
References XSECURE_ADDR_HIGH_SHIFT, XSECURE_API_RSA_SIGN_VERIFY, XSecure_DCacheFlushRange, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
Referenced by XSecure_DataAuth, XSecure_SpkAuthentication.