xsecure_lms_core.c
XSECURE_LMS_PUB_KEY_TMP_BUF_ADJ_NODE_VAL_INDEX
LMS public key temporary buffer adjustment node value index.
Referenced by XSecure_LmsSignatureVerification.
volatile XSecure_LmsPublicKey AuthenticatedKey
XSecure_LmsDataDigestFixedFields DigestPrefixFields
volatile u32 SignatureLengthConsumed
XSecure_LmsDataDigest DigestChecksum
u32 CurrentLmsQ
static int XSecure_LmsOtsSignatureCompute(XSecure_Sha *ShaInstPtr, XPmcDma *DmaPtr, u8 *Data, u32 DataLen, u32 PreHashedMsg, u8 *LmsOtsSignatureBuff, u32 LmsOtsSignatureLen, XSecure_LmsOtsType LmsOtsExpectedType, u8 *Kc)
This function takes in LMS OTS Signature and produces LMS OTS Public key, which in turn is used to calculate the root public key of Merkle tree.
ShaInstPtr Pointer to the SHA instance. DmaPtr Pointer to the DMA instance. Data Pointer to the data to be authenticated DataLen Length of data to be authenticated PreHashedMsg If TRUE, then Data contains digest, if FALSE contains raw msg to be authenticated LmsOtsSignatureBuff Pointer to OTS signature buffer LmsOtsSignatureLen Length of OTS signature buffer LmsOtsExpectedType Expected OTS signature type, value read from public key of this level XSecure_LmsOtsType Kc Buffer where the computed value of root needs to be copied, assumed that has enough place XST_SUCCESS - If operation succeedsXSECURE_LMS_INVALID_PARAM - If input parameters are invalidXSECURE_LMS_OTS_PUB_KEY_SIGN_TYPE_MISMATCH_ERROR - If signature type mismatchXSECURE_LMS_OTS_SIGN_UNSUPPORTED_TYPE_ERROR - If unsupported signature typeXSECURE_LMS_OTS_DIGEST_CHECKSUM_OP_FAILED_ERROR - If digest checksum operation failsXSECURE_AUTH_LMS_DIGEST_CHECKSUM_FAILED_ERROR - If checksum computation failsXSECURE_ERR_GLITCH_DETECTED - If outer digit loop glitch is detectedXST_FAILURE - On failure
static u32 XSecure_SwapBytes(const u8 *const source, size_t bytes)
This function get bytes from buffer, to a unsigned int value, Changes endianness.
source - pointer to source buffer bytes - number of bytes to be extracted Resultant value
int XSecure_LmsSignatureVerification(XSecure_Sha *ShaInstPtr, XPmcDma *DmaPtr, XSecure_LmsSignVerifyParams *LmsSignVerifyParams)
This function performs LMS level signature verification.
ShaInstPtr Pointer to SHA instance DmaPtr Pointer to DMA instance LmsSignVerifyParams Pointer to LMS signature verification parameters XST_SUCCESS - On successXSECURE_LMS_INVALID_PARAM - Invalid parameter providedXSECURE_LMS_PUB_KEY_UNSUPPORTED_TYPE_1_ERROR - Public key LMS type is unsupportedXSECURE_LMS_SIGN_EXPECTED_PUB_KEY_LEN_2_ERROR - Expected public key length mismatchXSECURE_LMS_SIGN_LEN_1_ERROR - Signature length is insufficientXSECURE_LMS_OTS_PUB_KEY_LMS_OTS_SIGN_TYPE_MISMATCH_ERROR - OTS signature type mismatch with public keyXSECURE_LMS_SIGN_UNSUPPORTED_OTS_TYPE_1_ERROR - OTS signature type is unsupportedXSECURE_LMS_SIGN_LEN_2_ERROR - Signature length error for OTS componentXSECURE_LMS_PUB_KEY_LMS_SIGN_TYPE_MISMATCH_ERROR - LMS signature type mismatch with public keyXSECURE_LMS_SIGN_UNSUPPORTED_TYPE_1_ERROR - LMS signature type is unsupportedXSECURE_LMS_SIGN_INVALID_NODE_NUMBER_ERROR - Invalid node number in signatureXSECURE_LMS_SIGN_LEN_3_ERROR - Total signature length mismatchXSECURE_LMS_SIGN_OTS_OP_ERROR - OTS signature computation operation failedXSECURE_LMS_SIGN_VERIF_SHA_DIGEST_LEAF_FAILED_ERROR - SHA digest failed for leaf nodeXSECURE_LMS_PUB_KEY_AUTHENTICATION_FAILED_ERROR - Public key authentication failedXSECURE_LMS_PUB_KEY_AUTHENTICATION_GLITCH_ERROR - Public key authentication glitch detectedXST_FAILURE - On any other failure
References XSecure_LmsPubKeyTmp_::D, XSecure_LmsSignVerifyParams::Data, XSecure_LmsSignVerifyParams::DataLen, XSecure_LmsSignVerifyParams::ExpectedPubKey, XSecure_LmsPubKeyTmp_::Fields, XSecure_LmsDataDigestFixedFields_::Fields, XSecure_LmsParam::h, XSecure_LmsOtsParam::H, XSecure_LmsPubKeyTmp_::half_node_number, XSecure_LmsPubKeyTmp_::I, XSecure_LmsDataDigestFixedFields_::I, XSecure_LmsSignVerifyParams::LmsSign, XSecure_LmsSignVerifyParams::LmsSignLen, XSecure_LmsParam::m, XSecure_LmsParam::mh, XSecure_LmsSignVerifyParams::PreHashedMsg, XSecure_LmsSignVerifyParams::PubKeyLen, XSecure_LmsDataDigestFixedFields_::q, XSecure_LmsOtsParam::SignLen, XSecure_LmsPubKeyTmp_::Tmp, XSECURE_DEBUG_GENERAL, XSECURE_IS_ODD, XSECURE_LMS_I_FIELD_SIZE, XSECURE_LMS_INVALID_PARAM, XSECURE_LMS_M_BYTE_FIELD_SIZE, XSECURE_LMS_MEM_COPY_ERROR, XSECURE_LMS_NOT_SUPPORTED, XSECURE_LMS_OTS_NOT_SUPPORTED, XSECURE_LMS_OTS_PUB_KEY_K_FIELD_SIZE, XSECURE_LMS_OTS_PUB_KEY_LMS_OTS_SIGN_TYPE_MISMATCH_ERROR, XSECURE_LMS_OTS_SIGN_TYPE_FIELD_OFFSET, XSECURE_LMS_OTS_TYPE_SIZE, XSECURE_LMS_PUB_KEY_AUTHENTICATION_FAILED_ERROR, XSECURE_LMS_PUB_KEY_AUTHENTICATION_GLITCH_ERROR, XSECURE_LMS_PUB_KEY_FIXED_FIELD_SIZE, XSECURE_LMS_PUB_KEY_I_OFFSET, XSECURE_LMS_PUB_KEY_LMS_SIGN_TYPE_MISMATCH_ERROR, XSECURE_LMS_PUB_KEY_OTS_TYPE_OFFSET, XSECURE_LMS_PUB_KEY_T_FIELD_SIZE, XSECURE_LMS_PUB_KEY_T_OFFSET, XSECURE_LMS_PUB_KEY_TMP_BUF_ADJ_NODE_VAL_INDEX, XSECURE_LMS_PUB_KEY_TMP_BUFFER_INTR_TOTAL_SIZE, XSECURE_LMS_PUB_KEY_TMP_BUFFER_LEAF_TOTAL_SIZE, XSECURE_LMS_PUB_KEY_TYPE_OFFSET, XSECURE_LMS_PUB_KEY_UNSUPPORTED_TYPE_1_ERROR, XSECURE_LMS_Q_FIELD_SIZE, XSECURE_LMS_SIGN_EXPECTED_PUB_KEY_LEN_2_ERROR, XSECURE_LMS_SIGN_INVALID_NODE_NUMBER_ERROR, XSECURE_LMS_SIGN_LEN_1_ERROR, XSECURE_LMS_SIGN_LEN_2_ERROR, XSECURE_LMS_SIGN_LEN_3_ERROR, XSECURE_LMS_SIGN_UNSUPPORTED_OTS_TYPE_1_ERROR, XSECURE_LMS_SIGN_UNSUPPORTED_TYPE_1_ERROR, XSECURE_LMS_SIGN_VERIF_SHA_DIGEST_INTR_EVEN_FAILED_ERROR, XSECURE_LMS_SIGN_VERIF_SHA_DIGEST_INTR_ODD_FAILED_ERROR, XSECURE_LMS_SIGNATURE_OTS_FIELD_OFFSET, XSECURE_LMS_SIGNATURE_Q_FIELD_OFFSET, XSECURE_LMS_TYPE_SIZE, XSecure_LmsLookupParamSet, XSecure_LmsOtsLookupParamSet, XSecure_Printf, XSecure_ShaDigest.
Referenced by XSecure_HssFinish, XSecure_HssInit, XSecure_LmsSha2256Kat, XSecure_LmsShake256Kat.
int XSecure_HssInit(XSecure_Sha *ShaInstPtr, XPmcDma *DmaPtr, XSecure_HssInitParams *HssInitParams)
This function Initiates LMS Signature verification process.
Completes all upper level Merkle trees verification and prepares for data's Digest calculation ShaInstPtr Pointer to SHA instance DmaPtr Pointer to DMA instance HssInitParams Pointer to HSS initialization parameters XST_SUCCESS - On successXSECURE_LMS_INVALID_PARAM - Invalid parameter providedXSECURE_LMS_HSS_PUB_KEY_INVALID_LEN_2_ERROR - HSS public key length is invalidXSECURE_LMS_HSS_SIGN_LEVEL_UNSUPPORTED_ERROR - HSS signature level is not supportedXSECURE_LMS_HSS_SIGN_PUB_KEY_LEVEL_MISMATCH_ERROR - HSS signature and public key level mismatchXSECURE_LMS_HSS_L0_PUB_KEY_LMS_TYPE_UNSUPPORTED_ERROR - Level 0 public key LMS type is unsupportedXSECURE_LMS_HSS_L0_PUB_KEY_LMS_OTS_TYPE_UNSUPPORTED_ERROR - Level 0 public key LMS OTS type is unsupportedXSECURE_LMS_SIGN_VERIFY_BH_AND_TYPE_SHA_ALGO_MISMATCH_L0_ERROR - SHA algorithm mismatch at level 0XSECURE_LMS_HSS_L0_SIGN_INVALID_LEN_2_ERROR - Level 0 signature length is invalidXSECURE_LMS_HSS_L0_PUB_KEY_AUTH_FAILED_ERROR - Level 0 public key authentication failedXSECURE_LMS_PUB_OP_FAILED_ERROR - Public key operation failedXSECURE_LMS_PUB_OP_FAILED_1_ERROR - Public key operation failedXSECURE_LMS_HSS_L1_PUB_KEY_LMS_TYPE_1_UNSUPPORTED_ERROR - Level 1 public key LMS type is unsupportedXST_FAILURE - On any other failure
References XSecure_LmsDataDigestFixedFields_::C, XSecure_LmsSignVerifyParams::Data, XSecure_LmsSignVerifyParams::DataLen, XSecure_LmsSignVerifyParams::ExpectedPubKey, XSecure_LmsPublicKey_::Fields, XSecure_LmsDataDigestFixedFields_::Fields, XSecure_LmsParam::H, XSecure_LmsOtsParam::H, XSecure_ShaPlatConfig::HashAlgo, XSecure_LmsPublicKey_::I, XSecure_LmsDataDigestFixedFields_::I, XSecure_LmsSignVerifyParams::LmsSign, XSecure_LmsSignVerifyParams::LmsSignLen, XSecure_LmsParam::mh, XSecure_LmsSignVerifyParams::PreHashedMsg, XSecure_LmsSignVerifyParams::PubKeyLen, XSecure_HssInitParams::PublicKey, XSecure_HssInitParams::PublicKeyLen, XSecure_LmsDataDigestFixedFields_::q, XSecure_HssInitParams::SignatureLen, XSecure_HssInitParams::SignBuff, XSecure_LmsOtsParam::SignLen, XSECURE_ALLFS, XSECURE_DEBUG_GENERAL, XSECURE_ERR_GLITCH_DETECTED, XSECURE_HSS_PUBLIC_KEY_LEVEL_FIELD_OFFSET, XSECURE_HSS_PUBLIC_KEY_LMS_FIELD_OFFSET, XSECURE_HSS_PUBLIC_KEY_TOTAL_SIZE, XSECURE_HSS_SIGN_LIST_LEVEL_FIELD_OFFSET, XSECURE_LMS_C_FIELD_SIZE, XSECURE_LMS_HSS_L0_PUB_KEY_LMS_OTS_TYPE_UNSUPPORTED_ERROR, XSECURE_LMS_HSS_L0_PUB_KEY_LMS_TYPE_UNSUPPORTED_ERROR, XSECURE_LMS_HSS_L0_SIGN_INVALID_LEN_2_ERROR, XSECURE_LMS_HSS_L1_PUB_KEY_LMS_TYPE_1_UNSUPPORTED_ERROR, XSECURE_LMS_HSS_LEVELS_FIELD_SIZE, XSECURE_LMS_HSS_MAX_LEVELS_SUPPORTED, XSECURE_LMS_HSS_MIN_LEVELS_SUPPORTED, XSECURE_LMS_HSS_PUB_KEY_INVALID_LEN_2_ERROR, XSECURE_LMS_HSS_SIGN_LEVEL_UNSUPPORTED_ERROR, XSECURE_LMS_HSS_SIGN_PUB_KEY_LEVEL_MISMATCH_ERROR, XSECURE_LMS_I_FIELD_SIZE, XSECURE_LMS_INVALID_PARAM, XSECURE_LMS_MEM_COPY_ERROR, XSECURE_LMS_NOT_SUPPORTED, XSECURE_LMS_OTS_NOT_SUPPORTED, XSECURE_LMS_OTS_SIGN_C_FIELD_OFFSET, XSECURE_LMS_OTS_TYPE_SIZE, XSECURE_LMS_PUB_KEY_OTS_TYPE_OFFSET, XSECURE_LMS_PUB_KEY_TOTAL_SIZE, XSECURE_LMS_PUB_KEY_TYPE_OFFSET, XSECURE_LMS_PUB_OP_FAILED_1_ERROR, XSECURE_LMS_PUB_OP_FAILED_ERROR, XSECURE_LMS_Q_FIELD_SIZE, XSECURE_LMS_SIGN_VERIFY_BH_AND_TYPE_SHA_ALGO_MISMATCH_L0_ERROR, XSECURE_LMS_SIGNATURE_OTS_FIELD_OFFSET, XSECURE_LMS_SIGNATURE_Q_FIELD_OFFSET, XSECURE_LMS_TYPE_SIZE, XSecure_LmsLookupParamSet, XSecure_LmsOtsLookupParamSet, XSecure_LmsSignatureVerification, XSecure_Printf, XSecure_ShaInitialize.
Referenced by XSecure_HssSha2256Kat, XSecure_HssShake256Kat, XSecure_HssSignatureVerification.
int XSecure_LmsHashMessage(XSecure_Sha *ShaInstPtr, u8 *Data, u32 DataLen, XSecure_ShaMode Mode)
This function calculates the Digest of data to authenticate to initiate the process of LMS verification.
ShaInstPtr Pointer to the SHA instance. Data Pointer to the data to be authenticated DataLen Length of data to be authenticated Mode Mode of the SHA operation XST_SUCCESS - On successXSECURE_LMS_HSS_L1_PUB_KEY_LMS_TYPE_1_UNSUPPORTED_ERROR - Level 1 public key LMS type is unsupportedXSECURE_LMS_HSS_L0_PUB_KEY_LMS_OTS_TYPE_UNSUPPORTED_ERROR - Level 0 public key LMS OTS type is unsupportedXST_FAILURE - On SHA operation failure
References XSecure_LmsDataDigestFixedFields_::D_MESG, XSecure_LmsDataDigestFixedFields_::Fields, XSECURE_LMS_DIGEST_SIZE, XSECURE_LMS_MESSAGE_TO_DIGEST_PREFIX_SIZE, XSecure_ShaFinish, XSecure_ShaLastUpdate, XSecure_ShaStart, XSecure_ShaUpdate.
Referenced by XSecure_HssSha2256Kat, XSecure_HssShake256Kat, XSecure_HssSignatureVerification.
int XSecure_HssFinish(XSecure_Sha *ShaInstPtr, XPmcDma *DmaPtr, u8 *SignBuff, u32 SignatureLen)
This function Completes LMS Signature verification process.
Data should have been pre-processed before calling this function, by calling @ref XSecure_HssInit & @ref XSecure_LmsHashMessage in sequence ShaInstPtr Pointer to the SHA instance. DmaPtr Pointer to the DMA instance. SignBuff Pointer to Signature buffer SignatureLen Length of signature buffer XST_SUCCESS - On successXSECURE_LMS_HSS_L1_PUB_KEY_LMS_TYPE_2_UNSUPPORTED_ERROR - Level 1 public key LMS type is unsupportedXSECURE_LMS_HSS_L1_PUB_KEY_LMS_OTS_TYPE_UNSUPPORTED_ERROR - Level 1 public key LMS OTS type is unsupportedXSECURE_LMS_HSS_OTS_SIGN_INVALID_LEN_1_ERROR - OTS signature length is invalidXSECURE_LMS_HSS_L1_SIGN_INVALID_LEN_2_ERROR - Level 1 signature length is invalidXSECURE_LMS_HSS_L0_PUB_KEY_AUTH_FAILED_ERROR - Level 0 public key authentication failedXST_FAILURE - On signature verification failure
References XSecure_LmsSignVerifyParams::Data, XSecure_LmsSignVerifyParams::DataLen, XSecure_LmsSignVerifyParams::ExpectedPubKey, XSecure_LmsSignVerifyParams::LmsSign, XSecure_LmsSignVerifyParams::LmsSignLen, XSecure_LmsParam::mh, XSecure_LmsSignVerifyParams::PreHashedMsg, XSecure_LmsSignVerifyParams::PubKeyLen, XSecure_LmsOtsParam::SignLen, XSECURE_DEBUG_GENERAL, XSECURE_LMS_HSS_L1_PUB_KEY_LMS_OTS_TYPE_UNSUPPORTED_ERROR, XSECURE_LMS_HSS_L1_PUB_KEY_LMS_TYPE_2_UNSUPPORTED_ERROR, XSECURE_LMS_HSS_L1_SIGN_INVALID_LEN_2_ERROR, XSECURE_LMS_HSS_OTS_SIGN_INVALID_LEN_1_ERROR, XSECURE_LMS_NOT_SUPPORTED, XSECURE_LMS_OTS_NOT_SUPPORTED, XSECURE_LMS_OTS_TYPE_SIZE, XSECURE_LMS_PUB_KEY_OTS_TYPE_OFFSET, XSECURE_LMS_PUB_KEY_TOTAL_SIZE, XSECURE_LMS_PUB_KEY_TYPE_OFFSET, XSECURE_LMS_Q_FIELD_SIZE, XSECURE_LMS_TYPE_SIZE, XSecure_LmsLookupParamSet, XSecure_LmsOtsLookupParamSet, XSecure_LmsSignatureVerification, XSecure_Printf.
Referenced by XSecure_HssSha2256Kat, XSecure_HssShake256Kat, XSecure_HssSignatureVerification.
int XSecure_HssSignatureVerification(XSecure_Sha *ShaInstPtr, XPmcDma *DmaPtr, XSecure_HssInitParams *HssInitParams, u8 *Data, u32 DataLen)
This function performs complete HSS signature verification in a single call.
It internally calls HssInit, LmsHashMessage, and HssFinish in sequence. The hash algorithm mode is automatically determined from the authenticated public key. ShaInstPtr Pointer to SHA instance DmaPtr Pointer to DMA instance HssInitParams Pointer to HSS initialization parameters (signature buffer, public key, and their lengths) Data Pointer to the data to be verified DataLen Length of data to be verified XST_SUCCESS - On successError codes from XSecure_HssInit, XSecure_LmsHashMessage, or XSecure_HssFinish on failure
References XSecure_LmsParam::H, XSecure_HssInitParams::SignatureLen, XSecure_HssInitParams::SignBuff, XSecure_HssFinish, XSecure_HssInit, XSECURE_LMS_INVALID_PARAM, XSECURE_LMS_PUB_KEY_TYPE_OFFSET, XSECURE_LMS_TYPE_SIZE, XSecure_LmsHashMessage, XSecure_LmsLookupParamSet.
int XSecure_GetLmsHashAlgo(u32 PubAlgo, const u8 *const PubKey, XSecure_ShaMode *SignAlgo)
This function returns public key LMS type.
PubAlgo Algorithm selected by current PDI PubKey Pointer to PPK location, PPK is used to detect the variant of LMS selected SignAlgo Pointer to store the extracted LMS hash algorithm XST_SUCCESS - On successXSECURE_LMS_HSS_L0_PUB_KEY_LMS_TYPE_UNSUPPORTED_ERROR - Level 0 public key LMS type is unsupportedXSECURE_LMS_INVALID_PARAM - Invalid public algorithm providedXST_FAILURE - On parameter lookup failure
References XSecure_LmsParam::H, XSECURE_DEBUG_GENERAL, XSECURE_HSS_PUBLIC_KEY_LMS_FIELD_OFFSET, XSECURE_LMS_HSS_L0_PUB_KEY_LMS_TYPE_UNSUPPORTED_ERROR, XSECURE_LMS_INVALID_PARAM, XSECURE_LMS_NOT_SUPPORTED, XSECURE_LMS_PUB_KEY_TYPE_OFFSET, XSECURE_LMS_TYPE_SIZE, XSecure_LmsLookupParamSet, XSecure_Printf.