xsecure_lms.c
int XSecure_LmsLookupParamSet(XSecure_LmsType Type, XSecure_LmsParam **Parameters)
This function returns the parameters for the type of LMS type.
Type XSecure_LmsType, type of OTS algorithm selected Parameters Pointer to array location where all predefined parameter values are present XSecure_LmsParam XST_SUCCESS - Valid type is passed, and parameters are assignedXST_FAILURE - If not a valid type is passed
References XSecure_LmsParam::H, XSECURE_ALLFS, XSECURE_LMS_NOT_SUPPORTED, XSECURE_LMS_RESERVED, XSECURE_LMS_SHA256_M32_H10, XSECURE_LMS_SHA256_M32_H15, XSECURE_LMS_SHA256_M32_H20, XSECURE_LMS_SHA256_M32_H5, XSECURE_LMS_SHAKE_M32_H10, XSECURE_LMS_SHAKE_M32_H15, XSECURE_LMS_SHAKE_M32_H20, XSECURE_LMS_SHAKE_M32_H5, XSECURE_LMS_TREE_HEIGHT_H10, XSECURE_LMS_TREE_HEIGHT_H15, XSECURE_LMS_TREE_HEIGHT_H20, XSECURE_LMS_TREE_HEIGHT_H5, XSECURE_LMS_TREE_HEIGHT_UNSUPPORTED, XSECURE_LMS_TYPE_LOOKUP_GLITCH_ERROR, XSECURE_LMS_TYPE_MAX_SUPPORTED, XSECURE_LMS_TYPE_UNSUPPORTED_ERROR, XSECURE_SHA2_256_HASH_LEN, XSECURE_SHAKE_256, XSECURE_SHAKE_256_HASH_LEN.
Referenced by XSecure_GetLmsHashAlgo, XSecure_HssFinish, XSecure_HssInit, XSecure_HssSignatureVerification, XSecure_LmsSignatureVerification.