xsecure.c
XSecure_Aes SecureAes
XSecure_Rsa Secure_Rsa
XSecure_Sha3 Sha3Instance
XCsuDma CsuDma
u32 XsecureIv[XSECURE_IV_LEN][XSECURE_IV_LEN]
static u32 XSecure_BhdrValidation(XSecure_ImageInfo *ImageInfo)
This function validates boot header.
ImageInfo Pointer to XSecure_ImageInfo structure. Returns Status XST_SUCCESS on successful verification.Error code on failure.
static u32 XSecure_DecryptPartition(XSecure_ImageInfo *ImageHdrInfo, u8 *SrcAddr, u8 *KupKey, XSecure_DataAddr *Addr)
This function decrypts the image partition.
ImageHdrInfo Pointer to XSecure_ImageInfo structure SrcAddr Pointer to single partition non-bitstream image KupKey Pointer to User Key Addr Location of the secure image loaded after validation Returns Status XST_SUCCESS on successful verification.Error code on failure.
static u32 XSecure_DataAuthentication(XSecure_AuthParam *AuthParam)
This function performs authentication of a given data.
AuthParam Pointer to auhentication parameter structure. Returns Status XST_SUCCESS on successXST_FAILURE on failure
u32 XSecure_CsuDmaInit(void)
This function is used to initialize the DMA driver.
returns the error code on any error returns XST_SUCCESS on success
References XSECURE_CSUDMA_DEVICEID, XSECURE_ERROR_CSUDMA_INIT_FAIL.
Referenced by Xsecure_GetCsuDma, XSecure_SecureImage, XSecure_Sha3Hash.
XCsuDma * Xsecure_GetCsuDma(void)
This function is used to initialize CsuDma and return CsuDma pointer.
returns reference to a XCsuDma driver instance
References XSecure_CsuDmaInit.
u32 XSecure_Sha3Hash(u32 SrcAddrHigh, u32 SrcAddrLow, u32 SrcSize, u32 Flags)
This function access the xilsecure SHA3 hardware based on the flags provided to calculate the SHA3 hash.
SrcAddrHigh Higher 32-bit of the input or output address. SrcAddrLow Lower 32-bit of the input or output address. SrcSize Size of the data on which hash should be calculated. Flags : inputs for the operation requested BIT(0) - for initializing csudma driver and SHA3, (Here address and size inputs can be NULL) BIT(1) - To call Sha3_Update API which can be called multiple times when data is not contiguous. BIT(2) - to get final hash of the whole updated data. Hash will be overwritten at provided address with 48 bytes. Returns Status XST_SUCCESS on success and error code on failure.
References XSecure_CsuDmaInit, XSECURE_ERROR_CSUDMA_INIT_FAIL, XSECURE_INVALID_FLAG, XSECURE_SHA3_FINAL, XSECURE_SHA3_INIT, XSECURE_SHA3_INIT_FAIL, XSECURE_SHA3_MASK, XSECURE_SHA3_UPDATE_FAIL, XSecure_Sha3Finish, XSECURE_SHA3HASH_UPDATE, XSecure_Sha3Initialize, XSecure_Sha3Start, XSecure_Sha3Update.
Referenced by XSecure_ShaDigest, XSecure_ShaFinish.
u32 XSecure_RsaCore(u32 SrcAddrHigh, u32 SrcAddrLow, u32 SrcSize, u32 Flags)
This is the function to RSA decrypt or encrypt the provided data and load back to memory.
SrcAddrHigh Higher 32-bit Linear memory space from where CSUDMA will read the data SrcAddrLow Lower 32-bit Linear memory space from where CSUDMA will read the data SrcSize Number of bytes to be encrypted or decrypted. Flags Flags for operation, where BIT(0) indicates Encryption/Decryption (0 for RSA Private key Decryption or 1 for RSA Public key Encryption) Returns Status XST_SUCCESS on success and error code on failure. Data to be encrypted/Decrypted + Modulus + Exponent Modulus and Data should always be key size Exponent : private key's exponent is key size while decrypting the signature and 32 bit for public key for encrypting the signature In this API we are not taking exponentiation value.
References XSECURE_DEC, XSECURE_RSA_CORE_OPERATION, XSecure_RsaInitialize, XSecure_RsaPrivateDecrypt, XSecure_RsaPublicEncrypt.
static u32 XSecure_InitAes(u32 AddrHigh, u32 AddrLow)
This function initializes the AES-GCM engine with Key and Iv.
AddrHigh Higher 32 bit address of the XSecure_AesParams structure. AddrLow Lower 32 bit address of the XSecure_AesParams structure. Returns Status XST_SUCCESS on successError code on failure
static u32 XSecure_DecryptData(u32 AddrHigh, u32 AddrLow)
This function performs the AES decryption of the data-blob.
AddrHigh Higher 32 bit address of the XSecure_AesParams structure. AddrLow Lower 32 bit address of the XSecure_AesParams structure. Returns Status XST_SUCCESS on successError code on failure
static u32 XSecure_EncryptData(u32 AddrHigh, u32 AddrLow)
This function performs the AES encryption of the data-blob.
AddrHigh Higher 32 bit address of the XSecure_AesParams structure. AddrLow Lower 32 bit address of the XSecure_AesParams structure. Returns Status XST_SUCCESS on successError code on failure
u32 XSecure_AesOperation(u32 AddrHigh, u32 AddrLow)
This function checks for flags field of the XSecure_AesParams struct and resolves weather the request is encryption or decryption.
AddrHigh Higher 32 bit address of the XSecure_AesParams structure. AddrLow Lower 32 bit address of the XSecure_AesParams structure. Returns Status XST_SUCCESS on successError code on failure
References XSECURE_AES_KUP_KEY, XSECURE_DEC, XSECURE_DEC_WRONG_KEY_SOURCE, XSECURE_ENC, XSECURE_INVALID_FLAG, XSECURE_SIZE_ERR, XSECURE_WORD_LEN.
u32 XSecure_DataAuth(u8 *Signature, XSecure_RsaKey *KeyInst, u8 *Hash)
This function performs authentication of data by encrypting the signature with provided key and compares with hash of the data and returns success or failure.
Signature Pointer to the RSA signature of the data KeyInst Pointer to XSecure_RsaKey structure. Hash Pointer to the hash of the data to be authenticated. Returns Status XST_SUCCESS on successError code on failure
References XSecure_RsaKey::Exponent, XSecure_RsaKey::Exponentiation, XSecure_RsaKey::Modulus, XSECURE_AUTH_FAILURE, XSECURE_HASH_TYPE_SHA3, XSECURE_MOD_LEN, XSECURE_RSA_ENCRYPT_ERR, XSECURE_RSA_INIT_ERR, XSecure_RsaInitialize, XSecure_RsaPublicEncrypt, XSecure_RsaSignVerification, XSECURE_VERIFY_ERR.
u32 XSecure_PartitionAuthentication(XCsuDma *CsuDmaInstPtr, u8 *Data, u32 Size, u8 *AuthCertPtr)
This function performs authentication of a partition of an image.
CsuDmaInstPtr Pointer to the CSU DMA instance. Data Pointer to partition to be authenticated. Size Represents the size of the partition. AuthCertPtr Pointer to authentication certificate of the partition. Returns Status XST_SUCCESS on successError code on failure
References XSECURE_AUTH_CERT_PARTSIG_OFFSET, XSECURE_AUTH_FAILURE.
Referenced by XSecure_AuthenticationHeaders, XSecure_SecureImage.
static u32 XSecure_BhdrAuthentication(XCsuDma *CsuDmaInstPtr, u8 *Data, u32 Size, u8 *AuthCertPtr)
This function performs authentication of a boot header of the image.
CsuDmaInstPtr Pointer to the CSU DMA instance. Data pointer to boot header of the image. Size Size of the boot header. AuthCertPtr Pointer to authentication certificate. Returns Status XST_SUCCESS on successXST_FAILURE on failure
u32 XSecure_MemCopy(void *DestPtr, void *SrcPtr, u32 Size)
This function copies the data from specified source to destination using CSU DMA.
DestPtr Pointer to the destination address. SrcPtr Pointer to the source address. Size Data size to be copied. Returns Status XST_SUCCESS on successXST_FAILURE on failure
References XSecure_SssDmaLoopBack, XSecure_SssInitialize.
Referenced by XSecure_AuthenticationHeaders, XSecure_SecureImage.
u32 XSecure_VerifySpk(u8 *AcPtr, u32 EfuseRsaenable)
This function verifies SPK by authenticating SPK with PPK, also checks either SPK is revoked or not.if it is not boot header authentication.
AcPtr Pointer to the authentication certificate. EfuseRsaenable Input variable which holds efuse RSA authentication or boot header authentication (0 for Boot header authentication or 1 for RSA authentication) Returns Status XST_SUCCESS on successError code on failure
References XSecure_IsRsaEnabled, XSecure_SpkAuthentication, XSecure_SpkRevokeCheck.
Referenced by XSecure_SecureImage.
u32 XSecure_AuthenticationHeaders(u8 *StartAddr, XSecure_ImageInfo *ImageInfo)
This function authenticates the single partition image's boot header and image header, also copies all the required details to the ImageInfo pointer.
StartAddr Pointer to the single partition image. ImageInfo Pointer to XSecure_ImageInfo structure. Returns Status XST_SUCCESS on successError code on failure XSECURE_AUTH_NOT_ENABLED - represents image is not authenticated. Copies the header and authentication certificate to internal buffer.
References XSecure_PartitionHeader::NextPartitionOffset, XSECURE_AC_IMAGE_HDR_OFFSET, XSECURE_ARRAY_LENGTH, XSECURE_AUTH_CERT_MIN_SIZE, XSECURE_AUTH_ISCOMPULSORY, XSECURE_AUTH_NOT_ENABLED, XSECURE_BOOT_HDR_MAX_SIZE, XSECURE_BUFFER_SIZE, XSECURE_DEC_WRONG_KEY_SOURCE, XSECURE_ENC_ISCOMPULSORY, XSECURE_IMAGE_HDR_OFFSET, XSECURE_IMAGE_HEADER_SIZE_ERR, XSECURE_IMAGE_SYNC_WORD_OFFSET, XSECURE_IMAGE_WITH_MUL_PARTITIONS, XSECURE_IMG_HDR_FAIL, XSECURE_INVALID_IMAGE_ERROR, XSecure_IsEncOnlyEnabled, XSecure_IsRsaEnabled, XSECURE_IV_LEN, XSECURE_IV_OFFSET, XSECURE_KEY_SOURCE_OFFSET, XSECURE_KEY_SRC_BBRAM, XSECURE_KEY_SRC_BLACK_BH, XSECURE_KEY_SRC_GREY_BH, XSecure_MemCopy, XSecure_PartitionAuthentication, XSECURE_PH_ATTR_ENC_ENABLE, XSECURE_PH_IV_MASK, XSECURE_PH_OFFSET, XSECURE_PH_TABLE_OFFSET, XSECURE_WORD_LEN.
Referenced by XSecure_SecureImage.
u32 XSecure_SecureImage(u32 AddrHigh, u32 AddrLow, u32 KupAddrHigh, u32 KupAddrLow, XSecure_DataAddr *Addr)
This function process the secure image of single partition created by bootgen.
AddrHigh Higher 32-bit linear memory space of single partition non-bitstream image. AddrLow Lower 32-bit linear memory space of single partition non-bitstream image. KupAddrHigh Higher 32-bit linear memory space of KUP key. KupAddrLow lower 32-bit linear memory space of KUP key. Addr Location of the secure image loaded after validation. Returns Status XST_SUCCESS on successError code on failure
References XSECURE_AUTH_CERT_MIN_SIZE, XSECURE_AUTH_NOT_ENABLED, XSecure_AuthenticationHeaders, XSECURE_BUFFER_SIZE, XSecure_CsuDmaInit, XSECURE_DEC_WRONG_KEY_SOURCE, XSECURE_ENC_ISCOMPULSORY, XSECURE_ERROR_CSUDMA_INIT_FAIL, XSECURE_HDR_NOAUTH_PART_AUTH, XSecure_IsEncOnlyEnabled, XSECURE_ISNOT_SECURE_IMAGE, XSECURE_IV_LEN, XSECURE_IV_OFFSET, XSECURE_KEY_SOURCE_OFFSET, XSECURE_KEY_SRC_BBRAM, XSECURE_KEY_SRC_BLACK_BH, XSECURE_KEY_SRC_GREY_BH, XSECURE_KEY_SRC_KUP, XSecure_MemCopy, XSECURE_PARTITION_FAIL, XSecure_PartitionAuthentication, XSECURE_PH_ATTR_AUTH_ENABLE, XSECURE_PH_ATTR_ENC_ENABLE, XSECURE_PH_IV_MASK, XSECURE_PH_TABLE_OFFSET, XSECURE_PPK_SIZE, XSecure_VerifySpk, XSECURE_WORD_LEN, XSECURE_WORD_SHIFT.
u32 XSecure_IsRsaEnabled(void)
This function tells whether RSA authentication is enabled or not.
Returns Status XSECURE_ENABLED if RSA bit of efuse is programmedXSECURE_NOTENABLED if RSA bit of efuse is not programmed.
References XSECURE_EFUSE_SEC_CTRL, XSECURE_ENABLED, XSECURE_NOTENABLED.
Referenced by XSecure_AuthenticationHeaders, XSecure_VerifySpk.
u32 XSecure_IsEncOnlyEnabled(void)
This function tells whether encrypt only is enabled or not.
Returns Status XSECURE_ENABLED if enc_only bit of efuse is programmedXSECURE_NOTENABLED if enc_only bit of efuse is not programmed
References XSECURE_EFUSE_SEC_CTRL, XSECURE_ENABLED, XSECURE_NOTENABLED.
Referenced by XSecure_AuthenticationHeaders, XSecure_SecureImage.
u32 XSecure_PpkVerify(XCsuDma *CsuDmaInstPtr, u8 *AuthCert)
This function verifies the PPK hash with PPK programmed on efuse.
CsuDmaInstPtr Pointer to CSU DMA instance. AuthCert Pointer to authentication certificate. Returns Status XST_SUCCESS on successful verification.Error code on failure.
References XSECURE_AC_PPK_OFFSET, XSECURE_AH_ATTR_PPK_SEL_MASK, XSECURE_AH_ATTR_PPK_SEL_SHIFT, XSECURE_EFUSE_PPK0, XSECURE_EFUSE_PPK1, XSECURE_EFUSE_SEC_CTRL, XSECURE_HASH_TYPE_SHA3, XSECURE_KEY_SIZE, XSECURE_PPK_ERR, XSECURE_REVOKE_ERR, XSECURE_SEL_ERR, XSECURE_SHA3_INIT_FAIL, XSECURE_SHA3_PADSELECT_ERR, XSecure_Sha3Digest, XSecure_Sha3Initialize, XSecure_Sha3PadSelection, XSECURE_VERIFY_ERR, XSECURE_WORD_LEN.
u32 XSecure_SpkAuthentication(XCsuDma *CsuDmaInstPtr, u8 *AuthCert, u8 *Ppk)
This function authenticates SPK with provided PPK or PPK from authentication certificate.
CsuDmaInstPtr Pointer to CSU DMA instance. AuthCert Pointer to authentication certificate. Ppk Pointer to the PPK key, or NULL to use PPK from provided * authentication certificate. Returns Status XST_SUCCESS on successful verification.Error code on failure.
References XSECURE_AH_ATTR_SPK_ID_FUSE_SEL_MASK, XSECURE_AH_ATTR_SPKID_FUSESEL_SHIFT, XSECURE_AUTH_HEADER_SIZE, XSECURE_HASH_TYPE_SHA3, XSECURE_INVALID_EFUSE_SELECT, XSECURE_PPK_MOD_EXT_SIZE, XSECURE_PPK_MOD_SIZE, XSECURE_PPK_SIZE, XSECURE_RSA_AC_ALIGN, XSECURE_RSA_ENCRYPT_ERR, XSECURE_RSA_INIT_ERR, XSecure_RsaInitialize, XSecure_RsaPublicEncrypt, XSecure_RsaSignVerification, XSECURE_SHA3_INIT_FAIL, XSecure_Sha3Finish, XSecure_Sha3Initialize, XSecure_Sha3PadSelection, XSecure_Sha3Start, XSecure_Sha3Update, XSECURE_SPK_ERR, XSECURE_SPK_SIG_SIZE, XSECURE_SPK_SIZE, XSECURE_SPKID_EFUSE, XSECURE_USER_EFUSE, XSECURE_VERIFY_ERR.
Referenced by XSecure_VerifySpk.
u32 XSecure_SpkRevokeCheck(u8 *AuthCert)
This function checks whether SPK is been revoked or not.
AuthCert Pointer to authentication certificate. Returns Status XST_SUCCESS on successful verification.Error code on failure.
References XSECURE_AC_SPKID_OFFSET, XSECURE_AH_ATTR_SPK_ID_FUSE_SEL_MASK, XSECURE_AH_ATTR_SPKID_FUSESEL_SHIFT, XSECURE_EFUSE_SPKID, XSECURE_INVALID_EFUSE_SELECT, XSECURE_OUT_OF_RANGE_USER_EFUSE_ERROR, XSECURE_REVOKE_ERR, XSECURE_SPK_ERR, XSECURE_SPKID_EFUSE, XSECURE_USER_EFUSE, XSECURE_USER_EFUSE_MAX_VALUE, XSECURE_USER_EFUSE_MIN_VALUE, XSECURE_USER_EFUSE_START_ADDR, XSECURE_WORD_LEN, XSECURE_WORD_SHIFT.
Referenced by XSecure_VerifySpk.