xsecure_katclient.c
int XSecure_AesDecryptKat(XSecure_ClientInstance *InstancePtr)
This function sends IPI request to PLM to perform decrypt KAT on AES engine.
InstancePtr Pointer to the client instance XST_SUCCESS When KAT PassXST_FAILURE On failure
References XSECURE_API_AES_DECRYPT_KAT, XSECURE_API_KAT, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
int XSecure_AesDecryptCmKat(XSecure_ClientInstance *InstancePtr)
This function sends IPI request to PLM to perform KAT on AES DPA countermeasure KAT.
InstancePtr Pointer to the client instance XST_SUCCESS On successXST_INVALID_PARAM If input parameters are invalidXST_FAILURE On failure
References XSECURE_API_AES_DECRYPT_CM_KAT, XSECURE_API_KAT, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
int XSecure_RsaPublicEncKat(XSecure_ClientInstance *InstancePtr)
This function sends IPI request to PLM to perform RSA encrypt KAT.
InstancePtr Pointer to the client instance XST_SUCCESS On successXST_INVALID_PARAM If input parameters are invalidXST_FAILURE On failure
References XSECURE_API_KAT, XSECURE_API_RSA_PUB_ENC_KAT, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
Referenced by main.
int XSecure_Sha3Kat(XSecure_ClientInstance *InstancePtr)
This function sends IPI request to PLM to perform SHA3 KAT.
InstancePtr Pointer to the client instance XST_SUCCESS When KAT PassXST_INVALID_PARAM If input parameters are invalidXST_FAILURE On failure
References XSECURE_API_KAT, XSECURE_API_SHA3_KAT, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
int XSecure_EllipticSignVerifyKat(XSecure_ClientInstance *InstancePtr, XSecure_EccCrvClass CurveClass)
This function sends IPI request to PLM to perform ECC sign verify KAT.
InstancePtr Pointer to the client instance CurveClass Type of elliptic curve class(Prime - 0, Binary - 1) XST_SUCCESS On successXST_INVALID_PARAM If input parameters are invalidXST_FAILURE On failure
References XSECURE_API_ELLIPTIC_SIGN_VERIFY_KAT, XSECURE_API_KAT, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
Referenced by main, XSecure_KatIpiHandler.
int XSecure_AesEncryptKat(XSecure_ClientInstance *InstancePtr)
This function sends IPI request to PLM to perform encrypt KAT.
InstancePtr Pointer to the client instance XST_SUCCESS When KAT PassXST_INVALID_PARAM If input parameters are invalidXST_FAILURE On failure
References XSECURE_API_AES_ENCRYPT_KAT, XSECURE_API_KAT, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
int XSecure_RsaPrivateDecKat(XSecure_ClientInstance *InstancePtr)
This function sends IPI request to PLM to perform RSA private decrypt KAT.
InstancePtr Pointer to the client instance XST_SUCCESS On successXST_INVALID_PARAM If input parameters are invalidXST_FAILURE On failure
References XSECURE_API_KAT, XSECURE_API_RSA_PRIVATE_DEC_KAT, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
Referenced by XSecure_KatIpiHandler.
int XSecure_EllipticSignGenKat(XSecure_ClientInstance *InstancePtr, XSecure_EccCrvClass CurveClass)
This function sends IPI request to PLM to perform ECC sign generate KAT.
InstancePtr Pointer to the client instance CurveClass Type of elliptic curve class(Prime - 0, Binary - 1) XST_SUCCESS On successXST_INVALID_PARAM If input parameters are invalidXST_FAILURE On failure
References XSECURE_API_ELLIPTIC_SIGN_GEN_KAT, XSECURE_API_KAT, XSecure_SendRequest, XSECURE_SLR_INDEX_SHIFT.
Referenced by main, XSecure_KatIpiHandler.