xsecure_plat_rsa.h
externC
For compilation in C++.
XSECURE_RSA_KEY_GEN_SIZE_IN_BYTES
RSA default key size in bytes.
Referenced by main, XSecure_KeyUnwrap, XSecure_RsaOaepDecrypt, XSecure_RsaOaepEncrypt, XSecure_RsaPwct.
XSECURE_RSA_KEY_GEN_SIZE_IN_WORDS
RSA key generation size in words.
XSECURE_RSA_MAX_KEY_GEN_SUPPORT
Maximum keys that needs to be generated.
Referenced by XSecure_GetRsaPrivateKey, XSecure_GetRsaPublicKey, XSecure_RsaDestroyKeyInUse.
XSECURE_RSA_KEY_STATUS_WAIT
RSA key status wait.
XSECURE_RSA_2048_QUANT_SIZE
RSA maximum quant size for 2048 bit key.
XSECURE_RSA_3072_QUANT_SIZE
RSA maximum quant size for 3072 bit key.
XSECURE_RSA_4096_QUANT_SIZE
RSA maximum quant size for 4096 bit key.
XSECURE_RSA_PUBLIC_EXPONENT
RSA public exponent value.
XSECURE_RSA_PUB_EXP_SIZE
RSA public exponent size.
Referenced by XSecure_RsaPwct.
XSECURE_KEY_PAIR_GEN_POLL_INTERVAL
Key pair generation poll interval.
Referenced by XSecure_AddRsaKeyPairGenerationToScheduler.
XSECURE_ECDSA_RSA_SOFT_RESET
ECDSA/RSA soft reset address.
Referenced by XSecure_RsaExp, XSecure_RsaExpCRT, XSecure_RsaExpopt.
XSECURE_RSA_SIZE_IN_BYTES
512 bytes for 4096 bit data
XSECURE_PRIME_FACTOR_P_SIZE
size of first prime factor(P)
XSECURE_PRIME_FACTOR_Q_SIZE
size of first prime factor(Q)
XSECURE_PRIME_FACTOR_MAX_P_SIZE
256 bytes size of first prime factor(P)
XSECURE_PRIME_FACTOR_MAX_Q_SIZE
256 bytes size of first prime factor(Q)
XSecure_RsaKeyOpState
Default state.
XSecure_RsaKeyStatus
RSA key is free.
typedef RsaKeyPair XSecure_RsaKeyPtr
int XSecure_RsaOaepEncrypt(XSecure_Rsa *InstancePtr, XSecure_RsaOaepParam *OaepParam)
This function encodes the given message using RSA OAEP and encrypts it.
InstancePtr is a pointer to the XSecure_Rsa instance. OaepParam is a pointer to the XSecure_RsaOaepParam instance. XST_SUCCESS - On success.XSECURE_RSA_OAEP_INVALID_PARAM - On invalid parameter.XST_FAILURE - On failure.
References XSecure_RsaOaepParam::OutputDataAddr, XSECURE_RSA_KEY_GEN_SIZE_IN_BYTES, XSECURE_RSA_OAEP_INVALID_PARAM, XSecure_RsaPublicEncrypt_64Bit.
Referenced by XSecure_RsaPwct.
int XSecure_RsaOaepDecrypt(XSecure_RsaPrivKey *PrivKey, XSecure_RsaOaepParam *OaepParam)
This function decodes the given message and decrypts it using RSA OAEP.
PrivKey is a pointer to the XSecure_RsaPrivKey instance. OaepParam is a pointer to the XSecure_RsaOaepParam instance. XST_SUCCESS - On success.XSECURE_RSA_OAEP_INVALID_PARAM - On invalid parameter.XST_FAILURE - On failure.
References XSecure_RsaPrivKey::DP, XSecure_RsaPrivKey::DQ, XSecure_RsaOaepParam::InputDataAddr, XSecure_RsaPrivKey::Mod, XSecure_RsaPrivKey::P, XSecure_RsaPrivKey::Q, XSecure_RsaPrivKey::QInv, XSECURE_BYTE_IN_BITS, XSECURE_RSA_KEY_GEN_SIZE_IN_BYTES, XSECURE_RSA_OAEP_INVALID_PARAM, XSecure_RsaExpCRT.
Referenced by XSecure_KeyUnwrap, XSecure_RsaPwct.
XSecure_RsaPrivKey * XSecure_GetRsaPrivateKey(u32 RsaIdx)
This function returns RSA private key.
RsaIdx Index of the RSA key to retrieve. Pointer to XSecure_RsaPrivKey or NULL otherwise.
References XSECURE_RSA_MAX_KEY_GEN_SUPPORT.
Referenced by XSecure_KeyUnwrap.
XSecure_RsaPubKey * XSecure_GetRsaPublicKey(u32 RsaIdx)
This function returns RSA public key.
API to retrieve RSA KEY in use index. Pointer to XSecure_RsaPubKey or NULL otherwise.
References XSECURE_RSA_MAX_KEY_GEN_SUPPORT.
u32 XSecure_GetRsaKeyInUseIdx(void)
This function returns RSA key inuse index.
API to destroy key pair that is in use. KeyInUse To indicate the key that is in use
References XSecure_RsaKeyMgmt::KeyInUse, XSECURE_RSA_KEY_AVAIL.
Referenced by XSecure_KeyUnwrap.
int XSecure_RsaDestroyKeyInUse(void)
This function destroys the RSA key in use.
API to add key pair generation to scheduler. XST_SUCCESS - On success.XST_FAILURE - On failure.
References XSecure_RsaKeyGenParam::IsRsaKeyAvail, XSecure_RsaKeyMgmt::Key, XSecure_RsaKeyMgmt::KeyInUse, XSecure_RsaKeyGenParam::KeyPair, XSecure_RsaKeyPair::PrivKey, XSecure_RsaKeyPair::PubKey, XSecure_AddRsaKeyPairGenerationToScheduler, XSECURE_RSA_KEY_AVAIL, XSECURE_RSA_MAX_KEY_GEN_SUPPORT, XSECURE_RTCA_RSA_KEY_STATUS_MASK, XSECURE_RTCA_RSA_KEY_STATUS_REG, XSECURE_ZERO.
int XSecure_AddRsaKeyPairGenerationToScheduler(void)
This function adds periodic task of generation RSA key pair to scheduler.
XST_SUCCESS - On success.XSECURE_ERR_ADD_TASK_SCHEDULER - If failed to add task to scheduler.
References XSECURE_DEBUG_GENERAL, XSECURE_KEY_PAIR_GEN_POLL_INTERVAL, XSecure_Printf.
Referenced by XSecure_Init, XSecure_RsaDestroyKeyInUse.