xsecure_lms_ots.c
XSECURE_BYTE_QUO
To Pick the byte in array.
XSECURE_BYTE_REM
Inside the byte interested value has to be right shifted.
XSECURE_BIT_MASK
Mask out rest of bits, only take w width back to caller invocations to get signature is equal to number of w width digits in a digest to get that, (2^w - 1), example w=8, Mask = 256.
XSECURE_BITS_PER_BYTE
Bits per byte.
XSECURE_LOWER_16_BIT_MASK
Lower 16 bit mask.
u32 XSecure_LmsOtsCoeff(u8 const *const Arr, const u32 ArrayIndex, const u32 w)
This function extracts the digits from the array for bytes.
S (represented in bits) = 0x1234 [0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0] ^ | coef(S, 7, 1) [1, 2, 3, 4] ^ | coef(S, 0, 4)If i is larger than the number of w-bit values in S, then coef(S, i, w) is undefined, this can't be checked here Arr Byte array from where the digit needs to be picked ArrayIndex When array is divided into array of digits, i represents the index of digit w Width in bits, for each digit allowed values digit value.
int XSecure_LmsOtsComputeChecksum(const u8 *const Array, const u32 ArrayLen, const u32 w, const u32 ls, u32 *const Checksum)
This function calculates the checksum for a given array.
Array Byte array ffor which checksum needs to be calculated ArrayLen Length of input array w Width in bits, for each digit allowed values ls Number of bits to left-shift the calculated checksum Checksum Pointer to address, where computed checksum needs to be copied XST_SUCCESS - On successXSECURE_LMS_OTS_CHECKSUM_BUFF_INVALID_LEN_ERROR - Invalid buffer length (zero length)
References XSECURE_LMS_OTS_CHECKSUM_BUFF_INVALID_LEN_ERROR.
int XSecure_LmsOtsLookupParamSet(XSecure_LmsOtsType Type, XSecure_LmsOtsParam **Parameters)
This function returns the parameters for the type of LMS OTS type.
Type XSecure_LmsOtsType, type of OTS algorithm selected Parameters Pointer to array location where all predefined parameter values are present XSecure_LmsOtsParam XST_SUCCESS - On successXSECURE_LMS_OTS_TYPE_UNSUPPORTED_ERROR - LMS OTS type is not supportedXSECURE_LMS_OTS_TYPE_LOOKUP_GLITCH_ERROR - Glitch detected during type lookup
References XSecure_LmsOtsParam::H, XSECURE_LMS_OTS_LS_NOT_SUPPORTED, XSECURE_LMS_OTS_P_NOT_SUPPORTED, XSECURE_LMS_OTS_U_NOT_SUPPORTED, XSECURE_LMS_OTS_V_NOT_SUPPORTED, XSECURE_LMS_OTS_W_NOT_SUPPORTED.
Referenced by XSecure_HssFinish, XSecure_HssInit, XSecure_LmsSignatureVerification.