xsecure_slhdsa_hash.c
int XSecure_SlhdsaShake256sHashMsg(void)
This function computes the hash of the message as required by the SLH_DSA algorithm.
Gets signature and public key addresses from the instance structure for IPC compatibility. XST_SUCCESS if the operation was successful.Error code otherwise.
References XSecure_SlhdsaInstance::Data1, XSecure_SlhdsaInstance::Data1Len, XSecure_SlhdsaInstance::Data2, XSecure_SlhdsaInstance::DataAddr, XSecure_SlhdsaInstance::DataLen, XSecure_SlhdsaParam::m, XSecure_SlhdsaParam::n, XSecure_SlhdsaInstance::Param, XSecure_SlhdsaInstance::PublicKeyAddr, XSecure_SlhdsaInstance::ShaInstance, XSecure_SlhdsaInstance::SignatureAddr, XSecure_ExtendedShaFinish, XSECURE_SHAKE_256, XSecure_ShaLastUpdate, XSecure_ShaStart, XSecure_ShaUpdate, XSecure_SlhdsaGetInstance, XSECURE_VALUE_TWO, XSECURE_ZERO.
int XSecure_SlhdsaShake256sHashF(const u64 PublicKeyAddr, const u64 InputAddr, u8 *const Output)
This function generates a hash value based on the provided public key and input data, and stores the result in the output buffer.
It takes an n-byte message as input and produces an n-byte output. PublicKeyAddr 64-bit address of the public key buffer. InputAddr 64-bit address of the input data buffer to be hashed. Output Pointer to the buffer where the computed hash will be stored. XST_SUCCESS if the operation was successful.Error code otherwise.
References XSecure_SlhdsaInstance::Addr, XSecure_SlhdsaParam::n, XSecure_SlhdsaInstance::Param, XSecure_SlhdsaInstance::ShaInstance, XSecure_ShaFinish, XSECURE_SHAKE_256, XSecure_ShaLastUpdate, XSecure_ShaStart, XSecure_ShaUpdate, XSecure_SlhdsaGetInstance.
Referenced by XSecure_SlhdsaForsPkFromSig.
int XSecure_SlhdsaShake256sChain(const u64 InputAddr, const XSecure_SlhdsaChainConfig *const ChainConfig, const u64 PublicKeyAddr, u8 *const Output)
This function performs chained SLH_DSA hash operations on the input data, starting from the specified index and performing the given number of steps.
InputAddr 64-bit address of the input data buffer. ChainConfig Pointer to structure containing chain configuration: StartIdx: Index in the input buffer from where the chain operation should startSteps: Number of hash chain steps to perform PublicKeyAddr 64-bit address of the public key used for verification. Output Pointer to the buffer where the resulting hash will be stored. XST_SUCCESS if the operation was successful.Error code otherwise.
References XSecure_SlhdsaInstance::Addr, XSecure_SlhdsaParam::n, XSecure_SlhdsaInstance::Param, XSecure_SlhdsaInstance::ShaInstance, XSecure_SlhdsaChainConfig::StartIdx, XSecure_SlhdsaChainConfig::Steps, XSecure_MemCpy64, XSecure_ShaFinish, XSecure_ShaLastUpdate, XSecure_ShaStart, XSecure_ShaUpdate, XSecure_SlhdsaGetInstance, XSECURE_ZERO.
Referenced by XSecure_SlhdsaWotsPkFromSign.
int XSecure_SlhdsaShake256sHashTl(const u64 PublicKeyAddr, const u8 *const Input, u32 InputLen, u8 *const Output)
This function generates a hash value for the provided input data.
The hash is computed with respect to the given public key and the result is stored in the output buffer. PublicKeyAddr 64-bit address of the public key used for hashing. Input Pointer to the input data to be hashed. InputLen Length of the input data in bytes. Output Pointer to the buffer where the computed hash will be stored. XST_SUCCESS if the hash was computed successfully.Error code otherwise.
References XSecure_SlhdsaInstance::Addr, XSecure_SlhdsaParam::n, XSecure_SlhdsaInstance::Param, XSecure_SlhdsaInstance::ShaInstance, XSecure_ShaFinish, XSECURE_SHAKE_256, XSecure_ShaLastUpdate, XSecure_ShaStart, XSecure_ShaUpdate, XSecure_SlhdsaGetInstance.
Referenced by XSecure_SlhdsaForsPkFromSig, XSecure_SlhdsaWotsPkFromSign.
int XSecure_SlhdsaShake256sHashH(const u64 PublicKeyAddr, const u64 Data1Addr, const u64 Data2Addr, u8 *const Output)
This function generates a hash value for the provided input data.
The hash is computed with respect to the given public key and the result is stored in the output buffer. PublicKeyAddr 64-bit address of the public key used for hashing. Data1Addr 64-bit address of the first input data to be hashed. Data2Addr 64-bit address of the second input data to be hashed. Output Pointer to the buffer where the hash output will be stored. XST_SUCCESS if the hash was computed successfully.Error code otherwise.
References XSecure_SlhdsaInstance::Addr, XSecure_SlhdsaParam::n, XSecure_SlhdsaInstance::Param, XSecure_SlhdsaInstance::ShaInstance, XSecure_ShaFinish, XSECURE_SHAKE_256, XSecure_ShaLastUpdate, XSecure_ShaStart, XSecure_ShaUpdate, XSecure_SlhdsaGetInstance.
Referenced by XSecure_SlhdsaForsPkFromSig, XSecure_SlhdsaXmssPkFromSign.