xsecure_resourcehandling.c
XSECURE_DATACONTEXTLOST_SET
Set value of data context lost.
Referenced by XSecure_IpiEventHandling, XSecure_SetDataContextLost.
XSECURE_DATACONTEXTLOST_CLR
Clear value of data context lost.
Referenced by XSecure_IpiEventHandling.
u32 XSecure_ResIpiMask[XPLMI_MAX_CORE][XPLMI_MAX_CORE]
u32 XSecure_DataContextLost[XPLMI_MAX_CORE][XPLMI_MAX_CORE]
int XSecure_MakeResFree(XPlmi_CoreType Core)
The function frees AES/SHA resource.
Core is the resource which is to be freed Always returns XST_SUCCESS
References XSECURE_IPI_MASK_DEF_VAL.
Referenced by XSecure_AesIpiHandler, XSecure_HmacIpiHandler, XSecure_KatIpiHandler, XSecure_KatPlatIpiHandler, XSecure_PlatAesIpiHandler, XSecure_Sha3IpiHandler, XSecure_ShaIpiHandler, XSecure_SlhdsaIpiHandler.
int XSecure_IpiEventHandling(XPlmi_Cmd *Cmd, XPlmi_CoreType Core)
The function handles the SHA/AES IPI events.
Cmd is the pointer to received IPI command Core is the resource whose IPI events are to be handled XST_SUCCESS - On successXST_INVALID_PARAM - If Cmd is NULL or Core is invalidXST_DEVICE_BUSY - If device is busy with different IPI maskXST_DATA_LOST - If data context was lost
References XSECURE_DATACONTEXTLOST_CLR, XSECURE_DATACONTEXTLOST_SET, XSECURE_IPI_MASK_DEF_VAL.
Referenced by XSecure_AesIpiHandler, XSecure_HmacIpiHandler, XSecure_KatIpiHandler, XSecure_KatPlatIpiHandler, XSecure_PlatAesIpiHandler, XSecure_Sha3IpiHandler, XSecure_ShaIpiHandler, XSecure_SlhdsaIpiHandler.
int XSecure_SetDataContextLost(XPlmi_CoreType Core)
This function sets the status of data context of previous AES/SHA operation.
Core is the SHA/AES source whose data context status has to be set XST_SUCCESS - On successXST_INVALID_PARAM - If Core is invalid
References XSECURE_DATACONTEXTLOST_SET, XSecure_GetAesInstance, XSecure_GetSha3Instance, XSECURE_IPI_MASK_DEF_VAL, XSecure_SetReset, XSECURE_SHA3_RESET_OFFSET, XSECURE_SHA_0_DEVICE_ID, XSECURE_SHA_INITIALIZED.