xsecure_slhdsa_instance.h
XSECURE_SLHDSA_N_LEN
Output length in bytes for SLH-DSA-SHAKE-256s.
XSECURE_SLHDSA_SHAKE_256S_SIGN_LEN
Total signature length in bytes for SLH-DSA-SHAKE-256s.
Referenced by XSecure_SlhdsaGetInstance.
XSECURE_SLHDSA_MAX_DATA1_LEN_IN_BYTES
Maximum length of Data1 buffer in bytes (for WOTS+ chain values)
Referenced by XSecure_SlhdsaGetInstance.
XSECURE_SLHDSA_MAX_DATA2_LEN_IN_BYTES
Maximum length of Data2 buffer in bytes (for hash outputs and base conversions)
Referenced by XSecure_SlhdsaGetInstance.
XSECURE_SLHDSA_MAX_DATA3_LEN_IN_BYTES
Maximum length of Data3 buffer in bytes (for single hash outputs)
Referenced by XSecure_SlhdsaGetInstance.
XSECURE_SLHDSA_MAX_DATA4_LEN_IN_WORDS
Maximum length of Data4 buffer in words (for storing digits)
Referenced by XSecure_SlhdsaGetInstance.
XSECURE_SLHDSA_NO_OF_INV_SIGN
Number of invalid signature invocations allowed.
Referenced by XSecure_SlhdsaGetInstance.
XSECURE_SLHDSA_CSUM_INPUT_LEN_IN_DIGITS
Length of checksum input in digits for WOTS+.
Referenced by XSecure_SlhdsaGetInstance.
XSECURE_SLHDSA_CSUM_LEN_IN_DIGITS
Length of checksum in digits.
Referenced by XSecure_SlhdsaGetInstance.
XSECURE_SLHDSA_CSUM_SHIFT
Shift value for checksum calculation.
Referenced by XSecure_SlhdsaGetInstance.
XSECURE_SLHDSA_CSUM_SIZE_IN_BYTES
Size of checksum in bytes.
Referenced by XSecure_SlhdsaGetInstance.
XSecure_Slhdsa_n
16 bytes
XSecure_Slhdsa_h
63
XSecure_Slhdsa_d
7
XSecure_Slhdsa_hprime
3
XSecure_Slhdsa_a
6
XSecure_Slhdsa_k
14
XSecure_Slhdsa_lgw
4
XSecure_Slhdsa_m
30
XSecure_SlhdsaInstance * XSecure_SlhdsaGetInstance(void)
This function returns the XSecure_SlhdsaInstance instance.
SlhdsaInstance stores all required components for SLH-DSA signature verification. Returns pointer to XSecure_SlhdsaInstance instance
References XSecure_SlhdsaInstance::Addr, XSecure_SlhdsaInstance::Data1, XSecure_SlhdsaInstance::Data2, XSecure_SlhdsaInstance::Data3, XSecure_SlhdsaInstance::Data4, XSecure_SlhdsaParam::n, XSecure_SlhdsaInstance::Param, XSECURE_SLH_DSA_A_14, XSECURE_SLH_DSA_D_8, XSECURE_SLH_DSA_H_64, XSECURE_SLH_DSA_HPRIME_8, XSECURE_SLH_DSA_K_22, XSECURE_SLH_DSA_LGW_4, XSECURE_SLH_DSA_M_47, XSECURE_SLH_DSA_N_32, XSECURE_SLHDSA_CSUM_INPUT_LEN_IN_DIGITS, XSECURE_SLHDSA_CSUM_LEN_IN_DIGITS, XSECURE_SLHDSA_CSUM_SHIFT, XSECURE_SLHDSA_CSUM_SIZE_IN_BYTES, XSECURE_SLHDSA_MAX_DATA1_LEN_IN_BYTES, XSECURE_SLHDSA_MAX_DATA2_LEN_IN_BYTES, XSECURE_SLHDSA_MAX_DATA3_LEN_IN_BYTES, XSECURE_SLHDSA_MAX_DATA4_LEN_IN_WORDS, XSECURE_SLHDSA_NO_OF_INV_SIGN, XSECURE_SLHDSA_SHAKE_256S_SIGN_LEN.
Referenced by XSecure_SlhdsaForsPkFromSig, XSecure_SlhdsaHtVerify, XSecure_SlhdsaShake256sChain, XSecure_SlhdsaShake256sHashF, XSecure_SlhdsaShake256sHashH, XSecure_SlhdsaShake256sHashMsg, XSecure_SlhdsaShake256sHashTl, XSecure_SlhdsaVerify, XSecure_SlhdsaWotsPkFromSign, XSecure_SlhdsaXmssPkFromSign.