xsecure_lms_ots.h
XSECURE_LMS_OTS_TYPE_MAX_SUPPORTED
Max supported types, used for creating lookup table for parameters for types supported number should be max valid + 1 (as first slot will be for invalid parameterXSecure_LmsOtsType XSecure_LmsOtsType.
XSECURE_ALLFS
32-bit value with all bits set
Referenced by XSecure_HssInit, XSecure_LmsLookupParamSet.
XSECURE_LMS_OTS_TYPE_SIZE
common lengths - they remain same irrespective of place they are used
Length of type field
Referenced by XSecure_HssFinish, XSecure_HssInit, XSecure_LmsSignatureVerification.
XSECURE_LMS_I_FIELD_SIZE
Length of I field.
Referenced by XSecure_HssInit, XSecure_LmsSignatureVerification.
XSECURE_LMS_Q_FIELD_SIZE
Length of q field.
Referenced by XSecure_HssFinish, XSecure_HssInit, XSecure_LmsSignatureVerification.
XSECURE_LMS_N_FIELD_SIZE
For now supported variants o/p length match.
XSECURE_LMS_C_FIELD_SIZE
32 byte random value for every msg to be authenticated
Referenced by XSecure_HssInit.
XSECURE_LMS_D_MESG_FIELD_SIZE
Size of XSECURE_D_MESG.
XSECURE_LMS_D_PBLC_FIELD_SIZE
Size of XSECURE_D_PBLC.
XSECURE_LMS_DIGEST_SIZE
Digest and Checksum related.
'n' bytes, output of SHA operation
Referenced by XSecure_LmsHashMessage.
XSECURE_LMS_CHECKSUM_FIELD_SIZE
Length of checksum field after digest.
XSECURE_LMS_DIGEST_CHECKSUM_SIZE
Digest of data to be authenticated concatenated with checksum value.
XSECURE_LMS_MESSAGE_TO_DIGEST_PREFIX_SIZE
Prefix fields length, before sending actual data to sha engine for digest.
Referenced by XSecure_LmsHashMessage.
XSECURE_LMS_OTS_PUB_KEY_FIXED_FIELD_SIZE
OTS public key sizes.
XSECURE_LMS_OTS_PUB_KEY_K_FIELD_SIZE
'n' bytes
Referenced by XSecure_LmsSignatureVerification.
XSECURE_LMS_OTS_PUB_KEY_TOTAL_SIZE
OTS Public key total size.
XSECURE_LMS_OTS_SIGN_VERIF_TMP_BUFF_i_SIZE
'i' Field, this causes different hash output for hash position in signature
XSECURE_LMS_OTS_SIGN_VERIF_TMP_BUFF_j_SIZE
'j' Field, this causes different hash output for per iteration (inner loop)
XSECURE_LMS_OTS_SIGN_VERIF_TMP_BUFF_Y_SIZE
Size of individual hash chain placed in sequence in signature
XSECURE_LMS_OTS_SIGN_VERIF_TMP_BUFF_TOTAL_SIZE
Total size of buffer, XSecure_LmsOtsHashPerDigit.
XSECURE_LMS_OTS_SIGN_VERIF_CHAIN_TMP_BUFF_CURR_z_SIZE
Used for calculating the size of z array, based on p value.
XSECURE_LMS_OTS_SIGN_VERIF_CHAIN_TMP_BUFF_z_SIZE
Max possible size as supported only till XSECURE_LMS_OTS_W2.
XSECURE_LMS_OTS_SIGN_VERIF_CHAIN_TMP_BUFF_TOTAL_SIZE
Total MAX Size of buffer used in OTS verification.
XSECURE_LMS_OTS_SIGN_VERIF_CHAIN_TMP_BUFF_CURRENT_SIZE
Total Size of buffer used in OTS verification, while considering current 'p' parameter.
XSECURE_LMS_OTS_PUBKEY_I_OFFSET
Offset of 'I' field in OTS Public key.
XSECURE_LMS_OTS_PUBKEY_Q_OFFSET
Offset of 'q' field in OTS Public key.
XSECURE_LMS_OTS_SIGN_TYPE_FIELD_OFFSET
Offset of 'Type' field in OTS Signature buffer.
Referenced by XSecure_LmsSignatureVerification.
XSECURE_LMS_OTS_SIGN_C_FIELD_OFFSET
Offset of 'C' field in OTS Signature buffer.
Referenced by XSecure_HssInit.
XSECURE_LMS_OTS_SIGN_Y_FIELD_OFFSET
Offset of 'Y' field in OTS Signature buffer.
XSECURE_LMS_OTS_SIGN_VERIF_TMP_BUFF_I_OFFSET
Offset of 'I' field in temporary buffer, where inner loops result are stored, for reprocessing during OTS operations.
XSECURE_LMS_OTS_SIGN_VERIF_TMP_BUFF_Q_OFFSET
Offset of 'q' field in temporary buffer, where inner loops result are stored, for reprocessing during OTS operations.
XSECURE_LMS_OTS_SIGN_VERIF_TMP_BUFF_i_OFFSET
Offset of 'i' field in temporary buffer, where inner loops result are stored, for reprocessing during OTS operations.
XSECURE_LMS_OTS_SIGN_VERIF_TMP_BUFF_j_OFFSET
Offset of 'j' field in temporary buffer, where inner loops result are stored, for reprocessing during OTS operations.
XSECURE_LMS_OTS_SIGN_VERIF_TMP_BUFF_Y_OFFSET
Offset of 'Y' field in temporary buffer, where inner loops result are stored, for reprocessing during OTS operations.
XSECURE_LMS_OTS_SIGN_VERIF_CHAIN_TMP_BUFF_I_OFFSET
Offset of 'I' field in temporary buffer, where inner loops result is concatenated during OTS operations.
XSECURE_LMS_OTS_SIGN_VERIF_CHAIN_TMP_BUFF_Q_OFFSET
Offset of 'q' field in temporary buffer, where inner loops result is concatenated during OTS operations.
XSECURE_LMS_OTS_SIGN_VERIF_CHAIN_TMP_BUFF_D_PBLC_OFFSET
Offset of D_PBLC field in temporary buffer, where inner loops result is concatenated during OTS operations.
XSECURE_LMS_OTS_SIGN_VERIF_CHAIN_TMP_BUFF_Z_OFFSET
Offset of 'z' field in temporary buffer, where inner loops result is concatenated during OTS operations.
XSecure_LmsOtsType
Reserved.
XSecure_LmsOtsWIndex
Not Supported.
XSecure_LmsOtsuIndex
Not Supported.
XSecure_LmsOtsvIndex
Not Supported.
XSecure_LmsOtslsIndex
'ls' corresponding to 'w' = 2
XSecure_LmsOtspIndex
Not Supported.
typedef union XSecure_LmsOtsPublicKey_ XSecure_LmsOtsPublicKey
LMS OTS Public key structure.
Size = 4 + 16 + 4 + H Len (32) = 56 Bytes
typedef union XSecure_LmsOtsHashPerDigit_ XSecure_LmsOtsHashPerDigit
Temporary buffer, used in LMS OTS signature verification, used in hash chain to arrive at values which will be concatenated and hashed to get public value.
Size = 1 + 16 + 4 + 2 + 1 + H Len (32) = 56 Bytes
typedef union XSecure_LmsOtsSignToPubKeyHash_ XSecure_LmsOtsSignToPubKeyHash
Structure used when validating LMS OTS, once hash chain is completed, result needs to be stored so that they can be further concatenated and hashed to get OTS public key, this provides a way to access members and fill data in a structured way.
Size = 16(I) + 4(q) + 2(D_PBLC) + (p * H Len (32))
typedef struct XSecure_LmsOtsSignature_ XSecure_LmsOtsSignature
Partial LMS OTS Signature structure.
struct Size = 4 + 32 Sign size = 4 + 32 + (p * n) = 4 + n * (p+1)
typedef union XSecure_LmsDataDigestFixedFields_ XSecure_LmsDataDigestFixedFields
Temporary buffer, used to send prefix fields to calculate digest for data to be authenticate.
Size = I (16) + q (4) + D_MESG (2) + C (32) = 54 Bytes
typedef union XSecure_LmsDataDigest_ XSecure_LmsDataDigest
Digest for message to be authenticated, along with checksum.
Size = Digest (32) + Check sum (2) = 34 Bytes
u32 XSecure_LmsOtsCoeff(u8 const *const Arr, const u32 ArrayIndex, const u32 w)
This function extracts the digits from the array for bytes.
S (represented in bits) = 0x1234 [0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0] ^ | coef(S, 7, 1) [1, 2, 3, 4] ^ | coef(S, 0, 4)If i is larger than the number of w-bit values in S, then coef(S, i, w) is undefined, this can't be checked here Arr Byte array from where the digit needs to be picked ArrayIndex When array is divided into array of digits, i represents the index of digit w Width in bits, for each digit allowed values digit value.
int XSecure_LmsOtsComputeChecksum(const u8 *const Array, const u32 ArrayLen, const u32 w, const u32 ls, u32 *const Checksum)
This function calculates the checksum for a given array.
Array Byte array ffor which checksum needs to be calculated ArrayLen Length of input array w Width in bits, for each digit allowed values ls Number of bits to left-shift the calculated checksum Checksum Pointer to address, where computed checksum needs to be copied XST_SUCCESS - On successXSECURE_LMS_OTS_CHECKSUM_BUFF_INVALID_LEN_ERROR - Invalid buffer length (zero length)
References XSECURE_LMS_OTS_CHECKSUM_BUFF_INVALID_LEN_ERROR.
int XSecure_LmsOtsLookupParamSet(XSecure_LmsOtsType Type, XSecure_LmsOtsParam **Parameters)
This function returns the parameters for the type of LMS OTS type.
Type XSecure_LmsOtsType, type of OTS algorithm selected Parameters Pointer to array location where all predefined parameter values are present XSecure_LmsOtsParam XST_SUCCESS - On successXSECURE_LMS_OTS_TYPE_UNSUPPORTED_ERROR - LMS OTS type is not supportedXSECURE_LMS_OTS_TYPE_LOOKUP_GLITCH_ERROR - Glitch detected during type lookup
References XSecure_LmsOtsParam::H, XSECURE_LMS_OTS_LS_NOT_SUPPORTED, XSECURE_LMS_OTS_P_NOT_SUPPORTED, XSECURE_LMS_OTS_U_NOT_SUPPORTED, XSECURE_LMS_OTS_V_NOT_SUPPORTED, XSECURE_LMS_OTS_W_NOT_SUPPORTED.
Referenced by XSecure_HssFinish, XSecure_HssInit, XSecure_LmsSignatureVerification.