xsecure_alghelper.c
XSECURE_RESPONSE_STATUS_IDX
Response status index.
Referenced by XSecure_GetAlgInfo.
int XSecure_GetAlgInfo(Xil_CryptoAlgInfo *AlgInfo, u32 CryptoAlg)
Retrieves cryptographic algorithm information from PLM.
AlgInfo Pointer to Xil_CryptoAlgInfo structure CryptoAlg Cryptographic algorithm identifier XST_SUCCESS - On successXST_INVALID_PARAM - If input parameters are invalidError - On failure
References XSECURE_ALGO_VERSION_RESP_INDEX, XSECURE_API_FEATURES, XSecure_ClientInit, XSECURE_NIST_STATUS_RESP_INDEX, XSECURE_RESPONSE_STATUS_IDX.
Referenced by XSecure_AesGetCryptoAlgInfo, XSecure_EcdhGetCryptoAlgInfo, XSecure_EllipticGetCryptoAlgInfo, XSecure_HmacGetCryptoAlgInfo, XSecure_KeyUnwrapGetCryptoAlgInfo, XSecure_LmsGetCryptoAlgInfo, XSecure_RsaGetCryptoAlgInfo, XSecure_Sha3GetCryptoAlgInfo, XSecure_ShaGetCryptoAlgInfo, XSecure_TrngGetCryptoAlgInfo.