xsecure_lms.h
XSECURE_IS_ODD
Check if a value is odd.
Referenced by XSecure_LmsSignatureVerification, XSecure_SlhdsaForsPkFromSig, XSecure_SlhdsaXmssPkFromSign.
XSECURE_LMS_TYPE_MAX_SUPPORTED
Max supported types, used for creating lookup table for parameters for types supported number should be max valid + 1 (as first slot will be for invalid parameters) XSecure_LmsType from 0 (unsupported) to XSECURE_LMS_SHAKE_M32_H20.
Referenced by XSecure_LmsLookupParamSet.
XSECURE_LMS_TYPE_SIZE
Length of type field.
Referenced by XSecure_GetLmsHashAlgo, XSecure_HssFinish, XSecure_HssInit, XSecure_HssSignatureVerification, XSecure_LmsSignatureVerification.
XSECURE_LMS_M_BYTE_FIELD_SIZE
Length of M byte field.
Referenced by XSecure_LmsSignatureVerification.
XSECURE_LMS_PUB_KEY_FIXED_FIELD_SIZE
Length of fixed part of public key.
Referenced by XSecure_LmsSignatureVerification.
XSECURE_LMS_PUB_KEY_T_FIELD_SIZE
Length of T field of public key.
Referenced by XSecure_LmsSignatureVerification.
XSECURE_LMS_PUB_KEY_TOTAL_SIZE
Length of total public key.
Referenced by XSecure_HssFinish, XSecure_HssInit, XSecure_LmsSha2256Kat, XSecure_LmsShake256Kat.
XSECURE_MERKLE_TREE_NODE_NUMBER_SIZE
Length of Merkle tree node number.
XSECURE_LMS_D_LEAF_FIELD_SIZE
Length of D leaf field.
XSECURE_LMS_D_INTR_FIELD_SIZE
Length of D internal field.
XSECURE_LMS_D_FIELD_SIZE
Length of D field.
XSECURE_LMS_PUB_KEY_TMP_BUFFER_LEAF_TOTAL_SIZE
Used for leaf node processing.
Referenced by XSecure_LmsSignatureVerification.
XSECURE_LMS_PUB_KEY_TMP_BUFFER_INTR_TOTAL_SIZE
Used for internal nodes processing.
Referenced by XSecure_LmsSignatureVerification.
XSECURE_LMS_PUB_KEY_TYPE_OFFSET
Offset of LmsType field in public key.
Referenced by XSecure_GetLmsHashAlgo, XSecure_HssFinish, XSecure_HssInit, XSecure_HssSignatureVerification, XSecure_LmsSignatureVerification.
XSECURE_LMS_PUB_KEY_OTS_TYPE_OFFSET
Offset of OtsType field in public key.
Referenced by XSecure_HssFinish, XSecure_HssInit, XSecure_LmsSignatureVerification.
XSECURE_LMS_PUB_KEY_I_OFFSET
Offset of I field in public key.
Referenced by XSecure_LmsSignatureVerification.
XSECURE_LMS_PUB_KEY_T_OFFSET
Offset of T field in public key.
Referenced by XSecure_LmsSignatureVerification.
XSECURE_LMS_SIGNATURE_Q_FIELD_OFFSET
Offset of Q field in LMS Signature.
Referenced by XSecure_HssInit, XSecure_LmsSignatureVerification.
XSECURE_LMS_SIGNATURE_OTS_FIELD_OFFSET
Offset of OTS field in LMS Signature.
Referenced by XSecure_HssInit, XSecure_LmsSignatureVerification.
XSecure_LmsType
Reserved.
XSecure_LmsTreeHeight
Unsupported tree height.
typedef union XSecure_LmsPublicKey_ XSecure_LmsPublicKey
LMS Public key structure to access root value.
Size = 4 + 4 + 16 + H Len (32) = 56 Bytes
typedef union XSecure_LmsPubKeyTmp_ XSecure_LmsPubKeyTmp
Used to store data which is repeatedly sent to SHA engine, during LMS root value calculation.
Size = 16(I) + 4(node_number/2) + 2(D_INTR) + (32 * 2)
int XSecure_LmsLookupParamSet(XSecure_LmsType Type, XSecure_LmsParam **Parameters)
This function returns the parameters for the type of LMS type.
Type XSecure_LmsType, type of OTS algorithm selected Parameters Pointer to array location where all predefined parameter values are present XSecure_LmsParam XST_SUCCESS - Valid type is passed, and parameters are assignedXST_FAILURE - If not a valid type is passed
References XSecure_LmsParam::H, XSECURE_ALLFS, XSECURE_LMS_NOT_SUPPORTED, XSECURE_LMS_RESERVED, XSECURE_LMS_SHA256_M32_H10, XSECURE_LMS_SHA256_M32_H15, XSECURE_LMS_SHA256_M32_H20, XSECURE_LMS_SHA256_M32_H5, XSECURE_LMS_SHAKE_M32_H10, XSECURE_LMS_SHAKE_M32_H15, XSECURE_LMS_SHAKE_M32_H20, XSECURE_LMS_SHAKE_M32_H5, XSECURE_LMS_TREE_HEIGHT_H10, XSECURE_LMS_TREE_HEIGHT_H15, XSECURE_LMS_TREE_HEIGHT_H20, XSECURE_LMS_TREE_HEIGHT_H5, XSECURE_LMS_TREE_HEIGHT_UNSUPPORTED, XSECURE_LMS_TYPE_LOOKUP_GLITCH_ERROR, XSECURE_LMS_TYPE_MAX_SUPPORTED, XSECURE_LMS_TYPE_UNSUPPORTED_ERROR, XSECURE_SHA2_256_HASH_LEN, XSECURE_SHAKE_256, XSECURE_SHAKE_256_HASH_LEN.
Referenced by XSecure_GetLmsHashAlgo, XSecure_HssFinish, XSecure_HssInit, XSecure_HssSignatureVerification, XSecure_LmsSignatureVerification.