xsecure_init.c
XSecure_Sha XSecure_ShaInstance[XSECURE_SHA_NUM_OF_INSTANCES][XSECURE_SHA_NUM_OF_INSTANCES]
int XSecure_AesShaInit(void)
This function initializes AES and SHA hardware instances.
XST_SUCCESS - On successXST_FAILURE - On failure
References XSecure_AesInitialize, XSecure_GetAesInstance, XSecure_GetSha2Instance, XSecure_GetSha3Instance, XSECURE_SHA_0_DEVICE_ID, XSECURE_SHA_1_DEVICE_ID, XSecure_ShaInitialize, XSecure_ShaLookupConfig.
Referenced by XSecure_Init.
int XSecure_Init(XSecure_PartialPdiEventParams *PpdiEventParamsPtr)
This function registers the handlers for XilSecure IPI commands.
PpdiEventParamsPtr is the pointer to partial PDI event parameters XST_SUCCESS - On successXST_FAILURE - On failure
References XSecure_AddRsaKeyPairGenerationToScheduler, XSecure_AesShaInit, XSecure_CmdsInit.
XSecure_Sha * XSecure_GetSha3Instance(u32 DeviceId)
This function provides the pointer to the sha3 instance.
Pointer to the XSecure_Sha instance
References XSecure_GetShaInstance.
Referenced by XSecure_AesShaInit, XSecure_Hkdf, XSecure_HmacIpiHandler, XSecure_KatIpiHandler, XSecure_SetDataContextLost, XSecure_Sha3IpiHandler, XSecure_ShaIpiHandler, XSecure_SlhdsaIpiHandler.
XSecure_Sha * XSecure_GetSha2Instance(u32 DeviceId)
This function provides the pointer to the sha2 instance.
Pointer to the XSecure_Sha instance
References XSecure_GetShaInstance.
Referenced by XSecure_AesShaInit, XSecure_KatPlatIpiHandler, XSecure_ShaIpiHandler.
XSecure_Aes * XSecure_GetAesInstance(void)
This function provides the pointer to the common Aes instance which has to be used between PLM and xilsecure server.
Pointer to the XSecure_Aes instance
Referenced by XSecure_AesInit, XSecure_AesIpiHandler, XSecure_AesKeyWrite, XSecure_AesKeyZeroize, XSecure_AesPerformOperation, XSecure_AesPlatPmcDmaCfgAndXfer, XSecure_AesShaInit, XSecure_ConfigureDmaByteSwap, XSecure_KatIpiHandler, XSecure_KeyUnwrap, XSecure_PlatAesIpiHandler, XSecure_SetDataContextLost.
XSecure_Rsa * XSecure_GetRsaInstance(void)
This function provides the pointer to the common Rsa instance which has to be used between PLM and xilsecure server.
Pointer to the XSecure_Rsa instance
XSecure_Sha * XSecure_GetShaInstance(u32 DeviceId)
This function provides the pointer to the sha instance based on the DevieId.
Pointer to the XSecure_Sha instance
References XSECURE_SHA_NUM_OF_INSTANCES.
Referenced by XSecure_GetSha2Instance, XSecure_GetSha3Instance.