xsecure_kat.c
XSECURE_KAT_AES_SPLIT_DATA_SIZE
< AES KAT parameters
XSECURE_KAT_KEY_SIZE_IN_WORDS
XSECURE_KAT_OPER_DATA_SIZE_IN_WORDS
const u32 Key0[XSECURE_KAT_KEY_SIZE_IN_WORDS][XSECURE_KAT_KEY_SIZE_IN_WORDS]
const u32 Data0[XSECURE_KAT_OPER_DATA_SIZE_IN_WORDS][XSECURE_KAT_OPER_DATA_SIZE_IN_WORDS]
const u32 Ct0[XSECURE_KAT_AES_SPLIT_DATA_SIZE][XSECURE_KAT_AES_SPLIT_DATA_SIZE]
const u32 MiC0[XSECURE_KAT_AES_SPLIT_DATA_SIZE][XSECURE_KAT_AES_SPLIT_DATA_SIZE]
const u8 KatMessage[XSECURE_KAT_MSG_LEN_IN_BYTES][XSECURE_KAT_MSG_LEN_IN_BYTES]
const u8 AesKey[XSECURE_KAT_KEY_SIZE_IN_BYTES][XSECURE_KAT_KEY_SIZE_IN_BYTES]
const u8 AesIv[XSECURE_KAT_IV_SIZE_IN_BYTES][XSECURE_KAT_IV_SIZE_IN_BYTES]
const u8 AesCt[XSECURE_KAT_MSG_LEN_IN_BYTES][XSECURE_KAT_MSG_LEN_IN_BYTES]
const u8 AesGcmTag[XSECURE_SECURE_GCM_TAG_SIZE][XSECURE_SECURE_GCM_TAG_SIZE]
const u8 AesAadData[XSECURE_KAT_AAD_SIZE_IN_BYTES][XSECURE_KAT_AAD_SIZE_IN_BYTES]
const u8 ExpSha3Hash[XSECURE_SHA_384_HASH_SIZE_IN_BYTES][XSECURE_SHA_384_HASH_SIZE_IN_BYTES]
const u32 RsaModulus[XSECURE_RSA_2048_SIZE_WORDS][XSECURE_RSA_2048_SIZE_WORDS]
const u32 RsaModExt[XSECURE_RSA_2048_SIZE_WORDS][XSECURE_RSA_2048_SIZE_WORDS]
const u32 RsaData[XSECURE_RSA_2048_SIZE_WORDS][XSECURE_RSA_2048_SIZE_WORDS]
const u32 RsaExpCtData[XSECURE_RSA_2048_SIZE_WORDS][XSECURE_RSA_2048_SIZE_WORDS]
const u8 Pubkey_P384[XSECURE_ECC_P384_SIZE_IN_BYTES+XSECURE_ECC_P384_SIZE_IN_BYTES][XSECURE_ECC_P384_SIZE_IN_BYTES+XSECURE_ECC_P384_SIZE_IN_BYTES]
const u8 Sign_P384[XSECURE_ECC_P384_SIZE_IN_BYTES+XSECURE_ECC_P384_SIZE_IN_BYTES][XSECURE_ECC_P384_SIZE_IN_BYTES+XSECURE_ECC_P384_SIZE_IN_BYTES]
const u8 D_P384[XSECURE_ECC_P384_SIZE_IN_BYTES][XSECURE_ECC_P384_SIZE_IN_BYTES]
const u8 K_P384[XSECURE_ECC_P384_SIZE_IN_BYTES][XSECURE_ECC_P384_SIZE_IN_BYTES]
const u8 ExpEccSha3Hash[XSECURE_KAT_ECC_P521_SHA3_HASH_SIZE_IN_BYTES][XSECURE_KAT_ECC_P521_SHA3_HASH_SIZE_IN_BYTES]
static int XSecure_AesDecCmChecks(const u32 *P, const u32 *Q, const u32 *R, const u32 *S)
This function performs checks for AES DPA CM KAT output.
P is the pointer to the data array of size 4 words. Q is the pointer to the data array of size 4 words. R is the pointer to the data array of size 4 words. S is the pointer to the data array of size 4 words. XST_SUCCESS - When check is passedXST_FAILURE - when check is failed
u8 * XSecure_GetKatMessage(void)
This function returns message to perform KAT.
Message to perform KAT
Referenced by XSecure_AesDecryptKat, XSecure_AesEncryptKat, XSecure_HmacKat, XSecure_RsaPwct, XSecure_Sha384Kat.
u8 * XSecure_GetKatAesKey(void)
This function returns AES key for KAT.
AES key for KAT
Referenced by XSecure_HmacKat.
u8 * XSecure_GetKatSha3ExpHash(void)
This function returns expected SHA3 hash for KAT.
Expected SHA3 hash for KAT
u32 * XSecure_GetKatRsaModulus(void)
This function returns modulus for RSA KAT.
RSA modulus for KAT
Referenced by XSecure_RsaPrivateDecryptKat.
u32 * XSecure_GetKatRsaModExt(void)
This function returns public pre-calculated exponential (R^2 Mod N) value for RSA KAT.
RSA pre-calculated exponential (R^2 Mod N) value for KAT
Referenced by XSecure_RsaPrivateDecryptKat.
u32 * XSecure_GetKatRsaData(void)
This function returns data for RSA KAT.
Input data to be encrypted for RSA KAT
Referenced by XSecure_RsaPrivateDecryptKat.
u32 * XSecure_GetKatRsaCtData(void)
This function returns cipher text data for RSA KAT.
Expected cipher text for RSA KAT
Referenced by XSecure_RsaPrivateDecryptKat.
u32 * XSecure_GetKatRsaPrivateExp(void)
This function returns private exponent for RSA KAT.
RSA private exponent for KAT
References XSECURE_RSA_2048_SIZE_WORDS.
Referenced by XSecure_RsaPrivateDecryptKat.
XSecure_EllipticKey * XSecure_GetKatEccPublicKey(XSecure_EllipticCrvClass CrvClass)
This function returns ECC public key to perform KAT.
CrvClass ECC curve class ECC public key
References XSecure_EllipticKey::Qx, XSecure_EllipticKey::Qy, XSECURE_ECC_P384_SIZE_IN_BYTES, XSECURE_ECC_PRIME.
Referenced by XSecure_EllipticVerifySignKat.
XSecure_EllipticSign * XSecure_GetKatEccExpSign(XSecure_EllipticCrvClass CrvClass)
This function returns ECC expected signature to perform KAT.
CrvClass ECC curve class ECC expected signature
References XSecure_EllipticSign::SignR, XSecure_EllipticSign::SignS, XSECURE_ECC_P384_SIZE_IN_BYTES, XSECURE_ECC_PRIME.
Referenced by XSecure_EllipticSignGenerateKat, XSecure_EllipticVerifySignKat.
u8 * XSecure_GetKatEccPrivateKey(XSecure_EllipticCrvClass CrvClass)
This function returns ECC private key to perform KAT.
CrvClass ECC curve class ECC private key
References XSECURE_ECC_PRIME.
Referenced by XSecure_EllipticSignGenerateKat.
u8 * XSecure_GetKatEccEphemeralKey(XSecure_EllipticCrvTyp CrvType)
This function returns ECC ephemeral key to perform KAT.
CrvType ECC curve type ECC ephemeral key
References XSECURE_ECC_NIST_P192, XSECURE_ECC_NIST_P224, XSECURE_ECC_NIST_P256, XSECURE_ECC_NIST_P384, XSECURE_ECC_NIST_P521.
Referenced by XSecure_EllipticPwct, XSecure_EllipticSignGenerateKat.
int XSecure_AesDecryptCmKat(const XSecure_Aes *AesInstance)
This function performs known answer test(KAT) on AES engine to confirm DPA counter measures is working fine.
AesInstance Pointer to the XSecure_Aes instance XST_SUCCESS - When KAT PassXSECURE_AESKAT_INVALID_PARAM - On invalid argumentXSECURE_AES_KAT_BUSY - when AES is busyXSECURE_AES_STATE_MISMATCH_ERROR - If AES state is mismatchedXSECURE_AESDPACM_KAT_CHECK1_FAILED_ERROR - Error when AESDPACM data not matched with expected dataXSECURE_AESDPACM_KAT_CHECK2_FAILED_ERROR - Error when AESDPACM data not matched with expected dataXSECURE_AESDPACM_KAT_CHECK3_FAILED_ERROR - Error when AESDPACM data not matched with expected dataXSECURE_AESDPACM_KAT_CHECK4_FAILED_ERROR - Error when AESDPACM data not matched with expected dataXSECURE_AESDPACM_KAT_CHECK5_FAILED_ERROR - Error when AESDPACM data not matched with expected dataXST_FAILURE - On failure
References R0, XSECURE_AES_KAT_BUSY, XSECURE_AES_STATE_MISMATCH_ERROR, XSECURE_AES_USER_KEY_7, XSECURE_AESDPACM_KAT_CHECK1_FAILED_ERROR, XSECURE_AESDPACM_KAT_CHECK2_FAILED_ERROR, XSECURE_AESDPACM_KAT_CHECK3_FAILED_ERROR, XSECURE_AESDPACM_KAT_CHECK4_FAILED_ERROR, XSECURE_AESDPACM_KAT_CHECK5_FAILED_ERROR, XSecure_AesDpaCmDecryptData, XSECURE_AESKAT_INVALID_PARAM, XSecure_AesKeyZero.
int XSecure_AesDecryptKat(XSecure_Aes *AesInstance)
This function performs decryption known answer test(KAT) on AES engine.
AesInstance Pointer to the XSecure_Aes instance XST_SUCCESS - When KAT PassXSECURE_AESKAT_INVALID_PARAM - Invalid ArgumentXSECURE_AES_KAT_BUSY - Error when AES is busyXSECURE_AES_STATE_MISMATCH_ERROR - Error when AES state is mismatchedXSECURE_AES_KAT_WRITE_KEY_FAILED_ERROR - Error when AES key write failsXSECURE_AES_KAT_DECRYPT_INIT_FAILED_ERROR - Error when AES decrypt init failsXSECURE_AES_KAT_UPDATE_AAD_FAILED_ERROR - Error when update AAD failsXSECURE_AES_KAT_DECRYPT_UPDATE_FAILED_ERROR - Error when decrypt update failsXSECURE_AES_KAT_GCM_TAG_MISMATCH_ERROR - Error when GCM tag not matched with user provided tagXSECURE_AES_KAT_DATA_MISMATCH_ERROR - Error when AES data not matched with expected data
References XSECURE_AES_KAT_BUSY, XSECURE_AES_KAT_DATA_MISMATCH_ERROR, XSECURE_AES_KAT_DECRYPT_INIT_FAILED_ERROR, XSECURE_AES_KAT_DECRYPT_UPDATE_FAILED_ERROR, XSECURE_AES_KAT_GCM_TAG_MISMATCH_ERROR, XSECURE_AES_KAT_UPDATE_AAD_FAILED_ERROR, XSECURE_AES_KAT_WRITE_KEY_FAILED_ERROR, XSECURE_AES_STATE_MISMATCH_ERROR, XSECURE_AES_USER_KEY_7, XSecure_AesDecryptFinal, XSecure_AesDecryptInit, XSecure_AesDecryptUpdate, XSECURE_AESKAT_INVALID_PARAM, XSecure_AesKeyZero, XSecure_AesUpdateAad, XSecure_AesWriteKey, XSecure_ConfigureDmaByteSwap, XSECURE_ENABLE_BYTE_SWAP, XSecure_GetKatMessage, XSECURE_KAT_AAD_SIZE_IN_BYTES, XSECURE_KAT_MSG_LEN_IN_BYTES, XSECURE_KAT_MSG_LEN_IN_WORDS.
int XSecure_AesEncryptKat(XSecure_Aes *AesInstance)
This function performs encryption known answer test(KAT) on AES engine.
AesInstance Pointer to the XSecure_Aes instance XST_SUCCESS - When KAT PassXSECURE_AESKAT_INVALID_PARAM - Invalid ArgumentXSECURE_AES_KAT_BUSY - Error when AES is busyXSECURE_AES_STATE_MISMATCH_ERROR - Error when AES state is mismatchedXSECURE_AES_KAT_WRITE_KEY_FAILED_ERROR - Error when AES key write failsXSECURE_AES_KAT_ENCRYPT_INIT_FAILED_ERROR - Error when AES encrypt init failsXSECURE_AES_KAT_UPDATE_AAD_FAILED_ERROR - Error when update AAD failsXSECURE_AES_KAT_ENCRYPT_UPDATE_FAILED_ERROR - Error when AES encrypt update failsXSECURE_AES_KAT_ENCRYPT_FINAL_FAILED_ERROR - Error when AES encrypt final failsXSECURE_KAT_GCM_TAG_MISMATCH_ERROR - Error when GCM tag not matched with user provided tagXSECURE_AES_KAT_DATA_MISMATCH_ERROR - Error when AES data not matched with expected data
References XSECURE_AES_KAT_BUSY, XSECURE_AES_KAT_DATA_MISMATCH_ERROR, XSECURE_AES_KAT_ENCRYPT_FINAL_FAILED_ERROR, XSECURE_AES_KAT_ENCRYPT_INIT_FAILED_ERROR, XSECURE_AES_KAT_ENCRYPT_UPDATE_FAILED_ERROR, XSECURE_AES_KAT_UPDATE_AAD_FAILED_ERROR, XSECURE_AES_KAT_WRITE_KEY_FAILED_ERROR, XSECURE_AES_STATE_MISMATCH_ERROR, XSECURE_AES_USER_KEY_7, XSecure_AesEncryptFinal, XSecure_AesEncryptInit, XSecure_AesEncryptUpdate, XSECURE_AESKAT_INVALID_PARAM, XSecure_AesKeyZero, XSecure_AesUpdateAad, XSecure_AesWriteKey, XSecure_ConfigureDmaByteSwap, XSECURE_ENABLE_BYTE_SWAP, XSecure_GetKatMessage, XSECURE_KAT_AAD_SIZE_IN_BYTES, XSECURE_KAT_GCM_TAG_MISMATCH_ERROR, XSECURE_KAT_MSG_LEN_IN_BYTES, XSECURE_KAT_MSG_LEN_IN_WORDS.
int XSecure_Sha3Kat(XSecure_Sha3 *SecureSha3)
This function performs known answer test(KAT) on SHA crypto engine.
SecureSha3 Pointer to the XSecure_Sha3 instance XST_SUCCESS - When KAT PassXSECURE_SHA3_INVALID_PARAM - On invalid argumentXSECURE_SHA3_KAT_BUSY - Error when SHA3 is busyXSECURE_SHA3_LAST_UPDATE_ERROR - Error when SHA3 last update failsXSECURE_SHA3_KAT_FAILED_ERROR - Error when SHA3 hash not matched with expected hashXSECURE_SHA3_PMC_DMA_UPDATE_ERROR - Error when DMA driver fails to update the data to SHA3XSECURE_SHA3_FINISH_ERROR - Error when SHA3 finish fails
References XSECURE_KAT_MSG_LEN_IN_BYTES, XSecure_SetReset, XSECURE_SHA3_384, XSECURE_SHA3_FINISH_ERROR, XSECURE_SHA3_INVALID_PARAM, XSECURE_SHA3_KAT_BUSY, XSECURE_SHA3_KAT_FAILED_ERROR, XSECURE_SHA3_PMC_DMA_UPDATE_ERROR, XSECURE_SHA3_RESET_OFFSET, XSecure_ShaFinish, XSecure_ShaLastUpdate, XSecure_ShaStart, XSecure_ShaUpdate.
int XSecure_RsaPublicEncryptKat(void)
This function performs KAT on RSA core.
XST_SUCCESS - On successXSECURE_RSA_KAT_INIT_ERROR - Error when RSA init failsXSECURE_RSA_KAT_ENCRYPT_FAILED_ERROR - When RSA KAT failsXSECURE_RSA_KAT_ENCRYPT_DATA_MISMATCH_ERROR - Error when RSA data not matched with expected data
References XSECURE_KAT_RSA_PUB_EXP, XSECURE_RSA_2048_KEY_SIZE, XSECURE_RSA_2048_SIZE_WORDS, XSECURE_RSA_KAT_ENCRYPT_DATA_MISMATCH_ERROR, XSECURE_RSA_KAT_ENCRYPT_FAILED_ERROR, XSECURE_RSA_KAT_INIT_ERROR, XSecure_RsaInitialize, XSecure_RsaPublicEncrypt.
int XSecure_EllipticVerifySignKat(XSecure_EllipticCrvClass CrvClass)
This function performs ECC sign verify known answer test(KAT) on ECC core.
CrvClass Type of ECC curve class either prime or binary curve XST_SUCCESS - On successXSECURE_ELLIPTIC_KAT_KEY_NOTVALID_ERROR - When elliptic key is invalidXSECURE_ELLIPTIC_KAT_INVLD_CRV_ERROR - Error when input is invalidXSECURE_ELLIPTIC_KAT_SIGN_VERIFY_ERROR - When signature is invalid
References XSecure_EllipticKey::Qx, XSecure_EllipticKey::Qy, XSecure_EllipticSign::SignR, XSecure_EllipticSign::SignS, XSECURE_ECC_NIST_P384, XSECURE_ELLIPTIC_KAT_INVLD_CRV_ERROR, XSECURE_ELLIPTIC_KAT_KEY_NOTVALID_ERROR, XSECURE_ELLIPTIC_KAT_SIGN_VERIFY_ERROR, XSecure_EllipticValidateKey, XSecure_EllipticVerifySign, XSecure_GetKatEccExpSign, XSecure_GetKatEccPublicKey.
int XSecure_EllipticSignGenerateKat(XSecure_EllipticCrvClass CrvClass)
This function performs ECC sign generate known answer test(KAT) on ECC core.
CrvClass Type of ECC curve class either prime or binary class XST_SUCCESS - When KAT passesXSECURE_ELLIPTIC_KAT_INVLD_CRV_ERROR - When input is invalid.XSECURE_ELLIPTIC_KAT_GENERATE_SIGN_ERROR - When generate sign failsXSECURE_ELLIPTIC_KAT_GENERATE_SIGNR_ERROR - When SignR is mismatched
References XSecure_EllipticSign::SignR, XSecure_EllipticSign::SignS, XSECURE_ECC_NIST_P384, XSECURE_ECC_P384_SIZE_IN_BYTES, XSECURE_ELLIPTIC_KAT_GENERATE_SIGN_ERROR, XSECURE_ELLIPTIC_KAT_GENERATE_SIGNR_ERROR, XSECURE_ELLIPTIC_KAT_INVLD_CRV_ERROR, XSecure_EllipticGenerateSignature, XSecure_GetKatEccEphemeralKey, XSecure_GetKatEccExpSign, XSecure_GetKatEccPrivateKey.
int XSecure_EllipticPwct(XSecure_EllipticCrvTyp Curvetype, u64 DAddr, XSecure_EllipticKeyAddr *PubKeyAddr)
This function performs ECC pairwise consistency test on ECC core.
Curvetype Type of ECC curve used for authentication DAddr Address of ECC private key PubKeyAddr Address of ECC public key XST_SUCCESS - When KAT passesXSECURE_ELLIPTIC_KAT_INVLD_CRV_ERROR - When input is invalidXSECURE_ELLIPTIC_KAT_GENERATE_SIGN_64BIT_ERROR - When generate signature failsXSECURE_ELLIPTIC_KAT_64BIT_SIGN_VERIFY_ERROR - When verify sign is invalid
References XSecure_EllipticHashData::Addr, XSecure_EllipticHashData::Len, XSecure_EllipticSignAddr::SignR, XSecure_EllipticSignAddr::SignS, XSECURE_ECC_NIST_P192, XSECURE_ECC_NIST_P224, XSECURE_ECC_NIST_P256, XSECURE_ECC_NIST_P384, XSECURE_ECC_NIST_P521, XSECURE_ECC_P192_SIZE_IN_BYTES, XSECURE_ECC_P224_SIZE_IN_BYTES, XSECURE_ECC_P256_SIZE_IN_BYTES, XSECURE_ECC_P384_SIZE_IN_BYTES, XSECURE_ECC_P521_SIZE_IN_BYTES, XSECURE_ELLIPTIC_KAT_64BIT_SIGN_VERIFY_ERROR, XSECURE_ELLIPTIC_KAT_GENERATE_SIGN_64BIT_ERROR, XSECURE_ELLIPTIC_KAT_INVLD_CRV_ERROR, XSecure_EllipticGenerateSignature_64Bit, XSecure_EllipticVerifySign_64Bit, XSecure_GetKatEccEphemeralKey.