zynqmp/xsecure_rsa.c
XSECURE_RSA_PUBLIC_EXPO_SIZE
Size of public key expo.
static int XSecure_IsNonZeroBuffer(u8 *Data, const u32 Size)
This function checks if the data in the provided buffer is non-zero.
Data - Pointer to the buffer which contains data to be validated Size - Size of the buffer in bytes XST_SUCCESS In case of non-zero bufferXST_FAILURE In case the buffer is all zeroes
int XSecure_RsaInitialize_64Bit(XSecure_Rsa *InstancePtr, u64 Mod, u64 ModExt, u64 ModExpo)
This function initializes a a XSecure_Rsa structure with the default values located at a 64-bit address required for operating the RSA cryptographic engine.
InstancePtr Pointer to the XSecure_Rsa instance Mod Address of the key Modulus of key size ModExt Address of the pre-calculated exponential (R^2 Mod N) value, or 0 if user doesn't have pre-calculated R^2 Mod N value (control will take care of this calculation internally) ModExpo Address of the buffer which contains key exponent XST_SUCCESS - If initialization was successfulXSECURE_RSA_INVALID_PARAM - On invalid arguments Modulus, ModExt and ModExpo are part of partition signature when authenticated boot image is generated by bootgen, else the all of them should be extracted from the key
References XSecure_Rsa::Mod, XSecure_Rsa::ModAddr, XSecure_Rsa::ModExpo, XSecure_Rsa::ModExpoAddr, XSecure_Rsa::ModExt, XSecure_Rsa::ModExtAddr, XSecure_Rsa::RsaState, XSecure_Rsa::SizeInWords, XSECURE_RSA_4096_SIZE_WORDS, XSECURE_RSA_INITIALIZED, XSECURE_RSA_INVALID_PARAM, XSecure_RsaCfgInitialize.
Referenced by XSecure_RsaInitialize.
int XSecure_RsaInitialize(XSecure_Rsa *InstancePtr, u8 *Mod, u8 *ModExt, u8 *ModExpo)
This function initializes a a XSecure_Rsa structure with the default values required for operating the RSA cryptographic engine.
InstancePtr Pointer to the XSecure_Rsa instance Mod A character Pointer which contains the key Modulus of key size ModExt A Pointer to the pre-calculated exponential (R^2 Mod N) value, or NULL if user doesn't have pre-calculated R^2 Mod N value (control will take care of this calculation internally) ModExpo Pointer to the buffer which contains key exponent XST_SUCCESS - If initialization was successfulXSECURE_RSA_INVALID_PARAM - On invalid arguments Modulus, ModExt and ModExpo are part of partition signature when authenticated boot image is generated by bootgen, else the all of them should be extracted from the key
References XSecure_RsaInitialize_64Bit.
Referenced by XSecure_DataAuth, XSecure_RsaCore, XSecure_RsaPrivateDecryptKat, XSecure_RsaPublicEncryptKat, XSecure_RsaPwct, XSecure_SpkAuthentication.
int XSecure_RsaSignVerification_64Bit(const u64 Signature, const u64 Hash, u32 HashLen)
This function verifies the RSA decrypted data located at a 64-bit address provided is either matching with the provided expected hash by taking care of PKCS padding.
Signature Address of the buffer which holds the decrypted RSA signature Hash Address of the buffer which has the hash calculated on the data to be authenticated HashLen Length of Hash used For SHA3 it should be 48 bytes XST_SUCCESS - If decryption was successfulXSECURE_RSA_INVALID_PARAM - On invalid argumentsXST_FAILURE In case of mismatch Signature Address of the buffer which holds the decrypted RSA signature Hash Address of the buffer which has the hash calculated on the data to be authenticated HashLen Length of Hash used For SHA3 it should be 48 bytes XST_SUCCESS - If decryption was successfulXSECURE_RSA_INVALID_PARAM - On invalid argumentsXST_FAILURE - In case of mismatch
References XSECURE_FSBL_SIG_SIZE, XSECURE_HASH_TYPE_SHA3, XSECURE_RSA_BYTE_PAD1, XSECURE_RSA_BYTE_PAD2, XSECURE_RSA_BYTE_PAD3, XSECURE_RSA_BYTE_PAD_LENGTH, XSECURE_RSA_INVALID_PARAM, XSECURE_RSA_T_PAD_LENGTH, XSecure_RsaGetTPadding.
Referenced by XSecure_RsaSignVerification.
int XSecure_RsaSignVerification(const u8 *Signature, const u8 *Hash, u32 HashLen)
This function verifies the RSA decrypted data provided is either matching with the provided expected hash by taking care of PKCS padding.
Signature Pointer to the buffer which holds the decrypted RSA signature Hash Pointer to the buffer which has the hash calculated on the data to be authenticated HashLen Length of Hash used For SHA3 it should be 48 bytes XST_SUCCESS - If decryption was successfulXSECURE_RSA_INVALID_PARAM - On invalid argumentsXST_FAILURE In case of mismatch Signature Pointer to the buffer which holds the decrypted RSA signature Hash Pointer to the buffer which has the hash calculated on the data to be authenticated HashLen Length of Hash used For SHA3 it should be 48 bytes XST_SUCCESS - If decryption was successfulXSECURE_RSA_INVALID_PARAM - On invalid argumentsXST_FAILURE - In case of mismatch
References XSecure_RsaSignVerification_64Bit.
int XSecure_RsaPublicEncrypt_64Bit(XSecure_Rsa *InstancePtr, u64 Input, u32 Size, u64 Result)
This function handles the RSA encryption for data available at 64-bit address with the public key components provided when initializing the RSA cryptographic core with the XSecure_RsaInitialize function.
InstancePtr Pointer to the XSecure_Rsa instance Input Address of the buffer which contains the input data to be encrypted Size Key size in bytes, Input size also should be same as Key size mentioned. Inputs supported are XSECURE_RSA_4096_KEY_SIZE, XSECURE_RSA_2048_KEY_SIZE, or XSECURE_RSA_3072_KEY_SIZE Result Address of buffer where resultant decrypted data to be stored XST_SUCCESS - If encryption was successfulXSECURE_RSA_INVALID_PARAM - On invalid argumentsXSECURE_RSA_STATE_MISMATCH_ERROR - If State mismatch is occurred The Size passed here needs to match the key size used in the XSecure_RsaInitialize function
References XSecure_Rsa::RsaState, XSECURE_RSA_INITIALIZED, XSECURE_RSA_INVALID_PARAM, XSECURE_RSA_SIGN_ENC, XSECURE_RSA_STATE_MISMATCH_ERROR, XSecure_RsaOperation.
Referenced by XSecure_RsaOaepEncrypt, XSecure_RsaPublicEncrypt.
int XSecure_RsaPublicEncrypt(XSecure_Rsa *InstancePtr, u8 *Input, u32 Size, u8 *Result)
This function handles the RSA encryption with the public key components provided when initializing the RSA cryptographic core with the XSecure_RsaInitialize function.
InstancePtr Pointer to the XSecure_Rsa instance Input Pointer to the buffer which contains the input data to be encrypted Size Key size in bytes, Input size also should be same as Key size mentioned. Inputs supported are XSECURE_RSA_4096_KEY_SIZE, XSECURE_RSA_2048_KEY_SIZE, or XSECURE_RSA_3072_KEY_SIZE Result Pointer to the buffer where resultant decrypted data to be stored XST_SUCCESS - If encryption was successfulXSECURE_RSA_INVALID_PARAM - On invalid argumentsXSECURE_RSA_STATE_MISMATCH_ERROR - If State mismatch is occurred The Size passed here needs to match the key size used in the XSecure_RsaInitialize function InstancePtr Pointer to the XSecure_Rsa instance Input Pointer to the buffer which contains the input data to be encrypted Size Key size in bytes, Input size also should be same as Key size mentioned. Inputs supported are XSECURE_RSA_4096_KEY_SIZEXSECURE_RSA_2048_KEY_SIZEXSECURE_RSA_3072_KEY_SIZE Result Pointer to the buffer where resultant decrypted data to be stored XST_SUCCESS - If encryption was successfulXSECURE_RSA_INVALID_PARAM - On invalid argumentsXSECURE_RSA_STATE_MISMATCH_ERROR - If State mismatch is occurred The Size passed here needs to match the key size used in the XSecure_RsaInitialize function
References XSecure_RsaPublicEncrypt_64Bit.
int XSecure_RsaPrivateDecrypt_64Bit(XSecure_Rsa *InstancePtr, u64 Input, u32 Size, u64 Result)
This function handles the RSA decryption for data available at 64-bit address with the private key components provided when initializing the RSA cryptographic core with the XSecure_RsaInitialize function.
InstancePtr Pointer to the XSecure_Rsa instance Input Address of the buffer which contains the input data to be decrypted Size Key size in bytes, Input size also should be same as Key size mentioned. Inputs supported are XSECURE_RSA_4096_KEY_SIZE, XSECURE_RSA_2048_KEY_SIZE, or XSECURE_RSA_3072_KEY_SIZE Result Address of buffer where resultant decrypted data to be stored XST_SUCCESS - If decryption was successfulXSECURE_RSA_INVALID_PARAM - On invalid parametersXSECURE_RSA_DATA_VALUE_ERROR - If input data is greater than modulusXSECURE_RSA_STATE_MISMATCH_ERROR - If State mismatch is occurredXST_FAILURE - On RSA operation failure RSA private key decryption data should be less than modulus. InstancePtr Pointer to the XSecure_Rsa instance Input Address of the buffer which contains the input data to be decrypted Size Key size in bytes, Input size also should be same as Key size mentioned. Inputs supported are XSECURE_RSA_4096_KEY_SIZE, XSECURE_RSA_2048_KEY_SIZE, or XSECURE_RSA_3072_KEY_SIZE Result Address of buffer where resultant decrypted data to be stored XST_SUCCESS - If decryption was successfulXSECURE_RSA_DATA_VALUE_ERROR - If input data is greater than modulusXSECURE_RSA_STATE_MISMATCH_ERROR - If State mismatch is occurredXST_FAILURE - On RSA operation failure The Size passed here needs to match the key size used in the XSecure_RsaInitialize functionRSA private key decryption data should be lesser than modulus.
References XSecure_Rsa::Mod, XSecure_Rsa::ModAddr, XSecure_Rsa::RsaState, XSECURE_RSA_DATA_VALUE_ERROR, XSECURE_RSA_INITIALIZED, XSECURE_RSA_INVALID_PARAM, XSECURE_RSA_SIGN_DEC, XSECURE_RSA_STATE_MISMATCH_ERROR, XSecure_RsaOperation.
Referenced by XSecure_RsaPrivateDecrypt.
int XSecure_RsaPrivateDecrypt(XSecure_Rsa *InstancePtr, u8 *Input, u32 Size, u8 *Result)
This function handles the RSA decryption with the private key components provided when initializing the RSA cryptographic core with the XSecure_RsaInitialize function.
InstancePtr Pointer to the XSecure_Rsa instance Input Pointer to the buffer which contains the input data to be decrypted Size Key size in bytes, Input size also should be same as Key size mentioned. Inputs supported are XSECURE_RSA_4096_KEY_SIZE, XSECURE_RSA_2048_KEY_SIZE, or XSECURE_RSA_3072_KEY_SIZE Result Pointer to the buffer where resultant decrypted data to be stored XST_SUCCESS - If decryption was successfulXSECURE_RSA_INVALID_PARAM - On invalid parametersXSECURE_RSA_DATA_VALUE_ERROR - If input data is greater than modulusXSECURE_RSA_STATE_MISMATCH_ERROR - If State mismatch is occurredXST_FAILURE - On RSA operation failure RSA private key decryption data should be less than modulus. InstancePtr Pointer to the XSecure_Rsa instance Input Pointer to the buffer which contains the input data to be decrypted Size Key size in bytes, Input size also should be same as Key size mentioned. Inputs supported are XSECURE_RSA_4096_KEY_SIZE,XSECURE_RSA_2048_KEY_SIZEXSECURE_RSA_3072_KEY_SIZE Result Pointer to the buffer where resultant decrypted data to be stored XST_SUCCESS - If decryption was successfulXSECURE_RSA_DATA_VALUE_ERROR - If input data is greater than modulusXSECURE_RSA_STATE_MISMATCH_ERROR - If State mismatch is occurredXST_FAILURE - On RSA operation failure The Size passed here needs to match the key size used in the XSecure_RsaInitialize function
References XSecure_RsaPrivateDecrypt_64Bit.