zynqmp/xsecure_utils.h
XSecure_AssertVoid
< All asserts are under XSECDEBUG macro now
XSecure_AssertVoidAlways
XSecure_AssertNonvoid
XSecure_AssertNonvoidAlways
XSECURE_RESET_SET
To set the core into reset.
XSECURE_RESET_UNSET
To take the core out of reset.
XSECURE_WORD_SIZE
WORD size in BYTES.
XSECURE_QWORD_SIZE
QWORD size in BYTES.
XSECURE_WORD_IN_BITS
WORD size in BITS.
XSECURE_WORD_ALIGN_MASK
WORD alignment.
XSecure_MemCpy
Backward compatibility.
XSecure_In32
Reads data from 32-bit address.
XSecure_Out32
Writes data to 32-bit address.
XSecure_SecureOut32
Writes data to 32-bit address and checks for blind writes.
static u32 XSecure_ReadReg(u32 BaseAddress, u16 RegOffset)
Read from the register.
BaseAddress - Contains the base address of the device RegOffset - Contains the offset from the base address of the device The value read from the register
static void XSecure_WriteReg(u32 BaseAddress, u32 RegOffset, u32 RegisterValue)
Write to the register.
BaseAddress - Contains the base address of the device RegOffset - Contains the offset from the base address of the device RegisterValue - Is the value to be written to the register
static u32 XSecure_In64(u64 Addr)
This function reads data from 64-bit address.
Addr is the address
static u8 XSecure_InByte64(u64 Addr)
This function reads a byte from 64-bit address.
Addr is the address
static void XSecure_Out64(u64 Addr, u32 Data)
This function writes data to 64-bit address.
Addr is the address Data is the value to be written
static void XSecure_OutWord64(u64 Addr, u32 Data)
This function writes 32 bit data to 64-bit address.
Addr is the address Data is the value to be written
static void XSecure_OutByte64(u64 Addr, u8 Data)
This function writes a byte to a 64-bit address.
Addr is the address Data is the value to be written
void XSecure_SetReset(u32 BaseAddress, u32 Offset)
This function places the hardware core into the reset.
BaseAddress - Base address of the core Offset - Offset of the reset register
References XSECURE_RESET_SET.
void XSecure_ReleaseReset(u32 BaseAddress, u32 Offset)
This function takes the hardware core out of reset.
BaseAddress - Base address of the core Offset - Offset of the reset register
References XSECURE_RESET_SET, XSECURE_RESET_UNSET.
void XSecure_MemCpy64(u64 DstAddr, u64 SrcAddr, u32 Cnt)
This function copies data from 64 bit address Src to 64 bit address Dst.
DstAddr is the 64 bit destination address SrcAddr is the 64 bit source address Cnt is the number of bytes of data to be copied
References XSECURE_WORD_ALIGN_MASK.
Referenced by XSecure_AesEncryptUpdate, XSecure_KeyUnwrap, XSecure_ShaDmaXfer, XSecure_SlhdsaShake256sChain.