zynqmp/xsecure_utils.c
void XSecure_ReleaseReset(u32 BaseAddress, u32 Offset)
This function takes the hardware core out of reset.
BaseAddress - Base address of the core Offset - Offset of the reset register
References XSECURE_RESET_SET, XSECURE_RESET_UNSET.
void XSecure_SetReset(u32 BaseAddress, u32 Offset)
This function places the hardware core into the reset.
BaseAddress - Base address of the core Offset - Offset of the reset register
References XSECURE_RESET_SET.
void XSecure_MemCpy64(u64 DstAddr, u64 SrcAddr, u32 Cnt)
This function copies data from 64 bit address Src to 64 bit address Dst.
DstAddr is the 64 bit destination address SrcAddr is the 64 bit source address Cnt is the number of bytes of data to be copied
References XSECURE_WORD_ALIGN_MASK.
Referenced by XSecure_AesEncryptUpdate, XSecure_KeyUnwrap, XSecure_ShaDmaXfer, XSecure_SlhdsaShake256sChain.