xilfpga.h
typedef struct XFpgatag XFpga
Structure to the XFpga instance.
u32 XFpga_Initialize(XFpga *InstancePtr)
This API, when called, initializes the XFPGA interface with default settings.
InstancePtr Pointer to the XFpga structure. Returns Status XFPGA_SUCCESS on successError code on failure
References XFpgatag::XFpga_WriteToPl, XFpgatag::XFpga_GetConfigData, XFpgatag::XFpga_GetConfigReg, XFpgatag::XFpga_GetInterfaceStatus.
Referenced by main.
u32 XFpga_ValidateImage(XFpga *InstancePtr, UINTPTR BitstreamImageAddr, UINTPTR KeyAddr, u32 Size, u32 Flags)
This function is used to validate the bitstream image.
InstancePtr Pointer to the XFpga structure BitstreamImageAddr Linear memory bitstream image base address KeyAddr Aes key address which is used for decryption. Size Used to store size of bitstream image. Flags Flags are used to specify the type of bitstream file. BIT(0) - Bitstream type 0 - Full bitstream1 - Partial bitstream BIT(1) - Authentication using DDR 1 - Enable0 - Disable BIT(2) - Authentication using OCM 1 - Enable0 - Disable BIT(3) - User-key Encryption 1 - Enable0 - Disable BIT(4) - Device-key Encryption 1 - Enable0 - Disable Codes as mentioned in xilfpga.h
References XFpgatag::XFpga_ValidateBitstream, XFpgatag::WriteInfo, XFpga_Write::BitstreamAddr, XFpga_Write::Flags, XFpga_Write::KeyAddr, XFpga_Write::Size.
Referenced by XFpga_BitStream_Load.
u32 XFpga_BitStream_Load(XFpga *InstancePtr, UINTPTR BitstreamImageAddr, UINTPTR KeyAddr, u32 Size, u32 Flags)
The API is used to load the bitstream file into the PL region.
It supports AMD Vivado™ Design Suite generated bitstream (*.bit, *.bin) and Bootgen-generated bitstream (*.bin) loading, Passing valid bitstream size(Size) information is mandatory for Vivado Design Suite generated bitstream, For Bootgen-generated bitstreams bitstream size is taken from the bitstream header. InstancePtr Pointer to the XFpga structure. BitstreamImageAddr Linear memory bitstream image base address KeyAddr AES key address which is used for decryption. Size Used to store size of bitstream image. Flags Flags are used to specify the type of bitstream file. BIT(0) - Bitstream type 0 - Full bitstream1 - Partial bitstream BIT(1) - Authentication using DDR 1 - Enable0 - Disable BIT(2) - Authentication using OCM 1 - Enable0 - Disable BIT(3) - User-key Encryption 1 - Enable0 - Disable BIT(4) - Device-key Encryption 1 - Enable0 - Disable XFPGA_SUCCESS on successError code on failure.XFPGA_VALIDATE_ERROR.XFPGA_PRE_CONFIG_ERROR.XFPGA_WRITE_BITSTREAM_ERROR.XFPGA_POST_CONFIG_ERROR.
References XFpga_ValidateImage, XFpgatag::WriteInfo, XFpga_Write::BitstreamAddr, XFpga_Write::Flags, XFpga_Write::KeyAddr, XFpga_Write::Size, XFpga_PL_Preconfig, XFpga_Write_Pl, XFpga_PL_PostConfig.
Referenced by main.
u32 XFpga_PL_Preconfig(XFpga *InstancePtr)
This function prepares the FPGA to receive configuration data.
InstancePtr is the pointer to the XFpga. Codes as mentioned in xilfpga.h
References XFpgatag::XFpga_PreConfig.
Referenced by XFpga_BitStream_Load.
u32 XFpga_Write_Pl(XFpga *InstancePtr, UINTPTR BitstreamImageAddr, UINTPTR KeyAddr, u32 Size, u32 Flags)
This function writes the count bytes of configuration data into the PL.
InstancePtr Pointer to the XFpga structure BitstreamImageAddr Linear memory bitstream image base address KeyAddr Aes key address which is used for decryption. Size Used to store size of bitstream image. Flags Flags are used to specify the type of bitstream file. BIT(0) - Bitstream type 0 - Full bitstream1 - Partial bitstream BIT(1) - Authentication using DDR 1 - Enable0 - Disable BIT(2) - Authentication using OCM 1 - Enable0 - Disable BIT(3) - User-key Encryption 1 - Enable0 - Disable BIT(4) - Device-key Encryption 1 - Enable0 - Disable Codes as mentioned in xilfpga.h
References XFpgatag::XFpga_WriteToPl, XFpgatag::WriteInfo, XFpga_Write::BitstreamAddr, XFpga_Write::Flags, XFpga_Write::KeyAddr, XFpga_Write::Size.
Referenced by XFpga_BitStream_Load.
u32 XFpga_PL_PostConfig(XFpga *InstancePtr)
This function sets the FPGA to the operating state after writing.
InstancePtr Pointer to the XFpga structure Codes as mentioned in xilfpga.h
References XFpgatag::XFpga_PostConfig.
Referenced by XFpga_BitStream_Load.
u32 XFpga_GetPlConfigData(XFpga *InstancePtr, UINTPTR ReadbackAddr, u32 NumFrames)
This function provides functionality to read back the PL configuration data.
InstancePtr Pointer to the XFpga structure ReadbackAddr Address which is used to store the PL readback data. NumFrames The number of FPGA configuration frames to read. XFPGA_SUCCESS, if successfulXFPGA_FAILURE, if unsuccessfulXFPGA_OPS_NOT_IMPLEMENTED, if implementation not exists. This API is not supported for the Versal platform.
References XFpgatag::XFpga_GetConfigData, XFpgatag::ReadInfo.
u32 XFpga_GetPlConfigReg(XFpga *InstancePtr, UINTPTR ReadbackAddr, u32 ConfigRegAddr)
This function provides PL specific configuration register values.
InstancePtr Pointer to the XFpga structure ReadbackAddr Address which is used to store the PL Configuration register data. ConfigRegAddr Configuration register address as mentioned in the UG570. XFPGA_SUCCESS if, successfulXFPGA_FAILURE if, unsuccessfulXFPGA_OPS_NOT_IMPLEMENTED, if implementation not exists. This API is not supported for the Versal platform.
References XFpgatag::XFpga_GetConfigReg, XFpgatag::ReadInfo.
u32 XFpga_InterfaceStatus(XFpga *InstancePtr)
This function provides the status of the PL programming interface.
InstancePtr Pointer to the XFpga structure Status of the PL programming interface This API is not supported for the Versal platform.
References XFpgatag::XFpga_GetInterfaceStatus.