
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2020 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT

*
* Description: Configurations for Standalone BSP
*
*******************************************************************/

#ifndef BSPCONFIG_H  /* prevent circular inclusions */
#define BSPCONFIG_H  /* by using protection macros */

#define MICROBLAZE_PVR_NONE

#endif /*end of __BSPCONFIG_H_*/
