xv_gamma_lut.h
XVGAMMA_LUT_IRQ_DONE_MASK
Interrupt Done mask (bit 0)
Referenced by XVGammaLut_InterruptHandler.
XVGAMMA_LUT_IRQ_READY_MASK
Interrupt Ready mask (bit 1)
Referenced by XVGammaLut_InterruptHandler.
XV_gamma_lut_WriteReg
Write to gamma lut register (bare-metal)
Referenced by XV_gamma_lut_DisableAutoRestart, XV_gamma_lut_EnableAutoRestart, XV_gamma_lut_InterruptClear, XV_gamma_lut_InterruptDisable, XV_gamma_lut_InterruptEnable, XV_gamma_lut_InterruptGlobalDisable, XV_gamma_lut_InterruptGlobalEnable, XV_gamma_lut_Set_HwReg_height, XV_gamma_lut_Set_HwReg_video_format, XV_gamma_lut_Set_HwReg_width, XV_gamma_lut_Start.
XV_gamma_lut_ReadReg
Read from gamma lut register (bare-metal)
Referenced by XV_gamma_lut_Get_HwReg_height, XV_gamma_lut_Get_HwReg_video_format, XV_gamma_lut_Get_HwReg_width, XV_gamma_lut_InterruptDisable, XV_gamma_lut_InterruptEnable, XV_gamma_lut_InterruptGetEnabled, XV_gamma_lut_InterruptGetStatus, XV_gamma_lut_IsDone, XV_gamma_lut_IsIdle, XV_gamma_lut_IsReady, XV_gamma_lut_Start.
XVGAMMA_LUT_HandlerType
Handler for ap_done interrupt.
typedef void(* XVGamma_Lut_Callback)(void *InstancePtr))(void *InstancePtr)
int XV_gamma_lut_Initialize(XV_gamma_lut *InstancePtr, UINTPTR BaseAddress)
Initializes the Gamma LUT driver instance (SDT)
This function initializes a Gamma LUT driver instance by looking up the configuration based on the base address and calling the configuration initialization function. This version is used with System Device Tree (SDT) configurations. InstancePtr is a pointer to the XV_gamma_lut instance. BaseAddress is the base address to initialize. XST_SUCCESS on success, XST_DEVICE_NOT_FOUND if device not found None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::IsReady, XV_gamma_lut_CfgInitialize, XV_gamma_lut_LookupConfig.
XV_gamma_lut_Config* XV_gamma_lut_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on base address (SDT)
This function searches the configuration table for a device matching the provided base address and returns a pointer to its configuration structure. This version is used with System Device Tree (SDT) configurations. BaseAddress is the base address to search for. Pointer to the XV_gamma_lut_Config structure if found, NULL otherwise None
References XV_gamma_lut_Config::Name.
Referenced by driverInit, XV_gamma_lut_Initialize.
int XV_gamma_lut_CfgInitialize(XV_gamma_lut *InstancePtr, XV_gamma_lut_Config *ConfigPtr, UINTPTR EffectiveAddr)
Initializes the Gamma LUT core instance.
This function initializes the Gamma LUT core by setting up the instance configuration structure and marking the instance as ready. InstancePtr is a pointer to the XV_gamma_lut instance. ConfigPtr is a pointer to the configuration structure. EffectiveAddr is the base address of the device. XST_SUCCESS on successful initialization None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_gamma_lut::IsReady.
Referenced by driverInit, XV_gamma_lut_Initialize.
void XV_gamma_lut_Start(XV_gamma_lut *InstancePtr)
Starts the Gamma LUT core.
This function starts the Gamma LUT core by setting the AP_START bit in the control register while preserving the auto-restart setting. InstancePtr is a pointer to the XV_gamma_lut instance. None None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_gamma_lut::IsReady, XV_GAMMA_LUT_CTRL_ADDR_AP_CTRL, XV_gamma_lut_ReadReg, XV_gamma_lut_WriteReg.
Referenced by videoIpConfig.
u32 XV_gamma_lut_IsDone(XV_gamma_lut *InstancePtr)
Checks if the Gamma LUT core has finished processing.
This function checks the AP_DONE bit in the control register to determine if the core has finished processing the current frame. InstancePtr is a pointer to the XV_gamma_lut instance. 1 if done, 0 otherwise None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_gamma_lut::IsReady, XV_GAMMA_LUT_CTRL_ADDR_AP_CTRL, XV_gamma_lut_ReadReg.
u32 XV_gamma_lut_IsIdle(XV_gamma_lut *InstancePtr)
Checks if the Gamma LUT core is idle.
This function checks the AP_IDLE bit in the control register to determine if the core is idle and not processing any data. InstancePtr is a pointer to the XV_gamma_lut instance. 1 if idle, 0 otherwise None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_gamma_lut::IsReady, XV_GAMMA_LUT_CTRL_ADDR_AP_CTRL, XV_gamma_lut_ReadReg.
u32 XV_gamma_lut_IsReady(XV_gamma_lut *InstancePtr)
Checks if the Gamma LUT core is ready for next input.
This function checks if the core is ready to accept new input by verifying the AP_START bit is not set. InstancePtr is a pointer to the XV_gamma_lut instance. 1 if ready, 0 otherwise None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_gamma_lut::IsReady, XV_GAMMA_LUT_CTRL_ADDR_AP_CTRL, XV_gamma_lut_ReadReg.
void XV_gamma_lut_EnableAutoRestart(XV_gamma_lut *InstancePtr)
Enables auto-restart mode.
This function enables the auto-restart feature, which allows the core to automatically restart processing after completion. InstancePtr is a pointer to the XV_gamma_lut instance. None None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_gamma_lut::IsReady, XV_GAMMA_LUT_CTRL_ADDR_AP_CTRL, XV_gamma_lut_WriteReg.
Referenced by videoIpConfig.
void XV_gamma_lut_DisableAutoRestart(XV_gamma_lut *InstancePtr)
Disables auto-restart mode.
This function disables the auto-restart feature, requiring manual restart after each frame processing completion. InstancePtr is a pointer to the XV_gamma_lut instance. None None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_gamma_lut::IsReady, XV_GAMMA_LUT_CTRL_ADDR_AP_CTRL, XV_gamma_lut_WriteReg.
void XV_gamma_lut_Set_HwReg_width(XV_gamma_lut *InstancePtr, u32 Data)
Sets the width register value.
This function writes the width value to the hardware width register. InstancePtr is a pointer to the XV_gamma_lut instance. Data is the width value to set. None None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_gamma_lut::IsReady, XV_GAMMA_LUT_CTRL_ADDR_HWREG_WIDTH_DATA, XV_gamma_lut_WriteReg.
Referenced by videoIpConfig.
u32 XV_gamma_lut_Get_HwReg_width(XV_gamma_lut *InstancePtr)
Gets the width register value.
This function reads and returns the width value from the hardware width register. InstancePtr is a pointer to the XV_gamma_lut instance. The width value None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_gamma_lut::IsReady, XV_GAMMA_LUT_CTRL_ADDR_HWREG_WIDTH_DATA, XV_gamma_lut_ReadReg.
void XV_gamma_lut_Set_HwReg_height(XV_gamma_lut *InstancePtr, u32 Data)
Sets the height register value.
This function writes the height value to the hardware height register. InstancePtr is a pointer to the XV_gamma_lut instance. Data is the height value to set. None None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_gamma_lut::IsReady, XV_GAMMA_LUT_CTRL_ADDR_HWREG_HEIGHT_DATA, XV_gamma_lut_WriteReg.
Referenced by videoIpConfig.
u32 XV_gamma_lut_Get_HwReg_height(XV_gamma_lut *InstancePtr)
Gets the height register value.
This function reads and returns the height value from the hardware height register. InstancePtr is a pointer to the XV_gamma_lut instance. The height value None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_gamma_lut::IsReady, XV_GAMMA_LUT_CTRL_ADDR_HWREG_HEIGHT_DATA, XV_gamma_lut_ReadReg.
void XV_gamma_lut_Set_HwReg_video_format(XV_gamma_lut *InstancePtr, u32 Data)
Sets the video format register value.
This function writes the video format value to the hardware video format register. InstancePtr is a pointer to the XV_gamma_lut instance. Data is the video format value to set. None None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_gamma_lut::IsReady, XV_GAMMA_LUT_CTRL_ADDR_HWREG_VIDEO_FORMAT_DATA, XV_gamma_lut_WriteReg.
Referenced by videoIpConfig.
u32 XV_gamma_lut_Get_HwReg_video_format(XV_gamma_lut *InstancePtr)
Gets the video format register value.
This function reads and returns the video format value from the hardware video format register. InstancePtr is a pointer to the XV_gamma_lut instance. The video format value None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_gamma_lut::IsReady, XV_GAMMA_LUT_CTRL_ADDR_HWREG_VIDEO_FORMAT_DATA, XV_gamma_lut_ReadReg.
u32 XV_gamma_lut_Get_HwReg_gamma_lut_0_BaseAddress(XV_gamma_lut *InstancePtr)
Gets the base address of gamma LUT 0.
This function returns the base address of the gamma LUT 0 memory region. InstancePtr is a pointer to the XV_gamma_lut instance. The base address of gamma LUT 0 None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_gamma_lut::IsReady, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_0_BASE.
u32 XV_gamma_lut_Get_HwReg_gamma_lut_0_HighAddress(XV_gamma_lut *InstancePtr)
Gets the high address of gamma LUT 0.
This function returns the high address of the gamma LUT 0 memory region. InstancePtr is a pointer to the XV_gamma_lut instance. The high address of gamma LUT 0 None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_gamma_lut::IsReady, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_0_HIGH.
u32 XV_gamma_lut_Get_HwReg_gamma_lut_0_TotalBytes(XV_gamma_lut *InstancePtr)
Gets the total bytes of gamma LUT 0.
This function calculates and returns the total size in bytes of the gamma LUT 0 memory region. InstancePtr is a pointer to the XV_gamma_lut instance. The total bytes of gamma LUT 0 None
References XV_gamma_lut::IsReady, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_0_BASE, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_0_HIGH.
u32 XV_gamma_lut_Get_HwReg_gamma_lut_0_BitWidth(XV_gamma_lut *InstancePtr)
Gets the bit width of gamma LUT 0 entries.
This function returns the bit width of each entry in gamma LUT 0. InstancePtr is a pointer to the XV_gamma_lut instance. The bit width of gamma LUT 0 entries None
References XV_gamma_lut::IsReady, XV_GAMMA_LUT_CTRL_WIDTH_HWREG_GAMMA_LUT_0.
u32 XV_gamma_lut_Get_HwReg_gamma_lut_0_Depth(XV_gamma_lut *InstancePtr)
Gets the depth of gamma LUT 0.
This function returns the depth (number of entries) of gamma LUT 0. InstancePtr is a pointer to the XV_gamma_lut instance. The depth of gamma LUT 0 None
References XV_gamma_lut::IsReady, XV_GAMMA_LUT_CTRL_DEPTH_HWREG_GAMMA_LUT_0.
u32 XV_gamma_lut_Write_HwReg_gamma_lut_0_Words(XV_gamma_lut *InstancePtr, int offset, int *data, int length)
Writes words to gamma LUT 0.
This function writes multiple 32-bit words to gamma LUT 0 starting at the specified offset. InstancePtr is a pointer to the XV_gamma_lut instance. offset is the word offset to start writing. data is a pointer to the data array to write. length is the number of words to write. The number of words written, or 0 if offset+length exceeds bounds None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_0_BASE, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_0_HIGH.
u32 XV_gamma_lut_Read_HwReg_gamma_lut_0_Words(XV_gamma_lut *InstancePtr, int offset, int *data, int length)
Reads words from gamma LUT 0.
This function reads multiple 32-bit words from gamma LUT 0 starting at the specified offset. InstancePtr is a pointer to the XV_gamma_lut instance. offset is the word offset to start reading. data is a pointer to the data array to store read values. length is the number of words to read. The number of words read, or 0 if offset+length exceeds bounds None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_0_BASE, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_0_HIGH.
u32 XV_gamma_lut_Write_HwReg_gamma_lut_0_Bytes(XV_gamma_lut *InstancePtr, int offset, char *data, int length)
Writes bytes to gamma LUT 0.
This function writes multiple bytes to gamma LUT 0 starting at the specified offset. InstancePtr is a pointer to the XV_gamma_lut instance. offset is the byte offset to start writing. data is a pointer to the data array to write. length is the number of bytes to write. The number of bytes written, or 0 if offset+length exceeds bounds None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_0_BASE, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_0_HIGH.
u32 XV_gamma_lut_Read_HwReg_gamma_lut_0_Bytes(XV_gamma_lut *InstancePtr, int offset, char *data, int length)
Reads bytes from gamma LUT 0.
This function reads multiple bytes from gamma LUT 0 starting at the specified offset. InstancePtr is a pointer to the XV_gamma_lut instance. offset is the byte offset to start reading. data is a pointer to the data array to store read values. length is the number of bytes to read. The number of bytes read, or 0 if offset+length exceeds bounds None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_0_BASE, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_0_HIGH.
u32 XV_gamma_lut_Get_HwReg_gamma_lut_1_BaseAddress(XV_gamma_lut *InstancePtr)
Gets the base address of gamma LUT 1.
This function returns the base address of the gamma LUT 1 memory region. InstancePtr is a pointer to the XV_gamma_lut instance. The base address of gamma LUT 1 None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_gamma_lut::IsReady, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_1_BASE.
u32 XV_gamma_lut_Get_HwReg_gamma_lut_1_HighAddress(XV_gamma_lut *InstancePtr)
Gets the high address of gamma LUT 1.
This function returns the high address of the gamma LUT 1 memory region. InstancePtr is a pointer to the XV_gamma_lut instance. The high address of gamma LUT 1 None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_gamma_lut::IsReady, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_1_HIGH.
u32 XV_gamma_lut_Get_HwReg_gamma_lut_1_TotalBytes(XV_gamma_lut *InstancePtr)
Gets the total bytes of gamma LUT 1.
This function calculates and returns the total size in bytes of the gamma LUT 1 memory region. InstancePtr is a pointer to the XV_gamma_lut instance. The total bytes of gamma LUT 1 None
References XV_gamma_lut::IsReady, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_1_BASE, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_1_HIGH.
u32 XV_gamma_lut_Get_HwReg_gamma_lut_1_BitWidth(XV_gamma_lut *InstancePtr)
Gets the bit width of gamma LUT 1 entries.
This function returns the bit width of each entry in gamma LUT 1. InstancePtr is a pointer to the XV_gamma_lut instance. The bit width of gamma LUT 1 entries None
References XV_gamma_lut::IsReady, XV_GAMMA_LUT_CTRL_WIDTH_HWREG_GAMMA_LUT_1.
u32 XV_gamma_lut_Get_HwReg_gamma_lut_1_Depth(XV_gamma_lut *InstancePtr)
Gets the depth of gamma LUT 1.
This function returns the depth (number of entries) of gamma LUT 1. InstancePtr is a pointer to the XV_gamma_lut instance. The depth of gamma LUT 1 None
References XV_gamma_lut::IsReady, XV_GAMMA_LUT_CTRL_DEPTH_HWREG_GAMMA_LUT_1.
u32 XV_gamma_lut_Write_HwReg_gamma_lut_1_Words(XV_gamma_lut *InstancePtr, int offset, int *data, int length)
Writes words to gamma LUT 1.
This function writes multiple 32-bit words to gamma LUT 1 starting at the specified offset. InstancePtr is a pointer to the XV_gamma_lut instance. offset is the word offset to start writing. data is a pointer to the data array to write. length is the number of words to write. The number of words written, or 0 if offset+length exceeds bounds None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_1_BASE, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_1_HIGH.
u32 XV_gamma_lut_Read_HwReg_gamma_lut_1_Words(XV_gamma_lut *InstancePtr, int offset, int *data, int length)
Reads words from gamma LUT 1.
This function reads multiple 32-bit words from gamma LUT 1 starting at the specified offset. InstancePtr is a pointer to the XV_gamma_lut instance. offset is the word offset to start reading. data is a pointer to the data array to store read values. length is the number of words to read. The number of words read, or 0 if offset+length exceeds bounds None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_1_BASE, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_1_HIGH.
u32 XV_gamma_lut_Write_HwReg_gamma_lut_1_Bytes(XV_gamma_lut *InstancePtr, int offset, char *data, int length)
Writes bytes to gamma LUT 1.
This function writes multiple bytes to gamma LUT 1 starting at the specified offset. InstancePtr is a pointer to the XV_gamma_lut instance. offset is the byte offset to start writing. data is a pointer to the data array to write. length is the number of bytes to write. The number of bytes written, or 0 if offset+length exceeds bounds None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_1_BASE, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_1_HIGH.
u32 XV_gamma_lut_Read_HwReg_gamma_lut_1_Bytes(XV_gamma_lut *InstancePtr, int offset, char *data, int length)
Reads bytes from gamma LUT 1.
This function reads multiple bytes from gamma LUT 1 starting at the specified offset. InstancePtr is a pointer to the XV_gamma_lut instance. offset is the byte offset to start reading. data is a pointer to the data array to store read values. length is the number of bytes to read. The number of bytes read, or 0 if offset+length exceeds bounds None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_1_BASE, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_1_HIGH.
u32 XV_gamma_lut_Get_HwReg_gamma_lut_2_BaseAddress(XV_gamma_lut *InstancePtr)
Gets the base address of gamma LUT 2.
This function returns the base address of the gamma LUT 2 memory region. InstancePtr is a pointer to the XV_gamma_lut instance. The base address of gamma LUT 2 None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_gamma_lut::IsReady, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_2_BASE.
u32 XV_gamma_lut_Get_HwReg_gamma_lut_2_HighAddress(XV_gamma_lut *InstancePtr)
Gets the high address of gamma LUT 2.
This function returns the high address of the gamma LUT 2 memory region. InstancePtr is a pointer to the XV_gamma_lut instance. The high address of gamma LUT 2 None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_gamma_lut::IsReady, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_2_HIGH.
u32 XV_gamma_lut_Get_HwReg_gamma_lut_2_TotalBytes(XV_gamma_lut *InstancePtr)
Gets the total bytes of gamma LUT 2.
This function calculates and returns the total size in bytes of the gamma LUT 2 memory region. InstancePtr is a pointer to the XV_gamma_lut instance. The total bytes of gamma LUT 2 None
References XV_gamma_lut::IsReady, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_2_BASE, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_2_HIGH.
u32 XV_gamma_lut_Get_HwReg_gamma_lut_2_BitWidth(XV_gamma_lut *InstancePtr)
Gets the bit width of gamma LUT 2 entries.
This function returns the bit width of each entry in gamma LUT 2. InstancePtr is a pointer to the XV_gamma_lut instance. The bit width of gamma LUT 2 entries None
References XV_gamma_lut::IsReady, XV_GAMMA_LUT_CTRL_WIDTH_HWREG_GAMMA_LUT_2.
u32 XV_gamma_lut_Get_HwReg_gamma_lut_2_Depth(XV_gamma_lut *InstancePtr)
Gets the depth of gamma LUT 2.
This function returns the depth (number of entries) of gamma LUT 2. InstancePtr is a pointer to the XV_gamma_lut instance. The depth of gamma LUT 2 None
References XV_gamma_lut::IsReady, XV_GAMMA_LUT_CTRL_DEPTH_HWREG_GAMMA_LUT_2.
u32 XV_gamma_lut_Write_HwReg_gamma_lut_2_Words(XV_gamma_lut *InstancePtr, int offset, int *data, int length)
Writes words to gamma LUT 2.
This function writes multiple 32-bit words to gamma LUT 2 starting at the specified offset. InstancePtr is a pointer to the XV_gamma_lut instance. offset is the word offset to start writing. data is a pointer to the data array to write. length is the number of words to write. The number of words written, or 0 if offset+length exceeds bounds None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_2_BASE, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_2_HIGH.
u32 XV_gamma_lut_Read_HwReg_gamma_lut_2_Words(XV_gamma_lut *InstancePtr, int offset, int *data, int length)
Reads words from gamma LUT 2.
This function reads multiple 32-bit words from gamma LUT 2 starting at the specified offset. InstancePtr is a pointer to the XV_gamma_lut instance. offset is the word offset to start reading. data is a pointer to the data array to store read values. length is the number of words to read. The number of words read, or 0 if offset+length exceeds bounds None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_2_BASE, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_2_HIGH.
u32 XV_gamma_lut_Write_HwReg_gamma_lut_2_Bytes(XV_gamma_lut *InstancePtr, int offset, char *data, int length)
Writes bytes to gamma LUT 2.
This function writes multiple bytes to gamma LUT 2 starting at the specified offset. InstancePtr is a pointer to the XV_gamma_lut instance. offset is the byte offset to start writing. data is a pointer to the data array to write. length is the number of bytes to write. The number of bytes written, or 0 if offset+length exceeds bounds None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_2_BASE, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_2_HIGH.
u32 XV_gamma_lut_Read_HwReg_gamma_lut_2_Bytes(XV_gamma_lut *InstancePtr, int offset, char *data, int length)
Reads bytes from gamma LUT 2.
This function reads multiple bytes from gamma LUT 2 starting at the specified offset. InstancePtr is a pointer to the XV_gamma_lut instance. offset is the byte offset to start reading. data is a pointer to the data array to store read values. length is the number of bytes to read. The number of bytes read, or 0 if offset+length exceeds bounds None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_2_BASE, XV_GAMMA_LUT_CTRL_ADDR_HWREG_GAMMA_LUT_2_HIGH.
void XV_gamma_lut_InterruptGlobalEnable(XV_gamma_lut *InstancePtr)
Enables global interrupts.
This function enables the global interrupt output by setting the GIE (Global Interrupt Enable) bit. InstancePtr is a pointer to the XV_gamma_lut instance. None None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_gamma_lut::IsReady, XV_GAMMA_LUT_CTRL_ADDR_GIE, XV_gamma_lut_WriteReg.
void XV_gamma_lut_InterruptGlobalDisable(XV_gamma_lut *InstancePtr)
Disables global interrupts.
This function disables the global interrupt output by clearing the GIE (Global Interrupt Enable) bit. InstancePtr is a pointer to the XV_gamma_lut instance. None None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_gamma_lut::IsReady, XV_GAMMA_LUT_CTRL_ADDR_GIE, XV_gamma_lut_WriteReg.
void XV_gamma_lut_InterruptEnable(XV_gamma_lut *InstancePtr, u32 Mask)
Enables specific interrupts.
This function enables individual interrupts specified by the Mask parameter in the Interrupt Enable Register (IER). InstancePtr is a pointer to the XV_gamma_lut instance. Mask is the bit mask of interrupts to enable. None None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_gamma_lut::IsReady, XV_GAMMA_LUT_CTRL_ADDR_IER, XV_gamma_lut_ReadReg, XV_gamma_lut_WriteReg.
void XV_gamma_lut_InterruptDisable(XV_gamma_lut *InstancePtr, u32 Mask)
Disables specific interrupts.
This function disables individual interrupts specified by the Mask parameter in the Interrupt Enable Register (IER). InstancePtr is a pointer to the XV_gamma_lut instance. Mask is the bit mask of interrupts to disable. None None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_gamma_lut::IsReady, XV_GAMMA_LUT_CTRL_ADDR_IER, XV_gamma_lut_ReadReg, XV_gamma_lut_WriteReg.
void XV_gamma_lut_InterruptClear(XV_gamma_lut *InstancePtr, u32 Mask)
Clears pending interrupts.
This function clears pending interrupts specified by the Mask parameter in the Interrupt Status Register (ISR). InstancePtr is a pointer to the XV_gamma_lut instance. Mask is the bit mask of interrupts to clear. None None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_gamma_lut::IsReady, XV_GAMMA_LUT_CTRL_ADDR_ISR, XV_gamma_lut_WriteReg.
Referenced by XVGammaLut_InterruptHandler.
u32 XV_gamma_lut_InterruptGetEnabled(XV_gamma_lut *InstancePtr)
Gets the enabled interrupt mask.
This function reads and returns the Interrupt Enable Register (IER) value, indicating which interrupts are currently enabled. InstancePtr is a pointer to the XV_gamma_lut instance. The enabled interrupt mask None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_gamma_lut::IsReady, XV_GAMMA_LUT_CTRL_ADDR_IER, XV_gamma_lut_ReadReg.
u32 XV_gamma_lut_InterruptGetStatus(XV_gamma_lut *InstancePtr)
Gets the interrupt status.
This function reads and returns the Interrupt Status Register (ISR) value, indicating which interrupts are currently pending. InstancePtr is a pointer to the XV_gamma_lut instance. The interrupt status mask None
References XV_gamma_lut_Config::BaseAddress, XV_gamma_lut::Config, XV_gamma_lut::IsReady, XV_GAMMA_LUT_CTRL_ADDR_ISR, XV_gamma_lut_ReadReg.
Referenced by XVGammaLut_InterruptHandler.
void XVGammaLut_SetCallback(XV_gamma_lut *InstancePtr, u32 HandlerType, void *CallbackFunc, void *CallbackRef)
Installs an asynchronous callback function for the given handler type.
This function installs an asynchronous callback function for the given HandlerType: HandlerType Callback Function Type ----------------------- -------------------------------------------------- (XVGAMMA_LUT_HANDLER_DONE) DoneCallback (XVGAMMA_LUT_HANDLER_READY) ReadyCallback InstancePtr is a pointer to the GammaLut IP instance. HandlerType specifies the type of handler (DONE or READY). CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. None Invoking this function for a handler that already has been installed replaces it with the new handler.
References XVGAMMA_LUT_HANDLER_DONE, XV_gamma_lut::FrameDoneCallback, XV_gamma_lut::CallbackDoneRef, XVGAMMA_LUT_HANDLER_READY, XV_gamma_lut::FrameReadyCallback, XV_gamma_lut::CallbackReadyRef.
void XVGammaLut_InterruptHandler(XV_gamma_lut *InstancePtr)
Interrupt handler for the Gamma LUT core driver.
This function is the interrupt handler for the Gamma Lut core driver. This handler clears the pending interrupt and determined if the source is frame done signal. If yes, starts the next frame processing and calls the registered callback function.The application is responsible for connecting this function to the interrupt system. Application beyond this driver is also responsible for providing callbacks to handle interrupts and installing the callbacks using XVGammaLut_SetCallback() during initialization phase. InstancePtr is a pointer to the core instance that just interrupted. None None
References XV_gamma_lut::IsReady, XV_gamma_lut_InterruptGetStatus, XVGAMMA_LUT_IRQ_DONE_MASK, XV_gamma_lut_InterruptClear, XV_gamma_lut::FrameDoneCallback, XV_gamma_lut::CallbackDoneRef, XVGAMMA_LUT_IRQ_READY_MASK, XV_gamma_lut::FrameReadyCallback, XV_gamma_lut::CallbackReadyRef.