axivdma
XAXIVDMA_BD_MINIMUM_ALIGNMENT
Minimum byte alignment requirement for descriptors.
Referenced by XAxiVdma_SetBdAddrs.
XAXIVDMA_BD_MINIMUM_ALIGNMENT_WD
Minimum word alignment requirement for descriptors.
XAXIVDMA_MAX_FRAMESTORE
Maximum number of the frame store.
Maximum # of the frame store
Referenced by XAxiVdma_ChannelSetBufferAddr.
XAXIVDMA_MAX_FRAMESTORE_64
Maximum # of the frame store for 64 bit.
Referenced by XAxiVdma_ChannelSetBufferAddr.
XAXIVDMA_MAX_VSIZE
XAXIVDMA_MAX_HSIZE
XAXIVDMA_MAX_STRIDE
XAXIVDMA_FRMDLY_MAX
Maximum frame delay.
Referenced by XAxiVdma_ChannelConfig.
XAXIVDMA_TX_OFFSET
TX channel registers base.
Referenced by XAxiVdma_CfgInitialize, XAxiVdma_Selftest.
XAXIVDMA_RX_OFFSET
RX channel registers base.
Referenced by XAxiVdma_CfgInitialize, XAxiVdma_Selftest.
XAXIVDMA_PARKPTR_OFFSET
Park Pointer Register.
Referenced by XAxiVdma_ChannelConfig, XAxiVdma_CurrFrameStore, XAxiVdma_StartParking.
XAXIVDMA_VERSION_OFFSET
Version register.
Referenced by XAxiVdma_GetVersion.
XAXIVDMA_CR_OFFSET
Channel control.
Referenced by XAxiVdma_ChannelConfig, XAxiVdma_ChannelDisableIntr, XAxiVdma_ChannelEnableIntr, XAxiVdma_ChannelGetEnabledIntr, XAxiVdma_ChannelGetFrmCnt, XAxiVdma_ChannelRegisterDump, XAxiVdma_ChannelReset, XAxiVdma_ChannelResetNotDone, XAxiVdma_ChannelSetFrmCnt, XAxiVdma_ChannelStart, XAxiVdma_ChannelStartFrmCntEnable, XAxiVdma_ChannelStartParking, XAxiVdma_ChannelStop, XAxiVdma_ChannelStopParking, XAxiVdma_FsyncSrcSelect, XAxiVdma_GenLockSourceSelect.
XAXIVDMA_SR_OFFSET
Status.
Referenced by XAxiVdma_ChannelGetPendingIntr, XAxiVdma_ChannelGetStatus, XAxiVdma_ChannelIntrClear, XAxiVdma_ChannelIsBusy, XAxiVdma_ChannelRegisterDump.
XAXIVDMA_CDESC_OFFSET
Current descriptor pointer.
Referenced by XAxiVdma_ChannelRegisterDump, XAxiVdma_ChannelStart.
XAXIVDMA_TDESC_OFFSET
Tail descriptor pointer.
Referenced by XAxiVdma_ChannelRegisterDump, XAxiVdma_ChannelStart.
XAXIVDMA_HI_FRMBUF_OFFSET
32 FrameBuf Sel
XAXIVDMA_FRMSTORE_OFFSET
Frame Store.
Referenced by XAxiVdma_GetFrmStore, XAxiVdma_SetFrmStore.
XAXIVDMA_BUFTHRES_OFFSET
Line Buffer Thres.
Referenced by XAxiVdma_CfgInitialize, XAxiVdma_SetLineBufThreshold.
XAXIVDMA_MM2S_ADDR_OFFSET
MM2S channel Addr.
Referenced by XAxiVdma_CfgInitialize.
XAXIVDMA_S2MM_ADDR_OFFSET
S2MM channel Addr.
Referenced by XAxiVdma_CfgInitialize.
XAXIVDMA_VFLIP_OFFSET
Enable Vertical Flip Register.
Referenced by XAxiVdma_ChannelConfig.
XAXIVDMA_S2MM_DMA_IRQ_MASK_OFFSET
S2MM Err IRQ Mask.
Referenced by XAxiVdma_MaskS2MMErrIntr.
XAXIVDMA_VSIZE_OFFSET
Vertical size.
Referenced by XAxiVdma_ChannelStart.
XAXIVDMA_HSIZE_OFFSET
Horizontal size.
Referenced by XAxiVdma_ChannelConfig.
XAXIVDMA_STRD_FRMDLY_OFFSET
Horizontal size.
Referenced by XAxiVdma_ChannelConfig.
XAXIVDMA_START_ADDR_OFFSET
Start of address.
Referenced by XAxiVdma_ChannelSetBufferAddr.
XAXIVDMA_START_ADDR_LEN
Each entry is 4 bytes.
Referenced by XAxiVdma_ChannelSetBufferAddr.
XAXIVDMA_START_ADDR_MSB_OFFSET
Start of address.
Referenced by XAxiVdma_ChannelSetBufferAddr.
XAXIVDMA_CR_RUNSTOP_MASK
Start/stop DMA channel.
Referenced by XAxiVdma_ChannelStart, XAxiVdma_ChannelStop.
XAXIVDMA_CR_TAIL_EN_MASK
Tail ptr enable or Park.
Referenced by XAxiVdma_ChannelConfig, XAxiVdma_ChannelStartParking, XAxiVdma_ChannelStopParking.
XAXIVDMA_CR_RESET_MASK
Reset channel.
Referenced by XAxiVdma_ChannelReset, XAxiVdma_ChannelResetNotDone.
XAXIVDMA_CR_SYNC_EN_MASK
Gen-lock enable.
Referenced by XAxiVdma_ChannelConfig.
XAXIVDMA_CR_FRMCNT_EN_MASK
Frame count enable.
Referenced by XAxiVdma_ChannelConfig, XAxiVdma_ChannelStartFrmCntEnable.
XAXIVDMA_CR_FSYNC_SRC_MASK
Fsync Source Select.
Referenced by XAxiVdma_FsyncSrcSelect.
XAXIVDMA_CR_GENLCK_SRC_MASK
Genlock Source Select.
Referenced by XAxiVdma_GenLockSourceSelect.
XAXIVDMA_CR_RD_PTR_MASK
Read pointer number.
Referenced by XAxiVdma_ChannelConfig.
XAXIVDMA_CR_GENLCK_RPT_MASK
GenLock Repeat.
Referenced by XAxiVdma_ChannelConfig.
XAXIVDMA_VFLIP_EN_MASK
Vertical flip enable.
Referenced by XAxiVdma_ChannelConfig.
XAXIVDMA_CR_RD_PTR_SHIFT
Shift for read pointer number.
Referenced by XAxiVdma_ChannelConfig.
XAXIVDMA_SR_HALTED_MASK
DMA channel halted.
Referenced by XAxiVdma_ChannelIsBusy.
XAXIVDMA_SR_IDLE_MASK
DMA channel idle.
Referenced by XAxiVdma_ChannelIsBusy.
XAXIVDMA_SR_ERR_INTERNAL_MASK
Datamover internal err.
XAXIVDMA_SR_ERR_SLAVE_MASK
Datamover slave err.
XAXIVDMA_SR_ERR_DECODE_MASK
Datamover decode err.
XAXIVDMA_SR_ERR_FSZ_LESS_MASK
FSize Less Mismatch err.
XAXIVDMA_SR_ERR_LSZ_LESS_MASK
LSize Less Mismatch err.
XAXIVDMA_SR_ERR_SG_SLV_MASK
SG slave err.
XAXIVDMA_SR_ERR_SG_DEC_MASK
SG decode err.
XAXIVDMA_SR_ERR_FSZ_MORE_MASK
FSize More Mismatch err.
XAXIVDMA_SR_ERR_ALL_MASK
All errors.
XAXIVDMA_IXR_FRMCNT_MASK
Frame count intr.
Referenced by run_triple_frame_buffer.
XAXIVDMA_IXR_DELAYCNT_MASK
Delay interrupt.
XAXIVDMA_IXR_ERROR_MASK
Error interrupt.
Referenced by run_triple_frame_buffer, XAxiVdma_ReadIntrHandler, XAxiVdma_WriteIntrHandler.
XAXIVDMA_IXR_COMPLETION_MASK
Completion interrupts.
Referenced by XAxiVdma_ReadIntrHandler, XAxiVdma_WriteIntrHandler.
XAXIVDMA_IXR_ALL_MASK
All interrupts.
Referenced by main, XAxiVdma_ChannelDisableIntr, XAxiVdma_ChannelEnableIntr, XAxiVdma_ChannelGetEnabledIntr, XAxiVdma_ChannelGetPendingIntr, XAxiVdma_ChannelIntrClear.
XAXIVDMA_DELAY_MASK
Delay timeout counter.
Referenced by XAxiVdma_ChannelGetFrmCnt, XAxiVdma_ChannelSetFrmCnt.
XAXIVDMA_FRMCNT_MASK
Frame counter.
Referenced by XAxiVdma_ChannelGetFrmCnt, XAxiVdma_ChannelSetFrmCnt.
XAXIVDMA_REGINDEX_MASK
Register Index.
XAXIVDMA_DELAY_SHIFT
XAXIVDMA_FRMCNT_SHIFT
XAXIVDMA_CDESC_CURBD_MASK
BD now working on.
XAXIVDMA_TDESC_CURBD_MASK
BD to stop on.
XAXIVDMA_FRMSTORE_MASK
XAXIVDMA_PARKPTR_READREF_MASK
Read frame to park on.
Referenced by XAxiVdma_ChannelConfig, XAxiVdma_StartParking.
XAXIVDMA_PARKPTR_WRTREF_MASK
Write frame to park on.
Referenced by XAxiVdma_ChannelConfig, XAxiVdma_StartParking.
XAXIVDMA_PARKPTR_READSTR_MASK
Current read frame.
Referenced by XAxiVdma_CurrFrameStore.
XAXIVDMA_PARKPTR_WRTSTR_MASK
Current write frame.
Referenced by XAxiVdma_CurrFrameStore.
XAXIVDMA_READREF_SHIFT
XAXIVDMA_WRTREF_SHIFT
XAXIVDMA_READSTR_SHIFT
XAXIVDMA_WRTSTR_SHIFT
XAXIVDMA_FRM_MAX
At most 16 frames.
Referenced by XAxiVdma_ChannelConfig, XAxiVdma_StartParking.
XAXIVDMA_VERSION_MAJOR_MASK
Major version.
XAXIVDMA_VERSION_MINOR_MASK
Minor version.
XAXIVDMA_VERSION_REV_MASK
Revision letter.
XAXIVDMA_VERSION_MAJOR_SHIFT
XAXIVDMA_VERSION_MINOR_SHIFT
XAXIVDMA_S2MM_IRQ_FSZLESS_SOF_ERLY_MASK
Masks S2MM IRQ FSize Less/SOF Early Error.
XAXIVDMA_S2MM_IRQ_LSZLESS_EOL_ERLY_MASK
Masks S2MM IRQ LSize Less/EOL Early Error.
XAXIVDMA_S2MM_IRQ_FSZMORE_SOF_LATE_MASK
Masks S2MM IRQ FSize More/SOF Late Error.
XAXIVDMA_S2MM_IRQ_LSZMORE_EOL_LATE_MASK
Masks S2MM IRQ LSize More/EOL Late Error.
XAXIVDMA_S2MM_IRQ_ERR_ALL_MASK
Masks all S2MM IRQ Errors.
Referenced by XAxiVdma_MaskS2MMErrIntr.
XAXIVDMA_VSIZE_MASK
Vertical size.
XAXIVDMA_HSIZE_MASK
Horizontal size.
XAXIVDMA_STRIDE_MASK
Stride size.
XAXIVDMA_FRMDLY_MASK
Frame delay.
XAXIVDMA_FRMDLY_SHIFT
Shift for frame delay.
Referenced by XAxiVdma_ChannelConfig.
XAXIVDMA_BD_NDESC_OFFSET
Next descriptor pointer.
XAXIVDMA_BD_START_ADDR_OFFSET
Start address.
XAXIVDMA_BD_VSIZE_OFFSET
Vertical size.
XAXIVDMA_BD_HSIZE_OFFSET
Horizontal size.
XAXIVDMA_BD_STRIDE_OFFSET
Stride size.
XAXIVDMA_BD_NUM_WORDS
Total number of words for one BD.
XAXIVDMA_BD_HW_NUM_BYTES
Number of bytes hw used.
XAXIVDMA_BD_BYTES_TO_CLEAR
Skip next ptr when clearing.
typedef void(* XAxiVdma_CallBack)(void *CallBackRef, u32 InterruptTypes))(void *CallBackRef, u32 InterruptTypes)
Callback type for general interrupts.
CallBackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is called. InterruptTypes indicates the detailed type(s) of the interrupt. Its value equals 'OR'ing one or more XAXIVDMA_IXR_* values defined in xaxivdma_hw.h
typedef void(* XAxiVdma_ErrorCallBack)(void *CallBackRef, u32 ErrorMask))(void *CallBackRef, u32 ErrorMask)
Callback type for Error interrupt.
CallBackRef is a callback reference passed in by the upper layer when setting the callback function, and it is passed back to the upper layer when the callback is called. ErrorMask is a bit mask indicating the cause of the error. Its value equals 'OR'ing one or more XAXIVDMA_IXR_* values defined in xaxivdma_hw.h
typedef u32 XAxiVdma_Bd[XAXIVDMA_BD_MINIMUM_ALIGNMENT_WD][XAXIVDMA_BD_MINIMUM_ALIGNMENT_WD]
char* XAxiVdma_Config::Name
Unique name of the device.
Referenced by XAxiVdma_LookupConfig.
UINTPTR XAxiVdma_Config::BaseAddress
BaseAddress is the physical base address of the device's registers
Referenced by AxiVDMASelfTestExample, main, run_triple_frame_buffer.
u16 XAxiVdma_Config::MaxFrameStoreNum
The maximum number of Frame Stores.
Referenced by main, XAxiVdma_CfgInitialize.
int XAxiVdma_Config::HasMm2S
Whether hw build has read channel.
Referenced by XAxiVdma_CfgInitialize.
int XAxiVdma_Config::HasMm2SDRE
Read channel supports unaligned transfer.
Referenced by XAxiVdma_CfgInitialize.
int XAxiVdma_Config::Mm2SWordLen
Read channel word length.
Referenced by XAxiVdma_CfgInitialize.
int XAxiVdma_Config::HasS2Mm
Whether hw build has write channel.
Referenced by XAxiVdma_CfgInitialize.
int XAxiVdma_Config::HasS2MmDRE
Write channel supports unaligned transfer.
Referenced by XAxiVdma_CfgInitialize.
int XAxiVdma_Config::S2MmWordLen
Write channel word length.
Referenced by XAxiVdma_CfgInitialize.
int XAxiVdma_Config::HasSG
Whether hardware has SG engine.
Referenced by XAxiVdma_CfgInitialize.
int XAxiVdma_Config::EnableVIDParamRead
Read Enable for video parameters in direct register mode.
int XAxiVdma_Config::UseFsync
DMA operations synchronized to Frame Sync.
Referenced by XAxiVdma_CfgInitialize.
int XAxiVdma_Config::FlushonFsync
VDMA Transactions are flushed & channel states reset on Frame Sync
Referenced by XAxiVdma_CfgInitialize.
int XAxiVdma_Config::Mm2SBufDepth
Depth of Read Channel Line Buffer FIFO.
Referenced by XAxiVdma_CfgInitialize.
int XAxiVdma_Config::S2MmBufDepth
Depth of Write Channel Line Buffer FIFO.
Referenced by XAxiVdma_CfgInitialize.
int XAxiVdma_Config::Mm2SGenLock
Mm2s Gen Lock Mode.
Referenced by XAxiVdma_CfgInitialize.
int XAxiVdma_Config::S2MmGenLock
S2Mm Gen Lock Mode.
Referenced by XAxiVdma_CfgInitialize.
int XAxiVdma_Config::InternalGenLock
Internal Gen Lock.
Referenced by XAxiVdma_CfgInitialize.
int XAxiVdma_Config::S2MmSOF
S2MM Start of Flag Enable.
Referenced by XAxiVdma_CfgInitialize.
int XAxiVdma_Config::Mm2SStreamWidth
MM2S TData Width.
Referenced by run_triple_frame_buffer, XAxiVdma_CfgInitialize.
int XAxiVdma_Config::S2MmStreamWidth
S2MM TData Width.
Referenced by XAxiVdma_CfgInitialize.
int XAxiVdma_Config::Mm2SThresRegEn
MM2S Threshold Register Enable Flag This corresponds to C_ENABLE_DEBUG_INFO_1 configuration parameter.
Referenced by XAxiVdma_CfgInitialize.
int XAxiVdma_Config::Mm2SFrmStoreRegEn
MM2S Frame Store Register Enable Flag This corresponds to C_ENABLE_DEBUG_INFO_5 configuration parameter.
Referenced by XAxiVdma_CfgInitialize.
int XAxiVdma_Config::Mm2SDlyCntrEn
MM2S Delay Counter (Control Reg) Enable Flag This corresponds to C_ENABLE_DEBUG_INFO_6 configuration parameter.
Referenced by XAxiVdma_CfgInitialize.
int XAxiVdma_Config::Mm2SFrmCntrEn
MM2S Frame Counter (Control Reg) Enable Flag This corresponds to C_ENABLE_DEBUG_INFO_7 configuration parameter.
Referenced by XAxiVdma_CfgInitialize.
int XAxiVdma_Config::S2MmThresRegEn
S2MM Threshold Register Enable Flag This corresponds to C_ENABLE_DEBUG_INFO_9 configuration parameter.
Referenced by XAxiVdma_CfgInitialize.
int XAxiVdma_Config::S2MmFrmStoreRegEn
S2MM Frame Store Register Enable Flag This corresponds to C_ENABLE_DEBUG_INFO_13 configuration parameter.
Referenced by XAxiVdma_CfgInitialize.
int XAxiVdma_Config::S2MmDlyCntrEn
S2MM Delay Counter (Control Reg) Enable Flag This corresponds to C_ENABLE_DEBUG_INFO_14 configuration parameter.
Referenced by XAxiVdma_CfgInitialize.
int XAxiVdma_Config::S2MmFrmCntrEn
S2MM Frame Counter (Control Reg) Enable Flag This corresponds to C_ENABLE_DEBUG_INFO_15 configuration parameter.
Referenced by XAxiVdma_CfgInitialize.
int XAxiVdma_Config::EnableAllDbgFeatures
Enable all Debug features This corresponds to C_ENABLE_DEBUG_ALL configuration parameter.
Referenced by XAxiVdma_CfgInitialize.
int XAxiVdma_Config::AddrWidth
Address Width.
Referenced by XAxiVdma_CfgInitialize.
u8 XAxiVdma_Config::HasVFlip
Whether hardware has Vertical Flip enabled(c_enable_vert_flip)
Referenced by XAxiVdma_CfgInitialize.
u16 XAxiVdma_Config::IntrId[2][2]
Bits[11:0] Interrupt-id Bits[15:12] trigger type and level flags.
Referenced by main.
UINTPTR XAxiVdma_Config::IntrParent
Bit[0] Interrupt parent type Bit[64/32:1] Parent base address.
Referenced by main.
int XAxiVdma_DmaSetup::VertSizeInput
Vertical size input.
int XAxiVdma_DmaSetup::HoriSizeInput
Horizontal size input.
int XAxiVdma_DmaSetup::Stride
Stride.
int XAxiVdma_DmaSetup::FrameDelay
Frame Delay.
int XAxiVdma_DmaSetup::EnableCircularBuf
Circular Buffer Mode?
int XAxiVdma_DmaSetup::EnableSync
Gen-Lock Mode?
int XAxiVdma_DmaSetup::PointNum
Master we synchronize with.
int XAxiVdma_DmaSetup::EnableFrameCounter
Frame Counter Enable.
UINTPTR XAxiVdma_DmaSetup::FrameStoreStartAddr[XAXIVDMA_MAX_FRAMESTORE][XAXIVDMA_MAX_FRAMESTORE]
Start Addresses of Frame Store Buffers.
int XAxiVdma_DmaSetup::FixedFrameStoreAddr
Fixed Frame Store Address index.
int XAxiVdma_DmaSetup::GenLockRepeat
Gen-Lock Repeat?
u8 XAxiVdma_DmaSetup::EnableVFlip
Vertical Flip state.
u8 XAxiVdma_FrameCounter::ReadFrameCount
Interrupt threshold for Receive.
Referenced by main, run_triple_frame_buffer, XAxiVdma_GetFrameCounter, XAxiVdma_SetFrameCounter.
u8 XAxiVdma_FrameCounter::ReadDelayTimerCount
Delay timer threshold for receive.
Referenced by main, run_triple_frame_buffer, XAxiVdma_GetFrameCounter, XAxiVdma_SetFrameCounter.
u8 XAxiVdma_FrameCounter::WriteFrameCount
Interrupt threshold for transmit.
Referenced by main, run_triple_frame_buffer, XAxiVdma_GetFrameCounter, XAxiVdma_SetFrameCounter.
u8 XAxiVdma_FrameCounter::WriteDelayTimerCount
Delay timer threshold for transmit.
Referenced by main, run_triple_frame_buffer, XAxiVdma_GetFrameCounter, XAxiVdma_SetFrameCounter.
XAxiVdma_CallBack XAxiVdma_ChannelCallBack::CompletionCallBack
Call back for completion intr.
Referenced by XAxiVdma_CfgInitialize, XAxiVdma_ReadIntrHandler, XAxiVdma_SetCallBack, XAxiVdma_WriteIntrHandler.
void* XAxiVdma_ChannelCallBack::CompletionRef
Call back ref.
Referenced by XAxiVdma_ReadIntrHandler, XAxiVdma_SetCallBack, XAxiVdma_WriteIntrHandler.
XAxiVdma_ErrorCallBack XAxiVdma_ChannelCallBack::ErrCallBack
Call back for error intr.
Referenced by XAxiVdma_CfgInitialize, XAxiVdma_ReadIntrHandler, XAxiVdma_SetCallBack, XAxiVdma_WriteIntrHandler.
void* XAxiVdma_ChannelCallBack::ErrRef
Call back ref.
Referenced by XAxiVdma_ReadIntrHandler, XAxiVdma_SetCallBack, XAxiVdma_WriteIntrHandler.
UINTPTR XAxiVdma::BaseAddr
Memory address for this device.
Referenced by XAxiVdma_CfgInitialize, XAxiVdma_CurrFrameStore, XAxiVdma_GetVersion, XAxiVdma_Selftest, XAxiVdma_StartParking.
int XAxiVdma::HasSG
Whether hardware has SG engine.
Referenced by XAxiVdma_CfgInitialize.
int XAxiVdma::IsReady
Whether driver is initialized.
Referenced by XAxiVdma_CfgInitialize, XAxiVdma_GetFrameCounter, XAxiVdma_SetCallBack, XAxiVdma_SetFrameCounter.
int XAxiVdma::MaxNumFrames
Number of frames to work on.
Referenced by XAxiVdma_CfgInitialize, XAxiVdma_SetFrmStore.
int XAxiVdma::HasMm2S
Whether hw build has read channel.
Referenced by XAxiVdma_CfgInitialize, XAxiVdma_GenLockSourceSelect, XAxiVdma_Selftest.
int XAxiVdma::HasMm2SDRE
Whether read channel has DRE.
int XAxiVdma::HasS2Mm
Whether hw build has write channel.
Referenced by XAxiVdma_CfgInitialize, XAxiVdma_GenLockSourceSelect, XAxiVdma_Selftest.
int XAxiVdma::HasS2MmDRE
Whether write channel has DRE.
int XAxiVdma::EnableVIDParamRead
Read Enable for video parameters in direct register mode.
int XAxiVdma::UseFsync
DMA operations synchronized to Frame Sync.
Referenced by XAxiVdma_CfgInitialize, XAxiVdma_FsyncSrcSelect.
int XAxiVdma::InternalGenLock
Internal Gen Lock.
Referenced by XAxiVdma_CfgInitialize, XAxiVdma_GenLockSourceSelect.
XAxiVdma_ChannelCallBack XAxiVdma::ReadCallBack
Call back for read channel.
Referenced by XAxiVdma_CfgInitialize, XAxiVdma_ReadIntrHandler, XAxiVdma_SetCallBack.
XAxiVdma_ChannelCallBack XAxiVdma::WriteCallBack
Call back for write channel.
Referenced by XAxiVdma_CfgInitialize, XAxiVdma_SetCallBack, XAxiVdma_WriteIntrHandler.
XAxiVdma_Channel XAxiVdma::ReadChannel
Channel to read from memory.
Referenced by XAxiVdma_GetChannel.
XAxiVdma_Channel XAxiVdma::WriteChannel
Channel to write to memory.
Referenced by XAxiVdma_GetChannel.
int XAxiVdma::AddrWidth
Address Width.
Referenced by XAxiVdma_CfgInitialize.
XAxiVdma_Config XAxiVdma_ConfigTable[][]
XAxiVdma_Channel * XAxiVdma_GetChannel(XAxiVdma *InstancePtr, u16 Direction)
Get a channel.
InstancePtr is the DMA engine to work on Direction is the direction for the channel to get The pointer to the channel. Upon error, return NULL. Since this function is internally used, we assume Direction is valid
References XAxiVdma::ReadChannel, XAxiVdma::WriteChannel, XAXIVDMA_READ, XAXIVDMA_WRITE.
Referenced by XAxiVdma_CfgInitialize, XAxiVdma_ClearDmaChannelErrors, XAxiVdma_DmaConfig, XAxiVdma_DmaRegisterDump, XAxiVdma_DmaSetBufferAddr, XAxiVdma_DmaStart, XAxiVdma_DmaStop, XAxiVdma_FsyncSrcSelect, XAxiVdma_GenLockSourceSelect, XAxiVdma_GetDmaChannelErrors, XAxiVdma_GetFrameCounter, XAxiVdma_GetFrmStore, XAxiVdma_GetStatus, XAxiVdma_IntrClear, XAxiVdma_IntrDisable, XAxiVdma_IntrEnable, XAxiVdma_IntrGetPending, XAxiVdma_IsBusy, XAxiVdma_MaskS2MMErrIntr, XAxiVdma_ReadIntrHandler, XAxiVdma_Reset, XAxiVdma_ResetNotDone, XAxiVdma_Selftest, XAxiVdma_SetBdAddrs, XAxiVdma_SetFrameCounter, XAxiVdma_SetFrmStore, XAxiVdma_SetLineBufThreshold, XAxiVdma_StartFrmCntEnable, XAxiVdma_StartParking, XAxiVdma_StartReadFrame, XAxiVdma_StartWriteFrame, XAxiVdma_StopParking, XAxiVdma_WriteIntrHandler.
static int XAxiVdma_Major(XAxiVdma *InstancePtr)
int XAxiVdma_CfgInitialize(XAxiVdma *InstancePtr, XAxiVdma_Config *CfgPtr, UINTPTR EffectiveAddr)
Initialize the driver with hardware configuration.
InstancePtr is the pointer to the DMA engine to work on CfgPtr is the pointer to the hardware configuration structure EffectiveAddr is the virtual address map for the device XST_SUCCESS if everything goes fineXST_FAILURE if reset the hardware failed, need system reset to recover If channel fails reset, then it will be set as invalid
References XAxiVdma_Config::AddrWidth, XAxiVdma::AddrWidth, XAxiVdma::BaseAddr, XAxiVdma_ChannelCallBack::CompletionCallBack, XAxiVdma_Config::EnableAllDbgFeatures, XAxiVdma_ChannelCallBack::ErrCallBack, XAxiVdma_Config::FlushonFsync, XAxiVdma_Config::HasMm2S, XAxiVdma::HasMm2S, XAxiVdma_Config::HasMm2SDRE, XAxiVdma_Config::HasS2Mm, XAxiVdma::HasS2Mm, XAxiVdma_Config::HasS2MmDRE, XAxiVdma_Config::HasSG, XAxiVdma::HasSG, XAxiVdma_Config::HasVFlip, XAxiVdma_Config::InternalGenLock, XAxiVdma::InternalGenLock, XAxiVdma::IsReady, XAxiVdma_Config::MaxFrameStoreNum, XAxiVdma::MaxNumFrames, XAxiVdma_Config::Mm2SBufDepth, XAxiVdma_Config::Mm2SDlyCntrEn, XAxiVdma_Config::Mm2SFrmCntrEn, XAxiVdma_Config::Mm2SFrmStoreRegEn, XAxiVdma_Config::Mm2SGenLock, XAxiVdma_Config::Mm2SStreamWidth, XAxiVdma_Config::Mm2SThresRegEn, XAxiVdma_Config::Mm2SWordLen, XAxiVdma::ReadCallBack, XAxiVdma_Config::S2MmBufDepth, XAxiVdma_Config::S2MmDlyCntrEn, XAxiVdma_Config::S2MmFrmCntrEn, XAxiVdma_Config::S2MmFrmStoreRegEn, XAxiVdma_Config::S2MmGenLock, XAxiVdma_Config::S2MmSOF, XAxiVdma_Config::S2MmStreamWidth, XAxiVdma_Config::S2MmThresRegEn, XAxiVdma_Config::S2MmWordLen, XAxiVdma_Config::UseFsync, XAxiVdma::UseFsync, XAxiVdma::WriteCallBack, XAXIVDMA_BUFTHRES_OFFSET, XAxiVdma_ChannelGetStatus, XAxiVdma_ChannelInit, XAxiVdma_ChannelReset, XAxiVdma_ChannelResetNotDone, XAXIVDMA_DEVICE_READY, XAXIVDMA_ENABLE_DBG_THRESHOLD_REG, XAxiVdma_GetChannel, XAXIVDMA_MM2S_ADDR_OFFSET, XAXIVDMA_READ, XAxiVdma_ReadReg, XAXIVDMA_RX_OFFSET, XAXIVDMA_S2MM_ADDR_OFFSET, XAXIVDMA_TX_OFFSET, XAXIVDMA_WRITE.
Referenced by AxiVDMASelfTestExample, main, run_triple_frame_buffer.
void XAxiVdma_Reset(XAxiVdma *InstancePtr, u16 Direction)
This function resets one DMA channel.
The registers will be default values after the reset InstancePtr is the pointer to the DMA engine to work on Direction is the channel to work on, use XAXIVDMA_READ/WRITE None Due to undeterminism of system delays, check the reset status through XAxiVdma_ResetNotDone(). If direction is invalid, do nothing.
References XAxiVdma_ChannelReset, XAxiVdma_GetChannel.
Referenced by main.
int XAxiVdma_ResetNotDone(XAxiVdma *InstancePtr, u16 Direction)
This function checks one DMA channel for reset completion.
InstancePtr is the pointer to the DMA engine to work on Direction is the channel to work on, use XAXIVDMA_READ/WRITE 0 if reset is done1 if reset is ongoing We do not check for channel validity, because channel is marked as invalid before reset is done
References XAxiVdma_ChannelResetNotDone, XAxiVdma_GetChannel.
Referenced by main.
int XAxiVdma_IsBusy(XAxiVdma *InstancePtr, u16 Direction)
Check whether a DMA channel is busy.
InstancePtr is the pointer to the DMA engine to work on Direction is the channel to work on, use XAXIVDMA_READ/WRITE Non-zero if the channel is busyZero if the channel is idle
References XAxiVdma_ChannelIsBusy, XAxiVdma_GetChannel.
u32 XAxiVdma_CurrFrameStore(XAxiVdma *InstancePtr, u16 Direction)
Get the current frame that hardware is working on.
InstancePtr is the pointer to the DMA engine to work on Direction is the channel to work on, use XAXIVDMA_READ/WRITE The current frame that the hardware is working on If returned frame number is out of range, then the channel is invalid
References XAxiVdma::BaseAddr, XAXIVDMA_PARKPTR_OFFSET, XAXIVDMA_PARKPTR_READSTR_MASK, XAXIVDMA_PARKPTR_WRTSTR_MASK, XAXIVDMA_READ, XAxiVdma_ReadReg, XAXIVDMA_WRITE.
u32 XAxiVdma_GetVersion(XAxiVdma *InstancePtr)
Get the version of the hardware.
InstancePtr is the pointer to the DMA engine to work on The version of the hardware
References XAxiVdma::BaseAddr, XAxiVdma_ReadReg, XAXIVDMA_VERSION_OFFSET.
u32 XAxiVdma_GetStatus(XAxiVdma *InstancePtr, u16 Direction)
Get the status of a channel.
InstancePtr is the pointer to the DMA engine to work on Direction is the channel to work on, use XAXIVDMA_READ/WRITE The status of the channel An invalid return value indicates that channel is invalid
References XAxiVdma_ChannelGetStatus, XAxiVdma_GetChannel.
Referenced by main.
int XAxiVdma_SetLineBufThreshold(XAxiVdma *InstancePtr, int LineBufThreshold, u16 Direction)
Configure Line Buffer Threshold.
InstancePtr is the pointer to the DMA engine to work on LineBufThreshold is the value to set threshold Direction is the DMA channel to work on XST_SUCCESS if successfulXST_FAILURE otherwiseXST_NO_FEATURE if access to Threshold register is disabled
References XAXIVDMA_BUFTHRES_OFFSET, XAXIVDMA_ENABLE_DBG_THRESHOLD_REG, XAxiVdma_GetChannel, XAxiVdma_ReadReg, XAxiVdma_WriteReg.
int XAxiVdma_FsyncSrcSelect(XAxiVdma *InstancePtr, u32 Source, u16 Direction)
Configure Frame Sync Source and valid only when C_USE_FSYNC is enabled.
InstancePtr is the pointer to the DMA engine to work on Source is the value to set the source of Frame Sync Direction is the DMA channel to work on XST_SUCCESS if successfulXST_FAILURE if C_USE_FSYNC is disabled.
References XAxiVdma::UseFsync, XAXIVDMA_CHAN_FSYNC, XAXIVDMA_CR_FSYNC_SRC_MASK, XAXIVDMA_CR_OFFSET, XAxiVdma_GetChannel, XAxiVdma_ReadReg, XAXIVDMA_WRITE, XAxiVdma_WriteReg.
int XAxiVdma_GenLockSourceSelect(XAxiVdma *InstancePtr, u32 Source, u16 Direction)
Configure Gen Lock Source.
InstancePtr is the pointer to the DMA engine to work on Source is the value to set the source of Gen Lock Direction is the DMA channel to work on XST_SUCCESS if successfulXST_FAILURE if the channel is in GenLock Master Mode. if C_INCLUDE_INTERNAL_GENLOCK is disabled.
References XAxiVdma::HasMm2S, XAxiVdma::HasS2Mm, XAxiVdma::InternalGenLock, XAXIVDMA_CR_GENLCK_SRC_MASK, XAXIVDMA_CR_OFFSET, XAXIVDMA_EXTERNAL_GENLOCK, XAXIVDMA_GENLOCK_MASTER, XAxiVdma_GetChannel, XAXIVDMA_READ, XAxiVdma_ReadReg, XAXIVDMA_WRITE, XAxiVdma_WriteReg.
int XAxiVdma_StartParking(XAxiVdma *InstancePtr, int FrameIndex, u16 Direction)
Start parking mode on a certain frame.
InstancePtr is the pointer to the DMA engine to work on FrameIndex is the frame to park on Direction is the channel to work on, use XAXIVDMA_READ/WRITE XST_SUCCESS if everything is fineXST_INVALID_PARAM if . channel is invalid . FrameIndex is invalid . Direction is invalid
References XAxiVdma::BaseAddr, XAxiVdma_ChannelStartParking, XAXIVDMA_FRM_MAX, XAxiVdma_GetChannel, XAXIVDMA_PARKPTR_OFFSET, XAXIVDMA_PARKPTR_READREF_MASK, XAXIVDMA_PARKPTR_WRTREF_MASK, XAXIVDMA_READ, XAxiVdma_ReadReg, XAXIVDMA_WRITE, XAxiVdma_WriteReg.
void XAxiVdma_StopParking(XAxiVdma *InstancePtr, u16 Direction)
Exit parking mode, the channel will return to circular buffer mode.
InstancePtr is the pointer to the DMA engine to work on Direction is the channel to work on, use XAXIVDMA_READ/WRITE None If channel is invalid, then do nothing
References XAxiVdma_ChannelStopParking, XAxiVdma_GetChannel.
void XAxiVdma_StartFrmCntEnable(XAxiVdma *InstancePtr, u16 Direction)
Start frame count enable on one channel.
This is needed to start limiting the number of frames to transfer so that software can check the data etc after hardware stops transfer. InstancePtr is the pointer to the DMA engine to work on Direction is the channel to work on, use XAXIVDMA_READ/WRITE None
References XAxiVdma_ChannelStartFrmCntEnable, XAxiVdma_GetChannel.
int XAxiVdma_SetBdAddrs(XAxiVdma *InstancePtr, u32 BdAddrPhys, u32 BdAddrVirt, int NumBds, u16 Direction)
Set BD addresses to be different.
In some systems, it is convenient to put BDs into a certain region of the memory. This function enables that. InstancePtr is the pointer to the DMA engine to work on BdAddrPhys is the physical starting address for BDs BdAddrVirt is the Virtual starting address for BDs. For systems that do not use MMU, then virtual address is the same as physical address NumBds is the number of BDs to setup with. This is required to be the same as the number of frame stores for that channel Direction is the channel direction XST_SUCCESS for a successful setupXST_DEVICE_BUSY if the DMA channel is not idle, BDs are still being usedXST_INVALID_PARAM if parameters not validXST_DEVICE_NOT_FOUND if the channel is invalid We assume that the memory region starting from BdAddrPhys and BdAddrVirt are large enough to hold all the BDs.
References XAXIVDMA_BD_MINIMUM_ALIGNMENT, XAxiVdma_ChannelSetBdAddrs, XAxiVdma_GetChannel.
int XAxiVdma_StartWriteFrame(XAxiVdma *InstancePtr, XAxiVdma_DmaSetup *DmaConfigPtr)
Start a write operation.
Write corresponds to send data from device to memory InstancePtr is the pointer to the DMA engine to work on DmaConfigPtr is the pointer to the setup structure XST_SUCCESS for a successful submissionXST_DEVICE_BUSY if the DMA channel is not idle, BDs are still being usedXST_INVAID_PARAM if parameters in config structure not validXST_DEVICE_NOT_FOUND if the channel is invalid
References XAxiVdma_ChannelStartTransfer, XAxiVdma_GetChannel, XAXIVDMA_WRITE.
int XAxiVdma_StartReadFrame(XAxiVdma *InstancePtr, XAxiVdma_DmaSetup *DmaConfigPtr)
Start a read operation.
Read corresponds to send data from memory to device InstancePtr is the pointer to the DMA engine to work on DmaConfigPtr is the pointer to the setup structure XST_SUCCESS for a successful submissionXST_DEVICE_BUSY if the DMA channel is not idle, BDs are still being usedXST_INVAID_PARAM if parameters in config structure not validXST_DEVICE_NOT_FOUND if the channel is invalid
References XAxiVdma_ChannelStartTransfer, XAxiVdma_GetChannel, XAXIVDMA_READ.
int XAxiVdma_DmaConfig(XAxiVdma *InstancePtr, u16 Direction, XAxiVdma_DmaSetup *DmaConfigPtr)
Configure one DMA channel using the configuration structure.
InstancePtr is the pointer to the DMA engine to work on Direction is the DMA channel to work on DmaConfigPtr is the pointer to the setup structure XST_SUCCESS if successfulXST_DEVICE_BUSY if the DMA channel is not idle, BDs are still being usedXST_INVAID_PARAM if buffer address not valid, for example, unaligned address with no DRE built in the hardware, or Direction invalidXST_DEVICE_NOT_FOUND if the channel is invalid
References XAxiVdma_ChannelConfig, XAxiVdma_GetChannel.
int XAxiVdma_DmaSetBufferAddr(XAxiVdma *InstancePtr, u16 Direction, UINTPTR *BufferAddrSet)
Configure buffer addresses for one DMA channel.
InstancePtr is the pointer to the DMA engine to work on Direction is the DMA channel to work on BufferAddrSet is the set of addresses for the transfers XST_SUCCESS if successfulXST_DEVICE_BUSY if the DMA channel is not idle, BDs are still being usedXST_INVAID_PARAM if buffer address not valid, for example, unaligned address with no DRE built in the hardware, or Direction invalidXST_DEVICE_NOT_FOUND if the channel is invalid
References XAxiVdma_ChannelSetBufferAddr, XAxiVdma_GetChannel.
int XAxiVdma_DmaStart(XAxiVdma *InstancePtr, u16 Direction)
Start one DMA channel.
InstancePtr is the pointer to the DMA engine to work on Direction is the DMA channel to work on XST_SUCCESS if channel started successfullyXST_FAILURE otherwiseXST_DEVICE_NOT_FOUND if the channel is invalidXST_INVALID_PARAM if Direction invalid
References XAxiVdma_ChannelStart, XAxiVdma_GetChannel.
void XAxiVdma_DmaStop(XAxiVdma *InstancePtr, u16 Direction)
Stop one DMA channel.
InstancePtr is the pointer to the DMA engine to work on Direction is the DMA channel to work on None If channel is invalid, then do nothing on that channel
References XAxiVdma_ChannelStop, XAxiVdma_GetChannel.
void XAxiVdma_DmaRegisterDump(XAxiVdma *InstancePtr, u16 Direction)
Dump registers of one DMA channel.
InstancePtr is the pointer to the DMA engine to work on Direction is the DMA channel to work on None If channel is invalid, then do nothing on that channel
References XAxiVdma_ChannelRegisterDump, XAxiVdma_GetChannel.
int XAxiVdma_SetFrameCounter(XAxiVdma *InstancePtr, XAxiVdma_FrameCounter *CfgPtr)
Set the frame counter and delay counter for both channels.
InstancePtr is the pointer to the DMA engine to work on CfgPtr is the pointer to the configuration structure XST_SUCCESS if setup finishes successfullyXST_INVALID_PARAM if the configuration structure has invalid valuesOthers if setting channel frame counter fails If channel is invalid, then do nothing on that channel
References XAxiVdma::IsReady, XAxiVdma_FrameCounter::ReadDelayTimerCount, XAxiVdma_FrameCounter::ReadFrameCount, XAxiVdma_FrameCounter::WriteDelayTimerCount, XAxiVdma_FrameCounter::WriteFrameCount, XAxiVdma_ChannelSetFrmCnt, XAXIVDMA_DEVICE_READY, XAxiVdma_GetChannel, XAXIVDMA_READ, XAXIVDMA_WRITE.
Referenced by main, run_triple_frame_buffer.
void XAxiVdma_GetFrameCounter(XAxiVdma *InstancePtr, XAxiVdma_FrameCounter *CfgPtr)
Get the frame counter and delay counter for both channels.
InstancePtr is the pointer to the DMA engine to work on CfgPtr is the configuration structure to contain return values None If returned frame counter value is 0, then the channel is not valid
References XAxiVdma::IsReady, XAxiVdma_FrameCounter::ReadDelayTimerCount, XAxiVdma_FrameCounter::ReadFrameCount, XAxiVdma_FrameCounter::WriteDelayTimerCount, XAxiVdma_FrameCounter::WriteFrameCount, XAxiVdma_ChannelGetFrmCnt, XAXIVDMA_DEVICE_READY, XAxiVdma_GetChannel, XAXIVDMA_READ, XAXIVDMA_WRITE.
int XAxiVdma_SetFrmStore(XAxiVdma *InstancePtr, u8 FrmStoreNum, u16 Direction)
Set the number of frame store buffers to use.
InstancePtr is the XAxiVdma instance to operate on FrmStoreNum is the number of frame store buffers to use. Direction is the channel to work on, use XAXIVDMA_READ/WRITE - XST_SUCCESS if operation is successful XST_FAILURE if operation fails.XST_NO_FEATURE if access to FrameStore register is disabled None
References XAxiVdma::MaxNumFrames, XAxiVdma_ChannelInit, XAXIVDMA_FRMSTORE_OFFSET, XAxiVdma_GetChannel, XAxiVdma_WriteReg.
Referenced by main.
void XAxiVdma_GetFrmStore(XAxiVdma *InstancePtr, u8 *FrmStoreNum, u16 Direction)
Get the number of frame store buffers to use.
InstancePtr is the XAxiVdma instance to operate on FrmStoreNum is the number of frame store buffers to use. Direction is the channel to work on, use XAXIVDMA_READ/WRITE None None
References XAXIVDMA_FRMSTORE_OFFSET, XAxiVdma_GetChannel, XAxiVdma_ReadReg.
int XAxiVdma_GetDmaChannelErrors(XAxiVdma *InstancePtr, u16 Direction)
Check for DMA Channel Errors.
InstancePtr is the XAxiVdma instance to operate on Direction is the channel to work on, use XAXIVDMA_READ/WRITE - Errors seen on the channel XST_INVALID_PARAM, when channel pointer is invalid.XST_DEVICE_NOT_FOUND, when the channel is not valid. None
References XAxiVdma_GetChannel.
int XAxiVdma_ClearDmaChannelErrors(XAxiVdma *InstancePtr, u16 Direction, u32 ErrorMask)
Clear DMA Channel Errors.
InstancePtr is the XAxiVdma instance to operate on Direction is the channel to work on, use XAXIVDMA_READ/WRITE ErrorMask is the mask of error bits to clear - XST_SUCCESS, when error bits are cleared. XST_INVALID_PARAM, when channel pointer is invalid.XST_DEVICE_NOT_FOUND, when the channel is not valid. None
References XAxiVdma_GetChannel.
XAxiVdma_Config * XAxiVdma_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
A table contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration table entry corresponding to the given device ID/BaseAddress, or NULL if no match is found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XAxiVdma_Config::Name.
Referenced by AxiVDMASelfTestExample, main, run_triple_frame_buffer.
void XAxiVdma_IntrEnable(XAxiVdma *InstancePtr, u32 IntrType, u16 Direction)
Enable specific interrupts for a channel.
Interrupts not specified by the mask will not be affected InstancePtr is the pointer to the DMA engine to work on Direction is the DMA channel, use XAXIVDMA_READ or XAXIVDMA_WRITE IntrType is the bit mask for the interrupts to be enabled None If channel is invalid, then nothing is done
References XAxiVdma_ChannelEnableIntr, XAxiVdma_GetChannel.
Referenced by main, run_triple_frame_buffer.
void XAxiVdma_IntrDisable(XAxiVdma *InstancePtr, u32 IntrType, u16 Direction)
Disable specific interrupts for a channel.
Interrupts not specified by the mask will not be affected InstancePtr is the pointer to the DMA engine to work on IntrType is the bit mask for the interrupts to be disabled Direction is the DMA channel, use XAXIVDMA_READ or XAXIVDMA_WRITE None If channel is invalid, then nothing is done
References XAxiVdma_ChannelDisableIntr, XAxiVdma_GetChannel.
u32 XAxiVdma_IntrGetPending(XAxiVdma *InstancePtr, u16 Direction)
Get the pending interrupts of a channel.
InstancePtr is the pointer to the DMA engine to work on Direction is the DMA channel, use XAXIVDMA_READ or XAXIVDMA_WRITE The bit mask for the currently pending interrupts If Direction is invalid, return 0
References XAxiVdma_ChannelGetPendingIntr, XAxiVdma_GetChannel.
void XAxiVdma_IntrClear(XAxiVdma *InstancePtr, u32 IntrType, u16 Direction)
Clear the pending interrupts specified by the bit mask.
Interrupts not specified by the mask will not be affected InstancePtr is the pointer to the DMA engine to work on Direction is the DMA channel, use XAXIVDMA_READ or XAXIVDMA_WRITE IntrType is the bit mask for the interrupts to be cleared None If channel is invalid, then nothing is done
References XAxiVdma_ChannelIntrClear, XAxiVdma_GetChannel.
int XAxiVdma_MaskS2MMErrIntr(XAxiVdma *InstancePtr, u32 ErrorMask, u16 Direction)
Masks the S2MM error interrupt for the provided error mask value.
InstancePtr is the XAxiVdma instance to operate on ErrorMask is the mask of error bits for which S2MM error interrupt can be disabled. Direction is the channel to work on, use XAXIVDMA_READ/WRITE - XST_SUCCESS, when error bits are cleared. XST_INVALID_PARAM, when channel pointer is invalid.XST_DEVICE_NOT_FOUND, when the channel is not valid. The register S2MM_DMA_IRQ_MASK is only applicable from IPv6.01a which is added at offset XAXIVDMA_S2MM_DMA_IRQ_MASK_OFFSET. For older versions, this offset location is reserved and so the API does not have any effect.
References XAxiVdma_GetChannel, XAXIVDMA_S2MM_DMA_IRQ_MASK_OFFSET, XAXIVDMA_S2MM_IRQ_ERR_ALL_MASK, XAXIVDMA_WRITE, XAxiVdma_WriteReg.
void XAxiVdma_ReadIntrHandler(void *InstancePtr)
Interrupt handler for the read channel.
InstancePtr is the pointer to the DMA engine to work on None If the channel is invalid, then no interrupt handling
References XAxiVdma_ChannelCallBack::CompletionCallBack, XAxiVdma_ChannelCallBack::CompletionRef, XAxiVdma_ChannelCallBack::ErrCallBack, XAxiVdma_ChannelCallBack::ErrRef, XAxiVdma::ReadCallBack, XAxiVdma_ChannelGetEnabledIntr, XAxiVdma_ChannelGetPendingIntr, XAxiVdma_ChannelIntrClear, XAxiVdma_GetChannel, XAXIVDMA_IXR_COMPLETION_MASK, XAXIVDMA_IXR_ERROR_MASK, XAXIVDMA_READ.
Referenced by main.
void XAxiVdma_WriteIntrHandler(void *InstancePtr)
Interrupt handler for the write channel.
InstancePtr is the pointer to the DMA engine to work on None If the channel is invalid, then no interrupt handling
References XAxiVdma_ChannelCallBack::CompletionCallBack, XAxiVdma_ChannelCallBack::CompletionRef, XAxiVdma_ChannelCallBack::ErrCallBack, XAxiVdma_ChannelCallBack::ErrRef, XAxiVdma::WriteCallBack, XAxiVdma_ChannelGetEnabledIntr, XAxiVdma_ChannelGetPendingIntr, XAxiVdma_ChannelIntrClear, XAxiVdma_GetChannel, XAXIVDMA_IXR_COMPLETION_MASK, XAXIVDMA_IXR_ERROR_MASK, XAXIVDMA_WRITE.
Referenced by main.
int XAxiVdma_SetCallBack(XAxiVdma *InstancePtr, u32 HandlerType, void *CallBackFunc, void *CallBackRef, u16 Direction)
Set call back function and call back reference pointer for one channel.
InstancePtr is the pointer to the DMA engine to work on HandlerType is the interrupt type that this callback handles CallBackFunc is the call back function pointer CallBackRef is the call back reference pointer Direction is the DMA channel, use XAXIVDMA_READ or XAXIVDMA_WRITE XST_SUCCESS if everything is fineXST_INVALID_PARAM if the handler type or direction invalid This function overwrites the existing interrupt handler and its reference pointer. The function sets the handlers even if the channels are invalid.
References XAxiVdma_ChannelCallBack::CompletionCallBack, XAxiVdma_ChannelCallBack::CompletionRef, XAxiVdma_ChannelCallBack::ErrCallBack, XAxiVdma_ChannelCallBack::ErrRef, XAxiVdma::IsReady, XAxiVdma::ReadCallBack, XAxiVdma::WriteCallBack, XAXIVDMA_DEVICE_READY, XAXIVDMA_HANDLER_ERROR, XAXIVDMA_HANDLER_GENERAL, XAXIVDMA_READ.
Referenced by main.
int XAxiVdma_Selftest(XAxiVdma *InstancePtr)
Runs a self-test on the driver/device.
This test perform a reset of the VDMA device and checks the device is coming out of reset or not InstancePtr is a pointer to the XAxiVdma instance. XST_SUCCESS if self-test was successful XST_FAILURE if the device is not coming out of reset. None.
References XAxiVdma::BaseAddr, XAxiVdma::HasMm2S, XAxiVdma::HasS2Mm, XAxiVdma_ChannelReset, XAxiVdma_ChannelResetNotDone, XAxiVdma_GetChannel, XAXIVDMA_READ, XAXIVDMA_RX_OFFSET, XAXIVDMA_TX_OFFSET, XAXIVDMA_WRITE.
Referenced by AxiVDMASelfTestExample.
static u32 XAxiVdma_BdRead(XAxiVdma_Bd *BdPtr, int Offset)
static void XAxiVdma_BdWrite(XAxiVdma_Bd *BdPtr, int Offset, u32 Value)
static void XAxiVdma_BdSetNextPtr(XAxiVdma_Bd *BdPtr, u32 NextPtr)
static void XAxiVdma_BdSetAddr(XAxiVdma_Bd *BdPtr, u32 Addr)
static int XAxiVdma_BdSetVsize(XAxiVdma_Bd *BdPtr, int Vsize)
static int XAxiVdma_BdSetHsize(XAxiVdma_Bd *BdPtr, int Vsize)
static int XAxiVdma_BdSetStride(XAxiVdma_Bd *BdPtr, int Stride)
static int XAxiVdma_BdSetFrmDly(XAxiVdma_Bd *BdPtr, int FrmDly)
void XAxiVdma_ChannelInit(XAxiVdma_Channel *Channel)
Initialize a channel of a DMA engine.
This function initializes the BD ring for this channel Channel is the pointer to the DMA channel to work on None
Referenced by XAxiVdma_CfgInitialize, XAxiVdma_SetFrmStore.
int XAxiVdma_ChannelResetNotDone(XAxiVdma_Channel *Channel)
This function checks whether reset operation is done.
Channel is the pointer to the DMA channel to work on 0 if reset is done1 if reset is still going
References XAXIVDMA_CR_OFFSET, XAXIVDMA_CR_RESET_MASK, XAxiVdma_ReadReg.
Referenced by XAxiVdma_CfgInitialize, XAxiVdma_ResetNotDone, XAxiVdma_Selftest.
void XAxiVdma_ChannelReset(XAxiVdma_Channel *Channel)
This function resets one DMA channel.
The registers will be default values after the reset Channel is the pointer to the DMA channel to work on None
References XAXIVDMA_CR_OFFSET, XAXIVDMA_CR_RESET_MASK, XAxiVdma_WriteReg.
Referenced by XAxiVdma_CfgInitialize, XAxiVdma_Reset, XAxiVdma_Selftest.
int XAxiVdma_ChannelIsRunning(XAxiVdma_Channel *Channel)
int XAxiVdma_ChannelIsBusy(XAxiVdma_Channel *Channel)
Check whether a DMA channel is busy.
Channel is the pointer to the channel to work on non zero if the channel is busy0 is the channel is idle
References XAxiVdma_ReadReg, XAXIVDMA_SR_HALTED_MASK, XAXIVDMA_SR_IDLE_MASK, XAXIVDMA_SR_OFFSET.
Referenced by XAxiVdma_ChannelConfig, XAxiVdma_ChannelSetBdAddrs, XAxiVdma_ChannelStart, XAxiVdma_ChannelStartTransfer, XAxiVdma_IsBusy.
u32 XAxiVdma_ChannelErrors(XAxiVdma_Channel *Channel)
void XAxiVdma_ClearChannelErrors(XAxiVdma_Channel *Channel, u32 ErrorMask)
u32 XAxiVdma_ChannelGetStatus(XAxiVdma_Channel *Channel)
Get the current status of a channel.
Channel is the pointer to the channel to work on The status of the channel
References XAxiVdma_ReadReg, XAXIVDMA_SR_OFFSET.
Referenced by XAxiVdma_CfgInitialize, XAxiVdma_GetStatus.
int XAxiVdma_ChannelStartParking(XAxiVdma_Channel *Channel)
Set the channel to run in parking mode.
Channel is the pointer to the channel to work on XST_SUCCESS if everything is fineXST_FAILURE if hardware is not running
References XAXIVDMA_CR_OFFSET, XAXIVDMA_CR_TAIL_EN_MASK, XAxiVdma_ReadReg, XAxiVdma_WriteReg.
Referenced by XAxiVdma_StartParking.
void XAxiVdma_ChannelStopParking(XAxiVdma_Channel *Channel)
Set the channel to run in circular mode, exiting parking mode.
Channel is the pointer to the channel to work on None
References XAXIVDMA_CR_OFFSET, XAXIVDMA_CR_TAIL_EN_MASK, XAxiVdma_ReadReg, XAxiVdma_WriteReg.
Referenced by XAxiVdma_StopParking.
void XAxiVdma_ChannelStartFrmCntEnable(XAxiVdma_Channel *Channel)
Set the channel to run in frame count enable mode.
Channel is the pointer to the channel to work on None
References XAXIVDMA_CR_FRMCNT_EN_MASK, XAXIVDMA_CR_OFFSET, XAxiVdma_ReadReg, XAxiVdma_WriteReg.
Referenced by XAxiVdma_StartFrmCntEnable.
int XAxiVdma_ChannelSetBdAddrs(XAxiVdma_Channel *Channel, UINTPTR BdAddrPhys, UINTPTR BdAddrVirt)
Setup BD addresses to a different memory region.
In some systems, it is convenient to put BDs into a certain region of the memory. This function enables that. Channel is the pointer to the channel to work on BdAddrPhys is the physical starting address for BDs BdAddrVirt is the Virtual starting address for BDs. For systems that do not use MMU, then virtual address is the same as physical address XST_SUCCESS for a successful setupXST_DEVICE_BUSY if the DMA channel is not idle, BDs are still being used We assume that the memory region starting from BdAddrPhys is large enough to hold all the BDs.
References XAxiVdma_ChannelIsBusy.
Referenced by XAxiVdma_SetBdAddrs.
int XAxiVdma_ChannelStartTransfer(XAxiVdma_Channel *Channel, XAxiVdma_ChannelSetup *ChannelCfgPtr)
Start a transfer.
This function setup the DMA engine and start the engine to do the transfer. Channel is the pointer to the channel to work on ChannelCfgPtr is the pointer to the setup structure XST_SUCCESS for a successful submissionXST_FAILURE if channel has not being initializedXST_DEVICE_BUSY if the DMA channel is not idle, BDs are still being usedXST_INVAID_PARAM if parameters in config structure not valid
References XAxiVdma_ChannelConfig, XAxiVdma_ChannelIsBusy, XAxiVdma_ChannelSetBufferAddr, XAxiVdma_ChannelStart.
Referenced by XAxiVdma_StartReadFrame, XAxiVdma_StartWriteFrame.
int XAxiVdma_ChannelConfig(XAxiVdma_Channel *Channel, XAxiVdma_ChannelSetup *ChannelCfgPtr)
Configure one DMA channel using the configuration structure.
Setup the control register and BDs, however, BD addresses are not set. Channel is the pointer to the channel to work on ChannelCfgPtr is the pointer to the setup structure XST_SUCCESS if successfulXST_FAILURE if channel has not being initializedXST_DEVICE_BUSY if the DMA channel is not idleXST_INVALID_PARAM if fields in ChannelCfgPtr is not valid
References XAxiVdma_ChannelIsBusy, XAXIVDMA_CR_FRMCNT_EN_MASK, XAXIVDMA_CR_GENLCK_RPT_MASK, XAXIVDMA_CR_OFFSET, XAXIVDMA_CR_RD_PTR_MASK, XAXIVDMA_CR_RD_PTR_SHIFT, XAXIVDMA_CR_SYNC_EN_MASK, XAXIVDMA_CR_TAIL_EN_MASK, XAXIVDMA_FRM_MAX, XAXIVDMA_FRMDLY_MAX, XAXIVDMA_FRMDLY_SHIFT, XAXIVDMA_GENLOCK_MASTER, XAXIVDMA_HSIZE_OFFSET, XAXIVDMA_PARKPTR_OFFSET, XAXIVDMA_PARKPTR_READREF_MASK, XAXIVDMA_PARKPTR_WRTREF_MASK, XAxiVdma_ReadReg, XAXIVDMA_STRD_FRMDLY_OFFSET, XAXIVDMA_VFLIP_EN_MASK, XAXIVDMA_VFLIP_OFFSET, XAXIVDMA_WRITE, XAxiVdma_WriteReg.
Referenced by XAxiVdma_ChannelStartTransfer, XAxiVdma_DmaConfig.
int XAxiVdma_ChannelSetBufferAddr(XAxiVdma_Channel *Channel, UINTPTR *BufferAddrSet, int NumFrames)
Configure buffer addresses for one DMA channel.
The buffer addresses are physical addresses. Access to 32 Frame Buffer Addresses in direct mode is done through XAxiVdma_ChannelHiFrmAddrEnable/Disable Functions. 0 - Access Bank0 Registers (0x5C - 0x98) 1 - Access Bank1 Registers (0x5C - 0x98) Channel is the pointer to the channel to work on BufferAddrSet is the set of addresses for the transfers NumFrames is the number of frames to set the address XST_SUCCESS if successfulXST_FAILURE if channel has not being initializedXST_DEVICE_BUSY if the DMA channel is not idle, BDs are still being usedXST_INVAID_PARAM if buffer address not valid, for example, unaligned address with no DRE built in the hardware
References XAxiVdma_ChannelHiFrmAddrDisable, XAxiVdma_ChannelHiFrmAddrEnable, XAXIVDMA_MAX_FRAMESTORE, XAXIVDMA_MAX_FRAMESTORE_64, XAXIVDMA_START_ADDR_LEN, XAXIVDMA_START_ADDR_MSB_OFFSET, XAXIVDMA_START_ADDR_OFFSET, XAxiVdma_WriteReg.
Referenced by XAxiVdma_ChannelStartTransfer, XAxiVdma_DmaSetBufferAddr.
int XAxiVdma_ChannelStart(XAxiVdma_Channel *Channel)
Start one DMA channel.
Channel is the pointer to the channel to work on XST_SUCCESS if successfulXST_FAILURE if channel is not initializedXST_DMA_ERROR if: . The DMA channel fails to stop . The DMA channel fails to startXST_DEVICE_BUSY is the channel is doing transfers
References XAXIVDMA_CDESC_OFFSET, XAxiVdma_ChannelIsBusy, XAXIVDMA_CR_OFFSET, XAXIVDMA_CR_RUNSTOP_MASK, XAxiVdma_ReadReg, XAXIVDMA_TDESC_OFFSET, XAXIVDMA_VSIZE_OFFSET, XAxiVdma_WriteReg.
Referenced by XAxiVdma_ChannelStartTransfer, XAxiVdma_DmaStart.
void XAxiVdma_ChannelStop(XAxiVdma_Channel *Channel)
Stop one DMA channel.
Channel is the pointer to the channel to work on None
References XAXIVDMA_CR_OFFSET, XAXIVDMA_CR_RUNSTOP_MASK, XAxiVdma_ReadReg, XAxiVdma_WriteReg.
Referenced by XAxiVdma_DmaStop.
void XAxiVdma_ChannelRegisterDump(XAxiVdma_Channel *Channel)
Dump registers from one DMA channel.
Channel is the pointer to the channel to work on None
References XAXIVDMA_CDESC_OFFSET, XAXIVDMA_CR_OFFSET, XAxiVdma_ReadReg, XAXIVDMA_SR_OFFSET, XAXIVDMA_TDESC_OFFSET.
Referenced by XAxiVdma_DmaRegisterDump.
int XAxiVdma_ChannelSetFrmCnt(XAxiVdma_Channel *Channel, u8 FrmCnt, u8 DlyCnt)
Set the frame counter and delay counter for one channel.
Channel is the pointer to the channel to work on FrmCnt is the frame counter value to be set DlyCnt is the delay counter value to be set XST_SUCCESS if setup finishes successfullyXST_FAILURE if channel is not initializedXST_INVALID_PARAM if the configuration structure has invalid valuesXST_NO_FEATURE if Frame Counter or Delay Counter is disabled
References XAXIVDMA_CR_OFFSET, XAXIVDMA_DELAY_MASK, XAXIVDMA_FRMCNT_MASK, XAxiVdma_ReadReg, XAxiVdma_WriteReg.
Referenced by XAxiVdma_SetFrameCounter.
void XAxiVdma_ChannelGetFrmCnt(XAxiVdma_Channel *Channel, u8 *FrmCnt, u8 *DlyCnt)
Get the frame counter and delay counter for both channels.
Channel is the pointer to the channel to work on FrmCnt is the pointer for the returning frame counter value DlyCnt is the pointer for the returning delay counter value None If FrmCnt return as 0, then the channel is not initialized
References XAXIVDMA_CR_OFFSET, XAXIVDMA_DELAY_MASK, XAXIVDMA_FRMCNT_MASK, XAxiVdma_ReadReg.
Referenced by XAxiVdma_GetFrameCounter.
void XAxiVdma_ChannelEnableIntr(XAxiVdma_Channel *Channel, u32 IntrType)
Enable interrupts for a channel.
Interrupts that are not specified by the interrupt mask are not affected. Channel is the pointer to the channel to work on IntrType is the interrupt mask for interrupts to be enabled None.
References XAXIVDMA_CR_OFFSET, XAXIVDMA_IXR_ALL_MASK, XAxiVdma_ReadReg, XAxiVdma_WriteReg.
Referenced by XAxiVdma_IntrEnable.
void XAxiVdma_ChannelDisableIntr(XAxiVdma_Channel *Channel, u32 IntrType)
Disable interrupts for a channel.
Interrupts that are not specified by the interrupt mask are not affected. Channel is the pointer to the channel to work on IntrType is the interrupt mask for interrupts to be disabled None.
References XAXIVDMA_CR_OFFSET, XAXIVDMA_IXR_ALL_MASK, XAxiVdma_ReadReg, XAxiVdma_WriteReg.
Referenced by XAxiVdma_IntrDisable.
u32 XAxiVdma_ChannelGetPendingIntr(XAxiVdma_Channel *Channel)
Get pending interrupts of a channel.
Channel is the pointer to the channel to work on The interrupts mask represents pending interrupts.
References XAXIVDMA_IXR_ALL_MASK, XAxiVdma_ReadReg, XAXIVDMA_SR_OFFSET.
Referenced by XAxiVdma_IntrGetPending, XAxiVdma_ReadIntrHandler, XAxiVdma_WriteIntrHandler.
void XAxiVdma_ChannelIntrClear(XAxiVdma_Channel *Channel, u32 IntrType)
Clear interrupts of a channel.
Interrupts that are not specified by the interrupt mask are not affected. Channel is the pointer to the channel to work on IntrType is the interrupt mask for interrupts to be cleared None.
References XAXIVDMA_IXR_ALL_MASK, XAXIVDMA_SR_OFFSET, XAxiVdma_WriteReg.
Referenced by XAxiVdma_IntrClear, XAxiVdma_ReadIntrHandler, XAxiVdma_WriteIntrHandler.
u32 XAxiVdma_ChannelGetEnabledIntr(XAxiVdma_Channel *Channel)
Get the enabled interrupts of a channel.
Channel is the pointer to the channel to work on The interrupts mask represents pending interrupts.
References XAXIVDMA_CR_OFFSET, XAXIVDMA_IXR_ALL_MASK, XAxiVdma_ReadReg.
Referenced by XAxiVdma_ReadIntrHandler, XAxiVdma_WriteIntrHandler.
INITIALIZATION_POLLING
XAXIVDMA_H_
XAXIVDMA_WRITE
VDMA data transfer direction.
DMA transfer into memory
Referenced by main, run_triple_frame_buffer, XAxiVdma_CfgInitialize, XAxiVdma_ChannelConfig, XAxiVdma_CurrFrameStore, XAxiVdma_FsyncSrcSelect, XAxiVdma_GenLockSourceSelect, XAxiVdma_GetChannel, XAxiVdma_GetFrameCounter, XAxiVdma_MaskS2MMErrIntr, XAxiVdma_Selftest, XAxiVdma_SetFrameCounter, XAxiVdma_StartParking, XAxiVdma_StartWriteFrame, XAxiVdma_WriteIntrHandler.
XAXIVDMA_READ
DMA transfer from memory.
Referenced by main, run_triple_frame_buffer, XAxiVdma_CfgInitialize, XAxiVdma_CurrFrameStore, XAxiVdma_GenLockSourceSelect, XAxiVdma_GetChannel, XAxiVdma_GetFrameCounter, XAxiVdma_ReadIntrHandler, XAxiVdma_Selftest, XAxiVdma_SetCallBack, XAxiVdma_SetFrameCounter, XAxiVdma_StartParking, XAxiVdma_StartReadFrame.
XAXIVDMA_CHAN_FSYNC
Frame Sync Source Selection.
Referenced by XAxiVdma_FsyncSrcSelect.
XAXIVDMA_CHAN_OTHER_FSYNC
XAXIVDMA_S2MM_TUSER_FSYNC
XAXIVDMA_EXTERNAL_GENLOCK
GenLock Source Selection.
Referenced by XAxiVdma_GenLockSourceSelect.
XAXIVDMA_INTERNAL_GENLOCK
XAXIVDMA_GENLOCK_MASTER
GenLock Mode Constants.
Referenced by XAxiVdma_ChannelConfig, XAxiVdma_GenLockSourceSelect.
XAXIVDMA_GENLOCK_SLAVE
XAXIVDMA_DYN_GENLOCK_MASTER
XAXIVDMA_DYN_GENLOCK_SLAVE
XAXIVDMA_HANDLER_GENERAL
Interrupt type for setting up callback.
Non-Error Interrupt Type
Referenced by main, XAxiVdma_SetCallBack.
XAXIVDMA_HANDLER_ERROR
Error Interrupt Type.
Referenced by main, XAxiVdma_SetCallBack.
XAXIVDMA_DEVICE_READY
Flag to signal that device is ready to be used.
Referenced by XAxiVdma_CfgInitialize, XAxiVdma_GetFrameCounter, XAxiVdma_SetCallBack, XAxiVdma_SetFrameCounter.
XAXIVDMA_ENABLE_DBG_THRESHOLD_REG
Debug Configuration Parameter Constants (C_ENABLE_DEBUG_INFO_*)
Referenced by XAxiVdma_CfgInitialize, XAxiVdma_SetLineBufThreshold.
XAXIVDMA_ENABLE_DBG_FRMSTORE_REG
XAXIVDMA_ENABLE_DBG_FRM_CNTR
XAXIVDMA_ENABLE_DBG_DLY_CNTR
XAXIVDMA_ENABLE_DBG_ALL_FEATURES
XST_VDMA_MISMATCH_ERROR
XAXIVDMA_RESET_POLLING
XAXIVDMA_VIRT_TO_PHYS
XAxiVdma_ChannelHiFrmAddrEnable
Set the channel to enable access to higher Frame Buffer Addresses (SG=0)
Channel is the pointer to the channel to work on
Referenced by XAxiVdma_ChannelSetBufferAddr.
XAxiVdma_ChannelHiFrmAddrDisable
Set the channel to disable access higher Frame Buffer Addresses (SG=0)
Channel is the pointer to the channel to work on
Referenced by XAxiVdma_ChannelSetBufferAddr.
XAXIVDMA_MISMATCH_ERROR
Frame/Line Mismatch Error This is a typical DMA Internal Error, which on detection does not require a reset (as opposed to other errors).
So a MSB bit is set to identify it, from other DMA Internal Errors.
XAxiVdma_In32
XAxiVdma_Out32
XAxiVdma_ReadReg
Read the given register.
BaseAddress is the base address of the device RegOffset is the register offset to be read The 32-bit value of the register C-style signature: u32 XAxiVdma_ReadReg(u32 BaseAddress, u32 RegOffset)
Referenced by XAxiVdma_CfgInitialize, XAxiVdma_ChannelConfig, XAxiVdma_ChannelDisableIntr, XAxiVdma_ChannelEnableIntr, XAxiVdma_ChannelGetEnabledIntr, XAxiVdma_ChannelGetFrmCnt, XAxiVdma_ChannelGetPendingIntr, XAxiVdma_ChannelGetStatus, XAxiVdma_ChannelIsBusy, XAxiVdma_ChannelRegisterDump, XAxiVdma_ChannelResetNotDone, XAxiVdma_ChannelSetFrmCnt, XAxiVdma_ChannelStart, XAxiVdma_ChannelStartFrmCntEnable, XAxiVdma_ChannelStartParking, XAxiVdma_ChannelStop, XAxiVdma_ChannelStopParking, XAxiVdma_CurrFrameStore, XAxiVdma_FsyncSrcSelect, XAxiVdma_GenLockSourceSelect, XAxiVdma_GetFrmStore, XAxiVdma_GetVersion, XAxiVdma_SetLineBufThreshold, XAxiVdma_StartParking.
XAxiVdma_WriteReg
Write the given register.
BaseAddress is the base address of the device RegOffset is the register offset to be written Data is the 32-bit value to write to the register None. C-style signature: void XAxiVdma_WriteReg(u32 BaseAddress, u32 RegOffset, u32 Data)
Referenced by XAxiVdma_ChannelConfig, XAxiVdma_ChannelDisableIntr, XAxiVdma_ChannelEnableIntr, XAxiVdma_ChannelIntrClear, XAxiVdma_ChannelReset, XAxiVdma_ChannelSetBufferAddr, XAxiVdma_ChannelSetFrmCnt, XAxiVdma_ChannelStart, XAxiVdma_ChannelStartFrmCntEnable, XAxiVdma_ChannelStartParking, XAxiVdma_ChannelStop, XAxiVdma_ChannelStopParking, XAxiVdma_FsyncSrcSelect, XAxiVdma_GenLockSourceSelect, XAxiVdma_MaskS2MMErrIntr, XAxiVdma_SetFrmStore, XAxiVdma_SetLineBufThreshold, XAxiVdma_StartParking.
XAXIVDMA_RESET_TIMEOUT
XPAR_XAXIVDMA_NUM_INSTANCES