xaxivdma.h
XAXIVDMA_H_
XAXIVDMA_WRITE
VDMA data transfer direction.
DMA transfer into memory
Referenced by main, run_triple_frame_buffer, XAxiVdma_CfgInitialize, XAxiVdma_ChannelConfig, XAxiVdma_CurrFrameStore, XAxiVdma_FsyncSrcSelect, XAxiVdma_GenLockSourceSelect, XAxiVdma_GetChannel, XAxiVdma_GetFrameCounter, XAxiVdma_MaskS2MMErrIntr, XAxiVdma_Selftest, XAxiVdma_SetFrameCounter, XAxiVdma_StartParking, XAxiVdma_StartWriteFrame, XAxiVdma_WriteIntrHandler.
XAXIVDMA_READ
DMA transfer from memory.
Referenced by main, run_triple_frame_buffer, XAxiVdma_CfgInitialize, XAxiVdma_CurrFrameStore, XAxiVdma_GenLockSourceSelect, XAxiVdma_GetChannel, XAxiVdma_GetFrameCounter, XAxiVdma_ReadIntrHandler, XAxiVdma_Selftest, XAxiVdma_SetCallBack, XAxiVdma_SetFrameCounter, XAxiVdma_StartParking, XAxiVdma_StartReadFrame.
XAXIVDMA_CHAN_FSYNC
Frame Sync Source Selection.
Referenced by XAxiVdma_FsyncSrcSelect.
XAXIVDMA_CHAN_OTHER_FSYNC
XAXIVDMA_S2MM_TUSER_FSYNC
XAXIVDMA_EXTERNAL_GENLOCK
GenLock Source Selection.
Referenced by XAxiVdma_GenLockSourceSelect.
XAXIVDMA_INTERNAL_GENLOCK
XAXIVDMA_GENLOCK_MASTER
GenLock Mode Constants.
Referenced by XAxiVdma_ChannelConfig, XAxiVdma_GenLockSourceSelect.
XAXIVDMA_GENLOCK_SLAVE
XAXIVDMA_DYN_GENLOCK_MASTER
XAXIVDMA_DYN_GENLOCK_SLAVE
XAXIVDMA_HANDLER_GENERAL
Interrupt type for setting up callback.
Non-Error Interrupt Type
Referenced by main, XAxiVdma_SetCallBack.
XAXIVDMA_HANDLER_ERROR
Error Interrupt Type.
Referenced by main, XAxiVdma_SetCallBack.
XAXIVDMA_DEVICE_READY
Flag to signal that device is ready to be used.
Referenced by XAxiVdma_CfgInitialize, XAxiVdma_GetFrameCounter, XAxiVdma_SetCallBack, XAxiVdma_SetFrameCounter.
XAXIVDMA_ENABLE_DBG_THRESHOLD_REG
Debug Configuration Parameter Constants (C_ENABLE_DEBUG_INFO_*)
Referenced by XAxiVdma_CfgInitialize, XAxiVdma_SetLineBufThreshold.
XAXIVDMA_ENABLE_DBG_FRMSTORE_REG
XAXIVDMA_ENABLE_DBG_FRM_CNTR
XAXIVDMA_ENABLE_DBG_DLY_CNTR
XAXIVDMA_ENABLE_DBG_ALL_FEATURES
XST_VDMA_MISMATCH_ERROR
typedef void(* XAxiVdma_CallBack)(void *CallBackRef, u32 InterruptTypes))(void *CallBackRef, u32 InterruptTypes)
Callback type for general interrupts.
CallBackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is called. InterruptTypes indicates the detailed type(s) of the interrupt. Its value equals 'OR'ing one or more XAXIVDMA_IXR_* values defined in xaxivdma_hw.h
typedef void(* XAxiVdma_ErrorCallBack)(void *CallBackRef, u32 ErrorMask))(void *CallBackRef, u32 ErrorMask)
Callback type for Error interrupt.
CallBackRef is a callback reference passed in by the upper layer when setting the callback function, and it is passed back to the upper layer when the callback is called. ErrorMask is a bit mask indicating the cause of the error. Its value equals 'OR'ing one or more XAXIVDMA_IXR_* values defined in xaxivdma_hw.h
XAxiVdma_Config * XAxiVdma_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
A table contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration table entry corresponding to the given device ID/BaseAddress, or NULL if no match is found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XAxiVdma_Config::Name.
Referenced by AxiVDMASelfTestExample, main, run_triple_frame_buffer.
int XAxiVdma_CfgInitialize(XAxiVdma *InstancePtr, XAxiVdma_Config *CfgPtr, UINTPTR EffectiveAddr)
Initialize the driver with hardware configuration.
InstancePtr is the pointer to the DMA engine to work on CfgPtr is the pointer to the hardware configuration structure EffectiveAddr is the virtual address map for the device XST_SUCCESS if everything goes fineXST_FAILURE if reset the hardware failed, need system reset to recover If channel fails reset, then it will be set as invalid
References XAxiVdma_Config::AddrWidth, XAxiVdma::AddrWidth, XAxiVdma::BaseAddr, XAxiVdma_ChannelCallBack::CompletionCallBack, XAxiVdma_Config::EnableAllDbgFeatures, XAxiVdma_ChannelCallBack::ErrCallBack, XAxiVdma_Config::FlushonFsync, XAxiVdma_Config::HasMm2S, XAxiVdma::HasMm2S, XAxiVdma_Config::HasMm2SDRE, XAxiVdma_Config::HasS2Mm, XAxiVdma::HasS2Mm, XAxiVdma_Config::HasS2MmDRE, XAxiVdma_Config::HasSG, XAxiVdma::HasSG, XAxiVdma_Config::HasVFlip, XAxiVdma_Config::InternalGenLock, XAxiVdma::InternalGenLock, XAxiVdma::IsReady, XAxiVdma_Config::MaxFrameStoreNum, XAxiVdma::MaxNumFrames, XAxiVdma_Config::Mm2SBufDepth, XAxiVdma_Config::Mm2SDlyCntrEn, XAxiVdma_Config::Mm2SFrmCntrEn, XAxiVdma_Config::Mm2SFrmStoreRegEn, XAxiVdma_Config::Mm2SGenLock, XAxiVdma_Config::Mm2SStreamWidth, XAxiVdma_Config::Mm2SThresRegEn, XAxiVdma_Config::Mm2SWordLen, XAxiVdma::ReadCallBack, XAxiVdma_Config::S2MmBufDepth, XAxiVdma_Config::S2MmDlyCntrEn, XAxiVdma_Config::S2MmFrmCntrEn, XAxiVdma_Config::S2MmFrmStoreRegEn, XAxiVdma_Config::S2MmGenLock, XAxiVdma_Config::S2MmSOF, XAxiVdma_Config::S2MmStreamWidth, XAxiVdma_Config::S2MmThresRegEn, XAxiVdma_Config::S2MmWordLen, XAxiVdma_Config::UseFsync, XAxiVdma::UseFsync, XAxiVdma::WriteCallBack, XAXIVDMA_BUFTHRES_OFFSET, XAxiVdma_ChannelGetStatus, XAxiVdma_ChannelInit, XAxiVdma_ChannelReset, XAxiVdma_ChannelResetNotDone, XAXIVDMA_DEVICE_READY, XAXIVDMA_ENABLE_DBG_THRESHOLD_REG, XAxiVdma_GetChannel, XAXIVDMA_MM2S_ADDR_OFFSET, XAXIVDMA_READ, XAxiVdma_ReadReg, XAXIVDMA_RX_OFFSET, XAXIVDMA_S2MM_ADDR_OFFSET, XAXIVDMA_TX_OFFSET, XAXIVDMA_WRITE.
Referenced by AxiVDMASelfTestExample, main, run_triple_frame_buffer.
void XAxiVdma_Reset(XAxiVdma *InstancePtr, u16 Direction)
This function resets one DMA channel.
The registers will be default values after the reset InstancePtr is the pointer to the DMA engine to work on Direction is the channel to work on, use XAXIVDMA_READ/WRITE None Due to undeterminism of system delays, check the reset status through XAxiVdma_ResetNotDone(). If direction is invalid, do nothing.
References XAxiVdma_ChannelReset, XAxiVdma_GetChannel.
Referenced by main.
int XAxiVdma_ResetNotDone(XAxiVdma *InstancePtr, u16 Direction)
This function checks one DMA channel for reset completion.
InstancePtr is the pointer to the DMA engine to work on Direction is the channel to work on, use XAXIVDMA_READ/WRITE 0 if reset is done1 if reset is ongoing We do not check for channel validity, because channel is marked as invalid before reset is done
References XAxiVdma_ChannelResetNotDone, XAxiVdma_GetChannel.
Referenced by main.
int XAxiVdma_IsBusy(XAxiVdma *InstancePtr, u16 Direction)
Check whether a DMA channel is busy.
InstancePtr is the pointer to the DMA engine to work on Direction is the channel to work on, use XAXIVDMA_READ/WRITE Non-zero if the channel is busyZero if the channel is idle
References XAxiVdma_ChannelIsBusy, XAxiVdma_GetChannel.
u32 XAxiVdma_CurrFrameStore(XAxiVdma *InstancePtr, u16 Direction)
Get the current frame that hardware is working on.
InstancePtr is the pointer to the DMA engine to work on Direction is the channel to work on, use XAXIVDMA_READ/WRITE The current frame that the hardware is working on If returned frame number is out of range, then the channel is invalid
References XAxiVdma::BaseAddr, XAXIVDMA_PARKPTR_OFFSET, XAXIVDMA_PARKPTR_READSTR_MASK, XAXIVDMA_PARKPTR_WRTSTR_MASK, XAXIVDMA_READ, XAxiVdma_ReadReg, XAXIVDMA_WRITE.
u32 XAxiVdma_GetVersion(XAxiVdma *InstancePtr)
Get the version of the hardware.
InstancePtr is the pointer to the DMA engine to work on The version of the hardware
References XAxiVdma::BaseAddr, XAxiVdma_ReadReg, XAXIVDMA_VERSION_OFFSET.
u32 XAxiVdma_GetStatus(XAxiVdma *InstancePtr, u16 Direction)
Get the status of a channel.
InstancePtr is the pointer to the DMA engine to work on Direction is the channel to work on, use XAXIVDMA_READ/WRITE The status of the channel An invalid return value indicates that channel is invalid
References XAxiVdma_ChannelGetStatus, XAxiVdma_GetChannel.
Referenced by main.
int XAxiVdma_SetLineBufThreshold(XAxiVdma *InstancePtr, int LineBufThreshold, u16 Direction)
Configure Line Buffer Threshold.
InstancePtr is the pointer to the DMA engine to work on LineBufThreshold is the value to set threshold Direction is the DMA channel to work on XST_SUCCESS if successfulXST_FAILURE otherwiseXST_NO_FEATURE if access to Threshold register is disabled
References XAXIVDMA_BUFTHRES_OFFSET, XAXIVDMA_ENABLE_DBG_THRESHOLD_REG, XAxiVdma_GetChannel, XAxiVdma_ReadReg, XAxiVdma_WriteReg.
int XAxiVdma_StartParking(XAxiVdma *InstancePtr, int FrameIndex, u16 Direction)
Start parking mode on a certain frame.
InstancePtr is the pointer to the DMA engine to work on FrameIndex is the frame to park on Direction is the channel to work on, use XAXIVDMA_READ/WRITE XST_SUCCESS if everything is fineXST_INVALID_PARAM if . channel is invalid . FrameIndex is invalid . Direction is invalid
References XAxiVdma::BaseAddr, XAxiVdma_ChannelStartParking, XAXIVDMA_FRM_MAX, XAxiVdma_GetChannel, XAXIVDMA_PARKPTR_OFFSET, XAXIVDMA_PARKPTR_READREF_MASK, XAXIVDMA_PARKPTR_WRTREF_MASK, XAXIVDMA_READ, XAxiVdma_ReadReg, XAXIVDMA_WRITE, XAxiVdma_WriteReg.
void XAxiVdma_StopParking(XAxiVdma *InstancePtr, u16 Direction)
Exit parking mode, the channel will return to circular buffer mode.
InstancePtr is the pointer to the DMA engine to work on Direction is the channel to work on, use XAXIVDMA_READ/WRITE None If channel is invalid, then do nothing
References XAxiVdma_ChannelStopParking, XAxiVdma_GetChannel.
void XAxiVdma_StartFrmCntEnable(XAxiVdma *InstancePtr, u16 Direction)
Start frame count enable on one channel.
This is needed to start limiting the number of frames to transfer so that software can check the data etc after hardware stops transfer. InstancePtr is the pointer to the DMA engine to work on Direction is the channel to work on, use XAXIVDMA_READ/WRITE None
References XAxiVdma_ChannelStartFrmCntEnable, XAxiVdma_GetChannel.
void XAxiVdma_IntrEnable(XAxiVdma *InstancePtr, u32 IntrType, u16 Direction)
Enable specific interrupts for a channel.
Interrupts not specified by the mask will not be affected InstancePtr is the pointer to the DMA engine to work on Direction is the DMA channel, use XAXIVDMA_READ or XAXIVDMA_WRITE IntrType is the bit mask for the interrupts to be enabled None If channel is invalid, then nothing is done
References XAxiVdma_ChannelEnableIntr, XAxiVdma_GetChannel.
Referenced by main, run_triple_frame_buffer.
void XAxiVdma_IntrDisable(XAxiVdma *InstancePtr, u32 IntrType, u16 Direction)
Disable specific interrupts for a channel.
Interrupts not specified by the mask will not be affected InstancePtr is the pointer to the DMA engine to work on IntrType is the bit mask for the interrupts to be disabled Direction is the DMA channel, use XAXIVDMA_READ or XAXIVDMA_WRITE None If channel is invalid, then nothing is done
References XAxiVdma_ChannelDisableIntr, XAxiVdma_GetChannel.
u32 XAxiVdma_IntrGetPending(XAxiVdma *InstancePtr, u16 Direction)
Get the pending interrupts of a channel.
InstancePtr is the pointer to the DMA engine to work on Direction is the DMA channel, use XAXIVDMA_READ or XAXIVDMA_WRITE The bit mask for the currently pending interrupts If Direction is invalid, return 0
References XAxiVdma_ChannelGetPendingIntr, XAxiVdma_GetChannel.
void XAxiVdma_IntrClear(XAxiVdma *InstancePtr, u32 IntrType, u16 Direction)
Clear the pending interrupts specified by the bit mask.
Interrupts not specified by the mask will not be affected InstancePtr is the pointer to the DMA engine to work on Direction is the DMA channel, use XAXIVDMA_READ or XAXIVDMA_WRITE IntrType is the bit mask for the interrupts to be cleared None If channel is invalid, then nothing is done
References XAxiVdma_ChannelIntrClear, XAxiVdma_GetChannel.
int XAxiVdma_SetBdAddrs(XAxiVdma *InstancePtr, u32 BdAddrPhys, u32 BdAddrVirt, int NumBds, u16 Direction)
Set BD addresses to be different.
In some systems, it is convenient to put BDs into a certain region of the memory. This function enables that. InstancePtr is the pointer to the DMA engine to work on BdAddrPhys is the physical starting address for BDs BdAddrVirt is the Virtual starting address for BDs. For systems that do not use MMU, then virtual address is the same as physical address NumBds is the number of BDs to setup with. This is required to be the same as the number of frame stores for that channel Direction is the channel direction XST_SUCCESS for a successful setupXST_DEVICE_BUSY if the DMA channel is not idle, BDs are still being usedXST_INVALID_PARAM if parameters not validXST_DEVICE_NOT_FOUND if the channel is invalid We assume that the memory region starting from BdAddrPhys and BdAddrVirt are large enough to hold all the BDs.
References XAXIVDMA_BD_MINIMUM_ALIGNMENT, XAxiVdma_ChannelSetBdAddrs, XAxiVdma_GetChannel.
XAxiVdma_Channel * XAxiVdma_GetChannel(XAxiVdma *InstancePtr, u16 Direction)
Get a channel.
InstancePtr is the DMA engine to work on Direction is the direction for the channel to get The pointer to the channel. Upon error, return NULL. Since this function is internally used, we assume Direction is valid
References XAxiVdma::ReadChannel, XAxiVdma::WriteChannel, XAXIVDMA_READ, XAXIVDMA_WRITE.
Referenced by XAxiVdma_CfgInitialize, XAxiVdma_ClearDmaChannelErrors, XAxiVdma_DmaConfig, XAxiVdma_DmaRegisterDump, XAxiVdma_DmaSetBufferAddr, XAxiVdma_DmaStart, XAxiVdma_DmaStop, XAxiVdma_FsyncSrcSelect, XAxiVdma_GenLockSourceSelect, XAxiVdma_GetDmaChannelErrors, XAxiVdma_GetFrameCounter, XAxiVdma_GetFrmStore, XAxiVdma_GetStatus, XAxiVdma_IntrClear, XAxiVdma_IntrDisable, XAxiVdma_IntrEnable, XAxiVdma_IntrGetPending, XAxiVdma_IsBusy, XAxiVdma_MaskS2MMErrIntr, XAxiVdma_ReadIntrHandler, XAxiVdma_Reset, XAxiVdma_ResetNotDone, XAxiVdma_Selftest, XAxiVdma_SetBdAddrs, XAxiVdma_SetFrameCounter, XAxiVdma_SetFrmStore, XAxiVdma_SetLineBufThreshold, XAxiVdma_StartFrmCntEnable, XAxiVdma_StartParking, XAxiVdma_StartReadFrame, XAxiVdma_StartWriteFrame, XAxiVdma_StopParking, XAxiVdma_WriteIntrHandler.
int XAxiVdma_SetFrmStore(XAxiVdma *InstancePtr, u8 FrmStoreNum, u16 Direction)
Set the number of frame store buffers to use.
InstancePtr is the XAxiVdma instance to operate on FrmStoreNum is the number of frame store buffers to use. Direction is the channel to work on, use XAXIVDMA_READ/WRITE - XST_SUCCESS if operation is successful XST_FAILURE if operation fails.XST_NO_FEATURE if access to FrameStore register is disabled None
References XAxiVdma::MaxNumFrames, XAxiVdma_ChannelInit, XAXIVDMA_FRMSTORE_OFFSET, XAxiVdma_GetChannel, XAxiVdma_WriteReg.
Referenced by main.
void XAxiVdma_GetFrmStore(XAxiVdma *InstancePtr, u8 *FrmStoreNum, u16 Direction)
Get the number of frame store buffers to use.
InstancePtr is the XAxiVdma instance to operate on FrmStoreNum is the number of frame store buffers to use. Direction is the channel to work on, use XAXIVDMA_READ/WRITE None None
References XAXIVDMA_FRMSTORE_OFFSET, XAxiVdma_GetChannel, XAxiVdma_ReadReg.
int XAxiVdma_FsyncSrcSelect(XAxiVdma *InstancePtr, u32 Source, u16 Direction)
Configure Frame Sync Source and valid only when C_USE_FSYNC is enabled.
InstancePtr is the pointer to the DMA engine to work on Source is the value to set the source of Frame Sync Direction is the DMA channel to work on XST_SUCCESS if successfulXST_FAILURE if C_USE_FSYNC is disabled.
References XAxiVdma::UseFsync, XAXIVDMA_CHAN_FSYNC, XAXIVDMA_CR_FSYNC_SRC_MASK, XAXIVDMA_CR_OFFSET, XAxiVdma_GetChannel, XAxiVdma_ReadReg, XAXIVDMA_WRITE, XAxiVdma_WriteReg.
int XAxiVdma_GenLockSourceSelect(XAxiVdma *InstancePtr, u32 Source, u16 Direction)
Configure Gen Lock Source.
InstancePtr is the pointer to the DMA engine to work on Source is the value to set the source of Gen Lock Direction is the DMA channel to work on XST_SUCCESS if successfulXST_FAILURE if the channel is in GenLock Master Mode. if C_INCLUDE_INTERNAL_GENLOCK is disabled.
References XAxiVdma::HasMm2S, XAxiVdma::HasS2Mm, XAxiVdma::InternalGenLock, XAXIVDMA_CR_GENLCK_SRC_MASK, XAXIVDMA_CR_OFFSET, XAXIVDMA_EXTERNAL_GENLOCK, XAXIVDMA_GENLOCK_MASTER, XAxiVdma_GetChannel, XAXIVDMA_READ, XAxiVdma_ReadReg, XAXIVDMA_WRITE, XAxiVdma_WriteReg.
int XAxiVdma_GetDmaChannelErrors(XAxiVdma *InstancePtr, u16 Direction)
Check for DMA Channel Errors.
InstancePtr is the XAxiVdma instance to operate on Direction is the channel to work on, use XAXIVDMA_READ/WRITE - Errors seen on the channel XST_INVALID_PARAM, when channel pointer is invalid.XST_DEVICE_NOT_FOUND, when the channel is not valid. None
References XAxiVdma_GetChannel.
int XAxiVdma_ClearDmaChannelErrors(XAxiVdma *InstancePtr, u16 Direction, u32 ErrorMask)
Clear DMA Channel Errors.
InstancePtr is the XAxiVdma instance to operate on Direction is the channel to work on, use XAXIVDMA_READ/WRITE ErrorMask is the mask of error bits to clear - XST_SUCCESS, when error bits are cleared. XST_INVALID_PARAM, when channel pointer is invalid.XST_DEVICE_NOT_FOUND, when the channel is not valid. None
References XAxiVdma_GetChannel.
int XAxiVdma_MaskS2MMErrIntr(XAxiVdma *InstancePtr, u32 ErrorMask, u16 Direction)
Masks the S2MM error interrupt for the provided error mask value.
InstancePtr is the XAxiVdma instance to operate on ErrorMask is the mask of error bits for which S2MM error interrupt can be disabled. Direction is the channel to work on, use XAXIVDMA_READ/WRITE - XST_SUCCESS, when error bits are cleared. XST_INVALID_PARAM, when channel pointer is invalid.XST_DEVICE_NOT_FOUND, when the channel is not valid. The register S2MM_DMA_IRQ_MASK is only applicable from IPv6.01a which is added at offset XAXIVDMA_S2MM_DMA_IRQ_MASK_OFFSET. For older versions, this offset location is reserved and so the API does not have any effect.
References XAxiVdma_GetChannel, XAXIVDMA_S2MM_DMA_IRQ_MASK_OFFSET, XAXIVDMA_S2MM_IRQ_ERR_ALL_MASK, XAXIVDMA_WRITE, XAxiVdma_WriteReg.
int XAxiVdma_StartWriteFrame(XAxiVdma *InstancePtr, XAxiVdma_DmaSetup *DmaConfigPtr)
Start a write operation.
Write corresponds to send data from device to memory InstancePtr is the pointer to the DMA engine to work on DmaConfigPtr is the pointer to the setup structure XST_SUCCESS for a successful submissionXST_DEVICE_BUSY if the DMA channel is not idle, BDs are still being usedXST_INVAID_PARAM if parameters in config structure not validXST_DEVICE_NOT_FOUND if the channel is invalid
References XAxiVdma_ChannelStartTransfer, XAxiVdma_GetChannel, XAXIVDMA_WRITE.
int XAxiVdma_StartReadFrame(XAxiVdma *InstancePtr, XAxiVdma_DmaSetup *DmaConfigPtr)
Start a read operation.
Read corresponds to send data from memory to device InstancePtr is the pointer to the DMA engine to work on DmaConfigPtr is the pointer to the setup structure XST_SUCCESS for a successful submissionXST_DEVICE_BUSY if the DMA channel is not idle, BDs are still being usedXST_INVAID_PARAM if parameters in config structure not validXST_DEVICE_NOT_FOUND if the channel is invalid
References XAxiVdma_ChannelStartTransfer, XAxiVdma_GetChannel, XAXIVDMA_READ.
int XAxiVdma_DmaConfig(XAxiVdma *InstancePtr, u16 Direction, XAxiVdma_DmaSetup *DmaConfigPtr)
Configure one DMA channel using the configuration structure.
InstancePtr is the pointer to the DMA engine to work on Direction is the DMA channel to work on DmaConfigPtr is the pointer to the setup structure XST_SUCCESS if successfulXST_DEVICE_BUSY if the DMA channel is not idle, BDs are still being usedXST_INVAID_PARAM if buffer address not valid, for example, unaligned address with no DRE built in the hardware, or Direction invalidXST_DEVICE_NOT_FOUND if the channel is invalid
References XAxiVdma_ChannelConfig, XAxiVdma_GetChannel.
int XAxiVdma_DmaSetBufferAddr(XAxiVdma *InstancePtr, u16 Direction, UINTPTR *BufferAddrSet)
Configure buffer addresses for one DMA channel.
InstancePtr is the pointer to the DMA engine to work on Direction is the DMA channel to work on BufferAddrSet is the set of addresses for the transfers XST_SUCCESS if successfulXST_DEVICE_BUSY if the DMA channel is not idle, BDs are still being usedXST_INVAID_PARAM if buffer address not valid, for example, unaligned address with no DRE built in the hardware, or Direction invalidXST_DEVICE_NOT_FOUND if the channel is invalid
References XAxiVdma_ChannelSetBufferAddr, XAxiVdma_GetChannel.
int XAxiVdma_DmaStart(XAxiVdma *InstancePtr, u16 Direction)
Start one DMA channel.
InstancePtr is the pointer to the DMA engine to work on Direction is the DMA channel to work on XST_SUCCESS if channel started successfullyXST_FAILURE otherwiseXST_DEVICE_NOT_FOUND if the channel is invalidXST_INVALID_PARAM if Direction invalid
References XAxiVdma_ChannelStart, XAxiVdma_GetChannel.
void XAxiVdma_DmaStop(XAxiVdma *InstancePtr, u16 Direction)
Stop one DMA channel.
InstancePtr is the pointer to the DMA engine to work on Direction is the DMA channel to work on None If channel is invalid, then do nothing on that channel
References XAxiVdma_ChannelStop, XAxiVdma_GetChannel.
void XAxiVdma_DmaRegisterDump(XAxiVdma *InstancePtr, u16 Direction)
Dump registers of one DMA channel.
InstancePtr is the pointer to the DMA engine to work on Direction is the DMA channel to work on None If channel is invalid, then do nothing on that channel
References XAxiVdma_ChannelRegisterDump, XAxiVdma_GetChannel.
int XAxiVdma_SetFrameCounter(XAxiVdma *InstancePtr, XAxiVdma_FrameCounter *CfgPtr)
Set the frame counter and delay counter for both channels.
InstancePtr is the pointer to the DMA engine to work on CfgPtr is the pointer to the configuration structure XST_SUCCESS if setup finishes successfullyXST_INVALID_PARAM if the configuration structure has invalid valuesOthers if setting channel frame counter fails If channel is invalid, then do nothing on that channel
References XAxiVdma::IsReady, XAxiVdma_FrameCounter::ReadDelayTimerCount, XAxiVdma_FrameCounter::ReadFrameCount, XAxiVdma_FrameCounter::WriteDelayTimerCount, XAxiVdma_FrameCounter::WriteFrameCount, XAxiVdma_ChannelSetFrmCnt, XAXIVDMA_DEVICE_READY, XAxiVdma_GetChannel, XAXIVDMA_READ, XAXIVDMA_WRITE.
Referenced by main, run_triple_frame_buffer.
void XAxiVdma_GetFrameCounter(XAxiVdma *InstancePtr, XAxiVdma_FrameCounter *CfgPtr)
Get the frame counter and delay counter for both channels.
InstancePtr is the pointer to the DMA engine to work on CfgPtr is the configuration structure to contain return values None If returned frame counter value is 0, then the channel is not valid
References XAxiVdma::IsReady, XAxiVdma_FrameCounter::ReadDelayTimerCount, XAxiVdma_FrameCounter::ReadFrameCount, XAxiVdma_FrameCounter::WriteDelayTimerCount, XAxiVdma_FrameCounter::WriteFrameCount, XAxiVdma_ChannelGetFrmCnt, XAXIVDMA_DEVICE_READY, XAxiVdma_GetChannel, XAXIVDMA_READ, XAXIVDMA_WRITE.
void XAxiVdma_ReadIntrHandler(void *InstancePtr)
Interrupt handler for the read channel.
InstancePtr is the pointer to the DMA engine to work on None If the channel is invalid, then no interrupt handling
References XAxiVdma_ChannelCallBack::CompletionCallBack, XAxiVdma_ChannelCallBack::CompletionRef, XAxiVdma_ChannelCallBack::ErrCallBack, XAxiVdma_ChannelCallBack::ErrRef, XAxiVdma::ReadCallBack, XAxiVdma_ChannelGetEnabledIntr, XAxiVdma_ChannelGetPendingIntr, XAxiVdma_ChannelIntrClear, XAxiVdma_GetChannel, XAXIVDMA_IXR_COMPLETION_MASK, XAXIVDMA_IXR_ERROR_MASK, XAXIVDMA_READ.
Referenced by main.
void XAxiVdma_WriteIntrHandler(void *InstancePtr)
Interrupt handler for the write channel.
InstancePtr is the pointer to the DMA engine to work on None If the channel is invalid, then no interrupt handling
References XAxiVdma_ChannelCallBack::CompletionCallBack, XAxiVdma_ChannelCallBack::CompletionRef, XAxiVdma_ChannelCallBack::ErrCallBack, XAxiVdma_ChannelCallBack::ErrRef, XAxiVdma::WriteCallBack, XAxiVdma_ChannelGetEnabledIntr, XAxiVdma_ChannelGetPendingIntr, XAxiVdma_ChannelIntrClear, XAxiVdma_GetChannel, XAXIVDMA_IXR_COMPLETION_MASK, XAXIVDMA_IXR_ERROR_MASK, XAXIVDMA_WRITE.
Referenced by main.
int XAxiVdma_SetCallBack(XAxiVdma *InstancePtr, u32 HandlerType, void *CallBackFunc, void *CallBackRef, u16 Direction)
Set call back function and call back reference pointer for one channel.
InstancePtr is the pointer to the DMA engine to work on HandlerType is the interrupt type that this callback handles CallBackFunc is the call back function pointer CallBackRef is the call back reference pointer Direction is the DMA channel, use XAXIVDMA_READ or XAXIVDMA_WRITE XST_SUCCESS if everything is fineXST_INVALID_PARAM if the handler type or direction invalid This function overwrites the existing interrupt handler and its reference pointer. The function sets the handlers even if the channels are invalid.
References XAxiVdma_ChannelCallBack::CompletionCallBack, XAxiVdma_ChannelCallBack::CompletionRef, XAxiVdma_ChannelCallBack::ErrCallBack, XAxiVdma_ChannelCallBack::ErrRef, XAxiVdma::IsReady, XAxiVdma::ReadCallBack, XAxiVdma::WriteCallBack, XAXIVDMA_DEVICE_READY, XAXIVDMA_HANDLER_ERROR, XAXIVDMA_HANDLER_GENERAL, XAXIVDMA_READ.
Referenced by main.
int XAxiVdma_Selftest(XAxiVdma *InstancePtr)
Runs a self-test on the driver/device.
This test perform a reset of the VDMA device and checks the device is coming out of reset or not InstancePtr is a pointer to the XAxiVdma instance. XST_SUCCESS if self-test was successful XST_FAILURE if the device is not coming out of reset. None.
References XAxiVdma::BaseAddr, XAxiVdma::HasMm2S, XAxiVdma::HasS2Mm, XAxiVdma_ChannelReset, XAxiVdma_ChannelResetNotDone, XAxiVdma_GetChannel, XAXIVDMA_READ, XAXIVDMA_RX_OFFSET, XAXIVDMA_TX_OFFSET, XAXIVDMA_WRITE.
Referenced by AxiVDMASelfTestExample.