xaxivdma_intr.c
void XAxiVdma_IntrEnable(XAxiVdma *InstancePtr, u32 IntrType, u16 Direction)
Enable specific interrupts for a channel.
Interrupts not specified by the mask will not be affected InstancePtr is the pointer to the DMA engine to work on Direction is the DMA channel, use XAXIVDMA_READ or XAXIVDMA_WRITE IntrType is the bit mask for the interrupts to be enabled None If channel is invalid, then nothing is done
References XAxiVdma_ChannelEnableIntr, XAxiVdma_GetChannel.
Referenced by main, run_triple_frame_buffer.
void XAxiVdma_IntrDisable(XAxiVdma *InstancePtr, u32 IntrType, u16 Direction)
Disable specific interrupts for a channel.
Interrupts not specified by the mask will not be affected InstancePtr is the pointer to the DMA engine to work on IntrType is the bit mask for the interrupts to be disabled Direction is the DMA channel, use XAXIVDMA_READ or XAXIVDMA_WRITE None If channel is invalid, then nothing is done
References XAxiVdma_ChannelDisableIntr, XAxiVdma_GetChannel.
u32 XAxiVdma_IntrGetPending(XAxiVdma *InstancePtr, u16 Direction)
Get the pending interrupts of a channel.
InstancePtr is the pointer to the DMA engine to work on Direction is the DMA channel, use XAXIVDMA_READ or XAXIVDMA_WRITE The bit mask for the currently pending interrupts If Direction is invalid, return 0
References XAxiVdma_ChannelGetPendingIntr, XAxiVdma_GetChannel.
void XAxiVdma_IntrClear(XAxiVdma *InstancePtr, u32 IntrType, u16 Direction)
Clear the pending interrupts specified by the bit mask.
Interrupts not specified by the mask will not be affected InstancePtr is the pointer to the DMA engine to work on Direction is the DMA channel, use XAXIVDMA_READ or XAXIVDMA_WRITE IntrType is the bit mask for the interrupts to be cleared None If channel is invalid, then nothing is done
References XAxiVdma_ChannelIntrClear, XAxiVdma_GetChannel.
int XAxiVdma_MaskS2MMErrIntr(XAxiVdma *InstancePtr, u32 ErrorMask, u16 Direction)
Masks the S2MM error interrupt for the provided error mask value.
InstancePtr is the XAxiVdma instance to operate on ErrorMask is the mask of error bits for which S2MM error interrupt can be disabled. Direction is the channel to work on, use XAXIVDMA_READ/WRITE - XST_SUCCESS, when error bits are cleared. XST_INVALID_PARAM, when channel pointer is invalid.XST_DEVICE_NOT_FOUND, when the channel is not valid. The register S2MM_DMA_IRQ_MASK is only applicable from IPv6.01a which is added at offset XAXIVDMA_S2MM_DMA_IRQ_MASK_OFFSET. For older versions, this offset location is reserved and so the API does not have any effect.
References XAxiVdma_GetChannel, XAXIVDMA_S2MM_DMA_IRQ_MASK_OFFSET, XAXIVDMA_S2MM_IRQ_ERR_ALL_MASK, XAXIVDMA_WRITE, XAxiVdma_WriteReg.
void XAxiVdma_ReadIntrHandler(void *InstancePtr)
Interrupt handler for the read channel.
InstancePtr is the pointer to the DMA engine to work on None If the channel is invalid, then no interrupt handling
References XAxiVdma_ChannelCallBack::CompletionCallBack, XAxiVdma_ChannelCallBack::CompletionRef, XAxiVdma_ChannelCallBack::ErrCallBack, XAxiVdma_ChannelCallBack::ErrRef, XAxiVdma::ReadCallBack, XAxiVdma_ChannelGetEnabledIntr, XAxiVdma_ChannelGetPendingIntr, XAxiVdma_ChannelIntrClear, XAxiVdma_GetChannel, XAXIVDMA_IXR_COMPLETION_MASK, XAXIVDMA_IXR_ERROR_MASK, XAXIVDMA_READ.
Referenced by main.
void XAxiVdma_WriteIntrHandler(void *InstancePtr)
Interrupt handler for the write channel.
InstancePtr is the pointer to the DMA engine to work on None If the channel is invalid, then no interrupt handling
References XAxiVdma_ChannelCallBack::CompletionCallBack, XAxiVdma_ChannelCallBack::CompletionRef, XAxiVdma_ChannelCallBack::ErrCallBack, XAxiVdma_ChannelCallBack::ErrRef, XAxiVdma::WriteCallBack, XAxiVdma_ChannelGetEnabledIntr, XAxiVdma_ChannelGetPendingIntr, XAxiVdma_ChannelIntrClear, XAxiVdma_GetChannel, XAXIVDMA_IXR_COMPLETION_MASK, XAXIVDMA_IXR_ERROR_MASK, XAXIVDMA_WRITE.
Referenced by main.
int XAxiVdma_SetCallBack(XAxiVdma *InstancePtr, u32 HandlerType, void *CallBackFunc, void *CallBackRef, u16 Direction)
Set call back function and call back reference pointer for one channel.
InstancePtr is the pointer to the DMA engine to work on HandlerType is the interrupt type that this callback handles CallBackFunc is the call back function pointer CallBackRef is the call back reference pointer Direction is the DMA channel, use XAXIVDMA_READ or XAXIVDMA_WRITE XST_SUCCESS if everything is fineXST_INVALID_PARAM if the handler type or direction invalid This function overwrites the existing interrupt handler and its reference pointer. The function sets the handlers even if the channels are invalid.
References XAxiVdma_ChannelCallBack::CompletionCallBack, XAxiVdma_ChannelCallBack::CompletionRef, XAxiVdma_ChannelCallBack::ErrCallBack, XAxiVdma_ChannelCallBack::ErrRef, XAxiVdma::IsReady, XAxiVdma::ReadCallBack, XAxiVdma::WriteCallBack, XAXIVDMA_DEVICE_READY, XAXIVDMA_HANDLER_ERROR, XAXIVDMA_HANDLER_GENERAL, XAXIVDMA_READ.
Referenced by main.