xaxivdma_channel.c
XAXIVDMA_RESET_POLLING
XAXIVDMA_VIRT_TO_PHYS
XAxiVdma_ChannelHiFrmAddrEnable
Set the channel to enable access to higher Frame Buffer Addresses (SG=0)
Channel is the pointer to the channel to work on
Referenced by XAxiVdma_ChannelSetBufferAddr.
XAxiVdma_ChannelHiFrmAddrDisable
Set the channel to disable access higher Frame Buffer Addresses (SG=0)
Channel is the pointer to the channel to work on
Referenced by XAxiVdma_ChannelSetBufferAddr.
static u32 XAxiVdma_BdRead(XAxiVdma_Bd *BdPtr, int Offset)
static void XAxiVdma_BdWrite(XAxiVdma_Bd *BdPtr, int Offset, u32 Value)
static void XAxiVdma_BdSetNextPtr(XAxiVdma_Bd *BdPtr, u32 NextPtr)
static void XAxiVdma_BdSetAddr(XAxiVdma_Bd *BdPtr, u32 Addr)
static int XAxiVdma_BdSetVsize(XAxiVdma_Bd *BdPtr, int Vsize)
static int XAxiVdma_BdSetHsize(XAxiVdma_Bd *BdPtr, int Vsize)
static int XAxiVdma_BdSetStride(XAxiVdma_Bd *BdPtr, int Stride)
static int XAxiVdma_BdSetFrmDly(XAxiVdma_Bd *BdPtr, int FrmDly)
void XAxiVdma_ChannelInit(XAxiVdma_Channel *Channel)
Initialize a channel of a DMA engine.
This function initializes the BD ring for this channel Channel is the pointer to the DMA channel to work on None
Referenced by XAxiVdma_CfgInitialize, XAxiVdma_SetFrmStore.
int XAxiVdma_ChannelResetNotDone(XAxiVdma_Channel *Channel)
This function checks whether reset operation is done.
Channel is the pointer to the DMA channel to work on 0 if reset is done1 if reset is still going
References XAXIVDMA_CR_OFFSET, XAXIVDMA_CR_RESET_MASK, XAxiVdma_ReadReg.
Referenced by XAxiVdma_CfgInitialize, XAxiVdma_ResetNotDone, XAxiVdma_Selftest.
void XAxiVdma_ChannelReset(XAxiVdma_Channel *Channel)
This function resets one DMA channel.
The registers will be default values after the reset Channel is the pointer to the DMA channel to work on None
References XAXIVDMA_CR_OFFSET, XAXIVDMA_CR_RESET_MASK, XAxiVdma_WriteReg.
Referenced by XAxiVdma_CfgInitialize, XAxiVdma_Reset, XAxiVdma_Selftest.
int XAxiVdma_ChannelIsRunning(XAxiVdma_Channel *Channel)
int XAxiVdma_ChannelIsBusy(XAxiVdma_Channel *Channel)
Check whether a DMA channel is busy.
Channel is the pointer to the channel to work on non zero if the channel is busy0 is the channel is idle
References XAxiVdma_ReadReg, XAXIVDMA_SR_HALTED_MASK, XAXIVDMA_SR_IDLE_MASK, XAXIVDMA_SR_OFFSET.
Referenced by XAxiVdma_ChannelConfig, XAxiVdma_ChannelSetBdAddrs, XAxiVdma_ChannelStart, XAxiVdma_ChannelStartTransfer, XAxiVdma_IsBusy.
u32 XAxiVdma_ChannelErrors(XAxiVdma_Channel *Channel)
void XAxiVdma_ClearChannelErrors(XAxiVdma_Channel *Channel, u32 ErrorMask)
u32 XAxiVdma_ChannelGetStatus(XAxiVdma_Channel *Channel)
Get the current status of a channel.
Channel is the pointer to the channel to work on The status of the channel
References XAxiVdma_ReadReg, XAXIVDMA_SR_OFFSET.
Referenced by XAxiVdma_CfgInitialize, XAxiVdma_GetStatus.
int XAxiVdma_ChannelStartParking(XAxiVdma_Channel *Channel)
Set the channel to run in parking mode.
Channel is the pointer to the channel to work on XST_SUCCESS if everything is fineXST_FAILURE if hardware is not running
References XAXIVDMA_CR_OFFSET, XAXIVDMA_CR_TAIL_EN_MASK, XAxiVdma_ReadReg, XAxiVdma_WriteReg.
Referenced by XAxiVdma_StartParking.
void XAxiVdma_ChannelStopParking(XAxiVdma_Channel *Channel)
Set the channel to run in circular mode, exiting parking mode.
Channel is the pointer to the channel to work on None
References XAXIVDMA_CR_OFFSET, XAXIVDMA_CR_TAIL_EN_MASK, XAxiVdma_ReadReg, XAxiVdma_WriteReg.
Referenced by XAxiVdma_StopParking.
void XAxiVdma_ChannelStartFrmCntEnable(XAxiVdma_Channel *Channel)
Set the channel to run in frame count enable mode.
Channel is the pointer to the channel to work on None
References XAXIVDMA_CR_FRMCNT_EN_MASK, XAXIVDMA_CR_OFFSET, XAxiVdma_ReadReg, XAxiVdma_WriteReg.
Referenced by XAxiVdma_StartFrmCntEnable.
int XAxiVdma_ChannelSetBdAddrs(XAxiVdma_Channel *Channel, UINTPTR BdAddrPhys, UINTPTR BdAddrVirt)
Setup BD addresses to a different memory region.
In some systems, it is convenient to put BDs into a certain region of the memory. This function enables that. Channel is the pointer to the channel to work on BdAddrPhys is the physical starting address for BDs BdAddrVirt is the Virtual starting address for BDs. For systems that do not use MMU, then virtual address is the same as physical address XST_SUCCESS for a successful setupXST_DEVICE_BUSY if the DMA channel is not idle, BDs are still being used We assume that the memory region starting from BdAddrPhys is large enough to hold all the BDs.
References XAxiVdma_ChannelIsBusy.
Referenced by XAxiVdma_SetBdAddrs.
int XAxiVdma_ChannelStartTransfer(XAxiVdma_Channel *Channel, XAxiVdma_ChannelSetup *ChannelCfgPtr)
Start a transfer.
This function setup the DMA engine and start the engine to do the transfer. Channel is the pointer to the channel to work on ChannelCfgPtr is the pointer to the setup structure XST_SUCCESS for a successful submissionXST_FAILURE if channel has not being initializedXST_DEVICE_BUSY if the DMA channel is not idle, BDs are still being usedXST_INVAID_PARAM if parameters in config structure not valid
References XAxiVdma_ChannelConfig, XAxiVdma_ChannelIsBusy, XAxiVdma_ChannelSetBufferAddr, XAxiVdma_ChannelStart.
Referenced by XAxiVdma_StartReadFrame, XAxiVdma_StartWriteFrame.
int XAxiVdma_ChannelConfig(XAxiVdma_Channel *Channel, XAxiVdma_ChannelSetup *ChannelCfgPtr)
Configure one DMA channel using the configuration structure.
Setup the control register and BDs, however, BD addresses are not set. Channel is the pointer to the channel to work on ChannelCfgPtr is the pointer to the setup structure XST_SUCCESS if successfulXST_FAILURE if channel has not being initializedXST_DEVICE_BUSY if the DMA channel is not idleXST_INVALID_PARAM if fields in ChannelCfgPtr is not valid
References XAxiVdma_ChannelIsBusy, XAXIVDMA_CR_FRMCNT_EN_MASK, XAXIVDMA_CR_GENLCK_RPT_MASK, XAXIVDMA_CR_OFFSET, XAXIVDMA_CR_RD_PTR_MASK, XAXIVDMA_CR_RD_PTR_SHIFT, XAXIVDMA_CR_SYNC_EN_MASK, XAXIVDMA_CR_TAIL_EN_MASK, XAXIVDMA_FRM_MAX, XAXIVDMA_FRMDLY_MAX, XAXIVDMA_FRMDLY_SHIFT, XAXIVDMA_GENLOCK_MASTER, XAXIVDMA_HSIZE_OFFSET, XAXIVDMA_PARKPTR_OFFSET, XAXIVDMA_PARKPTR_READREF_MASK, XAXIVDMA_PARKPTR_WRTREF_MASK, XAxiVdma_ReadReg, XAXIVDMA_STRD_FRMDLY_OFFSET, XAXIVDMA_VFLIP_EN_MASK, XAXIVDMA_VFLIP_OFFSET, XAXIVDMA_WRITE, XAxiVdma_WriteReg.
Referenced by XAxiVdma_ChannelStartTransfer, XAxiVdma_DmaConfig.
int XAxiVdma_ChannelSetBufferAddr(XAxiVdma_Channel *Channel, UINTPTR *BufferAddrSet, int NumFrames)
Configure buffer addresses for one DMA channel.
The buffer addresses are physical addresses. Access to 32 Frame Buffer Addresses in direct mode is done through XAxiVdma_ChannelHiFrmAddrEnable/Disable Functions. 0 - Access Bank0 Registers (0x5C - 0x98) 1 - Access Bank1 Registers (0x5C - 0x98) Channel is the pointer to the channel to work on BufferAddrSet is the set of addresses for the transfers NumFrames is the number of frames to set the address XST_SUCCESS if successfulXST_FAILURE if channel has not being initializedXST_DEVICE_BUSY if the DMA channel is not idle, BDs are still being usedXST_INVAID_PARAM if buffer address not valid, for example, unaligned address with no DRE built in the hardware
References XAxiVdma_ChannelHiFrmAddrDisable, XAxiVdma_ChannelHiFrmAddrEnable, XAXIVDMA_MAX_FRAMESTORE, XAXIVDMA_MAX_FRAMESTORE_64, XAXIVDMA_START_ADDR_LEN, XAXIVDMA_START_ADDR_MSB_OFFSET, XAXIVDMA_START_ADDR_OFFSET, XAxiVdma_WriteReg.
Referenced by XAxiVdma_ChannelStartTransfer, XAxiVdma_DmaSetBufferAddr.
int XAxiVdma_ChannelStart(XAxiVdma_Channel *Channel)
Start one DMA channel.
Channel is the pointer to the channel to work on XST_SUCCESS if successfulXST_FAILURE if channel is not initializedXST_DMA_ERROR if: . The DMA channel fails to stop . The DMA channel fails to startXST_DEVICE_BUSY is the channel is doing transfers
References XAXIVDMA_CDESC_OFFSET, XAxiVdma_ChannelIsBusy, XAXIVDMA_CR_OFFSET, XAXIVDMA_CR_RUNSTOP_MASK, XAxiVdma_ReadReg, XAXIVDMA_TDESC_OFFSET, XAXIVDMA_VSIZE_OFFSET, XAxiVdma_WriteReg.
Referenced by XAxiVdma_ChannelStartTransfer, XAxiVdma_DmaStart.
void XAxiVdma_ChannelStop(XAxiVdma_Channel *Channel)
Stop one DMA channel.
Channel is the pointer to the channel to work on None
References XAXIVDMA_CR_OFFSET, XAXIVDMA_CR_RUNSTOP_MASK, XAxiVdma_ReadReg, XAxiVdma_WriteReg.
Referenced by XAxiVdma_DmaStop.
void XAxiVdma_ChannelRegisterDump(XAxiVdma_Channel *Channel)
Dump registers from one DMA channel.
Channel is the pointer to the channel to work on None
References XAXIVDMA_CDESC_OFFSET, XAXIVDMA_CR_OFFSET, XAxiVdma_ReadReg, XAXIVDMA_SR_OFFSET, XAXIVDMA_TDESC_OFFSET.
Referenced by XAxiVdma_DmaRegisterDump.
int XAxiVdma_ChannelSetFrmCnt(XAxiVdma_Channel *Channel, u8 FrmCnt, u8 DlyCnt)
Set the frame counter and delay counter for one channel.
Channel is the pointer to the channel to work on FrmCnt is the frame counter value to be set DlyCnt is the delay counter value to be set XST_SUCCESS if setup finishes successfullyXST_FAILURE if channel is not initializedXST_INVALID_PARAM if the configuration structure has invalid valuesXST_NO_FEATURE if Frame Counter or Delay Counter is disabled
References XAXIVDMA_CR_OFFSET, XAXIVDMA_DELAY_MASK, XAXIVDMA_FRMCNT_MASK, XAxiVdma_ReadReg, XAxiVdma_WriteReg.
Referenced by XAxiVdma_SetFrameCounter.
void XAxiVdma_ChannelGetFrmCnt(XAxiVdma_Channel *Channel, u8 *FrmCnt, u8 *DlyCnt)
Get the frame counter and delay counter for both channels.
Channel is the pointer to the channel to work on FrmCnt is the pointer for the returning frame counter value DlyCnt is the pointer for the returning delay counter value None If FrmCnt return as 0, then the channel is not initialized
References XAXIVDMA_CR_OFFSET, XAXIVDMA_DELAY_MASK, XAXIVDMA_FRMCNT_MASK, XAxiVdma_ReadReg.
Referenced by XAxiVdma_GetFrameCounter.
void XAxiVdma_ChannelEnableIntr(XAxiVdma_Channel *Channel, u32 IntrType)
Enable interrupts for a channel.
Interrupts that are not specified by the interrupt mask are not affected. Channel is the pointer to the channel to work on IntrType is the interrupt mask for interrupts to be enabled None.
References XAXIVDMA_CR_OFFSET, XAXIVDMA_IXR_ALL_MASK, XAxiVdma_ReadReg, XAxiVdma_WriteReg.
Referenced by XAxiVdma_IntrEnable.
void XAxiVdma_ChannelDisableIntr(XAxiVdma_Channel *Channel, u32 IntrType)
Disable interrupts for a channel.
Interrupts that are not specified by the interrupt mask are not affected. Channel is the pointer to the channel to work on IntrType is the interrupt mask for interrupts to be disabled None.
References XAXIVDMA_CR_OFFSET, XAXIVDMA_IXR_ALL_MASK, XAxiVdma_ReadReg, XAxiVdma_WriteReg.
Referenced by XAxiVdma_IntrDisable.
u32 XAxiVdma_ChannelGetPendingIntr(XAxiVdma_Channel *Channel)
Get pending interrupts of a channel.
Channel is the pointer to the channel to work on The interrupts mask represents pending interrupts.
References XAXIVDMA_IXR_ALL_MASK, XAxiVdma_ReadReg, XAXIVDMA_SR_OFFSET.
Referenced by XAxiVdma_IntrGetPending, XAxiVdma_ReadIntrHandler, XAxiVdma_WriteIntrHandler.
void XAxiVdma_ChannelIntrClear(XAxiVdma_Channel *Channel, u32 IntrType)
Clear interrupts of a channel.
Interrupts that are not specified by the interrupt mask are not affected. Channel is the pointer to the channel to work on IntrType is the interrupt mask for interrupts to be cleared None.
References XAXIVDMA_IXR_ALL_MASK, XAXIVDMA_SR_OFFSET, XAxiVdma_WriteReg.
Referenced by XAxiVdma_IntrClear, XAxiVdma_ReadIntrHandler, XAxiVdma_WriteIntrHandler.
u32 XAxiVdma_ChannelGetEnabledIntr(XAxiVdma_Channel *Channel)
Get the enabled interrupts of a channel.
Channel is the pointer to the channel to work on The interrupts mask represents pending interrupts.
References XAXIVDMA_CR_OFFSET, XAXIVDMA_IXR_ALL_MASK, XAxiVdma_ReadReg.
Referenced by XAxiVdma_ReadIntrHandler, XAxiVdma_WriteIntrHandler.