xospipsv_flash_intr_example.c
INTC_DEVICE_ID
OSPIPSV_INTR_ID
PAGE_COUNT
MAX_PAGE_SIZE
TEST_ADDRESS
UNIQUE_VALUE
u8 TxBfrPtr
u8 ReadBfrPtr[8][8]
u32 FlashMake
u32 FlashType
u32 FCTIndex
XOspiPsv OspiPsvInstance
XOspiPsv_Msg FlashMsg
volatile int TransferInProgress
int Error
int Test
u8 ReadBuffer[(PAGE_COUNT *MAX_PAGE_SIZE)][(PAGE_COUNT *MAX_PAGE_SIZE)]
u8 WriteBuffer[(PAGE_COUNT *MAX_PAGE_SIZE)][(PAGE_COUNT *MAX_PAGE_SIZE)]
u8 CmdBfr[8][8]
u8 FSRFlag
u32 MaxData
int OspiPsvInterruptFlashExample(XOspiPsv *OspiPsvInstancePtr, UINTPTR BaseAddress)
The purpose of this function is to illustrate how to use the XOspiPsv device driver using OSPI flash devices greater than or equal to 128Mb.
This function reads data in either DMA or DAC mode. OspiPsvInstancePtr is a pointer to the instance of the Ospi device. BaseAddress contains the base address of the device XST_SUCCESS if successful, else XST_FAILURE. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XOspiPsv::Config, XOspiPsv_Config::ConnectionMode, FlashEnterExit4BAddMode, FlashErase, FlashIoWrite, FlashRead, FlashReadID, FlashSetSDRDDRMode, XOspiPsv_Config::IntrId, XOspiPsv_Config::IntrParent, MxConfigDummy, OspiPsvHandler, SpansionSetEccMode, XOspiPsv_CfgInitialize, XOspiPsv_DeviceReset, XOspiPsv_DeviceResetViaOspi, XOSPIPSV_HWPIN_RESET, XOspiPsv_IntrHandler, XOspiPsv_LookupConfig, XOSPIPSV_SELECT_FLASH_CS0, XOspiPsv_SelectFlash, XOspiPsv_SetClkPrescaler, XOspiPsv_SetOptions, XOspiPsv_SetSdrDdrMode, XOspiPsv_SetStatusHandler.
Referenced by main.
void OspiPsvHandler(void *CallBackRef, u32 StatusEvent)
This function setups the interrupt system for a OspiPsv device.
IntcInstancePtr is a pointer to the instance of the Intc device. OspiPsvInstancePtr is a pointer to the instance of the OspiPsv device. XST_SUCCESS if successful, otherwise XST_FAILURE. None. Callback handler. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. StatusEvent is the event that just occurred. None None.
Referenced by OspiPsvInterruptFlashExample.
int FlashReadID(XOspiPsv *OspiPsvPtr)
Reads the flash ID and identifies the flash in FCT table.
OspiPsvPtr is a pointer to the OSPIPSV driver component to use. XST_SUCCESS if successful, else XST_FAILURE. None.
References XOspiPsv_Msg::Addrsize, XOspiPsv_Msg::Addrvalid, XOspiPsv_Msg::ByteCount, XOspiPsv::DeviceIdData, XOspiPsv::DualByteOpcodeEn, XOspiPsv_Msg::Dummy, XOspiPsv_Msg::ExtendedOpcode, XOspiPsv::Extra_DummyCycle, XOspiPsv_Msg::Flags, XOspiPsv_Msg::IsDDROpCode, XOspiPsv_Msg::Opcode, XOspiPsv_Msg::Proto, READ_ID, XOspiPsv_Msg::RxBfrPtr, XOspiPsv::SdrDdrMode, XOspiPsv_Msg::TxBfrPtr, XOspiPsv_IntrTransfer, XOSPIPSV_MSG_FLAG_RX.
Referenced by OspiPsvFlashNonBlockingReadExample, OspiPsvInterruptFlashExample, OspiPsvPolledFlashExample.
int FlashErase(XOspiPsv *OspiPsvPtr, u32 Address, u32 ByteCount, u8 *WriteBfrPtr)
This function erases the sectors in the serial Flash connected to the OSPIPSV interface.
OspiPsvPtr is a pointer to the OSPIPSV driver component to use. Address contains the address of the first sector which needs to be erased. ByteCount contains the total size to be erased. WriteBfrPtr is Pointer to the write buffer (which is to be transmitted) XST_SUCCESS if successful, else XST_FAILURE. None.
References XOspiPsv_Msg::Addr, XOspiPsv_Msg::Addrsize, XOspiPsv_Msg::Addrvalid, BulkErase, XOspiPsv_Msg::ByteCount, XOspiPsv::Config, XOspiPsv_Config::ConnectionMode, DieErase, XOspiPsv::DualByteOpcodeEn, XOspiPsv_Msg::Dummy, XOspiPsv_Msg::ExtendedOpcode, XOspiPsv::Extra_DummyCycle, XOspiPsv_Msg::Flags, GetRealAddr, XOspiPsv_Msg::IsDDROpCode, XOspiPsv_Msg::Opcode, XOspiPsv_Msg::Proto, XOspiPsv_Msg::RxBfrPtr, XOspiPsv::SdrDdrMode, XOspiPsv_Msg::TxBfrPtr, XOspiPsv_IntrTransfer, XOSPIPSV_MSG_FLAG_RX, XOSPIPSV_SELECT_FLASH_CS0, XOspiPsv_SelectFlash.
Referenced by MicronBlockProtectTest, OspiPsvFlashNonBlockingReadExample, OspiPsvInterruptFlashExample, OspiPsvPolledFlashExample.
int FlashIoWrite(XOspiPsv *OspiPsvPtr, u32 Address, u32 ByteCount, u8 *WriteBfrPtr)
This function writes to the serial Flash connected to the OSPIPSV interface.
All the data put into the buffer must be in the same page of the device with page boundaries being on 256 byte boundaries. This can be used in IO or DMA mode. OspiPsvPtr is a pointer to the OSPIPSV driver component to use. Address contains the address to write data to in the Flash. ByteCount contains the number of bytes to write. WriteBfrPtr is Pointer to the write buffer (which is to be transmitted) XST_SUCCESS if successful, else XST_FAILURE. None. All the data put into the buffer must be in the same page of the device with page boundaries being on 256 byte boundaries. This can be used in IO or DMA mode. OspiPsvPtr is a pointer to the OSPIPSV driver component to use. Address contains the address to write data to in the Flash. ByteCount contains the number of bytes to write. WriteBfrPtr Pointer to the write buffer (which is to be transmitted) XST_SUCCESS if successful, else XST_FAILURE. None.
References XOspiPsv_Msg::Addr, XOspiPsv_Msg::Addrsize, XOspiPsv_Msg::Addrvalid, XOspiPsv_Msg::ByteCount, XOspiPsv::DualByteOpcodeEn, XOspiPsv_Msg::Dummy, XOspiPsv_Msg::ExtendedOpcode, XOspiPsv::Extra_DummyCycle, XOspiPsv_Msg::Flags, GetRealAddr, XOspiPsv_Msg::IsDDROpCode, XOspiPsv_Msg::Opcode, XOspiPsv_Msg::Proto, XOspiPsv_Msg::RxBfrPtr, XOspiPsv::SdrDdrMode, XOspiPsv_Msg::TxBfrPtr, XOspiPsv_Get_Proto, XOspiPsv_IntrTransfer, XOSPIPSV_MSG_FLAG_RX.
Referenced by MicronBlockProtectTest, OspiPsvFlashNonBlockingReadExample, OspiPsvInterruptFlashExample, OspiPsvPolledFlashExample.
int FlashLinearWrite(XOspiPsv *OspiPsvPtr, u32 Address, u32 ByteCount, u8 *WriteBfrPtr)
This function writes to the serial Flash connected to the OSPIPSV interface.
All the data put into the buffer must be in the same page of the device with page boundaries being on 256 byte boundaries. This can be used when controller is in Linear mode. OspiPsvPtr is a pointer to the OSPIPSV driver component to use. Address contains the address to write data to in the Flash. ByteCount contains the number of bytes to write. WriteBfrPtr is Pointer to the write buffer (which is to be transmitted) XST_SUCCESS if successful, else XST_FAILURE. None.
References XOspiPsv_Msg::Addr, XOspiPsv_Msg::Addrsize, XOspiPsv_Msg::Addrvalid, XOspiPsv_Msg::ByteCount, XOspiPsv::DualByteOpcodeEn, XOspiPsv_Msg::Dummy, XOspiPsv_Msg::ExtendedOpcode, XOspiPsv_Msg::Flags, XOspiPsv_Msg::IsDDROpCode, XOspiPsv_Msg::Opcode, XOspiPsv_Msg::Proto, XOspiPsv_Msg::RxBfrPtr, XOspiPsv::SdrDdrMode, XOspiPsv_Msg::TxBfrPtr, XOspiPsv_Get_Proto, XOspiPsv_PollTransfer.
Referenced by MicronBlockProtectTest, OspiPsvFlashNonBlockingReadExample, OspiPsvPolledFlashExample.
int FlashRead(XOspiPsv *OspiPsvPtr, u32 Address, u32 ByteCount, u8 *WriteBfrPtr, u8 *ReadBfrPtr)
This function performs read.
DMA is the default setting. OspiPsvPtr is a pointer to the OSPIPSV driver component to use. Address contains the address of the first sector which needs to be erased. ByteCount contains the total size to be erased. WriteBfrPtr is Pointer to the write buffer which contains data to be transmitted ReadBfrPtr isPointer to the read buffer to which valid received data should be written XST_SUCCESS if successful, else XST_FAILURE. None. DMA is the default setting. OspiPsvPtr is a pointer to the OSPIPSV driver component to use. Address contains the address of the first sector which needs to be erased. ByteCount contains the total size to be erased. WriteBfrPtr is Pointer to the write buffer which contains data to be transmitted ReadBfrPtr is Pointer to the read buffer to which valid received data should be written XST_SUCCESS if successful, else XST_FAILURE. None.
References XOspiPsv_Msg::Addr, XOspiPsv_Msg::Addrsize, XOspiPsv_Msg::Addrvalid, XOspiPsv_Msg::ByteCount, XOspiPsv::Config, XOspiPsv_Config::ConnectionMode, XOspiPsv::DualByteOpcodeEn, XOspiPsv_Msg::Dummy, XOspiPsv_Msg::ExtendedOpcode, XOspiPsv::Extra_DummyCycle, XOspiPsv_Msg::Flags, GetRealAddr, XOspiPsv_Msg::IsDDROpCode, XOspiPsv_Msg::Opcode, XOspiPsv_Msg::Proto, XOspiPsv_Msg::RxBfrPtr, XOspiPsv::SdrDdrMode, XOspiPsv_Msg::TxBfrPtr, XOspiPsv_Get_Proto, XOspiPsv_IntrTransfer, XOSPIPSV_MSG_FLAG_RX.
Referenced by MicronBlockProtectTest, OspiPsvFlashNonBlockingReadExample, OspiPsvInterruptFlashExample, OspiPsvPolledFlashExample.
u32 GetRealAddr(XOspiPsv *OspiPsvPtr, u32 Address)
This functions translates the address based on the type of interconnection.
In case of stacked, this function asserts the corresponding slave select. OspiPsvPtr is a pointer to the OSPIPSV driver component to use. Address which is to be accessed (for erase, write or read) RealAddr is the translated address - for single it is unchanged; for stacked, the lower flash size is subtracted; In addition to get the actual address to work on flash this function also selects the CS based on the configuration detected.
References XOspiPsv::Config, XOspiPsv_Config::ConnectionMode, XOSPIPSV_SELECT_FLASH_CS0, XOspiPsv_SelectFlash.
Referenced by FlashErase, FlashIoWrite, FlashRead.
int BulkErase(XOspiPsv *OspiPsvPtr, u8 *WriteBfrPtr)
This functions performs a bulk erase operation when the flash device has a single die.
Works for both Spansion and Micron OspiPsvPtr is a pointer to the OSPIPSV driver component to use. WriteBfrPtr is the pointer to command+address to be sent XST_SUCCESS if successful, else XST_FAILURE. None.
References XOspiPsv_Msg::Addr, XOspiPsv_Msg::Addrsize, XOspiPsv_Msg::Addrvalid, XOspiPsv_Msg::ByteCount, XOspiPsv::DualByteOpcodeEn, XOspiPsv_Msg::Dummy, XOspiPsv_Msg::ExtendedOpcode, XOspiPsv::Extra_DummyCycle, XOspiPsv_Msg::Flags, XOspiPsv_Msg::IsDDROpCode, XOspiPsv_Msg::Opcode, XOspiPsv_Msg::Proto, XOspiPsv_Msg::RxBfrPtr, XOspiPsv::SdrDdrMode, XOspiPsv_Msg::TxBfrPtr, XOspiPsv_IntrTransfer, XOSPIPSV_MSG_FLAG_RX.
Referenced by FlashErase.
int DieErase(XOspiPsv *OspiPsvPtr, u8 *WriteBfrPtr)
This functions performs a die erase operation on all the die in the flash device.
This function uses the die erase command for Micron 512Mbit and 1Gbit OspiPsvPtr is a pointer to the OSPIPSV driver component to use. WriteBfrPtr is the pointer to command+address to be sent XST_SUCCESS if successful, else XST_FAILURE. None.
References XOspiPsv_Msg::Addrsize, XOspiPsv_Msg::Addrvalid, XOspiPsv_Msg::ByteCount, XOspiPsv::DualByteOpcodeEn, XOspiPsv_Msg::Dummy, XOspiPsv_Msg::ExtendedOpcode, XOspiPsv::Extra_DummyCycle, XOspiPsv_Msg::Flags, XOspiPsv_Msg::IsDDROpCode, XOspiPsv_Msg::Opcode, XOspiPsv_Msg::Proto, XOspiPsv_Msg::RxBfrPtr, XOspiPsv::SdrDdrMode, XOspiPsv_Msg::TxBfrPtr, XOspiPsv_IntrTransfer, XOSPIPSV_MSG_FLAG_RX.
Referenced by FlashErase.
int FlashRegisterRead(XOspiPsv *OspiPsvPtr, u32 ByteCount, u8 Command, u8 *ReadBfrPtr)
int FlashRegisterWrite(XOspiPsv *OspiPsvPtr, u32 ByteCount, u8 Command, u8 *WriteBfrPtr, u8 WrEn)
s32 InitCmd(XOspiPsv *OspiPsvInstancePtr)
int FlashEnterExit4BAddMode(XOspiPsv *OspiPsvPtr, int Enable)
This API enters the flash device into 4 bytes addressing mode.
As per the Micron spec, before issuing the command to enter into 4 byte addr mode, a write enable command is issued. OspiPsvPtr is a pointer to the OSPIPSV driver component to use. Enable is a either 1 or 0 if 1 then enters 4 byte if 0 exits. - XST_SUCCESS if successful. XST_FAILURE if it fails.
References XOspiPsv_Msg::Addrsize, XOspiPsv_Msg::Addrvalid, XOspiPsv_Msg::ByteCount, XOspiPsv::DualByteOpcodeEn, XOspiPsv_Msg::Dummy, XOspiPsv_Msg::ExtendedOpcode, XOspiPsv::Extra_DummyCycle, XOspiPsv_Msg::Flags, XOspiPsv_Msg::IsDDROpCode, XOspiPsv_Msg::Opcode, XOspiPsv_Msg::Proto, XOspiPsv_Msg::RxBfrPtr, XOspiPsv::SdrDdrMode, XOspiPsv_Msg::TxBfrPtr, XOspiPsv_IntrTransfer, XOSPIPSV_MSG_FLAG_RX.
Referenced by OspiPsvFlashNonBlockingReadExample, OspiPsvInterruptFlashExample, OspiPsvPolledFlashExample.
int FlashSetSDRDDRMode(XOspiPsv *OspiPsvPtr, int Mode)
This API enters the flash device into Octal DDR mode or exit from octal DDR mode (switches to Extended SPI mode).
OspiPsvPtr is a pointer to the OSPIPSV driver component to use. Mode is either 1 or 0 if 1 then enter octal DDR mode if 0 exits. - XST_SUCCESS if successful. XST_FAILURE if it fails.
References XOspiPsv_Msg::Addr, XOspiPsv_Msg::Addrsize, XOspiPsv_Msg::Addrvalid, XOspiPsv_Msg::ByteCount, XOspiPsv::Config, XOspiPsv::DeviceIdData, XOspiPsv::DualByteOpcodeEn, XOspiPsv_Msg::Dummy, XOspiPsv_Msg::ExtendedOpcode, XOspiPsv::Extra_DummyCycle, XOspiPsv_Msg::Flags, XOspiPsv_Config::IntrId, XOspiPsv_Config::IntrParent, XOspiPsv_Msg::IsDDROpCode, XOspiPsv_Msg::Opcode, XOspiPsv::OpMode, XOspiPsv_Msg::Proto, XOspiPsv_Msg::RxBfrPtr, XOspiPsv::SdrDdrMode, XOspiPsv_Msg::TxBfrPtr, XOspiPsv_ConfigDualByteOpcode, XOspiPsv_ConfigureAutoPolling, XOSPIPSV_DAC_EN_OPTION, XOSPIPSV_DUAL_BYTE_OP_DISABLE, XOspiPsv_IntrTransfer, XOSPIPSV_MSG_FLAG_RX, XOspiPsv_SetSdrDdrMode.
Referenced by OspiPsvFlashNonBlockingReadExample, OspiPsvInterruptFlashExample, OspiPsvPolledFlashExample.
int SpansionSetEccMode(XOspiPsv *OspiPsvPtr)
This function configures the ECC mode in Flash device.
In some flashes by default 2-bit ECC is enabled, which prevents byte-programming( <16-Bytes). This function enables byte-programming by setting the ECC configuration to 1-bit error detection/correction. OspiPsvPtr is a pointer to the OSPIPSV driver component to use. XST_SUCCESS or XST_FAILURE. This function is specific to some spansion flashes(S28HS02GT).
References XOspiPsv_Msg::Addr, XOspiPsv_Msg::Addrsize, XOspiPsv_Msg::Addrvalid, XOspiPsv_Msg::ByteCount, XOspiPsv::DualByteOpcodeEn, XOspiPsv_Msg::Dummy, XOspiPsv_Msg::ExtendedOpcode, XOspiPsv::Extra_DummyCycle, XOspiPsv_Msg::Flags, XOspiPsv_Msg::IsDDROpCode, XOspiPsv_Msg::Opcode, XOspiPsv_Msg::Proto, XOspiPsv_Msg::RxBfrPtr, XOspiPsv::SdrDdrMode, XOspiPsv_Msg::TxBfrPtr, XOspiPsv_IntrTransfer, XOSPIPSV_MSG_FLAG_RX.
Referenced by OspiPsvFlashNonBlockingReadExample, OspiPsvInterruptFlashExample, OspiPsvPolledFlashExample.
int MxConfigDummy(XOspiPsv *OspiPsvPtr)
This function configures the Dummy cycles in Flash device.
OspiPsvPtr is a pointer to the OSPIPSV driver component to use. XST_SUCCESS or XST_FAILURE.
References XOspiPsv_Msg::Addr, XOspiPsv_Msg::Addrsize, XOspiPsv_Msg::Addrvalid, XOspiPsv_Msg::ByteCount, XOspiPsv::DualByteOpcodeEn, XOspiPsv_Msg::Dummy, XOspiPsv_Msg::ExtendedOpcode, XOspiPsv::Extra_DummyCycle, XOspiPsv_Msg::Flags, XOspiPsv_Msg::IsDDROpCode, XOspiPsv_Msg::Opcode, XOspiPsv_Msg::Proto, XOspiPsv_Msg::RxBfrPtr, XOspiPsv::SdrDdrMode, XOspiPsv_Msg::TxBfrPtr, XOspiPsv_IntrTransfer, XOSPIPSV_MSG_FLAG_RX.
Referenced by OspiPsvFlashNonBlockingReadExample, OspiPsvInterruptFlashExample, OspiPsvPolledFlashExample.
int main(void)
Main function to call the OSPIPSV Flash Interrupt example.
XST_SUCCESS if successful, otherwise XST_FAILURE. None
References OspiPsvInterruptFlashExample.
u32 XOspiPsv_Get_Proto(XOspiPsv *OspiPsvInstancePtr, int Read)
The purpose of this function is to determine the number of lines used for command, address and data.
OspiPsvInstancePtr is a pointer to the OSPIPSV driver component to use. Read is to tell whether a read or write returns value to program the lines for command, address and data. None.
References XOspiPsv::OpMode, XOSPIPSV_IDAC_MODE, XOSPIPSV_READ_1_1_1.
Referenced by FlashIoWrite, FlashLinearWrite, FlashRead.