xospipsv_options.c
XOSPIPSV_NUM_OPTIONS
Total number of configuration options.
Referenced by XOspiPsv_GetOptions, XOspiPsv_SetOptions.
OptionsMap OptionsTable[][]
u32 XOspiPsv_SetOptions(XOspiPsv *InstancePtr, u32 Options)
Sets the options for the OSPIPSV device driver.The options control how the device behaves relative to the OSPIPSV bus.
The device must be idle rather than busy transferring data before setting these device options. InstancePtr Pointer to the XOspiPsv instance. Options Contains the specified options to be set. This is a bit mask where a 1 indicates the option should be turned ON and a 0 indicates no action. One or more bit Values may be contained in the mask. See the bit definitions named XOSPIPSV_*_OPTIONS in the file xospipsv.h. XST_SUCCESS if options are successfully set.XST_DEVICE_BUSY if the device is currently transferring data. The transfer must complete or be aborted before setting options. This function is not thread-safe.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv::IsBusy, XOspiPsv::IsReady, XOspiPsv::OpMode, XOSPIPSV_DAC_EN_OPTION, XOSPIPSV_IDAC_MODE, XOSPIPSV_NUM_OPTIONS, XOspiPsv_ReadReg.
Referenced by OspiPsvFlashNonBlockingReadExample, OspiPsvInterruptFlashExample, OspiPsvPolledFlashExample.
u32 XOspiPsv_GetOptions(const XOspiPsv *InstancePtr)
Gets the options for the OSPIPSV device.
The options control how the device behaves relative to the OSPIPSV bus. InstancePtr Pointer to the XOspiPsv instance. Options contains the specified options currently set. This is a bit Value where a 1 means the option is on, and a 0 means the option is off. See the bit definitions named XOSPIPSV_*_OPTIONS in file xospipsv.h.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv::IsReady, XOSPIPSV_NUM_OPTIONS, XOspiPsv_ReadReg.
Referenced by MicronBlockProtectTest, OspiPsvFlashNonBlockingReadExample, OspiPsvPolledFlashExample.
u32 XOspiPsv_SetClkPrescaler(XOspiPsv *InstancePtr, u8 Prescaler)
Configures the clock according to the prescaler passed.
InstancePtr Pointer to the XOspiPsv instance. Prescaler Clock prescaler to be set. XST_SUCCESS if successful. XST_FAILURE if failed to set prescaler. XST_DEVICE_IS_STARTED if the device is already started.XST_DEVICE_BUSY if the device is currently transferring data. It must be stopped to re-initialize.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv::IsBusy, XOspiPsv::IsReady, XOspiPsv::SdrDdrMode, XOSPIPSV_CLK_PRESCALE_2, XOspiPsv_ReadReg, XOspiPsv_SetDllDelay.
Referenced by OspiPsvFlashNonBlockingReadExample, OspiPsvInterruptFlashExample, OspiPsvPolledFlashExample.
u32 XOspiPsv_SetSdrDdrMode(XOspiPsv *InstancePtr, u32 Mode)
Configures the edge mode (SDR or DDR).
InstancePtr Pointer to the XOspiPsv instance. Mode Edge mode. XOSPIPSV_EDGE_MODE_* represents valid values. XST_SUCCESS if successful.XST_FAILURE if fail to set.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv::SdrDdrMode, XOSPIPSV_EDGE_MODE_SDR_PHY, XOspiPsv_ReadReg, XOspiPsv_SetDllDelay.
Referenced by FlashSetSDRDDRMode, OspiPsvFlashNonBlockingReadExample, OspiPsvInterruptFlashExample, OspiPsvPolledFlashExample, XOspiPsv_CfgInitialize.
u32 XOspiPsv_SelectFlash(XOspiPsv *InstancePtr, u8 chip_select)
Used to signify the OSPIPSV driver that the Hardware flash configuration being used.
This API should be called at least once in the application. If desired, it can be called multiple times when switching between communicating to different flash devices/using different configuration. InstancePtr Pointer to the XOspiPsv instance. chip_select Flash Chip Select. XST_SUCCESS if successful.XST_DEVICE_IS_STARTED if the device is already started. It must be stopped to re-initialize. If this function is not called at least once in the application, the driver assumes there is a single flash connected to the lower bus and CS line.
References XOspiPsv::ChipSelect.
Referenced by FlashErase, GetRealAddr, OspiPsvFlashNonBlockingReadExample, OspiPsvInterruptFlashExample, OspiPsvPolledFlashExample.
void XOspiPsv_ConfigureAutoPolling(const XOspiPsv *InstancePtr, u32 FlashMode)
Configures how the controller will poll the device following a write transfer in DAC mode.
InstancePtr Pointer to the XOspiPsv instance. FlashMode Edge mode. XOSPIPSV_EDGE_MODE_* represents valid values. XST_SUCCESS if successful.XST_FAILURE if fail to set.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv::Extra_DummyCycle, XOspiPsv_ReadReg.
Referenced by FlashSetSDRDDRMode.