xospipsv_control.c
MAX_DELAY_CNT
< Maximum delay count
Referenced by XOspiPsv_CheckOspiIdle.
MAX_IDAC_DELAY_CNT
Max INDAC delay count.
Referenced by XOspiPsv_IDac_Write.
u32 XOspiPsv_Stig_Read(XOspiPsv *InstancePtr, XOspiPsv_Msg *Msg)
Flash command based data reading using flash command control registers.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. XST_SUCCESS if successful.XST_FAILURE if transfer fails. This operation is in IO mode of reading.
References XOspiPsv_Msg::Addr, XOspiPsv_Msg::Addrsize, XOspiPsv_Msg::Addrvalid, XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv::DualByteOpcodeEn, XOspiPsv_Msg::Dummy, XOspiPsv_Msg::ExtendedOpcode, XOspiPsv_Msg::Opcode, XOspiPsv::RxBytes, XOspiPsv_Exec_Flash_Cmd, XOspiPsv_FifoRead, XOspiPsv_ReadReg, XOspiPsv_Setup_Stig_Ctrl.
Referenced by XOspiPsv_PollRecvData.
u32 XOspiPsv_Stig_Write(XOspiPsv *InstancePtr, XOspiPsv_Msg *Msg)
Flash command based data write using flash command control registers.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. XST_SUCCESS if successful. XST_FAILURE if fails. This operation is in IO mode of writing.
References XOspiPsv_Msg::Addr, XOspiPsv_Msg::Addrsize, XOspiPsv_Msg::Addrvalid, XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv::DualByteOpcodeEn, XOspiPsv_Msg::ExtendedOpcode, XOspiPsv_Msg::Opcode, XOspiPsv::TxBytes, XOspiPsv_Exec_Flash_Cmd, XOspiPsv_FifoWrite, XOspiPsv_ReadReg, XOspiPsv_Setup_Stig_Ctrl.
Referenced by XOspiPsv_PollSendData.
u32 XOspiPsv_Dma_Read(XOspiPsv *InstancePtr, XOspiPsv_Msg *Msg)
Reads the data using DMA.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. XST_SUCCESS if successful. XST_FAILURE if transfer fails.
References XOspiPsv_Msg::Addr, XOspiPsv_Msg::ByteCount, XOspiPsv::Config, XOspiPsv_Config::IsCacheCoherent, XOspiPsv::IsUnaligned, XOspiPsv::RecvBufferPtr, XOspiPsv_Msg::RxBfrPtr, XOspiPsv::RxBytes, XOspiPsv::UnalignReadBuffer, XOspiPsv_Msg::Xfer64bit, XOspiPsv_Config_Dma, XOspiPsv_Config_IndirectAhb, XOspiPsv_Exec_Dma.
Referenced by XOspiPsv_PollRecvData.
u32 XOspiPsv_Dac_Read(XOspiPsv *InstancePtr, XOspiPsv_Msg *Msg)
Reads the data using Linear controller.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. XST_SUCCESS if successful. XST_FAILURE for invalid address.
References XOspiPsv_Msg::Addr, XOspiPsv_Msg::RxBfrPtr, XOspiPsv::RxBytes.
Referenced by XOspiPsv_PollRecvData.
u32 XOspiPsv_Dac_Write(XOspiPsv *InstancePtr, const XOspiPsv_Msg *Msg)
Writes the data Using Linear controller.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. XST_SUCCESS if successful. XST_FAILURE for invalid address.
References XOspiPsv_Msg::Addr, XOspiPsv_Msg::TxBfrPtr, XOspiPsv::TxBytes.
Referenced by XOspiPsv_PollSendData.
u32 XOspiPsv_ExecuteRxTuning(XOspiPsv *InstancePtr, XOspiPsv_Msg *FlashMsg, u32 TXTap)
Performs RX Tuning for SDR/DDR mode to calculate RX DLL Delay.
InstancePtr Pointer to the XOspiPsv instance. FlashMsg Pointer to the XOspiPsv_Msg structure. TXTap TX DLL Delay value. XST_SUCCESS if successful.XST_FAILURE if fails.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv::DllMode, XOspiPsv_Msg::Dummy, XOspiPsv_CalculateRxTap, XOspiPsv_WaitForLock.
Referenced by XOspiPsv_SetDllDelay.
u32 XOspiPsv_ConfigureTaps(const XOspiPsv *InstancePtr, u32 RxTap, u32 TxTap)
Configures the Rx and Tx taps in Phy Configuration register.
InstancePtr Pointer to the XOspiPsv instance. RxTap Rx tap value. TxTap Tx tap value. XST_SUCCESS if successful.XST_FAILURE if fails.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv::DllMode, XOspiPsv_WaitForLock.
Referenced by XOspiPsv_CalculateRxTap.
u32 XOspiPsv_CheckOspiIdle(const XOspiPsv *InstancePtr)
Checks for OSPI idle which means Serial interface and low level SPI pipeline is IDLE.
InstancePtr Pointer to the XOspiPsv instance. XST_SUCCESS if successful.XST_FAILURE if fails.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, MAX_DELAY_CNT.
Referenced by XOspiPsv_CheckDmaDone, XOspiPsv_IntrHandler, XOspiPsv_IntrTransfer, XOspiPsv_PollTransfer, XOspiPsv_SetDllDelay, XOspiPsv_StartDmaTransfer.
u32 XOspiPsv_IDac_Write(const XOspiPsv *InstancePtr, const XOspiPsv_Msg *Msg)
Writes data in Non-DMA Indirect mode.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. - XST_SUCCESS if successful. XST_FAILURE if fails.
References XOspiPsv_Msg::Addr, XOspiPsv_Config::BaseAddress, XOspiPsv_Msg::ByteCount, XOspiPsv::Config, MAX_IDAC_DELAY_CNT, XOspiPsv_Msg::TxBfrPtr, XOspiPsv_ReadReg.
Referenced by XOspiPsv_PollSendData.