xospipsv.h
XOSPIPSV_DAC_EN_OPTION
User configuration options.
Referenced by FlashSetSDRDDRMode, MicronBlockProtectTest, OspiPsvFlashNonBlockingReadExample, OspiPsvPolledFlashExample, XOspiPsv_SetOptions.
XOSPIPSV_IDAC_EN_OPTION
XOSPIPSV_STIG_EN_OPTION
XOSPIPSV_CLK_POL_OPTION
XOSPIPSV_CLK_PHASE_OPTION
XOSPIPSV_PHY_EN_OPTION
XOSPIPSV_LEGIP_EN_OPTION
XOSPIPSV_DTR_EN_OPTION
XOSPIPSV_CRC_EN_OPTION
XOSPIPSV_DB_OP_EN_OPTION
XOspiPsv_ReadReg
Low level macros to read/write memory.
Referenced by XOspiPsv_CalculateRxTap, XOspiPsv_CheckDmaDone, XOspiPsv_ConfigDualByteOpcode, XOspiPsv_ConfigureAutoPolling, XOspiPsv_DeviceReset, XOspiPsv_DeviceResetViaOspi, XOspiPsv_Exec_Dma, XOspiPsv_Exec_Flash_Cmd, XOspiPsv_FifoRead, XOspiPsv_GetOptions, XOspiPsv_IDac_Write, XOspiPsv_Idle, XOspiPsv_IntrHandler, XOspiPsv_IntrRecvData, XOspiPsv_IntrSendData, XOspiPsv_PollTransfer, XOspiPsv_SetClkPrescaler, XOspiPsv_SetDllDelay, XOspiPsv_SetOptions, XOspiPsv_SetSdrDdrMode, XOspiPsv_Setup_Dev_Read_Instr_Reg, XOspiPsv_Setup_Dev_Write_Instr_Reg, XOspiPsv_Setup_Devsize, XOspiPsv_Start_Indr_RdTransfer, XOspiPsv_StartDmaTransfer, XOspiPsv_Stig_Read, XOspiPsv_Stig_Write.
XOspiPsv_WriteReg
XOSPIPSV_IDAC_MODE
Macros to select INDAC and DAC modes.
Referenced by XOspiPsv_CfgInitialize, XOspiPsv_Get_Proto, XOspiPsv_PollRecvData, XOspiPsv_SetOptions, XOspiPsv_StartDmaTransfer.
XOSPIPSV_DAC_MODE
XOSPIPSV_MSG_FLAG_RX
Macros to select RX and TX transfer flags.
Referenced by BulkErase, DieErase, FlashEnterExit4BAddMode, FlashErase, FlashIoWrite, FlashRead, FlashReadID, FlashSetSDRDDRMode, MxConfigDummy, SetBlockProtect, SpansionSetEccMode, XOspiPsv_IntrHandler, XOspiPsv_IntrTransfer, XOspiPsv_PollTransfer, XOspiPsv_SetDllDelay, XOspiPsv_StartDmaTransfer.
XOSPIPSV_MSG_FLAG_TX
XOSPIPSV_READ_1_1_1
Macros to select Read and Write prototype.
Referenced by XOspiPsv_Get_Proto, XOspiPsv_PollRecvData, XOspiPsv_Setup_Dev_Read_Instr_Reg.
XOSPIPSV_READ_1_0_1
XOSPIPSV_READ_1_1_2
XOSPIPSV_READ_1_1_8
XOSPIPSV_READ_1_8_8
XOSPIPSV_READ_8_8_8
XOSPIPSV_READ_8_0_0
XOSPIPSV_READ_8_8_0
XOSPIPSV_READ_8_0_8
XOSPIPSV_READ_1_1_4
XOSPIPSV_READ_4_4_4
XOSPIPSV_WRITE_1_1_1
XOSPIPSV_WRITE_1_0_1
XOSPIPSV_WRITE_1_1_2
XOSPIPSV_WRITE_1_1_8
XOSPIPSV_WRITE_1_8_8
XOSPIPSV_WRITE_8_8_8
XOSPIPSV_WRITE_8_0_0
XOSPIPSV_WRITE_8_8_0
XOSPIPSV_WRITE_8_0_8
XOSPIPSV_WRITE_1_1_4
XOSPIPSV_WRITE_4_4_4
XOSPIPSV_SELECT_FLASH_CS0
Macros to select CS0 and CS1.
Referenced by FlashErase, GetRealAddr, OspiPsvFlashNonBlockingReadExample, OspiPsvInterruptFlashExample, OspiPsvPolledFlashExample.
XOSPIPSV_SELECT_FLASH_CS1
XOSPIPSV_CLK_PRESCALE_2
Macros to select different baud rate divisors.
Referenced by XOspiPsv_SetClkPrescaler.
XOSPIPSV_CLK_PRESCALE_4
XOSPIPSV_CLK_PRESCALE_6
XOSPIPSV_CLK_PRESCALE_8
XOSPIPSV_CLK_PRESCALE_10
XOSPIPSV_CLK_PRESCALE_12
XOSPIPSV_CLK_PRESCALE_14
XOSPIPSV_CLK_PRESCALE_16
XOSPIPSV_CLK_PRESCALE_18
XOSPIPSV_CLK_PRESCALE_20
XOSPIPSV_CLK_PRESCALE_22
XOSPIPSV_CLK_PRESCALE_24
XOSPIPSV_CLK_PRESCALE_26
XOSPIPSV_CLK_PRESCALE_28
XOSPIPSV_CLK_PRESCALE_30
XOSPIPSV_CLK_PRESCALE_32
XOSPIPSV_CR_PRESC_MAXIMUM
XOSPIPSV_NO_SLAVE_SELCT_VALUE
Macros to select default OSPI configuration.
XOSPIPSV_DISABLE_DAC_VALUE
XOSPIPSV_SPI_DISABLE_VALUE
XOSPIPSV_CONFIG_INIT_VALUE
XOSPIPSV_POLL_CNT_FLD_PHY
XOSPIPSV_POLL_CNT_FLD_NON_PHY
XOSPIPSV_MIN_PHY_FREQ
XOSPIPSV_DDR_STATS_REG_DUMMY
XOSPIPSV_REMAP_ADDR_VAL
XOSPIPSV_NON_PHY_RD_DLY
XOSPIPSV_EDGE_MODE_SDR_PHY
Macros to select different edge modes like SDR+NON-PHY, SDR+PHY and DDR+PHY.
Referenced by XOspiPsv_SetSdrDdrMode.
XOSPIPSV_EDGE_MODE_SDR_NON_PHY
XOSPIPSV_EDGE_MODE_DDR_PHY
XOSPIPSV_SDR_TX_VAL
Macros to select TX DLL delays.
Referenced by XOspiPsv_SetDllDelay.
XOSPIPSV_DDR_TX_VAL
XOSPIPSV_DDR_TX_VAL_MASTER
XOSPIPSV_SDR_TX_VAL_MASTER
XOSPIPSV_DLL_MAX_TAPS
XOSPIPSV_HWPIN_RESET
Macros to select HWPIN and INBAND resets.
Referenced by OspiPsvFlashNonBlockingReadExample, OspiPsvInterruptFlashExample, OspiPsvPolledFlashExample, XOspiPsv_DeviceReset, XOspiPsv_DeviceResetViaOspi.
XOSPIPSV_INBAND_RESET
XOSPIPSV_DLL_BYPASS_MODE
Macros to select DLL BYPASS and MASTER modes.
Referenced by XOspiPsv_CfgInitialize.
XOSPIPSV_DLL_MASTER_MODE
XOSPIPSV_CONNECTION_MODE_SINGLE
Macros to select SINGLE and STACKED connection modes.
XOSPIPSV_CONNECTION_MODE_STACKED
XOSPIPSV_DUAL_BYTE_OP_DISABLE
Macros to enable/disable Dual Byte opcode.
Referenced by FlashSetSDRDDRMode.
XOSPIPSV_DUAL_BYTE_OP_ENABLE
XOSPIPSV_DUAL_BYTE_OP_SAME
XOSPIPSV_H_
< prevent circular inclusions
by using protection macros
XOSPIPSV_RXADDR_OVER_32BIT
< Macro used for more than 32-bit address
Referenced by XOspiPsv_Config_Dma.
XOSPIPSV_TAP_GRAN_SEL_MIN_FREQ
Minimum frequency for Tap grain selection.
Referenced by XOspiPsv_CfgInitialize.
typedef void(* XOspiPsv_StatusHandler)(void *CallBackRef, u32 StatusEvent))(void *CallBackRef, u32 StatusEvent)
The handler data type allows the user to define a callback function to handle the asynchronous processing for the OSPIPSV device.
The application using this driver is expected to define a handler of this type to support interrupt driven mode. The handler executes in an interrupt context, so only minimal processing should be performed. CallBackRef Callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. Its type is not important to the driver, so it is a void pointer. StatusEvent Holds one or more status events that have occurred. See the XOspiPsv_SetStatusHandler() for details on the status events that can be passed in the callback.
XOspiPsv_Config XOspiPsv_ConfigTable[][]
The configuration table for devices.
Referenced by XOspiPsv_LookupConfig.
XOspiPsv_Config * XOspiPsv_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XOspiPsv_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xospipsv.h for the definition of XOspiPsv_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XOspiPsv_Config::Name, XOspiPsv_ConfigTable.
Referenced by OspiPsvFlashNonBlockingReadExample, OspiPsvInterruptFlashExample, OspiPsvPolledFlashExample.
u32 XOspiPsv_CfgInitialize(XOspiPsv *InstancePtr, const XOspiPsv_Config *ConfigPtr)
Initializes a specific XOspiPsv instance so that the driver is ready to use.
InstancePtr Pointer to the XOspiPsv instance. ConfigPtr Reference to a structure containing information about a specific OSPIPSV device. This function initializes an InstancePtr object for a specific device specified by the contents of Config. XST_SUCCESS if successful.XST_DEVICE_IS_STARTED if the device is already started. It must be stopped to re-initialize.
References XOspiPsv_Config::BaseAddress, XOspiPsv_Config::BusWidth, XOspiPsv::Config, XOspiPsv_Config::ConnectionMode, XOspiPsv::DeviceIdData, XOspiPsv::DllMode, XOspiPsv::DualByteOpcodeEn, XOspiPsv::Extra_DummyCycle, XOspiPsv_Config::InputClockHz, XOspiPsv::IsBusy, XOspiPsv_Config::IsCacheCoherent, XOspiPsv::IsReady, XOspiPsv::IsUnaligned, XOspiPsv::OpMode, XOspiPsv::RecvBufferPtr, XOspiPsv::RxBytes, XOspiPsv::SdrDdrMode, XOspiPsv::SendBufferPtr, SILICON_VERSION_1, XOspiPsv::StatusHandler, XOspiPsv::TxBytes, XOSPIPSV_DLL_BYPASS_MODE, XOSPIPSV_IDAC_MODE, XOspiPsv_Reset, XOspiPsv_SetSdrDdrMode, XOSPIPSV_TAP_GRAN_SEL_MIN_FREQ.
Referenced by OspiPsvFlashNonBlockingReadExample, OspiPsvInterruptFlashExample, OspiPsvPolledFlashExample.
void XOspiPsv_Reset(XOspiPsv *InstancePtr)
Resets the configuration register.
The Upper layer software is responsible for re-configuring (if necessary) and restarting the OSPIPSV device after the reset. InstancePtr Pointer to the XOspiPsv instance. None.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv::IsBusy.
Referenced by XOspiPsv_CfgInitialize.
u32 XOspiPsv_SetClkPrescaler(XOspiPsv *InstancePtr, u8 Prescaler)
Configures the clock according to the prescaler passed.
InstancePtr Pointer to the XOspiPsv instance. Prescaler Clock prescaler to be set. XST_SUCCESS if successful. XST_FAILURE if failed to set prescaler. XST_DEVICE_IS_STARTED if the device is already started.XST_DEVICE_BUSY if the device is currently transferring data. It must be stopped to re-initialize.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv::IsBusy, XOspiPsv::IsReady, XOspiPsv::SdrDdrMode, XOSPIPSV_CLK_PRESCALE_2, XOspiPsv_ReadReg, XOspiPsv_SetDllDelay.
Referenced by OspiPsvFlashNonBlockingReadExample, OspiPsvInterruptFlashExample, OspiPsvPolledFlashExample.
u32 XOspiPsv_SelectFlash(XOspiPsv *InstancePtr, u8 chip_select)
Used to signify the OSPIPSV driver that the Hardware flash configuration being used.
This API should be called at least once in the application. If desired, it can be called multiple times when switching between communicating to different flash devices/using different configuration. InstancePtr Pointer to the XOspiPsv instance. chip_select Flash Chip Select. XST_SUCCESS if successful.XST_DEVICE_IS_STARTED if the device is already started. It must be stopped to re-initialize. If this function is not called at least once in the application, the driver assumes there is a single flash connected to the lower bus and CS line.
References XOspiPsv::ChipSelect.
Referenced by FlashErase, GetRealAddr, OspiPsvFlashNonBlockingReadExample, OspiPsvInterruptFlashExample, OspiPsvPolledFlashExample.
u32 XOspiPsv_SetOptions(XOspiPsv *InstancePtr, u32 Options)
Sets the options for the OSPIPSV device driver.The options control how the device behaves relative to the OSPIPSV bus.
The device must be idle rather than busy transferring data before setting these device options. InstancePtr Pointer to the XOspiPsv instance. Options Contains the specified options to be set. This is a bit mask where a 1 indicates the option should be turned ON and a 0 indicates no action. One or more bit Values may be contained in the mask. See the bit definitions named XOSPIPSV_*_OPTIONS in the file xospipsv.h. XST_SUCCESS if options are successfully set.XST_DEVICE_BUSY if the device is currently transferring data. The transfer must complete or be aborted before setting options. This function is not thread-safe.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv::IsBusy, XOspiPsv::IsReady, XOspiPsv::OpMode, XOSPIPSV_DAC_EN_OPTION, XOSPIPSV_IDAC_MODE, XOSPIPSV_NUM_OPTIONS, XOspiPsv_ReadReg.
Referenced by OspiPsvFlashNonBlockingReadExample, OspiPsvInterruptFlashExample, OspiPsvPolledFlashExample.
u32 XOspiPsv_GetOptions(const XOspiPsv *InstancePtr)
Gets the options for the OSPIPSV device.
The options control how the device behaves relative to the OSPIPSV bus. InstancePtr Pointer to the XOspiPsv instance. Options contains the specified options currently set. This is a bit Value where a 1 means the option is on, and a 0 means the option is off. See the bit definitions named XOSPIPSV_*_OPTIONS in file xospipsv.h.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv::IsReady, XOSPIPSV_NUM_OPTIONS, XOspiPsv_ReadReg.
Referenced by MicronBlockProtectTest, OspiPsvFlashNonBlockingReadExample, OspiPsvPolledFlashExample.
u32 XOspiPsv_PollTransfer(XOspiPsv *InstancePtr, XOspiPsv_Msg *Msg)
Performs a transfer on the bus in polled mode.
The messages passed are all transferred on the bus between one CS assert and de-assert. InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. XST_SUCCESS if successful.XST_FAILURE if transfer fails.XST_DEVICE_BUSY if a transfer is already in progress.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv_Msg::Flags, XOspiPsv::IsBusy, XOspiPsv::IsReady, XOspiPsv::Msg, XOspiPsv_CheckOspiIdle, XOSPIPSV_MSG_FLAG_RX, XOspiPsv_PollRecvData, XOspiPsv_PollSendData, XOspiPsv_ReadReg, XOspiPsv_Setup_Devsize.
Referenced by FlashLinearWrite, SetBlockProtect, XOspiPsv_CalculateRxTap.
u32 XOspiPsv_IntrTransfer(XOspiPsv *InstancePtr, XOspiPsv_Msg *Msg)
Performs a transfer on the bus in interrupt mode.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. XST_SUCCESS if successful.XST_DEVICE_BUSY if a transfer is already in progress.
References XOspiPsv_Msg::Flags, XOspiPsv::IsBusy, XOspiPsv::IsReady, XOspiPsv::Msg, XOspiPsv::OpMode, XOspiPsv_CheckOspiIdle, XOspiPsv_IntrRecvData, XOspiPsv_IntrSendData, XOSPIPSV_MSG_FLAG_RX, XOspiPsv_Setup_Devsize.
Referenced by BulkErase, DieErase, FlashEnterExit4BAddMode, FlashErase, FlashIoWrite, FlashRead, FlashReadID, FlashSetSDRDDRMode, MxConfigDummy, SpansionSetEccMode.
u32 XOspiPsv_IntrHandler(XOspiPsv *InstancePtr)
Handles interrupt based transfers.
InstancePtr Pointer to the XOspiPsv instance. XST_SUCCESS if successful.XST_DEVICE_BUSY if a transfer is already in progress.
References XOspiPsv_Msg::Addr, XOspiPsv_Msg::Addrvalid, XOspiPsv_Config::BaseAddress, XOspiPsv_Msg::ByteCount, XOspiPsv::Config, XOspiPsv_Msg::Flags, XOspiPsv::IsBusy, XOspiPsv_Config::IsCacheCoherent, XOspiPsv::IsUnaligned, XOspiPsv::Msg, XOspiPsv::RecvBufferPtr, XOspiPsv_Msg::RxBfrPtr, XOspiPsv::RxBytes, XOspiPsv::StatusHandler, XOspiPsv::StatusRef, XOspiPsv::UnalignReadBuffer, XOspiPsv_Msg::Xfer64bit, XOspiPsv_CheckOspiIdle, XOspiPsv_Config_Dma, XOspiPsv_Config_IndirectAhb, XOspiPsv_FifoRead, XOSPIPSV_MSG_FLAG_RX, XOspiPsv_ReadReg, XOspiPsv_Start_Indr_RdTransfer.
Referenced by OspiPsvInterruptFlashExample.
void XOspiPsv_SetStatusHandler(XOspiPsv *InstancePtr, void *CallBackRef, XOspiPsv_StatusHandler FuncPointer)
Sets the status callback function, the status handler, which the driver calls when it encounters conditions that should be reported to upper layer software.
The handler executes in an interrupt context, so it must minimize the amount of processing performed. One of the following status events is passed to the status handler.XST_SPI_TRANSFER_DONE The requested data transfer is done InstancePtr Pointer to the XOspiPsv instance. CallBackRef Upper layer callback reference passed back when the callback function is invoked. FuncPointer Pointer to the callback function. None. The handler is called within interrupt context, so it should do its work quickly and queue potentially time-consuming work to a task-level thread.
References XOspiPsv::IsReady, XOspiPsv::StatusHandler, XOspiPsv::StatusRef.
Referenced by OspiPsvInterruptFlashExample.
u32 XOspiPsv_SetSdrDdrMode(XOspiPsv *InstancePtr, u32 Mode)
Configures the edge mode (SDR or DDR).
InstancePtr Pointer to the XOspiPsv instance. Mode Edge mode. XOSPIPSV_EDGE_MODE_* represents valid values. XST_SUCCESS if successful.XST_FAILURE if fail to set.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv::SdrDdrMode, XOSPIPSV_EDGE_MODE_SDR_PHY, XOspiPsv_ReadReg, XOspiPsv_SetDllDelay.
Referenced by FlashSetSDRDDRMode, OspiPsvFlashNonBlockingReadExample, OspiPsvInterruptFlashExample, OspiPsvPolledFlashExample, XOspiPsv_CfgInitialize.
void XOspiPsv_ConfigureAutoPolling(const XOspiPsv *InstancePtr, u32 FlashMode)
Configures how the controller will poll the device following a write transfer in DAC mode.
InstancePtr Pointer to the XOspiPsv instance. FlashMode Edge mode. XOSPIPSV_EDGE_MODE_* represents valid values. XST_SUCCESS if successful.XST_FAILURE if fail to set.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv::Extra_DummyCycle, XOspiPsv_ReadReg.
Referenced by FlashSetSDRDDRMode.
void XOspiPsv_Idle(const XOspiPsv *InstancePtr)
Stops the transfer of data to internal DST FIFO from stream interface and also stops the issuing of new write commands to memory.
By calling this API, any ongoing Dma transfers will be paused and DMA will not issue AXI write commands to memory InstancePtr Pointer to the XOspiPsv instance. None.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv_ReadReg.
u32 XOspiPsv_DeviceReset(u8 Type)
Reset the OSPI flash device.
Type Reset type. XST_SUCCESS if successful. XST_FAILURE for invalid Reset Type.
References XOSPIPSV_HWPIN_RESET, XOspiPsv_ReadReg.
Referenced by OspiPsvFlashNonBlockingReadExample, OspiPsvInterruptFlashExample, OspiPsvPolledFlashExample.
u32 XOspiPsv_DeviceResetViaOspi(const XOspiPsv *InstancePtr, u8 Type)
Resets the OSPI flash device via OSPI controller.
InstancePtr Pointer to the XOspiPsv instance. Type Resets type. XST_SUCCESS if successful. XST_FAILURE for invalid Reset Type.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOSPIPSV_HWPIN_RESET, XOspiPsv_ReadReg.
Referenced by OspiPsvFlashNonBlockingReadExample, OspiPsvInterruptFlashExample, OspiPsvPolledFlashExample.
u32 XOspiPsv_StartDmaTransfer(XOspiPsv *InstancePtr, XOspiPsv_Msg *Msg)
Starts a DMA transfer.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. XST_SUCCESS if successful.XST_FAILURE if transfer fails.XST_DEVICE_BUSY if a transfer is already in progress.
References XOspiPsv_Config::BaseAddress, XOspiPsv_Msg::ByteCount, XOspiPsv::Config, XOspiPsv_Msg::Flags, XOspiPsv::IsBusy, XOspiPsv::IsReady, XOspiPsv::Msg, XOspiPsv::OpMode, XOspiPsv::RecvBufferPtr, XOspiPsv_Msg::RxBfrPtr, XOspiPsv::RxBytes, XOspiPsv::SendBufferPtr, XOspiPsv_CheckOspiIdle, XOspiPsv_Config_Dma, XOspiPsv_Config_IndirectAhb, XOSPIPSV_IDAC_MODE, XOSPIPSV_MSG_FLAG_RX, XOspiPsv_ReadReg, XOspiPsv_Setup_Dev_Read_Instr_Reg, XOspiPsv_Setup_Devsize.
u32 XOspiPsv_CheckDmaDone(XOspiPsv *InstancePtr)
Checks for DMA transfer complete.
InstancePtr Pointer to the XOspiPsv instance. XST_SUCCESS if DMA transfer complete.XST_FAILURE if DMA transfer is not completed.
References XOspiPsv_Config::BaseAddress, XOspiPsv_Msg::ByteCount, XOspiPsv::Config, XOspiPsv::IsBusy, XOspiPsv_Config::IsCacheCoherent, XOspiPsv::Msg, XOspiPsv_Msg::RxBfrPtr, XOspiPsv_Msg::Xfer64bit, XOspiPsv_CheckOspiIdle, XOspiPsv_ReadReg.
u32 XOspiPsv_SetDllDelay(XOspiPsv *InstancePtr)
Configures TX and RX DLL Delay.
Based on the mode and reference clock this API calculates the RX delay and configure them in PHY configuration register. InstancePtr Pointer to the XOspiPsv instance. XST_SUCCESS if successful.XST_FAILURE if fails.
References XOspiPsv_Msg::Addr, XOspiPsv_Msg::Addrsize, XOspiPsv_Msg::Addrvalid, XOspiPsv_Config::BaseAddress, XOspiPsv_Msg::ByteCount, XOspiPsv::Config, XOspiPsv::DllMode, XOspiPsv::DualByteOpcodeEn, XOspiPsv_Msg::Dummy, XOspiPsv_Msg::ExtendedOpcode, XOspiPsv::Extra_DummyCycle, XOspiPsv_Msg::Flags, XOspiPsv_Msg::IsDDROpCode, XOspiPsv_Msg::Opcode, XOspiPsv_Msg::Proto, READ_ID, XOspiPsv_Msg::RxBfrPtr, XOspiPsv::SdrDdrMode, XOspiPsv_Msg::TxBfrPtr, XOspiPsv_CheckOspiIdle, XOspiPsv_ExecuteRxTuning, XOSPIPSV_MSG_FLAG_RX, XOspiPsv_ReadReg, XOSPIPSV_SDR_TX_VAL, XOspiPsv_WaitForLock.
Referenced by XOspiPsv_SetClkPrescaler, XOspiPsv_SetSdrDdrMode.
u32 XOspiPsv_ConfigDualByteOpcode(XOspiPsv *InstancePtr, u8 Enable)
Configures the dual-byte opcode mode.
InstancePtr Pointer to the XOspiPsv instance. Enable 1 to enable dual-byte opcode, 0 to disable. None.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv::DualByteOpcodeEn, XOspiPsv::IsReady, XOspiPsv_ReadReg.
Referenced by FlashSetSDRDDRMode.