xospipsv.c
SILICON_VERSION_1
Silicon version.
Referenced by XOspiPsv_CfgInitialize.
READ_ID
Read Id opcode.
Referenced by FlashReadID, XOspiPsv_SetDllDelay.
static void XOspiPsv_AssertCS(const XOspiPsv *InstancePtr)
Asserts the chip select line.
InstancePtr Pointer to the XOspiPsv instance. None
static void XOspiPsv_DeAssertCS(const XOspiPsv *InstancePtr)
De-asserts the chip select line.
InstancePtr Pointer to the XOspiPsv instance. None
static void StubStatusHandler(void *CallBackRef, u32 StatusEvent)
Stub for the status callback.
The stub is here in case the upper layers forget to set the handler. CallBackRef Pointer to the upper layer callback reference StatusEvent Event that just occurred. None.
u32 XOspiPsv_CfgInitialize(XOspiPsv *InstancePtr, const XOspiPsv_Config *ConfigPtr)
Initializes a specific XOspiPsv instance so that the driver is ready to use.
InstancePtr Pointer to the XOspiPsv instance. ConfigPtr Reference to a structure containing information about a specific OSPIPSV device. This function initializes an InstancePtr object for a specific device specified by the contents of Config. XST_SUCCESS if successful.XST_DEVICE_IS_STARTED if the device is already started. It must be stopped to re-initialize.
References XOspiPsv_Config::BaseAddress, XOspiPsv_Config::BusWidth, XOspiPsv::Config, XOspiPsv_Config::ConnectionMode, XOspiPsv::DeviceIdData, XOspiPsv::DllMode, XOspiPsv::DualByteOpcodeEn, XOspiPsv::Extra_DummyCycle, XOspiPsv_Config::InputClockHz, XOspiPsv::IsBusy, XOspiPsv_Config::IsCacheCoherent, XOspiPsv::IsReady, XOspiPsv::IsUnaligned, XOspiPsv::OpMode, XOspiPsv::RecvBufferPtr, XOspiPsv::RxBytes, XOspiPsv::SdrDdrMode, XOspiPsv::SendBufferPtr, SILICON_VERSION_1, XOspiPsv::StatusHandler, XOspiPsv::TxBytes, XOSPIPSV_DLL_BYPASS_MODE, XOSPIPSV_IDAC_MODE, XOspiPsv_Reset, XOspiPsv_SetSdrDdrMode, XOSPIPSV_TAP_GRAN_SEL_MIN_FREQ.
Referenced by OspiPsvFlashNonBlockingReadExample, OspiPsvInterruptFlashExample, OspiPsvPolledFlashExample.
void XOspiPsv_Reset(XOspiPsv *InstancePtr)
Resets the configuration register.
The Upper layer software is responsible for re-configuring (if necessary) and restarting the OSPIPSV device after the reset. InstancePtr Pointer to the XOspiPsv instance. None.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv::IsBusy.
Referenced by XOspiPsv_CfgInitialize.
u32 XOspiPsv_DeviceReset(u8 Type)
Reset the OSPI flash device.
Type Reset type. XST_SUCCESS if successful. XST_FAILURE for invalid Reset Type.
References XOSPIPSV_HWPIN_RESET, XOspiPsv_ReadReg.
Referenced by OspiPsvFlashNonBlockingReadExample, OspiPsvInterruptFlashExample, OspiPsvPolledFlashExample.
u32 XOspiPsv_DeviceResetViaOspi(const XOspiPsv *InstancePtr, u8 Type)
Resets the OSPI flash device via OSPI controller.
InstancePtr Pointer to the XOspiPsv instance. Type Resets type. XST_SUCCESS if successful. XST_FAILURE for invalid Reset Type.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOSPIPSV_HWPIN_RESET, XOspiPsv_ReadReg.
Referenced by OspiPsvFlashNonBlockingReadExample, OspiPsvInterruptFlashExample, OspiPsvPolledFlashExample.
u32 XOspiPsv_PollTransfer(XOspiPsv *InstancePtr, XOspiPsv_Msg *Msg)
Performs a transfer on the bus in polled mode.
The messages passed are all transferred on the bus between one CS assert and de-assert. InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. XST_SUCCESS if successful.XST_FAILURE if transfer fails.XST_DEVICE_BUSY if a transfer is already in progress.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv_Msg::Flags, XOspiPsv::IsBusy, XOspiPsv::IsReady, XOspiPsv::Msg, XOspiPsv_CheckOspiIdle, XOSPIPSV_MSG_FLAG_RX, XOspiPsv_PollRecvData, XOspiPsv_PollSendData, XOspiPsv_ReadReg, XOspiPsv_Setup_Devsize.
Referenced by FlashLinearWrite, SetBlockProtect, XOspiPsv_CalculateRxTap.
u32 XOspiPsv_StartDmaTransfer(XOspiPsv *InstancePtr, XOspiPsv_Msg *Msg)
Starts a DMA transfer.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. XST_SUCCESS if successful.XST_FAILURE if transfer fails.XST_DEVICE_BUSY if a transfer is already in progress.
References XOspiPsv_Config::BaseAddress, XOspiPsv_Msg::ByteCount, XOspiPsv::Config, XOspiPsv_Msg::Flags, XOspiPsv::IsBusy, XOspiPsv::IsReady, XOspiPsv::Msg, XOspiPsv::OpMode, XOspiPsv::RecvBufferPtr, XOspiPsv_Msg::RxBfrPtr, XOspiPsv::RxBytes, XOspiPsv::SendBufferPtr, XOspiPsv_CheckOspiIdle, XOspiPsv_Config_Dma, XOspiPsv_Config_IndirectAhb, XOSPIPSV_IDAC_MODE, XOSPIPSV_MSG_FLAG_RX, XOspiPsv_ReadReg, XOspiPsv_Setup_Dev_Read_Instr_Reg, XOspiPsv_Setup_Devsize.
u32 XOspiPsv_CheckDmaDone(XOspiPsv *InstancePtr)
Checks for DMA transfer complete.
InstancePtr Pointer to the XOspiPsv instance. XST_SUCCESS if DMA transfer complete.XST_FAILURE if DMA transfer is not completed.
References XOspiPsv_Config::BaseAddress, XOspiPsv_Msg::ByteCount, XOspiPsv::Config, XOspiPsv::IsBusy, XOspiPsv_Config::IsCacheCoherent, XOspiPsv::Msg, XOspiPsv_Msg::RxBfrPtr, XOspiPsv_Msg::Xfer64bit, XOspiPsv_CheckOspiIdle, XOspiPsv_ReadReg.
u32 XOspiPsv_IntrTransfer(XOspiPsv *InstancePtr, XOspiPsv_Msg *Msg)
Performs a transfer on the bus in interrupt mode.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. XST_SUCCESS if successful.XST_DEVICE_BUSY if a transfer is already in progress.
References XOspiPsv_Msg::Flags, XOspiPsv::IsBusy, XOspiPsv::IsReady, XOspiPsv::Msg, XOspiPsv::OpMode, XOspiPsv_CheckOspiIdle, XOspiPsv_IntrRecvData, XOspiPsv_IntrSendData, XOSPIPSV_MSG_FLAG_RX, XOspiPsv_Setup_Devsize.
Referenced by BulkErase, DieErase, FlashEnterExit4BAddMode, FlashErase, FlashIoWrite, FlashRead, FlashReadID, FlashSetSDRDDRMode, MxConfigDummy, SpansionSetEccMode.
u32 XOspiPsv_IntrHandler(XOspiPsv *InstancePtr)
Handles interrupt based transfers.
InstancePtr Pointer to the XOspiPsv instance. XST_SUCCESS if successful.XST_DEVICE_BUSY if a transfer is already in progress.
References XOspiPsv_Msg::Addr, XOspiPsv_Msg::Addrvalid, XOspiPsv_Config::BaseAddress, XOspiPsv_Msg::ByteCount, XOspiPsv::Config, XOspiPsv_Msg::Flags, XOspiPsv::IsBusy, XOspiPsv_Config::IsCacheCoherent, XOspiPsv::IsUnaligned, XOspiPsv::Msg, XOspiPsv::RecvBufferPtr, XOspiPsv_Msg::RxBfrPtr, XOspiPsv::RxBytes, XOspiPsv::StatusHandler, XOspiPsv::StatusRef, XOspiPsv::UnalignReadBuffer, XOspiPsv_Msg::Xfer64bit, XOspiPsv_CheckOspiIdle, XOspiPsv_Config_Dma, XOspiPsv_Config_IndirectAhb, XOspiPsv_FifoRead, XOSPIPSV_MSG_FLAG_RX, XOspiPsv_ReadReg, XOspiPsv_Start_Indr_RdTransfer.
Referenced by OspiPsvInterruptFlashExample.
void XOspiPsv_Idle(const XOspiPsv *InstancePtr)
Stops the transfer of data to internal DST FIFO from stream interface and also stops the issuing of new write commands to memory.
By calling this API, any ongoing Dma transfers will be paused and DMA will not issue AXI write commands to memory InstancePtr Pointer to the XOspiPsv instance. None.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv_ReadReg.
u32 XOspiPsv_SetDllDelay(XOspiPsv *InstancePtr)
Configures TX and RX DLL Delay.
Based on the mode and reference clock this API calculates the RX delay and configure them in PHY configuration register. InstancePtr Pointer to the XOspiPsv instance. XST_SUCCESS if successful.XST_FAILURE if fails.
References XOspiPsv_Msg::Addr, XOspiPsv_Msg::Addrsize, XOspiPsv_Msg::Addrvalid, XOspiPsv_Config::BaseAddress, XOspiPsv_Msg::ByteCount, XOspiPsv::Config, XOspiPsv::DllMode, XOspiPsv::DualByteOpcodeEn, XOspiPsv_Msg::Dummy, XOspiPsv_Msg::ExtendedOpcode, XOspiPsv::Extra_DummyCycle, XOspiPsv_Msg::Flags, XOspiPsv_Msg::IsDDROpCode, XOspiPsv_Msg::Opcode, XOspiPsv_Msg::Proto, READ_ID, XOspiPsv_Msg::RxBfrPtr, XOspiPsv::SdrDdrMode, XOspiPsv_Msg::TxBfrPtr, XOspiPsv_CheckOspiIdle, XOspiPsv_ExecuteRxTuning, XOSPIPSV_MSG_FLAG_RX, XOspiPsv_ReadReg, XOSPIPSV_SDR_TX_VAL, XOspiPsv_WaitForLock.
Referenced by XOspiPsv_SetClkPrescaler, XOspiPsv_SetSdrDdrMode.
u32 XOspiPsv_ConfigDualByteOpcode(XOspiPsv *InstancePtr, u8 Enable)
Configures the dual-byte opcode mode.
InstancePtr Pointer to the XOspiPsv instance. Enable 1 to enable dual-byte opcode, 0 to disable. None.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv::DualByteOpcodeEn, XOspiPsv::IsReady, XOspiPsv_ReadReg.
Referenced by FlashSetSDRDDRMode.
void XOspiPsv_SetStatusHandler(XOspiPsv *InstancePtr, void *CallBackRef, XOspiPsv_StatusHandler FuncPointer)
Sets the status callback function, the status handler, which the driver calls when it encounters conditions that should be reported to upper layer software.
The handler executes in an interrupt context, so it must minimize the amount of processing performed. One of the following status events is passed to the status handler.XST_SPI_TRANSFER_DONE The requested data transfer is done InstancePtr Pointer to the XOspiPsv instance. CallBackRef Upper layer callback reference passed back when the callback function is invoked. FuncPointer Pointer to the callback function. None. The handler is called within interrupt context, so it should do its work quickly and queue potentially time-consuming work to a task-level thread.
References XOspiPsv::IsReady, XOspiPsv::StatusHandler, XOspiPsv::StatusRef.
Referenced by OspiPsvInterruptFlashExample.