xospipsv_control.h
XOSPIPSV_LOWLEVEL_H_
< prevent circular inclusions
by using protection macros
static void XOspiPsv_Disable(const XOspiPsv *InstancePtr)
Disables the OSPIPSV device.
InstancePtr Pointer to the XOspiPsv instance. None.
static void XOspiPsv_Enable(const XOspiPsv *InstancePtr)
Enables the OSPIPSV device.
InstancePtr Pointer to the XOspiPsv instance. None.
static void XOspiPsv_ConfigureMux_Linear(const XOspiPsv *InstancePtr)
Configures the OSPI MUX to Linear mode.
InstancePtr Pointer to the XOspiPsv instance. None.
static void XOspiPsv_ConfigureMux_Dma(const XOspiPsv *InstancePtr)
Configures the OSPI MUX to DMA mode.
InstancePtr Pointer to the XOspiPsv instance. None.
u32 XOspiPsv_Stig_Read(XOspiPsv *InstancePtr, XOspiPsv_Msg *Msg)
Flash command based data reading using flash command control registers.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. XST_SUCCESS if successful.XST_FAILURE if transfer fails. This operation is in IO mode of reading.
References XOspiPsv_Msg::Addr, XOspiPsv_Msg::Addrsize, XOspiPsv_Msg::Addrvalid, XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv::DualByteOpcodeEn, XOspiPsv_Msg::Dummy, XOspiPsv_Msg::ExtendedOpcode, XOspiPsv_Msg::Opcode, XOspiPsv::RxBytes, XOspiPsv_Exec_Flash_Cmd, XOspiPsv_FifoRead, XOspiPsv_ReadReg, XOspiPsv_Setup_Stig_Ctrl.
Referenced by XOspiPsv_PollRecvData.
u32 XOspiPsv_Stig_Write(XOspiPsv *InstancePtr, XOspiPsv_Msg *Msg)
Flash command based data write using flash command control registers.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. XST_SUCCESS if successful. XST_FAILURE if fails. This operation is in IO mode of writing.
References XOspiPsv_Msg::Addr, XOspiPsv_Msg::Addrsize, XOspiPsv_Msg::Addrvalid, XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv::DualByteOpcodeEn, XOspiPsv_Msg::ExtendedOpcode, XOspiPsv_Msg::Opcode, XOspiPsv::TxBytes, XOspiPsv_Exec_Flash_Cmd, XOspiPsv_FifoWrite, XOspiPsv_ReadReg, XOspiPsv_Setup_Stig_Ctrl.
Referenced by XOspiPsv_PollSendData.
u32 XOspiPsv_Dac_Read(XOspiPsv *InstancePtr, XOspiPsv_Msg *Msg)
Reads the data using Linear controller.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. XST_SUCCESS if successful. XST_FAILURE for invalid address.
References XOspiPsv_Msg::Addr, XOspiPsv_Msg::RxBfrPtr, XOspiPsv::RxBytes.
Referenced by XOspiPsv_PollRecvData.
u32 XOspiPsv_Dac_Write(XOspiPsv *InstancePtr, const XOspiPsv_Msg *Msg)
Writes the data Using Linear controller.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. XST_SUCCESS if successful. XST_FAILURE for invalid address.
References XOspiPsv_Msg::Addr, XOspiPsv_Msg::TxBfrPtr, XOspiPsv::TxBytes.
Referenced by XOspiPsv_PollSendData.
u32 XOspiPsv_Dma_Read(XOspiPsv *InstancePtr, XOspiPsv_Msg *Msg)
Reads the data using DMA.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. XST_SUCCESS if successful. XST_FAILURE if transfer fails.
References XOspiPsv_Msg::Addr, XOspiPsv_Msg::ByteCount, XOspiPsv::Config, XOspiPsv_Config::IsCacheCoherent, XOspiPsv::IsUnaligned, XOspiPsv::RecvBufferPtr, XOspiPsv_Msg::RxBfrPtr, XOspiPsv::RxBytes, XOspiPsv::UnalignReadBuffer, XOspiPsv_Msg::Xfer64bit, XOspiPsv_Config_Dma, XOspiPsv_Config_IndirectAhb, XOspiPsv_Exec_Dma.
Referenced by XOspiPsv_PollRecvData.
void XOspiPsv_FifoRead(XOspiPsv *InstancePtr, XOspiPsv_Msg *Msg)
Reads data from RX FIFO.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. None This operation is in IO mode of reading.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv_Msg::RxBfrPtr, XOspiPsv::RxBytes, XOspiPsv_ReadReg.
Referenced by XOspiPsv_IntrHandler, XOspiPsv_Stig_Read.
void XOspiPsv_FifoWrite(XOspiPsv *InstancePtr, XOspiPsv_Msg *Msg)
Writes data to TX FIFO.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. XST_SUCCESS if successful.XST_FAILURE if transfer fails. This operation is in IO mode of writing.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv_Msg::TxBfrPtr, XOspiPsv::TxBytes.
Referenced by XOspiPsv_IntrSendData, XOspiPsv_Stig_Write.
void XOspiPsv_Setup_Stig_Ctrl(const XOspiPsv *InstancePtr, u32 Cmd_op, u32 Rd_data_en, u32 Num_rd_data_bytes, u32 Cmd_addr_en, u32 Mode_bit_en, u32 Num_addr_bytes, u32 Wr_data_en, u32 Num_wr_data_bytes, u32 Dummy, u32 Membank_en)
Configures the STIG control register (Flash cmd register).
InstancePtr Pointer to the XOspiPsv instance. Cmd_op Command opcode. Rd_data_en Specifies whether cmd_op requires data to read or not. Num_rd_data_bytes Number of bytes to read. Cmd_addr_en Specifies whether cmd_op requires addr or not. Mode_bit_en Represents mode bit configuration register. Num_addr_bytes Represents addr bytes (4/3 etc). Wr_data_en Specifies whether cmd_op requires write enable or not. Num_wr_data_bytes Number of bytes to write. Dummy Number of bytes to write. Membank_en Enables STIG memory bank. None.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config.
Referenced by XOspiPsv_IntrRecvData, XOspiPsv_IntrSendData, XOspiPsv_Stig_Read, XOspiPsv_Stig_Write.
void XOspiPsv_Setup_Dev_Write_Instr_Reg(const XOspiPsv *InstancePtr, const XOspiPsv_Msg *Msg)
Configures the below info to write instruction register DataXfertype - SPI/Dual/Quad/Octal AddrXfertype - 3 or 4B.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. None Used in DMA or Linear operations.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv::DualByteOpcodeEn, XOspiPsv_Msg::ExtendedOpcode, XOspiPsv_Msg::Opcode, XOspiPsv_Msg::Proto, XOspiPsv_ReadReg.
Referenced by XOspiPsv_IntrSendData, XOspiPsv_PollSendData.
void XOspiPsv_Setup_Dev_Read_Instr_Reg(const XOspiPsv *InstancePtr, const XOspiPsv_Msg *Msg)
Configures the below info to read instruction register DataXfertype - SPI/Dual/Quad/Octal AddrXfertype - 3 or 4B.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. None Used in DMA or Linear operations
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv::DualByteOpcodeEn, XOspiPsv_Msg::Dummy, XOspiPsv_Msg::ExtendedOpcode, XOspiPsv_Msg::IsDDROpCode, XOspiPsv_Msg::Opcode, XOspiPsv_Msg::Proto, XOspiPsv::SdrDdrMode, XOSPIPSV_READ_1_1_1, XOspiPsv_ReadReg.
Referenced by XOspiPsv_IntrRecvData, XOspiPsv_PollRecvData, XOspiPsv_StartDmaTransfer.
void XOspiPsv_Setup_Devsize(const XOspiPsv *InstancePtr, const XOspiPsv_Msg *Msg)
Sets the device size config register.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. None
References XOspiPsv_Msg::Addrsize, XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv_ReadReg.
Referenced by XOspiPsv_IntrTransfer, XOspiPsv_PollTransfer, XOspiPsv_StartDmaTransfer.
void XOspiPsv_Start_Indr_RdTransfer(const XOspiPsv *InstancePtr)
Initiates the indirect read transfer.
InstancePtr Pointer to the XOspiPsv instance. None
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv_ReadReg.
Referenced by XOspiPsv_IntrHandler, XOspiPsv_IntrRecvData.
void XOspiPsv_Config_IndirectAhb(const XOspiPsv *InstancePtr, const XOspiPsv_Msg *Msg)
Configures the Indirect controller.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. None
References XOspiPsv_Msg::Addr, XOspiPsv_Config::BaseAddress, XOspiPsv_Msg::ByteCount, XOspiPsv::Config.
Referenced by XOspiPsv_Dma_Read, XOspiPsv_IntrHandler, XOspiPsv_IntrRecvData, XOspiPsv_StartDmaTransfer.
void XOspiPsv_Config_Dma(const XOspiPsv *InstancePtr, const XOspiPsv_Msg *Msg)
Sets up the Dma configuration.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. None
References XOspiPsv_Config::BaseAddress, XOspiPsv_Msg::ByteCount, XOspiPsv::Config, XOspiPsv_Config::IsCacheCoherent, XOspiPsv_Msg::RxAddr64bit, XOspiPsv_Msg::RxBfrPtr, XOspiPsv_Msg::Xfer64bit, XOSPIPSV_RXADDR_OVER_32BIT.
Referenced by XOspiPsv_Dma_Read, XOspiPsv_IntrHandler, XOspiPsv_IntrRecvData, XOspiPsv_StartDmaTransfer.
u32 XOspiPsv_Exec_Dma(const XOspiPsv *InstancePtr)
Initiates the DMA transfer.
InstancePtr Pointer to the XOspiPsv instance. XST_SUCCESS if successful. XST_FAILURE if transfer fails.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, MAX_DMA_DELAY_CNT, XOspiPsv_ReadReg.
Referenced by XOspiPsv_Dma_Read.
u32 XOspiPsv_Exec_Flash_Cmd(const XOspiPsv *InstancePtr)
Executes the Flash command configured using Flash Command control register.
InstancePtr Pointer to the XOspiPsv instance. XST_SUCCESS if successful. XST_FAILURE if transfer fails. Wait till the command is executed.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, MAX_STIG_DELAY_CNT, XOspiPsv_ReadReg.
Referenced by XOspiPsv_Stig_Read, XOspiPsv_Stig_Write.
u32 XOspiPsv_CheckOspiIdle(const XOspiPsv *InstancePtr)
Checks for OSPI idle which means Serial interface and low level SPI pipeline is IDLE.
InstancePtr Pointer to the XOspiPsv instance. XST_SUCCESS if successful.XST_FAILURE if fails.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, MAX_DELAY_CNT.
Referenced by XOspiPsv_CheckDmaDone, XOspiPsv_IntrHandler, XOspiPsv_IntrTransfer, XOspiPsv_PollTransfer, XOspiPsv_SetDllDelay, XOspiPsv_StartDmaTransfer.
u32 XOspiPsv_WaitForLock(const XOspiPsv *InstancePtr, u32 Mask)
Waits for bit to be set.
This API polls for the required bit for 10 seconds, if not set then timeout occurs. InstancePtr Pointer to the XOspiPsv instance. Mask Bit mask to check for lock. XST_SUCCESS if lock bit is set.XST_FAILURE if fails.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, LOCK_MAX_DELAY_CNT.
Referenced by XOspiPsv_ConfigureTaps, XOspiPsv_ExecuteRxTuning, XOspiPsv_SetDllDelay.
u32 XOspiPsv_ExecuteRxTuning(XOspiPsv *InstancePtr, XOspiPsv_Msg *FlashMsg, u32 TXTap)
Performs RX Tuning for SDR/DDR mode to calculate RX DLL Delay.
InstancePtr Pointer to the XOspiPsv instance. FlashMsg Pointer to the XOspiPsv_Msg structure. TXTap TX DLL Delay value. XST_SUCCESS if successful.XST_FAILURE if fails.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv::DllMode, XOspiPsv_Msg::Dummy, XOspiPsv_CalculateRxTap, XOspiPsv_WaitForLock.
Referenced by XOspiPsv_SetDllDelay.
u32 XOspiPsv_CalculateRxTap(XOspiPsv *InstancePtr, XOspiPsv_Msg *FlashMsg, u8 *AvgRXTap, u8 *MaxWindowSize, u8 DummyIncr, u32 TXTap)
Calculates the Max window size and the corresponding Average Rx Tap.
InstancePtr Pointer to the XOspiPsv instance. FlashMsg Pointer to XOspiPsv_Msg instance. AvgRXTap Pointer to median Rx Tap. MaxWindowSize Pointer to maximum window size. DummyIncr Flag to indicate additional dummy. TXTap Tx tap value used while doing Rx tuning. XST_SUCCESS if lock bit is set.XST_FAILURE if fails.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv::DeviceIdData, XOspiPsv::DllMode, XOspiPsv::Extra_DummyCycle, XOspiPsv_Config::InputClockHz, XOspiPsv_Msg::RxBfrPtr, TERA_MACRO, XOspiPsv_ConfigureTaps, XOspiPsv_PollTransfer, XOspiPsv_ReadReg.
Referenced by XOspiPsv_ExecuteRxTuning.
u32 XOspiPsv_ConfigureTaps(const XOspiPsv *InstancePtr, u32 RxTap, u32 TxTap)
Configures the Rx and Tx taps in Phy Configuration register.
InstancePtr Pointer to the XOspiPsv instance. RxTap Rx tap value. TxTap Tx tap value. XST_SUCCESS if successful.XST_FAILURE if fails.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv::DllMode, XOspiPsv_WaitForLock.
Referenced by XOspiPsv_CalculateRxTap.
u32 XOspiPsv_IDac_Write(const XOspiPsv *InstancePtr, const XOspiPsv_Msg *Msg)
Writes data in Non-DMA Indirect mode.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. - XST_SUCCESS if successful. XST_FAILURE if fails.
References XOspiPsv_Msg::Addr, XOspiPsv_Config::BaseAddress, XOspiPsv_Msg::ByteCount, XOspiPsv::Config, MAX_IDAC_DELAY_CNT, XOspiPsv_Msg::TxBfrPtr, XOspiPsv_ReadReg.
Referenced by XOspiPsv_PollSendData.
u32 XOspiPsv_PollRecvData(XOspiPsv *InstancePtr, XOspiPsv_Msg *Msg)
This function performs a polled data receive operation.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. XST_SUCCESS if successful.XST_FAILURE if transfer fails.
References XOspiPsv_Msg::Addrvalid, XOspiPsv_Msg::ByteCount, XOspiPsv::OpMode, XOspiPsv_Msg::Proto, XOspiPsv::RecvBufferPtr, XOspiPsv_Msg::RxBfrPtr, XOspiPsv::RxBytes, XOspiPsv::SendBufferPtr, XOspiPsv_Dac_Read, XOspiPsv_Dma_Read, XOSPIPSV_IDAC_MODE, XOSPIPSV_READ_1_1_1, XOspiPsv_Setup_Dev_Read_Instr_Reg, XOspiPsv_Stig_Read.
Referenced by XOspiPsv_PollTransfer.
u32 XOspiPsv_PollSendData(XOspiPsv *InstancePtr, XOspiPsv_Msg *Msg)
This function performs a polled data send operation.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. XST_SUCCESS if successful.XST_FAILURE if transfer fails.
References XOspiPsv_Msg::ByteCount, XOspiPsv::OpMode, XOspiPsv::RecvBufferPtr, XOspiPsv::SendBufferPtr, XOspiPsv_Msg::TxBfrPtr, XOspiPsv::TxBytes, XOspiPsv_Dac_Write, XOspiPsv_IDac_Write, XOspiPsv_Setup_Dev_Write_Instr_Reg, XOspiPsv_Stig_Write.
Referenced by XOspiPsv_PollTransfer.
void XOspiPsv_IntrRecvData(XOspiPsv *InstancePtr, XOspiPsv_Msg *Msg)
This function performs an interrupt-based data receive operation.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. None.
References XOspiPsv_Msg::Addrsize, XOspiPsv_Msg::Addrvalid, XOspiPsv_Config::BaseAddress, XOspiPsv_Msg::ByteCount, XOspiPsv::Config, XOspiPsv_Msg::Dummy, XOspiPsv::IsUnaligned, XOspiPsv_Msg::Opcode, XOspiPsv::RecvBufferPtr, XOspiPsv_Msg::RxBfrPtr, XOspiPsv::RxBytes, XOspiPsv::SendBufferPtr, XOspiPsv::UnalignReadBuffer, XOspiPsv_Config_Dma, XOspiPsv_Config_IndirectAhb, XOspiPsv_ReadReg, XOspiPsv_Setup_Dev_Read_Instr_Reg, XOspiPsv_Setup_Stig_Ctrl, XOspiPsv_Start_Indr_RdTransfer.
Referenced by XOspiPsv_IntrTransfer.
void XOspiPsv_IntrSendData(XOspiPsv *InstancePtr, XOspiPsv_Msg *Msg)
This function performs an interrupt-based data send operation.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. None.
References XOspiPsv_Msg::Addr, XOspiPsv_Msg::Addrsize, XOspiPsv_Msg::Addrvalid, XOspiPsv_Config::BaseAddress, XOspiPsv_Msg::ByteCount, XOspiPsv::Config, XOspiPsv_Msg::Opcode, XOspiPsv::RecvBufferPtr, XOspiPsv::SendBufferPtr, XOspiPsv_Msg::TxBfrPtr, XOspiPsv::TxBytes, XOspiPsv_FifoWrite, XOspiPsv_ReadReg, XOspiPsv_Setup_Dev_Write_Instr_Reg, XOspiPsv_Setup_Stig_Ctrl.
Referenced by XOspiPsv_IntrTransfer.