xospipsv_sinit.c
XOspiPsv_Config * XOspiPsv_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XOspiPsv_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xospipsv.h for the definition of XOspiPsv_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XOspiPsv_Config::Name, XOspiPsv_ConfigTable.
Referenced by OspiPsvFlashNonBlockingReadExample, OspiPsvInterruptFlashExample, OspiPsvPolledFlashExample.