xospipsv_xfer.c
u32 XOspiPsv_PollRecvData(XOspiPsv *InstancePtr, XOspiPsv_Msg *Msg)
This function performs a polled data receive operation.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. XST_SUCCESS if successful.XST_FAILURE if transfer fails.
References XOspiPsv_Msg::Addrvalid, XOspiPsv_Msg::ByteCount, XOspiPsv::OpMode, XOspiPsv_Msg::Proto, XOspiPsv::RecvBufferPtr, XOspiPsv_Msg::RxBfrPtr, XOspiPsv::RxBytes, XOspiPsv::SendBufferPtr, XOspiPsv_Dac_Read, XOspiPsv_Dma_Read, XOSPIPSV_IDAC_MODE, XOSPIPSV_READ_1_1_1, XOspiPsv_Setup_Dev_Read_Instr_Reg, XOspiPsv_Stig_Read.
Referenced by XOspiPsv_PollTransfer.
u32 XOspiPsv_PollSendData(XOspiPsv *InstancePtr, XOspiPsv_Msg *Msg)
This function performs a polled data send operation.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. XST_SUCCESS if successful.XST_FAILURE if transfer fails.
References XOspiPsv_Msg::ByteCount, XOspiPsv::OpMode, XOspiPsv::RecvBufferPtr, XOspiPsv::SendBufferPtr, XOspiPsv_Msg::TxBfrPtr, XOspiPsv::TxBytes, XOspiPsv_Dac_Write, XOspiPsv_IDac_Write, XOspiPsv_Setup_Dev_Write_Instr_Reg, XOspiPsv_Stig_Write.
Referenced by XOspiPsv_PollTransfer.
void XOspiPsv_IntrRecvData(XOspiPsv *InstancePtr, XOspiPsv_Msg *Msg)
This function performs an interrupt-based data receive operation.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. None.
References XOspiPsv_Msg::Addrsize, XOspiPsv_Msg::Addrvalid, XOspiPsv_Config::BaseAddress, XOspiPsv_Msg::ByteCount, XOspiPsv::Config, XOspiPsv_Msg::Dummy, XOspiPsv::IsUnaligned, XOspiPsv_Msg::Opcode, XOspiPsv::RecvBufferPtr, XOspiPsv_Msg::RxBfrPtr, XOspiPsv::RxBytes, XOspiPsv::SendBufferPtr, XOspiPsv::UnalignReadBuffer, XOspiPsv_Config_Dma, XOspiPsv_Config_IndirectAhb, XOspiPsv_ReadReg, XOspiPsv_Setup_Dev_Read_Instr_Reg, XOspiPsv_Setup_Stig_Ctrl, XOspiPsv_Start_Indr_RdTransfer.
Referenced by XOspiPsv_IntrTransfer.
void XOspiPsv_IntrSendData(XOspiPsv *InstancePtr, XOspiPsv_Msg *Msg)
This function performs an interrupt-based data send operation.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. None.
References XOspiPsv_Msg::Addr, XOspiPsv_Msg::Addrsize, XOspiPsv_Msg::Addrvalid, XOspiPsv_Config::BaseAddress, XOspiPsv_Msg::ByteCount, XOspiPsv::Config, XOspiPsv_Msg::Opcode, XOspiPsv::RecvBufferPtr, XOspiPsv::SendBufferPtr, XOspiPsv_Msg::TxBfrPtr, XOspiPsv::TxBytes, XOspiPsv_FifoWrite, XOspiPsv_ReadReg, XOspiPsv_Setup_Dev_Write_Instr_Reg, XOspiPsv_Setup_Stig_Ctrl.
Referenced by XOspiPsv_IntrTransfer.