xospipsv_hw.c
MAX_STIG_DELAY_CNT
Max STIG delay count.
Referenced by XOspiPsv_Exec_Flash_Cmd.
MAX_DMA_DELAY_CNT
Max DMA delay count.
Referenced by XOspiPsv_Exec_Dma.
LOCK_MAX_DELAY_CNT
Max LOCK delay count.
Referenced by XOspiPsv_WaitForLock.
TERA_MACRO
Macro for 10^12.
Referenced by XOspiPsv_CalculateRxTap.
void XOspiPsv_Setup_Stig_Ctrl(const XOspiPsv *InstancePtr, u32 Cmd_op, u32 Rd_data_en, u32 Num_rd_data_bytes, u32 Cmd_addr_en, u32 Mode_bit_en, u32 Num_addr_bytes, u32 Wr_data_en, u32 Num_wr_data_bytes, u32 Dummy, u32 Membank_en)
Configures the STIG control register (Flash cmd register).
InstancePtr Pointer to the XOspiPsv instance. Cmd_op Command opcode. Rd_data_en Specifies whether cmd_op requires data to read or not. Num_rd_data_bytes Number of bytes to read. Cmd_addr_en Specifies whether cmd_op requires addr or not. Mode_bit_en Represents mode bit configuration register. Num_addr_bytes Represents addr bytes (4/3 etc). Wr_data_en Specifies whether cmd_op requires write enable or not. Num_wr_data_bytes Number of bytes to write. Dummy Number of bytes to write. Membank_en Enables STIG memory bank. None.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config.
Referenced by XOspiPsv_IntrRecvData, XOspiPsv_IntrSendData, XOspiPsv_Stig_Read, XOspiPsv_Stig_Write.
u32 XOspiPsv_Exec_Flash_Cmd(const XOspiPsv *InstancePtr)
Executes the Flash command configured using Flash Command control register.
InstancePtr Pointer to the XOspiPsv instance. XST_SUCCESS if successful. XST_FAILURE if transfer fails. Wait till the command is executed.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, MAX_STIG_DELAY_CNT, XOspiPsv_ReadReg.
Referenced by XOspiPsv_Stig_Read, XOspiPsv_Stig_Write.
void XOspiPsv_FifoRead(XOspiPsv *InstancePtr, XOspiPsv_Msg *Msg)
Reads data from RX FIFO.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. None This operation is in IO mode of reading.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv_Msg::RxBfrPtr, XOspiPsv::RxBytes, XOspiPsv_ReadReg.
Referenced by XOspiPsv_IntrHandler, XOspiPsv_Stig_Read.
void XOspiPsv_FifoWrite(XOspiPsv *InstancePtr, XOspiPsv_Msg *Msg)
Writes data to TX FIFO.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. XST_SUCCESS if successful.XST_FAILURE if transfer fails. This operation is in IO mode of writing.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv_Msg::TxBfrPtr, XOspiPsv::TxBytes.
Referenced by XOspiPsv_IntrSendData, XOspiPsv_Stig_Write.
void XOspiPsv_Setup_Dev_Write_Instr_Reg(const XOspiPsv *InstancePtr, const XOspiPsv_Msg *Msg)
Configures the below info to write instruction register DataXfertype - SPI/Dual/Quad/Octal AddrXfertype - 3 or 4B.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. None Used in DMA or Linear operations.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv::DualByteOpcodeEn, XOspiPsv_Msg::ExtendedOpcode, XOspiPsv_Msg::Opcode, XOspiPsv_Msg::Proto, XOspiPsv_ReadReg.
Referenced by XOspiPsv_IntrSendData, XOspiPsv_PollSendData.
void XOspiPsv_Setup_Dev_Read_Instr_Reg(const XOspiPsv *InstancePtr, const XOspiPsv_Msg *Msg)
Configures the below info to read instruction register DataXfertype - SPI/Dual/Quad/Octal AddrXfertype - 3 or 4B.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. None Used in DMA or Linear operations
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv::DualByteOpcodeEn, XOspiPsv_Msg::Dummy, XOspiPsv_Msg::ExtendedOpcode, XOspiPsv_Msg::IsDDROpCode, XOspiPsv_Msg::Opcode, XOspiPsv_Msg::Proto, XOspiPsv::SdrDdrMode, XOSPIPSV_READ_1_1_1, XOspiPsv_ReadReg.
Referenced by XOspiPsv_IntrRecvData, XOspiPsv_PollRecvData, XOspiPsv_StartDmaTransfer.
void XOspiPsv_Setup_Devsize(const XOspiPsv *InstancePtr, const XOspiPsv_Msg *Msg)
Sets the device size config register.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. None
References XOspiPsv_Msg::Addrsize, XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv_ReadReg.
Referenced by XOspiPsv_IntrTransfer, XOspiPsv_PollTransfer, XOspiPsv_StartDmaTransfer.
void XOspiPsv_Start_Indr_RdTransfer(const XOspiPsv *InstancePtr)
Initiates the indirect read transfer.
InstancePtr Pointer to the XOspiPsv instance. None
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv_ReadReg.
Referenced by XOspiPsv_IntrHandler, XOspiPsv_IntrRecvData.
void XOspiPsv_Config_IndirectAhb(const XOspiPsv *InstancePtr, const XOspiPsv_Msg *Msg)
Configures the Indirect controller.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. None
References XOspiPsv_Msg::Addr, XOspiPsv_Config::BaseAddress, XOspiPsv_Msg::ByteCount, XOspiPsv::Config.
Referenced by XOspiPsv_Dma_Read, XOspiPsv_IntrHandler, XOspiPsv_IntrRecvData, XOspiPsv_StartDmaTransfer.
void XOspiPsv_Config_Dma(const XOspiPsv *InstancePtr, const XOspiPsv_Msg *Msg)
Sets up the Dma configuration.
InstancePtr Pointer to the XOspiPsv instance. Msg Pointer to the structure containing transfer data. None
References XOspiPsv_Config::BaseAddress, XOspiPsv_Msg::ByteCount, XOspiPsv::Config, XOspiPsv_Config::IsCacheCoherent, XOspiPsv_Msg::RxAddr64bit, XOspiPsv_Msg::RxBfrPtr, XOspiPsv_Msg::Xfer64bit, XOSPIPSV_RXADDR_OVER_32BIT.
Referenced by XOspiPsv_Dma_Read, XOspiPsv_IntrHandler, XOspiPsv_IntrRecvData, XOspiPsv_StartDmaTransfer.
u32 XOspiPsv_Exec_Dma(const XOspiPsv *InstancePtr)
Initiates the DMA transfer.
InstancePtr Pointer to the XOspiPsv instance. XST_SUCCESS if successful. XST_FAILURE if transfer fails.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, MAX_DMA_DELAY_CNT, XOspiPsv_ReadReg.
Referenced by XOspiPsv_Dma_Read.
u32 XOspiPsv_WaitForLock(const XOspiPsv *InstancePtr, u32 Mask)
Waits for bit to be set.
This API polls for the required bit for 10 seconds, if not set then timeout occurs. InstancePtr Pointer to the XOspiPsv instance. Mask Bit mask to check for lock. XST_SUCCESS if lock bit is set.XST_FAILURE if fails.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, LOCK_MAX_DELAY_CNT.
Referenced by XOspiPsv_ConfigureTaps, XOspiPsv_ExecuteRxTuning, XOspiPsv_SetDllDelay.
u32 XOspiPsv_CalculateRxTap(XOspiPsv *InstancePtr, XOspiPsv_Msg *FlashMsg, u8 *AvgRXTap, u8 *MaxWindowSize, u8 DummyIncr, u32 TXTap)
Calculates the Max window size and the corresponding Average Rx Tap.
InstancePtr Pointer to the XOspiPsv instance. FlashMsg Pointer to XOspiPsv_Msg instance. AvgRXTap Pointer to median Rx Tap. MaxWindowSize Pointer to maximum window size. DummyIncr Flag to indicate additional dummy. TXTap Tx tap value used while doing Rx tuning. XST_SUCCESS if lock bit is set.XST_FAILURE if fails.
References XOspiPsv_Config::BaseAddress, XOspiPsv::Config, XOspiPsv::DeviceIdData, XOspiPsv::DllMode, XOspiPsv::Extra_DummyCycle, XOspiPsv_Config::InputClockHz, XOspiPsv_Msg::RxBfrPtr, TERA_MACRO, XOspiPsv_ConfigureTaps, XOspiPsv_PollTransfer, XOspiPsv_ReadReg.
Referenced by XOspiPsv_ExecuteRxTuning.