qspips
XQSPIPS_CLK_ACTIVE_LOW_OPTION
Active Low Clock option.
XQSPIPS_CLK_PHASE_1_OPTION
Clock Phase one option.
XQSPIPS_FORCE_SSELECT_OPTION
Force Slave Select.
Referenced by DualStackExample, LinearQspiFlashExample, QspiFlashIntrExample, QspiFlashPolledExample, QspiG128FlashExample.
XQSPIPS_MANUAL_START_OPTION
Manual Start enable.
Referenced by DualStackExample, LinearQspiFlashExample, QspiFlashIntrExample, QspiFlashPolledExample, QspiG128FlashExample.
XQSPIPS_LQSPI_MODE_OPTION
Linear QPSI mode.
Referenced by DualStackExample, LinearQspiFlashExample, XQspiPs_GetOptions, XQspiPs_SetOptions.
XQSPIPS_HOLD_B_DRIVE_OPTION
Drive HOLD_B Pin.
Referenced by DualStackExample, LinearQspiFlashExample, QspiFlashIntrExample, QspiFlashPolledExample, QspiG128FlashExample.
XQSPIPS_CLK_PRESCALE_2
PCLK/2 Prescaler.
XQSPIPS_CLK_PRESCALE_4
PCLK/4 Prescaler.
XQSPIPS_CLK_PRESCALE_8
PCLK/8 Prescaler.
Referenced by DualStackExample, LinearQspiFlashExample, QspiFlashIntrExample, QspiFlashPolledExample, QspiG128FlashExample.
XQSPIPS_CLK_PRESCALE_16
PCLK/16 Prescaler.
XQSPIPS_CLK_PRESCALE_32
PCLK/32 Prescaler.
XQSPIPS_CLK_PRESCALE_64
PCLK/64 Prescaler.
XQSPIPS_CLK_PRESCALE_128
PCLK/128 Prescaler.
XQSPIPS_CLK_PRESCALE_256
PCLK/256 Prescaler.
XQSPIPS_EVENT_TRANSFER_DONE
Transfer done.
XQSPIPS_EVENT_TRANSMIT_UNDERRUN
TX FIFO empty.
XQSPIPS_EVENT_RECEIVE_OVERRUN
Receive data loss because RX FIFO full.
XQSPIPS_FLASH_OPCODE_WRSR
XQSPIPS_FLASH_OPCODE_PP
XQSPIPS_FLASH_OPCODE_NORM_READ
XQSPIPS_FLASH_OPCODE_WRDS
XQSPIPS_FLASH_OPCODE_RDSR1
XQSPIPS_FLASH_OPCODE_WREN
XQSPIPS_FLASH_OPCODE_FAST_READ
XQSPIPS_FLASH_OPCODE_BE_4K
XQSPIPS_FLASH_OPCODE_RDSR2
XQSPIPS_FLASH_OPCODE_DUAL_READ
XQSPIPS_FLASH_OPCODE_BE_32K
XQSPIPS_FLASH_OPCODE_QUAD_READ
XQSPIPS_FLASH_OPCODE_ERASE_SUS
XQSPIPS_FLASH_OPCODE_ERASE_RES
XQSPIPS_FLASH_OPCODE_RDID
XQSPIPS_FLASH_OPCODE_BE
XQSPIPS_FLASH_OPCODE_SE
XQSPIPS_FLASH_OPCODE_DUAL_IO_READ
XQSPIPS_FLASH_OPCODE_QUAD_IO_READ
XQSPIPS_FLASH_OPCODE_BRWR
XQSPIPS_FLASH_OPCODE_BRRD
XQSPIPS_FLASH_OPCODE_EARWR
XQSPIPS_FLASH_OPCODE_EARRD
XQSPIPS_FLASH_OPCODE_DIE_ERASE
XQSPIPS_FLASH_OPCODE_READ_FLAG_SR
XQSPIPS_FLASH_OPCODE_CLEAR_FLAG_SR
XQSPIPS_FLASH_OPCODE_READ_LOCK_REG
XQSPIPS_FLASH_OPCODE_WRITE_LOCK_REG
XQSPIPS_SIZE_ONE
XQSPIPS_SIZE_TWO
XQSPIPS_SIZE_THREE
XQSPIPS_SIZE_FOUR
XQSPIPS_CONNECTION_MODE_SINGLE
XQSPIPS_CONNECTION_MODE_STACKED
XQSPIPS_CONNECTION_MODE_PARALLEL
XQSPIPS_RXFIFO_THRESHOLD_OPT
XQSPIPS_CR_PRESC_DIV_BY_4
XQSPIPS_CR_OFFSET
Configuration Register.
Referenced by XQspiPs_Abort, XQspiPs_GetClkPrescaler, XQspiPs_GetOptions, XQspiPs_InterruptHandler, XQspiPs_LinearInit, XQspiPs_PolledTransfer, XQspiPs_Reset, XQspiPs_ResetHw, XQspiPs_SetClkPrescaler, XQspiPs_SetOptions, XQspiPs_SetSlaveSelect, XQspiPs_Transfer.
XQSPIPS_SR_OFFSET
Interrupt Status.
Referenced by XQspiPs_InterruptHandler, XQspiPs_PolledTransfer, XQspiPs_ResetHw, XQspiPs_Transfer.
XQSPIPS_IER_OFFSET
Interrupt Enable.
Referenced by XQspiPs_InterruptHandler, XQspiPs_Transfer.
XQSPIPS_IDR_OFFSET
Interrupt Disable.
Referenced by XQspiPs_InterruptHandler, XQspiPs_ResetHw.
XQSPIPS_IMR_OFFSET
Interrupt Enabled Mask.
XQSPIPS_ER_OFFSET
Enable/Disable Register.
Referenced by XQspiPs_LinearInit, XQspiPs_ResetHw.
XQSPIPS_DR_OFFSET
Delay Register.
Referenced by XQspiPs_GetDelays, XQspiPs_SetDelays.
XQSPIPS_TXD_00_OFFSET
Transmit 4-byte inst/data.
Referenced by XQspiPs_InterruptHandler, XQspiPs_PolledTransfer, XQspiPs_Transfer.
XQSPIPS_RXD_OFFSET
Data Receive Register.
Referenced by XQspiPs_InterruptHandler, XQspiPs_PolledTransfer, XQspiPs_ResetHw.
XQSPIPS_SICR_OFFSET
Slave Idle Count.
XQSPIPS_TXWR_OFFSET
Transmit FIFO Watermark.
Referenced by XQspiPs_Abort, XQspiPs_ResetHw.
XQSPIPS_RXWR_OFFSET
Receive FIFO Watermark.
Referenced by XQspiPs_Abort, XQspiPs_InterruptHandler, XQspiPs_PolledTransfer, XQspiPs_ResetHw, XQspiPs_Transfer.
XQSPIPS_GPIO_OFFSET
GPIO Register.
XQSPIPS_LPBK_DLY_ADJ_OFFSET
Loopback Delay Adjust Reg.
XQSPIPS_TXD_01_OFFSET
Transmit 1-byte inst.
Referenced by XQspiPs_PolledTransfer, XQspiPs_Transfer.
XQSPIPS_TXD_10_OFFSET
Transmit 2-byte inst.
Referenced by XQspiPs_PolledTransfer, XQspiPs_Transfer.
XQSPIPS_TXD_11_OFFSET
Transmit 3-byte inst.
Referenced by XQspiPs_PolledTransfer, XQspiPs_Transfer.
XQSPIPS_LQSPI_CR_OFFSET
Linear QSPI config register.
Referenced by XQspiPs_GetOptions, XQspiPs_LinearInit, XQspiPs_ResetHw, XQspiPs_SetOptions.
XQSPIPS_LQSPI_SR_OFFSET
Linear QSPI status register.
XQSPIPS_MOD_ID_OFFSET
Module ID register.
XQSPIPS_CR_IFMODE_MASK
Flash mem interface mode.
XQSPIPS_CR_ENDIAN_MASK
Tx/Rx FIFO endianness.
XQSPIPS_CR_MANSTRT_MASK
Manual Transmission Start.
Referenced by XQspiPs_InterruptHandler, XQspiPs_PolledTransfer, XQspiPs_Transfer.
XQSPIPS_CR_MANSTRTEN_MASK
Manual Transmission Start Enable.
XQSPIPS_CR_SSFORCE_MASK
Force Slave Select.
Referenced by XQspiPs_Abort, XQspiPs_ResetHw.
XQSPIPS_CR_SSCTRL_MASK
Slave Select Decode.
Referenced by XQspiPs_Abort, XQspiPs_InterruptHandler, XQspiPs_LinearInit, XQspiPs_PolledTransfer, XQspiPs_ResetHw, XQspiPs_SetSlaveSelect, XQspiPs_Transfer.
XQSPIPS_CR_SSCTRL_SHIFT
Slave Select Decode shift.
XQSPIPS_CR_DATA_SZ_MASK
Size of word to be transferred.
XQSPIPS_CR_PRESC_MASK
Prescaler Setting.
Referenced by XQspiPs_GetClkPrescaler, XQspiPs_LinearInit, XQspiPs_SetClkPrescaler.
XQSPIPS_CR_PRESC_SHIFT
Prescaler shift.
Referenced by XQspiPs_GetClkPrescaler, XQspiPs_LinearInit, XQspiPs_SetClkPrescaler.
XQSPIPS_CR_PRESC_MAXIMUM
Prescaler maximum value.
Referenced by XQspiPs_SetClkPrescaler.
XQSPIPS_CR_CPHA_MASK
Phase Configuration.
XQSPIPS_CR_CPOL_MASK
Polarity Configuration.
XQSPIPS_CR_MSTREN_MASK
Master Mode Enable.
XQSPIPS_CR_HOLD_B_MASK
HOLD_B Pin Drive Enable.
XQSPIPS_CR_REF_CLK_MASK
Ref clk bit - should be 0.
XQSPIPS_CR_RESET_MASK_SET
XQSPIPS_CR_RESET_MASK_CLR
XQSPIPS_IXR_TXUF_MASK
QSPI Tx FIFO Underflow.
Referenced by XQspiPs_InterruptHandler, XQspiPs_Transfer.
XQSPIPS_IXR_RXFULL_MASK
QSPI Rx FIFO Full.
XQSPIPS_IXR_RXNEMPTY_MASK
QSPI Rx FIFO Not Empty.
Referenced by XQspiPs_InterruptHandler, XQspiPs_PolledTransfer, XQspiPs_ResetHw, XQspiPs_Transfer.
XQSPIPS_IXR_TXFULL_MASK
QSPI Tx FIFO Full.
XQSPIPS_IXR_TXOW_MASK
QSPI Tx FIFO Overwater.
Referenced by XQspiPs_InterruptHandler, XQspiPs_PolledTransfer, XQspiPs_Transfer.
XQSPIPS_IXR_RXOVR_MASK
QSPI Rx FIFO Overrun.
Referenced by XQspiPs_InterruptHandler, XQspiPs_Transfer.
XQSPIPS_IXR_DFLT_MASK
QSPI default interrupts mask.
XQSPIPS_IXR_WR_TO_CLR_MASK
Interrupts which need write to clear.
Referenced by XQspiPs_InterruptHandler, XQspiPs_ResetHw, XQspiPs_Transfer.
XQSPIPS_ISR_RESET_STATE
Default to tx/rx empty.
XQSPIPS_IXR_DISABLE_ALL
Disable all interrupts.
Referenced by XQspiPs_ResetHw.
XQSPIPS_ER_ENABLE_MASK
QSPI Enable Bit Mask.
Referenced by XQspiPs_LinearInit.
XQSPIPS_DR_NSS_MASK
Delay to de-assert slave select between two words mask.
Referenced by XQspiPs_GetDelays.
XQSPIPS_DR_NSS_SHIFT
Delay to de-assert slave select between two words shift.
Referenced by XQspiPs_GetDelays, XQspiPs_SetDelays.
XQSPIPS_DR_BTWN_MASK
Delay Between Transfers mask.
Referenced by XQspiPs_GetDelays.
XQSPIPS_DR_BTWN_SHIFT
Delay Between Transfers shift.
Referenced by XQspiPs_GetDelays, XQspiPs_SetDelays.
XQSPIPS_DR_AFTER_MASK
Delay After Transfers mask.
Referenced by XQspiPs_GetDelays.
XQSPIPS_DR_AFTER_SHIFT
Delay After Transfers shift.
Referenced by XQspiPs_GetDelays, XQspiPs_SetDelays.
XQSPIPS_DR_INIT_MASK
Delay Initially mask.
Referenced by XQspiPs_GetDelays.
XQSPIPS_SICR_MASK
Slave Idle Count Mask.
XQSPIPS_TXWR_MASK
Transmit Watermark Mask.
Referenced by XQspiPs_ResetHw.
XQSPIPS_TXWR_RESET_VALUE
Transmit Watermark register reset value.
Referenced by XQspiPs_Abort, XQspiPs_ResetHw.
XQSPIPS_RXWR_MASK
Receive Watermark Mask.
Referenced by XQspiPs_ResetHw.
XQSPIPS_RXWR_RESET_VALUE
Receive Watermark register reset value.
Referenced by XQspiPs_Abort, XQspiPs_InterruptHandler, XQspiPs_PolledTransfer, XQspiPs_ResetHw.
XQSPIPS_FIFO_DEPTH
FIFO depth (words)
Referenced by XQspiPs_PolledTransfer, XQspiPs_Transfer.
XQSPIPS_LQSPI_CR_LINEAR_MASK
LQSPI mode enable.
Referenced by XQspiPs_GetOptions, XQspiPs_LqspiRead, XQspiPs_SetOptions.
XQSPIPS_LQSPI_CR_TWO_MEM_MASK
Both memories or one.
Referenced by XQspiPs_LinearInit.
XQSPIPS_LQSPI_CR_SEP_BUS_MASK
Separate memory bus.
Referenced by XQspiPs_LinearInit.
XQSPIPS_LQSPI_CR_U_PAGE_MASK
Upper memory page.
Referenced by FlashErase, GetRealAddr.
XQSPIPS_LQSPI_CR_MODE_EN_MASK
Enable mode bits.
XQSPIPS_LQSPI_CR_MODE_ON_MASK
Mode on.
XQSPIPS_LQSPI_CR_MODE_BITS_MASK
Mode value for dual I/O or quad I/O.
XQSPIPS_LQSPI_CR_DUMMY_MASK
Number of dummy bytes between addr and return read data.
XQSPIPS_LQSPI_CR_INST_MASK
Read instr code.
XQSPIPS_LQSPI_CR_RST_STATE
Default CR value.
Referenced by XQspiPs_LinearInit, XQspiPs_SetOptions.
XQSPIPS_LQSPI_SR_D_FSM_ERR_MASK
AXI Data FSM Error received.
XQSPIPS_LQSPI_SR_WR_RECVD_MASK
AXI write command received.
XQSPIPS_LPBK_DLY_ADJ_USE_LPBK_MASK
Loopback Bit.
SLCR_LOCK
SLCR Write Protection Lock.
Referenced by XQspiPs_Abort.
SLCR_UNLOCK
SLCR Write Protection Unlock.
Referenced by XQspiPs_Abort.
LQSPI_RST_CTRL
Quad SPI Software Reset Control.
Referenced by XQspiPs_Abort.
SLCR_LOCKSTA
SLCR Write Protection status.
Referenced by XQspiPs_Abort.
XPAR_XSLCR_0_BASEADDR
SLCR_LOCK_MASK
Write Protection Lock mask.
Referenced by XQspiPs_Abort.
SLCR_UNLOCK_MASK
SLCR Write Protection Unlock.
Referenced by XQspiPs_Abort.
LQSPI_RST_CTRL_MASK
Quad SPI Software Reset Control.
Referenced by XQspiPs_Abort.
typedef void(* XQspiPs_StatusHandler)(void *CallBackRef, u32 StatusEvent, unsigned ByteCount))(void *CallBackRef, u32 StatusEvent, unsigned ByteCount)
The handler data type allows the user to define a callback function to handle the asynchronous processing for the QSPI device.
The application using this driver is expected to define a handler of this type to support interrupt driven mode. The handler executes in an interrupt context, so only minimal processing should be performed. CallBackRef is the callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. Its type is not important to the driver, so it is a void pointer. StatusEvent holds one or more status events that have occurred. See the XQspiPs_SetStatusHandler() for details on the status events that can be passed in the callback. ByteCount indicates how many bytes of data were successfully transferred. This may be less than the number of bytes requested if the status event indicates an error.
XQspiPsInstFormat FlashInst[][]
XQspiPs_Config XQspiPs_ConfigTable[XPAR_XQSPIPS_NUM_INSTANCES][XPAR_XQSPIPS_NUM_INSTANCES]
This table contains configuration information for each QSPI device in the system.
OptionsMap OptionsTable[][]
XQspiPs_Config XQspiPs_ConfigTable[][]
This table contains configuration information for each QSPI device in the system.
static void XQspiPs_GetReadData(XQspiPs *InstancePtr, u32 Data, u8 Size)
Copies data from Data to the Receive buffer.
InstancePtr is a pointer to the XQspiPs instance. Data is the data which needs to be copied to the Rx buffer. Size is the number of bytes to be copied to the Receive buffer. None. None.
static void StubStatusHandler(void *CallBackRef, u32 StatusEvent, unsigned ByteCount)
This is a stub for the status callback.
The stub is here in case the upper layers forget to set the handler. CallBackRef is a pointer to the upper layer callback reference StatusEvent is the event that just occurred. ByteCount is the number of bytes transferred up until the event occurred. None. None.
int XQspiPs_CfgInitialize(XQspiPs *InstancePtr, XQspiPs_Config *ConfigPtr, u32 EffectiveAddr)
Initializes a specific XQspiPs instance such that the driver is ready to use.
The state of the device after initialization is: Master modeActive high clock polarityClock phase 0Baud rate divisor 2Transfer width 32Master reference clock = pclkNo chip select activeManual CS and Manual Start disabled InstancePtr is a pointer to the XQspiPs instance. ConfigPtr is a reference to a structure containing information about a specific QSPI device. This function initializes an InstancePtr object for a specific device specified by the contents of Config. EffectiveAddr is the device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, use ConfigPtr->Config.BaseAddress for this device. XST_SUCCESS if successful.XST_DEVICE_IS_STARTED if the device is already started. It must be stopped to re-initialize. None.
References XQspiPs_Config::BaseAddress, XQspiPs::Config, XQspiPs_Config::ConnectionMode, XQspiPs::IsBusy, XQspiPs::IsReady, XQspiPs::RecvBufferPtr, XQspiPs::RemainingBytes, XQspiPs::RequestedBytes, XQspiPs::SendBufferPtr, XQspiPs_Reset.
Referenced by DualStackExample, LinearQspiFlashExample, QspiFlashIntrExample, QspiFlashPolledExample, QspiG128FlashExample, QspiPsSelfTestExample.
void XQspiPs_Reset(XQspiPs *InstancePtr)
Resets the QSPI device.
Reset must only be called after the driver has been initialized. Any data transfer that is in progress is aborted.The upper layer software is responsible for re-configuring (if necessary) and restarting the QSPI device after the reset. InstancePtr is a pointer to the XQspiPs instance. None. None.
References XQspiPs_Config::BaseAddress, XQspiPs::Config, XQspiPs::IsReady, XQspiPs_Abort, XQSPIPS_CR_OFFSET, XQspiPs_ReadReg, XQspiPs_WriteReg.
Referenced by XQspiPs_CfgInitialize, XQspiPs_SelfTest.
void XQspiPs_Abort(XQspiPs *InstancePtr)
Aborts a transfer in progress by disabling the device and flush the RxFIFO.
The byte counts are cleared, the busy flag is cleared. InstancePtr is a pointer to the XQspiPs instance. None. This function does a read/modify/write of the config register. The user of this function needs to take care of critical sections.
References XQspiPs_Config::BaseAddress, XQspiPs::Config, XQspiPs::IsBusy, LQSPI_RST_CTRL, LQSPI_RST_CTRL_MASK, XQspiPs::RemainingBytes, XQspiPs::RequestedBytes, SLCR_LOCK, SLCR_LOCK_MASK, SLCR_LOCKSTA, SLCR_UNLOCK, SLCR_UNLOCK_MASK, XQSPIPS_CR_OFFSET, XQSPIPS_CR_SSCTRL_MASK, XQSPIPS_CR_SSFORCE_MASK, XQspiPs_Disable, XQspiPs_ReadReg, XQSPIPS_RXWR_OFFSET, XQSPIPS_RXWR_RESET_VALUE, XQSPIPS_TXWR_OFFSET, XQSPIPS_TXWR_RESET_VALUE, XQspiPs_WriteReg.
Referenced by XQspiPs_Reset.
s32 XQspiPs_Transfer(XQspiPs *InstancePtr, u8 *SendBufPtr, u8 *RecvBufPtr, u32 ByteCount)
Transfers specified data on the QSPI bus.
Initiates bus communication and sends/receives data to/from the selected QSPI slave. For every byte sent, a byte is received.The caller has the option of providing two different buffers for send and receive, or one buffer for both send and receive, or no buffer for receive. The receive buffer must be at least as big as the send buffer to prevent unwanted memory writes. This implies that the byte count passed in as an argument must be the smaller of the two buffers if they differ in size. Here are some sample usages: XQspiPs_Transfer(InstancePtr, SendBuf, RecvBuf, ByteCount) The caller wishes to send and receive, and provides two different buffers for send and receive. XQspiPs_Transfer(InstancePtr, SendBuf, NULL, ByteCount) The caller wishes only to send and does not care about the received data. The driver ignores the received data in this case. XQspiPs_Transfer(InstancePtr, SendBuf, SendBuf, ByteCount) The caller wishes to send and receive, but provides the same buffer for doing both. The driver sends the data and overwrites the send buffer with received data as it transfers the data. XQspiPs_Transfer(InstancePtr, RecvBuf, RecvBuf, ByteCount) The caller wishes to only receive and does not care about sending data. In this case, the caller must still provide a send buffer, but it can be the same as the receive buffer if the caller does not care what it sends. The device must send N bytes of data if it wishes to receive N bytes of data. Although this function takes entire buffers as arguments, the driver can only transfer a limited number of bytes at a time, limited by the size of the FIFO. A call to this function only starts the transfer, then subsequent transfers of the data is performed by the interrupt service routine until the entire buffer has been transferred. The status callback function is called when the entire buffer has been sent/received.This function is non-blocking. The SetSlaveSelect function must be called prior to this function. InstancePtr is a pointer to the XQspiPs instance. SendBufPtr is a pointer to a data buffer that needs to be transmitted. This buffer must not be NULL. RecvBufPtr is a pointer to a buffer for received data. This argument can be NULL if do not care about receiving. ByteCount contains the number of bytes to send/receive. The number of bytes received always equals the number of bytes sent. XST_SUCCESS if the buffers are successfully handed off to the device for transfer.XST_DEVICE_BUSY indicates that a data transfer is already in progress. This is determined by the driver. This function is not thread-safe. The higher layer software must ensure that no two threads are transferring data on the QSPI bus at the same time.
References XQspiPs_Config::BaseAddress, XQspiPs::Config, XQspiPs::IsBusy, XQspiPs::IsReady, XQspiPs::RecvBufferPtr, XQspiPs::RemainingBytes, XQspiPs::RequestedBytes, XQspiPs::SendBufferPtr, XQspiPs::ShiftReadData, XQSPIPS_CR_MANSTRT_MASK, XQSPIPS_CR_OFFSET, XQSPIPS_CR_SSCTRL_MASK, XQspiPs_Enable, XQSPIPS_FIFO_DEPTH, XQSPIPS_IER_OFFSET, XQSPIPS_IXR_RXNEMPTY_MASK, XQSPIPS_IXR_RXOVR_MASK, XQSPIPS_IXR_TXOW_MASK, XQSPIPS_IXR_TXUF_MASK, XQSPIPS_IXR_WR_TO_CLR_MASK, XQspiPs_ReadReg, XQSPIPS_RXWR_OFFSET, XQSPIPS_SR_OFFSET, XQSPIPS_TXD_00_OFFSET, XQSPIPS_TXD_01_OFFSET, XQSPIPS_TXD_10_OFFSET, XQSPIPS_TXD_11_OFFSET, XQspiPs_WriteReg.
Referenced by FlashRead.
s32 XQspiPs_PolledTransfer(XQspiPs *InstancePtr, u8 *SendBufPtr, u8 *RecvBufPtr, u32 ByteCount)
Transfers specified data on the QSPI bus in polled mode.
The caller has the option of providing two different buffers for send and receive, or one buffer for both send and receive, or no buffer for receive. The receive buffer must be at least as big as the send buffer to prevent unwanted memory writes. This implies that the byte count passed in as an argument must be the smaller of the two buffers if they differ in size. Here are some sample usages: XQspiPs_PolledTransfer(InstancePtr, SendBuf, RecvBuf, ByteCount) The caller wishes to send and receive, and provides two different buffers for send and receive. XQspiPs_PolledTransfer(InstancePtr, SendBuf, NULL, ByteCount) The caller wishes only to send and does not care about the received data. The driver ignores the received data in this case. XQspiPs_PolledTransfer(InstancePtr, SendBuf, SendBuf, ByteCount) The caller wishes to send and receive, but provides the same buffer for doing both. The driver sends the data and overwrites the send buffer with received data as it transfers the data. XQspiPs_PolledTransfer(InstancePtr, RecvBuf, RecvBuf, ByteCount) The caller wishes to only receive and does not care about sending data. In this case, the caller must still provide a send buffer, but it can be the same as the receive buffer if the caller does not care what it sends. The device must send N bytes of data if it wishes to receive N bytes of data. InstancePtr is a pointer to the XQspiPs instance. SendBufPtr is a pointer to a data buffer that needs to be transmitted. This buffer must not be NULL. RecvBufPtr is a pointer to a buffer for received data. This argument can be NULL if do not care about receiving. ByteCount contains the number of bytes to send/receive. The number of bytes received always equals the number of bytes sent. XST_SUCCESS if the buffers are successfully handed off to the device for transfer.XST_DEVICE_BUSY indicates that a data transfer is already in progress. This is determined by the driver. This function is not thread-safe. The higher layer software must ensure that no two threads are transferring data on the QSPI bus at the same time.
References XQspiPs_Config::BaseAddress, XQspiPs::Config, XQspiPs::IsBusy, XQspiPs::IsReady, XQspiPs::RecvBufferPtr, XQspiPs::RemainingBytes, XQspiPs::RequestedBytes, XQspiPs::SendBufferPtr, XQspiPs::ShiftReadData, XQSPIPS_CR_MANSTRT_MASK, XQSPIPS_CR_OFFSET, XQSPIPS_CR_SSCTRL_MASK, XQspiPs_Disable, XQspiPs_Enable, XQSPIPS_FIFO_DEPTH, XQSPIPS_IXR_RXNEMPTY_MASK, XQSPIPS_IXR_TXOW_MASK, XQspiPs_ReadReg, XQSPIPS_RXD_OFFSET, XQSPIPS_RXWR_OFFSET, XQSPIPS_RXWR_RESET_VALUE, XQSPIPS_SR_OFFSET, XQSPIPS_TXD_00_OFFSET, XQSPIPS_TXD_01_OFFSET, XQSPIPS_TXD_10_OFFSET, XQSPIPS_TXD_11_OFFSET, XQspiPs_WriteReg.
Referenced by BulkErase, DieErase, FlashErase, FlashQuadEnable, FlashRead, FlashReadID, FlashWrite, SendBankSelect.
int XQspiPs_LqspiRead(XQspiPs *InstancePtr, u8 *RecvBufPtr, u32 Address, unsigned ByteCount)
Read the flash in Linear QSPI mode.
InstancePtr is a pointer to the XQspiPs instance. RecvBufPtr is a pointer to a buffer for received data. Address is the starting address within the flash from from where data needs to be read. ByteCount contains the number of bytes to receive. XST_SUCCESS if read is performedXST_FAILURE if Linear mode is not set None.
References XQspiPs::IsReady, XQspiPs_Disable, XQspiPs_Enable, XQspiPs_GetLqspiConfigReg, XQSPIPS_LQSPI_CR_LINEAR_MASK.
Referenced by DualStackExample, LinearQspiFlashExample.
int XQspiPs_SetSlaveSelect(XQspiPs *InstancePtr)
Selects the slave with which the master communicates.
The user is not allowed to select the slave while a transfer is in progress. InstancePtr is a pointer to the XQspiPs instance. XST_SUCCESS if the slave is selected or deselected successfully.XST_DEVICE_BUSY if a transfer is in progress, slave cannot be changed. This function only sets the slave which will be selected when a transfer occurs. The slave is not selected when the QSPI is idle.
References XQspiPs_Config::BaseAddress, XQspiPs::Config, XQspiPs::IsBusy, XQspiPs::IsReady, XQSPIPS_CR_OFFSET, XQSPIPS_CR_SSCTRL_MASK, XQspiPs_ReadReg, XQspiPs_WriteReg.
Referenced by DualStackExample, FlashErase, GetRealAddr, LinearQspiFlashExample, QspiFlashIntrExample, QspiFlashPolledExample, QspiG128FlashExample, XQspiPs_SetOptions.
void XQspiPs_SetStatusHandler(XQspiPs *InstancePtr, void *CallBackRef, XQspiPs_StatusHandler FuncPtr)
Sets the status callback function, the status handler, which the driver calls when it encounters conditions that should be reported to upper layer software.
The handler executes in an interrupt context, so it must minimize the amount of processing performed. One of the following status events is passed to the status handler.XST_SPI_TRANSFER_DONE The requested data transfer is doneXST_SPI_TRANSMIT_UNDERRUN As a slave device, the master clocked data but there were none available in the transmit register/FIFO. This typically means the slave application did not issue a transfer request fast enough, or the processor/driver could not fill the transmit register/FIFO fast enough.XST_SPI_RECEIVE_OVERRUN The QSPI device lost data. Data was received but the receive data register/FIFO was full. InstancePtr is a pointer to the XQspiPs instance. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. FuncPtr is the pointer to the callback function. None. The handler is called within interrupt context, so it should do its work quickly and queue potentially time-consuming work to a task-level thread.
References XQspiPs::IsReady, XQspiPs::StatusRef.
Referenced by QspiFlashIntrExample.
void XQspiPs_InterruptHandler(void *InstancePtr)
The interrupt handler for QSPI interrupts.
This function must be connected by the user to an interrupt controller.The interrupts that are handled are: Data Transmit Register (FIFO) Empty. This interrupt is generated when the transmit register or FIFO is empty. The driver uses this interrupt during a transmission to continually send/receive data until the transfer is done.Data Transmit Register (FIFO) Underflow. This interrupt is generated when the QSPI device, when configured as a slave, attempts to read an empty DTR/FIFO. An empty DTR/FIFO usually means that software is not giving the device data in a timely manner. No action is taken by the driver other than to inform the upper layer software of the error.Data Receive Register (FIFO) Overflow. This interrupt is generated when the QSPI device attempts to write a received byte to an already full DRR/FIFO. A full DRR/FIFO usually means software is not emptying the data in a timely manner. No action is taken by the driver other than to inform the upper layer software of the error. InstancePtr is a pointer to the XQspiPs instance. None. The slave select register is being set to deselect the slave when a transfer is complete.
References XQspiPs_Config::BaseAddress, XQspiPs::Config, XQspiPs::IsBusy, XQspiPs::IsReady, XQspiPs::RecvBufferPtr, XQspiPs::RemainingBytes, XQspiPs::RequestedBytes, XQspiPs::SendBufferPtr, XQspiPs::StatusRef, XQSPIPS_CR_MANSTRT_MASK, XQSPIPS_CR_OFFSET, XQSPIPS_CR_SSCTRL_MASK, XQspiPs_Disable, XQSPIPS_IDR_OFFSET, XQSPIPS_IER_OFFSET, XQSPIPS_IXR_RXNEMPTY_MASK, XQSPIPS_IXR_RXOVR_MASK, XQSPIPS_IXR_TXOW_MASK, XQSPIPS_IXR_TXUF_MASK, XQSPIPS_IXR_WR_TO_CLR_MASK, XQspiPs_ReadReg, XQSPIPS_RXD_OFFSET, XQSPIPS_RXWR_OFFSET, XQSPIPS_RXWR_RESET_VALUE, XQSPIPS_SR_OFFSET, XQSPIPS_TXD_00_OFFSET, XQspiPs_WriteReg.
Referenced by QspiFlashIntrExample.
XQspiPs_Config * XQspiPs_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XQspiPs_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xqspips.h for the definition of XQspiPs_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XQspiPs_Config::Name.
Referenced by DualStackExample, LinearQspiFlashExample, QspiFlashIntrExample, QspiFlashPolledExample, QspiG128FlashExample, QspiPsSelfTestExample.
int XQspiPs_SelfTest(XQspiPs *InstancePtr)
Runs a self-test on the driver/device.
The self-test is destructive in that a reset of the device is performed in order to check the reset values of the registers and to get the device into a known state.Upon successful return from the self-test, the device is reset. InstancePtr is a pointer to the XQspiPs instance. XST_SUCCESS if successful XST_REGISTER_ERROR indicates a register did not read or write correctly. None.
References XQspiPs::IsReady, XQspiPs_GetDelays, XQspiPs_Reset, XQspiPs_SetDelays.
Referenced by DualStackExample, LinearQspiFlashExample, QspiFlashIntrExample, QspiFlashPolledExample, QspiG128FlashExample, QspiPsSelfTestExample.
s32 XQspiPs_SetOptions(XQspiPs *InstancePtr, u32 Options)
This function sets the options for the QSPI device driver.
The options control how the device behaves relative to the QSPI bus. The device must be idle rather than busy transferring data before setting these device options. InstancePtr is a pointer to the XQspiPs instance. Options contains the specified options to be set. This is a bit mask where a 1 means to turn the option on, and a 0 means to turn the option off. One or more bit values may be contained in the mask. See the bit definitions named XQSPIPS_*_OPTIONS in the file xqspips.h. XST_SUCCESS if options are successfully set.XST_DEVICE_BUSY if the device is currently transferring data. The transfer must complete or be aborted before setting options. This function is not thread-safe.
References XQspiPs_Config::BaseAddress, XQspiPs::Config, XQspiPs::IsBusy, XQspiPs::IsReady, XQSPIPS_CR_OFFSET, XQSPIPS_LQSPI_CR_LINEAR_MASK, XQSPIPS_LQSPI_CR_OFFSET, XQSPIPS_LQSPI_CR_RST_STATE, XQSPIPS_LQSPI_MODE_OPTION, XQspiPs_ReadReg, XQspiPs_SetSlaveSelect, XQspiPs_WriteReg.
Referenced by DualStackExample, LinearQspiFlashExample, QspiFlashIntrExample, QspiFlashPolledExample, QspiG128FlashExample.
u32 XQspiPs_GetOptions(XQspiPs *InstancePtr)
This function gets the options for the QSPI device.
The options control how the device behaves relative to the QSPI bus. InstancePtr is a pointer to the XQspiPs instance. Options contains the specified options currently set. This is a bit value where a 1 means the option is on, and a 0 means the option is off. See the bit definitions named XQSPIPS_*_OPTIONS in file xqspips.h.None.
References XQspiPs_Config::BaseAddress, XQspiPs::Config, XQspiPs::IsReady, XQSPIPS_CR_OFFSET, XQSPIPS_LQSPI_CR_LINEAR_MASK, XQSPIPS_LQSPI_CR_OFFSET, XQSPIPS_LQSPI_MODE_OPTION, XQspiPs_ReadReg.
s32 XQspiPs_SetClkPrescaler(XQspiPs *InstancePtr, u8 Prescaler)
This function sets the clock prescaler for an QSPI device.
The device must be idle rather than busy transferring data before setting these device options. InstancePtr is a pointer to the XQspiPs instance. Prescaler is the value that determine how much the clock should be divided by. Use the XQSPIPS_CLK_PRESCALE_* constants defined in xqspips.h for this setting. XST_SUCCESS if options are successfully set.XST_DEVICE_BUSY if the device is currently transferring data. The transfer must complete or be aborted before setting options. This function is not thread-safe.
References XQspiPs_Config::BaseAddress, XQspiPs::Config, XQspiPs::IsBusy, XQspiPs::IsReady, XQSPIPS_CR_OFFSET, XQSPIPS_CR_PRESC_MASK, XQSPIPS_CR_PRESC_MAXIMUM, XQSPIPS_CR_PRESC_SHIFT, XQspiPs_ReadReg, XQspiPs_WriteReg.
Referenced by DualStackExample, LinearQspiFlashExample, QspiFlashIntrExample, QspiFlashPolledExample, QspiG128FlashExample.
u8 XQspiPs_GetClkPrescaler(XQspiPs *InstancePtr)
This function gets the clock prescaler of an QSPI device.
InstancePtr is a pointer to the XQspiPs instance. The prescaler value. None.
References XQspiPs_Config::BaseAddress, XQspiPs::Config, XQspiPs::IsReady, XQSPIPS_CR_OFFSET, XQSPIPS_CR_PRESC_MASK, XQSPIPS_CR_PRESC_SHIFT, XQspiPs_ReadReg.
int XQspiPs_SetDelays(XQspiPs *InstancePtr, u8 DelayNss, u8 DelayBtwn, u8 DelayAfter, u8 DelayInit)
This function sets the delay register for the QSPI device driver.
The delay register controls the Delay Between Transfers, Delay After Transfers, and the Delay Initially. The default value is 0x0. The range of each delay value is 0-255. InstancePtr is a pointer to the XQspiPs instance. DelayNss is the delay to de-assert slave select between two word transfers. DelayBtwn is the delay between one Slave Select being de-activated and the activation of another slave. The delay is the number of master clock periods given by DelayBtwn + 2. DelayAfter define the delay between the last bit of the current byte transfer and the first bit of the next byte transfer. The delay in number of master clock periods is given as: CHPA=0:DelayInit+DelayAfter+3 CHPA=1:DelayAfter+1 DelayInit is the delay between asserting the slave select signal and the first bit transfer. The delay int number of master clock periods is DelayInit+1. XST_SUCCESS if delays are successfully set.XST_DEVICE_BUSY if the device is currently transferring data. The transfer must complete or be aborted before setting options. None.
References XQspiPs_Config::BaseAddress, XQspiPs::Config, XQspiPs::IsBusy, XQspiPs::IsReady, XQSPIPS_DR_AFTER_SHIFT, XQSPIPS_DR_BTWN_SHIFT, XQSPIPS_DR_NSS_SHIFT, XQSPIPS_DR_OFFSET, XQspiPs_WriteReg.
Referenced by XQspiPs_SelfTest.
void XQspiPs_GetDelays(XQspiPs *InstancePtr, u8 *DelayNss, u8 *DelayBtwn, u8 *DelayAfter, u8 *DelayInit)
This function gets the delay settings for an QSPI device.
The delay register controls the Delay Between Transfers, Delay After Transfers, and the Delay Initially. The default value is 0x0. InstancePtr is a pointer to the XQspiPs instance. DelayNss is a pointer to the Delay to de-assert slave select between two word transfers. DelayBtwn is a pointer to the Delay Between transfers value. This is a return parameter. DelayAfter is a pointer to the Delay After transfer value. This is a return parameter. DelayInit is a pointer to the Delay Initially value. This is a return parameter. None. None.
References XQspiPs_Config::BaseAddress, XQspiPs::Config, XQspiPs::IsReady, XQSPIPS_DR_AFTER_MASK, XQSPIPS_DR_AFTER_SHIFT, XQSPIPS_DR_BTWN_MASK, XQSPIPS_DR_BTWN_SHIFT, XQSPIPS_DR_INIT_MASK, XQSPIPS_DR_NSS_MASK, XQSPIPS_DR_NSS_SHIFT, XQSPIPS_DR_OFFSET, XQspiPs_ReadReg.
Referenced by XQspiPs_SelfTest.
void XQspiPs_ResetHw(u32 BaseAddress)
Resets QSPI by disabling the device and bringing it to reset state through register writes.
BaseAddress None. None.
References XQSPIPS_CR_OFFSET, XQSPIPS_CR_SSCTRL_MASK, XQSPIPS_CR_SSFORCE_MASK, XQSPIPS_ER_OFFSET, XQSPIPS_IDR_OFFSET, XQSPIPS_IXR_DISABLE_ALL, XQSPIPS_IXR_RXNEMPTY_MASK, XQSPIPS_IXR_WR_TO_CLR_MASK, XQSPIPS_LQSPI_CR_OFFSET, XQspiPs_ReadReg, XQSPIPS_RXD_OFFSET, XQSPIPS_RXWR_MASK, XQSPIPS_RXWR_OFFSET, XQSPIPS_RXWR_RESET_VALUE, XQSPIPS_SR_OFFSET, XQSPIPS_TXWR_MASK, XQSPIPS_TXWR_OFFSET, XQSPIPS_TXWR_RESET_VALUE, XQspiPs_WriteReg.
void XQspiPs_LinearInit(u32 BaseAddress)
Initializes QSPI to Linear mode with default QSPI boot settings.
BaseAddress None. None.
References XQSPIPS_CR_OFFSET, XQSPIPS_CR_PRESC_MASK, XQSPIPS_CR_PRESC_SHIFT, XQSPIPS_CR_SSCTRL_MASK, XQSPIPS_ER_ENABLE_MASK, XQSPIPS_ER_OFFSET, XQSPIPS_LQSPI_CR_OFFSET, XQSPIPS_LQSPI_CR_RST_STATE, XQSPIPS_LQSPI_CR_SEP_BUS_MASK, XQSPIPS_LQSPI_CR_TWO_MEM_MASK, XQspiPs_ReadReg, XQspiPs_WriteReg.
ARRAY_SIZE
XQSPIPS_H
XQspiPs_IsManualStart
XQspiPs_IsManualChipSelect
XQspiPs_SetSlaveIdle
Set the contents of the slave idle count register.
InstancePtr is a pointer to the XQspiPs instance. RegisterValue is the value to be written, valid values are 0-255. None C-Style signature: void XQspiPs_SetSlaveIdle(XQspiPs *InstancePtr, u32 RegisterValue)
XQspiPs_GetSlaveIdle
Get the contents of the slave idle count register.
Use the XQSPIPS_SICR_* constants defined in xqspips_hw.h to interpret the bit-mask returned. InstancePtr is a pointer to the XQspiPs instance. An 8-bit value representing Slave Idle Count. C-Style signature: u32 XQspiPs_GetSlaveIdle(XQspiPs *InstancePtr)
XQspiPs_SetTXWatermark
Set the contents of the transmit FIFO watermark register.
InstancePtr is a pointer to the XQspiPs instance. RegisterValue is the value to be written, valid values are 1-63. None. C-Style signature: void XQspiPs_SetTXWatermark(XQspiPs *InstancePtr, u32 RegisterValue)
XQspiPs_GetTXWatermark
Get the contents of the transmit FIFO watermark register.
Valid values are in the range 1-63. InstancePtr is a pointer to the XQspiPs instance. A 6-bit value representing Tx Watermark level. C-Style signature: u32 XQspiPs_GetTXWatermark(XQspiPs *InstancePtr)
XQspiPs_SetRXWatermark
Set the contents of the receive FIFO watermark register.
InstancePtr is a pointer to the XQspiPs instance. RegisterValue is the value to be written, valid values are 1-63. None. C-Style signature: void XQspiPs_SetRXWatermark(XQspiPs *InstancePtr, u32 RegisterValue)
XQspiPs_GetRXWatermark
Get the contents of the receive FIFO watermark register.
Valid values are in the range 1-63. InstancePtr is a pointer to the XQspiPs instance. A 6-bit value representing Rx Watermark level. C-Style signature: u32 XQspiPs_GetRXWatermark(XQspiPs *InstancePtr)
XQspiPs_Enable
Enable the device and uninhibit master transactions.
InstancePtr is a pointer to the XQspiPs instance. None. C-Style signature: void XQspiPs_Enable(XQspiPs *InstancePtr)
Referenced by XQspiPs_LqspiRead, XQspiPs_PolledTransfer, XQspiPs_Transfer.
XQspiPs_Disable
Disable the device.
InstancePtr is a pointer to the XQspiPs instance. None. C-Style signature: void XQspiPs_Disable(XQspiPs *InstancePtr)
Referenced by XQspiPs_Abort, XQspiPs_InterruptHandler, XQspiPs_LqspiRead, XQspiPs_PolledTransfer.
XQspiPs_SetLqspiConfigReg
Set the contents of the Linear QSPI Configuration register.
InstancePtr is a pointer to the XQspiPs instance. RegisterValue is the value to be written to the Linear QSPI configuration register. None. C-Style signature: void XQspiPs_SetLqspiConfigReg(XQspiPs *InstancePtr, u32 RegisterValue)
Referenced by DualStackExample, FlashErase, GetRealAddr, LinearQspiFlashExample, QspiG128FlashExample.
XQspiPs_GetLqspiConfigReg
Get the contents of the Linear QSPI Configuration register.
InstancePtr is a pointer to the XQspiPs instance. A 32-bit value representing the contents of the LQSPI Config register. C-Style signature: u32 XQspiPs_GetLqspiConfigReg(u32 *InstancePtr)
Referenced by FlashErase, GetRealAddr, XQspiPs_LqspiRead.
XQSPIPS_HW_H
XQspiPs_In32
XQspiPs_Out32
XQSPIPS_DUMMY_TX_DATA
XQspiPs_ReadReg
Read a register.
BaseAddress contains the base address of the device. RegOffset contains the offset from the 1st register of the device to the target register. The value read from the register. C-Style signature: u32 XQspiPs_ReadReg(u32 BaseAddress. int RegOffset)
Referenced by XQspiPs_Abort, XQspiPs_GetClkPrescaler, XQspiPs_GetDelays, XQspiPs_GetOptions, XQspiPs_InterruptHandler, XQspiPs_LinearInit, XQspiPs_PolledTransfer, XQspiPs_Reset, XQspiPs_ResetHw, XQspiPs_SetClkPrescaler, XQspiPs_SetOptions, XQspiPs_SetSlaveSelect, XQspiPs_Transfer.
XQspiPs_WriteReg
Write to a register.
BaseAddress contains the base address of the device. RegOffset contains the offset from the 1st register of the device to target register. RegisterValue is the value to be written to the register. None. C-Style signature: void XQspiPs_WriteReg(u32 BaseAddress, int RegOffset, u32 RegisterValue)
Referenced by XQspiPs_Abort, XQspiPs_InterruptHandler, XQspiPs_LinearInit, XQspiPs_PolledTransfer, XQspiPs_Reset, XQspiPs_ResetHw, XQspiPs_SetClkPrescaler, XQspiPs_SetDelays, XQspiPs_SetOptions, XQspiPs_SetSlaveSelect, XQspiPs_Transfer.
XQSPIPS_NUM_OPTIONS