xqspips_g128_flash_example.c
WRITE_STATUS_CMD
WRITE_CMD
READ_CMD
WRITE_DISABLE_CMD
READ_STATUS_CMD
WRITE_ENABLE_CMD
FAST_READ_CMD
DUAL_READ_CMD
QUAD_READ_CMD
BULK_ERASE_CMD
SEC_ERASE_CMD
READ_ID
READ_CONFIG_CMD
WRITE_CONFIG_CMD
BANK_REG_RD
BANK_REG_WR
EXTADD_REG_RD
EXTADD_REG_WR
DIE_ERASE_CMD
READ_FLAG_STATUS_CMD
COMMAND_OFFSET
ADDRESS_1_OFFSET
ADDRESS_2_OFFSET
ADDRESS_3_OFFSET
DATA_OFFSET
DUMMY_OFFSET
DUMMY_SIZE
RD_ID_SIZE
BULK_ERASE_SIZE
SEC_ERASE_SIZE
BANK_SEL_SIZE
RD_CFG_SIZE
WR_CFG_SIZE
DIE_ERASE_SIZE
OVERHEAD_SIZE
FLASH1BASE
SIXTEENMB
FLASH_QUAD_EN_MASK
FLASH_SRWD_MASK
BANKMASK
MICRON_ID_BYTE0
MICRON_ID_BYTE2_128
MICRON_ID_BYTE2_256
MICRON_ID_BYTE2_512
MICRON_ID_BYTE2_1G
SPANSION_ID_BYTE0
SPANSION_ID_BYTE2_128
SPANSION_ID_BYTE2_256
SPANSION_ID_BYTE2_512
WINBOND_ID_BYTE0
WINBOND_ID_BYTE2_128
MACRONIX_ID_BYTE0
MACRONIX_ID_BYTE2_256
MACRONIX_ID_BYTE2_512
MACRONIX_ID_BYTE2_1G
ISSI_ID_BYTE0
ISSI_ID_BYTE2_256
SPANSION_INDEX_START
FLASH_CFG_TBL_SINGLE_128_SP
FLASH_CFG_TBL_STACKED_128_SP
FLASH_CFG_TBL_PARALLEL_128_SP
FLASH_CFG_TBL_SINGLE_256_SP
FLASH_CFG_TBL_STACKED_256_SP
FLASH_CFG_TBL_PARALLEL_256_SP
FLASH_CFG_TBL_SINGLE_512_SP
FLASH_CFG_TBL_STACKED_512_SP
FLASH_CFG_TBL_PARALLEL_512_SP
MICRON_INDEX_START
FLASH_CFG_TBL_SINGLE_128_MC
FLASH_CFG_TBL_STACKED_128_MC
FLASH_CFG_TBL_PARALLEL_128_MC
FLASH_CFG_TBL_SINGLE_256_MC
FLASH_CFG_TBL_STACKED_256_MC
FLASH_CFG_TBL_PARALLEL_256_MC
FLASH_CFG_TBL_SINGLE_512_MC
FLASH_CFG_TBL_STACKED_512_MC
FLASH_CFG_TBL_PARALLEL_512_MC
FLASH_CFG_TBL_SINGLE_1GB_MC
FLASH_CFG_TBL_STACKED_1GB_MC
FLASH_CFG_TBL_PARALLEL_1GB_MC
WINBOND_INDEX_START
FLASH_CFG_TBL_SINGLE_128_WB
FLASH_CFG_TBL_STACKED_128_WB
FLASH_CFG_TBL_PARALLEL_128_WB
MACRONIX_INDEX_START
FLASH_CFG_TBL_SINGLE_256_MX
FLASH_CFG_TBL_STACKED_256_MX
FLASH_CFG_TBL_PARALLEL_256_MX
FLASH_CFG_TBL_SINGLE_512_MX
FLASH_CFG_TBL_STACKED_512_MX
FLASH_CFG_TBL_PARALLEL_512_MX
FLASH_CFG_TBL_SINGLE_1G_MX
FLASH_CFG_TBL_STACKED_1G_MX
FLASH_CFG_TBL_PARALLEL_1G_MX
ISSI_INDEX_START
FLASH_CFG_TBL_SINGLE_256_ISSI
FLASH_CFG_TBL_STACKED_256_ISSI
FLASH_CFG_TBL_PARALLEL_256_ISSI
LQSPI_CR_FAST_QUAD_READ
LQSPI_CR_1_DUMMY_BYTE
DUAL_STACK_CONFIG_WRITE
DUAL_QSPI_CONFIG_WRITE
PAGE_COUNT
MAX_PAGE_SIZE
TEST_ADDRESS
UNIQUE_VALUE
FlashInfo Flash_Config_Table[34][34]
Flash Config Table.
Referenced by DieErase, FlashErase, FlashRead, FlashWrite, GetRealAddr, QspiG128FlashExample.
u32 FlashMake
u32 FCTIndex
XQspiPs QspiInstance
int Test
u8 ReadBuffer[(PAGE_COUNT *MAX_PAGE_SIZE)+(DATA_OFFSET+DUMMY_SIZE)*8][(PAGE_COUNT *MAX_PAGE_SIZE)+(DATA_OFFSET+DUMMY_SIZE)*8]
u8 WriteBuffer[(PAGE_COUNT *MAX_PAGE_SIZE)+DATA_OFFSET][(PAGE_COUNT *MAX_PAGE_SIZE)+DATA_OFFSET]
u32 MaxData
int QspiG128FlashExample(XQspiPs *QspiInstancePtr, UINTPTR BaseAddress)
The purpose of this function is to illustrate how to use the XQspiPs device driver in single, parallel and stacked modes using flash devices greater than 128Mb.
This function reads and writes data in I/O mode. QspiInstancePtr is a pointer to the QSPIPS driver to use. BaseAddress contains the base address of the device XST_SUCCESS if successful, else XST_FAILURE. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XQspiPs_Config::BaseAddress, XQspiPs_Config::ConnectionMode, Flash_Config_Table, FlashErase, FlashRead, FlashReadID, FlashWrite, XQspiPs_CfgInitialize, XQSPIPS_CLK_PRESCALE_8, XQSPIPS_FORCE_SSELECT_OPTION, XQSPIPS_HOLD_B_DRIVE_OPTION, XQspiPs_LookupConfig, XQSPIPS_MANUAL_START_OPTION, XQspiPs_SelfTest, XQspiPs_SetClkPrescaler, XQspiPs_SetLqspiConfigReg, XQspiPs_SetOptions, XQspiPs_SetSlaveSelect.
Referenced by main.
void FlashErase(XQspiPs *QspiPtr, u32 Address, u32 ByteCount, u8 *WriteBfrPtr)
This function erases the sectors in the serial Flash connected to the QSPI interface.
QspiPtr is a pointer to the QSPI driver component to use. Address contains the address of the first sector which needs to be erased. ByteCount contains the total size to be erased. WriteBfrPtr is Pointer to the write buffer (which is to be transmitted) None. None.
References BulkErase, XQspiPs::Config, XQspiPs_Config::ConnectionMode, DieErase, Flash_Config_Table, GetRealAddr, SendBankSelect, XQspiPs_GetLqspiConfigReg, XQSPIPS_LQSPI_CR_U_PAGE_MASK, XQspiPs_PolledTransfer, XQspiPs_SetLqspiConfigReg, XQspiPs_SetSlaveSelect.
void FlashWrite(XQspiPs *QspiPtr, u32 Address, u32 ByteCount, u8 Command, u8 *WriteBfrPtr)
This function writes to the serial Flash connected to the QSPI interface.
All the data put into the buffer must be in the same page of the device with page boundaries being on 256 byte boundaries. QspiPtr is a pointer to the QSPI driver component to use. Address contains the address to write data to in the Flash. ByteCount contains the number of bytes to write. Command is the command used to write data to the flash. QSPI device supports only Page Program command to write data to the flash. WriteBfrptr is the pointer to the write buffer(which is to be transmitted) None. None.
References Flash_Config_Table, GetRealAddr, SendBankSelect, XQspiPs_PolledTransfer.
int FlashReadID(XQspiPs *QspiPtr, u8 *WriteBfrPtr, u8 *ReadBfrPtr)
This function reads serial Flash ID connected to the SPI interface.
It then deduces the make and size of the flash and obtains the connection mode to point to corresponding parameters in the flash configuration table. The flash driver will function based on this and it presently supports Micron and Spansion - 128, 256 and 512Mbit and Winbond 128Mbit QspiPtr is a pointer to the QSPI driver component to use. WriteBfrPtr is pointer to the write buffer (which is to be transmitted) ReadBfrPtr is pointer to the read buffer to which valid received data should be written. XST_SUCCESS if read id, otherwise XST_FAILURE. None.
References XQspiPs::Config, XQspiPs_Config::ConnectionMode, XQspiPs_PolledTransfer.
void FlashRead(XQspiPs *QspiPtr, u32 Address, u32 ByteCount, u8 Command, u8 *WriteBfrPtr, u8 *ReadBfrPtr)
This function performs an I/O read.
QspiPtr is a pointer to the QSPI driver component to use. Address contains the address of the first sector which needs to be erased. ByteCount contains the total size to be erased. Command is the command used to read data from the flash. Supports normal, fast, dual and quad read commands. WriteBfrPtr is pointer to the write buffer which contains data to be transmitted ReadBfrPtr is pointer to the read buffer to which valid received data should be written none. None.
References Flash_Config_Table, GetRealAddr, SendBankSelect, XQspiPs_PolledTransfer.
int SendBankSelect(XQspiPs *QspiPtr, u8 *WriteBfrPtr, u32 BankSel)
This functions selects the current bank.
QspiPtr is a pointer to the QSPI driver component to use. WriteBfrPtr to the write buffer which contains data to be transmitted. BankSel is the bank to be selected in the flash device(s). XST_SUCCESS if bank selected, otherwise XST_FAILURE. None.
References XQspiPs_PolledTransfer.
Referenced by DieErase, FlashErase, FlashRead, FlashWrite.
void BulkErase(XQspiPs *QspiPtr, u8 *WriteBfrPtr)
This functions performs a bulk erase operation when the flash device has a single die.
Works for both Spansion and Micron QspiPtr is a pointer to the QSPI driver component to use. WriteBfrPtr is the pointer to command+address to be sent None None.
References XQspiPs_PolledTransfer.
Referenced by FlashErase.
void DieErase(XQspiPs *QspiPtr, u8 *WriteBfrPtr)
This functions performs a die erase operation on all the die in the flash device.
This function uses the die erase command for Micron 512Mbit and 1Gbit QspiPtr is a pointer to the QSPI driver component to use. WriteBfrPtr is the pointer to command+address to be sent None None.
References Flash_Config_Table, SendBankSelect, XQspiPs_PolledTransfer.
Referenced by FlashErase.
u32 GetRealAddr(XQspiPs *QspiPtr, u32 Address)
This functions translates the address based on the type of interconnection.
In case of stacked, this function asserts the corresponding slave select. QspiPtr is a pointer to the QSPI driver component to use. Address which is to be accessed (for erase, write or read) RealAddr is the translated address - for single it is unchanged; for stacked, the lower flash size is subtracted; for parallel the address is divided by 2. None.
References XQspiPs::Config, XQspiPs_Config::ConnectionMode, Flash_Config_Table, XQspiPs_GetLqspiConfigReg, XQSPIPS_LQSPI_CR_U_PAGE_MASK, XQspiPs_SetLqspiConfigReg, XQspiPs_SetSlaveSelect.
Referenced by FlashErase, FlashRead, FlashWrite.
int main(void)
Main function to call the QSPI Flash example.
XST_SUCCESS if successful, otherwise XST_FAILURE. None
References QspiG128FlashExample.