xqspips.c
ARRAY_SIZE
XPAR_PS7_QSPI_LINEAR_0_S_AXI_BASEADDR
XQspiPsInstFormat FlashInst[][]
static void XQspiPs_GetReadData(XQspiPs *InstancePtr, u32 Data, u8 Size)
Copies data from Data to the Receive buffer.
InstancePtr is a pointer to the XQspiPs instance. Data is the data which needs to be copied to the Rx buffer. Size is the number of bytes to be copied to the Receive buffer. None. None.
static void StubStatusHandler(void *CallBackRef, u32 StatusEvent, unsigned ByteCount)
This is a stub for the status callback.
The stub is here in case the upper layers forget to set the handler. CallBackRef is a pointer to the upper layer callback reference StatusEvent is the event that just occurred. ByteCount is the number of bytes transferred up until the event occurred. None. None.
int XQspiPs_CfgInitialize(XQspiPs *InstancePtr, XQspiPs_Config *ConfigPtr, u32 EffectiveAddr)
Initializes a specific XQspiPs instance such that the driver is ready to use.
The state of the device after initialization is: Master modeActive high clock polarityClock phase 0Baud rate divisor 2Transfer width 32Master reference clock = pclkNo chip select activeManual CS and Manual Start disabled InstancePtr is a pointer to the XQspiPs instance. ConfigPtr is a reference to a structure containing information about a specific QSPI device. This function initializes an InstancePtr object for a specific device specified by the contents of Config. EffectiveAddr is the device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, use ConfigPtr->Config.BaseAddress for this device. XST_SUCCESS if successful.XST_DEVICE_IS_STARTED if the device is already started. It must be stopped to re-initialize. None.
References XQspiPs_Config::BaseAddress, XQspiPs::Config, XQspiPs_Config::ConnectionMode, XQspiPs::IsBusy, XQspiPs::IsReady, XQspiPs::RecvBufferPtr, XQspiPs::RemainingBytes, XQspiPs::RequestedBytes, XQspiPs::SendBufferPtr, XQspiPs_Reset.
Referenced by DualStackExample, LinearQspiFlashExample, QspiFlashIntrExample, QspiFlashPolledExample, QspiG128FlashExample, QspiPsSelfTestExample.
void XQspiPs_Reset(XQspiPs *InstancePtr)
Resets the QSPI device.
Reset must only be called after the driver has been initialized. Any data transfer that is in progress is aborted.The upper layer software is responsible for re-configuring (if necessary) and restarting the QSPI device after the reset. InstancePtr is a pointer to the XQspiPs instance. None. None.
References XQspiPs_Config::BaseAddress, XQspiPs::Config, XQspiPs::IsReady, XQspiPs_Abort, XQSPIPS_CR_OFFSET, XQspiPs_ReadReg, XQspiPs_WriteReg.
Referenced by XQspiPs_CfgInitialize, XQspiPs_SelfTest.
void XQspiPs_Abort(XQspiPs *InstancePtr)
Aborts a transfer in progress by disabling the device and flush the RxFIFO.
The byte counts are cleared, the busy flag is cleared. InstancePtr is a pointer to the XQspiPs instance. None. This function does a read/modify/write of the config register. The user of this function needs to take care of critical sections.
References XQspiPs_Config::BaseAddress, XQspiPs::Config, XQspiPs::IsBusy, LQSPI_RST_CTRL, LQSPI_RST_CTRL_MASK, XQspiPs::RemainingBytes, XQspiPs::RequestedBytes, SLCR_LOCK, SLCR_LOCK_MASK, SLCR_LOCKSTA, SLCR_UNLOCK, SLCR_UNLOCK_MASK, XQSPIPS_CR_OFFSET, XQSPIPS_CR_SSCTRL_MASK, XQSPIPS_CR_SSFORCE_MASK, XQspiPs_Disable, XQspiPs_ReadReg, XQSPIPS_RXWR_OFFSET, XQSPIPS_RXWR_RESET_VALUE, XQSPIPS_TXWR_OFFSET, XQSPIPS_TXWR_RESET_VALUE, XQspiPs_WriteReg.
Referenced by XQspiPs_Reset.
s32 XQspiPs_Transfer(XQspiPs *InstancePtr, u8 *SendBufPtr, u8 *RecvBufPtr, u32 ByteCount)
Transfers specified data on the QSPI bus.
Initiates bus communication and sends/receives data to/from the selected QSPI slave. For every byte sent, a byte is received.The caller has the option of providing two different buffers for send and receive, or one buffer for both send and receive, or no buffer for receive. The receive buffer must be at least as big as the send buffer to prevent unwanted memory writes. This implies that the byte count passed in as an argument must be the smaller of the two buffers if they differ in size. Here are some sample usages: XQspiPs_Transfer(InstancePtr, SendBuf, RecvBuf, ByteCount) The caller wishes to send and receive, and provides two different buffers for send and receive. XQspiPs_Transfer(InstancePtr, SendBuf, NULL, ByteCount) The caller wishes only to send and does not care about the received data. The driver ignores the received data in this case. XQspiPs_Transfer(InstancePtr, SendBuf, SendBuf, ByteCount) The caller wishes to send and receive, but provides the same buffer for doing both. The driver sends the data and overwrites the send buffer with received data as it transfers the data. XQspiPs_Transfer(InstancePtr, RecvBuf, RecvBuf, ByteCount) The caller wishes to only receive and does not care about sending data. In this case, the caller must still provide a send buffer, but it can be the same as the receive buffer if the caller does not care what it sends. The device must send N bytes of data if it wishes to receive N bytes of data. Although this function takes entire buffers as arguments, the driver can only transfer a limited number of bytes at a time, limited by the size of the FIFO. A call to this function only starts the transfer, then subsequent transfers of the data is performed by the interrupt service routine until the entire buffer has been transferred. The status callback function is called when the entire buffer has been sent/received.This function is non-blocking. The SetSlaveSelect function must be called prior to this function. InstancePtr is a pointer to the XQspiPs instance. SendBufPtr is a pointer to a data buffer that needs to be transmitted. This buffer must not be NULL. RecvBufPtr is a pointer to a buffer for received data. This argument can be NULL if do not care about receiving. ByteCount contains the number of bytes to send/receive. The number of bytes received always equals the number of bytes sent. XST_SUCCESS if the buffers are successfully handed off to the device for transfer.XST_DEVICE_BUSY indicates that a data transfer is already in progress. This is determined by the driver. This function is not thread-safe. The higher layer software must ensure that no two threads are transferring data on the QSPI bus at the same time.
References XQspiPs_Config::BaseAddress, XQspiPs::Config, XQspiPs::IsBusy, XQspiPs::IsReady, XQspiPs::RecvBufferPtr, XQspiPs::RemainingBytes, XQspiPs::RequestedBytes, XQspiPs::SendBufferPtr, XQspiPs::ShiftReadData, XQSPIPS_CR_MANSTRT_MASK, XQSPIPS_CR_OFFSET, XQSPIPS_CR_SSCTRL_MASK, XQspiPs_Enable, XQSPIPS_FIFO_DEPTH, XQSPIPS_IER_OFFSET, XQSPIPS_IXR_RXNEMPTY_MASK, XQSPIPS_IXR_RXOVR_MASK, XQSPIPS_IXR_TXOW_MASK, XQSPIPS_IXR_TXUF_MASK, XQSPIPS_IXR_WR_TO_CLR_MASK, XQspiPs_ReadReg, XQSPIPS_RXWR_OFFSET, XQSPIPS_SR_OFFSET, XQSPIPS_TXD_00_OFFSET, XQSPIPS_TXD_01_OFFSET, XQSPIPS_TXD_10_OFFSET, XQSPIPS_TXD_11_OFFSET, XQspiPs_WriteReg.
Referenced by FlashRead.
s32 XQspiPs_PolledTransfer(XQspiPs *InstancePtr, u8 *SendBufPtr, u8 *RecvBufPtr, u32 ByteCount)
Transfers specified data on the QSPI bus in polled mode.
The caller has the option of providing two different buffers for send and receive, or one buffer for both send and receive, or no buffer for receive. The receive buffer must be at least as big as the send buffer to prevent unwanted memory writes. This implies that the byte count passed in as an argument must be the smaller of the two buffers if they differ in size. Here are some sample usages: XQspiPs_PolledTransfer(InstancePtr, SendBuf, RecvBuf, ByteCount) The caller wishes to send and receive, and provides two different buffers for send and receive. XQspiPs_PolledTransfer(InstancePtr, SendBuf, NULL, ByteCount) The caller wishes only to send and does not care about the received data. The driver ignores the received data in this case. XQspiPs_PolledTransfer(InstancePtr, SendBuf, SendBuf, ByteCount) The caller wishes to send and receive, but provides the same buffer for doing both. The driver sends the data and overwrites the send buffer with received data as it transfers the data. XQspiPs_PolledTransfer(InstancePtr, RecvBuf, RecvBuf, ByteCount) The caller wishes to only receive and does not care about sending data. In this case, the caller must still provide a send buffer, but it can be the same as the receive buffer if the caller does not care what it sends. The device must send N bytes of data if it wishes to receive N bytes of data. InstancePtr is a pointer to the XQspiPs instance. SendBufPtr is a pointer to a data buffer that needs to be transmitted. This buffer must not be NULL. RecvBufPtr is a pointer to a buffer for received data. This argument can be NULL if do not care about receiving. ByteCount contains the number of bytes to send/receive. The number of bytes received always equals the number of bytes sent. XST_SUCCESS if the buffers are successfully handed off to the device for transfer.XST_DEVICE_BUSY indicates that a data transfer is already in progress. This is determined by the driver. This function is not thread-safe. The higher layer software must ensure that no two threads are transferring data on the QSPI bus at the same time.
References XQspiPs_Config::BaseAddress, XQspiPs::Config, XQspiPs::IsBusy, XQspiPs::IsReady, XQspiPs::RecvBufferPtr, XQspiPs::RemainingBytes, XQspiPs::RequestedBytes, XQspiPs::SendBufferPtr, XQspiPs::ShiftReadData, XQSPIPS_CR_MANSTRT_MASK, XQSPIPS_CR_OFFSET, XQSPIPS_CR_SSCTRL_MASK, XQspiPs_Disable, XQspiPs_Enable, XQSPIPS_FIFO_DEPTH, XQSPIPS_IXR_RXNEMPTY_MASK, XQSPIPS_IXR_TXOW_MASK, XQspiPs_ReadReg, XQSPIPS_RXD_OFFSET, XQSPIPS_RXWR_OFFSET, XQSPIPS_RXWR_RESET_VALUE, XQSPIPS_SR_OFFSET, XQSPIPS_TXD_00_OFFSET, XQSPIPS_TXD_01_OFFSET, XQSPIPS_TXD_10_OFFSET, XQSPIPS_TXD_11_OFFSET, XQspiPs_WriteReg.
Referenced by BulkErase, DieErase, FlashErase, FlashQuadEnable, FlashRead, FlashReadID, FlashWrite, SendBankSelect.
int XQspiPs_LqspiRead(XQspiPs *InstancePtr, u8 *RecvBufPtr, u32 Address, unsigned ByteCount)
Read the flash in Linear QSPI mode.
InstancePtr is a pointer to the XQspiPs instance. RecvBufPtr is a pointer to a buffer for received data. Address is the starting address within the flash from from where data needs to be read. ByteCount contains the number of bytes to receive. XST_SUCCESS if read is performedXST_FAILURE if Linear mode is not set None.
References XQspiPs::IsReady, XQspiPs_Disable, XQspiPs_Enable, XQspiPs_GetLqspiConfigReg, XQSPIPS_LQSPI_CR_LINEAR_MASK.
Referenced by DualStackExample, LinearQspiFlashExample.
int XQspiPs_SetSlaveSelect(XQspiPs *InstancePtr)
Selects the slave with which the master communicates.
The user is not allowed to select the slave while a transfer is in progress. InstancePtr is a pointer to the XQspiPs instance. XST_SUCCESS if the slave is selected or deselected successfully.XST_DEVICE_BUSY if a transfer is in progress, slave cannot be changed. This function only sets the slave which will be selected when a transfer occurs. The slave is not selected when the QSPI is idle.
References XQspiPs_Config::BaseAddress, XQspiPs::Config, XQspiPs::IsBusy, XQspiPs::IsReady, XQSPIPS_CR_OFFSET, XQSPIPS_CR_SSCTRL_MASK, XQspiPs_ReadReg, XQspiPs_WriteReg.
Referenced by DualStackExample, FlashErase, GetRealAddr, LinearQspiFlashExample, QspiFlashIntrExample, QspiFlashPolledExample, QspiG128FlashExample, XQspiPs_SetOptions.
void XQspiPs_SetStatusHandler(XQspiPs *InstancePtr, void *CallBackRef, XQspiPs_StatusHandler FuncPtr)
Sets the status callback function, the status handler, which the driver calls when it encounters conditions that should be reported to upper layer software.
The handler executes in an interrupt context, so it must minimize the amount of processing performed. One of the following status events is passed to the status handler.XST_SPI_TRANSFER_DONE The requested data transfer is doneXST_SPI_TRANSMIT_UNDERRUN As a slave device, the master clocked data but there were none available in the transmit register/FIFO. This typically means the slave application did not issue a transfer request fast enough, or the processor/driver could not fill the transmit register/FIFO fast enough.XST_SPI_RECEIVE_OVERRUN The QSPI device lost data. Data was received but the receive data register/FIFO was full. InstancePtr is a pointer to the XQspiPs instance. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. FuncPtr is the pointer to the callback function. None. The handler is called within interrupt context, so it should do its work quickly and queue potentially time-consuming work to a task-level thread.
References XQspiPs::IsReady, XQspiPs::StatusRef.
Referenced by QspiFlashIntrExample.
void XQspiPs_InterruptHandler(void *InstancePtr)
The interrupt handler for QSPI interrupts.
This function must be connected by the user to an interrupt controller.The interrupts that are handled are: Data Transmit Register (FIFO) Empty. This interrupt is generated when the transmit register or FIFO is empty. The driver uses this interrupt during a transmission to continually send/receive data until the transfer is done.Data Transmit Register (FIFO) Underflow. This interrupt is generated when the QSPI device, when configured as a slave, attempts to read an empty DTR/FIFO. An empty DTR/FIFO usually means that software is not giving the device data in a timely manner. No action is taken by the driver other than to inform the upper layer software of the error.Data Receive Register (FIFO) Overflow. This interrupt is generated when the QSPI device attempts to write a received byte to an already full DRR/FIFO. A full DRR/FIFO usually means software is not emptying the data in a timely manner. No action is taken by the driver other than to inform the upper layer software of the error. InstancePtr is a pointer to the XQspiPs instance. None. The slave select register is being set to deselect the slave when a transfer is complete.
References XQspiPs_Config::BaseAddress, XQspiPs::Config, XQspiPs::IsBusy, XQspiPs::IsReady, XQspiPs::RecvBufferPtr, XQspiPs::RemainingBytes, XQspiPs::RequestedBytes, XQspiPs::SendBufferPtr, XQspiPs::StatusRef, XQSPIPS_CR_MANSTRT_MASK, XQSPIPS_CR_OFFSET, XQSPIPS_CR_SSCTRL_MASK, XQspiPs_Disable, XQSPIPS_IDR_OFFSET, XQSPIPS_IER_OFFSET, XQSPIPS_IXR_RXNEMPTY_MASK, XQSPIPS_IXR_RXOVR_MASK, XQSPIPS_IXR_TXOW_MASK, XQSPIPS_IXR_TXUF_MASK, XQSPIPS_IXR_WR_TO_CLR_MASK, XQspiPs_ReadReg, XQSPIPS_RXD_OFFSET, XQSPIPS_RXWR_OFFSET, XQSPIPS_RXWR_RESET_VALUE, XQSPIPS_SR_OFFSET, XQSPIPS_TXD_00_OFFSET, XQspiPs_WriteReg.
Referenced by QspiFlashIntrExample.