xqspips_sinit.c
XQspiPs_Config XQspiPs_ConfigTable[][]
This table contains configuration information for each QSPI device in the system.
XQspiPs_Config * XQspiPs_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XQspiPs_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xqspips.h for the definition of XQspiPs_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XQspiPs_Config::Name.
Referenced by DualStackExample, LinearQspiFlashExample, QspiFlashIntrExample, QspiFlashPolledExample, QspiG128FlashExample, QspiPsSelfTestExample.