xqspips_selftest.c
int XQspiPs_SelfTest(XQspiPs *InstancePtr)
Runs a self-test on the driver/device.
The self-test is destructive in that a reset of the device is performed in order to check the reset values of the registers and to get the device into a known state.Upon successful return from the self-test, the device is reset. InstancePtr is a pointer to the XQspiPs instance. XST_SUCCESS if successful XST_REGISTER_ERROR indicates a register did not read or write correctly. None.
References XQspiPs::IsReady, XQspiPs_GetDelays, XQspiPs_Reset, XQspiPs_SetDelays.
Referenced by DualStackExample, LinearQspiFlashExample, QspiFlashIntrExample, QspiFlashPolledExample, QspiG128FlashExample, QspiPsSelfTestExample.