xqspips_flash_polled_example.c
WRITE_STATUS_CMD
WRITE_CMD
READ_CMD
WRITE_DISABLE_CMD
READ_STATUS_CMD
WRITE_ENABLE_CMD
FAST_READ_CMD
DUAL_READ_CMD
QUAD_READ_CMD
BULK_ERASE_CMD
SEC_ERASE_CMD
READ_ID
COMMAND_OFFSET
ADDRESS_1_OFFSET
ADDRESS_2_OFFSET
ADDRESS_3_OFFSET
DATA_OFFSET
DUMMY_OFFSET
DUMMY_SIZE
RD_ID_SIZE
BULK_ERASE_SIZE
SEC_ERASE_SIZE
OVERHEAD_SIZE
SECTOR_SIZE
NUM_SECTORS
NUM_PAGES
PAGE_SIZE
PAGE_COUNT
TEST_ADDRESS
UNIQUE_VALUE
MAX_DATA
XQspiPs QspiInstance
int Test
u8 ReadBuffer[MAX_DATA+DATA_OFFSET+DUMMY_SIZE][MAX_DATA+DATA_OFFSET+DUMMY_SIZE]
u8 WriteBuffer[PAGE_SIZE+DATA_OFFSET][PAGE_SIZE+DATA_OFFSET]
void FlashErase(XQspiPs *QspiPtr, u32 Address, u32 ByteCount)
This function erases the sectors in the serial FLASH connected to the QSPI interface.
QspiPtr is a pointer to the QSPI driver component to use. Address contains the address of the first sector which needs to be erased. ByteCount contains the total size to be erased. None. None.
void FlashWrite(XQspiPs *QspiPtr, u32 Address, u32 ByteCount, u8 Command)
This function writes to the serial FLASH connected to the QSPI interface.
All the data put into the buffer must be in the same page of the device with page boundaries being on 256 byte boundaries. QspiPtr is a pointer to the QSPI driver component to use. Address contains the address to write data to in the FLASH. ByteCount contains the number of bytes to write. Command is the command used to write data to the flash. QSPI device supports only Page Program command to write data to the flash. None. None.
void FlashRead(XQspiPs *QspiPtr, u32 Address, u32 ByteCount, u8 Command)
This function reads from the serial FLASH connected to the QSPI interface.
QspiPtr is a pointer to the QSPI driver component to use. Address contains the address to read data from in the FLASH. ByteCount contains the number of bytes to read. Command is the command used to read data from the flash. QSPI device supports one of the Read, Fast Read, Dual Read and Fast Read commands to read data from the flash. None. None.
References XQspiPs_Transfer.
Referenced by QspiFlashIntrExample, QspiFlashPolledExample, QspiG128FlashExample.
int FlashReadID(void)
This function reads serial FLASH ID connected to the SPI interface.
XST_SUCCESS if read id, otherwise XST_FAILURE. None.
void FlashQuadEnable(XQspiPs *QspiPtr)
This function enables quad mode in the serial flash connected to the SPI interface.
QspiPtr is a pointer to the QSPI driver component to use. None. None.
int QspiFlashPolledExample(XQspiPs *QspiInstancePtr, UINTPTR BaseAddress)
The purpose of this function is to illustrate how to use the XQspiPs device driver in polled mode.
This function writes and reads data from a serial FLASH. QspiInstancePtr is a pointer to the QSPIPS driver to use. BaseAddress contains the base address of the device XST_SUCCESS if successful, else XST_FAILURE. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XQspiPs_Config::BaseAddress, FlashErase, FlashQuadEnable, FlashRead, FlashReadID, FlashWrite, XQspiPs_CfgInitialize, XQSPIPS_CLK_PRESCALE_8, XQSPIPS_FORCE_SSELECT_OPTION, XQSPIPS_HOLD_B_DRIVE_OPTION, XQspiPs_LookupConfig, XQSPIPS_MANUAL_START_OPTION, XQspiPs_SelfTest, XQspiPs_SetClkPrescaler, XQspiPs_SetOptions, XQspiPs_SetSlaveSelect.
Referenced by main.
int main(void)
Main function to call the QSPI Flash example.
XST_SUCCESS if successful, otherwise XST_FAILURE. None
References QspiFlashPolledExample.