xqspips_options.c
XQSPIPS_NUM_OPTIONS
OptionsMap OptionsTable[][]
s32 XQspiPs_SetOptions(XQspiPs *InstancePtr, u32 Options)
This function sets the options for the QSPI device driver.
The options control how the device behaves relative to the QSPI bus. The device must be idle rather than busy transferring data before setting these device options. InstancePtr is a pointer to the XQspiPs instance. Options contains the specified options to be set. This is a bit mask where a 1 means to turn the option on, and a 0 means to turn the option off. One or more bit values may be contained in the mask. See the bit definitions named XQSPIPS_*_OPTIONS in the file xqspips.h. XST_SUCCESS if options are successfully set.XST_DEVICE_BUSY if the device is currently transferring data. The transfer must complete or be aborted before setting options. This function is not thread-safe.
References XQspiPs_Config::BaseAddress, XQspiPs::Config, XQspiPs::IsBusy, XQspiPs::IsReady, XQSPIPS_CR_OFFSET, XQSPIPS_LQSPI_CR_LINEAR_MASK, XQSPIPS_LQSPI_CR_OFFSET, XQSPIPS_LQSPI_CR_RST_STATE, XQSPIPS_LQSPI_MODE_OPTION, XQspiPs_ReadReg, XQspiPs_SetSlaveSelect, XQspiPs_WriteReg.
Referenced by DualStackExample, LinearQspiFlashExample, QspiFlashIntrExample, QspiFlashPolledExample, QspiG128FlashExample.
u32 XQspiPs_GetOptions(XQspiPs *InstancePtr)
This function gets the options for the QSPI device.
The options control how the device behaves relative to the QSPI bus. InstancePtr is a pointer to the XQspiPs instance. Options contains the specified options currently set. This is a bit value where a 1 means the option is on, and a 0 means the option is off. See the bit definitions named XQSPIPS_*_OPTIONS in file xqspips.h.None.
References XQspiPs_Config::BaseAddress, XQspiPs::Config, XQspiPs::IsReady, XQSPIPS_CR_OFFSET, XQSPIPS_LQSPI_CR_LINEAR_MASK, XQSPIPS_LQSPI_CR_OFFSET, XQSPIPS_LQSPI_MODE_OPTION, XQspiPs_ReadReg.
s32 XQspiPs_SetClkPrescaler(XQspiPs *InstancePtr, u8 Prescaler)
This function sets the clock prescaler for an QSPI device.
The device must be idle rather than busy transferring data before setting these device options. InstancePtr is a pointer to the XQspiPs instance. Prescaler is the value that determine how much the clock should be divided by. Use the XQSPIPS_CLK_PRESCALE_* constants defined in xqspips.h for this setting. XST_SUCCESS if options are successfully set.XST_DEVICE_BUSY if the device is currently transferring data. The transfer must complete or be aborted before setting options. This function is not thread-safe.
References XQspiPs_Config::BaseAddress, XQspiPs::Config, XQspiPs::IsBusy, XQspiPs::IsReady, XQSPIPS_CR_OFFSET, XQSPIPS_CR_PRESC_MASK, XQSPIPS_CR_PRESC_MAXIMUM, XQSPIPS_CR_PRESC_SHIFT, XQspiPs_ReadReg, XQspiPs_WriteReg.
Referenced by DualStackExample, LinearQspiFlashExample, QspiFlashIntrExample, QspiFlashPolledExample, QspiG128FlashExample.
u8 XQspiPs_GetClkPrescaler(XQspiPs *InstancePtr)
This function gets the clock prescaler of an QSPI device.
InstancePtr is a pointer to the XQspiPs instance. The prescaler value. None.
References XQspiPs_Config::BaseAddress, XQspiPs::Config, XQspiPs::IsReady, XQSPIPS_CR_OFFSET, XQSPIPS_CR_PRESC_MASK, XQSPIPS_CR_PRESC_SHIFT, XQspiPs_ReadReg.
int XQspiPs_SetDelays(XQspiPs *InstancePtr, u8 DelayNss, u8 DelayBtwn, u8 DelayAfter, u8 DelayInit)
This function sets the delay register for the QSPI device driver.
The delay register controls the Delay Between Transfers, Delay After Transfers, and the Delay Initially. The default value is 0x0. The range of each delay value is 0-255. InstancePtr is a pointer to the XQspiPs instance. DelayNss is the delay to de-assert slave select between two word transfers. DelayBtwn is the delay between one Slave Select being de-activated and the activation of another slave. The delay is the number of master clock periods given by DelayBtwn + 2. DelayAfter define the delay between the last bit of the current byte transfer and the first bit of the next byte transfer. The delay in number of master clock periods is given as: CHPA=0:DelayInit+DelayAfter+3 CHPA=1:DelayAfter+1 DelayInit is the delay between asserting the slave select signal and the first bit transfer. The delay int number of master clock periods is DelayInit+1. XST_SUCCESS if delays are successfully set.XST_DEVICE_BUSY if the device is currently transferring data. The transfer must complete or be aborted before setting options. None.
References XQspiPs_Config::BaseAddress, XQspiPs::Config, XQspiPs::IsBusy, XQspiPs::IsReady, XQSPIPS_DR_AFTER_SHIFT, XQSPIPS_DR_BTWN_SHIFT, XQSPIPS_DR_NSS_SHIFT, XQSPIPS_DR_OFFSET, XQspiPs_WriteReg.
Referenced by XQspiPs_SelfTest.
void XQspiPs_GetDelays(XQspiPs *InstancePtr, u8 *DelayNss, u8 *DelayBtwn, u8 *DelayAfter, u8 *DelayInit)
This function gets the delay settings for an QSPI device.
The delay register controls the Delay Between Transfers, Delay After Transfers, and the Delay Initially. The default value is 0x0. InstancePtr is a pointer to the XQspiPs instance. DelayNss is a pointer to the Delay to de-assert slave select between two word transfers. DelayBtwn is a pointer to the Delay Between transfers value. This is a return parameter. DelayAfter is a pointer to the Delay After transfer value. This is a return parameter. DelayInit is a pointer to the Delay Initially value. This is a return parameter. None. None.
References XQspiPs_Config::BaseAddress, XQspiPs::Config, XQspiPs::IsReady, XQSPIPS_DR_AFTER_MASK, XQSPIPS_DR_AFTER_SHIFT, XQSPIPS_DR_BTWN_MASK, XQSPIPS_DR_BTWN_SHIFT, XQSPIPS_DR_INIT_MASK, XQSPIPS_DR_NSS_MASK, XQSPIPS_DR_NSS_SHIFT, XQSPIPS_DR_OFFSET, XQspiPs_ReadReg.
Referenced by XQspiPs_SelfTest.