axis_switch
XAXIS_SCR_CTRL_OFFSET
Control Register offset.
XAXIS_SCR_MI_MUX_START_OFFSET
Start of MI MUX Register offset.
Referenced by XAxisScr_IsMiPortDisabled, XAxisScr_IsMiPortEnabled, XAxisScr_MiPortDisable, XAxisScr_MiPortDisableAll, XAxisScr_MiPortEnable.
XAXIS_SCR_MI_MUX_END_OFFSET
End of MI MUX Register offset.
XAXIS_SCR_CTRL_REG_UPDATE_MASK
Register Update mask.
XAXIS_SCR_MI_X_MUX_MASK
MI MUX mask.
Referenced by XAxisScr_IsMiPortEnabled.
XAXIS_SCR_MI_X_DISABLE_MASK
MI Disable mask.
Referenced by XAxisScr_MiPortDisable, XAxisScr_MiPortDisableAll.
XAXIS_SCR_MI_X_DISABLE_SHIFT
MI Disable shift.
Referenced by XAxisScr_IsMiPortDisabled, XAxisScr_IsMiPortEnabled.
XAxisScr_In32
Input Operations.
XAxisScr_Out32
Output Operations.
XAxisScr_ReadReg
This macro reads a value from a AXI4-Stream Switch register.
A 32 bit read is performed. If the component is implemented in a smaller width, only the least significant data is read from the register. The most significant data will be read as 0. BaseAddress is the base address of the XAxis_Switch core instance. RegOffset is the register offset of the register (defined at the top of this file). The 32-bit value of the register. C-style signature: u32 XAxisScr_ReadReg(u32 BaseAddress, u32 RegOffset)
Referenced by XAxisScr_IsMiPortDisabled, XAxisScr_IsMiPortEnabled.
XAxisScr_WriteReg
This macro writes a value to a AXI4-Stream Switch register.
A 32 bit write is performed. If the component is implemented in a smaller width, only the least significant data is written. BaseAddress is the base address of the XAxis_Switch core instance. RegOffset is the register offset of the register (defined at the top of this file) to be written. Data is the 32-bit value to write into the register. None. C-style signature: void XAxisScr_WriteReg(u32 BaseAddress, u32 RegOffset, u32 Data)
Referenced by XAxisScr_MiPortDisable, XAxisScr_MiPortDisableAll, XAxisScr_MiPortEnable.
XAxis_Switch_Config XAxis_Switch_ConfigTable[][]
s32 XAxisScr_CfgInitialize(XAxis_Switch *InstancePtr, XAxis_Switch_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the AXI4-Stream Switch core.
This function must be called prior to using the core. Initialization of the core includes setting up the instance data and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the XAxis_Switch core instance. CfgPtr points to the configuration structure associated with the AXI4-Stream Switch core. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if XAxisScr_CfgInitialize was successful. Axis_Switch core connects up to 16 masters to 16 slaves.
References XAxis_Switch_Config::BaseAddress, XAxis_Switch::Config, XAxis_Switch::IsReady, XAxisScr_MiPortDisableAll.
Referenced by AxisSwitch_Example.
void XAxisScr_MiPortEnable(XAxis_Switch *InstancePtr, u8 MiIndex, u8 SiIndex)
This function enables the MUX port specified by a MI index and links with desired SI, indicated by a SiIndex.
InstancePtr is a pointer to the XAxis_Switch core instance. MiIndex specifies an index that will be used for enabling MUX which is within the range [0 to 15]. SiIndex specifies an index that will be used as a source to MUX. The range is [0 to 15]. None. MUX[MiIndex] is sourced from SI[SiIndex]. Axis_Switch core connects up to 16 masters to 16 slaves.
References XAxis_Switch_Config::BaseAddress, XAxis_Switch::Config, XAXIS_SCR_MI_MUX_START_OFFSET, XAxisScr_WriteReg.
Referenced by AxisSwitch_Example, XAxisScr_SelfTest.
void XAxisScr_MiPortDisable(XAxis_Switch *InstancePtr, u8 MiIndex)
This function disables the MUX port specified by a MI index and un-link SI, set previously.
InstancePtr is a pointer to the XAxis_Switch core instance. MiIndex specifies an index that will be used for disabling MUX which is within the range [0 to 15]. None. MUX[MiIndex] is removed for SI[SiIndex]. Axis_Switch core connects up to 16 masters to 16 slaves.
References XAxis_Switch_Config::BaseAddress, XAxis_Switch::Config, XAXIS_SCR_MI_MUX_START_OFFSET, XAXIS_SCR_MI_X_DISABLE_MASK, XAxisScr_WriteReg.
Referenced by AxisSwitch_Example.
s32 XAxisScr_IsMiPortEnabled(XAxis_Switch *InstancePtr, u8 MiIndex, u8 SiIndex)
This function returns the status of whether MUX is sourced from desired SI.
InstancePtr is a pointer to the XAxis_Switch core instance. MiIndex specifies an index that will be used for addressing the MUX which is within the range [0 to 15]. SiIndex specifies an index that will be used to identify, whether it is sourced. The range is [0 to 15]. TRUE, if MUX is sourced from SI.FALSE, if MUX is not sourced from SI. Axis_Switch core connects up to 16 masters to 16 slaves.
References XAxis_Switch_Config::BaseAddress, XAxis_Switch::Config, XAXIS_SCR_MI_MUX_START_OFFSET, XAXIS_SCR_MI_X_DISABLE_SHIFT, XAXIS_SCR_MI_X_MUX_MASK, XAxisScr_ReadReg.
Referenced by AxisSwitch_Example, XAxisScr_SelfTest.
s32 XAxisScr_IsMiPortDisabled(XAxis_Switch *InstancePtr, u8 MiIndex)
This function returns the status of whether MUX is disabled.
InstancePtr is a pointer to the XAxis_Switch core instance. MiIndex specifies an index that will be used for addressing the MUX which is within the range [0 to 15]. TRUE, if MUX is disabled.FALSE, if MUX is enabled. Axis_Switch core connects up to 16 masters to 16 slaves.
References XAxis_Switch_Config::BaseAddress, XAxis_Switch::Config, XAXIS_SCR_MI_MUX_START_OFFSET, XAXIS_SCR_MI_X_DISABLE_SHIFT, XAxisScr_ReadReg.
void XAxisScr_MiPortDisableAll(XAxis_Switch *InstancePtr)
This function disables all the MUX port, in turn removes association with desired SI.
InstancePtr is a pointer to the XAxis_Switch core instance. None. Axis_Switch core connects up to 16 masters to 16 slaves.
References XAxis_Switch_Config::BaseAddress, XAxis_Switch::Config, XAxis_Switch_Config::MaxNumMI, XAXIS_SCR_MI_MUX_START_OFFSET, XAXIS_SCR_MI_X_DISABLE_MASK, XAxisScr_WriteReg.
Referenced by AxisSwitch_Example, XAxisScr_CfgInitialize, XAxisScr_SelfTest.
XAxis_Switch_Config * XAxisScr_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XAxis_Switch_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xaxis_switch.h for the definition of XAxis_Switch_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XAxis_Switch_Config::Name.
Referenced by AxisSwitch_Example.
s32 XAxisScr_SelfTest(XAxis_Switch *InstancePtr)
This function performs self test on AXI4-Stream Switch core registers.
InstancePtr is a pointer to the XAxis_Switch core instance. TRUE if self test passed.FALSE if self test failed. None.
References XAxisScr_IsMiPortEnabled, XAxisScr_MiPortDisableAll, XAxisScr_MiPortEnable.
XAXIS_SWITCH_H_
Prevent circular inclusions by using protection macros.
XAxisScr_RegUpdateEnable
This macro enables register updates.
InstancePtr is a pointer to the XAxis_Switch core instance. None. C-style signature: void XAxisScr_RegUpdateEnable(XAxis_Switch *InstancePtr)
Referenced by AxisSwitch_Example.
XAxisScr_RegUpdateDisable
This macro disables register updates.
InstancePtr is a pointer to the XAxis_Switch core instance. None. C-style signature: void XAxisScr_RegUpdateDisable(XAxis_Switch *InstancePtr)
Referenced by AxisSwitch_Example.
XAXIS_SWITCH_HW_H_
Prevent circular inclusions by using protection macros.
XPAR_XAXIS_SWITCH_NUM_INSTANCES