usbpsu_api
XusbPsuLinkState
U0 state/ in HS - ON.
XusbPsuLinkStateChange
U0 /in HS - ON.
typedef XUsbPsu_Config Usb_Config
typedef configuration structure
XUsbPsu_Config XUsbPsu_ConfigTable[][]
Configuration table.
Referenced by XUsbPsu_LookupConfig.
static void XUsbPsu_SetMode(struct XUsbPsu *InstancePtr, u32 Mode)
Sets mode of core to USB Device/Host/OTG.
InstancePtr Pointer to the XUsbPsu instance to be worked on. Mode Mode to set XUSBPSU_GCTL_PRTCAP_OTGXUSBPSU_GCTL_PRTCAP_HOSTXUSBPSU_GCTL_PRTCAP_DEVICE None
static void XUsbPsu_InitializeEps(struct XUsbPsu *InstancePtr)
Initializes endpoints.
All OUT endpoints are even numbered and all IN endpoints are odd numbered. EP0 is for Control OUT and EP1 is for Control IN. InstancePtr Pointer to the XUsbPsu instance. None.
s32 XUsbPsu_CfgInitialize(struct XUsbPsu *InstancePtr, XUsbPsu_Config *ConfigPtr, u32 BaseAddress)
This function does the following:
- initializes a specific XUsbPsu instance. - sets up Event Buffer for Core to write events. - Core Reset and PHY Reset. - Sets core in Device Mode. - Sets default speed as HIGH_SPEED. - Sets Device Address to 0. - Enables interrupts. InstancePtr Pointer to the XUsbPsu instance. ConfigPtr Points to the XUsbPsu device configuration structure. BaseAddress Device base address in the virtual memory address space. If the address translation is not used then the physical address is passed. Unexpected errors may occur if the address mapping is changed after this function is invoked. XST_SUCCESS else XST_FAILURE
References XUsbPsu::ConfigPtr, XUsbPsu_Config::EnableSuperSpeed, XUsbPsu::NumInEps, XUsbPsu::NumOutEps, XUsbPsu_CoreInit, XUsbPsu_EventBuffersSetup, XUsbPsu_ReadHwParams, XUsbPsu_SetDeviceAddress, XUsbPsu_SetSpeed.
s32 XUsbPsu_Start(struct XUsbPsu *InstancePtr)
Starts the controller so that host can detect this device.
InstancePtr Pointer to the XUsbPsu instance. XST_SUCCESS else XST_FAILURE
References XUsbPsu_WaitClearTimeout.
s32 XUsbPsu_Stop(struct XUsbPsu *InstancePtr)
Stops the controller so that the device disconnects from the host.
InstancePtr Pointer to the XUsbPsu instance. XST_SUCCESS else XST_FAILURE
References XUsbPsu_WaitSetTimeout.
Referenced by XUsbPsu_Idle.
u8 XUsbPsu_GetLinkState(struct XUsbPsu *InstancePtr)
Gets current state of USB link.
InstancePtr Pointer to the XUsbPsu instance. Link State
s32 XUsbPsu_SetLinkState(struct XUsbPsu *InstancePtr, XusbPsuLinkStateChange State)
Sets USB Link to a particular State.
InstancePtr Pointer to the XUsbPsu instance. State State of Link to set. XST_SUCCESS else XST_FAILURE
References XUsbPsu_WaitClearTimeout.
s32 XUsbPsu_SetU1SleepTimeout(struct XUsbPsu *InstancePtr, u8 Timeout)
Sets U1 sleep timeout.
InstancePtr Pointer to the XUsbPsu instance. Timeout Time in microseconds XST_SUCCESS else XST_FAILURE
s32 XUsbPsu_SetU2SleepTimeout(struct XUsbPsu *InstancePtr, u8 Timeout)
Sets U2 sleep timeout.
InstancePtr Pointer to the XUsbPsu instance. Timeout Time in microseconds. XST_SUCCESS else XST_FAILURE
s32 XUsbPsu_AcceptU1U2Sleep(struct XUsbPsu *InstancePtr)
Enable Accept U1 and U2 sleep enable.
InstancePtr Pointer to the XUsbPsu instance. XST_SUCCESS else XST_FAILURE
s32 XUsbPsu_U1SleepEnable(struct XUsbPsu *InstancePtr)
Enables U1 enable sleep.
InstancePtr Pointer to the XUsbPsu instance. XST_SUCCESS else XST_FAILURE
s32 XUsbPsu_U2SleepEnable(struct XUsbPsu *InstancePtr)
Enables U2 enable sleep.
InstancePtr Pointer to the XUsbPsu instance. XST_SUCCESS else XST_FAILURE
s32 XUsbPsu_U1SleepDisable(struct XUsbPsu *InstancePtr)
Enables U1 disable sleep.
InstancePtr Pointer to the XUsbPsu instance. XST_SUCCESS else XST_FAILURE
s32 XUsbPsu_U2SleepDisable(struct XUsbPsu *InstancePtr)
Enables U2 disable sleep.
InstancePtr Pointer to the XUsbPsu instance. XST_SUCCESS else XST_FAILURE
s32 XUsbPsu_IsSuperSpeed(struct XUsbPsu *InstancePtr)
Checks if the current speed is super speed or not.
InstancePtr Pointer to the XUsbPsu instance. XST_SUCCESS else XST_FAILURE
References XUsbPsu::AppData, Usb_DevData::Speed, XUSBPSU_SPEED_SUPER.
Referenced by IsSuperSpeed.
static void* XUsbPsu_get_drvdata(struct XUsbPsu *InstancePtr)
Returns the data pointer of driver instance.
InstancePtr Pointer to the XUsbPsu instance to be worked on. data pointer of driver instance.
static void XUsbPsu_set_drvdata(struct XUsbPsu *InstancePtr, void *data)
Sets driver data from driver like speed/state.
InstancePtr Pointer to the XUsbPsu instance to be worked on. data Void pointer None.
static void XUsbPsu_set_ch9handler(struct XUsbPsu *InstancePtr, void(*func)(struct Usb_DevData *, SetupPacket *))
This function is used as chapter 9 interrupt handler.
InstancePtr Pointer to the XUsbPsu instance to be worked on. func USB Chapter9 function handler None.
static void XUsbPsu_set_rsthandler(struct XUsbPsu *InstancePtr, void(*func)(struct Usb_DevData *))
Handles USB resets.
InstancePtr Pointer to the XUsbPsu instance to be worked on. func USB Reset function handler. None.
static void XUsbPsu_set_disconnect(struct XUsbPsu *InstancePtr, void(*func)(struct Usb_DevData *))
This function is used as disconnect interrupt handler.
InstancePtr Pointer to the XUsbPsu instance to be worked on. func USB disconnect function handler None.
s32 XUsbPsu_EpEnable(struct XUsbPsu *InstancePtr, u8 UsbEpNum, u8 Dir, u16 Maxsize, u8 Type, u8 Restore)
Enables endpoint for sending/receiving data.
InstancePtr Pointer to the XUsbPsu instance. UsbEpNum USB endpoint number. Dir Direction of endpoint XUSBPSU_EP_DIR_IN/XUSBPSU_EP_DIR_OUT. Maxsize Size of Endpoint size. Type Endpoint type Control/Bulk/Interrupt/Isoc. Restore Typically False, True if saved state has to be restored. XST_SUCCESS else XST_FAILURE.
References XUsbPsu_Trb::BufferPtrHigh, XUsbPsu_Trb::BufferPtrLow, XUsbPsu::ConfigPtr, XUsbPsu_Trb::Ctrl, XUsbPsu_Ep::CurUf, XUsbPsu_Ep::Direction, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Config::IsCacheCoherent, XUsbPsu::IsHibernated, XUsbPsu_Ep::MaxSize, XUsbPsu_Ep::PhyEpNum, XUsbPsu_Ep::TrbDequeue, XUsbPsu_Ep::TrbEnqueue, XUsbPsu_Ep::Type, XUsbPsu_Ep::UsbEpNum, XUSBPSU_EP_DIR_IN, XUSBPSU_EP_DIR_OUT, XUsbPsu_SetEpConfig, XUsbPsu_SetXferResource, XUsbPsu_StartEpConfig.
Referenced by XUsbPsu_EnableControlEp.
s32 XUsbPsu_EpDisable(struct XUsbPsu *InstancePtr, u8 UsbEpNum, u8 Dir)
Disables Endpoint.
InstancePtr Pointer to the XUsbPsu instance. UsbEpNum USB endpoint number. Dir Direction of endpoint XUSBPSU_EP_DIR_IN/XUSBPSU_EP_DIR_OUT. XST_SUCCESS else XST_FAILURE.
References XUsbPsu_Ep::Direction, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Ep::MaxSize, XUsbPsu_Ep::PhyEpNum, XUsbPsu_Ep::TrbDequeue, XUsbPsu_Ep::TrbEnqueue, XUsbPsu_Ep::Type, XUsbPsu_Ep::UsbEpNum, XUSBPSU_EP_DIR_IN, XUSBPSU_EP_DIR_OUT, XUsbPsu_EpClearStall.
void XUsbPsu_ClearStalls(struct XUsbPsu *InstancePtr)
Clears stall on all endpoints.
InstancePtr Pointer to the XUsbPsu instance. None.
References XUsbPsu_Ep::Direction, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Ep::UsbEpNum, XUsbPsu_GetEpParams, XUsbPsu_SendEpCmd.
s32 XUsbPsu_EpBufferSend(struct XUsbPsu *InstancePtr, u8 UsbEp, u8 *BufferPtr, u32 BufferLen)
Initiates DMA to send data on endpoint to the host.
InstancePtr Pointer to the XUsbPsu instance. UsbEp USB endpoint number. BufferPtr Pointer to data. This data buffer is cache-aligned. BufferLen Length of data buffer. XST_SUCCESS else XST_FAILURE This function is expected to initiates DMA to send data on endpoint towards host. This data buffer should be aligned.
References XUsbPsu_Ep::BufferPtr, XUsbPsu_Trb::BufferPtrHigh, XUsbPsu_Trb::BufferPtrLow, XUsbPsu_Ep::BytesTxed, XUsbPsu::ConfigPtr, XUsbPsu_Trb::Ctrl, XUsbPsu_Ep::CurUf, XUsbPsu_Ep::Direction, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Config::IsCacheCoherent, XUsbPsu_EpParams::Param0, XUsbPsu_EpParams::Param1, XUsbPsu_EpParams::Param2, XUsbPsu_Ep::PhyEpNum, XUsbPsu_Ep::RequestedBytes, XUsbPsu_Ep::ResourceIndex, XUsbPsu_Trb::Size, XUsbPsu_Ep::TrbEnqueue, XUsbPsu_Ep::Type, XUsbPsu_Ep::UsbEpNum, XUSBPSU_ENDPOINT_XFER_BULK, XUSBPSU_ENDPOINT_XFER_INT, XUSBPSU_ENDPOINT_XFER_ISOC, XUsbPsu_Ep0Send, XUSBPSU_EP_DIR_IN, XUsbPsu_EpGetTransferIndex, XUsbPsu_SendEpCmd.
s32 XUsbPsu_EpBufferRecv(struct XUsbPsu *InstancePtr, u8 UsbEp, u8 *BufferPtr, u32 Length)
Initiates DMA to receive data on endpoint from host.
InstancePtr Pointer to the XUsbPsu instance. UsbEp USB endpoint number. BufferPtr Pointer to data. This data buffer is cache-aligned. Length Length of data to be received. XST_SUCCESS else XST_FAILURE This function is expected to initiates DMA to receive data on the endpoint from the host. This data buffer should be aligned.
References XUsbPsu_Ep::BufferPtr, XUsbPsu_Trb::BufferPtrHigh, XUsbPsu_Trb::BufferPtrLow, XUsbPsu_Ep::BytesTxed, XUsbPsu::ConfigPtr, XUsbPsu_Trb::Ctrl, XUsbPsu_Ep::CurUf, XUsbPsu_Ep::Direction, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Config::IsCacheCoherent, XUsbPsu_Ep::MaxSize, XUsbPsu_EpParams::Param0, XUsbPsu_EpParams::Param1, XUsbPsu_EpParams::Param2, XUsbPsu_Ep::RequestedBytes, XUsbPsu_Ep::ResourceIndex, XUsbPsu_Trb::Size, XUsbPsu_Ep::TrbEnqueue, XUsbPsu_Ep::Type, XUsbPsu_Ep::UnalignedTx, XUsbPsu_Ep::UsbEpNum, XUSBPSU_ENDPOINT_XFER_BULK, XUSBPSU_ENDPOINT_XFER_INT, XUSBPSU_ENDPOINT_XFER_ISOC, XUsbPsu_Ep0Recv, XUSBPSU_EP_DIR_OUT, XUsbPsu_EpGetTransferIndex, XUsbPsu_SendEpCmd.
void XUsbPsu_EpSetStall(struct XUsbPsu *InstancePtr, u8 Epnum, u8 Dir)
Stalls an endpoint.
InstancePtr Pointer to the XUsbPsu instance. Epnum USB endpoint number. Dir Direction None.
References XUsbPsu_Ep::Direction, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Ep::UsbEpNum, XUSBPSU_EP_DIR_IN, XUSBPSU_EP_DIR_OUT, XUsbPsu_GetEpParams, XUsbPsu_SendEpCmd.
Referenced by XUsbPsu_Ep0StallRestart.
void XUsbPsu_EpClearStall(struct XUsbPsu *InstancePtr, u8 Epnum, u8 Dir)
Clears stall on an endpoint.
InstancePtr Pointer to the XUsbPsu instance. Epnum USB endpoint number. Dir Direction. None.
References XUsbPsu_Ep::Direction, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Ep::UsbEpNum, XUSBPSU_EP_DIR_IN, XUSBPSU_EP_DIR_OUT, XUsbPsu_GetEpParams, XUsbPsu_SendEpCmd.
Referenced by XUsbPsu_ClearStallAllEp, XUsbPsu_EpDisable.
void XUsbPsu_SetEpHandler(struct XUsbPsu *InstancePtr, u8 Epnum, u8 Dir, void(*Handler)(void *, u32, u32))
Sets an user handler to be called after data is sent/received by an endpoint.
InstancePtr Pointer to the XUsbPsu instance. Epnum USB endpoint number. Dir Direction of endpoint XUSBPSU_EP_DIR_IN/XUSBPSU_EP_DIR_OUT. Handler User handler to be called. None.
References XUsbPsu::eps, XUsbPsu_Ep::Handler, XUsbPsu_Ep::PhyEpNum, XUSBPSU_EP_DIR_IN, XUSBPSU_EP_DIR_OUT.
s32 XUsbPsu_IsEpStalled(struct XUsbPsu *InstancePtr, u8 Epnum, u8 Dir)
Returns status of endpoint whether it is stalled or not.
InstancePtr Pointer to the XUsbPsu instance. Epnum USB endpoint number. Dir Direction of endpoint XUSBPSU_EP_DIR_IN/XUSBPSU_EP_DIR_OUT. 1 - if stalled 0 - if not stalled
References XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Ep::PhyEpNum, XUSBPSU_EP_DIR_IN, XUSBPSU_EP_DIR_OUT.
void XUsbPsu_StopTransfer(struct XUsbPsu *InstancePtr, u8 UsbEpNum, u8 Dir, u8 Force)
Stops transfer on Endpoint.
InstancePtr Pointer to the XUsbPsu instance. UsbEpNum USB endpoint number. Dir Direction of endpoint XUSBPSU_EP_DIR_IN/XUSBPSU_EP_DIR_OUT. Force Flag to stop/pause transfer. None.
References XUsbPsu_Ep::Direction, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Ep::ResourceIndex, XUsbPsu_Ep::UsbEpNum, XUSBPSU_EP_DIR_IN, XUSBPSU_EP_DIR_OUT, XUsbPsu_GetEpParams, XUsbPsu_SendEpCmd, XUsbPsu_Sleep.
Referenced by XUsbPsu_Idle, XUsbPsu_StopActiveTransfers.
void XUsbPsu_IntrHandler(void *XUsbPsuInstancePtr)
Main interrupt handler.
XUsbPsuInstancePtr Void pointer to the XUsbPsu instance. None.
References XUsbPsu_EvtBuffer::Count, XUsbPsu::Evt, XUsbPsu_EvtBuffer::Flags, XUsbPsu_EventBufferHandler.
Referenced by main, UsbPollHandler.
void XUsbPsu_EnableIntr(struct XUsbPsu *InstancePtr, u32 Mask)
Enables an interrupt in event enable RegValister.
InstancePtr Pointer to the XUsbPsu instance to be worked on. Mask OR of any interrupt enable Masks: XUSBPSU_DEVTEN_VNDRDEVTSTRCVEDENXUSBPSU_DEVTEN_EVNTOVERFLOWENXUSBPSU_DEVTEN_CMDCMPLTENXUSBPSU_DEVTEN_ERRTICERRENXUSBPSU_DEVTEN_SOFENXUSBPSU_DEVTEN_EOPFENXUSBPSU_DEVTEN_HIBERNATIONREQEVTENXUSBPSU_DEVTEN_WKUPEVTENXUSBPSU_DEVTEN_ULSTCNGENXUSBPSU_DEVTEN_CONNECTDONEENXUSBPSU_DEVTEN_USBRSTENXUSBPSU_DEVTEN_DISCONNEVTEN None
Referenced by main, UsbEnableEvent.
void XUsbPsu_DisableIntr(struct XUsbPsu *InstancePtr, u32 Mask)
Disables an interrupt in event enable RegValister.
InstancePtr Pointer to the XUsbPsu instance to be worked on. Mask OR of Interrupt Enable Masks XUSBPSU_DEVTEN_VNDRDEVTSTRCVEDENXUSBPSU_DEVTEN_EVNTOVERFLOWENXUSBPSU_DEVTEN_CMDCMPLTENXUSBPSU_DEVTEN_ERRTICERRENXUSBPSU_DEVTEN_SOFENXUSBPSU_DEVTEN_EOPFENXUSBPSU_DEVTEN_HIBERNATIONREQEVTENXUSBPSU_DEVTEN_WKUPEVTENXUSBPSU_DEVTEN_ULSTCNGENXUSBPSU_DEVTEN_CONNECTDONEENXUSBPSU_DEVTEN_USBRSTENXUSBPSU_DEVTEN_DISCONNEVTEN None
s32 XUsbPsu_SetDeviceAddress(struct XUsbPsu *InstancePtr, u16 Addr)
Sets the device address of the core.
InstancePtr Pointer to the XUsbPsu instance. Addr Address to set. XST_SUCCESS else XST_FAILURE
References XUsbPsu::AppData, Usb_DevData::State, XUSBPSU_STATE_ADDRESS, XUSBPSU_STATE_CONFIGURED, XUSBPSU_STATE_DEFAULT.
Referenced by XUsbPsu_CfgInitialize.
void XUsbPsu_Idle(struct XUsbPsu *InstancePtr)
This function puts the controller into idle state by stopping the transfers for all endpoints, stopping the usb core, and clearing the event buffers.
InstancePtr Pointer to the XUsbPsu instance to be worked on. None
References XUSBPSU_EP_DIR_IN, XUSBPSU_EP_DIR_OUT, XUsbPsu_EpTransferDeactive, XUsbPsu_ReadHwParams, XUsbPsu_Stop, XUsbPsu_StopTransfer, XUsbPsu_WaitClearTimeout.
void XUsbPsu_SetSpeed(struct XUsbPsu *InstancePtr, u32 Speed)
Sets speed of the core for connecting to host.
InstancePtr Pointer to the XUsbPsu instance. Speed Required speed XUSBPSU_DCFG_HIGHSPEEDXUSBPSU_DCFG_FULLSPEED2XUSBPSU_DCFG_LOWSPEEDXUSBPSU_DCFG_FULLSPEED1 None
Referenced by XUsbPsu_CfgInitialize.
void XUsbPsu_Sleep(u32 USeconds)
API for Sleep routine.
USeconds Time in MicroSeconds. None.
Referenced by XUsbPsu_Ep0_EndControlData, XUsbPsu_PhyReset, XUsbPsu_StopTransfer.
void XUsbPsu_Ep0StallRestart(struct XUsbPsu *InstancePtr)
Stalls control endpoint and restarts to receive setup packet.
InstancePtr Pointer to the XUsbPsu instance. None
References XUsbPsu::Ep0State, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUSBPSU_EP_DIR_OUT, XUsbPsu_EpSetStall, XUsbPsu_RecvSetup.
Referenced by XUsbPsu_Ep0StatusDone, XUsbPsu_Ep0XferNotReady.
XUsbPsu_Config * XUsbPsu_LookupConfig(u32 BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The table contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration table entry corresponding to the given device ID/BaseAddress, or NULL if no match is found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XUsbPsu_ConfigTable.
struct XUsbPsu_EpParams* XUsbPsu_GetEpParams(struct XUsbPsu *InstancePtr)
Returns zeroed parameters to be used by Endpoint commands.
InstancePtr Pointer to the XUsbPsu instance. Zeroed Params structure pointer.
References XUsbPsu::EpParams, XUsbPsu_EpParams::Param0, XUsbPsu_EpParams::Param1, XUsbPsu_EpParams::Param2.
Referenced by XUsbPsu_ClearStalls, XUsbPsu_Ep0_EndControlData, XUsbPsu_Ep0Recv, XUsbPsu_Ep0Send, XUsbPsu_Ep0StartStatus, XUsbPsu_EpClearStall, XUsbPsu_EpSetStall, XUsbPsu_RecvSetup, XUsbPsu_SaveEndpointState, XUsbPsu_SetEpConfig, XUsbPsu_SetXferResource, XUsbPsu_StartEpConfig, XUsbPsu_StopTransfer.
s32 XUsbPsu_SendEpCmd(struct XUsbPsu *InstancePtr, u8 UsbEpNum, u8 Dir, u32 Cmd, struct XUsbPsu_EpParams *Params)
Sends Endpoint command to the Endpoint.
InstancePtr Pointer to the XUsbPsu instance. UsbEpNum USB endpoint number. Dir Direction of endpoint XUSBPSU_EP_DIR_IN/ XUSBPSU_EP_DIR_OUT. Cmd Endpoint command. Params Endpoint command parameters. XST_SUCCESS else XST_FAILURE.
References XUsbPsu_EpParams::Param0, XUsbPsu_EpParams::Param1, XUsbPsu_EpParams::Param2, XUsbPsu_Ep::PhyEpNum, XUsbPsu_Ep::UsbEpNum, XUSBPSU_EP_DIR_IN, XUSBPSU_EP_DIR_OUT, XUsbPsu_WaitClearTimeout.
Referenced by XUsbPsu_ClearStalls, XUsbPsu_Ep0_EndControlData, XUsbPsu_Ep0Recv, XUsbPsu_Ep0Send, XUsbPsu_Ep0StartStatus, XUsbPsu_EpBufferRecv, XUsbPsu_EpBufferSend, XUsbPsu_EpClearStall, XUsbPsu_EpSetStall, XUsbPsu_RecvSetup, XUsbPsu_SaveEndpointState, XUsbPsu_SetEpConfig, XUsbPsu_SetXferResource, XUsbPsu_StartEpConfig, XUsbPsu_StopTransfer.
void XUsbPsu_Ep0DataDone(struct XUsbPsu *InstancePtr, const struct XUsbPsu_Event_Epevt *Event)
Checks the data phase and calls user endpoint handler.
InstancePtr Pointer to the XUsbPsu instance. Event Pointer to the Endpoint event occurred in core. None.
References XUsbPsu::AppData, XUsbPsu_Ep::BufferPtr, XUsbPsu_Ep::BytesTxed, XUsbPsu::ConfigPtr, XUsbPsu_Event_Epevt::Epnumber, XUsbPsu::eps, XUsbPsu_Ep::Handler, XUsbPsu_Config::IsCacheCoherent, XUsbPsu_Ep::RequestedBytes, XUsbPsu_Ep::UnalignedTx, XUSBPSU_EP_DIR_IN, XUSBPSU_EP_DIR_OUT.
Referenced by XUsbPsu_Ep0XferComplete.
void XUsbPsu_Ep0StatusDone(struct XUsbPsu *InstancePtr)
Checks the status phase and starts next control transfer.
InstancePtr Pointer to the XUsbPsu instance. None.
References XUsbPsu::ConfigPtr, XUsbPsu_Config::IsCacheCoherent, XUsbPsu::IsInTestMode, XUsbPsu::TestMode, XUsbPsu_Ep0StallRestart, XUsbPsu_RecvSetup, XUsbPsu_SetTestMode.
Referenced by XUsbPsu_Ep0XferComplete.
s32 XUsbPsu_Ep0StartStatus(struct XUsbPsu *InstancePtr, const struct XUsbPsu_Event_Epevt *Event)
Starts status phase of control transfer.
InstancePtr Pointer to the XUsbPsu instance. Event Pointer to the Endpoint event occurred in core. XST_SUCCESS else XST_FAILURE
References XUsbPsu_Trb::BufferPtrHigh, XUsbPsu_Trb::BufferPtrLow, XUsbPsu::ConfigPtr, XUsbPsu::ControlDir, XUsbPsu_Trb::Ctrl, XUsbPsu_Ep::Direction, XUsbPsu::Ep0State, XUsbPsu_Event_Epevt::Epnumber, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Config::IsCacheCoherent, XUsbPsu::IsThreeStage, XUsbPsu_EpParams::Param0, XUsbPsu_EpParams::Param1, XUsbPsu_Ep::ResourceIndex, XUsbPsu_Trb::Size, XUsbPsu_Ep::UsbEpNum, XUsbPsu_EpGetTransferIndex, XUsbPsu_GetEpParams, XUsbPsu_SendEpCmd.
Referenced by XUsbPsu_Ep0XferNotReady.
void XUsbPsu_Ep0_EndControlData(struct XUsbPsu *InstancePtr, struct XUsbPsu_Ep *Ept)
Ends data phase which is used in case of the error.
InstancePtr Pointer to the XUsbPsu instance. Ept Pointer to the Endpoint structure. None
References XUsbPsu_Ep::Direction, XUsbPsu_Ep::ResourceIndex, XUsbPsu_Ep::UsbEpNum, XUsbPsu_GetEpParams, XUsbPsu_SendEpCmd, XUsbPsu_Sleep.
Referenced by XUsbPsu_Ep0XferNotReady.
s32 XUsbPsu_EnableControlEp(struct XUsbPsu *InstancePtr, u16 Size)
Enables USB control endpoint that is EP0OUT and EP0IN of Core.
InstancePtr Pointer to the XUsbPsu instance. Size Control endpoint size. XST_SUCCESS else XST_FAILURE.
References XUSBPSU_ENDPOINT_XFER_CONTROL, XUSBPSU_EP_DIR_IN, XUSBPSU_EP_DIR_OUT, XUsbPsu_EpEnable.
Referenced by XUsbPsu_ConnDoneIntr.
static void XUsbPsu_EventBuffersReset(struct XUsbPsu *InstancePtr)
Resets event buffer registers to zero so that events are not written by Core.
InstancePtr Pointer to the XUsbPsu instance to be worked on. None
void XUsbPsu_PhyReset(struct XUsbPsu *InstancePtr)
Issues core PHY reset.
InstancePtr Pointer to the XUsbPsu instance to be worked on. None
References XUsbPsu_Sleep.
Referenced by XUsbPsu_CoreInit.
s32 XUsbPsu_WaitClearTimeout(struct XUsbPsu *InstancePtr, u32 Offset, u32 BitMask, u32 Timeout)
Waits until a bit in a register is cleared or timeout occurs.
InstancePtr Pointer to the XUsbPsu instance to be worked on. Offset Register offset. BitMask Bit mask of required bit to be checked. Timeout Time to wait specified in micro seconds. XST_SUCCESS when bit is cleared.XST_FAILURE when timed out.
References XUsbPsu_Config::BaseAddress, XUsbPsu::ConfigPtr.
Referenced by XUsbPsu_CoreInit, XUsbPsu_Idle, XUsbPsu_SendEpCmd, XUsbPsu_SetLinkState, XUsbPsu_Start.
s32 XUsbPsu_WaitSetTimeout(struct XUsbPsu *InstancePtr, u32 Offset, u32 BitMask, u32 Timeout)
Waits until a bit in a register is set or timeout occurs.
InstancePtr Pointer to the XUsbPsu instance to be worked on Offset Register offset. BitMask Bit mask of required bit to be checked. Timeout Time to wait specified in micro seconds. XST_SUCCESS when bit is set.XST_FAILURE when timed out.
References XUsbPsu_Config::BaseAddress, XUsbPsu::ConfigPtr.
Referenced by XUsbPsu_Stop.
static void XUsbPsu_SetRegVal(struct XUsbPsu *InstancePtr, u32 Offset, u32 BitMask)
Sets the register bits with the bit mask value.
InstancePtr Pointer to the XUsbPsu instance to be worked on Offset Register offset. BitMask Bit mask of required bit to be checked. None
static void XUsbPsu_ClearRegVal(struct XUsbPsu *InstancePtr, u32 Offset, u32 BitMask)
Clears the register bits with the bit mask value.
InstancePtr Pointer to the XUsbPsu instance to be worked on. Offset Register offset. BitMask Bit mask of required bit to be checked. None
u32 XUsbPsu_ReadHwParams(struct XUsbPsu *InstancePtr, u8 RegIndex)
Reads data from hardware parameters registers of the core.
InstancePtr Pointer to the XUsbPsu instance to be worked on RegIndex Register number to read. XUSBPSU_GHWPARAMS0XUSBPSU_GHWPARAMS1XUSBPSU_GHWPARAMS2XUSBPSU_GHWPARAMS3XUSBPSU_GHWPARAMS4XUSBPSU_GHWPARAMS5XUSBPSU_GHWPARAMS6XUSBPSU_GHWPARAMS7 One of the GHWPARAMS RegValister contents.
Referenced by XUsbPsu_CfgInitialize, XUsbPsu_CoreInit, XUsbPsu_Idle.
s32 XUsbPsu_SetTestMode(struct XUsbPsu *InstancePtr, u32 Mode)
Enables USB2 test modes.
InstancePtr Pointer to the XUsbPsu instance. Mode Test mode to set. XST_SUCCESS else XST_FAILURE
References XUSBPSU_TEST_FORCE_ENABLE, XUSBPSU_TEST_J, XUSBPSU_TEST_K, XUSBPSU_TEST_PACKET, XUSBPSU_TEST_SE0_NAK.
Referenced by XUsbPsu_Ep0StatusDone.
s32 XUsbPsu_CoreInit(struct XUsbPsu *InstancePtr)
Initializes the core.
InstancePtr Pointer to the XUsbPsu instance to be worked on. XST_SUCCESS if initialization was successful.XST_FAILURE if initialization was not successful.
References XUsbPsu::ConfigPtr, XUsbPsu::HasHibernation, XUsbPsu_Config::IsCacheCoherent, XUsbPsu_PhyReset, XUsbPsu_ReadHwParams, XUsbPsu_WaitClearTimeout.
Referenced by XUsbPsu_CfgInitialize.
void XUsbPsu_EventBuffersSetup(struct XUsbPsu *InstancePtr)
Sets up the event buffers so that events are written by Core.
InstancePtr Pointer to the XUsbPsu instance to be worked on. None
References XUsbPsu_EvtBuffer::BuffAddr, XUsbPsu::EventBuffer, XUsbPsu::Evt, XUsbPsu_EvtBuffer::Offset.
Referenced by XUsbPsu_CfgInitialize.
u32 XUsbPsu_EpGetTransferIndex(struct XUsbPsu *InstancePtr, u8 UsbEpNum, u8 Dir)
Returns transfer index assigned by Core for an endpoint transfer.
InstancePtr Pointer to the XUsbPsu instance. UsbEpNum USB endpoint number. Dir Direction of endpoint XUSBPSU_EP_DIR_IN/XUSBPSU_EP_DIR_OUT Transfer Resource Index.
References XUSBPSU_EP_DIR_IN, XUSBPSU_EP_DIR_OUT.
Referenced by XUsbPsu_Ep0Recv, XUsbPsu_Ep0Send, XUsbPsu_Ep0StartStatus, XUsbPsu_EpBufferRecv, XUsbPsu_EpBufferSend, XUsbPsu_RecvSetup.
s32 XUsbPsu_StartEpConfig(struct XUsbPsu *InstancePtr, u32 UsbEpNum, u8 Dir)
Sends start new configuration command to the endpoint.
InstancePtr Pointer to the XUsbPsu instance. UsbEpNum USB endpoint number. Dir Direction of endpoint XUSBPSU_EP_DIR_IN/ XUSBPSU_EP_DIR_OUT. XST_SUCCESS else XST_FAILURE. As per data book this command should be issued by software under these conditions: After power-on-reset with XferRscIdx=0 before starting to configure Physical Endpoints 0 and 1.With XferRscIdx=2 before starting to configure Physical Endpoints > 1This command should always be issued to Endpoint 0 (DEPCMD0).
References XUsbPsu::IsConfigDone, XUSBPSU_EP_DIR_OUT, XUsbPsu_GetEpParams, XUsbPsu_SendEpCmd.
Referenced by XUsbPsu_EpEnable.
s32 XUsbPsu_SetEpConfig(struct XUsbPsu *InstancePtr, u8 UsbEpNum, u8 Dir, u16 Size, u8 Type, u8 Restore)
Sends set endpoint configuration command to the endpoint.
InstancePtr Pointer to the XUsbPsu instance. UsbEpNum USB endpoint number. Dir Direction of endpoint -XUSBPSU_EP_DIR_IN/XUSBPSU_EP_DIR_OUT. Size Size of Endpoint size. Type Endpoint type Control/Bulk/Interrupt/Isoc. Restore Typically false, true if saved state has to be restored. XST_SUCCESS else XST_FAILURE.
References XUsbPsu::AppData, XUsbPsu::eps, XUsbPsu_Ep::EpSavedState, XUsbPsu_Ep::Interval, XUsbPsu_EpParams::Param0, XUsbPsu_EpParams::Param1, XUsbPsu_EpParams::Param2, Usb_DevData::Speed, XUsbPsu_Ep::Type, XUSBPSU_ENDPOINT_XFER_ISOC, XUSBPSU_EP_DIR_OUT, XUsbPsu_GetEpParams, XUsbPsu_SendEpCmd, XUSBPSU_SPEED_SUPER.
Referenced by XUsbPsu_EpEnable.
s32 XUsbPsu_SetXferResource(struct XUsbPsu *InstancePtr, u8 UsbEpNum, u8 Dir)
Sends set transfer resource command to the endpoint.
InstancePtr Pointer to the XUsbPsu instance. UsbEpNum USB endpoint number. Dir Direction of endpoint - XUSBPSU_EP_DIR_IN/XUSBPSU_EP_DIR_OUT XST_SUCCESS else XST_FAILURE.
References XUsbPsu_EpParams::Param0, XUsbPsu_GetEpParams, XUsbPsu_SendEpCmd.
Referenced by XUsbPsu_EpEnable.
void XUsbPsu_StopActiveTransfers(struct XUsbPsu *InstancePtr)
Stops any active transfer.
InstancePtr Pointer to the XUsbPsu instance. None.
References XUsbPsu_Ep::Direction, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Ep::UsbEpNum, XUsbPsu_StopTransfer.
Referenced by XUsbPsu_ResetIntr.
void XUsbPsu_ClearStallAllEp(struct XUsbPsu *InstancePtr)
Clears stall on all stalled endpoints.
InstancePtr Pointer to the XUsbPsu instance. None.
References XUsbPsu_Ep::Direction, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Ep::UsbEpNum, XUsbPsu_EpClearStall.
Referenced by XUsbPsu_ResetIntr.
s32 XUsbPsu_RecvSetup(struct XUsbPsu *InstancePtr)
Initiates DMA on control endpoint 0 to receive setup packet.
InstancePtr Pointer to the XUsbPsu instance. XST_SUCCESS else XST_FAILURE.
References XUsbPsu_Trb::BufferPtrHigh, XUsbPsu_Trb::BufferPtrLow, XUsbPsu::ConfigPtr, XUsbPsu_Trb::Ctrl, XUsbPsu_Ep::Direction, XUsbPsu::Ep0State, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Config::IsCacheCoherent, XUsbPsu_EpParams::Param0, XUsbPsu_EpParams::Param1, XUsbPsu_Ep::ResourceIndex, XUsbPsu_Trb::Size, XUsbPsu_Ep::UsbEpNum, XUSBPSU_EP_DIR_OUT, XUsbPsu_EpGetTransferIndex, XUsbPsu_GetEpParams, XUsbPsu_SendEpCmd.
Referenced by XUsbPsu_ConnDoneIntr, XUsbPsu_Ep0StallRestart, XUsbPsu_Ep0StatusDone.
void XUsbPsu_Ep0XferComplete(struct XUsbPsu *InstancePtr, const struct XUsbPsu_Event_Epevt *Event)
Handles transfer complete event of control endpoints EP0 OUT and EP0 IN.
InstancePtr Pointer to the XUsbPsu instance. Event Pointer to the Endpoint event occurred in core. None.
References XUsbPsu::AppData, SetupPacket::bRequestType, XUsbPsu::Chapter9, XUsbPsu::ConfigPtr, XUsbPsu::ControlDir, XUsbPsu::Ep0State, XUsbPsu_Event_Epevt::Epnumber, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Config::IsCacheCoherent, XUsbPsu::IsThreeStage, XUsbPsu_Ep::ResourceIndex, SetupPacket::wLength, XUsbPsu_Ep0DataDone, XUsbPsu_Ep0StatusDone, XUSBPSU_EP_DIR_OUT, XUSBPSU_USB_DIR_IN.
Referenced by XUsbPsu_Ep0Intr.
void XUsbPsu_Ep0XferNotReady(struct XUsbPsu *InstancePtr, const struct XUsbPsu_Event_Epevt *Event)
Handles transfer not ready event of control endpoints EP0 OUT and EP0 IN.
InstancePtr Pointer to the XUsbPsu instance. Event Pointer to the Endpoint event occurred in core. None.
References XUsbPsu::ControlDir, XUsbPsu_Event_Epevt::Epnumber, XUsbPsu::eps, XUsbPsu_Event_Epevt::Status, XUsbPsu_Ep0_EndControlData, XUsbPsu_Ep0StallRestart, XUsbPsu_Ep0StartStatus.
Referenced by XUsbPsu_Ep0Intr.
s32 XUsbPsu_Ep0Send(struct XUsbPsu *InstancePtr, u8 *BufferPtr, u32 BufferLen)
Initiates DMA to send data on control endpoint EP0 IN to host.
InstancePtr Pointer to the XUsbPsu instance. BufferPtr Pointer to data. BufferLen Length of data buffer. XST_SUCCESS else XST_FAILURE
References XUsbPsu_Ep::BufferPtr, XUsbPsu_Trb::BufferPtrHigh, XUsbPsu_Trb::BufferPtrLow, XUsbPsu_Ep::BytesTxed, XUsbPsu::ConfigPtr, XUsbPsu_Trb::Ctrl, XUsbPsu_Ep::Direction, XUsbPsu::Ep0State, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Config::IsCacheCoherent, XUsbPsu_EpParams::Param0, XUsbPsu_EpParams::Param1, XUsbPsu_Ep::RequestedBytes, XUsbPsu_Ep::ResourceIndex, XUsbPsu_Trb::Size, XUsbPsu_Ep::UsbEpNum, XUSBPSU_EP_DIR_IN, XUsbPsu_EpGetTransferIndex, XUsbPsu_GetEpParams, XUsbPsu_SendEpCmd.
Referenced by XUsbPsu_EpBufferSend.
s32 XUsbPsu_Ep0Recv(struct XUsbPsu *InstancePtr, u8 *BufferPtr, u32 Length)
Initiates DMA to receive data on control endpoint EP0 OUT from host.
InstancePtr Pointer to the XUsbPsu instance. BufferPtr Pointer to data. Length Length of data to be received. XST_SUCCESS else XST_FAILURE
References XUsbPsu_Ep::BufferPtr, XUsbPsu_Trb::BufferPtrHigh, XUsbPsu_Trb::BufferPtrLow, XUsbPsu_Ep::BytesTxed, XUsbPsu::ConfigPtr, XUsbPsu_Trb::Ctrl, XUsbPsu_Ep::Direction, XUsbPsu::Ep0State, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Config::IsCacheCoherent, XUsbPsu_Ep::MaxSize, XUsbPsu_EpParams::Param0, XUsbPsu_EpParams::Param1, XUsbPsu_Ep::RequestedBytes, XUsbPsu_Ep::ResourceIndex, XUsbPsu_Trb::Size, XUsbPsu_Ep::UnalignedTx, XUsbPsu_Ep::UsbEpNum, XUSBPSU_EP_DIR_OUT, XUsbPsu_EpGetTransferIndex, XUsbPsu_GetEpParams, XUsbPsu_SendEpCmd.
Referenced by XUsbPsu_EpBufferRecv.
void XUsbPsu_EpTransferDeactive(struct XUsbPsu *InstancePtr, u8 UsbEpNum, u8 Dir)
Resets and deactivates transfer endpoint.
InstancePtr Pointer to the XUsbPsu instance. UsbEpNum USB endpoint number. Dir Direction of endpoint XUSBPSU_EP_DIR_IN/XUSBPSU_EP_DIR_OUT. None.
References XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Ep::MaxSize, XUsbPsu_Ep::PhyEpNum, XUsbPsu_Ep::TrbDequeue, XUsbPsu_Ep::TrbEnqueue, XUsbPsu_Ep::Type, XUSBPSU_EP_DIR_IN, XUSBPSU_EP_DIR_OUT.
Referenced by XUsbPsu_Idle.
void XUsbPsu_SaveEndpointState(struct XUsbPsu *InstancePtr, struct XUsbPsu_Ep *Ept)
Queries endpoint state and saves it in EpSavedState.
InstancePtr Pointer to the XUsbPsu instance. Ept Pointer to the XUsbPsu pointer structure. None.
References XUsbPsu_Ep::Direction, XUsbPsu_Ep::EpSavedState, XUsbPsu_Ep::PhyEpNum, XUsbPsu_Ep::UsbEpNum, XUsbPsu_GetEpParams, XUsbPsu_SendEpCmd.
void XUsbPsu_EpXferComplete(struct XUsbPsu *InstancePtr, const struct XUsbPsu_Event_Epevt *Event)
Checks the data phase and calls user endpoint handler.
InstancePtr Pointer to the XUsbPsu instance. Event Pointer to the endpoint event occurred in core. None.
References XUsbPsu::AppData, XUsbPsu_Ep::BufferPtr, XUsbPsu_Ep::BytesTxed, XUsbPsu::ConfigPtr, XUsbPsu_Ep::Direction, XUsbPsu_Event_Epevt::Endpoint_Event, XUsbPsu_Event_Epevt::Epnumber, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Ep::Handler, XUsbPsu_Config::IsCacheCoherent, XUsbPsu_Ep::MaxSize, XUsbPsu_Ep::RequestedBytes, XUsbPsu_Ep::ResourceIndex, XUsbPsu_Ep::TrbDequeue, XUsbPsu_Ep::UnalignedTx, XUSBPSU_EP_DIR_IN, XUSBPSU_EP_DIR_OUT.
Referenced by XUsbPsu_EpEvent.
void XUsbPsu_EpXferNotReady(struct XUsbPsu *InstancePtr, const struct XUsbPsu_Event_Epevt *Event)
For Isochronous transfer, gets the microframe time and calls respective endpoint handler.
InstancePtr Pointer to the XUsbPsu instance. Event Pointer to the Endpoint event occurred in core. None.
References XUsbPsu::AppData, XUsbPsu_Ep::CurUf, XUsbPsu_Event_Epevt::Epnumber, XUsbPsu::eps, XUsbPsu_Ep::Handler, XUsbPsu_Ep::Interval, XUsbPsu_Event_Epevt::Parameters, XUsbPsu_Ep::Type, XUSBPSU_ENDPOINT_XFER_ISOC.
Referenced by XUsbPsu_EpEvent.
void XUsbPsu_EpEvent(struct XUsbPsu *InstancePtr, const struct XUsbPsu_Event_Epevt *Event)
Endpoint event handler.
InstancePtr Pointer to the XUsbPsu instance. Event Endpoint Event occurred in the core. None.
References XUsbPsu_Event_Epevt::Endpoint_Event, XUsbPsu_Event_Epevt::Epnumber, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Ep0Intr, XUsbPsu_EpXferComplete, XUsbPsu_EpXferNotReady.
Referenced by XUsbPsu_EventHandler.
void XUsbPsu_DeviceEvent(struct XUsbPsu *InstancePtr, const struct XUsbPsu_Event_Devt *Event)
Device event handler for device specific events.
InstancePtr Pointer to the XUsbPsu instance. Event Device Event occurred in core. None.
References XUsbPsu_Event_Devt::Event_Info, XUsbPsu::HasHibernation, XUsbPsu_Event_Devt::Type, XUsbPsu_ConnDoneIntr, XUsbPsu_DisconnectIntr, XUsbPsu_LinkStsChangeIntr, XUsbPsu_ResetIntr.
Referenced by XUsbPsu_EventHandler.
void XUsbPsu_EventBufferHandler(struct XUsbPsu *InstancePtr)
Processes events in an event buffer.
InstancePtr Pointer to the XUsbPsu instance. None.
References XUsbPsu_EvtBuffer::BuffAddr, XUsbPsu::ConfigPtr, XUsbPsu_EvtBuffer::Count, XUsbPsu::Evt, XUsbPsu_EvtBuffer::Flags, XUsbPsu_Config::IsCacheCoherent, XUsbPsu::IsHibernated, XUsbPsu_EvtBuffer::Offset, XUsbPsu_Event::Raw, XUsbPsu_EventHandler.
Referenced by XUsbPsu_IntrHandler.
void XUsbPsu_DisconnectIntr(struct XUsbPsu *InstancePtr)
Disconnects interrupt handler.
InstancePtr Pointer to the XUsbPsu instance. None.
References XUsbPsu::AppData, XUsbPsu::DisconnectIntrHandler, XUsbPsu::HasHibernation, XUsbPsu::IsConfigDone, Usb_DevData::Speed, XUSBPSU_SPEED_UNKNOWN.
Referenced by XUsbPsu_DeviceEvent.
void XUsbPsu_ResetIntr(struct XUsbPsu *InstancePtr)
Resets interrupt handler.
InstancePtr Pointer to the XUsbPsu instance. None.
References XUsbPsu::AppData, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu::IsConfigDone, XUsbPsu::NumInEps, XUsbPsu::NumOutEps, XUsbPsu::ResetIntrHandler, Usb_DevData::State, XUsbPsu::TestMode, XUsbPsu_ClearStallAllEp, XUSBPSU_STATE_DEFAULT, XUsbPsu_StopActiveTransfers.
Referenced by XUsbPsu_DeviceEvent.
void XUsbPsu_Ep0Intr(struct XUsbPsu *InstancePtr, const struct XUsbPsu_Event_Epevt *Event)
Handle interrupts of control endpoints EP0 OUT and EP0 IN.
InstancePtr Pointer to the XUsbPsu instance. Event Pointer to the Endpoint event occurred in core. None.
References XUsbPsu_Event_Epevt::Endpoint_Event, XUsbPsu_Ep0XferComplete, XUsbPsu_Ep0XferNotReady.
Referenced by XUsbPsu_EpEvent.
void XUsbPsu_ConnDoneIntr(struct XUsbPsu *InstancePtr)
Interrupt handler which indicates that the connection is completed.
InstancePtr Pointer to the XUsbPsu instance. None.
References XUsbPsu::AppData, XUsbPsu::HasHibernation, Usb_DevData::Speed, XUsbPsu_EnableControlEp, XUsbPsu_RecvSetup, XUSBPSU_SPEED_FULL, XUSBPSU_SPEED_HIGH, XUSBPSU_SPEED_LOW, XUSBPSU_SPEED_SUPER.
Referenced by XUsbPsu_DeviceEvent.
void XUsbPsu_LinkStsChangeIntr(struct XUsbPsu *InstancePtr, u32 EvtInfo)
Link status change interrupt handler.
InstancePtr Pointer to the XUsbPsu instance. EvtInfo Event information. None.
References XUsbPsu::LinkState.
Referenced by XUsbPsu_DeviceEvent.
void XUsbPsu_EventHandler(struct XUsbPsu *InstancePtr, const union XUsbPsu_Event *Event)
Processes an event entry in the event Buffer.
InstancePtr Pointer to the XUsbPsu instance. Event Event entry. None.
References XUsbPsu_Event::Devt, XUsbPsu_Event::Epevt, XUsbPsu_Event_Type::Is_DevEvt, XUsbPsu_Event_Type::Type, XUsbPsu_Event::Type, XUsbPsu_DeviceEvent, XUsbPsu_EpEvent.
Referenced by XUsbPsu_EventBufferHandler.
XUSBPSU_H
by using protection macros
XUSBPSU_EP_DIR_IN
Direction IN.
Referenced by XUsbPsu_EnableControlEp, XUsbPsu_Ep0DataDone, XUsbPsu_Ep0Send, XUsbPsu_EpBufferSend, XUsbPsu_EpClearStall, XUsbPsu_EpDisable, XUsbPsu_EpEnable, XUsbPsu_EpGetTransferIndex, XUsbPsu_EpSetStall, XUsbPsu_EpTransferDeactive, XUsbPsu_EpXferComplete, XUsbPsu_Idle, XUsbPsu_IsEpStalled, XUsbPsu_SendEpCmd, XUsbPsu_SetEpHandler, XUsbPsu_StopTransfer.
XUSBPSU_EP_DIR_OUT
Direction OUT.
Referenced by XUsbPsu_EnableControlEp, XUsbPsu_Ep0DataDone, XUsbPsu_Ep0Recv, XUsbPsu_Ep0StallRestart, XUsbPsu_Ep0XferComplete, XUsbPsu_EpBufferRecv, XUsbPsu_EpClearStall, XUsbPsu_EpDisable, XUsbPsu_EpEnable, XUsbPsu_EpGetTransferIndex, XUsbPsu_EpSetStall, XUsbPsu_EpTransferDeactive, XUsbPsu_EpXferComplete, XUsbPsu_Idle, XUsbPsu_IsEpStalled, XUsbPsu_RecvSetup, XUsbPsu_SendEpCmd, XUsbPsu_SetEpConfig, XUsbPsu_SetEpHandler, XUsbPsu_StartEpConfig, XUsbPsu_StopTransfer.
XUSBPSU_USB_DIR_OUT
Direction to device.
XUSBPSU_USB_DIR_IN
Direction to host.
Referenced by XUsbPsu_Ep0XferComplete.
XUSBPSU_ENDPOINT_XFERTYPE_MASK
Transfer type mask.
XUSBPSU_ENDPOINT_XFER_CONTROL
Control EP.
Referenced by XUsbPsu_EnableControlEp.
XUSBPSU_ENDPOINT_XFER_ISOC
ISO EP.
Referenced by XUsbPsu_EpBufferRecv, XUsbPsu_EpBufferSend, XUsbPsu_EpXferNotReady, XUsbPsu_SetEpConfig.
XUSBPSU_ENDPOINT_XFER_BULK
Bulk EP.
Referenced by XUsbPsu_EpBufferRecv, XUsbPsu_EpBufferSend.
XUSBPSU_ENDPOINT_XFER_INT
Interrupt EP.
Referenced by XUsbPsu_EpBufferRecv, XUsbPsu_EpBufferSend.
XUSBPSU_ENDPOINT_MAX_ADJUSTABLE
Max EP.
XUSBPSU_TEST_J
Test Mode J.
Referenced by XUsbPsu_SetTestMode.
XUSBPSU_TEST_K
Test Mode K.
Referenced by XUsbPsu_SetTestMode.
XUSBPSU_TEST_SE0_NAK
Test Mode SE0_NAK.
Referenced by XUsbPsu_SetTestMode.
XUSBPSU_TEST_PACKET
Test Mode TEST PACKET.
Referenced by XUsbPsu_SetTestMode.
XUSBPSU_TEST_FORCE_ENABLE
Test Mode FORCE ENABLE.
Referenced by XUsbPsu_SetTestMode.
XUSBPSU_STATE_ATTACHED
Device State Attach.
XUSBPSU_STATE_POWERED
Device State Power.
XUSBPSU_STATE_DEFAULT
Device State Default.
Referenced by XUsbPsu_ResetIntr, XUsbPsu_SetDeviceAddress.
XUSBPSU_STATE_ADDRESS
Device State Address.
Referenced by XUsbPsu_SetDeviceAddress.
XUSBPSU_STATE_CONFIGURED
Device State Configure.
Referenced by XUsbPsu_SetDeviceAddress.
XUSBPSU_STATE_SUSPENDED
Device State Suspend.
XUSBPSU_SPEED_UNKNOWN
Device Speed Unknown.
Referenced by XUsbPsu_DisconnectIntr.
XUSBPSU_SPEED_LOW
Device Speed Low.
Referenced by XUsbPsu_ConnDoneIntr.
XUSBPSU_SPEED_FULL
Device Speed Full.
Referenced by XUsbPsu_ConnDoneIntr.
XUSBPSU_SPEED_HIGH
Device Speed High.
Referenced by XUsbPsu_ConnDoneIntr.
XUSBPSU_SPEED_SUPER
Device Speed Speed.
Referenced by XUsbPsu_ConnDoneIntr, XUsbPsu_IsSuperSpeed, XUsbPsu_SetEpConfig.
XUSBPSU_DEVTEN_VNDRDEVTSTRCVEDEN
Vendor Device Test LMP Received Event.
XUSBPSU_DEVTEN_EVNTOVERFLOWEN
Reserved.
Referenced by main.
XUSBPSU_DEVTEN_CMDCMPLTEN
Reserved.
XUSBPSU_DEVTEN_ERRTICERREN
Erratic Error Event Enable.
XUSBPSU_DEVTEN_SOFEN
Start of (u)frame.
XUSBPSU_DEVTEN_EOPFEN
U3/L2-L1 Suspend Event Enable.
XUSBPSU_DEVTEN_HIBERNATIONREQEVTEN
Hibernation Request Event.
Referenced by main.
XUSBPSU_DEVTEN_WKUPEVTEN
Resume/Remote Wakeup Detected Event Enable.
Referenced by main.
XUSBPSU_DEVTEN_ULSTCNGEN
Link State Change Event Enable.
Referenced by main.
XUSBPSU_DEVTEN_CONNECTDONEEN
Connection Done Enable.
Referenced by main.
XUSBPSU_DEVTEN_USBRSTEN
USB Reset Enable.
Referenced by main.
XUSBPSU_DEVTEN_DISCONNEVTEN
Disconnect Detected Event Enable.
Referenced by main.