xusbpsu_endpoint.c
u32 XUsbPsu_EpGetTransferIndex(struct XUsbPsu *InstancePtr, u8 UsbEpNum, u8 Dir)
Returns transfer index assigned by Core for an endpoint transfer.
InstancePtr Pointer to the XUsbPsu instance. UsbEpNum USB endpoint number. Dir Direction of endpoint XUSBPSU_EP_DIR_IN/XUSBPSU_EP_DIR_OUT Transfer Resource Index.
References XUSBPSU_EP_DIR_IN, XUSBPSU_EP_DIR_OUT.
Referenced by XUsbPsu_Ep0Recv, XUsbPsu_Ep0Send, XUsbPsu_Ep0StartStatus, XUsbPsu_EpBufferRecv, XUsbPsu_EpBufferSend, XUsbPsu_RecvSetup.
s32 XUsbPsu_StartEpConfig(struct XUsbPsu *InstancePtr, u32 UsbEpNum, u8 Dir)
Sends start new configuration command to the endpoint.
InstancePtr Pointer to the XUsbPsu instance. UsbEpNum USB endpoint number. Dir Direction of endpoint XUSBPSU_EP_DIR_IN/ XUSBPSU_EP_DIR_OUT. XST_SUCCESS else XST_FAILURE. As per data book this command should be issued by software under these conditions: After power-on-reset with XferRscIdx=0 before starting to configure Physical Endpoints 0 and 1.With XferRscIdx=2 before starting to configure Physical Endpoints > 1This command should always be issued to Endpoint 0 (DEPCMD0).
References XUsbPsu::IsConfigDone, XUSBPSU_EP_DIR_OUT, XUsbPsu_GetEpParams, XUsbPsu_SendEpCmd.
Referenced by XUsbPsu_EpEnable.
s32 XUsbPsu_SetEpConfig(struct XUsbPsu *InstancePtr, u8 UsbEpNum, u8 Dir, u16 Size, u8 Type, u8 Restore)
Sends set endpoint configuration command to the endpoint.
InstancePtr Pointer to the XUsbPsu instance. UsbEpNum USB endpoint number. Dir Direction of endpoint -XUSBPSU_EP_DIR_IN/XUSBPSU_EP_DIR_OUT. Size Size of Endpoint size. Type Endpoint type Control/Bulk/Interrupt/Isoc. Restore Typically false, true if saved state has to be restored. XST_SUCCESS else XST_FAILURE.
References XUsbPsu::AppData, XUsbPsu::eps, XUsbPsu_Ep::EpSavedState, XUsbPsu_Ep::Interval, XUsbPsu_EpParams::Param0, XUsbPsu_EpParams::Param1, XUsbPsu_EpParams::Param2, Usb_DevData::Speed, XUsbPsu_Ep::Type, XUSBPSU_ENDPOINT_XFER_ISOC, XUSBPSU_EP_DIR_OUT, XUsbPsu_GetEpParams, XUsbPsu_SendEpCmd, XUSBPSU_SPEED_SUPER.
Referenced by XUsbPsu_EpEnable.
s32 XUsbPsu_SetXferResource(struct XUsbPsu *InstancePtr, u8 UsbEpNum, u8 Dir)
Sends set transfer resource command to the endpoint.
InstancePtr Pointer to the XUsbPsu instance. UsbEpNum USB endpoint number. Dir Direction of endpoint - XUSBPSU_EP_DIR_IN/XUSBPSU_EP_DIR_OUT XST_SUCCESS else XST_FAILURE.
References XUsbPsu_EpParams::Param0, XUsbPsu_GetEpParams, XUsbPsu_SendEpCmd.
Referenced by XUsbPsu_EpEnable.
void XUsbPsu_StopActiveTransfers(struct XUsbPsu *InstancePtr)
Stops any active transfer.
InstancePtr Pointer to the XUsbPsu instance. None.
References XUsbPsu_Ep::Direction, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Ep::UsbEpNum, XUsbPsu_StopTransfer.
Referenced by XUsbPsu_ResetIntr.
void XUsbPsu_ClearStallAllEp(struct XUsbPsu *InstancePtr)
Clears stall on all stalled endpoints.
InstancePtr Pointer to the XUsbPsu instance. None.
References XUsbPsu_Ep::Direction, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Ep::UsbEpNum, XUsbPsu_EpClearStall.
Referenced by XUsbPsu_ResetIntr.