xusbpsu_intr.c
void XUsbPsu_DisconnectIntr(struct XUsbPsu *InstancePtr)
Disconnects interrupt handler.
InstancePtr Pointer to the XUsbPsu instance. None.
References XUsbPsu::AppData, XUsbPsu::DisconnectIntrHandler, XUsbPsu::HasHibernation, XUsbPsu::IsConfigDone, Usb_DevData::Speed, XUSBPSU_SPEED_UNKNOWN.
Referenced by XUsbPsu_DeviceEvent.
void XUsbPsu_ResetIntr(struct XUsbPsu *InstancePtr)
Resets interrupt handler.
InstancePtr Pointer to the XUsbPsu instance. None.
References XUsbPsu::AppData, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu::IsConfigDone, XUsbPsu::NumInEps, XUsbPsu::NumOutEps, XUsbPsu::ResetIntrHandler, Usb_DevData::State, XUsbPsu::TestMode, XUsbPsu_ClearStallAllEp, XUSBPSU_STATE_DEFAULT, XUsbPsu_StopActiveTransfers.
Referenced by XUsbPsu_DeviceEvent.
void XUsbPsu_Ep0Intr(struct XUsbPsu *InstancePtr, const struct XUsbPsu_Event_Epevt *Event)
Handle interrupts of control endpoints EP0 OUT and EP0 IN.
InstancePtr Pointer to the XUsbPsu instance. Event Pointer to the Endpoint event occurred in core. None.
References XUsbPsu_Event_Epevt::Endpoint_Event, XUsbPsu_Ep0XferComplete, XUsbPsu_Ep0XferNotReady.
Referenced by XUsbPsu_EpEvent.
void XUsbPsu_ConnDoneIntr(struct XUsbPsu *InstancePtr)
Interrupt handler which indicates that the connection is completed.
InstancePtr Pointer to the XUsbPsu instance. None.
References XUsbPsu::AppData, XUsbPsu::HasHibernation, Usb_DevData::Speed, XUsbPsu_EnableControlEp, XUsbPsu_RecvSetup, XUSBPSU_SPEED_FULL, XUSBPSU_SPEED_HIGH, XUSBPSU_SPEED_LOW, XUSBPSU_SPEED_SUPER.
Referenced by XUsbPsu_DeviceEvent.
void XUsbPsu_LinkStsChangeIntr(struct XUsbPsu *InstancePtr, u32 EvtInfo)
Link status change interrupt handler.
InstancePtr Pointer to the XUsbPsu instance. EvtInfo Event information. None.
References XUsbPsu::LinkState.
Referenced by XUsbPsu_DeviceEvent.
void XUsbPsu_EventHandler(struct XUsbPsu *InstancePtr, const union XUsbPsu_Event *Event)
Processes an event entry in the event Buffer.
InstancePtr Pointer to the XUsbPsu instance. Event Event entry. None.
References XUsbPsu_Event::Devt, XUsbPsu_Event::Epevt, XUsbPsu_Event_Type::Is_DevEvt, XUsbPsu_Event_Type::Type, XUsbPsu_Event::Type, XUsbPsu_DeviceEvent, XUsbPsu_EpEvent.
Referenced by XUsbPsu_EventBufferHandler.
void XUsbPsu_EnableIntr(struct XUsbPsu *InstancePtr, u32 Mask)
Enables an interrupt in event enable RegValister.
InstancePtr Pointer to the XUsbPsu instance to be worked on. Mask OR of any interrupt enable Masks: XUSBPSU_DEVTEN_VNDRDEVTSTRCVEDENXUSBPSU_DEVTEN_EVNTOVERFLOWENXUSBPSU_DEVTEN_CMDCMPLTENXUSBPSU_DEVTEN_ERRTICERRENXUSBPSU_DEVTEN_SOFENXUSBPSU_DEVTEN_EOPFENXUSBPSU_DEVTEN_HIBERNATIONREQEVTENXUSBPSU_DEVTEN_WKUPEVTENXUSBPSU_DEVTEN_ULSTCNGENXUSBPSU_DEVTEN_CONNECTDONEENXUSBPSU_DEVTEN_USBRSTENXUSBPSU_DEVTEN_DISCONNEVTEN None
Referenced by main, UsbEnableEvent.
void XUsbPsu_DisableIntr(struct XUsbPsu *InstancePtr, u32 Mask)
Disables an interrupt in event enable RegValister.
InstancePtr Pointer to the XUsbPsu instance to be worked on. Mask OR of Interrupt Enable Masks XUSBPSU_DEVTEN_VNDRDEVTSTRCVEDENXUSBPSU_DEVTEN_EVNTOVERFLOWENXUSBPSU_DEVTEN_CMDCMPLTENXUSBPSU_DEVTEN_ERRTICERRENXUSBPSU_DEVTEN_SOFENXUSBPSU_DEVTEN_EOPFENXUSBPSU_DEVTEN_HIBERNATIONREQEVTENXUSBPSU_DEVTEN_WKUPEVTENXUSBPSU_DEVTEN_ULSTCNGENXUSBPSU_DEVTEN_CONNECTDONEENXUSBPSU_DEVTEN_USBRSTENXUSBPSU_DEVTEN_DISCONNEVTEN None
void XUsbPsu_IntrHandler(void *XUsbPsuInstancePtr)
Main interrupt handler.
XUsbPsuInstancePtr Void pointer to the XUsbPsu instance. None.
References XUsbPsu_EvtBuffer::Count, XUsbPsu::Evt, XUsbPsu_EvtBuffer::Flags, XUsbPsu_EventBufferHandler.
Referenced by main, UsbPollHandler.