xusbpsu_event.c
void XUsbPsu_EpEvent(struct XUsbPsu *InstancePtr, const struct XUsbPsu_Event_Epevt *Event)
Endpoint event handler.
InstancePtr Pointer to the XUsbPsu instance. Event Endpoint Event occurred in the core. None.
References XUsbPsu_Event_Epevt::Endpoint_Event, XUsbPsu_Event_Epevt::Epnumber, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Ep0Intr, XUsbPsu_EpXferComplete, XUsbPsu_EpXferNotReady.
Referenced by XUsbPsu_EventHandler.
void XUsbPsu_DeviceEvent(struct XUsbPsu *InstancePtr, const struct XUsbPsu_Event_Devt *Event)
Device event handler for device specific events.
InstancePtr Pointer to the XUsbPsu instance. Event Device Event occurred in core. None.
References XUsbPsu_Event_Devt::Event_Info, XUsbPsu::HasHibernation, XUsbPsu_Event_Devt::Type, XUsbPsu_ConnDoneIntr, XUsbPsu_DisconnectIntr, XUsbPsu_LinkStsChangeIntr, XUsbPsu_ResetIntr.
Referenced by XUsbPsu_EventHandler.
void XUsbPsu_EventBufferHandler(struct XUsbPsu *InstancePtr)
Processes events in an event buffer.
InstancePtr Pointer to the XUsbPsu instance. None.
References XUsbPsu_EvtBuffer::BuffAddr, XUsbPsu::ConfigPtr, XUsbPsu_EvtBuffer::Count, XUsbPsu::Evt, XUsbPsu_EvtBuffer::Flags, XUsbPsu_Config::IsCacheCoherent, XUsbPsu::IsHibernated, XUsbPsu_EvtBuffer::Offset, XUsbPsu_Event::Raw, XUsbPsu_EventHandler.
Referenced by XUsbPsu_IntrHandler.