xusbpsu_ephandler.c
void XUsbPsu_StopTransfer(struct XUsbPsu *InstancePtr, u8 UsbEpNum, u8 Dir, u8 Force)
Stops transfer on Endpoint.
InstancePtr Pointer to the XUsbPsu instance. UsbEpNum USB endpoint number. Dir Direction of endpoint XUSBPSU_EP_DIR_IN/XUSBPSU_EP_DIR_OUT. Force Flag to stop/pause transfer. None.
References XUsbPsu_Ep::Direction, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Ep::ResourceIndex, XUsbPsu_Ep::UsbEpNum, XUSBPSU_EP_DIR_IN, XUSBPSU_EP_DIR_OUT, XUsbPsu_GetEpParams, XUsbPsu_SendEpCmd, XUsbPsu_Sleep.
Referenced by XUsbPsu_Idle, XUsbPsu_StopActiveTransfers.
void XUsbPsu_EpTransferDeactive(struct XUsbPsu *InstancePtr, u8 UsbEpNum, u8 Dir)
Resets and deactivates transfer endpoint.
InstancePtr Pointer to the XUsbPsu instance. UsbEpNum USB endpoint number. Dir Direction of endpoint XUSBPSU_EP_DIR_IN/XUSBPSU_EP_DIR_OUT. None.
References XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Ep::MaxSize, XUsbPsu_Ep::PhyEpNum, XUsbPsu_Ep::TrbDequeue, XUsbPsu_Ep::TrbEnqueue, XUsbPsu_Ep::Type, XUSBPSU_EP_DIR_IN, XUSBPSU_EP_DIR_OUT.
Referenced by XUsbPsu_Idle.
void XUsbPsu_SaveEndpointState(struct XUsbPsu *InstancePtr, struct XUsbPsu_Ep *Ept)
Queries endpoint state and saves it in EpSavedState.
InstancePtr Pointer to the XUsbPsu instance. Ept Pointer to the XUsbPsu pointer structure. None.
References XUsbPsu_Ep::Direction, XUsbPsu_Ep::EpSavedState, XUsbPsu_Ep::PhyEpNum, XUsbPsu_Ep::UsbEpNum, XUsbPsu_GetEpParams, XUsbPsu_SendEpCmd.
void XUsbPsu_ClearStalls(struct XUsbPsu *InstancePtr)
Clears stall on all endpoints.
InstancePtr Pointer to the XUsbPsu instance. None.
References XUsbPsu_Ep::Direction, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Ep::UsbEpNum, XUsbPsu_GetEpParams, XUsbPsu_SendEpCmd.
s32 XUsbPsu_EpBufferSend(struct XUsbPsu *InstancePtr, u8 UsbEp, u8 *BufferPtr, u32 BufferLen)
Initiates DMA to send data on endpoint to the host.
InstancePtr Pointer to the XUsbPsu instance. UsbEp USB endpoint number. BufferPtr Pointer to data. This data buffer is cache-aligned. BufferLen Length of data buffer. XST_SUCCESS else XST_FAILURE This function is expected to initiates DMA to send data on endpoint towards host. This data buffer should be aligned.
References XUsbPsu_Ep::BufferPtr, XUsbPsu_Trb::BufferPtrHigh, XUsbPsu_Trb::BufferPtrLow, XUsbPsu_Ep::BytesTxed, XUsbPsu::ConfigPtr, XUsbPsu_Trb::Ctrl, XUsbPsu_Ep::CurUf, XUsbPsu_Ep::Direction, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Config::IsCacheCoherent, XUsbPsu_EpParams::Param0, XUsbPsu_EpParams::Param1, XUsbPsu_EpParams::Param2, XUsbPsu_Ep::PhyEpNum, XUsbPsu_Ep::RequestedBytes, XUsbPsu_Ep::ResourceIndex, XUsbPsu_Trb::Size, XUsbPsu_Ep::TrbEnqueue, XUsbPsu_Ep::Type, XUsbPsu_Ep::UsbEpNum, XUSBPSU_ENDPOINT_XFER_BULK, XUSBPSU_ENDPOINT_XFER_INT, XUSBPSU_ENDPOINT_XFER_ISOC, XUsbPsu_Ep0Send, XUSBPSU_EP_DIR_IN, XUsbPsu_EpGetTransferIndex, XUsbPsu_SendEpCmd.
s32 XUsbPsu_EpBufferRecv(struct XUsbPsu *InstancePtr, u8 UsbEp, u8 *BufferPtr, u32 Length)
Initiates DMA to receive data on endpoint from host.
InstancePtr Pointer to the XUsbPsu instance. UsbEp USB endpoint number. BufferPtr Pointer to data. This data buffer is cache-aligned. Length Length of data to be received. XST_SUCCESS else XST_FAILURE This function is expected to initiates DMA to receive data on the endpoint from the host. This data buffer should be aligned.
References XUsbPsu_Ep::BufferPtr, XUsbPsu_Trb::BufferPtrHigh, XUsbPsu_Trb::BufferPtrLow, XUsbPsu_Ep::BytesTxed, XUsbPsu::ConfigPtr, XUsbPsu_Trb::Ctrl, XUsbPsu_Ep::CurUf, XUsbPsu_Ep::Direction, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Config::IsCacheCoherent, XUsbPsu_Ep::MaxSize, XUsbPsu_EpParams::Param0, XUsbPsu_EpParams::Param1, XUsbPsu_EpParams::Param2, XUsbPsu_Ep::RequestedBytes, XUsbPsu_Ep::ResourceIndex, XUsbPsu_Trb::Size, XUsbPsu_Ep::TrbEnqueue, XUsbPsu_Ep::Type, XUsbPsu_Ep::UnalignedTx, XUsbPsu_Ep::UsbEpNum, XUSBPSU_ENDPOINT_XFER_BULK, XUSBPSU_ENDPOINT_XFER_INT, XUSBPSU_ENDPOINT_XFER_ISOC, XUsbPsu_Ep0Recv, XUSBPSU_EP_DIR_OUT, XUsbPsu_EpGetTransferIndex, XUsbPsu_SendEpCmd.
void XUsbPsu_EpSetStall(struct XUsbPsu *InstancePtr, u8 Epnum, u8 Dir)
Stalls an endpoint.
InstancePtr Pointer to the XUsbPsu instance. Epnum USB endpoint number. Dir Direction None.
References XUsbPsu_Ep::Direction, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Ep::UsbEpNum, XUSBPSU_EP_DIR_IN, XUSBPSU_EP_DIR_OUT, XUsbPsu_GetEpParams, XUsbPsu_SendEpCmd.
Referenced by XUsbPsu_Ep0StallRestart.
void XUsbPsu_EpClearStall(struct XUsbPsu *InstancePtr, u8 Epnum, u8 Dir)
Clears stall on an endpoint.
InstancePtr Pointer to the XUsbPsu instance. Epnum USB endpoint number. Dir Direction. None.
References XUsbPsu_Ep::Direction, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Ep::UsbEpNum, XUSBPSU_EP_DIR_IN, XUSBPSU_EP_DIR_OUT, XUsbPsu_GetEpParams, XUsbPsu_SendEpCmd.
Referenced by XUsbPsu_ClearStallAllEp, XUsbPsu_EpDisable.
void XUsbPsu_SetEpHandler(struct XUsbPsu *InstancePtr, u8 Epnum, u8 Dir, void(*Handler)(void *, u32, u32))
Sets an user handler to be called after data is sent/received by an endpoint.
InstancePtr Pointer to the XUsbPsu instance. Epnum USB endpoint number. Dir Direction of endpoint XUSBPSU_EP_DIR_IN/XUSBPSU_EP_DIR_OUT. Handler User handler to be called. None.
References XUsbPsu::eps, XUsbPsu_Ep::Handler, XUsbPsu_Ep::PhyEpNum, XUSBPSU_EP_DIR_IN, XUSBPSU_EP_DIR_OUT.
s32 XUsbPsu_IsEpStalled(struct XUsbPsu *InstancePtr, u8 Epnum, u8 Dir)
Returns status of endpoint whether it is stalled or not.
InstancePtr Pointer to the XUsbPsu instance. Epnum USB endpoint number. Dir Direction of endpoint XUSBPSU_EP_DIR_IN/XUSBPSU_EP_DIR_OUT. 1 - if stalled 0 - if not stalled
References XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Ep::PhyEpNum, XUSBPSU_EP_DIR_IN, XUSBPSU_EP_DIR_OUT.
void XUsbPsu_EpXferComplete(struct XUsbPsu *InstancePtr, const struct XUsbPsu_Event_Epevt *Event)
Checks the data phase and calls user endpoint handler.
InstancePtr Pointer to the XUsbPsu instance. Event Pointer to the endpoint event occurred in core. None.
References XUsbPsu::AppData, XUsbPsu_Ep::BufferPtr, XUsbPsu_Ep::BytesTxed, XUsbPsu::ConfigPtr, XUsbPsu_Ep::Direction, XUsbPsu_Event_Epevt::Endpoint_Event, XUsbPsu_Event_Epevt::Epnumber, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Ep::Handler, XUsbPsu_Config::IsCacheCoherent, XUsbPsu_Ep::MaxSize, XUsbPsu_Ep::RequestedBytes, XUsbPsu_Ep::ResourceIndex, XUsbPsu_Ep::TrbDequeue, XUsbPsu_Ep::UnalignedTx, XUSBPSU_EP_DIR_IN, XUSBPSU_EP_DIR_OUT.
Referenced by XUsbPsu_EpEvent.
void XUsbPsu_EpXferNotReady(struct XUsbPsu *InstancePtr, const struct XUsbPsu_Event_Epevt *Event)
For Isochronous transfer, gets the microframe time and calls respective endpoint handler.
InstancePtr Pointer to the XUsbPsu instance. Event Pointer to the Endpoint event occurred in core. None.
References XUsbPsu::AppData, XUsbPsu_Ep::CurUf, XUsbPsu_Event_Epevt::Epnumber, XUsbPsu::eps, XUsbPsu_Ep::Handler, XUsbPsu_Ep::Interval, XUsbPsu_Event_Epevt::Parameters, XUsbPsu_Ep::Type, XUSBPSU_ENDPOINT_XFER_ISOC.
Referenced by XUsbPsu_EpEvent.