xusbpsu_controltransfers.c
void XUsbPsu_Ep0StallRestart(struct XUsbPsu *InstancePtr)
Stalls control endpoint and restarts to receive setup packet.
InstancePtr Pointer to the XUsbPsu instance. None
References XUsbPsu::Ep0State, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUSBPSU_EP_DIR_OUT, XUsbPsu_EpSetStall, XUsbPsu_RecvSetup.
Referenced by XUsbPsu_Ep0StatusDone, XUsbPsu_Ep0XferNotReady.
void XUsbPsu_Ep0DataDone(struct XUsbPsu *InstancePtr, const struct XUsbPsu_Event_Epevt *Event)
Checks the data phase and calls user endpoint handler.
InstancePtr Pointer to the XUsbPsu instance. Event Pointer to the Endpoint event occurred in core. None.
References XUsbPsu::AppData, XUsbPsu_Ep::BufferPtr, XUsbPsu_Ep::BytesTxed, XUsbPsu::ConfigPtr, XUsbPsu_Event_Epevt::Epnumber, XUsbPsu::eps, XUsbPsu_Ep::Handler, XUsbPsu_Config::IsCacheCoherent, XUsbPsu_Ep::RequestedBytes, XUsbPsu_Ep::UnalignedTx, XUSBPSU_EP_DIR_IN, XUSBPSU_EP_DIR_OUT.
Referenced by XUsbPsu_Ep0XferComplete.
void XUsbPsu_Ep0StatusDone(struct XUsbPsu *InstancePtr)
Checks the status phase and starts next control transfer.
InstancePtr Pointer to the XUsbPsu instance. None.
References XUsbPsu::ConfigPtr, XUsbPsu_Config::IsCacheCoherent, XUsbPsu::IsInTestMode, XUsbPsu::TestMode, XUsbPsu_Ep0StallRestart, XUsbPsu_RecvSetup, XUsbPsu_SetTestMode.
Referenced by XUsbPsu_Ep0XferComplete.
s32 XUsbPsu_Ep0StartStatus(struct XUsbPsu *InstancePtr, const struct XUsbPsu_Event_Epevt *Event)
Starts status phase of control transfer.
InstancePtr Pointer to the XUsbPsu instance. Event Pointer to the Endpoint event occurred in core. XST_SUCCESS else XST_FAILURE
References XUsbPsu_Trb::BufferPtrHigh, XUsbPsu_Trb::BufferPtrLow, XUsbPsu::ConfigPtr, XUsbPsu::ControlDir, XUsbPsu_Trb::Ctrl, XUsbPsu_Ep::Direction, XUsbPsu::Ep0State, XUsbPsu_Event_Epevt::Epnumber, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Config::IsCacheCoherent, XUsbPsu::IsThreeStage, XUsbPsu_EpParams::Param0, XUsbPsu_EpParams::Param1, XUsbPsu_Ep::ResourceIndex, XUsbPsu_Trb::Size, XUsbPsu_Ep::UsbEpNum, XUsbPsu_EpGetTransferIndex, XUsbPsu_GetEpParams, XUsbPsu_SendEpCmd.
Referenced by XUsbPsu_Ep0XferNotReady.
void XUsbPsu_Ep0_EndControlData(struct XUsbPsu *InstancePtr, struct XUsbPsu_Ep *Ept)
Ends data phase which is used in case of the error.
InstancePtr Pointer to the XUsbPsu instance. Ept Pointer to the Endpoint structure. None
References XUsbPsu_Ep::Direction, XUsbPsu_Ep::ResourceIndex, XUsbPsu_Ep::UsbEpNum, XUsbPsu_GetEpParams, XUsbPsu_SendEpCmd, XUsbPsu_Sleep.
Referenced by XUsbPsu_Ep0XferNotReady.
s32 XUsbPsu_EnableControlEp(struct XUsbPsu *InstancePtr, u16 Size)
Enables USB control endpoint that is EP0OUT and EP0IN of Core.
InstancePtr Pointer to the XUsbPsu instance. Size Control endpoint size. XST_SUCCESS else XST_FAILURE.
References XUSBPSU_ENDPOINT_XFER_CONTROL, XUSBPSU_EP_DIR_IN, XUSBPSU_EP_DIR_OUT, XUsbPsu_EpEnable.
Referenced by XUsbPsu_ConnDoneIntr.