xusbpsu_ep0handler.c
s32 XUsbPsu_RecvSetup(struct XUsbPsu *InstancePtr)
Initiates DMA on control endpoint 0 to receive setup packet.
InstancePtr Pointer to the XUsbPsu instance. XST_SUCCESS else XST_FAILURE.
References XUsbPsu_Trb::BufferPtrHigh, XUsbPsu_Trb::BufferPtrLow, XUsbPsu::ConfigPtr, XUsbPsu_Trb::Ctrl, XUsbPsu_Ep::Direction, XUsbPsu::Ep0State, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Config::IsCacheCoherent, XUsbPsu_EpParams::Param0, XUsbPsu_EpParams::Param1, XUsbPsu_Ep::ResourceIndex, XUsbPsu_Trb::Size, XUsbPsu_Ep::UsbEpNum, XUSBPSU_EP_DIR_OUT, XUsbPsu_EpGetTransferIndex, XUsbPsu_GetEpParams, XUsbPsu_SendEpCmd.
Referenced by XUsbPsu_ConnDoneIntr, XUsbPsu_Ep0StallRestart, XUsbPsu_Ep0StatusDone.
void XUsbPsu_Ep0XferComplete(struct XUsbPsu *InstancePtr, const struct XUsbPsu_Event_Epevt *Event)
Handles transfer complete event of control endpoints EP0 OUT and EP0 IN.
InstancePtr Pointer to the XUsbPsu instance. Event Pointer to the Endpoint event occurred in core. None.
References XUsbPsu::AppData, SetupPacket::bRequestType, XUsbPsu::Chapter9, XUsbPsu::ConfigPtr, XUsbPsu::ControlDir, XUsbPsu::Ep0State, XUsbPsu_Event_Epevt::Epnumber, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Config::IsCacheCoherent, XUsbPsu::IsThreeStage, XUsbPsu_Ep::ResourceIndex, SetupPacket::wLength, XUsbPsu_Ep0DataDone, XUsbPsu_Ep0StatusDone, XUSBPSU_EP_DIR_OUT, XUSBPSU_USB_DIR_IN.
Referenced by XUsbPsu_Ep0Intr.
void XUsbPsu_Ep0XferNotReady(struct XUsbPsu *InstancePtr, const struct XUsbPsu_Event_Epevt *Event)
Handles transfer not ready event of control endpoints EP0 OUT and EP0 IN.
InstancePtr Pointer to the XUsbPsu instance. Event Pointer to the Endpoint event occurred in core. None.
References XUsbPsu::ControlDir, XUsbPsu_Event_Epevt::Epnumber, XUsbPsu::eps, XUsbPsu_Event_Epevt::Status, XUsbPsu_Ep0_EndControlData, XUsbPsu_Ep0StallRestart, XUsbPsu_Ep0StartStatus.
Referenced by XUsbPsu_Ep0Intr.
s32 XUsbPsu_Ep0Send(struct XUsbPsu *InstancePtr, u8 *BufferPtr, u32 BufferLen)
Initiates DMA to send data on control endpoint EP0 IN to host.
InstancePtr Pointer to the XUsbPsu instance. BufferPtr Pointer to data. BufferLen Length of data buffer. XST_SUCCESS else XST_FAILURE
References XUsbPsu_Ep::BufferPtr, XUsbPsu_Trb::BufferPtrHigh, XUsbPsu_Trb::BufferPtrLow, XUsbPsu_Ep::BytesTxed, XUsbPsu::ConfigPtr, XUsbPsu_Trb::Ctrl, XUsbPsu_Ep::Direction, XUsbPsu::Ep0State, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Config::IsCacheCoherent, XUsbPsu_EpParams::Param0, XUsbPsu_EpParams::Param1, XUsbPsu_Ep::RequestedBytes, XUsbPsu_Ep::ResourceIndex, XUsbPsu_Trb::Size, XUsbPsu_Ep::UsbEpNum, XUSBPSU_EP_DIR_IN, XUsbPsu_EpGetTransferIndex, XUsbPsu_GetEpParams, XUsbPsu_SendEpCmd.
Referenced by XUsbPsu_EpBufferSend.
s32 XUsbPsu_Ep0Recv(struct XUsbPsu *InstancePtr, u8 *BufferPtr, u32 Length)
Initiates DMA to receive data on control endpoint EP0 OUT from host.
InstancePtr Pointer to the XUsbPsu instance. BufferPtr Pointer to data. Length Length of data to be received. XST_SUCCESS else XST_FAILURE
References XUsbPsu_Ep::BufferPtr, XUsbPsu_Trb::BufferPtrHigh, XUsbPsu_Trb::BufferPtrLow, XUsbPsu_Ep::BytesTxed, XUsbPsu::ConfigPtr, XUsbPsu_Trb::Ctrl, XUsbPsu_Ep::Direction, XUsbPsu::Ep0State, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Config::IsCacheCoherent, XUsbPsu_Ep::MaxSize, XUsbPsu_EpParams::Param0, XUsbPsu_EpParams::Param1, XUsbPsu_Ep::RequestedBytes, XUsbPsu_Ep::ResourceIndex, XUsbPsu_Trb::Size, XUsbPsu_Ep::UnalignedTx, XUsbPsu_Ep::UsbEpNum, XUSBPSU_EP_DIR_OUT, XUsbPsu_EpGetTransferIndex, XUsbPsu_GetEpParams, XUsbPsu_SendEpCmd.
Referenced by XUsbPsu_EpBufferRecv.