xusbpsu_device.c
static void XUsbPsu_EventBuffersReset(struct XUsbPsu *InstancePtr)
Resets event buffer registers to zero so that events are not written by Core.
InstancePtr Pointer to the XUsbPsu instance to be worked on. None
void XUsbPsu_PhyReset(struct XUsbPsu *InstancePtr)
Issues core PHY reset.
InstancePtr Pointer to the XUsbPsu instance to be worked on. None
References XUsbPsu_Sleep.
Referenced by XUsbPsu_CoreInit.
s32 XUsbPsu_WaitClearTimeout(struct XUsbPsu *InstancePtr, u32 Offset, u32 BitMask, u32 Timeout)
Waits until a bit in a register is cleared or timeout occurs.
InstancePtr Pointer to the XUsbPsu instance to be worked on. Offset Register offset. BitMask Bit mask of required bit to be checked. Timeout Time to wait specified in micro seconds. XST_SUCCESS when bit is cleared.XST_FAILURE when timed out.
References XUsbPsu_Config::BaseAddress, XUsbPsu::ConfigPtr.
Referenced by XUsbPsu_CoreInit, XUsbPsu_Idle, XUsbPsu_SendEpCmd, XUsbPsu_SetLinkState, XUsbPsu_Start.
s32 XUsbPsu_WaitSetTimeout(struct XUsbPsu *InstancePtr, u32 Offset, u32 BitMask, u32 Timeout)
Waits until a bit in a register is set or timeout occurs.
InstancePtr Pointer to the XUsbPsu instance to be worked on Offset Register offset. BitMask Bit mask of required bit to be checked. Timeout Time to wait specified in micro seconds. XST_SUCCESS when bit is set.XST_FAILURE when timed out.
References XUsbPsu_Config::BaseAddress, XUsbPsu::ConfigPtr.
Referenced by XUsbPsu_Stop.
static void XUsbPsu_SetRegVal(struct XUsbPsu *InstancePtr, u32 Offset, u32 BitMask)
Sets the register bits with the bit mask value.
InstancePtr Pointer to the XUsbPsu instance to be worked on Offset Register offset. BitMask Bit mask of required bit to be checked. None
static void XUsbPsu_ClearRegVal(struct XUsbPsu *InstancePtr, u32 Offset, u32 BitMask)
Clears the register bits with the bit mask value.
InstancePtr Pointer to the XUsbPsu instance to be worked on. Offset Register offset. BitMask Bit mask of required bit to be checked. None
u32 XUsbPsu_ReadHwParams(struct XUsbPsu *InstancePtr, u8 RegIndex)
Reads data from hardware parameters registers of the core.
InstancePtr Pointer to the XUsbPsu instance to be worked on RegIndex Register number to read. XUSBPSU_GHWPARAMS0XUSBPSU_GHWPARAMS1XUSBPSU_GHWPARAMS2XUSBPSU_GHWPARAMS3XUSBPSU_GHWPARAMS4XUSBPSU_GHWPARAMS5XUSBPSU_GHWPARAMS6XUSBPSU_GHWPARAMS7 One of the GHWPARAMS RegValister contents.
Referenced by XUsbPsu_CfgInitialize, XUsbPsu_CoreInit, XUsbPsu_Idle.
void XUsbPsu_SetSpeed(struct XUsbPsu *InstancePtr, u32 Speed)
Sets speed of the core for connecting to host.
InstancePtr Pointer to the XUsbPsu instance. Speed Required speed XUSBPSU_DCFG_HIGHSPEEDXUSBPSU_DCFG_FULLSPEED2XUSBPSU_DCFG_LOWSPEEDXUSBPSU_DCFG_FULLSPEED1 None
Referenced by XUsbPsu_CfgInitialize.
s32 XUsbPsu_SetDeviceAddress(struct XUsbPsu *InstancePtr, u16 Addr)
Sets the device address of the core.
InstancePtr Pointer to the XUsbPsu instance. Addr Address to set. XST_SUCCESS else XST_FAILURE
References XUsbPsu::AppData, Usb_DevData::State, XUSBPSU_STATE_ADDRESS, XUSBPSU_STATE_CONFIGURED, XUSBPSU_STATE_DEFAULT.
Referenced by XUsbPsu_CfgInitialize.
s32 XUsbPsu_SetTestMode(struct XUsbPsu *InstancePtr, u32 Mode)
Enables USB2 test modes.
InstancePtr Pointer to the XUsbPsu instance. Mode Test mode to set. XST_SUCCESS else XST_FAILURE
References XUSBPSU_TEST_FORCE_ENABLE, XUSBPSU_TEST_J, XUSBPSU_TEST_K, XUSBPSU_TEST_PACKET, XUSBPSU_TEST_SE0_NAK.
Referenced by XUsbPsu_Ep0StatusDone.
void XUsbPsu_Idle(struct XUsbPsu *InstancePtr)
This function puts the controller into idle state by stopping the transfers for all endpoints, stopping the usb core, and clearing the event buffers.
InstancePtr Pointer to the XUsbPsu instance to be worked on. None
References XUSBPSU_EP_DIR_IN, XUSBPSU_EP_DIR_OUT, XUsbPsu_EpTransferDeactive, XUsbPsu_ReadHwParams, XUsbPsu_Stop, XUsbPsu_StopTransfer, XUsbPsu_WaitClearTimeout.
s32 XUsbPsu_CoreInit(struct XUsbPsu *InstancePtr)
Initializes the core.
InstancePtr Pointer to the XUsbPsu instance to be worked on. XST_SUCCESS if initialization was successful.XST_FAILURE if initialization was not successful.
References XUsbPsu::ConfigPtr, XUsbPsu::HasHibernation, XUsbPsu_Config::IsCacheCoherent, XUsbPsu_PhyReset, XUsbPsu_ReadHwParams, XUsbPsu_WaitClearTimeout.
Referenced by XUsbPsu_CfgInitialize.
void XUsbPsu_EventBuffersSetup(struct XUsbPsu *InstancePtr)
Sets up the event buffers so that events are written by Core.
InstancePtr Pointer to the XUsbPsu instance to be worked on. None
References XUsbPsu_EvtBuffer::BuffAddr, XUsbPsu::EventBuffer, XUsbPsu::Evt, XUsbPsu_EvtBuffer::Offset.
Referenced by XUsbPsu_CfgInitialize.
void XUsbPsu_Sleep(u32 USeconds)
API for Sleep routine.
USeconds Time in MicroSeconds. None.
Referenced by XUsbPsu_Ep0_EndControlData, XUsbPsu_PhyReset, XUsbPsu_StopTransfer.