xusb_class_audio_dfu.c
u8 DetachCounter
static void Usb_DfuWaitForReset(struct dfu_if *DFU)
s32 Usb_DfuSetState(struct dfu_if *DFU, u8 dfu_state)
This function handles setting of DFU state.
DFU is a pointer to DFU instance of the controller dfu_state is a value of the DFU state to be set - XST_SUCCESS if the function is successful. XST_FAILURE if an Error occurred. None.
Referenced by Usb_DfuClassReq, Usb_DfuSetIntf, Usb_SetIntf.
void USB_DfuSetDwloadState(struct dfu_if *DFU, u8 *status)
This function updates the current state while downloading a file.
DFU is a pointer to DFU instance of the controller status is a pointer of the DFU status None.
Referenced by USB_DfuGetStatus.
void USB_DfuGetStatus(struct dfu_if *DFU, u8 *status)
This function handles getting of DFU status.
DFU is a pointer to DFU instance of the controller status is the pointer of the DFU status None None.
Referenced by Usb_DfuClassReq.
void Usb_DisconnectHandler(struct Usb_DevData *InstancePtr)
This function handles USB disconnect, called from driver.
InstancePtr is a pointer to Usb_DevData instance of the controller None. None.
void Usb_ResetHandler(struct Usb_DevData *InstancePtr)
This function handles USB reset, called from driver.
InstancePtr is a pointer to Usb_DevData instance of the controller None. None.
void Usb_SetIntf(struct Usb_DevData *InstancePtr, SetupPacket *SetupData)
This function handles set interface request.
InstancePtr is a pointer to Usb_DevData instance of the controller SetupData is a pointer to setup token of control transfer None. None.
static void Usb_AudioClassReq(struct Usb_DevData *InstancePtr, SetupPacket *SetupData)
This function handles UAC1 class request.
InstancePtr is a pointer to Usb_DevData instance of the controller SetupData is a pointer to setup token of control transfer None. None.
static void Usb_DfuClassReq(struct Usb_DevData *InstancePtr, SetupPacket *SetupData)
This function handles DFU heart and soul of DFU state machine.
InstancePtr is a pointer to Usb_DevData instance of the controller SetupData is a pointer to setup token of control transfer None. None.
void Usb_ClassReq(struct Usb_DevData *InstancePtr, SetupPacket *SetupData)