xusbpsu_command.c
struct XUsbPsu_EpParams* XUsbPsu_GetEpParams(struct XUsbPsu *InstancePtr)
Returns zeroed parameters to be used by Endpoint commands.
InstancePtr Pointer to the XUsbPsu instance. Zeroed Params structure pointer.
References XUsbPsu::EpParams, XUsbPsu_EpParams::Param0, XUsbPsu_EpParams::Param1, XUsbPsu_EpParams::Param2.
Referenced by XUsbPsu_ClearStalls, XUsbPsu_Ep0_EndControlData, XUsbPsu_Ep0Recv, XUsbPsu_Ep0Send, XUsbPsu_Ep0StartStatus, XUsbPsu_EpClearStall, XUsbPsu_EpSetStall, XUsbPsu_RecvSetup, XUsbPsu_SaveEndpointState, XUsbPsu_SetEpConfig, XUsbPsu_SetXferResource, XUsbPsu_StartEpConfig, XUsbPsu_StopTransfer.
s32 XUsbPsu_EpEnable(struct XUsbPsu *InstancePtr, u8 UsbEpNum, u8 Dir, u16 Maxsize, u8 Type, u8 Restore)
Enables endpoint for sending/receiving data.
InstancePtr Pointer to the XUsbPsu instance. UsbEpNum USB endpoint number. Dir Direction of endpoint XUSBPSU_EP_DIR_IN/XUSBPSU_EP_DIR_OUT. Maxsize Size of Endpoint size. Type Endpoint type Control/Bulk/Interrupt/Isoc. Restore Typically False, True if saved state has to be restored. XST_SUCCESS else XST_FAILURE.
References XUsbPsu_Trb::BufferPtrHigh, XUsbPsu_Trb::BufferPtrLow, XUsbPsu::ConfigPtr, XUsbPsu_Trb::Ctrl, XUsbPsu_Ep::CurUf, XUsbPsu_Ep::Direction, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Config::IsCacheCoherent, XUsbPsu::IsHibernated, XUsbPsu_Ep::MaxSize, XUsbPsu_Ep::PhyEpNum, XUsbPsu_Ep::TrbDequeue, XUsbPsu_Ep::TrbEnqueue, XUsbPsu_Ep::Type, XUsbPsu_Ep::UsbEpNum, XUSBPSU_EP_DIR_IN, XUSBPSU_EP_DIR_OUT, XUsbPsu_SetEpConfig, XUsbPsu_SetXferResource, XUsbPsu_StartEpConfig.
Referenced by XUsbPsu_EnableControlEp.
s32 XUsbPsu_EpDisable(struct XUsbPsu *InstancePtr, u8 UsbEpNum, u8 Dir)
Disables Endpoint.
InstancePtr Pointer to the XUsbPsu instance. UsbEpNum USB endpoint number. Dir Direction of endpoint XUSBPSU_EP_DIR_IN/XUSBPSU_EP_DIR_OUT. XST_SUCCESS else XST_FAILURE.
References XUsbPsu_Ep::Direction, XUsbPsu::eps, XUsbPsu_Ep::EpStatus, XUsbPsu_Ep::MaxSize, XUsbPsu_Ep::PhyEpNum, XUsbPsu_Ep::TrbDequeue, XUsbPsu_Ep::TrbEnqueue, XUsbPsu_Ep::Type, XUsbPsu_Ep::UsbEpNum, XUSBPSU_EP_DIR_IN, XUSBPSU_EP_DIR_OUT, XUsbPsu_EpClearStall.
s32 XUsbPsu_SendEpCmd(struct XUsbPsu *InstancePtr, u8 UsbEpNum, u8 Dir, u32 Cmd, struct XUsbPsu_EpParams *Params)
Sends Endpoint command to the Endpoint.
InstancePtr Pointer to the XUsbPsu instance. UsbEpNum USB endpoint number. Dir Direction of endpoint XUSBPSU_EP_DIR_IN/ XUSBPSU_EP_DIR_OUT. Cmd Endpoint command. Params Endpoint command parameters. XST_SUCCESS else XST_FAILURE.
References XUsbPsu_EpParams::Param0, XUsbPsu_EpParams::Param1, XUsbPsu_EpParams::Param2, XUsbPsu_Ep::PhyEpNum, XUsbPsu_Ep::UsbEpNum, XUSBPSU_EP_DIR_IN, XUSBPSU_EP_DIR_OUT, XUsbPsu_WaitClearTimeout.
Referenced by XUsbPsu_ClearStalls, XUsbPsu_Ep0_EndControlData, XUsbPsu_Ep0Recv, XUsbPsu_Ep0Send, XUsbPsu_Ep0StartStatus, XUsbPsu_EpBufferRecv, XUsbPsu_EpBufferSend, XUsbPsu_EpClearStall, XUsbPsu_EpSetStall, XUsbPsu_RecvSetup, XUsbPsu_SaveEndpointState, XUsbPsu_SetEpConfig, XUsbPsu_SetXferResource, XUsbPsu_StartEpConfig, XUsbPsu_StopTransfer.