xusb_wrapper.h
USB_EP1_IN
USB_EP1_OUT
USB_EP2_IN
USB_EP2_OUT
USB_EP_TYPE_CONTROL
USB_EP_TYPE_ISOCHRONOUS
USB_EP_TYPE_BULK
USB_EP_TYPE_INTERRUPT
XUSB_WRAPPER_H
USB_DEVICE_ID
USB_EP_DIR_IN
USB_EP_DIR_OUT
USB_DIR_OUT
USB_DIR_IN
USB_ENDPOINT_NUMBER_MASK
USB_ENDPOINT_DIR_MASK
USB_STATE_ATTACHED
USB_STATE_POWERED
USB_STATE_DEFAULT
USB_STATE_ADDRESS
USB_STATE_CONFIGURED
USB_STATE_SUSPENDED
XUSBPSU_REQ_REPLY_LEN
Max size of reply buffer.
USB_REQ_REPLY_LEN
USB_SPEED_UNKNOWN
USB_SPEED_LOW
USB_SPEED_FULL
USB_SPEED_HIGH
USB_SPEED_SUPER
USB_DCFG_SPEED_MASK
USB_DCFG_SUPERSPEED
USB_DCFG_HIGHSPEED
USB_DCFG_FULLSPEED2
USB_DCFG_LOWSPEED
USB_DCFG_FULLSPEED1
USB_TEST_J
USB_TEST_K
USB_TEST_SE0_NAK
USB_TEST_PACKET
USB_TEST_FORCE_ENABLE
USB_LPM_MODE
PhysicalEp
Usb_Config* LookupConfig(UINTPTR BaseAddress)
void CacheInit(void)
s32 CfgInitialize(struct Usb_DevData *InstancePtr, Usb_Config *ConfigPtr, u32 BaseAddress)
void Set_Ch9Handler(void *InstancePtr, void(*func)(struct Usb_DevData *, SetupPacket *))
void Set_RstHandler(void *InstancePtr, void(*func)(struct Usb_DevData *))
void Set_Disconnect(void *InstancePtr, void(*func)(struct Usb_DevData *))
void EpConfigure(void *UsbInstance, u8 EndpointNo, u8 dir, u32 Type)
s32 ConfigureDevice(void *UsbInstance, u8 *MemPtr, u32 memSize)
void SetEpHandler(void *InstancePtr, u8 Epnum, u8 Dir, void(*Handler)(void *, u32, u32))
s32 Usb_Start(void *InstancePtr)
void UsbPollHandler(struct XUsbPsu *InstancePtr)
Handler called from polled mode for handling usb events.
InstancePtr is a pointer to the XUsbPsu instance. None. None.
References XUsbPsu_IntrHandler.
Referenced by main.
void UsbEnableEvent(struct XUsbPsu *InstancePtr, u32 Mask)
Enables the events specified in the mask.
InstancePtr is a pointer to the XUsbPsu instance. None. None.
References XUsbPsu_EnableIntr.
Referenced by main.
void* Get_DrvData(void *InstancePtr)
void Set_DrvData(void *InstancePtr, void *data)
s32 IsEpStalled(void *InstancePtr, u8 Epnum, u8 Dir)
void EpClearStall(void *InstancePtr, u8 Epnum, u8 Dir)
s32 EpBufferSend(void *InstancePtr, u8 UsbEp, u8 *BufferPtr, u32 BufferLen)
s32 EpBufferRecv(void *InstancePtr, u8 UsbEp, u8 *BufferPtr, u32 Length)
void EpSetStall(void *InstancePtr, u8 Epnum, u8 Dir)
void SetBits(void *InstancePtr, u32 TestSel)
s32 SetDeviceAddress(void *InstancePtr, u16 Addr)
s32 SetU1SleepTimeout(void *InstancePtr, u8 Sleep)
s32 SetU2SleepTimeout(void *InstancePtr, u8 Sleep)
s32 AcceptU1U2Sleep(void *InstancePtr)
s32 U1SleepEnable(void *InstancePtr)
s32 U2SleepEnable(void *InstancePtr)
s32 U1SleepDisable(void *InstancePtr)
s32 U2SleepDisable(void *InstancePtr)
s32 EpEnable(void *InstancePtr, u8 UsbEpNum, u8 Dir, u16 Maxsize, u8 Type)
s32 EpDisable(void *InstancePtr, u8 UsbEpNum, u8 Dir)
void Usb_SetSpeed(void *InstancePtr, u32 Speed)
s32 IsSuperSpeed(struct Usb_DevData *InstancePtr)
Sets speed of the Core for connecting to Host.
InstancePtr is a pointer to the Usb_DevData instance. XST_SUCCESS else XST_FAILURE None.
References Usb_DevData::PrivateData, XUsbPsu_IsSuperSpeed.
Referenced by ParseCBW, Usb_Ch9SetupCfgDescReply, Usb_Ch9SetupDevDescReply, Usb_Ch9SetupStrDescReply.
void SetConfigDone(void *InstancePtr, u8 Flag)
Set the Config state.
InstancePtr is a private member of Usb_DevData instance. Flag is the config value. None. None.
Referenced by Usb_SetConfiguration, Usb_SetConfigurationApp.
u8 GetConfigDone(void *InstancePtr)
Get the Config state.
InstancePtr is a private member of Usb_DevData instance. Current configuration value None.
References XUsbPsu::IsConfigDone.
void Ep0StallRestart(void *InstancePtr)
void SetEpInterval(void *InstancePtr, u8 UsbEpNum, u8 Dir, u32 Interval)
This function sets Endpoint Interval.
InstancePtr is a private member of Usb_DevData instance. UsbEpnum is Endpoint Number. Dir is Endpoint Direction(In/Out). Interval is the data transfer service interval None. None.
References XUsbPsu_Ep::Interval.
Referenced by prvPlayBackTask, prvRecordTask, Usb_SetIntf.
void StopTransfer(void *InstancePtr, u8 EpNum, u8 Dir)
s32 StreamOn(void *InstancePtr, u8 EpNum, u8 Dir, u8 *BufferPtr)
void StreamOff(void *InstancePtr, u8 EpNum, u8 Dir)