xxvethernet
XXE_FCS_STRIP_OPTION
< XXE_FCS_STRIP_OPTION specifies the Xxv Ethernet device to strip FCS and PAD from received frames.
This driver sets this option to enabled (set) by default.XXE_FCS_INSERT_OPTION specifies the Xxv Ethernet device to generate the FCS field and add PAD automatically for outgoing frames. This driver sets this option to enabled (set) by default.
Referenced by XXxvEthernet_ClearOptions, XXxvEthernet_SetOptions.
XXE_FCS_INSERT_OPTION
XXE_TRANSMITTER_ENABLE_OPTION specifies the Xxv Ethernet device transmitter to be enabled.
This driver sets this option to enabled (set) by default.
Referenced by XXxvEthernet_ClearOptions, XXxvEthernet_SetOptions.
XXE_TRANSMITTER_ENABLE_OPTION
XXE_RECEIVER_ENABLE_OPTION specifies the Xxv Ethernet device receiver to be enabled.
This driver sets this option to enabled (set) by default.
Referenced by XXxvEthernet_ClearOptions, XXxvEthernet_SetOptions, XXxvEthernet_Start.
XXE_RECEIVER_ENABLE_OPTION
XXE_DEFAULT_OPTIONS
XXE_DEFAULT_OPTIONS specify the options set in XXxvEthernet_Reset() and XXxvEthernet_CfgInitialize()
Referenced by XXxvEthernet_Reset, XXxvEthernet_SetOptions.
XXE_GRR_OFFSET
XXE_RST_OFFSET
XXE_MODE_OFFSET
XXE_TXCFG_OFFSET
XXE_RXCFG_OFFSET
XXE_RXMTU_OFFSET
XXE_TICK_OFFSET
XXE_REV_OFFSET
XXE_USXGMII_AN_OFFSET
XXE_RSFEC_OFFSET
XXE_FEC_OFFSET
XXE_ANCR1_OFFSET
XXE_ANCR2_OFFSET
XXE_ANACR_OFFSET
XXE_LTCR_OFFSET
XXE_LTTR_OFFSET
XXE_LTPR_OFFSET
XXE_LTIR_OFFSET
XXE_LTSR_OFFSET
XXE_LTCOR_OFFSET
XXE_USR0_OFFSET
XXE_USR1_OFFSET
XXE_CORESPEEDSR_OFFSET
XXE_TXSR_OFFSET
XXE_RXSR_OFFSET
XXE_SR_OFFSET
XXE_RXBLSR_OFFSET
XXE_ANSR_OFFSET
XXE_ANASR_OFFSET
XXE_MODE_LCLLPBK_MASK
XXE_TXCFG_TX_MASK
XXE_TXCFG_FCS_MASK
XXE_RXCFG_RX_MASK
XXE_RXCFG_DEL_FCS_MASK
XXE_RXCFG_IGN_FCS_MASK
XXE_USXGMII_ANBYPASS_MASK
XXE_USXGMII_ANENABLE_MASK
XXE_USXGMII_ANMAINRESET_MASK
XXE_USXGMII_ANRESTART_MASK
XXE_USXGMII_RATE_MASK
XXE_USXGMII_ANA_MASK
XXE_USXGMII_ANA_SPEED_MASK
XXE_USXGMII_ANA_FD_MASK
XXE_USXGMII_ANACK_MASK
XXE_USXGMII_LINK_STS_MASK
XXE_USXGMII_RATE_10M_MASK
XXE_USXGMII_RATE_100M_MASK
XXE_USXGMII_RATE_1G_MASK
XXE_USXGMII_RATE_10G_MASK
XXE_USXGMII_RATE_2G5_MASK
XXE_USXGMII_RATE_SHIFT
XXE_USXGMII_SPEED_SHIFT
XXE_RXMTU_MIN_JUM_MASK
XXE_RXMTU_MAX_JUM_MASK
XXE_RXBLKLCK_MASK
XXE_TICK_STATEN_MASK
XXE_AN_COMP_MASK
XXE_USXGMII_AN_COMP_MASK
XXE_ANA_10GKR_MASK
XXE_RAF_STATSRST_MASK
Statistics Counter Reset.
XXE_RAF_RXBADFRMEN_MASK
Receive Bad Frame Enable.
XXE_TFGP_IFGP_MASK
Transmit inter-frame gap adjustment value.
XXE_SPEED_10_GBPS
Speed of 10 Gbps.
Referenced by XXxvEthernet_GetAutoNegSpeed.
XXE_LOOPS_TO_COME_OUT_OF_RST
Number of loops in the driver API to wait for before returning a failure case.
Referenced by XXxvEthernet_Reset.
XXE_RST_DELAY_LOOPCNT_VAL
Timeout in ticks used while checking if the core had come out of reset.
The exact tick time is defined in each case/loop where it will be used
typedef struct XXxvEthernet_Config XXxvEthernet_Config
This typedef contains configuration information for a Xxv Ethernet device.
typedef struct XXxvEthernet XXxvEthernet
struct XXxvEthernet is the type for Xxv Ethernet driver instance data.
The calling code is required to use a unique instance of this structure for every Xxv Ethernet device used in the system. A reference to a structure of this type is then passed to the driver API functions.
static void XXxvEthernet_InitHw(XXxvEthernet *InstancePtr)
int XXxvEthernet_CfgInitialize(XXxvEthernet *InstancePtr, XXxvEthernet_Config *CfgPtr, UINTPTR EffectiveAddress)
XXxvEthernet_CfgInitialize initializes an XXV Ethernet device along with the InstancePtr that references it.
InstancePtr references the memory instance to be associated with the XXV Ethernet core instance upon initialization. CfgPtr references the structure holding the hardware configuration for the Xxv Ethernet core to initialize. EffectiveAddress is the processor address used to access the base address of the XXV Ethernet instance. In systems with an MMU and virtual memory, EffectiveAddress is the virtual address mapped to the physical in ConfigPtr->Config.BaseAddress. In systems without an active MMU, EffectiveAddress should be set to the same value as ConfigPtr->Config.BaseAddress. XST_SUCCESS None.
References XXxvEthernet_Config::BaseAddress, XXxvEthernet::Config, XXxvEthernet::IsReady, XXxvEthernet_Reset.
Referenced by XxvEthernetSgDmaIntrExample.
int XXxvEthernet_Initialize(XXxvEthernet *InstancePtr, XXxvEthernet_Config *CfgPtr)
XXxvEthernet_Initialize initializes an XXV Ethernet device along with the InstancePtr that references it.
The PHY is setup independently from the Ethernet core. Use the MII or whatever other interface may be present for setup. InstancePtr references the memory instance to be associated with the AXI Ethernet core instance upon initialization. CfgPtr references the structure holding the hardware configuration for the Axi Ethernet core to initialize. XST_SUCCESS. When user calls this function he should ensure the hardware is in a quiescent state by resetting all the hardware Configurations.
References XXxvEthernet_Config::BaseAddress, XXxvEthernet::Config, XXxvEthernet::IsReady.
int XXxvEthernet_Start(XXxvEthernet *InstancePtr)
XXxvEthernet_Start starts the Xxv Ethernet device as follows:
- Enable transmitter if XXE_TRANSMIT_ENABLE_OPTION is set - Enable receiver if XXE_RECEIVER_ENABLE_OPTION is set - Upon enabling RX, check for RX BLOCK LOCK bit to make sure RX channel is ready. InstancePtr is a pointer to the Xxv Ethernet instance to be worked on. XST_FAILURE if RX is enabled and BLOCK LOCK is not set. None
References XXxvEthernet_Config::BaseAddress, XXxvEthernet::Config, XXxvEthernet::IsReady, XXxvEthernet::IsStarted, XXxvEthernet::Options, XXE_TRANSMITTER_ENABLE_OPTION, XXxvEthernet_ReadReg, XXxvEthernet_WriteReg.
Referenced by XxvEthernetSgDmaIntrSingleFrameExample.
void XXxvEthernet_Stop(XXxvEthernet *InstancePtr)
XXxvEthernet_Stop gracefully stops the Xxv Ethernet device by disabling the receiver.
XXxvEthernet_Stop does not modify any of the current device options.Since the transmitter is not disabled, frames currently in internal buffers or in process by a DMA engine are allowed to be transmitted. InstancePtr is a pointer to the Xxv Ethernet instance to be worked on. None None.
References XXxvEthernet_Config::BaseAddress, XXxvEthernet::Config, XXxvEthernet::IsReady, XXxvEthernet::IsStarted, XXxvEthernet_ReadReg, XXxvEthernet_WriteReg.
Referenced by XxvEthernetSgDmaIntrExample, XxvEthernetSgDmaIntrSingleFrameExample, XXxvEthernet_Reset.
void XXxvEthernet_Reset(XXxvEthernet *InstancePtr)
XXxvEthernet_Reset does not perform a soft reset of the XxvEthernet core.
XxvEthernet hardware is reset by the device connected to the AXI4-Stream interface i.e. MCDMA. This function simply disabled TX and RX. This function inserts some delay before proceeding to stop the device. InstancePtr is a pointer to the Xxv Ethernet instance to be worked on. None
References XXxvEthernet::IsReady, XXxvEthernet::Options, XXE_DEFAULT_OPTIONS, XXE_LOOPS_TO_COME_OUT_OF_RST, XXxvEthernet_Stop.
Referenced by XXxvEthernet_CfgInitialize.
int XXxvEthernet_SetOptions(XXxvEthernet *InstancePtr, u32 Options)
XXxvEthernet_SetOptions enables the options, Options for the Xxv Ethernet, specified by InstancePtr.
Xxv Ethernet should be stopped with XXxvEthernet_Stop() before changing options. InstancePtr is a pointer to the Xxv Ethernet instance to be worked on. Options is a bitmask of OR'd XXE_*_OPTION values for options to set. Options not specified are not affected. XST_SUCCESS on successful completion.XST_DEVICE_IS_STARTED if the device has not been stopped. See xxxvethernet.h for a description of the available options.
References XXxvEthernet_Config::BaseAddress, XXxvEthernet::Config, XXxvEthernet::IsReady, XXxvEthernet::IsStarted, XXxvEthernet::Options, XXE_DEFAULT_OPTIONS, XXE_FCS_INSERT_OPTION, XXE_FCS_STRIP_OPTION, XXE_TRANSMITTER_ENABLE_OPTION, XXxvEthernet_ReadReg, XXxvEthernet_WriteReg.
Referenced by XxvEthernetUtilUsxgmiiSetup, XxvEthernetUtilUsxgmiiSetupBypassAN.
int XXxvEthernet_ClearOptions(XXxvEthernet *InstancePtr, u32 Options)
XXxvEthernet_ClearOptions clears the options, Options for the Xxv Ethernet, specified by InstancePtr.
Xxv Ethernet should be stopped with XXxvEthernet_Stop() before changing options. InstancePtr is a pointer to the Xxv Ethernet instance to be worked on. Options is a bitmask of OR'd XXE_*_OPTION values for options to clear. Options not specified are not affected. XST_SUCCESS on successful completion.XST_DEVICE_IS_STARTED if the device has not been stopped. See xxxvethernet.h for a description of the available options.
References XXxvEthernet_Config::BaseAddress, XXxvEthernet::Config, XXxvEthernet::IsReady, XXxvEthernet::IsStarted, XXxvEthernet::Options, XXE_FCS_INSERT_OPTION, XXE_FCS_STRIP_OPTION, XXE_TRANSMITTER_ENABLE_OPTION, XXxvEthernet_ReadReg, XXxvEthernet_WriteReg.
u32 XXxvEthernet_GetOptions(XXxvEthernet *InstancePtr)
XXxvEthernet_GetOptions returns the current option settings.
InstancePtr is a pointer to the Xxv Ethernet instance to be worked on. Returns a bitmask of XXE_*_OPTION constants, each bit specifying an option that is currently active. See xxxvethernet.h for a description of the available options.
References XXxvEthernet::IsReady, XXxvEthernet::Options.
int XXxvEthernet_SetUsxgmiiRateAndDuplex(XXxvEthernet *InstancePtr, u32 Rate, u32 SetFD)
XXxvEthernet_SetUsxgmiiRateAndDuplex sets the speed and duplex ability in USXGMII Autonegotiation register.
InstancePtr references the Xxv Ethernet on which to operate. Rate to be set - currently only 1G and 2.5G are tested. Pass RATE_1G or RATE_2G5 to the function. Set FD or HD - if 0 Half duplex is set, else Full duplex. - XST_SUCCESS on successful setting of speed. XST_FAILURE, if the speed cannot be set for the present hardware configuration. None.
References XXxvEthernet_Config::BaseAddress, XXxvEthernet::Config, XXxvEthernet::IsReady, XXxvEthernet_ReadReg, XXxvEthernet_WriteReg.
Referenced by XxvEthernetUtilUsxgmiiSetup, XxvEthernetUtilUsxgmiiSetupBypassAN.
XXxvEthernet_Config * XXxvEthernet_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
A table contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration table entry corresponding to the given device ID/BaseAddress, or NULL if no match is found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XXxvEthernet_Config::Name.
Referenced by XxvEthernetSgDmaIntrExample.
u16 XXxvEthernet_GetAutoNegSpeed(XXxvEthernet *InstancePtr)
XXxvEthernet_GetAutoNegSpeed reports the speed (only 10G supported) from the Autonegotiation status register.
InstancePtr is a pointer to the Xxv Ethernet instance to be worked on. Returns the link speed in units of gigabits per second (10) Can return a value of 0, in case 10Gbps is not set. This function is only supported for XXV Ethernet MAC
References XXxvEthernet_Config::BaseAddress, XXxvEthernet::Config, XXxvEthernet::IsReady, XXE_SPEED_10_GBPS, XXxvEthernet_ReadReg.
int XXxvEthernet_SetAutoNegSpeed(XXxvEthernet *InstancePtr)
XXxvEthernet_SetAutoNegSpeed sets the speed (only 10G supported) in the Autonegotiation control register.
InstancePtr references the Xxv Ethernet on which to operate. - XST_SUCCESS on successful setting of speed. XST_FAILURE, if the speed cannot be set for the present hardware configuration. This function is only supported for XXV Ethernet MAC
References XXxvEthernet_Config::BaseAddress, XXxvEthernet::Config, XXxvEthernet::IsReady, XXxvEthernet_WriteReg.
void XXxvEthernet_UsxgmiiAnMainReset(XXxvEthernet *InstancePtr)
XXxvEthernet_UsxgmiiAnMainReset sets the USXGMII AN Main reset.
A delay is provided in between setting and clearing the main reset bit. InstancePtr is a pointer to the Xxv Ethernet instance to be worked on. None This function is only supported for USXGMII Ethernet MAC
References XXxvEthernet_Config::BaseAddress, XXxvEthernet::Config, XXxvEthernet::IsReady, XXxvEthernet_ReadReg, XXxvEthernet_WriteReg.
void XXxvEthernet_UsxgmiiAnMainRestart(XXxvEthernet *InstancePtr)
XXxvEthernet_UsxgmiiAnMainRestart sets the USXGMII AN Main restart.
A delay is provided in between setting and clearing this bit as it is not self clearing. InstancePtr is a pointer to the Xxv Ethernet instance to be worked on. None This function is only supported for USXGMII Ethernet MAC
References XXxvEthernet_Config::BaseAddress, XXxvEthernet::Config, XXxvEthernet::IsReady, XXxvEthernet_ReadReg, XXxvEthernet_WriteReg.
Referenced by XxvEthernetUtilUsxgmiiSetup, XxvEthernetUtilUsxgmiiSetupBypassAN.
xdbg_stmnt(extern int indent_on)
XXxvEthernet_Config* XXxvEthernet_LookupConfigBaseAddr(UINTPTR BaseAddress)
XXxvEthernet_LookupConfigBaseAddr returns a reference to an XXxvEthernet_Config structure based on base address.
The return value will refer to an entry in the device configuration table defined in the xxxvethernet_g.c file. Baseaddr is the base address of the device to lookup for. Returns a reference to a config record in the configuration table (in xxxvethernet_g.c) corresponding to Baseaddr, or NULLNULL if no match is found.
References XXxvEthernet_Config::Name.
XXXVETHERNET_H
XXE_MAC_ADDR_SIZE
XXE_MTU
XXE_JUMBO_MTU
XXE_HDR_SIZE
XXE_TRL_SIZE
XXE_MAX_FRAME_SIZE
XXE_MAX_JUMBO_FRAME_SIZE
XXE_RX
XXE_TX
RATE_10M
RATE_100M
RATE_1G
RATE_2G5
RATE_10G
XXxvEthernet_IsStarted
XXxvEthernet_IsStarted reports if the device is in the started or stopped state.
To be in the started state, the calling code must have made a successful call to XXxvEthernet_Start. To be in the stopped state, XXxvEthernet_Stop or XXxvEthernet_CfgInitialize function must have been called. InstancePtr is a pointer to the of Xxv Ethernet instance to be worked on. TRUE if the device has been started.FALSE.if the device has not been started C-style signature: u32 XXxvEthernet_IsStarted(XXxvEthernet *InstancePtr)
XXxvEthernet_XxvDevBaseAddress
XXxvEthernet_XxvDevBaseAddress reports the base address of the core connected to the Xxv Ethernet's Axi4 Stream interface (expected to be MCDMA).
This function is currently not in use because of limitation in exporting target MCDMA information. InstancePtr is a pointer to the Xxv Ethernet instance to be worked on. The base address of the core connected to the Xxv Ethernet's streaming interface. C-style signature: u32 XXxvEthernet_XxvDevBaseAddress(XXxvEthernet *InstancePtr)
XXxvEthernet_IsTxErr
XXxvEthernet_IsTxErr determines if there is any TX error reported by device.
The TX status register is read for this to be determined. InstancePtr is a pointer to the Xxv Ethernet instance to be worked on. TRUE if error bit mask is setFALSE if error bit mask is not set C-style signature: u32 XXxvEthernet_IsTxErr(XXxvEthernet *InstancePtr)
XXxvEthernet_IsRxErr
XXxvEthernet_IsRxErr determines if there is any RX error reported by device.
The RX status register is read for this to be determined. InstancePtr is a pointer to the Xxv Ethernet instance to be worked on. TRUE if error bit mask is setFALSE if error bit mask is not set C-style signature: u32 XXxvEthernet_IsRxErr(XXxvEthernet *InstancePtr)
XXxvEthernet_GetStatus
XXxvEthernet_GetStatus returns the contents of status register.
InstancePtr is a pointer to the Xxv Ethernet instance to be worked on. Returns the status register. C-style signature: u32 XXxvEthernet_GetStatus(XXxvEthernet *InstancePtr)
XXxvEthernet_IsStatsConfigured
XXxvEthernet_IsStatsConfigured returns determines if Statistics gathering.
is configured in the hardware or not. InstancePtr is a pointer to the Xxv Ethernet instance to be worked on. TRUE if the device is configured with statistics gathering.FALSE if the device is NOT configured with statistics gathering. C-style signature: u32 XXxvEthernet_IsStatsConfigured(XXxvEthernet *InstancePtr)
XXxvEthernet_UsxgmiiLinkSts
XXxvEthernet_UsxgmiiLinkSts returns the USXGMII link status.
InstancePtr is a pointer to the Xxv Ethernet instance to be worked on. TRUE if link is upFALSE if link is down C-style signature: u32 XXxvEthernet_UsxgmiiLinkSts(XXxvEthernet *InstancePtr)
XXxvEthernet_SetUsxgmiiAnEnable
XXxvEthernet_SetUsxgmiiAnEnable enables USXGMII autonegotiation.
InstancePtr is a pointer to the Xxv Ethernet instance to be worked on. C-style signature: u32 XXxvEthernet_SetUsxgmiiAnEnable(XXxvEthernet *InstancePtr)
Referenced by XxvEthernetUtilUsxgmiiSetup.
XXxvEthernet_SetUsxgmiiAnBypass
XXxvEthernet_SetUsxgmiiAnBypass bypasses USXGMII autonegotiation.
InstancePtr is a pointer to the Xxv Ethernet instance to be worked on. C-style signature: u32 XXxvEthernet_SetUsxgmiiAnBypass(XXxvEthernet *InstancePtr)
Referenced by XxvEthernetUtilUsxgmiiSetupBypassAN.
XXxvEthernet_GetUsxgmiiAnSts
XXxvEthernet_GetUsxgmiiAnSts returns the contents of USXGMII autonegotiation status register.
InstancePtr is a pointer to the Xxv Ethernet instance to be worked on. C-style signature: u32 XXxvEthernet_GetUsxgmiiAnSts(XXxvEthernet *InstancePtr)
Referenced by XxvEthernetUtilUsxgmiiSetup, XxvEthernetUtilUsxgmiiSetupBypassAN.
XXxvEthernet_IsMcDma
XXxvEthernet_IsMcDma reports if the device is currently connected to MCDMA.
InstancePtr is a pointer to the Xxv Ethernet instance to be worked on. TRUE if the Xxv Ethernet device is connected MCDMA.FALSE.if the Xxv Ethernet device is NOT connected to MCDMA C-style signature: u32 XXxvEthernet_IsMcDma(XXxvEthernet *InstancePtr)
XXXVETHERNET_HW_H
XXE_STS_TX_ERROR_MASK
XXE_STS_RX_ERROR_MASK
XXxvEthernet_indent
XXxvEthernet_reg_name
XXxvEthernet_print_reg_o
XXxvEthernet_print_reg_i
XXxvEthernet_ReadReg
XXxvEthernet_ReadReg returns the value read from the register specified by RegOffset.
BaseAddress is the base address of the Xxv Ethernet device. RegOffset is the offset of the register to be read. Returns the 32-bit value of the register. C-style signature: u32 XXxvEthernet_ReadReg(u32 BaseAddress, u32 RegOffset)
Referenced by XxvEthernetUtilEnterLocalLoopback, XXxvEthernet_ClearOptions, XXxvEthernet_GetAutoNegSpeed, XXxvEthernet_SetOptions, XXxvEthernet_SetUsxgmiiRateAndDuplex, XXxvEthernet_Start, XXxvEthernet_Stop, XXxvEthernet_UsxgmiiAnMainReset, XXxvEthernet_UsxgmiiAnMainRestart.
XXxvEthernet_WriteReg
XXxvEthernet_WriteReg, writes Data to the register specified by RegOffset.
BaseAddress is the base address of the Xxv Ethernet device. RegOffset is the offset of the register to be written. Data is the 32-bit value to write to the register. None. C-style signature: void XXxvEthernet_WriteReg(u32 BaseAddress, u32 RegOffset, u32 Data)
Referenced by XxvEthernetUtilEnterLocalLoopback, XxvEthernetUtilUsxgmiiSetup, XxvEthernetUtilUsxgmiiSetupBypassAN, XXxvEthernet_ClearOptions, XXxvEthernet_SetAutoNegSpeed, XXxvEthernet_SetOptions, XXxvEthernet_SetUsxgmiiRateAndDuplex, XXxvEthernet_Start, XXxvEthernet_Stop, XXxvEthernet_UsxgmiiAnMainReset, XXxvEthernet_UsxgmiiAnMainRestart.