xxxvethernet.c
static void XXxvEthernet_InitHw(XXxvEthernet *InstancePtr)
int XXxvEthernet_CfgInitialize(XXxvEthernet *InstancePtr, XXxvEthernet_Config *CfgPtr, UINTPTR EffectiveAddress)
XXxvEthernet_CfgInitialize initializes an XXV Ethernet device along with the InstancePtr that references it.
InstancePtr references the memory instance to be associated with the XXV Ethernet core instance upon initialization. CfgPtr references the structure holding the hardware configuration for the Xxv Ethernet core to initialize. EffectiveAddress is the processor address used to access the base address of the XXV Ethernet instance. In systems with an MMU and virtual memory, EffectiveAddress is the virtual address mapped to the physical in ConfigPtr->Config.BaseAddress. In systems without an active MMU, EffectiveAddress should be set to the same value as ConfigPtr->Config.BaseAddress. XST_SUCCESS None.
References XXxvEthernet_Config::BaseAddress, XXxvEthernet::Config, XXxvEthernet::IsReady, XXxvEthernet_Reset.
Referenced by XxvEthernetSgDmaIntrExample.
int XXxvEthernet_Initialize(XXxvEthernet *InstancePtr, XXxvEthernet_Config *CfgPtr)
XXxvEthernet_Initialize initializes an XXV Ethernet device along with the InstancePtr that references it.
The PHY is setup independently from the Ethernet core. Use the MII or whatever other interface may be present for setup. InstancePtr references the memory instance to be associated with the AXI Ethernet core instance upon initialization. CfgPtr references the structure holding the hardware configuration for the Axi Ethernet core to initialize. XST_SUCCESS. When user calls this function he should ensure the hardware is in a quiescent state by resetting all the hardware Configurations.
References XXxvEthernet_Config::BaseAddress, XXxvEthernet::Config, XXxvEthernet::IsReady.
int XXxvEthernet_Start(XXxvEthernet *InstancePtr)
XXxvEthernet_Start starts the Xxv Ethernet device as follows:
- Enable transmitter if XXE_TRANSMIT_ENABLE_OPTION is set - Enable receiver if XXE_RECEIVER_ENABLE_OPTION is set - Upon enabling RX, check for RX BLOCK LOCK bit to make sure RX channel is ready. InstancePtr is a pointer to the Xxv Ethernet instance to be worked on. XST_FAILURE if RX is enabled and BLOCK LOCK is not set. None
References XXxvEthernet_Config::BaseAddress, XXxvEthernet::Config, XXxvEthernet::IsReady, XXxvEthernet::IsStarted, XXxvEthernet::Options, XXE_TRANSMITTER_ENABLE_OPTION, XXxvEthernet_ReadReg, XXxvEthernet_WriteReg.
Referenced by XxvEthernetSgDmaIntrSingleFrameExample.
void XXxvEthernet_Stop(XXxvEthernet *InstancePtr)
XXxvEthernet_Stop gracefully stops the Xxv Ethernet device by disabling the receiver.
XXxvEthernet_Stop does not modify any of the current device options.Since the transmitter is not disabled, frames currently in internal buffers or in process by a DMA engine are allowed to be transmitted. InstancePtr is a pointer to the Xxv Ethernet instance to be worked on. None None.
References XXxvEthernet_Config::BaseAddress, XXxvEthernet::Config, XXxvEthernet::IsReady, XXxvEthernet::IsStarted, XXxvEthernet_ReadReg, XXxvEthernet_WriteReg.
Referenced by XxvEthernetSgDmaIntrExample, XxvEthernetSgDmaIntrSingleFrameExample, XXxvEthernet_Reset.
void XXxvEthernet_Reset(XXxvEthernet *InstancePtr)
XXxvEthernet_Reset does not perform a soft reset of the XxvEthernet core.
XxvEthernet hardware is reset by the device connected to the AXI4-Stream interface i.e. MCDMA. This function simply disabled TX and RX. This function inserts some delay before proceeding to stop the device. InstancePtr is a pointer to the Xxv Ethernet instance to be worked on. None
References XXxvEthernet::IsReady, XXxvEthernet::Options, XXE_DEFAULT_OPTIONS, XXE_LOOPS_TO_COME_OUT_OF_RST, XXxvEthernet_Stop.
Referenced by XXxvEthernet_CfgInitialize.
int XXxvEthernet_SetOptions(XXxvEthernet *InstancePtr, u32 Options)
XXxvEthernet_SetOptions enables the options, Options for the Xxv Ethernet, specified by InstancePtr.
Xxv Ethernet should be stopped with XXxvEthernet_Stop() before changing options. InstancePtr is a pointer to the Xxv Ethernet instance to be worked on. Options is a bitmask of OR'd XXE_*_OPTION values for options to set. Options not specified are not affected. XST_SUCCESS on successful completion.XST_DEVICE_IS_STARTED if the device has not been stopped. See xxxvethernet.h for a description of the available options.
References XXxvEthernet_Config::BaseAddress, XXxvEthernet::Config, XXxvEthernet::IsReady, XXxvEthernet::IsStarted, XXxvEthernet::Options, XXE_DEFAULT_OPTIONS, XXE_FCS_INSERT_OPTION, XXE_FCS_STRIP_OPTION, XXE_TRANSMITTER_ENABLE_OPTION, XXxvEthernet_ReadReg, XXxvEthernet_WriteReg.
Referenced by XxvEthernetUtilUsxgmiiSetup, XxvEthernetUtilUsxgmiiSetupBypassAN.
int XXxvEthernet_ClearOptions(XXxvEthernet *InstancePtr, u32 Options)
XXxvEthernet_ClearOptions clears the options, Options for the Xxv Ethernet, specified by InstancePtr.
Xxv Ethernet should be stopped with XXxvEthernet_Stop() before changing options. InstancePtr is a pointer to the Xxv Ethernet instance to be worked on. Options is a bitmask of OR'd XXE_*_OPTION values for options to clear. Options not specified are not affected. XST_SUCCESS on successful completion.XST_DEVICE_IS_STARTED if the device has not been stopped. See xxxvethernet.h for a description of the available options.
References XXxvEthernet_Config::BaseAddress, XXxvEthernet::Config, XXxvEthernet::IsReady, XXxvEthernet::IsStarted, XXxvEthernet::Options, XXE_FCS_INSERT_OPTION, XXE_FCS_STRIP_OPTION, XXE_TRANSMITTER_ENABLE_OPTION, XXxvEthernet_ReadReg, XXxvEthernet_WriteReg.
u32 XXxvEthernet_GetOptions(XXxvEthernet *InstancePtr)
XXxvEthernet_GetOptions returns the current option settings.
InstancePtr is a pointer to the Xxv Ethernet instance to be worked on. Returns a bitmask of XXE_*_OPTION constants, each bit specifying an option that is currently active. See xxxvethernet.h for a description of the available options.
References XXxvEthernet::IsReady, XXxvEthernet::Options.
int XXxvEthernet_SetUsxgmiiRateAndDuplex(XXxvEthernet *InstancePtr, u32 Rate, u32 SetFD)
XXxvEthernet_SetUsxgmiiRateAndDuplex sets the speed and duplex ability in USXGMII Autonegotiation register.
InstancePtr references the Xxv Ethernet on which to operate. Rate to be set - currently only 1G and 2.5G are tested. Pass RATE_1G or RATE_2G5 to the function. Set FD or HD - if 0 Half duplex is set, else Full duplex. - XST_SUCCESS on successful setting of speed. XST_FAILURE, if the speed cannot be set for the present hardware configuration. None.
References XXxvEthernet_Config::BaseAddress, XXxvEthernet::Config, XXxvEthernet::IsReady, XXxvEthernet_ReadReg, XXxvEthernet_WriteReg.
Referenced by XxvEthernetUtilUsxgmiiSetup, XxvEthernetUtilUsxgmiiSetupBypassAN.
void XXxvEthernet_UsxgmiiAnMainReset(XXxvEthernet *InstancePtr)
XXxvEthernet_UsxgmiiAnMainReset sets the USXGMII AN Main reset.
A delay is provided in between setting and clearing the main reset bit. InstancePtr is a pointer to the Xxv Ethernet instance to be worked on. None This function is only supported for USXGMII Ethernet MAC
References XXxvEthernet::IsReady, XXxvEthernet_ReadReg, XXxvEthernet::Config, XXxvEthernet_Config::BaseAddress, XXxvEthernet_WriteReg.
void XXxvEthernet_UsxgmiiAnMainRestart(XXxvEthernet *InstancePtr)
XXxvEthernet_UsxgmiiAnMainRestart sets the USXGMII AN Main restart.
A delay is provided in between setting and clearing this bit as it is not self clearing. InstancePtr is a pointer to the Xxv Ethernet instance to be worked on. None This function is only supported for USXGMII Ethernet MAC
References XXxvEthernet::IsReady, XXxvEthernet_ReadReg, XXxvEthernet::Config, XXxvEthernet_Config::BaseAddress, XXxvEthernet_WriteReg.
Referenced by XxvEthernetUtilUsxgmiiSetup, XxvEthernetUtilUsxgmiiSetupBypassAN.
u16 XXxvEthernet_GetAutoNegSpeed(XXxvEthernet *InstancePtr)
XXxvEthernet_GetAutoNegSpeed reports the speed (only 10G supported) from the Autonegotiation status register.
InstancePtr is a pointer to the Xxv Ethernet instance to be worked on. Returns the link speed in units of gigabits per second (10) Can return a value of 0, in case 10Gbps is not set. This function is only supported for XXV Ethernet MAC
References XXxvEthernet::IsReady, XXxvEthernet_ReadReg, XXxvEthernet::Config, XXxvEthernet_Config::BaseAddress, XXE_SPEED_10_GBPS.
int XXxvEthernet_SetAutoNegSpeed(XXxvEthernet *InstancePtr)
XXxvEthernet_SetAutoNegSpeed sets the speed (only 10G supported) in the Autonegotiation control register.
InstancePtr references the Xxv Ethernet on which to operate. - XST_SUCCESS on successful setting of speed. XST_FAILURE, if the speed cannot be set for the present hardware configuration. This function is only supported for XXV Ethernet MAC
References XXxvEthernet::IsReady, XXxvEthernet_WriteReg, XXxvEthernet::Config, XXxvEthernet_Config::BaseAddress.