xasu_rsa_common_apis
s32 XAsu_RsaValidateInputParams(const XAsu_RsaParams *RsaParamsPtr)
This function validates input parameters that are common to all RSA padding algorithms.
RsaParamsPtr Pointer to XAsu_RsaParams structure that holds the input parameters for RSA. XST_SUCCESS, if input validation is successful.XST_FAILURE, if input validation fails.
References XAsu_RsaParams::InputDataAddr, XAsu_RsaParams::KeyCompAddr, XAsu_RsaParams::KeyId, XAsu_KmValidateKeyAddrNdKeyId.
Referenced by XAsu_RsaCrtDec, XAsu_RsaDec, XAsu_RsaEnc, XAsu_RsaOaepDec, XAsu_RsaOaepEnc, XAsu_RsaPssSignGen, XAsu_RsaPssSignVer.