xasu_ocp_common_apis
s32 XAsu_OcpValidateCertParams(const XAsu_OcpCertParams *OcpCertParam)
This function validates the OCP certificate parameters.
OcpCertParam Pointer to XAsu_OcpCertParams structure which holds the parameters of OCP input argument. XST_SUCCESS, if OCP certificate parameters are validated successfully.XST_FAILURE, if OCP certificate parameters validation is failed.
References XAsu_OcpCertParams::CertActualSize, XAsu_OcpCertParams::CertBufAddr, XAsu_OcpCertParams::CertBufLen, XAsu_OcpCertParams::DevKeySel, XOCP_MAX_DEVICE_KEY.
Referenced by XAsu_OcpGetDevAkX509Certificate, XAsu_OcpGetDevIkCsr, XAsu_OcpGetDevIkX509Certificate.
s32 XAsu_OcpValidateAttestParams(const XAsu_OcpDevAkAttest *OcpAttestParam)
This function validates the OCP DevAk attestation parameters.
OcpAttestParam Pointer to XAsu_OcpDevAkAttest Params structure which holds the parameters of OCP attestation input argument. XST_SUCCESS, if OCP attestation parameters are validated successfully.XST_FAILURE, if OCP attestation parameters validation is failed.
References XAsu_OcpDevAkAttest::DataAddr, XAsu_OcpDevAkAttest::DataLen, XAsu_OcpDevAkAttest::SignatureAddr, XAsu_OcpDevAkAttest::SignatureBufLen, XASU_ECC_P384_PVT_KEY_SIZE_IN_BYTES.
Referenced by XAsu_OcpDevAkAttestation.