xasu_ecies_common_apis
s32 XAsu_ValidateEciesParameters(const XAsu_EciesParams *EciesParams)
This function validates the input parameters for ECIES.
EciesParams Pointer to XAsu_EciesParams structure that holds the input parameters for ECIES. XST_SUCCESS, if ECIES input parameters validation is successful.XST_FAILURE, if ECIES input parameters validation fails.
References XAsu_EciesParams::AesKeySize, XAsu_EciesParams::ContextAddr, XAsu_EciesParams::ContextLen, XAsu_EciesParams::DataLength, XAsu_EciesParams::EccCurveType, XAsu_EciesParams::EccKeyLength, XAsu_EciesParams::InDataAddr, XAsu_EciesParams::IvAddr, XAsu_EciesParams::IvLength, XAsu_EciesParams::MacAddr, XAsu_EciesParams::MacLength, XAsu_EciesParams::OutDataAddr, XAsu_EciesParams::RxKeyAddr, XAsu_EciesParams::ShaMode, XAsu_EciesParams::ShaType, XAsu_EciesParams::TxKeyAddr, XASU_AES_IV_SIZE_96BIT_IN_BYTES, XASU_AES_KEY_SIZE_128_BITS, XASU_AES_KEY_SIZE_256_BITS, XASU_AES_MAX_TAG_LENGTH_IN_BYTES, XASU_ASU_DMA_MAX_TRANSFER_LENGTH, XAsu_EccValidateCurveInfo, XASU_KDF_MAX_CONTEXT_LEN.
Referenced by XAsu_EciesDecrypt, XAsu_EciesEncrypt.
s32 XAsu_EccValidateCurveInfo(u32 CurveType, u32 CurveLen)
This function validates the given ECC curve type and curve length.
CurveType Curve type provided. CurveLen Curve length provided. XST_SUCCESS, if curve type is valid.XST_FAILURE, if curve length is invalid.
References XASU_ECC_BRAINPOOL_P256, XASU_ECC_BRAINPOOL_P320, XASU_ECC_BRAINPOOL_P384, XASU_ECC_BRAINPOOL_P512, XASU_ECC_CURVE25519, XASU_ECC_CURVE448, XASU_ECC_CURVE448_PVT_KEY_SIZE_IN_BYTES, XASU_ECC_ED448_PVT_KEY_SIZE_IN_BYTES, XASU_ECC_NIST_ED25519, XASU_ECC_NIST_ED25519_PH, XASU_ECC_NIST_ED448, XASU_ECC_NIST_ED448_PH, XASU_ECC_NIST_P192, XASU_ECC_NIST_P224, XASU_ECC_NIST_P256, XASU_ECC_NIST_P384, XASU_ECC_NIST_P521, XASU_ECC_P192_PVT_KEY_SIZE_IN_BYTES, XASU_ECC_P224_PVT_KEY_SIZE_IN_BYTES, XASU_ECC_P256_PVT_KEY_SIZE_IN_BYTES, XASU_ECC_P320_PVT_KEY_SIZE_IN_BYTES, XASU_ECC_P384_PVT_KEY_SIZE_IN_BYTES, XASU_ECC_P512_PVT_KEY_SIZE_IN_BYTES, XASU_ECC_P521_PVT_KEY_SIZE_IN_BYTES.
Referenced by XAsu_EccValidatePubKey, XAsu_KmGenerateEccKeyPair, XAsu_ValidateEciesParameters.