xasu_keymanager_common.h
XASU_KM_AES_KEYTYPE
Key type identifier for AES key.
Referenced by XAsu_KmGenerateAesKey, XAsu_KmValidateKeyLength.
XASU_KM_IV_KEYTYPE
Key type identifier for IV.
Referenced by XAsu_KmGenerateAesIv, XAsu_KmValidateKeyLength.
XASU_KM_KDF_HMAC_KEYTYPE
Key type identifier for KDF/HMAC key.
Referenced by XAsu_KmGenerateRawKey, XAsu_KmValidateKeyLength.
XASU_KM_RSA_KEYTYPE
Key type identifier for RSA key.
Referenced by XAsu_KmGenerateRsaKeyPair, XAsu_KmValidateKeyLength.
XASU_KM_ACCESS_RIGHTS_LOWER_BYTE_MASK
Mask to extract lower byte of AccessRights.
XASU_KM_ACCESS_RIGHTS_UPPER_BYTE_SHIFT
Shift to extract upper byte of AccessRights.
XASU_KEYMANAGER_NON_EXPORTABLE_VAULT
Non-exportable vault value.
Referenced by XAsu_KmValidateVaultCreateParams.
XASU_KEYMANAGER_EXPORTABLE_VAULT
Exportable vault value.
Referenced by XAsu_KmValidateVaultCreateParams.
XASU_IS_REDUNDANT_BYTE_VALID
Check if lower byte and upper byte of AccessRights are same.
Referenced by XAsu_KmCreateKeyVault.
s32 XAsu_KmValidateVaultParams(const XAsu_KeyManagerParams *KmParamsPtr)
This function validates input parameters for keymanager.
KmParamsPtr Pointer to XAsu_KeyManagerParams structure that holds the input parameters for Key manager XST_SUCCESS, if input validation is successful.XST_FAILURE, if input validation fails.
References XAsu_KeyManagerParams::KeyIdAddr, XAsu_KeyManagerParams::KeyMetadata, XAsu_KeyManagerParams::KeyObjectAddr, XAsu_KmValidateKeyAddrNdKeyId, XAsu_KmValidateKeyMetadata.
Referenced by XAsu_KmGenerateAesIv, XAsu_KmGenerateAesKey, XAsu_KmGenerateEccKeyPair, XAsu_KmGenerateRawKey, XAsu_KmGenerateRsaKeyPair.
s32 XAsu_KmValidateKeyMetadata(const XAsu_KeyManagerKeyMetadata *MetadataPtr)
This function validates key metadata fields.
MetadataPtr Pointer to XAsu_KeyManagerKeyMetadata structure. XST_SUCCESS, if metadata validation is successful.XST_FAILURE, if metadata validation fails.
References XAsu_KeyManagerKeyMetadata::KeyUseCase, XAsu_KeyManagerKeyMetadata::UsageCount, XAsu_KeyManagerKeyMetadata::VaultId, XASU_KM_MAX_VAULTS.
Referenced by XAsu_KmStoreKey, XAsu_KmValidateVaultParams.
s32 XAsu_KmValidateKeyLength(u32 KeyLength, u8 KeyType)
This function validates key length parameters for a given key.
KeyLength Length of the key material in bytes. KeyType Type of key to be validated (see XASU_KM_*_KEYTYPE). XST_SUCCESS, if input validation is successful.XST_FAILURE, if input validation fails.
References XASU_AES_IV_SIZE_128BIT_IN_BYTES, XASU_AES_KEY_SIZE_128BIT_IN_BYTES, XASU_AES_KEY_SIZE_256BIT_IN_BYTES, XASU_KM_AES_KEYTYPE, XASU_KM_IV_KEYTYPE, XASU_KM_KDF_HMAC_KEYTYPE, XASU_KM_KDF_HMAC_MAX_KEY_LENGTH, XASU_KM_RSA_KEYTYPE, XRSA_2048_KEY_SIZE, XRSA_3072_KEY_SIZE, XRSA_4096_KEY_SIZE.
Referenced by XAsu_KmGenerateAesIv, XAsu_KmGenerateAesKey, XAsu_KmGenerateRawKey, XAsu_KmGenerateRsaKeyPair.
s32 XAsu_KmValidateKeyAddrNdKeyId(u64 KeyCompAddr, u32 KeyId)
This function validates that exactly one of KeyCompAddr or KeyId is provided.
KeyCompAddr Address of the key component structure. KeyId Composite key identifier for vault-based key retrieval. XST_SUCCESS, if exactly one of (KeyCompAddr, KeyId) is non-zero.XST_FAILURE, if both are zero (no source) or both are non-zero (ambiguous source).
Referenced by XAsu_AesOperation, XAsu_HmacSha3Kat, XAsu_KeyWrapUnwrapValidateInputParams, XAsu_KmValidateVaultParams, XAsu_LmsValidateParams, XAsu_RsaValidateInputParams, XAsu_ValidateKdfParameters.
s32 XAsu_KmValidateVaultCreateParams(const XAsu_KeyManagerSubVaultParams *ParamsPtr)
This function validates input parameters for key vault creation.
ParamsPtr Pointer to XAsu_KeyManagerSubVaultParams structure that holds the input parameters for Key manager. XST_SUCCESS, if input validation is successful.XST_FAILURE, if input validation fails.
References XAsu_KeyManagerSubVaultParams::AESKeyVaultCapacity, XAsu_KeyManagerSubVaultParams::ECCPubKeyVaultCapacity, XAsu_KeyManagerSubVaultParams::ECCPvtKeyVaultCapacity, XAsu_KeyManagerSubVaultParams::IVVaultCapacity, XAsu_KeyManagerSubVaultParams::KDFHmacKeyVaultCapacity, XAsu_KeyManagerSubVaultParams::LMSKeyVaultCapacity, XAsu_KeyManagerSubVaultParams::Restrictions, XAsu_KeyManagerSubVaultParams::RSAPubKeyVaultCapacity, XAsu_KeyManagerSubVaultParams::RSAPvtKeyVaultCapacity, XAsu_KeyManagerSubVaultParams::X509KeyVaultCapacity, XASU_KEYMANAGER_EXPORTABLE_VAULT, XASU_KEYMANAGER_NON_EXPORTABLE_VAULT.
Referenced by XAsu_KmCreateKeyVault.