xasu_client.c
XASU_QUEUE_BUFFER_FULL
To indicate queue full state.
XASU_CLIENT_READY
To indicate Client is ready.
XASU_TARGET_IPI_INT_MASK
ASU IPI interrupt mask.
XASU_ASUFW_BIT_CHECK_TIMEOUT_VALUE
ASUFW check timeout value.
XASU_KAT_EXEC_STATUS_CHECK_TIMEOUT_VALUE
KAT execution status check timeout value in microseconds (5sec)
XASU_NO_OF_CONTEXTS
No of contexts can be saved by client.
XASU_INITIAL_CALL_COUNT
Initial count for multi-update requests.
XASU_INVALID_UNIQUE_ID_VAL
Invalid unique id value.
XAsu_RefToCallBack AsuCallBackRef[XASU_UNIQUE_ID_MAX][XASU_UNIQUE_ID_MAX]
Entry of callback info.
XAsu_ClientCtx AsuContext[XASU_NO_OF_CONTEXTS][XASU_NO_OF_CONTEXTS]
ASU Context with initial UniqueId value as XASU_INVALID_UNIQUE_ID_VAL for all contexts
static XAsu_Client * XAsu_GetClientInstance(void)
This function returns an instance pointer of ASU client interface.
Pointer to the client instance.
static s32 XAsu_SendIpi(void)
This function sends an IPI request to ASU.
XST_SUCCESS, if the IPI is sent successfully.XST_FAILURE, if there is a failure.
static void XAsu_DoorBellToClient(void *CallBackRef)
This function polls for the response from ASUFW.
CallBackRef Callback reference pointer.
static s32 XAsu_CheckAsufwPrsntBit(void)
This function returns the ASUFW application's present status.
XST_SUCCESS, if ASUFW is present.XST_FAILURE, if ASUFW is not present.
static u8 XAsu_GenerateUniqueId(void)
This function generates a unique ID for client requests.
The client library assigns a unique ID to each request, ensuring distinct identification. This ID is used to map the application's response handlers, which are invoked when the corresponding response IPI interrupt is received from ASUFW.Unique ID 0 to (XASU_UNIQUE_ID_MAX-1) if AsuCallBackRef array has any empty index.XASU_UNIQUE_ID_MAX upon no free space is left
static u8 XAsu_GetFreeIndex(u8 Priority)
This function gets the free index of selected priority queue buffer.
Priority Select the queue priority. Free Index of the Channel queue buffer of the selected priority 0 to 7XASU_MAX_BUFFERS, if no index is free
s32 XAsu_ClientInit(XMailbox *MailboxInstancePtr)
This function initializes the client instance.
MailboxInstancePtr Pointer to the Mailbox instance. XST_SUCCESS, On successful initialization.XST_FAILURE, On failure.
Referenced by main.
s32 XAsu_ValidateClientParameters(XAsu_ClientParams *ClientParamPtr)
This function validates the input client parameters.
ClientParamPtr Pointer to the XAsu_ClientParams instance. XST_SUCCESS, if client parameters validation is successful.XASU_INVALID_ARGUMENT, if the input parameters are invalid. XASU_INVALID_CLIENT_PARAM, if ClientParamPtr is NULL.XASU_INVALID_CALL_BACK_REF, if CallBackFuncPtr is NULL.XASU_INVALID_PRIORITY, if invalid priority is selected.
References XASU_INVALID_CLIENT_PARAM.
Referenced by XAsu_AesKat, XAsu_AesOperation, XAsu_CmacKdfGenerate, XAsu_EccGenPubKey, XAsu_EccGenSign, XAsu_EccKat, XAsu_EccValidatePubKey, XAsu_EccVerifySign, XAsu_EcdhGenSharedSecret, XAsu_EcdhKat, XAsu_EciesDecrypt, XAsu_EciesEncrypt, XAsu_EciesKat, XAsu_HKdfGenerate, XAsu_HmacCompute, XAsu_HmacKat, XAsu_HssSignVerify, XAsu_HssSignVerifyKat, XAsu_KdfGenerate, XAsu_KdfKat, XAsu_KeyUnwrap, XAsu_KeyWrap, XAsu_KeyWrapKat, XAsu_KmCreateKeyVault, XAsu_KmDeleteKey, XAsu_KmDeleteKeyVault, XAsu_KmExportKeyVault, XAsu_KmGenerateAesIv, XAsu_KmGenerateAesKey, XAsu_KmGenerateEccKeyPair, XAsu_KmGenerateRawKey, XAsu_KmGenerateRsaKeyPair, XAsu_KmImportKeyVault, XAsu_KmStoreKey, XAsu_LmsSignVerify, XAsu_OcpDevAkAttestation, XAsu_OcpGetDevAkX509Certificate, XAsu_OcpGetDevIkCsr, XAsu_OcpGetDevIkX509Certificate, XAsu_OcpGetHuk, XAsu_OcpUdeChallengeReq, XAsu_OcpUdeKeysEncrypt, XAsu_RsaCrtDec, XAsu_RsaDec, XAsu_RsaEnc, XAsu_RsaOaepDec, XAsu_RsaOaepEnc, XAsu_RsaOaepEncDecKat, XAsu_RsaPssSignGen, XAsu_RsaPssSignGenAndVerKat, XAsu_RsaPssSignVer, XAsu_Sha2Kat, XAsu_Sha2Operation, XAsu_Sha3Kat, XAsu_Sha3Operation, XAsu_TrngGetRandomNum, XAsu_TrngKat.
s32 XAsu_SendCmdToAsu(XAsu_ClientParams *ClientParam, void *ReqBuffer, u32 Size, u32 Header)
This function updates the queue buffer status to notify the request is present and generates a doorbell to ASU.
ClientParam Pointer to the XAsu_ClientParams instance. ReqBuffer Pointer to the XAsu_ChannelQueueBuf's Request buffer data to be filled. Size Size of the request buffer in bytes. Header Header of the request buffer to be filled. XST_SUCCESS, if IPI is sent successfully.XST_FAILURE, if there is any failure.XASU_INVALID_ARGUMENT, if the input parameters are invalid.
Referenced by XAsu_AesKat, XAsu_AesOperation, XAsu_CmacKdfGenerate, XAsu_EccGenPubKey, XAsu_EccGenSign, XAsu_EccKat, XAsu_EccValidatePubKey, XAsu_EccVerifySign, XAsu_EcdhGenSharedSecret, XAsu_EcdhKat, XAsu_EciesDecrypt, XAsu_EciesEncrypt, XAsu_EciesKat, XAsu_HKdfGenerate, XAsu_HmacCompute, XAsu_HmacKat, XAsu_HssSignVerify, XAsu_HssSignVerifyKat, XAsu_KdfGenerate, XAsu_KdfKat, XAsu_KeyUnwrap, XAsu_KeyWrap, XAsu_KeyWrapKat, XAsu_KmCreateKeyVault, XAsu_KmDeleteKey, XAsu_KmDeleteKeyVault, XAsu_KmExportKeyVault, XAsu_KmGenerateAesIv, XAsu_KmGenerateAesKey, XAsu_KmGenerateEccKeyPair, XAsu_KmGenerateRawKey, XAsu_KmGenerateRsaKeyPair, XAsu_KmImportKeyVault, XAsu_KmStoreKey, XAsu_LmsSignVerify, XAsu_OcpDevAkAttestation, XAsu_OcpGetDevAkX509Certificate, XAsu_OcpGetDevIkCsr, XAsu_OcpGetDevIkX509Certificate, XAsu_OcpGetHuk, XAsu_OcpUdeChallengeReq, XAsu_OcpUdeKeysEncrypt, XAsu_RsaCrtDec, XAsu_RsaDec, XAsu_RsaEnc, XAsu_RsaOaepDec, XAsu_RsaOaepEnc, XAsu_RsaOaepEncDecKat, XAsu_RsaPssSignGen, XAsu_RsaPssSignGenAndVerKat, XAsu_RsaPssSignVer, XAsu_Sha2Kat, XAsu_Sha2Operation, XAsu_Sha3Kat, XAsu_Sha3Operation, XAsu_TrngGetRandomNum, XAsu_TrngKat.
u8 XAsu_RegCallBackNGetUniqueId(XAsu_ClientParams *ClientParamPtr, u8 *RespBufferPtr, u32 Size, u8 IsFinalCall)
This function registers callback parameters across the generated unique ID per request.
ClientParamPtr Pointer to the XAsu_ClientParams structure which holds the client input arguments. RespBufferPtr Buffer to hold the response from response buffer, if no data is part of response buffer for the request the value shall be NULL. Size Size of the data to be filled in response buffer. IsFinalCall Flag indicating whether this is the final callback (1 if final, 0 otherwise). Unique ID used for registration (valid values are 0 to (XASU_UNIQUE_ID_MAX - 1)).XASU_UNIQUE_ID_MAX, if unique ID is unavailable.
Referenced by XAsu_AesKat, XAsu_CmacKdfGenerate, XAsu_EccGenPubKey, XAsu_EccGenSign, XAsu_EccKat, XAsu_EccValidatePubKey, XAsu_EccVerifySign, XAsu_EcdhGenSharedSecret, XAsu_EcdhKat, XAsu_EciesDecrypt, XAsu_EciesEncrypt, XAsu_EciesKat, XAsu_HandleContextOperation, XAsu_HKdfGenerate, XAsu_HmacKat, XAsu_HssSignVerify, XAsu_HssSignVerifyKat, XAsu_KdfGenerate, XAsu_KdfKat, XAsu_KeyUnwrap, XAsu_KeyWrap, XAsu_KeyWrapKat, XAsu_KmCreateKeyVault, XAsu_KmDeleteKey, XAsu_KmDeleteKeyVault, XAsu_KmExportKeyVault, XAsu_KmGenerateAesIv, XAsu_KmGenerateAesKey, XAsu_KmGenerateEccKeyPair, XAsu_KmGenerateRawKey, XAsu_KmGenerateRsaKeyPair, XAsu_KmImportKeyVault, XAsu_KmStoreKey, XAsu_LmsSignVerify, XAsu_OcpDevAkAttestation, XAsu_OcpGetDevAkX509Certificate, XAsu_OcpGetDevIkCsr, XAsu_OcpGetDevIkX509Certificate, XAsu_OcpGetHuk, XAsu_OcpUdeChallengeReq, XAsu_OcpUdeKeysEncrypt, XAsu_RsaCrtDec, XAsu_RsaDec, XAsu_RsaEnc, XAsu_RsaOaepDec, XAsu_RsaOaepEnc, XAsu_RsaOaepEncDecKat, XAsu_RsaPssSignGen, XAsu_RsaPssSignGenAndVerKat, XAsu_RsaPssSignVer, XAsu_Sha2Kat, XAsu_Sha3Kat, XAsu_TrngGetRandomNum, XAsu_TrngKat.
s32 XAsu_UpdateCallBackDetails(u8 UniqueId, u8 *RespBufferPtr, u32 Size, u8 IsFinalCall)
Updates callback details based on the provided unique ID, response buffer, size, and final call flag.
UniqueId Unique identifier for the callback update. RespBufferPtr Pointer to the response buffer containing the data. Size Size of the response buffer. IsFinalCall Flag indicating whether this is the final callback (1 if final, 0 otherwise). XST_SUCCESS, if callback details are updated successfully.XST_FAILURE, in case of failure.
Referenced by XAsu_CleanupFinishOperation.
s32 XAsu_GetModuleInfo(XAsu_CryptoAlgInfo *AlginfoPtr, u32 ModuleId)
This function fetches the algorithm information based on Module ID and populates the algorithm information structure.
AlginfoPtr Pointer to the structure where the algorithm information of module will be stored. ModuleId Registered ID of the module. XST_SUCCESS, if version info is updated successfully. XST_FAILURE, if version info update fails.XASU_KAT_EXEC_NOT_COMPLETED, if KAT execution is not completed. XASU_INVALID_ARGUMENT, if any argument is invalid.
References XASU_INVALID_ARGUMENT.
s32 XAsu_FreeCtx(void *Context)
Frees the memory associated with the provided context.
Context Pointer to the XAsu_ClientCtx to be freed. XST_SUCCESS, if the context is freed successfully.XASU_FREE_CTX_FAIL, if freeing the context fails.
Referenced by XAsu_CleanupFinishOperation.
void * XAsu_UpdateNGetCtx(u8 UniqueId)
Saves the provided unique ID and returns the address of the saved context.
UniqueId Unique ID associated with the request Pointer of the XAsu_ClientCtx, which references the saved context.
Referenced by XAsu_HandleContextOperation.
s32 XAsu_VerifyNGetUniqueIdCtx(const void *Context, u8 *UniqueId)
Validates the provided context by comparing it with stored contexts to determine the appropriate multi-update calls.
Context Pointer to the XAsu_ClientCtx reference context. UniqueId Pointer to the buffer where the corresponding Unique ID will be stored. XST_SUCCESS if validation is successful.XASU_INVALID_CLIENT_CTX if the provided context is not found.
s32 XAsu_HandleContextOperation(XAsu_ClientParams *ClientParamPtr, void **P0CtxPtr, void **P1CtxPtr, u32 OperationFlags, u8 *UniqueIdPtr)
Handles INIT or UPDATE/FINAL operations for multi-part cryptographic operations with priority-based context management.
ClientParamPtr Pointer to XAsu_ClientParams structure with priority information. P0CtxPtr Pointer to HIGH priority (P0) context. P1CtxPtr Pointer to LOW priority (P1) context. OperationFlags Current operation flags (combination of XASU_INIT, XASU_UPDATE, XASU_FINISH) from the client request. UniqueIdPtr Pointer to store the generated or retrieved Unique ID. XST_SUCCESS, if operation is successful.XASU_INVALID_PRIORITY, if the priority in ClientParamPtr is invalid.XASU_INVALID_UNIQUE_ID, if generated Unique ID is invalid.XASU_REQUEST_INPROGRESS, if a multi-part request is already in progress.XASU_FAIL_SAVE_CTX, if context save fails.XASU_CLIENT_CTX_NOT_CREATED, if client context does not exist.
References XASU_FAIL_SAVE_CTX, XASU_FALSE, XASU_FINISH, XASU_INVALID_PRIORITY, XASU_INVALID_UNIQUE_ID, XASU_PRIORITY_HIGH, XASU_PRIORITY_LOW, XAsu_RegCallBackNGetUniqueId, XASU_REQUEST_INPROGRESS, XASU_TRUE, XAsu_UpdateNGetCtx.
Referenced by XAsu_AesOperation, XAsu_HmacCompute, XAsu_Sha2Operation, XAsu_Sha3Operation.
s32 XAsu_CleanupFinishOperation(XAsu_ClientParams *ClientParamPtr, void **P0CtxPtr, void **P1CtxPtr, u8 UniqueId, u8 *ResponseBuffer, u32 ResponseSize)
Cleans up context and updates callback details when a FINISH/FINAL operation is executed.
ClientParamPtr Pointer to XAsu_ClientParams structure. P0CtxPtr HIGH priority (P0) context. P1CtxPtr LOW priority (P1) context. UniqueId Unique ID associated with this operation. ResponseBuffer Pointer to response buffer address (can be NULL). ResponseSize Size of the response buffer. XST_SUCCESS, if cleanup is successful.Error code from callback update or context free.
References XAsu_FreeCtx, XASU_TRUE, XAsu_UpdateCallBackDetails.
Referenced by XAsu_AesOperation, XAsu_HmacCompute, XAsu_Sha2Operation, XAsu_Sha3Operation.