emaclite
typedef void(* XEmacLite_Handler)(void *CallBackRef))(void *CallBackRef)
XEmacLite_Config XEmacLite_ConfigTable[XPAR_XEMACLITE_NUM_INSTANCES][XPAR_XEMACLITE_NUM_INSTANCES]
This table contains configuration information for each EmacLite device in the system.
XEmacLite_Config XEmacLite_ConfigTable[][]
This table contains configuration information for each EmacLite device in the system.
XEmacLite_Config XEmacLite_ConfigTable[][]
This table contains configuration information for each EmacLite device in the system.
static u16 XEmacLite_GetReceiveDataLength(UINTPTR BaseAddress)
Return the length of the data in the Receive Buffer.
BaseAddress contains the base address of the device. The type/length field of the frame received. None.
int XEmacLite_CfgInitialize(XEmacLite *InstancePtr, XEmacLite_Config *EmacLiteConfigPtr, UINTPTR EffectiveAddr)
Initialize a specific XEmacLite instance/driver.
The initialization entails: Initialize fields of the XEmacLite instance structure. The driver defaults to polled mode operation. InstancePtr is a pointer to the XEmacLite instance. EmacLiteConfigPtr points to the XEmacLite device configuration structure. EffectiveAddr is the device base address in the virtual memory address space. If the address translation is not used then the physical address is passed. Unexpected errors may occur if the address mapping is changed after this function is invoked. XST_SUCCESS if initialization was successful. The initialization of the PHY device is not done in this function. The user needs to use XEmacLite_PhyRead and XEmacLite_PhyWrite functions to access the PHY device.
References XEmacLite_Config::BaseAddress, XEmacLite_Config::IntrId, XEmacLite_Config::IntrParent, XEmacLite_Config::Loopback, XEmacLite_Config::MdioInclude, XEmacLite_Config::RxPingPong, StubHandler, XEmacLite_Config::TxPingPong, XEL_BUFFER_OFFSET, XEL_TSR_OFFSET, XEmacLite_WriteReg.
Referenced by EmacLiteIntrExample, EmacLiteIntrLoopbackExample, EmacLitePhyLoopbackExample, EmacLitePolledExample, EMACLiteSelfTestExample, XEmacLite_Initialize.
int XEmacLite_Send(XEmacLite *InstancePtr, u8 *FramePtr, unsigned ByteCount)
Send an Ethernet frame.
The ByteCount is the total frame size, including header. InstancePtr is a pointer to the XEmacLite instance. FramePtr is a pointer to frame. For optimal performance, a 32-bit aligned buffer should be used but it is not required, the function will align the data if necessary. ByteCount is the size, in bytes, of the frame XST_SUCCESS if data was transmitted.XST_FAILURE if buffer(s) was (were) full and no valid data was transmitted. This function call is not blocking in nature, i.e. it will not wait until the frame is transmitted.
References XEmacLite_Config::BaseAddress, XEmacLite_Config::TxPingPong, XEL_BUFFER_OFFSET, XEL_MAX_TX_FRAME_SIZE, XEL_TPLR_LENGTH_MASK_HI, XEL_TPLR_LENGTH_MASK_LO, XEL_TPLR_OFFSET, XEL_TSR_XMIT_ACTIVE_MASK, XEL_TSR_XMIT_BUSY_MASK, XEL_TSR_XMIT_IE_MASK, XEmacLite_AlignedWrite, XEmacLite_GetTxStatus, XEmacLite_NextTransmitAddr, XEmacLite_SetTxStatus, XEmacLite_WriteReg.
u16 XEmacLite_Recv(XEmacLite *InstancePtr, u8 *FramePtr)
Receive a frame.
Intended to be called from the interrupt context or with a wrapper which waits for the receive frame to be available. InstancePtr is a pointer to the XEmacLite instance. FramePtr is a pointer to a buffer where the frame will be stored. The buffer must be at least XEL_MAX_FRAME_SIZE bytes. For optimal performance, a 32-bit aligned buffer should be used but it is not required, the function will align the data if necessary. The type/length field of the frame received. When the type/length field contains the type, XEL_MAX_FRAME_SIZE bytes will be copied out of the buffer and it is up to the higher layers to sort out the frame. Function returns 0 if there is no data waiting in the receive buffer or the pong buffer if configured. This function call is not blocking in nature, i.e. it will not wait until a frame arrives.
References XEmacLite_Config::RxPingPong, XEL_ARP_PACKET_SIZE, XEL_BUFFER_OFFSET, XEL_ETHER_PROTO_TYPE_ARP, XEL_ETHER_PROTO_TYPE_IP, XEL_FCS_SIZE, XEL_HEADER_IP_LENGTH_OFFSET, XEL_HEADER_SHIFT, XEL_HEADER_SIZE, XEL_MAX_FRAME_SIZE, XEL_RPLR_LENGTH_MASK_HI, XEL_RPLR_LENGTH_MASK_LO, XEL_RSR_RECV_DONE_MASK, XEL_RXBUFF_OFFSET, XEmacLite_AlignedRead, XEmacLite_GetRxStatus, XEmacLite_NextReceiveAddr, XEmacLite_ReadReg, XEmacLite_SetRxStatus.
Referenced by EmacLitePolledExample.
void XEmacLite_SetMacAddress(XEmacLite *InstancePtr, u8 *AddressPtr)
Set the MAC address for this device.
The address is a 48-bit value. InstancePtr is a pointer to the XEmacLite instance. AddressPtr is a pointer to a 6-byte MAC address. the format of the MAC address is major octet to minor octet None. - TX must be idle and RX should be idle for deterministic results. It is recommended that this function should be called after the initialization and before transmission of any packets from the device. - Function will not return if hardware is absent or not functioning properly. - The MAC address can be programmed using any of the two transmit buffers (if configured).
References XEL_MAC_ADDR_SIZE, XEL_TPLR_OFFSET, XEL_TSR_PROG_MAC_ADDR, XEmacLite_AlignedWrite, XEmacLite_GetTxStatus, XEmacLite_NextTransmitAddr, XEmacLite_SetTxStatus, XEmacLite_WriteReg.
Referenced by EmacLiteIntrExample, EmacLiteIntrLoopbackExample, EmacLitePhyLoopbackExample, EmacLitePolledExample.
void StubHandler(void *CallBackRef)
This is a stub for the send and receive callbacks.
The stub is here in case the upper layers forget to set the handlers. CallBackRef is a pointer to the upper layer callback reference. None. None.
Referenced by XEmacLite_CfgInitialize, XEmacLite_EnableInterrupts.
int XEmacLite_TxBufferAvailable(XEmacLite *InstancePtr)
Determine if there is a transmit buffer available.
InstancePtr is the pointer to the instance of the driver to be worked on. TRUE if there is a TX buffer available for data to be writtenFALSE if Tx Buffer is not available. None.
References XEmacLite_Config::TxPingPong, XEL_BUFFER_OFFSET, XEL_TSR_XMIT_ACTIVE_MASK, XEL_TSR_XMIT_BUSY_MASK, XEmacLite_GetTxStatus.
Referenced by EmacLiteIntrExample, EmacLiteIntrLoopbackExample, EmacLitePhyLoopbackExample, EmacLitePolledExample.
void XEmacLite_FlushReceive(XEmacLite *InstancePtr)
Flush the Receive buffers.
All data will be lost. InstancePtr is the pointer to the instance of the driver to be worked on. None. None.
References XEmacLite_Config::BaseAddress, XEmacLite_Config::RxPingPong, XEL_BUFFER_OFFSET, XEL_RSR_RECV_IE_MASK, XEmacLite_GetRxStatus, XEmacLite_SetRxStatus.
Referenced by EmacLiteIntrExample, EmacLiteIntrLoopbackExample, EmacLitePhyLoopbackExample, EmacLitePolledExample.
int XEmacLite_PhyRead(XEmacLite *InstancePtr, u32 PhyAddress, u32 RegNum, u16 *PhyDataPtr)
Read the specified PHY register.
InstancePtr is the pointer to the instance of the driver. PhyAddress is the address of the PHY device. The valid range is is from 0 to 31. RegNum is the register number in the PHY device which is to be read. The valid range is is from 0 to 31. PhyDataPtr is a pointer to the data in which the data read from the PHY device is returned. XST_SUCCESS if the data is read from the PHY.XST_DEVICE_BUSY if MDIO is busy. This function waits for the completion of MDIO data transfer.
References XEmacLite_Config::BaseAddress, XEmacLite_Config::MdioInclude, XEL_MDIO_ADDRESS_MASK, XEL_MDIO_ADDRESS_SHIFT, XEL_MDIO_OP_MASK, XEL_MDIOADDR_OFFSET, XEL_MDIOCNTR_ENABLE_MASK, XEL_MDIOCNTR_OFFSET, XEL_MDIOCNTR_STATUS_MASK, XEL_MDIORD_OFFSET, XEmacLite_ReadReg, XEmacLite_WriteReg.
Referenced by EmacLiteDisablePhyLoopBack, EmacLitePhyDetect.
int XEmacLite_PhyWrite(XEmacLite *InstancePtr, u32 PhyAddress, u32 RegNum, u16 PhyData)
Write the given data to the specified register in the PHY device.
InstancePtr is the pointer to the instance of the driver. PhyAddress is the address of the PHY device. The valid range is is from 0 to 31. RegNum is the register number in the PHY device which is to be written. The valid range is is from 0 to 31. PhyData is the data to be written to the specified register in the PHY device. XST_SUCCESS if the data is written to the PHY.XST_DEVICE_BUSY if MDIO is busy. This function waits for the completion of MDIO data transfer.
References XEmacLite_Config::BaseAddress, XEmacLite_Config::MdioInclude, XEL_MDIO_ADDRESS_MASK, XEL_MDIO_ADDRESS_SHIFT, XEL_MDIO_OP_MASK, XEL_MDIOADDR_OFFSET, XEL_MDIOCNTR_ENABLE_MASK, XEL_MDIOCNTR_OFFSET, XEL_MDIOCNTR_STATUS_MASK, XEL_MDIOWR_OFFSET, XEmacLite_ReadReg, XEmacLite_WriteReg.
Referenced by EmacLiteDisablePhyLoopBack, EmacLiteEnablePhyLoopBack.
void XEmacLite_EnableLoopBack(XEmacLite *InstancePtr)
Enable Internal loop back functionality.
InstancePtr is the pointer to the instance of the driver. None. None.
References XEmacLite_Config::BaseAddress, XEmacLite_Config::Loopback, XEL_TSR_LOOPBACK_MASK, XEL_TSR_OFFSET, XEmacLite_ReadReg, XEmacLite_WriteReg.
Referenced by EmacLiteIntrLoopbackExample.
void XEmacLite_DisableLoopBack(XEmacLite *InstancePtr)
Disable Internal loop back functionality.
InstancePtr is the pointer to the instance of the driver. None. None.
References XEmacLite_Config::BaseAddress, XEmacLite_Config::Loopback, XEL_TSR_LOOPBACK_MASK, XEL_TSR_OFFSET, XEmacLite_ReadReg, XEmacLite_WriteReg.
Referenced by EmacLiteIntrLoopbackExample.
XEmacLite_Config * XEmacLite_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
A table contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration table entry corresponding to the given device ID/BaseAddress, or NULL if no match is found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XEmacLite_Config::Name.
Referenced by EmacLiteIntrExample, EmacLiteIntrLoopbackExample, EmacLitePhyLoopbackExample, EmacLitePolledExample, EMACLiteSelfTestExample, XEmacLite_Initialize.
int XEmacLite_Initialize(XEmacLite *InstancePtr, UINTPTR BaseAddress)
Initialize a specific XEmacLite instance/driver.
The initialization entails: Initialize fields of the XEmacLite instance structure. The driver defaults to polled mode operation. InstancePtr is a pointer to the XEmacLite instance. DeviceId is the unique id of the device controlled by this XEmacLite instance. Passing in a device id associates the generic XEmacLite instance to a specific device, as chosen by the caller or application developer. XST_SUCCESS if initialization was successful.XST_DEVICE_NOT_FOUND/XST_FAILURE if device configuration information was not found for a device with the supplied device ID. None
References XEmacLite_Config::BaseAddress, XEmacLite_CfgInitialize, XEmacLite_LookupConfig.
int XEmacLite_EnableInterrupts(XEmacLite *InstancePtr)
Enable the EmacLite Interrupts.
This function must be called before other functions to send or receive data in interrupt driven mode. The user should have connected the interrupt handler of the driver to an interrupt source such as an interrupt controller or the processor interrupt prior to this function being called. InstancePtr is a pointer to the XEmacLite instance. XST_SUCCESS if the device interrupts were enabled successfully. XST_NO_CALLBACK if the callbacks were not set. None.
References XEmacLite_Config::BaseAddress, StubHandler, XEL_GIER_GIE_MASK, XEL_GIER_OFFSET, XEL_RSR_RECV_IE_MASK, XEL_TSR_XMIT_IE_MASK, XEmacLite_GetRxStatus, XEmacLite_GetTxStatus, XEmacLite_SetRxStatus, XEmacLite_SetTxStatus, XEmacLite_WriteReg.
Referenced by EmacLiteIntrExample, EmacLiteIntrLoopbackExample, EmacLitePhyLoopbackExample.
void XEmacLite_DisableInterrupts(XEmacLite *InstancePtr)
Disables the interrupts from the device (the higher layer software is responsible for disabling interrupts at the interrupt controller).
To start using the device again, _EnableInterrupts must be called. InstancePtr is a pointer to the XEmacLite instance . None. None.
References XEmacLite_Config::BaseAddress, XEL_GIER_OFFSET, XEL_RSR_RECV_IE_MASK, XEL_TSR_XMIT_IE_MASK, XEmacLite_GetRxStatus, XEmacLite_GetTxStatus, XEmacLite_SetRxStatus, XEmacLite_SetTxStatus, XEmacLite_WriteReg.
Referenced by EmacLiteIntrExample, EmacLiteIntrLoopbackExample, EmacLitePhyLoopbackExample.
void XEmacLite_InterruptHandler(void *InstancePtr)
Interrupt handler for the EmacLite driver.
It performs the following processing: - Get the interrupt status from the registers to determine the source of the interrupt. - Call the appropriate handler based on the source of the interrupt. InstancePtr contains a pointer to the EmacLite device instance for the interrupt. None. None.
References XEmacLite_Config::BaseAddress, XEL_BUFFER_OFFSET, XEL_TSR_XMIT_ACTIVE_MASK, XEL_TSR_XMIT_BUSY_MASK, XEmacLite_GetTxStatus, XEmacLite_IsRxEmpty, XEmacLite_SetTxStatus.
Referenced by EmacLiteIntrExample, EmacLiteIntrLoopbackExample, EmacLitePhyLoopbackExample.
void XEmacLite_SetRecvHandler(XEmacLite *InstancePtr, void *CallBackRef, XEmacLite_Handler FuncPtr)
Sets the callback function for handling received frames in interrupt mode.
The upper layer software should call this function during initialization. The callback is called when a frame is received. The callback function should communicate the data to a thread such that the processing is not performed in an interrupt context.The callback is invoked by the driver within interrupt context, so it needs to do its job quickly. If there are other potentially slow operations within the callback, these should be done at task-level. InstancePtr is a pointer to the XEmacLite instance.. CallBackRef is a reference pointer to be passed back to the application in the callback. This helps the application correlate the callback to a particular driver. FuncPtr is the pointer to the callback function. None. None.
Referenced by EmacLiteIntrExample, EmacLiteIntrLoopbackExample, EmacLitePhyLoopbackExample.
void XEmacLite_SetSendHandler(XEmacLite *InstancePtr, void *CallBackRef, XEmacLite_Handler FuncPtr)
Sets the callback function for handling transmitted frames in interrupt mode.
The upper layer software should call this function during initialization. The callback is called when a frame is transmitted. The callback function should communicate the data to a thread such that the processing is not performed in an interrupt context.The callback is invoked by the driver within interrupt context, so it needs to do its job quickly. If there are other potentially slow operations within the callback, these should be done at task-level. InstancePtr is a pointer to the XEmacLite instance. CallBackRef is a reference pointer to be passed back to the application in the callback. This helps the application correlate the callback to a particular driver. FuncPtr is the pointer to the callback function. None. None.
Referenced by EmacLiteIntrExample, EmacLiteIntrLoopbackExample, EmacLitePhyLoopbackExample.
int XEmacLite_SelfTest(XEmacLite *InstancePtr)
Performs a SelfTest on the EmacLite device as follows:
Writes to the mandatory TX buffer and reads back to verify.If configured, writes to the secondary TX buffer and reads back to verify.Writes to the mandatory RX buffer and reads back to verify.If configured, writes to the secondary RX buffer and reads back to verify. InstancePtr is a pointer to the XEmacLite instance . XST_SUCCESS if the device Passed the Self Test. XST_FAILURE if any of the data read backs fail. None.
References XEmacLite_Config::BaseAddress, XEmacLite_Config::RxPingPong, XEmacLite_Config::TxPingPong, XEL_BUFFER_OFFSET, XEL_RXBUFF_OFFSET, XEL_TXBUFF_OFFSET, XEmacLite_AlignedRead, XEmacLite_AlignedWrite.
Referenced by EMACLiteSelfTestExample.
void XEmacLite_AlignedWrite(void *SrcPtr, UINTPTR *DestPtr, unsigned ByteCount)
This function aligns the incoming data and writes it out to a 32-bit aligned destination address range.
SrcPtr is a pointer to incoming data of any alignment. DestPtr is a pointer to outgoing data of 32-bit alignment. ByteCount is the number of bytes to write. None. None.
Referenced by XEmacLite_SelfTest, XEmacLite_Send, XEmacLite_SendFrame, XEmacLite_SetMacAddress.
void XEmacLite_AlignedRead(UINTPTR *SrcPtr, void *DestPtr, unsigned ByteCount)
This function reads from a 32-bit aligned source address range and aligns the writes to the provided destination pointer alignment.
SrcPtr is a pointer to incoming data of 32-bit alignment. DestPtr is a pointer to outgoing data of any alignment. ByteCount is the number of bytes to read. None. None.
Referenced by XEmacLite_Recv, XEmacLite_RecvFrame, XEmacLite_SelfTest.
void XEmacLite_SendFrame(UINTPTR BaseAddress, u8 *FramePtr, unsigned ByteCount)
Send an Ethernet frame.
The size is the total frame size, including header. This function blocks waiting for the frame to be transmitted. BaseAddress is the base address of the device FramePtr is a pointer to frame ByteCount is the size, in bytes, of the frame None. This function call is blocking in nature, i.e. it will wait until the frame is transmitted. This function can hang and not exit if the hardware is not configured properly.If the ping buffer is the destination of the data, the argument should be DeviceAddress + XEL_TXBUFF_OFFSET. If the pong buffer is the destination of the data, the argument should be DeviceAddress + XEL_TXBUFF_OFFSET + XEL_BUFFER_OFFSET. The function does not take the different buffers into consideration.
References XEL_TPLR_LENGTH_MASK_HI, XEL_TPLR_LENGTH_MASK_LO, XEL_TPLR_OFFSET, XEL_TSR_XMIT_BUSY_MASK, XEmacLite_AlignedWrite, XEmacLite_GetTxStatus, XEmacLite_IsTxDone, XEmacLite_SetTxStatus, XEmacLite_WriteReg.
u16 XEmacLite_RecvFrame(UINTPTR BaseAddress, u8 *FramePtr)
Receive a frame.
Wait for a frame to arrive. BaseAddress is the base address of the device FramePtr is a pointer to a buffer where the frame will be stored. The type/length field of the frame received. When the type/length field contains the type , XEL_MAX_FRAME_SIZE bytes will be copied out of the buffer and it is up to the higher layers to sort out the frame. This function call is blocking in nature, i.e. it will wait until a frame arrives.If the ping buffer is the source of the data, the argument should be DeviceAddress + XEL_RXBUFF_OFFSET. If the pong buffer is the source of the data, the argument should be DeviceAddress + XEL_RXBUFF_OFFSET + XEL_BUFFER_OFFSET. The function does not take the different buffers into consideration.
References XEL_FCS_SIZE, XEL_HEADER_SIZE, XEL_MAX_FRAME_SIZE, XEL_RPLR_LENGTH_MASK_HI, XEL_RPLR_LENGTH_MASK_LO, XEL_RPLR_OFFSET, XEL_RSR_RECV_DONE_MASK, XEL_RXBUFF_OFFSET, XEmacLite_AlignedRead, XEmacLite_GetRxStatus, XEmacLite_IsRxEmpty, XEmacLite_ReadReg, XEmacLite_SetRxStatus.
XEMACLITE_H
XEL_DEVICE_NAME
XEL_DEVICE_DESC
XEmacLite_NextTransmitAddr
Return the next expected Transmit Buffer's address.
InstancePtr is the pointer to the instance of the driver to be worked on C-Style signature: u32 XEmacLite_NextTransmitAddr(XEmacLite *InstancePtr); This macro returns the address of the next transmit buffer to put data into. This is used to determine the destination of the next transmit data frame.
Referenced by XEmacLite_Send, XEmacLite_SetMacAddress.
XEmacLite_NextReceiveAddr
Return the next expected Receive Buffer's address.
InstancePtr is the pointer to the instance of the driver to be worked on C-Style signature: u32 XEmacLite_NextReceiveAddr(XEmacLite *InstancePtr); This macro returns the address of the next receive buffer to read data from. This is the expected receive buffer address if the driver is in sync.
Referenced by XEmacLite_Recv.
XEmacLite_IsMdioConfigured
This macro determines if the device is currently configured for MDIO.
InstancePtr is the pointer to the instance of the EmacLite driver. TRUE if the device is configured for MDIO. FALSE if the device is NOT configured for MDIO. C-Style signature: int XEmacLite_IsMdioConfigured(XEmacLite *InstancePtr)
Referenced by EmacLiteIntrExample, EmacLitePhyLoopbackExample, EmacLitePolledExample.
XEmacLite_IsLoopbackConfigured
This macro determines if the device is currently configured for internal loopback.
InstancePtr is the pointer to the instance of the EmacLite driver. TRUE if the device is configured for internal loopback. FALSE if the device is NOT configured for internal loopback. C-Style signature: int XEmacLite_IsLoopbackConfigured(XEmacLite *InstancePtr)
XEMACLITE_I_H
XEmacLite_GetTxActive
Get the TX active location to check status.
This is used to check if the TX buffer is currently active. There isn't any way in the hardware to implement this but the register is fully populated so the driver can set the bit in the send routine and the ISR can clear the bit when the handler is complete. This mimics the correct operation of the hardware if it was possible to do this in hardware. BaseAddress is the base address of the device Contents of active bit in register. C-Style signature: u32 XEmacLite_GetTxActive(u32 BaseAddress)
XEmacLite_SetTxActive
Set the TX active location to update status.
This is used to set the bit indicating which TX buffer is currently active. There isn't any way in the hardware to implement this but the register is fully populated so the driver can set the bit in the send routine and the ISR can clear the bit when the handler is complete. This mimics the correct operation of the hardware if it was possible to do this in hardware. BaseAddress is the base address of the device Mask is the data to be written None C-Style signature: void XEmacLite_SetTxActive(u32 BaseAddress, u32 Mask)
XEMAC_LITE_L_H
XEL_TXBUFF_OFFSET
Register offsets for the Ethernet MAC.
Transmit Buffer
Referenced by XEmacLite_SelfTest.
XEL_MDIOADDR_OFFSET
MDIO Address offset register.
Referenced by XEmacLite_PhyRead, XEmacLite_PhyWrite.
XEL_MDIOWR_OFFSET
MDIO write data register offset.
Referenced by XEmacLite_PhyWrite.
XEL_MDIORD_OFFSET
MDIO read data register offset.
Referenced by XEmacLite_PhyRead.
XEL_MDIOCNTR_OFFSET
MDIO Control Register offset.
Referenced by XEmacLite_PhyRead, XEmacLite_PhyWrite.
XEL_GIER_OFFSET
Offset for the GIE Register.
Referenced by XEmacLite_DisableInterrupts, XEmacLite_EnableInterrupts.
XEL_TSR_OFFSET
Tx status.
Referenced by XEmacLite_CfgInitialize, XEmacLite_DisableLoopBack, XEmacLite_EnableLoopBack.
XEL_TPLR_OFFSET
Tx packet length.
Referenced by XEmacLite_Send, XEmacLite_SendFrame, XEmacLite_SetMacAddress.
XEL_RXBUFF_OFFSET
Receive Buffer.
Referenced by XEmacLite_Recv, XEmacLite_RecvFrame, XEmacLite_SelfTest.
XEL_RSR_OFFSET
Rx status.
XEL_RPLR_OFFSET
Rx packet length.
Referenced by XEmacLite_RecvFrame.
XEL_MAC_HI_OFFSET
MAC address hi offset.
XEL_MAC_LO_OFFSET
MAC address lo offset.
XEL_BUFFER_OFFSET
Next buffer's offset same for both TX and RX.
Referenced by XEmacLite_CfgInitialize, XEmacLite_FlushReceive, XEmacLite_InterruptHandler, XEmacLite_Recv, XEmacLite_SelfTest, XEmacLite_Send, XEmacLite_TxBufferAvailable.
XEL_MDIO_ADDRESS_MASK
MDIO Address/Write Data/Read Data Register Bit Masks.
PHY Address mask
Referenced by XEmacLite_PhyRead, XEmacLite_PhyWrite.
XEL_MDIO_ADDRESS_SHIFT
PHY Address shift.
Referenced by XEmacLite_PhyRead, XEmacLite_PhyWrite.
XEL_MDIO_OP_MASK
PHY read access.
Referenced by XEmacLite_PhyRead, XEmacLite_PhyWrite.
XEL_MDIOCNTR_STATUS_MASK
MDIO Control Register Bit Masks.
MDIO transfer in Progress
Referenced by XEmacLite_PhyRead, XEmacLite_PhyWrite.
XEL_MDIOCNTR_ENABLE_MASK
MDIO Enable.
Referenced by XEmacLite_PhyRead, XEmacLite_PhyWrite.
XEL_GIER_GIE_MASK
Global Interrupt Enable Register (GIER) Bit Masks.
Global Enable
Referenced by XEmacLite_EnableInterrupts.
XEL_TSR_XMIT_BUSY_MASK
Transmit Status Register (TSR) Bit Masks.
Xmit complete
Referenced by XEmacLite_InterruptHandler, XEmacLite_Send, XEmacLite_SendFrame, XEmacLite_TxBufferAvailable.
XEL_TSR_PROGRAM_MASK
Program the MAC address.
XEL_TSR_XMIT_IE_MASK
Xmit interrupt enable bit.
Referenced by XEmacLite_DisableInterrupts, XEmacLite_EnableInterrupts, XEmacLite_Send.
XEL_TSR_LOOPBACK_MASK
Loop back enable bit.
Referenced by XEmacLite_DisableLoopBack, XEmacLite_EnableLoopBack.
XEL_TSR_XMIT_ACTIVE_MASK
Buffer is active, SW bit only.
This is not documented in the HW spec
Referenced by XEmacLite_InterruptHandler, XEmacLite_Send, XEmacLite_TxBufferAvailable.
XEL_TSR_PROG_MAC_ADDR
define for programming the MAC address into the EmacLite
Referenced by XEmacLite_SetMacAddress.
XEL_RSR_RECV_DONE_MASK
Receive Status Register (RSR)
Recv complete
Referenced by XEmacLite_Recv, XEmacLite_RecvFrame.
XEL_RSR_RECV_IE_MASK
Recv interrupt enable bit.
Referenced by XEmacLite_DisableInterrupts, XEmacLite_EnableInterrupts, XEmacLite_FlushReceive.
XEL_TPLR_LENGTH_MASK_HI
Transmit Packet Length Register (TPLR)
Transmit packet length upper byte
Referenced by XEmacLite_Send, XEmacLite_SendFrame.
XEL_TPLR_LENGTH_MASK_LO
Transmit packet length lower byte.
Referenced by XEmacLite_Send, XEmacLite_SendFrame.
XEL_RPLR_LENGTH_MASK_HI
Receive Packet Length Register (RPLR)
Receive packet length upper byte
Referenced by XEmacLite_Recv, XEmacLite_RecvFrame.
XEL_RPLR_LENGTH_MASK_LO
Receive packet length lower byte.
Referenced by XEmacLite_Recv, XEmacLite_RecvFrame.
XEL_HEADER_SIZE
Size of header in bytes.
Referenced by XEmacLite_Recv, XEmacLite_RecvFrame.
XEL_MTU_SIZE
Max size of data in frame.
Referenced by EmacLiteIntrLoopbackExample, EmacLitePhyLoopbackExample.
XEL_FCS_SIZE
Size of CRC.
Referenced by XEmacLite_Recv, XEmacLite_RecvFrame.
XEL_HEADER_OFFSET
Offset to length field.
XEL_HEADER_SHIFT
Right shift value to align length.
Referenced by XEmacLite_Recv.
XEL_MAX_FRAME_SIZE
Max length of Rx frame used if length/type field contains the type (> 1500)
Referenced by XEmacLite_Recv, XEmacLite_RecvFrame.
XEL_MAX_TX_FRAME_SIZE
Max length of Tx frame.
Referenced by XEmacLite_Send.
XEL_MAC_ADDR_SIZE
length of MAC address
Referenced by XEmacLite_SetMacAddress.
XEL_ETHER_PROTO_TYPE_IP
IP Protocol.
Referenced by XEmacLite_Recv.
XEL_ETHER_PROTO_TYPE_ARP
ARP Protocol.
Referenced by XEmacLite_Recv.
XEL_ETHER_PROTO_TYPE_VLAN
VLAN Tagged.
XEL_ARP_PACKET_SIZE
Max ARP packet size.
Referenced by XEmacLite_Recv.
XEL_HEADER_IP_LENGTH_OFFSET
IP Length Offset.
Referenced by XEmacLite_Recv.
XEL_VLAN_TAG_SIZE
VLAN Tag Size.
XEmacLite_In32
XEmacLite_Out32
XEmacLite_ReadReg
Read from the specified EmacLite device register.
BaseAddress contains the base address of the device. RegOffset contains the offset from the 1st register of the device to select the specific register. The value read from the register. C-Style signature: u32 XEmacLite_ReadReg(u32 BaseAddress, u32 RegOffset);
Referenced by XEmacLite_DisableLoopBack, XEmacLite_EnableLoopBack, XEmacLite_PhyRead, XEmacLite_PhyWrite, XEmacLite_Recv, XEmacLite_RecvFrame.
XEmacLite_WriteReg
Write to the specified EmacLite device register.
BaseAddress contains the base address of the device. RegOffset contains the offset from the 1st register of the device to select the specific register. RegisterValue is the value to be written to the register. None. C-Style signature: void XEmacLite_WriteReg(u32 BaseAddress, u32 RegOffset, u32 RegisterValue);
Referenced by XEmacLite_CfgInitialize, XEmacLite_DisableInterrupts, XEmacLite_DisableLoopBack, XEmacLite_EnableInterrupts, XEmacLite_EnableLoopBack, XEmacLite_PhyRead, XEmacLite_PhyWrite, XEmacLite_Send, XEmacLite_SendFrame, XEmacLite_SetMacAddress.
XEmacLite_GetTxStatus
Get the Tx Status Register Contents.
BaseAddress is the base address of the device The contents of the Tx Status Register. C-Style signature: u32 XEmacLite_GetTxStatus(u32 BaseAddress)
Referenced by XEmacLite_DisableInterrupts, XEmacLite_EnableInterrupts, XEmacLite_InterruptHandler, XEmacLite_Send, XEmacLite_SendFrame, XEmacLite_SetMacAddress, XEmacLite_TxBufferAvailable.
XEmacLite_SetTxStatus
Set the Tx Status Register Contents.
BaseAddress is the base address of the device Data is the value to be written to the Register. None. C-Style signature: u32 XEmacLite_SetTxStatus(u32 BaseAddress, u32 Data)
Referenced by XEmacLite_DisableInterrupts, XEmacLite_EnableInterrupts, XEmacLite_InterruptHandler, XEmacLite_Send, XEmacLite_SendFrame, XEmacLite_SetMacAddress.
XEmacLite_GetRxStatus
Get the Rx Status Register Contents.
BaseAddress is the base address of the device The contents of the Rx Status Register. C-Style signature: u32 XEmacLite_GetRxStatus(u32 BaseAddress)
Referenced by XEmacLite_DisableInterrupts, XEmacLite_EnableInterrupts, XEmacLite_FlushReceive, XEmacLite_Recv, XEmacLite_RecvFrame.
XEmacLite_SetRxStatus
Set the Rx Status Register Contents.
BaseAddress is the base address of the device Data is the value to be written to the Register. None. C-Style signature: u32 XEmacLite_SetRxStatus(u32 BaseAddress, u32 Data)
Referenced by XEmacLite_DisableInterrupts, XEmacLite_EnableInterrupts, XEmacLite_FlushReceive, XEmacLite_Recv, XEmacLite_RecvFrame.
XEmacLite_IsTxDone
Check to see if the transmission is complete.
BaseAddress is the base address of the device TRUE if it is done, or FALSE if it is not. C-Style signature: int XEmacLite_IsTxDone(u32 BaseAddress)
Referenced by XEmacLite_SendFrame.
XEmacLite_IsRxEmpty
Check to see if the receive is empty.
BaseAddress is the base address of the device TRUE if it is empty, or FALSE if it is not. C-Style signature: int XEmacLite_IsRxEmpty(u32 BaseAddress)
Referenced by XEmacLite_InterruptHandler, XEmacLite_RecvFrame.