xemaclite.c
static u16 XEmacLite_GetReceiveDataLength(UINTPTR BaseAddress)
Return the length of the data in the Receive Buffer.
BaseAddress contains the base address of the device. The type/length field of the frame received. None.
int XEmacLite_CfgInitialize(XEmacLite *InstancePtr, XEmacLite_Config *EmacLiteConfigPtr, UINTPTR EffectiveAddr)
Initialize a specific XEmacLite instance/driver.
The initialization entails: Initialize fields of the XEmacLite instance structure. The driver defaults to polled mode operation. InstancePtr is a pointer to the XEmacLite instance. EmacLiteConfigPtr points to the XEmacLite device configuration structure. EffectiveAddr is the device base address in the virtual memory address space. If the address translation is not used then the physical address is passed. Unexpected errors may occur if the address mapping is changed after this function is invoked. XST_SUCCESS if initialization was successful. The initialization of the PHY device is not done in this function. The user needs to use XEmacLite_PhyRead and XEmacLite_PhyWrite functions to access the PHY device.
References XEmacLite_Config::BaseAddress, XEmacLite_Config::IntrId, XEmacLite_Config::IntrParent, XEmacLite_Config::Loopback, XEmacLite_Config::MdioInclude, XEmacLite_Config::RxPingPong, StubHandler, XEmacLite_Config::TxPingPong, XEL_BUFFER_OFFSET, XEL_TSR_OFFSET, XEmacLite_WriteReg.
Referenced by EmacLiteIntrExample, EmacLiteIntrLoopbackExample, EmacLitePhyLoopbackExample, EmacLitePolledExample, EMACLiteSelfTestExample, XEmacLite_Initialize.
int XEmacLite_Send(XEmacLite *InstancePtr, u8 *FramePtr, unsigned ByteCount)
Send an Ethernet frame.
The ByteCount is the total frame size, including header. InstancePtr is a pointer to the XEmacLite instance. FramePtr is a pointer to frame. For optimal performance, a 32-bit aligned buffer should be used but it is not required, the function will align the data if necessary. ByteCount is the size, in bytes, of the frame XST_SUCCESS if data was transmitted.XST_FAILURE if buffer(s) was (were) full and no valid data was transmitted. This function call is not blocking in nature, i.e. it will not wait until the frame is transmitted.
References XEmacLite_Config::BaseAddress, XEmacLite_Config::TxPingPong, XEL_BUFFER_OFFSET, XEL_MAX_TX_FRAME_SIZE, XEL_TPLR_LENGTH_MASK_HI, XEL_TPLR_LENGTH_MASK_LO, XEL_TPLR_OFFSET, XEL_TSR_XMIT_ACTIVE_MASK, XEL_TSR_XMIT_BUSY_MASK, XEL_TSR_XMIT_IE_MASK, XEmacLite_AlignedWrite, XEmacLite_GetTxStatus, XEmacLite_NextTransmitAddr, XEmacLite_SetTxStatus, XEmacLite_WriteReg.
u16 XEmacLite_Recv(XEmacLite *InstancePtr, u8 *FramePtr)
Receive a frame.
Intended to be called from the interrupt context or with a wrapper which waits for the receive frame to be available. InstancePtr is a pointer to the XEmacLite instance. FramePtr is a pointer to a buffer where the frame will be stored. The buffer must be at least XEL_MAX_FRAME_SIZE bytes. For optimal performance, a 32-bit aligned buffer should be used but it is not required, the function will align the data if necessary. The type/length field of the frame received. When the type/length field contains the type, XEL_MAX_FRAME_SIZE bytes will be copied out of the buffer and it is up to the higher layers to sort out the frame. Function returns 0 if there is no data waiting in the receive buffer or the pong buffer if configured. This function call is not blocking in nature, i.e. it will not wait until a frame arrives.
References XEmacLite_Config::RxPingPong, XEL_ARP_PACKET_SIZE, XEL_BUFFER_OFFSET, XEL_ETHER_PROTO_TYPE_ARP, XEL_ETHER_PROTO_TYPE_IP, XEL_FCS_SIZE, XEL_HEADER_IP_LENGTH_OFFSET, XEL_HEADER_SHIFT, XEL_HEADER_SIZE, XEL_MAX_FRAME_SIZE, XEL_RPLR_LENGTH_MASK_HI, XEL_RPLR_LENGTH_MASK_LO, XEL_RSR_RECV_DONE_MASK, XEL_RXBUFF_OFFSET, XEmacLite_AlignedRead, XEmacLite_GetRxStatus, XEmacLite_NextReceiveAddr, XEmacLite_ReadReg, XEmacLite_SetRxStatus.
Referenced by EmacLitePolledExample.
void XEmacLite_SetMacAddress(XEmacLite *InstancePtr, u8 *AddressPtr)
Set the MAC address for this device.
The address is a 48-bit value. InstancePtr is a pointer to the XEmacLite instance. AddressPtr is a pointer to a 6-byte MAC address. the format of the MAC address is major octet to minor octet None. - TX must be idle and RX should be idle for deterministic results. It is recommended that this function should be called after the initialization and before transmission of any packets from the device. - Function will not return if hardware is absent or not functioning properly. - The MAC address can be programmed using any of the two transmit buffers (if configured).
References XEL_MAC_ADDR_SIZE, XEL_TPLR_OFFSET, XEL_TSR_PROG_MAC_ADDR, XEmacLite_AlignedWrite, XEmacLite_GetTxStatus, XEmacLite_NextTransmitAddr, XEmacLite_SetTxStatus, XEmacLite_WriteReg.
Referenced by EmacLiteIntrExample, EmacLiteIntrLoopbackExample, EmacLitePhyLoopbackExample, EmacLitePolledExample.
void StubHandler(void *CallBackRef)
This is a stub for the send and receive callbacks.
The stub is here in case the upper layers forget to set the handlers. CallBackRef is a pointer to the upper layer callback reference. None. None.
Referenced by XEmacLite_CfgInitialize, XEmacLite_EnableInterrupts.
int XEmacLite_TxBufferAvailable(XEmacLite *InstancePtr)
Determine if there is a transmit buffer available.
InstancePtr is the pointer to the instance of the driver to be worked on. TRUE if there is a TX buffer available for data to be writtenFALSE if Tx Buffer is not available. None.
References XEmacLite_Config::TxPingPong, XEL_BUFFER_OFFSET, XEL_TSR_XMIT_ACTIVE_MASK, XEL_TSR_XMIT_BUSY_MASK, XEmacLite_GetTxStatus.
Referenced by EmacLiteIntrExample, EmacLiteIntrLoopbackExample, EmacLitePhyLoopbackExample, EmacLitePolledExample.
void XEmacLite_FlushReceive(XEmacLite *InstancePtr)
Flush the Receive buffers.
All data will be lost. InstancePtr is the pointer to the instance of the driver to be worked on. None. None.
References XEmacLite_Config::BaseAddress, XEmacLite_Config::RxPingPong, XEL_BUFFER_OFFSET, XEL_RSR_RECV_IE_MASK, XEmacLite_GetRxStatus, XEmacLite_SetRxStatus.
Referenced by EmacLiteIntrExample, EmacLiteIntrLoopbackExample, EmacLitePhyLoopbackExample, EmacLitePolledExample.
int XEmacLite_PhyRead(XEmacLite *InstancePtr, u32 PhyAddress, u32 RegNum, u16 *PhyDataPtr)
Read the specified PHY register.
InstancePtr is the pointer to the instance of the driver. PhyAddress is the address of the PHY device. The valid range is is from 0 to 31. RegNum is the register number in the PHY device which is to be read. The valid range is is from 0 to 31. PhyDataPtr is a pointer to the data in which the data read from the PHY device is returned. XST_SUCCESS if the data is read from the PHY.XST_DEVICE_BUSY if MDIO is busy. This function waits for the completion of MDIO data transfer.
References XEmacLite_Config::BaseAddress, XEmacLite_Config::MdioInclude, XEL_MDIO_ADDRESS_MASK, XEL_MDIO_ADDRESS_SHIFT, XEL_MDIO_OP_MASK, XEL_MDIOADDR_OFFSET, XEL_MDIOCNTR_ENABLE_MASK, XEL_MDIOCNTR_OFFSET, XEL_MDIOCNTR_STATUS_MASK, XEL_MDIORD_OFFSET, XEmacLite_ReadReg, XEmacLite_WriteReg.
Referenced by EmacLiteDisablePhyLoopBack, EmacLitePhyDetect.
int XEmacLite_PhyWrite(XEmacLite *InstancePtr, u32 PhyAddress, u32 RegNum, u16 PhyData)
Write the given data to the specified register in the PHY device.
InstancePtr is the pointer to the instance of the driver. PhyAddress is the address of the PHY device. The valid range is is from 0 to 31. RegNum is the register number in the PHY device which is to be written. The valid range is is from 0 to 31. PhyData is the data to be written to the specified register in the PHY device. XST_SUCCESS if the data is written to the PHY.XST_DEVICE_BUSY if MDIO is busy. This function waits for the completion of MDIO data transfer.
References XEmacLite_Config::BaseAddress, XEmacLite_Config::MdioInclude, XEL_MDIO_ADDRESS_MASK, XEL_MDIO_ADDRESS_SHIFT, XEL_MDIO_OP_MASK, XEL_MDIOADDR_OFFSET, XEL_MDIOCNTR_ENABLE_MASK, XEL_MDIOCNTR_OFFSET, XEL_MDIOCNTR_STATUS_MASK, XEL_MDIOWR_OFFSET, XEmacLite_ReadReg, XEmacLite_WriteReg.
Referenced by EmacLiteDisablePhyLoopBack, EmacLiteEnablePhyLoopBack.
void XEmacLite_EnableLoopBack(XEmacLite *InstancePtr)
Enable Internal loop back functionality.
InstancePtr is the pointer to the instance of the driver. None. None.
References XEmacLite_Config::BaseAddress, XEmacLite_Config::Loopback, XEL_TSR_LOOPBACK_MASK, XEL_TSR_OFFSET, XEmacLite_ReadReg, XEmacLite_WriteReg.
Referenced by EmacLiteIntrLoopbackExample.
void XEmacLite_DisableLoopBack(XEmacLite *InstancePtr)
Disable Internal loop back functionality.
InstancePtr is the pointer to the instance of the driver. None. None.
References XEmacLite_Config::BaseAddress, XEmacLite_Config::Loopback, XEL_TSR_LOOPBACK_MASK, XEL_TSR_OFFSET, XEmacLite_ReadReg, XEmacLite_WriteReg.
Referenced by EmacLiteIntrLoopbackExample.