xemaclite_intr.c
int XEmacLite_EnableInterrupts(XEmacLite *InstancePtr)
Enable the EmacLite Interrupts.
This function must be called before other functions to send or receive data in interrupt driven mode. The user should have connected the interrupt handler of the driver to an interrupt source such as an interrupt controller or the processor interrupt prior to this function being called. InstancePtr is a pointer to the XEmacLite instance. XST_SUCCESS if the device interrupts were enabled successfully. XST_NO_CALLBACK if the callbacks were not set. None.
References XEmacLite_Config::BaseAddress, StubHandler, XEL_GIER_GIE_MASK, XEL_GIER_OFFSET, XEL_RSR_RECV_IE_MASK, XEL_TSR_XMIT_IE_MASK, XEmacLite_GetRxStatus, XEmacLite_GetTxStatus, XEmacLite_SetRxStatus, XEmacLite_SetTxStatus, XEmacLite_WriteReg.
Referenced by EmacLiteIntrExample, EmacLiteIntrLoopbackExample, EmacLitePhyLoopbackExample.
void XEmacLite_DisableInterrupts(XEmacLite *InstancePtr)
Disables the interrupts from the device (the higher layer software is responsible for disabling interrupts at the interrupt controller).
To start using the device again, _EnableInterrupts must be called. InstancePtr is a pointer to the XEmacLite instance . None. None.
References XEmacLite_Config::BaseAddress, XEL_GIER_OFFSET, XEL_RSR_RECV_IE_MASK, XEL_TSR_XMIT_IE_MASK, XEmacLite_GetRxStatus, XEmacLite_GetTxStatus, XEmacLite_SetRxStatus, XEmacLite_SetTxStatus, XEmacLite_WriteReg.
Referenced by EmacLiteIntrExample, EmacLiteIntrLoopbackExample, EmacLitePhyLoopbackExample.
void XEmacLite_InterruptHandler(void *InstancePtr)
Interrupt handler for the EmacLite driver.
It performs the following processing: - Get the interrupt status from the registers to determine the source of the interrupt. - Call the appropriate handler based on the source of the interrupt. InstancePtr contains a pointer to the EmacLite device instance for the interrupt. None. None.
References XEmacLite_Config::BaseAddress, XEL_BUFFER_OFFSET, XEL_TSR_XMIT_ACTIVE_MASK, XEL_TSR_XMIT_BUSY_MASK, XEmacLite_GetTxStatus, XEmacLite_IsRxEmpty, XEmacLite_SetTxStatus.
Referenced by EmacLiteIntrExample, EmacLiteIntrLoopbackExample, EmacLitePhyLoopbackExample.
void XEmacLite_SetRecvHandler(XEmacLite *InstancePtr, void *CallBackRef, XEmacLite_Handler FuncPtr)
Sets the callback function for handling received frames in interrupt mode.
The upper layer software should call this function during initialization. The callback is called when a frame is received. The callback function should communicate the data to a thread such that the processing is not performed in an interrupt context.The callback is invoked by the driver within interrupt context, so it needs to do its job quickly. If there are other potentially slow operations within the callback, these should be done at task-level. InstancePtr is a pointer to the XEmacLite instance.. CallBackRef is a reference pointer to be passed back to the application in the callback. This helps the application correlate the callback to a particular driver. FuncPtr is the pointer to the callback function. None. None.
Referenced by EmacLiteIntrExample, EmacLiteIntrLoopbackExample, EmacLitePhyLoopbackExample.
void XEmacLite_SetSendHandler(XEmacLite *InstancePtr, void *CallBackRef, XEmacLite_Handler FuncPtr)
Sets the callback function for handling transmitted frames in interrupt mode.
The upper layer software should call this function during initialization. The callback is called when a frame is transmitted. The callback function should communicate the data to a thread such that the processing is not performed in an interrupt context.The callback is invoked by the driver within interrupt context, so it needs to do its job quickly. If there are other potentially slow operations within the callback, these should be done at task-level. InstancePtr is a pointer to the XEmacLite instance. CallBackRef is a reference pointer to be passed back to the application in the callback. This helps the application correlate the callback to a particular driver. FuncPtr is the pointer to the callback function. None. None.
Referenced by EmacLiteIntrExample, EmacLiteIntrLoopbackExample, EmacLitePhyLoopbackExample.