xemaclite_sinit.c
XEmacLite_Config XEmacLite_ConfigTable[][]
This table contains configuration information for each EmacLite device in the system.
XEmacLite_Config * XEmacLite_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
A table contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration table entry corresponding to the given device ID/BaseAddress, or NULL if no match is found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XEmacLite_Config::Name.
Referenced by EmacLiteIntrExample, EmacLiteIntrLoopbackExample, EmacLitePhyLoopbackExample, EmacLitePolledExample, EMACLiteSelfTestExample, XEmacLite_Initialize.
int XEmacLite_Initialize(XEmacLite *InstancePtr, UINTPTR BaseAddress)
Initialize a specific XEmacLite instance/driver.
The initialization entails: Initialize fields of the XEmacLite instance structure. The driver defaults to polled mode operation. InstancePtr is a pointer to the XEmacLite instance. DeviceId is the unique id of the device controlled by this XEmacLite instance. Passing in a device id associates the generic XEmacLite instance to a specific device, as chosen by the caller or application developer. XST_SUCCESS if initialization was successful.XST_DEVICE_NOT_FOUND/XST_FAILURE if device configuration information was not found for a device with the supplied device ID. None
References XEmacLite_Config::BaseAddress, XEmacLite_CfgInitialize, XEmacLite_LookupConfig.