xemaclite_l.c
void XEmacLite_AlignedWrite(void *SrcPtr, UINTPTR *DestPtr, unsigned ByteCount)
This function aligns the incoming data and writes it out to a 32-bit aligned destination address range.
SrcPtr is a pointer to incoming data of any alignment. DestPtr is a pointer to outgoing data of 32-bit alignment. ByteCount is the number of bytes to write. None. None.
Referenced by XEmacLite_SelfTest, XEmacLite_Send, XEmacLite_SendFrame, XEmacLite_SetMacAddress.
void XEmacLite_AlignedRead(UINTPTR *SrcPtr, void *DestPtr, unsigned ByteCount)
This function reads from a 32-bit aligned source address range and aligns the writes to the provided destination pointer alignment.
SrcPtr is a pointer to incoming data of 32-bit alignment. DestPtr is a pointer to outgoing data of any alignment. ByteCount is the number of bytes to read. None. None.
Referenced by XEmacLite_Recv, XEmacLite_RecvFrame, XEmacLite_SelfTest.
void XEmacLite_SendFrame(UINTPTR BaseAddress, u8 *FramePtr, unsigned ByteCount)
Send an Ethernet frame.
The size is the total frame size, including header. This function blocks waiting for the frame to be transmitted. BaseAddress is the base address of the device FramePtr is a pointer to frame ByteCount is the size, in bytes, of the frame None. This function call is blocking in nature, i.e. it will wait until the frame is transmitted. This function can hang and not exit if the hardware is not configured properly.If the ping buffer is the destination of the data, the argument should be DeviceAddress + XEL_TXBUFF_OFFSET. If the pong buffer is the destination of the data, the argument should be DeviceAddress + XEL_TXBUFF_OFFSET + XEL_BUFFER_OFFSET. The function does not take the different buffers into consideration.
References XEL_TPLR_LENGTH_MASK_HI, XEL_TPLR_LENGTH_MASK_LO, XEL_TPLR_OFFSET, XEL_TSR_XMIT_BUSY_MASK, XEmacLite_AlignedWrite, XEmacLite_GetTxStatus, XEmacLite_IsTxDone, XEmacLite_SetTxStatus, XEmacLite_WriteReg.
u16 XEmacLite_RecvFrame(UINTPTR BaseAddress, u8 *FramePtr)
Receive a frame.
Wait for a frame to arrive. BaseAddress is the base address of the device FramePtr is a pointer to a buffer where the frame will be stored. The type/length field of the frame received. When the type/length field contains the type , XEL_MAX_FRAME_SIZE bytes will be copied out of the buffer and it is up to the higher layers to sort out the frame. This function call is blocking in nature, i.e. it will wait until a frame arrives.If the ping buffer is the source of the data, the argument should be DeviceAddress + XEL_RXBUFF_OFFSET. If the pong buffer is the source of the data, the argument should be DeviceAddress + XEL_RXBUFF_OFFSET + XEL_BUFFER_OFFSET. The function does not take the different buffers into consideration.
References XEL_FCS_SIZE, XEL_HEADER_SIZE, XEL_MAX_FRAME_SIZE, XEL_RPLR_LENGTH_MASK_HI, XEL_RPLR_LENGTH_MASK_LO, XEL_RPLR_OFFSET, XEL_RSR_RECV_DONE_MASK, XEL_RXBUFF_OFFSET, XEmacLite_AlignedRead, XEmacLite_GetRxStatus, XEmacLite_IsRxEmpty, XEmacLite_ReadReg, XEmacLite_SetRxStatus.