xemaclite_i.h
XEMACLITE_I_H
XEmacLite_GetTxActive
Get the TX active location to check status.
This is used to check if the TX buffer is currently active. There isn't any way in the hardware to implement this but the register is fully populated so the driver can set the bit in the send routine and the ISR can clear the bit when the handler is complete. This mimics the correct operation of the hardware if it was possible to do this in hardware. BaseAddress is the base address of the device Contents of active bit in register. C-Style signature: u32 XEmacLite_GetTxActive(u32 BaseAddress)
XEmacLite_SetTxActive
Set the TX active location to update status.
This is used to set the bit indicating which TX buffer is currently active. There isn't any way in the hardware to implement this but the register is fully populated so the driver can set the bit in the send routine and the ISR can clear the bit when the handler is complete. This mimics the correct operation of the hardware if it was possible to do this in hardware. BaseAddress is the base address of the device Mask is the data to be written None C-Style signature: void XEmacLite_SetTxActive(u32 BaseAddress, u32 Mask)
XEmacLite_Config XEmacLite_ConfigTable[][]
This table contains configuration information for each EmacLite device in the system.
void XEmacLite_AlignedWrite(void *SrcPtr, UINTPTR *DestPtr, unsigned ByteCount)
This function aligns the incoming data and writes it out to a 32-bit aligned destination address range.
SrcPtr is a pointer to incoming data of any alignment. DestPtr is a pointer to outgoing data of 32-bit alignment. ByteCount is the number of bytes to write. None. None.
Referenced by XEmacLite_SelfTest, XEmacLite_Send, XEmacLite_SendFrame, XEmacLite_SetMacAddress.
void XEmacLite_AlignedRead(UINTPTR *SrcPtr, void *DestPtr, unsigned ByteCount)
This function reads from a 32-bit aligned source address range and aligns the writes to the provided destination pointer alignment.
SrcPtr is a pointer to incoming data of 32-bit alignment. DestPtr is a pointer to outgoing data of any alignment. ByteCount is the number of bytes to read. None. None.
Referenced by XEmacLite_Recv, XEmacLite_RecvFrame, XEmacLite_SelfTest.
void StubHandler(void *CallBackRef)
This is a stub for the send and receive callbacks.
The stub is here in case the upper layers forget to set the handlers. CallBackRef is a pointer to the upper layer callback reference. None. None.
Referenced by XEmacLite_CfgInitialize, XEmacLite_EnableInterrupts.