xemaclite_example.h
PHY_REG0_OFFSET
PHY_REG1_OFFSET
PHY_REG0_RESET_MASK
PHY_REG0_LOOPBACK_MASK
PHY_REG0_SPD_100_MASK
PHY_REG1_DETECT_MASK
EMACLITE_PHY_DELAY_SEC
EMACLITE_BASEADDR
XEmacLite EmacLiteInstance
u8 TxFrame[XEL_MAX_FRAME_SIZE][XEL_MAX_FRAME_SIZE]
u8 RxFrame[XEL_MAX_FRAME_SIZE][XEL_MAX_FRAME_SIZE]
volatile u32 RecvFrameLength
volatile int TransmitComplete
void EmacLitePhyDelay(unsigned int Seconds)
For PPC we use a usleep call, for Microblaze we use an assembly loop that is roughly the same regardless of optimization level, although caches and memory access time can make the delay vary.
Just keep in mind that after resetting or updating the PHY modes, the PHY typically needs time to recover.None None
Referenced by EmacLiteEnablePhyLoopBack.
u32 EmacLitePhyDetect(XEmacLite *InstancePtr)
This function detects the PHY address by looking for successful MII status register contents (PHY register 1).
It looks for a PHY that supports auto-negotiation and 10Mbps full-duplex and half-duplex. So, this code won't work for PHYs that don't support those features, but it's a bit more general purpose than matching a specific PHY manufacturer ID.Note also that on some (older) Xilinx ML4xx boards, PHY address 0 does not properly respond to this query. But, since the default is 0 and assuming no other address responds, then it seems to work OK. InstancePtr is the pointer to the instance of EmacLite driver. The address of the PHY device detected (returns 0 if not detected). The bit mask (0x1808) of the MII status register (PHY Register 1) used in this function are: 0x1000: 10Mbps full duplex support. 0x0800: 10Mbps half duplex support. 0x0008: Auto-negotiation support.
References XEmacLite_PhyRead.
Referenced by EmacLiteIntrExample, EmacLitePhyLoopbackExample, EmacLitePolledExample.
int EmacLiteEnablePhyLoopBack(XEmacLite *InstancePtr, u32 PhyAddress)
This function enables the MAC loopback on the PHY.
InstancePtr is the pointer to the instance of EmacLite driver. PhyAddress is the address of the Phy device. XST_SUCCESS if the loop back is enabled.XST_FAILURE if the loop back was not enabled. None.
References EmacLitePhyDelay, XEmacLite_PhyWrite.
Referenced by EmacLiteIntrExample, EmacLitePhyLoopbackExample, EmacLitePolledExample.
int EmacLiteDisablePhyLoopBack(XEmacLite *InstancePtr, u32 PhyAddress)
This function disables the MAC loopback on the PHY.
InstancePtr is the pointer to the instance of EmacLite driver. PhyAddress is the address of the Phy device. XST_SUCCESS if the loop back was disabled.XST_FAILURE if the loop back was not disabled. None.
References XEmacLite_PhyRead, XEmacLite_PhyWrite.
Referenced by EmacLiteIntrExample, EmacLitePhyLoopbackExample, EmacLitePolledExample.