xsem_client_api.h
CMD_ACK_CFR_INIT
CRAM Initialization Acknowledgment ID.
CMD_ACK_CFR_START_SCAN
CRAM Start Scan Acknowledgment ID.
CMD_ACK_CFR_STOP_SCAN
CRAM Stop Scan Acknowledgment ID.
CMD_ACK_CFR_NJCT_ERR
CRAM Error Injection Acknowledgment ID.
CMD_ACK_SEM_READ_FRAME_ECC
SEM Read Frame ECC Acknowledgment ID.
Referenced by main.
CMD_ACK_CFR_GET_GLDN_CRC
SEM Read Golden CRC Acknowledgment ID.
CMD_ACK_CFR_GET_TF
SEM Get Total Frames Acknowledgment ID.
CMD_ACK_NPI_STARTSCAN
NPI Start Scan Acknowledgment ID.
Referenced by main.
CMD_ACK_NPI_STOPSCAN
NPI Stop Scan Acknowledgment ID.
Referenced by main.
CMD_ACK_NPI_ERRINJECT
NPI Error Injection Acknowledgment ID.
Referenced by main.
CMD_ACK_NPI_GET_GLDN_SHA
NPI Get NPI Golden SHA Acknowledgment ID.
Referenced by main.
CMD_ACK_SEM_GET_CONFIG
SEM Get configuration Acknowledgment ID.
Referenced by main.
MAX_CRAMERR_REGISTER_CNT
Maximum CRAM error register count.
Referenced by XSem_CmdCfrGetStatus.
MAX_ADDRLOC
Maximum CRAM error High and Low register count.
MAX_NPI_SLV_SKIP_CNT
Maximum NPI slave skip count.
Referenced by main, XSem_CmdNpiGetStatus.
MAX_NPI_ERR_INFO_CNT
Maximum NPI Error info count.
Referenced by main, XSem_CmdNpiGetStatus.
PMC_RAM_BASEADDR
PMC_RAM - Base Address.
PMC_RAM_SEM_NPI_STATUS
SEM NPI Status.
Referenced by XSem_CmdNpiGetStatus.
PMC_RAM_SEM_NPI_SLVSKIP_CNT0
SEM NPI Slave Skip Count.
Referenced by XSem_CmdNpiGetStatus.
PMC_RAM_SEM_NPI_SCAN_CNT
SEM NPI Scan Count.
Referenced by XSem_CmdNpiGetStatus.
PMC_RAM_SEM_NPI_HEARTBEAT_CNT
SEM NPI Heartbeat Count.
Referenced by XSem_CmdNpiGetStatus.
PMC_RAM_SEM_NPIERR_INFO0
SEM NPI Error Info 0.
Referenced by XSem_CmdNpiGetStatus.
PMC_RAM_SEM_NPIERR_INFO1
SEM NPI Error Info 1.
PMC_RAM_SEM_CRAM_STATUS
PMC_RAM_SEM_CRAM_STATUS.
Referenced by XSem_CmdCfrGetStatus.
PMC_RAM_SEM_CRAMERR_ADDRL0
PMC_RAM_SEM_CRAMERR_ADDRL0.
Referenced by XSem_CmdCfrGetStatus.
PMC_RAM_SEM_CRAMERR_ADDRH0
PMC_RAM_SEM_CRAMERR_ADDRH0.
Referenced by XSem_CmdCfrGetStatus.
PMC_RAM_SEM_CRAM_COR_BITCNT
PMC_RAM_SEM_CRAM_COR_BITCNT.
Referenced by XSem_CmdCfrGetStatus.
CMD_ID_CFR_INIT
Command ID for CRAM initialization.
Referenced by XSem_CmdCfrInit.
CMD_ID_CFR_START_SCAN
Command ID for CRAM Start scan.
Referenced by XSem_CmdCfrStartScan.
CMD_ID_CFR_STOP_SCAN
Command ID for CRAM Stop scan.
Referenced by XSem_CmdCfrStopScan.
CMD_ID_CFR_NJCT_ERR
Command ID for CRAM error injection.
Referenced by XSem_CmdCfrNjctErr.
CMD_ID_CFR_RDFRAME_ECC
Command ID for CRAM Read Frame ECC.
Referenced by XSem_CmdCfrReadFrameEcc.
CMD_NPI_STARTSCAN
Command ID for NPI Start scan.
Referenced by XSem_CmdNpiStartScan.
CMD_NPI_STOPSCAN
Command ID for NPI Stop scan.
Referenced by XSem_CmdNpiStopScan.
CMD_NPI_ERRINJECT
Command ID for NPI error injection.
Referenced by XSem_CmdNpiInjectError.
CMD_NPI_GET_GLDN_SHA
Command ID for NPI Get Golden SHA.
Referenced by XSem_CmdNpiGetGldnSha.
CMD_EM_EVENT_REGISTER
Event Notification Register Command ID.
Referenced by XSem_RegisterEvent.
CMD_ID_SEM_GET_CONFIG
Command ID for SEM Get Configuration.
Referenced by XSem_CmdGetConfig.
CMD_ID_SEM_GET_CRC
Command ID for SEM Get Configuration for SSIT devices.
NPI_MAX_DESCRIPTORS
Total number of possible descriptors in NPI scan.
CFRAME_BASE_ADDRESS
Base address for CFRAME Registers.
Referenced by XSem_CmdCfrGetCrc, XSem_CmdCfrGetTotalFrames.
CFRAME_ROW_OFFSET
Offset address to select CFRAME Row instance.
Referenced by XSem_CmdCfrGetCrc, XSem_CmdCfrGetTotalFrames.
CFRAME_SEU_CRC_ADDR
Offset address for Golden CRC.
Referenced by XSem_CmdCfrGetCrc.
CFRAME_LAST_BOT_ADDR
Offset address for reading Total frames in type 0, 1, 2, 3.
Referenced by XSem_CmdCfrGetTotalFrames.
CFRAME_MAX_TYPE
Maximum number of frame types.
Referenced by main.
CFRAME_BIT_0_19_MASK
MASK for 0 to 19 bits for getting Type_0, Type_4 frames.
Referenced by XSem_CmdCfrGetTotalFrames.
CFRAME_BIT_20_39_MASK_LOW
MASK for 20 to 31 bits for getting Type_1, Type_5 frames.
Referenced by XSem_CmdCfrGetTotalFrames.
CFRAME_BIT_20_39_MASK_HIGH
MASK for 32 to 39 bits for getting Type_1, Type_5 frames.
Referenced by XSem_CmdCfrGetTotalFrames.
CFRAME_BIT_20_39_SHIFT_R
Shift for 20 to 31 bits for getting Type_1, Type_5 frames.
Referenced by XSem_CmdCfrGetTotalFrames.
CFRAME_BIT_20_39_SHIFT_L
Shift for 32 to 39 bits for getting Type_1, Type_5 frames.
Referenced by XSem_CmdCfrGetTotalFrames.
CFRAME_BIT_40_59_MASK
MASK for 40 to 59 bits for getting Type_2, Type_6 frames.
Referenced by XSem_CmdCfrGetTotalFrames.
CFRAME_BIT_40_59_SHIFT_R
Shift for 40 to 59 bits for getting Type_2, Type_6 frames.
Referenced by XSem_CmdCfrGetTotalFrames.
CFRAME_BIT_60_79_MASK_LOW
MASK for 60 to 63 bits for getting Type_3.
Referenced by XSem_CmdCfrGetTotalFrames.
CFRAME_BIT_60_79_MASK_HIGH
MASK for 64 to 79 bits for getting Type_3.
Referenced by XSem_CmdCfrGetTotalFrames.
CFRAME_BIT_60_79_SHIFT_R
Shift for 60 to 63 bits for getting Type_3.
Referenced by XSem_CmdCfrGetTotalFrames.
CFRAME_BIT_60_79_SHIFT_L
Shift for 64 to 79 bits for getting Type_3.
Referenced by XSem_CmdCfrGetTotalFrames.
CMD_ID_CFR_GET_TF
Command ID for CRAM Get Total Frames.
XSEM_NOTIFY_CRAM
SEM CRAM Module Notification ID.
XSEM_NOTIFY_NPI
SEM NPI Module Notification ID.
XSEM_EVENT_ERROR
SEM Generic Event ID.
XSEM_EVENT_CRAM_UNCOR_ECC_ERR
SEM CRAM Uncorrectable ECC Error Event.
XSEM_EVENT_CRAM_CRC_ERR
SEM CRAM Uncorrectable CRC Error Event.
XSEM_EVENT_CRAM_INT_ERR
SEM CRAM Internal or Fatal Errors.
XSEM_EVENT_CRAM_COR_ECC_ERR
SEM Correctable ECC Error Event, detected when correction is disabled.
XSEM_EVENT_NPI_CRC_ERR
SEM NPI Uncorrectable CRC Error Event.
XSEM_EVENT_NPI_DESC_FMT_ERR
NPI Unsupported Descriptor Format.
XSEM_EVENT_NPI_DESC_ABSNT_ERR
NPI Descriptors absent for Scan.
XSEM_EVENT_NPI_SHA_IND_ERR
NPI SHA Indicator mismatch error.
XSEM_EVENT_NPI_SHA_ENGINE_ERR
NPI SHA engine error.
XSEM_EVENT_NPI_PSCAN_MISSED_ERR
NPI Periodic Scan Missed Error.
XSEM_EVENT_NPI_CRYPTO_EXPORT_SET_ERR
NPI Cryptographic Accelerator Disabled error.
XSEM_EVENT_NPI_SFTY_WR_ERR
NPI Safety Write Failure.
XSEM_EVENT_NPI_GPIO_ERR
NPI GPIO Error event.
XSEM_EVENT_NPI_SELF_DIAG_FAIL
NPI Self Diagnostic event.
XSEM_EVENT_NPI_GT_ARB_FAIL
NPI GT arbitration failure event.
GT arbitration failure is notified for every 5 times GT arbitration failure is encountered in NPI scanSEM Event_NPI GT Arbitration Fail
XSEM_EVENT_ENABLE
SEM Event Flags.
SEM Event Notification Enable
XSEM_EVENT_DISABLE
SEM Event Notification Disable.
XSEM_SSIT_MASTER_SLR_MASK
The below definitions are used for decoding response from PLM during particular SLR failure.
SSIT master SLR mask
XSEM_SSIT_SLAVE_SLR0_MASK
SSIT slave SLR0 mask.
XSEM_SSIT_SLAVE_SLR1_MASK
SSIT slave SLR1 mask.
XSEM_SSIT_SLAVE_SLR2_MASK
SSIT slave SLR2 mask.
XSEM_SSIT_ALL_SLAVE_SLRS_MASK
SSIT all slave SLR mask.
XSEM_SSIT_ALL_SLRS_MASK
SSIT all SLR mask.
XSEM_SSIT_SLR_CHECK_MASK
SSIT Check SLR mask.
XSEM_SSIT_MASTER_SLR_ID
The below definitions are used for targeting SLRs while sending commands.
SSIT master SLR index
XSEM_SSIT_SLAVE0_SLR_ID
SSIT slave SLR0 index.
XSEM_SSIT_SLAVE1_SLR_ID
SSIT slave SLR1 index.
XSEM_SSIT_SLAVE2_SLR_ID
SSIT slave SLR2 index.
XSEM_SSIT_INVALID_SLR_ID
SSIT invalid SLR index.
XSEM_SSIT_ALL_SLRS_ID
SSIT all SLRs index.
XStatus XSem_CmdCfrInit(XIpiPsu *IpiInst, XSemIpiResp *Resp)
This function is used to initialize CRAM scan from user application.
Primarily this function sends an IPI request to PLM to start CRAM Scan Initialization, waits for PLM to process the request and reads the response message. In case of EL1 Non-Secure mode, this function generates an SMC call to TF-A. The SMC request goes to the PLM through the TF-A. This function reads the response of the SMC call and returns the status. IpiInst Pointer to IPI driver instance Resp Structure Pointer of IPI response Resp->RespMsg1: Acknowledgment ID of CRAM Initialization(0x10301)Resp->RespMsg2: Status of CRAM Initialization 0x01000000U - ECC/CRC error detected during calibration in case of SWECC 0X00000080U - Calibration timeout 0X00002000U - Internal error This API returns the success or failure. XST_FAILURE: On CRAM Initialization failureXST_SUCCESS: On CRAM Initialization success
References CMD_ID_CFR_INIT, XSemIpiResp::RespMsg1, XSemIpiResp::RespMsg2.
XStatus XSem_CmdCfrStartScan(XIpiPsu *IpiInst, XSemIpiResp *Resp)
This function is used to start CRAM scan from user application.
Primarily this function sends an IPI request to PLM to invoke SEM CRAM StartScan, waits for PLM to process the request and reads the response message. In case of EL1 Non-Secure mode, this function generates an SMC call to TF-A. The SMC request goes to the PLM through the TF-A. This function reads the response of the SMC call and returns the status. IpiInst Pointer to IPI driver instance Resp Structure Pointer of IPI response Resp->RespMsg1: Acknowledgment ID of CRAM start scan(0x10302)Resp->RespMsg2: Status of CRAM start scan 0x2000 – Null pointer error 0x00F00000 – Active crc/uncor error 0x00500000 – CRAM init not done 0x00600000 – Start scan failed This API returns the success or failure. XST_FAILURE: On CRAM start scan failureXST_SUCCESS: On CRAM start scan success
References CMD_ID_CFR_START_SCAN, XSemIpiResp::RespMsg1, XSemIpiResp::RespMsg2.
XStatus XSem_CmdCfrStopScan(XIpiPsu *IpiInst, XSemIpiResp *Resp)
This function is used to stop CRAM scan from user application.
Primarily this function sends an IPI request to PLM to invoke SEM CRAM StopScan, waits for PLM to process the request and reads the response message. In case of EL1 Non-Secure mode, this function generates an SMC call to TF-A. The SMC request goes to the PLM through the TF-A. This function reads the response of the SMC call and returns the status. IpiInst Pointer to IPI driver instance Resp Structure Pointer of IPI response Resp->RespMsg1: Acknowledgment ID of CRAM stop scan(0x10303)Resp->RespMsg2: Status of CRAM stop scan 0x00500000 – CRAM init not done 0x00700000 – Stop scan failed This API returns the success or failure. XST_FAILURE: On CRAM stop scan failureXST_SUCCESS: On CRAM stop scan success
References CMD_ID_CFR_STOP_SCAN, XSemIpiResp::RespMsg1, XSemIpiResp::RespMsg2.
XStatus XSem_CmdCfrNjctErr(XIpiPsu *IpiInst, XSemCfrErrInjData *ErrDetail, XSemIpiResp *Resp)
This function is used to inject an error at a valid location in CRAM from user application.
Primarily this function sends an IPI request to PLM to perform error injection in CRAM with user provided arguments in *ErrDetail, waits for PLM to process the request and reads the response message. In case of EL1 Non-Secure mode, this function generates an SMC call to TF-A. The SMC request goes to the PLM through the TF-A. This function reads the response of the SMC call and returns the status. IpiInst Pointer to IPI driver instance ErrDetail Structure Pointer with Error Injection details ErrDetail->Row : Row Number (Min: 0 , Max: (value at CFU_ROW_RANGE)-1)ErrDetail->Efar : Frame Address Frame Number [0:19] (Refer note)Block Type [20:22] ErrDetail->Qword : Quad Word(Min: 0, Max: 24)ErrDetail->Bit : Bit Position(Min: 0, Max: 127) Resp Structure Pointer of IPI response Resp->RespMsg1: Acknowledgment ID of CRAM error injection(0x10304)Resp->RespMsg2: Status of CRAM error injection 0x00002000 – Null pointer error 0x00500000 – CRAM init not done 0x00800000 – Invalid row 0x00900000 – Invalid qword 0x00A00000 – Invalid bit 0x00B00000 – Invalid frame address 0x00C00000 – Unexpected bits flipped 0x00D00000 – Masked bit 0x00E00000 – Invalid block type 0x00F00000 – Active crc/uncor ecc error in CRAM This API returns the success or failure. XST_FAILURE: On CRAM error injection failureXST_SUCCESS: On CRAM error injection success Total number of frames in a row is not same for all rows.XSem_CmdCfrGetTotalFrames API is provided to know the total number of frames in a row for each block. Output param (FrameCntPtr) of XSem_CmdCfrGetTotalFrames API is updated with total number of frames of each block type for the input row. If a particular block in a row has 0 frames, then error injection shall not be performed. Range of Frame number: 0 to (FrameCntPtr[n] - 1) where n is block type with range 0 to 6. - The safe location to perform error injection is QWORD 12 which has ECC bits. The error injection will not change the design behaviour.
References XSemCfrErrInjData::Efar, XSemCfrErrInjData::Bit, XSemCfrErrInjData::Qword, XSemCfrErrInjData::Row, CMD_ID_CFR_NJCT_ERR, XSemIpiResp::RespMsg1, XSemIpiResp::RespMsg2.
XStatus XSem_CmdCfrGetStatus(XSemCfrStatus *CfrStatusInfo)
This function is used to read all CRAM Status registers from PMC RAM and send to user application.
CfrStatusInfo Structure Pointer with CRAM Status details CfrStatusInfo->Status: Provides details about CRAM scan Bit [31-29]: ReservedBit [28-25]: CRAM Target SLR ID 0001: Target is master only0010: Target is slave 0 only0100: Target is slave 1 only1000: Target is slave 2 onl Bit [24:20]: CRAM Error codes 00001: Unexpected CRC error when CRAM is not in observation state00010: Unexpected ECC error when CRAM is not in Observation or Initialization state00011: Safety write error in SEU handler00100: ECC/CRC ISR not found in any Row00101: CRAM Initialization is not done00110: CRAM Start Scan failure00111: CRAM Stop Scan failure01000: Invalid Row for Error Injection01001: Invalid QWord for Error Injection01010: Invalid Bit for Error Injection01011: Invalid Frame Address for Error Injection01100: Unexpected Bit flip during Error Injection01101: Masked Bit during Injection01110: Invalid Block Type for Error Injection01111: CRC or Uncorrectable Error or correctable error(when correction is disabled) is active in CRAM10000: ECC or CRC Error detected during CRAM Calibration in case of SWECC Bit [19-18]: ReservedBit [17]: 0: CRAM scan is enabled in design 1: CRAM scan is disabled in designBit [16]: 0: CRAM scan is not initialized 1: CRAM Initialization is completedBit [15-14]: CRAM Correctable ECC error status 00: No Correctable error encountered01: Correctable error is detected and corrected10: Correctable error is detected but not corrected (Correction is disabled)11: Reserved Bit [13]: 0: No error in CRAM scan 1: CRAM scan has internal error (Null pointer access/Safety write error) In this error condition, scan will be stopped and an event will be sent to R5.Bit [12]: 0: No error in error decoding 1: Invalid Error Location is reported In this error condition, scan will be stopped and an event will be sent to R5.Bit [11]: 0: No correctable error detected 1: Correctable ECC error detected In this condition, an event will be sent to R5. If correction is disabled, then scan will be stopped. Else, scan will continue to run.Bit [10]: 0: No CRC error 1: CRC error is detected by CRAM. In this error condition, scan will be stopped and an event will be sent to R5.Bit [09]: 0: No uncorrectable error 1: Uncorrectable ECC error is detected In this error condition, scan will be stopped and an event will be sent to R5.Bit [08]: 0: No error in CRAM scan start-up test 1: CRAM start-up test failure In this error condition, scan will be stopped.Bit [07]: 0: No error during CRAM calibration` 1: CRAM Calibration Timeout error In this error condition, scan will be stopped and an event will be sent to R5.Bit [06]: 0: CRAM scan is not in the fatal state 1: CRAM scan is in the fatal state This bit is for CRAM scan state.Bit [05]: 0: CRAM scan is not in the error injection state 1: CRAM scan is in the error injection state This bit is for CRAM scan state.Bit [04]: 0: CRAM scan is not in the idle state 1: CRAM scan is in the idle state This bit is for CRAM scan state.Bit [03]: 0: CRAM scan is not in the correction state 1: CRAM scan is in the correction state This bit is for CRAM scan state.Bit [02]: 0: CRAM scan is not in the observation state 1: CRAM scan is in the observation state This bit is for CRAM scan state.Bit [01]: 0: CRAM scan is not in the Initialization state 1: CRAM scan is in the Initialization state This bit is for CRAM scan state.Bit [00]: CRAM Scan is included in design This bit is for CRAM scan state. CfrStatusInfo->ErrAddrL: This stores the low address of the last 7 corrected error details if correction is enabled in design. Bit [31:28]: ReservedBit [27:23]: QWord location where error was detectedBit [22:16]: Bit location where error was detectedBit [15:2]: ReservedBit [1:0]: Define validity of error address. 00: Info not available01: Address out of range10: Reserved11: Address valid CfrStatusInfo->ErrAddrH: This stores the high address of the last 7 corrected error details if correction is enabled in design. Bits[31:27]: ReservedBits[26:23]: Row number where error was detectedBits[22:20]: Block type of the frameBits[19:0]: Frame address where error was detected CfrStatusInfo->ErrCorCnt: Counter value of Correctable Error Bits This API returns the success or failure. XST_FAILURE: If NULL pointer reference of CfrStatusInfoXST_SUCCESS: On successful read from PMC RAM
References XSemCfrStatus::Status, PMC_RAM_SEM_CRAM_STATUS, XSemCfrStatus::ErrCorCnt, PMC_RAM_SEM_CRAM_COR_BITCNT, MAX_CRAMERR_REGISTER_CNT, XSemCfrStatus::ErrAddrL, PMC_RAM_SEM_CRAMERR_ADDRL0, XSemCfrStatus::ErrAddrH, PMC_RAM_SEM_CRAMERR_ADDRH0.
Referenced by main.
XStatus XSem_CmdCfrReadFrameEcc(XIpiPsu *IpiInst, u32 CframeAddr, u32 RowLoc, XSemIpiResp *Resp)
This function is used to Read frame ECC of a particular Frame.
Primarily this function sends an IPI request to PLM to invoke SEM CRAM SendFrameEcc, waits for PLM to process the request and reads the response message. In case of EL1 Non-Secure mode, this function generates an SMC call to TF-A. The SMC request goes to the PLM through the TF-A. This function reads the response of the SMC call and returns the status. IpiInst Pointer to IPI driver instance CframeAddr Frame Address Frame Number [0:19] (Refer note)Block Type [20:22] RowLoc Row index(Min: 0 , Max: CFU_ROW_RANGE -1) Resp Structure Pointer of IPI response Resp->RespMsg1: Acknowledgment ID of CRAM Send Frame ECC(0x3030A)Resp->RespMsg2: Segment 0 ECC valueResp->RespMsg3: Segment 1 ECC valueResp->RespMsg4: Status of CRAM stop scan This API returns the success or failure. XST_FAILURE: On CRAM Read Frame ECC failureXST_SUCCESS: On CRAM Read Frame ECC success Total number of frames in a row is not same for all rows.XSem_CmdCfrGetTotalFrames API is provided to know the total number of frames in a row for each block. Output param (FrameCntPtr) of XSem_CmdCfrGetTotalFrames API is updated with total number of frames of each block type for the input row. If a particular block in a row has 0 frames, then error injection shall not be performed. Range of Frame number: 0 to (FrameCntPtr[n] - 1) where n is block type with range 0 to 6. - The safe location to perform error injection is QWORD 12 which has ECC bits. The error injection will not change the design behaviour.
References CMD_ID_CFR_RDFRAME_ECC, XSemIpiResp::RespMsg1, XSemIpiResp::RespMsg2, XSemIpiResp::RespMsg3, XSemIpiResp::RespMsg4.
Referenced by main.
u32 XSem_CmdCfrGetCrc(u32 RowIndex)
This function is used to read CFRAME golden CRC for a row.
RowIndex Row index for which CRC to be read (Min: 0 , Max: CFU_ROW_RANGE -1) This API returns the Golden CRC for a given Row. Total number of rows is not same for all platforms.The number maximum rows (CFU_ROW_RANGE) can be obtained by reading the address CFU_ROW_RANGE(0XF12B006C).
References CFRAME_BASE_ADDRESS, CFRAME_ROW_OFFSET, CFRAME_SEU_CRC_ADDR.
Referenced by main.
void XSem_CmdCfrGetTotalFrames(u32 RowIndex, u32 *FrameCntPtr)
This function is used to read total frames in a row.
RowIndex Row index for which total number of frames is to be read (Min: 0 , Max: CFU_ROW_RANGE -1) FrameCntPtr Pointer to store Total frames FrameCntPtr[0] : Type_0 total framesFrameCntPtr[1] : Type_1 total framesFrameCntPtr[2] : Type_2 total framesFrameCntPtr[3] : Type_3 total framesFrameCntPtr[4] : Type_4 total framesFrameCntPtr[5] : Type_5 total framesFrameCntPtr[6] : Type_6 total frames Total number of frames in a row is not same for all rows.XSem_CmdCfrGetTotalFrames API is provided to know the total number of frames in a row for each block. Output param (FrameCntPtr) of XSem_CmdCfrGetTotalFrames API is updated with total number of frames of each block type for the input row. If a particular block in a row has 0 frames, then error injection shall not be performed. Range of Frame number: 0 to (FrameCntPtr[n] - 1) where n is block type with range 0 to 6.The safe location to perform error injection is QWORD 12 which has ECC bits. The error injection will not change the design behaviour.
References CFRAME_BASE_ADDRESS, CFRAME_ROW_OFFSET, CFRAME_LAST_BOT_ADDR, CFRAME_BIT_0_19_MASK, CFRAME_BIT_20_39_MASK_LOW, CFRAME_BIT_20_39_SHIFT_R, CFRAME_BIT_20_39_MASK_HIGH, CFRAME_BIT_20_39_SHIFT_L, CFRAME_BIT_40_59_MASK, CFRAME_BIT_40_59_SHIFT_R, CFRAME_BIT_60_79_MASK_LOW, CFRAME_BIT_60_79_SHIFT_R, CFRAME_BIT_60_79_MASK_HIGH, CFRAME_BIT_60_79_SHIFT_L.
Referenced by main.
XStatus XSem_CmdNpiStartScan(XIpiPsu *IpiInst, XSemIpiResp *Resp)
This function is used to start NPI scan from user application.
Primarily this function sends an IPI request to PLM to invoke SEM NPI StartScan, waits for PLM to process the request and reads the response message. In case of EL1 Non-Secure mode, this function generates an SMC call to TF-A. The SMC request goes to the PLM through the TF-A. This function reads the response of the SMC call and returns the status. IpiInst Pointer to IPI driver instance Resp Structure Pointer of IPI response Resp->RespMsg1: Acknowledgment ID of NPI start scan(0x10305)Resp->RespMsg2: Status of NPI start scan (0: Success, 1: Failure) This API returns the success or failure. XST_FAILURE: On NPI start scan failureXST_SUCCESS: On NPI start scan success
References CMD_NPI_STARTSCAN, XSemIpiResp::RespMsg1, XSemIpiResp::RespMsg2.
Referenced by main.
XStatus XSem_CmdNpiStopScan(XIpiPsu *IpiInst, XSemIpiResp *Resp)
This function is used to stop NPI scan from user application.
Primarily this function sends an IPI request to PLM to invoke SEM NPI StopScan, waits for PLM to process the request and reads the response message. In case of EL1 Non-Secure mode, this function generates an SMC call to TF-A. The SMC request goes to the PLM through the TF-A. This function reads the response of the SMC call and returns the status. IpiInst Pointer to IPI driver instance Resp Structure Pointer of IPI response Resp->RespMsg1: Acknowledgment ID of NPI stop scan(0x10306)Resp->RespMsg2: Status of NPI stop scan (0: Success, 1: Failure) This API returns the success or failure. XST_FAILURE: On NPI stop scan failureXST_SUCCESS: On NPI stop scan success
References CMD_NPI_STOPSCAN, XSemIpiResp::RespMsg1, XSemIpiResp::RespMsg2.
Referenced by main.
XStatus XSem_CmdNpiInjectError(XIpiPsu *IpiInst, XSemIpiResp *Resp)
This function is used to inject SHA error in NPI descriptor list (in the first NPI descriptor) from user application.
Primarily this function sends an IPI request to PLM to invoke SEM NPI ErrorInject, waits for PLM to process the request and reads the response message. In case of EL1 Non-Secure mode, this function generates an SMC call to TF-A. The SMC request goes to the PLM through the TF-A. This function reads the response of the SMC call and returns the status. IpiInst Pointer to IPI driver instance Resp Structure Pointer of IPI response Resp->RespMsg1: Acknowledgment ID of NPI error injection(0x10307)Resp->RespMsg2: Status of NPI error injection (0: Success, 1: Failure) This API returns the success or failure. XST_FAILURE: On NPI error injection failureXST_SUCCESS: On NPI error injection success The caller shall invoke this XSem_CmdNpiInjectError function again to correct the injected error in NPI descriptor.
References CMD_NPI_ERRINJECT, XSemIpiResp::RespMsg1, XSemIpiResp::RespMsg2.
Referenced by main.
XStatus XSem_CmdNpiGetGldnSha(XIpiPsu *IpiInst, XSemIpiResp *Resp, XSem_DescriptorData *DescData)
This function is used to get golden SHA In case of EL1 Non-Secure mode, this function generates an SMC call to TF-A.
The SMC request goes to the PLM through the TF-A. This function reads the response of the SMC call and returns the status. IpiInst Pointer to IPI driver instance Resp Structure Pointer of IPI response Resp->RespMsg1: Acknowledgment ID of NPI get golden SHA(0x10310)Resp->RespMsg2: Status of NPI get golden SHA DescData Structure pointer to hold total descriptor count, golden SHA and information related to descriptors This API returns the success or failure. XST_FAILURE: On NPI golden SHA retrieve failureXST_SUCCESS: On NPI golden SHA retrieve success
References CMD_NPI_GET_GLDN_SHA, XSemIpiResp::RespMsg1, XSemIpiResp::RespMsg2.
Referenced by main.
XStatus XSem_CmdNpiGetStatus(XSemNpiStatus *NpiStatusInfo)
This function is used to read all NPI Status registers from PMC RAM and send to user application.
NpiStatusInfo Structure Pointer with NPI Status details NpiStatusInfo->Status: Provides details about NPI scan Bit [31]: 0 - No error, SHA-3 engine is present 1 - Cryptographic acceleration blocks are disabled for export compliance. No support for NPI scan, an event will be sent to R5Bit [30]: 0 - NPI scan is running for scheduled interval 1 - Indicates NPI scan failed to run on scheduled interval. If NPI scan is not executed as per the configured periodicity, the error will notified to R5 user. The scan will continue to runBit [29]: 0- No descriptor missed during scanning 1- Indicates NPI scan failed to scan all descriptors completely (excluding arbitration failures). This will be notified to R5 user and the scan will continue to run.Bit [28]: 0 - NPI scan executing within budget time 1 - Indicates NPI scan has exceeded maximum budget execution time of 20ms. This will be notified to R5 user and the scan will continue to run.Bit [27]: 0 - No error in SLR to SLR communication 1 - Indicates failure in SSIT internal communication channel This bit is applicable for SSIT devices.Bit [26]: ReservedBit [25]: 0 - No error in PMC_PL_GPO 1 - Indicates GPO Initialization or write failed. This is HW failure. In this condition, the scan will be stopped, and notification will be sent to R5Bit [24]: 0 - No error SHA-3 engine 1 - Indicates SHA engine failed to function during initialization or start or DMA transfer. This is HW failure. In this condition, the scan will be stopped, and notification will be sent to R5Bit [23]: 0 - No error in register writes 1 - Indicates the register write and read back failure occurred during the scan. This is HW failure. In this condition, the scan will be stopped, and notification will be sent to R5Bit [22]: ReservedBit [21]: 0 - No error in DDR calibration 1 - Indicates NPI DDRMC Main Slave Arbitration Timeout occurred during the scan. If the DDRMC calibration is not done, the descriptor will be skipped and scan will continue to run for next descriptorBit [20]: 0 - No error in descriptor format 1 - Indicates NPI Descriptor has invalid format. This failure indicates that there is some corruption in the XilSEM NPI descriptor data. The scan will be stopped, and notification will be sent to R5Bit [19]: 0 - No error in NPI Descriptor SHA header 1 - Indicates NPI Descriptor SHA Header mismatch occurred during the scan. This failure indicates that there is some corruption in the XilSEM NPI descriptor data. The scan will be stopped, and notification will be sent to R5Bit [18]: 0 - NPI descriptors are present in the memory 1 - Indicates the absence of NPI Descriptor (Zero descriptors) This failure indicates that there is some corruption in the XilSEM NPI descriptor data. The scan will be stopped, and notification will be sent to R5Bit [17]: 0 - No error in SHA comparison during run time 1- Indicates SHA comparison failure occurred during run time. This failure indicates that there is some bit flip in the NPI registers. The scan will be stopped and an event will be sent to R5Bit [16]: 0 - No error in SHA comparison during first scan 1- Indicates SHA comparison failure occurred during initialization. This failure indicates that there is some bit flip in the NPI registers. The scan will be stopped and an event will be sent to R5Bit [15-12]: NPI Target SLR ID 0001 - Target is master only 0010 - Target is slave 0 only 0100 - Target is slave 1 only 1000 - Target is slave 2 onlyBit [11]: 0 - NPI scan task is not added to PLM Scheduler to run periodically 1 - NPI scan task is added to PLM Scheduler to run periodically This bit is for NPI scan state information.Bit [10]: NPI scan is suspended 0 - NPI scan is not suspended 1 - NPI scan is suspended due to errors This bit is for NPI scan state information.Bit [09]: 0 - NPI scan initialization is not done 1 - NPI scan initialization is done This bit is for NPI scan state information.Bit [08]: 0 - NPI scan is present in the design 1 - NPI scan disabled in the design This bit is for NPI scan state information.Bit [07-06]: ReservedBit [05]: 0 - No internal error 1 - NPI scan is in error state (due to timeouts, invalid descriptors) This bit is for NPI scan state information.Bit [04]: 0 - No error in NPI Scan 1 - NPI scan in SHA comparison mismatch error state. This bit is for NPI scan state information.Bit [03]: 0 - NPI scan is not in SHA error inject state 1 - NPI scan is in SHA error inject state. This bit is for NPI scan state information.Bit [02]: 0 - NPI scan is not in scan state 1 - NPI scan is in scan state. This bit is for NPI scan state information.Bit [01]: 0 - NPI scan is not in initialization state 1 - NPI scan is in initialization state This bit is for NPI scan state information.Bit [00]: 0 - NPI scan is not in idle state 1 - NPI scan is in idle state This bit is for NPI scan state information. NpiStatusInfo->SlvSkipCnt: Provides NPI descriptor slave skip counter value if arbitration failure. This is 8 words result to accommodate 32 1-Byte skip counters for individual slaves arbitration failures. Slaves can be DDRMC Main, GT for which arbitration is required before performing scanning.NpiStatusInfo->ScanCnt: NPI scan counter value. This counter represents number of periodic scan cycle completion.NpiStatusInfo->HbCnt: NPI heartbeat counter value. This counter represents number of scanned descriptor slaves.NpiStatusInfo->ErrInfo: NPI scan error information if SHA mismatch is detected. This is 2 word information. Word 0: Node ID of descriptor for which SHA mismatch is detectedWord 1 Bit [15-8]: NPI descriptor index numberWord 1 Bit [7-0]: NPI Slave Skip count Index This API returns the success or failure. XST_FAILURE: If NULL pointer reference of NpiStatusInfoXST_SUCCESS: On successful read from PMC RAM
References XSemNpiStatus::Status, PMC_RAM_SEM_NPI_STATUS, XSemNpiStatus::ScanCnt, PMC_RAM_SEM_NPI_SCAN_CNT, XSemNpiStatus::HbCnt, PMC_RAM_SEM_NPI_HEARTBEAT_CNT, MAX_NPI_SLV_SKIP_CNT, XSemNpiStatus::SlvSkipCnt, PMC_RAM_SEM_NPI_SLVSKIP_CNT0, MAX_NPI_ERR_INFO_CNT, XSemNpiStatus::ErrInfo, PMC_RAM_SEM_NPIERR_INFO0.
Referenced by main, XSem_ApiCheckScanCount, XSem_ApiCheckHbtCount.
XStatus XSem_CmdGetConfig(XIpiPsu *IpiInst, XSemIpiResp *Resp)
This function is used to read CRAM & NPI configuration.
Primarily this function sends an IPI request to PLM to invoke SEM Get configuration command, waits for PLM to process the request and reads the response message. In case of EL1 Non-Secure mode, this function generates an SMC call to TF-A. The SMC request goes to the PLM through the TF-A. This function reads the response of the SMC call and returns the status. IpiInst Pointer to IPI driver instance Resp Structure Pointer of IPI response Resp->RespMsg1: Acknowledgment ID of Get Configuration(0x30309)Resp->RespMsg2: CRAM Attribute register details Bit [31:16]: Not ImplementedBit [15:9]: ReservedBit [8]: ReservedBit [7]: ReservedBit [6:5]: Indicates when to start CRAM scan 00: Do not automatically start scan01: Enable scan automatically after device configuration.10: Reserved11: Reserved Bit [4]: ReservedBit [3]: Indicates HwECC/SwECC 0: Uses hardware calculated ECC.1: Uses software calculated ECC that comes from tools and part of CDO Bit [2]: Indicates Correctable error is to be corrected/not 0: Disables error correction capability1: Enables error correction capability Bit [1:0]: Define the mode of the scan (Enable/Disable scan) 00: Disable Configuration RAM scan01: RESERVED10: Enable Configuration RAM scan11: RESERVED Resp->RespMsg3: NPI Attribute register details Bit [31:24]: Not implementedBit [23:18]: ReservedBit [17:8]: The scheduled time in milliseconds that the NPI scan will be periodically performed. Default Setting: 0x064 = 100msBit [7:6]: ReservedBit [5:4]: Indicates when to start NPI scan 00: Do not automatically start scan01: Enable scan automatically after device configuration.10: Reserved11: Reserved Bit [3]: ReservedBit [2]: Indicates HwSHA/SwSHA 0: Use hardware calculated SHA. 1: Use software calculated SHA.Bit [1:0]: Reserved Resp->RespMsg4: Status of Get Configuration command This API returns the success or failure. XST_FAILURE: On Get Configuration failureXST_SUCCESS: On Get Configuration success
References CMD_ID_SEM_GET_CONFIG, XSemIpiResp::RespMsg1, XSemIpiResp::RespMsg2, XSemIpiResp::RespMsg3, XSemIpiResp::RespMsg4.
Referenced by main.
XStatus XSem_RegisterEvent(XIpiPsu *IpiInst, XSem_Notifier *Notifier)
This function is used to register/un-register event notification with XilSEM Server.
Primarily this function sends an IPI request to PLM to invoke SEM Event Notifier registration, waits for PLM to process the request and check the status. Since SLR slave devices do not support IPI, registering events to mater registers events on all slave SLRs In case of EL1 Non-Secure mode, this function generates an SMC call to TF-A. The SMC request goes to the PLM through the TF-A. This function reads the response of the SMC call and returns the status. IpiInst Pointer to IPI driver instance Notifier Pointer of the notifier object to be associated with the requested notification Notifier->Module: The SEM module from which notification is requiredNotifier->Event: Event(s) belonging to the Module for which notifications are requiredNotifier->Flag: Flags to enable or disable notifications This API returns the success or failure. XST_FAILURE: On event registration/un-registration failureXST_SUCCESS: On event registration/un-registration success The caller shall initialize the notifier object before invoking the XSem_RegisterEvent function.
References XSem_Notifier::Module, XSem_Notifier::Event, XSem_Notifier::Flag, CMD_EM_EVENT_REGISTER.
Referenced by XSem_NpiEventRegisterNotifier.