xdmapcie_intr.c
void XDmaPcie_EnableGlobalInterrupt(XDmaPcie *InstancePtr)
Enable the Global Interrupt.
InstancePtr is the XDmaPcie instance to operate on. None This bit is in the Bridge Status and Control Register.
References XDmaPcie_Config::BaseAddress, XDmaPcie::Config, XDmaPcie::IsReady, XDMAPCIE_BSC_GI_MASK, XDMAPCIE_BSC_GI_SHIFT, XDMAPCIE_BSC_OFFSET, XDmaPcie_ReadReg, XDmaPcie_WriteReg.
void XDmaPcie_DisableGlobalInterrupt(XDmaPcie *InstancePtr)
Disable the Global Interrupt.
InstancePtr is the XDmaPcie instance to operate on. None This bit is in the Bridge Status and Control Register.
References XDmaPcie_Config::BaseAddress, XDmaPcie::Config, XDmaPcie::IsReady, XDMAPCIE_BSC_GI_MASK, XDMAPCIE_BSC_GI_SHIFT, XDMAPCIE_BSC_OFFSET, XDmaPcie_ReadReg, XDmaPcie_WriteReg.
void XDmaPcie_EnableInterrupts(XDmaPcie *InstancePtr, u32 EnableMask)
Enable the IP interrupt bits passed into "EnableMask".
InstancePtr is the XDmaPcie instance to operate on. EnableMask is the bit pattern for interrupts wanted to be enabled. None If an interrupt is already enabled before calling this function, it will stay enabled regardless of the value of "EnableMask" passed from the caller.
References XDmaPcie_Config::BaseAddress, XDmaPcie::Config, XDmaPcie::IsReady, XDMAPCIE_IM_OFFSET, XDmaPcie_ReadReg, XDmaPcie_WriteReg.
void XDmaPcie_DisableInterrupts(XDmaPcie *InstancePtr, u32 DisableMask)
Disable the IP interrupt bits passed into "DisableMask".
InstancePtr is the XDmaPcie instance to operate on. DisableMask is the bit pattern for interrupts wanted to be disabled. None If an interrupt is already disabled before calling this function, it will stay disabled regardless of the value of "DisableMask" passed from the caller.
References XDmaPcie_Config::BaseAddress, XDmaPcie::Config, XDmaPcie::IsReady, XDMAPCIE_IM_OFFSET, XDmaPcie_ReadReg, XDmaPcie_WriteReg.
Referenced by PcieInitRootComplex, XDmaPcie_CfgInitialize.
void XDmaPcie_GetEnabledInterrupts(XDmaPcie *InstancePtr, u32 *EnabledMaskPtr)
Get the currently enabled interrupt bits of the IP and pass them back to the caller into "EnabledMask".
InstancePtr is the XDmaPcie instance to operate on. EnabledMaskPtr is a pointer to a variable where the driver will pass back the enabled interrupt bits after reading them from IP. None. None.
References XDmaPcie_Config::BaseAddress, XDmaPcie::Config, XDmaPcie::IsReady, XDMAPCIE_IM_OFFSET, XDmaPcie_ReadReg.
Referenced by PcieInitRootComplex.
void XDmaPcie_GetPendingInterrupts(XDmaPcie *InstancePtr, u32 *PendingMaskPtr)
Get the currently pending interrupt bits of the IP and pass them back to the caller into "PendingMask".
InstancePtr is the XDmaPcie instance to operate on. PendingMaskPtr is a pointer to a variable where the driver will pass back the pending interrupt bits after reading them from IP. None. None.
References XDmaPcie_Config::BaseAddress, XDmaPcie::Config, XDmaPcie::IsReady, XDMAPCIE_ID_OFFSET, XDmaPcie_ReadReg.
Referenced by PcieInitRootComplex.
void XDmaPcie_ClearPendingInterrupts(XDmaPcie *InstancePtr, u32 ClearMask)
Clear the currently pending interrupt bits of the IP passed from the caller into "ClearMask".
InstancePtr is the XDmaPcie instance to operate on. ClearMask is the bit pattern for pending interrupts wanted to be cleared. None. None.
References XDmaPcie_Config::BaseAddress, XDmaPcie::Config, XDmaPcie::IsReady, XDMAPCIE_ID_OFFSET, XDmaPcie_ReadReg, XDmaPcie_WriteReg.
Referenced by PcieInitRootComplex.