Overview
XRFDC_CLK_EN_OFFSET
ADC Clock Enable Register.
Referenced by XRFdc_GetBlockStatus.
XRFDC_ADC_DEBUG_RST_OFFSET
ADC Debug Reset Register.
XRFDC_ADC_FABRIC_RATE_OFFSET
ADC Fabric Rate Register.
XRFDC_ADC_FABRIC_RATE_OBS_OFFSET
ADC Obs Fabric Rate Register.
XRFDC_ADC_FABRIC_RATE_TDD_OFFSET
ADC Fabric Rate (or OBS) Register TDD Selected.
XRFDC_DAC_FABRIC_RATE_OFFSET
DAC Fabric Rate Register.
Referenced by XRFdc_SetDataPathMode, XRFdc_SetFabWrVldWords.
XRFDC_ADC_FABRIC_OFFSET
ADC Fabric Register.
XRFDC_ADC_FABRIC_OBS_OFFSET
ADC Obs Fabric Register.
XRFDC_ADC_FABRIC_TDD_OFFSET
ADC Fabric Register (or OBS) TDD Selected.
XRFDC_ADC_FABRIC_ISR_OFFSET
ADC Fabric ISR Register.
Referenced by XRFdc_GetIntrStatus, XRFdc_IntrClr.
XRFDC_DAC_FIFO_START_OFFSET
DAC FIFO Start Register.
Referenced by XRFdc_SetInterpolationFactor.
XRFDC_DAC_FABRIC_ISR_OFFSET
DAC Fabric ISR Register.
Referenced by XRFdc_GetIntrStatus, XRFdc_IntrClr.
XRFDC_ADC_FABRIC_IMR_OFFSET
ADC Fabric IMR Register.
Referenced by XRFdc_GetEnabledInterrupts, XRFdc_IntrDisable, XRFdc_IntrEnable.
XRFDC_DAC_FABRIC_IMR_OFFSET
DAC Fabric IMR Register.
Referenced by XRFdc_GetEnabledInterrupts, XRFdc_IntrDisable, XRFdc_IntrEnable.
XRFDC_ADC_FABRIC_DBG_OFFSET
ADC Fabric Debug Register.
XRFDC_ADC_FABRIC_DBG_OBS_OFFSET
ADC Obs Fabric Debug Register.
XRFDC_ADC_FABRIC_DBG_TDD_OFFSET
ADC Fabric Debug (or OBS) Register TDD Selected.
XRFDC_ADC_UPDATE_DYN_OFFSET
ADC Update Dynamic Register.
Referenced by XRFdc_SetCoarseDelaySettings, XRFdc_SetMixerSettings, XRFdc_SetQMCSettings, XRFdc_UpdateEvent.
XRFDC_DAC_UPDATE_DYN_OFFSET
DAC Update Dynamic Register.
Referenced by XRFdc_SetCoarseDelaySettings, XRFdc_SetMixerSettings, XRFdc_SetQMCSettings, XRFdc_UpdateEvent.
XRFDC_ADC_FIFO_LTNC_CRL_OFFSET
ADC FIFO Latency Control Register.
XRFDC_ADC_FIFO_LTNC_CRL_OBS_OFFSET
ADC Obs FIFO Latency Control Register.
XRFDC_ADC_FIFO_LTNC_CRL_TDD_OFFSET
ADC FIFO Latency Control (or OBS) Register TDD Selected.
XRFDC_ADC_DEC_ISR_OFFSET
ADC Decoder interface ISR Register.
Referenced by XRFdc_GetIntrStatus, XRFdc_IntrClr.
XRFDC_DAC_DATAPATH_OFFSET
ADC Decoder interface IMR Register.
Referenced by XRFdc_GetDataPathMode, XRFdc_GetIMRPassMode, XRFdc_GetMixerSettings, XRFdc_MultiBand, XRFdc_SetDataPathMode, XRFdc_SetIMRPassMode, XRFdc_SetInterpolationFactor, XRFdc_SetMixerSettings.
XRFDC_ADC_DEC_IMR_OFFSET
ADC Decoder interface IMR Register.
Referenced by XRFdc_GetEnabledInterrupts, XRFdc_IntrDisable, XRFdc_IntrEnable.
XRFDC_DATPATH_ISR_OFFSET
ADC Data Path ISR Register.
Referenced by XRFdc_GetIntrStatus, XRFdc_IntrClr.
XRFDC_DATPATH_IMR_OFFSET
ADC Data Path IMR Register.
Referenced by XRFdc_GetEnabledInterrupts, XRFdc_IntrDisable, XRFdc_IntrEnable.
XRFDC_ADC_DECI_CONFIG_OFFSET
ADC Decimation Config Register.
Referenced by XRFdc_SetMixerSettings.
XRFDC_ADC_DECI_CONFIG_OBS_OFFSET
ADC Decimation Config Register.
XRFDC_ADC_DECI_CONFIG_TDD_OFFSET
ADC Decimation Config (or OBS) Register TDD Selected.
XRFDC_DAC_INTERP_CTRL_OFFSET
DAC Interpolation Control Register.
Referenced by XRFdc_GetInterpolationFactor, XRFdc_SetDataPathMode, XRFdc_SetInterpolationFactor.
XRFDC_ADC_DECI_MODE_OFFSET
ADC Decimation mode Register.
XRFDC_ADC_DECI_MODE_OBS_OFFSET
ADC Obs Decimation mode Register.
XRFDC_ADC_DECI_MODE_TDD_OFFSET
ADC Decimation mode (or OBS) Register TDD Selected.
XRFDC_DAC_ITERP_DATA_OFFSET
DAC interpolation data.
Referenced by XRFdc_SetDataPathMode, XRFdc_SetInterpolationFactor, XRFdc_SetMixerSettings.
XRFDC_ADC_FABRIC_ISR_OBS_OFFSET
ADC Fabric ISR Observation Register.
Referenced by XRFdc_GetIntrStatus, XRFdc_IntrClr.
XRFDC_ADC_FABRIC_IMR_OBS_OFFSET
ADC Fabric ISR Observation Register.
Referenced by XRFdc_GetEnabledInterrupts, XRFdc_IntrDisable, XRFdc_IntrEnable.
XRFDC_DAC_TDD_MODE0_OFFSET
DAC TDD Mode 0 Configuration.
XRFDC_ADC_TDD_MODE0_OFFSET
ADC TDD Mode 0 Configuration.
XRFDC_TDD_MODE0_OFFSET
ADC TDD Mode 0 Configuration.
XRFDC_ADC_MXR_CFG0_OFFSET
ADC I channel mixer config Register.
Referenced by XRFdc_GetMixerSettings.
XRFDC_ADC_MXR_CFG1_OFFSET
ADC Q channel mixer config Register.
Referenced by XRFdc_GetMixerSettings.
XRFDC_MXR_MODE_OFFSET
ADC/DAC mixer mode Register.
Referenced by XRFdc_GetMixerSettings, XRFdc_SetMixerSettings.
XRFDC_NCO_UPDT_OFFSET
ADC/DAC NCO Update mode Register.
Referenced by XRFdc_GetMixerSettings, XRFdc_SetMixerSettings, XRFdc_UpdateEvent.
XRFDC_NCO_RST_OFFSET
ADC/DAC NCO Phase Reset Register.
Referenced by XRFdc_ResetNCOPhase.
XRFDC_ADC_NCO_FQWD_UPP_OFFSET
ADC NCO Frequency Word[47:32] Register.
Referenced by XRFdc_GetMixerSettings, XRFdc_SetMixerSettings.
XRFDC_ADC_NCO_FQWD_MID_OFFSET
ADC NCO Frequency Word[31:16] Register.
Referenced by XRFdc_GetMixerSettings, XRFdc_SetMixerSettings.
XRFDC_ADC_NCO_FQWD_LOW_OFFSET
ADC NCO Frequency Word[15:0] Register.
Referenced by XRFdc_GetMixerSettings, XRFdc_SetMixerSettings.
XRFDC_NCO_PHASE_UPP_OFFSET
ADC/DAC NCO Phase[17:16] Register.
Referenced by XRFdc_GetMixerSettings, XRFdc_SetMixerSettings.
XRFDC_NCO_PHASE_LOW_OFFSET
ADC/DAC NCO Phase[15:0] Register.
Referenced by XRFdc_GetMixerSettings, XRFdc_SetMixerSettings.
XRFDC_ADC_NCO_PHASE_MOD_OFFSET
ADC NCO Phase Mode Register.
Referenced by XRFdc_SetMixerSettings.
XRFDC_QMC_UPDT_OFFSET
ADC/DAC QMC Update Mode Register.
Referenced by XRFdc_GetQMCSettings, XRFdc_SetQMCSettings, XRFdc_UpdateEvent.
XRFDC_QMC_CFG_OFFSET
ADC/DAC QMC Config Register.
Referenced by XRFdc_GetQMCSettings, XRFdc_SetQMCSettings.
XRFDC_QMC_OFF_OFFSET
ADC/DAC QMC Offset Correction Register.
Referenced by XRFdc_GetQMCSettings, XRFdc_SetQMCSettings.
XRFDC_QMC_GAIN_OFFSET
ADC/DAC QMC Gain Correction Register.
Referenced by XRFdc_GetQMCSettings, XRFdc_SetQMCSettings.
XRFDC_QMC_PHASE_OFFSET
ADC/DAC QMC Phase Correction Register.
Referenced by XRFdc_GetQMCSettings, XRFdc_SetQMCSettings.
XRFDC_ADC_CRSE_DLY_UPDT_OFFSET
ADC Coarse Delay Update Register.
Referenced by XRFdc_GetCoarseDelaySettings, XRFdc_SetCoarseDelaySettings, XRFdc_UpdateEvent.
XRFDC_DAC_CRSE_DLY_UPDT_OFFSET
DAC Coarse Delay Update Register.
Referenced by XRFdc_GetCoarseDelaySettings, XRFdc_SetCoarseDelaySettings, XRFdc_UpdateEvent.
XRFDC_ADC_CRSE_DLY_CFG_OFFSET
ADC Coarse delay Config Register.
Referenced by XRFdc_GetCoarseDelaySettings, XRFdc_SetCoarseDelaySettings.
XRFDC_DAC_CRSE_DLY_CFG_OFFSET
DAC Coarse delay Config Register.
Referenced by XRFdc_GetCoarseDelaySettings, XRFdc_SetCoarseDelaySettings.
XRFDC_ADC_DAT_SCAL_CFG_OFFSET
ADC Data Scaling Config Register.
XRFDC_ADC_SWITCH_MATRX_OFFSET
ADC Switch Matrix Config Register.
Referenced by XRFdc_GetConnectedIQData, XRFdc_SetQMCSettings.
XRFDC_ADC_TRSHD0_CFG_OFFSET
ADC Threshold0 Config Register.
Referenced by XRFdc_GetThresholdSettings, XRFdc_SetThresholdClrMode, XRFdc_SetThresholdSettings, XRFdc_ThresholdStickyClear.
XRFDC_ADC_TRSHD0_AVG_UP_OFFSET
ADC Threshold0 Average[31:16] Register.
Referenced by XRFdc_GetThresholdSettings, XRFdc_SetThresholdSettings.
XRFDC_ADC_TRSHD0_AVG_LO_OFFSET
ADC Threshold0 Average[15:0] Register.
Referenced by XRFdc_GetThresholdSettings, XRFdc_SetThresholdSettings.
XRFDC_ADC_TRSHD0_UNDER_OFFSET
ADC Threshold0 Under Threshold Register.
Referenced by XRFdc_GetThresholdSettings, XRFdc_SetThresholdSettings.
XRFDC_ADC_TRSHD0_OVER_OFFSET
ADC Threshold0 Over Threshold Register.
Referenced by XRFdc_GetThresholdSettings, XRFdc_SetThresholdSettings.
XRFDC_ADC_TRSHD1_CFG_OFFSET
ADC Threshold1 Config Register.
Referenced by XRFdc_GetThresholdSettings, XRFdc_SetThresholdClrMode, XRFdc_SetThresholdSettings, XRFdc_ThresholdStickyClear.
XRFDC_ADC_TRSHD1_AVG_UP_OFFSET
ADC Threshold1 Average[31:16] Register.
Referenced by XRFdc_GetThresholdSettings, XRFdc_SetThresholdSettings.
XRFDC_ADC_TRSHD1_AVG_LO_OFFSET
ADC Threshold1 Average[15:0] Register.
Referenced by XRFdc_GetThresholdSettings, XRFdc_SetThresholdSettings.
XRFDC_ADC_TRSHD1_UNDER_OFFSET
ADC Threshold1 Under Threshold Register.
Referenced by XRFdc_GetThresholdSettings, XRFdc_SetThresholdSettings.
XRFDC_ADC_TRSHD1_OVER_OFFSET
ADC Threshold1 Over Threshold Register.
Referenced by XRFdc_GetThresholdSettings, XRFdc_SetThresholdSettings.
XRFDC_ADC_FEND_DAT_CRL_OFFSET
ADC Front end Data Control Register.
XRFDC_ADC_TI_DCB_CRL0_OFFSET
ADC Time Interleaved digital correction block gain control0 Register.
Referenced by XRFdc_GetCalibrationMode, XRFdc_SetCalibrationMode.
XRFDC_ADC_TI_DCB_CRL1_OFFSET
ADC Time Interleaved digital correction block gain control1 Register.
Referenced by XRFdc_DisableCoefficientsOverride, XRFdc_GetCalCoefficients, XRFdc_SetCalCoefficients.
XRFDC_ADC_TI_DCB_CRL2_OFFSET
ADC Time Interleaved digital correction block gain control2 Register.
XRFDC_ADC_TI_DCB_CRL3_OFFSET
ADC Time Interleaved digital correction block gain control3 Register.
Referenced by XRFdc_DisableCoefficientsOverride, XRFdc_SetCalCoefficients.
XRFDC_ADC_TI_TISK_CRL0_OFFSET
ADC Time skew correction control bits0 Register.
Referenced by XRFdc_GetNyquistZone, XRFdc_SetCalibrationMode, XRFdc_SetNyquistZone.
XRFDC_DAC_MC_CFG0_OFFSET
Static Configuration data for DAC Analog.
Referenced by XRFdc_GetNyquistZone, XRFdc_SetNyquistZone.
XRFDC_ADC_TI_TISK_CRL1_OFFSET
ADC Time skew correction control bits1 Register.
XRFDC_ADC_TI_TISK_CRL2_OFFSET
ADC Time skew correction control bits2 Register.
XRFDC_ADC_TI_TISK_CRL3_OFFSET
ADC Time skew correction control bits3 Register.
XRFDC_ADC_TI_TISK_CRL4_OFFSET
ADC Time skew correction control bits4 Register.
XRFDC_ADC_TI_TISK_CRL5_OFFSET
ADC Time skew correction control bits5 Register (Gen 3 only)
Referenced by XRFdc_GetCalibrationMode, XRFdc_SetCalibrationMode.
XRFDC_ADC_TI_TISK_DAC0_OFFSET
ADC Time skew DAC cal code of subadc ch0 Register(Below Gen 3)
XRFDC_ADC_TI_TISK_DAC1_OFFSET
ADC Time skew DAC cal code of subadc ch1 Register.
XRFDC_ADC_TI_TISK_DAC2_OFFSET
ADC Time skew DAC cal code of subadc ch2 Register.
XRFDC_ADC_TI_TISK_DAC3_OFFSET
ADC Time skew DAC cal code of subadc ch3 Register.
XRFDC_ADC_TI_TISK_DACP0_OFFSET
ADC Time skew DAC cal code of subadc ch0 Register.
XRFDC_ADC_TI_TISK_DACP1_OFFSET
ADC Time skew DAC cal code of subadc ch1 Register.
XRFDC_ADC_TI_TISK_DACP2_OFFSET
ADC Time skew DAC cal code of subadc ch2 Register.
XRFDC_ADC_TI_TISK_DACP3_OFFSET
ADC Time skew DAC cal code of subadc ch3 Register.
XRFDC_DATA_SCALER_OFFSET
DAC Data Scaler Register.
Referenced by XRFdc_GetDACDataScaler, XRFdc_SetDACDataScaler.
XRFDC_DAC_VOP_CTRL_OFFSET
DAC variable output power control Register.
Referenced by XRFdc_SetDACVOP.
XRFDC_ADC0_SUBDRP_ADDR_OFFSET
subadc0, sub-drp address of target Register
XRFDC_ADC0_SUBDRP_DAT_OFFSET
subadc0, sub-drp data of target Register
XRFDC_ADC1_SUBDRP_ADDR_OFFSET
subadc1, sub-drp address of target Register
XRFDC_ADC1_SUBDRP_DAT_OFFSET
subadc1, sub-drp data of target Register
XRFDC_ADC2_SUBDRP_ADDR_OFFSET
subadc2, sub-drp address of target Register
XRFDC_ADC2_SUBDRP_DAT_OFFSET
subadc2, sub-drp data of target Register
XRFDC_ADC3_SUBDRP_ADDR_OFFSET
subadc3, sub-drp address of target Register
XRFDC_ADC3_SUBDRP_DAT_OFFSET
subadc3, sub-drp data of target Register
XRFDC_ADC_RX_MC_PWRDWN_OFFSET
ADC Static configuration bits for ADC(RX) analog Register.
XRFDC_ADC_DAC_MC_CFG0_OFFSET
ADC/DAC Static configuration bits for ADC/DAC analog Register.
Referenced by XRFdc_DynamicPLLConfig, XRFdc_GetDither, XRFdc_SetDACVOP, XRFdc_SetDither.
XRFDC_ADC_DAC_MC_CFG1_OFFSET
ADC/DAC Static configuration bits for ADC/DAC analog Register.
XRFDC_ADC_DAC_MC_CFG2_OFFSET
ADC/DAC Static configuration bits for ADC/DAC analog Register.
Referenced by XRFdc_GetDACCompMode, XRFdc_GetOutputCurr, XRFdc_SetDACCompMode, XRFdc_SetDACVOP.
XRFDC_DAC_MC_CFG3_OFFSET
DAC Static configuration bits for DAC analog Register.
Referenced by XRFdc_GetOutputCurr, XRFdc_SetDACVOP.
XRFDC_ADC_RXPR_MC_CFG0_OFFSET
ADC RX Pair static Configuration Register.
Referenced by XRFdc_GetCoupling, XRFdc_GetLinkCoupling.
XRFDC_ADC_RXPR_MC_CFG1_OFFSET
ADC RX Pair static Configuration Register.
XRFDC_ADC_TI_DCBSTS0_BG_OFFSET
ADC DCB Status0 BG Register.
XRFDC_ADC_TI_DCBSTS0_FG_OFFSET
ADC DCB Status0 FG Register.
XRFDC_ADC_TI_DCBSTS1_BG_OFFSET
ADC DCB Status1 BG Register.
XRFDC_ADC_TI_DCBSTS1_FG_OFFSET
ADC DCB Status1 FG Register.
XRFDC_ADC_TI_DCBSTS2_BG_OFFSET
ADC DCB Status2 BG Register.
XRFDC_ADC_TI_DCBSTS2_FG_OFFSET
ADC DCB Status2 FG Register.
XRFDC_ADC_TI_DCBSTS3_BG_OFFSET
ADC DCB Status3 BG Register.
XRFDC_ADC_TI_DCBSTS3_FG_OFFSET
ADC DCB Status3 FG Register.
XRFDC_ADC_TI_DCBSTS4_MB_OFFSET
ADC DCB Status4 MSB Register.
XRFDC_ADC_TI_DCBSTS4_LB_OFFSET
ADC DCB Status4 LSB Register.
XRFDC_ADC_TI_DCBSTS5_MB_OFFSET
ADC DCB Status5 MSB Register.
XRFDC_ADC_TI_DCBSTS5_LB_OFFSET
ADC DCB Status5 LSB Register.
XRFDC_ADC_TI_DCBSTS6_MB_OFFSET
ADC DCB Status6 MSB Register.
XRFDC_ADC_TI_DCBSTS6_LB_OFFSET
ADC DCB Status6 LSB Register.
XRFDC_ADC_TI_DCBSTS7_MB_OFFSET
ADC DCB Status7 MSB Register.
XRFDC_ADC_TI_DCBSTS7_LB_OFFSET
ADC DCB Status7 LSB Register.
XRFDC_DSA_UPDT_OFFSET
ADC DSA Update Trigger REgister.
Referenced by XRFdc_SetDSA.
XRFDC_ADC_FIFO_LTNCY_LB_OFFSET
ADC FIFO Latency measurement LSB Register.
XRFDC_ADC_FIFO_LTNCY_MB_OFFSET
ADC FIFO Latency measurement MSB Register.
XRFDC_DAC_DECODER_CTRL_OFFSET
DAC Unary Decoder/ Randomizer settings.
Referenced by XRFdc_GetDecoderMode, XRFdc_SetDecoderMode.
XRFDC_DAC_DECODER_CLK_OFFSET
Decoder Clock enable.
Referenced by XRFdc_SetDecoderMode.
XRFDC_MB_CONFIG_OFFSET
Multiband Config status.
Referenced by XRFdc_GetConnectedIQData, XRFdc_GetMultibandConfig.
XRFDC_ADC_SIG_DETECT_CTRL_OFFSET
ADC Signal Detector Control.
Referenced by XRFdc_GetSignalDetector, XRFdc_SetSignalDetector.
XRFDC_ADC_SIG_DETECT_THRESHOLD0_LEVEL_OFFSET
ADC Signal Detector Threshold 0.
Referenced by XRFdc_GetSignalDetector, XRFdc_SetSignalDetector.
XRFDC_ADC_SIG_DETECT_THRESHOLD0_CNT_OFF_OFFSET
ADC Signal Detector Threshold 0 on Counter.
Referenced by XRFdc_GetSignalDetector, XRFdc_SetSignalDetector.
XRFDC_ADC_SIG_DETECT_THRESHOLD0_CNT_ON_OFFSET
ADC Signal Detector Threshold 0 off Counter.
Referenced by XRFdc_GetSignalDetector, XRFdc_SetSignalDetector.
XRFDC_ADC_SIG_DETECT_MAGN_OFFSET
ADC Signal Detector Magintude.
XRFDC_HSCOM_CLK_DSTR_OFFSET
Clock Distribution Register.
Referenced by XRFdc_DynamicPLLConfig, XRFdc_GetClkDistribution, XRFdc_SetClkDistribution.
XRFDC_HSCOM_CLK_DSTR_MASK
Clock Distribution Register.
Referenced by XRFdc_SetClkDistribution.
XRFDC_HSCOM_CLK_DSTR_MASK_ALT
Clock Distribution Register for Intratile.
XRFDC_HSCOM_PWR_OFFSET
Control register during power-up sequence.
XRFDC_HSCOM_CLK_DIV_OFFSET
Fabric clk out divider.
Referenced by XRFdc_GetFabClkOutDiv, XRFdc_SetDataPathMode, XRFdc_SetFabClkOutDiv.
XRFDC_HSCOM_PWR_STATE_OFFSET
Check powerup state.
Referenced by XRFdc_DynamicPLLConfig.
XRFDC_HSCOM_UPDT_DYN_OFFSET
Trigger the update dynamic event.
Referenced by XRFdc_UpdateEvent.
XRFDC_HSCOM_EFUSE_2_OFFSET
XRFDC_DAC_INVSINC_OFFSET
Invsinc control.
Referenced by XRFdc_GetInvSincFIR, XRFdc_SetInvSincFIR.
XRFDC_DAC_MB_CFG_OFFSET
Multiband config.
Referenced by XRFdc_GetConnectedIQData, XRFdc_GetQMCSettings, XRFdc_SetQMCSettings.
XRFDC_MTS_SRDIST
XRFDC_MTS_SRCAP_T1
XRFDC_MTS_SRCAP_PLL
XRFDC_MTS_SRCAP_DIG
XRFDC_MTS_SRDTC_T1
XRFDC_MTS_SRDTC_PLL
XRFDC_MTS_SRFLAG
XRFDC_MTS_CLKSTAT
XRFDC_MTS_SRCOUNT_CTRL
XRFDC_MTS_SRCOUNT_VAL
XRFDC_MTS_SRFREQ_VAL
XRFDC_MTS_FIFO_CTRL_ADC
XRFDC_MTS_FIFO_CTRL_DAC
XRFDC_MTS_DELAY_CTRL
XRFDC_MTS_ADC_MARKER
XRFDC_MTS_ADC_MARKER_CNT
XRFDC_MTS_DAC_MARKER_CTRL
XRFDC_MTS_DAC_MARKER_CNT
XRFDC_MTS_DAC_MARKER_LOC
XRFDC_MTS_DAC_FIFO_MARKER_CTRL
XRFDC_MTS_DAC_FABRIC_OFFSET
XRFDC_RESET_OFFSET
Tile reset register.
XRFDC_RESTART_OFFSET
Tile restart register.
Referenced by XRFdc_SetClkDistribution.
XRFDC_RESTART_STATE_OFFSET
Tile restart state register.
Referenced by XRFdc_SetClkDistribution.
XRFDC_CURRENT_STATE_OFFSET
Current state register.
Referenced by XRFdc_GetIPStatus, XRFdc_WaitForState.
XRFDC_CLOCK_DETECT_OFFSET
Clock detect register.
Referenced by XRFdc_GetClkDistribution, XRFdc_SetClkDistribution.
XRFDC_STATUS_OFFSET
Common status register.
Referenced by XRFdc_DynamicPLLConfig, XRFdc_GetIPStatus, XRFdc_GetPLLLockStatus.
XRFDC_CAL_DIV_BYP_OFFSET
Calibration divider bypass register.
Referenced by XRFdc_CustomStartUp, XRFdc_DynamicPLLConfig.
XRFDC_COMMON_INTR_STS
Common Intr Status register.
Referenced by XRFdc_IntrHandler.
XRFDC_COMMON_INTR_ENABLE
Common Intr enable register.
Referenced by XRFdc_GetEnabledInterrupts, XRFdc_IntrEnable.
XRFDC_INTR_STS
Intr status register.
Referenced by XRFdc_GetIntrStatus, XRFdc_IntrHandler.
XRFDC_INTR_ENABLE
Intr enable register.
Referenced by XRFdc_GetEnabledInterrupts, XRFdc_IntrDisable, XRFdc_IntrEnable.
XRFDC_CONV_INTR_STS
XRFDC_CONV_INTR_EN
XRFDC_CONV_CAL_STGS
XRFDC_CONV_DSA_STGS
XRFDC_CAL_GCB_COEFF0_FAB
XRFDC_CAL_GCB_COEFF1_FAB
XRFDC_CAL_GCB_COEFF2_FAB
XRFDC_CAL_GCB_COEFF3_FAB
XRFDC_TDD_CTRL_SLICE_OFFSET
TDD control registers.
Referenced by XRFdc_GetPwrMode, XRFdc_SetPwrMode.
XRFDC_PLL_FREQ
PLL output frequency (before divider) register.
Referenced by XRFdc_DynamicPLLConfig, XRFdc_GetPLLConfig.
XRFDC_PLL_FS
Sampling rate register.
Referenced by XRFdc_DynamicPLLConfig, XRFdc_GetPLLConfig.
XRFDC_CAL_TMR_MULT_OFFSET
Calibration timer register.
Referenced by XRFdc_CustomStartUp, XRFdc_DynamicPLLConfig.
XRFDC_CAL_DLY_OFFSET
Calibration delay register.
Referenced by XRFdc_CustomStartUp, XRFdc_DynamicPLLConfig.
XRFDC_CPL_TYPE_OFFSET
Coupling type register.
Referenced by XRFdc_GetCoupling, XRFdc_SetDACVOP.
XRFDC_FIFO_ENABLE
FIFO Enable and Disable.
Referenced by XRFdc_GetFIFOStatusInt.
XRFDC_PLL_SDM_CFG0
PLL Configuration bits for sdm.
XRFDC_PLL_SDM_SEED0
PLL Bits for sdm LSB.
XRFDC_PLL_SDM_SEED1
PLL Bits for sdm MSB.
XRFDC_PLL_VREG
PLL bits for voltage regulator.
PLL voltage regulator.
XRFDC_PLL_VREG
PLL bits for voltage regulator.
PLL voltage regulator.
XRFDC_PLL_VCO0
PLL bits for coltage controlled oscillator LSB.
XRFDC_PLL_VCO1
PLL bits for coltage controlled oscillator MSB.
XRFDC_PLL_CRS1
PLL bits for coarse frequency control LSB.
XRFDC_PLL_CRS2
PLL bits for coarse frequency control MSB.
XRFDC_PLL_DIVIDER0
PLL Output Divider LSB register.
Referenced by XRFdc_DynamicPLLConfig, XRFdc_GetClockSource, XRFdc_GetPLLConfig.
XRFDC_PLL_DIVIDER1
PLL Output Divider MSB register.
XRFDC_PLL_SPARE0
PLL spare inputs LSB.
XRFDC_PLL_SPARE1
PLL spare inputs MSB.
XRFDC_PLL_REFDIV
PLL Reference Divider register.
Referenced by XRFdc_GetPLLConfig.
XRFDC_PLL_CHARGEPUMP
PLL bits for charge pumps.
XRFDC_PLL_LPF0
PLL bits for loop filters LSB.
XRFDC_PLL_LPF1
PLL bits for loop filters MSB.
XRFDC_PLL_FPDIV
PLL Feedback Divider register.
Referenced by XRFdc_GetPLLConfig.
XRFDC_CLK_NETWORK_CTRL0
Clock network control and trim register.
XRFDC_CLK_NETWORK_CTRL1
Multi-tile sync and clock source control register.
Referenced by XRFdc_DynamicPLLConfig, XRFdc_GetClockSource.
XRFDC_HSCOM_NETWORK_CTRL1_MASK
Clock Network Register Mask for IntraTile.
XRFDC_PLL_REFDIV_MASK
PLL Reference Divider Register Mask for IntraTile.
XRFDC_PLL_DIVIDER0_ALT_MASK
PLL Output Divider Register Mask for IntraTile.
XRFDC_PLL_DIVIDER0_BYPPLL_MASK
PLL Output Divider Register Mask for IntraTile.
XRFDC_PLL_DIVIDER0_BYPDIV_MASK
PLL Output Divider Register Mask for IntraTile.
XRFDC_CAL_OCB1_OFFSET_COEFF0
Foreground offset correction block.
Referenced by XRFdc_GetCalCoefficients, XRFdc_SetCalCoefficients.
XRFDC_CAL_OCB1_OFFSET_COEFF1
Foreground offset correction block.
Referenced by XRFdc_GetCalCoefficients, XRFdc_SetCalCoefficients.
XRFDC_CAL_OCB1_OFFSET_COEFF2
Foreground offset correction block.
Referenced by XRFdc_GetCalCoefficients, XRFdc_SetCalCoefficients.
XRFDC_CAL_OCB1_OFFSET_COEFF3
Foreground offset correction block.
Referenced by XRFdc_GetCalCoefficients, XRFdc_SetCalCoefficients.
XRFDC_CAL_OCB2_OFFSET_COEFF0
Background offset correction block.
Referenced by XRFdc_GetCalCoefficients, XRFdc_SetCalCoefficients.
XRFDC_CAL_OCB2_OFFSET_COEFF1
Background offset correction block.
Referenced by XRFdc_GetCalCoefficients, XRFdc_SetCalCoefficients.
XRFDC_CAL_OCB2_OFFSET_COEFF2
Background offset correction block.
Referenced by XRFdc_GetCalCoefficients, XRFdc_SetCalCoefficients.
XRFDC_CAL_OCB2_OFFSET_COEFF3
Background offset correction block.
Referenced by XRFdc_GetCalCoefficients, XRFdc_SetCalCoefficients.
XRFDC_CAL_GCB_OFFSET_COEFF0
Background gain correction block.
Referenced by XRFdc_GetCalCoefficients, XRFdc_SetCalCoefficients.
XRFDC_CAL_GCB_OFFSET_COEFF1
Background gain correction block.
Referenced by XRFdc_GetCalCoefficients, XRFdc_SetCalCoefficients.
XRFDC_CAL_GCB_OFFSET_COEFF2
Background gain correction block.
Referenced by XRFdc_GetCalCoefficients, XRFdc_SetCalCoefficients.
XRFDC_CAL_GCB_OFFSET_COEFF3
Background gain correction block.
Referenced by XRFdc_GetCalCoefficients, XRFdc_SetCalCoefficients.
XRFDC_CAL_GCB_OFFSET_COEFF0_ALT
Background gain correction block (below Gen 3)
Referenced by XRFdc_GetCalCoefficients.
XRFDC_CAL_GCB_OFFSET_COEFF1_ALT
Background gain correction block (below Gen 3)
Referenced by XRFdc_GetCalCoefficients.
XRFDC_CAL_GCB_OFFSET_COEFF2_ALT
Background gain correction block (below Gen 3)
Referenced by XRFdc_GetCalCoefficients.
XRFDC_CAL_GCB_OFFSET_COEFF3_ALT
Background gain correction block (below Gen 3)
Referenced by XRFdc_GetCalCoefficients.
XRFDC_CAL_TSCB_OFFSET_COEFF0
Background time skew correction block.
Referenced by XRFdc_DisableCoefficientsOverride, XRFdc_GetCalCoefficients, XRFdc_SetCalCoefficients.
XRFDC_CAL_TSCB_OFFSET_COEFF1
Background time skew correction block.
Referenced by XRFdc_DisableCoefficientsOverride, XRFdc_GetCalCoefficients, XRFdc_SetCalCoefficients.
XRFDC_CAL_TSCB_OFFSET_COEFF2
Background time skew correction block.
Referenced by XRFdc_DisableCoefficientsOverride, XRFdc_GetCalCoefficients, XRFdc_SetCalCoefficients.
XRFDC_CAL_TSCB_OFFSET_COEFF3
Background time skew correction block.
Referenced by XRFdc_DisableCoefficientsOverride, XRFdc_GetCalCoefficients, XRFdc_SetCalCoefficients.
XRFDC_CAL_TSCB_OFFSET_COEFF4
Background time skew correction block.
Referenced by XRFdc_DisableCoefficientsOverride, XRFdc_GetCalCoefficients, XRFdc_SetCalCoefficients.
XRFDC_CAL_TSCB_OFFSET_COEFF5
Background time skew correction block.
Referenced by XRFdc_DisableCoefficientsOverride, XRFdc_GetCalCoefficients, XRFdc_SetCalCoefficients.
XRFDC_CAL_TSCB_OFFSET_COEFF6
Background time skew correction block.
Referenced by XRFdc_DisableCoefficientsOverride, XRFdc_GetCalCoefficients, XRFdc_SetCalCoefficients.
XRFDC_CAL_TSCB_OFFSET_COEFF7
Background time skew correction block.
Referenced by XRFdc_DisableCoefficientsOverride, XRFdc_GetCalCoefficients, XRFdc_SetCalCoefficients.
XRFDC_CAL_TSCB_OFFSET_COEFF0_ALT
Background time skew correction block (below Gen 3)
Referenced by XRFdc_DisableCoefficientsOverride, XRFdc_GetCalCoefficients, XRFdc_SetCalCoefficients.
XRFDC_CAL_TSCB_OFFSET_COEFF1_ALT
Background time skew correction block (below Gen 3)
Referenced by XRFdc_DisableCoefficientsOverride, XRFdc_GetCalCoefficients, XRFdc_SetCalCoefficients.
XRFDC_CAL_TSCB_OFFSET_COEFF2_ALT
Background time skew correction block (below Gen 3)
Referenced by XRFdc_DisableCoefficientsOverride, XRFdc_GetCalCoefficients, XRFdc_SetCalCoefficients.
XRFDC_CAL_TSCB_OFFSET_COEFF3_ALT
Background time skew correction block (below Gen 3)
Referenced by XRFdc_DisableCoefficientsOverride, XRFdc_GetCalCoefficients, XRFdc_SetCalCoefficients.
XRFDC_CAL_TSCB_OFFSET_COEFF4_ALT
Background time skew correction block (below Gen 3)
Referenced by XRFdc_DisableCoefficientsOverride, XRFdc_GetCalCoefficients, XRFdc_SetCalCoefficients.
XRFDC_CAL_TSCB_OFFSET_COEFF5_ALT
Background time skew correction block (below Gen 3)
Referenced by XRFdc_DisableCoefficientsOverride, XRFdc_GetCalCoefficients, XRFdc_SetCalCoefficients.
XRFDC_CAL_TSCB_OFFSET_COEFF6_ALT
Background time skew correction block (below Gen 3)
Referenced by XRFdc_DisableCoefficientsOverride, XRFdc_GetCalCoefficients, XRFdc_SetCalCoefficients.
XRFDC_CAL_TSCB_OFFSET_COEFF7_ALT
Background time skew correction block (below Gen 3)
Referenced by XRFdc_DisableCoefficientsOverride, XRFdc_GetCalCoefficients, XRFdc_SetCalCoefficients.
XRFDC_HSCOM_FIFO_START_OFFSET
FIFO Start register tommon along tile.
XRFDC_HSCOM_FIFO_START_OBS_OFFSET
FIFO Obs Start register common along tile.
XRFDC_HSCOM_FIFO_START_TDD_OFFSET
FIFO Start (or OBS) register common along tile TDD Selected.
XRFDC_TILES_ENABLED_OFFSET
The tiles enabled in the design.
Referenced by XRFdc_CheckTileEnabled.
XRFDC_ADC_PATHS_ENABLED_OFFSET
The ADC analogue/digital paths enabled in the design.
Referenced by XRFdc_IsADCBlockEnabled, XRFdc_IsADCDigitalPathEnabled.
XRFDC_DAC_PATHS_ENABLED_OFFSET
The DAC analogue/digital paths enabled in the design.
Referenced by XRFdc_IsDACBlockEnabled, XRFdc_IsDACDigitalPathEnabled.
XRFDC_PATH_ENABLED_TILE_SHIFT
A shift to get to the correct tile for the path.
Referenced by XRFdc_IsADCBlockEnabled, XRFdc_IsADCDigitalPathEnabled, XRFdc_IsDACBlockEnabled, XRFdc_IsDACDigitalPathEnabled.
XRFDC_CURRENT_STATE_MASK
Current tile state mask.
Referenced by XRFdc_WaitForState.
XRFDC_CAL_MODES_MASK
Calibration modes for Gen 3 mask.
Referenced by XRFdc_GetCalibrationMode, XRFdc_SetCalibrationMode.
XRFDC_CAL_OCB_MASK
offsets coeff mask
Referenced by XRFdc_GetCalCoefficients, XRFdc_SetCalCoefficients.
XRFDC_CAL_GCB_MASK
gain coeff mask
Referenced by XRFdc_DisableCoefficientsOverride, XRFdc_GetCalCoefficients, XRFdc_SetCalCoefficients.
XRFDC_CAL_GCB_FAB_MASK
gain coeff mask for IP Gen 2 or below
Referenced by XRFdc_GetCalCoefficients.
XRFDC_CAL_TSCB_MASK
time skew coeff mask
Referenced by XRFdc_GetCalCoefficients, XRFdc_SetCalCoefficients.
XRFDC_CAL_GCB_FLSH_MASK
GCB accumulator flush mask.
Referenced by XRFdc_GetCalCoefficients, XRFdc_SetCalCoefficients.
XRFDC_CAL_GCB_ACEN_MASK
GCB accumulator enable mask.
Referenced by XRFdc_DisableCoefficientsOverride, XRFdc_SetCalCoefficients.
XRFDC_CAL_GCB_ENFL_MASK
GCB accumulator enable mask.
Referenced by XRFdc_DisableCoefficientsOverride.
XRFDC_CAL_OCB_EN_MASK
offsets coeff override enable mask
Referenced by XRFdc_DisableCoefficientsOverride, XRFdc_SetCalCoefficients.
XRFDC_CAL_GCB_EN_MASK
gain coeff override enable mask
Referenced by XRFdc_DisableCoefficientsOverride, XRFdc_SetCalCoefficients.
XRFDC_CAL_TSCB_EN_MASK
time skew coeff override enable mask
Referenced by XRFdc_DisableCoefficientsOverride, XRFdc_SetCalCoefficients.
XRFDC_CAL_OCB_EN_SHIFT
offsets coeff shift
XRFDC_CAL_GCB_EN_SHIFT
gain coeff shift
Referenced by XRFdc_SetCalCoefficients.
XRFDC_CAL_TSCB_EN_SHIFT
time skew coeff shift
Referenced by XRFdc_SetCalCoefficients.
XRFDC_CAL_GCB_FLSH_SHIFT
GCB accumulator flush shift.
Referenced by XRFdc_SetCalCoefficients.
XRFDC_CAL_GCB_ACEN_SHIFT
GCB accumulator enable shift.
XRFDC_CAL_TSCB_TUNE_MASK
time skew tuning mask
Referenced by XRFdc_SetCalibrationMode.
XRFDC_CAL_SLICE_SHIFT
Coefficient shift for HSADCs.
Referenced by XRFdc_GetCalCoefficients, XRFdc_SetCalCoefficients.
XRFDC_CAL_FREEZE_CAL_MASK
Calibration freeze enable mask.
Referenced by XRFdc_GetCalFreeze, XRFdc_SetCalFreeze.
XRFDC_CAL_FREEZE_STS_MASK
Calibration freeze status mask.
Referenced by XRFdc_GetCalFreeze.
XRFDC_CAL_FREEZE_PIN_MASK
Calibration freeze pin disable mask.
Referenced by XRFdc_GetCalFreeze, XRFdc_SetCalFreeze.
XRFDC_CAL_FREEZE_CAL_SHIFT
Calibration freeze enable shift.
Referenced by XRFdc_GetCalFreeze, XRFdc_SetCalFreeze.
XRFDC_CAL_FREEZE_STS_SHIFT
Calibration freeze status shift.
Referenced by XRFdc_GetCalFreeze.
XRFDC_CAL_FREEZE_PIN_SHIFT
Calibration freeze pin disable shift.
Referenced by XRFdc_GetCalFreeze, XRFdc_SetCalFreeze.
XRFDC_FIFO_EN_MASK
FIFO enable/disable mask.
Referenced by XRFdc_GetFIFOStatusInt.
XRFDC_FIFO_EN_OBS_MASK
FIFO OBS enable/disable mask.
Referenced by XRFdc_GetFIFOStatusInt.
XRFDC_FIFO_EN_OBS_SHIFT
FIFO OBS enable/disable shift.
Referenced by XRFdc_GetFIFOStatusInt.
XRFDC_RESTART_MASK
Restart bit mask.
Referenced by XRFdc_SetClkDistribution.
XRFDC_CLK_EN_CAL_MASK
Enable Output Register clock.
XRFDC_CLK_EN_DIG_MASK
Enable full-rate clock.
XRFDC_CLK_EN_DP_MASK
Enable Data Path clock.
XRFDC_CLK_EN_FAB_MASK
Enable fabric clock.
XRFDC_DAT_CLK_EN_MASK
Data Path Clk enable.
Referenced by XRFdc_GetBlockStatus.
XRFDC_CLK_EN_LM_MASK
Enable for FIFO Latency measurement clock.
XRFDC_DBG_RST_CAL_MASK
Reset clk_cal clock domain.
XRFDC_DBG_RST_DP_MASK
Reset data path clock domain.
XRFDC_DBG_RST_FAB_MASK
Reset clock fabric clock domain.
XRFDC_DBG_RST_DIG_MASK
Reset clk_dig clock domain.
XRFDC_DBG_RST_DRP_CAL_MASK
Reset subadc-drp register on clock cal.
XRFDC_DBG_RST_LM_MASK
Reset FIFO Latency measurement clock domain.
XRFDC_ADC_FAB_RATE_WR_MASK
ADC FIFO Write Number of Words per clock.
XRFDC_DAC_FAB_RATE_WR_MASK
DAC FIFO Write Number of Words per clock.
Referenced by XRFdc_SetFabWrVldWords.
XRFDC_ADC_FAB_RATE_RD_MASK
ADC FIFO Read Number of Words per clock.
XRFDC_DAC_FAB_RATE_RD_MASK
DAC FIFO Read Number of Words per clock.
Referenced by XRFdc_SetDataPathMode.
XRFDC_FAB_RATE_RD_SHIFT
Fabric Read shift.
Referenced by XRFdc_SetDataPathMode.
XRFDC_FAB_RD_PTR_OFFST_MASK
FIFO read pointer offset for interface de-skew.
XRFDC_FAB_ISR_USRDAT_OVR_MASK
User-data overlap- data written faster than read (overflow)
XRFDC_FAB_ISR_USRDAT_UND_MASK
User-data overlap- data read faster than written (underflow)
XRFDC_FAB_ISR_USRDAT_MASK
User-data overlap Mask.
XRFDC_FAB_ISR_MARGIND_OVR_MASK
Marginal-indicator overlap (overflow)
XRFDC_FAB_ISR_MARGIND_UND_MASK
Marginal-indicator overlap (underflow)
XRFDC_FAB_IMR_USRDAT_OVR_MASK
User-data overlap- data written faster than read (overflow)
XRFDC_FAB_IMR_USRDAT_UND_MASK
User-data overlap- data read faster than written (underflow)
XRFDC_FAB_IMR_USRDAT_MASK
User-data overlap Mask.
XRFDC_FAB_IMR_MARGIND_OVR_MASK
Marginal-indicator overlap (overflow)
XRFDC_FAB_IMR_MARGIND_UND_MASK
Marginal-indicator overlap (underflow)
XRFDC_UPDT_EVNT_MASK
Update event mask.
Referenced by XRFdc_SetCoarseDelaySettings, XRFdc_SetMixerSettings, XRFdc_SetQMCSettings.
XRFDC_UPDT_EVNT_SLICE_MASK
Trigger a slice update event apply to _DCONFIG reg.
XRFDC_UPDT_EVNT_NCO_MASK
Trigger a update event apply to NCO_DCONFIG reg.
Referenced by XRFdc_SetMixerSettings.
XRFDC_UPDT_EVNT_QMC_MASK
Trigger a update event apply to QMC_DCONFIG reg.
Referenced by XRFdc_SetQMCSettings.
XRFDC_ADC_UPDT_CRSE_DLY_MASK
ADC Trigger a update event apply to Coarse delay_DCONFIG reg.
Referenced by XRFdc_SetCoarseDelaySettings.
XRFDC_DAC_UPDT_CRSE_DLY_MASK
DAC Trigger a update event apply to Coarse delay_DCONFIG reg.
Referenced by XRFdc_SetCoarseDelaySettings.
XRFDC_FIFO_LTNCY_PRD_MASK
Set FIFO Latency measurement period.
XRFDC_FIFO_LTNCY_RESTRT_MASK
Restart FIFO Latency measurement.
XRFDC_FIFO_LTNCY_DIS_MASK
Disable FIFO Latency measurement.
XRFDC_DEC_ISR_SUBADC_MASK
subadc decoder Mask
Referenced by XRFdc_GetIntrStatus.
XRFDC_DEC_ISR_SUBADC0_UND_MASK
subadc0 decoder underflow range
XRFDC_DEC_ISR_SUBADC0_OVR_MASK
subadc0 decoder overflow range
XRFDC_DEC_ISR_SUBADC1_UND_MASK
subadc1 decoder underflow range
XRFDC_DEC_ISR_SUBADC1_OVR_MASK
subadc1 decoder overflow range
XRFDC_DEC_ISR_SUBADC2_UND_MASK
subadc2 decoder underflow range
XRFDC_DEC_ISR_SUBADC2_OVR_MASK
subadc2 decoder overflow range
XRFDC_DEC_ISR_SUBADC3_UND_MASK
subadc3 decoder underflow range
XRFDC_DEC_ISR_SUBADC3_OVR_MASK
subadc3 decoder overflow range
XRFDC_DEC_IMR_SUBADC0_UND_MASK
subadc0 decoder underflow range
XRFDC_DEC_IMR_SUBADC0_OVR_MASK
subadc0 decoder overflow range
XRFDC_DEC_IMR_SUBADC1_UND_MASK
subadc1 decoder underflow range
XRFDC_DEC_IMR_SUBADC1_OVR_MASK
subadc1 decoder overflow range
XRFDC_DEC_IMR_SUBADC2_UND_MASK
subadc2 decoder underflow range
XRFDC_DEC_IMR_SUBADC2_OVR_MASK
subadc2 decoder overflow range
XRFDC_DEC_IMR_SUBADC3_UND_MASK
subadc3 decoder underflow range
XRFDC_DEC_IMR_SUBADC3_OVR_MASK
subadc3 decoder overflow range
XRFDC_DEC_IMR_MASK
XRFDC_DATAPATH_MODE_MASK
DataPath Mode.
Referenced by XRFdc_GetDataPathMode, XRFdc_GetMixerSettings, XRFdc_MultiBand, XRFdc_SetDataPathMode, XRFdc_SetInterpolationFactor, XRFdc_SetMixerSettings.
XRFDC_DATAPATH_IMR_MASK
IMR Mode.
Referenced by XRFdc_GetDataPathMode, XRFdc_GetIMRPassMode, XRFdc_SetDataPathMode, XRFdc_SetIMRPassMode.
XRFDC_DATAPATH_LATENCY_MASK
DataPath Latency.
XRFDC_DATAPATH_IMR_SHIFT
IMR Mode shift.
Referenced by XRFdc_GetDataPathMode, XRFdc_SetDataPathMode.
XRFDC_ADC_DAT_PATH_ISR_MASK
ADC Data Path Overflow.
Referenced by XRFdc_GetIntrStatus.
XRFDC_DAC_DAT_PATH_ISR_MASK
DAC Data Path Overflow.
Referenced by XRFdc_GetIntrStatus.
XRFDC_DAT_ISR_DECI_IPATH_MASK
Decimation I-Path overflow for stages 0,1,2.
XRFDC_DAT_ISR_INTR_QPATH_MASK
Interpolation Q-Path overflow for stages 0,1,2.
XRFDC_DAT_ISR_QMC_GAIN_MASK
QMC Gain/Phase overflow.
XRFDC_DAT_ISR_QMC_OFFST_MASK
QMC offset overflow.
XRFDC_DAC_DAT_ISR_INVSINC_MASK
Inverse-Sinc offset overflow.
XRFDC_DAT_IMR_DECI_IPATH_MASK
Decimation I-Path overflow for stages 0,1,2.
XRFDC_DAT_IMR_INTR_QPATH_MASK
Interpolation Q-Path overflow for stages 0,1,2.
XRFDC_DAT_IMR_QMC_GAIN_MASK
QMC Gain/Phase overflow.
XRFDC_DAT_IMR_QMC_OFFST_MASK
QMC offset overflow.
XRFDC_DAC_DAT_IMR_INV_SINC_MASK
Inverse Sinc overflow.
XRFDC_DAC_DAT_IMR_MXR_HLF_I_MASK
Over or under flow mixer (Mixer half I)
XRFDC_DAC_DAT_IMR_MXR_HLF_Q_MASK
Over or under flow mixer (Mixer half Q)
XRFDC_DAC_DAT_IMR_DP_SCALE_MASK
DataPath Scaling overflow.
XRFDC_DAC_DAT_IMR_INTR_IPATH3_MASK
Interpolation I-Path overflow for stage 3.
XRFDC_DAC_DAT_IMR_INTR_QPATH3_MASK
Interpolation Q-Path overflow for stage 3.
XRFDC_DAC_DAT_IMR_IMR_OV_MASK
IMR overflow.
XRFDC_DAC_DAT_IMR_INV_SINC_EVEN_NYQ_MASK
2nd Nyquist Zone Inverse SINC overflow
XRFDC_ADC_DAT_IMR_MASK
ADC DataPath mask.
Referenced by XRFdc_GetEnabledInterrupts, XRFdc_IntrEnable.
XRFDC_DAC_DAT_IMR_MASK
DAC DataPath mask.
Referenced by XRFdc_GetEnabledInterrupts, XRFdc_IntrEnable.
XRFDC_FIFO_USRD_OF_MASK
User data overflow.
XRFDC_FIFO_USRD_UF_MASK
User data underflow.
XRFDC_FIFO_MRGN_OF_MASK
Marginal overflow.
XRFDC_FIFO_MRGN_UF_MASK
Marginal underflow.
XRFDC_FIFO_ACTL_OF_MASK
DAC Actual overflow.
XRFDC_FIFO_ACTL_UF_MASK
DAC Actual underflow.
XRFDC_DAC_FIFO_IMR_SUPP_MASK
DAC FIFO Mask.
Referenced by XRFdc_GetEnabledInterrupts, XRFdc_GetIntrStatus.
XRFDC_DAC_FIFO_IMR_MASK
DAC FIFO Mask.
Referenced by XRFdc_IntrEnable.
XRFDC_DEC_CFG_MASK
ChannelA (2GSPS real data from Mixer I output)
Referenced by XRFdc_SetMixerSettings.
XRFDC_DEC_CFG_CHA_MASK
ChannelA(I)
Referenced by XRFdc_SetMixerSettings.
XRFDC_DEC_CFG_CHB_MASK
ChannelB (2GSPS real data from Mixer Q output)
XRFDC_DEC_CFG_IQ_MASK
IQ-2GSPS.
Referenced by XRFdc_SetMixerSettings.
XRFDC_DEC_CFG_4GSPS_MASK
4GSPS may be I or Q or Real depending on high level block config
Referenced by XRFdc_SetMixerSettings.
XRFDC_DEC_MOD_MASK
Decimation mode Mask.
XRFDC_DEC_MOD_MASK_EXT
Decimation mode Mask.
XRFDC_MIX_CFG0_MASK
Mixer Config0 Mask.
Referenced by XRFdc_GetMixerSettings.
XRFDC_MIX_I_DAT_WRD0_MASK
Output data word[0] of I channel.
XRFDC_MIX_I_DAT_WRD1_MASK
Output data word[1] of I channel.
XRFDC_MIX_I_DAT_WRD2_MASK
Output data word[2] of I channel.
XRFDC_MIX_I_DAT_WRD3_MASK
Output data word[3] of I channel.
XRFDC_MIX_CFG1_MASK
Mixer Config0 Mask.
Referenced by XRFdc_GetMixerSettings.
XRFDC_MIX_Q_DAT_WRD0_MASK
Output data word[0] of Q channel.
XRFDC_MIX_Q_DAT_WRD1_MASK
Output data word[1] of Q channel.
XRFDC_MIX_Q_DAT_WRD2_MASK
Output data word[2] of Q channel.
XRFDC_MIX_Q_DAT_WRD3_MASK
Output data word[3] of Q channel.
XRFDC_EN_I_IQ_MASK
Enable fine mixer multipliers on IQ i/p for I output.
Referenced by XRFdc_GetMixerSettings.
XRFDC_EN_Q_IQ_MASK
Enable fine mixer multipliers on IQ i/p for Q output.
Referenced by XRFdc_GetMixerSettings.
XRFDC_FINE_MIX_SCALE_MASK
NCO output scale.
Referenced by XRFdc_GetMixerSettings, XRFdc_SetMixerSettings.
XRFDC_SEL_I_IQ_MASK
Select NCO phases for I output.
XRFDC_SEL_Q_IQ_MASK
Select NCO phases for Q output.
XRFDC_I_IQ_COS_MINSIN
Select NCO phases for I output.
XRFDC_Q_IQ_SIN_COS
Select NCO phases for Q output.
XRFDC_MIXER_MODE_C2C_MASK
Mixer mode C2C Mask.
XRFDC_MIXER_MODE_R2C_MASK
Mixer mode R2C Mask.
XRFDC_MIXER_MODE_C2R_MASK
Mixer mode C2R Mask.
XRFDC_MIXER_MODE_OFF_MASK
Mixer mode OFF Mask.
XRFDC_NCO_UPDT_MODE_MASK
NCO event source selection mask.
Referenced by XRFdc_GetMixerSettings, XRFdc_SetMixerSettings, XRFdc_UpdateEvent.
XRFDC_NCO_UPDT_MODE_GRP
NCO event source selection is Group.
XRFDC_NCO_UPDT_MODE_SLICE
NCO event source selection is slice.
XRFDC_NCO_UPDT_MODE_TILE
NCO event source selection is tile.
XRFDC_NCO_UPDT_MODE_SYSREF
NCO event source selection is Sysref.
XRFDC_NCO_UPDT_MODE_MARKER
NCO event source selection is Marker.
XRFDC_NCO_UPDT_MODE_FABRIC
NCO event source selection is fabric.
XRFDC_NCO_UPDT_DLY_MASK
delay in clk_dp cycles in application of event after arrival
XRFDC_NCO_UPDT_RST_DLY_MASK
optional delay on the NCO phase reset delay
XRFDC_NCO_PHASE_RST_MASK
Reset NCO Phase of current slice.
Referenced by XRFdc_ResetNCOPhase.
XRFDC_DAC_INTERP_DATA_MASK
Data type mask.
Referenced by XRFdc_SetDataPathMode, XRFdc_SetMixerSettings.
XRFDC_NCO_FQWD_UPP_MASK
NCO Phase increment[47:32].
Referenced by XRFdc_SetMixerSettings.
XRFDC_NCO_FQWD_UPP_SHIFT
Freq Word upper shift.
Referenced by XRFdc_GetMixerSettings, XRFdc_SetMixerSettings.
XRFDC_NCO_FQWD_MID_MASK
NCO Phase increment[31:16].
Referenced by XRFdc_SetMixerSettings.
XRFDC_NCO_FQWD_MID_SHIFT
Freq Word Mid shift.
Referenced by XRFdc_GetMixerSettings, XRFdc_SetMixerSettings.
XRFDC_NCO_FQWD_LOW_MASK
NCO Phase increment[15:0].
XRFDC_NCO_FQWD_MASK
NCO Freq offset[48:0].
Referenced by XRFdc_GetMixerSettings.
XRFDC_NCO_PHASE_UPP_MASK
NCO Phase offset[17:16].
Referenced by XRFdc_SetMixerSettings.
XRFDC_NCO_PHASE_UPP_SHIFT
NCO phase upper shift.
Referenced by XRFdc_GetMixerSettings, XRFdc_SetMixerSettings.
XRFDC_NCO_PHASE_LOW_MASK
NCO Phase offset[15:0].
XRFDC_NCO_PHASE_MASK
NCO Phase offset[17:0].
Referenced by XRFdc_GetMixerSettings.
XRFDC_NCO_PHASE_MOD_MASK
NCO mode of operation mask.
XRFDC_NCO_PHASE_MOD_4PHASE
NCO output 4 successive phase.
XRFDC_NCO_PHASE_MOD_EVEN
NCO output even phase.
Referenced by XRFdc_SetMixerSettings.
XRFDC_NCO_PHASE_MODE_ODD
NCO output odd phase.
Referenced by XRFdc_SetMixerSettings.
XRFDC_QMC_UPDT_MODE_MASK
QMC event source selection mask.
Referenced by XRFdc_GetCoarseDelaySettings, XRFdc_GetQMCSettings, XRFdc_SetCoarseDelaySettings, XRFdc_SetQMCSettings, XRFdc_UpdateEvent.
XRFDC_QMC_UPDT_MODE_GRP
QMC event source selection is group.
XRFDC_QMC_UPDT_MODE_SLICE
QMC event source selection is slice.
XRFDC_QMC_UPDT_MODE_TILE
QMC event source selection is tile.
XRFDC_QMC_UPDT_MODE_SYSREF
QMC event source selection is Sysref.
XRFDC_QMC_UPDT_MODE_MARKER
QMC event source selection is Marker.
XRFDC_QMC_UPDT_MODE_FABRIC
QMC event source selection is fabric.
XRFDC_QMC_UPDT_DLY_MASK
delay in clk_dp cycles in application of event after arrival
XRFDC_QMC_CFG_EN_GAIN_MASK
enable QMC gain correction mask
Referenced by XRFdc_GetQMCSettings, XRFdc_SetQMCSettings.
XRFDC_QMC_CFG_EN_PHASE_MASK
enable QMC Phase correction mask
Referenced by XRFdc_GetQMCSettings, XRFdc_SetQMCSettings.
XRFDC_QMC_CFG_PHASE_SHIFT
QMC config phase shift.
Referenced by XRFdc_GetQMCSettings, XRFdc_SetQMCSettings.
XRFDC_QMC_OFFST_CRCTN_MASK
QMC offset correction factor.
Referenced by XRFdc_GetQMCSettings, XRFdc_SetQMCSettings.
XRFDC_QMC_OFFST_CRCTN_SIGN_MASK
QMC offset correction factor sign bit.
Referenced by XRFdc_GetQMCSettings.
XRFDC_QMC_GAIN_CRCTN_MASK
QMC gain correction factor.
Referenced by XRFdc_GetQMCSettings, XRFdc_SetQMCSettings.
XRFDC_QMC_PHASE_CRCTN_MASK
QMC phase correction factor.
Referenced by XRFdc_GetQMCSettings, XRFdc_SetQMCSettings.
XRFDC_QMC_PHASE_CRCTN_SIGN_MASK
QMC phase correction factor sign bit.
Referenced by XRFdc_GetQMCSettings.
XRFDC_CRSEDLY_UPDT_MODE_MASK
Coarse delay event source selection mask.
XRFDC_CRSEDLY_UPDT_MODE_GRP
Coarse delay event source selection is group.
XRFDC_CRSEDLY_UPDT_MODE_SLICE
Coarse delay event source selection is slice.
XRFDC_CRSEDLY_UPDT_MODE_TILE
Coarse delay event source selection is tile.
XRFDC_CRSEDLY_UPDT_MODE_SYSREF
Coarse delay event source selection is sysref.
XRFDC_CRSEDLY_UPDT_MODE_MARKER
Coarse delay event source selection is Marker.
XRFDC_CRSEDLY_UPDT_MODE_FABRIC
Coarse delay event source selection is fabric.
XRFDC_CRSEDLY_UPDT_DLY_MASK
delay in clk_dp cycles in application of event after arrival
XRFDC_CRSE_DLY_CFG_MASK
Coarse delay select.
Referenced by XRFdc_SetCoarseDelaySettings.
XRFDC_CRSE_DLY_CFG_MASK_EXT
Extended coarse delay select.
Referenced by XRFdc_SetCoarseDelaySettings.
XRFDC_DAT_SCALE_CFG_MASK
Enable data scaling.
XRFDC_DAT_SCALE_CFG_MASK
Enable data scaling.
XRFDC_SWITCH_MTRX_MASK
Switch matrix mask.
XRFDC_SEL_CB_TO_MIX1_MASK
Control crossbar switch that select the data to mixer block mux1.
Referenced by XRFdc_GetConnectedIQData.
XRFDC_SEL_CB_TO_MIX0_MASK
Control crossbar switch that select the data to mixer block mux0.
XRFDC_SEL_CB_TO_QMC_MASK
Control crossbar switch that select the data to QMC.
Referenced by XRFdc_SetQMCSettings.
XRFDC_SEL_CB_TO_DECI_MASK
Control crossbar switch that select the data to decimation filter.
XRFDC_SEL_CB_TO_MIX0_SHIFT
Crossbar Mixer0 shift.
XRFDC_TRSHD0_EN_MOD_MASK
Enable Threshold0 block.
Referenced by XRFdc_GetThresholdSettings, XRFdc_SetThresholdSettings.
XRFDC_TRSHD0_CLR_MOD_MASK
Clear mode.
Referenced by XRFdc_SetThresholdClrMode.
XRFDC_TRSHD0_STIKY_CLR_MASK
Clear sticky bit.
Referenced by XRFdc_ThresholdStickyClear.
XRFDC_TRSHD0_AVG_UPP_MASK
Threshold0 under Averaging[31:16].
XRFDC_TRSHD0_AVG_UPP_SHIFT
Threshold0 Avg upper shift.
Referenced by XRFdc_GetThresholdSettings, XRFdc_SetThresholdSettings.
XRFDC_TRSHD0_AVG_LOW_MASK
Threshold0 under Averaging[15:0].
XRFDC_TRSHD0_UNDER_MASK
Threshold0 under Threshold[13:0].
Referenced by XRFdc_GetThresholdSettings, XRFdc_SetThresholdSettings.
XRFDC_TRSHD0_OVER_MASK
Threshold0 under Threshold[13:0].
Referenced by XRFdc_GetThresholdSettings, XRFdc_SetThresholdSettings.
XRFDC_TRSHD1_EN_MOD_MASK
Enable Threshold1 block.
Referenced by XRFdc_GetThresholdSettings, XRFdc_SetThresholdSettings.
XRFDC_TRSHD1_CLR_MOD_MASK
Clear mode.
Referenced by XRFdc_SetThresholdClrMode.
XRFDC_TRSHD1_STIKY_CLR_MASK
Clear sticky bit.
Referenced by XRFdc_ThresholdStickyClear.
XRFDC_TRSHD1_AVG_UPP_MASK
Threshold1 under Averaging[31:16].
XRFDC_TRSHD1_AVG_UPP_SHIFT
Threshold1 Avg upper shift.
Referenced by XRFdc_GetThresholdSettings, XRFdc_SetThresholdSettings.
XRFDC_TRSHD1_AVG_LOW_MASK
Threshold1 under Averaging[15:0].
XRFDC_TRSHD1_UNDER_MASK
Threshold1 under Threshold[13:0].
Referenced by XRFdc_GetThresholdSettings, XRFdc_SetThresholdSettings.
XRFDC_TRSHD1_OVER_MASK
Threshold1 under Threshold[13:0].
Referenced by XRFdc_GetThresholdSettings, XRFdc_SetThresholdSettings.
XRFDC_TDD_CTRL_MASK
All TDD control bits.
XRFDC_TDD_CTRL_MODE01_MASK
The TDD mode control bits.
XRFDC_TDD_CTRL_MODE0_MASK
The TDD control bit for Mode 0 config.
Referenced by XRFdc_GetPwrMode, XRFdc_SetPwrMode.
XRFDC_TDD_CTRL_MODE1_MASK
The TDD control bit for Mode 1 config (unused)
XRFDC_TDD_CTRL_OBS_EN_MASK
The observation port enable.
XRFDC_TDD_CTRL_RTP_MASK
The IP RTS disable bit.
Referenced by XRFdc_GetPwrMode, XRFdc_SetPwrMode.
XRFDC_TDD_CTRL_RTP_OBS_MASK
The IP RTS disable bit for the observation channel.
XRFDC_TDD_CTRL_MODE1_SHIFT
The TDD control bit for Mode 1 config (unused)
XRFDC_TDD_CTRL_OBS_EN_SHIFT
The observation port enable.
XRFDC_TDD_CTRL_RTP_SHIFT
The IP RTS disable bit.
Referenced by XRFdc_GetPwrMode, XRFdc_SetPwrMode.
XRFDC_TDD_CTRL_RTP_OBS_SHIFT
The IP RTS disable bit for the observation channel.
XRFDC_FEND_DAT_CTRL_MASK
raw data and cal coefficient to be streamed to memory
XRFDC_TI_DCB_CTRL0_MASK
TI DCB gain and offset correction.
XRFDC_TI_DCB_MODE_MASK
TI DCB Mode mask.
Referenced by XRFdc_GetCalibrationMode, XRFdc_SetCalibrationMode.
XRFDC_TI_DCB_CTRL1_MASK
TI DCB gain and offset correction.
XRFDC_TI_DCB_CTRL2_MASK
TI DCB gain and offset correction.
XRFDC_TI_TISK_EN_MASK
Block Enable.
XRFDC_TI_TISK_MODE_MASK
Mode (2G/4G)
XRFDC_TI_TISK_ZONE_MASK
Specifies Nyquist zone.
Referenced by XRFdc_GetNyquistZone, XRFdc_SetNyquistZone.
XRFDC_TI_TISK_CHOP_EN_MASK
enable chopping mode
XRFDC_TI_TISK_MU_CM_MASK
Constant mu_cm multiplying common mode path.
XRFDC_TI_TISK_MU_DF_MASK
Constant mu_df multiplying differential path.
XRFDC_TI_TISK_DBG_CTRL_MASK
Debug control.
XRFDC_TI_TISK_DBG_UPDT_RT_MASK
Debug update rate.
XRFDC_TI_TISK_DITH_DLY_MASK
Programmable delay on dither path to match data path.
XRFDC_TISK_ZONE_SHIFT
Nyquist zone shift.
Referenced by XRFdc_GetNyquistZone.
XRFDC_TISK_EN_MASK
Block Enable.
XRFDC_TISK_MODE_MASK
Mode (2G/4G)
XRFDC_TISK_ZONE_MASK
Specifies Nyquist zone.
XRFDC_TISK_CHOP_EN_MASK
enable chopping mode
XRFDC_TISK_MU_CM_MASK
Constant mu_cm multiplying common mode path.
XRFDC_TISK_MU_DF_MASK
Constant mu_df multiplying differential path.
XRFDC_TISK_DBG_CTRL_MASK
Debug control.
XRFDC_TISK_DBG_UPDT_RT_MASK
Debug update rate.
XRFDC_TISK_DITH_DLY_MASK
Programmable delay on dither path to match data path.
XRFDC_MC_CFG0_MIX_MODE_MASK
Enable Mixing mode.
Referenced by XRFdc_GetNyquistZone, XRFdc_SetNyquistZone.
XRFDC_MC_CFG0_MIX_MODE_SHIFT
Mix mode shift.
Referenced by XRFdc_GetNyquistZone.
XRFDC_TISK_DZ_MIN_VAL_MASK
Deadzone min.
XRFDC_TISK_DZ_MAX_VAL_MASK
Deadzone max.
XRFDC_TISK_MU0_MASK
Filter0 multiplying factor.
XRFDC_TISK_BYPASS0_MASK
ByPass filter0.
XRFDC_TISK_MU1_MASK
Filter1 multiplying factor.
XRFDC_TISK_BYPASS1_MASK
Filter1 multiplying factor.
XRFDC_TISK_SETTLE_MASK
Settling time following code update.
XRFDC_TISK_CAL_PRI_MASK
XRFDC_TISK_DITH_INV_MASK
XRFDC_TISK_DAC0_CODE_MASK
Code to correction DAC of subadc ch0 front end switch0.
XRFDC_TISK_DAC0_OVRID_EN_MASK
override enable
XRFDC_TISK_DAC1_CODE_MASK
Code to correction DAC of subadc ch1 front end switch0.
XRFDC_TISK_DAC1_OVRID_EN_MASK
override enable
XRFDC_TISK_DAC2_CODE_MASK
Code to correction DAC of subadc ch2 front end switch0.
XRFDC_TISK_DAC2_OVRID_EN_MASK
override enable
XRFDC_TISK_DAC3_CODE_MASK
Code to correction DAC of subadc ch3 front end switch0.
XRFDC_TISK_DAC3_OVRID_EN_MASK
override enable
XRFDC_TISK_DACP0_CODE_MASK
Code to correction DAC of subadc ch0 front end switch1.
XRFDC_TISK_DACP0_OVRID_EN_MASK
override enable
XRFDC_TISK_DACP1_CODE_MASK
Code to correction DAC of subadc ch1 front end switch1.
XRFDC_TISK_DACP1_OVRID_EN_MASK
override enable
XRFDC_TISK_DACP2_CODE_MASK
Code to correction DAC of subadc ch2 front end switch1.
XRFDC_TISK_DACP2_OVRID_EN_MASK
override enable
XRFDC_TISK_DACP3_CODE_MASK
Code to correction DAC of subadc ch3 front end switch1.
XRFDC_TISK_DACP3_OVRID_EN_MASK
override enable
XRFDC_SUBDRP_ADC0_ADDR_MASK
sub-drp0 address
XRFDC_SUBDRP_ADC0_DAT_MASK
sub-drp0 data for read or write transaction
XRFDC_SUBDRP_ADC1_ADDR_MASK
sub-drp1 address
XRFDC_SUBDRP_ADC1_DAT_MASK
sub-drp1 data for read or write transaction
XRFDC_SUBDRP_ADC2_ADDR_MASK
sub-drp2 address
XRFDC_SUBDRP_ADC2_DAT_MASK
sub-drp2 data for read or write transaction
XRFDC_SUBDRP_ADC3_ADDR_MASK
sub-drp3 address
XRFDC_SUBDRP_ADC3_DAT_MASK
sub-drp3 data for read or write transaction
XRFDC_RX_MC_PWRDWN_MASK
RX MC power down.
XRFDC_RX_MC_CFG0_MASK
RX MC config0.
XRFDC_RX_MC_CFG0_CM_MASK
Coupling mode mask.
Referenced by XRFdc_GetCoupling, XRFdc_GetLinkCoupling.
XRFDC_RX_MC_CFG0_IM3_DITH_MASK
IM3 Dither Enable mode mask.
Referenced by XRFdc_GetDither, XRFdc_SetDither.
XRFDC_RX_MC_CFG0_IM3_DITH_SHIFT
IM3 Dither Enable mode shift.
Referenced by XRFdc_SetDither.
XRFDC_RX_MC_CFG1_MASK
RX MC Config1.
XRFDC_RX_MC_CFG2_MASK
RX MC Config2.
XRFDC_RX_PR_MC_CFG0_MASK
RX Pair MC Config0.
XRFDC_RX_PR_MC_CFG0_PSNK_MASK
RX Pair MC Config0.
Referenced by XRFdc_DynamicPLLConfig.
XRFDC_RX_PR_MC_CFG0_IDIV_MASK
RX Pair MC Config0.
Referenced by XRFdc_DynamicPLLConfig.
XRFDC_RX_PR_MC_CFG1_MASK
RX Pair MC Config1.
XRFDC_TI_DCB_STS0_BG_MASK
DCB Status0 BG.
XRFDC_TI_DCB_STS0_FG_MASK
DCB Status0 FG.
XRFDC_TI_DCB_STS1_BG_MASK
DCB Status1 BG.
XRFDC_TI_DCB_STS1_FG_MASK
DCB Status1 FG.
XRFDC_TI_DCB_STS2_BG_MASK
DCB Status2 BG.
XRFDC_TI_DCB_STS2_FG_MASK
DCB Status2 FG.
XRFDC_TI_DCB_STS3_BG_MASK
DCB Status3 BG.
XRFDC_TI_DCB_STS3_FG_MASK
DCB Status3 FG.
XRFDC_TI_DCB_STS4_MSB_MASK
read the status of gcb acc0 msb bits(subadc chan0)
XRFDC_TI_DCB_STS4_LSB_MASK
read the status of gcb acc0 lsb bits(subadc chan0)
XRFDC_TI_DCB_STS5_MSB_MASK
read the status of gcb acc1 msb bits(subadc chan1)
XRFDC_TI_DCB_STS5_LSB_MASK
read the status of gcb acc1 lsb bits(subadc chan1)
XRFDC_TI_DCB_STS6_MSB_MASK
read the status of gcb acc2 msb bits(subadc chan2)
XRFDC_TI_DCB_STS6_LSB_MASK
read the status of gcb acc2 lsb bits(subadc chan2)
XRFDC_TI_DCB_STS7_MSB_MASK
read the status of gcb acc3 msb bits(subadc chan3)
XRFDC_TI_DCB_STS7_LSB_MASK
read the status of gcb acc3 lsb bits(subadc chan3)
XRFDC_REFCLK_DIV_MASK
XRFDC_REFCLK_DIV_1_MASK
Mask for Div1.
XRFDC_REFCLK_DIV_2_MASK
Mask for Div2.
Referenced by XRFdc_GetPLLConfig.
XRFDC_REFCLK_DIV_3_MASK
Mask for Div3.
Referenced by XRFdc_GetPLLConfig.
XRFDC_REFCLK_DIV_4_MASK
Mask for Div4.
Referenced by XRFdc_GetPLLConfig.
XRFDC_FIFO_LTNCY_RES_MASK
Latency measurement result.
XRFDC_FIFO_LTNCY_KEY_MASK
Latency measurement result identification key.
XRFDC_FIFO_LTNCY_DONE_MASK
Latency measurement done flag.
XRFDC_DEC_CTRL_MODE_MASK
Decoder mode.
Referenced by XRFdc_GetDecoderMode, XRFdc_SetDecoderMode.
XRFDC_HSCOM_PWR_STATE_MASK
powerup state mask
XRFDC_INTERP_MODE_MASK
Interp filter mask.
Referenced by XRFdc_SetInterpolationFactor.
XRFDC_INTERP_MODE_I_MASK
Interp filter I.
Referenced by XRFdc_GetInterpolationFactor.
XRFDC_INTERP_MODE_Q_SHIFT
Interp mode Q shift.
Referenced by XRFdc_SetInterpolationFactor.
XRFDC_INTERP_MODE_MASK_EXT
Interp filter mask.
Referenced by XRFdc_SetDataPathMode, XRFdc_SetInterpolationFactor.
XRFDC_INTERP_MODE_I_MASK_EXT
Interp filter I.
Referenced by XRFdc_GetInterpolationFactor, XRFdc_SetDataPathMode.
XRFDC_INTERP_MODE_Q_SHIFT_EXT
Interp mode Q shift.
Referenced by XRFdc_SetInterpolationFactor.
XRFDC_DAC_TILES_ENABLED_SHIFT
Shift to the DAC tile bits.
Referenced by XRFdc_CheckTileEnabled.
XRFDC_DIGITAL_PATH_ENABLED_SHIFT
Shift to the digital path bits.
Referenced by XRFdc_IsADCDigitalPathEnabled, XRFdc_IsDACDigitalPathEnabled.
XRFDC_TILE_RESET_MASK
Tile reset mask.
XRFDC_PWR_UP_STAT_MASK
Power Up state mask.
Referenced by XRFdc_DynamicPLLConfig, XRFdc_GetIPStatus.
XRFDC_PWR_UP_STAT_SHIFT
PowerUp status shift.
Referenced by XRFdc_DynamicPLLConfig, XRFdc_GetIPStatus.
XRFDC_PLL_LOCKED_MASK
PLL Locked mask.
Referenced by XRFdc_GetIPStatus, XRFdc_GetPLLLockStatus.
XRFDC_PLL_LOCKED_SHIFT
PLL locked shift.
Referenced by XRFdc_GetIPStatus.
XRFDC_PWR_STATE_MASK
State mask.
Referenced by XRFdc_SetClkDistribution.
XRFDC_RSR_START_SHIFT
Start state shift.
Referenced by XRFdc_SetClkDistribution.
XRFDC_CLOCK_DETECT_MASK
Clock detect mask.
Referenced by XRFdc_SetClkDistribution.
XRFDC_CLOCK_DETECT_SRC_MASK
Clock detect mask.
Referenced by XRFdc_GetClkDistribution, XRFdc_SetClkDistribution.
XRFDC_CLOCK_DETECT_DST_SHIFT
Clock detect mask.
Referenced by XRFdc_SetClkDistribution.
XRFDC_EN_INTR_DAC_TILE0_MASK
DAC Tile0 interrupt enable mask.
Referenced by XRFdc_IntrHandler.
XRFDC_EN_INTR_DAC_TILE1_MASK
DAC Tile1 interrupt enable mask.
Referenced by XRFdc_IntrHandler.
XRFDC_EN_INTR_DAC_TILE2_MASK
DAC Tile2 interrupt enable mask.
Referenced by XRFdc_IntrHandler.
XRFDC_EN_INTR_DAC_TILE3_MASK
DAC Tile3 interrupt enable mask.
Referenced by XRFdc_IntrHandler.
XRFDC_EN_INTR_ADC_TILE0_MASK
ADC Tile0 interrupt enable mask.
Referenced by XRFdc_IntrHandler.
XRFDC_EN_INTR_ADC_TILE1_MASK
ADC Tile1 interrupt enable mask.
Referenced by XRFdc_IntrHandler.
XRFDC_EN_INTR_ADC_TILE2_MASK
ADC Tile2 interrupt enable mask.
Referenced by XRFdc_IntrHandler.
XRFDC_EN_INTR_ADC_TILE3_MASK
ADC Tile3 interrupt enable mask.
Referenced by XRFdc_IntrHandler.
XRFDC_EN_INTR_SLICE_MASK
Slice intr mask.
XRFDC_EN_INTR_SLICE0_MASK
slice0 interrupt enable mask
Referenced by XRFdc_IntrHandler.
XRFDC_EN_INTR_SLICE1_MASK
slice1 interrupt enable mask
Referenced by XRFdc_IntrHandler.
XRFDC_EN_INTR_SLICE2_MASK
slice2 interrupt enable mask
Referenced by XRFdc_IntrHandler.
XRFDC_EN_INTR_SLICE3_MASK
slice3 interrupt enable mask
Referenced by XRFdc_IntrHandler.
XRFDC_INTR_COMMON_MASK
Common interrupt enable mask.
Referenced by XRFdc_GetIntrStatus, XRFdc_IntrHandler.
XRFDC_INTR_OVR_RANGE_MASK
Over Range interrupt mask.
Referenced by XRFdc_GetIntrStatus.
XRFDC_INTR_OVR_VOLTAGE_MASK
Over Voltage interrupt mask.
Referenced by XRFdc_GetIntrStatus.
XRFDC_INTR_FIFO_OVR_MASK
FIFO OF mask.
Referenced by XRFdc_GetIntrStatus.
XRFDC_INTR_DAT_OVR_MASK
Data OF mask.
Referenced by XRFdc_GetIntrStatus.
XRFDC_INTR_CMODE_OVR_MASK
Common mode OV mask.
Referenced by XRFdc_GetIntrStatus.
XRFDC_INTR_CMODE_UNDR_MASK
Common mode UV mask.
Referenced by XRFdc_GetIntrStatus.
XRFDC_EN_MB_MASK
multi-band adder mask
XRFDC_EN_MB_SHIFT
XRFDC_DAC_MB_SEL_MASK
XRFDC_ALT_BOND_MASK
XRFDC_ALT_BOND_SHIFT
XRFDC_ALT_BOND_CLKDP_MASK
XRFDC_ALT_BOND_CLKDP_SHIFT
XRFDC_MB_CONFIG_MASK
XRFDC_EN_INVSINC_MASK
invsinc enable mask
Referenced by XRFdc_GetInvSincFIR, XRFdc_SetInvSincFIR.
XRFDC_MODE_INVSINC_MASK
invsinc mode mask
Referenced by XRFdc_GetInvSincFIR, XRFdc_SetInvSincFIR.
XRFDC_HSCOM_FIFO_START_OBS_EN_MASK
invsinc enable mask
XRFDC_HSCOM_FIFO_START_OBS_EN_SHIFT
invsinc mode mask
XRFDC_ADC_SIG_DETECT_MASK
signal detector mask
Referenced by XRFdc_GetSignalDetector, XRFdc_SetSignalDetector.
XRFDC_ADC_SIG_DETECT_THRESH_MASK
signal detector thresholds mask
XRFDC_ADC_SIG_DETECT_THRESH_CNT_MASK
signal detector thresholds counter mask
XRFDC_ADC_SIG_DETECT_INTG_MASK
leaky integrator enable mask
Referenced by XRFdc_GetSignalDetector.
XRFDC_ADC_SIG_DETECT_FLUSH_MASK
leaky integrator flush mask
Referenced by XRFdc_GetSignalDetector.
XRFDC_ADC_SIG_DETECT_TCONST_MASK
time constant mask
Referenced by XRFdc_GetSignalDetector.
XRFDC_ADC_SIG_DETECT_MODE_MASK
mode mask
Referenced by XRFdc_GetSignalDetector.
XRFDC_ADC_SIG_DETECT_HYST_MASK
hysteresis enable mask
Referenced by XRFdc_GetSignalDetector.
XRFDC_ADC_SIG_DETECT_INTG_SHIFT
leaky integrator enable shift
Referenced by XRFdc_GetSignalDetector, XRFdc_SetSignalDetector.
XRFDC_ADC_SIG_DETECT_FLUSH_SHIFT
leaky integrator flush shift
Referenced by XRFdc_GetSignalDetector, XRFdc_SetSignalDetector.
XRFDC_ADC_SIG_DETECT_TCONST_SHIFT
time constant shift
Referenced by XRFdc_GetSignalDetector, XRFdc_SetSignalDetector.
XRFDC_ADC_SIG_DETECT_MODE_WRITE_SHIFT
mode shift fror writing
Referenced by XRFdc_SetSignalDetector.
XRFDC_ADC_SIG_DETECT_MODE_READ_SHIFT
mode shift fror reading
Referenced by XRFdc_GetSignalDetector.
XRFDC_ADC_SIG_DETECT_HYST_SHIFT
hysteresis enable shift
Referenced by XRFdc_GetSignalDetector, XRFdc_SetSignalDetector.
XRFDC_FAB_CLK_DIV_MASK
clk div mask
Referenced by XRFdc_GetFabClkOutDiv, XRFdc_SetFabClkOutDiv.
XRFDC_FAB_CLK_DIV_CAL_MASK
clk div cal mask
Referenced by XRFdc_SetDataPathMode.
XRFDC_FAB_CLK_DIV_SYNC_PULSE_MASK
clk div cal mask
XRFDC_MB_CFG_MASK
MB config mask.
XRFDC_MB_EN_4X_MASK
Enable 4X MB mask.
XRFDC_MTS_SRCAP_PLL_M
XRFDC_MTS_SRCAP_DIG_M
XRFDC_MTS_SRCAP_EN_TRX_M
XRFDC_MTS_SRCAP_INIT_M
XRFDC_MTS_SRCLR_T1_M
XRFDC_MTS_SRCLR_PLL_M
XRFDC_MTS_PLLEN_M
XRFDC_MTS_SRCOUNT_M
XRFDC_MTS_DELAY_VAL_M
XRFDC_MTS_AMARK_CNT_M
XRFDC_MTS_AMARK_LOC_M
XRFDC_MTS_AMARK_DONE_M
XRFDC_PLL_DIVIDER0_MASK
XRFDC_PLL_DIVIDER0_MODE_MASK
XRFDC_PLL_DIVIDER0_BYP_OPDIV_MASK
XRFDC_PLL_DIVIDER0_BYP_PLL_MASK
XRFDC_PLL_DIVIDER0_VALUE_MASK
XRFDC_PLL_DIVIDER0_SHIFT
XRFDC_CLK_NETWORK_CTRL1_USE_PLL_MASK
PLL clock mask.
Referenced by XRFdc_DynamicPLLConfig, XRFdc_GetClockSource.
XRFDC_CLK_NETWORK_CTRL1_USE_RX_MASK
PLL clock mask.
XRFDC_CLK_NETWORK_CTRL1_REGS_MASK
PLL clock mask.
Referenced by XRFdc_DynamicPLLConfig.
XRFDC_CLK_NETWORK_CTRL1_EN_SYNC_MASK
PLL clock mask.
XRFDC_PLL_CRS1_VCO_SEL_MASK
VCO SEL Mask.
XRFDC_PLL_VCO_SEL_AUTO_MASK
VCO Auto SEL Mask.
XRFDC_DIGI_ANALOG_SHIFT4
Register bits Shift, Width Masks.
XRFDC_DIGI_ANALOG_SHIFT8
XRFDC_DIGI_ANALOG_SHIFT12
XRFDC_DAC_FIFO_DELAY_MASK
DAC FIFO ReadPtr Delay.
Referenced by XRFdc_SetInterpolationFactor.
XRFDC_ADC_FIFO_DELAY_MASK
ADC FIFO ReadPtr Delay.
XRFDC_ADC_FIFO_DELAY_SHIFT
ADC FIFO ReadPtr Shift.
XRFDC_DATA_SCALER_MASK
Clock detect mask.
Referenced by XRFdc_GetDACDataScaler, XRFdc_SetDACDataScaler.
XRFDC_CAL_DIV_BYP_MASK
Calibration divider bypass mask.
Referenced by XRFdc_CustomStartUp, XRFdc_DynamicPLLConfig.
typedef __u32 u32
typedef __u16 u16
typedef __u8 u8
typedef __s32 s32
typedef __s16 s16
typedef __u64 u64
typedef __s64 s64
typedef __s8 s8
typedef void(* XRFdc_StatusHandler)(void *CallBackRef, u32 Type, u32 Tile_Id, u32 Block_Id, u32 StatusEvent))(void *CallBackRef, u32 Type, u32 Tile_Id, u32 Block_Id, u32 StatusEvent)
The handler data type allows the user to define a callback function to respond to interrupt events in the system.
This function is executed in interrupt context, so amount of processing should be minimized. CallBackRef is the callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. Its type is not important to the driver, so it is a void pointer. Type indicates ADC/DAC. Tile_Id indicates Tile number (0-3). Block_Id indicates Block number (0-3). StatusEvent indicates one or more interrupt occurred.
u32 PllTuningMatrix[8][4][2][8][4][2]
XRFdc_Config* XRFdc_ConfigTablePtr
static u32 XRFdc_RestartIPSM(XRFdc *InstancePtr, u32 Type, int Tile_Id, u32 Start, u32 End)
Restarts a requested the tile and ensures that starts from a defined start state and reaches the requested or defined end state.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3, and -1. Start is start state of State Machine End is end state of State Machine. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
static void StubHandler(void *CallBackRefPtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 StatusEvent)
This is a stub for the status callback.
The stub is here in case the upper layers forget to set the handler. CallBackRefPtr is a pointer to the upper layer callback reference. Type indicates ADC/DAC. Tile_Id indicates Tile number (0-3). Block_Id indicates Block number (0-3). StatusEvent indicates one or more interrupt occurred. None.None.
static void XRFdc_ADCInitialize(XRFdc *InstancePtr)
Initialize ADC Tiles.
InstancePtr is a pointer to the XRfdc instance. None. Static API used to initialize ADC Tiles
static void XRFdc_DACInitialize(XRFdc *InstancePtr)
Initialize DAC Tiles.
InstancePtr is a pointer to the XRfdc instance. None. Static API used to initialize DAC Tiles
static void XRFdc_DACMBConfigInit(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id)
Initialize Multiband Configuration for DAC Tiles.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3, and -1. Block_Id is DAC block number inside the tile. Valid values are 0-3. None. Static API used to initialize DAC MB Config
static void XRFdc_ADCMBConfigInit(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id)
Initialize Multiband Configuration for ADC Tiles.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3, and -1. Block_Id is ADC block number inside the tile. Valid values are 0-3. None. Static API used to initialize ADC MB Config
static void XRFdc_UpdatePLLStruct(XRFdc *InstancePtr, u32 Type, u32 Tile_Id)
This API updates PLL Structure.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC. Tile_Id Valid values are 0-3, and -1. None. Static API used to initialize PLL Settings for ADC and DAC
static u32 XRFdc_GetADCBlockStatus(XRFdc *InstancePtr, u32 BaseAddr, u32 Tile_Id, u32 Block_Id, XRFdc_BlockStatus *BlockStatusPtr)
The API returns the requested block status for ADC block.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. XRFdc_BlockStatus. BlockStatus is Pointer to the XRFdc_BlockStatus structure through which the ADC/DAC block status is returned. XRFDC_SUCCESS if successful.XRFDC_FAILURE if block not enabled. Static API for ADC blocks.
static u32 XRFdc_GetDACBlockStatus(XRFdc *InstancePtr, u32 BaseAddr, u32 Tile_Id, u32 Block_Id, XRFdc_BlockStatus *BlockStatusPtr)
The API returns the requested block status for DAC block.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. XRFdc_BlockStatus. BlockStatus is Pointer to the XRFdc_BlockStatus structure through which the DAC block status is returned. XRFDC_SUCCESS if successful.XRFDC_FAILURE if block not enabled. Static API for DAC blocks.
static void XRFdc_DumpHSCOMRegs(XRFdc *InstancePtr, u32 Type, int Tile_Id)
Static API to dump HSCOM registers.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3, and -1. None None.
static void XRFdc_DumpDACRegs(XRFdc *InstancePtr, int Tile_Id)
Static API to dump DAC registers.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3, and -1. None None.
static void XRFdc_DumpADCRegs(XRFdc *InstancePtr, int Tile_Id)
Static API to dump ADC registers.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3, and -1. None None.
static u32 XRFdc_WaitForRestartClr(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 BaseAddr, u32 End)
This Static API will be used to wait for restart bit clears and also check for PLL Lock if clock source is internal PLL.
InstancePtr is a pointer to the XRfdc instance. End is end state of State Machine. XRFDC_SUCCESS if successful.XRFDC_FAILURE if timeout occurs. None.
u32 XRFdc_CfgInitialize(XRFdc *InstancePtr, XRFdc_Config *ConfigPtr)
Initializes a specific XRFdc instance such that the driver is ready to use.
InstancePtr is a pointer to the XRfdc instance. ConfigPtr is a reference to a structure containing information about xrfdc. This function initializes an InstancePtr object for a specific device specified by the contents of Config. XRFDC_SUCCESS if successful. The user needs to first call the XRFdc_LookupConfig() API which returns the Configuration structure pointer which is passed as a parameter to the XRFdc_CfgInitialize() API.
Referenced by RFdcMTS_Example.
u32 XRFdc_StartUp(XRFdc *InstancePtr, u32 Type, int Tile_Id)
The API Restarts the requested tile.
It can restart a single tile and alternatively can restart all the tiles. Existing register settings are not lost or altered in the process. It just starts the requested tile(s). InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3, and -1. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
u32 XRFdc_Shutdown(XRFdc *InstancePtr, u32 Type, int Tile_Id)
The API stops the tile as requested.
It can also stop all the tiles if asked for. It does not clear any of the existing register settings. It just stops the requested tile(s). InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3, and -1. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
u32 XRFdc_Reset(XRFdc *InstancePtr, u32 Type, int Tile_Id)
The API resets the requested tile.
It can reset all the tiles as well. In the process, all existing register settings are cleared and are replaced with the settings initially configured (through the GUI). InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3, and -1. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
u32 XRFdc_CustomStartUp(XRFdc *InstancePtr, u32 Type, int Tile_Id, u32 StartState, u32 EndState)
The API starts the requested tile from a provided state and runs to the given end state.
It can restart a single tile and alternatively can restart all the tiles. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3, and -1. StartState Valid values are XRFDC_START_STATE_*. Tile_Id Valid values are XRFDC_END_STATE_*. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. If starting from/ending at XRFDC_START_STATE_OFF/XRFDC_END_STATE_OFF, register settings will be wiped.
References XRFDC_CAL_DIV_BYP_MASK, XRFDC_CAL_DIV_BYP_OFFSET, XRFDC_CAL_DLY_OFFSET, XRFDC_CAL_TMR_MULT_OFFSET, XRFdc_ClrSetReg, XRFdc_IsHighSpeedADC, XRFdc_ReadReg, XRFdc_WriteReg.
Referenced by XRFdc_DynamicPLLConfig.
u32 XRFdc_WaitForState(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 State)
This function is used to wait for a tile to reach a given state.
InstancePtr is a pointer to the XRfdc instance. Type represents ADC or DAC. Tile_Id Valid values are 0-3. State represents the state which the tile must reach. XRFDC_SUCCESS if valid.XRFDC_FAILURE if not valid.
References XRFdc_CheckTileEnabled, XRFDC_CURRENT_STATE_MASK, XRFDC_CURRENT_STATE_OFFSET, XRFdc_RDReg.
Referenced by XRFdc_SetClkDistribution.
u32 XRFdc_GetIPStatus(XRFdc *InstancePtr, XRFdc_IPStatus *IPStatusPtr)
The API returns the IP status.
InstancePtr is a pointer to the XRfdc instance. IPStatusPtr Pointer to the XRFdc_IPStatus structure through which the status is returned. XRFDC_SUCCESS if successful. None.
References XRFDC_CURRENT_STATE_OFFSET, XRFdc_IsADCBlockEnabled, XRFdc_IsDACBlockEnabled, XRFDC_PLL_LOCKED_MASK, XRFDC_PLL_LOCKED_SHIFT, XRFDC_PWR_UP_STAT_MASK, XRFDC_PWR_UP_STAT_SHIFT, XRFdc_ReadReg16, XRFDC_STATUS_OFFSET.
Referenced by XRFdc_MultiConverter_Sync.
u32 XRFdc_GetBlockStatus(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, XRFdc_BlockStatus *BlockStatusPtr)
The API returns the requested block status.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. XRFdc_BlockStatus. BlockStatusPtr is Pointer to the XRFdc_BlockStatus structure through which the ADC/DAC block status is returned. XRFDC_SUCCESS if successful.XRFDC_FAILURE if block not enabled. Common API for ADC/DAC blocks.
References XRFdc_CheckBlockEnabled, XRFDC_CLK_EN_OFFSET, XRFDC_DAT_CLK_EN_MASK, XRFdc_IsHighSpeedADC, XRFdc_RDReg.
u32 XRFdc_SetDataPathMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 Mode)
This API is to set the DAC Datapath mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Mode valid values are 0-3. XRFDC_SUCCESS if successful.XRFDC_FAILURE if tile not enabled / out of range. Only for DAC blocks
References XRFdc_CheckBlockEnabled, XRFdc_CheckDigitalPathEnabled, XRFdc_ClrSetReg, XRFDC_DAC_DATAPATH_OFFSET, XRFDC_DAC_FAB_RATE_RD_MASK, XRFDC_DAC_FABRIC_RATE_OFFSET, XRFDC_DAC_INTERP_CTRL_OFFSET, XRFDC_DAC_INTERP_DATA_MASK, XRFDC_DAC_ITERP_DATA_OFFSET, XRFDC_DATAPATH_IMR_MASK, XRFDC_DATAPATH_IMR_SHIFT, XRFDC_DATAPATH_MODE_MASK, XRFDC_FAB_CLK_DIV_CAL_MASK, XRFDC_FAB_RATE_RD_SHIFT, XRFdc_GetMixerSettings, XRFDC_HSCOM_CLK_DIV_OFFSET, XRFDC_INTERP_MODE_I_MASK_EXT, XRFDC_INTERP_MODE_MASK_EXT, XRFdc_RDReg, XRFdc_SetMixerSettings.
u32 XRFdc_GetDataPathMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *ModePtr)
This API is to get the DAC Datapath mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. ModePtr pointer used to return value. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for DAC blocks
References XRFdc_CheckDigitalPathEnabled, XRFDC_DAC_DATAPATH_OFFSET, XRFDC_DATAPATH_IMR_MASK, XRFDC_DATAPATH_IMR_SHIFT, XRFDC_DATAPATH_MODE_MASK, XRFdc_RDReg.
u32 XRFdc_SetIMRPassMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 Mode)
This API is to set the DAC Image Reject Filter Pass mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Mode valid values are 0 (for low pass) 1 (for high pass). XRFDC_SUCCESS if successful.XRFDC_FAILURE if tile not enabled / bad parameter passed Only for DAC blocks
References XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFDC_DAC_DATAPATH_OFFSET, XRFDC_DATAPATH_IMR_MASK.
u32 XRFdc_GetIMRPassMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *ModePtr)
This API is to get the DAC Image Reject Filter Pass mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. ModePtr pointer used to return value. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for DAC blocks
References XRFdc_CheckBlockEnabled, XRFDC_DAC_DATAPATH_OFFSET, XRFDC_DATAPATH_IMR_MASK, XRFdc_RDReg.
void XRFdc_DumpRegs(XRFdc *InstancePtr, u32 Type, int Tile_Id)
This Prints the offset of the register along with the content.
This API is meant to be used for debug purposes. It prints to the console the contents of registers for the passed Tile_Id. If -1 is passed, it prints the contents of the registers for all the tiles for the respective ADC or DAC InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3, and -1. None None.
u32 XRFdc_SetPwrMode(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, XRFdc_Pwr_Mode_Settings *SettingsPtr)
Set The Power up/down mode of a given converter.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id Valid values are 0-3. SettingsPtr is a pointer with the power mode settings. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Common API for ADC/DAC blocks
References XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFdc_IsHighSpeedADC, XRFDC_TDD_CTRL_MODE0_MASK, XRFDC_TDD_CTRL_RTP_MASK, XRFDC_TDD_CTRL_RTP_SHIFT, XRFDC_TDD_CTRL_SLICE_OFFSET.
u32 XRFdc_GetPwrMode(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, XRFdc_Pwr_Mode_Settings *SettingsPtr)
Get The Power up/down mode of a given converter.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id Valid values are 0-3. SettingsPtr is a pointer to be filled with the power mode settings. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Common API for ADC/DAC blocks
References XRFdc_CheckBlockEnabled, XRFdc_IsHighSpeedADC, XRFdc_RDReg, XRFDC_TDD_CTRL_MODE0_MASK, XRFDC_TDD_CTRL_RTP_MASK, XRFDC_TDD_CTRL_RTP_SHIFT, XRFDC_TDD_CTRL_SLICE_OFFSET.
void XRFdc_ClrSetReg(XRFdc *InstancePtr, u32 BaseAddr, u32 RegAddr, u16 Mask, u16 Data)
Execute Read modify Write.
InstancePtr is a pointer to the XRfdc instance. BaseAddr is address of a block. RegAddr is register offset value. Mask contains bit mask value. Data contains value to be written to register. None
References XRFdc_ReadReg16, XRFdc_WriteReg16.
Referenced by XRFdc_CustomStartUp, XRFdc_DisableCoefficientsOverride, XRFdc_DynamicPLLConfig, XRFdc_IntrEnable, XRFdc_ResetNCOPhase, XRFdc_SetCalCoefficients, XRFdc_SetCalFreeze, XRFdc_SetCalibrationMode, XRFdc_SetClkDistribution, XRFdc_SetCoarseDelaySettings, XRFdc_SetDACCompMode, XRFdc_SetDACDataScaler, XRFdc_SetDACVOP, XRFdc_SetDataPathMode, XRFdc_SetDecoderMode, XRFdc_SetDither, XRFdc_SetDSA, XRFdc_SetFabClkOutDiv, XRFdc_SetFabWrVldWords, XRFdc_SetIMRPassMode, XRFdc_SetInterpolationFactor, XRFdc_SetInvSincFIR, XRFdc_SetMixerSettings, XRFdc_SetPwrMode, XRFdc_SetQMCSettings, XRFdc_SetSignalDetector, XRFdc_SetThresholdSettings, XRFdc_ThresholdStickyClear.
void XRFdc_ClrReg(XRFdc *InstancePtr, u32 BaseAddr, u32 RegAddr, u16 Mask)
Execute Read and clear.
InstancePtr is a pointer to the XRfdc instance. BaseAddr is address of a block. RegAddr is register offset value. Mask contains bit mask value. None
References XRFdc_ReadReg16, XRFdc_WriteReg16.
Referenced by XRFdc_IntrDisable.
u16 XRFdc_RDReg(XRFdc *InstancePtr, u32 BaseAddr, u32 RegAddr, u16 Mask)
Execute Read and mask with the value.
InstancePtr is a pointer to the XRfdc instance. BaseAddr is address of a block. RegAddr is register offset value. Mask contains bit mask value. None
References XRFdc_ReadReg16.
Referenced by XRFdc_DynamicPLLConfig, XRFdc_GetBlockStatus, XRFdc_GetCalCoefficients, XRFdc_GetCalFreeze, XRFdc_GetCalibrationMode, XRFdc_GetClkDistribution, XRFdc_GetClockSource, XRFdc_GetCoarseDelaySettings, XRFdc_GetConnectedIQData, XRFdc_GetCoupling, XRFdc_GetDACCompMode, XRFdc_GetDACDataScaler, XRFdc_GetDataPathMode, XRFdc_GetDecoderMode, XRFdc_GetDither, XRFdc_GetDSA, XRFdc_GetEnabledInterrupts, XRFdc_GetFabClkOutDiv, XRFdc_GetFIFOStatusInt, XRFdc_GetIMRPassMode, XRFdc_GetInterpolationFactor, XRFdc_GetInvSincFIR, XRFdc_GetLinkCoupling, XRFdc_GetMixerSettings, XRFdc_GetNyquistZone, XRFdc_GetOutputCurr, XRFdc_GetPLLConfig, XRFdc_GetPLLLockStatus, XRFdc_GetPwrMode, XRFdc_GetQMCSettings, XRFdc_GetSignalDetector, XRFdc_GetThresholdSettings, XRFdc_MultiBand, XRFdc_SetClkDistribution, XRFdc_SetDACVOP, XRFdc_SetDataPathMode, XRFdc_SetInterpolationFactor, XRFdc_SetMixerSettings, XRFdc_SetQMCSettings, XRFdc_UpdateEvent, XRFdc_WaitForState.
u32 XRFdc_IsHighSpeedADC(XRFdc *InstancePtr, u32 Tile)
Get ADC type is High Speed or Medium Speed.
InstancePtr is a pointer to the XRfdc instance. Return 1 if ADC type is a dual typeReturn 0 if quad or invalid tile.
Referenced by XRFdc_CustomStartUp, XRFdc_DisableCoefficientsOverride, XRFdc_DynamicPLLConfig, XRFdc_Get_BlockBaseAddr, XRFdc_GetBlockStatus, XRFdc_GetCalCoefficients, XRFdc_GetCalFreeze, XRFdc_GetCalibrationMode, XRFdc_GetCoarseDelaySettings, XRFdc_GetCoupling, XRFdc_GetDither, XRFdc_GetDSA, XRFdc_GetEnabledInterrupts, XRFdc_GetIntrStatus, XRFdc_GetLinkCoupling, XRFdc_GetMaxSampleRate, XRFdc_GetMinSampleRate, XRFdc_GetMixerSettings, XRFdc_GetNyquistZone, XRFdc_GetPwrMode, XRFdc_GetQMCSettings, XRFdc_GetSignalDetector, XRFdc_GetThresholdSettings, XRFdc_IntrClr, XRFdc_IntrDisable, XRFdc_IntrEnable, XRFdc_IntrHandler, XRFdc_IsADCBlockEnabled, XRFdc_IsADCDigitalPathEnabled, XRFdc_MultiBand, XRFdc_ResetNCOPhase, XRFdc_SetCalCoefficients, XRFdc_SetCalFreeze, XRFdc_SetCalibrationMode, XRFdc_SetCoarseDelaySettings, XRFdc_SetDither, XRFdc_SetDSA, XRFdc_SetMixerSettings, XRFdc_SetNyquistZone, XRFdc_SetPwrMode, XRFdc_SetQMCSettings, XRFdc_SetSignalDetector, XRFdc_SetThresholdClrMode, XRFdc_SetThresholdSettings, XRFdc_ThresholdStickyClear, XRFdc_UpdateEvent.
u32 XRFdc_Get_IPBaseAddr(XRFdc *InstancePtr)
Get IP BaseAddress.
InstancePtr is a pointer to the XRfdc instance. Return IP BaseAddress.
u32 XRFdc_Get_TileBaseAddr(XRFdc *InstancePtr, u32 Type, u32 Tile_Id)
Get Tile BaseAddress.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Return Tile BaseAddress if valid tile.Return 0U if invalid/unavailable tile.
References XRFdc_CheckTileEnabled.
u32 XRFdc_Get_BlockBaseAddr(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id)
Get Block BaseAddress.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3 in DAC/ADC-2GSPS and 0-1 in ADC-4GSPS. Return Block BaseAddress.Return 0U if invalid/unavailable block.
References XRFdc_CheckBlockEnabled, XRFdc_IsHighSpeedADC.
u32 XRFdc_GetNoOfDACBlock(XRFdc *InstancePtr, u32 Tile_Id)
Get Number of DAC Blocks enabled.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Return number of DAC blocks enabled.
u32 XRFdc_GetNoOfADCBlocks(XRFdc *InstancePtr, u32 Tile_Id)
Get Number of ADC Blocks enabled.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Return number of ADC blocks enabled.
u32 XRFdc_GetDataWidth(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id)
Get Data Width for ADC/DAC block.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Return DataWidth of ADC/DAC block.
u32 XRFdc_CheckTileEnabled(XRFdc *InstancePtr, u32 Type, u32 Tile_Id)
Checks whether ADC/DAC tile is enabled or not.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC. Tile_Id Valid values are 0-3. XRFDC_SUCCESS if tile enabled.XRFDC_FAILURE if tile not enabled.
References XRFDC_DAC_TILES_ENABLED_SHIFT, XRFdc_ReadReg, XRFDC_TILES_ENABLED_OFFSET.
Referenced by XRFdc_DynamicPLLConfig, XRFdc_Get_TileBaseAddr, XRFdc_GetClkDistribution, XRFdc_GetClockSource, XRFdc_GetFabClkOutDiv, XRFdc_GetFIFOStatusInt, XRFdc_GetMTSEnable, XRFdc_GetPLLConfig, XRFdc_SetFabClkOutDiv, XRFdc_WaitForState.
u32 XRFdc_GetMaxSampleRate(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, double *MaxSampleRatePtr)
Gets ADC/DAC tile maximum sampling rate.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC. Tile_Id Valid values are 0-3. MaxSampleRatePtr pointer for maximum sample rate. XRFDC_SUCCESS if found sampling rate.XRFDC_FAILURE if could not find sampling rate.
References XRFdc_IsHighSpeedADC.
Referenced by XRFdc_DynamicPLLConfig.
u32 XRFdc_GetMinSampleRate(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, double *MinSampleRatePtr)
Gets ADC/DAC tile minimum sampling rate.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC. Tile_Id Valid values are 0-3. MinSampleRatePtr pointer for minimum sample rate. XRFDC_SUCCESS if found sampling rate.XRFDC_FAILURE if could not find sampling rate.
References XRFdc_IsHighSpeedADC.
Referenced by XRFdc_DynamicPLLConfig.
u8 XRFdc_GetTileLayout(XRFdc *InstancePtr)
Gets whether the device is a DFE variant or not.
InstancePtr is a pointer to the XRfdc instance. XRFDC_3ADC_2DAC_TILES if DFE variant.XRFDC_4ADC_4DAC_TILES if regular Gen 1/2/3.
Referenced by XRFdc_DynamicPLLConfig, XRFdc_GetClkDistribution, XRFdc_SetClkDistribution.
double XRFdc_GetDriverVersion(void)
This API is used to get the driver version.
None Driver version number None.
XRFdc_Config* XRFdc_LookupConfig(metal_phys_addr_t BaseAddr)
u32 XRFdc_RegisterMetal(XRFdc *InstancePtr, u16 DeviceId, struct metal_device **DevicePtr)
Register/open the deviceand map RFDC to the IO region.
InstancePtr is a pointer to the XRfdc instance. DeviceId contains the ID of the device to register/map DevicePtr is a pointer to the metal device. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
References XRFdc_GetDeviceNameByDeviceId.
Referenced by RFdcMTS_Example.
u32 XRFdc_SetMixerSettings(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, XRFdc_Mixer_Settings *MixerSettingsPtr)
The API is used to update various mixer settings, fine, coarse, NCO etc.
Mixer/NCO settings passed are used to update the corresponding block level registers. Driver structure is updated with the new values. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. MixerSettingsPtr Pointer to the XRFdc_Mixer_Settings structure in which the Mixer/NCO settings are passed. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. FineMixerScale in Mixer_Settings structure can have 3 values. XRFDC_MIXER_SCALE_* represents the valid values. XRFDC_MIXER_SCALE_AUTO - If mixer mode is R2C, Mixer Scale is set to 1 and for other modes mixer scale is set to 0.7 XRFDC_MIXER_SCALE_1P0 - To set fine mixer scale to 1. XRFDC_MIXER_SCALE_0P7 - To set fine mixer scale to 0.7.
References XRFDC_ADC_DECI_CONFIG_OFFSET, XRFDC_ADC_NCO_FQWD_LOW_OFFSET, XRFDC_ADC_NCO_FQWD_MID_OFFSET, XRFDC_ADC_NCO_FQWD_UPP_OFFSET, XRFDC_ADC_NCO_PHASE_MOD_OFFSET, XRFDC_ADC_UPDATE_DYN_OFFSET, XRFdc_CheckDigitalPathEnabled, XRFdc_ClrSetReg, XRFDC_DAC_DATAPATH_OFFSET, XRFDC_DAC_INTERP_DATA_MASK, XRFDC_DAC_ITERP_DATA_OFFSET, XRFDC_DAC_UPDATE_DYN_OFFSET, XRFDC_DATAPATH_MODE_MASK, XRFDC_DEC_CFG_4GSPS_MASK, XRFDC_DEC_CFG_CHA_MASK, XRFDC_DEC_CFG_IQ_MASK, XRFDC_DEC_CFG_MASK, XRFDC_FINE_MIX_SCALE_MASK, XRFdc_GetCalibrationMode, XRFdc_GetNyquistZone, XRFdc_IsHighSpeedADC, XRFDC_MXR_MODE_OFFSET, XRFDC_NCO_FQWD_MID_MASK, XRFDC_NCO_FQWD_MID_SHIFT, XRFDC_NCO_FQWD_UPP_MASK, XRFDC_NCO_FQWD_UPP_SHIFT, XRFDC_NCO_PHASE_LOW_OFFSET, XRFDC_NCO_PHASE_MOD_EVEN, XRFDC_NCO_PHASE_MODE_ODD, XRFDC_NCO_PHASE_UPP_MASK, XRFDC_NCO_PHASE_UPP_OFFSET, XRFDC_NCO_PHASE_UPP_SHIFT, XRFDC_NCO_UPDT_MODE_MASK, XRFDC_NCO_UPDT_OFFSET, XRFdc_RDReg, XRFdc_ReadReg16, XRFdc_ResetInternalFIFOWidth, XRFDC_UPDT_EVNT_MASK, XRFDC_UPDT_EVNT_NCO_MASK, XRFdc_WriteReg16.
Referenced by XRFdc_SetCalibrationMode, XRFdc_SetDataPathMode.
u32 XRFdc_GetMixerSettings(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, XRFdc_Mixer_Settings *MixerSettingsPtr)
The API returns back Mixer/NCO settings to the caller.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. MixerSettingsPtr Pointer to the XRFdc_Mixer_Settings structure in which the Mixer/NCO settings are passed. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. FineMixerScale in Mixer_Settings structure can have 3 values. XRFDC_MIXER_SCALE_* represents the valid values. XRFDC_MIXER_SCALE_AUTO - If mixer mode is R2C, Mixer Scale is set to 1 and for other modes mixer scale is set to 0.7 XRFDC_MIXER_SCALE_1P0 - To set fine mixer scale to 1. XRFDC_MIXER_SCALE_0P7 - To set fine mixer scale to 0.7.
References XRFDC_ADC_MXR_CFG0_OFFSET, XRFDC_ADC_MXR_CFG1_OFFSET, XRFDC_ADC_NCO_FQWD_LOW_OFFSET, XRFDC_ADC_NCO_FQWD_MID_OFFSET, XRFDC_ADC_NCO_FQWD_UPP_OFFSET, XRFdc_CheckDigitalPathEnabled, XRFDC_DAC_DATAPATH_OFFSET, XRFDC_DATAPATH_MODE_MASK, XRFDC_EN_I_IQ_MASK, XRFDC_EN_Q_IQ_MASK, XRFDC_FINE_MIX_SCALE_MASK, XRFdc_GetCalibrationMode, XRFdc_GetNyquistZone, XRFdc_IsHighSpeedADC, XRFDC_MIX_CFG0_MASK, XRFDC_MIX_CFG1_MASK, XRFDC_MXR_MODE_OFFSET, XRFDC_NCO_FQWD_MASK, XRFDC_NCO_FQWD_MID_SHIFT, XRFDC_NCO_FQWD_UPP_SHIFT, XRFDC_NCO_PHASE_LOW_OFFSET, XRFDC_NCO_PHASE_MASK, XRFDC_NCO_PHASE_UPP_OFFSET, XRFDC_NCO_PHASE_UPP_SHIFT, XRFDC_NCO_UPDT_MODE_MASK, XRFDC_NCO_UPDT_OFFSET, XRFdc_RDReg, XRFdc_ReadReg16.
Referenced by XRFdc_SetCalibrationMode, XRFdc_SetDataPathMode.
u32 XRFdc_SetQMCSettings(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, XRFdc_QMC_Settings *QMCSettingsPtr)
This API is used to update various QMC settings, eg gain, phase, offset etc.
QMC settings passed are used to update the corresponding block level registers. Driver structure is updated with the new values. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. QMCSettingsPtr is Pointer to the XRFdc_QMC_Settings structure in which the QMC settings are passed. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
References XRFDC_ADC_SWITCH_MATRX_OFFSET, XRFDC_ADC_UPDATE_DYN_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFDC_DAC_MB_CFG_OFFSET, XRFDC_DAC_UPDATE_DYN_OFFSET, XRFdc_GetConnectedIData, XRFdc_GetConnectedQData, XRFdc_IsHighSpeedADC, XRFDC_QMC_CFG_EN_GAIN_MASK, XRFDC_QMC_CFG_EN_PHASE_MASK, XRFDC_QMC_CFG_OFFSET, XRFDC_QMC_CFG_PHASE_SHIFT, XRFDC_QMC_GAIN_CRCTN_MASK, XRFDC_QMC_GAIN_OFFSET, XRFDC_QMC_OFF_OFFSET, XRFDC_QMC_OFFST_CRCTN_MASK, XRFDC_QMC_PHASE_CRCTN_MASK, XRFDC_QMC_PHASE_OFFSET, XRFDC_QMC_UPDT_MODE_MASK, XRFDC_QMC_UPDT_OFFSET, XRFdc_RDReg, XRFDC_SEL_CB_TO_QMC_MASK, XRFDC_UPDT_EVNT_MASK, XRFDC_UPDT_EVNT_QMC_MASK.
u32 XRFdc_GetQMCSettings(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, XRFdc_QMC_Settings *QMCSettingsPtr)
QMC settings are returned back to the caller through this API.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. QMCSettingsPtr Pointer to the XRFdc_QMC_Settings structure in which the QMC settings are passed. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
References XRFdc_CheckBlockEnabled, XRFDC_DAC_MB_CFG_OFFSET, XRFdc_IsHighSpeedADC, XRFDC_QMC_CFG_EN_GAIN_MASK, XRFDC_QMC_CFG_EN_PHASE_MASK, XRFDC_QMC_CFG_OFFSET, XRFDC_QMC_CFG_PHASE_SHIFT, XRFDC_QMC_GAIN_CRCTN_MASK, XRFDC_QMC_GAIN_OFFSET, XRFDC_QMC_OFF_OFFSET, XRFDC_QMC_OFFST_CRCTN_MASK, XRFDC_QMC_OFFST_CRCTN_SIGN_MASK, XRFDC_QMC_PHASE_CRCTN_MASK, XRFDC_QMC_PHASE_CRCTN_SIGN_MASK, XRFDC_QMC_PHASE_OFFSET, XRFDC_QMC_UPDT_MODE_MASK, XRFDC_QMC_UPDT_OFFSET, XRFdc_RDReg.
u32 XRFdc_GetCoarseDelaySettings(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, XRFdc_CoarseDelay_Settings *CoarseDelaySettingsPtr)
Coarse delay settings are returned back to the caller.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. CoarseDelaySettingsPtr Pointer to the XRFdc_CoarseDelay_Settings structure in which the Coarse Delay settings are passed. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
References XRFDC_ADC_CRSE_DLY_CFG_OFFSET, XRFDC_ADC_CRSE_DLY_UPDT_OFFSET, XRFdc_CheckBlockEnabled, XRFDC_DAC_CRSE_DLY_CFG_OFFSET, XRFDC_DAC_CRSE_DLY_UPDT_OFFSET, XRFdc_IsHighSpeedADC, XRFDC_QMC_UPDT_MODE_MASK, XRFdc_RDReg, XRFdc_ReadReg16.
u32 XRFdc_SetCoarseDelaySettings(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, XRFdc_CoarseDelay_Settings *CoarseDelaySettingsPtr)
Coarse delay settings passed are used to update the corresponding block level registers.
Driver structure is updated with the new values. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. CoarseDelaySettingsPtr is Pointer to the XRFdc_CoarseDelay_Settings structure in which the CoarseDelay settings are passed. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
References XRFDC_ADC_CRSE_DLY_CFG_OFFSET, XRFDC_ADC_CRSE_DLY_UPDT_OFFSET, XRFDC_ADC_UPDATE_DYN_OFFSET, XRFDC_ADC_UPDT_CRSE_DLY_MASK, XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFDC_CRSE_DLY_CFG_MASK, XRFDC_CRSE_DLY_CFG_MASK_EXT, XRFDC_DAC_CRSE_DLY_CFG_OFFSET, XRFDC_DAC_CRSE_DLY_UPDT_OFFSET, XRFDC_DAC_UPDATE_DYN_OFFSET, XRFDC_DAC_UPDT_CRSE_DLY_MASK, XRFdc_IsHighSpeedADC, XRFDC_QMC_UPDT_MODE_MASK, XRFDC_UPDT_EVNT_MASK.
u32 XRFdc_GetInterpolationFactor(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *InterpolationFactorPtr)
Interpolation factor are returned back to the caller.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. InterpolationFactorPtr Pointer to return the interpolation factor for DAC blocks. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for DAC blocks
References XRFdc_CheckDigitalPathEnabled, XRFDC_DAC_INTERP_CTRL_OFFSET, XRFDC_INTERP_MODE_I_MASK, XRFDC_INTERP_MODE_I_MASK_EXT, XRFdc_RDReg.
Referenced by RFdcMTS_Example.
u32 XRFdc_GetDecimationFactor(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *DecimationFactorPtr)
Decimation factor are returned back to the caller.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. DecimationFactorPtr Pointer to return the Decimation factor for DAC blocks. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
Referenced by RFdcMTS_Example.
u32 XRFdc_GetDecimationFactorObs(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *DecimationFactorPtr)
Decimation factor are returned back to the caller for the observation FIFO.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. DecimationFactorPtr Pointer to return the Decimation factor for DAC blocks. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
u32 XRFdc_GetFabWrVldWords(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 *FabricWrVldWordsPtr)
This API returns the number of fabric write valid words requested for the block.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. FabricWrVldWordsPtr Pointer to return the fabric data rate for DAC block XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. ADC/DAC blocks
u32 XRFdc_GetFabWrVldWordsObs(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 *FabricWrVldWordsPtr)
This API returns the number of fabric write valid words requested for the block.
This is for the observation FIFO. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. FabricWrVldWordsPtr Pointer to return the fabric data rate for DAC block XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. ADC blocks only
u32 XRFdc_GetFabRdVldWords(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 *FabricRdVldWordsPtr)
This API returns the number of fabric read valid words requested for the block.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. FabricRdVldWordsPtr Pointer to return the fabric data rate for ADC/DAC block XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. ADC/DAC blocks
u32 XRFdc_GetFabRdVldWordsObs(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 *FabricRdVldWordsPtr)
This function returns the number of fabric read valid words requested for the block.
This is for the observation FIFO. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. FabricRdVldWordsPtr Pointer to return the fabric data rate for ADC/DAC block XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. ADC blocks only
u32 XRFdc_SetFabRdVldWords(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 FabricRdVldWords)
Fabric data rate for the requested ADC block is set by writing to the corresponding register.
The function writes the number of valid read words for the requested ADC block. InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC block number inside the tile. Valid values are 0-3. FabricRdVldWords is Read fabric rate to be set for ADC block. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
u32 XRFdc_SetFabRdVldWordsObs(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 FabricRdVldWords)
Fabric data rate for the requested ADC block is set by writing to the corresponding register.
The function writes the number of valid read words for the requested ADC block. This is for the observation FIFO. InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC block number inside the tile. Valid values are 0-3. FabricRdVldWords is Read fabric rate to be set for ADC block. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
u32 XRFdc_SetFabWrVldWords(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 FabricWrVldWords)
Fabric data rate for the requested DAC block is set by writing to the corresponding register.
The function writes the number of valid write words for the requested DAC block. InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. FabricWrVldWords is write fabric rate to be set for DAC block. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for DAC blocks
References XRFdc_CheckDigitalPathEnabled, XRFdc_ClrSetReg, XRFDC_DAC_FAB_RATE_WR_MASK, XRFDC_DAC_FABRIC_RATE_OFFSET.
u32 XRFdc_GetThresholdSettings(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, XRFdc_Threshold_Settings *ThresholdSettingsPtr)
Threshold settings are read from the corresponding registers and are passed back to the caller.
There can be two threshold settings: threshold0 and threshold1. Both of them are independent of each other. The function returns the requested threshold (which can be threshold0, threshold1, or both. InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. ThresholdSettingsPtr Pointer through which the register settings for thresholds are passed back.. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_ADC_TRSHD0_AVG_LO_OFFSET, XRFDC_ADC_TRSHD0_AVG_UP_OFFSET, XRFDC_ADC_TRSHD0_CFG_OFFSET, XRFDC_ADC_TRSHD0_OVER_OFFSET, XRFDC_ADC_TRSHD0_UNDER_OFFSET, XRFDC_ADC_TRSHD1_AVG_LO_OFFSET, XRFDC_ADC_TRSHD1_AVG_UP_OFFSET, XRFDC_ADC_TRSHD1_CFG_OFFSET, XRFDC_ADC_TRSHD1_OVER_OFFSET, XRFDC_ADC_TRSHD1_UNDER_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_IsHighSpeedADC, XRFdc_RDReg, XRFdc_ReadReg16, XRFDC_TRSHD0_AVG_UPP_SHIFT, XRFDC_TRSHD0_EN_MOD_MASK, XRFDC_TRSHD0_OVER_MASK, XRFDC_TRSHD0_UNDER_MASK, XRFDC_TRSHD1_AVG_UPP_SHIFT, XRFDC_TRSHD1_EN_MOD_MASK, XRFDC_TRSHD1_OVER_MASK, XRFDC_TRSHD1_UNDER_MASK.
u32 XRFdc_SetThresholdSettings(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, XRFdc_Threshold_Settings *ThresholdSettingsPtr)
Threshold settings are updated into the relevant registers.
Driver structure is updated with the new values. There can be two threshold settings: threshold0 and threshold1. Both of them are independent of each other. The function returns the requested threshold (which can be threshold0, threshold1, or both. InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. ThresholdSettingsPtr Pointer through which the register settings for thresholds are passed to the API. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only ADC blocks
References XRFDC_ADC_TRSHD0_AVG_LO_OFFSET, XRFDC_ADC_TRSHD0_AVG_UP_OFFSET, XRFDC_ADC_TRSHD0_CFG_OFFSET, XRFDC_ADC_TRSHD0_OVER_OFFSET, XRFDC_ADC_TRSHD0_UNDER_OFFSET, XRFDC_ADC_TRSHD1_AVG_LO_OFFSET, XRFDC_ADC_TRSHD1_AVG_UP_OFFSET, XRFDC_ADC_TRSHD1_CFG_OFFSET, XRFDC_ADC_TRSHD1_OVER_OFFSET, XRFDC_ADC_TRSHD1_UNDER_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFdc_IsHighSpeedADC, XRFDC_TRSHD0_AVG_UPP_SHIFT, XRFDC_TRSHD0_EN_MOD_MASK, XRFDC_TRSHD0_OVER_MASK, XRFDC_TRSHD0_UNDER_MASK, XRFDC_TRSHD1_AVG_UPP_SHIFT, XRFDC_TRSHD1_EN_MOD_MASK, XRFDC_TRSHD1_OVER_MASK, XRFDC_TRSHD1_UNDER_MASK, XRFdc_WriteReg16.
u32 XRFdc_SetDecoderMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 DecoderMode)
Decoder mode is updated into the relevant registers.
Driver structure is updated with the new values. InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is DAC block number inside the tile. Valid values are 0-3. DecoderMode Valid values are 1 (Maximum SNR, for non- randomized decoder), 2 (Maximum Linearity, for randomized decoder) XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only DAC blocks
References XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFDC_DAC_DECODER_CLK_OFFSET, XRFDC_DAC_DECODER_CTRL_OFFSET, XRFDC_DEC_CTRL_MODE_MASK.
u32 XRFdc_UpdateEvent(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 Event)
This function will trigger the update event for an event.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Event is for which dynamic update event will trigger. XRFDC_EVENT_* defines the different events. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Common API for ADC/DAC blocks
References XRFDC_ADC_CRSE_DLY_UPDT_OFFSET, XRFDC_ADC_UPDATE_DYN_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_CheckDigitalPathEnabled, XRFDC_DAC_CRSE_DLY_UPDT_OFFSET, XRFDC_DAC_UPDATE_DYN_OFFSET, XRFDC_HSCOM_UPDT_DYN_OFFSET, XRFdc_IsHighSpeedADC, XRFDC_NCO_UPDT_MODE_MASK, XRFDC_NCO_UPDT_OFFSET, XRFDC_QMC_UPDT_MODE_MASK, XRFDC_QMC_UPDT_OFFSET, XRFdc_RDReg, XRFdc_WriteReg16.
u32 XRFdc_GetDecoderMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *DecoderModePtr)
Decoder mode is read and returned back.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is DAC block number inside the tile. Valid values are 0-3. DecoderModePtr Valid values are 1 (Maximum SNR, for non-randomized decoder), 2 (Maximum Linearity, for randomized decoder) XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for DAC blocks
References XRFdc_CheckBlockEnabled, XRFDC_DAC_DECODER_CTRL_OFFSET, XRFDC_DEC_CTRL_MODE_MASK, XRFdc_RDReg.
u32 XRFdc_ResetNCOPhase(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id)
Resets the NCO phase of the current block phase accumulator.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
References XRFdc_CheckDigitalPathEnabled, XRFdc_ClrSetReg, XRFdc_IsHighSpeedADC, XRFDC_NCO_PHASE_RST_MASK, XRFDC_NCO_RST_OFFSET.
u32 XRFdc_MultiBand(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u8 DigitalDataPathMask, u32 MixerInOutDataType, u32 DataConverterMask)
User-level API to setup multiband configuration.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. DigitalDataPathMask is the DataPath mask. First 4 bits represent 4 data paths, 1 means enabled and 0 means disabled. MixerInOutDataType is mixer data type, valid values are XRFDC_MB_DATATYPE_* DataConverterMask is block enabled mask (input/output driving blocks). 1 means enabled and 0 means disabled. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Common API for ADC/DAC blocks
References XRFdc_CheckBlockEnabled, XRFdc_CheckDigitalPathEnabled, XRFDC_DAC_DATAPATH_OFFSET, XRFDC_DATAPATH_MODE_MASK, XRFdc_IsHighSpeedADC, XRFdc_RDReg.
int XRFdc_GetConnectedIData(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id)
Get Data Converter connected for digital data path I.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is Digital Data Path number. Return Data converter Id.
References XRFdc_GetConnectedIQData.
Referenced by XRFdc_SetQMCSettings.
int XRFdc_GetConnectedQData(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id)
Get Data Converter connected for digital data path Q.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is Digital Data Path number. Return Data converter Id.
References XRFdc_GetConnectedIQData.
Referenced by XRFdc_SetQMCSettings.
u32 XRFdc_GetConnectedIQData(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, int *ConnectedIData, int *ConnectedQData)
Get Data Converter connected for digital data paths I & Q.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is Digital Data Path number. ConnectedData is Digital Data Path number. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs.
References XRFDC_ADC_SWITCH_MATRX_OFFSET, XRFdc_CheckDigitalPathEnabled, XRFDC_DAC_MB_CFG_OFFSET, XRFDC_MB_CONFIG_OFFSET, XRFdc_RDReg, XRFdc_ReadReg, XRFDC_SEL_CB_TO_MIX1_MASK.
Referenced by XRFdc_GetConnectedIData, XRFdc_GetConnectedQData.
u32 XRFdc_IntrHandler(u32 Vector, void *XRFdcPtr)
This function is the interrupt handler for the driver.
It must be connected to an interrupt system by the application such that it can be called when an interrupt occurs. Vector is interrupt vector number. Libmetal status handler expects two parameters in the handler prototype, hence kept this parameter. This is not used inside the interrupt handler API. XRFdcPtr contains a pointer to the driver instance None.Vector param is not useful inside the interrupt handler, hence typecast with void to remove compilation warning.
References XRFDC_COMMON_INTR_STS, XRFDC_EN_INTR_ADC_TILE0_MASK, XRFDC_EN_INTR_ADC_TILE1_MASK, XRFDC_EN_INTR_ADC_TILE2_MASK, XRFDC_EN_INTR_ADC_TILE3_MASK, XRFDC_EN_INTR_DAC_TILE0_MASK, XRFDC_EN_INTR_DAC_TILE1_MASK, XRFDC_EN_INTR_DAC_TILE2_MASK, XRFDC_EN_INTR_DAC_TILE3_MASK, XRFDC_EN_INTR_SLICE0_MASK, XRFDC_EN_INTR_SLICE1_MASK, XRFDC_EN_INTR_SLICE2_MASK, XRFDC_EN_INTR_SLICE3_MASK, XRFdc_GetIntrStatus, XRFDC_INTR_COMMON_MASK, XRFDC_INTR_STS, XRFdc_IntrClr, XRFdc_IsHighSpeedADC, XRFdc_ReadReg16.
u32 XRFdc_IntrClr(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 IntrMask)
This function clear the interrupts.
InstancePtr is a pointer to the XRFdc instance Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3, and -1. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. IntrMask contains the interrupts to be cleared. XRFDC_SUCCESS if successful.XRFDC_FAILURE if block not available. None.
References XRFDC_ADC_DEC_ISR_OFFSET, XRFDC_ADC_FABRIC_ISR_OBS_OFFSET, XRFDC_ADC_FABRIC_ISR_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_CheckDigitalPathEnabled, XRFDC_DAC_FABRIC_ISR_OFFSET, XRFDC_DATPATH_ISR_OFFSET, XRFdc_IsHighSpeedADC, XRFdc_WriteReg, XRFdc_WriteReg16.
Referenced by XRFdc_IntrHandler.
u32 XRFdc_GetIntrStatus(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 *IntrStsPtr)
This function returns the interrupt status read from Interrupt Status Register(ISR).
InstancePtr is a pointer to the XRFdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3, and -1. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. IntrStsPtr is pointer to a32-bit value representing the contents of the Interrupt Status Registers (FIFO interface, Decoder interface, Data Path Interface). XRFDC_SUCCESS if successful.XRFDC_FAILURE if block not available. None.
References XRFDC_ADC_DAT_PATH_ISR_MASK, XRFDC_ADC_DEC_ISR_OFFSET, XRFDC_ADC_FABRIC_ISR_OBS_OFFSET, XRFDC_ADC_FABRIC_ISR_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_CheckDigitalPathEnabled, XRFDC_DAC_DAT_PATH_ISR_MASK, XRFDC_DAC_FABRIC_ISR_OFFSET, XRFDC_DAC_FIFO_IMR_SUPP_MASK, XRFDC_DATPATH_ISR_OFFSET, XRFDC_DEC_ISR_SUBADC_MASK, XRFDC_INTR_CMODE_OVR_MASK, XRFDC_INTR_CMODE_UNDR_MASK, XRFDC_INTR_COMMON_MASK, XRFDC_INTR_DAT_OVR_MASK, XRFDC_INTR_FIFO_OVR_MASK, XRFDC_INTR_OVR_RANGE_MASK, XRFDC_INTR_OVR_VOLTAGE_MASK, XRFDC_INTR_STS, XRFdc_IsHighSpeedADC, XRFdc_ReadReg, XRFdc_ReadReg16.
Referenced by XRFdc_IntrHandler.
u32 XRFdc_IntrDisable(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 IntrMask)
This function clears the interrupt mask.
InstancePtr is a pointer to the XRFdc instance Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3, and -1. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. IntrMask contains the interrupts to be disabled. '1' disables an interrupt, and '0' remains no change. XRFDC_SUCCESS if successful.XRFDC_FAILURE if block not available. None.
References XRFDC_ADC_DEC_IMR_OFFSET, XRFDC_ADC_FABRIC_IMR_OBS_OFFSET, XRFDC_ADC_FABRIC_IMR_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_CheckDigitalPathEnabled, XRFdc_ClrReg, XRFDC_DAC_FABRIC_IMR_OFFSET, XRFDC_DATPATH_IMR_OFFSET, XRFDC_INTR_ENABLE, XRFdc_IsHighSpeedADC, XRFdc_ReadReg, XRFdc_WriteReg.
Referenced by RFdcHandler.
u32 XRFdc_IntrEnable(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 IntrMask)
This function sets the interrupt mask.
InstancePtr is a pointer to the XRFdc instance Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3, and -1. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. IntrMask contains the interrupts to be enabled. '1' enables an interrupt, and '0' disables. XRFDC_SUCCESS if successful.XRFDC_FAILURE if block not available. None.
References XRFDC_ADC_DAT_IMR_MASK, XRFDC_ADC_DEC_IMR_OFFSET, XRFDC_ADC_FABRIC_IMR_OBS_OFFSET, XRFDC_ADC_FABRIC_IMR_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_CheckDigitalPathEnabled, XRFdc_ClrSetReg, XRFDC_COMMON_INTR_ENABLE, XRFDC_DAC_DAT_IMR_MASK, XRFDC_DAC_FABRIC_IMR_OFFSET, XRFDC_DAC_FIFO_IMR_MASK, XRFDC_DATPATH_IMR_OFFSET, XRFDC_INTR_ENABLE, XRFdc_IsHighSpeedADC, XRFdc_ReadReg, XRFdc_ReadReg16, XRFdc_WriteReg, XRFdc_WriteReg16.
u32 XRFdc_GetEnabledInterrupts(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 *IntrMask)
This function gets a mask of enabled interrupts.
InstancePtr is a pointer to the XRFdc instance Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3, and -1. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. IntrMask is a pointer to the mask of enabled interrupts. '1' denotes an enabled interrupt, and '0' denotes a disabled interrupt. XRFDC_SUCCESS if successful.XRFDC_FAILURE if block not available. None.
References XRFDC_ADC_DAT_IMR_MASK, XRFDC_ADC_DEC_IMR_OFFSET, XRFDC_ADC_FABRIC_IMR_OBS_OFFSET, XRFDC_ADC_FABRIC_IMR_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_CheckDigitalPathEnabled, XRFDC_COMMON_INTR_ENABLE, XRFDC_DAC_DAT_IMR_MASK, XRFDC_DAC_FABRIC_IMR_OFFSET, XRFDC_DAC_FIFO_IMR_SUPP_MASK, XRFDC_DATPATH_IMR_OFFSET, XRFDC_INTR_ENABLE, XRFdc_IsHighSpeedADC, XRFdc_RDReg, XRFdc_ReadReg, XRFdc_ReadReg16.
u32 XRFdc_SetThresholdClrMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 ThresholdToUpdate, u32 ClrMode)
This API sets the threshold clear mode.
The clear mode can be through explicit DRP access (manual) or auto clear (QMC gain update event). InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADCC block number inside the tile. Valid values are 0-3. ThresholdToUpdate Select which Threshold (Threshold0 or Threshold1 or both) to update. ClrMode can be DRP access (manual) or auto clear (QMC gain update event). XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only ADC blocks
References XRFDC_ADC_TRSHD0_CFG_OFFSET, XRFDC_ADC_TRSHD1_CFG_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_IsHighSpeedADC, XRFdc_ReadReg16, XRFDC_TRSHD0_CLR_MOD_MASK, XRFDC_TRSHD1_CLR_MOD_MASK, XRFdc_WriteReg16.
u32 XRFdc_ThresholdStickyClear(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 ThresholdToUpdate)
This API is to clear the Sticky bit in threshold config registers.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. ThresholdToUpdate Select which Threshold (Threshold0 or Threshold1 or both) to update. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only ADC blocks
References XRFDC_ADC_TRSHD0_CFG_OFFSET, XRFDC_ADC_TRSHD1_CFG_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFdc_IsHighSpeedADC, XRFDC_TRSHD0_STIKY_CLR_MASK, XRFDC_TRSHD1_STIKY_CLR_MASK.
void XRFdc_SetStatusHandler(XRFdc *InstancePtr, void *CallBackRef, XRFdc_StatusHandler FunctionPtr)
This function sets the status callback function, the status handler, which the driver calls when it encounters conditions that should be reported to the higher layer software.
The handler executes in an interrupt context, so the amount of processing should be minimized InstancePtr is a pointer to the XRFdc instance. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. FunctionPtr is the pointer to the callback function. None.The handler is called within interrupt context, so it should finish its work quickly.
u32 XRFdc_SetupFIFO(XRFdc *InstancePtr, u32 Type, int Tile_Id, u8 Enable)
Enable and Disable the ADC/DAC FIFO.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Enable valid values are 1 (FIFO enable) and 0 (FIFO Disable) XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Common API for ADC/DAC blocks
u32 XRFdc_SetupFIFOObs(XRFdc *InstancePtr, u32 Type, int Tile_Id, u8 Enable)
Enable and Disable the ADC/DAC FIFO.
For ADCs this is for the observtion FIFO. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Enable valid values are 1 (FIFO enable) and 0 (FIFO Disable) XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. ADC blocks only
u32 XRFdc_SetupFIFOBoth(XRFdc *InstancePtr, u32 Type, int Tile_Id, u8 Enable)
Enable and Disable the ADC/DAC FIFO.
Thisis for the actual and observtion FIFO. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Enable valid values are 1 (FIFO enable) and 0 (FIFO Disable) XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. ADC blocks only
u32 XRFdc_GetFIFOStatus(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u8 *EnablePtr)
Current status of ADC/DAC FIFO.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. EnablePtr valid values are 1 (FIFO enable) and 0 (FIFO Disable) XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Common API for ADC/DAC blocks
References XRFdc_GetFIFOStatusInt.
u32 XRFdc_GetFIFOStatusObs(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u8 *EnablePtr)
Current status of ADC/DAC FIFO.
This is for the observation FIFO. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. EnablePtr valid values are 1 (FIFO enable) and 0 (FIFO Disable) XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. ADC blocks only
References XRFdc_GetFIFOStatusInt.
u32 XRFdc_SetNyquistZone(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 NyquistZone)
Set the Nyquist zone.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. NyquistZone valid values are 1 (Odd),2 (Even). XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Common API for ADC/DAC blocks
References XRFDC_ADC_TI_TISK_CRL0_OFFSET, XRFdc_CheckBlockEnabled, XRFDC_DAC_MC_CFG0_OFFSET, XRFdc_GetCalibrationMode, XRFdc_IsHighSpeedADC, XRFDC_MC_CFG0_MIX_MODE_MASK, XRFdc_ReadReg16, XRFDC_TI_TISK_ZONE_MASK, XRFdc_WriteReg16.
Referenced by XRFdc_SetCalibrationMode.
u32 XRFdc_GetNyquistZone(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 *NyquistZonePtr)
Get the Nyquist zone.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. NyquistZonePtr Pointer to return the Nyquist zone. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Common API for ADC/DAC blocks
References XRFDC_ADC_TI_TISK_CRL0_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_CheckDigitalPathEnabled, XRFDC_DAC_MC_CFG0_OFFSET, XRFdc_GetCalibrationMode, XRFdc_IsHighSpeedADC, XRFDC_MC_CFG0_MIX_MODE_MASK, XRFDC_MC_CFG0_MIX_MODE_SHIFT, XRFdc_RDReg, XRFDC_TI_TISK_ZONE_MASK, XRFDC_TISK_ZONE_SHIFT.
Referenced by XRFdc_GetMixerSettings, XRFdc_SetCalibrationMode, XRFdc_SetInvSincFIR, XRFdc_SetMixerSettings.
u32 XRFdc_GetOutputCurr(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *OutputCurrPtr)
Get Output Current for DAC block.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. OutputCurrPtr pointer to return the output current. Return Output Current for DAC block
References XRFDC_ADC_DAC_MC_CFG2_OFFSET, XRFdc_CheckBlockEnabled, XRFDC_DAC_MC_CFG3_OFFSET, XRFdc_RDReg.
u32 XRFdc_SetDecimationFactor(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 DecimationFactor)
This API is to set the decimation factor and also update the FIFO write words w.r.t to decimation factor.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. DecimationFactor to be set for DAC block. XRFDC_INTERP_DECIM_* defines the valid values. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only ADC blocks
u32 XRFdc_SetDecimationFactorObs(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 DecimationFactor)
This API is to set the decimation factor and also update the FIFO write words w.r.t to decimation factor for the observation FIFO.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. DecimationFactor to be set for DAC block. XRFDC_INTERP_DECIM_* defines the valid values. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only ADC blocks
u32 XRFdc_SetInterpolationFactor(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 InterpolationFactor)
This API is to set the interpolation factor and also update the FIFO read words w.r.t to interpolation factor.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. InterpolationFactor to be set for DAC block. XRFDC_INTERP_DECIM_* defines the valid values. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only DAC blocks
References XRFdc_CheckDigitalPathEnabled, XRFdc_ClrSetReg, XRFDC_DAC_DATAPATH_OFFSET, XRFDC_DAC_FIFO_DELAY_MASK, XRFDC_DAC_FIFO_START_OFFSET, XRFDC_DAC_INTERP_CTRL_OFFSET, XRFDC_DAC_ITERP_DATA_OFFSET, XRFDC_DATAPATH_MODE_MASK, XRFDC_INTERP_MODE_MASK, XRFDC_INTERP_MODE_MASK_EXT, XRFDC_INTERP_MODE_Q_SHIFT, XRFDC_INTERP_MODE_Q_SHIFT_EXT, XRFdc_RDReg, XRFdc_ReadReg16.
u32 XRFdc_SetFabClkOutDiv(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u16 FabClkDiv)
This API is to set the divider for clock fabric out.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. FabClkDiv to be set for a tile. XRFDC_FAB_CLK_* defines the valid divider values. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. ADC and DAC Tiles
References XRFdc_CheckTileEnabled, XRFdc_ClrSetReg, XRFDC_FAB_CLK_DIV_MASK, XRFDC_HSCOM_CLK_DIV_OFFSET.
u32 XRFdc_SetCalibrationMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u8 CalibrationMode)
This API is to set the Calibration mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. CalibrationMode valid values are 0(Gen 3 only), 1 and 2. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_ADC_TI_DCB_CRL0_OFFSET, XRFDC_ADC_TI_TISK_CRL0_OFFSET, XRFDC_ADC_TI_TISK_CRL5_OFFSET, XRFDC_CAL_MODES_MASK, XRFDC_CAL_TSCB_TUNE_MASK, XRFdc_CheckBlockEnabled, XRFdc_CheckDigitalPathEnabled, XRFdc_ClrSetReg, XRFdc_GetMixerSettings, XRFdc_GetNyquistZone, XRFdc_IsHighSpeedADC, XRFdc_ReadReg16, XRFdc_SetMixerSettings, XRFdc_SetNyquistZone, XRFDC_TI_DCB_MODE_MASK, XRFdc_WriteReg16.
u32 XRFdc_GetCalibrationMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u8 *CalibrationModePtr)
This API is to get the Calibration mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. CalibrationModePtr pointer to get the calibration mode. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_ADC_TI_DCB_CRL0_OFFSET, XRFDC_ADC_TI_TISK_CRL5_OFFSET, XRFDC_CAL_MODES_MASK, XRFdc_CheckBlockEnabled, XRFdc_CheckDigitalPathEnabled, XRFdc_IsHighSpeedADC, XRFdc_RDReg, XRFDC_TI_DCB_MODE_MASK.
Referenced by XRFdc_GetMixerSettings, XRFdc_GetNyquistZone, XRFdc_SetMixerSettings, XRFdc_SetNyquistZone.
u32 XRFdc_GetClockSource(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 *ClockSourcePtr)
This function gets Clock source.
InstancePtr is a pointer to the XRfdc instance. Type indicates ADC/DAC. Tile_Id indicates Tile number (0-3). ClockSourcePtr Pointer to return the clock source XRFDC_SUCCESS if successful.XRFDC_FAILURE if tile not enabled. None.
References XRFdc_CheckTileEnabled, XRFDC_CLK_NETWORK_CTRL1, XRFDC_CLK_NETWORK_CTRL1_USE_PLL_MASK, XRFDC_PLL_DIVIDER0, XRFdc_RDReg, XRFdc_ReadReg16.
Referenced by XRFdc_DynamicPLLConfig, XRFdc_GetPLLConfig, XRFdc_GetPLLLockStatus.
u32 XRFdc_GetPLLLockStatus(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 *LockStatusPtr)
This function gets PLL lock status.
InstancePtr is a pointer to the XRfdc instance. Type indicates ADC/DAC. Tile_Id indicates Tile number (0-3). LockStatusPtr Pointer to return the PLL lock status XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
References XRFdc_GetClockSource, XRFDC_PLL_LOCKED_MASK, XRFdc_RDReg, XRFDC_STATUS_OFFSET.
u32 XRFdc_GetPLLConfig(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, XRFdc_PLL_Settings *PLLSettings)
This API is used to get the PLL Configurations.
InstancePtr is a pointer to the XRfdc instance. Type represents ADC or DAC. Tile_Id Valid values are 0-3. PLLSettings pointer to the XRFdc_PLL_Settings structure to get the PLL configurations None.
References XRFdc_CheckTileEnabled, XRFdc_GetClockSource, XRFDC_PLL_DIVIDER0, XRFDC_PLL_FPDIV, XRFDC_PLL_FREQ, XRFDC_PLL_FS, XRFDC_PLL_REFDIV, XRFdc_RDReg, XRFdc_ReadReg, XRFdc_ReadReg16, XRFDC_REFCLK_DIV_2_MASK, XRFDC_REFCLK_DIV_3_MASK, XRFDC_REFCLK_DIV_4_MASK.
Referenced by XRFdc_GetClkDistribution.
u32 XRFdc_DynamicPLLConfig(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u8 Source, double RefClkFreq, double SamplingRate)
This function used for dynamically switch between internal PLL and external clcok source and configuring the internal PLL.
InstancePtr is a pointer to the XRfdc instance. Type indicates ADC/DAC Tile_Id indicates Tile number (0-3) Source Clock source internal PLL or external clock source RefClkFreq Reference Clock Frequency in MHz(102.40625MHz - 1.2GHz) SamplingRate Sampling Rate in MHz(0.1- 6.554GHz for DAC and 0.5/1.0 - 2.058/4.116GHz for ADC based on the device package). XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. This API enables automatic selection of the VCO which will work in IP version 2.0.1 and above. Using older version of IP this API is not likely to work.
References XRFDC_ADC_DAC_MC_CFG0_OFFSET, XRFDC_CAL_DIV_BYP_MASK, XRFDC_CAL_DIV_BYP_OFFSET, XRFDC_CAL_DLY_OFFSET, XRFDC_CAL_TMR_MULT_OFFSET, XRFdc_CheckTileEnabled, XRFDC_CLK_NETWORK_CTRL1, XRFDC_CLK_NETWORK_CTRL1_REGS_MASK, XRFDC_CLK_NETWORK_CTRL1_USE_PLL_MASK, XRFdc_ClrSetReg, XRFdc_CustomStartUp, XRFdc_GetClockSource, XRFdc_GetMaxSampleRate, XRFdc_GetMinSampleRate, XRFdc_GetTileLayout, XRFDC_HSCOM_CLK_DSTR_OFFSET, XRFDC_HSCOM_PWR_STATE_OFFSET, XRFdc_IsHighSpeedADC, XRFDC_PLL_DIVIDER0, XRFDC_PLL_FREQ, XRFDC_PLL_FS, XRFDC_PWR_UP_STAT_MASK, XRFDC_PWR_UP_STAT_SHIFT, XRFdc_RDReg, XRFdc_ReadReg, XRFdc_ReadReg16, XRFDC_RX_PR_MC_CFG0_IDIV_MASK, XRFDC_RX_PR_MC_CFG0_PSNK_MASK, XRFDC_STATUS_OFFSET, XRFdc_WriteReg, XRFdc_WriteReg16.
u32 XRFdc_SetInvSincFIR(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u16 Mode)
This API is used to set the mode for the Inverse-Sinc filter.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is DAC block number inside the tile. Valid values are 0-3. Mode valid values are 0(disable), 1(1st Nyquist zone) and 2(2nd Nyquist zone). XRFDC_SUCCESS if successful.XRFDC_FAILURE if block not enabled/invalid mode. Only DAC blocks
References XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFDC_DAC_INVSINC_OFFSET, XRFDC_EN_INVSINC_MASK, XRFdc_GetNyquistZone, XRFDC_MODE_INVSINC_MASK.
u32 XRFdc_GetInvSincFIR(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u16 *ModePtr)
This API is used to get the Inverse-Sinc filter mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is DAC block number inside the tile. Valid values are 0-3. ModePtr is a pointer to get the inv-sinc status. valid values are 0(disable), 1(1st Nyquist zone) and 2(2nd Nyquist zone). XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only DAC blocks
References XRFdc_CheckBlockEnabled, XRFDC_DAC_INVSINC_OFFSET, XRFDC_EN_INVSINC_MASK, XRFDC_MODE_INVSINC_MASK, XRFdc_RDReg.
u32 XRFdc_GetCoupling(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 *ModePtr)
This function is used to get the Coupling mode.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC. Tile_Id indicates Tile number. Block_Id indicates Block number. ModePtr pointer to get link coupling mode. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
References XRFDC_ADC_RXPR_MC_CFG0_OFFSET, XRFdc_CheckBlockEnabled, XRFDC_CPL_TYPE_OFFSET, XRFdc_IsHighSpeedADC, XRFdc_RDReg, XRFdc_ReadReg, XRFDC_RX_MC_CFG0_CM_MASK.
u32 XRFdc_GetLinkCoupling(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *ModePtr)
This function is used to get the Link Coupling mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id indicates Tile number (0-3). Block_Id indicates Block number(0-3 for 2G, 0-1 for 4G). ModePtr pointer to get link coupling mode. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_ADC_RXPR_MC_CFG0_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_IsHighSpeedADC, XRFdc_RDReg, XRFDC_RX_MC_CFG0_CM_MASK.
u32 XRFdc_GetFabClkOutDiv(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u16 *FabClkDivPtr)
This API is to get the divider for clock fabric out.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. FabClkDivPtr is a pointer to get fabric clock for a tile. XRFDC_FAB_CLK_* defines the valid divider values. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. API is applicable for both ADC and DAC Tiles
References XRFdc_CheckTileEnabled, XRFDC_FAB_CLK_DIV_MASK, XRFDC_HSCOM_CLK_DIV_OFFSET, XRFdc_RDReg.
u32 XRFdc_SetDither(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 Mode)
This function is used to set the IM3 Dither mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id indicates Tile number (0-3). Block_Id indicates Block number(0-3 for LS, 0-1 for HS). Mode 0: Disable 1: Enable XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_ADC_DAC_MC_CFG0_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFdc_IsHighSpeedADC, XRFDC_RX_MC_CFG0_IM3_DITH_MASK, XRFDC_RX_MC_CFG0_IM3_DITH_SHIFT.
u32 XRFdc_GetDither(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *ModePtr)
This function is used to get the IM3 Dither mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id indicates Tile number (0-3). Block_Id indicates Block number(0-3 for LS, 0-1 for HS). ModePtr pointer to get link coupling mode. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_ADC_DAC_MC_CFG0_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_IsHighSpeedADC, XRFdc_RDReg, XRFDC_RX_MC_CFG0_IM3_DITH_MASK.
u32 XRFdc_SetClkDistribution(XRFdc *InstancePtr, XRFdc_Distribution_Settings *DistributionSettingsPtr)
This function is used to set the clock distribution.
InstancePtr is a pointer to the XRfdc instance. DistributionSettingsPtr pointer to the distribution settings struct XRFDC_SUCCESS if successful.XRFDC_FAILURE if could not set distribution.
References XRFDC_CLOCK_DETECT_DST_SHIFT, XRFDC_CLOCK_DETECT_MASK, XRFDC_CLOCK_DETECT_OFFSET, XRFDC_CLOCK_DETECT_SRC_MASK, XRFdc_ClrSetReg, XRFdc_GetTileLayout, XRFDC_HSCOM_CLK_DSTR_MASK, XRFDC_HSCOM_CLK_DSTR_OFFSET, XRFDC_PWR_STATE_MASK, XRFdc_RDReg, XRFDC_RESTART_MASK, XRFDC_RESTART_OFFSET, XRFDC_RESTART_STATE_OFFSET, XRFDC_RSR_START_SHIFT, XRFdc_WaitForState, XRFdc_WriteReg.
u32 XRFdc_GetClkDistribution(XRFdc *InstancePtr, XRFdc_Distribution_System_Settings *DistributionSystemPtr)
This function is used to get the clock distribution.
InstancePtr is a pointer to the XRfdc instance. DistributionSettingsPtr pointer to get the distribution settings XRFDC_SUCCESS if successful.XRFDC_FAILURE if no valid distribution found.
References XRFdc_CheckTileEnabled, XRFDC_CLOCK_DETECT_OFFSET, XRFDC_CLOCK_DETECT_SRC_MASK, XRFdc_GetPLLConfig, XRFdc_GetTileLayout, XRFDC_HSCOM_CLK_DSTR_OFFSET, XRFdc_RDReg, XRFdc_ReadReg16.
u32 XRFdc_SetSignalDetector(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, XRFdc_Signal_Detector_Settings *SettingsPtr)
This function is used to set the ADC Signal Detector Settings.
InstancePtr is a pointer to the XRfdc instance. Tile_Id indicates Tile number (0-3). Block_Id indicates Block number(0-3 for LS, 0-1 for HS). SettingsPtr pointer to the XRFdc_Signal_Detector_Settings structure to set the signal detector configurations XRFDC_SUCCESS if successful.XRFDC_FAILURE if tile not enabled, or invalid values. Only for ADC blocks
References XRFDC_ADC_SIG_DETECT_CTRL_OFFSET, XRFDC_ADC_SIG_DETECT_FLUSH_SHIFT, XRFDC_ADC_SIG_DETECT_HYST_SHIFT, XRFDC_ADC_SIG_DETECT_INTG_SHIFT, XRFDC_ADC_SIG_DETECT_MASK, XRFDC_ADC_SIG_DETECT_MODE_WRITE_SHIFT, XRFDC_ADC_SIG_DETECT_TCONST_SHIFT, XRFDC_ADC_SIG_DETECT_THRESHOLD0_CNT_OFF_OFFSET, XRFDC_ADC_SIG_DETECT_THRESHOLD0_CNT_ON_OFFSET, XRFDC_ADC_SIG_DETECT_THRESHOLD0_LEVEL_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFdc_IsHighSpeedADC, XRFdc_WriteReg16.
u32 XRFdc_GetSignalDetector(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, XRFdc_Signal_Detector_Settings *SettingsPtr)
This function is used to get the ADC Signal Detector Settings.
InstancePtr is a pointer to the XRfdc instance. Tile_Id indicates Tile number (0-3). Block_Id indicates Block number(0-3 for LS, 0-1 for HS). SettingsPtr pointer to the XRFdc_Signal_Detector_Settings structure to get the signal detector configurations XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_ADC_SIG_DETECT_CTRL_OFFSET, XRFDC_ADC_SIG_DETECT_FLUSH_MASK, XRFDC_ADC_SIG_DETECT_FLUSH_SHIFT, XRFDC_ADC_SIG_DETECT_HYST_MASK, XRFDC_ADC_SIG_DETECT_HYST_SHIFT, XRFDC_ADC_SIG_DETECT_INTG_MASK, XRFDC_ADC_SIG_DETECT_INTG_SHIFT, XRFDC_ADC_SIG_DETECT_MASK, XRFDC_ADC_SIG_DETECT_MODE_MASK, XRFDC_ADC_SIG_DETECT_MODE_READ_SHIFT, XRFDC_ADC_SIG_DETECT_TCONST_MASK, XRFDC_ADC_SIG_DETECT_TCONST_SHIFT, XRFDC_ADC_SIG_DETECT_THRESHOLD0_CNT_OFF_OFFSET, XRFDC_ADC_SIG_DETECT_THRESHOLD0_CNT_ON_OFFSET, XRFDC_ADC_SIG_DETECT_THRESHOLD0_LEVEL_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_IsHighSpeedADC, XRFdc_RDReg, XRFdc_ReadReg16.
u32 XRFdc_DisableCoefficientsOverride(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 CalibrationBlock)
This function is used to disable Calibration Coefficients override.
InstancePtr is a pointer to the XRfdc instance. Tile_Id indicates Tile number (0-3). Block_Id indicates Block number(0-3 for LS, 0-1 for HS). CalibrationBlock indicates the calibration block. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_ADC_TI_DCB_CRL1_OFFSET, XRFDC_ADC_TI_DCB_CRL3_OFFSET, XRFDC_CAL_GCB_ACEN_MASK, XRFDC_CAL_GCB_EN_MASK, XRFDC_CAL_GCB_ENFL_MASK, XRFDC_CAL_GCB_MASK, XRFDC_CAL_OCB_EN_MASK, XRFDC_CAL_TSCB_EN_MASK, XRFDC_CAL_TSCB_OFFSET_COEFF0, XRFDC_CAL_TSCB_OFFSET_COEFF0_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF1, XRFDC_CAL_TSCB_OFFSET_COEFF1_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF2, XRFDC_CAL_TSCB_OFFSET_COEFF2_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF3, XRFDC_CAL_TSCB_OFFSET_COEFF3_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF4, XRFDC_CAL_TSCB_OFFSET_COEFF4_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF5, XRFDC_CAL_TSCB_OFFSET_COEFF5_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF6, XRFDC_CAL_TSCB_OFFSET_COEFF6_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF7, XRFDC_CAL_TSCB_OFFSET_COEFF7_ALT, XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFdc_IsHighSpeedADC.
u32 XRFdc_SetCalCoefficients(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 CalibrationBlock, XRFdc_Calibration_Coefficients *CoeffPtr)
This function is used to set the ADC Calibration Coefficients.
InstancePtr is a pointer to the XRfdc instance. Tile_Id indicates Tile number (0-3). Block_Id indicates Block number(0-3 for LS, 0-1 for HS). CalibrationBlock indicates the block to be written to. CoeffPtr is pointer to the XRFdc_Calibration_Coefficients structure to set the calibration coefficients. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_ADC_TI_DCB_CRL1_OFFSET, XRFDC_ADC_TI_DCB_CRL3_OFFSET, XRFDC_CAL_GCB_ACEN_MASK, XRFDC_CAL_GCB_EN_MASK, XRFDC_CAL_GCB_EN_SHIFT, XRFDC_CAL_GCB_FLSH_MASK, XRFDC_CAL_GCB_FLSH_SHIFT, XRFDC_CAL_GCB_MASK, XRFDC_CAL_GCB_OFFSET_COEFF0, XRFDC_CAL_GCB_OFFSET_COEFF1, XRFDC_CAL_GCB_OFFSET_COEFF2, XRFDC_CAL_GCB_OFFSET_COEFF3, XRFDC_CAL_OCB1_OFFSET_COEFF0, XRFDC_CAL_OCB1_OFFSET_COEFF1, XRFDC_CAL_OCB1_OFFSET_COEFF2, XRFDC_CAL_OCB1_OFFSET_COEFF3, XRFDC_CAL_OCB2_OFFSET_COEFF0, XRFDC_CAL_OCB2_OFFSET_COEFF1, XRFDC_CAL_OCB2_OFFSET_COEFF2, XRFDC_CAL_OCB2_OFFSET_COEFF3, XRFDC_CAL_OCB_EN_MASK, XRFDC_CAL_OCB_MASK, XRFDC_CAL_SLICE_SHIFT, XRFDC_CAL_TSCB_EN_MASK, XRFDC_CAL_TSCB_EN_SHIFT, XRFDC_CAL_TSCB_MASK, XRFDC_CAL_TSCB_OFFSET_COEFF0, XRFDC_CAL_TSCB_OFFSET_COEFF0_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF1, XRFDC_CAL_TSCB_OFFSET_COEFF1_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF2, XRFDC_CAL_TSCB_OFFSET_COEFF2_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF3, XRFDC_CAL_TSCB_OFFSET_COEFF3_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF4, XRFDC_CAL_TSCB_OFFSET_COEFF4_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF5, XRFDC_CAL_TSCB_OFFSET_COEFF5_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF6, XRFDC_CAL_TSCB_OFFSET_COEFF6_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF7, XRFDC_CAL_TSCB_OFFSET_COEFF7_ALT, XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFdc_IsHighSpeedADC.
u32 XRFdc_GetCalCoefficients(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 CalibrationBlock, XRFdc_Calibration_Coefficients *CoeffPtr)
This function is used to get the ADC Calibration Coefficients.
InstancePtr is a pointer to the XRfdc instance. Tile_Id indicates Tile number (0-3). Block_Id indicates Block number(0-3 for LS, 0-1 for HS). CalibrationBlock indicates the block to be read from CoeffPtr is pointer to the XRFdc_Calibration_Coefficients structure to get the calibration coefficients. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_ADC_TI_DCB_CRL1_OFFSET, XRFDC_CAL_GCB_FAB_MASK, XRFDC_CAL_GCB_FLSH_MASK, XRFDC_CAL_GCB_MASK, XRFDC_CAL_GCB_OFFSET_COEFF0, XRFDC_CAL_GCB_OFFSET_COEFF0_ALT, XRFDC_CAL_GCB_OFFSET_COEFF1, XRFDC_CAL_GCB_OFFSET_COEFF1_ALT, XRFDC_CAL_GCB_OFFSET_COEFF2, XRFDC_CAL_GCB_OFFSET_COEFF2_ALT, XRFDC_CAL_GCB_OFFSET_COEFF3, XRFDC_CAL_GCB_OFFSET_COEFF3_ALT, XRFDC_CAL_OCB1_OFFSET_COEFF0, XRFDC_CAL_OCB1_OFFSET_COEFF1, XRFDC_CAL_OCB1_OFFSET_COEFF2, XRFDC_CAL_OCB1_OFFSET_COEFF3, XRFDC_CAL_OCB2_OFFSET_COEFF0, XRFDC_CAL_OCB2_OFFSET_COEFF1, XRFDC_CAL_OCB2_OFFSET_COEFF2, XRFDC_CAL_OCB2_OFFSET_COEFF3, XRFDC_CAL_OCB_MASK, XRFDC_CAL_SLICE_SHIFT, XRFDC_CAL_TSCB_MASK, XRFDC_CAL_TSCB_OFFSET_COEFF0, XRFDC_CAL_TSCB_OFFSET_COEFF0_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF1, XRFDC_CAL_TSCB_OFFSET_COEFF1_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF2, XRFDC_CAL_TSCB_OFFSET_COEFF2_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF3, XRFDC_CAL_TSCB_OFFSET_COEFF3_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF4, XRFDC_CAL_TSCB_OFFSET_COEFF4_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF5, XRFDC_CAL_TSCB_OFFSET_COEFF5_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF6, XRFDC_CAL_TSCB_OFFSET_COEFF6_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF7, XRFDC_CAL_TSCB_OFFSET_COEFF7_ALT, XRFdc_CheckBlockEnabled, XRFdc_IsHighSpeedADC, XRFdc_RDReg.
u32 XRFdc_SetCalFreeze(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, XRFdc_Cal_Freeze_Settings *CalFreezePtr)
This function is used to set calibration freeze settings.
InstancePtr is a pointer to the XRfdc instance. Tile_Id indicates Tile number (0-3). Block_Id indicates Block number(0-3 for LS, 0-1 for HS). CalFreezePtr pointer to the settings to be applied. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_CAL_FREEZE_CAL_MASK, XRFDC_CAL_FREEZE_CAL_SHIFT, XRFDC_CAL_FREEZE_PIN_MASK, XRFDC_CAL_FREEZE_PIN_SHIFT, XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFdc_IsHighSpeedADC.
u32 XRFdc_GetCalFreeze(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, XRFdc_Cal_Freeze_Settings *CalFreezePtr)
This function is used to get calibration freeze settings and status.
InstancePtr is a pointer to the XRfdc instance. Tile_Id indicates Tile number (0-3). Block_Id indicates Block number(0-3 for LS, 0-1 for HS). CalFreezePtr pointer to be filled the settings/status. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_CAL_FREEZE_CAL_MASK, XRFDC_CAL_FREEZE_CAL_SHIFT, XRFDC_CAL_FREEZE_PIN_MASK, XRFDC_CAL_FREEZE_PIN_SHIFT, XRFDC_CAL_FREEZE_STS_MASK, XRFDC_CAL_FREEZE_STS_SHIFT, XRFdc_CheckBlockEnabled, XRFdc_IsHighSpeedADC, XRFdc_RDReg.
u32 XRFdc_SetDACVOP(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 uACurrent)
Set Output Current for DAC block.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. uACurrent is the current in uA. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Range 6425 - 32000 uA with 25 uA resolution.
References XRFDC_ADC_DAC_MC_CFG0_OFFSET, XRFDC_ADC_DAC_MC_CFG2_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFDC_CPL_TYPE_OFFSET, XRFDC_DAC_MC_CFG3_OFFSET, XRFDC_DAC_VOP_CTRL_OFFSET, XRFdc_RDReg, XRFdc_ReadReg.
u32 XRFdc_SetDACCompMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 Enable)
Sets VOP compatibility mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. mode is ADC/DAC block number inside the tile. Valid values are 0-3. Enable is whether to enable (1) or disable(0) the compatibility mode. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
References XRFDC_ADC_DAC_MC_CFG2_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg.
u32 XRFdc_GetDACCompMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *EnabledPtr)
Gets VOP compatibility mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. mode is ADC/DAC block number inside the tile. Valid values are 0-3. EnabledPtr is pointer a that is filled with whether the mode is enabled (1) or disabled(0). XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
References XRFDC_ADC_DAC_MC_CFG2_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_RDReg.
u32 XRFdc_SetDSA(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, XRFdc_DSA_Settings *SettingsPtr)
Set DSA for ADC block.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Attenuation is the attenuation in dB XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Range 0 - 11 dB with 0.5 dB resolution ES1 Si. Range 0 - 27 dB with 1 dB resolution for Production Si.
References XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFDC_DSA_UPDT_OFFSET, XRFdc_IsHighSpeedADC.
u32 XRFdc_GetDSA(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, XRFdc_DSA_Settings *SettingsPtr)
Get DSA for ADC block.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. AttenuationPtr is the attenuation in dB XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Range 0 - 11 dB with 0.5 dB resolution ES1 Si. Range 0 - 27 dB with 1 dB resolution for Production Si.
References XRFdc_CheckBlockEnabled, XRFdc_IsHighSpeedADC, XRFdc_RDReg, XRFdc_ReadReg16.
u32 XRFdc_ResetInternalFIFOWidth(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id)
Set the correct FIFO width for current mixer & rate change settings.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id Valid values are 0-3. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Common API for ADC/DAC blocks
References XRFdc_CheckDigitalPathEnabled.
Referenced by XRFdc_SetMixerSettings.
u32 XRFdc_ResetInternalFIFOWidthObs(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id)
Set the correct Observation FIFO width for current mixer & rate change settings.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id Valid values are 0-3. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. ADC blocks only
References XRFdc_CheckDigitalPathEnabled.
u32 XRFdc_IsDACBlockEnabled(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id)
Checks whether DAC block is available or not.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Return 1 if DAC block is available, otherwise 0.
References XRFDC_DAC_PATHS_ENABLED_OFFSET, XRFDC_PATH_ENABLED_TILE_SHIFT, XRFdc_ReadReg.
Referenced by XRFdc_CheckBlockEnabled, XRFdc_GetIPStatus.
u32 XRFdc_IsADCBlockEnabled(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id)
Checks whether ADC block is available or not.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3 in DAC/ADC-2GSPS and 0-1 in ADC-4GSPS. Return 1 if ADC block is available, otherwise 0.
References XRFDC_ADC_PATHS_ENABLED_OFFSET, XRFdc_IsHighSpeedADC, XRFDC_PATH_ENABLED_TILE_SHIFT, XRFdc_ReadReg.
Referenced by XRFdc_CheckBlockEnabled, XRFdc_GetIPStatus.
u32 XRFdc_IsDACDigitalPathEnabled(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id)
Checks whether DAC Digital path is enabled or not.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Return 1 if DAC digital path is enabled, otherwise 0.
References XRFDC_DAC_PATHS_ENABLED_OFFSET, XRFDC_DIGITAL_PATH_ENABLED_SHIFT, XRFDC_PATH_ENABLED_TILE_SHIFT, XRFdc_ReadReg.
Referenced by XRFdc_CheckDigitalPathEnabled.
u32 XRFdc_IsADCDigitalPathEnabled(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id)
Checks whether ADC digital path is enabled or not.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3 in DAC/ADC-2GSPS and 0-1 in ADC-4GSPS. Return 1 if ADC digital path is enabled, otherwise 0.
References XRFDC_ADC_PATHS_ENABLED_OFFSET, XRFDC_DIGITAL_PATH_ENABLED_SHIFT, XRFdc_IsHighSpeedADC, XRFDC_PATH_ENABLED_TILE_SHIFT, XRFdc_ReadReg.
Referenced by XRFdc_CheckDigitalPathEnabled.
u32 XRFdc_CheckDigitalPathEnabled(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id)
Checks whether ADC/DAC Digital path is enabled or not.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. XRFDC_SUCCESS if Digital path is enabled.XRFDC_FAILURE if Digital path is not enabled.
References XRFdc_IsADCDigitalPathEnabled, XRFdc_IsDACDigitalPathEnabled.
Referenced by XRFdc_GetCalibrationMode, XRFdc_GetConnectedIQData, XRFdc_GetDataPathMode, XRFdc_GetEnabledInterrupts, XRFdc_GetInterpolationFactor, XRFdc_GetIntrStatus, XRFdc_GetMixerSettings, XRFdc_GetNyquistZone, XRFdc_IntrClr, XRFdc_IntrDisable, XRFdc_IntrEnable, XRFdc_MultiBand, XRFdc_ResetInternalFIFOWidth, XRFdc_ResetInternalFIFOWidthObs, XRFdc_ResetNCOPhase, XRFdc_SetCalibrationMode, XRFdc_SetDataPathMode, XRFdc_SetFabWrVldWords, XRFdc_SetInterpolationFactor, XRFdc_SetMixerSettings, XRFdc_UpdateEvent.
u32 XRFdc_GetDataType(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id)
Get Mixer Input Data Type for ADC/DAC block.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Return MixerInputDataType of ADC/DAC block.Return 0 if invalid
u32 XRFdc_GetInverseSincFilter(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id)
Get Inversesync filter for DAC block.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Return Inversesync filter for DAC blockReturn 0 if invalid
u32 XRFdc_GetMixedMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id)
Get Mixed mode for DAC block.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Return mixed mode for DAC blockReturn 0 if invalid
u32 XRFdc_GetMasterTile(XRFdc *InstancePtr, u32 Type)
Get Master Tile for ADC/DAC tiles.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Return Master Tile for ADC/DAC tilesReturn XRFDC_TILE_ID_INV if invalid tile
u32 XRFdc_GetSysRefSource(XRFdc *InstancePtr, u32 Type)
Get Sysref source for ADC/DAC tile.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Return Sysref source for ADC/DAC tileReturn XRFDC_TILE_ID_INV if invalid tile
double XRFdc_GetFabClkFreq(XRFdc *InstancePtr, u32 Type, u32 Tile_Id)
Get Fabric Clock frequency.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Return Fabric Clock frequency for ADC/DAC tile
u32 XRFdc_IsFifoEnabled(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id)
Get whether FIFO is enabled or not.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Return 1 if FIFO is enabled, otherwise 0.
void XRFdc_SetConnectedIQData(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, int ConnectedIData, int ConnectedQData)
Set Data Converter connected for digital data path I and Q.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is Digital Data Path number. ConnectedIData is Converter Id to which DigitalPathI connected. ConnectedQData is Converter Id to which DigitalPathQ connected. None.
u32 XRFdc_GetMultibandConfig(XRFdc *InstancePtr, u32 Type, u32 Tile_Id)
Get Multiband Config data.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Return Multiband Configuration.Return 0 if invalid.
References XRFDC_MB_CONFIG_OFFSET, XRFdc_ReadReg.
u32 XRFdc_CheckBlockEnabled(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id)
Checks whether ADC/DAC block is enabled or not.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. XRFDC_SUCCESS if block enabled.XRFDC_FAILURE if block not enabled.
References XRFdc_IsADCBlockEnabled, XRFdc_IsDACBlockEnabled.
Referenced by XRFdc_DisableCoefficientsOverride, XRFdc_Get_BlockBaseAddr, XRFdc_GetBlockStatus, XRFdc_GetCalCoefficients, XRFdc_GetCalFreeze, XRFdc_GetCalibrationMode, XRFdc_GetCoarseDelaySettings, XRFdc_GetCoupling, XRFdc_GetDACCompMode, XRFdc_GetDACDataScaler, XRFdc_GetDecoderMode, XRFdc_GetDither, XRFdc_GetDSA, XRFdc_GetEnabledInterrupts, XRFdc_GetIMRPassMode, XRFdc_GetIntrStatus, XRFdc_GetInvSincFIR, XRFdc_GetLinkCoupling, XRFdc_GetNyquistZone, XRFdc_GetOutputCurr, XRFdc_GetPwrMode, XRFdc_GetQMCSettings, XRFdc_GetSignalDetector, XRFdc_GetThresholdSettings, XRFdc_IntrClr, XRFdc_IntrDisable, XRFdc_IntrEnable, XRFdc_MultiBand, XRFdc_MultiConverter_Sync, XRFdc_SetCalCoefficients, XRFdc_SetCalFreeze, XRFdc_SetCalibrationMode, XRFdc_SetCoarseDelaySettings, XRFdc_SetDACCompMode, XRFdc_SetDACDataScaler, XRFdc_SetDACVOP, XRFdc_SetDataPathMode, XRFdc_SetDecoderMode, XRFdc_SetDither, XRFdc_SetDSA, XRFdc_SetIMRPassMode, XRFdc_SetInvSincFIR, XRFdc_SetNyquistZone, XRFdc_SetPwrMode, XRFdc_SetQMCSettings, XRFdc_SetSignalDetector, XRFdc_SetThresholdClrMode, XRFdc_SetThresholdSettings, XRFdc_ThresholdStickyClear, XRFdc_UpdateEvent.
u32 XRFdc_MultiConverter_Sync(XRFdc *InstancePtr, u32 Type, XRFdc_MultiConverter_Sync_Config *ConfigPtr)
This is the top level API which will be used for Multi-tile Synchronization.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC ConfigPtr Multi-tile sync config structure. XRFDC_MTS_OK if successful. XRFDC_MTS_TIMEOUT if timeout occurs. XRFDC_MTS_MARKER_RUNXRFDC_MTS_MARKER_MISMXRFDC_MTS_NOT_SUPPORTED if MTS is not supported. None.
References XRFdc_CheckBlockEnabled, XRFdc_GetIPStatus, XRFdc_ReadReg.
Referenced by RFdcMTS_Example.
u32 XRFdc_MultiConverter_Init(XRFdc_MultiConverter_Sync_Config *ConfigPtr, int *PLL_CodesPtr, int *T1_CodesPtr, u32 RefTile)
This API Initializes the multi-tile sync config structures.
Optionally allows target codes to be provided for the Pll/T1 analog sysref capture ConfigPtr pointer to Multi-tile sync config structure. PLL_CodesPtr pointer to PLL analog sysref capture. T1_CodesPtr pointer to T1 analog sysref capture. RefTile the tile ID of the reference tile. XRFDC_MTS_OK if successful.XRFDC_MTS_BAD_REF_TILE if bad reference tile value is supplied. None.
Referenced by RFdcMTS_Example.
u32 XRFdc_MTS_Sysref_Config(XRFdc *InstancePtr, XRFdc_MultiConverter_Sync_Config *DACSyncConfigPtr, XRFdc_MultiConverter_Sync_Config *ADCSyncConfigPtr, u32 SysRefEnable)
This API is used to enable/disable the sysref.
InstancePtr is a pointer to the XRfdc instance. DACSyncConfigPtr is pointer to DAC Multi-Tile Sync config structure. ADCSyncConfigPtr is pointer to ADC Multi-Tile Sync config structure. SysRefEnable valid values are 0(disable) and 1(enable). XRFDC_MTS_OK if successful. None.
u32 XRFdc_GetMTSEnable(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 *EnablePtr)
This is the top level API which will be used to check if Multi-tile is enabled.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC. Tile_Id indicates Tile number (0-3). EnablePtr to be filled with the enable state. XRFDC_SUCCESS if successful.XRFDC_SUCCESS if error occurs. None.
References XRFdc_CheckTileEnabled, XRFdc_ReadReg.
u32 XRFdc_SetDACDataScaler(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 Enable)
Set data scaler for DAC block.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Enable valid values are 1 (enable) and 0 (disable). XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. DAC blocks only.
References XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFDC_DATA_SCALER_MASK, XRFDC_DATA_SCALER_OFFSET.
u32 XRFdc_GetDACDataScaler(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *EnablePtr)
Get data scaler for DAC block.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. EnablePtr valid values are 1 (enable) and 0 (disable). XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. DAC blocks only.
References XRFdc_CheckBlockEnabled, XRFDC_DATA_SCALER_MASK, XRFDC_DATA_SCALER_OFFSET, XRFdc_RDReg.
s32 XRFdc_GetDeviceNameByDeviceId(char *DevNamePtr, u16 DevId)
Traverse "/sys/bus/platform/device" directory, to find RFDC device entry, corresponding to provided device id.
If device entry corresponding to said device id is found, store it in output buffer DevNamePtr. DevNamePtr is base address of char array, where device name will be stored DevId contains the ID of the device to look up the RFDC device name entry in "/sys/bus/platform/device" XRFDC_SUCCESS if successful.XRFDC_FAILURE if device entry not found for given device id. None.
Referenced by XRFdc_LookupConfig, XRFdc_RegisterMetal.
static u32 XRFdc_CheckClkDistValid(XRFdc *InstancePtr, XRFdc_Distribution_Settings *DistributionSettingsPtr)
This function is used to check the distribution chosen is valid.
InstancePtr is a pointer to the XRfdc instance. DistributionSettingsPtr pointer to the distribution settings struct XRFDC_SUCCESS if valid.XRFDC_FAILURE if not valid.
static u32 XRFdc_SetPLLConfig(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, double RefClkFreq, double SamplingRate)
This function used for configuring the internal PLL registers based on reference clock and sampling rate.
InstancePtr is a pointer to the XRfdc instance. Type indicates ADC/DAC. Tile_Id indicates Tile number (0-3). RefClkFreq Reference Clock Frequency MHz(50MHz - 1.2GHz) SamplingRate Sampling Rate in MHz(0.5- 4 GHz) XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
static void XRFdc_DistTile2TypeTile(XRFdc *InstancePtr, u32 DistTile, u32 *Type, u32 *Tile_Id)
static u8 XRFdc_TypeTile2DistTile(XRFdc *InstancePtr, u32 Type, u32 Tile_Id)
static u32 XRFdc_SetTileClkSettings(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, XRFdc_Tile_Clock_Settings *SettingsPtr)
This function is used to set the clock settings.
InstancePtr is a pointer to the XRfdc instance. Type indicates ADC/DAC. Tile_Id indicates Tile number (0-3). SettingsPtr pointer to set the clock settings XRFDC_SUCCESS if successful.XRFDC_FAILURE if no valid distribution found.
static u32 XRFdc_StartUpDist(XRFdc *InstancePtr, XRFdc_Distribution_Settings *DistributionSettingsPtr)
This function is used to start the distribution tiles.
InstancePtr is a pointer to the XRfdc instance. DistributionSettingsPtr pointer to the distribution settings struct XRFDC_SUCCESS if valid.XRFDC_FAILURE if not valid.
static void XRFdc_IntResetInternalFIFOWidth(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 Channel)
Set the correct FIFO width for current mixer & rate change settings (int).
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id Valid values are 0-3. Channel Valid values are 0 for actual FIFO 1 for obs FIFO. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Common API for ADC/DAC blocks
static u32 XRFdc_SetDecimationFactorInt(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 DecimationFactor, u32 Channel)
This function is to set the decimation factor and also update the FIFO write words w.r.t to decimation factor for both the actual and observtion FIFOs.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. DecimationFactor to be set for DAC block. XRFDC_INTERP_DECIM_* defines the valid values. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only ADC blocks
static u32 XRFdc_GetDecimationFactorInt(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *DecimationFactorPtr, u32 Channel)
Decimation factor are returned back to the caller for both actual and observation FIFO.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. DecimationFactorPtr Pointer to return the Decimation factor for DAC blocks. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
static u32 XRFdc_SetFabRdVldWordsInt(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 FabricRdVldWords, u32 Channel)
Fabric data rate for the requested ADC block is set by writing to the corresponding register.
The function writes the number of valid read words for the requested ADC block. This is for both the actual and observation FIFO. InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC block number inside the tile. Valid values are 0-3. FabricRdVldWords is Read fabric rate to be set for ADC block. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
static u32 XRFdc_GetFabWrVldWordsInt(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 *FabricWrVldWordsPtr, u32 Channel)
This function returns the the number of fabric write valid words requested for the block.
For ADCs this is for both the actual and observation FIFO. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. FabricWrVldWordsPtr Pointer to return the fabric data rate for DAC block XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. ADC/DAC blocks
static u32 XRFdc_GetFabRdVldWordsInt(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 *FabricRdVldWordsPtr, u32 Channel)
This function returns the number of fabric read valid words requested for the block.
For ADCs this is for both the actual and observation FIFO. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. FabricRdVldWordsPtr Pointer to return the fabric data rate for ADC/DAC block XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. ADC/DAC blocks
static u32 XRFdc_SetupFIFOInt(XRFdc *InstancePtr, u32 Type, int Tile_Id, u8 Enable, u32 Channel)
Enable and Disable the ADC/DAC FIFO.
For ADCs this is for the actual and observtion FIFO. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Enable valid values are 1 (FIFO enable) and 0 (FIFO Disable) XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Common API for ADC/DAC blocks
u32 XRFdc_GetFIFOStatusInt(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u8 *EnablePtr, u32 Channel)
Current status of ADC/DAC FIFO.
For ADCs this is for both the actual and observations FIFOs. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. EnablePtr valid values are 1 (FIFO enable) and 0 (FIFO Disable) XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Common API for ADC/DAC blocks
References XRFdc_CheckTileEnabled, XRFDC_FIFO_EN_MASK, XRFDC_FIFO_EN_OBS_MASK, XRFDC_FIFO_EN_OBS_SHIFT, XRFDC_FIFO_ENABLE, XRFdc_RDReg.
Referenced by XRFdc_GetFIFOStatus, XRFdc_GetFIFOStatusObs.
static void XRFdc_SetSignalFlow(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Mode, u32 DigitalDataPathId, u32 MixerInOutDataType, int ConnectIData, int ConnectQData)
Sets up signal flow configuration.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Mode is connection mode SB/MB_2X/MB_4X. DigitalDataPathId for the requested I or Q data. MixerInOutDataType is mixer data type, valid values are XRFDC_MB_DATATYPE_* ConnectIData is analog blocks that are connected to DigitalDataPath I. ConnectQData is analog blocks that are connected to DigitalDataPath Q. None.static API used internally.
static void XRFdc_MB_R2C_C2R(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u8 NoOfDataPaths, u32 MixerInOutDataType, u32 Mode, u32 DataPathIndex[], u32 BlockIndex[])
Static API to setup Multiband configuration for C2C MixerInOutDataType.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. MixerInOutDataType is mixer data type, valid values are XRFDC_MB_DATATYPE_* Mode is connection mode SB/MB_2X/MB_4X. DataPathIndex is the array that represents the blocks enabled in DigitalData Path. BlockIndex is the array that represents the blocks enabled in Analog Path(Data Converters). None Static API for ADC/DAC blocks
static void XRFdc_MB_C2C(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u8 NoOfDataPaths, u32 MixerInOutDataType, u32 Mode, u32 DataPathIndex[], u32 BlockIndex[])
Static API to setup Multiband configuration for C2C MixerInOutDataType.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. MixerInOutDataType is mixer data type, valid values are XRFDC_MB_DATATYPE_* Mode is connection mode SB/MB_2X/MB_4X. DataPathIndex is the array that represents the blocks enabled in DigitalData Path. BlockIndex is the array that represents the blocks enabled in Analog Path(Data Converters). None Static API for ADC/DAC blocks
static void XRFdc_SB_R2C_C2R(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 MixerInOutDataType, u32 Mode, u32 DataPathIndex[], u32 BlockIndex[])
Static API to setup Singleband configuration for C2R and R2C MultiBandDataTypes.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. MixerInOutDataType is mixer data type, valid values are XRFDC_MB_DATATYPE_* Mode is connection mode SB/MB_2X/MB_4X. DataPathIndex is the array that represents the blocks enabled in DigitalData Path. BlockIndex is the array that represents the blocks enabled in Analog Path(Data Converters). None Static API for ADC/DAC blocks
static void XRFdc_SB_C2C(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 MixerInOutDataType, u32 Mode, u32 DataPathIndex[], u32 BlockIndex[])
Static API to setup Singleband configuration for C2C MixerInOutDataType.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. MixerInOutDataType is mixer data type, valid values are XRFDC_MB_DATATYPE_* Mode is connection mode SB/MB_2X/MB_4X. DataPathIndex is the array that represents the blocks enabled in DigitalData Path. BlockIndex is the array that represents the blocks enabled in Analog Path(Data Converters). None Static API for ADC/DAC blocks
static void XRFdc_AltQMCRouting(XRFdc *InstancePtr, u32 Tile_Id, u32 Enable)
Static API to route QMC settings if switching to and from complex mode on alternate bodnout devices.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Enable 0 for normal routing, 1 for IQ routing. None Static API for DAC Tiles
static u32 XRFdc_UpdateMBConfig(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u8 NoOfDataPaths, u32 *ModePtr, u32 DataPathIndex[], u32 MixerInOutDataType)
Static API to update mode and MultibandConfig.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. NoOfDataPaths is number of DataPaths enabled. ModePtr is a pointer to connection mode SB/MB_2X/MB_4X. DataPathIndex is the array that represents the blocks enabled in DigitalData Path. MixerInOutDataType is mixer data type, valid values are XRFDC_MB_DATATYPE_* None Static API for ADC/DAC blocks
static void XRFdc_SetFineMixer(XRFdc *InstancePtr, u32 BaseAddr, XRFdc_Mixer_Settings *MixerSettingsPtr)
Static API used to set the Fine Mixer.
InstancePtr is a pointer to the XRfdc instance. BaseAddr is ADC or DAC base address. MixerSettingsPtr Pointer to the XRFdc_Mixer_Settings structure in which the Mixer/NCO settings are passed. None Static API
static void XRFdc_SetCoarseMixer(XRFdc *InstancePtr, u32 Type, u32 BaseAddr, u32 Tile_Id, u32 Block_Id, u32 CoarseMixFreq, XRFdc_Mixer_Settings *MixerSettingsPtr)
Static API used to set the Coarse Mixer.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC BaseAddr is ADC or DAC base address. Block_Id is ADC/DAC block number inside the tile. CoarseMixFreq is ADC or DAC Coarse mixer frequency. MixerSettingsPtr Pointer to the XRFdc_Mixer_Settings structure in which the Mixer/NCO settings are passed. None Static API
static u32 XRFdc_MixerRangeCheck(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, XRFdc_Mixer_Settings *MixerSettingsPtr)
Static API used to do the Mixer Settings range check.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC MixerSettingsPtr Pointer to the XRFdc_Mixer_Settings structure in which the Mixer/NCO settings are passed. XRFDC_SUCCESS if mixer settings are within the range.XRFDC_FAILURE if mixer settings are not in valid range None.
static void XRFdc_MixersOff(XRFdc *InstancePtr, u32 BaseAddr)
Static API used to turn off Fine & Coarse Mixers.
InstancePtr is a pointer to the XRfdc instance. BaseAddr is ADC or DAC base address. None Static API
static void XRFdc_MTS_Sysref_TRx(XRFdc *InstancePtr, u32 Enable)
This API enables the master tile sysref Tx/Rx.
InstancePtr is a pointer to the XRfdc instance. Enable the master tile sysref for Tx/Rx, valid values are 0 and 1. None. None.
static void XRFdc_MTS_Sysref_Ctrl(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Is_PLL, u32 Enable_Cap, u32 Enable_Div_Reset)
This API Control SysRef Capture Settings.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Is_PLL Valid values are 0 and 1. Enable_Cap Valid values are 0 and 1. Enable_Div_Reset Valid values are 0 and 1. None. None.
static u32 XRFdc_MTS_Sysref_Dist(XRFdc *InstancePtr, int Num_DAC)
This API Update SysRef Distribution between tiles.
InstancePtr is a pointer to the XRfdc instance. Num_DAC is number of DAC tiles XRFDC_MTS_OK if successful.XRFDC_MTS_NOT_SUPPORTED None.
static u32 XRFdc_MTS_Sysref_Count(XRFdc *InstancePtr, u32 Type, u32 Count_Val)
This API Wait for a number of sysref's to be captured.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Count_Val to wait for a number of sysref's to be captured. XRFDC_MTS_OK if successful.XRFDC_MTS_TIMEOUT if timeout occurs. None.
static u32 XRFdc_MTS_Dtc_Scan(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, XRFdc_MTS_DTC_Settings *SettingsPtr)
This API Scan the DTC codes and determine the optimal capture code for both PLL and T1 cases.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. SettingsPtr dtc settings structure. XRFDC_MTS_OK if successful. XRFDC_MTS_TIMEOUT if timeout occurs. None.
static u32 XRFdc_MTS_Dtc_Code(XRFdc *InstancePtr, u32 Type, u32 BaseAddr, u32 SRCtrlAddr, u32 DTCAddr, u16 SRctl, u16 SRclr_m, u32 Code)
This API Set a DTC code and wait for it to be updated.
Return early/late flags, if set InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC BaseAddr is for internal usage. SRCtrlAddr is for internal usage. DTCAddr is for internal usage. SRctl is for internal usage. SRclr_m is for internal usage. Code is for internal usage. XRFDC_MTS_OK if successful. XRFDC_MTS_TIMEOUT if timeout occurs. None.
static u32 XRFdc_MTS_Dtc_Calc(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, XRFdc_MTS_DTC_Settings *SettingsPtr, u8 *FlagsPtr)
This API Calculate the best DTC code to use.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. SettingsPtr dtc settings structure. FlagsPtr is for internal usage. XRFDC_MTS_OK if successful. XRFDC_MTS_NOT_SUPPORTED if MTS is not supported. None.
static void XRFdc_MTS_Dtc_Flag_Debug(u8 *FlagsPtr, u32 Type, u32 Tile_Id, u32 Target, u32 Picked)
This API print the DTC scan results.
FlagsPtr is for internal usage. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Target is for internal usage. Picked is for internal usage. None.None.
static void XRFdc_MTS_FIFOCtrl(XRFdc *InstancePtr, u32 Type, u32 FIFO_Mode, u32 Tiles_To_Clear)
This API Control the FIFO enable for the group.
If Tiles_to_clear has bits set, the FIFOs of those tiles will have their FIFO flags cleared. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC FIFO_Mode is fifo mode. Tiles_To_Clear bits set, FIFO flags will be cleared for those tiles. None.None.
static u32 XRFdc_MTS_GetMarker(XRFdc *InstancePtr, u32 Type, u32 Tiles, XRFdc_MTS_Marker *MarkersPtr, int Marker_Delay)
This API Run the marker counter and read the results.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tiles is tiles to get marker MarkersPtr mts marker structure. Marker_Delay is marker delay. XRFDC_MTS_OK if successful.XRFDC_MTS_TIMEOUT if timeout occurs.XRFDC_MTS_MARKER_RUNXRFDC_MTS_MARKER_MISM None.
static void XRFdc_MTS_Marker_Read(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 FIFO_Id, u32 *CountPtr, u32 *LocPtr, u32 *DonePtr)
This API Read-back the marker data for an ADC or DAC.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. FIFO_Id is FIFO number. Count is for internal usage. Loc is for internal usage. Done is for internal usage. None. None.
static u32 XRFdc_MTS_Latency(XRFdc *InstancePtr, u32 Type, XRFdc_MultiConverter_Sync_Config *ConfigPtr, XRFdc_MTS_Marker *MarkersPtr)
This API Calculate the absolute/relative latencies.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC ConfigPtr is mts config structure. MarkersPtr is mts marker structure. XRFDC_MTS_OK if successful.XRFDC_MTS_DELAY_OVERXRFDC_MTS_TARGET_LOW Latency calculation will use Sysref frequency counters logic which will work with IP version 2.0.1 and above.
static u32 XRFdc_MTS_Dtc_Scan_PLL(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, XRFdc_MultiConverter_Sync_Config *ConfigPtr)
This API Scans the DTC codes and determine the optimal capture code for PLL cases.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. SettingsPtr dtc settings structure. XRFDC_MTS_OK if successful.XRFDC_MTS_TIMEOUT if timeout occurs. None.
int metal_linux_get_device_property(struct metal_device *device, const char *property_name, void *output, int len)
static s32 XRFdc_Strrncmp(const char *Str1Ptr, const char *Str2Ptr, size_t Count)
Compare two strings in the reversed order.This function compares only the last "Count" number of characters of Str1Ptr and Str2Ptr.
Str1Ptr is base address of first string Str2Ptr is base address of second string Count is number of last characters to be compared between Str1Ptr and Str2Ptr 0 if last "Count" number of bytes matches between Str1Ptr and Str2Ptr, else difference in unmatched character. None.
XRFdc_Config* XRFdc_LookupConfig(u16 DeviceId)
Looks up the device configuration based on the unique device ID.
A table contains the configuration info for each device in the system. DeviceId contains the ID of the device to look up the configuration for. A pointer to the configuration found or NULL if the specified device ID was not found. See xrfdc.h for the definition of XRFdc_Config.None.
References XRFdc_Config::Name, XRFdc_GetDeviceNameByDeviceId.
Referenced by RFdcMTS_Example.
XRFdc_IsADC4GSPS
XRFDC_MTS_RMW
XRFDC_MTS_FIELD
Xil_AssertNonvoid
Xil_AssertVoid
Xil_AssertVoidAlways
XRFDC_MAX
XRFDC_MIN
XRFDC_SUCCESS
XRFDC_FAILURE
XRFDC_GEN3
XRFDC_COMPONENT_IS_READY
XRFDC_NUM_SLICES_HSADC
XRFDC_NUM_SLICES_LSADC
XRFDC_PLATFORM_DEVICE_DIR
XRFDC_BUS_NAME
XRFDC_SIGNATURE
XRFDC_CONFIG_DATA_PROPERTY
XRFDC_COMPATIBLE_PROPERTY
XRFDC_NUM_INSTANCES_PROPERTY
XRFDC_COMPATIBLE_STRING
XRFDC_DEVICE_ID_SIZE
XRFDC_NUM_INST_SIZE
XRFDC_CONFIG_DATA_SIZE
XRFDC_REGION_SIZE
XRFDC_IP_BASE
XRFDC_DRP_BASE
XRFDC_CTRL_STS_BASE
XRFDC_BLOCK_BASE
XRFDC_ADC_TILE
XRFDC_DAC_TILE
XRFDC_TILE_ID_MAX
XRFDC_BLOCK_ID_MAX
XRFDC_EVNT_SRC_IMMEDIATE
XRFDC_EVNT_SRC_SLICE
XRFDC_EVNT_SRC_TILE
XRFDC_EVNT_SRC_SYSREF
XRFDC_EVNT_SRC_MARKER
XRFDC_EVNT_SRC_PL
XRFDC_EVENT_MIXER
XRFDC_EVENT_CRSE_DLY
XRFDC_EVENT_QMC
XRFDC_SELECT_ALL_TILES
XRFDC_ADC_4GSPS
XRFDC_CRSE_DLY_MAX
XRFDC_CRSE_DLY_MAX_EXT
XRFDC_NCO_FREQ_MULTIPLIER
XRFDC_NCO_PHASE_MULTIPLIER
XRFDC_QMC_PHASE_MULT
XRFDC_QMC_GAIN_MULT
XRFDC_DATA_TYPE_IQ
XRFDC_DATA_TYPE_REAL
XRFDC_TRSHD_OFF
XRFDC_TRSHD_STICKY_OVER
XRFDC_TRSHD_STICKY_UNDER
XRFDC_TRSHD_HYSTERISIS
XRFDC_MIXER_MODE_OFF
XRFDC_MIXER_MODE_C2C
XRFDC_MIXER_MODE_C2R
XRFDC_MIXER_MODE_R2C
XRFDC_MIXER_MODE_R2R
XRFDC_I_IQ_COS_MINSIN
XRFDC_Q_IQ_SIN_COS
XRFDC_EN_I_IQ
XRFDC_EN_Q_IQ
XRFDC_MIXER_TYPE_COARSE
XRFDC_MIXER_TYPE_FINE
XRFDC_MIXER_TYPE_OFF
XRFDC_MIXER_TYPE_DISABLED
XRFDC_COARSE_MIX_OFF
XRFDC_COARSE_MIX_SAMPLE_FREQ_BY_TWO
XRFDC_COARSE_MIX_SAMPLE_FREQ_BY_FOUR
XRFDC_COARSE_MIX_MIN_SAMPLE_FREQ_BY_FOUR
XRFDC_COARSE_MIX_BYPASS
XRFDC_COARSE_MIX_MODE_C2C_C2R
XRFDC_COARSE_MIX_MODE_R2C
XRFDC_CRSE_MIX_OFF
XRFDC_CRSE_MIX_BYPASS
XRFDC_CRSE_4GSPS_ODD_FSBYTWO
XRFDC_CRSE_MIX_I_ODD_FSBYFOUR
XRFDC_CRSE_MIX_Q_ODD_FSBYFOUR
XRFDC_CRSE_MIX_I_Q_FSBYTWO
XRFDC_CRSE_MIX_I_FSBYFOUR
XRFDC_CRSE_MIX_Q_FSBYFOUR
XRFDC_CRSE_MIX_I_MINFSBYFOUR
XRFDC_CRSE_MIX_Q_MINFSBYFOUR
XRFDC_CRSE_MIX_R_I_FSBYFOUR
XRFDC_CRSE_MIX_R_Q_FSBYFOUR
XRFDC_CRSE_MIX_R_I_MINFSBYFOUR
XRFDC_CRSE_MIX_R_Q_MINFSBYFOUR
XRFDC_MIXER_SCALE_AUTO
XRFDC_MIXER_SCALE_1P0
XRFDC_MIXER_SCALE_0P7
XRFDC_MIXER_PHASE_OFFSET_UP_LIMIT
XRFDC_MIXER_PHASE_OFFSET_LOW_LIMIT
XRFDC_UPDATE_THRESHOLD_0
XRFDC_UPDATE_THRESHOLD_1
XRFDC_UPDATE_THRESHOLD_BOTH
XRFDC_THRESHOLD_CLRMD_MANUAL_CLR
XRFDC_THRESHOLD_CLRMD_AUTO_CLR
XRFDC_DECODER_MAX_SNR_MODE
XRFDC_DECODER_MAX_LINEARITY_MODE
XRFDC_OUTPUT_CURRENT_32MA
XRFDC_OUTPUT_CURRENT_20MA
XRFDC_MIXER_MODE_IQ
XRFDC_ADC_MIXER_MODE_IQ
XRFDC_DAC_MIXER_MODE_REAL
XRFDC_ODD_NYQUIST_ZONE
XRFDC_EVEN_NYQUIST_ZONE
XRFDC_INTERP_DECIM_OFF
XRFDC_INTERP_DECIM_1X
XRFDC_INTERP_DECIM_2X
XRFDC_INTERP_DECIM_3X
XRFDC_INTERP_DECIM_4X
XRFDC_INTERP_DECIM_5X
XRFDC_INTERP_DECIM_6X
XRFDC_INTERP_DECIM_8X
XRFDC_INTERP_DECIM_10X
XRFDC_INTERP_DECIM_12X
XRFDC_INTERP_DECIM_16X
XRFDC_INTERP_DECIM_20X
XRFDC_INTERP_DECIM_24X
XRFDC_INTERP_DECIM_40X
XRFDC_FAB_CLK_DIV1
XRFDC_FAB_CLK_DIV2
XRFDC_FAB_CLK_DIV4
XRFDC_FAB_CLK_DIV8
XRFDC_FAB_CLK_DIV16
XRFDC_CALIB_MODE_AUTO
XRFDC_CALIB_MODE1
XRFDC_CALIB_MODE2
XRFDC_CALIB_MODE_MIXED
XRFDC_CALIB_MODE_ABS_DIFF
XRFDC_CALIB_MODE_NEG_ABS_SUM
XRFDC_TI_DCB_MODE1_4GSPS
XRFDC_TI_DCB_MODE1_2GSPS
XRFDC_PLL_UNLOCKED
XRFDC_PLL_LOCKED
XRFDC_EXTERNAL_CLK
XRFDC_INTERNAL_PLL_CLK
PLL_FPDIV_MIN
PLL_FPDIV_MAX
PLL_DIVIDER_MIN
PLL_DIVIDER_MIN_GEN3
PLL_DIVIDER_MAX
VCO_RANGE_MIN
VCO_RANGE_MAX
VCO_RANGE_ADC_MIN
VCO_RANGE_ADC_MAX
VCO_RANGE_DAC_MIN
VCO_RANGE_DAC_MAX
XRFDC_PLL_LPF1_VAL
XRFDC_PLL_CRS2_VAL
XRFDC_VCO_UPPER_BAND
XRFDC_VCO_LOWER_BAND
XRFDC_REF_CLK_DIV_1
XRFDC_REF_CLK_DIV_2
XRFDC_REF_CLK_DIV_3
XRFDC_REF_CLK_DIV_4
XRFDC_SINGLEBAND_MODE
XRFDC_MULTIBAND_MODE_2X
XRFDC_MULTIBAND_MODE_4X
XRFDC_MB_DATATYPE_C2C
XRFDC_MB_DATATYPE_R2C
XRFDC_MB_DATATYPE_C2R
XRFDC_MB_DUAL_BAND
XRFDC_MB_QUAD_BAND
XRFDC_SB_C2C_BLK0
XRFDC_SB_C2C_BLK1
XRFDC_SB_C2R
XRFDC_MB_C2C_BLK0
XRFDC_MB_C2C_BLK1
XRFDC_MB_C2R_BLK0
XRFDC_MB_C2R_BLK1
XRFDC_MIXER_MODE_BYPASS
XRFDC_LINK_COUPLING_DC
XRFDC_LINK_COUPLING_AC
XRFDC_MB_MODE_SB
XRFDC_MB_MODE_2X_BLK01
XRFDC_MB_MODE_2X_BLK23
XRFDC_MB_MODE_2X_BLK01_BLK23
XRFDC_MB_MODE_4X
XRFDC_MB_MODE_2X_BLK01_BLK23_ALT
XRFDC_MILLI
XRFDC_MICRO
XRFDC_DAC_SAMPLING_MIN
XRFDC_DAC_SAMPLING_MAX
XRFDC_ADC_4G_SAMPLING_MIN
XRFDC_ADC_4G_SAMPLING_MAX
XRFDC_ADC_2G_SAMPLING_MIN
XRFDC_ADC_2G_SAMPLING_MAX
XRFDC_REFFREQ_MIN
XRFDC_REFFREQ_MAX
XRFDC_DIGITALPATH_ENABLE
XRFDC_ANALOGPATH_ENABLE
XRFDC_BLK_ID0
XRFDC_BLK_ID1
XRFDC_BLK_ID2
XRFDC_BLK_ID3
XRFDC_BLK_ID4
XRFDC_BLK_ID_NONE
XRFDC_BLK_ID_ALL
XRFDC_BLK_ID_INV
XRFDC_TILE_ID0
XRFDC_TILE_ID1
XRFDC_TILE_ID2
XRFDC_TILE_ID3
XRFDC_TILE_ID4
XRFDC_TILE_ID_INV
XRFDC_NUM_OF_BLKS1
XRFDC_NUM_OF_BLKS2
XRFDC_NUM_OF_BLKS3
XRFDC_NUM_OF_BLKS4
XRFDC_NUM_OF_TILES1
XRFDC_NUM_OF_TILES2
XRFDC_NUM_OF_TILES3
XRFDC_NUM_OF_TILES4
XRFDC_SM_STATE0
XRFDC_SM_STATE1
XRFDC_SM_STATE3
XRFDC_SM_STATE7
XRFDC_SM_STATE15
XRFDC_STATE_OFF
XRFDC_STATE_SHUTDOWN
XRFDC_STATE_PWRUP
XRFDC_STATE_CLK_DET
XRFDC_STATE_CAL
XRFDC_STATE_FULL
XRFDC_DECIM_4G_DATA_TYPE
XRFDC_DECIM_2G_IQ_DATA_TYPE
XRFDC_DAC_MAX_WR_FAB_RATE
XRFDC_ADC_MAX_RD_FAB_RATE
XRFDC_MIN_PHASE_CORR_FACTOR
XRFDC_MAX_PHASE_CORR_FACTOR
XRFDC_MAX_GAIN_CORR_FACTOR
XRFDC_MIN_GAIN_CORR_FACTOR
XRFDC_FAB_RATE_16
XRFDC_FAB_RATE_8
XRFDC_FAB_RATE_4
XRFDC_FAB_RATE_2
XRFDC_FAB_RATE_1
XRFDC_HSCOM_PWR_STATS_PLL
XRFDC_HSCOM_PWR_STATS_EXTERNAL
XRFDC_HSCOM_PWR_STATS_RX_EXT
XRFDC_HSCOM_PWR_STATS_DIST_EXT
XRFDC_HSCOM_PWR_STATS_RX_PLL
XRFDC_HSCOM_PWR_STATS_DIST_PLL
XRFDC_HSCOM_PWR_STATS_RX_EXT_DIV
XRFDC_HSCOM_PWR_STATS_DIST_EXT_DIV
XRFDC_HSCOM_PWR_STATS_DIST_EXT_SRC
XRFDC_HSCOM_PWR_STATS_DIST_EXT_DIV_SRC
XRFDC_CLK_DST_TILE_231
XRFDC_CLK_DST_TILE_230
XRFDC_CLK_DST_TILE_229
XRFDC_CLK_DST_TILE_228
XRFDC_CLK_DST_TILE_227
XRFDC_CLK_DST_TILE_226
XRFDC_CLK_DST_TILE_225
XRFDC_CLK_DST_TILE_224
XRFDC_CLK_DST_INVALID
XRFDC_GLBL_OFST_DAC
XRFDC_GLBL_OFST_ADC
XRFDC_TILE_GLBL_ADDR
XRFDC_CLK_DISTR_MUX4A_SRC_INT
XRFDC_CLK_DISTR_MUX4A_SRC_STH
XRFDC_CLK_DISTR_MUX6_SRC_OFF
XRFDC_CLK_DISTR_MUX6_SRC_INT
XRFDC_CLK_DISTR_MUX6_SRC_NTH
XRFDC_CLK_DISTR_MUX7_SRC_OFF
XRFDC_CLK_DISTR_MUX7_SRC_STH
XRFDC_CLK_DISTR_MUX7_SRC_INT
XRFDC_CLK_DISTR_MUX8_SRC_NTH
XRFDC_CLK_DISTR_MUX8_SRC_INT
XRFDC_CLK_DISTR_MUX9_SRC_NTH
XRFDC_CLK_DISTR_MUX9_SRC_INT
XRFDC_CLK_DISTR_MUX5A_SRC_PLL
XRFDC_CLK_DISTR_MUX5A_SRC_RX
XRFDC_CLK_DISTR_OFF
XRFDC_CLK_DISTR_LEFTMOST_TILE
XRFDC_CLK_DISTR_CONT_LEFT_EVEN
XRFDC_CLK_DISTR_CONT_LEFT_ODD
XRFDC_CLK_DISTR_RIGHTMOST_TILE
XRFDC_CLK_DISTR_CONT_RIGHT_EVEN
XRFDC_CLK_DISTR_CONT_RIGHT_HWL_ODD
XRFDC_CLK_DISTR_MUX4A_SRC_CLR
XRFDC_CLK_DISTR_MUX6_SRC_CLR
XRFDC_CLK_DISTR_MUX7_SRC_CLR
XRFDC_CLK_DISTR_MUX8_SRC_CLR
XRFDC_CLK_DISTR_MUX9_SRC_CLR
XRFDC_DIST_MAX
XRFDC_NET_CTRL_CLK_REC_PLL
XRFDC_NET_CTRL_CLK_REC_DIST_T1
XRFDC_NET_CTRL_CLK_T1_SRC_LOCAL
XRFDC_NET_CTRL_CLK_T1_SRC_DIST
XRFDC_NET_CTRL_CLK_INPUT_DIST
XRFDC_DIST_CTRL_TO_PLL_DIV
XRFDC_DIST_CTRL_TO_T1
XRFDC_DIST_CTRL_DIST_SRC_LOCAL
XRFDC_DIST_CTRL_DIST_SRC_PLL
XRFDC_DIST_CTRL_CLK_T1_SRC_LOCAL
XRFDC_PLLREFDIV_INPUT_OFF
XRFDC_PLLREFDIV_INPUT_DIST
XRFDC_PLLREFDIV_INPUT_FABRIC
XRFDC_PLLOPDIV_INPUT_DIST_LOCAL
XRFDC_TILE_SOURCE_RX
XRFDC_TILE_SOURCE_DIST
XRFDC_TILE_SOURCE_FABRIC
XRFDC_DIST_OUT_NONE
XRFDC_DIST_OUT_RX
XRFDC_DIST_OUT_OUTDIV
XRFDC_PLL_SOURCE_NONE
XRFDC_PLL_SOURCE_RX
XRFDC_PLL_SOURCE_OUTDIV
XRFDC_PLL_OUTDIV_MODE_1
XRFDC_PLL_OUTDIV_MODE_2
XRFDC_PLL_OUTDIV_MODE_3
XRFDC_PLL_OUTDIV_MODE_N
XRFDC_PLL_OUTDIV_MODE_3_VAL
XRFDC_DIVISION_FACTOR_MIN
XRFDC_DITH_ENABLE
XRFDC_DITH_DISABLE
XRFDC_SIGDET_MODE_AVG
XRFDC_SIGDET_MODE_RNDM
XRFDC_SIGDET_TC_2_0
XRFDC_SIGDET_TC_2_2
XRFDC_SIGDET_TC_2_4
XRFDC_SIGDET_TC_2_8
XRFDC_SIGDET_TC_2_12
XRFDC_SIGDET_TC_2_14
XRFDC_SIGDET_TC_2_16
XRFDC_SIGDET_TC_2_18
XRFDC_DISABLED
XRFDC_ENABLED
XRFDC_ES1_SI
XRFDC_PROD_SI
XRFDC_CAL_BLOCK_OCB1
XRFDC_CAL_BLOCK_OCB2
XRFDC_CAL_BLOCK_GCB
XRFDC_CAL_BLOCK_TSCB
XRFDC_TSCB_TUNE_AUTOCAL
XRFDC_TSCB_TUNE_NOT_AUTOCAL
XRFDC_INV_SYNC_MODE_MAX
XRFDC_INV_SYNC_EN_MAX
XRFDC_CTRL_MASK
XRFDC_EXPORTCTRL_CLKDIST
XRFDC_PREMIUMCTRL_CLKDIST
XRFDC_EXPORTCTRL_VOP
XRFDC_EXPORTCTRL_DSA
XRFDC_DATAPATH_MODE_DUC_0_FSDIVTWO
XRFDC_DATAPATH_MODE_DUC_0_FSDIVFOUR
XRFDC_DATAPATH_MODE_FSDIVFOUR_FSDIVTWO
XRFDC_DATAPATH_MODE_NODUC_0_FSDIVTWO
XRFDC_DAC_INT_MODE_FULL_BW
XRFDC_DAC_INT_MODE_HALF_BW_IMR
XRFDC_DAC_INT_MODE_FULL_BW_BYPASS
XRFDC_DAC_MODE_MAX
XRFDC_FULL_BW_DIVISOR
XRFDC_HALF_BW_DIVISOR
XRFDC_DAC_IMR_MODE_LOWPASS
XRFDC_DAC_IMR_MODE_HIGHPASS
XRFDC_DAC_IMR_MODE_MAX
XRFDC_CLOCK_DETECT_CLK
XRFDC_CLOCK_DETECT_DIST
XRFDC_CLOCK_DETECT_BOTH
XRFDC_CAL_UNFREEZE_CALIB
XRFDC_CAL_FREEZE_CALIB
XRFDC_CAL_FRZ_PIN_ENABLE
XRFDC_CAL_FRZ_PIN_DISABLE
XRFDC_CLK_REG_EN_MASK
XRFDC_GEN1_LOW_I
XRFDC_GEN1_HIGH_I
XRFDC_MAX_ATTEN
XRFDC_MIN_ATTEN
XRFDC_STEP_ATTEN
XRFDC_DAC_VOP_CTRL_REG_UPDT_MASK
XRFDC_DAC_VOP_CTRL_TST_BLD_MASK
XRFDC_DAC_VOP_BLDR_LOW_BITS_MASK
XRFDC_PLL_LOCK_DLY_CNT
XRFDC_RESTART_CLR_DLY_CNT
XRFDC_WAIT_ATTEMPTS_CNT
XRFDC_STATE_WAIT
XRFDC_RESTART_CLR_WAIT
XRFDC_PLL_LOCK_WAIT
XRFDC_CLK_DIV_DP_FIRST_MODE
XRFDC_CLK_DIV_DP_OTHER_MODES
XRFDC_TILE_STARTED
XRFDC_SI_REV_ES
XRFDC_SI_REV_PROD
XRFDC_CG_WAIT_CYCLES
XRFDC_ADC_CG_WAIT_CYCLES
XRFDC_CG_CYCLES_TOTAL_X1_X2_X4_X8
XRFDC_CG_CYCLES_KEPT_X1_X2_X4_X8
XRFDC_CG_CYCLES_TOTAL_X3_X6_X12
XRFDC_CG_CYCLES_KEPT_X3_X6_X12
XRFDC_CG_CYCLES_TOTAL_X5_X10
XRFDC_CG_CYCLES_KEPT_X5_X10
XRFDC_CG_CYCLES_TOTAL_X16
XRFDC_CG_CYCLES_KEPT_X16
XRFDC_CG_CYCLES_TOTAL_X20
XRFDC_CG_CYCLES_KEPT_X20
XRFDC_CG_CYCLES_TOTAL_X24
XRFDC_CG_CYCLES_KEPT_X24
XRFDC_CG_CYCLES_TOTAL_X40
XRFDC_CG_CYCLES_KEPT_X40
XRFDC_CG_FIXED_OFS
XRFDC_FIFO_CHANNEL_ACT
XRFDC_FIFO_CHANNEL_OBS
XRFDC_FIFO_CHANNEL_BOTH
XRFDC_PWR_MODE_OFF
XRFDC_PWR_MODE_ON
XRFDC_DUAL_TILE
XRFDC_QUAD_TILE
XRFDC_4ADC_4DAC_TILES
XRFDC_3ADC_2DAC_TILES
XRFDC_MTS_SYSREF_DISABLE
XRFDC_MTS_SYSREF_ENABLE
XRFDC_MTS_SCAN_INIT
XRFDC_MTS_SCAN_RELOAD
XRFDC_MTS_OK
XRFDC_MTS_NOT_SUPPORTED
XRFDC_MTS_TIMEOUT
XRFDC_MTS_MARKER_RUN
XRFDC_MTS_MARKER_MISM
XRFDC_MTS_DELAY_OVER
XRFDC_MTS_TARGET_LOW
XRFDC_MTS_IP_NOT_READY
XRFDC_MTS_DTC_INVALID
XRFDC_MTS_NOT_ENABLED
XRFDC_MTS_SYSREF_GATE_ERROR
XRFDC_MTS_SYSREF_FREQ_NDONE
XRFDC_MTS_BAD_REF_TILE
XRFDC_CAL_AXICLK_MULT
XRFDC_CAL_DIV_CUTOFF_FREQ
XRFDC_DAC_LINK_COUPLING_AC
XRFDC_VOP_ES1_AC_MIN_UA
XRFDC_VOP_ES1_AC_MAX_UA
XRFDC_VOP_AC_MIN_UA
XRFDC_VOP_AC_MAX_UA
XRFDC_VOP_DC_MIN_UA
XRFDC_VOP_DC_MAX_UA
XRFDC_MIN_I_UA_INT
XRFDC_STEP_I_UA
XRFDC_BLDR_GAIN
XRFDC_CSCAS_BLDR
XRFDC_OPCAS_BIAS
XRFDC_MAX_DLY_INIT
XRFDC_MIN_DLY_INIT
XRFDC_DLY_UNIT
XRFDC_MAX_DISTRS
XRFDC_IXR_FIFOUSRDAT_MASK
XRFDC_DAC_IXR_FIFOUSRDAT_SUPP_MASK
XRFDC_DAC_IXR_FIFOUSRDAT_MASK
XRFDC_IXR_FIFOUSRDAT_OBS_MASK
XRFDC_IXR_FIFOUSRDAT_OF_MASK
XRFDC_IXR_FIFOUSRDAT_UF_MASK
XRFDC_IXR_FIFOMRGNIND_OF_MASK
XRFDC_IXR_FIFOMRGNIND_UF_MASK
XRFDC_DAC_IXR_FIFOACTIND_OF_MASK
XRFDC_DAC_IXR_FIFOACTIND_UF_MASK
XRFDC_ADC_IXR_DATAPATH_MASK
XRFDC_ADC_IXR_DMON_STG_MASK
XRFDC_DAC_IXR_DATAPATH_MASK
XRFDC_DAC_IXR_INTP_STG_MASK
XRFDC_DAC_IXR_INTP_I_STG0_MASK
XRFDC_DAC_IXR_INTP_I_STG1_MASK
XRFDC_DAC_IXR_INTP_I_STG2_MASK
XRFDC_DAC_IXR_INTP_Q_STG0_MASK
XRFDC_DAC_IXR_INTP_Q_STG1_MASK
XRFDC_DAC_IXR_INTP_Q_STG2_MASK
XRFDC_ADC_IXR_DMON_I_STG0_MASK
XRFDC_ADC_IXR_DMON_I_STG1_MASK
XRFDC_ADC_IXR_DMON_I_STG2_MASK
XRFDC_ADC_IXR_DMON_Q_STG0_MASK
XRFDC_ADC_IXR_DMON_Q_STG1_MASK
XRFDC_ADC_IXR_DMON_Q_STG2_MASK
XRFDC_IXR_QMC_GAIN_PHASE_MASK
XRFDC_IXR_QMC_OFFST_MASK
XRFDC_DAC_IXR_INVSNC_OF_MASK
XRFDC_DAC_IXR_MXR_HLF_I_MASK
XRFDC_DAC_IXR_MXR_HLF_Q_MASK
XRFDC_DAC_IXR_DP_SCALE_MASK
XRFDC_DAC_IXR_INTP_I_STG3_MASK
XRFDC_DAC_IXR_INTP_Q_STG3_MASK
XRFDC_DAC_IXR_IMR_OV_MASK
XRFDC_DAC_IXR_INV_SINC_EVEN_NYQ_MASK
XRFDC_SUBADC_IXR_DCDR_MASK
XRFDC_SUBADC0_IXR_DCDR_OF_MASK
XRFDC_SUBADC0_IXR_DCDR_UF_MASK
XRFDC_SUBADC1_IXR_DCDR_OF_MASK
XRFDC_SUBADC1_IXR_DCDR_UF_MASK
XRFDC_SUBADC2_IXR_DCDR_OF_MASK
XRFDC_SUBADC2_IXR_DCDR_UF_MASK
XRFDC_SUBADC3_IXR_DCDR_OF_MASK
XRFDC_SUBADC3_IXR_DCDR_UF_MASK
XRFDC_ADC_OVR_VOLTAGE_MASK
XRFDC_COMMON_MASK
XRFDC_ADC_OVR_RANGE_MASK
XRFDC_ADC_CMODE_OVR_MASK
XRFDC_ADC_CMODE_UNDR_MASK
XRFDC_ADC_DAT_OVR_MASK
XRFDC_DAT_OVR_MASK
XRFDC_ADC_FIFO_OVR_MASK
XRFDC_FIFO_OVR_MASK
XRFDC_DAC_MC_CFG2_OPCSCAS_MASK
XRFDC_DAC_MC_CFG2_BLDGAIN_MASK
XRFDC_DAC_MC_CFG3_CSGAIN_MASK
XRFDC_DAC_MC_CFG2_OPCSCAS_20MA
XRFDC_DAC_MC_CFG3_CSGAIN_20MA
XRFDC_DAC_MC_CFG2_OPCSCAS_32MA
XRFDC_DAC_MC_CFG3_CSGAIN_32MA
XRFDC_DAC_MC_CFG2_GEN1_COMP_MASK
XRFDC_DAC_MC_CFG3_OPT_LUT_MASK
XRFDC_DAC_MC_CFG3_OPT_MASK
XRFDC_DAC_MC_CFG3_UPDATE_MASK
XRFDC_DAC_MC_CFG0_CAS_BLDR_MASK
XRFDC_DAC_MC_CFG2_CAS_BIAS_MASK
XRFDC_ADC_DSA_RTS_PIN_MASK
XRFDC_ADC_DSA_CODE_MASK
XRFDC_ADC_DSA_UPDT_MASK
XRFDC_DAC_MC_CFG2_BLDGAIN_SHIFT
XRFDC_DAC_MC_CFG3_CSGAIN_SHIFT
XRFDC_DAC_MC_CFG3_OPT_LUT_SHIFT
XRFDC_ADC_OVR_VOL_RANGE_SHIFT
XRFDC_ADC_DAT_FIFO_OVR_SHIFT
XRFDC_DAT_FIFO_OVR_SHIFT
XRFDC_ADC_SUBADC_DCDR_SHIFT
XRFDC_IXR_FIFOUSRDAT_OBS_SHIFT
XRFDC_DAC_IXR_FIFOUSRDAT_SUPP_SHIFT
XRFDC_DATA_PATH_SHIFT
XRFDC_ADC_CMODE_SHIFT
XRFDC_COMMON_SHIFT
XRFDC_DAC_MC_CFG2_GEN1_COMP_SHIFT
XRFDC_ADC_DSA_RTS_PIN_SHIFT
XRFDC_DAC_TILE_DRP_ADDR
XRFDC_DAC_TILE_CTRL_STATS_ADDR
XRFDC_ADC_TILE_DRP_ADDR
XRFDC_ADC_TILE_CTRL_STATS_ADDR
XRFDC_CTRL_STATS_OFFSET
XRFDC_HSCOM_ADDR
XRFDC_BLOCK_ADDR_OFFSET
XRFDC_TILE_DRP_OFFSET
XRFdc_In64
XRFdc_Out64
XRFdc_In32
XRFdc_Out32
XRFdc_In16
XRFdc_Out16
XRFdc_In8
XRFdc_Out8
XRFdc_ReadReg64
Read a register.
InstancePtr is a pointer to the XRfdc instance. BaseAddress contains the base address of the device. RegOffset contains the offset from the 1st register of the device to the target register. The value read from the register. C-Style signature: u32 XRFdc_ReadReg64(XRFdc *InstancePtr. u32 BaseAddress, s32 RegOffset)
XRFdc_WriteReg64
Write to a register.
InstancePtr is a pointer to the XRfdc instance. BaseAddress contains the base address of the device. RegOffset contains the offset from the 1st register of the device to target register. RegisterValue is the value to be written to the register. None.C-Style signature: void XRFdc_WriteReg64(XRFdc *InstancePtr, u32 BaseAddress, s32 RegOffset, u64 RegisterValue)
XRFdc_ReadReg
Read a register.
InstancePtr is a pointer to the XRfdc instance. BaseAddress contains the base address of the device. RegOffset contains the offset from the 1st register of the device to the target register. The value read from the register. C-Style signature: u32 XRFdc_ReadReg(XRFdc *InstancePtr, u32 BaseAddress. int RegOffset)
Referenced by XRFdc_CheckTileEnabled, XRFdc_CustomStartUp, XRFdc_DynamicPLLConfig, XRFdc_GetConnectedIQData, XRFdc_GetCoupling, XRFdc_GetEnabledInterrupts, XRFdc_GetIntrStatus, XRFdc_GetMTSEnable, XRFdc_GetMultibandConfig, XRFdc_GetPLLConfig, XRFdc_IntrDisable, XRFdc_IntrEnable, XRFdc_IsADCBlockEnabled, XRFdc_IsADCDigitalPathEnabled, XRFdc_IsDACBlockEnabled, XRFdc_IsDACDigitalPathEnabled, XRFdc_MultiConverter_Sync, XRFdc_SetDACVOP.
XRFdc_WriteReg
Write to a register.
InstancePtr is a pointer to the XRfdc instance. BaseAddress contains the base address of the device. RegOffset contains the offset from the 1st register of the device to target register. RegisterValue is the value to be written to the register. None.C-Style signature: void XRFdc_WriteReg(XRFdc *InstancePtr, u32 BaseAddress, int RegOffset, u32 RegisterValue)
Referenced by XRFdc_CustomStartUp, XRFdc_DynamicPLLConfig, XRFdc_IntrClr, XRFdc_IntrDisable, XRFdc_IntrEnable, XRFdc_SetClkDistribution.
XRFdc_ReadReg16
Read a register.
InstancePtr is a pointer to the XRfdc instance. BaseAddress contains the base address of the device. RegOffset contains the offset from the 1st register of the device to the target register. The value read from the register. C-Style signature: u16 XRFdc_ReadReg16(XRFdc *InstancePtr, u32 BaseAddress. int RegOffset)
Referenced by XRFdc_ClrReg, XRFdc_ClrSetReg, XRFdc_DynamicPLLConfig, XRFdc_GetClkDistribution, XRFdc_GetClockSource, XRFdc_GetCoarseDelaySettings, XRFdc_GetDSA, XRFdc_GetEnabledInterrupts, XRFdc_GetIntrStatus, XRFdc_GetIPStatus, XRFdc_GetMixerSettings, XRFdc_GetPLLConfig, XRFdc_GetSignalDetector, XRFdc_GetThresholdSettings, XRFdc_IntrEnable, XRFdc_IntrHandler, XRFdc_RDReg, XRFdc_SetCalibrationMode, XRFdc_SetInterpolationFactor, XRFdc_SetMixerSettings, XRFdc_SetNyquistZone, XRFdc_SetThresholdClrMode.
XRFdc_WriteReg16
Write to a register.
InstancePtr is a pointer to the XRfdc instance. BaseAddress contains the base address of the device. RegOffset contains the offset from the 1st register of the device to target register. RegisterValue is the value to be written to the register. None.C-Style signature: void XRFdc_WriteReg16(XRFdc *InstancePtr, u32 BaseAddress, int RegOffset, u16 RegisterValue)
Referenced by XRFdc_ClrReg, XRFdc_ClrSetReg, XRFdc_DynamicPLLConfig, XRFdc_IntrClr, XRFdc_IntrEnable, XRFdc_SetCalibrationMode, XRFdc_SetMixerSettings, XRFdc_SetNyquistZone, XRFdc_SetSignalDetector, XRFdc_SetThresholdClrMode, XRFdc_SetThresholdSettings, XRFdc_UpdateEvent.
XRFdc_ReadReg8
Read a register.
InstancePtr is a pointer to the XRfdc instance. BaseAddress contains the base address of the device. RegOffset contains the offset from the 1st register of the device to the target register. The value read from the register. C-Style signature: u8 XRFdc_ReadReg8(XRFdc *InstancePtr, u32 BaseAddress. int RegOffset)
XRFdc_WriteReg8
Write to a register.
InstancePtr is a pointer to the XRfdc instance. BaseAddress contains the base address of the device. RegOffset contains the offset from the 1st register of the device to target register. RegisterValue is the value to be written to the register. None.C-Style signature: void XRFdc_WriteReg8(XRFdc *InstancePtr, u32 BaseAddress, int RegOffset, u8 RegisterValue)
XRFDC_MTS_NUM_DTC
XRFDC_MTS_REF_TARGET
XRFDC_MTS_MAX_CODE
XRFDC_MTS_MIN_GAP_T1
XRFDC_MTS_MIN_GAP_GEN3
XRFDC_MTS_MIN_GAP_PLL
XRFDC_MTS_SR_TIMEOUT
XRFDC_MTS_DTC_COUNT
XRFDC_MTS_MARKER_COUNT
XRFDC_MTS_SRCOUNT_TIMEOUT
XRFDC_MTS_DELAY_MAX
XRFDC_MTS_CHECK_ALL_FIFOS
XRFDC_MTS_SRCAP_T1_EN
XRFDC_MTS_SRCAP_T1_RST
XRFDC_MTS_SRFLAG_T1
XRFDC_MTS_SRFLAG_PLL
XRFDC_MTS_FIFO_DEFAULT
XRFDC_MTS_FIFO_ENABLE
XRFDC_MTS_FIFO_DISABLE
XRFDC_MTS_AMARK_LOC_S
XRFDC_MTS_AMARK_DONE_S
XRFDC_MTS_DLY_ALIGNER0
XRFDC_MTS_DLY_ALIGNER1
XRFDC_MTS_DLY_ALIGNER2
XRFDC_MTS_DLY_ALIGNER3
XRFDC_MTS_DIR_FIFO_PTR
XRFDC_MTS_DAC_MARKER_LOC_MASK
XRFDC_MTS_RMW
XRFDC_MTS_FIELD