xrfdc_dp.c
static void XRFdc_IntResetInternalFIFOWidth(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 Channel)
Set the correct FIFO width for current mixer & rate change settings (int).
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id Valid values are 0-3. Channel Valid values are 0 for actual FIFO 1 for obs FIFO. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Common API for ADC/DAC blocks
static u32 XRFdc_SetDecimationFactorInt(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 DecimationFactor, u32 Channel)
This function is to set the decimation factor and also update the FIFO write words w.r.t to decimation factor for both the actual and observtion FIFOs.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. DecimationFactor to be set for DAC block. XRFDC_INTERP_DECIM_* defines the valid values. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only ADC blocks
u32 XRFdc_SetDecimationFactor(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 DecimationFactor)
This API is to set the decimation factor and also update the FIFO write words w.r.t to decimation factor.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. DecimationFactor to be set for DAC block. XRFDC_INTERP_DECIM_* defines the valid values. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only ADC blocks
u32 XRFdc_SetDecimationFactorObs(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 DecimationFactor)
This API is to set the decimation factor and also update the FIFO write words w.r.t to decimation factor for the observation FIFO.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. DecimationFactor to be set for DAC block. XRFDC_INTERP_DECIM_* defines the valid values. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only ADC blocks
u32 XRFdc_UpdateEvent(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 Event)
This function will trigger the update event for an event.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Event is for which dynamic update event will trigger. XRFDC_EVENT_* defines the different events. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Common API for ADC/DAC blocks
References XRFDC_ADC_CRSE_DLY_UPDT_OFFSET, XRFDC_ADC_UPDATE_DYN_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_CheckDigitalPathEnabled, XRFDC_DAC_CRSE_DLY_UPDT_OFFSET, XRFDC_DAC_UPDATE_DYN_OFFSET, XRFDC_HSCOM_UPDT_DYN_OFFSET, XRFdc_IsHighSpeedADC, XRFDC_NCO_UPDT_MODE_MASK, XRFDC_NCO_UPDT_OFFSET, XRFDC_QMC_UPDT_MODE_MASK, XRFDC_QMC_UPDT_OFFSET, XRFdc_RDReg, XRFdc_WriteReg16.
u32 XRFdc_SetInterpolationFactor(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 InterpolationFactor)
This API is to set the interpolation factor and also update the FIFO read words w.r.t to interpolation factor.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. InterpolationFactor to be set for DAC block. XRFDC_INTERP_DECIM_* defines the valid values. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only DAC blocks
References XRFdc_CheckDigitalPathEnabled, XRFdc_ClrSetReg, XRFDC_DAC_DATAPATH_OFFSET, XRFDC_DAC_FIFO_DELAY_MASK, XRFDC_DAC_FIFO_START_OFFSET, XRFDC_DAC_INTERP_CTRL_OFFSET, XRFDC_DAC_ITERP_DATA_OFFSET, XRFDC_DATAPATH_MODE_MASK, XRFDC_INTERP_MODE_MASK, XRFDC_INTERP_MODE_MASK_EXT, XRFDC_INTERP_MODE_Q_SHIFT, XRFDC_INTERP_MODE_Q_SHIFT_EXT, XRFdc_RDReg, XRFdc_ReadReg16.
u32 XRFdc_GetInterpolationFactor(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *InterpolationFactorPtr)
Interpolation factor are returned back to the caller.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. InterpolationFactorPtr Pointer to return the interpolation factor for DAC blocks. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for DAC blocks
References XRFdc_CheckDigitalPathEnabled, XRFDC_DAC_INTERP_CTRL_OFFSET, XRFDC_INTERP_MODE_I_MASK, XRFDC_INTERP_MODE_I_MASK_EXT, XRFdc_RDReg.
Referenced by RFdcMTS_Example.
static u32 XRFdc_GetDecimationFactorInt(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *DecimationFactorPtr, u32 Channel)
Decimation factor are returned back to the caller for both actual and observation FIFO.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. DecimationFactorPtr Pointer to return the Decimation factor for DAC blocks. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
u32 XRFdc_GetDecimationFactor(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *DecimationFactorPtr)
Decimation factor are returned back to the caller.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. DecimationFactorPtr Pointer to return the Decimation factor for DAC blocks. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
Referenced by RFdcMTS_Example.
u32 XRFdc_GetDecimationFactorObs(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *DecimationFactorPtr)
Decimation factor are returned back to the caller for the observation FIFO.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. DecimationFactorPtr Pointer to return the Decimation factor for DAC blocks. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
u32 XRFdc_SetInvSincFIR(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u16 Mode)
This API is used to set the mode for the Inverse-Sinc filter.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is DAC block number inside the tile. Valid values are 0-3. Mode valid values are 0(disable), 1(1st Nyquist zone) and 2(2nd Nyquist zone). XRFDC_SUCCESS if successful.XRFDC_FAILURE if block not enabled/invalid mode. Only DAC blocks
References XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFDC_DAC_INVSINC_OFFSET, XRFDC_EN_INVSINC_MASK, XRFdc_GetNyquistZone, XRFDC_MODE_INVSINC_MASK.
u32 XRFdc_GetInvSincFIR(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u16 *ModePtr)
This API is used to get the Inverse-Sinc filter mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is DAC block number inside the tile. Valid values are 0-3. ModePtr is a pointer to get the inv-sinc status. valid values are 0(disable), 1(1st Nyquist zone) and 2(2nd Nyquist zone). XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only DAC blocks
References XRFdc_CheckBlockEnabled, XRFDC_DAC_INVSINC_OFFSET, XRFDC_EN_INVSINC_MASK, XRFDC_MODE_INVSINC_MASK, XRFdc_RDReg.
u32 XRFdc_IsDACDigitalPathEnabled(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id)
Checks whether DAC Digital path is enabled or not.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Return 1 if DAC digital path is enabled, otherwise 0.
References XRFDC_DAC_PATHS_ENABLED_OFFSET, XRFDC_DIGITAL_PATH_ENABLED_SHIFT, XRFDC_PATH_ENABLED_TILE_SHIFT, XRFdc_ReadReg.
Referenced by XRFdc_CheckDigitalPathEnabled.
u32 XRFdc_IsADCDigitalPathEnabled(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id)
Checks whether ADC digital path is enabled or not.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3 in DAC/ADC-2GSPS and 0-1 in ADC-4GSPS. Return 1 if ADC digital path is enabled, otherwise 0.
References XRFDC_ADC_PATHS_ENABLED_OFFSET, XRFDC_DIGITAL_PATH_ENABLED_SHIFT, XRFdc_IsHighSpeedADC, XRFDC_PATH_ENABLED_TILE_SHIFT, XRFdc_ReadReg.
Referenced by XRFdc_CheckDigitalPathEnabled.
u32 XRFdc_CheckDigitalPathEnabled(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id)
Checks whether ADC/DAC Digital path is enabled or not.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. XRFDC_SUCCESS if Digital path is enabled.XRFDC_FAILURE if Digital path is not enabled.
References XRFdc_IsADCDigitalPathEnabled, XRFdc_IsDACDigitalPathEnabled.
Referenced by XRFdc_GetCalibrationMode, XRFdc_GetConnectedIQData, XRFdc_GetDataPathMode, XRFdc_GetEnabledInterrupts, XRFdc_GetInterpolationFactor, XRFdc_GetIntrStatus, XRFdc_GetMixerSettings, XRFdc_GetNyquistZone, XRFdc_IntrClr, XRFdc_IntrDisable, XRFdc_IntrEnable, XRFdc_MultiBand, XRFdc_ResetInternalFIFOWidth, XRFdc_ResetInternalFIFOWidthObs, XRFdc_ResetNCOPhase, XRFdc_SetCalibrationMode, XRFdc_SetDataPathMode, XRFdc_SetFabWrVldWords, XRFdc_SetInterpolationFactor, XRFdc_SetMixerSettings, XRFdc_UpdateEvent.
u32 XRFdc_SetFabClkOutDiv(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u16 FabClkDiv)
This API is to set the divider for clock fabric out.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. FabClkDiv to be set for a tile. XRFDC_FAB_CLK_* defines the valid divider values. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. ADC and DAC Tiles
References XRFdc_CheckTileEnabled, XRFdc_ClrSetReg, XRFDC_FAB_CLK_DIV_MASK, XRFDC_HSCOM_CLK_DIV_OFFSET.
u32 XRFdc_GetFabClkOutDiv(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u16 *FabClkDivPtr)
This API is to get the divider for clock fabric out.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. FabClkDivPtr is a pointer to get fabric clock for a tile. XRFDC_FAB_CLK_* defines the valid divider values. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. API is applicable for both ADC and DAC Tiles
References XRFdc_CheckTileEnabled, XRFDC_FAB_CLK_DIV_MASK, XRFDC_HSCOM_CLK_DIV_OFFSET, XRFdc_RDReg.
u32 XRFdc_SetFabWrVldWords(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 FabricWrVldWords)
Fabric data rate for the requested DAC block is set by writing to the corresponding register.
The function writes the number of valid write words for the requested DAC block. InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. FabricWrVldWords is write fabric rate to be set for DAC block. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for DAC blocks
References XRFdc_CheckDigitalPathEnabled, XRFdc_ClrSetReg, XRFDC_DAC_FAB_RATE_WR_MASK, XRFDC_DAC_FABRIC_RATE_OFFSET.
static u32 XRFdc_SetFabRdVldWordsInt(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 FabricRdVldWords, u32 Channel)
Fabric data rate for the requested ADC block is set by writing to the corresponding register.
The function writes the number of valid read words for the requested ADC block. This is for both the actual and observation FIFO. InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC block number inside the tile. Valid values are 0-3. FabricRdVldWords is Read fabric rate to be set for ADC block. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
u32 XRFdc_SetFabRdVldWords(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 FabricRdVldWords)
Fabric data rate for the requested ADC block is set by writing to the corresponding register.
The function writes the number of valid read words for the requested ADC block. InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC block number inside the tile. Valid values are 0-3. FabricRdVldWords is Read fabric rate to be set for ADC block. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
u32 XRFdc_SetFabRdVldWordsObs(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 FabricRdVldWords)
Fabric data rate for the requested ADC block is set by writing to the corresponding register.
The function writes the number of valid read words for the requested ADC block. This is for the observation FIFO. InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC block number inside the tile. Valid values are 0-3. FabricRdVldWords is Read fabric rate to be set for ADC block. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
static u32 XRFdc_GetFabWrVldWordsInt(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 *FabricWrVldWordsPtr, u32 Channel)
This function returns the the number of fabric write valid words requested for the block.
For ADCs this is for both the actual and observation FIFO. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. FabricWrVldWordsPtr Pointer to return the fabric data rate for DAC block XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. ADC/DAC blocks
u32 XRFdc_GetFabWrVldWords(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 *FabricWrVldWordsPtr)
This API returns the number of fabric write valid words requested for the block.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. FabricWrVldWordsPtr Pointer to return the fabric data rate for DAC block XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. ADC/DAC blocks
u32 XRFdc_GetFabWrVldWordsObs(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 *FabricWrVldWordsPtr)
This API returns the number of fabric write valid words requested for the block.
This is for the observation FIFO. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. FabricWrVldWordsPtr Pointer to return the fabric data rate for DAC block XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. ADC blocks only
static u32 XRFdc_GetFabRdVldWordsInt(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 *FabricRdVldWordsPtr, u32 Channel)
This function returns the number of fabric read valid words requested for the block.
For ADCs this is for both the actual and observation FIFO. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. FabricRdVldWordsPtr Pointer to return the fabric data rate for ADC/DAC block XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. ADC/DAC blocks
u32 XRFdc_GetFabRdVldWords(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 *FabricRdVldWordsPtr)
This API returns the number of fabric read valid words requested for the block.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. FabricRdVldWordsPtr Pointer to return the fabric data rate for ADC/DAC block XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. ADC/DAC blocks
u32 XRFdc_GetFabRdVldWordsObs(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 *FabricRdVldWordsPtr)
This function returns the number of fabric read valid words requested for the block.
This is for the observation FIFO. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. FabricRdVldWordsPtr Pointer to return the fabric data rate for ADC/DAC block XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. ADC blocks only
static u32 XRFdc_SetupFIFOInt(XRFdc *InstancePtr, u32 Type, int Tile_Id, u8 Enable, u32 Channel)
Enable and Disable the ADC/DAC FIFO.
For ADCs this is for the actual and observtion FIFO. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Enable valid values are 1 (FIFO enable) and 0 (FIFO Disable) XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Common API for ADC/DAC blocks
u32 XRFdc_SetupFIFO(XRFdc *InstancePtr, u32 Type, int Tile_Id, u8 Enable)
Enable and Disable the ADC/DAC FIFO.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Enable valid values are 1 (FIFO enable) and 0 (FIFO Disable) XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Common API for ADC/DAC blocks
u32 XRFdc_SetupFIFOObs(XRFdc *InstancePtr, u32 Type, int Tile_Id, u8 Enable)
Enable and Disable the ADC/DAC FIFO.
For ADCs this is for the observtion FIFO. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Enable valid values are 1 (FIFO enable) and 0 (FIFO Disable) XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. ADC blocks only
u32 XRFdc_SetupFIFOBoth(XRFdc *InstancePtr, u32 Type, int Tile_Id, u8 Enable)
Enable and Disable the ADC/DAC FIFO.
Thisis for the actual and observtion FIFO. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Enable valid values are 1 (FIFO enable) and 0 (FIFO Disable) XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. ADC blocks only
u32 XRFdc_GetFIFOStatusInt(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u8 *EnablePtr, u32 Channel)
Current status of ADC/DAC FIFO.
For ADCs this is for both the actual and observations FIFOs. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. EnablePtr valid values are 1 (FIFO enable) and 0 (FIFO Disable) XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Common API for ADC/DAC blocks
References XRFdc_CheckTileEnabled, XRFDC_FIFO_EN_MASK, XRFDC_FIFO_EN_OBS_MASK, XRFDC_FIFO_EN_OBS_SHIFT, XRFDC_FIFO_ENABLE, XRFdc_RDReg.
Referenced by XRFdc_GetFIFOStatus, XRFdc_GetFIFOStatusObs.
u32 XRFdc_GetFIFOStatus(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u8 *EnablePtr)
Current status of ADC/DAC FIFO.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. EnablePtr valid values are 1 (FIFO enable) and 0 (FIFO Disable) XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Common API for ADC/DAC blocks
References XRFdc_GetFIFOStatusInt.
u32 XRFdc_GetFIFOStatusObs(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u8 *EnablePtr)
Current status of ADC/DAC FIFO.
This is for the observation FIFO. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. EnablePtr valid values are 1 (FIFO enable) and 0 (FIFO Disable) XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. ADC blocks only
References XRFdc_GetFIFOStatusInt.
u32 XRFdc_ResetInternalFIFOWidth(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id)
Set the correct FIFO width for current mixer & rate change settings.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id Valid values are 0-3. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Common API for ADC/DAC blocks
References XRFdc_CheckDigitalPathEnabled.
Referenced by XRFdc_SetMixerSettings.
u32 XRFdc_ResetInternalFIFOWidthObs(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id)
Set the correct Observation FIFO width for current mixer & rate change settings.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id Valid values are 0-3. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. ADC blocks only
References XRFdc_CheckDigitalPathEnabled.
double XRFdc_GetFabClkFreq(XRFdc *InstancePtr, u32 Type, u32 Tile_Id)
Get Fabric Clock frequency.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Return Fabric Clock frequency for ADC/DAC tile
u32 XRFdc_IsFifoEnabled(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id)
Get whether FIFO is enabled or not.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Return 1 if FIFO is enabled, otherwise 0.