xrfdc.h
XRFdc_IsADC4GSPS
XRFDC_MTS_RMW
XRFDC_MTS_FIELD
Xil_AssertNonvoid
Xil_AssertVoid
Xil_AssertVoidAlways
XRFDC_MAX
XRFDC_MIN
XRFDC_SUCCESS
XRFDC_FAILURE
XRFDC_GEN3
XRFDC_COMPONENT_IS_READY
XRFDC_NUM_SLICES_HSADC
XRFDC_NUM_SLICES_LSADC
XRFDC_PLATFORM_DEVICE_DIR
XRFDC_BUS_NAME
XRFDC_SIGNATURE
XRFDC_CONFIG_DATA_PROPERTY
XRFDC_COMPATIBLE_PROPERTY
XRFDC_NUM_INSTANCES_PROPERTY
XRFDC_COMPATIBLE_STRING
XRFDC_DEVICE_ID_SIZE
XRFDC_NUM_INST_SIZE
XRFDC_CONFIG_DATA_SIZE
XRFDC_REGION_SIZE
XRFDC_IP_BASE
XRFDC_DRP_BASE
XRFDC_CTRL_STS_BASE
XRFDC_BLOCK_BASE
XRFDC_ADC_TILE
XRFDC_DAC_TILE
XRFDC_TILE_ID_MAX
XRFDC_BLOCK_ID_MAX
XRFDC_EVNT_SRC_IMMEDIATE
XRFDC_EVNT_SRC_SLICE
XRFDC_EVNT_SRC_TILE
XRFDC_EVNT_SRC_SYSREF
XRFDC_EVNT_SRC_MARKER
XRFDC_EVNT_SRC_PL
XRFDC_EVENT_MIXER
XRFDC_EVENT_CRSE_DLY
XRFDC_EVENT_QMC
XRFDC_SELECT_ALL_TILES
XRFDC_ADC_4GSPS
XRFDC_CRSE_DLY_MAX
XRFDC_CRSE_DLY_MAX_EXT
XRFDC_NCO_FREQ_MULTIPLIER
XRFDC_NCO_PHASE_MULTIPLIER
XRFDC_QMC_PHASE_MULT
XRFDC_QMC_GAIN_MULT
XRFDC_DATA_TYPE_IQ
XRFDC_DATA_TYPE_REAL
XRFDC_TRSHD_OFF
XRFDC_TRSHD_STICKY_OVER
XRFDC_TRSHD_STICKY_UNDER
XRFDC_TRSHD_HYSTERISIS
XRFDC_MIXER_MODE_OFF
XRFDC_MIXER_MODE_C2C
XRFDC_MIXER_MODE_C2R
XRFDC_MIXER_MODE_R2C
XRFDC_MIXER_MODE_R2R
XRFDC_I_IQ_COS_MINSIN
XRFDC_Q_IQ_SIN_COS
XRFDC_EN_I_IQ
XRFDC_EN_Q_IQ
XRFDC_MIXER_TYPE_COARSE
XRFDC_MIXER_TYPE_FINE
XRFDC_MIXER_TYPE_OFF
XRFDC_MIXER_TYPE_DISABLED
XRFDC_COARSE_MIX_OFF
XRFDC_COARSE_MIX_SAMPLE_FREQ_BY_TWO
XRFDC_COARSE_MIX_SAMPLE_FREQ_BY_FOUR
XRFDC_COARSE_MIX_MIN_SAMPLE_FREQ_BY_FOUR
XRFDC_COARSE_MIX_BYPASS
XRFDC_COARSE_MIX_MODE_C2C_C2R
XRFDC_COARSE_MIX_MODE_R2C
XRFDC_CRSE_MIX_OFF
XRFDC_CRSE_MIX_BYPASS
XRFDC_CRSE_4GSPS_ODD_FSBYTWO
XRFDC_CRSE_MIX_I_ODD_FSBYFOUR
XRFDC_CRSE_MIX_Q_ODD_FSBYFOUR
XRFDC_CRSE_MIX_I_Q_FSBYTWO
XRFDC_CRSE_MIX_I_FSBYFOUR
XRFDC_CRSE_MIX_Q_FSBYFOUR
XRFDC_CRSE_MIX_I_MINFSBYFOUR
XRFDC_CRSE_MIX_Q_MINFSBYFOUR
XRFDC_CRSE_MIX_R_I_FSBYFOUR
XRFDC_CRSE_MIX_R_Q_FSBYFOUR
XRFDC_CRSE_MIX_R_I_MINFSBYFOUR
XRFDC_CRSE_MIX_R_Q_MINFSBYFOUR
XRFDC_MIXER_SCALE_AUTO
XRFDC_MIXER_SCALE_1P0
XRFDC_MIXER_SCALE_0P7
XRFDC_MIXER_PHASE_OFFSET_UP_LIMIT
XRFDC_MIXER_PHASE_OFFSET_LOW_LIMIT
XRFDC_UPDATE_THRESHOLD_0
XRFDC_UPDATE_THRESHOLD_1
XRFDC_UPDATE_THRESHOLD_BOTH
XRFDC_THRESHOLD_CLRMD_MANUAL_CLR
XRFDC_THRESHOLD_CLRMD_AUTO_CLR
XRFDC_DECODER_MAX_SNR_MODE
XRFDC_DECODER_MAX_LINEARITY_MODE
XRFDC_OUTPUT_CURRENT_32MA
XRFDC_OUTPUT_CURRENT_20MA
XRFDC_MIXER_MODE_IQ
XRFDC_ADC_MIXER_MODE_IQ
XRFDC_DAC_MIXER_MODE_REAL
XRFDC_ODD_NYQUIST_ZONE
XRFDC_EVEN_NYQUIST_ZONE
XRFDC_INTERP_DECIM_OFF
XRFDC_INTERP_DECIM_1X
XRFDC_INTERP_DECIM_2X
XRFDC_INTERP_DECIM_3X
XRFDC_INTERP_DECIM_4X
XRFDC_INTERP_DECIM_5X
XRFDC_INTERP_DECIM_6X
XRFDC_INTERP_DECIM_8X
XRFDC_INTERP_DECIM_10X
XRFDC_INTERP_DECIM_12X
XRFDC_INTERP_DECIM_16X
XRFDC_INTERP_DECIM_20X
XRFDC_INTERP_DECIM_24X
XRFDC_INTERP_DECIM_40X
XRFDC_FAB_CLK_DIV1
XRFDC_FAB_CLK_DIV2
XRFDC_FAB_CLK_DIV4
XRFDC_FAB_CLK_DIV8
XRFDC_FAB_CLK_DIV16
XRFDC_CALIB_MODE_AUTO
XRFDC_CALIB_MODE1
XRFDC_CALIB_MODE2
XRFDC_CALIB_MODE_MIXED
XRFDC_CALIB_MODE_ABS_DIFF
XRFDC_CALIB_MODE_NEG_ABS_SUM
XRFDC_TI_DCB_MODE1_4GSPS
XRFDC_TI_DCB_MODE1_2GSPS
XRFDC_PLL_UNLOCKED
XRFDC_PLL_LOCKED
XRFDC_EXTERNAL_CLK
XRFDC_INTERNAL_PLL_CLK
PLL_FPDIV_MIN
PLL_FPDIV_MAX
PLL_DIVIDER_MIN
PLL_DIVIDER_MIN_GEN3
PLL_DIVIDER_MAX
VCO_RANGE_MIN
VCO_RANGE_MAX
VCO_RANGE_ADC_MIN
VCO_RANGE_ADC_MAX
VCO_RANGE_DAC_MIN
VCO_RANGE_DAC_MAX
XRFDC_PLL_LPF1_VAL
XRFDC_PLL_CRS2_VAL
XRFDC_VCO_UPPER_BAND
XRFDC_VCO_LOWER_BAND
XRFDC_REF_CLK_DIV_1
XRFDC_REF_CLK_DIV_2
XRFDC_REF_CLK_DIV_3
XRFDC_REF_CLK_DIV_4
XRFDC_SINGLEBAND_MODE
XRFDC_MULTIBAND_MODE_2X
XRFDC_MULTIBAND_MODE_4X
XRFDC_MB_DATATYPE_C2C
XRFDC_MB_DATATYPE_R2C
XRFDC_MB_DATATYPE_C2R
XRFDC_MB_DUAL_BAND
XRFDC_MB_QUAD_BAND
XRFDC_SB_C2C_BLK0
XRFDC_SB_C2C_BLK1
XRFDC_SB_C2R
XRFDC_MB_C2C_BLK0
XRFDC_MB_C2C_BLK1
XRFDC_MB_C2R_BLK0
XRFDC_MB_C2R_BLK1
XRFDC_MIXER_MODE_BYPASS
XRFDC_LINK_COUPLING_DC
XRFDC_LINK_COUPLING_AC
XRFDC_MB_MODE_SB
XRFDC_MB_MODE_2X_BLK01
XRFDC_MB_MODE_2X_BLK23
XRFDC_MB_MODE_2X_BLK01_BLK23
XRFDC_MB_MODE_4X
XRFDC_MB_MODE_2X_BLK01_BLK23_ALT
XRFDC_MILLI
XRFDC_MICRO
XRFDC_DAC_SAMPLING_MIN
XRFDC_DAC_SAMPLING_MAX
XRFDC_ADC_4G_SAMPLING_MIN
XRFDC_ADC_4G_SAMPLING_MAX
XRFDC_ADC_2G_SAMPLING_MIN
XRFDC_ADC_2G_SAMPLING_MAX
XRFDC_REFFREQ_MIN
XRFDC_REFFREQ_MAX
XRFDC_DIGITALPATH_ENABLE
XRFDC_ANALOGPATH_ENABLE
XRFDC_BLK_ID0
XRFDC_BLK_ID1
XRFDC_BLK_ID2
XRFDC_BLK_ID3
XRFDC_BLK_ID4
XRFDC_BLK_ID_NONE
XRFDC_BLK_ID_ALL
XRFDC_BLK_ID_INV
XRFDC_TILE_ID0
XRFDC_TILE_ID1
XRFDC_TILE_ID2
XRFDC_TILE_ID3
XRFDC_TILE_ID4
XRFDC_TILE_ID_INV
XRFDC_NUM_OF_BLKS1
XRFDC_NUM_OF_BLKS2
XRFDC_NUM_OF_BLKS3
XRFDC_NUM_OF_BLKS4
XRFDC_NUM_OF_TILES1
XRFDC_NUM_OF_TILES2
XRFDC_NUM_OF_TILES3
XRFDC_NUM_OF_TILES4
XRFDC_SM_STATE0
XRFDC_SM_STATE1
XRFDC_SM_STATE3
XRFDC_SM_STATE7
XRFDC_SM_STATE15
XRFDC_STATE_OFF
XRFDC_STATE_SHUTDOWN
XRFDC_STATE_PWRUP
XRFDC_STATE_CLK_DET
XRFDC_STATE_CAL
XRFDC_STATE_FULL
XRFDC_DECIM_4G_DATA_TYPE
XRFDC_DECIM_2G_IQ_DATA_TYPE
XRFDC_DAC_MAX_WR_FAB_RATE
XRFDC_ADC_MAX_RD_FAB_RATE
XRFDC_MIN_PHASE_CORR_FACTOR
XRFDC_MAX_PHASE_CORR_FACTOR
XRFDC_MAX_GAIN_CORR_FACTOR
XRFDC_MIN_GAIN_CORR_FACTOR
XRFDC_FAB_RATE_16
XRFDC_FAB_RATE_8
XRFDC_FAB_RATE_4
XRFDC_FAB_RATE_2
XRFDC_FAB_RATE_1
XRFDC_HSCOM_PWR_STATS_PLL
XRFDC_HSCOM_PWR_STATS_EXTERNAL
XRFDC_HSCOM_PWR_STATS_RX_EXT
XRFDC_HSCOM_PWR_STATS_DIST_EXT
XRFDC_HSCOM_PWR_STATS_RX_PLL
XRFDC_HSCOM_PWR_STATS_DIST_PLL
XRFDC_HSCOM_PWR_STATS_RX_EXT_DIV
XRFDC_HSCOM_PWR_STATS_DIST_EXT_DIV
XRFDC_HSCOM_PWR_STATS_DIST_EXT_SRC
XRFDC_HSCOM_PWR_STATS_DIST_EXT_DIV_SRC
XRFDC_CLK_DST_TILE_231
XRFDC_CLK_DST_TILE_230
XRFDC_CLK_DST_TILE_229
XRFDC_CLK_DST_TILE_228
XRFDC_CLK_DST_TILE_227
XRFDC_CLK_DST_TILE_226
XRFDC_CLK_DST_TILE_225
XRFDC_CLK_DST_TILE_224
XRFDC_CLK_DST_INVALID
XRFDC_GLBL_OFST_DAC
XRFDC_GLBL_OFST_ADC
XRFDC_TILE_GLBL_ADDR
XRFDC_CLK_DISTR_MUX4A_SRC_INT
XRFDC_CLK_DISTR_MUX4A_SRC_STH
XRFDC_CLK_DISTR_MUX6_SRC_OFF
XRFDC_CLK_DISTR_MUX6_SRC_INT
XRFDC_CLK_DISTR_MUX6_SRC_NTH
XRFDC_CLK_DISTR_MUX7_SRC_OFF
XRFDC_CLK_DISTR_MUX7_SRC_STH
XRFDC_CLK_DISTR_MUX7_SRC_INT
XRFDC_CLK_DISTR_MUX8_SRC_NTH
XRFDC_CLK_DISTR_MUX8_SRC_INT
XRFDC_CLK_DISTR_MUX9_SRC_NTH
XRFDC_CLK_DISTR_MUX9_SRC_INT
XRFDC_CLK_DISTR_MUX5A_SRC_PLL
XRFDC_CLK_DISTR_MUX5A_SRC_RX
XRFDC_CLK_DISTR_OFF
XRFDC_CLK_DISTR_LEFTMOST_TILE
XRFDC_CLK_DISTR_CONT_LEFT_EVEN
XRFDC_CLK_DISTR_CONT_LEFT_ODD
XRFDC_CLK_DISTR_RIGHTMOST_TILE
XRFDC_CLK_DISTR_CONT_RIGHT_EVEN
XRFDC_CLK_DISTR_CONT_RIGHT_HWL_ODD
XRFDC_CLK_DISTR_MUX4A_SRC_CLR
XRFDC_CLK_DISTR_MUX6_SRC_CLR
XRFDC_CLK_DISTR_MUX7_SRC_CLR
XRFDC_CLK_DISTR_MUX8_SRC_CLR
XRFDC_CLK_DISTR_MUX9_SRC_CLR
XRFDC_DIST_MAX
XRFDC_NET_CTRL_CLK_REC_PLL
XRFDC_NET_CTRL_CLK_REC_DIST_T1
XRFDC_NET_CTRL_CLK_T1_SRC_LOCAL
XRFDC_NET_CTRL_CLK_T1_SRC_DIST
XRFDC_NET_CTRL_CLK_INPUT_DIST
XRFDC_DIST_CTRL_TO_PLL_DIV
XRFDC_DIST_CTRL_TO_T1
XRFDC_DIST_CTRL_DIST_SRC_LOCAL
XRFDC_DIST_CTRL_DIST_SRC_PLL
XRFDC_DIST_CTRL_CLK_T1_SRC_LOCAL
XRFDC_PLLREFDIV_INPUT_OFF
XRFDC_PLLREFDIV_INPUT_DIST
XRFDC_PLLREFDIV_INPUT_FABRIC
XRFDC_PLLOPDIV_INPUT_DIST_LOCAL
XRFDC_TILE_SOURCE_RX
XRFDC_TILE_SOURCE_DIST
XRFDC_TILE_SOURCE_FABRIC
XRFDC_DIST_OUT_NONE
XRFDC_DIST_OUT_RX
XRFDC_DIST_OUT_OUTDIV
XRFDC_PLL_SOURCE_NONE
XRFDC_PLL_SOURCE_RX
XRFDC_PLL_SOURCE_OUTDIV
XRFDC_PLL_OUTDIV_MODE_1
XRFDC_PLL_OUTDIV_MODE_2
XRFDC_PLL_OUTDIV_MODE_3
XRFDC_PLL_OUTDIV_MODE_N
XRFDC_PLL_OUTDIV_MODE_3_VAL
XRFDC_DIVISION_FACTOR_MIN
XRFDC_DITH_ENABLE
XRFDC_DITH_DISABLE
XRFDC_SIGDET_MODE_AVG
XRFDC_SIGDET_MODE_RNDM
XRFDC_SIGDET_TC_2_0
XRFDC_SIGDET_TC_2_2
XRFDC_SIGDET_TC_2_4
XRFDC_SIGDET_TC_2_8
XRFDC_SIGDET_TC_2_12
XRFDC_SIGDET_TC_2_14
XRFDC_SIGDET_TC_2_16
XRFDC_SIGDET_TC_2_18
XRFDC_DISABLED
XRFDC_ENABLED
XRFDC_ES1_SI
XRFDC_PROD_SI
XRFDC_CAL_BLOCK_OCB1
XRFDC_CAL_BLOCK_OCB2
XRFDC_CAL_BLOCK_GCB
XRFDC_CAL_BLOCK_TSCB
XRFDC_TSCB_TUNE_AUTOCAL
XRFDC_TSCB_TUNE_NOT_AUTOCAL
XRFDC_INV_SYNC_MODE_MAX
XRFDC_INV_SYNC_EN_MAX
XRFDC_CTRL_MASK
XRFDC_EXPORTCTRL_CLKDIST
XRFDC_PREMIUMCTRL_CLKDIST
XRFDC_EXPORTCTRL_VOP
XRFDC_EXPORTCTRL_DSA
XRFDC_DATAPATH_MODE_DUC_0_FSDIVTWO
XRFDC_DATAPATH_MODE_DUC_0_FSDIVFOUR
XRFDC_DATAPATH_MODE_FSDIVFOUR_FSDIVTWO
XRFDC_DATAPATH_MODE_NODUC_0_FSDIVTWO
XRFDC_DAC_INT_MODE_FULL_BW
XRFDC_DAC_INT_MODE_HALF_BW_IMR
XRFDC_DAC_INT_MODE_FULL_BW_BYPASS
XRFDC_DAC_MODE_MAX
XRFDC_FULL_BW_DIVISOR
XRFDC_HALF_BW_DIVISOR
XRFDC_DAC_IMR_MODE_LOWPASS
XRFDC_DAC_IMR_MODE_HIGHPASS
XRFDC_DAC_IMR_MODE_MAX
XRFDC_CLOCK_DETECT_CLK
XRFDC_CLOCK_DETECT_DIST
XRFDC_CLOCK_DETECT_BOTH
XRFDC_CAL_UNFREEZE_CALIB
XRFDC_CAL_FREEZE_CALIB
XRFDC_CAL_FRZ_PIN_ENABLE
XRFDC_CAL_FRZ_PIN_DISABLE
XRFDC_CLK_REG_EN_MASK
XRFDC_GEN1_LOW_I
XRFDC_GEN1_HIGH_I
XRFDC_MAX_ATTEN
XRFDC_MIN_ATTEN
XRFDC_STEP_ATTEN
XRFDC_DAC_VOP_CTRL_REG_UPDT_MASK
XRFDC_DAC_VOP_CTRL_TST_BLD_MASK
XRFDC_DAC_VOP_BLDR_LOW_BITS_MASK
XRFDC_PLL_LOCK_DLY_CNT
XRFDC_RESTART_CLR_DLY_CNT
XRFDC_WAIT_ATTEMPTS_CNT
XRFDC_STATE_WAIT
XRFDC_RESTART_CLR_WAIT
XRFDC_PLL_LOCK_WAIT
XRFDC_CLK_DIV_DP_FIRST_MODE
XRFDC_CLK_DIV_DP_OTHER_MODES
XRFDC_TILE_STARTED
XRFDC_SI_REV_ES
XRFDC_SI_REV_PROD
XRFDC_CG_WAIT_CYCLES
XRFDC_ADC_CG_WAIT_CYCLES
XRFDC_CG_CYCLES_TOTAL_X1_X2_X4_X8
XRFDC_CG_CYCLES_KEPT_X1_X2_X4_X8
XRFDC_CG_CYCLES_TOTAL_X3_X6_X12
XRFDC_CG_CYCLES_KEPT_X3_X6_X12
XRFDC_CG_CYCLES_TOTAL_X5_X10
XRFDC_CG_CYCLES_KEPT_X5_X10
XRFDC_CG_CYCLES_TOTAL_X16
XRFDC_CG_CYCLES_KEPT_X16
XRFDC_CG_CYCLES_TOTAL_X20
XRFDC_CG_CYCLES_KEPT_X20
XRFDC_CG_CYCLES_TOTAL_X24
XRFDC_CG_CYCLES_KEPT_X24
XRFDC_CG_CYCLES_TOTAL_X40
XRFDC_CG_CYCLES_KEPT_X40
XRFDC_CG_FIXED_OFS
XRFDC_FIFO_CHANNEL_ACT
XRFDC_FIFO_CHANNEL_OBS
XRFDC_FIFO_CHANNEL_BOTH
XRFDC_PWR_MODE_OFF
XRFDC_PWR_MODE_ON
XRFDC_DUAL_TILE
XRFDC_QUAD_TILE
XRFDC_4ADC_4DAC_TILES
XRFDC_3ADC_2DAC_TILES
XRFDC_MTS_SYSREF_DISABLE
XRFDC_MTS_SYSREF_ENABLE
XRFDC_MTS_SCAN_INIT
XRFDC_MTS_SCAN_RELOAD
XRFDC_MTS_OK
XRFDC_MTS_NOT_SUPPORTED
XRFDC_MTS_TIMEOUT
XRFDC_MTS_MARKER_RUN
XRFDC_MTS_MARKER_MISM
XRFDC_MTS_DELAY_OVER
XRFDC_MTS_TARGET_LOW
XRFDC_MTS_IP_NOT_READY
XRFDC_MTS_DTC_INVALID
XRFDC_MTS_NOT_ENABLED
XRFDC_MTS_SYSREF_GATE_ERROR
XRFDC_MTS_SYSREF_FREQ_NDONE
XRFDC_MTS_BAD_REF_TILE
XRFDC_CAL_AXICLK_MULT
XRFDC_CAL_DIV_CUTOFF_FREQ
typedef __u32 u32
typedef __u16 u16
typedef __u8 u8
typedef __s32 s32
typedef __s16 s16
typedef __u64 u64
typedef __s64 s64
typedef __s8 s8
typedef void(* XRFdc_StatusHandler)(void *CallBackRef, u32 Type, u32 Tile_Id, u32 Block_Id, u32 StatusEvent))(void *CallBackRef, u32 Type, u32 Tile_Id, u32 Block_Id, u32 StatusEvent)
The handler data type allows the user to define a callback function to respond to interrupt events in the system.
This function is executed in interrupt context, so amount of processing should be minimized. CallBackRef is the callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. Its type is not important to the driver, so it is a void pointer. Type indicates ADC/DAC. Tile_Id indicates Tile number (0-3). Block_Id indicates Block number (0-3). StatusEvent indicates one or more interrupt occurred.
XRFdc_Config* XRFdc_LookupConfig(metal_phys_addr_t BaseAddr)
u32 XRFdc_RegisterMetal(XRFdc *InstancePtr, u16 DeviceId, struct metal_device **DevicePtr)
Register/open the deviceand map RFDC to the IO region.
InstancePtr is a pointer to the XRfdc instance. DeviceId contains the ID of the device to register/map DevicePtr is a pointer to the metal device. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
References XRFdc_GetDeviceNameByDeviceId.
Referenced by RFdcMTS_Example.
u32 XRFdc_CfgInitialize(XRFdc *InstancePtr, XRFdc_Config *ConfigPtr)
Initializes a specific XRFdc instance such that the driver is ready to use.
InstancePtr is a pointer to the XRfdc instance. ConfigPtr is a reference to a structure containing information about xrfdc. This function initializes an InstancePtr object for a specific device specified by the contents of Config. XRFDC_SUCCESS if successful. The user needs to first call the XRFdc_LookupConfig() API which returns the Configuration structure pointer which is passed as a parameter to the XRFdc_CfgInitialize() API.
Referenced by RFdcMTS_Example.
u32 XRFdc_StartUp(XRFdc *InstancePtr, u32 Type, int Tile_Id)
The API Restarts the requested tile.
It can restart a single tile and alternatively can restart all the tiles. Existing register settings are not lost or altered in the process. It just starts the requested tile(s). InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3, and -1. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
u32 XRFdc_Shutdown(XRFdc *InstancePtr, u32 Type, int Tile_Id)
The API stops the tile as requested.
It can also stop all the tiles if asked for. It does not clear any of the existing register settings. It just stops the requested tile(s). InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3, and -1. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
u32 XRFdc_Reset(XRFdc *InstancePtr, u32 Type, int Tile_Id)
The API resets the requested tile.
It can reset all the tiles as well. In the process, all existing register settings are cleared and are replaced with the settings initially configured (through the GUI). InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3, and -1. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
u32 XRFdc_CustomStartUp(XRFdc *InstancePtr, u32 Type, int Tile_Id, u32 StartState, u32 EndState)
The API starts the requested tile from a provided state and runs to the given end state.
It can restart a single tile and alternatively can restart all the tiles. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3, and -1. StartState Valid values are XRFDC_START_STATE_*. Tile_Id Valid values are XRFDC_END_STATE_*. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. If starting from/ending at XRFDC_START_STATE_OFF/XRFDC_END_STATE_OFF, register settings will be wiped.
References XRFDC_CAL_DIV_BYP_MASK, XRFDC_CAL_DIV_BYP_OFFSET, XRFDC_CAL_DLY_OFFSET, XRFDC_CAL_TMR_MULT_OFFSET, XRFdc_ClrSetReg, XRFdc_IsHighSpeedADC, XRFdc_ReadReg, XRFdc_WriteReg.
Referenced by XRFdc_DynamicPLLConfig.
u32 XRFdc_WaitForState(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 State)
This function is used to wait for a tile to reach a given state.
InstancePtr is a pointer to the XRfdc instance. Type represents ADC or DAC. Tile_Id Valid values are 0-3. State represents the state which the tile must reach. XRFDC_SUCCESS if valid.XRFDC_FAILURE if not valid.
References XRFdc_CheckTileEnabled, XRFDC_CURRENT_STATE_MASK, XRFDC_CURRENT_STATE_OFFSET, XRFdc_RDReg.
Referenced by XRFdc_SetClkDistribution.
u32 XRFdc_GetIPStatus(XRFdc *InstancePtr, XRFdc_IPStatus *IPStatusPtr)
The API returns the IP status.
InstancePtr is a pointer to the XRfdc instance. IPStatusPtr Pointer to the XRFdc_IPStatus structure through which the status is returned. XRFDC_SUCCESS if successful. None.
References XRFDC_CURRENT_STATE_OFFSET, XRFdc_IsADCBlockEnabled, XRFdc_IsDACBlockEnabled, XRFDC_PLL_LOCKED_MASK, XRFDC_PLL_LOCKED_SHIFT, XRFDC_PWR_UP_STAT_MASK, XRFDC_PWR_UP_STAT_SHIFT, XRFdc_ReadReg16, XRFDC_STATUS_OFFSET.
Referenced by XRFdc_MultiConverter_Sync.
u32 XRFdc_GetBlockStatus(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, XRFdc_BlockStatus *BlockStatusPtr)
The API returns the requested block status.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. XRFdc_BlockStatus. BlockStatusPtr is Pointer to the XRFdc_BlockStatus structure through which the ADC/DAC block status is returned. XRFDC_SUCCESS if successful.XRFDC_FAILURE if block not enabled. Common API for ADC/DAC blocks.
References XRFdc_CheckBlockEnabled, XRFDC_CLK_EN_OFFSET, XRFDC_DAT_CLK_EN_MASK, XRFdc_IsHighSpeedADC, XRFdc_RDReg.
u32 XRFdc_SetMixerSettings(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, XRFdc_Mixer_Settings *MixerSettingsPtr)
The API is used to update various mixer settings, fine, coarse, NCO etc.
Mixer/NCO settings passed are used to update the corresponding block level registers. Driver structure is updated with the new values. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. MixerSettingsPtr Pointer to the XRFdc_Mixer_Settings structure in which the Mixer/NCO settings are passed. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. FineMixerScale in Mixer_Settings structure can have 3 values. XRFDC_MIXER_SCALE_* represents the valid values. XRFDC_MIXER_SCALE_AUTO - If mixer mode is R2C, Mixer Scale is set to 1 and for other modes mixer scale is set to 0.7 XRFDC_MIXER_SCALE_1P0 - To set fine mixer scale to 1. XRFDC_MIXER_SCALE_0P7 - To set fine mixer scale to 0.7.
References XRFDC_ADC_DECI_CONFIG_OFFSET, XRFDC_ADC_NCO_FQWD_LOW_OFFSET, XRFDC_ADC_NCO_FQWD_MID_OFFSET, XRFDC_ADC_NCO_FQWD_UPP_OFFSET, XRFDC_ADC_NCO_PHASE_MOD_OFFSET, XRFDC_ADC_UPDATE_DYN_OFFSET, XRFdc_CheckDigitalPathEnabled, XRFdc_ClrSetReg, XRFDC_DAC_DATAPATH_OFFSET, XRFDC_DAC_INTERP_DATA_MASK, XRFDC_DAC_ITERP_DATA_OFFSET, XRFDC_DAC_UPDATE_DYN_OFFSET, XRFDC_DATAPATH_MODE_MASK, XRFDC_DEC_CFG_4GSPS_MASK, XRFDC_DEC_CFG_CHA_MASK, XRFDC_DEC_CFG_IQ_MASK, XRFDC_DEC_CFG_MASK, XRFDC_FINE_MIX_SCALE_MASK, XRFdc_GetCalibrationMode, XRFdc_GetNyquistZone, XRFdc_IsHighSpeedADC, XRFDC_MXR_MODE_OFFSET, XRFDC_NCO_FQWD_MID_MASK, XRFDC_NCO_FQWD_MID_SHIFT, XRFDC_NCO_FQWD_UPP_MASK, XRFDC_NCO_FQWD_UPP_SHIFT, XRFDC_NCO_PHASE_LOW_OFFSET, XRFDC_NCO_PHASE_MOD_EVEN, XRFDC_NCO_PHASE_MODE_ODD, XRFDC_NCO_PHASE_UPP_MASK, XRFDC_NCO_PHASE_UPP_OFFSET, XRFDC_NCO_PHASE_UPP_SHIFT, XRFDC_NCO_UPDT_MODE_MASK, XRFDC_NCO_UPDT_OFFSET, XRFdc_RDReg, XRFdc_ReadReg16, XRFdc_ResetInternalFIFOWidth, XRFDC_UPDT_EVNT_MASK, XRFDC_UPDT_EVNT_NCO_MASK, XRFdc_WriteReg16.
Referenced by XRFdc_SetCalibrationMode, XRFdc_SetDataPathMode.
u32 XRFdc_GetMixerSettings(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, XRFdc_Mixer_Settings *MixerSettingsPtr)
The API returns back Mixer/NCO settings to the caller.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. MixerSettingsPtr Pointer to the XRFdc_Mixer_Settings structure in which the Mixer/NCO settings are passed. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. FineMixerScale in Mixer_Settings structure can have 3 values. XRFDC_MIXER_SCALE_* represents the valid values. XRFDC_MIXER_SCALE_AUTO - If mixer mode is R2C, Mixer Scale is set to 1 and for other modes mixer scale is set to 0.7 XRFDC_MIXER_SCALE_1P0 - To set fine mixer scale to 1. XRFDC_MIXER_SCALE_0P7 - To set fine mixer scale to 0.7.
References XRFDC_ADC_MXR_CFG0_OFFSET, XRFDC_ADC_MXR_CFG1_OFFSET, XRFDC_ADC_NCO_FQWD_LOW_OFFSET, XRFDC_ADC_NCO_FQWD_MID_OFFSET, XRFDC_ADC_NCO_FQWD_UPP_OFFSET, XRFdc_CheckDigitalPathEnabled, XRFDC_DAC_DATAPATH_OFFSET, XRFDC_DATAPATH_MODE_MASK, XRFDC_EN_I_IQ_MASK, XRFDC_EN_Q_IQ_MASK, XRFDC_FINE_MIX_SCALE_MASK, XRFdc_GetCalibrationMode, XRFdc_GetNyquistZone, XRFdc_IsHighSpeedADC, XRFDC_MIX_CFG0_MASK, XRFDC_MIX_CFG1_MASK, XRFDC_MXR_MODE_OFFSET, XRFDC_NCO_FQWD_MASK, XRFDC_NCO_FQWD_MID_SHIFT, XRFDC_NCO_FQWD_UPP_SHIFT, XRFDC_NCO_PHASE_LOW_OFFSET, XRFDC_NCO_PHASE_MASK, XRFDC_NCO_PHASE_UPP_OFFSET, XRFDC_NCO_PHASE_UPP_SHIFT, XRFDC_NCO_UPDT_MODE_MASK, XRFDC_NCO_UPDT_OFFSET, XRFdc_RDReg, XRFdc_ReadReg16.
Referenced by XRFdc_SetCalibrationMode, XRFdc_SetDataPathMode.
u32 XRFdc_SetQMCSettings(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, XRFdc_QMC_Settings *QMCSettingsPtr)
This API is used to update various QMC settings, eg gain, phase, offset etc.
QMC settings passed are used to update the corresponding block level registers. Driver structure is updated with the new values. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. QMCSettingsPtr is Pointer to the XRFdc_QMC_Settings structure in which the QMC settings are passed. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
References XRFDC_ADC_SWITCH_MATRX_OFFSET, XRFDC_ADC_UPDATE_DYN_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFDC_DAC_MB_CFG_OFFSET, XRFDC_DAC_UPDATE_DYN_OFFSET, XRFdc_GetConnectedIData, XRFdc_GetConnectedQData, XRFdc_IsHighSpeedADC, XRFDC_QMC_CFG_EN_GAIN_MASK, XRFDC_QMC_CFG_EN_PHASE_MASK, XRFDC_QMC_CFG_OFFSET, XRFDC_QMC_CFG_PHASE_SHIFT, XRFDC_QMC_GAIN_CRCTN_MASK, XRFDC_QMC_GAIN_OFFSET, XRFDC_QMC_OFF_OFFSET, XRFDC_QMC_OFFST_CRCTN_MASK, XRFDC_QMC_PHASE_CRCTN_MASK, XRFDC_QMC_PHASE_OFFSET, XRFDC_QMC_UPDT_MODE_MASK, XRFDC_QMC_UPDT_OFFSET, XRFdc_RDReg, XRFDC_SEL_CB_TO_QMC_MASK, XRFDC_UPDT_EVNT_MASK, XRFDC_UPDT_EVNT_QMC_MASK.
u32 XRFdc_GetQMCSettings(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, XRFdc_QMC_Settings *QMCSettingsPtr)
QMC settings are returned back to the caller through this API.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. QMCSettingsPtr Pointer to the XRFdc_QMC_Settings structure in which the QMC settings are passed. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
References XRFdc_CheckBlockEnabled, XRFDC_DAC_MB_CFG_OFFSET, XRFdc_IsHighSpeedADC, XRFDC_QMC_CFG_EN_GAIN_MASK, XRFDC_QMC_CFG_EN_PHASE_MASK, XRFDC_QMC_CFG_OFFSET, XRFDC_QMC_CFG_PHASE_SHIFT, XRFDC_QMC_GAIN_CRCTN_MASK, XRFDC_QMC_GAIN_OFFSET, XRFDC_QMC_OFF_OFFSET, XRFDC_QMC_OFFST_CRCTN_MASK, XRFDC_QMC_OFFST_CRCTN_SIGN_MASK, XRFDC_QMC_PHASE_CRCTN_MASK, XRFDC_QMC_PHASE_CRCTN_SIGN_MASK, XRFDC_QMC_PHASE_OFFSET, XRFDC_QMC_UPDT_MODE_MASK, XRFDC_QMC_UPDT_OFFSET, XRFdc_RDReg.
u32 XRFdc_GetCoarseDelaySettings(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, XRFdc_CoarseDelay_Settings *CoarseDelaySettingsPtr)
Coarse delay settings are returned back to the caller.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. CoarseDelaySettingsPtr Pointer to the XRFdc_CoarseDelay_Settings structure in which the Coarse Delay settings are passed. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
References XRFDC_ADC_CRSE_DLY_CFG_OFFSET, XRFDC_ADC_CRSE_DLY_UPDT_OFFSET, XRFdc_CheckBlockEnabled, XRFDC_DAC_CRSE_DLY_CFG_OFFSET, XRFDC_DAC_CRSE_DLY_UPDT_OFFSET, XRFdc_IsHighSpeedADC, XRFDC_QMC_UPDT_MODE_MASK, XRFdc_RDReg, XRFdc_ReadReg16.
u32 XRFdc_SetCoarseDelaySettings(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, XRFdc_CoarseDelay_Settings *CoarseDelaySettingsPtr)
Coarse delay settings passed are used to update the corresponding block level registers.
Driver structure is updated with the new values. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. CoarseDelaySettingsPtr is Pointer to the XRFdc_CoarseDelay_Settings structure in which the CoarseDelay settings are passed. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
References XRFDC_ADC_CRSE_DLY_CFG_OFFSET, XRFDC_ADC_CRSE_DLY_UPDT_OFFSET, XRFDC_ADC_UPDATE_DYN_OFFSET, XRFDC_ADC_UPDT_CRSE_DLY_MASK, XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFDC_CRSE_DLY_CFG_MASK, XRFDC_CRSE_DLY_CFG_MASK_EXT, XRFDC_DAC_CRSE_DLY_CFG_OFFSET, XRFDC_DAC_CRSE_DLY_UPDT_OFFSET, XRFDC_DAC_UPDATE_DYN_OFFSET, XRFDC_DAC_UPDT_CRSE_DLY_MASK, XRFdc_IsHighSpeedADC, XRFDC_QMC_UPDT_MODE_MASK, XRFDC_UPDT_EVNT_MASK.
u32 XRFdc_GetInterpolationFactor(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *InterpolationFactorPtr)
Interpolation factor are returned back to the caller.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. InterpolationFactorPtr Pointer to return the interpolation factor for DAC blocks. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for DAC blocks
References XRFdc_CheckDigitalPathEnabled, XRFDC_DAC_INTERP_CTRL_OFFSET, XRFDC_INTERP_MODE_I_MASK, XRFDC_INTERP_MODE_I_MASK_EXT, XRFdc_RDReg.
Referenced by RFdcMTS_Example.
u32 XRFdc_GetDecimationFactor(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *DecimationFactorPtr)
Decimation factor are returned back to the caller.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. DecimationFactorPtr Pointer to return the Decimation factor for DAC blocks. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
Referenced by RFdcMTS_Example.
u32 XRFdc_GetDecimationFactorObs(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *DecimationFactorPtr)
Decimation factor are returned back to the caller for the observation FIFO.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. DecimationFactorPtr Pointer to return the Decimation factor for DAC blocks. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
u32 XRFdc_GetFabWrVldWords(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 *FabricWrVldWordsPtr)
This API returns the number of fabric write valid words requested for the block.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. FabricWrVldWordsPtr Pointer to return the fabric data rate for DAC block XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. ADC/DAC blocks
u32 XRFdc_GetFabWrVldWordsObs(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 *FabricWrVldWordsPtr)
This API returns the number of fabric write valid words requested for the block.
This is for the observation FIFO. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. FabricWrVldWordsPtr Pointer to return the fabric data rate for DAC block XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. ADC blocks only
u32 XRFdc_GetFabRdVldWords(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 *FabricRdVldWordsPtr)
This API returns the number of fabric read valid words requested for the block.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. FabricRdVldWordsPtr Pointer to return the fabric data rate for ADC/DAC block XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. ADC/DAC blocks
u32 XRFdc_GetFabRdVldWordsObs(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 *FabricRdVldWordsPtr)
This function returns the number of fabric read valid words requested for the block.
This is for the observation FIFO. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. FabricRdVldWordsPtr Pointer to return the fabric data rate for ADC/DAC block XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. ADC blocks only
u32 XRFdc_SetFabRdVldWords(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 FabricRdVldWords)
Fabric data rate for the requested ADC block is set by writing to the corresponding register.
The function writes the number of valid read words for the requested ADC block. InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC block number inside the tile. Valid values are 0-3. FabricRdVldWords is Read fabric rate to be set for ADC block. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
u32 XRFdc_SetFabRdVldWordsObs(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 FabricRdVldWords)
Fabric data rate for the requested ADC block is set by writing to the corresponding register.
The function writes the number of valid read words for the requested ADC block. This is for the observation FIFO. InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC block number inside the tile. Valid values are 0-3. FabricRdVldWords is Read fabric rate to be set for ADC block. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
u32 XRFdc_SetFabWrVldWords(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 FabricWrVldWords)
Fabric data rate for the requested DAC block is set by writing to the corresponding register.
The function writes the number of valid write words for the requested DAC block. InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. FabricWrVldWords is write fabric rate to be set for DAC block. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for DAC blocks
References XRFdc_CheckDigitalPathEnabled, XRFdc_ClrSetReg, XRFDC_DAC_FAB_RATE_WR_MASK, XRFDC_DAC_FABRIC_RATE_OFFSET.
u32 XRFdc_GetThresholdSettings(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, XRFdc_Threshold_Settings *ThresholdSettingsPtr)
Threshold settings are read from the corresponding registers and are passed back to the caller.
There can be two threshold settings: threshold0 and threshold1. Both of them are independent of each other. The function returns the requested threshold (which can be threshold0, threshold1, or both. InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. ThresholdSettingsPtr Pointer through which the register settings for thresholds are passed back.. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_ADC_TRSHD0_AVG_LO_OFFSET, XRFDC_ADC_TRSHD0_AVG_UP_OFFSET, XRFDC_ADC_TRSHD0_CFG_OFFSET, XRFDC_ADC_TRSHD0_OVER_OFFSET, XRFDC_ADC_TRSHD0_UNDER_OFFSET, XRFDC_ADC_TRSHD1_AVG_LO_OFFSET, XRFDC_ADC_TRSHD1_AVG_UP_OFFSET, XRFDC_ADC_TRSHD1_CFG_OFFSET, XRFDC_ADC_TRSHD1_OVER_OFFSET, XRFDC_ADC_TRSHD1_UNDER_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_IsHighSpeedADC, XRFdc_RDReg, XRFdc_ReadReg16, XRFDC_TRSHD0_AVG_UPP_SHIFT, XRFDC_TRSHD0_EN_MOD_MASK, XRFDC_TRSHD0_OVER_MASK, XRFDC_TRSHD0_UNDER_MASK, XRFDC_TRSHD1_AVG_UPP_SHIFT, XRFDC_TRSHD1_EN_MOD_MASK, XRFDC_TRSHD1_OVER_MASK, XRFDC_TRSHD1_UNDER_MASK.
u32 XRFdc_SetThresholdSettings(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, XRFdc_Threshold_Settings *ThresholdSettingsPtr)
Threshold settings are updated into the relevant registers.
Driver structure is updated with the new values. There can be two threshold settings: threshold0 and threshold1. Both of them are independent of each other. The function returns the requested threshold (which can be threshold0, threshold1, or both. InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. ThresholdSettingsPtr Pointer through which the register settings for thresholds are passed to the API. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only ADC blocks
References XRFDC_ADC_TRSHD0_AVG_LO_OFFSET, XRFDC_ADC_TRSHD0_AVG_UP_OFFSET, XRFDC_ADC_TRSHD0_CFG_OFFSET, XRFDC_ADC_TRSHD0_OVER_OFFSET, XRFDC_ADC_TRSHD0_UNDER_OFFSET, XRFDC_ADC_TRSHD1_AVG_LO_OFFSET, XRFDC_ADC_TRSHD1_AVG_UP_OFFSET, XRFDC_ADC_TRSHD1_CFG_OFFSET, XRFDC_ADC_TRSHD1_OVER_OFFSET, XRFDC_ADC_TRSHD1_UNDER_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFdc_IsHighSpeedADC, XRFDC_TRSHD0_AVG_UPP_SHIFT, XRFDC_TRSHD0_EN_MOD_MASK, XRFDC_TRSHD0_OVER_MASK, XRFDC_TRSHD0_UNDER_MASK, XRFDC_TRSHD1_AVG_UPP_SHIFT, XRFDC_TRSHD1_EN_MOD_MASK, XRFDC_TRSHD1_OVER_MASK, XRFDC_TRSHD1_UNDER_MASK, XRFdc_WriteReg16.
u32 XRFdc_SetDecoderMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 DecoderMode)
Decoder mode is updated into the relevant registers.
Driver structure is updated with the new values. InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is DAC block number inside the tile. Valid values are 0-3. DecoderMode Valid values are 1 (Maximum SNR, for non- randomized decoder), 2 (Maximum Linearity, for randomized decoder) XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only DAC blocks
References XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFDC_DAC_DECODER_CLK_OFFSET, XRFDC_DAC_DECODER_CTRL_OFFSET, XRFDC_DEC_CTRL_MODE_MASK.
u32 XRFdc_UpdateEvent(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 Event)
This function will trigger the update event for an event.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Event is for which dynamic update event will trigger. XRFDC_EVENT_* defines the different events. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Common API for ADC/DAC blocks
References XRFDC_ADC_CRSE_DLY_UPDT_OFFSET, XRFDC_ADC_UPDATE_DYN_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_CheckDigitalPathEnabled, XRFDC_DAC_CRSE_DLY_UPDT_OFFSET, XRFDC_DAC_UPDATE_DYN_OFFSET, XRFDC_HSCOM_UPDT_DYN_OFFSET, XRFdc_IsHighSpeedADC, XRFDC_NCO_UPDT_MODE_MASK, XRFDC_NCO_UPDT_OFFSET, XRFDC_QMC_UPDT_MODE_MASK, XRFDC_QMC_UPDT_OFFSET, XRFdc_RDReg, XRFdc_WriteReg16.
u32 XRFdc_GetDecoderMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *DecoderModePtr)
Decoder mode is read and returned back.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is DAC block number inside the tile. Valid values are 0-3. DecoderModePtr Valid values are 1 (Maximum SNR, for non-randomized decoder), 2 (Maximum Linearity, for randomized decoder) XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for DAC blocks
References XRFdc_CheckBlockEnabled, XRFDC_DAC_DECODER_CTRL_OFFSET, XRFDC_DEC_CTRL_MODE_MASK, XRFdc_RDReg.
u32 XRFdc_ResetNCOPhase(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id)
Resets the NCO phase of the current block phase accumulator.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
References XRFdc_CheckDigitalPathEnabled, XRFdc_ClrSetReg, XRFdc_IsHighSpeedADC, XRFDC_NCO_PHASE_RST_MASK, XRFDC_NCO_RST_OFFSET.
void XRFdc_DumpRegs(XRFdc *InstancePtr, u32 Type, int Tile_Id)
This Prints the offset of the register along with the content.
This API is meant to be used for debug purposes. It prints to the console the contents of registers for the passed Tile_Id. If -1 is passed, it prints the contents of the registers for all the tiles for the respective ADC or DAC InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3, and -1. None None.
u32 XRFdc_MultiBand(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u8 DigitalDataPathMask, u32 MixerInOutDataType, u32 DataConverterMask)
User-level API to setup multiband configuration.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. DigitalDataPathMask is the DataPath mask. First 4 bits represent 4 data paths, 1 means enabled and 0 means disabled. MixerInOutDataType is mixer data type, valid values are XRFDC_MB_DATATYPE_* DataConverterMask is block enabled mask (input/output driving blocks). 1 means enabled and 0 means disabled. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Common API for ADC/DAC blocks
References XRFdc_CheckBlockEnabled, XRFdc_CheckDigitalPathEnabled, XRFDC_DAC_DATAPATH_OFFSET, XRFDC_DATAPATH_MODE_MASK, XRFdc_IsHighSpeedADC, XRFdc_RDReg.
int XRFdc_GetConnectedIData(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id)
Get Data Converter connected for digital data path I.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is Digital Data Path number. Return Data converter Id.
References XRFdc_GetConnectedIQData.
Referenced by XRFdc_SetQMCSettings.
int XRFdc_GetConnectedQData(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id)
Get Data Converter connected for digital data path Q.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is Digital Data Path number. Return Data converter Id.
References XRFdc_GetConnectedIQData.
Referenced by XRFdc_SetQMCSettings.
u32 XRFdc_GetConnectedIQData(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, int *ConnectedIData, int *ConnectedQData)
Get Data Converter connected for digital data paths I & Q.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is Digital Data Path number. ConnectedData is Digital Data Path number. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs.
References XRFDC_ADC_SWITCH_MATRX_OFFSET, XRFdc_CheckDigitalPathEnabled, XRFDC_DAC_MB_CFG_OFFSET, XRFDC_MB_CONFIG_OFFSET, XRFdc_RDReg, XRFdc_ReadReg, XRFDC_SEL_CB_TO_MIX1_MASK.
Referenced by XRFdc_GetConnectedIData, XRFdc_GetConnectedQData.
u32 XRFdc_IntrHandler(u32 Vector, void *XRFdcPtr)
This function is the interrupt handler for the driver.
It must be connected to an interrupt system by the application such that it can be called when an interrupt occurs. Vector is interrupt vector number. Libmetal status handler expects two parameters in the handler prototype, hence kept this parameter. This is not used inside the interrupt handler API. XRFdcPtr contains a pointer to the driver instance None.Vector param is not useful inside the interrupt handler, hence typecast with void to remove compilation warning.
References XRFDC_COMMON_INTR_STS, XRFDC_EN_INTR_ADC_TILE0_MASK, XRFDC_EN_INTR_ADC_TILE1_MASK, XRFDC_EN_INTR_ADC_TILE2_MASK, XRFDC_EN_INTR_ADC_TILE3_MASK, XRFDC_EN_INTR_DAC_TILE0_MASK, XRFDC_EN_INTR_DAC_TILE1_MASK, XRFDC_EN_INTR_DAC_TILE2_MASK, XRFDC_EN_INTR_DAC_TILE3_MASK, XRFDC_EN_INTR_SLICE0_MASK, XRFDC_EN_INTR_SLICE1_MASK, XRFDC_EN_INTR_SLICE2_MASK, XRFDC_EN_INTR_SLICE3_MASK, XRFdc_GetIntrStatus, XRFDC_INTR_COMMON_MASK, XRFDC_INTR_STS, XRFdc_IntrClr, XRFdc_IsHighSpeedADC, XRFdc_ReadReg16.
u32 XRFdc_IntrClr(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 IntrMask)
This function clear the interrupts.
InstancePtr is a pointer to the XRFdc instance Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3, and -1. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. IntrMask contains the interrupts to be cleared. XRFDC_SUCCESS if successful.XRFDC_FAILURE if block not available. None.
References XRFDC_ADC_DEC_ISR_OFFSET, XRFDC_ADC_FABRIC_ISR_OBS_OFFSET, XRFDC_ADC_FABRIC_ISR_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_CheckDigitalPathEnabled, XRFDC_DAC_FABRIC_ISR_OFFSET, XRFDC_DATPATH_ISR_OFFSET, XRFdc_IsHighSpeedADC, XRFdc_WriteReg, XRFdc_WriteReg16.
Referenced by XRFdc_IntrHandler.
u32 XRFdc_GetIntrStatus(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 *IntrStsPtr)
This function returns the interrupt status read from Interrupt Status Register(ISR).
InstancePtr is a pointer to the XRFdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3, and -1. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. IntrStsPtr is pointer to a32-bit value representing the contents of the Interrupt Status Registers (FIFO interface, Decoder interface, Data Path Interface). XRFDC_SUCCESS if successful.XRFDC_FAILURE if block not available. None.
References XRFDC_ADC_DAT_PATH_ISR_MASK, XRFDC_ADC_DEC_ISR_OFFSET, XRFDC_ADC_FABRIC_ISR_OBS_OFFSET, XRFDC_ADC_FABRIC_ISR_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_CheckDigitalPathEnabled, XRFDC_DAC_DAT_PATH_ISR_MASK, XRFDC_DAC_FABRIC_ISR_OFFSET, XRFDC_DAC_FIFO_IMR_SUPP_MASK, XRFDC_DATPATH_ISR_OFFSET, XRFDC_DEC_ISR_SUBADC_MASK, XRFDC_INTR_CMODE_OVR_MASK, XRFDC_INTR_CMODE_UNDR_MASK, XRFDC_INTR_COMMON_MASK, XRFDC_INTR_DAT_OVR_MASK, XRFDC_INTR_FIFO_OVR_MASK, XRFDC_INTR_OVR_RANGE_MASK, XRFDC_INTR_OVR_VOLTAGE_MASK, XRFDC_INTR_STS, XRFdc_IsHighSpeedADC, XRFdc_ReadReg, XRFdc_ReadReg16.
Referenced by XRFdc_IntrHandler.
u32 XRFdc_IntrDisable(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 IntrMask)
This function clears the interrupt mask.
InstancePtr is a pointer to the XRFdc instance Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3, and -1. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. IntrMask contains the interrupts to be disabled. '1' disables an interrupt, and '0' remains no change. XRFDC_SUCCESS if successful.XRFDC_FAILURE if block not available. None.
References XRFDC_ADC_DEC_IMR_OFFSET, XRFDC_ADC_FABRIC_IMR_OBS_OFFSET, XRFDC_ADC_FABRIC_IMR_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_CheckDigitalPathEnabled, XRFdc_ClrReg, XRFDC_DAC_FABRIC_IMR_OFFSET, XRFDC_DATPATH_IMR_OFFSET, XRFDC_INTR_ENABLE, XRFdc_IsHighSpeedADC, XRFdc_ReadReg, XRFdc_WriteReg.
Referenced by RFdcHandler.
u32 XRFdc_IntrEnable(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 IntrMask)
This function sets the interrupt mask.
InstancePtr is a pointer to the XRFdc instance Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3, and -1. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. IntrMask contains the interrupts to be enabled. '1' enables an interrupt, and '0' disables. XRFDC_SUCCESS if successful.XRFDC_FAILURE if block not available. None.
References XRFDC_ADC_DAT_IMR_MASK, XRFDC_ADC_DEC_IMR_OFFSET, XRFDC_ADC_FABRIC_IMR_OBS_OFFSET, XRFDC_ADC_FABRIC_IMR_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_CheckDigitalPathEnabled, XRFdc_ClrSetReg, XRFDC_COMMON_INTR_ENABLE, XRFDC_DAC_DAT_IMR_MASK, XRFDC_DAC_FABRIC_IMR_OFFSET, XRFDC_DAC_FIFO_IMR_MASK, XRFDC_DATPATH_IMR_OFFSET, XRFDC_INTR_ENABLE, XRFdc_IsHighSpeedADC, XRFdc_ReadReg, XRFdc_ReadReg16, XRFdc_WriteReg, XRFdc_WriteReg16.
u32 XRFdc_GetEnabledInterrupts(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 *IntrMask)
This function gets a mask of enabled interrupts.
InstancePtr is a pointer to the XRFdc instance Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3, and -1. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. IntrMask is a pointer to the mask of enabled interrupts. '1' denotes an enabled interrupt, and '0' denotes a disabled interrupt. XRFDC_SUCCESS if successful.XRFDC_FAILURE if block not available. None.
References XRFDC_ADC_DAT_IMR_MASK, XRFDC_ADC_DEC_IMR_OFFSET, XRFDC_ADC_FABRIC_IMR_OBS_OFFSET, XRFDC_ADC_FABRIC_IMR_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_CheckDigitalPathEnabled, XRFDC_COMMON_INTR_ENABLE, XRFDC_DAC_DAT_IMR_MASK, XRFDC_DAC_FABRIC_IMR_OFFSET, XRFDC_DAC_FIFO_IMR_SUPP_MASK, XRFDC_DATPATH_IMR_OFFSET, XRFDC_INTR_ENABLE, XRFdc_IsHighSpeedADC, XRFdc_RDReg, XRFdc_ReadReg, XRFdc_ReadReg16.
u32 XRFdc_SetThresholdClrMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 ThresholdToUpdate, u32 ClrMode)
This API sets the threshold clear mode.
The clear mode can be through explicit DRP access (manual) or auto clear (QMC gain update event). InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADCC block number inside the tile. Valid values are 0-3. ThresholdToUpdate Select which Threshold (Threshold0 or Threshold1 or both) to update. ClrMode can be DRP access (manual) or auto clear (QMC gain update event). XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only ADC blocks
References XRFDC_ADC_TRSHD0_CFG_OFFSET, XRFDC_ADC_TRSHD1_CFG_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_IsHighSpeedADC, XRFdc_ReadReg16, XRFDC_TRSHD0_CLR_MOD_MASK, XRFDC_TRSHD1_CLR_MOD_MASK, XRFdc_WriteReg16.
u32 XRFdc_ThresholdStickyClear(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 ThresholdToUpdate)
This API is to clear the Sticky bit in threshold config registers.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. ThresholdToUpdate Select which Threshold (Threshold0 or Threshold1 or both) to update. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only ADC blocks
References XRFDC_ADC_TRSHD0_CFG_OFFSET, XRFDC_ADC_TRSHD1_CFG_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFdc_IsHighSpeedADC, XRFDC_TRSHD0_STIKY_CLR_MASK, XRFDC_TRSHD1_STIKY_CLR_MASK.
void XRFdc_SetStatusHandler(XRFdc *InstancePtr, void *CallBackRef, XRFdc_StatusHandler FunctionPtr)
This function sets the status callback function, the status handler, which the driver calls when it encounters conditions that should be reported to the higher layer software.
The handler executes in an interrupt context, so the amount of processing should be minimized InstancePtr is a pointer to the XRFdc instance. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. FunctionPtr is the pointer to the callback function. None.The handler is called within interrupt context, so it should finish its work quickly.
u32 XRFdc_SetupFIFO(XRFdc *InstancePtr, u32 Type, int Tile_Id, u8 Enable)
Enable and Disable the ADC/DAC FIFO.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Enable valid values are 1 (FIFO enable) and 0 (FIFO Disable) XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Common API for ADC/DAC blocks
u32 XRFdc_SetupFIFOObs(XRFdc *InstancePtr, u32 Type, int Tile_Id, u8 Enable)
Enable and Disable the ADC/DAC FIFO.
For ADCs this is for the observtion FIFO. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Enable valid values are 1 (FIFO enable) and 0 (FIFO Disable) XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. ADC blocks only
u32 XRFdc_SetupFIFOBoth(XRFdc *InstancePtr, u32 Type, int Tile_Id, u8 Enable)
Enable and Disable the ADC/DAC FIFO.
Thisis for the actual and observtion FIFO. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Enable valid values are 1 (FIFO enable) and 0 (FIFO Disable) XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. ADC blocks only
u32 XRFdc_GetFIFOStatus(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u8 *EnablePtr)
Current status of ADC/DAC FIFO.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. EnablePtr valid values are 1 (FIFO enable) and 0 (FIFO Disable) XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Common API for ADC/DAC blocks
References XRFdc_GetFIFOStatusInt.
u32 XRFdc_GetFIFOStatusObs(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u8 *EnablePtr)
Current status of ADC/DAC FIFO.
This is for the observation FIFO. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. EnablePtr valid values are 1 (FIFO enable) and 0 (FIFO Disable) XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. ADC blocks only
References XRFdc_GetFIFOStatusInt.
u32 XRFdc_SetNyquistZone(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 NyquistZone)
Set the Nyquist zone.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. NyquistZone valid values are 1 (Odd),2 (Even). XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Common API for ADC/DAC blocks
References XRFDC_ADC_TI_TISK_CRL0_OFFSET, XRFdc_CheckBlockEnabled, XRFDC_DAC_MC_CFG0_OFFSET, XRFdc_GetCalibrationMode, XRFdc_IsHighSpeedADC, XRFDC_MC_CFG0_MIX_MODE_MASK, XRFdc_ReadReg16, XRFDC_TI_TISK_ZONE_MASK, XRFdc_WriteReg16.
Referenced by XRFdc_SetCalibrationMode.
u32 XRFdc_GetNyquistZone(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 *NyquistZonePtr)
Get the Nyquist zone.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. NyquistZonePtr Pointer to return the Nyquist zone. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Common API for ADC/DAC blocks
References XRFDC_ADC_TI_TISK_CRL0_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_CheckDigitalPathEnabled, XRFDC_DAC_MC_CFG0_OFFSET, XRFdc_GetCalibrationMode, XRFdc_IsHighSpeedADC, XRFDC_MC_CFG0_MIX_MODE_MASK, XRFDC_MC_CFG0_MIX_MODE_SHIFT, XRFdc_RDReg, XRFDC_TI_TISK_ZONE_MASK, XRFDC_TISK_ZONE_SHIFT.
Referenced by XRFdc_GetMixerSettings, XRFdc_SetCalibrationMode, XRFdc_SetInvSincFIR, XRFdc_SetMixerSettings.
u32 XRFdc_GetOutputCurr(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *OutputCurrPtr)
Get Output Current for DAC block.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. OutputCurrPtr pointer to return the output current. Return Output Current for DAC block
References XRFDC_ADC_DAC_MC_CFG2_OFFSET, XRFdc_CheckBlockEnabled, XRFDC_DAC_MC_CFG3_OFFSET, XRFdc_RDReg.
u32 XRFdc_SetDecimationFactor(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 DecimationFactor)
This API is to set the decimation factor and also update the FIFO write words w.r.t to decimation factor.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. DecimationFactor to be set for DAC block. XRFDC_INTERP_DECIM_* defines the valid values. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only ADC blocks
u32 XRFdc_SetDecimationFactorObs(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 DecimationFactor)
This API is to set the decimation factor and also update the FIFO write words w.r.t to decimation factor for the observation FIFO.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. DecimationFactor to be set for DAC block. XRFDC_INTERP_DECIM_* defines the valid values. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only ADC blocks
u32 XRFdc_SetInterpolationFactor(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 InterpolationFactor)
This API is to set the interpolation factor and also update the FIFO read words w.r.t to interpolation factor.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. InterpolationFactor to be set for DAC block. XRFDC_INTERP_DECIM_* defines the valid values. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only DAC blocks
References XRFdc_CheckDigitalPathEnabled, XRFdc_ClrSetReg, XRFDC_DAC_DATAPATH_OFFSET, XRFDC_DAC_FIFO_DELAY_MASK, XRFDC_DAC_FIFO_START_OFFSET, XRFDC_DAC_INTERP_CTRL_OFFSET, XRFDC_DAC_ITERP_DATA_OFFSET, XRFDC_DATAPATH_MODE_MASK, XRFDC_INTERP_MODE_MASK, XRFDC_INTERP_MODE_MASK_EXT, XRFDC_INTERP_MODE_Q_SHIFT, XRFDC_INTERP_MODE_Q_SHIFT_EXT, XRFdc_RDReg, XRFdc_ReadReg16.
u32 XRFdc_SetFabClkOutDiv(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u16 FabClkDiv)
This API is to set the divider for clock fabric out.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. FabClkDiv to be set for a tile. XRFDC_FAB_CLK_* defines the valid divider values. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. ADC and DAC Tiles
References XRFdc_CheckTileEnabled, XRFdc_ClrSetReg, XRFDC_FAB_CLK_DIV_MASK, XRFDC_HSCOM_CLK_DIV_OFFSET.
u32 XRFdc_SetCalibrationMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u8 CalibrationMode)
This API is to set the Calibration mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. CalibrationMode valid values are 0(Gen 3 only), 1 and 2. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_ADC_TI_DCB_CRL0_OFFSET, XRFDC_ADC_TI_TISK_CRL0_OFFSET, XRFDC_ADC_TI_TISK_CRL5_OFFSET, XRFDC_CAL_MODES_MASK, XRFDC_CAL_TSCB_TUNE_MASK, XRFdc_CheckBlockEnabled, XRFdc_CheckDigitalPathEnabled, XRFdc_ClrSetReg, XRFdc_GetMixerSettings, XRFdc_GetNyquistZone, XRFdc_IsHighSpeedADC, XRFdc_ReadReg16, XRFdc_SetMixerSettings, XRFdc_SetNyquistZone, XRFDC_TI_DCB_MODE_MASK, XRFdc_WriteReg16.
u32 XRFdc_GetCalibrationMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u8 *CalibrationModePtr)
This API is to get the Calibration mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. CalibrationModePtr pointer to get the calibration mode. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_ADC_TI_DCB_CRL0_OFFSET, XRFDC_ADC_TI_TISK_CRL5_OFFSET, XRFDC_CAL_MODES_MASK, XRFdc_CheckBlockEnabled, XRFdc_CheckDigitalPathEnabled, XRFdc_IsHighSpeedADC, XRFdc_RDReg, XRFDC_TI_DCB_MODE_MASK.
Referenced by XRFdc_GetMixerSettings, XRFdc_GetNyquistZone, XRFdc_SetMixerSettings, XRFdc_SetNyquistZone.
u32 XRFdc_GetClockSource(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 *ClockSourcePtr)
This function gets Clock source.
InstancePtr is a pointer to the XRfdc instance. Type indicates ADC/DAC. Tile_Id indicates Tile number (0-3). ClockSourcePtr Pointer to return the clock source XRFDC_SUCCESS if successful.XRFDC_FAILURE if tile not enabled. None.
References XRFdc_CheckTileEnabled, XRFDC_CLK_NETWORK_CTRL1, XRFDC_CLK_NETWORK_CTRL1_USE_PLL_MASK, XRFDC_PLL_DIVIDER0, XRFdc_RDReg, XRFdc_ReadReg16.
Referenced by XRFdc_DynamicPLLConfig, XRFdc_GetPLLConfig, XRFdc_GetPLLLockStatus.
u32 XRFdc_GetPLLLockStatus(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 *LockStatusPtr)
This function gets PLL lock status.
InstancePtr is a pointer to the XRfdc instance. Type indicates ADC/DAC. Tile_Id indicates Tile number (0-3). LockStatusPtr Pointer to return the PLL lock status XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
References XRFdc_GetClockSource, XRFDC_PLL_LOCKED_MASK, XRFdc_RDReg, XRFDC_STATUS_OFFSET.
u32 XRFdc_GetPLLConfig(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, XRFdc_PLL_Settings *PLLSettings)
This API is used to get the PLL Configurations.
InstancePtr is a pointer to the XRfdc instance. Type represents ADC or DAC. Tile_Id Valid values are 0-3. PLLSettings pointer to the XRFdc_PLL_Settings structure to get the PLL configurations None.
References XRFdc_CheckTileEnabled, XRFdc_GetClockSource, XRFDC_PLL_DIVIDER0, XRFDC_PLL_FPDIV, XRFDC_PLL_FREQ, XRFDC_PLL_FS, XRFDC_PLL_REFDIV, XRFdc_RDReg, XRFdc_ReadReg, XRFdc_ReadReg16, XRFDC_REFCLK_DIV_2_MASK, XRFDC_REFCLK_DIV_3_MASK, XRFDC_REFCLK_DIV_4_MASK.
Referenced by XRFdc_GetClkDistribution.
u32 XRFdc_DynamicPLLConfig(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u8 Source, double RefClkFreq, double SamplingRate)
This function used for dynamically switch between internal PLL and external clcok source and configuring the internal PLL.
InstancePtr is a pointer to the XRfdc instance. Type indicates ADC/DAC Tile_Id indicates Tile number (0-3) Source Clock source internal PLL or external clock source RefClkFreq Reference Clock Frequency in MHz(102.40625MHz - 1.2GHz) SamplingRate Sampling Rate in MHz(0.1- 6.554GHz for DAC and 0.5/1.0 - 2.058/4.116GHz for ADC based on the device package). XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. This API enables automatic selection of the VCO which will work in IP version 2.0.1 and above. Using older version of IP this API is not likely to work.
References XRFDC_ADC_DAC_MC_CFG0_OFFSET, XRFDC_CAL_DIV_BYP_MASK, XRFDC_CAL_DIV_BYP_OFFSET, XRFDC_CAL_DLY_OFFSET, XRFDC_CAL_TMR_MULT_OFFSET, XRFdc_CheckTileEnabled, XRFDC_CLK_NETWORK_CTRL1, XRFDC_CLK_NETWORK_CTRL1_REGS_MASK, XRFDC_CLK_NETWORK_CTRL1_USE_PLL_MASK, XRFdc_ClrSetReg, XRFdc_CustomStartUp, XRFdc_GetClockSource, XRFdc_GetMaxSampleRate, XRFdc_GetMinSampleRate, XRFdc_GetTileLayout, XRFDC_HSCOM_CLK_DSTR_OFFSET, XRFDC_HSCOM_PWR_STATE_OFFSET, XRFdc_IsHighSpeedADC, XRFDC_PLL_DIVIDER0, XRFDC_PLL_FREQ, XRFDC_PLL_FS, XRFDC_PWR_UP_STAT_MASK, XRFDC_PWR_UP_STAT_SHIFT, XRFdc_RDReg, XRFdc_ReadReg, XRFdc_ReadReg16, XRFDC_RX_PR_MC_CFG0_IDIV_MASK, XRFDC_RX_PR_MC_CFG0_PSNK_MASK, XRFDC_STATUS_OFFSET, XRFdc_WriteReg, XRFdc_WriteReg16.
u32 XRFdc_SetInvSincFIR(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u16 Mode)
This API is used to set the mode for the Inverse-Sinc filter.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is DAC block number inside the tile. Valid values are 0-3. Mode valid values are 0(disable), 1(1st Nyquist zone) and 2(2nd Nyquist zone). XRFDC_SUCCESS if successful.XRFDC_FAILURE if block not enabled/invalid mode. Only DAC blocks
References XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFDC_DAC_INVSINC_OFFSET, XRFDC_EN_INVSINC_MASK, XRFdc_GetNyquistZone, XRFDC_MODE_INVSINC_MASK.
u32 XRFdc_GetInvSincFIR(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u16 *ModePtr)
This API is used to get the Inverse-Sinc filter mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is DAC block number inside the tile. Valid values are 0-3. ModePtr is a pointer to get the inv-sinc status. valid values are 0(disable), 1(1st Nyquist zone) and 2(2nd Nyquist zone). XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only DAC blocks
References XRFdc_CheckBlockEnabled, XRFDC_DAC_INVSINC_OFFSET, XRFDC_EN_INVSINC_MASK, XRFDC_MODE_INVSINC_MASK, XRFdc_RDReg.
u32 XRFdc_GetCoupling(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 *ModePtr)
This function is used to get the Coupling mode.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC. Tile_Id indicates Tile number. Block_Id indicates Block number. ModePtr pointer to get link coupling mode. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
References XRFDC_ADC_RXPR_MC_CFG0_OFFSET, XRFdc_CheckBlockEnabled, XRFDC_CPL_TYPE_OFFSET, XRFdc_IsHighSpeedADC, XRFdc_RDReg, XRFdc_ReadReg, XRFDC_RX_MC_CFG0_CM_MASK.
u32 XRFdc_GetLinkCoupling(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *ModePtr)
This function is used to get the Link Coupling mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id indicates Tile number (0-3). Block_Id indicates Block number(0-3 for 2G, 0-1 for 4G). ModePtr pointer to get link coupling mode. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_ADC_RXPR_MC_CFG0_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_IsHighSpeedADC, XRFdc_RDReg, XRFDC_RX_MC_CFG0_CM_MASK.
u32 XRFdc_GetFabClkOutDiv(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u16 *FabClkDivPtr)
This API is to get the divider for clock fabric out.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. FabClkDivPtr is a pointer to get fabric clock for a tile. XRFDC_FAB_CLK_* defines the valid divider values. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. API is applicable for both ADC and DAC Tiles
References XRFdc_CheckTileEnabled, XRFDC_FAB_CLK_DIV_MASK, XRFDC_HSCOM_CLK_DIV_OFFSET, XRFdc_RDReg.
u32 XRFdc_SetDither(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 Mode)
This function is used to set the IM3 Dither mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id indicates Tile number (0-3). Block_Id indicates Block number(0-3 for LS, 0-1 for HS). Mode 0: Disable 1: Enable XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_ADC_DAC_MC_CFG0_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFdc_IsHighSpeedADC, XRFDC_RX_MC_CFG0_IM3_DITH_MASK, XRFDC_RX_MC_CFG0_IM3_DITH_SHIFT.
u32 XRFdc_GetDither(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *ModePtr)
This function is used to get the IM3 Dither mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id indicates Tile number (0-3). Block_Id indicates Block number(0-3 for LS, 0-1 for HS). ModePtr pointer to get link coupling mode. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_ADC_DAC_MC_CFG0_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_IsHighSpeedADC, XRFdc_RDReg, XRFDC_RX_MC_CFG0_IM3_DITH_MASK.
u32 XRFdc_SetClkDistribution(XRFdc *InstancePtr, XRFdc_Distribution_Settings *DistributionSettingsPtr)
This function is used to set the clock distribution.
InstancePtr is a pointer to the XRfdc instance. DistributionSettingsPtr pointer to the distribution settings struct XRFDC_SUCCESS if successful.XRFDC_FAILURE if could not set distribution.
References XRFDC_CLOCK_DETECT_DST_SHIFT, XRFDC_CLOCK_DETECT_MASK, XRFDC_CLOCK_DETECT_OFFSET, XRFDC_CLOCK_DETECT_SRC_MASK, XRFdc_ClrSetReg, XRFdc_GetTileLayout, XRFDC_HSCOM_CLK_DSTR_MASK, XRFDC_HSCOM_CLK_DSTR_OFFSET, XRFDC_PWR_STATE_MASK, XRFdc_RDReg, XRFDC_RESTART_MASK, XRFDC_RESTART_OFFSET, XRFDC_RESTART_STATE_OFFSET, XRFDC_RSR_START_SHIFT, XRFdc_WaitForState, XRFdc_WriteReg.
u32 XRFdc_GetClkDistribution(XRFdc *InstancePtr, XRFdc_Distribution_System_Settings *DistributionSystemPtr)
This function is used to get the clock distribution.
InstancePtr is a pointer to the XRfdc instance. DistributionSettingsPtr pointer to get the distribution settings XRFDC_SUCCESS if successful.XRFDC_FAILURE if no valid distribution found.
References XRFdc_CheckTileEnabled, XRFDC_CLOCK_DETECT_OFFSET, XRFDC_CLOCK_DETECT_SRC_MASK, XRFdc_GetPLLConfig, XRFdc_GetTileLayout, XRFDC_HSCOM_CLK_DSTR_OFFSET, XRFdc_RDReg, XRFdc_ReadReg16.
u32 XRFdc_SetDataPathMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 Mode)
This API is to set the DAC Datapath mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Mode valid values are 0-3. XRFDC_SUCCESS if successful.XRFDC_FAILURE if tile not enabled / out of range. Only for DAC blocks
References XRFdc_CheckBlockEnabled, XRFdc_CheckDigitalPathEnabled, XRFdc_ClrSetReg, XRFDC_DAC_DATAPATH_OFFSET, XRFDC_DAC_FAB_RATE_RD_MASK, XRFDC_DAC_FABRIC_RATE_OFFSET, XRFDC_DAC_INTERP_CTRL_OFFSET, XRFDC_DAC_INTERP_DATA_MASK, XRFDC_DAC_ITERP_DATA_OFFSET, XRFDC_DATAPATH_IMR_MASK, XRFDC_DATAPATH_IMR_SHIFT, XRFDC_DATAPATH_MODE_MASK, XRFDC_FAB_CLK_DIV_CAL_MASK, XRFDC_FAB_RATE_RD_SHIFT, XRFdc_GetMixerSettings, XRFDC_HSCOM_CLK_DIV_OFFSET, XRFDC_INTERP_MODE_I_MASK_EXT, XRFDC_INTERP_MODE_MASK_EXT, XRFdc_RDReg, XRFdc_SetMixerSettings.
u32 XRFdc_GetDataPathMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *ModePtr)
This API is to get the DAC Datapath mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. ModePtr pointer used to return value. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for DAC blocks
References XRFdc_CheckDigitalPathEnabled, XRFDC_DAC_DATAPATH_OFFSET, XRFDC_DATAPATH_IMR_MASK, XRFDC_DATAPATH_IMR_SHIFT, XRFDC_DATAPATH_MODE_MASK, XRFdc_RDReg.
u32 XRFdc_SetIMRPassMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 Mode)
This API is to set the DAC Image Reject Filter Pass mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Mode valid values are 0 (for low pass) 1 (for high pass). XRFDC_SUCCESS if successful.XRFDC_FAILURE if tile not enabled / bad parameter passed Only for DAC blocks
References XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFDC_DAC_DATAPATH_OFFSET, XRFDC_DATAPATH_IMR_MASK.
u32 XRFdc_GetIMRPassMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *ModePtr)
This API is to get the DAC Image Reject Filter Pass mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. ModePtr pointer used to return value. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for DAC blocks
References XRFdc_CheckBlockEnabled, XRFDC_DAC_DATAPATH_OFFSET, XRFDC_DATAPATH_IMR_MASK, XRFdc_RDReg.
u32 XRFdc_SetSignalDetector(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, XRFdc_Signal_Detector_Settings *SettingsPtr)
This function is used to set the ADC Signal Detector Settings.
InstancePtr is a pointer to the XRfdc instance. Tile_Id indicates Tile number (0-3). Block_Id indicates Block number(0-3 for LS, 0-1 for HS). SettingsPtr pointer to the XRFdc_Signal_Detector_Settings structure to set the signal detector configurations XRFDC_SUCCESS if successful.XRFDC_FAILURE if tile not enabled, or invalid values. Only for ADC blocks
References XRFDC_ADC_SIG_DETECT_CTRL_OFFSET, XRFDC_ADC_SIG_DETECT_FLUSH_SHIFT, XRFDC_ADC_SIG_DETECT_HYST_SHIFT, XRFDC_ADC_SIG_DETECT_INTG_SHIFT, XRFDC_ADC_SIG_DETECT_MASK, XRFDC_ADC_SIG_DETECT_MODE_WRITE_SHIFT, XRFDC_ADC_SIG_DETECT_TCONST_SHIFT, XRFDC_ADC_SIG_DETECT_THRESHOLD0_CNT_OFF_OFFSET, XRFDC_ADC_SIG_DETECT_THRESHOLD0_CNT_ON_OFFSET, XRFDC_ADC_SIG_DETECT_THRESHOLD0_LEVEL_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFdc_IsHighSpeedADC, XRFdc_WriteReg16.
u32 XRFdc_GetSignalDetector(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, XRFdc_Signal_Detector_Settings *SettingsPtr)
This function is used to get the ADC Signal Detector Settings.
InstancePtr is a pointer to the XRfdc instance. Tile_Id indicates Tile number (0-3). Block_Id indicates Block number(0-3 for LS, 0-1 for HS). SettingsPtr pointer to the XRFdc_Signal_Detector_Settings structure to get the signal detector configurations XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_ADC_SIG_DETECT_CTRL_OFFSET, XRFDC_ADC_SIG_DETECT_FLUSH_MASK, XRFDC_ADC_SIG_DETECT_FLUSH_SHIFT, XRFDC_ADC_SIG_DETECT_HYST_MASK, XRFDC_ADC_SIG_DETECT_HYST_SHIFT, XRFDC_ADC_SIG_DETECT_INTG_MASK, XRFDC_ADC_SIG_DETECT_INTG_SHIFT, XRFDC_ADC_SIG_DETECT_MASK, XRFDC_ADC_SIG_DETECT_MODE_MASK, XRFDC_ADC_SIG_DETECT_MODE_READ_SHIFT, XRFDC_ADC_SIG_DETECT_TCONST_MASK, XRFDC_ADC_SIG_DETECT_TCONST_SHIFT, XRFDC_ADC_SIG_DETECT_THRESHOLD0_CNT_OFF_OFFSET, XRFDC_ADC_SIG_DETECT_THRESHOLD0_CNT_ON_OFFSET, XRFDC_ADC_SIG_DETECT_THRESHOLD0_LEVEL_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_IsHighSpeedADC, XRFdc_RDReg, XRFdc_ReadReg16.
u32 XRFdc_DisableCoefficientsOverride(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 CalibrationBlock)
This function is used to disable Calibration Coefficients override.
InstancePtr is a pointer to the XRfdc instance. Tile_Id indicates Tile number (0-3). Block_Id indicates Block number(0-3 for LS, 0-1 for HS). CalibrationBlock indicates the calibration block. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_ADC_TI_DCB_CRL1_OFFSET, XRFDC_ADC_TI_DCB_CRL3_OFFSET, XRFDC_CAL_GCB_ACEN_MASK, XRFDC_CAL_GCB_EN_MASK, XRFDC_CAL_GCB_ENFL_MASK, XRFDC_CAL_GCB_MASK, XRFDC_CAL_OCB_EN_MASK, XRFDC_CAL_TSCB_EN_MASK, XRFDC_CAL_TSCB_OFFSET_COEFF0, XRFDC_CAL_TSCB_OFFSET_COEFF0_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF1, XRFDC_CAL_TSCB_OFFSET_COEFF1_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF2, XRFDC_CAL_TSCB_OFFSET_COEFF2_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF3, XRFDC_CAL_TSCB_OFFSET_COEFF3_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF4, XRFDC_CAL_TSCB_OFFSET_COEFF4_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF5, XRFDC_CAL_TSCB_OFFSET_COEFF5_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF6, XRFDC_CAL_TSCB_OFFSET_COEFF6_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF7, XRFDC_CAL_TSCB_OFFSET_COEFF7_ALT, XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFdc_IsHighSpeedADC.
u32 XRFdc_SetCalCoefficients(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 CalibrationBlock, XRFdc_Calibration_Coefficients *CoeffPtr)
This function is used to set the ADC Calibration Coefficients.
InstancePtr is a pointer to the XRfdc instance. Tile_Id indicates Tile number (0-3). Block_Id indicates Block number(0-3 for LS, 0-1 for HS). CalibrationBlock indicates the block to be written to. CoeffPtr is pointer to the XRFdc_Calibration_Coefficients structure to set the calibration coefficients. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_ADC_TI_DCB_CRL1_OFFSET, XRFDC_ADC_TI_DCB_CRL3_OFFSET, XRFDC_CAL_GCB_ACEN_MASK, XRFDC_CAL_GCB_EN_MASK, XRFDC_CAL_GCB_EN_SHIFT, XRFDC_CAL_GCB_FLSH_MASK, XRFDC_CAL_GCB_FLSH_SHIFT, XRFDC_CAL_GCB_MASK, XRFDC_CAL_GCB_OFFSET_COEFF0, XRFDC_CAL_GCB_OFFSET_COEFF1, XRFDC_CAL_GCB_OFFSET_COEFF2, XRFDC_CAL_GCB_OFFSET_COEFF3, XRFDC_CAL_OCB1_OFFSET_COEFF0, XRFDC_CAL_OCB1_OFFSET_COEFF1, XRFDC_CAL_OCB1_OFFSET_COEFF2, XRFDC_CAL_OCB1_OFFSET_COEFF3, XRFDC_CAL_OCB2_OFFSET_COEFF0, XRFDC_CAL_OCB2_OFFSET_COEFF1, XRFDC_CAL_OCB2_OFFSET_COEFF2, XRFDC_CAL_OCB2_OFFSET_COEFF3, XRFDC_CAL_OCB_EN_MASK, XRFDC_CAL_OCB_MASK, XRFDC_CAL_SLICE_SHIFT, XRFDC_CAL_TSCB_EN_MASK, XRFDC_CAL_TSCB_EN_SHIFT, XRFDC_CAL_TSCB_MASK, XRFDC_CAL_TSCB_OFFSET_COEFF0, XRFDC_CAL_TSCB_OFFSET_COEFF0_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF1, XRFDC_CAL_TSCB_OFFSET_COEFF1_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF2, XRFDC_CAL_TSCB_OFFSET_COEFF2_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF3, XRFDC_CAL_TSCB_OFFSET_COEFF3_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF4, XRFDC_CAL_TSCB_OFFSET_COEFF4_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF5, XRFDC_CAL_TSCB_OFFSET_COEFF5_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF6, XRFDC_CAL_TSCB_OFFSET_COEFF6_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF7, XRFDC_CAL_TSCB_OFFSET_COEFF7_ALT, XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFdc_IsHighSpeedADC.
u32 XRFdc_GetCalCoefficients(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 CalibrationBlock, XRFdc_Calibration_Coefficients *CoeffPtr)
This function is used to get the ADC Calibration Coefficients.
InstancePtr is a pointer to the XRfdc instance. Tile_Id indicates Tile number (0-3). Block_Id indicates Block number(0-3 for LS, 0-1 for HS). CalibrationBlock indicates the block to be read from CoeffPtr is pointer to the XRFdc_Calibration_Coefficients structure to get the calibration coefficients. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_ADC_TI_DCB_CRL1_OFFSET, XRFDC_CAL_GCB_FAB_MASK, XRFDC_CAL_GCB_FLSH_MASK, XRFDC_CAL_GCB_MASK, XRFDC_CAL_GCB_OFFSET_COEFF0, XRFDC_CAL_GCB_OFFSET_COEFF0_ALT, XRFDC_CAL_GCB_OFFSET_COEFF1, XRFDC_CAL_GCB_OFFSET_COEFF1_ALT, XRFDC_CAL_GCB_OFFSET_COEFF2, XRFDC_CAL_GCB_OFFSET_COEFF2_ALT, XRFDC_CAL_GCB_OFFSET_COEFF3, XRFDC_CAL_GCB_OFFSET_COEFF3_ALT, XRFDC_CAL_OCB1_OFFSET_COEFF0, XRFDC_CAL_OCB1_OFFSET_COEFF1, XRFDC_CAL_OCB1_OFFSET_COEFF2, XRFDC_CAL_OCB1_OFFSET_COEFF3, XRFDC_CAL_OCB2_OFFSET_COEFF0, XRFDC_CAL_OCB2_OFFSET_COEFF1, XRFDC_CAL_OCB2_OFFSET_COEFF2, XRFDC_CAL_OCB2_OFFSET_COEFF3, XRFDC_CAL_OCB_MASK, XRFDC_CAL_SLICE_SHIFT, XRFDC_CAL_TSCB_MASK, XRFDC_CAL_TSCB_OFFSET_COEFF0, XRFDC_CAL_TSCB_OFFSET_COEFF0_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF1, XRFDC_CAL_TSCB_OFFSET_COEFF1_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF2, XRFDC_CAL_TSCB_OFFSET_COEFF2_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF3, XRFDC_CAL_TSCB_OFFSET_COEFF3_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF4, XRFDC_CAL_TSCB_OFFSET_COEFF4_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF5, XRFDC_CAL_TSCB_OFFSET_COEFF5_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF6, XRFDC_CAL_TSCB_OFFSET_COEFF6_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF7, XRFDC_CAL_TSCB_OFFSET_COEFF7_ALT, XRFdc_CheckBlockEnabled, XRFdc_IsHighSpeedADC, XRFdc_RDReg.
u32 XRFdc_SetCalFreeze(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, XRFdc_Cal_Freeze_Settings *CalFreezePtr)
This function is used to set calibration freeze settings.
InstancePtr is a pointer to the XRfdc instance. Tile_Id indicates Tile number (0-3). Block_Id indicates Block number(0-3 for LS, 0-1 for HS). CalFreezePtr pointer to the settings to be applied. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_CAL_FREEZE_CAL_MASK, XRFDC_CAL_FREEZE_CAL_SHIFT, XRFDC_CAL_FREEZE_PIN_MASK, XRFDC_CAL_FREEZE_PIN_SHIFT, XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFdc_IsHighSpeedADC.
u32 XRFdc_GetCalFreeze(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, XRFdc_Cal_Freeze_Settings *CalFreezePtr)
This function is used to get calibration freeze settings and status.
InstancePtr is a pointer to the XRfdc instance. Tile_Id indicates Tile number (0-3). Block_Id indicates Block number(0-3 for LS, 0-1 for HS). CalFreezePtr pointer to be filled the settings/status. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_CAL_FREEZE_CAL_MASK, XRFDC_CAL_FREEZE_CAL_SHIFT, XRFDC_CAL_FREEZE_PIN_MASK, XRFDC_CAL_FREEZE_PIN_SHIFT, XRFDC_CAL_FREEZE_STS_MASK, XRFDC_CAL_FREEZE_STS_SHIFT, XRFdc_CheckBlockEnabled, XRFdc_IsHighSpeedADC, XRFdc_RDReg.
u32 XRFdc_SetDACVOP(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 uACurrent)
Set Output Current for DAC block.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. uACurrent is the current in uA. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Range 6425 - 32000 uA with 25 uA resolution.
References XRFDC_ADC_DAC_MC_CFG0_OFFSET, XRFDC_ADC_DAC_MC_CFG2_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFDC_CPL_TYPE_OFFSET, XRFDC_DAC_MC_CFG3_OFFSET, XRFDC_DAC_VOP_CTRL_OFFSET, XRFdc_RDReg, XRFdc_ReadReg.
u32 XRFdc_SetDACCompMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 Enable)
Sets VOP compatibility mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. mode is ADC/DAC block number inside the tile. Valid values are 0-3. Enable is whether to enable (1) or disable(0) the compatibility mode. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
References XRFDC_ADC_DAC_MC_CFG2_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg.
u32 XRFdc_GetDACCompMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *EnabledPtr)
Gets VOP compatibility mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. mode is ADC/DAC block number inside the tile. Valid values are 0-3. EnabledPtr is pointer a that is filled with whether the mode is enabled (1) or disabled(0). XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
References XRFDC_ADC_DAC_MC_CFG2_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_RDReg.
u32 XRFdc_SetDSA(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, XRFdc_DSA_Settings *SettingsPtr)
Set DSA for ADC block.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Attenuation is the attenuation in dB XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Range 0 - 11 dB with 0.5 dB resolution ES1 Si. Range 0 - 27 dB with 1 dB resolution for Production Si.
References XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFDC_DSA_UPDT_OFFSET, XRFdc_IsHighSpeedADC.
u32 XRFdc_GetDSA(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, XRFdc_DSA_Settings *SettingsPtr)
Get DSA for ADC block.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. AttenuationPtr is the attenuation in dB XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Range 0 - 11 dB with 0.5 dB resolution ES1 Si. Range 0 - 27 dB with 1 dB resolution for Production Si.
References XRFdc_CheckBlockEnabled, XRFdc_IsHighSpeedADC, XRFdc_RDReg, XRFdc_ReadReg16.
u32 XRFdc_SetPwrMode(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, XRFdc_Pwr_Mode_Settings *SettingsPtr)
Set The Power up/down mode of a given converter.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id Valid values are 0-3. SettingsPtr is a pointer with the power mode settings. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Common API for ADC/DAC blocks
References XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFdc_IsHighSpeedADC, XRFDC_TDD_CTRL_MODE0_MASK, XRFDC_TDD_CTRL_RTP_MASK, XRFDC_TDD_CTRL_RTP_SHIFT, XRFDC_TDD_CTRL_SLICE_OFFSET.
u32 XRFdc_GetPwrMode(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, XRFdc_Pwr_Mode_Settings *SettingsPtr)
Get The Power up/down mode of a given converter.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id Valid values are 0-3. SettingsPtr is a pointer to be filled with the power mode settings. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Common API for ADC/DAC blocks
References XRFdc_CheckBlockEnabled, XRFdc_IsHighSpeedADC, XRFdc_RDReg, XRFDC_TDD_CTRL_MODE0_MASK, XRFDC_TDD_CTRL_RTP_MASK, XRFDC_TDD_CTRL_RTP_SHIFT, XRFDC_TDD_CTRL_SLICE_OFFSET.
u32 XRFdc_ResetInternalFIFOWidth(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id)
Set the correct FIFO width for current mixer & rate change settings.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id Valid values are 0-3. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Common API for ADC/DAC blocks
References XRFdc_CheckDigitalPathEnabled.
Referenced by XRFdc_SetMixerSettings.
u32 XRFdc_ResetInternalFIFOWidthObs(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id)
Set the correct Observation FIFO width for current mixer & rate change settings.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id Valid values are 0-3. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. ADC blocks only
References XRFdc_CheckDigitalPathEnabled.
void XRFdc_ClrSetReg(XRFdc *InstancePtr, u32 BaseAddr, u32 RegAddr, u16 Mask, u16 Data)
Execute Read modify Write.
InstancePtr is a pointer to the XRfdc instance. BaseAddr is address of a block. RegAddr is register offset value. Mask contains bit mask value. Data contains value to be written to register. None
References XRFdc_ReadReg16, XRFdc_WriteReg16.
Referenced by XRFdc_CustomStartUp, XRFdc_DisableCoefficientsOverride, XRFdc_DynamicPLLConfig, XRFdc_IntrEnable, XRFdc_ResetNCOPhase, XRFdc_SetCalCoefficients, XRFdc_SetCalFreeze, XRFdc_SetCalibrationMode, XRFdc_SetClkDistribution, XRFdc_SetCoarseDelaySettings, XRFdc_SetDACCompMode, XRFdc_SetDACDataScaler, XRFdc_SetDACVOP, XRFdc_SetDataPathMode, XRFdc_SetDecoderMode, XRFdc_SetDither, XRFdc_SetDSA, XRFdc_SetFabClkOutDiv, XRFdc_SetFabWrVldWords, XRFdc_SetIMRPassMode, XRFdc_SetInterpolationFactor, XRFdc_SetInvSincFIR, XRFdc_SetMixerSettings, XRFdc_SetPwrMode, XRFdc_SetQMCSettings, XRFdc_SetSignalDetector, XRFdc_SetThresholdSettings, XRFdc_ThresholdStickyClear.
void XRFdc_ClrReg(XRFdc *InstancePtr, u32 BaseAddr, u32 RegAddr, u16 Mask)
Execute Read and clear.
InstancePtr is a pointer to the XRfdc instance. BaseAddr is address of a block. RegAddr is register offset value. Mask contains bit mask value. None
References XRFdc_ReadReg16, XRFdc_WriteReg16.
Referenced by XRFdc_IntrDisable.
u16 XRFdc_RDReg(XRFdc *InstancePtr, u32 BaseAddr, u32 RegAddr, u16 Mask)
Execute Read and mask with the value.
InstancePtr is a pointer to the XRfdc instance. BaseAddr is address of a block. RegAddr is register offset value. Mask contains bit mask value. None
References XRFdc_ReadReg16.
Referenced by XRFdc_DynamicPLLConfig, XRFdc_GetBlockStatus, XRFdc_GetCalCoefficients, XRFdc_GetCalFreeze, XRFdc_GetCalibrationMode, XRFdc_GetClkDistribution, XRFdc_GetClockSource, XRFdc_GetCoarseDelaySettings, XRFdc_GetConnectedIQData, XRFdc_GetCoupling, XRFdc_GetDACCompMode, XRFdc_GetDACDataScaler, XRFdc_GetDataPathMode, XRFdc_GetDecoderMode, XRFdc_GetDither, XRFdc_GetDSA, XRFdc_GetEnabledInterrupts, XRFdc_GetFabClkOutDiv, XRFdc_GetFIFOStatusInt, XRFdc_GetIMRPassMode, XRFdc_GetInterpolationFactor, XRFdc_GetInvSincFIR, XRFdc_GetLinkCoupling, XRFdc_GetMixerSettings, XRFdc_GetNyquistZone, XRFdc_GetOutputCurr, XRFdc_GetPLLConfig, XRFdc_GetPLLLockStatus, XRFdc_GetPwrMode, XRFdc_GetQMCSettings, XRFdc_GetSignalDetector, XRFdc_GetThresholdSettings, XRFdc_MultiBand, XRFdc_SetClkDistribution, XRFdc_SetDACVOP, XRFdc_SetDataPathMode, XRFdc_SetInterpolationFactor, XRFdc_SetMixerSettings, XRFdc_SetQMCSettings, XRFdc_UpdateEvent, XRFdc_WaitForState.
u32 XRFdc_IsHighSpeedADC(XRFdc *InstancePtr, u32 Tile)
Get ADC type is High Speed or Medium Speed.
InstancePtr is a pointer to the XRfdc instance. Return 1 if ADC type is a dual typeReturn 0 if quad or invalid tile.
Referenced by XRFdc_CustomStartUp, XRFdc_DisableCoefficientsOverride, XRFdc_DynamicPLLConfig, XRFdc_Get_BlockBaseAddr, XRFdc_GetBlockStatus, XRFdc_GetCalCoefficients, XRFdc_GetCalFreeze, XRFdc_GetCalibrationMode, XRFdc_GetCoarseDelaySettings, XRFdc_GetCoupling, XRFdc_GetDither, XRFdc_GetDSA, XRFdc_GetEnabledInterrupts, XRFdc_GetIntrStatus, XRFdc_GetLinkCoupling, XRFdc_GetMaxSampleRate, XRFdc_GetMinSampleRate, XRFdc_GetMixerSettings, XRFdc_GetNyquistZone, XRFdc_GetPwrMode, XRFdc_GetQMCSettings, XRFdc_GetSignalDetector, XRFdc_GetThresholdSettings, XRFdc_IntrClr, XRFdc_IntrDisable, XRFdc_IntrEnable, XRFdc_IntrHandler, XRFdc_IsADCBlockEnabled, XRFdc_IsADCDigitalPathEnabled, XRFdc_MultiBand, XRFdc_ResetNCOPhase, XRFdc_SetCalCoefficients, XRFdc_SetCalFreeze, XRFdc_SetCalibrationMode, XRFdc_SetCoarseDelaySettings, XRFdc_SetDither, XRFdc_SetDSA, XRFdc_SetMixerSettings, XRFdc_SetNyquistZone, XRFdc_SetPwrMode, XRFdc_SetQMCSettings, XRFdc_SetSignalDetector, XRFdc_SetThresholdClrMode, XRFdc_SetThresholdSettings, XRFdc_ThresholdStickyClear, XRFdc_UpdateEvent.
u32 XRFdc_IsDACBlockEnabled(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id)
Checks whether DAC block is available or not.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Return 1 if DAC block is available, otherwise 0.
References XRFDC_DAC_PATHS_ENABLED_OFFSET, XRFDC_PATH_ENABLED_TILE_SHIFT, XRFdc_ReadReg.
Referenced by XRFdc_CheckBlockEnabled, XRFdc_GetIPStatus.
u32 XRFdc_IsADCBlockEnabled(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id)
Checks whether ADC block is available or not.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3 in DAC/ADC-2GSPS and 0-1 in ADC-4GSPS. Return 1 if ADC block is available, otherwise 0.
References XRFDC_ADC_PATHS_ENABLED_OFFSET, XRFdc_IsHighSpeedADC, XRFDC_PATH_ENABLED_TILE_SHIFT, XRFdc_ReadReg.
Referenced by XRFdc_CheckBlockEnabled, XRFdc_GetIPStatus.
u32 XRFdc_IsDACDigitalPathEnabled(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id)
Checks whether DAC Digital path is enabled or not.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Return 1 if DAC digital path is enabled, otherwise 0.
References XRFDC_DAC_PATHS_ENABLED_OFFSET, XRFDC_DIGITAL_PATH_ENABLED_SHIFT, XRFDC_PATH_ENABLED_TILE_SHIFT, XRFdc_ReadReg.
Referenced by XRFdc_CheckDigitalPathEnabled.
u32 XRFdc_IsADCDigitalPathEnabled(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id)
Checks whether ADC digital path is enabled or not.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3 in DAC/ADC-2GSPS and 0-1 in ADC-4GSPS. Return 1 if ADC digital path is enabled, otherwise 0.
References XRFDC_ADC_PATHS_ENABLED_OFFSET, XRFDC_DIGITAL_PATH_ENABLED_SHIFT, XRFdc_IsHighSpeedADC, XRFDC_PATH_ENABLED_TILE_SHIFT, XRFdc_ReadReg.
Referenced by XRFdc_CheckDigitalPathEnabled.
u32 XRFdc_CheckDigitalPathEnabled(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id)
Checks whether ADC/DAC Digital path is enabled or not.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. XRFDC_SUCCESS if Digital path is enabled.XRFDC_FAILURE if Digital path is not enabled.
References XRFdc_IsADCDigitalPathEnabled, XRFdc_IsDACDigitalPathEnabled.
Referenced by XRFdc_GetCalibrationMode, XRFdc_GetConnectedIQData, XRFdc_GetDataPathMode, XRFdc_GetEnabledInterrupts, XRFdc_GetInterpolationFactor, XRFdc_GetIntrStatus, XRFdc_GetMixerSettings, XRFdc_GetNyquistZone, XRFdc_IntrClr, XRFdc_IntrDisable, XRFdc_IntrEnable, XRFdc_MultiBand, XRFdc_ResetInternalFIFOWidth, XRFdc_ResetInternalFIFOWidthObs, XRFdc_ResetNCOPhase, XRFdc_SetCalibrationMode, XRFdc_SetDataPathMode, XRFdc_SetFabWrVldWords, XRFdc_SetInterpolationFactor, XRFdc_SetMixerSettings, XRFdc_UpdateEvent.
u32 XRFdc_Get_IPBaseAddr(XRFdc *InstancePtr)
Get IP BaseAddress.
InstancePtr is a pointer to the XRfdc instance. Return IP BaseAddress.
u32 XRFdc_Get_TileBaseAddr(XRFdc *InstancePtr, u32 Type, u32 Tile_Id)
Get Tile BaseAddress.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Return Tile BaseAddress if valid tile.Return 0U if invalid/unavailable tile.
References XRFdc_CheckTileEnabled.
u32 XRFdc_Get_BlockBaseAddr(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id)
Get Block BaseAddress.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3 in DAC/ADC-2GSPS and 0-1 in ADC-4GSPS. Return Block BaseAddress.Return 0U if invalid/unavailable block.
References XRFdc_CheckBlockEnabled, XRFdc_IsHighSpeedADC.
u32 XRFdc_GetNoOfDACBlock(XRFdc *InstancePtr, u32 Tile_Id)
Get Number of DAC Blocks enabled.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Return number of DAC blocks enabled.
u32 XRFdc_GetNoOfADCBlocks(XRFdc *InstancePtr, u32 Tile_Id)
Get Number of ADC Blocks enabled.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Return number of ADC blocks enabled.
u32 XRFdc_GetDataType(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id)
Get Mixer Input Data Type for ADC/DAC block.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Return MixerInputDataType of ADC/DAC block.Return 0 if invalid
u32 XRFdc_GetDataWidth(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id)
Get Data Width for ADC/DAC block.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Return DataWidth of ADC/DAC block.
u32 XRFdc_GetInverseSincFilter(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id)
Get Inversesync filter for DAC block.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Return Inversesync filter for DAC blockReturn 0 if invalid
u32 XRFdc_GetMixedMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id)
Get Mixed mode for DAC block.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Return mixed mode for DAC blockReturn 0 if invalid
u32 XRFdc_GetMasterTile(XRFdc *InstancePtr, u32 Type)
Get Master Tile for ADC/DAC tiles.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Return Master Tile for ADC/DAC tilesReturn XRFDC_TILE_ID_INV if invalid tile
u32 XRFdc_GetSysRefSource(XRFdc *InstancePtr, u32 Type)
Get Sysref source for ADC/DAC tile.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Return Sysref source for ADC/DAC tileReturn XRFDC_TILE_ID_INV if invalid tile
double XRFdc_GetFabClkFreq(XRFdc *InstancePtr, u32 Type, u32 Tile_Id)
Get Fabric Clock frequency.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Return Fabric Clock frequency for ADC/DAC tile
u32 XRFdc_IsFifoEnabled(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id)
Get whether FIFO is enabled or not.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Return 1 if FIFO is enabled, otherwise 0.
void XRFdc_SetConnectedIQData(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, int ConnectedIData, int ConnectedQData)
Set Data Converter connected for digital data path I and Q.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is Digital Data Path number. ConnectedIData is Converter Id to which DigitalPathI connected. ConnectedQData is Converter Id to which DigitalPathQ connected. None.
u32 XRFdc_GetMultibandConfig(XRFdc *InstancePtr, u32 Type, u32 Tile_Id)
Get Multiband Config data.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Return Multiband Configuration.Return 0 if invalid.
References XRFDC_MB_CONFIG_OFFSET, XRFdc_ReadReg.
u32 XRFdc_CheckBlockEnabled(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id)
Checks whether ADC/DAC block is enabled or not.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. XRFDC_SUCCESS if block enabled.XRFDC_FAILURE if block not enabled.
References XRFdc_IsADCBlockEnabled, XRFdc_IsDACBlockEnabled.
Referenced by XRFdc_DisableCoefficientsOverride, XRFdc_Get_BlockBaseAddr, XRFdc_GetBlockStatus, XRFdc_GetCalCoefficients, XRFdc_GetCalFreeze, XRFdc_GetCalibrationMode, XRFdc_GetCoarseDelaySettings, XRFdc_GetCoupling, XRFdc_GetDACCompMode, XRFdc_GetDACDataScaler, XRFdc_GetDecoderMode, XRFdc_GetDither, XRFdc_GetDSA, XRFdc_GetEnabledInterrupts, XRFdc_GetIMRPassMode, XRFdc_GetIntrStatus, XRFdc_GetInvSincFIR, XRFdc_GetLinkCoupling, XRFdc_GetNyquistZone, XRFdc_GetOutputCurr, XRFdc_GetPwrMode, XRFdc_GetQMCSettings, XRFdc_GetSignalDetector, XRFdc_GetThresholdSettings, XRFdc_IntrClr, XRFdc_IntrDisable, XRFdc_IntrEnable, XRFdc_MultiBand, XRFdc_MultiConverter_Sync, XRFdc_SetCalCoefficients, XRFdc_SetCalFreeze, XRFdc_SetCalibrationMode, XRFdc_SetCoarseDelaySettings, XRFdc_SetDACCompMode, XRFdc_SetDACDataScaler, XRFdc_SetDACVOP, XRFdc_SetDataPathMode, XRFdc_SetDecoderMode, XRFdc_SetDither, XRFdc_SetDSA, XRFdc_SetIMRPassMode, XRFdc_SetInvSincFIR, XRFdc_SetNyquistZone, XRFdc_SetPwrMode, XRFdc_SetQMCSettings, XRFdc_SetSignalDetector, XRFdc_SetThresholdClrMode, XRFdc_SetThresholdSettings, XRFdc_ThresholdStickyClear, XRFdc_UpdateEvent.
u32 XRFdc_CheckTileEnabled(XRFdc *InstancePtr, u32 Type, u32 Tile_Id)
Checks whether ADC/DAC tile is enabled or not.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC. Tile_Id Valid values are 0-3. XRFDC_SUCCESS if tile enabled.XRFDC_FAILURE if tile not enabled.
References XRFDC_DAC_TILES_ENABLED_SHIFT, XRFdc_ReadReg, XRFDC_TILES_ENABLED_OFFSET.
Referenced by XRFdc_DynamicPLLConfig, XRFdc_Get_TileBaseAddr, XRFdc_GetClkDistribution, XRFdc_GetClockSource, XRFdc_GetFabClkOutDiv, XRFdc_GetFIFOStatusInt, XRFdc_GetMTSEnable, XRFdc_GetPLLConfig, XRFdc_SetFabClkOutDiv, XRFdc_WaitForState.
u32 XRFdc_GetMaxSampleRate(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, double *MaxSampleRatePtr)
Gets ADC/DAC tile maximum sampling rate.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC. Tile_Id Valid values are 0-3. MaxSampleRatePtr pointer for maximum sample rate. XRFDC_SUCCESS if found sampling rate.XRFDC_FAILURE if could not find sampling rate.
References XRFdc_IsHighSpeedADC.
Referenced by XRFdc_DynamicPLLConfig.
u32 XRFdc_GetMinSampleRate(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, double *MinSampleRatePtr)
Gets ADC/DAC tile minimum sampling rate.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC. Tile_Id Valid values are 0-3. MinSampleRatePtr pointer for minimum sample rate. XRFDC_SUCCESS if found sampling rate.XRFDC_FAILURE if could not find sampling rate.
References XRFdc_IsHighSpeedADC.
Referenced by XRFdc_DynamicPLLConfig.
double XRFdc_GetDriverVersion(void)
This API is used to get the driver version.
None Driver version number None.
u32 XRFdc_MultiConverter_Sync(XRFdc *InstancePtr, u32 Type, XRFdc_MultiConverter_Sync_Config *ConfigPtr)
This is the top level API which will be used for Multi-tile Synchronization.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC ConfigPtr Multi-tile sync config structure. XRFDC_MTS_OK if successful. XRFDC_MTS_TIMEOUT if timeout occurs. XRFDC_MTS_MARKER_RUNXRFDC_MTS_MARKER_MISMXRFDC_MTS_NOT_SUPPORTED if MTS is not supported. None.
References XRFdc_CheckBlockEnabled, XRFdc_GetIPStatus, XRFdc_ReadReg.
Referenced by RFdcMTS_Example.
u32 XRFdc_MultiConverter_Init(XRFdc_MultiConverter_Sync_Config *ConfigPtr, int *PLL_CodesPtr, int *T1_CodesPtr, u32 RefTile)
This API Initializes the multi-tile sync config structures.
Optionally allows target codes to be provided for the Pll/T1 analog sysref capture ConfigPtr pointer to Multi-tile sync config structure. PLL_CodesPtr pointer to PLL analog sysref capture. T1_CodesPtr pointer to T1 analog sysref capture. RefTile the tile ID of the reference tile. XRFDC_MTS_OK if successful.XRFDC_MTS_BAD_REF_TILE if bad reference tile value is supplied. None.
Referenced by RFdcMTS_Example.
u32 XRFdc_MTS_Sysref_Config(XRFdc *InstancePtr, XRFdc_MultiConverter_Sync_Config *DACSyncConfigPtr, XRFdc_MultiConverter_Sync_Config *ADCSyncConfigPtr, u32 SysRefEnable)
This API is used to enable/disable the sysref.
InstancePtr is a pointer to the XRfdc instance. DACSyncConfigPtr is pointer to DAC Multi-Tile Sync config structure. ADCSyncConfigPtr is pointer to ADC Multi-Tile Sync config structure. SysRefEnable valid values are 0(disable) and 1(enable). XRFDC_MTS_OK if successful. None.
u32 XRFdc_GetMTSEnable(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 *EnablePtr)
This is the top level API which will be used to check if Multi-tile is enabled.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC. Tile_Id indicates Tile number (0-3). EnablePtr to be filled with the enable state. XRFDC_SUCCESS if successful.XRFDC_SUCCESS if error occurs. None.
References XRFdc_CheckTileEnabled, XRFdc_ReadReg.
u32 XRFdc_SetDACDataScaler(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 Enable)
Set data scaler for DAC block.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Enable valid values are 1 (enable) and 0 (disable). XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. DAC blocks only.
References XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFDC_DATA_SCALER_MASK, XRFDC_DATA_SCALER_OFFSET.
u32 XRFdc_GetDACDataScaler(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *EnablePtr)
Get data scaler for DAC block.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. EnablePtr valid values are 1 (enable) and 0 (disable). XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. DAC blocks only.
References XRFdc_CheckBlockEnabled, XRFDC_DATA_SCALER_MASK, XRFDC_DATA_SCALER_OFFSET, XRFdc_RDReg.
u8 XRFdc_GetTileLayout(XRFdc *InstancePtr)
Gets whether the device is a DFE variant or not.
InstancePtr is a pointer to the XRfdc instance. XRFDC_3ADC_2DAC_TILES if DFE variant.XRFDC_4ADC_4DAC_TILES if regular Gen 1/2/3.
Referenced by XRFdc_DynamicPLLConfig, XRFdc_GetClkDistribution, XRFdc_SetClkDistribution.
s32 XRFdc_GetDeviceNameByDeviceId(char *DevNamePtr, u16 DevId)
Traverse "/sys/bus/platform/device" directory, to find RFDC device entry, corresponding to provided device id.
If device entry corresponding to said device id is found, store it in output buffer DevNamePtr. DevNamePtr is base address of char array, where device name will be stored DevId contains the ID of the device to look up the RFDC device name entry in "/sys/bus/platform/device" XRFDC_SUCCESS if successful.XRFDC_FAILURE if device entry not found for given device id. None.
Referenced by XRFdc_LookupConfig, XRFdc_RegisterMetal.