xrfdc_sinit.c
XRFdc_Config* XRFdc_ConfigTablePtr
int metal_linux_get_device_property(struct metal_device *device, const char *property_name, void *output, int len)
static s32 XRFdc_Strrncmp(const char *Str1Ptr, const char *Str2Ptr, size_t Count)
Compare two strings in the reversed order.This function compares only the last "Count" number of characters of Str1Ptr and Str2Ptr.
Str1Ptr is base address of first string Str2Ptr is base address of second string Count is number of last characters to be compared between Str1Ptr and Str2Ptr 0 if last "Count" number of bytes matches between Str1Ptr and Str2Ptr, else difference in unmatched character. None.
s32 XRFdc_GetDeviceNameByDeviceId(char *DevNamePtr, u16 DevId)
Traverse "/sys/bus/platform/device" directory, to find RFDC device entry, corresponding to provided device id.
If device entry corresponding to said device id is found, store it in output buffer DevNamePtr. DevNamePtr is base address of char array, where device name will be stored DevId contains the ID of the device to look up the RFDC device name entry in "/sys/bus/platform/device" XRFDC_SUCCESS if successful.XRFDC_FAILURE if device entry not found for given device id. None.
Referenced by XRFdc_LookupConfig, XRFdc_RegisterMetal.
XRFdc_Config* XRFdc_LookupConfig(u16 DeviceId)
Looks up the device configuration based on the unique device ID.
A table contains the configuration info for each device in the system. DeviceId contains the ID of the device to look up the configuration for. A pointer to the configuration found or NULL if the specified device ID was not found. See xrfdc.h for the definition of XRFdc_Config.None.
References XRFdc_Config::Name, XRFdc_GetDeviceNameByDeviceId.
Referenced by RFdcMTS_Example.
u32 XRFdc_RegisterMetal(XRFdc *InstancePtr, u16 DeviceId, struct metal_device **DevicePtr)
Register/open the deviceand map RFDC to the IO region.
InstancePtr is a pointer to the XRfdc instance. DeviceId contains the ID of the device to register/map DevicePtr is a pointer to the metal device. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
References XRFdc_GetDeviceNameByDeviceId.
Referenced by RFdcMTS_Example.