xrfdc_mb.c
static void XRFdc_SetSignalFlow(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Mode, u32 DigitalDataPathId, u32 MixerInOutDataType, int ConnectIData, int ConnectQData)
Sets up signal flow configuration.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Mode is connection mode SB/MB_2X/MB_4X. DigitalDataPathId for the requested I or Q data. MixerInOutDataType is mixer data type, valid values are XRFDC_MB_DATATYPE_* ConnectIData is analog blocks that are connected to DigitalDataPath I. ConnectQData is analog blocks that are connected to DigitalDataPath Q. None.static API used internally.
static void XRFdc_MB_R2C_C2R(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u8 NoOfDataPaths, u32 MixerInOutDataType, u32 Mode, u32 DataPathIndex[], u32 BlockIndex[])
Static API to setup Multiband configuration for C2C MixerInOutDataType.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. MixerInOutDataType is mixer data type, valid values are XRFDC_MB_DATATYPE_* Mode is connection mode SB/MB_2X/MB_4X. DataPathIndex is the array that represents the blocks enabled in DigitalData Path. BlockIndex is the array that represents the blocks enabled in Analog Path(Data Converters). None Static API for ADC/DAC blocks
static void XRFdc_MB_C2C(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u8 NoOfDataPaths, u32 MixerInOutDataType, u32 Mode, u32 DataPathIndex[], u32 BlockIndex[])
Static API to setup Multiband configuration for C2C MixerInOutDataType.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. MixerInOutDataType is mixer data type, valid values are XRFDC_MB_DATATYPE_* Mode is connection mode SB/MB_2X/MB_4X. DataPathIndex is the array that represents the blocks enabled in DigitalData Path. BlockIndex is the array that represents the blocks enabled in Analog Path(Data Converters). None Static API for ADC/DAC blocks
static void XRFdc_SB_R2C_C2R(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 MixerInOutDataType, u32 Mode, u32 DataPathIndex[], u32 BlockIndex[])
Static API to setup Singleband configuration for C2R and R2C MultiBandDataTypes.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. MixerInOutDataType is mixer data type, valid values are XRFDC_MB_DATATYPE_* Mode is connection mode SB/MB_2X/MB_4X. DataPathIndex is the array that represents the blocks enabled in DigitalData Path. BlockIndex is the array that represents the blocks enabled in Analog Path(Data Converters). None Static API for ADC/DAC blocks
static void XRFdc_SB_C2C(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 MixerInOutDataType, u32 Mode, u32 DataPathIndex[], u32 BlockIndex[])
Static API to setup Singleband configuration for C2C MixerInOutDataType.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. MixerInOutDataType is mixer data type, valid values are XRFDC_MB_DATATYPE_* Mode is connection mode SB/MB_2X/MB_4X. DataPathIndex is the array that represents the blocks enabled in DigitalData Path. BlockIndex is the array that represents the blocks enabled in Analog Path(Data Converters). None Static API for ADC/DAC blocks
static void XRFdc_AltQMCRouting(XRFdc *InstancePtr, u32 Tile_Id, u32 Enable)
Static API to route QMC settings if switching to and from complex mode on alternate bodnout devices.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Enable 0 for normal routing, 1 for IQ routing. None Static API for DAC Tiles
static u32 XRFdc_UpdateMBConfig(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u8 NoOfDataPaths, u32 *ModePtr, u32 DataPathIndex[], u32 MixerInOutDataType)
Static API to update mode and MultibandConfig.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. NoOfDataPaths is number of DataPaths enabled. ModePtr is a pointer to connection mode SB/MB_2X/MB_4X. DataPathIndex is the array that represents the blocks enabled in DigitalData Path. MixerInOutDataType is mixer data type, valid values are XRFDC_MB_DATATYPE_* None Static API for ADC/DAC blocks
u32 XRFdc_MultiBand(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u8 DigitalDataPathMask, u32 MixerInOutDataType, u32 DataConverterMask)
User-level API to setup multiband configuration.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. DigitalDataPathMask is the DataPath mask. First 4 bits represent 4 data paths, 1 means enabled and 0 means disabled. MixerInOutDataType is mixer data type, valid values are XRFDC_MB_DATATYPE_* DataConverterMask is block enabled mask (input/output driving blocks). 1 means enabled and 0 means disabled. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Common API for ADC/DAC blocks
References XRFdc_CheckBlockEnabled, XRFdc_CheckDigitalPathEnabled, XRFDC_DAC_DATAPATH_OFFSET, XRFDC_DATAPATH_MODE_MASK, XRFdc_IsHighSpeedADC, XRFdc_RDReg.
u32 XRFdc_GetConnectedIQData(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, int *ConnectedIData, int *ConnectedQData)
Get Data Converter connected for digital data paths I & Q.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is Digital Data Path number. ConnectedData is Digital Data Path number. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs.
References XRFDC_ADC_SWITCH_MATRX_OFFSET, XRFdc_CheckDigitalPathEnabled, XRFDC_DAC_MB_CFG_OFFSET, XRFDC_MB_CONFIG_OFFSET, XRFdc_RDReg, XRFdc_ReadReg, XRFDC_SEL_CB_TO_MIX1_MASK.
Referenced by XRFdc_GetConnectedIData, XRFdc_GetConnectedQData.
int XRFdc_GetConnectedIData(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id)
Get Data Converter connected for digital data path I.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is Digital Data Path number. Return Data converter Id.
References XRFdc_GetConnectedIQData.
Referenced by XRFdc_SetQMCSettings.
int XRFdc_GetConnectedQData(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id)
Get Data Converter connected for digital data path Q.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is Digital Data Path number. Return Data converter Id.
References XRFdc_GetConnectedIQData.
Referenced by XRFdc_SetQMCSettings.
void XRFdc_SetConnectedIQData(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, int ConnectedIData, int ConnectedQData)
Set Data Converter connected for digital data path I and Q.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is Digital Data Path number. ConnectedIData is Converter Id to which DigitalPathI connected. ConnectedQData is Converter Id to which DigitalPathQ connected. None.
u32 XRFdc_GetMultibandConfig(XRFdc *InstancePtr, u32 Type, u32 Tile_Id)
Get Multiband Config data.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Return Multiband Configuration.Return 0 if invalid.
References XRFDC_MB_CONFIG_OFFSET, XRFdc_ReadReg.