xrfdc_mixer.c
static void XRFdc_SetFineMixer(XRFdc *InstancePtr, u32 BaseAddr, XRFdc_Mixer_Settings *MixerSettingsPtr)
Static API used to set the Fine Mixer.
InstancePtr is a pointer to the XRfdc instance. BaseAddr is ADC or DAC base address. MixerSettingsPtr Pointer to the XRFdc_Mixer_Settings structure in which the Mixer/NCO settings are passed. None Static API
static void XRFdc_SetCoarseMixer(XRFdc *InstancePtr, u32 Type, u32 BaseAddr, u32 Tile_Id, u32 Block_Id, u32 CoarseMixFreq, XRFdc_Mixer_Settings *MixerSettingsPtr)
Static API used to set the Coarse Mixer.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC BaseAddr is ADC or DAC base address. Block_Id is ADC/DAC block number inside the tile. CoarseMixFreq is ADC or DAC Coarse mixer frequency. MixerSettingsPtr Pointer to the XRFdc_Mixer_Settings structure in which the Mixer/NCO settings are passed. None Static API
static u32 XRFdc_MixerRangeCheck(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, XRFdc_Mixer_Settings *MixerSettingsPtr)
Static API used to do the Mixer Settings range check.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC MixerSettingsPtr Pointer to the XRFdc_Mixer_Settings structure in which the Mixer/NCO settings are passed. XRFDC_SUCCESS if mixer settings are within the range.XRFDC_FAILURE if mixer settings are not in valid range None.
static void XRFdc_MixersOff(XRFdc *InstancePtr, u32 BaseAddr)
Static API used to turn off Fine & Coarse Mixers.
InstancePtr is a pointer to the XRfdc instance. BaseAddr is ADC or DAC base address. None Static API
u32 XRFdc_SetMixerSettings(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, XRFdc_Mixer_Settings *MixerSettingsPtr)
The API is used to update various mixer settings, fine, coarse, NCO etc.
Mixer/NCO settings passed are used to update the corresponding block level registers. Driver structure is updated with the new values. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. MixerSettingsPtr Pointer to the XRFdc_Mixer_Settings structure in which the Mixer/NCO settings are passed. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. FineMixerScale in Mixer_Settings structure can have 3 values. XRFDC_MIXER_SCALE_* represents the valid values. XRFDC_MIXER_SCALE_AUTO - If mixer mode is R2C, Mixer Scale is set to 1 and for other modes mixer scale is set to 0.7 XRFDC_MIXER_SCALE_1P0 - To set fine mixer scale to 1. XRFDC_MIXER_SCALE_0P7 - To set fine mixer scale to 0.7.
References XRFDC_ADC_DECI_CONFIG_OFFSET, XRFDC_ADC_NCO_FQWD_LOW_OFFSET, XRFDC_ADC_NCO_FQWD_MID_OFFSET, XRFDC_ADC_NCO_FQWD_UPP_OFFSET, XRFDC_ADC_NCO_PHASE_MOD_OFFSET, XRFDC_ADC_UPDATE_DYN_OFFSET, XRFdc_CheckDigitalPathEnabled, XRFdc_ClrSetReg, XRFDC_DAC_DATAPATH_OFFSET, XRFDC_DAC_INTERP_DATA_MASK, XRFDC_DAC_ITERP_DATA_OFFSET, XRFDC_DAC_UPDATE_DYN_OFFSET, XRFDC_DATAPATH_MODE_MASK, XRFDC_DEC_CFG_4GSPS_MASK, XRFDC_DEC_CFG_CHA_MASK, XRFDC_DEC_CFG_IQ_MASK, XRFDC_DEC_CFG_MASK, XRFDC_FINE_MIX_SCALE_MASK, XRFdc_GetCalibrationMode, XRFdc_GetNyquistZone, XRFdc_IsHighSpeedADC, XRFDC_MXR_MODE_OFFSET, XRFDC_NCO_FQWD_MID_MASK, XRFDC_NCO_FQWD_MID_SHIFT, XRFDC_NCO_FQWD_UPP_MASK, XRFDC_NCO_FQWD_UPP_SHIFT, XRFDC_NCO_PHASE_LOW_OFFSET, XRFDC_NCO_PHASE_MOD_EVEN, XRFDC_NCO_PHASE_MODE_ODD, XRFDC_NCO_PHASE_UPP_MASK, XRFDC_NCO_PHASE_UPP_OFFSET, XRFDC_NCO_PHASE_UPP_SHIFT, XRFDC_NCO_UPDT_MODE_MASK, XRFDC_NCO_UPDT_OFFSET, XRFdc_RDReg, XRFdc_ReadReg16, XRFdc_ResetInternalFIFOWidth, XRFDC_UPDT_EVNT_MASK, XRFDC_UPDT_EVNT_NCO_MASK, XRFdc_WriteReg16.
Referenced by XRFdc_SetCalibrationMode, XRFdc_SetDataPathMode.
u32 XRFdc_GetMixerSettings(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, XRFdc_Mixer_Settings *MixerSettingsPtr)
The API returns back Mixer/NCO settings to the caller.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. MixerSettingsPtr Pointer to the XRFdc_Mixer_Settings structure in which the Mixer/NCO settings are passed. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. FineMixerScale in Mixer_Settings structure can have 3 values. XRFDC_MIXER_SCALE_* represents the valid values. XRFDC_MIXER_SCALE_AUTO - If mixer mode is R2C, Mixer Scale is set to 1 and for other modes mixer scale is set to 0.7 XRFDC_MIXER_SCALE_1P0 - To set fine mixer scale to 1. XRFDC_MIXER_SCALE_0P7 - To set fine mixer scale to 0.7.
References XRFDC_ADC_MXR_CFG0_OFFSET, XRFDC_ADC_MXR_CFG1_OFFSET, XRFDC_ADC_NCO_FQWD_LOW_OFFSET, XRFDC_ADC_NCO_FQWD_MID_OFFSET, XRFDC_ADC_NCO_FQWD_UPP_OFFSET, XRFdc_CheckDigitalPathEnabled, XRFDC_DAC_DATAPATH_OFFSET, XRFDC_DATAPATH_MODE_MASK, XRFDC_EN_I_IQ_MASK, XRFDC_EN_Q_IQ_MASK, XRFDC_FINE_MIX_SCALE_MASK, XRFdc_GetCalibrationMode, XRFdc_GetNyquistZone, XRFdc_IsHighSpeedADC, XRFDC_MIX_CFG0_MASK, XRFDC_MIX_CFG1_MASK, XRFDC_MXR_MODE_OFFSET, XRFDC_NCO_FQWD_MASK, XRFDC_NCO_FQWD_MID_SHIFT, XRFDC_NCO_FQWD_UPP_SHIFT, XRFDC_NCO_PHASE_LOW_OFFSET, XRFDC_NCO_PHASE_MASK, XRFDC_NCO_PHASE_UPP_OFFSET, XRFDC_NCO_PHASE_UPP_SHIFT, XRFDC_NCO_UPDT_MODE_MASK, XRFDC_NCO_UPDT_OFFSET, XRFdc_RDReg, XRFdc_ReadReg16.
Referenced by XRFdc_SetCalibrationMode, XRFdc_SetDataPathMode.
u32 XRFdc_ResetNCOPhase(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id)
Resets the NCO phase of the current block phase accumulator.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
References XRFdc_CheckDigitalPathEnabled, XRFdc_ClrSetReg, XRFdc_IsHighSpeedADC, XRFDC_NCO_PHASE_RST_MASK, XRFDC_NCO_RST_OFFSET.
u32 XRFdc_GetDataType(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id)
Get Mixer Input Data Type for ADC/DAC block.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Return MixerInputDataType of ADC/DAC block.Return 0 if invalid