xrfdc_clock.c
XRFDC_MAX_DLY_INIT
XRFDC_MIN_DLY_INIT
XRFDC_DLY_UNIT
XRFDC_MAX_DISTRS
u32 PllTuningMatrix[8][4][2][8][4][2]
static u32 XRFdc_CheckClkDistValid(XRFdc *InstancePtr, XRFdc_Distribution_Settings *DistributionSettingsPtr)
This function is used to check the distribution chosen is valid.
InstancePtr is a pointer to the XRfdc instance. DistributionSettingsPtr pointer to the distribution settings struct XRFDC_SUCCESS if valid.XRFDC_FAILURE if not valid.
static u32 XRFdc_SetPLLConfig(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, double RefClkFreq, double SamplingRate)
This function used for configuring the internal PLL registers based on reference clock and sampling rate.
InstancePtr is a pointer to the XRfdc instance. Type indicates ADC/DAC. Tile_Id indicates Tile number (0-3). RefClkFreq Reference Clock Frequency MHz(50MHz - 1.2GHz) SamplingRate Sampling Rate in MHz(0.5- 4 GHz) XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
static void XRFdc_DistTile2TypeTile(XRFdc *InstancePtr, u32 DistTile, u32 *Type, u32 *Tile_Id)
static u8 XRFdc_TypeTile2DistTile(XRFdc *InstancePtr, u32 Type, u32 Tile_Id)
static u32 XRFdc_SetTileClkSettings(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, XRFdc_Tile_Clock_Settings *SettingsPtr)
This function is used to set the clock settings.
InstancePtr is a pointer to the XRfdc instance. Type indicates ADC/DAC. Tile_Id indicates Tile number (0-3). SettingsPtr pointer to set the clock settings XRFDC_SUCCESS if successful.XRFDC_FAILURE if no valid distribution found.
static u32 XRFdc_StartUpDist(XRFdc *InstancePtr, XRFdc_Distribution_Settings *DistributionSettingsPtr)
This function is used to start the distribution tiles.
InstancePtr is a pointer to the XRfdc instance. DistributionSettingsPtr pointer to the distribution settings struct XRFDC_SUCCESS if valid.XRFDC_FAILURE if not valid.
u32 XRFdc_SetClkDistribution(XRFdc *InstancePtr, XRFdc_Distribution_Settings *DistributionSettingsPtr)
This function is used to set the clock distribution.
InstancePtr is a pointer to the XRfdc instance. DistributionSettingsPtr pointer to the distribution settings struct XRFDC_SUCCESS if successful.XRFDC_FAILURE if could not set distribution.
References XRFDC_CLOCK_DETECT_DST_SHIFT, XRFDC_CLOCK_DETECT_MASK, XRFDC_CLOCK_DETECT_OFFSET, XRFDC_CLOCK_DETECT_SRC_MASK, XRFdc_ClrSetReg, XRFdc_GetTileLayout, XRFDC_HSCOM_CLK_DSTR_MASK, XRFDC_HSCOM_CLK_DSTR_OFFSET, XRFDC_PWR_STATE_MASK, XRFdc_RDReg, XRFDC_RESTART_MASK, XRFDC_RESTART_OFFSET, XRFDC_RESTART_STATE_OFFSET, XRFDC_RSR_START_SHIFT, XRFdc_WaitForState, XRFdc_WriteReg.
u32 XRFdc_GetClkDistribution(XRFdc *InstancePtr, XRFdc_Distribution_System_Settings *DistributionSystemPtr)
This function is used to get the clock distribution.
InstancePtr is a pointer to the XRfdc instance. DistributionSettingsPtr pointer to get the distribution settings XRFDC_SUCCESS if successful.XRFDC_FAILURE if no valid distribution found.
References XRFdc_CheckTileEnabled, XRFDC_CLOCK_DETECT_OFFSET, XRFDC_CLOCK_DETECT_SRC_MASK, XRFdc_GetPLLConfig, XRFdc_GetTileLayout, XRFDC_HSCOM_CLK_DSTR_OFFSET, XRFdc_RDReg, XRFdc_ReadReg16.
u32 XRFdc_GetClockSource(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 *ClockSourcePtr)
This function gets Clock source.
InstancePtr is a pointer to the XRfdc instance. Type indicates ADC/DAC. Tile_Id indicates Tile number (0-3). ClockSourcePtr Pointer to return the clock source XRFDC_SUCCESS if successful.XRFDC_FAILURE if tile not enabled. None.
References XRFdc_CheckTileEnabled, XRFDC_CLK_NETWORK_CTRL1, XRFDC_CLK_NETWORK_CTRL1_USE_PLL_MASK, XRFDC_PLL_DIVIDER0, XRFdc_RDReg, XRFdc_ReadReg16.
Referenced by XRFdc_DynamicPLLConfig, XRFdc_GetPLLConfig, XRFdc_GetPLLLockStatus.
u32 XRFdc_GetPLLLockStatus(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 *LockStatusPtr)
This function gets PLL lock status.
InstancePtr is a pointer to the XRfdc instance. Type indicates ADC/DAC. Tile_Id indicates Tile number (0-3). LockStatusPtr Pointer to return the PLL lock status XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
References XRFdc_GetClockSource, XRFDC_PLL_LOCKED_MASK, XRFdc_RDReg, XRFDC_STATUS_OFFSET.
u32 XRFdc_GetPLLConfig(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, XRFdc_PLL_Settings *PLLSettings)
This API is used to get the PLL Configurations.
InstancePtr is a pointer to the XRfdc instance. Type represents ADC or DAC. Tile_Id Valid values are 0-3. PLLSettings pointer to the XRFdc_PLL_Settings structure to get the PLL configurations None.
References XRFdc_CheckTileEnabled, XRFdc_GetClockSource, XRFDC_PLL_DIVIDER0, XRFDC_PLL_FPDIV, XRFDC_PLL_FREQ, XRFDC_PLL_FS, XRFDC_PLL_REFDIV, XRFdc_RDReg, XRFdc_ReadReg, XRFdc_ReadReg16, XRFDC_REFCLK_DIV_2_MASK, XRFDC_REFCLK_DIV_3_MASK, XRFDC_REFCLK_DIV_4_MASK.
Referenced by XRFdc_GetClkDistribution.
u32 XRFdc_DynamicPLLConfig(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u8 Source, double RefClkFreq, double SamplingRate)
This function used for dynamically switch between internal PLL and external clcok source and configuring the internal PLL.
InstancePtr is a pointer to the XRfdc instance. Type indicates ADC/DAC Tile_Id indicates Tile number (0-3) Source Clock source internal PLL or external clock source RefClkFreq Reference Clock Frequency in MHz(102.40625MHz - 1.2GHz) SamplingRate Sampling Rate in MHz(0.1- 6.554GHz for DAC and 0.5/1.0 - 2.058/4.116GHz for ADC based on the device package). XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. This API enables automatic selection of the VCO which will work in IP version 2.0.1 and above. Using older version of IP this API is not likely to work.
References XRFDC_ADC_DAC_MC_CFG0_OFFSET, XRFDC_CAL_DIV_BYP_MASK, XRFDC_CAL_DIV_BYP_OFFSET, XRFDC_CAL_DLY_OFFSET, XRFDC_CAL_TMR_MULT_OFFSET, XRFdc_CheckTileEnabled, XRFDC_CLK_NETWORK_CTRL1, XRFDC_CLK_NETWORK_CTRL1_REGS_MASK, XRFDC_CLK_NETWORK_CTRL1_USE_PLL_MASK, XRFdc_ClrSetReg, XRFdc_CustomStartUp, XRFdc_GetClockSource, XRFdc_GetMaxSampleRate, XRFdc_GetMinSampleRate, XRFdc_GetTileLayout, XRFDC_HSCOM_CLK_DSTR_OFFSET, XRFDC_HSCOM_PWR_STATE_OFFSET, XRFdc_IsHighSpeedADC, XRFDC_PLL_DIVIDER0, XRFDC_PLL_FREQ, XRFDC_PLL_FS, XRFDC_PWR_UP_STAT_MASK, XRFDC_PWR_UP_STAT_SHIFT, XRFdc_RDReg, XRFdc_ReadReg, XRFdc_ReadReg16, XRFDC_RX_PR_MC_CFG0_IDIV_MASK, XRFDC_RX_PR_MC_CFG0_PSNK_MASK, XRFDC_STATUS_OFFSET, XRFdc_WriteReg, XRFdc_WriteReg16.