xrfdc.c
static u32 XRFdc_RestartIPSM(XRFdc *InstancePtr, u32 Type, int Tile_Id, u32 Start, u32 End)
Restarts a requested the tile and ensures that starts from a defined start state and reaches the requested or defined end state.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3, and -1. Start is start state of State Machine End is end state of State Machine. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
static void StubHandler(void *CallBackRefPtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 StatusEvent)
This is a stub for the status callback.
The stub is here in case the upper layers forget to set the handler. CallBackRefPtr is a pointer to the upper layer callback reference. Type indicates ADC/DAC. Tile_Id indicates Tile number (0-3). Block_Id indicates Block number (0-3). StatusEvent indicates one or more interrupt occurred. None.None.
static void XRFdc_ADCInitialize(XRFdc *InstancePtr)
Initialize ADC Tiles.
InstancePtr is a pointer to the XRfdc instance. None. Static API used to initialize ADC Tiles
static void XRFdc_DACInitialize(XRFdc *InstancePtr)
Initialize DAC Tiles.
InstancePtr is a pointer to the XRfdc instance. None. Static API used to initialize DAC Tiles
static void XRFdc_DACMBConfigInit(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id)
Initialize Multiband Configuration for DAC Tiles.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3, and -1. Block_Id is DAC block number inside the tile. Valid values are 0-3. None. Static API used to initialize DAC MB Config
static void XRFdc_ADCMBConfigInit(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id)
Initialize Multiband Configuration for ADC Tiles.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3, and -1. Block_Id is ADC block number inside the tile. Valid values are 0-3. None. Static API used to initialize ADC MB Config
static void XRFdc_UpdatePLLStruct(XRFdc *InstancePtr, u32 Type, u32 Tile_Id)
This API updates PLL Structure.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC. Tile_Id Valid values are 0-3, and -1. None. Static API used to initialize PLL Settings for ADC and DAC
static u32 XRFdc_GetADCBlockStatus(XRFdc *InstancePtr, u32 BaseAddr, u32 Tile_Id, u32 Block_Id, XRFdc_BlockStatus *BlockStatusPtr)
The API returns the requested block status for ADC block.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. XRFdc_BlockStatus. BlockStatus is Pointer to the XRFdc_BlockStatus structure through which the ADC/DAC block status is returned. XRFDC_SUCCESS if successful.XRFDC_FAILURE if block not enabled. Static API for ADC blocks.
static u32 XRFdc_GetDACBlockStatus(XRFdc *InstancePtr, u32 BaseAddr, u32 Tile_Id, u32 Block_Id, XRFdc_BlockStatus *BlockStatusPtr)
The API returns the requested block status for DAC block.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. XRFdc_BlockStatus. BlockStatus is Pointer to the XRFdc_BlockStatus structure through which the DAC block status is returned. XRFDC_SUCCESS if successful.XRFDC_FAILURE if block not enabled. Static API for DAC blocks.
static void XRFdc_DumpHSCOMRegs(XRFdc *InstancePtr, u32 Type, int Tile_Id)
Static API to dump HSCOM registers.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3, and -1. None None.
static void XRFdc_DumpDACRegs(XRFdc *InstancePtr, int Tile_Id)
Static API to dump DAC registers.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3, and -1. None None.
static void XRFdc_DumpADCRegs(XRFdc *InstancePtr, int Tile_Id)
Static API to dump ADC registers.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3, and -1. None None.
static u32 XRFdc_WaitForRestartClr(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 BaseAddr, u32 End)
This Static API will be used to wait for restart bit clears and also check for PLL Lock if clock source is internal PLL.
InstancePtr is a pointer to the XRfdc instance. End is end state of State Machine. XRFDC_SUCCESS if successful.XRFDC_FAILURE if timeout occurs. None.
u32 XRFdc_CfgInitialize(XRFdc *InstancePtr, XRFdc_Config *ConfigPtr)
Initializes a specific XRFdc instance such that the driver is ready to use.
InstancePtr is a pointer to the XRfdc instance. ConfigPtr is a reference to a structure containing information about xrfdc. This function initializes an InstancePtr object for a specific device specified by the contents of Config. XRFDC_SUCCESS if successful. The user needs to first call the XRFdc_LookupConfig() API which returns the Configuration structure pointer which is passed as a parameter to the XRFdc_CfgInitialize() API.
Referenced by RFdcMTS_Example.
u32 XRFdc_StartUp(XRFdc *InstancePtr, u32 Type, int Tile_Id)
The API Restarts the requested tile.
It can restart a single tile and alternatively can restart all the tiles. Existing register settings are not lost or altered in the process. It just starts the requested tile(s). InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3, and -1. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
u32 XRFdc_Shutdown(XRFdc *InstancePtr, u32 Type, int Tile_Id)
The API stops the tile as requested.
It can also stop all the tiles if asked for. It does not clear any of the existing register settings. It just stops the requested tile(s). InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3, and -1. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
u32 XRFdc_Reset(XRFdc *InstancePtr, u32 Type, int Tile_Id)
The API resets the requested tile.
It can reset all the tiles as well. In the process, all existing register settings are cleared and are replaced with the settings initially configured (through the GUI). InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3, and -1. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
u32 XRFdc_CustomStartUp(XRFdc *InstancePtr, u32 Type, int Tile_Id, u32 StartState, u32 EndState)
The API starts the requested tile from a provided state and runs to the given end state.
It can restart a single tile and alternatively can restart all the tiles. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3, and -1. StartState Valid values are XRFDC_START_STATE_*. Tile_Id Valid values are XRFDC_END_STATE_*. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. If starting from/ending at XRFDC_START_STATE_OFF/XRFDC_END_STATE_OFF, register settings will be wiped.
References XRFDC_CAL_DIV_BYP_MASK, XRFDC_CAL_DIV_BYP_OFFSET, XRFDC_CAL_DLY_OFFSET, XRFDC_CAL_TMR_MULT_OFFSET, XRFdc_ClrSetReg, XRFdc_IsHighSpeedADC, XRFdc_ReadReg, XRFdc_WriteReg.
Referenced by XRFdc_DynamicPLLConfig.
u32 XRFdc_WaitForState(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 State)
This function is used to wait for a tile to reach a given state.
InstancePtr is a pointer to the XRfdc instance. Type represents ADC or DAC. Tile_Id Valid values are 0-3. State represents the state which the tile must reach. XRFDC_SUCCESS if valid.XRFDC_FAILURE if not valid.
References XRFdc_CheckTileEnabled, XRFDC_CURRENT_STATE_MASK, XRFDC_CURRENT_STATE_OFFSET, XRFdc_RDReg.
Referenced by XRFdc_SetClkDistribution.
u32 XRFdc_GetIPStatus(XRFdc *InstancePtr, XRFdc_IPStatus *IPStatusPtr)
The API returns the IP status.
InstancePtr is a pointer to the XRfdc instance. IPStatusPtr Pointer to the XRFdc_IPStatus structure through which the status is returned. XRFDC_SUCCESS if successful. None.
References XRFDC_CURRENT_STATE_OFFSET, XRFdc_IsADCBlockEnabled, XRFdc_IsDACBlockEnabled, XRFDC_PLL_LOCKED_MASK, XRFDC_PLL_LOCKED_SHIFT, XRFDC_PWR_UP_STAT_MASK, XRFDC_PWR_UP_STAT_SHIFT, XRFdc_ReadReg16, XRFDC_STATUS_OFFSET.
Referenced by XRFdc_MultiConverter_Sync.
u32 XRFdc_GetBlockStatus(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, XRFdc_BlockStatus *BlockStatusPtr)
The API returns the requested block status.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. XRFdc_BlockStatus. BlockStatusPtr is Pointer to the XRFdc_BlockStatus structure through which the ADC/DAC block status is returned. XRFDC_SUCCESS if successful.XRFDC_FAILURE if block not enabled. Common API for ADC/DAC blocks.
References XRFdc_CheckBlockEnabled, XRFDC_CLK_EN_OFFSET, XRFDC_DAT_CLK_EN_MASK, XRFdc_IsHighSpeedADC, XRFdc_RDReg.
u32 XRFdc_SetDataPathMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 Mode)
This API is to set the DAC Datapath mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Mode valid values are 0-3. XRFDC_SUCCESS if successful.XRFDC_FAILURE if tile not enabled / out of range. Only for DAC blocks
References XRFdc_CheckBlockEnabled, XRFdc_CheckDigitalPathEnabled, XRFdc_ClrSetReg, XRFDC_DAC_DATAPATH_OFFSET, XRFDC_DAC_FAB_RATE_RD_MASK, XRFDC_DAC_FABRIC_RATE_OFFSET, XRFDC_DAC_INTERP_CTRL_OFFSET, XRFDC_DAC_INTERP_DATA_MASK, XRFDC_DAC_ITERP_DATA_OFFSET, XRFDC_DATAPATH_IMR_MASK, XRFDC_DATAPATH_IMR_SHIFT, XRFDC_DATAPATH_MODE_MASK, XRFDC_FAB_CLK_DIV_CAL_MASK, XRFDC_FAB_RATE_RD_SHIFT, XRFdc_GetMixerSettings, XRFDC_HSCOM_CLK_DIV_OFFSET, XRFDC_INTERP_MODE_I_MASK_EXT, XRFDC_INTERP_MODE_MASK_EXT, XRFdc_RDReg, XRFdc_SetMixerSettings.
u32 XRFdc_GetDataPathMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *ModePtr)
This API is to get the DAC Datapath mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. ModePtr pointer used to return value. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for DAC blocks
References XRFdc_CheckDigitalPathEnabled, XRFDC_DAC_DATAPATH_OFFSET, XRFDC_DATAPATH_IMR_MASK, XRFDC_DATAPATH_IMR_SHIFT, XRFDC_DATAPATH_MODE_MASK, XRFdc_RDReg.
u32 XRFdc_SetIMRPassMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 Mode)
This API is to set the DAC Image Reject Filter Pass mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Mode valid values are 0 (for low pass) 1 (for high pass). XRFDC_SUCCESS if successful.XRFDC_FAILURE if tile not enabled / bad parameter passed Only for DAC blocks
References XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFDC_DAC_DATAPATH_OFFSET, XRFDC_DATAPATH_IMR_MASK.
u32 XRFdc_GetIMRPassMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *ModePtr)
This API is to get the DAC Image Reject Filter Pass mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. ModePtr pointer used to return value. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for DAC blocks
References XRFdc_CheckBlockEnabled, XRFDC_DAC_DATAPATH_OFFSET, XRFDC_DATAPATH_IMR_MASK, XRFdc_RDReg.
void XRFdc_DumpRegs(XRFdc *InstancePtr, u32 Type, int Tile_Id)
This Prints the offset of the register along with the content.
This API is meant to be used for debug purposes. It prints to the console the contents of registers for the passed Tile_Id. If -1 is passed, it prints the contents of the registers for all the tiles for the respective ADC or DAC InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3, and -1. None None.
u32 XRFdc_SetPwrMode(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, XRFdc_Pwr_Mode_Settings *SettingsPtr)
Set The Power up/down mode of a given converter.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id Valid values are 0-3. SettingsPtr is a pointer with the power mode settings. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Common API for ADC/DAC blocks
References XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFdc_IsHighSpeedADC, XRFDC_TDD_CTRL_MODE0_MASK, XRFDC_TDD_CTRL_RTP_MASK, XRFDC_TDD_CTRL_RTP_SHIFT, XRFDC_TDD_CTRL_SLICE_OFFSET.
u32 XRFdc_GetPwrMode(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, XRFdc_Pwr_Mode_Settings *SettingsPtr)
Get The Power up/down mode of a given converter.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id Valid values are 0-3. SettingsPtr is a pointer to be filled with the power mode settings. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Common API for ADC/DAC blocks
References XRFdc_CheckBlockEnabled, XRFdc_IsHighSpeedADC, XRFdc_RDReg, XRFDC_TDD_CTRL_MODE0_MASK, XRFDC_TDD_CTRL_RTP_MASK, XRFDC_TDD_CTRL_RTP_SHIFT, XRFDC_TDD_CTRL_SLICE_OFFSET.
void XRFdc_ClrSetReg(XRFdc *InstancePtr, u32 BaseAddr, u32 RegAddr, u16 Mask, u16 Data)
Execute Read modify Write.
InstancePtr is a pointer to the XRfdc instance. BaseAddr is address of a block. RegAddr is register offset value. Mask contains bit mask value. Data contains value to be written to register. None
References XRFdc_ReadReg16, XRFdc_WriteReg16.
Referenced by XRFdc_CustomStartUp, XRFdc_DisableCoefficientsOverride, XRFdc_DynamicPLLConfig, XRFdc_IntrEnable, XRFdc_ResetNCOPhase, XRFdc_SetCalCoefficients, XRFdc_SetCalFreeze, XRFdc_SetCalibrationMode, XRFdc_SetClkDistribution, XRFdc_SetCoarseDelaySettings, XRFdc_SetDACCompMode, XRFdc_SetDACDataScaler, XRFdc_SetDACVOP, XRFdc_SetDataPathMode, XRFdc_SetDecoderMode, XRFdc_SetDither, XRFdc_SetDSA, XRFdc_SetFabClkOutDiv, XRFdc_SetFabWrVldWords, XRFdc_SetIMRPassMode, XRFdc_SetInterpolationFactor, XRFdc_SetInvSincFIR, XRFdc_SetMixerSettings, XRFdc_SetPwrMode, XRFdc_SetQMCSettings, XRFdc_SetSignalDetector, XRFdc_SetThresholdSettings, XRFdc_ThresholdStickyClear.
void XRFdc_ClrReg(XRFdc *InstancePtr, u32 BaseAddr, u32 RegAddr, u16 Mask)
Execute Read and clear.
InstancePtr is a pointer to the XRfdc instance. BaseAddr is address of a block. RegAddr is register offset value. Mask contains bit mask value. None
References XRFdc_ReadReg16, XRFdc_WriteReg16.
Referenced by XRFdc_IntrDisable.
u16 XRFdc_RDReg(XRFdc *InstancePtr, u32 BaseAddr, u32 RegAddr, u16 Mask)
Execute Read and mask with the value.
InstancePtr is a pointer to the XRfdc instance. BaseAddr is address of a block. RegAddr is register offset value. Mask contains bit mask value. None
References XRFdc_ReadReg16.
Referenced by XRFdc_DynamicPLLConfig, XRFdc_GetBlockStatus, XRFdc_GetCalCoefficients, XRFdc_GetCalFreeze, XRFdc_GetCalibrationMode, XRFdc_GetClkDistribution, XRFdc_GetClockSource, XRFdc_GetCoarseDelaySettings, XRFdc_GetConnectedIQData, XRFdc_GetCoupling, XRFdc_GetDACCompMode, XRFdc_GetDACDataScaler, XRFdc_GetDataPathMode, XRFdc_GetDecoderMode, XRFdc_GetDither, XRFdc_GetDSA, XRFdc_GetEnabledInterrupts, XRFdc_GetFabClkOutDiv, XRFdc_GetFIFOStatusInt, XRFdc_GetIMRPassMode, XRFdc_GetInterpolationFactor, XRFdc_GetInvSincFIR, XRFdc_GetLinkCoupling, XRFdc_GetMixerSettings, XRFdc_GetNyquistZone, XRFdc_GetOutputCurr, XRFdc_GetPLLConfig, XRFdc_GetPLLLockStatus, XRFdc_GetPwrMode, XRFdc_GetQMCSettings, XRFdc_GetSignalDetector, XRFdc_GetThresholdSettings, XRFdc_MultiBand, XRFdc_SetClkDistribution, XRFdc_SetDACVOP, XRFdc_SetDataPathMode, XRFdc_SetInterpolationFactor, XRFdc_SetMixerSettings, XRFdc_SetQMCSettings, XRFdc_UpdateEvent, XRFdc_WaitForState.
u32 XRFdc_IsHighSpeedADC(XRFdc *InstancePtr, u32 Tile)
Get ADC type is High Speed or Medium Speed.
InstancePtr is a pointer to the XRfdc instance. Return 1 if ADC type is a dual typeReturn 0 if quad or invalid tile.
Referenced by XRFdc_CustomStartUp, XRFdc_DisableCoefficientsOverride, XRFdc_DynamicPLLConfig, XRFdc_Get_BlockBaseAddr, XRFdc_GetBlockStatus, XRFdc_GetCalCoefficients, XRFdc_GetCalFreeze, XRFdc_GetCalibrationMode, XRFdc_GetCoarseDelaySettings, XRFdc_GetCoupling, XRFdc_GetDither, XRFdc_GetDSA, XRFdc_GetEnabledInterrupts, XRFdc_GetIntrStatus, XRFdc_GetLinkCoupling, XRFdc_GetMaxSampleRate, XRFdc_GetMinSampleRate, XRFdc_GetMixerSettings, XRFdc_GetNyquistZone, XRFdc_GetPwrMode, XRFdc_GetQMCSettings, XRFdc_GetSignalDetector, XRFdc_GetThresholdSettings, XRFdc_IntrClr, XRFdc_IntrDisable, XRFdc_IntrEnable, XRFdc_IntrHandler, XRFdc_IsADCBlockEnabled, XRFdc_IsADCDigitalPathEnabled, XRFdc_MultiBand, XRFdc_ResetNCOPhase, XRFdc_SetCalCoefficients, XRFdc_SetCalFreeze, XRFdc_SetCalibrationMode, XRFdc_SetCoarseDelaySettings, XRFdc_SetDither, XRFdc_SetDSA, XRFdc_SetMixerSettings, XRFdc_SetNyquistZone, XRFdc_SetPwrMode, XRFdc_SetQMCSettings, XRFdc_SetSignalDetector, XRFdc_SetThresholdClrMode, XRFdc_SetThresholdSettings, XRFdc_ThresholdStickyClear, XRFdc_UpdateEvent.
u32 XRFdc_Get_IPBaseAddr(XRFdc *InstancePtr)
Get IP BaseAddress.
InstancePtr is a pointer to the XRfdc instance. Return IP BaseAddress.
u32 XRFdc_Get_TileBaseAddr(XRFdc *InstancePtr, u32 Type, u32 Tile_Id)
Get Tile BaseAddress.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Return Tile BaseAddress if valid tile.Return 0U if invalid/unavailable tile.
References XRFdc_CheckTileEnabled.
u32 XRFdc_Get_BlockBaseAddr(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id)
Get Block BaseAddress.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3 in DAC/ADC-2GSPS and 0-1 in ADC-4GSPS. Return Block BaseAddress.Return 0U if invalid/unavailable block.
References XRFdc_CheckBlockEnabled, XRFdc_IsHighSpeedADC.
u32 XRFdc_GetNoOfDACBlock(XRFdc *InstancePtr, u32 Tile_Id)
Get Number of DAC Blocks enabled.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Return number of DAC blocks enabled.
u32 XRFdc_GetNoOfADCBlocks(XRFdc *InstancePtr, u32 Tile_Id)
Get Number of ADC Blocks enabled.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Return number of ADC blocks enabled.
u32 XRFdc_GetDataWidth(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id)
Get Data Width for ADC/DAC block.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Return DataWidth of ADC/DAC block.
u32 XRFdc_CheckTileEnabled(XRFdc *InstancePtr, u32 Type, u32 Tile_Id)
Checks whether ADC/DAC tile is enabled or not.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC. Tile_Id Valid values are 0-3. XRFDC_SUCCESS if tile enabled.XRFDC_FAILURE if tile not enabled.
References XRFDC_DAC_TILES_ENABLED_SHIFT, XRFdc_ReadReg, XRFDC_TILES_ENABLED_OFFSET.
Referenced by XRFdc_DynamicPLLConfig, XRFdc_Get_TileBaseAddr, XRFdc_GetClkDistribution, XRFdc_GetClockSource, XRFdc_GetFabClkOutDiv, XRFdc_GetFIFOStatusInt, XRFdc_GetMTSEnable, XRFdc_GetPLLConfig, XRFdc_SetFabClkOutDiv, XRFdc_WaitForState.
u32 XRFdc_GetMaxSampleRate(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, double *MaxSampleRatePtr)
Gets ADC/DAC tile maximum sampling rate.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC. Tile_Id Valid values are 0-3. MaxSampleRatePtr pointer for maximum sample rate. XRFDC_SUCCESS if found sampling rate.XRFDC_FAILURE if could not find sampling rate.
References XRFdc_IsHighSpeedADC.
Referenced by XRFdc_DynamicPLLConfig.
u32 XRFdc_GetMinSampleRate(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, double *MinSampleRatePtr)
Gets ADC/DAC tile minimum sampling rate.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC. Tile_Id Valid values are 0-3. MinSampleRatePtr pointer for minimum sample rate. XRFDC_SUCCESS if found sampling rate.XRFDC_FAILURE if could not find sampling rate.
References XRFdc_IsHighSpeedADC.
Referenced by XRFdc_DynamicPLLConfig.
u8 XRFdc_GetTileLayout(XRFdc *InstancePtr)
Gets whether the device is a DFE variant or not.
InstancePtr is a pointer to the XRfdc instance. XRFDC_3ADC_2DAC_TILES if DFE variant.XRFDC_4ADC_4DAC_TILES if regular Gen 1/2/3.
Referenced by XRFdc_DynamicPLLConfig, XRFdc_GetClkDistribution, XRFdc_SetClkDistribution.
double XRFdc_GetDriverVersion(void)
This API is used to get the driver version.
None Driver version number None.