xrfdc_intr.c
u32 XRFdc_IntrEnable(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 IntrMask)
This function sets the interrupt mask.
InstancePtr is a pointer to the XRFdc instance Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3, and -1. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. IntrMask contains the interrupts to be enabled. '1' enables an interrupt, and '0' disables. XRFDC_SUCCESS if successful.XRFDC_FAILURE if block not available. None.
References XRFDC_ADC_DAT_IMR_MASK, XRFDC_ADC_DEC_IMR_OFFSET, XRFDC_ADC_FABRIC_IMR_OBS_OFFSET, XRFDC_ADC_FABRIC_IMR_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_CheckDigitalPathEnabled, XRFdc_ClrSetReg, XRFDC_COMMON_INTR_ENABLE, XRFDC_DAC_DAT_IMR_MASK, XRFDC_DAC_FABRIC_IMR_OFFSET, XRFDC_DAC_FIFO_IMR_MASK, XRFDC_DATPATH_IMR_OFFSET, XRFDC_INTR_ENABLE, XRFdc_IsHighSpeedADC, XRFdc_ReadReg, XRFdc_ReadReg16, XRFdc_WriteReg, XRFdc_WriteReg16.
u32 XRFdc_IntrDisable(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 IntrMask)
This function clears the interrupt mask.
InstancePtr is a pointer to the XRFdc instance Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3, and -1. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. IntrMask contains the interrupts to be disabled. '1' disables an interrupt, and '0' remains no change. XRFDC_SUCCESS if successful.XRFDC_FAILURE if block not available. None.
References XRFDC_ADC_DEC_IMR_OFFSET, XRFDC_ADC_FABRIC_IMR_OBS_OFFSET, XRFDC_ADC_FABRIC_IMR_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_CheckDigitalPathEnabled, XRFdc_ClrReg, XRFDC_DAC_FABRIC_IMR_OFFSET, XRFDC_DATPATH_IMR_OFFSET, XRFDC_INTR_ENABLE, XRFdc_IsHighSpeedADC, XRFdc_ReadReg, XRFdc_WriteReg.
Referenced by RFdcHandler.
u32 XRFdc_GetEnabledInterrupts(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 *IntrMask)
This function gets a mask of enabled interrupts.
InstancePtr is a pointer to the XRFdc instance Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3, and -1. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. IntrMask is a pointer to the mask of enabled interrupts. '1' denotes an enabled interrupt, and '0' denotes a disabled interrupt. XRFDC_SUCCESS if successful.XRFDC_FAILURE if block not available. None.
References XRFDC_ADC_DAT_IMR_MASK, XRFDC_ADC_DEC_IMR_OFFSET, XRFDC_ADC_FABRIC_IMR_OBS_OFFSET, XRFDC_ADC_FABRIC_IMR_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_CheckDigitalPathEnabled, XRFDC_COMMON_INTR_ENABLE, XRFDC_DAC_DAT_IMR_MASK, XRFDC_DAC_FABRIC_IMR_OFFSET, XRFDC_DAC_FIFO_IMR_SUPP_MASK, XRFDC_DATPATH_IMR_OFFSET, XRFDC_INTR_ENABLE, XRFdc_IsHighSpeedADC, XRFdc_RDReg, XRFdc_ReadReg, XRFdc_ReadReg16.
u32 XRFdc_GetIntrStatus(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 *IntrStsPtr)
This function returns the interrupt status read from Interrupt Status Register(ISR).
InstancePtr is a pointer to the XRFdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3, and -1. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. IntrStsPtr is pointer to a32-bit value representing the contents of the Interrupt Status Registers (FIFO interface, Decoder interface, Data Path Interface). XRFDC_SUCCESS if successful.XRFDC_FAILURE if block not available. None.
References XRFDC_ADC_DAT_PATH_ISR_MASK, XRFDC_ADC_DEC_ISR_OFFSET, XRFDC_ADC_FABRIC_ISR_OBS_OFFSET, XRFDC_ADC_FABRIC_ISR_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_CheckDigitalPathEnabled, XRFDC_DAC_DAT_PATH_ISR_MASK, XRFDC_DAC_FABRIC_ISR_OFFSET, XRFDC_DAC_FIFO_IMR_SUPP_MASK, XRFDC_DATPATH_ISR_OFFSET, XRFDC_DEC_ISR_SUBADC_MASK, XRFDC_INTR_CMODE_OVR_MASK, XRFDC_INTR_CMODE_UNDR_MASK, XRFDC_INTR_COMMON_MASK, XRFDC_INTR_DAT_OVR_MASK, XRFDC_INTR_FIFO_OVR_MASK, XRFDC_INTR_OVR_RANGE_MASK, XRFDC_INTR_OVR_VOLTAGE_MASK, XRFDC_INTR_STS, XRFdc_IsHighSpeedADC, XRFdc_ReadReg, XRFdc_ReadReg16.
Referenced by XRFdc_IntrHandler.
u32 XRFdc_IntrClr(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 IntrMask)
This function clear the interrupts.
InstancePtr is a pointer to the XRFdc instance Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3, and -1. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. IntrMask contains the interrupts to be cleared. XRFDC_SUCCESS if successful.XRFDC_FAILURE if block not available. None.
References XRFDC_ADC_DEC_ISR_OFFSET, XRFDC_ADC_FABRIC_ISR_OBS_OFFSET, XRFDC_ADC_FABRIC_ISR_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_CheckDigitalPathEnabled, XRFDC_DAC_FABRIC_ISR_OFFSET, XRFDC_DATPATH_ISR_OFFSET, XRFdc_IsHighSpeedADC, XRFdc_WriteReg, XRFdc_WriteReg16.
Referenced by XRFdc_IntrHandler.
u32 XRFdc_IntrHandler(u32 Vector, void *XRFdcPtr)
This function is the interrupt handler for the driver.
It must be connected to an interrupt system by the application such that it can be called when an interrupt occurs. Vector is interrupt vector number. Libmetal status handler expects two parameters in the handler prototype, hence kept this parameter. This is not used inside the interrupt handler API. XRFdcPtr contains a pointer to the driver instance None.Vector param is not useful inside the interrupt handler, hence typecast with void to remove compilation warning.
References XRFDC_COMMON_INTR_STS, XRFDC_EN_INTR_ADC_TILE0_MASK, XRFDC_EN_INTR_ADC_TILE1_MASK, XRFDC_EN_INTR_ADC_TILE2_MASK, XRFDC_EN_INTR_ADC_TILE3_MASK, XRFDC_EN_INTR_DAC_TILE0_MASK, XRFDC_EN_INTR_DAC_TILE1_MASK, XRFDC_EN_INTR_DAC_TILE2_MASK, XRFDC_EN_INTR_DAC_TILE3_MASK, XRFDC_EN_INTR_SLICE0_MASK, XRFDC_EN_INTR_SLICE1_MASK, XRFDC_EN_INTR_SLICE2_MASK, XRFDC_EN_INTR_SLICE3_MASK, XRFdc_GetIntrStatus, XRFDC_INTR_COMMON_MASK, XRFDC_INTR_STS, XRFdc_IntrClr, XRFdc_IsHighSpeedADC, XRFdc_ReadReg16.
void XRFdc_SetStatusHandler(XRFdc *InstancePtr, void *CallBackRef, XRFdc_StatusHandler FunctionPtr)
This function sets the status callback function, the status handler, which the driver calls when it encounters conditions that should be reported to the higher layer software.
The handler executes in an interrupt context, so the amount of processing should be minimized InstancePtr is a pointer to the XRFdc instance. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. FunctionPtr is the pointer to the callback function. None.The handler is called within interrupt context, so it should finish its work quickly.