xrfdc_ap.c
XRFDC_DAC_LINK_COUPLING_AC
XRFDC_VOP_ES1_AC_MIN_UA
XRFDC_VOP_ES1_AC_MAX_UA
XRFDC_VOP_AC_MIN_UA
XRFDC_VOP_AC_MAX_UA
XRFDC_VOP_DC_MIN_UA
XRFDC_VOP_DC_MAX_UA
XRFDC_MIN_I_UA_INT
XRFDC_STEP_I_UA
XRFDC_BLDR_GAIN
XRFDC_CSCAS_BLDR
XRFDC_OPCAS_BIAS
u32 XRFdc_SetQMCSettings(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, XRFdc_QMC_Settings *QMCSettingsPtr)
This API is used to update various QMC settings, eg gain, phase, offset etc.
QMC settings passed are used to update the corresponding block level registers. Driver structure is updated with the new values. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. QMCSettingsPtr is Pointer to the XRFdc_QMC_Settings structure in which the QMC settings are passed. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
References XRFDC_ADC_SWITCH_MATRX_OFFSET, XRFDC_ADC_UPDATE_DYN_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFDC_DAC_MB_CFG_OFFSET, XRFDC_DAC_UPDATE_DYN_OFFSET, XRFdc_GetConnectedIData, XRFdc_GetConnectedQData, XRFdc_IsHighSpeedADC, XRFDC_QMC_CFG_EN_GAIN_MASK, XRFDC_QMC_CFG_EN_PHASE_MASK, XRFDC_QMC_CFG_OFFSET, XRFDC_QMC_CFG_PHASE_SHIFT, XRFDC_QMC_GAIN_CRCTN_MASK, XRFDC_QMC_GAIN_OFFSET, XRFDC_QMC_OFF_OFFSET, XRFDC_QMC_OFFST_CRCTN_MASK, XRFDC_QMC_PHASE_CRCTN_MASK, XRFDC_QMC_PHASE_OFFSET, XRFDC_QMC_UPDT_MODE_MASK, XRFDC_QMC_UPDT_OFFSET, XRFdc_RDReg, XRFDC_SEL_CB_TO_QMC_MASK, XRFDC_UPDT_EVNT_MASK, XRFDC_UPDT_EVNT_QMC_MASK.
u32 XRFdc_GetQMCSettings(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, XRFdc_QMC_Settings *QMCSettingsPtr)
QMC settings are returned back to the caller through this API.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. QMCSettingsPtr Pointer to the XRFdc_QMC_Settings structure in which the QMC settings are passed. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
References XRFdc_CheckBlockEnabled, XRFDC_DAC_MB_CFG_OFFSET, XRFdc_IsHighSpeedADC, XRFDC_QMC_CFG_EN_GAIN_MASK, XRFDC_QMC_CFG_EN_PHASE_MASK, XRFDC_QMC_CFG_OFFSET, XRFDC_QMC_CFG_PHASE_SHIFT, XRFDC_QMC_GAIN_CRCTN_MASK, XRFDC_QMC_GAIN_OFFSET, XRFDC_QMC_OFF_OFFSET, XRFDC_QMC_OFFST_CRCTN_MASK, XRFDC_QMC_OFFST_CRCTN_SIGN_MASK, XRFDC_QMC_PHASE_CRCTN_MASK, XRFDC_QMC_PHASE_CRCTN_SIGN_MASK, XRFDC_QMC_PHASE_OFFSET, XRFDC_QMC_UPDT_MODE_MASK, XRFDC_QMC_UPDT_OFFSET, XRFdc_RDReg.
u32 XRFdc_SetCoarseDelaySettings(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, XRFdc_CoarseDelay_Settings *CoarseDelaySettingsPtr)
Coarse delay settings passed are used to update the corresponding block level registers.
Driver structure is updated with the new values. InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. CoarseDelaySettingsPtr is Pointer to the XRFdc_CoarseDelay_Settings structure in which the CoarseDelay settings are passed. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
References XRFDC_ADC_CRSE_DLY_CFG_OFFSET, XRFDC_ADC_CRSE_DLY_UPDT_OFFSET, XRFDC_ADC_UPDATE_DYN_OFFSET, XRFDC_ADC_UPDT_CRSE_DLY_MASK, XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFDC_CRSE_DLY_CFG_MASK, XRFDC_CRSE_DLY_CFG_MASK_EXT, XRFDC_DAC_CRSE_DLY_CFG_OFFSET, XRFDC_DAC_CRSE_DLY_UPDT_OFFSET, XRFDC_DAC_UPDATE_DYN_OFFSET, XRFDC_DAC_UPDT_CRSE_DLY_MASK, XRFdc_IsHighSpeedADC, XRFDC_QMC_UPDT_MODE_MASK, XRFDC_UPDT_EVNT_MASK.
u32 XRFdc_GetCoarseDelaySettings(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, XRFdc_CoarseDelay_Settings *CoarseDelaySettingsPtr)
Coarse delay settings are returned back to the caller.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. CoarseDelaySettingsPtr Pointer to the XRFdc_CoarseDelay_Settings structure in which the Coarse Delay settings are passed. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
References XRFDC_ADC_CRSE_DLY_CFG_OFFSET, XRFDC_ADC_CRSE_DLY_UPDT_OFFSET, XRFdc_CheckBlockEnabled, XRFDC_DAC_CRSE_DLY_CFG_OFFSET, XRFDC_DAC_CRSE_DLY_UPDT_OFFSET, XRFdc_IsHighSpeedADC, XRFDC_QMC_UPDT_MODE_MASK, XRFdc_RDReg, XRFdc_ReadReg16.
u32 XRFdc_ThresholdStickyClear(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 ThresholdToUpdate)
This API is to clear the Sticky bit in threshold config registers.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. ThresholdToUpdate Select which Threshold (Threshold0 or Threshold1 or both) to update. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only ADC blocks
References XRFDC_ADC_TRSHD0_CFG_OFFSET, XRFDC_ADC_TRSHD1_CFG_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFdc_IsHighSpeedADC, XRFDC_TRSHD0_STIKY_CLR_MASK, XRFDC_TRSHD1_STIKY_CLR_MASK.
u32 XRFdc_SetThresholdClrMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 ThresholdToUpdate, u32 ClrMode)
This API sets the threshold clear mode.
The clear mode can be through explicit DRP access (manual) or auto clear (QMC gain update event). InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADCC block number inside the tile. Valid values are 0-3. ThresholdToUpdate Select which Threshold (Threshold0 or Threshold1 or both) to update. ClrMode can be DRP access (manual) or auto clear (QMC gain update event). XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only ADC blocks
References XRFDC_ADC_TRSHD0_CFG_OFFSET, XRFDC_ADC_TRSHD1_CFG_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_IsHighSpeedADC, XRFdc_ReadReg16, XRFDC_TRSHD0_CLR_MOD_MASK, XRFDC_TRSHD1_CLR_MOD_MASK, XRFdc_WriteReg16.
u32 XRFdc_SetThresholdSettings(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, XRFdc_Threshold_Settings *ThresholdSettingsPtr)
Threshold settings are updated into the relevant registers.
Driver structure is updated with the new values. There can be two threshold settings: threshold0 and threshold1. Both of them are independent of each other. The function returns the requested threshold (which can be threshold0, threshold1, or both. InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. ThresholdSettingsPtr Pointer through which the register settings for thresholds are passed to the API. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only ADC blocks
References XRFDC_ADC_TRSHD0_AVG_LO_OFFSET, XRFDC_ADC_TRSHD0_AVG_UP_OFFSET, XRFDC_ADC_TRSHD0_CFG_OFFSET, XRFDC_ADC_TRSHD0_OVER_OFFSET, XRFDC_ADC_TRSHD0_UNDER_OFFSET, XRFDC_ADC_TRSHD1_AVG_LO_OFFSET, XRFDC_ADC_TRSHD1_AVG_UP_OFFSET, XRFDC_ADC_TRSHD1_CFG_OFFSET, XRFDC_ADC_TRSHD1_OVER_OFFSET, XRFDC_ADC_TRSHD1_UNDER_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFdc_IsHighSpeedADC, XRFDC_TRSHD0_AVG_UPP_SHIFT, XRFDC_TRSHD0_EN_MOD_MASK, XRFDC_TRSHD0_OVER_MASK, XRFDC_TRSHD0_UNDER_MASK, XRFDC_TRSHD1_AVG_UPP_SHIFT, XRFDC_TRSHD1_EN_MOD_MASK, XRFDC_TRSHD1_OVER_MASK, XRFDC_TRSHD1_UNDER_MASK, XRFdc_WriteReg16.
u32 XRFdc_GetThresholdSettings(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, XRFdc_Threshold_Settings *ThresholdSettingsPtr)
Threshold settings are read from the corresponding registers and are passed back to the caller.
There can be two threshold settings: threshold0 and threshold1. Both of them are independent of each other. The function returns the requested threshold (which can be threshold0, threshold1, or both. InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. ThresholdSettingsPtr Pointer through which the register settings for thresholds are passed back.. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_ADC_TRSHD0_AVG_LO_OFFSET, XRFDC_ADC_TRSHD0_AVG_UP_OFFSET, XRFDC_ADC_TRSHD0_CFG_OFFSET, XRFDC_ADC_TRSHD0_OVER_OFFSET, XRFDC_ADC_TRSHD0_UNDER_OFFSET, XRFDC_ADC_TRSHD1_AVG_LO_OFFSET, XRFDC_ADC_TRSHD1_AVG_UP_OFFSET, XRFDC_ADC_TRSHD1_CFG_OFFSET, XRFDC_ADC_TRSHD1_OVER_OFFSET, XRFDC_ADC_TRSHD1_UNDER_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_IsHighSpeedADC, XRFdc_RDReg, XRFdc_ReadReg16, XRFDC_TRSHD0_AVG_UPP_SHIFT, XRFDC_TRSHD0_EN_MOD_MASK, XRFDC_TRSHD0_OVER_MASK, XRFDC_TRSHD0_UNDER_MASK, XRFDC_TRSHD1_AVG_UPP_SHIFT, XRFDC_TRSHD1_EN_MOD_MASK, XRFDC_TRSHD1_OVER_MASK, XRFDC_TRSHD1_UNDER_MASK.
u32 XRFdc_SetDecoderMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 DecoderMode)
Decoder mode is updated into the relevant registers.
Driver structure is updated with the new values. InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is DAC block number inside the tile. Valid values are 0-3. DecoderMode Valid values are 1 (Maximum SNR, for non- randomized decoder), 2 (Maximum Linearity, for randomized decoder) XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only DAC blocks
References XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFDC_DAC_DECODER_CLK_OFFSET, XRFDC_DAC_DECODER_CTRL_OFFSET, XRFDC_DEC_CTRL_MODE_MASK.
u32 XRFdc_GetDecoderMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *DecoderModePtr)
Decoder mode is read and returned back.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is DAC block number inside the tile. Valid values are 0-3. DecoderModePtr Valid values are 1 (Maximum SNR, for non-randomized decoder), 2 (Maximum Linearity, for randomized decoder) XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for DAC blocks
References XRFdc_CheckBlockEnabled, XRFDC_DAC_DECODER_CTRL_OFFSET, XRFDC_DEC_CTRL_MODE_MASK, XRFdc_RDReg.
u32 XRFdc_GetOutputCurr(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *OutputCurrPtr)
Get Output Current for DAC block.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. OutputCurrPtr pointer to return the output current. Return Output Current for DAC block
References XRFDC_ADC_DAC_MC_CFG2_OFFSET, XRFdc_CheckBlockEnabled, XRFDC_DAC_MC_CFG3_OFFSET, XRFdc_RDReg.
u32 XRFdc_SetNyquistZone(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 NyquistZone)
Set the Nyquist zone.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. NyquistZone valid values are 1 (Odd),2 (Even). XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Common API for ADC/DAC blocks
References XRFDC_ADC_TI_TISK_CRL0_OFFSET, XRFdc_CheckBlockEnabled, XRFDC_DAC_MC_CFG0_OFFSET, XRFdc_GetCalibrationMode, XRFdc_IsHighSpeedADC, XRFDC_MC_CFG0_MIX_MODE_MASK, XRFdc_ReadReg16, XRFDC_TI_TISK_ZONE_MASK, XRFdc_WriteReg16.
Referenced by XRFdc_SetCalibrationMode.
u32 XRFdc_GetNyquistZone(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 *NyquistZonePtr)
Get the Nyquist zone.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. NyquistZonePtr Pointer to return the Nyquist zone. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Common API for ADC/DAC blocks
References XRFDC_ADC_TI_TISK_CRL0_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_CheckDigitalPathEnabled, XRFDC_DAC_MC_CFG0_OFFSET, XRFdc_GetCalibrationMode, XRFdc_IsHighSpeedADC, XRFDC_MC_CFG0_MIX_MODE_MASK, XRFDC_MC_CFG0_MIX_MODE_SHIFT, XRFdc_RDReg, XRFDC_TI_TISK_ZONE_MASK, XRFDC_TISK_ZONE_SHIFT.
Referenced by XRFdc_GetMixerSettings, XRFdc_SetCalibrationMode, XRFdc_SetInvSincFIR, XRFdc_SetMixerSettings.
u32 XRFdc_SetCalibrationMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u8 CalibrationMode)
This API is to set the Calibration mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. CalibrationMode valid values are 0(Gen 3 only), 1 and 2. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_ADC_TI_DCB_CRL0_OFFSET, XRFDC_ADC_TI_TISK_CRL0_OFFSET, XRFDC_ADC_TI_TISK_CRL5_OFFSET, XRFDC_CAL_MODES_MASK, XRFDC_CAL_TSCB_TUNE_MASK, XRFdc_CheckBlockEnabled, XRFdc_CheckDigitalPathEnabled, XRFdc_ClrSetReg, XRFdc_GetMixerSettings, XRFdc_GetNyquistZone, XRFdc_IsHighSpeedADC, XRFdc_ReadReg16, XRFdc_SetMixerSettings, XRFdc_SetNyquistZone, XRFDC_TI_DCB_MODE_MASK, XRFdc_WriteReg16.
u32 XRFdc_GetCalibrationMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u8 *CalibrationModePtr)
This API is to get the Calibration mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. CalibrationModePtr pointer to get the calibration mode. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_ADC_TI_DCB_CRL0_OFFSET, XRFDC_ADC_TI_TISK_CRL5_OFFSET, XRFDC_CAL_MODES_MASK, XRFdc_CheckBlockEnabled, XRFdc_CheckDigitalPathEnabled, XRFdc_IsHighSpeedADC, XRFdc_RDReg, XRFDC_TI_DCB_MODE_MASK.
Referenced by XRFdc_GetMixerSettings, XRFdc_GetNyquistZone, XRFdc_SetMixerSettings, XRFdc_SetNyquistZone.
u32 XRFdc_GetCoupling(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id, u32 *ModePtr)
This function is used to get the Coupling mode.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC. Tile_Id indicates Tile number. Block_Id indicates Block number. ModePtr pointer to get link coupling mode. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
References XRFDC_ADC_RXPR_MC_CFG0_OFFSET, XRFdc_CheckBlockEnabled, XRFDC_CPL_TYPE_OFFSET, XRFdc_IsHighSpeedADC, XRFdc_RDReg, XRFdc_ReadReg, XRFDC_RX_MC_CFG0_CM_MASK.
u32 XRFdc_GetLinkCoupling(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *ModePtr)
This function is used to get the Link Coupling mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id indicates Tile number (0-3). Block_Id indicates Block number(0-3 for 2G, 0-1 for 4G). ModePtr pointer to get link coupling mode. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_ADC_RXPR_MC_CFG0_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_IsHighSpeedADC, XRFdc_RDReg, XRFDC_RX_MC_CFG0_CM_MASK.
u32 XRFdc_SetDither(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 Mode)
This function is used to set the IM3 Dither mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id indicates Tile number (0-3). Block_Id indicates Block number(0-3 for LS, 0-1 for HS). Mode 0: Disable 1: Enable XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_ADC_DAC_MC_CFG0_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFdc_IsHighSpeedADC, XRFDC_RX_MC_CFG0_IM3_DITH_MASK, XRFDC_RX_MC_CFG0_IM3_DITH_SHIFT.
u32 XRFdc_GetDither(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *ModePtr)
This function is used to get the IM3 Dither mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id indicates Tile number (0-3). Block_Id indicates Block number(0-3 for LS, 0-1 for HS). ModePtr pointer to get link coupling mode. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_ADC_DAC_MC_CFG0_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_IsHighSpeedADC, XRFdc_RDReg, XRFDC_RX_MC_CFG0_IM3_DITH_MASK.
u32 XRFdc_SetSignalDetector(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, XRFdc_Signal_Detector_Settings *SettingsPtr)
This function is used to set the ADC Signal Detector Settings.
InstancePtr is a pointer to the XRfdc instance. Tile_Id indicates Tile number (0-3). Block_Id indicates Block number(0-3 for LS, 0-1 for HS). SettingsPtr pointer to the XRFdc_Signal_Detector_Settings structure to set the signal detector configurations XRFDC_SUCCESS if successful.XRFDC_FAILURE if tile not enabled, or invalid values. Only for ADC blocks
References XRFDC_ADC_SIG_DETECT_CTRL_OFFSET, XRFDC_ADC_SIG_DETECT_FLUSH_SHIFT, XRFDC_ADC_SIG_DETECT_HYST_SHIFT, XRFDC_ADC_SIG_DETECT_INTG_SHIFT, XRFDC_ADC_SIG_DETECT_MASK, XRFDC_ADC_SIG_DETECT_MODE_WRITE_SHIFT, XRFDC_ADC_SIG_DETECT_TCONST_SHIFT, XRFDC_ADC_SIG_DETECT_THRESHOLD0_CNT_OFF_OFFSET, XRFDC_ADC_SIG_DETECT_THRESHOLD0_CNT_ON_OFFSET, XRFDC_ADC_SIG_DETECT_THRESHOLD0_LEVEL_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFdc_IsHighSpeedADC, XRFdc_WriteReg16.
u32 XRFdc_GetSignalDetector(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, XRFdc_Signal_Detector_Settings *SettingsPtr)
This function is used to get the ADC Signal Detector Settings.
InstancePtr is a pointer to the XRfdc instance. Tile_Id indicates Tile number (0-3). Block_Id indicates Block number(0-3 for LS, 0-1 for HS). SettingsPtr pointer to the XRFdc_Signal_Detector_Settings structure to get the signal detector configurations XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_ADC_SIG_DETECT_CTRL_OFFSET, XRFDC_ADC_SIG_DETECT_FLUSH_MASK, XRFDC_ADC_SIG_DETECT_FLUSH_SHIFT, XRFDC_ADC_SIG_DETECT_HYST_MASK, XRFDC_ADC_SIG_DETECT_HYST_SHIFT, XRFDC_ADC_SIG_DETECT_INTG_MASK, XRFDC_ADC_SIG_DETECT_INTG_SHIFT, XRFDC_ADC_SIG_DETECT_MASK, XRFDC_ADC_SIG_DETECT_MODE_MASK, XRFDC_ADC_SIG_DETECT_MODE_READ_SHIFT, XRFDC_ADC_SIG_DETECT_TCONST_MASK, XRFDC_ADC_SIG_DETECT_TCONST_SHIFT, XRFDC_ADC_SIG_DETECT_THRESHOLD0_CNT_OFF_OFFSET, XRFDC_ADC_SIG_DETECT_THRESHOLD0_CNT_ON_OFFSET, XRFDC_ADC_SIG_DETECT_THRESHOLD0_LEVEL_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_IsHighSpeedADC, XRFdc_RDReg, XRFdc_ReadReg16.
u32 XRFdc_DisableCoefficientsOverride(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 CalibrationBlock)
This function is used to disable Calibration Coefficients override.
InstancePtr is a pointer to the XRfdc instance. Tile_Id indicates Tile number (0-3). Block_Id indicates Block number(0-3 for LS, 0-1 for HS). CalibrationBlock indicates the calibration block. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_ADC_TI_DCB_CRL1_OFFSET, XRFDC_ADC_TI_DCB_CRL3_OFFSET, XRFDC_CAL_GCB_ACEN_MASK, XRFDC_CAL_GCB_EN_MASK, XRFDC_CAL_GCB_ENFL_MASK, XRFDC_CAL_GCB_MASK, XRFDC_CAL_OCB_EN_MASK, XRFDC_CAL_TSCB_EN_MASK, XRFDC_CAL_TSCB_OFFSET_COEFF0, XRFDC_CAL_TSCB_OFFSET_COEFF0_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF1, XRFDC_CAL_TSCB_OFFSET_COEFF1_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF2, XRFDC_CAL_TSCB_OFFSET_COEFF2_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF3, XRFDC_CAL_TSCB_OFFSET_COEFF3_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF4, XRFDC_CAL_TSCB_OFFSET_COEFF4_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF5, XRFDC_CAL_TSCB_OFFSET_COEFF5_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF6, XRFDC_CAL_TSCB_OFFSET_COEFF6_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF7, XRFDC_CAL_TSCB_OFFSET_COEFF7_ALT, XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFdc_IsHighSpeedADC.
u32 XRFdc_SetCalCoefficients(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 CalibrationBlock, XRFdc_Calibration_Coefficients *CoeffPtr)
This function is used to set the ADC Calibration Coefficients.
InstancePtr is a pointer to the XRfdc instance. Tile_Id indicates Tile number (0-3). Block_Id indicates Block number(0-3 for LS, 0-1 for HS). CalibrationBlock indicates the block to be written to. CoeffPtr is pointer to the XRFdc_Calibration_Coefficients structure to set the calibration coefficients. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_ADC_TI_DCB_CRL1_OFFSET, XRFDC_ADC_TI_DCB_CRL3_OFFSET, XRFDC_CAL_GCB_ACEN_MASK, XRFDC_CAL_GCB_EN_MASK, XRFDC_CAL_GCB_EN_SHIFT, XRFDC_CAL_GCB_FLSH_MASK, XRFDC_CAL_GCB_FLSH_SHIFT, XRFDC_CAL_GCB_MASK, XRFDC_CAL_GCB_OFFSET_COEFF0, XRFDC_CAL_GCB_OFFSET_COEFF1, XRFDC_CAL_GCB_OFFSET_COEFF2, XRFDC_CAL_GCB_OFFSET_COEFF3, XRFDC_CAL_OCB1_OFFSET_COEFF0, XRFDC_CAL_OCB1_OFFSET_COEFF1, XRFDC_CAL_OCB1_OFFSET_COEFF2, XRFDC_CAL_OCB1_OFFSET_COEFF3, XRFDC_CAL_OCB2_OFFSET_COEFF0, XRFDC_CAL_OCB2_OFFSET_COEFF1, XRFDC_CAL_OCB2_OFFSET_COEFF2, XRFDC_CAL_OCB2_OFFSET_COEFF3, XRFDC_CAL_OCB_EN_MASK, XRFDC_CAL_OCB_MASK, XRFDC_CAL_SLICE_SHIFT, XRFDC_CAL_TSCB_EN_MASK, XRFDC_CAL_TSCB_EN_SHIFT, XRFDC_CAL_TSCB_MASK, XRFDC_CAL_TSCB_OFFSET_COEFF0, XRFDC_CAL_TSCB_OFFSET_COEFF0_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF1, XRFDC_CAL_TSCB_OFFSET_COEFF1_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF2, XRFDC_CAL_TSCB_OFFSET_COEFF2_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF3, XRFDC_CAL_TSCB_OFFSET_COEFF3_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF4, XRFDC_CAL_TSCB_OFFSET_COEFF4_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF5, XRFDC_CAL_TSCB_OFFSET_COEFF5_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF6, XRFDC_CAL_TSCB_OFFSET_COEFF6_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF7, XRFDC_CAL_TSCB_OFFSET_COEFF7_ALT, XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFdc_IsHighSpeedADC.
u32 XRFdc_GetCalCoefficients(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 CalibrationBlock, XRFdc_Calibration_Coefficients *CoeffPtr)
This function is used to get the ADC Calibration Coefficients.
InstancePtr is a pointer to the XRfdc instance. Tile_Id indicates Tile number (0-3). Block_Id indicates Block number(0-3 for LS, 0-1 for HS). CalibrationBlock indicates the block to be read from CoeffPtr is pointer to the XRFdc_Calibration_Coefficients structure to get the calibration coefficients. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_ADC_TI_DCB_CRL1_OFFSET, XRFDC_CAL_GCB_FAB_MASK, XRFDC_CAL_GCB_FLSH_MASK, XRFDC_CAL_GCB_MASK, XRFDC_CAL_GCB_OFFSET_COEFF0, XRFDC_CAL_GCB_OFFSET_COEFF0_ALT, XRFDC_CAL_GCB_OFFSET_COEFF1, XRFDC_CAL_GCB_OFFSET_COEFF1_ALT, XRFDC_CAL_GCB_OFFSET_COEFF2, XRFDC_CAL_GCB_OFFSET_COEFF2_ALT, XRFDC_CAL_GCB_OFFSET_COEFF3, XRFDC_CAL_GCB_OFFSET_COEFF3_ALT, XRFDC_CAL_OCB1_OFFSET_COEFF0, XRFDC_CAL_OCB1_OFFSET_COEFF1, XRFDC_CAL_OCB1_OFFSET_COEFF2, XRFDC_CAL_OCB1_OFFSET_COEFF3, XRFDC_CAL_OCB2_OFFSET_COEFF0, XRFDC_CAL_OCB2_OFFSET_COEFF1, XRFDC_CAL_OCB2_OFFSET_COEFF2, XRFDC_CAL_OCB2_OFFSET_COEFF3, XRFDC_CAL_OCB_MASK, XRFDC_CAL_SLICE_SHIFT, XRFDC_CAL_TSCB_MASK, XRFDC_CAL_TSCB_OFFSET_COEFF0, XRFDC_CAL_TSCB_OFFSET_COEFF0_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF1, XRFDC_CAL_TSCB_OFFSET_COEFF1_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF2, XRFDC_CAL_TSCB_OFFSET_COEFF2_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF3, XRFDC_CAL_TSCB_OFFSET_COEFF3_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF4, XRFDC_CAL_TSCB_OFFSET_COEFF4_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF5, XRFDC_CAL_TSCB_OFFSET_COEFF5_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF6, XRFDC_CAL_TSCB_OFFSET_COEFF6_ALT, XRFDC_CAL_TSCB_OFFSET_COEFF7, XRFDC_CAL_TSCB_OFFSET_COEFF7_ALT, XRFdc_CheckBlockEnabled, XRFdc_IsHighSpeedADC, XRFdc_RDReg.
u32 XRFdc_SetCalFreeze(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, XRFdc_Cal_Freeze_Settings *CalFreezePtr)
This function is used to set calibration freeze settings.
InstancePtr is a pointer to the XRfdc instance. Tile_Id indicates Tile number (0-3). Block_Id indicates Block number(0-3 for LS, 0-1 for HS). CalFreezePtr pointer to the settings to be applied. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_CAL_FREEZE_CAL_MASK, XRFDC_CAL_FREEZE_CAL_SHIFT, XRFDC_CAL_FREEZE_PIN_MASK, XRFDC_CAL_FREEZE_PIN_SHIFT, XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFdc_IsHighSpeedADC.
u32 XRFdc_GetCalFreeze(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, XRFdc_Cal_Freeze_Settings *CalFreezePtr)
This function is used to get calibration freeze settings and status.
InstancePtr is a pointer to the XRfdc instance. Tile_Id indicates Tile number (0-3). Block_Id indicates Block number(0-3 for LS, 0-1 for HS). CalFreezePtr pointer to be filled the settings/status. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Only for ADC blocks
References XRFDC_CAL_FREEZE_CAL_MASK, XRFDC_CAL_FREEZE_CAL_SHIFT, XRFDC_CAL_FREEZE_PIN_MASK, XRFDC_CAL_FREEZE_PIN_SHIFT, XRFDC_CAL_FREEZE_STS_MASK, XRFDC_CAL_FREEZE_STS_SHIFT, XRFdc_CheckBlockEnabled, XRFdc_IsHighSpeedADC, XRFdc_RDReg.
u32 XRFdc_SetDACVOP(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 uACurrent)
Set Output Current for DAC block.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. uACurrent is the current in uA. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Range 6425 - 32000 uA with 25 uA resolution.
References XRFDC_ADC_DAC_MC_CFG0_OFFSET, XRFDC_ADC_DAC_MC_CFG2_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFDC_CPL_TYPE_OFFSET, XRFDC_DAC_MC_CFG3_OFFSET, XRFDC_DAC_VOP_CTRL_OFFSET, XRFdc_RDReg, XRFdc_ReadReg.
u32 XRFdc_GetDACCompMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *EnabledPtr)
Gets VOP compatibility mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. mode is ADC/DAC block number inside the tile. Valid values are 0-3. EnabledPtr is pointer a that is filled with whether the mode is enabled (1) or disabled(0). XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
References XRFDC_ADC_DAC_MC_CFG2_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_RDReg.
u32 XRFdc_SetDACCompMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 Enable)
Sets VOP compatibility mode.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. mode is ADC/DAC block number inside the tile. Valid values are 0-3. Enable is whether to enable (1) or disable(0) the compatibility mode. XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. None.
References XRFDC_ADC_DAC_MC_CFG2_OFFSET, XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg.
u32 XRFdc_SetDSA(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, XRFdc_DSA_Settings *SettingsPtr)
Set DSA for ADC block.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Attenuation is the attenuation in dB XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Range 0 - 11 dB with 0.5 dB resolution ES1 Si. Range 0 - 27 dB with 1 dB resolution for Production Si.
References XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFDC_DSA_UPDT_OFFSET, XRFdc_IsHighSpeedADC.
u32 XRFdc_GetDSA(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, XRFdc_DSA_Settings *SettingsPtr)
Get DSA for ADC block.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. AttenuationPtr is the attenuation in dB XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. Range 0 - 11 dB with 0.5 dB resolution ES1 Si. Range 0 - 27 dB with 1 dB resolution for Production Si.
References XRFdc_CheckBlockEnabled, XRFdc_IsHighSpeedADC, XRFdc_RDReg, XRFdc_ReadReg16.
u32 XRFdc_IsDACBlockEnabled(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id)
Checks whether DAC block is available or not.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Return 1 if DAC block is available, otherwise 0.
References XRFDC_DAC_PATHS_ENABLED_OFFSET, XRFDC_PATH_ENABLED_TILE_SHIFT, XRFdc_ReadReg.
Referenced by XRFdc_CheckBlockEnabled, XRFdc_GetIPStatus.
u32 XRFdc_IsADCBlockEnabled(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id)
Checks whether ADC block is available or not.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3 in DAC/ADC-2GSPS and 0-1 in ADC-4GSPS. Return 1 if ADC block is available, otherwise 0.
References XRFDC_ADC_PATHS_ENABLED_OFFSET, XRFdc_IsHighSpeedADC, XRFDC_PATH_ENABLED_TILE_SHIFT, XRFdc_ReadReg.
Referenced by XRFdc_CheckBlockEnabled, XRFdc_GetIPStatus.
u32 XRFdc_CheckBlockEnabled(XRFdc *InstancePtr, u32 Type, u32 Tile_Id, u32 Block_Id)
Checks whether ADC/DAC block is enabled or not.
InstancePtr is a pointer to the XRfdc instance. Type is ADC or DAC. 0 for ADC and 1 for DAC. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. XRFDC_SUCCESS if block enabled.XRFDC_FAILURE if block not enabled.
References XRFdc_IsADCBlockEnabled, XRFdc_IsDACBlockEnabled.
Referenced by XRFdc_DisableCoefficientsOverride, XRFdc_Get_BlockBaseAddr, XRFdc_GetBlockStatus, XRFdc_GetCalCoefficients, XRFdc_GetCalFreeze, XRFdc_GetCalibrationMode, XRFdc_GetCoarseDelaySettings, XRFdc_GetCoupling, XRFdc_GetDACCompMode, XRFdc_GetDACDataScaler, XRFdc_GetDecoderMode, XRFdc_GetDither, XRFdc_GetDSA, XRFdc_GetEnabledInterrupts, XRFdc_GetIMRPassMode, XRFdc_GetIntrStatus, XRFdc_GetInvSincFIR, XRFdc_GetLinkCoupling, XRFdc_GetNyquistZone, XRFdc_GetOutputCurr, XRFdc_GetPwrMode, XRFdc_GetQMCSettings, XRFdc_GetSignalDetector, XRFdc_GetThresholdSettings, XRFdc_IntrClr, XRFdc_IntrDisable, XRFdc_IntrEnable, XRFdc_MultiBand, XRFdc_MultiConverter_Sync, XRFdc_SetCalCoefficients, XRFdc_SetCalFreeze, XRFdc_SetCalibrationMode, XRFdc_SetCoarseDelaySettings, XRFdc_SetDACCompMode, XRFdc_SetDACDataScaler, XRFdc_SetDACVOP, XRFdc_SetDataPathMode, XRFdc_SetDecoderMode, XRFdc_SetDither, XRFdc_SetDSA, XRFdc_SetIMRPassMode, XRFdc_SetInvSincFIR, XRFdc_SetNyquistZone, XRFdc_SetPwrMode, XRFdc_SetQMCSettings, XRFdc_SetSignalDetector, XRFdc_SetThresholdClrMode, XRFdc_SetThresholdSettings, XRFdc_ThresholdStickyClear, XRFdc_UpdateEvent.
u32 XRFdc_GetInverseSincFilter(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id)
Get Inversesync filter for DAC block.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Return Inversesync filter for DAC blockReturn 0 if invalid
u32 XRFdc_GetMixedMode(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id)
Get Mixed mode for DAC block.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Return mixed mode for DAC blockReturn 0 if invalid
u32 XRFdc_SetDACDataScaler(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 Enable)
Set data scaler for DAC block.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. Enable valid values are 1 (enable) and 0 (disable). XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. DAC blocks only.
References XRFdc_CheckBlockEnabled, XRFdc_ClrSetReg, XRFDC_DATA_SCALER_MASK, XRFDC_DATA_SCALER_OFFSET.
u32 XRFdc_GetDACDataScaler(XRFdc *InstancePtr, u32 Tile_Id, u32 Block_Id, u32 *EnablePtr)
Get data scaler for DAC block.
InstancePtr is a pointer to the XRfdc instance. Tile_Id Valid values are 0-3. Block_Id is ADC/DAC block number inside the tile. Valid values are 0-3. EnablePtr valid values are 1 (enable) and 0 (disable). XRFDC_SUCCESS if successful.XRFDC_FAILURE if error occurs. DAC blocks only.
References XRFdc_CheckBlockEnabled, XRFDC_DATA_SCALER_MASK, XRFDC_DATA_SCALER_OFFSET, XRFdc_RDReg.