ufspsxc
Error_Bits_15_12
Error_Bits_11_8
Qry_Error_Bits_7_0
Ocs
Uic_Cfg_Codes
Uic_Ctrl_Codes
General_Error_Codes
Hce
Card_Status
memory_types
Task_Tag
XUfsPsxc_Config XUfsPsxc_ConfigTable[][]
XUfsPsxc_Config XUfsPsxc_ConfigTable[XPAR_XUFSPSXC_NUM_INSTANCES][XPAR_XUFSPSXC_NUM_INSTANCES]
void XUfsPsxc_CfgInitialize(XUfsPsxc *InstancePtr, const XUfsPsxc_Config *ConfigPtr)
Initializes a specific XUfsPsxc instance such that the driver is ready to use.
InstancePtr is a pointer to the XUfsPsxc instance. ConfigPtr is a reference to a structure containing information about a specific UFSPSXC device. This function initializes an InstancePtr object for a specific device specified by the contents of Config. None
References XUfsPsxc_Config::BaseAddress, XUfsPsxc_Config::CfgClkFreqHz, XUfsPsxc_Config::InputClockHz, XUfsPsxc_Config::IsCacheCoherent, XUfsPsxc_Config::RefPadClk.
Referenced by UfsPsxcRawTest.
u32 XUfsPsxc_Initialize(XUfsPsxc *InstancePtr)
Initializes the Host Controller and UFS device.
InstancePtr is a pointer to the XUfsPsxc instance. XUFSPSXC_SUCCESS, XUFSPSXC_FAILURE, UIC Error Codes in xufspsxc.h file.
References XUfsPsxc_CardInitialize, XUfsPsxc_GetLUNInfo, XUfsPsxc_HostInitialize, XUfsPsxc_ReadDeviceInfo.
Referenced by UfsPsxcRawTest.
u32 XUfsPsxc_ConfigureSpeedGear(XUfsPsxc *InstancePtr, u32 SpeedGear)
This API Configures the Power Mode.
InstancePtr is a pointer to the XUfsPsxc instance. SpeedGear is the Power Mode value to be set. Refer XUFSPSXC_PWM_* XUFSPSXC_HS_* macros in xufspsxc.h file. XUFSPSXC_SUCCESS or ERROR_CODE.
References XUfsPsxc_Config::BaseAddress, XUfsPsxc_ConfigureTxRxAttributes.
u32 XUfsPsxc_CheckBootReq(XUfsPsxc *InstancePtr)
This API check boot requirements like BootEnable and bBootLunEn.
InstancePtr is a pointer to the XUfsPsxc instance. XUFSPSXC_SUCCESS or ERROR_CODE.
References XUfsPsxc_Set4KBlkSize.
u32 XUfsPsxc_SwitchBootLUN(XUfsPsxc *InstancePtr)
This API switch the Boot-LU(1->2 or 2->1) by modifying the Attributes and also set the block size to 4K if it is not 4K.
InstancePtr is a pointer to the XUfsPsxc instance. XUFSPSXC_SUCCESS or ERROR_CODE.
References XUfsPsxc_Xfer_CmdDesc::RespUpiu, XUfsPsxc_TransSpecFlds::Value, XUfsPsxc_FillAttrUpiu, XUfsPsxc_ProcessUpiu, XUfsPsxc_Set4KBlkSize.
Referenced by UfsPsxcRawTest.
u32 XUfsPsxc_ReadPolled(XUfsPsxc *InstancePtr, u32 Lun, u64 Address, u32 BlkCnt, const u8 *Buff)
This API perform the data read from the UFS device.
InstancePtr is a pointer to the XUfsPsxc instance. Lun is a Logical Unit Number. Address is the starting Logical Unit number. BlkCnt is the number of blocks to be read. Buff is a pointer to the destination data buffer. XUFSPSXC_SUCCESS, XUFSPSXC_FAILURE.
References XUfsPsxc_Config::IsCacheCoherent, XUfsPsxc_Xfer_CmdDesc::ReqUpiu, XUfsPsxc_Xfer_CmdDesc::RespUpiu, XUfsPsxc_FillReadCmdUpiu, XUfsPsxc_FillTestUnitRdyUpiu, XUfsPsxc_ProcessUpiu, XUFSPSXC_SCSI_GOOD.
Referenced by UfsPsxcRawTest.
u32 XUfsPsxc_WritePolled(XUfsPsxc *InstancePtr, u32 Lun, u64 Address, u32 BlkCnt, const u8 *Buff)
This API perform the data Write to the UFS device.
InstancePtr is a pointer to the XUfsPsxc instance. Lun is a Logical Unit Number. Address is the starting Logical Unit number. BlkCnt is the number of blocks to be read. Buff is a pointer to the destination data buffer. XUFSPSXC_SUCCESS, XUFSPSXC_FAILURE.
References XUfsPsxc_Config::IsCacheCoherent, XUfsPsxc_Xfer_CmdDesc::ReqUpiu, XUfsPsxc_Xfer_CmdDesc::RespUpiu, XUfsPsxc_FillTestUnitRdyUpiu, XUfsPsxc_FillWriteCmdUpiu, XUfsPsxc_ProcessUpiu, XUFSPSXC_SCSI_GOOD.
Referenced by UfsPsxcRawTest.
static void XUfsPsxc_FillUpiuHeader(XUfsPsxc_Xfer_CmdDesc *CmdDescPtr, u8 TransType, u32 Upiu_Dw0, u8 QueryTaskMangFn, u16 DataSegmentLen)
static void XUfsPsxc_FillCmdUpiu(const XUfsPsxc *InstancePtr, XUfsPsxc_Xfer_CmdDesc *CmdDescPtr, u32 BlkCnt, u8 Cmd, u64 Address)
static void XUfsPsxc_FillQryReqUpiu(XUfsPsxc_Xfer_CmdDesc *CmdDescPtr, u8 Cmd, u32 Tsf_Dw0, u32 Value, u16 Length)
static void XUfsPsxc_FillUTPTransReqDesc(XUfsPsxc *InstancePtr, const XUfsPsxc_Xfer_CmdDesc *CmdDescPtr, u32 DataDirection, u32 RespUpiuLen, u32 PrdtLen)
static void XUfsPsxc_FillUICCmd(XUfsPsxc_UicCmd *UicCmdPtr, u32 MIBAttr_GenSel, u32 MIBVal, u32 AttrSetType, u32 Cmd)
XUfsPsxc_Config * XUfsPsxc_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID.
A table contains the configuration info for each device in the system. BaseAddress contains the BaseAddress of the device to look up the configuration for. A pointer to the configuration found or NULL if the specified device ID was not found. See XUfsPsxc.h for the definition of XUfsPsxc_Config.
References XUfsPsxc_Config::Name.
Referenced by UfsPsxcRawTest.
u32 XUfsPsxc_SendUICCmd(const XUfsPsxc *InstancePtr, XUfsPsxc_UicCmd *UicCmdPtr)
Send UIC Command.
InstancePtr is a pointer to the XUfsPsxc instance. UicCmdPtr is a pointer to the XUfsPsxc_UicCmd instance. Refer UIC Error Codes in xufspsxc.h file.
References XUfsPsxc_Config::BaseAddress.
Referenced by XUfsPsxc_ConfigureTxRxAttributes, XUfsPsxc_EnableMPhy, XUfsPsxc_HostInitialize, XUfsPsxc_ReadPhyReg, XUfsPsxc_SetRmmiConfig, XUfsPsxc_WritePhyReg.
u32 XUfsPsxc_SetHce(const XUfsPsxc *InstancePtr, u32 Value)
Perform the Host Controller Enable/Disable.
InstancePtr is a pointer to the XUfsPsxc instance. Value is used to enable/disable Host Controller. XUFSPSXC_SUCCESS for Success XUFSPSXC_FAILURE for failure
References XUfsPsxc_Config::BaseAddress.
Referenced by XUfsPsxc_HostInitialize.
void XUfsPsxc_FillNopOutUpiu(XUfsPsxc *InstancePtr, XUfsPsxc_Xfer_CmdDesc *CmdDescPtr)
This API Fill the transfer request descriptor for NOP-OUT UPIU.
InstancePtr is a pointer to the XUfsPsxc instance. CmdDescPtr is a pointer to the XUfsPsxc_Xfer_CmdDesc instance. None.
References XUfsPsxc_Xfer_CmdDesc::RespUpiu.
Referenced by XUfsPsxc_CardInitialize.
void XUfsPsxc_FillTestUnitRdyUpiu(XUfsPsxc *InstancePtr, XUfsPsxc_Xfer_CmdDesc *CmdDescPtr)
This API Fill the transfer request descriptor for TEST UNIT READY Command.
InstancePtr is a pointer to the XUfsPsxc instance. CmdDescPtr is a pointer to the XUfsPsxc_Xfer_CmdDesc instance. None.
References XUfsPsxc_Xfer_CmdDesc::RespUpiu.
Referenced by XUfsPsxc_ReadPolled, XUfsPsxc_WritePolled.
void XUfsPsxc_FillReadCmdUpiu(XUfsPsxc *InstancePtr, XUfsPsxc_Xfer_CmdDesc *CmdDescPtr, u64 Address, u32 BlkCnt, const u8 *Buff)
This API Fill the transfer request descriptor for READ Command.
InstancePtr is a pointer to the XUfsPsxc instance. CmdDescPtr is a pointer to the XUfsPsxc_Xfer_CmdDesc instance. Address specifies the first logical block accessed by this command. BlkCnt is the number of blocks to be read. Buff is a pointer to the destination data buffer. None.
References XUfsPsxc_Xfer_CmdDesc::Prdt, XUfsPsxc_Xfer_CmdDesc::ReqUpiu, XUfsPsxc_Xfer_CmdDesc::RespUpiu.
Referenced by XUfsPsxc_ReadPolled.
u32 XUfsPsxc_ProcessUpiu(const XUfsPsxc *InstancePtr, const XUfsPsxc_Xfer_CmdDesc *CmdDescPtr)
This API send the UPIU to the UFS device.
InstancePtr is a pointer to the XUfsPsxc instance. CmdDescPtr is a pointer to the XUfsPsxc_Xfer_CmdDesc instance. Refer OCS in xufspsxc.h file, XUFSPSXC_FAILURE
References XUfsPsxc_Config::BaseAddress, XUfsPsxc_Xfer_ReqDesc::DW2_Ocs, XUfsPsxc_Config::IsCacheCoherent, XUfsPsxc_Xfer_CmdDesc::Prdt, XUfsPsxc_Xfer_CmdDesc::ReqUpiu, XUfsPsxc_Xfer_CmdDesc::RespUpiu, XUFSPSXC_SCSI_GOOD.
Referenced by XUfsPsxc_CardInitialize, XUfsPsxc_GetLUNInfo, XUfsPsxc_ReadDeviceInfo, XUfsPsxc_ReadPolled, XUfsPsxc_Set4KBlkSize, XUfsPsxc_SwitchBootLUN, XUfsPsxc_WritePolled.
void XUfsPsxc_FillFlagUpiu(XUfsPsxc *InstancePtr, XUfsPsxc_Xfer_CmdDesc *CmdDescPtr, u32 IsRead, u32 FlagIDn)
This API Fill the transfer request descriptor for READ/SET FLAG Command.
InstancePtr is a pointer to the XUfsPsxc instance. CmdDescPtr is a pointer to the XUfsPsxc_Xfer_CmdDesc instance. IsRead is a flag to indicate whether the operation is read or write. FlagIDn is a Flag Identification number. None.
References XUfsPsxc_Xfer_CmdDesc::RespUpiu, XUfsPsxc_TransSpecFlds::Value.
Referenced by XUfsPsxc_CardInitialize.
void XUfsPsxc_FillDescUpiu(XUfsPsxc *InstancePtr, XUfsPsxc_Xfer_CmdDesc *CmdDescPtr, u32 Tsf_DW0, u32 IsRead, u32 Length)
This API Fill the transfer request descriptor for read or write Descriptor Command.
InstancePtr is a pointer to the XUfsPsxc instance. CmdDescPtr is a pointer to the XUfsPsxc_Xfer_CmdDesc instance. Tsf_DW0 contains information about Description identification Number(3rd byte), Index(2nd byte) and Selector(1st byte). IsRead is a flag to indicate whether the operation is read or write descriptor. Length is the number of bytes to read the descriptor. None.
References XUfsPsxc_Xfer_CmdDesc::RespUpiu.
Referenced by XUfsPsxc_GetLUNInfo, XUfsPsxc_ReadDeviceInfo, XUfsPsxc_Set4KBlkSize.
void XUfsPsxc_FillAttrUpiu(XUfsPsxc *InstancePtr, XUfsPsxc_Xfer_CmdDesc *CmdDescPtr, u32 IsRead, u32 AttrIDn, u32 Value)
This API Fill the transfer request descriptor for read or write Attribute Command.
InstancePtr is a pointer to the XUfsPsxc instance. CmdDescPtr is a pointer to the XUfsPsxc_Xfer_CmdDesc instance. IsRead is a flag to indicate whether the operation is read or write descriptor. AttrIDn is a Attribute Identification number. Value is value to be written to the attributes. None.
References XUfsPsxc_Xfer_CmdDesc::RespUpiu.
Referenced by XUfsPsxc_GetLUNInfo, XUfsPsxc_SwitchBootLUN.
u32 XUfsPsxc_HostInitialize(XUfsPsxc *InstancePtr)
Initializes the Host Controller.
InstancePtr is a pointer to the XUfsPsxc instance. XUFSPSXC_SUCCESS, XUFSPSXC_FAILURE, UIC Error Codes in xufspsxc.h file.
References XUfsPsxc_Config::BaseAddress, XUfsPsxc_Config::CfgClkFreqHz, XUfsPsxc_Config::InputClockHz, XUfsPsxc_Config::RefPadClk, XUfsPsxc_PhyInit, XUfsPsxc_SendUICCmd, XUfsPsxc_SetHce.
Referenced by XUfsPsxc_Initialize.
u32 XUfsPsxc_CardInitialize(XUfsPsxc *InstancePtr, XUfsPsxc_Xfer_CmdDesc *CmdDescPtr)
This API Partially Initialize the UFS device.
InstancePtr is a pointer to the XUfsPsxc instance. CmdDescPtr is a pointer to the XUfsPsxc_Xfer_CmdDesc instance. XUFSPSXC_SUCCESS, XUFSPSXC_FAILURE.
References XUfsPsxc_Xfer_CmdDesc::RespUpiu, XUfsPsxc_TransSpecFlds::Value, XUfsPsxc_FillFlagUpiu, XUfsPsxc_FillNopOutUpiu, XUfsPsxc_ProcessUpiu.
Referenced by XUfsPsxc_Initialize.
u32 XUfsPsxc_GetLUNInfo(XUfsPsxc *InstancePtr, XUfsPsxc_Xfer_CmdDesc *CmdDescPtr)
This API update the Logical Unit information structure by reading the configuration descriptor.
InstancePtr is a pointer to the XUfsPsxc instance. CmdDescPtr is a pointer to the XUfsPsxc_Xfer_CmdDesc instance. XUFSPSXC_SUCCESS, XUFSPSXC_FAILURE.
References XUfsPsxc_Xfer_CmdDesc::RespUpiu, XUfsPsxc_TransSpecFlds::Value, XUfsPsxc_FillAttrUpiu, XUfsPsxc_FillDescUpiu, XUfsPsxc_ProcessUpiu.
Referenced by XUfsPsxc_Initialize.
u32 XUfsPsxc_WritePhyReg(const XUfsPsxc *InstancePtr, XUfsPsxc_UicCmd *UicCmdPtr, u32 Address, u32 Value)
This API does PHY register write with the required sequence.
InstancePtr is a pointer to the XUfsPsxc instance. UicCmdPtr is a pointer to the XUfsPsxc_UicCmd instance. Address is Address of the PHy register. Value is Value to be written to the PHY register. XUFSPSXC_SUCCESS or Error codes.
References XUfsPsxc_SendUICCmd.
Referenced by XUfsPsxc_ConfigureTxRxAttributes, XUfsPsxc_OverridePhyRxReq, XUfsPsxc_PhyInit.
u32 XUfsPsxc_ReadPhyReg(const XUfsPsxc *InstancePtr, XUfsPsxc_UicCmd *UicCmdPtr, u32 Address, u32 *Value)
This API does PHY register read with the required sequence.
InstancePtr is a pointer to the XUfsPsxc instance. UicCmdPtr is a pointer to the XUfsPsxc_UicCmd instance. Address is Address of the PHy register. Value is a pointer to store the PHY register data. XUFSPSXC_SUCCESS or Error codes.
References XUfsPsxc_SendUICCmd.
Referenced by XUfsPsxc_ConfigureTxRxAttributes, XUfsPsxc_OverridePhyRxReq, XUfsPsxc_PhyInit.
u32 XUfsPsxc_Set4KBlkSize(XUfsPsxc *InstancePtr, XUfsPsxc_Xfer_CmdDesc *CmdDescPtr)
This API set the block size to 4K for Boot LUN.
InstancePtr is a pointer to the XUfsPsxc instance. CmdDescPtr is a pointer to the XUfsPsxc_Xfer_CmdDesc instance. XUFSPSXC_SUCCESS, XUFSPSXC_FAILURE.
References XUfsPsxc_Xfer_CmdDesc::ReqUpiu, XUfsPsxc_FillDescUpiu, XUfsPsxc_ProcessUpiu.
Referenced by XUfsPsxc_CheckBootReq, XUfsPsxc_SwitchBootLUN.
u32 XUfsPsxc_PhyInit(const XUfsPsxc *InstancePtr)
This API does PHY Initialization sequence.
InstancePtr is a pointer to the XUfsPsxc instance. UicCmdPtr is a pointer to the XUfsPsxc_UicCmd instance. XUFSPSXC_SUCCESS or Error codes.
References XUfsPsxc_EnableMPhy, XUfsPsxc_ReadPhyReg, XUfsPsxc_SetRmmiConfig, XUfsPsxc_WritePhyReg.
Referenced by XUfsPsxc_HostInitialize.
u32 XUfsPsxc_SetRmmiConfig(const XUfsPsxc *InstancePtr)
This API setup RMMI configurations.
InstancePtr is a pointer to the XUfsPsxc instance. XUFSPSXC_SUCCESS or Error codes.
References XUfsPsxc_SendUICCmd.
Referenced by XUfsPsxc_PhyInit.
u32 XUfsPsxc_EnableMPhy(const XUfsPsxc *InstancePtr)
This API enable the MPHY and wait for Rx/Tx busy de-assertion.
InstancePtr is a pointer to the XUfsPsxc instance. XUFSPSXC_SUCCESS or Error codes.
References XUfsPsxc_SendUICCmd.
Referenced by XUfsPsxc_PhyInit.
u32 XUfsPsxc_OverridePhyRxReq(const XUfsPsxc *InstancePtr, u32 RxReq, u32 NumLanes)
This API Overrides the PHY rx_req.
InstancePtr is a pointer to the XUfsPsxc instance. RxReq indicates PHY should be receiver mode or not NumLanes indicates Number of connected lanes XUFSPSXC_SUCCESS or Error codes.
References XUfsPsxc_ReadPhyReg, XUfsPsxc_WritePhyReg.
Referenced by XUfsPsxc_ConfigureTxRxAttributes.
u32 XUfsPsxc_ConfigureTxRxAttributes(const XUfsPsxc *InstancePtr, u32 SpeedGear, u32 RxTermCap, u32 TxTermCap)
This API Configures the Tx/Rx Attributes.
InstancePtr is a pointer to the XUfsPsxc instance. SpeedGear is the Power Mode value to be set. RxTermCap is the Rx Termination Capability. TxTermCap is the Tx Termination Capability. XUFSPSXC_SUCCESS or Error codes.
References XUfsPsxc_OverridePhyRxReq, XUfsPsxc_ReadPhyReg, XUfsPsxc_SendUICCmd, XUfsPsxc_WritePhyReg.
Referenced by XUfsPsxc_ConfigureSpeedGear.
u32 XUfsPsxc_ReadDeviceInfo(XUfsPsxc *InstancePtr, XUfsPsxc_Xfer_CmdDesc *CmdDescPtr)
This API read the UFS device information.
InstancePtr is a pointer to the XUfsPsxc instance. CmdDescPtr is a pointer to the XUfsPsxc_Xfer_CmdDesc instance. XUFSPSXC_SUCCESS, XUFSPSXC_FAILURE.
References XUfsPsxc_Xfer_CmdDesc::RespUpiu, XUfsPsxc_FillDescUpiu, XUfsPsxc_ProcessUpiu.
Referenced by XUfsPsxc_Initialize.
void XUfsPsxc_FillWriteCmdUpiu(XUfsPsxc *InstancePtr, XUfsPsxc_Xfer_CmdDesc *CmdDescPtr, u64 Address, u32 BlkCnt, const u8 *Buff)
This API Fill the transfer request descriptor for WRITE Command.
InstancePtr is a pointer to the XUfsPsxc instance. CmdDescPtr is a pointer to the XUfsPsxc_Xfer_CmdDesc instance. Address specifies the first logical block accessed by this command. BlkCnt is the number of blocks to write. Buff is a pointer to the destination data buffer. None.
References XUfsPsxc_Xfer_CmdDesc::Prdt, XUfsPsxc_Xfer_CmdDesc::ReqUpiu, XUfsPsxc_Xfer_CmdDesc::RespUpiu.
Referenced by XUfsPsxc_WritePolled.
XUFSPSXC_H_
< prevent circular inclusions
by using protection macros
XUFSPSXC_PRDT_ENTRIES
XUFSPSXC_SCSI_GOOD
< UPIU(SCSI) 8-bits [7:0]
Referenced by XUfsPsxc_ProcessUpiu, XUfsPsxc_ReadPolled, XUfsPsxc_WritePolled.
XUFSPSXC_SCSI_CHK_CONDITION
XUFSPSXC_SCSI_BUSY
XUFSPSXC_SCSI_RESV_CONFLICT
XUFSPSXC_SCSI_TASK_SET_FULL
XUFSPSXC_DME_GET_OPCODE
XUFSPSXC_DME_SET_OPCODE
XUFSPSXC_UIC_CFG_CMD_MAX_OPCODE
XUFSPSXC_DME_LINKSTARTUP_OPCODE
XUFSPSXC_NOP_UPIU_TRANS_CODE
XUFSPSXC_CMD_UPIU_TRANS_CODE
XUFSPSXC_QRY_UPIU_TRANS_CODE
XUFSPSXC_UPIU_FLAGS_WRITE
XUFSPSXC_UPIU_FLAGS_READ
XUFSPSXC_QRY_READ
XUFSPSXC_QRY_WRITE
XUFSPSXC_SCSI_TEST_UNIT_RDY_CMD
XUFSPSXC_SCSI_READ10_CMD
XUFSPSXC_SCSI_WRITE10_CMD
XUFSPSXC_SCSI_READ16_CMD
XUFSPSXC_SCSI_WRITE16_CMD
XUFSPSXC_QRY_READ_DESC_CMD
XUFSPSXC_QRY_WRITE_DESC_CMD
XUFSPSXC_QRY_READ_ATTR_CMD
XUFSPSXC_QRY_WRITE_ATTR_CMD
XUFSPSXC_QRY_READ_FLAG_CMD
XUFSPSXC_QRY_SET_FLAG_CMD
XUFSPSXC_DEVICE_DESC_IDN
XUFSPSXC_CONFIG_DESC_IDN
XUFSPSXC_UNIT_DESC_IDN
XUFSPSXC_GEOMETRY_DESC_IDN
XUFSPSXC_DEVICE_DESC_BOOTEN_LEN
XUFSPSXC_DEVICE_DESC_REQ_LEN
XUFSPSXC_DEVICE_BOOTEN_OFFSET
XUFSPSXC_UD0_BASE_OFFSET
XUFSPSXC_UD_LEN_OFFSET
XUFSPSXC_GEOMETRY_DESC_LEN
XUFSPSXC_CFG_DESC_LEN
XUFSPSXC_CFG_DESC_HEADER_LEN
XUFSPSXC_CFG_DESC_UNITDESC_LEN
XUFSPSXC_CFG_DESC_CONT_OFFSET
XUFSPSXC_CFG_DESC_OFFSET
XUFSPSXC_LU_ENABLE_OFFSET
XUFSPSXC_BLUNEN_OFFSET
XUFSPSXC_BLKSZ_OFFSET
XUFSPSXC_MEMTYPE_OFFSET
XUFSPSXC_NUM_ALLOC_OFFSET
XUFSPSXC_MAX_CDB_LEN
XUFSPSXC_FDEVINIT_FLAG_IDN
XUFSPSXC_MAXNUMLU_OFFSET
XUFSPSXC_SEGSZ_OFFSET
XUFSPSXC_ALLOCSZ_OFFSET
XUFSPSXC_SYSCODE_CAPADJ_OFFSET
XUFSPSXC_NONPERS_CAPADJ_OFFSET
XUFSPSXC_ENH1_CAPADJ_OFFSET
XUFSPSXC_ENH2_CAPADJ_OFFSET
XUFSPSXC_ENH3_CAPADJ_OFFSET
XUFSPSXC_ENH4_CAPADJ_OFFSET
XUFSPSXC_BLUN_A
XUFSPSXC_BLUN_B
XUFSPSXC_LU_ENABLE
XUFSPSXC_LU_BLKSZ_4K
XUFSPSXC_BLUNEN_ATTRID
XUFSPSXC_WRITE
XUFSPSXC_READ
XUFSPSXC_CT_UFS_STORAGE_MASK
XUFSPSXC_INTERRUPT_CMD_MASK
XUFSPSXC_DD_DEV_TO_MEM_MASK
XUFSPSXC_DD_MEM_TO_DEV_MASK
XUFSPSXC_LBA_OVER_32BIT
XUFSPSXC_TL_OVER_16BIT
XUFSPSXC_256KB
XUFSPSXC_INVALID_LUN_ID
XUFSPSXC_BLUN_ID
XUFSPSXC_PWM_G1
XUFSPSXC_PWM_G2
XUFSPSXC_PWM_G3
XUFSPSXC_PWM_G4
XUFSPSXC_HS_G1
XUFSPSXC_HS_G2
XUFSPSXC_HS_G3
XUFSPSXC_HS_G4
XUFSPSXC_HS_G1_B
XUFSPSXC_HS_G2_B
XUFSPSXC_HS_G3_B
XUFSPSXC_HS_G4_B
XUFSPSXC_TX_RX_FAST
XUFSPSXC_TX_RX_SLOW
XUFSPSXC_HSSERIES_A
XUFSPSXC_HSSERIES_B
XUFSPSXC_GEAR4
XUFSPSXC_PWR_OK
XUFSPSXC_PWR_LOCAL
XUFSPSXC_PWR_ERR_CAP
XUFSPSXC_PWR_FATAL_ERR
XUFSPSXC_PWR_MODE_VAL
XUFSPSXC_CLK_SEL_19P2
XUFSPSXC_CLK_SEL_26
XUFSPSXC_CLK_SEL_38P4
XUFSPSXC_CLK_SEL_52
XUFSPSXC_LOWLEVEL_H_
< prevent circular inclusions
by using protection macros
SEC_TO_MSEC
XUFSPSXC_HSG1A_MIN_BPS
XUFSPSXC_HSG1B_MIN_BPS
XUFSPSXC_PWMG1_MIN_BPS
XUFSPSXC_MAX_UD0_OFFSET
XUFSPSXC_MAX_UD0_LENGTH
XUFSPSXC_HIBERN8_STATE
XUFSPSXC_SLEEP_STATE
XUFSPSXC_LS_BURST_STATE