xufspsxc_init.c
XUFSPSXC_MAX_UD0_OFFSET
XUFSPSXC_MAX_UD0_LENGTH
XUFSPSXC_HIBERN8_STATE
XUFSPSXC_SLEEP_STATE
XUFSPSXC_LS_BURST_STATE
u32 XUfsPsxc_HostInitialize(XUfsPsxc *InstancePtr)
Initializes the Host Controller.
InstancePtr is a pointer to the XUfsPsxc instance. XUFSPSXC_SUCCESS, XUFSPSXC_FAILURE, UIC Error Codes in xufspsxc.h file.
References XUfsPsxc_Config::BaseAddress, XUfsPsxc_Config::CfgClkFreqHz, XUfsPsxc_Config::InputClockHz, XUfsPsxc_Config::RefPadClk, XUfsPsxc_PhyInit, XUfsPsxc_SendUICCmd, XUfsPsxc_SetHce.
Referenced by XUfsPsxc_Initialize.
u32 XUfsPsxc_CardInitialize(XUfsPsxc *InstancePtr, XUfsPsxc_Xfer_CmdDesc *CmdDescPtr)
This API Partially Initialize the UFS device.
InstancePtr is a pointer to the XUfsPsxc instance. CmdDescPtr is a pointer to the XUfsPsxc_Xfer_CmdDesc instance. XUFSPSXC_SUCCESS, XUFSPSXC_FAILURE.
References XUfsPsxc_Xfer_CmdDesc::RespUpiu, XUfsPsxc_TransSpecFlds::Value, XUfsPsxc_FillFlagUpiu, XUfsPsxc_FillNopOutUpiu, XUfsPsxc_ProcessUpiu.
Referenced by XUfsPsxc_Initialize.
u32 XUfsPsxc_ReadDeviceInfo(XUfsPsxc *InstancePtr, XUfsPsxc_Xfer_CmdDesc *CmdDescPtr)
This API read the UFS device information.
InstancePtr is a pointer to the XUfsPsxc instance. CmdDescPtr is a pointer to the XUfsPsxc_Xfer_CmdDesc instance. XUFSPSXC_SUCCESS, XUFSPSXC_FAILURE.
References XUfsPsxc_Xfer_CmdDesc::RespUpiu, XUfsPsxc_FillDescUpiu, XUfsPsxc_ProcessUpiu.
Referenced by XUfsPsxc_Initialize.
u32 XUfsPsxc_GetLUNInfo(XUfsPsxc *InstancePtr, XUfsPsxc_Xfer_CmdDesc *CmdDescPtr)
This API update the Logical Unit information structure by reading the configuration descriptor.
InstancePtr is a pointer to the XUfsPsxc instance. CmdDescPtr is a pointer to the XUfsPsxc_Xfer_CmdDesc instance. XUFSPSXC_SUCCESS, XUFSPSXC_FAILURE.
References XUfsPsxc_Xfer_CmdDesc::RespUpiu, XUfsPsxc_TransSpecFlds::Value, XUfsPsxc_FillAttrUpiu, XUfsPsxc_FillDescUpiu, XUfsPsxc_ProcessUpiu.
Referenced by XUfsPsxc_Initialize.
u32 XUfsPsxc_Set4KBlkSize(XUfsPsxc *InstancePtr, XUfsPsxc_Xfer_CmdDesc *CmdDescPtr)
This API set the block size to 4K for Boot LUN.
InstancePtr is a pointer to the XUfsPsxc instance. CmdDescPtr is a pointer to the XUfsPsxc_Xfer_CmdDesc instance. XUFSPSXC_SUCCESS, XUFSPSXC_FAILURE.
References XUfsPsxc_Xfer_CmdDesc::ReqUpiu, XUfsPsxc_FillDescUpiu, XUfsPsxc_ProcessUpiu.
Referenced by XUfsPsxc_CheckBootReq, XUfsPsxc_SwitchBootLUN.
u32 XUfsPsxc_WritePhyReg(const XUfsPsxc *InstancePtr, XUfsPsxc_UicCmd *UicCmdPtr, u32 Address, u32 Value)
This API does PHY register write with the required sequence.
InstancePtr is a pointer to the XUfsPsxc instance. UicCmdPtr is a pointer to the XUfsPsxc_UicCmd instance. Address is Address of the PHy register. Value is Value to be written to the PHY register. XUFSPSXC_SUCCESS or Error codes.
References XUfsPsxc_SendUICCmd.
Referenced by XUfsPsxc_ConfigureTxRxAttributes, XUfsPsxc_OverridePhyRxReq, XUfsPsxc_PhyInit.
u32 XUfsPsxc_ReadPhyReg(const XUfsPsxc *InstancePtr, XUfsPsxc_UicCmd *UicCmdPtr, u32 Address, u32 *Value)
This API does PHY register read with the required sequence.
InstancePtr is a pointer to the XUfsPsxc instance. UicCmdPtr is a pointer to the XUfsPsxc_UicCmd instance. Address is Address of the PHy register. Value is a pointer to store the PHY register data. XUFSPSXC_SUCCESS or Error codes.
References XUfsPsxc_SendUICCmd.
Referenced by XUfsPsxc_ConfigureTxRxAttributes, XUfsPsxc_OverridePhyRxReq, XUfsPsxc_PhyInit.
u32 XUfsPsxc_SetRmmiConfig(const XUfsPsxc *InstancePtr)
This API setup RMMI configurations.
InstancePtr is a pointer to the XUfsPsxc instance. XUFSPSXC_SUCCESS or Error codes.
References XUfsPsxc_SendUICCmd.
Referenced by XUfsPsxc_PhyInit.
u32 XUfsPsxc_EnableMPhy(const XUfsPsxc *InstancePtr)
This API enable the MPHY and wait for Rx/Tx busy de-assertion.
InstancePtr is a pointer to the XUfsPsxc instance. XUFSPSXC_SUCCESS or Error codes.
References XUfsPsxc_SendUICCmd.
Referenced by XUfsPsxc_PhyInit.
u32 XUfsPsxc_ConfigureTxRxAttributes(const XUfsPsxc *InstancePtr, u32 SpeedGear, u32 RxTermCap, u32 TxTermCap)
This API Configures the Tx/Rx Attributes.
InstancePtr is a pointer to the XUfsPsxc instance. SpeedGear is the Power Mode value to be set. RxTermCap is the Rx Termination Capability. TxTermCap is the Tx Termination Capability. XUFSPSXC_SUCCESS or Error codes.
References XUfsPsxc_OverridePhyRxReq, XUfsPsxc_ReadPhyReg, XUfsPsxc_SendUICCmd, XUfsPsxc_WritePhyReg.
Referenced by XUfsPsxc_ConfigureSpeedGear.