xufspsxc.c
void XUfsPsxc_CfgInitialize(XUfsPsxc *InstancePtr, const XUfsPsxc_Config *ConfigPtr)
Initializes a specific XUfsPsxc instance such that the driver is ready to use.
InstancePtr is a pointer to the XUfsPsxc instance. ConfigPtr is a reference to a structure containing information about a specific UFSPSXC device. This function initializes an InstancePtr object for a specific device specified by the contents of Config. None
References XUfsPsxc_Config::BaseAddress, XUfsPsxc_Config::CfgClkFreqHz, XUfsPsxc_Config::InputClockHz, XUfsPsxc_Config::IsCacheCoherent, XUfsPsxc_Config::RefPadClk.
Referenced by UfsPsxcRawTest.
u32 XUfsPsxc_Initialize(XUfsPsxc *InstancePtr)
Initializes the Host Controller and UFS device.
InstancePtr is a pointer to the XUfsPsxc instance. XUFSPSXC_SUCCESS, XUFSPSXC_FAILURE, UIC Error Codes in xufspsxc.h file.
References XUfsPsxc_CardInitialize, XUfsPsxc_GetLUNInfo, XUfsPsxc_HostInitialize, XUfsPsxc_ReadDeviceInfo.
Referenced by UfsPsxcRawTest.
u32 XUfsPsxc_ConfigureSpeedGear(XUfsPsxc *InstancePtr, u32 SpeedGear)
This API Configures the Power Mode.
InstancePtr is a pointer to the XUfsPsxc instance. SpeedGear is the Power Mode value to be set. Refer XUFSPSXC_PWM_* XUFSPSXC_HS_* macros in xufspsxc.h file. XUFSPSXC_SUCCESS or ERROR_CODE.
References XUfsPsxc_Config::BaseAddress, XUfsPsxc_ConfigureTxRxAttributes.
u32 XUfsPsxc_CheckBootReq(XUfsPsxc *InstancePtr)
This API check boot requirements like BootEnable and bBootLunEn.
InstancePtr is a pointer to the XUfsPsxc instance. XUFSPSXC_SUCCESS or ERROR_CODE.
References XUfsPsxc_Set4KBlkSize.
u32 XUfsPsxc_SwitchBootLUN(XUfsPsxc *InstancePtr)
This API switch the Boot-LU(1->2 or 2->1) by modifying the Attributes and also set the block size to 4K if it is not 4K.
InstancePtr is a pointer to the XUfsPsxc instance. XUFSPSXC_SUCCESS or ERROR_CODE.
References XUfsPsxc_Xfer_CmdDesc::RespUpiu, XUfsPsxc_TransSpecFlds::Value, XUfsPsxc_FillAttrUpiu, XUfsPsxc_ProcessUpiu, XUfsPsxc_Set4KBlkSize.
Referenced by UfsPsxcRawTest.
u32 XUfsPsxc_ReadPolled(XUfsPsxc *InstancePtr, u32 Lun, u64 Address, u32 BlkCnt, const u8 *Buff)
This API perform the data read from the UFS device.
InstancePtr is a pointer to the XUfsPsxc instance. Lun is a Logical Unit Number. Address is the starting Logical Unit number. BlkCnt is the number of blocks to be read. Buff is a pointer to the destination data buffer. XUFSPSXC_SUCCESS, XUFSPSXC_FAILURE.
References XUfsPsxc_Config::IsCacheCoherent, XUfsPsxc_Xfer_CmdDesc::ReqUpiu, XUfsPsxc_Xfer_CmdDesc::RespUpiu, XUfsPsxc_FillReadCmdUpiu, XUfsPsxc_FillTestUnitRdyUpiu, XUfsPsxc_ProcessUpiu, XUFSPSXC_SCSI_GOOD.
Referenced by UfsPsxcRawTest.
u32 XUfsPsxc_WritePolled(XUfsPsxc *InstancePtr, u32 Lun, u64 Address, u32 BlkCnt, const u8 *Buff)
This API perform the data Write to the UFS device.
InstancePtr is a pointer to the XUfsPsxc instance. Lun is a Logical Unit Number. Address is the starting Logical Unit number. BlkCnt is the number of blocks to be read. Buff is a pointer to the destination data buffer. XUFSPSXC_SUCCESS, XUFSPSXC_FAILURE.
References XUfsPsxc_Config::IsCacheCoherent, XUfsPsxc_Xfer_CmdDesc::ReqUpiu, XUfsPsxc_Xfer_CmdDesc::RespUpiu, XUfsPsxc_FillTestUnitRdyUpiu, XUfsPsxc_FillWriteCmdUpiu, XUfsPsxc_ProcessUpiu, XUFSPSXC_SCSI_GOOD.
Referenced by UfsPsxcRawTest.