xufspsxc_control.h
XUFSPSXC_LOWLEVEL_H_
< prevent circular inclusions
by using protection macros
u32 XUfsPsxc_SendUICCmd(const XUfsPsxc *InstancePtr, XUfsPsxc_UicCmd *UicCmdPtr)
Send UIC Command.
InstancePtr is a pointer to the XUfsPsxc instance. UicCmdPtr is a pointer to the XUfsPsxc_UicCmd instance. Refer UIC Error Codes in xufspsxc.h file.
References XUfsPsxc_Config::BaseAddress.
Referenced by XUfsPsxc_ConfigureTxRxAttributes, XUfsPsxc_EnableMPhy, XUfsPsxc_HostInitialize, XUfsPsxc_ReadPhyReg, XUfsPsxc_SetRmmiConfig, XUfsPsxc_WritePhyReg.
u32 XUfsPsxc_SetHce(const XUfsPsxc *InstancePtr, u32 Value)
Perform the Host Controller Enable/Disable.
InstancePtr is a pointer to the XUfsPsxc instance. Value is used to enable/disable Host Controller. XUFSPSXC_SUCCESS for Success XUFSPSXC_FAILURE for failure
References XUfsPsxc_Config::BaseAddress.
Referenced by XUfsPsxc_HostInitialize.
void XUfsPsxc_FillNopOutUpiu(XUfsPsxc *InstancePtr, XUfsPsxc_Xfer_CmdDesc *CmdDescPtr)
This API Fill the transfer request descriptor for NOP-OUT UPIU.
InstancePtr is a pointer to the XUfsPsxc instance. CmdDescPtr is a pointer to the XUfsPsxc_Xfer_CmdDesc instance. None.
References XUfsPsxc_Xfer_CmdDesc::RespUpiu.
Referenced by XUfsPsxc_CardInitialize.
void XUfsPsxc_FillTestUnitRdyUpiu(XUfsPsxc *InstancePtr, XUfsPsxc_Xfer_CmdDesc *CmdDescPtr)
This API Fill the transfer request descriptor for TEST UNIT READY Command.
InstancePtr is a pointer to the XUfsPsxc instance. CmdDescPtr is a pointer to the XUfsPsxc_Xfer_CmdDesc instance. None.
References XUfsPsxc_Xfer_CmdDesc::RespUpiu.
Referenced by XUfsPsxc_ReadPolled, XUfsPsxc_WritePolled.
void XUfsPsxc_FillReadCmdUpiu(XUfsPsxc *InstancePtr, XUfsPsxc_Xfer_CmdDesc *CmdDescPtr, u64 Address, u32 BlkCnt, const u8 *Buff)
This API Fill the transfer request descriptor for READ Command.
InstancePtr is a pointer to the XUfsPsxc instance. CmdDescPtr is a pointer to the XUfsPsxc_Xfer_CmdDesc instance. Address specifies the first logical block accessed by this command. BlkCnt is the number of blocks to be read. Buff is a pointer to the destination data buffer. None.
References XUfsPsxc_Xfer_CmdDesc::Prdt, XUfsPsxc_Xfer_CmdDesc::ReqUpiu, XUfsPsxc_Xfer_CmdDesc::RespUpiu.
Referenced by XUfsPsxc_ReadPolled.
u32 XUfsPsxc_ProcessUpiu(const XUfsPsxc *InstancePtr, const XUfsPsxc_Xfer_CmdDesc *CmdDescPtr)
This API send the UPIU to the UFS device.
InstancePtr is a pointer to the XUfsPsxc instance. CmdDescPtr is a pointer to the XUfsPsxc_Xfer_CmdDesc instance. Refer OCS in xufspsxc.h file, XUFSPSXC_FAILURE
References XUfsPsxc_Config::BaseAddress, XUfsPsxc_Xfer_ReqDesc::DW2_Ocs, XUfsPsxc_Config::IsCacheCoherent, XUfsPsxc_Xfer_CmdDesc::Prdt, XUfsPsxc_Xfer_CmdDesc::ReqUpiu, XUfsPsxc_Xfer_CmdDesc::RespUpiu, XUFSPSXC_SCSI_GOOD.
Referenced by XUfsPsxc_CardInitialize, XUfsPsxc_GetLUNInfo, XUfsPsxc_ReadDeviceInfo, XUfsPsxc_ReadPolled, XUfsPsxc_Set4KBlkSize, XUfsPsxc_SwitchBootLUN, XUfsPsxc_WritePolled.
void XUfsPsxc_FillFlagUpiu(XUfsPsxc *InstancePtr, XUfsPsxc_Xfer_CmdDesc *CmdDescPtr, u32 IsRead, u32 FlagIDn)
This API Fill the transfer request descriptor for READ/SET FLAG Command.
InstancePtr is a pointer to the XUfsPsxc instance. CmdDescPtr is a pointer to the XUfsPsxc_Xfer_CmdDesc instance. IsRead is a flag to indicate whether the operation is read or write. FlagIDn is a Flag Identification number. None.
References XUfsPsxc_Xfer_CmdDesc::RespUpiu, XUfsPsxc_TransSpecFlds::Value.
Referenced by XUfsPsxc_CardInitialize.
void XUfsPsxc_FillDescUpiu(XUfsPsxc *InstancePtr, XUfsPsxc_Xfer_CmdDesc *CmdDescPtr, u32 Tsf_DW0, u32 IsRead, u32 Length)
This API Fill the transfer request descriptor for read or write Descriptor Command.
InstancePtr is a pointer to the XUfsPsxc instance. CmdDescPtr is a pointer to the XUfsPsxc_Xfer_CmdDesc instance. Tsf_DW0 contains information about Description identification Number(3rd byte), Index(2nd byte) and Selector(1st byte). IsRead is a flag to indicate whether the operation is read or write descriptor. Length is the number of bytes to read the descriptor. None.
References XUfsPsxc_Xfer_CmdDesc::RespUpiu.
Referenced by XUfsPsxc_GetLUNInfo, XUfsPsxc_ReadDeviceInfo, XUfsPsxc_Set4KBlkSize.
void XUfsPsxc_FillAttrUpiu(XUfsPsxc *InstancePtr, XUfsPsxc_Xfer_CmdDesc *CmdDescPtr, u32 IsRead, u32 AttrIDn, u32 Value)
This API Fill the transfer request descriptor for read or write Attribute Command.
InstancePtr is a pointer to the XUfsPsxc instance. CmdDescPtr is a pointer to the XUfsPsxc_Xfer_CmdDesc instance. IsRead is a flag to indicate whether the operation is read or write descriptor. AttrIDn is a Attribute Identification number. Value is value to be written to the attributes. None.
References XUfsPsxc_Xfer_CmdDesc::RespUpiu.
Referenced by XUfsPsxc_GetLUNInfo, XUfsPsxc_SwitchBootLUN.
u32 XUfsPsxc_HostInitialize(XUfsPsxc *InstancePtr)
Initializes the Host Controller.
InstancePtr is a pointer to the XUfsPsxc instance. XUFSPSXC_SUCCESS, XUFSPSXC_FAILURE, UIC Error Codes in xufspsxc.h file.
References XUfsPsxc_Config::BaseAddress, XUfsPsxc_Config::CfgClkFreqHz, XUfsPsxc_Config::InputClockHz, XUfsPsxc_Config::RefPadClk, XUfsPsxc_PhyInit, XUfsPsxc_SendUICCmd, XUfsPsxc_SetHce.
Referenced by XUfsPsxc_Initialize.
u32 XUfsPsxc_CardInitialize(XUfsPsxc *InstancePtr, XUfsPsxc_Xfer_CmdDesc *CmdDescPtr)
This API Partially Initialize the UFS device.
InstancePtr is a pointer to the XUfsPsxc instance. CmdDescPtr is a pointer to the XUfsPsxc_Xfer_CmdDesc instance. XUFSPSXC_SUCCESS, XUFSPSXC_FAILURE.
References XUfsPsxc_Xfer_CmdDesc::RespUpiu, XUfsPsxc_TransSpecFlds::Value, XUfsPsxc_FillFlagUpiu, XUfsPsxc_FillNopOutUpiu, XUfsPsxc_ProcessUpiu.
Referenced by XUfsPsxc_Initialize.
u32 XUfsPsxc_GetLUNInfo(XUfsPsxc *InstancePtr, XUfsPsxc_Xfer_CmdDesc *CmdDescPtr)
This API update the Logical Unit information structure by reading the configuration descriptor.
InstancePtr is a pointer to the XUfsPsxc instance. CmdDescPtr is a pointer to the XUfsPsxc_Xfer_CmdDesc instance. XUFSPSXC_SUCCESS, XUFSPSXC_FAILURE.
References XUfsPsxc_Xfer_CmdDesc::RespUpiu, XUfsPsxc_TransSpecFlds::Value, XUfsPsxc_FillAttrUpiu, XUfsPsxc_FillDescUpiu, XUfsPsxc_ProcessUpiu.
Referenced by XUfsPsxc_Initialize.
u32 XUfsPsxc_WritePhyReg(const XUfsPsxc *InstancePtr, XUfsPsxc_UicCmd *UicCmdPtr, u32 Address, u32 Value)
This API does PHY register write with the required sequence.
InstancePtr is a pointer to the XUfsPsxc instance. UicCmdPtr is a pointer to the XUfsPsxc_UicCmd instance. Address is Address of the PHy register. Value is Value to be written to the PHY register. XUFSPSXC_SUCCESS or Error codes.
References XUfsPsxc_SendUICCmd.
Referenced by XUfsPsxc_ConfigureTxRxAttributes, XUfsPsxc_OverridePhyRxReq, XUfsPsxc_PhyInit.
u32 XUfsPsxc_ReadPhyReg(const XUfsPsxc *InstancePtr, XUfsPsxc_UicCmd *UicCmdPtr, u32 Address, u32 *Value)
This API does PHY register read with the required sequence.
InstancePtr is a pointer to the XUfsPsxc instance. UicCmdPtr is a pointer to the XUfsPsxc_UicCmd instance. Address is Address of the PHy register. Value is a pointer to store the PHY register data. XUFSPSXC_SUCCESS or Error codes.
References XUfsPsxc_SendUICCmd.
Referenced by XUfsPsxc_ConfigureTxRxAttributes, XUfsPsxc_OverridePhyRxReq, XUfsPsxc_PhyInit.
u32 XUfsPsxc_Set4KBlkSize(XUfsPsxc *InstancePtr, XUfsPsxc_Xfer_CmdDesc *CmdDescPtr)
This API set the block size to 4K for Boot LUN.
InstancePtr is a pointer to the XUfsPsxc instance. CmdDescPtr is a pointer to the XUfsPsxc_Xfer_CmdDesc instance. XUFSPSXC_SUCCESS, XUFSPSXC_FAILURE.
References XUfsPsxc_Xfer_CmdDesc::ReqUpiu, XUfsPsxc_FillDescUpiu, XUfsPsxc_ProcessUpiu.
Referenced by XUfsPsxc_CheckBootReq, XUfsPsxc_SwitchBootLUN.
u32 XUfsPsxc_PhyInit(const XUfsPsxc *InstancePtr)
This API does PHY Initialization sequence.
InstancePtr is a pointer to the XUfsPsxc instance. UicCmdPtr is a pointer to the XUfsPsxc_UicCmd instance. XUFSPSXC_SUCCESS or Error codes.
References XUfsPsxc_EnableMPhy, XUfsPsxc_ReadPhyReg, XUfsPsxc_SetRmmiConfig, XUfsPsxc_WritePhyReg.
Referenced by XUfsPsxc_HostInitialize.
u32 XUfsPsxc_SetRmmiConfig(const XUfsPsxc *InstancePtr)
This API setup RMMI configurations.
InstancePtr is a pointer to the XUfsPsxc instance. XUFSPSXC_SUCCESS or Error codes.
References XUfsPsxc_SendUICCmd.
Referenced by XUfsPsxc_PhyInit.
u32 XUfsPsxc_EnableMPhy(const XUfsPsxc *InstancePtr)
This API enable the MPHY and wait for Rx/Tx busy de-assertion.
InstancePtr is a pointer to the XUfsPsxc instance. XUFSPSXC_SUCCESS or Error codes.
References XUfsPsxc_SendUICCmd.
Referenced by XUfsPsxc_PhyInit.
u32 XUfsPsxc_OverridePhyRxReq(const XUfsPsxc *InstancePtr, u32 RxReq, u32 NumLanes)
This API Overrides the PHY rx_req.
InstancePtr is a pointer to the XUfsPsxc instance. RxReq indicates PHY should be receiver mode or not NumLanes indicates Number of connected lanes XUFSPSXC_SUCCESS or Error codes.
References XUfsPsxc_ReadPhyReg, XUfsPsxc_WritePhyReg.
Referenced by XUfsPsxc_ConfigureTxRxAttributes.
u32 XUfsPsxc_ConfigureTxRxAttributes(const XUfsPsxc *InstancePtr, u32 SpeedGear, u32 RxTermCap, u32 TxTermCap)
This API Configures the Tx/Rx Attributes.
InstancePtr is a pointer to the XUfsPsxc instance. SpeedGear is the Power Mode value to be set. RxTermCap is the Rx Termination Capability. TxTermCap is the Tx Termination Capability. XUFSPSXC_SUCCESS or Error codes.
References XUfsPsxc_OverridePhyRxReq, XUfsPsxc_ReadPhyReg, XUfsPsxc_SendUICCmd, XUfsPsxc_WritePhyReg.
Referenced by XUfsPsxc_ConfigureSpeedGear.
u32 XUfsPsxc_ReadDeviceInfo(XUfsPsxc *InstancePtr, XUfsPsxc_Xfer_CmdDesc *CmdDescPtr)
This API read the UFS device information.
InstancePtr is a pointer to the XUfsPsxc instance. CmdDescPtr is a pointer to the XUfsPsxc_Xfer_CmdDesc instance. XUFSPSXC_SUCCESS, XUFSPSXC_FAILURE.
References XUfsPsxc_Xfer_CmdDesc::RespUpiu, XUfsPsxc_FillDescUpiu, XUfsPsxc_ProcessUpiu.
Referenced by XUfsPsxc_Initialize.
void XUfsPsxc_FillWriteCmdUpiu(XUfsPsxc *InstancePtr, XUfsPsxc_Xfer_CmdDesc *CmdDescPtr, u64 Address, u32 BlkCnt, const u8 *Buff)
This API Fill the transfer request descriptor for WRITE Command.
InstancePtr is a pointer to the XUfsPsxc instance. CmdDescPtr is a pointer to the XUfsPsxc_Xfer_CmdDesc instance. Address specifies the first logical block accessed by this command. BlkCnt is the number of blocks to write. Buff is a pointer to the destination data buffer. None.
References XUfsPsxc_Xfer_CmdDesc::Prdt, XUfsPsxc_Xfer_CmdDesc::ReqUpiu, XUfsPsxc_Xfer_CmdDesc::RespUpiu.
Referenced by XUfsPsxc_WritePolled.