hdcp1x
XHdcp1x_CipherHandlerType
XHdcp1x_CipherRequestType
XHdcp1x_Rx_StateType
XHdcp1x_Tx_StateType
XHdcp1x_HandlerType
XHdcp1x_RepeaterStateMachineHandlerType
XHdcp1x_TopologyField
XHdcp1x_PortHandlerType
An (re)auth request.
XHdcp1x_EventType
XHdcp1x_StateType
XHdcp1x_EventType
XHdcp1x_StateType
typedef void(* XHdcp1x_Callback)(void *CallbackRef))(void *CallbackRef)
This typedef defines the callback interface that is to be used for interrupts within this driver.
typedef void(* XHdcp1x_Printf)(const char *fmt,...))(const char *fmt,...)
This typedef defines the function interface that is to be used for debug print statements within this driver.
typedef void(* XHdcp1x_LogMsg)(const char *fmt,...))(const char *fmt,...)
This typedef defines the function interface that is to be used for debug log message statements within this driver.
typedef int(* XHdcp1x_RunDdcHandler)(u8 DeviceAddress, u16 ByteCount, u8 *BufferPtr, u8 Stop, void *RefPtr))(u8 DeviceAddress, u16 ByteCount, u8 *BufferPtr, u8 Stop, void *RefPtr)
Callback type used for calling DDC read and write functions.
DeviceAddress is the (i2c) device address of the HDCP port. ByteCount is the amount of data bytes in the buffer to read or write. BufferPtr is a pointer to a buffer that is used for reading or writing. Stop is a flag to control if a stop token is set or not. RefPtr is a callback reference passed in by the upper layer when setting the DDC reading and writing functions, and passed back to the upper layer when the callback is invoked. XST_SUCCESS The read action was successful.XST_FAILURE The read action failed. None.
typedef void(* XHdcp1x_SetDdcHandler)(void *HandlerRef, u32 Data))(void *HandlerRef, u32 Data)
This typedef defines the function interface that is to be used for setting the DDC handler for HDMI implementation of HDCP functionality over HDMI within this driver.
typedef u32(* XHdcp1x_GetDdcHandler)(void *HandlerRef))(void *HandlerRef)
This typedef defines the function interface that is to be used to get the DDC handler for implementation of HDCP functionality over HDMI within this driver.
typedef u64 XHdcp1x_Ksv
This typedef defines a memory to store a Key Selection Vector (KSV)
typedef struct XHdcp1x_PortStruct XHdcp1x_Port
This typedef contains an instance of the HDCP port.
typedef int(* XHdcp1x_TimerStart)(void *InstancePtr, u16 TmoInMs))(void *InstancePtr, u16 TmoInMs)
This typedef defines the function interface that is to be used for starting a one shot timer on behalf of an HDCP interface within the underlying platform.
typedef int(* XHdcp1x_TimerStop)(void *InstancePtr))(void *InstancePtr)
This typedef defines the function interface that is to be used for stopping a timer on behalf of an HDCP interface.
typedef int(* XHdcp1x_TimerDelay)(void *InstancePtr, u16 DelayInMs))(void *InstancePtr, u16 DelayInMs)
This typedef defines the function interface that is to be used for performing a busy delay on behalf of an HDCP interface.
typedef int(* XHdcp1x_KsvRevokeCheck)(const XHdcp1x *InstancePtr, u64 Ksv))(const XHdcp1x *InstancePtr, u64 Ksv)
This typedef defines the function interface that is to be used for checking a specific KSV against the platforms revocation list.
typedef struct XHdcp1x_PortPhyIfAdaptorS XHdcp1x_PortPhyIfAdaptor
The typedef defines the HDCP port adaptor table.
This contains a series of functions that map the external interface of the HDCP port device to the underlying physical interface that it is running over
XHdcp1x_Printf XHdcp1xDebugPrintf
Instance of function interface used for debug print statement.
Referenced by XHdcp1x_SetDebugPrintf.
XHdcp1x_LogMsg XHdcp1xDebugLogMsg
Instance of function interface used for debug log message statement.
Referenced by XHdcp1x_SetDebugLogMsg.
XHdcp1x_KsvRevokeCheck XHdcp1xKsvRevokeCheck
Instance of function interface used for checking a specific KSV against the platforms revocation list.
Referenced by XHdcp1x_PlatformIsKsvRevoked, XHdcp1x_SetKsvRevokeCheck.
XHdcp1x_Printf XHdcp1xDebugPrintf
Instance of function interface used for debug print statement.
Referenced by XHdcp1x_SetDebugPrintf.
XHdcp1x_LogMsg XHdcp1xDebugLogMsg
Instance of function interface used for debug log message statement.
Referenced by XHdcp1x_SetDebugLogMsg.
XHdcp1x_KsvRevokeCheck XHdcp1xKsvRevokeCheck
Instance of function interface used for checking a specific KSV against the platforms revocation list.
Referenced by XHdcp1x_PlatformIsKsvRevoked, XHdcp1x_SetKsvRevokeCheck.
XHdcp1x_Config XHdcp1x_ConfigTable[][]
Instance of Lookup table of HDCP instance(s) in the design.
int XHdcp1x_CfgInitialize(XHdcp1x *InstancePtr, const XHdcp1x_Config *CfgPtr, void *PhyIfPtr, UINTPTR EffectiveAddr)
This function retrieves the configuration for this HDCP instance and fills in the InstancePtr->Config structure.
InstancePtr is the device whose adaptor is to be determined. CfgPtr is the configuration of the instance. PhyIfPtr is pointer to the underlying physical interface. EffectiveAddr is the device base address in the virtual memory space. If the address translation is not used, then the physical address is passed. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x_PortStruct::Adaptor, XHdcp1x_Tx::AuthenticatedCallback, XHdcp1x_Rx::AuthenticatedCallback, XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHdcp1x_Rx::DdcGetDataCallback, XHdcp1x_Tx::DdcRead, XHdcp1x_Rx::DdcSetAddressCallback, XHdcp1x_Rx::DdcSetDataCallback, XHdcp1x_Tx::DdcWrite, XHdcp1x_Rx::EncryptionUpdateCallback, XHdcp1x_PortPhyIfAdaptorS::Init, XHdcp1x_Tx::IsAuthenticatedCallbackSet, XHdcp1x_Rx::IsAuthenticatedCallbackSet, XHdcp1x_Rx::IsDdcGetDataCallbackSet, XHdcp1x_Tx::IsDdcReadSet, XHdcp1x_Rx::IsDdcSetAddressCallbackSet, XHdcp1x_Rx::IsDdcSetDataCallbackSet, XHdcp1x_Tx::IsDdcWriteSet, XHdcp1x_Rx::IsEncryptionUpdateCallbackSet, XHdcp1x_Config::IsHDMI, XHdcp1x::IsReady, XHdcp1x_Rx::IsRepeaterDownstreamAuthCallbackSet, XHdcp1x_Tx::IsRepeaterExchangeCallbackSet, XHdcp1x_Config::IsRx, XHdcp1x_Rx::IsTopologyUpdateCallbackSet, XHdcp1x_Tx::IsUnauthenticatedCallbackSet, XHdcp1x_Rx::IsUnauthenticatedCallbackSet, XHdcp1x_PortStruct::PhyIfPtr, XHdcp1x::Port, XHdcp1x_Rx::RepeaterDownstreamAuthCallback, XHdcp1x_Tx::RepeaterExchangeCallback, XHdcp1x::Rx, XHdcp1x_Rx::TopologyUpdateCallback, XHdcp1x::Tx, XHdcp1x_Tx::UnauthenticatedCallback, XHdcp1x_Rx::UnauthenticatedCallback, XHDCP1X_CIPHER_BITMASK_TYPE_DIRECTION, XHDCP1X_CIPHER_BITMASK_TYPE_PROTOCOL, XHDCP1X_CIPHER_REG_TYPE, XHDCP1X_CIPHER_VALUE_TYPE_DIRECTION_RX, XHDCP1X_CIPHER_VALUE_TYPE_PROTOCOL_HDMI, XHdcp1x_CipherInit, XHdcp1x_PortDetermineAdaptor, XHdcp1x_ReadReg, XHdcp1x_RxInit, XHdcp1x_TxInit.
void XHdcp1x_LateInit(XHdcp1x *InstancePtr)
int XHdcp1x_Poll(XHdcp1x *InstancePtr)
This function polls an HDCP interface.
InstancePtr is the interface to poll. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_RxPoll, XHdcp1x_TxPoll.
int XHdcp1x_DownstreamReady(XHdcp1x *InstancePtr)
This function posts a DOWNSTREAMREADY event to an HDCP interface.
InstancePtr is the interface to reset. XST_SUCCESS if successful. XST_FAILURE otherwise. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_RxDownstreamReady.
int XHdcp1x_GetRepeaterInfo(XHdcp1x *InstancePtr, XHdcp1x_RepeaterExchange *RepeaterInfoPtr)
This function copies the V'H0, V'H1, V'H2, V'H3, V'H4, KSVList and BInfo values in the HDCP RX HDCP Instance for Repeater validation .
InstancePtr is the receiver instance. RepeaterInfoPtr is the Repeater information in the transmitter instance. XST_SUCCESS if successful. XST_FAILURE otherwise. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_RxGetRepeaterInfo.
int XHdcp1x_Enable_ECF_Slots(XHdcp1x *InstancePtr, u64 timeslots)
This function enables an HDCP MST ECF Field.
InstancePtr is the interface to enable. timeslots is the time slots to be enabled for ECF. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_TxEnableEcfTimeslots.
int XHdcp1x_SetRepeater(XHdcp1x *InstancePtr, u8 State)
This function sets the Repeater functionality for an HDCP interface.
InstancePtr is the interface to disable. State is either TRUE or FALSE XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x::Config, XHdcp1x::IsRepeater, XHdcp1x_Config::IsRx, XHdcp1x_RxSetRepeaterBcaps.
int XHdcp1x_Reset(XHdcp1x *InstancePtr)
This function resets an HDCP interface.
InstancePtr is the interface to reset. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_RxReset, XHdcp1x_TxReset.
int XHdcp1x_Enable(XHdcp1x *InstancePtr)
This function enables an HDCP interface.
InstancePtr is the interface to enable. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x_PortStruct::Adaptor, XHdcp1x::Config, XHdcp1x_PortPhyIfAdaptorS::Init, XHdcp1x_Config::IsRx, XHdcp1x::Port, XHdcp1x_RxEnable, XHdcp1x_TxEnable.
int XHdcp1x_Disable(XHdcp1x *InstancePtr)
This function disables an HDCP interface.
InstancePtr is the interface to disable. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_RxDisable, XHdcp1x_TxDisable.
int XHdcp1x_SetPhysicalState(XHdcp1x *InstancePtr, int IsUp)
This function updates the state of the underlying physical interface.
InstancePtr is the interface to update. IsUp indicates the state of the underlying physical interface. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_RxSetPhysicalState, XHdcp1x_TxSetPhysicalState.
int XHdcp1x_SetLaneCount(XHdcp1x *InstancePtr, int LaneCount)
This function sets the lane count of a hdcp interface.
InstancePtr is the interface to update. LaneCount is the lane count. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x::Config, XHdcp1x_Config::IsHDMI, XHdcp1x_Config::IsRx, XHdcp1x_RxSetLaneCount, XHdcp1x_TxSetLaneCount.
int XHdcp1x_SetMSTMode(XHdcp1x *InstancePtr, int mode)
This function sets the MST/ SST of a hdcp interface.
InstancePtr is the interface to update. mode determines the MST/ SST configuration. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x::Config, XHdcp1x_Config::IsHDMI, XHdcp1x_Config::IsRx, XHdcp1x_TxSetMSTMode.
int XHdcp1x_Authenticate(XHdcp1x *InstancePtr)
This function initiates authentication of an HDCP interface.
InstancePtr is the interface to initiate authentication on. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_RxAuthenticate, XHdcp1x_TxAuthenticate.
int XHdcp1x_ReadDownstream(XHdcp1x *InstancePtr)
This function initiates downstream read of READY bit and consequently the second part of Repeater authentication.
InstancePtr is the interface to initiate authentication on. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_TxReadDownstream.
int XHdcp1x_IsInProgress(const XHdcp1x *InstancePtr)
This function queries an interface to determine if authentication is in progress.
InstancePtr is the interface to query. Truth value indicating authentication in progress (TRUE) or not (FALSE). None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_TxIsInProgress.
int XHdcp1x_IsAuthenticated(const XHdcp1x *InstancePtr)
This function queries an interface to determine if it has successfully completed authentication.
InstancePtr is the interface to query. Truth value indicating authenticated (TRUE) or not (FALSE). None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_RxIsAuthenticated, XHdcp1x_TxIsAuthenticated.
Referenced by XHdcp1x_EnableEncryption, XHdcp1x_IsEncrypted.
int XHdcp1x_IsInComputations(const XHdcp1x *InstancePtr)
This function queries an interface to determine if it is in the state of computations or not.
InstancePtr is the interface to query. Truth value indicating authenticated (TRUE) or not (FALSE). None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_RxIsInComputations, XHdcp1x_TxIsInComputations.
int XHdcp1x_IsInWaitforready(const XHdcp1x *InstancePtr)
This function queries an interface to determine if it is in the wait-for-ready state or not.
InstancePtr is the interface to query. Truth value indicating authenticated (TRUE) or not (FALSE). None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_RxIsInWaitforready, XHdcp1x_TxIsInWaitforready.
int XHdcp1x_IsDwnstrmCapable(const XHdcp1x *InstancePtr)
This function queries the device connected to the downstream interface to determine if it supports hdcp or not.
InstancePtr is the interface to query. Truth value indicating HDCP capability (TRUE) or not (FALSE). None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_TxIsDownstrmCapable.
int XHdcp1x_IsEnabled(const XHdcp1x *InstancePtr)
This function queries an interface to determine if it is enabled.
InstancePtr is the interface to query. Truth value indicating enabled (TRUE) or not (FALSE). None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_RxIsEnabled, XHdcp1x_TxIsEnabled.
u64 XHdcp1x_GetEncryption(const XHdcp1x *InstancePtr)
This function retrieves the current encryption map of the video streams traversing an hdcp interface.
InstancePtr is the interface to query. The current encryption map. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_RxGetEncryption, XHdcp1x_TxGetEncryption.
Referenced by XHdcp1x_IsEncrypted.
int XHdcp1x_IsEncrypted(const XHdcp1x *InstancePtr)
This function determines if the video stream is encrypted.
The traffic is encrypted if the encryption bit map is non-zero and the interface is authenticated. InstancePtr is a pointer to the HDCP instance. Truth value indicating encrypted (TRUE) or not (FALSE). None.
References XHdcp1x_GetEncryption, XHdcp1x_IsAuthenticated.
Referenced by XHdcp1x_RxInfo, XHdcp1x_TxInfo.
int XHdcp1x_EnableEncryption(XHdcp1x *InstancePtr, u64 Map)
This function enables encryption on a series of streams within an HDCP interface.
InstancePtr is the interface to configure. Map is the stream map to enable encryption on. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x_PortStruct::Adaptor, XHdcp1x::Config, XHdcp1x_PortPhyIfAdaptorS::Init, XHdcp1x_Config::IsRx, XHdcp1x_Tx::mode, XHdcp1x::Port, XHdcp1x::Tx, UNUSED, XHdcp1x_IsAuthenticated, XHdcp1x_TxEnableEncryption.
int XHdcp1x_DisableEncryption(XHdcp1x *InstancePtr, u64 Map)
This function disables encryption on a series of streams within an HDCP interface.
InstancePtr is the interface to configure. Map is the stream map to disable encryption on. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, UNUSED, XHdcp1x_TxDisableEncryption.
int XHdcp1x_SetKeySelect(XHdcp1x *InstancePtr, u8 KeySelect)
This function sets the key selection vector that is to be used by the HDCP cipher.
InstancePtr is the interface to configure. KeySelect is the key selection vector. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x_CipherSetKeySelect.
void XHdcp1x_HandleTimeout(void *InstancePtr)
This function handles a timeout on an HDCP interface.
InstancePtr is the interface. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHDCP1X_DEBUG_PRINTF, XHdcp1x_RxHandleTimeout, XHdcp1x_TxHandleTimeout.
void XHdcp1x_SetDebugPrintf(XHdcp1x_Printf PrintfFunc)
This function sets the debug printf function for the module.
PrintfFunc is the printf function. None.
References XHdcp1xDebugPrintf.
void XHdcp1x_SetDebugLogMsg(XHdcp1x_LogMsg LogFunc)
This function sets the debug log message function for the module.
LogFunc is the debug logging function. None.
References XHdcp1xDebugLogMsg.
void XHdcp1x_SetKsvRevokeCheck(XHdcp1x_KsvRevokeCheck RevokeCheckFunc)
This function sets the KSV revocation list check function for the module.
RevokeCheckFunc is the KSV revocation list check function. None.
References XHdcp1xKsvRevokeCheck.
void XHdcp1x_SetTimerStart(XHdcp1x *InstancePtr, XHdcp1x_TimerStart TimerStartFunc)
This function sets timer start function for the module.
InstancePtr is the pointer to the HDCP interface. TimerStartFunc is the timer start function. None.
References XHdcp1x::XHdcp1xTimerStart.
void XHdcp1x_SetTimerStop(XHdcp1x *InstancePtr, XHdcp1x_TimerStop TimerStopFunc)
This function sets timer stop function for the module.
InstancePtr is the pointer to the HDCP interface. TimerStopFunc is the timer stop function. None.
References XHdcp1x::XHdcp1xTimerStop.
void XHdcp1x_SetTimerDelay(XHdcp1x *InstancePtr, XHdcp1x_TimerDelay TimerDelayFunc)
This function sets timer busy delay function for the module.
InstancePtr is the pointer to the HDCP interface. TimerDelayFunc is the timer busy delay function. None.
References XHdcp1x::XHdcp1xTimerDelay.
u32 XHdcp1x_GetDriverVersion(void)
This function retrieves the version of the HDCP driver software.
The software driver version. None.
References DRIVER_VERSION.
Referenced by XHdcp1x_RxInfo, XHdcp1x_TxInfo.
u32 XHdcp1x_GetVersion(const XHdcp1x *InstancePtr)
This function retrieves the cipher version of an HDCP interface.
InstancePtr is the interface to query. The cipher version used by the interface None.
References XHdcp1x_CipherGetVersion.
void XHdcp1x_Info(const XHdcp1x *InstancePtr)
This function performs a debug display of an HDCP instance.
InstancePtr is the interface to display. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHDCP1X_DEBUG_PRINTF, XHdcp1x_RxInfo, XHdcp1x_TxInfo.
void XHdcp1x_ProcessAKsv(XHdcp1x *InstancePtr)
This function processes the AKsv.
InstancePtr is the interface to display. None.
References XHdcp1x_PortStruct::Adaptor, XHdcp1x_PortPhyIfAdaptorS::CallbackHandler, XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x::Port.
void * XHdcp1x_GetTopology(XHdcp1x *InstancePtr)
This function returns a pointer to the downstream Topology structure.
InstancePtr is a pointer to the XHdcp14 core instance. A pointer to the XHdcp14 Topology structure or NULL when the topology info is invalid. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHDCP1X_DEBUG_PRINTF, XHdcp1x_TxGetTopology.
void XHdcp1x_DisableBlank(XHdcp1x *InstancePtr)
This function disables the blank output for the cipher.
InstancePtr is a pointer to the XHdcp14 core instance. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_TxDisableBlank.
void XHdcp1x_EnableBlank(XHdcp1x *InstancePtr)
This function enables the blank output for the cipher.
InstancePtr is a pointer to the XHdcp14 core instance. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_TxEnableBlank.
u8 * XHdcp1x_GetTopologyKSVList(XHdcp1x *InstancePtr)
This function returns the value of KSV List read in the downstream interface of the repeater topology.
InstancePtr is a pointer to the XHdcp14 core instance. List of KSVs of the downstream devices None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_TxGetTopologyKSVList.
u8 * XHdcp1x_GetTopologyBKSV(XHdcp1x *InstancePtr)
This function returns the value of KSV of the device attached to the downstream interface of the repeater.
InstancePtr is a pointer to the XHdcp14 core instance. TRUE if MAX_DEPTH_EXCEEDED None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_TxGetTopologyBKSV.
void XHdcp1x_SetTopologyField(XHdcp1x *InstancePtr, XHdcp1x_TopologyField Field, u8 Value)
This function is used to set various fields inside the topology structure.
InstancePtr is a pointer to the XHdcp1x core instance. Field indicates what field of the topology structure to update. Value is the value assigned to the field of the topology structure. None.
References XHdcp1x_RxSetTopologyDepth, XHdcp1x_RxSetTopologyDeviceCnt, XHdcp1x_RxSetTopologyMaxCascadeExceeded, XHdcp1x_RxSetTopologyMaxDevsExceeded.
u32 XHdcp1x_GetTopologyField(XHdcp1x *InstancePtr, XHdcp1x_TopologyField Field)
This function is used to get various fields inside the topology structure.
InstancePtr is a pointer to the XHdcp1x core instance. Field indicates what field of the topology structure to update. None. None.
References XHdcp1x_TxGetTopologyDepth, XHdcp1x_TxGetTopologyDeviceCnt, XHdcp1x_TxGetTopologyMaxCascadeExceeded, XHdcp1x_TxGetTopologyMaxDevsExceeded.
int XHdcp1x_IsRepeater(XHdcp1x *InstancePtr)
This function return if the HDCP interface is a repeater in case of Rx or is connected to a repeater in case of Tx.
InstancePtr is the transmitter instance. TRUE if Repeater.FALSE if not Repeater, None.
References XHdcp1x::Config, XHdcp1x::IsRepeater, XHdcp1x_Config::IsRx, XHDCP1X_DEBUG_PRINTF, XHdcp1x_TxIsRepeater.
void XHdcp1x_SetTopology(XHdcp1x *InstancePtr, const XHdcp1x_RepeaterExchange *TopologyPtr)
This function sets the RepeaterInfo value int the HDCP RX instance.
InstancePtr is a pointer to the Hdcp1x core instance. TopologyPtr is a pointer to the Repeater Info value(s). None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_RxSetTopology.
void XHdcp1x_SetTopologyKSVList(XHdcp1x *InstancePtr, u8 *ListPtr, u32 ListSize)
This function sets the KSVList value(s) in the HDCP RX KSV Fifo register space for the upstream interface to read.
InstancePtr is a pointer to the Hdcp1x core instance. ListPtr is a pointer to the KSV list. ListSize is the number of KSVs in the list. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, UNUSED, XHdcp1x_RxSetTopologyKSVList.
void XHdcp1x_SetTopologyUpdate(XHdcp1x *InstancePtr)
This function does the necessary actions to update HDCP after the topology has been set.
InstancePtr is a pointer to the Hdcp1x core instance. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHDCP1X_DEBUG_PRINTF, XHdcp1x_RxSetTopologyUpdate.
void XHdcp1x_SetHdmiMode(XHdcp1x *InstancePtr, u8 Value)
This function set the HDMI_MODE in the BStatus register of the HDMI DDC space.
InstancePtr is a pointer to the Hdcp1x core instance. Value is the truth-value. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHDCP1X_DEBUG_PRINTF, XHdcp1x_RxSetHdmiMode, XHdcp1x_TxSetHdmiMode.
XHdcp1x_Config * XHdcp1x_LookupConfig(UINTPTR BaseAddress)
This function returns a reference to an XHdcp1x_Config structure based on specified device ID.
DeviceId is the unique core ID of the HDCP interface. A reference to the config record in the configuration table (in xhdcp_g.c) corresponding the specified DeviceId. NULL if no match is found. None.
int XHdcp1x_SelfTest(XHdcp1x *InstancePtr)
This function self tests an HDCP interface.
InstancePtr is the interface to test. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHdcp1x_Config::IsHDMI, XHdcp1x_Config::IsRx, XHDCP1X_CIPHER_REG_VERSION, XHdcp1x_IsDP, XHdcp1x_IsHDMI, XHdcp1x_IsRX, XHdcp1x_IsTX, XHdcp1x_ReadReg.
int XHdcp1x_SetCallback(XHdcp1x *InstancePtr, XHdcp1x_HandlerType HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs callback functions for the given HandlerType.
InstancePtr is a pointer to the HDCP core instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_RxSetCallback, XHdcp1x_TxSetCallback.
void XHdcp1x_CipherIntrHandler(void *InstancePtr)
This function is the cipher interrupt handler for the HDCP module.
InstancePtr is the device instance that just interrupted. This function just forwards the interrupt along to the corresponding cipher core.
References XHdcp1x::IsReady, XHdcp1x_CipherHandleInterrupt.
void XHdcp1x_PortIntrHandler(void *InstancePtr, u32 IntCause)
This function is the port interrupt handler for the HDCP module.
InstancePtr is the device instance that just interrupted. IntCause is the interrupt cause bit map. This function just forwards the interrupt along to the corresponding cipher core.
References XHdcp1x::IsReady, XHdcp1x_PortHandleInterrupt.
void XHdcp1x_CipherInit(XHdcp1x *InstancePtr)
This function initializes an HDCP cipher.
InstancePtr is the device to initialize. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_CONTROL_NUM_LANES, XHDCP1X_CIPHER_BITMASK_CONTROL_RESET, XHDCP1X_CIPHER_BITMASK_CONTROL_UPDATE, XHDCP1X_CIPHER_REG_CONTROL, XHDCP1X_CIPHER_REG_INTERRUPT_MASK, XHDCP1X_CIPHER_REG_INTERRUPT_STATUS, XHdcp1x_IsDP, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
Referenced by XHdcp1x_CfgInitialize.
int XHdcp1x_CipherIsLinkUp(const XHdcp1x *InstancePtr)
This function queries the link state of a cipher device.
InstancePtr is the device to query. Truth value. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_INTERRUPT_LINK_FAIL, XHDCP1X_CIPHER_REG_STATUS, XHdcp1x_CipherIsEnabled, XHdcp1x_ReadReg.
int XHdcp1x_CipherEnable(XHdcp1x *InstancePtr)
This function enables a HDCP cipher.
InstancePtr is the device to enable. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_CIPHER_CONTROL_XOR_ENABLE, XHDCP1X_CIPHER_BITMASK_CONTROL_ENABLE, XHDCP1X_CIPHER_BITMASK_CONTROL_UPDATE, XHDCP1X_CIPHER_REG_CIPHER_CONTROL, XHDCP1X_CIPHER_REG_CONTROL, XHDCP1X_CIPHER_REG_ENCRYPT_ENABLE_H, XHDCP1X_CIPHER_REG_ENCRYPT_ENABLE_L, XHdcp1x_CipherIsEnabled, XHdcp1x_IsRX, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
int XHdcp1x_CipherDisable(XHdcp1x *InstancePtr)
This function disables a HDCP cipher.
InstancePtr is the device to disable. XST_SUCCESS if successful. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_CIPHER_CONTROL_XOR_ENABLE, XHDCP1X_CIPHER_BITMASK_CONTROL_ENABLE, XHDCP1X_CIPHER_BITMASK_CONTROL_UPDATE, XHDCP1X_CIPHER_REG_CIPHER_CONTROL, XHDCP1X_CIPHER_REG_CONTROL, XHDCP1X_CIPHER_REG_ENCRYPT_ENABLE_H, XHDCP1X_CIPHER_REG_ENCRYPT_ENABLE_L, XHDCP1X_CIPHER_REG_INTERRUPT_MASK, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
int XHdcp1x_CipherSetKeySelect(XHdcp1x *InstancePtr, u8 KeySelect)
This function configures the key selection value.
InstancePtr is the device to configure. KeySelect is the desired key select value. XST_SUCCESS if successful. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_KEYMGMT_CONTROL_SET_SELECT, XHDCP1X_CIPHER_REG_KEYMGMT_CONTROL, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
Referenced by XHdcp1x_SetKeySelect.
int XHdcp1x_CipherDoRequest(XHdcp1x *InstancePtr, XHdcp1x_CipherRequestType Request)
This function initiates a request within the HDCP cipher.
InstancePtr is the device to submit the request to. Request is the request to submit. XST_SUCCESS if successful.XST_NOT_ENABLE if the core is disabled.XST_DEVICE_BUSY if the core is busy. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_CIPHER_CONTROL_REQUEST, XHDCP1X_CIPHER_BITMASK_CIPHER_STATUS_REQUEST_IN_PROG, XHDCP1X_CIPHER_BITMASK_CONTROL_UPDATE, XHDCP1X_CIPHER_REG_CIPHER_CONTROL, XHDCP1X_CIPHER_REG_CIPHER_STATUS, XHDCP1X_CIPHER_REG_CONTROL, XHDCP1X_CIPHER_VALUE_CIPHER_CONTROL_REQUEST_BLOCK, XHdcp1x_CipherIsEnabled, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
int XHdcp1x_CipherIsRequestComplete(const XHdcp1x *InstancePtr)
This function queries the progress of the current request.
InstancePtr is the device to query. Truth value. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_CIPHER_STATUS_REQUEST_IN_PROG, XHDCP1X_CIPHER_REG_CIPHER_STATUS, XHdcp1x_ReadReg.
u32 XHdcp1x_CipherGetNumLanes(const XHdcp1x *InstancePtr)
This function retrieves the current number of lanes of the HDCP cipher.
InstancePtr is the device to query. The current number of lanes. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_CONTROL_NUM_LANES, XHDCP1X_CIPHER_REG_CONTROL, XHdcp1x_CipherIsEnabled, XHdcp1x_ReadReg.
int XHdcp1x_CipherSetNumLanes(XHdcp1x *InstancePtr, u32 NumLanes)
This function configures the number of lanes of the HDCP cipher.
InstancePtr is the device to configure. NumLanes is the number of lanes to configure. XST_SUCCESS if successful. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_CONTROL_NUM_LANES, XHDCP1X_CIPHER_REG_CONTROL, XHdcp1x_IsHDMI, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
Referenced by XHdcp1x_RxSetLaneCount, XHdcp1x_TxSetLaneCount.
int XHdcp1x_CipherSetMode(XHdcp1x *InstancePtr, u32 mode)
This function configures the Mode of the HDCP cipher to MST/ SST.
InstancePtr is the device to configure. mode determines MST/ SST configuration. XST_SUCCESS if successful. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_MODE, XHDCP1X_CIPHER_REG_CONTROL, XHdcp1x_IsHDMI, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
Referenced by XHdcp1x_TxSetMSTMode.
u64 XHdcp1x_CipherGetEncryption(const XHdcp1x *InstancePtr)
This function retrieves the current encryption stream map.
InstancePtr is the device to query. The current encryption stream map. In the case of the receiver version of this core, the XOR in progress bit needs to be checked as well as the encryption map to fully determine if encryption is enabled for the SST case. This is the reason for the additional check in this code.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_REG_ENCRYPT_ENABLE_H, XHDCP1X_CIPHER_REG_ENCRYPT_ENABLE_L, XHdcp1x_CipherIsEnabled, XHdcp1x_CipherXorInProgress, XHdcp1x_ReadReg.
Referenced by XHdcp1x_RxGetEncryption.
int XHdcp1x_CipherEnableEncryption(XHdcp1x *InstancePtr, u64 StreamMap)
This function enables encryption on a set of streams.
InstancePtr is the device to configure. StreamMap is the bit map of streams to enable encryption on. XST_SUCCESS if successful.XST_NOT_ENABLE if the core is not enabled.XST_FAILURE otherwise. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_CIPHER_CONTROL_XOR_ENABLE, XHDCP1X_CIPHER_BITMASK_CONTROL_UPDATE, XHDCP1X_CIPHER_REG_CIPHER_CONTROL, XHDCP1X_CIPHER_REG_CONTROL, XHDCP1X_CIPHER_REG_ENCRYPT_ENABLE_H, XHDCP1X_CIPHER_REG_ENCRYPT_ENABLE_L, XHdcp1x_CipherIsEnabled, XHdcp1x_CipherXorInProgress, XHdcp1x_IsRX, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
int XHdcp1x_CipherDisableEncryption(XHdcp1x *InstancePtr, u64 StreamMap)
This function disables encryption on a set of streams.
InstancePtr is the device to configure. StreamMap is the bit map of streams to disable encryption on. XST_SUCCESS if successful.XST_NOT_ENABLE if the core is not enabled.XST_FAILURE otherwise. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_CIPHER_CONTROL_XOR_ENABLE, XHDCP1X_CIPHER_BITMASK_CONTROL_UPDATE, XHDCP1X_CIPHER_REG_CIPHER_CONTROL, XHDCP1X_CIPHER_REG_CONTROL, XHDCP1X_CIPHER_REG_ENCRYPT_ENABLE_H, XHDCP1X_CIPHER_REG_ENCRYPT_ENABLE_L, XHdcp1x_CipherIsEnabled, XHdcp1x_IsHDMI, XHdcp1x_IsRX, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
Referenced by XHdcp1x_TxDisableEncryption.
u64 XHdcp1x_CipherGetLocalKsv(const XHdcp1x *InstancePtr)
This function reads the local KSV value from the cipher.
InstancePtr is the device to query. The local KSV value. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_KEYMGMT_CONTROL_ABORT_Km, XHDCP1X_CIPHER_BITMASK_KEYMGMT_CONTROL_LOCAL_KSV, XHDCP1X_CIPHER_BITMASK_KEYMGMT_STATUS_KSV_READY, XHDCP1X_CIPHER_REG_KEYMGMT_CONTROL, XHDCP1X_CIPHER_REG_KEYMGMT_STATUS, XHDCP1X_CIPHER_REG_KSV_LOCAL_H, XHDCP1X_CIPHER_REG_KSV_LOCAL_L, XHdcp1x_CipherIsEnabled, XHdcp1x_CipherLocalKsvReady, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
Referenced by XHdcp1x_CipherSetRemoteKsv, XHdcp1x_RxInfo, XHdcp1x_TxInfo.
u64 XHdcp1x_CipherGetRemoteKsv(const XHdcp1x *InstancePtr)
This function reads the remote KSV value from the cipher.
InstancePtr is the device to query. The remote KSV value. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_REG_KSV_REMOTE_H, XHDCP1X_CIPHER_REG_KSV_REMOTE_L, XHdcp1x_ReadReg.
int XHdcp1x_CipherSetRemoteKsv(XHdcp1x *InstancePtr, u64 Ksv)
This function writes the remote KSV value to the cipher.
InstancePtr is the device to write to. Ksv is the remote KSV value to write. XST_SUCCESS if successful.XST_NOT_ENABLED otherwise. Whenever this function is called, the underlying driver will initiate the calculation of the Km value and wait for it to complete.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_CONTROL_UPDATE, XHDCP1X_CIPHER_BITMASK_KEYMGMT_CONTROL_BEGIN_Km, XHDCP1X_CIPHER_REG_CONTROL, XHDCP1X_CIPHER_REG_KEYMGMT_CONTROL, XHDCP1X_CIPHER_REG_KSV_REMOTE_H, XHDCP1X_CIPHER_REG_KSV_REMOTE_L, XHdcp1x_CipherGetLocalKsv, XHdcp1x_CipherIsEnabled, XHdcp1x_CipherKmReady, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
int XHdcp1x_CipherGetB(const XHdcp1x *InstancePtr, u32 *X, u32 *Y, u32 *Z)
This function reads the contents of the B register in BM0.
InstancePtr is the device to query. X is to be loaded with the contents of Bx. Y is to be loaded with the contents of By. Z is to be loaded with the contents of Bz. XST_SUCCESS if successful.XST_NOT_ENABLED otherwise. A NULL pointer can be passed in any of X, Y and Z. If so, then this portion of the B register is not returned to the caller.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_REG_CIPHER_Bx, XHDCP1X_CIPHER_REG_CIPHER_By, XHDCP1X_CIPHER_REG_CIPHER_Bz, XHdcp1x_CipherIsEnabled, XHdcp1x_ReadReg.
int XHdcp1x_CipherSetB(XHdcp1x *InstancePtr, u32 X, u32 Y, u32 Z)
This function writes the contents of the B register in BM0.
InstancePtr is the device to write to. X is the value to be written to Bx. Y is the value to be written to By. Z is the value to be written to Bz. XST_SUCCESS if successful.XST_NOT_ENABLED otherwise. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_CONTROL_UPDATE, XHDCP1X_CIPHER_REG_CIPHER_Bx, XHDCP1X_CIPHER_REG_CIPHER_By, XHDCP1X_CIPHER_REG_CIPHER_Bz, XHDCP1X_CIPHER_REG_CONTROL, XHdcp1x_CipherIsEnabled, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
int XHdcp1x_CipherGetK(const XHdcp1x *InstancePtr, u32 *X, u32 *Y, u32 *Z)
This function reads the contents of the K register in BM0.
InstancePtr is the device to query. X is to be loaded with the contents of Kx. Y is to be loaded with the contents of Ky. Z is to be loaded with the contents of Kz. XST_SUCCESS if successful.XST_NOT_ENABLED otherwise. A NULL pointer can be passed in any of X, Y and Z. If so, then this portion of the K register is not returned to the caller.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_REG_CIPHER_Kx, XHDCP1X_CIPHER_REG_CIPHER_Ky, XHDCP1X_CIPHER_REG_CIPHER_Kz, XHdcp1x_CipherIsEnabled, XHdcp1x_ReadReg.
int XHdcp1x_CipherSetK(XHdcp1x *InstancePtr, u32 X, u32 Y, u32 Z)
This function writes the contents of the K register in BM0.
InstancePtr is the device to write to. X is the value to be written to Kx. Y is the value to be written to Ky. Z is the value to be written to Kz. XST_SUCCESS if successful.XST_NOT_ENABLED otherwise. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_CONTROL_UPDATE, XHDCP1X_CIPHER_REG_CIPHER_Kx, XHDCP1X_CIPHER_REG_CIPHER_Ky, XHDCP1X_CIPHER_REG_CIPHER_Kz, XHDCP1X_CIPHER_REG_CONTROL, XHdcp1x_CipherIsEnabled, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
u64 XHdcp1x_CipherGetMi(const XHdcp1x *InstancePtr)
This function reads the contents of the Mi/An register of BM0.
InstancePtr is the device to query. The contents of the register. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_REG_CIPHER_Mi_H, XHDCP1X_CIPHER_REG_CIPHER_Mi_L, XHdcp1x_CipherIsEnabled, XHdcp1x_ReadReg.
u16 XHdcp1x_CipherGetRi(const XHdcp1x *InstancePtr)
This function reads the contents of the Ri register of BM0.
InstancePtr is the device to query. The contents of the register. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_REG_CIPHER_Ri, XHdcp1x_CipherIsEnabled, XHdcp1x_ReadReg.
u64 XHdcp1x_CipherGetMo(const XHdcp1x *InstancePtr)
This function reads the contents of the Mo register of the device.
InstancePtr is the device to query. The contents of the Mo register. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_REG_CIPHER_Mo_H, XHDCP1X_CIPHER_REG_CIPHER_Mo_L, XHdcp1x_CipherIsEnabled, XHdcp1x_ReadReg.
u16 XHdcp1x_CipherGetRo(const XHdcp1x *InstancePtr)
This function reads the contents of the Ro register of the device.
InstancePtr is the device to query. The contents of the Ro register. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_REG_CIPHER_Ro, XHdcp1x_CipherIsEnabled, XHdcp1x_ReadReg.
u32 XHdcp1x_CipherGetVersion(const XHdcp1x *InstancePtr)
This function reads the version of the HDCP cipher core.
InstancePtr is the device to query. The version of the HDCP cipher device. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_REG_VERSION, XHdcp1x_ReadReg.
Referenced by XHdcp1x_GetVersion, XHdcp1x_RxInfo, XHdcp1x_TxInfo.
void XHdcp1x_CipherEnableBlank(XHdcp1x *InstancePtr)
This function sets the cipher blank value to 0x0000FF (blue), and sets the cipher blank select to TRUE.
InstancePtr is the device to query. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_BLANK_SEL, XHDCP1X_CIPHER_BITMASK_BLANK_VALUE, XHDCP1X_CIPHER_REG_BLANK_SEL, XHDCP1X_CIPHER_REG_BLANK_VALUE, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
Referenced by XHdcp1x_TxEnableBlank.
void XHdcp1x_CipherDisableBlank(XHdcp1x *InstancePtr)
This function sets the cipher blank select to FALSE.
InstancePtr is the device to query. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_BLANK_SEL, XHDCP1X_CIPHER_REG_BLANK_SEL, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
Referenced by XHdcp1x_TxDisableBlank.
int XHdcp1x_CipherSetCallback(XHdcp1x *InstancePtr, u32 HandlerType, XHdcp1x_Callback CallbackFunc, void *CallbackRef)
This function installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function Type ----------------------------------- ----------------------------------- (XHDCP1X_CIPHER_HANDLER_LINK_FAILURE) LinkFailCallback (XHDCP1X_CIPHER_HANDLER_Ri_UPDATE) RiUpdateCallback InstancePtr is a pointer to the HDCP cipher core instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XHdcp1x::Cipher, XHdcp1x_Cipher::IsLinkFailCallbackSet, XHdcp1x_Cipher::IsRiUpdateCallbackSet, XHdcp1x_Cipher::LinkFailCallback, XHdcp1x_Cipher::LinkFailRef, XHdcp1x_Cipher::RiUpdateCallback, XHdcp1x_Cipher::RiUpdateRef.
int XHdcp1x_CipherSetLinkStateCheck(XHdcp1x *InstancePtr, int IsEnabled)
This function enables/disables the reporting of link check state changes.
InstancePtr is the cipher core instance. IsEnabled enables/disables link state change notifications. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_INTERRUPT_LINK_FAIL, XHDCP1X_CIPHER_REG_INTERRUPT_MASK, XHDCP1X_CIPHER_REG_INTERRUPT_STATUS, XHdcp1x_IsDP, XHdcp1x_IsRX, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
int XHdcp1x_CipherSetRiUpdate(XHdcp1x *InstancePtr, int IsEnabled)
This function enables/disables the reporting of Ri update notifications.
InstancePtr is the cipher core instance. IsEnabled enables/disables Ri update notifications. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_INTERRUPT_Ri_UPDATE, XHDCP1X_CIPHER_REG_INTERRUPT_MASK, XHDCP1X_CIPHER_REG_INTERRUPT_STATUS, XHdcp1x_IsHDMI, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
void XHdcp1x_CipherHandleInterrupt(void *InstancePtr)
This function is the interrupt handler for the cipher core driver.
InstancePtr is the cipher core instance. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Cipher, XHdcp1x::Config, XHdcp1x_CipherStats::IntCount, XHdcp1x_Cipher::IsLinkFailCallbackSet, XHdcp1x::IsReady, XHdcp1x_Cipher::IsRiUpdateCallbackSet, XHdcp1x_Cipher::LinkFailCallback, XHdcp1x_Cipher::LinkFailRef, XHdcp1x_Cipher::RiUpdateCallback, XHdcp1x_Cipher::RiUpdateRef, XHdcp1x_Cipher::Stats, XHDCP1X_CIPHER_BITMASK_INTERRUPT_LINK_FAIL, XHDCP1X_CIPHER_BITMASK_INTERRUPT_Ri_UPDATE, XHDCP1X_CIPHER_REG_INTERRUPT_STATUS, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
Referenced by XHdcp1x_CipherIntrHandler.
int XHdcp1x_PlatformIsKsvRevoked(const XHdcp1x *InstancePtr, u64 Ksv)
This function checks a KSV value to determine if it has been revoked or not.
InstancePtr is the HDCP interface. Ksv is the KSV to check. Truth value indicating the KSV is revoked (TRUE) or not (FALSE) None.
References XHdcp1xKsvRevokeCheck.
int XHdcp1x_PlatformTimerStart(XHdcp1x *InstancePtr, u16 TimeoutInMs)
This function starts a timer on behalf of an HDCP interface.
InstancePtr is the hdcp interface. TimeoutInMs is the duration of the timer in milliseconds. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x::XHdcp1xTimerStart.
int XHdcp1x_PlatformTimerStop(XHdcp1x *InstancePtr)
This function stop a timer on behalf of an HDCP interface.
InstancePtr is the HDCP interface. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x::XHdcp1xTimerStop.
int XHdcp1x_PlatformTimerBusy(XHdcp1x *InstancePtr, u16 DelayInMs)
This function busy waits on a timer for a number of milliseconds.
InstancePtr is the hdcp interface. DelayInMs is the delay time in milliseconds. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x::XHdcp1xTimerDelay.
const XHdcp1x_PortPhyIfAdaptor * XHdcp1x_PortDetermineAdaptor(XHdcp1x *InstancePtr)
This function determines the adaptor for a specified port device.
InstancePtr is the device whose adaptor is to be determined. A pointer to the adaptor table. NULL if not found. None.
References XHdcp1x::Config, XHdcp1x_Config::IsHDMI, XHdcp1x_Config::IsRx.
Referenced by XHdcp1x_CfgInitialize.
int XHdcp1x_PortEnable(XHdcp1x *InstancePtr)
This function enables a port device.
InstancePtr is the device to enables. XST_SUCCESS if successful.XST_NO_FEATURE if the port lacks an Enable function. None.
References XHdcp1x_PortStruct::Adaptor, XHdcp1x_PortPhyIfAdaptorS::Enable, XHdcp1x::Port.
int XHdcp1x_SetEcfSlots(XHdcp1x *InstancePtr, u64 timeslots)
This function enables encryption/decyption for all timeslots.
InstancePtr is the device to enables. timeslots is the timeslot configuration value. XST_SUCCESS if successful.XST_NO_FEATURE if the port lacks an Enable function. None.
References XHdcp1x_PortStruct::Adaptor, XHdcp1x::Port, XHdcp1x_PortPhyIfAdaptorS::SetEcfSlots.
Referenced by XHdcp1x_TxEnableEcf, XHdcp1x_TxEnableEcfTimeslots.
int XHdcp1x_PortDisable(XHdcp1x *InstancePtr)
This function disables a port device.
InstancePtr is the device to disables. XST_SUCCESS if successful.XST_NO_FEATURE if the port lacks a Disable function. None.
References XHdcp1x_PortStruct::Adaptor, XHdcp1x_PortPhyIfAdaptorS::Disable, XHdcp1x::Port.
int XHdcp1x_PortIsCapable(const XHdcp1x *InstancePtr)
This function queries a port device to determine if hdcp is supported.
InstancePtr is the device to query. Truth value. None.
References XHdcp1x_PortStruct::Adaptor, XHdcp1x_PortPhyIfAdaptorS::IsCapable, XHdcp1x::Port.
Referenced by XHdcp1x_TxIsDownstrmCapable.
int XHdcp1x_PortIsRepeater(const XHdcp1x *InstancePtr)
This function queries a port device to determine if it is connected to a repeater.
InstancePtr is the device to query. Truth value. None.
References XHdcp1x_PortStruct::Adaptor, XHdcp1x_PortPhyIfAdaptorS::IsRepeater, XHdcp1x::Port.
Referenced by XHdcp1x_TxIsRepeater.
int XHdcp1x_PortSetRepeater(XHdcp1x *InstancePtr, u8 RptrConf)
This function set the REPEATER information in the connected device.
InstancePtr is the device to query. RptrConf is the configuration of the device as repeater. XST_SUCCESS if successful.XST_NO_FEATURE if the port fails to set the Repeater value. None.
References XHdcp1x_PortStruct::Adaptor, XHdcp1x::Port, XHdcp1x_PortPhyIfAdaptorS::SetRepeater.
Referenced by XHdcp1x_RxSetRepeaterBcaps.
int XHdcp1x_PortGetRepeaterInfo(XHdcp1x *InstancePtr, u16 *InfoPtr)
This function retrieves the repeater information from the connected device.
InstancePtr is the device to query. InfoPtr is the repeater info. XST_SUCCESS if successful.XST_NO_FEATURE if the port lacks a GetRepeaterInfo function. None.
References XHdcp1x_PortStruct::Adaptor, XHdcp1x_PortPhyIfAdaptorS::GetRepeaterInfo, XHdcp1x::Port.
int XHdcp1x_PortRead(const XHdcp1x *InstancePtr, u8 Offset, void *Buf, u32 BufSize)
This function reads a register from a HDCP port device.
InstancePtr is the device to read from. Offset is the offset to start reading from. Buf is the buffer to copy the data read. BufSize is the size of the buffer. The number of bytes read. None.
References XHdcp1x_PortStruct::Adaptor, XHdcp1x::Port, XHdcp1x_PortPhyIfAdaptorS::Read.
Referenced by XHdcp1x_RxSetHdmiMode, XHdcp1x_RxSetTopologyMaxCascadeExceeded, XHdcp1x_RxSetTopologyMaxDevsExceeded, XHdcp1x_TxGetTopologyBKSV, XHdcp1x_TxGetTopologyMaxCascadeExceeded, XHdcp1x_TxGetTopologyMaxDevsExceeded.
int XHdcp1x_PortWrite(XHdcp1x *InstancePtr, u8 Offset, const void *Buf, u32 BufSize)
This function writes a register within a HDCP port device.
InstancePtr is the device to write to. Offset is the offset to start writing at. Buf is the buffer containing the data to write. BufSize is the size of the buffer. The number of bytes written. None.
References XHdcp1x_PortStruct::Adaptor, XHdcp1x::Port, XHdcp1x_PortPhyIfAdaptorS::Write.
Referenced by XHdcp1x_RxSetHdmiMode, XHdcp1x_RxSetTopologyMaxCascadeExceeded, XHdcp1x_RxSetTopologyMaxDevsExceeded.
int XHdcp1x_PortSetCallback(XHdcp1x *InstancePtr, u32 HandlerType, XHdcp1x_Callback CallbackFunc, void *CallbackRef)
This function installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function Type ------------------------------------ ------------------------------------- (XHDCP1X_PORT_HANDLER_AUTHENTICATE) AuthCallback InstancePtr is a pointer to the HDCP port instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XHdcp1x_PortStruct::AuthCallback, XHdcp1x_PortStruct::AuthRef, XHdcp1x_PortStruct::IsAuthCallbackSet, XHdcp1x::Port, XHDCP1X_PORT_HANDLER_AUTHENTICATE.
void XHdcp1x_PortHandleInterrupt(XHdcp1x *InstancePtr, u32 IntCause)
This handles an interrupt generated by a HDCP port device.
InstancePtr is the device to write to. IntCause is the interrupt cause bit map. None.
References XHdcp1x_PortStruct::Adaptor, XHdcp1x_PortStats::IntCount, XHdcp1x_PortPhyIfAdaptorS::IntrHandler, XHdcp1x::Port, XHdcp1x_PortStruct::Stats.
Referenced by XHdcp1x_PortIntrHandler.
static void XHdcp1x_RxDebugLog(const XHdcp1x *InstancePtr, const char *LogMsg)
This function logs a debug message on behalf of a handler state machine.
InstancePtr is the receiver instance. LogMsg is the message to log. None. None.
static void XHdcp1x_RxPostEvent(XHdcp1x *InstancePtr, XHdcp1x_EventType Event)
This function posts an event to a state machine.
InstancePtr is the receiver instance. Event is the event to post. None. None.
static void XHdcp1x_RxStartTimer(XHdcp1x *InstancePtr, u16 TimeoutInMs)
This function starts a state machine's timer.
InstancePtr is the state machine. TimeoutInMs is the timeout in milli-seconds. None. None.
static void XHdcp1x_RxStopTimer(XHdcp1x *InstancePtr)
This function stops a state machine's timer.
InstancePtr is the state machine. None. None.
static void XHdcp1x_RxAuthCallback(void *Parameter)
This function acts as the re-authentication callback for a state machine.
Parameter is the parameter specified during registration. None. None.
static void XHdcp1x_RxLinkFailCallback(void *Parameter)
This function acts as the link failure callback for a state machine.
Parameter is the parameter specified during registration. None. None.
static void XHdcp1x_RxRiUpdateCallback(void *Parameter)
This function acts as the Ri register update callback for a state machine.
Parameter is the parameter specified during registration. None. None.
static void XHdcp1x_RxSetCheckLinkState(XHdcp1x *InstancePtr, int IsEnabled)
This function sets the check link state of the handler.
InstancePtr is the receiver instance. IsEnabled is truth value indicating on/off. None. None.
static void XHdcp1x_RxEnableState(XHdcp1x *InstancePtr)
This function enables a receiver state machine.
InstancePtr is the receiver instance. None. None.
static void XHdcp1x_RxDisableState(XHdcp1x *InstancePtr)
This function disables a receiver state machine.
InstancePtr is the receiver instance. None. None.
static void XHdcp1x_RxStartComputations(XHdcp1x *InstancePtr, XHdcp1x_StateType *NextStatePtr)
This function initiates the computations for a receiver state machine.
InstancePtr is the receiver instance. NextStatePtr is the next state. None. None.
static void XHdcp1x_RxPollForComputations(XHdcp1x *InstancePtr, XHdcp1x_StateType *NextStatePtr)
This function polls the progress of the computations for a state machine.
InstancePtr is the receiver instance. NextStatePtr is the next state. None. None.
static int XHdcp1x_RxCalculateSHA1Value(XHdcp1x *InstancePtr, u16 RepeaterInfo)
This function calculates the SHA-1 Hash value for the Repeater Rx interface.
InstancePtr is the hdcp state machine. RepeaterInfo is the repeater information. Truth value indicating valid (TRUE) or invalid (FALSE). None.
static void XHdcp1x_RxAssembleKSVList(XHdcp1x *InstancePtr, XHdcp1x_StateType *NextStatePtr)
This function writes the KSV List and the BInfo values to the RX DPCD register space and sets the READY bit.
InstancePtr is the receiver instance. NextStatePtr is the next state. None.
static void XHdcp1x_RxUpdateRi(XHdcp1x *InstancePtr)
This function updates the Ro'/Ri' register of the state machine.
InstancePtr is the receiver instance. NextStatePtr is the next state. This function has to save the value of Ri (in RememberRi) as the macro that converts from a uint16 to a HDCP buffer destroys the original value.
static void XHdcp1x_RxCheckLinkIntegrity(XHdcp1x *InstancePtr, XHdcp1x_StateType *NextStatePtr)
This functions handles check the integrity of the link.
InstancePtr is the receiver instance. NextStatePtr is the next state. None.
static void XHdcp1x_RxReportLinkIntegrityFailure(XHdcp1x *InstancePtr, XHdcp1x_StateType *NextStatePtr)
This functions reports the failure of link integrity.
InstancePtr is the receiver instance. NextStatePtr is the next state. None.
static void XHdcp1x_RxRunDisabledState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event, XHdcp1x_StateType *NextStatePtr)
This function runs the "disabled" state of the receiver state machine.
InstancePtr is the receiver instance. Event is the event to process. NextStatePtr is the next state. None.
static void XHdcp1x_RxRunUnauthenticatedState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event, XHdcp1x_StateType *NextStatePtr)
This function runs the "unauthenticated" state of the receiver state machine.
InstancePtr is the receiver instance. Event is the event to process. NextStatePtr is the next state. None.
static void XHdcp1x_RxRunComputationsState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event, XHdcp1x_StateType *NextStatePtr)
This function runs the "computations" state of the receiver state machine.
InstancePtr is the receiver instance. Event is the event to process. NextStatePtr is the next state. None.
static void XHdcp1x_RxRunAuthenticatedState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event, XHdcp1x_StateType *NextStatePtr)
This function runs the "authenticated" state of the receiver state machine.
InstancePtr is the receiver instance. Event is the event to process. NextStatePtr is the next state. None.
static void XHdcp1x_RxRunLinkIntegrityFailedState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event, XHdcp1x_StateType *NextStatePtr)
This function runs the "link integrity failed" state of the receiver state machine.
InstancePtr is the receiver instance. Event is the event to process. NextStatePtr is the next state. None.
static void XHdcp1x_RxRunPhysicalLayerDownState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event, XHdcp1x_StateType *NextStatePtr)
This function runs the "physical layer down" state of the receiver state machine.
InstancePtr is the receiver instance. Event is the event to process. NextStatePtr is the next state. None.
static void XHdcp1x_RxEnterState(XHdcp1x *InstancePtr, XHdcp1x_StateType State, XHdcp1x_StateType *NextStatePtr)
This function enters a HDCP receiver state.
InstancePtr is the receiver instance. State is the state to enter. NextStatePtr is the next state. None.
static void XHdcp1x_RxExitState(XHdcp1x *InstancePtr, XHdcp1x_StateType State)
This function exits a HDCP receiver state.
InstancePtr is the receiver instance. State is the state to exit. None.
static void XHdcp1x_RxDoTheState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event)
This function drives a HDCP receiver state machine.
InstancePtr is the receiver instance. Event is the event to process. None. None.
static void XHdcp1x_RxProcessPending(XHdcp1x *InstancePtr)
This function processes the events pending on a state machine.
InstancePtr is the receiver instance. None. None.
static const char * XHdcp1x_RxStateToString(XHdcp1x_StateType State)
This function converts from a state to a display string.
State is the state to convert. The corresponding display string. None.
int XHdcp1x_RxSetCallback(XHdcp1x *InstancePtr, XHdcp1x_HandlerType HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs callback functions for the given HandlerType:
InstancePtr is a pointer to the HDCP core instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XHdcp1x_Rx::AuthenticatedCallback, XHdcp1x_Rx::AuthenticatedCallbackRef, XHdcp1x_Rx::DdcGetDataCallback, XHdcp1x_Rx::DdcGetDataCallbackRef, XHdcp1x_Rx::DdcSetAddressCallback, XHdcp1x_Rx::DdcSetAddressCallbackRef, XHdcp1x_Rx::DdcSetDataCallback, XHdcp1x_Rx::DdcSetDataCallbackRef, XHdcp1x_Rx::EncryptionUpdateCallback, XHdcp1x_Rx::EncryptionUpdateCallbackRef, XHdcp1x_Rx::IsAuthenticatedCallbackSet, XHdcp1x_Rx::IsDdcGetDataCallbackSet, XHdcp1x_Rx::IsDdcSetAddressCallbackSet, XHdcp1x_Rx::IsDdcSetDataCallbackSet, XHdcp1x_Rx::IsEncryptionUpdateCallbackSet, XHdcp1x_Rx::IsRepeaterDownstreamAuthCallbackSet, XHdcp1x_Rx::IsTopologyUpdateCallbackSet, XHdcp1x_Rx::IsUnauthenticatedCallbackSet, XHdcp1x_Rx::RepeaterDownstreamAuthCallback, XHdcp1x_Rx::RepeaterDownstreamAuthRef, XHdcp1x::Rx, XHdcp1x_Rx::TopologyUpdateCallback, XHdcp1x_Rx::TopologyUpdateCallbackRef, XHdcp1x_Rx::UnauthenticatedCallback, XHdcp1x_Rx::UnauthenticatedCallbackRef.
Referenced by XHdcp1x_SetCallback.
void XHdcp1x_RxLoadBksvToBuf(XHdcp1x *InstancePtr)
void XHdcp1x_RxInit(XHdcp1x *InstancePtr)
This function initializes a HDCP receiver state machine.
InstancePtr is the receiver instance. None.
References XHdcp1x_Rx::PendingEvents, XHdcp1x::Rx.
Referenced by XHdcp1x_CfgInitialize.
int XHdcp1x_RxPoll(XHdcp1x *InstancePtr)
This function polls the HDCP receiver module.
InstancePtr is the receiver instance. XST_SUCCESS if successful. None.
Referenced by XHdcp1x_Poll.
int XHdcp1x_RxSetRepeaterBcaps(XHdcp1x *InstancePtr, u8 IsRptr)
This function set the REPEATER bit for the HDCP RX interface.
InstancePtr is the receiver instance. IsRptr is the truth value to determine if the repeater bit in the port registers is to be set. XST_SUCCESS if successful. This function disables and then re-enables the interface.
References XHdcp1x_PortSetRepeater.
Referenced by XHdcp1x_SetRepeater.
int XHdcp1x_RxReset(XHdcp1x *InstancePtr)
This function resets an HDCP interface.
InstancePtr is the receiver instance. XST_SUCCESS if successful. This function disables and then re-enables the interface.
Referenced by XHdcp1x_Reset.
int XHdcp1x_RxEnable(XHdcp1x *InstancePtr)
This function enables a HDCP receive interface.
InstancePtr is the receiver instance. XST_SUCCESS if successful. None.
Referenced by XHdcp1x_Enable.
int XHdcp1x_RxDisable(XHdcp1x *InstancePtr)
This function disables a HDCP receive interface.
InstancePtr is the receiver instance. XST_SUCCESS if successful. None.
Referenced by XHdcp1x_Disable.
int XHdcp1x_RxIsEnabled(const XHdcp1x *InstancePtr)
This function queries an interface to check if is enabled.
InstancePtr is the receiver instance. Truth value indicating is enabled (true) or not (false). None.
References XHdcp1x_Rx::CurrentState, XHdcp1x::Rx.
Referenced by XHdcp1x_IsEnabled.
int XHdcp1x_RxSetPhysicalState(XHdcp1x *InstancePtr, int IsUp)
This function updates the physical state of an HDCP interface.
InstancePtr is the receiver instance. IsUp is truth value indicating the status of physical interface. XST_SUCCESS if successful. None.
Referenced by XHdcp1x_SetPhysicalState.
int XHdcp1x_RxSetLaneCount(XHdcp1x *InstancePtr, int LaneCount)
This function set the lane count of an hdcp interface.
InstancePtr is the receiver instance. LaneCount is the number of lanes of the interface. XST_SUCCESS if successful. None.
References XHdcp1x_CipherSetNumLanes.
Referenced by XHdcp1x_SetLaneCount.
int XHdcp1x_RxDownstreamReady(XHdcp1x *InstancePtr)
This function initiates downstream ready/ assemble ksv list on an interface.
InstancePtr is the receiver instance. XST_SUCCESS if successful. None.
Referenced by XHdcp1x_DownstreamReady.
int XHdcp1x_RxAuthenticate(XHdcp1x *InstancePtr)
This function initiates authentication on an interface.
InstancePtr is the receiver instance. XST_SUCCESS if successful. None.
Referenced by XHdcp1x_Authenticate.
int XHdcp1x_RxIsInProgress(const XHdcp1x *InstancePtr)
This function queries an interface to check if authentication is in progress.
InstancePtr is the receiver instance. Truth value indicating in progress (true) or not (false). None.
References XHdcp1x_Rx::CurrentState, XHdcp1x::Rx.
int XHdcp1x_RxIsAuthenticated(const XHdcp1x *InstancePtr)
This function queries an interface to check if its been authenticated.
InstancePtr is the receiver instance. Truth value indicating authenticated (true) or not (false). None.
References XHdcp1x_Rx::CurrentState, XHdcp1x::Rx.
Referenced by XHdcp1x_IsAuthenticated.
int XHdcp1x_RxIsInComputations(const XHdcp1x *InstancePtr)
This function queries an interface to check if its in the computations state.
InstancePtr is the receiver instance. Truth value indicating authenticated (true) or not (false). None.
References XHdcp1x_Rx::CurrentState, XHdcp1x::Rx.
Referenced by XHdcp1x_IsInComputations.
int XHdcp1x_RxIsInWaitforready(const XHdcp1x *InstancePtr)
This function queries an interface to check if its in the wait-for-downstream-ready state.
InstancePtr is the receiver instance. Truth value indicating authenticated (true) or not (false). None.
References XHdcp1x_Rx::CurrentState, XHdcp1x::Rx.
Referenced by XHdcp1x_IsInWaitforready.
u64 XHdcp1x_RxGetEncryption(const XHdcp1x *InstancePtr)
This function retrieves the current encryption stream map.
InstancePtr is the receiver instance. The current encryption stream map. None.
References XHdcp1x_CipherGetEncryption.
Referenced by XHdcp1x_GetEncryption.
void XHdcp1x_RxHandleTimeout(XHdcp1x *InstancePtr)
This function handles a timeout on an HDCP interface.
InstancePtr is the receiver instance. None.
Referenced by XHdcp1x_HandleTimeout.
int XHdcp1x_RxInfo(const XHdcp1x *InstancePtr)
This function implements the debug display output for receiver instances.
InstancePtr is the receiver instance. XST_SUCCESS if successful. None.
References XHdcp1x_RxStats::AuthAttempts, XHdcp1x::Cipher, XHdcp1x::Config, XHdcp1x_Rx::CurrentState, XHdcp1x_Rx::Flags, XHdcp1x_CipherStats::IntCount, XHdcp1x_PortStats::IntCount, XHdcp1x_Config::IsHDMI, XHdcp1x_RxStats::LinkFailures, XHdcp1x::Port, XHdcp1x_Rx::PreviousState, XHdcp1x_RxStats::RiUpdates, XHdcp1x::Rx, XHdcp1x_Cipher::Stats, XHdcp1x_PortStruct::Stats, XHdcp1x_Rx::Stats, XHdcp1x_CipherGetLocalKsv, XHdcp1x_CipherGetVersion, XHDCP1X_DEBUG_PRINTF, XHdcp1x_GetDriverVersion, XHdcp1x_IsEncrypted.
Referenced by XHdcp1x_Info.
int XHdcp1x_RxGetRepeaterInfo(XHdcp1x *InstancePtr, XHdcp1x_RepeaterExchange *RepeaterInfoPtr)
This function copies the V'H0, V'H1, V'H2, V'H3, V'H4, KSVList and BInfo values in the HDCP RX HDCP Instance for Repeater validation .
InstancePtr is the receiver instance. RepeaterInfoPtr is the Repeater information in the transmitter instance. XST_SUCCESS if successful. None.
References XHdcp1x_RepeaterExchange::Depth, XHdcp1x_RepeaterExchange::DeviceCount, XHdcp1x_RepeaterExchange::KsvList, XHdcp1x::RepeaterValues, XHdcp1x_RepeaterExchange::V.
Referenced by XHdcp1x_GetRepeaterInfo.
void XHdcp1x_RxSetTopologyUpdate(XHdcp1x *InstancePtr)
This function does the necessary actions to update HDCP after the topology has been set.
InstancePtr is a pointer to the Hdcp1x core instance. None.
Referenced by XHdcp1x_SetTopologyUpdate.
void XHdcp1x_RxSetTopology(XHdcp1x *InstancePtr, const XHdcp1x_RepeaterExchange *TopologyPtr)
This function sets the RepeaterInfo value int the HDCP RX instance.
InstancePtr is a pointer to the Hdcp1x core instance. TopologyPtr is the pointer to topology information. None.
References XHdcp1x::RepeaterValues.
Referenced by XHdcp1x_SetTopology.
void XHdcp1x_RxSetTopologyKSVList(XHdcp1x *InstancePtr, u8 *ListPtr, u32 ListSize)
This function sets the KSVList value(s) in the HDCP RX KSV Fifo register space for the upstream interface to read.
InstancePtr is a pointer to the Hdcp1x core instance. ListPtr is a pointer to the KSV list. ListSize is the number of KSVs in the list. None.
References XHdcp1x_RepeaterExchange::KsvList, XHdcp1x::RepeaterValues, XHDCP1X_PORT_SIZE_BKSV.
Referenced by XHdcp1x_SetTopologyKSVList.
void XHdcp1x_RxSetTopologyDepth(XHdcp1x *InstancePtr, u32 Value)
This function sets the Depth value in the HDCP RX BStatus/BInfo register space for the upstream interface to read.
InstancePtr is a pointer to the Hdcp1x core instance. Value is the Depth value. None.
References XHdcp1x_RepeaterExchange::Depth, XHdcp1x::RepeaterValues.
Referenced by XHdcp1x_SetTopologyField.
void XHdcp1x_RxSetTopologyDeviceCnt(XHdcp1x *InstancePtr, u32 Value)
This function sets the DEVICE_COUNT value in the HDCP RX register space for the upstream interface to read.
InstancePtr is a pointer to the Hdcp1x core instance. Value is the device count value. None.
References XHdcp1x_RepeaterExchange::DeviceCount, XHdcp1x::RepeaterValues.
Referenced by XHdcp1x_SetTopologyField.
void XHdcp1x_RxSetTopologyMaxCascadeExceeded(XHdcp1x *InstancePtr, u8 Value)
This function sets the MAX_CASCADE_EXCEEDED error flag in the HDCP BStatus/BInfo register to indicate a topology error.
Setting the flag indicates a depth of more than (4 - 1). InstancePtr is a pointer to the Hdcp1x core instance. Value is either TRUE or FALSE. None.
References XHDCP1X_PORT_BINFO_DEPTH_ERR_SHIFT, XHDCP1X_PORT_BSTATUS_DEPTH_ERR_SHIFT, XHDCP1X_PORT_OFFSET_BINFO, XHDCP1X_PORT_OFFSET_BSTATUS, XHDCP1X_PORT_SIZE_BINFO, XHDCP1X_PORT_SIZE_BSTATUS, XHdcp1x_PortRead, XHdcp1x_PortWrite.
Referenced by XHdcp1x_SetTopologyField.
void XHdcp1x_RxSetTopologyMaxDevsExceeded(XHdcp1x *InstancePtr, u8 Value)
This function sets the MAX_DEVS_EXCEEDED error flag in the HDCP BStatus register to indicate a topology error.
Setting the flag indicates that more than 31 downstream devices are attached. InstancePtr is a pointer to the Hdcp1x core instance. Value is either TRUE or FALSE. None.
References XHDCP1X_PORT_BINFO_DEV_CNT_ERR_SHIFT, XHDCP1X_PORT_BSTATUS_DEV_CNT_ERR_SHIFT, XHDCP1X_PORT_OFFSET_BINFO, XHDCP1X_PORT_OFFSET_BSTATUS, XHDCP1X_PORT_SIZE_BINFO, XHDCP1X_PORT_SIZE_BSTATUS, XHdcp1x_PortRead, XHdcp1x_PortWrite.
Referenced by XHdcp1x_SetTopologyField.
void XHdcp1x_RxSetHdmiMode(XHdcp1x *InstancePtr, u8 Value)
This function set the HDMI_MODE in the BStatus register of the HDMI RX DDC space.
InstancePtr is a pointer to the Hdcp1x core instance. Value is the truth-value. None.
References UNUSED, XHDCP1X_PORT_BIT_BSTATUS_HDMI_MODE, XHDCP1X_PORT_OFFSET_BSTATUS, XHDCP1X_PORT_SIZE_BSTATUS, XHdcp1x_PortRead, XHdcp1x_PortWrite.
Referenced by XHdcp1x_SetHdmiMode.
static void XHdcp1x_RxCheckEncryptionChange(XHdcp1x *InstancePtr)
This functions handles check if the encryption status (enable/disable) of the HDCP cipher has changed.
InstancePtr is the receiver instance. None.
static void XHdcp1x_RxRunWaitForDownstreamState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event, XHdcp1x_StateType *NextStatePtr)
This function runs the "wait for downstream" state of the receiver state machine.
InstancePtr is the receiver instance. Event is the event to process. NextStatePtr is the next state. None.
static void XHdcp1x_RxRunAssembleKsvListState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event, XHdcp1x_StateType *NextStatePtr)
This function runs the "assemble KSV list" state of the receiver state machine.
InstancePtr is the receiver instance. Event is the event to process. NextStatePtr is the next state. None.
static void XHdcp1x_TxDebugLog(const XHdcp1x *InstancePtr, const char *LogMsg)
This function logs a debug message on behalf of a handler state machine.
InstancePtr is the receiver instance. LogMsg is the message to log. None.
static void XHdcp1x_TxPostEvent(XHdcp1x *InstancePtr, XHdcp1x_EventType Event)
This function posts an event to a state machine.
InstancePtr is the transmitter instance. Event is the event to post. None.
static void XHdcp1x_TxStartTimer(XHdcp1x *InstancePtr, u16 TimeoutInMs)
This function starts a state machine's timer.
InstancePtr is the state machine. TimeoutInMs is the timeout in milli-seconds. None.
static void XHdcp1x_TxStopTimer(XHdcp1x *InstancePtr)
This function stops a state machine's timer.
InstancePtr is the state machine. None.
static void XHdcp1x_TxBusyDelay(XHdcp1x *InstancePtr, u16 DelayInMs)
This function busy delays a state machine.
InstancePtr is the state machine. DelayInMs is the delay time in milli-seconds. None.
static void XHdcp1x_TxReauthenticateCallback(void *Parameter)
This function acts as the reauthentication callback for a state machine.
Parameter is the parameter specified during registration. None. None.
static void XHdcp1x_TxCheckLinkCallback(void *Parameter)
This function acts as the check link callback for a state machine.
Parameter is the parameter specified during registration. None.
static void XHdcp1x_TxSetCheckLinkState(XHdcp1x *InstancePtr, int IsEnabled)
This function sets the check link state of the handler.
InstancePtr is the HDCP state machine. IsEnabled is truth value indicating on/off. None.
static void XHdcp1x_TxEnableEncryptionState(XHdcp1x *InstancePtr)
This function enables encryption for a state machine.
InstancePtr is the HDCP state machine. None. This function inserts a 5ms delay for things to settle when encryption is actually being disabled.
static void XHdcp1x_TxDisableEncryptionState(XHdcp1x *InstancePtr)
This function disables encryption for a state machine.
InstancePtr is the HDCP state machine. None. This function inserts a 5ms delay for things to settle when encryption is actually being disabled.
static void XHdcp1x_TxEnableState(XHdcp1x *InstancePtr)
This function enables a state machine.
InstancePtr is the HDCP state machine. None. None.
static void XHdcp1x_TxDisableState(XHdcp1x *InstancePtr)
This function disables a state machine.
InstancePtr is the HDCP state machine. None. None.
static void XHdcp1x_TxCheckRxCapable(const XHdcp1x *InstancePtr, XHdcp1x_StateType *NextStatePtr)
This function checks to ensure that the remote end is HDCP capable.
InstancePtr is the HDCP state machine. NextStatePtr is the next state. None. None.
static u64 XHdcp1x_TxGenerateAn(XHdcp1x *InstancePtr)
This function generates the An from a random number generator.
InstancePtr is the HDCP state machine. A 64-bit pseudo random number (An). None.
static int XHdcp1x_TxIsKsvValid(u64 Ksv)
This function validates a KSV value as having 20 1s and 20 0s.
Ksv is the value to validate. Truth value indicating valid (TRUE) or not (FALSE). None.
static void XHdcp1x_TxExchangeKsvs(XHdcp1x *InstancePtr, XHdcp1x_StateType *NextStatePtr)
This function exchanges the ksvs between the two ends of the link.
InstancePtr is the HDCP state machine. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxStartComputations(XHdcp1x *InstancePtr, XHdcp1x_StateType *NextStatePtr)
This function initiates the computations for a state machine.
InstancePtr is the HDCP receiver state machine. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxPollForComputations(XHdcp1x *InstancePtr, XHdcp1x_StateType *NextStatePtr)
This function polls the progress of the computations for a state machine.
InstancePtr is the HDCP state machine. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxValidateRx(XHdcp1x *InstancePtr, XHdcp1x_StateType *NextStatePtr)
This function validates the attached receiver.
InstancePtr is the HDCP state machine. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxCheckLinkIntegrity(XHdcp1x *InstancePtr, XHdcp1x_StateType *NextStatePtr)
This function checks the integrity of a HDCP link.
InstancePtr is the hdcp state machine. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxTestForRepeater(XHdcp1x *InstancePtr, XHdcp1x_StateType *NextStatePtr)
This function checks the remote end to see if its a repeater.
InstancePtr is the HDCP state machine. NextStatePtr is the next state. None. The implementation of this function enables encryption when a repeater is detected downstream. The standard is ambiguous as to the handling of this specific case by this behaviour is required in order to pass the Unigraf compliance test suite.
static void XHdcp1x_TxPollForWaitForReady(XHdcp1x *InstancePtr, XHdcp1x_StateType *NextStatePtr)
This function polls a state machine in the "wait for ready" state.
InstancePtr is the hdcp state machine. NextStatePtr is the next state. None. None.
static int XHdcp1x_TxSetRepeaterInfo(XHdcp1x *InstancePtr)
This function sets the V'H0, V'H1, V'H2, V'H3, V'H4, KSVList and BInfo values in the HDCP TX HDCP Instance for Repeater validation .
InstancePtr is the transmitter instance. -XST_SUCCESS if successful. -XST_FAILURE if unsuccessful. None.
static int XHdcp1x_TxValidateKsvList(XHdcp1x *InstancePtr, u16 RepeaterInfo)
This function validates the ksv list from an attached repeater.
InstancePtr is the hdcp state machine. RepeaterInfo is the repeater information. Truth value indicating valid (TRUE) or invalid (FALSE). None.
static void XHdcp1x_TxReadKsvList(XHdcp1x *InstancePtr, XHdcp1x_StateType *NextStatePtr)
This function reads the ksv list from an attached repeater.
InstancePtr is the hdcp state machine. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxRunDisabledState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event, XHdcp1x_StateType *NextStatePtr)
This function runs the "disabled" state of the transmit state machine.
InstancePtr is the transmitter instance. Event is the event to process. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxRunDetermineRxCapableState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event, XHdcp1x_StateType *NextStatePtr)
This function runs the "determine rx capable" state of the transmit state machine.
InstancePtr is the transmitter instance. Event is the event to process. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxRunExchangeKsvsState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event, XHdcp1x_StateType *NextStatePtr)
This function runs the "exchange ksvs" state of the transmit state machine.
InstancePtr is the transmitter instance. Event is the event to process. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxRunComputationsState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event, XHdcp1x_StateType *NextStatePtr)
This function runs the "computations" state of the transmit state machine.
InstancePtr is the transmitter instance. Event is the event to process. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxRunValidateRxState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event, XHdcp1x_StateType *NextStatePtr)
This function runs the "validate-rx" state of the transmit state machine.
InstancePtr is the transmitter instance. Event is the event to process. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxRunAuthenticatedState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event, XHdcp1x_StateType *NextStatePtr)
This function runs the "authenticated" state of the transmit state machine.
InstancePtr is the transmitter instance. Event is the event to process. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxRunLinkIntegrityCheckState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event, XHdcp1x_StateType *NextStatePtr)
This function runs the "link-integrity check" state of the transmit state machine.
InstancePtr is the transmitter instance. Event is the event to process. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxRunTestForRepeaterState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event, XHdcp1x_StateType *NextStatePtr)
This function runs the "test-for-repeater" state of the transmit state machine.
InstancePtr is the transmitter instance. Event is the event to process. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxRunWaitForReadyState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event, XHdcp1x_StateType *NextStatePtr)
This function runs the "wait-for-ready" state of the transmit state machine.
InstancePtr is the transmitter instance. Event is the event to process. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxRunReadKsvListState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event, XHdcp1x_StateType *NextStatePtr)
This function runs the "read-ksv-list" state of the transmit state machine.
InstancePtr is the transmitter instance. Event is the event to process. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxRunUnauthenticatedState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event, XHdcp1x_StateType *NextStatePtr)
This function runs the "unauthenticated" state of the transmit state machine.
InstancePtr is the transmitter instance. Event is the event to process. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxRunPhysicalLayerDownState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event, XHdcp1x_StateType *NextStatePtr)
This function runs the "physical-layer-down" state of the transmit state machine.
InstancePtr is the transmitter instance. Event is the event to process. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxEnterState(XHdcp1x *InstancePtr, XHdcp1x_StateType State, XHdcp1x_StateType *NextStatePtr)
This function enters a state.
InstancePtr is the HDCP state machine. State is the state to enter. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxExitState(XHdcp1x *InstancePtr, XHdcp1x_StateType State, XHdcp1x_StateType *NextStatePtr)
This function exits a state.
InstancePtr is the HDCP state machine. State is the state to exit. None. None.
static void XHdcp1x_TxDoTheState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event)
This function drives a transmit state machine.
InstancePtr is the HDCP state machine. Event is the event to process. None. None.
static void XHdcp1x_TxProcessPending(XHdcp1x *InstancePtr)
This function processes the events pending on a state machine.
InstancePtr is the receiver instance. None.
static const char * XHdcp1x_TxStateToString(XHdcp1x_StateType State)
This function converts from a state to a display string.
State is the state to convert. The corresponding display string. None.
int XHdcp1x_TxSetCallback(XHdcp1x *InstancePtr, XHdcp1x_HandlerType HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs callback functions for the given HandlerType:
InstancePtr is a pointer to the HDCP core instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XHdcp1x_Tx::AuthenticatedCallback, XHdcp1x_Tx::AuthenticatedCallbackRef, XHdcp1x_Tx::DdcRead, XHdcp1x_Tx::DdcReadRef, XHdcp1x_Tx::DdcWrite, XHdcp1x_Tx::DdcWriteRef, XHdcp1x_Tx::IsAuthenticatedCallbackSet, XHdcp1x_Tx::IsDdcReadSet, XHdcp1x_Tx::IsDdcWriteSet, XHdcp1x_Tx::IsRepeaterExchangeCallbackSet, XHdcp1x_Tx::IsUnauthenticatedCallbackSet, XHdcp1x_Tx::RepeaterExchangeCallback, XHdcp1x_Tx::RepeaterExchangeRef, XHdcp1x::Tx, XHdcp1x_Tx::UnauthenticatedCallback, XHdcp1x_Tx::UnauthenticatedCallbackRef.
Referenced by XHdcp1x_SetCallback.
void XHdcp1x_TxInit(XHdcp1x *InstancePtr)
This function initializes a transmit state machine.
InstancePtr is the receiver instance. None.
References XHdcp1x_Tx::PendingEvents, XHdcp1x::Tx.
Referenced by XHdcp1x_CfgInitialize.
int XHdcp1x_TxPoll(XHdcp1x *InstancePtr)
This function polls an HDCP interface.
InstancePtr is the transmitter instance. XST_SUCCESS if successful. None.
References XHdcp1x::IsReady.
Referenced by XHdcp1x_Poll.
int XHdcp1x_TxReset(XHdcp1x *InstancePtr)
This function resets an HDCP interface.
InstancePtr is the transmitter instance. XST_SUCCESS if successful. This function disables and then re-enables the interface.
References XHdcp1x_Tx::IsAuthReqPending, XHdcp1x::Tx.
Referenced by XHdcp1x_Reset.
int XHdcp1x_TxEnable(XHdcp1x *InstancePtr)
This function enables an HDCP interface.
InstancePtr is the transmitter instance. XST_SUCCESS if successful. None.
Referenced by XHdcp1x_Enable.
int XHdcp1x_TxDisable(XHdcp1x *InstancePtr)
This function disables an HDCP interface.
InstancePtr is the transmitter instance. XST_SUCCESS if successful. None.
Referenced by XHdcp1x_Disable.
int XHdcp1x_TxIsEnabled(const XHdcp1x *InstancePtr)
This function queries an interface to check if it is enabled.
InstancePtr is the transmitter instance. Truth value indicating is enabled (true) or not (false). None.
References XHdcp1x_Tx::CurrentState, XHdcp1x::Tx.
Referenced by XHdcp1x_IsEnabled, XHdcp1x_TxDisableEncryption.
int XHdcp1x_TxSetPhysicalState(XHdcp1x *InstancePtr, int IsUp)
This function updates the physical state of an HDCP interface.
InstancePtr is the transmitter instance. IsUp is truth value indicating the status of physical interface. XST_SUCCESS if successful. None.
Referenced by XHdcp1x_SetPhysicalState.
int XHdcp1x_TxSetLaneCount(XHdcp1x *InstancePtr, int LaneCount)
This function set the lane count of an HDCP interface.
InstancePtr is the transmitter instance. LaneCount is the number of lanes of the interface. XST_SUCCESS if successful. None.
References XHdcp1x_CipherSetNumLanes.
Referenced by XHdcp1x_SetLaneCount.
int XHdcp1x_TxSetMSTMode(XHdcp1x *InstancePtr, int mode)
This function set the MST/SST mode of an HDCP interface.
InstancePtr is the transmitter instance. mode enables MST/SST configuration. XST_SUCCESS if successful. None.
References XHdcp1x_Tx::mode, XHdcp1x::Tx, XHdcp1x_CipherSetMode.
Referenced by XHdcp1x_SetMSTMode.
int XHdcp1x_TxEnableEcfTimeslots(XHdcp1x *InstancePtr, u64 timeslots)
This function enables HDCP ECF slots.
InstancePtr is the receiver instance. timeslots is the ECF timeslots to be enabled. XST_SUCCESS if successful. None.
References XHdcp1x_SetEcfSlots.
Referenced by XHdcp1x_Enable_ECF_Slots.
int XHdcp1x_TxAuthenticate(XHdcp1x *InstancePtr)
This function initiates authentication on an interface.
InstancePtr is the transmitter instance. XST_SUCCESS if successful. None.
References XHdcp1x_Tx::IsAuthReqPending, XHdcp1x::Tx.
Referenced by XHdcp1x_Authenticate.
int XHdcp1x_TxReadDownstream(XHdcp1x *InstancePtr)
This function initiates the transmitter to read READY bit from downstream and complete second part of authentication.
InstancePtr is the transmitter instance. XST_SUCCESS if successful. None.
Referenced by XHdcp1x_ReadDownstream.
int XHdcp1x_TxIsInProgress(const XHdcp1x *InstancePtr)
This function queries an interface to check if authentication is still in progress.
InstancePtr is the transmitter instance. Truth value indicating in progress (true) or not (false). None.
References XHdcp1x_Tx::IsAuthReqPending, XHdcp1x::Tx.
Referenced by XHdcp1x_IsInProgress.
int XHdcp1x_TxIsAuthenticated(const XHdcp1x *InstancePtr)
This function queries an interface to check if its been authenticated.
InstancePtr is the transmitter instance. Truth value indicating authenticated (true) or not (false). None.
References XHdcp1x_Tx::CurrentState, XHdcp1x::Tx.
Referenced by XHdcp1x_IsAuthenticated, XHdcp1x_TxEnableEncryption.
int XHdcp1x_TxIsInComputations(const XHdcp1x *InstancePtr)
This function queries an interface to check if its in the computations state.
InstancePtr is the transmitter instance. Truth value indicating authenticated (true) or not (false). None.
References XHdcp1x_Tx::CurrentState, XHdcp1x::Tx.
Referenced by XHdcp1x_IsInComputations.
int XHdcp1x_TxIsInWaitforready(const XHdcp1x *InstancePtr)
This function queries an interface to check if its in the wait-for-ready state.
InstancePtr is the transmitter instance. Truth value indicating authenticated (true) or not (false). None.
References XHdcp1x_Tx::CurrentState, XHdcp1x::Tx.
Referenced by XHdcp1x_IsInWaitforready.
int XHdcp1x_TxIsDownstrmCapable(const XHdcp1x *InstancePtr)
This function queries the downstream device to check if the downstream device is HDCP capable.
InstancePtr is the receiver instance. Truth value indicating HDCP capability (true) or not (false). None.
References XHdcp1x_PortIsCapable.
Referenced by XHdcp1x_IsDwnstrmCapable.
u64 XHdcp1x_TxGetEncryption(const XHdcp1x *InstancePtr)
This function retrieves the current encryption stream map.
InstancePtr the transmitter instance. The current encryption stream map. None.
References XHdcp1x_Tx::EncryptionMap, XHdcp1x::Tx.
Referenced by XHdcp1x_GetEncryption.
int XHdcp1x_TxEnableEncryption(XHdcp1x *InstancePtr, u64 StreamMap)
This function enables encryption on set of streams on an HDCP interface.
InstancePtr is the transmitter instance. StreamMap is the bit map of streams to enable encryption on. XST_SUCCESS if successful. None.
References XHdcp1x_Tx::EncryptionMap, XHdcp1x::Tx, XHdcp1x_TxIsAuthenticated.
Referenced by XHdcp1x_EnableEncryption.
int XHdcp1x_TxDisableEncryption(XHdcp1x *InstancePtr, u64 StreamMap)
This function disables encryption on set of streams on an HDCP interface.
InstancePtr is the transmitter instance. StreamMap is the bit map of streams to disable encryption on. XST_SUCCESS if successful. None.
References XHdcp1x_Tx::EncryptionMap, XHdcp1x::Tx, XHdcp1x_CipherDisableEncryption, XHdcp1x_TxIsEnabled.
Referenced by XHdcp1x_DisableEncryption.
void XHdcp1x_TxSetHdmiMode(XHdcp1x *InstancePtr, u8 Value)
This set a flag that allows the hdcp1x drivers to determine if the transmitter is HDMI or DVI.
InstancePtr is the transmitter instance. Value The mode value to set (typically 1 for HDMI, 0 for DVI). None.
References XHdcp1x::Tx, XHdcp1x_Tx::TxIsHdmi, UNUSED.
Referenced by XHdcp1x_SetHdmiMode.
void XHdcp1x_TxHandleTimeout(XHdcp1x *InstancePtr)
This function handles a timeout on an HDCP interface.
InstancePtr is the transmitter instance. None.
Referenced by XHdcp1x_HandleTimeout.
int XHdcp1x_TxIsRepeater(XHdcp1x *InstancePtr)
This function returns if HDCP TX interface is connected to a downstream repeater.
InstancePtr is the transmitter instance. TRUE if Repeater.FALSE if not Repeater, None.
References XHdcp1x_PortIsRepeater.
Referenced by XHdcp1x_IsRepeater.
int XHdcp1x_TxInfo(const XHdcp1x *InstancePtr)
This function implements the debug display output for transmit instances.
InstancePtr is the receiver instance. XST_SUCCESS if successful. None.
References XHdcp1x_TxStats::AuthFailed, XHdcp1x_TxStats::AuthPassed, XHdcp1x::Cipher, XHdcp1x::Config, XHdcp1x_Tx::CurrentState, XHdcp1x_Tx::EncryptionMap, XHdcp1x_Tx::Flags, XHdcp1x_CipherStats::IntCount, XHdcp1x_PortStats::IntCount, XHdcp1x_Config::IsHDMI, XHdcp1x_TxStats::LinkCheckFailed, XHdcp1x_TxStats::LinkCheckPassed, XHdcp1x::Port, XHdcp1x_Tx::PreviousState, XHdcp1x_TxStats::ReadFailures, XHdcp1x_TxStats::ReauthRequested, XHdcp1x_Tx::StateHelper, XHdcp1x_Cipher::Stats, XHdcp1x_PortStruct::Stats, XHdcp1x_Tx::Stats, XHdcp1x::Tx, XHdcp1x_CipherGetLocalKsv, XHdcp1x_CipherGetVersion, XHDCP1X_DEBUG_PRINTF, XHdcp1x_GetDriverVersion, XHdcp1x_IsEncrypted.
Referenced by XHdcp1x_Info.
void XHdcp1x_TxEnableBlank(XHdcp1x *InstancePtr)
This function enables the blank output for the cipher.
InstancePtr is a pointer to the Hdcp1.4 core instance. None.
References XHdcp1x_CipherEnableBlank.
Referenced by XHdcp1x_EnableBlank.
void XHdcp1x_TxDisableBlank(XHdcp1x *InstancePtr)
This function disables the blank output for the cipher.
InstancePtr is a pointer to the Hdcp1.4 core instance. None.
References XHdcp1x_CipherDisableBlank.
Referenced by XHdcp1x_DisableBlank.
void XHdcp1x_TxTriggerDownstreamAuth(void *Parameter)
This function acts as the downstream authentication trigger callback for a Repeater state machine, to start the second part of authentication.
Parameter is the parameter specified during registration. None.
u8 * XHdcp1x_TxGetTopologyKSVList(XHdcp1x *InstancePtr)
This function returns the value of KSV List read in the downstream interface of the repeater topology.
InstancePtr is a pointer to the XHdcp14 core instance. TRUE if MAX_DEPTH_EXCEEDEDFALSE if not None.
References XHdcp1x_RepeaterExchange::DeviceCount, XHdcp1x_RepeaterExchange::KsvList, XHdcp1x::RepeaterValues.
Referenced by XHdcp1x_GetTopologyKSVList.
u32 XHdcp1x_TxGetTopologyDepth(XHdcp1x *InstancePtr)
This function returns the value of Depth read in the downstream interface of the repeater topology.
InstancePtr is a pointer to the XHdcp14 core instance. Value of Depth. None.
References XHdcp1x_RepeaterExchange::Depth, XHdcp1x::RepeaterValues.
Referenced by XHdcp1x_GetTopologyField.
u32 XHdcp1x_TxGetTopologyDeviceCnt(XHdcp1x *InstancePtr)
This function returns the value of Device Count read in the downstream interface of the repeater topology.
InstancePtr is a pointer to the XHdcp14 core instance. TRUE if MAX_DEPTH_EXCEEDEDFALSE if not None.
References XHdcp1x_RepeaterExchange::DeviceCount, XHdcp1x::RepeaterValues.
Referenced by XHdcp1x_GetTopologyField.
u32 XHdcp1x_TxGetTopologyMaxCascadeExceeded(XHdcp1x *InstancePtr)
This function returns the MAX_DEPTH_EXCEEDED flag in the repeater topology structure.
InstancePtr is a pointer to the XHdcp14 core instance. TRUE if MAX_DEPTH_EXCEEDEDFALSE if not None.
References XHDCP1X_PORT_BINFO_BIT_DEPTH_ERR, XHDCP1X_PORT_BSTATUS_BIT_DEPTH_ERR, XHDCP1X_PORT_OFFSET_BINFO, XHDCP1X_PORT_OFFSET_BSTATUS, XHDCP1X_PORT_SIZE_BINFO, XHDCP1X_PORT_SIZE_BSTATUS, XHdcp1x_PortRead.
Referenced by XHdcp1x_GetTopologyField.
u8 * XHdcp1x_TxGetTopologyBKSV(XHdcp1x *InstancePtr)
This function returns the value of BKSV of the device connected to the repeater downstream interface.
InstancePtr is a pointer to the XHdcp14 core instance. TRUE if MAX_DEPTH_EXCEEDEDFALSE if not None.
References XHDCP1X_PORT_BUF_TO_UINT, XHDCP1X_PORT_OFFSET_BKSV, XHDCP1X_PORT_SIZE_BKSV, XHdcp1x_PortRead.
Referenced by XHdcp1x_GetTopologyBKSV.
u32 XHdcp1x_TxGetTopologyMaxDevsExceeded(XHdcp1x *InstancePtr)
This function returns the MAX_DEVICS_EXCEEDED flag in the repeater topology structure.
InstancePtr is a pointer to the XHdcp14 core instance. TRUE if MAX_DEVICES_EXCEEDEDFALSE if not None.
References XHDCP1X_PORT_BINFO_BIT_DEV_CNT_ERR, XHDCP1X_PORT_BSTATUS_BIT_DEV_CNT_ERR, XHDCP1X_PORT_OFFSET_BINFO, XHDCP1X_PORT_OFFSET_BSTATUS, XHDCP1X_PORT_SIZE_BINFO, XHDCP1X_PORT_SIZE_BSTATUS, XHdcp1x_PortRead.
Referenced by XHdcp1x_GetTopologyField.
XHdcp1x_RepeaterExchange * XHdcp1x_TxGetTopology(XHdcp1x *InstancePtr)
This function returns a pointer to the downstream Topology structure.
InstancePtr is a pointer to the XHdcp14 core instance. A pointer to the XHdcp14 Topology structure or NULL when the topology info is invalid. None.
References XHdcp1x_Tx::CurrentState, XHdcp1x::IsRepeater, XHdcp1x::RepeaterValues, XHdcp1x::Tx.
Referenced by XHdcp1x_GetTopology.
void XHdcp1x_TxEnableEcf(XHdcp1x *InstancePtr, u64 timeslots)
This function enables HDCP ECF slots.
InstancePtr is the receiver instance. timeslots is the number of timeslots to enable ECF for. None.
References XHdcp1x_SetEcfSlots.
DRIVER_VERSION
This defines the version of the software driver.
Referenced by XHdcp1x_GetDriverVersion.
XHDCP1X_H
< Prevent circular inclusions by using protection macros
XPAR_XHDCP_NUM_INSTANCES
XPAR_XDPTXSS_NUM_INSTANCES
XPAR_XDPRXSS_NUM_INSTANCES
XHDCP1X_KSV_SIZE
Size of each hdcp 1.4 Public Key in bytes.
XHDCP1X_RPTR_MAX_CASCADE
Maximum depth that the Repeater can support on the downstream interface.
XHDCP1X_RPTR_MAX_DEVS_COUNT
Maximum devices that can be cascaded to the Repeater.
XHdcp1x_SetCallBack
Alternative name for the function to set callback for HDCP functions.
UNUSED
Used to remove warnings for unused variables.
Referenced by XHdcp1x_DisableEncryption, XHdcp1x_EnableEncryption, XHdcp1x_RxSetHdmiMode, XHdcp1x_SetTopologyKSVList, XHdcp1x_TxSetHdmiMode.
XHDCP1X_ADDITIONAL_DEBUG
Adds extra functions for additional debugging.
XHDCP1X_CIPHER_H
< Prevent circular inclusions by using protection macros
HDCP1X_CIPHER_BIT_REPEATER_ENABLE
Bit in the cipher Bz register to indicate Repeater.
XHDCP1X_DEBUG_H
< Prevent circular inclusions by using protection macros
XHDCP1X_DEBUG_PRINTF
Instance of the function interface used for debug print statements.
Referenced by XHdcp1x_GetTopology, XHdcp1x_HandleTimeout, XHdcp1x_Info, XHdcp1x_IsRepeater, XHdcp1x_RxInfo, XHdcp1x_SetHdmiMode, XHdcp1x_SetTopologyUpdate, XHdcp1x_TxInfo.
XHDCP1X_DEBUG_LOGMSG
Instance of the function interface used for debug log messages.
XHDCP1X_HW_H
< Prevent circular inclusions by using protection macros
XPAR_XDPTXSS_NUM_INSTANCES
XPAR_XDPRXSS_NUM_INSTANCES
XHDCP1X_CIPHER_REG_VERSION
Version register offset.
Referenced by XHdcp1x_CipherGetVersion, XHdcp1x_SelfTest.
XHDCP1X_CIPHER_REG_TYPE
Type register offset.
Referenced by XHdcp1x_CfgInitialize.
XHDCP1X_CIPHER_REG_SCRATCH
Scratch pad register offset.
XHDCP1X_CIPHER_REG_CONTROL
Control register offset.
Referenced by XHdcp1x_CipherDisable, XHdcp1x_CipherDisableEncryption, XHdcp1x_CipherDoRequest, XHdcp1x_CipherEnable, XHdcp1x_CipherEnableEncryption, XHdcp1x_CipherGetNumLanes, XHdcp1x_CipherInit, XHdcp1x_CipherSetB, XHdcp1x_CipherSetK, XHdcp1x_CipherSetMode, XHdcp1x_CipherSetNumLanes, XHdcp1x_CipherSetRemoteKsv.
XHDCP1X_CIPHER_REG_STATUS
Status register offset.
Referenced by XHdcp1x_CipherIsLinkUp.
XHDCP1X_CIPHER_REG_INTERRUPT_MASK
Interrupt Mask register offset.
Referenced by XHdcp1x_CipherDisable, XHdcp1x_CipherInit, XHdcp1x_CipherSetLinkStateCheck, XHdcp1x_CipherSetRiUpdate.
XHDCP1X_CIPHER_REG_INTERRUPT_STATUS
Interrupt Status register offset.
Referenced by XHdcp1x_CipherHandleInterrupt, XHdcp1x_CipherInit, XHdcp1x_CipherSetLinkStateCheck, XHdcp1x_CipherSetRiUpdate.
XHDCP1X_CIPHER_REG_ENCRYPT_ENABLE_H
Encryption Enable (High) register offset.
Referenced by XHdcp1x_CipherDisable, XHdcp1x_CipherDisableEncryption, XHdcp1x_CipherEnable, XHdcp1x_CipherEnableEncryption, XHdcp1x_CipherGetEncryption.
XHDCP1X_CIPHER_REG_ENCRYPT_ENABLE_L
Encryption Enable (Low) register offset.
Referenced by XHdcp1x_CipherDisable, XHdcp1x_CipherDisableEncryption, XHdcp1x_CipherEnable, XHdcp1x_CipherEnableEncryption, XHdcp1x_CipherGetEncryption.
XHDCP1X_CIPHER_REG_KEYMGMT_CONTROL
Key Management Control register offset.
Referenced by XHdcp1x_CipherGetLocalKsv, XHdcp1x_CipherSetKeySelect, XHdcp1x_CipherSetRemoteKsv.
XHDCP1X_CIPHER_REG_KEYMGMT_STATUS
Key Management Status register offset.
Referenced by XHdcp1x_CipherGetLocalKsv.
XHDCP1X_CIPHER_REG_KSV_LOCAL_H
Local KSV (High) register offset.
Referenced by XHdcp1x_CipherGetLocalKsv.
XHDCP1X_CIPHER_REG_KSV_LOCAL_L
Local KSV (Low) register offset.
Referenced by XHdcp1x_CipherGetLocalKsv.
XHDCP1X_CIPHER_REG_KSV_REMOTE_H
Remote KSV (High) offset.
Referenced by XHdcp1x_CipherGetRemoteKsv, XHdcp1x_CipherSetRemoteKsv.
XHDCP1X_CIPHER_REG_KSV_REMOTE_L
Remote KSV (Low) register offset.
Referenced by XHdcp1x_CipherGetRemoteKsv, XHdcp1x_CipherSetRemoteKsv.
XHDCP1X_CIPHER_REG_Km_H
Km (High) register offset.
XHDCP1X_CIPHER_REG_Km_L
Km (Low) register offset.
XHDCP1X_CIPHER_REG_CIPHER_CONTROL
Cipher Control register offset.
Referenced by XHdcp1x_CipherDisable, XHdcp1x_CipherDisableEncryption, XHdcp1x_CipherDoRequest, XHdcp1x_CipherEnable, XHdcp1x_CipherEnableEncryption.
XHDCP1X_CIPHER_REG_CIPHER_STATUS
Cipher Status register offset.
Referenced by XHdcp1x_CipherDoRequest, XHdcp1x_CipherIsRequestComplete.
XHDCP1X_CIPHER_REG_CIPHER_Bx
Cipher Bx register offset.
Referenced by XHdcp1x_CipherGetB, XHdcp1x_CipherSetB.
XHDCP1X_CIPHER_REG_CIPHER_By
Cipher By register offset.
Referenced by XHdcp1x_CipherGetB, XHdcp1x_CipherSetB.
XHDCP1X_CIPHER_REG_CIPHER_Bz
Cipher Bz register offset.
Referenced by XHdcp1x_CipherGetB, XHdcp1x_CipherSetB.
XHDCP1X_CIPHER_REG_CIPHER_Kx
Cipher Kx register offset.
Referenced by XHdcp1x_CipherGetK, XHdcp1x_CipherSetK.
XHDCP1X_CIPHER_REG_CIPHER_Ky
Cipher Ky register offset.
Referenced by XHdcp1x_CipherGetK, XHdcp1x_CipherSetK.
XHDCP1X_CIPHER_REG_CIPHER_Kz
Cipher Kz register offset.
Referenced by XHdcp1x_CipherGetK, XHdcp1x_CipherSetK.
XHDCP1X_CIPHER_REG_CIPHER_Mi_H
Cipher Mi (High) register offset.
Referenced by XHdcp1x_CipherGetMi.
XHDCP1X_CIPHER_REG_CIPHER_Mi_L
Cipher Mi (Low) register offset.
Referenced by XHdcp1x_CipherGetMi.
XHDCP1X_CIPHER_REG_CIPHER_Ri
Cipher Ri register offset.
Referenced by XHdcp1x_CipherGetRi.
XHDCP1X_CIPHER_REG_CIPHER_Ro
Cipher Ro register offset.
Referenced by XHdcp1x_CipherGetRo.
XHDCP1X_CIPHER_REG_CIPHER_Mo_H
Cipher Mo (High) register offset.
Referenced by XHdcp1x_CipherGetMo.
XHDCP1X_CIPHER_REG_CIPHER_Mo_L
Cipher Mo (Low) register offset.
Referenced by XHdcp1x_CipherGetMo.
XHDCP1X_CIPHER_REG_BLANK_VALUE
Cipher blank value register.
Referenced by XHdcp1x_CipherEnableBlank.
XHDCP1X_CIPHER_REG_BLANK_SEL
Cipher blank select register.
Referenced by XHdcp1x_CipherDisableBlank, XHdcp1x_CipherEnableBlank.
XHDCP1X_CIPHER_BITMASK_TYPE_PROTOCOL
Protocol bitmask in Type register.
Referenced by XHdcp1x_CfgInitialize.
XHDCP1X_CIPHER_BITMASK_TYPE_DIRECTION
Direction bitmask in Type register.
Referenced by XHdcp1x_CfgInitialize.
XHDCP1X_CIPHER_BITMASK_CONTROL_ENABLE
Enable bitmask in Control register.
Referenced by XHdcp1x_CipherDisable, XHdcp1x_CipherEnable.
XHDCP1X_CIPHER_BITMASK_MODE
Enable SST/MST in Control register.
Referenced by XHdcp1x_CipherSetMode.
XHDCP1X_CIPHER_BITMASK_CONTROL_UPDATE
Update bitmask in Control register.
Referenced by XHdcp1x_CipherDisable, XHdcp1x_CipherDisableEncryption, XHdcp1x_CipherDoRequest, XHdcp1x_CipherEnable, XHdcp1x_CipherEnableEncryption, XHdcp1x_CipherInit, XHdcp1x_CipherSetB, XHdcp1x_CipherSetK, XHdcp1x_CipherSetRemoteKsv.
XHDCP1X_CIPHER_BITMASK_CONTROL_NUM_LANES
Num Lanes bitmask in Control register.
Referenced by XHdcp1x_CipherGetNumLanes, XHdcp1x_CipherInit, XHdcp1x_CipherSetNumLanes.
XHDCP1X_CIPHER_BITMASK_CONTROL_RESET
Reset bitmask in Control register.
Referenced by XHdcp1x_CipherInit.
XHDCP1X_CIPHER_BITMASK_INTERRUPT_LINK_FAIL
Link Failure bitmask in Interrupt register(s)
Referenced by XHdcp1x_CipherHandleInterrupt, XHdcp1x_CipherIsLinkUp, XHdcp1x_CipherSetLinkStateCheck.
XHDCP1X_CIPHER_BITMASK_INTERRUPT_Ri_UPDATE
Ri bitmask in Interrupt register(s)
Referenced by XHdcp1x_CipherHandleInterrupt, XHdcp1x_CipherSetRiUpdate.
XHDCP1X_CIPHER_BITMASK_KEYMGMT_CONTROL_LOCAL_KSV
Read Local KSV bitmask in Key Management Control register.
Referenced by XHdcp1x_CipherGetLocalKsv.
XHDCP1X_CIPHER_BITMASK_KEYMGMT_CONTROL_BEGIN_Km
Being Km bitmask in Key Management Control register.
Referenced by XHdcp1x_CipherSetRemoteKsv.
XHDCP1X_CIPHER_BITMASK_KEYMGMT_CONTROL_ABORT_Km
Abort Km bitmask in Key Management Control register.
Referenced by XHdcp1x_CipherGetLocalKsv.
XHDCP1X_CIPHER_BITMASK_KEYMGMT_CONTROL_SET_SELECT
Key Set Select bitmask in Key Management Control register.
Referenced by XHdcp1x_CipherSetKeySelect.
XHDCP1X_CIPHER_BITMASK_KEYMGMT_STATUS_KSV_READY
Local KSV ready bitmask in Key Management Status register.
Referenced by XHdcp1x_CipherGetLocalKsv.
XHDCP1X_CIPHER_BITMASK_KEYMGMT_STATUS_Km_READY
Km Value ready bitmask in Key Management Status register.
XHDCP1X_CIPHER_BITMASK_CIPHER_CONTROL_XOR_ENABLE
XOR Enable bitmask in Cipher Control register.
Referenced by XHdcp1x_CipherDisable, XHdcp1x_CipherDisableEncryption, XHdcp1x_CipherEnable, XHdcp1x_CipherEnableEncryption.
XHDCP1X_CIPHER_BITMASK_CIPHER_CONTROL_REQUEST
Request bitmask in Cipher Control register.
Referenced by XHdcp1x_CipherDoRequest.
XHDCP1X_CIPHER_BITMASK_CIPHER_STATUS_XOR_IN_PROG
XOR In Progress bitmask in Cipher Status register.
XHDCP1X_CIPHER_BITMASK_CIPHER_STATUS_REQUEST_IN_PROG
Request In Progress bitmask in Cipher Status register.
Referenced by XHdcp1x_CipherDoRequest, XHdcp1x_CipherIsRequestComplete.
XHDCP1X_CIPHER_BITMASK_BLANK_VALUE
Cipher blank value bitmask, lower 24 bits.
Referenced by XHdcp1x_CipherEnableBlank.
XHDCP1X_CIPHER_BITMASK_BLANK_SEL
Cipher blank select bitmask.
Referenced by XHdcp1x_CipherDisableBlank, XHdcp1x_CipherEnableBlank.
XHDCP1X_CIPHER_VALUE_TYPE_PROTOCOL_DP
DP Protocol value in Type register.
XHDCP1X_CIPHER_VALUE_TYPE_PROTOCOL_HDMI
HDMI Protocol value in Type register.
Referenced by XHdcp1x_CfgInitialize.
XHDCP1X_CIPHER_VALUE_TYPE_DIRECTION_RX
RX Direction value in Type register.
Referenced by XHdcp1x_CfgInitialize.
XHDCP1X_CIPHER_VALUE_TYPE_DIRECTION_TX
TX Direction value in Type register.
XHDCP1X_CIPHER_VALUE_CIPHER_CONTROL_REQUEST_BLOCK
Block Request value in Cipher Control register.
Referenced by XHdcp1x_CipherDoRequest.
XHDCP1X_CIPHER_VALUE_CIPHER_CONTROL_REQUEST_REKEY
ReKey Request value in Cipher Control register.
XHDCP1X_CIPHER_VALUE_CIPHER_CONTROL_REQUEST_RNG
RNG Request value in Cipher Control register.
XHdcp1x_In32
Input Operations.
XHdcp1x_Out32
Output Operations.
XHdcp1x_ReadReg
This macro reads a value from a HDCP cipher register.
A 32 bit read is always performed. BaseAddress is the base address of the HDCP cipher core instance. RegOffset is the register offset of the register The 32-bit value of the register. C-style: u32 XHdcp1x_ReadReg(UINTPTR BaseAddress, u32 RegOffset)
Referenced by XHdcp1x_CfgInitialize, XHdcp1x_CipherDisable, XHdcp1x_CipherDisableBlank, XHdcp1x_CipherDisableEncryption, XHdcp1x_CipherDoRequest, XHdcp1x_CipherEnable, XHdcp1x_CipherEnableBlank, XHdcp1x_CipherEnableEncryption, XHdcp1x_CipherGetB, XHdcp1x_CipherGetEncryption, XHdcp1x_CipherGetK, XHdcp1x_CipherGetLocalKsv, XHdcp1x_CipherGetMi, XHdcp1x_CipherGetMo, XHdcp1x_CipherGetNumLanes, XHdcp1x_CipherGetRemoteKsv, XHdcp1x_CipherGetRi, XHdcp1x_CipherGetRo, XHdcp1x_CipherGetVersion, XHdcp1x_CipherHandleInterrupt, XHdcp1x_CipherInit, XHdcp1x_CipherIsLinkUp, XHdcp1x_CipherIsRequestComplete, XHdcp1x_CipherSetB, XHdcp1x_CipherSetK, XHdcp1x_CipherSetKeySelect, XHdcp1x_CipherSetLinkStateCheck, XHdcp1x_CipherSetMode, XHdcp1x_CipherSetNumLanes, XHdcp1x_CipherSetRemoteKsv, XHdcp1x_CipherSetRiUpdate, XHdcp1x_SelfTest.
XHdcp1x_WriteReg
This macro writes a value to a HDCP cipher register.
A 32 bit write is always performed. BaseAddress is the base address of the HDCP cipher core instance. RegOffset is the register offset of the register Data is the 32-bit value to write into the register. None. C-style: void XHdcp1x_WriteReg(UINTPTR BaseAddress, u32 RegOffset, u32 Data)
Referenced by XHdcp1x_CipherDisable, XHdcp1x_CipherDisableBlank, XHdcp1x_CipherDisableEncryption, XHdcp1x_CipherDoRequest, XHdcp1x_CipherEnable, XHdcp1x_CipherEnableBlank, XHdcp1x_CipherEnableEncryption, XHdcp1x_CipherGetLocalKsv, XHdcp1x_CipherHandleInterrupt, XHdcp1x_CipherInit, XHdcp1x_CipherSetB, XHdcp1x_CipherSetK, XHdcp1x_CipherSetKeySelect, XHdcp1x_CipherSetLinkStateCheck, XHdcp1x_CipherSetMode, XHdcp1x_CipherSetNumLanes, XHdcp1x_CipherSetRemoteKsv, XHdcp1x_CipherSetRiUpdate.
XHdcp1x_CipherIsEnabled
This queries a cipher to determine if it is enabled.
InstancePtr is the instance to query. Truth value indicating transmitter (TRUE) or not (FALSE). None.
Referenced by XHdcp1x_CipherDisableEncryption, XHdcp1x_CipherDoRequest, XHdcp1x_CipherEnable, XHdcp1x_CipherEnableEncryption, XHdcp1x_CipherGetB, XHdcp1x_CipherGetEncryption, XHdcp1x_CipherGetK, XHdcp1x_CipherGetLocalKsv, XHdcp1x_CipherGetMi, XHdcp1x_CipherGetMo, XHdcp1x_CipherGetNumLanes, XHdcp1x_CipherGetRi, XHdcp1x_CipherGetRo, XHdcp1x_CipherIsLinkUp, XHdcp1x_CipherSetB, XHdcp1x_CipherSetK, XHdcp1x_CipherSetRemoteKsv.
XHdcp1x_CipherXorInProgress
This queries a cipher to determine if the XOR (encryption) function is currently in progress.
InstancePtr is the instance to query. Truth value indicating in progress (TRUE) or not (FALSE). None.
Referenced by XHdcp1x_CipherEnableEncryption, XHdcp1x_CipherGetEncryption.
XHdcp1x_CipherLocalKsvReady
This queries a cipher to determine if the local KSV is ready to read.
InstancePtr is the instance to query. Truth value indicating ready (TRUE) or not (FALSE). None.
Referenced by XHdcp1x_CipherGetLocalKsv.
XHdcp1x_CipherKmReady
This queries a cipher to determine if the Km value is ready.
InstancePtr is the instance to query. Truth value indicating ready (TRUE) or not (FALSE). None.
Referenced by XHdcp1x_CipherSetRemoteKsv.
XHdcp1x_IsDP
This macro checks if a core supports the Display Port protocol.
InstancePtr is a pointer to the XHdcp1x core instance. Truth value indicating DP (TRUE) or not (FALSE)
Referenced by XHdcp1x_CipherInit, XHdcp1x_CipherSetLinkStateCheck, XHdcp1x_SelfTest.
XHdcp1x_IsHDMI
This macro checks if a core supports the HDMI protocol.
InstancePtr is a pointer to the XHdcp1x core instance. Truth value indicating HDMI (TRUE) or not (FALSE)
Referenced by XHdcp1x_CipherDisableEncryption, XHdcp1x_CipherSetMode, XHdcp1x_CipherSetNumLanes, XHdcp1x_CipherSetRiUpdate, XHdcp1x_SelfTest.
XHdcp1x_IsRX
This macro checks if a core supports the receive direction.
InstancePtr is a pointer to the XHdcp1x core instance. Truth value indicating receive (TRUE) or not (FALSE)
Referenced by XHdcp1x_CipherDisableEncryption, XHdcp1x_CipherEnable, XHdcp1x_CipherEnableEncryption, XHdcp1x_CipherSetLinkStateCheck, XHdcp1x_SelfTest.
XHdcp1x_IsTX
This macro checks if a core supports the transmit direction.
InstancePtr is a pointer to the XHdcp1x core instance. Truth value indicating transmit (TRUE) or not (FALSE)
Referenced by XHdcp1x_SelfTest.
XHDCP1X_PLATFORM_H
< Prevent circular inclusions by using protection macros
XHDCP1X_PORT_H
< Prevent circular inclusions by using protection macros
XHDCP1X_PORT_UINT_TO_BUF
This macro converts from an unsigned integer to a little endian formatted buffer.
buf the buffer to write to Value the unsigned integer to convert numbits the number of bits within the unsigned integer to use None. The value of the "Value" parameter is destroyed by a call to this macro
XHDCP1X_PORT_BUF_TO_UINT
This macro converts from a little endian formatted buffer to an unsigned integer value.
Value the unsigned integer to write buf the buffer to convert numbits the number of bits within the buffer to use None. None.
Referenced by XHdcp1x_TxGetTopologyBKSV.
XHDCP1X_PORT_BSET_IN_BUF
This macro sets a bit within a little endian formatted buffer.
buf the buffer to write to bitnum the bit to set None. None.
XHDCP1X_PORT_BCLR_IN_BUF
This macro clears a bit within a little endian formatted buffer.
buf the buffer to write to bitnum the bit to clear None. None.
XHDCP1X_PORT_BTST_IN_BUF
This macro tests a bit within a little endian formatted buffer.
buf the buffer containing the bit to test bitnum the bit to test None. None.
XHDCP1X_PORT_DP_H
< Prevent circular inclusions by using protection macros
XHDCP1X_PORT_OFFSET_BKSV
These constants specify the offsets for the various fields and/or attributes within the hdcp port.
Bksv Offset
Referenced by XHdcp1x_TxGetTopologyBKSV.
XHDCP1X_PORT_OFFSET_RO
R0' Offset.
XHDCP1X_PORT_OFFSET_AKSV
Aksv Offset.
XHDCP1X_PORT_OFFSET_AN
An Offset.
XHDCP1X_PORT_OFFSET_VH0
V'.H0 Offset.
XHDCP1X_PORT_OFFSET_VH1
V'.H1 Offset.
XHDCP1X_PORT_OFFSET_VH2
V'.H2 Offset.
XHDCP1X_PORT_OFFSET_VH3
V'.H3 Offset.
XHDCP1X_PORT_OFFSET_VH4
V'.H4 Offset.
XHDCP1X_PORT_OFFSET_BCAPS
Bcaps Offset.
XHDCP1X_PORT_OFFSET_BSTATUS
Bstatus Offset.
Referenced by XHdcp1x_RxSetHdmiMode, XHdcp1x_RxSetTopologyMaxCascadeExceeded, XHdcp1x_RxSetTopologyMaxDevsExceeded, XHdcp1x_TxGetTopologyMaxCascadeExceeded, XHdcp1x_TxGetTopologyMaxDevsExceeded.
XHDCP1X_PORT_OFFSET_BINFO
Binfo Offset.
Referenced by XHdcp1x_RxSetTopologyMaxCascadeExceeded, XHdcp1x_RxSetTopologyMaxDevsExceeded, XHdcp1x_TxGetTopologyMaxCascadeExceeded, XHdcp1x_TxGetTopologyMaxDevsExceeded.
XHDCP1X_PORT_OFFSET_KSVFIFO
KSV FIFO Offset.
XHDCP1X_PORT_OFFSET_AINFO
Ainfo Offset.
XHDCP1X_PORT_OFFSET_DBG
Debug Space Offset.
XHDCP1X_PORT_HDCP_RESET_KSV
KSV FIFO Read pointer reset Offset.
XHDCP1X_PORT_SIZE_BKSV
These constants specify the sizes for the various fields and/or attributes within the hdcp port.
Bksv Size
Referenced by XHdcp1x_RxSetTopologyKSVList, XHdcp1x_TxGetTopologyBKSV.
XHDCP1X_PORT_SIZE_RO
R0' Size.
XHDCP1X_PORT_SIZE_AKSV
Aksv Size.
XHDCP1X_PORT_SIZE_AN
An Size.
XHDCP1X_PORT_SIZE_VH0
V'.H0 Size.
XHDCP1X_PORT_SIZE_VH1
V'.H1 Size.
XHDCP1X_PORT_SIZE_VH2
V'.H2 Size.
XHDCP1X_PORT_SIZE_VH3
V'.H3 Size.
XHDCP1X_PORT_SIZE_VH4
V'.H4 Size.
XHDCP1X_PORT_SIZE_BCAPS
Bcaps Size.
XHDCP1X_PORT_SIZE_BSTATUS
Bstatus Size.
Referenced by XHdcp1x_RxSetHdmiMode, XHdcp1x_RxSetTopologyMaxCascadeExceeded, XHdcp1x_RxSetTopologyMaxDevsExceeded, XHdcp1x_TxGetTopologyMaxCascadeExceeded, XHdcp1x_TxGetTopologyMaxDevsExceeded.
XHDCP1X_PORT_SIZE_BINFO
Binfo Size.
Referenced by XHdcp1x_RxSetTopologyMaxCascadeExceeded, XHdcp1x_RxSetTopologyMaxDevsExceeded, XHdcp1x_TxGetTopologyMaxCascadeExceeded, XHdcp1x_TxGetTopologyMaxDevsExceeded.
XHDCP1X_PORT_SIZE_KSVFIFO
KSV FIFO Size.
XHDCP1X_PORT_SIZE_AINFO
Ainfo Offset.
XHDCP1X_PORT_SIZE_DBG
Debug Space Size.
XHDCP1X_PORT_SIZE_HDCP_RESET_KSV
KSV FIFO pointer reset Size.
XHDCP1X_PORT_BIT_BSTATUS_READY
These constants specify the bit definitions within the various fields and/or attributes within the hdcp port.
BStatus Ready Mask
XHDCP1X_PORT_BIT_BSTATUS_RO_AVAILABLE
BStatus Ro available Mask.
XHDCP1X_PORT_BIT_BSTATUS_LINK_FAILURE
BStatus Link Failure Mask.
XHDCP1X_PORT_BIT_BSTATUS_REAUTH_REQUEST
BStatus Reauth Request Mask.
XHDCP1X_PORT_BIT_BCAPS_HDCP_CAPABLE
BCaps HDCP Capable Mask.
XHDCP1X_PORT_BIT_BCAPS_REPEATER
BCaps HDCP Repeater Mask.
XHDCP1X_PORT_BIT_AINFO_REAUTH_ENABLE_IRQ
Ainfo Reauth Enable Mask.
XHDCP1X_PORT_HDCP_RESET_KSV_RST
KSV FIFO pointer Reset Mask.
XHDCP1X_PORT_BINFO_BIT_DEV_CNT_ERR
BInfo Device Count Error Mask.
Referenced by XHdcp1x_TxGetTopologyMaxDevsExceeded.
XHDCP1X_PORT_BINFO_BIT_DEV_CNT_NO_ERR
BInfo Device Count for No Error Mask.
XHDCP1X_PORT_BINFO_DEV_CNT_MASK
BInfo Device Count Error Mask.
XHDCP1X_PORT_BINFO_BIT_DEPTH_ERR
BInfo Depth Error Mask.
Referenced by XHdcp1x_TxGetTopologyMaxCascadeExceeded.
XHDCP1X_PORT_BINFO_BIT_DEPTH_NO_ERR
BInfo Depth Error for No Error Mask.
XHDCP1X_PORT_BINFO_DEV_CNT_ERR_SHIFT
BStatus Device Count Error Shift Mask.
Referenced by XHdcp1x_RxSetTopologyMaxDevsExceeded.
XHDCP1X_PORT_BINFO_DEPTH_ERR_SHIFT
BStatus Depth Error Shift Mask.
Referenced by XHdcp1x_RxSetTopologyMaxCascadeExceeded.
XHDCP1X_PORT_BINFO_DEPTH_SHIFT
BInfo Device Count Error Mask.
XHDCP1X_PORT_DPCD_BASE
This constant defines the base address of the hdcp port within the DPCD address space.
Base Addr in DPCD
XPAR_XHDCP_NUM_INSTANCES
XPAR_XDPTXSS_NUM_INSTANCES
XPAR_XDPRXSS_NUM_INSTANCES
XPAR_XHDCP_NUM_INSTANCES
XPAR_XDPTXSS_NUM_INSTANCES
XPAR_XDPRXSS_NUM_INSTANCES
XHDCP1X_PORT_HDMI_H
< Prevent circular inclusions by using protection macros
XHDCP1X_PORT_OFFSET_BKSV
These constants specify the offsets for the various fields and/or attributes within the hdcp port.
Bksv Offset
XHDCP1X_PORT_OFFSET_RO
Ri'/Ro' Offset.
XHDCP1X_PORT_OFFSET_PJ
Pj' Offset.
XHDCP1X_PORT_OFFSET_AKSV
Aksv Offset.
XHDCP1X_PORT_OFFSET_AINFO
Ainfo Offset.
XHDCP1X_PORT_OFFSET_AN
An Offset.
XHDCP1X_PORT_OFFSET_VH0
V'.H0 Offset.
XHDCP1X_PORT_OFFSET_VH1
V'.H1 Offset.
XHDCP1X_PORT_OFFSET_VH2
V'.H2 Offset.
XHDCP1X_PORT_OFFSET_VH3
V'.H3 Offset.
XHDCP1X_PORT_OFFSET_VH4
V'.H4 Offset.
XHDCP1X_PORT_OFFSET_BCAPS
Bcaps Offset.
XHDCP1X_PORT_OFFSET_BSTATUS
Bstatus Offset.
XHDCP1X_PORT_OFFSET_KSVFIFO
KSV FIFO Offset.
XHDCP1X_PORT_OFFSET_DBG
Debug Space Offset.
XHDCP1X_PORT_SIZE_BKSV
These constants specify the sizes for the various fields and/or attributes within the hdcp port.
Bksv Size
XHDCP1X_PORT_SIZE_RO
Ri' Size.
XHDCP1X_PORT_SIZE_PJ
Pj' Size.
XHDCP1X_PORT_SIZE_AKSV
Aksv Size.
XHDCP1X_PORT_SIZE_AINFO
Ainfo Size.
XHDCP1X_PORT_SIZE_AN
An Size.
XHDCP1X_PORT_SIZE_VH0
V'.H0 Size.
XHDCP1X_PORT_SIZE_VH1
V'.H1 Size.
XHDCP1X_PORT_SIZE_VH2
V'.H2 Size.
XHDCP1X_PORT_SIZE_VH3
V'.H3 Size.
XHDCP1X_PORT_SIZE_VH4
V'.H4 Size.
XHDCP1X_PORT_SIZE_BCAPS
Bcaps Size.
XHDCP1X_PORT_SIZE_BSTATUS
Bstatus Size.
XHDCP1X_PORT_SIZE_KSVFIFO
KSV FIFO Size.
XHDCP1X_PORT_SIZE_DBG
Debug Space Size.
XHDCP1X_PORT_BIT_BSTATUS_HDMI_MODE
These constants specify the bit definitions within the various fields and/or attributes within the hdcp port.
BStatus HDMI Mode Mask
Referenced by XHdcp1x_RxSetHdmiMode.
XHDCP1X_PORT_BIT_BCAPS_FAST_REAUTH
BCaps Fast Reauth Mask.
XHDCP1X_PORT_BIT_BCAPS_1d1_FEATURES
BCaps HDCP 1.1 Features Support Mask.
XHDCP1X_PORT_BIT_BCAPS_FAST
BCaps Fast Transfers Mask.
XHDCP1X_PORT_BIT_BCAPS_READY
BCaps KSV FIFO Ready bit Mask.
XHDCP1X_PORT_BIT_BCAPS_REPEATER
BCaps Repeater Capable Mask.
XHDCP1X_PORT_BIT_BCAPS_HDMI
BCaps HDMI Supported Mask.
XHDCP1X_PORT_BIT_AINFO_ENABLE_1d1_FEATURES
AInfo Enable 1.1 Features.
XHDCP1X_PORT_BSTATUS_BIT_DEV_CNT_ERR
BStatus Device Count Error Mask.
Referenced by XHdcp1x_TxGetTopologyMaxDevsExceeded.
XHDCP1X_PORT_BSTATUS_BIT_DEV_CNT_NO_ERR
BStatus Device Count for No Error Mask.
XHDCP1X_PORT_BSTATUS_DEV_CNT_MASK
BStatus Device Count Error Mask.
XHDCP1X_PORT_BSTATUS_BIT_DEPTH_ERR
BStatus Depth Error Mask.
Referenced by XHdcp1x_TxGetTopologyMaxCascadeExceeded.
XHDCP1X_PORT_BSTATUS_BIT_DEPTH_NO_ERR
BStatus Depth Error for No Error Mask.
XHDCP1X_PORT_BSTATUS_DEV_CNT_ERR_SHIFT
BStatus Device Count Error Shift Mask.
Referenced by XHdcp1x_RxSetTopologyMaxDevsExceeded.
XHDCP1X_PORT_BSTATUS_DEPTH_ERR_SHIFT
BStatus Depth Error Shift Mask.
Referenced by XHdcp1x_RxSetTopologyMaxCascadeExceeded.
XHDCP1X_PORT_BSTATUS_DEPTH_SHIFT
BStatus Device Count Error Mask.
XHDCP1X_PORT_PRIMARY_I2C_ADDR
This constant defines the i2c address of the hdcp port.
I2C Addr Primary Link
XHDCP1X_PORT_SECONDARY_I2C_ADDR
I2C Addr Secondary Link.
XVPHY_FLAG_PHY_UP
Flag to track physical state.
XVPHY_TMO_5MS
Timeout value for 5ms.
XVPHY_TMO_100MS
Timeout value for 100ms.
XVPHY_TMO_1SECOND
Timeout value for 1s.
XHDCP1X_RX_H
< Prevent circular inclusions by using protection macros
XVPHY_FLAG_PHY_UP
Flag to track physical state.
XVPHY_FLAG_IS_REPEATER
Flag to track repeater state.
XVPHY_TMO_5MS
Timeout value for 5ms.
XVPHY_TMO_100MS
Timeout value for 100ms.
XVPHY_TMO_1SECOND
Timeout value for 1s.
XHDCP1X_MAX_BCAPS_RDY_POLL_CNT
Max times to poll on BCaps Ready bit at 100ms interval.
XHDCP1X_TX_H
< Prevent circular inclusions by using protection macros