xhdcp1x_cipher.h
XHdcp1x_CipherHandlerType
XHdcp1x_CipherRequestType
XHDCP1X_CIPHER_H
< Prevent circular inclusions by using protection macros
HDCP1X_CIPHER_BIT_REPEATER_ENABLE
Bit in the cipher Bz register to indicate Repeater.
void XHdcp1x_CipherInit(XHdcp1x *InstancePtr)
This function initializes an HDCP cipher.
InstancePtr is the device to initialize. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_CONTROL_NUM_LANES, XHDCP1X_CIPHER_BITMASK_CONTROL_RESET, XHDCP1X_CIPHER_BITMASK_CONTROL_UPDATE, XHDCP1X_CIPHER_REG_CONTROL, XHDCP1X_CIPHER_REG_INTERRUPT_MASK, XHDCP1X_CIPHER_REG_INTERRUPT_STATUS, XHdcp1x_IsDP, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
Referenced by XHdcp1x_CfgInitialize.
int XHdcp1x_CipherSetCallback(XHdcp1x *InstancePtr, u32 HandlerType, XHdcp1x_Callback CallbackFunc, void *CallbackRef)
This function installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function Type ----------------------------------- ----------------------------------- (XHDCP1X_CIPHER_HANDLER_LINK_FAILURE) LinkFailCallback (XHDCP1X_CIPHER_HANDLER_Ri_UPDATE) RiUpdateCallback InstancePtr is a pointer to the HDCP cipher core instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XHdcp1x::Cipher, XHdcp1x_Cipher::IsLinkFailCallbackSet, XHdcp1x_Cipher::IsRiUpdateCallbackSet, XHdcp1x_Cipher::LinkFailCallback, XHdcp1x_Cipher::LinkFailRef, XHdcp1x_Cipher::RiUpdateCallback, XHdcp1x_Cipher::RiUpdateRef.
int XHdcp1x_CipherSetLinkStateCheck(XHdcp1x *InstancePtr, int IsEnabled)
This function enables/disables the reporting of link check state changes.
InstancePtr is the cipher core instance. IsEnabled enables/disables link state change notifications. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_INTERRUPT_LINK_FAIL, XHDCP1X_CIPHER_REG_INTERRUPT_MASK, XHDCP1X_CIPHER_REG_INTERRUPT_STATUS, XHdcp1x_IsDP, XHdcp1x_IsRX, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
int XHdcp1x_CipherIsLinkUp(const XHdcp1x *InstancePtr)
This function queries the link state of a cipher device.
InstancePtr is the device to query. Truth value. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_INTERRUPT_LINK_FAIL, XHDCP1X_CIPHER_REG_STATUS, XHdcp1x_CipherIsEnabled, XHdcp1x_ReadReg.
int XHdcp1x_CipherSetRiUpdate(XHdcp1x *InstancePtr, int IsEnabled)
This function enables/disables the reporting of Ri update notifications.
InstancePtr is the cipher core instance. IsEnabled enables/disables Ri update notifications. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_INTERRUPT_Ri_UPDATE, XHDCP1X_CIPHER_REG_INTERRUPT_MASK, XHDCP1X_CIPHER_REG_INTERRUPT_STATUS, XHdcp1x_IsHDMI, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
int XHdcp1x_CipherEnable(XHdcp1x *InstancePtr)
This function enables a HDCP cipher.
InstancePtr is the device to enable. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_CIPHER_CONTROL_XOR_ENABLE, XHDCP1X_CIPHER_BITMASK_CONTROL_ENABLE, XHDCP1X_CIPHER_BITMASK_CONTROL_UPDATE, XHDCP1X_CIPHER_REG_CIPHER_CONTROL, XHDCP1X_CIPHER_REG_CONTROL, XHDCP1X_CIPHER_REG_ENCRYPT_ENABLE_H, XHDCP1X_CIPHER_REG_ENCRYPT_ENABLE_L, XHdcp1x_CipherIsEnabled, XHdcp1x_IsRX, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
int XHdcp1x_CipherDisable(XHdcp1x *InstancePtr)
This function disables a HDCP cipher.
InstancePtr is the device to disable. XST_SUCCESS if successful. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_CIPHER_CONTROL_XOR_ENABLE, XHDCP1X_CIPHER_BITMASK_CONTROL_ENABLE, XHDCP1X_CIPHER_BITMASK_CONTROL_UPDATE, XHDCP1X_CIPHER_REG_CIPHER_CONTROL, XHDCP1X_CIPHER_REG_CONTROL, XHDCP1X_CIPHER_REG_ENCRYPT_ENABLE_H, XHDCP1X_CIPHER_REG_ENCRYPT_ENABLE_L, XHDCP1X_CIPHER_REG_INTERRUPT_MASK, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
int XHdcp1x_CipherSetKeySelect(XHdcp1x *InstancePtr, u8 KeySelect)
This function configures the key selection value.
InstancePtr is the device to configure. KeySelect is the desired key select value. XST_SUCCESS if successful. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_KEYMGMT_CONTROL_SET_SELECT, XHDCP1X_CIPHER_REG_KEYMGMT_CONTROL, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
Referenced by XHdcp1x_SetKeySelect.
int XHdcp1x_CipherDoRequest(XHdcp1x *InstancePtr, XHdcp1x_CipherRequestType Request)
This function initiates a request within the HDCP cipher.
InstancePtr is the device to submit the request to. Request is the request to submit. XST_SUCCESS if successful.XST_NOT_ENABLE if the core is disabled.XST_DEVICE_BUSY if the core is busy. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_CIPHER_CONTROL_REQUEST, XHDCP1X_CIPHER_BITMASK_CIPHER_STATUS_REQUEST_IN_PROG, XHDCP1X_CIPHER_BITMASK_CONTROL_UPDATE, XHDCP1X_CIPHER_REG_CIPHER_CONTROL, XHDCP1X_CIPHER_REG_CIPHER_STATUS, XHDCP1X_CIPHER_REG_CONTROL, XHDCP1X_CIPHER_VALUE_CIPHER_CONTROL_REQUEST_BLOCK, XHdcp1x_CipherIsEnabled, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
int XHdcp1x_CipherIsRequestComplete(const XHdcp1x *InstancePtr)
This function queries the progress of the current request.
InstancePtr is the device to query. Truth value. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_CIPHER_STATUS_REQUEST_IN_PROG, XHDCP1X_CIPHER_REG_CIPHER_STATUS, XHdcp1x_ReadReg.
u32 XHdcp1x_CipherGetNumLanes(const XHdcp1x *InstancePtr)
This function retrieves the current number of lanes of the HDCP cipher.
InstancePtr is the device to query. The current number of lanes. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_CONTROL_NUM_LANES, XHDCP1X_CIPHER_REG_CONTROL, XHdcp1x_CipherIsEnabled, XHdcp1x_ReadReg.
int XHdcp1x_CipherSetNumLanes(XHdcp1x *InstancePtr, u32 NumLanes)
This function configures the number of lanes of the HDCP cipher.
InstancePtr is the device to configure. NumLanes is the number of lanes to configure. XST_SUCCESS if successful. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_CONTROL_NUM_LANES, XHDCP1X_CIPHER_REG_CONTROL, XHdcp1x_IsHDMI, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
Referenced by XHdcp1x_RxSetLaneCount, XHdcp1x_TxSetLaneCount.
int XHdcp1x_CipherSetMode(XHdcp1x *InstancePtr, u32 mode)
This function configures the Mode of the HDCP cipher to MST/ SST.
InstancePtr is the device to configure. mode determines MST/ SST configuration. XST_SUCCESS if successful. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_MODE, XHDCP1X_CIPHER_REG_CONTROL, XHdcp1x_IsHDMI, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
Referenced by XHdcp1x_TxSetMSTMode.
u64 XHdcp1x_CipherGetEncryption(const XHdcp1x *InstancePtr)
This function retrieves the current encryption stream map.
InstancePtr is the device to query. The current encryption stream map. In the case of the receiver version of this core, the XOR in progress bit needs to be checked as well as the encryption map to fully determine if encryption is enabled for the SST case. This is the reason for the additional check in this code.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_REG_ENCRYPT_ENABLE_H, XHDCP1X_CIPHER_REG_ENCRYPT_ENABLE_L, XHdcp1x_CipherIsEnabled, XHdcp1x_CipherXorInProgress, XHdcp1x_ReadReg.
Referenced by XHdcp1x_RxGetEncryption.
int XHdcp1x_CipherEnableEncryption(XHdcp1x *InstancePtr, u64 StreamMap)
This function enables encryption on a set of streams.
InstancePtr is the device to configure. StreamMap is the bit map of streams to enable encryption on. XST_SUCCESS if successful.XST_NOT_ENABLE if the core is not enabled.XST_FAILURE otherwise. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_CIPHER_CONTROL_XOR_ENABLE, XHDCP1X_CIPHER_BITMASK_CONTROL_UPDATE, XHDCP1X_CIPHER_REG_CIPHER_CONTROL, XHDCP1X_CIPHER_REG_CONTROL, XHDCP1X_CIPHER_REG_ENCRYPT_ENABLE_H, XHDCP1X_CIPHER_REG_ENCRYPT_ENABLE_L, XHdcp1x_CipherIsEnabled, XHdcp1x_CipherXorInProgress, XHdcp1x_IsRX, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
int XHdcp1x_CipherDisableEncryption(XHdcp1x *InstancePtr, u64 StreamMap)
This function disables encryption on a set of streams.
InstancePtr is the device to configure. StreamMap is the bit map of streams to disable encryption on. XST_SUCCESS if successful.XST_NOT_ENABLE if the core is not enabled.XST_FAILURE otherwise. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_CIPHER_CONTROL_XOR_ENABLE, XHDCP1X_CIPHER_BITMASK_CONTROL_UPDATE, XHDCP1X_CIPHER_REG_CIPHER_CONTROL, XHDCP1X_CIPHER_REG_CONTROL, XHDCP1X_CIPHER_REG_ENCRYPT_ENABLE_H, XHDCP1X_CIPHER_REG_ENCRYPT_ENABLE_L, XHdcp1x_CipherIsEnabled, XHdcp1x_IsHDMI, XHdcp1x_IsRX, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
Referenced by XHdcp1x_TxDisableEncryption.
u64 XHdcp1x_CipherGetLocalKsv(const XHdcp1x *InstancePtr)
This function reads the local KSV value from the cipher.
InstancePtr is the device to query. The local KSV value. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_KEYMGMT_CONTROL_ABORT_Km, XHDCP1X_CIPHER_BITMASK_KEYMGMT_CONTROL_LOCAL_KSV, XHDCP1X_CIPHER_BITMASK_KEYMGMT_STATUS_KSV_READY, XHDCP1X_CIPHER_REG_KEYMGMT_CONTROL, XHDCP1X_CIPHER_REG_KEYMGMT_STATUS, XHDCP1X_CIPHER_REG_KSV_LOCAL_H, XHDCP1X_CIPHER_REG_KSV_LOCAL_L, XHdcp1x_CipherIsEnabled, XHdcp1x_CipherLocalKsvReady, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
Referenced by XHdcp1x_CipherSetRemoteKsv, XHdcp1x_RxInfo, XHdcp1x_TxInfo.
u64 XHdcp1x_CipherGetRemoteKsv(const XHdcp1x *InstancePtr)
This function reads the remote KSV value from the cipher.
InstancePtr is the device to query. The remote KSV value. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_REG_KSV_REMOTE_H, XHDCP1X_CIPHER_REG_KSV_REMOTE_L, XHdcp1x_ReadReg.
int XHdcp1x_CipherSetRemoteKsv(XHdcp1x *InstancePtr, u64 Ksv)
This function writes the remote KSV value to the cipher.
InstancePtr is the device to write to. Ksv is the remote KSV value to write. XST_SUCCESS if successful.XST_NOT_ENABLED otherwise. Whenever this function is called, the underlying driver will initiate the calculation of the Km value and wait for it to complete.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_CONTROL_UPDATE, XHDCP1X_CIPHER_BITMASK_KEYMGMT_CONTROL_BEGIN_Km, XHDCP1X_CIPHER_REG_CONTROL, XHDCP1X_CIPHER_REG_KEYMGMT_CONTROL, XHDCP1X_CIPHER_REG_KSV_REMOTE_H, XHDCP1X_CIPHER_REG_KSV_REMOTE_L, XHdcp1x_CipherGetLocalKsv, XHdcp1x_CipherIsEnabled, XHdcp1x_CipherKmReady, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
int XHdcp1x_CipherGetB(const XHdcp1x *InstancePtr, u32 *X, u32 *Y, u32 *Z)
This function reads the contents of the B register in BM0.
InstancePtr is the device to query. X is to be loaded with the contents of Bx. Y is to be loaded with the contents of By. Z is to be loaded with the contents of Bz. XST_SUCCESS if successful.XST_NOT_ENABLED otherwise. A NULL pointer can be passed in any of X, Y and Z. If so, then this portion of the B register is not returned to the caller.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_REG_CIPHER_Bx, XHDCP1X_CIPHER_REG_CIPHER_By, XHDCP1X_CIPHER_REG_CIPHER_Bz, XHdcp1x_CipherIsEnabled, XHdcp1x_ReadReg.
int XHdcp1x_CipherSetB(XHdcp1x *InstancePtr, u32 X, u32 Y, u32 Z)
This function writes the contents of the B register in BM0.
InstancePtr is the device to write to. X is the value to be written to Bx. Y is the value to be written to By. Z is the value to be written to Bz. XST_SUCCESS if successful.XST_NOT_ENABLED otherwise. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_CONTROL_UPDATE, XHDCP1X_CIPHER_REG_CIPHER_Bx, XHDCP1X_CIPHER_REG_CIPHER_By, XHDCP1X_CIPHER_REG_CIPHER_Bz, XHDCP1X_CIPHER_REG_CONTROL, XHdcp1x_CipherIsEnabled, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
int XHdcp1x_CipherGetK(const XHdcp1x *InstancePtr, u32 *X, u32 *Y, u32 *Z)
This function reads the contents of the K register in BM0.
InstancePtr is the device to query. X is to be loaded with the contents of Kx. Y is to be loaded with the contents of Ky. Z is to be loaded with the contents of Kz. XST_SUCCESS if successful.XST_NOT_ENABLED otherwise. A NULL pointer can be passed in any of X, Y and Z. If so, then this portion of the K register is not returned to the caller.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_REG_CIPHER_Kx, XHDCP1X_CIPHER_REG_CIPHER_Ky, XHDCP1X_CIPHER_REG_CIPHER_Kz, XHdcp1x_CipherIsEnabled, XHdcp1x_ReadReg.
int XHdcp1x_CipherSetK(XHdcp1x *InstancePtr, u32 X, u32 Y, u32 Z)
This function writes the contents of the K register in BM0.
InstancePtr is the device to write to. X is the value to be written to Kx. Y is the value to be written to Ky. Z is the value to be written to Kz. XST_SUCCESS if successful.XST_NOT_ENABLED otherwise. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_CONTROL_UPDATE, XHDCP1X_CIPHER_REG_CIPHER_Kx, XHDCP1X_CIPHER_REG_CIPHER_Ky, XHDCP1X_CIPHER_REG_CIPHER_Kz, XHDCP1X_CIPHER_REG_CONTROL, XHdcp1x_CipherIsEnabled, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
u64 XHdcp1x_CipherGetMi(const XHdcp1x *InstancePtr)
This function reads the contents of the Mi/An register of BM0.
InstancePtr is the device to query. The contents of the register. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_REG_CIPHER_Mi_H, XHDCP1X_CIPHER_REG_CIPHER_Mi_L, XHdcp1x_CipherIsEnabled, XHdcp1x_ReadReg.
u16 XHdcp1x_CipherGetRi(const XHdcp1x *InstancePtr)
This function reads the contents of the Ri register of BM0.
InstancePtr is the device to query. The contents of the register. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_REG_CIPHER_Ri, XHdcp1x_CipherIsEnabled, XHdcp1x_ReadReg.
u64 XHdcp1x_CipherGetMo(const XHdcp1x *InstancePtr)
This function reads the contents of the Mo register of the device.
InstancePtr is the device to query. The contents of the Mo register. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_REG_CIPHER_Mo_H, XHDCP1X_CIPHER_REG_CIPHER_Mo_L, XHdcp1x_CipherIsEnabled, XHdcp1x_ReadReg.
u16 XHdcp1x_CipherGetRo(const XHdcp1x *InstancePtr)
This function reads the contents of the Ro register of the device.
InstancePtr is the device to query. The contents of the Ro register. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_REG_CIPHER_Ro, XHdcp1x_CipherIsEnabled, XHdcp1x_ReadReg.
u32 XHdcp1x_CipherGetVersion(const XHdcp1x *InstancePtr)
This function reads the version of the HDCP cipher core.
InstancePtr is the device to query. The version of the HDCP cipher device. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_REG_VERSION, XHdcp1x_ReadReg.
Referenced by XHdcp1x_GetVersion, XHdcp1x_RxInfo, XHdcp1x_TxInfo.
void XHdcp1x_CipherHandleInterrupt(void *InstancePtr)
This function is the interrupt handler for the cipher core driver.
InstancePtr is the cipher core instance. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Cipher, XHdcp1x::Config, XHdcp1x_CipherStats::IntCount, XHdcp1x_Cipher::IsLinkFailCallbackSet, XHdcp1x::IsReady, XHdcp1x_Cipher::IsRiUpdateCallbackSet, XHdcp1x_Cipher::LinkFailCallback, XHdcp1x_Cipher::LinkFailRef, XHdcp1x_Cipher::RiUpdateCallback, XHdcp1x_Cipher::RiUpdateRef, XHdcp1x_Cipher::Stats, XHDCP1X_CIPHER_BITMASK_INTERRUPT_LINK_FAIL, XHDCP1X_CIPHER_BITMASK_INTERRUPT_Ri_UPDATE, XHDCP1X_CIPHER_REG_INTERRUPT_STATUS, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
Referenced by XHdcp1x_CipherIntrHandler.
void XHdcp1x_CipherEnableBlank(XHdcp1x *InstancePtr)
This function sets the cipher blank value to 0x0000FF (blue), and sets the cipher blank select to TRUE.
InstancePtr is the device to query. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_BLANK_SEL, XHDCP1X_CIPHER_BITMASK_BLANK_VALUE, XHDCP1X_CIPHER_REG_BLANK_SEL, XHDCP1X_CIPHER_REG_BLANK_VALUE, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
Referenced by XHdcp1x_TxEnableBlank.
void XHdcp1x_CipherDisableBlank(XHdcp1x *InstancePtr)
This function sets the cipher blank select to FALSE.
InstancePtr is the device to query. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHDCP1X_CIPHER_BITMASK_BLANK_SEL, XHDCP1X_CIPHER_REG_BLANK_SEL, XHdcp1x_ReadReg, XHdcp1x_WriteReg.
Referenced by XHdcp1x_TxDisableBlank.