xhdcp1x_tx.c
XVPHY_FLAG_PHY_UP
Flag to track physical state.
XVPHY_FLAG_IS_REPEATER
Flag to track repeater state.
XVPHY_TMO_5MS
Timeout value for 5ms.
XVPHY_TMO_100MS
Timeout value for 100ms.
XVPHY_TMO_1SECOND
Timeout value for 1s.
XHDCP1X_MAX_BCAPS_RDY_POLL_CNT
Max times to poll on BCaps Ready bit at 100ms interval.
XHdcp1x_EventType
XHdcp1x_StateType
static void XHdcp1x_TxDebugLog(const XHdcp1x *InstancePtr, const char *LogMsg)
This function logs a debug message on behalf of a handler state machine.
InstancePtr is the receiver instance. LogMsg is the message to log. None.
static void XHdcp1x_TxPostEvent(XHdcp1x *InstancePtr, XHdcp1x_EventType Event)
This function posts an event to a state machine.
InstancePtr is the transmitter instance. Event is the event to post. None.
static void XHdcp1x_TxStartTimer(XHdcp1x *InstancePtr, u16 TimeoutInMs)
This function starts a state machine's timer.
InstancePtr is the state machine. TimeoutInMs is the timeout in milli-seconds. None.
static void XHdcp1x_TxStopTimer(XHdcp1x *InstancePtr)
This function stops a state machine's timer.
InstancePtr is the state machine. None.
static void XHdcp1x_TxBusyDelay(XHdcp1x *InstancePtr, u16 DelayInMs)
This function busy delays a state machine.
InstancePtr is the state machine. DelayInMs is the delay time in milli-seconds. None.
static void XHdcp1x_TxReauthenticateCallback(void *Parameter)
This function acts as the reauthentication callback for a state machine.
Parameter is the parameter specified during registration. None. None.
static void XHdcp1x_TxCheckLinkCallback(void *Parameter)
This function acts as the check link callback for a state machine.
Parameter is the parameter specified during registration. None.
static void XHdcp1x_TxSetCheckLinkState(XHdcp1x *InstancePtr, int IsEnabled)
This function sets the check link state of the handler.
InstancePtr is the HDCP state machine. IsEnabled is truth value indicating on/off. None.
static void XHdcp1x_TxEnableEncryptionState(XHdcp1x *InstancePtr)
This function enables encryption for a state machine.
InstancePtr is the HDCP state machine. None. This function inserts a 5ms delay for things to settle when encryption is actually being disabled.
static void XHdcp1x_TxDisableEncryptionState(XHdcp1x *InstancePtr)
This function disables encryption for a state machine.
InstancePtr is the HDCP state machine. None. This function inserts a 5ms delay for things to settle when encryption is actually being disabled.
static void XHdcp1x_TxEnableState(XHdcp1x *InstancePtr)
This function enables a state machine.
InstancePtr is the HDCP state machine. None. None.
static void XHdcp1x_TxDisableState(XHdcp1x *InstancePtr)
This function disables a state machine.
InstancePtr is the HDCP state machine. None. None.
static void XHdcp1x_TxCheckRxCapable(const XHdcp1x *InstancePtr, XHdcp1x_StateType *NextStatePtr)
This function checks to ensure that the remote end is HDCP capable.
InstancePtr is the HDCP state machine. NextStatePtr is the next state. None. None.
static u64 XHdcp1x_TxGenerateAn(XHdcp1x *InstancePtr)
This function generates the An from a random number generator.
InstancePtr is the HDCP state machine. A 64-bit pseudo random number (An). None.
static int XHdcp1x_TxIsKsvValid(u64 Ksv)
This function validates a KSV value as having 20 1s and 20 0s.
Ksv is the value to validate. Truth value indicating valid (TRUE) or not (FALSE). None.
static void XHdcp1x_TxExchangeKsvs(XHdcp1x *InstancePtr, XHdcp1x_StateType *NextStatePtr)
This function exchanges the ksvs between the two ends of the link.
InstancePtr is the HDCP state machine. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxStartComputations(XHdcp1x *InstancePtr, XHdcp1x_StateType *NextStatePtr)
This function initiates the computations for a state machine.
InstancePtr is the HDCP receiver state machine. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxPollForComputations(XHdcp1x *InstancePtr, XHdcp1x_StateType *NextStatePtr)
This function polls the progress of the computations for a state machine.
InstancePtr is the HDCP state machine. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxValidateRx(XHdcp1x *InstancePtr, XHdcp1x_StateType *NextStatePtr)
This function validates the attached receiver.
InstancePtr is the HDCP state machine. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxCheckLinkIntegrity(XHdcp1x *InstancePtr, XHdcp1x_StateType *NextStatePtr)
This function checks the integrity of a HDCP link.
InstancePtr is the hdcp state machine. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxTestForRepeater(XHdcp1x *InstancePtr, XHdcp1x_StateType *NextStatePtr)
This function checks the remote end to see if its a repeater.
InstancePtr is the HDCP state machine. NextStatePtr is the next state. None. The implementation of this function enables encryption when a repeater is detected downstream. The standard is ambiguous as to the handling of this specific case by this behaviour is required in order to pass the Unigraf compliance test suite.
static void XHdcp1x_TxPollForWaitForReady(XHdcp1x *InstancePtr, XHdcp1x_StateType *NextStatePtr)
This function polls a state machine in the "wait for ready" state.
InstancePtr is the hdcp state machine. NextStatePtr is the next state. None. None.
static int XHdcp1x_TxSetRepeaterInfo(XHdcp1x *InstancePtr)
This function sets the V'H0, V'H1, V'H2, V'H3, V'H4, KSVList and BInfo values in the HDCP TX HDCP Instance for Repeater validation .
InstancePtr is the transmitter instance. -XST_SUCCESS if successful. -XST_FAILURE if unsuccessful. None.
static int XHdcp1x_TxValidateKsvList(XHdcp1x *InstancePtr, u16 RepeaterInfo)
This function validates the ksv list from an attached repeater.
InstancePtr is the hdcp state machine. RepeaterInfo is the repeater information. Truth value indicating valid (TRUE) or invalid (FALSE). None.
static void XHdcp1x_TxReadKsvList(XHdcp1x *InstancePtr, XHdcp1x_StateType *NextStatePtr)
This function reads the ksv list from an attached repeater.
InstancePtr is the hdcp state machine. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxRunDisabledState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event, XHdcp1x_StateType *NextStatePtr)
This function runs the "disabled" state of the transmit state machine.
InstancePtr is the transmitter instance. Event is the event to process. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxRunDetermineRxCapableState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event, XHdcp1x_StateType *NextStatePtr)
This function runs the "determine rx capable" state of the transmit state machine.
InstancePtr is the transmitter instance. Event is the event to process. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxRunExchangeKsvsState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event, XHdcp1x_StateType *NextStatePtr)
This function runs the "exchange ksvs" state of the transmit state machine.
InstancePtr is the transmitter instance. Event is the event to process. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxRunComputationsState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event, XHdcp1x_StateType *NextStatePtr)
This function runs the "computations" state of the transmit state machine.
InstancePtr is the transmitter instance. Event is the event to process. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxRunValidateRxState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event, XHdcp1x_StateType *NextStatePtr)
This function runs the "validate-rx" state of the transmit state machine.
InstancePtr is the transmitter instance. Event is the event to process. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxRunAuthenticatedState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event, XHdcp1x_StateType *NextStatePtr)
This function runs the "authenticated" state of the transmit state machine.
InstancePtr is the transmitter instance. Event is the event to process. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxRunLinkIntegrityCheckState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event, XHdcp1x_StateType *NextStatePtr)
This function runs the "link-integrity check" state of the transmit state machine.
InstancePtr is the transmitter instance. Event is the event to process. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxRunTestForRepeaterState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event, XHdcp1x_StateType *NextStatePtr)
This function runs the "test-for-repeater" state of the transmit state machine.
InstancePtr is the transmitter instance. Event is the event to process. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxRunWaitForReadyState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event, XHdcp1x_StateType *NextStatePtr)
This function runs the "wait-for-ready" state of the transmit state machine.
InstancePtr is the transmitter instance. Event is the event to process. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxRunReadKsvListState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event, XHdcp1x_StateType *NextStatePtr)
This function runs the "read-ksv-list" state of the transmit state machine.
InstancePtr is the transmitter instance. Event is the event to process. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxRunUnauthenticatedState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event, XHdcp1x_StateType *NextStatePtr)
This function runs the "unauthenticated" state of the transmit state machine.
InstancePtr is the transmitter instance. Event is the event to process. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxRunPhysicalLayerDownState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event, XHdcp1x_StateType *NextStatePtr)
This function runs the "physical-layer-down" state of the transmit state machine.
InstancePtr is the transmitter instance. Event is the event to process. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxEnterState(XHdcp1x *InstancePtr, XHdcp1x_StateType State, XHdcp1x_StateType *NextStatePtr)
This function enters a state.
InstancePtr is the HDCP state machine. State is the state to enter. NextStatePtr is the next state. None. None.
static void XHdcp1x_TxExitState(XHdcp1x *InstancePtr, XHdcp1x_StateType State, XHdcp1x_StateType *NextStatePtr)
This function exits a state.
InstancePtr is the HDCP state machine. State is the state to exit. None. None.
static void XHdcp1x_TxDoTheState(XHdcp1x *InstancePtr, XHdcp1x_EventType Event)
This function drives a transmit state machine.
InstancePtr is the HDCP state machine. Event is the event to process. None. None.
static void XHdcp1x_TxProcessPending(XHdcp1x *InstancePtr)
This function processes the events pending on a state machine.
InstancePtr is the receiver instance. None.
static const char * XHdcp1x_TxStateToString(XHdcp1x_StateType State)
This function converts from a state to a display string.
State is the state to convert. The corresponding display string. None.
int XHdcp1x_TxSetCallback(XHdcp1x *InstancePtr, XHdcp1x_HandlerType HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs callback functions for the given HandlerType:
InstancePtr is a pointer to the HDCP core instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XHdcp1x_Tx::AuthenticatedCallback, XHdcp1x_Tx::AuthenticatedCallbackRef, XHdcp1x_Tx::DdcRead, XHdcp1x_Tx::DdcReadRef, XHdcp1x_Tx::DdcWrite, XHdcp1x_Tx::DdcWriteRef, XHdcp1x_Tx::IsAuthenticatedCallbackSet, XHdcp1x_Tx::IsDdcReadSet, XHdcp1x_Tx::IsDdcWriteSet, XHdcp1x_Tx::IsRepeaterExchangeCallbackSet, XHdcp1x_Tx::IsUnauthenticatedCallbackSet, XHdcp1x_Tx::RepeaterExchangeCallback, XHdcp1x_Tx::RepeaterExchangeRef, XHdcp1x::Tx, XHdcp1x_Tx::UnauthenticatedCallback, XHdcp1x_Tx::UnauthenticatedCallbackRef.
Referenced by XHdcp1x_SetCallback.
void XHdcp1x_TxInit(XHdcp1x *InstancePtr)
This function initializes a transmit state machine.
InstancePtr is the receiver instance. None.
References XHdcp1x_Tx::PendingEvents, XHdcp1x::Tx.
Referenced by XHdcp1x_CfgInitialize.
int XHdcp1x_TxPoll(XHdcp1x *InstancePtr)
This function polls an HDCP interface.
InstancePtr is the transmitter instance. XST_SUCCESS if successful. None.
References XHdcp1x::IsReady.
Referenced by XHdcp1x_Poll.
int XHdcp1x_TxReset(XHdcp1x *InstancePtr)
This function resets an HDCP interface.
InstancePtr is the transmitter instance. XST_SUCCESS if successful. This function disables and then re-enables the interface.
References XHdcp1x_Tx::IsAuthReqPending, XHdcp1x::Tx.
Referenced by XHdcp1x_Reset.
int XHdcp1x_TxEnable(XHdcp1x *InstancePtr)
This function enables an HDCP interface.
InstancePtr is the transmitter instance. XST_SUCCESS if successful. None.
Referenced by XHdcp1x_Enable.
int XHdcp1x_TxDisable(XHdcp1x *InstancePtr)
This function disables an HDCP interface.
InstancePtr is the transmitter instance. XST_SUCCESS if successful. None.
Referenced by XHdcp1x_Disable.
int XHdcp1x_TxIsEnabled(const XHdcp1x *InstancePtr)
This function queries an interface to check if it is enabled.
InstancePtr is the transmitter instance. Truth value indicating is enabled (true) or not (false). None.
References XHdcp1x_Tx::CurrentState, XHdcp1x::Tx.
Referenced by XHdcp1x_IsEnabled, XHdcp1x_TxDisableEncryption.
int XHdcp1x_TxSetPhysicalState(XHdcp1x *InstancePtr, int IsUp)
This function updates the physical state of an HDCP interface.
InstancePtr is the transmitter instance. IsUp is truth value indicating the status of physical interface. XST_SUCCESS if successful. None.
Referenced by XHdcp1x_SetPhysicalState.
int XHdcp1x_TxSetLaneCount(XHdcp1x *InstancePtr, int LaneCount)
This function set the lane count of an HDCP interface.
InstancePtr is the transmitter instance. LaneCount is the number of lanes of the interface. XST_SUCCESS if successful. None.
References XHdcp1x_CipherSetNumLanes.
Referenced by XHdcp1x_SetLaneCount.
int XHdcp1x_TxSetMSTMode(XHdcp1x *InstancePtr, int mode)
This function set the MST/SST mode of an HDCP interface.
InstancePtr is the transmitter instance. mode enables MST/SST configuration. XST_SUCCESS if successful. None.
References XHdcp1x_Tx::mode, XHdcp1x::Tx, XHdcp1x_CipherSetMode.
Referenced by XHdcp1x_SetMSTMode.
int XHdcp1x_TxEnableEcfTimeslots(XHdcp1x *InstancePtr, u64 timeslots)
This function enables HDCP ECF slots.
InstancePtr is the receiver instance. timeslots is the ECF timeslots to be enabled. XST_SUCCESS if successful. None.
References XHdcp1x_SetEcfSlots.
Referenced by XHdcp1x_Enable_ECF_Slots.
int XHdcp1x_TxAuthenticate(XHdcp1x *InstancePtr)
This function initiates authentication on an interface.
InstancePtr is the transmitter instance. XST_SUCCESS if successful. None.
References XHdcp1x_Tx::IsAuthReqPending, XHdcp1x::Tx.
Referenced by XHdcp1x_Authenticate.
int XHdcp1x_TxReadDownstream(XHdcp1x *InstancePtr)
This function initiates the transmitter to read READY bit from downstream and complete second part of authentication.
InstancePtr is the transmitter instance. XST_SUCCESS if successful. None.
Referenced by XHdcp1x_ReadDownstream.
int XHdcp1x_TxIsInProgress(const XHdcp1x *InstancePtr)
This function queries an interface to check if authentication is still in progress.
InstancePtr is the transmitter instance. Truth value indicating in progress (true) or not (false). None.
References XHdcp1x_Tx::IsAuthReqPending, XHdcp1x::Tx.
Referenced by XHdcp1x_IsInProgress.
int XHdcp1x_TxIsAuthenticated(const XHdcp1x *InstancePtr)
This function queries an interface to check if its been authenticated.
InstancePtr is the transmitter instance. Truth value indicating authenticated (true) or not (false). None.
References XHdcp1x_Tx::CurrentState, XHdcp1x::Tx.
Referenced by XHdcp1x_IsAuthenticated, XHdcp1x_TxEnableEncryption.
int XHdcp1x_TxIsInComputations(const XHdcp1x *InstancePtr)
This function queries an interface to check if its in the computations state.
InstancePtr is the transmitter instance. Truth value indicating authenticated (true) or not (false). None.
References XHdcp1x_Tx::CurrentState, XHdcp1x::Tx.
Referenced by XHdcp1x_IsInComputations.
int XHdcp1x_TxIsInWaitforready(const XHdcp1x *InstancePtr)
This function queries an interface to check if its in the wait-for-ready state.
InstancePtr is the transmitter instance. Truth value indicating authenticated (true) or not (false). None.
References XHdcp1x_Tx::CurrentState, XHdcp1x::Tx.
Referenced by XHdcp1x_IsInWaitforready.
int XHdcp1x_TxIsDownstrmCapable(const XHdcp1x *InstancePtr)
This function queries the downstream device to check if the downstream device is HDCP capable.
InstancePtr is the receiver instance. Truth value indicating HDCP capability (true) or not (false). None.
References XHdcp1x_PortIsCapable.
Referenced by XHdcp1x_IsDwnstrmCapable.
u64 XHdcp1x_TxGetEncryption(const XHdcp1x *InstancePtr)
This function retrieves the current encryption stream map.
InstancePtr the transmitter instance. The current encryption stream map. None.
References XHdcp1x_Tx::EncryptionMap, XHdcp1x::Tx.
Referenced by XHdcp1x_GetEncryption.
int XHdcp1x_TxEnableEncryption(XHdcp1x *InstancePtr, u64 StreamMap)
This function enables encryption on set of streams on an HDCP interface.
InstancePtr is the transmitter instance. StreamMap is the bit map of streams to enable encryption on. XST_SUCCESS if successful. None.
References XHdcp1x_Tx::EncryptionMap, XHdcp1x::Tx, XHdcp1x_TxIsAuthenticated.
Referenced by XHdcp1x_EnableEncryption.
int XHdcp1x_TxDisableEncryption(XHdcp1x *InstancePtr, u64 StreamMap)
This function disables encryption on set of streams on an HDCP interface.
InstancePtr is the transmitter instance. StreamMap is the bit map of streams to disable encryption on. XST_SUCCESS if successful. None.
References XHdcp1x_Tx::EncryptionMap, XHdcp1x::Tx, XHdcp1x_CipherDisableEncryption, XHdcp1x_TxIsEnabled.
Referenced by XHdcp1x_DisableEncryption.
void XHdcp1x_TxSetHdmiMode(XHdcp1x *InstancePtr, u8 Value)
This set a flag that allows the hdcp1x drivers to determine if the transmitter is HDMI or DVI.
InstancePtr is the transmitter instance. Value The mode value to set (typically 1 for HDMI, 0 for DVI). None.
References XHdcp1x::Tx, XHdcp1x_Tx::TxIsHdmi, UNUSED.
Referenced by XHdcp1x_SetHdmiMode.
void XHdcp1x_TxHandleTimeout(XHdcp1x *InstancePtr)
This function handles a timeout on an HDCP interface.
InstancePtr is the transmitter instance. None.
Referenced by XHdcp1x_HandleTimeout.
int XHdcp1x_TxIsRepeater(XHdcp1x *InstancePtr)
This function returns if HDCP TX interface is connected to a downstream repeater.
InstancePtr is the transmitter instance. TRUE if Repeater.FALSE if not Repeater, None.
References XHdcp1x_PortIsRepeater.
Referenced by XHdcp1x_IsRepeater.
int XHdcp1x_TxInfo(const XHdcp1x *InstancePtr)
This function implements the debug display output for transmit instances.
InstancePtr is the receiver instance. XST_SUCCESS if successful. None.
References XHdcp1x_TxStats::AuthFailed, XHdcp1x_TxStats::AuthPassed, XHdcp1x::Cipher, XHdcp1x::Config, XHdcp1x_Tx::CurrentState, XHdcp1x_Tx::EncryptionMap, XHdcp1x_Tx::Flags, XHdcp1x_CipherStats::IntCount, XHdcp1x_PortStats::IntCount, XHdcp1x_Config::IsHDMI, XHdcp1x_TxStats::LinkCheckFailed, XHdcp1x_TxStats::LinkCheckPassed, XHdcp1x::Port, XHdcp1x_Tx::PreviousState, XHdcp1x_TxStats::ReadFailures, XHdcp1x_TxStats::ReauthRequested, XHdcp1x_Tx::StateHelper, XHdcp1x_Cipher::Stats, XHdcp1x_PortStruct::Stats, XHdcp1x_Tx::Stats, XHdcp1x::Tx, XHdcp1x_CipherGetLocalKsv, XHdcp1x_CipherGetVersion, XHDCP1X_DEBUG_PRINTF, XHdcp1x_GetDriverVersion, XHdcp1x_IsEncrypted.
Referenced by XHdcp1x_Info.
void XHdcp1x_TxEnableBlank(XHdcp1x *InstancePtr)
This function enables the blank output for the cipher.
InstancePtr is a pointer to the Hdcp1.4 core instance. None.
References XHdcp1x_CipherEnableBlank.
Referenced by XHdcp1x_EnableBlank.
void XHdcp1x_TxDisableBlank(XHdcp1x *InstancePtr)
This function disables the blank output for the cipher.
InstancePtr is a pointer to the Hdcp1.4 core instance. None.
References XHdcp1x_CipherDisableBlank.
Referenced by XHdcp1x_DisableBlank.
void XHdcp1x_TxTriggerDownstreamAuth(void *Parameter)
This function acts as the downstream authentication trigger callback for a Repeater state machine, to start the second part of authentication.
Parameter is the parameter specified during registration. None.
u8 * XHdcp1x_TxGetTopologyKSVList(XHdcp1x *InstancePtr)
This function returns the value of KSV List read in the downstream interface of the repeater topology.
InstancePtr is a pointer to the XHdcp14 core instance. TRUE if MAX_DEPTH_EXCEEDEDFALSE if not None.
References XHdcp1x_RepeaterExchange::DeviceCount, XHdcp1x_RepeaterExchange::KsvList, XHdcp1x::RepeaterValues.
Referenced by XHdcp1x_GetTopologyKSVList.
u32 XHdcp1x_TxGetTopologyDepth(XHdcp1x *InstancePtr)
This function returns the value of Depth read in the downstream interface of the repeater topology.
InstancePtr is a pointer to the XHdcp14 core instance. Value of Depth. None.
References XHdcp1x_RepeaterExchange::Depth, XHdcp1x::RepeaterValues.
Referenced by XHdcp1x_GetTopologyField.
u32 XHdcp1x_TxGetTopologyDeviceCnt(XHdcp1x *InstancePtr)
This function returns the value of Device Count read in the downstream interface of the repeater topology.
InstancePtr is a pointer to the XHdcp14 core instance. TRUE if MAX_DEPTH_EXCEEDEDFALSE if not None.
References XHdcp1x_RepeaterExchange::DeviceCount, XHdcp1x::RepeaterValues.
Referenced by XHdcp1x_GetTopologyField.
u32 XHdcp1x_TxGetTopologyMaxCascadeExceeded(XHdcp1x *InstancePtr)
This function returns the MAX_DEPTH_EXCEEDED flag in the repeater topology structure.
InstancePtr is a pointer to the XHdcp14 core instance. TRUE if MAX_DEPTH_EXCEEDEDFALSE if not None.
References XHDCP1X_PORT_BINFO_BIT_DEPTH_ERR, XHDCP1X_PORT_BSTATUS_BIT_DEPTH_ERR, XHDCP1X_PORT_OFFSET_BINFO, XHDCP1X_PORT_OFFSET_BSTATUS, XHDCP1X_PORT_SIZE_BINFO, XHDCP1X_PORT_SIZE_BSTATUS, XHdcp1x_PortRead.
Referenced by XHdcp1x_GetTopologyField.
u8 * XHdcp1x_TxGetTopologyBKSV(XHdcp1x *InstancePtr)
This function returns the value of BKSV of the device connected to the repeater downstream interface.
InstancePtr is a pointer to the XHdcp14 core instance. TRUE if MAX_DEPTH_EXCEEDEDFALSE if not None.
References XHDCP1X_PORT_BUF_TO_UINT, XHDCP1X_PORT_OFFSET_BKSV, XHDCP1X_PORT_SIZE_BKSV, XHdcp1x_PortRead.
Referenced by XHdcp1x_GetTopologyBKSV.
u32 XHdcp1x_TxGetTopologyMaxDevsExceeded(XHdcp1x *InstancePtr)
This function returns the MAX_DEVICS_EXCEEDED flag in the repeater topology structure.
InstancePtr is a pointer to the XHdcp14 core instance. TRUE if MAX_DEVICES_EXCEEDEDFALSE if not None.
References XHDCP1X_PORT_BINFO_BIT_DEV_CNT_ERR, XHDCP1X_PORT_BSTATUS_BIT_DEV_CNT_ERR, XHDCP1X_PORT_OFFSET_BINFO, XHDCP1X_PORT_OFFSET_BSTATUS, XHDCP1X_PORT_SIZE_BINFO, XHDCP1X_PORT_SIZE_BSTATUS, XHdcp1x_PortRead.
Referenced by XHdcp1x_GetTopologyField.
XHdcp1x_RepeaterExchange * XHdcp1x_TxGetTopology(XHdcp1x *InstancePtr)
This function returns a pointer to the downstream Topology structure.
InstancePtr is a pointer to the XHdcp14 core instance. A pointer to the XHdcp14 Topology structure or NULL when the topology info is invalid. None.
References XHdcp1x_Tx::CurrentState, XHdcp1x::IsRepeater, XHdcp1x::RepeaterValues, XHdcp1x::Tx.
Referenced by XHdcp1x_GetTopology.
void XHdcp1x_TxEnableEcf(XHdcp1x *InstancePtr, u64 timeslots)
This function enables HDCP ECF slots.
InstancePtr is the receiver instance. timeslots is the number of timeslots to enable ECF for. None.
References XHdcp1x_SetEcfSlots.