xhdcp1x_rx.h
XHDCP1X_RX_H
< Prevent circular inclusions by using protection macros
void XHdcp1x_RxInit(XHdcp1x *InstancePtr)
This function initializes a HDCP receiver state machine.
InstancePtr is the receiver instance. None.
References XHdcp1x_Rx::PendingEvents, XHdcp1x::Rx.
Referenced by XHdcp1x_CfgInitialize.
void XHdcp1x_RxLoadBksvToBuf(XHdcp1x *InstancePtr)
int XHdcp1x_RxSetCallback(XHdcp1x *InstancePtr, XHdcp1x_HandlerType HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs callback functions for the given HandlerType:
InstancePtr is a pointer to the HDCP core instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XHdcp1x_Rx::AuthenticatedCallback, XHdcp1x_Rx::AuthenticatedCallbackRef, XHdcp1x_Rx::DdcGetDataCallback, XHdcp1x_Rx::DdcGetDataCallbackRef, XHdcp1x_Rx::DdcSetAddressCallback, XHdcp1x_Rx::DdcSetAddressCallbackRef, XHdcp1x_Rx::DdcSetDataCallback, XHdcp1x_Rx::DdcSetDataCallbackRef, XHdcp1x_Rx::EncryptionUpdateCallback, XHdcp1x_Rx::EncryptionUpdateCallbackRef, XHdcp1x_Rx::IsAuthenticatedCallbackSet, XHdcp1x_Rx::IsDdcGetDataCallbackSet, XHdcp1x_Rx::IsDdcSetAddressCallbackSet, XHdcp1x_Rx::IsDdcSetDataCallbackSet, XHdcp1x_Rx::IsEncryptionUpdateCallbackSet, XHdcp1x_Rx::IsRepeaterDownstreamAuthCallbackSet, XHdcp1x_Rx::IsTopologyUpdateCallbackSet, XHdcp1x_Rx::IsUnauthenticatedCallbackSet, XHdcp1x_Rx::RepeaterDownstreamAuthCallback, XHdcp1x_Rx::RepeaterDownstreamAuthRef, XHdcp1x::Rx, XHdcp1x_Rx::TopologyUpdateCallback, XHdcp1x_Rx::TopologyUpdateCallbackRef, XHdcp1x_Rx::UnauthenticatedCallback, XHdcp1x_Rx::UnauthenticatedCallbackRef.
Referenced by XHdcp1x_SetCallback.
int XHdcp1x_RxPoll(XHdcp1x *InstancePtr)
This function polls the HDCP receiver module.
InstancePtr is the receiver instance. XST_SUCCESS if successful. None.
Referenced by XHdcp1x_Poll.
int XHdcp1x_RxSetRepeaterBcaps(XHdcp1x *InstancePtr, u8 IsRptr)
This function set the REPEATER bit for the HDCP RX interface.
InstancePtr is the receiver instance. IsRptr is the truth value to determine if the repeater bit in the port registers is to be set. XST_SUCCESS if successful. This function disables and then re-enables the interface.
References XHdcp1x_PortSetRepeater.
Referenced by XHdcp1x_SetRepeater.
int XHdcp1x_RxReset(XHdcp1x *InstancePtr)
This function resets an HDCP interface.
InstancePtr is the receiver instance. XST_SUCCESS if successful. This function disables and then re-enables the interface.
Referenced by XHdcp1x_Reset.
int XHdcp1x_RxEnable(XHdcp1x *InstancePtr)
This function enables a HDCP receive interface.
InstancePtr is the receiver instance. XST_SUCCESS if successful. None.
Referenced by XHdcp1x_Enable.
int XHdcp1x_RxDisable(XHdcp1x *InstancePtr)
This function disables a HDCP receive interface.
InstancePtr is the receiver instance. XST_SUCCESS if successful. None.
Referenced by XHdcp1x_Disable.
int XHdcp1x_RxSetPhysicalState(XHdcp1x *InstancePtr, int IsUp)
This function updates the physical state of an HDCP interface.
InstancePtr is the receiver instance. IsUp is truth value indicating the status of physical interface. XST_SUCCESS if successful. None.
Referenced by XHdcp1x_SetPhysicalState.
int XHdcp1x_RxSetLaneCount(XHdcp1x *InstancePtr, int LaneCount)
This function set the lane count of an hdcp interface.
InstancePtr is the receiver instance. LaneCount is the number of lanes of the interface. XST_SUCCESS if successful. None.
References XHdcp1x_CipherSetNumLanes.
Referenced by XHdcp1x_SetLaneCount.
int XHdcp1x_RxDownstreamReady(XHdcp1x *InstancePtr)
This function initiates downstream ready/ assemble ksv list on an interface.
InstancePtr is the receiver instance. XST_SUCCESS if successful. None.
Referenced by XHdcp1x_DownstreamReady.
int XHdcp1x_RxAuthenticate(XHdcp1x *InstancePtr)
This function initiates authentication on an interface.
InstancePtr is the receiver instance. XST_SUCCESS if successful. None.
Referenced by XHdcp1x_Authenticate.
int XHdcp1x_RxIsAuthenticated(const XHdcp1x *InstancePtr)
This function queries an interface to check if its been authenticated.
InstancePtr is the receiver instance. Truth value indicating authenticated (true) or not (false). None.
References XHdcp1x_Rx::CurrentState, XHdcp1x::Rx.
Referenced by XHdcp1x_IsAuthenticated.
int XHdcp1x_RxIsInComputations(const XHdcp1x *InstancePtr)
This function queries an interface to check if its in the computations state.
InstancePtr is the receiver instance. Truth value indicating authenticated (true) or not (false). None.
References XHdcp1x_Rx::CurrentState, XHdcp1x::Rx.
Referenced by XHdcp1x_IsInComputations.
int XHdcp1x_RxIsInWaitforready(const XHdcp1x *InstancePtr)
This function queries an interface to check if its in the wait-for-downstream-ready state.
InstancePtr is the receiver instance. Truth value indicating authenticated (true) or not (false). None.
References XHdcp1x_Rx::CurrentState, XHdcp1x::Rx.
Referenced by XHdcp1x_IsInWaitforready.
int XHdcp1x_RxIsEnabled(const XHdcp1x *InstancePtr)
This function queries an interface to check if is enabled.
InstancePtr is the receiver instance. Truth value indicating is enabled (true) or not (false). None.
References XHdcp1x_Rx::CurrentState, XHdcp1x::Rx.
Referenced by XHdcp1x_IsEnabled.
int XHdcp1x_RxIsInProgress(const XHdcp1x *InstancePtr)
This function queries an interface to check if authentication is in progress.
InstancePtr is the receiver instance. Truth value indicating in progress (true) or not (false). None.
References XHdcp1x_Rx::CurrentState, XHdcp1x::Rx.
u64 XHdcp1x_RxGetEncryption(const XHdcp1x *InstancePtr)
This function retrieves the current encryption stream map.
InstancePtr is the receiver instance. The current encryption stream map. None.
References XHdcp1x_CipherGetEncryption.
Referenced by XHdcp1x_GetEncryption.
void XHdcp1x_RxHandleTimeout(XHdcp1x *InstancePtr)
This function handles a timeout on an HDCP interface.
InstancePtr is the receiver instance. None.
Referenced by XHdcp1x_HandleTimeout.
int XHdcp1x_RxInfo(const XHdcp1x *InstancePtr)
This function implements the debug display output for receiver instances.
InstancePtr is the receiver instance. XST_SUCCESS if successful. None.
References XHdcp1x_RxStats::AuthAttempts, XHdcp1x::Cipher, XHdcp1x::Config, XHdcp1x_Rx::CurrentState, XHdcp1x_Rx::Flags, XHdcp1x_CipherStats::IntCount, XHdcp1x_PortStats::IntCount, XHdcp1x_Config::IsHDMI, XHdcp1x_RxStats::LinkFailures, XHdcp1x::Port, XHdcp1x_Rx::PreviousState, XHdcp1x_RxStats::RiUpdates, XHdcp1x::Rx, XHdcp1x_Cipher::Stats, XHdcp1x_PortStruct::Stats, XHdcp1x_Rx::Stats, XHdcp1x_CipherGetLocalKsv, XHdcp1x_CipherGetVersion, XHDCP1X_DEBUG_PRINTF, XHdcp1x_GetDriverVersion, XHdcp1x_IsEncrypted.
Referenced by XHdcp1x_Info.
int XHdcp1x_RxGetRepeaterInfo(XHdcp1x *InstancePtr, XHdcp1x_RepeaterExchange *RepeaterInfoPtr)
This function copies the V'H0, V'H1, V'H2, V'H3, V'H4, KSVList and BInfo values in the HDCP RX HDCP Instance for Repeater validation .
InstancePtr is the receiver instance. RepeaterInfoPtr is the Repeater information in the transmitter instance. XST_SUCCESS if successful. None.
References XHdcp1x_RepeaterExchange::Depth, XHdcp1x_RepeaterExchange::DeviceCount, XHdcp1x_RepeaterExchange::KsvList, XHdcp1x::RepeaterValues, XHdcp1x_RepeaterExchange::V.
Referenced by XHdcp1x_GetRepeaterInfo.
void XHdcp1x_RxSetTopologyMaxDevsExceeded(XHdcp1x *InstancePtr, u8 Value)
This function sets the MAX_DEVS_EXCEEDED error flag in the HDCP BStatus register to indicate a topology error.
Setting the flag indicates that more than 31 downstream devices are attached. InstancePtr is a pointer to the Hdcp1x core instance. Value is either TRUE or FALSE. None.
References XHDCP1X_PORT_BINFO_DEV_CNT_ERR_SHIFT, XHDCP1X_PORT_BSTATUS_DEV_CNT_ERR_SHIFT, XHDCP1X_PORT_OFFSET_BINFO, XHDCP1X_PORT_OFFSET_BSTATUS, XHDCP1X_PORT_SIZE_BINFO, XHDCP1X_PORT_SIZE_BSTATUS, XHdcp1x_PortRead, XHdcp1x_PortWrite.
Referenced by XHdcp1x_SetTopologyField.
void XHdcp1x_RxSetTopologyMaxCascadeExceeded(XHdcp1x *InstancePtr, u8 Value)
This function sets the MAX_CASCADE_EXCEEDED error flag in the HDCP BStatus/BInfo register to indicate a topology error.
Setting the flag indicates a depth of more than (4 - 1). InstancePtr is a pointer to the Hdcp1x core instance. Value is either TRUE or FALSE. None.
References XHDCP1X_PORT_BINFO_DEPTH_ERR_SHIFT, XHDCP1X_PORT_BSTATUS_DEPTH_ERR_SHIFT, XHDCP1X_PORT_OFFSET_BINFO, XHDCP1X_PORT_OFFSET_BSTATUS, XHDCP1X_PORT_SIZE_BINFO, XHDCP1X_PORT_SIZE_BSTATUS, XHdcp1x_PortRead, XHdcp1x_PortWrite.
Referenced by XHdcp1x_SetTopologyField.
void XHdcp1x_RxSetTopologyDeviceCnt(XHdcp1x *InstancePtr, u32 Value)
This function sets the DEVICE_COUNT value in the HDCP RX register space for the upstream interface to read.
InstancePtr is a pointer to the Hdcp1x core instance. Value is the device count value. None.
References XHdcp1x_RepeaterExchange::DeviceCount, XHdcp1x::RepeaterValues.
Referenced by XHdcp1x_SetTopologyField.
void XHdcp1x_RxSetTopologyDepth(XHdcp1x *InstancePtr, u32 Value)
This function sets the Depth value in the HDCP RX BStatus/BInfo register space for the upstream interface to read.
InstancePtr is a pointer to the Hdcp1x core instance. Value is the Depth value. None.
References XHdcp1x_RepeaterExchange::Depth, XHdcp1x::RepeaterValues.
Referenced by XHdcp1x_SetTopologyField.
void XHdcp1x_RxSetTopologyKSVList(XHdcp1x *InstancePtr, u8 *ListPtr, u32 ListSize)
This function sets the KSVList value(s) in the HDCP RX KSV Fifo register space for the upstream interface to read.
InstancePtr is a pointer to the Hdcp1x core instance. ListPtr is a pointer to the KSV list. ListSize is the number of KSVs in the list. None.
References XHdcp1x_RepeaterExchange::KsvList, XHdcp1x::RepeaterValues, XHDCP1X_PORT_SIZE_BKSV.
Referenced by XHdcp1x_SetTopologyKSVList.
void XHdcp1x_RxSetTopologyUpdate(XHdcp1x *InstancePtr)
This function does the necessary actions to update HDCP after the topology has been set.
InstancePtr is a pointer to the Hdcp1x core instance. None.
Referenced by XHdcp1x_SetTopologyUpdate.
void XHdcp1x_RxSetTopology(XHdcp1x *InstancePtr, const XHdcp1x_RepeaterExchange *TopologyPtr)
This function sets the RepeaterInfo value int the HDCP RX instance.
InstancePtr is a pointer to the Hdcp1x core instance. TopologyPtr is the pointer to topology information. None.
References XHdcp1x::RepeaterValues.
Referenced by XHdcp1x_SetTopology.
void XHdcp1x_RxSetHdmiMode(XHdcp1x *InstancePtr, u8 Value)
This function set the HDMI_MODE in the BStatus register of the HDMI RX DDC space.
InstancePtr is a pointer to the Hdcp1x core instance. Value is the truth-value. None.
References UNUSED, XHDCP1X_PORT_BIT_BSTATUS_HDMI_MODE, XHDCP1X_PORT_OFFSET_BSTATUS, XHDCP1X_PORT_SIZE_BSTATUS, XHdcp1x_PortRead, XHdcp1x_PortWrite.
Referenced by XHdcp1x_SetHdmiMode.