xhdcp1x_port.h
XHDCP1X_PORT_H
< Prevent circular inclusions by using protection macros
XHDCP1X_PORT_UINT_TO_BUF
This macro converts from an unsigned integer to a little endian formatted buffer.
buf the buffer to write to Value the unsigned integer to convert numbits the number of bits within the unsigned integer to use None. The value of the "Value" parameter is destroyed by a call to this macro
XHDCP1X_PORT_BUF_TO_UINT
This macro converts from a little endian formatted buffer to an unsigned integer value.
Value the unsigned integer to write buf the buffer to convert numbits the number of bits within the buffer to use None. None.
Referenced by XHdcp1x_TxGetTopologyBKSV.
XHDCP1X_PORT_BSET_IN_BUF
This macro sets a bit within a little endian formatted buffer.
buf the buffer to write to bitnum the bit to set None. None.
XHDCP1X_PORT_BCLR_IN_BUF
This macro clears a bit within a little endian formatted buffer.
buf the buffer to write to bitnum the bit to clear None. None.
XHDCP1X_PORT_BTST_IN_BUF
This macro tests a bit within a little endian formatted buffer.
buf the buffer containing the bit to test bitnum the bit to test None. None.
XHdcp1x_PortHandlerType
An (re)auth request.
typedef struct XHdcp1x_PortPhyIfAdaptorS XHdcp1x_PortPhyIfAdaptor
The typedef defines the HDCP port adaptor table.
This contains a series of functions that map the external interface of the HDCP port device to the underlying physical interface that it is running over
const XHdcp1x_PortPhyIfAdaptor * XHdcp1x_PortDetermineAdaptor(XHdcp1x *InstancePtr)
This function determines the adaptor for a specified port device.
InstancePtr is the device whose adaptor is to be determined. A pointer to the adaptor table. NULL if not found. None.
References XHdcp1x::Config, XHdcp1x_Config::IsHDMI, XHdcp1x_Config::IsRx.
Referenced by XHdcp1x_CfgInitialize.
int XHdcp1x_PortSetCallback(XHdcp1x *InstancePtr, u32 HandlerType, XHdcp1x_Callback CallbackFunc, void *CallbackRef)
This function installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function Type ------------------------------------ ------------------------------------- (XHDCP1X_PORT_HANDLER_AUTHENTICATE) AuthCallback InstancePtr is a pointer to the HDCP port instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XHdcp1x_PortStruct::AuthCallback, XHdcp1x_PortStruct::AuthRef, XHdcp1x_PortStruct::IsAuthCallbackSet, XHdcp1x::Port, XHDCP1X_PORT_HANDLER_AUTHENTICATE.
int XHdcp1x_PortEnable(XHdcp1x *InstancePtr)
This function enables a port device.
InstancePtr is the device to enables. XST_SUCCESS if successful.XST_NO_FEATURE if the port lacks an Enable function. None.
References XHdcp1x_PortStruct::Adaptor, XHdcp1x_PortPhyIfAdaptorS::Enable, XHdcp1x::Port.
int XHdcp1x_PortDisable(XHdcp1x *InstancePtr)
This function disables a port device.
InstancePtr is the device to disables. XST_SUCCESS if successful.XST_NO_FEATURE if the port lacks a Disable function. None.
References XHdcp1x_PortStruct::Adaptor, XHdcp1x_PortPhyIfAdaptorS::Disable, XHdcp1x::Port.
int XHdcp1x_PortIsCapable(const XHdcp1x *InstancePtr)
This function queries a port device to determine if hdcp is supported.
InstancePtr is the device to query. Truth value. None.
References XHdcp1x_PortStruct::Adaptor, XHdcp1x_PortPhyIfAdaptorS::IsCapable, XHdcp1x::Port.
Referenced by XHdcp1x_TxIsDownstrmCapable.
int XHdcp1x_PortIsRepeater(const XHdcp1x *InstancePtr)
This function queries a port device to determine if it is connected to a repeater.
InstancePtr is the device to query. Truth value. None.
References XHdcp1x_PortStruct::Adaptor, XHdcp1x_PortPhyIfAdaptorS::IsRepeater, XHdcp1x::Port.
Referenced by XHdcp1x_TxIsRepeater.
int XHdcp1x_PortSetRepeater(XHdcp1x *InstancePtr, u8 RptrConf)
This function set the REPEATER information in the connected device.
InstancePtr is the device to query. RptrConf is the configuration of the device as repeater. XST_SUCCESS if successful.XST_NO_FEATURE if the port fails to set the Repeater value. None.
References XHdcp1x_PortStruct::Adaptor, XHdcp1x::Port, XHdcp1x_PortPhyIfAdaptorS::SetRepeater.
Referenced by XHdcp1x_RxSetRepeaterBcaps.
int XHdcp1x_PortGetRepeaterInfo(XHdcp1x *InstancePtr, u16 *InfoPtr)
This function retrieves the repeater information from the connected device.
InstancePtr is the device to query. InfoPtr is the repeater info. XST_SUCCESS if successful.XST_NO_FEATURE if the port lacks a GetRepeaterInfo function. None.
References XHdcp1x_PortStruct::Adaptor, XHdcp1x_PortPhyIfAdaptorS::GetRepeaterInfo, XHdcp1x::Port.
int XHdcp1x_PortRead(const XHdcp1x *InstancePtr, u8 Offset, void *Buf, u32 BufSize)
This function reads a register from a HDCP port device.
InstancePtr is the device to read from. Offset is the offset to start reading from. Buf is the buffer to copy the data read. BufSize is the size of the buffer. The number of bytes read. None.
References XHdcp1x_PortStruct::Adaptor, XHdcp1x::Port, XHdcp1x_PortPhyIfAdaptorS::Read.
Referenced by XHdcp1x_RxSetHdmiMode, XHdcp1x_RxSetTopologyMaxCascadeExceeded, XHdcp1x_RxSetTopologyMaxDevsExceeded, XHdcp1x_TxGetTopologyBKSV, XHdcp1x_TxGetTopologyMaxCascadeExceeded, XHdcp1x_TxGetTopologyMaxDevsExceeded.
int XHdcp1x_PortWrite(XHdcp1x *InstancePtr, u8 Offset, const void *Buf, u32 BufSize)
This function writes a register within a HDCP port device.
InstancePtr is the device to write to. Offset is the offset to start writing at. Buf is the buffer containing the data to write. BufSize is the size of the buffer. The number of bytes written. None.
References XHdcp1x_PortStruct::Adaptor, XHdcp1x::Port, XHdcp1x_PortPhyIfAdaptorS::Write.
Referenced by XHdcp1x_RxSetHdmiMode, XHdcp1x_RxSetTopologyMaxCascadeExceeded, XHdcp1x_RxSetTopologyMaxDevsExceeded.
void XHdcp1x_PortHandleInterrupt(XHdcp1x *InstancePtr, u32 IntCause)
This handles an interrupt generated by a HDCP port device.
InstancePtr is the device to write to. IntCause is the interrupt cause bit map. None.
References XHdcp1x_PortStruct::Adaptor, XHdcp1x_PortStats::IntCount, XHdcp1x_PortPhyIfAdaptorS::IntrHandler, XHdcp1x::Port, XHdcp1x_PortStruct::Stats.
Referenced by XHdcp1x_PortIntrHandler.
int XHdcp1x_SetEcfSlots(XHdcp1x *InstancePtr, u64 timeslots)
This function enables encryption/decyption for all timeslots.
InstancePtr is the device to enables. timeslots is the timeslot configuration value. XST_SUCCESS if successful.XST_NO_FEATURE if the port lacks an Enable function. None.
References XHdcp1x_PortStruct::Adaptor, XHdcp1x::Port, XHdcp1x_PortPhyIfAdaptorS::SetEcfSlots.
Referenced by XHdcp1x_TxEnableEcf, XHdcp1x_TxEnableEcfTimeslots.