xhdcp1x.h
XHDCP1X_H
< Prevent circular inclusions by using protection macros
XPAR_XHDCP_NUM_INSTANCES
XPAR_XDPTXSS_NUM_INSTANCES
XPAR_XDPRXSS_NUM_INSTANCES
XHDCP1X_KSV_SIZE
Size of each hdcp 1.4 Public Key in bytes.
XHDCP1X_RPTR_MAX_CASCADE
Maximum depth that the Repeater can support on the downstream interface.
XHDCP1X_RPTR_MAX_DEVS_COUNT
Maximum devices that can be cascaded to the Repeater.
XHdcp1x_SetCallBack
Alternative name for the function to set callback for HDCP functions.
UNUSED
Used to remove warnings for unused variables.
Referenced by XHdcp1x_DisableEncryption, XHdcp1x_EnableEncryption, XHdcp1x_RxSetHdmiMode, XHdcp1x_SetTopologyKSVList, XHdcp1x_TxSetHdmiMode.
XHDCP1X_ADDITIONAL_DEBUG
Adds extra functions for additional debugging.
XHdcp1x_Rx_StateType
XHdcp1x_Tx_StateType
XHdcp1x_HandlerType
XHdcp1x_RepeaterStateMachineHandlerType
XHdcp1x_TopologyField
typedef void(* XHdcp1x_Callback)(void *CallbackRef))(void *CallbackRef)
This typedef defines the callback interface that is to be used for interrupts within this driver.
typedef void(* XHdcp1x_Printf)(const char *fmt,...))(const char *fmt,...)
This typedef defines the function interface that is to be used for debug print statements within this driver.
typedef void(* XHdcp1x_LogMsg)(const char *fmt,...))(const char *fmt,...)
This typedef defines the function interface that is to be used for debug log message statements within this driver.
typedef int(* XHdcp1x_RunDdcHandler)(u8 DeviceAddress, u16 ByteCount, u8 *BufferPtr, u8 Stop, void *RefPtr))(u8 DeviceAddress, u16 ByteCount, u8 *BufferPtr, u8 Stop, void *RefPtr)
Callback type used for calling DDC read and write functions.
DeviceAddress is the (i2c) device address of the HDCP port. ByteCount is the amount of data bytes in the buffer to read or write. BufferPtr is a pointer to a buffer that is used for reading or writing. Stop is a flag to control if a stop token is set or not. RefPtr is a callback reference passed in by the upper layer when setting the DDC reading and writing functions, and passed back to the upper layer when the callback is invoked. XST_SUCCESS The read action was successful.XST_FAILURE The read action failed. None.
typedef void(* XHdcp1x_SetDdcHandler)(void *HandlerRef, u32 Data))(void *HandlerRef, u32 Data)
This typedef defines the function interface that is to be used for setting the DDC handler for HDMI implementation of HDCP functionality over HDMI within this driver.
typedef u32(* XHdcp1x_GetDdcHandler)(void *HandlerRef))(void *HandlerRef)
This typedef defines the function interface that is to be used to get the DDC handler for implementation of HDCP functionality over HDMI within this driver.
typedef u64 XHdcp1x_Ksv
This typedef defines a memory to store a Key Selection Vector (KSV)
typedef struct XHdcp1x_PortStruct XHdcp1x_Port
This typedef contains an instance of the HDCP port.
typedef int(* XHdcp1x_TimerStart)(void *InstancePtr, u16 TmoInMs))(void *InstancePtr, u16 TmoInMs)
This typedef defines the function interface that is to be used for starting a one shot timer on behalf of an HDCP interface within the underlying platform.
typedef int(* XHdcp1x_TimerStop)(void *InstancePtr))(void *InstancePtr)
This typedef defines the function interface that is to be used for stopping a timer on behalf of an HDCP interface.
typedef int(* XHdcp1x_TimerDelay)(void *InstancePtr, u16 DelayInMs))(void *InstancePtr, u16 DelayInMs)
This typedef defines the function interface that is to be used for performing a busy delay on behalf of an HDCP interface.
typedef int(* XHdcp1x_KsvRevokeCheck)(const XHdcp1x *InstancePtr, u64 Ksv))(const XHdcp1x *InstancePtr, u64 Ksv)
This typedef defines the function interface that is to be used for checking a specific KSV against the platforms revocation list.
XHdcp1x_Config * XHdcp1x_LookupConfig(UINTPTR BaseAddress)
This function returns a reference to an XHdcp1x_Config structure based on specified device ID.
DeviceId is the unique core ID of the HDCP interface. A reference to the config record in the configuration table (in xhdcp_g.c) corresponding the specified DeviceId. NULL if no match is found. None.
int XHdcp1x_CfgInitialize(XHdcp1x *InstancePtr, const XHdcp1x_Config *CfgPtr, void *PhyIfPtr, UINTPTR EffectiveAddr)
This function retrieves the configuration for this HDCP instance and fills in the InstancePtr->Config structure.
InstancePtr is the device whose adaptor is to be determined. CfgPtr is the configuration of the instance. PhyIfPtr is pointer to the underlying physical interface. EffectiveAddr is the device base address in the virtual memory space. If the address translation is not used, then the physical address is passed. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x_PortStruct::Adaptor, XHdcp1x_Tx::AuthenticatedCallback, XHdcp1x_Rx::AuthenticatedCallback, XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHdcp1x_Rx::DdcGetDataCallback, XHdcp1x_Tx::DdcRead, XHdcp1x_Rx::DdcSetAddressCallback, XHdcp1x_Rx::DdcSetDataCallback, XHdcp1x_Tx::DdcWrite, XHdcp1x_Rx::EncryptionUpdateCallback, XHdcp1x_PortPhyIfAdaptorS::Init, XHdcp1x_Tx::IsAuthenticatedCallbackSet, XHdcp1x_Rx::IsAuthenticatedCallbackSet, XHdcp1x_Rx::IsDdcGetDataCallbackSet, XHdcp1x_Tx::IsDdcReadSet, XHdcp1x_Rx::IsDdcSetAddressCallbackSet, XHdcp1x_Rx::IsDdcSetDataCallbackSet, XHdcp1x_Tx::IsDdcWriteSet, XHdcp1x_Rx::IsEncryptionUpdateCallbackSet, XHdcp1x_Config::IsHDMI, XHdcp1x::IsReady, XHdcp1x_Rx::IsRepeaterDownstreamAuthCallbackSet, XHdcp1x_Tx::IsRepeaterExchangeCallbackSet, XHdcp1x_Config::IsRx, XHdcp1x_Rx::IsTopologyUpdateCallbackSet, XHdcp1x_Tx::IsUnauthenticatedCallbackSet, XHdcp1x_Rx::IsUnauthenticatedCallbackSet, XHdcp1x_PortStruct::PhyIfPtr, XHdcp1x::Port, XHdcp1x_Rx::RepeaterDownstreamAuthCallback, XHdcp1x_Tx::RepeaterExchangeCallback, XHdcp1x::Rx, XHdcp1x_Rx::TopologyUpdateCallback, XHdcp1x::Tx, XHdcp1x_Tx::UnauthenticatedCallback, XHdcp1x_Rx::UnauthenticatedCallback, XHDCP1X_CIPHER_BITMASK_TYPE_DIRECTION, XHDCP1X_CIPHER_BITMASK_TYPE_PROTOCOL, XHDCP1X_CIPHER_REG_TYPE, XHDCP1X_CIPHER_VALUE_TYPE_DIRECTION_RX, XHDCP1X_CIPHER_VALUE_TYPE_PROTOCOL_HDMI, XHdcp1x_CipherInit, XHdcp1x_PortDetermineAdaptor, XHdcp1x_ReadReg, XHdcp1x_RxInit, XHdcp1x_TxInit.
void XHdcp1x_LateInit(XHdcp1x *InstancePtr)
int XHdcp1x_SelfTest(XHdcp1x *InstancePtr)
This function self tests an HDCP interface.
InstancePtr is the interface to test. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x_Config::BaseAddress, XHdcp1x::Config, XHdcp1x_Config::IsHDMI, XHdcp1x_Config::IsRx, XHDCP1X_CIPHER_REG_VERSION, XHdcp1x_IsDP, XHdcp1x_IsHDMI, XHdcp1x_IsRX, XHdcp1x_IsTX, XHdcp1x_ReadReg.
int XHdcp1x_Poll(XHdcp1x *InstancePtr)
This function polls an HDCP interface.
InstancePtr is the interface to poll. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_RxPoll, XHdcp1x_TxPoll.
int XHdcp1x_DownstreamReady(XHdcp1x *InstancePtr)
This function posts a DOWNSTREAMREADY event to an HDCP interface.
InstancePtr is the interface to reset. XST_SUCCESS if successful. XST_FAILURE otherwise. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_RxDownstreamReady.
int XHdcp1x_GetRepeaterInfo(XHdcp1x *InstancePtr, XHdcp1x_RepeaterExchange *RepeaterInfoPtr)
This function copies the V'H0, V'H1, V'H2, V'H3, V'H4, KSVList and BInfo values in the HDCP RX HDCP Instance for Repeater validation .
InstancePtr is the receiver instance. RepeaterInfoPtr is the Repeater information in the transmitter instance. XST_SUCCESS if successful. XST_FAILURE otherwise. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_RxGetRepeaterInfo.
int XHdcp1x_SetRepeater(XHdcp1x *InstancePtr, u8 State)
This function sets the Repeater functionality for an HDCP interface.
InstancePtr is the interface to disable. State is either TRUE or FALSE XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x::Config, XHdcp1x::IsRepeater, XHdcp1x_Config::IsRx, XHdcp1x_RxSetRepeaterBcaps.
int XHdcp1x_Reset(XHdcp1x *InstancePtr)
This function resets an HDCP interface.
InstancePtr is the interface to reset. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_RxReset, XHdcp1x_TxReset.
int XHdcp1x_Enable(XHdcp1x *InstancePtr)
This function enables an HDCP interface.
InstancePtr is the interface to enable. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x_PortStruct::Adaptor, XHdcp1x::Config, XHdcp1x_PortPhyIfAdaptorS::Init, XHdcp1x_Config::IsRx, XHdcp1x::Port, XHdcp1x_RxEnable, XHdcp1x_TxEnable.
int XHdcp1x_Disable(XHdcp1x *InstancePtr)
This function disables an HDCP interface.
InstancePtr is the interface to disable. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_RxDisable, XHdcp1x_TxDisable.
int XHdcp1x_SetPhysicalState(XHdcp1x *InstancePtr, int IsUp)
This function updates the state of the underlying physical interface.
InstancePtr is the interface to update. IsUp indicates the state of the underlying physical interface. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_RxSetPhysicalState, XHdcp1x_TxSetPhysicalState.
int XHdcp1x_SetLaneCount(XHdcp1x *InstancePtr, int LaneCount)
This function sets the lane count of a hdcp interface.
InstancePtr is the interface to update. LaneCount is the lane count. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x::Config, XHdcp1x_Config::IsHDMI, XHdcp1x_Config::IsRx, XHdcp1x_RxSetLaneCount, XHdcp1x_TxSetLaneCount.
int XHdcp1x_SetMSTMode(XHdcp1x *InstancePtr, int mode)
This function sets the MST/ SST of a hdcp interface.
InstancePtr is the interface to update. mode determines the MST/ SST configuration. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x::Config, XHdcp1x_Config::IsHDMI, XHdcp1x_Config::IsRx, XHdcp1x_TxSetMSTMode.
int XHdcp1x_Authenticate(XHdcp1x *InstancePtr)
This function initiates authentication of an HDCP interface.
InstancePtr is the interface to initiate authentication on. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_RxAuthenticate, XHdcp1x_TxAuthenticate.
int XHdcp1x_ReadDownstream(XHdcp1x *InstancePtr)
This function initiates downstream read of READY bit and consequently the second part of Repeater authentication.
InstancePtr is the interface to initiate authentication on. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_TxReadDownstream.
int XHdcp1x_IsInProgress(const XHdcp1x *InstancePtr)
This function queries an interface to determine if authentication is in progress.
InstancePtr is the interface to query. Truth value indicating authentication in progress (TRUE) or not (FALSE). None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_TxIsInProgress.
int XHdcp1x_IsAuthenticated(const XHdcp1x *InstancePtr)
This function queries an interface to determine if it has successfully completed authentication.
InstancePtr is the interface to query. Truth value indicating authenticated (TRUE) or not (FALSE). None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_RxIsAuthenticated, XHdcp1x_TxIsAuthenticated.
Referenced by XHdcp1x_EnableEncryption, XHdcp1x_IsEncrypted.
int XHdcp1x_IsInComputations(const XHdcp1x *InstancePtr)
This function queries an interface to determine if it is in the state of computations or not.
InstancePtr is the interface to query. Truth value indicating authenticated (TRUE) or not (FALSE). None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_RxIsInComputations, XHdcp1x_TxIsInComputations.
int XHdcp1x_IsInWaitforready(const XHdcp1x *InstancePtr)
This function queries an interface to determine if it is in the wait-for-ready state or not.
InstancePtr is the interface to query. Truth value indicating authenticated (TRUE) or not (FALSE). None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_RxIsInWaitforready, XHdcp1x_TxIsInWaitforready.
int XHdcp1x_IsDwnstrmCapable(const XHdcp1x *InstancePtr)
This function queries the device connected to the downstream interface to determine if it supports hdcp or not.
InstancePtr is the interface to query. Truth value indicating HDCP capability (TRUE) or not (FALSE). None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_TxIsDownstrmCapable.
int XHdcp1x_IsEnabled(const XHdcp1x *InstancePtr)
This function queries an interface to determine if it is enabled.
InstancePtr is the interface to query. Truth value indicating enabled (TRUE) or not (FALSE). None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_RxIsEnabled, XHdcp1x_TxIsEnabled.
u64 XHdcp1x_GetEncryption(const XHdcp1x *InstancePtr)
This function retrieves the current encryption map of the video streams traversing an hdcp interface.
InstancePtr is the interface to query. The current encryption map. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_RxGetEncryption, XHdcp1x_TxGetEncryption.
Referenced by XHdcp1x_IsEncrypted.
int XHdcp1x_IsEncrypted(const XHdcp1x *InstancePtr)
This function determines if the video stream is encrypted.
The traffic is encrypted if the encryption bit map is non-zero and the interface is authenticated. InstancePtr is a pointer to the HDCP instance. Truth value indicating encrypted (TRUE) or not (FALSE). None.
References XHdcp1x_GetEncryption, XHdcp1x_IsAuthenticated.
Referenced by XHdcp1x_RxInfo, XHdcp1x_TxInfo.
int XHdcp1x_EnableEncryption(XHdcp1x *InstancePtr, u64 Map)
This function enables encryption on a series of streams within an HDCP interface.
InstancePtr is the interface to configure. Map is the stream map to enable encryption on. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x_PortStruct::Adaptor, XHdcp1x::Config, XHdcp1x_PortPhyIfAdaptorS::Init, XHdcp1x_Config::IsRx, XHdcp1x_Tx::mode, XHdcp1x::Port, XHdcp1x::Tx, UNUSED, XHdcp1x_IsAuthenticated, XHdcp1x_TxEnableEncryption.
int XHdcp1x_DisableEncryption(XHdcp1x *InstancePtr, u64 Map)
This function disables encryption on a series of streams within an HDCP interface.
InstancePtr is the interface to configure. Map is the stream map to disable encryption on. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, UNUSED, XHdcp1x_TxDisableEncryption.
int XHdcp1x_SetKeySelect(XHdcp1x *InstancePtr, u8 KeySelect)
This function sets the key selection vector that is to be used by the HDCP cipher.
InstancePtr is the interface to configure. KeySelect is the key selection vector. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x_CipherSetKeySelect.
int XHdcp1x_Enable_ECF_Slots(XHdcp1x *InstancePtr, u64 timeslots)
This function enables an HDCP MST ECF Field.
InstancePtr is the interface to enable. timeslots is the time slots to be enabled for ECF. XST_SUCCESS if successful.XST_FAILURE otherwise. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_TxEnableEcfTimeslots.
void XHdcp1x_HandleTimeout(void *InstancePtr)
This function handles a timeout on an HDCP interface.
InstancePtr is the interface. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHDCP1X_DEBUG_PRINTF, XHdcp1x_RxHandleTimeout, XHdcp1x_TxHandleTimeout.
int XHdcp1x_SetCallback(XHdcp1x *InstancePtr, XHdcp1x_HandlerType HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs callback functions for the given HandlerType.
InstancePtr is a pointer to the HDCP core instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_RxSetCallback, XHdcp1x_TxSetCallback.
void XHdcp1x_CipherIntrHandler(void *InstancePtr)
This function is the cipher interrupt handler for the HDCP module.
InstancePtr is the device instance that just interrupted. This function just forwards the interrupt along to the corresponding cipher core.
References XHdcp1x::IsReady, XHdcp1x_CipherHandleInterrupt.
void XHdcp1x_PortIntrHandler(void *InstancePtr, u32 IntCause)
This function is the port interrupt handler for the HDCP module.
InstancePtr is the device instance that just interrupted. IntCause is the interrupt cause bit map. This function just forwards the interrupt along to the corresponding cipher core.
References XHdcp1x::IsReady, XHdcp1x_PortHandleInterrupt.
void XHdcp1x_SetDebugPrintf(XHdcp1x_Printf PrintfFunc)
This function sets the debug printf function for the module.
PrintfFunc is the printf function. None.
References XHdcp1xDebugPrintf.
void XHdcp1x_SetDebugLogMsg(XHdcp1x_LogMsg LogFunc)
This function sets the debug log message function for the module.
LogFunc is the debug logging function. None.
References XHdcp1xDebugLogMsg.
void XHdcp1x_SetKsvRevokeCheck(XHdcp1x_KsvRevokeCheck RevokeCheckFunc)
This function sets the KSV revocation list check function for the module.
RevokeCheckFunc is the KSV revocation list check function. None.
References XHdcp1xKsvRevokeCheck.
void XHdcp1x_SetTimerStart(XHdcp1x *InstancePtr, XHdcp1x_TimerStart TimerStartFunc)
This function sets timer start function for the module.
InstancePtr is the pointer to the HDCP interface. TimerStartFunc is the timer start function. None.
References XHdcp1x::XHdcp1xTimerStart.
void XHdcp1x_SetTimerStop(XHdcp1x *InstancePtr, XHdcp1x_TimerStop TimerStopFunc)
This function sets timer stop function for the module.
InstancePtr is the pointer to the HDCP interface. TimerStopFunc is the timer stop function. None.
References XHdcp1x::XHdcp1xTimerStop.
void XHdcp1x_SetTimerDelay(XHdcp1x *InstancePtr, XHdcp1x_TimerDelay TimerDelayFunc)
This function sets timer busy delay function for the module.
InstancePtr is the pointer to the HDCP interface. TimerDelayFunc is the timer busy delay function. None.
References XHdcp1x::XHdcp1xTimerDelay.
u32 XHdcp1x_GetDriverVersion(void)
This function retrieves the version of the HDCP driver software.
The software driver version. None.
References DRIVER_VERSION.
Referenced by XHdcp1x_RxInfo, XHdcp1x_TxInfo.
u32 XHdcp1x_GetVersion(const XHdcp1x *InstancePtr)
This function retrieves the cipher version of an HDCP interface.
InstancePtr is the interface to query. The cipher version used by the interface None.
References XHdcp1x_CipherGetVersion.
void XHdcp1x_Info(const XHdcp1x *InstancePtr)
This function performs a debug display of an HDCP instance.
InstancePtr is the interface to display. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHDCP1X_DEBUG_PRINTF, XHdcp1x_RxInfo, XHdcp1x_TxInfo.
void XHdcp1x_ProcessAKsv(XHdcp1x *InstancePtr)
This function processes the AKsv.
InstancePtr is the interface to display. None.
References XHdcp1x_PortStruct::Adaptor, XHdcp1x_PortPhyIfAdaptorS::CallbackHandler, XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x::Port.
void * XHdcp1x_GetTopology(XHdcp1x *InstancePtr)
This function returns a pointer to the downstream Topology structure.
InstancePtr is a pointer to the XHdcp14 core instance. A pointer to the XHdcp14 Topology structure or NULL when the topology info is invalid. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHDCP1X_DEBUG_PRINTF, XHdcp1x_TxGetTopology.
void XHdcp1x_DisableBlank(XHdcp1x *InstancePtr)
This function disables the blank output for the cipher.
InstancePtr is a pointer to the XHdcp14 core instance. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_TxDisableBlank.
void XHdcp1x_EnableBlank(XHdcp1x *InstancePtr)
This function enables the blank output for the cipher.
InstancePtr is a pointer to the XHdcp14 core instance. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_TxEnableBlank.
void XHdcp1x_SetTopologyField(XHdcp1x *InstancePtr, XHdcp1x_TopologyField Field, u8 Value)
This function is used to set various fields inside the topology structure.
InstancePtr is a pointer to the XHdcp1x core instance. Field indicates what field of the topology structure to update. Value is the value assigned to the field of the topology structure. None.
References XHdcp1x_RxSetTopologyDepth, XHdcp1x_RxSetTopologyDeviceCnt, XHdcp1x_RxSetTopologyMaxCascadeExceeded, XHdcp1x_RxSetTopologyMaxDevsExceeded.
u32 XHdcp1x_GetTopologyField(XHdcp1x *InstancePtr, XHdcp1x_TopologyField Field)
This function is used to get various fields inside the topology structure.
InstancePtr is a pointer to the XHdcp1x core instance. Field indicates what field of the topology structure to update. None. None.
References XHdcp1x_TxGetTopologyDepth, XHdcp1x_TxGetTopologyDeviceCnt, XHdcp1x_TxGetTopologyMaxCascadeExceeded, XHdcp1x_TxGetTopologyMaxDevsExceeded.
u8 * XHdcp1x_GetTopologyKSVList(XHdcp1x *InstancePtr)
This function returns the value of KSV List read in the downstream interface of the repeater topology.
InstancePtr is a pointer to the XHdcp14 core instance. List of KSVs of the downstream devices None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_TxGetTopologyKSVList.
u8 * XHdcp1x_GetTopologyBKSV(XHdcp1x *InstancePtr)
This function returns the value of KSV of the device attached to the downstream interface of the repeater.
InstancePtr is a pointer to the XHdcp14 core instance. TRUE if MAX_DEPTH_EXCEEDED None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_TxGetTopologyBKSV.
int XHdcp1x_IsRepeater(XHdcp1x *InstancePtr)
This function return if the HDCP interface is a repeater in case of Rx or is connected to a repeater in case of Tx.
InstancePtr is the transmitter instance. TRUE if Repeater.FALSE if not Repeater, None.
References XHdcp1x::Config, XHdcp1x::IsRepeater, XHdcp1x_Config::IsRx, XHDCP1X_DEBUG_PRINTF, XHdcp1x_TxIsRepeater.
void XHdcp1x_SetTopology(XHdcp1x *InstancePtr, const XHdcp1x_RepeaterExchange *TopologyPtr)
This function sets the RepeaterInfo value int the HDCP RX instance.
InstancePtr is a pointer to the Hdcp1x core instance. TopologyPtr is a pointer to the Repeater Info value(s). None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHdcp1x_RxSetTopology.
void XHdcp1x_SetTopologyKSVList(XHdcp1x *InstancePtr, u8 *ListPtr, u32 ListSize)
This function sets the KSVList value(s) in the HDCP RX KSV Fifo register space for the upstream interface to read.
InstancePtr is a pointer to the Hdcp1x core instance. ListPtr is a pointer to the KSV list. ListSize is the number of KSVs in the list. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, UNUSED, XHdcp1x_RxSetTopologyKSVList.
void XHdcp1x_SetTopologyUpdate(XHdcp1x *InstancePtr)
This function does the necessary actions to update HDCP after the topology has been set.
InstancePtr is a pointer to the Hdcp1x core instance. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHDCP1X_DEBUG_PRINTF, XHdcp1x_RxSetTopologyUpdate.
void XHdcp1x_SetHdmiMode(XHdcp1x *InstancePtr, u8 Value)
This function set the HDMI_MODE in the BStatus register of the HDMI DDC space.
InstancePtr is a pointer to the Hdcp1x core instance. Value is the truth-value. None.
References XHdcp1x::Config, XHdcp1x_Config::IsRx, XHDCP1X_DEBUG_PRINTF, XHdcp1x_RxSetHdmiMode, XHdcp1x_TxSetHdmiMode.