xiltimer_api
XTimer TimerInst
static u32 XAxiTimer_Init(XTimer *InstancePtr, UINTPTR BaseAddress, XTmrCtr *AxiTimerInstPtr)
Initialize the Axi Timer Instance.
InstancePtr is a pointer to the instance to be worked on BaseAddress is the Axi Timer Instance baseaddress to be worked on XST_SUCCESS if initialization was successful XST_FAILURE in case of failure
static u32 XTimer_ScutimerInit(XTimer *InstancePtr, UINTPTR BaseAddress, XScuTimer *ScuTimerInstPtr)
Initialize the Scutimer Instance.
InstancePtr is a pointer to the instance to be worked on BaseAddress is the Scutimer Instance baseaddress to be worked on ScuTimerInstPtr is a pointer to the XScuTimer Instance XST_SUCCESS if initialization was successful XST_FAILURE in case of failure
static u32 XTimer_TtcInit(UINTPTR BaseAddress, XTtcPs *TtcPsInstPtr)
Initialize the TtcPs Instance.
BaseAddress is the Scutimer Instance baseaddress to be worked on XST_SUCCESS if initialization was successful XST_FAILURE in case of failure
void XilTimer_Sleep(unsigned long delay, XTimer_DelayType DelayType)
This API contains common delay implementation using library API's.
none none
References XTimerTag::XTimer_ModifyInterval.
Referenced by msleep, sleep, usleep.
void sleep(unsigned int seconds)
This API gives delay in sec.
seconds Delay time in seconds none none
References XilTimer_Sleep, XTIMER_DELAY_SEC.
void msleep(unsigned long mseconds)
This API gives delay in msec.
mseconds Delay time in milliseconds none none
References XilTimer_Sleep, XTIMER_DELAY_MSEC.
void usleep(unsigned long useconds)
This API gives delay in usec.
useconds Delay time in microseconds none none
References XilTimer_Sleep, XTIMER_DELAY_USEC.
void xtimerinit()
This API initializes the xiltimer library through constructor.
none
References XilSleepTimer_Init, XilTickTimer_Init.
void XTimer_SetHandler(XTimer_TickHandler FuncPtr, void *CallBackRef, u8 Priority)
This routine installs an asynchronous callback function for the given FuncPtr.
FuncPtr is the address of the callback function. CallBackRef is a user data item that will be passed to the callback function when it is invoked. Priority - Priority for the interrupt None
References XTimerTag::CallBackRef, XTimerTag::Handler, XTimerTag::XTimer_TickIntrHandler.
void XTimer_SetInterval(unsigned long delay)
This API sets the elapse interval for the timer instance.
delay Delay time in milliseconds none none
References XTimerTag::XTimer_TickInterval.
void XTimer_ClearTickInterrupt(void)
This API clears the interrupt status of the tick timer instance.
none none
References XTimerTag::XTickTimer_ClearInterrupt.
MAX_COUNT
The ScuTimer typically operates with a 32-bit counter, and this value represents the maximum possible count that can be stored in that counter.
REG_SHIFT
the shift amount used when concatenating two registers to form a 64-bit value.
the shift amount is 32, indicating a 16-bit register width.
XCntrVal
the type used to represent the value of a timer counter.
Depending on the architecture being targeted, it is a 16-bit unsigned integer (u16).