xiltimer.c
XTimer TimerInst
void XilTimer_Sleep(unsigned long delay, XTimer_DelayType DelayType)
This API contains common delay implementation using library API's.
none none
References XTimerTag::XTimer_ModifyInterval.
Referenced by msleep, sleep, usleep.
void sleep(unsigned int seconds)
This API gives delay in sec.
seconds Delay time in seconds none none
References XilTimer_Sleep, XTIMER_DELAY_SEC.
void msleep(unsigned long mseconds)
This API gives delay in msec.
mseconds Delay time in milliseconds none none
References XilTimer_Sleep, XTIMER_DELAY_MSEC.
void usleep(unsigned long useconds)
This API gives delay in usec.
useconds Delay time in microseconds none none
References XilTimer_Sleep, XTIMER_DELAY_USEC.
void xtimerinit()
This API initializes the xiltimer library through constructor.
none
References XilSleepTimer_Init, XilTickTimer_Init.
void XTimer_SetHandler(XTimer_TickHandler FuncPtr, void *CallBackRef, u8 Priority)
This routine installs an asynchronous callback function for the given FuncPtr.
FuncPtr is the address of the callback function. CallBackRef is a user data item that will be passed to the callback function when it is invoked. Priority - Priority for the interrupt None
References XTimerTag::CallBackRef, XTimerTag::Handler, XTimerTag::XTimer_TickIntrHandler.
void XTimer_SetInterval(unsigned long delay)
This API sets the elapse interval for the timer instance.
delay Delay time in milliseconds none none
References XTimerTag::XTimer_TickInterval.
void XTimer_ClearTickInterrupt(void)
This API clears the interrupt status of the tick timer instance.
none none
References XTimerTag::XTickTimer_ClearInterrupt.