xv_hdmitx_vsif.c
int XV_HdmiTx_VSIF_Extract3DInfo(u8 *VSIFRaw, XV_HdmiTx_3D_Info *InstancePtr)
This function extracts the 3D information from the Vendor Specific InfoFrame (VSIF).
VSIFRaw is a pointer to the VSIF payload. InstancePtr is a pointer to the XV_HdmiTx_3D_Info instance. XST_SUCCESS if operation was successfulXST_FAILURE if an error was detected during parsing
static XV_HdmiTx_3D_Struct_Field XV_HdmiTx_VSIF_Conv3DInfoTo3DStruct(XVidC_3DInfo *InfoPtr)
This function extracts the 3D format from XVidC_3DInfo and returns a XV_HdmiTx_3D_Struct_Field type.
InfoPtr is a pointer to the XVidC_3DInfo instance. The extracted value.
static XV_HdmiTx_3D_Sampling_Method XV_HdmiTx_VSIF_Conv3DInfoTo3DSampMethod(XVidC_3DInfo *InfoPtr)
This function extracts the sampling method info from XVidC_3DInfo and returns a XV_HdmiTx_3D_Sampling_Method type.
InfoPtr is a pointer to the XVidC_3DInfo instance. The extracted value.
static XV_HdmiTx_3D_Sampling_Position XV_HdmiTx_VSIF_Conv3DInfoTo3DSampPos(XVidC_3DInfo *InfoPtr)
This function extracts the sampling position info from XVidC_3DInfo and returns a XV_HdmiTx_3D_Sampling_Position type.
InfoPtr is a pointer to the XVidC_3DInfo instance. The extracted value.
static XVidC_3DFormat XV_HdmiTx_VSIF_Conv3DStructTo3DFormat(XV_HdmiTx_3D_Struct_Field Value)
This function converts a XV_HdmiTx_3D_Struct_Field type to a XVidC_3DFormat type.
Value is the value to convert. The converted value.
static XVidC_3DSamplingMethod XV_HdmiTx_VSIF_Conv3DSampMethodTo3DSampMethod(XV_HdmiTx_3D_Sampling_Method Value)
This function converts a XV_HdmiTx_3D_Sampling_Method type to a XVidC_3DSamplingMethod type.
Value is the value to convert. The converted value.
static XVidC_3DSamplingPosition XV_HdmiTx_VSIF_Conv3DSampPosTo3DSampPos(XV_HdmiTx_3D_Sampling_Position Value)
This function converts a XV_HdmiTx_3D_Sampling_Position type to a XVidC_3DSamplingPosition type.
Value is the value to convert. The converted value.
int XV_HdmiTx_VSIF_ParsePacket(XHdmiC_Aux *AuxPtr, XV_HdmiTx_VSIF *VSIFPtr)
This function parses a Vendor Specific InfoFrame (VSIF).
AuxPtr is a pointer to the XV_HdmiTx_Rx_Aux instance. VSIFPtr is a pointer to the XV_HdmiTx_VSIF instance. XST_SUCCESS if operation was successfulXST_FAILURE if an error was detected during parsing
References XV_HdmiTx_VSIF::Format, XV_HdmiTx_VSIF::HDMI_VIC, XV_HdmiTx_VSIF::IEEE_ID, XV_HdmiTx_VSIF::Info_3D, XV_HdmiTx_VSIF::Version, XV_HDMITX_VSIF_VF_3D, XV_HDMITX_VSIF_VF_EXTRES, XV_HDMITX_VSIF_VF_NOINFO, XV_HDMITX_VSIF_VIDEO_FORMAT_MASK, XV_HDMITX_VSIF_VIDEO_FORMAT_SHIFT.
int XV_HdmiTx_VSIF_GeneratePacket(XV_HdmiTx_VSIF *VSIFPtr, XHdmiC_Aux *AuxPtr)
This function generates a Vendor Specific InfoFrame (VSIF).
VSIFPtr is a pointer to the XV_HdmiTx_VSIF instance. AuxPtr is a pointer to the XV_HdmiTx_Tx_Aux instance. XST_SUCCESS if operation was successfulXST_FAILURE if an error was detected during generation
References XV_HdmiTx_3D_MetaData::Data, XV_HdmiTx_VSIF::Format, XV_HdmiTx_VSIF::HDMI_VIC, XV_HdmiTx_VSIF::IEEE_ID, XV_HdmiTx_VSIF::Info_3D, XV_HdmiTx_3D_MetaData::IsPresent, XV_HdmiTx_3D_MetaData::Length, XV_HdmiTx_3D_Info::MetaData, XV_HdmiTx_3D_MetaData::Type, XV_HdmiTx_VSIF::Version, XV_HDMITX_3D_META_LENGTH_MASK, XV_HDMITX_3D_META_LENGTH_SHIFT, XV_HDMITX_3D_META_PRESENT_SHIFT, XV_HDMITX_3D_META_TYPE_MASK, XV_HDMITX_3D_META_TYPE_SHIFT, XV_HDMITX_3D_SAMP_METHOD_MASK, XV_HDMITX_3D_SAMP_METHOD_SHIFT, XV_HDMITX_3D_SAMP_POS_MASK, XV_HDMITX_3D_SAMP_POS_SHIFT, XV_HDMITX_3D_STRUCT_MASK, XV_HDMITX_3D_STRUCT_SHIFT, XV_HDMITX_3D_STRUCT_SIDE_BY_SIDE_HALF, XV_HDMITX_VSIF_VF_3D, XV_HDMITX_VSIF_VF_EXTRES, XV_HDMITX_VSIF_VIDEO_FORMAT_MASK, XV_HDMITX_VSIF_VIDEO_FORMAT_SHIFT.
void XV_HdmiTx_VSIF_DisplayInfo(XV_HdmiTx_VSIF *VSIFPtr)
This function displays the contents of an XV_HdmiTx_VSIF instance.
VSIFPtr is a pointer to the XV_HdmiTx_VSIF instance. None.
References XV_HdmiTx_VSIF::Format, XV_HdmiTx_VSIF::HDMI_VIC, XV_HdmiTx_VSIF::Info_3D, XV_HdmiTx_3D_MetaData::IsPresent, XV_HdmiTx_3D_Info::MetaData, XV_HDMITX_3D_STRUCT_SIDE_BY_SIDE_HALF, XV_HdmiTx_VSIF_3DSampMethodToString, XV_HdmiTx_VSIF_3DSampPosToString, XV_HdmiTx_VSIF_3DStructToString, XV_HDMITX_VSIF_VF_3D, XV_HDMITX_VSIF_VF_EXTRES.
char* XV_HdmiTx_VSIF_3DStructToString(XV_HdmiTx_3D_Struct_Field Item)
This function returns a string representation of the enumerated type XV_HdmiTx_3D_Struct_Field.
Item specifies the value to convert. Pointer to the converted string.
References XV_HDMITX_3D_STRUCT_FIELD_ALTERNATIVE, XV_HDMITX_3D_STRUCT_FRAME_PACKING, XV_HDMITX_3D_STRUCT_L_DEPTH, XV_HDMITX_3D_STRUCT_L_DEPTH_GRAPH_GDEPTH, XV_HDMITX_3D_STRUCT_LINE_ALTERNATIVE, XV_HDMITX_3D_STRUCT_SIDE_BY_SIDE_FULL, XV_HDMITX_3D_STRUCT_SIDE_BY_SIDE_HALF, XV_HDMITX_3D_STRUCT_TOP_AND_BOTTOM.
Referenced by XV_HdmiTx_VSIF_DisplayInfo.
char* XV_HdmiTx_VSIF_3DSampMethodToString(XV_HdmiTx_3D_Sampling_Method Item)
This function returns a string representation of the enumerated type XV_HdmiTx_3D_Sampling_Method.
Item specifies the value to convert. Pointer to the converted string.
References XV_HDMITX_3D_SAMPLING_HORIZONTAL, XV_HDMITX_3D_SAMPLING_QUINCUNX.
Referenced by XV_HdmiTx_VSIF_DisplayInfo.
char* XV_HdmiTx_VSIF_3DSampPosToString(XV_HdmiTx_3D_Sampling_Position Item)
This function returns a string representation of the enumerated type XV_HdmiTx_3D_Sampling_Position.
Item specifies the value to convert. Pointer to the converted string.
References XV_HDMITX_3D_SAMPPOS_ELER, XV_HDMITX_3D_SAMPPOS_ELOR, XV_HDMITX_3D_SAMPPOS_OLER, XV_HDMITX_3D_SAMPPOS_OLOR.
Referenced by XV_HdmiTx_VSIF_DisplayInfo.