xv_hdmitx.h
XV_HdmiTx_HandlerType
XV_HDMITX_H_
Prevent circular inclusions by using protection macros.
XV_HdmiTx_GetTime1Ms
This macro returns the clock cycles required to count up to 1MS with respect to AXI Lite Frequency.
InstancePtr is a pointer to the XV_HdmiTX core instance. None.
Referenced by XV_HdmiTx_CfgInitialize.
XV_HdmiTx_GetVersion
This macro reads the TX version.
InstancePtr is a pointer to the XV_HdmiTX core instance. None.
XV_HdmiTx_Reset
This macro asserts or releases the HDMI TX reset.
InstancePtr is a pointer to the XV_HdmiTx core instance. Reset specifies TRUE/FALSE value to either assert or release HDMI TX reset. None. The reset output of the PIO is inverted. When the system is in reset, the PIO output is cleared and this will reset the HDMI RX. Therefore, clearing the PIO reset output will assert the HDMI link and video reset. C-style signature: void XV_HdmiTx_Reset(XV_HdmiTx *InstancePtr, u8 Reset)
XV_HdmiTx_SetScrambler
This macro controls the HDMI TX Scrambler.
InstancePtr is a pointer to the XV_HdmiTx core instance. SetClr specifies TRUE/FALSE value to either set ON or clear Scrambler. None. C-style signature: void XV_HdmiTx_SetScrambler(XV_HdmiTx *InstancePtr, u8 SetClr)
Referenced by XV_HdmiTx_Scrambler.
XV_HdmiTx_Bridge_yuv420
This macro controls the YUV420 mode for video bridge.
InstancePtr is a pointer to the XHdmi_Tx core instance. SetClr specifies TRUE/FALSE value to either enable or disable the YUV 420 Support. None. C-style signature: void XV_HdmiTx_Bridge_yuv420(XV_HdmiTx *InstancePtr, u8 SetClr)
XV_HdmiTx_Bridge_pixel
This macro controls the Pixel Repeat mode for video bridge.
InstancePtr is a pointer to the XHdmi_Tx core instance. SetClr specifies TRUE/FALSE value to either enable or disable the Pixel Repetition Support. None. C-style signature: void XV_HdmiTx_Bridge_pixel(XV_HdmiTx *InstancePtr, u8 SetClr)
XV_HdmiTx_PioEnable
This macro enables the HDMI TX PIO peripheral.
InstancePtr is a pointer to the XV_HdmiTx core instance. None. C-style signature: void XV_HdmiTx_PioEnable(XV_HdmiTx *InstancePtr)
Referenced by XV_HdmiTx_CfgInitialize.
XV_HdmiTx_PioDisable
This macro disables the HDMI TX PIO peripheral.
InstancePtr is a pointer to the XV_HdmiTx core instance. None. C-style signature: void XV_HdmiTx_PioDisable(XV_HdmiTx *InstancePtr)
Referenced by XV_HdmiTx_CfgInitialize.
XV_HdmiTx_PioIntrEnable
This macro enables interrupt in the HDMI TX PIO peripheral.
InstancePtr is a pointer to the XV_HdmiTx core instance. None. C-style signature: void XV_HdmiTx_PioIntrEnable(XV_HdmiTx *InstancePtr)
Referenced by XV_HdmiTx_CfgInitialize, XV_HdmiTx_DdcRead, XV_HdmiTx_DdcWrite.
XV_HdmiTx_PioIntrDisable
This macro disables interrupt in the HDMI TX PIO peripheral.
InstancePtr is a pointer to the XV_HdmiTx core instance. None. C-style signature: void XV_HdmiTx_PioIntrDisable(XV_HdmiTx *InstancePtr)
Referenced by XV_HdmiTx_DdcRead, XV_HdmiTx_DdcWrite.
XV_HdmiTx_PioIntrClear
This macro clears HDMI TX PIO interrupt.
InstancePtr is a pointer to the XV_HdmiTx core instance. None. C-style signature: void XV_HdmiTx_PioIntrClear(XV_HdmiTx *InstancePtr)
Referenced by XV_HdmiTx_CfgInitialize.
XV_HdmiTx_DdcEnable
This macro enables the HDMI TX Display Data Channel (DDC) peripheral.
InstancePtr is a pointer to the XV_HdmiTx core instance. None. C-style signature: void XV_HdmiTx_DdcEnable(XV_HdmiTx *InstancePtr)
Referenced by XV_HdmiTx_DdcRead, XV_HdmiTx_DdcWrite.
XV_HdmiTx_DdcDisable
This macro disables the HDMI TX Display Data Channel (DDC) peripheral.
InstancePtr is a pointer to the XV_HdmiTx core instance. None. C-style signature: void XV_HdmiTx_DdcDisable(XV_HdmiTx *InstancePtr)
Referenced by XV_HdmiTx_CfgInitialize, XV_HdmiTx_DdcRead, XV_HdmiTx_DdcWrite.
XV_HdmiTx_DdcIntrEnable
This macro enables interrupt in the HDMI TX DDC peripheral.
InstancePtr is a pointer to the XV_HdmiTx core instance. None. C-style signature: void XV_HdmiTx_DdcIntrEnable(XV_HdmiTx *InstancePtr)
XV_HdmiTx_DdcIntrDisable
This macro disables interrupt in the HDMI TX DDC peripheral.
InstancePtr is a pointer to the XV_HdmiTx core instance. None. C-style signature: void XV_HdmiTx_DdcIntrDisable(XV_HdmiTx *InstancePtr)
Referenced by XV_HdmiTx_DdcRead, XV_HdmiTx_DdcWrite.
XV_HdmiTx_DdcIntrClear
This macro clears HDMI TX DDC interrupt.
InstancePtr is a pointer to the XV_HdmiTx core instance. None. C-style signature: void XV_HdmiTx_DdcIntrClear(XV_HdmiTx *InstancePtr)
Referenced by XV_HdmiTx_CfgInitialize.
XV_HdmiTx_AuxEnable
This macro enables the HDMI TX Auxiliary (AUX) peripheral.
InstancePtr is a pointer to the XV_HdmiTx core instance. None. C-style signature: void XV_HdmiTx_AuxEnable(XV_HdmiTx *InstancePtr)
Referenced by XV_HdmiTx_SetHdmiMode.
XV_HdmiTx_AuxDisable
This macro disables the HDMI TX Auxiliary (AUX) peripheral.
InstancePtr is a pointer to the XV_HdmiTx core instance. None. C-style signature: void XV_HdmiTx_AuxDisable(XV_HdmiTx *InstancePtr)
Referenced by XV_HdmiTx_CfgInitialize, XV_HdmiTx_SetDviMode.
XV_HdmiTx_AuxIntrEnable
This macro enables interrupt in the HDMI TX AUX peripheral.
InstancePtr is a pointer to the XV_HdmiTx core instance. None. C-style signature: void XV_HdmiTx_AuxIntrEnable(XV_HdmiTx *InstancePtr)
XV_HdmiTx_AuxIntrDisable
This macro disables interrupt in the HDMI TX AUX peripheral.
InstancePtr is a pointer to the XV_HdmiTx core instance. None. C-style signature: void XV_HdmiTx_AuxIntrDisable(XV_HdmiTx *InstancePtr)
XV_HdmiTx_AudioEnable
This macro enables audio in HDMI TX core.
InstancePtr is a pointer to the XV_HdmiTx core instance. None. C-style signature: void XV_HdmiTx_AudioEnable(XV_HdmiTx *InstancePtr)
Referenced by XV_HdmiTx_SetHdmiMode.
XV_HdmiTx_AudioDisable
This macro disables audio in HDMI TX core.
InstancePtr is a pointer to the XV_HdmiTx core instance. None. C-style signature: void XV_HdmiTx_AudioDisable(XV_HdmiTx *InstancePtr)
Referenced by XV_HdmiTx_CfgInitialize, XV_HdmiTx_SetDviMode.
XV_HdmiTx_AudioUnmute
This macro unmutes audio in HDMI TX core.
InstancePtr is a pointer to the XV_HdmiTx core instance. None. C-style signature: void XV_HdmiTx_AudioUnmute(XV_HdmiTx *InstancePtr) DeprecatedXV_HdmiTx_AudioUnmute will be deprecated in 2019.3 and replaced by XV_HdmiTx_AudioEnable.
XV_HdmiTx_AudioMute
This macro mutes audio in HDMI TX core.
InstancePtr is a pointer to the XV_HdmiTx core instance. None. C-style signature: void XV_HdmiTx_AudioMute(XV_HdmiTx *InstancePtr) DeprecatedXV_HdmiTx_AudioMute will be deprecated in 2019.3 and replaced by XV_HdmiTx_AudioDisable.
XV_HdmiTx_SetMode
This macro sets the mode bit.
InstancePtr is a pointer to the XV_HdmiTx core instance. None. C-style signature: void XV_HdmiTx_SetMode(XV_HdmiTx *InstancePtr)
Referenced by XV_HdmiTx_SetHdmiMode.
XV_HdmiTx_ClearMode
This macro clears the mode bit.
InstancePtr is a pointer to the XV_HdmiTx core instance. None. C-style signature: void XV_HdmiTx_ClearMode(XV_HdmiTx *InstancePtr)
Referenced by XV_HdmiTx_SetDviMode.
XV_HdmiTx_GetMode
This macro provides the current mode.
InstancePtr is a pointer to the XV_HdmiTx core instance. Current mode. 0 = DVI 1 = HDMI C-style signature: u8 XV_HdmiTx_GetMode(XV_HdmiTx *InstancePtr)
XV_HdmiTx_GetSampleRate
This macro provides the current sample rate.
InstancePtr is a pointer to the XV_HdmiTx core instance. Sample rate C-style signature: u8 XV_HdmiTx_GetSampleRate(XV_HdmiTx *InstancePtr)
XV_HdmiTx_GetAudioChannels
This macro provides the active audio channels.
InstancePtr is a pointer to the XV_HdmiTx core instance. Audio channels
XV_HdmiTx_GetPixelPackingPhase
This macro provides the current pixel packing phase.
InstancePtr is a pointer to the XV_HdmiTx core instance. Pixel packing phase.
XV_HdmiTx_MaskDisable
This macro disables video mask in HDMI TX core.
InstancePtr is a pointer to the XV_HdmiTx core instance. None. C-style signature: void XV_HdmiTx_MaskDisable(XV_HdmiTx *InstancePtr)
XV_HdmiTx_MaskEnable
This macro enables video mask in HDMI TX core.
InstancePtr is a pointer to the XV_HdmiTx core instance. None. C-style signature: void XV_HdmiTx_MaskEnable(XV_HdmiTx *InstancePtr)
XV_HdmiTx_MaskNoise
This macro enables or disables the noise in the video mask.
InstancePtr is a pointer to the XHdmi_Tx core instance. SetClr specifies TRUE/FALSE value to either enable or disable the Noise. None. C-style signature: void XV_HdmiTx_MaskNoise(XV_HdmiTx *InstancePtr, u8 SetClr)
XV_HdmiTx_MaskSetRed
This macro sets the red component value in the video mask.
InstancePtr is a pointer to the XHdmi_Tx core instance. Value None. C-style signature: void XV_HdmiTx_MaskSetRed(XV_HdmiTx *InstancePtr, u16 Value)
XV_HdmiTx_MaskSetGreen
This macro sets the green component value in the video mask.
InstancePtr is a pointer to the XHdmi_Tx core instance. Value None. C-style signature: void XV_HdmiTx_MaskSetGreen(XV_HdmiTx *InstancePtr, u16 Value)
XV_HdmiTx_MaskSetBlue
This macro sets the blue component value in the video mask.
InstancePtr is a pointer to the XHdmi_Tx core instance. Value None. C-style signature: void XV_HdmiTx_MaskSetBlue(XV_HdmiTx *InstancePtr, u16 Value)
XV_HdmiTx_IsMasked
This macro provides the current video mask mode.
InstancePtr is a pointer to the XV_HdmiTx core instance. Current mode. 0 = Video masking is disabled 1 = Video masking is enabled C-style signature: u8 XV_HdmiTx_IsMasked(XV_HdmiTx *InstancePtr)
XV_HdmiTx_State
Stream down.
XV_HdmiTx_AudioFormatType
L-PCM audio format.
typedef void(* XV_HdmiTx_Callback)(void *CallbackRef))(void *CallbackRef)
Callback type for Vsync event interrupt.
CallbackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. None. None.
XV_HdmiTx_Config* XV_HdmiTx_LookupConfig(UINTPTR BaseAddress)
This function returns a reference to an XV_HdmiTx_Config structure based on the core id, DeviceId.
The return value will refer to an entry in the device configuration table defined in the xv_hdmitx_g.c file. DeviceId is the unique core ID of the HDMI TX core for the lookup operation. XV_HdmiTx_LookupConfig returns a reference to a config record in the configuration table (in xv_hdmitx_g.c) corresponding to DeviceId, or NULL if no match is found. None.
int XV_HdmiTx_CfgInitialize(XV_HdmiTx *InstancePtr, XV_HdmiTx_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the HDMI TX core.
This function must be called prior to using the HDMI TX core. Initialization of the HDMI TX includes setting up the instance data and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the XV_HdmiTx core instance. CfgPtr points to the configuration structure associated with the HDMI TX core. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if XV_HdmiTx_CfgInitialize was successful.XST_FAILURE if HDMI TX PIO ID mismatched. None.
References XV_HdmiTx_Config::BaseAddress, XV_HdmiTx::Config, XV_HdmiTx::ConnectCallback, XV_HdmiTx::IsConnectCallbackSet, XV_HdmiTx_Stream::IsConnected, XV_HdmiTx::IsReady, XV_HdmiTx::IsStreamDownCallbackSet, XV_HdmiTx::IsStreamUpCallbackSet, XV_HdmiTx::IsToggleCallbackSet, XV_HdmiTx::IsVsCallbackSet, XV_HdmiTx_Stream::OverrideScrambler, XV_HdmiTx_Stream::State, XV_HdmiTx::Stream, XV_HdmiTx::StreamDownCallback, XV_HdmiTx::StreamUpCallback, XV_HdmiTx::ToggleCallback, XV_HdmiTx::VsCallback, XV_HdmiTx_AudioDisable, XV_HdmiTx_AuxDisable, XV_HdmiTx_Clear, XV_HDMITX_CONNECT_CONF_OFFSET, XV_HdmiTx_DdcDisable, XV_HdmiTx_DdcIntrClear, XV_HdmiTx_GetTime1Ms, XV_HDMITX_HPD_TIMEGRID_OFFSET, XV_HDMITX_MASK_16, XV_HDMITX_PIO_ID, XV_HDMITX_PIO_ID_OFFSET, XV_HDMITX_PIO_IN_BRDG_LOCKED_MASK, XV_HDMITX_PIO_IN_BRDG_OVERFLOW_MASK, XV_HDMITX_PIO_IN_BRDG_UNDERFLOW_MASK, XV_HDMITX_PIO_IN_EVT_FE_OFFSET, XV_HDMITX_PIO_IN_EVT_RE_OFFSET, XV_HDMITX_PIO_IN_HPD_MASK, XV_HDMITX_PIO_IN_HPD_TOGGLE_MASK, XV_HDMITX_PIO_IN_LNK_RDY_MASK, XV_HDMITX_PIO_IN_VS_MASK, XV_HdmiTx_PioDisable, XV_HdmiTx_PioEnable, XV_HdmiTx_PioIntrClear, XV_HdmiTx_PioIntrEnable, XV_HdmiTx_ReadReg, XV_HdmiTx_SetHdmiMode, XV_HDMITX_SHIFT_16, XV_HDMITX_STATE_STREAM_DOWN, XV_HDMITX_TOGGLE_CONF_OFFSET, XV_HdmiTx_WriteReg.
void XV_HdmiTx_SetHdmiMode(XV_HdmiTx *InstancePtr)
This function sets the core into HDMI mode.
InstancePtr is a pointer to the XV_HdmiTx core instance. This is required after a reset or init.
References XV_HdmiTx_Stream::IsHdmi, XV_HdmiTx::Stream, XV_HdmiTx_AudioEnable, XV_HdmiTx_AuxEnable, XV_HdmiTx_SetMode.
Referenced by XV_HdmiTx_CfgInitialize.
void XV_HdmiTx_SetDviMode(XV_HdmiTx *InstancePtr)
This function sets the core into DVI mode.
InstancePtr is a pointer to the XV_HdmiTx core instance. This is required after a reset or init.
References XV_HdmiTx_Stream::IsHdmi, XV_HdmiTx::Stream, XV_HdmiTx_AudioDisable, XV_HdmiTx_AuxDisable, XV_HdmiTx_ClearMode.
void XV_HdmiTx_Clear(XV_HdmiTx *InstancePtr)
This function clear the HDMI TX variables and sets it to the defaults.
InstancePtr is a pointer to the XV_HdmiTx core instance. This is required after a reset or init.
Referenced by XV_HdmiTx_CfgInitialize.
u8 XV_HdmiTx_GetVic(XVidC_VideoMode VideoMode)
XVidC_VideoMode XV_HdmiTx_GetVideoModeFromVic(u8 Vic)
u32 XV_HdmiTx_SetStream(XV_HdmiTx *InstancePtr, XVidC_VideoMode VideoMode, XVidC_ColorFormat ColorFormat, XVidC_ColorDepth Bpc, XVidC_PixelsPerClock Ppc, XVidC_3DInfo *Info3D)
This function sets the HDMI TX stream parameters.
InstancePtr is a pointer to the XV_HdmiTx core instance. VideoMode specifies resolution identifier. ColorFormat specifies the type of color format. 0 = XVIDC_CSF_RGB1 = XVIDC_CSF_YCRCB_4442 = XVIDC_CSF_YCRCB_4223 = XVIDC_CSF_YCRCB_420 Bpc specifies the color depth/bits per color component. 6 = XVIDC_BPC_68 = XVIDC_BPC_810 = XVIDC_BPC_1012 = XVIDC_BPC_1216 = XVIDC_BPC_16 Ppc specifies the pixel per clock. 1 = XVIDC_PPC_12 = XVIDC_PPC_24 = XVIDC_PPC_4 Info3D is a pointer to 3D info structure or NULL for 2D. TmdsClock, reference clock calculated based on the input parameters. None.
References XV_HdmiTx_Stream::IsHdmi20, XV_HdmiTx_Stream::IsScrambled, XV_HdmiTx::Stream, XV_HdmiTx_Stream::TMDSClock, XV_HdmiTx_Stream::TMDSClockRatio, XV_HdmiTx_Stream::Vic, XV_HdmiTx_Stream::Video, XV_HdmiTx_ClockRatio, XV_HdmiTx_GetTmdsClk, XV_HdmiTx_LookupVic, XV_HdmiTx_Scrambler, XV_HdmiTx_SetColorDepth, XV_HdmiTx_SetColorFormat, XV_HdmiTx_SetPixelRate.
u32 XV_HdmiTx_GetTmdsClk(XV_HdmiTx *InstancePtr, XVidC_VideoMode VideoMode, XVidC_ColorFormat ColorFormat, XVidC_ColorDepth Bpc)
This function sets and return the TMDS Clock based on Video Parameter.
InstancePtr is a pointer to the XV_HdmiTx core instance. VideoMode specifies resolution identifier. ColorFormat specifies the type of color format. 0 = XVIDC_CSF_RGB1 = XVIDC_CSF_YCRCB_4442 = XVIDC_CSF_YCRCB_4223 = XVIDC_CSF_YCRCB_420 Bpc specifies the color depth/bits per color component. 6 = XVIDC_BPC_68 = XVIDC_BPC_810 = XVIDC_BPC_1012 = XVIDC_BPC_1216 = XVIDC_BPC_16 TMDS Clock None.
References XV_HdmiTx_Stream::PixelClk, XV_HdmiTx::Stream.
Referenced by XV_HdmiTx_SetStream.
void XV_HdmiTx_INT_VRST(XV_HdmiTx *InstancePtr, u8 Reset)
This function asserts or releases the HDMI TX Internal VRST.
InstancePtr is a pointer to the XV_HdmiTx core instance. Reset specifies TRUE/FALSE value to either assert or release HDMI TX Internal VRST. None. The reset output of the PIO is inverted. When the system is in reset, the PIO output is cleared and this will reset the HDMI TX. Therefore, clearing the PIO reset output will assert the HDMI Internal video reset. C-style signature: void XV_HdmiTx_INT_VRST(XV_HdmiTx *InstancePtr, u8 Reset)
References XV_HDMITX_PIO_OUT_CLR_OFFSET, XV_HDMITX_PIO_OUT_INT_VRST_MASK, XV_HDMITX_PIO_OUT_SET_OFFSET, XV_HdmiTx_WriteReg.
void XV_HdmiTx_INT_LRST(XV_HdmiTx *InstancePtr, u8 Reset)
This function asserts or releases the HDMI TX Internal LRST.
InstancePtr is a pointer to the XV_HdmiTx core instance. Reset specifies TRUE/FALSE value to either assert or release HDMI TX Internal LRST. None. The reset output of the PIO is inverted. When the system is in reset, the PIO output is cleared and this will reset the HDMI TX. Therefore, clearing the PIO reset output will assert the HDMI Internal link reset. C-style signature: void XV_HdmiTx_INT_VRST(XV_HdmiTx *InstancePtr, u8 Reset)
References XV_HDMITX_PIO_OUT_CLR_OFFSET, XV_HDMITX_PIO_OUT_INT_LRST_MASK, XV_HDMITX_PIO_OUT_SET_OFFSET, XV_HdmiTx_WriteReg.
void XV_HdmiTx_EXT_VRST(XV_HdmiTx *InstancePtr, u8 Reset)
This function asserts or releases the HDMI TX External VRST.
InstancePtr is a pointer to the XV_HdmiTx core instance. Reset specifies TRUE/FALSE value to either assert or release HDMI TX External VRST. None. The reset output of the PIO is inverted. When the system is in reset, the PIO output is cleared and this will reset the HDMI TX. Therefore, clearing the PIO reset output will assert the HDMI external video reset. C-style signature: void XV_HdmiTx_EXT_VRST(XV_HdmiTx *InstancePtr, u8 Reset)
References XV_HDMITX_PIO_OUT_CLR_OFFSET, XV_HDMITX_PIO_OUT_EXT_VRST_MASK, XV_HDMITX_PIO_OUT_SET_OFFSET, XV_HdmiTx_WriteReg.
void XV_HdmiTx_EXT_SYSRST(XV_HdmiTx *InstancePtr, u8 Reset)
This function asserts or releases the HDMI TX External SYSRST.
InstancePtr is a pointer to the XV_HdmiTx core instance. Reset specifies TRUE/FALSE value to either assert or release HDMI TX External SYSRST. None. The reset output of the PIO is inverted. When the system is in reset, the PIO output is cleared and this will reset the HDMI TX. Therefore, clearing the PIO reset output will assert the HDMI External system reset. C-style signature: void XV_HdmiTx_EXT_SYSRST(XV_HdmiTx *InstancePtr, u8 Reset)
References XV_HDMITX_PIO_OUT_CLR_OFFSET, XV_HDMITX_PIO_OUT_EXT_SYSRST_MASK, XV_HDMITX_PIO_OUT_SET_OFFSET, XV_HdmiTx_WriteReg.
void XV_HdmiTx_SetGcpAvmuteBit(XV_HdmiTx *InstancePtr)
This function sets the HDMI TX AUX GCP register AVMUTE bit.
InstancePtr is a pointer to the XV_HdmiTx core instance. None. None.
References XV_HDMITX_PIO_OUT_GCP_AVMUTE_MASK, XV_HDMITX_PIO_OUT_SET_OFFSET, XV_HdmiTx_WriteReg.
void XV_HdmiTx_ClearGcpAvmuteBit(XV_HdmiTx *InstancePtr)
This function clears the HDMI TX AUX GCP register AVMUTE bit.
InstancePtr is a pointer to the XV_HdmiTx core instance. None. None.
References XV_HDMITX_PIO_OUT_CLR_OFFSET, XV_HDMITX_PIO_OUT_GCP_AVMUTE_MASK, XV_HdmiTx_WriteReg.
void XV_HdmiTx_SetGcpClearAvmuteBit(XV_HdmiTx *InstancePtr)
This function sets the HDMI TX AUX GCP register CLEAR_AVMUTE bit.
InstancePtr is a pointer to the XV_HdmiTx core instance. None. None.
References XV_HDMITX_PIO_OUT_GCP_CLEARAVMUTE_MASK, XV_HDMITX_PIO_OUT_SET_OFFSET, XV_HdmiTx_WriteReg.
void XV_HdmiTx_ClearGcpClearAvmuteBit(XV_HdmiTx *InstancePtr)
This function clears the HDMI TX AUX GCP register CLEAR_AVMUTE bit.
InstancePtr is a pointer to the XV_HdmiTx core instance. None. None.
References XV_HDMITX_PIO_OUT_CLR_OFFSET, XV_HDMITX_PIO_OUT_GCP_CLEARAVMUTE_MASK, XV_HdmiTx_WriteReg.
void XV_HdmiTx_SetPixelRate(XV_HdmiTx *InstancePtr)
This function sets the pixel rate at output.
InstancePtr is a pointer to the XV_HdmiTx core instance. None. None.
References XV_HdmiTx_Config::BaseAddress, XV_HdmiTx::Config, XV_HdmiTx::Stream, XV_HdmiTx_Stream::Video, XV_HDMITX_PIO_OUT_MSK_OFFSET, XV_HDMITX_PIO_OUT_OFFSET, XV_HDMITX_PIO_OUT_PIXEL_RATE_MASK, XV_HDMITX_PIO_OUT_PIXEL_RATE_SHIFT, XV_HdmiTx_WriteReg.
Referenced by XV_HdmiTx_SetStream.
void XV_HdmiTx_SetSampleRate(XV_HdmiTx *InstancePtr, u8 SampleRate)
This function sets the sample rate at output.
InstancePtr is a pointer to the XV_HdmiTx core instance. SampleRate specifies the value that needs to be set. 2 samples per clock3 samples per clock.5 samples per clock. None. None.
References XV_HdmiTx_Config::BaseAddress, XV_HdmiTx::Config, XV_HdmiTx_Stream::SampleRate, XV_HdmiTx::Stream, XV_HDMITX_PIO_OUT_MSK_OFFSET, XV_HDMITX_PIO_OUT_OFFSET, XV_HDMITX_PIO_OUT_SAMPLE_RATE_MASK, XV_HDMITX_PIO_OUT_SAMPLE_RATE_SHIFT, XV_HdmiTx_WriteReg.
void XV_HdmiTx_SetColorFormat(XV_HdmiTx *InstancePtr)
This function sets the color format.
InstancePtr is a pointer to the XV_HdmiTx core instance. None. None.
References XV_HdmiTx_Config::BaseAddress, XV_HdmiTx::Config, XV_HdmiTx::Stream, XV_HdmiTx_Stream::Video, XV_HDMITX_PIO_OUT_COLOR_SPACE_MASK, XV_HDMITX_PIO_OUT_COLOR_SPACE_SHIFT, XV_HDMITX_PIO_OUT_MSK_OFFSET, XV_HDMITX_PIO_OUT_OFFSET, XV_HdmiTx_WriteReg.
Referenced by XV_HdmiTx_SetStream.
void XV_HdmiTx_SetColorDepth(XV_HdmiTx *InstancePtr)
This function sets the color depth.
InstancePtr is a pointer to the XV_HdmiTx core instance. None. None.
References XV_HdmiTx_Config::BaseAddress, XV_HdmiTx::Config, XV_HdmiTx::Stream, XV_HdmiTx_Stream::Video, XV_HDMITX_PIO_OUT_COLOR_DEPTH_MASK, XV_HDMITX_PIO_OUT_COLOR_DEPTH_SHIFT, XV_HDMITX_PIO_OUT_MSK_OFFSET, XV_HDMITX_PIO_OUT_OFFSET, XV_HdmiTx_WriteReg.
Referenced by XV_HdmiTx_SetStream.
int XV_HdmiTx_IsStreamScrambled(XV_HdmiTx *InstancePtr)
This function provides status of the stream.
InstancePtr is a pointer to the XV_HdmiTx core instance. TRUE = Scrambled.FALSE = Not scrambled. None.
References XV_HdmiTx_Stream::IsScrambled, XV_HdmiTx::Stream.
int XV_HdmiTx_IsStreamConnected(XV_HdmiTx *InstancePtr)
This function provides the stream connected status.
InstancePtr is a pointer to the XV_HdmiTx core instance. TRUE = Stream is connected.FALSE = Stream is connected. None.
References XV_HdmiTx_Stream::IsConnected, XV_HdmiTx::Stream.
void XV_HdmiTx_SetAxiClkFreq(XV_HdmiTx *InstancePtr, u32 ClkFreq)
This function sets the AXI4-Lite Clock Frequency.
InstancePtr is a pointer to the XV_HdmiTx core instance. ClkFreq specifies the value that needs to be set. This is required after a reset or init.
References XV_HdmiTx_DdcInit.
void XV_HdmiTx_DdcInit(XV_HdmiTx *InstancePtr, u32 Frequency)
This function prepares TX DDC peripheral to use.
InstancePtr is a pointer to the XV_HdmiTx core instance. Frequency specifies the value that needs to be set. None. None.
References XV_HdmiTx_Config::BaseAddress, XV_HdmiTx::Config, XV_HDMITX_DDC_CTRL_CLK_DIV_MASK, XV_HDMITX_DDC_CTRL_OFFSET, XV_HdmiTx_WriteReg.
Referenced by XV_HdmiTx_SetAxiClkFreq.
int XV_HdmiTx_DdcWrite(XV_HdmiTx *InstancePtr, u8 Slave, u16 Length, u8 *Buffer, u8 Stop)
This function writes data from DDC peripheral from given slave address.
InstancePtr is a pointer to the XV_HdmiTx core instance. Slave specifies the slave address from where data needs to be read. Length specifies number of bytes to be read. Buffer specifies a pointer to u8 variable that will be filled with data. Stop specifies the stop flag which is either TRUE/FALSE. XST_SUCCESS if an acknowledgement received and timeout.XST_FAILURE if no acknowledgement received. None.
References XV_HDMITX_DDC_CMD_STP_TOKEN, XV_HDMITX_DDC_CMD_STR_TOKEN, XV_HDMITX_DDC_CMD_WR_TOKEN, XV_HdmiTx_DdcDisable, XV_HdmiTx_DdcEnable, XV_HdmiTx_DdcGetAck, XV_HdmiTx_DdcIntrDisable, XV_HdmiTx_DdcWaitForDone, XV_HdmiTx_DdcWriteCommand, XV_HdmiTx_PioIntrDisable, XV_HdmiTx_PioIntrEnable.
Referenced by XV_HdmiTx_ClockRatio, XV_HdmiTx_DetectHdmi20, XV_HdmiTx_Scrambler, XV_HdmiTx_ShowSCDC.
int XV_HdmiTx_DdcRead(XV_HdmiTx *InstancePtr, u8 Slave, u16 Length, u8 *Buffer, u8 Stop)
This function reads data from DDC peripheral from given slave address.
InstancePtr is a pointer to the XV_HdmiTx core instance. Slave specifies the slave address from where data needs to be read. Length specifies number of bytes to be read. Buffer specifies a pointer to u8 variable that will be filled with data. Stop specifies the stop flag which is either TRUE/FALSE. XST_SUCCESS if an acknowledgement received and timeout.XST_FAILURE if no acknowledgement received. None.
References XV_HDMITX_DDC_CMD_RD_TOKEN, XV_HDMITX_DDC_CMD_STP_TOKEN, XV_HDMITX_DDC_CMD_STR_TOKEN, XV_HDMITX_DDC_CMD_WR_TOKEN, XV_HdmiTx_DdcDisable, XV_HdmiTx_DdcEnable, XV_HdmiTx_DdcGetAck, XV_HdmiTx_DdcIntrDisable, XV_HdmiTx_DdcReadData, XV_HdmiTx_DdcWaitForDone, XV_HdmiTx_DdcWriteCommand, XV_HdmiTx_PioIntrDisable, XV_HdmiTx_PioIntrEnable.
Referenced by XV_HdmiTx_ClockRatio, XV_HdmiTx_Scrambler, XV_HdmiTx_ShowSCDC.
u32 XV_HdmiTx_AuxSend(XV_HdmiTx *InstancePtr)
This function transmits the infoframes generated by the processor.
InstancePtr is a pointer to the XV_HdmiTx core instance. XST_SUCCESS if infoframes transmitted successfully.XST_FAILURE if AUX FIFO is full. None.
References XV_HdmiTx::Aux, XV_HdmiTx_Config::BaseAddress, XV_HdmiTx::Config, XV_HDMITX_AUX_DAT_OFFSET, XV_HDMITX_AUX_STA_FIFO_FUL_MASK, XV_HDMITX_AUX_STA_OFFSET, XV_HDMITX_AUX_STA_PKT_RDY_MASK, XV_HdmiTx_ReadReg, XV_HdmiTx_WriteReg.
int XV_HdmiTx_Scrambler(XV_HdmiTx *InstancePtr)
This function controls the scrambler.
Requires TMDSClock to be up to date in order to force enable scrambler when TMDSClock > 340MHz. InstancePtr is a pointer to the XV_HdmiTx core instance. XST_SUCCESS if HDMI 2.0XST_FAILURE if HDMI 1.4 None.
References XV_HdmiTx_Stream::IsHdmi20, XV_HdmiTx_Stream::IsScrambled, XV_HdmiTx_Stream::OverrideScrambler, XV_HdmiTx::Stream, XV_HdmiTx_Stream::TMDSClock, XV_HdmiTx_DdcRead, XV_HdmiTx_DdcWrite, XV_HdmiTx_SetScrambler.
Referenced by XV_HdmiTx_SetStream.
int XV_HdmiTx_ClockRatio(XV_HdmiTx *InstancePtr)
This function controls the TMDS clock ratio.
InstancePtr is a pointer to the XV_HdmiTx core instance. XST_SUCCESS if HDMI 2.0XST_FAILURE if HDMI 1.4 None.
References XV_HdmiTx_Stream::IsHdmi20, XV_HdmiTx::Stream, XV_HdmiTx_Stream::TMDSClockRatio, XV_HdmiTx_DdcRead, XV_HdmiTx_DdcWrite.
Referenced by XV_HdmiTx_SetStream.
int XV_HdmiTx_DetectHdmi20(XV_HdmiTx *InstancePtr)
This function detects connected sink is a HDMI 2.0/HDMI 1.4 sink device and sets appropriate flag in the TX stream.
InstancePtr is a pointer to the XV_HdmiTx core instance. XST_SUCCESS if HDMI 2.0XST_FAILURE if HDMI 1.4 None.
References XV_HdmiTx_Stream::IsHdmi20, XV_HdmiTx::Stream, XV_HdmiTx_DdcWrite.
void XV_HdmiTx_ShowSCDC(XV_HdmiTx *InstancePtr)
This function shows the sinks SCDC registers.
InstancePtr is a pointer to the XV_HdmiTx core instance. None. None.
References XV_HdmiTx_DdcRead, XV_HdmiTx_DdcWrite.
void XV_HdmiTx_DebugInfo(XV_HdmiTx *InstancePtr)
This function prints stream and timing information on STDIO/Uart console.
InstancePtr is a pointer to the XV_HdmiTx core instance. None. None.
References XV_HdmiTx::Stream, XV_HdmiTx_Stream::Video.
int XV_HdmiTx_SetAudioChannels(XV_HdmiTx *InstancePtr, u8 Value)
This function sets the active audio channels.
InstancePtr is a pointer to the XV_HdmiTx core instance. Value is the number of active audio channels (2, 4, 6, 8, 12, 24, 32). XST_SUCCESS if active channels were set.XST_FAILURE if no active channels were set. None.
References XV_HDMITX_AUD_CTRL_CH_MASK, XV_HDMITX_AUD_CTRL_CH_SHIFT, XV_HDMITX_AUD_CTRL_CLR_OFFSET, XV_HDMITX_AUD_CTRL_OFFSET, XV_HDMITX_AUD_CTRL_RUN_MASK, XV_HDMITX_AUD_CTRL_SET_OFFSET, XV_HdmiTx_ReadReg, XV_HdmiTx_WriteReg.
int XV_HdmiTx_SetAudioFormat(XV_HdmiTx *InstancePtr, XV_HdmiTx_AudioFormatType Value)
This function sets the active audio format.
InstancePtr is a pointer to the XV_HdmiTx core instance. Value is the audio format type to set. XST_SUCCESS if audio format was set.XST_FAILURE if audio format was not set. None.
References XV_HDMITX_AUD_CTRL_AUDFMT_MASK, XV_HDMITX_AUD_CTRL_AUDFMT_SHIFT, XV_HDMITX_AUD_CTRL_CLR_OFFSET, XV_HDMITX_AUD_CTRL_OFFSET, XV_HDMITX_AUD_CTRL_RUN_MASK, XV_HDMITX_AUD_CTRL_SET_OFFSET, XV_HDMITX_AUDFMT_3D, XV_HdmiTx_ReadReg, XV_HdmiTx_WriteReg.
XV_HdmiTx_AudioFormatType XV_HdmiTx_GetAudioFormat(XV_HdmiTx *InstancePtr)
This function gets the active audio format.
InstancePtr is a pointer to the XV_HdmiTx core instance. Active audio format of HDMI Tx None.
References XV_HDMITX_AUD_CTRL_AUDFMT_MASK, XV_HDMITX_AUD_CTRL_AUDFMT_SHIFT, XV_HDMITX_AUD_CTRL_OFFSET, XV_HdmiTx_ReadReg.
int XV_HdmiTx_SelfTest(XV_HdmiTx *InstancePtr)
This function reads ID of HDMI TX PIO peripheral.
InstancePtr is a pointer to the XV_HdmiTx core instance. XST_SUCCESS if PIO ID was matched.XST_FAILURE if PIO ID was mismatched. None.
References XV_HdmiTx_Config::BaseAddress, XV_HdmiTx::Config, XV_HDMITX_MASK_16, XV_HDMITX_PIO_ID, XV_HDMITX_PIO_ID_OFFSET, XV_HdmiTx_ReadReg, XV_HDMITX_SHIFT_16.
void XV_HdmiTx_IntrHandler(void *InstancePtr)
This function is the interrupt handler for the HDMI TX driver.
This handler reads the pending interrupt from PIO and DDC peripheral, determines the source of the interrupts, clears the interrupts and calls callbacks accordingly.The application is responsible for connecting this function to the interrupt system. Application beyond this driver is also responsible for providing callbacks to handle interrupts and installing the callbacks using XV_HdmiTx_SetCallback() during initialization phase. An example delivered with this driver demonstrates how this could be done. InstancePtr is a pointer to the XV_HdmiTx instance that just interrupted. None. None.
References XV_HdmiTx_Config::BaseAddress, XV_HdmiTx::Config, XV_HdmiTx::IsReady, XV_HDMITX_DDC_STA_IRQ_MASK, XV_HDMITX_DDC_STA_OFFSET, XV_HDMITX_PIO_STA_IRQ_MASK, XV_HDMITX_PIO_STA_OFFSET, XV_HdmiTx_ReadReg.
int XV_HdmiTx_SetCallback(XV_HdmiTx *InstancePtr, XV_HdmiTx_HandlerType HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function Type ----------------------- -------------------------------------------------- (XV_HDMITX_HANDLER_HPD) HpdCallback (XV_HDMITX_HANDLER_VS) VsCallback InstancePtr is a pointer to the HDMI TX core instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XV_HdmiTx::BrdgOverflowCallback, XV_HdmiTx::BrdgOverflowRef, XV_HdmiTx::BrdgUnderflowCallback, XV_HdmiTx::BrdgUnderflowRef, XV_HdmiTx::BrdgUnlockedCallback, XV_HdmiTx::BrdgUnlockedRef, XV_HdmiTx::ConnectCallback, XV_HdmiTx::ConnectRef, XV_HdmiTx::IsBrdgOverflowCallbackSet, XV_HdmiTx::IsBrdgUnderflowCallbackSet, XV_HdmiTx::IsBrdgUnlockedCallbackSet, XV_HdmiTx::IsConnectCallbackSet, XV_HdmiTx::IsStreamDownCallbackSet, XV_HdmiTx::IsStreamUpCallbackSet, XV_HdmiTx::IsToggleCallbackSet, XV_HdmiTx::IsVsCallbackSet, XV_HdmiTx::StreamDownCallback, XV_HdmiTx::StreamDownRef, XV_HdmiTx::StreamUpCallback, XV_HdmiTx::StreamUpRef, XV_HdmiTx::ToggleCallback, XV_HdmiTx::ToggleRef, XV_HdmiTx::VsCallback, XV_HdmiTx::VsRef.
int XV_HdmiTx_VSIF_GeneratePacket(XV_HdmiTx_VSIF *VSIFPtr, XHdmiC_Aux *AuxPtr)
This function generates a Vendor Specific InfoFrame (VSIF).
VSIFPtr is a pointer to the XV_HdmiTx_VSIF instance. AuxPtr is a pointer to the XV_HdmiTx_Tx_Aux instance. XST_SUCCESS if operation was successfulXST_FAILURE if an error was detected during generation
References XV_HdmiTx_3D_MetaData::Data, XV_HdmiTx_VSIF::Format, XV_HdmiTx_VSIF::HDMI_VIC, XV_HdmiTx_VSIF::IEEE_ID, XV_HdmiTx_VSIF::Info_3D, XV_HdmiTx_3D_MetaData::IsPresent, XV_HdmiTx_3D_MetaData::Length, XV_HdmiTx_3D_Info::MetaData, XV_HdmiTx_3D_MetaData::Type, XV_HdmiTx_VSIF::Version, XV_HDMITX_3D_META_LENGTH_MASK, XV_HDMITX_3D_META_LENGTH_SHIFT, XV_HDMITX_3D_META_PRESENT_SHIFT, XV_HDMITX_3D_META_TYPE_MASK, XV_HDMITX_3D_META_TYPE_SHIFT, XV_HDMITX_3D_SAMP_METHOD_MASK, XV_HDMITX_3D_SAMP_METHOD_SHIFT, XV_HDMITX_3D_SAMP_POS_MASK, XV_HDMITX_3D_SAMP_POS_SHIFT, XV_HDMITX_3D_STRUCT_MASK, XV_HDMITX_3D_STRUCT_SHIFT, XV_HDMITX_3D_STRUCT_SIDE_BY_SIDE_HALF, XV_HDMITX_VSIF_VF_3D, XV_HDMITX_VSIF_VF_EXTRES, XV_HDMITX_VSIF_VIDEO_FORMAT_MASK, XV_HDMITX_VSIF_VIDEO_FORMAT_SHIFT.
void XV_HdmiTx_VSIF_DisplayInfo(XV_HdmiTx_VSIF *VSIFPtr)
This function displays the contents of an XV_HdmiTx_VSIF instance.
VSIFPtr is a pointer to the XV_HdmiTx_VSIF instance. None.
References XV_HdmiTx_VSIF::Format, XV_HdmiTx_VSIF::HDMI_VIC, XV_HdmiTx_VSIF::Info_3D, XV_HdmiTx_3D_MetaData::IsPresent, XV_HdmiTx_3D_Info::MetaData, XV_HDMITX_3D_STRUCT_SIDE_BY_SIDE_HALF, XV_HdmiTx_VSIF_3DSampMethodToString, XV_HdmiTx_VSIF_3DSampPosToString, XV_HdmiTx_VSIF_3DStructToString, XV_HDMITX_VSIF_VF_3D, XV_HDMITX_VSIF_VF_EXTRES.
char* XV_HdmiTx_VSIF_3DStructToString(XV_HdmiTx_3D_Struct_Field Item)
This function returns a string representation of the enumerated type XV_HdmiTx_3D_Struct_Field.
Item specifies the value to convert. Pointer to the converted string.
References XV_HDMITX_3D_STRUCT_FIELD_ALTERNATIVE, XV_HDMITX_3D_STRUCT_FRAME_PACKING, XV_HDMITX_3D_STRUCT_L_DEPTH, XV_HDMITX_3D_STRUCT_L_DEPTH_GRAPH_GDEPTH, XV_HDMITX_3D_STRUCT_LINE_ALTERNATIVE, XV_HDMITX_3D_STRUCT_SIDE_BY_SIDE_FULL, XV_HDMITX_3D_STRUCT_SIDE_BY_SIDE_HALF, XV_HDMITX_3D_STRUCT_TOP_AND_BOTTOM.
Referenced by XV_HdmiTx_VSIF_DisplayInfo.
char* XV_HdmiTx_VSIF_3DSampMethodToString(XV_HdmiTx_3D_Sampling_Method Item)
This function returns a string representation of the enumerated type XV_HdmiTx_3D_Sampling_Method.
Item specifies the value to convert. Pointer to the converted string.
References XV_HDMITX_3D_SAMPLING_HORIZONTAL, XV_HDMITX_3D_SAMPLING_QUINCUNX.
Referenced by XV_HdmiTx_VSIF_DisplayInfo.
char* XV_HdmiTx_VSIF_3DSampPosToString(XV_HdmiTx_3D_Sampling_Position Item)
This function returns a string representation of the enumerated type XV_HdmiTx_3D_Sampling_Position.
Item specifies the value to convert. Pointer to the converted string.
References XV_HDMITX_3D_SAMPPOS_ELER, XV_HDMITX_3D_SAMPPOS_ELOR, XV_HDMITX_3D_SAMPPOS_OLER, XV_HDMITX_3D_SAMPPOS_OLOR.
Referenced by XV_HdmiTx_VSIF_DisplayInfo.