2ve_2vm/server/xplmi_plat.c
XPLMI_ROM_VERSION_1_0
ROM version 1.
XPLMI_SSSCFG_SHA0_MASK
SHA0 mask.
XPLMI_SSSCFG_SHA1_MASK
SHA1 mask.
XPLMI_SSSCFG_AES_MASK
AES mask.
XPLMI_SSS_SHA0_DMA0
SHA0 DMA0.
XPLMI_SSS_SHA0_DMA1
SHA0 DMA1.
XPLMI_SSS_SHA1_DMA0
SHA1 DMA0.
XPLMI_SSS_SHA1_DMA1
SHA1 DMA1.
XPLMI_SSS_AES_DMA0
AES DMA0.
XPLMI_SSS_AES_DMA1
AES DMA1.
XPLMI_LPDINITIALIZED_VER
LPD initialized version.
XPLMI_LPDINITIALIZED_LCVER
LPD initialized LC version.
XPLMI_UART_BASEADDR_VER
UART base address version.
XPLMI_UART_BASEADDR_LCVER
UART base address LC version.
XPLMI_TRACE_LOG_VERSION
Trace log version.
XPLMI_TRACE_LOG_LCVERSION
Trace log LC version.
XPLMI_BOARD_PARAMS_VERSION
Board parameters version.
Referenced by XPlmi_GetBoardParams.
XPLMI_BOARD_PARAMS_LCVERSION
Board parameters LC version.
Referenced by XPlmi_GetBoardParams.
XPLMI_XIOMODULE_VERSION
IOModule version.
XPLMI_XIOMODULE_LCVERSION
IOModule LC version.
XPLMI_PMC_VOLTAGE_MULTIPLIER
Voltage multiplier for Sysmon.
XPLMI_PPU_BUFFER_DS_VER
PPU buffers Data structure version.
Referenced by XPlmi_GetBufferList.
XPLMI_PPU_BUFFER_DS_LCVER
PPU buffers Data structure LC version.
Referenced by XPlmi_GetBufferList.
XPLMI_PMC_BUFFER_DS_VER
PMC buffers Data structure version.
Referenced by XPlmi_GetBufferList.
XPLMI_PMC_BUFFER_DS_LCVER
PMC buffers Data structure LC version.
Referenced by XPlmi_GetBufferList.
XPLMI_PPU_BUFFER_LIST_DS_VER
PPU buffer list Data structure version.
Referenced by XPlmi_GetBufferList.
XPLMI_PPU_BUFFER_LIST_DS_LCVER
PPU buffer list Data structure LC version.
Referenced by XPlmi_GetBufferList.
XPLMI_PMC_BUFFER_LIST_DS_VER
PMC buffer list Data structure version.
Referenced by XPlmi_GetBufferList.
XPLMI_PMC_BUFFER_LIST_DS_LCVER
PMC buffer list Data structure LC version.
Referenced by XPlmi_GetBufferList.
XInterruptHandler g_TopLevelInterruptTable[][]
u32 RomIroFreq
static u32 XPlmi_GetRawVoltage(float Voltage)
This function converts voltage to raw voltage value.
Voltage is the floating point voltage value 32-bit voltage value
static void XPlmi_DisableClearIOmodule(void)
This function will disable and clear the IOmodule interrupts.
None
static void XPlmi_HwIntrHandler(void *CallbackRef)
This function provides handler for HW interrupts.
CallbackRef is presently the interrupt number that is received
static u32 XPlmi_GetIoIntrMask(void)
This function returns the current enabled interrupt mask of IOmodule.
Current interrupt enable mask
static void XPlmi_SetIoIntrMask(u32 Value)
This function enables the IOModule interrupts with provided value.
Value to be written to the IER register of IOModule
static int XPlmi_UpdateFipsState(void)
This function monitors the KAT status and updates the FIPS state in RTCA.
XST_SUCCESS on successXST_FAILURE on failure
XInterruptHandler * XPlmi_GetTopLevelIntrTbl(void)
This function provides pointer to g_TopLevelInterruptTable.
Pointer to g_TopLevelInterruptTable structure Pointer to g_TopLevelInterruptTable structure.
Referenced by XPlmi_SetUpInterruptSystem.
u8 XPlmi_GetTopLevelIntrTblSize(void)
This function provides size of g_TopLevelInterruptTable.
Size g_TopLevelInterruptTable structure Size g_TopLevelInterruptTable structure.
Referenced by XPlmi_SetUpInterruptSystem.
XPlmi_BoardParams* XPlmi_GetBoardParams(void)
This function provides pointer to BoardParams.
Pointer to BoardParams Pointer to BoardParams.
References EXPORT_GENERIC_DS, XPLMI_BOARD_PARAMS_DS_ID, XPLMI_BOARD_PARAMS_LCVERSION, XPLMI_BOARD_PARAMS_VERSION.
XIOModule * XPlmi_GetIOModuleInst(void)
This function provides pointer to IOModule structure.
Pointer to XIOModule Pointer to XIOModule.
Referenced by XPlmi_GetTimerValue, XPlmi_PlmIntrClear, XPlmi_PlmIntrDisable, XPlmi_PlmIntrEnable, XPlmi_RegisterHandler, XPlmi_SetUpInterruptSystem, XPlmi_StartTimer.
u32 * XPlmi_GetLpdInitialized(void)
This function provides LpdInitialized variable pointer.
Pointer to LpdInitialized variable Pointer to LpdInitialized variable.
Referenced by XPlmi_ResetLpdInitialized, XPlmi_SetLpdInitialized, XPlmi_UnSetLpdInitialized.
u32 * XPlmi_GetUartBaseAddr(void)
This function provides LpdInitialized variable pointer.
This function provides a pointer to the UART base address variable.Pointer to LpdInitialized variable Pointer to LpdInitialized variable. Pointer to the static UartBaseAddr variable that stores the UART base address (initialized to XPLMI_INVALID_UART_BASE_ADDR)
Referenced by outbyte, XPlmi_ConfigUart, XPlmi_InitUart.
int XPlmi_PreInit(void)
This function performs plmi pre-initializaton.
Reset reason status. XST_SUCCESS always.
Referenced by XPlmi_Init.
void XPlmi_RtcaPlatInit(void)
This function performs initialization of platform specific RCTA registers.
Referenced by XPlmi_RunTimeConfigInit.
void XPlmi_PrintRomVersion(void)
This function prints ROM version using ROM digest value.
Referenced by XPlmi_PrintPlmBanner.
void XPlmi_SssMask(u32 DmaSrc)
This function masks the secure stream switch value.
DmaSrc - DMA0 or DMA1 DmaSrc DMA0 or DMA1.
XPlmi_CircularBuffer * XPlmi_GetTraceLogInst(void)
This function provides TraceLog instance.
Pointer to TraceLog variable Pointer to TraceLog variable.
Referenced by XPlmi_EventLogging.
int XPlmi_GenericHandler(XPlmi_ModuleOp Op)
This function is used for shutdown operation before In-place PLM Update.
Op is the operation information XST_SUCCESS on success and XST_FAILURE on failure
References EmDisableErrAction, GET_PMC_ERR_ACTION_OFFSET, GET_PMC_IRQ_MASK, XPlmi_EmDisableLpdSlcrErrors, XPlmi_GicIntrClearStatus, XPLMI_MODULE_NORMAL_STATE, XPLMI_MODULE_SHUTDOWN_ABORT, XPLMI_MODULE_SHUTDOWN_COMPLETE, XPLMI_MODULE_SHUTDOWN_COMPLETED_STATE, XPLMI_MODULE_SHUTDOWN_INITIATE, XPLMI_MODULE_SHUTDOWN_INITIATED_STATE, XPlmi_PlmIntrClear, XPlmi_PlmIntrDisable, XPLMI_RTCFG_SECURE_STATE_PLM_ADDR, XPLMI_SBI_GICP_INDEX, XPLMI_SBI_GICPX_INDEX.
void XPlmi_GetReadbackSrcDest(u32 SlrType, u64 *SrcAddr, u64 *DestAddrRead)
This function processes and provides SrcAddr and DestAddr for cfi readback.
SlrType is the type of Slr passed in readback cmd SrcAddr is the pointer to the SrcAddr variable DestAddrRead is the pointer to the DestAddrRead variable SlrType is the type of Slr passed in readback cmd. SrcAddr is the pointer to the SrcAddr variable. DestAddrRead is the pointer to the DestAddrRead variable.
References XPLMI_SLR1_CFU_FDRO_2_ADDR, XPLMI_SLR1_CFU_STREAM_2_ADDR, XPLMI_SLR2_CFU_FDRO_2_ADDR, XPLMI_SLR2_CFU_STREAM_2_ADDR, XPLMI_SLR3_CFU_FDRO_2_ADDR, XPLMI_SLR3_CFU_STREAM_2_ADDR.
void XPlmi_GicAddTask(u32 PlmIntrId)
This will add the GIC interrupt task handler to the TaskQueue.
PlmIntrId is the GIC interrupt ID of the task PlmIntrId is the GIC interrupt ID of the task.
References XPlmi_GetIpiIntrId, XPlmi_GicIntrAddTask.
Referenced by XPlmi_GicIntrHandler.
void XPlmi_IpiIntrHandler(void *CallbackRef)
This function is the IPI interrupt handler for the device.
This function is the Ipi interrupt handler for the device. CallbackRef is a dummy argument
References XPlmi_GetIpiIntrId, XPlmi_GetTaskInstance, XPlmi_PlmIntrClear, XPlmi_TaskTriggerNow.
int XPlmi_RegisterNEnableIpi(void)
This function registers and enables IPI interrupt.
XST_SUCCESS on success and XST_FAILURE on failure XST_SUCCESS on success and XST_FAILURE on failure XST_SUCCESS on success.XST_FAILURE on failure.
void XPlmi_EnableIomoduleIntr(void)
This function registers and enables IPI interrupt.
Referenced by XPlmi_SetUpInterruptSystem.
u32 XPlmi_GetRomIroFreq(void)
This function provides the Iro Frequency used in ROM.
RomIroFreq value
Referenced by XPlmi_PrintRomTime.
static u32 XPlmi_IsMporHpPart(void)
This function provides check if its Mp or hp part.
- returns TRUE for voltage > 0.775v FALSE otherwise
int XPlmi_SetPmcIroFreq(void)
It sets the PMC IRO frequency.
This functions sets the PMC IRO frequency. XST_SUCCESS on success and error code failure - XST_SUCCESS on success XST_FAILURE on failure XST_SUCCESS on success.Error code failure.
Referenced by XPlmi_StartTimer.
XPlmi_WaitForDmaDone_t XPlmi_GetPlmiWaitForDone(u64 DestAddr)
This function is used to check and wait for DMA done when sending data to SSIT Slave SLRs.
This function is used to check and wait for DMA done. DestAddr holds the address of the destination buffer XST_SUCCESS on success and error code on failure DestAddr is the address of destination XST_SUCCESS on success and error code on failure DestAddr holds the address of the destination buffer. XST_SUCCESS on success.Error code on failure.
Referenced by XPlmi_DmaXfr.
u32 XPlmi_GetGicIntrId(u32 GicPVal, u32 GicPxVal)
This function provides Gic interrupt id.
GicPVal indicates GICP source GicPxVal indicates GICPx source Gic Interrupt Id GicPVal indicates GICP source GicPxVal indicates GICPx source Readback length GicPVal indicates GICP source. GicPxVal indicates GICPx source. Gic Interrupt Id.
Referenced by XPlmi_GicRegisterHandler.
u32 XPlmi_GetIpiIntrId(u32 BufferIndex)
This function provides IPI interrupt id.
BufferIndex is the Ipi target buffer index IPI interrupt id BufferIndex is the Ipi target buffer index. IPI interrupt id.
Referenced by XPlmi_GicAddTask, XPlmi_IpiIntrHandler.
int XPlmi_RomISR(XPlmi_RomIntr RomServiceReq)
This function raises an interrupt request to ROM and waits for completion.
Before calling this API all pre-requsites for ROM service shall be completed. RomServiceReq variable of enum type XPlmi_RomIntr XST_SUCCESS if success.XPLMI_ERR_INVALID_ROM_INT_REQ on invalid interrupt request for ROM.
References XPLMI_DME_CHL_SIGN_GEN, XPLMI_INVALID_INT, XPLMI_PLM_UPDT_REQ, XPLMI_ROM_SERVICE_TIMEOUT.
u32 XPlmi_IsFipsModeEn(void)
This function return FIPS mode.
TRUE If FIPS mode is enabled FALSE If FIPS mode is disabled
Referenced by XPlmi_CheckAndUpdateFipsState.
u32 XPlmi_GetRomKatStatus(void)
This function returns ROM KAT status.
ROM KAT status
References XPLMI_ROM_KAT_MASK.
void XPlmi_GetBootKatStatus(volatile u32 *PlmKatStatus)
This function returns KAT status from RCTA area.
This function sets KAT status from RTC area. PlmKatStatus is the pointer to the variable which holds kat status PlmKatStatus is the pointer to the variable which holds kat status.
void XPlmi_ClearSSSCfgErr(void)
This function clears SSS Cfg error set during ROM PCR Extension.
References XPlmi_IsPlmUpdateDone.
XPlmi_FipsKatMask * XPlmi_GetFipsKatMaskInstance(void)
This function returns XPlmi_FipsKatMask instance.
pointer to the XPlmi_FipsKatMask instance
Referenced by XPlmi_SetFipsKatMask.
int XPlmi_CheckAndUpdateFipsState(void)
This function checks and updates the FIPS state in RTCA.
XST_SUCCESS on successXST_FAILURE on failure
References XPlmi_IsFipsModeEn.
Referenced by XPlmi_SetFipsKatMask, XPlmi_UpdateKatStatus.
void XPlmi_UpdateCryptoStatus(u32 Mask, u32 Val)
This function sets or clears crypto bit in RTCA based on mask.
Mask Mask to set or clear crypto status Val Value to set or clear crypto status
References XPlmi_UtilRMW.
u32 XPlmi_GetCryptoStatus(u32 Mask)
This function returns crypto status flag.
Mask Mask to read crypto status Crypto status value
u8 XPlmi_IsKatRan(u32 PlmKatMask)
This function will return KAT status of given mask.
PlmKatMask contains the KAT mask TRUE If KAT ran FALSE If KAT didn't ran PlmKatMask contains the KAT mask TRUE If KAT ran.FALSE If KAT didn't ran.
References XPlmi_IsCryptoKatEn.
XPlmi_BufferList* XPlmi_GetBufferList(u32 BufferListType)
This function defines BufferList and returns the address of the same.
BufferListType is the proc list type if it is stored in PMC or PSM RAM BufferList is the address of BufferList structure BufferListType is the proc list type if it is stored in PMC or PPU RAM BufferList is the address of BufferList structure BufferListType is the proc list type if it is stored in PMC or PSM RAM. BufferList is the address of BufferList structure.
References EXPORT_GENERIC_DS, XPLMI_MAX_PMC_BUFFERS, XPLMI_PMC_BUFFER_DS_ID, XPLMI_PMC_BUFFER_DS_LCVER, XPLMI_PMC_BUFFER_DS_VER, XPLMI_PMC_BUFFER_LIST_DS_ID, XPLMI_PMC_BUFFER_LIST_DS_LCVER, XPLMI_PMC_BUFFER_LIST_DS_VER, XPLMI_PPU_BUFFER_DS_ID, XPLMI_PPU_BUFFER_DS_LCVER, XPLMI_PPU_BUFFER_DS_VER, XPLMI_PPU_BUFFER_LIST_DS_ID, XPLMI_PPU_BUFFER_LIST_DS_LCVER, XPLMI_PPU_BUFFER_LIST_DS_VER.
Referenced by XPlmi_ExecuteProc, XPlmi_PsmSequence, XPlmi_SetBufferList.