2ve_2vm/server/xplmi_err.c
XPLMI_ERROR_TABLE_DS_VER
Error table data structure version.
XPLMI_ERROR_TABLE_DS_LCVER
Error table data structure LC version.
XPLMI_NUM_ERROUTS_VERSION
ERROUTS version.
XPLMI_NUM_ERROUTS_LCVERSION
ERROUTS LC version.
PCIE0_LINK_DOWN_PROC_ID
PCIE0 link down proc Id.
PCIE1_LINK_DOWN_PROC_ID
PCIE1 link down proc Id.
XPlmi_Error_t ErrorTable[XPLMI_ERROR_SW_ERR_MAX][XPLMI_ERROR_SW_ERR_MAX]
static void XPlmi_HandleLPDSlcrError(u32 ErrorNodeId, u32 RegMask)
This function handles the error in LPD SLCR routed to PLM.
ErrorNodeId is the node ID for the error event RegMask is the register mask of the error received None
static void XPlmi_ErrLPDSlcrIntrHandler(u32 ErrorNodeId, u32 RegMask)
This function is the interrupt handler for Errors in LPDSLCR.
ErrorNodeId is the node ID for the error event RegMask is the register mask of the error received None
static void XPlmi_PcieErrHandler(u32 ErrorNodeId, u32 RegMask)
This function handles the PCIE errors.
ErrorNodeId is the node ID for the error event RegMask is the register mask of the error received
void XPlmi_HandleLinkDownError(u32 Cpm5PcieIrStatusReg, u32 Cpm5DmaCsrIntDecReg, u32 ProcId)
This function handles the CPM_NCR PCIE link down error.
This function handles the PCIE link down error. Cpm5PcieIrStatusReg is the PCIE0/1 IR status register address Cpm5DmaCsrIntDecReg is the DMA0/1 CSR INT DEC register address ProcId is the ProcId for PCIE0/1 link down error DeviceIrStatusReg is the PCIE0/1 Device IR status register address GenralStsReg is the PCIE0/1 General status register address ProcId is the ProcId for PCIE0/1 link down error Cpm5PcieIrStatusReg is the PCIE0/1 IR status register address. Cpm5DmaCsrIntDecReg is the DMA0/1 CSR INT DEC register address. ProcId is the ProcId for PCIE0/1 link down error.
References XPlmi_ErrMgr, XPlmi_ExecuteProc.
static void XPlmi_XppuErrHandler(u32 BaseAddr, const char *ProtUnitStr)
This function handles the XPPU errors.
BaseAddr is the base address of the XPPU ProtUnitStr is string prefix to be used while printing event info None
static void XPlmi_XmpuErrHandler(u32 BaseAddr, const char *ProtUnitStr)
This function handles the XMPU errors.
BaseAddr is the base address of the XMPU ProtUnitStr is string prefix to be used while printing event info None
XPlmi_Error_t * XPlmi_GetErrorTable(void)
This function provides error table pointer.
Pointer to Error Table Pointer to Error Table
Referenced by XPlmi_EmClearError, XPlmi_EmConfig, XPlmi_EmGetAction, XPlmi_EmInit, XPlmi_EmSetAction, XPlmi_ErrorTaskHandler, XPlmi_ErrPSMIntrHandler, XPlmi_HandleSwError, XPlmi_LpdSlcrEmInit, XPlmi_PsEmInit, XPlmi_TriggerFwNcrError, XPlmi_UpdateErrorSubsystemId, XPlmi_Versal2Ve2VmEAMHandler.
void XPlmi_ReconfigErrActions(void)
This function reconfigures error actions after the update.
None
References XPlmi_EmConfig.
Referenced by XPlmi_EmInit.
u8 XPlmi_GetEventIndex(XPlmi_EventType ErrorNodeType)
This function provides event index.
ErrorNodeType is the Node Type of the EAM register Event Index ErrorNodeType is the Node Type of the EAM register. Event Index.
Referenced by XPlmi_EmClearError, XPlmi_EmDisable, XPlmi_Versal2Ve2VmSetAction.
void XPlmi_ErrPrintToLog(u32 ErrorNodeId, u32 RegMask)
This function is the interrupt handler for Error action "Print to Log".
This function prints detailed information if the error is due to XMPU/XPPU protection units. ErrorNodeId is the node ID for the error event RegMask is the register mask of the error received This function prints detailed information if the error is due to XMPU/XPPU protection units. ErrorNodeId is the node ID for the error event RegMask is the register mask of the error received None This function prints detailed information if the error is due to XMPU/XPPU protection units. ErrorNodeId is the node ID for the error event. RegMask is the register mask of the error received.
References XPlmi_GetErrorId.
Referenced by XPlmi_EmConfig.
void XPlmi_DumpErrNGicStatus(void)
This function dumps EAM Error status registers and Gic Status registers.
None
int XPlmi_RestrictErrActions(XPlmi_EventType NodeType, u32 RegMask, u32 ErrorAction)
This function restricts error actions.
NodeType of Error RegMask of Error ErrorAction of the the Error XST_SUCCESS on success and error code on failure NodeType of Error RegMask of Error ErrorAction of the the Error XST_SUCCESS if success.XPLMI_INVALID_ERROR_ACTION on invalid error action. NodeType of Error. RegMask of Error. ErrorAction of the the Error. XST_SUCCESS on success.Error code on failure.
Referenced by XPlmi_Versal2Ve2VmSetAction.
u32 * XPlmi_GetNumErrOuts(void)
This function provides pointer to NumErrOuts.
Pointer to NumErrOuts Pointer to NumErrOuts.
Referenced by XPlmi_UpdateNumErrOutsCount.
int EmEnableLpdSlcrErrAction(u32 ErrMaskRegAddr, u32 RegMask)
This function enables the error action for the given error mask.
ErrMaskRegAddr is the error action mask register address RegMask is the register mask of the error to be disabled XST_SUCCESS on success.XPLMI_ERROR_ACTION_NOT_ENABLED if error action is not enabled.
int XPlmi_EmDisableLpdSlcrErrors(u32 RegMaskAddr, u32 RegMask)
This function disables the LPD SCLR error actions for the given mask.
RegMaskAddr is the offset for the PMC ERR, POR ,IRQ mask,SRST mask RegMask is the register mask of the error to be disabled XST_SUCCESS on success.XPLMI_ERROR_ACTION_NOT_DISABLED if error action is not disabled.
Referenced by XPlmi_EmDisable, XPlmi_GenericHandler, XPlmi_LpdSlcrEmInit.
int XPlmi_Versal2Ve2VmEAMHandler(void *Data)
This function is the interrupt handler for the EAM errors.
Data is presently passed as NULL XST_SUCCESS always.
References GET_PMC_ERR_ACTION_OFFSET, GET_PMC_IRQ_MASK, XPlmi_EmClearError, XPlmi_EmDisable, XPlmi_GetErrorTable, XPlmi_PlmIntrClear, XPlmi_PlmIntrEnable.
Referenced by XPlmi_ErrorTaskHandler.
int XPlmi_LpdSlcrEmInit(void)
This function initializes the error actions in LPD Slcr Disables all the LPD SLCR error actions and registers default action.
XST_SUCCESS always.
References XPlmi_EmDisableLpdSlcrErrors, XPlmi_EmSetAction, XPlmi_GetErrorTable.
Referenced by XPlmi_LpdInit.
int XPlmi_Versal2Ve2VmSetAction(XPlmi_Cmd *Cmd)
This function sets the error action as prescribed by the command.
Command payload parameters are * Error Node ID * Error Action 0 - Invalid 1 - POR 2 - SRST 3 - Custom(Not supported) 4 - ErrOut 5 - Subsystem Shutdown 6 - Subsystem Restart 7 - Print to log 8 - SLD 9 - SLD with TRI 10 - None * Error ID Mask Cmd is pointer to the command structure XST_SUCCESS on success.XPLMI_INVALID_NODE_ID on invalid node ID.XPLMI_INVALID_ERROR_ACTION on invalid error action.XPLMI_CANNOT_CHANGE_ACTION if failed to change error action.XPLMI_LPD_UNINITIALIZED if LPD failed to initialize.
References XPlmi_EmSetAction, XPlmi_GetEmSubsystemId, XPlmi_GetEventIndex, XPlmi_RestrictErrActions.