2ve_2vm/server/xplmi_err.h
GET_PMC_ERR_ACTION_OFFSET
PMC error action offset.
GET_PMC_ERR_ACTION_ADDR
PMC error action address.
GET_PMC_ERR_OUT_MASK
PMC error out mask.
GET_PMC_POR_MASK
PMC POR mask.
GET_PMC_IRQ_MASK
PMC IRQ mask.
GET_PMC_SRST_MASK
PMC SRST mask.
static void XPlmi_SysmonClkSetIro(void)
This function sets the sysmon clock to IRO for ES1 silicon.
None
static void XPlmi_ClearSsitErrors(u32 *PmcErrStatus, u32 Index)
This function clears Ssit errors for ES1 silicon.
PmcErrStatus is the pointer to the error status array Index is the PMC Error register Index None
XPlmi_Error_t* XPlmi_GetErrorTable(void)
This function provides error table pointer.
Pointer to Error Table Pointer to Error Table
u8 XPlmi_GetEventIndex(XPlmi_EventType ErrorNodeType)
This function provides event index.
ErrorNodeType is the Node Type of the EAM register Event Index ErrorNodeType is the Node Type of the EAM register. Event Index.
int XPlmi_RestrictErrActions(XPlmi_EventType NodeType, u32 RegMask, u32 ErrorAction)
This function restricts error actions.
NodeType of Error RegMask of Error ErrorAction of the the Error XST_SUCCESS on success and error code on failure NodeType of Error RegMask of Error ErrorAction of the the Error XST_SUCCESS if success.XPLMI_INVALID_ERROR_ACTION on invalid error action. NodeType of Error. RegMask of Error. ErrorAction of the the Error. XST_SUCCESS on success.Error code on failure.
void XPlmi_DumpErrNGicStatus(void)
This function dumps EAM Error status registers and Gic Status registers.
None
void XPlmi_ReconfigErrActions(void)
This function reconfigures error actions after the update.
None
u32* XPlmi_GetNumErrOuts(void)
This function provides pointer to NumErrOuts.
Pointer to NumErrOuts Pointer to NumErrOuts.
u32* XPlmi_GetPsmCrState(void)
This function provides IsPsmChanged variable.
Pointer to IsPsmCrChanged Pointer to IsPsmCrChanged.
void XPlmi_HandleLinkUpEvent(u32 Cpm5NPcieCdxIrStatusReg, u32 Cpm5NCdxPcieBReg, u32 ProcId)
This function handles the CPM_NCR PCIE link up event.
Cpm5NPcieCdxIrStatusReg is the PCIE0/1/2/3 IR status register address Cpm5NCdxPcieBReg is the Pcie Bridge Misc Status register address ProcId is the ProcId for PCIE0/1/2/3 link up event
void XPlmi_ErrPrintToLog(u32 ErrorNodeId, u32 RegMask)
This function is the interrupt handler for Error action "Print to Log".
This function prints detailed information if the error is due to XMPU/XPPU protection units. ErrorNodeId is the node ID for the error event RegMask is the register mask of the error received This function prints detailed information if the error is due to XMPU/XPPU protection units. ErrorNodeId is the node ID for the error event RegMask is the register mask of the error received None This function prints detailed information if the error is due to XMPU/XPPU protection units. ErrorNodeId is the node ID for the error event. RegMask is the register mask of the error received.
int XPlmi_EmDisableLpdSlcrErrors(u32 RegMaskAddr, u32 RegMask)
This function disables the LPD SCLR error actions for the given mask.
RegMaskAddr is the offset for the PMC ERR, POR ,IRQ mask,SRST mask RegMask is the register mask of the error to be disabled XST_SUCCESS on success.XPLMI_ERROR_ACTION_NOT_DISABLED if error action is not disabled.
Referenced by XPlmi_LpdSlcrEmInit, XPlmi_EmDisable, XPlmi_GenericHandler.
int EmEnableLpdSlcrErrAction(u32 ErrMaskRegAddr, u32 RegMask)
This function enables the error action for the given error mask.
ErrMaskRegAddr is the error action mask register address RegMask is the register mask of the error to be disabled XST_SUCCESS on success.XPLMI_ERROR_ACTION_NOT_ENABLED if error action is not enabled.
int XPlmi_LpdSlcrEmInit(void)
This function initializes the error actions in LPD Slcr Disables all the LPD SLCR error actions and registers default action.
XST_SUCCESS always.
References XPlmi_GetErrorTable, XPlmi_EmDisableLpdSlcrErrors, XPlmi_EmSetAction.
Referenced by XPlmi_LpdInit.
int XPlmi_Versal2Ve2VmSetAction(XPlmi_Cmd *Cmd)
This function sets the error action as prescribed by the command.
Command payload parameters are * Error Node ID * Error Action 0 - Invalid 1 - POR 2 - SRST 3 - Custom(Not supported) 4 - ErrOut 5 - Subsystem Shutdown 6 - Subsystem Restart 7 - Print to log 8 - SLD 9 - SLD with TRI 10 - None * Error ID Mask Cmd is pointer to the command structure XST_SUCCESS on success.XPLMI_INVALID_NODE_ID on invalid node ID.XPLMI_INVALID_ERROR_ACTION on invalid error action.XPLMI_CANNOT_CHANGE_ACTION if failed to change error action.XPLMI_LPD_UNINITIALIZED if LPD failed to initialize.
References XPlmi_GetEmSubsystemId, XPlmi_GetEventIndex, XPlmi_RestrictErrActions, XPlmi_EmSetAction.