2vp_p/server/xplmi_err.h
GET_PMC_ERR_ACTION_OFFSET
PMC error action offset.
GET_PMC_ERR_ACTION_ADDR
PMC error action address.
GET_PMC_ERR_OUT_MASK
PMC error out mask.
GET_PMC_POR_MASK
PMC POR mask.
GET_PMC_IRQ_MASK
PMC IRQ mask.
GET_PMC_SRST_MASK
PMC SRST mask.
static void XPlmi_ReconfigErrActions(void)
This function reconfigures error actions after the update.
None.
XPlmi_Error_t* XPlmi_GetErrorTable(void)
This function provides error table pointer.
Pointer to Error Table Pointer to Error Table
void XPlmi_SysmonClkSetIro(void)
This function sets the sysmon clock to IRO for ES1 silicon.
References XPlmi_UtilRMW, XPLMI_SYSMON_CLK_SRC_IRO_VAL.
Referenced by XPlmi_PORHandler, XPlmi_SoftResetHandler, XPlmi_TriggerFwNcrError.
void XPlmi_HandleLinkDownError(u32 Cpm5PcieIrStatusReg, u32 Cpm5DmaCsrIntDecReg, u32 ProcId)
This function handles the CPM_NCR PCIE link down error.
This function handles the PCIE link down error. Cpm5PcieIrStatusReg is the PCIE0/1 IR status register address Cpm5DmaCsrIntDecReg is the DMA0/1 CSR INT DEC register address ProcId is the ProcId for PCIE0/1 link down error DeviceIrStatusReg is the PCIE0/1 Device IR status register address GenralStsReg is the PCIE0/1 General status register address ProcId is the ProcId for PCIE0/1 link down error Cpm5PcieIrStatusReg is the PCIE0/1 IR status register address. Cpm5DmaCsrIntDecReg is the DMA0/1 CSR INT DEC register address. ProcId is the ProcId for PCIE0/1 link down error.
References XPlmi_ExecuteProc, XPlmi_ErrMgr.
void XPlmi_DumpErrNGicStatus(void)
This function dumps EAM Error status registers and Gic Status registers.
None
u8 XPlmi_GetEventIndex(XPlmi_EventType ErrorNodeType)
This function provides event index.
ErrorNodeType is the Node Type of the EAM register Event Index ErrorNodeType is the Node Type of the EAM register. Event Index.
void XPlmi_ClearSsitErrors(u32 *PmcErrStatus, u32 Index)
This function clears Ssit errors for ES1 silicon.
PmcErrStatus is the pointer to the error status array Index is the PMC Error register Index PmcErrStatus is the pointer to the error status array. Index is the PMC Error register Index.
References XPLMI_PMC_ERR_SSIT_MASK.
Referenced by XPlmi_EmInit.
u32* XPlmi_GetNumErrOuts(void)
This function provides pointer to NumErrOuts.
Pointer to NumErrOuts Pointer to NumErrOuts.
int XPlmi_RestrictErrActions(XPlmi_EventType NodeType, u32 RegMask, u32 ErrorAction)
This function restricts error actions.
NodeType of Error RegMask of Error ErrorAction of the the Error XST_SUCCESS on success and error code on failure NodeType of Error RegMask of Error ErrorAction of the the Error XST_SUCCESS if success.XPLMI_INVALID_ERROR_ACTION on invalid error action. NodeType of Error. RegMask of Error. ErrorAction of the the Error. XST_SUCCESS on success.Error code on failure.
u32* XPlmi_GetPsmCrState(void)
This function provides IsPsmChanged variable.
Pointer to IsPsmCrChanged Pointer to IsPsmCrChanged.
void XPlmi_ErrPrintToLog(u32 ErrorNodeId, u32 RegMask)
This function is the interrupt handler for Error action "Print to Log".
This function prints detailed information if the error is due to XMPU/XPPU protection units. ErrorNodeId is the node ID for the error event RegMask is the register mask of the error received This function prints detailed information if the error is due to XMPU/XPPU protection units. ErrorNodeId is the node ID for the error event RegMask is the register mask of the error received None This function prints detailed information if the error is due to XMPU/XPPU protection units. ErrorNodeId is the node ID for the error event. RegMask is the register mask of the error received.