client/xplmi_generic.c
int XPlmi_SendRequest(XPlmi_ClientInstance *InstancePtr, u32 *PayloadBuf, u32 PayloadLen, u32 *ResponseBuf, u32 ResponseLen)
This function sends request to PLM through either SMC or IPI mailbox based on the execution environment.
For EL1 non-secure AArch64 applications, SMC is used. For other environments, IPI mailbox is used. InstancePtr Pointer to the client instance (used for mailbox, can be NULL for SMC) PayloadBuf Pointer to payload buffer containing command and arguments PayloadLen Length of payload buffer (number of u32 elements) ResponseBuf Pointer to store response values (can be NULL if response not needed) ResponseLen Length of response buffer (number of u32 elements) XST_SUCCESS on success.XST_FAILURE on failure.XST_INVALID_PARAM If input parameters are invalid This is a generic API that internally handles SMC or Mailbox communication based on the build configuration.
References XPlmi_ClientInstance::MailboxPtr, XPlmi_ClientInstance::Response, RESPONSE_ARG_CNT, XPlmi_ProcessMailbox.
Referenced by XPlmi_ConfigSecureComm, XPlmi_EventLogging, XPlmi_GetBoard, XPlmi_GetDeviceID, XPlmi_GetSecureCommStatus, XPlmi_SetDDRMCMainRegSts, XPlmi_TamperTrigger.