xilplmi_server_apis
static int XPlmi_CmdAsuFeatures(XPlmi_Cmd *Cmd)
Static function pointer which holds address of XOcp_GetOcpEventMask.
Contains the module ID and PLM error commands array This function is reserved to get the supported features for this module. Cmd is pointer to the command structure XST_SUCCESS always.
static int XPlmi_CmdAsuKeyTransfer(XPlmi_Cmd *Cmd)
This function transfers keys as prescribed by the command.
Cmd is pointer to the command structure XST_SUCCESS on success.
XPlmi_IsAddrRangeValid_t XPlmi_IsAddrRangeValid
< Global address range validation handler
Referenced by XPlmi_Init.
XPmcDma PmcDma0
Instance of the Pmc_Dma Device.
XPmcDma PmcDma1
Instance of the Pmc_Dma Device.
XPmcDma_Configure DmaCtrl
s32(* PmSystemShutdown)(u32 SubsystemId, const u32 Type, const u32 SubType, const u32 CmdType))(u32 SubsystemId, const u32 Type, const u32 SubType, const u32 CmdType)
u32 EmSubsystemId
EmSubsystemId variable stores the error management subsystem ID.
XPlmi_Module* Modules[XPLMI_ALL_MODULES_MAX][XPLMI_ALL_MODULES_MAX]
u32 PmcIroFreq
PmcIroFreq variable stores the frequency of the PMC IRO in Hz.
XPlmi_Scheduler_t Sched
u32 SldState
SldState variable maintains the current secure lockdown state.
u32 TamperResponse
TamperResponse variable stores the tamper response configuration.
XPlmi_TaskNode* TamperTask
TamperTask is the task node pointer for tamper response processing.
struct metal_list TaskQueue[XPLMI_TASK_PRIORITIES][XPLMI_TASK_PRIORITIES]
XPlmi_Error_t ErrorTable[XPLMI_ERROR_SW_ERR_MAX][XPLMI_ERROR_SW_ERR_MAX]
XInterruptHandler g_TopLevelInterruptTable[][]
u8 XRamAvailable
int(* AsuGeneratePufKEK)(u8 *PufRegenStatusFlag))(u8 *PufRegenStatusFlag)
int(* AsuInitiateKeyXfer)(void))(void)
Static function pointer which holds address of Xplmi_PufOnDemandRegeneration.
int(* AsuGetAsuCdiSeed)(u32 CdiAddr))(u32 CdiAddr)
Static function pointer which holds address of XSecure_InitiateASUKeyTransfer.
int(* AsuGetSubsysDigest)(u32 SubsystemId, u32 SubsysHashAddrPtr))(u32 SubsystemId, u32 SubsysHashAddrPtr)
Static function pointer which holds address of XOcp_GetAsuCdiSeed.
void(* AsuGetOcpEventMask)(u32 *EventMask))(u32 *EventMask)
Static function pointer which holds address of XOcp_GetSubsysDigest.
XPlmi_IsPdiAddrLookup_t XPlmi_IsPdiAddrLookup
Function pointer for PDI address lookup.
XPlmi_CheckAsuPresenceInPdi_t XPlmi_IsAsuPresenceInPdi
Function pointer for ASU presence check.
XPlmi_LoadAsuImage_t XLoader_LoadAsu
Function pointer for ASU image loading.
u32 UpdateAsuPdiAddr
Update PDI address.
XPlmi_Error_t ErrorTable[XPLMI_ERROR_SW_ERR_MAX][XPLMI_ERROR_SW_ERR_MAX]
XInterruptHandler g_TopLevelInterruptTable[][]
u32 RomIroFreq
XPlmi_Error_t ErrorTable[XPLMI_ERROR_SW_ERR_MAX][XPLMI_ERROR_SW_ERR_MAX]
XInterruptHandler g_TopLevelInterruptTable[][]
u8 XRamAvailable
XPlmi_Error_t ErrorTable[XPLMI_ERROR_SW_ERR_MAX][XPLMI_ERROR_SW_ERR_MAX]
XInterruptHandler g_TopLevelInterruptTable[][]
u8 XRamAvailable
XPlmi_Error_t ErrorTable[XPLMI_ERROR_SW_ERR_MAX][XPLMI_ERROR_SW_ERR_MAX]
XInterruptHandler g_TopLevelInterruptTable[][]
u32 RomIroFreq
XPlmi_BufferList AddressBufferList
XPlmi_CompatibilityCheck_t XPlmi_CompatibilityCheck
XPlmi_IsPdiAddrLookup_t XPlmi_IsPdiAddrLookup
XPlmi_CheckPsmPresenceInOD_t XPlmi_CheckPsmPresenceInOD
XPlmi_DsEntry __data_struct_start[][]
XPlmi_DsEntry __data_struct_end[][]
u32 __update_mgr_b_start[][]
u8 __update_mgr_a_fn_start[][]
u8 __update_mgr_a_fn_end[][]
u8 PlmUpdateState
u8 PlmUpdateStateTmp
u32 UpdatePdiAddr
u32 DbStartAddr
u32 DbEndAddr
Db Start Address.
XPlmi_Wdt WdtInstance
WdtInstance is an instance of external WDT used for GPIO toggling.
static void XPlmi_PrintEarlyLog(void)
This function prints early log.
int XPlmi_Init(XPlmi_IsAddrRangeValid_t IsAddrRangeValidHandler)
This function will initialize the PLMI module.
IsAddrRangeValidHandler - Function pointer to address range validation handler that validates if a given address range is accessible by the specified subsystem. XST_SUCCESS on success.XPLMI_ERR_PRE_INIT if pre initialization fails.XPLMI_ERR_REGISTER_VERIFY_ADDR_RANGE_HANDLER if handler is NULL.
References XPLMI_ERR_PRE_INIT, XPlmi_IsAddrRangeValid, XPlmi_PreInit, XPlmi_SetPlmLiveStatus, XPlmi_SetUpInterruptSystem.
int XPlmi_RunTimeConfigInit(void)
This function initializes the Runtime Configuration Area with default values.
XST_SUCCESS on success and error code on failure
References XPlmi_IsPlmUpdateDone, XPlmi_IsPlmUpdateDoneTmp, XPlmi_MemSet, XPLMI_PLM_MAJOR_VERSION, XPLMI_PLM_MAJOR_VERSION_SHIFT, XPLMI_PLM_MINOR_VERSION, XPLMI_PLM_MINOR_VERSION_SHIFT, XPLMI_PLM_RC_VERSION, XPLMI_PLM_RC_VERSION_SHIFT, XPLMI_PLM_USER_DEFINED_VERSION, XPlmi_RtcaPlatInit, XPLMI_RTCFG_BASEADDR, XPLMI_RTCFG_DDRMC_CALIB_CHECK_SKIP_ADDR, XPLMI_RTCFG_IMG_STORE_ADDRESS_HIGH, XPLMI_RTCFG_IMG_STORE_ADDRESS_LOW, XPLMI_RTCFG_IMG_STORE_SIZE, XPLMI_RTCFG_LOG_UART_OFFSET.
void XPlmi_LpdInit(void)
This function calls all the PS LPD init functions of all the different modules.
As a part of init functions, modules can register the command handlers, interrupt handlers with the interface layer.
References LPD_INITIALIZED, XPlmi_ErrMgr, XPlmi_InitUart, XPlmi_IsPlmUpdateDone, XPlmi_LogPlmErr, XPlmi_LpdSlcrEmInit, XPlmi_PsEmInit, XPlmi_SetLpdInitialized, XPlmi_UtilRMW, XPLMI_WARNING_MAJOR_MASK.
void XPlmi_PrintPlmBanner(void)
This function prints PLM banner.
References SDK_RELEASE_QUARTER, SDK_RELEASE_YEAR, XPlmi_IsPlmUpdateDone, XPLMI_PLM_BANNER, XPLMI_PMC_VERSION_MASK, XPLMI_PMC_VERSION_SHIFT, XPlmi_PrintRomVersion.
void XPlmi_ResetLpdInitialized(void)
This function resets LpdInitialized variable to 0.
References LPD_WDT_INITIALIZED, XPlmi_DisableWdt, XPlmi_GetLpdInitialized.
void XPlmi_SetLpdInitialized(u32 Flag)
This function sets LpdInitialized variable with given flag.
Flag to set the UART or LPD WDT initialization state.
References XPlmi_GetLpdInitialized.
Referenced by XPlmi_ConfigUart, XPlmi_EnableWdt, XPlmi_InitUart, XPlmi_LpdInit.
void XPlmi_UnSetLpdInitialized(u32 Flag)
This function clears LpdInitialized variable with given flag.
Flag to unset the UART or LPD WDT initialization state.
References XPlmi_GetLpdInitialized.
Referenced by XPlmi_ConfigUart.
void XPlmi_UpdateKatStatus(u32 PlmKatStatus)
This function sets XPLMI_RTCFG_PLM_KAT_ADDR with PlmKatStatus.
PlmKatStatus contains the KAT status updated by PLM
References XPlmi_CheckAndUpdateFipsState, XPLMI_KAT_MASK, XPlmi_UtilRMW.
Referenced by XPlmi_ClearKatMask, XPlmi_SetKatMask.
u32 XPlmi_GetKatStatus(void)
This function is called to get KAT status.
References XPLMI_KAT_MASK.
Referenced by XPlmi_ClearKatMask, XPlmi_SetKatMask.
void XPlmi_SetKatMask(u32 PlmKatMask)
This function sets XPLMI_RTCFG_PLM_KAT_ADDR with PlmKatMask.
PlmKatMask contains the kat mask that needs to be set
References XPlmi_GetKatStatus, XPlmi_UpdateKatStatus.
void XPlmi_ClearKatMask(u32 PlmKatMask)
This function clears XPLMI_RTCFG_PLM_KAT_ADDR with PlmKatMask.
PlmKatMask contains the kat mask that needs to be cleared
References XPlmi_GetKatStatus, XPlmi_UpdateKatStatus.
u32 XPlmi_IsCryptoKatEn(void)
This function will return the crypto kat enable status from efuse cache.
TRUE If crypto kat bit is set FALSE If crypto kat bit is not set
Referenced by XPlmi_IsKatRan.
static u32 XPlmi_CmdSize(const u32 *Buf, u32 Len)
This function will calculate the size of the command.
Bits 16 to 23 denote the size of the command. If the value is 255, then the word following CmdId would denote the size of the command. Buf is pointer to buffer Len is length of the command that is available in memory to parse Size of the command
static void XPlmi_SetupCmd(XPlmi_Cmd *Cmd, u32 *Buf, u32 BufLen)
This function will setup the command structure.
Cmd is pointer to the command structure Buf is pointer to the command buffer BufLen is length of the buffer. It may not have total Command length if buffer is not available.
static int XPlmi_CdoVerifyHeader(const XPlmiCdo *CdoPtr)
This function verifies CDO header by comparing checksum.
CdoPtr is pointer to the CDO structure XST_SUCCESS on success.XPLMI_ERR_CDO_HDR_ID on invalid CDO header.XPLMI_ERR_CDO_CHECKSUM if CDO checksum fails.
int XPlmi_InitCdo(XPlmiCdo *CdoPtr)
This function initializes the CDO pointer structure.
CdoPtr is pointer to the CDO structure XST_SUCCESS on success and error code on failure
References XPlmi_MemSetBytes.
static int XPlmi_CdoCmdResume(XPlmiCdo *CdoPtr, u32 *BufPtr, u32 BufLen, u32 *Size)
This function will save processed length and resume the command from previous state.
CdoPtr Pointer to the CDO structure BufPtr Pointer to the buffer BufLen Len of the buffer Size Pointer to the Size consumed by the command execution XST_SUCCESS in case of success
static int XPlmi_CdoCmdExecute(XPlmiCdo *CdoPtr, u32 *BufPtr, u32 BufLen, u32 *Size)
This function copies gets the prepares the CMD pointer and executes it.
CdoPtr is pointer to the CDO structure BufPtr is pointer to the buffer BufLen is length of the buffer Size is pointer to the Size consumed by the command execution XST_SUCCESS on success.XPLMI_ERR_MEMCPY_CMD_EXEC if mem copy command execution fails.
int XPlmi_ProcessCdo(XPlmiCdo *CdoPtr)
This function process the CDO file.
CdoPtr is pointer to the CDO structure XST_SUCCESS on success.XPLMI_INVALID_BREAK_LENGTH on invalid break length provided in CDO.
References XPLMI_ERR_MAX_RECURSIVE_CDO_PROCESS, XPLMI_INVALID_BREAK_LENGTH, XPlmi_LogPlmErr, XPLMI_MAX_RECURSIVE_CDO_PROCESS, XPlmi_SetPlmLiveStatus, XPLMI_SLD_IN_PROGRESS, XPlmi_SldState.
Referenced by XPlmi_ExecuteProc.
int XPlmi_CmdExecute(XPlmi_Cmd *CmdPtr)
This function will call the command handler registered with the command.
Command handler shall execute the command till the payload length. CmdPtr is pointer to command structure XST_SUCCESS on success.XPLMI_ERR_MODULE_NOT_REGISTERED if the module is not registered.XPLMI_ERR_CMD_APIID on invalid module and unregistered CMD ID.XPLMI_ERR_CMD_HANDLER_NULL if command handler is not registered.XPLMI_ERR_CDO_CMD on invalid CDO command handler.
References XPLMI_CMD_IN_PROGRESS, XPLMI_ERR_CMD_APIID, XPLMI_ERR_CMD_HANDLER_NULL, XPLMI_ERR_MODULE_NOT_REGISTERED, XPlmi_GetModule, XPlmi_LogPlmErr.
int XPlmi_CmdResume(XPlmi_Cmd *CmdPtr)
This function resumes the command after being partially executed.
Resume handler shall execute the command till the payload length. CmdPtr is pointer to command structure XST_SUCCESS on success.XPLMI_ERR_RESUME_HANDLER if CDO CMD resume handler fails.
int XPlmi_InitUart(void)
This function initializes the PS UART.
XST_SUCCESS on success.XPLMI_ERR_UART_MEMSET on UART instance failure.XPLMI_ERR_UART_LOOKUP if UART driver lookup fails.XPLMI_ERR_UART_CFG if UART driver configuration fails.XPLMI_ERR_UART_PSV_SET_BAUD_RATE if failed to set the baud rate.
References UART_INITIALIZED, UART_PRINT_ENABLED, XPLMI_ERR_UART_CFG, XPLMI_ERR_UART_LOOKUP, XPLMI_ERR_UART_MEMSET, XPLMI_ERR_UART_PSV_SET_BAUD_RATE, XPlmi_GetUartBaseAddr, XPlmi_MemSetBytes, XPlmi_SetLpdInitialized.
Referenced by XPlmi_LpdInit.
int XPlmi_ConfigUart(u8 UartSelect, u8 UartEnable)
This function configures the PS UART base address.
UartSelect is the uart number to be selected UartEnable is the flag used to enable or disable uart XST_SUCCESS on success.XPLMI_ERR_NO_UART_PRESENT if UART is not available to configure.XPLMI_ERR_CURRENT_UART_INVALID if selected UART base address is invalid.XPLMI_ERR_INVALID_UART_SELECT if invalid UART SELECT argument is passed.XPLMI_ERR_INVALID_UART_ENABLE if invalid UART ENABLE argument is passed.
References UART_PRINT_ENABLED, XPLMI_ERR_CURRENT_UART_INVALID, XPLMI_ERR_INVALID_UART_ENABLE, XPLMI_ERR_INVALID_UART_SELECT, XPLMI_ERR_NO_UART_PRESENT, XPlmi_GetUartBaseAddr, XPlmi_SetLpdInitialized, XPlmi_UnSetLpdInitialized.
Referenced by XPlmi_EventLogging.
void outbyte(char c)
This function prints and logs the terminal prints to debug log buffer.
c is the character to be printed and logged
References XPlmi_GetUartBaseAddr.
void XPlmi_Print(u16 DebugType, const char8 *Ctrl1,...)
This function prints debug messages with timestamp.
DebugType is the PLM Debug level for the message Ctrl1 is the format specified string to print
References XPlmi_PrintPlmTimeStamp.
Referenced by XPlmi_ScatterWrite, XPlmi_ScatterWrite2, XPlmi_SetFipsKatMask.
static int XPlmi_DmaDrvInit(XPmcDma *DmaPtr, u32 BaseAddress)
This function is used to initialize a single Driver instance.
DmaPtr is pointer to the DMA instance DeviceId of the DMA as defined in xparameters.h XST_SUCCESS on success.XPLMI_ERR_DMA_LOOKUP if DMA driver lookup fails.XPLMI_ERR_DMA_CFG if DMA driver configuration fails.XPLMI_ERR_DMA_SELFTEST if DMA driver self test fails.
static void XPlmi_SSSCfgDmaDma(u32 Flags)
This function is used set SSS configuration for DMA to DMA.
Flags to select PMC DMA
static void XPlmi_SSSCfgDmaPzm(void)
This function is used set SSS configuration for DMA to PZM.
static void XPlmi_SSSCfgSbiDma(void)
This function is used set SSS configuration for SBI to DMA.
static int XPlmi_DmaChXfer(u64 Addr, u32 Len, XPmcDma_Channel Channel, u32 Flags)
This function is used transfer the data on SRC or DST channel.
Addr is address to which data has to be stored Len is length of the data in words Channel is SRC/DST channel selection Flags to select PMC DMA and DMA Burst type XST_SUCCESS on success.XPLMI_ERR_DMA_XFER_WAIT if DMA transfer failed to wait.
static int XPlmi_StartDma(u64 SrcAddr, u64 DestAddr, u32 Len, u32 Flags, XPmcDma **DmaPtrAddr)
This function is used initiate the DMA to DMA transfer.
SrcAddr is address for SRC channel to fetch data from DestAddr is address for DST channel to store the data Len is length of the data in words Flags to select PMC DMA and DMA Burst type DmaPtrAddr is to store address to PmcDmaInstance XST_SUCCESS on success and error codes on failure
int XPlmi_DmaInit(void)
This function will initialize the DMA driver instances.
XST_SUCCESS on success and error code on failure
XPmcDma* XPlmi_GetDmaInstance(UINTPTR BaseAddress)
This function returns DMA instance.
DeviceId is PMC DMA's device ID PMC DMA instance pointer.
int XPlmi_WaitForNonBlkDma(u32 DmaFlags)
This function is used to wait on non blocking DMA.
DmaFlags to differentiate between PMCDMA_0 and PMCDMA_1 XST_SUCCESS on success.XPLMI_ERR_NON_BLOCK_DMA_WAIT_DEST if Non Block Dma transfer wait failed in destination channel WaitForDone.XPLMI_ERR_NON_BLOCK_DMA_WAIT_SRC if Non Block Dma transfer wait failed in source channel WaitForDone.
References XPLMI_ERR_NON_BLOCK_DMA_WAIT_DEST, XPLMI_ERR_NON_BLOCK_DMA_WAIT_SRC.
int XPlmi_WaitForNonBlkSrcDma(u32 DmaFlags)
This function is used set wait on non blocking DMA.
It is called when Src DMA is non blocking. DmaFlags to differentiate between PMCDMA_0 and PMCDMA_1 XST_SUCCESS on success.XPLMI_ERR_NON_BLOCK_SRC_DMA_WAIT if Non Block source Dma transfer wait failed.
References XPLMI_ERR_NON_BLOCK_SRC_DMA_WAIT.
int XPlmi_WaitForNonBlkDestDma(u32 DmaFlags)
This function is used set wait on non blocking DMA.
It is called when Dest DMA is non blocking. DmaFlags to differentiate between PMCDMA_0 and PMCDMA_1 XST_SUCCESS on success.XPLMI_ERR_NON_BLOCK_DEST_DMA_WAIT if Non Block destination Dma transfer wait failed.
References XPLMI_ERR_NON_BLOCK_DEST_DMA_WAIT.
int XPlmi_SbiDmaXfer(u64 DestAddr, u32 Len, u32 Flags)
This function is used to transfer the data from SBI to DMA.
DestAddr to which data has to be stored Len of the data in words Flags to select PMC DMA and DMA Burst type XST_SUCCESS on success and error codes on failure
int XPlmi_DmaSbiXfer(u64 SrcAddr, u32 Len, u32 Flags)
This function is used to transfer the data from DMA to SBI.
SrcAddr for DMA to fetch data from Len of the data in words Flags to select PMC DMA and DMA Burst type XST_SUCCESS on success and error codes on failure
int XPlmi_DmaXfr(u64 SrcAddr, u64 DestAddr, u32 Len, u32 Flags)
This function is used to initiate and complete the DMA to DMA transfer.
SrcAddr for SRC channel to fetch data from DestAddr for DST channel to store the data Len of the data in words Flags to select PMC DMA and DMA Burst type XST_SUCCESS on success.XPLMI_ERR_DMA_XFER_WAIT_SRC if Dma Xfer failed in Src Channel wait for done.XPLMI_ERR_DMA_XFER_WAIT_DEST if Dma Xfer failed in Dest Channel wait for done.
References XPLMI_ERR_DMA_XFER_WAIT_DEST, XPLMI_ERR_DMA_XFER_WAIT_SRC, XPlmi_GetPlmiWaitForDone, XPlmi_GetTimerValue, XPlmi_MeasurePerfTime.
Referenced by XPlmi_DmaTransfer, XPlmi_MemCpy64, XPlmi_MemSet.
int XPlmi_EccInit(u64 Addr, u32 Len)
This function is used to initialize the ECC memory.
Addr is memory address to be initialized Len is size of memory to be initialized in bytes Status of the DMA transfer
References XPLMI_WORD_LEN.
Referenced by XPlmi_InitNVerifyMem, XPlmi_MemSet.
int XPlmi_MemSet(u64 DestAddress, u32 Val, u32 Len)
This function is used to Set the memory with a value.
DestAddress is the address where the val need to be set Val is the value that has to be set Len is size of memory to be set in words Status of the DMA transfer
References XPlmi_DmaXfr, XPlmi_EccInit, XPLMI_WORD_LEN.
Referenced by XPlmi_MemSetBytes, XPlmi_RunTimeConfigInit.
int XPlmi_InitNVerifyMem(u64 Addr, u32 Len)
This function initializes the memory using PZM and verifies by reading back initialized memory.
Addr Memory address to be initialized Len Length of the area to be initialized in bytes XST_SUCCESS on success and error codes on failure
References XPlmi_EccInit, XPLMI_WORD_LEN.
void XPlmi_SetMaxOutCmds(u8 Val)
This function is used to set the MaxOutCmds variable.
This is required to support non blocking DMA. Val to be set
int XPlmi_MemSetBytes(void *const DestPtr, u32 DestLen, u8 Val, u32 Length)
This function is used to Set the memory with a value.
If Len is greater than DestLen, then DestPtr is filled with Val till DestLen bytes and is considered as a failure. DestPtr is the pointer where the val need to be set DestLen is the memory allotted to destination buffer in bytes Val is the value that has to be set Length is size of memory to be set in bytes XST_SUCCESS on success and error code on failure
References XPlmi_MemSet, XPLMI_WORD_LEN.
Referenced by XPlmi_ExecuteProc, XPlmi_InitCdo, XPlmi_InitUart.
int XPlmi_MemCpy64(u64 DestAddress, u64 SrcAddress, u32 Length)
This function can copy the content of memory for both 32 and 64-bit address space.
DestAddress is the address of the destination where content of SrcAddr memory should be copied. SrcAddress is the address of the source where copy should start from. Length is size of memory to be copied in bytes. XST_SUCCESS on success and error code on failure
References XPlmi_DmaXfr, XPLMI_WORD_LEN.
static int XPlmi_CmdEmFeatures(XPlmi_Cmd *Cmd)
This function is reserved to get the supported features for this module.
Cmd is pointer to the command structure XST_SUCCESS always.
static int XPlmi_CmdEmSetAction(XPlmi_Cmd *Cmd)
This function sets the error action as prescribed by the command.
Command payload parameters are: Error Node IDError Action: 0 - Invalid1 - POR2 - SRST3 - Custom(Not supported)4 - ErrOut5 - Subsystem Shutdown6 - Subsystem Restart7 - None Error ID Mask Cmd is pointer to the command structure XST_SUCCESS on success.XPLMI_INVALID_NODE_ID on invalid node ID.XPLMI_INVALID_ERROR_ACTION on invalid error action.XPLMI_CANNOT_CHANGE_ACTION if failed to change error action.XPLMI_LPD_UNINITIALIZED if LPD failed to initialize.
static void XPlmi_ErrIntrSubTypeHandler(u32 ErrorNodeId, u32 RegMask)
This function is the interrupt handler for Error subtype subsystem shutdown and subsystem restart.
ErrorNodeId is the node ID for the error event RegMask is the register mask of the error received
static void XPlmi_DumpRegisters(void)
This function dumps the registers which can help debugging.
static void XPlmi_ErrOutNClearFwCR(u32 ErrorId)
This function updates error out count and clears PMC FW_CR error.
ErrorId is the Error number for which error out count to be updated.
void XPlmi_LogPlmErr(int ErrStatusVal)
This function is called for logging PLM error into FW_ERR register.
ErrStatusVal is the error code written to the FW_ERR register
References XPlmi_UtilRMW.
Referenced by XPlmi_CmdExecute, XPlmi_ErrMgr, XPlmi_LpdInit, XPlmi_ProcessCdo.
void XPlmi_ErrMgr(int ErrStatusVal)
This function is called in PLM error cases.
ErrStatusVal is the error code written to the FW_ERR register
References XPlmi_IsPlmUpdateDone, XPlmi_LogPlmErr, XPlmi_PORHandler, XPlmi_SetPlmLiveStatus, XPLMI_SSIT_MASTER_SLR, XPLMI_SSIT_MONOLITIC, XPlmi_TriggerFwNcrError, XPlmi_UtilRMW.
Referenced by XPlmi_HandleLinkDownError, XPlmi_HandleLinkUpEvent, XPlmi_LpdInit, XPlmi_TaskDispatchLoop.
void XPlmi_UpdateErrorSubsystemId(u32 ErrorNodeId, u32 ErrorMasks, u32 SubsystemId)
This function updates the SubystemId for the given error index.
ErrorNodeId is the node Id for the error event ErrorMasks is the Register mask of the Errors SubsystemId is the Subsystem ID for the error node.
References XPlmi_GetErrorTable.
void XPlmi_PORHandler(void)
This function triggers Power on Reset.
References XPlmi_SysmonClkSetIro, XPlmi_UtilRMW.
Referenced by XPlmi_ErrMgr, XPlmi_HandleSwError.
u32 XPlmi_GetErrorId(u32 ErrorNodeId, u32 RegMask)
This function returns Error Id for the given error node type and error mask.
ErrorNodeId is the error node Id. RegMask is register mask of the error. ErrorId value.
Referenced by XPlmi_EmGetAction, XPlmi_ErrPrintToLog, XPlmi_HandleSwError.
static void XPlmi_TriggerSecureLockdown(u32 ErrorNodeId, u32 RegMask)
This function triggers secure lockdown.
ErrorNodeId is the node ID for the error event RegMask is the register mask of the error received
void XPlmi_HandleSwError(u32 ErrorNodeId, u32 RegMask)
This function handles the Software error triggered from within PLM.
ErrorNodeId is the node ID for the error event RegMask is the register mask of the error received
References XPlmi_EmDisable, XPlmi_GetErrorId, XPlmi_GetErrorTable, XPlmi_PORHandler, XPlmi_SoftResetHandler, XPlmi_UpdateNumErrOutsCount.
Referenced by XPlmi_AsuUpdate.
static void XPlmi_DetectAndHandleTamper(void)
This function detects and handles tamper condition in EAM IRQ interrupt handler.
void XPlmi_ErrIntrHandler(void *CallbackRef)
This function is default interrupt handler for EAM error which will add the task to the task queue.
CallbackRef is presently the interrupt number that is received
References XPlmi_ErrorTaskHandler, XPlmi_GetTaskInstance, XPlmi_PlmIntrDisable, XPlmi_TaskTriggerNow.
int XPlmi_ErrorTaskHandler(void *Data)
This function is the interrupt handler for the EAM errors.
Data is presently passed as NULL XST_SUCCESS always.
References GET_PMC_ERR_ACTION_OFFSET, GET_PMC_IRQ_MASK, XPlmi_EmClearError, XPlmi_EmDisable, XPlmi_ErrPSMIntrHandler, XPlmi_GetErrorTable, XPlmi_PlmIntrClear, XPlmi_PlmIntrEnable, XPlmi_Versal2Ve2VmEAMHandler.
Referenced by XPlmi_EmInit, XPlmi_ErrIntrHandler.
void XPlmi_EmClearError(XPlmi_EventType ErrorNodeType, u32 ErrorId)
This function clears any previous errors before enabling them.
ErrorNodeType is the node type for the error event ErrorId is the index of the error to be cleared
References XPlmi_GetErrorTable, XPlmi_GetEventIndex.
Referenced by XPlmi_EmSetAction, XPlmi_ErrorTaskHandler, XPlmi_Versal2Ve2VmEAMHandler.
u32 EmDisableErrAction(u32 ErrMaskRegAddr, u32 RegMask)
This function disables the error action for the given error mask.
ErrMaskRegAddr is the error action mask register address RegMask is the register mask of the error to be disabled XST_SUCCESS on success.XPLMI_ERROR_ACTION_NOT_DISABLED if error action is not disabled.
Referenced by XPlmi_EmDisablePmcErrors, XPlmi_EmDisablePsmErrors, XPlmi_GenericHandler.
static int EmEnableErrAction(u32 ErrMaskRegAddr, u32 RegMask)
This function enables the error action for the given error mask.
ErrMaskRegAddr is the error action mask register address RegMask is the register mask of the error to be disabled XST_SUCCESS on success.XPLMI_ERROR_ACTION_NOT_ENABLED if error action is not enabled.
int XPlmi_EmDisablePmcErrors(u32 RegOffset, u32 RegMask)
This function disables the PMC error actions for the given mask.
RegOffset is the offset for the PMC ERR, POR ,IRQ mask,SRST mask RegMask is the register mask of the error to be disabled XST_SUCCESS on success.XPLMI_ERROR_ACTION_NOT_DISABLED if error action is not disabled.
References EmDisableErrAction, GET_PMC_ERR_OUT_MASK, GET_PMC_IRQ_MASK, GET_PMC_POR_MASK, GET_PMC_SRST_MASK.
Referenced by XPlmi_EmDisable, XPlmi_EmInit.
int XPlmi_EmDisable(u32 ErrorNodeId, u32 RegMask)
This function disables the responses for the given error.
ErrorNodeId is the node Id for the error event RegMask is the register mask of the error to be disabled XST_SUCCESS on success.XPLMI_ERROR_ACTION_NOT_DISABLED if error action is not disabled.XPLMI_INVALID_ERROR_TYPE on invalid error type.
References GET_PMC_ERR_ACTION_OFFSET, XPlmi_EmDisableLpdSlcrErrors, XPlmi_EmDisablePmcErrors, XPlmi_EmDisablePsmErrors, XPlmi_GetEventIndex.
Referenced by XPlmi_EmSetAction, XPlmi_ErrorTaskHandler, XPlmi_HandleSwError, XPlmi_Versal2Ve2VmEAMHandler.
static int XPlmi_EmEnableAction(XPlmi_EventType ErrorNodeType, u32 RegMask, u8 Action)
This function enables HW error actions for the given Error.
ErrorNodeType is the node type for the error event RegMask is the register mask of the error to be enabled Action is the HW Error action of the error to be enabled XST_SUCCESS on success.XPLMI_ERROR_ACTION_NOT_ENABLED if error action is not enabled.XPLMI_INVALID_ERROR_ACTION on invalid error action.XPLMI_INVALID_ERROR_TYPE on invalid error type.
int XPlmi_EmConfig(XPlmi_EventType NodeType, u32 ErrorId, u8 ActionId, XPlmi_ErrorHandler_t ErrorHandler, const u32 SubsystemId)
This function configures the Action specified for a given Error ID.
NodeType is the error node type ErrorId is the index of the error to which given action to be set ActionId is the action that need to be set for ErrorId. Action can be SRST/POR/ERR OUT/INT ErrorHandler If INT is defined as response, handler should be defined. SubsystemId is the subsystem ID for the error node XST_SUCCESS on success and error code on failure
References XPlmi_ErrPrintToLog, XPlmi_GetErrorTable.
Referenced by XPlmi_EmSetAction, XPlmi_ReconfigErrActions.
int XPlmi_EmSetAction(u32 ErrorNodeId, u32 ErrorMasks, u8 ActionId, XPlmi_ErrorHandler_t ErrorHandler, const u32 SubsystemId)
This function sets the Action specified for a given Error Masks.
ErrorNodeId is the node ID for the error event ErrorMasks is the error masks to which specified action to be set ActionId is the action that need to be set for ErrorMasks. Action can be SRST/POR/ERR OUT/INT ErrorHandler If INT is defined as response, handler should be defined. SubsystemId is the subsystem ID for the error node XST_SUCCESS on success.XPLMI_INVALID_NODE_ID on invalid node ID.XPLMI_INVALID_ERROR_ID on invalid error ID.XPLMI_INVALID_ERROR_HANDLER on invalid error handler.
References XPlmi_EmClearError, XPlmi_EmConfig, XPlmi_EmDisable, XPlmi_GetErrorTable.
Referenced by XPlmi_EmInit, XPlmi_LpdSlcrEmInit, XPlmi_PsEmInit, XPlmi_RegisterTamperIntrHandler, XPlmi_Versal2Ve2VmSetAction.
int XPlmi_EmGetAction(u32 ErrorNodeId, u32 ErrorMasks, u8 *ActionIdPtr)
This function gets the Action for a given Error Node ID and Error Mask.
ErrorNodeId is the node ID for the error event ErrorMasks is the register mask of the error ActionIdPtr is the pointer to store the action ID XST_SUCCESS on success.XPLMI_INVALID_NODE_ID on invalid node ID.XPLMI_INVALID_ERROR_ID on invalid error ID.XST_INVALID_PARAM on invalid parameter.
References XPlmi_GetErrorId, XPlmi_GetErrorTable.
int XPlmi_EmInit(XPlmi_ShutdownHandler_t SystemShutdown)
This function initializes the error module.
Disables all the error actions and registers default action. SystemShutdown is the pointer to the PM system shutdown callback handler for action subtype system shutdown XST_SUCCESS on success and error code on failure
References GET_PMC_ERR_ACTION_OFFSET, GET_RTCFG_PMC_ERR_ADDR, XPlmi_ClearSsitErrors, XPlmi_EmDisablePmcErrors, XPlmi_EmSetAction, XPLMI_ERR_EMINIT_INVALID_PARAM, XPlmi_ErrorTaskHandler, XPlmi_GetErrorTable, XPlmi_GetTaskInstance, XPlmi_IsPlmUpdateDone, XPlmi_ReconfigErrActions, XPlmi_RegisterTamperIntrHandler, XPlmi_SysMonOTDetect, XPlmi_TaskCreate.
void XPlmi_SoftResetHandler(void)
This function sets clock source to IRO for ES1 silicon and resets the device.
References XPlmi_SysmonClkSetIro.
Referenced by XPlmi_HandleSwError.
void XPlmi_TriggerFwNcrError(void)
This function sets clock source to IRO for ES1 silicon and triggers FW NCR error.
References XPlmi_GetErrorTable, XPlmi_SysmonClkSetIro, XPlmi_UtilRMW.
Referenced by XPlmi_ErrMgr.
void XPlmi_SetEmSubsystemId(const u32 *Id)
This function sets EmSubsystemId.
Id pointer to set the EmSubsystemId
u32 XPlmi_GetEmSubsystemId(void)
This function returns EmSubsystemId.
EmSubsystemId
Referenced by XPlmi_Versal2Ve2VmSetAction.
u32 XPlmi_UpdateNumErrOutsCount(u8 UpdateType)
This function updates NumErrOuts and returns number of error outs count to the caller.
UpdateType is increment/decrement Number of ErrOuts count
References XPlmi_GetNumErrOuts.
Referenced by XPlmi_HandleSwError.
int XPlmi_CheckNpiErrors(void)
This function checks for NPI errors and logs them if present.
XST_SUCCESS if no errors detected.XST_FAILURE if NPI errors are detected.
int XPlmi_ClearNpiErrors(void)
This function clears NPI errors.
XST_SUCCESS on success and error code on failure
References XPLMI_ERR_NPI_LOCK, XPlmi_UtilRMW.
int XPlmi_EventLogging(XPlmi_Cmd *Cmd)
This function processes event logging commands for managing log buffers, log levels, and UART configuration.
Supported commands and their payload parameters: - Command 1: Configure print log level - Arg1: Log Level - Command 2: Configure Debug Log buffer memory - Arg1: High Address - Arg2: Low Address - Arg3: Buffer Length in bytes - Command 3: Retrieve Debug Log buffer data - Arg1: Destination High Address - Arg2: Destination Low Address - Command 4: Retrieve Debug Log buffer information - Command 5: Configure Trace Log buffer memory - Arg1: High Address - Arg2: Low Address - Arg3: Buffer Length in bytes - Command 6: Retrieve Trace Log buffer data - Arg1: Destination High Address - Arg2: Destination Low Address - Command 7: Retrieve Trace Log buffer information - Command 8: Configure UART settings - Arg1: UART Select - Arg2: UART Enable/Disable Cmd is pointer to the command structure XST_SUCCESS on success.XPLMI_ERR_INVALID_LOG_LEVEL on invalid log level.XST_INVALID_PARAM on invalid logging command.
References XPlmi_ConfigUart, XPLMI_ERR_INVALID_LOG_LEVEL, XPLMI_EVENT_LOGGING_CMD_ID, XPlmi_GetTraceLogInst.
static int XPlmi_Features(XPlmi_Cmd *Cmd)
This function checks if a particular PLM Command ID is supported or not.
Command ID is the only payload parameter. Cmd is pointer to the command structure XST_SUCCESS always.
static int XPlmi_Nop(XPlmi_Cmd *Cmd)
This function provides no operation.
The command is supported for alignment purposes. Zero command payload parameters. Cmd is pointer to the command structure XST_SUCCESS always.
static int XPlmi_GetDeviceID(XPlmi_Cmd *Cmd)
This function reads the device ID and fills in the response buffer.
Command: GetDeviceID Reserved[31:24]=0 Length[23:16]=[0] PLM=1 CMD_DEVID=18 Payload = 0 The command reads PMC_TAP_IDCODE register and EFUSE_CACHE_IP_DISABLE_0 register and fills the command response array with these values. Cmd is pointer to the command structure XST_SUCCESS always.
int XPlmi_GenericMaskPoll(XPlmi_Cmd *Cmd, u64 Addr, u32 Type)
This function provides generic implementation for both 32-bit and 64-bit mask poll command execution.
Command payload parameters are - Address - Mask - Expected Value - Timeout in us - Deferred Error flag - Optional 0 - Return error in case of failure, 1 - Ignore error, return success always 2 - Defer error till the end of partition load 3 - Break to end offset in case of failure - Error Code Cmd is pointer to the command structure Addr is address of mask poll Type is flag indicating if the address is 64-bit XST_SUCCESS on success.XST_FAILURE if timedout.
References XPlmi_GetTimerValue, XPlmi_MeasurePerfTime, XPlmi_UtilPoll, XPlmi_UtilPoll64.
Referenced by XPlmi_ListMaskPoll.
static int XPlmi_MaskPoll(XPlmi_Cmd *Cmd)
This function provides 32 bit mask poll command execution.
Command payload parameters are - Address - Mask - Expected Value - Timeout in us - Deferred Error flag - Optional 0 - Return error in case of failure, 1 - Ignore error, return success always 2 - Defer error till the end of partition load 3 - Break to end offset in case of failure - Error Code Cmd is pointer to the command structure XST_SUCCESS on success.XST_FAILURE if timedout.
static int XPlmi_MaskWrite(XPlmi_Cmd *Cmd)
This function provides 32 bit mask write command execution.
Command payload parameters are - Address - Mask - Value Cmd is pointer to the command structure XST_SUCCESS always.
static int XPlmi_Write(XPlmi_Cmd *Cmd)
This function provides 32 bit Write command execution.
Command payload parameters are - Address - Value Cmd is pointer to the command structure XST_SUCCESS always.
static int XPlmi_Delay(XPlmi_Cmd *Cmd)
This function provides delay command execution.
Command payload parameter delay in micro seconds Cmd is pointer to the command structure XST_SUCCESS always.
int XPlmi_DmaTransfer(u64 Dest, u64 Src, u32 Len, u32 Flags)
This function provides functionality for DMA write.
Dest is the destination address Src is the source address Len is the number of words to be transferred Flags is the DMA transfer related flags XST_SUCCESS on success.XPLMI_ERR_UNALIGNED_DMA_XFER if unaligned DMA transfer fails.
References XPlmi_DmaXfr, XPLMI_ERR_UNALIGNED_DMA_XFER, XPLMI_WORD_LEN.
Referenced by XPlmi_MoveBuffer, XPlmi_PsmSequence, XPlmi_StoreBuffer.
static int XPlmi_DmaWrite(XPlmi_Cmd *Cmd)
This function provides DMA write command execution.
Command payload parameters are - High Dest Addr - Low Dest Addr Cmd is pointer to the command structure XST_SUCCESS on success and error code on failure
static int XPlmi_MaskPoll64(XPlmi_Cmd *Cmd)
This function provides 64 bit mask poll command execution.
Command payload parameters are - High Address - Low Address - Mask - Expected Value - Timeout in us - Deferred Error flag - Optional 0 - Return error in case of failure, 1 - Ignore error, return success always 2 - Defer error till the end of partition load 3 - Break to end offset in case of failure - Error Code Cmd is pointer to the command structure XST_SUCCESS on success.XST_FAILURE if timedout.
static int XPlmi_MaskWrite64(XPlmi_Cmd *Cmd)
This function provides 64 bit mask write command execution.
Command payload parameters are - High Address - Low Address - Mask - Value Cmd is pointer to the command structure XST_SUCCESS always.
static int XPlmi_Write64(XPlmi_Cmd *Cmd)
This function provides 64 bit write command execution.
Command payload parameters are - High Address - Low Address - Value Cmd is pointer to the command structure XST_SUCCESS always.
static int XPlmi_DmaXfer(XPlmi_Cmd *Cmd)
This function provides DMA Xfer command execution.
Command payload parameters are - High Src Addr - Low Src Addr - High Dest Addr - Low Dest Addr - Params - AXI burst type (Fixed/INCR) Cmd is pointer to the command structure XST_SUCCESS on success and error code on failure
static int XPlmi_InitSeq(XPlmi_Cmd *Cmd)
This function provides INIT_SEQ command execution.
Command payload parameters are - DATA Cmd is pointer to the command structure and unused XPLMI_ERR_CMD_NOT_SUPPORTED always.
u32 XPlmi_GetReadbackLen(u32 Len)
This function processes and provides readback length.
Len is the current readback length Readback length
static int XPlmi_CfiRead(XPlmi_Cmd *Cmd)
This function provides CFI READ command execution.
Command payload parameters are - Params - SMPA/JTAG/DDR - High Dest Addr - Low Dest Addr - Read Length in number of words to be read from CFU - DATA (CFU READ Packets) Cmd is pointer to the command structure XST_SUCCESS on success.XPLMI_ERR_READBACK_BUFFER_OVERFLOW if readback buffer overflows.
static int XPlmi_Set(XPlmi_Cmd *Cmd)
This function provides SET command execution.
Command payload parameters are - High Dest Addr - Low Dest Addr - Length (Length of words to set to value) - Value Cmd is pointer to the command structure XST_SUCCESS always.
static int XPlmi_DmaWriteKeyHole(XPlmi_Cmd *Cmd)
This function provides DMA key hole write command execution.
Command payload parameters are - High Dest Addr - Low Dest Addr - Keyhole Size in bytes - DATA Cmd is pointer to the command structure XST_SUCCESS on success and error code on failure
static int XPlmi_SetBoard(XPlmi_Cmd *Cmd)
This function provides SET BOARD command execution.
Command payload parameters are - Board Name Cmd is pointer to the command structure XST_SUCCESS always.
static int XPlmi_GetBoard(XPlmi_Cmd *Cmd)
This function provides GET BOARD command execution.
Cmd is pointer to the command structure Command payload parameters are High AddrLow AddrMax size in words XST_SUCCESS on success and error code on failure
static int XPlmi_SetWdtParam(XPlmi_Cmd *Cmd)
This function sets the WDT parameters used in PLM.
Cmd is pointer to the command structure Command payload parameters are Node Id for PMC, PS MIOPeriodicity XST_SUCCESS on success and error code on failure
static int XPlmi_LogString(XPlmi_Cmd *Cmd)
This function adds Debug string to PLM logs.
Cmd is pointer to the command structure Command payload parameters are Debug String XST_SUCCESS always.
static int XPlmi_LogAddress(XPlmi_Cmd *Cmd)
This function reads the value at an address and displays and adds the value to PLM logs.
Cmd is pointer to the command structure Command payload parameters are Low AddressHigh Address (Optional) XST_SUCCESS always.
static int XPlmi_Marker(XPlmi_Cmd *Cmd)
This function provides Marker command execution.
Cmd is pointer to the command structure Command payload parameters are TypeString XST_SUCCESS always.
int XPlmi_MoveBuffer(u32 BufferIndex, XPlmi_BufferList *BufferList)
This function provides functionality to move procs when proc command is received for existing BufferId.
BufferIndex is the index of BufferId to be moved BufferList is the list of buffers whose buffers need to be moved XST_SUCCESS on success and error code on failure
References XPlmi_DmaTransfer, XPLMI_WORD_LEN.
Referenced by XPlmi_StoreBuffer.
int XPlmi_SetBufferList(u32 Address, u16 Size)
This function sets PSM BufferList address to given Address and Size.
Address is the address of Buffer reserved memory for PSM BufferList Size is the size of Buffer reserved memory for PSM BufferList in bytes XST_SUCCESS on success and error code on failureXPLMI_ERR_PROC_INVALID_ADDRESS_RANGE if provided proc address is invalid.
References XPLMI_ERR_PROC_INVALID_ADDRESS_RANGE, XPlmi_GetBufferList.
int XPlmi_SearchBufferList(XPlmi_BufferList *BufferList, u32 BufferId, u64 *BufAddr, u32 *BufLen)
This function searches Buffer list with the buffer Id to provide buffer address and buffer length.
BufferList is the pointer to the list of buffers to search BufferId is the id of the buffer to search for BufAddr is the address of the Buffer found BufLen is the length of the Buffer found XST_SUCCESS on success.XPLMI_ERR_BUFFER_MEM_NOT_AVAILABLE if Buffer memory is not available for storing.XPLMI_ERR_PROCID_NOT_VALID if provided proc id is invalid.
References XPLMI_ERR_BUFFER_MEM_NOT_AVAILABLE, XPLMI_ERR_PROCID_NOT_VALID, XPLMI_WORD_LEN.
Referenced by XPlmi_ExecuteProc, XPlmi_ListMaskPoll, XPlmi_ListMaskWrite, XPlmi_ListWrite.
int XPlmi_ExecuteProc(u32 ProcId)
This function provides functionality to execute given ProcId when request to execute a particular ProcId.
ProcId is ProcId to be executed XST_SUCCESS on success.XPLMI_ERR_PROC_LPD_NOT_INITIALIZED The Proc command cannot be executed because the LPD is not initialized.
References XPLMI_ERR_PROC_LPD_NOT_INITIALIZED, XPlmi_GetBufferList, XPlmi_MemSetBytes, XPlmi_ProcessCdo, XPlmi_SearchBufferList.
Referenced by XPlmi_HandleLinkDownError, XPlmi_HandleLinkUpEvent, XPlmi_RunProc.
static int XPlmi_Proc(XPlmi_Cmd *Cmd)
This function copies the proc data to reserved PSM/PMC RAM when proc command is received.
Cmd is pointer to the command structure Command payload parameters are ProcIdData XST_SUCCESS on success.XPLMI_ERR_PROC_LPD_NOT_INITIALIZED The Proc command cannot be stored because the LPD is not initialized.
int XPlmi_StoreBuffer(XPlmi_Cmd *Cmd, u32 BufferId, XPlmi_BufferList *BufferList)
This function stores the buffer data into the buffer list provided.
Cmd is pointer to the command structure BufferId is the Id of the Buffer to be stored in the buffer list BufferList is the pointer to the BufferList XST_SUCCESS on success.XPLMI_ERR_BUFFER_MEM_NOT_AVAILABLE if Buffer memory is not available for storing.XPLMI_UNSUPPORTED_PROC_LENGTH if received proc does not fit in proc memory.XPLMI_MAX_PROC_COMMANDS_RECEIVED on maximum supported proc commands received.
References XPlmi_DmaTransfer, XPLMI_ERR_BUFFER_MEM_NOT_AVAILABLE, XPLMI_MAX_PROC_COMMANDS_RECEIVED, XPlmi_MoveBuffer, XPLMI_UNSUPPORTED_PROC_LENGTH, XPLMI_WORD_LEN.
Referenced by XPlmi_ListSet.
static int XPlmi_OTCheck(XPlmi_Cmd *Cmd)
This function provides Over Temperature Check command execution.
Cmd is pointer to the command structure Command payload parameters are Delay in milliseconds XST_SUCCESS always.
static int XPlmi_Begin(XPlmi_Cmd *Cmd)
This function provides start of the block.
Command payload parameters are - Offset : specifies no. of words until "end" of the block - String : optional for debugging purpose Cmd is pointer to the command structure XST_SUCCESS on success and error code on failure
static int XPlmi_End(XPlmi_Cmd *Cmd)
This function provides end of the block.
Cmd is pointer to the command structure XST_SUCCESS on success and error code on failure
static int XPlmi_Break(XPlmi_Cmd *Cmd)
This function skips all the commands until the Levels number of nested "end".
Cmd is pointer to the command structure XST_SUCCESS on success and error code on failure
static int XPlmi_SetIpiAccess(XPlmi_Cmd *Cmd)
This function sets ipi access permissions for the range of commands requested.
Cmd is pointer to the command structure Command payload parameters are Api Id Upper Limit, Api Id Lower Limit, Module IdAccess Permission Mask XST_SUCCESS on success. XPLMI_ERR_SET_IPI_INVALID_API_ID_UPPER if the Api Id Upper limit is greater than maximum api countXPLMI_ERR_SET_IPI_INVALID_API_ID_LOWER if the Api Id Lower limit is greater than Api Id upper limitXPLMI_ERR_SET_IPI_ACCESS_PERM_NOT_SET if the Ipi Access permission is not set properlyXPLMI_ERR_SET_IPI_PERM_BUFF_NOT_REGISTERED if the permission buffer in which the access permissions has to be stored is not registered
static int XPlmi_TamperTrigger(XPlmi_Cmd *Cmd)
This function triggers secure lockdown when Tamper Trigger IPI is received.
Cmd is pointer to the command structure Command payload parameters are Tamper Response XST_SUCCESS on success.XPLMI_INVALID_TAMPER_RESPONSE on invalid tamper response received for TamperTrigger IPI call.
int XPlmi_SetDDRMCMainRegSts(u32 DDRMCNum, u32 RegSts)
This function sets the access status of DDR MC main registers.
DDRMCNum - DDR MC number RegSts - To be set status(Busy/Free) XST_SUCCESS on success.error code on failure
References MAX_DEV_DDRMC, XPLMI_DDRMC_UB0_BASE_ADDR, XPLMI_DDRMC_UB1_BASE_ADDR, XPLMI_DDRMC_UB2_BASE_ADDR, XPLMI_DDRMC_UB3_BASE_ADDR, XPLMI_DDRMC_UB_PCSR_LOCK_OFFSET, XPLMI_DDRMC_UB_PMC2UB_GPI1_OFFSET, XPLMI_ERR_INVALID_PARAM, XPlmi_UtilRMW.
static int XPlmi_SetDDRMCRegStsCmdHandler(XPlmi_Cmd *Cmd)
This function handles XPlmi_SetDDRMCRegSts command.
Cmd is pointer to the command structure Command payload parameters are DDR MC numberTo be set status(Busy/Free) XST_SUCCESS on success.error code on failure
static int XPlmi_InvalidCmdHandler(u32 *Payload, u32 *RespBuf)
This function calls the handler for invalid commands.
Payload is pointer to payload data RespBuf buffer to store response of slaves XST_SUCCESS on successful communication error code On failure
int XPlmi_GicRegisterHandler(u32 GicPVal, u32 GicPxVal, GicIntHandler_t Handler, void *Data)
This will register the GIC handler.
GicPVal indicates GICP source GicPxVal indicates GICPx source Handler is the interrupt handler Data is the pointer to arguments to interrupt handler XST_SUCCESS on success.XPLM_ERR_TASK_CREATE if failed to create task.
References XPLM_ERR_TASK_CREATE, XPlmi_GetGicIntrId, XPlmi_TaskCreate.
void XPlmi_GicIntrClearStatus(u32 GicPVal, u32 GicPxVal)
This will clear the GIC interrupt.
GicPVal indicates GICP source GicPxVal indicates GICPx source
References XPLMI_GICPX_LEN.
Referenced by XPlmi_GenericHandler.
void XPlmi_GicIntrEnable(u32 GicPVal, u32 GicPxVal)
This will enable the GIC interrupt.
GicPVal indicates GICP source GicPxVal indicates GICPx source
References XPLMI_GICPX_LEN.
void XPlmi_GicIntrDisable(u32 GicPVal, u32 GicPxVal)
This will disable the GIC interrupt.
GicPVal indicates GICP source GicPxVal indicates GICPx source
References XPLMI_GICPX_LEN.
void XPlmi_GicIntrHandler(void *CallbackRef)
This is handler for GIC interrupts.
CallbackRef Not used in the function currently
References XPlmi_GicAddTask, XPLMI_GICP_INDEX_SHIFT, XPLMI_GICP_SOURCE_COUNT, XPLMI_GICPX_INDEX_SHIFT, XPLMI_GICPX_LEN.
void XPlmi_GicIntrAddTask(u32 Index)
This function adds the GiC task handler to the TaskQueue.
Index is the interrupt index with GicPx and its corresponding bit details.
References XPlmi_GetTaskInstance, XPlmi_TaskTriggerNow.
Referenced by XPlmi_GicAddTask.
int XPlmi_ValidateIpiCmd(XPlmi_Cmd *Cmd, u32 SrcIndex)
This function checks whether the Cmd passed is supported via IPI mechanism or not.
Cmd is the pointer to Cmd structure SrcIndex is the source index of IPI command XST_SUCCESS on success.
int XPlmi_IpiPollForAck(u32 DestCpuMask, u32 TimeOutCount)
This function polls for IPI acknowledgment from destination CPU.
DestCpuMask Destination CPU IPI mask TimeOutCount Timeout value XST_SUCCESS on success
int XPlmi_IpiWrite(u32 DestCpuMask, const u32 *MsgPtr, u32 MsgLen, u8 Type)
This function writes an IPI message or a response to destination CPU.
DestCpuMask Destination CPU IPI mask MsgPtr Pointer to message to be written MsgLen IPI message length Type IPI buffer type XST_SUCCESS on success
int XPlmi_IpiTrigger(u32 DestCpuMask)
This function triggers the IPI interrupt to destination CPU.
DestCpuMask Destination CPU IPI mask XST_SUCCESS on success
int XPlmi_IpiRead(u32 SrcCpuMask, u32 *MsgPtr, u32 MsgLen, u8 Type)
This function reads an IPI message or response from source CPU.
SrcCpuMask Source CPU IPI mask MsgPtr IPI read message buffer MsgLen IPI message length Type IPI buffer type XST_SUCCESS on success.
void XPlmi_ModuleRegister(XPlmi_Module *Module)
This function registers the module.
Module is pointer to XPlmi Module
XPlmi_Module* XPlmi_GetModule(u32 ModuleId)
This function returns the Module pointer if registered.
ModuleId Registered ID of the module. Module ptr if module is registered else NULL.
Referenced by XPlmi_CmdExecute.
static void XPlmi_InitPitTimer(u32 Timer, u32 ResetValue)
It initializes the Programmable Interval Timer.
Timer is PIT timer number to be initialized ResetValue is the reset value of timer when started.
static void XPlmi_GetPerfTime(u64 TCur, u64 TStart, u32 IroFreq, XPlmi_PerfTime *PerfTime)
This function prints the total time taken between two points for performance measurement.
TCur is the current time TStart is the start time IroFreq is the frequency at which PMC IRO is running PerfTime is the pointer to variable holding the performance time
u32* XPlmi_GetPmcIroFreq(void)
This function provides the pointer to PmcIroFreq variable.
Pointer to PmcIroFreq variable
Referenced by XPlmi_UtilPollNs.
u64 XPlmi_GetTimerValue(void)
This function is used to read the 64 bit timer value.
It reads from PIT1 and PIT2 and makes it 64 bit.Returns 64 bit timer value
References XPlmi_GetIOModuleInst.
Referenced by XPlmi_DmaXfr, XPlmi_GenericMaskPoll, XPlmi_MeasurePerfTime, XPlmi_SchedulerHandler, XPlmi_SchedulerInit, XPlmi_TaskDispatchLoop, XPlmi_UtilPollNs.
void XPlmi_MeasurePerfTime(u64 TCur, XPlmi_PerfTime *PerfTime)
This function measures the total time taken between two points for performance measurement.
TCur is current time PerfTime is the variable to hold the time elapsed
References XPlmi_GetTimerValue.
Referenced by XPlmi_DmaXfr, XPlmi_GenericMaskPoll, XPlmi_PrintPlmTimeStamp, XPlmi_SchedulerAddTask, XPlmi_TaskDispatchLoop.
void XPlmi_PrintRomTime(void)
This function prints the ROM time.
References XPlmi_GetRomIroFreq.
void XPlmi_PrintPlmTimeStamp(void)
This function prints the PLM time stamp.
References XPlmi_MeasurePerfTime.
Referenced by XPlmi_Print.
int XPlmi_StartTimer(void)
It initializes the IO module structures and PIT timers.
XST_SUCCESS on success.XPLMI_ERR_IOMOD_INIT if IOModdule drive lookup fails.XPLMI_ERR_IOMOD_START if IOModdule drive startup fails.XPLMI_ERR_SET_PMC_IRO_FREQ if failed to set PMC IRO frequency.
References XPLMI_ERR_IOMOD_INIT, XPLMI_ERR_IOMOD_START, XPLMI_ERR_SET_PMC_IRO_FREQ, XPlmi_GetIOModuleInst, XPlmi_IsPlmUpdateDone, XPlmi_SchedulerInit, XPlmi_SetPmcIroFreq.
int XPlmi_SetUpInterruptSystem(void)
This function connects the interrupt handler of the IO Module to the processor.
XST_SUCCESS if handlers are registered properly.XPLMI_ERR_IOMOD_CONNECT if IOModule driver fails to establish connection.
References XPlmi_EnableIomoduleIntr, XPLMI_ERR_IOMOD_CONNECT, XPlmi_GetIOModuleInst, XPlmi_GetTopLevelIntrTbl, XPlmi_GetTopLevelIntrTblSize, XPlmi_IntrHandler, XPLMI_MB_MSR_BIP_MASK, XPlmi_SchedulerHandler.
Referenced by XPlmi_Init.
void XPlmi_IntrHandler(void *CallbackRef)
This function is default interrupt handler for the device.
CallbackRef is presently the interrupt number that is received.
Referenced by XPlmi_SetUpInterruptSystem.
void XPlmi_PlmIntrEnable(u32 IntrId)
This function will enable the Iomodule interrupt.
IntrId Interrupt ID as specified in the xplmi_proc.h
References XPlmi_GetIOModuleInst.
Referenced by XPlmi_ErrorTaskHandler, XPlmi_Versal2Ve2VmEAMHandler.
int XPlmi_PlmIntrDisable(u32 IntrId)
This function will disable the Iomodule interrupt.
IntrId Interrupt ID as specified in the xplmi_proc.h XST_SUCCESS on success and error code on failure
References XPlmi_GetIOModuleInst.
Referenced by XPlmi_ErrIntrHandler, XPlmi_GenericHandler.
int XPlmi_PlmIntrClear(u32 IntrId)
This function will clear the Iomodule interrupt.
IntrId Interrupt ID as specified in the xplmi_proc.h XST_SUCCESS on success and error code on failure
References XPlmi_GetIOModuleInst.
Referenced by XPlmi_ErrorTaskHandler, XPlmi_GenericHandler, XPlmi_IpiIntrHandler, XPlmi_Versal2Ve2VmEAMHandler.
int XPlmi_RegisterHandler(u32 IntrId, GicIntHandler_t Handler, void *Data)
This function will register the handler and enable the Iomodule interrupt.
IntrId Interrupt ID as specified in the xplmi_hw.h Handler to be registered for the interrupt Data to be passed to handler XST_SUCCESS on success.XPLMI_ERR_REGISTER_IOMOD_HANDLER if failed to register the handler.
References XPLMI_ERR_REGISTER_IOMOD_HANDLER, XPlmi_GetIOModuleInst.
static void XPlmi_ResTimeoutHandling(void)
The function decrements AES and SHA timeout and releases resource if timeout has reached.
static u8 XPlmi_IsTaskNonPeriodic(const XPlmi_Scheduler_t *SchedPtr, u32 TaskListIndex)
The function checks the specified task is periodic or not, returns corresponding periodicity status.
SchedPtr is the Scheduler pointer TaskListIndex is the Task index TRUE or FALSE based on the task peridocity status
static u8 XPlmi_IsTaskActive(XPlmi_Scheduler_t *SchedPtr, u32 TaskListIndex)
The function checks the specified task is active or not, returns corresponding status of the task.
SchedPtr is Scheduler pointer TaskListIndex is Task index TRUE or FALSE based on the task active status
void XPlmi_SchedulerInit(void)
The function initializes scheduler and returns the initialization status.
References XPlmi_GetTimerValue.
Referenced by XPlmi_StartTimer.
void XPlmi_SchedulerHandler(void *Data)
The function is scheduler handler and it is called at regular intervals based on configured interval.
Scheduler handler checks and adds the user periodic task to PLM task queue. Data - Not used currently. Added as a part of generic interrupt handler
References XPLMI_ERR_SCHED_TASK_MISSED, XPlmi_GetTimerValue, XPlmi_TaskTriggerNow, XPlmi_UtilRMW, XPlmi_WdtHandler.
Referenced by XPlmi_SetUpInterruptSystem.
int XPlmi_SchedulerAddTask(u32 OwnerId, XPlmi_Callback_t CallbackFn, XPlmi_ErrorFunc_t ErrorFunc, u32 MilliSeconds, TaskPriority_t Priority, void *Data, u8 TaskType)
The function adds user periodic task to scheduler queue.
The user shall call this function to register their scheduler task. OwnerId Id of the owner, used while removing the task. CallbackFn callback function that should be called ErrorFunc error function to be called when task does not execute on scheduled interval MilliSeconds For Periodic tasks, it's the Periodicity of the task. For Non-Periodic tasks, it's the delay after which task has to be scheduled. Value should be in multiples of 10ms Priority is the priority of the task Data is the pointer to the private data of the task TaskType is the type of Task (periodic or non-periodic) XST_SUCCESS if scheduler task is registered properly.XPLMI_ERR_INVALID_TASK_TYPE on invalid task type.XPLMI_ERR_INVALID_TASK_PERIOD on invalid task period.XPLMI_ERR_TASK_EXISTS if task is already present.XPLM_ERR_TASK_CREATE if failed to create the task.
References XPLM_ERR_TASK_CREATE, XPLMI_ERR_INVALID_TASK_PERIOD, XPLMI_ERR_INVALID_TASK_TYPE, XPLMI_ERR_TASK_EXISTS, XPlmi_GetTaskInstance, XPlmi_MeasurePerfTime, XPlmi_TaskCreate.
int XPlmi_SchedulerRemoveTask(u32 OwnerId, XPlmi_Callback_t CallbackFn, u32 MilliSeconds, const void *Data)
The function removes scheduler task from scheduler queue.
The function called by the user for deregistering the scheduler task. OwnerId Id of the owner, removed only if matches the ownerid while adding the task. CallbackFn callback function that is given while adding. MilliSeconds Periodicity of the task given while adding. Data is the pointer to the private data of the task XST_SUCCESS on success and error code on failure
static void XPlmi_WriteSysmonCtrlReg(u32 Addr, u32 Value)
This function writes given configuration to Sysmon Ctrl register.
Addr is the address of Sysmon Mask register Value is the configuration to be written to Control register
XSysMonPsv* XPlmi_GetSysmonInst(void)
This function provides address of Sysmon Instance.
Address of SysmonInst
Referenced by XPlmi_SysMonInit.
int XPlmi_SysMonInit(void)
This function initializes the SysMon.
XST_SUCCESS on success and error code on failure
References XPlmi_GetSysmonInst, XPLMI_SYSMON_PCSR_CTRL_SLVERREN_MASK, XPLMI_SYSMON_SAT0_PCSR_MASK_OFFSET, XPLMI_SYSMON_SAT1_PCSR_MASK_OFFSET.
void XPlmi_SysMonOTDetect(u32 WaitInMSecVal)
This function detects if we are still in over-temperature condition.
WaitInMSecVal is the time in milliseconds for which the firmware must wait before proceeding after over temperature event clears up
References XPlmi_SetPlmLiveStatus.
Referenced by XPlmi_EmInit.
static void XPlmi_PmcApbErrorHandler(const u32 ErrorNodeId, const u32 ErrorMask)
This is the handler for tamper interrupt.
ErrorNodeId - Node Identifier ErrorMask - Mask Identifier
static int XPlmi_ProcessTamperResponse(void *Data)
This function processes the tamper response.
Data is unused No status return, waits forever for ROM to complete secure lockdown.
u32 XPlmi_SldState(void)
This function returns Secure Lockdown State.
Secure Lockdown State
Referenced by XPlmi_ProcessCdo, XPlmi_TriggerTamperResponse.
void XPlmi_TriggerTamperResponse(u32 Response, u32 Flag)
This functions Triggers Tamper Response processing immediately or as a task.
Response is the Tamper Response that has to occur Flag denotes whether processing has to occur immediately or as a task. The possible values are: XPLMI_TRIGGER_TAMPER_TASK, XPLMI_TRIGGER_TAMPER_IMMEDIATE.
References XPlmi_NotifySldSlaveSlrs, XPLMI_SLD_NOT_TRIGGERED, XPLMI_SLD_TRIGGERED, XPlmi_SldState, XPlmi_TaskTriggerNow, XPLMI_TRIGGER_TAMPER_TASK.
Referenced by XPlmi_TriggerSLDOnHaltBoot.
int XPlmi_RegisterTamperIntrHandler(void)
This function registers the handler for tamper interrupt.
XST_SUCCESS - On successXPLMI_INVALID_ERROR_ID - On invalid IDXPLMI_INVALID_ERROR_HANDLER - On Null handler
References XPLM_ERR_TASK_CREATE, XPlmi_EmSetAction, XPlmi_GetTaskInstance, XPlmi_TaskCreate.
Referenced by XPlmi_EmInit.
void XPlmi_TriggerSLDOnHaltBoot(u32 Flag)
This function triggers secure lockdown if haltboot efuses are programmed.
Flag denotes whether processing has to occur immediately or as a task. The possible values are: XPLMI_TRIGGER_TAMPER_TASK, XPLMI_TRIGGER_TAMPER_IMMEDIATE.
References XPlmi_TriggerTamperResponse.
XPlmi_TaskNode* XPlmi_TaskCreate(TaskPriority_t Priority, int(*Handler)(void *Arg), void *PrivData)
This function creates the task and initializes its fields with the user parameters.
Priority Priority of the task Handler function pointer to the task handler PrivData Private Data to be passed with task handler Pointer to the task node structure
References XPlmi_GetTaskInstance.
Referenced by XPlmi_AsuUpdateInit, XPlmi_EmInit, XPlmi_GicRegisterHandler, XPlmi_RegisterTamperIntrHandler, XPlmi_SchedulerAddTask, XPlmi_UpdateInit.
XPlmi_TaskNode* XPlmi_GetTaskInstance(int(*Handler)(void *Arg), const void *PrivData, const u32 IntrId)
This function returns the instance of the task with matching handler and private data or with matching interrupt id.
Handler is pointer to the task handler PrivData is argument to be passed to the task handler IntrId is the interrupt id associated with the task Instance of the task in case of a match, NULL otherwise
Referenced by XPlmi_AsuUpdate, XPlmi_EmInit, XPlmi_ErrIntrHandler, XPlmi_GicIntrAddTask, XPlmi_IpiIntrHandler, XPlmi_PlmUpdate, XPlmi_RegisterTamperIntrHandler, XPlmi_SchedulerAddTask, XPlmi_TaskCreate.
void XPlmi_TaskTriggerNow(XPlmi_TaskNode *Task)
This function adds the task to the task queue so that it can be triggered based on its priority.
Task Pointer to the task node
Referenced by XPlmi_AsuUpdate, XPlmi_ErrIntrHandler, XPlmi_GicIntrAddTask, XPlmi_IpiIntrHandler, XPlmi_PlmUpdate, XPlmi_SchedulerHandler, XPlmi_TriggerTamperResponse.
void XPlmi_TaskInit(void)
This function initializes the task queues list.
void XPlmi_TaskDispatchLoop(void)
This function will be checking for tasks in the queue based on the priority.
After calling every task handlers, next high priority task will be called.
References XPlmi_ErrMgr, XPlmi_GetTimerValue, XPlmi_MeasurePerfTime, XPlmi_SetPlmLiveStatus.
void XPlmi_UtilRMW(u32 RegAddr, u32 Mask, u32 Value)
This function will Read, Modify and Write to a register.
RegAddr is the address of the register Mask denotes the bits to be modified Value is the value to be written to the register
Referenced by XPlmi_ClearNpiErrors, XPlmi_DisableCFrameIso, XPlmi_ErrMgr, XPlmi_ListMaskWrite, XPlmi_LogPlmErr, XPlmi_LpdInit, XPlmi_PORHandler, XPlmi_SaveLpdEAMInfo, XPlmi_SchedulerHandler, XPlmi_SetDDRMCMainRegSts, XPlmi_SsitSyncMaster, XPlmi_SysmonClkSetIro, XPlmi_TriggerFwNcrError, XPlmi_UpdateCryptoStatus, XPlmi_UpdateKatStatus.
int XPlmi_UtilPoll(u32 RegAddr, u32 Mask, u32 ExpectedValue, u32 TimeOutInUs, void(*ClearHandler)(void))
This function polls a register till the masked bits are set to expected value or till timeout occurs.
RegAddr is the address of the register Mask denotes the bits to be modified ExpectedValue is the value for which the register is polled TimeOutInUs is the max time in microseconds for which the register would be polled for the expected value ClearHandler is the handler to clear the latched values if required before reading them XST_SUCCESS on success and error code on failure
References XPlmi_SetPlmLiveStatus.
Referenced by XPlmi_GenericMaskPoll, XPlmi_InterSlrSldHandshake.
int XPlmi_UtilPoll64(u64 RegAddr, u32 Mask, u32 ExpectedValue, u32 TimeOutInUs)
This function polls a 64 bit address till the masked bits are set to expected value or till timeout occurs.
RegAddr 64 bit address Mask is the bit field to be polled ExpectedValue is value to be polled TimeOutInUs is delay time in micro sec XST_SUCCESS on success and error code on failure
References XPlmi_SetPlmLiveStatus.
Referenced by XPlmi_GenericMaskPoll.
int XPlmi_UtilPollForMask(u32 RegAddr, u32 Mask, u32 TimeOutInUs)
This function polls a 64 bit register till the masked bits are set to expected value or till timeout occurs.
RegAddr is the register address Mask is the bit field to be updated TimeOutInUs is delay time in micro sec XST_SUCCESS on success and error code on failure
References XPlmi_SetPlmLiveStatus.
Referenced by XPlmi_InterSlrSldHandshake.
int XPlmi_UtilPollForMask64(u32 HighAddr, u32 LowAddr, u32 Mask, u32 TimeOutInUs)
This function polls a 64 bit register till the masked bits are set to expected value or till timeout occurs.
HighAddr is higher 32-bits of 64-bit address LowAddr is lower 32-bits of 64-bit address Mask is the bit field to be updated TimeOutInUs is delay time in micro sec XST_SUCCESS on success and error code on failure
References XPlmi_SetPlmLiveStatus.
void XPlmi_UtilWrite64(u32 HighAddr, u32 LowAddr, u32 Value)
This function writes to a 64 bit address.
HighAddr is higher 32-bits of 64-bit address LowAddr is lower 32-bits of 64-bit address Value is value to be updated
void XPlmi_PrintArray(u16 DebugType, const u64 BufAddr, u32 Len, const char *Str)
This function is used to print the entire array in bytes as specified by the debug type.
DebugType printing of the array will happen as defined by the debug type BufAddr pointer to the buffer to be printed Len length of the bytes to be printed Str pointer to the data that is printed along the data
References XPLMI_WORD_LEN.
int XPlmi_UtilPollNs(u32 RegAddr, u32 Mask, u32 ExpectedValue, u64 TimeOutInNs, void(*ClearHandler)(void))
This function polls a register till the masked bits are set to expected value or till timeout occurs.
The timeout is specified in nanoseconds. Also provides a clearhandler to clear the latched values before reading them. RegAddr is the address of the register Mask denotes the bits to be modified ExpectedValue is the value for which the register is polled TimeOutInNs is the max time in nanoseconds for which the register would be polled for the expected value ClearHandler is the handler to clear the latched values if required before reading them XST_SUCCESS on success and XST_FAILURE on failure
References XPlmi_GetPmcIroFreq, XPlmi_GetTimerValue.
Referenced by XPlmi_InterSlrSldHandshake.
void XPlmi_StoreMultiboot(void)
This is a placeholder function used in case the feature is disabled.
void XPlmi_RestoreMultiboot(void)
This is a placeholder function used in case the feature is disabled.
void XPlmi_ClearMultiboot(void)
This is a placeholder function used in case the feature is disabled.
static void XPlmi_CpmErrHandler(u32 ErrorNodeId, u32 RegMask)
This function handles the CPM_NCR error.
ErrorNodeId is the node ID for the error event RegMask is the register mask of the error received
static void XPlmi_XppuErrHandler(u32 BaseAddr, const char *ProtUnitStr)
This function handles the XPPU errors.
BaseAddr is the base address of the XPPU ProtUnitStr is string prefix to be used while printing event info
static void XPlmi_XmpuErrHandler(u32 BaseAddr, const char *ProtUnitStr)
This function handles the XMPU errors.
BaseAddr is the base address of the XMPU ProtUnitStr is string prefix to be used while printing event info
XPlmi_Error_t * XPlmi_GetErrorTable(void)
This function provides error table pointer.
Pointer to Error Table Pointer to Error Table
Referenced by XPlmi_EmClearError, XPlmi_EmConfig, XPlmi_EmGetAction, XPlmi_EmInit, XPlmi_EmSetAction, XPlmi_ErrorTaskHandler, XPlmi_ErrPSMIntrHandler, XPlmi_HandleSwError, XPlmi_LpdSlcrEmInit, XPlmi_PsEmInit, XPlmi_TriggerFwNcrError, XPlmi_UpdateErrorSubsystemId, XPlmi_Versal2Ve2VmEAMHandler.
u32 * XPlmi_GetPsmCrState(void)
This function provides IsPsmChanged variable.
Pointer to IsPsmCrChanged Pointer to IsPsmCrChanged.
u8 XPlmi_GetEventIndex(XPlmi_EventType ErrorNodeType)
This function provides event index.
ErrorNodeType is the Node Type of the EAM register Event Index ErrorNodeType is the Node Type of the EAM register. Event Index.
Referenced by XPlmi_EmClearError, XPlmi_EmDisable, XPlmi_Versal2Ve2VmSetAction.
void XPlmi_SysmonClkSetIro(void)
This function sets the sysmon clock to IRO for ES1 silicon.
References XPLMI_SYSMON_CLK_SRC_IRO_VAL, XPlmi_UtilRMW.
Referenced by XPlmi_PORHandler, XPlmi_SoftResetHandler, XPlmi_TriggerFwNcrError.
void XPlmi_HandleLinkDownError(u32 Cpm5PcieIrStatusReg, u32 Cpm5DmaCsrIntDecReg, u32 ProcId)
This function handles the CPM_NCR PCIE link down error.
This function handles the PCIE link down error. Cpm5PcieIrStatusReg is the PCIE0/1 IR status register address Cpm5DmaCsrIntDecReg is the DMA0/1 CSR INT DEC register address ProcId is the ProcId for PCIE0/1 link down error DeviceIrStatusReg is the PCIE0/1 Device IR status register address GenralStsReg is the PCIE0/1 General status register address ProcId is the ProcId for PCIE0/1 link down error Cpm5PcieIrStatusReg is the PCIE0/1 IR status register address. Cpm5DmaCsrIntDecReg is the DMA0/1 CSR INT DEC register address. ProcId is the ProcId for PCIE0/1 link down error.
References XPlmi_ErrMgr, XPlmi_ExecuteProc.
void XPlmi_ErrPrintToLog(u32 ErrorNodeId, u32 RegMask)
This function is the interrupt handler for Error action "Print to Log".
This function prints detailed information if the error is due to XMPU/XPPU protection units. ErrorNodeId is the node ID for the error event RegMask is the register mask of the error received This function prints detailed information if the error is due to XMPU/XPPU protection units. ErrorNodeId is the node ID for the error event RegMask is the register mask of the error received None This function prints detailed information if the error is due to XMPU/XPPU protection units. ErrorNodeId is the node ID for the error event. RegMask is the register mask of the error received.
References XPlmi_GetErrorId.
Referenced by XPlmi_EmConfig.
void XPlmi_DumpErrNGicStatus(void)
This function dumps EAM Error status registers and Gic Status registers.
None
void XPlmi_ClearSsitErrors(u32 *PmcErrStatus, u32 Index)
This function clears Ssit errors for ES1 silicon.
PmcErrStatus is the pointer to the error status array Index is the PMC Error register Index PmcErrStatus is the pointer to the error status array. Index is the PMC Error register Index.
References XPLMI_PMC_ERR_SSIT_MASK.
Referenced by XPlmi_EmInit.
u32 * XPlmi_GetNumErrOuts(void)
This function provides pointer to NumErrOuts.
Pointer to NumErrOuts Pointer to NumErrOuts.
Referenced by XPlmi_UpdateNumErrOutsCount.
int XPlmi_RestrictErrActions(XPlmi_EventType NodeType, u32 RegMask, u32 ErrorAction)
This function restricts error actions.
NodeType of Error RegMask of Error ErrorAction of the the Error XST_SUCCESS on success and error code on failure NodeType of Error RegMask of Error ErrorAction of the the Error XST_SUCCESS if success.XPLMI_INVALID_ERROR_ACTION on invalid error action. NodeType of Error. RegMask of Error. ErrorAction of the the Error. XST_SUCCESS on success.Error code on failure.
Referenced by XPlmi_Versal2Ve2VmSetAction.
static int XPlmi_UpdateResetReason(void)
This function updates reset reason.
XST_SUCCESS on success and error code on failure
static int XPlmi_SsitWaitForDmaDone(XPmcDma *DmaPtr, XPmcDma_Channel Channel)
This function is used to check and wait for DMA done when sending data to SSIT Slave SLRs.
DmaPtr is pointer to DMA structure Channel is DMA source or destination channel XST_SUCCESS on success.XPLMI_ERR_FROM_SSIT_SLAVE if error received from slave SLR.
void XPlmi_SetXRamAvailable(void)
Flag to indicate XRAM is available.
This function sets XRAM Available FlagThis function sets XRAM Available Flag.
XInterruptHandler * XPlmi_GetTopLevelIntrTbl(void)
This function provides pointer to g_TopLevelInterruptTable.
Pointer to g_TopLevelInterruptTable structure Pointer to g_TopLevelInterruptTable structure.
Referenced by XPlmi_SetUpInterruptSystem.
u8 XPlmi_GetTopLevelIntrTblSize(void)
This function provides size of g_TopLevelInterruptTable.
Size g_TopLevelInterruptTable structure Size g_TopLevelInterruptTable structure.
Referenced by XPlmi_SetUpInterruptSystem.
XPlmi_BoardParams* XPlmi_GetBoardParams(void)
This function provides pointer to BoardParams.
Pointer to BoardParams Pointer to BoardParams.
References EXPORT_GENERIC_DS, XPLMI_BOARD_PARAMS_DS_ID, XPLMI_BOARD_PARAMS_LCVERSION, XPLMI_BOARD_PARAMS_VERSION.
XIOModule * XPlmi_GetIOModuleInst(void)
This function provides pointer to IOModule structure.
Pointer to XIOModule Pointer to XIOModule.
Referenced by XPlmi_GetTimerValue, XPlmi_PlmIntrClear, XPlmi_PlmIntrDisable, XPlmi_PlmIntrEnable, XPlmi_RegisterHandler, XPlmi_SetUpInterruptSystem, XPlmi_StartTimer.
u32 * XPlmi_GetUartBaseAddr(void)
This function provides LpdInitialized variable pointer.
This function provides a pointer to the UART base address variable.Pointer to LpdInitialized variable Pointer to LpdInitialized variable. Pointer to the static UartBaseAddr variable that stores the UART base address (initialized to XPLMI_INVALID_UART_BASE_ADDR)
Referenced by outbyte, XPlmi_ConfigUart, XPlmi_InitUart.
u32 * XPlmi_GetLpdInitialized(void)
This function provides LpdInitialized variable pointer.
Pointer to LpdInitialized variable Pointer to LpdInitialized variable.
Referenced by XPlmi_ResetLpdInitialized, XPlmi_SetLpdInitialized, XPlmi_UnSetLpdInitialized.
void XPlmi_RtcaPlatInit(void)
This function performs initialization of platform specific RCTA registers.
Referenced by XPlmi_RunTimeConfigInit.
void XPlmi_PrintRomVersion(void)
This function prints ROM version using ROM digest value.
Referenced by XPlmi_PrintPlmBanner.
int XPlmi_PreInit(void)
This function performs plmi pre-initializaton.
Reset reason status. XST_SUCCESS always.
Referenced by XPlmi_Init.
void XPlmi_SssMask(u32 DmaSrc)
This function masks the secure stream switch value.
DmaSrc - DMA0 or DMA1 DmaSrc DMA0 or DMA1.
XPlmi_WaitForDmaDone_t XPlmi_GetPlmiWaitForDone(u64 DestAddr)
This function is used to check and wait for DMA done when sending data to SSIT Slave SLRs.
This function is used to check and wait for DMA done. DestAddr holds the address of the destination buffer XST_SUCCESS on success and error code on failure DestAddr is the address of destination XST_SUCCESS on success and error code on failure DestAddr holds the address of the destination buffer. XST_SUCCESS on success.Error code on failure.
Referenced by XPlmi_DmaXfr.
XPlmi_CircularBuffer * XPlmi_GetTraceLogInst(void)
This function provides TraceLog instance.
Pointer to TraceLog variable Pointer to TraceLog variable.
Referenced by XPlmi_EventLogging.
void XPlmi_GetReadbackSrcDest(u32 SlrType, u64 *SrcAddr, u64 *DestAddrRead)
This function processes and provides SrcAddr and DestAddr for cfi readback.
SlrType is the type of Slr passed in readback cmd SrcAddr is the pointer to the SrcAddr variable DestAddrRead is the pointer to the DestAddrRead variable SlrType is the type of Slr passed in readback cmd. SrcAddr is the pointer to the SrcAddr variable. DestAddrRead is the pointer to the DestAddrRead variable.
References XPLMI_SLR1_CFU_FDRO_2_ADDR, XPLMI_SLR1_CFU_STREAM_2_ADDR, XPLMI_SLR2_CFU_FDRO_2_ADDR, XPLMI_SLR2_CFU_STREAM_2_ADDR, XPLMI_SLR3_CFU_FDRO_2_ADDR, XPLMI_SLR3_CFU_STREAM_2_ADDR.
void XPlmi_GicAddTask(u32 PlmIntrId)
This will add the GIC interrupt task handler to the TaskQueue.
PlmIntrId is the GIC interrupt ID of the task PlmIntrId is the GIC interrupt ID of the task.
References XPlmi_GetIpiIntrId, XPlmi_GicIntrAddTask.
Referenced by XPlmi_GicIntrHandler.
int XPlmi_RegisterNEnableIpi(void)
This function registers and enables IPI interrupt.
XST_SUCCESS on success and XST_FAILURE on failure XST_SUCCESS on success and XST_FAILURE on failure XST_SUCCESS on success.XST_FAILURE on failure.
void XPlmi_EnableIomoduleIntr(void)
This function registers and enables IPI interrupt.
Referenced by XPlmi_SetUpInterruptSystem.
int XPlmi_SetPmcIroFreq(void)
It sets the PMC IRO frequency.
This functions sets the PMC IRO frequency. XST_SUCCESS on success and error code failure - XST_SUCCESS on success XST_FAILURE on failure XST_SUCCESS on success.Error code failure.
Referenced by XPlmi_StartTimer.
int XPlmi_GetPitResetValues(u32 *Pit1ResetValue, u32 *Pit2ResetValue)
This functions provides the PIT1 and PIT2 reset values.
Pit1ResetValue is the pointer to store the PIT1 reset value. Pit2ResetValue is the pointer to store the PIT12 reset value. XST_SUCCESS always.
u32 XPlmi_GetGicIntrId(u32 GicPVal, u32 GicPxVal)
This function provides Gic interrupt id.
GicPVal indicates GICP source GicPxVal indicates GICPx source Gic Interrupt Id GicPVal indicates GICP source GicPxVal indicates GICPx source Readback length GicPVal indicates GICP source. GicPxVal indicates GICPx source. Gic Interrupt Id.
Referenced by XPlmi_GicRegisterHandler.
u32 XPlmi_GetIpiIntrId(u32 BufferIndex)
This function provides IPI interrupt id.
BufferIndex is the Ipi target buffer index IPI interrupt id BufferIndex is the Ipi target buffer index. IPI interrupt id.
Referenced by XPlmi_GicAddTask, XPlmi_IpiIntrHandler.
void XPlmi_EnableIpiIntr(void)
This function enables IPI interrupt.
void XPlmi_ClearIpiIntr(void)
This function clears IPI interrupt.
void XPlmi_DisableCFrameIso(void)
This function Disables CFRAME Isolation.
References XPlmi_UtilRMW.
void XPlmi_GetBootKatStatus(volatile u32 *PlmKatStatus)
This function returns KAT status from RCTA area.
This function sets KAT status from RTC area. PlmKatStatus is the pointer to the variable which holds kat status PlmKatStatus is the pointer to the variable which holds kat status.
XPlmi_BufferList* XPlmi_GetBufferList(u32 BufferListType)
This function defines BufferList and returns the address of the same.
BufferListType is the proc list type if it is stored in PMC or PSM RAM BufferList is the address of BufferList structure BufferListType is the proc list type if it is stored in PMC or PPU RAM BufferList is the address of BufferList structure BufferListType is the proc list type if it is stored in PMC or PSM RAM. BufferList is the address of BufferList structure.
References EXPORT_GENERIC_DS, XPLMI_MAX_PMC_BUFFERS, XPLMI_PMC_BUFFER_DS_ID, XPLMI_PMC_BUFFER_DS_LCVER, XPLMI_PMC_BUFFER_DS_VER, XPLMI_PMC_BUFFER_LIST_DS_ID, XPLMI_PMC_BUFFER_LIST_DS_LCVER, XPLMI_PMC_BUFFER_LIST_DS_VER, XPLMI_PPU_BUFFER_DS_ID, XPLMI_PPU_BUFFER_DS_LCVER, XPLMI_PPU_BUFFER_DS_VER, XPLMI_PPU_BUFFER_LIST_DS_ID, XPLMI_PPU_BUFFER_LIST_DS_LCVER, XPLMI_PPU_BUFFER_LIST_DS_VER.
Referenced by XPlmi_ExecuteProc, XPlmi_PsmSequence, XPlmi_SetBufferList.
static u32 XPlmi_SsitGetSlaveErrorMask(void)
This function checks which Slave SLR this code is running on and returns corresponding SSIT mask of PMC GLOBAL PMC_ERROR2_STATUS register.
return 0 if error occurred. Else return one of the ERR_MASK.
u8 XPlmi_GetSlrIndex(void)
This function is used to get the local SLR index.
Returns Local SLR index
u32 XPlmi_GetSlavesSlrMask(void)
This function is used to get the combined mask of all slave SLRs.
Returns combined mask of all slave SLRs
int XPlmi_SsitRegisterEvent(u32 EventIndex, XPlmi_EventHandler_t Handler, u8 EventOrigin)
This function is used to register any event between Master and Slave SLRs.
EventIndex is the Index of the event to be registered Handler is the handler to be executed when this Event occurs EventOrigin is the SLR origin which can trigger the event Returns XST_SUCCESS for non-SSIT designs
int XPlmi_SsitWriteEventBufferAndTriggerMsgEvent(u8 SlrIndex, u32 *ReqBuf, u32 ReqBufSize)
This function is used to write the event buffer data and trigger the Message Event.
SlrIndex is the index of the SLR to which the event buffer need to be written ReqBuf is the buffer from where the event buffer data to be written to Slave SLRs event buffer ReqBufSize is the size of the ReqBuf Returns XST_SUCCESS for non-SSIT designs
int XPlmi_SsitReadEventBuffer(u32 *ReqBuf, u32 ReqBufSize)
This function is used to read the event buffer of Master SLR in Slave SLRs where the message event is received.
ReqBuf is the buffer to which the event buffer data to be written ReqBufSize is the size of the ReqBuf Returns XST_SUCCESS for non-SSIT designs
int XPlmi_SsitTriggerEvent(u8 SlrIndex, u32 EventIndex)
This function is used to trigger the given event to the given SLR.
SlrIndex is the index of the SLR to which the event to be triggered EventIndex is the Index of the event to be triggered Returns XST_SUCCESS for non-SSIT designs
int XPlmi_SsitWaitForEvent(u8 SlrIndex, u32 EventIndex, u32 TimeOut)
This function is used to wait for the event to be acknowledged by the given SLR after triggering.
SlrIndex is the SLR index where the event is triggered EventIndex is the Index of the event triggered TimeOut is the timeout in us to wait for the acknowledgment Returns XST_SUCCESS for non-SSIT designs
int XPlmi_SsitReadResponse(u8 SlrIndex, u32 *RespBuf, u32 RespBufSize)
This function is used to read the response (if applicable) in Master SLR once the event is acknowledged by Slave SLR.
SlrIndex is the SLR index from the response need to be read RespBuf is the Response Buffer to where the response to be written RespBufSize is the size of the response buffer Returns XST_SUCCESS for non-SSIT designs
int XPlmi_SsitWriteResponseAndAckMsgEvent(u32 *RespBuf, u32 RespBufSize)
This function is used to write the response (if applicable) in Slave SLR once the event is handled and acknowledge the message event.
RespBuf is the Response Buffer data to be written RespBufSize is the size of the response buffer Returns XST_SUCCESS for non-SSIT designs
int XPlmi_SsitAcknowledgeEvent(u8 SlrIndex, u32 EventIndex)
This function is used to acknowledge the event after handling.
SlrIndex is index of the SLR for which the event was triggered EventIndex is the event to acknowledge Returns XST_SUCCESS for non-SSIT designs
u64 XPlmi_SsitGetSlrAddr(u32 Address, u8 SlrIndex)
This function is used to get the global SLR address for the given local address.
Address is the local address for which the global SLR address need to be calculated SlrIndex is the index of the SLR for which the address need to be calculated Returns 0x0 for non-SSIT designs
int XPlmi_SsitSendMsgEventAndGetResp(u8 SlrIndex, u32 *ReqBuf, u32 ReqBufSize, u32 *RespBuf, u32 RespBufSize, u32 WaitForEventCompletion)
This function sends a message event with given request buffer to a slave SLR, waits for event completion, reads the response from the slave SLR and returns it to the caller.
SlrIndex is the SLR index from which the response need to be read ReqBuf is the buffer to which the event buffer data to be written ReqBufSize is the size of the ReqBuf RespBuf is the Response Buffer to where the response to be written RespBufSize is the size of the response buffer WaitForEventCompletion is the maximum time to wait before the requested message event is handled by a slave SLR [in microseconds] Returns XST_SUCCESS for non-SSIT designs
Referenced by XPlmi_SendIpiCmdToSlaveSlr, XPlmi_SsitCfgSecComm.
int XPlmi_SsitSyncMaster(XPlmi_Cmd *Cmd)
This function provides SSIT Sync Master command execution.
Cmd is pointer to the command structure Returns the Status of SSIT Sync Master command
References XPLMI_SSIT_SYNC_MASTER_CMD_ID, XPlmi_UtilRMW.
int XPlmi_SsitSyncSlaves(XPlmi_Cmd *Cmd)
This function provides SSIT Sync Slaves command execution.
Command payload parameters are * Slaves Mask * Timeout Cmd is pointer to the command structure Returns the Status of SSIT Sync Slaves commandXPLMI_ERR_SSIT_SLAVE_SYNC if master timedout on slave sync.
References XPLMI_ERR_SSIT_SLAVE_SYNC, XPlmi_SetPlmLiveStatus, XPLMI_SSIT_SYNC_SLAVES_CMD_ID.
int XPlmi_SsitWaitSlaves(XPlmi_Cmd *Cmd)
This function provides SSIT Wait Slaves command execution.
Command payload parameters are * Slaves Mask * Timeout Cmd is pointer to the command structure Returns the Status of SSIT Wait Slaves commandXPLMI_ERR_SSIT_SLAVE_SYNC if master timedout on slave sync.
References XPLMI_ERR_SSIT_SLAVE_SYNC, XPlmi_SetPlmLiveStatus, XPLMI_SSIT_WAIT_SLAVES_CMD_ID.
int XPlmi_SendIpiCmdToSlaveSlr(u32 *Payload, u32 *RespBuf)
This function handles invalid commands.
Payload holds the inputs of the slaves RespBuf Stores the response of the slaves XST_SUCCESS on success.XPLMI_ERR_CMD_APIID on unregistered command ID.XPLMI_SSIT_INTR_NOT_ENABLED if interrupts are not enabled.
References XPLMI_ERR_CMD_APIID, XPLMI_SLR_INDEX_SHIFT, XPLMI_SSIT_INTR_NOT_ENABLED, XPLMI_SSIT_MONOLITIC, XPlmi_SsitSendMsgEventAndGetResp.
void XPlmi_NotifySldSlaveSlrs(void)
This function notifies other SLRs about Secure Lockdown or tamper condition in SSIT devices.
References XPLMI_SSIT_MASTER_SLR, XPLMI_SSIT_MONOLITIC.
Referenced by XPlmi_TriggerTamperResponse.
void XPlmi_InterSlrSldHandshake(void)
This function performs handshake between SLRs on SSIT ERR lines.
This has to be done on SSIT devices before doing secure lockdown
References XPLMI_SSIT_MASTER_SLR, XPLMI_SSIT_MONOLITIC, XPlmi_UtilPoll, XPlmi_UtilPollForMask, XPlmi_UtilPollNs.
int XPlmi_SsitCfgSecComm(XPlmi_Cmd *Cmd)
This function provides SSIT config secure communication command execution.
Command payload parameters are * SLR number, base address of buffer which consists of IV1,IV2,Key in master * IV1(128-bit), IV2(128-bit) and Key(256-bit) in slave Cmd is pointer to the command structure XST_SUCCESS If command is successfulXST_FAILURE If there is failure
References XPLMI_ERR_INVALID_ADDR_RANGE, XPLMI_EVENT_NOT_SUPPORTED_FROM_SLR, XPLMI_INVALID_SLR_TYPE, XPLMI_KEY_SIZE_BYTES, XPLMI_SSIT_MASTER_SLR, XPLMI_SSIT_MONOLITIC, XPlmi_SsitSendMsgEventAndGetResp, XPLMI_VERIFY_ADDR_RANGE.
int XPlmi_GetSsitSecCommStatus(XPlmi_Cmd *Cmd)
This function gives SSIT secure communication status Command payload parameters are.
* SLR index for which secure communication status is requested Cmd is pointer to the command structure Returns the Status of get secure communication status command
References XPLMI_EVENT_NOT_SUPPORTED_FROM_SLR, XPLMI_INVALID_SLR_TYPE, XPLMI_SSIT_MASTER_SLR, XPLMI_SSIT_MONOLITIC.
int XPlmi_EnableWdt(u32 NodeId, u32 Periodicity)
This function enables the WDT and sets NodeId and periodicity.
It also verifies the parameters. NodeId NodeId is the MIO node to be used by PLM for toggling. Periodicity at which MIO value should be toggled. XST_SUCCESS if success.XPLMI_ERR_WDT_PERIODICITY on invalid Periodicity.XPLMI_ERR_WDT_LPD_NOT_INITIALIZED if LPD is not initialized.XPLMI_ERR_WDT_NODE_ID on invalid node ID. It also verifies the parameters. NodeId NodeId is the MIO node to be used by PLM for toggling. Periodicity at which MIO value should be toggled. XST_SUCCESS if success.XPLMI_ERR_WDT_PERIODICITY on invalid Periodicity.XPLMI_ERR_WDT_LPD_NOT_INITIALIZED if LPD is not initialized.XPLMI_ERR_WDT_NODE_ID on invalid node ID. NodeId NodeId is the MIO node to be used by PLM for toggling. Periodicity at which MIO value should be toggled. XST_SUCCESS if success.XPLMI_ERR_WDT_PERIODICITY on invalid Periodicity.XPLMI_ERR_PMC_WDT_NOT_ENABLED if PMC WDT is tried use and it is not enabled in design.XPLMI_ERR_PMC_WDT_DRV_INIT if PMC WDT driver initialization fails.XPLMI_ERR_WDT_LPD_NOT_INITIALIZED if LPD is not initialized.XPLMI_ERR_WDT_NODE_ID on invalid node ID.
References LPD_WDT_INITIALIZED, XPLMI_ERR_WDT_LPD_NOT_INITIALIZED, XPLMI_ERR_WDT_NODE_ID, XPLMI_ERR_WDT_PERIODICITY, XPLMI_MIO_NUM_PER_BANK, XPLMI_PM_STMIC_LMIO_0, XPLMI_PM_STMIC_LMIO_25, XPLMI_PM_STMIC_PMIO_0, XPLMI_PM_STMIC_PMIO_51, XPlmi_SetLpdInitialized, XPLMI_WDT_PERIODICITY_MAX, XPLMI_WDT_PERIODICITY_MIN.
Referenced by XPlmi_DefaultSWdtConfig.
void XPlmi_DisableWdt(u32 NodeId)
This function disables the WDT.
This is required when LPD is powered down and if LPD MIO is used. Also required when debugging. NodeId is not applicable for versal platform. This is required when LPD is powered down and if LPD MIO is used. Also required when debugging. NodeId is the Node ID of external WDT or internal PMC WDT
Referenced by XPlmi_ResetLpdInitialized.
void XPlmi_SetPlmLiveStatus(void)
This function Sets the PLM Status.
Referenced by XPlmi_ErrMgr, XPlmi_Init, XPlmi_ProcessCdo, XPlmi_SsitSyncSlaves, XPlmi_SsitWaitSlaves, XPlmi_SysMonOTDetect, XPlmi_TaskDispatchLoop, XPlmi_UtilPoll, XPlmi_UtilPoll64, XPlmi_UtilPollForMask, XPlmi_UtilPollForMask64.
void XPlmi_ClearPlmLiveStatus(void)
This function clears the PLM status.
void XPlmi_WdtHandler(void)
This function is handler for WDT.
Scheduler calls this function periodically to check the PLM Live status and to toggle the MIO.
References XPLMI_SCHEDULER_PERIOD, XPLMI_WDT_PERIODICITY_MIN.
Referenced by XPlmi_SchedulerHandler.
void XPlmi_AsuModuleInit(int(*const GeneratePufKEK)(u8 *PufRegenStatusFlag), int(*const InitiateKeyXfer)(void), int(*const GetAsuCdiSeed)(u32 CdiAddr), int(*const GetSubsysDigest)(u32 SubsystemId, u32 SubsysHashAddrPtr), void(*const GetOcpEventMask)(u32 *EventMask))
static int XPlmi_AsuUpdateTask(void *Arg)
This function is the task handler for ASU in-place update.
It polls for ASU shutdown completion, loads the new firmware image, resets ASU, and waits for the new firmware to initialize. Arg is unused parameter. XST_SUCCESS if ASU update completed successfully.XPLMI_ERR_ASU_SHUTDOWN_TIMEOUT if ASU shutdown exceeds 60 seconds.XPLMI_ERR_ASU_FW_NOT_RUNNING if ASU firmware fails to restart after update.Error code from XLoader_LoadAsu() if firmware loading fails.
u32 XPlmi_GetAsuUpdatePdiAddr(void)
This function gets UpdateAsuPdiAddr variable value.
UpdateAsuPdiAddr value.
u8 XPlmi_AsuFwIsPresent(void)
This function checks if ASU firmware is present and running.
TRUE if ASU firmware is present (FW_IS_PRESENT bit set).FALSE if ASU firmware is not running.
References XPLMI_ASU_RTCA_EXEC_STATUS, XPLMI_ASU_RTCA_FW_IS_PRESENT_MASK.
Referenced by XPlmi_AsuUpdate.
int XPlmi_AsuUpdateInit(XPlmi_IsPdiAddrLookup_t IsPdiAddrLookupHandler, XPlmi_CheckAsuPresenceInPdi_t CheckAsuPresenceHandler, XPlmi_LoadAsuImage_t LoadAsuImageHandler)
This function initializes ASU in-place update subsystem.
IsPdiAddrLookupHandler is the PDI address look-up handler. CheckAsuPresenceHandler is the callback to check ASU presence in PDI. LoadAsuImageHandler is the callback to load ASU image from PDI. XST_SUCCESS if initialization successful.XPLM_ERR_TASK_CREATE if failed to create ASU update task.
References XPLM_ERR_TASK_CREATE, XPLMI_ASU_UPDATE_TASK_ID, XPlmi_TaskCreate.
int XPlmi_AsuUpdate(XPlmi_Cmd *Cmd)
This function handles In-Place ASU Update.
Cmd is the command structure with payload containing DDR address. XST_SUCCESS if ASU update successful.Error code on failure.
References XPLMI_ASU_UPDATE_TASK_ID, XPlmi_AsuFwIsPresent, XPLMI_ERR_INPLACE_UPDATE_FROM_IMAGE_STORE, XPLMI_ERR_INPLACE_UPDATE_INVALID_PAYLOAD_LEN, XPLMI_ERR_INPLACE_UPDATE_TASK_NOT_FOUND, XPLMI_ERR_INVALID_PAYLOAD_LEN, XPLMI_ERR_INVALID_RSVD_DDR_REGION_UPDATE, XPlmi_GetTaskInstance, XPlmi_HandleSwError, XPLMI_INVALID_PLM_RSVD_DDR_ADDR, XPLMI_INVALID_PLM_RSVD_DDR_SIZE, XPLMI_INVALID_UPDATE_ADDR, XPLMI_RTCFG_IMG_STORE_ADDRESS_HIGH, XPLMI_RTCFG_PLM_RSVD_DDR_ADDR, XPLMI_RTCFG_PLM_RSVD_DDR_SIZE, XPlmi_TaskTriggerNow, XPLMI_UPDATE_FLAG_MASK, XPLMI_UPDATE_PAYLOAD_LEN, XPLMI_UPDATE_USING_IMAGE_STORE.
static void XPlmi_HandleLPDSlcrError(u32 ErrorNodeId, u32 RegMask)
This function handles the error in LPD SLCR routed to PLM.
ErrorNodeId is the node ID for the error event RegMask is the register mask of the error received None
static void XPlmi_ErrLPDSlcrIntrHandler(u32 ErrorNodeId, u32 RegMask)
This function is the interrupt handler for Errors in LPDSLCR.
ErrorNodeId is the node ID for the error event RegMask is the register mask of the error received None
static void XPlmi_PcieErrHandler(u32 ErrorNodeId, u32 RegMask)
This function handles the PCIE errors.
ErrorNodeId is the node ID for the error event RegMask is the register mask of the error received
void XPlmi_ReconfigErrActions(void)
This function reconfigures error actions after the update.
None
References XPlmi_EmConfig.
Referenced by XPlmi_EmInit.
int EmEnableLpdSlcrErrAction(u32 ErrMaskRegAddr, u32 RegMask)
This function enables the error action for the given error mask.
ErrMaskRegAddr is the error action mask register address RegMask is the register mask of the error to be disabled XST_SUCCESS on success.XPLMI_ERROR_ACTION_NOT_ENABLED if error action is not enabled.
int XPlmi_EmDisableLpdSlcrErrors(u32 RegMaskAddr, u32 RegMask)
This function disables the LPD SCLR error actions for the given mask.
RegMaskAddr is the offset for the PMC ERR, POR ,IRQ mask,SRST mask RegMask is the register mask of the error to be disabled XST_SUCCESS on success.XPLMI_ERROR_ACTION_NOT_DISABLED if error action is not disabled.
Referenced by XPlmi_EmDisable, XPlmi_GenericHandler, XPlmi_LpdSlcrEmInit.
int XPlmi_Versal2Ve2VmEAMHandler(void *Data)
This function is the interrupt handler for the EAM errors.
Data is presently passed as NULL XST_SUCCESS always.
References GET_PMC_ERR_ACTION_OFFSET, GET_PMC_IRQ_MASK, XPlmi_EmClearError, XPlmi_EmDisable, XPlmi_GetErrorTable, XPlmi_PlmIntrClear, XPlmi_PlmIntrEnable.
Referenced by XPlmi_ErrorTaskHandler.
int XPlmi_LpdSlcrEmInit(void)
This function initializes the error actions in LPD Slcr Disables all the LPD SLCR error actions and registers default action.
XST_SUCCESS always.
References XPlmi_EmDisableLpdSlcrErrors, XPlmi_EmSetAction, XPlmi_GetErrorTable.
Referenced by XPlmi_LpdInit.
int XPlmi_Versal2Ve2VmSetAction(XPlmi_Cmd *Cmd)
This function sets the error action as prescribed by the command.
Command payload parameters are * Error Node ID * Error Action 0 - Invalid 1 - POR 2 - SRST 3 - Custom(Not supported) 4 - ErrOut 5 - Subsystem Shutdown 6 - Subsystem Restart 7 - Print to log 8 - SLD 9 - SLD with TRI 10 - None * Error ID Mask Cmd is pointer to the command structure XST_SUCCESS on success.XPLMI_INVALID_NODE_ID on invalid node ID.XPLMI_INVALID_ERROR_ACTION on invalid error action.XPLMI_CANNOT_CHANGE_ACTION if failed to change error action.XPLMI_LPD_UNINITIALIZED if LPD failed to initialize.
References XPlmi_EmSetAction, XPlmi_GetEmSubsystemId, XPlmi_GetEventIndex, XPlmi_RestrictErrActions.
static u32 XPlmi_GetRawVoltage(float Voltage)
This function converts voltage to raw voltage value.
Voltage is the floating point voltage value 32-bit voltage value
static void XPlmi_DisableClearIOmodule(void)
This function will disable and clear the IOmodule interrupts.
None
static void XPlmi_HwIntrHandler(void *CallbackRef)
This function provides handler for HW interrupts.
CallbackRef is presently the interrupt number that is received
static u32 XPlmi_GetIoIntrMask(void)
This function returns the current enabled interrupt mask of IOmodule.
Current interrupt enable mask
static void XPlmi_SetIoIntrMask(u32 Value)
This function enables the IOModule interrupts with provided value.
Value to be written to the IER register of IOModule
static int XPlmi_UpdateFipsState(void)
This function monitors the KAT status and updates the FIPS state in RTCA.
XST_SUCCESS on successXST_FAILURE on failure
int XPlmi_GenericHandler(XPlmi_ModuleOp Op)
This function is used for shutdown operation before In-place PLM Update.
Op is the operation information XST_SUCCESS on success and XST_FAILURE on failure
References EmDisableErrAction, GET_PMC_ERR_ACTION_OFFSET, GET_PMC_IRQ_MASK, XPlmi_EmDisableLpdSlcrErrors, XPlmi_GicIntrClearStatus, XPLMI_MODULE_NORMAL_STATE, XPLMI_MODULE_SHUTDOWN_ABORT, XPLMI_MODULE_SHUTDOWN_COMPLETE, XPLMI_MODULE_SHUTDOWN_COMPLETED_STATE, XPLMI_MODULE_SHUTDOWN_INITIATE, XPLMI_MODULE_SHUTDOWN_INITIATED_STATE, XPlmi_PlmIntrClear, XPlmi_PlmIntrDisable, XPLMI_RTCFG_SECURE_STATE_PLM_ADDR, XPLMI_SBI_GICP_INDEX, XPLMI_SBI_GICPX_INDEX.
void XPlmi_IpiIntrHandler(void *CallbackRef)
This function is the IPI interrupt handler for the device.
This function is the Ipi interrupt handler for the device. CallbackRef is a dummy argument
References XPlmi_GetIpiIntrId, XPlmi_GetTaskInstance, XPlmi_PlmIntrClear, XPlmi_TaskTriggerNow.
u32 XPlmi_GetRomIroFreq(void)
This function provides the Iro Frequency used in ROM.
RomIroFreq value
Referenced by XPlmi_PrintRomTime.
static u32 XPlmi_IsMporHpPart(void)
This function provides check if its Mp or hp part.
- returns TRUE for voltage > 0.775v FALSE otherwise
int XPlmi_RomISR(XPlmi_RomIntr RomServiceReq)
This function raises an interrupt request to ROM and waits for completion.
Before calling this API all pre-requsites for ROM service shall be completed. RomServiceReq variable of enum type XPlmi_RomIntr XST_SUCCESS if success.XPLMI_ERR_INVALID_ROM_INT_REQ on invalid interrupt request for ROM.
References XPLMI_DME_CHL_SIGN_GEN, XPLMI_INVALID_INT, XPLMI_PLM_UPDT_REQ, XPLMI_ROM_SERVICE_TIMEOUT.
u32 XPlmi_IsFipsModeEn(void)
This function return FIPS mode.
TRUE If FIPS mode is enabled FALSE If FIPS mode is disabled
Referenced by XPlmi_CheckAndUpdateFipsState.
u32 XPlmi_GetRomKatStatus(void)
This function returns ROM KAT status.
ROM KAT status
References XPLMI_ROM_KAT_MASK.
void XPlmi_ClearSSSCfgErr(void)
This function clears SSS Cfg error set during ROM PCR Extension.
References XPlmi_IsPlmUpdateDone.
XPlmi_FipsKatMask * XPlmi_GetFipsKatMaskInstance(void)
This function returns XPlmi_FipsKatMask instance.
pointer to the XPlmi_FipsKatMask instance
Referenced by XPlmi_SetFipsKatMask.
int XPlmi_CheckAndUpdateFipsState(void)
This function checks and updates the FIPS state in RTCA.
XST_SUCCESS on successXST_FAILURE on failure
References XPlmi_IsFipsModeEn.
Referenced by XPlmi_SetFipsKatMask, XPlmi_UpdateKatStatus.
void XPlmi_UpdateCryptoStatus(u32 Mask, u32 Val)
This function sets or clears crypto bit in RTCA based on mask.
Mask Mask to set or clear crypto status Val Value to set or clear crypto status
References XPlmi_UtilRMW.
u32 XPlmi_GetCryptoStatus(u32 Mask)
This function returns crypto status flag.
Mask Mask to read crypto status Crypto status value
u8 XPlmi_IsKatRan(u32 PlmKatMask)
This function will return KAT status of given mask.
PlmKatMask contains the KAT mask TRUE If KAT ran FALSE If KAT didn't ran PlmKatMask contains the KAT mask TRUE If KAT ran.FALSE If KAT didn't ran.
References XPlmi_IsCryptoKatEn.
int XPlmi_VerifyAddrRange(u64 StartAddr, u64 EndAddr)
This function is used to check if the given address range is valid.
This function can be called before loading any elf or assigning any buffer in that address range. StartAddr is the starting address. EndAddr is the ending address. XST_SUCCESS on success.Error code on failure.
void XPlmi_HandleLinkUpEvent(u32 Cpm5NPcieCdxIrStatusReg, u32 Cpm5NCdxPcieBReg, u32 ProcId)
This function handles the CPM_NCR PCIE link up event.
Cpm5NPcieCdxIrStatusReg is the PCIE0/1/2/3 IR status register address Cpm5NCdxPcieBReg is the Pcie Bridge Misc Status register address ProcId is the ProcId for PCIE0/1/2/3 link up event
References XPlmi_ErrMgr, XPlmi_ExecuteProc.
static u32 XPlmi_IsHpPart(void)
This function provides check if its hp part.
- returns TRUE for voltage > 0.854v FALSE otherwise
static void XPlmi_DisableIOmodule(void)
This function will disable the IOmodule interrupts.
void XPlmi_SetAddrBufferList(void)
This function initializes Address Buffer List.
References XPLMI_MAX_ADDR_BUFFERS, XPLMI_MAX_ADDR_LIST_CNT.
int XPlmi_InPlacePlmUpdate(XPlmi_Cmd *Cmd)
This function provides In Place PLM Update support.
Cmd is pointer to the command structure Command payload parameters are High AddrLow Addr XST_SUCCESS on success and error code on failure
References XPlmi_PlmUpdate.
static int XPlmi_SendToPsm(u32 BuffAddr, u32 BuffLen)
This function is used to send psm_sequence commands data address and length to be processed by PSM.
BuffAddr is the address of the buffer BuffLen is the length of the buffer in 32-bit word XST_SUCCESS on success and error code on failure
int XPlmi_PsmSequence(XPlmi_Cmd *Cmd)
This function is used to transfer all psm_sequence commands to PSM RAM regions which are then processed by PSM immediately.
Cmd is a pointer to command structure XST_SUCCESS if success.XPLMI_ERR_PROC_LPD_NOT_INITIALIZED if failed to initialize LPD.XPLMI_UNSUPPORTED_PROC_LENGTH if received proc does not fit in the proc memory.
References XPlmi_DmaTransfer, XPLMI_ERR_PROC_LPD_NOT_INITIALIZED, XPlmi_GetBufferList, XPLMI_PSM_SEQUENCE_CMD_ID, XPLMI_UNSUPPORTED_PROC_LENGTH, XPLMI_WORD_LEN.
int XPlmi_ScatterWrite(XPlmi_Cmd *Cmd)
This function will write single 32 bit value to multiple addresses which are specified in the payload.
Command payload parameters are - Value - Address[N]: array of N addresses Cmd is pointer to the command structure XST_SUCCESS if success.XPLMI_ERR_INVALID_PAYLOAD_LEN on invalid payload length.
References XPLMI_ERR_INVALID_PAYLOAD_LEN, XPlmi_Print, XPLMI_SCATTER_WRITE_CMD_ID, XPLMI_SCATTER_WRITE_PAYLOAD_LEN.
int XPlmi_ScatterWrite2(XPlmi_Cmd *Cmd)
This function will write 2 32-bit values to multiple addresses which are specified by the payload.
Command payload parameters are Value1Value2Address[N]: array of N addresses where Address[i] = Value1 and Address[i] + 4 = Value2 Cmd is pointer to the command structure XST_SUCCESS if success.XPLMI_ERR_INVALID_PAYLOAD_LEN on invalid payload length.
References XPLMI_ERR_INVALID_PAYLOAD_LEN, XPlmi_Print, XPLMI_SCATTER_WRITE2_CMD_ID, XPLMI_SCATTER_WRITE2_PAYLOAD_LEN, XPLMI_WORD_LEN.
int XPlmi_SetFipsKatMask(XPlmi_Cmd *Cmd)
This function will store the KAT mask set by the user so that PLM can monitor the RTCA and compare it with KAT masks before going into FIPS operational state.
Cmd is pointer to the command structure XST_SUCCESS if success.XPLMI_ERR_INVALID_PAYLOAD_LEN on invalid payload length.
References XPlmi_CheckAndUpdateFipsState, XPLMI_ERR_INVALID_PAYLOAD_LEN, XPLMI_FIPS_WRITE_KATMASK_PAYLOAD_LEN, XPlmi_GetFipsKatMaskInstance, XPLMI_KAT_MASK, XPlmi_Print, XPLMI_ROM_KAT_MASK, XPLMI_SET_FIPS_MASK_CMD_ID.
int XPlmi_RunProc(XPlmi_Cmd *Cmd)
This function will run the already stored proc if present.
Cmd is pointer to the command structure XST_SUCCESS if success and error code if failure
References XPlmi_ExecuteProc, XPLMI_RUN_PROC_CMD_ID.
int XPlmi_ListSet(XPlmi_Cmd *Cmd)
This function will create a list with given list of addresses.
Cmd is pointer to the command structure XST_SUCCESS if success and error code if failure
References XPLMI_LIST_ID_INDEX, XPLMI_LIST_ID_MASK, XPLMI_LIST_ID_SHIFT, XPLMI_LIST_SET_CMD_ID, XPlmi_StoreBuffer.
int XPlmi_ListWrite(XPlmi_Cmd *Cmd)
This function will execute write for the requested list of addresses.
Cmd is pointer to the command structure XST_SUCCESS if success and error code if failure
References XPLMI_ADDRESS_OFFSET_MASK, XPLMI_LIST_ID_MASK, XPLMI_LIST_ID_SHIFT, XPLMI_LIST_WRITE_CMD_ID, XPlmi_SearchBufferList.
int XPlmi_ListMaskWrite(XPlmi_Cmd *Cmd)
This function will execute mask write for the requested list of addresses.
Cmd is pointer to the command structure XST_SUCCESS if success and error code if failure
References XPLMI_ADDRESS_OFFSET_MASK, XPLMI_LIST_ID_MASK, XPLMI_LIST_ID_SHIFT, XPLMI_LIST_MASK_WRITE_CMD_ID, XPlmi_SearchBufferList, XPlmi_UtilRMW.
int XPlmi_ListMaskPoll(XPlmi_Cmd *Cmd)
This function will execute mask poll for the requested list of addresses.
Cmd is pointer to the command structure XST_SUCCESS if success and error code if failure
References XPLMI_ADDRESS_OFFSET_MASK, XPlmi_GenericMaskPoll, XPLMI_LIST_ID_MASK, XPLMI_LIST_ID_SHIFT, XPLMI_LIST_MASK_POLL_CMD_ID, XPlmi_SearchBufferList.
static int XPlmi_PlmUpdateMgr(void)
This function will Initiate the PLM Update process with ROM.
XST_SUCCESS on success and error code on failure No Functions should be called inside this function as this code will be relocated during run time and the relative jumps used for the function calls can not be resolved. However, inline functions can be used provided they are forced to be inline using compiler attributes.
static int XPlmi_PlmUpdateTask(void *Arg)
This function does In-Place PLM Update.
Arg is the PDI address. XST_SUCCESS if success.XPLMI_ERR_PLM_UPDATE_SHUTDOWN_COMPLETE if failed to shutdown complete of modules during in place PLM update.XPLMI_ERR_STORE_DATA_BACKUP if failed to store the data structure.XPLMI_ERR_MEMCPY_RELOCATE if failed to relocate update manager code.XPLMI_ERR_PLM_UPDATE_RELOCATED_FN if the relocated PLM update function fails.
EXPORT_GENERIC_DS(UpdatePdiAddr, XPLMI_UPDATE_PDIADDR_DS_ID, XPLMI_UPDATE_PDIADDR_VER, XPLMI_UPDATE_PDIADDR_LCVER, sizeof(UpdatePdiAddr),(u32)(UINTPTR)&UpdatePdiAddr)
Macro to Export Data Structures.
Referenced by XPlmi_GetBoardParams, XPlmi_GetBufferList.
int XPlmi_UpdateInit(XPlmi_CompatibilityCheck_t CompatibilityHandler, XPlmi_IsPdiAddrLookup_t IsPdiAddrLookupHandler, XPlmi_CheckPsmPresenceInOD_t CheckPsmPresenceHandler)
Db End Address.
This function will initialize In-Place Update related logic CompatibilityHandler is the handler used for compatibility check IsPdiAddrLookupHandler is the PDI address look-up handler CheckPsmPresenceHandler is the PSM presence check handler XST_SUCCESS if success.XPLM_ERR_TASK_CREATE if failed to create a task.XPLMI_ERR_IPI_DRV_INIT if there is a failure in Ipi Driver Init which is done after In-Place update.XPLMI_ERR_MEMSET_UPDATE_RESP if there is a failure in memset of IPI response buffer used to ack the ipi after update.
References PMX_PLM_UPDATE_REASON_MASK, XPLM_ERR_TASK_CREATE, XPLMI_ERR_INVALID_RSVD_DDR_REGION_RESTORE, XPLMI_INVALID_PLM_RSVD_DDR_ADDR, XPLMI_INVALID_PLM_RSVD_DDR_SIZE, XPlmi_IsPlmUpdateDone, XPlmi_KickWdt, XPlmi_RestoreDataBackup, XPLMI_RTCFG_PLM_RSVD_DDR_ADDR, XPLMI_RTCFG_PLM_RSVD_DDR_SIZE, XPlmi_TaskCreate, XPLMI_UPDATE_DONE, XPLMI_UPDATE_TASK_ID.
u8 XPlmi_IsPlmUpdateDone(void)
This function checks if Inplace PLM update occurs or not.
TRUE if Inplace PLM Update and FALSE otherwise
References XPLMI_UPDATE_DONE.
Referenced by XPlmi_ClearSSSCfgErr, XPlmi_EmInit, XPlmi_ErrMgr, XPlmi_LpdInit, XPlmi_PrintPlmBanner, XPlmi_RunTimeConfigInit, XPlmi_StartTimer, XPlmi_UpdateInit.
u8 XPlmi_IsPlmUpdateDoneTmp(void)
This function checks if Inplace PLM update occurs or not.
TRUE if Inplace PLM Update and FALSE otherwise
References XPLMI_UPDATE_DONE.
Referenced by XPlmi_RunTimeConfigInit.
u8 XPlmi_IsPlmUpdateInProgress(void)
This function checks if Inplace PLM update is in progress or not.
TRUE if Inplace PLM Update is in progress and FALSE otherwise
References XPLMI_UPDATE_IN_PROGRESS.
Referenced by XPlmi_PlmUpdate.
int XPlmi_DsOps(u32 Op, u64 Addr, void *Data)
This function does operations like storing, restoring the Data Structure to Memory during PLM update.
Op is the type of operation to be performed on the data structure Addr is the memory address to which data structure should be stored or restored from Data is the Data Structure Entry XST_SUCCESS if success.XPLMI_ERR_INVALID_DS_ENTRY if invalid Data Structure entry is passed to the PLM Db Update Handler.XPLMI_ERR_DS_ALIGNMENT_INCORRECT if the alignment of Data Structure used during store or restore operations is not word aligned Header.XPLMI_ERR_PLM_UPDATE_DB_OVERFLOW if the given Data Structure length is exceed the Update DB buffer available.XPLMI_ERR_MEMCPY_STORE_DB if memcpy failed to store database.XPLMI_ERR_MEMSET_RESTORE_DB if memset failed to restore database.XPLMI_ERR_MEMCPY_RESTORE_DB if memcpy failed to restore database.XPLMI_ERR_PLM_UPDATE_INVALID_OP if invalid operation is passed to PLM Update DB Handler.
References XPLMI_DS_HDR_SIZE, XPLMI_RESTORE_DATABASE, XPLMI_STORE_DATABASE, XPLMI_WORD_LEN.
XPlmi_DsEntry* XPlmi_GetDsEntry(XPlmi_DsEntry *DsList, u32 DsCnt, XPlmi_DsVer *DsVer)
This function returns DsEntry found after searching in the provided DsList.
DsList is the Data Structure List in which the DS is searched DsCnt is the number of Data Structures present in the List DsVer is the version information of the data structure XST_SUCCESS on success and error code on failure
Referenced by XPlmi_RestoreDataBackup.
int XPlmi_RestoreDataBackup(void)
This function restore all the data structures after InPlace PLM update.
XST_SUCCESS on success.XPLMI_ERR_DB_HDR_VERSION_MISMATCH if the DB Hdr version of old PLM is not matching with that of updated PLM.XPLMI_ERR_DB_HDR_SIZE_MISMATCH if the DB Hdr size of old PLM is not matching with the size of updated PLM.XPLMI_ERR_DB_ENDADDR_INVALID if the DB end address calculated is not in a valid range that is accepted by updated PLM. Data Structures during InPlace PLM Update.XPLMI_ERR_INVALID_RESTORE_DS_HANDLER if invalid Data Structure Handler used in restoring of Data Structures during InPlace PLM Update.
References XPLMI_DS_CNT, XPLMI_DS_HDR_SIZE, XPlmi_GetDsEntry, XPLMI_RESTORE_DATABASE, XPLMI_UPDATE_DB_VERSION, XPLMI_WORD_LEN.
Referenced by XPlmi_UpdateInit.
static int XPlmi_StoreDataBackup(void)
This function store all the data structures before InPlace PLM update.
XST_SUCCESS if success.XPLMI_ERR_MEMSET_DBHDR if memset of DbHdr during store database is failed.XPLMI_ERR_INVALID_STORE_DS_HANDLER if invalid Data Structure Handler used in storing of Data Structures during InPlace PLM Update.
static int XPlmi_ShutdownModules(XPlmi_ModuleOp Op)
This function shutdown all the modules gracefully.
Op is the operation structure passed to determine type of operation and other details XST_SUCCESS on success and error code on failure
static u32 XPlmi_GetPlmDbSize(void)
This function provides the PLM Database Size which has to be stored and restored during the update.
Size of PLM Database
int XPlmi_PlmUpdate(XPlmi_Cmd *Cmd)
This function does In-Place PLM Update.
Cmd is the command pointer of in place update command XST_SUCCESS if success.XPLMI_ERR_INPLACE_UPDATE_IN_PROGRESS if a task cannot be executed as the update is in progress.XPLMI_ERR_INPLACE_UPDATE_DISABLED if PLM Update is disabled in ROM_RSV efuse.XPLMI_ERR_INVALID_RSVD_DDR_REGION_UPDATE if invalid/no DDR region reserved for PLM.XPLMI_ERR_INPLACE_UPDATE_SHUTDOWN_INIT if failed to shutdown initiate of modules during InPlace PLM UpdateXPLMI_ERR_INPLACE_UPDATE_TASK_NOT_FOUND if PLM Update task is not found.XPLMI_ERR_INPLACE_UPDATE_INVALID_PAYLOAD_LEN if Invalid Payload Len.XPLMI_ERR_INPLACE_UPDATE_FROM_IMAGE_STORE error during update from IS.
References XPLMI_ERR_INPLACE_UPDATE_DISABLED, XPLMI_ERR_INPLACE_UPDATE_FROM_IMAGE_STORE, XPLMI_ERR_INPLACE_UPDATE_IN_PROGRESS, XPLMI_ERR_INPLACE_UPDATE_INVALID_PAYLOAD_LEN, XPLMI_ERR_INPLACE_UPDATE_SHUTDOWN_INIT, XPLMI_ERR_INPLACE_UPDATE_TASK_NOT_FOUND, XPLMI_ERR_INSUFFICIENT_PLM_RSVD_DDR_REGION, XPLMI_ERR_INVALID_RSVD_DDR_REGION_UPDATE, XPlmi_GetTaskInstance, XPLMI_INVALID_PLM_RSVD_DDR_ADDR, XPLMI_INVALID_PLM_RSVD_DDR_SIZE, XPlmi_IsPlmUpdateInProgress, XPLMI_MODULE_NO_OPERATION, XPLMI_MODULE_SHUTDOWN_ABORT, XPLMI_MODULE_SHUTDOWN_INITIATE, XPLMI_RTCFG_IMG_STORE_ADDRESS_HIGH, XPLMI_RTCFG_INPLACE_UPDATE_IPI_MASK, XPLMI_RTCFG_INPLACE_UPDATE_IPI_RESP_BUFF, XPLMI_RTCFG_PLM_RSVD_DDR_ADDR, XPLMI_RTCFG_PLM_RSVD_DDR_SIZE, XPlmi_TaskTriggerNow, XPLMI_UPDATE_FLAG_MASK, XPLMI_UPDATE_IN_PROGRESS, XPLMI_UPDATE_PAYLOAD_LEN, XPLMI_UPDATE_TASK_ID, XPLMI_UPDATE_USING_IMAGE_STORE.
Referenced by XPlmi_InPlacePlmUpdate.
u32 XPlmi_GetUpdatePdiAddr(void)
This function gets UpdatePdiAddr variable value.
UpdatePdiAddr value
u32 XPlmi_GetPlmUpdateIpiMask(void)
This function gets PlmUpdateIpiMask variable value.
PlmUpdateIpiMask value
References XPlmi_GetPlmUpdateIpiMask, XPLMI_RTCFG_INPLACE_UPDATE_IPI_MASK.
Referenced by XPlmi_GetPlmUpdateIpiMask.
void XPlmi_SetPlmUpdateIpiMask(u32 value)
This function sets PlmUpdateIpiMask variable value.
value of PlmUpdateIpiMask
References XPLMI_RTCFG_INPLACE_UPDATE_IPI_MASK.
int XPlmi_DefaultSWdtConfig(void)
This function configures the default WDT configuration if the wdt is not enabled and ROM SWDT usage bit is enabled in EFUSE.
XST_SUCCESS on success and error code on failure
References XPlmi_EnableWdt, XPLMI_PM_DEV_PMC_WDT.
void XPlmi_StopWdt(u32 NodeId)
This function stops PMC WDT.
Used during In-Place PLM update. NodeId is the Node ID of external WDT or internal PMC WDT
static void XPlmi_RefreshWdt(u32 NodeId)
This function is used to refresh WDT before timeout.
NodeId is the Node ID of external WDT or internal PMC WDT
void XPlmi_KickWdt(u32 NodeId)
This function is used to kick the WDT.
NodeId is the Node ID of external WDT or internal PMC WDT
Referenced by XPlmi_UpdateInit.
void XPlmi_RestoreWdt(void)
This function is used to restore wdt after the In-Place PLM Update.
XPLMI_MAX_RECURSIVE_CDO_PROCESS
< Maximum recursive CDO processing allowed
Referenced by XPlmi_ProcessCdo.
XPLMI_XCSUDMA_DEST_CTRL_OFFSET
CSUDMA destination control offset.
XPLMI_CMD_ID_EM_FEATURES
Command Id of error module features.
XPLMI_CMD_ID_EM_SET_ACTION
Command Id of set action error module.
XPLMI_MB_MSR_BIP_MASK
Microblaze MSR Break In Progress bit mask.
Referenced by XPlmi_SetUpInterruptSystem.
XPLMI_SYSMON_SAT0_PCSR_MASK_OFFSET
SAT0 PCSR mask offset.
Referenced by XPlmi_SysMonInit.
XPLMI_SYSMON_SAT1_PCSR_MASK_OFFSET
SAT1 PCSR mask offset.
Referenced by XPlmi_SysMonInit.
XPLMI_SYSMON_PCSR_CTRL_SLVERREN_MASK
PCSR control slave error enable mask.
Referenced by XPlmi_SysMonInit.
XPLMI_SYSMON_CLK_SRC_IRO_VAL
Sysmon clock source IRO value.
Referenced by XPlmi_SysmonClkSetIro.
XPLMI_PMC_ERR_SSIT_MASK
PMC error SSIT mask.
Referenced by XPlmi_ClearSsitErrors.
CPM_NCR_PCIE0_LINK_DOWN_PROC_ID
PCIE0 link down proc Id.
CPM_NCR_PCIE1_LINK_DOWN_PROC_ID
PCIE1 link down proc Id.
XPLMI_DIGEST_PMC_1_0_ROM_1_0
PMC1 ROM version 1 digest.
XPLMI_DIGEST_PMC_2_0_ROM_2_0
PMC2 ROM version 2 digest.
XPLMI_ROM_VERSION_1_0
ROM version 1.
XPLMI_ROM_VERSION_2_0
ROM version 2.
XPLMI_INVALID_ROM_VERSION
Invalid ROM version.
XPLMI_CFU_STREAM_2_SLR_OFFSET
SLR offset for CFU stream 2 register.
XPLMI_CFU_FDRO_2_SLR_OFFSET
SLR offset for CFU FDRO 2 register.
XPLMI_SLR1_CFU_FDRO_2_ADDR
SLR1 CFU FDRO 2 address.
Referenced by XPlmi_GetReadbackSrcDest.
XPLMI_SLR2_CFU_FDRO_2_ADDR
SLR2 CFU FDRO 2 address.
Referenced by XPlmi_GetReadbackSrcDest.
XPLMI_SLR3_CFU_FDRO_2_ADDR
SLR3 CFU FDRO 2 address.
Referenced by XPlmi_GetReadbackSrcDest.
XPLMI_SLR1_CFU_STREAM_2_ADDR
SLR1 CFU Stream 2 address.
Referenced by XPlmi_GetReadbackSrcDest.
XPLMI_SLR2_CFU_STREAM_2_ADDR
SLR2 CFU Stream 2 address.
Referenced by XPlmi_GetReadbackSrcDest.
XPLMI_SLR3_CFU_STREAM_2_ADDR
SLR3 CFU Stream 2 address.
Referenced by XPlmi_GetReadbackSrcDest.
XPLMI_PMC_VOLTAGE_MULTIPLIER
PMC voltage multiplier.
XPLMI_PMC_VERSION_1_0
PMC version 1.0.
XPlmi_GetRawVoltage
This macro converts voltage to raw voltage value.
Voltage is the voltage value in volts 32-bit voltage value
XPLMI_CMD_ID_ASU_FEATURES
Command Id of ASU module features.
XPLMI_CMD_ID_ASU_KEY_TRANSFER
Command Id of ASU key transfer features.
XPLMI_CMD_ID_ASU_CDI_TRANSFER
Command Id of ASU CDI transfer features.
XPLMI_CMD_ID_SUBSYSTEM_HASH_TRANSFER
Command Id of subsystem hash transfer features.
XPLMI_CMD_ID_GET_OCP_EVENT_MASK
Command Id to get OCP event mask.
XPLMI_CMD_ID_ASU_FEATURES_INDEX
ASU module features index.
XPLMI_CMD_ID_ASU_RESPONSE_INDEX
ASU module response index.
XPLMI_RESP_CMD_EXEC_STATUS_INDEX
Response command execution status index.
XPLMI_ASU_IPI_FULL_ACCESS
Value for only ASU mask to be full access.
XPLMI_ASU_UPDATE_TASK_ID
Task Id for ASU update.
Referenced by XPlmi_AsuUpdate, XPlmi_AsuUpdateInit.
XPLMI_INVALID_UPDATE_ADDR
Invalid update address.
Referenced by XPlmi_AsuUpdate.
XPLMI_ASU_MAX_RETRY_COUNT
Max retry count: 600 * 100ms = 60 sec.
XPLMI_US_TO_MS_DIV_FACTOR
Microseconds to milliseconds conversion factor.
XPLMI_UPDATE_FLAG_MASK
In-Place Update flag Mask.
Referenced by XPlmi_AsuUpdate.
XPLMI_UPDATE_PAYLOAD_LEN
In-Place Update payload len.
Referenced by XPlmi_AsuUpdate.
XPLMI_UPDATE_USING_IMAGE_STORE
In-Place Update using PDI in Image Store, 1-DDR Location.
Referenced by XPlmi_AsuUpdate.
XPLMI_ERROR_TABLE_DS_VER
Error table data structure version.
XPLMI_ERROR_TABLE_DS_LCVER
Error table data structure LC version.
XPLMI_NUM_ERROUTS_VERSION
ERROUTS version.
XPLMI_NUM_ERROUTS_LCVERSION
ERROUTS LC version.
PCIE0_LINK_DOWN_PROC_ID
PCIE0 link down proc Id.
PCIE1_LINK_DOWN_PROC_ID
PCIE1 link down proc Id.
XPLMI_ROM_VERSION_1_0
ROM version 1.
XPLMI_SSSCFG_SHA0_MASK
SHA0 mask.
XPLMI_SSSCFG_SHA1_MASK
SHA1 mask.
XPLMI_SSSCFG_AES_MASK
AES mask.
XPLMI_SSS_SHA0_DMA0
SHA0 DMA0.
XPLMI_SSS_SHA0_DMA1
SHA0 DMA1.
XPLMI_SSS_SHA1_DMA0
SHA1 DMA0.
XPLMI_SSS_SHA1_DMA1
SHA1 DMA1.
XPLMI_SSS_AES_DMA0
AES DMA0.
XPLMI_SSS_AES_DMA1
AES DMA1.
XPLMI_LPDINITIALIZED_VER
LPD initialized version.
XPLMI_LPDINITIALIZED_LCVER
LPD initialized LC version.
XPLMI_UART_BASEADDR_VER
UART base address version.
XPLMI_UART_BASEADDR_LCVER
UART base address LC version.
XPLMI_TRACE_LOG_VERSION
Trace log version.
XPLMI_TRACE_LOG_LCVERSION
Trace log LC version.
XPLMI_BOARD_PARAMS_VERSION
Board parameters version.
Referenced by XPlmi_GetBoardParams.
XPLMI_BOARD_PARAMS_LCVERSION
Board parameters LC version.
Referenced by XPlmi_GetBoardParams.
XPLMI_XIOMODULE_VERSION
IOModule version.
XPLMI_XIOMODULE_LCVERSION
IOModule LC version.
XPLMI_PMC_VOLTAGE_MULTIPLIER
Voltage multiplier for Sysmon.
XPLMI_PPU_BUFFER_DS_VER
PPU buffers Data structure version.
Referenced by XPlmi_GetBufferList.
XPLMI_PPU_BUFFER_DS_LCVER
PPU buffers Data structure LC version.
Referenced by XPlmi_GetBufferList.
XPLMI_PMC_BUFFER_DS_VER
PMC buffers Data structure version.
Referenced by XPlmi_GetBufferList.
XPLMI_PMC_BUFFER_DS_LCVER
PMC buffers Data structure LC version.
Referenced by XPlmi_GetBufferList.
XPLMI_PPU_BUFFER_LIST_DS_VER
PPU buffer list Data structure version.
Referenced by XPlmi_GetBufferList.
XPLMI_PPU_BUFFER_LIST_DS_LCVER
PPU buffer list Data structure LC version.
Referenced by XPlmi_GetBufferList.
XPLMI_PMC_BUFFER_LIST_DS_VER
PMC buffer list Data structure version.
Referenced by XPlmi_GetBufferList.
XPLMI_PMC_BUFFER_LIST_DS_LCVER
PMC buffer list Data structure LC version.
Referenced by XPlmi_GetBufferList.
XPLMI_SYSMON_CLK_SRC_IRO_VAL
Sysmon clock source IRO value.
XPLMI_PMC_ERR_SSIT_MASK
PMC error SSIT mask.
CPM_NCR_PCIE0_LINK_DOWN_PROC_ID
PCIE0 link down proc Id.
CPM_NCR_PCIE1_LINK_DOWN_PROC_ID
PCIE1 link down proc Id.
XPLMI_DIGEST_PMC_1_0_ROM_1_0
PMC1 ROM version 1 digest.
XPLMI_DIGEST_PMC_2_0_ROM_2_0
PMC2 ROM version 2 digest.
XPLMI_ROM_VERSION_1_0
ROM version 1.
XPLMI_ROM_VERSION_2_0
ROM version 2.
XPLMI_INVALID_ROM_VERSION
Invalid ROM version.
XPLMI_CFU_STREAM_2_SLR_OFFSET
SLR offset for CFU stream 2 register.
XPLMI_CFU_FDRO_2_SLR_OFFSET
SLR offset for CFU FDRO 2 register.
XPLMI_SLR1_CFU_FDRO_2_ADDR
SLR1 CFU FDRO 2 address.
XPLMI_SLR2_CFU_FDRO_2_ADDR
SLR2 CFU FDRO 2 address.
XPLMI_SLR3_CFU_FDRO_2_ADDR
SLR3 CFU FDRO 2 address.
XPLMI_SLR1_CFU_STREAM_2_ADDR
SLR1 CFU Stream 2 address.
XPLMI_SLR2_CFU_STREAM_2_ADDR
SLR2 CFU Stream 2 address.
XPLMI_SLR3_CFU_STREAM_2_ADDR
SLR3 CFU Stream 2 address.
XPLMI_PMC_VOLTAGE_MULTIPLIER
PMC voltage multiplier.
XPLMI_PMC_VERSION_1_0
PMC version 1.0.
XPlmi_GetRawVoltage
This macro converts voltage to raw voltage value.
Voltage is the voltage value in volts. 32-bit voltage value.
XPLMI_SYSMON_CLK_SRC_IRO_VAL
Sysmon clock source IRO value.
XPLMI_PMC_ERR_SSIT_MASK
PMC error SSIT mask.
CPM_NCR_PCIE0_LINK_DOWN_PROC_ID
PCIE0 link down proc Id.
CPM_NCR_PCIE1_LINK_DOWN_PROC_ID
PCIE1 link down proc Id.
XPLMI_DIGEST_PMC_1_0_ROM_1_0
PMC1 ROM version 1 digest.
XPLMI_DIGEST_PMC_2_0_ROM_2_0
PMC2 ROM version 2 digest.
XPLMI_ROM_VERSION_1_0
ROM version 1.
XPLMI_ROM_VERSION_2_0
ROM version 2.
XPLMI_INVALID_ROM_VERSION
Invalid ROM version.
XPLMI_CFU_STREAM_2_SLR_OFFSET
SLR offset for CFU stream 2 register.
XPLMI_CFU_FDRO_2_SLR_OFFSET
SLR offset for CFU FDRO 2 register.
XPLMI_SLR1_CFU_FDRO_2_ADDR
SLR1 CFU FDRO 2 address.
XPLMI_SLR2_CFU_FDRO_2_ADDR
SLR2 CFU FDRO 2 address.
XPLMI_SLR3_CFU_FDRO_2_ADDR
SLR3 CFU FDRO 2 address.
XPLMI_SLR1_CFU_STREAM_2_ADDR
SLR1 CFU Stream 2 address.
XPLMI_SLR2_CFU_STREAM_2_ADDR
SLR2 CFU Stream 2 address.
XPLMI_SLR3_CFU_STREAM_2_ADDR
SLR3 CFU Stream 2 address.
XPLMI_PMC_VOLTAGE_MULTIPLIER
PMC voltage multiplier.
XPLMI_PMC_VERSION_1_0
PMC version 1.0.
XPlmi_GetRawVoltage
This macro converts voltage to raw voltage value.
Voltage is the voltage value in volts. 32-bit voltage value.
XPLMI_ERROR_TABLE_DS_VER
Error table data structure version.
XPLMI_ERROR_TABLE_DS_LCVER
Error table data structure LC version.
XPLMI_IS_PSMCR_CHANGED_VERSION
PSMCR changed version status.
XPLMI_IS_PSMCR_CHANGED_LCVERSION
PSMCR changed LC version status.
XPLMI_NUM_ERROUTS_VERSION
ERROUTS version.
XPLMI_NUM_ERROUTS_LCVERSION
ERROUTS LC version.
CPM5N_NCR_PCIE0_LINK_UP_EVENT_PROC_ID
CPM5N_NCR_PCIE0 linkup event procedure Id.
CPM5N_NCR_PCIE1_LINK_UP_EVENT_PROC_ID
CPM5N_NCR_PCIE1 linkup event procedure Id.
CPM5N_NCR_PCIE2_LINK_UP_EVENT_PROC_ID
CPM5N_NCR_PCIE2 linkup event procedure Id.
CPM5N_NCR_PCIE3_LINK_UP_EVENT_PROC_ID
CPM5N_NCR_PCIE3 linkup event procedure Id.
XPLMI_ROM_VERSION_1_0
ROM version 1.
XPLMI_SSSCFG_SHA0_MASK
SHA0 mask.
XPLMI_SSSCFG_SHA1_MASK
SHA1 mask.
XPLMI_SSSCFG_AES_MASK
AES mask.
XPLMI_SSS_SHA0_DMA0
SHA0 DMA0.
XPLMI_SSS_SHA0_DMA1
SHA0 DMA1.
XPLMI_SSS_SHA1_DMA0
SHA1 DMA0.
XPLMI_SSS_SHA1_DMA1
SHA1 DMA1.
XPLMI_SSS_AES_DMA0
AES DMA0.
XPLMI_SSS_AES_DMA1
AES DMA1.
XPLMI_LPDINITIALIZED_VER
LPD initialized version.
XPLMI_LPDINITIALIZED_LCVER
LPD initialized LC version.
XPLMI_UART_BASEADDR_VER
UART base address version.
XPLMI_UART_BASEADDR_LCVER
UART base address LC version.
XPLMI_TRACE_LOG_VERSION
Trace log version.
XPLMI_TRACE_LOG_LCVERSION
Trace log LC version.
XPLMI_BOARD_PARAMS_VERSION
Board parameters version.
XPLMI_BOARD_PARAMS_LCVERSION
Board parameters LC version.
XPLMI_XIOMODULE_VERSION
IOModule version.
XPLMI_XIOMODULE_LCVERSION
IOModule LC version.
XPLMI_PMC_VOLTAGE_MULTIPLIER
Voltage multiplier for Sysmon.
XPLMI_PMC_IRO_FREQ_233_MHZ
PMC IRO frequency 233Mhz.
XPLMI_PSM_BUFFER_DS_VER
PSM buffers Data structure version.
XPLMI_PSM_BUFFER_DS_LCVER
PSM buffers Data structure LC version.
XPLMI_PMC_BUFFER_DS_VER
PMC buffers Data structure version.
XPLMI_PMC_BUFFER_DS_LCVER
PMC buffers Data structure LC version.
XPLMI_PSM_BUFFER_LIST_DS_VER
PSM buffer list Data structure version.
XPLMI_PSM_BUFFER_LIST_DS_LCVER
PSM buffer list Data structure LC version.
XPLMI_PMC_BUFFER_LIST_DS_VER
PMC buffer list Data structure version.
XPLMI_PMC_BUFFER_LIST_DS_LCVER
PMC buffer list Data structure LC version.
XPLMI_BUFFER_PSM_SEND_API_ID
API Id.
XPLMI_BUFFER_PSM_SEND_API_ID_IDX
API Id index.
XPLMI_BUFFER_PSM_SEND_START_ADDR_IDX
Start address index.
XPLMI_BUFFER_PSM_SEND_END_ADDR_IDX
End address index.
XPLMI_BUFFER_PAYLOAD_ARG_CNT
Payload argument count.
IPI_MAX_TIMEOUT
IPI Max timeout ~5sec.
XPLMI_SCATTER_WRITE_PAYLOAD_LEN
Scatter write payload length.
Referenced by XPlmi_ScatterWrite.
XPLMI_SCATTER_WRITE2_PAYLOAD_LEN
Scatter write2 payload length.
Referenced by XPlmi_ScatterWrite2.
XPLMI_FIPS_WRITE_KATMASK_PAYLOAD_LEN
FIPS write KAT mask payload length.
Referenced by XPlmi_SetFipsKatMask.
XPLMI_MAX_ADDR_BUFFERS
Maximum address buffers.
Referenced by XPlmi_SetAddrBufferList.
XPLMI_MAX_ADDR_LIST_CNT
Maximum address list count.
Referenced by XPlmi_SetAddrBufferList.
XPLMI_LIST_ID_MASK
List Id mask.
Referenced by XPlmi_ListMaskPoll, XPlmi_ListMaskWrite, XPlmi_ListSet, XPlmi_ListWrite.
XPLMI_LIST_ID_SHIFT
List Id shift.
Referenced by XPlmi_ListMaskPoll, XPlmi_ListMaskWrite, XPlmi_ListSet, XPlmi_ListWrite.
XPLMI_ADDRESS_OFFSET_MASK
Address buffer offset mask.
Referenced by XPlmi_ListMaskPoll, XPlmi_ListMaskWrite, XPlmi_ListWrite.
XPLMI_LIST_ID_INDEX
List Id index.
Referenced by XPlmi_ListSet.
XPLMI_RESET_VECTOR
Reset vector.
XPLMI_ROM_PLM_UPDATE_REQ
ROM PLM update request.
PMX_PLM_UPDATE_REASON_MASK
PMX PLM update reason mask.
Referenced by XPlmi_UpdateInit.
XPLMI_ROM_INT_REASON_CLEAR
ROM initialize reason clear.
PLM_UPDATE_DONE_POLL_TIMEOUT
PLM update done POLL timeout.
XPLMI_UPDATE_DB_VERSION
DB version update.
Referenced by XPlmi_RestoreDataBackup.
XPLMI_DS_HDR_SIZE
Data structure header size.
Referenced by XPlmi_DsOps, XPlmi_RestoreDataBackup.
XPLMI_DS_CNT
Data structure count.
Referenced by XPlmi_RestoreDataBackup.
XPLMI_UPDATE_PDIADDR_VER
PDI Address version update.
XPLMI_UPDATE_PDIADDR_LCVER
PDI Address LC version update.
XPLMI_UPDATE_TASK_ID
Task Id update.
Referenced by XPlmi_PlmUpdate, XPlmi_UpdateInit.
XPLMI_UPDATE_FLAG_MASK
In-Place Update flag Mask.
Referenced by XPlmi_PlmUpdate.
XPLMI_UPDATE_PAYLOAD_LEN
In-Place Update payload len.
Referenced by XPlmi_PlmUpdate.
XPLMI_UPDATE_USING_IMAGE_STORE
In-Place Update using PDI in Image Store,1-DDR Location.
Referenced by XPlmi_PlmUpdate.
XPLMI_UPDATE_IN_PROGRESS
Update in progress.
Referenced by XPlmi_IsPlmUpdateInProgress, XPlmi_PlmUpdate.
XPLMI_UPDATE_DONE
Update done.
Referenced by XPlmi_IsPlmUpdateDone, XPlmi_IsPlmUpdateDoneTmp, XPlmi_UpdateInit.
XPLMI_INVALID_UPDATE_ADDR
Invalid update address.
XPLMI_UPDATE_TASK_DELAY
Update task delay.
XPLMI_WDT_PERIODICITY
WDT periodicity.
XPLMI_SCHEDULER_PERIOD
Scheduler period.
Referenced by XPlmi_WdtHandler.
XPLMI_WDT_PERIODICITY_MIN
Minimum WDT periodicity.
Referenced by XPlmi_EnableWdt, XPlmi_WdtHandler.
XPLMI_WDT_PERIODICITY_MAX
Maximum WDT periodicity.
Referenced by XPlmi_EnableWdt.
XPLMI_SPP_WDT_PERIODICITY_MIN
SPP minimum WDT periodicity.
XPLMI_MIO_NUM_PER_BANK
Number of MIO per bank.
Referenced by XPlmi_EnableWdt.
XPLMI_PM_STMIC_LMIO_0
PM STMIC LMIO_0.
Referenced by XPlmi_EnableWdt.
XPLMI_PM_STMIC_LMIO_25
PM STMIC LMIO_25.
Referenced by XPlmi_EnableWdt.
XPLMI_PM_STMIC_PMIO_0
PM STMIC PMIO_0.
Referenced by XPlmi_EnableWdt.
XPLMI_PM_STMIC_PMIO_51
PM STMIC PMIO_51.
Referenced by XPlmi_EnableWdt.
XPLMI_PM_DEV_PMC_WDT
PM DEV PMC WDT.
Referenced by XPlmi_DefaultSWdtConfig.