xilplmi_client_apis
int XPlmi_GetDeviceID(XPlmi_ClientInstance *InstancePtr, XLoader_DeviceIdCode *DeviceIdCode)
This function sends IPI request to provides Get device id.
InstancePtr Pointer to the client instance DeviceIdCode used to store the Id code register values. XST_SUCCESS on success.XST_FAILURE on failure.
References PAYLOAD_ARG_CNT, RESPONSE_ARG_CNT, XPLMI_GET_DEVICE_CMD_ID, XPlmi_SendRequest.
int XPlmi_GetBoard(XPlmi_ClientInstance *InstancePtr, u64 Addr, u32 Size, u32 *ResponseLength)
This function sends IPI request to Get board.
InstancePtr Pointer to the client instance Addr Address where PLM has to copy the board details Size Max size available at destination for PLM to copy in words ResponseLength Length of board data that PLM copied XST_SUCCESS on success.XST_FAILURE on failure.
References PAYLOAD_ARG_CNT, RESPONSE_ARG_CNT, XPLMI_ADDR_HIGH_SHIFT, XPLMI_GET_BOARD_CMD_ID, XPlmi_SendRequest.
int XPlmi_TamperTrigger(XPlmi_ClientInstance *InstancePtr, u32 TamperResponse)
This function sends IPI request to Tamper Trigger.
InstancePtr Pointer to the client instance TamperResponse To select the valid tamper response Handoff to the Rom on success.XST_FAILURE on failure.
References PAYLOAD_ARG_CNT, XPlmi_SendRequest, XPLMI_TAMPER_TRIGGER_CMD_ID.
int XPlmi_EventLogging(XPlmi_ClientInstance *InstancePtr, u32 sub_cmd, u64 Arg, u32 Len)
This function sends IPI request to Event Logging.
InstancePtr Pointer to the client instance sub_cmd To configure the debug information Arg Arguments to be passed for the sub command, for all sub commands Arg holds Address, whereas uart sub command Arg holds Arg1, Arg2 in upper and lower 32bit respectively Len Length of the buffer XST_SUCCESS on success.XST_FAILURE on failure.
References PAYLOAD_ARG_CNT, RESPONSE_ARG_CNT, XPlmi_ClientInstance::SlrIndex, XPLMI_ADDR_HIGH_SHIFT, XPLMI_EVENT_LOGGING_CMD_ID, XPlmi_SendRequest, XPLMI_SLR_INDEX_SHIFT.
int XPlmi_ConfigSecureComm(XPlmi_ClientInstance *InstancePtr, XPlmi_SsitSecComm *SsitSecCommDataPtr)
This function sends IPI request to configure secure communication.
InstancePtr Pointer to the client instance SsitSecCommDataPtr Pointer to structure which contains SLR index, IV1, IV2 and key XST_SUCCESS on success.XST_FAILURE on failure.
References PAYLOAD_ARG_CNT, XPLMI_ADDR_HIGH_SHIFT, XPLMI_CONFIG_SECCOMM_CMD_ID, XPlmi_SendRequest.
int XPlmi_GetSecureCommStatus(XPlmi_ClientInstance *InstancePtr, u32 SlrIndex, u32 *SecCommStatus)
This function sends IPI request to get secure communication status.
InstancePtr Pointer to the client instance SlrIndex SLR number for which secure communication establishment status is needed SecCommStatus Pointer to variable to which secure communication status is to be written XST_SUCCESS on success.XST_FAILURE on failure.
References PAYLOAD_ARG_CNT, RESPONSE_ARG_CNT, XPLMI_GETSECCOMM_STATUS_CMD_ID, XPlmi_SendRequest.
int XPlmi_SetDDRMCMainRegSts(XPlmi_ClientInstance *InstancePtr, u32 DDRMCNum, u32 RegSts)
This function sends IPI request to set DDRMC main registers status command.
InstancePtr Pointer to the client instance DDRMCNum DDRMC number RegSts To be set status XST_SUCCESS on success.XST_FAILURE on failure.
References PAYLOAD_ARG_CNT, XPLMI_DDRMC_MAINREG_STS_SET_CMD_ID, XPlmi_SendRequest.
int XPlmi_InputSlrIndex(XPlmi_ClientInstance *InstancePtr, u32 SlrIndex)
Adds the SLR Index.
InstancePtr is a pointer to instance XPlmi_ClientInstance SlrIndex - SLR index number - XST_SUCCESS - On valid input SlrIndex. XST_FAILURE - On non valid input SlrIndex
References XPlmi_ClientInstance::SlrIndex, XPLMI_SLR_INDEX_3.
int XPlmi_SendRequest(XPlmi_ClientInstance *InstancePtr, u32 *PayloadBuf, u32 PayloadLen, u32 *ResponseBuf, u32 ResponseLen)
This function sends request to PLM through either SMC or IPI mailbox based on the execution environment.
For EL1 non-secure AArch64 applications, SMC is used. For other environments, IPI mailbox is used. InstancePtr Pointer to the client instance (used for mailbox, can be NULL for SMC) PayloadBuf Pointer to payload buffer containing command and arguments PayloadLen Length of payload buffer (number of u32 elements) ResponseBuf Pointer to store response values (can be NULL if response not needed) ResponseLen Length of response buffer (number of u32 elements) XST_SUCCESS on success.XST_FAILURE on failure.XST_INVALID_PARAM If input parameters are invalid This is a generic API that internally handles SMC or Mailbox communication based on the build configuration.
References XPlmi_ClientInstance::MailboxPtr, XPlmi_ClientInstance::Response, RESPONSE_ARG_CNT, XPlmi_ProcessMailbox.
Referenced by XPlmi_ConfigSecureComm, XPlmi_EventLogging, XPlmi_GetBoard, XPlmi_GetDeviceID, XPlmi_GetSecureCommStatus, XPlmi_SetDDRMCMainRegSts, XPlmi_TamperTrigger.
int XPlmi_WriteReg32(u32 Offset, u32 Data)
Writes value to register.
Offset Offset of the register Data Value to be written in register XST_SUCCESS on success error code on failure
static int XPlmi_UpdateReg32(u32 Offset, u32 Mask, u32 Data)
Updates register value.
Offset Offset address of the register Mask Bits to be masked Data value to be written XST_SUCCESS on success error code on failure
int XPlmi_ReadReg32(u32 Offset, u32 *Data)
Reads register value.
Offset Offset of the register. Data Value to be read. XST_SUCCESS on success error code on failure
int XPlmi_ConfigureGlitchDetector(u8 Depth, u8 Width, u8 RefVoltage, u8 UserRegVal, u8 GlitchDetectorNum)
This function configures desired glitch detector.
Depth is the minimum voltage glitch detection depth Width is the minimum glitch detector width RefVoltage is the reference voltage for the glitch detector comparators UserRegVal indicates to select the register values instead of the eFUSE values to configure the glitch detector GlitchDetectorNum is the number of glitch detector to be configured XST_SUCCESS on success.error code on failure.
int XPlmi_ChangeGlitchDetectorState(u8 GlitchDetectorNum, eStatus EnableStatus)
This function enables/disables the desired glitch detector.
GlitchDetectorNum is the number of glitch detector to be enabled/disabled EnableStatus indicates action i.e., enable/disable XST_SUCCESS on success.error code on failure.
int XPlmi_GlitchDetectorStatus(u8 GlitchDetectorNum, u8 *GlitchDetStatus)
This function reads the status of desired glitch detector.
GlitchDetectorNum is the number of glitch detector whose status is to be read GlitchDetStatus holds the status Status of glitch detector
static int XPlmi_InPlaceAsuUpdate(XPlmi_ClientInstance *InstancePtr, const u32 Flag, u32 PdiValue)
This function sends IPI request to perform in-place ASU update.
InstancePtr Pointer to XPlmi_ClientInstance Flag Update flag (0 = use Image Store, 1 = use DDR) PdiValue PDI ID (Image Store) or DDR address XST_SUCCESS on success.XST_FAILURE on failure.
int XPlmi_InPlaceAsuUpdate_DDR(XPlmi_ClientInstance *Ptr, const u32 Flag, u32 DDRAddr)
This function sends IPI request to perform in-place ASU update from DDR.
Ptr Pointer to XPlmi_ClientInstance Flag Update flag (should be 1 for DDR source) DDRAddr Address of update PDI in DDR XST_SUCCESS on success.XST_FAILURE on failure.
int XPlmi_InPlaceAsuUpdate_ImageStore(XPlmi_ClientInstance *Ptr, const u32 Flag, u32 PdiId)
This function sends IPI request to perform in-place ASU update from Image Store.
Ptr Pointer to XPlmi_ClientInstance Flag Update flag (should be 0 for Image Store source) PdiId Image store PDI ID XST_SUCCESS on success.XST_FAILURE on failure.
static int XPlmi_InPlacePlmUpdate(XPlmi_ClientInstance *InstancePtr, const u32 Flag, u32 PdiValue)
This function sends IPI request to perform in-place PLM update.
InstancePtr Pointer to XPlmi_ClientInstance Flag To enable / disable jtag PdiValue To select the pdi src XST_SUCCESS on success.XST_FAILURE on failure.
int XPlmi_InPlacePlmUpdate_DDR(XPlmi_ClientInstance *Ptr, const u32 Flag, u32 DDRAddr)
This function sends IPI request to perform in-place PLM update from DDR.
Ptr Pointer to XPlmi_ClientInstance Flag To enable / disable jtag DDRAddr Address of DDR XST_SUCCESS on success.XST_FAILURE on failure.
References XPlmi_InPlacePlmUpdate.
int XPlmi_InPlacePlmUpdate_ImageStore(XPlmi_ClientInstance *Ptr, const u32 Flag, u32 PdiId)
This function sends IPI request to perform in-place PLM update from Image Store.
Ptr Pointer to XPlmi_ClientInstance Flag To enable / disable jtag PdiId Image store pdi id XST_SUCCESS on success.XST_FAILURE on failure.
References XPlmi_InPlacePlmUpdate.
XPLMI_ADDR_HIGH_SHIFT
Shift value to get higher 32 bit address.
Referenced by XPlmi_ConfigSecureComm, XPlmi_EventLogging, XPlmi_GetBoard.
XPLMI_REFVOL_3LSBITS_MASK
Mask to extract 3 least significant bits from reference voltage.
XPLMI_DEPTH_3LSBITS_MASK
Mask to extract 3 least significant bits from depth.
XPLMI_REFVOL_MSBIT_MASK
Mask to extract most significant bit from reference voltage.
XPLMI_DEPTH_2MSBITS_MASK
Mask to extract 2 most significant bits from depth.
XPLMI_REFVOL_MSBIT_SHIFT
Shift value to place most significant bit of reference voltage.
XPLMI_REFVOL_3LSBITS_SHIFT
Shift value to place 3 least significant bits of reference voltage.
XPLMI_DEPTH_2MSBITS_SHIFT
Shift value to place 2 most significant bits of depth.
XPLMI_DEPTH_3LSBITS_SHIFT
Shift value to place 3 least significant bits of depth.
XPLMI_WIDTH_BITS_SHIFT
Shift value to place bits of width.
XPLMI_WORD_LEN
Word size in bytes.
Referenced by XPlmi_DmaTransfer, XPlmi_DsOps, XPlmi_EccInit, XPlmi_InitNVerifyMem, XPlmi_MemCpy64, XPlmi_MemSet, XPlmi_MemSetBytes, XPlmi_MoveBuffer, XPlmi_PrintArray, XPlmi_PsmSequence, XPlmi_RestoreDataBackup, XPlmi_ScatterWrite2, XPlmi_SearchBufferList, XPlmi_StoreBuffer.
XPLMI_GD1_STATUS_POS
Bit position of glitch detector1 status.