net/server/xplmi_plat.h
XPLMI_PLM_BANNER
PLM banner.
XPLMI_PLM_PLAT_RC_VERSION
PLM Plat RC Version.
XPLMI_PLM_USER_DEFINED_VERSION
PLM User Defined Version.
XPLMI_MAX_PSM_BUFFERS
Maximum PSM Buffers.
XPLMI_MAX_PMC_BUFFERS
Maximum PMC Buffers.
XPLMI_RTCFG_BASEADDR
Runtime configuration base address.
XPLMI_RTCFG_PMC_ERR1_STATUS_ADDR
PMC error 1 status address.
XPLMI_RTCFG_PSM_ERR1_STATUS_ADDR
PSM error 1 status address.
XPLMI_RTCFG_PMC_ERR3_STATUS_ADDR
PMC error 3 status address.
XPLMI_RTCFG_PSM_ERR3_STATUS_ADDR
PSM error 3 status address.
XPLMI_RTCFG_SECURE_STATE_PLM_ADDR
Secure state PLM address.
XPLMI_RTCFG_PLM_CRYPTO_STATUS_ADDR
PLM crypto status address.
XPLMI_RTCFG_IMG_STORE_ADDRESS_HIGH
Image store address high.
XPLMI_RTCFG_IMG_STORE_ADDRESS_LOW
Image store address low.
XPLMI_RTCFG_IMG_STORE_SIZE
Image store size.
XPLMI_RTCFG_SECURE_DDR_KAT_ADDR
Secure DDR KAT address.
XPLMI_RTCFG_SECURE_HNIC_CPM5N_PCIDE_KAT_ADDR
Secure HNIC CPM5N PCIDE KAT address.
XPLMI_RTCFG_SECURE_PKI_KAT_ADDR_0
Secure PKI KAT address 0.
XPLMI_RTCFG_SECURE_PKI_KAT_ADDR_1
Secure PKI KAT address 1.
XPLMI_RTCFG_SECURE_PKI_KAT_ADDR_2
Secure PKI KAT address 2.
XPLMI_RTCFG_PLM_RSVD_DDR_ADDR
Baseadress of DDR region reserved for PLM.
XPLMI_RTCFG_PLM_RSVD_DDR_SIZE
Size of DDR region reserved for PLM.
XPLMI_RTCFG_VID_OVERRIDE
VID override.
XPLMI_RTCFG_INPLACE_UPDATE_IPI_MASK
RTCA register to save IPI Mask.
XPLMI_RTCFG_INPLACE_UPDATE_IPI_RESP_BUFF
RTCA Register to save response buffer address.
XPLMI_RTCFG_INPLACE_UPDATE_ERR_IPOR_TIMEOUT
RTCA Register to store timeout in milli seconds before IPOR.
XPLMI_RTCFG_DDRMC_CALIB_CHECK_SKIP_ADDR
Skip DDRMC Calib Check.
XPLMI_INVALID_RESP_BUFF_ADDR
Invalid Response Buffer Address.
XPLMI_INVALID_IPI_MASK
Invalid IPI Mask.
XPLMI_INVALID_PLM_RSVD_DDR_ADDR
Invalid reserved DDR address.
XPLMI_INVALID_PLM_RSVD_DDR_SIZE
Invalid reserved DDR size.
XPLMI_REG_OFFSET_BYTE_4
Register Offset by 4 bytes.
XPLMI_LPD_DOMAIN_INIT_MASK
LPD Domain Init Status.
XPLMI_ROM_SERVICE_TIMEOUT
ROM service timeout.
XPLMI_MILLI_SEC_TIME_MULTIPLIER
factor for ~1msec for 320MHz to 400MHz range
XPLMI_PMC_IRO_FREQ_320_MHZ
PMC IRO frequency 320Mhz.
XPLMI_WDT_DS_ID
WDT data structure Id.
XPLMI_TRACELOG_DS_ID
Trace log data structure Id.
XPLMI_LPDINITIALIZED_DS_ID
LPD initialized data structure Id.
XPLMI_RESERVED_DS_ID
Update RESERVED DS ID.
XPLMI_UART_BASEADDR_DS_ID
UART base address data structure Id.
XPLMI_ERROR_TABLE_DS_ID
Error table data structure Id.
XPLMI_IS_PSMCR_CHANGED_DS_ID
PSMCR status check data structure Id.
XPLMI_NUM_ERROUTS_DS_ID
Number of error outs data structure Id.
XPLMI_BOARD_PARAMS_DS_ID
Board parameters data structure Id.
XPLMI_PSM_BUFFER_DS_ID
PSM Buffers data structure Id.
XPLMI_PMC_BUFFER_DS_ID
PMC Buffers data structure Id.
XPLMI_UPDATE_PDIADDR_DS_ID
Update IPI mask data structure Id.
XPLMI_XIOMODULE_DS_ID
IOModule data structure Id.
XPLMI_PSM_BUFFER_LIST_DS_ID
PSM Buffers data structure Id.
XPLMI_PMC_BUFFER_LIST_DS_ID
PMC Buffers data structure Id.
XPLMI_SSIT_MONOLITIC
SSIT monolitic.
XPLMI_SSIT_MASTER_SLR
SSIT master SLR.
XPLMI_SSIT_SLAVE0_SLR_TOP
Slave0 SLR Top.
XPLMI_SSIT_SLAVE0_SLR_NTOP
Slave0 SLR NTop.
XPLMI_SSIT_SLAVE1_SLR_TOP
Slave1 SLR Top.
XPLMI_SSIT_SLAVE1_SLR_NTOP
Slave1 SLR NTop.
XPLMI_SSIT_SLAVE2_SLR_TOP
Slave2 SLR Top.
XPLMI_SSIT_INVALID_SLR
Invalid SLR.
XPLMI_GICP_SOURCE_COUNT
GICP source count.
XPLMI_GICP_INDEX_SHIFT
GICP index shift.
XPLMI_GICPX_INDEX_SHIFT
GICPX index shift.
XPLMI_GICPX_LEN
GICPX length.
XPLMI_PMC_GIC_IRQ_GICP0
GICP0 Interrupt.
XPLMI_PMC_GIC_IRQ_GICP1
GICP1 Interrupt.
XPLMI_PMC_GIC_IRQ_GICP2
GICP2 Interrupt.
XPLMI_PMC_GIC_IRQ_GICP3
GICP3 Interrupt.
XPLMI_PMC_GIC_IRQ_GICP4
GICP4 Interrupt.
XPLMI_PMC_GIC_IRQ_GICP5
GICP5 Interrupt.
XPLMI_PMC_GIC_IRQ_GICP6
GICP6 Interrupt.
XPLMI_GICP0_SRC20
GPIO Interrupt.
XPLMI_GICP0_SRC21
I2C_0 Interrupt.
XPLMI_GICP0_SRC22
I2C_1 Interrupt.
XPLMI_GICP0_SRC23
SPI_0 Interrupt.
XPLMI_GICP0_SRC24
SPI_1 Interrupt.
XPLMI_GICP0_SRC25
UART_0 Interrupt.
XPLMI_GICP0_SRC26
UART_1 Interrupt.
XPLMI_GICP0_SRC27
CAN_0 Interrupt.
XPLMI_GICP0_SRC28
CAN_1 Interrupt.
XPLMI_GICP0_SRC29
USB_0 Interrupt.
XPLMI_GICP0_SRC30
USB_0 Interrupt.
XPLMI_GICP0_SRC31
USB_0 Interrupt.
XPLMI_GICP1_SRC0
USB_0 Interrupt.
XPLMI_GICP1_SRC1
USB_0 Interrupt.
XPLMI_GICP1_SRC2
USB_1 Interrupt.
XPLMI_GICP1_SRC3
USB_1 Interrupt.
XPLMI_GICP1_SRC4
USB_1 Interrupt.
XPLMI_GICP1_SRC5
USB_1 Interrupt.
XPLMI_GICP1_SRC6
USB_1 Interrupt.
XPLMI_GICP1_SRC7
GEM_0 Interrupt.
XPLMI_GICP1_SRC8
GEM_0 Interrupt.
XPLMI_GICP1_SRC9
GEM_1 Interrupt.
XPLMI_GICP1_SRC10
GEM_1 Interrupt.
XPLMI_GICP1_SRC11
TTC_0 Interrupt.
XPLMI_GICP1_SRC12
TTC_0 Interrupt.
XPLMI_GICP1_SRC13
TTC_0 Interrupt.
XPLMI_GICP1_SRC14
TTC_1 Interrupt.
XPLMI_GICP1_SRC15
TTC_1 Interrupt.
XPLMI_GICP1_SRC16
TTC_1 Interrupt.
XPLMI_GICP1_SRC17
TTC_2 Interrupt.
XPLMI_GICP1_SRC18
TTC_2 Interrupt.
XPLMI_GICP1_SRC19
TTC_2 Interrupt.
XPLMI_GICP1_SRC20
TTC_3 Interrupt.
XPLMI_GICP1_SRC21
TTC_3 Interrupt.
XPLMI_GICP1_SRC22
TTC_3 Interrupt.
XPLMI_GICP2_SRC8
ADMA_0 Interrupt.
XPLMI_GICP2_SRC9
ADMA_1 Interrupt.
XPLMI_GICP2_SRC10
ADMA_2 Interrupt.
XPLMI_GICP2_SRC11
ADMA_3 Interrupt.
XPLMI_GICP2_SRC12
ADMA_4 Interrupt.
XPLMI_GICP2_SRC13
ADMA_5 Interrupt.
XPLMI_GICP2_SRC14
ADMA_6 Interrupt.
XPLMI_GICP2_SRC15
ADMA_7 Interrupt.
XPLMI_GICP3_SRC2
USB_0 Interrupt.
XPLMI_GICP3_SRC3
USB_1 Interrupt.
XPLMI_GICP5_SRC22
OSPI Interrupt.
XPLMI_GICP5_SRC23
QSPI Interrupt.
XPLMI_GICP5_SRC24
SD_0 Interrupt.
XPLMI_GICP5_SRC25
SD_0 Interrupt.
XPLMI_GICP5_SRC26
SD_1 Interrupt.
XPLMI_GICP5_SRC27
SD_1 Interrupt.
XPLMI_GICP6_SRC1
SBI Interrupt.
XPLMI_SBI_GICP_INDEX
SBI GICP index.
XPLMI_SBI_GICPX_INDEX
SBI GICPX index.
XPLMI_IPI_INTR_ID
IPI interrupt Id.
XPLMI_IPI_INDEX_SHIFT
IPI shift index.
XPLMI_HW_INT_GIC_IRQ
GIC hardware interrupt.
XPLMI_HW_SW_INTR_MASK
Hardware / software interrupt mask.
XPLMI_HW_SW_INTR_SHIFT
Shift hardware / software interrupt.
XPLMI_PLM_GENERIC_PLMUPDATE
Generic PLM update.
XPLMI_MODULE_NO_OPERATION
No operation.
XPLMI_MODULE_SHUTDOWN_INITIATE
Shutdown initiate.
XPLMI_MODULE_SHUTDOWN_COMPLETE
Shutdown complete.
XPLMI_MODULE_SHUTDOWN_ABORT
Shutdown abort.
XPLMI_MODULE_NORMAL_STATE
Normal state.
XPLMI_MODULE_SHUTDOWN_INITIATED_STATE
Shutdown initiated state.
XPLMI_MODULE_SHUTDOWN_COMPLETED_STATE
Shutdown completed state.
XPlmi_SsitSyncMaster
SSIT sync master.
XPlmi_SsitSyncSlaves
SSIT sync slaves.
XPlmi_SsitWaitSlaves
SSIT wait slaves.
XPlmi_SsitCfgSecComm
SSIT configure secure communication.
XPlmi_GetSsitSecCommStatus
SSIT get secure communication status.
MAX_DEV_DDRMC
Maximum device for Double Data Rate Memory Controller.
XPLMI_DDRMC_UB0_BASE_ADDR
DDRMC_UB0 base address.
XPLMI_DDRMC_UB1_BASE_ADDR
DDRMC_UB1 base address.
XPLMI_DDRMC_UB2_BASE_ADDR
DDRMC_UB2 base address.
XPLMI_DDRMC_UB3_BASE_ADDR
DDRMC_UB3 base address.
XPLMI_DDRMC_UB4_BASE_ADDR
DDRMC_UB4 base address.
XPLMI_DDRMC_UB5_BASE_ADDR
DDRMC_UB2 base address.
XPLMI_DDRMC_UB6_BASE_ADDR
DDRMC_UB3 base address.
XPLMI_DDRMC_UB7_BASE_ADDR
DDRMC_UB4 base address.
XPLMI_DDRMC_UB_PCSR_LOCK_OFFSET
Offset of PCSR register.
XPLMI_DDRMC_UB_PMC2UB_INFO_OFFSET
Offset of PMC2UBInfo register.
XPLMI_SECURE_SHA3_KAT_MASK
SHA3 Instance0 KAT mask.
XPLMI_SECURE_RSA_KAT_MASK
RSA KAT mask.
XPLMI_SECURE_ECC_SIGN_VERIFY_SHA3_384_KAT_MASK
ECC sign verify SHA3_384 KAT mask.
XPLMI_SECURE_AES_DEC_KAT_MASK
AES decrypt KAT mask.
XPLMI_SECURE_AES_CMKAT_MASK
AES CMKAT mask.
XPLMI_SECURE_TRNG_KAT_MASK
TRNG KAT mask.
XPLMI_SECURE_SHA384_KAT_MASK
SHA384 KAT mask.
XPLMI_SECURE_AES_ENC_KAT_MASK
AES encrypt KAT mask.
XPLMI_SECURE_HMAC_KAT_MASK
HMAC KAT mask.
XPLMI_SECURE_RSA_PRIVATE_DEC_KAT_MASK
RSA private decrypt KAT mask.
XPLMI_SECURE_ECC_SIGN_GEN_SHA3_384_KAT_MASK
ECC sign generation SHA3_384 KAT mask.
XPLMI_SECURE_ECC_PWCT_KAT_MASK
PWCT KAT mask.
XPLMI_SECURE_ECC_DEVIK_PWCT_KAT_MASK
DEVIK PWCT KAT mask.
XPLMI_SECURE_ECC_DEVAK_PWCT_KAT_MASK
DEVAK PWCT KAT mask.
XPLMI_SECURE_SHA3_1_KAT_MASK
SHA3 Instance1 KAT mask.
XPLMI_SECURE_FIPS_STATE_MASK
FIPS state mask.
XPLMI_ROM_KAT_MASK
ROM KAT mask.
XPLMI_KAT_MASK
KAT mask.
XPLMI_DDR_0_KAT_MASK
DDR 0 KAT mask.
XPLMI_DDR_1_KAT_MASK
DDR 1 KAT mask.
XPLMI_DDR_2_KAT_MASK
DDR 2 KAT mask.
XPLMI_DDR_3_KAT_MASK
DDR 3 KAT mask.
XPLMI_DDR_4_KAT_MASK
DDR 4 KAT mask.
XPLMI_DDR_5_KAT_MASK
DDR 5 KAT mask.
XPLMI_DDR_6_KAT_MASK
DDR 6 KAT mask.
XPLMI_DDR_7_KAT_MASK
DDR 7 KAT mask.
XPLMI_HNIC_KAT_MASK
HNIC KAT mask.
XPLMI_CPM5N_KAT_MASK
CPM5N KAT mask.
XPLMI_PCIDE_KAT_MASK
PCIDE KAT mask.
XPLMI_HNIC_CPM5N_PCIDE_KAT_MASK
HNIC CPM5N PCIDE KAT mask.
XPLMI_PKI_KAT_MASK
PKI KAT mask.
XPLMI_SECURE_AES_MASK
AES mask.
XPLMI_SECURE_RSA_MASK
RSA mask.
XPLMI_SECURE_ECDSA_MASK
ECDSA mask.
XPLMI_SECURE_SHA3_384_MASK
SHA3_384 mask.
XPLMI_SECURE_TRNG_MASK
TRNG mask.
XPLMI_SECURE_HNIC_AES_MASK
HNIC AES mask.
XPLMI_SECURE_CPM5N_AES_MASK
CPM5N AES mask.
XPLMI_SECURE_PCIDE_AES_MASK
PCIDE AES mask.
XPLMI_SECURE_PKI_RSA_MASK
PKI RSA mask.
XPLMI_SECURE_PKI_ECC_MASK
PKI ECC mask.
XPLMI_SECURE_PKI_SHA2_MASK
PKI SHA2 mask.
XPLMI_SECURE_PKI_CRYPTO_MASK
PKI crypto mask.
XPLMI_PLM_CRYPTO_MASK
PLM crypto mask.
GET_RTCFG_PMC_ERR_ADDR
Runtime configuration PMC error address.
GET_RTCFG_PSM_ERR_ADDR
Runtime configuration PSM error address.
XPLMI_STATUS_GLITCH_DETECT
Glitch check on Status.
Function pointer type for address range validation handler
VERIFY_ADDR_DEBUG_PRINT
XPLMI_VERIFY_ADDR_RANGE
This macro calls the registered address validation handler (XPm_IsMemAddressValid) to ensure memory access is within valid bounds for security-critical functions.
Also adds redundancy to XPm_IsMemAddressValid function if PLM_ENABLE_VERIFY_ADDR_REDUNDANT_CALL is defined, this is to avoid glitches from altering the return values of security critical functions. SubsysId Subsystem ID StartAddr Start address of the range to verify Len Length of the address range to verify StatusVar Status variable to be updated ErrorCode Error code to set on failure Label Label to jump to on error None
@4
0x1 - XPLMI_ERR_FAILURE
XPlmi_RomIntr
DME channel signature generation.
typedef int(* XPlmi_UpdateHandler_t)(XPlmi_ModuleOp Op))(XPlmi_ModuleOp Op)
typedef XStatus(* XPlmi_IsAddrRangeValid_t)(u32 SubsystemId, u64 Addr, u64 Size))(u32 SubsystemId, u64 Addr, u64 Size)
Global address range validation handler.
XPlmi_IsAddrRangeValid_t XPlmi_IsAddrRangeValid
< Global address range validation handler
Referenced by XPlmi_Init.
static u8 XPlmi_GetSlrType(void)
This function provides the Slr Type.
SlrType
static void XPlmi_DisableCFrameIso(void)
This function Disables CFRAME Isolation.
static void XPlmi_EnableIpiIntr(void)
This function provides Iomodule instance pointer.
Pointer to Iomodule instance
static void XPlmi_ClearIpiIntr(void)
This function clears IPI interrupt.
static void XPlmi_NotifySldSlaveSlrs(void)
This function is not applicable for Versal Net.
static void XPlmi_InterSlrSldHandshake(void)
This function is not applicable for Versal Net.
static void XPlmi_AckIpi(u32 PlmErr, u32 RomErr)
This function sets ACK's the IPI request.
PlmErr value of Plm error RomErr value of ROM error
static void XPlmi_IpuErrIporWait(void)
This function waits for specified timeout before doing IPOR.
u32* XPlmi_GetLpdInitialized(void)
This function provides LpdInitialized variable pointer.
Pointer to LpdInitialized variable Pointer to LpdInitialized variable.
Referenced by XPlmi_ResetLpdInitialized, XPlmi_SetLpdInitialized, XPlmi_UnSetLpdInitialized.
int XPlmi_PreInit(void)
This function performs plmi pre-initializaton.
Reset reason status. XST_SUCCESS always.
Referenced by XPlmi_Init.
void XPlmi_RtcaPlatInit(void)
This function performs initialization of platform specific RCTA registers.
Referenced by XPlmi_RunTimeConfigInit.
u8 XPlmi_IsPlmUpdateDone(void)
This function checks if Inplace PLM update occurs or not.
TRUE if Inplace PLM Update and FALSE otherwise
References XPLMI_UPDATE_DONE.
u8 XPlmi_IsPlmUpdateDoneTmp(void)
This function checks if Inplace PLM update occurs or not.
TRUE if Inplace PLM Update and FALSE otherwise
References XPLMI_UPDATE_DONE.
u8 XPlmi_IsPlmUpdateInProgress(void)
This function checks if Inplace PLM update is in progress or not.
TRUE if Inplace PLM Update is in progress and FALSE otherwise
References XPLMI_UPDATE_IN_PROGRESS.
void XPlmi_SssMask(u32 DmaSrc)
This function masks the secure stream switch value.
DmaSrc - DMA0 or DMA1 DmaSrc DMA0 or DMA1.
XPlmi_CircularBuffer* XPlmi_GetTraceLogInst(void)
This function provides TraceLog instance.
Pointer to TraceLog variable Pointer to TraceLog variable.
Referenced by XPlmi_EventLogging.
void XPlmi_GetReadbackSrcDest(u32 SlrType, u64 *SrcAddr, u64 *DestAddrRead)
This function processes and provides SrcAddr and DestAddr for cfi readback.
SlrType is the type of Slr passed in readback cmd SrcAddr is the pointer to the SrcAddr variable DestAddrRead is the pointer to the DestAddrRead variable SlrType is the type of Slr passed in readback cmd. SrcAddr is the pointer to the SrcAddr variable. DestAddrRead is the pointer to the DestAddrRead variable.
References XPLMI_SLR1_CFU_FDRO_2_ADDR, XPLMI_SLR1_CFU_STREAM_2_ADDR, XPLMI_SLR2_CFU_FDRO_2_ADDR, XPLMI_SLR2_CFU_STREAM_2_ADDR, XPLMI_SLR3_CFU_FDRO_2_ADDR, XPLMI_SLR3_CFU_STREAM_2_ADDR.
int XPlmi_GenericHandler(XPlmi_ModuleOp Op)
This function is used for shutdown operation before In-place PLM Update.
Op is the operation information XST_SUCCESS on success and XST_FAILURE on failure
References XPLMI_MODULE_NORMAL_STATE, XPLMI_MODULE_SHUTDOWN_INITIATE, XPLMI_MODULE_SHUTDOWN_INITIATED_STATE, XPLMI_MODULE_SHUTDOWN_COMPLETE, XPLMI_MODULE_SHUTDOWN_COMPLETED_STATE, XPLMI_RTCFG_SECURE_STATE_PLM_ADDR, EmDisableErrAction, GET_PMC_IRQ_MASK, GET_PMC_ERR_ACTION_OFFSET, XPlmi_EmDisableLpdSlcrErrors, XPlmi_PlmIntrDisable, XPlmi_GicIntrClearStatus, XPLMI_SBI_GICP_INDEX, XPLMI_SBI_GICPX_INDEX, XPlmi_PlmIntrClear, XPLMI_MODULE_SHUTDOWN_ABORT.
void XPlmi_GicAddTask(u32 PlmIntrId)
This will add the GIC interrupt task handler to the TaskQueue.
PlmIntrId is the GIC interrupt ID of the task PlmIntrId is the GIC interrupt ID of the task.
References XPlmi_GicIntrAddTask, XPlmi_GetIpiIntrId.
Referenced by XPlmi_GicIntrHandler.
int XPlmi_RegisterNEnableIpi(void)
This function registers and enables IPI interrupt.
XST_SUCCESS on success and XST_FAILURE on failure XST_SUCCESS on success and XST_FAILURE on failure XST_SUCCESS on success.XST_FAILURE on failure.
void XPlmi_EnableIomoduleIntr(void)
This function registers and enables IPI interrupt.
Referenced by XPlmi_SetUpInterruptSystem.
int XPlmi_SetPmcIroFreq(void)
It sets the PMC IRO frequency.
This functions sets the PMC IRO frequency. XST_SUCCESS on success and error code failure - XST_SUCCESS on success XST_FAILURE on failure XST_SUCCESS on success.Error code failure.
Referenced by XPlmi_StartTimer.
XInterruptHandler* XPlmi_GetTopLevelIntrTbl(void)
This function provides pointer to g_TopLevelInterruptTable.
Pointer to g_TopLevelInterruptTable structure Pointer to g_TopLevelInterruptTable structure.
Referenced by XPlmi_SetUpInterruptSystem.
u8 XPlmi_GetTopLevelIntrTblSize(void)
This function provides size of g_TopLevelInterruptTable.
Size g_TopLevelInterruptTable structure Size g_TopLevelInterruptTable structure.
Referenced by XPlmi_SetUpInterruptSystem.
XPlmi_WaitForDmaDone_t XPlmi_GetPlmiWaitForDone(u64 DestAddr)
This function is used to check and wait for DMA done when sending data to SSIT Slave SLRs.
This function is used to check and wait for DMA done. DestAddr holds the address of the destination buffer XST_SUCCESS on success and error code on failure DestAddr is the address of destination XST_SUCCESS on success and error code on failure DestAddr holds the address of the destination buffer. XST_SUCCESS on success.Error code on failure.
Referenced by XPlmi_DmaXfr.
void XPlmi_PrintRomVersion(void)
This function prints ROM version using ROM digest value.
Referenced by XPlmi_PrintPlmBanner.
u32 XPlmi_GetGicIntrId(u32 GicPVal, u32 GicPxVal)
This function provides Gic interrupt id.
GicPVal indicates GICP source GicPxVal indicates GICPx source Gic Interrupt Id GicPVal indicates GICP source GicPxVal indicates GICPx source Readback length GicPVal indicates GICP source. GicPxVal indicates GICPx source. Gic Interrupt Id.
Referenced by XPlmi_GicRegisterHandler.
u32 XPlmi_GetIpiIntrId(u32 BufferIndex)
This function provides IPI interrupt id.
BufferIndex is the Ipi target buffer index IPI interrupt id BufferIndex is the Ipi target buffer index. IPI interrupt id.
Referenced by XPlmi_GicAddTask, XPlmi_IpiIntrHandler.
u32* XPlmi_GetUartBaseAddr(void)
This function provides LpdInitialized variable pointer.
This function provides a pointer to the UART base address variable.Pointer to LpdInitialized variable Pointer to LpdInitialized variable. Pointer to the static UartBaseAddr variable that stores the UART base address (initialized to XPLMI_INVALID_UART_BASE_ADDR)
Referenced by XPlmi_InitUart, XPlmi_ConfigUart, outbyte.
u32 XPlmi_IsFipsModeEn(void)
This function return FIPS mode.
TRUE If FIPS mode is enabled FALSE If FIPS mode is disabled
Referenced by XPlmi_CheckAndUpdateFipsState.
u32 XPlmi_GetRomKatStatus(void)
This function returns ROM KAT status.
ROM KAT status
References XPLMI_ROM_KAT_MASK.
void XPlmi_GetBootKatStatus(volatile u32 *PlmKatStatus)
This function returns KAT status from RCTA area.
This function sets KAT status from RTC area. PlmKatStatus is the pointer to the variable which holds kat status PlmKatStatus is the pointer to the variable which holds kat status.
void XPlmi_IpiIntrHandler(void *CallbackRef)
This function is the IPI interrupt handler for the device.
This function is the Ipi interrupt handler for the device. CallbackRef is a dummy argument
References XPlmi_PlmIntrClear, XPlmi_GetTaskInstance, XPlmi_GetIpiIntrId, XPlmi_TaskTriggerNow.
void XPlmi_ClearSSSCfgErr(void)
This function clears SSS Cfg error set during ROM PCR Extension.
References XPlmi_IsPlmUpdateDone.
XPlmi_FipsKatMask* XPlmi_GetFipsKatMaskInstance(void)
This function returns XPlmi_FipsKatMask instance.
pointer to the XPlmi_FipsKatMask instance
Referenced by XPlmi_SetFipsKatMask.
int XPlmi_CheckAndUpdateFipsState(void)
This function checks and updates the FIPS state in RTCA.
XST_SUCCESS on successXST_FAILURE on failure
References XPlmi_IsFipsModeEn.
Referenced by XPlmi_UpdateKatStatus, XPlmi_SetFipsKatMask.
void XPlmi_UpdateCryptoStatus(u32 Mask, u32 Val)
This function sets or clears crypto bit in RTCA based on mask.
Mask Mask to set or clear crypto status Val Value to set or clear crypto status
References XPlmi_UtilRMW.
u32 XPlmi_GetCryptoStatus(u32 Mask)
This function returns crypto status flag.
Mask Mask to read crypto status Crypto status value
u8 XPlmi_IsKatRan(u32 PlmKatMask)
This function will return KAT status of given mask.
PlmKatMask contains the KAT mask TRUE If KAT ran FALSE If KAT didn't ran PlmKatMask contains the KAT mask TRUE If KAT ran.FALSE If KAT didn't ran.
References XPlmi_IsCryptoKatEn.
u32 XPlmi_GetRomIroFreq(void)
This function provides the Iro Frequency used in ROM.
RomIroFreq value
Referenced by XPlmi_PrintRomTime.
XIOModule* XPlmi_GetIOModuleInst(void)
This function provides pointer to IOModule structure.
Pointer to XIOModule Pointer to XIOModule.
Referenced by XPlmi_GetTimerValue, XPlmi_StartTimer, XPlmi_SetUpInterruptSystem, XPlmi_PlmIntrEnable, XPlmi_PlmIntrDisable, XPlmi_PlmIntrClear, XPlmi_RegisterHandler.
int XPlmi_InPlacePlmUpdate(XPlmi_Cmd *Cmd)
This function provides In Place PLM Update support.
Cmd is pointer to the command structure Command payload parameters are High AddrLow Addr XST_SUCCESS on success and error code on failure
References XPlmi_PlmUpdate.
int XPlmi_PsmSequence(XPlmi_Cmd *Cmd)
This function is used to transfer all psm_sequence commands to PSM RAM regions which are then processed by PSM immediately.
Cmd is a pointer to command structure XST_SUCCESS if success.XPLMI_ERR_PROC_LPD_NOT_INITIALIZED if failed to initialize LPD.XPLMI_UNSUPPORTED_PROC_LENGTH if received proc does not fit in the proc memory.
References XPlmi_GetBufferList, XPLMI_PSM_SEQUENCE_CMD_ID, XPLMI_ERR_PROC_LPD_NOT_INITIALIZED, XPLMI_WORD_LEN, XPLMI_UNSUPPORTED_PROC_LENGTH, XPlmi_DmaTransfer.
int XPlmi_ScatterWrite(XPlmi_Cmd *Cmd)
This function will write single 32 bit value to multiple addresses which are specified in the payload.
Command payload parameters are - Value - Address[N]: array of N addresses Cmd is pointer to the command structure XST_SUCCESS if success.XPLMI_ERR_INVALID_PAYLOAD_LEN on invalid payload length.
References XPLMI_SCATTER_WRITE_CMD_ID, XPLMI_SCATTER_WRITE_PAYLOAD_LEN, XPlmi_Print, XPLMI_ERR_INVALID_PAYLOAD_LEN.
int XPlmi_ScatterWrite2(XPlmi_Cmd *Cmd)
This function will write 2 32-bit values to multiple addresses which are specified by the payload.
Command payload parameters are Value1Value2Address[N]: array of N addresses where Address[i] = Value1 and Address[i] + 4 = Value2 Cmd is pointer to the command structure XST_SUCCESS if success.XPLMI_ERR_INVALID_PAYLOAD_LEN on invalid payload length.
References XPLMI_SCATTER_WRITE2_CMD_ID, XPLMI_SCATTER_WRITE2_PAYLOAD_LEN, XPlmi_Print, XPLMI_ERR_INVALID_PAYLOAD_LEN, XPLMI_WORD_LEN.
int XPlmi_SetFipsKatMask(XPlmi_Cmd *Cmd)
This function will store the KAT mask set by the user so that PLM can monitor the RTCA and compare it with KAT masks before going into FIPS operational state.
Cmd is pointer to the command structure XST_SUCCESS if success.XPLMI_ERR_INVALID_PAYLOAD_LEN on invalid payload length.
References XPlmi_GetFipsKatMaskInstance, XPLMI_SET_FIPS_MASK_CMD_ID, XPLMI_FIPS_WRITE_KATMASK_PAYLOAD_LEN, XPlmi_Print, XPLMI_ERR_INVALID_PAYLOAD_LEN, XPLMI_ROM_KAT_MASK, XPLMI_KAT_MASK, XPlmi_CheckAndUpdateFipsState.
int XPlmi_RunProc(XPlmi_Cmd *Cmd)
This function will run the already stored proc if present.
Cmd is pointer to the command structure XST_SUCCESS if success and error code if failure
References XPLMI_RUN_PROC_CMD_ID, XPlmi_ExecuteProc.
void XPlmi_SetAddrBufferList(void)
This function initializes Address Buffer List.
References XPLMI_MAX_ADDR_LIST_CNT, XPLMI_MAX_ADDR_BUFFERS.
int XPlmi_ListSet(XPlmi_Cmd *Cmd)
This function will create a list with given list of addresses.
Cmd is pointer to the command structure XST_SUCCESS if success and error code if failure
References XPLMI_LIST_SET_CMD_ID, XPLMI_LIST_ID_INDEX, XPLMI_LIST_ID_MASK, XPLMI_LIST_ID_SHIFT, XPlmi_StoreBuffer.
int XPlmi_ListWrite(XPlmi_Cmd *Cmd)
This function will execute write for the requested list of addresses.
Cmd is pointer to the command structure XST_SUCCESS if success and error code if failure
References XPLMI_LIST_ID_MASK, XPLMI_LIST_ID_SHIFT, XPLMI_ADDRESS_OFFSET_MASK, XPLMI_LIST_WRITE_CMD_ID, XPlmi_SearchBufferList.
int XPlmi_ListMaskWrite(XPlmi_Cmd *Cmd)
This function will execute mask write for the requested list of addresses.
Cmd is pointer to the command structure XST_SUCCESS if success and error code if failure
References XPLMI_LIST_ID_MASK, XPLMI_LIST_ID_SHIFT, XPLMI_ADDRESS_OFFSET_MASK, XPLMI_LIST_MASK_WRITE_CMD_ID, XPlmi_SearchBufferList, XPlmi_UtilRMW.
int XPlmi_ListMaskPoll(XPlmi_Cmd *Cmd)
This function will execute mask poll for the requested list of addresses.
Cmd is pointer to the command structure XST_SUCCESS if success and error code if failure
References XPLMI_LIST_ID_MASK, XPLMI_LIST_ID_SHIFT, XPLMI_ADDRESS_OFFSET_MASK, XPLMI_LIST_MASK_POLL_CMD_ID, XPlmi_SearchBufferList, XPlmi_GenericMaskPoll.
int XPlmi_RomISR(XPlmi_RomIntr RomServiceReq)
This function raises an interrupt request to ROM and waits for completion.
Before calling this API all pre-requsites for ROM service shall be completed. RomServiceReq variable of enum type XPlmi_RomIntr XST_SUCCESS if success.XPLMI_ERR_INVALID_ROM_INT_REQ on invalid interrupt request for ROM.
References XPLMI_INVALID_INT, XPLMI_PLM_UPDT_REQ, XPLMI_DME_CHL_SIGN_GEN, XPLMI_ROM_SERVICE_TIMEOUT.
void XPlmi_SaveLpdEAMInfo(void)
Saves the PSM (Platform System Management) error status info for the LPD (Low Power Domain), reads the error status registers from the PSM, and stores error status values into the RTCFG memory.
This function is platform-specific.