net/server/xplmi_err.c
XPLMI_ERROR_TABLE_DS_VER
Error table data structure version.
XPLMI_ERROR_TABLE_DS_LCVER
Error table data structure LC version.
XPLMI_IS_PSMCR_CHANGED_VERSION
PSMCR changed version status.
XPLMI_IS_PSMCR_CHANGED_LCVERSION
PSMCR changed LC version status.
XPLMI_NUM_ERROUTS_VERSION
ERROUTS version.
XPLMI_NUM_ERROUTS_LCVERSION
ERROUTS LC version.
CPM5N_NCR_PCIE0_LINK_UP_EVENT_PROC_ID
CPM5N_NCR_PCIE0 linkup event procedure Id.
CPM5N_NCR_PCIE1_LINK_UP_EVENT_PROC_ID
CPM5N_NCR_PCIE1 linkup event procedure Id.
CPM5N_NCR_PCIE2_LINK_UP_EVENT_PROC_ID
CPM5N_NCR_PCIE2 linkup event procedure Id.
CPM5N_NCR_PCIE3_LINK_UP_EVENT_PROC_ID
CPM5N_NCR_PCIE3 linkup event procedure Id.
XPlmi_Error_t ErrorTable[XPLMI_ERROR_SW_ERR_MAX][XPLMI_ERROR_SW_ERR_MAX]
static void XPlmi_CpmErrHandler(u32 ErrorNodeId, u32 RegMask)
This function handles the CPM_NCR error.
ErrorNodeId is the node ID for the error event RegMask is the register mask of the error received
static void XPlmi_XppuErrHandler(u32 BaseAddr, const char *ProtUnitStr)
This function handles the XPPU errors.
BaseAddr is the base address of the XPPU ProtUnitStr is string prefix to be used while printing event info
static void XPlmi_XmpuErrHandler(u32 BaseAddr, const char *ProtUnitStr)
This function handles the XMPU errors.
BaseAddr is the base address of the XMPU ProtUnitStr is string prefix to be used while printing event info
XPlmi_Error_t * XPlmi_GetErrorTable(void)
This function provides error table pointer.
Pointer to Error Table Pointer to Error Table
Referenced by XPlmi_EmClearError, XPlmi_EmConfig, XPlmi_EmGetAction, XPlmi_EmInit, XPlmi_EmSetAction, XPlmi_ErrorTaskHandler, XPlmi_ErrPSMIntrHandler, XPlmi_HandleSwError, XPlmi_LpdSlcrEmInit, XPlmi_PsEmInit, XPlmi_TriggerFwNcrError, XPlmi_UpdateErrorSubsystemId, XPlmi_Versal2Ve2VmEAMHandler.
u32 * XPlmi_GetPsmCrState(void)
This function provides IsPsmChanged variable.
Pointer to IsPsmCrChanged Pointer to IsPsmCrChanged.
void XPlmi_ReconfigErrActions(void)
This function reconfigures error actions after the update.
None
References XPlmi_EmConfig.
Referenced by XPlmi_EmInit.
u8 XPlmi_GetEventIndex(XPlmi_EventType ErrorNodeType)
This function provides event index.
ErrorNodeType is the Node Type of the EAM register Event Index ErrorNodeType is the Node Type of the EAM register. Event Index.
Referenced by XPlmi_EmClearError, XPlmi_EmDisable, XPlmi_Versal2Ve2VmSetAction.
void XPlmi_HandleLinkUpEvent(u32 Cpm5NPcieCdxIrStatusReg, u32 Cpm5NCdxPcieBReg, u32 ProcId)
This function handles the CPM_NCR PCIE link up event.
Cpm5NPcieCdxIrStatusReg is the PCIE0/1/2/3 IR status register address Cpm5NCdxPcieBReg is the Pcie Bridge Misc Status register address ProcId is the ProcId for PCIE0/1/2/3 link up event
References XPlmi_ErrMgr, XPlmi_ExecuteProc.
void XPlmi_ErrPrintToLog(u32 ErrorNodeId, u32 RegMask)
This function is the interrupt handler for Error action "Print to Log".
This function prints detailed information if the error is due to XMPU/XPPU protection units. ErrorNodeId is the node ID for the error event RegMask is the register mask of the error received This function prints detailed information if the error is due to XMPU/XPPU protection units. ErrorNodeId is the node ID for the error event RegMask is the register mask of the error received None This function prints detailed information if the error is due to XMPU/XPPU protection units. ErrorNodeId is the node ID for the error event. RegMask is the register mask of the error received.
References XPlmi_GetErrorId.
Referenced by XPlmi_EmConfig.
void XPlmi_DumpErrNGicStatus(void)
This function dumps EAM Error status registers and Gic Status registers.
None
int XPlmi_RestrictErrActions(XPlmi_EventType NodeType, u32 RegMask, u32 ErrorAction)
This function restricts error actions.
NodeType of Error RegMask of Error ErrorAction of the the Error XST_SUCCESS on success and error code on failure NodeType of Error RegMask of Error ErrorAction of the the Error XST_SUCCESS if success.XPLMI_INVALID_ERROR_ACTION on invalid error action. NodeType of Error. RegMask of Error. ErrorAction of the the Error. XST_SUCCESS on success.Error code on failure.
Referenced by XPlmi_Versal2Ve2VmSetAction.
u32 * XPlmi_GetNumErrOuts(void)
This function provides pointer to NumErrOuts.
Pointer to NumErrOuts Pointer to NumErrOuts.
Referenced by XPlmi_UpdateNumErrOutsCount.