net/server/xplmi_wdt.c
XPLMI_WDT_PERIODICITY
WDT periodicity.
XPLMI_SCHEDULER_PERIOD
Scheduler period.
Referenced by XPlmi_WdtHandler.
XPLMI_WDT_PERIODICITY_MIN
Minimum WDT periodicity.
Referenced by XPlmi_EnableWdt, XPlmi_WdtHandler.
XPLMI_WDT_PERIODICITY_MAX
Maximum WDT periodicity.
Referenced by XPlmi_EnableWdt.
XPLMI_SPP_WDT_PERIODICITY_MIN
SPP minimum WDT periodicity.
XPLMI_MIO_NUM_PER_BANK
Number of MIO per bank.
Referenced by XPlmi_EnableWdt.
XPLMI_PM_STMIC_LMIO_0
PM STMIC LMIO_0.
Referenced by XPlmi_EnableWdt.
XPLMI_PM_STMIC_LMIO_25
PM STMIC LMIO_25.
Referenced by XPlmi_EnableWdt.
XPLMI_PM_STMIC_PMIO_0
PM STMIC PMIO_0.
Referenced by XPlmi_EnableWdt.
XPLMI_PM_STMIC_PMIO_51
PM STMIC PMIO_51.
Referenced by XPlmi_EnableWdt.
XPLMI_PM_DEV_PMC_WDT
PM DEV PMC WDT.
Referenced by XPlmi_DefaultSWdtConfig.
XPlmi_Wdt WdtInstance
WdtInstance is an instance of external WDT used for GPIO toggling.
int XPlmi_EnableWdt(u32 NodeId, u32 Periodicity)
This function enables the WDT and sets NodeId and periodicity.
It also verifies the parameters. NodeId NodeId is the MIO node to be used by PLM for toggling. Periodicity at which MIO value should be toggled. XST_SUCCESS if success.XPLMI_ERR_WDT_PERIODICITY on invalid Periodicity.XPLMI_ERR_WDT_LPD_NOT_INITIALIZED if LPD is not initialized.XPLMI_ERR_WDT_NODE_ID on invalid node ID. It also verifies the parameters. NodeId NodeId is the MIO node to be used by PLM for toggling. Periodicity at which MIO value should be toggled. XST_SUCCESS if success.XPLMI_ERR_WDT_PERIODICITY on invalid Periodicity.XPLMI_ERR_WDT_LPD_NOT_INITIALIZED if LPD is not initialized.XPLMI_ERR_WDT_NODE_ID on invalid node ID. NodeId NodeId is the MIO node to be used by PLM for toggling. Periodicity at which MIO value should be toggled. XST_SUCCESS if success.XPLMI_ERR_WDT_PERIODICITY on invalid Periodicity.XPLMI_ERR_PMC_WDT_NOT_ENABLED if PMC WDT is tried use and it is not enabled in design.XPLMI_ERR_PMC_WDT_DRV_INIT if PMC WDT driver initialization fails.XPLMI_ERR_WDT_LPD_NOT_INITIALIZED if LPD is not initialized.XPLMI_ERR_WDT_NODE_ID on invalid node ID.
References LPD_WDT_INITIALIZED, XPLMI_ERR_WDT_LPD_NOT_INITIALIZED, XPLMI_ERR_WDT_NODE_ID, XPLMI_ERR_WDT_PERIODICITY, XPLMI_MIO_NUM_PER_BANK, XPLMI_PM_STMIC_LMIO_0, XPLMI_PM_STMIC_LMIO_25, XPLMI_PM_STMIC_PMIO_0, XPLMI_PM_STMIC_PMIO_51, XPlmi_SetLpdInitialized, XPLMI_WDT_PERIODICITY_MAX, XPLMI_WDT_PERIODICITY_MIN.
Referenced by XPlmi_DefaultSWdtConfig.
int XPlmi_DefaultSWdtConfig(void)
This function configures the default WDT configuration if the wdt is not enabled and ROM SWDT usage bit is enabled in EFUSE.
XST_SUCCESS on success and error code on failure
References XPlmi_EnableWdt, XPLMI_PM_DEV_PMC_WDT.
void XPlmi_DisableWdt(u32 NodeId)
This function disables the WDT.
This is required when LPD is powered down and if LPD MIO is used. Also required when debugging. NodeId is not applicable for versal platform. This is required when LPD is powered down and if LPD MIO is used. Also required when debugging. NodeId is the Node ID of external WDT or internal PMC WDT
Referenced by XPlmi_ResetLpdInitialized.
void XPlmi_StopWdt(u32 NodeId)
This function stops PMC WDT.
Used during In-Place PLM update. NodeId is the Node ID of external WDT or internal PMC WDT
void XPlmi_SetPlmLiveStatus(void)
This function Sets the PLM Status.
Referenced by XPlmi_ErrMgr, XPlmi_Init, XPlmi_ProcessCdo, XPlmi_SsitSyncSlaves, XPlmi_SsitWaitSlaves, XPlmi_SysMonOTDetect, XPlmi_TaskDispatchLoop, XPlmi_UtilPoll, XPlmi_UtilPoll64, XPlmi_UtilPollForMask, XPlmi_UtilPollForMask64.
void XPlmi_ClearPlmLiveStatus(void)
This function clears the PLM status.
static void XPlmi_RefreshWdt(u32 NodeId)
This function is used to refresh WDT before timeout.
NodeId is the Node ID of external WDT or internal PMC WDT
void XPlmi_KickWdt(u32 NodeId)
This function is used to kick the WDT.
NodeId is the Node ID of external WDT or internal PMC WDT
Referenced by XPlmi_UpdateInit.
void XPlmi_RestoreWdt(void)
This function is used to restore wdt after the In-Place PLM Update.
void XPlmi_WdtHandler(void)
This function is handler for WDT.
Scheduler calls this function periodically to check the PLM Live status and to toggle the MIO.
References XPLMI_SCHEDULER_PERIOD, XPLMI_WDT_PERIODICITY_MIN.
Referenced by XPlmi_SchedulerHandler.