net/server/xplmi_err.h
GET_PMC_ERR_ACTION_OFFSET
PMC error action offset.
GET_PMC_ERR_ACTION_ADDR
PMC error action address.
GET_PMC_ERR_OUT_MASK
PMC error out mask.
GET_PMC_POR_MASK
PMC POR mask.
GET_PMC_IRQ_MASK
PMC IRQ mask.
GET_PMC_SRST_MASK
PMC SRST mask.
static void XPlmi_SysmonClkSetIro(void)
This function sets the sysmon clock to IRO for ES1 silicon.
static void XPlmi_ClearSsitErrors(u32 *PmcErrStatus, u32 Index)
This function clears Ssit errors for ES1 silicon.
PmcErrStatus is the pointer to the error status array Index is the PMC Error register Index
XPlmi_Error_t* XPlmi_GetErrorTable(void)
This function provides error table pointer.
Pointer to Error Table Pointer to Error Table
Referenced by XPlmi_Versal2Ve2VmEAMHandler, XPlmi_LpdSlcrEmInit, XPlmi_UpdateErrorSubsystemId, XPlmi_HandleSwError, XPlmi_ErrorTaskHandler, XPlmi_EmClearError, XPlmi_EmConfig, XPlmi_EmSetAction, XPlmi_EmGetAction, XPlmi_EmInit, XPlmi_TriggerFwNcrError, XPlmi_ErrPSMIntrHandler, XPlmi_PsEmInit.
u8 XPlmi_GetEventIndex(XPlmi_EventType ErrorNodeType)
This function provides event index.
ErrorNodeType is the Node Type of the EAM register Event Index ErrorNodeType is the Node Type of the EAM register. Event Index.
Referenced by XPlmi_Versal2Ve2VmSetAction, XPlmi_EmClearError, XPlmi_EmDisable.
int XPlmi_RestrictErrActions(XPlmi_EventType NodeType, u32 RegMask, u32 ErrorAction)
This function restricts error actions.
NodeType of Error RegMask of Error ErrorAction of the the Error XST_SUCCESS on success and error code on failure NodeType of Error RegMask of Error ErrorAction of the the Error XST_SUCCESS if success.XPLMI_INVALID_ERROR_ACTION on invalid error action. NodeType of Error. RegMask of Error. ErrorAction of the the Error. XST_SUCCESS on success.Error code on failure.
Referenced by XPlmi_Versal2Ve2VmSetAction.
void XPlmi_DumpErrNGicStatus(void)
This function dumps EAM Error status registers and Gic Status registers.
None
void XPlmi_ReconfigErrActions(void)
This function reconfigures error actions after the update.
None
References XPlmi_EmConfig.
Referenced by XPlmi_EmInit.
u32* XPlmi_GetNumErrOuts(void)
This function provides pointer to NumErrOuts.
Pointer to NumErrOuts Pointer to NumErrOuts.
Referenced by XPlmi_UpdateNumErrOutsCount.
u32* XPlmi_GetPsmCrState(void)
This function provides IsPsmChanged variable.
Pointer to IsPsmCrChanged Pointer to IsPsmCrChanged.
void XPlmi_HandleLinkUpEvent(u32 Cpm5NPcieCdxIrStatusReg, u32 Cpm5NCdxPcieBReg, u32 ProcId)
This function handles the CPM_NCR PCIE link up event.
Cpm5NPcieCdxIrStatusReg is the PCIE0/1/2/3 IR status register address Cpm5NCdxPcieBReg is the Pcie Bridge Misc Status register address ProcId is the ProcId for PCIE0/1/2/3 link up event
References XPlmi_ExecuteProc, XPlmi_ErrMgr.
void XPlmi_ErrPrintToLog(u32 ErrorNodeId, u32 RegMask)
This function is the interrupt handler for Error action "Print to Log".
This function prints detailed information if the error is due to XMPU/XPPU protection units. ErrorNodeId is the node ID for the error event RegMask is the register mask of the error received This function prints detailed information if the error is due to XMPU/XPPU protection units. ErrorNodeId is the node ID for the error event RegMask is the register mask of the error received None This function prints detailed information if the error is due to XMPU/XPPU protection units. ErrorNodeId is the node ID for the error event. RegMask is the register mask of the error received.
References XPlmi_GetErrorId.
Referenced by XPlmi_EmConfig.