net/server/xplmi_wdt.h
XPLMI_INPLACE_UPDATE_WDT_TIMEOUT
XPLMI_PM_STMIC_LMIO_0
XPLMI_PM_STMIC_LMIO_25
XPLMI_PM_STMIC_PMIO_0
XPLMI_PM_STMIC_PMIO_51
XPLMI_PM_DEV_PMC_WDT
XPLMI_WDT_EXTERNAL
XPLMI_WDT_INTERNAL
static u8 XPlmi_RomSwdtUsage(void)
This function checks if ROM SWDT Usage is enabled in EFUSE.
TRUE if Usage is enabled, else FALSE
void XPlmi_SetPlmLiveStatus(void)
This function Sets the PLM Status.
Referenced by XPlmi_Init, XPlmi_ProcessCdo, XPlmi_ErrMgr, XPlmi_SsitSyncSlaves, XPlmi_SsitWaitSlaves, XPlmi_SysMonOTDetect, XPlmi_TaskDispatchLoop, XPlmi_UtilPoll, XPlmi_UtilPoll64, XPlmi_UtilPollForMask, XPlmi_UtilPollForMask64.
void XPlmi_ClearPlmLiveStatus(void)
This function clears the PLM status.
int XPlmi_EnableWdt(u32 NodeId, u32 Periodicity)
This function enables the WDT and sets NodeId and periodicity.
It also verifies the parameters. NodeId NodeId is the MIO node to be used by PLM for toggling. Periodicity at which MIO value should be toggled. XST_SUCCESS if success.XPLMI_ERR_WDT_PERIODICITY on invalid Periodicity.XPLMI_ERR_WDT_LPD_NOT_INITIALIZED if LPD is not initialized.XPLMI_ERR_WDT_NODE_ID on invalid node ID. It also verifies the parameters. NodeId NodeId is the MIO node to be used by PLM for toggling. Periodicity at which MIO value should be toggled. XST_SUCCESS if success.XPLMI_ERR_WDT_PERIODICITY on invalid Periodicity.XPLMI_ERR_WDT_LPD_NOT_INITIALIZED if LPD is not initialized.XPLMI_ERR_WDT_NODE_ID on invalid node ID. NodeId NodeId is the MIO node to be used by PLM for toggling. Periodicity at which MIO value should be toggled. XST_SUCCESS if success.XPLMI_ERR_WDT_PERIODICITY on invalid Periodicity.XPLMI_ERR_PMC_WDT_NOT_ENABLED if PMC WDT is tried use and it is not enabled in design.XPLMI_ERR_PMC_WDT_DRV_INIT if PMC WDT driver initialization fails.XPLMI_ERR_WDT_LPD_NOT_INITIALIZED if LPD is not initialized.XPLMI_ERR_WDT_NODE_ID on invalid node ID.
References XPLMI_WDT_PERIODICITY_MIN, XPLMI_WDT_PERIODICITY_MAX, XPLMI_ERR_WDT_PERIODICITY, XPLMI_PM_STMIC_LMIO_0, XPLMI_PM_STMIC_LMIO_25, XPLMI_ERR_WDT_LPD_NOT_INITIALIZED, XPlmi_SetLpdInitialized, LPD_WDT_INITIALIZED, XPLMI_PM_STMIC_PMIO_0, XPLMI_PM_STMIC_PMIO_51, XPLMI_MIO_NUM_PER_BANK, XPLMI_ERR_WDT_NODE_ID.
Referenced by XPlmi_DefaultSWdtConfig.
void XPlmi_KickWdt(u32 NodeId)
This function is used to kick the WDT.
NodeId is the Node ID of external WDT or internal PMC WDT
Referenced by XPlmi_UpdateInit.
void XPlmi_RestoreWdt(void)
This function is used to restore wdt after the In-Place PLM Update.
void XPlmi_StopWdt(u32 NodeId)
This function stops PMC WDT.
Used during In-Place PLM update. NodeId is the Node ID of external WDT or internal PMC WDT
int XPlmi_DefaultSWdtConfig(void)
This function configures the default WDT configuration if the wdt is not enabled and ROM SWDT usage bit is enabled in EFUSE.
XST_SUCCESS on success and error code on failure
References XPlmi_EnableWdt, XPLMI_PM_DEV_PMC_WDT.
void XPlmi_DisableWdt(u32 NodeId)
This function disables the WDT.
This is required when LPD is powered down and if LPD MIO is used. Also required when debugging. NodeId is not applicable for versal platform. This is required when LPD is powered down and if LPD MIO is used. Also required when debugging. NodeId is the Node ID of external WDT or internal PMC WDT
Referenced by XPlmi_ResetLpdInitialized.
void XPlmi_WdtHandler(void)
This function is handler for WDT.
Scheduler calls this function periodically to check the PLM Live status and to toggle the MIO.
References XPLMI_SCHEDULER_PERIOD, XPLMI_WDT_PERIODICITY_MIN.
Referenced by XPlmi_SchedulerHandler.