server/xplmi_plat.c
XPLMI_DIGEST_PMC_1_0_ROM_1_0
PMC1 ROM version 1 digest.
XPLMI_DIGEST_PMC_2_0_ROM_2_0
PMC2 ROM version 2 digest.
XPLMI_ROM_VERSION_1_0
ROM version 1.
XPLMI_ROM_VERSION_2_0
ROM version 2.
XPLMI_INVALID_ROM_VERSION
Invalid ROM version.
XPLMI_CFU_STREAM_2_SLR_OFFSET
SLR offset for CFU stream 2 register.
XPLMI_CFU_FDRO_2_SLR_OFFSET
SLR offset for CFU FDRO 2 register.
XPLMI_SLR1_CFU_FDRO_2_ADDR
SLR1 CFU FDRO 2 address.
Referenced by XPlmi_GetReadbackSrcDest.
XPLMI_SLR2_CFU_FDRO_2_ADDR
SLR2 CFU FDRO 2 address.
Referenced by XPlmi_GetReadbackSrcDest.
XPLMI_SLR3_CFU_FDRO_2_ADDR
SLR3 CFU FDRO 2 address.
Referenced by XPlmi_GetReadbackSrcDest.
XPLMI_SLR1_CFU_STREAM_2_ADDR
SLR1 CFU Stream 2 address.
Referenced by XPlmi_GetReadbackSrcDest.
XPLMI_SLR2_CFU_STREAM_2_ADDR
SLR2 CFU Stream 2 address.
Referenced by XPlmi_GetReadbackSrcDest.
XPLMI_SLR3_CFU_STREAM_2_ADDR
SLR3 CFU Stream 2 address.
Referenced by XPlmi_GetReadbackSrcDest.
XPLMI_PMC_VOLTAGE_MULTIPLIER
PMC voltage multiplier.
XPLMI_PMC_VERSION_1_0
PMC version 1.0.
XPlmi_GetRawVoltage
This macro converts voltage to raw voltage value.
Voltage is the voltage value in volts 32-bit voltage value
XInterruptHandler g_TopLevelInterruptTable[][]
u8 XRamAvailable
static int XPlmi_UpdateResetReason(void)
This function updates reset reason.
XST_SUCCESS on success and error code on failure
static int XPlmi_SsitWaitForDmaDone(XPmcDma *DmaPtr, XPmcDma_Channel Channel)
This function is used to check and wait for DMA done when sending data to SSIT Slave SLRs.
DmaPtr is pointer to DMA structure Channel is DMA source or destination channel XST_SUCCESS on success.XPLMI_ERR_FROM_SSIT_SLAVE if error received from slave SLR.
void XPlmi_SetXRamAvailable(void)
Flag to indicate XRAM is available.
This function sets XRAM Available FlagThis function sets XRAM Available Flag.
XInterruptHandler * XPlmi_GetTopLevelIntrTbl(void)
This function provides pointer to g_TopLevelInterruptTable.
Pointer to g_TopLevelInterruptTable structure Pointer to g_TopLevelInterruptTable structure.
Referenced by XPlmi_SetUpInterruptSystem.
u8 XPlmi_GetTopLevelIntrTblSize(void)
This function provides size of g_TopLevelInterruptTable.
Size g_TopLevelInterruptTable structure Size g_TopLevelInterruptTable structure.
Referenced by XPlmi_SetUpInterruptSystem.
XPlmi_BoardParams* XPlmi_GetBoardParams(void)
This function provides pointer to BoardParams.
Pointer to BoardParams Pointer to BoardParams.
References EXPORT_GENERIC_DS, XPLMI_BOARD_PARAMS_DS_ID, XPLMI_BOARD_PARAMS_LCVERSION, XPLMI_BOARD_PARAMS_VERSION.
XIOModule * XPlmi_GetIOModuleInst(void)
This function provides pointer to IOModule structure.
Pointer to XIOModule Pointer to XIOModule.
Referenced by XPlmi_GetTimerValue, XPlmi_PlmIntrClear, XPlmi_PlmIntrDisable, XPlmi_PlmIntrEnable, XPlmi_RegisterHandler, XPlmi_SetUpInterruptSystem, XPlmi_StartTimer.
u32 * XPlmi_GetUartBaseAddr(void)
This function provides LpdInitialized variable pointer.
This function provides a pointer to the UART base address variable.Pointer to LpdInitialized variable Pointer to LpdInitialized variable. Pointer to the static UartBaseAddr variable that stores the UART base address (initialized to XPLMI_INVALID_UART_BASE_ADDR)
Referenced by outbyte, XPlmi_ConfigUart, XPlmi_InitUart.
u32 * XPlmi_GetLpdInitialized(void)
This function provides LpdInitialized variable pointer.
Pointer to LpdInitialized variable Pointer to LpdInitialized variable.
Referenced by XPlmi_ResetLpdInitialized, XPlmi_SetLpdInitialized, XPlmi_UnSetLpdInitialized.
void XPlmi_RtcaPlatInit(void)
This function performs initialization of platform specific RCTA registers.
Referenced by XPlmi_RunTimeConfigInit.
void XPlmi_PrintRomVersion(void)
This function prints ROM version using ROM digest value.
Referenced by XPlmi_PrintPlmBanner.
int XPlmi_PreInit(void)
This function performs plmi pre-initializaton.
Reset reason status. XST_SUCCESS always.
Referenced by XPlmi_Init.
void XPlmi_SssMask(u32 DmaSrc)
This function masks the secure stream switch value.
DmaSrc - DMA0 or DMA1 DmaSrc DMA0 or DMA1.
XPlmi_WaitForDmaDone_t XPlmi_GetPlmiWaitForDone(u64 DestAddr)
This function is used to check and wait for DMA done when sending data to SSIT Slave SLRs.
This function is used to check and wait for DMA done. DestAddr holds the address of the destination buffer XST_SUCCESS on success and error code on failure DestAddr is the address of destination XST_SUCCESS on success and error code on failure DestAddr holds the address of the destination buffer. XST_SUCCESS on success.Error code on failure.
Referenced by XPlmi_DmaXfr.
XPlmi_CircularBuffer * XPlmi_GetTraceLogInst(void)
This function provides TraceLog instance.
Pointer to TraceLog variable Pointer to TraceLog variable.
Referenced by XPlmi_EventLogging.
void XPlmi_GetReadbackSrcDest(u32 SlrType, u64 *SrcAddr, u64 *DestAddrRead)
This function processes and provides SrcAddr and DestAddr for cfi readback.
SlrType is the type of Slr passed in readback cmd SrcAddr is the pointer to the SrcAddr variable DestAddrRead is the pointer to the DestAddrRead variable SlrType is the type of Slr passed in readback cmd. SrcAddr is the pointer to the SrcAddr variable. DestAddrRead is the pointer to the DestAddrRead variable.
References XPLMI_SLR1_CFU_FDRO_2_ADDR, XPLMI_SLR1_CFU_STREAM_2_ADDR, XPLMI_SLR2_CFU_FDRO_2_ADDR, XPLMI_SLR2_CFU_STREAM_2_ADDR, XPLMI_SLR3_CFU_FDRO_2_ADDR, XPLMI_SLR3_CFU_STREAM_2_ADDR.
void XPlmi_GicAddTask(u32 PlmIntrId)
This will add the GIC interrupt task handler to the TaskQueue.
PlmIntrId is the GIC interrupt ID of the task PlmIntrId is the GIC interrupt ID of the task.
References XPlmi_GetIpiIntrId, XPlmi_GicIntrAddTask.
Referenced by XPlmi_GicIntrHandler.
int XPlmi_RegisterNEnableIpi(void)
This function registers and enables IPI interrupt.
XST_SUCCESS on success and XST_FAILURE on failure XST_SUCCESS on success and XST_FAILURE on failure XST_SUCCESS on success.XST_FAILURE on failure.
void XPlmi_EnableIomoduleIntr(void)
This function registers and enables IPI interrupt.
Referenced by XPlmi_SetUpInterruptSystem.
int XPlmi_SetPmcIroFreq(void)
It sets the PMC IRO frequency.
This functions sets the PMC IRO frequency. XST_SUCCESS on success and error code failure - XST_SUCCESS on success XST_FAILURE on failure XST_SUCCESS on success.Error code failure.
Referenced by XPlmi_StartTimer.
int XPlmi_GetPitResetValues(u32 *Pit1ResetValue, u32 *Pit2ResetValue)
This functions provides the PIT1 and PIT2 reset values.
Pit1ResetValue is the pointer to store the PIT1 reset value. Pit2ResetValue is the pointer to store the PIT12 reset value. XST_SUCCESS always.
u32 XPlmi_GetGicIntrId(u32 GicPVal, u32 GicPxVal)
This function provides Gic interrupt id.
GicPVal indicates GICP source GicPxVal indicates GICPx source Gic Interrupt Id GicPVal indicates GICP source GicPxVal indicates GICPx source Readback length GicPVal indicates GICP source. GicPxVal indicates GICPx source. Gic Interrupt Id.
Referenced by XPlmi_GicRegisterHandler.
u32 XPlmi_GetIpiIntrId(u32 BufferIndex)
This function provides IPI interrupt id.
BufferIndex is the Ipi target buffer index IPI interrupt id BufferIndex is the Ipi target buffer index. IPI interrupt id.
Referenced by XPlmi_GicAddTask, XPlmi_IpiIntrHandler.
void XPlmi_EnableIpiIntr(void)
This function enables IPI interrupt.
void XPlmi_ClearIpiIntr(void)
This function clears IPI interrupt.
void XPlmi_DisableCFrameIso(void)
This function Disables CFRAME Isolation.
References XPlmi_UtilRMW.
void XPlmi_GetBootKatStatus(volatile u32 *PlmKatStatus)
This function returns KAT status from RCTA area.
This function sets KAT status from RTC area. PlmKatStatus is the pointer to the variable which holds kat status PlmKatStatus is the pointer to the variable which holds kat status.
XPlmi_BufferList* XPlmi_GetBufferList(u32 BufferListType)
This function defines BufferList and returns the address of the same.
BufferListType is the proc list type if it is stored in PMC or PSM RAM BufferList is the address of BufferList structure BufferListType is the proc list type if it is stored in PMC or PPU RAM BufferList is the address of BufferList structure BufferListType is the proc list type if it is stored in PMC or PSM RAM. BufferList is the address of BufferList structure.
References EXPORT_GENERIC_DS, XPLMI_MAX_PMC_BUFFERS, XPLMI_PMC_BUFFER_DS_ID, XPLMI_PMC_BUFFER_DS_LCVER, XPLMI_PMC_BUFFER_DS_VER, XPLMI_PMC_BUFFER_LIST_DS_ID, XPLMI_PMC_BUFFER_LIST_DS_LCVER, XPLMI_PMC_BUFFER_LIST_DS_VER, XPLMI_PPU_BUFFER_DS_ID, XPLMI_PPU_BUFFER_DS_LCVER, XPLMI_PPU_BUFFER_DS_VER, XPLMI_PPU_BUFFER_LIST_DS_ID, XPLMI_PPU_BUFFER_LIST_DS_LCVER, XPLMI_PPU_BUFFER_LIST_DS_VER.
Referenced by XPlmi_ExecuteProc, XPlmi_PsmSequence, XPlmi_SetBufferList.