server/xplmi_err.c
XPLMI_SYSMON_CLK_SRC_IRO_VAL
Sysmon clock source IRO value.
Referenced by XPlmi_SysmonClkSetIro.
XPLMI_PMC_ERR_SSIT_MASK
PMC error SSIT mask.
Referenced by XPlmi_ClearSsitErrors.
CPM_NCR_PCIE0_LINK_DOWN_PROC_ID
PCIE0 link down proc Id.
CPM_NCR_PCIE1_LINK_DOWN_PROC_ID
PCIE1 link down proc Id.
XPlmi_Error_t ErrorTable[XPLMI_ERROR_SW_ERR_MAX][XPLMI_ERROR_SW_ERR_MAX]
static void XPlmi_CpmErrHandler(u32 ErrorNodeId, u32 RegMask)
This function handles the CPM_NCR error.
ErrorNodeId is the node ID for the error event RegMask is the register mask of the error received
static void XPlmi_XppuErrHandler(u32 BaseAddr, const char *ProtUnitStr)
This function handles the XPPU errors.
BaseAddr is the base address of the XPPU ProtUnitStr is string prefix to be used while printing event info
static void XPlmi_XmpuErrHandler(u32 BaseAddr, const char *ProtUnitStr)
This function handles the XMPU errors.
BaseAddr is the base address of the XMPU ProtUnitStr is string prefix to be used while printing event info
XPlmi_Error_t * XPlmi_GetErrorTable(void)
This function provides error table pointer.
Pointer to Error Table Pointer to Error Table
Referenced by XPlmi_EmClearError, XPlmi_EmConfig, XPlmi_EmGetAction, XPlmi_EmInit, XPlmi_EmSetAction, XPlmi_ErrorTaskHandler, XPlmi_ErrPSMIntrHandler, XPlmi_HandleSwError, XPlmi_LpdSlcrEmInit, XPlmi_PsEmInit, XPlmi_TriggerFwNcrError, XPlmi_UpdateErrorSubsystemId, XPlmi_Versal2Ve2VmEAMHandler.
u32 * XPlmi_GetPsmCrState(void)
This function provides IsPsmChanged variable.
Pointer to IsPsmCrChanged Pointer to IsPsmCrChanged.
u8 XPlmi_GetEventIndex(XPlmi_EventType ErrorNodeType)
This function provides event index.
ErrorNodeType is the Node Type of the EAM register Event Index ErrorNodeType is the Node Type of the EAM register. Event Index.
Referenced by XPlmi_EmClearError, XPlmi_EmDisable, XPlmi_Versal2Ve2VmSetAction.
void XPlmi_SysmonClkSetIro(void)
This function sets the sysmon clock to IRO for ES1 silicon.
References XPLMI_SYSMON_CLK_SRC_IRO_VAL, XPlmi_UtilRMW.
Referenced by XPlmi_PORHandler, XPlmi_SoftResetHandler, XPlmi_TriggerFwNcrError.
void XPlmi_HandleLinkDownError(u32 Cpm5PcieIrStatusReg, u32 Cpm5DmaCsrIntDecReg, u32 ProcId)
This function handles the CPM_NCR PCIE link down error.
This function handles the PCIE link down error. Cpm5PcieIrStatusReg is the PCIE0/1 IR status register address Cpm5DmaCsrIntDecReg is the DMA0/1 CSR INT DEC register address ProcId is the ProcId for PCIE0/1 link down error DeviceIrStatusReg is the PCIE0/1 Device IR status register address GenralStsReg is the PCIE0/1 General status register address ProcId is the ProcId for PCIE0/1 link down error Cpm5PcieIrStatusReg is the PCIE0/1 IR status register address. Cpm5DmaCsrIntDecReg is the DMA0/1 CSR INT DEC register address. ProcId is the ProcId for PCIE0/1 link down error.
References XPlmi_ErrMgr, XPlmi_ExecuteProc.
void XPlmi_ErrPrintToLog(u32 ErrorNodeId, u32 RegMask)
This function is the interrupt handler for Error action "Print to Log".
This function prints detailed information if the error is due to XMPU/XPPU protection units. ErrorNodeId is the node ID for the error event RegMask is the register mask of the error received This function prints detailed information if the error is due to XMPU/XPPU protection units. ErrorNodeId is the node ID for the error event RegMask is the register mask of the error received None This function prints detailed information if the error is due to XMPU/XPPU protection units. ErrorNodeId is the node ID for the error event. RegMask is the register mask of the error received.
References XPlmi_GetErrorId.
Referenced by XPlmi_EmConfig.
void XPlmi_DumpErrNGicStatus(void)
This function dumps EAM Error status registers and Gic Status registers.
None
void XPlmi_ClearSsitErrors(u32 *PmcErrStatus, u32 Index)
This function clears Ssit errors for ES1 silicon.
PmcErrStatus is the pointer to the error status array Index is the PMC Error register Index PmcErrStatus is the pointer to the error status array. Index is the PMC Error register Index.
References XPLMI_PMC_ERR_SSIT_MASK.
Referenced by XPlmi_EmInit.
u32 * XPlmi_GetNumErrOuts(void)
This function provides pointer to NumErrOuts.
Pointer to NumErrOuts Pointer to NumErrOuts.
Referenced by XPlmi_UpdateNumErrOutsCount.
int XPlmi_RestrictErrActions(XPlmi_EventType NodeType, u32 RegMask, u32 ErrorAction)
This function restricts error actions.
NodeType of Error RegMask of Error ErrorAction of the the Error XST_SUCCESS on success and error code on failure NodeType of Error RegMask of Error ErrorAction of the the Error XST_SUCCESS if success.XPLMI_INVALID_ERROR_ACTION on invalid error action. NodeType of Error. RegMask of Error. ErrorAction of the the Error. XST_SUCCESS on success.Error code on failure.
Referenced by XPlmi_Versal2Ve2VmSetAction.