server/xplmi_generic.c
static int XPlmi_Features(XPlmi_Cmd *Cmd)
This function checks if a particular PLM Command ID is supported or not.
Command ID is the only payload parameter. Cmd is pointer to the command structure XST_SUCCESS always.
static int XPlmi_Nop(XPlmi_Cmd *Cmd)
This function provides no operation.
The command is supported for alignment purposes. Zero command payload parameters. Cmd is pointer to the command structure XST_SUCCESS always.
static int XPlmi_GetDeviceID(XPlmi_Cmd *Cmd)
This function reads the device ID and fills in the response buffer.
Command: GetDeviceID Reserved[31:24]=0 Length[23:16]=[0] PLM=1 CMD_DEVID=18 Payload = 0 The command reads PMC_TAP_IDCODE register and EFUSE_CACHE_IP_DISABLE_0 register and fills the command response array with these values. Cmd is pointer to the command structure XST_SUCCESS always.
int XPlmi_GenericMaskPoll(XPlmi_Cmd *Cmd, u64 Addr, u32 Type)
This function provides generic implementation for both 32-bit and 64-bit mask poll command execution.
Command payload parameters are - Address - Mask - Expected Value - Timeout in us - Deferred Error flag - Optional 0 - Return error in case of failure, 1 - Ignore error, return success always 2 - Defer error till the end of partition load 3 - Break to end offset in case of failure - Error Code Cmd is pointer to the command structure Addr is address of mask poll Type is flag indicating if the address is 64-bit XST_SUCCESS on success.XST_FAILURE if timedout.
References XPlmi_GetTimerValue, XPlmi_MeasurePerfTime, XPlmi_UtilPoll, XPlmi_UtilPoll64.
Referenced by XPlmi_ListMaskPoll.
static int XPlmi_MaskPoll(XPlmi_Cmd *Cmd)
This function provides 32 bit mask poll command execution.
Command payload parameters are - Address - Mask - Expected Value - Timeout in us - Deferred Error flag - Optional 0 - Return error in case of failure, 1 - Ignore error, return success always 2 - Defer error till the end of partition load 3 - Break to end offset in case of failure - Error Code Cmd is pointer to the command structure XST_SUCCESS on success.XST_FAILURE if timedout.
static int XPlmi_MaskWrite(XPlmi_Cmd *Cmd)
This function provides 32 bit mask write command execution.
Command payload parameters are - Address - Mask - Value Cmd is pointer to the command structure XST_SUCCESS always.
static int XPlmi_Write(XPlmi_Cmd *Cmd)
This function provides 32 bit Write command execution.
Command payload parameters are - Address - Value Cmd is pointer to the command structure XST_SUCCESS always.
static int XPlmi_Delay(XPlmi_Cmd *Cmd)
This function provides delay command execution.
Command payload parameter delay in micro seconds Cmd is pointer to the command structure XST_SUCCESS always.
int XPlmi_DmaTransfer(u64 Dest, u64 Src, u32 Len, u32 Flags)
This function provides functionality for DMA write.
Dest is the destination address Src is the source address Len is the number of words to be transferred Flags is the DMA transfer related flags XST_SUCCESS on success.XPLMI_ERR_UNALIGNED_DMA_XFER if unaligned DMA transfer fails.
References XPlmi_DmaXfr, XPLMI_ERR_UNALIGNED_DMA_XFER, XPLMI_WORD_LEN.
Referenced by XPlmi_MoveBuffer, XPlmi_PsmSequence, XPlmi_StoreBuffer.
static int XPlmi_DmaWrite(XPlmi_Cmd *Cmd)
This function provides DMA write command execution.
Command payload parameters are - High Dest Addr - Low Dest Addr Cmd is pointer to the command structure XST_SUCCESS on success and error code on failure
static int XPlmi_MaskPoll64(XPlmi_Cmd *Cmd)
This function provides 64 bit mask poll command execution.
Command payload parameters are - High Address - Low Address - Mask - Expected Value - Timeout in us - Deferred Error flag - Optional 0 - Return error in case of failure, 1 - Ignore error, return success always 2 - Defer error till the end of partition load 3 - Break to end offset in case of failure - Error Code Cmd is pointer to the command structure XST_SUCCESS on success.XST_FAILURE if timedout.
static int XPlmi_MaskWrite64(XPlmi_Cmd *Cmd)
This function provides 64 bit mask write command execution.
Command payload parameters are - High Address - Low Address - Mask - Value Cmd is pointer to the command structure XST_SUCCESS always.
static int XPlmi_Write64(XPlmi_Cmd *Cmd)
This function provides 64 bit write command execution.
Command payload parameters are - High Address - Low Address - Value Cmd is pointer to the command structure XST_SUCCESS always.
static int XPlmi_DmaXfer(XPlmi_Cmd *Cmd)
This function provides DMA Xfer command execution.
Command payload parameters are - High Src Addr - Low Src Addr - High Dest Addr - Low Dest Addr - Params - AXI burst type (Fixed/INCR) Cmd is pointer to the command structure XST_SUCCESS on success and error code on failure
static int XPlmi_InitSeq(XPlmi_Cmd *Cmd)
This function provides INIT_SEQ command execution.
Command payload parameters are - DATA Cmd is pointer to the command structure and unused XPLMI_ERR_CMD_NOT_SUPPORTED always.
u32 XPlmi_GetReadbackLen(u32 Len)
This function processes and provides readback length.
Len is the current readback length Readback length
static int XPlmi_CfiRead(XPlmi_Cmd *Cmd)
This function provides CFI READ command execution.
Command payload parameters are - Params - SMPA/JTAG/DDR - High Dest Addr - Low Dest Addr - Read Length in number of words to be read from CFU - DATA (CFU READ Packets) Cmd is pointer to the command structure XST_SUCCESS on success.XPLMI_ERR_READBACK_BUFFER_OVERFLOW if readback buffer overflows.
static int XPlmi_Set(XPlmi_Cmd *Cmd)
This function provides SET command execution.
Command payload parameters are - High Dest Addr - Low Dest Addr - Length (Length of words to set to value) - Value Cmd is pointer to the command structure XST_SUCCESS always.
static int XPlmi_DmaWriteKeyHole(XPlmi_Cmd *Cmd)
This function provides DMA key hole write command execution.
Command payload parameters are - High Dest Addr - Low Dest Addr - Keyhole Size in bytes - DATA Cmd is pointer to the command structure XST_SUCCESS on success and error code on failure
static int XPlmi_SetBoard(XPlmi_Cmd *Cmd)
This function provides SET BOARD command execution.
Command payload parameters are - Board Name Cmd is pointer to the command structure XST_SUCCESS always.
static int XPlmi_GetBoard(XPlmi_Cmd *Cmd)
This function provides GET BOARD command execution.
Cmd is pointer to the command structure Command payload parameters are High AddrLow AddrMax size in words XST_SUCCESS on success and error code on failure
static int XPlmi_SetWdtParam(XPlmi_Cmd *Cmd)
This function sets the WDT parameters used in PLM.
Cmd is pointer to the command structure Command payload parameters are Node Id for PMC, PS MIOPeriodicity XST_SUCCESS on success and error code on failure
static int XPlmi_LogString(XPlmi_Cmd *Cmd)
This function adds Debug string to PLM logs.
Cmd is pointer to the command structure Command payload parameters are Debug String XST_SUCCESS always.
static int XPlmi_LogAddress(XPlmi_Cmd *Cmd)
This function reads the value at an address and displays and adds the value to PLM logs.
Cmd is pointer to the command structure Command payload parameters are Low AddressHigh Address (Optional) XST_SUCCESS always.
static int XPlmi_Marker(XPlmi_Cmd *Cmd)
This function provides Marker command execution.
Cmd is pointer to the command structure Command payload parameters are TypeString XST_SUCCESS always.
int XPlmi_MoveBuffer(u32 BufferIndex, XPlmi_BufferList *BufferList)
This function provides functionality to move procs when proc command is received for existing BufferId.
BufferIndex is the index of BufferId to be moved BufferList is the list of buffers whose buffers need to be moved XST_SUCCESS on success and error code on failure
References XPlmi_DmaTransfer, XPLMI_WORD_LEN.
Referenced by XPlmi_StoreBuffer.
int XPlmi_SetBufferList(u32 Address, u16 Size)
This function sets PSM BufferList address to given Address and Size.
Address is the address of Buffer reserved memory for PSM BufferList Size is the size of Buffer reserved memory for PSM BufferList in bytes XST_SUCCESS on success and error code on failureXPLMI_ERR_PROC_INVALID_ADDRESS_RANGE if provided proc address is invalid.
References XPLMI_ERR_PROC_INVALID_ADDRESS_RANGE, XPlmi_GetBufferList.
int XPlmi_SearchBufferList(XPlmi_BufferList *BufferList, u32 BufferId, u64 *BufAddr, u32 *BufLen)
This function searches Buffer list with the buffer Id to provide buffer address and buffer length.
BufferList is the pointer to the list of buffers to search BufferId is the id of the buffer to search for BufAddr is the address of the Buffer found BufLen is the length of the Buffer found XST_SUCCESS on success.XPLMI_ERR_BUFFER_MEM_NOT_AVAILABLE if Buffer memory is not available for storing.XPLMI_ERR_PROCID_NOT_VALID if provided proc id is invalid.
References XPLMI_ERR_BUFFER_MEM_NOT_AVAILABLE, XPLMI_ERR_PROCID_NOT_VALID, XPLMI_WORD_LEN.
Referenced by XPlmi_ExecuteProc, XPlmi_ListMaskPoll, XPlmi_ListMaskWrite, XPlmi_ListWrite.
int XPlmi_ExecuteProc(u32 ProcId)
This function provides functionality to execute given ProcId when request to execute a particular ProcId.
ProcId is ProcId to be executed XST_SUCCESS on success.XPLMI_ERR_PROC_LPD_NOT_INITIALIZED The Proc command cannot be executed because the LPD is not initialized.
References XPLMI_ERR_PROC_LPD_NOT_INITIALIZED, XPlmi_GetBufferList, XPlmi_MemSetBytes, XPlmi_ProcessCdo, XPlmi_SearchBufferList.
Referenced by XPlmi_HandleLinkDownError, XPlmi_HandleLinkUpEvent, XPlmi_RunProc.
static int XPlmi_Proc(XPlmi_Cmd *Cmd)
This function copies the proc data to reserved PSM/PMC RAM when proc command is received.
Cmd is pointer to the command structure Command payload parameters are ProcIdData XST_SUCCESS on success.XPLMI_ERR_PROC_LPD_NOT_INITIALIZED The Proc command cannot be stored because the LPD is not initialized.
int XPlmi_StoreBuffer(XPlmi_Cmd *Cmd, u32 BufferId, XPlmi_BufferList *BufferList)
This function stores the buffer data into the buffer list provided.
Cmd is pointer to the command structure BufferId is the Id of the Buffer to be stored in the buffer list BufferList is the pointer to the BufferList XST_SUCCESS on success.XPLMI_ERR_BUFFER_MEM_NOT_AVAILABLE if Buffer memory is not available for storing.XPLMI_UNSUPPORTED_PROC_LENGTH if received proc does not fit in proc memory.XPLMI_MAX_PROC_COMMANDS_RECEIVED on maximum supported proc commands received.
References XPlmi_DmaTransfer, XPLMI_ERR_BUFFER_MEM_NOT_AVAILABLE, XPLMI_MAX_PROC_COMMANDS_RECEIVED, XPlmi_MoveBuffer, XPLMI_UNSUPPORTED_PROC_LENGTH, XPLMI_WORD_LEN.
Referenced by XPlmi_ListSet.
static int XPlmi_OTCheck(XPlmi_Cmd *Cmd)
This function provides Over Temperature Check command execution.
Cmd is pointer to the command structure Command payload parameters are Delay in milliseconds XST_SUCCESS always.
static int XPlmi_Begin(XPlmi_Cmd *Cmd)
This function provides start of the block.
Command payload parameters are - Offset : specifies no. of words until "end" of the block - String : optional for debugging purpose Cmd is pointer to the command structure XST_SUCCESS on success and error code on failure
static int XPlmi_End(XPlmi_Cmd *Cmd)
This function provides end of the block.
Cmd is pointer to the command structure XST_SUCCESS on success and error code on failure
static int XPlmi_Break(XPlmi_Cmd *Cmd)
This function skips all the commands until the Levels number of nested "end".
Cmd is pointer to the command structure XST_SUCCESS on success and error code on failure
static int XPlmi_SetIpiAccess(XPlmi_Cmd *Cmd)
This function sets ipi access permissions for the range of commands requested.
Cmd is pointer to the command structure Command payload parameters are Api Id Upper Limit, Api Id Lower Limit, Module IdAccess Permission Mask XST_SUCCESS on success. XPLMI_ERR_SET_IPI_INVALID_API_ID_UPPER if the Api Id Upper limit is greater than maximum api countXPLMI_ERR_SET_IPI_INVALID_API_ID_LOWER if the Api Id Lower limit is greater than Api Id upper limitXPLMI_ERR_SET_IPI_ACCESS_PERM_NOT_SET if the Ipi Access permission is not set properlyXPLMI_ERR_SET_IPI_PERM_BUFF_NOT_REGISTERED if the permission buffer in which the access permissions has to be stored is not registered
static int XPlmi_TamperTrigger(XPlmi_Cmd *Cmd)
This function triggers secure lockdown when Tamper Trigger IPI is received.
Cmd is pointer to the command structure Command payload parameters are Tamper Response XST_SUCCESS on success.XPLMI_INVALID_TAMPER_RESPONSE on invalid tamper response received for TamperTrigger IPI call.
int XPlmi_SetDDRMCMainRegSts(u32 DDRMCNum, u32 RegSts)
This function sets the access status of DDR MC main registers.
DDRMCNum - DDR MC number RegSts - To be set status(Busy/Free) XST_SUCCESS on success.error code on failure
References MAX_DEV_DDRMC, XPLMI_DDRMC_UB0_BASE_ADDR, XPLMI_DDRMC_UB1_BASE_ADDR, XPLMI_DDRMC_UB2_BASE_ADDR, XPLMI_DDRMC_UB3_BASE_ADDR, XPLMI_DDRMC_UB_PCSR_LOCK_OFFSET, XPLMI_DDRMC_UB_PMC2UB_GPI1_OFFSET, XPLMI_ERR_INVALID_PARAM, XPlmi_UtilRMW.
static int XPlmi_SetDDRMCRegStsCmdHandler(XPlmi_Cmd *Cmd)
This function handles XPlmi_SetDDRMCRegSts command.
Cmd is pointer to the command structure Command payload parameters are DDR MC numberTo be set status(Busy/Free) XST_SUCCESS on success.error code on failure
static int XPlmi_InvalidCmdHandler(u32 *Payload, u32 *RespBuf)
This function calls the handler for invalid commands.
Payload is pointer to payload data RespBuf buffer to store response of slaves XST_SUCCESS on successful communication error code On failure