server/xplmi_generic.h
XPLMI_MAX_NAME_LEN
XPLMI_MAX_NAME_WORDS
XPLMI_SBI_DEST_ADDR
XPLMI_READBK_INTF_TYPE_SMAP
XPLMI_READBK_INTF_TYPE_JTAG
XPLMI_READBK_INTF_TYPE_DDR
XPLMI_READBACK_DEF_DST_ADDR
XPLMI_READBACK_SRC_MASK
XPLMI_READBACK_SLR_TYPE_MASK
XPLMI_READBACK_SLR_TYPE_SHIFT
XPLMI_READBACK_SLR_TYPE_1
XPLMI_READBACK_SLR_TYPE_2
XPLMI_READBACK_SLR_TYPE_3
XPLMI_MASK_POLL_MIN_TIMEOUT
XPLMI_MAXOUT_CMD_MIN_VAL
XPLMI_MAXOUT_CMD_DEF_VAL
XPLMI_CFI_DATA_OFFSET
XPLMI_SIXTEEN_BYTE_MASK
XPLMI_NUM_BITS_IN_WORD
XPLMI_MASKPOLL_LEN_EXT
XPLMI_MASKPOLL64_LEN_EXT
XPLMI_MASKPOLL_FLAGS_MASK
XPLMI_MASKPOLL_FLAGS_SUCCESS
XPLMI_MASKPOLL_FLAGS_DEFERRED_ERR
XPLMI_MASKPOLL_FLAGS_BREAK
XPLMI_MASKPOLL_FLAGS_BREAK_LEVEL_MASK
XPLMI_MASKPOLL_FLAGS_BREAK_LEVEL_SHIFT
XPLMI_MASKPOLL_FLAGS_DISABLE_MINIMAL_TIMEOUT
if bit 31 in flags is set, then disable minimal timeout.
XPLMI_MASK_POLL_32BIT_TYPE
XPLMI_MASK_POLL_64BIT_TYPE
XPLMI_LIST_MASK_POLL_32BIT_TYPE
XPLMI_PLM_GENERIC_CMD_ID_MASK
XPLMI_PLM_MODULES_FEATURES_VAL
XPLMI_PLM_GENERIC_DEVICE_ID_VAL
XPLMI_PLM_GENERIC_EVENT_LOGGING_VAL
XPLMI_PLM_MODULES_GET_BOARD_VAL
XPLMI_PLM_GENERIC_TAMP_TRIGGER_VAL
XPLMI_PLM_LOADER_SET_IMG_INFO_VAL
XPLMI_BREAK_LEVEL_MASK
XPLMI_PSM_BUFFER_LIST
XPLMI_PMC_BUFFER_LIST
XPLMI_ADDR_BUFFER_LIST
XPLMI_PMC_RAM_PROC_ID_MASK
XPLMI_SLD_PROC_ID
void XPlmi_GenericInit(void)
int XPlmi_ExecuteProc(u32 ProcId)
This function provides functionality to execute given ProcId when request to execute a particular ProcId.
ProcId is ProcId to be executed XST_SUCCESS on success.XPLMI_ERR_PROC_LPD_NOT_INITIALIZED The Proc command cannot be executed because the LPD is not initialized.
References XPlmi_GetBufferList, XPLMI_ERR_PROC_LPD_NOT_INITIALIZED, XPlmi_MemSetBytes, XPlmi_SearchBufferList, XPlmi_ProcessCdo.
Referenced by XPlmi_HandleLinkDownError, XPlmi_HandleLinkUpEvent, XPlmi_RunProc.
int XPlmi_SetBufferList(u32 Address, u16 Size)
This function sets PSM BufferList address to given Address and Size.
Address is the address of Buffer reserved memory for PSM BufferList Size is the size of Buffer reserved memory for PSM BufferList in bytes XST_SUCCESS on success and error code on failureXPLMI_ERR_PROC_INVALID_ADDRESS_RANGE if provided proc address is invalid.
References XPlmi_GetBufferList, XPLMI_ERR_PROC_INVALID_ADDRESS_RANGE.
XPlmi_BufferList * XPlmi_GetBufferList(u32 BufferListType)
This function defines BufferList and returns the address of the same.
BufferListType is the proc list type if it is stored in PMC or PPU RAM BufferList is the address of BufferList structure BufferListType is the proc list type if it is stored in PMC or PSM RAM. BufferList is the address of BufferList structure. BufferListType is the proc list type if it is stored in PMC or PSM RAM BufferList is the address of BufferList structure BufferListType is the proc list type if it is stored in PMC or PSM RAM BufferList is the address of BufferList structure BufferListType is the proc list type if it is stored in PMC or PPU RAM BufferList is the address of BufferList structure BufferListType is the proc list type if it is stored in PMC or PSM RAM. BufferList is the address of BufferList structure.
References XPLMI_MAX_PMC_BUFFERS, EXPORT_GENERIC_DS, XPLMI_PPU_BUFFER_DS_ID, XPLMI_PPU_BUFFER_DS_VER, XPLMI_PPU_BUFFER_DS_LCVER, XPLMI_PMC_BUFFER_DS_ID, XPLMI_PMC_BUFFER_DS_VER, XPLMI_PMC_BUFFER_DS_LCVER, XPLMI_PPU_BUFFER_LIST_DS_ID, XPLMI_PPU_BUFFER_LIST_DS_VER, XPLMI_PPU_BUFFER_LIST_DS_LCVER, XPLMI_PMC_BUFFER_LIST_DS_ID, XPLMI_PMC_BUFFER_LIST_DS_VER, XPLMI_PMC_BUFFER_LIST_DS_LCVER.
Referenced by XPlmi_SetBufferList, XPlmi_ExecuteProc, XPlmi_PsmSequence.
int XPlmi_DmaTransfer(u64 Dest, u64 Src, u32 Len, u32 Flags)
This function provides functionality for DMA write.
Dest is the destination address Src is the source address Len is the number of words to be transferred Flags is the DMA transfer related flags XST_SUCCESS on success.XPLMI_ERR_UNALIGNED_DMA_XFER if unaligned DMA transfer fails.
References XPLMI_ERR_UNALIGNED_DMA_XFER, XPLMI_WORD_LEN, XPlmi_DmaXfr.
Referenced by XPlmi_MoveBuffer, XPlmi_StoreBuffer, XPlmi_PsmSequence.
int XPlmi_GetJumpOffSet(XPlmi_Cmd *Cmd, u32 LevelVal)
int XPlmi_MoveBuffer(u32 BufferIndex, XPlmi_BufferList *BufferList)
This function provides functionality to move procs when proc command is received for existing BufferId.
BufferIndex is the index of BufferId to be moved BufferList is the list of buffers whose buffers need to be moved XST_SUCCESS on success and error code on failure
References XPLMI_WORD_LEN, XPlmi_DmaTransfer.
Referenced by XPlmi_StoreBuffer.
int XPlmi_StoreBuffer(XPlmi_Cmd *Cmd, u32 BufferId, XPlmi_BufferList *BufferList)
This function stores the buffer data into the buffer list provided.
Cmd is pointer to the command structure BufferId is the Id of the Buffer to be stored in the buffer list BufferList is the pointer to the BufferList XST_SUCCESS on success.XPLMI_ERR_BUFFER_MEM_NOT_AVAILABLE if Buffer memory is not available for storing.XPLMI_UNSUPPORTED_PROC_LENGTH if received proc does not fit in proc memory.XPLMI_MAX_PROC_COMMANDS_RECEIVED on maximum supported proc commands received.
References XPLMI_ERR_BUFFER_MEM_NOT_AVAILABLE, XPLMI_UNSUPPORTED_PROC_LENGTH, XPlmi_MoveBuffer, XPLMI_MAX_PROC_COMMANDS_RECEIVED, XPlmi_DmaTransfer, XPLMI_WORD_LEN.
Referenced by XPlmi_ListSet.
int XPlmi_SearchBufferList(XPlmi_BufferList *BufferList, u32 BufferId, u64 *BufAddr, u32 *BufLen)
This function searches Buffer list with the buffer Id to provide buffer address and buffer length.
BufferList is the pointer to the list of buffers to search BufferId is the id of the buffer to search for BufAddr is the address of the Buffer found BufLen is the length of the Buffer found XST_SUCCESS on success.XPLMI_ERR_BUFFER_MEM_NOT_AVAILABLE if Buffer memory is not available for storing.XPLMI_ERR_PROCID_NOT_VALID if provided proc id is invalid.
References XPLMI_ERR_BUFFER_MEM_NOT_AVAILABLE, XPLMI_ERR_PROCID_NOT_VALID, XPLMI_WORD_LEN.
Referenced by XPlmi_ExecuteProc, XPlmi_ListWrite, XPlmi_ListMaskWrite, XPlmi_ListMaskPoll.
int XPlmi_GenericMaskPoll(XPlmi_Cmd *Cmd, u64 Addr, u32 Type)
This function provides generic implementation for both 32-bit and 64-bit mask poll command execution.
Command payload parameters are - Address - Mask - Expected Value - Timeout in us - Deferred Error flag - Optional 0 - Return error in case of failure, 1 - Ignore error, return success always 2 - Defer error till the end of partition load 3 - Break to end offset in case of failure - Error Code Cmd is pointer to the command structure Addr is address of mask poll Type is flag indicating if the address is 64-bit XST_SUCCESS on success.XST_FAILURE if timedout.
References XPlmi_GetTimerValue, XPlmi_UtilPoll64, XPlmi_UtilPoll, XPlmi_MeasurePerfTime.
Referenced by XPlmi_ListMaskPoll.
u32 XPlmi_GetReadbackLen(u32 Len)
This function processes and provides readback length.
Len is the current readback length Readback length
int XPlmi_SetDDRMCMainRegSts(u32 DDRMCNum, u32 RegSts)
This function sets the access status of DDR MC main registers.
DDRMCNum - DDR MC number RegSts - To be set status(Busy/Free) XST_SUCCESS on success.error code on failure
References MAX_DEV_DDRMC, XPLMI_DDRMC_UB0_BASE_ADDR, XPLMI_DDRMC_UB1_BASE_ADDR, XPLMI_DDRMC_UB2_BASE_ADDR, XPLMI_DDRMC_UB3_BASE_ADDR, XPLMI_ERR_INVALID_PARAM, XPLMI_DDRMC_UB_PMC2UB_GPI1_OFFSET, XPLMI_DDRMC_UB_PCSR_LOCK_OFFSET, XPlmi_UtilRMW.
XPlmi_BoardParams * XPlmi_GetBoardParams(void)
This function provides pointer to BoardParams.
Pointer to BoardParams Pointer to BoardParams. Pointer to BoardParams Pointer to BoardParams.
References EXPORT_GENERIC_DS, XPLMI_BOARD_PARAMS_DS_ID, XPLMI_BOARD_PARAMS_VERSION, XPLMI_BOARD_PARAMS_LCVERSION.