xplmi_debug.c
int XPlmi_InitUart(void)
This function initializes the PS UART.
XST_SUCCESS on success.XPLMI_ERR_UART_MEMSET on UART instance failure.XPLMI_ERR_UART_LOOKUP if UART driver lookup fails.XPLMI_ERR_UART_CFG if UART driver configuration fails.XPLMI_ERR_UART_PSV_SET_BAUD_RATE if failed to set the baud rate.
References UART_INITIALIZED, UART_PRINT_ENABLED, XPLMI_ERR_UART_CFG, XPLMI_ERR_UART_LOOKUP, XPLMI_ERR_UART_MEMSET, XPLMI_ERR_UART_PSV_SET_BAUD_RATE, XPlmi_GetUartBaseAddr, XPlmi_MemSetBytes, XPlmi_SetLpdInitialized.
Referenced by XPlmi_LpdInit.
int XPlmi_ConfigUart(u8 UartSelect, u8 UartEnable)
This function configures the PS UART base address.
UartSelect is the uart number to be selected UartEnable is the flag used to enable or disable uart XST_SUCCESS on success.XPLMI_ERR_NO_UART_PRESENT if UART is not available to configure.XPLMI_ERR_CURRENT_UART_INVALID if selected UART base address is invalid.XPLMI_ERR_INVALID_UART_SELECT if invalid UART SELECT argument is passed.XPLMI_ERR_INVALID_UART_ENABLE if invalid UART ENABLE argument is passed.
References UART_PRINT_ENABLED, XPLMI_ERR_CURRENT_UART_INVALID, XPLMI_ERR_INVALID_UART_ENABLE, XPLMI_ERR_INVALID_UART_SELECT, XPLMI_ERR_NO_UART_PRESENT, XPlmi_GetUartBaseAddr, XPlmi_SetLpdInitialized, XPlmi_UnSetLpdInitialized.
Referenced by XPlmi_EventLogging.
void outbyte(char c)
This function prints and logs the terminal prints to debug log buffer.
c is the character to be printed and logged
References XPlmi_GetUartBaseAddr.
void XPlmi_Print(u16 DebugType, const char8 *Ctrl1,...)
This function prints debug messages with timestamp.
DebugType is the PLM Debug level for the message Ctrl1 is the format specified string to print
References XPlmi_PrintPlmTimeStamp.
Referenced by XPlmi_ScatterWrite, XPlmi_ScatterWrite2, XPlmi_SetFipsKatMask.