xplmi_update.h
XPLMI_STORE_DATABASE
Store database.
Referenced by XPlmi_DsOps.
XPLMI_RESTORE_DATABASE
Restore database.
Referenced by XPlmi_DsOps, XPlmi_RestoreDataBackup.
DSVER_ATTR
Data structure versions section attribute.
DSENTRY_ATTR
Data structure entries section attribute.
XPLMI_INIT_DS_VER_HDR
Data structure version header initialization.
EXPORT_DS_W_HANDLER
Data structure with custom write handler.
EXPORT_DS
Data structure with default write handler.
EXPORT_GENERIC_DS
Generic data structure.
EXPORT_LOADER_DS
Loader data structure.
EXPORT_SEM_DS
Semaphore data structure.
EXPORT_XILSECURE_DS
XilSecure data structure.
EXPORT_XILPSM_DS
XilPSM data structure.
EXPORT_ERROR_DS
Error data structure.
EXPORT_STL_DS
STL data structure.
EXPORT_OCP_DS
OCP data structure.
typedef int(* XPlmi_CompatibilityCheck_t)(u32 PdiAddr))(u32 PdiAddr)
typedef int(* XPlmi_IsPdiAddrLookup_t)(u32 PdiId, u64 *PdiAddr))(u32 PdiId, u64 *PdiAddr)
typedef int(* XPlmi_CheckPsmPresenceInOD_t)(u32 PdiAddr))(u32 PdiAddr)
int XPlmi_PlmUpdate(XPlmi_Cmd *Cmd)
This function does In-Place PLM Update.
Cmd is the command pointer of in place update command XST_SUCCESS if success.XPLMI_ERR_INPLACE_UPDATE_IN_PROGRESS if a task cannot be executed as the update is in progress.XPLMI_ERR_INPLACE_UPDATE_DISABLED if PLM Update is disabled in ROM_RSV efuse.XPLMI_ERR_INVALID_RSVD_DDR_REGION_UPDATE if invalid/no DDR region reserved for PLM.XPLMI_ERR_INPLACE_UPDATE_SHUTDOWN_INIT if failed to shutdown initiate of modules during InPlace PLM UpdateXPLMI_ERR_INPLACE_UPDATE_TASK_NOT_FOUND if PLM Update task is not found.XPLMI_ERR_INPLACE_UPDATE_INVALID_PAYLOAD_LEN if Invalid Payload Len.XPLMI_ERR_INPLACE_UPDATE_FROM_IMAGE_STORE error during update from IS.
References XPLMI_MODULE_NO_OPERATION, XPLMI_UPDATE_PAYLOAD_LEN, XPLMI_ERR_INPLACE_UPDATE_INVALID_PAYLOAD_LEN, XPlmi_IsPlmUpdateInProgress, XPLMI_ERR_INPLACE_UPDATE_IN_PROGRESS, XPLMI_RTCFG_PLM_RSVD_DDR_ADDR, XPLMI_RTCFG_PLM_RSVD_DDR_SIZE, XPLMI_INVALID_PLM_RSVD_DDR_ADDR, XPLMI_INVALID_PLM_RSVD_DDR_SIZE, XPLMI_ERR_INVALID_RSVD_DDR_REGION_UPDATE, XPLMI_ERR_INSUFFICIENT_PLM_RSVD_DDR_REGION, XPLMI_UPDATE_FLAG_MASK, XPLMI_UPDATE_USING_IMAGE_STORE, XPLMI_RTCFG_IMG_STORE_ADDRESS_HIGH, XPLMI_ERR_INPLACE_UPDATE_FROM_IMAGE_STORE, XPLMI_ERR_INPLACE_UPDATE_DISABLED, XPLMI_UPDATE_IN_PROGRESS, XPLMI_MODULE_SHUTDOWN_INITIATE, XPLMI_ERR_INPLACE_UPDATE_SHUTDOWN_INIT, XPLMI_RTCFG_INPLACE_UPDATE_IPI_MASK, XPLMI_RTCFG_INPLACE_UPDATE_IPI_RESP_BUFF, XPlmi_GetTaskInstance, XPLMI_UPDATE_TASK_ID, XPLMI_ERR_INPLACE_UPDATE_TASK_NOT_FOUND, XPlmi_TaskTriggerNow, XPLMI_MODULE_SHUTDOWN_ABORT.
Referenced by XPlmi_InPlacePlmUpdate.
int XPlmi_RestoreDataBackup(void)
This function restore all the data structures after InPlace PLM update.
XST_SUCCESS on success.XPLMI_ERR_DB_HDR_VERSION_MISMATCH if the DB Hdr version of old PLM is not matching with that of updated PLM.XPLMI_ERR_DB_HDR_SIZE_MISMATCH if the DB Hdr size of old PLM is not matching with the size of updated PLM.XPLMI_ERR_DB_ENDADDR_INVALID if the DB end address calculated is not in a valid range that is accepted by updated PLM. Data Structures during InPlace PLM Update.XPLMI_ERR_INVALID_RESTORE_DS_HANDLER if invalid Data Structure Handler used in restoring of Data Structures during InPlace PLM Update.
References XPLMI_UPDATE_DB_VERSION, XPLMI_WORD_LEN, XPlmi_GetDsEntry, XPLMI_DS_CNT, XPLMI_RESTORE_DATABASE, XPLMI_DS_HDR_SIZE.
Referenced by XPlmi_UpdateInit.
int XPlmi_DsOps(u32 Op, u64 Addr, void *Data)
This function does operations like storing, restoring the Data Structure to Memory during PLM update.
Op is the type of operation to be performed on the data structure Addr is the memory address to which data structure should be stored or restored from Data is the Data Structure Entry XST_SUCCESS if success.XPLMI_ERR_INVALID_DS_ENTRY if invalid Data Structure entry is passed to the PLM Db Update Handler.XPLMI_ERR_DS_ALIGNMENT_INCORRECT if the alignment of Data Structure used during store or restore operations is not word aligned Header.XPLMI_ERR_PLM_UPDATE_DB_OVERFLOW if the given Data Structure length is exceed the Update DB buffer available.XPLMI_ERR_MEMCPY_STORE_DB if memcpy failed to store database.XPLMI_ERR_MEMSET_RESTORE_DB if memset failed to restore database.XPLMI_ERR_MEMCPY_RESTORE_DB if memcpy failed to restore database.XPLMI_ERR_PLM_UPDATE_INVALID_OP if invalid operation is passed to PLM Update DB Handler.
References XPLMI_WORD_LEN, XPLMI_DS_HDR_SIZE, XPLMI_STORE_DATABASE, XPLMI_RESTORE_DATABASE.
int XPlmi_UpdateInit(XPlmi_CompatibilityCheck_t CompatibilityHandler, XPlmi_IsPdiAddrLookup_t IsPdiAddrLookupHandler, XPlmi_CheckPsmPresenceInOD_t CheckPsmPresenceHandler)
Db End Address.
This function will initialize In-Place Update related logic CompatibilityHandler is the handler used for compatibility check IsPdiAddrLookupHandler is the PDI address look-up handler CheckPsmPresenceHandler is the PSM presence check handler XST_SUCCESS if success.XPLM_ERR_TASK_CREATE if failed to create a task.XPLMI_ERR_IPI_DRV_INIT if there is a failure in Ipi Driver Init which is done after In-Place update.XPLMI_ERR_MEMSET_UPDATE_RESP if there is a failure in memset of IPI response buffer used to ack the ipi after update.
References PMX_PLM_UPDATE_REASON_MASK, XPLMI_UPDATE_DONE, XPlmi_TaskCreate, XPLM_ERR_TASK_CREATE, XPLMI_UPDATE_TASK_ID, XPlmi_IsPlmUpdateDone, XPLMI_RTCFG_PLM_RSVD_DDR_ADDR, XPLMI_RTCFG_PLM_RSVD_DDR_SIZE, XPLMI_INVALID_PLM_RSVD_DDR_ADDR, XPLMI_INVALID_PLM_RSVD_DDR_SIZE, XPLMI_ERR_INVALID_RSVD_DDR_REGION_RESTORE, XPlmi_RestoreDataBackup, XPlmi_KickWdt.
XPlmi_DsEntry* XPlmi_GetDsEntry(XPlmi_DsEntry *DsList, u32 DsCnt, XPlmi_DsVer *DsVer)
This function returns DsEntry found after searching in the provided DsList.
DsList is the Data Structure List in which the DS is searched DsCnt is the number of Data Structures present in the List DsVer is the version information of the data structure XST_SUCCESS on success and error code on failure
Referenced by XPlmi_RestoreDataBackup.
u32 XPlmi_GetUpdatePdiAddr(void)
This function gets UpdatePdiAddr variable value.
UpdatePdiAddr value
void XPlmi_SetPlmUpdateIpiMask(u32 value)
This function sets PlmUpdateIpiMask variable value.
value of PlmUpdateIpiMask
References XPLMI_RTCFG_INPLACE_UPDATE_IPI_MASK.
u32 XPlmi_GetPlmUpdateIpiMask(void)
This function gets PlmUpdateIpiMask variable value.
PlmUpdateIpiMask value
References XPlmi_GetPlmUpdateIpiMask, XPLMI_RTCFG_INPLACE_UPDATE_IPI_MASK.
Referenced by XPlmi_GetPlmUpdateIpiMask.