xplmi.c
XPlmi_IsAddrRangeValid_t XPlmi_IsAddrRangeValid
< Global address range validation handler
Referenced by XPlmi_Init.
static void XPlmi_PrintEarlyLog(void)
This function prints early log.
int XPlmi_Init(XPlmi_IsAddrRangeValid_t IsAddrRangeValidHandler)
This function will initialize the PLMI module.
IsAddrRangeValidHandler - Function pointer to address range validation handler that validates if a given address range is accessible by the specified subsystem. XST_SUCCESS on success.XPLMI_ERR_PRE_INIT if pre initialization fails.XPLMI_ERR_REGISTER_VERIFY_ADDR_RANGE_HANDLER if handler is NULL.
References XPLMI_ERR_PRE_INIT, XPlmi_IsAddrRangeValid, XPlmi_PreInit, XPlmi_SetPlmLiveStatus, XPlmi_SetUpInterruptSystem.
int XPlmi_RunTimeConfigInit(void)
This function initializes the Runtime Configuration Area with default values.
XST_SUCCESS on success and error code on failure
References XPlmi_IsPlmUpdateDone, XPlmi_IsPlmUpdateDoneTmp, XPlmi_MemSet, XPLMI_PLM_MAJOR_VERSION, XPLMI_PLM_MAJOR_VERSION_SHIFT, XPLMI_PLM_MINOR_VERSION, XPLMI_PLM_MINOR_VERSION_SHIFT, XPLMI_PLM_RC_VERSION, XPLMI_PLM_RC_VERSION_SHIFT, XPLMI_PLM_USER_DEFINED_VERSION, XPlmi_RtcaPlatInit, XPLMI_RTCFG_BASEADDR, XPLMI_RTCFG_DDRMC_CALIB_CHECK_SKIP_ADDR, XPLMI_RTCFG_IMG_STORE_ADDRESS_HIGH, XPLMI_RTCFG_IMG_STORE_ADDRESS_LOW, XPLMI_RTCFG_IMG_STORE_SIZE, XPLMI_RTCFG_LOG_UART_OFFSET.
void XPlmi_LpdInit(void)
This function calls all the PS LPD init functions of all the different modules.
As a part of init functions, modules can register the command handlers, interrupt handlers with the interface layer.
References LPD_INITIALIZED, XPlmi_ErrMgr, XPlmi_InitUart, XPlmi_IsPlmUpdateDone, XPlmi_LogPlmErr, XPlmi_LpdSlcrEmInit, XPlmi_PsEmInit, XPlmi_SetLpdInitialized, XPlmi_UtilRMW, XPLMI_WARNING_MAJOR_MASK.
void XPlmi_PrintPlmBanner(void)
This function prints PLM banner.
References SDK_RELEASE_QUARTER, SDK_RELEASE_YEAR, XPlmi_IsPlmUpdateDone, XPLMI_PLM_BANNER, XPLMI_PMC_VERSION_MASK, XPLMI_PMC_VERSION_SHIFT, XPlmi_PrintRomVersion.
void XPlmi_ResetLpdInitialized(void)
This function resets LpdInitialized variable to 0.
References LPD_WDT_INITIALIZED, XPlmi_DisableWdt, XPlmi_GetLpdInitialized.
void XPlmi_SetLpdInitialized(u32 Flag)
This function sets LpdInitialized variable with given flag.
Flag to set the UART or LPD WDT initialization state.
References XPlmi_GetLpdInitialized.
Referenced by XPlmi_ConfigUart, XPlmi_EnableWdt, XPlmi_InitUart, XPlmi_LpdInit.
void XPlmi_UnSetLpdInitialized(u32 Flag)
This function clears LpdInitialized variable with given flag.
Flag to unset the UART or LPD WDT initialization state.
References XPlmi_GetLpdInitialized.
Referenced by XPlmi_ConfigUart.
void XPlmi_UpdateKatStatus(u32 PlmKatStatus)
This function sets XPLMI_RTCFG_PLM_KAT_ADDR with PlmKatStatus.
PlmKatStatus contains the KAT status updated by PLM
References XPlmi_CheckAndUpdateFipsState, XPLMI_KAT_MASK, XPlmi_UtilRMW.
Referenced by XPlmi_ClearKatMask, XPlmi_SetKatMask.
u32 XPlmi_GetKatStatus(void)
This function is called to get KAT status.
References XPLMI_KAT_MASK.
Referenced by XPlmi_ClearKatMask, XPlmi_SetKatMask.
void XPlmi_SetKatMask(u32 PlmKatMask)
This function sets XPLMI_RTCFG_PLM_KAT_ADDR with PlmKatMask.
PlmKatMask contains the kat mask that needs to be set
References XPlmi_GetKatStatus, XPlmi_UpdateKatStatus.
void XPlmi_ClearKatMask(u32 PlmKatMask)
This function clears XPLMI_RTCFG_PLM_KAT_ADDR with PlmKatMask.
PlmKatMask contains the kat mask that needs to be cleared
References XPlmi_GetKatStatus, XPlmi_UpdateKatStatus.
u32 XPlmi_IsCryptoKatEn(void)
This function will return the crypto kat enable status from efuse cache.
TRUE If crypto kat bit is set FALSE If crypto kat bit is not set
Referenced by XPlmi_IsKatRan.