xplmi_proc.c
XPLMI_MB_MSR_BIP_MASK
Microblaze MSR Break In Progress bit mask.
Referenced by XPlmi_SetUpInterruptSystem.
u32 PmcIroFreq
PmcIroFreq variable stores the frequency of the PMC IRO in Hz.
static void XPlmi_InitPitTimer(u32 Timer, u32 ResetValue)
It initializes the Programmable Interval Timer.
Timer is PIT timer number to be initialized ResetValue is the reset value of timer when started.
static void XPlmi_GetPerfTime(u64 TCur, u64 TStart, u32 IroFreq, XPlmi_PerfTime *PerfTime)
This function prints the total time taken between two points for performance measurement.
TCur is the current time TStart is the start time IroFreq is the frequency at which PMC IRO is running PerfTime is the pointer to variable holding the performance time
u32* XPlmi_GetPmcIroFreq(void)
This function provides the pointer to PmcIroFreq variable.
Pointer to PmcIroFreq variable
Referenced by XPlmi_UtilPollNs.
u64 XPlmi_GetTimerValue(void)
This function is used to read the 64 bit timer value.
It reads from PIT1 and PIT2 and makes it 64 bit.Returns 64 bit timer value
References XPlmi_GetIOModuleInst.
Referenced by XPlmi_DmaXfr, XPlmi_GenericMaskPoll, XPlmi_MeasurePerfTime, XPlmi_SchedulerHandler, XPlmi_SchedulerInit, XPlmi_TaskDispatchLoop, XPlmi_UtilPollNs.
void XPlmi_MeasurePerfTime(u64 TCur, XPlmi_PerfTime *PerfTime)
This function measures the total time taken between two points for performance measurement.
TCur is current time PerfTime is the variable to hold the time elapsed
References XPlmi_GetTimerValue.
Referenced by XPlmi_DmaXfr, XPlmi_GenericMaskPoll, XPlmi_PrintPlmTimeStamp, XPlmi_SchedulerAddTask, XPlmi_TaskDispatchLoop.
void XPlmi_PrintRomTime(void)
This function prints the ROM time.
References XPlmi_GetRomIroFreq.
void XPlmi_PrintPlmTimeStamp(void)
This function prints the PLM time stamp.
References XPlmi_MeasurePerfTime.
Referenced by XPlmi_Print.
int XPlmi_StartTimer(void)
It initializes the IO module structures and PIT timers.
XST_SUCCESS on success.XPLMI_ERR_IOMOD_INIT if IOModdule drive lookup fails.XPLMI_ERR_IOMOD_START if IOModdule drive startup fails.XPLMI_ERR_SET_PMC_IRO_FREQ if failed to set PMC IRO frequency.
References XPLMI_ERR_IOMOD_INIT, XPLMI_ERR_IOMOD_START, XPLMI_ERR_SET_PMC_IRO_FREQ, XPlmi_GetIOModuleInst, XPlmi_IsPlmUpdateDone, XPlmi_SchedulerInit, XPlmi_SetPmcIroFreq.
int XPlmi_SetUpInterruptSystem(void)
This function connects the interrupt handler of the IO Module to the processor.
XST_SUCCESS if handlers are registered properly.XPLMI_ERR_IOMOD_CONNECT if IOModule driver fails to establish connection.
References XPlmi_EnableIomoduleIntr, XPLMI_ERR_IOMOD_CONNECT, XPlmi_GetIOModuleInst, XPlmi_GetTopLevelIntrTbl, XPlmi_GetTopLevelIntrTblSize, XPlmi_IntrHandler, XPLMI_MB_MSR_BIP_MASK, XPlmi_SchedulerHandler.
Referenced by XPlmi_Init.
void XPlmi_IntrHandler(void *CallbackRef)
This function is default interrupt handler for the device.
CallbackRef is presently the interrupt number that is received.
Referenced by XPlmi_SetUpInterruptSystem.
void XPlmi_PlmIntrEnable(u32 IntrId)
This function will enable the Iomodule interrupt.
IntrId Interrupt ID as specified in the xplmi_proc.h
References XPlmi_GetIOModuleInst.
Referenced by XPlmi_ErrorTaskHandler, XPlmi_Versal2Ve2VmEAMHandler.
int XPlmi_PlmIntrDisable(u32 IntrId)
This function will disable the Iomodule interrupt.
IntrId Interrupt ID as specified in the xplmi_proc.h XST_SUCCESS on success and error code on failure
References XPlmi_GetIOModuleInst.
Referenced by XPlmi_ErrIntrHandler, XPlmi_GenericHandler.
int XPlmi_PlmIntrClear(u32 IntrId)
This function will clear the Iomodule interrupt.
IntrId Interrupt ID as specified in the xplmi_proc.h XST_SUCCESS on success and error code on failure
References XPlmi_GetIOModuleInst.
Referenced by XPlmi_ErrorTaskHandler, XPlmi_GenericHandler, XPlmi_IpiIntrHandler, XPlmi_Versal2Ve2VmEAMHandler.
int XPlmi_RegisterHandler(u32 IntrId, GicIntHandler_t Handler, void *Data)
This function will register the handler and enable the Iomodule interrupt.
IntrId Interrupt ID as specified in the xplmi_hw.h Handler to be registered for the interrupt Data to be passed to handler XST_SUCCESS on success.XPLMI_ERR_REGISTER_IOMOD_HANDLER if failed to register the handler.
References XPLMI_ERR_REGISTER_IOMOD_HANDLER, XPlmi_GetIOModuleInst.