xplmi_task.c
struct metal_list TaskQueue[XPLMI_TASK_PRIORITIES][XPLMI_TASK_PRIORITIES]
XPlmi_TaskNode* XPlmi_TaskCreate(TaskPriority_t Priority, int(*Handler)(void *Arg), void *PrivData)
This function creates the task and initializes its fields with the user parameters.
Priority Priority of the task Handler function pointer to the task handler PrivData Private Data to be passed with task handler Pointer to the task node structure
References XPlmi_GetTaskInstance.
Referenced by XPlmi_AsuUpdateInit, XPlmi_EmInit, XPlmi_GicRegisterHandler, XPlmi_RegisterTamperIntrHandler, XPlmi_SchedulerAddTask, XPlmi_UpdateInit.
XPlmi_TaskNode* XPlmi_GetTaskInstance(int(*Handler)(void *Arg), const void *PrivData, const u32 IntrId)
This function returns the instance of the task with matching handler and private data or with matching interrupt id.
Handler is pointer to the task handler PrivData is argument to be passed to the task handler IntrId is the interrupt id associated with the task Instance of the task in case of a match, NULL otherwise
Referenced by XPlmi_AsuUpdate, XPlmi_EmInit, XPlmi_ErrIntrHandler, XPlmi_GicIntrAddTask, XPlmi_IpiIntrHandler, XPlmi_PlmUpdate, XPlmi_RegisterTamperIntrHandler, XPlmi_SchedulerAddTask, XPlmi_TaskCreate.
void XPlmi_TaskTriggerNow(XPlmi_TaskNode *Task)
This function adds the task to the task queue so that it can be triggered based on its priority.
Task Pointer to the task node
Referenced by XPlmi_AsuUpdate, XPlmi_ErrIntrHandler, XPlmi_GicIntrAddTask, XPlmi_IpiIntrHandler, XPlmi_PlmUpdate, XPlmi_SchedulerHandler, XPlmi_TriggerTamperResponse.
void XPlmi_TaskInit(void)
This function initializes the task queues list.
void XPlmi_TaskDispatchLoop(void)
This function will be checking for tasks in the queue based on the priority.
After calling every task handlers, next high priority task will be called.
References XPlmi_ErrMgr, XPlmi_GetTimerValue, XPlmi_MeasurePerfTime, XPlmi_SetPlmLiveStatus.