xplmi_dma.c
XPLMI_XCSUDMA_DEST_CTRL_OFFSET
CSUDMA destination control offset.
XPmcDma PmcDma0
Instance of the Pmc_Dma Device.
XPmcDma PmcDma1
Instance of the Pmc_Dma Device.
XPmcDma_Configure DmaCtrl
static int XPlmi_DmaDrvInit(XPmcDma *DmaPtr, u32 BaseAddress)
This function is used to initialize a single Driver instance.
DmaPtr is pointer to the DMA instance DeviceId of the DMA as defined in xparameters.h XST_SUCCESS on success.XPLMI_ERR_DMA_LOOKUP if DMA driver lookup fails.XPLMI_ERR_DMA_CFG if DMA driver configuration fails.XPLMI_ERR_DMA_SELFTEST if DMA driver self test fails.
static void XPlmi_SSSCfgDmaDma(u32 Flags)
This function is used set SSS configuration for DMA to DMA.
Flags to select PMC DMA
static void XPlmi_SSSCfgDmaPzm(void)
This function is used set SSS configuration for DMA to PZM.
static void XPlmi_SSSCfgSbiDma(void)
This function is used set SSS configuration for SBI to DMA.
static int XPlmi_DmaChXfer(u64 Addr, u32 Len, XPmcDma_Channel Channel, u32 Flags)
This function is used transfer the data on SRC or DST channel.
Addr is address to which data has to be stored Len is length of the data in words Channel is SRC/DST channel selection Flags to select PMC DMA and DMA Burst type XST_SUCCESS on success.XPLMI_ERR_DMA_XFER_WAIT if DMA transfer failed to wait.
static int XPlmi_StartDma(u64 SrcAddr, u64 DestAddr, u32 Len, u32 Flags, XPmcDma **DmaPtrAddr)
This function is used initiate the DMA to DMA transfer.
SrcAddr is address for SRC channel to fetch data from DestAddr is address for DST channel to store the data Len is length of the data in words Flags to select PMC DMA and DMA Burst type DmaPtrAddr is to store address to PmcDmaInstance XST_SUCCESS on success and error codes on failure
int XPlmi_DmaInit(void)
This function will initialize the DMA driver instances.
XST_SUCCESS on success and error code on failure
XPmcDma* XPlmi_GetDmaInstance(UINTPTR BaseAddress)
This function returns DMA instance.
DeviceId is PMC DMA's device ID PMC DMA instance pointer.
int XPlmi_WaitForNonBlkDma(u32 DmaFlags)
This function is used to wait on non blocking DMA.
DmaFlags to differentiate between PMCDMA_0 and PMCDMA_1 XST_SUCCESS on success.XPLMI_ERR_NON_BLOCK_DMA_WAIT_DEST if Non Block Dma transfer wait failed in destination channel WaitForDone.XPLMI_ERR_NON_BLOCK_DMA_WAIT_SRC if Non Block Dma transfer wait failed in source channel WaitForDone.
References XPLMI_ERR_NON_BLOCK_DMA_WAIT_DEST, XPLMI_ERR_NON_BLOCK_DMA_WAIT_SRC.
int XPlmi_WaitForNonBlkSrcDma(u32 DmaFlags)
This function is used set wait on non blocking DMA.
It is called when Src DMA is non blocking. DmaFlags to differentiate between PMCDMA_0 and PMCDMA_1 XST_SUCCESS on success.XPLMI_ERR_NON_BLOCK_SRC_DMA_WAIT if Non Block source Dma transfer wait failed.
References XPLMI_ERR_NON_BLOCK_SRC_DMA_WAIT.
int XPlmi_WaitForNonBlkDestDma(u32 DmaFlags)
This function is used set wait on non blocking DMA.
It is called when Dest DMA is non blocking. DmaFlags to differentiate between PMCDMA_0 and PMCDMA_1 XST_SUCCESS on success.XPLMI_ERR_NON_BLOCK_DEST_DMA_WAIT if Non Block destination Dma transfer wait failed.
References XPLMI_ERR_NON_BLOCK_DEST_DMA_WAIT.
int XPlmi_SbiDmaXfer(u64 DestAddr, u32 Len, u32 Flags)
This function is used to transfer the data from SBI to DMA.
DestAddr to which data has to be stored Len of the data in words Flags to select PMC DMA and DMA Burst type XST_SUCCESS on success and error codes on failure
int XPlmi_DmaSbiXfer(u64 SrcAddr, u32 Len, u32 Flags)
This function is used to transfer the data from DMA to SBI.
SrcAddr for DMA to fetch data from Len of the data in words Flags to select PMC DMA and DMA Burst type XST_SUCCESS on success and error codes on failure
int XPlmi_DmaXfr(u64 SrcAddr, u64 DestAddr, u32 Len, u32 Flags)
This function is used to initiate and complete the DMA to DMA transfer.
SrcAddr for SRC channel to fetch data from DestAddr for DST channel to store the data Len of the data in words Flags to select PMC DMA and DMA Burst type XST_SUCCESS on success.XPLMI_ERR_DMA_XFER_WAIT_SRC if Dma Xfer failed in Src Channel wait for done.XPLMI_ERR_DMA_XFER_WAIT_DEST if Dma Xfer failed in Dest Channel wait for done.
References XPLMI_ERR_DMA_XFER_WAIT_DEST, XPLMI_ERR_DMA_XFER_WAIT_SRC, XPlmi_GetPlmiWaitForDone, XPlmi_GetTimerValue, XPlmi_MeasurePerfTime.
Referenced by XPlmi_DmaTransfer, XPlmi_MemCpy64, XPlmi_MemSet.
int XPlmi_EccInit(u64 Addr, u32 Len)
This function is used to initialize the ECC memory.
Addr is memory address to be initialized Len is size of memory to be initialized in bytes Status of the DMA transfer
References XPLMI_WORD_LEN.
Referenced by XPlmi_InitNVerifyMem, XPlmi_MemSet.
int XPlmi_MemSet(u64 DestAddress, u32 Val, u32 Len)
This function is used to Set the memory with a value.
DestAddress is the address where the val need to be set Val is the value that has to be set Len is size of memory to be set in words Status of the DMA transfer
References XPlmi_DmaXfr, XPlmi_EccInit, XPLMI_WORD_LEN.
Referenced by XPlmi_MemSetBytes, XPlmi_RunTimeConfigInit.
int XPlmi_InitNVerifyMem(u64 Addr, u32 Len)
This function initializes the memory using PZM and verifies by reading back initialized memory.
Addr Memory address to be initialized Len Length of the area to be initialized in bytes XST_SUCCESS on success and error codes on failure
References XPlmi_EccInit, XPLMI_WORD_LEN.
void XPlmi_SetMaxOutCmds(u8 Val)
This function is used to set the MaxOutCmds variable.
This is required to support non blocking DMA. Val to be set
int XPlmi_MemSetBytes(void *const DestPtr, u32 DestLen, u8 Val, u32 Length)
This function is used to Set the memory with a value.
If Len is greater than DestLen, then DestPtr is filled with Val till DestLen bytes and is considered as a failure. DestPtr is the pointer where the val need to be set DestLen is the memory allotted to destination buffer in bytes Val is the value that has to be set Length is size of memory to be set in bytes XST_SUCCESS on success and error code on failure
References XPlmi_MemSet, XPLMI_WORD_LEN.
Referenced by XPlmi_ExecuteProc, XPlmi_InitCdo, XPlmi_InitUart.
int XPlmi_MemCpy64(u64 DestAddress, u64 SrcAddress, u32 Length)
This function can copy the content of memory for both 32 and 64-bit address space.
DestAddress is the address of the destination where content of SrcAddr memory should be copied. SrcAddress is the address of the source where copy should start from. Length is size of memory to be copied in bytes. XST_SUCCESS on success and error code on failure
References XPlmi_DmaXfr, XPLMI_WORD_LEN.