xplmi_update.c
XPLMI_RESET_VECTOR
Reset vector.
XPLMI_ROM_PLM_UPDATE_REQ
ROM PLM update request.
PMX_PLM_UPDATE_REASON_MASK
PMX PLM update reason mask.
Referenced by XPlmi_UpdateInit.
XPLMI_ROM_INT_REASON_CLEAR
ROM initialize reason clear.
PLM_UPDATE_DONE_POLL_TIMEOUT
PLM update done POLL timeout.
XPLMI_UPDATE_DB_VERSION
DB version update.
Referenced by XPlmi_RestoreDataBackup.
XPLMI_DS_HDR_SIZE
Data structure header size.
Referenced by XPlmi_DsOps, XPlmi_RestoreDataBackup.
XPLMI_DS_CNT
Data structure count.
Referenced by XPlmi_RestoreDataBackup.
XPLMI_UPDATE_PDIADDR_VER
PDI Address version update.
XPLMI_UPDATE_PDIADDR_LCVER
PDI Address LC version update.
XPLMI_UPDATE_TASK_ID
Task Id update.
Referenced by XPlmi_PlmUpdate, XPlmi_UpdateInit.
XPLMI_UPDATE_FLAG_MASK
In-Place Update flag Mask.
Referenced by XPlmi_PlmUpdate.
XPLMI_UPDATE_PAYLOAD_LEN
In-Place Update payload len.
Referenced by XPlmi_PlmUpdate.
XPLMI_UPDATE_USING_IMAGE_STORE
In-Place Update using PDI in Image Store,1-DDR Location.
Referenced by XPlmi_PlmUpdate.
XPLMI_UPDATE_IN_PROGRESS
Update in progress.
Referenced by XPlmi_IsPlmUpdateInProgress, XPlmi_PlmUpdate.
XPLMI_UPDATE_DONE
Update done.
Referenced by XPlmi_IsPlmUpdateDone, XPlmi_IsPlmUpdateDoneTmp, XPlmi_UpdateInit.
XPLMI_INVALID_UPDATE_ADDR
Invalid update address.
XPLMI_UPDATE_TASK_DELAY
Update task delay.
XPlmi_CompatibilityCheck_t XPlmi_CompatibilityCheck
XPlmi_IsPdiAddrLookup_t XPlmi_IsPdiAddrLookup
XPlmi_CheckPsmPresenceInOD_t XPlmi_CheckPsmPresenceInOD
XPlmi_DsEntry __data_struct_start[][]
XPlmi_DsEntry __data_struct_end[][]
u32 __update_mgr_b_start[][]
u8 __update_mgr_a_fn_start[][]
u8 __update_mgr_a_fn_end[][]
u8 PlmUpdateState
u8 PlmUpdateStateTmp
u32 UpdatePdiAddr
u32 DbStartAddr
u32 DbEndAddr
Db Start Address.
static int XPlmi_PlmUpdateMgr(void)
This function will Initiate the PLM Update process with ROM.
XST_SUCCESS on success and error code on failure No Functions should be called inside this function as this code will be relocated during run time and the relative jumps used for the function calls can not be resolved. However, inline functions can be used provided they are forced to be inline using compiler attributes.
static int XPlmi_PlmUpdateTask(void *Arg)
This function does In-Place PLM Update.
Arg is the PDI address. XST_SUCCESS if success.XPLMI_ERR_PLM_UPDATE_SHUTDOWN_COMPLETE if failed to shutdown complete of modules during in place PLM update.XPLMI_ERR_STORE_DATA_BACKUP if failed to store the data structure.XPLMI_ERR_MEMCPY_RELOCATE if failed to relocate update manager code.XPLMI_ERR_PLM_UPDATE_RELOCATED_FN if the relocated PLM update function fails.
EXPORT_GENERIC_DS(UpdatePdiAddr, XPLMI_UPDATE_PDIADDR_DS_ID, XPLMI_UPDATE_PDIADDR_VER, XPLMI_UPDATE_PDIADDR_LCVER, sizeof(UpdatePdiAddr),(u32)(UINTPTR)&UpdatePdiAddr)
Macro to Export Data Structures.
Referenced by XPlmi_GetBoardParams, XPlmi_GetBufferList.
int XPlmi_UpdateInit(XPlmi_CompatibilityCheck_t CompatibilityHandler, XPlmi_IsPdiAddrLookup_t IsPdiAddrLookupHandler, XPlmi_CheckPsmPresenceInOD_t CheckPsmPresenceHandler)
Db End Address.
This function will initialize In-Place Update related logic CompatibilityHandler is the handler used for compatibility check IsPdiAddrLookupHandler is the PDI address look-up handler CheckPsmPresenceHandler is the PSM presence check handler XST_SUCCESS if success.XPLM_ERR_TASK_CREATE if failed to create a task.XPLMI_ERR_IPI_DRV_INIT if there is a failure in Ipi Driver Init which is done after In-Place update.XPLMI_ERR_MEMSET_UPDATE_RESP if there is a failure in memset of IPI response buffer used to ack the ipi after update.
References PMX_PLM_UPDATE_REASON_MASK, XPLM_ERR_TASK_CREATE, XPLMI_ERR_INVALID_RSVD_DDR_REGION_RESTORE, XPLMI_INVALID_PLM_RSVD_DDR_ADDR, XPLMI_INVALID_PLM_RSVD_DDR_SIZE, XPlmi_IsPlmUpdateDone, XPlmi_KickWdt, XPlmi_RestoreDataBackup, XPLMI_RTCFG_PLM_RSVD_DDR_ADDR, XPLMI_RTCFG_PLM_RSVD_DDR_SIZE, XPlmi_TaskCreate, XPLMI_UPDATE_DONE, XPLMI_UPDATE_TASK_ID.
u8 XPlmi_IsPlmUpdateDone(void)
This function checks if Inplace PLM update occurs or not.
TRUE if Inplace PLM Update and FALSE otherwise
References XPLMI_UPDATE_DONE.
Referenced by XPlmi_ClearSSSCfgErr, XPlmi_EmInit, XPlmi_ErrMgr, XPlmi_LpdInit, XPlmi_PrintPlmBanner, XPlmi_RunTimeConfigInit, XPlmi_StartTimer, XPlmi_UpdateInit.
u8 XPlmi_IsPlmUpdateDoneTmp(void)
This function checks if Inplace PLM update occurs or not.
TRUE if Inplace PLM Update and FALSE otherwise
References XPLMI_UPDATE_DONE.
Referenced by XPlmi_RunTimeConfigInit.
u8 XPlmi_IsPlmUpdateInProgress(void)
This function checks if Inplace PLM update is in progress or not.
TRUE if Inplace PLM Update is in progress and FALSE otherwise
References XPLMI_UPDATE_IN_PROGRESS.
Referenced by XPlmi_PlmUpdate.
int XPlmi_DsOps(u32 Op, u64 Addr, void *Data)
This function does operations like storing, restoring the Data Structure to Memory during PLM update.
Op is the type of operation to be performed on the data structure Addr is the memory address to which data structure should be stored or restored from Data is the Data Structure Entry XST_SUCCESS if success.XPLMI_ERR_INVALID_DS_ENTRY if invalid Data Structure entry is passed to the PLM Db Update Handler.XPLMI_ERR_DS_ALIGNMENT_INCORRECT if the alignment of Data Structure used during store or restore operations is not word aligned Header.XPLMI_ERR_PLM_UPDATE_DB_OVERFLOW if the given Data Structure length is exceed the Update DB buffer available.XPLMI_ERR_MEMCPY_STORE_DB if memcpy failed to store database.XPLMI_ERR_MEMSET_RESTORE_DB if memset failed to restore database.XPLMI_ERR_MEMCPY_RESTORE_DB if memcpy failed to restore database.XPLMI_ERR_PLM_UPDATE_INVALID_OP if invalid operation is passed to PLM Update DB Handler.
References XPLMI_DS_HDR_SIZE, XPLMI_RESTORE_DATABASE, XPLMI_STORE_DATABASE, XPLMI_WORD_LEN.
XPlmi_DsEntry* XPlmi_GetDsEntry(XPlmi_DsEntry *DsList, u32 DsCnt, XPlmi_DsVer *DsVer)
This function returns DsEntry found after searching in the provided DsList.
DsList is the Data Structure List in which the DS is searched DsCnt is the number of Data Structures present in the List DsVer is the version information of the data structure XST_SUCCESS on success and error code on failure
Referenced by XPlmi_RestoreDataBackup.
int XPlmi_RestoreDataBackup(void)
This function restore all the data structures after InPlace PLM update.
XST_SUCCESS on success.XPLMI_ERR_DB_HDR_VERSION_MISMATCH if the DB Hdr version of old PLM is not matching with that of updated PLM.XPLMI_ERR_DB_HDR_SIZE_MISMATCH if the DB Hdr size of old PLM is not matching with the size of updated PLM.XPLMI_ERR_DB_ENDADDR_INVALID if the DB end address calculated is not in a valid range that is accepted by updated PLM. Data Structures during InPlace PLM Update.XPLMI_ERR_INVALID_RESTORE_DS_HANDLER if invalid Data Structure Handler used in restoring of Data Structures during InPlace PLM Update.
References XPLMI_DS_CNT, XPLMI_DS_HDR_SIZE, XPlmi_GetDsEntry, XPLMI_RESTORE_DATABASE, XPLMI_UPDATE_DB_VERSION, XPLMI_WORD_LEN.
Referenced by XPlmi_UpdateInit.
static int XPlmi_StoreDataBackup(void)
This function store all the data structures before InPlace PLM update.
XST_SUCCESS if success.XPLMI_ERR_MEMSET_DBHDR if memset of DbHdr during store database is failed.XPLMI_ERR_INVALID_STORE_DS_HANDLER if invalid Data Structure Handler used in storing of Data Structures during InPlace PLM Update.
static int XPlmi_ShutdownModules(XPlmi_ModuleOp Op)
This function shutdown all the modules gracefully.
Op is the operation structure passed to determine type of operation and other details XST_SUCCESS on success and error code on failure
static u32 XPlmi_GetPlmDbSize(void)
This function provides the PLM Database Size which has to be stored and restored during the update.
Size of PLM Database
int XPlmi_PlmUpdate(XPlmi_Cmd *Cmd)
This function does In-Place PLM Update.
Cmd is the command pointer of in place update command XST_SUCCESS if success.XPLMI_ERR_INPLACE_UPDATE_IN_PROGRESS if a task cannot be executed as the update is in progress.XPLMI_ERR_INPLACE_UPDATE_DISABLED if PLM Update is disabled in ROM_RSV efuse.XPLMI_ERR_INVALID_RSVD_DDR_REGION_UPDATE if invalid/no DDR region reserved for PLM.XPLMI_ERR_INPLACE_UPDATE_SHUTDOWN_INIT if failed to shutdown initiate of modules during InPlace PLM UpdateXPLMI_ERR_INPLACE_UPDATE_TASK_NOT_FOUND if PLM Update task is not found.XPLMI_ERR_INPLACE_UPDATE_INVALID_PAYLOAD_LEN if Invalid Payload Len.XPLMI_ERR_INPLACE_UPDATE_FROM_IMAGE_STORE error during update from IS.
References XPLMI_ERR_INPLACE_UPDATE_DISABLED, XPLMI_ERR_INPLACE_UPDATE_FROM_IMAGE_STORE, XPLMI_ERR_INPLACE_UPDATE_IN_PROGRESS, XPLMI_ERR_INPLACE_UPDATE_INVALID_PAYLOAD_LEN, XPLMI_ERR_INPLACE_UPDATE_SHUTDOWN_INIT, XPLMI_ERR_INPLACE_UPDATE_TASK_NOT_FOUND, XPLMI_ERR_INSUFFICIENT_PLM_RSVD_DDR_REGION, XPLMI_ERR_INVALID_RSVD_DDR_REGION_UPDATE, XPlmi_GetTaskInstance, XPLMI_INVALID_PLM_RSVD_DDR_ADDR, XPLMI_INVALID_PLM_RSVD_DDR_SIZE, XPlmi_IsPlmUpdateInProgress, XPLMI_MODULE_NO_OPERATION, XPLMI_MODULE_SHUTDOWN_ABORT, XPLMI_MODULE_SHUTDOWN_INITIATE, XPLMI_RTCFG_IMG_STORE_ADDRESS_HIGH, XPLMI_RTCFG_INPLACE_UPDATE_IPI_MASK, XPLMI_RTCFG_INPLACE_UPDATE_IPI_RESP_BUFF, XPLMI_RTCFG_PLM_RSVD_DDR_ADDR, XPLMI_RTCFG_PLM_RSVD_DDR_SIZE, XPlmi_TaskTriggerNow, XPLMI_UPDATE_FLAG_MASK, XPLMI_UPDATE_IN_PROGRESS, XPLMI_UPDATE_PAYLOAD_LEN, XPLMI_UPDATE_TASK_ID, XPLMI_UPDATE_USING_IMAGE_STORE.
Referenced by XPlmi_InPlacePlmUpdate.
u32 XPlmi_GetUpdatePdiAddr(void)
This function gets UpdatePdiAddr variable value.
UpdatePdiAddr value
u32 XPlmi_GetPlmUpdateIpiMask(void)
This function gets PlmUpdateIpiMask variable value.
PlmUpdateIpiMask value
References XPlmi_GetPlmUpdateIpiMask, XPLMI_RTCFG_INPLACE_UPDATE_IPI_MASK.
Referenced by XPlmi_GetPlmUpdateIpiMask.
void XPlmi_SetPlmUpdateIpiMask(u32 value)
This function sets PlmUpdateIpiMask variable value.
value of PlmUpdateIpiMask
References XPLMI_RTCFG_INPLACE_UPDATE_IPI_MASK.