xplmi_err_common.c
s32(* PmSystemShutdown)(u32 SubsystemId, const u32 Type, const u32 SubType, const u32 CmdType))(u32 SubsystemId, const u32 Type, const u32 SubType, const u32 CmdType)
u32 EmSubsystemId
EmSubsystemId variable stores the error management subsystem ID.
static void XPlmi_ErrIntrSubTypeHandler(u32 ErrorNodeId, u32 RegMask)
This function is the interrupt handler for Error subtype subsystem shutdown and subsystem restart.
ErrorNodeId is the node ID for the error event RegMask is the register mask of the error received
static void XPlmi_DumpRegisters(void)
This function dumps the registers which can help debugging.
static void XPlmi_ErrOutNClearFwCR(u32 ErrorId)
This function updates error out count and clears PMC FW_CR error.
ErrorId is the Error number for which error out count to be updated.
void XPlmi_LogPlmErr(int ErrStatusVal)
This function is called for logging PLM error into FW_ERR register.
ErrStatusVal is the error code written to the FW_ERR register
References XPlmi_UtilRMW.
Referenced by XPlmi_CmdExecute, XPlmi_ErrMgr, XPlmi_LpdInit, XPlmi_ProcessCdo.
void XPlmi_ErrMgr(int ErrStatusVal)
This function is called in PLM error cases.
ErrStatusVal is the error code written to the FW_ERR register
References XPlmi_IsPlmUpdateDone, XPlmi_LogPlmErr, XPlmi_PORHandler, XPlmi_SetPlmLiveStatus, XPLMI_SSIT_MASTER_SLR, XPLMI_SSIT_MONOLITIC, XPlmi_TriggerFwNcrError, XPlmi_UtilRMW.
Referenced by XPlmi_HandleLinkDownError, XPlmi_HandleLinkUpEvent, XPlmi_LpdInit, XPlmi_TaskDispatchLoop.
void XPlmi_UpdateErrorSubsystemId(u32 ErrorNodeId, u32 ErrorMasks, u32 SubsystemId)
This function updates the SubystemId for the given error index.
ErrorNodeId is the node Id for the error event ErrorMasks is the Register mask of the Errors SubsystemId is the Subsystem ID for the error node.
References XPlmi_GetErrorTable.
void XPlmi_PORHandler(void)
This function triggers Power on Reset.
References XPlmi_SysmonClkSetIro, XPlmi_UtilRMW.
Referenced by XPlmi_ErrMgr, XPlmi_HandleSwError.
u32 XPlmi_GetErrorId(u32 ErrorNodeId, u32 RegMask)
This function returns Error Id for the given error node type and error mask.
ErrorNodeId is the error node Id. RegMask is register mask of the error. ErrorId value.
Referenced by XPlmi_EmGetAction, XPlmi_ErrPrintToLog, XPlmi_HandleSwError.
static void XPlmi_TriggerSecureLockdown(u32 ErrorNodeId, u32 RegMask)
This function triggers secure lockdown.
ErrorNodeId is the node ID for the error event RegMask is the register mask of the error received
void XPlmi_HandleSwError(u32 ErrorNodeId, u32 RegMask)
This function handles the Software error triggered from within PLM.
ErrorNodeId is the node ID for the error event RegMask is the register mask of the error received
References XPlmi_EmDisable, XPlmi_GetErrorId, XPlmi_GetErrorTable, XPlmi_PORHandler, XPlmi_SoftResetHandler, XPlmi_UpdateNumErrOutsCount.
Referenced by XPlmi_AsuUpdate.
static void XPlmi_DetectAndHandleTamper(void)
This function detects and handles tamper condition in EAM IRQ interrupt handler.
void XPlmi_ErrIntrHandler(void *CallbackRef)
This function is default interrupt handler for EAM error which will add the task to the task queue.
CallbackRef is presently the interrupt number that is received
References XPlmi_ErrorTaskHandler, XPlmi_GetTaskInstance, XPlmi_PlmIntrDisable, XPlmi_TaskTriggerNow.
int XPlmi_ErrorTaskHandler(void *Data)
This function is the interrupt handler for the EAM errors.
Data is presently passed as NULL XST_SUCCESS always.
References GET_PMC_ERR_ACTION_OFFSET, GET_PMC_IRQ_MASK, XPlmi_EmClearError, XPlmi_EmDisable, XPlmi_ErrPSMIntrHandler, XPlmi_GetErrorTable, XPlmi_PlmIntrClear, XPlmi_PlmIntrEnable, XPlmi_Versal2Ve2VmEAMHandler.
Referenced by XPlmi_EmInit, XPlmi_ErrIntrHandler.
void XPlmi_EmClearError(XPlmi_EventType ErrorNodeType, u32 ErrorId)
This function clears any previous errors before enabling them.
ErrorNodeType is the node type for the error event ErrorId is the index of the error to be cleared
References XPlmi_GetErrorTable, XPlmi_GetEventIndex.
Referenced by XPlmi_EmSetAction, XPlmi_ErrorTaskHandler, XPlmi_Versal2Ve2VmEAMHandler.
u32 EmDisableErrAction(u32 ErrMaskRegAddr, u32 RegMask)
This function disables the error action for the given error mask.
ErrMaskRegAddr is the error action mask register address RegMask is the register mask of the error to be disabled XST_SUCCESS on success.XPLMI_ERROR_ACTION_NOT_DISABLED if error action is not disabled.
Referenced by XPlmi_EmDisablePmcErrors, XPlmi_EmDisablePsmErrors, XPlmi_GenericHandler.
static int EmEnableErrAction(u32 ErrMaskRegAddr, u32 RegMask)
This function enables the error action for the given error mask.
ErrMaskRegAddr is the error action mask register address RegMask is the register mask of the error to be disabled XST_SUCCESS on success.XPLMI_ERROR_ACTION_NOT_ENABLED if error action is not enabled.
int XPlmi_EmDisablePmcErrors(u32 RegOffset, u32 RegMask)
This function disables the PMC error actions for the given mask.
RegOffset is the offset for the PMC ERR, POR ,IRQ mask,SRST mask RegMask is the register mask of the error to be disabled XST_SUCCESS on success.XPLMI_ERROR_ACTION_NOT_DISABLED if error action is not disabled.
References EmDisableErrAction, GET_PMC_ERR_OUT_MASK, GET_PMC_IRQ_MASK, GET_PMC_POR_MASK, GET_PMC_SRST_MASK.
Referenced by XPlmi_EmDisable, XPlmi_EmInit.
int XPlmi_EmDisable(u32 ErrorNodeId, u32 RegMask)
This function disables the responses for the given error.
ErrorNodeId is the node Id for the error event RegMask is the register mask of the error to be disabled XST_SUCCESS on success.XPLMI_ERROR_ACTION_NOT_DISABLED if error action is not disabled.XPLMI_INVALID_ERROR_TYPE on invalid error type.
References GET_PMC_ERR_ACTION_OFFSET, XPlmi_EmDisableLpdSlcrErrors, XPlmi_EmDisablePmcErrors, XPlmi_EmDisablePsmErrors, XPlmi_GetEventIndex.
Referenced by XPlmi_EmSetAction, XPlmi_ErrorTaskHandler, XPlmi_HandleSwError, XPlmi_Versal2Ve2VmEAMHandler.
static int XPlmi_EmEnableAction(XPlmi_EventType ErrorNodeType, u32 RegMask, u8 Action)
This function enables HW error actions for the given Error.
ErrorNodeType is the node type for the error event RegMask is the register mask of the error to be enabled Action is the HW Error action of the error to be enabled XST_SUCCESS on success.XPLMI_ERROR_ACTION_NOT_ENABLED if error action is not enabled.XPLMI_INVALID_ERROR_ACTION on invalid error action.XPLMI_INVALID_ERROR_TYPE on invalid error type.
int XPlmi_EmConfig(XPlmi_EventType NodeType, u32 ErrorId, u8 ActionId, XPlmi_ErrorHandler_t ErrorHandler, const u32 SubsystemId)
This function configures the Action specified for a given Error ID.
NodeType is the error node type ErrorId is the index of the error to which given action to be set ActionId is the action that need to be set for ErrorId. Action can be SRST/POR/ERR OUT/INT ErrorHandler If INT is defined as response, handler should be defined. SubsystemId is the subsystem ID for the error node XST_SUCCESS on success and error code on failure
References XPlmi_ErrPrintToLog, XPlmi_GetErrorTable.
Referenced by XPlmi_EmSetAction, XPlmi_ReconfigErrActions.
int XPlmi_EmSetAction(u32 ErrorNodeId, u32 ErrorMasks, u8 ActionId, XPlmi_ErrorHandler_t ErrorHandler, const u32 SubsystemId)
This function sets the Action specified for a given Error Masks.
ErrorNodeId is the node ID for the error event ErrorMasks is the error masks to which specified action to be set ActionId is the action that need to be set for ErrorMasks. Action can be SRST/POR/ERR OUT/INT ErrorHandler If INT is defined as response, handler should be defined. SubsystemId is the subsystem ID for the error node XST_SUCCESS on success.XPLMI_INVALID_NODE_ID on invalid node ID.XPLMI_INVALID_ERROR_ID on invalid error ID.XPLMI_INVALID_ERROR_HANDLER on invalid error handler.
References XPlmi_EmClearError, XPlmi_EmConfig, XPlmi_EmDisable, XPlmi_GetErrorTable.
Referenced by XPlmi_EmInit, XPlmi_LpdSlcrEmInit, XPlmi_PsEmInit, XPlmi_RegisterTamperIntrHandler, XPlmi_Versal2Ve2VmSetAction.
int XPlmi_EmGetAction(u32 ErrorNodeId, u32 ErrorMasks, u8 *ActionIdPtr)
This function gets the Action for a given Error Node ID and Error Mask.
ErrorNodeId is the node ID for the error event ErrorMasks is the register mask of the error ActionIdPtr is the pointer to store the action ID XST_SUCCESS on success.XPLMI_INVALID_NODE_ID on invalid node ID.XPLMI_INVALID_ERROR_ID on invalid error ID.XST_INVALID_PARAM on invalid parameter.
References XPlmi_GetErrorId, XPlmi_GetErrorTable.
int XPlmi_EmInit(XPlmi_ShutdownHandler_t SystemShutdown)
This function initializes the error module.
Disables all the error actions and registers default action. SystemShutdown is the pointer to the PM system shutdown callback handler for action subtype system shutdown XST_SUCCESS on success and error code on failure
References GET_PMC_ERR_ACTION_OFFSET, GET_RTCFG_PMC_ERR_ADDR, XPlmi_ClearSsitErrors, XPlmi_EmDisablePmcErrors, XPlmi_EmSetAction, XPLMI_ERR_EMINIT_INVALID_PARAM, XPlmi_ErrorTaskHandler, XPlmi_GetErrorTable, XPlmi_GetTaskInstance, XPlmi_IsPlmUpdateDone, XPlmi_ReconfigErrActions, XPlmi_RegisterTamperIntrHandler, XPlmi_SysMonOTDetect, XPlmi_TaskCreate.
void XPlmi_SoftResetHandler(void)
This function sets clock source to IRO for ES1 silicon and resets the device.
References XPlmi_SysmonClkSetIro.
Referenced by XPlmi_HandleSwError.
void XPlmi_TriggerFwNcrError(void)
This function sets clock source to IRO for ES1 silicon and triggers FW NCR error.
References XPlmi_GetErrorTable, XPlmi_SysmonClkSetIro, XPlmi_UtilRMW.
Referenced by XPlmi_ErrMgr.
void XPlmi_SetEmSubsystemId(const u32 *Id)
This function sets EmSubsystemId.
Id pointer to set the EmSubsystemId
u32 XPlmi_GetEmSubsystemId(void)
This function returns EmSubsystemId.
EmSubsystemId
Referenced by XPlmi_Versal2Ve2VmSetAction.
u32 XPlmi_UpdateNumErrOutsCount(u8 UpdateType)
This function updates NumErrOuts and returns number of error outs count to the caller.
UpdateType is increment/decrement Number of ErrOuts count
References XPlmi_GetNumErrOuts.
Referenced by XPlmi_HandleSwError.
int XPlmi_CheckNpiErrors(void)
This function checks for NPI errors and logs them if present.
XST_SUCCESS if no errors detected.XST_FAILURE if NPI errors are detected.
int XPlmi_ClearNpiErrors(void)
This function clears NPI errors.
XST_SUCCESS on success and error code on failure
References XPLMI_ERR_NPI_LOCK, XPlmi_UtilRMW.