xplmi_ssit.c
static u32 XPlmi_SsitGetSlaveErrorMask(void)
This function checks which Slave SLR this code is running on and returns corresponding SSIT mask of PMC GLOBAL PMC_ERROR2_STATUS register.
return 0 if error occurred. Else return one of the ERR_MASK.
u8 XPlmi_GetSlrIndex(void)
This function is used to get the local SLR index.
Returns Local SLR index
u32 XPlmi_GetSlavesSlrMask(void)
This function is used to get the combined mask of all slave SLRs.
Returns combined mask of all slave SLRs
int XPlmi_SsitRegisterEvent(u32 EventIndex, XPlmi_EventHandler_t Handler, u8 EventOrigin)
This function is used to register any event between Master and Slave SLRs.
EventIndex is the Index of the event to be registered Handler is the handler to be executed when this Event occurs EventOrigin is the SLR origin which can trigger the event Returns XST_SUCCESS for non-SSIT designs
int XPlmi_SsitWriteEventBufferAndTriggerMsgEvent(u8 SlrIndex, u32 *ReqBuf, u32 ReqBufSize)
This function is used to write the event buffer data and trigger the Message Event.
SlrIndex is the index of the SLR to which the event buffer need to be written ReqBuf is the buffer from where the event buffer data to be written to Slave SLRs event buffer ReqBufSize is the size of the ReqBuf Returns XST_SUCCESS for non-SSIT designs
int XPlmi_SsitReadEventBuffer(u32 *ReqBuf, u32 ReqBufSize)
This function is used to read the event buffer of Master SLR in Slave SLRs where the message event is received.
ReqBuf is the buffer to which the event buffer data to be written ReqBufSize is the size of the ReqBuf Returns XST_SUCCESS for non-SSIT designs
int XPlmi_SsitTriggerEvent(u8 SlrIndex, u32 EventIndex)
This function is used to trigger the given event to the given SLR.
SlrIndex is the index of the SLR to which the event to be triggered EventIndex is the Index of the event to be triggered Returns XST_SUCCESS for non-SSIT designs
int XPlmi_SsitWaitForEvent(u8 SlrIndex, u32 EventIndex, u32 TimeOut)
This function is used to wait for the event to be acknowledged by the given SLR after triggering.
SlrIndex is the SLR index where the event is triggered EventIndex is the Index of the event triggered TimeOut is the timeout in us to wait for the acknowledgment Returns XST_SUCCESS for non-SSIT designs
int XPlmi_SsitReadResponse(u8 SlrIndex, u32 *RespBuf, u32 RespBufSize)
This function is used to read the response (if applicable) in Master SLR once the event is acknowledged by Slave SLR.
SlrIndex is the SLR index from the response need to be read RespBuf is the Response Buffer to where the response to be written RespBufSize is the size of the response buffer Returns XST_SUCCESS for non-SSIT designs
int XPlmi_SsitWriteResponseAndAckMsgEvent(u32 *RespBuf, u32 RespBufSize)
This function is used to write the response (if applicable) in Slave SLR once the event is handled and acknowledge the message event.
RespBuf is the Response Buffer data to be written RespBufSize is the size of the response buffer Returns XST_SUCCESS for non-SSIT designs
int XPlmi_SsitAcknowledgeEvent(u8 SlrIndex, u32 EventIndex)
This function is used to acknowledge the event after handling.
SlrIndex is index of the SLR for which the event was triggered EventIndex is the event to acknowledge Returns XST_SUCCESS for non-SSIT designs
u64 XPlmi_SsitGetSlrAddr(u32 Address, u8 SlrIndex)
This function is used to get the global SLR address for the given local address.
Address is the local address for which the global SLR address need to be calculated SlrIndex is the index of the SLR for which the address need to be calculated Returns 0x0 for non-SSIT designs
int XPlmi_SsitSendMsgEventAndGetResp(u8 SlrIndex, u32 *ReqBuf, u32 ReqBufSize, u32 *RespBuf, u32 RespBufSize, u32 WaitForEventCompletion)
This function sends a message event with given request buffer to a slave SLR, waits for event completion, reads the response from the slave SLR and returns it to the caller.
SlrIndex is the SLR index from which the response need to be read ReqBuf is the buffer to which the event buffer data to be written ReqBufSize is the size of the ReqBuf RespBuf is the Response Buffer to where the response to be written RespBufSize is the size of the response buffer WaitForEventCompletion is the maximum time to wait before the requested message event is handled by a slave SLR [in microseconds] Returns XST_SUCCESS for non-SSIT designs
Referenced by XPlmi_SendIpiCmdToSlaveSlr, XPlmi_SsitCfgSecComm.
int XPlmi_SsitSyncMaster(XPlmi_Cmd *Cmd)
This function provides SSIT Sync Master command execution.
Cmd is pointer to the command structure Returns the Status of SSIT Sync Master command
References XPLMI_SSIT_SYNC_MASTER_CMD_ID, XPlmi_UtilRMW.
int XPlmi_SsitSyncSlaves(XPlmi_Cmd *Cmd)
This function provides SSIT Sync Slaves command execution.
Command payload parameters are * Slaves Mask * Timeout Cmd is pointer to the command structure Returns the Status of SSIT Sync Slaves commandXPLMI_ERR_SSIT_SLAVE_SYNC if master timedout on slave sync.
References XPLMI_ERR_SSIT_SLAVE_SYNC, XPlmi_SetPlmLiveStatus, XPLMI_SSIT_SYNC_SLAVES_CMD_ID.
int XPlmi_SsitWaitSlaves(XPlmi_Cmd *Cmd)
This function provides SSIT Wait Slaves command execution.
Command payload parameters are * Slaves Mask * Timeout Cmd is pointer to the command structure Returns the Status of SSIT Wait Slaves commandXPLMI_ERR_SSIT_SLAVE_SYNC if master timedout on slave sync.
References XPLMI_ERR_SSIT_SLAVE_SYNC, XPlmi_SetPlmLiveStatus, XPLMI_SSIT_WAIT_SLAVES_CMD_ID.
int XPlmi_SendIpiCmdToSlaveSlr(u32 *Payload, u32 *RespBuf)
This function handles invalid commands.
Payload holds the inputs of the slaves RespBuf Stores the response of the slaves XST_SUCCESS on success.XPLMI_ERR_CMD_APIID on unregistered command ID.XPLMI_SSIT_INTR_NOT_ENABLED if interrupts are not enabled.
References XPLMI_ERR_CMD_APIID, XPLMI_SLR_INDEX_SHIFT, XPLMI_SSIT_INTR_NOT_ENABLED, XPLMI_SSIT_MONOLITIC, XPlmi_SsitSendMsgEventAndGetResp.
void XPlmi_NotifySldSlaveSlrs(void)
This function notifies other SLRs about Secure Lockdown or tamper condition in SSIT devices.
References XPLMI_SSIT_MASTER_SLR, XPLMI_SSIT_MONOLITIC.
Referenced by XPlmi_TriggerTamperResponse.
void XPlmi_InterSlrSldHandshake(void)
This function performs handshake between SLRs on SSIT ERR lines.
This has to be done on SSIT devices before doing secure lockdown
References XPLMI_SSIT_MASTER_SLR, XPLMI_SSIT_MONOLITIC, XPlmi_UtilPoll, XPlmi_UtilPollForMask, XPlmi_UtilPollNs.
int XPlmi_SsitCfgSecComm(XPlmi_Cmd *Cmd)
This function provides SSIT config secure communication command execution.
Command payload parameters are * SLR number, base address of buffer which consists of IV1,IV2,Key in master * IV1(128-bit), IV2(128-bit) and Key(256-bit) in slave Cmd is pointer to the command structure XST_SUCCESS If command is successfulXST_FAILURE If there is failure
References XPLMI_ERR_INVALID_ADDR_RANGE, XPLMI_EVENT_NOT_SUPPORTED_FROM_SLR, XPLMI_INVALID_SLR_TYPE, XPLMI_KEY_SIZE_BYTES, XPLMI_SSIT_MASTER_SLR, XPLMI_SSIT_MONOLITIC, XPlmi_SsitSendMsgEventAndGetResp, XPLMI_VERIFY_ADDR_RANGE.
int XPlmi_GetSsitSecCommStatus(XPlmi_Cmd *Cmd)
This function gives SSIT secure communication status Command payload parameters are.
* SLR index for which secure communication status is requested Cmd is pointer to the command structure Returns the Status of get secure communication status command
References XPLMI_EVENT_NOT_SUPPORTED_FROM_SLR, XPLMI_INVALID_SLR_TYPE, XPLMI_SSIT_MASTER_SLR, XPLMI_SSIT_MONOLITIC.