xplmi_err_psm.c
static void XPlmi_HandlePsmError(u32 ErrorNodeId, u32 RegMask)
This function handles the PSM error routed to PLM.
ErrorNodeId is the node ID for the error event RegMask is the register mask of the error received None
void XPlmi_ErrPSMIntrHandler(u32 ErrorNodeId, u32 RegMask)
This function is the interrupt handler for PSM Errors.
ErrorNodeId is the node ID for the error event RegMask is the register mask of the error received None
References XPlmi_GetErrorTable.
Referenced by XPlmi_ErrorTaskHandler.
int XPlmi_EmDisablePsmErrors(u32 RegOffset, u32 RegMask)
This function disables the PSM error actions for the given mask.
RegOffset is the offset for the PSM ERR1 errors RegMask is the register mask of the error to be disabled XST_SUCCESS on success.XPLMI_ERROR_ACTION_NOT_DISABLED if error action is not disabled.
References EmDisableErrAction.
Referenced by XPlmi_EmDisable, XPlmi_PsEmInit.
int XPlmi_PsEmInit(void)
This function initializes the PSM error actions.
Disables all the PSM error actions and registers default action. XST_SUCCESS always.
References XPlmi_EmDisablePsmErrors, XPlmi_EmSetAction, XPlmi_GetErrorTable.
Referenced by XPlmi_LpdInit.
void XPlmi_SaveLpdEAMInfo(void)
Saves the PSM (Platform System Management) error status info for the LPD (Low Power Domain), reads the error status registers from the PSM, and stores error status values into the RTCFG memory.
This function is platform-specific.
References GET_RTCFG_PSM_ERR_ADDR, XPLMI_LPD_DOMAIN_INIT_MASK, XPlmi_UtilRMW.