xplmi_util.c
void XPlmi_UtilRMW(u32 RegAddr, u32 Mask, u32 Value)
This function will Read, Modify and Write to a register.
RegAddr is the address of the register Mask denotes the bits to be modified Value is the value to be written to the register
Referenced by XPlmi_ClearNpiErrors, XPlmi_DisableCFrameIso, XPlmi_ErrMgr, XPlmi_ListMaskWrite, XPlmi_LogPlmErr, XPlmi_LpdInit, XPlmi_PORHandler, XPlmi_SaveLpdEAMInfo, XPlmi_SchedulerHandler, XPlmi_SetDDRMCMainRegSts, XPlmi_SsitSyncMaster, XPlmi_SysmonClkSetIro, XPlmi_TriggerFwNcrError, XPlmi_UpdateCryptoStatus, XPlmi_UpdateKatStatus.
int XPlmi_UtilPoll(u32 RegAddr, u32 Mask, u32 ExpectedValue, u32 TimeOutInUs, void(*ClearHandler)(void))
This function polls a register till the masked bits are set to expected value or till timeout occurs.
RegAddr is the address of the register Mask denotes the bits to be modified ExpectedValue is the value for which the register is polled TimeOutInUs is the max time in microseconds for which the register would be polled for the expected value ClearHandler is the handler to clear the latched values if required before reading them XST_SUCCESS on success and error code on failure
References XPlmi_SetPlmLiveStatus.
Referenced by XPlmi_GenericMaskPoll, XPlmi_InterSlrSldHandshake.
int XPlmi_UtilPoll64(u64 RegAddr, u32 Mask, u32 ExpectedValue, u32 TimeOutInUs)
This function polls a 64 bit address till the masked bits are set to expected value or till timeout occurs.
RegAddr 64 bit address Mask is the bit field to be polled ExpectedValue is value to be polled TimeOutInUs is delay time in micro sec XST_SUCCESS on success and error code on failure
References XPlmi_SetPlmLiveStatus.
Referenced by XPlmi_GenericMaskPoll.
int XPlmi_UtilPollForMask(u32 RegAddr, u32 Mask, u32 TimeOutInUs)
This function polls a 64 bit register till the masked bits are set to expected value or till timeout occurs.
RegAddr is the register address Mask is the bit field to be updated TimeOutInUs is delay time in micro sec XST_SUCCESS on success and error code on failure
References XPlmi_SetPlmLiveStatus.
Referenced by XPlmi_InterSlrSldHandshake.
int XPlmi_UtilPollForMask64(u32 HighAddr, u32 LowAddr, u32 Mask, u32 TimeOutInUs)
This function polls a 64 bit register till the masked bits are set to expected value or till timeout occurs.
HighAddr is higher 32-bits of 64-bit address LowAddr is lower 32-bits of 64-bit address Mask is the bit field to be updated TimeOutInUs is delay time in micro sec XST_SUCCESS on success and error code on failure
References XPlmi_SetPlmLiveStatus.
void XPlmi_UtilWrite64(u32 HighAddr, u32 LowAddr, u32 Value)
This function writes to a 64 bit address.
HighAddr is higher 32-bits of 64-bit address LowAddr is lower 32-bits of 64-bit address Value is value to be updated
void XPlmi_PrintArray(u16 DebugType, const u64 BufAddr, u32 Len, const char *Str)
This function is used to print the entire array in bytes as specified by the debug type.
DebugType printing of the array will happen as defined by the debug type BufAddr pointer to the buffer to be printed Len length of the bytes to be printed Str pointer to the data that is printed along the data
References XPLMI_WORD_LEN.
int XPlmi_UtilPollNs(u32 RegAddr, u32 Mask, u32 ExpectedValue, u64 TimeOutInNs, void(*ClearHandler)(void))
This function polls a register till the masked bits are set to expected value or till timeout occurs.
The timeout is specified in nanoseconds. Also provides a clearhandler to clear the latched values before reading them. RegAddr is the address of the register Mask denotes the bits to be modified ExpectedValue is the value for which the register is polled TimeOutInNs is the max time in nanoseconds for which the register would be polled for the expected value ClearHandler is the handler to clear the latched values if required before reading them XST_SUCCESS on success and XST_FAILURE on failure
References XPlmi_GetPmcIroFreq, XPlmi_GetTimerValue.
Referenced by XPlmi_InterSlrSldHandshake.
void XPlmi_StoreMultiboot(void)
This is a placeholder function used in case the feature is disabled.
void XPlmi_RestoreMultiboot(void)
This is a placeholder function used in case the feature is disabled.
void XPlmi_ClearMultiboot(void)
This is a placeholder function used in case the feature is disabled.