xplmi_tamper.h
XPLMI_TRIGGER_TAMPER_TASK
Trigger tamper as a Task.
Referenced by XPlmi_TriggerTamperResponse.
XPLMI_TRIGGER_TAMPER_IMMEDIATE
Trigger tamper immediately.
XPLMI_SLD_NOT_TRIGGERED
Secure lockdown not triggered.
Referenced by XPlmi_TriggerTamperResponse.
XPLMI_SLD_TRIGGERED
Secure lockdown triggered.
Referenced by XPlmi_TriggerTamperResponse.
XPLMI_SLD_IN_PROGRESS
Secure lockdown is in progress.
Referenced by XPlmi_ProcessCdo.
XPLMI_HALT_BOOT_SLD_TEMPORAL_CHECK
Updates the return value of the called function into Status and StatusTmp variables for redundancy.
when called function returns a failure it triggers secure lockdown if haltboot efuses are programmed. MajorError contains the major error code Status is the variable which holds the return value of function executed StatusTmp is the variable which holds the value stored in Status function is the function to be executed Other params are arguments to the called function None
XPLMI_HALT_BOOT_SLD_TEMPORAL_CHECK_FOR_INPRGRESS_STS
int XPlmi_RegisterTamperIntrHandler(void)
This function registers the handler for tamper interrupt.
XST_SUCCESS - On successXPLMI_INVALID_ERROR_ID - On invalid IDXPLMI_INVALID_ERROR_HANDLER - On Null handler
References XPlmi_GetTaskInstance, XPlmi_TaskCreate, XPLM_ERR_TASK_CREATE, XPlmi_EmSetAction.
Referenced by XPlmi_EmInit.
void XPlmi_TriggerTamperResponse(u32 Response, u32 Flag)
This functions Triggers Tamper Response processing immediately or as a task.
Response is the Tamper Response that has to occur Flag denotes whether processing has to occur immediately or as a task. The possible values are: XPLMI_TRIGGER_TAMPER_TASK, XPLMI_TRIGGER_TAMPER_IMMEDIATE.
References XPlmi_SldState, XPLMI_SLD_NOT_TRIGGERED, XPLMI_SLD_TRIGGERED, XPlmi_NotifySldSlaveSlrs, XPLMI_TRIGGER_TAMPER_TASK, XPlmi_TaskTriggerNow.
Referenced by XPlmi_TriggerSLDOnHaltBoot.
void XPlmi_TriggerSLDOnHaltBoot(u32 Flag)
This function triggers secure lockdown if haltboot efuses are programmed.
Flag denotes whether processing has to occur immediately or as a task. The possible values are: XPLMI_TRIGGER_TAMPER_TASK, XPLMI_TRIGGER_TAMPER_IMMEDIATE.
References XPlmi_TriggerTamperResponse.
u32 XPlmi_SldState(void)
This function returns Secure Lockdown State.
Secure Lockdown State
Referenced by XPlmi_ProcessCdo, XPlmi_TriggerTamperResponse.