xplmi_tamper.c
u32 SldState
SldState variable maintains the current secure lockdown state.
u32 TamperResponse
TamperResponse variable stores the tamper response configuration.
XPlmi_TaskNode* TamperTask
TamperTask is the task node pointer for tamper response processing.
static void XPlmi_PmcApbErrorHandler(const u32 ErrorNodeId, const u32 ErrorMask)
This is the handler for tamper interrupt.
ErrorNodeId - Node Identifier ErrorMask - Mask Identifier
static int XPlmi_ProcessTamperResponse(void *Data)
This function processes the tamper response.
Data is unused No status return, waits forever for ROM to complete secure lockdown.
u32 XPlmi_SldState(void)
This function returns Secure Lockdown State.
Secure Lockdown State
Referenced by XPlmi_ProcessCdo, XPlmi_TriggerTamperResponse.
void XPlmi_TriggerTamperResponse(u32 Response, u32 Flag)
This functions Triggers Tamper Response processing immediately or as a task.
Response is the Tamper Response that has to occur Flag denotes whether processing has to occur immediately or as a task. The possible values are: XPLMI_TRIGGER_TAMPER_TASK, XPLMI_TRIGGER_TAMPER_IMMEDIATE.
References XPlmi_NotifySldSlaveSlrs, XPLMI_SLD_NOT_TRIGGERED, XPLMI_SLD_TRIGGERED, XPlmi_SldState, XPlmi_TaskTriggerNow, XPLMI_TRIGGER_TAMPER_TASK.
Referenced by XPlmi_TriggerSLDOnHaltBoot.
int XPlmi_RegisterTamperIntrHandler(void)
This function registers the handler for tamper interrupt.
XST_SUCCESS - On successXPLMI_INVALID_ERROR_ID - On invalid IDXPLMI_INVALID_ERROR_HANDLER - On Null handler
References XPLM_ERR_TASK_CREATE, XPlmi_EmSetAction, XPlmi_GetTaskInstance, XPlmi_TaskCreate.
Referenced by XPlmi_EmInit.
void XPlmi_TriggerSLDOnHaltBoot(u32 Flag)
This function triggers secure lockdown if haltboot efuses are programmed.
Flag denotes whether processing has to occur immediately or as a task. The possible values are: XPLMI_TRIGGER_TAMPER_TASK, XPLMI_TRIGGER_TAMPER_IMMEDIATE.
References XPlmi_TriggerTamperResponse.