xilflash_cfi.c
int XFlashCFI_ReadCommon(XFlash *InstancePtr, u8 BusWidth)
Retrieves the standard CFI data from the part(s), interpret the data, and update the provided geometry and properties structures.
Extended CFI data is part specific and ignored here. This data must be read by the specific flash device family library. InstancePtr is the pointer to the XFlash instance. BusWidth is the total width of the flash memory, in bytes. XST_SUCCESS if successful.XFLASH_CFI_QUERY_ERROR if an error occurred interpreting the data.XFLASH_PART_NOT_SUPPORTED if invalid Layout parameter. None.
References XFL_CFI_ADVANCE_PTR16, XFL_CFI_ADVANCE_PTR8, XFL_CFI_POSITION_PTR, XFL_LAYOUT_NUM_PARTS_MASK, XFlashCFI_Read16, XFlashCFI_Read8.
Referenced by XFlash_Initialize.
int XFlashCFI_Read8(u8 *Ptr, u8 Interleave, u8 Mode)
Reads 8-bits of data from the CFI data location into a local variable.
Ptr is the pointer to read. Can be a pointer to any type. Interleave is the byte interleaving (based on part layout). Mode is the mode of operation (based on part layout). The byte at Ptr adjusted for the interleave factor.
Referenced by XFlashCFI_ReadCommon.
int XFlashCFI_Read16(u8 *Ptr, u8 Interleave, u8 Mode)
Reads 16-bits of data from the CFI data location into a local variable.
Ptr is the pointer to read. Can be a pointer to any type. Interleave is the byte interleaving (based on part layout). Mode is the mode of operation (based on part layout). The 16-bit value at Ptr adjusted for the interleave factor.
Referenced by XFlashCFI_ReadCommon.