xilflash_cfi.h
XFL_LAYOUT_NUM_PARTS_MASK
LAYOUT constants are used to parse the XFL_LAYOUT_X* constants.
Referenced by XFlashCFI_ReadCommon.
XFL_LAYOUT_PART_MODE_MASK
XFL_LAYOUT_PART_WIDTH_MASK
XFL_LAYOUT_CFI_INTERL_MASK
XFL_LAYOUT_NUM_PARTS_1
XFL_LAYOUT_NUM_PARTS_2
XFL_LAYOUT_NUM_PARTS_4
XFL_LAYOUT_PART_MODE_8
XFL_LAYOUT_PART_MODE_16
XFL_LAYOUT_PART_WIDTH_8
XFL_LAYOUT_PART_WIDTH_16
XFL_LAYOUT_CFI_INTERL_1
XFL_LAYOUT_CFI_INTERL_2
XFL_LAYOUT_CFI_INTERL_4
XFL_LAYOUT_CFI_INTERL_8
XFLASH_CFI_H
< prevent circular inclusions
by using protection macros
XFL_CFI_POSITION_PTR
Moves the CFI data pointer to a physical address that corresponds to a specific CFI byte offset.
Ptr is the pointer to modify. Can be of any type. BaseAddr is the base address of flash part. Interleave is the byte interleaving (based on part layout). ByteAddr is the byte offset within CFI data to read. The Ptr argument is set to point at the CFI byte specified by the ByteAddr parameter.
Referenced by XFlashCFI_ReadCommon.
XFL_CFI_ADVANCE_PTR8
Advances the CFI pointer to the next byte.
Ptr is the pointer to advance. Can be a pointer to any type. Interleave is the byte interleaving (based on part layout). Adjusted Ptr.
Referenced by XFlashCFI_ReadCommon.
XFL_CFI_ADVANCE_PTR16
Advances the CFI pointer to the next 16-bit quantity.
Ptr is the pointer to advance. Can be a pointer to any type. Interleave is the byte interleaving (based on part layout). Adjusted Ptr.
Referenced by XFlashCFI_ReadCommon.
int XFlashCFI_ReadCommon(XFlash *InstancePtr, u8 BusWidth)
Retrieves the standard CFI data from the part(s), interpret the data, and update the provided geometry and properties structures.
Extended CFI data is part specific and ignored here. This data must be read by the specific flash device family library. InstancePtr is the pointer to the XFlash instance. BusWidth is the total width of the flash memory, in bytes. XST_SUCCESS if successful.XFLASH_CFI_QUERY_ERROR if an error occurred interpreting the data.XFLASH_PART_NOT_SUPPORTED if invalid Layout parameter. None.
References XFL_CFI_ADVANCE_PTR16, XFL_CFI_ADVANCE_PTR8, XFL_CFI_POSITION_PTR, XFL_LAYOUT_NUM_PARTS_MASK, XFlashCFI_Read16, XFlashCFI_Read8.
Referenced by XFlash_Initialize.
int XFlashCFI_Read8(u8 *Ptr, u8 Interleave, u8 Mode)
Reads 8-bits of data from the CFI data location into a local variable.
Ptr is the pointer to read. Can be a pointer to any type. Interleave is the byte interleaving (based on part layout). Mode is the mode of operation (based on part layout). The byte at Ptr adjusted for the interleave factor.
Referenced by XFlashCFI_ReadCommon.
int XFlashCFI_Read16(u8 *Ptr, u8 Interleave, u8 Mode)
Reads 16-bits of data from the CFI data location into a local variable.
Ptr is the pointer to read. Can be a pointer to any type. Interleave is the byte interleaving (based on part layout). Mode is the mode of operation (based on part layout). The 16-bit value at Ptr adjusted for the interleave factor.
Referenced by XFlashCFI_ReadCommon.