xhdmi_intr.c
XHDMI_MAX_NUM_INTR_INPUTS
XHDMI_MAX_NUM_INTR_QUEUE
ANSI_COLOR_RED
ANSI_COLOR_YELLOW
ANSI_COLOR_RESET
XIntc Intc
XHdmi_Interrupt_VectorTableEntry XHdmi_HandlerTable[XPAR_INTC_MAX_NUM_INTR_INPUTS][XPAR_INTC_MAX_NUM_INTR_INPUTS]
void* CallBackRefFlagVector[XHDMI_MAX_NUM_INTR_QUEUE][XHDMI_MAX_NUM_INTR_QUEUE]
u8 CallBackRefFlagHead
u8 CallBackRefFlagTail
u8 CallBackRefFlagCount
void XHdmi_InterruptInitialize(void)
Initialize the HDMI ExDes interrupt queue variables.
None. None. None.
u32 XHdmi_InterruptConnect(void *Intc, u8 Id, XInterruptHandler Handler, void *CallBackRef)
Makes the connection between the Id of the interrupt source and the associated handler that is to run when the interrupt is recognized.
It registers the CallBack reference and handler in the local interrupt handler table based in the DevID or interrupt bit position. Intc is a pointer to the INT controlerr instance to be worked on. Id contains the ID of the interrupt source and should be in the range of 0 to MAX_NUM_INTR_INPUTS - 1 with 0 being the highest priority interrupt. Handler to the handler for that interrupt. CallBackRef is the callback reference, usually the instance pointer of the connecting driver. - XST_SUCCESS if the handler was connected correctly. WARNING: The handler provided as an argument will overwrite any handler that was previously connected.
References XHdmi_InterruptHandler.
void XHdmi_InterruptHandler(void *CallBackRef)
This function is the interrupt handler for the HDMI ExDes.
It will will register the CallBackRef in the tail of the interrupt queue and will disable the interrupt position to prevent interrupt storm. CallBackRef is the callback reference register in the interrupt controller. None. None.
References XHdmi_InterruptDevIdLookUp.
Referenced by XHdmi_InterruptConnect.
void XHdmi_InterruptService(void)
This function services the queued interrupts for the HDMI ExDes in the normal program flow (outside ISR).
It will invoke the appropriate callback for the corresponding interrupt and will re-enable the interrupt bit in the INT controller after servicing. None. None. None.
References XHdmi_InterruptDevIdLookUp.
u32 XHdmi_InterruptDevIdLookUp(void *CallBackRef)
This function will look for the interrupt device ID based on the Callback reference registered to it.
CallBackRef is a pointer to the XHdmi_HandlerTable instance. Interrupt Device ID None.
Referenced by XHdmi_InterruptHandler, XHdmi_InterruptService.