xv_hdmitxss1.h
XV_HdmiTxSs1_LogEvent
Log event none.
XV_HdmiTxSs1_HpdToleranceType
system should tolerate leading edge variations in the HPD signal
XV_HdmiTxSs1_HdcpProtocol
No content protection.
XV_HdmiTxSs1_HandlerType
Handler for connect event.
HDMITXSS1_H
< prevent circular inclusions by using protection macros
XV_HDMITXSS1_LOG_ENABLE
XV_HDMITXSS1_DDC_EDID_LENGTH
ANSI_COLOR_RED
ANSI_COLOR_YELLOW
ANSI_COLOR_RESET
typedef void(* XV_HdmiTxSs1_Callback)(void *CallbackRef))(void *CallbackRef)
Callback type for interrupt.
CallbackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. None. None.
typedef u64(* XV_HdmiTxSs1_LogCallback)(void *CallbackRef))(void *CallbackRef)
Callback type for interrupt.
CallbackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. u8 value. None.
XV_HdmiTxSs1_Config* XV_HdmiTxSs1_LookupConfig(UINTPTR BaseAddress)
This function looks for the device configuration based on the unique device ID.
The table XV_HdmiTxSs1_ConfigTable[] contains the configuration information for each instance of the device in the system. DeviceId is the unique device ID of the device being looked up A pointer to the configuration table entry corresponding to the given device ID, or NULL if no match is found
u32 XV_HdmiTxSs1_GetDrvIndex(UINTPTR BaseAddress)
This function returns the Index number of config table using BaseAddress.
A pointer to the instance structure Base address of the instance Index number of the config table
void XV_HdmiTxSS1_SetHdmiTmdsMode(XV_HdmiTxSs1 *InstancePtr)
This function sets the core into HDMI mode.
InstancePtr is a pointer to the HDMI TX Subsystem
References XV_HdmiTxSs1::HdmiTx1Ptr.
Referenced by XV_HdmiTxSs1_SubcoreInitHdmiTx1.
void XV_HdmiTxSS1_SetDviMode(XV_HdmiTxSs1 *InstancePtr)
This function sets the core into DVI mode.
InstancePtr is a pointer to the HDMI TX Subsystem
References XV_HdmiTxSs1::HdmiTx1Ptr.
void XV_HdmiTxSS1_HdmiTx1IntrHandler(XV_HdmiTxSs1 *InstancePtr)
This function calls the interrupt handler for HDMI TX.
InstancePtr is a pointer to the HDMI TX Subsystem
References XV_HdmiTxSs1::HdmiTx1Ptr.
int XV_HdmiTxSs1_CfgInitialize(XV_HdmiTxSs1 *InstancePtr, XV_HdmiTxSs1_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the video subsystem and included sub-cores.
This function must be called prior to using the subsystem. Initialization includes setting up the instance data for top level as well as all included sub-core therein, and ensuring the hardware is in a known stable state. InstancePtr is a pointer to the Subsystem instance to be worked on. CfgPtr points to the configuration structure associated with the subsystem instance. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if initialization is successful else XST_FAILURE
References XV_HdmiTxSs1::AppMajVer, XV_HdmiTxSs1::AppMinVer, XV_HdmiTxSs1::AudioInfoframe, XV_HdmiTxSs1::AVIInfoframe, XV_HdmiTxSs1_Config::AxiLiteClkFreq, XV_HdmiTxSs1_Config::BaseAddress, XV_HdmiTxSs1::Config, XV_HdmiTxSs1::DrmInfoframe, XV_HdmiTxSs1::EnableHDCPLogging, XV_HdmiTxSs1::EnableHDMILogging, XV_HdmiTxSs1::HdcpProtocol, XV_HdmiTxSs1::HdmiTx1Ptr, XV_HdmiTxSs1::IsReady, XV_HdmiTxSs1::VSIF, XV_HdmiTxSs1::VtcPtr, XV_HDMITXSS1_HDCP_BOTH, XV_HDMITXSS1_HDCP_NONE, XV_HdmiTxSs1_Reset, XV_HdmiTxSs1_SubcoreInitHdmiTx1, XV_HdmiTxSs1_SubcoreInitVtc.
void XV_HdmiTxSS1_SetAppVersion(XV_HdmiTxSs1 *InstancePtr, u8 maj, u8 min)
This function will set the major and minor application version in TXSs struct.
InstancePtr is a pointer to the XV_HdmiTxSs1 core instance. maj is the major version of the application. min is the minor version of the application. void. None.
References XV_HdmiTxSs1::AppMajVer, XV_HdmiTxSs1::AppMinVer.
void XV_HdmiTxSs1_Start(XV_HdmiTxSs1 *InstancePtr)
This function starts the HDMI TX subsystem including all sub-cores that are included in the processing pipeline for a given use-case.
Video pipe is started from back to front InstancePtr is a pointer to the Subsystem instance to be worked on. None Cores are started only if the corresponding start flag in the scratch pad memory is set. This allows to selectively start only those cores included in the processing chain
References XV_HdmiTxSs1::HdmiTx1Ptr, XV_HDMITXSS1_LOG_EVT_START, XV_HdmiTxSs1_LogWrite.
Referenced by main.
void XV_HdmiTxSs1_Stop(XV_HdmiTxSs1 *InstancePtr)
This function stops the HDMI TX subsystem including all sub-cores Stop the video pipe starting from front to back.
InstancePtr is a pointer to the Subsystem instance to be worked on. None
References XV_HdmiTxSs1::HdmiTx1Ptr, XV_HdmiTxSs1::VtcPtr, XV_HDMITXSS1_LOG_EVT_STOP, XV_HdmiTxSs1_LogWrite.
void XV_HdmiTxSs1_Reset(XV_HdmiTxSs1 *InstancePtr)
This function resets the video subsystem sub-cores.
There are 2 reset networks within the subsystem For cores that are on AXIS interfaceFor cores that are on AXI-MM interface InstancePtr is a pointer to the Subsystem instance to be worked on. None
References XV_HDMITXSS1_LOG_EVT_RESET, XV_HdmiTxSs1_LogWrite, XV_HdmiTxSs1_SYSRST, XV_HdmiTxSs1_TXCore_LRST, XV_HdmiTxSs1_TXCore_VRST, XV_HdmiTxSs1_VRST.
Referenced by XV_HdmiTxSs1_CfgInitialize.
void XV_HdmiTxSs1_TXCore_VRST(XV_HdmiTxSs1 *InstancePtr, u8 Reset)
This function asserts or releases the Internal Video reset of the HDMI subcore within the subsystem.
InstancePtr is a pointer to the Subsystem instance to be worked on. Reset specifies whether to assert (TRUE) or release (FALSE) the reset. None
References XV_HdmiTxSs1::HdmiTx1Ptr.
Referenced by XV_HdmiTxSs1_RefClockChangeInit, XV_HdmiTxSs1_Reset.
void XV_HdmiTxSs1_TXCore_LRST(XV_HdmiTxSs1 *InstancePtr, u8 Reset)
This function asserts or releases the Internal Link reset of the HDMI subcore within the subsystem.
InstancePtr is a pointer to the Subsystem instance to be worked on. Reset specifies whether to assert (TRUE) or release (FALSE) the reset. None
References XV_HdmiTxSs1::HdmiTx1Ptr.
Referenced by XV_HdmiTxSs1_RefClockChangeInit, XV_HdmiTxSs1_Reset.
void XV_HdmiTxSs1_VRST(XV_HdmiTxSs1 *InstancePtr, u8 Reset)
This function asserts or releases the video reset of other blocks within the subsystem.
InstancePtr is a pointer to the Subsystem instance to be worked on. Reset specifies whether to assert (TRUE) or release (FALSE) the reset. None
References XV_HdmiTxSs1::HdmiTx1Ptr.
Referenced by XV_HdmiTxSs1_RefClockChangeInit, XV_HdmiTxSs1_Reset.
void XV_HdmiTxSs1_SYSRST(XV_HdmiTxSs1 *InstancePtr, u8 Reset)
This function asserts or releases the system reset of other blocks within the subsystem.
InstancePtr is a pointer to the Subsystem instance to be worked on. Reset specifies whether to assert (TRUE) or release (FALSE) the reset. None
References XV_HdmiTxSs1::HdmiTx1Ptr.
Referenced by XV_HdmiTxSs1_RefClockChangeInit, XV_HdmiTxSs1_Reset.
void XV_HdmiTxSs1_SetGcpAvmuteBit(XV_HdmiTxSs1 *InstancePtr)
This function sets the HDMI TX AUX GCP register AVMUTE bit.
InstancePtr is a pointer to the Subsystem instance to be worked on. None
References XV_HdmiTxSs1::HdmiTx1Ptr.
void XV_HdmiTxSs1_ClearGcpAvmuteBit(XV_HdmiTxSs1 *InstancePtr)
This function clears the HDMI TX AUX GCP register AVMUTE bit.
InstancePtr is a pointer to the Subsystem instance to be worked on. None
References XV_HdmiTxSs1::HdmiTx1Ptr.
void XV_HdmiTxSs1_SetGcpClearAvmuteBit(XV_HdmiTxSs1 *InstancePtr)
This function sets the HDMI TX AUX GCP register CLEAR_AVMUTE bit.
InstancePtr is a pointer to the Subsystem instance to be worked on. None
References XV_HdmiTxSs1::HdmiTx1Ptr.
void XV_HdmiTxSs1_ClearGcpClearAvmuteBit(XV_HdmiTxSs1 *InstancePtr)
This function clears the HDMI TX AUX GCP register CLEAR_AVMUTE bit.
InstancePtr is a pointer to the Subsystem instance to be worked on. None
References XV_HdmiTxSs1::HdmiTx1Ptr.
int XV_HdmiTxSs1_SetCallback(XV_HdmiTxSs1 *InstancePtr, XV_HdmiTxSs1_HandlerType HandlerType, void *CallbackFuncPtr, void *CallbackRef)
This function installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function Type ----------------------- --------------------------------------------- (XV_HDMITXSS1_HANDLER_CONNECT) HpdCallback (XV_HDMITXSS1_HANDLER_VS) VsCallback (XV_HDMITXSS1_HANDLER_STREAM_DOWN) StreamDownCallback (XV_HDMITXSS1_HANDLER_STREAM_UP) StreamUpCallback (XV_HDMITXSS1_HANDLER_BRDGOVERFLOW) BrdgOverflowCallback (XV_HDMITXSS1_HANDLER_BRDGUNDERFLOW) BrdgUnderflowCallback (XV_HDMITXSS1_HANDLER_HDCP_AUTHENTICATED) (XV_HDMITXSS1_HANDLER_HDCP_DOWNSTREAM_TOPOLOGY_AVAILABLE) (XV_HDMITXSS1_HANDLER_HDCP_UNAUTHENTICATED) InstancePtr is a pointer to the HDMI TX Subsystem instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XV_HdmiTxSs1::BrdgLockedCallback, XV_HdmiTxSs1::BrdgLockedRef, XV_HdmiTxSs1::BrdgOverflowCallback, XV_HdmiTxSs1::BrdgOverflowRef, XV_HdmiTxSs1::BrdgUnderflowCallback, XV_HdmiTxSs1::BrdgUnderflowRef, XV_HdmiTxSs1::BrdgUnlockedCallback, XV_HdmiTxSs1::BrdgUnlockedRef, XV_HdmiTxSs1::ConnectCallback, XV_HdmiTxSs1::ConnectRef, XV_HdmiTxSs1::DscDecodeFailCallback, XV_HdmiTxSs1::DscDecodeFailRef, XV_HdmiTxSs1::DynHdrMtwCallback, XV_HdmiTxSs1::DynHdrMtwRef, XV_HdmiTxSs1::StreamDownCallback, XV_HdmiTxSs1::StreamDownRef, XV_HdmiTxSs1::StreamUpCallback, XV_HdmiTxSs1::StreamUpRef, XV_HdmiTxSs1::TmdsConfigCallback, XV_HdmiTxSs1::TmdsConfigRef, XV_HdmiTxSs1::ToggleCallback, XV_HdmiTxSs1::ToggleRef, XV_HdmiTxSs1::VsCallback, XV_HdmiTxSs1::VsRef, XV_HDMITXSS1_HANDLER_BRDGLOCK, XV_HDMITXSS1_HANDLER_BRDGOVERFLOW, XV_HDMITXSS1_HANDLER_BRDGUNDERFLOW, XV_HDMITXSS1_HANDLER_BRDGUNLOCK, XV_HDMITXSS1_HANDLER_CONNECT, XV_HDMITXSS1_HANDLER_DSCDECODE_FAIL, XV_HDMITXSS1_HANDLER_DYNHDR_MWT, XV_HDMITXSS1_HANDLER_FRL_CONFIG, XV_HDMITXSS1_HANDLER_FRL_FFE, XV_HDMITXSS1_HANDLER_FRL_START, XV_HDMITXSS1_HANDLER_FRL_STOP, XV_HDMITXSS1_HANDLER_HDCP_AUTHENTICATED, XV_HDMITXSS1_HANDLER_HDCP_DOWNSTREAM_TOPOLOGY_AVAILABLE, XV_HDMITXSS1_HANDLER_HDCP_UNAUTHENTICATED, XV_HDMITXSS1_HANDLER_STREAM_DOWN, XV_HDMITXSS1_HANDLER_STREAM_UP, XV_HDMITXSS1_HANDLER_TMDS_CONFIG, XV_HDMITXSS1_HANDLER_TOGGLE, XV_HDMITXSS1_HANDLER_VS.
Referenced by main.
int XV_HdmiTxSs1_SetLogCallback(XV_HdmiTxSs1 *InstancePtr, u64 *CallbackFunc, void *CallbackRef)
This function installs an asynchronous callback function for the LogWrite API:
InstancePtr is a pointer to the HDMI TX Subsystem instance. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when callback function is not installed successfully.
References XV_HdmiTxSs1::LogWriteCallback, XV_HdmiTxSs1::LogWriteRef.
int XV_HdmiTxSs1_SendCvtemAuxPackets(XV_HdmiTxSs1 *InstancePtr, XHdmiC_Aux *DscAuxFifo)
This function is used to Send CVTEM Packet.
InstancePtr is a pointer to the HDMI TX Subsystem instance. DscAuxFifo is a pointer to the HDMI Aux fifo XST_SUCCESS on successful update of header and data. XST_FAILURE if the device is busy
References XV_HdmiTxSs1::HdmiTx1Ptr.
int XV_HdmiTxSs1_ReadEdid(XV_HdmiTxSs1 *InstancePtr, u8 *BufferPtr, u32 BufferSize)
This function reads the HDMI Sink EDID.
InstancePtr is a pointer to the HDMI TX Subsystem instance. Buffer is a pointer to the buffer where the EDID data will be stored. BufferSize is the size of the buffer in bytes. XST_SUCCESS if EDID is read successfully.XST_FAILURE if the operation failed or the buffer is too small. None. None.
References XV_HdmiTxSs1::HdmiTx1Ptr, XV_HdmiTxSs1::IsStreamConnected, XV_HdmiTxSs1_ReadEdidSegment.
int XV_HdmiTxSs1_ReadEdid_extension(XV_HdmiTxSs1 *InstancePtr, XV_VidC_EdidCntrlParam *EdidCtrlParam, u8 *BufferPtr, u32 BufferSize)
This function reads the HDMI Sink EDID.
InstancePtr is a pointer to the HDMI TX Subsystem instance. EdidCtrlParam is a pointer to the EDID control parameter structure. BufferPtr is a pointer to the buffer to store the EDID data. BufferSize is the size of the buffer in bytes. XST_SUCCESS if EDID is read successfully, otherwise XST_FAILURE. None.
References XV_HdmiTxSs1::HdmiTx1Ptr, XV_HdmiTxSs1::IsStreamConnected, XV_HdmiTxSs1_ReadEdidSegment.
int XV_HdmiTxSs1_ReadEdidSegment(XV_HdmiTxSs1 *InstancePtr, u8 *Buffer, u8 segment)
This function reads a 256-byte EDID segment from the HDMI sink connected to the transmitter.
It handles segment selection and reads two 128-byte blocks (offsets 0 and 128) into the provided buffer. If the segment is not zero, it sets the segment pointer before reading. InstancePtr Pointer to the HDMI TX Subsystem instance. Buffer Pointer to a buffer where the EDID data will be stored. Must be at least 256 bytes. segment The EDID segment number to read. XST_SUCCESS if the EDID segment was read successfully.XST_FAILURE if the operation failed or no sink is connected. The function assumes that the HDMI sink is connected.The buffer must be large enough to hold 256 bytes.
References XV_HdmiTxSs1::HdmiTx1Ptr, XV_HdmiTxSs1::IsStreamConnected.
Referenced by XV_HdmiTxSs1_ReadEdid, XV_HdmiTxSs1_ReadEdid_extension, XV_HdmiTxSs1_ShowEdid, XV_HdmiTxSs1_ShowEdid_extension.
void XV_HdmiTxSs1_ShowEdid(XV_HdmiTxSs1 *InstancePtr)
This function shows the HDMI source edid.
InstancePtr is a pointer to the HDMI TX Subsystem instance. None. None.
References XV_HdmiTxSs1::IsStreamConnected, XV_HdmiTxSs1_ReadEdidSegment.
void XV_HdmiTxSs1_ShowEdid_extension(XV_HdmiTxSs1 *InstancePtr, XV_VidC_EdidCntrlParam *EdidCtrlParam)
This function shows the HDMI source edid.
InstancePtr is a pointer to the HDMI TX Subsystem instance. EdidCtrlParam is a pointer to the EDID control parameter structure. None. None.
References XV_HdmiTxSs1::IsStreamConnected, XV_HdmiTxSs1_ReadEdidSegment.
void XV_HdmiTxSs1_SetScrambler(XV_HdmiTxSs1 *InstancePtr, u8 Enable)
This function enables / disables the TX scrambler.
InstancePtr is a pointer to the Subsystem instance to be worked on. Enable TRUE:Enable scrambler FALSE:Disable scrambler None. The scrambler setting will revert to the default behavior during the next stream configuration (scrambler is enabled for HDMI 2.0 video and disabled when the video is of HDMI 1.4 or lower)
References XV_HdmiTxSs1::HdmiTx1Ptr, XV_HdmiTxSs1_SetVideoStreamScramblingFlag.
void XV_HdmiTxSs1_StreamStart(XV_HdmiTxSs1 *InstancePtr)
This function starts the HDMI TX stream.
InstancePtr is a pointer to the HDMI TX Subsystem instance. None.
References XV_HdmiTxSs1::HdmiTx1Ptr, XV_HDMITXSS1_LOG_EVT_STREAMSTART, XV_HdmiTxSs1_LogWrite.
void XV_HdmiTxSs1_SendAuxInfoframe(XV_HdmiTxSs1 *InstancePtr, void *AuxPtr)
This function sends audio info frames.
InstancePtr is a pointer to the HDMI TX Subsystem instance. Aux is a pointer to the auxiliary infoframe structure to send. None. None.
References XV_HdmiTxSs1::HdmiTx1Ptr.
u32 XV_HdmiTxSs1_SendGenericAuxInfoframe(XV_HdmiTxSs1 *InstancePtr, void *AuxPtr)
This function sends a generic HDMI auxiliary infoframe.
InstancePtr is a pointer to the HDMI TX Subsystem instance. Aux is a pointer to the auxiliary infoframe structure to send. XST_SUCCESS if infoframe transmitted successfully.XST_FAILURE if AUX FIFO is full. None.
References XV_HdmiTxSs1::HdmiTx1Ptr.
void XV_HdmiTxSs1_SetAudioChannels(XV_HdmiTxSs1 *InstancePtr, u8 AudioChannels)
This function Sets the HDMI TX SS number of active audio channels.
InstancePtr pointer to XV_HdmiTxSs1 instance AudioChannels None. None.
References XV_HdmiTxSs1::AudioChannels, XV_HdmiTxSs1::AudioInfoframe, XV_HdmiTxSs1::HdmiTx1Ptr, XV_HDMITXSS1_LOG_EVT_SETAUDIOCHANNELS, XV_HdmiTxSs1_LogWrite.
void XV_HdmiTxSs1_AudioMute(XV_HdmiTxSs1 *InstancePtr, u8 Enable)
This function set HDMI TX audio parameters.
InstancePtr pointer to XV_HdmiTxSs1 instance* Enable 0: Unmute the audio 1: Mute the audio. None. None.
References XV_HdmiTxSs1::HdmiTx1Ptr, XV_HDMITXSS1_LOG_EVT_AUDIOMUTE, XV_HDMITXSS1_LOG_EVT_AUDIOUNMUTE, XV_HdmiTxSs1_LogWrite.
void XV_HdmiTxSs1_SetAudioFormat(XV_HdmiTxSs1 *InstancePtr, XV_HdmiTx1_AudioFormatType format)
This function Sets the HDMI TX SS Audio Format.
InstancePtr pointer to XV_HdmiTxSs1 instance format 1:HBR 0:L-PCM None. None.
References XV_HdmiTxSs1::HdmiTx1Ptr.
void XV_HdmiTxSs1_SetIntACR(XV_HdmiTxSs1 *InstancePtr)
This function Sets use the internal ACR Module.
InstancePtr pointer to XV_HdmiTxSs1 instance None. None.
References XV_HdmiTxSs1::HdmiTx1Ptr.
void XV_HdmiTxSs1_SetExtACR(XV_HdmiTxSs1 *InstancePtr)
This function Sets use the external ACR Module.
InstancePtr pointer to XV_HdmiTxSs1 instance None. None.
References XV_HdmiTxSs1::HdmiTx1Ptr.
void XV_HdmiTxSs1_SetSampleFrequency(XV_HdmiTxSs1 *InstancePtr, XHdmiC_SamplingFrequencyVal AudSampleFreqVal)
This function Sets the audio sampling frequency.
InstancePtr pointer to XV_HdmiTxSs1 instance AudSampleFreqVal Sample Frequency in Hz None. None.
References XV_HdmiTxSs1::HdmiTx1Ptr, XV_HDMITXSS1_LOG_EVT_AUDIOINVALIDSAMPRATE, XV_HdmiTxSs1_LogWrite.
XV_HdmiTx1_AudioFormatType XV_HdmiTxSs1_GetAudioFormat(XV_HdmiTxSs1 *InstancePtr)
This function gets the active audio format.
InstancePtr is a pointer to the XV_HdmiTxSs1 core instance. Active audio format of HDMI Tx Subsystem None.
References XV_HdmiTxSs1::HdmiTx1Ptr.
Referenced by XV_HdmiTxSs1_ReportAudio.
XHdmiC_Aux* XV_HdmiTxSs1_GetAuxiliary(XV_HdmiTxSs1 *InstancePtr)
This function returns the pointer to HDMI TX SS Aux structure.
InstancePtr pointer to XV_HdmiTxSs1 instance XVidC_VideoStream pointer None.
References XV_HdmiTxSs1::HdmiTx1Ptr.
XHdmiC_AVI_InfoFrame* XV_HdmiTxSs1_GetAviInfoframe(XV_HdmiTxSs1 *InstancePtr)
This function returns the pointer to HDMI TX SS AVI InfoFrame structure.
InstancePtr pointer to XV_HdmiTxSs1 instance XHdmiC_AVI_InfoFrame pointer None.
References XV_HdmiTxSs1::AVIInfoframe.
XHdmiC_AudioInfoFrame* XV_HdmiTxSs1_GetAudioInfoframe(XV_HdmiTxSs1 *InstancePtr)
This function returns the pointer to HDMI TX SS Audio InfoFrame structure.
InstancePtr pointer to XV_HdmiTxSs1 instance XHdmiC_AudioInfoFrame pointer None.
References XV_HdmiTxSs1::AudioInfoframe.
XHdmiC_VSIF* XV_HdmiTxSs1_GetVSIF(XV_HdmiTxSs1 *InstancePtr)
This function returns the pointer to HDMI TX SS Vendor Specific InfoFrame structure.
InstancePtr pointer to XV_HdmiTxSs1 instance XHdmiC_VSIF pointer None.
References XV_HdmiTxSs1::VSIF.
XHdmiC_DRMInfoFrame* XV_HdmiTxSs1_GetDrmInfoframe(XV_HdmiTxSs1 *InstancePtr)
This function returns the pointer to HDMI 2.1 TX SS DRM InfoFrame structure.
InstancePtr pointer to XV_HdmiTxSs1 instance XHdmiC_DRMInfoFrame pointer None.
References XV_HdmiTxSs1::DrmInfoframe.
Referenced by XV_HdmiTxSs1_ReportDRMInfo.
u32 XV_HdmiTxSs1_SetStream(XV_HdmiTxSs1 *InstancePtr, XVidC_VideoTiming VideoTiming, XVidC_FrameRate FrameRate, XVidC_ColorFormat ColorFormat, XVidC_ColorDepth Bpc, u8 IsDSCompressed, XVidC_3DInfo *Info3D, u64 *TmdsClk)
This function set HDMI TX subsystem stream parameters.
It returns the calculated TMDS clock value. InstancePtr - Pointer to HDMI 2.1 Tx Subsystem. VideoTiming - Video Timing of the video to be displayed. FrameRate - Frame rate to set ColorFormat - Color format of stream (RGB, YUV444/422/420) Bpc - Bit per component IsDSCompressed - Flag to indicate DSCompression Info3D - 3D Info TmdsClock - Address where the calculated TMDS Clock value is stored. XST_SUCCESS - In case TMDS clock is calculated correctly XST_INVALID_PARAM - In case invalid parameters None.
References XV_HdmiTxSs1::Config, XV_HdmiTxSs1::HdmiTx1Ptr, XV_HdmiTxSs1_Config::Ppc, XV_HdmiTxSs1_Config::VideoInterface, XV_HDMITXSS1_LOG_EVT_SETSTREAM, XV_HdmiTxSs1_LogWrite.
XVidC_VideoStream* XV_HdmiTxSs1_GetVideoStream(XV_HdmiTxSs1 *InstancePtr)
This function returns the pointer to HDMI TX SS video stream.
InstancePtr pointer to XV_HdmiTxSs1 instance XVidC_VideoStream pointer None.
References XV_HdmiTxSs1::HdmiTx1Ptr.
Referenced by main, XV_HdmiTxSS1_SetBackgroundColor, XV_HdmiTxSS1_SetVrrVfpStretch.
void XV_HdmiTxSs1_SetVideoStream(XV_HdmiTxSs1 *InstancePtr, XVidC_VideoStream VidStream)
This function Sets the HDMI TX SS video stream.
InstancePtr pointer to XV_HdmiTxSs1 instance VidStream video stream to be set None. None.
References XV_HdmiTxSs1::HdmiTx1Ptr.
void XV_HdmiTxSs1_SetSamplingRate(XV_HdmiTxSs1 *InstancePtr, u8 SamplingRate)
This function Sets the HDMI TX SS video Identification code.
InstancePtr pointer to XV_HdmiTxSs1 instance SamplingRate Value None. None.
References XV_HdmiTxSs1::SamplingRate.
void XV_HdmiTxSs1_SetVideoIDCode(XV_HdmiTxSs1 *InstancePtr, u8 Vic)
This function Sets the HDMI TX SS video Identification code.
InstancePtr pointer to XV_HdmiTxSs1 instance Vic is a VIC ID value None. None.
References XV_HdmiTxSs1::HdmiTx1Ptr.
u8 XV_HdmiTxSs1_GetVideoStreamType(XV_HdmiTxSs1 *InstancePtr)
This function returns the HDMI TX SS video stream type.
InstancePtr pointer to XV_HdmiTxSs1 instance Value 1:HDMI TMDS 0:DVI. None.
References XV_HdmiTxSs1::HdmiTx1Ptr.
u8 XV_HdmiTxSs1_GetTransportMode(XV_HdmiTxSs1 *InstancePtr)
This function returns the pointer to HDMI TX SS video stream type.
InstancePtr pointer to XV_HdmiTxSs1 instance Transport Mode 1:FRL 0:TMDS None.
References XV_HdmiTxSs1::HdmiTx1Ptr.
void XV_HdmiTxSs1_SetVideoStreamScramblingFlag(XV_HdmiTxSs1 *InstancePtr, u8 IsScrambled)
This function Sets the HDMI TX SS video stream type.
InstancePtr pointer to XV_HdmiTxSs1 instance IsScrambled 1:IsScrambled 0: not Scrambled None. None.
References XV_HdmiTxSs1::HdmiTx1Ptr.
Referenced by XV_HdmiTxSs1_SetScrambler.
void XV_HdmiTxSs1_SetVideoStreamScramblingOverrideFlag(XV_HdmiTxSs1 *InstancePtr, u8 OverrideScramble)
This function Sets the HDMI TX SS video stream scrambling behaviour.
Setting OverrideScramble to true will force enabling/disabling scrambling function based on the value of IsScrambled flag. InstancePtr pointer to XV_HdmiTxSs1 instance OverrideScramble 0: Scrambling is always enabled for HDMI 2.0 resolutions and is enabled /or disabled for HDMI 1.4 resolutions based on IsScrambled value 1: Enable scrambling if IsScrambled is TRUE and disable scrambling if IsScrambled is FALSE None. None.
References XV_HdmiTxSs1::HdmiTx1Ptr.
void XV_HdmiTxSs1_SetTmdsClockRatio(XV_HdmiTxSs1 *InstancePtr, u8 Ratio)
This function Sets the HDMI TX SS TMDS Cock Ratio.
InstancePtr pointer to XV_HdmiTxSs1 instance Ratio 0 - 1/10, 1 - 1/40 None. None.
References XV_HdmiTxSs1::HdmiTx1Ptr.
u32 XV_HdmiTxSs1_GetTmdsClockFreqHz(XV_HdmiTxSs1 *InstancePtr)
This function Sets the HDMI TX SS video Identification code.
InstancePtr pointer to XV_HdmiTxSs1 instance Stream Data Structure (TMDS Clock) None.
References XV_HdmiTxSs1::HdmiTx1Ptr.
int XV_HdmiTxSs1_DetectHdmi20(XV_HdmiTxSs1 *InstancePtr)
This function detects connected sink is a HDMI 2.0/HDMI 1.4 sink device.
InstancePtr is a pointer to the XV_HdmiTxSs1 core instance. XST_SUCCESS if HDMI 2.0XST_FAILURE if HDMI 1.4 None.
References XV_HdmiTxSs1::HdmiTx1Ptr.
void XV_HdmiTxSs1_RefClockChangeInit(XV_HdmiTxSs1 *InstancePtr)
This function is called when HDMI TX SS TMDS clock changes.
InstancePtr is a pointer to the HDMI TX Subsystem instance. None None.
References XV_HdmiTxSs1::HdmiTx1Ptr, XV_HdmiTxSs1_SYSRST, XV_HdmiTxSs1_TXCore_LRST, XV_HdmiTxSs1_TXCore_VRST, XV_HdmiTxSs1_VRST.
void XV_HdmiTxSs1_ReportInfo(XV_HdmiTxSs1 *InstancePtr)
This function prints the HDMI TX SS subcore versions.
InstancePtr is a pointer to the HDMI TX Subsystem instance. None. None.
References XV_HdmiTxSs1_ReportAudio, XV_HdmiTxSs1_ReportCoreInfo, XV_HdmiTxSs1_ReportDRMInfo, XV_HdmiTxSs1_ReportSubcoreVersion, XV_HdmiTxSs1_ReportTiming.
void XV_HdmiTxSs1_DebugInfo(XV_HdmiTxSs1 *InstancePtr)
This function prints debug information on STDIO/UART console.
InstancePtr is a pointer to the XV_HdmiTxSs1 instance. None. None.
References XV_HdmiTxSs1::HdmiTx1Ptr.
Referenced by DetailedInfo.
void XV_HdmiTxSs1_RegisterDebug(XV_HdmiTxSs1 *InstancePtr)
This function prints out the sub-core register dump.
InstancePtr Instance Pointer to the main data structure None. None.
References XV_HdmiTxSs1::Config, XV_HdmiTxSs1::HdmiTx1Ptr, XV_HdmiTxSs1::IsStreamUp, XV_HdmiTxSs1_Config::Vtc, XV_HdmiTxSs1::VtcPtr.
int XV_HdmiTxSs1_IsStreamUp(XV_HdmiTxSs1 *InstancePtr)
This function checks if the video stream is up.
InstancePtr is a pointer to the HDMI TX Subsystem instance. TRUE if stream is up.FALSE if stream is down. None.
References XV_HdmiTxSs1::IsStreamUp.
int XV_HdmiTxSs1_IsStreamConnected(XV_HdmiTxSs1 *InstancePtr)
This function checks if the interface is connected.
InstancePtr is a pointer to the HDMI TX Subsystem instance. TRUE if the interface is connected.FALSE if the interface is not connected. None.
References XV_HdmiTxSs1::IsStreamConnected.
int XV_HdmiTxSs1_IsStreamToggled(XV_HdmiTxSs1 *InstancePtr)
This function checks if the interface has toggled.
InstancePtr is a pointer to the HDMI TX Subsystem instance. TRUE if the interface HPD has toggled.FALSE if the interface HPD has not toggled. None.
References XV_HdmiTxSs1::IsStreamToggled.
u8 XV_HdmiTxSs1_IsSinkHdcp14Capable(XV_HdmiTxSs1 *InstancePtr)
This function determines if the connected HDMI sink is HDCP 1.4 capable.
InstancePtr is a pointer to the XV_HdmiTxSs1 instance. TRUE if sink is HDCP 1.4 capable and ready to authenticate.FALSE if sink does not support HDCP 1.4 or is not ready.
u8 XV_HdmiTxSs1_IsSinkHdcp22Capable(XV_HdmiTxSs1 *InstancePtr)
This function determines if the connected HDMI sink is HDCP 2.2 capable.
InstancePtr is a pointer to the XV_HdmiTxSs1 instance. TRUE if sink is HDCP 2.2 capable and ready to authenticate.FALSE if sink does not support HDCP 2.2 or is not ready.
void XV_HdmiTxSs1_SetDefaultPpc(XV_HdmiTxSs1 *InstancePtr, u8 Id)
This function will set the default in HDF.
InstancePtr is a pointer to the XV_HdmiTxSs1 core instance. Id is the XV_HdmiTxSs1 ID to operate on. None. None.
References XV_HdmiTxSs1::Config, XV_HdmiTxSs1_Config::Ppc.
void XV_HdmiTxSs1_SetPpc(XV_HdmiTxSs1 *InstancePtr, u8 Id, u8 Ppc)
This function will set PPC specified by user.
InstancePtr is a pointer to the XV_HdmiTxSs1 core instance. Id is the XV_HdmiTxSs1 ID to operate on. Ppc is the PPC to be set. None. None.
References XV_HdmiTxSs1::Config, XV_HdmiTxSs1_Config::Ppc.
XVidC_PixelsPerClock XV_HdmiTxSS1_GetCorePpc(XV_HdmiTxSs1 *InstancePtr)
This function will set the major and minor application version in TXSs struct.
InstancePtr is a pointer to the XV_HdmiTxSs1 core instance. Core pixel per clock value None.
References XV_HdmiTxSs1::HdmiTx1Ptr.
void XV_HdmiTxSs1_VrrControl(XV_HdmiTxSs1 *InstancePtr, u8 Enable)
This function allows enabling/disabling of VRR in HDMI Tx.
InstancePtr is a pointer to the XV_HdmiTxSs1 core instance. Enable 0: disable VRR 1: enable VRR None.
References XV_HdmiTxSs1::HdmiTx1Ptr.
Referenced by Exdes_ProcessVTEMPacket, main.
void XV_HdmiTxSs1_FSyncControl(XV_HdmiTxSs1 *InstancePtr, u8 Enable)
This function allows enabling/disabling of FSync in HDMI Tx.
InstancePtr is a pointer to the XV_HdmiTxSs1 core instance. Enable 0: disable FSync 1: enable FSync None. None.
References XV_HdmiTxSs1::HdmiTx1Ptr.
Referenced by Exdes_ProcessVTEMPacket, main.
void XV_HdmiTxSS1_SetVrrMode(XV_HdmiTxSs1 *InstancePtr, u8 mode, u8 VrrEn, u8 FvaFactor, u8 CnmvrrEn)
This function configures Video Timing Controller with Adaptive-Sync mode.
InstancePtr is a pointer to the XV_HdmiTxSs1 instance. mode is vtc mode. 0: Fixed stretch, 1: Auto VrrEn is to enable/disable VRR FvaFactor is to set FVA factor value CnmvrrEn is to enable/disable Cnmvrr None. Should be called before XV_HdmiTxSs1_SetStream at least once for VRR use case.
void XV_HdmiTxSS1_SetVrrVfpStretch(XV_HdmiTxSs1 *InstancePtr, u16 StretchValue)
This function configures vertical front porch stretch limit in Video Timing Controller.
InstancePtr is a pointer to the XV_HdmiTxSs1 instance. StretchValue is vertical front porch stretch value. None. Call after XV_HdmiTxSs1_SetStream and VRR mode is already set through XV_HdmiTxSS1_SetVrrMode.
References XV_HdmiTxSs1::VtcPtr, XV_HdmiTxSs1_GetVideoStream.
Referenced by Exdes_ProcessVRRTimingChange, main.
void XV_HdmiTxSS1_DisableVrr(XV_HdmiTxSs1 *InstancePtr)
This function disables Adaptive-Sync feature in Video Timing Controller.
InstancePtr is a pointer to the XV_HdmiTxSs1 instance. None. None.
References XV_HdmiTxSs1::VtcPtr.
void XV_HdmiTxSs1_SetVrrIf(XV_HdmiTxSs1 *InstancePtr, XV_HdmiC_VrrInfoFrame *VrrIF)
This function allows setting VRR meta in core.
InstancePtr is a pointer to the XV_HdmiTxSs1 instance. VrrIF is a pointer to the XV_HdmiC_VrrInfoFrame structure None. None.
References XV_HdmiTxSs1::HdmiTx1Ptr.
Referenced by Exdes_ProcessVTEMPacket, main.
void XV_HdmiTxSs1_SetCustomVrrIf(XV_HdmiTxSs1 *InstancePtr, XV_HdmiC_VrrInfoFrame *VrrIF, u16 Sync, u16 DataSetLen)
This function allows setting Custom VRR meta in core.
InstancePtr is a pointer to the XV_HdmiTxSs1 instance. VrrIF is a pointer to the XV_HdmiC_VrrInfoFrame structure Sync is a Value of sync in Vrr packet DataSetLen is a Value of data set length None. None.
References XV_HdmiTxSs1::HdmiTx1Ptr.
void XV_HdmiTxSs1_DynHdr_Control(XV_HdmiTxSs1 *InstancePtr, u8 Flag)
This function will enable/disable Dynamic HDR.
InstancePtr is a pointer to the XV_HdmiTxSs1 core instance. Flag set to TRUE/FALSE. void. None.
References XV_HdmiTxSs1::Config, XV_HdmiTxSs1_Config::DynHdr, XV_HdmiTxSs1::HdmiTx1Ptr.
void XV_HdmiTxSs1_DynHdr_GOF_Control(XV_HdmiTxSs1 *InstancePtr, u8 Flag)
This function will enable/disable GOF for Dynamic HDR.
InstancePtr is a pointer to the XV_HdmiTxSs1 core instance. Flag set to TRUE/FALSE. void. None.
References XV_HdmiTxSs1::Config, XV_HdmiTxSs1_Config::DynHdr, XV_HdmiTxSs1::HdmiTx1Ptr.
void XV_HdmiTxSs1_DynHdr_Cfg(XV_HdmiTxSs1 *InstancePtr, XV_HdmiTxSs1_DynHdr_Config *Cfg)
This function will configure the HDMI Tx for Dynamic HDR.
The configuration should be updated and called by application in Dynamic HDR MTW callback. InstancePtr is a pointer to the XV_HdmiTxSs1 core instance. CfgPtr is a pointer to XV_HdmiTxSs1_DynHdr_Config instance void. None.
References XV_HdmiTxSs1_DynHdr_Config::Address, XV_HdmiTxSs1::Config, XV_HdmiTxSs1_Config::DynHdr, XV_HdmiTxSs1_DynHdr_Config::FAPA, XV_HdmiTxSs1_DynHdr_Config::GOF, XV_HdmiTxSs1_DynHdr_Config::PktLength, XV_HdmiTxSs1_DynHdr_Config::PktType.
void XV_HdmiTxSs1_DynHdr_DM_Control(XV_HdmiTxSs1 *InstancePtr, u8 Flag)
This function will enable or disable the Data Mover in Dynamic HDR.
InstancePtr is a pointer to the XV_HdmiTxSs1 core instance. Flag 0 to disable and 1 to enable the Data Mover void. None.
References XV_HdmiTxSs1::Config, XV_HdmiTxSs1_Config::DynHdr, XV_HdmiTxSs1::HdmiTx1Ptr.
u32 XV_HdmiTxSs1_DynHdr_GetErr(XV_HdmiTxSs1 *InstancePtr)
This function will read the error status of the Data Mover for Dynamic HDR.
InstancePtr is a pointer to the XV_HdmiTxSs1 core instance. 0 - if no error else 1 None.
References XV_HdmiTxSs1::Config, XV_HdmiTxSs1_Config::DynHdr.
void XV_HdmiTxSs1_LogReset(XV_HdmiTxSs1 *InstancePtr)
This function will reset the driver's logging mechanism.
InstancePtr is a pointer to the xv_hdmitxss1 core instance. None. None.
References XV_HdmiTxSs1_Log::HeadIndex, XV_HdmiTxSs1::Log, XV_HdmiTxSs1_Log::TailIndex.
void XV_HdmiTxSs1_LogWrite(XV_HdmiTxSs1 *InstancePtr, XV_HdmiTxSs1_LogEvent Evt, u8 Data)
This function will insert an event in the driver's logginc mechanism.
InstancePtr is a pointer to the XV_HdmiTxSs1 core instance. Evt is the event type to log. Data is the associated data for the event. None. None.
References XV_HdmiTxSs1_Log::DataBuffer, XV_HdmiTxSs1_Log::HeadIndex, XV_HdmiTxSs1::Log, XV_HdmiTxSs1::LogWriteCallback, XV_HdmiTxSs1::LogWriteRef, XV_HdmiTxSs1_Log::TailIndex, XV_HdmiTxSs1_Log::TimeRecord, XV_HDMITXSS1_LOG_EVT_DUMMY.
Referenced by XV_HdmiTxSs1_AudioMute, XV_HdmiTxSs1_Reset, XV_HdmiTxSs1_SetAudioChannels, XV_HdmiTxSs1_SetSampleFrequency, XV_HdmiTxSs1_SetStream, XV_HdmiTxSs1_Start, XV_HdmiTxSs1_Stop, XV_HdmiTxSs1_StreamStart, XV_HdmiTxSs1_SubcoreInitHdmiTx1, XV_HdmiTxSs1_SubcoreInitVtc, XV_HdmiTxSs1_TmdsConfigCallback.
u16 XV_HdmiTxSs1_LogRead(XV_HdmiTxSs1 *InstancePtr)
This function will read the last event from the log.
InstancePtr is a pointer to the XV_HdmiTxSs1 core instance. The log data. None.
References XV_HdmiTxSs1_Log::DataBuffer, XV_HdmiTxSs1_Log::HeadIndex, XV_HdmiTxSs1::Log, XV_HdmiTxSs1_Log::TailIndex.
Referenced by XV_HdmiTxSs1_LogDisplay.
void XV_HdmiTxSs1_LogDisplay(XV_HdmiTxSs1 *InstancePtr)
This function will print the entire log.
InstancePtr is a pointer to the XV_HdmiTxSs1 core instance. None. None.
References XV_HdmiTxSs1::Log, XV_HdmiTxSs1::LogWriteCallback, XV_HdmiTxSs1_Log::TailIndex, XV_HdmiTxSs1_Log::TimeRecord, XV_HDMITXSS1_LOG_EVT_AUDIOINVALIDSAMPRATE, XV_HDMITXSS1_LOG_EVT_AUDIOMUTE, XV_HDMITXSS1_LOG_EVT_AUDIOUNMUTE, XV_HDMITXSS1_LOG_EVT_BRDG_LOCKED, XV_HDMITXSS1_LOG_EVT_BRDG_UNLOCKED, XV_HDMITXSS1_LOG_EVT_CONNECT, XV_HDMITXSS1_LOG_EVT_DISCONNECT, XV_HDMITXSS1_LOG_EVT_FRL_CFG, XV_HDMITXSS1_LOG_EVT_FRL_LT_PASS, XV_HDMITXSS1_LOG_EVT_FRL_START, XV_HDMITXSS1_LOG_EVT_HDCP14_AUTHREQ, XV_HDMITXSS1_LOG_EVT_HDCP14_INIT, XV_HDMITXSS1_LOG_EVT_HDCP22_AUTHREQ, XV_HDMITXSS1_LOG_EVT_HDCP22_INIT, XV_HDMITXSS1_LOG_EVT_HDCPTIMER_INIT, XV_HDMITXSS1_LOG_EVT_HDMITX1_INIT, XV_HDMITXSS1_LOG_EVT_NONE, XV_HDMITXSS1_LOG_EVT_PIX_REPEAT_ERR, XV_HDMITXSS1_LOG_EVT_RESET, XV_HDMITXSS1_LOG_EVT_SETAUDIOCHANNELS, XV_HDMITXSS1_LOG_EVT_SETSTREAM, XV_HDMITXSS1_LOG_EVT_START, XV_HDMITXSS1_LOG_EVT_STOP, XV_HDMITXSS1_LOG_EVT_STREAMDOWN, XV_HDMITXSS1_LOG_EVT_STREAMSTART, XV_HDMITXSS1_LOG_EVT_STREAMUP, XV_HDMITXSS1_LOG_EVT_TMDS_START, XV_HDMITXSS1_LOG_EVT_TOGGLE, XV_HDMITXSS1_LOG_EVT_VTC_INIT, XV_HDMITXSS1_LOG_EVT_VTC_RES_ERR, XV_HdmiTxSs1_LogRead.
void XV_HdmiTxSs1_ReportCoreInfo(XV_HdmiTxSs1 *InstancePtr)
This function reports list of cores included in Video Processing Subsystem.
InstancePtr is a pointer to the Subsystem instance. None
References XV_HdmiTxSs1::HdmiTx1Ptr, XV_HdmiTxSs1::VtcPtr.
Referenced by DetailedInfo, XV_HdmiTxSs1_ReportInfo.
void XV_HdmiTxSs1_ReportTiming(XV_HdmiTxSs1 *InstancePtr)
This function prints the HDMI TX SS timing information.
InstancePtr is a pointer to the HDMI TX Subsystem instance.. None. None.
References XV_HdmiTxSs1::HdmiTx1Ptr, XV_HdmiTxSS1_IsMasked.
Referenced by Info, XV_HdmiTxSs1_ReportInfo.
void XV_HdmiTxSs1_ReportDRMInfo(XV_HdmiTxSs1 *InstancePtr)
This function prints the HDMI 2.1 TX SS DRM If information.
InstancePtr is a pointer to the HDMI TX Subsystem instance. None. None.
References XV_HdmiTxSs1_GetDrmInfoframe.
Referenced by Info, XV_HdmiTxSs1_ReportInfo.
void XV_HdmiTxSs1_ReportAudio(XV_HdmiTxSs1 *InstancePtr)
This function prints the HDMI TX SS audio information.
InstancePtr is a pointer to the HDMI TX Subsystem instance. None. None.
References XV_HdmiTxSs1::HdmiTx1Ptr, XV_HdmiTxSs1_GetAudioFormat.
Referenced by Info, XV_HdmiTxSs1_ReportInfo.
void XV_HdmiTxSs1_ReportSubcoreVersion(XV_HdmiTxSs1 *InstancePtr)
This function prints the HDMI TX SS subcore versions.
InstancePtr is a pointer to the HDMI TX Subsystem instance. None. None.
References XV_HdmiTxSs1::HdmiTx1Ptr, XV_HdmiTxSs1::IsStreamUp, XV_HdmiTxSs1::VtcPtr.
Referenced by DetailedInfo, XV_HdmiTxSs1_ReportInfo.
void XV_HdmiTxSS1_MaskEnable(XV_HdmiTxSs1 *InstancePtr)
This function will enable the video masking.
InstancePtr is a pointer to the XV_HdmiTxSs1 core instance. None. None.
References XV_HdmiTxSs1::HdmiTx1Ptr.
Referenced by XV_HdmiTxSS1_SetBackgroundColor.
void XV_HdmiTxSS1_MaskDisable(XV_HdmiTxSs1 *InstancePtr)
This function will disable the video masking.
InstancePtr is a pointer to the XV_HdmiTxSs1 core instance. None. None.
References XV_HdmiTxSs1::HdmiTx1Ptr.
void XV_HdmiTxSS1_MaskNoise(XV_HdmiTxSs1 *InstancePtr, u8 Enable)
This function will enable or disable the noise in the video mask.
InstancePtr is a pointer to the XV_HdmiTxSs1 core instance. Enable specifies TRUE/FALSE value to either enable or disable the Noise. None. None.
References XV_HdmiTxSs1::HdmiTx1Ptr.
Referenced by XV_HdmiTxSS1_SetBackgroundColor.
void XV_HdmiTxSS1_MaskSetRed(XV_HdmiTxSs1 *InstancePtr, u16 Value)
This function will set the red component in the video mask.
InstancePtr is a pointer to the XV_HdmiTxSs1 core instance. Value specifies the video mask value set to red component None. None.
References XV_HdmiTxSs1::HdmiTx1Ptr.
Referenced by XV_HdmiTxSS1_SetBackgroundColor.
void XV_HdmiTxSS1_MaskSetGreen(XV_HdmiTxSs1 *InstancePtr, u16 Value)
This function will set the green component in the video mask.
InstancePtr is a pointer to the XV_HdmiTxSs1 core instance. Value specifies the video mask value set to green component None. None.
References XV_HdmiTxSs1::HdmiTx1Ptr.
Referenced by XV_HdmiTxSS1_SetBackgroundColor.
void XV_HdmiTxSS1_MaskSetBlue(XV_HdmiTxSs1 *InstancePtr, u16 Value)
This function will set the blue component in the video mask.
InstancePtr is a pointer to the XV_HdmiTxSs1 core instance. Value specifies the video mask value set to blue component None. None.
References XV_HdmiTxSs1::HdmiTx1Ptr.
Referenced by XV_HdmiTxSS1_SetBackgroundColor.
void XV_HdmiTxSS1_SetBackgroundColor(XV_HdmiTxSs1 *InstancePtr, XVMaskColorId ColorId)
This function configures the background color for Video Masking Feature.
InstancePtr is a pointer to the core instance to be worked on. ColorId is the background color requested None
References XV_HdmiTxSs1::HdmiTx1Ptr, XV_HdmiTxSs1_GetVideoStream, XV_HdmiTxSS1_MaskEnable, XV_HdmiTxSS1_MaskNoise, XV_HdmiTxSS1_MaskSetBlue, XV_HdmiTxSS1_MaskSetGreen, XV_HdmiTxSS1_MaskSetRed.
u8 XV_HdmiTxSS1_IsMasked(XV_HdmiTxSs1 *InstancePtr)
This function will get the current video mask mode.
InstancePtr is a pointer to the XV_HdmiTxSs1 core instance. Current mode. 0 = Video masking is disabled 1 = Video masking is enabled None.
References XV_HdmiTxSs1::HdmiTx1Ptr.
Referenced by XV_HdmiTxSs1_ReportTiming.
u8 XV_HdmiTxSs1_FrlCalcBandwidth(XV_HdmiTxSs1 *InstancePtr, XVidC_VideoMode VmId, XVidC_ColorFormat ColorFormat, XVidC_ColorDepth Bpc)
This function performs FRL bandwidth calculations and determines if the requested video and audio streams can be supported by the trained FRL link.
Audio parameters are automatically fetched from the instance. InstancePtr is a pointer to the XV_HdmiTxSs1 instance. The trained FRL LineRate and Lanes are fetched from InstancePtr->HdmiTx1Ptr->Stream.Frl after FRL training. Audio parameters are fetched from: InstancePtr->AudioEnabledInstancePtr->HdmiTx1Ptr->Stream.Audio.SampleFrequencyInstancePtr->AudioChannels VmId is the video mode ID used to lookup timing information via XVidC_GetVideoModeData(). ColorFormat is the color format (RGB, YCbCr444, YCbCr422, YCbCr420). Bpc is the bits per color component (8, 10, 12, 16). TRUE if video+audio bandwidth fits within the trained FRL rate.FALSE if bandwidth exceeds capacity or resolution is not divisible by 4. This function prints bandwidth calculation results and diagnostic information to the console via xil_printf. For TMDS mode (LineRate=0), returns TRUE if bandwidth is within 18 Gbps limit, FALSE otherwise. For FRL mode, FRL training must be completed before calling this function.
References XV_HdmiTxSs1::AudioChannels, XV_HdmiTxSs1::AudioEnabled, XV_HdmiTxSs1::HdmiTx1Ptr, XV_HDMITXSS1_FRL_AUDIO_MBPS_DIVISOR, XV_HDMITXSS1_FRL_CHAR_PER_2TB, XV_HDMITXSS1_FRL_DISP_DECIMAL, XV_HDMITXSS1_FRL_DISP_DIVISOR, XV_HDMITXSS1_FRL_ENCODE_DATA_BITS, XV_HDMITXSS1_FRL_ENCODE_LINE_BITS, XV_HDMITXSS1_FRL_GBPS_TO_BPS, XV_HDMITXSS1_FRL_MBPS_DIVISOR, XV_HDMITXSS1_FRL_OVERHEAD_COMMON, XV_HDMITXSS1_FRL_OVERHEAD_SB_3LANE, XV_HDMITXSS1_FRL_OVERHEAD_SB_4LANE, XV_HDMITXSS1_FRL_OVERHEAD_SCALE, XV_HDMITXSS1_FRL_PPM_SCALE, XV_HDMITXSS1_FRL_TB_PER_3CHAR, XV_HDMITXSS1_FRL_TOLERANCE_FRL_BIT_PPM, XV_HDMITXSS1_FRL_TRIBYTE_BITS, XV_HDMITXSS1_FRL_YUV420_DIVISOR, XV_HDMITXSS1_TMDS_MAX_BW_MBPS.
int XV_HdmiTxSs1_StartTmdsMode(XV_HdmiTxSs1 *InstancePtr)
Start TMDS mode.
InstancePtr is a pointer to the XV_HdmiTxSs1 core instance. XST_SUCCESS on success, error code otherwise.
int XV_HdmiTxSs1_TmdsStart(XV_HdmiTxSs1 *InstancePtr)
Start legacy HDMI TMDS mode.
InstancePtr is a pointer to the XV_HdmiTxSs1 core instance. XST_SUCCESS if TMDS mode is successfully started, XST_FAILURE otherwise.
u8* XV_HdmiTxSs1_GetScdcEdRegisters(XV_HdmiTxSs1 *InstancePtr)
This function returns a pointer to the SCDC ED registers associated with the HDMI transmitter instance.
InstancePtr Pointer to the XV_HdmiTxSs1 instance. Pointer to the SCDC ED registers.
References XV_HdmiTxSs1::HdmiTx1Ptr.
Referenced by DetailedInfo.
void XV_HdmiTxSS1_SetHpdTolerance(XV_HdmiTxSs1 *InstancePtr, XV_HdmiTxSs1_HpdToleranceType Type, u16 ToleranceVal)
This function will Configure Timegrid based on the tolerance value for HPD and Toggle event.
InstancePtr is a pointer to the XV_HdmiTxSs1 core instance. Type is the tolerance type. ToleranceVal is the tolerance value to be applied. void. None.
References XV_HdmiTxSs1_Config::BaseAddress, XV_HdmiTxSs1::Config, XV_HDMITXSS1_LAGGING_TOLERANCE, XV_HDMITXSS1_LEADING_TOLERANCE.