xv_hdmitxss1_log.c
void XV_HdmiTxSs1_LogReset(XV_HdmiTxSs1 *InstancePtr)
This function will reset the driver's logging mechanism.
InstancePtr is a pointer to the xv_hdmitxss1 core instance. None. None.
References XV_HdmiTxSs1_Log::HeadIndex, XV_HdmiTxSs1::Log, XV_HdmiTxSs1_Log::TailIndex.
void XV_HdmiTxSs1_LogWrite(XV_HdmiTxSs1 *InstancePtr, XV_HdmiTxSs1_LogEvent Evt, u8 Data)
This function will insert an event in the driver's logginc mechanism.
InstancePtr is a pointer to the XV_HdmiTxSs1 core instance. Evt is the event type to log. Data is the associated data for the event. None. None.
References XV_HdmiTxSs1_Log::DataBuffer, XV_HdmiTxSs1_Log::HeadIndex, XV_HdmiTxSs1::Log, XV_HdmiTxSs1::LogWriteCallback, XV_HdmiTxSs1::LogWriteRef, XV_HdmiTxSs1_Log::TailIndex, XV_HdmiTxSs1_Log::TimeRecord, XV_HDMITXSS1_LOG_EVT_DUMMY.
Referenced by XV_HdmiTxSs1_AudioMute, XV_HdmiTxSs1_Reset, XV_HdmiTxSs1_SetAudioChannels, XV_HdmiTxSs1_SetSampleFrequency, XV_HdmiTxSs1_SetStream, XV_HdmiTxSs1_Start, XV_HdmiTxSs1_Stop, XV_HdmiTxSs1_StreamStart, XV_HdmiTxSs1_SubcoreInitHdmiTx1, XV_HdmiTxSs1_SubcoreInitVtc, XV_HdmiTxSs1_TmdsConfigCallback.
u16 XV_HdmiTxSs1_LogRead(XV_HdmiTxSs1 *InstancePtr)
This function will read the last event from the log.
InstancePtr is a pointer to the XV_HdmiTxSs1 core instance. The log data. None.
References XV_HdmiTxSs1_Log::DataBuffer, XV_HdmiTxSs1_Log::HeadIndex, XV_HdmiTxSs1::Log, XV_HdmiTxSs1_Log::TailIndex.
Referenced by XV_HdmiTxSs1_LogDisplay.
void XV_HdmiTxSs1_LogDisplay(XV_HdmiTxSs1 *InstancePtr)
This function will print the entire log.
InstancePtr is a pointer to the XV_HdmiTxSs1 core instance. None. None.
References XV_HdmiTxSs1::Log, XV_HdmiTxSs1::LogWriteCallback, XV_HdmiTxSs1_Log::TailIndex, XV_HdmiTxSs1_Log::TimeRecord, XV_HDMITXSS1_LOG_EVT_AUDIOINVALIDSAMPRATE, XV_HDMITXSS1_LOG_EVT_AUDIOMUTE, XV_HDMITXSS1_LOG_EVT_AUDIOUNMUTE, XV_HDMITXSS1_LOG_EVT_BRDG_LOCKED, XV_HDMITXSS1_LOG_EVT_BRDG_UNLOCKED, XV_HDMITXSS1_LOG_EVT_CONNECT, XV_HDMITXSS1_LOG_EVT_DISCONNECT, XV_HDMITXSS1_LOG_EVT_FRL_CFG, XV_HDMITXSS1_LOG_EVT_FRL_LT_PASS, XV_HDMITXSS1_LOG_EVT_FRL_START, XV_HDMITXSS1_LOG_EVT_HDCP14_AUTHREQ, XV_HDMITXSS1_LOG_EVT_HDCP14_INIT, XV_HDMITXSS1_LOG_EVT_HDCP22_AUTHREQ, XV_HDMITXSS1_LOG_EVT_HDCP22_INIT, XV_HDMITXSS1_LOG_EVT_HDCPTIMER_INIT, XV_HDMITXSS1_LOG_EVT_HDMITX1_INIT, XV_HDMITXSS1_LOG_EVT_NONE, XV_HDMITXSS1_LOG_EVT_PIX_REPEAT_ERR, XV_HDMITXSS1_LOG_EVT_RESET, XV_HDMITXSS1_LOG_EVT_SETAUDIOCHANNELS, XV_HDMITXSS1_LOG_EVT_SETSTREAM, XV_HDMITXSS1_LOG_EVT_START, XV_HDMITXSS1_LOG_EVT_STOP, XV_HDMITXSS1_LOG_EVT_STREAMDOWN, XV_HDMITXSS1_LOG_EVT_STREAMSTART, XV_HDMITXSS1_LOG_EVT_STREAMUP, XV_HDMITXSS1_LOG_EVT_TMDS_START, XV_HDMITXSS1_LOG_EVT_TOGGLE, XV_HDMITXSS1_LOG_EVT_VTC_INIT, XV_HDMITXSS1_LOG_EVT_VTC_RES_ERR, XV_HdmiTxSs1_LogRead.