// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
//
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xv_dpt4175.h"

extern XV_dpt4175_Config XV_dpt4175_ConfigTable[];

XV_dpt4175_Config *XV_dpt4175_LookupConfig(u16 DeviceId) {
    XV_dpt4175_Config *ConfigPtr = NULL;

    int Index;

    for (Index = 0; Index < XPAR_XV_DPT4175_NUM_INSTANCES; Index++) {
        if (XV_dpt4175_ConfigTable[Index].DeviceId == DeviceId) {
            ConfigPtr = &XV_dpt4175_ConfigTable[Index];
            break;
        }
    }

    return ConfigPtr;
}

int XV_dpt4175_Initialize(XV_dpt4175 *InstancePtr, u16 DeviceId) {
    XV_dpt4175_Config *ConfigPtr;

    Xil_AssertNonvoid(InstancePtr != NULL);

    ConfigPtr = XV_dpt4175_LookupConfig(DeviceId);
    if (ConfigPtr == NULL) {
        InstancePtr->IsReady = 0;
        return (XST_DEVICE_NOT_FOUND);
    }

    return XV_dpt4175_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif
