main.c
GPIO_0_TX_MODE
GPIO_0_RX_MODE
GPIO_2_TX_FORMAT
AUD_ATPG
GT_RESET
I2C_MUX_ADDR
I2C Mux Address.
I2C_CLK_ADDR
I2C Clk Address.
I2C_CLK_ADDR_570
I2C Clk Address for Si570.
Referenced by main.
CARRIAGE_RETURN
BACKSPACE
DELETE
FREQ_148_5_MHz
FREQ_148_35_MHz
FREQ_148_43_MHz
FREQ_297_MHz
unsigned char inchar
unsigned char get_val[9][9]
char slv_type[9][9]
unsigned char IsValid
unsigned int State
unsigned char IsMode
unsigned char IsSDReso
unsigned char IsHDReso
unsigned char Is3GReso
unsigned char IsHigherReso
unsigned char IsSDFPS
unsigned char IsFPS1
unsigned char IsFPS2
unsigned char IsFPS3
unsigned char IsFPS4
fzetta_dev_type dev
u8 channel
spi_slave_sel slave_sel
u8 regaddr
u8 regdata
static int I2cMux(void)
This function setup SI5324 clock generator over IIC.
The number of bytes sent. None.
static int I2cClk(u32 InFreq, u32 OutFreq)
This function setup SI5324 clock generator either in free or locked mode.
InFreq specifies an input frequency for the si5324. OutFreq specifies the output frequency of si5324. 'XST_FAILURE' if error in programming external clock else 'XST_SUCCESS' if success None.
static int I2cClk_SI5319(u32 InFreq, u32 OutFreq)
This function setup SI5319 clock generator either in free or locked mode.
InFreq specifies an input frequency for the si5319. OutFreq specifies the output frequency of si5319. 'XST_FAILURE' if error in programming external clock else 'XST_SUCCESS' if success None.
int Si570_SetClock(u32 IICBaseAddress, u8 IICAddress1, u32 RxRefClk)
Set the output frequency of the Si570 clock generator.
IICBaseAddress contains the base address of the IIC master device. IICAddress1 contains the 7 bit IIC address of the Si5324 device. RxRefClk is the input reference clock that can be either of FREQ_SI570_148_5_MHz, FREQ_SI570_148_35_MHz SI5324_SUCCESS for success, SI5324_ERR_IIC for IIC access failure, SI5324_ERR_FREQ when the requested frequency cannot be generated, SI5324_ERR_PARM when the ClkSrc or ClkDest parameters are invalid or the ClkInFreq or ClkOutFreq are out of range. IICBaseAddress contains the base address of the IIC master device. IICAddress1 contains the 7 bit IIC address of the Si570 device. RxRefClk contains the value to be written in Si570 register for that particular clock frequency. SI570_SUCCESS for successSI570_ERR_IIC for IIC access failure,SI570_ERR_FREQ when the requested frequency cannot be generatedSI570_ERR_PARM when the ClkSrc or ClkDest parameters are invalid or the ClkInFreq or ClkOutFreq are out of range.
References Si570_DoSettings.
Referenced by main.
void slave_StringCopy(char *StrOut, spi_slave_sel slave_sel)
This function copies string based on spi slave selection.
StrOut Destination string. slave_sel The string to be copied. None None
Referenced by ctrl_app.
void cls(void)
This function clears the screen.
None. None
Referenced by main.
void get_input2_val(void)
This function takes the input from user.
None. None
Referenced by ctrl_app.
void ctrl_main_menu(unsigned char IsValid)
This function display the user menu.
IsValid Returns from menu for a 0 value. None. None
Referenced by ctrl_app.
void ctlr_spi_slv_select_menu(unsigned char IsValid)
This function displays spi slave selection menu.
IsValid Returns from menu for a 0 value. None None
Referenced by ctrl_app.
void mode_menu(unsigned char IsMode)
This function has Menu to generate modes.
IsMode Returns from menu for a 0 value. None None
Referenced by ctrl_app.
void sd_reso_menu(unsigned char IsSDReso)
This function has Menu for resolutions.
IsSDReso Returns from menu for a 0 value. None None
Referenced by ctrl_app.
void hd_reso_menu(unsigned char IsHDReso)
This function has Menu for HD resolutions.
IsHDReso Returns from menu for a 0 value. None None
Referenced by ctrl_app.
void threeg_reso_menu(unsigned char Is3GReso)
This function has Menu for 3G resolutions.
Is3GReso Returns from menu for a 0 value. None None
Referenced by ctrl_app.
void higher_reso_menu(unsigned char IsHigerReso)
This function has Menu for higher resolutions.
IsHigerReso Returns from menu for a 0 value. None None
Referenced by ctrl_app.
void fps_1_menu(unsigned char IsFPS1)
This function has Menu for fps.
IsFPS1 Returns from menu for a 0 value. None HD-720p,1080i, 3G-A, 12G
Referenced by ctrl_app.
void fps_2_menu(unsigned char IsFPS2)
This function has Menu for fps.
IsFPS2 Returns from menu for a 0 value. None HD-1080p
Referenced by ctrl_app.
void fps_3_menu(unsigned char IsFPS3)
This function has Menu for fps.
IsFPS3 Returns from menu for a 0 value. None 3G-B, 6G
Referenced by ctrl_app.
void fps_4_menu(unsigned char IsFPS4)
This function has Menu for fps.
IsFPS4 Returns from menu for a 0 value. None HD-1080pSF
Referenced by ctrl_app.
void report_audio_status(void)
This function reports audio status.
None None None
Referenced by ctrl_app.
void reset_audio_generator(void)
This function resets the audio test pattern generator.
None None None
Referenced by ctrl_app.
void GT_Reset(void)
This function resets the audio test pattern generator.
None None None
void ctrl_app(unsigned char inchar)
This function has Main control for Fidus FMC register configuration.
inchar Character input to show the main menu. None None
References ctlr_spi_slv_select_menu, ctrl_main_menu, fps_1_menu, fps_2_menu, fps_3_menu, fps_4_menu, get_input2_val, hd_reso_menu, higher_reso_menu, mode_menu, report_audio_status, reset_audio_generator, sd_reso_menu, slave_StringCopy, threeg_reso_menu.
Referenced by get_ctrl_app_input, main.
void get_ctrl_app_input(void)
This function Fetch input from UART then callback voip_contrl_app to process the selection.
None None
References ctrl_app.
Referenced by main.
int main()
Main function to call example with SDI RX and SDI TX drivers for KCU116 board.
XST_SUCCESS if SDI example was successfully.XST_FAILURE if SDI example failed. None
References cls, ctrl_app, get_ctrl_app_input, I2C_CLK_ADDR_570, Si570_SetClock.