xv_sdirxss.h
XV_SDIRXSS_IER_VIDEO_LOCK_MASK
Video lock interrupt mask.
XV_SDIRXSS_IER_VIDEO_UNLOCK_MASK
Video unlock interrupt mask.
XV_SDIRXSS_IER_OVERFLOW_MASK
Overflow interrupt mask.
XV_SDIRXSS_IER_UNDERFLOW_MASK
Underflow interrupt mask.
XV_SDIRXSS_IER_VSYNC_MASK
Vsync interrupt mask.
XV_SDIRXSS_IER_ALLINTR_MASK
All interrupts mask.
Referenced by XV_SdiRxSs_IntrDisable, XV_SdiRxSs_IntrEnable.
XV_SdiRxSs_LogEvent
Log event none.
XV_SdiRxSs_HandlerType
Handler for stream down event.
XV_SDIRXSS_H_
Prevent circular inclusions by using protection macros.
XV_SdiRxSs_GetVersion
This macro reads the RX version.
InstancePtr is a pointer to the XV_SdiRX core instance. None.
typedef void(* XV_SdiRxSs_Callback)(void *CallbackRef))(void *CallbackRef)
Callback type for interrupt.
CallbackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. None. None.
XV_SdiRxSs_Config* XV_SdiRxSs_LookupConfig(UINTPTR BaseAddress)
This function looks for the device configuration based on the unique device ID.
The table XV_SdiRxSs_ConfigTable[] contains the configuration information for each instance of the device in the system. DeviceId is the unique device ID of the device being looked up A pointer to the configuration table entry corresponding to the given device ID, or NULL if no match is found
Referenced by SdiRxSs_SelfTestExample.
u32 XV_SdiRxSs_GetDrvIndex(XV_SdiRxSs *InstancePtr, UINTPTR BaseAddress)
This function returns the Index number of config table using BaseAddress.
A pointer to the instance structure Base address of the instance Index number of the config table
int XV_SdiRxSs_CfgInitialize(XV_SdiRxSs *InstancePtr, XV_SdiRxSs_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the video subsystem and included sub-cores.
This function must be called prior to using the subsystem. Initialization includes setting up the instance data for top level as well as all included sub-core therein, and ensuring the hardware is in a known stable state. InstancePtr is a pointer to the Subsystem instance to be worked on. CfgPtr points to the configuration structure associated with the subsystem instance. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if initialization is successful else XST_FAILURE
References XV_SdiRxSs_Config::BaseAddress, XV_SdiRxSs::Config, XV_SdiRxSs::IsReady, XV_SdiRxSs::SdiRxPtr, XV_SdiRxSs_SubcoreInitSdiRx.
Referenced by SdiRxSs_SelfTestExample.
void XV_SdiRxSS_SdiRxIntrHandler(XV_SdiRxSs *InstancePtr)
This function calls the interrupt handler for SDI RX.
InstancePtr is a pointer to the SDI RX Subsystem
References XV_SdiRxSs::SdiRxPtr.
void XV_SdiRxSs_StreamFlowEnable(XV_SdiRxSs *InstancePtr)
This function enables the AXIS and video bridges.
InstancePtr pointer to XV_SdiRxSs instance None.
References XV_SdiRxSs::SdiRxPtr.
void XV_SdiRxSs_StreamFlowDisable(XV_SdiRxSs *InstancePtr)
This function disables the AXIS and video bridges.
InstancePtr pointer to XV_SdiRxSs instance None.
References XV_SdiRxSs::SdiRxPtr.
void XV_SdiRxSs_Start(XV_SdiRxSs *InstancePtr, XV_SdiRx_SearchMode Mode)
This function starts the SDI RX stream detection.
InstancePtr pointer to XV_SdiRxSs instance Mode specifies the mode of SDI modes searching operation. 0 = XV_SDIRX_SINGLESEARCHMODE_HD1 = XV_SDIRX_SINGLESEARCHMODE_SD2 = XV_SDIRX_SINGLESEARCHMODE_3G4 = XV_SDIRX_SINGLESEARCHMODE_6G5 = XV_SDIRX_SINGLESEARCHMODE_12GI6 = XV_SDIRX_SINGLESEARCHMODE_12GF10 = XV_SDIRX_MULTISEARCHMODE where the supported modes will be enabled by XV_SdiRx_EnableMode function None.
References XV_SdiRxSs::SdiRxPtr, XV_SDIRXSS_LOG_EVT_START, XV_SdiRxSs_LogWrite.
void XV_SdiRxSs_Stop(XV_SdiRxSs *InstancePtr)
This function stops the SDI RX stream detection.
InstancePtr is a pointer to the Subsystem instance to be worked on. None.
References XV_SdiRxSs::SdiRxPtr, XV_SDIRXSS_LOG_EVT_STOP, XV_SdiRxSs_LogWrite.
void XV_SdiRxSs_ReportDetectedError(XV_SdiRxSs *InstancePtr)
Reports detected errors in the SDI Rx Subsystem.
This function examines the SDI Rx Subsystem instance and reports any detected errors that have occurred during SDI reception operations. The function can be used for debugging and error handling purposes. InstancePtr Pointer to the XV_SdiRxSs instance to be operated on. The caller must ensure that InstancePtr is a valid pointer to an initialized XV_SdiRxSs instance before calling this function.
References XV_SdiRxSs::SdiRxPtr.
void XV_SdiRxSs_SetYCbCr444_RGB_10bit(XV_SdiRxSs *InstancePtr)
This function enable the YUV444/RGB 10bit support SDI RX SS video stream.
InstancePtr pointer to XV_SdiRxSs instance
References XV_SdiRxSs::SdiRxPtr.
void XV_SdiRxSs_ClearYCbCr444_RGB_10bit(XV_SdiRxSs *InstancePtr)
This function disable the YUV444/RGB 10bit support SDI RX SS video stream.
InstancePtr pointer to XV_SdiRxSs instance
References XV_SdiRxSs::SdiRxPtr.
int XV_SdiRxSs_SetCallback(XV_SdiRxSs *InstancePtr, u32 HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function Type ----------------------- --------------------------------------------- (XV_SDIRXSS_HANDLER_STREAM_DOWN) StreamDownCallback (XV_SDIRXSS_HANDLER_STREAM_UP) StreamUpCallback (XV_SDIRXSS_HANDLER_OVERFLOW) OverFlowCallback (XV_SDIRXSS_HANDLER_UNDERFLOW) UnderFlowCallback (XV_SDIRXSS_HANDLER_VSYNC) VsyncCallback InstancePtr is a pointer to the SDI RX Subsystem instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XV_SdiRxSs::OverFlowCallback, XV_SdiRxSs::OverFlowRef, XV_SdiRxSs::StreamDownCallback, XV_SdiRxSs::StreamDownRef, XV_SdiRxSs::StreamUpCallback, XV_SdiRxSs::StreamUpRef, XV_SdiRxSs::UnderFlowCallback, XV_SdiRxSs::UnderFlowRef, XV_SdiRxSs::VsyncCallback, XV_SdiRxSs::VsyncRef, XV_SDIRXSS_HANDLER_OVERFLOW, XV_SDIRXSS_HANDLER_STREAM_DOWN, XV_SDIRXSS_HANDLER_STREAM_UP, XV_SDIRXSS_HANDLER_UNDERFLOW, XV_SDIRXSS_HANDLER_VSYNC.
void XV_SdiRxSs_ReportCoreInfo(XV_SdiRxSs *InstancePtr)
This function reports list of cores included in Video Processing Subsystem.
InstancePtr is a pointer to the Subsystem instance. None.
References XV_SdiRxSs::SdiRxPtr.
Referenced by XV_SdiRxSs_ReportInfo.
void XV_SdiRxSs_ReportInfo(XV_SdiRxSs *InstancePtr)
This function prints the SDI RX SS information.
InstancePtr pointer to XV_SdiRxSs instance None.
References XV_SdiRxSs::SdiRxPtr, XV_SdiRxSs_ReportCoreInfo.
void XV_SdiRxSs_ReportDebugInfo(XV_SdiRxSs *InstancePtr)
This function prints the SDI RX SS debug information.
InstancePtr pointer to XV_SdiRxSs instance None.
References XV_SdiRxSs::SdiRxPtr.
u32* XV_SdiRxSs_GetPayloadId(XV_SdiRxSs *InstancePtr, u8 StreamId)
Retrieves the payload ID for a specified stream in the SDI Rx subsystem.
This function returns the payload identifier associated with the given stream in the SDI Receiver subsystem instance. InstancePtr Pointer to the XV_SdiRxSs instance to be worked on. StreamId The stream identifier for which the payload ID is to be retrieved. Pointer to u32 containing the payload ID for the specified stream. Returns NULL if the InstancePtr is invalid or StreamId is out of range. The caller must ensure that InstancePtr is a valid and initialized XV_SdiRxSs instance before calling this function.
References XV_SdiRxSs::SdiRxPtr.
u32 XV_SdiRxSs_WaitforPayLoad(XV_SdiRxSs *InstancePtr)
This function is used to wait for the payload valid bit to be set.
This has to be called from application based on the callback indication of the video lock interrupt handler. InstancePtr pointer to XV_SdiRxSs instance XST_FAILURE if the payload valid bits are not set.XST_SUCCESS if ST352 registers are read and loaded to Rx structures None.
References XV_SdiRxSs::SdiRxPtr.
XSdiVid_Transport* XV_SdiRxSs_GetTransport(XV_SdiRxSs *InstancePtr)
Gets the Transport information from the SDI Rx subsystem.
InstancePtr Pointer to the XV_SdiRxSs instance. Pointer to the XSdiVid_Transport structure containing transport information.
References XV_SdiRxSs::SdiRxPtr.
XVidC_VideoStream* XV_SdiRxSs_GetVideoStream(XV_SdiRxSs *InstancePtr, u8 StreamId)
This function returns the pointer to SDI RX SS video stream.
InstancePtr pointer to XV_SdiRxSs instance StreamId specifies which video stream's pointer to be returned XVidC_VideoStream pointer None.
References XV_SdiRxSs::SdiRxPtr.
XSdiVid_TransMode XV_SdiRxSs_GetTransportMode(XV_SdiRxSs *InstancePtr)
Gets the transport mode of the SDI receiver subsystem.
This function retrieves the current transport mode configuration of the SDI (Serial Digital Interface) receiver subsystem instance. InstancePtr Pointer to the XV_SdiRxSs instance to query. Must not be NULL. XSdiVid_TransMode The current transport mode of the SDI receiver. Returns the transport mode enumeration value indicating the data transport configuration. The InstancePtr must point to a valid and initialized XV_SdiRxSs instance.
References XV_SdiRxSs::Config, XV_SdiRxSs::SdiRxPtr.
u8 XV_SdiRxSs_GetTransportBitRate(XV_SdiRxSs *InstancePtr)
Gets the transport bit rate information from the SDI Rx subsystem.
This function retrieves the transport bit rate information of the SDI (Serial Digital Interface) receiver subsystem instance. It indicates whether the transport is operating in fractional mode or not. InstancePtr Pointer to the XV_SdiRxSs instance to query. Must not be NULL. u8 Returns 1 if the transport is operating in fractional mode, otherwise returns 0. The InstancePtr must point to a valid and initialized XV_SdiRxSs instance.
References XV_SdiRxSs::SdiRxPtr.
int XV_SdiRxSs_IsStreamUp(XV_SdiRxSs *InstancePtr)
This function checks if the video stream is up.
InstancePtr pointer to XV_SdiRxSs instance TRUE if stream is up.FALSE if stream is down. None.
References XV_SdiRxSs::IsStreamUp.
void XV_SdiRxSs_IntrEnable(XV_SdiRxSs *InstancePtr, u32 IntrMask)
This function is used to configure the SDI RX interrupts that are to be handled by the application.
Refer to xv_sdirxss_hw.h for interrupt masks. InstancePtr pointer to XV_SdiRxSs instance IntrMask Indicates Mask for enable interrupts. None.
References XV_SdiRxSs::SdiRxPtr, XV_SDIRXSS_IER_ALLINTR_MASK.
void XV_SdiRxSs_IntrDisable(XV_SdiRxSs *InstancePtr, u32 IntrMask)
This function is used to configure the SDI RX interrupts that are to be handled by the application.
Refer to xv_sdirxss_hw.h for interrupt masks. InstancePtr pointer to XV_SdiRxSs instance IntrMask Indicates Mask for disabling interrupts. None.
References XV_SdiRxSs::SdiRxPtr, XV_SDIRXSS_IER_ALLINTR_MASK.
u32 XV_SdiRxSs_SelfTest(XV_SdiRxSs *InstancePtr)
This function performs self test on SDI Rx Subsystem sub-cores.
InstancePtr is a pointer to the XV_SdiRxSs core instance. XST_SUCCESS if self test passed.XST_FAILURE if self test failed. None.
References XV_SdiRxSs::SdiRxPtr.
Referenced by SdiRxSs_SelfTestExample.
void XV_SdiRxSs_LogReset(XV_SdiRxSs *InstancePtr)
This function will reset the driver's logging mechanism.
InstancePtr is a pointer to the xv_sdirxss core instance. None.
References XV_SdiRxSs_Log::HeadIndex, XV_SdiRxSs::Log, XV_SdiRxSs_Log::TailIndex.
void XV_SdiRxSs_LogWrite(XV_SdiRxSs *InstancePtr, XV_SdiRxSs_LogEvent Evt, u8 Data)
This function will insert an event in the driver's logging mechanism.
InstancePtr is a pointer to the XV_SdiRxSs core instance. Evt is the event type to log. Data is the associated data for the event. None.
References XV_SdiRxSs_Log::DataBuffer, XV_SdiRxSs_Log::HeadIndex, XV_SdiRxSs::Log, XV_SdiRxSs_Log::TailIndex, XV_SDIRXSS_LOG_EVT_DUMMY.
Referenced by XV_SdiRxSs_Start, XV_SdiRxSs_Stop, XV_SdiRxSs_SubcoreInitSdiRx.
u16 XV_SdiRxSs_LogRead(XV_SdiRxSs *InstancePtr)
This function will read the last event from the log.
InstancePtr is a pointer to the XV_SdiRxSs core instance. The log data. None.
References XV_SdiRxSs_Log::DataBuffer, XV_SdiRxSs_Log::HeadIndex, XV_SdiRxSs::Log, XV_SdiRxSs_Log::TailIndex.
Referenced by XV_SdiRxSs_LogDisplay.
void XV_SdiRxSs_LogDisplay(XV_SdiRxSs *InstancePtr)
This function will print the entire log.
InstancePtr is a pointer to the XV_SdiRxSs core instance. None.
References XV_SDIRXSS_LOG_EVT_NONE, XV_SDIRXSS_LOG_EVT_OVERFLOW, XV_SDIRXSS_LOG_EVT_RESET, XV_SDIRXSS_LOG_EVT_SDIRX_INIT, XV_SDIRXSS_LOG_EVT_SETSTREAM, XV_SDIRXSS_LOG_EVT_START, XV_SDIRXSS_LOG_EVT_STOP, XV_SDIRXSS_LOG_EVT_STREAMDOWN, XV_SDIRXSS_LOG_EVT_STREAMSTART, XV_SDIRXSS_LOG_EVT_STREAMUP, XV_SDIRXSS_LOG_EVT_UNDERFLOW, XV_SdiRxSs_LogRead.
void XV_SdiRxSs_HandleNoPayload(XV_SdiRxSs *InstancePtr, u8 enable)
This function disables handling for no payload case.
InstancePtr is a pointer to the XV_SdiRxSs core instance. enable is to enable/disable the Handling of nopayload case
References XV_SdiRxSs::SdiRxPtr.