xv_sdirxss_log.c
void XV_SdiRxSs_LogReset(XV_SdiRxSs *InstancePtr)
This function will reset the driver's logging mechanism.
InstancePtr is a pointer to the xv_sdirxss core instance. None.
References XV_SdiRxSs_Log::HeadIndex, XV_SdiRxSs::Log, XV_SdiRxSs_Log::TailIndex.
void XV_SdiRxSs_LogWrite(XV_SdiRxSs *InstancePtr, XV_SdiRxSs_LogEvent Evt, u8 Data)
This function will insert an event in the driver's logging mechanism.
InstancePtr is a pointer to the XV_SdiRxSs core instance. Evt is the event type to log. Data is the associated data for the event. None.
References XV_SdiRxSs_Log::DataBuffer, XV_SdiRxSs_Log::HeadIndex, XV_SdiRxSs::Log, XV_SdiRxSs_Log::TailIndex, XV_SDIRXSS_LOG_EVT_DUMMY.
Referenced by XV_SdiRxSs_Start, XV_SdiRxSs_Stop, XV_SdiRxSs_SubcoreInitSdiRx.
u16 XV_SdiRxSs_LogRead(XV_SdiRxSs *InstancePtr)
This function will read the last event from the log.
InstancePtr is a pointer to the XV_SdiRxSs core instance. The log data. None.
References XV_SdiRxSs_Log::DataBuffer, XV_SdiRxSs_Log::HeadIndex, XV_SdiRxSs::Log, XV_SdiRxSs_Log::TailIndex.
Referenced by XV_SdiRxSs_LogDisplay.
void XV_SdiRxSs_LogDisplay(XV_SdiRxSs *InstancePtr)
This function will print the entire log.
InstancePtr is a pointer to the XV_SdiRxSs core instance. None.
References XV_SDIRXSS_LOG_EVT_NONE, XV_SDIRXSS_LOG_EVT_OVERFLOW, XV_SDIRXSS_LOG_EVT_RESET, XV_SDIRXSS_LOG_EVT_SDIRX_INIT, XV_SDIRXSS_LOG_EVT_SETSTREAM, XV_SDIRXSS_LOG_EVT_START, XV_SDIRXSS_LOG_EVT_STOP, XV_SDIRXSS_LOG_EVT_STREAMDOWN, XV_SDIRXSS_LOG_EVT_STREAMSTART, XV_SDIRXSS_LOG_EVT_STREAMUP, XV_SDIRXSS_LOG_EVT_UNDERFLOW, XV_SdiRxSs_LogRead.