dppt.h
UART_BASEADDR
TIMER_BASEADDR
VIDPHY_BASEADDR
CLK_2_GPIO_BASEADDR
XINTC_DPTXSS_DP_INTERRUPT_ID
XINTC_DPRXSS_DP_INTERRUPT_ID
XINTC_DPRXSS_IIC_INTERRUPT_ID
XDPRXSS_DEVICE_ID
XINTC_DEVICE_ID
XDPTXSS_DEVICE_ID
IIC_DEVICE_ID
XINTC_TIMER_0
XINTC_HDCP_TIMER_ID
XINTC_IIC_ID
TIMER_RESET_VALUE
TIMER_HDCP_STABLIZATION_VALUE
CLK_WIZ_BASE
XPAR_VIDEO_FRAME_CRC_TX_BASEADDR
XPAR_VIDEO_FRAME_CRC_RX_BASEADDR
XPAR_AV_PAT_GEN_0_BASEADDR
GPIO_CLK_BASEADDR
HLS_RESET
ENABLE_HDCP_IN_DESIGN
ENABLE_HDCP_FLOW_GUIDE
FOR_INTERNAL
JUST_RX
COMPLIANCE
CAP_OVER_RIDE
MAX_RATE
MAX_LANE
PE_VS_ADJUST
DP141_ADJUST
ENABLE_AUDIO
DEBUG_MAIN_FLOW
EEPROM_TEST_START_ADDRESS
IIC_SI570_ADDRESS
IIC_SWITCH_ADDRESS
PAGE_SIZE
NUM_MODES
NUM_CLOCK_REGS
PROG_48_KHZ_MODE
SET_TX_TO_2BYTE
SET_RX_TO_2BYTE
BUFFER_BYPASS
XDP_RX_CRC_CONFIG
XDP_RX_DPC_LINK_QUAL_CONFIG
XDP_RX_DPC_L01_PRBS_CNTR
XDP_RX_DPC_L23_PRBS_CNTR
XDP_RX_DPCD_LINK_QUAL_PRBS
XVPHY_DRP_GTHE4_PRBS_ERR_CNTR_LOWER
XVPHY_DRP_GTHE4_PRBS_ERR_CNTR_UPPER
AccessErrorCounterHandler_FLAG
typedef unsigned int UINT32
user_config_struct user_config
int DPPtIntrInitialize()
int DpPt_SetupIntrSystem()
This function is sets up Interrupt system and start it.
None.
References XDpTxSs::Config, XDpTxSs_DpIntrHandler.
void DpPt_HpdEventHandler(void *InstancePtr)
This function takes care HPD event.
None. None.
References XDpTxSs::DpPtr, sink_power_down, sink_power_up, XDpTxSs_IsConnected.
Referenced by DpTxSs_SetupIntrSystem.
void DpPt_HpdPulseHandler(void *InstancePtr)
This function takes care HPD pulse interrupt.
None. None.
References XDpTxSs::DpPtr.
Referenced by DpTxSs_SetupIntrSystem.
void DpPt_LinkrateChgHandler(void *InstancePtr)
This function sets link line rate.
@return None. None.
References get_LineRate, set_vphy.
Referenced by DpTxSs_SetupIntrSystem.
void DpPt_pe_vs_adjustHandler(void *InstancePtr)
void DpPt_TxSetMsaValuesImmediate(void *InstancePtr)
void Dprx_InterruptHandlerPllReset(void *InstancePtr)
void Dprx_InterruptHandlerLinkBW(void *InstancePtr)
void Dprx_InterruptHandlerTrainingDone(void *InstancePtr)
void Dprx_InterruptHandlerBwChange(void *InstancePtr)
void Dprx_InterruptHandlerInfoPkt(void *InstancePtr)
void Dprx_InterruptHandlerExtPkt(void *InstancePtr)
void Dprx_InterruptHandlerUplug(void *InstancePtr)
void Dprx_InterruptHandlerPwr(void *InstancePtr)
u8 get_LineRate(void)
This function returns current line rate.
None. None. None.
References XDpTxSs::DpPtr.
void DpRxSs_AccessLaneSetHandler(void *InstancePtr)
This function is the callback function for Access lane set request.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_AccessLinkQualHandler(void *InstancePtr)
This function is the callback function for Access link qual request.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_AccessErrorCounterHandler(void *InstancePtr)
This function is the callback function for Access prbs error count.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_CRCTestEventHandler(void *InstancePtr)
This function is the callback function for Test CRC Event request.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_InfoPacketHandler(void *InstancePtr)
This function is the callback function for Info Packet Handling.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_ExtPacketHandler(void *InstancePtr)
This function is the callback function for Generic Packet Handling of 32-Bytes payload.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void Dprx_HdcpAuthCallback(void *InstancePtr)
void Dprx_HdcpUnAuthCallback(void *InstancePtr)
void DpPt_CustomWaitUs(void *InstancePtr, u32 MicroSeconds)
This function use h/w timer to count specific Microseconds.
pointer to timer MicroSeconds to wait None. None. This function use h/w timer to count specific Microseconds.It provides timer with predefined amount of loop iterations. InstancePtr is a pointer to the XDp instance. None. Use the XDpTxSs_SetUserTimerHandler driver function to set this function as the handler custom delay/sleep.
Referenced by DpTxSs_SetupIntrSystem, reconfig_clkwiz, sink_power_cycle, start_tx.
int DPTxInitialize()
int DPRxInitialize()
int init_peripherals()
void hpd_con()
This function is called when a Hot-Plug-Detect (HPD) event is received by the DisplayPort TX Subsystem core.
InstancePtr is a pointer to the XDpTxSs instance. None. Use the XDpTxSs_SetCallback driver function to set this function as the handler for HPD event.
References XDpTxSs::DpPtr, update_edid, XDpTxSs_SetLaneCount, XDpTxSs_SetLinkRate.
void hpd_pulse_con()
This function is called when a Hot-Plug-Detect (HPD) pulse is received by the DisplayPort TX Subsystem core.
InstancePtr is a pointer to the XDpTxSs instance. None. Use the XDpTxSs_SetCallback driver function to set this function as the handler for HPD pulse.
References XDpTxSs::DpPtr, XDpTxSs_SetLaneCount, XDpTxSs_SetLinkRate.
void start_tx(u8 line_rate, u8 lane_count, XVidC_VideoMode res_table, u8 bpc, u8 pat, u8 pat_update)
This is for Tx only mode This function will start outputting internal video pattern image Setup GT, DP, pattern and generator.
line_rate Link rate setting for the DisplayPort transmission lane_count Number of lanes to use for transmission res_table Video resolution mode from the resolution table bpc Bits per color component (e.g., 8, 10, 12) pat Pattern type identifier (unused parameter) pat_update Pattern update flag to select video pattern This function configures the DisplayPort TX subsystem with the specified parameters, trains the link, and starts video output with the selected internal pattern generator settings.
References clk_wiz_locked, DpPt_CustomWaitUs, XDpTxSs::DpPtr, XDpTxSs_UsrOpt::NumOfStreams, sink_power_cycle, XDpTxSs::UsrOpt, Vpg_StreamSrcConfigure, Vpg_VidgenSetUserPattern, XDpTxSs_UsrOpt::VtcAdjustBs, XDpTxSs::VtcPtr, XDpTxSs_CheckLinkStatus, XDpTxSs_SetBpc, XDpTxSs_SetLaneCount, XDpTxSs_SetLinkRate, XDpTxSs_SetVidMode, XDpTxSs_VtcSetup.
void prog_bb(u8 bw, u8 is_tx)
void vdma_stop()
void vdma_start()
void phy_cmpl(char CommandKey)
u32 DpTxSubsystem_Start(XDpTxSs *, int)
char GetInbyte(void)
static char inbyte_local(void)
void Dprx_SetupTxWithCustomMsa(void *InstancePtr, u8 tx_with_msa)
void Dprx_SetupTx(void *InstancePtr, u8 tx_with_msa, XVidC_VideoMode VmId)
void app_help()
void bpc_help_menu()
void reset_clkwiz()
This function will reset Tx side MMCM.
None
void clk_wiz_locked()
This function to check MMCM lock status.
None. None. None. This function to check MMCM lock status.None
Referenced by start_tx.
void reconfig_clkwiz()
void resolution_help_menu()
void rx_help_menu()
void select_link_lane()
void select_rx_link_lane()
void sub_help_menu()
void test_pattern_gen_help()
void format_help_menu(void)
int i2c_write_dp141(u32 I2CBaseAddress, u8 I2CSlaveAddress, u16 RegisterAddress, u8 Value)
u8 i2c_read_dp141(u32 I2CBaseAddress, u8 I2CSlaveAddress, u16 RegisterAddress)
This function reads DP141 VFMC- IIC.
None. None. None.
void DP141_init(u32 I2CBaseAddress, u8 I2CSlaveAddress)
void edid_change(int page)
void edid_default()
int VideoFMC_Init(void)
This function will detect video resolution/frequency change Many GPUs won't re-train when only video res/freq change.
Application needs to know if it changed and need to detect new parameter. Based on the parameter, re-set and re-start VDAM and TxNone This function will detect video resolution/frequency change Many GPUs won't re-train when only video res/freq change. None. None. None. Application needs to know if it changed and need to detect new parameter. Based on the parameter, re-set and re-start VDAM and TxNone This function will detect video resolution/frequency change Many GPUs won't re-train when only video res/freq change. None. None. None.
References I2C_IDT8N49_ADDR, I2C_LMK03318_ADDR, I2C_MUX_ADDR, I2C_VFMCEXP_0_ADDR, I2C_VFMCEXP_1_ADDR, IDT_8T49N24x_Init, TI_LMK03318_PowerDown.
int write_si570()
void I2C_Scan(u32 BaseAddress)
This function scans VFMC- IIC.
None. None. None.
Referenced by VideoFMC_Init.
void select_rx_quad()
void read_DP141()
void video_change_detect(u32 *count_track, u32 *rxMsamisc0_track, u32 *bpc_track, u32 *recv_clk_freq_track, float *recv_frame_clk_track, u32 *recv_frame_clk_int_track, int *track_count)
This function will detect video resolution/frequency change Many GPUs won't re-train when only video res/freq change.
Application needs to know if it changed and need to detect new parameter. Based on the parameter, re-set and re-start VDAM and TxNone
References XDpTxSs::DpPtr, Vpg_VidgenSetUserPattern, XDpTxSs_Stop.
void detect_rx_video_and_startTx(int *track_count1)
This function detects incoming video and find out video parameters Based on the parameters, set up Tx and VDMA, then start Tx output.
None
References XDpTxSs::DpPtr, Vpg_StreamSrcConfigure, Vpg_VidgenSetUserPattern, XDpTxSs_Reset, XDpTxSs_Stop.
void switch_to_Tx_only(int *track_switch, u8 *pwr_dwn_x)
This function will be used when no incoming video at pass-through mode If no video, switching to internal pattern generator.
None
References XDpTxSs::DpPtr, PHY_Configuration_Tx, sink_power_cycle, start_tx, Vpg_StreamSrcConfigure, Vpg_VidgenSetUserPattern, XDpTxSs_Reset, XDpTxSs_Stop.
void start_audio_passThrough()
void sink_power_cycle(u32 power_down_time)
This function will send power down and power up command over AUX.
None
References DpPt_CustomWaitUs, XDpTxSs::DpPtr.
void Vpg_Audio_start(void)
This function starts audio pattern generator.
None. None.
void Vpg_Audio_stop()
This function stops audio pattern generator.
None. None.
void power_down_HLSIPs(void)
void power_up_HLSIPs(void)
void remap_start(struct dma_chan_parms *dma_struct)
void resetIp()
This function toggles HW reset line for all IP's.
None
void update_edid()
This function will update and overwrite EDID color depth 10BPC will be changed to 8BPC due to design limitation.
None
Referenced by hpd_con.
void Print_InfoPkt()
This function is the callback function for Info Packet Handling.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void Print_ExtPkt()
This function is the callback function for Ext Packet Handling.
InstancePtr is a pointer to the XDpRxSs instance. None. None.