xdptxss_sinit.c
XDpTxSs_Config XDpTxSs_ConfigTable[XPAR_XDPTXSS_NUM_INSTANCES][XPAR_XDPTXSS_NUM_INSTANCES]
XDpTxSs_Config * XDpTxSs_LookupConfig(UINTPTR BaseAddress)
This function returns a reference to an XDptxss_Config structure based on the core id, DeviceId.
The return value will refer to an entry in the device configuration table defined in the xdptxss_g.c file. DeviceId is the unique core ID of the XDpTxSs core for the lookup operation. XDptxss_LookupConfig returns a reference to a config record in the configuration table (in xdptxss_g.c) corresponding to DeviceId, or NULL if no match is found. None.
Referenced by DpTxSs_DebugExample, DpTxSs_HdcpExample, DpTxSs_IntrExample, DpTxSs_MstExample, DpTxSs_SelfTestExample.
u32 XDpTxSs_GetDrvIndex(UINTPTR BaseAddress)
This function returns the Index number of config table using BaseAddress.
Base address of the instance Index number of the config table