xdptxss_intr.c
void XDpTxSs_DpIntrHandler(void *InstancePtr)
This function is the interrupt handler for the DisplayPort TX core operating in TX mode.
The application is responsible for connecting this function to the interrupt system. Application beyond this driver is also responsible for providing callbacks to handle interrupts and installing the callbacks using XDpTxSs_SetCallBack() during initialization phase. InstancePtr is a pointer to the XDpTxSs core instance that just interrupted. None.
References XDpTxSs::DpPtr, XDpTxSs::IsReady.
Referenced by DpPt_SetupIntrSystem, DpTxSs_SetupIntrSystem.
void XDpTxSs_HpdEventProcess(void *InstancePtr)
This function is process some DP driver read as per DP spec on HPD EVENT.
InstancePtr is a pointer to the XDpTxSs core instance that just interrupted. None.
References XDpTxSs::DpPtr, XDpTxSs::IsReady, XDpTxSs::UsrHpdEventData.
Referenced by XDpTxSs_CfgInitialize.
void XDpTxSs_HpdPulseProcess(void *InstancePtr)
This function is process some DP driver read as per DP spec on HPD Pulse.
InstancePtr is a pointer to the XDpTxSs core instance that just interrupted. None.
References XDpTxSs::DpPtr, XDpTxSs::IsReady, XDpTxSs::UsrHpdPulseData.
Referenced by XDpTxSs_CfgInitialize.
void XDpTxSs_WriteVscExtPktProcess(void *InstancePtr)
This function writes the pixel encoding format and colorimetry formats in to the extended packet registers at DP TX offset addresses "0x0330 to 0x0350".
InstancePtr is a pointer to the XDpTxSs core instance that just interrupted. None.
References XDpTxSs::DpPtr.
Referenced by XDpTxSs_CfgInitialize.
u32 XDpTxSs_SetCallBack(XDpTxSs *InstancePtr, u32 HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function HandlerType ---------------------------------------- ------------------------------------ (XDPTXSS_HANDLER_DP_HPD_EVENT) XDP_TX_HANDLER_HPDEVENT (XDPTXSS_HANDLER_DP_HPD_PULSE) XDP_TX_HANDLER_HPDPULSE (XDPTXSS_HANDLER_DP_LANE_COUNT_CHG) XDP_TX_HANDLER_LANECNTCHANGE (XDPTXSS_HANDLER_DP_LINK_RATE_CHG) XDP_TX_HANDLER_LINKRATECHANGE (XDPTXSS_HANDLER_DP_PE_VS_ADJUST) XDP_TX_HANDLER_PEVSADJUST (XDPTXSS_HANDLER_DP_EXT_PKT_EVENT) XDP_TX_HANDLER_EXTPKT_TXD (XDPTXSS_DRV_HANDLER_DP_EXT_PKT_EVENT) XDP_TX_HANDLER_DRV_EXTPKT_TXD (XDPTXSS_HANDLER_DP_VSYNC) XDP_TX_HANDLER_VSYNC (XDPTXSS_HANDLER_HDCP_RPTR_EXCHG) XHdcp1x_SetCallBack (XDPTXSS_HANDLER_DP_SET_MSA) XDP_TX_HANDLER_SETMSA InstancePtr is a pointer to the XDpTxSs core instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XDpTxSs::DpPtr, XDpTxSs::IsReady, XDPTXSS_DRV_HANDLER_DP_EXT_PKT_EVENT, XDPTXSS_DRV_HANDLER_DP_HPD_EVENT, XDPTXSS_DRV_HANDLER_DP_HPD_PULSE, XDPTXSS_HANDLER_DP_EXT_PKT_EVENT, XDPTXSS_HANDLER_DP_HPD_EVENT, XDPTXSS_HANDLER_DP_HPD_PULSE, XDPTXSS_HANDLER_DP_LANE_COUNT_CHG, XDPTXSS_HANDLER_DP_LINK_RATE_CHG, XDPTXSS_HANDLER_DP_PE_VS_ADJUST, XDPTXSS_HANDLER_DP_SET_MSA, XDPTXSS_HANDLER_DP_VSYNC.
Referenced by DpTxSs_SetupIntrSystem, XDpTxSs_CfgInitialize.
void XDpTxSs_SetUserTimerHandler(XDpTxSs *InstancePtr, XDpTxSs_TimerHandler CallbackFunc, void *CallbackRef)
This function installs a custom delay/sleep function to be used by the DisplayPort TX Subsystem.
InstancePtr is a pointer to the XDpTxSs instance. CallbackFunc is the address to the callback function. CallbackRef is the user data item (microseconds to delay) that will be passed to the custom sleep/delay function when it is invoked. None.
References XDpTxSs::DpPtr.
Referenced by DpTxSs_SetupIntrSystem.