xdptxss_dbg.c
void XDpTxSs_ReportSinkCapInfo(XDpTxSs *InstancePtr)
This function prints the capabilities of the DisplayPort sink.
InstancePtr is a pointer to the XDpTxSs core instance. None.
References XDpTxSs::DpPtr.
Referenced by DpTxSs_DebugExample.
void XDpTxSs_ReportCoreInfo(XDpTxSs *InstancePtr)
This function reports list of sub-cores included in DisplayPort TX Subsystem.
InstancePtr is a pointer to the XDpTxSs core instance. None.
References XDpTxSs::Config, XDpTxSs::DpPtr, XDpTxSs_Config::HdcpEnable, XDpTxSs_Config::MaxBpc, XDpTxSs_Config::MaxLaneCount, XDpTxSs_UsrOpt::MstSupport, XDpTxSs_Config::MstSupport, XDpTxSs_Config::NumMstStreams, XDpTxSs_Config::SecondaryChEn, XDpTxSs::UsrOpt, XDpTxSs::VtcPtr.
Referenced by DpTxSs_DebugExample.
void XDpTxSs_ReportSplitterInfo(XDpTxSs *InstancePtr)
This function prints the current Dual Splitter information.
InstancePtr is a pointer to the XDpTxSs core instance. None.
Referenced by DpTxSs_DebugExample.
void XDpTxSs_ReportVtcInfo(XDpTxSs *InstancePtr)
This function prints the current VTC timing information.
InstancePtr is a pointer to the XDpTxSs core instance. None.
References XDpTxSs::Config, XDpTxSs_Config::NumMstStreams, XDpTxSs::VtcPtr.
Referenced by DpTxSs_DebugExample.
void XDpTxSs_ReportLinkInfo(XDpTxSs *InstancePtr)
This function prints the link status, selected resolution, bits per color and link/lane count symbol error.
InstancePtr is a pointer to the XDpTxSs core instance. None.
References XDpTxSs_UsrOpt::Bpc, XDpTxSs::DpPtr, XDpTxSs::UsrOpt, XDpTxSs_UsrOpt::VmId.
Referenced by DpTxSs_DebugExample.
void XDpTxSs_ReportMsaInfo(XDpTxSs *InstancePtr)
This function prints the current main stream attributes from the DisplayPort TX core.
InstancePtr is a pointer to the XDpTxSs core instance. None.
References XDpTxSs::Config, XDpTxSs::DpPtr, XDpTxSs_Config::NumMstStreams.
Referenced by DpTxSs_DebugExample.
void XDpTxSs_ReportHdcpInfo(XDpTxSs *InstancePtr)
This function prints the debug display info of the HDCP interface.
InstancePtr is a pointer to the XDpTxSs core instance. None.
Referenced by DpTxSs_DebugExample.