xdptxss_dptx.c
XDP_TX_SB_MSG_DELAY
static u32 Dp_GetTopology(XDp *InstancePtr)
This function discovers the topology and finds the actual number of sinks.
It enables streams corresponding to each sink found during topology discovery. InstancePtr is a pointer to the XDp instance. XST_SUCCESS if topology discovered successfully.XST_FAILURE if topology discovery failed. None.
static u32 Dp_CheckBandwidth(XDp *InstancePtr, u8 Bpc, XVidC_VideoMode VidMode)
This function calculates the video bandwidth and link bandwidth in single stream and millstream mode.
It checks whether the link bandwidth is not over-subscribed for video bandwidth. InstancePtr is a pointer to the XDp instance. Bpc is the new number of bits per color to use. VidMode is one of the enumerated standard video modes defined in xvidc.h file. XST_SUCCESS if link bandwidth is not over-subscribed.XST_FAILURE otherwise. Check that the stream allocation will succeed based on capabilities. Don't go through training and allocation sequence if the pre-calculations indicate that it will fail
static XVidC_VideoMode Dp_GetPreferredVm(u8 *EdidPtr)
This function retrieves preferred timing mode information from the EDID to identify video mode or resolution.
EdidPtr is the supplied base EDID to retrieve timing values. Id of a supported video mode. None.
static void Dp_ConfigVideoPackingClockControl(XDp *InstancePtr, u8 Bpc)
This function configures DisplayPort video packaging clock control bit ( VIDEO_PACKING_CLOCK_CONTROL) if bpc is 12/16.
InstancePtr is a pointer to the XDp instance. Bpc is the new number of bits per color to use. None.
u32 XDpTxSs_DpTxStart(XDp *InstancePtr, u8 TransportMode, u8 Bpc, XVidC_VideoMode VidMode)
This function configures DisplayPort sub-core with preferred resolution read from sink or user set resolution, bits per color in SST/MST mode.
In MST mode, if sinks are more than two, it re-orders the sinks if belongs to same tiled display topology. It trains the link and allocates stream payloads for single stream (SST) or multi-stream transport mode (MST). In MST mode, discovers the topology and finds the actual number of sinks to which associates streams. InstancePtr is a pointer to the XDp instance. TransportMode specifies whether multiple/single steam to be sent over the main link. TransportMode = 1 (for Multi-Stream Transport)TransportMode = 0 (for Single Stream Transport) Bpc is the new number of bits per color to use. VidMode is one of the enumerated standard video modes defined in xvidc.h file. XST_SUCCESS DisplayPort configured successfully.XST_FAILURE if DisplayPort configuration failed. None.
References XDPTXSS_DPTX_MST, XDPTXSS_DPTX_SST, XDpTxSs_DpTxStartLink.
Referenced by XDpTxSs_Start, XDpTxSs_StartCustomMsa.
u32 XDpTxSs_DpTxStartLink(XDp *InstancePtr, u8 TrainMaxCap)
This function checks if the link needs training and runs the training sequence if training is required based on the flags, indicates to use maximum RX capabilities or user specified link rate, lane count during training.
InstancePtr is a pointer to the XDp instance. TrainMaxCap is a flag indicates whether maximum capabilities to be used during link training. TRUE - Use maximum RX capabilities.FALSE - Use custom capabilities. XST_SUCCESS the if main link was successfully established.XST_FAILURE otherwise. None.
Referenced by XDpTxSs_DpTxStart.