xdptxss_debug_example.c
DPTXSS_MST
DPTXSS_LINK_RATE
DPTXSS_LANE_COUNT
DPTXSS_VID_MODE
DPTXSS_BPC
FLOAT_FRAC_TO_U32
XDpTxSs DpTxSsInst
MODIFICATION HISTORY:Ver Who Date Changes 1.00 Nishant 19/12/20 Added support for vck190.Added ReadModifyWrite() for writing to vck190 register space.set_vphy() renamed to config_phy() and has two parameters for linerate and lanecount.
u32 DpTxSs_DebugExample(u32 BaseAddress)
This function is the main entry point for the debug example using the XDpTxSs driver.
This function will print values set during DisplayPort TX Subsystem set up to work in MST/SST based upon RX device capabilities. DeviceId is the unique device ID of the DisplayPort TX Subsystem core. XST_SUCCESS if DisplayPort TX Subsystem prints debug information successfully.XST_FAILURE, otherwise. None.
References XDpTxSs_Config::BaseAddress, DpTxSs_PlatformInit, DpTxSs_ReportEdidInfo, DpTxSs_StreamSrc, XDpTxSs_UsrOpt::MstSupport, XDpTxSs::UsrOpt, XDpTxSs_UsrOpt::VmId, XDpTxSs_CfgInitialize, XDpTxSs_GetRxCapabilities, XDpTxSs_IsMstCapable, XDpTxSs_LookupConfig, XDpTxSs_ReportCoreInfo, XDpTxSs_ReportHdcpInfo, XDpTxSs_ReportLinkInfo, XDpTxSs_ReportMsaInfo, XDpTxSs_ReportSinkCapInfo, XDpTxSs_ReportSplitterInfo, XDpTxSs_ReportVtcInfo, XDpTxSs_SetBpc, XDpTxSs_SetLaneCount, XDpTxSs_SetLinkRate, XDpTxSs_SetTransportMode, XDpTxSs_SetVidMode, XDpTxSs_Start.
Referenced by main.
u32 DpTxSs_PlatformInit(void)
This function initialize required platform-specifc peripherals.
None. XST_SUCCESS if required peripherals are initialized and configured successfully.XST_FAILURE, otherwise. None.
Referenced by DpTxSs_DebugExample, DpTxSs_HdcpExample, DpTxSs_IntrExample, DpTxSs_MstExample.
u32 DpTxSs_StreamSrc(u8 VerticalSplit)
This function setup stream source to input DisplayPort TX Subsystem.
VerticalSplit specifies whether to split video frame vertically into two different vertical halves. 1 = Vertically split input frame0 = No vertically split input frame. XST_SUCCESS if stream source is configured successfully.XST_FAILURE, otherwise. None.
Referenced by DpTxSs_DebugExample, DpTxSs_HdcpExample, DpTxSs_MstExample.
void DpTxSs_ReportEdidInfo(XDpTxSs *InstancePtr)
This function prints EDID info of RX device.
InstancePtr is a pointer to the XDpTxSs core instance. None. None.
References XDpTxSs::DpPtr, DpTxSs_EdidDecodeBase, DpTxSs_PrintEdid, XDpTxSs_UsrOpt::MstSupport, XDpTxSs::UsrOpt, XDpTxSs_GetEdid, XDpTxSs_GetRemoteEdid, XDPTXSS_INTERRUPT_MASK, XDPTXSS_INTERRUPT_MASK_HPD_EVENT_MASK, XDPTXSS_INTERRUPT_MASK_HPD_PULSE_DETECTED_MASK, XDpTxSs_ReadReg, XDpTxSs_WriteReg.
Referenced by DpTxSs_DebugExample.
u32 DpTxSs_EdidDecodeBase(u8 *EdidRaw)
This function decodes and prints EDID header and tag information.
EdidRaw is a pointer to u8 variable that will be used for parsing EDID blocks. XST_SUCCESS, if EDID blocks parsed successfully. None.
References DpTxSs_EdidBaseBasicDisp, DpTxSs_EdidBaseVerRev, DpTxSs_EdidBaseVPId, DpTxSs_EdidCalculateChecksum, DpTxSs_EdidColorChar, DpTxSs_EdidEstTimings, DpTxSs_EdidPtm, DpTxSs_EdidStdTimings.
Referenced by DpTxSs_ReportEdidInfo.
void DpTxSs_EdidBaseVPId(u8 *EdidRaw)
This function prints RX device identification data.
EdidRaw is a pointer to u8 variable that will be used for parsing EDID blocks. None. None.
Referenced by DpTxSs_EdidDecodeBase.
void DpTxSs_EdidBaseVerRev(u8 *EdidRaw)
This function prints structure version and revision of RX EDID.
EdidRaw is a pointer to u8 variable that will be used for parsing EDID blocks. None. None.
Referenced by DpTxSs_EdidDecodeBase.
void DpTxSs_EdidBaseBasicDisp(u8 *EdidRaw)
This function prints basic display information of RX device.
EdidRaw is a pointer to u8 variable that will be used for parsing EDID blocks. None. None.
Referenced by DpTxSs_EdidDecodeBase.
void DpTxSs_EdidColorChar(u8 *EdidRaw)
This function prints color characteristics of RX device.
EdidRaw is a pointer to u8 variable that will be used for parsing EDID blocks. None. None.
Referenced by DpTxSs_EdidDecodeBase.
void DpTxSs_EdidEstTimings(u8 *EdidRaw)
This function prints supported timings by the RX device.
EdidRaw is a pointer to u8 variable that will be used for parsing EDID blocks. None. None.
Referenced by DpTxSs_EdidDecodeBase.
void DpTxSs_EdidStdTimings(u8 *EdidRaw)
This function prints standard timings of RX device.
EdidRaw is a pointer to u8 variable that will be used for parsing EDID blocks. None. None.
Referenced by DpTxSs_EdidDecodeBase.
void DpTxSs_EdidPtm(u8 *EdidRaw)
This function prints preferred timing values of RX device.
EdidRaw is a pointer to u8 variable that will be used for parsing EDID blocks. None. None.
Referenced by DpTxSs_EdidDecodeBase.
u8 DpTxSs_EdidCalculateChecksum(u8 *Data, u8 Size)
This function calculates the EDID checksum.
Data is a pointer to u8 variable that will be used to retrieve data. Size specifies the number of bytes. Calculated checksum. None.
Referenced by DpTxSs_EdidDecodeBase.
void DpTxSs_PrintEdid(u8 *EdidRaw)
This function prints 128 byte content from EDID.
EdidRaw is a pointer to u8 variable that will be used for parsing EDID blocks. None. None.
Referenced by DpTxSs_ReportEdidInfo.
int main()
This is the main function for XDpTxSs SST/MST example.
None. XST_SUCCESS if the MST/SST example passed.XST_FAILURE if the MST/SST example was unsuccessful. None.
References DpTxSs_DebugExample.