xdptxss_zcu102_dp14_mst_pt.c
I2C_MUX_device_address
MODIFICATION HISTORY:Ver Who Date Changes 1.00 KU 02/05/19 Initial release. 1.01 KU 09/09/19 Added support for unplug, enhanced audio check 1.02 ND 02/14/19 mcdp related function call now need dprxss instance address instead of base address as first parameter 1.03 ND 09/11/20 Added support for New AV pattern generator 1.04 ND 02/12/21 Added case 'z' to display menu in PT mode. Added support to set the MSA values for the tx according to the selected stream to be displayed front the menu. Added the enabling of vblank interrupts for all streams in Dprx_InterruptHandlerActRx() handler. 1.05 ND 04/03/21 Moved all global variables declaration from .h to .c files due to gcc compiler compilation error. 1.06 ND 04/15/21 Added support for stream 2,3 and 4 handler interrupts 1.07 ND 02/25/22 Modified the code for de-asserting longer hpd for some gpu's to retrain our rx. 1.08 ND 07/18/22 Added support to the app for branch topology. Disabling the av pat gen before start of new training sequence. Updation of the LMK03318 address. 1.09 ND 08/26/22 Added DELAY macro to increase delay in IDT_8T49N24x_SetClock() if encountering iic race condition.
Si570_device_address
audio_clk_Hz
INTRNAME_DPTX
INTRNAME_DPRX
NUM_TEST_FORMATS
XVphy_User_Config PHY_User_Config_Table[][]
u8 rx_unplugged
u32 bpc
u8 comp
u32 dp_msa_hres
u32 dp_msa_vres
u32 DpHres_total
u32 DpVres_total
u8 LaneCount
u8 LineRate
u8 pixel
u32 recv_clk_see
u32 recv_clk_freq_track
float recv_frame_clk_track
u32 recv_frame_clk_int_track
u32 recv_frame_clk_int
u32 recv_clk_freq
float recv_frame_clk
u32 rxMsaMVid
u32 rxMsaNVid
u32 rxMsamisc0
XDpTxSs_MainStreamAttributes Msa[4][4]
u8 Bpc[][]
u32 XVFRMBUFRD_BUFFER_BASEADDR
u32 XVFRMBUFWR_BUFFER_BASEADDR
XilAudioInfoFrame_rx AudioinfoFrame
XilAudioExtFrame SdpExtFrame
XilAudioExtFrame SdpExtFrame_q
XV_FrmbufRd_l2 frmbufrd
XV_FrmbufWr_l2 frmbufwr
XAxis_Switch axis_switch
XAxis_Switch axis_switch_tx
XDpRxSs DpRxSsInst
XDpTxSs DpTxSsInst
MODIFICATION HISTORY:Ver Who Date Changes 1.00 Nishant 19/12/20 Added support for vck190.Added ReadModifyWrite() for writing to vck190 register space.set_vphy() renamed to config_phy() and has two parameters for linerate and lanecount.
XIic IicInstance
XIic_Config* ConfigPtr_IIC
XVphy VPhyInst
XTmrCtr TmrCtr
MODIFICATION HISTORY:Ver Who Date Changes - ----- -----------------------------------------------. 1.00 Nishant 19/12/19 Added support for vck190, VCU118 DpTxSs_VideoPhyInit() renamed to DpTxSs_PhyInit() set_vphy() renamed to config_phy() and has two parameters for linerate and lanecount. The application files are common for ZCU102, VCU118 and VCK190 TX Only design 1.01 KU 22/10/20 Added support for fabric 8b10b implementation of of DP1.4 1.02 ND 01/12/21 Added support for VSC in application menu. Changed options for Format menu. 1.03 ND 04/01/21 Moved all global variables declaration from .h to .c files due to gcc compiler compilation error. Setting tx_is_reconnected=0 and setting max_cap_new=XDP_TX_LINK_BW_SET_810GBPS in hpd_con for TX CTS test case. 1.04 KU 04/12/21 Updated Versal GT programming to get /20 clk 1.05 ND 05/07/21 Setting bit[12] of Reg 0x1A4 to 1 for VSC Colorimetry support 1.06 ND 07/21/22 Updated the LMK03318 address. 1.07 ND 08/11/22 Added support for gpio to monitor gtpowergood for versal GT 1.08 ND 08/26/22 Added DELAY macro to increase delay in IDT_8T49N24x_SetClock() if encountering iic race condition.
int tx_is_reconnected
u8 prev_line_rate
u8 hpd_pulse_con_event
u8 num_sinks
XScuGic IntcInst
XDpTxSs_Config* ConfigPtr
XDpRxSs_Config* ConfigPtr_rx
DP_Rx_Training_Algo_Config RxTrainConfig
u8 edid_rx[256][256]
This function initialize required platform-specifc peripherals.
None. XST_SUCCESS if required peripherals are initialized and configured successfully.XST_FAILURE, otherwise. None.
u32 appx_fs_dup
This function is the callback function for when a training lost interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
u8 rx_trained
u8 tx_is_up
This function takes care HPD event.
None. None.
u8 aud_info_rcvd
u32 rx_maud_dup
This function is the callback function for Info Packet Handling.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
u32 rx_naud_dup
u8 start_i2s_clk
u8 aud_started
u8 tx_ppc_set
u8 stream_id_used
u8 invalid_stream
VideoFormats ColorFormats[NUM_TEST_FORMATS][NUM_TEST_FORMATS]
u32 StreamOffsetAddr[4][4]
u32 DpMST_Main()
This function is the main entry point for the interrupt example using the XDpTxSs driver.
This function will set up the system with interrupts and set up Hot-Plug-Event (HPD) handlers. DeviceId is the unique device ID of the DisplayPort TX Subsystem core. XST_FAILURE if the system setup failed.XST_SUCCESS should never return since this function, if setup was successful, is blocking. If system setup was successful, this function is blocking in order to illustrate interrupt handling taking place for HPD events.
u32 DpMST_PlatformInit(void)
char XUartPs_RecvByte_NonBlocking()
This function is a non-blocking UART return byte.
None. None. None.
void DpRxSs_VmChangeEventHandler(void *InstancePtr)
This function is the callback function for when the Video mode change event interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_VmChange2EventHandler(void *InstancePtr)
This function is the callback function for when the Video mode change event interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_VmChange3EventHandler(void *InstancePtr)
This function is the callback function for when the Video mode change event interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_VmChange4EventHandler(void *InstancePtr)
This function is the callback function for when the Video mode change event interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_Video2Handler(void *InstancePtr)
This function is the callback function for when a valid video interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_Video3Handler(void *InstancePtr)
This function is the callback function for when a valid video interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_Video4Handler(void *InstancePtr)
This function is the callback function for when a valid video interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_InfoPacket2Handler(void *InstancePtr)
This function is the callback function for Info Packet Handling.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_InfoPacket3Handler(void *InstancePtr)
This function is the callback function for Info Packet Handling.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_InfoPacket4Handler(void *InstancePtr)
This function is the callback function for Info Packet Handling.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_ExtPacket2Handler(void *InstancePtr)
This function is the callback function for Generic Packet Handling of 32-Bytes payload.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_ExtPacket3Handler(void *InstancePtr)
This function is the callback function for Generic Packet Handling of 32-Bytes payload.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_ExtPacket4Handler(void *InstancePtr)
This function is the callback function for Generic Packet Handling of 32-Bytes payload.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_NoVideo2Handler(void *InstancePtr)
This function is the callback function for when a no video interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_NoVideo3Handler(void *InstancePtr)
This function is the callback function for when a no video interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_NoVideo4Handler(void *InstancePtr)
This function is the callback function for when a no video interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
int main()
This is the main function for XDpTxSs interrupt example.
If the DpTxSs_IntrExample function which sets up the system succeeds, this function will wait for the interrupts. Once a connection event or pulse is detected, DpTxSs will RX device capabilities and re-start the subsystem. None. XST_FAILURE if the interrupt example was unsuccessful. Unless setup failed, main will never return since DpTxSs_IntrExample is blocking (it is waiting on interrupts for Hot-Plug-Detect (HPD) events.
u32 Dp_SetupIntrSystem(void)
This function sets up the interrupt system so interrupts can occur for the DisplayPort TX Subsystem core.
The function is application-specific since the actual system may or may not have an interrupt controller. The DPTX Subsystem core could be directly connected to a processor without an interrupt controller. The user should modify this function to fit the application. None XST_SUCCESS if interrupt setup was successful.A specific error code defined in "xstatus.h" if an error occurs. None.
void DpRxSs_PowerChangeHandler(void *InstancePtr)
This function is the callback function for when the power state interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_NoVideoHandler(void *InstancePtr)
This function is the callback function for when a no video interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_VerticalBlankHandler(void *InstancePtr)
This function is the callback function for when a vertical blank interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_VerticalBlank1Handler(void *InstancePtr)
void DpRxSs_VerticalBlank2Handler(void *InstancePtr)
void DpRxSs_VerticalBlank3Handler(void *InstancePtr)
void DpRxSs_TrainingLostHandler(void *InstancePtr)
This function is the callback function for when a training lost interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_VideoHandler(void *InstancePtr)
This function is the callback function for when a valid video interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_TrainingDoneHandler(void *InstancePtr)
This function is the callback function for when the training done interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_UnplugHandler(void *InstancePtr)
This function is the callback function for when the unplug event occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_LinkBandwidthHandler(void *InstancePtr)
This function is the callback function for when the link bandwidth change occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_PllResetHandler(void *InstancePtr)
This function is the callback function for PLL reset request.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_BWChangeHandler(void *InstancePtr)
This function is the callback function for PLL reset request.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_AccessLaneSetHandler(void *InstancePtr)
This function is the callback function for Access lane set request.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_CRCTestEventHandler(void *InstancePtr)
This function is the callback function for Test CRC Event request.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_AccessLinkQualHandler(void *InstancePtr)
This function is the callback function for Access link qual request.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_AccessErrorCounterHandler(void *InstancePtr)
This function is the callback function for Access prbs error count.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_InfoPacketHandler(void *InstancePtr)
This function is the callback function for Info Packet Handling.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_ExtPacketHandler(void *InstancePtr)
This function is the callback function for Generic Packet Handling of 32-Bytes payload.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void Dprx_InterruptHandlerPayloadAlloc(void *InstancePtr)
void Dprx_InterruptHandlerActRx(void *InstancePtr)
void Dprx_InterruptHandlerDownReq(void *InstancePtr)
void Dprx_InterruptHandlerDownReply(void *InstancePtr)
void bufferWr_callback(void *InstancePtr)
u32 DpTxSs_VideoPhyInit(u32 BaseAddress)
This function configures Video Phy.
None. XST_SUCCESS if Video Phy configured successfully.XST_FAILURE, otherwise. None.
void PLLRefClkSel(XVphy *InstancePtr, u8 link_rate)
This function sets proper ref clk frequency and line rate.
InstancePtr is a pointer to the Video PHY instance. None. None.
void PHY_Two_byte_set(XVphy *InstancePtr, u8 Tx_to_two_byte, u8 Rx_to_two_byte)
This function sets GT in 16-bits (2-Byte) or 32-bits (4-Byte) mode.
InstancePtr is a pointer to the Video PHY instance. None. None.
void DpPt_LinkrateChgHandler(void *InstancePtr)
This function sets link line rate.
@return None. None.
References get_LineRate, set_vphy.
Referenced by DpTxSs_SetupIntrSystem.
void DpPt_pe_vs_adjustHandler(void *InstancePtr)
void DpPt_CustomWaitUs(void *InstancePtr, u32 MicroSeconds)
This function use h/w timer to count specific Microseconds.
pointer to timer MicroSeconds to wait None. None.
Referenced by reconfig_clkwiz, start_tx, sink_power_cycle, DpTxSs_SetupIntrSystem.
void DpPt_HpdEventHandler(void *InstancePtr)
This function takes care HPD event.
None. None.
References XDpTxSs_IsConnected, sink_power_down, sink_power_up, XDpTxSs::DpPtr.
Referenced by DpTxSs_SetupIntrSystem.
void DpPt_HpdPulseHandler(void *InstancePtr)
This function takes care HPD pulse interrupt.
None. None.
References XDpTxSs::DpPtr.
Referenced by DpTxSs_SetupIntrSystem.
void hpd_pulse_con(XDpTxSs *InstancePtr, u8 only_tx)
This function is the main hpd pulse process.
None. None.
u32 DpTxSubsystem_Start(XDpTxSs *InstancePtr, XDpTxSs_MainStreamAttributes Msa[4])
void DpTxSs_Setup(u8 *LineRate_init, u8 *LaneCount_init, u8 Edid_org[128], u8 Edid1_org[128])
This function sets up DPTxSubsystem.
LineRate LaneCount edid 1st block edid 2nd block None. None.
u32 PHY_Configuration_Tx(XVphy *InstancePtr, XVphy_User_Config PHY_User_Config_Table)
This function sets up PHY.
pointer to VideoPHY User Config table XST_SUCCESS if interrupt setup was successful.A specific error code defined in "xstatus.h" if an error occurs. None.
Referenced by DpPt_LinkrateChgHandler, switch_to_Tx_only, set_vphy.
u32 start_tx(u8 line_rate, u8 lane_count, user_config_struct user_config, XDpTxSs_MainStreamAttributes Msa[4])
This function starts tx process.
line rate lane counts pointer to resolution table bit per components video pattern to output XST_SUCCESS if interrupt setup was successful.A specific error code defined in "xstatus.h" if an error occurs. None.
u32 start_tx_only(u8 line_rate, u8 lane_count, user_config_struct user_config)
void clk_wiz_locked(void)
This function to check MMCM lock status.
None. None. None.
Referenced by start_tx.
void hpd_con(XDpTxSs *InstancePtr, u8 Edid_org[128], u8 Edid1_org[128], u16 res_update)
This function is called when a Hot-Plug-Detect (HPD) event is received by the DisplayPort TX Subsystem core.
InstancePtr is a pointer to the XDpTxSs instance. None. Use the XDpTxSs_SetCallback driver function to set this function as the handler for HPD event.
References XDpTxSs::UsrHpdEventData, XDpTxSs::DpPtr, set_vphy, XDpTxSs_SetLinkRate, XDpTxSs_SetLaneCount, XDpTxSs_SetVidMode, XDpTxSs_SetBpc, XDpTxSs_Start, Vpg_StreamSrcConfigure, Vpg_VidgenSetUserPattern, XDpTxSs_CheckLinkStatus.
static u8 CalculateChecksum(u8 *Data, u8 Size)
This function to send Audio Information Frame.
XilAudioInfoFrame None. None. This function to calculate EDID checksum edid data size of the edid data checksum number None.
XVidC_VideoMode GetPreferredVm(u8 *EdidPtr, u8 cap, u8 lane)
This function to find out preferred Video Mode ID.
pointer to edid data maximum capability of line speed number of lane Video Mode ID None.
void sink_power_down(void)
This function powers down sink.
None. None. None.
References XDpTxSs::DpPtr.
Referenced by DpPt_HpdEventHandler, sink_power_cycle.
void sink_power_up(void)
This function powers down sink.
None. None. None.
References XDpTxSs::DpPtr.
Referenced by DpPt_HpdEventHandler, sink_power_cycle.
u8 get_LineRate(void)
This function returns current line rate.
None. None. None.
References XDpTxSs::DpPtr.
Referenced by DpPt_LinkrateChgHandler.
u8 get_Lanecounts(void)
This function returns current lane counts.
None. None. None.
References XDpTxSs::DpPtr.
u32 set_vphy(int LineRate_init_tx)
This function sets VPHY based on the linerate.
user_config_struct. Status. None.
References PHY_Configuration_Tx.
Referenced by DpPt_LinkrateChgHandler, hpd_con.
void sink_power_cycle(void)
This function power cycle the sink.
user_config_struct. Status. None.
References sink_power_down, sink_power_up.
Referenced by DpPt_HpdEventHandler, start_tx, switch_to_Tx_only, hpd_pulse_con.
int VideoFMC_Init(void)
This function will detect video resolution/frequency change Many GPUs won't re-train when only video res/freq change.
Application needs to know if it changed and need to detect new parameter. Based on the parameter, re-set and re-start VDAM and TxNone This function will detect video resolution/frequency change Many GPUs won't re-train when only video res/freq change. None. None. None.
References I2C_MUX_ADDR, I2C_VFMCEXP_0_ADDR, I2C_VFMCEXP_1_ADDR, IDT_8T49N24x_Init, I2C_IDT8N49_ADDR, TI_LMK03318_PowerDown, I2C_LMK03318_ADDR.
void I2C_Scan(u32 BaseAddress)
This function scans VFMC- IIC.
None. None. None.
Referenced by VideoFMC_Init.
u8 i2c_read_dp141(u32 I2CBaseAddress, u8 I2CSlaveAddress, u16 RegisterAddress)
This function reads DP141 VFMC- IIC.
None. None. None.
int i2c_write_dp141(u32 I2CBaseAddress, u8 I2CSlaveAddress, u16 RegisterAddress, u8 Value)
void read_DP141()
u32 DpRxSs_Setup(void)
This function configures DisplayPort RX Subsystem.
None. XST_SUCCESS if DP RX Subsystem configured successfully.XST_FAILURE, otherwise. None.
void resetIp_wr()
void resetIp_rd()
void Dppt_DetectResolution(void *InstancePtr, u16 offset, XDpTxSs_MainStreamAttributes Msa[4], u8 stream)
void Dprx_ResetVideoOutput(void *InstancePtr)
void frameBuffer_stop_wr()
void frameBuffer_stop_rd()
void frameBuffer_stop()
u32 CalcStride(XVidC_ColorFormat Cfmt, u16 AXIMMDataWidth, XVidC_VideoStream *StreamPtr)
This function calculates the stride.
stride in bytes
int ConfigFrmbuf_wr(u32 StrideInBytes, XVidC_ColorFormat Cfmt, XVidC_VideoStream *StreamPtr)
This function configures Frame BufferWr for defined mode.
XST_SUCCESS if init is OK else XST_FAILURE
int ConfigFrmbuf_rd(u32 StrideInBytes, XVidC_ColorFormat Cfmt, XVidC_VideoStream *StreamPtr)
This function configures Frame Buffer for defined mode.
This function configures Frame Buffer for defined mode The FrramBuffer is put in Autorestart mode for non-Adaptive Sync mode When Adaptive Sync mode is enabled the FrameBuffer is put in manual mode.XST_SUCCESS if init is OK else XST_FAILURE
void frameBuffer_start_wr(XDpTxSs_MainStreamAttributes Msa[4], u8 downshift4K)
void frameBuffer_start_rd(XDpTxSs_MainStreamAttributes Msa[4], u8 downshift4K)
void DpPt_TxSetMsaValuesImmediate(void *InstancePtr)