xvid_pat_gen.h
XVID_PAT_GEN_H_
Prevent circular inclusions by using protection macros.
XILINX_DISPLAYPORT_VID_BASE_ADDRESS
XILINX_DISPLAYPORT_VID2_BASE_ADDRESS
XILINX_DISPLAYPORT_VID3_BASE_ADDRESS
XILINX_DISPLAYPORT_VID4_BASE_ADDRESS
XILINX_DISPLAYPORT_VID2_BASE_ADDRESS_OFFSET
XILINX_DISPLAYPORT_VID3_BASE_ADDRESS_OFFSET
XILINX_DISPLAYPORT_VID4_BASE_ADDRESS_OFFSET
u8 StreamPattern[5][5]
int Vpg_StreamSrcSetup(XDp *InstancePtr)
int Vpg_StreamSrcConfigure(XDp *InstancePtr, u8 VSplitMode, u8 first_time)
This function updates required timing values in Video Pattern Generator core.
InstancePtr is a pointer to the XDp instance. VSplitMode specifies vertical split mode to be used for splitting resolution vertically. XST_SUCCESS if Video pattern configured successfully. None.
References Vpg_VidgenSetTestPattern.
Referenced by detect_rx_video_and_startTx, hpd_con, start_tx, switch_to_Tx_only.
int Vpg_StreamSrcSync(XDp *InstancePtr)
void Vpg_VidgenSetTestPattern(XDp *InstancePtr, u8 Stream)
This function sets pattern to generate in Video Pattern Generator core.
InstancePtr is a pointer to the XDp instance. Stream is the stream number for which to set the pattern. None. None.
Referenced by Vpg_StreamSrcConfigure.
void Vpg_VidgenSetUserPattern(XDp *InstancePtr, u8 Pattern)
This function sets user pattern.
InstancePtr is a pointer to the XDp instance. Pattern number to set with None. None.