/******************************************************************************
* Copyright (c) 2018 - 2022 Xilinx, Inc. All rights reserved.
* Copyright (c) 2022 - 2024 Advanced Micro Devices, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT
******************************************************************************/

/*
 * This is an automatically generated file from script.
 * Please do not modify this!
 */

#include "xil_util.h"
#include "xpm_pin.h"

static XPm_PinGroup PmPinGroups[XPM_NODEIDX_STMIC_MAX] = {
	[XPM_NODEIDX_STMIC_LMIO_0] = {
		.GroupCount = 9U,
		.GroupList = ((u16 []) {
			PIN_GRP_GEM0_0,
			PIN_GRP_UART0_0,
			PIN_GRP_GPIO2_0,
			PIN_GRP_SPI0_0,
			PIN_GRP_CAN1_0,
			PIN_GRP_I2C1_0,
			PIN_GRP_TTC3_CLK_0,
			PIN_GRP_WWDT0_0,
			PIN_GRP_SYSMON_I2C0_0,
		})
	},
	[XPM_NODEIDX_STMIC_LMIO_1] = {
		.GroupCount = 9U,
		.GroupList = ((u16 []) {
			PIN_GRP_GEM0_0,
			PIN_GRP_UART0_0,
			PIN_GRP_GPIO2_1,
			PIN_GRP_SPI0_SS_0,
			PIN_GRP_CAN1_0,
			PIN_GRP_I2C1_0,
			PIN_GRP_TTC3_WAV_0,
			PIN_GRP_WWDT0_0,
			PIN_GRP_SYSMON_I2C0_0,
		})
	},
	[XPM_NODEIDX_STMIC_LMIO_2] = {
		.GroupCount = 10U,
		.GroupList = ((u16 []) {
			PIN_GRP_GEM0_0,
			PIN_GRP_TRACE0_0,
			PIN_GRP_UART0_CTRL_0,
			PIN_GRP_GPIO2_2,
			PIN_GRP_SPI0_SS_0,
			PIN_GRP_CAN0_0,
			PIN_GRP_I2C0_0,
			PIN_GRP_TTC2_CLK_0,
			PIN_GRP_WWDT0_0,
			PIN_GRP_SYSMON_I2C0_ALRT_0,
		})
	},
	[XPM_NODEIDX_STMIC_LMIO_3] = {
		.GroupCount = 9U,
		.GroupList = ((u16 []) {
			PIN_GRP_GEM0_0,
			PIN_GRP_TRACE0_0,
			PIN_GRP_UART0_CTRL_0,
			PIN_GRP_GPIO2_3,
			PIN_GRP_SPI0_SS_0,
			PIN_GRP_CAN0_0,
			PIN_GRP_I2C0_0,
			PIN_GRP_TTC2_WAV_0,
			PIN_GRP_WWDT0_0,
		})
	},
	[XPM_NODEIDX_STMIC_LMIO_4] = {
		.GroupCount = 10U,
		.GroupList = ((u16 []) {
			PIN_GRP_GEM0_0,
			PIN_GRP_TRACE0_0,
			PIN_GRP_UART1_0,
			PIN_GRP_GPIO2_4,
			PIN_GRP_SPI0_0,
			PIN_GRP_CAN1_1,
			PIN_GRP_I2C1_1,
			PIN_GRP_TTC1_CLK_0,
			PIN_GRP_WWDT0_0,
			PIN_GRP_SYSMON_I2C0_1,
		})
	},
	[XPM_NODEIDX_STMIC_LMIO_5] = {
		.GroupCount = 10U,
		.GroupList = ((u16 []) {
			PIN_GRP_GEM0_0,
			PIN_GRP_TRACE0_0,
			PIN_GRP_UART1_0,
			PIN_GRP_GPIO2_5,
			PIN_GRP_SPI0_0,
			PIN_GRP_CAN1_1,
			PIN_GRP_I2C1_1,
			PIN_GRP_TTC1_WAV_0,
			PIN_GRP_WWDT1_0,
			PIN_GRP_SYSMON_I2C0_1,
		})
	},
	[XPM_NODEIDX_STMIC_LMIO_6] = {
		.GroupCount = 10U,
		.GroupList = ((u16 []) {
			PIN_GRP_GEM0_0,
			PIN_GRP_TRACE0_CLK_0,
			PIN_GRP_UART1_CTRL_0,
			PIN_GRP_GPIO2_6,
			PIN_GRP_SPI1_0,
			PIN_GRP_CAN0_1,
			PIN_GRP_I2C0_1,
			PIN_GRP_TTC0_CLK_0,
			PIN_GRP_WWDT1_0,
			PIN_GRP_SYSMON_I2C0_ALRT_1,
		})
	},
	[XPM_NODEIDX_STMIC_LMIO_7] = {
		.GroupCount = 9U,
		.GroupList = ((u16 []) {
			PIN_GRP_GEM0_0,
			PIN_GRP_TRACE0_0,
			PIN_GRP_UART1_CTRL_0,
			PIN_GRP_GPIO2_7,
			PIN_GRP_SPI1_SS_0,
			PIN_GRP_CAN0_1,
			PIN_GRP_I2C0_1,
			PIN_GRP_TTC0_WAV_0,
			PIN_GRP_WWDT1_0,
		})
	},
	[XPM_NODEIDX_STMIC_LMIO_8] = {
		.GroupCount = 9U,
		.GroupList = ((u16 []) {
			PIN_GRP_GEM0_0,
			PIN_GRP_TRACE0_0,
			PIN_GRP_UART0_1,
			PIN_GRP_GPIO2_8,
			PIN_GRP_SPI1_SS_0,
			PIN_GRP_CAN1_2,
			PIN_GRP_I2C1_2,
			PIN_GRP_TTC3_CLK_1,
			PIN_GRP_WWDT1_0,
		})
	},
	[XPM_NODEIDX_STMIC_LMIO_9] = {
		.GroupCount = 10U,
		.GroupList = ((u16 []) {
			PIN_GRP_GEM0_0,
			PIN_GRP_TRACE0_0,
			PIN_GRP_UART0_1,
			PIN_GRP_GPIO2_9,
			PIN_GRP_SPI1_SS_0,
			PIN_GRP_CAN1_2,
			PIN_GRP_I2C1_2,
			PIN_GRP_TTC3_WAV_1,
			PIN_GRP_WWDT1_0,
			PIN_GRP_SYSMON_I2C0_2,
		})
	},
	[XPM_NODEIDX_STMIC_LMIO_10] = {
		.GroupCount = 10U,
		.GroupList = ((u16 []) {
			PIN_GRP_GEM0_0,
			PIN_GRP_TRACE0_0,
			PIN_GRP_UART0_CTRL_1,
			PIN_GRP_GPIO2_10,
			PIN_GRP_SPI1_0,
			PIN_GRP_CAN0_2,
			PIN_GRP_I2C0_2,
			PIN_GRP_TTC2_CLK_1,
			PIN_GRP_WWDT0_1,
			PIN_GRP_SYSMON_I2C0_2,
		})
	},
	[XPM_NODEIDX_STMIC_LMIO_11] = {
		.GroupCount = 10U,
		.GroupList = ((u16 []) {
			PIN_GRP_GEM0_0,
			PIN_GRP_TRACE0_0,
			PIN_GRP_UART0_CTRL_1,
			PIN_GRP_GPIO2_11,
			PIN_GRP_SPI1_0,
			PIN_GRP_CAN0_2,
			PIN_GRP_I2C0_2,
			PIN_GRP_TTC2_WAV_1,
			PIN_GRP_WWDT0_1,
			PIN_GRP_SYSMON_I2C0_ALRT_2,
		})
	},
	[XPM_NODEIDX_STMIC_LMIO_12] = {
		.GroupCount = 9U,
		.GroupList = ((u16 []) {
			PIN_GRP_GEM1_0,
			PIN_GRP_TRACE0_0,
			PIN_GRP_UART1_1,
			PIN_GRP_GPIO2_12,
			PIN_GRP_SPI0_1,
			PIN_GRP_CAN1_3,
			PIN_GRP_I2C1_3,
			PIN_GRP_TTC1_CLK_1,
			PIN_GRP_WWDT0_1,
		})
	},
	[XPM_NODEIDX_STMIC_LMIO_13] = {
		.GroupCount = 11U,
		.GroupList = ((u16 []) {
			PIN_GRP_GEM1_0,
			PIN_GRP_TRACE0_0,
			PIN_GRP_EMIO0_0,
			PIN_GRP_UART1_1,
			PIN_GRP_GPIO2_13,
			PIN_GRP_SPI0_SS_1,
			PIN_GRP_CAN1_3,
			PIN_GRP_I2C1_3,
			PIN_GRP_TTC1_WAV_1,
			PIN_GRP_WWDT0_1,
			PIN_GRP_SYSMON_I2C0_3,
		})
	},
	[XPM_NODEIDX_STMIC_LMIO_14] = {
		.GroupCount = 9U,
		.GroupList = ((u16 []) {
			PIN_GRP_GEM1_0,
			PIN_GRP_UART1_CTRL_1,
			PIN_GRP_GPIO2_14,
			PIN_GRP_SPI0_SS_1,
			PIN_GRP_CAN0_3,
			PIN_GRP_I2C0_3,
			PIN_GRP_TTC0_CLK_1,
			PIN_GRP_WWDT0_1,
			PIN_GRP_SYSMON_I2C0_3,
		})
	},
	[XPM_NODEIDX_STMIC_LMIO_15] = {
		.GroupCount = 9U,
		.GroupList = ((u16 []) {
			PIN_GRP_GEM1_0,
			PIN_GRP_UART1_CTRL_1,
			PIN_GRP_GPIO2_15,
			PIN_GRP_SPI0_SS_1,
			PIN_GRP_CAN0_3,
			PIN_GRP_I2C0_3,
			PIN_GRP_TTC0_WAV_1,
			PIN_GRP_WWDT1_1,
			PIN_GRP_SYSMON_I2C0_ALRT_3,
		})
	},
	[XPM_NODEIDX_STMIC_LMIO_16] = {
		.GroupCount = 8U,
		.GroupList = ((u16 []) {
			PIN_GRP_GEM1_0,
			PIN_GRP_UART0_2,
			PIN_GRP_GPIO2_16,
			PIN_GRP_SPI0_1,
			PIN_GRP_CAN1_4,
			PIN_GRP_I2C1_4,
			PIN_GRP_TTC3_CLK_2,
			PIN_GRP_WWDT1_1,
		})
	},
	[XPM_NODEIDX_STMIC_LMIO_17] = {
		.GroupCount = 9U,
		.GroupList = ((u16 []) {
			PIN_GRP_GEM1_0,
			PIN_GRP_EMIO0_0,
			PIN_GRP_UART0_2,
			PIN_GRP_GPIO2_17,
			PIN_GRP_SPI0_1,
			PIN_GRP_CAN1_4,
			PIN_GRP_I2C1_4,
			PIN_GRP_TTC3_WAV_2,
			PIN_GRP_WWDT1_1,
		})
	},
	[XPM_NODEIDX_STMIC_LMIO_18] = {
		.GroupCount = 11U,
		.GroupList = ((u16 []) {
			PIN_GRP_GEM1_0,
			PIN_GRP_TRACE0_0,
			PIN_GRP_UART0_CTRL_2,
			PIN_GRP_GPIO2_18,
			PIN_GRP_SPI1_1,
			PIN_GRP_PCIE0_0,
			PIN_GRP_CAN0_4,
			PIN_GRP_I2C0_4,
			PIN_GRP_TTC2_CLK_2,
			PIN_GRP_WWDT1_1,
			PIN_GRP_SYSMON_I2C0_4,
		})
	},
	[XPM_NODEIDX_STMIC_LMIO_19] = {
		.GroupCount = 11U,
		.GroupList = ((u16 []) {
			PIN_GRP_GEM1_0,
			PIN_GRP_TRACE0_0,
			PIN_GRP_UART0_CTRL_2,
			PIN_GRP_GPIO2_19,
			PIN_GRP_SPI1_SS_1,
			PIN_GRP_PCIE0_0,
			PIN_GRP_CAN0_4,
			PIN_GRP_I2C0_4,
			PIN_GRP_TTC2_WAV_2,
			PIN_GRP_WWDT1_1,
			PIN_GRP_SYSMON_I2C0_4,
		})
	},
	[XPM_NODEIDX_STMIC_LMIO_20] = {
		.GroupCount = 11U,
		.GroupList = ((u16 []) {
			PIN_GRP_GEM1_0,
			PIN_GRP_TRACE0_0,
			PIN_GRP_UART1_2,
			PIN_GRP_GPIO2_20,
			PIN_GRP_SPI1_SS_1,
			PIN_GRP_PCIE0_0,
			PIN_GRP_CAN1_5,
			PIN_GRP_I2C1_5,
			PIN_GRP_TTC1_CLK_2,
			PIN_GRP_WWDT0_2,
			PIN_GRP_SYSMON_I2C0_ALRT_4,
		})
	},
	[XPM_NODEIDX_STMIC_LMIO_21] = {
		.GroupCount = 10U,
		.GroupList = ((u16 []) {
			PIN_GRP_GEM1_0,
			PIN_GRP_TRACE0_0,
			PIN_GRP_UART1_2,
			PIN_GRP_GPIO2_21,
			PIN_GRP_SPI1_SS_1,
			PIN_GRP_PCIE0_0,
			PIN_GRP_CAN1_5,
			PIN_GRP_I2C1_5,
			PIN_GRP_TTC1_WAV_2,
			PIN_GRP_WWDT0_2,
		})
	},
	[XPM_NODEIDX_STMIC_LMIO_22] = {
		.GroupCount = 9U,
		.GroupList = ((u16 []) {
			PIN_GRP_GEM1_0,
			PIN_GRP_TRACE0_0,
			PIN_GRP_UART1_CTRL_2,
			PIN_GRP_GPIO2_22,
			PIN_GRP_SPI1_1,
			PIN_GRP_CAN0_5,
			PIN_GRP_I2C0_5,
			PIN_GRP_TTC0_CLK_2,
			PIN_GRP_WWDT0_2,
		})
	},
	[XPM_NODEIDX_STMIC_LMIO_23] = {
		.GroupCount = 10U,
		.GroupList = ((u16 []) {
			PIN_GRP_GEM1_0,
			PIN_GRP_TRACE0_0,
			PIN_GRP_UART1_CTRL_2,
			PIN_GRP_GPIO2_23,
			PIN_GRP_SPI1_1,
			PIN_GRP_CAN0_5,
			PIN_GRP_I2C0_5,
			PIN_GRP_TTC0_WAV_2,
			PIN_GRP_WWDT0_2,
			PIN_GRP_SYSMON_I2C0_5,
		})
	},
	[XPM_NODEIDX_STMIC_LMIO_24] = {
		.GroupCount = 9U,
		.GroupList = ((u16 []) {
			PIN_GRP_GEM_TSU0_0,
			PIN_GRP_GPIO2_24,
			PIN_GRP_SMP_0,
			PIN_GRP_MDIO0_0,
			PIN_GRP_CAN1_6,
			PIN_GRP_I2C1_6,
			PIN_GRP_MDIO1_0,
			PIN_GRP_WWDT0_2,
			PIN_GRP_SYSMON_I2C0_5,
		})
	},
	[XPM_NODEIDX_STMIC_LMIO_25] = {
		.GroupCount = 8U,
		.GroupList = ((u16 []) {
			PIN_GRP_GEM_TSU0_1,
			PIN_GRP_GPIO2_25,
			PIN_GRP_SMP_1,
			PIN_GRP_MDIO0_0,
			PIN_GRP_CAN1_6,
			PIN_GRP_I2C1_6,
			PIN_GRP_MDIO1_0,
			PIN_GRP_SYSMON_I2C0_ALRT_5,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_0] = {
		.GroupCount = 13U,
		.GroupList = ((u16 []) {
			PIN_GRP_OSPI0_0,
			PIN_GRP_SMAP0_0,
			PIN_GRP_QSPI0_0,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART0_3,
			PIN_GRP_GPIO0_0,
			PIN_GRP_SYSMON_I2C0_6,
			PIN_GRP_I2C1_7,
			PIN_GRP_SPI0_2,
			PIN_GRP_CAN0_6,
			PIN_GRP_WWDT0_3,
			PIN_GRP_TTC3_CLK_3,
			PIN_GRP_PCIE0_1,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_1] = {
		.GroupCount = 13U,
		.GroupList = ((u16 []) {
			PIN_GRP_OSPI0_0,
			PIN_GRP_SMAP0_0,
			PIN_GRP_QSPI0_0,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART0_3,
			PIN_GRP_GPIO0_1,
			PIN_GRP_SYSMON_I2C0_6,
			PIN_GRP_I2C1_7,
			PIN_GRP_SPI0_SS_2,
			PIN_GRP_CAN0_6,
			PIN_GRP_WWDT0_3,
			PIN_GRP_TTC3_WAV_3,
			PIN_GRP_PCIE0_1,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_2] = {
		.GroupCount = 13U,
		.GroupList = ((u16 []) {
			PIN_GRP_OSPI0_0,
			PIN_GRP_SMAP0_0,
			PIN_GRP_QSPI0_0,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART0_CTRL_3,
			PIN_GRP_GPIO0_2,
			PIN_GRP_SYSMON_I2C0_ALRT_6,
			PIN_GRP_I2C0_6,
			PIN_GRP_SPI0_SS_2,
			PIN_GRP_CAN1_7,
			PIN_GRP_WWDT0_3,
			PIN_GRP_TTC2_CLK_3,
			PIN_GRP_PCIE0_1,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_3] = {
		.GroupCount = 12U,
		.GroupList = ((u16 []) {
			PIN_GRP_OSPI0_0,
			PIN_GRP_SMAP0_0,
			PIN_GRP_QSPI0_0,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART0_CTRL_3,
			PIN_GRP_GPIO0_3,
			PIN_GRP_I2C0_6,
			PIN_GRP_SPI0_SS_2,
			PIN_GRP_CAN1_7,
			PIN_GRP_WWDT0_3,
			PIN_GRP_TTC2_WAV_3,
			PIN_GRP_PCIE0_1,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_4] = {
		.GroupCount = 13U,
		.GroupList = ((u16 []) {
			PIN_GRP_OSPI0_0,
			PIN_GRP_SMAP0_0,
			PIN_GRP_QSPI0_0,
			PIN_GRP_TRACE0_1,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART1_3,
			PIN_GRP_GPIO0_4,
			PIN_GRP_SYSMON_I2C0_7,
			PIN_GRP_I2C1_8,
			PIN_GRP_SPI0_2,
			PIN_GRP_CAN0_7,
			PIN_GRP_WWDT0_3,
			PIN_GRP_TTC1_CLK_3,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_5] = {
		.GroupCount = 13U,
		.GroupList = ((u16 []) {
			PIN_GRP_OSPI0_0,
			PIN_GRP_SMAP0_0,
			PIN_GRP_QSPI0_SS_0,
			PIN_GRP_TRACE0_1,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART1_3,
			PIN_GRP_GPIO0_5,
			PIN_GRP_SYSMON_I2C0_7,
			PIN_GRP_I2C1_8,
			PIN_GRP_SPI0_2,
			PIN_GRP_CAN0_7,
			PIN_GRP_WWDT1_2,
			PIN_GRP_TTC1_WAV_3,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_6] = {
		.GroupCount = 13U,
		.GroupList = ((u16 []) {
			PIN_GRP_OSPI0_0,
			PIN_GRP_SMAP0_0,
			PIN_GRP_QSPI0_FBCLK_0,
			PIN_GRP_TRACE0_CLK_1,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART1_CTRL_3,
			PIN_GRP_GPIO0_6,
			PIN_GRP_SYSMON_I2C0_ALRT_7,
			PIN_GRP_I2C0_7,
			PIN_GRP_SPI1_2,
			PIN_GRP_CAN1_8,
			PIN_GRP_WWDT1_2,
			PIN_GRP_TTC0_CLK_3,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_7] = {
		.GroupCount = 12U,
		.GroupList = ((u16 []) {
			PIN_GRP_OSPI0_0,
			PIN_GRP_SMAP0_0,
			PIN_GRP_QSPI0_SS_0,
			PIN_GRP_TRACE0_1,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART1_CTRL_3,
			PIN_GRP_GPIO0_7,
			PIN_GRP_I2C0_7,
			PIN_GRP_SPI1_SS_2,
			PIN_GRP_CAN1_8,
			PIN_GRP_WWDT1_2,
			PIN_GRP_TTC0_WAV_3,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_8] = {
		.GroupCount = 12U,
		.GroupList = ((u16 []) {
			PIN_GRP_OSPI0_0,
			PIN_GRP_SMAP0_0,
			PIN_GRP_QSPI0_0,
			PIN_GRP_TRACE0_1,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART0_4,
			PIN_GRP_GPIO0_8,
			PIN_GRP_I2C1_9,
			PIN_GRP_SPI1_SS_2,
			PIN_GRP_CAN0_8,
			PIN_GRP_WWDT1_2,
			PIN_GRP_TTC3_CLK_4,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_9] = {
		.GroupCount = 13U,
		.GroupList = ((u16 []) {
			PIN_GRP_OSPI0_0,
			PIN_GRP_SMAP0_0,
			PIN_GRP_QSPI0_0,
			PIN_GRP_TRACE0_1,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART0_4,
			PIN_GRP_GPIO0_9,
			PIN_GRP_SYSMON_I2C0_8,
			PIN_GRP_I2C1_9,
			PIN_GRP_SPI1_SS_2,
			PIN_GRP_CAN0_8,
			PIN_GRP_WWDT1_2,
			PIN_GRP_TTC3_WAV_4,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_10] = {
		.GroupCount = 13U,
		.GroupList = ((u16 []) {
			PIN_GRP_OSPI0_SS_0,
			PIN_GRP_SMAP0_0,
			PIN_GRP_QSPI0_0,
			PIN_GRP_TRACE0_1,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART0_CTRL_4,
			PIN_GRP_GPIO0_10,
			PIN_GRP_SYSMON_I2C0_8,
			PIN_GRP_I2C0_8,
			PIN_GRP_SPI1_2,
			PIN_GRP_CAN1_9,
			PIN_GRP_WWDT0_4,
			PIN_GRP_TTC2_CLK_4,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_11] = {
		.GroupCount = 13U,
		.GroupList = ((u16 []) {
			PIN_GRP_OSPI0_SS_0,
			PIN_GRP_SMAP0_0,
			PIN_GRP_QSPI0_0,
			PIN_GRP_TRACE0_1,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART0_CTRL_4,
			PIN_GRP_GPIO0_11,
			PIN_GRP_SYSMON_I2C0_ALRT_8,
			PIN_GRP_I2C0_8,
			PIN_GRP_SPI1_2,
			PIN_GRP_CAN1_9,
			PIN_GRP_WWDT0_4,
			PIN_GRP_TTC2_WAV_4,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_12] = {
		.GroupCount = 11U,
		.GroupList = ((u16 []) {
			PIN_GRP_OSPI0_RST_N_0,
			PIN_GRP_QSPI0_0,
			PIN_GRP_TRACE0_1,
			PIN_GRP_UART1_4,
			PIN_GRP_GPIO0_12,
			PIN_GRP_I2C1_10,
			PIN_GRP_SPI0_3,
			PIN_GRP_CAN0_9,
			PIN_GRP_WWDT0_4,
			PIN_GRP_TTC1_CLK_4,
			PIN_GRP_TAMPER_TRIGGER_0,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_13] = {
		.GroupCount = 13U,
		.GroupList = ((u16 []) {
			PIN_GRP_OSPI0_ECC_FAIL_0,
			PIN_GRP_SD0_0,
			PIN_GRP_USB0_0,
			PIN_GRP_TRACE0_1,
			PIN_GRP_UART1_4,
			PIN_GRP_GPIO0_13,
			PIN_GRP_SYSMON_I2C0_9,
			PIN_GRP_I2C1_10,
			PIN_GRP_SPI0_SS_3,
			PIN_GRP_CAN0_9,
			PIN_GRP_WWDT0_4,
			PIN_GRP_TTC1_WAV_4,
			PIN_GRP_TAMPER_TRIGGER_1,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_14] = {
		.GroupCount = 12U,
		.GroupList = ((u16 []) {
			PIN_GRP_SD1_0,
			PIN_GRP_SD0_0,
			PIN_GRP_USB0_0,
			PIN_GRP_TRACE0_1,
			PIN_GRP_UART1_CTRL_4,
			PIN_GRP_GPIO0_14,
			PIN_GRP_SYSMON_I2C0_9,
			PIN_GRP_I2C0_9,
			PIN_GRP_SPI0_SS_3,
			PIN_GRP_CAN1_10,
			PIN_GRP_WWDT0_4,
			PIN_GRP_TTC0_CLK_4,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_15] = {
		.GroupCount = 12U,
		.GroupList = ((u16 []) {
			PIN_GRP_SD1_0,
			PIN_GRP_SD0_0,
			PIN_GRP_USB0_0,
			PIN_GRP_TRACE0_1,
			PIN_GRP_UART1_CTRL_4,
			PIN_GRP_GPIO0_15,
			PIN_GRP_SYSMON_I2C0_ALRT_9,
			PIN_GRP_I2C0_9,
			PIN_GRP_SPI0_SS_3,
			PIN_GRP_CAN1_10,
			PIN_GRP_WWDT1_3,
			PIN_GRP_TTC0_WAV_4,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_16] = {
		.GroupCount = 11U,
		.GroupList = ((u16 []) {
			PIN_GRP_SD1_0,
			PIN_GRP_SD0_0,
			PIN_GRP_USB0_0,
			PIN_GRP_TRACE0_1,
			PIN_GRP_UART0_5,
			PIN_GRP_GPIO0_16,
			PIN_GRP_I2C1_11,
			PIN_GRP_SPI0_3,
			PIN_GRP_CAN0_10,
			PIN_GRP_WWDT1_3,
			PIN_GRP_TTC3_CLK_5,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_17] = {
		.GroupCount = 11U,
		.GroupList = ((u16 []) {
			PIN_GRP_SD1_0,
			PIN_GRP_SD0_PC_0,
			PIN_GRP_USB0_0,
			PIN_GRP_TRACE0_1,
			PIN_GRP_UART0_5,
			PIN_GRP_GPIO0_17,
			PIN_GRP_I2C1_11,
			PIN_GRP_SPI0_3,
			PIN_GRP_CAN0_10,
			PIN_GRP_WWDT1_3,
			PIN_GRP_TTC3_WAV_5,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_18] = {
		.GroupCount = 12U,
		.GroupList = ((u16 []) {
			PIN_GRP_SD1_0,
			PIN_GRP_SD0_0,
			PIN_GRP_USB0_0,
			PIN_GRP_TRACE0_1,
			PIN_GRP_UART0_CTRL_5,
			PIN_GRP_GPIO0_18,
			PIN_GRP_SYSMON_I2C0_10,
			PIN_GRP_I2C0_10,
			PIN_GRP_SPI1_3,
			PIN_GRP_CAN1_11,
			PIN_GRP_WWDT1_3,
			PIN_GRP_TTC2_CLK_5,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_19] = {
		.GroupCount = 12U,
		.GroupList = ((u16 []) {
			PIN_GRP_SD1_0,
			PIN_GRP_SD0_0,
			PIN_GRP_USB0_0,
			PIN_GRP_TRACE0_1,
			PIN_GRP_UART0_CTRL_5,
			PIN_GRP_GPIO0_19,
			PIN_GRP_SYSMON_I2C0_10,
			PIN_GRP_I2C0_10,
			PIN_GRP_SPI1_SS_3,
			PIN_GRP_CAN1_11,
			PIN_GRP_WWDT1_3,
			PIN_GRP_TTC2_WAV_5,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_20] = {
		.GroupCount = 12U,
		.GroupList = ((u16 []) {
			PIN_GRP_SD1_0,
			PIN_GRP_SD0_0,
			PIN_GRP_USB0_0,
			PIN_GRP_TRACE0_1,
			PIN_GRP_UART1_5,
			PIN_GRP_GPIO0_20,
			PIN_GRP_SYSMON_I2C0_ALRT_10,
			PIN_GRP_I2C1_12,
			PIN_GRP_SPI1_SS_3,
			PIN_GRP_CAN0_11,
			PIN_GRP_WWDT0_5,
			PIN_GRP_TTC1_CLK_5,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_21] = {
		.GroupCount = 11U,
		.GroupList = ((u16 []) {
			PIN_GRP_SD1_0,
			PIN_GRP_SD0_0,
			PIN_GRP_USB0_0,
			PIN_GRP_TRACE0_1,
			PIN_GRP_UART1_5,
			PIN_GRP_GPIO0_21,
			PIN_GRP_I2C1_12,
			PIN_GRP_SPI1_SS_3,
			PIN_GRP_CAN0_11,
			PIN_GRP_WWDT0_5,
			PIN_GRP_TTC1_WAV_5,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_22] = {
		.GroupCount = 12U,
		.GroupList = ((u16 []) {
			PIN_GRP_SD1_0,
			PIN_GRP_SD0_0,
			PIN_GRP_USB0_0,
			PIN_GRP_TEST_CLK_0,
			PIN_GRP_UART1_CTRL_5,
			PIN_GRP_GPIO0_22,
			PIN_GRP_I2C0_11,
			PIN_GRP_SPI1_3,
			PIN_GRP_CAN1_12,
			PIN_GRP_WWDT0_5,
			PIN_GRP_TTC0_CLK_5,
			PIN_GRP_TAMPER_TRIGGER_2,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_23] = {
		.GroupCount = 13U,
		.GroupList = ((u16 []) {
			PIN_GRP_SD1_0,
			PIN_GRP_SD0_0,
			PIN_GRP_USB0_0,
			PIN_GRP_TEST_CLK_0,
			PIN_GRP_UART1_CTRL_5,
			PIN_GRP_GPIO0_23,
			PIN_GRP_SYSMON_I2C0_11,
			PIN_GRP_I2C0_11,
			PIN_GRP_SPI1_3,
			PIN_GRP_CAN1_12,
			PIN_GRP_WWDT0_5,
			PIN_GRP_TTC0_WAV_5,
			PIN_GRP_TAMPER_TRIGGER_3,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_24] = {
		.GroupCount = 7U,
		.GroupList = ((u16 []) {
			PIN_GRP_SD1_DQS_0,
			PIN_GRP_SD0_CD_0,
			PIN_GRP_USB0_0,
			PIN_GRP_TEST_CLK_0,
			PIN_GRP_GPIO0_24,
			PIN_GRP_SYSMON_I2C0_11,
			PIN_GRP_WWDT0_5,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_25] = {
		.GroupCount = 7U,
		.GroupList = ((u16 []) {
			PIN_GRP_SD1_PC_0,
			PIN_GRP_SD0_WP_0,
			PIN_GRP_USB0_0,
			PIN_GRP_TEST_CLK_0,
			PIN_GRP_GPIO0_25,
			PIN_GRP_SYSMON_I2C0_ALRT_11,
			PIN_GRP_SMP_2,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_26] = {
		.GroupCount = 14U,
		.GroupList = ((u16 []) {
			PIN_GRP_OSPI0_ECC_FAIL_1,
			PIN_GRP_SD0_PC_1,
			PIN_GRP_GEM0_1,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART0_6,
			PIN_GRP_GPIO1_0,
			PIN_GRP_SYSMON_I2C0_12,
			PIN_GRP_I2C0_12,
			PIN_GRP_SPI0_4,
			PIN_GRP_CAN0_12,
			PIN_GRP_WWDT1_4,
			PIN_GRP_TTC3_CLK_6,
			PIN_GRP_SMP_3,
			PIN_GRP_TAMPER_TRIGGER_4,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_27] = {
		.GroupCount = 12U,
		.GroupList = ((u16 []) {
			PIN_GRP_SD0_1,
			PIN_GRP_GEM0_1,
			PIN_GRP_USB1_0,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART0_6,
			PIN_GRP_GPIO1_1,
			PIN_GRP_SYSMON_I2C0_12,
			PIN_GRP_I2C0_12,
			PIN_GRP_SPI0_SS_4,
			PIN_GRP_CAN0_12,
			PIN_GRP_WWDT1_4,
			PIN_GRP_TTC3_WAV_6,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_28] = {
		.GroupCount = 13U,
		.GroupList = ((u16 []) {
			PIN_GRP_SMAP0_0,
			PIN_GRP_SD0_1,
			PIN_GRP_GEM0_1,
			PIN_GRP_USB1_0,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART0_CTRL_6,
			PIN_GRP_GPIO1_2,
			PIN_GRP_SYSMON_I2C0_ALRT_12,
			PIN_GRP_I2C1_13,
			PIN_GRP_SPI0_SS_4,
			PIN_GRP_CAN1_13,
			PIN_GRP_WWDT1_4,
			PIN_GRP_TTC2_CLK_6,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_29] = {
		.GroupCount = 12U,
		.GroupList = ((u16 []) {
			PIN_GRP_SMAP0_0,
			PIN_GRP_SD0_1,
			PIN_GRP_GEM0_1,
			PIN_GRP_USB1_0,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART0_CTRL_6,
			PIN_GRP_GPIO1_3,
			PIN_GRP_I2C1_13,
			PIN_GRP_SPI0_SS_4,
			PIN_GRP_CAN1_13,
			PIN_GRP_WWDT1_4,
			PIN_GRP_TTC2_WAV_6,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_30] = {
		.GroupCount = 14U,
		.GroupList = ((u16 []) {
			PIN_GRP_SMAP0_0,
			PIN_GRP_SD0_1,
			PIN_GRP_GEM0_1,
			PIN_GRP_USB1_0,
			PIN_GRP_TRACE0_2,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART1_6,
			PIN_GRP_GPIO1_4,
			PIN_GRP_SYSMON_I2C0_13,
			PIN_GRP_I2C0_13,
			PIN_GRP_SPI0_4,
			PIN_GRP_CAN0_13,
			PIN_GRP_WWDT1_4,
			PIN_GRP_TTC1_CLK_6,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_31] = {
		.GroupCount = 14U,
		.GroupList = ((u16 []) {
			PIN_GRP_SMAP0_0,
			PIN_GRP_SD0_1,
			PIN_GRP_GEM0_1,
			PIN_GRP_USB1_0,
			PIN_GRP_TRACE0_2,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART1_6,
			PIN_GRP_GPIO1_5,
			PIN_GRP_SYSMON_I2C0_13,
			PIN_GRP_I2C0_13,
			PIN_GRP_SPI0_4,
			PIN_GRP_CAN0_13,
			PIN_GRP_WWDT0_6,
			PIN_GRP_TTC1_WAV_6,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_32] = {
		.GroupCount = 14U,
		.GroupList = ((u16 []) {
			PIN_GRP_SMAP0_0,
			PIN_GRP_SD0_1,
			PIN_GRP_GEM0_1,
			PIN_GRP_USB1_0,
			PIN_GRP_TRACE0_CLK_2,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART1_CTRL_6,
			PIN_GRP_GPIO1_6,
			PIN_GRP_SYSMON_I2C0_ALRT_13,
			PIN_GRP_I2C1_14,
			PIN_GRP_SPI1_4,
			PIN_GRP_CAN1_14,
			PIN_GRP_WWDT0_6,
			PIN_GRP_TTC0_CLK_6,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_33] = {
		.GroupCount = 13U,
		.GroupList = ((u16 []) {
			PIN_GRP_SMAP0_0,
			PIN_GRP_SD0_1,
			PIN_GRP_GEM0_1,
			PIN_GRP_USB1_0,
			PIN_GRP_TRACE0_2,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART1_CTRL_6,
			PIN_GRP_GPIO1_7,
			PIN_GRP_I2C1_14,
			PIN_GRP_SPI1_SS_4,
			PIN_GRP_CAN1_14,
			PIN_GRP_WWDT0_6,
			PIN_GRP_TTC0_WAV_6,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_34] = {
		.GroupCount = 13U,
		.GroupList = ((u16 []) {
			PIN_GRP_SMAP0_0,
			PIN_GRP_SD0_1,
			PIN_GRP_GEM0_1,
			PIN_GRP_USB1_0,
			PIN_GRP_TRACE0_2,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART0_7,
			PIN_GRP_GPIO1_8,
			PIN_GRP_I2C0_14,
			PIN_GRP_SPI1_SS_4,
			PIN_GRP_CAN0_14,
			PIN_GRP_WWDT0_6,
			PIN_GRP_TTC3_CLK_7,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_35] = {
		.GroupCount = 14U,
		.GroupList = ((u16 []) {
			PIN_GRP_SMAP0_0,
			PIN_GRP_SD0_1,
			PIN_GRP_GEM0_1,
			PIN_GRP_USB1_0,
			PIN_GRP_TRACE0_2,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART0_7,
			PIN_GRP_GPIO1_9,
			PIN_GRP_SYSMON_I2C0_14,
			PIN_GRP_I2C0_14,
			PIN_GRP_SPI1_SS_4,
			PIN_GRP_CAN0_14,
			PIN_GRP_WWDT0_6,
			PIN_GRP_TTC3_WAV_7,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_36] = {
		.GroupCount = 14U,
		.GroupList = ((u16 []) {
			PIN_GRP_SMAP0_0,
			PIN_GRP_SD0_1,
			PIN_GRP_GEM0_1,
			PIN_GRP_USB1_0,
			PIN_GRP_TRACE0_2,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART0_CTRL_7,
			PIN_GRP_GPIO1_10,
			PIN_GRP_SYSMON_I2C0_14,
			PIN_GRP_I2C1_15,
			PIN_GRP_SPI1_4,
			PIN_GRP_CAN1_15,
			PIN_GRP_WWDT1_5,
			PIN_GRP_TTC2_CLK_7,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_37] = {
		.GroupCount = 15U,
		.GroupList = ((u16 []) {
			PIN_GRP_SMAP0_0,
			PIN_GRP_SD0_CD_1,
			PIN_GRP_GEM0_1,
			PIN_GRP_USB1_0,
			PIN_GRP_TRACE0_2,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART0_CTRL_7,
			PIN_GRP_GPIO1_11,
			PIN_GRP_SYSMON_I2C0_ALRT_14,
			PIN_GRP_I2C1_15,
			PIN_GRP_SPI1_4,
			PIN_GRP_CAN1_15,
			PIN_GRP_WWDT1_5,
			PIN_GRP_TTC2_WAV_7,
			PIN_GRP_TAMPER_TRIGGER_5,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_38] = {
		.GroupCount = 14U,
		.GroupList = ((u16 []) {
			PIN_GRP_SMAP0_0,
			PIN_GRP_SD0_WP_1,
			PIN_GRP_GEM1_1,
			PIN_GRP_USB1_0,
			PIN_GRP_TRACE0_2,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART1_7,
			PIN_GRP_GPIO1_12,
			PIN_GRP_I2C0_15,
			PIN_GRP_SPI0_5,
			PIN_GRP_CAN0_15,
			PIN_GRP_WWDT1_5,
			PIN_GRP_TTC1_CLK_7,
			PIN_GRP_PCIE0_2,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_39] = {
		.GroupCount = 14U,
		.GroupList = ((u16 []) {
			PIN_GRP_SMAP0_0,
			PIN_GRP_GEM1_1,
			PIN_GRP_USB1_0,
			PIN_GRP_TRACE0_2,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART1_7,
			PIN_GRP_GPIO1_13,
			PIN_GRP_SYSMON_I2C0_15,
			PIN_GRP_I2C0_15,
			PIN_GRP_SPI0_SS_5,
			PIN_GRP_CAN0_15,
			PIN_GRP_WWDT1_5,
			PIN_GRP_TTC1_WAV_7,
			PIN_GRP_PCIE0_2,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_40] = {
		.GroupCount = 14U,
		.GroupList = ((u16 []) {
			PIN_GRP_SD1_1,
			PIN_GRP_SMAP0_0,
			PIN_GRP_GEM1_1,
			PIN_GRP_TRACE0_2,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART1_CTRL_7,
			PIN_GRP_GPIO1_14,
			PIN_GRP_SYSMON_I2C0_15,
			PIN_GRP_I2C1_16,
			PIN_GRP_SPI0_SS_5,
			PIN_GRP_CAN1_16,
			PIN_GRP_WWDT1_5,
			PIN_GRP_TTC0_CLK_7,
			PIN_GRP_PCIE0_2,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_41] = {
		.GroupCount = 14U,
		.GroupList = ((u16 []) {
			PIN_GRP_SD1_1,
			PIN_GRP_SMAP0_0,
			PIN_GRP_GEM1_1,
			PIN_GRP_TRACE0_2,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART1_CTRL_7,
			PIN_GRP_GPIO1_15,
			PIN_GRP_SYSMON_I2C0_ALRT_15,
			PIN_GRP_I2C1_16,
			PIN_GRP_SPI0_SS_5,
			PIN_GRP_CAN1_16,
			PIN_GRP_WWDT0_7,
			PIN_GRP_TTC0_WAV_7,
			PIN_GRP_PCIE0_2,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_42] = {
		.GroupCount = 12U,
		.GroupList = ((u16 []) {
			PIN_GRP_SD1_1,
			PIN_GRP_SMAP0_0,
			PIN_GRP_GEM1_1,
			PIN_GRP_TRACE0_2,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART0_8,
			PIN_GRP_GPIO1_16,
			PIN_GRP_I2C0_16,
			PIN_GRP_SPI0_5,
			PIN_GRP_CAN0_16,
			PIN_GRP_WWDT0_7,
			PIN_GRP_TTC3_CLK_8,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_43] = {
		.GroupCount = 12U,
		.GroupList = ((u16 []) {
			PIN_GRP_SD1_1,
			PIN_GRP_SMAP0_0,
			PIN_GRP_GEM1_1,
			PIN_GRP_TRACE0_2,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART0_8,
			PIN_GRP_GPIO1_17,
			PIN_GRP_I2C0_16,
			PIN_GRP_SPI0_5,
			PIN_GRP_CAN0_16,
			PIN_GRP_WWDT0_7,
			PIN_GRP_TTC3_WAV_8,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_44] = {
		.GroupCount = 13U,
		.GroupList = ((u16 []) {
			PIN_GRP_SD1_1,
			PIN_GRP_SMAP0_0,
			PIN_GRP_GEM1_1,
			PIN_GRP_TRACE0_2,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART0_CTRL_8,
			PIN_GRP_GPIO1_18,
			PIN_GRP_SYSMON_I2C0_16,
			PIN_GRP_I2C1_17,
			PIN_GRP_SPI1_5,
			PIN_GRP_CAN1_17,
			PIN_GRP_WWDT0_7,
			PIN_GRP_TTC2_CLK_8,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_45] = {
		.GroupCount = 13U,
		.GroupList = ((u16 []) {
			PIN_GRP_SD1_1,
			PIN_GRP_SMAP0_0,
			PIN_GRP_GEM1_1,
			PIN_GRP_TRACE0_2,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART0_CTRL_8,
			PIN_GRP_GPIO1_19,
			PIN_GRP_SYSMON_I2C0_16,
			PIN_GRP_I2C1_17,
			PIN_GRP_SPI1_SS_5,
			PIN_GRP_CAN1_17,
			PIN_GRP_WWDT0_7,
			PIN_GRP_TTC2_WAV_8,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_46] = {
		.GroupCount = 13U,
		.GroupList = ((u16 []) {
			PIN_GRP_SD1_1,
			PIN_GRP_SMAP0_0,
			PIN_GRP_GEM1_1,
			PIN_GRP_TRACE0_2,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART1_8,
			PIN_GRP_GPIO1_20,
			PIN_GRP_SYSMON_I2C0_ALRT_16,
			PIN_GRP_I2C0_17,
			PIN_GRP_SPI1_SS_5,
			PIN_GRP_CAN0_17,
			PIN_GRP_WWDT1_6,
			PIN_GRP_TTC1_CLK_8,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_47] = {
		.GroupCount = 12U,
		.GroupList = ((u16 []) {
			PIN_GRP_SD1_1,
			PIN_GRP_SMAP0_0,
			PIN_GRP_GEM1_1,
			PIN_GRP_TRACE0_2,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART1_8,
			PIN_GRP_GPIO1_21,
			PIN_GRP_I2C0_17,
			PIN_GRP_SPI1_SS_5,
			PIN_GRP_CAN0_17,
			PIN_GRP_WWDT1_6,
			PIN_GRP_TTC1_WAV_8,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_48] = {
		.GroupCount = 11U,
		.GroupList = ((u16 []) {
			PIN_GRP_SD1_1,
			PIN_GRP_SMAP0_0,
			PIN_GRP_GEM1_1,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART1_CTRL_8,
			PIN_GRP_GPIO1_22,
			PIN_GRP_I2C1_18,
			PIN_GRP_SPI1_5,
			PIN_GRP_CAN1_18,
			PIN_GRP_WWDT1_6,
			PIN_GRP_TTC0_CLK_8,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_49] = {
		.GroupCount = 12U,
		.GroupList = ((u16 []) {
			PIN_GRP_SD1_1,
			PIN_GRP_SMAP0_0,
			PIN_GRP_GEM1_1,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_UART1_CTRL_8,
			PIN_GRP_GPIO1_23,
			PIN_GRP_SYSMON_I2C0_17,
			PIN_GRP_I2C1_18,
			PIN_GRP_SPI1_5,
			PIN_GRP_CAN1_18,
			PIN_GRP_WWDT1_6,
			PIN_GRP_TTC0_WAV_8,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_50] = {
		.GroupCount = 11U,
		.GroupList = ((u16 []) {
			PIN_GRP_SD1_DQS_1,
			PIN_GRP_SMAP0_0,
			PIN_GRP_GEM_TSU0_2,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_GPIO1_24,
			PIN_GRP_SYSMON_I2C0_17,
			PIN_GRP_MDIO0_1,
			PIN_GRP_MDIO1_1,
			PIN_GRP_WWDT1_6,
			PIN_GRP_SMP_4,
			PIN_GRP_TAMPER_TRIGGER_6,
		})
	},
	[XPM_NODEIDX_STMIC_PMIO_51] = {
		.GroupCount = 10U,
		.GroupList = ((u16 []) {
			PIN_GRP_SD1_PC_1,
			PIN_GRP_SMAP0_0,
			PIN_GRP_GEM_TSU0_3,
			PIN_GRP_TEST_SCAN_0,
			PIN_GRP_GPIO1_25,
			PIN_GRP_SYSMON_I2C0_ALRT_17,
			PIN_GRP_MDIO0_1,
			PIN_GRP_MDIO1_1,
			PIN_GRP_SMP_5,
			PIN_GRP_TAMPER_TRIGGER_7,
		})
	},
};

/****************************************************************************/
/**
 * @brief  Get requested pin group by node index
 *
 * @param PinIndex     Pin Index.
 *
 * @return Pointer to requested XPm_PinGroup, NULL otherwise
 *
 * @note Requires only node index
 *
 ****************************************************************************/
XPm_PinGroup *XPmPin_GetGroupByIdx(const u32 PinIndex)
{
	return &PmPinGroups[PinIndex];
}
