
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT

*
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xv_warp_init.h"

/*
* The configuration table for devices
*/

XV_warp_init_Config XV_warp_init_ConfigTable[XPAR_XV_WARP_INIT_NUM_INSTANCES] =
{
	{
		XPAR_V_WARP_INIT_0_DEVICE_ID,
		XPAR_V_WARP_INIT_0_S_AXI_CTRL_BASEADDR,
		XPAR_V_WARP_INIT_0_MAX_COLS,
		XPAR_V_WARP_INIT_0_MAX_ROWS,
		XPAR_V_WARP_INIT_0_WARP_TYPE,
		XPAR_V_WARP_INIT_0_AXI_MM_DATA_WIDTH,
		XPAR_V_WARP_INIT_0_BITS_PER_COMPONENT,
		XPAR_V_WARP_INIT_0_MAX_CTRL_PTS_R
	}
};
