ttcps
XTTCPS_OPTION_EXTERNAL_CLK
External clock source.
XTTCPS_OPTION_CLK_EDGE_NEG
Clock on trailing edge for external clock.
XTTCPS_OPTION_INTERVAL_MODE
Interval mode.
Referenced by SetupTicker.
XTTCPS_OPTION_DECREMENT
Decrement the counter.
XTTCPS_OPTION_MATCH_MODE
Match mode.
XTTCPS_OPTION_WAVE_DISABLE
No waveform output.
Referenced by SetupTicker.
XTTCPS_OPTION_WAVE_POLARITY
Waveform polarity.
COUNTER_BASE_ADDRESS_MASK
Mask to detect main TTC node.
Referenced by XTtcPs_InterruptHandler.
XTTCPS_CLK_CNTRL_OFFSET
Clock Control Register.
Referenced by XTtcPs_CfgInitialize, XTtcPs_GetPrescaler, XTtcPs_SetOptions, XTtcPs_SetPrescaler.
XTTCPS_CNT_CNTRL_OFFSET
Counter Control Register.
Referenced by XTtcPs_CfgInitialize, XTtcPs_SelfTest, XTtcPs_SetOptions.
XTTCPS_COUNT_VALUE_OFFSET
Current Counter Value.
XTTCPS_INTERVAL_VAL_OFFSET
Interval Count Value.
Referenced by XTtcPs_CfgInitialize.
XTTCPS_MATCH_0_OFFSET
Match 1 value.
Referenced by XTtcPs_CfgInitialize.
XTTCPS_MATCH_1_OFFSET
Match 2 value.
Referenced by XTtcPs_CfgInitialize.
XTTCPS_MATCH_2_OFFSET
Match 3 value.
Referenced by XTtcPs_CfgInitialize.
XTTCPS_ISR_OFFSET
Interrupt Status Register.
Referenced by XTtcPs_CfgInitialize, XTtcPs_InterruptHandler.
XTTCPS_IER_OFFSET
Interrupt Enable Register.
Referenced by XTtcPs_CfgInitialize.
XTTCPS_CLK_CNTRL_PS_EN_MASK
Prescale enable.
Referenced by XTtcPs_GetPrescaler, XTtcPs_SetPrescaler.
XTTCPS_CLK_CNTRL_PS_VAL_MASK
Prescale value.
Referenced by XTtcPs_GetPrescaler, XTtcPs_SetPrescaler.
XTTCPS_CLK_CNTRL_PS_VAL_SHIFT
Prescale shift.
Referenced by XTtcPs_GetPrescaler, XTtcPs_SetPrescaler.
XTTCPS_CLK_CNTRL_PS_DISABLE
Prescale disable.
Referenced by XTtcPs_CalcIntervalFromFreq, XTtcPs_GetPrescaler, XTtcPs_SetPrescaler.
XTTCPS_CLK_CNTRL_SRC_MASK
Clock source.
XTTCPS_CLK_CNTRL_EXT_EDGE_MASK
External Clock edge.
XTTCPS_CNT_CNTRL_DIS_MASK
Disable the counter.
XTTCPS_CNT_CNTRL_INT_MASK
Interval mode.
XTTCPS_CNT_CNTRL_DECR_MASK
Decrement mode.
XTTCPS_CNT_CNTRL_MATCH_MASK
Match mode.
XTTCPS_CNT_CNTRL_RST_MASK
Reset counter.
XTTCPS_CNT_CNTRL_EN_WAVE_MASK
Enable waveform.
XTTCPS_CNT_CNTRL_POL_WAVE_MASK
Waveform polarity.
XTTCPS_CNT_CNTRL_RESET_VALUE
Reset value.
Referenced by XTtcPs_CfgInitialize, XTtcPs_SelfTest.
XTTCPS_COUNT_VALUE_MASK
16-bit counter value
XTTCPS_INTERVAL_VAL_MASK
16-bit Interval value
XTTCPS_MATCH_MASK
16-bit Match value
XTTCPS_NUM_MATCH_REG
Num of Match reg.
Referenced by XTtcPs_GetMatchValue, XTtcPs_SetMatchValue.
XTTCPS_IXR_INTERVAL_MASK
Interval Interrupt.
Referenced by SetupTicker.
XTTCPS_IXR_MATCH_0_MASK
Match 1 Interrupt.
XTTCPS_IXR_MATCH_1_MASK
Match 2 Interrupt.
XTTCPS_IXR_MATCH_2_MASK
Match 3 Interrupt.
XTTCPS_IXR_CNT_OVR_MASK
Counter Overflow.
XTTCPS_IXR_ALL_MASK
All valid Interrupts.
Referenced by XTtcPs_CfgInitialize, XTtcPs_Release.
typedef void(* XTtcPs_StatusHandler)(const void *CallBackRef, u32 StatusEvent))(const void *CallBackRef, u32 StatusEvent)
typedef u16 XInterval
This typedef contains interval count and Match register value.
typedef u16 XMatchRegValue
XTtcPs_StatusHandlerTableEntry StatusHandlerTable[XPAR_XTTCPS_NUM_INSTANCES][XPAR_XTTCPS_NUM_INSTANCES]
XTtcPs_Config XTtcPs_ConfigTable[][]
This table contains configuration information for each TTC device in the system.
XTtcPs_Config XTtcPs_ConfigTable[XPAR_XTTCPS_NUM_INSTANCES][XPAR_XTTCPS_NUM_INSTANCES]
This table contains configuration information for each TTC device in the system.
OptionsMap TmrCtrOptionsTable[][]
XTtcPs_Config XTtcPs_ConfigTable[][]
This table contains configuration information for each TTC device in the system.
static void StubStatusHandler(const void *CallBackRef, u32 StatusEvent)
This is a stub for the status callback.
The stub is here in case the upper layers forget to set the handler. CallBackRef is a pointer to the upper layer callback reference StatusEvent is the event that just occurred. None. None.
static u32 GetIndexFromBaseAddr(u32 BaseAddress)
s32 XTtcPs_CfgInitialize(XTtcPs *InstancePtr, XTtcPs_Config *ConfigPtr, u32 EffectiveAddr)
Initializes a specific XTtcPs instance such that the driver is ready to use.
This function initializes a single timer counter in the triple timer counter function block.The state of the device after initialization is: Overflow ModeInternal (pclk) selectedCounter disabledAll Interrupts disabledOutput waveforms disabled InstancePtr is a pointer to the XTtcPs instance. ConfigPtr is a reference to a structure containing information about a specific TTC device. EffectiveAddr is the device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, then use ConfigPtr->BaseAddress for this parameter, passing the physical address instead. - XST_SUCCESS if the initialization is successful. - XST_DEVICE_IS_STARTED if the device is started. It must be stopped to re-initialize. Device has to be stopped first to call this function to initialize it.
References XTtcPs_Config::BaseAddress, XTtcPs::Config, XTtcPs_Config::InputClockHz, XTtcPs_Config::IntrParent, XTtcPs::IsReady, XTTCPS_CLK_CNTRL_OFFSET, XTTCPS_CNT_CNTRL_OFFSET, XTTCPS_CNT_CNTRL_RESET_VALUE, XTTCPS_IER_OFFSET, XTTCPS_INTERVAL_VAL_OFFSET, XTTCPS_ISR_OFFSET, XTtcPs_IsStarted, XTTCPS_IXR_ALL_MASK, XTTCPS_MATCH_0_OFFSET, XTTCPS_MATCH_1_OFFSET, XTTCPS_MATCH_2_OFFSET, XTtcPs_ResetCounterValue, XTtcPs_Stop, XTtcPs_WriteReg.
u32 XTtcPs_Release(XTtcPs *InstancePtr)
This routine releases resources of XTtcPs instance/driver.
None - XST_SUCCESS if node release was successful XST_FAILURE if node release was fail, Node won't be released if any other counter/counters in that TTC in use. None.
References XTtcPs_Config::BaseAddress, XTtcPs::Config, XTtcPs_ClearInterruptStatus, XTtcPs_DisableInterrupts, XTtcPs_GetInterruptStatus, XTTCPS_IXR_ALL_MASK, XTtcPs_Stop.
Referenced by TmrInterruptExample.
void XTtcPs_SetMatchValue(XTtcPs *InstancePtr, u8 MatchIndex, XMatchRegValue Value)
This function is used to set the match registers.
There are three match registers.The match 0 register is special. If the waveform output mode is enabled, the waveform will change polarity when the count matches the value in the match 0 register. The polarity of the waveform output can also be set using the XTtcPs_SetOptions() function. InstancePtr is a pointer to the XTtcPs instance. MatchIndex is the index to the match register to be set. Valid values are: 0 - 2. Value is the 16-bit value to be set in the match register. Valid Values are: (For Zynq): 0 - ((2^16)-1) (For Zynq UltraScale + MpSoc) and Versal: 0 - ((2^32) - 1) None None
References XTtcPs_Config::BaseAddress, XTtcPs::Config, XTtcPs::IsReady, XTtcPs_Match_N_Offset, XTTCPS_NUM_MATCH_REG, XTtcPs_WriteReg.
XMatchRegValue XTtcPs_GetMatchValue(XTtcPs *InstancePtr, u8 MatchIndex)
This function is used to get the value of the match registers.
There are three match registers. InstancePtr is a pointer to the XTtcPs instance. MatchIndex is the index to the match register to be set. There are three match registers are there. Valid values are: 0 - 2. The match register value None
References XTtcPs_Config::BaseAddress, XTtcPs::Config, XTtcPs::IsReady, XTtcPs_Match_N_Offset, XTTCPS_NUM_MATCH_REG, XTtcPs_ReadReg.
void XTtcPs_SetPrescaler(XTtcPs *InstancePtr, u8 PrescalerValue)
This function sets the prescaler enable bit and if needed sets the prescaler bits in the control register.
InstancePtr is a pointer to the XTtcPs instance. PrescalerValue is a number from 0-16 that sets the prescaler to use. If the parameter is 0 - 15, use a prescaler on the clock of 2^(PrescalerValue+1), or 2-65536. If the parameter is XTTCPS_CLK_CNTRL_PS_DISABLE, do not use a prescaler. Valid values are: 0 - 15None None
References XTtcPs_Config::BaseAddress, XTtcPs::Config, XTtcPs::IsReady, XTTCPS_CLK_CNTRL_OFFSET, XTTCPS_CLK_CNTRL_PS_DISABLE, XTTCPS_CLK_CNTRL_PS_EN_MASK, XTTCPS_CLK_CNTRL_PS_VAL_MASK, XTTCPS_CLK_CNTRL_PS_VAL_SHIFT, XTtcPs_ReadReg, XTtcPs_WriteReg.
u8 XTtcPs_GetPrescaler(XTtcPs *InstancePtr)
This function gets the input clock prescaler.
InstancePtr is a pointer to the XTtcPs instance. The value(n) from which the prescalar value is calculated as 2^(n+1). Some example values are given below : Value Prescaler 0 2 1 4 N 2^(n+1) 15 65536 16 1 Valid values are: 0 - 16 None.
References XTtcPs_Config::BaseAddress, XTtcPs::Config, XTtcPs::IsReady, XTTCPS_CLK_CNTRL_OFFSET, XTTCPS_CLK_CNTRL_PS_DISABLE, XTTCPS_CLK_CNTRL_PS_EN_MASK, XTTCPS_CLK_CNTRL_PS_VAL_MASK, XTTCPS_CLK_CNTRL_PS_VAL_SHIFT, XTtcPs_ReadReg.
void XTtcPs_CalcIntervalFromFreq(XTtcPs *InstancePtr, u32 Freq, XInterval *Interval, u8 *Prescaler)
This function calculates the interval value as well as the prescaler value for a given frequency.
InstancePtr is a pointer to the XTtcPs instance. Freq is the requested output frequency for the device. valid values are: 1 - (2^32)-1 Interval is the interval value for the given frequency, it is the output value for this function. Prescaler is the prescaler value for the given frequency, it is the output value for this function. None. Upon successful calculation for the given frequency, Interval and Prescaler carry the settings for the timer counter; Upon unsuccessful calculation, Interval and Prescaler are set to 0xFF(FF) for their maximum values to signal the caller of failure. Therefore, caller needs to check the return interval or prescaler values for whether the function has succeeded.
References XTtcPs::Config, XTtcPs_Config::InputClockHz, XTTCPS_CLK_CNTRL_PS_DISABLE.
u32 XTtcPs_InterruptHandler(XTtcPs *InstancePtr)
Handles interrupts by resetting the counter value and clearing the status register.
InstancePtr is a pointer to the XTtcPs instance. XST_SUCCESS if successful. None.
References XTtcPs_Config::BaseAddress, XTtcPs::Config, COUNTER_BASE_ADDRESS_MASK, XTTCPS_ISR_OFFSET.
Referenced by SetupTicker.
void XTtcPs_SetStatusHandler(XTtcPs *InstancePtr, void *CallBackRef, XTtcPs_StatusHandler FuncPointer)
Sets the status callback function, the status handler, which the driver calls when it encounters conditions that should be reported to upper layer software.
The handler executes in an interrupt context, so it must minimize the amount of processing performed. One of the following status events is passed to the status handler. InstancePtr is a pointer to the XTtcPs instance. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. FuncPointer is the pointer to the callback function. None. The handler is called within interrupt context, so it should do its work quickly and queue potentially time-consuming work to a task-level thread.
References XTtcPs_Config::BaseAddress, XTtcPs::Config, XTtcPs::IsReady.
Referenced by SetupTicker.
XTtcPs_Config * XTtcPs_LookupConfig(u32 BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
A table contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xttcps.h for the definition of XTtcPs_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
s32 XTtcPs_SetOptions(XTtcPs *InstancePtr, u32 Options)
This function sets the options for the TTC device.
InstancePtr is a pointer to the XTtcPs instance. Options contains the specified options to be set. This is a bit mask where a 1 means to turn the option on, and a 0 means to turn the option off. One or more bit values may be contained in the mask. See the bit definitions named XTTCPS_*_OPTION in the file xttcps.h. XST_SUCCESS if options are successfully set.XST_FAILURE if any of the options are unknown. None
References XTtcPs_Config::BaseAddress, XTtcPs::Config, XTtcPs::IsReady, XTTCPS_CLK_CNTRL_OFFSET, XTTCPS_CNT_CNTRL_OFFSET, XTtcPs_ReadReg, XTtcPs_WriteReg.
u32 XTtcPs_GetOptions(XTtcPs *InstancePtr)
This function gets the settings for the options for the TTC device.
InstancePtr is a pointer to the XTtcPs instance. The return u32 contains the specified options that are set. This is a bit mask where a '1' means the option is on, and a'0' means the option is off. One or more bit values may be contained in the mask. See the bit definitions named XTTCPS_*_OPTION in the file xttcps.h.None.
References XTtcPs_Config::BaseAddress, XTtcPs::Config, XTtcPs::IsReady, XTtcPs_ReadReg.
s32 XTtcPs_SelfTest(XTtcPs *InstancePtr)
Runs a self-test on the driver/device.
InstancePtr is a pointer to the XTtcPs instance. - XST_SUCCESS if successful - XST_FAILURE indicates a register did not read or write correctly This test fails if it is not called right after initialization.
References XTtcPs_Config::BaseAddress, XTtcPs::Config, XTtcPs::IsReady, XTTCPS_CNT_CNTRL_OFFSET, XTTCPS_CNT_CNTRL_RESET_VALUE, XTtcPs_ReadReg.
XTTCPS_H
XTTCPS_MAX_INTERVAL_COUNT
XTTCPS_NUM_COUNTERS
InstReadReg
InstWriteReg
XTtcPs_Start
This function starts the counter/timer without resetting the counter value.
InstancePtr is a pointer to the XTtcPs instance. None C-style signature: void XTtcPs_Start(XTtcPs *InstancePtr)
Referenced by SetupTicker.
XTtcPs_Stop
This function stops the counter/timer.
This macro may be called at any time to stop the counter. The counter holds the last value until it is reset, restarted or enabled. InstancePtr is a pointer to the XTtcPs instance. None C-style signature: void XTtcPs_Stop(XTtcPs *InstancePtr)
Referenced by TmrInterruptExample, XTtcPs_CfgInitialize, XTtcPs_Release.
XTtcPs_IsStarted
This function checks whether the timer counter has already started.
InstancePtr is a pointer to the XTtcPs instance Non-zero if the device has started, '0' otherwise. C-style signature: int XTtcPs_IsStarted(XTtcPs *InstancePtr)
Referenced by XTtcPs_CfgInitialize.
XTtcPs_GetCounterValue
This function returns the current 16-bit counter value.
It may be called at any time. InstancePtr is a pointer to the XTtcPs instance. zynq:16 bit counter value. zynq ultrascale+mpsoc:32 bit counter value. C-style signature: zynq: u16 XTtcPs_GetCounterValue(XTtcPs *InstancePtr) zynq ultrascale+mpsoc: u32 XTtcPs_GetCounterValue(XTtcPs *InstancePtr)
XTtcPs_SetInterval
This function sets the interval value to be used in interval mode.
InstancePtr is a pointer to the XTtcPs instance. Value is the 16-bit value to be set in the interval register. None C-style signature: void XTtcPs_SetInterval(XTtcPs *InstancePtr, XInterval Value)
XTtcPs_GetInterval
This function gets the interval value from the interval register.
InstancePtr is a pointer to the XTtcPs instance. zynq:16 bit interval value. zynq ultrascale+mpsoc:32 bit interval value. C-style signature: zynq: u16 XTtcPs_GetInterval(XTtcPs *InstancePtr) zynq ultrascale+mpsoc: u32 XTtcPs_GetInterval(XTtcPs *InstancePtr)
XTtcPs_ResetCounterValue
This macro resets the count register.
It may be called at any time. The counter is reset to either 0 or 0xFFFF, or the interval value, depending on the increment/decrement mode. The state of the counter, as started or stopped, is not affected by calling reset. InstancePtr is a pointer to the XTtcPs instance. None C-style signature: void XTtcPs_ResetCounterValue(XTtcPs *InstancePtr)
Referenced by XTtcPs_CfgInitialize.
XTtcPs_EnableInterrupts
This function enables the interrupts.
InstancePtr is a pointer to the XTtcPs instance. InterruptMask defines which interrupt should be enabled. Constants are defined in xttcps_hw.h as XTTCPS_IXR_*. This is a bit mask, all set bits will be enabled, cleared bits will not be disabled. None. C-style signature: void XTtcPs_EnableInterrupts(XTtcPs *InstancePtr, u32 InterruptMask)
Referenced by SetupTicker.
XTtcPs_DisableInterrupts
This function disables the interrupts.
InstancePtr is a pointer to the XTtcPs instance. InterruptMask defines which interrupt should be disabled. Constants are defined in xttcps_hw.h as XTTCPS_IXR_*. This is a bit mask, all set bits will be disabled, cleared bits will not be disabled. None. C-style signature: void XTtcPs_DisableInterrupts(XTtcPs *InstancePtr, u32 InterruptMask)
Referenced by XTtcPs_Release.
XTtcPs_GetInterruptStatus
This function reads the interrupt status.
InstancePtr is a pointer to the XTtcPs instance. None. C-style signature: u32 XTtcPs_GetInterruptStatus(XTtcPs *InstancePtr)
Referenced by XTtcPs_Release.
XTtcPs_ClearInterruptStatus
This function clears the interrupt status.
InstancePtr is a pointer to the XTtcPs instance. InterruptMask defines which interrupt should be cleared. Constants are defined in xttcps_hw.h as XTTCPS_IXR_*. This is a bit mask, all set bits will be cleared, cleared bits will not be cleared. None. C-style signature: void XTtcPs_ClearInterruptStatus(XTtcPs *InstancePtr, u32 InterruptMask)
Referenced by XTtcPs_Release.
XTTCPS_HW_H
ARMA9
XTtcPs_ReadReg
Read the given Timer Counter register.
BaseAddress is the base address of the timer counter device. RegOffset is the register offset to be read The 32-bit value of the register C-style signature: u32 XTtcPs_ReadReg(u32 BaseAddress, u32 RegOffset)
Referenced by XTtcPs_GetMatchValue, XTtcPs_GetOptions, XTtcPs_GetPrescaler, XTtcPs_SelfTest, XTtcPs_SetOptions, XTtcPs_SetPrescaler.
XTtcPs_WriteReg
Write the given Timer Counter register.
BaseAddress is the base address of the timer counter device. RegOffset is the register offset to be written Data is the 32-bit value to write to the register None. C-style signature: void XTtcPs_WriteReg(XTtcPs BaseAddress, u32 RegOffset, u32 Data)
Referenced by XTtcPs_CfgInitialize, XTtcPs_SetMatchValue, XTtcPs_SetOptions, XTtcPs_SetPrescaler.
XTtcPs_Match_N_Offset
Calculate a match register offset using the Match Register index.
MatchIndex is the 0-2 value of the match register MATCH_N_OFFSET. C-style signature: u32 XTtcPs_Match_N_Offset(u8 MatchIndex)
Referenced by XTtcPs_GetMatchValue, XTtcPs_SetMatchValue.
XTTCPS_NUM_TMRCTR_OPTIONS