
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version:
* DO NOT EDIT.
*
* Copyright (C) 2010-2015 Xilinx, Inc. All Rights Reserved.*
*Permission is hereby granted, free of charge, to any person obtaining a copy
*of this software and associated documentation files (the Software), to deal
*in the Software without restriction, including without limitation the rights
*to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*copies of the Software, and to permit persons to whom the Software is
*furnished to do so, subject to the following conditions:
*
*The above copyright notice and this permission notice shall be included in
*all copies or substantial portions of the Software.
*
* Use of the Software is limited solely to applications:
*(a) running on a Xilinx device, or
*(b) that interact with a Xilinx device through a bus or interconnect.
*
*THE SOFTWARE IS PROVIDED AS IS, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
*XILINX BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
*WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT
*OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*
*Except as contained in this notice, the name of the Xilinx shall not be used
*in advertising or otherwise to promote the sale, use or other dealings in
*this Software without prior written authorization from Xilinx.
*

*
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xdptxss.h"

/*
* The configuration table for devices
*/

#define XPAR_DP_TX_SUBSYSTEM_0_DP_PRESENT 	1
#define XPAR_DP_TX_SUBSYSTEM_0_VS_PRESENT 	1
#define XPAR_DP_TX_SUBSYSTEM_0_VTC1_PRESENT 	1
#define XPAR_DP_TX_SUBSYSTEM_0_VTC2_PRESENT 	1
#define XPAR_DP_TX_SUBSYSTEM_0_VTC3_PRESENT 	1
#define XPAR_DP_TX_SUBSYSTEM_0_VTC4_PRESENT 	1


XDpTxSs_Config XDpTxSs_ConfigTable[] =
{
	{
		XPAR_DP_TX_SUBSYSTEM_0_DEVICE_ID,
		XPAR_DP_TX_SUBSYSTEM_0_BASEADDR,
		XPAR_DP_TX_SUBSYSTEM_0_AUDIO_ENABLE,
		XPAR_DP_TX_SUBSYSTEM_0_BITS_PER_COLOR,
		XPAR_DP_TX_SUBSYSTEM_0_HDCP_ENABLE,
		XPAR_DP_TX_SUBSYSTEM_0_LANE_COUNT,
		XPAR_DP_TX_SUBSYSTEM_0_MODE,
		XPAR_DP_TX_SUBSYSTEM_0_NUM_STREAMS,

		{
			XPAR_DP_TX_SUBSYSTEM_0_DP_PRESENT,
			{
				XPAR_DP_TX_SUBSYSTEM_0_DP_DEVICE_ID,
				XPAR_DP_TX_SUBSYSTEM_0_DP_BASEADDR,
				XPAR_DP_TX_SUBSYSTEM_0_DP_S_AXI_ACLK,
				XPAR_DP_TX_SUBSYSTEM_0_DP_LANE_COUNT,
				XPAR_DP_TX_SUBSYSTEM_0_DP_LINK_RATE,
				XPAR_DP_TX_SUBSYSTEM_0_DP_MAX_BITS_PER_COLOR,
				XPAR_DP_TX_SUBSYSTEM_0_DP_QUAD_PIXEL_ENABLE,
				XPAR_DP_TX_SUBSYSTEM_0_DP_DUAL_PIXEL_ENABLE,
				XPAR_DP_TX_SUBSYSTEM_0_DP_YCRCB_ENABLE,
				XPAR_DP_TX_SUBSYSTEM_0_DP_YONLY_ENABLE,
				XPAR_DP_TX_SUBSYSTEM_0_DP_GT_DATAWIDTH,
				XPAR_DP_TX_SUBSYSTEM_0_DP_SECONDARY_SUPPORT,
				XPAR_DP_TX_SUBSYSTEM_0_DP_AUDIO_CHANNELS,
				XPAR_DP_TX_SUBSYSTEM_0_DP_MST_ENABLE,
				XPAR_DP_TX_SUBSYSTEM_0_DP_NUMBER_OF_MST_STREAMS,
				XPAR_DP_TX_SUBSYSTEM_0_DP_PROTOCOL_SELECTION,
				XPAR_DP_TX_SUBSYSTEM_0_DP_FLOW_DIRECTION
			}
		},
		{
			XPAR_DP_TX_SUBSYSTEM_0_VS_PRESENT,
			{
				XPAR_DP_TX_SUBSYSTEM_0_VS_DEVICE_ID,
				XPAR_DP_TX_SUBSYSTEM_0_VS_BASEADDR,
				XPAR_DP_TX_SUBSYSTEM_0_VS_ACTIVE_COLS,
				XPAR_DP_TX_SUBSYSTEM_0_VS_ACTIVE_ROWS,
				XPAR_DP_TX_SUBSYSTEM_0_VS_MAX_SEGMENTS,
				XPAR_DP_TX_SUBSYSTEM_0_VS_AXIS_VIDEO_MAX_TDATA_WIDTH,
				XPAR_DP_TX_SUBSYSTEM_0_VS_AXIS_VIDEO_MAX_ITDATASMPLS_PER_CLK,
				XPAR_DP_TX_SUBSYSTEM_0_VS_AXIS_VIDEO_MAX_OTDATASMPLS_PER_CLK,
				XPAR_DP_TX_SUBSYSTEM_0_VS_MAX_OVRLAP,
				XPAR_DP_TX_SUBSYSTEM_0_VS_MAX_SMPL_WIDTH,
				XPAR_DP_TX_SUBSYSTEM_0_VS_HAS_AXI4_LITE,
				XPAR_DP_TX_SUBSYSTEM_0_VS_HAS_IRQ
			}
		},
		{
			{
				XPAR_DP_TX_SUBSYSTEM_0_VTC1_PRESENT,
				{
					XPAR_DP_TX_SUBSYSTEM_0_VTC1_DEVICE_ID,
					XPAR_DP_TX_SUBSYSTEM_0_VTC1_BASEADDR
				}
			},
			{
				XPAR_DP_TX_SUBSYSTEM_0_VTC2_PRESENT,
				{
					XPAR_DP_TX_SUBSYSTEM_0_VTC2_DEVICE_ID,
					XPAR_DP_TX_SUBSYSTEM_0_VTC2_BASEADDR
				}
			},
			{
				XPAR_DP_TX_SUBSYSTEM_0_VTC3_PRESENT,
				{
					XPAR_DP_TX_SUBSYSTEM_0_VTC3_DEVICE_ID,
					XPAR_DP_TX_SUBSYSTEM_0_VTC3_BASEADDR
				}
			},
			{
				XPAR_DP_TX_SUBSYSTEM_0_VTC4_PRESENT,
				{
					XPAR_DP_TX_SUBSYSTEM_0_VTC4_DEVICE_ID,
					XPAR_DP_TX_SUBSYSTEM_0_VTC4_BASEADDR
				}
			}
		}
	}
};
