xsysmon_selftest.c
XSM_ATR_TEST_VALUE
int XSysMon_SelfTest(XSysMon *InstancePtr)
Functions in xsysmon_selftest.c.
Run a self-test on the driver/device.The test Resets the device,Writes a value into the Alarm Threshold register and reads it back for comparison.Resets the device again. InstancePtr is a pointer to the XSysMon instance. XST_SUCCESS if the value read from the Alarm Threshold register is the same as the value written.XST_FAILURE Otherwise This is a destructive test in that resets of the device are performed. Refer to the device specification for the device status after the reset operation.
References XSysMon::IsReady, XSM_ATR_VCCINT_UPPER, XSysMon_GetAlarmThreshold, XSysMon_Reset, XSysMon_SetAlarmThreshold.
Referenced by SysMonAuxPolledExample, SysMonIntrExample, SysMonPolledExample.