xsysmon_sinit.c
XSysMon_Config XSysMon_ConfigTable[][]
This table contains configuration information for each System Monitor/ADC device in the system.
XSysMon_Config * XSysMon_LookupConfig(u32 BaseAddress)
Functions in xsysmon_sinit.c.
This function looks up the device configuration based on the unique device ID.The table XSysMon_ConfigTable contains the configuration info for each device in the system. DeviceId contains the ID of the device for which the device configuration pointer is to be returned. A pointer to the configuration found.NULL if the specified device ID was not found. None.
Referenced by SysMonAuxPolledExample, SysMonIntrExample, SysMonPolledExample.