xsysmon_intr.c
void XSysMon_IntrGlobalEnable(XSysMon *InstancePtr)
Functions in xsysmon_intr.c.
This function enables the global interrupt in the Global Interrupt Enable Register (GIER) so that the interrupt output from the System Monitor/ADC device is enabled.Interrupts enabled using XSysMon_IntrEnable() will not occur until the global interrupt enable bit is set by using this function. InstancePtr is a pointer to the XSysMon instance. None. The device must be configured at hardware build time to include interrupt component for this function to work.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon_Config::IncludeInterrupt, XSysMon::IsReady, XSM_GIER_GIE_MASK, XSM_GIER_OFFSET, XSysMon_WriteReg.
Referenced by SysMonIntrExample.
void XSysMon_IntrGlobalDisable(XSysMon *InstancePtr)
This function disables the global interrupt in the Global Interrupt Enable Register (GIER) so that the interrupt output from the System Monitor/ADC device is disabled.
InstancePtr is a pointer to the XSysMon instance. None. The device must be configured at hardware build time to include interrupt component for this function to work.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon_Config::IncludeInterrupt, XSysMon::IsReady, XSM_GIER_OFFSET, XSysMon_WriteReg.
Referenced by SysMonIntrExample.
void XSysMon_IntrEnable(XSysMon *InstancePtr, u32 Mask)
This function enables the specified interrupts in the device.
Interrupts enabled using this function will not occur until the global interrupt enable bit is set by using the XSysMon_IntrGlobalEnable()function. InstancePtr is a pointer to the XSysMon instance. Mask is the bit-mask of the interrupts to be enabled. Bit positions of 1 will be enabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XSM_IPIXR_* bits defined in xsysmon_hw.h. None. The device must be configured at hardware build time to include interrupt component for this function to work.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon_Config::IncludeInterrupt, XSysMon::IsReady, XSM_IPIER_OFFSET, XSM_IPIXR_ALL_MASK, XSysMon_ReadReg, XSysMon_WriteReg.
Referenced by SysMonIntrExample.
void XSysMon_IntrDisable(XSysMon *InstancePtr, u32 Mask)
This function disables the specified interrupts in the device.
InstancePtr is a pointer to the XSysMon instance. Mask is the bit-mask of the interrupts to be disabled. Bit positions of 1 will be disabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XSM_IPIXR_* bits defined in xsysmon_hw.h. None. The device must be configured at hardware build time to include interrupt component for this function to work.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon_Config::IncludeInterrupt, XSysMon::IsReady, XSM_IPIER_OFFSET, XSM_IPIXR_ALL_MASK, XSysMon_ReadReg, XSysMon_WriteReg.
u32 XSysMon_IntrGetEnabled(XSysMon *InstancePtr)
This function returns the enabled interrupts read from the Interrupt Enable Register (IPIER).
Use the XSM_IPIXR_* constants defined in xsysmon_hw.h to interpret the returned value. InstancePtr is a pointer to the XSysMon instance. A 32-bit value representing the contents of the IPIER. The device must be configured at hardware build time to include interrupt component for this function to work.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon_Config::IncludeInterrupt, XSysMon::IsReady, XSM_IPIER_OFFSET, XSM_IPIXR_ALL_MASK, XSysMon_ReadReg.
u32 XSysMon_IntrGetStatus(XSysMon *InstancePtr)
This function returns the interrupt status read from Interrupt Status Register(IPISR).
Use the XSM_IPIXR_* constants defined in xsysmon_hw.h to interpret the returned value. InstancePtr is a pointer to the XSysMon instance. A 32-bit value representing the contents of the IPISR. The device must be configured at hardware build time to include interrupt component for this function to work.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon_Config::IncludeInterrupt, XSysMon::IsReady, XSM_IPISR_OFFSET, XSM_IPIXR_ALL_MASK, XSysMon_ReadReg.
Referenced by SysMonIntrExample.
void XSysMon_IntrClear(XSysMon *InstancePtr, u32 Mask)
This function clears the specified interrupts in the Interrupt Status Register (IPISR).
InstancePtr is a pointer to the XSysMon instance. Mask is the bit-mask of the interrupts to be cleared. Bit positions of 1 will be cleared. Bit positions of 0 will not change the previous interrupt status. This mask is formed by OR'ing XSM_IPIXR_* bits which are defined in xsysmon_hw.h. None. The device must be configured at hardware build time to include interrupt component for this function to work.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon_Config::IncludeInterrupt, XSysMon::IsReady, XSM_IPISR_OFFSET, XSM_IPIXR_ALL_MASK, XSysMon_ReadReg, XSysMon_WriteReg.
Referenced by SysMonIntrExample.