xsysmon.h
XSM_CH_TEMP
On Chip Temperature.
Referenced by SysMonIntrExample, SysMonPolledExample.
XSM_CH_VCCINT
VCCINT.
XSM_CH_VCCAUX
VCCAUX.
Referenced by SysMonIntrExample, SysMonPolledExample.
XSM_CH_VPVN
VP/VN Dedicated analog inputs.
Referenced by XSysMon_SetSingleChParams.
XSM_CH_VREFP
VREFP.
XSM_CH_VREFN
VREFN.
Referenced by XSysMon_SetExtenalMux, XSysMon_SetSingleChParams.
XSM_CH_VBRAM
VBRAM - 7 Series and Zynq.
Referenced by XSysMon_GetAdcData.
XSM_CH_SUPPLY_CALIB
Supply Calib Data Reg.
XSM_CH_ADC_CALIB
ADC Offset Channel Reg.
XSM_CH_GAINERR_CALIB
Gain Error Channel Reg.
XSM_CH_VCCPINT
On-chip PS VCCPINT Channel, Zynq.
Referenced by XSysMon_GetAdcData.
XSM_CH_VCCPAUX
On-chip PS VCCPAUX Channel, Zynq.
XSM_CH_VCCPDRO
On-chip PS VCCPDRO Channel, Zynq.
XSM_CH_VCCLPINT
On-chip PS VCCLPINT Channel, Ultrascale.
XSM_CH_VCCFPINT
On-chip PS VCCFPINT Channel, Ultrascale.
XSM_CH_VCCPSAUX
On-chip PS VCCPAUX Channel, Ultrascale.
XSM_CH_AUX_MIN
Channel number for 1st Aux Channel.
Referenced by SysMonAuxPolledExample, XSysMon_SetExtenalMux, XSysMon_SetSingleChParams.
XSM_CH_AUX_MAX
Channel number for Last Aux channel.
Referenced by XSysMon_GetAdcData, XSysMon_SetExtenalMux, XSysMon_SetSingleChParams.
XSM_CH_VUSR0
VUSER0 Supply - UltraScale.
Referenced by XSysMon_GetAdcData, XSysMon_SetSingleChParams.
XSM_CH_VUSR1
VUSER1 Supply - UltraScale.
XSM_CH_VUSR2
VUSER2 Supply - UltraScale.
XSM_CH_VUSR3
VUSER3 Supply - UltraScale.
Referenced by XSysMon_GetAdcData, XSysMon_SetSingleChParams.
XSM_CALIB_SUPPLY_OFFSET_COEFF
Supply Offset Calib Coefficient.
XSM_CALIB_ADC_OFFSET_COEFF
ADC Offset Calib Coefficient.
XSM_CALIB_GAIN_ERROR_COEFF
Gain Error Calib Coefficient.
Referenced by XSysMon_GetCalibCoefficient.
XSM_MAX_TEMP
Maximum Temperature Data.
Referenced by SysMonPolledExample.
XSM_MAX_VCCINT
Maximum VCCINT Data.
XSM_MAX_VCCAUX
Maximum VCCAUX Data.
Referenced by SysMonPolledExample.
XSM_MAX_VCCBRAM
Maximum VCCBRAM Data, 7 Series/Zynq.
XSM_MIN_TEMP
Minimum Temperature Data.
Referenced by SysMonPolledExample.
XSM_MIN_VCCINT
Minimum VCCINT Data.
XSM_MIN_VCCAUX
Minimum VCCAUX Data.
Referenced by SysMonPolledExample.
XSM_MIN_VCCBRAM
Minimum VCCBRAM Data, 7 Series/Zynq.
XSM_MAX_VCCPINT
Maximum VCCPINT Data, Zynq.
XSM_MAX_VCCPAUX
Maximum VCCPAUX Data, Zynq.
XSM_MAX_VCCPDRO
Maximum VCCPDRO Data, Zynq.
Referenced by XSysMon_GetMinMaxMeasurement.
XSM_MIN_VCCPINT
Minimum VCCPINT Data, Zynq.
Referenced by XSysMon_GetMinMaxMeasurement.
XSM_MIN_VCCPAUX
Minimum VCCPAUX Data, Zynq.
XSM_MIN_VCCPDRO
Minimum VCCPDRO Data, Zynq.
Referenced by XSysMon_GetMinMaxMeasurement.
XSM_MAX_VUSR0
Maximum VUSR0 Data, Ultrascale.
Referenced by XSysMon_GetMinMaxMeasurement.
XSM_MAX_VUSR1
Maximum VUSR1 Data, Ultrascale.
XSM_MAX_VUSR2
Maximum VUSR2 Data, Ultrascale.
XSM_MAX_VUSR3
Maximum VUSR3 Data, Ultrascale.
Referenced by XSysMon_GetMinMaxMeasurement.
XSM_MIN_VUSR0
Minimum VUSR0 Data, Ultrascale.
Referenced by XSysMon_GetMinMaxMeasurement.
XSM_MIN_VUSR1
Minimum VUSR1 Data, Ultrascale.
XSM_MIN_VUSR2
Minimum VUSR2 Data, Ultrascale.
XSM_MIN_VUSR3
Minimum VUSR3 Data, Ultrascale.
Referenced by XSysMon_GetMinMaxMeasurement.
XSM_ATR_TEMP_UPPER
High user Temperature.
Referenced by SysMonIntrExample, SysMonPolledExample.
XSM_ATR_VCCINT_UPPER
VCCINT high voltage limit.
Referenced by XSysMon_SelfTest.
XSM_ATR_VCCAUX_UPPER
VCCAUX high voltage limit.
Referenced by SysMonIntrExample, SysMonPolledExample.
XSM_ATR_OT_UPPER
Lower Over Temperature limit.
XSM_ATR_TEMP_LOWER
Low user Temperature.
Referenced by SysMonIntrExample, SysMonPolledExample.
XSM_ATR_VCCINT_LOWER
VCCINT low voltage limit.
XSM_ATR_VCCAUX_LOWER
VCCAUX low voltage limit.
Referenced by SysMonIntrExample, SysMonPolledExample.
XSM_ATR_OT_LOWER
Lower Over Temperature limit.
XSM_ATR_VBRAM_UPPER
VBRAM high voltage limit.
XSM_ATR_VCCPINT_UPPER
VCCPINT Upper Alarm, Zynq.
XSM_ATR_VCCPAUX_UPPER
VCCPAUX Upper Alarm, Zynq.
XSM_ATR_VCCPDRO_UPPER
VCCPDRO Upper Alarm, Zynq.
XSM_ATR_VBRAM_LOWER
VRBAM Lower Alarm, 7 Series and Zynq.
XSM_ATR_VCCPINT_LOWER
VCCPINT Lower Alarm, Zynq.
XSM_ATR_VCCPAUX_LOWER
VCCPAUX Lower Alarm, Zynq.
XSM_ATR_VCCPDRO_LOWER
VCCPDRO Lower Alarm, Zynq.
XSM_ATR_VUSR0_UPPER
VUSER0 Upper Alarm, Ultrascale.
XSM_ATR_VUSR1_UPPER
VUSER1 Upper Alarm, Ultrascale.
XSM_ATR_VUSR2_UPPER
VUSER2 Upper Alarm, Ultrascale.
XSM_ATR_VUSR3_UPPER
VUSER3 Upper Alarm, Ultrascale.
Referenced by XSysMon_GetAlarmThreshold, XSysMon_SetAlarmThreshold.
XSM_ATR_VUSR0_LOWER
VUSER0 Lower Alarm, Ultrascale.
Referenced by XSysMon_GetAlarmThreshold, XSysMon_SetAlarmThreshold.
XSM_ATR_VUSR1_LOWER
VUSER1 Lower Alarm, Ultrascale.
XSM_ATR_VUSR2_LOWER
VUSER2 Lower Alarm, Ultrascale.
XSM_ATR_VUSR3_LOWER
VUSER3 Lower Alarm, Ultrascale.
Referenced by XSysMon_GetAlarmThreshold, XSysMon_SetAlarmThreshold.
XSM_AVG_0_SAMPLES
No Averaging.
XSM_AVG_16_SAMPLES
Average 16 samples.
Referenced by SysMonAuxPolledExample, SysMonIntrExample, SysMonPolledExample.
XSM_AVG_64_SAMPLES
Average 64 samples.
XSM_AVG_256_SAMPLES
Average 256 samples.
Referenced by XSysMon_SetAvg.
XSM_SEQ_MODE_SAFE
Default Safe Mode.
Referenced by SysMonAuxPolledExample, SysMonIntrExample, SysMonPolledExample, XSysMon_SetSeqAcqTime, XSysMon_SetSeqAvgEnables, XSysMon_SetSeqChEnables, XSysMon_SetSeqInputMode.
XSM_SEQ_MODE_ONEPASS
Onepass through Sequencer.
XSM_SEQ_MODE_CONTINPASS
Continuous Cycling Seqquencer.
Referenced by SysMonAuxPolledExample, SysMonIntrExample, SysMonPolledExample.
XSM_SEQ_MODE_SINGCHAN
Single channel - No Sequencing.
Referenced by XSysMon_SetSingleChParams.
XSM_SEQ_MODE_SIMUL
Simultaneous Cycling Sequencer, 7 Series and Zynq XADC only.
Referenced by XSysMon_SetSequencerMode.
XSM_SEQ_MODE_INDEPENDENT
Independent ADC Sequencer, 7 Series and Zynq XADC only.
Referenced by XSysMon_SetSequencerMode.
XSYSMON_H
XSM_CH_CALIBRATION
XSM_ATR_BRAM_UPPER
XSM_ATR_BRAM_LOWER
XSysMon_IsEventSamplingModeSet
This macro checks if the SysMonitor/ADC device is in Event Sampling mode.
InstancePtr is a pointer to the XSysMon instance. TRUE if the device is in Event Sampling Mode.FALSE if the device is in Continuous Sampling Mode. C-Style signature: int XSysMon_IsEventSamplingMode(XSysMon *InstancePtr);
XSysMon_IsDrpBusy
This macro checks if the Dynamic Reconfiguration Port (DRP) transaction from the JTAG is in progress.
InstancePtr is a pointer to the XSysMon instance. TRUE if the DRP transaction from JTAG is in Progress.FALSE if there is no DRP transaction from the JTAG. C-Style signature: int XSysMon_IsDrpBusy(XSysMon *InstancePtr);
XSysMon_IsDrpLocked
This macro checks if the Dynamic Reconfiguration Port (DRP) is locked by the JTAG.
InstancePtr is a pointer to the XSysMon instance. TRUE if the DRP is locked by the JTAG.FALSE if the DRP is not locked by the JTAG. C-Style signature: int XSysMon_IsDrpLocked(XSysMon *InstancePtr);
XSysMon_RawToTemperature
This macro converts System Monitor/ADC Raw Data to Temperature(centigrades).
AdcData is the SysMon Raw ADC Data. The Temperature in centigrades. C-Style signature: float XSysMon_RawToTemperature(u32 AdcData);
Referenced by SysMonIntrExample, SysMonPolledExample.
XSysMon_RawToVoltage
This macro converts System Monitor/ADC Raw Data to Voltage(volts).
AdcData is the System Monitor/ADC Raw Data. The Voltage in volts. C-Style signature: float XSysMon_RawToVoltage(u32 AdcData);
Referenced by SysMonAuxPolledExample.
XSysMon_TemperatureToRaw
This macro converts Temperature in centigrades to System Monitor/ADC Raw Data.
Temperature is the Temperature in centigrades to be converted to System Monitor/ADC Raw Data. The System Monitor/ADC Raw Data. C-Style signature: int XSysMon_TemperatureToRaw(float Temperature);
XSysMon_VoltageToRaw
This macro converts Voltage in Volts to System Monitor/ADC Raw Data.
Voltage is the Voltage in volts to be converted to System Monitor/ADC Raw Data. The System Monitor/ADC Raw Data. C-Style signature: int XSysMon_VoltageToRaw(float Voltage);
XSysMon_Config * XSysMon_LookupConfig(u32 BaseAddress)
Functions in xsysmon_sinit.c.
This function looks up the device configuration based on the unique device ID.The table XSysMon_ConfigTable contains the configuration info for each device in the system. DeviceId contains the ID of the device for which the device configuration pointer is to be returned. A pointer to the configuration found.NULL if the specified device ID was not found. None.
Referenced by SysMonAuxPolledExample, SysMonIntrExample, SysMonPolledExample.
int XSysMon_CfgInitialize(XSysMon *InstancePtr, XSysMon_Config *ConfigPtr, UINTPTR EffectiveAddr)
This function initializes a specific XSysMon device/instance.
Functions in xsysmon.c.This function must be called prior to using the System Monitor/ADC device. InstancePtr is a pointer to the XSysMon instance. ConfigPtr points to the XSysMon device configuration structure. EffectiveAddr is the device base address in the virtual memory address space. If the address translation is not used then the physical address is passed. Unexpected errors may occur if the address mapping is changed after this function is invoked. XST_SUCCESS if successful. The user needs to first call the XSysMon_LookupConfig() API which returns the Configuration structure pointer which is passed as a parameter to the XSysMon_CfgInitialize() API.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSysMon::Mask, XSM_CONVST_WAITCYCLES_DEFAULT, XSM_CONVST_WAITCYCLES_SHIFT, XSysMon_Reset.
Referenced by SysMonAuxPolledExample, SysMonIntrExample, SysMonPolledExample.
void XSysMon_Reset(XSysMon *InstancePtr)
This function forces the software reset of the complete SystemMonitor/ADC Hard Macro and the SYSMON ADC Core Logic.
InstancePtr is a pointer to the XSysMon instance. None. The Control registers in the SystemMonitor/ADC Hard Macro are not affected by this reset, only the Status registers are reset. Refer to the device data sheet for the device status and register values after the reset. Use the XSysMon_ResetAdc() to reset only the SystemMonitor/ADC Hard Macro.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSM_SRR_IPRST_MASK, XSM_SRR_OFFSET, XSysMon_WriteReg.
Referenced by XSysMon_CfgInitialize, XSysMon_SelfTest.
u32 XSysMon_GetStatus(XSysMon *InstancePtr)
The functions reads the contents of the Status Register.
InstancePtr is a pointer to the XSysMon instance. A 32-bit value representing the contents of the Status Register. Use the XSM_SR_*_MASK constants defined in xsysmon_hw.h to interpret the returned value. None.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSM_SR_OFFSET, XSysMon_ReadReg.
Referenced by SysMonAuxPolledExample, SysMonIntrExample, SysMonPolledExample.
u32 XSysMon_GetAlarmOutputStatus(XSysMon *InstancePtr)
This function reads the contents of Alarm Output Register.
InstancePtr is a pointer to the XSysMon instance. A 32-bit value read from the Alarm Output Register. Use the XSM_AOR_*_MASK constants defined in xsysmon_hw.h to interpret the value. None.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSM_AOR_ALARM_ALL_MASK, XSM_AOR_OFFSET, XSysMon_ReadReg.
Referenced by SysMonPolledExample.
void XSysMon_StartAdcConversion(XSysMon *InstancePtr)
This function starts the ADC conversion in the Single Channel event driven sampling mode.
The EOC bit in Status Register will be set once the conversion is finished. Refer to the device specification for more details. InstancePtr is a pointer to the XSysMon instance. None. The default state of the CONVST bit is a logic 0. The conversion is started when the CONVST bit is set to 1 from 0. This bit is cleared in this function so that the next conversion can be started by setting this bit.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSysMon::Mask, XSM_CONVST_CONVST_MASK, XSM_CONVST_OFFSET, XSysMon_WriteReg.
void XSysMon_ResetAdc(XSysMon *InstancePtr)
This function resets the SystemMonitor/ADC Hard Macro in the device.
InstancePtr is a pointer to the XSysMon instance. None. The Control registers in the SystemMonitor/ADC Hard Macro are not affected by this reset, only the Status registers are reset. This reset causes the ADC to begin with a new conversion. Refer to the device data sheet for the device status and register values after the reset. Use the XSysMon_Reset() API to reset both the SystemMonitor/ADC Hard Macro and the SYSMON ADC Core Logic.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSM_ARR_OFFSET, XSM_ARR_RST_MASK, XSysMon_WriteReg.
u16 XSysMon_GetAdcData(XSysMon *InstancePtr, u8 Channel)
Get the ADC converted data for the specified channel.
InstancePtr is a pointer to the XSysMon instance. Channel is the channel number. Use the XSM_CH_* defined in the file xsysmon.h. The valid channels are 0 to 5 and 16 to 31 for all the device families. Channel 6 is valid for 7 Series and Zynq. Channel 13, 14, 15 are valid for Zynq. 32 to 35 are valid for Ultrascale. A 16-bit value representing the ADC converted data for the specified channel. The System Monitor/ADC device guarantees a 10 bit resolution for the ADC converted data and data is the 10 MSB bits of the 16 data read from the device. The channels 7,8,9 are used for calibration of the device and hence there is no associated data with this channel. Please make sure that the proper channel number is passed.
References XSysMon::IsReady, XSM_CH_AUX_MAX, XSM_CH_VBRAM, XSM_CH_VCCPINT, XSM_CH_VUSR0, XSM_CH_VUSR3, XSM_TEMP_OFFSET, XSM_VUSR0_OFFSET, XSysMon_ReadReg.
Referenced by SysMonAuxPolledExample, SysMonIntrExample, SysMonPolledExample.
u16 XSysMon_GetCalibCoefficient(XSysMon *InstancePtr, u8 CoeffType)
This function gets the calibration coefficient data for the specified parameter.
InstancePtr is a pointer to the XSysMon instance. CoeffType specifies the calibration coefficient to be read. Use XSM_CALIB_* constants defined in xsysmon.h to specify the calibration coefficient to be read. A 16-bit value representing the calibration coefficient. The System Monitor/ADC device guarantees a 10 bit resolution for the ADC converted data and data is the 10 MSB bits of the 16 data read from the device. None.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSM_CALIB_GAIN_ERROR_COEFF, XSM_SUPPLY_CALIB_OFFSET, XSysMon_ReadReg.
u16 XSysMon_GetMinMaxMeasurement(XSysMon *InstancePtr, u8 MeasurementType)
This function reads the Minimum/Maximum measurement for one of the following parameters :
- Minimum Temperature (XSM_MIN_TEMP) - All families - Minimum VCCINT (XSM_MIN_VCCINT) - All families - Minimum VCCAUX (XSM_MIN_VCCAUX) - All families - Maximum Temperature (XSM_MAX_TEMP) - All families - Maximum VCCINT (XSM_MAX_VCCINT) - All families - Maximum VCCAUX (XSM_MAX_VCCAUX) - All families - Maximum VCCBRAM (XSM_MAX_VCCBRAM) - 7 series and Zynq only - Minimum VCCBRAM (XSM_MIN_VCCBRAM) - 7 series and Zynq only - Maximum VCCPINT (XSM_MAX_VCCPINT) - Zynq only - Maximum VCCPAUX (XSM_MAX_VCCPAUX) - Zynq only - Maximum VCCPDRO (XSM_MAX_VCCPDRO) - Zynq only - Minimum VCCPINT (XSM_MIN_VCCPINT) - Zynq only - Minimum VCCPAUX (XSM_MIN_VCCPAUX) - Zynq only - Minimum VCCPDRO (XSM_MIN_VCCPDRO) - Zynq only - Maximum VUSER0 (XSM_MAX_VUSR0) - Ultrascale - Maximum VUSER1 (XSM_MAX_VUSR1) - Ultrascale - Maximum VUSER2 (XSM_MAX_VUSR2) - Ultrascale - Maximum VUSER3 (XSM_MAX_VUSR3) - Ultrascale - Minimum VUSER0 (XSM_MIN_VUSR0) - Ultrascale - Minimum VUSER1 (XSM_MIN_VUSR1) - Ultrascale - Minimum VUSER2 (XSM_MIN_VUSR2) - Ultrascale - Minimum VUSER3 (XSM_MIN_VUSR3) - Ultrascale InstancePtr is a pointer to the XSysMon instance. MeasurementType specifies the parameter for which the Minimum/Maximum measurement has to be read. Use XSM_MAX_* and XSM_MIN_* constants defined in xsysmon.h to specify the data to be read. A 16-bit value representing the maximum/minimum measurement for specified parameter. The System Monitor/ADC device guarantees a 10 bit resolution for the ADC converted data and data is the 10 MSB bits of 16 bit data read from the device.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSM_MAX_TEMP_OFFSET, XSM_MAX_VCCPDRO, XSM_MAX_VUSR0, XSM_MAX_VUSR3, XSM_MIN_VCCPDRO, XSM_MIN_VCCPINT, XSM_MIN_VUSR0, XSM_MIN_VUSR3, XSysMon_ReadReg.
Referenced by SysMonPolledExample.
void XSysMon_SetAvg(XSysMon *InstancePtr, u8 Average)
This function sets the number of samples of averaging that is to be done for all the channels in both the single channel mode and sequence mode of operations.
InstancePtr is a pointer to the XSysMon instance. Average is the number of samples of averaging programmed to the Configuration Register 0. Use the XSM_AVG_* definitions defined in xsysmon.h file : XSM_AVG_0_SAMPLES for no averagingXSM_AVG_16_SAMPLES for 16 samples of averagingXSM_AVG_64_SAMPLES for 64 samples of averagingXSM_AVG_256_SAMPLES for 256 samples of averaging None. None.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSM_AVG_256_SAMPLES, XSM_CFR0_AVG_SHIFT, XSM_CFR0_AVG_VALID_MASK, XSM_CFR0_OFFSET, XSysMon_ReadReg, XSysMon_WriteReg.
Referenced by SysMonAuxPolledExample, SysMonIntrExample, SysMonPolledExample.
u8 XSysMon_GetAvg(XSysMon *InstancePtr)
This function returns the number of samples of averaging configured for all the channels in the Configuration Register 0.
InstancePtr is a pointer to the XSysMon instance. The averaging read from the Configuration Register 0 is returned. Use the XSM_AVG_* bit definitions defined in xsysmon.h file to interpret the returned value : XSM_AVG_0_SAMPLES means no averagingXSM_AVG_16_SAMPLES means 16 samples of averagingXSM_AVG_64_SAMPLES means 64 samples of averagingXSM_AVG_256_SAMPLES means 256 samples of averaging None.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSM_CFR0_AVG_SHIFT, XSM_CFR0_AVG_VALID_MASK, XSM_CFR0_OFFSET, XSysMon_ReadReg.
int XSysMon_SetSingleChParams(XSysMon *InstancePtr, u8 Channel, int IncreaseAcqCycles, int IsEventMode, int IsDifferentialMode)
The function sets the given parameters in the Configuration Register 0 in the single channel mode.
InstancePtr is a pointer to the XSysMon instance. Channel is the channel number for conversion. The valid channels are 0 to 5, 8, and 16 to 31. Channel 6 is valid for 7 series and Zynq XADC. Channel 32 to 35 are valid for Ultrascale. IncreaseAcqCycles is a boolean parameter which specifies whether the Acquisition time for the external channels has to be increased to 10 ADCCLK cycles (specify TRUE) or remain at the default 4 ADCCLK cycles (specify FALSE). This parameter is only valid for the external channels. IsEventMode is a boolean parameter that specifies continuous sampling (specify FALSE) or event driven sampling mode (specify TRUE) for the given channel. IsDifferentialMode is a boolean parameter which specifies unipolar(specify FALSE) or differential mode (specify TRUE) for the analog inputs. The input mode is only valid for the external channels. XST_SUCCESS if the given values were written successfully to the Configuration Register 0.XST_FAILURE if the channel sequencer is enabled or the input parameters are not valid for the selected channel. The number of samples for the averaging for all the channels is set by using the function XSysMon_SetAvg.The calibration of the device is done by doing a ADC conversion on the calibration channel(channel 8). The input parameters IncreaseAcqCycles, IsDifferentialMode and IsEventMode are not valid for this channel.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSM_CFR0_ACQ_MASK, XSM_CFR0_AVG_VALID_MASK, XSM_CFR0_CHANNEL_MASK, XSM_CFR0_DU_MASK, XSM_CFR0_EC_MASK, XSM_CFR0_OFFSET, XSM_CH_AUX_MAX, XSM_CH_AUX_MIN, XSM_CH_VPVN, XSM_CH_VREFN, XSM_CH_VUSR0, XSM_CH_VUSR3, XSM_SEQ_MODE_SINGCHAN, XSysMon_GetSequencerMode, XSysMon_ReadReg, XSysMon_WriteReg.
void XSysMon_SetAlarmEnables(XSysMon *InstancePtr, u32 AlmEnableMask)
This function enables the alarm outputs for the specified alarms in the Configuration Registers 1 and 3:
- OT for Over Temperature (XSM_CFR_OT_MASK) - ALM0 for On board Temperature (XSM_CFR_ALM_TEMP_MASK) - ALM1 for VCCINT (XSM_CFR_ALM_VCCINT_MASK) - ALM2 for VCCAUX (XSM_CFR_ALM_VCCAUX_MASK) - ALM3 for VBRAM (XSM_CFR_ALM_VBRAM_MASK)for 7 Series and Zynq - ALM4 for VCCPINT (XSM_CFR_ALM_VCCPINT_MASK) for Zynq - ALM5 for VCCPAUX (XSM_CFR_ALM_VCCPAUX_MASK) for Zynq - ALM6 for VCCPDRO (XSM_CFR_ALM_VCCPDRO_MASK) for Zynq - ALM8 for VUSER0 (XSM_CFR_ALM_VUSR0_MASK) for Ultrascale - ALM9 for VUSER1 (XSM_CFR_ALM_VUSR1_MASK) for Ultrascale - ALM10 for VUSER2 (XSM_CFR_ALM_VUSR2_MASK) for Ultrascale - ALM11 for VUSER3 (XSM_CFR_ALM_VUSR3_MASK) for Ultrascale InstancePtr is a pointer to the XSysMon instance. AlmEnableMask is the bit-mask of the alarm outputs to be enabled in the Configuration Register 1. Bit positions of 1 will be enabled. Bit positions of 0 will be disabled. This mask is formed by OR'ing XSM_CFR_ALM_*_MASK, XSM_CFR_ALM_*_MASK and XSM_CFR_OT_MASK masks defined in xsysmon_hw.h. None. The implementation of the alarm enables in the Configuration register 1 is such that the alarms for bit positions of 1 will be disabled and alarms for bit positions of 0 will be enabled. The alarm outputs specified by the AlmEnableMask are negated before writing to the Configuration Register 1.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSM_CFR1_ALM_ALL_MASK, XSM_CFR1_OFFSET, XSM_CFR3_ALM_ALL_MASK, XSysMon_ReadReg, XSysMon_WriteReg.
Referenced by SysMonIntrExample, SysMonPolledExample.
u32 XSysMon_GetAlarmEnables(XSysMon *InstancePtr)
This function gets the status of the alarm output enables in the Configuration Register 1.
InstancePtr is a pointer to the XSysMon instance. This is the bit-mask of the enabled alarm outputs in the Configuration Register 1. Use the masks XSM_CFR_ALM_*, XSM_CFR_ALM*_* and XSM_CFR_OT_MASK defined in xsysmon_hw.h to interpret the returned value. Bit positions of 1 indicate that the alarm output is enabled. Bit positions of 0 indicate that the alarm output is disabled.The implementation of the alarm enables in the Configuration register 1 is such that alarms for the bit positions of 1 will be disabled and alarms for bit positions of 0 will be enabled. The enabled alarm outputs returned by this function is the negated value of the the data read from the Configuration Register 1.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSM_CFR1_ALM_ALL_MASK, XSM_CFR1_OFFSET, XSM_CFR3_ALM_ALL_MASK, XSysMon_ReadReg.
void XSysMon_SetCalibEnables(XSysMon *InstancePtr, u16 Calibration)
This function enables the specified calibration in the Configuration Register 1 :
- XSM_CFR1_CAL_ADC_OFFSET_MASK : Calibration 0 -ADC offset correction - XSM_CFR1_CAL_ADC_GAIN_OFFSET_MASK : Calibration 1 -ADC gain and offset correction - XSM_CFR1_CAL_PS_OFFSET_MASK : Calibration 2 -Power Supply sensor offset correction - XSM_CFR1_CAL_PS_GAIN_OFFSET_MASK : Calibration 3 -Power Supply sensor gain and offset correction - XSM_CFR1_CAL_DISABLE_MASK : No Calibration InstancePtr is a pointer to the XSysMon instance. Calibration is the Calibration to be applied. Use XSM_CFR1_CAL*_* bits defined in xsysmon_hw.h. Multiple calibrations can be enabled at a time by oring the XSM_CFR1_CAL_ADC_* and XSM_CFR1_CAL_PS_* bits. Calibration can be disabled by specifying XSM_CFR1_CAL_DISABLE_MASK; None. None.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSM_CFR1_CAL_ADC_OFFSET_MASK, XSM_CFR1_CAL_DISABLE_MASK, XSM_CFR1_CAL_VALID_MASK, XSM_CFR1_OFFSET, XSysMon_ReadReg, XSysMon_WriteReg.
u16 XSysMon_GetCalibEnables(XSysMon *InstancePtr)
This function reads the value of the calibration enables from the Configuration Register 1.
InstancePtr is a pointer to the XSysMon instance. The value of the calibration enables in the Configuration Register 1 : XSM_CFR1_CAL_ADC_OFFSET_MASK : ADC offset correctionXSM_CFR1_CAL_ADC_GAIN_OFFSET_MASK : ADC gain and offset correctionXSM_CFR1_CAL_PS_OFFSET_MASK : Power Supply sensor offset correctionXSM_CFR1_CAL_PS_GAIN_OFFSET_MASK : Power Supply sensor gain and offset correctionXSM_CFR1_CAL_DISABLE_MASK : No Calibration None.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSM_CFR1_CAL_VALID_MASK, XSM_CFR1_OFFSET, XSysMon_ReadReg.
void XSysMon_SetSequencerMode(XSysMon *InstancePtr, u8 SequencerMode)
This function sets the specified Channel Sequencer Mode in the Configuration Register 1 :
- Default safe mode (XSM_SEQ_MODE_SAFE) - One pass through sequence (XSM_SEQ_MODE_ONEPASS) - Continuous channel sequencing (XSM_SEQ_MODE_CONTINPASS) - Single Channel/Sequencer off (XSM_SEQ_MODE_SINGCHAN) - Simultaneous sampling mode (XSM_SEQ_MODE_SIMUL) - Independent mode (XSM_SEQ_MODE_INDEPENDENT) InstancePtr is a pointer to the XSysMon instance. SequencerMode is the sequencer mode to be set. Use XSM_SEQ_MODE_* bits defined in xsysmon.h. None. Only one of the modes can be enabled at a time.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSM_CFR1_OFFSET, XSM_CFR1_SEQ_SHIFT, XSM_CFR1_SEQ_VALID_MASK, XSM_SEQ_MODE_INDEPENDENT, XSM_SEQ_MODE_SIMUL, XSysMon_ReadReg, XSysMon_WriteReg.
Referenced by SysMonAuxPolledExample, SysMonIntrExample, SysMonPolledExample.
u8 XSysMon_GetSequencerMode(XSysMon *InstancePtr)
This function gets the channel sequencer mode from the Configuration Register 1.
InstancePtr is a pointer to the XSysMon instance. The channel sequencer mode : XSM_SEQ_MODE_SAFE : Default safe modeXSM_SEQ_MODE_ONEPASS : One pass through sequenceXSM_SEQ_MODE_CONTINPASS : Continuous channel sequencingXSM_SEQ_MODE_SINGCHAN : Single channel/Sequencer offXSM_SEQ_MODE_SIMUL : Simultaneous sampling modeXSM_SEQ_MODE_INDEPENDENT : Independent mode None.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSM_CFR1_OFFSET, XSM_CFR1_SEQ_SHIFT, XSM_CFR1_SEQ_VALID_MASK, XSysMon_ReadReg.
Referenced by XSysMon_SetSeqAcqTime, XSysMon_SetSeqAvgEnables, XSysMon_SetSeqChEnables, XSysMon_SetSeqInputMode, XSysMon_SetSingleChParams.
void XSysMon_SetSequencerEvent(XSysMon *InstancePtr, int IsEventMode)
The function enables the Event mode or Continuous mode in the sequencer mode.
InstancePtr is a pointer to the XSysMon instance. IsEventMode is a boolean parameter that specifies continuous sampling (specify FALSE) or event driven sampling mode (specify TRUE) for the given channel. None. The Event mode is only available in 7 Series XADC and Zynq. This API should be used only with 7 Series XADC and Zynq .
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSM_CFR0_EC_MASK, XSM_CFR0_OFFSET, XSysMon_ReadReg, XSysMon_WriteReg.
void XSysMon_SetExtenalMux(XSysMon *InstancePtr, u8 Channel)
The function enables the external mux and connects a channel to the mux.
InstancePtr is a pointer to the XSysMon instance. Channel is the channel number used to connect to the external Mux. The valid channels are 0 to 6, 8, and 16 to 31. XST_SUCCESS if the given values were written successfully to the Configuration Register 0.XST_FAILURE if the channel sequencer is enabled or the input parameters are not valid for the selected channel. The External Mux is only available in 7 Series and Zynq XADC. This API should be used only with 7 Series and Zynq XADC.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSM_CFR0_CHANNEL_MASK, XSM_CFR0_MUX_MASK, XSM_CFR0_OFFSET, XSM_CH_AUX_MAX, XSM_CH_AUX_MIN, XSM_CH_VREFN, XSysMon_ReadReg, XSysMon_WriteReg.
Referenced by SysMonAuxPolledExample.
void XSysMon_SetAdcClkDivisor(XSysMon *InstancePtr, u8 Divisor)
The function sets the frequency of the ADCCLK by configuring the DCLK to ADCCLK ratio in the Configuration Register #2.
InstancePtr is a pointer to the XSysMon instance. Divisor is clock divisor used to derive ADCCLK from DCLK. Valid values of the divisor are 8 to 255 for V5 SysMon.0 to 255 for V6/7 Series and Zynq XADC. Values 0, 1, 2 are all mapped to 2. Refer to the device specification for more details. None. - The ADCCLK is an internal clock used by the ADC and is synchronized to the DCLK clock. The ADCCLK is equal to DCLK divided by the user selection in the Configuration Register 2. There is no Assert on the minimum value of the Divisor. Users must take care such that the minimum value of Divisor used is 8, in case of V5 SysMon.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSM_CFR2_CD_SHIFT, XSM_CFR2_OFFSET, XSysMon_WriteReg.
Referenced by SysMonAuxPolledExample, SysMonIntrExample, SysMonPolledExample.
u8 XSysMon_GetAdcClkDivisor(XSysMon *InstancePtr)
The function gets the ADCCLK divisor from the Configuration Register 2.
InstancePtr is a pointer to the XSysMon instance. The divisor read from the Configuration Register 2. The ADCCLK is an internal clock used by the ADC and is synchronized to the DCLK clock. The ADCCLK is equal to DCLK divided by the user selection in the Configuration Register 2.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSM_CFR2_CD_SHIFT, XSM_CFR2_OFFSET, XSysMon_ReadReg.
int XSysMon_SetSeqChEnables(XSysMon *InstancePtr, u64 ChEnableMask)
This function enables the specified channels in the ADC Channel Selection Sequencer Registers.
The sequencer must be in the Safe Mode before writing to these registers. InstancePtr is a pointer to the XSysMon instance. ChEnableMask is the bit mask of all the channels to be enabled. Use XSM_SEQ_CH_* defined in xsysmon_hw.h to specify the Channel numbers. Bit masks of 1 will be enabled and bit mask of 0 will be disabled. The ChEnableMask is a 64 bit mask that is written to the three 16 bit ADC Channel Selection Sequencer Registers. XST_SUCCESS if the given values were written successfully to the ADC Channel Selection Sequencer Registers.XST_FAILURE if the channel sequencer is enabled. None.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSM_SEQ00_CH_VALID_MASK, XSM_SEQ00_OFFSET, XSM_SEQ01_CH_VALID_MASK, XSM_SEQ01_OFFSET, XSM_SEQ08_CH_VALID_MASK, XSM_SEQ08_OFFSET, XSM_SEQ_CH_AUX_SHIFT, XSM_SEQ_CH_VUSR_SHIFT, XSM_SEQ_MODE_SAFE, XSysMon_GetSequencerMode, XSysMon_WriteReg.
Referenced by SysMonAuxPolledExample, SysMonIntrExample, SysMonPolledExample.
u64 XSysMon_GetSeqChEnables(XSysMon *InstancePtr)
This function gets the channel enable bits status from the ADC Channel Selection Sequencer Registers.
InstancePtr is a pointer to the XSysMon instance. Gets the channel enable bits. Use XSM_SEQ_CH_* defined in xsysmon_hw.h to interpret the Channel numbers. Bit masks of 1 are the channels that are enabled and bit mask of 0 are the channels that are disabled.None. None.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSM_SEQ00_CH_VALID_MASK, XSM_SEQ00_OFFSET, XSM_SEQ01_CH_VALID_MASK, XSM_SEQ01_OFFSET, XSM_SEQ08_CH_VALID_MASK, XSM_SEQ08_OFFSET, XSM_SEQ_CH_AUX_SHIFT, XSM_SEQ_CH_VUSR_SHIFT, XSysMon_ReadReg.
int XSysMon_SetSeqAvgEnables(XSysMon *InstancePtr, u64 AvgEnableChMask)
This function enables the averaging for the specified channels in the ADC Channel Averaging Enable Sequencer Registers.
The sequencer must be in the Safe Mode before writing to these registers. InstancePtr is a pointer to the XSysMon instance. AvgEnableChMask is the bit mask of all the channels for which averaging is to be enabled. Use XSM_SEQ_CH__* defined in xsysmon_hw.h to specify the Channel numbers. Averaging will be enabled for bit masks of 1 and disabled for bit mask of 0. The AvgEnableChMask is a 64 bit mask that is written to the three 16 bit ADC Channel Averaging Enable Sequencer Registers. XST_SUCCESS if the given values were written successfully to the ADC Channel Averaging Enables Sequencer Registers.XST_FAILURE if the channel sequencer is enabled. None.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSM_SEQ02_CH_VALID_MASK, XSM_SEQ02_OFFSET, XSM_SEQ03_CH_VALID_MASK, XSM_SEQ03_OFFSET, XSM_SEQ09_CH_VALID_MASK, XSM_SEQ09_OFFSET, XSM_SEQ_CH_AUX_SHIFT, XSM_SEQ_CH_VUSR_SHIFT, XSM_SEQ_MODE_SAFE, XSysMon_GetSequencerMode, XSysMon_WriteReg.
Referenced by SysMonAuxPolledExample, SysMonIntrExample, SysMonPolledExample.
u64 XSysMon_GetSeqAvgEnables(XSysMon *InstancePtr)
This function returns the channels for which the averaging has been enabled in the ADC Channel Averaging Enables Sequencer Registers.
InstancePtr is a pointer to the XSysMon instance. The status of averaging (enabled/disabled) for all the channels. Use XSM_SEQ_CH__* defined in xsysmon_hw.h to interpret the Channel numbers. Bit masks of 1 are the channels for which averaging is enabled and bit mask of 0 are the channels for averaging is disabled. None.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSM_SEQ02_CH_VALID_MASK, XSM_SEQ02_OFFSET, XSM_SEQ03_CH_VALID_MASK, XSM_SEQ03_OFFSET, XSM_SEQ09_CH_VALID_MASK, XSM_SEQ09_OFFSET, XSM_SEQ_CH_AUX_SHIFT, XSM_SEQ_CH_VUSR_SHIFT, XSysMon_ReadReg.
int XSysMon_SetSeqInputMode(XSysMon *InstancePtr, u32 InputModeChMask)
This function sets the Analog input mode for the specified channels in the ADC Channel Analog-Input Mode Sequencer Registers.
The sequencer must be in the Safe Mode before writing to these registers. InstancePtr is a pointer to the XSysMon instance. InputModeChMask is the bit mask of all the channels for which the input mode is differential mode. Use XSM_SEQ_CH__* defined in xsysmon_hw.h to specify the channel numbers. Differential input mode will be set for bit masks of 1 and unipolar input mode for bit masks of 0. The InputModeChMask is a 32 bit mask that is written to the two 16 bit ADC Channel Analog-Input Mode Sequencer Registers. XST_SUCCESS if the given values were written successfully to the ADC Channel Analog-Input Mode Sequencer Registers.XST_FAILURE if the channel sequencer is enabled. None.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSM_SEQ04_CH_VALID_MASK, XSM_SEQ04_OFFSET, XSM_SEQ05_CH_VALID_MASK, XSM_SEQ05_OFFSET, XSM_SEQ_CH_AUX_SHIFT, XSM_SEQ_MODE_SAFE, XSysMon_GetSequencerMode, XSysMon_WriteReg.
Referenced by SysMonAuxPolledExample, SysMonIntrExample, SysMonPolledExample.
u32 XSysMon_GetSeqInputMode(XSysMon *InstancePtr)
This function gets the Analog input mode for all the channels from the ADC Channel Analog-Input Mode Sequencer Registers.
InstancePtr is a pointer to the XSysMon instance. The input mode for all the channels. Use XSM_SEQ_CH_* defined in xsysmon_hw.h to interpret the Channel numbers. Bit masks of 1 are the channels for which input mode is differential and bit mask of 0 are the channels for which input mode is unipolar. None.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSM_SEQ04_CH_VALID_MASK, XSM_SEQ04_OFFSET, XSM_SEQ05_CH_VALID_MASK, XSM_SEQ05_OFFSET, XSM_SEQ_CH_AUX_SHIFT, XSysMon_ReadReg.
int XSysMon_SetSeqAcqTime(XSysMon *InstancePtr, u32 AcqCyclesChMask)
This function sets the number of Acquisition cycles in the ADC Channel Acquisition Time Sequencer Registers.
The sequencer must be in the Safe Mode before writing to these registers. InstancePtr is a pointer to the XSysMon instance. AcqCyclesChMask is the bit mask of all the channels for which the number of acquisition cycles is to be extended. Use XSM_SEQ_CH__* defined in xsysmon_hw.h to specify the Channel numbers. Acquisition cycles will be extended to 10 ADCCLK cycles for bit masks of 1 and will be the default 4 ADCCLK cycles for bit masks of 0. The AcqCyclesChMask is a 32 bit mask that is written to the two 16 bit ADC Channel Acquisition Time Sequencer Registers. XST_SUCCESS if the given values were written successfully to the Channel Sequencer Registers.XST_FAILURE if the channel sequencer is enabled. None.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSM_SEQ06_CH_VALID_MASK, XSM_SEQ06_OFFSET, XSM_SEQ07_CH_VALID_MASK, XSM_SEQ07_OFFSET, XSM_SEQ_CH_AUX_SHIFT, XSM_SEQ_MODE_SAFE, XSysMon_GetSequencerMode, XSysMon_WriteReg.
Referenced by SysMonAuxPolledExample, SysMonIntrExample, SysMonPolledExample.
u32 XSysMon_GetSeqAcqTime(XSysMon *InstancePtr)
This function gets the status of acquisition from the ADC Channel Acquisition Time Sequencer Registers.
InstancePtr is a pointer to the XSysMon instance. The acquisition time for all the channels. Use XSM_SEQ_CH__* defined in xsysmon_hw.h to interpret the Channel numbers. Bit masks of 1 are the channels for which acquisition cycles are extended and bit mask of 0 are the channels for which acquisition cycles are not extended. None.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSM_SEQ06_CH_VALID_MASK, XSM_SEQ06_OFFSET, XSM_SEQ07_CH_VALID_MASK, XSM_SEQ07_OFFSET, XSM_SEQ_CH_AUX_SHIFT, XSysMon_ReadReg.
void XSysMon_SetAlarmThreshold(XSysMon *InstancePtr, u8 AlarmThrReg, u16 Value)
This functions sets the contents of the given Alarm Threshold Register.
InstancePtr is a pointer to the XSysMon instance. AlarmThrReg is the index of an Alarm Threshold Register to be set. Use XSM_ATR_* constants defined in xsysmon.h to specify the index. Value is the 16-bit threshold value to write into the register. None. Over Temperature upper threshold is programmable only in V6, 7 Series/Zynq XADC and UltraScale. BRAM high and low voltage threshold registers are available only in 7 Series XADC and UltraScale. VUSER0 to VUSER3 threshold registers are available only in UltraScale. All the remaining Alarm Threshold registers specified by the constants XSM_ATR_*, are available in all the families of the Sysmon.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSM_ATR_TEMP_UPPER_OFFSET, XSM_ATR_VUSR0_LOWER, XSM_ATR_VUSR3_LOWER, XSM_ATR_VUSR3_UPPER, XSysMon_WriteReg.
Referenced by SysMonIntrExample, SysMonPolledExample, XSysMon_SelfTest.
u16 XSysMon_GetAlarmThreshold(XSysMon *InstancePtr, u8 AlarmThrReg)
This function returns the contents of the specified Alarm Threshold Register.
InstancePtr is a pointer to the XSysMon instance. AlarmThrReg is the index of an Alarm Threshold Register to be read. Use XSM_ATR_* constants defined in xsysmon.h to specify the index. A 16-bit value representing the contents of the selected Alarm Threshold Register. Over Temperature upper threshold is programmable only in V6 and 7 Series XADC BRAM high and low voltage threshold registers are available only in 7 Series and Zynq XADC. All the remaining Alarm Threshold registers specified by the constants XSM_ATR_*, are available in all the families of the Sysmon.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSM_ATR_TEMP_UPPER_OFFSET, XSM_ATR_VUSR0_LOWER, XSM_ATR_VUSR3_LOWER, XSM_ATR_VUSR3_UPPER, XSysMon_ReadReg.
Referenced by XSysMon_SelfTest.
void XSysMon_SetOverTemp(XSysMon *InstancePtr, u16 Value)
This function sets the powerdown temperature for the OverTemp signal in the OT Powerdown register.
InstancePtr is a pointer to the XSysMon instance. Value is the 16-bit OT Upper Alarm Register powerdown value. Valid values are 0 to 0x0FFF. None. This API has been deprecated. Use XSysMon_SetAlarmThreshold(), instead. This API should be used only with V6/7 Series since the upper threshold of OverTemp is programmable in in only V6 SysMon/7 Series and Zynq XADC.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSM_ATR_OT_UPPER_OFFSET, XSM_ATR_OT_UPPER_VAL_MASK, XSM_ATR_OT_UPPER_VAL_MAX, XSM_ATR_OT_UPPER_VAL_SHIFT, XSysMon_ReadReg, XSysMon_WriteReg.
u16 XSysMon_GetOverTemp(XSysMon *InstancePtr)
This function returns the powerdown temperature of the OverTemp signal in the OT Powerdown register.
InstancePtr is a pointer to the XSysMon instance. A 12-bit OT Upper Alarm Register powerdown value. This API has been deprecated. Use XSysMon_GetAlarmThreshold(), instead. This API should be used only with V6/7 Series since the upper threshold of OverTemp is programmable in only V6 SysMon/7 Series and Zynq XADC.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSM_ATR_OT_UPPER_OFFSET, XSM_ATR_OT_UPPER_VAL_SHIFT, XSysMon_ReadReg.
void XSysMon_EnableUserOverTemp(XSysMon *InstancePtr)
This function enables programming of the powerdown temperature for the OverTemp signal in the OT Powerdown register.
InstancePtr is a pointer to the XSysMon instance. None. This API should be used only with V6/7 Series since the upper threshold of OverTemp is programmable in only V6 SysMon/7 Series and Zynq XADC.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSM_ATR_OT_UPPER_ENB_MASK, XSM_ATR_OT_UPPER_ENB_VAL, XSM_ATR_OT_UPPER_OFFSET, XSysMon_ReadReg, XSysMon_WriteReg.
void XSysMon_DisableUserOverTemp(XSysMon *InstancePtr)
This function disables programming of the powerdown temperature for the OverTemp signal in the OT Powerdown register.
InstancePtr is a pointer to the XSysMon instance. None. This API should be used only with V6 SysMon/7 Series and Zynq XADC since the upper threshold of OverTemp is programmable in only V6 SysMon/7 Series and Zynq XADC.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSM_ATR_OT_UPPER_ENB_MASK, XSM_ATR_OT_UPPER_OFFSET, XSysMon_ReadReg, XSysMon_WriteReg.
void XSysMon_EnableTempUpdate(XSysMon *InstancePtr)
This function enables the Temperature updation logic so that temperature can be sent over TEMP_OUT port.
InstancePtr is a pointer to the XSysMon instance. None. None
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSysMon::Mask, XSM_CONVST_OFFSET, XSM_CONVST_TEMPUPDT_MASK, XSysMon_WriteReg.
void XSysMon_DisableTempUpdate(XSysMon *InstancePtr)
This function disables the Temperature updation logic for TEMP_OUT port.
InstancePtr is a pointer to the XSysMon instance. None. None
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSysMon::Mask, XSM_CONVST_OFFSET, XSM_CONVST_TEMPUPDT_MASK, XSysMon_WriteReg.
void XSysMon_SetTempWaitCycles(XSysMon *InstancePtr, u16 WaitCycles)
This function sets the number of Wait Cycles for Temperature updation logic.
InstancePtr is a pointer to the XSysMon instance. WaitCycles is number of wait cycles None. The default number of wait cycles are 1000(0x3E8).
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon::IsReady, XSysMon::Mask, XSM_CONVST_OFFSET, XSM_CONVST_WAITCYCLES_MASK, XSM_CONVST_WAITCYCLES_SHIFT, XSysMon_WriteReg.
int XSysMon_SelfTest(XSysMon *InstancePtr)
Functions in xsysmon_selftest.c.
Run a self-test on the driver/device.The test Resets the device,Writes a value into the Alarm Threshold register and reads it back for comparison.Resets the device again. InstancePtr is a pointer to the XSysMon instance. XST_SUCCESS if the value read from the Alarm Threshold register is the same as the value written.XST_FAILURE Otherwise This is a destructive test in that resets of the device are performed. Refer to the device specification for the device status after the reset operation.
References XSysMon::IsReady, XSM_ATR_VCCINT_UPPER, XSysMon_GetAlarmThreshold, XSysMon_Reset, XSysMon_SetAlarmThreshold.
Referenced by SysMonAuxPolledExample, SysMonIntrExample, SysMonPolledExample.
void XSysMon_IntrGlobalEnable(XSysMon *InstancePtr)
Functions in xsysmon_intr.c.
This function enables the global interrupt in the Global Interrupt Enable Register (GIER) so that the interrupt output from the System Monitor/ADC device is enabled.Interrupts enabled using XSysMon_IntrEnable() will not occur until the global interrupt enable bit is set by using this function. InstancePtr is a pointer to the XSysMon instance. None. The device must be configured at hardware build time to include interrupt component for this function to work.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon_Config::IncludeInterrupt, XSysMon::IsReady, XSM_GIER_GIE_MASK, XSM_GIER_OFFSET, XSysMon_WriteReg.
Referenced by SysMonIntrExample.
void XSysMon_IntrGlobalDisable(XSysMon *InstancePtr)
This function disables the global interrupt in the Global Interrupt Enable Register (GIER) so that the interrupt output from the System Monitor/ADC device is disabled.
InstancePtr is a pointer to the XSysMon instance. None. The device must be configured at hardware build time to include interrupt component for this function to work.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon_Config::IncludeInterrupt, XSysMon::IsReady, XSM_GIER_OFFSET, XSysMon_WriteReg.
Referenced by SysMonIntrExample.
void XSysMon_IntrEnable(XSysMon *InstancePtr, u32 Mask)
This function enables the specified interrupts in the device.
Interrupts enabled using this function will not occur until the global interrupt enable bit is set by using the XSysMon_IntrGlobalEnable()function. InstancePtr is a pointer to the XSysMon instance. Mask is the bit-mask of the interrupts to be enabled. Bit positions of 1 will be enabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XSM_IPIXR_* bits defined in xsysmon_hw.h. None. The device must be configured at hardware build time to include interrupt component for this function to work.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon_Config::IncludeInterrupt, XSysMon::IsReady, XSM_IPIER_OFFSET, XSM_IPIXR_ALL_MASK, XSysMon_ReadReg, XSysMon_WriteReg.
Referenced by SysMonIntrExample.
void XSysMon_IntrDisable(XSysMon *InstancePtr, u32 Mask)
This function disables the specified interrupts in the device.
InstancePtr is a pointer to the XSysMon instance. Mask is the bit-mask of the interrupts to be disabled. Bit positions of 1 will be disabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XSM_IPIXR_* bits defined in xsysmon_hw.h. None. The device must be configured at hardware build time to include interrupt component for this function to work.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon_Config::IncludeInterrupt, XSysMon::IsReady, XSM_IPIER_OFFSET, XSM_IPIXR_ALL_MASK, XSysMon_ReadReg, XSysMon_WriteReg.
u32 XSysMon_IntrGetEnabled(XSysMon *InstancePtr)
This function returns the enabled interrupts read from the Interrupt Enable Register (IPIER).
Use the XSM_IPIXR_* constants defined in xsysmon_hw.h to interpret the returned value. InstancePtr is a pointer to the XSysMon instance. A 32-bit value representing the contents of the IPIER. The device must be configured at hardware build time to include interrupt component for this function to work.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon_Config::IncludeInterrupt, XSysMon::IsReady, XSM_IPIER_OFFSET, XSM_IPIXR_ALL_MASK, XSysMon_ReadReg.
u32 XSysMon_IntrGetStatus(XSysMon *InstancePtr)
This function returns the interrupt status read from Interrupt Status Register(IPISR).
Use the XSM_IPIXR_* constants defined in xsysmon_hw.h to interpret the returned value. InstancePtr is a pointer to the XSysMon instance. A 32-bit value representing the contents of the IPISR. The device must be configured at hardware build time to include interrupt component for this function to work.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon_Config::IncludeInterrupt, XSysMon::IsReady, XSM_IPISR_OFFSET, XSM_IPIXR_ALL_MASK, XSysMon_ReadReg.
Referenced by SysMonIntrExample.
void XSysMon_IntrClear(XSysMon *InstancePtr, u32 Mask)
This function clears the specified interrupts in the Interrupt Status Register (IPISR).
InstancePtr is a pointer to the XSysMon instance. Mask is the bit-mask of the interrupts to be cleared. Bit positions of 1 will be cleared. Bit positions of 0 will not change the previous interrupt status. This mask is formed by OR'ing XSM_IPIXR_* bits which are defined in xsysmon_hw.h. None. The device must be configured at hardware build time to include interrupt component for this function to work.
References XSysMon_Config::BaseAddress, XSysMon::Config, XSysMon_Config::IncludeInterrupt, XSysMon::IsReady, XSM_IPISR_OFFSET, XSM_IPIXR_ALL_MASK, XSysMon_ReadReg, XSysMon_WriteReg.
Referenced by SysMonIntrExample.