dmaps
XDMAPS_DS_OFFSET
XDMAPS_DPC_OFFSET
XDMAPS_INTEN_OFFSET
XDMAPS_ES_OFFSET
XDMAPS_INTSTATUS_OFFSET
XDMAPS_INTCLR_OFFSET
XDMAPS_FSM_OFFSET
XDMAPS_FSC_OFFSET
XDMAPS_FTM_OFFSET
XDMAPS_FTC0_OFFSET
XDmaPs_FTCn_OFFSET
XDMAPS_CS0_OFFSET
XDmaPs_CSn_OFFSET
XDMAPS_CPC0_OFFSET
XDmaPs_CPCn_OFFSET
XDMAPS_SA_0_OFFSET
XDmaPs_SA_n_OFFSET
XDMAPS_DA_0_OFFSET
XDmaPs_DA_n_OFFSET
XDMAPS_CC_0_OFFSET
XDmaPs_CC_n_OFFSET
XDMAPS_LC0_0_OFFSET
XDmaPs_LC0_n_OFFSET
XDMAPS_LC1_0_OFFSET
XDmaPs_LC1_n_OFFSET
XDMAPS_DBGSTATUS_OFFSET
XDMAPS_DBGCMD_OFFSET
XDMAPS_DBGINST0_OFFSET
XDMAPS_DBGINST1_OFFSET
XDMAPS_CR0_OFFSET
XDMAPS_CR1_OFFSET
XDMAPS_CR2_OFFSET
XDMAPS_CR3_OFFSET
XDMAPS_CR4_OFFSET
XDMAPS_CRDN_OFFSET
XDMAPS_PERIPH_ID_0_OFFSET
XDMAPS_PERIPH_ID_1_OFFSET
XDMAPS_PERIPH_ID_2_OFFSET
XDMAPS_PERIPH_ID_3_OFFSET
XDMAPS_PCELL_ID_0_OFFSET
XDMAPS_PCELL_ID_1_OFFSET
XDMAPS_PCELL_ID_2_OFFSET
XDMAPS_PCELL_ID_3_OFFSET
XDMAPS_DS_DMA_STATUS
XDMAPS_DS_DMA_STATUS_STOPPED
XDMAPS_DBGSTATUS_BUSY
XDMAPS_CS_ACTIVE_MASK
XDMAPS_CR1_I_CACHE_LEN_MASK
XDmaPs_DBGINST0
typedef void(* XDmaPsDoneHandler)(unsigned int Channel, XDmaPs_Cmd *DmaCmd, void *CallbackRef))(unsigned int Channel, XDmaPs_Cmd *DmaCmd, void *CallbackRef)
It's the done handler a user can set for a channel.
typedef void(* XDmaPsFaultHandler)(unsigned int Channel, XDmaPs_Cmd *DmaCmd, void *CallbackRef))(unsigned int Channel, XDmaPs_Cmd *DmaCmd, void *CallbackRef)
It's the fault handler a user can set for a channel.
XDmaPs_Config XDmaPs_ConfigTable[][]
Each XDmaPs device in the system has an entry in this table.
XDmaPs_Config XDmaPs_ConfigTable[][]
Each XDmaPs device in the system has an entry in this table.
static int XDmaPs_Exec_DMAKILL(u32 BaseAddr, unsigned int Channel, unsigned int Thread)
Use the debug registers to kill the DMA thread.
BaseAddr is DMA device base address. Channel is the DMA channel number. Thread is Debug thread encoding. 0: DMA manager thread, 1: DMA channel. 0 on success, -1 on time out None.
static void XDmaPs_BufPool_Free(XDmaPs_ProgBuf *Pool, void *Buf)
Free a buffer of the DMA program buffer.
Pool the DMA program pool. Buf the DMA program buffer to be release. None None.
static int XDmaPs_Exec_DMAGO(u32 BaseAddr, unsigned int Channel, u32 DmaProg)
XDmaPs_Exec_DMAGO - Execute the DMAGO to start a channel.
BaseAddr PL330 device base address Channel Channel number for the device DmaProg DMA program starting address, this should be DMA address 0 on success, -1 on time out None.
static void XDmaPs_DoneISR_n(XDmaPs *InstPtr, unsigned Channel)
It's the generic Done ISR.
InstPtr is the DMA instance. Channel is the DMA channel number. None.* None.
static void * XDmaPs_BufPool_Allocate(XDmaPs_ProgBuf *Pool)
Allocate a buffer of the DMA program buffer from the pool.
Pool the DMA program pool. The allocated buffer, NULL if there is any error. None.
static int XDmaPs_BuildDmaProg(unsigned Channel, XDmaPs_Cmd *Cmd, unsigned CacheLength)
Construct the DMA program based on the descriptions of the DMA transfer.
The function handles memory to memory DMA transfers. It also handles unalgined head and small amount of residue tail. Channel DMA channel number Cmd is the DMA command. CacheLength is the icache line length, in terms of bytes. If it's zero, the performance enhancement feature will be turned off. The number of bytes for the program. None.
static void XDmaPs_Print_DmaProgBuf(char *Buf, int Length)
Prints the content of the buffer in bytes.
Buf is the buffer. Length is the length of the DMA program. None. None.
int XDmaPs_CfgInitialize(XDmaPs *InstPtr, XDmaPs_Config *Config, u32 EffectiveAddr)
Initializes a specific XDmaPs instance such that it is ready to be used.
The data format of the device is setup for 8 data bits, 1 stop bit, and no parity by default. The baud rate is set to a default value specified by Config->DefaultBaudRate if set, otherwise it is set to 19.2K baud. The receive FIFO threshold is set for 8 bytes. The default operating mode of the driver is polled mode. InstPtr is a pointer to the XDmaPs instance. Config is a reference to a structure containing information about a specific XDmaPs driver. EffectiveAddr is the device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, pass in the physical address instead. - XST_SUCCESS on initialization completion None.
References XDmaPs_Config::BaseAddress, XDmaPs::CacheLength, XDmaPs_ChannelData::ChanId, XDmaPs::Chans, XDmaPs::Config, XDmaPs_ChannelData::DevId, XDmaPs_Config::IntrId, XDmaPs_Config::IntrParent, XDmaPs::IsReady.
Referenced by XDmaPs_Example_W_Intr.
int XDmaPs_ResetManager(XDmaPs *InstPtr)
Reset the DMA Manager.
InstPtr is the DMA instance. 0 on success, -1 on time out None.
References XDmaPs_Config::BaseAddress, XDmaPs::Config.
int XDmaPs_ResetChannel(XDmaPs *InstPtr, unsigned int Channel)
Reset the specified DMA Channel.
InstPtr is the DMA instance. Channel is the channel to be reset. 0 on success, -1 on time out None.
References XDmaPs_Config::BaseAddress, XDmaPs::Config.
void XDmaPs_FaultISR(XDmaPs *InstPtr)
Driver fault interrupt service routine This is the one that connects the GIC.
Driver fault interrupt service routine. InstPtr is the DMA instance. None. None.
References XDmaPs_Config::BaseAddress, XDmaPs_Cmd::ChanFaultPCAddr, XDmaPs_Cmd::ChanFaultType, XDmaPs::Chans, XDmaPs::Config, XDmaPs_ChannelData::DmaCmdFromHw, XDmaPs_ChannelData::DmaCmdToHw, XDmaPs_Cmd::DmaStatus, XDmaPs::FaultHandler, XDmaPs::FaultRef, XDmaPs_Cmd::GeneratedDmaProg, XDmaPs_ChannelData::HoldDmaProg, XDmaPs_ChannelData::ProgBufPool.
Referenced by XDmaPs_Example_W_Intr.
int XDmaPs_SetDoneHandler(XDmaPs *InstPtr, unsigned Channel, XDmaPsDoneHandler DoneHandler, void *CallbackRef)
Set the done handler for a channel.
InstPtr is the DMA instance. Channel is the channel number. DoneHandler is the done interrupt handler. CallbackRef is the callback reference data. None. None.
References XDmaPs::Chans, XDmaPs_ChannelData::DoneHandler, XDmaPs_ChannelData::DoneRef.
Referenced by XDmaPs_Example_W_Intr.
int XDmaPs_SetFaultHandler(XDmaPs *InstPtr, XDmaPsFaultHandler FaultHandler, void *CallbackRef)
Set the fault handler for a channel.
InstPtr is the DMA instance. FaultHandler is the fault interrupt handler. CallbackRef is the callback reference data. None. None.
References XDmaPs::FaultHandler, XDmaPs::FaultRef.
static int XDmaPs_Instr_DMAEND(char *DmaProg)
Construction function for DMAEND instruction.
This function fills the program buffer with the constructed instruction. DmaProg the DMA program buffer, it's the starting address for the instruction being constructed The number of bytes for this instruction which is 1. None.
static void XDmaPs_Memcpy4(char *Dst, char *Src)
static int XDmaPs_Instr_DMAGO(char *DmaProg, unsigned int Cn, u32 Imm, unsigned int Ns)
Construction function for DMAGO instruction.
This function fills the program buffer with the constructed instruction. DmaProg is the DMA program buffer, it's the starting address for the instruction being constructed Cn is the Channel number, 0 - 7 Imm is 32-bit immediate number written to the Channel Program Counter. Ns is Non-secure flag. If Ns is 1, the DMA channel operates in the Non-secure state. If Ns is 0, the execution depends on the security state of the DMA manager: DMA manager is in the Secure state, DMA channel operates in the Secure state. DMA manager is in the Non-secure state, DMAC aborts. The number of bytes for this instruction which is 6. None
static int XDmaPs_Instr_DMALD(char *DmaProg)
Construction function for DMALD instruction.
This function fills the program buffer with the constructed instruction. DmaProg the DMA program buffer, it's the starting address for the instruction being constructed The number of bytes for this instruction which is 1. None.
static int XDmaPs_Instr_DMALP(char *DmaProg, unsigned Lc, unsigned LoopIterations)
Construction function for DMALP instruction.
This function fills the program buffer with the constructed instruction. DmaProg is the DMA program buffer, it's the starting address for the instruction being constructed Lc is the Loop counter register, can either be 0 or 1. LoopIterations : the number of iterations, LoopInterations - 1 will be encoded in the DMALP instruction. The number of bytes for this instruction which is 2. None.
static int XDmaPs_Instr_DMALPEND(char *DmaProg, char *BodyStart, unsigned Lc)
Construction function for DMALPEND instruction.
This function fills the program buffer with the constructed instruction. DmaProg is the DMA program buffer, it's the starting address for the instruction being constructed BodyStart is the starting address of the loop body. It is used to calculate the bytes of backward jump. Lc is the Loop counter register, can either be 0 or 1. The number of bytes for this instruction which is 2. None.
static int XDmaPs_Instr_DMAMOV(char *DmaProg, unsigned Rd, u32 Imm)
Construction function for DMAMOV instruction.
This function fills the program buffer with the constructed instruction. DmaProg is the DMA program buffer, it's the starting address for the instruction being constructed Rd is the register id, 0 for SAR, 1 for CCR, and 2 for DAR Imm is the 32-bit immediate number The number of bytes for this instruction which is 6. None.
static int XDmaPs_Instr_DMANOP(char *DmaProg)
Construction function for DMANOP instruction.
This function fills the program buffer with the constructed instruction. DmaProg is the DMA program buffer, it's the starting address for the instruction being constructed The number of bytes for this instruction which is 1. None.
int XDmaPs_Instr_DMARMB(char *DmaProg)
Construction function for DMARMB instruction.
This function fills the program buffer with the constructed instruction. DmaProg is the DMA program buffer, it's the starting address for the instruction being constructed The number of bytes for this instruction which is 1. None.
static int XDmaPs_Instr_DMASEV(char *DmaProg, unsigned int EventNumber)
Construction function for DMASEV instruction.
This function fills the program buffer with the constructed instruction. DmaProg is the DMA program buffer, it's the starting address for the instruction being constructed EventNumber is the Event number to signal. The number of bytes for this instruction which is 2. None.
static int XDmaPs_Instr_DMAST(char *DmaProg)
Construction function for DMAST instruction.
This function fills the program buffer with the constructed instruction. DmaProg is the DMA program buffer, it's the starting address for the instruction being constructed The number of bytes for this instruction which is 1. None.
int XDmaPs_Instr_DMAWMB(char *DmaProg)
Construction function for DMAWMB instruction.
This function fills the program buffer with the constructed instruction. DmaProg is the DMA program buffer, it's the starting address for the instruction being constructed The number of bytes for this instruction which is 1. None.
static unsigned XDmaPs_ToEndianSwapSizeBits(unsigned int EndianSwapSize)
Conversion function from the endian swap size to the bit encoding of the CCR.
EndianSwapSize is the endian swap size, in terms of bits, it could be 8, 16, 32, 64, or 128(We are using DMA assembly syntax) The endian swap size bit encoding for the CCR. None.
static unsigned XDmaPs_ToBurstSizeBits(unsigned BurstSize)
Conversion function from the burst size to the bit encoding of the CCR.
BurstSize is the burst size. It's the data width. In terms of bytes, it could be 1, 2, 4, 8, 16, 32, 64, or 128. It must be no larger than the bus width. (We are using DMA assembly syntax.) None.
u32 XDmaPs_ToCCRValue(XDmaPs_ChanCtrl *ChanCtrl)
Conversion function from PL330 bus transfer descriptors to CCR value.
All the values passed to the functions are in terms of assembly languages, not in terms of the register bit encoding. ChanCtrl is the Instance of XDmaPs_ChanCtrl. The 32-bit CCR value. None.
References XDmaPs_ChanCtrl::DstBurstLen, XDmaPs_ChanCtrl::DstBurstSize, XDmaPs_ChanCtrl::DstCacheCtrl, XDmaPs_ChanCtrl::DstInc, XDmaPs_ChanCtrl::DstProtCtrl, XDmaPs_ChanCtrl::EndianSwapSize, XDmaPs_ChanCtrl::SrcBurstLen, XDmaPs_ChanCtrl::SrcBurstSize, XDmaPs_ChanCtrl::SrcCacheCtrl, XDmaPs_ChanCtrl::SrcInc, XDmaPs_ChanCtrl::SrcProtCtrl.
int XDmaPs_ConstructSingleLoop(char *DmaProgStart, int CacheLength, char *DmaProgLoopStart, int LoopCount)
Construct a loop with only DMALD and DMAST as the body using loop counter 0.
The function also makes sure the loop body and the lpend is in the same cache line. DmaProgStart is the very start address of the DMA program. This is used to calculate whether the loop is in a cache line. CacheLength is the icache line length, in terms of bytes. If it's zero, the performance enhancement feature will be turned off. DmaProgLoopStart The starting address of the loop (DMALP). LoopCount The inner loop count. Loop count - 1 will be used to initialize the loop counter. The number of bytes the loop has. None.
Referenced by XDmaPs_ConstructNestedLoop.
int XDmaPs_ConstructNestedLoop(char *DmaProgStart, int CacheLength, char *DmaProgLoopStart, unsigned int LoopCountOuter, unsigned int LoopCountInner)
Construct a nested loop with only DMALD and DMAST in the inner loop body.
It uses loop counter 1 for the outer loop and loop counter 0 for the inner loop. DmaProgStart is the very start address of the DMA program. This is used to calculate whether the loop is in a cache line. CacheLength is the icache line length, in terms of bytes. If it's zero, the performance enhancement feature will be turned off. DmaProgLoopStart The starting address of the loop (DMALP). LoopCountOuter The outer loop count. Loop count - 1 will be used to initialize the loop counter. LoopCountInner The inner loop count. Loop count - 1 will be used to initialize the loop counter. The number byes the nested loop program has. None.
References XDmaPs_ConstructSingleLoop.
int XDmaPs_GenDmaProg(XDmaPs *InstPtr, unsigned int Channel, XDmaPs_Cmd *Cmd)
Generate a DMA program based for the DMA command, the buffer will be pointed by the GeneratedDmaProg field of the command.
InstPtr is then DMA instance. Channel is the DMA channel number. Cmd is the DMA command. - XST_SUCCESS on success. XST_FAILURE if it fails None.
References XDmaPs_Cmd::BD, XDmaPs::CacheLength, XDmaPs_Cmd::ChanCtrl, XDmaPs::Chans, XDmaPs_BD::DstAddr, XDmaPs_ChanCtrl::DstBurstLen, XDmaPs_ChanCtrl::DstBurstSize, XDmaPs_ChanCtrl::DstInc, XDmaPs_Cmd::GeneratedDmaProg, XDmaPs_Cmd::GeneratedDmaProgLength, XDmaPs_ChannelData::ProgBufPool, XDmaPs_BD::SrcAddr, XDmaPs_ChanCtrl::SrcBurstLen, XDmaPs_ChanCtrl::SrcBurstSize, XDmaPs_ChanCtrl::SrcInc, XDmaPs_Print_DmaProg.
Referenced by XDmaPs_Start.
int XDmaPs_FreeDmaProg(XDmaPs *InstPtr, unsigned int Channel, XDmaPs_Cmd *Cmd)
Free the DMA program buffer that is pointed by the GeneratedDmaProg field of the command.
InstPtr is then DMA instance. Channel is the DMA channel number. Cmd is the DMA command. XST_SUCCESS on success. XST_FAILURE if there is any error. None.
References XDmaPs::Chans, XDmaPs_Cmd::GeneratedDmaProg, XDmaPs_Cmd::GeneratedDmaProgLength, XDmaPs_ChannelData::ProgBufPool.
int XDmaPs_Start(XDmaPs *InstPtr, unsigned int Channel, XDmaPs_Cmd *Cmd, int HoldDmaProg)
Start a DMA command.
The command can only be invoked when the channel is idle. The driver takes the command, generates DMA program if needed, then pass the program to DMAC to execute. InstPtr is then DMA instance. Channel is the DMA channel number. Cmd is the DMA command. HoldDmaProg is tag indicating whether the driver can release the allocated DMA buffer or not. If a user wants to examine the generated DMA program, the flag should be set to 1. After the DMA program is finished, a user needs to explicitly free the buffer. XST_SUCCESS on successXST_DEVICE_BUSY if DMA is busyXST_FAILURE on other failures None.
References XDmaPs_Config::BaseAddress, XDmaPs_Cmd::BD, XDmaPs_Cmd::ChanCtrl, XDmaPs::Chans, XDmaPs::Config, XDmaPs_ChannelData::DmaCmdToHw, XDmaPs_Cmd::DmaStatus, XDmaPs_BD::DstAddr, XDmaPs_ChanCtrl::DstInc, XDmaPs_Cmd::GeneratedDmaProg, XDmaPs_ChannelData::HoldDmaProg, XDmaPs_BD::Length, XDmaPs_BD::SrcAddr, XDmaPs_ChanCtrl::SrcInc, XDmaPs_Cmd::UserDmaProg, XDmaPs_GenDmaProg, XDmaPs_IsActive, XDmaPs_WriteReg.
Referenced by XDmaPs_Example_W_Intr.
int XDmaPs_IsActive(XDmaPs *InstPtr, unsigned int Channel)
Checks whether the DMA channel is active or idle.
InstPtr is the DMA instance. Channel is the DMA channel number. 0: if the channel is idle 1: otherwise None.
References XDmaPs::Chans, XDmaPs_ChannelData::DmaCmdToHw.
Referenced by XDmaPs_Start.
void XDmaPs_DoneISR_0(XDmaPs *InstPtr)
Driver done interrupt service routine for channel 0.
To avoid linkage error,modify all inline functions from extern inline to static inline for IAR compiler.We need this done ISR mainly because the driver needs to release the DMA program buffer. This is the one that connects the GIC InstPtr is the DMA instance. None. None. Driver done interrupt service routines for the channels. We need this done ISR mainly because the driver needs to release the DMA program buffer. This is the one that connects the GIC
Referenced by XDmaPs_Example_W_Intr.
void XDmaPs_DoneISR_1(XDmaPs *InstPtr)
Driver done interrupt service routine for channel 1.
We need this done ISR mainly because the driver needs to release the DMA program buffer. This is the one that connects the GIC InstPtr is the DMA instance. None. None.
Referenced by XDmaPs_Example_W_Intr.
void XDmaPs_DoneISR_2(XDmaPs *InstPtr)
Driver done interrupt service routine for channel 2.
We need this done ISR mainly because the driver needs to release the DMA program buffer. This is the one that connects the GIC InstPtr is the DMA instance. None. None.
Referenced by XDmaPs_Example_W_Intr.
void XDmaPs_DoneISR_3(XDmaPs *InstPtr)
Driver done interrupt service routine for channel 3.
We need this done ISR mainly because the driver needs to release the DMA program buffer. This is the one that connects the GIC InstPtr is the DMA instance. None. None.
Referenced by XDmaPs_Example_W_Intr.
void XDmaPs_DoneISR_4(XDmaPs *InstPtr)
Driver done interrupt service routine for channel 4.
We need this done ISR mainly because the driver needs to release the DMA program buffer. This is the one that connects the GIC InstPtr is the DMA instance. None. None.
Referenced by XDmaPs_Example_W_Intr.
void XDmaPs_DoneISR_5(XDmaPs *InstPtr)
Driver done interrupt service routine for channel 5.
We need this done ISR mainly because the driver needs to release the DMA program buffer. This is the one that connects the GIC InstPtr is the DMA instance. None. None.
Referenced by XDmaPs_Example_W_Intr.
void XDmaPs_DoneISR_6(XDmaPs *InstPtr)
Driver done interrupt service routine for channel 6.
We need this done ISR mainly because the driver needs to release the DMA program buffer. This is the one that connects the GIC InstPtr is the DMA instance. None. None.
Referenced by XDmaPs_Example_W_Intr.
void XDmaPs_DoneISR_7(XDmaPs *InstPtr)
Driver done interrupt service routine for channel 7.
We need this done ISR mainly because the driver needs to release the DMA program buffer. This is the one that connects the GIC InstPtr is the DMA instance. None. None.
Referenced by XDmaPs_Example_W_Intr.
void XDmaPs_Print_DmaProg(XDmaPs_Cmd *Cmd)
Print the Dma Prog Contents.
Cmd is the command buffer. None. None.
References XDmaPs_Cmd::GeneratedDmaProg, XDmaPs_Cmd::GeneratedDmaProgLength, XDmaPs_Cmd::UserDmaProg, XDmaPs_Cmd::UserDmaProgLength.
Referenced by XDmaPs_GenDmaProg.
XDmaPs_Config * XDmaPs_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
A table contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration table entry corresponding to the given device ID/BaseAddress, or NULL if no match is found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XDmaPs_Config::Name.
Referenced by XDmaPs_Example_W_Intr.
u32 XDmaPs_GetDrvIndex(XDmaPs *InstancePtr, UINTPTR BaseAddress)
int XDmaPs_SelfTest(XDmaPs *InstPtr)
This function runs a self-test on the driver and hardware device.
This self test performs a local loopback and verifies data can be sent and received.The time for this test is proportional to the baud rate that has been set prior to calling this function.The mode and control registers are restored before return. InstPtr is a pointer to the XDmaPs instance - XST_SUCCESS if the test was successful - XST_FAILURE if the test failed This function can hang if the hardware is not functioning properly.
References XDmaPs_Config::BaseAddress, XDmaPs::Config.
void XDmaPs_ResetHw(u32 BaseAddress)
This function perform the reset sequence to the given dmaps interface by configuring the appropriate control bits in the dmaps specific registers the dmaps reset sequence involves the following steps Disable all the interuupts Clear the pending interrupts Kill all the active channel threads Kill the manager thread.
BaseAddress of the interface N/A This function will not modify the slcr registers that are relevant for dmaps controller
References XDmaPs_WriteReg.
XDMAPS_MOV_SAR
XDMAPS_MOV_CCR
XDMAPS_MOV_DAR
XDMAPS_CCR_SINGLE_BYTE
XDMAPS_CCR_M2M_SINGLE_BYTE
XDMAPS_MAX_WAIT
XDMAPS_H
XDMAPS_MAX_CHAN_BUFS
XDMAPS_CHAN_BUF_LEN
XDMAPS_MAX_WAIT
XDMAPS_HW_H
XDMAPS_CHANNELS_PER_DEV
XDMAPS_INTCLR_ALL_MASK
XDmaPs_ReadReg
XDmaPs_WriteReg
Write a DMAC register.
BaseAddress contains the base address of the device. RegOffset contains the offset from the base address of the device. RegisterValue is the value to be written to the register. None. C-Style signature: void XDmaPs_WriteReg(u32 BaseAddress, int RegOffset, u32 RegisterValue)
Referenced by XDmaPs_ResetHw, XDmaPs_Start.