xdmaps.h
XDMAPS_H
XDMAPS_MAX_CHAN_BUFS
XDMAPS_CHAN_BUF_LEN
typedef void(* XDmaPsDoneHandler)(unsigned int Channel, XDmaPs_Cmd *DmaCmd, void *CallbackRef))(unsigned int Channel, XDmaPs_Cmd *DmaCmd, void *CallbackRef)
It's the done handler a user can set for a channel.
typedef void(* XDmaPsFaultHandler)(unsigned int Channel, XDmaPs_Cmd *DmaCmd, void *CallbackRef))(unsigned int Channel, XDmaPs_Cmd *DmaCmd, void *CallbackRef)
It's the fault handler a user can set for a channel.
int XDmaPs_CfgInitialize(XDmaPs *InstPtr, XDmaPs_Config *Config, u32 EffectiveAddr)
Initializes a specific XDmaPs instance such that it is ready to be used.
The data format of the device is setup for 8 data bits, 1 stop bit, and no parity by default. The baud rate is set to a default value specified by Config->DefaultBaudRate if set, otherwise it is set to 19.2K baud. The receive FIFO threshold is set for 8 bytes. The default operating mode of the driver is polled mode. InstPtr is a pointer to the XDmaPs instance. Config is a reference to a structure containing information about a specific XDmaPs driver. EffectiveAddr is the device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, pass in the physical address instead. - XST_SUCCESS on initialization completion None.
References XDmaPs_Config::BaseAddress, XDmaPs::CacheLength, XDmaPs_ChannelData::ChanId, XDmaPs::Chans, XDmaPs::Config, XDmaPs_ChannelData::DevId, XDmaPs_Config::IntrId, XDmaPs_Config::IntrParent, XDmaPs::IsReady.
Referenced by XDmaPs_Example_W_Intr.
int XDmaPs_Start(XDmaPs *InstPtr, unsigned int Channel, XDmaPs_Cmd *Cmd, int HoldDmaProg)
Start a DMA command.
The command can only be invoked when the channel is idle. The driver takes the command, generates DMA program if needed, then pass the program to DMAC to execute. InstPtr is then DMA instance. Channel is the DMA channel number. Cmd is the DMA command. HoldDmaProg is tag indicating whether the driver can release the allocated DMA buffer or not. If a user wants to examine the generated DMA program, the flag should be set to 1. After the DMA program is finished, a user needs to explicitly free the buffer. XST_SUCCESS on successXST_DEVICE_BUSY if DMA is busyXST_FAILURE on other failures None.
References XDmaPs_Config::BaseAddress, XDmaPs_Cmd::BD, XDmaPs_Cmd::ChanCtrl, XDmaPs::Chans, XDmaPs::Config, XDmaPs_ChannelData::DmaCmdToHw, XDmaPs_Cmd::DmaStatus, XDmaPs_BD::DstAddr, XDmaPs_ChanCtrl::DstInc, XDmaPs_Cmd::GeneratedDmaProg, XDmaPs_ChannelData::HoldDmaProg, XDmaPs_BD::Length, XDmaPs_BD::SrcAddr, XDmaPs_ChanCtrl::SrcInc, XDmaPs_Cmd::UserDmaProg, XDmaPs_GenDmaProg, XDmaPs_IsActive, XDmaPs_WriteReg.
Referenced by XDmaPs_Example_W_Intr.
int XDmaPs_IsActive(XDmaPs *InstPtr, unsigned int Channel)
Checks whether the DMA channel is active or idle.
InstPtr is the DMA instance. Channel is the DMA channel number. 0: if the channel is idle 1: otherwise None.
References XDmaPs::Chans, XDmaPs_ChannelData::DmaCmdToHw.
Referenced by XDmaPs_Start.
int XDmaPs_GenDmaProg(XDmaPs *InstPtr, unsigned int Channel, XDmaPs_Cmd *Cmd)
Generate a DMA program based for the DMA command, the buffer will be pointed by the GeneratedDmaProg field of the command.
InstPtr is then DMA instance. Channel is the DMA channel number. Cmd is the DMA command. - XST_SUCCESS on success. XST_FAILURE if it fails None.
References XDmaPs_Cmd::BD, XDmaPs::CacheLength, XDmaPs_Cmd::ChanCtrl, XDmaPs::Chans, XDmaPs_BD::DstAddr, XDmaPs_ChanCtrl::DstBurstLen, XDmaPs_ChanCtrl::DstBurstSize, XDmaPs_ChanCtrl::DstInc, XDmaPs_Cmd::GeneratedDmaProg, XDmaPs_Cmd::GeneratedDmaProgLength, XDmaPs_ChannelData::ProgBufPool, XDmaPs_BD::SrcAddr, XDmaPs_ChanCtrl::SrcBurstLen, XDmaPs_ChanCtrl::SrcBurstSize, XDmaPs_ChanCtrl::SrcInc, XDmaPs_Print_DmaProg.
Referenced by XDmaPs_Start.
int XDmaPs_FreeDmaProg(XDmaPs *InstPtr, unsigned int Channel, XDmaPs_Cmd *Cmd)
Free the DMA program buffer that is pointed by the GeneratedDmaProg field of the command.
InstPtr is then DMA instance. Channel is the DMA channel number. Cmd is the DMA command. XST_SUCCESS on success. XST_FAILURE if there is any error. None.
References XDmaPs::Chans, XDmaPs_Cmd::GeneratedDmaProg, XDmaPs_Cmd::GeneratedDmaProgLength, XDmaPs_ChannelData::ProgBufPool.
void XDmaPs_Print_DmaProg(XDmaPs_Cmd *Cmd)
Print the Dma Prog Contents.
Cmd is the command buffer. None. None.
References XDmaPs_Cmd::GeneratedDmaProg, XDmaPs_Cmd::GeneratedDmaProgLength, XDmaPs_Cmd::UserDmaProg, XDmaPs_Cmd::UserDmaProgLength.
Referenced by XDmaPs_GenDmaProg.
int XDmaPs_ResetManager(XDmaPs *InstPtr)
Reset the DMA Manager.
InstPtr is the DMA instance. 0 on success, -1 on time out None.
References XDmaPs_Config::BaseAddress, XDmaPs::Config.
int XDmaPs_ResetChannel(XDmaPs *InstPtr, unsigned int Channel)
Reset the specified DMA Channel.
InstPtr is the DMA instance. Channel is the channel to be reset. 0 on success, -1 on time out None.
References XDmaPs_Config::BaseAddress, XDmaPs::Config.
int XDmaPs_SetDoneHandler(XDmaPs *InstPtr, unsigned Channel, XDmaPsDoneHandler DoneHandler, void *CallbackRef)
Set the done handler for a channel.
InstPtr is the DMA instance. Channel is the channel number. DoneHandler is the done interrupt handler. CallbackRef is the callback reference data. None. None.
References XDmaPs::Chans, XDmaPs_ChannelData::DoneHandler, XDmaPs_ChannelData::DoneRef.
Referenced by XDmaPs_Example_W_Intr.
int XDmaPs_SetFaultHandler(XDmaPs *InstPtr, XDmaPsFaultHandler FaultHandler, void *CallbackRef)
Set the fault handler for a channel.
InstPtr is the DMA instance. FaultHandler is the fault interrupt handler. CallbackRef is the callback reference data. None. None.
References XDmaPs::FaultHandler, XDmaPs::FaultRef.
int XDmaPs_Instr_DMARMB(char *DmaProg)
Construction function for DMARMB instruction.
This function fills the program buffer with the constructed instruction. DmaProg is the DMA program buffer, it's the starting address for the instruction being constructed The number of bytes for this instruction which is 1. None.
int XDmaPs_Instr_DMAWMB(char *DmaProg)
Construction function for DMAWMB instruction.
This function fills the program buffer with the constructed instruction. DmaProg is the DMA program buffer, it's the starting address for the instruction being constructed The number of bytes for this instruction which is 1. None.
void XDmaPs_DoneISR_0(XDmaPs *InstPtr)
Driver done interrupt service routine for channel 0.
To avoid linkage error,modify all inline functions from extern inline to static inline for IAR compiler.We need this done ISR mainly because the driver needs to release the DMA program buffer. This is the one that connects the GIC InstPtr is the DMA instance. None. None. Driver done interrupt service routines for the channels. We need this done ISR mainly because the driver needs to release the DMA program buffer. This is the one that connects the GIC
Referenced by XDmaPs_Example_W_Intr.
void XDmaPs_DoneISR_1(XDmaPs *InstPtr)
Driver done interrupt service routine for channel 1.
We need this done ISR mainly because the driver needs to release the DMA program buffer. This is the one that connects the GIC InstPtr is the DMA instance. None. None.
Referenced by XDmaPs_Example_W_Intr.
void XDmaPs_DoneISR_2(XDmaPs *InstPtr)
Driver done interrupt service routine for channel 2.
We need this done ISR mainly because the driver needs to release the DMA program buffer. This is the one that connects the GIC InstPtr is the DMA instance. None. None.
Referenced by XDmaPs_Example_W_Intr.
void XDmaPs_DoneISR_3(XDmaPs *InstPtr)
Driver done interrupt service routine for channel 3.
We need this done ISR mainly because the driver needs to release the DMA program buffer. This is the one that connects the GIC InstPtr is the DMA instance. None. None.
Referenced by XDmaPs_Example_W_Intr.
void XDmaPs_DoneISR_4(XDmaPs *InstPtr)
Driver done interrupt service routine for channel 4.
We need this done ISR mainly because the driver needs to release the DMA program buffer. This is the one that connects the GIC InstPtr is the DMA instance. None. None.
Referenced by XDmaPs_Example_W_Intr.
void XDmaPs_DoneISR_5(XDmaPs *InstPtr)
Driver done interrupt service routine for channel 5.
We need this done ISR mainly because the driver needs to release the DMA program buffer. This is the one that connects the GIC InstPtr is the DMA instance. None. None.
Referenced by XDmaPs_Example_W_Intr.
void XDmaPs_DoneISR_6(XDmaPs *InstPtr)
Driver done interrupt service routine for channel 6.
We need this done ISR mainly because the driver needs to release the DMA program buffer. This is the one that connects the GIC InstPtr is the DMA instance. None. None.
Referenced by XDmaPs_Example_W_Intr.
void XDmaPs_DoneISR_7(XDmaPs *InstPtr)
Driver done interrupt service routine for channel 7.
We need this done ISR mainly because the driver needs to release the DMA program buffer. This is the one that connects the GIC InstPtr is the DMA instance. None. None.
Referenced by XDmaPs_Example_W_Intr.
void XDmaPs_FaultISR(XDmaPs *InstPtr)
Driver fault interrupt service routine This is the one that connects the GIC.
Driver fault interrupt service routine. InstPtr is the DMA instance. None. None.
References XDmaPs_Config::BaseAddress, XDmaPs_Cmd::ChanFaultPCAddr, XDmaPs_Cmd::ChanFaultType, XDmaPs::Chans, XDmaPs::Config, XDmaPs_ChannelData::DmaCmdFromHw, XDmaPs_ChannelData::DmaCmdToHw, XDmaPs_Cmd::DmaStatus, XDmaPs::FaultHandler, XDmaPs::FaultRef, XDmaPs_Cmd::GeneratedDmaProg, XDmaPs_ChannelData::HoldDmaProg, XDmaPs_ChannelData::ProgBufPool.
Referenced by XDmaPs_Example_W_Intr.
XDmaPs_Config * XDmaPs_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
A table contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration table entry corresponding to the given device ID/BaseAddress, or NULL if no match is found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XDmaPs_Config::Name.
Referenced by XDmaPs_Example_W_Intr.
u32 XDmaPs_GetDrvIndex(XDmaPs *InstancePtr, UINTPTR BaseAddress)
int XDmaPs_SelfTest(XDmaPs *InstPtr)
This function runs a self-test on the driver and hardware device.
This self test performs a local loopback and verifies data can be sent and received.The time for this test is proportional to the baud rate that has been set prior to calling this function.The mode and control registers are restored before return. InstPtr is a pointer to the XDmaPs instance - XST_SUCCESS if the test was successful - XST_FAILURE if the test failed This function can hang if the hardware is not functioning properly.
References XDmaPs_Config::BaseAddress, XDmaPs::Config.