xv_hdmitx1.c
const XV_HdmiTx1_ScdcField ScdcField[XV_HDMITX1_SCDCFIELD_SIZE][XV_HDMITX1_SCDCFIELD_SIZE]
This table contains the attributes for SCDC fields Each entry consists of: 1) Register Offset 2) Bits Mask 3) Bits Shift.
static void StubCallback(void *Callback)
This function is a stub for the asynchronous callback.
The stub is here in case the upper layer forgot to set the handlers. On initialization, all handlers are set to this callback. It is considered an error for this handler to be invoked. CallbackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. None. None.
int XV_HdmiTx1_CfgInitialize(XV_HdmiTx1 *InstancePtr, XV_HdmiTx1_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the HDMI TX core.
This function must be called prior to using the HDMI TX core. Initialization of the HDMI TX includes setting up the instance data and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the XV_HdmiTx1 core instance. CfgPtr points to the configuration structure associated with the HDMI TX core. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if XV_HdmiTx1_CfgInitialize was successful.XST_FAILURE if HDMI TX PIO ID mismatched. None.
References XV_HdmiTx1_Stream::Audio, XV_HdmiTx1_Config::BaseAddress, XV_HdmiTx1::Config, XV_HdmiTx1::ConnectCallback, XV_HdmiTx1_Stream::CorePixPerClk, XV_HdmiTx1::DscDecodeFailCallback, XV_HdmiTx1::DynHdrMtwCallback, XV_HdmiTx1_Stream::Frl, XV_HdmiTx1_Stream::IsConnected, XV_HdmiTx1::IsReady, XV_HdmiTx1_Frl::Lanes, XV_HdmiTx1_Frl::MaxFrlRate, XV_HdmiTx1_Config::MaxFrlRate, XV_HdmiTx1_Stream::OverrideScrambler, XV_HdmiTx1_Frl::RateLock, XV_HdmiTx1_Stream::State, XV_HdmiTx1::Stream, XV_HdmiTx1::StreamDownCallback, XV_HdmiTx1::StreamUpCallback, XV_HdmiTx1::TmdsConfigCallback, XV_HdmiTx1::ToggleCallback, XV_HdmiTx1_Frl::TrainingState, XV_HdmiTx1::VsCallback, XV_HDMITX1_AUD_CTRL_CLR_OFFSET, XV_HDMITX1_AUD_CTRL_SET_OFFSET, XV_HdmiTx1_AudioDisable, XV_HdmiTx1_AuxDisable, XV_HdmiTx1_Clear, XV_HDMITX1_CONNECT_CONF_OFFSET, XV_HdmiTx1_DdcDisable, XV_HdmiTx1_DdcIntrClear, XV_HDMITX1_FRLSTATE_LTS_L, XV_HdmiTx1_GetTime1Ms, XV_HDMITX1_HPD_TIMEGRID_OFFSET, XV_HDMITX1_MASK_16, XV_HDMITX1_PIO_ID, XV_HDMITX1_PIO_ID_OFFSET, XV_HDMITX1_PIO_IN_BRDG_LOCKED_MASK, XV_HDMITX1_PIO_IN_BRDG_OVERFLOW_MASK, XV_HDMITX1_PIO_IN_BRDG_UNDERFLOW_MASK, XV_HDMITX1_PIO_IN_EVT_FE_OFFSET, XV_HDMITX1_PIO_IN_EVT_RE_OFFSET, XV_HDMITX1_PIO_IN_HPD_MASK, XV_HDMITX1_PIO_IN_HPD_TOGGLE_MASK, XV_HDMITX1_PIO_IN_LNK_RDY_MASK, XV_HDMITX1_PIO_IN_VS_MASK, XV_HdmiTx1_PioDisable, XV_HdmiTx1_PioIntrClear, XV_HdmiTx1_ReadReg, XV_HdmiTx1_SetHdmiTmdsMode, XV_HDMITX1_SHIFT_16, XV_HDMITX1_TOGGLE_CONF_OFFSET, XV_HdmiTx1_WriteReg.
void XV_HdmiTx1_SetAxiClkFreq(XV_HdmiTx1 *InstancePtr, u32 ClkFreq)
This function sets the AXI4-Lite Clock Frequency.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. ClkFreq specifies the value that needs to be set. This is required after a reset or init.
References XV_HdmiTx1::Config, XV_HdmiTx1::CpuClkFreq, XV_HdmiTx1_DdcInit.
void XV_HdmiTx1_SetHdmiTmdsMode(XV_HdmiTx1 *InstancePtr)
This function sets the core into HDMI TMDS mode.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. This is required after a reset or init.
References XV_HdmiTx1::Stream, XV_HdmiTx1_AudioEnable, XV_HdmiTx1_AuxEnable, XV_HdmiTx1_SetMode.
Referenced by XV_HdmiTx1_CfgInitialize.
void XV_HdmiTx1_SetDviMode(XV_HdmiTx1 *InstancePtr)
This function sets the core into DVI mode.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. This is required after a reset or init.
References XV_HdmiTx1::Stream, XV_HdmiTx1_AudioDisable, XV_HdmiTx1_AuxDisable, XV_HdmiTx1_ClearMode.
void XV_HdmiTx1_AuxEnable(XV_HdmiTx1 *InstancePtr)
This function enables the HDMI TX Auxiliary (AUX) peripheral.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. None.
References XV_HDMITX1_AUX_CTRL_RUN_MASK, XV_HDMITX1_AUX_CTRL_SET_OFFSET, XV_HdmiTx1_WriteReg.
Referenced by XV_HdmiTx1_SetHdmiTmdsMode.
void XV_HdmiTx1_AudioEnable(XV_HdmiTx1 *InstancePtr)
This macro enables audio in HDMI TX core.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. None.
References XV_HdmiTx1::Stream, XV_HDMITX1_AUD_CTRL_RUN_MASK, XV_HDMITX1_AUD_CTRL_SET_OFFSET, XV_HdmiTx1_TMDSACRStart, XV_HdmiTx1_WriteReg.
Referenced by XV_HdmiTx1_SetAudioChannels, XV_HdmiTx1_SetAudioFormat, XV_HdmiTx1_SetHdmiTmdsMode.
void XV_HdmiTx1_Clear(XV_HdmiTx1 *InstancePtr)
This function clear the HDMI TX variables and sets it to the defaults.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. This is required after a reset or init.
Referenced by XV_HdmiTx1_CfgInitialize.
void XV_HdmiTx1_Start(XV_HdmiTx1 *InstancePtr)
This function starts the HDMI TX core.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. This is required after a reset or initialization.
References XV_HdmiTx1_PioEnable, XV_HdmiTx1_PioIntrEnable.
void XV_HdmiTx1_Stop(XV_HdmiTx1 *InstancePtr)
This function stops the HDMI TX core.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None.
References XV_HdmiTx1_PioDisable, XV_HdmiTx1_PioIntrDisable.
u8 XV_HdmiTx1_LookupVic(XVidC_VideoMode VideoMode)
This function provides video identification code of video mode.
VideoMode specifies resolution identifier. Video identification code defined in the VIC table. None.
u64 XV_HdmiTx1_GetTmdsClk(XV_HdmiTx1 *InstancePtr)
This function sets and return the TMDS Clock based on Video Parameter from the InstancePtr.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. TMDS Clock None.
References XV_HdmiTx1_Stream::PixelClk, XV_HdmiTx1::Stream, XV_HdmiTx1_Stream::Video.
Referenced by XV_HdmiTx1_SetStream.
int XV_HdmiTx1_Scrambler(XV_HdmiTx1 *InstancePtr)
This function controls the scrambler.
Requires TMDSClock to be up to date in order to force enable scrambler when TMDSClock > 340MHz. InstancePtr is a pointer to the XV_HdmiTx1 core instance. XST_SUCCESS if HDMI 2.0XST_FAILURE if HDMI 1.4 None.
References XV_HdmiTx1_Stream::IsScrambled, XV_HdmiTx1_Stream::OverrideScrambler, XV_HdmiTx1_Stream::ScdcSupport, XV_HdmiTx1::Stream, XV_HdmiTx1_Stream::TMDSClock, XV_HdmiTx1_DdcRead, XV_HdmiTx1_DdcWrite, XV_HdmiTx1_SetScrambler.
Referenced by XV_HdmiTx1_SetStream.
int XV_HdmiTx1_ClockRatio(XV_HdmiTx1 *InstancePtr)
This function controls the TMDS clock ratio.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. XST_SUCCESS if HDMI 2.0XST_FAILURE if HDMI 1.4 None.
References XV_HdmiTx1_Stream::ScdcSupport, XV_HdmiTx1::Stream, XV_HdmiTx1_Stream::TMDSClockRatio, XV_HdmiTx1_DdcRead, XV_HdmiTx1_DdcWrite.
Referenced by XV_HdmiTx1_SetStream.
int XV_HdmiTx1_DetectHdmi20(XV_HdmiTx1 *InstancePtr)
This function detects connected sink is a HDMI 2.0/HDMI 1.4 sink device and sets appropriate flag in the TX stream.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. XST_SUCCESS if HDMI 2.0XST_FAILURE if HDMI 1.4 None.
References XV_HdmiTx1_Stream::ScdcSupport, XV_HdmiTx1::Stream, XV_HdmiTx1_DdcWrite.
void XV_HdmiTx1_ShowSCDC(XV_HdmiTx1 *InstancePtr)
This function shows the sinks SCDC registers.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. None.
References XV_HdmiTx1_DdcRead, XV_HdmiTx1_DdcWrite.
u32 XV_HdmiTx1_SetStream(XV_HdmiTx1 *InstancePtr, XVidC_VideoTiming VideoTiming, XVidC_FrameRate FrameRate, XVidC_ColorFormat ColorFormat, XVidC_ColorDepth Bpc, XVidC_PixelsPerClock Ppc, XVidC_3DInfo *Info3D, u8 FVaFactor, u8 VrrEnabled, u8 CnmvrrEnabled, u64 *TmdsClock)
This function sets the HDMI TX stream parameters.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. VideoTiming specifies video timing. FrameRate specifies frame rate. ColorFormat specifies the type of color format. 0 = XVIDC_CSF_RGB1 = XVIDC_CSF_YCRCB_4442 = XVIDC_CSF_YCRCB_4223 = XVIDC_CSF_YCRCB_420 Bpc specifies the color depth/bits per color component. 6 = XVIDC_BPC_68 = XVIDC_BPC_810 = XVIDC_BPC_1012 = XVIDC_BPC_1216 = XVIDC_BPC_16 Ppc specifies the pixel per clock. 4 = XVIDC_PPC_4 Info3D 3D info FVaFactor - Fast Video Active Factor VrrEnabled - VRR is enabled or not CnmvrrEnabled - Negative VRR supported flag TmdsClock - reference clock calculated based on the input parameters. XST_SUCCESS on success else XST_FAILURE None.
References XV_HdmiTx1_Stream::IsScrambled, XV_HdmiTx1_Stream::ScdcSupport, XV_HdmiTx1::Stream, XV_HdmiTx1_Stream::TMDSClock, XV_HdmiTx1_Stream::TMDSClockRatio, XV_HdmiTx1_Stream::Video, XV_HdmiTx1_ClockRatio, XV_HdmiTx1_GetTmdsClk, XV_HdmiTx1_Scrambler, XV_HdmiTx1_SetColorDepth, XV_HdmiTx1_SetColorFormat, XV_HdmiTx1_SetPixelRate.
void XV_HdmiTx1_INT_VRST(XV_HdmiTx1 *InstancePtr, u8 Reset)
This function asserts or releases the HDMI TX Internal VRST.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Reset specifies TRUE/FALSE value to either assert or release HDMI TX Internal VRST. None. The reset output of the PIO is inverted. When the system is in reset, the PIO output is cleared and this will reset the HDMI TX. Therefore, clearing the PIO reset output will assert the HDMI Internal video reset. C-style signature: void XV_HdmiTx1_INT_VRST(XV_HdmiTx1 *InstancePtr, u8 Reset)
References XV_HDMITX1_PIO_OUT_CLR_OFFSET, XV_HDMITX1_PIO_OUT_INT_VRST_MASK, XV_HDMITX1_PIO_OUT_SET_OFFSET, XV_HdmiTx1_WriteReg.
void XV_HdmiTx1_INT_LRST(XV_HdmiTx1 *InstancePtr, u8 Reset)
This function asserts or releases the HDMI TX Internal LRST.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Reset specifies TRUE/FALSE value to either assert or release HDMI TX Internal LRST. None. The reset output of the PIO is inverted. When the system is in reset, the PIO output is cleared and this will reset the HDMI TX. Therefore, clearing the PIO reset output will assert the HDMI Internal link reset. C-style signature: void XV_HdmiTx1_INT_VRST(XV_HdmiTx1 *InstancePtr, u8 Reset)
References XV_HDMITX1_PIO_OUT_CLR_OFFSET, XV_HDMITX1_PIO_OUT_INT_LRST_MASK, XV_HDMITX1_PIO_OUT_SET_OFFSET, XV_HdmiTx1_WriteReg.
void XV_HdmiTx1_EXT_VRST(XV_HdmiTx1 *InstancePtr, u8 Reset)
This function asserts or releases the HDMI TX External VRST.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Reset specifies TRUE/FALSE value to either assert or release HDMI TX External VRST. None. The reset output of the PIO is inverted. When the system is in reset, the PIO output is cleared and this will reset the HDMI TX. Therefore, clearing the PIO reset output will assert the HDMI external video reset. C-style signature: void XV_HdmiTx1_EXT_VRST(XV_HdmiTx1 *InstancePtr, u8 Reset)
References XV_HDMITX1_PIO_OUT_CLR_OFFSET, XV_HDMITX1_PIO_OUT_EXT_VRST_MASK, XV_HDMITX1_PIO_OUT_SET_OFFSET, XV_HdmiTx1_WriteReg.
void XV_HdmiTx1_EXT_SYSRST(XV_HdmiTx1 *InstancePtr, u8 Reset)
This function asserts or releases the HDMI TX External SYSRST.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Reset specifies TRUE/FALSE value to either assert or release HDMI TX External SYSRST. None. The reset output of the PIO is inverted. When the system is in reset, the PIO output is cleared and this will reset the HDMI TX. Therefore, clearing the PIO reset output will assert the HDMI External system reset. C-style signature: void XV_HdmiTx1_EXT_SYSRST(XV_HdmiTx1 *InstancePtr, u8 Reset)
References XV_HDMITX1_PIO_OUT_CLR_OFFSET, XV_HDMITX1_PIO_OUT_EXT_SYSRST_MASK, XV_HDMITX1_PIO_OUT_SET_OFFSET, XV_HdmiTx1_WriteReg.
void XV_HdmiTx1_SetGcpAvmuteBit(XV_HdmiTx1 *InstancePtr)
This function sets the HDMI TX AUX GCP register AVMUTE bit.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. None.
References XV_HDMITX1_PIO_OUT_GCP_AVMUTE_MASK, XV_HDMITX1_PIO_OUT_SET_OFFSET, XV_HdmiTx1_WriteReg.
void XV_HdmiTx1_ClearGcpAvmuteBit(XV_HdmiTx1 *InstancePtr)
This function clears the HDMI TX AUX GCP register AVMUTE bit.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. None.
References XV_HDMITX1_PIO_OUT_CLR_OFFSET, XV_HDMITX1_PIO_OUT_GCP_AVMUTE_MASK, XV_HdmiTx1_WriteReg.
void XV_HdmiTx1_SetGcpClearAvmuteBit(XV_HdmiTx1 *InstancePtr)
This function sets the HDMI TX AUX GCP register CLEAR_AVMUTE bit.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. None.
References XV_HDMITX1_PIO_OUT_GCP_CLEARAVMUTE_MASK, XV_HDMITX1_PIO_OUT_SET_OFFSET, XV_HdmiTx1_WriteReg.
void XV_HdmiTx1_ClearGcpClearAvmuteBit(XV_HdmiTx1 *InstancePtr)
This function clears the HDMI TX AUX GCP register CLEAR_AVMUTE bit.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. None.
References XV_HDMITX1_PIO_OUT_CLR_OFFSET, XV_HDMITX1_PIO_OUT_GCP_CLEARAVMUTE_MASK, XV_HdmiTx1_WriteReg.
void XV_HdmiTx1_SetPixelRate(XV_HdmiTx1 *InstancePtr)
This function sets the pixel rate at output.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. None.
References XV_HdmiTx1_Config::BaseAddress, XV_HdmiTx1::Config, XV_HdmiTx1_Stream::CorePixPerClk, XV_HdmiTx1::Stream, XV_HDMITX1_PIO_OUT_MSK_OFFSET, XV_HDMITX1_PIO_OUT_OFFSET, XV_HDMITX1_PIO_OUT_PIXEL_RATE_MASK, XV_HDMITX1_PIO_OUT_PIXEL_RATE_SHIFT, XV_HdmiTx1_WriteReg.
Referenced by XV_HdmiTx1_SetStream.
void XV_HdmiTx1_SetSampleRate(XV_HdmiTx1 *InstancePtr, u8 SampleRate)
This function sets the sample rate at output.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. SampleRate specifies the value that needs to be set. 2 samples per clock3 samples per clock.5 samples per clock. None. None.
References XV_HdmiTx1_Config::BaseAddress, XV_HdmiTx1::Config, XV_HdmiTx1_Stream::SampleRate, XV_HdmiTx1::Stream, XV_HDMITX1_PIO_OUT_MSK_OFFSET, XV_HDMITX1_PIO_OUT_OFFSET, XV_HDMITX1_PIO_OUT_SAMPLE_RATE_MASK, XV_HDMITX1_PIO_OUT_SAMPLE_RATE_SHIFT, XV_HdmiTx1_WriteReg.
void XV_HdmiTx1_SetColorFormat(XV_HdmiTx1 *InstancePtr)
This function sets the color format.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. None.
References XV_HdmiTx1_Config::BaseAddress, XV_HdmiTx1::Config, XV_HdmiTx1::Stream, XV_HdmiTx1_Stream::Video, XV_HDMITX1_PIO_OUT_COLOR_SPACE_MASK, XV_HDMITX1_PIO_OUT_COLOR_SPACE_SHIFT, XV_HDMITX1_PIO_OUT_MSK_OFFSET, XV_HDMITX1_PIO_OUT_OFFSET, XV_HdmiTx1_WriteReg.
Referenced by XV_HdmiTx1_SetStream.
void XV_HdmiTx1_SetColorDepth(XV_HdmiTx1 *InstancePtr)
This function sets the color depth.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. None.
References XV_HdmiTx1_Config::BaseAddress, XV_HdmiTx1::Config, XV_HdmiTx1::Stream, XV_HdmiTx1_Stream::Video, XV_HDMITX1_PIO_OUT_COLOR_DEPTH_MASK, XV_HDMITX1_PIO_OUT_COLOR_DEPTH_SHIFT, XV_HDMITX1_PIO_OUT_MSK_OFFSET, XV_HDMITX1_PIO_OUT_OFFSET, XV_HdmiTx1_WriteReg.
Referenced by XV_HdmiTx1_SetStream.
void XV_HdmiTx1_DdcInit(XV_HdmiTx1 *InstancePtr, u32 Frequency)
This function prepares TX DDC peripheral to use.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Frequency specifies the value that needs to be set. None. None.
References XV_HdmiTx1_Config::BaseAddress, XV_HdmiTx1::Config, XV_HDMITX1_DDC_CTRL_CLK_DIV_MASK, XV_HDMITX1_DDC_CTRL_OFFSET, XV_HdmiTx1_WriteReg.
Referenced by XV_HdmiTx1_SetAxiClkFreq.
int XV_HdmiTx1_DdcGetAck(XV_HdmiTx1 *InstancePtr)
This function gets the acknowledge flag.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Non-zero if the ACK bit is set (acknowledgment received).Zero if the ACK bit is not set. None.
References XV_HdmiTx1_Config::BaseAddress, XV_HdmiTx1::Config, XV_HDMITX1_DDC_STA_ACK_MASK, XV_HDMITX1_DDC_STA_OFFSET, XV_HdmiTx1_ReadReg.
Referenced by XV_HdmiTx1_DdcRead, XV_HdmiTx1_DdcWrite.
int XV_HdmiTx1_DdcWaitForDone(XV_HdmiTx1 *InstancePtr)
This function waits for the done flag to be set.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. XST_SUCCESS if the DDC operation completed successfully. XST_FAILURE if the operation timed out or the DDC controller was not running This function blocks until the DDC operation completes or fails.
References XV_HdmiTx1_Config::BaseAddress, XV_HdmiTx1::Config, XV_HDMITX1_DDC_CTRL_OFFSET, XV_HDMITX1_DDC_CTRL_RUN_MASK, XV_HDMITX1_DDC_STA_DONE_MASK, XV_HDMITX1_DDC_STA_OFFSET, XV_HDMITX1_DDC_STA_TIMEOUT_MASK, XV_HdmiTx1_ReadReg, XV_HdmiTx1_WriteReg.
Referenced by XV_HdmiTx1_DdcRead, XV_HdmiTx1_DdcWrite.
void XV_HdmiTx1_DdcWriteCommand(XV_HdmiTx1 *InstancePtr, u32 Cmd)
This function writes data into the command fifo.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Cmd is a 32-bit command to be written to the DDC command FIFO None.
References XV_HdmiTx1_Config::BaseAddress, XV_HdmiTx1::Config, XV_HDMITX1_DDC_CMD_OFFSET, XV_HDMITX1_DDC_CTRL_OFFSET, XV_HDMITX1_DDC_CTRL_RUN_MASK, XV_HDMITX1_DDC_STA_CMD_FULL, XV_HDMITX1_DDC_STA_OFFSET, XV_HdmiTx1_ReadReg, XV_HdmiTx1_WriteReg.
Referenced by XV_HdmiTx1_DdcRead, XV_HdmiTx1_DdcWrite.
u8 XV_HdmiTx1_DdcReadData(XV_HdmiTx1 *InstancePtr)
This function reads data from the data fifo.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. A byte of data read from the DDC FIFO if available.0 if the DDC engine is not running or the FIFO is empty None.
References XV_HdmiTx1_Config::BaseAddress, XV_HdmiTx1::Config, XV_HDMITX1_DDC_CTRL_OFFSET, XV_HDMITX1_DDC_CTRL_RUN_MASK, XV_HDMITX1_DDC_DAT_OFFSET, XV_HDMITX1_DDC_STA_DAT_EMPTY, XV_HDMITX1_DDC_STA_OFFSET, XV_HdmiTx1_ReadReg.
Referenced by XV_HdmiTx1_DdcRead.
int XV_HdmiTx1_DdcWrite(XV_HdmiTx1 *InstancePtr, u8 Slave, u16 Length, u8 *Buffer, u8 Stop)
This function writes data from DDC peripheral from given slave address.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Slave specifies the slave address from where data needs to be read. Length specifies number of bytes to be read. Buffer specifies a pointer to u8 variable that will be filled with data. Stop specifies the stop flag which is either TRUE/FALSE. XST_SUCCESS if an acknowledgement received and timeout.XST_FAILURE if no acknowledgement received. None.
References XV_HDMITX1_DDC_CMD_STP_TOKEN, XV_HDMITX1_DDC_CMD_STR_TOKEN, XV_HDMITX1_DDC_CMD_WR_TOKEN, XV_HdmiTx1_DdcDisable, XV_HdmiTx1_DdcEnable, XV_HdmiTx1_DdcGetAck, XV_HdmiTx1_DdcIntrDisable, XV_HdmiTx1_DdcWaitForDone, XV_HdmiTx1_DdcWriteCommand, XV_HdmiTx1_PioIntrDisable, XV_HdmiTx1_PioIntrEnable.
Referenced by XV_HdmiTx1_ClockRatio, XV_HdmiTx1_DdcReadReg, XV_HdmiTx1_DdcWriteField, XV_HdmiTx1_DetectHdmi20, XV_HdmiTx1_Scrambler, XV_HdmiTx1_ShowSCDC.
int XV_HdmiTx1_DdcRead(XV_HdmiTx1 *InstancePtr, u8 Slave, u16 Length, u8 *Buffer, u8 Stop)
This function reads data from DDC peripheral from given slave address.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Slave specifies the slave address from where data needs to be read. Length specifies number of bytes to be read. Buffer specifies a pointer to u8 variable that will be filled with data. Stop specifies the stop flag which is either TRUE/FALSE. XST_SUCCESS if an acknowledgement received and timeout.XST_FAILURE if no acknowledgement received. None.
References XV_HDMITX1_DDC_CMD_RD_TOKEN, XV_HDMITX1_DDC_CMD_STP_TOKEN, XV_HDMITX1_DDC_CMD_STR_TOKEN, XV_HDMITX1_DDC_CMD_WR_TOKEN, XV_HdmiTx1_DdcDisable, XV_HdmiTx1_DdcEnable, XV_HdmiTx1_DdcGetAck, XV_HdmiTx1_DdcIntrDisable, XV_HdmiTx1_DdcReadData, XV_HdmiTx1_DdcWaitForDone, XV_HdmiTx1_DdcWriteCommand, XV_HdmiTx1_PioIntrDisable, XV_HdmiTx1_PioIntrEnable.
Referenced by XV_HdmiTx1_ClockRatio, XV_HdmiTx1_DdcReadReg, XV_HdmiTx1_DdcWriteField, XV_HdmiTx1_Scrambler, XV_HdmiTx1_ShowSCDC.
int XV_HdmiTx1_DdcReadReg(XV_HdmiTx1 *InstancePtr, u8 Slave, u16 Length, u8 RegAddr, u8 *Buffer)
This function reads specified register from DDC peripheral from given slave address.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Slave specifies the slave address from where data needs to be read. Length specifies number of bytes to be read. RegAddr specifies the register address from where data needs to be read. Buffer specifies a pointer to u8 variable that will be filled with data. XST_SUCCESS if an acknowledgement received and timeout.XST_FAILURE if no acknowledgement received. None.
References XV_HdmiTx1_DdcRead, XV_HdmiTx1_DdcWrite.
Referenced by XV_HdmiTx1_GetScdcEdRegisters.
int XV_HdmiTx1_DdcWriteField(XV_HdmiTx1 *InstancePtr, XV_HdmiTx1_ScdcFieldType Field, u8 Value)
This function writes the specified SCDC Field.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Field specifies the fields from SCDC channels to be written Value specifies the values to be written XST_SUCCESSXST_FAILURE None.
References XV_HdmiTx1_ScdcField::Mask, XV_HdmiTx1_ScdcField::Offset, XV_HdmiTx1_ScdcField::Shift, XV_HdmiTx1_DdcRead, XV_HdmiTx1_DdcWrite.
void XV_HdmiTx1_Aux_Dsc_Send_Header(XV_HdmiTx1 *InstancePtr, u32 Data)
This function transmits the DSC packet header.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Data value to be written None. None.
References XV_HdmiTx1_Config::BaseAddress, XV_HdmiTx1::Config, XV_HdmiTx1_WriteReg.
void XV_HdmiTx1_Aux_Dsc_Send_Data(XV_HdmiTx1 *InstancePtr, u32 Data)
This function transmits the DSC packet data.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Data value to be written None. None.
References XV_HdmiTx1_Config::BaseAddress, XV_HdmiTx1::Config, XV_HdmiTx1_WriteReg.
u32 XV_HdmiTx1_AuxSend(XV_HdmiTx1 *InstancePtr)
This function transmits the infoframes generated by the processor.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. XST_SUCCESS if infoframes transmitted successfully.XST_FAILURE if AUX FIFO is full. None.
References XV_HdmiTx1::Aux, XV_HdmiTx1_Config::BaseAddress, XV_HdmiTx1::Config, XV_HDMITX1_AUX_DAT_OFFSET, XV_HDMITX1_AUX_STA_FIFO_FUL_MASK, XV_HDMITX1_AUX_STA_OFFSET, XV_HDMITX1_AUX_STA_PKT_RDY_MASK, XV_HdmiTx1_ReadReg, XV_HdmiTx1_WriteReg.
void XV_HdmiTx1_Info(XV_HdmiTx1 *InstancePtr)
This function prints stream and timing information on STDIO/Uart console.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. None.
References XV_HdmiTx1::Stream, XV_HdmiTx1_Stream::Video.
void XV_HdmiTx1_DebugInfo(XV_HdmiTx1 *InstancePtr)
This function prints debug information on STDIO/UART console.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. None.
References XV_HdmiTx1_Config::BaseAddress, XV_HdmiTx1::Config, XV_HDMITX1_ANLZ_HBP_HS_HPB_SZ_MASK, XV_HDMITX1_ANLZ_HBP_HS_HPB_SZ_SHIFT, XV_HDMITX1_ANLZ_HBP_HS_HS_SZ_MASK, XV_HDMITX1_ANLZ_HBP_HS_OFFSET, XV_HDMITX1_ANLZ_LN_ACT_ACT_SZ_MASK, XV_HDMITX1_ANLZ_LN_ACT_LN_SZ_MASK, XV_HDMITX1_ANLZ_LN_ACT_LN_SZ_SHIFT, XV_HDMITX1_ANLZ_LN_ACT_OFFSET, XV_HDMITX1_DBG_STS_OFFSET, XV_HDMITX1_PIO_IN_BRDG_LOCKED_MASK, XV_HDMITX1_PIO_IN_OFFSET, XV_HDMITX1_PIO_OUT_MODE_MASK, XV_HDMITX1_PIO_OUT_OFFSET, XV_HdmiTx1_ReadReg, XV_HDMITX1_VCKE_SYS_CNT_OFFSET, XV_HDMITX1_VER_ID_OFFSET, XV_HDMITX1_VER_VERSION_OFFSET.
void XV_HdmiTx1_RegisterDebug(XV_HdmiTx1 *InstancePtr)
This function prints out HDMI TX register.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. None.
References XV_HdmiTx1_Config::BaseAddress, XV_HdmiTx1::Config, XV_HDMITX1_MASK_BLUE_OFFSET, XV_HdmiTx1_ReadReg.
int XV_HdmiTx1_IsStreamScrambled(XV_HdmiTx1 *InstancePtr)
This function provides status of the stream.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. TRUE = Scrambled.FALSE = Not scrambled. None.
References XV_HdmiTx1_Stream::IsScrambled, XV_HdmiTx1::Stream.
int XV_HdmiTx1_IsStreamConnected(XV_HdmiTx1 *InstancePtr)
This function provides the stream connected status.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. TRUE = Stream is connected.FALSE = Stream is connected. None.
References XV_HdmiTx1_Stream::IsConnected, XV_HdmiTx1::Stream.
void XV_HdmiTx1_TMDSACRStart(XV_HdmiTx1 *InstancePtr)
This function Starts the internal ACR module for TMDS.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None.
References XV_HdmiTx1_Stream::Audio, XV_HdmiTx1::Stream, XV_HdmiTx1_Stream::TMDSClock, XV_HDMITX1_AUD_ACR_N_OFFSET, XV_HDMITX1_AUD_CTRL_CLR_OFFSET, XV_HDMITX1_AUD_CTRL_SET_OFFSET, XV_HdmiTx1_WriteReg.
Referenced by XV_HdmiTx1_AudioEnable.
int XV_HdmiTx1_SetAudioChannels(XV_HdmiTx1 *InstancePtr, u8 Value)
This function sets the active audio channels.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Value is number of active audio channels XST_SUCCESS if active channels were set.XST_FAILURE if no active channels were set. None.
References XV_HDMITX1_3DAUD_CTRL_CH_MASK, XV_HDMITX1_3DAUD_CTRL_CH_SHIFT, XV_HDMITX1_AUD_CTRL_CH_MASK, XV_HDMITX1_AUD_CTRL_CH_SHIFT, XV_HDMITX1_AUD_CTRL_CLR_OFFSET, XV_HDMITX1_AUD_CTRL_OFFSET, XV_HDMITX1_AUD_CTRL_RUN_MASK, XV_HDMITX1_AUD_CTRL_SET_OFFSET, XV_HdmiTx1_AudioEnable, XV_HdmiTx1_ReadReg, XV_HdmiTx1_WriteReg.
u32 XV_HdmiTxSs1_GetAudioCtsVal(XV_HdmiTx1 *InstancePtr)
This function gets the Generated ACR CTS Value.
InstancePtr is a pointer to the XV_HdmiTxSs1 core instance. Generated ACR CTS Value None.
References XV_HDMITX1_AUD_ACR_CTS_OFFSET, XV_HdmiTx1_ReadReg.
u32 XV_HdmiTxSs1_GetAudioNVal(XV_HdmiTx1 *InstancePtr)
This function gets the programmed ACR N Value.
InstancePtr is a pointer to the XV_HdmiTxSs1 core instance. Programmed ACR N Value None.
References XV_HDMITX1_AUD_ACR_N_OFFSET, XV_HdmiTx1_ReadReg.
int XV_HdmiTx1_SetAudioFormat(XV_HdmiTx1 *InstancePtr, XV_HdmiTx1_AudioFormatType Value)
This function sets the active audio format.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Value specifies the audio format XST_SUCCESS if active channels were set.XST_FAILURE if no active channels were set. None.
References XV_HDMITX1_AUD_CTRL_3DAUDFMT_EN, XV_HDMITX1_AUD_CTRL_3DAUDFMT_MASK, XV_HDMITX1_AUD_CTRL_AUDFMT_MASK, XV_HDMITX1_AUD_CTRL_CLR_OFFSET, XV_HDMITX1_AUD_CTRL_OFFSET, XV_HDMITX1_AUD_CTRL_RUN_MASK, XV_HDMITX1_AUD_CTRL_SET_OFFSET, XV_HdmiTx1_AudioEnable, XV_HdmiTx1_ReadReg, XV_HdmiTx1_WriteReg.
XV_HdmiTx1_AudioFormatType XV_HdmiTx1_GetAudioFormat(XV_HdmiTx1 *InstancePtr)
This function gets the active audio format.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Active audio format of HDMI Tx None.
References XV_HDMITX1_AUD_CTRL_3DAUDFMT_MASK, XV_HDMITX1_AUD_CTRL_AUDFMT_MASK, XV_HDMITX1_AUD_CTRL_AUDFMT_SHIFT, XV_HDMITX1_AUD_CTRL_OFFSET, XV_HdmiTx1_ReadReg.
u8* XV_HdmiTx1_GetScdcEdRegisters(XV_HdmiTx1 *InstancePtr)
This function reads the CED and RSED registers from the sink and returns the pointer to the data structure which stores the CED related readings (from SCDC register 0x50 to 0x5A).
InstancePtr is a pointer to the XHdmi_Tx core instance. Returns a pointer to the local buffer containing the SCDC character error detection readings Reading the SCDC registers will clear the values at the sink
References XV_HdmiTx1_Stream::ScdcEd, XV_HdmiTx1::Stream, XV_HdmiTx1_DdcReadReg.
XV_HdmiC_VideoTimingExtMeta* XV_HdmiTx1_GetVidTimingExtMeta(XV_HdmiTx1 *InstancePtr)
This function returns Video Timing Extended Metadata.
InstancePtr is a pointer to the XHdmiTx1 core instance. XV_HdmiC_VideoTimingExtMeta None.
References XV_HdmiTx1::VrrIF.
Referenced by XV_HdmiTx1_GenerateCustomVideoTimingExtMetaIF, XV_HdmiTx1_GenerateVideoTimingExtMetaIF.
void XV_HdmiTx1_GenerateVideoTimingExtMetaIF(XV_HdmiTx1 *InstancePtr, XV_HdmiC_VideoTimingExtMeta *ExtMeta)
This function configures the HDMI transmitter with extended video timing metadata such as QMS (Quick Media Switching), VRR (Variable Refresh Rate), and other timing-related parameters.
It prepares the VTEM data based on the provided metadata structure and writes it to the appropriate auxiliary registers. InstancePtr is a pointer to the XHdmiTx1 core instance. ExtMeta is a pointer to the structure containing extended video timing metadata. None
References XV_HdmiTx1_Config::BaseAddress, XV_HdmiTx1::Config, XV_HDMITX1_AUX_CTRL_DATASET_LEN_EN_MASK, XV_HDMITX1_AUX_CTRL_OFFSET, XV_HDMITX1_AUX_CTRL_SYNC_EN_MASK, XV_HDMITX1_AUX_VTEM_OFFSET, XV_HdmiTx1_GetVidTimingExtMeta, XV_HdmiTx1_ReadReg, XV_HdmiTx1_WriteReg.
void XV_HdmiTx1_GenerateCustomVideoTimingExtMetaIF(XV_HdmiTx1 *InstancePtr, XV_HdmiC_VideoTimingExtMeta *ExtMeta, u16 Sync, u16 DataSetLen)
This function allows fine-grained control over the VTEM InfoFrame generation by accepting custom values for the sync enable and dataset length fields.
It is useful for debugging or advanced HDMI configurations where default behavior needs to be overridden. InstancePtr is a pointer to the XHdmiTx1 core instance. ExtMeta is a pointer to the structure containing extended video timing metadata. Sync Value to set the Sync Enable bit (0 or 1). DataSetLen Value to set the Dataset Length Enable bit (0 or 1). None
References XV_HdmiTx1_Config::BaseAddress, XV_HdmiTx1::Config, XV_HDMITX1_AUX_CTRL_DATASET_LEN_EN_MASK, XV_HDMITX1_AUX_CTRL_OFFSET, XV_HDMITX1_AUX_CTRL_SYNC_EN_MASK, XV_HDMITX1_AUX_VTEM_OFFSET, XV_HdmiTx1_GetVidTimingExtMeta, XV_HdmiTx1_ReadReg, XV_HdmiTx1_WriteReg.
XV_HdmiC_SrcProdDescIF* XV_HdmiTx1_GetSrcProdDescIF(XV_HdmiTx1 *InstancePtr)
This function returns a pointer to the SrcProdDescIF which contains the Source Product Descriptor InfoFrame data used in HDMI VRR (Variable Refresh Rate) or other auxiliary metadata transmission.
InstancePtr is a pointer to the XHdmiTx1 core instance. XV_HdmiC_SrcProdDescIF None
References XV_HdmiTx1::VrrIF.
Referenced by XV_HdmiTx1_GenerateSrcProdDescInfoframe.
void XV_HdmiTx1_GenerateSrcProdDescInfoframe(XV_HdmiTx1 *InstancePtr, XV_HdmiC_SrcProdDescIF *SpdIfPtr)
This function configures the HDMI transmitter with Source Product Descriptor metadata, including FreeSync and FreeSync Pro capabilities.
It prepares the data based on the provided structure and writes it to the appropriate auxiliary registers InstancePtr is a pointer to the XHdmiTx1 core instance. SpdIfPtr is a pointer to the structure containing SPD InfoFrame data. None
References XV_HdmiTx1_Config::BaseAddress, XV_HdmiTx1::Config, XV_HDMITX1_AUX_FSYNC_OFFSET, XV_HDMITX1_AUX_FSYNC_PRO_OF, XV_HdmiTx1_GetSrcProdDescIF, XV_HdmiTx1_WriteReg.