xv_hdmitx1.h
XV_HdmiTx1_HandlerType
XV_HdmiTx1_State
XV_HdmiTx1_AudioFormatType
XV_HdmiTx1_ScdcFieldType
XV_HdmiTx1_CTSNSource
XV_HDMITX1_H_
Prevent circular inclusions by using protection macros.
XV_HDMITX1_DDC_ADDRESS
ANSI_COLOR_RED
ANSI_COLOR_GREEN
ANSI_COLOR_YELLOW
ANSI_COLOR_BLUE
ANSI_COLOR_MAGENTA
ANSI_COLOR_CYAN
ANSI_COLOR_WHITE
ANSI_COLOR_RESET
XV_HdmiTx1_GetTime1Ms
This macro returns the clock cycles required to count up to 1MS with respect to AXI Lite Frequency.
InstancePtr is a pointer to the XV_HdmiTX1 core instance. None.
Referenced by XV_HdmiTx1_CfgInitialize.
XV_HdmiTx1_GetTime10Ms
This macro returns the clock cycles required to count up to 10MS with respect to AXI Lite Frequency.
InstancePtr is a pointer to the XV_HdmiTX core instance. None.
XV_HdmiTx1_GetVersion
This macro reads the TX version.
InstancePtr is a pointer to the XV_HdmiTX1 core instance. None.
XV_HdmiTx1_Reset
This macro asserts or releases the HDMI TX reset.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Reset specifies TRUE/FALSE value to either assert or release HDMI TX reset. None. The reset output of the PIO is inverted. When the system is in reset, the PIO output is cleared and this will reset the HDMI . Therefore, clearing the PIO reset output will assert the HDMI link and video reset. C-style signature: void XV_HdmiTx1_Reset(XV_HdmiTx1 *InstancePtr, u8 Reset)
XV_HdmiTx1_SetScrambler
This macro controls the HDMI TX Scrambler.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. SetClr specifies TRUE/FALSE value to either set ON or clear Scrambler. None. C-style signature: void XV_HdmiTx1_SetScrambler(XV_HdmiTx1 *InstancePtr, u8 SetClr)
Referenced by XV_HdmiTx1_Scrambler.
XV_HdmiTx1_Bridge_yuv420
This macro controls the YUV420 mode for video bridge.
InstancePtr is a pointer to the XHdmi_Tx core instance. SetClr specifies TRUE/FALSE value to either enable or disable the YUV 420 Support. None. C-style signature: void XV_HdmiTx1_Bridge_yuv420(XV_HdmiTx1 *InstancePtr, u8 SetClr)
XV_HdmiTx1_Bridge_pixel
This macro controls the Pixel Repeat mode for video bridge.
InstancePtr is a pointer to the XHdmi_Tx core instance. SetClr specifies TRUE/FALSE value to either enable or disable the Pixel Repetition Support. None. C-style signature: void XV_HdmiTx1_Bridge_pixel(XV_HdmiTx1 *InstancePtr, u8 SetClr)
XV_HdmiTx1_PioEnable
This macro enables the HDMI TX PIO peripheral.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. C-style signature: void XV_HdmiTx1_PioEnable(XV_HdmiTx1 *InstancePtr)
Referenced by XV_HdmiTx1_Start.
XV_HdmiTx1_PioDisable
This macro disables the HDMI TX PIO peripheral.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. C-style signature: void XV_HdmiTx1_PioDisable(XV_HdmiTx1 *InstancePtr)
Referenced by XV_HdmiTx1_CfgInitialize, XV_HdmiTx1_Stop.
XV_HdmiTx1_PioIntrEnable
This macro enables interrupt in the HDMI TX PIO peripheral.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. C-style signature: void XV_HdmiTx1_PioIntrEnable(XV_HdmiTx1 *InstancePtr)
Referenced by XV_HdmiTx1_DdcRead, XV_HdmiTx1_DdcWrite, XV_HdmiTx1_Start.
XV_HdmiTx1_PioIntrDisable
This macro disables interrupt in the HDMI TX PIO peripheral.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. C-style signature: void XV_HdmiTx1_PioIntrDisable(XV_HdmiTx1 *InstancePtr)
Referenced by XV_HdmiTx1_DdcRead, XV_HdmiTx1_DdcWrite, XV_HdmiTx1_Stop.
XV_HdmiTx1_PioIntrClear
This macro clears HDMI TX PIO interrupt.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. C-style signature: void XV_HdmiTx1_PioIntrClear(XV_HdmiTx1 *InstancePtr)
Referenced by XV_HdmiTx1_CfgInitialize.
XV_HdmiTx1_DdcEnable
This macro enables the HDMI TX Display Data Channel (DDC) peripheral.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. C-style signature: void XV_HdmiTx1_DdcEnable(XV_HdmiTx1 *InstancePtr)
Referenced by XV_HdmiTx1_DdcRead, XV_HdmiTx1_DdcWrite.
XV_HdmiTx1_DdcDisable
This macro disables the HDMI TX Display Data Channel (DDC) peripheral.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. C-style signature: void XV_HdmiTx1_DdcDisable(XV_HdmiTx1 *InstancePtr)
Referenced by XV_HdmiTx1_CfgInitialize, XV_HdmiTx1_DdcRead, XV_HdmiTx1_DdcWrite.
XV_HdmiTx1_DdcIntrEnable
This macro enables interrupt in the HDMI TX DDC peripheral.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. C-style signature: void XV_HdmiTx1_DdcIntrEnable(XV_HdmiTx1 *InstancePtr)
XV_HdmiTx1_DdcIntrDisable
This macro disables interrupt in the HDMI TX DDC peripheral.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. C-style signature: void XV_HdmiTx1_DdcIntrDisable(XV_HdmiTx1 *InstancePtr)
Referenced by XV_HdmiTx1_DdcRead, XV_HdmiTx1_DdcWrite.
XV_HdmiTx1_DdcIntrClear
This macro clears HDMI TX DDC interrupt.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. C-style signature: void XV_HdmiTx1_DdcIntrClear(XV_HdmiTx1 *InstancePtr)
Referenced by XV_HdmiTx1_CfgInitialize.
XV_HdmiTx1_AuxDisable
This macro disables the HDMI TX Auxiliary (AUX) peripheral.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. C-style signature: void XV_HdmiTx1_AuxDisable(XV_HdmiTx1 *InstancePtr)
Referenced by XV_HdmiTx1_CfgInitialize, XV_HdmiTx1_SetDviMode.
XV_HdmiTx1_AuxIntrEnable
This macro enables interrupt in the HDMI TX AUX peripheral.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. C-style signature: void XV_HdmiTx1_AuxIntrEnable(XV_HdmiTx1 *InstancePtr)
XV_HdmiTx1_VrrControl
This macro allows enabling/disabling of VRR in HDMI Tx.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. SetClr specifies TRUE/FALSE value to either enable or disable the VFP Event None. C-style signature: void XV_HdmiTx1_VrrControl(XV_HdmiTx1 *InstancePtr, u8 SetClr)
XV_HdmiTx1_FSyncControl
This macro allows enabling/disabling of FSync in HDMI Tx.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. SetClr specifies TRUE/FALSE value to either enable or disable the VFP Event None. C-style signature: void XV_HdmiTx1_FSyncControl(XV_HdmiTx1 *InstancePtr, u8 SetClr)
XV_HdmiTx1_DynHdr_DM_Enable
This macro enables the data mover for Dynamic HDR in HDMI Tx.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. C-style signature: void XV_HdmiTx1_DynHdr_DM_Enable(XV_HdmiTx1 *InstancePtr)
XV_HdmiTx1_DynHdr_DM_Disable
This macro disables the data mover for Dynamic HDR in HDMI Tx.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. C-style signature: void XV_HdmiTx1_DynHdr_DM_Disable(XV_HdmiTx1 *InstancePtr)
XV_HdmiTx1_DynHdr_Control
This macro allows enabling/disabling of Dynamic HDR in HDMI Tx.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. SetClr specifies TRUE/FALSE value to either enable or disable the Dynamic HDR None. C-style signature: void XV_HdmiTx1_DynHdrControl(XV_HdmiTx1 *InstancePtr, u8 SetClr)
XV_HdmiTx1_DynHdr_FAPA_Control
This macro allows enabling/disabling of FAPA Location Dynamic HDR in HDMI Tx.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. SetClr specifies TRUE/FALSE value for FAPA location. None. C-style signature: void XV_HdmiTx1_DynHdr_FAPA_Control(XV_HdmiTx1 *InstancePtr, u8 SetClr)
XV_HdmiTx1_DynHdr_GOF_Control
This macro allows enabling/disabling of GOF Dynamic HDR in HDMI Tx.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. SetClr specifies TRUE/FALSE value to either enable or disable the GOF (Graphics Overlay Flag) None. C-style signature: void XV_HdmiTx1_DynHdr_GOF_Control(XV_HdmiTx1 *InstancePtr, u8 SetClr)
XV_HdmiTx1_DynHdr_GOFVal_Control
This macro allows set/clear of GOF Value Dynamic HDR in HDMI Tx.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. SetClr specifies TRUE/FALSE value to either set or clear the GOF (Graphics Overlay Flag) Value None. C-style signature: void XV_HdmiTx1_DynHdr_GOFVal_Control(XV_HdmiTx1 *InstancePtr, u8 SetClr)
XV_HdmiTx1_DynHdr_MTW_Clear
This macro allows to set the MTW bit to clear it for Dynamic HDR in HDMI Tx.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. C-style signature: void XV_HdmiTx1_DynHdr_MTW_Clear(XV_HdmiTx1 *InstancePtr)
XV_HdmiTx1_DynHdr_GetReadStatus
This macro gets the read status of Data Mover for Dynamic HDR in HDMI Tx.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. u32 val - 0 means ok else memory read error C-style signature: u32 XV_HdmiTx1_DynHdr_GetReadStatus(XV_HdmiTx1 *InstancePtr)
XV_HdmiTx1_DynHdr_SetPacket
This macro sets the Header packet type and length for Dynamic HDR in HDMI Tx.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. PktLen is a u16 length of Dynamic HDR packet. PktType is a u16 Type of Dynamic HDR packet. None. C-style signature: void XV_HdmiTx1_DynHdr_SetPacket(XV_HdmiTx1 *InstancePtr, u16 PktLen, u16 PktType)
XV_HdmiTx1_DynHdr_SetAddr
This macro sets the buffer address for Dynamic HDR in HDMI Tx.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Addr is a u64 which contains the buffer address None. C-style signature: void XV_HdmiTx1_DynHdr_SetAddr(XV_HdmiTx1 *InstancePtr, u64 Addr)
XV_HdmiTx1_AuxIntrDisable
This macro disables interrupt in the HDMI TX AUX peripheral.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. C-style signature: void XV_HdmiTx1_AuxIntrDisable(XV_HdmiTx1 *InstancePtr)
XV_HdmiTx1_AudioDisable
This macro disables audio in HDMI TX core.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. C-style signature: void XV_HdmiTx1_AudioDisable(XV_HdmiTx1 *InstancePtr)
Referenced by XV_HdmiTx1_CfgInitialize, XV_HdmiTx1_SetDviMode.
XV_HdmiTx1_SetMode
This macro sets the mode bit.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. C-style signature: void XV_HdmiTx1_SetMode(XV_HdmiTx1 *InstancePtr)
Referenced by XV_HdmiTx1_SetHdmiTmdsMode.
XV_HdmiTx1_ClearMode
This macro clears the mode bit.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. C-style signature: void XV_HdmiTx1_ClearMode(XV_HdmiTx1 *InstancePtr)
Referenced by XV_HdmiTx1_SetDviMode.
XV_HdmiTx1_GetMode
This macro provides the current mode.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Current mode. 0 = DVI 1 = HDMI C-style signature: u8 XV_HdmiTx1_GetMode(XV_HdmiTx1 *InstancePtr)
XV_HdmiTx1_GetSampleRate
This macro provides the current sample rate.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Sample rate C-style signature: u8 XV_HdmiTx1_GetSampleRate(XV_HdmiTx1 *InstancePtr)
XV_HdmiTx1_GetAudioChannels
This macro provides the active audio channels.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Audio channels
XV_HdmiTx1_GetPixelPackingPhase
This macro provides the current pixel packing phase.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Pixel packing phase.
XV_HdmiTx1_MaskDisable
This macro disables video mask in HDMI TX core.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. C-style signature: void XV_HdmiTx1_MaskDisable(XV_HdmiTx1 *InstancePtr)
XV_HdmiTx1_MaskEnable
This macro enables video mask in HDMI TX core.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. C-style signature: void XV_HdmiTx1_MaskEnable(XV_HdmiTx1 *InstancePtr)
XV_HdmiTx1_MaskNoise
This macro enables or disables the noise in the video mask.
InstancePtr is a pointer to the XHdmi_Tx core instance. SetClr specifies TRUE/FALSE value to either enable or disable the Noise. None. C-style signature: void XV_HdmiTx1_MaskNoise(XV_HdmiTx1 *InstancePtr, u8 SetClr)
XV_HdmiTx1_MaskSetRed
This macro sets the red component value in the video mask.
InstancePtr is a pointer to the XHdmi_Tx core instance. Value None. C-style signature: void XV_HdmiTx1_MaskSetRed(XV_HdmiTx1 *InstancePtr, u16 Value)
XV_HdmiTx1_MaskSetGreen
This macro sets the green component value in the video mask.
InstancePtr is a pointer to the XHdmi_Tx core instance. Value None. C-style signature: void XV_HdmiTx1_MaskSetGreen(XV_HdmiTx1 *InstancePtr, u16 Value)
XV_HdmiTx1_MaskSetBlue
This macro sets the blue component value in the video mask.
InstancePtr is a pointer to the XHdmi_Tx core instance. Value None. C-style signature: void XV_HdmiTx1_MaskSetBlue(XV_HdmiTx1 *InstancePtr, u16 Value)
XV_HdmiTx1_IsMasked
This macro provides the current video mask mode.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Current mode. 0 = Video masking is disabled 1 = Video masking is enabled C-style signature: u8 XV_HdmiTx1_IsMasked(XV_HdmiTx1 *InstancePtr)
XV_HdmiTx1_DscControl
This macro allows enabling/disabling of DSC in HDMI-TX.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. SetClr specifies TRUE/FALSE value to either enable or disable the DSC None. C-style signature: void XV_HdmiTx1_DscControl(XV_HdmiTx1 *InstancePtr, u8 SetClr)
typedef void(* XV_HdmiTx1_Callback)(void *CallbackRef))(void *CallbackRef)
Callback type for Vsync event interrupt.
CallbackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. None. None.
XV_HdmiTx1_Config* XV_HdmiTx1_LookupConfig(UINTPTR BaseAddress)
This function returns a reference to an XV_HdmiTx1_Config structure based on the core id, DeviceId.
The return value will refer to an entry in the device configuration table defined in the xv_hdmitx1_g.c file. DeviceId is the unique core ID of the HDMI TX core for the lookup operation. XV_HdmiTx1_LookupConfig returns a reference to a config record in the configuration table (in xv_hdmitx1_g.c) corresponding to DeviceId, or NULL if no match is found. None.
int XV_HdmiTx1_CfgInitialize(XV_HdmiTx1 *InstancePtr, XV_HdmiTx1_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the HDMI TX core.
This function must be called prior to using the HDMI TX core. Initialization of the HDMI TX includes setting up the instance data and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the XV_HdmiTx1 core instance. CfgPtr points to the configuration structure associated with the HDMI TX core. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if XV_HdmiTx1_CfgInitialize was successful.XST_FAILURE if HDMI TX PIO ID mismatched. None.
References XV_HdmiTx1_Stream::Audio, XV_HdmiTx1_Config::BaseAddress, XV_HdmiTx1::Config, XV_HdmiTx1::ConnectCallback, XV_HdmiTx1_Stream::CorePixPerClk, XV_HdmiTx1::DscDecodeFailCallback, XV_HdmiTx1::DynHdrMtwCallback, XV_HdmiTx1_Stream::Frl, XV_HdmiTx1_Stream::IsConnected, XV_HdmiTx1::IsReady, XV_HdmiTx1_Frl::Lanes, XV_HdmiTx1_Frl::MaxFrlRate, XV_HdmiTx1_Config::MaxFrlRate, XV_HdmiTx1_Stream::OverrideScrambler, XV_HdmiTx1_Frl::RateLock, XV_HdmiTx1_Stream::State, XV_HdmiTx1::Stream, XV_HdmiTx1::StreamDownCallback, XV_HdmiTx1::StreamUpCallback, XV_HdmiTx1::TmdsConfigCallback, XV_HdmiTx1::ToggleCallback, XV_HdmiTx1_Frl::TrainingState, XV_HdmiTx1::VsCallback, XV_HDMITX1_AUD_CTRL_CLR_OFFSET, XV_HDMITX1_AUD_CTRL_SET_OFFSET, XV_HdmiTx1_AudioDisable, XV_HdmiTx1_AuxDisable, XV_HdmiTx1_Clear, XV_HDMITX1_CONNECT_CONF_OFFSET, XV_HdmiTx1_DdcDisable, XV_HdmiTx1_DdcIntrClear, XV_HDMITX1_FRLSTATE_LTS_L, XV_HdmiTx1_GetTime1Ms, XV_HDMITX1_HPD_TIMEGRID_OFFSET, XV_HDMITX1_MASK_16, XV_HDMITX1_PIO_ID, XV_HDMITX1_PIO_ID_OFFSET, XV_HDMITX1_PIO_IN_BRDG_LOCKED_MASK, XV_HDMITX1_PIO_IN_BRDG_OVERFLOW_MASK, XV_HDMITX1_PIO_IN_BRDG_UNDERFLOW_MASK, XV_HDMITX1_PIO_IN_EVT_FE_OFFSET, XV_HDMITX1_PIO_IN_EVT_RE_OFFSET, XV_HDMITX1_PIO_IN_HPD_MASK, XV_HDMITX1_PIO_IN_HPD_TOGGLE_MASK, XV_HDMITX1_PIO_IN_LNK_RDY_MASK, XV_HDMITX1_PIO_IN_VS_MASK, XV_HdmiTx1_PioDisable, XV_HdmiTx1_PioIntrClear, XV_HdmiTx1_ReadReg, XV_HdmiTx1_SetHdmiTmdsMode, XV_HDMITX1_SHIFT_16, XV_HDMITX1_TOGGLE_CONF_OFFSET, XV_HdmiTx1_WriteReg.
void XV_HdmiTx1_SetHdmiTmdsMode(XV_HdmiTx1 *InstancePtr)
This function sets the core into HDMI TMDS mode.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. This is required after a reset or init.
References XV_HdmiTx1::Stream, XV_HdmiTx1_AudioEnable, XV_HdmiTx1_AuxEnable, XV_HdmiTx1_SetMode.
Referenced by XV_HdmiTx1_CfgInitialize.
void XV_HdmiTx1_SetDviMode(XV_HdmiTx1 *InstancePtr)
This function sets the core into DVI mode.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. This is required after a reset or init.
References XV_HdmiTx1::Stream, XV_HdmiTx1_AudioDisable, XV_HdmiTx1_AuxDisable, XV_HdmiTx1_ClearMode.
void XV_HdmiTx1_AuxEnable(XV_HdmiTx1 *InstancePtr)
This function enables the HDMI TX Auxiliary (AUX) peripheral.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. None.
References XV_HDMITX1_AUX_CTRL_RUN_MASK, XV_HDMITX1_AUX_CTRL_SET_OFFSET, XV_HdmiTx1_WriteReg.
Referenced by XV_HdmiTx1_SetHdmiTmdsMode.
void XV_HdmiTx1_AudioEnable(XV_HdmiTx1 *InstancePtr)
This macro enables audio in HDMI TX core.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. None.
References XV_HdmiTx1::Stream, XV_HDMITX1_AUD_CTRL_RUN_MASK, XV_HDMITX1_AUD_CTRL_SET_OFFSET, XV_HdmiTx1_TMDSACRStart, XV_HdmiTx1_WriteReg.
Referenced by XV_HdmiTx1_SetAudioChannels, XV_HdmiTx1_SetAudioFormat, XV_HdmiTx1_SetHdmiTmdsMode.
void XV_HdmiTx1_Clear(XV_HdmiTx1 *InstancePtr)
This function clear the HDMI TX variables and sets it to the defaults.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. This is required after a reset or init.
Referenced by XV_HdmiTx1_CfgInitialize.
u8 XV_HdmiTx1_LookupVic(XVidC_VideoMode VideoMode)
This function provides video identification code of video mode.
VideoMode specifies resolution identifier. Video identification code defined in the VIC table. None.
XVidC_VideoMode XV_HdmiTx1_GetVideoModeFromVic(u8 Vic)
Get video mode from VIC (Video Identification Code).
Vic is the Video Identification Code. XVidC_VideoMode corresponding to the VIC.
u32 XV_HdmiTx1_SetStream(XV_HdmiTx1 *InstancePtr, XVidC_VideoTiming VideoTiming, XVidC_FrameRate FrameRate, XVidC_ColorFormat ColorFormat, XVidC_ColorDepth Bpc, XVidC_PixelsPerClock Ppc, XVidC_3DInfo *Info3D, u8 FVaFactor, u8 VrrEnabled, u8 CnmvrrEnabled, u64 *TmdsClk)
This function sets the HDMI TX stream parameters.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. VideoTiming specifies video timing. FrameRate specifies frame rate. ColorFormat specifies the type of color format. 0 = XVIDC_CSF_RGB1 = XVIDC_CSF_YCRCB_4442 = XVIDC_CSF_YCRCB_4223 = XVIDC_CSF_YCRCB_420 Bpc specifies the color depth/bits per color component. 6 = XVIDC_BPC_68 = XVIDC_BPC_810 = XVIDC_BPC_1012 = XVIDC_BPC_1216 = XVIDC_BPC_16 Ppc specifies the pixel per clock. 4 = XVIDC_PPC_4 Info3D 3D info FVaFactor - Fast Video Active Factor VrrEnabled - VRR is enabled or not CnmvrrEnabled - Negative VRR supported flag TmdsClock - reference clock calculated based on the input parameters. XST_SUCCESS on success else XST_FAILURE None.
References XV_HdmiTx1_Stream::IsScrambled, XV_HdmiTx1_Stream::ScdcSupport, XV_HdmiTx1::Stream, XV_HdmiTx1_Stream::TMDSClock, XV_HdmiTx1_Stream::TMDSClockRatio, XV_HdmiTx1_Stream::Video, XV_HdmiTx1_ClockRatio, XV_HdmiTx1_GetTmdsClk, XV_HdmiTx1_Scrambler, XV_HdmiTx1_SetColorDepth, XV_HdmiTx1_SetColorFormat, XV_HdmiTx1_SetPixelRate.
u64 XV_HdmiTx1_GetTmdsClk(XV_HdmiTx1 *InstancePtr)
This function sets and return the TMDS Clock based on Video Parameter from the InstancePtr.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. TMDS Clock None.
References XV_HdmiTx1_Stream::PixelClk, XV_HdmiTx1::Stream, XV_HdmiTx1_Stream::Video.
Referenced by XV_HdmiTx1_SetStream.
void XV_HdmiTx1_INT_VRST(XV_HdmiTx1 *InstancePtr, u8 Reset)
This function asserts or releases the HDMI TX Internal VRST.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Reset specifies TRUE/FALSE value to either assert or release HDMI TX Internal VRST. None. The reset output of the PIO is inverted. When the system is in reset, the PIO output is cleared and this will reset the HDMI TX. Therefore, clearing the PIO reset output will assert the HDMI Internal video reset. C-style signature: void XV_HdmiTx1_INT_VRST(XV_HdmiTx1 *InstancePtr, u8 Reset)
References XV_HDMITX1_PIO_OUT_CLR_OFFSET, XV_HDMITX1_PIO_OUT_INT_VRST_MASK, XV_HDMITX1_PIO_OUT_SET_OFFSET, XV_HdmiTx1_WriteReg.
void XV_HdmiTx1_INT_LRST(XV_HdmiTx1 *InstancePtr, u8 Reset)
This function asserts or releases the HDMI TX Internal LRST.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Reset specifies TRUE/FALSE value to either assert or release HDMI TX Internal LRST. None. The reset output of the PIO is inverted. When the system is in reset, the PIO output is cleared and this will reset the HDMI TX. Therefore, clearing the PIO reset output will assert the HDMI Internal link reset. C-style signature: void XV_HdmiTx1_INT_VRST(XV_HdmiTx1 *InstancePtr, u8 Reset)
References XV_HDMITX1_PIO_OUT_CLR_OFFSET, XV_HDMITX1_PIO_OUT_INT_LRST_MASK, XV_HDMITX1_PIO_OUT_SET_OFFSET, XV_HdmiTx1_WriteReg.
void XV_HdmiTx1_EXT_VRST(XV_HdmiTx1 *InstancePtr, u8 Reset)
This function asserts or releases the HDMI TX External VRST.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Reset specifies TRUE/FALSE value to either assert or release HDMI TX External VRST. None. The reset output of the PIO is inverted. When the system is in reset, the PIO output is cleared and this will reset the HDMI TX. Therefore, clearing the PIO reset output will assert the HDMI external video reset. C-style signature: void XV_HdmiTx1_EXT_VRST(XV_HdmiTx1 *InstancePtr, u8 Reset)
References XV_HDMITX1_PIO_OUT_CLR_OFFSET, XV_HDMITX1_PIO_OUT_EXT_VRST_MASK, XV_HDMITX1_PIO_OUT_SET_OFFSET, XV_HdmiTx1_WriteReg.
void XV_HdmiTx1_EXT_SYSRST(XV_HdmiTx1 *InstancePtr, u8 Reset)
This function asserts or releases the HDMI TX External SYSRST.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Reset specifies TRUE/FALSE value to either assert or release HDMI TX External SYSRST. None. The reset output of the PIO is inverted. When the system is in reset, the PIO output is cleared and this will reset the HDMI TX. Therefore, clearing the PIO reset output will assert the HDMI External system reset. C-style signature: void XV_HdmiTx1_EXT_SYSRST(XV_HdmiTx1 *InstancePtr, u8 Reset)
References XV_HDMITX1_PIO_OUT_CLR_OFFSET, XV_HDMITX1_PIO_OUT_EXT_SYSRST_MASK, XV_HDMITX1_PIO_OUT_SET_OFFSET, XV_HdmiTx1_WriteReg.
void XV_HdmiTx1_SetGcpAvmuteBit(XV_HdmiTx1 *InstancePtr)
This function sets the HDMI TX AUX GCP register AVMUTE bit.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. None.
References XV_HDMITX1_PIO_OUT_GCP_AVMUTE_MASK, XV_HDMITX1_PIO_OUT_SET_OFFSET, XV_HdmiTx1_WriteReg.
void XV_HdmiTx1_ClearGcpAvmuteBit(XV_HdmiTx1 *InstancePtr)
This function clears the HDMI TX AUX GCP register AVMUTE bit.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. None.
References XV_HDMITX1_PIO_OUT_CLR_OFFSET, XV_HDMITX1_PIO_OUT_GCP_AVMUTE_MASK, XV_HdmiTx1_WriteReg.
void XV_HdmiTx1_SetGcpClearAvmuteBit(XV_HdmiTx1 *InstancePtr)
This function sets the HDMI TX AUX GCP register CLEAR_AVMUTE bit.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. None.
References XV_HDMITX1_PIO_OUT_GCP_CLEARAVMUTE_MASK, XV_HDMITX1_PIO_OUT_SET_OFFSET, XV_HdmiTx1_WriteReg.
void XV_HdmiTx1_ClearGcpClearAvmuteBit(XV_HdmiTx1 *InstancePtr)
This function clears the HDMI TX AUX GCP register CLEAR_AVMUTE bit.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. None.
References XV_HDMITX1_PIO_OUT_CLR_OFFSET, XV_HDMITX1_PIO_OUT_GCP_CLEARAVMUTE_MASK, XV_HdmiTx1_WriteReg.
void XV_HdmiTx1_SetPixelRate(XV_HdmiTx1 *InstancePtr)
This function sets the pixel rate at output.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. None.
References XV_HdmiTx1_Config::BaseAddress, XV_HdmiTx1::Config, XV_HdmiTx1_Stream::CorePixPerClk, XV_HdmiTx1::Stream, XV_HDMITX1_PIO_OUT_MSK_OFFSET, XV_HDMITX1_PIO_OUT_OFFSET, XV_HDMITX1_PIO_OUT_PIXEL_RATE_MASK, XV_HDMITX1_PIO_OUT_PIXEL_RATE_SHIFT, XV_HdmiTx1_WriteReg.
Referenced by XV_HdmiTx1_SetStream.
void XV_HdmiTx1_SetSampleRate(XV_HdmiTx1 *InstancePtr, u8 SampleRate)
This function sets the sample rate at output.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. SampleRate specifies the value that needs to be set. 2 samples per clock3 samples per clock.5 samples per clock. None. None.
References XV_HdmiTx1_Config::BaseAddress, XV_HdmiTx1::Config, XV_HdmiTx1_Stream::SampleRate, XV_HdmiTx1::Stream, XV_HDMITX1_PIO_OUT_MSK_OFFSET, XV_HDMITX1_PIO_OUT_OFFSET, XV_HDMITX1_PIO_OUT_SAMPLE_RATE_MASK, XV_HDMITX1_PIO_OUT_SAMPLE_RATE_SHIFT, XV_HdmiTx1_WriteReg.
void XV_HdmiTx1_SetColorFormat(XV_HdmiTx1 *InstancePtr)
This function sets the color format.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. None.
References XV_HdmiTx1_Config::BaseAddress, XV_HdmiTx1::Config, XV_HdmiTx1::Stream, XV_HdmiTx1_Stream::Video, XV_HDMITX1_PIO_OUT_COLOR_SPACE_MASK, XV_HDMITX1_PIO_OUT_COLOR_SPACE_SHIFT, XV_HDMITX1_PIO_OUT_MSK_OFFSET, XV_HDMITX1_PIO_OUT_OFFSET, XV_HdmiTx1_WriteReg.
Referenced by XV_HdmiTx1_SetStream.
void XV_HdmiTx1_SetColorDepth(XV_HdmiTx1 *InstancePtr)
This function sets the color depth.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. None.
References XV_HdmiTx1_Config::BaseAddress, XV_HdmiTx1::Config, XV_HdmiTx1::Stream, XV_HdmiTx1_Stream::Video, XV_HDMITX1_PIO_OUT_COLOR_DEPTH_MASK, XV_HDMITX1_PIO_OUT_COLOR_DEPTH_SHIFT, XV_HDMITX1_PIO_OUT_MSK_OFFSET, XV_HDMITX1_PIO_OUT_OFFSET, XV_HdmiTx1_WriteReg.
Referenced by XV_HdmiTx1_SetStream.
int XV_HdmiTx1_IsStreamScrambled(XV_HdmiTx1 *InstancePtr)
This function provides status of the stream.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. TRUE = Scrambled.FALSE = Not scrambled. None.
References XV_HdmiTx1_Stream::IsScrambled, XV_HdmiTx1::Stream.
int XV_HdmiTx1_IsStreamConnected(XV_HdmiTx1 *InstancePtr)
This function provides the stream connected status.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. TRUE = Stream is connected.FALSE = Stream is connected. None.
References XV_HdmiTx1_Stream::IsConnected, XV_HdmiTx1::Stream.
void XV_HdmiTx1_SetAxiClkFreq(XV_HdmiTx1 *InstancePtr, u32 ClkFreq)
This function sets the AXI4-Lite Clock Frequency.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. ClkFreq specifies the value that needs to be set. This is required after a reset or init.
References XV_HdmiTx1::Config, XV_HdmiTx1::CpuClkFreq, XV_HdmiTx1_DdcInit.
void XV_HdmiTx1_DdcInit(XV_HdmiTx1 *InstancePtr, u32 Frequency)
This function prepares TX DDC peripheral to use.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Frequency specifies the value that needs to be set. None. None.
References XV_HdmiTx1_Config::BaseAddress, XV_HdmiTx1::Config, XV_HDMITX1_DDC_CTRL_CLK_DIV_MASK, XV_HDMITX1_DDC_CTRL_OFFSET, XV_HdmiTx1_WriteReg.
Referenced by XV_HdmiTx1_SetAxiClkFreq.
int XV_HdmiTx1_DdcWrite(XV_HdmiTx1 *InstancePtr, u8 Slave, u16 Length, u8 *Buffer, u8 Stop)
This function writes data from DDC peripheral from given slave address.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Slave specifies the slave address from where data needs to be read. Length specifies number of bytes to be read. Buffer specifies a pointer to u8 variable that will be filled with data. Stop specifies the stop flag which is either TRUE/FALSE. XST_SUCCESS if an acknowledgement received and timeout.XST_FAILURE if no acknowledgement received. None.
References XV_HDMITX1_DDC_CMD_STP_TOKEN, XV_HDMITX1_DDC_CMD_STR_TOKEN, XV_HDMITX1_DDC_CMD_WR_TOKEN, XV_HdmiTx1_DdcDisable, XV_HdmiTx1_DdcEnable, XV_HdmiTx1_DdcGetAck, XV_HdmiTx1_DdcIntrDisable, XV_HdmiTx1_DdcWaitForDone, XV_HdmiTx1_DdcWriteCommand, XV_HdmiTx1_PioIntrDisable, XV_HdmiTx1_PioIntrEnable.
Referenced by XV_HdmiTx1_ClockRatio, XV_HdmiTx1_DdcReadReg, XV_HdmiTx1_DdcWriteField, XV_HdmiTx1_DetectHdmi20, XV_HdmiTx1_Scrambler, XV_HdmiTx1_ShowSCDC.
int XV_HdmiTx1_DdcRead(XV_HdmiTx1 *InstancePtr, u8 Slave, u16 Length, u8 *Buffer, u8 Stop)
This function reads data from DDC peripheral from given slave address.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Slave specifies the slave address from where data needs to be read. Length specifies number of bytes to be read. Buffer specifies a pointer to u8 variable that will be filled with data. Stop specifies the stop flag which is either TRUE/FALSE. XST_SUCCESS if an acknowledgement received and timeout.XST_FAILURE if no acknowledgement received. None.
References XV_HDMITX1_DDC_CMD_RD_TOKEN, XV_HDMITX1_DDC_CMD_STP_TOKEN, XV_HDMITX1_DDC_CMD_STR_TOKEN, XV_HDMITX1_DDC_CMD_WR_TOKEN, XV_HdmiTx1_DdcDisable, XV_HdmiTx1_DdcEnable, XV_HdmiTx1_DdcGetAck, XV_HdmiTx1_DdcIntrDisable, XV_HdmiTx1_DdcReadData, XV_HdmiTx1_DdcWaitForDone, XV_HdmiTx1_DdcWriteCommand, XV_HdmiTx1_PioIntrDisable, XV_HdmiTx1_PioIntrEnable.
Referenced by XV_HdmiTx1_ClockRatio, XV_HdmiTx1_DdcReadReg, XV_HdmiTx1_DdcWriteField, XV_HdmiTx1_Scrambler, XV_HdmiTx1_ShowSCDC.
int XV_HdmiTx1_DdcReadReg(XV_HdmiTx1 *InstancePtr, u8 Slave, u16 Length, u8 RegAddr, u8 *Buffer)
This function reads specified register from DDC peripheral from given slave address.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Slave specifies the slave address from where data needs to be read. Length specifies number of bytes to be read. RegAddr specifies the register address from where data needs to be read. Buffer specifies a pointer to u8 variable that will be filled with data. XST_SUCCESS if an acknowledgement received and timeout.XST_FAILURE if no acknowledgement received. None.
References XV_HdmiTx1_DdcRead, XV_HdmiTx1_DdcWrite.
Referenced by XV_HdmiTx1_GetScdcEdRegisters.
int XV_HdmiTx1_DdcWriteField(XV_HdmiTx1 *InstancePtr, XV_HdmiTx1_ScdcFieldType Field, u8 Value)
This function writes the specified SCDC Field.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Field specifies the fields from SCDC channels to be written Value specifies the values to be written XST_SUCCESSXST_FAILURE None.
References XV_HdmiTx1_ScdcField::Mask, XV_HdmiTx1_ScdcField::Offset, XV_HdmiTx1_ScdcField::Shift, XV_HdmiTx1_DdcRead, XV_HdmiTx1_DdcWrite.
void XV_HdmiTx1_Aux_Dsc_Send_Header(XV_HdmiTx1 *InstancePtr, u32 Data)
This function transmits the DSC packet header.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Data value to be written None. None.
References XV_HdmiTx1_Config::BaseAddress, XV_HdmiTx1::Config, XV_HdmiTx1_WriteReg.
void XV_HdmiTx1_Aux_Dsc_Send_Data(XV_HdmiTx1 *InstancePtr, u32 Data)
This function transmits the DSC packet data.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Data value to be written None. None.
References XV_HdmiTx1_Config::BaseAddress, XV_HdmiTx1::Config, XV_HdmiTx1_WriteReg.
u32 XV_HdmiTx1_AuxSend(XV_HdmiTx1 *InstancePtr)
This function transmits the infoframes generated by the processor.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. XST_SUCCESS if infoframes transmitted successfully.XST_FAILURE if AUX FIFO is full. None.
References XV_HdmiTx1::Aux, XV_HdmiTx1_Config::BaseAddress, XV_HdmiTx1::Config, XV_HDMITX1_AUX_DAT_OFFSET, XV_HDMITX1_AUX_STA_FIFO_FUL_MASK, XV_HDMITX1_AUX_STA_OFFSET, XV_HDMITX1_AUX_STA_PKT_RDY_MASK, XV_HdmiTx1_ReadReg, XV_HdmiTx1_WriteReg.
int XV_HdmiTx1_Scrambler(XV_HdmiTx1 *InstancePtr)
This function controls the scrambler.
Requires TMDSClock to be up to date in order to force enable scrambler when TMDSClock > 340MHz. InstancePtr is a pointer to the XV_HdmiTx1 core instance. XST_SUCCESS if HDMI 2.0XST_FAILURE if HDMI 1.4 None.
References XV_HdmiTx1_Stream::IsScrambled, XV_HdmiTx1_Stream::OverrideScrambler, XV_HdmiTx1_Stream::ScdcSupport, XV_HdmiTx1::Stream, XV_HdmiTx1_Stream::TMDSClock, XV_HdmiTx1_DdcRead, XV_HdmiTx1_DdcWrite, XV_HdmiTx1_SetScrambler.
Referenced by XV_HdmiTx1_SetStream.
int XV_HdmiTx1_ClockRatio(XV_HdmiTx1 *InstancePtr)
This function controls the TMDS clock ratio.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. XST_SUCCESS if HDMI 2.0XST_FAILURE if HDMI 1.4 None.
References XV_HdmiTx1_Stream::ScdcSupport, XV_HdmiTx1::Stream, XV_HdmiTx1_Stream::TMDSClockRatio, XV_HdmiTx1_DdcRead, XV_HdmiTx1_DdcWrite.
Referenced by XV_HdmiTx1_SetStream.
int XV_HdmiTx1_DetectHdmi20(XV_HdmiTx1 *InstancePtr)
This function detects connected sink is a HDMI 2.0/HDMI 1.4 sink device and sets appropriate flag in the TX stream.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. XST_SUCCESS if HDMI 2.0XST_FAILURE if HDMI 1.4 None.
References XV_HdmiTx1_Stream::ScdcSupport, XV_HdmiTx1::Stream, XV_HdmiTx1_DdcWrite.
void XV_HdmiTx1_ShowSCDC(XV_HdmiTx1 *InstancePtr)
This function shows the sinks SCDC registers.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. None.
References XV_HdmiTx1_DdcRead, XV_HdmiTx1_DdcWrite.
void XV_HdmiTx1_Info(XV_HdmiTx1 *InstancePtr)
This function prints stream and timing information on STDIO/Uart console.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. None.
References XV_HdmiTx1::Stream, XV_HdmiTx1_Stream::Video.
void XV_HdmiTx1_DebugInfo(XV_HdmiTx1 *InstancePtr)
This function prints debug information on STDIO/UART console.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. None.
References XV_HdmiTx1_Config::BaseAddress, XV_HdmiTx1::Config, XV_HDMITX1_ANLZ_HBP_HS_HPB_SZ_MASK, XV_HDMITX1_ANLZ_HBP_HS_HPB_SZ_SHIFT, XV_HDMITX1_ANLZ_HBP_HS_HS_SZ_MASK, XV_HDMITX1_ANLZ_HBP_HS_OFFSET, XV_HDMITX1_ANLZ_LN_ACT_ACT_SZ_MASK, XV_HDMITX1_ANLZ_LN_ACT_LN_SZ_MASK, XV_HDMITX1_ANLZ_LN_ACT_LN_SZ_SHIFT, XV_HDMITX1_ANLZ_LN_ACT_OFFSET, XV_HDMITX1_DBG_STS_OFFSET, XV_HDMITX1_PIO_IN_BRDG_LOCKED_MASK, XV_HDMITX1_PIO_IN_OFFSET, XV_HDMITX1_PIO_OUT_MODE_MASK, XV_HDMITX1_PIO_OUT_OFFSET, XV_HdmiTx1_ReadReg, XV_HDMITX1_VCKE_SYS_CNT_OFFSET, XV_HDMITX1_VER_ID_OFFSET, XV_HDMITX1_VER_VERSION_OFFSET.
void XV_HdmiTx1_RegisterDebug(XV_HdmiTx1 *InstancePtr)
This function prints out HDMI TX register.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. None.
References XV_HdmiTx1_Config::BaseAddress, XV_HdmiTx1::Config, XV_HDMITX1_MASK_BLUE_OFFSET, XV_HdmiTx1_ReadReg.
int XV_HdmiTx1_SetAudioChannels(XV_HdmiTx1 *InstancePtr, u8 Value)
This function sets the active audio channels.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Value is number of active audio channels XST_SUCCESS if active channels were set.XST_FAILURE if no active channels were set. None.
References XV_HDMITX1_3DAUD_CTRL_CH_MASK, XV_HDMITX1_3DAUD_CTRL_CH_SHIFT, XV_HDMITX1_AUD_CTRL_CH_MASK, XV_HDMITX1_AUD_CTRL_CH_SHIFT, XV_HDMITX1_AUD_CTRL_CLR_OFFSET, XV_HDMITX1_AUD_CTRL_OFFSET, XV_HDMITX1_AUD_CTRL_RUN_MASK, XV_HDMITX1_AUD_CTRL_SET_OFFSET, XV_HdmiTx1_AudioEnable, XV_HdmiTx1_ReadReg, XV_HdmiTx1_WriteReg.
int XV_HdmiTx1_SetAudioFormat(XV_HdmiTx1 *InstancePtr, XV_HdmiTx1_AudioFormatType Value)
This function sets the active audio format.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Value specifies the audio format XST_SUCCESS if active channels were set.XST_FAILURE if no active channels were set. None.
References XV_HDMITX1_AUD_CTRL_3DAUDFMT_EN, XV_HDMITX1_AUD_CTRL_3DAUDFMT_MASK, XV_HDMITX1_AUD_CTRL_AUDFMT_MASK, XV_HDMITX1_AUD_CTRL_CLR_OFFSET, XV_HDMITX1_AUD_CTRL_OFFSET, XV_HDMITX1_AUD_CTRL_RUN_MASK, XV_HDMITX1_AUD_CTRL_SET_OFFSET, XV_HdmiTx1_AudioEnable, XV_HdmiTx1_ReadReg, XV_HdmiTx1_WriteReg.
XV_HdmiTx1_AudioFormatType XV_HdmiTx1_GetAudioFormat(XV_HdmiTx1 *InstancePtr)
This function gets the active audio format.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. Active audio format of HDMI Tx None.
References XV_HDMITX1_AUD_CTRL_3DAUDFMT_MASK, XV_HDMITX1_AUD_CTRL_AUDFMT_MASK, XV_HDMITX1_AUD_CTRL_AUDFMT_SHIFT, XV_HDMITX1_AUD_CTRL_OFFSET, XV_HdmiTx1_ReadReg.
u32 XV_HdmiTxSs1_GetAudioCtsVal(XV_HdmiTx1 *InstancePtr)
This function gets the Generated ACR CTS Value.
InstancePtr is a pointer to the XV_HdmiTxSs1 core instance. Generated ACR CTS Value None.
References XV_HDMITX1_AUD_ACR_CTS_OFFSET, XV_HdmiTx1_ReadReg.
u32 XV_HdmiTxSs1_GetAudioNVal(XV_HdmiTx1 *InstancePtr)
This function gets the programmed ACR N Value.
InstancePtr is a pointer to the XV_HdmiTxSs1 core instance. Programmed ACR N Value None.
References XV_HDMITX1_AUD_ACR_N_OFFSET, XV_HdmiTx1_ReadReg.
void XV_HdmiTx1_TMDSACRStart(XV_HdmiTx1 *InstancePtr)
This function Starts the internal ACR module for TMDS.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None.
References XV_HdmiTx1_Stream::Audio, XV_HdmiTx1::Stream, XV_HdmiTx1_Stream::TMDSClock, XV_HDMITX1_AUD_ACR_N_OFFSET, XV_HDMITX1_AUD_CTRL_CLR_OFFSET, XV_HDMITX1_AUD_CTRL_SET_OFFSET, XV_HdmiTx1_WriteReg.
Referenced by XV_HdmiTx1_AudioEnable.
int XV_HdmiTx1_StartTmdsMode(XV_HdmiTx1 *InstancePtr)
Start TMDS mode.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. XST_SUCCESS on success, error code otherwise.
u8* XV_HdmiTx1_GetScdcEdRegisters(XV_HdmiTx1 *InstancePtr)
This function reads the CED and RSED registers from the sink and returns the pointer to the data structure which stores the CED related readings (from SCDC register 0x50 to 0x5A).
InstancePtr is a pointer to the XHdmi_Tx core instance. Returns a pointer to the local buffer containing the SCDC character error detection readings Reading the SCDC registers will clear the values at the sink
References XV_HdmiTx1_Stream::ScdcEd, XV_HdmiTx1::Stream, XV_HdmiTx1_DdcReadReg.
void XV_HdmiTx1_Start(XV_HdmiTx1 *InstancePtr)
This function starts the HDMI TX core.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None. This is required after a reset or initialization.
References XV_HdmiTx1_PioEnable, XV_HdmiTx1_PioIntrEnable.
void XV_HdmiTx1_Stop(XV_HdmiTx1 *InstancePtr)
This function stops the HDMI TX core.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. None.
References XV_HdmiTx1_PioDisable, XV_HdmiTx1_PioIntrDisable.
int XV_HdmiTx1_SelfTest(XV_HdmiTx1 *InstancePtr)
This function reads ID of HDMI TX PIO peripheral.
InstancePtr is a pointer to the XV_HdmiTx1 core instance. XST_SUCCESS if PIO ID was matched.XST_FAILURE if PIO ID was mismatched. None.
References XV_HdmiTx1_Config::BaseAddress, XV_HdmiTx1::Config, XV_HDMITX1_MASK_16, XV_HDMITX1_PIO_ID, XV_HDMITX1_PIO_ID_OFFSET, XV_HdmiTx1_ReadReg, XV_HDMITX1_SHIFT_16.
void XV_HdmiTx1_IntrHandler(void *InstancePtr)
This function is the interrupt handler for the HDMI TX driver.
This handler reads the pending interrupt from PIO and DDC peripheral, determines the source of the interrupts, clears the interrupts and calls callbacks accordingly.The application is responsible for connecting this function to the interrupt system. Application beyond this driver is also responsible for providing callbacks to handle interrupts and installing the callbacks using XV_HdmiTx1_SetCallback() during initialization phase. An example delivered with this driver demonstrates how this could be done. InstancePtr is a pointer to the XV_HdmiTx1 instance that just interrupted. None. None.
References XV_HdmiTx1_Config::BaseAddress, XV_HdmiTx1::Config, XV_HdmiTx1::IsReady, XV_HDMITX1_AUX_STA_IRQ_MASK, XV_HDMITX1_AUX_STA_OFFSET, XV_HDMITX1_DDC_STA_IRQ_MASK, XV_HDMITX1_DDC_STA_OFFSET, XV_HDMITX1_PIO_STA_IRQ_MASK, XV_HDMITX1_PIO_STA_OFFSET, XV_HdmiTx1_ReadReg.
int XV_HdmiTx1_SetCallback(XV_HdmiTx1 *InstancePtr, XV_HdmiTx1_HandlerType HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function Type ----------------------- -------------------------------------------------- (XV_HDMITX1_HANDLER_HPD) HpdCallback (XV_HDMITX1_HANDLER_VS) VsCallback InstancePtr is a pointer to the HDMI TX core instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XV_HdmiTx1::BrdgLockedCallback, XV_HdmiTx1::BrdgLockedRef, XV_HdmiTx1::BrdgOverflowCallback, XV_HdmiTx1::BrdgOverflowRef, XV_HdmiTx1::BrdgUnderflowCallback, XV_HdmiTx1::BrdgUnderflowRef, XV_HdmiTx1::BrdgUnlockedCallback, XV_HdmiTx1::BrdgUnlockedRef, XV_HdmiTx1::CedUpdateCallback, XV_HdmiTx1::CedUpdateRef, XV_HdmiTx1::ConnectCallback, XV_HdmiTx1::ConnectRef, XV_HdmiTx1::DscDecodeFailCallback, XV_HdmiTx1::DscDecodeFailRef, XV_HdmiTx1::DynHdrMtwCallback, XV_HdmiTx1::DynHdrMtwRef, XV_HdmiTx1::StreamDownCallback, XV_HdmiTx1::StreamDownRef, XV_HdmiTx1::StreamUpCallback, XV_HdmiTx1::StreamUpRef, XV_HdmiTx1::TmdsConfigCallback, XV_HdmiTx1::TmdsConfigRef, XV_HdmiTx1::ToggleCallback, XV_HdmiTx1::ToggleRef, XV_HdmiTx1::VsCallback, XV_HdmiTx1::VsRef.
XV_HdmiC_VideoTimingExtMeta* XV_HdmiTx1_GetVidTimingExtMeta(XV_HdmiTx1 *InstancePtr)
This function returns Video Timing Extended Metadata.
InstancePtr is a pointer to the XHdmiTx1 core instance. XV_HdmiC_VideoTimingExtMeta None.
References XV_HdmiTx1::VrrIF.
Referenced by XV_HdmiTx1_GenerateCustomVideoTimingExtMetaIF, XV_HdmiTx1_GenerateVideoTimingExtMetaIF.
XV_HdmiC_SrcProdDescIF* XV_HdmiTx1_GetSrcProdDescIF(XV_HdmiTx1 *InstancePtr)
This function returns a pointer to the SrcProdDescIF which contains the Source Product Descriptor InfoFrame data used in HDMI VRR (Variable Refresh Rate) or other auxiliary metadata transmission.
InstancePtr is a pointer to the XHdmiTx1 core instance. XV_HdmiC_SrcProdDescIF None
References XV_HdmiTx1::VrrIF.
Referenced by XV_HdmiTx1_GenerateSrcProdDescInfoframe.
void XV_HdmiTx1_GenerateVideoTimingExtMetaIF(XV_HdmiTx1 *InstancePtr, XV_HdmiC_VideoTimingExtMeta *ExtMeta)
This function configures the HDMI transmitter with extended video timing metadata such as QMS (Quick Media Switching), VRR (Variable Refresh Rate), and other timing-related parameters.
It prepares the VTEM data based on the provided metadata structure and writes it to the appropriate auxiliary registers. InstancePtr is a pointer to the XHdmiTx1 core instance. ExtMeta is a pointer to the structure containing extended video timing metadata. None
References XV_HdmiTx1_Config::BaseAddress, XV_HdmiTx1::Config, XV_HDMITX1_AUX_CTRL_DATASET_LEN_EN_MASK, XV_HDMITX1_AUX_CTRL_OFFSET, XV_HDMITX1_AUX_CTRL_SYNC_EN_MASK, XV_HDMITX1_AUX_VTEM_OFFSET, XV_HdmiTx1_GetVidTimingExtMeta, XV_HdmiTx1_ReadReg, XV_HdmiTx1_WriteReg.
void XV_HdmiTx1_GenerateCustomVideoTimingExtMetaIF(XV_HdmiTx1 *InstancePtr, XV_HdmiC_VideoTimingExtMeta *ExtMeta, u16 Sync, u16 DataSetLen)
This function allows fine-grained control over the VTEM InfoFrame generation by accepting custom values for the sync enable and dataset length fields.
It is useful for debugging or advanced HDMI configurations where default behavior needs to be overridden. InstancePtr is a pointer to the XHdmiTx1 core instance. ExtMeta is a pointer to the structure containing extended video timing metadata. Sync Value to set the Sync Enable bit (0 or 1). DataSetLen Value to set the Dataset Length Enable bit (0 or 1). None
References XV_HdmiTx1_Config::BaseAddress, XV_HdmiTx1::Config, XV_HDMITX1_AUX_CTRL_DATASET_LEN_EN_MASK, XV_HDMITX1_AUX_CTRL_OFFSET, XV_HDMITX1_AUX_CTRL_SYNC_EN_MASK, XV_HDMITX1_AUX_VTEM_OFFSET, XV_HdmiTx1_GetVidTimingExtMeta, XV_HdmiTx1_ReadReg, XV_HdmiTx1_WriteReg.
void XV_HdmiTx1_GenerateSrcProdDescInfoframe(XV_HdmiTx1 *InstancePtr, XV_HdmiC_SrcProdDescIF *SpdIfPtr)
This function configures the HDMI transmitter with Source Product Descriptor metadata, including FreeSync and FreeSync Pro capabilities.
It prepares the data based on the provided structure and writes it to the appropriate auxiliary registers InstancePtr is a pointer to the XHdmiTx1 core instance. SpdIfPtr is a pointer to the structure containing SPD InfoFrame data. None
References XV_HdmiTx1_Config::BaseAddress, XV_HdmiTx1::Config, XV_HDMITX1_AUX_FSYNC_OFFSET, XV_HDMITX1_AUX_FSYNC_PRO_OF, XV_HdmiTx1_GetSrcProdDescIF, XV_HdmiTx1_WriteReg.