emacps
XEMACPS_PROMISC_OPTION
Accept all incoming packets.
This option defaults to disabled (cleared)
Referenced by XEmacPs_ClearOptions, XEmacPs_SetOptions.
XEMACPS_FRAME1536_OPTION
Frame larger than 1516 support for Tx & Rx.
This option defaults to disabled (cleared)
Referenced by XEmacPs_ClearOptions, XEmacPs_SetOptions.
XEMACPS_VLAN_OPTION
VLAN Rx & Tx frame support.
This option defaults to disabled (cleared)
Referenced by XEmacPs_ClearOptions, XEmacPs_SetOptions.
XEMACPS_FLOW_CONTROL_OPTION
Enable recognition of flow control frames on Rx This option defaults to enabled (set)
Referenced by XEmacPs_ClearOptions, XEmacPs_SetOptions.
XEMACPS_FCS_STRIP_OPTION
Strip FCS and PAD from incoming frames.
Note: PAD from VLAN frames is not stripped. This option defaults to enabled (set)
Referenced by XEmacPs_ClearOptions, XEmacPs_SetOptions.
XEMACPS_FCS_INSERT_OPTION
Generate FCS field and add PAD automatically for outgoing frames.
This option defaults to disabled (cleared)
XEMACPS_LENTYPE_ERR_OPTION
Enable Length/Type error checking for incoming frames.
When this option is set, the MAC will filter frames that have a mismatched type/length field and if XEMACPS_REPORT_RXERR_OPTION is set, the user is notified when these types of frames are encountered. When this option is cleared, the MAC will allow these types of frames to be received.This option defaults to disabled (cleared)
Referenced by XEmacPs_ClearOptions, XEmacPs_SetOptions.
XEMACPS_TRANSMITTER_ENABLE_OPTION
Enable the transmitter.
This option defaults to enabled (set)
Referenced by XEmacPs_ClearOptions, XEmacPs_Reset, XEmacPs_SetOptions, XEmacPs_Start.
XEMACPS_RECEIVER_ENABLE_OPTION
Enable the receiver This option defaults to enabled (set)
Referenced by XEmacPs_ClearOptions, XEmacPs_Reset, XEmacPs_SetOptions, XEmacPs_Start.
XEMACPS_BROADCAST_OPTION
Allow reception of the broadcast address This option defaults to enabled (set)
Referenced by XEmacPs_ClearOptions, XEmacPs_SetOptions.
XEMACPS_MULTICAST_OPTION
Allows reception of multicast addresses programmed into hash This option defaults to disabled (clear)
Referenced by XEmacPs_ClearOptions, XEmacPs_SetOptions.
XEMACPS_RX_CHKSUM_ENABLE_OPTION
Enable the RX checksum offload This option defaults to enabled (set)
Referenced by XEmacPs_ClearOptions, XEmacPs_SetOptions.
XEMACPS_TX_CHKSUM_ENABLE_OPTION
Enable the TX checksum offload This option defaults to enabled (set)
Referenced by XEmacPs_ClearOptions, XEmacPs_SetOptions.
XEMACPS_JUMBO_ENABLE_OPTION
XEMACPS_SGMII_ENABLE_OPTION
XEMACPS_GIGABIT_MODE_ENABLE_OPTION
XEMACPS_DEFAULT_OPTIONS
Default options set when device is initialized or reset.
Referenced by XEmacPs_Reset.
XEMACPS_HANDLER_DMASEND
XEMACPS_HANDLER_DMARECV
XEMACPS_HANDLER_ERROR
typedef void(* XEmacPs_Handler)(void *CallBackRef))(void *CallBackRef)
Callback invoked when frame(s) have been sent or received in interrupt driven DMA mode.
To set the send callback, invoke XEmacPs_SetHandler(). CallBackRef is user data assigned when the callback was set. See xemacps_hw.h for bitmasks definitions and the device hardware spec for further information on their meaning.
typedef void(* XEmacPs_ErrHandler)(void *CallBackRef, u8 Direction, u32 ErrorWord))(void *CallBackRef, u8 Direction, u32 ErrorWord)
Callback when an asynchronous error occurs.
To set this callback, invoke XEmacPs_SetHandler() with XEMACPS_HANDLER_ERROR in the HandlerType parameter. CallBackRef is user data assigned when the callback was set. Direction defines either receive or transmit error(s) has occurred. ErrorWord definition varies with Direction
XEMACPS_SEND
send direction
Referenced by EmacPsDmaIntrExample, EmacPsDmaSingleFrameIntrExample, XEmacPs_BdRingCheck, XEmacPs_BdRingClone, XEmacPs_IntrHandler, XEmacPs_Reset, XEmacPs_SetQueuePtr.
XEMACPS_RECV
receive direction
Referenced by EmacPsDmaIntrExample, EmacPsDmaSingleFrameIntrExample, XEmacPs_BdRingCheck, XEmacPs_BdRingClone, XEmacPs_IntrHandler, XEmacPs_Reset.
XEmacPs_MdcDiv
XEMACPS_ENABLE_HS_MAC_OFFSET
Use High Speed MAC.
XEMACPS_ENABLE_HS_MAC_SIZE
XEMACPS_NWCTRL_FLUSH_DPRAM_MASK
Flush a packet from Rx SRAM.
Referenced by XEmacPs_IntrHandler, XEmacPs_ResetHw.
XEMACPS_NWCTRL_ZEROPAUSETX_MASK
Transmit zero quantum pause frame.
XEMACPS_NWCTRL_PAUSETX_MASK
Transmit pause frame.
Referenced by XEmacPs_SendPausePacket.
XEMACPS_NWCTRL_HALTTX_MASK
Halt transmission after current frame.
Referenced by XEmacPs_ResetHw.
XEMACPS_NWCTRL_STARTTX_MASK
Start tx (tx_go)
XEMACPS_NWCTRL_STATWEN_MASK
Enable writing to stat counters.
XEMACPS_NWCTRL_STATINC_MASK
Increment statistic registers.
XEMACPS_NWCTRL_STATCLR_MASK
Clear statistic registers.
Referenced by XEmacPs_Reset, XEmacPs_ResetHw.
XEMACPS_NWCTRL_MDEN_MASK
Enable MDIO port.
Referenced by XEmacPs_Reset.
XEMACPS_NWCTRL_TXEN_MASK
Enable transmit.
Referenced by XEmacPs_ClearOptions, XEmacPs_ResetHw, XEmacPs_SetOptions, XEmacPs_Start, XEmacPs_Stop.
XEMACPS_NWCTRL_RXEN_MASK
Enable receive.
Referenced by XEmacPs_ClearOptions, XEmacPs_Reset, XEmacPs_ResetHw, XEmacPs_SetOptions, XEmacPs_Start, XEmacPs_Stop.
XEMACPS_NWCTRL_LOOPEN_MASK
local loopback
Referenced by EmacPsUtilEnterLocalLoopback, XEmacPs_Reset, XEmacPs_ResetHw.
XEMACPS_NWCFG_BADPREAMBEN_MASK
disable rejection of non-standard preamble
XEMACPS_NWCFG_IPDSTRETCH_MASK
enable transmit IPG
XEMACPS_NWCFG_SGMIIEN_MASK
SGMII Enable.
Referenced by XEmacPs_ClearOptions, XEmacPs_SetOptions.
XEMACPS_NWCFG_FCSIGNORE_MASK
disable rejection of FCS error
XEMACPS_NWCFG_HDRXEN_MASK
RX half duplex.
XEMACPS_NWCFG_RXCHKSUMEN_MASK
enable RX checksum offload
Referenced by XEmacPs_ClearOptions, XEmacPs_SetOptions.
XEMACPS_NWCFG_PAUSECOPYDI_MASK
Do not copy pause Frames to memory.
XEMACPS_NWCFG_DWIDTH_64_MASK
64 bit Data bus width
Referenced by XEmacPs_Reset.
XEMACPS_NWCFG_DWIDTH_128_MASK
128 bit Data bus width
Referenced by XEmacPs_Reset.
XEMACPS_NWCFG_MDC_SHIFT_MASK
shift bits for MDC
Referenced by XEmacPs_SetMdioDivisor.
XEMACPS_NWCFG_MDCCLKDIV_MASK
MDC Mask PCLK divisor.
Referenced by XEmacPs_Reset, XEmacPs_SetMdioDivisor.
XEMACPS_NWCFG_FCSREM_MASK
Discard FCS from received frames.
Referenced by XEmacPs_ClearOptions, XEmacPs_SetOptions.
XEMACPS_NWCFG_LENERRDSCRD_MASK
RX length error discard.
Referenced by XEmacPs_ClearOptions, XEmacPs_SetOptions.
XEMACPS_NWCFG_RXOFFS_MASK
RX buffer offset.
XEMACPS_NWCFG_PAUSEEN_MASK
Enable pause RX.
Referenced by XEmacPs_ClearOptions, XEmacPs_SetOptions.
XEMACPS_NWCFG_RETRYTESTEN_MASK
Retry test.
XEMACPS_NWCFG_XTADDMACHEN_MASK
External address match enable.
XEMACPS_NWCFG_PCSSEL_MASK
PCS Select.
Referenced by XEmacPs_ClearOptions, XEmacPs_Reset, XEmacPs_SetOptions.
XEMACPS_NWCFG_1000_MASK
1000 Mbps
Referenced by XEmacPs_ClearOptions, XEmacPs_GetOperatingSpeed, XEmacPs_Reset, XEmacPs_SetOperatingSpeed, XEmacPs_SetOptions.
XEMACPS_NWCFG_1536RXEN_MASK
Enable 1536 byte frames reception.
Referenced by XEmacPs_ClearOptions, XEmacPs_SetOptions.
XEMACPS_NWCFG_UCASTHASHEN_MASK
Receive unicast hash frames.
Referenced by XEmacPs_Reset.
XEMACPS_NWCFG_MCASTHASHEN_MASK
Receive multicast hash frames.
Referenced by XEmacPs_ClearOptions, XEmacPs_SetOptions.
XEMACPS_NWCFG_BCASTDI_MASK
Do not receive broadcast frames.
Referenced by XEmacPs_ClearOptions, XEmacPs_SetOptions.
XEMACPS_NWCFG_COPYALLEN_MASK
Copy all frames.
Referenced by XEmacPs_ClearOptions, XEmacPs_SetOptions.
XEMACPS_NWCFG_JUMBO_MASK
Jumbo frames.
Referenced by XEmacPs_ClearOptions, XEmacPs_SetOptions.
XEMACPS_NWCFG_NVLANDISC_MASK
Receive only VLAN frames.
Referenced by XEmacPs_ClearOptions, XEmacPs_SetOptions.
XEMACPS_NWCFG_FDEN_MASK
full duplex
Referenced by XEmacPs_Reset.
XEMACPS_NWCFG_100_MASK
100 Mbps
Referenced by XEmacPs_GetOperatingSpeed, XEmacPs_Reset, XEmacPs_SetOperatingSpeed.
XEMACPS_NWCFG_RESET_MASK
reset value
Referenced by XEmacPs_ResetHw.
XEMACPS_NWSR_MDIOIDLE_MASK
PHY management idle.
Referenced by XEmacPs_PhyRead, XEmacPs_PhyWrite, XEmacPs_SetupPCS.
XEMACPS_NWSR_MDIO_MASK
Status of mdio_in.
XEMACPS_LADDR_MACH_MASK
Address bits[47:32] bit[31:0] are in BOTTOM.
Referenced by XEmacPs_SetMacAddress.
XEMACPS_DMACR_ADDR_WIDTH_64
64 bit address bus
Referenced by XEmacPs_Reset.
XEMACPS_DMACR_TXEXTEND_MASK
Tx Extended desc mode.
XEMACPS_DMACR_RXEXTEND_MASK
Rx Extended desc mode.
XEMACPS_DMACR_RXBUF_MASK
Mask bit for RX buffer size.
Referenced by XEmacPs_ClearOptions, XEmacPs_Reset, XEmacPs_SetOptions.
XEMACPS_DMACR_RXBUF_SHIFT
Shift bit for RX buffer size.
Referenced by XEmacPs_ClearOptions, XEmacPs_Reset, XEmacPs_SetOptions.
XEMACPS_DMACR_TCPCKSUM_MASK
enable/disable TX checksum offload
Referenced by XEmacPs_ClearOptions, XEmacPs_SetOptions.
XEMACPS_DMACR_TXSIZE_MASK
TX buffer memory size.
Referenced by XEmacPs_Reset.
XEMACPS_DMACR_RXSIZE_MASK
RX buffer memory size.
Referenced by XEmacPs_Reset.
XEMACPS_DMACR_ENDIAN_MASK
endian configuration
XEMACPS_DMACR_BLENGTH_MASK
buffer burst length
Referenced by XEmacPs_DMABLengthUpdate.
XEMACPS_DMACR_SINGLE_AHB_BURST
single AHB bursts
Referenced by XEmacPs_DMABLengthUpdate.
XEMACPS_DMACR_INCR4_AHB_BURST
4 bytes AHB bursts
Referenced by XEmacPs_DMABLengthUpdate.
XEMACPS_DMACR_INCR8_AHB_BURST
8 bytes AHB bursts
Referenced by XEmacPs_DMABLengthUpdate.
XEMACPS_DMACR_INCR16_AHB_BURST
16 bytes AHB bursts
Referenced by XEmacPs_DMABLengthUpdate, XEmacPs_Reset.
XEMACPS_TXSR_HRESPNOK_MASK
Transmit hresp not OK.
XEMACPS_TXSR_URUN_MASK
Transmit underrun.
XEMACPS_TXSR_TXCOMPL_MASK
Transmit completed OK.
Referenced by XEmacPs_IntrHandler, XEmacPs_ResetHw.
XEMACPS_TXSR_BUFEXH_MASK
Transmit buffs exhausted mid frame.
XEMACPS_TXSR_TXGO_MASK
Status of go flag.
Referenced by XEmacPs_ResetHw.
XEMACPS_TXSR_RXOVR_MASK
Retry limit exceeded.
XEMACPS_TXSR_FRAMERX_MASK
Collision tx frame.
XEMACPS_TXSR_USEDREAD_MASK
TX buffer used bit set.
Referenced by XEmacPs_IntrHandler.
XEMACPS_TXSR_ERROR_MASK
XEMACPS_RXSR_HRESPNOK_MASK
Receive hresp not OK.
XEMACPS_RXSR_RXOVR_MASK
Receive overrun.
XEMACPS_RXSR_FRAMERX_MASK
Frame received OK.
Referenced by XEmacPs_IntrHandler, XEmacPs_ResetHw.
XEMACPS_RXSR_BUFFNA_MASK
RX buffer used bit set.
Referenced by XEmacPs_IntrHandler.
XEMACPS_RXSR_ERROR_MASK
XEMACPS_SR_ALL_MASK
Mask for full register.
Referenced by XEmacPs_Reset.
XEMACPS_HS_MAC_SPEED_OFFSET
Auto-negotiation.
XEMACPS_HS_MAC_SPEED_SIZE
Auto-negotiation.
SPEED_1G
SPEED_2_5G
SPEED_5G
SPEED_10G
XEMACPS_PCS_CON_AUTO_NEG_MASK
Auto-negotiation.
XEMACPS_LINK_STATUS_OFFSET
Link status.
XEMACPS_LINK_STATUS_SIZE
XEMACPS_USX_SPEED_OFFSET
XEMACPS_USX_SPEED_SIZE
XEMACPS_SERDES_RATE_OFFSET
XEMACPS_SERDES_RATE_SIZE
XEMACPS_RX_SCR_BYPASS_OFFSET
XEMACPS_RX_SCR_BYPASS_SIZE
XEMACPS_TX_SCR_BYPASS_OFFSET
XEMACPS_TX_SCR_BYPASS_SIZE
XEMACPS_RX_SYNC_RESET_OFFSET
XEMACPS_RX_SYNC_RESET_SIZE
XEMACPS_TX_EN_OFFSET
XEMACPS_TX_EN_SIZE
XEMACPS_SIGNAL_OK_OFFSET
XEMACPS_SIGNAL_OK_SIZE
XEMACPS_USX_BLOCK_LOCK_OFFSET
XEMACPS_BLOCK_LOCK_SIZE
SERDES_RATE_5G
SERDES_RATE_10G
SERDES_RATE_25G
XEMACPS_NO_PCS_OFFSET
NO PCS bit.
XEMACPS_NO_PCS_SIZE
NO PCS bit size.
XEMACPS_HIGH_SPEED_OFFSET
High Speed bit.
XEMACPS_HIGH_SPEED_SIZE
High Speed bit size.
XEMACPS_INTQ1SR_TXCOMPL_MASK
Transmit completed OK.
XEMACPS_INTQ1SR_TXERR_MASK
Transmit AMBA Error.
XEMACPS_INTQ1SR_RXCOMPL_MASK
Receive completed OK.
XEMACPS_INTQ1_IXR_ALL_MASK
XEMACPS_INTQ1_IXR_TX_MASK
XEMACPS_INTQ1_IXR_RX_MASK
XEMACPS_INTQISR_RXCOMPL_MASK
XEMACPS_INTQISR_TXCOMPL_MASK
XEMACPS_INTQSR_TXERR_MASK
XEMACPS_INTQ_IXR_ALL_MASK
XEMACPS_IXR_PTPPSTX_MASK
PTP Pdelay_resp TXed.
XEMACPS_IXR_PTPPDRTX_MASK
PTP Pdelay_req TXed.
XEMACPS_IXR_PTPPSRX_MASK
PTP Pdelay_resp RXed.
XEMACPS_IXR_PTPPDRRX_MASK
PTP Pdelay_req RXed.
XEMACPS_IXR_PTPSTX_MASK
PTP Sync TXed.
XEMACPS_IXR_PTPDRTX_MASK
PTP Delay_req TXed.
XEMACPS_IXR_PTPSRX_MASK
PTP Sync RXed.
XEMACPS_IXR_PTPDRRX_MASK
PTP Delay_req RXed.
XEMACPS_IXR_PAUSETX_MASK
Pause frame transmitted.
XEMACPS_IXR_PAUSEZERO_MASK
Pause time has reached zero.
XEMACPS_IXR_PAUSENZERO_MASK
Pause frame received.
XEMACPS_IXR_HRESPNOK_MASK
hresp not ok
XEMACPS_IXR_RXOVR_MASK
Receive overrun occurred.
XEMACPS_IXR_USXGMII_MASK
USXGMII Interrupt.
Referenced by XEmacPs_Start.
XEMACPS_IXR_TXCOMPL_MASK
Frame transmitted ok.
Referenced by XEmacPs_IntrHandler, XEmacPs_Start.
XEMACPS_IXR_TXEXH_MASK
Transmit err occurred or no buffers.
XEMACPS_IXR_RETRY_MASK
Retry limit exceeded.
XEMACPS_IXR_URUN_MASK
Transmit underrun.
XEMACPS_IXR_TXUSED_MASK
Tx buffer used bit read.
XEMACPS_IXR_RXUSED_MASK
Rx buffer used bit read.
Referenced by XEmacPs_IntrHandler.
XEMACPS_IXR_FRAMERX_MASK
Frame received ok.
Referenced by XEmacPs_Start.
XEMACPS_IXR_MGMNT_MASK
PHY management complete.
XEMACPS_IXR_ALL_MASK
Everything!
Referenced by XEmacPs_Reset, XEmacPs_ResetHw, XEmacPs_Start, XEmacPs_Stop.
XEMACPS_IXR_TX_ERR_MASK
XEMACPS_IXR_RX_ERR_MASK
XEMACPS_PHYMNTNC_OP_MASK
operation mask bits
Referenced by XEmacPs_PhyRead, XEmacPs_PhyWrite.
XEMACPS_PHYMNTNC_OP_R_MASK
read operation
Referenced by XEmacPs_PhyRead.
XEMACPS_PHYMNTNC_OP_W_MASK
write operation
Referenced by XEmacPs_PhyWrite.
XEMACPS_PHYMNTNC_ADDR_MASK
Address bits.
XEMACPS_PHYMNTNC_REG_MASK
register bits
XEMACPS_PHYMNTNC_DATA_MASK
data bits
XEMACPS_PHYMNTNC_PHAD_SHFT_MSK
Shift bits for PHYAD.
Referenced by XEmacPs_PhyRead, XEmacPs_PhyWrite.
XEMACPS_PHYMNTNC_PREG_SHFT_MSK
Shift bits for PHREG.
Referenced by XEmacPs_PhyRead, XEmacPs_PhyWrite.
XEMACPS_RXWM_HIGH_MASK
RXWM high mask.
XEMACPS_RXWM_LOW_MASK
RXWM low mask.
XEMACPS_RXWM_LOW_SHFT_MSK
Shift for RXWM low.
XEMACPS_CMPA_ENABLE_MASK
Enable Compare A.
Referenced by EmacPsDmaSingleFrameIntrExample.
XEMACPS_CMPA_MASK
Compare reg number.
XEmacPs_QxRegOffset
MAX_QUEUES_FEASIBLE
typedef struct XEmacPs_Instance XEmacPs
The XEmacPs driver instance data.
The user is required to allocate a structure of this type for every XEmacPs device in the system. A pointer to a structure of this type is then passed to the driver API functions.
typedef u32 XEmacPs_Bd[XEMACPS_BD_NUM_WORDS][XEMACPS_BD_NUM_WORDS]
The XEmacPs_Bd is the type for buffer descriptors (BDs).
XEmacPs_Config XEmacPs_ConfigTable[XPAR_XEMACPS_NUM_INSTANCES][XPAR_XEMACPS_NUM_INSTANCES]
XEmacPs_Config XEmacPs_ConfigTable[][]
void XEmacPs_StubHandler(void)
This is a stub for the asynchronous callbacks.
The stub is here in case the upper layer forgot to set the handler(s). On initialization, all handlers are set to this callback. It is considered an error for this handler to be invoked.
Referenced by XEmacPs_CfgInitialize.
LONG XEmacPs_CfgInitialize(XEmacPs *InstancePtr, XEmacPs_Config *CfgPtr, UINTPTR EffectiveAddress)
Initialize a specific XEmacPs instance/driver.
The initialization entails: Initialize fields of the XEmacPs instance structureReset hardware and apply default optionsConfigure the DMA channels The PHY is setup independently from the device. Use the MII or whatever other interface may be present for setup. InstancePtr is a pointer to the instance to be worked on. CfgPtr is the device configuration structure containing required hardware build data. EffectiveAddress is the base address of the device. If address translation is not utilized, this parameter can be passed in using CfgPtr->Config.BaseAddress to specify the physical base address. XST_SUCCESS if initialization was successful
References XEmacPs_Config::BaseAddress, XEmacPs_Config::GmiitoRgmiiConvPhyAddr, XEmacPs_Config::IntrId, XEmacPs_Config::IntrParent, XEmacPs_Config::IsCacheCoherent, XEmacPs_Config::MdioProducerBaseAddr, XEmacPs_Config::PhyAddr, XEmacPs_Config::PhyType, XEmacPs_Config::RefClk, XEmacPs_Config::S100MDiv0, XEmacPs_Config::S100MDiv1, XEmacPs_Config::S10MDiv0, XEmacPs_Config::S10MDiv1, XEmacPs_Config::S1GDiv0, XEmacPs_Config::S1GDiv1, XEmacPs_Reset, XEmacPs_StubHandler.
Referenced by EmacPsDmaIntrExample.
void XEmacPs_Start(XEmacPs *InstancePtr)
Start the Ethernet controller as follows:
Enable transmitter if XTE_TRANSMIT_ENABLE_OPTION is setEnable receiver if XTE_RECEIVER_ENABLE_OPTION is setStart the SG DMA send and receive channels and enable the device interrupt InstancePtr is a pointer to the instance to be worked on. N/A Hardware is configured with scatter-gather DMA, the driver expects to start the scatter-gather channels and expects that the user has previously set up the buffer descriptor lists. This function makes use of internal resources that are shared between the Start, Stop, and Set/ClearOptions functions. So if one task might be setting device options while another is trying to start the device, the user is required to provide protection of this shared data (typically using a semaphore).This function must not be preempted by an interrupt that may service the device.
References XEmacPs_Config::BaseAddress, XEmacPs_BdRing::BaseBdAddr, XEmacPs_Config::RefClk, XEmacPs_IntEnable, XEmacPs_IntQiEnable, XEMACPS_ISR_OFFSET, XEMACPS_IXR_ALL_MASK, XEMACPS_IXR_FRAMERX_MASK, XEMACPS_IXR_TXCOMPL_MASK, XEMACPS_IXR_USXGMII_MASK, XEMACPS_NWCTRL_OFFSET, XEMACPS_NWCTRL_RXEN_MASK, XEMACPS_NWCTRL_TXEN_MASK, XEmacPs_ReadReg, XEMACPS_RECEIVER_ENABLE_OPTION, XEMACPS_RXQBASE_OFFSET, XEMACPS_TRANSMITTER_ENABLE_OPTION, XEMACPS_TXQBASE_OFFSET, XEmacPs_WriteReg.
Referenced by EmacPsDmaSingleFrameIntrExample.
void XEmacPs_Stop(XEmacPs *InstancePtr)
Gracefully stop the Ethernet MAC as follows:
Disable all interrupts from this deviceStop DMA channelsDisable the transmitter and receiver Device options currently in effect are not changed.This function will disable all interrupts. Default interrupts settings that had been enabled will be restored when XEmacPs_Start() is called. InstancePtr is a pointer to the instance to be worked on. This function makes use of internal resources that are shared between the Start, Stop, SetOptions, and ClearOptions functions. So if one task might be setting device options while another is trying to start the device, the user is required to provide protection of this shared data (typically using a semaphore). Stopping the DMA channels causes this function to block until the DMA operation is complete.
References XEmacPs_Config::BaseAddress, XEmacPs_Config::RefClk, XEMACPS_IDR_OFFSET, XEMACPS_IXR_ALL_MASK, XEMACPS_NWCTRL_OFFSET, XEMACPS_NWCTRL_RXEN_MASK, XEMACPS_NWCTRL_TXEN_MASK, XEmacPs_ReadReg, XEmacPs_WriteReg.
Referenced by EmacPsDmaIntrExample, EmacPsDmaSingleFrameIntrExample, XEmacPs_Reset.
void XEmacPs_Reset(XEmacPs *InstancePtr)
Perform a graceful reset of the Ethernet MAC.
Resets the DMA channels, the transmitter, and the receiver.Steps to reset Stops transmit and receive channelsStops DMAConfigure transmit and receive buffer size to defaultClear transmit and receive status register and countersClear all interrupt sourcesClear phy (if there is any previously detected) addressClear MAC addresses (1-4) as well as Type IDs and hash value All options are placed in their default state. Any frames in the descriptor lists will remain in the lists. The side effect of doing this is that after a reset and following a restart of the device, frames were in the list before the reset may be transmitted or received.The upper layer software is responsible for re-configuring (if necessary) and restarting the MAC after the reset. Note also that driver statistics are not cleared on reset. It is up to the upper layer software to clear the statistics if needed.When a reset is required, the driver notifies the upper layer software of this need through the ErrorHandler callback and specific status codes. The upper layer software is responsible for calling this Reset function and then re-configuring the device. InstancePtr is a pointer to the instance to be worked on.
References XEmacPs_Config::BaseAddress, XEmacPs_Config::MdioProducerBaseAddr, XEmacPs_ClearHash, XEmacPs_ClearOptions, XEMACPS_DEFAULT_OPTIONS, XEMACPS_DMACR_ADDR_WIDTH_64, XEMACPS_DMACR_INCR16_AHB_BURST, XEMACPS_DMACR_OFFSET, XEMACPS_DMACR_RXBUF_MASK, XEMACPS_DMACR_RXBUF_SHIFT, XEMACPS_DMACR_RXSIZE_MASK, XEMACPS_DMACR_TXSIZE_MASK, XEmacPs_GetQxOffset, XEMACPS_IDR_OFFSET, XEmacPs_IsCommonMdioPresent, XEmacPs_IsHighSpeedPCS, XEMACPS_ISR_OFFSET, XEMACPS_IXR_ALL_MASK, XEMACPS_LAST_OFFSET, XEMACPS_NWCFG_1000_MASK, XEMACPS_NWCFG_100_MASK, XEMACPS_NWCFG_DWIDTH_128_MASK, XEMACPS_NWCFG_DWIDTH_64_MASK, XEMACPS_NWCFG_FDEN_MASK, XEMACPS_NWCFG_MDCCLKDIV_MASK, XEMACPS_NWCFG_OFFSET, XEMACPS_NWCFG_PCSSEL_MASK, XEMACPS_NWCFG_UCASTHASHEN_MASK, XEMACPS_NWCTRL_LOOPEN_MASK, XEMACPS_NWCTRL_MDEN_MASK, XEMACPS_NWCTRL_OFFSET, XEMACPS_NWCTRL_RXEN_MASK, XEMACPS_NWCTRL_STATCLR_MASK, XEMACPS_OCTTXL_OFFSET, XEmacPs_ReadReg, XEMACPS_RECEIVER_ENABLE_OPTION, XEMACPS_RECV, XEMACPS_RX_BUF_SIZE, XEMACPS_RX_BUF_UNIT, XEMACPS_RXBUF_LEN_MASK, XEMACPS_RXSR_OFFSET, XEMACPS_SEND, XEmacPs_SetMacAddress, XEmacPs_SetOptions, XEmacPs_SetQueuePtr, XEmacPs_SetTypeIdCheck, XEmacPs_SetupPCS, XEMACPS_SR_ALL_MASK, XEmacPs_Stop, XEMACPS_TRANSMITTER_ENABLE_OPTION, XEMACPS_TXSR_OFFSET, XEmacPs_WriteReg.
Referenced by XEmacPs_CfgInitialize.
void XEmacPs_SetQueuePtr(XEmacPs *InstancePtr, UINTPTR QPtr, u8 QueueNum, u16 Direction)
This function sets the start address of the transmit/receive buffer queue.
InstancePtr is a pointer to the instance to be worked on. QPtr is the address of the Queue to be written QueueNum is the Buffer Queue Index Direction indicates Transmit/Receive The buffer queue addresses has to be set before starting the transfer, so this function has to be called in prior to XEmacPs_Start()
References XEmacPs_Config::BaseAddress, XEmacPs_GetQxOffset, XEMACPS_MSBBUF_RXQBASE_OFFSET, XEMACPS_MSBBUF_TXQBASE_OFFSET, XEMACPS_SEND, XEmacPs_WriteReg.
Referenced by EmacPsDmaSingleFrameIntrExample, XEmacPs_Reset.
static u8 get_num_set_bits(u32 n)
XEmacPs_Config * XEmacPs_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
A table contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration table entry corresponding to the given device ID/BaseAddress, or NULL if no match is found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XEmacPs_Config::Name.
Referenced by EmacPsDmaIntrExample.
LONG XEmacPs_SetHandler(XEmacPs *InstancePtr, u32 HandlerType, void *FuncPointer, void *CallBackRef)
Install an asynchronous handler function for the given HandlerType:
InstancePtr is a pointer to the instance to be worked on. HandlerType indicates what interrupt handler type is. XEMACPS_HANDLER_DMASEND, XEMACPS_HANDLER_DMARECV and XEMACPS_HANDLER_ERROR. FuncPointer is the pointer to the callback function CallBackRef is the upper layer callback reference passed back when when the callback function is invoked. None.There is no assert on the CallBackRef since the driver doesn't know what it is.
Referenced by EmacPsDmaIntrExample.
void XEmacPs_IntrHandler(void *XEmacPsPtr)
Master interrupt handler for EMAC driver.
This routine will query the status of the device, bump statistics, and invoke user callbacks.This routine must be connected to an interrupt controller using OS/BSP specific methods. XEmacPsPtr is a pointer to the XEMACPS instance that has caused the interrupt.
References XEmacPs_Config::BaseAddress, XEmacPs_GetQxOffset, XEMACPS_ISR_OFFSET, XEMACPS_IXR_RXUSED_MASK, XEMACPS_IXR_TXCOMPL_MASK, XEMACPS_NWCTRL_FLUSH_DPRAM_MASK, XEMACPS_NWCTRL_OFFSET, XEmacPs_ReadReg, XEMACPS_RECV, XEMACPS_RXSR_BUFFNA_MASK, XEMACPS_RXSR_FRAMERX_MASK, XEMACPS_RXSR_OFFSET, XEMACPS_SEND, XEMACPS_TXSR_OFFSET, XEMACPS_TXSR_TXCOMPL_MASK, XEMACPS_TXSR_USEDREAD_MASK, XEmacPs_WriteReg.
Referenced by EmacPsDmaIntrExample.
LONG XEmacPs_SetOptions(XEmacPs *InstancePtr, u32 Options)
Set options for the driver/device.
The driver should be stopped with XEmacPs_Stop() before changing options. InstancePtr is a pointer to the instance to be worked on. Options are the options to set. Multiple options can be set by OR'ing XTE_*_OPTIONS constants together. Options not specified are not affected. XST_SUCCESS if the options were set successfullyXST_DEVICE_IS_STARTED if the device has not yet been stopped See xemacps.h for a description of the available options.
References XEmacPs_Config::BaseAddress, XEMACPS_BROADCAST_OPTION, XEMACPS_DMACR_OFFSET, XEMACPS_DMACR_RXBUF_MASK, XEMACPS_DMACR_RXBUF_SHIFT, XEMACPS_DMACR_TCPCKSUM_MASK, XEMACPS_FCS_STRIP_OPTION, XEMACPS_FLOW_CONTROL_OPTION, XEMACPS_FRAME1536_OPTION, XEMACPS_JUMBOMAXLEN_OFFSET, XEMACPS_LENTYPE_ERR_OPTION, XEMACPS_MULTICAST_OPTION, XEMACPS_NWCFG_1000_MASK, XEMACPS_NWCFG_1536RXEN_MASK, XEMACPS_NWCFG_BCASTDI_MASK, XEMACPS_NWCFG_COPYALLEN_MASK, XEMACPS_NWCFG_FCSREM_MASK, XEMACPS_NWCFG_JUMBO_MASK, XEMACPS_NWCFG_LENERRDSCRD_MASK, XEMACPS_NWCFG_MCASTHASHEN_MASK, XEMACPS_NWCFG_NVLANDISC_MASK, XEMACPS_NWCFG_OFFSET, XEMACPS_NWCFG_PAUSEEN_MASK, XEMACPS_NWCFG_PCSSEL_MASK, XEMACPS_NWCFG_RXCHKSUMEN_MASK, XEMACPS_NWCFG_SGMIIEN_MASK, XEMACPS_NWCTRL_OFFSET, XEMACPS_NWCTRL_RXEN_MASK, XEMACPS_NWCTRL_TXEN_MASK, XEMACPS_PROMISC_OPTION, XEmacPs_ReadReg, XEMACPS_RECEIVER_ENABLE_OPTION, XEMACPS_RX_BUF_UNIT, XEMACPS_RX_CHKSUM_ENABLE_OPTION, XEMACPS_RXBUF_LEN_JUMBO_MASK, XEMACPS_TRANSMITTER_ENABLE_OPTION, XEMACPS_TX_CHKSUM_ENABLE_OPTION, XEMACPS_VLAN_OPTION, XEmacPs_WriteReg.
Referenced by EmacPsDmaIntrExample, XEmacPs_Reset.
LONG XEmacPs_ClearOptions(XEmacPs *InstancePtr, u32 Options)
Clear options for the driver/device.
InstancePtr is a pointer to the instance to be worked on. Options are the options to clear. Multiple options can be cleared by OR'ing XEMACPS_*_OPTIONS constants together. Options not specified are not affected. XST_SUCCESS if the options were set successfullyXST_DEVICE_IS_STARTED if the device has not yet been stopped See xemacps.h for a description of the available options.
References XEmacPs_Config::BaseAddress, XEMACPS_BROADCAST_OPTION, XEMACPS_DMACR_OFFSET, XEMACPS_DMACR_RXBUF_MASK, XEMACPS_DMACR_RXBUF_SHIFT, XEMACPS_DMACR_TCPCKSUM_MASK, XEMACPS_FCS_STRIP_OPTION, XEMACPS_FLOW_CONTROL_OPTION, XEMACPS_FRAME1536_OPTION, XEMACPS_LENTYPE_ERR_OPTION, XEMACPS_MULTICAST_OPTION, XEMACPS_NWCFG_1000_MASK, XEMACPS_NWCFG_1536RXEN_MASK, XEMACPS_NWCFG_BCASTDI_MASK, XEMACPS_NWCFG_COPYALLEN_MASK, XEMACPS_NWCFG_FCSREM_MASK, XEMACPS_NWCFG_JUMBO_MASK, XEMACPS_NWCFG_LENERRDSCRD_MASK, XEMACPS_NWCFG_MCASTHASHEN_MASK, XEMACPS_NWCFG_NVLANDISC_MASK, XEMACPS_NWCFG_OFFSET, XEMACPS_NWCFG_PAUSEEN_MASK, XEMACPS_NWCFG_PCSSEL_MASK, XEMACPS_NWCFG_RXCHKSUMEN_MASK, XEMACPS_NWCFG_SGMIIEN_MASK, XEMACPS_NWCTRL_OFFSET, XEMACPS_NWCTRL_RXEN_MASK, XEMACPS_NWCTRL_TXEN_MASK, XEMACPS_PROMISC_OPTION, XEmacPs_ReadReg, XEMACPS_RECEIVER_ENABLE_OPTION, XEMACPS_RX_BUF_SIZE, XEMACPS_RX_BUF_UNIT, XEMACPS_RX_CHKSUM_ENABLE_OPTION, XEMACPS_RXBUF_LEN_MASK, XEMACPS_TRANSMITTER_ENABLE_OPTION, XEMACPS_TX_CHKSUM_ENABLE_OPTION, XEMACPS_VLAN_OPTION, XEmacPs_WriteReg.
Referenced by XEmacPs_Reset.
u32 XEmacPs_GetOptions(XEmacPs *InstancePtr)
Get current option settings.
InstancePtr is a pointer to the instance to be worked on. A bitmask of XTE_*_OPTION constants. Any bit set to 1 is to be interpreted as a set option. See xemacps.h for a description of the available options.
LONG XEmacPs_SetMacAddress(XEmacPs *InstancePtr, void *AddressPtr, u8 Index)
Set the MAC address for this driver/device.
The address is a 48-bit value. The device must be stopped before calling this function. InstancePtr is a pointer to the instance to be worked on. AddressPtr is a pointer to a 6-byte MAC address. Index is a index to which MAC (1-4) address. XST_SUCCESS if the MAC address was set successfullyXST_DEVICE_IS_STARTED if the device has not yet been stopped
References XEmacPs_Config::BaseAddress, XEMACPS_LADDR1H_OFFSET, XEMACPS_LADDR1L_OFFSET, XEMACPS_LADDR_MACH_MASK, XEMACPS_MAX_MAC_ADDR, XEmacPs_ReadReg, XEmacPs_WriteReg.
Referenced by EmacPsDmaIntrExample, XEmacPs_Reset.
LONG XEmacPs_DeleteHash(XEmacPs *InstancePtr, void *AddressPtr)
Delete 48-bit MAC addresses in hash table.
The device must be stopped before calling this function. InstancePtr is a pointer to the instance to be worked on. AddressPtr is a pointer to a 6-byte MAC address. XST_SUCCESS if the HASH MAC address was deleted successfullyXST_DEVICE_IS_STARTED if the device has not yet been stoppedXST_INVALID_PARAM if the HASH MAC address passed in does not meet requirement after calculation Having Aptr be unsigned type prevents the following operations from sign extending.
References XEmacPs_Config::BaseAddress, XEMACPS_HASHH_OFFSET, XEMACPS_HASHL_OFFSET, XEMACPS_MAX_HASH_BITS, XEmacPs_ReadReg, XEmacPs_WriteReg.
void XEmacPs_GetMacAddress(XEmacPs *InstancePtr, void *AddressPtr, u8 Index)
Get the MAC address for this driver/device.
InstancePtr is a pointer to the instance to be worked on. AddressPtr is an output parameter, and is a pointer to a buffer into which the current MAC address will be copied. Index is a index to which MAC (1-4) address.
References XEmacPs_Config::BaseAddress, XEMACPS_LADDR1H_OFFSET, XEMACPS_LADDR1L_OFFSET, XEMACPS_MAX_MAC_ADDR, XEmacPs_ReadReg.
LONG XEmacPs_SetHash(XEmacPs *InstancePtr, void *AddressPtr)
Set 48-bit MAC addresses in hash table.
The device must be stopped before calling this function.The hash address register is 64 bits long and takes up two locations in the memory map. The least significant bits are stored in hash register bottom and the most significant bits in hash register top.The unicast hash enable and the multicast hash enable bits in the network configuration register enable the reception of hash matched frames. The destination address is reduced to a 6 bit index into the 64 bit hash register using the following hash function. The hash function is an XOR of every sixth bit of the destination address. hash_index[05] = da[05]^da[11]^da[17]^da[23]^da[29]^da[35]^da[41]^da[47] hash_index[04] = da[04]^da[10]^da[16]^da[22]^da[28]^da[34]^da[40]^da[46] hash_index[03] = da[03]^da[09]^da[15]^da[21]^da[27]^da[33]^da[39]^da[45] hash_index[02] = da[02]^da[08]^da[14]^da[20]^da[26]^da[32]^da[38]^da[44] hash_index[01] = da[01]^da[07]^da[13]^da[19]^da[25]^da[31]^da[37]^da[43] hash_index[00] = da[00]^da[06]^da[12]^da[18]^da[24]^da[30]^da[36]^da[42] da[0] represents the least significant bit of the first byte received, that is, the multicast/unicast indicator, and da[47] represents the most significant bit of the last byte received.If the hash index points to a bit that is set in the hash register then the frame will be matched according to whether the frame is multicast or unicast.A multicast match will be signaled if the multicast hash enable bit is set, da[0] is logic 1 and the hash index points to a bit set in the hash register.A unicast match will be signaled if the unicast hash enable bit is set, da[0] is logic 0 and the hash index points to a bit set in the hash register.To receive all multicast frames, the hash register should be set with all ones and the multicast hash enable bit should be set in the network configuration register. InstancePtr is a pointer to the instance to be worked on. AddressPtr is a pointer to a 6-byte MAC address. XST_SUCCESS if the HASH MAC address was set successfullyXST_DEVICE_IS_STARTED if the device has not yet been stoppedXST_INVALID_PARAM if the HASH MAC address passed in does not meet requirement after calculation Having Aptr be unsigned type prevents the following operations from sign extending.
References XEmacPs_Config::BaseAddress, XEMACPS_HASHH_OFFSET, XEMACPS_HASHL_OFFSET, XEMACPS_MAX_HASH_BITS, XEmacPs_ReadReg, XEmacPs_WriteReg.
void XEmacPs_ClearHash(XEmacPs *InstancePtr)
Clear the Hash registers for the mac address pointed by AddressPtr.
InstancePtr is a pointer to the instance to be worked on.
References XEmacPs_Config::BaseAddress, XEMACPS_HASHH_OFFSET, XEMACPS_HASHL_OFFSET, XEmacPs_WriteReg.
Referenced by XEmacPs_Reset.
void XEmacPs_GetHash(XEmacPs *InstancePtr, void *AddressPtr)
Get the Hash address for this driver/device.
InstancePtr is a pointer to the instance to be worked on. AddressPtr is an output parameter, and is a pointer to a buffer into which the current HASH MAC address will be copied.
References XEmacPs_Config::BaseAddress, XEMACPS_HASHH_OFFSET, XEMACPS_HASHL_OFFSET, XEmacPs_ReadReg.
void XEmacPs_SetMdioDivisor(XEmacPs *InstancePtr, XEmacPs_MdcDiv Divisor)
Set the MDIO clock divisor.
Calculating the divisor: f[HOSTCLK] f[MDC] = ----------------- (1 + Divisor) * 2 where f[HOSTCLK] is the bus clock frequency in MHz, and f[MDC] is the MDIO clock frequency in MHz to the PHY. Typically, f[MDC] should not exceed 2.5 MHz. Some PHYs can tolerate faster speeds which means faster access. Here is the table to show values to generate MDC, 000 : divide pclk by 8 (pclk up to 20 MHz) 001 : divide pclk by 16 (pclk up to 40 MHz) 010 : divide pclk by 32 (pclk up to 80 MHz) 011 : divide pclk by 48 (pclk up to 120 MHz) 100 : divide pclk by 64 (pclk up to 160 MHz) 101 : divide pclk by 96 (pclk up to 240 MHz) 110 : divide pclk by 128 (pclk up to 320 MHz) 111 : divide pclk by 224 (pclk up to 540 MHz) InstancePtr is a pointer to the instance to be worked on. Divisor is the divisor to set. Range is 0b000 to 0b111.
References XEmacPs_Config::BaseAddress, XEmacPs_Config::MdioProducerBaseAddr, XEMACPS_NWCFG_MDC_SHIFT_MASK, XEMACPS_NWCFG_MDCCLKDIV_MASK, XEMACPS_NWCFG_OFFSET, XEmacPs_ReadReg, XEmacPs_WriteReg.
Referenced by EmacPsDmaIntrExample.
void XEmacPs_SetOperatingSpeed(XEmacPs *InstancePtr, u16 Speed)
XEmacPs_SetOperatingSpeed sets the current operating link speed.
For any traffic to be passed, this speed must match the current MII/GMII/SGMII/RGMII link speed. InstancePtr references the TEMAC channel on which to operate. Speed is the speed to set in units of Mbps. Valid values are 10, 100, or 1000. XEmacPs_SetOperatingSpeed ignores invalid values.
References XEmacPs_Config::BaseAddress, XEMACPS_NWCFG_1000_MASK, XEMACPS_NWCFG_100_MASK, XEMACPS_NWCFG_OFFSET, XEmacPs_ReadReg, XEmacPs_WriteReg.
Referenced by EmacPsDmaIntrExample.
u16 XEmacPs_GetOperatingSpeed(XEmacPs *InstancePtr)
XEmacPs_GetOperatingSpeed gets the current operating link speed.
This may be the value set by XEmacPs_SetOperatingSpeed() or a hardware default. InstancePtr references the TEMAC channel on which to operate. XEmacPs_GetOperatingSpeed returns the link speed in units of megabits per second.
References XEmacPs_Config::BaseAddress, XEMACPS_NWCFG_1000_MASK, XEMACPS_NWCFG_100_MASK, XEMACPS_NWCFG_OFFSET, XEmacPs_ReadReg.
LONG XEmacPs_PhyRead(XEmacPs *InstancePtr, u32 PhyAddress, u32 RegisterNum, u16 *PhyDataPtr)
Read the current value of the PHY register indicated by the PhyAddress and the RegisterNum parameters.
The MAC provides the driver with the ability to talk to a PHY that adheres to the Media Independent Interface (MII) as defined in the IEEE 802.3 standard.Prior to PHY access with this function, the user should have setup the MDIO clock with XEmacPs_SetMdioDivisor(). InstancePtr is a pointer to the XEmacPs instance to be worked on. PhyAddress is the address of the PHY to be read (supports multiple PHYs) RegisterNum is the register number, 0-31, of the specific PHY register to read PhyDataPtr is an output parameter, and points to a 16-bit buffer into which the current value of the register will be copied. XST_SUCCESS if the PHY was read from successfullyXST_EMAC_MII_BUSY if there is another PHY operation in progress This function is not thread-safe. The user must provide mutually exclusive access to this function if there are to be multiple threads that can call it.There is the possibility that this function will not return if the hardware is broken (i.e., it never sets the status bit indicating that the read is done). If this is of concern to the user, the user should provide a mechanism suitable to their needs for recovery.For the duration of this function, all host interface reads and writes are blocked to the current XEmacPs instance.
References XEmacPs_Config::BaseAddress, XEmacPs_Config::MdioProducerBaseAddr, XEMACPS_NWSR_MDIOIDLE_MASK, XEMACPS_NWSR_OFFSET, XEMACPS_PHYMNTNC_OFFSET, XEMACPS_PHYMNTNC_OP_MASK, XEMACPS_PHYMNTNC_OP_R_MASK, XEMACPS_PHYMNTNC_PHAD_SHFT_MSK, XEMACPS_PHYMNTNC_PREG_SHFT_MSK, XEmacPs_ReadReg, XEmacPs_WriteReg.
LONG XEmacPs_PhyWrite(XEmacPs *InstancePtr, u32 PhyAddress, u32 RegisterNum, u16 PhyData)
Write data to the specified PHY register.
The Ethernet driver does not require the device to be stopped before writing to the PHY. Although it is probably a good idea to stop the device, it is the responsibility of the application to deem this necessary. The MAC provides the driver with the ability to talk to a PHY that adheres to the Media Independent Interface (MII) as defined in the IEEE 802.3 standard.Prior to PHY access with this function, the user should have setup the MDIO clock with XEmacPs_SetMdioDivisor(). InstancePtr is a pointer to the XEmacPs instance to be worked on. PhyAddress is the address of the PHY to be written (supports multiple PHYs) RegisterNum is the register number, 0-31, of the specific PHY register to write PhyData is the 16-bit value that will be written to the register XST_SUCCESS if the PHY was written to successfully. Since there is no error status from the MAC on a write, the user should read the PHY to verify the write was successful.XST_EMAC_MII_BUSY if there is another PHY operation in progress This function is not thread-safe. The user must provide mutually exclusive access to this function if there are to be multiple threads that can call it.There is the possibility that this function will not return if the hardware is broken (i.e., it never sets the status bit indicating that the write is done). If this is of concern to the user, the user should provide a mechanism suitable to their needs for recovery.For the duration of this function, all host interface reads and writes are blocked to the current XEmacPs instance.
References XEmacPs_Config::BaseAddress, XEmacPs_Config::MdioProducerBaseAddr, XEMACPS_NWSR_MDIOIDLE_MASK, XEMACPS_NWSR_OFFSET, XEMACPS_PHYMNTNC_OFFSET, XEMACPS_PHYMNTNC_OP_MASK, XEMACPS_PHYMNTNC_OP_W_MASK, XEMACPS_PHYMNTNC_PHAD_SHFT_MSK, XEMACPS_PHYMNTNC_PREG_SHFT_MSK, XEmacPs_ReadReg, XEmacPs_WriteReg.
LONG XEmacPs_SetTypeIdCheck(XEmacPs *InstancePtr, u32 Id_Check, u8 Index)
Set the Type ID match for this driver/device.
The register is a 32-bit value. The device must be stopped before calling this function. InstancePtr is a pointer to the instance to be worked on. Id_Check is type ID to be configured. Index is a index to which Type ID (1-4). XST_SUCCESS if the MAC address was set successfullyXST_DEVICE_IS_STARTED if the device has not yet been stopped
References XEmacPs_Config::BaseAddress, XEMACPS_MATCH1_OFFSET, XEMACPS_MAX_TYPE_ID, XEmacPs_WriteReg.
Referenced by XEmacPs_Reset.
LONG XEmacPs_SendPausePacket(XEmacPs *InstancePtr)
Send a pause packet.
InstancePtr is a pointer to the instance to be worked on. XST_SUCCESS if pause frame transmission was initiatedXST_DEVICE_IS_STOPPED if the device has not been started.
References XEmacPs_Config::BaseAddress, XEMACPS_NWCTRL_OFFSET, XEMACPS_NWCTRL_PAUSETX_MASK, XEmacPs_ReadReg, XEmacPs_WriteReg.
void XEmacPs_DMABLengthUpdate(XEmacPs *InstancePtr, s32 BLength)
API to update the Burst length in the DMACR register.
InstancePtr is a pointer to the XEmacPs instance to be worked on. BLength is the length in bytes for the dma burst. None
References XEmacPs_Config::BaseAddress, XEMACPS_DMACR_BLENGTH_MASK, XEMACPS_DMACR_INCR16_AHB_BURST, XEMACPS_DMACR_INCR4_AHB_BURST, XEMACPS_DMACR_INCR8_AHB_BURST, XEMACPS_DMACR_OFFSET, XEMACPS_DMACR_SINGLE_AHB_BURST, XEmacPs_ReadReg, XEmacPs_WriteReg.
int XEmacPs_IsCommonMdioPresent(XEmacPs *InstancePtr)
Check if a common MDIO (Management Data Input/Output) interface is present.
This function evaluates whether the GEM instance uses a shared MDIO interface by comparing the base address of the current instance with the MDIO producer base address. The existence of a valid MDIO producer base address is also checked. InstancePtr is a pointer to the XEmacPs instance being checked. TRUE if a common MDIO is present (when the base address of the instance differs from the MDIO producer base address, and the producer base address is non-zero).FALSE otherwise.
References XEmacPs_Config::BaseAddress, XEmacPs_Config::MdioProducerBaseAddr.
Referenced by XEmacPs_Reset.
static void XEmacPs_BdSetRxWrap(UINTPTR BdPtr)
Set this bit to mark the last descriptor in the receive buffer descriptor list.
BdPtr is the BD pointer to operate on C-style signature: void XEmacPs_BdSetRxWrap(XEmacPs_Bd* BdPtr)
static void XEmacPs_BdSetTxWrap(UINTPTR BdPtr)
Sets this bit to mark the last descriptor in the transmit buffer descriptor list.
BdPtr is the BD pointer to operate on C-style signature: void XEmacPs_BdSetTxWrap(XEmacPs_Bd* BdPtr)
LONG XEmacPs_BdRingCreate(XEmacPs_BdRing *RingPtr, UINTPTR PhysAddr, UINTPTR VirtAddr, u32 Alignment, u32 BdCount)
Using a memory segment allocated by the caller, create and setup the BD list for the given DMA channel.
RingPtr is the instance to be worked on. PhysAddr is the physical base address of user memory region. VirtAddr is the virtual base address of the user memory region. If address translation is not being utilized, then VirtAddr should be equivalent to PhysAddr. Alignment governs the byte alignment of individual BDs. This function will enforce a minimum alignment of 4 bytes with no maximum as long as it is specified as a power of 2. BdCount is the number of BDs to setup in the user memory region. It is assumed the region is large enough to contain the BDs. XST_SUCCESS if initialization was successfulXST_NO_FEATURE if the provided instance is a non DMA type channel.XST_INVALID_PARAM under any of the following conditions: 1) PhysAddr and/or VirtAddr are not aligned to the given Alignment parameter. 2) Alignment parameter does not meet minimum requirements or is not a power of 2 value. 3) BdCount is 0.XST_DMA_SG_LIST_ERROR if the memory segment containing the list spans over address 0x00000000 in virtual address space. Make sure to pass in the right alignment value.
References XEmacPs_BdRing::AllCnt, XEmacPs_BdRing::BaseBdAddr, XEmacPs_BdRing::BdaRestart, XEmacPs_BdRing::FreeCnt, XEmacPs_BdRing::FreeHead, XEmacPs_BdRing::HighBdAddr, XEmacPs_BdRing::HwCnt, XEmacPs_BdRing::HwHead, XEmacPs_BdRing::HwTail, XEmacPs_BdRing::Length, XEmacPs_BdRing::PhysBaseAddr, XEmacPs_BdRing::PostCnt, XEmacPs_BdRing::PostHead, XEmacPs_BdRing::PreCnt, XEmacPs_BdRing::PreHead, XEmacPs_BdRing::RunState, XEmacPs_BdRing::Separation.
Referenced by EmacPsDmaIntrExample.
LONG XEmacPs_BdRingClone(XEmacPs_BdRing *RingPtr, XEmacPs_Bd *SrcBdPtr, u8 Direction)
Clone the given BD into every BD in the list.
every field of the source BD is replicated in every BD of the list.This function can be called only when all BDs are in the free group such as they are immediately after initialization with XEmacPs_BdRingCreate(). This prevents modification of BDs while they are in use by hardware or the user. RingPtr is the pointer of BD ring instance to be worked on. SrcBdPtr is the source BD template to be cloned into the list. This BD will be modified. Direction is either XEMACPS_SEND or XEMACPS_RECV that indicates which direction. XST_SUCCESS if the list was modified.XST_DMA_SG_NO_LIST if a list has not been created.XST_DMA_SG_LIST_ERROR if some of the BDs in this channel are under hardware or user control.XST_DEVICE_IS_STARTED if the DMA channel has not been stopped.
References XEmacPs_BdRing::AllCnt, XEmacPs_BdRing::BaseBdAddr, XEmacPs_BdRing::FreeCnt, XEmacPs_BdRing::RunState, XEmacPs_BdRing::Separation, XEMACPS_RECV, XEMACPS_SEND.
Referenced by EmacPsDmaIntrExample.
LONG XEmacPs_BdRingAlloc(XEmacPs_BdRing *RingPtr, u32 NumBd, XEmacPs_Bd **BdSetPtr)
Reserve locations in the BD list.
The set of returned BDs may be modified in preparation for future DMA transaction(s). Once the BDs are ready to be submitted to hardware, the user must call XEmacPs_BdRingToHw() in the same order which they were allocated here. Example: NumBd = 2, Status = XEmacPs_BdRingAlloc(MyRingPtr, NumBd, &MyBdSet), if (Status != XST_SUCCESS) { *Not enough BDs available for the request* } CurBd = MyBdSet, for (i=0; i<NumBd; i++) { * Prepare CurBd *..... * Onto next BD * CurBd = XEmacPs_BdRingNext(MyRingPtr, CurBd), } * Give list to hardware * Status = XEmacPs_BdRingToHw(MyRingPtr, NumBd, MyBdSet), A more advanced use of this function may allocate multiple sets of BDs. They must be allocated and given to hardware in the correct sequence: * Legal * XEmacPs_BdRingAlloc(MyRingPtr, NumBd1, &MySet1), XEmacPs_BdRingToHw(MyRingPtr, NumBd1, MySet1), * Legal * XEmacPs_BdRingAlloc(MyRingPtr, NumBd1, &MySet1), XEmacPs_BdRingAlloc(MyRingPtr, NumBd2, &MySet2), XEmacPs_BdRingToHw(MyRingPtr, NumBd1, MySet1), XEmacPs_BdRingToHw(MyRingPtr, NumBd2, MySet2), * Not legal * XEmacPs_BdRingAlloc(MyRingPtr, NumBd1, &MySet1), XEmacPs_BdRingAlloc(MyRingPtr, NumBd2, &MySet2), XEmacPs_BdRingToHw(MyRingPtr, NumBd2, MySet2), XEmacPs_BdRingToHw(MyRingPtr, NumBd1, MySet1), Use the API defined in xemacps_bd.h to modify individual BDs. Traversal of the BD set can be done using XEmacPs_BdRingNext() and XEmacPs_BdRingPrev(). RingPtr is a pointer to the BD ring instance to be worked on. NumBd is the number of BDs to allocate BdSetPtr is an output parameter, it points to the first BD available for modification. XST_SUCCESS if the requested number of BDs was returned in the BdSetPtr parameter.XST_FAILURE if there were not enough free BDs to satisfy the request. This function should not be preempted by another XEmacPs_Bd function call that modifies the BD space. It is the caller's responsibility to provide a mutual exclusion mechanism.Do not modify more BDs than the number requested with the NumBd parameter. Doing so will lead to data corruption and system instability.
References XEmacPs_BdRing::FreeCnt, XEmacPs_BdRing::FreeHead, XEmacPs_BdRing::PreCnt.
Referenced by EmacPsDmaSingleFrameIntrExample.
LONG XEmacPs_BdRingUnAlloc(XEmacPs_BdRing *RingPtr, u32 NumBd, XEmacPs_Bd *BdSetPtr)
Fully or partially undo an XEmacPs_BdRingAlloc() operation.
Use this function if all the BDs allocated by XEmacPs_BdRingAlloc() could not be transferred to hardware with XEmacPs_BdRingToHw().This function helps out in situations when an unrelated error occurs after BDs have been allocated but before they have been given to hardware. An example of this type of error would be an OS running out of resources.This function is not the same as XEmacPs_BdRingFree(). The Free function returns BDs to the free list after they have been processed by hardware, while UnAlloc returns them before being processed by hardware.There are two scenarios where this function can be used. Full UnAlloc or Partial UnAlloc. A Full UnAlloc means all the BDs Alloc'd will be returned: Status = XEmacPs_BdRingAlloc(MyRingPtr, 10, &BdPtr), ... if (Error) { Status = XEmacPs_BdRingUnAlloc(MyRingPtr, 10, &BdPtr), } A partial UnAlloc means some of the BDs Alloc'd will be returned: Status = XEmacPs_BdRingAlloc(MyRingPtr, 10, &BdPtr), BdsLeft = 10, CurBdPtr = BdPtr, while (BdsLeft) { if (Error) { Status = XEmacPs_BdRingUnAlloc(MyRingPtr, BdsLeft, CurBdPtr), } CurBdPtr = XEmacPs_BdRingNext(MyRingPtr, CurBdPtr), BdsLeft--, } A partial UnAlloc must include the last BD in the list that was Alloc'd. RingPtr is a pointer to the instance to be worked on. NumBd is the number of BDs to allocate BdSetPtr is an output parameter, it points to the first BD available for modification. XST_SUCCESS if the BDs were unallocated.XST_FAILURE if NumBd parameter was greater that the number of BDs in the preprocessing state. This function should not be preempted by another XEmacPs_Bd function call that modifies the BD space. It is the caller's responsibility to provide a mutual exclusion mechanism.
References XEmacPs_BdRing::FreeCnt, XEmacPs_BdRing::FreeHead, XEmacPs_BdRing::PreCnt.
LONG XEmacPs_BdRingToHw(XEmacPs_BdRing *RingPtr, u32 NumBd, XEmacPs_Bd *BdSetPtr)
Enqueue a set of BDs to hardware that were previously allocated by XEmacPs_BdRingAlloc().
Once this function returns, the argument BD set goes under hardware control. Any changes made to these BDs after this point will corrupt the BD list leading to data corruption and system instability.The set will be rejected if the last BD of the set does not mark the end of a packet (see XEmacPs_BdSetLast()). RingPtr is a pointer to the instance to be worked on. NumBd is the number of BDs in the set. BdSetPtr is the first BD of the set to commit to hardware. XST_SUCCESS if the set of BDs was accepted and enqueued to hardware.XST_FAILURE if the set of BDs was rejected because the last BD of the set did not have its "last" bit set.XST_DMA_SG_LIST_ERROR if this function was called out of sequence with XEmacPs_BdRingAlloc(). This function should not be preempted by another XEmacPs_Bd function call that modifies the BD space. It is the caller's responsibility to provide a mutual exclusion mechanism.
References XEmacPs_BdRing::HwCnt, XEmacPs_BdRing::HwTail, XEmacPs_BdRing::PreCnt, XEmacPs_BdRing::PreHead, XEmacPs_BdRingNext.
Referenced by EmacPsDmaSingleFrameIntrExample.
u32 XEmacPs_BdRingFromHwTx(XEmacPs_BdRing *RingPtr, u32 BdLimit, XEmacPs_Bd **BdSetPtr)
Returns a set of BD(s) that have been processed by hardware.
The returned BDs may be examined to determine the outcome of the DMA transaction(s). Once the BDs have been examined, the user must call XEmacPs_BdRingFree() in the same order which they were retrieved here. Example: NumBd = XEmacPs_BdRingFromHwTx(MyRingPtr, MaxBd, &MyBdSet), if (NumBd == 0) { * hardware has nothing ready for us yet* } CurBd = MyBdSet, for (i=0; i<NumBd; i++) { * Examine CurBd for post processing *..... * Onto next BD * CurBd = XEmacPs_BdRingNext(MyRingPtr, CurBd), } XEmacPs_BdRingFree(MyRingPtr, NumBd, MyBdSet), *Return list* } A more advanced use of this function may allocate multiple sets of BDs. They must be retrieved from hardware and freed in the correct sequence: * Legal * XEmacPs_BdRingFromHwTx(MyRingPtr, NumBd1, &MySet1), XEmacPs_BdRingFree(MyRingPtr, NumBd1, MySet1), * Legal * XEmacPs_BdRingFromHwTx(MyRingPtr, NumBd1, &MySet1), XEmacPs_BdRingFromHwTx(MyRingPtr, NumBd2, &MySet2), XEmacPs_BdRingFree(MyRingPtr, NumBd1, MySet1), XEmacPs_BdRingFree(MyRingPtr, NumBd2, MySet2), * Not legal * XEmacPs_BdRingFromHwTx(MyRingPtr, NumBd1, &MySet1), XEmacPs_BdRingFromHwTx(MyRingPtr, NumBd2, &MySet2), XEmacPs_BdRingFree(MyRingPtr, NumBd2, MySet2), XEmacPs_BdRingFree(MyRingPtr, NumBd1, MySet1), If hardware has only partially completed a packet spanning multiple BDs, then none of the BDs for that packet will be included in the results. RingPtr is a pointer to the instance to be worked on. BdLimit is the maximum number of BDs to return in the set. BdSetPtr is an output parameter, it points to the first BD available for examination. The number of BDs processed by hardware. A value of 0 indicates that no data is available. No more than BdLimit BDs will be returned. Treat BDs returned by this function as read-only.This function should not be preempted by another XEmacPs_Bd function call that modifies the BD space. It is the caller's responsibility to provide a mutual exclusion mechanism.
References XEmacPs_BdRing::HwCnt, XEmacPs_BdRing::HwHead, XEmacPs_BdRing::HwTail, XEmacPs_BdRing::PostCnt, XEMACPS_BD_STAT_OFFSET, XEmacPs_BdRead, XEmacPs_BdRingNext, XEMACPS_TXBUF_LAST_MASK, XEMACPS_TXBUF_USED_MASK.
Referenced by EmacPsDmaSingleFrameIntrExample.
u32 XEmacPs_BdRingFromHwRx(XEmacPs_BdRing *RingPtr, u32 BdLimit, XEmacPs_Bd **BdSetPtr)
Returns a set of BD(s) that have been processed by hardware.
The returned BDs may be examined to determine the outcome of the DMA transaction(s). Once the BDs have been examined, the user must call XEmacPs_BdRingFree() in the same order which they were retrieved here. Example: NumBd = XEmacPs_BdRingFromHwRx(MyRingPtr, MaxBd, &MyBdSet), if (NumBd == 0) { *hardware has nothing ready for us yet* } CurBd = MyBdSet, for (i=0; i<NumBd; i++) { * Examine CurBd for post processing *..... * Onto next BD * CurBd = XEmacPs_BdRingNext(MyRingPtr, CurBd), } XEmacPs_BdRingFree(MyRingPtr, NumBd, MyBdSet), * Return list * } A more advanced use of this function may allocate multiple sets of BDs. They must be retrieved from hardware and freed in the correct sequence: * Legal * XEmacPs_BdRingFromHwRx(MyRingPtr, NumBd1, &MySet1), XEmacPs_BdRingFree(MyRingPtr, NumBd1, MySet1), * Legal * XEmacPs_BdRingFromHwRx(MyRingPtr, NumBd1, &MySet1), XEmacPs_BdRingFromHwRx(MyRingPtr, NumBd2, &MySet2), XEmacPs_BdRingFree(MyRingPtr, NumBd1, MySet1), XEmacPs_BdRingFree(MyRingPtr, NumBd2, MySet2), * Not legal * XEmacPs_BdRingFromHwRx(MyRingPtr, NumBd1, &MySet1), XEmacPs_BdRingFromHwRx(MyRingPtr, NumBd2, &MySet2), XEmacPs_BdRingFree(MyRingPtr, NumBd2, MySet2), XEmacPs_BdRingFree(MyRingPtr, NumBd1, MySet1), If hardware has only partially completed a packet spanning multiple BDs, then none of the BDs for that packet will be included in the results. RingPtr is a pointer to the instance to be worked on. BdLimit is the maximum number of BDs to return in the set. BdSetPtr is an output parameter, it points to the first BD available for examination. The number of BDs processed by hardware. A value of 0 indicates that no data is available. No more than BdLimit BDs will be returned. Treat BDs returned by this function as read-only.This function should not be preempted by another XEmacPs_Bd function call that modifies the BD space. It is the caller's responsibility to provide a mutual exclusion mechanism.
References XEmacPs_BdRing::HwCnt, XEmacPs_BdRing::HwHead, XEmacPs_BdRing::HwTail, XEmacPs_BdRing::PostCnt, XEMACPS_BD_STAT_OFFSET, XEmacPs_BdIsRxNew, XEmacPs_BdRead, XEmacPs_BdRingNext, XEMACPS_RXBUF_EOF_MASK.
Referenced by EmacPsDmaSingleFrameIntrExample.
LONG XEmacPs_BdRingFree(XEmacPs_BdRing *RingPtr, u32 NumBd, XEmacPs_Bd *BdSetPtr)
Frees a set of BDs that had been previously retrieved with XEmacPs_BdRingFromHw().
RingPtr is a pointer to the instance to be worked on. NumBd is the number of BDs to free. BdSetPtr is the head of a list of BDs returned by XEmacPs_BdRingFromHw(). XST_SUCCESS if the set of BDs was freed.XST_DMA_SG_LIST_ERROR if this function was called out of sequence with XEmacPs_BdRingFromHw(). This function should not be preempted by another XEmacPs_Bd function call that modifies the BD space. It is the caller's responsibility to provide a mutual exclusion mechanism.
References XEmacPs_BdRing::FreeCnt, XEmacPs_BdRing::PostCnt, XEmacPs_BdRing::PostHead.
Referenced by EmacPsDmaSingleFrameIntrExample.
LONG XEmacPs_BdRingCheck(XEmacPs_BdRing *RingPtr, u8 Direction)
Check the internal data structures of the BD ring for the provided channel.
The following checks are made: Is the BD ring linked correctly in physical address space.Do the internal pointers point to BDs in the ring.Do the internal counters add up. The channel should be stopped prior to calling this function. RingPtr is a pointer to the instance to be worked on. Direction is either XEMACPS_SEND or XEMACPS_RECV that indicates which direction. XST_SUCCESS if the set of BDs was freed.XST_DMA_SG_NO_LIST if the list has not been created.XST_IS_STARTED if the channel is not stopped.XST_DMA_SG_LIST_ERROR if a problem is found with the internal data structures. If this value is returned, the channel should be reset to avoid data corruption or system instability. This function should not be preempted by another XEmacPs_Bd function call that modifies the BD space. It is the caller's responsibility to provide a mutual exclusion mechanism.
References XEmacPs_BdRing::AllCnt, XEmacPs_BdRing::BaseBdAddr, XEmacPs_BdRing::FreeCnt, XEmacPs_BdRing::FreeHead, XEmacPs_BdRing::HighBdAddr, XEmacPs_BdRing::HwCnt, XEmacPs_BdRing::HwHead, XEmacPs_BdRing::HwTail, XEmacPs_BdRing::PhysBaseAddr, XEmacPs_BdRing::PostCnt, XEmacPs_BdRing::PostHead, XEmacPs_BdRing::PreCnt, XEmacPs_BdRing::PreHead, XEmacPs_BdRing::RunState, XEmacPs_BdRing::Separation, XEMACPS_BD_ADDR_OFFSET, XEmacPs_BdIsRxWrap, XEmacPs_BdIsTxWrap, XEmacPs_BdRead, XEMACPS_RECV, XEMACPS_SEND.
void XEmacPs_BdRingPtrReset(XEmacPs_BdRing *RingPtr, void *virtaddrloc)
Reset BD ring head and tail pointers.
RingPtr is the instance to be worked on. virtaddrloc is the virtual base address of the user memory region. Should be called after XEmacPs_Stop()C-style signature: void XEmacPs_BdRingPtrReset(XEmacPs_BdRing * RingPtr, void *virtaddrloc)
References XEmacPs_BdRing::FreeHead, XEmacPs_BdRing::HwHead, XEmacPs_BdRing::HwTail, XEmacPs_BdRing::PostHead, XEmacPs_BdRing::PreHead.
void XEmacPs_ResetHw(u32 BaseAddr)
This function perform the reset sequence to the given emacps interface by configuring the appropriate control bits in the emacps specific registers.
the emacps reset sequence involves the following steps Disable all the interuupts Clear the status registers Disable Rx and Tx engines Update the Tx and Rx descriptor queue registers with reset values Update the other relevant control registers with reset value BaseAddr of the interface N/A This function will not modify the slcr registers that are relevant for emacps controller
References XEMACPS_HASHH_OFFSET, XEMACPS_HASHL_OFFSET, XEMACPS_IDR_OFFSET, XEMACPS_ISR_OFFSET, XEMACPS_IXR_ALL_MASK, XEMACPS_NWCFG_OFFSET, XEMACPS_NWCFG_RESET_MASK, XEMACPS_NWCTRL_FLUSH_DPRAM_MASK, XEMACPS_NWCTRL_HALTTX_MASK, XEMACPS_NWCTRL_LOOPEN_MASK, XEMACPS_NWCTRL_OFFSET, XEMACPS_NWCTRL_RXEN_MASK, XEMACPS_NWCTRL_STATCLR_MASK, XEMACPS_NWCTRL_TXEN_MASK, XEmacPs_ReadReg, XEMACPS_RXQBASE_OFFSET, XEMACPS_RXSR_FRAMERX_MASK, XEMACPS_RXSR_OFFSET, XEMACPS_TXQBASE_OFFSET, XEMACPS_TXSR_OFFSET, XEMACPS_TXSR_TXCOMPL_MASK, XEMACPS_TXSR_TXGO_MASK, XEmacPs_WriteReg.
u32 XEmacPs_GetQxOffset(XEmacPs_QxRegOffset RegName, u8 Queue)
The register offset of a specific queue register is returned by this function.
RegName Basename of the register Queue Corresponding Queue Register offset
References XEMACPS_DMA_RXQ1_BUFSIZE_OFFSET, XEMACPS_DMA_RXQ2_BUFSIZE_OFFSET, XEMACPS_DMA_RXQ3_BUFSIZE_OFFSET, XEMACPS_INTQ1_IDR_OFFSET, XEMACPS_INTQ1_IER_OFFSET, XEMACPS_INTQ1_STS_OFFSET, XEMACPS_INTQ2_IDR_OFFSET, XEMACPS_INTQ2_IER_OFFSET, XEMACPS_INTQ2_STS_OFFSET, XEMACPS_INTQ3_IDR_OFFSET, XEMACPS_INTQ3_IER_OFFSET, XEMACPS_INTQ3_STS_OFFSET, XEMACPS_ISR_OFFSET, XEMACPS_RXQ1BASE_OFFSET, XEMACPS_RXQ2BASE_OFFSET, XEMACPS_RXQ3BASE_OFFSET, XEMACPS_RXQBASE_OFFSET, XEMACPS_TXQ1BASE_OFFSET, XEMACPS_TXQ2BASE_OFFSET, XEMACPS_TXQ3BASE_OFFSET, XEMACPS_TXQBASE_OFFSET.
Referenced by XEmacPs_IntrHandler, XEmacPs_Reset, XEmacPs_SetQueuePtr.
void XEmacPs_SetupPCS(XEmacPs *EmacPsInstancePtr)
Set up PCS as follows for every given speed:
Configure HS_MAC register for given speedConfigure serdes rate and speed in USX_CONTROL registerAssert Rx reset signal for GT resetWait for PCS_BLOCK_LOCK InstancePtr is a pointer to the instance to be worked on. N/A
References XEmacPs_Config::BaseAddress, XEMACPS_NWSR_MDIOIDLE_MASK, XEmacPs_WriteReg.
Referenced by XEmacPs_Reset.
bool XEmacPs_USXPCSGetState(UINTPTR BaseAddr)
Get USX synchronisation status.
BaseAddr is the base address of the device true if block synchronization achievedfalse if block is out of sync
References XEmacPs_ReadReg.
bool XEmacPs_IsHighSpeedPCS(UINTPTR BaseAddr)
Detect if the device supports High Speeds ( 5G, 10G )
BaseAddr is the base address of the device true if the device support High Speedfalse if the device doesn't support High Speed
References XEmacPs_ReadReg.
Referenced by XEmacPs_Reset.
XEMACPS_H
XEMACPS_DEVICE_NAME
XEMACPS_DEVICE_DESC
XEMACPS_MDIO_DIV_DFT
Default MDIO clock divisor.
XEMACPS_MAC_ADDR_SIZE
XEMACPS_MTU
XEMACPS_MTU_JUMBO
XEMACPS_HDR_SIZE
XEMACPS_HDR_VLAN_SIZE
XEMACPS_TRL_SIZE
XEMACPS_MAX_FRAME_SIZE
XEMACPS_MAX_VLAN_FRAME_SIZE
XEMACPS_MAX_VLAN_FRAME_SIZE_JUMBO
XEMACPS_SINGLE_BURST
XEMACPS_4BYTE_BURST
XEMACPS_8BYTE_BURST
XEMACPS_16BYTE_BURST
CLOCK_FREQ_1000MBPS
CLOCK_FREQ_100MBPS
CLOCK_FREQ_10MBPS
XEmacPs_GetTxRing
Retrieve the Tx ring object.
This object can be used in the various Ring API functions. InstancePtr is the DMA channel to operate on. TxBdRing attribute C-style signature: XEmacPs_BdRing XEmacPs_GetTxRing(XEmacPs *InstancePtr)
Referenced by EmacPsDmaIntrExample, EmacPsDmaSingleFrameIntrExample.
XEmacPs_GetRxRing
Retrieve the Rx ring object.
This object can be used in the various Ring API functions. InstancePtr is the DMA channel to operate on. RxBdRing attribute C-style signature: XEmacPs_BdRing XEmacPs_GetRxRing(XEmacPs *InstancePtr)
Referenced by EmacPsDmaIntrExample, EmacPsDmaSingleFrameIntrExample.
XEmacPs_IntEnable
Enable interrupts specified in Mask.
The corresponding interrupt for each bit set to 1 in Mask, will be enabled. InstancePtr is a pointer to the instance to be worked on. Mask contains a bit mask of interrupts to enable. The mask can be formed using a set of bitwise or'd values. The state of the transmitter and receiver are not modified by this function. C-style signature void XEmacPs_IntEnable(XEmacPs *InstancePtr, u32 Mask)
Referenced by XEmacPs_Start.
XEmacPs_IntDisable
Disable interrupts specified in Mask.
The corresponding interrupt for each bit set to 1 in Mask, will be enabled. InstancePtr is a pointer to the instance to be worked on. Mask contains a bit mask of interrupts to disable. The mask can be formed using a set of bitwise or'd values. The state of the transmitter and receiver are not modified by this function. C-style signature void XEmacPs_IntDisable(XEmacPs *InstancePtr, u32 Mask)
XEmacPs_IntQiEnable
Enable interrupts of queue Queue specified in Mask.
The corresponding interrupt for each bit set to 1 in Mask, will be enabled. InstancePtr is a pointer to the instance to be worked on. Indx of Queue, it should be from 1. Mask contains a bit mask of interrupts to enable. The mask can be formed using a set of bitwise or'd values. The state of the transmitter and receiver are not modified by this function. C-style signature void XEmacPs_IntQiEnable(XEmacPs *InstancePtr, u8 Queue, u32 Mask)
Referenced by XEmacPs_Start.
XEmacPs_IntQiDisable
Disable interrupts of queue Queue specified in Mask.
The corresponding interrupt for each bit set to 1 in Mask, will be enabled. InstancePtr is a pointer to the instance to be worked on. Index of Queue, it should be from 1. Mask contains a bit mask of interrupts to disable. The mask can be formed using a set of bitwise or'd values. The state of the transmitter and receiver are not modified by this function. C-style signature void XEmacPs_IntDisable(XEmacPs *InstancePtr, u8 Queue, u32 Mask)
XEmacPs_Transmit
This macro triggers transmit circuit to send data currently in TX buffer(s).
InstancePtr is a pointer to the XEmacPs instance to be worked on. Signature: void XEmacPs_Transmit(XEmacPs *InstancePtr)
Referenced by EmacPsDmaSingleFrameIntrExample.
XEmacPs_IsRxCsum
This macro determines if the device is configured with checksum offloading on the receive channel.
InstancePtr is a pointer to the XEmacPs instance to be worked on. Boolean TRUE if the device is configured with checksum offloading, or FALSE otherwise. Signature: u32 XEmacPs_IsRxCsum(XEmacPs *InstancePtr)
XEmacPs_IsTxCsum
This macro determines if the device is configured with checksum offloading on the transmit channel.
InstancePtr is a pointer to the XEmacPs instance to be worked on. Boolean TRUE if the device is configured with checksum offloading, or FALSE otherwise. Signature: u32 XEmacPs_IsTxCsum(XEmacPs *InstancePtr)
XEmacPs_SetRXWatermark
This macro sets RX watermark register.
InstancePtr is a pointer to the XEmacPs instance to be worked on. High is the non-zero RX high watermark value. When SRAM fill level is above this, a pause frame will be sent. Low is the non-zero RX low watermark value. When SRAM fill level is below this, a zero length pause frame will be sent IF the last pause frame sent was non-zero. None Signature: void XEmacPs_SetRXWatermark(XEmacPs *InstancePtr, u16 High, u16 Low)
XEmacPs_GetRXWatermark
This macro gets RX watermark register.
InstancePtr is a pointer to the XEmacPs instance to be worked on. RX watermark register value Signature: void XEmacPs_GetRXWatermark(XEmacPs *InstancePtr)
BIT
SET_BIT
GET_BIT
CLEAR_BIT
GENMASK
XEMACPS_BD_H
XEMACPS_DMABD_MINIMUM_ALIGNMENT
XEMACPS_BD_NUM_WORDS
XEmacPs_BdClear
Zero out BD fields.
BdPtr is the BD pointer to operate on Nothing C-style signature: void XEmacPs_BdClear(XEmacPs_Bd* BdPtr)
Referenced by EmacPsDmaIntrExample, EmacPsDmaSingleFrameIntrExample.
XEmacPs_BdRead
Read the given Buffer Descriptor word.
BaseAddress is the base address of the BD to read Offset is the word offset to be read The 32-bit value of the field C-style signature: u32 XEmacPs_BdRead(UINTPTR BaseAddress, UINTPTR Offset)
Referenced by XEmacPs_BdRingCheck, XEmacPs_BdRingFromHwRx, XEmacPs_BdRingFromHwTx.
XEmacPs_BdWrite
Write the given Buffer Descriptor word.
BaseAddress is the base address of the BD to write Offset is the word offset to be written Data is the 32-bit value to write to the field None. C-style signature: void XEmacPs_BdWrite(UINTPTR BaseAddress, UINTPTR Offset, UINTPTR Data)
XEmacPs_BdSetAddressTx
Set the BD's Address field (word 0).
BdPtr is the BD pointer to operate on Addr is the value to write to BD's status field. : C-style signature: void XEmacPs_BdSetAddressTx(XEmacPs_Bd* BdPtr, UINTPTR Addr)
Referenced by EmacPsDmaSingleFrameIntrExample.
XEmacPs_BdSetAddressRx
Set the BD's Address field (word 0).
BdPtr is the BD pointer to operate on Addr is the value to write to BD's status field. : Due to some bits are mixed within receive BD's address field, read-modify-write is performed. C-style signature: void XEmacPs_BdSetAddressRx(XEmacPs_Bd* BdPtr, UINTPTR Addr)
Referenced by EmacPsDmaSingleFrameIntrExample.
XEmacPs_BdSetStatus
Set the BD's Status field (word 1).
BdPtr is the BD pointer to operate on Data is the value to write to BD's status field. C-style signature: void XEmacPs_BdSetStatus(XEmacPs_Bd* BdPtr, UINTPTR Data)
Referenced by EmacPsDmaIntrExample, EmacPsDmaSingleFrameIntrExample.
XEmacPs_BdGetStatus
Retrieve the BD's Packet DMA transfer status word (word 1).
BdPtr is the BD pointer to operate on Status word C-style signature: u32 XEmacPs_BdGetStatus(XEmacPs_Bd* BdPtr) Due to the BD bit layout differences in transmit and receive. User's caution is required.
XEmacPs_BdGetBufAddr
Get the address (bits 0..31) of the BD's buffer address (word 0)
BdPtr is the BD pointer to operate on C-style signature: UINTPTR XEmacPs_BdGetBufAddr(XEmacPs_Bd* BdPtr)
XEmacPs_BdSetLength
Set transfer length in bytes for the given BD.
The length must be set each time a BD is submitted to hardware. BdPtr is the BD pointer to operate on LenBytes is the number of bytes to transfer. C-style signature: void XEmacPs_BdSetLength(XEmacPs_Bd* BdPtr, u32 LenBytes)
Referenced by EmacPsDmaSingleFrameIntrExample.
XEmacPs_BdGetLength
Retrieve the BD length field.
For Tx channels, the returned value is the same as that written with XEmacPs_BdSetLength().For Rx channels, the returned value is the size of the received packet. BdPtr is the BD pointer to operate on Length field processed by hardware or set by XEmacPs_BdSetLength(). C-style signature: UINTPTR XEmacPs_BdGetLength(XEmacPs_Bd* BdPtr) XEAMCPS_RXBUF_LEN_MASK is same as XEMACPS_TXBUF_LEN_MASK.
Referenced by EmacPsDmaSingleFrameIntrExample.
XEmacPs_GetRxFrameSize
Retrieve the RX frame size.
The returned value is the size of the received packet. This API supports jumbo frame sizes if enabled. InstancePtr is the pointer to XEmacps instance BdPtr is the BD pointer to operate on Length field processed by hardware or set by XEmacPs_BdSetLength(). C-style signature: UINTPTR XEmacPs_GetRxFrameSize(XEmacPs* InstancePtr, XEmacPs_Bd* BdPtr) RxBufMask is dependent on whether jumbo is enabled or not.
Referenced by EmacPsDmaSingleFrameIntrExample.
XEmacPs_BdIsLast
Test whether the given BD has been marked as the last BD of a packet.
BdPtr is the BD pointer to operate on TRUE if BD represents the "Last" BD of a packet, FALSE otherwise C-style signature: UINTPTR XEmacPs_BdIsLast(XEmacPs_Bd* BdPtr)
XEmacPs_BdSetLast
Tell the DMA engine that the given transmit BD marks the end of the current packet to be processed.
BdPtr is the BD pointer to operate on C-style signature: void XEmacPs_BdSetLast(XEmacPs_Bd* BdPtr)
Referenced by EmacPsDmaSingleFrameIntrExample.
XEmacPs_BdClearLast
Tell the DMA engine that the current packet does not end with the given BD.
BdPtr is the BD pointer to operate on C-style signature: void XEmacPs_BdClearLast(XEmacPs_Bd* BdPtr)
XEmacPs_BdIsRxWrap
Set this bit to mark the last descriptor in the receive buffer descriptor list.
BdPtr is the BD pointer to operate on C-style signature: void XEmacPs_BdSetRxWrap(XEmacPs_Bd* BdPtr) Determine the wrap bit of the receive BD which indicates end of the BD list. BdPtr is the BD pointer to operate on C-style signature: u8 XEmacPs_BdIsRxWrap(XEmacPs_Bd* BdPtr)
Referenced by XEmacPs_BdRingCheck.
XEmacPs_BdIsTxWrap
Sets this bit to mark the last descriptor in the transmit buffer descriptor list.
BdPtr is the BD pointer to operate on C-style signature: void XEmacPs_BdSetTxWrap(XEmacPs_Bd* BdPtr) Determine the wrap bit of the transmit BD which indicates end of the BD list. BdPtr is the BD pointer to operate on C-style signature: u8 XEmacPs_BdGetTxWrap(XEmacPs_Bd* BdPtr)
Referenced by XEmacPs_BdRingCheck.
XEmacPs_BdClearRxNew
XEmacPs_BdIsRxNew
Determine the new bit of the receive BD.
BdPtr is the BD pointer to operate on C-style signature: UINTPTR XEmacPs_BdIsRxNew(XEmacPs_Bd* BdPtr)
Referenced by XEmacPs_BdRingFromHwRx.
XEmacPs_BdSetTxUsed
Software sets this bit to disable the buffer to be read by the hardware.
Hardware sets this bit for the first buffer of a frame once it has been successfully transmitted. This macro sets this bit of transmit BD to avoid confusion. BdPtr is the BD pointer to operate on C-style signature: void XEmacPs_BdSetTxUsed(XEmacPs_Bd* BdPtr)
XEmacPs_BdClearTxUsed
Software clears this bit to enable the buffer to be read by the hardware.
Hardware sets this bit for the first buffer of a frame once it has been successfully transmitted. This macro clears this bit of transmit BD. BdPtr is the BD pointer to operate on C-style signature: void XEmacPs_BdClearTxUsed(XEmacPs_Bd* BdPtr)
Referenced by EmacPsDmaSingleFrameIntrExample.
XEmacPs_BdIsTxUsed
Determine the used bit of the transmit BD.
BdPtr is the BD pointer to operate on C-style signature: UINTPTR XEmacPs_BdIsTxUsed(XEmacPs_Bd* BdPtr)
XEmacPs_BdIsTxRetry
Determine if a frame fails to be transmitted due to too many retries.
BdPtr is the BD pointer to operate on C-style signature: UINTPTR XEmacPs_BdIsTxRetry(XEmacPs_Bd* BdPtr)
XEmacPs_BdIsTxUrun
Determine if a frame fails to be transmitted due to data can not be feteched in time or buffers are exhausted.
BdPtr is the BD pointer to operate on C-style signature: UINTPTR XEmacPs_BdIsTxUrun(XEmacPs_Bd* BdPtr)
XEmacPs_BdIsTxExh
Determine if a frame fails to be transmitted due to buffer is exhausted mid-frame.
BdPtr is the BD pointer to operate on C-style signature: UINTPTR XEmacPs_BdIsTxExh(XEmacPs_Bd* BdPtr)
XEmacPs_BdSetTxNoCRC
Sets this bit, no CRC will be appended to the current frame.
This control bit must be set for the first buffer in a frame and will be ignored for the subsequent buffers of a frame. BdPtr is the BD pointer to operate on This bit must be clear when using the transmit checksum generation offload, otherwise checksum generation and substitution will not occur. C-style signature: UINTPTR XEmacPs_BdSetTxNoCRC(XEmacPs_Bd* BdPtr)
XEmacPs_BdClearTxNoCRC
Clear this bit, CRC will be appended to the current frame.
This control bit must be set for the first buffer in a frame and will be ignored for the subsequent buffers of a frame. BdPtr is the BD pointer to operate on This bit must be clear when using the transmit checksum generation offload, otherwise checksum generation and substitution will not occur. C-style signature: UINTPTR XEmacPs_BdClearTxNoCRC(XEmacPs_Bd* BdPtr)
XEmacPs_BdIsRxBcast
Determine the broadcast bit of the receive BD.
BdPtr is the BD pointer to operate on C-style signature: UINTPTR XEmacPs_BdIsRxBcast(XEmacPs_Bd* BdPtr)
XEmacPs_BdIsRxMultiHash
Determine the multicast hash bit of the receive BD.
BdPtr is the BD pointer to operate on C-style signature: UINTPTR XEmacPs_BdIsRxMultiHash(XEmacPs_Bd* BdPtr)
XEmacPs_BdIsRxUniHash
Determine the unicast hash bit of the receive BD.
BdPtr is the BD pointer to operate on C-style signature: UINTPTR XEmacPs_BdIsRxUniHash(XEmacPs_Bd* BdPtr)
XEmacPs_BdIsRxVlan
Determine if the received frame is a VLAN Tagged frame.
BdPtr is the BD pointer to operate on C-style signature: UINTPTR XEmacPs_BdIsRxVlan(XEmacPs_Bd* BdPtr)
XEmacPs_BdIsRxPri
Determine if the received frame has Type ID of 8100h and null VLAN identifier(Priority tag).
BdPtr is the BD pointer to operate on C-style signature: UINTPTR XEmacPs_BdIsRxPri(XEmacPs_Bd* BdPtr)
XEmacPs_BdIsRxCFI
Determine if the received frame's Concatenation Format Indicator (CFI) of the frames VLANTCI field was set.
BdPtr is the BD pointer to operate on C-style signature: UINTPTR XEmacPs_BdIsRxCFI(XEmacPs_Bd* BdPtr)
XEmacPs_BdIsRxEOF
Determine the End Of Frame (EOF) bit of the receive BD.
BdPtr is the BD pointer to operate on C-style signature: UINTPTR XEmacPs_BdGetRxEOF(XEmacPs_Bd* BdPtr)
XEmacPs_BdIsRxSOF
Determine the Start Of Frame (SOF) bit of the receive BD.
BdPtr is the BD pointer to operate on C-style signature: UINTPTR XEmacPs_BdGetRxSOF(XEmacPs_Bd* BdPtr)
XEMACPS_PHYS_TO_VIRT
XEMACPS_VIRT_TO_PHYS
XEMACPS_RING_SEEKAHEAD
XEMACPS_RING_SEEKBACK
XEMACPS_BDRING_H
XEmacPs_BdRingCntCalc
Use this macro at initialization time to determine how many BDs will fit in a BD list within the given memory constraints.
The results of this macro can be provided to XEmacPs_BdRingCreate(). Alignment specifies what byte alignment the BDs must fall on and must be a power of 2 to get an accurate calculation (32, 64, 128,...) Bytes is the number of bytes to be used to store BDs. Number of BDs that can fit in the given memory area C-style signature: u32 XEmacPs_BdRingCntCalc(u32 Alignment, u32 Bytes)
XEmacPs_BdRingMemCalc
Use this macro at initialization time to determine how many bytes of memory is required to contain a given number of BDs at a given alignment.
Alignment specifies what byte alignment the BDs must fall on. This parameter must be a power of 2 to get an accurate calculation (32, 64, 128,...) NumBd is the number of BDs to calculate memory size requirements for The number of bytes of memory required to create a BD list with the given memory constraints. C-style signature: u32 XEmacPs_BdRingMemCalc(u32 Alignment, u32 NumBd)
XEmacPs_BdRingGetCnt
Return the total number of BDs allocated by this channel with XEmacPs_BdRingCreate().
RingPtr is the DMA channel to operate on. The total number of BDs allocated for this channel. C-style signature: u32 XEmacPs_BdRingGetCnt(XEmacPs_BdRing* RingPtr)
XEmacPs_BdRingGetFreeCnt
Return the number of BDs allocatable with XEmacPs_BdRingAlloc() for pre- processing.
RingPtr is the DMA channel to operate on. The number of BDs currently allocatable. C-style signature: u32 XEmacPs_BdRingGetFreeCnt(XEmacPs_BdRing* RingPtr)
XEmacPs_BdRingNext
Return the next BD from BdPtr in a list.
RingPtr is the DMA channel to operate on. BdPtr is the BD to operate on. The next BD in the list relative to the BdPtr parameter. C-style signature: XEmacPs_Bd XEmacPs_BdRingNext(XEmacPs_BdRing RingPtr, XEmacPs_Bd *BdPtr)
Referenced by XEmacPs_BdRingFromHwRx, XEmacPs_BdRingFromHwTx, XEmacPs_BdRingToHw.
XEmacPs_BdRingPrev
Return the previous BD from BdPtr in the list.
RingPtr is the DMA channel to operate on. BdPtr is the BD to operate on The previous BD in the list relative to the BdPtr parameter. C-style signature: XEmacPs_Bd XEmacPs_BdRingPrev(XEmacPs_BdRing RingPtr, XEmacPs_Bd *BdPtr)
XEMACPS_HW_H
XEMACPS_MAX_MAC_ADDR
Maxmum number of mac address supported.
Referenced by XEmacPs_GetMacAddress, XEmacPs_SetMacAddress.
XEMACPS_MAX_TYPE_ID
Maxmum number of type id supported.
Referenced by XEmacPs_SetTypeIdCheck.
XEMACPS_BD_ALIGNMENT
Minimum buffer descriptor alignment on the local bus.
Referenced by EmacPsDmaIntrExample.
XEMACPS_RX_BUF_ALIGNMENT
Minimum buffer alignment when using options that impose alignment restrictions on the buffer data on the local bus.
XEMACPS_RX_BUF_SIZE
Specify the receive buffer size in bytes, 64, 128, ...
10240
Referenced by XEmacPs_ClearOptions, XEmacPs_Reset.
XEMACPS_RX_BUF_SIZE_JUMBO
XEMACPS_RX_BUF_UNIT
Number of receive buffer bytes as a unit, this is HW setup.
Referenced by XEmacPs_ClearOptions, XEmacPs_Reset, XEmacPs_SetOptions.
XEMACPS_MAX_RXBD
Size of RX buffer descriptor queues.
XEMACPS_MAX_TXBD
Size of TX buffer descriptor queues.
XEMACPS_MAX_HASH_BITS
Maximum value for hash bits.
2**6
Referenced by XEmacPs_DeleteHash, XEmacPs_SetHash.
XEMACPS_NWCTRL_OFFSET
Network Control reg.
Referenced by EmacPsUtilEnterLocalLoopback, XEmacPs_ClearOptions, XEmacPs_IntrHandler, XEmacPs_Reset, XEmacPs_ResetHw, XEmacPs_SendPausePacket, XEmacPs_SetOptions, XEmacPs_Start, XEmacPs_Stop.
XEMACPS_NWCFG_OFFSET
Network Config reg.
Referenced by XEmacPs_ClearOptions, XEmacPs_GetOperatingSpeed, XEmacPs_Reset, XEmacPs_ResetHw, XEmacPs_SetMdioDivisor, XEmacPs_SetOperatingSpeed, XEmacPs_SetOptions.
XEMACPS_NWSR_OFFSET
Network Status reg.
Referenced by XEmacPs_PhyRead, XEmacPs_PhyWrite.
XEMACPS_DMACR_OFFSET
DMA Control reg.
Referenced by XEmacPs_ClearOptions, XEmacPs_DMABLengthUpdate, XEmacPs_Reset, XEmacPs_SetOptions.
XEMACPS_TXSR_OFFSET
TX Status reg.
Referenced by XEmacPs_IntrHandler, XEmacPs_Reset, XEmacPs_ResetHw.
XEMACPS_RXQBASE_OFFSET
RX Q Base address reg.
Referenced by XEmacPs_GetQxOffset, XEmacPs_ResetHw, XEmacPs_Start.
XEMACPS_TXQBASE_OFFSET
TX Q Base address reg.
Referenced by XEmacPs_GetQxOffset, XEmacPs_ResetHw, XEmacPs_Start.
XEMACPS_RXSR_OFFSET
RX Status reg.
Referenced by XEmacPs_IntrHandler, XEmacPs_Reset, XEmacPs_ResetHw.
XEMACPS_ISR_OFFSET
Interrupt Status reg.
Referenced by XEmacPs_GetQxOffset, XEmacPs_IntrHandler, XEmacPs_Reset, XEmacPs_ResetHw, XEmacPs_Start.
XEMACPS_IER_OFFSET
Interrupt Enable reg.
XEMACPS_IDR_OFFSET
Interrupt Disable reg.
Referenced by XEmacPs_Reset, XEmacPs_ResetHw, XEmacPs_Stop.
XEMACPS_IMR_OFFSET
Interrupt Mask reg.
XEMACPS_PHYMNTNC_OFFSET
Phy Maintenance reg.
Referenced by XEmacPs_PhyRead, XEmacPs_PhyWrite.
XEMACPS_RXPAUSE_OFFSET
RX Pause Time reg.
XEMACPS_TXPAUSE_OFFSET
TX Pause Time reg.
XEMACPS_JUMBOMAXLEN_OFFSET
Jumbo max length reg.
Referenced by XEmacPs_SetOptions.
XEMACPS_HS_MAC_CONFIG_OFFSET
High Speed MAC config reg.
XEMACPS_RXWATERMARK_OFFSET
RX watermark reg.
XEMACPS_HASHL_OFFSET
Hash Low address reg.
Referenced by XEmacPs_ClearHash, XEmacPs_DeleteHash, XEmacPs_GetHash, XEmacPs_ResetHw, XEmacPs_SetHash.
XEMACPS_HASHH_OFFSET
Hash High address reg.
Referenced by XEmacPs_ClearHash, XEmacPs_DeleteHash, XEmacPs_GetHash, XEmacPs_ResetHw, XEmacPs_SetHash.
XEMACPS_LADDR1L_OFFSET
Specific1 addr low reg.
Referenced by XEmacPs_GetMacAddress, XEmacPs_SetMacAddress.
XEMACPS_LADDR1H_OFFSET
Specific1 addr high reg.
Referenced by XEmacPs_GetMacAddress, XEmacPs_SetMacAddress.
XEMACPS_LADDR2L_OFFSET
Specific2 addr low reg.
XEMACPS_LADDR2H_OFFSET
Specific2 addr high reg.
XEMACPS_LADDR3L_OFFSET
Specific3 addr low reg.
XEMACPS_LADDR3H_OFFSET
Specific3 addr high reg.
XEMACPS_LADDR4L_OFFSET
Specific4 addr low reg.
XEMACPS_LADDR4H_OFFSET
Specific4 addr high reg.
XEMACPS_MATCH1_OFFSET
Type ID1 Match reg.
Referenced by XEmacPs_SetTypeIdCheck.
XEMACPS_MATCH2_OFFSET
Type ID2 Match reg.
XEMACPS_MATCH3_OFFSET
Type ID3 Match reg.
XEMACPS_MATCH4_OFFSET
Type ID4 Match reg.
XEMACPS_STRETCH_OFFSET
IPG Stretch reg.
XEMACPS_OCTTXL_OFFSET
Octets transmitted Low reg.
Referenced by XEmacPs_Reset.
XEMACPS_OCTTXH_OFFSET
Octets transmitted High reg.
XEMACPS_TXCNT_OFFSET
Error-free Frmaes transmitted counter.
Referenced by main.
XEMACPS_TXBCCNT_OFFSET
Error-free Broadcast Frames counter.
XEMACPS_TXMCCNT_OFFSET
Error-free Multicast Frame counter.
XEMACPS_TXPAUSECNT_OFFSET
Pause Frames Transmitted Counter.
XEMACPS_TX64CNT_OFFSET
Error-free 64 byte Frames Transmitted counter.
XEMACPS_TX65CNT_OFFSET
Error-free 65-127 byte Frames Transmitted counter.
XEMACPS_TX128CNT_OFFSET
Error-free 128-255 byte Frames Transmitted counter.
XEMACPS_TX256CNT_OFFSET
Error-free 256-511 byte Frames transmitted counter.
XEMACPS_TX512CNT_OFFSET
Error-free 512-1023 byte Frames transmitted counter.
XEMACPS_TX1024CNT_OFFSET
Error-free 1024-1518 byte Frames transmitted counter.
XEMACPS_TX1519CNT_OFFSET
Error-free larger than 1519 byte Frames transmitted counter.
XEMACPS_TXURUNCNT_OFFSET
TX under run error counter.
XEMACPS_SNGLCOLLCNT_OFFSET
Single Collision Frame Counter.
XEMACPS_MULTICOLLCNT_OFFSET
Multiple Collision Frame Counter.
XEMACPS_EXCESSCOLLCNT_OFFSET
Excessive Collision Frame Counter.
XEMACPS_LATECOLLCNT_OFFSET
Late Collision Frame Counter.
XEMACPS_TXDEFERCNT_OFFSET
Deferred Transmission Frame Counter.
XEMACPS_TXCSENSECNT_OFFSET
Transmit Carrier Sense Error Counter.
XEMACPS_OCTRXL_OFFSET
Octets Received register Low.
XEMACPS_OCTRXH_OFFSET
Octets Received register High.
XEMACPS_RXCNT_OFFSET
Error-free Frames Received Counter.
Referenced by main.
XEMACPS_RXBROADCNT_OFFSET
Error-free Broadcast Frames Received Counter.
XEMACPS_RXMULTICNT_OFFSET
Error-free Multicast Frames Received Counter.
XEMACPS_RXPAUSECNT_OFFSET
Pause Frames Received Counter.
XEMACPS_RX64CNT_OFFSET
Error-free 64 byte Frames Received Counter.
XEMACPS_RX65CNT_OFFSET
Error-free 65-127 byte Frames Received Counter.
XEMACPS_RX128CNT_OFFSET
Error-free 128-255 byte Frames Received Counter.
XEMACPS_RX256CNT_OFFSET
Error-free 256-512 byte Frames Received Counter.
XEMACPS_RX512CNT_OFFSET
Error-free 512-1023 byte Frames Received Counter.
XEMACPS_RX1024CNT_OFFSET
Error-free 1024-1518 byte Frames Received Counter.
XEMACPS_RX1519CNT_OFFSET
Error-free 1519-max byte Frames Received Counter.
XEMACPS_RXUNDRCNT_OFFSET
Undersize Frames Received Counter.
XEMACPS_RXOVRCNT_OFFSET
Oversize Frames Received Counter.
XEMACPS_RXJABCNT_OFFSET
Jabbers Received Counter.
XEMACPS_RXFCSCNT_OFFSET
Frame Check Sequence Error Counter.
XEMACPS_RXLENGTHCNT_OFFSET
Length Field Error Counter.
XEMACPS_RXSYMBCNT_OFFSET
Symbol Error Counter.
XEMACPS_RXALIGNCNT_OFFSET
Alignment Error Counter.
XEMACPS_RXRESERRCNT_OFFSET
Receive Resource Error Counter.
XEMACPS_RXORCNT_OFFSET
Receive Overrun Counter.
XEMACPS_RXIPCCNT_OFFSET
IP header Checksum Error Counter.
XEMACPS_RXTCPCCNT_OFFSET
TCP Checksum Error Counter.
XEMACPS_RXUDPCCNT_OFFSET
UDP Checksum Error Counter.
XEMACPS_LAST_OFFSET
Last statistic counter offset, for clearing.
Referenced by XEmacPs_Reset.
XEMACPS_1588_SEC_OFFSET
1588 second counter
XEMACPS_1588_NANOSEC_OFFSET
1588 nanosecond counter
XEMACPS_1588_ADJ_OFFSET
1588 nanosecond adjustment counter
XEMACPS_1588_INC_OFFSET
1588 nanosecond increment counter
XEMACPS_PTP_TXSEC_OFFSET
1588 PTP transmit second counter
XEMACPS_PTP_TXNANOSEC_OFFSET
1588 PTP transmit nanosecond counter
XEMACPS_PTP_RXSEC_OFFSET
1588 PTP receive second counter
XEMACPS_PTP_RXNANOSEC_OFFSET
1588 PTP receive nanosecond counter
XEMACPS_PTPP_TXSEC_OFFSET
1588 PTP peer transmit second counter
XEMACPS_PTPP_TXNANOSEC_OFFSET
1588 PTP peer transmit nanosecond counter
XEMACPS_PTPP_RXSEC_OFFSET
1588 PTP peer receive second counter
XEMACPS_PTPP_RXNANOSEC_OFFSET
1588 PTP peer receive nanosecond counter
XEMACPS_PCS_CONTROL_OFFSET
XEMACPS_PCS_STATUS_OFFSET
XEMACPS_DCFG1_OFFSET
XEMACPS_DCFG6_OFFSET
XEMACPS_DCFG12_OFFSET
XEMACPS_INTQ1_STS_OFFSET
Interrupt Q1 Status reg.
Referenced by XEmacPs_GetQxOffset.
XEMACPS_INTQ2_STS_OFFSET
Interrupt Q2 Status reg.
Referenced by XEmacPs_GetQxOffset.
XEMACPS_INTQ3_STS_OFFSET
Interrupt Q3 Status reg.
Referenced by XEmacPs_GetQxOffset.
XEMACPS_TXQ1BASE_OFFSET
TX Q1 Base address reg.
Referenced by XEmacPs_GetQxOffset.
XEMACPS_TXQ2BASE_OFFSET
TX Q2 Base address reg.
Referenced by XEmacPs_GetQxOffset.
XEMACPS_TXQ3BASE_OFFSET
TX Q3 Base address reg.
Referenced by XEmacPs_GetQxOffset.
XEMACPS_RXQ1BASE_OFFSET
RX Q1 Base address reg.
Referenced by XEmacPs_GetQxOffset.
XEMACPS_RXQ2BASE_OFFSET
RX Q2 Base address reg.
Referenced by XEmacPs_GetQxOffset.
XEMACPS_RXQ3BASE_OFFSET
RX Q3 Base address reg.
Referenced by XEmacPs_GetQxOffset.
XEMACPS_DMA_RXQ1_BUFSIZE_OFFSET
RX Q1 DMA buffer size reg.
Referenced by XEmacPs_GetQxOffset.
XEMACPS_DMA_RXQ2_BUFSIZE_OFFSET
RX Q2 DMA buffer size reg.
Referenced by XEmacPs_GetQxOffset.
XEMACPS_DMA_RXQ3_BUFSIZE_OFFSET
RX Q3 DMA buffer size reg.
Referenced by XEmacPs_GetQxOffset.
XEMACPS_MSBBUF_TXQBASE_OFFSET
MSB Buffer TX Q Base reg.
Referenced by XEmacPs_SetQueuePtr.
XEMACPS_MSBBUF_RXQBASE_OFFSET
MSB Buffer RX Q Base reg.
Referenced by XEmacPs_SetQueuePtr.
XEMACPS_SCREEN_TYPE2_REG0
XEMACPS_INTQ1_IER_OFFSET
Interrupt Q1 Enable reg.
Referenced by XEmacPs_GetQxOffset.
XEMACPS_INTQ2_IER_OFFSET
Interrupt Q2 Enable reg.
Referenced by XEmacPs_GetQxOffset.
XEMACPS_INTQ3_IER_OFFSET
Interrupt Q3 Enable reg.
Referenced by XEmacPs_GetQxOffset.
XEMACPS_INTQ1_IDR_OFFSET
Interrupt Q1 Disable reg.
Referenced by XEmacPs_GetQxOffset.
XEMACPS_INTQ2_IDR_OFFSET
Interrupt Q2 Disable reg.
Referenced by XEmacPs_GetQxOffset.
XEMACPS_INTQ3_IDR_OFFSET
Interrupt Q3 Disable reg.
Referenced by XEmacPs_GetQxOffset.
XEMACPS_INTQ1_IMR_OFFSET
Interrupt Q1 Mask reg.
XEMACPS_INTQ2_IMR_OFFSET
Interrupt Q2 Mask reg.
XEMACPS_INTQ3_IMR_OFFSET
Interrupt Q3 Mask reg.
XEMACPS_USX_CONTROL_OFFSET
USX Control Reg.
XEMACPS_USX_STATUS_OFFSET
USX Control Reg.
XEMACPS_BD_ADDR_OFFSET
word 0/addr of BDs
Referenced by XEmacPs_BdRingCheck.
XEMACPS_BD_STAT_OFFSET
word 1/status of BDs
Referenced by XEmacPs_BdRingFromHwRx, XEmacPs_BdRingFromHwTx.
XEMACPS_BD_ADDR_HI_OFFSET
word 2/addr of BDs
XEMACPS_TXBUF_USED_MASK
Used bit.
Referenced by EmacPsDmaIntrExample, EmacPsDmaSingleFrameIntrExample, XEmacPs_BdRingFromHwTx.
XEMACPS_TXBUF_WRAP_MASK
Wrap bit, last descriptor.
Referenced by EmacPsDmaSingleFrameIntrExample.
XEMACPS_TXBUF_RETRY_MASK
Retry limit exceeded.
XEMACPS_TXBUF_URUN_MASK
Transmit underrun occurred.
XEMACPS_TXBUF_EXH_MASK
Buffers exhausted.
XEMACPS_TXBUF_TCP_MASK
Late collision.
XEMACPS_TXBUF_NOCRC_MASK
No CRC.
XEMACPS_TXBUF_LAST_MASK
Last buffer.
Referenced by XEmacPs_BdRingFromHwTx.
XEMACPS_TXBUF_LEN_MASK
Mask for length field.
XEMACPS_RXBUF_BCAST_MASK
Broadcast frame.
XEMACPS_RXBUF_MULTIHASH_MASK
Multicast hashed frame.
XEMACPS_RXBUF_UNIHASH_MASK
Unicast hashed frame.
XEMACPS_RXBUF_EXH_MASK
buffer exhausted
XEMACPS_RXBUF_AMATCH_MASK
Specific address matched.
XEMACPS_RXBUF_IDFOUND_MASK
Type ID matched.
XEMACPS_RXBUF_IDMATCH_MASK
ID matched mask.
XEMACPS_RXBUF_VLAN_MASK
VLAN tagged.
XEMACPS_RXBUF_PRI_MASK
Priority tagged.
XEMACPS_RXBUF_VPRI_MASK
Vlan priority.
XEMACPS_RXBUF_CFI_MASK
CFI frame.
XEMACPS_RXBUF_EOF_MASK
End of frame.
Referenced by XEmacPs_BdRingFromHwRx.
XEMACPS_RXBUF_SOF_MASK
Start of frame.
XEMACPS_RXBUF_LEN_MASK
Mask for length field.
Referenced by XEmacPs_ClearOptions, XEmacPs_Reset.
XEMACPS_RXBUF_LEN_JUMBO_MASK
Mask for jumbo length.
Referenced by XEmacPs_SetOptions.
XEMACPS_RXBUF_WRAP_MASK
Wrap bit, last BD.
Referenced by EmacPsDmaSingleFrameIntrExample.
XEMACPS_RXBUF_NEW_MASK
Used bit.
Referenced by EmacPsDmaSingleFrameIntrExample.
XEMACPS_RXBUF_ADD_MASK
Mask for address.
XEmacPs_In32
XEmacPs_Out32
XEmacPs_ReadReg
Read the given register.
BaseAddress is the base address of the device RegOffset is the register offset to be read The 32-bit value of the register C-style signature: u32 XEmacPs_ReadReg(u32 BaseAddress, u32 RegOffset)
Referenced by EmacPsUtilEnterLocalLoopback, main, XEmacPs_ClearOptions, XEmacPs_DeleteHash, XEmacPs_DMABLengthUpdate, XEmacPs_GetHash, XEmacPs_GetMacAddress, XEmacPs_GetOperatingSpeed, XEmacPs_IntrHandler, XEmacPs_IsHighSpeedPCS, XEmacPs_PhyRead, XEmacPs_PhyWrite, XEmacPs_Reset, XEmacPs_ResetHw, XEmacPs_SendPausePacket, XEmacPs_SetHash, XEmacPs_SetMacAddress, XEmacPs_SetMdioDivisor, XEmacPs_SetOperatingSpeed, XEmacPs_SetOptions, XEmacPs_Start, XEmacPs_Stop, XEmacPs_USXPCSGetState.
XEmacPs_WriteReg
Write the given register.
BaseAddress is the base address of the device RegOffset is the register offset to be written Data is the 32-bit value to write to the register None. C-style signature: void XEmacPs_WriteReg(u32 BaseAddress, u32 RegOffset, u32 Data)
Referenced by EmacPsDmaSingleFrameIntrExample, EmacPsUtilEnterLocalLoopback, XEmacPs_ClearHash, XEmacPs_ClearOptions, XEmacPs_DeleteHash, XEmacPs_DMABLengthUpdate, XEmacPs_IntrHandler, XEmacPs_PhyRead, XEmacPs_PhyWrite, XEmacPs_Reset, XEmacPs_ResetHw, XEmacPs_SendPausePacket, XEmacPs_SetHash, XEmacPs_SetMacAddress, XEmacPs_SetMdioDivisor, XEmacPs_SetOperatingSpeed, XEmacPs_SetOptions, XEmacPs_SetQueuePtr, XEmacPs_SetTypeIdCheck, XEmacPs_SetupPCS, XEmacPs_Start, XEmacPs_Stop.
XEMACPS_REG
XEMACPS_BIT
XEMACPS_BF
XEMACPS_BFEXT
XEMACPS_BFINS
POLL_TIMEOUT
XEMACPS_PCS_H