xemacps.c
void XEmacPs_StubHandler(void)
This is a stub for the asynchronous callbacks.
The stub is here in case the upper layer forgot to set the handler(s). On initialization, all handlers are set to this callback. It is considered an error for this handler to be invoked.
Referenced by XEmacPs_CfgInitialize.
LONG XEmacPs_CfgInitialize(XEmacPs *InstancePtr, XEmacPs_Config *CfgPtr, UINTPTR EffectiveAddress)
Initialize a specific XEmacPs instance/driver.
The initialization entails: Initialize fields of the XEmacPs instance structureReset hardware and apply default optionsConfigure the DMA channels The PHY is setup independently from the device. Use the MII or whatever other interface may be present for setup. InstancePtr is a pointer to the instance to be worked on. CfgPtr is the device configuration structure containing required hardware build data. EffectiveAddress is the base address of the device. If address translation is not utilized, this parameter can be passed in using CfgPtr->Config.BaseAddress to specify the physical base address. XST_SUCCESS if initialization was successful
References XEmacPs_Config::BaseAddress, XEmacPs_Config::GmiitoRgmiiConvPhyAddr, XEmacPs_Config::IntrId, XEmacPs_Config::IntrParent, XEmacPs_Config::IsCacheCoherent, XEmacPs_Config::MdioProducerBaseAddr, XEmacPs_Config::PhyAddr, XEmacPs_Config::PhyType, XEmacPs_Config::RefClk, XEmacPs_Config::S100MDiv0, XEmacPs_Config::S100MDiv1, XEmacPs_Config::S10MDiv0, XEmacPs_Config::S10MDiv1, XEmacPs_Config::S1GDiv0, XEmacPs_Config::S1GDiv1, XEmacPs_Reset, XEmacPs_StubHandler.
Referenced by EmacPsDmaIntrExample.
void XEmacPs_Start(XEmacPs *InstancePtr)
Start the Ethernet controller as follows:
Enable transmitter if XTE_TRANSMIT_ENABLE_OPTION is setEnable receiver if XTE_RECEIVER_ENABLE_OPTION is setStart the SG DMA send and receive channels and enable the device interrupt InstancePtr is a pointer to the instance to be worked on. N/A Hardware is configured with scatter-gather DMA, the driver expects to start the scatter-gather channels and expects that the user has previously set up the buffer descriptor lists. This function makes use of internal resources that are shared between the Start, Stop, and Set/ClearOptions functions. So if one task might be setting device options while another is trying to start the device, the user is required to provide protection of this shared data (typically using a semaphore).This function must not be preempted by an interrupt that may service the device.
References XEmacPs_Config::BaseAddress, XEmacPs_BdRing::BaseBdAddr, XEmacPs_Config::RefClk, XEmacPs_IntEnable, XEmacPs_IntQiEnable, XEMACPS_ISR_OFFSET, XEMACPS_IXR_ALL_MASK, XEMACPS_IXR_FRAMERX_MASK, XEMACPS_IXR_TXCOMPL_MASK, XEMACPS_IXR_USXGMII_MASK, XEMACPS_NWCTRL_OFFSET, XEMACPS_NWCTRL_RXEN_MASK, XEMACPS_NWCTRL_TXEN_MASK, XEmacPs_ReadReg, XEMACPS_RECEIVER_ENABLE_OPTION, XEMACPS_RXQBASE_OFFSET, XEMACPS_TRANSMITTER_ENABLE_OPTION, XEMACPS_TXQBASE_OFFSET, XEmacPs_WriteReg.
Referenced by EmacPsDmaSingleFrameIntrExample.
void XEmacPs_Stop(XEmacPs *InstancePtr)
Gracefully stop the Ethernet MAC as follows:
Disable all interrupts from this deviceStop DMA channelsDisable the transmitter and receiver Device options currently in effect are not changed.This function will disable all interrupts. Default interrupts settings that had been enabled will be restored when XEmacPs_Start() is called. InstancePtr is a pointer to the instance to be worked on. This function makes use of internal resources that are shared between the Start, Stop, SetOptions, and ClearOptions functions. So if one task might be setting device options while another is trying to start the device, the user is required to provide protection of this shared data (typically using a semaphore). Stopping the DMA channels causes this function to block until the DMA operation is complete.
References XEmacPs_Config::BaseAddress, XEmacPs_Config::RefClk, XEMACPS_IDR_OFFSET, XEMACPS_IXR_ALL_MASK, XEMACPS_NWCTRL_OFFSET, XEMACPS_NWCTRL_RXEN_MASK, XEMACPS_NWCTRL_TXEN_MASK, XEmacPs_ReadReg, XEmacPs_WriteReg.
Referenced by EmacPsDmaIntrExample, EmacPsDmaSingleFrameIntrExample, XEmacPs_Reset.
void XEmacPs_Reset(XEmacPs *InstancePtr)
Perform a graceful reset of the Ethernet MAC.
Resets the DMA channels, the transmitter, and the receiver.Steps to reset Stops transmit and receive channelsStops DMAConfigure transmit and receive buffer size to defaultClear transmit and receive status register and countersClear all interrupt sourcesClear phy (if there is any previously detected) addressClear MAC addresses (1-4) as well as Type IDs and hash value All options are placed in their default state. Any frames in the descriptor lists will remain in the lists. The side effect of doing this is that after a reset and following a restart of the device, frames were in the list before the reset may be transmitted or received.The upper layer software is responsible for re-configuring (if necessary) and restarting the MAC after the reset. Note also that driver statistics are not cleared on reset. It is up to the upper layer software to clear the statistics if needed.When a reset is required, the driver notifies the upper layer software of this need through the ErrorHandler callback and specific status codes. The upper layer software is responsible for calling this Reset function and then re-configuring the device. InstancePtr is a pointer to the instance to be worked on.
References XEmacPs_Config::BaseAddress, XEmacPs_Config::MdioProducerBaseAddr, XEmacPs_ClearHash, XEmacPs_ClearOptions, XEMACPS_DEFAULT_OPTIONS, XEMACPS_DMACR_ADDR_WIDTH_64, XEMACPS_DMACR_INCR16_AHB_BURST, XEMACPS_DMACR_OFFSET, XEMACPS_DMACR_RXBUF_MASK, XEMACPS_DMACR_RXBUF_SHIFT, XEMACPS_DMACR_RXSIZE_MASK, XEMACPS_DMACR_TXSIZE_MASK, XEmacPs_GetQxOffset, XEMACPS_IDR_OFFSET, XEmacPs_IsCommonMdioPresent, XEmacPs_IsHighSpeedPCS, XEMACPS_ISR_OFFSET, XEMACPS_IXR_ALL_MASK, XEMACPS_LAST_OFFSET, XEMACPS_NWCFG_1000_MASK, XEMACPS_NWCFG_100_MASK, XEMACPS_NWCFG_DWIDTH_128_MASK, XEMACPS_NWCFG_DWIDTH_64_MASK, XEMACPS_NWCFG_FDEN_MASK, XEMACPS_NWCFG_MDCCLKDIV_MASK, XEMACPS_NWCFG_OFFSET, XEMACPS_NWCFG_PCSSEL_MASK, XEMACPS_NWCFG_UCASTHASHEN_MASK, XEMACPS_NWCTRL_LOOPEN_MASK, XEMACPS_NWCTRL_MDEN_MASK, XEMACPS_NWCTRL_OFFSET, XEMACPS_NWCTRL_RXEN_MASK, XEMACPS_NWCTRL_STATCLR_MASK, XEMACPS_OCTTXL_OFFSET, XEmacPs_ReadReg, XEMACPS_RECEIVER_ENABLE_OPTION, XEMACPS_RECV, XEMACPS_RX_BUF_SIZE, XEMACPS_RX_BUF_UNIT, XEMACPS_RXBUF_LEN_MASK, XEMACPS_RXSR_OFFSET, XEMACPS_SEND, XEmacPs_SetMacAddress, XEmacPs_SetOptions, XEmacPs_SetQueuePtr, XEmacPs_SetTypeIdCheck, XEmacPs_SetupPCS, XEMACPS_SR_ALL_MASK, XEmacPs_Stop, XEMACPS_TRANSMITTER_ENABLE_OPTION, XEMACPS_TXSR_OFFSET, XEmacPs_WriteReg.
Referenced by XEmacPs_CfgInitialize.
void XEmacPs_SetQueuePtr(XEmacPs *InstancePtr, UINTPTR QPtr, u8 QueueNum, u16 Direction)
This function sets the start address of the transmit/receive buffer queue.
InstancePtr is a pointer to the instance to be worked on. QPtr is the address of the Queue to be written QueueNum is the Buffer Queue Index Direction indicates Transmit/Receive The buffer queue addresses has to be set before starting the transfer, so this function has to be called in prior to XEmacPs_Start()
References XEmacPs_Config::BaseAddress, XEmacPs_GetQxOffset, XEMACPS_MSBBUF_RXQBASE_OFFSET, XEMACPS_MSBBUF_TXQBASE_OFFSET, XEMACPS_SEND, XEmacPs_WriteReg.
Referenced by EmacPsDmaSingleFrameIntrExample, XEmacPs_Reset.