xemacps_example_util.c
PHY_DETECT_REG1
This function detects the PHY address by looking for successful MII status register contents.
The XEMACPS driver instance The address of the PHY (defaults to 32 if none detected) None.
PHY_DETECT_REG2
PHY_ID_MARVELL
PHY_ID_TI
PHY_REG0_RESET
This function sets the PHY to loopback mode.
The XEMACPS driver instance Speed is the loopback speed 10/100 Mbit. XST_SUCCESS if successful, else XST_FAILURE. None.
PHY_REG0_LOOPBACK
PHY_REG0_10
PHY_REG0_100
PHY_REG0_1000
PHY_REG21_10
PHY_REG21_100
PHY_REG21_1000
PHY_LOOPCR
PHY_REGCR
PHY_ADDAR
PHY_RGMIIDCTL
PHY_RGMIICTL
PHY_REGCR_ADDR
PHY_REGCR_DATA
PHY_TI_RGMII_ZCU102
PHY_TI_RGMII_VERSALEMU
XEmacPs EmacPsInstance
char EmacPsMAC[][]
u32 Platform
void EmacPsUtilFrameHdrFormatMAC(EthernetFrame *FramePtr, char *DestAddr)
Set the MAC addresses in the frame.
FramePtr is the pointer to the frame. DestAddr is the Destination MAC address. None. None.
Referenced by EmacPsDmaSingleFrameIntrExample.
void EmacPsUtilFrameHdrFormatType(EthernetFrame *FramePtr, u16 FrameType)
Set the frame type for the specified frame.
FramePtr is the pointer to the frame. FrameType is the Type to set in frame. None. None.
Referenced by EmacPsDmaSingleFrameIntrExample.
void EmacPsUtilFrameSetPayloadData(EthernetFrame *FramePtr, u32 PayloadSize)
This function places a pattern in the payload section of a frame.
The pattern is a 8 bit incrementing series of numbers starting with 0. Once the pattern reaches 256, then the pattern changes to a 16 bit incrementing pattern: 0, 1, 2, ... 254, 255, 00, 00, 00, 01, 00, 02, ... FramePtr is a pointer to the frame to change. PayloadSize is the number of bytes in the payload that will be set. None. None.
Referenced by EmacPsDmaSingleFrameIntrExample.
LONG EmacPsUtilFrameVerify(EthernetFrame *CheckFrame, EthernetFrame *ActualFrame)
This function verifies the frame data against a CheckFrame.
Validation occurs by comparing the ActualFrame to the header of the CheckFrame. If the headers match, then the payload of ActualFrame is verified for the same pattern Util_FrameSetPayloadData() generates. CheckFrame is a pointer to a frame containing the 14 byte header that should be present in the ActualFrame parameter. ActualFrame is a pointer to a frame to validate. XST_SUCCESS if successful, else XST_FAILURE. None.
Referenced by EmacPsDmaSingleFrameIntrExample.
void EmacPsUtilFrameMemClear(EthernetFrame *FramePtr)
This function sets all bytes of a frame to 0.
FramePtr is a pointer to the frame itself. None. None.
Referenced by EmacPsDmaSingleFrameIntrExample.
void EmacPsUtilstrncpy(char *Destination, const char *Source, u32 n)
This function copies data from source to destination for n bytes.
Destination is the targeted string to copy to. Source is the source string to copy from. n is number of bytes to be copied. This function is similar to strncpy(), however strncpy will stop either at null byte or n bytes is been copied. This function will copy n bytes without checking the content.
void EmacPsUtilEnterLocalLoopback(XEmacPs *EmacPsInstancePtr)
This function sets the emacps to loopback mode.
EmacPsInstancePtr is the XEmacPs driver instance. None.
References XEmacPs_Config::BaseAddress, XEMACPS_NWCTRL_LOOPEN_MASK, XEMACPS_NWCTRL_OFFSET, XEmacPs_ReadReg, XEmacPs_WriteReg.
u32 XEmacPsDetectPHY(XEmacPs *EmacPsInstancePtr)
LONG EmacPsUtilMarvellPhyLoopback(XEmacPs *EmacPsInstancePtr, u32 Speed, u32 PhyAddr)
LONG EmacPsUtilTiPhyLoopback(XEmacPs *EmacPsInstancePtr, u32 Speed, u32 PhyAddr)
void EmacpsDelay(u32 delay)
This function provides delays in seconds.
delay in seconds None. for microblaze the delay is not accurate and it need to tuned.
Referenced by EmacPsDmaIntrExample.
LONG EmacPsUtilEnterLoopback(XEmacPs *EmacPsInstancePtr, u32 Speed)
void EmacPsUtilErrorTrap(const char *Message)
This function is called by example code when an error is detected.
It can be set as a breakpoint with a debugger or it can be used to print out the given message if there is a UART or STDIO device. Message is the text explaining the error None None
Referenced by EmacPsDmaIntrExample, EmacPsDmaSingleFrameIntrExample, main.