xemacps_example.h
EMACPS_LOOPBACK_SPEED
EMACPS_LOOPBACK_SPEED_1G
EMACPS_LOOPBACK_SPEED_2_5G
EMACPS_LOOPBACK_SPEED_5G
EMACPS_LOOPBACK_SPEED_10G
EMACPS_PHY_DELAY_SEC
EMACPS_SLCR_DIV_MASK
CSU_VERSION
PLATFORM_MASK
PLATFORM_SILICON
VERSAL_VERSION
PLATFORM_MASK_VERSAL
PLATFORM_VERSALEMU
PLATFORM_VERSALSIL
typedef char EthernetFrame[XEMACPS_MAX_VLAN_FRAME_SIZE_JUMBO][XEMACPS_MAX_VLAN_FRAME_SIZE_JUMBO]
XEmacPs EmacPsInstance
char EmacPsMAC[][]
u32 Platform
void EmacPsUtilSetupUart(void)
void EmacPsUtilFrameHdrFormatMAC(EthernetFrame *FramePtr, char *DestAddr)
Set the MAC addresses in the frame.
FramePtr is the pointer to the frame. DestAddr is the Destination MAC address. None. None.
Referenced by EmacPsDmaSingleFrameIntrExample.
void EmacPsUtilFrameHdrFormatType(EthernetFrame *FramePtr, u16 FrameType)
Set the frame type for the specified frame.
FramePtr is the pointer to the frame. FrameType is the Type to set in frame. None. None.
Referenced by EmacPsDmaSingleFrameIntrExample.
void EmacPsUtilFrameSetPayloadData(EthernetFrame *FramePtr, u32 PayloadSize)
This function places a pattern in the payload section of a frame.
The pattern is a 8 bit incrementing series of numbers starting with 0. Once the pattern reaches 256, then the pattern changes to a 16 bit incrementing pattern: 0, 1, 2, ... 254, 255, 00, 00, 00, 01, 00, 02, ... FramePtr is a pointer to the frame to change. PayloadSize is the number of bytes in the payload that will be set. None. None.
Referenced by EmacPsDmaSingleFrameIntrExample.
LONG EmacPsUtilFrameVerify(EthernetFrame *CheckFrame, EthernetFrame *ActualFrame)
This function verifies the frame data against a CheckFrame.
Validation occurs by comparing the ActualFrame to the header of the CheckFrame. If the headers match, then the payload of ActualFrame is verified for the same pattern Util_FrameSetPayloadData() generates. CheckFrame is a pointer to a frame containing the 14 byte header that should be present in the ActualFrame parameter. ActualFrame is a pointer to a frame to validate. XST_SUCCESS if successful, else XST_FAILURE. None.
Referenced by EmacPsDmaSingleFrameIntrExample.
void EmacPsUtilFrameMemClear(EthernetFrame *FramePtr)
This function sets all bytes of a frame to 0.
FramePtr is a pointer to the frame itself. None. None.
Referenced by EmacPsDmaSingleFrameIntrExample.
LONG EmacPsUtilEnterLoopback(XEmacPs *XEmacPsInstancePtr, u32 Speed)
void EmacPsUtilstrncpy(char *Destination, const char *Source, u32 n)
This function copies data from source to destination for n bytes.
Destination is the targeted string to copy to. Source is the source string to copy from. n is number of bytes to be copied. This function is similar to strncpy(), however strncpy will stop either at null byte or n bytes is been copied. This function will copy n bytes without checking the content.
void EmacPsUtilErrorTrap(const char *Message)
This function is called by example code when an error is detected.
It can be set as a breakpoint with a debugger or it can be used to print out the given message if there is a UART or STDIO device. Message is the text explaining the error None None
Referenced by EmacPsDmaIntrExample, EmacPsDmaSingleFrameIntrExample, main.
void EmacpsDelay(u32 delay)
This function provides delays in seconds.
delay in seconds None. for microblaze the delay is not accurate and it need to tuned.
Referenced by EmacPsDmaIntrExample.