xemacps_example_intr_dma.c
EMACPS_BASEADDR
ZYNQ_EMACPS_0_BASEADDR
ZYNQ_EMACPS_1_BASEADDR
ZYNQMP_EMACPS_0_BASEADDR
ZYNQMP_EMACPS_1_BASEADDR
ZYNQMP_EMACPS_2_BASEADDR
ZYNQMP_EMACPS_3_BASEADDR
VERSAL_EMACPS_0_BASEADDR
VERSAL_EMACPS_1_BASEADDR
VERSAL_NET_EMACPS_0_BASEADDR
VERSAL_NET_EMACPS_1_BASEADDR
RXBD_CNT
TXBD_CNT
NUM_PACKETS
SLCR_LOCK_ADDR
SLCR_UNLOCK_ADDR
SLCR_GEM0_CLK_CTRL_ADDR
SLCR_GEM1_CLK_CTRL_ADDR
SLCR_LOCK_KEY_VALUE
SLCR_UNLOCK_KEY_VALUE
SLCR_ADDR_GEM_RST_CTRL
CRL_GEM_DIV_MASK
CRL_GEM_DIV0_SHIFT
CRL_GEM_DIV1_SHIFT
CRL_GEM_DIV_VERSAL_MASK
CRL_GEM_DIV_VERSAL_SHIFT
JUMBO_FRAME_SIZE
FRAME_HDR_SIZE
GEMVERSION_ZYNQMP
GEMVERSION_VERSAL
GEMVERSION_VERSAL_2VE_2VM_10GBE
QUEUE_DISABLE
RXBD_SPACE_BYTES
TXBD_SPACE_BYTES
FIRST_FRAGMENT_SIZE
EthernetFrame TxFrame
EthernetFrame RxFrame
u8 bd_space[0x100000][0x100000]
u8* RxBdSpacePtr
u8* TxBdSpacePtr
volatile s32 FramesRx
volatile s32 FramesTx
volatile s32 DeviceErrors
u32 TxFrameLength
XEmacPs_Bd BdTxTerminate
XEmacPs_Bd BdRxTerminate
u32 GemVersion
LONG EmacPsDmaIntrExample(XEmacPs *EmacPsInstancePtr, UINTPTR BaseAddress)
This function demonstrates the usage of the EmacPs driver by sending by sending and receiving frames in interrupt driven DMA mode.
EmacPsInstancePtr is a pointer to the instance of the EmacPs driver. BaseAddress contains the base address of the device XST_SUCCESS to indicate success, otherwise XST_FAILURE. None.
References XEmacPs_Config::BaseAddress, EmacpsDelay, EmacPsDmaSingleFrameIntrExample, EmacPsUtilErrorTrap, XEmacPs_Config::IntrId, XEmacPs_Config::IntrParent, XEMACPS_BD_ALIGNMENT, XEmacPs_BdClear, XEmacPs_BdRingClone, XEmacPs_BdRingCreate, XEmacPs_BdSetStatus, XEmacPs_CfgInitialize, XEmacPs_GetRxRing, XEmacPs_GetTxRing, XEmacPs_IntrHandler, XEmacPs_LookupConfig, XEMACPS_RECV, XEMACPS_SEND, XEmacPs_SetHandler, XEmacPs_SetMacAddress, XEmacPs_SetMdioDivisor, XEmacPs_SetOperatingSpeed, XEmacPs_SetOptions, XEmacPs_Stop, XEMACPS_TXBUF_USED_MASK, XEmacPsClkSetup.
Referenced by main.
LONG EmacPsDmaSingleFrameIntrExample(XEmacPs *EmacPsInstancePtr, u32 packet)
This function demonstrates the usage of the EMACPS by sending and receiving a single frame in DMA interrupt mode.
The source packet will be described by two descriptors. It will be received into a buffer described by a single descriptor. EmacPsInstancePtr is a pointer to the instance of the EmacPs driver. packet is the count of current transmitted/received packet XST_SUCCESS to indicate success, otherwise XST_FAILURE. None.
References XEmacPs_Config::BaseAddress, XEmacPs_BdRing::BaseBdAddr, EmacPsUtilErrorTrap, EmacPsUtilFrameHdrFormatMAC, EmacPsUtilFrameHdrFormatType, EmacPsUtilFrameMemClear, EmacPsUtilFrameSetPayloadData, EmacPsUtilFrameVerify, XEmacPs_Config::IsCacheCoherent, XEmacPs_BdClear, XEmacPs_BdClearTxUsed, XEmacPs_BdGetLength, XEmacPs_BdRingAlloc, XEmacPs_BdRingFree, XEmacPs_BdRingFromHwRx, XEmacPs_BdRingFromHwTx, XEmacPs_BdRingToHw, XEmacPs_BdSetAddressRx, XEmacPs_BdSetAddressTx, XEmacPs_BdSetLast, XEmacPs_BdSetLength, XEmacPs_BdSetStatus, XEMACPS_CMPA_ENABLE_MASK, XEmacPs_GetRxFrameSize, XEmacPs_GetRxRing, XEmacPs_GetTxRing, XEMACPS_RECV, XEMACPS_RXBUF_NEW_MASK, XEMACPS_RXBUF_WRAP_MASK, XEMACPS_SEND, XEmacPs_SetQueuePtr, XEmacPs_Start, XEmacPs_Stop, XEmacPs_Transmit, XEMACPS_TXBUF_USED_MASK, XEMACPS_TXBUF_WRAP_MASK, XEmacPs_WriteReg.
Referenced by EmacPsDmaIntrExample.
static void XEmacPsSendHandler(void *Callback)
This function setups the interrupt system so interrupts can occur for the EMACPS.
IntcInstancePtr is a pointer to the instance of the Intc driver. EmacPsInstancePtr is a pointer to the instance of the EmacPs driver. EmacPsIntrId is the Interrupt ID and is typically XPAR_<EMACPS_instance>_INTR value from xparameters.h. XST_SUCCESS if successful, otherwise XST_FAILURE. None. This the Transmit handler callback function and will increment a shared counter that can be shared by the main thread of operation. Callback is the pointer to the instance of the EmacPs device. None. None.
static void XEmacPsRecvHandler(void *Callback)
This is the Receive handler callback function and will increment a shared counter that can be shared by the main thread of operation.
Callback is a pointer to the instance of the EmacPs device. None. None.
static void XEmacPsErrorHandler(void *Callback, u8 Direction, u32 ErrorWord)
This is the Error handler callback function and this function increments the error counter so that the main thread knows the number of errors.
Callback is the callback function for the driver. This parameter is not used in this example. Direction is passed in from the driver specifying which direction error has occurred. ErrorWord is the status register value passed in. None. None.
static LONG EmacPsResetDevice(XEmacPs *EmacPsInstancePtr)
This function resets the device but preserves the options set by the user.
The descriptor list could be reinitialized with the same calls to XEmacPs_BdRingClone() as used in main(). Doing this is a matter of preference. In many cases, an OS may have resources tied up in the descriptors. Reinitializing in this case may bad for the OS since its resources may be permanently lost. EmacPsInstancePtr is a pointer to the instance of the EmacPs driver. XST_SUCCESS if successful, else XST_FAILURE. None.
void XEmacPsClkSetup(XEmacPs *EmacPsInstancePtr, u16 EmacPsIntrId)
This function sets up the clock divisors for 1000Mbps.
EmacPsInstancePtr is a pointer to the instance of the EmacPs driver. EmacPsIntrId is the Interrupt ID and is typically XPAR_<EMACPS_instance>_INTR value from xparameters.h. None. None.
References XEmacPs_Config::BaseAddress, XEmacPs_Config::S1GDiv0, XEmacPs_Config::S1GDiv1.
Referenced by EmacPsDmaIntrExample.
void XEmacPs_SetMdioDivisor(XEmacPs *InstancePtr, XEmacPs_MdcDiv Divisor)
Set the MDIO clock divisor.
Calculating the divisor: f[HOSTCLK] f[MDC] = ----------------- (1 + Divisor) * 2 where f[HOSTCLK] is the bus clock frequency in MHz, and f[MDC] is the MDIO clock frequency in MHz to the PHY. Typically, f[MDC] should not exceed 2.5 MHz. Some PHYs can tolerate faster speeds which means faster access. Here is the table to show values to generate MDC, 000 : divide pclk by 8 (pclk up to 20 MHz) 001 : divide pclk by 16 (pclk up to 40 MHz) 010 : divide pclk by 32 (pclk up to 80 MHz) 011 : divide pclk by 48 (pclk up to 120 MHz) 100 : divide pclk by 64 (pclk up to 160 MHz) 101 : divide pclk by 96 (pclk up to 240 MHz) 110 : divide pclk by 128 (pclk up to 320 MHz) 111 : divide pclk by 224 (pclk up to 540 MHz) InstancePtr is a pointer to the instance to be worked on. Divisor is the divisor to set. Range is 0b000 to 0b111.
References XEmacPs_Config::MdioProducerBaseAddr, XEmacPs_Config::BaseAddress, XEmacPs_ReadReg, XEMACPS_NWCFG_OFFSET, XEMACPS_NWCFG_MDCCLKDIV_MASK, XEMACPS_NWCFG_MDC_SHIFT_MASK, XEmacPs_WriteReg.
Referenced by EmacPsDmaIntrExample.
int main(void)
This is the main function for the EmacPs example.
This function is not included if the example is generated from the TestAppGen test tool.XST_SUCCESS to indicate success, otherwise XST_FAILURE. None.
References XEmacPs_Config::BaseAddress, EmacPsDmaIntrExample, EmacPsUtilErrorTrap, XEmacPs_ReadReg, XEMACPS_RXCNT_OFFSET, XEMACPS_TXCNT_OFFSET.