xemacps_bdring.h
XEMACPS_BDRING_H
XEmacPs_BdRingCntCalc
Use this macro at initialization time to determine how many BDs will fit in a BD list within the given memory constraints.
The results of this macro can be provided to XEmacPs_BdRingCreate(). Alignment specifies what byte alignment the BDs must fall on and must be a power of 2 to get an accurate calculation (32, 64, 128,...) Bytes is the number of bytes to be used to store BDs. Number of BDs that can fit in the given memory area C-style signature: u32 XEmacPs_BdRingCntCalc(u32 Alignment, u32 Bytes)
XEmacPs_BdRingMemCalc
Use this macro at initialization time to determine how many bytes of memory is required to contain a given number of BDs at a given alignment.
Alignment specifies what byte alignment the BDs must fall on. This parameter must be a power of 2 to get an accurate calculation (32, 64, 128,...) NumBd is the number of BDs to calculate memory size requirements for The number of bytes of memory required to create a BD list with the given memory constraints. C-style signature: u32 XEmacPs_BdRingMemCalc(u32 Alignment, u32 NumBd)
XEmacPs_BdRingGetCnt
Return the total number of BDs allocated by this channel with XEmacPs_BdRingCreate().
RingPtr is the DMA channel to operate on. The total number of BDs allocated for this channel. C-style signature: u32 XEmacPs_BdRingGetCnt(XEmacPs_BdRing* RingPtr)
XEmacPs_BdRingGetFreeCnt
Return the number of BDs allocatable with XEmacPs_BdRingAlloc() for pre- processing.
RingPtr is the DMA channel to operate on. The number of BDs currently allocatable. C-style signature: u32 XEmacPs_BdRingGetFreeCnt(XEmacPs_BdRing* RingPtr)
XEmacPs_BdRingNext
Return the next BD from BdPtr in a list.
RingPtr is the DMA channel to operate on. BdPtr is the BD to operate on. The next BD in the list relative to the BdPtr parameter. C-style signature: XEmacPs_Bd XEmacPs_BdRingNext(XEmacPs_BdRing RingPtr, XEmacPs_Bd *BdPtr)
Referenced by XEmacPs_BdRingFromHwRx, XEmacPs_BdRingFromHwTx, XEmacPs_BdRingToHw.
XEmacPs_BdRingPrev
Return the previous BD from BdPtr in the list.
RingPtr is the DMA channel to operate on. BdPtr is the BD to operate on The previous BD in the list relative to the BdPtr parameter. C-style signature: XEmacPs_Bd XEmacPs_BdRingPrev(XEmacPs_BdRing RingPtr, XEmacPs_Bd *BdPtr)
LONG XEmacPs_BdRingCreate(XEmacPs_BdRing *RingPtr, UINTPTR PhysAddr, UINTPTR VirtAddr, u32 Alignment, u32 BdCount)
Using a memory segment allocated by the caller, create and setup the BD list for the given DMA channel.
RingPtr is the instance to be worked on. PhysAddr is the physical base address of user memory region. VirtAddr is the virtual base address of the user memory region. If address translation is not being utilized, then VirtAddr should be equivalent to PhysAddr. Alignment governs the byte alignment of individual BDs. This function will enforce a minimum alignment of 4 bytes with no maximum as long as it is specified as a power of 2. BdCount is the number of BDs to setup in the user memory region. It is assumed the region is large enough to contain the BDs. XST_SUCCESS if initialization was successfulXST_NO_FEATURE if the provided instance is a non DMA type channel.XST_INVALID_PARAM under any of the following conditions: 1) PhysAddr and/or VirtAddr are not aligned to the given Alignment parameter. 2) Alignment parameter does not meet minimum requirements or is not a power of 2 value. 3) BdCount is 0.XST_DMA_SG_LIST_ERROR if the memory segment containing the list spans over address 0x00000000 in virtual address space. Make sure to pass in the right alignment value.
References XEmacPs_BdRing::AllCnt, XEmacPs_BdRing::BaseBdAddr, XEmacPs_BdRing::BdaRestart, XEmacPs_BdRing::FreeCnt, XEmacPs_BdRing::FreeHead, XEmacPs_BdRing::HighBdAddr, XEmacPs_BdRing::HwCnt, XEmacPs_BdRing::HwHead, XEmacPs_BdRing::HwTail, XEmacPs_BdRing::Length, XEmacPs_BdRing::PhysBaseAddr, XEmacPs_BdRing::PostCnt, XEmacPs_BdRing::PostHead, XEmacPs_BdRing::PreCnt, XEmacPs_BdRing::PreHead, XEmacPs_BdRing::RunState, XEmacPs_BdRing::Separation.
Referenced by EmacPsDmaIntrExample.
LONG XEmacPs_BdRingClone(XEmacPs_BdRing *RingPtr, XEmacPs_Bd *SrcBdPtr, u8 Direction)
Clone the given BD into every BD in the list.
every field of the source BD is replicated in every BD of the list.This function can be called only when all BDs are in the free group such as they are immediately after initialization with XEmacPs_BdRingCreate(). This prevents modification of BDs while they are in use by hardware or the user. RingPtr is the pointer of BD ring instance to be worked on. SrcBdPtr is the source BD template to be cloned into the list. This BD will be modified. Direction is either XEMACPS_SEND or XEMACPS_RECV that indicates which direction. XST_SUCCESS if the list was modified.XST_DMA_SG_NO_LIST if a list has not been created.XST_DMA_SG_LIST_ERROR if some of the BDs in this channel are under hardware or user control.XST_DEVICE_IS_STARTED if the DMA channel has not been stopped.
References XEmacPs_BdRing::AllCnt, XEmacPs_BdRing::BaseBdAddr, XEmacPs_BdRing::FreeCnt, XEmacPs_BdRing::RunState, XEmacPs_BdRing::Separation, XEMACPS_RECV, XEMACPS_SEND.
Referenced by EmacPsDmaIntrExample.
LONG XEmacPs_BdRingAlloc(XEmacPs_BdRing *RingPtr, u32 NumBd, XEmacPs_Bd **BdSetPtr)
Reserve locations in the BD list.
The set of returned BDs may be modified in preparation for future DMA transaction(s). Once the BDs are ready to be submitted to hardware, the user must call XEmacPs_BdRingToHw() in the same order which they were allocated here. Example: NumBd = 2, Status = XEmacPs_BdRingAlloc(MyRingPtr, NumBd, &MyBdSet), if (Status != XST_SUCCESS) { *Not enough BDs available for the request* } CurBd = MyBdSet, for (i=0; i<NumBd; i++) { * Prepare CurBd *..... * Onto next BD * CurBd = XEmacPs_BdRingNext(MyRingPtr, CurBd), } * Give list to hardware * Status = XEmacPs_BdRingToHw(MyRingPtr, NumBd, MyBdSet), A more advanced use of this function may allocate multiple sets of BDs. They must be allocated and given to hardware in the correct sequence: * Legal * XEmacPs_BdRingAlloc(MyRingPtr, NumBd1, &MySet1), XEmacPs_BdRingToHw(MyRingPtr, NumBd1, MySet1), * Legal * XEmacPs_BdRingAlloc(MyRingPtr, NumBd1, &MySet1), XEmacPs_BdRingAlloc(MyRingPtr, NumBd2, &MySet2), XEmacPs_BdRingToHw(MyRingPtr, NumBd1, MySet1), XEmacPs_BdRingToHw(MyRingPtr, NumBd2, MySet2), * Not legal * XEmacPs_BdRingAlloc(MyRingPtr, NumBd1, &MySet1), XEmacPs_BdRingAlloc(MyRingPtr, NumBd2, &MySet2), XEmacPs_BdRingToHw(MyRingPtr, NumBd2, MySet2), XEmacPs_BdRingToHw(MyRingPtr, NumBd1, MySet1), Use the API defined in xemacps_bd.h to modify individual BDs. Traversal of the BD set can be done using XEmacPs_BdRingNext() and XEmacPs_BdRingPrev(). RingPtr is a pointer to the BD ring instance to be worked on. NumBd is the number of BDs to allocate BdSetPtr is an output parameter, it points to the first BD available for modification. XST_SUCCESS if the requested number of BDs was returned in the BdSetPtr parameter.XST_FAILURE if there were not enough free BDs to satisfy the request. This function should not be preempted by another XEmacPs_Bd function call that modifies the BD space. It is the caller's responsibility to provide a mutual exclusion mechanism.Do not modify more BDs than the number requested with the NumBd parameter. Doing so will lead to data corruption and system instability.
References XEmacPs_BdRing::FreeCnt, XEmacPs_BdRing::FreeHead, XEmacPs_BdRing::PreCnt.
Referenced by EmacPsDmaSingleFrameIntrExample.
LONG XEmacPs_BdRingUnAlloc(XEmacPs_BdRing *RingPtr, u32 NumBd, XEmacPs_Bd *BdSetPtr)
Fully or partially undo an XEmacPs_BdRingAlloc() operation.
Use this function if all the BDs allocated by XEmacPs_BdRingAlloc() could not be transferred to hardware with XEmacPs_BdRingToHw().This function helps out in situations when an unrelated error occurs after BDs have been allocated but before they have been given to hardware. An example of this type of error would be an OS running out of resources.This function is not the same as XEmacPs_BdRingFree(). The Free function returns BDs to the free list after they have been processed by hardware, while UnAlloc returns them before being processed by hardware.There are two scenarios where this function can be used. Full UnAlloc or Partial UnAlloc. A Full UnAlloc means all the BDs Alloc'd will be returned: Status = XEmacPs_BdRingAlloc(MyRingPtr, 10, &BdPtr), ... if (Error) { Status = XEmacPs_BdRingUnAlloc(MyRingPtr, 10, &BdPtr), } A partial UnAlloc means some of the BDs Alloc'd will be returned: Status = XEmacPs_BdRingAlloc(MyRingPtr, 10, &BdPtr), BdsLeft = 10, CurBdPtr = BdPtr, while (BdsLeft) { if (Error) { Status = XEmacPs_BdRingUnAlloc(MyRingPtr, BdsLeft, CurBdPtr), } CurBdPtr = XEmacPs_BdRingNext(MyRingPtr, CurBdPtr), BdsLeft--, } A partial UnAlloc must include the last BD in the list that was Alloc'd. RingPtr is a pointer to the instance to be worked on. NumBd is the number of BDs to allocate BdSetPtr is an output parameter, it points to the first BD available for modification. XST_SUCCESS if the BDs were unallocated.XST_FAILURE if NumBd parameter was greater that the number of BDs in the preprocessing state. This function should not be preempted by another XEmacPs_Bd function call that modifies the BD space. It is the caller's responsibility to provide a mutual exclusion mechanism.
References XEmacPs_BdRing::FreeCnt, XEmacPs_BdRing::FreeHead, XEmacPs_BdRing::PreCnt.
LONG XEmacPs_BdRingToHw(XEmacPs_BdRing *RingPtr, u32 NumBd, XEmacPs_Bd *BdSetPtr)
Enqueue a set of BDs to hardware that were previously allocated by XEmacPs_BdRingAlloc().
Once this function returns, the argument BD set goes under hardware control. Any changes made to these BDs after this point will corrupt the BD list leading to data corruption and system instability.The set will be rejected if the last BD of the set does not mark the end of a packet (see XEmacPs_BdSetLast()). RingPtr is a pointer to the instance to be worked on. NumBd is the number of BDs in the set. BdSetPtr is the first BD of the set to commit to hardware. XST_SUCCESS if the set of BDs was accepted and enqueued to hardware.XST_FAILURE if the set of BDs was rejected because the last BD of the set did not have its "last" bit set.XST_DMA_SG_LIST_ERROR if this function was called out of sequence with XEmacPs_BdRingAlloc(). This function should not be preempted by another XEmacPs_Bd function call that modifies the BD space. It is the caller's responsibility to provide a mutual exclusion mechanism.
References XEmacPs_BdRing::HwCnt, XEmacPs_BdRing::HwTail, XEmacPs_BdRing::PreCnt, XEmacPs_BdRing::PreHead, XEmacPs_BdRingNext.
Referenced by EmacPsDmaSingleFrameIntrExample.
LONG XEmacPs_BdRingFree(XEmacPs_BdRing *RingPtr, u32 NumBd, XEmacPs_Bd *BdSetPtr)
Frees a set of BDs that had been previously retrieved with XEmacPs_BdRingFromHw().
RingPtr is a pointer to the instance to be worked on. NumBd is the number of BDs to free. BdSetPtr is the head of a list of BDs returned by XEmacPs_BdRingFromHw(). XST_SUCCESS if the set of BDs was freed.XST_DMA_SG_LIST_ERROR if this function was called out of sequence with XEmacPs_BdRingFromHw(). This function should not be preempted by another XEmacPs_Bd function call that modifies the BD space. It is the caller's responsibility to provide a mutual exclusion mechanism.
References XEmacPs_BdRing::FreeCnt, XEmacPs_BdRing::PostCnt, XEmacPs_BdRing::PostHead.
Referenced by EmacPsDmaSingleFrameIntrExample.
u32 XEmacPs_BdRingFromHwTx(XEmacPs_BdRing *RingPtr, u32 BdLimit, XEmacPs_Bd **BdSetPtr)
Returns a set of BD(s) that have been processed by hardware.
The returned BDs may be examined to determine the outcome of the DMA transaction(s). Once the BDs have been examined, the user must call XEmacPs_BdRingFree() in the same order which they were retrieved here. Example: NumBd = XEmacPs_BdRingFromHwTx(MyRingPtr, MaxBd, &MyBdSet), if (NumBd == 0) { * hardware has nothing ready for us yet* } CurBd = MyBdSet, for (i=0; i<NumBd; i++) { * Examine CurBd for post processing *..... * Onto next BD * CurBd = XEmacPs_BdRingNext(MyRingPtr, CurBd), } XEmacPs_BdRingFree(MyRingPtr, NumBd, MyBdSet), *Return list* } A more advanced use of this function may allocate multiple sets of BDs. They must be retrieved from hardware and freed in the correct sequence: * Legal * XEmacPs_BdRingFromHwTx(MyRingPtr, NumBd1, &MySet1), XEmacPs_BdRingFree(MyRingPtr, NumBd1, MySet1), * Legal * XEmacPs_BdRingFromHwTx(MyRingPtr, NumBd1, &MySet1), XEmacPs_BdRingFromHwTx(MyRingPtr, NumBd2, &MySet2), XEmacPs_BdRingFree(MyRingPtr, NumBd1, MySet1), XEmacPs_BdRingFree(MyRingPtr, NumBd2, MySet2), * Not legal * XEmacPs_BdRingFromHwTx(MyRingPtr, NumBd1, &MySet1), XEmacPs_BdRingFromHwTx(MyRingPtr, NumBd2, &MySet2), XEmacPs_BdRingFree(MyRingPtr, NumBd2, MySet2), XEmacPs_BdRingFree(MyRingPtr, NumBd1, MySet1), If hardware has only partially completed a packet spanning multiple BDs, then none of the BDs for that packet will be included in the results. RingPtr is a pointer to the instance to be worked on. BdLimit is the maximum number of BDs to return in the set. BdSetPtr is an output parameter, it points to the first BD available for examination. The number of BDs processed by hardware. A value of 0 indicates that no data is available. No more than BdLimit BDs will be returned. Treat BDs returned by this function as read-only.This function should not be preempted by another XEmacPs_Bd function call that modifies the BD space. It is the caller's responsibility to provide a mutual exclusion mechanism.
References XEmacPs_BdRing::HwCnt, XEmacPs_BdRing::HwHead, XEmacPs_BdRing::HwTail, XEmacPs_BdRing::PostCnt, XEMACPS_BD_STAT_OFFSET, XEmacPs_BdRead, XEmacPs_BdRingNext, XEMACPS_TXBUF_LAST_MASK, XEMACPS_TXBUF_USED_MASK.
Referenced by EmacPsDmaSingleFrameIntrExample.
u32 XEmacPs_BdRingFromHwRx(XEmacPs_BdRing *RingPtr, u32 BdLimit, XEmacPs_Bd **BdSetPtr)
Returns a set of BD(s) that have been processed by hardware.
The returned BDs may be examined to determine the outcome of the DMA transaction(s). Once the BDs have been examined, the user must call XEmacPs_BdRingFree() in the same order which they were retrieved here. Example: NumBd = XEmacPs_BdRingFromHwRx(MyRingPtr, MaxBd, &MyBdSet), if (NumBd == 0) { *hardware has nothing ready for us yet* } CurBd = MyBdSet, for (i=0; i<NumBd; i++) { * Examine CurBd for post processing *..... * Onto next BD * CurBd = XEmacPs_BdRingNext(MyRingPtr, CurBd), } XEmacPs_BdRingFree(MyRingPtr, NumBd, MyBdSet), * Return list * } A more advanced use of this function may allocate multiple sets of BDs. They must be retrieved from hardware and freed in the correct sequence: * Legal * XEmacPs_BdRingFromHwRx(MyRingPtr, NumBd1, &MySet1), XEmacPs_BdRingFree(MyRingPtr, NumBd1, MySet1), * Legal * XEmacPs_BdRingFromHwRx(MyRingPtr, NumBd1, &MySet1), XEmacPs_BdRingFromHwRx(MyRingPtr, NumBd2, &MySet2), XEmacPs_BdRingFree(MyRingPtr, NumBd1, MySet1), XEmacPs_BdRingFree(MyRingPtr, NumBd2, MySet2), * Not legal * XEmacPs_BdRingFromHwRx(MyRingPtr, NumBd1, &MySet1), XEmacPs_BdRingFromHwRx(MyRingPtr, NumBd2, &MySet2), XEmacPs_BdRingFree(MyRingPtr, NumBd2, MySet2), XEmacPs_BdRingFree(MyRingPtr, NumBd1, MySet1), If hardware has only partially completed a packet spanning multiple BDs, then none of the BDs for that packet will be included in the results. RingPtr is a pointer to the instance to be worked on. BdLimit is the maximum number of BDs to return in the set. BdSetPtr is an output parameter, it points to the first BD available for examination. The number of BDs processed by hardware. A value of 0 indicates that no data is available. No more than BdLimit BDs will be returned. Treat BDs returned by this function as read-only.This function should not be preempted by another XEmacPs_Bd function call that modifies the BD space. It is the caller's responsibility to provide a mutual exclusion mechanism.
References XEmacPs_BdRing::HwCnt, XEmacPs_BdRing::HwHead, XEmacPs_BdRing::HwTail, XEmacPs_BdRing::PostCnt, XEMACPS_BD_STAT_OFFSET, XEmacPs_BdIsRxNew, XEmacPs_BdRead, XEmacPs_BdRingNext, XEMACPS_RXBUF_EOF_MASK.
Referenced by EmacPsDmaSingleFrameIntrExample.
LONG XEmacPs_BdRingCheck(XEmacPs_BdRing *RingPtr, u8 Direction)
Check the internal data structures of the BD ring for the provided channel.
The following checks are made: Is the BD ring linked correctly in physical address space.Do the internal pointers point to BDs in the ring.Do the internal counters add up. The channel should be stopped prior to calling this function. RingPtr is a pointer to the instance to be worked on. Direction is either XEMACPS_SEND or XEMACPS_RECV that indicates which direction. XST_SUCCESS if the set of BDs was freed.XST_DMA_SG_NO_LIST if the list has not been created.XST_IS_STARTED if the channel is not stopped.XST_DMA_SG_LIST_ERROR if a problem is found with the internal data structures. If this value is returned, the channel should be reset to avoid data corruption or system instability. This function should not be preempted by another XEmacPs_Bd function call that modifies the BD space. It is the caller's responsibility to provide a mutual exclusion mechanism.
References XEmacPs_BdRing::AllCnt, XEmacPs_BdRing::BaseBdAddr, XEmacPs_BdRing::FreeCnt, XEmacPs_BdRing::FreeHead, XEmacPs_BdRing::HighBdAddr, XEmacPs_BdRing::HwCnt, XEmacPs_BdRing::HwHead, XEmacPs_BdRing::HwTail, XEmacPs_BdRing::PhysBaseAddr, XEmacPs_BdRing::PostCnt, XEmacPs_BdRing::PostHead, XEmacPs_BdRing::PreCnt, XEmacPs_BdRing::PreHead, XEmacPs_BdRing::RunState, XEmacPs_BdRing::Separation, XEMACPS_BD_ADDR_OFFSET, XEmacPs_BdIsRxWrap, XEmacPs_BdIsTxWrap, XEmacPs_BdRead, XEMACPS_RECV, XEMACPS_SEND.
void XEmacPs_BdRingPtrReset(XEmacPs_BdRing *RingPtr, void *virtaddrloc)
Reset BD ring head and tail pointers.
RingPtr is the instance to be worked on. virtaddrloc is the virtual base address of the user memory region. Should be called after XEmacPs_Stop()C-style signature: void XEmacPs_BdRingPtrReset(XEmacPs_BdRing * RingPtr, void *virtaddrloc)
References XEmacPs_BdRing::FreeHead, XEmacPs_BdRing::HwHead, XEmacPs_BdRing::HwTail, XEmacPs_BdRing::PostHead, XEmacPs_BdRing::PreHead.