xemacps.h
XEMACPS_PROMISC_OPTION
Accept all incoming packets.
This option defaults to disabled (cleared)
Referenced by XEmacPs_ClearOptions, XEmacPs_SetOptions.
XEMACPS_FRAME1536_OPTION
Frame larger than 1516 support for Tx & Rx.
This option defaults to disabled (cleared)
Referenced by XEmacPs_ClearOptions, XEmacPs_SetOptions.
XEMACPS_VLAN_OPTION
VLAN Rx & Tx frame support.
This option defaults to disabled (cleared)
Referenced by XEmacPs_ClearOptions, XEmacPs_SetOptions.
XEMACPS_FLOW_CONTROL_OPTION
Enable recognition of flow control frames on Rx This option defaults to enabled (set)
Referenced by XEmacPs_ClearOptions, XEmacPs_SetOptions.
XEMACPS_FCS_STRIP_OPTION
Strip FCS and PAD from incoming frames.
Note: PAD from VLAN frames is not stripped. This option defaults to enabled (set)
Referenced by XEmacPs_ClearOptions, XEmacPs_SetOptions.
XEMACPS_FCS_INSERT_OPTION
Generate FCS field and add PAD automatically for outgoing frames.
This option defaults to disabled (cleared)
XEMACPS_LENTYPE_ERR_OPTION
Enable Length/Type error checking for incoming frames.
When this option is set, the MAC will filter frames that have a mismatched type/length field and if XEMACPS_REPORT_RXERR_OPTION is set, the user is notified when these types of frames are encountered. When this option is cleared, the MAC will allow these types of frames to be received.This option defaults to disabled (cleared)
Referenced by XEmacPs_ClearOptions, XEmacPs_SetOptions.
XEMACPS_TRANSMITTER_ENABLE_OPTION
Enable the transmitter.
This option defaults to enabled (set)
Referenced by XEmacPs_ClearOptions, XEmacPs_Reset, XEmacPs_SetOptions, XEmacPs_Start.
XEMACPS_RECEIVER_ENABLE_OPTION
Enable the receiver This option defaults to enabled (set)
Referenced by XEmacPs_ClearOptions, XEmacPs_Reset, XEmacPs_SetOptions, XEmacPs_Start.
XEMACPS_BROADCAST_OPTION
Allow reception of the broadcast address This option defaults to enabled (set)
Referenced by XEmacPs_ClearOptions, XEmacPs_SetOptions.
XEMACPS_MULTICAST_OPTION
Allows reception of multicast addresses programmed into hash This option defaults to disabled (clear)
Referenced by XEmacPs_ClearOptions, XEmacPs_SetOptions.
XEMACPS_RX_CHKSUM_ENABLE_OPTION
Enable the RX checksum offload This option defaults to enabled (set)
Referenced by XEmacPs_ClearOptions, XEmacPs_SetOptions.
XEMACPS_TX_CHKSUM_ENABLE_OPTION
Enable the TX checksum offload This option defaults to enabled (set)
Referenced by XEmacPs_ClearOptions, XEmacPs_SetOptions.
XEMACPS_JUMBO_ENABLE_OPTION
XEMACPS_SGMII_ENABLE_OPTION
XEMACPS_GIGABIT_MODE_ENABLE_OPTION
XEMACPS_DEFAULT_OPTIONS
Default options set when device is initialized or reset.
Referenced by XEmacPs_Reset.
XEMACPS_HANDLER_DMASEND
XEMACPS_HANDLER_DMARECV
XEMACPS_HANDLER_ERROR
typedef void(* XEmacPs_Handler)(void *CallBackRef))(void *CallBackRef)
Callback invoked when frame(s) have been sent or received in interrupt driven DMA mode.
To set the send callback, invoke XEmacPs_SetHandler(). CallBackRef is user data assigned when the callback was set. See xemacps_hw.h for bitmasks definitions and the device hardware spec for further information on their meaning.
typedef void(* XEmacPs_ErrHandler)(void *CallBackRef, u8 Direction, u32 ErrorWord))(void *CallBackRef, u8 Direction, u32 ErrorWord)
Callback when an asynchronous error occurs.
To set this callback, invoke XEmacPs_SetHandler() with XEMACPS_HANDLER_ERROR in the HandlerType parameter. CallBackRef is user data assigned when the callback was set. Direction defines either receive or transmit error(s) has occurred. ErrorWord definition varies with Direction
XEMACPS_H
XEMACPS_DEVICE_NAME
XEMACPS_DEVICE_DESC
XEMACPS_MDIO_DIV_DFT
Default MDIO clock divisor.
XEMACPS_MAC_ADDR_SIZE
XEMACPS_MTU
XEMACPS_MTU_JUMBO
XEMACPS_HDR_SIZE
XEMACPS_HDR_VLAN_SIZE
XEMACPS_TRL_SIZE
XEMACPS_MAX_FRAME_SIZE
XEMACPS_MAX_VLAN_FRAME_SIZE
XEMACPS_MAX_VLAN_FRAME_SIZE_JUMBO
XEMACPS_SINGLE_BURST
XEMACPS_4BYTE_BURST
XEMACPS_8BYTE_BURST
XEMACPS_16BYTE_BURST
CLOCK_FREQ_1000MBPS
CLOCK_FREQ_100MBPS
CLOCK_FREQ_10MBPS
XEmacPs_GetTxRing
Retrieve the Tx ring object.
This object can be used in the various Ring API functions. InstancePtr is the DMA channel to operate on. TxBdRing attribute C-style signature: XEmacPs_BdRing XEmacPs_GetTxRing(XEmacPs *InstancePtr)
Referenced by EmacPsDmaIntrExample, EmacPsDmaSingleFrameIntrExample.
XEmacPs_GetRxRing
Retrieve the Rx ring object.
This object can be used in the various Ring API functions. InstancePtr is the DMA channel to operate on. RxBdRing attribute C-style signature: XEmacPs_BdRing XEmacPs_GetRxRing(XEmacPs *InstancePtr)
Referenced by EmacPsDmaIntrExample, EmacPsDmaSingleFrameIntrExample.
XEmacPs_IntEnable
Enable interrupts specified in Mask.
The corresponding interrupt for each bit set to 1 in Mask, will be enabled. InstancePtr is a pointer to the instance to be worked on. Mask contains a bit mask of interrupts to enable. The mask can be formed using a set of bitwise or'd values. The state of the transmitter and receiver are not modified by this function. C-style signature void XEmacPs_IntEnable(XEmacPs *InstancePtr, u32 Mask)
Referenced by XEmacPs_Start.
XEmacPs_IntDisable
Disable interrupts specified in Mask.
The corresponding interrupt for each bit set to 1 in Mask, will be enabled. InstancePtr is a pointer to the instance to be worked on. Mask contains a bit mask of interrupts to disable. The mask can be formed using a set of bitwise or'd values. The state of the transmitter and receiver are not modified by this function. C-style signature void XEmacPs_IntDisable(XEmacPs *InstancePtr, u32 Mask)
XEmacPs_IntQiEnable
Enable interrupts of queue Queue specified in Mask.
The corresponding interrupt for each bit set to 1 in Mask, will be enabled. InstancePtr is a pointer to the instance to be worked on. Indx of Queue, it should be from 1. Mask contains a bit mask of interrupts to enable. The mask can be formed using a set of bitwise or'd values. The state of the transmitter and receiver are not modified by this function. C-style signature void XEmacPs_IntQiEnable(XEmacPs *InstancePtr, u8 Queue, u32 Mask)
Referenced by XEmacPs_Start.
XEmacPs_IntQiDisable
Disable interrupts of queue Queue specified in Mask.
The corresponding interrupt for each bit set to 1 in Mask, will be enabled. InstancePtr is a pointer to the instance to be worked on. Index of Queue, it should be from 1. Mask contains a bit mask of interrupts to disable. The mask can be formed using a set of bitwise or'd values. The state of the transmitter and receiver are not modified by this function. C-style signature void XEmacPs_IntDisable(XEmacPs *InstancePtr, u8 Queue, u32 Mask)
XEmacPs_Transmit
This macro triggers transmit circuit to send data currently in TX buffer(s).
InstancePtr is a pointer to the XEmacPs instance to be worked on. Signature: void XEmacPs_Transmit(XEmacPs *InstancePtr)
Referenced by EmacPsDmaSingleFrameIntrExample.
XEmacPs_IsRxCsum
This macro determines if the device is configured with checksum offloading on the receive channel.
InstancePtr is a pointer to the XEmacPs instance to be worked on. Boolean TRUE if the device is configured with checksum offloading, or FALSE otherwise. Signature: u32 XEmacPs_IsRxCsum(XEmacPs *InstancePtr)
XEmacPs_IsTxCsum
This macro determines if the device is configured with checksum offloading on the transmit channel.
InstancePtr is a pointer to the XEmacPs instance to be worked on. Boolean TRUE if the device is configured with checksum offloading, or FALSE otherwise. Signature: u32 XEmacPs_IsTxCsum(XEmacPs *InstancePtr)
XEmacPs_SetRXWatermark
This macro sets RX watermark register.
InstancePtr is a pointer to the XEmacPs instance to be worked on. High is the non-zero RX high watermark value. When SRAM fill level is above this, a pause frame will be sent. Low is the non-zero RX low watermark value. When SRAM fill level is below this, a zero length pause frame will be sent IF the last pause frame sent was non-zero. None Signature: void XEmacPs_SetRXWatermark(XEmacPs *InstancePtr, u16 High, u16 Low)
XEmacPs_GetRXWatermark
This macro gets RX watermark register.
InstancePtr is a pointer to the XEmacPs instance to be worked on. RX watermark register value Signature: void XEmacPs_GetRXWatermark(XEmacPs *InstancePtr)
BIT
SET_BIT
GET_BIT
CLEAR_BIT
GENMASK
typedef struct XEmacPs_Instance XEmacPs
The XEmacPs driver instance data.
The user is required to allocate a structure of this type for every XEmacPs device in the system. A pointer to a structure of this type is then passed to the driver API functions.
static u8 get_num_set_bits(u32 n)
LONG XEmacPs_CfgInitialize(XEmacPs *InstancePtr, XEmacPs_Config *CfgPtr, UINTPTR EffectiveAddress)
Initialize a specific XEmacPs instance/driver.
The initialization entails: Initialize fields of the XEmacPs instance structureReset hardware and apply default optionsConfigure the DMA channels The PHY is setup independently from the device. Use the MII or whatever other interface may be present for setup. InstancePtr is a pointer to the instance to be worked on. CfgPtr is the device configuration structure containing required hardware build data. EffectiveAddress is the base address of the device. If address translation is not utilized, this parameter can be passed in using CfgPtr->Config.BaseAddress to specify the physical base address. XST_SUCCESS if initialization was successful
References XEmacPs_Config::BaseAddress, XEmacPs_Config::GmiitoRgmiiConvPhyAddr, XEmacPs_Config::IntrId, XEmacPs_Config::IntrParent, XEmacPs_Config::IsCacheCoherent, XEmacPs_Config::MdioProducerBaseAddr, XEmacPs_Config::PhyAddr, XEmacPs_Config::PhyType, XEmacPs_Config::RefClk, XEmacPs_Config::S100MDiv0, XEmacPs_Config::S100MDiv1, XEmacPs_Config::S10MDiv0, XEmacPs_Config::S10MDiv1, XEmacPs_Config::S1GDiv0, XEmacPs_Config::S1GDiv1, XEmacPs_Reset, XEmacPs_StubHandler.
Referenced by EmacPsDmaIntrExample.
void XEmacPs_Start(XEmacPs *InstancePtr)
Start the Ethernet controller as follows:
Enable transmitter if XTE_TRANSMIT_ENABLE_OPTION is setEnable receiver if XTE_RECEIVER_ENABLE_OPTION is setStart the SG DMA send and receive channels and enable the device interrupt InstancePtr is a pointer to the instance to be worked on. N/A Hardware is configured with scatter-gather DMA, the driver expects to start the scatter-gather channels and expects that the user has previously set up the buffer descriptor lists. This function makes use of internal resources that are shared between the Start, Stop, and Set/ClearOptions functions. So if one task might be setting device options while another is trying to start the device, the user is required to provide protection of this shared data (typically using a semaphore).This function must not be preempted by an interrupt that may service the device.
References XEmacPs_Config::BaseAddress, XEmacPs_BdRing::BaseBdAddr, XEmacPs_Config::RefClk, XEmacPs_IntEnable, XEmacPs_IntQiEnable, XEMACPS_ISR_OFFSET, XEMACPS_IXR_ALL_MASK, XEMACPS_IXR_FRAMERX_MASK, XEMACPS_IXR_TXCOMPL_MASK, XEMACPS_IXR_USXGMII_MASK, XEMACPS_NWCTRL_OFFSET, XEMACPS_NWCTRL_RXEN_MASK, XEMACPS_NWCTRL_TXEN_MASK, XEmacPs_ReadReg, XEMACPS_RECEIVER_ENABLE_OPTION, XEMACPS_RXQBASE_OFFSET, XEMACPS_TRANSMITTER_ENABLE_OPTION, XEMACPS_TXQBASE_OFFSET, XEmacPs_WriteReg.
Referenced by EmacPsDmaSingleFrameIntrExample.
void XEmacPs_Stop(XEmacPs *InstancePtr)
Gracefully stop the Ethernet MAC as follows:
Disable all interrupts from this deviceStop DMA channelsDisable the transmitter and receiver Device options currently in effect are not changed.This function will disable all interrupts. Default interrupts settings that had been enabled will be restored when XEmacPs_Start() is called. InstancePtr is a pointer to the instance to be worked on. This function makes use of internal resources that are shared between the Start, Stop, SetOptions, and ClearOptions functions. So if one task might be setting device options while another is trying to start the device, the user is required to provide protection of this shared data (typically using a semaphore). Stopping the DMA channels causes this function to block until the DMA operation is complete.
References XEmacPs_Config::BaseAddress, XEmacPs_Config::RefClk, XEMACPS_IDR_OFFSET, XEMACPS_IXR_ALL_MASK, XEMACPS_NWCTRL_OFFSET, XEMACPS_NWCTRL_RXEN_MASK, XEMACPS_NWCTRL_TXEN_MASK, XEmacPs_ReadReg, XEmacPs_WriteReg.
Referenced by EmacPsDmaIntrExample, EmacPsDmaSingleFrameIntrExample, XEmacPs_Reset.
void XEmacPs_Reset(XEmacPs *InstancePtr)
Perform a graceful reset of the Ethernet MAC.
Resets the DMA channels, the transmitter, and the receiver.Steps to reset Stops transmit and receive channelsStops DMAConfigure transmit and receive buffer size to defaultClear transmit and receive status register and countersClear all interrupt sourcesClear phy (if there is any previously detected) addressClear MAC addresses (1-4) as well as Type IDs and hash value All options are placed in their default state. Any frames in the descriptor lists will remain in the lists. The side effect of doing this is that after a reset and following a restart of the device, frames were in the list before the reset may be transmitted or received.The upper layer software is responsible for re-configuring (if necessary) and restarting the MAC after the reset. Note also that driver statistics are not cleared on reset. It is up to the upper layer software to clear the statistics if needed.When a reset is required, the driver notifies the upper layer software of this need through the ErrorHandler callback and specific status codes. The upper layer software is responsible for calling this Reset function and then re-configuring the device. InstancePtr is a pointer to the instance to be worked on.
References XEmacPs_Config::BaseAddress, XEmacPs_Config::MdioProducerBaseAddr, XEmacPs_ClearHash, XEmacPs_ClearOptions, XEMACPS_DEFAULT_OPTIONS, XEMACPS_DMACR_ADDR_WIDTH_64, XEMACPS_DMACR_INCR16_AHB_BURST, XEMACPS_DMACR_OFFSET, XEMACPS_DMACR_RXBUF_MASK, XEMACPS_DMACR_RXBUF_SHIFT, XEMACPS_DMACR_RXSIZE_MASK, XEMACPS_DMACR_TXSIZE_MASK, XEmacPs_GetQxOffset, XEMACPS_IDR_OFFSET, XEmacPs_IsCommonMdioPresent, XEmacPs_IsHighSpeedPCS, XEMACPS_ISR_OFFSET, XEMACPS_IXR_ALL_MASK, XEMACPS_LAST_OFFSET, XEMACPS_NWCFG_1000_MASK, XEMACPS_NWCFG_100_MASK, XEMACPS_NWCFG_DWIDTH_128_MASK, XEMACPS_NWCFG_DWIDTH_64_MASK, XEMACPS_NWCFG_FDEN_MASK, XEMACPS_NWCFG_MDCCLKDIV_MASK, XEMACPS_NWCFG_OFFSET, XEMACPS_NWCFG_PCSSEL_MASK, XEMACPS_NWCFG_UCASTHASHEN_MASK, XEMACPS_NWCTRL_LOOPEN_MASK, XEMACPS_NWCTRL_MDEN_MASK, XEMACPS_NWCTRL_OFFSET, XEMACPS_NWCTRL_RXEN_MASK, XEMACPS_NWCTRL_STATCLR_MASK, XEMACPS_OCTTXL_OFFSET, XEmacPs_ReadReg, XEMACPS_RECEIVER_ENABLE_OPTION, XEMACPS_RECV, XEMACPS_RX_BUF_SIZE, XEMACPS_RX_BUF_UNIT, XEMACPS_RXBUF_LEN_MASK, XEMACPS_RXSR_OFFSET, XEMACPS_SEND, XEmacPs_SetMacAddress, XEmacPs_SetOptions, XEmacPs_SetQueuePtr, XEmacPs_SetTypeIdCheck, XEmacPs_SetupPCS, XEMACPS_SR_ALL_MASK, XEmacPs_Stop, XEMACPS_TRANSMITTER_ENABLE_OPTION, XEMACPS_TXSR_OFFSET, XEmacPs_WriteReg.
Referenced by XEmacPs_CfgInitialize.
void XEmacPs_SetQueuePtr(XEmacPs *InstancePtr, UINTPTR QPtr, u8 QueueNum, u16 Direction)
This function sets the start address of the transmit/receive buffer queue.
InstancePtr is a pointer to the instance to be worked on. QPtr is the address of the Queue to be written QueueNum is the Buffer Queue Index Direction indicates Transmit/Receive The buffer queue addresses has to be set before starting the transfer, so this function has to be called in prior to XEmacPs_Start()
References XEmacPs_Config::BaseAddress, XEmacPs_GetQxOffset, XEMACPS_MSBBUF_RXQBASE_OFFSET, XEMACPS_MSBBUF_TXQBASE_OFFSET, XEMACPS_SEND, XEmacPs_WriteReg.
Referenced by EmacPsDmaSingleFrameIntrExample, XEmacPs_Reset.
XEmacPs_Config * XEmacPs_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
A table contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration table entry corresponding to the given device ID/BaseAddress, or NULL if no match is found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XEmacPs_Config::Name.
Referenced by EmacPsDmaIntrExample.
LONG XEmacPs_SetHandler(XEmacPs *InstancePtr, u32 HandlerType, void *FuncPointer, void *CallBackRef)
Install an asynchronous handler function for the given HandlerType:
InstancePtr is a pointer to the instance to be worked on. HandlerType indicates what interrupt handler type is. XEMACPS_HANDLER_DMASEND, XEMACPS_HANDLER_DMARECV and XEMACPS_HANDLER_ERROR. FuncPointer is the pointer to the callback function CallBackRef is the upper layer callback reference passed back when when the callback function is invoked. None.There is no assert on the CallBackRef since the driver doesn't know what it is.
Referenced by EmacPsDmaIntrExample.
void XEmacPs_IntrHandler(void *XEmacPsPtr)
Master interrupt handler for EMAC driver.
This routine will query the status of the device, bump statistics, and invoke user callbacks.This routine must be connected to an interrupt controller using OS/BSP specific methods. XEmacPsPtr is a pointer to the XEMACPS instance that has caused the interrupt.
References XEmacPs_Config::BaseAddress, XEmacPs_GetQxOffset, XEMACPS_ISR_OFFSET, XEMACPS_IXR_RXUSED_MASK, XEMACPS_IXR_TXCOMPL_MASK, XEMACPS_NWCTRL_FLUSH_DPRAM_MASK, XEMACPS_NWCTRL_OFFSET, XEmacPs_ReadReg, XEMACPS_RECV, XEMACPS_RXSR_BUFFNA_MASK, XEMACPS_RXSR_FRAMERX_MASK, XEMACPS_RXSR_OFFSET, XEMACPS_SEND, XEMACPS_TXSR_OFFSET, XEMACPS_TXSR_TXCOMPL_MASK, XEMACPS_TXSR_USEDREAD_MASK, XEmacPs_WriteReg.
Referenced by EmacPsDmaIntrExample.
LONG XEmacPs_SetOptions(XEmacPs *InstancePtr, u32 Options)
Set options for the driver/device.
The driver should be stopped with XEmacPs_Stop() before changing options. InstancePtr is a pointer to the instance to be worked on. Options are the options to set. Multiple options can be set by OR'ing XTE_*_OPTIONS constants together. Options not specified are not affected. XST_SUCCESS if the options were set successfullyXST_DEVICE_IS_STARTED if the device has not yet been stopped See xemacps.h for a description of the available options.
References XEmacPs_Config::BaseAddress, XEMACPS_BROADCAST_OPTION, XEMACPS_DMACR_OFFSET, XEMACPS_DMACR_RXBUF_MASK, XEMACPS_DMACR_RXBUF_SHIFT, XEMACPS_DMACR_TCPCKSUM_MASK, XEMACPS_FCS_STRIP_OPTION, XEMACPS_FLOW_CONTROL_OPTION, XEMACPS_FRAME1536_OPTION, XEMACPS_JUMBOMAXLEN_OFFSET, XEMACPS_LENTYPE_ERR_OPTION, XEMACPS_MULTICAST_OPTION, XEMACPS_NWCFG_1000_MASK, XEMACPS_NWCFG_1536RXEN_MASK, XEMACPS_NWCFG_BCASTDI_MASK, XEMACPS_NWCFG_COPYALLEN_MASK, XEMACPS_NWCFG_FCSREM_MASK, XEMACPS_NWCFG_JUMBO_MASK, XEMACPS_NWCFG_LENERRDSCRD_MASK, XEMACPS_NWCFG_MCASTHASHEN_MASK, XEMACPS_NWCFG_NVLANDISC_MASK, XEMACPS_NWCFG_OFFSET, XEMACPS_NWCFG_PAUSEEN_MASK, XEMACPS_NWCFG_PCSSEL_MASK, XEMACPS_NWCFG_RXCHKSUMEN_MASK, XEMACPS_NWCFG_SGMIIEN_MASK, XEMACPS_NWCTRL_OFFSET, XEMACPS_NWCTRL_RXEN_MASK, XEMACPS_NWCTRL_TXEN_MASK, XEMACPS_PROMISC_OPTION, XEmacPs_ReadReg, XEMACPS_RECEIVER_ENABLE_OPTION, XEMACPS_RX_BUF_UNIT, XEMACPS_RX_CHKSUM_ENABLE_OPTION, XEMACPS_RXBUF_LEN_JUMBO_MASK, XEMACPS_TRANSMITTER_ENABLE_OPTION, XEMACPS_TX_CHKSUM_ENABLE_OPTION, XEMACPS_VLAN_OPTION, XEmacPs_WriteReg.
Referenced by EmacPsDmaIntrExample, XEmacPs_Reset.
LONG XEmacPs_ClearOptions(XEmacPs *InstancePtr, u32 Options)
Clear options for the driver/device.
InstancePtr is a pointer to the instance to be worked on. Options are the options to clear. Multiple options can be cleared by OR'ing XEMACPS_*_OPTIONS constants together. Options not specified are not affected. XST_SUCCESS if the options were set successfullyXST_DEVICE_IS_STARTED if the device has not yet been stopped See xemacps.h for a description of the available options.
References XEmacPs_Config::BaseAddress, XEMACPS_BROADCAST_OPTION, XEMACPS_DMACR_OFFSET, XEMACPS_DMACR_RXBUF_MASK, XEMACPS_DMACR_RXBUF_SHIFT, XEMACPS_DMACR_TCPCKSUM_MASK, XEMACPS_FCS_STRIP_OPTION, XEMACPS_FLOW_CONTROL_OPTION, XEMACPS_FRAME1536_OPTION, XEMACPS_LENTYPE_ERR_OPTION, XEMACPS_MULTICAST_OPTION, XEMACPS_NWCFG_1000_MASK, XEMACPS_NWCFG_1536RXEN_MASK, XEMACPS_NWCFG_BCASTDI_MASK, XEMACPS_NWCFG_COPYALLEN_MASK, XEMACPS_NWCFG_FCSREM_MASK, XEMACPS_NWCFG_JUMBO_MASK, XEMACPS_NWCFG_LENERRDSCRD_MASK, XEMACPS_NWCFG_MCASTHASHEN_MASK, XEMACPS_NWCFG_NVLANDISC_MASK, XEMACPS_NWCFG_OFFSET, XEMACPS_NWCFG_PAUSEEN_MASK, XEMACPS_NWCFG_PCSSEL_MASK, XEMACPS_NWCFG_RXCHKSUMEN_MASK, XEMACPS_NWCFG_SGMIIEN_MASK, XEMACPS_NWCTRL_OFFSET, XEMACPS_NWCTRL_RXEN_MASK, XEMACPS_NWCTRL_TXEN_MASK, XEMACPS_PROMISC_OPTION, XEmacPs_ReadReg, XEMACPS_RECEIVER_ENABLE_OPTION, XEMACPS_RX_BUF_SIZE, XEMACPS_RX_BUF_UNIT, XEMACPS_RX_CHKSUM_ENABLE_OPTION, XEMACPS_RXBUF_LEN_MASK, XEMACPS_TRANSMITTER_ENABLE_OPTION, XEMACPS_TX_CHKSUM_ENABLE_OPTION, XEMACPS_VLAN_OPTION, XEmacPs_WriteReg.
Referenced by XEmacPs_Reset.
u32 XEmacPs_GetOptions(XEmacPs *InstancePtr)
Get current option settings.
InstancePtr is a pointer to the instance to be worked on. A bitmask of XTE_*_OPTION constants. Any bit set to 1 is to be interpreted as a set option. See xemacps.h for a description of the available options.
LONG XEmacPs_SetMacAddress(XEmacPs *InstancePtr, void *AddressPtr, u8 Index)
Set the MAC address for this driver/device.
The address is a 48-bit value. The device must be stopped before calling this function. InstancePtr is a pointer to the instance to be worked on. AddressPtr is a pointer to a 6-byte MAC address. Index is a index to which MAC (1-4) address. XST_SUCCESS if the MAC address was set successfullyXST_DEVICE_IS_STARTED if the device has not yet been stopped
References XEmacPs_Config::BaseAddress, XEMACPS_LADDR1H_OFFSET, XEMACPS_LADDR1L_OFFSET, XEMACPS_LADDR_MACH_MASK, XEMACPS_MAX_MAC_ADDR, XEmacPs_ReadReg, XEmacPs_WriteReg.
Referenced by EmacPsDmaIntrExample, XEmacPs_Reset.
LONG XEmacPs_DeleteHash(XEmacPs *InstancePtr, void *AddressPtr)
Delete 48-bit MAC addresses in hash table.
The device must be stopped before calling this function. InstancePtr is a pointer to the instance to be worked on. AddressPtr is a pointer to a 6-byte MAC address. XST_SUCCESS if the HASH MAC address was deleted successfullyXST_DEVICE_IS_STARTED if the device has not yet been stoppedXST_INVALID_PARAM if the HASH MAC address passed in does not meet requirement after calculation Having Aptr be unsigned type prevents the following operations from sign extending.
References XEmacPs_Config::BaseAddress, XEMACPS_HASHH_OFFSET, XEMACPS_HASHL_OFFSET, XEMACPS_MAX_HASH_BITS, XEmacPs_ReadReg, XEmacPs_WriteReg.
void XEmacPs_GetMacAddress(XEmacPs *InstancePtr, void *AddressPtr, u8 Index)
Get the MAC address for this driver/device.
InstancePtr is a pointer to the instance to be worked on. AddressPtr is an output parameter, and is a pointer to a buffer into which the current MAC address will be copied. Index is a index to which MAC (1-4) address.
References XEmacPs_Config::BaseAddress, XEMACPS_LADDR1H_OFFSET, XEMACPS_LADDR1L_OFFSET, XEMACPS_MAX_MAC_ADDR, XEmacPs_ReadReg.
LONG XEmacPs_SetHash(XEmacPs *InstancePtr, void *AddressPtr)
Set 48-bit MAC addresses in hash table.
The device must be stopped before calling this function.The hash address register is 64 bits long and takes up two locations in the memory map. The least significant bits are stored in hash register bottom and the most significant bits in hash register top.The unicast hash enable and the multicast hash enable bits in the network configuration register enable the reception of hash matched frames. The destination address is reduced to a 6 bit index into the 64 bit hash register using the following hash function. The hash function is an XOR of every sixth bit of the destination address. hash_index[05] = da[05]^da[11]^da[17]^da[23]^da[29]^da[35]^da[41]^da[47] hash_index[04] = da[04]^da[10]^da[16]^da[22]^da[28]^da[34]^da[40]^da[46] hash_index[03] = da[03]^da[09]^da[15]^da[21]^da[27]^da[33]^da[39]^da[45] hash_index[02] = da[02]^da[08]^da[14]^da[20]^da[26]^da[32]^da[38]^da[44] hash_index[01] = da[01]^da[07]^da[13]^da[19]^da[25]^da[31]^da[37]^da[43] hash_index[00] = da[00]^da[06]^da[12]^da[18]^da[24]^da[30]^da[36]^da[42] da[0] represents the least significant bit of the first byte received, that is, the multicast/unicast indicator, and da[47] represents the most significant bit of the last byte received.If the hash index points to a bit that is set in the hash register then the frame will be matched according to whether the frame is multicast or unicast.A multicast match will be signaled if the multicast hash enable bit is set, da[0] is logic 1 and the hash index points to a bit set in the hash register.A unicast match will be signaled if the unicast hash enable bit is set, da[0] is logic 0 and the hash index points to a bit set in the hash register.To receive all multicast frames, the hash register should be set with all ones and the multicast hash enable bit should be set in the network configuration register. InstancePtr is a pointer to the instance to be worked on. AddressPtr is a pointer to a 6-byte MAC address. XST_SUCCESS if the HASH MAC address was set successfullyXST_DEVICE_IS_STARTED if the device has not yet been stoppedXST_INVALID_PARAM if the HASH MAC address passed in does not meet requirement after calculation Having Aptr be unsigned type prevents the following operations from sign extending.
References XEmacPs_Config::BaseAddress, XEMACPS_HASHH_OFFSET, XEMACPS_HASHL_OFFSET, XEMACPS_MAX_HASH_BITS, XEmacPs_ReadReg, XEmacPs_WriteReg.
void XEmacPs_ClearHash(XEmacPs *InstancePtr)
Clear the Hash registers for the mac address pointed by AddressPtr.
InstancePtr is a pointer to the instance to be worked on.
References XEmacPs_Config::BaseAddress, XEMACPS_HASHH_OFFSET, XEMACPS_HASHL_OFFSET, XEmacPs_WriteReg.
Referenced by XEmacPs_Reset.
void XEmacPs_GetHash(XEmacPs *InstancePtr, void *AddressPtr)
Get the Hash address for this driver/device.
InstancePtr is a pointer to the instance to be worked on. AddressPtr is an output parameter, and is a pointer to a buffer into which the current HASH MAC address will be copied.
References XEmacPs_Config::BaseAddress, XEMACPS_HASHH_OFFSET, XEMACPS_HASHL_OFFSET, XEmacPs_ReadReg.
void XEmacPs_SetMdioDivisor(XEmacPs *InstancePtr, XEmacPs_MdcDiv Divisor)
Set the MDIO clock divisor.
Calculating the divisor: f[HOSTCLK] f[MDC] = ----------------- (1 + Divisor) * 2 where f[HOSTCLK] is the bus clock frequency in MHz, and f[MDC] is the MDIO clock frequency in MHz to the PHY. Typically, f[MDC] should not exceed 2.5 MHz. Some PHYs can tolerate faster speeds which means faster access. Here is the table to show values to generate MDC, 000 : divide pclk by 8 (pclk up to 20 MHz) 001 : divide pclk by 16 (pclk up to 40 MHz) 010 : divide pclk by 32 (pclk up to 80 MHz) 011 : divide pclk by 48 (pclk up to 120 MHz) 100 : divide pclk by 64 (pclk up to 160 MHz) 101 : divide pclk by 96 (pclk up to 240 MHz) 110 : divide pclk by 128 (pclk up to 320 MHz) 111 : divide pclk by 224 (pclk up to 540 MHz) InstancePtr is a pointer to the instance to be worked on. Divisor is the divisor to set. Range is 0b000 to 0b111.
References XEmacPs_Config::BaseAddress, XEmacPs_Config::MdioProducerBaseAddr, XEMACPS_NWCFG_MDC_SHIFT_MASK, XEMACPS_NWCFG_MDCCLKDIV_MASK, XEMACPS_NWCFG_OFFSET, XEmacPs_ReadReg, XEmacPs_WriteReg.
Referenced by EmacPsDmaIntrExample.
void XEmacPs_SetOperatingSpeed(XEmacPs *InstancePtr, u16 Speed)
XEmacPs_SetOperatingSpeed sets the current operating link speed.
For any traffic to be passed, this speed must match the current MII/GMII/SGMII/RGMII link speed. InstancePtr references the TEMAC channel on which to operate. Speed is the speed to set in units of Mbps. Valid values are 10, 100, or 1000. XEmacPs_SetOperatingSpeed ignores invalid values.
References XEmacPs_Config::BaseAddress, XEMACPS_NWCFG_1000_MASK, XEMACPS_NWCFG_100_MASK, XEMACPS_NWCFG_OFFSET, XEmacPs_ReadReg, XEmacPs_WriteReg.
Referenced by EmacPsDmaIntrExample.
u16 XEmacPs_GetOperatingSpeed(XEmacPs *InstancePtr)
XEmacPs_GetOperatingSpeed gets the current operating link speed.
This may be the value set by XEmacPs_SetOperatingSpeed() or a hardware default. InstancePtr references the TEMAC channel on which to operate. XEmacPs_GetOperatingSpeed returns the link speed in units of megabits per second.
References XEmacPs_Config::BaseAddress, XEMACPS_NWCFG_1000_MASK, XEMACPS_NWCFG_100_MASK, XEMACPS_NWCFG_OFFSET, XEmacPs_ReadReg.
LONG XEmacPs_PhyRead(XEmacPs *InstancePtr, u32 PhyAddress, u32 RegisterNum, u16 *PhyDataPtr)
Read the current value of the PHY register indicated by the PhyAddress and the RegisterNum parameters.
The MAC provides the driver with the ability to talk to a PHY that adheres to the Media Independent Interface (MII) as defined in the IEEE 802.3 standard.Prior to PHY access with this function, the user should have setup the MDIO clock with XEmacPs_SetMdioDivisor(). InstancePtr is a pointer to the XEmacPs instance to be worked on. PhyAddress is the address of the PHY to be read (supports multiple PHYs) RegisterNum is the register number, 0-31, of the specific PHY register to read PhyDataPtr is an output parameter, and points to a 16-bit buffer into which the current value of the register will be copied. XST_SUCCESS if the PHY was read from successfullyXST_EMAC_MII_BUSY if there is another PHY operation in progress This function is not thread-safe. The user must provide mutually exclusive access to this function if there are to be multiple threads that can call it.There is the possibility that this function will not return if the hardware is broken (i.e., it never sets the status bit indicating that the read is done). If this is of concern to the user, the user should provide a mechanism suitable to their needs for recovery.For the duration of this function, all host interface reads and writes are blocked to the current XEmacPs instance.
References XEmacPs_Config::BaseAddress, XEmacPs_Config::MdioProducerBaseAddr, XEMACPS_NWSR_MDIOIDLE_MASK, XEMACPS_NWSR_OFFSET, XEMACPS_PHYMNTNC_OFFSET, XEMACPS_PHYMNTNC_OP_MASK, XEMACPS_PHYMNTNC_OP_R_MASK, XEMACPS_PHYMNTNC_PHAD_SHFT_MSK, XEMACPS_PHYMNTNC_PREG_SHFT_MSK, XEmacPs_ReadReg, XEmacPs_WriteReg.
LONG XEmacPs_PhyWrite(XEmacPs *InstancePtr, u32 PhyAddress, u32 RegisterNum, u16 PhyData)
Write data to the specified PHY register.
The Ethernet driver does not require the device to be stopped before writing to the PHY. Although it is probably a good idea to stop the device, it is the responsibility of the application to deem this necessary. The MAC provides the driver with the ability to talk to a PHY that adheres to the Media Independent Interface (MII) as defined in the IEEE 802.3 standard.Prior to PHY access with this function, the user should have setup the MDIO clock with XEmacPs_SetMdioDivisor(). InstancePtr is a pointer to the XEmacPs instance to be worked on. PhyAddress is the address of the PHY to be written (supports multiple PHYs) RegisterNum is the register number, 0-31, of the specific PHY register to write PhyData is the 16-bit value that will be written to the register XST_SUCCESS if the PHY was written to successfully. Since there is no error status from the MAC on a write, the user should read the PHY to verify the write was successful.XST_EMAC_MII_BUSY if there is another PHY operation in progress This function is not thread-safe. The user must provide mutually exclusive access to this function if there are to be multiple threads that can call it.There is the possibility that this function will not return if the hardware is broken (i.e., it never sets the status bit indicating that the write is done). If this is of concern to the user, the user should provide a mechanism suitable to their needs for recovery.For the duration of this function, all host interface reads and writes are blocked to the current XEmacPs instance.
References XEmacPs_Config::BaseAddress, XEmacPs_Config::MdioProducerBaseAddr, XEMACPS_NWSR_MDIOIDLE_MASK, XEMACPS_NWSR_OFFSET, XEMACPS_PHYMNTNC_OFFSET, XEMACPS_PHYMNTNC_OP_MASK, XEMACPS_PHYMNTNC_OP_W_MASK, XEMACPS_PHYMNTNC_PHAD_SHFT_MSK, XEMACPS_PHYMNTNC_PREG_SHFT_MSK, XEmacPs_ReadReg, XEmacPs_WriteReg.
LONG XEmacPs_SetTypeIdCheck(XEmacPs *InstancePtr, u32 Id_Check, u8 Index)
Set the Type ID match for this driver/device.
The register is a 32-bit value. The device must be stopped before calling this function. InstancePtr is a pointer to the instance to be worked on. Id_Check is type ID to be configured. Index is a index to which Type ID (1-4). XST_SUCCESS if the MAC address was set successfullyXST_DEVICE_IS_STARTED if the device has not yet been stopped
References XEmacPs_Config::BaseAddress, XEMACPS_MATCH1_OFFSET, XEMACPS_MAX_TYPE_ID, XEmacPs_WriteReg.
Referenced by XEmacPs_Reset.
LONG XEmacPs_SendPausePacket(XEmacPs *InstancePtr)
Send a pause packet.
InstancePtr is a pointer to the instance to be worked on. XST_SUCCESS if pause frame transmission was initiatedXST_DEVICE_IS_STOPPED if the device has not been started.
References XEmacPs_Config::BaseAddress, XEMACPS_NWCTRL_OFFSET, XEMACPS_NWCTRL_PAUSETX_MASK, XEmacPs_ReadReg, XEmacPs_WriteReg.
void XEmacPs_DMABLengthUpdate(XEmacPs *InstancePtr, s32 BLength)
API to update the Burst length in the DMACR register.
InstancePtr is a pointer to the XEmacPs instance to be worked on. BLength is the length in bytes for the dma burst. None
References XEmacPs_Config::BaseAddress, XEMACPS_DMACR_BLENGTH_MASK, XEMACPS_DMACR_INCR16_AHB_BURST, XEMACPS_DMACR_INCR4_AHB_BURST, XEMACPS_DMACR_INCR8_AHB_BURST, XEMACPS_DMACR_OFFSET, XEMACPS_DMACR_SINGLE_AHB_BURST, XEmacPs_ReadReg, XEmacPs_WriteReg.
int XEmacPs_IsCommonMdioPresent(XEmacPs *InstancePtr)
Check if a common MDIO (Management Data Input/Output) interface is present.
This function evaluates whether the GEM instance uses a shared MDIO interface by comparing the base address of the current instance with the MDIO producer base address. The existence of a valid MDIO producer base address is also checked. InstancePtr is a pointer to the XEmacPs instance being checked. TRUE if a common MDIO is present (when the base address of the instance differs from the MDIO producer base address, and the producer base address is non-zero).FALSE otherwise.
References XEmacPs_Config::BaseAddress, XEmacPs_Config::MdioProducerBaseAddr.
Referenced by XEmacPs_Reset.