xemacps_control.c
LONG XEmacPs_SetMacAddress(XEmacPs *InstancePtr, void *AddressPtr, u8 Index)
Set the MAC address for this driver/device.
The address is a 48-bit value. The device must be stopped before calling this function. InstancePtr is a pointer to the instance to be worked on. AddressPtr is a pointer to a 6-byte MAC address. Index is a index to which MAC (1-4) address. XST_SUCCESS if the MAC address was set successfullyXST_DEVICE_IS_STARTED if the device has not yet been stopped
References XEmacPs_Config::BaseAddress, XEMACPS_LADDR1H_OFFSET, XEMACPS_LADDR1L_OFFSET, XEMACPS_LADDR_MACH_MASK, XEMACPS_MAX_MAC_ADDR, XEmacPs_ReadReg, XEmacPs_WriteReg.
Referenced by EmacPsDmaIntrExample, XEmacPs_Reset.
void XEmacPs_GetMacAddress(XEmacPs *InstancePtr, void *AddressPtr, u8 Index)
Get the MAC address for this driver/device.
InstancePtr is a pointer to the instance to be worked on. AddressPtr is an output parameter, and is a pointer to a buffer into which the current MAC address will be copied. Index is a index to which MAC (1-4) address.
References XEmacPs_Config::BaseAddress, XEMACPS_LADDR1H_OFFSET, XEMACPS_LADDR1L_OFFSET, XEMACPS_MAX_MAC_ADDR, XEmacPs_ReadReg.
LONG XEmacPs_SetHash(XEmacPs *InstancePtr, void *AddressPtr)
Set 48-bit MAC addresses in hash table.
The device must be stopped before calling this function.The hash address register is 64 bits long and takes up two locations in the memory map. The least significant bits are stored in hash register bottom and the most significant bits in hash register top.The unicast hash enable and the multicast hash enable bits in the network configuration register enable the reception of hash matched frames. The destination address is reduced to a 6 bit index into the 64 bit hash register using the following hash function. The hash function is an XOR of every sixth bit of the destination address. hash_index[05] = da[05]^da[11]^da[17]^da[23]^da[29]^da[35]^da[41]^da[47] hash_index[04] = da[04]^da[10]^da[16]^da[22]^da[28]^da[34]^da[40]^da[46] hash_index[03] = da[03]^da[09]^da[15]^da[21]^da[27]^da[33]^da[39]^da[45] hash_index[02] = da[02]^da[08]^da[14]^da[20]^da[26]^da[32]^da[38]^da[44] hash_index[01] = da[01]^da[07]^da[13]^da[19]^da[25]^da[31]^da[37]^da[43] hash_index[00] = da[00]^da[06]^da[12]^da[18]^da[24]^da[30]^da[36]^da[42] da[0] represents the least significant bit of the first byte received, that is, the multicast/unicast indicator, and da[47] represents the most significant bit of the last byte received.If the hash index points to a bit that is set in the hash register then the frame will be matched according to whether the frame is multicast or unicast.A multicast match will be signaled if the multicast hash enable bit is set, da[0] is logic 1 and the hash index points to a bit set in the hash register.A unicast match will be signaled if the unicast hash enable bit is set, da[0] is logic 0 and the hash index points to a bit set in the hash register.To receive all multicast frames, the hash register should be set with all ones and the multicast hash enable bit should be set in the network configuration register. InstancePtr is a pointer to the instance to be worked on. AddressPtr is a pointer to a 6-byte MAC address. XST_SUCCESS if the HASH MAC address was set successfullyXST_DEVICE_IS_STARTED if the device has not yet been stoppedXST_INVALID_PARAM if the HASH MAC address passed in does not meet requirement after calculation Having Aptr be unsigned type prevents the following operations from sign extending.
References XEmacPs_Config::BaseAddress, XEMACPS_HASHH_OFFSET, XEMACPS_HASHL_OFFSET, XEMACPS_MAX_HASH_BITS, XEmacPs_ReadReg, XEmacPs_WriteReg.
LONG XEmacPs_DeleteHash(XEmacPs *InstancePtr, void *AddressPtr)
Delete 48-bit MAC addresses in hash table.
The device must be stopped before calling this function. InstancePtr is a pointer to the instance to be worked on. AddressPtr is a pointer to a 6-byte MAC address. XST_SUCCESS if the HASH MAC address was deleted successfullyXST_DEVICE_IS_STARTED if the device has not yet been stoppedXST_INVALID_PARAM if the HASH MAC address passed in does not meet requirement after calculation Having Aptr be unsigned type prevents the following operations from sign extending.
References XEmacPs_Config::BaseAddress, XEMACPS_HASHH_OFFSET, XEMACPS_HASHL_OFFSET, XEMACPS_MAX_HASH_BITS, XEmacPs_ReadReg, XEmacPs_WriteReg.
void XEmacPs_ClearHash(XEmacPs *InstancePtr)
Clear the Hash registers for the mac address pointed by AddressPtr.
InstancePtr is a pointer to the instance to be worked on.
References XEmacPs_Config::BaseAddress, XEMACPS_HASHH_OFFSET, XEMACPS_HASHL_OFFSET, XEmacPs_WriteReg.
Referenced by XEmacPs_Reset.
void XEmacPs_GetHash(XEmacPs *InstancePtr, void *AddressPtr)
Get the Hash address for this driver/device.
InstancePtr is a pointer to the instance to be worked on. AddressPtr is an output parameter, and is a pointer to a buffer into which the current HASH MAC address will be copied.
References XEmacPs_Config::BaseAddress, XEMACPS_HASHH_OFFSET, XEMACPS_HASHL_OFFSET, XEmacPs_ReadReg.
LONG XEmacPs_SetTypeIdCheck(XEmacPs *InstancePtr, u32 Id_Check, u8 Index)
Set the Type ID match for this driver/device.
The register is a 32-bit value. The device must be stopped before calling this function. InstancePtr is a pointer to the instance to be worked on. Id_Check is type ID to be configured. Index is a index to which Type ID (1-4). XST_SUCCESS if the MAC address was set successfullyXST_DEVICE_IS_STARTED if the device has not yet been stopped
References XEmacPs_Config::BaseAddress, XEMACPS_MATCH1_OFFSET, XEMACPS_MAX_TYPE_ID, XEmacPs_WriteReg.
Referenced by XEmacPs_Reset.
LONG XEmacPs_SetOptions(XEmacPs *InstancePtr, u32 Options)
Set options for the driver/device.
The driver should be stopped with XEmacPs_Stop() before changing options. InstancePtr is a pointer to the instance to be worked on. Options are the options to set. Multiple options can be set by OR'ing XTE_*_OPTIONS constants together. Options not specified are not affected. XST_SUCCESS if the options were set successfullyXST_DEVICE_IS_STARTED if the device has not yet been stopped See xemacps.h for a description of the available options.
References XEmacPs_Config::BaseAddress, XEMACPS_BROADCAST_OPTION, XEMACPS_DMACR_OFFSET, XEMACPS_DMACR_RXBUF_MASK, XEMACPS_DMACR_RXBUF_SHIFT, XEMACPS_DMACR_TCPCKSUM_MASK, XEMACPS_FCS_STRIP_OPTION, XEMACPS_FLOW_CONTROL_OPTION, XEMACPS_FRAME1536_OPTION, XEMACPS_JUMBOMAXLEN_OFFSET, XEMACPS_LENTYPE_ERR_OPTION, XEMACPS_MULTICAST_OPTION, XEMACPS_NWCFG_1000_MASK, XEMACPS_NWCFG_1536RXEN_MASK, XEMACPS_NWCFG_BCASTDI_MASK, XEMACPS_NWCFG_COPYALLEN_MASK, XEMACPS_NWCFG_FCSREM_MASK, XEMACPS_NWCFG_JUMBO_MASK, XEMACPS_NWCFG_LENERRDSCRD_MASK, XEMACPS_NWCFG_MCASTHASHEN_MASK, XEMACPS_NWCFG_NVLANDISC_MASK, XEMACPS_NWCFG_OFFSET, XEMACPS_NWCFG_PAUSEEN_MASK, XEMACPS_NWCFG_PCSSEL_MASK, XEMACPS_NWCFG_RXCHKSUMEN_MASK, XEMACPS_NWCFG_SGMIIEN_MASK, XEMACPS_NWCTRL_OFFSET, XEMACPS_NWCTRL_RXEN_MASK, XEMACPS_NWCTRL_TXEN_MASK, XEMACPS_PROMISC_OPTION, XEmacPs_ReadReg, XEMACPS_RECEIVER_ENABLE_OPTION, XEMACPS_RX_BUF_UNIT, XEMACPS_RX_CHKSUM_ENABLE_OPTION, XEMACPS_RXBUF_LEN_JUMBO_MASK, XEMACPS_TRANSMITTER_ENABLE_OPTION, XEMACPS_TX_CHKSUM_ENABLE_OPTION, XEMACPS_VLAN_OPTION, XEmacPs_WriteReg.
Referenced by EmacPsDmaIntrExample, XEmacPs_Reset.
LONG XEmacPs_ClearOptions(XEmacPs *InstancePtr, u32 Options)
Clear options for the driver/device.
InstancePtr is a pointer to the instance to be worked on. Options are the options to clear. Multiple options can be cleared by OR'ing XEMACPS_*_OPTIONS constants together. Options not specified are not affected. XST_SUCCESS if the options were set successfullyXST_DEVICE_IS_STARTED if the device has not yet been stopped See xemacps.h for a description of the available options.
References XEmacPs_Config::BaseAddress, XEMACPS_BROADCAST_OPTION, XEMACPS_DMACR_OFFSET, XEMACPS_DMACR_RXBUF_MASK, XEMACPS_DMACR_RXBUF_SHIFT, XEMACPS_DMACR_TCPCKSUM_MASK, XEMACPS_FCS_STRIP_OPTION, XEMACPS_FLOW_CONTROL_OPTION, XEMACPS_FRAME1536_OPTION, XEMACPS_LENTYPE_ERR_OPTION, XEMACPS_MULTICAST_OPTION, XEMACPS_NWCFG_1000_MASK, XEMACPS_NWCFG_1536RXEN_MASK, XEMACPS_NWCFG_BCASTDI_MASK, XEMACPS_NWCFG_COPYALLEN_MASK, XEMACPS_NWCFG_FCSREM_MASK, XEMACPS_NWCFG_JUMBO_MASK, XEMACPS_NWCFG_LENERRDSCRD_MASK, XEMACPS_NWCFG_MCASTHASHEN_MASK, XEMACPS_NWCFG_NVLANDISC_MASK, XEMACPS_NWCFG_OFFSET, XEMACPS_NWCFG_PAUSEEN_MASK, XEMACPS_NWCFG_PCSSEL_MASK, XEMACPS_NWCFG_RXCHKSUMEN_MASK, XEMACPS_NWCFG_SGMIIEN_MASK, XEMACPS_NWCTRL_OFFSET, XEMACPS_NWCTRL_RXEN_MASK, XEMACPS_NWCTRL_TXEN_MASK, XEMACPS_PROMISC_OPTION, XEmacPs_ReadReg, XEMACPS_RECEIVER_ENABLE_OPTION, XEMACPS_RX_BUF_SIZE, XEMACPS_RX_BUF_UNIT, XEMACPS_RX_CHKSUM_ENABLE_OPTION, XEMACPS_RXBUF_LEN_MASK, XEMACPS_TRANSMITTER_ENABLE_OPTION, XEMACPS_TX_CHKSUM_ENABLE_OPTION, XEMACPS_VLAN_OPTION, XEmacPs_WriteReg.
Referenced by XEmacPs_Reset.
u32 XEmacPs_GetOptions(XEmacPs *InstancePtr)
Get current option settings.
InstancePtr is a pointer to the instance to be worked on. A bitmask of XTE_*_OPTION constants. Any bit set to 1 is to be interpreted as a set option. See xemacps.h for a description of the available options.
LONG XEmacPs_SendPausePacket(XEmacPs *InstancePtr)
Send a pause packet.
InstancePtr is a pointer to the instance to be worked on. XST_SUCCESS if pause frame transmission was initiatedXST_DEVICE_IS_STOPPED if the device has not been started.
References XEmacPs_Config::BaseAddress, XEMACPS_NWCTRL_OFFSET, XEMACPS_NWCTRL_PAUSETX_MASK, XEmacPs_ReadReg, XEmacPs_WriteReg.
u16 XEmacPs_GetOperatingSpeed(XEmacPs *InstancePtr)
XEmacPs_GetOperatingSpeed gets the current operating link speed.
This may be the value set by XEmacPs_SetOperatingSpeed() or a hardware default. InstancePtr references the TEMAC channel on which to operate. XEmacPs_GetOperatingSpeed returns the link speed in units of megabits per second.
References XEmacPs_Config::BaseAddress, XEMACPS_NWCFG_1000_MASK, XEMACPS_NWCFG_100_MASK, XEMACPS_NWCFG_OFFSET, XEmacPs_ReadReg.
void XEmacPs_SetOperatingSpeed(XEmacPs *InstancePtr, u16 Speed)
XEmacPs_SetOperatingSpeed sets the current operating link speed.
For any traffic to be passed, this speed must match the current MII/GMII/SGMII/RGMII link speed. InstancePtr references the TEMAC channel on which to operate. Speed is the speed to set in units of Mbps. Valid values are 10, 100, or 1000. XEmacPs_SetOperatingSpeed ignores invalid values.
References XEmacPs_Config::BaseAddress, XEMACPS_NWCFG_1000_MASK, XEMACPS_NWCFG_100_MASK, XEMACPS_NWCFG_OFFSET, XEmacPs_ReadReg, XEmacPs_WriteReg.
Referenced by EmacPsDmaIntrExample.
void XEmacPs_SetMdioDivisor(XEmacPs *InstancePtr, XEmacPs_MdcDiv Divisor)
Set the MDIO clock divisor.
Calculating the divisor: f[HOSTCLK] f[MDC] = ----------------- (1 + Divisor) * 2 where f[HOSTCLK] is the bus clock frequency in MHz, and f[MDC] is the MDIO clock frequency in MHz to the PHY. Typically, f[MDC] should not exceed 2.5 MHz. Some PHYs can tolerate faster speeds which means faster access. Here is the table to show values to generate MDC, 000 : divide pclk by 8 (pclk up to 20 MHz) 001 : divide pclk by 16 (pclk up to 40 MHz) 010 : divide pclk by 32 (pclk up to 80 MHz) 011 : divide pclk by 48 (pclk up to 120 MHz) 100 : divide pclk by 64 (pclk up to 160 MHz) 101 : divide pclk by 96 (pclk up to 240 MHz) 110 : divide pclk by 128 (pclk up to 320 MHz) 111 : divide pclk by 224 (pclk up to 540 MHz) InstancePtr is a pointer to the instance to be worked on. Divisor is the divisor to set. Range is 0b000 to 0b111.
References XEmacPs_Config::BaseAddress, XEmacPs_Config::MdioProducerBaseAddr, XEMACPS_NWCFG_MDC_SHIFT_MASK, XEMACPS_NWCFG_MDCCLKDIV_MASK, XEMACPS_NWCFG_OFFSET, XEmacPs_ReadReg, XEmacPs_WriteReg.
Referenced by EmacPsDmaIntrExample.
LONG XEmacPs_PhyRead(XEmacPs *InstancePtr, u32 PhyAddress, u32 RegisterNum, u16 *PhyDataPtr)
Read the current value of the PHY register indicated by the PhyAddress and the RegisterNum parameters.
The MAC provides the driver with the ability to talk to a PHY that adheres to the Media Independent Interface (MII) as defined in the IEEE 802.3 standard.Prior to PHY access with this function, the user should have setup the MDIO clock with XEmacPs_SetMdioDivisor(). InstancePtr is a pointer to the XEmacPs instance to be worked on. PhyAddress is the address of the PHY to be read (supports multiple PHYs) RegisterNum is the register number, 0-31, of the specific PHY register to read PhyDataPtr is an output parameter, and points to a 16-bit buffer into which the current value of the register will be copied. XST_SUCCESS if the PHY was read from successfullyXST_EMAC_MII_BUSY if there is another PHY operation in progress This function is not thread-safe. The user must provide mutually exclusive access to this function if there are to be multiple threads that can call it.There is the possibility that this function will not return if the hardware is broken (i.e., it never sets the status bit indicating that the read is done). If this is of concern to the user, the user should provide a mechanism suitable to their needs for recovery.For the duration of this function, all host interface reads and writes are blocked to the current XEmacPs instance.
References XEmacPs_Config::BaseAddress, XEmacPs_Config::MdioProducerBaseAddr, XEMACPS_NWSR_MDIOIDLE_MASK, XEMACPS_NWSR_OFFSET, XEMACPS_PHYMNTNC_OFFSET, XEMACPS_PHYMNTNC_OP_MASK, XEMACPS_PHYMNTNC_OP_R_MASK, XEMACPS_PHYMNTNC_PHAD_SHFT_MSK, XEMACPS_PHYMNTNC_PREG_SHFT_MSK, XEmacPs_ReadReg, XEmacPs_WriteReg.
int XEmacPs_IsCommonMdioPresent(XEmacPs *InstancePtr)
Check if a common MDIO (Management Data Input/Output) interface is present.
This function evaluates whether the GEM instance uses a shared MDIO interface by comparing the base address of the current instance with the MDIO producer base address. The existence of a valid MDIO producer base address is also checked. InstancePtr is a pointer to the XEmacPs instance being checked. TRUE if a common MDIO is present (when the base address of the instance differs from the MDIO producer base address, and the producer base address is non-zero).FALSE otherwise.
References XEmacPs_Config::BaseAddress, XEmacPs_Config::MdioProducerBaseAddr.
Referenced by XEmacPs_Reset.
LONG XEmacPs_PhyWrite(XEmacPs *InstancePtr, u32 PhyAddress, u32 RegisterNum, u16 PhyData)
Write data to the specified PHY register.
The Ethernet driver does not require the device to be stopped before writing to the PHY. Although it is probably a good idea to stop the device, it is the responsibility of the application to deem this necessary. The MAC provides the driver with the ability to talk to a PHY that adheres to the Media Independent Interface (MII) as defined in the IEEE 802.3 standard.Prior to PHY access with this function, the user should have setup the MDIO clock with XEmacPs_SetMdioDivisor(). InstancePtr is a pointer to the XEmacPs instance to be worked on. PhyAddress is the address of the PHY to be written (supports multiple PHYs) RegisterNum is the register number, 0-31, of the specific PHY register to write PhyData is the 16-bit value that will be written to the register XST_SUCCESS if the PHY was written to successfully. Since there is no error status from the MAC on a write, the user should read the PHY to verify the write was successful.XST_EMAC_MII_BUSY if there is another PHY operation in progress This function is not thread-safe. The user must provide mutually exclusive access to this function if there are to be multiple threads that can call it.There is the possibility that this function will not return if the hardware is broken (i.e., it never sets the status bit indicating that the write is done). If this is of concern to the user, the user should provide a mechanism suitable to their needs for recovery.For the duration of this function, all host interface reads and writes are blocked to the current XEmacPs instance.
References XEmacPs_Config::BaseAddress, XEmacPs_Config::MdioProducerBaseAddr, XEMACPS_NWSR_MDIOIDLE_MASK, XEMACPS_NWSR_OFFSET, XEMACPS_PHYMNTNC_OFFSET, XEMACPS_PHYMNTNC_OP_MASK, XEMACPS_PHYMNTNC_OP_W_MASK, XEMACPS_PHYMNTNC_PHAD_SHFT_MSK, XEMACPS_PHYMNTNC_PREG_SHFT_MSK, XEmacPs_ReadReg, XEmacPs_WriteReg.
void XEmacPs_DMABLengthUpdate(XEmacPs *InstancePtr, s32 BLength)
API to update the Burst length in the DMACR register.
InstancePtr is a pointer to the XEmacPs instance to be worked on. BLength is the length in bytes for the dma burst. None
References XEmacPs_Config::BaseAddress, XEMACPS_DMACR_BLENGTH_MASK, XEMACPS_DMACR_INCR16_AHB_BURST, XEMACPS_DMACR_INCR4_AHB_BURST, XEMACPS_DMACR_INCR8_AHB_BURST, XEMACPS_DMACR_OFFSET, XEMACPS_DMACR_SINGLE_AHB_BURST, XEmacPs_ReadReg, XEmacPs_WriteReg.