xemacps_hw.c
void XEmacPs_ResetHw(u32 BaseAddr)
This function perform the reset sequence to the given emacps interface by configuring the appropriate control bits in the emacps specific registers.
the emacps reset sequence involves the following steps Disable all the interuupts Clear the status registers Disable Rx and Tx engines Update the Tx and Rx descriptor queue registers with reset values Update the other relevant control registers with reset value BaseAddr of the interface N/A This function will not modify the slcr registers that are relevant for emacps controller
References XEMACPS_HASHH_OFFSET, XEMACPS_HASHL_OFFSET, XEMACPS_IDR_OFFSET, XEMACPS_ISR_OFFSET, XEMACPS_IXR_ALL_MASK, XEMACPS_NWCFG_OFFSET, XEMACPS_NWCFG_RESET_MASK, XEMACPS_NWCTRL_FLUSH_DPRAM_MASK, XEMACPS_NWCTRL_HALTTX_MASK, XEMACPS_NWCTRL_LOOPEN_MASK, XEMACPS_NWCTRL_OFFSET, XEMACPS_NWCTRL_RXEN_MASK, XEMACPS_NWCTRL_STATCLR_MASK, XEMACPS_NWCTRL_TXEN_MASK, XEmacPs_ReadReg, XEMACPS_RXQBASE_OFFSET, XEMACPS_RXSR_FRAMERX_MASK, XEMACPS_RXSR_OFFSET, XEMACPS_TXQBASE_OFFSET, XEMACPS_TXSR_OFFSET, XEMACPS_TXSR_TXCOMPL_MASK, XEMACPS_TXSR_TXGO_MASK, XEmacPs_WriteReg.
u32 XEmacPs_GetQxOffset(XEmacPs_QxRegOffset RegName, u8 Queue)
The register offset of a specific queue register is returned by this function.
RegName Basename of the register Queue Corresponding Queue Register offset
References XEMACPS_DMA_RXQ1_BUFSIZE_OFFSET, XEMACPS_DMA_RXQ2_BUFSIZE_OFFSET, XEMACPS_DMA_RXQ3_BUFSIZE_OFFSET, XEMACPS_INTQ1_IDR_OFFSET, XEMACPS_INTQ1_IER_OFFSET, XEMACPS_INTQ1_STS_OFFSET, XEMACPS_INTQ2_IDR_OFFSET, XEMACPS_INTQ2_IER_OFFSET, XEMACPS_INTQ2_STS_OFFSET, XEMACPS_INTQ3_IDR_OFFSET, XEMACPS_INTQ3_IER_OFFSET, XEMACPS_INTQ3_STS_OFFSET, XEMACPS_ISR_OFFSET, XEMACPS_RXQ1BASE_OFFSET, XEMACPS_RXQ2BASE_OFFSET, XEMACPS_RXQ3BASE_OFFSET, XEMACPS_RXQBASE_OFFSET, XEMACPS_TXQ1BASE_OFFSET, XEMACPS_TXQ2BASE_OFFSET, XEMACPS_TXQ3BASE_OFFSET, XEMACPS_TXQBASE_OFFSET.
Referenced by XEmacPs_IntrHandler, XEmacPs_Reset, XEmacPs_SetQueuePtr.