xpuf_client_api
int XPuf_ClientInit(XPuf_ClientInstance *const InstancePtr, XMailbox *const MailboxPtr)
This function sets the instance of mailbox.
InstancePtr Pointer to the client instance MailboxPtr Pointer to the mailbox instance XST_SUCCESS on successful initializationXST_FAILURE on failure
References XPuf_ClientInstance::MailboxPtr, XPuf_ClientInstance::SlrIndex.
int XPuf_Registration(const XPuf_ClientInstance *InstancePtr, const u64 DataAddr)
This function sends IPI request for PUF registration.
InstancePtr Pointer to the client instance DataAddr Address of the data structure which includes options to configure PUF XST_SUCCESS if the PUF registration is successfulXST_FAILURE if there is a failure
References PAYLOAD_ARG_CNT, XPuf_ClientInstance::SlrIndex, XPUF_ADDR_HIGH_SHIFT, XPUF_DEBUG_GENERAL, XPuf_Printf, XPUF_PUF_REGISTRATION, XPuf_SendRequest, XPUF_SLR_INDEX_SHIFT.
int XPuf_Regeneration(const XPuf_ClientInstance *InstancePtr, const u64 DataAddr)
This function sends IPI request for PUF regeneration(on demand / ID only).
InstancePtr Pointer to the client instance DataAddr Address of the data structure which includes options to configure PUF XST_SUCCESS if the PUF regeneration is successfulXST_FAILURE if there is a failure
References PAYLOAD_ARG_CNT, XPuf_ClientInstance::SlrIndex, XPUF_ADDR_HIGH_SHIFT, XPUF_DEBUG_GENERAL, XPuf_Printf, XPUF_PUF_REGENERATION, XPuf_SendRequest, XPUF_SLR_INDEX_SHIFT.
int XPuf_ClearPufID(const XPuf_ClientInstance *InstancePtr)
This function sends IPI request for clearing PUF ID.
InstancePtr Pointer to the client instance XST_SUCCESS if the PUF clear ID is successfulXST_FAILURE if there is a failure
References PAYLOAD_ARG_CNT, XPuf_ClientInstance::SlrIndex, XPUF_DEBUG_GENERAL, XPuf_Printf, XPUF_PUF_CLEAR_PUF_ID, XPuf_SendRequest, XPUF_SLR_INDEX_SHIFT.
int XPuf_SendRequest(const XPuf_ClientInstance *InstancePtr, u32 *PayloadBuf, u32 PayloadLen, u32 *ResponseBuf, u32 ResponseLen)
This function sends request to PLM through either SMC or IPI mailbox based on the execution environment.
For EL1 non-secure AArch64 applications, SMC is used. For other environments, IPI mailbox is used. InstancePtr Pointer to the client instance PayloadBuf Pointer to the payload message PayloadLen Length of the payload message ResponseBuf Pointer to store response values (can be NULL) ResponseLen Length of response buffer (number of u32 elements) XST_SUCCESS if the request is successfulXST_FAILURE if there is a failureXST_INVALID_PARAM if input parameters are invalid This is a generic API that internally handles SMC or Mailbox communication based on the build configuration.
References XPuf_ClientInstance::MailboxPtr, XPuf_ProcessMailbox.
Referenced by XPuf_ClearPufID, XPuf_Regeneration, XPuf_Registration.
XPUF_SLR_INDEX_SHIFT
Shift value to get SLR index in the header of the IPI request.
Referenced by XPuf_ClearPufID, XPuf_Regeneration, XPuf_Registration.
XPUF_ADDR_HIGH_SHIFT
Shift value to get higher 32-bit address.
Referenced by XPuf_Regeneration, XPuf_Registration.