xpuf_generic.h
int XPuf_SendRequest(const XPuf_ClientInstance *InstancePtr, u32 *PayloadBuf, u32 PayloadLen, u32 *ResponseBuf, u32 ResponseLen)
This function sends request to PLM through either SMC or IPI mailbox based on the execution environment.
For EL1 non-secure AArch64 applications, SMC is used. For other environments, IPI mailbox is used. InstancePtr Pointer to the client instance PayloadBuf Pointer to the payload message PayloadLen Length of the payload message ResponseBuf Pointer to store response values (can be NULL) ResponseLen Length of response buffer (number of u32 elements) XST_SUCCESS if the request is successfulXST_FAILURE if there is a failureXST_INVALID_PARAM if input parameters are invalid This is a generic API that internally handles SMC or Mailbox communication based on the build configuration.
References XPuf_ClientInstance::MailboxPtr, XPuf_ProcessMailbox.
Referenced by XPuf_Registration, XPuf_Regeneration, XPuf_ClearPufID.