v_multi_scaler
XV_MULTISCALER_TYPE
Bilinear interpolation.
XV_MULTISCALER_TAPS
6-tap filter
XV_MULTISCALER_MEMORY_FORMATS
RGB with alpha, 8-bit per component.
const short XV_multiscaler_fixedcoeff_taps6_12C[XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12][XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12]
Fixed coefficient table for 6-tap polyphase filter (12 coefficient format)
Fixed coefficient table for 6-tap filter with 12 coefficients per phase.This table contains a 64-phase, 6-tap FIR filter bank for vertical and horizontal scaling. The 12-coefficient format includes zero-padding to match hardware requirements. Each row represents one of 64 interpolation phases, allowing smooth sub-pixel precision during scaling operations.Format: [XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12] Phases: 64 Active taps: 6 (with padding zeros)
const short XV_multiscaler_fixedcoeff_taps6_6C[XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_6][XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_6]
Fixed coefficient table for 6-tap polyphase filter (6 coefficient format)
Fixed coefficient tables for polyphase scaling filters.This table contains a 64-phase, 6-tap FIR filter bank optimized for hardware implementations that support exactly 6 coefficients per phase. This is a compact version of the 12C format without padding zeros.Format: [XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_6] Phases: 64 Active taps: 6
const short XV_multiscaler_fixedcoeff_taps8_12C[XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12][XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12]
Fixed coefficient table for 8-tap polyphase filter (12 coefficient format)
Fixed coefficient table for 8-tap filter with 12 coefficients per phase.This table contains a 64-phase, 8-tap FIR filter bank providing higher quality scaling compared to 6-tap filters. The 12-coefficient format includes zero-padding for hardware alignment. 8-tap filters offer improved frequency response and reduced aliasing artifacts.Format: [XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12] Phases: 64 Active taps: 8 (with padding zeros)
const short XV_multiscaler_fixedcoeff_taps8_8C[XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_8][XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_8]
Fixed coefficient table for 8-tap polyphase filter (8 coefficient format)
Fixed coefficient table for 8-tap filter with 8 coefficients per phase.This table contains a 64-phase, 8-tap FIR filter bank in compact format without padding zeros. Optimized for hardware that supports exactly 8 coefficients per phase.Format: [XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_8] Phases: 64 Active taps: 8
const short XV_multiscaler_fixedcoeff_taps10_12C[XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12][XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12]
Fixed coefficient table for 10-tap polyphase filter (12 coefficient format)
Fixed coefficient table for 10-tap filter with 12 coefficients per phase.This table contains a 64-phase, 10-tap FIR filter bank offering superior scaling quality. The 12-coefficient format includes minimal padding. 10-tap filters provide excellent frequency response characteristics and minimal ringing artifacts, suitable for professional image processing.Format: [XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12] Phases: 64 Active taps: 10 (with minimal padding)
const short XV_multiscaler_fixedcoeff_taps10_10C[XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_10][XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_10]
Fixed coefficient table for 10-tap polyphase filter (10 coefficient format)
Fixed coefficient table for 10-tap filter with 10 coefficients per phase.This table contains a 64-phase, 10-tap FIR filter bank in compact format without padding zeros. Optimized for hardware that supports exactly 10 coefficients per phase.Format: [XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_10] Phases: 64 Active taps: 10
const short XV_multiscaler_fixedcoeff_taps12_12C[XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12][XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12]
Fixed coefficient table for 12-tap polyphase filter (12 coefficient format)
Fixed coefficient table for 12-tap filter with 12 coefficients per phase.This table contains a 64-phase, 12-tap FIR filter bank providing the highest quality scaling among all supported tap configurations. With no padding required, all 12 coefficients are active. 12-tap filters deliver exceptional frequency response, minimal aliasing, and superior image quality for demanding applications.Format: [XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12] Phases: 64 Active taps: 12
XV_multi_scaler_Config XV_multi_scaler_ConfigTable[][]
MultiScaler device configuration table.
Configuration table for multi-scaler devices.This table contains the configuration information for each MultiScaler device in the system. Each entry includes: Device ID: Unique identifier for the device instanceBase Address: AXI control interface base addressSamples Per Clock: Number of samples processed per clock cycleMax Data Width: Maximum pixel data width supportedMax Cols: Maximum number of horizontal pixelsMax Rows: Maximum number of vertical pixelsPhase Shift: Scaling phase shift precisionScale Mode: Supported scaling modes (bilinear, polyphase, etc.)Taps: Number of filter taps for polyphase scalingMax Outs: Maximum number of output channels supported The table is indexed by device ID for lookup during initialization.
Referenced by XV_multi_scaler_LookupConfig.
const u32(* XV_MS_Get_WidthIn[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)
const u32(* XV_MS_Get_WidthOut[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)
const u32(* XV_MS_Get_HeightIn[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)
const u32(* XV_MS_Get_HeightOut[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)
const u32(* XV_MS_Get_ColorFormatIn[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)
const u32(* XV_MS_Get_ColorFormatOut[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)
const u32(* XV_MS_Get_InStride[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)
const u32(* XV_MS_Get_OutStride[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)
const u64(* XV_MS_Get_SrcImgBuf0[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)
const u64(* XV_MS_Get_SrcImgBuf1[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)
const u64(* XV_MS_Get_DstImgBuf0[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)
const u64(* XV_MS_Get_DstImgBuf1[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)
const void(* XV_MS_Set_WidthIn[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)
const void(* XV_MS_Set_WidthOut[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)
const void(* XV_MS_Set_HeightIn[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)
const void(* XV_MS_Set_HeightOut[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)
const void(* XV_MS_Set_LineRate[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)
const void(* XV_MS_Set_PixelRate[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)
const void(* XV_MS_Set_ColorFormatIn[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)
const void(* XV_MS_Set_ColorFormatOut[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)
const void(* XV_MS_Set_InStride[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)
const void(* XV_MS_Set_OutStride[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)
const void(* XV_MS_Set_SrcImgBuf0[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u64 Data)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u64 Data)
const void(* XV_MS_Set_SrcImgBuf1[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u64 Data)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u64 Data)
const void(* XV_MS_Set_DstImgBuf0[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u64 Data)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u64 Data)
const void(* XV_MS_Set_DstImgBuf1[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u64 Data)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u64 Data)
const short XV_multiscaler_fixedcoeff_taps6_6C[XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_6][XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_6]
Fixed coefficient tables for polyphase scaling filters.
Fixed coefficient tables for polyphase scaling filters.This table contains a 64-phase, 6-tap FIR filter bank optimized for hardware implementations that support exactly 6 coefficients per phase. This is a compact version of the 12C format without padding zeros.Format: [XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_6] Phases: 64 Active taps: 6
const short XV_multiscaler_fixedcoeff_taps6_12C[XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12][XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12]
Fixed coefficient table for 6-tap filter with 12 coefficients per phase.
Fixed coefficient table for 6-tap filter with 12 coefficients per phase.This table contains a 64-phase, 6-tap FIR filter bank for vertical and horizontal scaling. The 12-coefficient format includes zero-padding to match hardware requirements. Each row represents one of 64 interpolation phases, allowing smooth sub-pixel precision during scaling operations.Format: [XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12] Phases: 64 Active taps: 6 (with padding zeros)
const short XV_multiscaler_fixedcoeff_taps8_8C[XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_8][XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_8]
Fixed coefficient table for 8-tap filter with 8 coefficients per phase.
Fixed coefficient table for 8-tap filter with 8 coefficients per phase.This table contains a 64-phase, 8-tap FIR filter bank in compact format without padding zeros. Optimized for hardware that supports exactly 8 coefficients per phase.Format: [XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_8] Phases: 64 Active taps: 8
const short XV_multiscaler_fixedcoeff_taps8_12C[XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12][XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12]
Fixed coefficient table for 8-tap filter with 12 coefficients per phase.
Fixed coefficient table for 8-tap filter with 12 coefficients per phase.This table contains a 64-phase, 8-tap FIR filter bank providing higher quality scaling compared to 6-tap filters. The 12-coefficient format includes zero-padding for hardware alignment. 8-tap filters offer improved frequency response and reduced aliasing artifacts.Format: [XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12] Phases: 64 Active taps: 8 (with padding zeros)
const short XV_multiscaler_fixedcoeff_taps10_10C[XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_10][XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_10]
Fixed coefficient table for 10-tap filter with 10 coefficients per phase.
Fixed coefficient table for 10-tap filter with 10 coefficients per phase.This table contains a 64-phase, 10-tap FIR filter bank in compact format without padding zeros. Optimized for hardware that supports exactly 10 coefficients per phase.Format: [XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_10] Phases: 64 Active taps: 10
const short XV_multiscaler_fixedcoeff_taps10_12C[XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12][XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12]
Fixed coefficient table for 10-tap filter with 12 coefficients per phase.
Fixed coefficient table for 10-tap filter with 12 coefficients per phase.This table contains a 64-phase, 10-tap FIR filter bank offering superior scaling quality. The 12-coefficient format includes minimal padding. 10-tap filters provide excellent frequency response characteristics and minimal ringing artifacts, suitable for professional image processing.Format: [XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12] Phases: 64 Active taps: 10 (with minimal padding)
const short XV_multiscaler_fixedcoeff_taps12_12C[XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12][XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12]
Fixed coefficient table for 12-tap filter with 12 coefficients per phase.
Fixed coefficient table for 12-tap filter with 12 coefficients per phase.This table contains a 64-phase, 12-tap FIR filter bank providing the highest quality scaling among all supported tap configurations. With no padding required, all 12 coefficients are active. 12-tap filters deliver exceptional frequency response, minimal aliasing, and superior image quality for demanding applications.Format: [XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12] Phases: 64 Active taps: 12
void XVMultiScaler_SetCallback(XV_multi_scaler *InstancePtr, void *CallbackFunc, void *CallbackRef)
Install an asynchronous callback function for MultiScaler events.
This function registers a user-defined callback function that will be invoked when the MultiScaler IP generates an interrupt. The callback is typically used to handle frame processing completion notifications. InstancePtr is a pointer to the MultiScaler IP instance. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. None Invoking this function for a handler that already has been installed replaces it with the new handler.
References XV_multi_scaler::CallbackRef, XV_multi_scaler::FrameDoneCallback.
Referenced by main.
void* XV_MultiScalerIntrHandler(void *InstancePtr)
This function is the interrupt handler for the MultiScaler core driver.
This handler clears the pending interrupt and determines if the source is frame done signal. If yes, calls the registered callback function.The application is responsible for connecting this function to the interrupt system. InstancePtr is a pointer to the core instance that just interrupted. None. None.
References XV_multi_scaler::FrameDoneCallback, XV_multi_scaler::IsReady, XV_multi_scaler_InterruptClear, XV_multi_scaler_InterruptGetStatus, XV_MULTI_SCALER_ISR_DONE_BIT_MASK, XV_MULTI_SCALER_ISR_READY_BIT_MASK.
Referenced by main.
static void XV_MultiScalerSetCoeff(XV_multi_scaler *MscPtr, XV_multi_scaler_Video_Config *MS_cfg)
Program filter coefficients for scaling operation.
This function selects and programs the appropriate fixed filter coefficients into the multi scaler core registers based on the scaling ratio. The coefficients are chosen from predefined tables based on the vertical and horizontal scaling factors (HeightIn/HeightOut and WidthIn/WidthOut). Different coefficient sets are used for different scaling ranges to optimize image quality. MscPtr is a pointer to the core instance to be worked on. MS_cfg is a pointer to the channel configuration structure containing scaling parameters. None This is a static (internal) function called by XV_MultiScalerSetChannelConfig.
void XV_MultiScalerStart(XV_multi_scaler *InstancePtr)
Start the multi scaler core operation.
This function enables auto-restart mode and starts the multi scaler core. It validates that the number of outputs is configured correctly and that all output channels specified by the output bit mask are properly configured. InstancePtr is a pointer to the core instance to be worked on. None None
References XV_multi_scaler::OutBitMask, XV_MAX_OUTS, XV_multi_scaler_EnableAutoRestart, XV_multi_scaler_Get_HwReg_num_outs, XV_multi_scaler_Start, XV_MULTISCALER_OUTPUT_MASK.
Referenced by main.
void XV_MultiScalerStop(XV_multi_scaler *InstancePtr)
Stop the multi scaler core operation.
This function disables auto-restart mode on the multi scaler core, effectively stopping its operation after the current frame completes. InstancePtr is a pointer to the core instance to be worked on. None None
References XV_multi_scaler_DisableAutoRestart.
Referenced by XVMultiScalerCallback.
u32 XV_MultiScalerGetNumOutputs(XV_multi_scaler *InstancePtr)
Get the number of output channels configured.
This function retrieves the current number of output channels that are configured for the multi scaler core. InstancePtr is a pointer to the core instance to be worked on. Number of configured output channels (u32). None
References XV_multi_scaler_Get_HwReg_num_outs.
Referenced by main.
void XV_MultiScalerSetNumOutputs(XV_multi_scaler *InstancePtr, u32 NumOuts)
Set the number of output channels to be used.
This function configures the number of output channels for the multi scaler core. The number must be between 1 and the maximum number of outputs supported by the hardware instance. The output bit mask is reset when this function is called. InstancePtr is a pointer to the core instance to be worked on. NumOuts is the number of output channels to configure. None NumOuts must be greater than 0 and less than or equal to MaxOuts.
References XV_multi_scaler::OutBitMask, XV_multi_scaler_Set_HwReg_num_outs.
Referenced by main.
void XV_MultiScalerGetChannelConfig(XV_multi_scaler *InstancePtr, XV_multi_scaler_Video_Config *MS_cfg)
Read the configuration of a specific channel.
This function retrieves the current configuration settings for a specified output channel. The application must set the ChannelId field in the MS_cfg structure before calling this function. The function reads all channel parameters including dimensions, color formats, strides, and buffer addresses. InstancePtr is a pointer to the core instance to be worked on. MS_cfg is a pointer to the multi scaler config structure. The ChannelId field must be pre-filled by the application. None The ChannelId in MS_cfg must be set before calling this function.
References XV_multi_scaler_Video_Config::ChannelId, XV_multi_scaler_Video_Config::ColorFormatIn, XV_multi_scaler_Video_Config::ColorFormatOut, XV_multi_scaler_Video_Config::DstImgBuf0, XV_multi_scaler_Video_Config::DstImgBuf1, XV_multi_scaler_Video_Config::HeightIn, XV_multi_scaler_Video_Config::HeightOut, XV_multi_scaler_Video_Config::InStride, XV_multi_scaler_Video_Config::OutStride, XV_multi_scaler::SamplesPerClock, XV_multi_scaler_Video_Config::SrcImgBuf0, XV_multi_scaler_Video_Config::SrcImgBuf1, XV_multi_scaler_Video_Config::WidthIn, XV_multi_scaler_Video_Config::WidthOut.
void XV_MultiScalerSetChannelConfig(XV_multi_scaler *InstancePtr, XV_multi_scaler_Video_Config *MS_cfg)
Configure a channel with the specified scaling parameters.
This function programs all configuration parameters for a specific output channel including input/output dimensions, color formats, strides, buffer addresses, and scaling rates. It also handles optional cropping window configuration and automatically programs the appropriate filter coefficients based on the scaling ratio. Extensive validation is performed on all parameters to ensure valid configuration. InstancePtr is a pointer to the core instance to be worked on. MS_cfg is a pointer to the multi scaler config structure containing all channel configuration parameters. None All configuration parameters are validated via assertions. Buffer addresses must not overlap to prevent data corruption.
References XV_multi_scaler_Video_Config::ChannelId, XV_multi_scaler_Video_Config::ColorFormatIn, XV_multi_scaler_Video_Config::ColorFormatOut, XV_multi_scaler_Crop_Window::Crop, XV_multi_scaler_Video_Config::CropWin, XV_multi_scaler_Video_Config::DstImgBuf0, XV_multi_scaler_Video_Config::DstImgBuf1, XV_multi_scaler_Crop_Window::Height, XV_multi_scaler_Video_Config::HeightIn, XV_multi_scaler_Video_Config::HeightOut, XV_multi_scaler_Video_Config::InStride, XV_multi_scaler::MaxCols, XV_multi_scaler::MaxRows, XV_multi_scaler::OutBitMask, XV_multi_scaler_Video_Config::OutStride, XV_multi_scaler::SamplesPerClock, XV_multi_scaler_Video_Config::SrcImgBuf0, XV_multi_scaler_Video_Config::SrcImgBuf1, XV_multi_scaler_Crop_Window::StartX, XV_multi_scaler_Crop_Window::StartY, STEP_PRECISION, XV_multi_scaler_Crop_Window::Width, XV_multi_scaler_Video_Config::WidthIn, XV_multi_scaler_Video_Config::WidthOut, XV_MULTI_SCALER_BGR8, XV_MULTI_SCALER_RGB8, XV_MULTI_SCALER_UYVY8, XV_MULTI_SCALER_Y10, XV_MULTI_SCALER_Y8, XV_MULTI_SCALER_Y_UV10, XV_MULTI_SCALER_Y_UV10_420, XV_MULTI_SCALER_Y_UV8, XV_MULTI_SCALER_Y_UV8_420, XV_MULTI_SCALER_YUV8, XV_MULTI_SCALER_YUYV8.
Referenced by main.
XV_MULTISCALER_MAX_V_TAPS
Maximum number of vertical taps supported by the scaler.
XV_MULTISCALER_MAX_V_PHASES
Maximum number of vertical phases for polyphase filter.
XV_MULTISCALER_OUTPUT_MASK
Bit mask for extracting output channel selection.
Referenced by XV_MultiScalerStart.
XV_MAX_BYTES_PER_PIXEL
Maximum bytes per pixel (for RGBX/YUVX at 10-bit)
XV_MAX_BUF_SIZE
Maximum buffer size calculation based on max dimensions and pixel format.
XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_FLTCOEFF_OFFSET
Hardware register offset for filter coefficient memory.
STEP_PRECISION
Fixed-point precision for scaling step calculation (2^16)
Referenced by XV_MultiScalerSetChannelConfig.
XVSC_MASK_LOW_16BITS
Bit mask for extracting lower 16 bits.
XVSC_MASK_HIGH_16BITS
Bit mask for extracting upper 16 bits.