xv_multi_scaler_l2.c
const u32(* XV_MS_Get_WidthIn[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)
const u32(* XV_MS_Get_WidthOut[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)
const u32(* XV_MS_Get_HeightIn[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)
const u32(* XV_MS_Get_HeightOut[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)
const u32(* XV_MS_Get_ColorFormatIn[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)
const u32(* XV_MS_Get_ColorFormatOut[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)
const u32(* XV_MS_Get_InStride[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)
const u32(* XV_MS_Get_OutStride[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)
const u64(* XV_MS_Get_SrcImgBuf0[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)
const u64(* XV_MS_Get_SrcImgBuf1[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)
const u64(* XV_MS_Get_DstImgBuf0[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)
const u64(* XV_MS_Get_DstImgBuf1[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr)
const void(* XV_MS_Set_WidthIn[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)
const void(* XV_MS_Set_WidthOut[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)
const void(* XV_MS_Set_HeightIn[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)
const void(* XV_MS_Set_HeightOut[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)
const void(* XV_MS_Set_LineRate[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)
const void(* XV_MS_Set_PixelRate[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)
const void(* XV_MS_Set_ColorFormatIn[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)
const void(* XV_MS_Set_ColorFormatOut[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)
const void(* XV_MS_Set_InStride[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)
const void(* XV_MS_Set_OutStride[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u32 Data)
const void(* XV_MS_Set_SrcImgBuf0[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u64 Data)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u64 Data)
const void(* XV_MS_Set_SrcImgBuf1[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u64 Data)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u64 Data)
const void(* XV_MS_Set_DstImgBuf0[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u64 Data)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u64 Data)
const void(* XV_MS_Set_DstImgBuf1[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u64 Data)[XV_MAX_OUTS])(XV_multi_scaler *InstancePtr, u64 Data)
static void XV_MultiScalerSetCoeff(XV_multi_scaler *MscPtr, XV_multi_scaler_Video_Config *MS_cfg)
Program filter coefficients for scaling operation.
This function selects and programs the appropriate fixed filter coefficients into the multi scaler core registers based on the scaling ratio. The coefficients are chosen from predefined tables based on the vertical and horizontal scaling factors (HeightIn/HeightOut and WidthIn/WidthOut). Different coefficient sets are used for different scaling ranges to optimize image quality. MscPtr is a pointer to the core instance to be worked on. MS_cfg is a pointer to the channel configuration structure containing scaling parameters. None This is a static (internal) function called by XV_MultiScalerSetChannelConfig.
void XV_MultiScalerStart(XV_multi_scaler *InstancePtr)
Start the multi scaler core operation.
This function enables auto-restart mode and starts the multi scaler core. It validates that the number of outputs is configured correctly and that all output channels specified by the output bit mask are properly configured. InstancePtr is a pointer to the core instance to be worked on. None None
References XV_multi_scaler::OutBitMask, XV_MAX_OUTS, XV_multi_scaler_EnableAutoRestart, XV_multi_scaler_Get_HwReg_num_outs, XV_multi_scaler_Start, XV_MULTISCALER_OUTPUT_MASK.
Referenced by main.
void XV_MultiScalerStop(XV_multi_scaler *InstancePtr)
Stop the multi scaler core operation.
This function disables auto-restart mode on the multi scaler core, effectively stopping its operation after the current frame completes. InstancePtr is a pointer to the core instance to be worked on. None None
References XV_multi_scaler_DisableAutoRestart.
Referenced by XVMultiScalerCallback.
u32 XV_MultiScalerGetNumOutputs(XV_multi_scaler *InstancePtr)
Get the number of output channels configured.
This function retrieves the current number of output channels that are configured for the multi scaler core. InstancePtr is a pointer to the core instance to be worked on. Number of configured output channels (u32). None
References XV_multi_scaler_Get_HwReg_num_outs.
Referenced by main.
void XV_MultiScalerSetNumOutputs(XV_multi_scaler *InstancePtr, u32 NumOuts)
Set the number of output channels to be used.
This function configures the number of output channels for the multi scaler core. The number must be between 1 and the maximum number of outputs supported by the hardware instance. The output bit mask is reset when this function is called. InstancePtr is a pointer to the core instance to be worked on. NumOuts is the number of output channels to configure. None NumOuts must be greater than 0 and less than or equal to MaxOuts.
References XV_multi_scaler::OutBitMask, XV_multi_scaler_Set_HwReg_num_outs.
Referenced by main.
void XV_MultiScalerGetChannelConfig(XV_multi_scaler *InstancePtr, XV_multi_scaler_Video_Config *MS_cfg)
Read the configuration of a specific channel.
This function retrieves the current configuration settings for a specified output channel. The application must set the ChannelId field in the MS_cfg structure before calling this function. The function reads all channel parameters including dimensions, color formats, strides, and buffer addresses. InstancePtr is a pointer to the core instance to be worked on. MS_cfg is a pointer to the multi scaler config structure. The ChannelId field must be pre-filled by the application. None The ChannelId in MS_cfg must be set before calling this function.
References XV_multi_scaler_Video_Config::ChannelId, XV_multi_scaler_Video_Config::ColorFormatIn, XV_multi_scaler_Video_Config::ColorFormatOut, XV_multi_scaler_Video_Config::DstImgBuf0, XV_multi_scaler_Video_Config::DstImgBuf1, XV_multi_scaler_Video_Config::HeightIn, XV_multi_scaler_Video_Config::HeightOut, XV_multi_scaler_Video_Config::InStride, XV_multi_scaler_Video_Config::OutStride, XV_multi_scaler::SamplesPerClock, XV_multi_scaler_Video_Config::SrcImgBuf0, XV_multi_scaler_Video_Config::SrcImgBuf1, XV_multi_scaler_Video_Config::WidthIn, XV_multi_scaler_Video_Config::WidthOut.
void XV_MultiScalerSetChannelConfig(XV_multi_scaler *InstancePtr, XV_multi_scaler_Video_Config *MS_cfg)
Configure a channel with the specified scaling parameters.
This function programs all configuration parameters for a specific output channel including input/output dimensions, color formats, strides, buffer addresses, and scaling rates. It also handles optional cropping window configuration and automatically programs the appropriate filter coefficients based on the scaling ratio. Extensive validation is performed on all parameters to ensure valid configuration. InstancePtr is a pointer to the core instance to be worked on. MS_cfg is a pointer to the multi scaler config structure containing all channel configuration parameters. None All configuration parameters are validated via assertions. Buffer addresses must not overlap to prevent data corruption.
References XV_multi_scaler_Video_Config::ChannelId, XV_multi_scaler_Video_Config::ColorFormatIn, XV_multi_scaler_Video_Config::ColorFormatOut, XV_multi_scaler_Crop_Window::Crop, XV_multi_scaler_Video_Config::CropWin, XV_multi_scaler_Video_Config::DstImgBuf0, XV_multi_scaler_Video_Config::DstImgBuf1, XV_multi_scaler_Crop_Window::Height, XV_multi_scaler_Video_Config::HeightIn, XV_multi_scaler_Video_Config::HeightOut, XV_multi_scaler_Video_Config::InStride, XV_multi_scaler::MaxCols, XV_multi_scaler::MaxRows, XV_multi_scaler::OutBitMask, XV_multi_scaler_Video_Config::OutStride, XV_multi_scaler::SamplesPerClock, XV_multi_scaler_Video_Config::SrcImgBuf0, XV_multi_scaler_Video_Config::SrcImgBuf1, XV_multi_scaler_Crop_Window::StartX, XV_multi_scaler_Crop_Window::StartY, STEP_PRECISION, XV_multi_scaler_Crop_Window::Width, XV_multi_scaler_Video_Config::WidthIn, XV_multi_scaler_Video_Config::WidthOut, XV_MULTI_SCALER_BGR8, XV_MULTI_SCALER_RGB8, XV_MULTI_SCALER_UYVY8, XV_MULTI_SCALER_Y10, XV_MULTI_SCALER_Y8, XV_MULTI_SCALER_Y_UV10, XV_MULTI_SCALER_Y_UV10_420, XV_MULTI_SCALER_Y_UV8, XV_MULTI_SCALER_Y_UV8_420, XV_MULTI_SCALER_YUV8, XV_MULTI_SCALER_YUYV8.
Referenced by main.