xv_multi_scaler_l2.h
XV_MULTISCALER_MAX_V_TAPS
Maximum number of vertical taps supported by the scaler.
XV_MULTISCALER_MAX_V_PHASES
Maximum number of vertical phases for polyphase filter.
XV_MULTISCALER_OUTPUT_MASK
Bit mask for extracting output channel selection.
Referenced by XV_MultiScalerStart.
XV_MAX_BYTES_PER_PIXEL
Maximum bytes per pixel (for RGBX/YUVX at 10-bit)
XV_MAX_BUF_SIZE
Maximum buffer size calculation based on max dimensions and pixel format.
XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_FLTCOEFF_OFFSET
Hardware register offset for filter coefficient memory.
STEP_PRECISION
Fixed-point precision for scaling step calculation (2^16)
Referenced by XV_MultiScalerSetChannelConfig.
XVSC_MASK_LOW_16BITS
Bit mask for extracting lower 16 bits.
XVSC_MASK_HIGH_16BITS
Bit mask for extracting upper 16 bits.
XV_MULTISCALER_TYPE
Bilinear interpolation.
XV_MULTISCALER_TAPS
6-tap filter
XV_MULTISCALER_MEMORY_FORMATS
RGB with alpha, 8-bit per component.
const short XV_multiscaler_fixedcoeff_taps6_6C[XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_6][XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_6]
Fixed coefficient tables for polyphase scaling filters.
Fixed coefficient tables for polyphase scaling filters.This table contains a 64-phase, 6-tap FIR filter bank optimized for hardware implementations that support exactly 6 coefficients per phase. This is a compact version of the 12C format without padding zeros.Format: [XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_6] Phases: 64 Active taps: 6
const short XV_multiscaler_fixedcoeff_taps6_12C[XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12][XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12]
Fixed coefficient table for 6-tap filter with 12 coefficients per phase.
Fixed coefficient table for 6-tap filter with 12 coefficients per phase.This table contains a 64-phase, 6-tap FIR filter bank for vertical and horizontal scaling. The 12-coefficient format includes zero-padding to match hardware requirements. Each row represents one of 64 interpolation phases, allowing smooth sub-pixel precision during scaling operations.Format: [XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12] Phases: 64 Active taps: 6 (with padding zeros)
const short XV_multiscaler_fixedcoeff_taps8_8C[XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_8][XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_8]
Fixed coefficient table for 8-tap filter with 8 coefficients per phase.
Fixed coefficient table for 8-tap filter with 8 coefficients per phase.This table contains a 64-phase, 8-tap FIR filter bank in compact format without padding zeros. Optimized for hardware that supports exactly 8 coefficients per phase.Format: [XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_8] Phases: 64 Active taps: 8
const short XV_multiscaler_fixedcoeff_taps8_12C[XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12][XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12]
Fixed coefficient table for 8-tap filter with 12 coefficients per phase.
Fixed coefficient table for 8-tap filter with 12 coefficients per phase.This table contains a 64-phase, 8-tap FIR filter bank providing higher quality scaling compared to 6-tap filters. The 12-coefficient format includes zero-padding for hardware alignment. 8-tap filters offer improved frequency response and reduced aliasing artifacts.Format: [XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12] Phases: 64 Active taps: 8 (with padding zeros)
const short XV_multiscaler_fixedcoeff_taps10_10C[XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_10][XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_10]
Fixed coefficient table for 10-tap filter with 10 coefficients per phase.
Fixed coefficient table for 10-tap filter with 10 coefficients per phase.This table contains a 64-phase, 10-tap FIR filter bank in compact format without padding zeros. Optimized for hardware that supports exactly 10 coefficients per phase.Format: [XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_10] Phases: 64 Active taps: 10
const short XV_multiscaler_fixedcoeff_taps10_12C[XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12][XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12]
Fixed coefficient table for 10-tap filter with 12 coefficients per phase.
Fixed coefficient table for 10-tap filter with 12 coefficients per phase.This table contains a 64-phase, 10-tap FIR filter bank offering superior scaling quality. The 12-coefficient format includes minimal padding. 10-tap filters provide excellent frequency response characteristics and minimal ringing artifacts, suitable for professional image processing.Format: [XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12] Phases: 64 Active taps: 10 (with minimal padding)
const short XV_multiscaler_fixedcoeff_taps12_12C[XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12][XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12]
Fixed coefficient table for 12-tap filter with 12 coefficients per phase.
Fixed coefficient table for 12-tap filter with 12 coefficients per phase.This table contains a 64-phase, 12-tap FIR filter bank providing the highest quality scaling among all supported tap configurations. With no padding required, all 12 coefficients are active. 12-tap filters deliver exceptional frequency response, minimal aliasing, and superior image quality for demanding applications.Format: [XV_MULTISCALER_MAX_V_PHASES][XV_MULTISCALER_TAPS_12] Phases: 64 Active taps: 12
void XV_MultiScalerStart(XV_multi_scaler *InstancePtr)
Start the multi scaler core operation.
This function enables auto-restart mode and starts the multi scaler core. It validates that the number of outputs is configured correctly and that all output channels specified by the output bit mask are properly configured. InstancePtr is a pointer to the core instance to be worked on. None None
References XV_multi_scaler::OutBitMask, XV_MAX_OUTS, XV_multi_scaler_EnableAutoRestart, XV_multi_scaler_Get_HwReg_num_outs, XV_multi_scaler_Start, XV_MULTISCALER_OUTPUT_MASK.
Referenced by main.
void XV_MultiScalerStop(XV_multi_scaler *InstancePtr)
Stop the multi scaler core operation.
This function disables auto-restart mode on the multi scaler core, effectively stopping its operation after the current frame completes. InstancePtr is a pointer to the core instance to be worked on. None None
References XV_multi_scaler_DisableAutoRestart.
Referenced by XVMultiScalerCallback.
u32 XV_MultiScalerGetNumOutputs(XV_multi_scaler *InstancePtr)
Get the number of output channels configured.
This function retrieves the current number of output channels that are configured for the multi scaler core. InstancePtr is a pointer to the core instance to be worked on. Number of configured output channels (u32). None
References XV_multi_scaler_Get_HwReg_num_outs.
Referenced by main.
void XV_MultiScalerSetNumOutputs(XV_multi_scaler *InstancePtr, u32 NumOuts)
Set the number of output channels to be used.
This function configures the number of output channels for the multi scaler core. The number must be between 1 and the maximum number of outputs supported by the hardware instance. The output bit mask is reset when this function is called. InstancePtr is a pointer to the core instance to be worked on. NumOuts is the number of output channels to configure. None NumOuts must be greater than 0 and less than or equal to MaxOuts.
References XV_multi_scaler::OutBitMask, XV_multi_scaler_Set_HwReg_num_outs.
Referenced by main.
void XV_MultiScalerGetChannelConfig(XV_multi_scaler *InstancePtr, XV_multi_scaler_Video_Config *MS_cfg)
Read the configuration of a specific channel.
This function retrieves the current configuration settings for a specified output channel. The application must set the ChannelId field in the MS_cfg structure before calling this function. The function reads all channel parameters including dimensions, color formats, strides, and buffer addresses. InstancePtr is a pointer to the core instance to be worked on. MS_cfg is a pointer to the multi scaler config structure. The ChannelId field must be pre-filled by the application. None The ChannelId in MS_cfg must be set before calling this function.
References XV_multi_scaler_Video_Config::ChannelId, XV_multi_scaler_Video_Config::ColorFormatIn, XV_multi_scaler_Video_Config::ColorFormatOut, XV_multi_scaler_Video_Config::DstImgBuf0, XV_multi_scaler_Video_Config::DstImgBuf1, XV_multi_scaler_Video_Config::HeightIn, XV_multi_scaler_Video_Config::HeightOut, XV_multi_scaler_Video_Config::InStride, XV_multi_scaler_Video_Config::OutStride, XV_multi_scaler::SamplesPerClock, XV_multi_scaler_Video_Config::SrcImgBuf0, XV_multi_scaler_Video_Config::SrcImgBuf1, XV_multi_scaler_Video_Config::WidthIn, XV_multi_scaler_Video_Config::WidthOut.
void XV_MultiScalerSetChannelConfig(XV_multi_scaler *InstancePtr, XV_multi_scaler_Video_Config *MS_cfg)
Configure a channel with the specified scaling parameters.
This function programs all configuration parameters for a specific output channel including input/output dimensions, color formats, strides, buffer addresses, and scaling rates. It also handles optional cropping window configuration and automatically programs the appropriate filter coefficients based on the scaling ratio. Extensive validation is performed on all parameters to ensure valid configuration. InstancePtr is a pointer to the core instance to be worked on. MS_cfg is a pointer to the multi scaler config structure containing all channel configuration parameters. None All configuration parameters are validated via assertions. Buffer addresses must not overlap to prevent data corruption.
References XV_multi_scaler_Video_Config::ChannelId, XV_multi_scaler_Video_Config::ColorFormatIn, XV_multi_scaler_Video_Config::ColorFormatOut, XV_multi_scaler_Crop_Window::Crop, XV_multi_scaler_Video_Config::CropWin, XV_multi_scaler_Video_Config::DstImgBuf0, XV_multi_scaler_Video_Config::DstImgBuf1, XV_multi_scaler_Crop_Window::Height, XV_multi_scaler_Video_Config::HeightIn, XV_multi_scaler_Video_Config::HeightOut, XV_multi_scaler_Video_Config::InStride, XV_multi_scaler::MaxCols, XV_multi_scaler::MaxRows, XV_multi_scaler::OutBitMask, XV_multi_scaler_Video_Config::OutStride, XV_multi_scaler::SamplesPerClock, XV_multi_scaler_Video_Config::SrcImgBuf0, XV_multi_scaler_Video_Config::SrcImgBuf1, XV_multi_scaler_Crop_Window::StartX, XV_multi_scaler_Crop_Window::StartY, STEP_PRECISION, XV_multi_scaler_Crop_Window::Width, XV_multi_scaler_Video_Config::WidthIn, XV_multi_scaler_Video_Config::WidthOut, XV_MULTI_SCALER_BGR8, XV_MULTI_SCALER_RGB8, XV_MULTI_SCALER_UYVY8, XV_MULTI_SCALER_Y10, XV_MULTI_SCALER_Y8, XV_MULTI_SCALER_Y_UV10, XV_MULTI_SCALER_Y_UV10_420, XV_MULTI_SCALER_Y_UV8, XV_MULTI_SCALER_Y_UV8_420, XV_MULTI_SCALER_YUV8, XV_MULTI_SCALER_YUYV8.
Referenced by main.