xv_multi_scaler.h
XV_MAX_OUTS
Maximum number of output channels supported.
Referenced by XV_MultiScalerStart.
XV_MULTI_SCALER_CLEAR_BIT_MASK
Clear all status bits.
XV_MULTI_SCALER_AP_START_BIT_MASK
AP control start bit mask.
Referenced by XV_multi_scaler_IsReady, XV_multi_scaler_Start.
XV_MULTI_SCALER_AP_DONE_OFFSET
AP done status bit offset.
XV_MULTI_SCALER_AP_DONE_BIT_MASK
AP done status bit mask.
Referenced by XV_multi_scaler_IsDone.
XV_MULTI_SCALER_AP_IDLE_OFFSET
AP idle status bit offset.
XV_MULTI_SCALER_AP_IDLE_BIT_MASK
AP idle status bit mask.
Referenced by XV_multi_scaler_IsIdle.
XV_MULTI_SCALER_AP_READY_OFFSET
AP ready status bit offset.
XV_MULTI_SCALER_AP_READY_BIT_MASK
AP ready status bit mask.
XV_MULTI_SCALER_AP_AUTO_RESTART_OFFSET
AP auto-restart control bit offset.
XV_MULTI_SCALER_AP_AUTO_RESTART_BIT_MASK
AP auto-restart control bit mask.
Referenced by XV_multi_scaler_EnableAutoRestart, XV_multi_scaler_Start.
XV_MULTI_SCALER_ISR_DONE_BIT_MASK
Interrupt status register done bit mask.
Referenced by XV_MultiScalerIntrHandler.
XV_MULTI_SCALER_ISR_READY_OFFSET
Interrupt status register ready bit offset.
XV_MULTI_SCALER_ISR_READY_BIT_MASK
Interrupt status register ready bit mask.
Referenced by XV_MultiScalerIntrHandler.
XV_MULTI_SCALER_WIDTH_IN
Macro to generate function name for setting input width of channel x.
XV_MULTI_SCALER_WIDTH_OUT
Macro to generate function name for setting output width of channel x.
XV_MULTI_SCALER_HEIGHT_IN
Macro to generate function name for setting input height of channel x.
XV_MULTI_SCALER_HEIGHT_OUT
Macro to generate function name for setting output height of channel x.
XV_MULTI_SCALER_STRIDE_IN
Macro to generate function name for setting input stride of channel x.
XV_MULTI_SCALER_STRIDE_OUT
Macro to generate function name for setting output stride of channel x.
XV_MULTI_SCALER_LINE_RATE
Macro to generate function name for setting line rate of channel x.
XV_MULTI_SCALER_PIXEL_RATE
Macro to generate function name for setting pixel rate of channel x.
XV_MULTI_SCALER_IN_PIXEL_FMT
Macro to generate function name for setting input pixel format of channel x.
XV_MULTI_SCALER_OUT_PIXEL_FMT
Macro to generate function name for setting output pixel format of channel x.
XV_MULTI_SCALER_SRC_IMG_BUF_0
Macro to generate function name for setting source image buffer 0 of channel x.
XV_MULTI_SCALER_SRC_IMG_BUF_1
Macro to generate function name for setting source image buffer 1 of channel x.
XV_MULTI_SCALER_DST_IMG_BUF_0
Macro to generate function name for setting destination image buffer 0 of channel x.
XV_MULTI_SCALER_DST_IMG_BUF_1
Macro to generate function name for setting destination image buffer 1 of channel x.
XV_multi_scaler_WriteReg
Macro to write a 32-bit value to a register at the specified offset.
Referenced by XV_multi_scaler_DisableAutoRestart, XV_multi_scaler_EnableAutoRestart, XV_multi_scaler_InterruptClear, XV_multi_scaler_InterruptDisable, XV_multi_scaler_InterruptEnable, XV_multi_scaler_InterruptGlobalDisable, XV_multi_scaler_InterruptGlobalEnable, XV_multi_scaler_Set_HwReg_dstImgBuf0_0_V, XV_multi_scaler_Set_HwReg_dstImgBuf0_1_V, XV_multi_scaler_Set_HwReg_dstImgBuf0_2_V, XV_multi_scaler_Set_HwReg_dstImgBuf0_3_V, XV_multi_scaler_Set_HwReg_dstImgBuf0_4_V, XV_multi_scaler_Set_HwReg_dstImgBuf0_5_V, XV_multi_scaler_Set_HwReg_dstImgBuf0_6_V, XV_multi_scaler_Set_HwReg_dstImgBuf0_7_V, XV_multi_scaler_Set_HwReg_dstImgBuf1_0_V, XV_multi_scaler_Set_HwReg_dstImgBuf1_1_V, XV_multi_scaler_Set_HwReg_dstImgBuf1_2_V, XV_multi_scaler_Set_HwReg_dstImgBuf1_3_V, XV_multi_scaler_Set_HwReg_dstImgBuf1_4_V, XV_multi_scaler_Set_HwReg_dstImgBuf1_5_V, XV_multi_scaler_Set_HwReg_dstImgBuf1_6_V, XV_multi_scaler_Set_HwReg_dstImgBuf1_7_V, XV_multi_scaler_Set_HwReg_HeightIn_0, XV_multi_scaler_Set_HwReg_HeightIn_1, XV_multi_scaler_Set_HwReg_HeightIn_2, XV_multi_scaler_Set_HwReg_HeightIn_3, XV_multi_scaler_Set_HwReg_HeightIn_4, XV_multi_scaler_Set_HwReg_HeightIn_5, XV_multi_scaler_Set_HwReg_HeightIn_6, XV_multi_scaler_Set_HwReg_HeightIn_7, XV_multi_scaler_Set_HwReg_HeightOut_0, XV_multi_scaler_Set_HwReg_HeightOut_1, XV_multi_scaler_Set_HwReg_HeightOut_2, XV_multi_scaler_Set_HwReg_HeightOut_3, XV_multi_scaler_Set_HwReg_HeightOut_4, XV_multi_scaler_Set_HwReg_HeightOut_5, XV_multi_scaler_Set_HwReg_HeightOut_6, XV_multi_scaler_Set_HwReg_HeightOut_7, XV_multi_scaler_Set_HwReg_InPixelFmt_0, XV_multi_scaler_Set_HwReg_InPixelFmt_1, XV_multi_scaler_Set_HwReg_InPixelFmt_2, XV_multi_scaler_Set_HwReg_InPixelFmt_3, XV_multi_scaler_Set_HwReg_InPixelFmt_4, XV_multi_scaler_Set_HwReg_InPixelFmt_5, XV_multi_scaler_Set_HwReg_InPixelFmt_6, XV_multi_scaler_Set_HwReg_InPixelFmt_7, XV_multi_scaler_Set_HwReg_InStride_0, XV_multi_scaler_Set_HwReg_InStride_1, XV_multi_scaler_Set_HwReg_InStride_2, XV_multi_scaler_Set_HwReg_InStride_3, XV_multi_scaler_Set_HwReg_InStride_4, XV_multi_scaler_Set_HwReg_InStride_5, XV_multi_scaler_Set_HwReg_InStride_6, XV_multi_scaler_Set_HwReg_InStride_7, XV_multi_scaler_Set_HwReg_LineRate_0, XV_multi_scaler_Set_HwReg_LineRate_1, XV_multi_scaler_Set_HwReg_LineRate_2, XV_multi_scaler_Set_HwReg_LineRate_3, XV_multi_scaler_Set_HwReg_LineRate_4, XV_multi_scaler_Set_HwReg_LineRate_5, XV_multi_scaler_Set_HwReg_LineRate_6, XV_multi_scaler_Set_HwReg_LineRate_7, XV_multi_scaler_Set_HwReg_num_outs, XV_multi_scaler_Set_HwReg_OutPixelFmt_0, XV_multi_scaler_Set_HwReg_OutPixelFmt_1, XV_multi_scaler_Set_HwReg_OutPixelFmt_2, XV_multi_scaler_Set_HwReg_OutPixelFmt_3, XV_multi_scaler_Set_HwReg_OutPixelFmt_4, XV_multi_scaler_Set_HwReg_OutPixelFmt_5, XV_multi_scaler_Set_HwReg_OutPixelFmt_6, XV_multi_scaler_Set_HwReg_OutPixelFmt_7, XV_multi_scaler_Set_HwReg_OutStride_0, XV_multi_scaler_Set_HwReg_OutStride_1, XV_multi_scaler_Set_HwReg_OutStride_2, XV_multi_scaler_Set_HwReg_OutStride_3, XV_multi_scaler_Set_HwReg_OutStride_4, XV_multi_scaler_Set_HwReg_OutStride_5, XV_multi_scaler_Set_HwReg_OutStride_6, XV_multi_scaler_Set_HwReg_OutStride_7, XV_multi_scaler_Set_HwReg_PixelRate_0, XV_multi_scaler_Set_HwReg_PixelRate_1, XV_multi_scaler_Set_HwReg_PixelRate_2, XV_multi_scaler_Set_HwReg_PixelRate_3, XV_multi_scaler_Set_HwReg_PixelRate_4, XV_multi_scaler_Set_HwReg_PixelRate_5, XV_multi_scaler_Set_HwReg_PixelRate_6, XV_multi_scaler_Set_HwReg_PixelRate_7, XV_multi_scaler_Set_HwReg_srcImgBuf0_0_V, XV_multi_scaler_Set_HwReg_srcImgBuf0_1_V, XV_multi_scaler_Set_HwReg_srcImgBuf0_2_V, XV_multi_scaler_Set_HwReg_srcImgBuf0_3_V, XV_multi_scaler_Set_HwReg_srcImgBuf0_4_V, XV_multi_scaler_Set_HwReg_srcImgBuf0_5_V, XV_multi_scaler_Set_HwReg_srcImgBuf0_6_V, XV_multi_scaler_Set_HwReg_srcImgBuf0_7_V, XV_multi_scaler_Set_HwReg_srcImgBuf1_0_V, XV_multi_scaler_Set_HwReg_srcImgBuf1_1_V, XV_multi_scaler_Set_HwReg_srcImgBuf1_2_V, XV_multi_scaler_Set_HwReg_srcImgBuf1_3_V, XV_multi_scaler_Set_HwReg_srcImgBuf1_4_V, XV_multi_scaler_Set_HwReg_srcImgBuf1_5_V, XV_multi_scaler_Set_HwReg_srcImgBuf1_6_V, XV_multi_scaler_Set_HwReg_srcImgBuf1_7_V, XV_multi_scaler_Set_HwReg_WidthIn_0, XV_multi_scaler_Set_HwReg_WidthIn_1, XV_multi_scaler_Set_HwReg_WidthIn_2, XV_multi_scaler_Set_HwReg_WidthIn_3, XV_multi_scaler_Set_HwReg_WidthIn_4, XV_multi_scaler_Set_HwReg_WidthIn_5, XV_multi_scaler_Set_HwReg_WidthIn_6, XV_multi_scaler_Set_HwReg_WidthIn_7, XV_multi_scaler_Set_HwReg_WidthOut_0, XV_multi_scaler_Set_HwReg_WidthOut_1, XV_multi_scaler_Set_HwReg_WidthOut_2, XV_multi_scaler_Set_HwReg_WidthOut_3, XV_multi_scaler_Set_HwReg_WidthOut_4, XV_multi_scaler_Set_HwReg_WidthOut_5, XV_multi_scaler_Set_HwReg_WidthOut_6, XV_multi_scaler_Set_HwReg_WidthOut_7, XV_multi_scaler_Start, XV_Reset_MultiScaler.
XV_multi_scaler_ReadReg
Macro to read a 32-bit value from a register at the specified offset.
Referenced by XV_multi_scaler_Get_HwReg_dstImgBuf0_0_V, XV_multi_scaler_Get_HwReg_dstImgBuf0_1_V, XV_multi_scaler_Get_HwReg_dstImgBuf0_2_V, XV_multi_scaler_Get_HwReg_dstImgBuf0_3_V, XV_multi_scaler_Get_HwReg_dstImgBuf0_4_V, XV_multi_scaler_Get_HwReg_dstImgBuf0_5_V, XV_multi_scaler_Get_HwReg_dstImgBuf0_6_V, XV_multi_scaler_Get_HwReg_dstImgBuf0_7_V, XV_multi_scaler_Get_HwReg_dstImgBuf1_0_V, XV_multi_scaler_Get_HwReg_dstImgBuf1_1_V, XV_multi_scaler_Get_HwReg_dstImgBuf1_2_V, XV_multi_scaler_Get_HwReg_dstImgBuf1_3_V, XV_multi_scaler_Get_HwReg_dstImgBuf1_4_V, XV_multi_scaler_Get_HwReg_dstImgBuf1_5_V, XV_multi_scaler_Get_HwReg_dstImgBuf1_6_V, XV_multi_scaler_Get_HwReg_dstImgBuf1_7_V, XV_multi_scaler_Get_HwReg_HeightIn_0, XV_multi_scaler_Get_HwReg_HeightIn_1, XV_multi_scaler_Get_HwReg_HeightIn_2, XV_multi_scaler_Get_HwReg_HeightIn_3, XV_multi_scaler_Get_HwReg_HeightIn_4, XV_multi_scaler_Get_HwReg_HeightIn_5, XV_multi_scaler_Get_HwReg_HeightIn_6, XV_multi_scaler_Get_HwReg_HeightIn_7, XV_multi_scaler_Get_HwReg_HeightOut_0, XV_multi_scaler_Get_HwReg_HeightOut_1, XV_multi_scaler_Get_HwReg_HeightOut_2, XV_multi_scaler_Get_HwReg_HeightOut_3, XV_multi_scaler_Get_HwReg_HeightOut_4, XV_multi_scaler_Get_HwReg_HeightOut_5, XV_multi_scaler_Get_HwReg_HeightOut_6, XV_multi_scaler_Get_HwReg_HeightOut_7, XV_multi_scaler_Get_HwReg_InPixelFmt_0, XV_multi_scaler_Get_HwReg_InPixelFmt_1, XV_multi_scaler_Get_HwReg_InPixelFmt_2, XV_multi_scaler_Get_HwReg_InPixelFmt_3, XV_multi_scaler_Get_HwReg_InPixelFmt_4, XV_multi_scaler_Get_HwReg_InPixelFmt_5, XV_multi_scaler_Get_HwReg_InPixelFmt_6, XV_multi_scaler_Get_HwReg_InPixelFmt_7, XV_multi_scaler_Get_HwReg_InStride_0, XV_multi_scaler_Get_HwReg_InStride_1, XV_multi_scaler_Get_HwReg_InStride_2, XV_multi_scaler_Get_HwReg_InStride_3, XV_multi_scaler_Get_HwReg_InStride_4, XV_multi_scaler_Get_HwReg_InStride_5, XV_multi_scaler_Get_HwReg_InStride_6, XV_multi_scaler_Get_HwReg_InStride_7, XV_multi_scaler_Get_HwReg_LineRate_0, XV_multi_scaler_Get_HwReg_LineRate_1, XV_multi_scaler_Get_HwReg_LineRate_2, XV_multi_scaler_Get_HwReg_LineRate_3, XV_multi_scaler_Get_HwReg_LineRate_4, XV_multi_scaler_Get_HwReg_LineRate_5, XV_multi_scaler_Get_HwReg_LineRate_6, XV_multi_scaler_Get_HwReg_LineRate_7, XV_multi_scaler_Get_HwReg_num_outs, XV_multi_scaler_Get_HwReg_OutPixelFmt_0, XV_multi_scaler_Get_HwReg_OutPixelFmt_1, XV_multi_scaler_Get_HwReg_OutPixelFmt_2, XV_multi_scaler_Get_HwReg_OutPixelFmt_3, XV_multi_scaler_Get_HwReg_OutPixelFmt_4, XV_multi_scaler_Get_HwReg_OutPixelFmt_5, XV_multi_scaler_Get_HwReg_OutPixelFmt_6, XV_multi_scaler_Get_HwReg_OutPixelFmt_7, XV_multi_scaler_Get_HwReg_OutStride_0, XV_multi_scaler_Get_HwReg_OutStride_1, XV_multi_scaler_Get_HwReg_OutStride_2, XV_multi_scaler_Get_HwReg_OutStride_3, XV_multi_scaler_Get_HwReg_OutStride_4, XV_multi_scaler_Get_HwReg_OutStride_5, XV_multi_scaler_Get_HwReg_OutStride_6, XV_multi_scaler_Get_HwReg_OutStride_7, XV_multi_scaler_Get_HwReg_PixelRate_0, XV_multi_scaler_Get_HwReg_PixelRate_1, XV_multi_scaler_Get_HwReg_PixelRate_2, XV_multi_scaler_Get_HwReg_PixelRate_3, XV_multi_scaler_Get_HwReg_PixelRate_4, XV_multi_scaler_Get_HwReg_PixelRate_5, XV_multi_scaler_Get_HwReg_PixelRate_6, XV_multi_scaler_Get_HwReg_PixelRate_7, XV_multi_scaler_Get_HwReg_srcImgBuf0_0_V, XV_multi_scaler_Get_HwReg_srcImgBuf0_1_V, XV_multi_scaler_Get_HwReg_srcImgBuf0_2_V, XV_multi_scaler_Get_HwReg_srcImgBuf0_3_V, XV_multi_scaler_Get_HwReg_srcImgBuf0_4_V, XV_multi_scaler_Get_HwReg_srcImgBuf0_5_V, XV_multi_scaler_Get_HwReg_srcImgBuf0_6_V, XV_multi_scaler_Get_HwReg_srcImgBuf0_7_V, XV_multi_scaler_Get_HwReg_srcImgBuf1_0_V, XV_multi_scaler_Get_HwReg_srcImgBuf1_1_V, XV_multi_scaler_Get_HwReg_srcImgBuf1_2_V, XV_multi_scaler_Get_HwReg_srcImgBuf1_3_V, XV_multi_scaler_Get_HwReg_srcImgBuf1_4_V, XV_multi_scaler_Get_HwReg_srcImgBuf1_5_V, XV_multi_scaler_Get_HwReg_srcImgBuf1_6_V, XV_multi_scaler_Get_HwReg_srcImgBuf1_7_V, XV_multi_scaler_Get_HwReg_WidthIn_0, XV_multi_scaler_Get_HwReg_WidthIn_1, XV_multi_scaler_Get_HwReg_WidthIn_2, XV_multi_scaler_Get_HwReg_WidthIn_3, XV_multi_scaler_Get_HwReg_WidthIn_4, XV_multi_scaler_Get_HwReg_WidthIn_5, XV_multi_scaler_Get_HwReg_WidthIn_6, XV_multi_scaler_Get_HwReg_WidthIn_7, XV_multi_scaler_Get_HwReg_WidthOut_0, XV_multi_scaler_Get_HwReg_WidthOut_1, XV_multi_scaler_Get_HwReg_WidthOut_2, XV_multi_scaler_Get_HwReg_WidthOut_3, XV_multi_scaler_Get_HwReg_WidthOut_4, XV_multi_scaler_Get_HwReg_WidthOut_5, XV_multi_scaler_Get_HwReg_WidthOut_6, XV_multi_scaler_Get_HwReg_WidthOut_7, XV_multi_scaler_InterruptDisable, XV_multi_scaler_InterruptEnable, XV_multi_scaler_InterruptGetEnabled, XV_multi_scaler_InterruptGetStatus, XV_multi_scaler_IsDone, XV_multi_scaler_IsIdle, XV_multi_scaler_IsReady, XV_multi_scaler_Start.
typedef void(* XVMultiScaler_Callback)(void *CallbackRef))(void *CallbackRef)
Multi Scaler callback function type.
XV_multi_scaler_Config XV_multi_scaler_ConfigTable[][]
Configuration table for multi-scaler devices.
Configuration table for multi-scaler devices.This table contains the configuration information for each MultiScaler device in the system. Each entry includes: Device ID: Unique identifier for the device instanceBase Address: AXI control interface base addressSamples Per Clock: Number of samples processed per clock cycleMax Data Width: Maximum pixel data width supportedMax Cols: Maximum number of horizontal pixelsMax Rows: Maximum number of vertical pixelsPhase Shift: Scaling phase shift precisionScale Mode: Supported scaling modes (bilinear, polyphase, etc.)Taps: Number of filter taps for polyphase scalingMax Outs: Maximum number of output channels supported The table is indexed by device ID for lookup during initialization.
Referenced by XV_multi_scaler_LookupConfig.
int XV_multi_scaler_Initialize(XV_multi_scaler *InstancePtr, UINTPTR BaseAddress)
Initialize the Multi Scaler driver instance using base address.
This function locates the device configuration based on the base address and calls the configuration initialization function. The instance must be initialized before using any other driver functions. The base address is typically obtained from the device tree. InstancePtr is a pointer to the Multi Scaler instance to be initialized. BaseAddress is the physical base address of the device. XST_SUCCESS if initialization was successful, XST_DEVICE_NOT_FOUND if the configuration for the base address was not found. This function is used in SDT (Software Development Toolkit) builds.
References XV_multi_scaler::IsReady, XV_multi_scaler_CfgInitialize, XV_multi_scaler_LookupConfig.
Referenced by main.
XV_multi_scaler_Config* XV_multi_scaler_LookupConfig(UINTPTR BaseAddress)
Lookup the device configuration by base address.
This function searches the configuration table for a device matching the specified base address. The configuration table is populated at compile time based on the device tree configuration. If BaseAddress is 0, the first entry in the table is returned. BaseAddress is the physical base address of the device. If 0, returns the first configuration entry. Pointer to the configuration structure if found, NULL otherwise. This function is used in SDT (Software Development Toolkit) builds.
References XV_multi_scaler_Config::Name, XV_multi_scaler_ConfigTable.
Referenced by XV_multi_scaler_Initialize.
int XV_multi_scaler_CfgInitialize(XV_multi_scaler *InstancePtr, XV_multi_scaler_Config *ConfigPtr)
Initialize the Multi Scaler core instance.
This function initializes the Multi Scaler driver/device instance with the configuration parameters from the provided config structure. It copies configuration parameters and sets the instance to ready state. InstancePtr is a pointer to the Multi Scaler instance to be worked on ConfigPtr is a pointer to the configuration structure containing hardware build-time parameters XST_SUCCESS if initialization was successful The calling application must memset the instance structure to zero before passing it to this function
References XV_multi_scaler::Config, XV_multi_scaler_Config::Ctrl_BaseAddress, XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler_Config::IntrId, XV_multi_scaler_Config::IntrParent, XV_multi_scaler::IsReady, XV_multi_scaler_Config::MaxCols, XV_multi_scaler::MaxCols, XV_multi_scaler_Config::MaxDataWidth, XV_multi_scaler::MaxDataWidth, XV_multi_scaler_Config::MaxOuts, XV_multi_scaler::MaxOuts, XV_multi_scaler_Config::MaxRows, XV_multi_scaler::MaxRows, XV_multi_scaler_Config::NumTaps, XV_multi_scaler::NumTaps, XV_multi_scaler_Config::PhaseShift, XV_multi_scaler::PhaseShift, XV_multi_scaler_Config::SamplesPerClock, XV_multi_scaler::SamplesPerClock, XV_multi_scaler_Config::ScaleMode, XV_multi_scaler::ScaleMode.
Referenced by XV_multi_scaler_Initialize.
void XV_multi_scaler_Start(XV_multi_scaler *InstancePtr)
Start the Multi Scaler core.
This function starts the Multi Scaler hardware by setting the AP_START bit in the control register. Auto-restart mode is preserved if previously set. InstancePtr is a pointer to the Multi Scaler instance None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_AP_AUTO_RESTART_BIT_MASK, XV_MULTI_SCALER_AP_START_BIT_MASK, XV_MULTI_SCALER_CTRL_ADDR_AP_CTRL, XV_multi_scaler_ReadReg, XV_multi_scaler_WriteReg.
Referenced by XV_MultiScalerStart.
u32 XV_multi_scaler_IsDone(XV_multi_scaler *InstancePtr)
Check if Multi Scaler processing is done.
This function checks the AP_DONE bit in the control register to determine if the Multi Scaler has completed the current frame processing. InstancePtr is a pointer to the Multi Scaler instance Non-zero if the core has finished processing the current frame, zero otherwise
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_AP_DONE_BIT_MASK, XV_MULTI_SCALER_CTRL_ADDR_AP_CTRL, XV_multi_scaler_ReadReg.
u32 XV_multi_scaler_IsIdle(XV_multi_scaler *InstancePtr)
Check if Multi Scaler is idle.
This function checks the AP_IDLE bit in the control register to determine if the Multi Scaler hardware is currently idle (not processing). InstancePtr is a pointer to the Multi Scaler instance Non-zero if the core is idle, zero if it is actively processing
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_AP_IDLE_BIT_MASK, XV_MULTI_SCALER_CTRL_ADDR_AP_CTRL, XV_multi_scaler_ReadReg.
u32 XV_multi_scaler_IsReady(XV_multi_scaler *InstancePtr)
Check if Multi Scaler is ready for next operation.
This function checks if the Multi Scaler is ready to accept new input by verifying that the AP_START bit is not set in the control register. InstancePtr is a pointer to the Multi Scaler instance Non-zero if the core is ready for next input, zero otherwise
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_AP_START_BIT_MASK, XV_MULTI_SCALER_CTRL_ADDR_AP_CTRL, XV_multi_scaler_ReadReg.
void XV_multi_scaler_EnableAutoRestart(XV_multi_scaler *InstancePtr)
Enable auto-restart mode for Multi Scaler.
This function enables the auto-restart feature, allowing the Multi Scaler to automatically restart processing after completing the current frame. InstancePtr is a pointer to the Multi Scaler instance None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_AP_AUTO_RESTART_BIT_MASK, XV_MULTI_SCALER_CTRL_ADDR_AP_CTRL, XV_multi_scaler_WriteReg.
Referenced by XV_MultiScalerStart.
void XV_multi_scaler_DisableAutoRestart(XV_multi_scaler *InstancePtr)
Disable auto-restart mode for Multi Scaler.
This function disables the auto-restart feature, requiring manual restart after each frame processing operation completes. InstancePtr is a pointer to the Multi Scaler instance None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_AP_CTRL, XV_multi_scaler_WriteReg.
Referenced by XV_MultiScalerStop.
void XV_multi_scaler_Set_HwReg_num_outs(XV_multi_scaler *InstancePtr, u32 Data)
Set the number of output channels.
This function writes the number of active output channels to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the number of output channels to configure None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_NUM_OUTS_DATA, XV_multi_scaler_WriteReg.
Referenced by XV_MultiScalerSetNumOutputs.
u32 XV_multi_scaler_Get_HwReg_num_outs(XV_multi_scaler *InstancePtr)
Get the number of output channels.
This function reads the number of active output channels from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The number of output channels currently configured
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_NUM_OUTS_DATA, XV_multi_scaler_ReadReg.
Referenced by XV_MultiScalerGetNumOutputs, XV_MultiScalerStart.
void XV_multi_scaler_Set_HwReg_WidthIn_0(XV_multi_scaler *InstancePtr, u32 Data)
Set input width for channel 0.
This function writes the input image width for channel 0 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the input image width in pixels None Similar Set/Get functions exist for all 8 channels (0-7) and follow the same pattern for Width, Height, Stride, Rate, Format, and Buffer address parameters
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_WIDTHIN_0_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_WidthIn_0(XV_multi_scaler *InstancePtr)
Get input width for channel 0.
This function reads the input image width for channel 0 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The input image width in pixels
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_WIDTHIN_0_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_WidthOut_0(XV_multi_scaler *InstancePtr, u32 Data)
Set output width for channel 0.
This function writes the output image width for channel 0 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the output image width in pixels None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_WIDTHOUT_0_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_WidthOut_0(XV_multi_scaler *InstancePtr)
Get output width for channel 0.
This function reads the output image width for channel 0 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The output image width in pixels None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_WIDTHOUT_0_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_HeightIn_0(XV_multi_scaler *InstancePtr, u32 Data)
Set input height for channel 0.
This function writes the input image height for channel 0 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the input image height in pixels None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_HEIGHTIN_0_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_HeightIn_0(XV_multi_scaler *InstancePtr)
Get input height for channel 0.
This function reads the input image height for channel 0 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The input image height in pixels None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_HEIGHTIN_0_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_HeightOut_0(XV_multi_scaler *InstancePtr, u32 Data)
Set output height for channel 0.
This function writes the output image height for channel 0 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the output image height in pixels None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_HEIGHTOUT_0_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_HeightOut_0(XV_multi_scaler *InstancePtr)
Get output height for channel 0.
This function reads the output image height for channel 0 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The output image height in pixels None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_HEIGHTOUT_0_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_LineRate_0(XV_multi_scaler *InstancePtr, u32 Data)
Set line rate for channel 0.
This function writes the line processing rate for channel 0 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the line rate value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_LINERATE_0_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_LineRate_0(XV_multi_scaler *InstancePtr)
Get line rate for channel 0.
This function reads the line processing rate for channel 0 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The line rate value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_LINERATE_0_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_PixelRate_0(XV_multi_scaler *InstancePtr, u32 Data)
Set pixel rate for channel 0.
This function writes the pixel processing rate for channel 0 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the pixel rate value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_PIXELRATE_0_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_PixelRate_0(XV_multi_scaler *InstancePtr)
Get pixel rate for channel 0.
This function reads the pixel processing rate for channel 0 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The pixel rate value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_PIXELRATE_0_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_InPixelFmt_0(XV_multi_scaler *InstancePtr, u32 Data)
Set input pixel format for channel 0.
This function writes the input pixel format for channel 0 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the input pixel format value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_INPIXELFMT_0_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_InPixelFmt_0(XV_multi_scaler *InstancePtr)
Get input pixel format for channel 0.
This function reads the input pixel format for channel 0 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The input pixel format value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_INPIXELFMT_0_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_OutPixelFmt_0(XV_multi_scaler *InstancePtr, u32 Data)
Set output pixel format for channel 0.
This function writes the output pixel format for channel 0 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the output pixel format value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_OUTPIXELFMT_0_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_OutPixelFmt_0(XV_multi_scaler *InstancePtr)
Get output pixel format for channel 0.
This function reads the output pixel format for channel 0 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The output pixel format value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_OUTPIXELFMT_0_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_InStride_0(XV_multi_scaler *InstancePtr, u32 Data)
Set input stride for channel 0.
This function writes the input buffer stride for channel 0 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the input stride value in bytes None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_INSTRIDE_0_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_InStride_0(XV_multi_scaler *InstancePtr)
Get input stride for channel 0.
This function reads the input buffer stride for channel 0 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The input stride value in bytes None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_INSTRIDE_0_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_OutStride_0(XV_multi_scaler *InstancePtr, u32 Data)
Set output stride for channel 0.
This function writes the output buffer stride for channel 0 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the output stride value in bytes None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_OUTSTRIDE_0_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_OutStride_0(XV_multi_scaler *InstancePtr)
Get output stride for channel 0.
This function reads the output buffer stride for channel 0 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The output stride value in bytes None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_OUTSTRIDE_0_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_srcImgBuf0_0_V(XV_multi_scaler *InstancePtr, u64 Data)
Set source image buffer 0 address for channel 0.
This function writes the 64-bit address of source image buffer 0 for channel 0 to the hardware registers. InstancePtr is a pointer to the Multi Scaler instance Data is the 64-bit buffer address None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_SRCIMGBUF0_0_V_DATA, XV_multi_scaler_WriteReg.
u64 XV_multi_scaler_Get_HwReg_srcImgBuf0_0_V(XV_multi_scaler *InstancePtr)
Get source image buffer 0 address for channel 0.
This function reads the 64-bit address of source image buffer 0 for channel 0 from the hardware registers. InstancePtr is a pointer to the Multi Scaler instance The 64-bit buffer address None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_SRCIMGBUF0_0_V_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_srcImgBuf1_0_V(XV_multi_scaler *InstancePtr, u64 Data)
Set source image buffer 1 address for channel 0.
This function writes the 64-bit address of source image buffer 1 for channel 0 to the hardware registers. InstancePtr is a pointer to the Multi Scaler instance Data is the 64-bit buffer address None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_SRCIMGBUF1_0_V_DATA, XV_multi_scaler_WriteReg.
u64 XV_multi_scaler_Get_HwReg_srcImgBuf1_0_V(XV_multi_scaler *InstancePtr)
Get source image buffer 1 address for channel 0.
This function reads the 64-bit address of source image buffer 1 for channel 0 from the hardware registers. InstancePtr is a pointer to the Multi Scaler instance The 64-bit buffer address None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_SRCIMGBUF1_0_V_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_dstImgBuf0_0_V(XV_multi_scaler *InstancePtr, u64 Data)
Set destination image buffer 0 address for channel 0.
This function writes the 64-bit address of destination image buffer 0 for channel 0 to the hardware registers. InstancePtr is a pointer to the Multi Scaler instance Data is the 64-bit buffer address None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_DSTIMGBUF0_0_V_DATA, XV_multi_scaler_WriteReg.
u64 XV_multi_scaler_Get_HwReg_dstImgBuf0_0_V(XV_multi_scaler *InstancePtr)
Get destination image buffer 0 address for channel 0.
This function reads the 64-bit address of destination image buffer 0 for channel 0 from the hardware registers. InstancePtr is a pointer to the Multi Scaler instance The 64-bit buffer address None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_DSTIMGBUF0_0_V_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_dstImgBuf1_0_V(XV_multi_scaler *InstancePtr, u64 Data)
Set destination image buffer 1 address for channel 0.
This function writes the 64-bit address of destination image buffer 1 for channel 0 to the hardware registers. InstancePtr is a pointer to the Multi Scaler instance Data is the 64-bit buffer address None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_DSTIMGBUF1_0_V_DATA, XV_multi_scaler_WriteReg.
u64 XV_multi_scaler_Get_HwReg_dstImgBuf1_0_V(XV_multi_scaler *InstancePtr)
Get destination image buffer 1 address for channel 0.
This function reads the 64-bit address of destination image buffer 1 for channel 0 from the hardware registers. InstancePtr is a pointer to the Multi Scaler instance The 64-bit buffer address None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_DSTIMGBUF1_0_V_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_WidthIn_1(XV_multi_scaler *InstancePtr, u32 Data)
Set input width for channel 1.
This function writes the input image width for channel 1 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the input image width in pixels None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_WIDTHIN_1_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_WidthIn_1(XV_multi_scaler *InstancePtr)
Get input width for channel 1.
This function reads the input image width for channel 1 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The input image width in pixels None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_WIDTHIN_1_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_WidthOut_1(XV_multi_scaler *InstancePtr, u32 Data)
Set output width for channel 1.
This function writes the output image width for channel 1 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the output image width in pixels None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_WIDTHOUT_1_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_WidthOut_1(XV_multi_scaler *InstancePtr)
Get output width for channel 1.
This function reads the output image width for channel 1 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The output image width in pixels None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_WIDTHOUT_1_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_HeightIn_1(XV_multi_scaler *InstancePtr, u32 Data)
Set input height for channel 1.
This function writes the input image height for channel 1 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the input image height in pixels None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_HEIGHTIN_1_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_HeightIn_1(XV_multi_scaler *InstancePtr)
Get input height for channel 1.
This function reads the input image height for channel 1 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The input image height in pixels None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_HEIGHTIN_1_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_HeightOut_1(XV_multi_scaler *InstancePtr, u32 Data)
Set output height for channel 1.
This function writes the output image height for channel 1 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the output image height in pixels None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_HEIGHTOUT_1_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_HeightOut_1(XV_multi_scaler *InstancePtr)
Get output height for channel 1.
This function reads the output image height for channel 1 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The output image height in pixels None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_HEIGHTOUT_1_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_LineRate_1(XV_multi_scaler *InstancePtr, u32 Data)
Set line rate for channel 1.
This function writes the line processing rate for channel 1 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the line rate value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_LINERATE_1_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_LineRate_1(XV_multi_scaler *InstancePtr)
Get line rate for channel 1.
This function reads the line processing rate for channel 1 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The line rate value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_LINERATE_1_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_PixelRate_1(XV_multi_scaler *InstancePtr, u32 Data)
Set pixel rate for channel 1.
This function writes the pixel processing rate for channel 1 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the pixel rate value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_PIXELRATE_1_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_PixelRate_1(XV_multi_scaler *InstancePtr)
Get pixel rate for channel 1.
This function reads the pixel processing rate for channel 1 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The pixel rate value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_PIXELRATE_1_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_InPixelFmt_1(XV_multi_scaler *InstancePtr, u32 Data)
Set input pixel format for channel 1.
This function writes the input pixel format for channel 1 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the input pixel format value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_INPIXELFMT_1_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_InPixelFmt_1(XV_multi_scaler *InstancePtr)
Get input pixel format for channel 1.
This function reads the input pixel format for channel 1 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The input pixel format value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_INPIXELFMT_1_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_OutPixelFmt_1(XV_multi_scaler *InstancePtr, u32 Data)
Set output pixel format for channel 1.
This function writes the output pixel format for channel 1 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the output pixel format value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_OUTPIXELFMT_1_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_OutPixelFmt_1(XV_multi_scaler *InstancePtr)
Get output pixel format for channel 1.
This function reads the output pixel format for channel 1 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The output pixel format value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_OUTPIXELFMT_1_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_InStride_1(XV_multi_scaler *InstancePtr, u32 Data)
Set input stride for channel 1.
This function writes the input buffer stride for channel 1 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the input stride value in bytes None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_INSTRIDE_1_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_InStride_1(XV_multi_scaler *InstancePtr)
Get input stride for channel 1.
This function reads the input buffer stride for channel 1 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The input stride value in bytes None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_INSTRIDE_1_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_OutStride_1(XV_multi_scaler *InstancePtr, u32 Data)
Set output stride for channel 1.
This function writes the output buffer stride for channel 1 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the output stride value in bytes None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_OUTSTRIDE_1_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_OutStride_1(XV_multi_scaler *InstancePtr)
Get output stride for channel 1.
This function reads the output buffer stride for channel 1 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The output stride value in bytes None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_OUTSTRIDE_1_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_srcImgBuf0_1_V(XV_multi_scaler *InstancePtr, u64 Data)
Set source image buffer 0 address for channel 1.
This function writes the 64-bit address of source image buffer 0 for channel 1 to the hardware registers. InstancePtr is a pointer to the Multi Scaler instance Data is the 64-bit buffer address None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_SRCIMGBUF0_1_V_DATA, XV_multi_scaler_WriteReg.
u64 XV_multi_scaler_Get_HwReg_srcImgBuf0_1_V(XV_multi_scaler *InstancePtr)
Get source image buffer 0 address for channel 1.
This function reads the 64-bit address of source image buffer 0 for channel 1 from the hardware registers. InstancePtr is a pointer to the Multi Scaler instance The 64-bit buffer address None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_SRCIMGBUF0_1_V_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_srcImgBuf1_1_V(XV_multi_scaler *InstancePtr, u64 Data)
Set source image buffer 1 address for channel 1.
This function writes the 64-bit address of source image buffer 1 for channel 1 to the hardware registers. InstancePtr is a pointer to the Multi Scaler instance Data is the 64-bit buffer address None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_SRCIMGBUF1_1_V_DATA, XV_multi_scaler_WriteReg.
u64 XV_multi_scaler_Get_HwReg_srcImgBuf1_1_V(XV_multi_scaler *InstancePtr)
Get source image buffer 1 address for channel 1.
This function reads the 64-bit address of source image buffer 1 for channel 1 from the hardware registers. InstancePtr is a pointer to the Multi Scaler instance The 64-bit buffer address None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_SRCIMGBUF1_1_V_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_dstImgBuf0_1_V(XV_multi_scaler *InstancePtr, u64 Data)
Set destination image buffer 0 address for channel 1.
This function writes the 64-bit address of destination image buffer 0 for channel 1 to the hardware registers. InstancePtr is a pointer to the Multi Scaler instance Data is the 64-bit buffer address None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_DSTIMGBUF0_1_V_DATA, XV_multi_scaler_WriteReg.
u64 XV_multi_scaler_Get_HwReg_dstImgBuf0_1_V(XV_multi_scaler *InstancePtr)
Get destination image buffer 0 address for channel 1.
This function reads the 64-bit address of destination image buffer 0 for channel 1 from the hardware registers. InstancePtr is a pointer to the Multi Scaler instance The 64-bit buffer address None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_DSTIMGBUF0_1_V_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_dstImgBuf1_1_V(XV_multi_scaler *InstancePtr, u64 Data)
Set destination image buffer 1 address for channel 1.
This function writes the 64-bit address of destination image buffer 1 for channel 1 to the hardware registers. InstancePtr is a pointer to the Multi Scaler instance Data is the 64-bit buffer address None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_DSTIMGBUF1_1_V_DATA, XV_multi_scaler_WriteReg.
u64 XV_multi_scaler_Get_HwReg_dstImgBuf1_1_V(XV_multi_scaler *InstancePtr)
Get destination image buffer 1 address for channel 1.
This function reads the 64-bit address of destination image buffer 1 for channel 1 from the hardware registers. InstancePtr is a pointer to the Multi Scaler instance The 64-bit buffer address None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_DSTIMGBUF1_1_V_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_WidthIn_2(XV_multi_scaler *InstancePtr, u32 Data)
Set input width for channel 2.
This function writes the input image width for channel 2 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the input image width in pixels None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_WIDTHIN_2_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_WidthIn_2(XV_multi_scaler *InstancePtr)
Get input width for channel 2.
This function reads the input image width for channel 2 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The input image width in pixels None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_WIDTHIN_2_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_WidthOut_2(XV_multi_scaler *InstancePtr, u32 Data)
Set output width for channel 2.
This function writes the output image width for channel 2 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the output image width in pixels None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_WIDTHOUT_2_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_WidthOut_2(XV_multi_scaler *InstancePtr)
Get output width for channel 2.
This function reads the output image width for channel 2 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The output image width in pixels None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_WIDTHOUT_2_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_HeightIn_2(XV_multi_scaler *InstancePtr, u32 Data)
Set input height for channel 2.
This function writes the input image height for channel 2 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the input image height in pixels None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_HEIGHTIN_2_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_HeightIn_2(XV_multi_scaler *InstancePtr)
Get input height for channel 2.
This function reads the input image height for channel 2 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The input image height in pixels None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_HEIGHTIN_2_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_HeightOut_2(XV_multi_scaler *InstancePtr, u32 Data)
Set output height for channel 2.
This function writes the output image height for channel 2 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the output image height in pixels None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_HEIGHTOUT_2_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_HeightOut_2(XV_multi_scaler *InstancePtr)
Get output height for channel 2.
This function reads the output image height for channel 2 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The output image height in pixels None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_HEIGHTOUT_2_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_LineRate_2(XV_multi_scaler *InstancePtr, u32 Data)
Set line rate for channel 2.
This function writes the line processing rate for channel 2 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the line rate value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_LINERATE_2_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_LineRate_2(XV_multi_scaler *InstancePtr)
Get line rate for channel 2.
This function reads the line processing rate for channel 2 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The line rate value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_LINERATE_2_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_PixelRate_2(XV_multi_scaler *InstancePtr, u32 Data)
Set pixel rate for channel 2.
This function writes the pixel processing rate for channel 2 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the pixel rate value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_PIXELRATE_2_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_PixelRate_2(XV_multi_scaler *InstancePtr)
Get pixel rate for channel 2.
This function reads the pixel processing rate for channel 2 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The pixel rate value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_PIXELRATE_2_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_InPixelFmt_2(XV_multi_scaler *InstancePtr, u32 Data)
Set input pixel format for channel 2.
This function writes the input pixel format for channel 2 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the input pixel format value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_INPIXELFMT_2_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_InPixelFmt_2(XV_multi_scaler *InstancePtr)
Get input pixel format for channel 2.
This function reads the input pixel format for channel 2 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The input pixel format value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_INPIXELFMT_2_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_OutPixelFmt_2(XV_multi_scaler *InstancePtr, u32 Data)
Set output pixel format for channel 2.
This function writes the output pixel format for channel 2 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the output pixel format value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_OUTPIXELFMT_2_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_OutPixelFmt_2(XV_multi_scaler *InstancePtr)
Get output pixel format for channel 2.
This function reads the output pixel format for channel 2 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The output pixel format value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_OUTPIXELFMT_2_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_InStride_2(XV_multi_scaler *InstancePtr, u32 Data)
Set input stride for channel 2.
This function writes the input buffer stride for channel 2 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the input stride value in bytes None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_INSTRIDE_2_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_InStride_2(XV_multi_scaler *InstancePtr)
Get input stride for channel 2.
This function reads the input buffer stride for channel 2 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The input stride value in bytes None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_INSTRIDE_2_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_OutStride_2(XV_multi_scaler *InstancePtr, u32 Data)
Set output stride for channel 2.
This function writes the output buffer stride for channel 2 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the output stride value in bytes None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_OUTSTRIDE_2_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_OutStride_2(XV_multi_scaler *InstancePtr)
Get output stride for channel 2.
This function reads the output buffer stride for channel 2 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The output stride value in bytes None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_OUTSTRIDE_2_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_srcImgBuf0_2_V(XV_multi_scaler *InstancePtr, u64 Data)
Set source image buffer 0 address for channel 2.
This function writes the 64-bit address of source image buffer 0 for channel 2 to the hardware registers. InstancePtr is a pointer to the Multi Scaler instance Data is the 64-bit buffer address None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_SRCIMGBUF0_2_V_DATA, XV_multi_scaler_WriteReg.
u64 XV_multi_scaler_Get_HwReg_srcImgBuf0_2_V(XV_multi_scaler *InstancePtr)
Get source image buffer 0 address for channel 2.
This function reads the 64-bit address of source image buffer 0 for channel 2 from the hardware registers. InstancePtr is a pointer to the Multi Scaler instance The 64-bit buffer address None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_SRCIMGBUF0_2_V_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_srcImgBuf1_2_V(XV_multi_scaler *InstancePtr, u64 Data)
Set source image buffer 1 address for channel 2.
This function writes the 64-bit address of source image buffer 1 for channel 2 to the hardware registers. InstancePtr is a pointer to the Multi Scaler instance Data is the 64-bit buffer address None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_SRCIMGBUF1_2_V_DATA, XV_multi_scaler_WriteReg.
u64 XV_multi_scaler_Get_HwReg_srcImgBuf1_2_V(XV_multi_scaler *InstancePtr)
Get source image buffer 1 address for channel 2.
This function reads the 64-bit address of source image buffer 1 for channel 2 from the hardware registers. InstancePtr is a pointer to the Multi Scaler instance The 64-bit buffer address None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_SRCIMGBUF1_2_V_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_dstImgBuf0_2_V(XV_multi_scaler *InstancePtr, u64 Data)
Set destination image buffer 0 address for channel 2.
This function writes the 64-bit address of destination image buffer 0 for channel 2 to the hardware registers. InstancePtr is a pointer to the Multi Scaler instance Data is the 64-bit buffer address None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_DSTIMGBUF0_2_V_DATA, XV_multi_scaler_WriteReg.
u64 XV_multi_scaler_Get_HwReg_dstImgBuf0_2_V(XV_multi_scaler *InstancePtr)
Get destination image buffer 0 address for channel 2.
This function reads the 64-bit address of destination image buffer 0 for channel 2 from the hardware registers. InstancePtr is a pointer to the Multi Scaler instance The 64-bit buffer address None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_DSTIMGBUF0_2_V_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_dstImgBuf1_2_V(XV_multi_scaler *InstancePtr, u64 Data)
Set destination image buffer 1 address for channel 2.
This function writes the 64-bit address of destination image buffer 1 for channel 2 to the hardware registers. InstancePtr is a pointer to the Multi Scaler instance Data is the 64-bit buffer address None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_DSTIMGBUF1_2_V_DATA, XV_multi_scaler_WriteReg.
u64 XV_multi_scaler_Get_HwReg_dstImgBuf1_2_V(XV_multi_scaler *InstancePtr)
Get destination image buffer 1 address for channel 2.
This function reads the 64-bit address of destination image buffer 1 for channel 2 from the hardware registers. InstancePtr is a pointer to the Multi Scaler instance The 64-bit buffer address None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_DSTIMGBUF1_2_V_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_WidthIn_3(XV_multi_scaler *InstancePtr, u32 Data)
Set input width for channel 3.
This function writes the input image width for channel 3 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the input image width in pixels None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_WIDTHIN_3_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_WidthIn_3(XV_multi_scaler *InstancePtr)
Get input width for channel 3.
This function reads the input image width for channel 3 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The input image width in pixels None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_WIDTHIN_3_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_WidthOut_3(XV_multi_scaler *InstancePtr, u32 Data)
Set output width for channel 3.
This function writes the output image width for channel 3 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the output image width in pixels None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_WIDTHOUT_3_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_WidthOut_3(XV_multi_scaler *InstancePtr)
Get output width for channel 3.
This function reads the output image width for channel 3 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The output image width in pixels None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_WIDTHOUT_3_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_HeightIn_3(XV_multi_scaler *InstancePtr, u32 Data)
Set input height for channel 3.
This function writes the input image height for channel 3 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the input image height in pixels None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_HEIGHTIN_3_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_HeightIn_3(XV_multi_scaler *InstancePtr)
Get input height for channel 3.
This function reads the input image height for channel 3 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The input image height in pixels None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_HEIGHTIN_3_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_HeightOut_3(XV_multi_scaler *InstancePtr, u32 Data)
Set output height for channel 3.
This function writes the output image height for channel 3 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the output image height in pixels None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_HEIGHTOUT_3_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_HeightOut_3(XV_multi_scaler *InstancePtr)
Get output height for channel 3.
This function reads the output image height for channel 3 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The output image height in pixels None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_HEIGHTOUT_3_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_LineRate_3(XV_multi_scaler *InstancePtr, u32 Data)
Set line rate for channel 3.
This function writes the line processing rate for channel 3 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the line rate value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_LINERATE_3_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_LineRate_3(XV_multi_scaler *InstancePtr)
Get line rate for channel 3.
This function reads the line processing rate for channel 3 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The line rate value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_LINERATE_3_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_PixelRate_3(XV_multi_scaler *InstancePtr, u32 Data)
Set pixel rate for channel 3.
This function writes the pixel processing rate for channel 3 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the pixel rate value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_PIXELRATE_3_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_PixelRate_3(XV_multi_scaler *InstancePtr)
Get pixel rate for channel 3.
This function reads the pixel processing rate for channel 3 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The pixel rate value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_PIXELRATE_3_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_InPixelFmt_3(XV_multi_scaler *InstancePtr, u32 Data)
Set input pixel format for channel 3.
This function writes the input pixel format for channel 3 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the input pixel format value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_INPIXELFMT_3_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_InPixelFmt_3(XV_multi_scaler *InstancePtr)
Get input pixel format for channel 3.
This function reads the input pixel format for channel 3 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The input pixel format value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_INPIXELFMT_3_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_OutPixelFmt_3(XV_multi_scaler *InstancePtr, u32 Data)
Set output pixel format for channel 3.
This function writes the output pixel format for channel 3 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the output pixel format value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_OUTPIXELFMT_3_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_OutPixelFmt_3(XV_multi_scaler *InstancePtr)
Get output pixel format for channel 3.
This function reads the output pixel format for channel 3 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The output pixel format value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_OUTPIXELFMT_3_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_InStride_3(XV_multi_scaler *InstancePtr, u32 Data)
Set input stride for channel 3.
This function writes the input buffer stride for channel 3 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the input stride value in bytes None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_INSTRIDE_3_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_InStride_3(XV_multi_scaler *InstancePtr)
Get input stride for channel 3.
This function reads the input buffer stride for channel 3 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The input stride value in bytes None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_INSTRIDE_3_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_OutStride_3(XV_multi_scaler *InstancePtr, u32 Data)
Set output stride for channel 3.
This function writes the output buffer stride for channel 3 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the output stride value in bytes None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_OUTSTRIDE_3_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_OutStride_3(XV_multi_scaler *InstancePtr)
Get output stride for channel 3.
This function reads the output buffer stride for channel 3 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The output stride value in bytes None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_OUTSTRIDE_3_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_srcImgBuf0_3_V(XV_multi_scaler *InstancePtr, u64 Data)
Set source image buffer 0 address for channel 3.
This function writes the 64-bit address of source image buffer 0 for channel 3 to the hardware registers. InstancePtr is a pointer to the Multi Scaler instance Data is the 64-bit buffer address None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_SRCIMGBUF0_3_V_DATA, XV_multi_scaler_WriteReg.
u64 XV_multi_scaler_Get_HwReg_srcImgBuf0_3_V(XV_multi_scaler *InstancePtr)
Get source image buffer 0 address for channel 3.
This function reads the 64-bit address of source image buffer 0 for channel 3 from the hardware registers. InstancePtr is a pointer to the Multi Scaler instance The 64-bit buffer address None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_SRCIMGBUF0_3_V_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_srcImgBuf1_3_V(XV_multi_scaler *InstancePtr, u64 Data)
Set source image buffer 1 address for channel 3.
This function writes the 64-bit address of source image buffer 1 for channel 3 to the hardware registers. InstancePtr is a pointer to the Multi Scaler instance Data is the 64-bit buffer address None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_SRCIMGBUF1_3_V_DATA, XV_multi_scaler_WriteReg.
u64 XV_multi_scaler_Get_HwReg_srcImgBuf1_3_V(XV_multi_scaler *InstancePtr)
Get source image buffer 1 address for channel 3.
This function reads the 64-bit address of source image buffer 1 for channel 3 from the hardware registers. InstancePtr is a pointer to the Multi Scaler instance The 64-bit buffer address None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_SRCIMGBUF1_3_V_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_dstImgBuf0_3_V(XV_multi_scaler *InstancePtr, u64 Data)
Set destination image buffer 0 address for channel 3.
This function writes the 64-bit address of destination image buffer 0 for channel 3 to the hardware registers. InstancePtr is a pointer to the Multi Scaler instance Data is the 64-bit buffer address None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_DSTIMGBUF0_3_V_DATA, XV_multi_scaler_WriteReg.
u64 XV_multi_scaler_Get_HwReg_dstImgBuf0_3_V(XV_multi_scaler *InstancePtr)
Get destination image buffer 0 address for channel 3.
This function reads the 64-bit address of destination image buffer 0 for channel 3 from the hardware registers. InstancePtr is a pointer to the Multi Scaler instance The 64-bit buffer address None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_DSTIMGBUF0_3_V_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_dstImgBuf1_3_V(XV_multi_scaler *InstancePtr, u64 Data)
Set destination image buffer 1 address for channel 3.
This function writes the 64-bit address of destination image buffer 1 for channel 3 to the hardware registers. InstancePtr is a pointer to the Multi Scaler instance Data is the 64-bit buffer address None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_DSTIMGBUF1_3_V_DATA, XV_multi_scaler_WriteReg.
u64 XV_multi_scaler_Get_HwReg_dstImgBuf1_3_V(XV_multi_scaler *InstancePtr)
Get destination image buffer 1 address for channel 3.
This function reads the 64-bit address of destination image buffer 1 for channel 3 from the hardware registers. InstancePtr is a pointer to the Multi Scaler instance The 64-bit buffer address None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_DSTIMGBUF1_3_V_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_WidthIn_4(XV_multi_scaler *InstancePtr, u32 Data)
Set input width for channel 4.
This function writes the input width for channel 4 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the input width value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_WIDTHIN_4_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_WidthIn_4(XV_multi_scaler *InstancePtr)
Get input width for channel 4.
This function reads the input width for channel 4 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The input width value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_WIDTHIN_4_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_WidthOut_4(XV_multi_scaler *InstancePtr, u32 Data)
Set output width for channel 4.
This function writes the output width for channel 4 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the output width value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_WIDTHOUT_4_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_WidthOut_4(XV_multi_scaler *InstancePtr)
Get output width for channel 4.
This function reads the output width for channel 4 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The output width value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_WIDTHOUT_4_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_HeightIn_4(XV_multi_scaler *InstancePtr, u32 Data)
Set input height for channel 4.
This function writes the input height for channel 4 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the input height value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_HEIGHTIN_4_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_HeightIn_4(XV_multi_scaler *InstancePtr)
Get input height for channel 4.
This function reads the input height for channel 4 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The input height value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_HEIGHTIN_4_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_HeightOut_4(XV_multi_scaler *InstancePtr, u32 Data)
Set output height for channel 4.
This function writes the output height for channel 4 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the output height value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_HEIGHTOUT_4_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_HeightOut_4(XV_multi_scaler *InstancePtr)
Get output height for channel 4.
This function reads the output height for channel 4 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The output height value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_HEIGHTOUT_4_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_LineRate_4(XV_multi_scaler *InstancePtr, u32 Data)
Set line rate for channel 4.
This function writes the line rate for channel 4 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the line rate value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_LINERATE_4_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_LineRate_4(XV_multi_scaler *InstancePtr)
Get line rate for channel 4.
This function reads the line rate for channel 4 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The line rate value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_LINERATE_4_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_PixelRate_4(XV_multi_scaler *InstancePtr, u32 Data)
Set pixel rate for channel 4.
This function writes the pixel rate for channel 4 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the pixel rate value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_PIXELRATE_4_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_PixelRate_4(XV_multi_scaler *InstancePtr)
Get pixel rate for channel 4.
This function reads the pixel rate for channel 4 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The pixel rate value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_PIXELRATE_4_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_InPixelFmt_4(XV_multi_scaler *InstancePtr, u32 Data)
Set input pixel format for channel 4.
This function writes the input pixel format for channel 4 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the input pixel format value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_INPIXELFMT_4_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_InPixelFmt_4(XV_multi_scaler *InstancePtr)
Get input pixel format for channel 4.
This function reads the input pixel format for channel 4 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The input pixel format value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_INPIXELFMT_4_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_OutPixelFmt_4(XV_multi_scaler *InstancePtr, u32 Data)
Set output pixel format for channel 4.
This function writes the output pixel format for channel 4 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the output pixel format value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_OUTPIXELFMT_4_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_OutPixelFmt_4(XV_multi_scaler *InstancePtr)
Get output pixel format for channel 4.
This function reads the output pixel format for channel 4 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The output pixel format value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_OUTPIXELFMT_4_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_InStride_4(XV_multi_scaler *InstancePtr, u32 Data)
Set input stride for channel 4.
This function writes the input stride for channel 4 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the input stride value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_INSTRIDE_4_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_InStride_4(XV_multi_scaler *InstancePtr)
Get input stride for channel 4.
This function reads the input stride for channel 4 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The input stride value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_INSTRIDE_4_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_OutStride_4(XV_multi_scaler *InstancePtr, u32 Data)
Set output stride for channel 4.
This function writes the output stride for channel 4 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the output stride value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_OUTSTRIDE_4_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_OutStride_4(XV_multi_scaler *InstancePtr)
Get output stride for channel 4.
This function reads the output stride for channel 4 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The output stride value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_OUTSTRIDE_4_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_srcImgBuf0_4_V(XV_multi_scaler *InstancePtr, u64 Data)
Set source image buffer 0 address for channel 4.
This function writes the source image buffer 0 address for channel 4 to the hardware registers. InstancePtr is a pointer to the Multi Scaler instance Data is the source image buffer 0 address value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_SRCIMGBUF0_4_V_DATA, XV_multi_scaler_WriteReg.
u64 XV_multi_scaler_Get_HwReg_srcImgBuf0_4_V(XV_multi_scaler *InstancePtr)
Get source image buffer 0 address for channel 4.
This function reads the source image buffer 0 address for channel 4 from the hardware registers. InstancePtr is a pointer to the Multi Scaler instance The source image buffer 0 address value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_SRCIMGBUF0_4_V_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_srcImgBuf1_4_V(XV_multi_scaler *InstancePtr, u64 Data)
Set source image buffer 1 address for channel 4.
This function writes the source image buffer 1 address for channel 4 to the hardware registers. InstancePtr is a pointer to the Multi Scaler instance Data is the source image buffer 1 address value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_SRCIMGBUF1_4_V_DATA, XV_multi_scaler_WriteReg.
u64 XV_multi_scaler_Get_HwReg_srcImgBuf1_4_V(XV_multi_scaler *InstancePtr)
Get source image buffer 1 address for channel 4.
This function reads the source image buffer 1 address for channel 4 from the hardware registers. InstancePtr is a pointer to the Multi Scaler instance The source image buffer 1 address value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_SRCIMGBUF1_4_V_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_dstImgBuf0_4_V(XV_multi_scaler *InstancePtr, u64 Data)
Set destination image buffer 0 address for channel 4.
This function writes the destination image buffer 0 address for channel 4 to the hardware registers. InstancePtr is a pointer to the Multi Scaler instance Data is the destination image buffer 0 address value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_DSTIMGBUF0_4_V_DATA, XV_multi_scaler_WriteReg.
u64 XV_multi_scaler_Get_HwReg_dstImgBuf0_4_V(XV_multi_scaler *InstancePtr)
Get destination image buffer 0 address for channel 4.
This function reads the destination image buffer 0 address for channel 4 from the hardware registers. InstancePtr is a pointer to the Multi Scaler instance The destination image buffer 0 address value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_DSTIMGBUF0_4_V_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_dstImgBuf1_4_V(XV_multi_scaler *InstancePtr, u64 Data)
Set destination image buffer 1 address for channel 4.
This function writes the destination image buffer 1 address for channel 4 to the hardware registers. InstancePtr is a pointer to the Multi Scaler instance Data is the destination image buffer 1 address value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_DSTIMGBUF1_4_V_DATA, XV_multi_scaler_WriteReg.
u64 XV_multi_scaler_Get_HwReg_dstImgBuf1_4_V(XV_multi_scaler *InstancePtr)
Get destination image buffer 1 address for channel 4.
This function reads the destination image buffer 1 address for channel 4 from the hardware registers. InstancePtr is a pointer to the Multi Scaler instance The destination image buffer 1 address value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_DSTIMGBUF1_4_V_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_WidthIn_5(XV_multi_scaler *InstancePtr, u32 Data)
Set input width for channel 5.
This function writes the input width for channel 5 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the input width value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_WIDTHIN_5_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_WidthIn_5(XV_multi_scaler *InstancePtr)
Get input width for channel 5.
This function reads the input width for channel 5 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The input width value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_WIDTHIN_5_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_WidthOut_5(XV_multi_scaler *InstancePtr, u32 Data)
Set output width for channel 5.
This function writes the output width for channel 5 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the output width value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_WIDTHOUT_5_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_WidthOut_5(XV_multi_scaler *InstancePtr)
Get output width for channel 5.
This function reads the output width for channel 5 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The output width value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_WIDTHOUT_5_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_HeightIn_5(XV_multi_scaler *InstancePtr, u32 Data)
Set input height for channel 5.
This function writes the input height for channel 5 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the input height value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_HEIGHTIN_5_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_HeightIn_5(XV_multi_scaler *InstancePtr)
Get input height for channel 5.
This function reads the input height for channel 5 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The input height value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_HEIGHTIN_5_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_HeightOut_5(XV_multi_scaler *InstancePtr, u32 Data)
Set output height for channel 5.
This function writes the output height for channel 5 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the output height value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_HEIGHTOUT_5_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_HeightOut_5(XV_multi_scaler *InstancePtr)
Get output height for channel 5.
This function reads the output height for channel 5 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The output height value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_HEIGHTOUT_5_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_LineRate_5(XV_multi_scaler *InstancePtr, u32 Data)
Set line rate for channel 5.
This function writes the line rate for channel 5 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the line rate value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_LINERATE_5_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_LineRate_5(XV_multi_scaler *InstancePtr)
Get line rate for channel 5.
This function reads the line rate for channel 5 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The line rate value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_LINERATE_5_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_PixelRate_5(XV_multi_scaler *InstancePtr, u32 Data)
Set pixel rate for channel 5.
This function writes the pixel rate for channel 5 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the pixel rate value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_PIXELRATE_5_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_PixelRate_5(XV_multi_scaler *InstancePtr)
Get pixel rate for channel 5.
This function reads the pixel rate for channel 5 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The pixel rate value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_PIXELRATE_5_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_InPixelFmt_5(XV_multi_scaler *InstancePtr, u32 Data)
Set input pixel format for channel 5.
This function writes the input pixel format for channel 5 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the input pixel format value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_INPIXELFMT_5_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_InPixelFmt_5(XV_multi_scaler *InstancePtr)
Get input pixel format for channel 5.
This function reads the input pixel format for channel 5 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The input pixel format value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_INPIXELFMT_5_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_OutPixelFmt_5(XV_multi_scaler *InstancePtr, u32 Data)
Set output pixel format for channel 5.
This function writes the output pixel format for channel 5 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the output pixel format value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_OUTPIXELFMT_5_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_OutPixelFmt_5(XV_multi_scaler *InstancePtr)
Get output pixel format for channel 5.
This function reads the output pixel format for channel 5 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The output pixel format value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_OUTPIXELFMT_5_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_InStride_5(XV_multi_scaler *InstancePtr, u32 Data)
Set input stride for channel 5.
This function writes the input stride for channel 5 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the input stride value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_INSTRIDE_5_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_InStride_5(XV_multi_scaler *InstancePtr)
Get input stride for channel 5.
This function reads the input stride for channel 5 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The input stride value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_INSTRIDE_5_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_OutStride_5(XV_multi_scaler *InstancePtr, u32 Data)
Set output stride for channel 5.
This function writes the output stride for channel 5 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the output stride value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_OUTSTRIDE_5_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_OutStride_5(XV_multi_scaler *InstancePtr)
Get output stride for channel 5.
This function reads the output stride for channel 5 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The output stride value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_OUTSTRIDE_5_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_srcImgBuf0_5_V(XV_multi_scaler *InstancePtr, u64 Data)
Set source image buffer 0 address for channel 5.
This function writes the source image buffer 0 address for channel 5 to the hardware registers. InstancePtr is a pointer to the Multi Scaler instance Data is the source image buffer 0 address value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_SRCIMGBUF0_5_V_DATA, XV_multi_scaler_WriteReg.
u64 XV_multi_scaler_Get_HwReg_srcImgBuf0_5_V(XV_multi_scaler *InstancePtr)
Get source image buffer 0 address for channel 5.
This function reads the source image buffer 0 address for channel 5 from the hardware registers. InstancePtr is a pointer to the Multi Scaler instance The source image buffer 0 address value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_SRCIMGBUF0_5_V_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_srcImgBuf1_5_V(XV_multi_scaler *InstancePtr, u64 Data)
Set source image buffer 1 address for channel 5.
This function writes the source image buffer 1 address for channel 5 to the hardware registers. InstancePtr is a pointer to the Multi Scaler instance Data is the source image buffer 1 address value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_SRCIMGBUF1_5_V_DATA, XV_multi_scaler_WriteReg.
u64 XV_multi_scaler_Get_HwReg_srcImgBuf1_5_V(XV_multi_scaler *InstancePtr)
Get source image buffer 1 address for channel 5.
This function reads the source image buffer 1 address for channel 5 from the hardware registers. InstancePtr is a pointer to the Multi Scaler instance The source image buffer 1 address value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_SRCIMGBUF1_5_V_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_dstImgBuf0_5_V(XV_multi_scaler *InstancePtr, u64 Data)
Set destination image buffer 0 address for channel 5.
This function writes the destination image buffer 0 address for channel 5 to the hardware registers. InstancePtr is a pointer to the Multi Scaler instance Data is the destination image buffer 0 address value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_DSTIMGBUF0_5_V_DATA, XV_multi_scaler_WriteReg.
u64 XV_multi_scaler_Get_HwReg_dstImgBuf0_5_V(XV_multi_scaler *InstancePtr)
Get destination image buffer 0 address for channel 5.
This function reads the destination image buffer 0 address for channel 5 from the hardware registers. InstancePtr is a pointer to the Multi Scaler instance The destination image buffer 0 address value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_DSTIMGBUF0_5_V_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_dstImgBuf1_5_V(XV_multi_scaler *InstancePtr, u64 Data)
Set destination image buffer 1 address for channel 5.
This function writes the destination image buffer 1 address for channel 5 to the hardware registers. InstancePtr is a pointer to the Multi Scaler instance Data is the destination image buffer 1 address value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_DSTIMGBUF1_5_V_DATA, XV_multi_scaler_WriteReg.
u64 XV_multi_scaler_Get_HwReg_dstImgBuf1_5_V(XV_multi_scaler *InstancePtr)
Get destination image buffer 1 address for channel 5.
This function reads the destination image buffer 1 address for channel 5 from the hardware registers. InstancePtr is a pointer to the Multi Scaler instance The destination image buffer 1 address value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_DSTIMGBUF1_5_V_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_WidthIn_6(XV_multi_scaler *InstancePtr, u32 Data)
Set input width for channel 6.
This function writes the input width for channel 6 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the input width value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_WIDTHIN_6_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_WidthIn_6(XV_multi_scaler *InstancePtr)
Get input width for channel 6.
This function reads the input width for channel 6 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The input width value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_WIDTHIN_6_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_WidthOut_6(XV_multi_scaler *InstancePtr, u32 Data)
Set output width for channel 6.
This function writes the output width for channel 6 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the output width value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_WIDTHOUT_6_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_WidthOut_6(XV_multi_scaler *InstancePtr)
Get output width for channel 6.
This function reads the output width for channel 6 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The output width value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_WIDTHOUT_6_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_HeightIn_6(XV_multi_scaler *InstancePtr, u32 Data)
Set input height for channel 6.
This function writes the input height for channel 6 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the input height value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_HEIGHTIN_6_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_HeightIn_6(XV_multi_scaler *InstancePtr)
Get input height for channel 6.
This function reads the input height for channel 6 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The input height value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_HEIGHTIN_6_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_HeightOut_6(XV_multi_scaler *InstancePtr, u32 Data)
Set output height for channel 6.
This function writes the output height for channel 6 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the output height value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_HEIGHTOUT_6_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_HeightOut_6(XV_multi_scaler *InstancePtr)
Get output height for channel 6.
This function reads the output height for channel 6 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The output height value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_HEIGHTOUT_6_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_LineRate_6(XV_multi_scaler *InstancePtr, u32 Data)
Set line rate for channel 6.
This function writes the line rate for channel 6 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the line rate value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_LINERATE_6_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_LineRate_6(XV_multi_scaler *InstancePtr)
Get line rate for channel 6.
This function reads the line rate for channel 6 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The line rate value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_LINERATE_6_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_PixelRate_6(XV_multi_scaler *InstancePtr, u32 Data)
Set pixel rate for channel 6.
This function writes the pixel rate for channel 6 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the pixel rate value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_PIXELRATE_6_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_PixelRate_6(XV_multi_scaler *InstancePtr)
Get pixel rate for channel 6.
This function reads the pixel rate for channel 6 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The pixel rate value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_PIXELRATE_6_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_InPixelFmt_6(XV_multi_scaler *InstancePtr, u32 Data)
Set input pixel format for channel 6.
This function writes the input pixel format for channel 6 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the input pixel format value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_INPIXELFMT_6_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_InPixelFmt_6(XV_multi_scaler *InstancePtr)
Get input pixel format for channel 6.
This function reads the input pixel format for channel 6 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The input pixel format value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_INPIXELFMT_6_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_OutPixelFmt_6(XV_multi_scaler *InstancePtr, u32 Data)
Set output pixel format for channel 6.
This function writes the output pixel format for channel 6 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the output pixel format value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_OUTPIXELFMT_6_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_OutPixelFmt_6(XV_multi_scaler *InstancePtr)
Get output pixel format for channel 6.
This function reads the output pixel format for channel 6 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The output pixel format value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_OUTPIXELFMT_6_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_InStride_6(XV_multi_scaler *InstancePtr, u32 Data)
Set input stride for channel 6.
This function writes the input stride for channel 6 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the input stride value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_INSTRIDE_6_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_InStride_6(XV_multi_scaler *InstancePtr)
Get input stride for channel 6.
This function reads the input stride for channel 6 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The input stride value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_INSTRIDE_6_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_OutStride_6(XV_multi_scaler *InstancePtr, u32 Data)
Set output stride for channel 6.
This function writes the output stride for channel 6 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the output stride value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_OUTSTRIDE_6_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_OutStride_6(XV_multi_scaler *InstancePtr)
Get output stride for channel 6.
This function reads the output stride for channel 6 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The output stride value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_OUTSTRIDE_6_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_srcImgBuf0_6_V(XV_multi_scaler *InstancePtr, u64 Data)
Set source image buffer 0 address for channel 6.
This function writes the source image buffer 0 address for channel 6 to the hardware registers. InstancePtr is a pointer to the Multi Scaler instance Data is the source image buffer 0 address value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_SRCIMGBUF0_6_V_DATA, XV_multi_scaler_WriteReg.
u64 XV_multi_scaler_Get_HwReg_srcImgBuf0_6_V(XV_multi_scaler *InstancePtr)
Get source image buffer 0 address for channel 6.
This function reads the source image buffer 0 address for channel 6 from the hardware registers. InstancePtr is a pointer to the Multi Scaler instance The source image buffer 0 address value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_SRCIMGBUF0_6_V_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_srcImgBuf1_6_V(XV_multi_scaler *InstancePtr, u64 Data)
Set source image buffer 1 address for channel 6.
This function writes the source image buffer 1 address for channel 6 to the hardware registers. InstancePtr is a pointer to the Multi Scaler instance Data is the source image buffer 1 address value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_SRCIMGBUF1_6_V_DATA, XV_multi_scaler_WriteReg.
u64 XV_multi_scaler_Get_HwReg_srcImgBuf1_6_V(XV_multi_scaler *InstancePtr)
Get source image buffer 1 address for channel 6.
This function reads the source image buffer 1 address for channel 6 from the hardware registers. InstancePtr is a pointer to the Multi Scaler instance The source image buffer 1 address value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_SRCIMGBUF1_6_V_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_dstImgBuf0_6_V(XV_multi_scaler *InstancePtr, u64 Data)
Set destination image buffer 0 address for channel 6.
This function writes the destination image buffer 0 address for channel 6 to the hardware registers. InstancePtr is a pointer to the Multi Scaler instance Data is the destination image buffer 0 address value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_DSTIMGBUF0_6_V_DATA, XV_multi_scaler_WriteReg.
u64 XV_multi_scaler_Get_HwReg_dstImgBuf0_6_V(XV_multi_scaler *InstancePtr)
Get destination image buffer 0 address for channel 6.
This function reads the destination image buffer 0 address for channel 6 from the hardware registers. InstancePtr is a pointer to the Multi Scaler instance The destination image buffer 0 address value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_DSTIMGBUF0_6_V_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_dstImgBuf1_6_V(XV_multi_scaler *InstancePtr, u64 Data)
Set destination image buffer 1 address for channel 6.
This function writes the destination image buffer 1 address for channel 6 to the hardware registers. InstancePtr is a pointer to the Multi Scaler instance Data is the destination image buffer 1 address value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_DSTIMGBUF1_6_V_DATA, XV_multi_scaler_WriteReg.
u64 XV_multi_scaler_Get_HwReg_dstImgBuf1_6_V(XV_multi_scaler *InstancePtr)
Get destination image buffer 1 address for channel 6.
This function reads the destination image buffer 1 address for channel 6 from the hardware registers. InstancePtr is a pointer to the Multi Scaler instance The destination image buffer 1 address value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_DSTIMGBUF1_6_V_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_WidthIn_7(XV_multi_scaler *InstancePtr, u32 Data)
Set input width for channel 7.
This function writes the input width for channel 7 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the input width value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_WIDTHIN_7_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_WidthIn_7(XV_multi_scaler *InstancePtr)
Get input width for channel 7.
This function reads the input width for channel 7 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The input width value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_WIDTHIN_7_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_WidthOut_7(XV_multi_scaler *InstancePtr, u32 Data)
Set output width for channel 7.
This function writes the output width for channel 7 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the output width value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_WIDTHOUT_7_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_WidthOut_7(XV_multi_scaler *InstancePtr)
Get output width for channel 7.
This function reads the output width for channel 7 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The output width value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_WIDTHOUT_7_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_HeightIn_7(XV_multi_scaler *InstancePtr, u32 Data)
Set input height for channel 7.
This function writes the input height for channel 7 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the input height value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_HEIGHTIN_7_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_HeightIn_7(XV_multi_scaler *InstancePtr)
Get input height for channel 7.
This function reads the input height for channel 7 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The input height value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_HEIGHTIN_7_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_HeightOut_7(XV_multi_scaler *InstancePtr, u32 Data)
Set output height for channel 7.
This function writes the output height for channel 7 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the output height value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_HEIGHTOUT_7_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_HeightOut_7(XV_multi_scaler *InstancePtr)
Get output height for channel 7.
This function reads the output height for channel 7 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The output height value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_HEIGHTOUT_7_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_LineRate_7(XV_multi_scaler *InstancePtr, u32 Data)
Set line rate for channel 7.
This function writes the line rate for channel 7 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the line rate value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_LINERATE_7_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_LineRate_7(XV_multi_scaler *InstancePtr)
Get line rate for channel 7.
This function reads the line rate for channel 7 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The line rate value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_LINERATE_7_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_PixelRate_7(XV_multi_scaler *InstancePtr, u32 Data)
Set pixel rate for channel 7.
This function writes the pixel rate for channel 7 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the pixel rate value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_PIXELRATE_7_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_PixelRate_7(XV_multi_scaler *InstancePtr)
Get pixel rate for channel 7.
This function reads the pixel rate for channel 7 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The pixel rate value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_PIXELRATE_7_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_InPixelFmt_7(XV_multi_scaler *InstancePtr, u32 Data)
Set input pixel format for channel 7.
This function writes the input pixel format for channel 7 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the input pixel format value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_INPIXELFMT_7_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_InPixelFmt_7(XV_multi_scaler *InstancePtr)
Get input pixel format for channel 7.
This function reads the input pixel format for channel 7 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The input pixel format value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_INPIXELFMT_7_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_OutPixelFmt_7(XV_multi_scaler *InstancePtr, u32 Data)
Set output pixel format for channel 7.
This function writes the output pixel format for channel 7 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the output pixel format value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_OUTPIXELFMT_7_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_OutPixelFmt_7(XV_multi_scaler *InstancePtr)
Get output pixel format for channel 7.
This function reads the output pixel format for channel 7 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The output pixel format value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_OUTPIXELFMT_7_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_InStride_7(XV_multi_scaler *InstancePtr, u32 Data)
Set input stride for channel 7.
This function writes the input stride for channel 7 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the input stride value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_INSTRIDE_7_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_InStride_7(XV_multi_scaler *InstancePtr)
Get input stride for channel 7.
This function reads the input stride for channel 7 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The input stride value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_INSTRIDE_7_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_OutStride_7(XV_multi_scaler *InstancePtr, u32 Data)
Set output stride for channel 7.
This function writes the output stride for channel 7 to the hardware register. InstancePtr is a pointer to the Multi Scaler instance Data is the output stride value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_OUTSTRIDE_7_DATA, XV_multi_scaler_WriteReg.
u32 XV_multi_scaler_Get_HwReg_OutStride_7(XV_multi_scaler *InstancePtr)
Get output stride for channel 7.
This function reads the output stride for channel 7 from the hardware register. InstancePtr is a pointer to the Multi Scaler instance The output stride value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_OUTSTRIDE_7_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_srcImgBuf0_7_V(XV_multi_scaler *InstancePtr, u64 Data)
Set source image buffer 0 address for channel 7.
This function writes the source image buffer 0 address for channel 7 to the hardware registers. InstancePtr is a pointer to the Multi Scaler instance Data is the source image buffer 0 address value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_SRCIMGBUF0_7_V_DATA, XV_multi_scaler_WriteReg.
u64 XV_multi_scaler_Get_HwReg_srcImgBuf0_7_V(XV_multi_scaler *InstancePtr)
Get source image buffer 0 address for channel 7.
This function reads the source image buffer 0 address for channel 7 from the hardware registers. InstancePtr is a pointer to the Multi Scaler instance The source image buffer 0 address value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_SRCIMGBUF0_7_V_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_srcImgBuf1_7_V(XV_multi_scaler *InstancePtr, u64 Data)
Set source image buffer 1 address for channel 7.
This function writes the source image buffer 1 address for channel 7 to the hardware registers. InstancePtr is a pointer to the Multi Scaler instance Data is the source image buffer 1 address value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_SRCIMGBUF1_7_V_DATA, XV_multi_scaler_WriteReg.
u64 XV_multi_scaler_Get_HwReg_srcImgBuf1_7_V(XV_multi_scaler *InstancePtr)
Get source image buffer 1 address for channel 7.
This function reads the source image buffer 1 address for channel 7 from the hardware registers. InstancePtr is a pointer to the Multi Scaler instance The source image buffer 1 address value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_SRCIMGBUF1_7_V_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_dstImgBuf0_7_V(XV_multi_scaler *InstancePtr, u64 Data)
Set destination image buffer 0 address for channel 7.
This function writes the destination image buffer 0 address for channel 7 to the hardware registers. InstancePtr is a pointer to the Multi Scaler instance Data is the destination image buffer 0 address value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_DSTIMGBUF0_7_V_DATA, XV_multi_scaler_WriteReg.
u64 XV_multi_scaler_Get_HwReg_dstImgBuf0_7_V(XV_multi_scaler *InstancePtr)
Get destination image buffer 0 address for channel 7.
This function reads the destination image buffer 0 address for channel 7 from the hardware registers. InstancePtr is a pointer to the Multi Scaler instance The destination image buffer 0 address value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_DSTIMGBUF0_7_V_DATA, XV_multi_scaler_ReadReg.
void XV_multi_scaler_Set_HwReg_dstImgBuf1_7_V(XV_multi_scaler *InstancePtr, u64 Data)
Set destination image buffer 1 address for channel 7.
This function writes the destination image buffer 1 address for channel 7 to the hardware registers. InstancePtr is a pointer to the Multi Scaler instance Data is the destination image buffer 1 address value None None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_DSTIMGBUF1_7_V_DATA, XV_multi_scaler_WriteReg.
u64 XV_multi_scaler_Get_HwReg_dstImgBuf1_7_V(XV_multi_scaler *InstancePtr)
Get destination image buffer 1 address for channel 7.
This function reads the destination image buffer 1 address for channel 7 from the hardware registers. InstancePtr is a pointer to the Multi Scaler instance The destination image buffer 1 address value None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_DSTIMGBUF1_7_V_DATA, XV_multi_scaler_ReadReg.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_0_BaseAddress(XV_multi_scaler *InstancePtr)
Get base address of vertical filter coefficient memory bank 0.
This function returns the base address of the vertical filter coefficient memory bank 0 in the hardware address space. InstancePtr is a pointer to the Multi Scaler instance Base address of the vfltCoeff_0 memory region None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_0_BASE.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_0_HighAddress(XV_multi_scaler *InstancePtr)
Get high address of vertical filter coefficient memory bank 0.
This function returns the high address of the vertical filter coefficient memory bank 0 in the hardware address space. InstancePtr is a pointer to the Multi Scaler instance High address of the vfltCoeff_0 memory region None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_0_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_0_TotalBytes(XV_multi_scaler *InstancePtr)
Get total size of vertical filter coefficient memory bank 0.
This function returns the total size in bytes of the vertical filter coefficient memory bank 0. InstancePtr is a pointer to the Multi Scaler instance Total size of the vfltCoeff_0 memory region in bytes None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_0_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_0_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_0_BitWidth(XV_multi_scaler *InstancePtr)
Get bit width of vertical filter coefficient memory bank 0.
This function returns the bit width of each coefficient entry in the vertical filter coefficient memory bank 0. InstancePtr is a pointer to the Multi Scaler instance Bit width of coefficient entries None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_WIDTH_HWREG_MM_VFLTCOEFF_0.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_0_Depth(XV_multi_scaler *InstancePtr)
Get depth of vertical filter coefficient memory bank 0.
This function returns the depth (number of entries) of the vertical filter coefficient memory bank 0. InstancePtr is a pointer to the Multi Scaler instance Depth (number of coefficient entries) in the memory bank None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_DEPTH_HWREG_MM_VFLTCOEFF_0.
u32 XV_multi_scaler_Write_HwReg_mm_vfltCoeff_0_Words(XV_multi_scaler *InstancePtr, int offset, int *data, int length)
Write words to vertical filter coefficient memory bank 0.
This function writes integer words to the vertical filter coefficient memory bank 0 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the word offset from the base address data is a pointer to the data array to write length is the number of words to write Number of words written, or 0 if the write would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_0_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_0_HIGH.
u32 XV_multi_scaler_Read_HwReg_mm_vfltCoeff_0_Words(XV_multi_scaler *InstancePtr, int offset, int *data, int length)
Read words from vertical filter coefficient memory bank 0.
This function reads integer words from the vertical filter coefficient memory bank 0 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the word offset from the base address data is a pointer to the buffer to store the read data length is the number of words to read Number of words read, or 0 if the read would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_0_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_0_HIGH.
u32 XV_multi_scaler_Write_HwReg_mm_vfltCoeff_0_Bytes(XV_multi_scaler *InstancePtr, int offset, char *data, int length)
Write bytes to vertical filter coefficient memory bank 0.
This function writes individual bytes to the vertical filter coefficient memory bank 0 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the byte offset from the base address data is a pointer to the byte array to write length is the number of bytes to write Number of bytes written, or 0 if the write would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_0_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_0_HIGH.
u32 XV_multi_scaler_Read_HwReg_mm_vfltCoeff_0_Bytes(XV_multi_scaler *InstancePtr, int offset, char *data, int length)
Read bytes from vertical filter coefficient memory bank 0.
This function reads individual bytes from the vertical filter coefficient memory bank 0 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the byte offset from the base address data is a pointer to the buffer to store the read bytes length is the number of bytes to read Number of bytes read, or 0 if the read would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_0_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_0_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_0_BaseAddress(XV_multi_scaler *InstancePtr)
Get base address of horizontal filter coefficient memory bank 0.
This function returns the base address of the horizontal filter coefficient memory bank 0 in the hardware address space. InstancePtr is a pointer to the Multi Scaler instance Base address of the hfltCoeff_0 memory region None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_0_BASE.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_0_HighAddress(XV_multi_scaler *InstancePtr)
Get high address of horizontal filter coefficient memory bank 0.
This function returns the high address of the horizontal filter coefficient memory bank 0 in the hardware address space. InstancePtr is a pointer to the Multi Scaler instance High address of the hfltCoeff_0 memory region None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_0_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_0_TotalBytes(XV_multi_scaler *InstancePtr)
Get total size of horizontal filter coefficient memory bank 0.
This function returns the total size in bytes of the horizontal filter coefficient memory bank 0. InstancePtr is a pointer to the Multi Scaler instance Total size of the hfltCoeff_0 memory region in bytes None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_0_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_0_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_0_BitWidth(XV_multi_scaler *InstancePtr)
Get bit width of horizontal filter coefficient memory bank 0.
This function returns the bit width of each coefficient entry in the horizontal filter coefficient memory bank 0. InstancePtr is a pointer to the Multi Scaler instance Bit width of coefficient entries None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_WIDTH_HWREG_MM_HFLTCOEFF_0.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_0_Depth(XV_multi_scaler *InstancePtr)
Get depth of horizontal filter coefficient memory bank 0.
This function returns the depth (number of entries) of the horizontal filter coefficient memory bank 0. InstancePtr is a pointer to the Multi Scaler instance Depth (number of coefficient entries) in the memory bank None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_DEPTH_HWREG_MM_HFLTCOEFF_0.
u32 XV_multi_scaler_Write_HwReg_mm_hfltCoeff_0_Words(XV_multi_scaler *InstancePtr, int offset, int *data, int length)
Write words to horizontal filter coefficient memory bank 0.
This function writes integer words to the horizontal filter coefficient memory bank 0 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the word offset from the base address data is a pointer to the data array to write length is the number of words to write Number of words written, or 0 if the write would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_0_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_0_HIGH.
u32 XV_multi_scaler_Read_HwReg_mm_hfltCoeff_0_Words(XV_multi_scaler *InstancePtr, int offset, int *data, int length)
Read words from horizontal filter coefficient memory bank 0.
This function reads integer words from the horizontal filter coefficient memory bank 0 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the word offset from the base address data is a pointer to the buffer to store the read data length is the number of words to read Number of words read, or 0 if the read would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_0_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_0_HIGH.
u32 XV_multi_scaler_Write_HwReg_mm_hfltCoeff_0_Bytes(XV_multi_scaler *InstancePtr, int offset, char *data, int length)
Write bytes to horizontal filter coefficient memory bank 0.
This function writes individual bytes to the horizontal filter coefficient memory bank 0 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the byte offset from the base address data is a pointer to the byte array to write length is the number of bytes to write Number of bytes written, or 0 if the write would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_0_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_0_HIGH.
u32 XV_multi_scaler_Read_HwReg_mm_hfltCoeff_0_Bytes(XV_multi_scaler *InstancePtr, int offset, char *data, int length)
Read bytes from horizontal filter coefficient memory bank 0.
This function reads individual bytes from the horizontal filter coefficient memory bank 0 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the byte offset from the base address data is a pointer to the buffer to store the read bytes length is the number of bytes to read Number of bytes read, or 0 if the read would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_0_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_0_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_1_BaseAddress(XV_multi_scaler *InstancePtr)
Get base address of vertical filter coefficient memory bank 1.
This function returns the base address of the vertical filter coefficient memory bank 1 in the hardware address space. InstancePtr is a pointer to the Multi Scaler instance Base address of the vfltCoeff_1 memory region None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_1_BASE.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_1_HighAddress(XV_multi_scaler *InstancePtr)
Get high address of vertical filter coefficient memory bank 1.
This function returns the high address of the vertical filter coefficient memory bank 1 in the hardware address space. InstancePtr is a pointer to the Multi Scaler instance High address of the vfltCoeff_1 memory region None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_1_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_1_TotalBytes(XV_multi_scaler *InstancePtr)
Get total size of vertical filter coefficient memory bank 1.
This function returns the total size in bytes of the vertical filter coefficient memory bank 1. InstancePtr is a pointer to the Multi Scaler instance Total size of the vfltCoeff_1 memory region in bytes None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_1_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_1_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_1_BitWidth(XV_multi_scaler *InstancePtr)
Get bit width of vertical filter coefficient memory bank 1.
This function returns the bit width of each coefficient entry in the vertical filter coefficient memory bank 1. InstancePtr is a pointer to the Multi Scaler instance Bit width of coefficient entries None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_WIDTH_HWREG_MM_VFLTCOEFF_1.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_1_Depth(XV_multi_scaler *InstancePtr)
Get depth of vertical filter coefficient memory bank 1.
This function returns the depth (number of entries) of the vertical filter coefficient memory bank 1. InstancePtr is a pointer to the Multi Scaler instance Depth (number of coefficient entries) in the memory bank None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_DEPTH_HWREG_MM_VFLTCOEFF_1.
u32 XV_multi_scaler_Write_HwReg_mm_vfltCoeff_1_Words(XV_multi_scaler *InstancePtr, int offset, int *data, int length)
Write words to vertical filter coefficient memory bank 1.
This function writes integer words to the vertical filter coefficient memory bank 1 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the word offset from the base address data is a pointer to the data array to write length is the number of words to write Number of words written, or 0 if the write would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_1_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_1_HIGH.
u32 XV_multi_scaler_Read_HwReg_mm_vfltCoeff_1_Words(XV_multi_scaler *InstancePtr, int offset, int *data, int length)
Read words from vertical filter coefficient memory bank 1.
This function reads integer words from the vertical filter coefficient memory bank 1 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the word offset from the base address data is a pointer to the buffer to store the read data length is the number of words to read Number of words read, or 0 if the read would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_1_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_1_HIGH.
u32 XV_multi_scaler_Write_HwReg_mm_vfltCoeff_1_Bytes(XV_multi_scaler *InstancePtr, int offset, char *data, int length)
Write bytes to vertical filter coefficient memory bank 1.
This function writes individual bytes to the vertical filter coefficient memory bank 1 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the byte offset from the base address data is a pointer to the byte array to write length is the number of bytes to write Number of bytes written, or 0 if the write would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_1_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_1_HIGH.
u32 XV_multi_scaler_Read_HwReg_mm_vfltCoeff_1_Bytes(XV_multi_scaler *InstancePtr, int offset, char *data, int length)
Read bytes from vertical filter coefficient memory bank 1.
This function reads individual bytes from the vertical filter coefficient memory bank 1 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the byte offset from the base address data is a pointer to the buffer to store the read bytes length is the number of bytes to read Number of bytes read, or 0 if the read would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_1_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_1_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_1_BaseAddress(XV_multi_scaler *InstancePtr)
Get base address of horizontal filter coefficient memory bank 1.
This function returns the base address of the horizontal filter coefficient memory bank 1 in the hardware address space. InstancePtr is a pointer to the Multi Scaler instance Base address of the hfltCoeff_1 memory region None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_1_BASE.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_1_HighAddress(XV_multi_scaler *InstancePtr)
Get high address of horizontal filter coefficient memory bank 1.
This function returns the high address of the horizontal filter coefficient memory bank 1 in the hardware address space. InstancePtr is a pointer to the Multi Scaler instance High address of the hfltCoeff_1 memory region None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_1_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_1_TotalBytes(XV_multi_scaler *InstancePtr)
Get total size of horizontal filter coefficient memory bank 1.
This function returns the total size in bytes of the horizontal filter coefficient memory bank 1. InstancePtr is a pointer to the Multi Scaler instance Total size of the hfltCoeff_1 memory region in bytes None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_1_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_1_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_1_BitWidth(XV_multi_scaler *InstancePtr)
Get bit width of horizontal filter coefficient memory bank 1.
This function returns the bit width of each coefficient entry in the horizontal filter coefficient memory bank 1. InstancePtr is a pointer to the Multi Scaler instance Bit width of coefficient entries None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_WIDTH_HWREG_MM_HFLTCOEFF_1.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_1_Depth(XV_multi_scaler *InstancePtr)
Get depth of horizontal filter coefficient memory bank 1.
This function returns the depth (number of entries) of the horizontal filter coefficient memory bank 1. InstancePtr is a pointer to the Multi Scaler instance Depth (number of coefficient entries) in the memory bank None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_DEPTH_HWREG_MM_HFLTCOEFF_1.
u32 XV_multi_scaler_Write_HwReg_mm_hfltCoeff_1_Words(XV_multi_scaler *InstancePtr, int offset, int *data, int length)
Write words to horizontal filter coefficient memory bank 1.
This function writes integer words to the horizontal filter coefficient memory bank 1 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the word offset from the base address data is a pointer to the data array to write length is the number of words to write Number of words written, or 0 if the write would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_1_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_1_HIGH.
u32 XV_multi_scaler_Read_HwReg_mm_hfltCoeff_1_Words(XV_multi_scaler *InstancePtr, int offset, int *data, int length)
Read words from horizontal filter coefficient memory bank 1.
This function reads integer words from the horizontal filter coefficient memory bank 1 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the word offset from the base address data is a pointer to the buffer to store the read data length is the number of words to read Number of words read, or 0 if the read would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_1_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_1_HIGH.
u32 XV_multi_scaler_Write_HwReg_mm_hfltCoeff_1_Bytes(XV_multi_scaler *InstancePtr, int offset, char *data, int length)
Write bytes to horizontal filter coefficient memory bank 1.
This function writes individual bytes to the horizontal filter coefficient memory bank 1 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the byte offset from the base address data is a pointer to the byte array to write length is the number of bytes to write Number of bytes written, or 0 if the write would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_1_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_1_HIGH.
u32 XV_multi_scaler_Read_HwReg_mm_hfltCoeff_1_Bytes(XV_multi_scaler *InstancePtr, int offset, char *data, int length)
Read bytes from horizontal filter coefficient memory bank 1.
This function reads individual bytes from the horizontal filter coefficient memory bank 1 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the byte offset from the base address data is a pointer to the buffer to store the read bytes length is the number of bytes to read Number of bytes read, or 0 if the read would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_1_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_1_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_2_BaseAddress(XV_multi_scaler *InstancePtr)
Get base address of vertical filter coefficient memory bank 2.
This function returns the base address of the vertical filter coefficient memory bank 2 in the hardware address space. InstancePtr is a pointer to the Multi Scaler instance Base address of the vfltCoeff_2 memory region None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_2_BASE.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_2_HighAddress(XV_multi_scaler *InstancePtr)
Get high address of vertical filter coefficient memory bank 2.
This function returns the high address of the vertical filter coefficient memory bank 2 in the hardware address space. InstancePtr is a pointer to the Multi Scaler instance High address of the vfltCoeff_2 memory region None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_2_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_2_TotalBytes(XV_multi_scaler *InstancePtr)
Get total size of vertical filter coefficient memory bank 2.
This function returns the total size in bytes of the vertical filter coefficient memory bank 2. InstancePtr is a pointer to the Multi Scaler instance Total size of the vfltCoeff_2 memory region in bytes None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_2_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_2_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_2_BitWidth(XV_multi_scaler *InstancePtr)
Get bit width of vertical filter coefficient memory bank 2.
This function returns the bit width of each coefficient entry in the vertical filter coefficient memory bank 2. InstancePtr is a pointer to the Multi Scaler instance Bit width of coefficient entries None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_WIDTH_HWREG_MM_VFLTCOEFF_2.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_2_Depth(XV_multi_scaler *InstancePtr)
Get depth of vertical filter coefficient memory bank 2.
This function returns the depth (number of entries) of the vertical filter coefficient memory bank 2. InstancePtr is a pointer to the Multi Scaler instance Depth (number of coefficient entries) in the memory bank None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_DEPTH_HWREG_MM_VFLTCOEFF_2.
u32 XV_multi_scaler_Write_HwReg_mm_vfltCoeff_2_Words(XV_multi_scaler *InstancePtr, int offset, int *data, int length)
Write words to vertical filter coefficient memory bank 2.
This function writes integer words to the vertical filter coefficient memory bank 2 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the word offset from the base address data is a pointer to the data array to write length is the number of words to write Number of words written, or 0 if the write would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_2_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_2_HIGH.
u32 XV_multi_scaler_Read_HwReg_mm_vfltCoeff_2_Words(XV_multi_scaler *InstancePtr, int offset, int *data, int length)
Read words from vertical filter coefficient memory bank 2.
This function reads integer words from the vertical filter coefficient memory bank 2 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the word offset from the base address data is a pointer to the buffer to store the read data length is the number of words to read Number of words read, or 0 if the read would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_2_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_2_HIGH.
u32 XV_multi_scaler_Write_HwReg_mm_vfltCoeff_2_Bytes(XV_multi_scaler *InstancePtr, int offset, char *data, int length)
Write bytes to vertical filter coefficient memory bank 2.
This function writes individual bytes to the vertical filter coefficient memory bank 2 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the byte offset from the base address data is a pointer to the byte array to write length is the number of bytes to write Number of bytes written, or 0 if the write would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_2_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_2_HIGH.
u32 XV_multi_scaler_Read_HwReg_mm_vfltCoeff_2_Bytes(XV_multi_scaler *InstancePtr, int offset, char *data, int length)
Read bytes from vertical filter coefficient memory bank 2.
This function reads individual bytes from the vertical filter coefficient memory bank 2 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the byte offset from the base address data is a pointer to the buffer to store the read bytes length is the number of bytes to read Number of bytes read, or 0 if the read would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_2_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_2_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_2_BaseAddress(XV_multi_scaler *InstancePtr)
Get base address of horizontal filter coefficient memory bank 2.
This function returns the base address of the horizontal filter coefficient memory bank 2 in the hardware address space. InstancePtr is a pointer to the Multi Scaler instance Base address of the hfltCoeff_2 memory region None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_2_BASE.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_2_HighAddress(XV_multi_scaler *InstancePtr)
Get high address of horizontal filter coefficient memory bank 2.
This function returns the high address of the horizontal filter coefficient memory bank 2 in the hardware address space. InstancePtr is a pointer to the Multi Scaler instance High address of the hfltCoeff_2 memory region None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_2_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_2_TotalBytes(XV_multi_scaler *InstancePtr)
Get total size of horizontal filter coefficient memory bank 2.
This function returns the total size in bytes of the horizontal filter coefficient memory bank 2. InstancePtr is a pointer to the Multi Scaler instance Total size of the hfltCoeff_2 memory region in bytes None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_2_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_2_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_2_BitWidth(XV_multi_scaler *InstancePtr)
Get bit width of horizontal filter coefficient memory bank 2.
This function returns the bit width of each coefficient entry in the horizontal filter coefficient memory bank 2. InstancePtr is a pointer to the Multi Scaler instance Bit width of coefficient entries None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_WIDTH_HWREG_MM_HFLTCOEFF_2.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_2_Depth(XV_multi_scaler *InstancePtr)
Get depth of horizontal filter coefficient memory bank 2.
This function returns the depth (number of entries) of the horizontal filter coefficient memory bank 2. InstancePtr is a pointer to the Multi Scaler instance Depth (number of coefficient entries) in the memory bank None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_DEPTH_HWREG_MM_HFLTCOEFF_2.
u32 XV_multi_scaler_Write_HwReg_mm_hfltCoeff_2_Words(XV_multi_scaler *InstancePtr, int offset, int *data, int length)
Write words to horizontal filter coefficient memory bank 2.
This function writes integer words to the horizontal filter coefficient memory bank 2 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the word offset from the base address data is a pointer to the data array to write length is the number of words to write Number of words written, or 0 if the write would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_2_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_2_HIGH.
u32 XV_multi_scaler_Read_HwReg_mm_hfltCoeff_2_Words(XV_multi_scaler *InstancePtr, int offset, int *data, int length)
Read words from horizontal filter coefficient memory bank 2.
This function reads integer words from the horizontal filter coefficient memory bank 2 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the word offset from the base address data is a pointer to the buffer to store the read data length is the number of words to read Number of words read, or 0 if the read would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_2_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_2_HIGH.
u32 XV_multi_scaler_Write_HwReg_mm_hfltCoeff_2_Bytes(XV_multi_scaler *InstancePtr, int offset, char *data, int length)
Write bytes to horizontal filter coefficient memory bank 2.
This function writes individual bytes to the horizontal filter coefficient memory bank 2 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the byte offset from the base address data is a pointer to the byte array to write length is the number of bytes to write Number of bytes written, or 0 if the write would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_2_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_2_HIGH.
u32 XV_multi_scaler_Read_HwReg_mm_hfltCoeff_2_Bytes(XV_multi_scaler *InstancePtr, int offset, char *data, int length)
Read bytes from horizontal filter coefficient memory bank 2.
This function reads individual bytes from the horizontal filter coefficient memory bank 2 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the byte offset from the base address data is a pointer to the buffer to store the read bytes length is the number of bytes to read Number of bytes read, or 0 if the read would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_2_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_2_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_3_BaseAddress(XV_multi_scaler *InstancePtr)
Get base address of vertical filter coefficient memory bank 3.
This function returns the base address of the vertical filter coefficient memory bank 3 in the hardware address space. InstancePtr is a pointer to the Multi Scaler instance Base address of the vfltCoeff_3 memory region None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_3_BASE.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_3_HighAddress(XV_multi_scaler *InstancePtr)
Get high address of vertical filter coefficient memory bank 3.
This function returns the high address of the vertical filter coefficient memory bank 3 in the hardware address space. InstancePtr is a pointer to the Multi Scaler instance High address of the vfltCoeff_3 memory region None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_3_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_3_TotalBytes(XV_multi_scaler *InstancePtr)
Get total size of vertical filter coefficient memory bank 3.
This function returns the total size in bytes of the vertical filter coefficient memory bank 3. InstancePtr is a pointer to the Multi Scaler instance Total size of the vfltCoeff_3 memory region in bytes None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_3_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_3_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_3_BitWidth(XV_multi_scaler *InstancePtr)
Get bit width of vertical filter coefficient memory bank 3.
This function returns the bit width of each coefficient entry in the vertical filter coefficient memory bank 3. InstancePtr is a pointer to the Multi Scaler instance Bit width of coefficient entries None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_WIDTH_HWREG_MM_VFLTCOEFF_3.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_3_Depth(XV_multi_scaler *InstancePtr)
Get depth of vertical filter coefficient memory bank 3.
This function returns the depth (number of entries) of the vertical filter coefficient memory bank 3. InstancePtr is a pointer to the Multi Scaler instance Depth (number of coefficient entries) in the memory bank None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_DEPTH_HWREG_MM_VFLTCOEFF_3.
u32 XV_multi_scaler_Write_HwReg_mm_vfltCoeff_3_Words(XV_multi_scaler *InstancePtr, int offset, int *data, int length)
Write words to vertical filter coefficient memory bank 3.
This function writes integer words to the vertical filter coefficient memory bank 3 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the word offset from the base address data is a pointer to the data array to write length is the number of words to write Number of words written, or 0 if the write would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_3_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_3_HIGH.
u32 XV_multi_scaler_Read_HwReg_mm_vfltCoeff_3_Words(XV_multi_scaler *InstancePtr, int offset, int *data, int length)
Read words from vertical filter coefficient memory bank 3.
This function reads integer words from the vertical filter coefficient memory bank 3 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the word offset from the base address data is a pointer to the buffer to store the read data length is the number of words to read Number of words read, or 0 if the read would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_3_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_3_HIGH.
u32 XV_multi_scaler_Write_HwReg_mm_vfltCoeff_3_Bytes(XV_multi_scaler *InstancePtr, int offset, char *data, int length)
Write bytes to vertical filter coefficient memory bank 3.
This function writes individual bytes to the vertical filter coefficient memory bank 3 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the byte offset from the base address data is a pointer to the byte array to write length is the number of bytes to write Number of bytes written, or 0 if the write would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_3_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_3_HIGH.
u32 XV_multi_scaler_Read_HwReg_mm_vfltCoeff_3_Bytes(XV_multi_scaler *InstancePtr, int offset, char *data, int length)
Read bytes from vertical filter coefficient memory bank 3.
This function reads individual bytes from the vertical filter coefficient memory bank 3 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the byte offset from the base address data is a pointer to the buffer to store the read bytes length is the number of bytes to read Number of bytes read, or 0 if the read would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_3_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_3_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_3_BaseAddress(XV_multi_scaler *InstancePtr)
Get base address of horizontal filter coefficient memory bank 3.
This function returns the base address of the horizontal filter coefficient memory bank 3 in the hardware address space. InstancePtr is a pointer to the Multi Scaler instance Base address of the hfltCoeff_3 memory region None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_3_BASE.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_3_HighAddress(XV_multi_scaler *InstancePtr)
Get high address of horizontal filter coefficient memory bank 3.
This function returns the high address of the horizontal filter coefficient memory bank 3 in the hardware address space. InstancePtr is a pointer to the Multi Scaler instance High address of the hfltCoeff_3 memory region None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_3_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_3_TotalBytes(XV_multi_scaler *InstancePtr)
Get total size of horizontal filter coefficient memory bank 3.
This function returns the total size in bytes of the horizontal filter coefficient memory bank 3. InstancePtr is a pointer to the Multi Scaler instance Total size of the hfltCoeff_3 memory region in bytes None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_3_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_3_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_3_BitWidth(XV_multi_scaler *InstancePtr)
Get bit width of horizontal filter coefficient memory bank 3.
This function returns the bit width of each coefficient entry in the horizontal filter coefficient memory bank 3. InstancePtr is a pointer to the Multi Scaler instance Bit width of coefficient entries None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_WIDTH_HWREG_MM_HFLTCOEFF_3.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_3_Depth(XV_multi_scaler *InstancePtr)
Get depth of horizontal filter coefficient memory bank 3.
This function returns the depth (number of entries) of the horizontal filter coefficient memory bank 3. InstancePtr is a pointer to the Multi Scaler instance Depth (number of coefficient entries) in the memory bank None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_DEPTH_HWREG_MM_HFLTCOEFF_3.
u32 XV_multi_scaler_Write_HwReg_mm_hfltCoeff_3_Words(XV_multi_scaler *InstancePtr, int offset, int *data, int length)
Write words to horizontal filter coefficient memory bank 3.
This function writes integer words to the horizontal filter coefficient memory bank 3 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the word offset from the base address data is a pointer to the data array to write length is the number of words to write Number of words written, or 0 if the write would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_3_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_3_HIGH.
u32 XV_multi_scaler_Read_HwReg_mm_hfltCoeff_3_Words(XV_multi_scaler *InstancePtr, int offset, int *data, int length)
Read words from horizontal filter coefficient memory bank 3.
This function reads integer words from the horizontal filter coefficient memory bank 3 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the word offset from the base address data is a pointer to the buffer to store the read data length is the number of words to read Number of words read, or 0 if the read would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_3_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_3_HIGH.
u32 XV_multi_scaler_Write_HwReg_mm_hfltCoeff_3_Bytes(XV_multi_scaler *InstancePtr, int offset, char *data, int length)
Write bytes to horizontal filter coefficient memory bank 3.
This function writes individual bytes to the horizontal filter coefficient memory bank 3 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the byte offset from the base address data is a pointer to the byte array to write length is the number of bytes to write Number of bytes written, or 0 if the write would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_3_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_3_HIGH.
u32 XV_multi_scaler_Read_HwReg_mm_hfltCoeff_3_Bytes(XV_multi_scaler *InstancePtr, int offset, char *data, int length)
Read bytes from horizontal filter coefficient memory bank 3.
This function reads individual bytes from the horizontal filter coefficient memory bank 3 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the byte offset from the base address data is a pointer to the buffer to store the read bytes length is the number of bytes to read Number of bytes read, or 0 if the read would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_3_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_3_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_4_BaseAddress(XV_multi_scaler *InstancePtr)
Get base address of vertical filter coefficient memory bank 4.
This function returns the base address of the vertical filter coefficient memory bank 4 in the hardware address space. InstancePtr is a pointer to the Multi Scaler instance Base address of the vfltCoeff_4 memory region None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_4_BASE.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_4_HighAddress(XV_multi_scaler *InstancePtr)
Get high address of vertical filter coefficient memory bank 4.
This function returns the high address of the vertical filter coefficient memory bank 4 in the hardware address space. InstancePtr is a pointer to the Multi Scaler instance High address of the vfltCoeff_4 memory region None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_4_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_4_TotalBytes(XV_multi_scaler *InstancePtr)
Get total size of vertical filter coefficient memory bank 4.
This function returns the total size in bytes of the vertical filter coefficient memory bank 4. InstancePtr is a pointer to the Multi Scaler instance Total size of the vfltCoeff_4 memory region in bytes None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_4_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_4_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_4_BitWidth(XV_multi_scaler *InstancePtr)
Get bit width of vertical filter coefficient memory bank 4.
This function returns the bit width of each coefficient entry in the vertical filter coefficient memory bank 4. InstancePtr is a pointer to the Multi Scaler instance Bit width of coefficient entries None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_WIDTH_HWREG_MM_VFLTCOEFF_4.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_4_Depth(XV_multi_scaler *InstancePtr)
Get depth of vertical filter coefficient memory bank 4.
This function returns the depth (number of entries) of the vertical filter coefficient memory bank 4. InstancePtr is a pointer to the Multi Scaler instance Depth (number of coefficient entries) in the memory bank None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_DEPTH_HWREG_MM_VFLTCOEFF_4.
u32 XV_multi_scaler_Write_HwReg_mm_vfltCoeff_4_Words(XV_multi_scaler *InstancePtr, int offset, int *data, int length)
Write words to vertical filter coefficient memory bank 4.
This function writes integer words to the vertical filter coefficient memory bank 4 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the word offset from the base address data is a pointer to the data array to write length is the number of words to write Number of words written, or 0 if the write would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_4_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_4_HIGH.
u32 XV_multi_scaler_Read_HwReg_mm_vfltCoeff_4_Words(XV_multi_scaler *InstancePtr, int offset, int *data, int length)
Read words from vertical filter coefficient memory bank 4.
This function reads integer words from the vertical filter coefficient memory bank 4 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the word offset from the base address data is a pointer to the buffer to store the read data length is the number of words to read Number of words read, or 0 if the read would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_4_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_4_HIGH.
u32 XV_multi_scaler_Write_HwReg_mm_vfltCoeff_4_Bytes(XV_multi_scaler *InstancePtr, int offset, char *data, int length)
Write bytes to vertical filter coefficient memory bank 4.
This function writes individual bytes to the vertical filter coefficient memory bank 4 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the byte offset from the base address data is a pointer to the byte array to write length is the number of bytes to write Number of bytes written, or 0 if the write would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_4_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_4_HIGH.
u32 XV_multi_scaler_Read_HwReg_mm_vfltCoeff_4_Bytes(XV_multi_scaler *InstancePtr, int offset, char *data, int length)
Read bytes from vertical filter coefficient memory bank 4.
This function reads individual bytes from the vertical filter coefficient memory bank 4 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the byte offset from the base address data is a pointer to the buffer to store the read bytes length is the number of bytes to read Number of bytes read, or 0 if the read would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_4_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_4_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_4_BaseAddress(XV_multi_scaler *InstancePtr)
Get base address of horizontal filter coefficient memory bank 4.
This function returns the base address of the horizontal filter coefficient memory bank 4 in the hardware address space. InstancePtr is a pointer to the Multi Scaler instance Base address of the hfltCoeff_4 memory region None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_4_BASE.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_4_HighAddress(XV_multi_scaler *InstancePtr)
Get high address of horizontal filter coefficient memory bank 4.
This function returns the high address of the horizontal filter coefficient memory bank 4 in the hardware address space. InstancePtr is a pointer to the Multi Scaler instance High address of the hfltCoeff_4 memory region None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_4_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_4_TotalBytes(XV_multi_scaler *InstancePtr)
Get total size of horizontal filter coefficient memory bank 4.
This function returns the total size in bytes of the horizontal filter coefficient memory bank 4. InstancePtr is a pointer to the Multi Scaler instance Total size of the hfltCoeff_4 memory region in bytes None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_4_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_4_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_4_BitWidth(XV_multi_scaler *InstancePtr)
Get bit width of horizontal filter coefficient memory bank 4.
This function returns the bit width of each coefficient entry in the horizontal filter coefficient memory bank 4. InstancePtr is a pointer to the Multi Scaler instance Bit width of the hfltCoeff_4 memory region None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_WIDTH_HWREG_MM_HFLTCOEFF_4.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_4_Depth(XV_multi_scaler *InstancePtr)
Get depth of horizontal filter coefficient memory bank 4.
This function returns the number of coefficient entries in the horizontal filter coefficient memory bank 4. InstancePtr is a pointer to the Multi Scaler instance Depth of the hfltCoeff_4 memory region None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_DEPTH_HWREG_MM_HFLTCOEFF_4.
u32 XV_multi_scaler_Write_HwReg_mm_hfltCoeff_4_Words(XV_multi_scaler *InstancePtr, int offset, int *data, int length)
Write words to horizontal filter coefficient memory bank 4.
This function writes an array of integer words to the horizontal filter coefficient memory bank 4 at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the word offset to start writing data is a pointer to the integer data array length is the number of words to write Number of words written, or 0 if write failed None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_4_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_4_HIGH.
u32 XV_multi_scaler_Read_HwReg_mm_hfltCoeff_4_Words(XV_multi_scaler *InstancePtr, int offset, int *data, int length)
Read words from horizontal filter coefficient memory bank 4.
This function reads an array of integer words from the horizontal filter coefficient memory bank 4 at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the word offset to start reading data is a pointer to the integer data array to store read values length is the number of words to read Number of words read, or 0 if read failed None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_4_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_4_HIGH.
u32 XV_multi_scaler_Write_HwReg_mm_hfltCoeff_4_Bytes(XV_multi_scaler *InstancePtr, int offset, char *data, int length)
Write bytes to horizontal filter coefficient memory bank 4.
This function writes an array of bytes to the horizontal filter coefficient memory bank 4 at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the byte offset to start writing data is a pointer to the byte data array length is the number of bytes to write Number of bytes written, or 0 if write failed None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_4_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_4_HIGH.
u32 XV_multi_scaler_Read_HwReg_mm_hfltCoeff_4_Bytes(XV_multi_scaler *InstancePtr, int offset, char *data, int length)
Read bytes from horizontal filter coefficient memory bank 4.
This function reads an array of bytes from the horizontal filter coefficient memory bank 4 at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the byte offset to start reading data is a pointer to the byte data array to store read values length is the number of bytes to read Number of bytes read, or 0 if read failed None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_4_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_4_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_5_BaseAddress(XV_multi_scaler *InstancePtr)
Get base address of vertical filter coefficient memory bank 5.
This function returns the base address of the vertical filter coefficient memory bank 5 in the hardware address space. InstancePtr is a pointer to the Multi Scaler instance Base address of the vfltCoeff_5 memory region None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_5_BASE.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_5_HighAddress(XV_multi_scaler *InstancePtr)
Get high address of vertical filter coefficient memory bank 5.
This function returns the high address of the vertical filter coefficient memory bank 5 in the hardware address space. InstancePtr is a pointer to the Multi Scaler instance High address of the vfltCoeff_5 memory region None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_5_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_5_TotalBytes(XV_multi_scaler *InstancePtr)
Get total size of vertical filter coefficient memory bank 5.
This function returns the total size in bytes of the vertical filter coefficient memory bank 5. InstancePtr is a pointer to the Multi Scaler instance Total size of the vfltCoeff_5 memory region in bytes None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_5_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_5_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_5_BitWidth(XV_multi_scaler *InstancePtr)
Get bit width of vertical filter coefficient memory bank 5.
This function returns the bit width of each coefficient entry in the vertical filter coefficient memory bank 5. InstancePtr is a pointer to the Multi Scaler instance Bit width of coefficient entries None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_WIDTH_HWREG_MM_VFLTCOEFF_5.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_5_Depth(XV_multi_scaler *InstancePtr)
Get depth of vertical filter coefficient memory bank 5.
This function returns the depth (number of entries) of the vertical filter coefficient memory bank 5. InstancePtr is a pointer to the Multi Scaler instance Depth (number of coefficient entries) in the memory bank None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_DEPTH_HWREG_MM_VFLTCOEFF_5.
u32 XV_multi_scaler_Write_HwReg_mm_vfltCoeff_5_Words(XV_multi_scaler *InstancePtr, int offset, int *data, int length)
Write words to vertical filter coefficient memory bank 5.
This function writes integer words to the vertical filter coefficient memory bank 5 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the word offset from the base address data is a pointer to the data array to write length is the number of words to write Number of words written, or 0 if the write would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_5_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_5_HIGH.
u32 XV_multi_scaler_Read_HwReg_mm_vfltCoeff_5_Words(XV_multi_scaler *InstancePtr, int offset, int *data, int length)
Read words from vertical filter coefficient memory bank 5.
This function reads integer words from the vertical filter coefficient memory bank 5 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the word offset from the base address data is a pointer to the buffer to store the read data length is the number of words to read Number of words read, or 0 if the read would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_5_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_5_HIGH.
u32 XV_multi_scaler_Write_HwReg_mm_vfltCoeff_5_Bytes(XV_multi_scaler *InstancePtr, int offset, char *data, int length)
Write bytes to vertical filter coefficient memory bank 5.
This function writes individual bytes to the vertical filter coefficient memory bank 5 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the byte offset from the base address data is a pointer to the byte array to write length is the number of bytes to write Number of bytes written, or 0 if the write would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_5_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_5_HIGH.
u32 XV_multi_scaler_Read_HwReg_mm_vfltCoeff_5_Bytes(XV_multi_scaler *InstancePtr, int offset, char *data, int length)
Read bytes from vertical filter coefficient memory bank 5.
This function reads individual bytes from the vertical filter coefficient memory bank 5 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the byte offset from the base address data is a pointer to the buffer to store the read bytes length is the number of bytes to read Number of bytes read, or 0 if the read would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_5_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_5_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_5_BaseAddress(XV_multi_scaler *InstancePtr)
Get base address of horizontal filter coefficient memory bank 5.
This function returns the base address of the horizontal filter coefficient memory bank 5 in the hardware address space. InstancePtr is a pointer to the Multi Scaler instance Base address of the hfltCoeff_5 memory region None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_5_BASE.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_5_HighAddress(XV_multi_scaler *InstancePtr)
Get high address of horizontal filter coefficient memory bank 5.
This function returns the high address of the horizontal filter coefficient memory bank 5 in the hardware address space. InstancePtr is a pointer to the Multi Scaler instance High address of the hfltCoeff_5 memory region None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_5_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_5_TotalBytes(XV_multi_scaler *InstancePtr)
Get total size of horizontal filter coefficient memory bank 5.
This function returns the total size in bytes of the horizontal filter coefficient memory bank 5. InstancePtr is a pointer to the Multi Scaler instance Total size of the hfltCoeff_5 memory region in bytes None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_5_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_5_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_5_BitWidth(XV_multi_scaler *InstancePtr)
Get bit width of horizontal filter coefficient memory bank 5.
This function returns the bit width of each coefficient entry in the horizontal filter coefficient memory bank 5. InstancePtr is a pointer to the Multi Scaler instance Bit width of coefficient entries None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_WIDTH_HWREG_MM_HFLTCOEFF_5.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_5_Depth(XV_multi_scaler *InstancePtr)
Get depth of horizontal filter coefficient memory bank 5.
This function returns the depth (number of entries) of the horizontal filter coefficient memory bank 5. InstancePtr is a pointer to the Multi Scaler instance Depth (number of coefficient entries) in the memory bank None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_DEPTH_HWREG_MM_HFLTCOEFF_5.
u32 XV_multi_scaler_Write_HwReg_mm_hfltCoeff_5_Words(XV_multi_scaler *InstancePtr, int offset, int *data, int length)
Write words to horizontal filter coefficient memory bank 5.
This function writes integer words to the horizontal filter coefficient memory bank 5 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the word offset from the base address data is a pointer to the data array to write length is the number of words to write Number of words written, or 0 if the write would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_5_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_5_HIGH.
u32 XV_multi_scaler_Read_HwReg_mm_hfltCoeff_5_Words(XV_multi_scaler *InstancePtr, int offset, int *data, int length)
Read words from horizontal filter coefficient memory bank 5.
This function reads integer words from the horizontal filter coefficient memory bank 5 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the word offset from the base address data is a pointer to the buffer to store the read data length is the number of words to read Number of words read, or 0 if the read would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_5_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_5_HIGH.
u32 XV_multi_scaler_Write_HwReg_mm_hfltCoeff_5_Bytes(XV_multi_scaler *InstancePtr, int offset, char *data, int length)
Write bytes to horizontal filter coefficient memory bank 5.
This function writes individual bytes to the horizontal filter coefficient memory bank 5 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the byte offset from the base address data is a pointer to the byte array to write length is the number of bytes to write Number of bytes written, or 0 if the write would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_5_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_5_HIGH.
u32 XV_multi_scaler_Read_HwReg_mm_hfltCoeff_5_Bytes(XV_multi_scaler *InstancePtr, int offset, char *data, int length)
Read bytes from horizontal filter coefficient memory bank 5.
This function reads individual bytes from the horizontal filter coefficient memory bank 5 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the byte offset from the base address data is a pointer to the buffer to store the read bytes length is the number of bytes to read Number of bytes read, or 0 if the read would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_5_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_5_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_6_BaseAddress(XV_multi_scaler *InstancePtr)
Get base address of vertical filter coefficient memory bank 6.
This function returns the base address of the vertical filter coefficient memory bank 6 in the hardware address space. InstancePtr is a pointer to the Multi Scaler instance Base address of the vfltCoeff_6 memory region None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_6_BASE.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_6_HighAddress(XV_multi_scaler *InstancePtr)
Get high address of vertical filter coefficient memory bank 6.
This function returns the high address of the vertical filter coefficient memory bank 6 in the hardware address space. InstancePtr is a pointer to the Multi Scaler instance High address of the vfltCoeff_6 memory region None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_6_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_6_TotalBytes(XV_multi_scaler *InstancePtr)
Get total size of vertical filter coefficient memory bank 6.
This function returns the total size in bytes of the vertical filter coefficient memory bank 6. InstancePtr is a pointer to the Multi Scaler instance Total size of the vfltCoeff_6 memory region in bytes None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_6_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_6_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_6_BitWidth(XV_multi_scaler *InstancePtr)
Get bit width of vertical filter coefficient memory bank 6.
This function returns the bit width of each coefficient entry in the vertical filter coefficient memory bank 6. InstancePtr is a pointer to the Multi Scaler instance Bit width of coefficient entries None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_WIDTH_HWREG_MM_VFLTCOEFF_6.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_6_Depth(XV_multi_scaler *InstancePtr)
Get depth of vertical filter coefficient memory bank 6.
This function returns the depth (number of entries) of the vertical filter coefficient memory bank 6. InstancePtr is a pointer to the Multi Scaler instance Depth (number of coefficient entries) in the memory bank None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_DEPTH_HWREG_MM_VFLTCOEFF_6.
u32 XV_multi_scaler_Write_HwReg_mm_vfltCoeff_6_Words(XV_multi_scaler *InstancePtr, int offset, int *data, int length)
Write words to vertical filter coefficient memory bank 6.
This function writes integer words to the vertical filter coefficient memory bank 6 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the word offset from the base address data is a pointer to the data array to write length is the number of words to write Number of words written, or 0 if the write would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_6_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_6_HIGH.
u32 XV_multi_scaler_Read_HwReg_mm_vfltCoeff_6_Words(XV_multi_scaler *InstancePtr, int offset, int *data, int length)
Read words from vertical filter coefficient memory bank 6.
This function reads integer words from the vertical filter coefficient memory bank 6 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the word offset from the base address data is a pointer to the buffer to store the read data length is the number of words to read Number of words read, or 0 if the read would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_6_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_6_HIGH.
u32 XV_multi_scaler_Write_HwReg_mm_vfltCoeff_6_Bytes(XV_multi_scaler *InstancePtr, int offset, char *data, int length)
Write bytes to vertical filter coefficient memory bank 6.
This function writes individual bytes to the vertical filter coefficient memory bank 6 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the byte offset from the base address data is a pointer to the byte array to write length is the number of bytes to write Number of bytes written, or 0 if the write would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_6_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_6_HIGH.
u32 XV_multi_scaler_Read_HwReg_mm_vfltCoeff_6_Bytes(XV_multi_scaler *InstancePtr, int offset, char *data, int length)
Read bytes from vertical filter coefficient memory bank 6.
This function reads individual bytes from the vertical filter coefficient memory bank 6 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the byte offset from the base address data is a pointer to the buffer to store the read bytes length is the number of bytes to read Number of bytes read, or 0 if the read would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_6_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_6_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_6_BaseAddress(XV_multi_scaler *InstancePtr)
Get base address of horizontal filter coefficient memory bank 6.
This function returns the base address of the horizontal filter coefficient memory bank 6 in the hardware address space. InstancePtr is a pointer to the Multi Scaler instance Base address of the hfltCoeff_6 memory region None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_6_BASE.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_6_HighAddress(XV_multi_scaler *InstancePtr)
Get high address of horizontal filter coefficient memory bank 6.
This function returns the high address of the horizontal filter coefficient memory bank 6 in the hardware address space. InstancePtr is a pointer to the Multi Scaler instance High address of the hfltCoeff_6 memory region None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_6_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_6_TotalBytes(XV_multi_scaler *InstancePtr)
Get total size of horizontal filter coefficient memory bank 6.
This function returns the total size in bytes of the horizontal filter coefficient memory bank 6. InstancePtr is a pointer to the Multi Scaler instance Total size of the hfltCoeff_6 memory region in bytes None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_6_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_6_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_6_BitWidth(XV_multi_scaler *InstancePtr)
Get bit width of horizontal filter coefficient memory bank 6.
This function returns the bit width of each coefficient entry in the horizontal filter coefficient memory bank 6. InstancePtr is a pointer to the Multi Scaler instance Bit width of coefficient entries None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_WIDTH_HWREG_MM_HFLTCOEFF_6.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_6_Depth(XV_multi_scaler *InstancePtr)
Get depth of horizontal filter coefficient memory bank 6.
This function returns the depth (number of entries) of the horizontal filter coefficient memory bank 6. InstancePtr is a pointer to the Multi Scaler instance Depth (number of coefficient entries) in the memory bank None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_DEPTH_HWREG_MM_HFLTCOEFF_6.
u32 XV_multi_scaler_Write_HwReg_mm_hfltCoeff_6_Words(XV_multi_scaler *InstancePtr, int offset, int *data, int length)
Write words to horizontal filter coefficient memory bank 6.
This function writes integer words to the horizontal filter coefficient memory bank 6 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the word offset from the base address data is a pointer to the data array to write length is the number of words to write Number of words written, or 0 if the write would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_6_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_6_HIGH.
u32 XV_multi_scaler_Read_HwReg_mm_hfltCoeff_6_Words(XV_multi_scaler *InstancePtr, int offset, int *data, int length)
Read words from horizontal filter coefficient memory bank 6.
This function reads integer words from the horizontal filter coefficient memory bank 6 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the word offset from the base address data is a pointer to the buffer to store the read data length is the number of words to read Number of words read, or 0 if the read would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_6_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_6_HIGH.
u32 XV_multi_scaler_Write_HwReg_mm_hfltCoeff_6_Bytes(XV_multi_scaler *InstancePtr, int offset, char *data, int length)
Write bytes to horizontal filter coefficient memory bank 6.
This function writes individual bytes to the horizontal filter coefficient memory bank 6 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the byte offset from the base address data is a pointer to the byte array to write length is the number of bytes to write Number of bytes written, or 0 if the write would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_6_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_6_HIGH.
u32 XV_multi_scaler_Read_HwReg_mm_hfltCoeff_6_Bytes(XV_multi_scaler *InstancePtr, int offset, char *data, int length)
Read bytes from horizontal filter coefficient memory bank 6.
This function reads individual bytes from the horizontal filter coefficient memory bank 6 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the byte offset from the base address data is a pointer to the buffer to store the read bytes length is the number of bytes to read Number of bytes read, or 0 if the read would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_6_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_6_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_7_BaseAddress(XV_multi_scaler *InstancePtr)
Get base address of vertical filter coefficient memory bank 7.
This function returns the base address of the vertical filter coefficient memory bank 7 in the hardware address space. InstancePtr is a pointer to the Multi Scaler instance Base address of the vfltCoeff_7 memory region None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_7_BASE.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_7_HighAddress(XV_multi_scaler *InstancePtr)
Get high address of vertical filter coefficient memory bank 7.
This function returns the high address of the vertical filter coefficient memory bank 7 in the hardware address space. InstancePtr is a pointer to the Multi Scaler instance High address of the vfltCoeff_7 memory region None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_7_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_7_TotalBytes(XV_multi_scaler *InstancePtr)
Get total size of vertical filter coefficient memory bank 7.
This function returns the total size in bytes of the vertical filter coefficient memory bank 7. InstancePtr is a pointer to the Multi Scaler instance Total size of the vfltCoeff_7 memory region in bytes None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_7_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_7_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_7_BitWidth(XV_multi_scaler *InstancePtr)
Get bit width of vertical filter coefficient memory bank 7.
This function returns the bit width of each coefficient entry in the vertical filter coefficient memory bank 7. InstancePtr is a pointer to the Multi Scaler instance Bit width of coefficient entries None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_WIDTH_HWREG_MM_VFLTCOEFF_7.
u32 XV_multi_scaler_Get_HwReg_mm_vfltCoeff_7_Depth(XV_multi_scaler *InstancePtr)
Get depth of vertical filter coefficient memory bank 7.
This function returns the depth (number of entries) of the vertical filter coefficient memory bank 7. InstancePtr is a pointer to the Multi Scaler instance Depth (number of coefficient entries) in the memory bank None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_DEPTH_HWREG_MM_VFLTCOEFF_7.
u32 XV_multi_scaler_Write_HwReg_mm_vfltCoeff_7_Words(XV_multi_scaler *InstancePtr, int offset, int *data, int length)
Write words to vertical filter coefficient memory bank 7.
This function writes integer words to the vertical filter coefficient memory bank 7 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the word offset from the base address data is a pointer to the data array to write length is the number of words to write Number of words written, or 0 if the write would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_7_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_7_HIGH.
u32 XV_multi_scaler_Read_HwReg_mm_vfltCoeff_7_Words(XV_multi_scaler *InstancePtr, int offset, int *data, int length)
Read words from vertical filter coefficient memory bank 7.
This function reads integer words from the vertical filter coefficient memory bank 7 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the word offset from the base address data is a pointer to the buffer to store the read data length is the number of words to read Number of words read, or 0 if the read would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_7_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_7_HIGH.
u32 XV_multi_scaler_Write_HwReg_mm_vfltCoeff_7_Bytes(XV_multi_scaler *InstancePtr, int offset, char *data, int length)
Write bytes to vertical filter coefficient memory bank 7.
This function writes individual bytes to the vertical filter coefficient memory bank 7 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the byte offset from the base address data is a pointer to the byte array to write length is the number of bytes to write Number of bytes written, or 0 if the write would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_7_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_7_HIGH.
u32 XV_multi_scaler_Read_HwReg_mm_vfltCoeff_7_Bytes(XV_multi_scaler *InstancePtr, int offset, char *data, int length)
Read bytes from vertical filter coefficient memory bank 7.
This function reads individual bytes from the vertical filter coefficient memory bank 7 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the byte offset from the base address data is a pointer to the buffer to store the read bytes length is the number of bytes to read Number of bytes read, or 0 if the read would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_7_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_VFLTCOEFF_7_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_7_BaseAddress(XV_multi_scaler *InstancePtr)
Get base address of horizontal filter coefficient memory bank 7.
This function returns the base address of the horizontal filter coefficient memory bank 7 in the hardware address space. InstancePtr is a pointer to the Multi Scaler instance Base address of the hfltCoeff_7 memory region None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_7_BASE.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_7_HighAddress(XV_multi_scaler *InstancePtr)
Get high address of horizontal filter coefficient memory bank 7.
This function returns the high address of the horizontal filter coefficient memory bank 7 in the hardware address space. InstancePtr is a pointer to the Multi Scaler instance High address of the hfltCoeff_7 memory region None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_7_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_7_TotalBytes(XV_multi_scaler *InstancePtr)
Get total size of horizontal filter coefficient memory bank 7.
This function returns the total size in bytes of the horizontal filter coefficient memory bank 7. InstancePtr is a pointer to the Multi Scaler instance Total size of the hfltCoeff_7 memory region in bytes None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_7_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_7_HIGH.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_7_BitWidth(XV_multi_scaler *InstancePtr)
Get bit width of horizontal filter coefficient memory bank 7.
This function returns the bit width of each coefficient entry in the horizontal filter coefficient memory bank 7. InstancePtr is a pointer to the Multi Scaler instance Bit width of coefficient entries None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_WIDTH_HWREG_MM_HFLTCOEFF_7.
u32 XV_multi_scaler_Get_HwReg_mm_hfltCoeff_7_Depth(XV_multi_scaler *InstancePtr)
Get depth of horizontal filter coefficient memory bank 7.
This function returns the depth (number of entries) of the horizontal filter coefficient memory bank 7. InstancePtr is a pointer to the Multi Scaler instance Depth (number of coefficient entries) in the memory bank None
References XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_DEPTH_HWREG_MM_HFLTCOEFF_7.
u32 XV_multi_scaler_Write_HwReg_mm_hfltCoeff_7_Words(XV_multi_scaler *InstancePtr, int offset, int *data, int length)
Write words to horizontal filter coefficient memory bank 7.
This function writes integer words to the horizontal filter coefficient memory bank 7 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the word offset from the base address data is a pointer to the data array to write length is the number of words to write Number of words written, or 0 if the write would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_7_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_7_HIGH.
u32 XV_multi_scaler_Read_HwReg_mm_hfltCoeff_7_Words(XV_multi_scaler *InstancePtr, int offset, int *data, int length)
Read words from horizontal filter coefficient memory bank 7.
This function reads integer words from the horizontal filter coefficient memory bank 7 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the word offset from the base address data is a pointer to the buffer to store the read data length is the number of words to read Number of words read, or 0 if the read would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_7_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_7_HIGH.
u32 XV_multi_scaler_Write_HwReg_mm_hfltCoeff_7_Bytes(XV_multi_scaler *InstancePtr, int offset, char *data, int length)
Write bytes to horizontal filter coefficient memory bank 7.
This function writes individual bytes to the horizontal filter coefficient memory bank 7 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the byte offset from the base address data is a pointer to the byte array to write length is the number of bytes to write Number of bytes written, or 0 if the write would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_7_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_7_HIGH.
u32 XV_multi_scaler_Read_HwReg_mm_hfltCoeff_7_Bytes(XV_multi_scaler *InstancePtr, int offset, char *data, int length)
Read bytes from horizontal filter coefficient memory bank 7.
This function reads individual bytes from the horizontal filter coefficient memory bank 7 starting at the specified offset. InstancePtr is a pointer to the Multi Scaler instance offset is the byte offset from the base address data is a pointer to the buffer to store the read bytes length is the number of bytes to read Number of bytes read, or 0 if the read would exceed memory bounds None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_7_BASE, XV_MULTI_SCALER_CTRL_ADDR_HWREG_MM_HFLTCOEFF_7_HIGH.
void XV_multi_scaler_InterruptGlobalEnable(XV_multi_scaler *InstancePtr)
Enable global interrupts for Multi Scaler.
This function enables the global interrupt enable bit, allowing interrupts from the Multi Scaler to be propagated to the system. InstancePtr is a pointer to the Multi Scaler instance None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_GIE, XV_multi_scaler_WriteReg.
Referenced by main.
void XV_multi_scaler_InterruptGlobalDisable(XV_multi_scaler *InstancePtr)
Disable global interrupts for Multi Scaler.
This function disables the global interrupt enable bit, preventing interrupts from the Multi Scaler from reaching the system. InstancePtr is a pointer to the Multi Scaler instance None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_GIE, XV_multi_scaler_WriteReg.
Referenced by XVMultiScalerCallback.
void XV_multi_scaler_InterruptEnable(XV_multi_scaler *InstancePtr, u32 Mask)
Enable specific interrupt sources.
This function enables interrupt sources specified by the mask parameter. Multiple sources can be enabled by ORing the appropriate bits. InstancePtr is a pointer to the Multi Scaler instance Mask is the bitmask of interrupt sources to enable None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_IER, XV_multi_scaler_ReadReg, XV_multi_scaler_WriteReg.
Referenced by main.
void XV_multi_scaler_InterruptDisable(XV_multi_scaler *InstancePtr, u32 Mask)
Disable specific interrupt sources.
This function disables interrupt sources specified by the mask parameter. Multiple sources can be disabled by ORing the appropriate bits. InstancePtr is a pointer to the Multi Scaler instance Mask is the bitmask of interrupt sources to disable None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_IER, XV_multi_scaler_ReadReg, XV_multi_scaler_WriteReg.
Referenced by XVMultiScalerCallback.
void XV_multi_scaler_InterruptClear(XV_multi_scaler *InstancePtr, u32 Mask)
Clear pending interrupts.
This function clears the interrupt status bits specified by the mask parameter. This should be called in the interrupt handler to acknowledge processed interrupts. InstancePtr is a pointer to the Multi Scaler instance Mask is the bitmask of interrupt sources to clear None
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_ISR, XV_multi_scaler_WriteReg.
Referenced by XV_MultiScalerIntrHandler.
u32 XV_multi_scaler_InterruptGetEnabled(XV_multi_scaler *InstancePtr)
Get enabled interrupt sources.
This function returns the current interrupt enable register value indicating which interrupt sources are enabled. InstancePtr is a pointer to the Multi Scaler instance Bitmask of enabled interrupt sources
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_IER, XV_multi_scaler_ReadReg.
u32 XV_multi_scaler_InterruptGetStatus(XV_multi_scaler *InstancePtr)
Get pending interrupt status.
This function returns the current interrupt status register value indicating which interrupt sources are currently pending. InstancePtr is a pointer to the Multi Scaler instance Bitmask of pending interrupt sources
References XV_multi_scaler::Ctrl_BaseAddress, XV_multi_scaler::IsReady, XV_MULTI_SCALER_CTRL_ADDR_ISR, XV_multi_scaler_ReadReg.
Referenced by XV_MultiScalerIntrHandler.
void* XV_MultiScalerIntrHandler(void *data)
This function is the interrupt handler for the MultiScaler core driver.
This handler clears the pending interrupt and determines if the source is frame done signal. If yes, calls the registered callback function.The application is responsible for connecting this function to the interrupt system. InstancePtr is a pointer to the core instance that just interrupted. None. None.
References XV_multi_scaler::IsReady, XV_multi_scaler_InterruptGetStatus, XV_multi_scaler_InterruptClear, XV_MULTI_SCALER_ISR_DONE_BIT_MASK, XV_MULTI_SCALER_ISR_READY_BIT_MASK, XV_multi_scaler::FrameDoneCallback.
Referenced by main.
void XVMultiScaler_SetCallback(XV_multi_scaler *InstancePtr, void *CallbackFunc, void *CallbackRef)
Install an asynchronous callback function for MultiScaler events.
This function registers a user-defined callback function that will be invoked when the MultiScaler IP generates an interrupt. The callback is typically used to handle frame processing completion notifications. InstancePtr is a pointer to the MultiScaler IP instance. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. None Invoking this function for a handler that already has been installed replaces it with the new handler.
References XV_multi_scaler::FrameDoneCallback, XV_multi_scaler::CallbackRef.
Referenced by main.