xv_sdirx_intr.c
XSDIRX_VIDMODE_SHIFT
static void SdiRx_VidLckIntrHandler(XV_SdiRx *InstancePtr)
This function is the interrupt handler for the SDI Video Lock Event.
InstancePtr is a pointer to the XV_SdiRx core instance. Derive the VmId of incoming Rx stream from either SDI Rx registers (for SD/HD modes) or st352 payload registers (for >= 3GA modes).
static void SdiRx_VidUnLckIntrHandler(XV_SdiRx *InstancePtr)
This function is the interrupt handler for the SDI Video Unlock Event.
InstancePtr is a pointer to the XV_SdiRx core instance. None.
static void SdiRx_OverFlowIntrHandler(XV_SdiRx *InstancePtr)
This function is the interrupt handler for the SDI Overflow Event.
InstancePtr is a pointer to the XV_SdiRx core instance. None.
static void SdiRx_UnderFlowIntrHandler(XV_SdiRx *InstancePtr)
This function is the interrupt handler for the SDI Underflow Event.
InstancePtr is a pointer to the XV_SdiRx core instance. None.
static void SdiRx_VsyncIntrHandler(XV_SdiRx *InstancePtr)
This function is the interrupt handler for the SDI Vsync Event.
InstancePtr is a pointer to the XV_SdiRx core instance. None.
u32 XV_SdiRx_GetIntrEnable(XV_SdiRx *InstancePtr)
This function will get the interrupt mask set (enabled) in the SDI Rx core.
InstancePtr is the XV_SdiRx instance to operate on Interrupt Mask with bits set for corresponding interrupt in Interrupt enable register None
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_ReadReg.
u32 XV_SdiRx_GetIntrStatus(XV_SdiRx *InstancePtr)
This function will get the list of interrupts pending in the Interrupt Status Register of the SDI Rx core.
InstancePtr is the XV_SdiRx instance to operate on Interrupt Mask with bits set for corresponding interrupt in Interrupt Status register None
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_ReadReg.
Referenced by XV_SdiRx_IntrHandler.
void XV_SdiRx_InterruptClear(XV_SdiRx *InstancePtr, u32 Mask)
This function will clear the interrupts set in the Interrupt Status Register of the SDI Rx core.
InstancePtr is the XV_SdiRx instance to operate on Mask is Interrupt Mask with bits set for corresponding interrupt to be cleared in the Interrupt Status register None
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_ReadReg, XV_SdiRx_WriteReg.
Referenced by XV_SdiRx_IntrHandler.
void XV_SdiRx_IntrHandler(void *InstancePtr)
This function is the interrupt handler for the SDI RX driver.
This handler reads the pending interrupt for video lock or video unlock interrupts, determines the source of the interrupts, clears the interrupts and calls callbacks accordingly.The application is responsible for connecting this function to the interrupt system. Application beyond this driver is also responsible for providing callbacks to handle interrupts and installing the callbacks using XV_SdiRx_SetCallback() during initialization phase. An example delivered with this driver demonstrates how this could be done. InstancePtr is a pointer to the XV_SdiRx instance that just interrupted. None.
References XV_SdiRx::IsReady, XV_SdiRx_GetIntrStatus, XV_SdiRx_InterruptClear.
int XV_SdiRx_SetCallback(XV_SdiRx *InstancePtr, u32 HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function Type ------------------------- --------------------------------------- (XV_SDIRX_HANDLER_STREAM_DOWN) StreamDownCallback (XV_SDIRX_HANDLER_STREAM_UP) StreamUpCallback (XV_SDIRX_HANDLER_OVERFLOW) OverFlowCallback (XV_SDIRX_HANDLER_UNDERFLOW) UnderFlowCallback (XV_SDIRX_HANDLER_VSYNC) VsyncCallback InstancePtr is a pointer to the SDI RX core instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XV_SdiRx::OverFlowCallback, XV_SdiRx::OverFlowRef, XV_SdiRx::StreamDownCallback, XV_SdiRx::StreamDownRef, XV_SdiRx::StreamUpCallback, XV_SdiRx::StreamUpRef, XV_SdiRx::UnderFlowCallback, XV_SdiRx::UnderFlowRef, XV_SdiRx::VsyncCallback, XV_SdiRx::VsyncRef.
void XV_SdiRx_IntrEnable(XV_SdiRx *InstancePtr, u32 Mask)
This function enables the selected interrupt.
InstancePtr is a pointer to the XV_SdiRx core instance. Mask is the interrupt mask which need to be enabled in core. None.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_ReadReg, XV_SdiRx_WriteReg.
void XV_SdiRx_IntrDisable(XV_SdiRx *InstancePtr, u32 Mask)
This function disables the selected interrupt.
InstancePtr is a pointer to the XV_SdiRx core instance. Mask is the interrupt mask which need to be disabled in core. None.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_WriteReg.
Referenced by XV_SdiRx_CfgInitialize.