xv_sdirx.c
XSDIRX_LINE_RATE_3G
XSDIRX_LINE_RATE_6G
XSDIRX_LINE_RATE_12G8DS
static void StubCallback(void *CallbackRef)
This function is a stub for the asynchronous callback.
The stub is here in case the upper layer forgot to set the handlers. On initialization, all handlers are set to this callback. It is considered an error for this handler to be invoked. CallbackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. None.
static void XV_SdiRx_SetGlobalInterrupt(XV_SdiRx *InstancePtr)
This function is used to enable the global interrupts.
This is used after setting the interrupts mask before enabling the core. InstancePtr is a pointer to the SDI RX Instance to be worked on. None None
static void XV_SdiRx_ResetGlobalInterrupt(XV_SdiRx *InstancePtr)
This function is used to disable the global interrupts.
This is done after disabling the core. InstancePtr is a pointer to the SDI Rx Instance to be worked on. None None
int XV_SdiRx_CfgInitialize(XV_SdiRx *InstancePtr, XV_SdiRx_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the SDI RX core.
This function must be called prior to using the SDI RX core. Initialization of the SDI RX includes setting up the instance data, and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the XV_SdiRx core instance. CfgPtr points to the configuration structure associated with the SDI RX core. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if XV_SdiRx_CfgInitialize was successful.XST_FAILURE if XV_SdiRx_CfgInitialize was unsuccessful. None.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx::IsReady, XV_SdiRx::OverFlowCallback, XV_SdiRx::StreamDownCallback, XV_SdiRx::StreamUpCallback, XV_SdiRx::UnderFlowCallback, XV_SdiRx::VsyncCallback, XV_SdiRx_EnableMode, XV_SdiRx_FramerEnable, XV_SdiRx_IntrDisable, XV_SdiRx_ResetStream, XV_SdiRx_SetEdhErrCntTrigger, XV_SdiRx_SetVidLckWindow, XV_SdiRx_Start, XV_SdiRx_Stop, XV_SDIRX_SUPPORT_12GF, XV_SDIRX_SUPPORT_12GI, XV_SDIRX_SUPPORT_6G, XV_SdiRx_WriteReg.
Referenced by XV_SdiRxSelfTestExample.
void XV_SdiRx_ResetStream(XV_SdiRx *InstancePtr)
This function clears the SDI RX stream variables and sets them to the defaults.
InstancePtr is a pointer to the XV_SdiRx core instance. This is required after a reset or init.
References XV_SdiRx_Stream::CAssignment, XV_SdiRx::Stream, XV_SdiRx_Stream::Video.
Referenced by XV_SdiRx_CfgInitialize.
void XV_SdiRx_DebugInfo(XV_SdiRx *InstancePtr, XV_SdiRx_DebugSelId SelId)
This function prints debug information of Stream 0 on STDIO/Uart console.
InstancePtr is a pointer to the XV_SdiRx core instance. SelId specifies which debug information to be printed out None.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx::Stream, XV_SdiRx_Stream::Video, XV_SdiRx_ReadReg.
int XV_SdiRx_Stop(XV_SdiRx *InstancePtr)
This function stops SDI RX core's modes detection.
InstancePtr is a pointer to the XV_SdiRx core instance. XST_SUCCESS if SDI Rx stop is successful.XST_FAILURE if SDI Rx stop is unsuccessful None.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_ReadReg, XV_SdiRx_WriteReg.
Referenced by XV_SdiRx_CfgInitialize, XV_SdiRx_SelfTest.
void XV_SdiRx_FramerEnable(XV_SdiRx *InstancePtr)
This function enables the framer function.
When enabled, the framer automatically readjusts the output word alignment to match the alignment of each timing reference signal (TRS). InstancePtr is a pointer to the XV_SdiRx core instance. None.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_ReadReg, XV_SdiRx_WriteReg.
Referenced by XV_SdiRx_CfgInitialize.
void XV_SdiRx_FramerDisable(XV_SdiRx *InstancePtr)
This function disables the framer function.
InstancePtr is a pointer to the XV_SdiRx core instance. None.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_ReadReg, XV_SdiRx_WriteReg.
void XV_SdiRx_Start(XV_SdiRx *InstancePtr, XV_SdiRx_SearchMode Mode)
This function enables SDI RX core's modes detection function.
InstancePtr is a pointer to the XV_SdiRx core instance. Mode specifies the mode of SDI modes searching operation. 0 = XV_SDIRX_SINGLESEARCHMODE_HD1 = XV_SDIRX_SINGLESEARCHMODE_SD2 = XV_SDIRX_SINGLESEARCHMODE_3G4 = XV_SDIRX_SINGLESEARCHMODE_6G5 = XV_SDIRX_SINGLESEARCHMODE_12GI6 = XV_SDIRX_SINGLESEARCHMODE_12GF10 = XV_SDIRX_MULTISEARCHMODE where the supported modes will be enabled by XV_SdiRx_EnableMode function None.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_ReadReg, XV_SdiRx_WriteReg.
Referenced by XV_SdiRx_CfgInitialize.
u32 XV_SdiRx_ReportDetectedError(XV_SdiRx *InstancePtr)
This function reports detected CRC or EDH errors count.
InstancePtr is a pointer to the XV_SdiRx core instance. CRC/EDH Error count None.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_GetSdiMode, XV_SdiRx_ReadReg.
void XV_SdiRx_SetYCbCr444_RGB_10bit(XV_SdiRx *InstancePtr)
This function enables 10bit YUV444 and RGB color format support for SDI Rx.
InstancePtr is a pointer to the XV_SdiRx core instance.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_ReadReg, XV_SdiRx_WriteReg.
void XV_SdiRx_ClearYCbCr444_RGB_10bit(XV_SdiRx *InstancePtr)
This function disables 10bit YUV444 and RGB color format support for SDI Rx.
InstancePtr is a pointer to the XV_SdiRx core instance.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_ReadReg, XV_SdiRx_WriteReg.
void XV_SdiRx_VidBridgeEnable(XV_SdiRx *InstancePtr)
This function enables the video bridge.
InstancePtr is a pointer to the XV_SdiRx core instance. None.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_ReadReg, XV_SdiRx_WriteReg.
void XV_SdiRx_VidBridgeDisable(XV_SdiRx *InstancePtr)
This function disables the video bridge.
InstancePtr is a pointer to the XV_SdiRx core instance. None.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_ReadReg, XV_SdiRx_WriteReg.
void XV_SdiRx_Axi4sBridgeEnable(XV_SdiRx *InstancePtr)
This function enable the AXI4S Bridge.
InstancePtr is a pointer to the XV_SdiRx core instance. None.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_ReadReg, XV_SdiRx_WriteReg.
void XV_SdiRx_Axi4sBridgeDisable(XV_SdiRx *InstancePtr)
This function disables the AXI4S Bridge.
InstancePtr is a pointer to the XV_SdiRx core instance. None.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_ReadReg, XV_SdiRx_WriteReg.
u32 XV_SdiRx_GetPayloadId(XV_SdiRx *InstancePtr, u8 DataStream)
This function returns incoming stream's incoming SDI payload ID.
InstancePtr is a pointer to the XV_SdiRx core instance. DataStream specifies which payload ID is to be returned. SDI payload ID None.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_ReadReg.
Referenced by XV_SdiRx_WaitforPayLoad.
u32 XV_SdiRx_WaitforPayLoad(XV_SdiRx *InstancePtr)
This function is used to wait for the payload valid bit to be set.
This has to be called from application based on the callback indication of the video lock interrupt handler. Without this function being called, it may be guaranteed that payload bits are valid after video lock interrupt occurred. InstancePtr is a pointer to the XV_SdiRx core instance. XST_FAILURE if the payload valid bits are not set.XST_SUCCESS if ST352 registers are read and loaded to Rx structures None.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx::Stream, XV_SdiRx_GetPayloadId, XV_SdiRx_ReadReg.
u32 XV_SdiRx_GetSdiMode(XV_SdiRx *InstancePtr)
This function returns the current SDI transport mode detected.
InstancePtr is a pointer to the XV_SdiRx core instance. SDI transport mode None.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_ReadReg.
Referenced by XV_SdiRx_ReportDetectedError.
void XV_SdiRx_SetVidLckWindow(XV_SdiRx *InstancePtr, u32 Data)
This function sets the clock period for video lock signal to be asserted before video lock interrupt is triggered.
InstancePtr is a pointer to the XV_SdiRx core instance. Data specifies the clock period. None.
References XV_SdiRx_WriteReg.
Referenced by XV_SdiRx_CfgInitialize.
void XV_SdiRx_SetEdhErrCntTrigger(XV_SdiRx *InstancePtr, u32 Enable)
This function sets the type of EDH errors which will trigger the error count.
InstancePtr is a pointer to the XV_SdiRx core instance. Enable specifies the type of EDH errors to be allowed to increment the error counter. Bit 0 = ANC EDH errorBit 1 = ANC EDA errorBit 2 = ANC IDH errorBit 3 = ANC IDA errorBit 4 = ANC Unknown Error Status errorBit 5 = FF EDH errorBit 6 = FF EDA errorBit 7 = FF IDH errorBit 8 = FF IDA errorBit 9 = FF Unknown Error Status errorBit 10 = AP EDH errorBit 11 = AP EDA errorBit 12 = AP IDH errorBit 13 = AP IDA errorBit 14 = AP Unknown Error Status errorBit 15 = EDH packet checksum-error None.
References XV_SdiRx_WriteReg.
Referenced by XV_SdiRx_CfgInitialize.
void XV_SdiRx_EnableMode(XV_SdiRx *InstancePtr, XV_SdiRx_SupportedModes SupportModes)
This function enables the modes which the SDI RX core will try to lock on.
InstancePtr is a pointer to the XV_SdiRx core instance. SupportModes specifies which SDI mode is to be supported from SDI mode detection logic. XV_SDIRX_MULTISEARCHMODE must be selected in the XV_SdiRx_Start function.
References XV_SdiRx::Config, XV_SDIRX_SUPPORT_12GF, XV_SDIRX_SUPPORT_12GI, XV_SDIRX_SUPPORT_6G.
Referenced by XV_SdiRx_CfgInitialize.
void XV_SdiRx_DisableMode(XV_SdiRx *InstancePtr, XV_SdiRx_SupportedModes RemoveModes)
This function disables the modes which the SDI RX core will try to lock on.
InstancePtr is a pointer to the XV_SdiRx core instance. RemoveModes specifies which SDI mode is to be removed from SDI mode detection logic. None.
void XV_SdiRx_SetBitDepth(XV_SdiRx *InstancePtr, XVidC_ColorDepth BitDepth)
This function sets the BitDepth configured for the SDI RXSS into SDI RX core.
InstancePtr is a pointer to the XV_SdiRx core instance. BitDepth specifies which BitDepth to be set None.
void XV_SdiRx_HandleNoPayload(XV_SdiRx *InstancePtr, u8 enable)
This function disables generating Video lock interrupt for no payload case.
InstancePtr is a pointer to the XV_SdiRx core instance. enable is to enable/disable the Handling of nopayload case 0 is to disable 1 is to enable