xv_sdirx.h
XV_SdiRx_HandlerType
XV_SdiRx_Modes
HD mode.
XV_SdiRx_DebugSelId
XV_SdiRx_Family_Encoding
SMPTE ST 274 standard.
XV_SdiRx_SupportedModes
Sdi HD.
XV_SdiRx_FrameRate
XV_SDIRX_H_
Prevent circular inclusions by using protection macros.
XV_SDIRX_MAX_DATASTREAM
XV_SDIRX_VID_LCK_WINDOW
XSDIRX_BIT
Generates a bitmask with the nth bit set to 1.
XV_SdiRx_GetVersion
Retrieves the version of the SDI Rx instance.
This macro reads and returns the version register value of the specified SDI Rx instance by accessing the version offset register at the instance's base address. InstancePtr Pointer to the XV_SdiRx instance. The version register value of the SDI Rx instance.
XV_SdiRx_VidLckIntrClr
XV_SdiRx_VidUnlckIntrClr
XV_SdiRx_SearchMode
Sdi HD.
typedef void(* XV_SdiRx_Callback)(void *CallbackRef))(void *CallbackRef)
Callback type for interrupt.
CallbackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. None. None.
XV_SdiRx_Config* XV_SdiRx_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration for a SDI Rx core based on its base address.
BaseAddress The base address of the SDI Rx core to search for. Pointer to the XV_SdiRx_Config structure corresponding to the given BaseAddress. Returns NULL if a matching configuration is not found. This function searches the configuration table for a device matching the specified BaseAddress and returns a pointer to its configuration structure. The configuration structure contains all hardware-specific parameters needed to initialize the SDI Rx core. Looks up the device configuration for a SDI Rx core based on its base address.The return value will refer to an entry in the device configuration table defined in the xv_sdirx_g.c file. DeviceId is the unique core ID of the SDI RX core for the lookup operation. XV_SdiRx_LookupConfig returns a reference to a config record in the configuration table (in xv_sdirx_g.c) corresponding to DeviceId, or NULL if no match is found. None. Look up the configuration for an SDI Rx device based on its base address. BaseAddress The base address of the SDI Rx device to look up. A pointer to the XV_SdiRx_Config structure for the device at the specified base address, or NULL if no matching configuration is found. This function searches the configuration table for a device matching the provided base address and returns the corresponding configuration. If no match is found, NULL is returned.
Referenced by XV_SdiRxSelfTestExample.
int XV_SdiRx_CfgInitialize(XV_SdiRx *InstancePtr, XV_SdiRx_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the SDI RX core.
This function must be called prior to using the SDI RX core. Initialization of the SDI RX includes setting up the instance data, and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the XV_SdiRx core instance. CfgPtr points to the configuration structure associated with the SDI RX core. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if XV_SdiRx_CfgInitialize was successful.XST_FAILURE if XV_SdiRx_CfgInitialize was unsuccessful. None.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx::IsReady, XV_SdiRx::OverFlowCallback, XV_SdiRx::StreamDownCallback, XV_SdiRx::StreamUpCallback, XV_SdiRx::UnderFlowCallback, XV_SdiRx::VsyncCallback, XV_SdiRx_EnableMode, XV_SdiRx_FramerEnable, XV_SdiRx_IntrDisable, XV_SdiRx_ResetStream, XV_SdiRx_SetEdhErrCntTrigger, XV_SdiRx_SetVidLckWindow, XV_SdiRx_Start, XV_SdiRx_Stop, XV_SDIRX_SUPPORT_12GF, XV_SDIRX_SUPPORT_12GI, XV_SDIRX_SUPPORT_6G, XV_SdiRx_WriteReg.
Referenced by XV_SdiRxSelfTestExample.
void XV_SdiRx_ResetStream(XV_SdiRx *InstancePtr)
This function clears the SDI RX stream variables and sets them to the defaults.
InstancePtr is a pointer to the XV_SdiRx core instance. This is required after a reset or init.
References XV_SdiRx_Stream::CAssignment, XV_SdiRx::Stream, XV_SdiRx_Stream::Video.
Referenced by XV_SdiRx_CfgInitialize.
u32 XV_SdiRx_GetPayloadId(XV_SdiRx *InstancePtr, u8 DataStream)
This function returns incoming stream's incoming SDI payload ID.
InstancePtr is a pointer to the XV_SdiRx core instance. DataStream specifies which payload ID is to be returned. SDI payload ID None.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_ReadReg.
Referenced by XV_SdiRx_WaitforPayLoad.
u32 XV_SdiRx_WaitforPayLoad(XV_SdiRx *InstancePtr)
This function is used to wait for the payload valid bit to be set.
This has to be called from application based on the callback indication of the video lock interrupt handler. Without this function being called, it may be guaranteed that payload bits are valid after video lock interrupt occurred. InstancePtr is a pointer to the XV_SdiRx core instance. XST_FAILURE if the payload valid bits are not set.XST_SUCCESS if ST352 registers are read and loaded to Rx structures None.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx::Stream, XV_SdiRx_GetPayloadId, XV_SdiRx_ReadReg.
u32 XV_SdiRx_GetSdiMode(XV_SdiRx *InstancePtr)
This function returns the current SDI transport mode detected.
InstancePtr is a pointer to the XV_SdiRx core instance. SDI transport mode None.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_ReadReg.
Referenced by XV_SdiRx_ReportDetectedError.
void XV_SdiRx_FramerEnable(XV_SdiRx *InstancePtr)
This function enables the framer function.
When enabled, the framer automatically readjusts the output word alignment to match the alignment of each timing reference signal (TRS). InstancePtr is a pointer to the XV_SdiRx core instance. None.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_ReadReg, XV_SdiRx_WriteReg.
Referenced by XV_SdiRx_CfgInitialize.
void XV_SdiRx_FramerDisable(XV_SdiRx *InstancePtr)
This function disables the framer function.
InstancePtr is a pointer to the XV_SdiRx core instance. None.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_ReadReg, XV_SdiRx_WriteReg.
void XV_SdiRx_SetEdhErrCntTrigger(XV_SdiRx *InstancePtr, u32 Enable)
This function sets the type of EDH errors which will trigger the error count.
InstancePtr is a pointer to the XV_SdiRx core instance. Enable specifies the type of EDH errors to be allowed to increment the error counter. Bit 0 = ANC EDH errorBit 1 = ANC EDA errorBit 2 = ANC IDH errorBit 3 = ANC IDA errorBit 4 = ANC Unknown Error Status errorBit 5 = FF EDH errorBit 6 = FF EDA errorBit 7 = FF IDH errorBit 8 = FF IDA errorBit 9 = FF Unknown Error Status errorBit 10 = AP EDH errorBit 11 = AP EDA errorBit 12 = AP IDH errorBit 13 = AP IDA errorBit 14 = AP Unknown Error Status errorBit 15 = EDH packet checksum-error None.
References XV_SdiRx_WriteReg.
Referenced by XV_SdiRx_CfgInitialize.
void XV_SdiRx_EnableMode(XV_SdiRx *InstancePtr, XV_SdiRx_SupportedModes SupportModes)
This function enables the modes which the SDI RX core will try to lock on.
InstancePtr is a pointer to the XV_SdiRx core instance. SupportModes specifies which SDI mode is to be supported from SDI mode detection logic. XV_SDIRX_MULTISEARCHMODE must be selected in the XV_SdiRx_Start function.
References XV_SdiRx::Config, XV_SDIRX_SUPPORT_12GF, XV_SDIRX_SUPPORT_12GI, XV_SDIRX_SUPPORT_6G.
Referenced by XV_SdiRx_CfgInitialize.
void XV_SdiRx_DisableMode(XV_SdiRx *InstancePtr, XV_SdiRx_SupportedModes RemoveModes)
This function disables the modes which the SDI RX core will try to lock on.
InstancePtr is a pointer to the XV_SdiRx core instance. RemoveModes specifies which SDI mode is to be removed from SDI mode detection logic. None.
void XV_SdiRx_Start(XV_SdiRx *InstancePtr, XV_SdiRx_SearchMode Mode)
This function enables SDI RX core's modes detection function.
InstancePtr is a pointer to the XV_SdiRx core instance. Mode specifies the mode of SDI modes searching operation. 0 = XV_SDIRX_SINGLESEARCHMODE_HD1 = XV_SDIRX_SINGLESEARCHMODE_SD2 = XV_SDIRX_SINGLESEARCHMODE_3G4 = XV_SDIRX_SINGLESEARCHMODE_6G5 = XV_SDIRX_SINGLESEARCHMODE_12GI6 = XV_SDIRX_SINGLESEARCHMODE_12GF10 = XV_SDIRX_MULTISEARCHMODE where the supported modes will be enabled by XV_SdiRx_EnableMode function None.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_ReadReg, XV_SdiRx_WriteReg.
Referenced by XV_SdiRx_CfgInitialize.
int XV_SdiRx_Stop(XV_SdiRx *InstancePtr)
This function stops SDI RX core's modes detection.
InstancePtr is a pointer to the XV_SdiRx core instance. XST_SUCCESS if SDI Rx stop is successful.XST_FAILURE if SDI Rx stop is unsuccessful None.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_ReadReg, XV_SdiRx_WriteReg.
Referenced by XV_SdiRx_CfgInitialize, XV_SdiRx_SelfTest.
u32 XV_SdiRx_ReportDetectedError(XV_SdiRx *InstancePtr)
This function reports detected CRC or EDH errors count.
InstancePtr is a pointer to the XV_SdiRx core instance. CRC/EDH Error count None.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_GetSdiMode, XV_SdiRx_ReadReg.
void XV_SdiRx_SetYCbCr444_RGB_10bit(XV_SdiRx *InstancePtr)
This function enables 10bit YUV444 and RGB color format support for SDI Rx.
InstancePtr is a pointer to the XV_SdiRx core instance.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_ReadReg, XV_SdiRx_WriteReg.
void XV_SdiRx_ClearYCbCr444_RGB_10bit(XV_SdiRx *InstancePtr)
This function disables 10bit YUV444 and RGB color format support for SDI Rx.
InstancePtr is a pointer to the XV_SdiRx core instance.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_ReadReg, XV_SdiRx_WriteReg.
void XV_SdiRx_SetVidLckWindow(XV_SdiRx *InstancePtr, u32 Data)
This function sets the clock period for video lock signal to be asserted before video lock interrupt is triggered.
InstancePtr is a pointer to the XV_SdiRx core instance. Data specifies the clock period. None.
References XV_SdiRx_WriteReg.
Referenced by XV_SdiRx_CfgInitialize.
void XV_SdiRx_VidBridgeEnable(XV_SdiRx *InstancePtr)
This function enables the video bridge.
InstancePtr is a pointer to the XV_SdiRx core instance. None.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_ReadReg, XV_SdiRx_WriteReg.
void XV_SdiRx_VidBridgeDisable(XV_SdiRx *InstancePtr)
This function disables the video bridge.
InstancePtr is a pointer to the XV_SdiRx core instance. None.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_ReadReg, XV_SdiRx_WriteReg.
void XV_SdiRx_Axi4sBridgeEnable(XV_SdiRx *InstancePtr)
This function enable the AXI4S Bridge.
InstancePtr is a pointer to the XV_SdiRx core instance. None.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_ReadReg, XV_SdiRx_WriteReg.
void XV_SdiRx_Axi4sBridgeDisable(XV_SdiRx *InstancePtr)
This function disables the AXI4S Bridge.
InstancePtr is a pointer to the XV_SdiRx core instance. None.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_ReadReg, XV_SdiRx_WriteReg.
void XV_SdiRx_DebugInfo(XV_SdiRx *InstancePtr, XV_SdiRx_DebugSelId SelId)
This function prints debug information of Stream 0 on STDIO/Uart console.
InstancePtr is a pointer to the XV_SdiRx core instance. SelId specifies which debug information to be printed out None.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx::Stream, XV_SdiRx_Stream::Video, XV_SdiRx_ReadReg.
u32 XV_SdiRx_SelfTest(XV_SdiRx *InstancePtr)
Runs a self-test on the driver/device.
This test checks if the LaneCount present in register matches the one from the generated file. InstancePtr is a pointer to the XV_SdiRx instance. XST_SUCCESS if self-test was successfulXST_FAILURE if the read value was not equal to _g.c file None
References XV_SdiRx::IsReady, XV_SdiRx_Stop, XV_SdiRx_ReadReg, XV_SdiRx::Config, XV_SdiRx_Config::BaseAddress.
Referenced by XV_SdiRxSelfTestExample.
u32 XV_SdiRx_GetIntrEnable(XV_SdiRx *InstancePtr)
This function will get the interrupt mask set (enabled) in the SDI Rx core.
InstancePtr is the XV_SdiRx instance to operate on Interrupt Mask with bits set for corresponding interrupt in Interrupt enable register None
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_ReadReg.
u32 XV_SdiRx_GetIntrStatus(XV_SdiRx *InstancePtr)
This function will get the list of interrupts pending in the Interrupt Status Register of the SDI Rx core.
InstancePtr is the XV_SdiRx instance to operate on Interrupt Mask with bits set for corresponding interrupt in Interrupt Status register None
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_ReadReg.
Referenced by XV_SdiRx_IntrHandler.
void XV_SdiRx_InterruptClear(XV_SdiRx *InstancePtr, u32 Mask)
This function will clear the interrupts set in the Interrupt Status Register of the SDI Rx core.
InstancePtr is the XV_SdiRx instance to operate on Mask is Interrupt Mask with bits set for corresponding interrupt to be cleared in the Interrupt Status register None
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_ReadReg, XV_SdiRx_WriteReg.
Referenced by XV_SdiRx_IntrHandler.
void XV_SdiRx_IntrHandler(void *InstancePtr)
This function is the interrupt handler for the SDI RX driver.
This handler reads the pending interrupt for video lock or video unlock interrupts, determines the source of the interrupts, clears the interrupts and calls callbacks accordingly.The application is responsible for connecting this function to the interrupt system. Application beyond this driver is also responsible for providing callbacks to handle interrupts and installing the callbacks using XV_SdiRx_SetCallback() during initialization phase. An example delivered with this driver demonstrates how this could be done. InstancePtr is a pointer to the XV_SdiRx instance that just interrupted. None.
References XV_SdiRx::IsReady, XV_SdiRx_GetIntrStatus, XV_SdiRx_InterruptClear.
int XV_SdiRx_SetCallback(XV_SdiRx *InstancePtr, u32 HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function Type ------------------------- --------------------------------------- (XV_SDIRX_HANDLER_STREAM_DOWN) StreamDownCallback (XV_SDIRX_HANDLER_STREAM_UP) StreamUpCallback (XV_SDIRX_HANDLER_OVERFLOW) OverFlowCallback (XV_SDIRX_HANDLER_UNDERFLOW) UnderFlowCallback (XV_SDIRX_HANDLER_VSYNC) VsyncCallback InstancePtr is a pointer to the SDI RX core instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XV_SdiRx::OverFlowCallback, XV_SdiRx::OverFlowRef, XV_SdiRx::StreamDownCallback, XV_SdiRx::StreamDownRef, XV_SdiRx::StreamUpCallback, XV_SdiRx::StreamUpRef, XV_SdiRx::UnderFlowCallback, XV_SdiRx::UnderFlowRef, XV_SdiRx::VsyncCallback, XV_SdiRx::VsyncRef.
void XV_SdiRx_IntrDisable(XV_SdiRx *InstancePtr, u32 Mask)
This function disables the selected interrupt.
InstancePtr is a pointer to the XV_SdiRx core instance. Mask is the interrupt mask which need to be disabled in core. None.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_WriteReg.
Referenced by XV_SdiRx_CfgInitialize.
void XV_SdiRx_IntrEnable(XV_SdiRx *InstancePtr, u32 Mask)
This function enables the selected interrupt.
InstancePtr is a pointer to the XV_SdiRx core instance. Mask is the interrupt mask which need to be enabled in core. None.
References XV_SdiRx_Config::BaseAddress, XV_SdiRx::Config, XV_SdiRx_ReadReg, XV_SdiRx_WriteReg.
void XV_SdiRx_SetBitDepth(XV_SdiRx *InstancePtr, XVidC_ColorDepth BitDepth)
This function sets the BitDepth configured for the SDI RXSS into SDI RX core.
InstancePtr is a pointer to the XV_SdiRx core instance. BitDepth specifies which BitDepth to be set None.
void XV_SdiRx_HandleNoPayload(XV_SdiRx *InstancePtr, u8 enable)
This function disables generating Video lock interrupt for no payload case.
InstancePtr is a pointer to the XV_SdiRx core instance. enable is to enable/disable the Handling of nopayload case 0 is to disable 1 is to enable