
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version:
* DO NOT EDIT.
*
* Copyright (C) 2018 Xilinx, Inc. All Rights Reserved.*
*Permission is hereby granted, free of charge, to any person obtaining a copy
*of this software and associated documentation files (the Software), to deal
*in the Software without restriction, including without limitation the rights
*to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*copies of the Software, and to permit persons to whom the Software is
*furnished to do so, subject to the following conditions:
*
*The above copyright notice and this permission notice shall be included in
*all copies or substantial portions of the Software.
*
*THE SOFTWARE IS PROVIDED AS IS, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
*THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
*LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
*OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
*SOFTWARE.
*
*
*

*
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xpciepsu.h"

/*
* The configuration table for devices
*/

XPciePsu_Config XPciePsu_ConfigTable[] =
{
	{
		XPAR_PSU_PCIE_DEVICE_ID,
		XPAR_PSU_PCIE_BASEADDR,
		XPAR_PSU_PCIE_ATTRIB_0_BASEADDR,
		XPAR_PSU_PCIE_HIGH2_BASEADDR,
		XPAR_PSU_PCIE_LOW_BASEADDR,
		XPAR_PSU_PCIE_HIGH1_BASEADDR,
		XPAR_PSU_PCIE_LOW_HIGHADDR,
		XPAR_PSU_PCIE_HIGH1_HIGHADDR
	}
};
