zdma
XZDMA_ERR_CTRL
XZDMA_CH_ECO
XZDMA_CH_ISR_OFFSET
XZDMA_CH_IMR_OFFSET
XZDMA_CH_IEN_OFFSET
XZDMA_CH_IDS_OFFSET
XZDMA_CH_CTRL0_OFFSET
XZDMA_CH_CTRL1_OFFSET
XZDMA_CH_PERIF_OFFSET
XZDMA_CH_STS_OFFSET
XZDMA_CH_DATA_ATTR_OFFSET
XZDMA_CH_DSCR_ATTR_OFFSET
XZDMA_CH_SRC_DSCR_WORD0_OFFSET
XZDMA_CH_SRC_DSCR_WORD1_OFFSET
XZDMA_CH_SRC_DSCR_WORD2_OFFSET
XZDMA_CH_SRC_DSCR_WORD3_OFFSET
XZDMA_CH_DST_DSCR_WORD0_OFFSET
XZDMA_CH_DST_DSCR_WORD1_OFFSET
XZDMA_CH_DST_DSCR_WORD2_OFFSET
XZDMA_CH_DST_DSCR_WORD3_OFFSET
XZDMA_CH_WR_ONLY_WORD0_OFFSET
XZDMA_CH_WR_ONLY_WORD1_OFFSET
XZDMA_CH_WR_ONLY_WORD2_OFFSET
XZDMA_CH_WR_ONLY_WORD3_OFFSET
XZDMA_CH_SRC_START_LSB_OFFSET
XZDMA_CH_SRC_START_MSB_OFFSET
XZDMA_CH_DST_START_LSB_OFFSET
XZDMA_CH_DST_START_MSB_OFFSET
XZDMA_CH_SRC_CUR_PYLD_LSB_OFFSET
XZDMA_CH_SRC_CUR_PYLD_MSB_OFFSET
XZDMA_CH_DST_CUR_PYLD_LSB_OFFSET
XZDMA_CH_DST_CUR_PYLD_MSB_OFFSET
XZDMA_CH_SRC_CUR_DSCR_LSB_OFFSET
XZDMA_CH_SRC_CUR_DSCR_MSB_OFFSET
XZDMA_CH_DST_CUR_DSCR_LSB_OFFSET
XZDMA_CH_DST_CUR_DSCR_MSB_OFFSET
XZDMA_CH_TOTAL_BYTE_OFFSET
XZDMA_CH_RATE_CNTL_OFFSET
XZDMA_CH_IRQ_SRC_ACCT_OFFSET
XZDMA_CH_IRQ_DST_ACCT_OFFSET
XZDMA_CH_CTRL2_OFFSET
XZDMA_IRQ_REG_OFFSET
XZDMA_IXR_DMA_PAUSE_MASK
IXR pause mask.
Referenced by XZDma_IntrHandler, XZDma_LinearExample.
XZDMA_IXR_DMA_DONE_MASK
IXR done mask.
Referenced by XZDma_IntrHandler, XZDma_LinearExample, XZDma_LinkedListExample, XZDma_SimpleReadOnlyExample, XZDma_WriteOnlyExample.
XZDMA_IXR_AXI_WR_DATA_MASK
IXR AXI write data error mask.
Referenced by XZDma_IntrHandler, XZDma_SimpleExample.
XZDMA_IXR_AXI_RD_DATA_MASK
IXR AXI read data error mask.
Referenced by XZDma_IntrHandler, XZDma_SimpleExample.
XZDMA_IXR_AXI_RD_DST_DSCR_MASK
IXR AXI read descriptor error mask.
Referenced by XZDma_IntrHandler.
XZDMA_IXR_AXI_RD_SRC_DSCR_MASK
IXR AXI write descriptor error mask.
Referenced by XZDma_IntrHandler.
XZDMA_IXR_DST_ACCT_ERR_MASK
IXR DST interrupt count overflow mask.
XZDMA_IXR_SRC_ACCT_ERR_MASK
IXR SRC interrupt count overflow mask.
XZDMA_IXR_BYTE_CNT_OVRFL_MASK
IXR byte count over flow mask.
XZDMA_IXR_DST_DSCR_DONE_MASK
IXR destination descriptor done mask.
XZDMA_IXR_SRC_DSCR_DONE_MASK
IXR source descriptor done mask.
XZDMA_IXR_INV_APB_MASK
IXR invalid APB access mask.
XZDMA_IXR_ALL_INTR_MASK
IXR OR of all the interrupts mask.
Referenced by XZDma_Enable, XZDma_IntrHandler, XZDma_Reset, XZDma_SimpleExample.
XZDMA_IXR_DONE_MASK
IXR All done mask.
XZDMA_IXR_ERR_MASK
IXR all Error mask.
Or of XZDMA_IXR_AXI_WR_DATA_MASK, XZDMA_IXR_AXI_RD_DATA_MASK, XZDMA_IXR_AXI_RD_DST_DSCR_MASK, XZDMA_IXR_AXI_RD_SRC_DSCR_MASK, XZDMA_IXR_INV_APB_MASK, XZDMA_IXR_DMA_PAUSE_MASK, XZDMA_IXR_BYTE_CNT_OVRFL_MASK, XZDMA_IXR_SRC_ACCT_ERR_MASK, XZDMA_IXR_DST_ACCT_ERR_MASK
Referenced by XZDma_IntrHandler.
XZDMA_CTRL0_OVR_FETCH_MASK
Over fetch mask.
Referenced by XZDma_SelfTest, XZDma_SetChDataConfig.
XZDMA_CTRL0_POINT_TYPE_MASK
Pointer type mask.
Referenced by XZDma_SetMode.
XZDMA_CTRL0_MODE_MASK
Mode mask.
Referenced by XZDma_SetMode.
XZDMA_CTRL0_WRONLY_MASK
Write only mask.
Referenced by XZDma_SetMode.
XZDMA_CTRL0_RDONLY_MASK
Read only mask.
Referenced by XZDma_SetMode.
XZDMA_CTRL0_RATE_CNTL_MASK
Rate control mask.
XZDMA_CTRL0_CONT_ADDR_MASK
Continue address specified mask.
Referenced by XZDma_Resume.
XZDMA_CTRL0_CONT_MASK
Continue mask.
Referenced by XZDma_Resume.
XZDMA_CTRL0_OVR_FETCH_SHIFT
Over fetch shift.
Referenced by XZDma_SetChDataConfig.
XZDMA_CTRL0_POINT_TYPE_SHIFT
Pointer type shift.
XZDMA_CTRL0_MODE_SHIFT
Mode type shift.
XZDMA_CTRL0_RESET_VALUE
CTRL0 reset value.
Referenced by XZDma_Reset.
XZDMA_CTRL1_SRC_ISSUE_MASK
Source issue mask.
Referenced by XZDma_SetChDataConfig.
XZDMA_CTRL1_RESET_VALUE
CTRL1 reset value.
Referenced by XZDma_Reset.
XZDMA_PERIF_PROG_CELL_CNT_MASK
Peripheral program cell count.
XZDMA_PERIF_SIDE_MASK
Interface attached the side mask.
XZDMA_PERIF_EN_MASK
Peripheral flow control mask.
XZDMA_STS_DONE_ERR_MASK
Done with errors mask.
Referenced by XZDma_ChannelState.
XZDMA_STS_BUSY_MASK
ZDMA is busy in transfer mask.
XZDMA_STS_PAUSE_MASK
ZDMA is in Pause state mask.
Referenced by XZDma_ChannelState.
XZDMA_STS_DONE_MASK
ZDMA done mask.
Referenced by XZDma_ChannelState.
XZDMA_STS_ALL_MASK
ZDMA status mask.
Referenced by XZDma_ChannelState.
XZDMA_DATA_ATTR_ARBURST_MASK
Data ArBurst mask.
Referenced by XZDma_SetChDataConfig.
XZDMA_DATA_ATTR_ARCACHE_MASK
Data ArCache mask.
Referenced by XZDma_SetChDataConfig.
XZDMA_DATA_ATTR_ARQOS_MASK
Data ARQos masks.
Referenced by XZDma_SetChDataConfig.
XZDMA_DATA_ATTR_ARLEN_MASK
Data Arlen mask.
Referenced by XZDma_SetChDataConfig.
XZDMA_DATA_ATTR_AWBURST_MASK
Data Awburst mask.
Referenced by XZDma_SetChDataConfig.
XZDMA_DATA_ATTR_AWCACHE_MASK
Data AwCache mask.
Referenced by XZDma_SetChDataConfig.
XZDMA_DATA_ATTR_AWQOS_MASK
Data AwQos mask.
Referenced by XZDma_SetChDataConfig.
XZDMA_DATA_ATTR_AWLEN_MASK
Data Awlen mask.
Referenced by XZDma_SetChDataConfig.
XZDMA_DATA_ATTR_ARBURST_SHIFT
Data Arburst shift.
Referenced by XZDma_SetChDataConfig.
XZDMA_DATA_ATTR_ARCACHE_SHIFT
Data ArCache shift.
Referenced by XZDma_SetChDataConfig.
XZDMA_DATA_ATTR_ARQOS_SHIFT
Data ARQos shift.
Referenced by XZDma_SetChDataConfig.
XZDMA_DATA_ATTR_ARLEN_SHIFT
Data Arlen shift.
Referenced by XZDma_SetChDataConfig.
XZDMA_DATA_ATTR_AWBURST_SHIFT
Data Awburst shift.
Referenced by XZDma_SetChDataConfig.
XZDMA_DATA_ATTR_AWCACHE_SHIFT
Data Awcache shift.
Referenced by XZDma_SetChDataConfig.
XZDMA_DATA_ATTR_AWQOS_SHIFT
Data Awqos shift.
Referenced by XZDma_SetChDataConfig.
XZDMA_DATA_ATTR_RESET_VALUE
Data Attributes reset value.
Referenced by XZDma_Reset.
XZDMA_DSCR_ATTR_AXCOHRNT_MASK
Descriptor coherent mask.
Referenced by XZDma_SetChDscrConfig.
XZDMA_DSCR_ATTR_AXCACHE_MASK
Descriptor cache mask.
Referenced by XZDma_SetChDscrConfig.
XZDMA_DSCR_ATTR_AXQOS_MASK
Descriptor AxQos mask.
Referenced by XZDma_SetChDscrConfig.
XZDMA_DSCR_ATTR_AXCOHRNT_SHIFT
Descriptor coherent shift.
Referenced by XZDma_Reset, XZDma_SetChDscrConfig.
XZDMA_DSCR_ATTR_AXCACHE_SHIFT
Descriptor cache shift.
Referenced by XZDma_SetChDscrConfig.
XZDMA_DSCR_ATTR_RESET_VALUE
Dscr Attributes reset value.
Referenced by XZDma_Reset.
XZDMA_WORD0_LSB_MASK
LSB Address mask.
Referenced by XZDma_ScatterGather.
XZDMA_WORD1_MSB_MASK
MSB Address mask.
Referenced by XZDma_ScatterGather.
XZDMA_WORD1_MSB_SHIFT
MSB Address shift.
Referenced by XZDma_ScatterGather.
XZDMA_WORD2_SIZE_MASK
Size mask.
XZDMA_WORD3_CMD_MASK
Cmd mask.
XZDMA_WORD3_CMD_SHIFT
Cmd shift.
XZDMA_WORD3_CMD_NXTVALID_MASK
Next Dscr is valid mask.
XZDMA_WORD3_CMD_PAUSE_MASK
Pause after this dscr mask.
XZDMA_WORD3_CMD_STOP_MASK
Stop after this ..* dscr mask.
XZDMA_WORD3_INTR_MASK
Interrupt enable or disable mask.
XZDMA_WORD3_INTR_SHIFT
Interrupt enable disable shift.
XZDMA_WORD3_TYPE_MASK
Type of Descriptor mask.
XZDMA_WORD3_TYPE_SHIFT
Type of Descriptor Shift.
XZDMA_WORD3_COHRNT_MASK
Coherence mask.
Referenced by XZDma_Reset.
XZDMA_START_MSB_ADDR_MASK
Start msb address mask.
XZDMA_CH_RATE_CNTL_MASK
Channel rate control mask.
XZDMA_CH_IRQ_ACCT_MASK
Interrupt count mask.
XZDMA_CH_DBG_CMN_BUF_MASK
Common buffer count mask.
XZDMA_CH_CTRL2_EN_MASK
Channel enable mask.
XZDMA_CH_CTRL2_DIS_MASK
Channel disable mask.
XZDMA_WRITE_TO_CLEAR_MASK
Write to clear mask.
XZDma_Handler
For Done Handler.
static void StubCallBack(void *CallBackRef, u32 Mask)
This routine is a stub for the asynchronous callbacks.
The stub is here in case the upper layer forgot to set the handlers. On initialization, All handlers are set to this callback. It is considered an error for this handler to be invoked. CallBackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. Mask is the type of the interrupts to enable. Use OR'ing of XZDMA_IXR_DMA_*_MASK constants defined in xzdma_hw.h to create this parameter value. None. None.
static void StubDoneCallBack(void *CallBackRef)
This routine is a stub for the DMA done callback.
The stub is here in case the upper layer forgot to set the handlers. On initialization, Done handler are set to this callback. CallBackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. None. None.
static void XZDma_SimpleMode(XZDma *InstancePtr, XZDma_Transfer *Data)
This static function sets all the required fields for initiating data transfer in simple mode.
InstancePtr is a pointer to the XZDma instance. Data is a pointer of array to the XZDma_Transfer structure which has all the configuration fields for initiating data transfer. None. None.
static void XZDma_LinearMode(XZDma *InstancePtr, XZDma_Transfer *Data, XZDma_LiDscr *SrcDscrPtr, XZDma_LiDscr *DstDscrPtr, u8 IsLast)
This static function sets all the required fields for initiating data transfer in Linear descriptor type.
InstancePtr is a pointer to the XZDma instance. Data is a pointer of array to the XZDma_Transfer structure which has all the configuration fields for initiating data transfer. SrcDscrPtr is descriptor pointer of source in which Data fields has to be filled. DstDscrPtr is descriptor pointer of destination in which Data fields has to be filled. IsLast specifies whether provided descriptor pointer is last one or not. XZDMA_TRUE - If descriptor is lastXZDMA_FALSE - If descriptor is not last None. None.
static void XZDma_ConfigLinear(XZDma_LiDscr *DscrPtr, u64 Addr, u32 Size, u32 CtrlValue)
This static function sets all the required fields for initiating data transfer in Linear descriptor type.
DscrPtr is a pointer to source/destination descriptor. Addr is a 64 bit variable which denotes the address of data. Size specifies the amount of the data to be transferred. CtrlValue contains all the control fields of descriptor. None. None.
static void XZDma_LinkedListMode(XZDma *InstancePtr, XZDma_Transfer *Data, XZDma_LlDscr *SrcDscrPtr, XZDma_LlDscr *DstDscrPtr, u8 IsLast)
This static function sets all the required fields for initiating data transfer in Linked list descriptor type.
InstancePtr is a pointer to the XZDma instance. Data is a pointer of array to the XZDma_Transfer structure which has all the configuration fields for initiating data transfer. SrcDscrPtr is descriptor pointer of source in which Data fields has to be filled. DstDscrPtr is descriptor pointer of destination in which Data fields has to be filled. IsLast specifies whether provided descriptor pointer is last one or not. TRUE - If descriptor is lastFALSE - If descriptor is not last None. None.
static void XZDma_ConfigLinkedList(XZDma_LlDscr *DscrPtr, u64 Addr, u32 Size, u32 CtrlValue, u64 NextDscrAddr)
This static function sets all the required fields for initiating data transfer in Linked list descriptor type.
DscrPtr is a pointer to source/destination descriptor. Addr is a 64 bit variable which denotes the address of data. Size specifies the amount of the data to be transferred. CtrlValue contains all the control fields of descriptor. NextDscrAddr is the address of next descriptor. None. None.
static void XZDma_GetConfigurations(XZDma *InstancePtr)
This static function gets all the reset configurations of ZDMA.
InstancePtr is a pointer to the XZDma instance. None. None.
s32 XZDma_CfgInitialize(XZDma *InstancePtr, XZDma_Config *CfgPtr, u32 EffectiveAddr)
This function initializes an ZDMA core.
This function must be called prior to using an ZDMA core. Initialization of an ZDMA includes setting up the instance data and ensuring the hardware is in a quiescent state and resets all the hardware configurations. InstancePtr is a pointer to the XZDma instance. CfgPtr is a reference to a structure containing information about a specific XZDma instance. EffectiveAddr is the device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, pass in the physical address instead. XST_SUCCESS if initialization was successful. None.
References XZDma_Config::BaseAddress, XZDma::ChannelState, XZDma::Config, XZDma_Config::DmaType, XZDma::DoneHandler, XZDma::ErrorHandler, XZDma::IntrMask, XZDma::irq_offset, XZDma_Config::IsCacheCoherent, XZDma::IsReady, XZDma::IsSgDma, XZDma::Mode, XZDma_Config::Name, XZDMA_IDLE, XZDMA_NORMAL_MODE, XZDma_Reset.
Referenced by XZDma_LinearExample, XZDma_LinkedListExample, XZDma_SelfTestExample, XZDma_SimpleExample, XZDma_SimpleReadOnlyExample, XZDma_WriteOnlyExample.
s32 XZDma_SetMode(XZDma *InstancePtr, u8 IsSgDma, XZDma_Mode Mode)
This function sets the pointer type and mode in which ZDMA needs to transfer the data.
InstancePtr is a pointer to the XZDma instance. IsSgDma is a variable which specifies whether transfer has to to be done in scatter gather mode or simple mode. TRUE - Scatter gather pointer typeFALSE - Simple pointer type Mode is the type of the mode in which data has to be initiated XZDMA_NORMAL_MODE - Normal data transfer from source to destination (Valid for both Scatter gather and simple types)XZDMA_WRONLY_MODE - Write only mode (Valid only for Simple)XZDMA_RDONLY_MODE - Read only mode (Valid only for Simple) XST_SUCCESS - If mode has been set successfully.XST_FAILURE - If mode has not been set. Mode cannot be changed while ZDMA is not in IDLE state.
References XZDma_Config::BaseAddress, XZDma::ChannelState, XZDma::Config, XZDma::IsSgDma, XZDma::Mode, XZDMA_CTRL0_MODE_MASK, XZDMA_CTRL0_POINT_TYPE_MASK, XZDMA_CTRL0_RDONLY_MASK, XZDMA_CTRL0_WRONLY_MASK, XZDMA_IDLE, XZDMA_NORMAL_MODE, XZDMA_RDONLY_MODE, XZDma_ReadReg, XZDma_WriteReg, XZDMA_WRONLY_MODE.
Referenced by XZDma_LinearExample, XZDma_LinkedListExample, XZDma_SimpleExample, XZDma_SimpleReadOnlyExample, XZDma_WriteOnlyExample.
u32 XZDma_CreateBDList(XZDma *InstancePtr, XZDma_DscrType TypeOfDscr, UINTPTR Dscr_MemPtr, u32 NoOfBytes)
This function sets the descriptor type and descriptor pointer's start address of both source and destination based on the memory allocated by user and also calculates no of descriptors(BDs) can be created in the allocated memory.
InstancePtr is a pointer to the XZDma instance. TypeOfDscr is a variable which specifies descriptor type whether Linear or linked list type of descriptor. XZDMA_LINEAR - Linear type of descriptor.XZDMA_LINKEDLIST- Linked list type of descriptor. Dscr_MemPtr is a pointer to the allocated memory for creating descriptors. It Should be aligned to 64 bytes. NoOfBytes specifies the number of bytes allocated for descriptors The Count of the descriptors can be created. User should allocate the memory for descriptors which should be capable of how many transfers he wish to do in one start. For Linear mode each descriptor needs 128 bit memory so for one data transfer it requires 2*128 = 256 bits i.e. 32 bytes Similarly for Linked list mode for each descriptor it needs 256 bit, so for one data transfer it require 2*256 = 512 bits i.e. 64 bytes.
References XZDma::Config, XZDma::Descriptor, XZDma_Descriptor::DscrCount, XZDma_Descriptor::DscrType, XZDma_Descriptor::DstDscrPtr, XZDma_Config::IsCacheCoherent, XZDma_Descriptor::SrcDscrPtr, XZDMA_LINEAR, XZDMA_LINKEDLIST.
Referenced by XZDma_LinearExample, XZDma_LinkedListExample.
s32 XZDma_SetChDataConfig(XZDma *InstancePtr, XZDma_DataConfig *Configure)
This function sets the data attributes and control configurations of a ZDMA core based on the inputs provided.
InstancePtr is a pointer to the XZDma instance. Configure is a pointer to the XZDma_ChDataConfig structure which has all the configuration fields. The fields of the structure are: OverFetch - Allows over fetch or not 0 - Not allowed to over-fetch on SRC1 - Allowed to over-fetch on SRC SrcIssue - Outstanding transaction on SRC Range is 1 to 32 SrcBurstType - Burst Type for SRC AXI transaction XZDMA_FIXED_BURST - Fixed burstXZDMA_INCR_BURST - Incremental burst SrcBurstLen - AXI Length for Data Read. Range of values is (1,2,4,8,16). DstBurstType - Burst Type for SRC AXI transaction XZDMA_FIXED_BURST - Fixed burstXZDMA_INCR_BURST - Incremental burst DstBurstLen - AXI Length for Data write. Range of values is (1,2,4,8,16). SrcCache - AXI cache bits for Data readSrcQos - Configurable QoS bits for AXI Data readDstCache - AXI cache bits for Data writeDstQos - configurable QoS bits for AXI Data write XST_FAILURE If ZDMA Core is not in Idle state andXST_SUCCESS If Configurations are made successfully These configurations will last till we modify or Reset by XZDma_Reset(XZDma *InstancePtr).Configurations should be modified only when ZDMA channel is IDLE this can be confirmed by using XZDma_ChannelState(XZDma *InstancePtr) API.
References XZDma_Config::BaseAddress, XZDma::ChannelState, XZDma::Config, XZDma::DataConfig, XZDma_DataConfig::DstBurstLen, XZDma_DataConfig::DstBurstType, XZDma_DataConfig::DstCache, XZDma_DataConfig::DstQos, XZDma_DataConfig::OverFetch, XZDma_DataConfig::SrcBurstLen, XZDma_DataConfig::SrcBurstType, XZDma_DataConfig::SrcCache, XZDma_DataConfig::SrcIssue, XZDma_DataConfig::SrcQos, XZDMA_CTRL0_OVR_FETCH_MASK, XZDMA_CTRL0_OVR_FETCH_SHIFT, XZDMA_CTRL1_SRC_ISSUE_MASK, XZDMA_DATA_ATTR_ARBURST_MASK, XZDMA_DATA_ATTR_ARBURST_SHIFT, XZDMA_DATA_ATTR_ARCACHE_MASK, XZDMA_DATA_ATTR_ARCACHE_SHIFT, XZDMA_DATA_ATTR_ARLEN_MASK, XZDMA_DATA_ATTR_ARLEN_SHIFT, XZDMA_DATA_ATTR_ARQOS_MASK, XZDMA_DATA_ATTR_ARQOS_SHIFT, XZDMA_DATA_ATTR_AWBURST_MASK, XZDMA_DATA_ATTR_AWBURST_SHIFT, XZDMA_DATA_ATTR_AWCACHE_MASK, XZDMA_DATA_ATTR_AWCACHE_SHIFT, XZDMA_DATA_ATTR_AWLEN_MASK, XZDMA_DATA_ATTR_AWQOS_MASK, XZDMA_DATA_ATTR_AWQOS_SHIFT, XZDMA_IDLE, XZDma_ReadReg, XZDma_WriteReg.
Referenced by XZDma_LinearExample, XZDma_LinkedListExample, XZDma_SimpleExample, XZDma_SimpleReadOnlyExample, XZDma_WriteOnlyExample.
void XZDma_GetChDataConfig(XZDma *InstancePtr, XZDma_DataConfig *Configure)
This function gets the data attributes and control configurations of a ZDMA core.
InstancePtr is a pointer to the XZDma instance. Configure is a pointer to the XZDma_ChDataConfig structure which has all the configuration fields. The fields of the structure are: OverFetch - Allows over fetch or not 0 - Not allowed to over-fetch on SRC1 - Allowed to over-fetch on SRC SrcIssue - Outstanding transaction on SRC Range is 1 to 32 SrcBurstType - Burst Type for SRC AXI transaction XZDMA_FIXED_BURST - Fixed burstXZDMA_INCR_BURST - Incremental burst SrcBurstLen - AXI Length for Data Read. Can be max of 16 to be compatible with AXI3 DstBurstType - Burst Type for SRC AXI transaction XZDMA_FIXED_BURST - Fixed burstXZDMA_INCR_BURST - Incremental burst DstBurstLen - AXI Length for Data write. Can be max of 16 to be compatible with AXI3 SrcCache - AXI cache bits for Data readSrcQos - Configurable QoS bits for AXI Data readDstCache - AXI cache bits for Data writeDstQos - Configurable QoS bits for AXI Data write None None.
References XZDma::DataConfig, XZDma_DataConfig::DstBurstLen, XZDma_DataConfig::DstBurstType, XZDma_DataConfig::DstCache, XZDma_DataConfig::DstQos, XZDma_DataConfig::OverFetch, XZDma_DataConfig::SrcBurstLen, XZDma_DataConfig::SrcBurstType, XZDma_DataConfig::SrcCache, XZDma_DataConfig::SrcIssue, XZDma_DataConfig::SrcQos.
Referenced by XZDma_LinearExample, XZDma_LinkedListExample.
s32 XZDma_SetChDscrConfig(XZDma *InstancePtr, XZDma_DscrConfig *Configure)
This function sets the descriptor attributes based on the inputs provided in the structure.
InstancePtr is a pointer to the XZDma instance. Configure is a pointer to the XZDma_ChDscrConfig structure which has all the configuration fields. The fields of the structure are: AxCoherent - AXI transactions generated for the descriptor. 0 - Non coherent1 - Coherent AXCache - AXI cache bit used for DSCR fetch (both on SRC and DST Side)AXQos - QoS bit used for DSCR fetch (both on SRC and DST Side) XST_FAILURE If ZDMA core is not in Idle state and XST_SUCCESS If Configurations are made successfully None.
References XZDma_DscrConfig::AXCache, XZDma_DscrConfig::AxCoherent, XZDma_DscrConfig::AXQos, XZDma_Config::BaseAddress, XZDma::ChannelState, XZDma::Config, XZDma::DscrConfig, XZDMA_DSCR_ATTR_AXCACHE_MASK, XZDMA_DSCR_ATTR_AXCACHE_SHIFT, XZDMA_DSCR_ATTR_AXCOHRNT_MASK, XZDMA_DSCR_ATTR_AXCOHRNT_SHIFT, XZDMA_DSCR_ATTR_AXQOS_MASK, XZDMA_IDLE, XZDma_WriteReg.
void XZDma_GetChDscrConfig(XZDma *InstancePtr, XZDma_DscrConfig *Configure)
This function gets the descriptor attributes of the channel.
InstancePtr is a pointer to the XZDma instance. Configure is a pointer to the XZDma_ChDscrConfig structure which has all the configuration fields. The fields of the structure are: AxCoherent - AXI transactions generated for the descriptor. 0 - Non coherent1 - Coherent AXCache - AXI cache bit used for DSCR fetch (both on SRC and DST Side)AXQos - QoS bit used for DSCR fetch (both on SRC and DST Side) None. None.
References XZDma_DscrConfig::AXCache, XZDma_DscrConfig::AxCoherent, XZDma_DscrConfig::AXQos, XZDma::DscrConfig.
void XZDma_WOData(XZDma *InstancePtr, u32 *Buffer)
This function preloads the buffers which will be used in write only mode.
In write only mode the data in the provided buffer will be written in destination address for specified size. InstancePtr is a pointer to the XZDma instance. Buffer is a pointer to an array of 64/128 bit data. i.e. pointer to 32 bit array of size 2/4 Array of Size 2 for ADMAArray of Size 4 for GDMA None. Valid only in simple mode. Prior to call this function ZDMA instance should be set in Write only mode by using XZDma_SetMode(XZDma *InstancePtr, u8 IsSgDma, XZDma_Mode Mode) To initiate data transfer after this API need to call XZDma_Start(XZDma *InstancePtr, XZDma_Transfer *Data, u32 Num) In which only destination fields has to be filled.
References XZDma_Config::BaseAddress, XZDma::Config, XZDma_Config::DmaType, XZDma_WriteReg.
Referenced by XZDma_WriteOnlyExample.
void XZDma_Resume(XZDma *InstancePtr)
This function resume the paused state of ZDMA core and starts the transfer from where it has paused.
InstancePtr is a pointer to the XZDma instance. None. Valid only for scatter gather mode.
References XZDma_Config::BaseAddress, XZDma::ChannelState, XZDma::Config, XZDma::IsSgDma, XZDMA_BUSY, XZDMA_CTRL0_CONT_ADDR_MASK, XZDMA_CTRL0_CONT_MASK, XZDMA_PAUSE, XZDma_ReadReg, XZDma_WriteReg.
Referenced by XZDma_LinearExample.
void XZDma_Reset(XZDma *InstancePtr)
This function resets the ZDMA core.
InstancePtr is a pointer to the XZDma instance. None. This function resets all the configurations made previously. Disables all the interrupts and clears interrupt status.
References XZDma_Config::BaseAddress, XZDma::ChannelState, XZDma::Config, XZDma::IntrMask, XZDma_Config::IsCacheCoherent, XZDMA_CTRL0_RESET_VALUE, XZDMA_CTRL1_RESET_VALUE, XZDMA_DATA_ATTR_RESET_VALUE, XZDma_DisableCh, XZDma_DisableIntr, XZDMA_DSCR_ATTR_AXCOHRNT_SHIFT, XZDMA_DSCR_ATTR_RESET_VALUE, XZDma_GetDstIntrCnt, XZDma_GetSrcIntrCnt, XZDMA_IDLE, XZDma_IntrClear, XZDMA_IXR_ALL_INTR_MASK, XZDma_TotalByteClear, XZDMA_WORD3_COHRNT_MASK, XZDma_WriteReg.
Referenced by XZDma_CfgInitialize, XZDma_LinearExample, XZDma_LinkedListExample, XZDma_SimpleExample, XZDma_WriteOnlyExample.
XZDmaState XZDma_ChannelState(XZDma *InstancePtr)
This function returns the state of ZDMA core.
InstancePtr is a pointer to the XZDma instance. This function returns state of ZDMA core XZDMA_IDLE - If ZDMA core is in idle state.XZDMA_PAUSE - If ZDMA is in paused state.XZDMA_BUSY - If ZDMA is in busy state. None. C-style signature: XZDmaState XZDma_ChannelState(XZDma *InstancePtr)
References XZDma_Config::BaseAddress, XZDma::Config, XZDMA_BUSY, XZDMA_IDLE, XZDMA_PAUSE, XZDma_ReadReg, XZDMA_STS_ALL_MASK, XZDMA_STS_DONE_ERR_MASK, XZDMA_STS_DONE_MASK, XZDMA_STS_PAUSE_MASK.
s32 XZDma_Start(XZDma *InstancePtr, XZDma_Transfer *Data, u32 Num)
This function sets all the required fields for initiating data transfer.
Data transfer elements needs to be passed through structure pointer. Data transfer can be done in any of the three modes (simple, Linear or Linked List) based on the selected mode but before calling this API make sure that ZDMA is in Idle state. InstancePtr is a pointer to the XZDma instance. Data is a pointer of array to the XZDma_Transfer structure which has all the configuration fields for initiating data transfer. The fields of the structure are: SrcAddr - Source addressDstAddr - Destination addressSize - size of the data to be transferred in bytesSrcCoherent - AXI transactions generated to process the descriptor payload for source channel 0 - Non coherent1 - Coherent DstCoherent - AXI transactions generated to process the descriptor payload for destination channel 0 - Non coherent1 - Coherent Pause - Valid only for scatter gather mode. Will pause after completion of this descriptor. Num specifies number of array elements of Data pointer. For simple mode Num should be equal to 1For Scatter gather mode (either linear or linked list) Num can be any choice. (But based on which memory should be allocated by Application) It should be less than the return value of XZDma_CreateBDList. XST_SUCCESS - if ZDMA initiated the transfer.XST_FAILURE - if ZDMA has not initiated data transfer. After Pause to resume the transfer need to use the following API XZDma_Resume User should provide allocated memory and descriptor type in scatter gather mode through the following API before calling the start API.XZDma_SetDescriptorType(XZDma *InstancePtr, XZDma_DscrType TypeOfDscr, UINTPTR Dscr_MemPtr, u32 NoOfBytes)
References XZDma::ChannelState, XZDma::Descriptor, XZDma_Descriptor::DscrCount, XZDma::IsSgDma, XZDMA_BUSY, XZDma_Enable, XZDma_ScatterGather.
Referenced by XZDma_LinearExample, XZDma_LinkedListExample, XZDma_SimpleExample, XZDma_SimpleReadOnlyExample, XZDma_WriteOnlyExample.
void XZDma_ScatterGather(XZDma *InstancePtr, XZDma_Transfer *Data, u32 Num)
This function sets all the required fields for initiating data transfer in scatter gather mode.
InstancePtr is a pointer to the XZDma instance. Data is a pointer of array to the XZDma_Transfer structure which has all the configuration fields for initiating data transfer. Num specifies number of array elements of Data pointer. None. None.
References XZDma_Config::BaseAddress, XZDma::Config, XZDma::Descriptor, XZDma_Descriptor::DscrType, XZDma_Descriptor::DstDscrPtr, XZDma_Descriptor::SrcDscrPtr, XZDMA_LINEAR, XZDMA_WORD0_LSB_MASK, XZDMA_WORD1_MSB_MASK, XZDMA_WORD1_MSB_SHIFT, XZDma_WriteReg.
Referenced by XZDma_Start.
void XZDma_Enable(XZDma *InstancePtr)
This function enables all the interrupts which user intended to enable and enables the ZDMA channel for initiating data transfer.
InstancePtr is a pointer to the XZDma instance. None. None.
References XZDma_Config::BaseAddress, XZDma::ChannelState, XZDma::Config, XZDma::IntrMask, XZDMA_BUSY, XZDma_EnableCh, XZDMA_IXR_ALL_INTR_MASK, XZDma_WriteReg.
Referenced by XZDma_Start.
s32 XZDma_Stop(XZDma *InstancePtr)
Stops the ZDMA engine and releases power management resources if supported.
This function asserts the validity of the input instance pointer. If power management (XPM_SUPPORT) is enabled, it releases the power management node associated with the ZDMA instance. If the release fails, an error message is printed. The function returns the status of the operation. InstancePtr is a pointer to the XZDma instance. Status code: XST_SUCCESS if successful.Error code if PM resource release fails (when XPM_SUPPORT is defined). None.
References XZDma_Config::BaseAddress, XZDma::Config.
Referenced by XZDma_WriteOnlyExample.
void XZDma_IntrHandler(void *Instance)
This function is the interrupt handler for the ZDMA core.
This handler reads the pending interrupt from Status register, determines the source of the interrupts and calls the respective callbacks for the interrupts that are enabled in IRQ_ENABLE register, and finally clears the interrupts.The application is responsible for connecting this function to the interrupt system. Application beyond this driver is also responsible for providing callbacks to handle interrupts and installing the callbacks using XZDma_SetCallBack() during initialization phase. . Instance is a pointer to the XZDma instance to be worked on. None. To generate interrupt required interrupts should be enabled.
References XZDma::ChannelState, XZDma::DoneHandler, XZDma::DoneRef, XZDma::ErrorHandler, XZDma::ErrorRef, XZDma_DisableIntr, XZDma_GetIntrMask, XZDMA_IDLE, XZDma_IntrClear, XZDma_IntrGetStatus, XZDMA_IXR_ALL_INTR_MASK, XZDMA_IXR_AXI_RD_DATA_MASK, XZDMA_IXR_AXI_RD_DST_DSCR_MASK, XZDMA_IXR_AXI_RD_SRC_DSCR_MASK, XZDMA_IXR_AXI_WR_DATA_MASK, XZDMA_IXR_DMA_DONE_MASK, XZDMA_IXR_DMA_PAUSE_MASK, XZDMA_IXR_ERR_MASK, XZDMA_PAUSE.
Referenced by XZDma_LinearExample, XZDma_LinkedListExample, XZDma_SimpleExample, XZDma_SimpleReadOnlyExample, XZDma_WriteOnlyExample.
s32 XZDma_SetCallBack(XZDma *InstancePtr, XZDma_Handler HandlerType, void *CallBackFunc, void *CallBackRef)
This routine installs an asynchronous callback function for the given HandlerType.
HandlerType Callback Function Type ----------------------- -------------------------------------------------- XZDMA_HANDLER_DONE Done handler XZDMA_HANDLER_ERROR Error handler InstancePtr is a pointer to the XZDma instance to be worked on. HandlerType specifies which callback is to be attached. CallBackFunc is the address of the callback function. CallBackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS when handler is installed.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XZDma::DoneHandler, XZDma::DoneRef, XZDma::ErrorHandler, XZDma::ErrorRef, XZDma::IsReady, XZDMA_HANDLER_DONE, XZDMA_HANDLER_ERROR.
Referenced by XZDma_LinearExample, XZDma_LinkedListExample, XZDma_SimpleExample, XZDma_SimpleReadOnlyExample, XZDma_WriteOnlyExample.
s32 XZDma_SelfTest(XZDma *InstancePtr)
This file contains a diagnostic self-test function for the ZDMA driver.
Refer to the header file xzdma.h for more detailed information. InstancePtr is a pointer to XZDma instance. XST_SUCCESS if the test is successful.XST_FAILURE if the test is failed. None.
References XZDma_Config::BaseAddress, XZDma::Config, XZDMA_CTRL0_OVR_FETCH_MASK, XZDma_ReadReg, XZDma_WriteReg.
Referenced by XZDma_LinearExample, XZDma_LinkedListExample, XZDma_SelfTestExample, XZDma_SimpleExample, XZDma_SimpleReadOnlyExample, XZDma_WriteOnlyExample.
XZDma_Config* XZDma_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
A table contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration table entry corresponding to the given device ID/BaseAddress, or NULL if no match is found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XZDma_Config::Name.
Referenced by XZDma_LinearExample, XZDma_LinkedListExample, XZDma_SelfTestExample, XZDma_SimpleExample, XZDma_SimpleReadOnlyExample, XZDma_WriteOnlyExample.
XZDMA_HW_H_
Prevent circular inclusions by using protection macros.
XZDma_In32
Input operation.
XZDma_Out32
Output operation.
XZDma_ReadReg
This macro reads the given register.
BaseAddress is the Xilinx base address of the ZDMA core. RegOffset is the register offset of the register. The 32-bit value of the register. C-style signature: u32 XZDma_ReadReg(u32 BaseAddress, u32 RegOffset)
Referenced by XZDma_ChannelState, XZDma_Resume, XZDma_SelfTest, XZDma_SetChDataConfig, XZDma_SetMode.
XZDma_WriteReg
This macro writes the value into the given register.
BaseAddress is the Xilinx base address of the ZDMA core. RegOffset is the register offset of the register. Data is the 32-bit value to write to the register. None. C-style signature: void XZDma_WriteReg(u32 BaseAddress, u32 RegOffset, u32 Data)
Referenced by XZDma_Enable, XZDma_Reset, XZDma_Resume, XZDma_ScatterGather, XZDma_SelfTest, XZDma_SetChDataConfig, XZDma_SetChDscrConfig, XZDma_SetMode, XZDma_WOData.