xzdma_sinit.c
XZDma_Config* XZDma_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
A table contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration table entry corresponding to the given device ID/BaseAddress, or NULL if no match is found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XZDma_Config::Name.
Referenced by XZDma_LinearExample, XZDma_LinkedListExample, XZDma_SelfTestExample, XZDma_SimpleExample, XZDma_SimpleReadOnlyExample, XZDma_WriteOnlyExample.