xzdma_intr.c
void XZDma_IntrHandler(void *Instance)
This function is the interrupt handler for the ZDMA core.
This handler reads the pending interrupt from Status register, determines the source of the interrupts and calls the respective callbacks for the interrupts that are enabled in IRQ_ENABLE register, and finally clears the interrupts.The application is responsible for connecting this function to the interrupt system. Application beyond this driver is also responsible for providing callbacks to handle interrupts and installing the callbacks using XZDma_SetCallBack() during initialization phase. . Instance is a pointer to the XZDma instance to be worked on. None. To generate interrupt required interrupts should be enabled.
References XZDma::ChannelState, XZDma::DoneHandler, XZDma::DoneRef, XZDma::ErrorHandler, XZDma::ErrorRef, XZDma_DisableIntr, XZDma_GetIntrMask, XZDMA_IDLE, XZDma_IntrClear, XZDma_IntrGetStatus, XZDMA_IXR_ALL_INTR_MASK, XZDMA_IXR_AXI_RD_DATA_MASK, XZDMA_IXR_AXI_RD_DST_DSCR_MASK, XZDMA_IXR_AXI_RD_SRC_DSCR_MASK, XZDMA_IXR_AXI_WR_DATA_MASK, XZDMA_IXR_DMA_DONE_MASK, XZDMA_IXR_DMA_PAUSE_MASK, XZDMA_IXR_ERR_MASK, XZDMA_PAUSE.
Referenced by XZDma_LinearExample, XZDma_LinkedListExample, XZDma_SimpleExample, XZDma_SimpleReadOnlyExample, XZDma_WriteOnlyExample.
s32 XZDma_SetCallBack(XZDma *InstancePtr, XZDma_Handler HandlerType, void *CallBackFunc, void *CallBackRef)
This routine installs an asynchronous callback function for the given HandlerType.
HandlerType Callback Function Type ----------------------- -------------------------------------------------- XZDMA_HANDLER_DONE Done handler XZDMA_HANDLER_ERROR Error handler InstancePtr is a pointer to the XZDma instance to be worked on. HandlerType specifies which callback is to be attached. CallBackFunc is the address of the callback function. CallBackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS when handler is installed.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XZDma::DoneHandler, XZDma::DoneRef, XZDma::ErrorHandler, XZDma::ErrorRef, XZDma::IsReady, XZDMA_HANDLER_DONE, XZDMA_HANDLER_ERROR.
Referenced by XZDma_LinearExample, XZDma_LinkedListExample, XZDma_SimpleExample, XZDma_SimpleReadOnlyExample, XZDma_WriteOnlyExample.