xzdma_selftest.c
s32 XZDma_SelfTest(XZDma *InstancePtr)
This file contains a diagnostic self-test function for the ZDMA driver.
Refer to the header file xzdma.h for more detailed information. InstancePtr is a pointer to XZDma instance. XST_SUCCESS if the test is successful.XST_FAILURE if the test is failed. None.
References XZDma_Config::BaseAddress, XZDma::Config, XZDMA_CTRL0_OVR_FETCH_MASK, XZDma_ReadReg, XZDma_WriteReg.
Referenced by XZDma_LinearExample, XZDma_LinkedListExample, XZDma_SelfTestExample, XZDma_SimpleExample, XZDma_SimpleReadOnlyExample, XZDma_WriteOnlyExample.