xzdma.h
XZDma_IntrGetStatus
This function returns interrupt status read from Interrupt Status Register.
Use the XZDMA_IXR_DMA_*_MASK constants defined in xzdma_hw.h to interpret the returned value. InstancePtr is a pointer to the XZDma instance. The pending interrupts of the ZDMA core. Use the masks specified in xzdma_hw.h to interpret the returned value. C-style signature: void XZDma_IntrGetStatus(XZDma *InstancePtr)
Referenced by XZDma_IntrHandler.
XZDma_IntrClear
This function clears interrupt(s).
Every bit set in Interrupt Status Register indicates that a specific type of interrupt is occurring, and this function clears one or more interrupts by writing a bit mask to Interrupt Clear Register. InstancePtr is a pointer to the XZDma instance. Mask is the type of the interrupts to enable. Use OR'ing of XZDMA_IXR_DMA_*_MASK constants defined in xzdma_hw.h to create this parameter value. None. C-style signature: void XZDma_IntrClear(XZDma *InstancePtr)
Referenced by XZDma_IntrHandler, XZDma_Reset.
XZDma_GetIntrMask
This function returns interrupt mask to know which interrupts are enabled and which of them were disabled.
InstancePtr is a pointer to the XZDma instance. The current interrupt mask. The mask indicates which interrupts are enabled/disabled. 0 bit represents .....corresponding interrupt is enabled. 1 bit represents .....Corresponding interrupt is disabled. C-style signature: void XZDma_GetIntrMask(XZDma *InstancePtr)
Referenced by XZDma_IntrHandler.
XZDma_EnableIntr
This function enables individual interrupts of the ZDMA core by updating the Interrupt Enable register.
InstancePtr is a pointer to the XZDma instance. Mask is the type of the interrupts to enable. Use OR'ing of XZDMA_IXR_DMA_*_MASK constants defined in xzdma_hw.h to create this parameter value. None. The existing enabled interrupt(s) will remain enabled. C-style signature: void XZDma_EnableIntr(XZDma *InstancePtr, u32 Mask)
Referenced by XZDma_LinearExample, XZDma_LinkedListExample, XZDma_SimpleExample, XZDma_SimpleReadOnlyExample, XZDma_WriteOnlyExample.
XZDma_DisableIntr
This function disables individual interrupts of the ZDMA core by updating the Interrupt Disable register.
InstancePtr is a pointer to the XZDma instance. Mask is the type of the interrupts to disable. Use OR'ing of XZDMA_IXR_DMA_*_MASK constants defined in xzdma_hw.h to create this parameter value. None. The existing disabled interrupt(s) will remain disabled. C-style signature: void XZDma_DisableIntr(XZDma *InstancePtr, u32 Mask)
Referenced by XZDma_IntrHandler, XZDma_LinearExample, XZDma_LinkedListExample, XZDma_Reset, XZDma_SimpleExample, XZDma_WriteOnlyExample.
XZDma_SrcCurPyld
This function returns source current payload address under process of ZDMA core.
InstancePtr is a pointer to the XZDma instance. None. This address may not be precise due to ZDMA pipeline structure C-style signature: u64 XZDma_SrcCurPyld(XZDma *InstancePtr)
XZDma_DstCurPyld
This function returns destination current payload address under process of ZDMA core.
InstancePtr is a pointer to the XZDma instance. None. This address may not be precise due to ZDMA pipeline structure C-style signature: u64 XZDma_DstCurPyld(XZDma *InstancePtr)
XZDma_SrcDscrCurPyld
This function returns source descriptor current payload address under process of ZDMA core.
InstancePtr is a pointer to the XZDma instance. None. This address may not be precise due to ZDMA pipeline structure C-style signature: u64 XZDma_SrcDscrCurPyld(XZDma *InstancePtr)
XZDma_DstDscrCurPyld
This function returns destination descriptor current payload address under process of ZDMA core.
InstancePtr is a pointer to the XZDma instance. None. This address may not be precise due to ZDMA pipeline structure C-style signature: u64 XZDma_DstDscrCurPyld(XZDma *InstancePtr)
XZDma_GetTotalByte
This function gets the count of total bytes transferred through core since last clear in ZDMA core.
InstancePtr is a pointer to the XZDma instance. None. C-style signature: void XZDma_GetTotalByte(XZDma *InstancePtr)
XZDma_TotalByteClear
This function clears the count of total bytes transferred in ZDMA core.
InstancePtr is a pointer to the XZDma instance. None. C-style signature: void XZDma_TotalByteClear(XZDma *InstancePtr)
Referenced by XZDma_Reset.
XZDma_GetSrcIntrCnt
This function gets the total number of Interrupt count for source after last call of this API.
InstancePtr is a pointer to the XZDma instance. None. Once this API is called then count will become zero. C-style signature: void XZDma_GetSrcIntrCnt(XZDma *InstancePtr)
Referenced by XZDma_Reset.
XZDma_GetDstIntrCnt
This function gets the total number of Interrupt count for destination after last call of this API.
InstancePtr is a pointer to the XZDma instance. None. Once this API is called then count will become zero. C-style signature: void XZDma_GetDstIntrCnt(XZDma *InstancePtr)
Referenced by XZDma_Reset.
XZDma_EnableCh
This function Enable's the ZDMA core for initiating the data transfer once the data transfer completes it will be automatically disabled.
InstancePtr is a pointer to the XZDma instance. None. None. C-style signature: void XZDma_EnableCh(XZDma *InstancePtr)
Referenced by XZDma_Enable.
XZDma_DisableCh
This function Disable's the ZDMA core.
InstancePtr is a pointer to the XZDma instance. None. None. C-style signature: void XZDma_DisableCh(XZDma *InstancePtr)
Referenced by XZDma_Reset.
XZDma_Handler
For Done Handler.
XZDma_DscrType
Linear descriptor.
XZDma_Mode
Normal transfer from source to destination.
XZDmaState
ZDMA is in Idle state.
XZDma_BurstType
Fixed burst type.
typedef void(* XZDma_DoneHandler)(void *CallBackRef))(void *CallBackRef)
Callback type for Completion of all data transfers.
CallBackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked.
typedef void(* XZDma_ErrorHandler)(void *CallBackRef, u32 ErrorMask))(void *CallBackRef, u32 ErrorMask)
Callback type for all error interrupts.
CallBackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. ErrorMask is a bit mask indicating the cause of the error. Its value equals 'OR'ing one or more XZDMA_IXR_* values defined in xzdma_hw.h
XZDma_Config* XZDma_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
A table contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration table entry corresponding to the given device ID/BaseAddress, or NULL if no match is found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XZDma_Config::Name.
Referenced by XZDma_LinearExample, XZDma_LinkedListExample, XZDma_SimpleReadOnlyExample, XZDma_SelfTestExample, XZDma_SimpleExample, XZDma_WriteOnlyExample.
s32 XZDma_CfgInitialize(XZDma *InstancePtr, XZDma_Config *CfgPtr, u32 EffectiveAddr)
This function initializes an ZDMA core.
This function must be called prior to using an ZDMA core. Initialization of an ZDMA includes setting up the instance data and ensuring the hardware is in a quiescent state and resets all the hardware configurations. InstancePtr is a pointer to the XZDma instance. CfgPtr is a reference to a structure containing information about a specific XZDma instance. EffectiveAddr is the device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, pass in the physical address instead. XST_SUCCESS if initialization was successful. None.
References XZDma::Config, XZDma_Config::BaseAddress, XZDma_Config::DmaType, XZDma_Config::IsCacheCoherent, XZDma::IsReady, XZDma::IsSgDma, XZDma::Mode, XZDMA_NORMAL_MODE, XZDma::IntrMask, XZDma::ChannelState, XZDMA_IDLE, XZDma::irq_offset, XZDma_Config::Name, XZDma::DoneHandler, XZDma::ErrorHandler, XZDma_Reset.
Referenced by XZDma_LinearExample, XZDma_LinkedListExample, XZDma_SimpleReadOnlyExample, XZDma_SelfTestExample, XZDma_SimpleExample, XZDma_WriteOnlyExample.
s32 XZDma_SetMode(XZDma *InstancePtr, u8 IsSgDma, XZDma_Mode Mode)
This function sets the pointer type and mode in which ZDMA needs to transfer the data.
InstancePtr is a pointer to the XZDma instance. IsSgDma is a variable which specifies whether transfer has to to be done in scatter gather mode or simple mode. TRUE - Scatter gather pointer typeFALSE - Simple pointer type Mode is the type of the mode in which data has to be initiated XZDMA_NORMAL_MODE - Normal data transfer from source to destination (Valid for both Scatter gather and simple types)XZDMA_WRONLY_MODE - Write only mode (Valid only for Simple)XZDMA_RDONLY_MODE - Read only mode (Valid only for Simple) XST_SUCCESS - If mode has been set successfully.XST_FAILURE - If mode has not been set. Mode cannot be changed while ZDMA is not in IDLE state.
References XZDMA_RDONLY_MODE, XZDma::ChannelState, XZDMA_IDLE, XZDma_ReadReg, XZDma::Config, XZDma_Config::BaseAddress, XZDMA_CTRL0_POINT_TYPE_MASK, XZDMA_NORMAL_MODE, XZDMA_CTRL0_MODE_MASK, XZDMA_WRONLY_MODE, XZDMA_CTRL0_WRONLY_MASK, XZDMA_CTRL0_RDONLY_MASK, XZDma_WriteReg, XZDma::IsSgDma, XZDma::Mode.
Referenced by XZDma_LinearExample, XZDma_LinkedListExample, XZDma_SimpleReadOnlyExample, XZDma_SimpleExample, XZDma_WriteOnlyExample.
u32 XZDma_CreateBDList(XZDma *InstancePtr, XZDma_DscrType TypeOfDscr, UINTPTR Dscr_MemPtr, u32 NoOfBytes)
This function sets the descriptor type and descriptor pointer's start address of both source and destination based on the memory allocated by user and also calculates no of descriptors(BDs) can be created in the allocated memory.
InstancePtr is a pointer to the XZDma instance. TypeOfDscr is a variable which specifies descriptor type whether Linear or linked list type of descriptor. XZDMA_LINEAR - Linear type of descriptor.XZDMA_LINKEDLIST- Linked list type of descriptor. Dscr_MemPtr is a pointer to the allocated memory for creating descriptors. It Should be aligned to 64 bytes. NoOfBytes specifies the number of bytes allocated for descriptors The Count of the descriptors can be created. User should allocate the memory for descriptors which should be capable of how many transfers he wish to do in one start. For Linear mode each descriptor needs 128 bit memory so for one data transfer it requires 2*128 = 256 bits i.e. 32 bytes Similarly for Linked list mode for each descriptor it needs 256 bit, so for one data transfer it require 2*256 = 512 bits i.e. 64 bytes.
References XZDMA_LINEAR, XZDMA_LINKEDLIST, XZDma::Descriptor, XZDma_Descriptor::DscrType, XZDma_Descriptor::DscrCount, XZDma_Descriptor::SrcDscrPtr, XZDma_Descriptor::DstDscrPtr, XZDma::Config, XZDma_Config::IsCacheCoherent.
Referenced by XZDma_LinearExample, XZDma_LinkedListExample.
s32 XZDma_SetChDataConfig(XZDma *InstancePtr, XZDma_DataConfig *Configure)
This function sets the data attributes and control configurations of a ZDMA core based on the inputs provided.
InstancePtr is a pointer to the XZDma instance. Configure is a pointer to the XZDma_ChDataConfig structure which has all the configuration fields. The fields of the structure are: OverFetch - Allows over fetch or not 0 - Not allowed to over-fetch on SRC1 - Allowed to over-fetch on SRC SrcIssue - Outstanding transaction on SRC Range is 1 to 32 SrcBurstType - Burst Type for SRC AXI transaction XZDMA_FIXED_BURST - Fixed burstXZDMA_INCR_BURST - Incremental burst SrcBurstLen - AXI Length for Data Read. Range of values is (1,2,4,8,16). DstBurstType - Burst Type for SRC AXI transaction XZDMA_FIXED_BURST - Fixed burstXZDMA_INCR_BURST - Incremental burst DstBurstLen - AXI Length for Data write. Range of values is (1,2,4,8,16). SrcCache - AXI cache bits for Data readSrcQos - Configurable QoS bits for AXI Data readDstCache - AXI cache bits for Data writeDstQos - configurable QoS bits for AXI Data write XST_FAILURE If ZDMA Core is not in Idle state andXST_SUCCESS If Configurations are made successfully These configurations will last till we modify or Reset by XZDma_Reset(XZDma *InstancePtr).Configurations should be modified only when ZDMA channel is IDLE this can be confirmed by using XZDma_ChannelState(XZDma *InstancePtr) API.
References XZDma::ChannelState, XZDMA_IDLE, XZDma::DataConfig, XZDma_DataConfig::DstBurstType, XZDma_DataConfig::DstBurstLen, XZDma_DataConfig::SrcBurstType, XZDma_DataConfig::SrcBurstLen, XZDma_DataConfig::OverFetch, XZDma_DataConfig::SrcIssue, XZDma_DataConfig::SrcCache, XZDma_DataConfig::SrcQos, XZDma_DataConfig::DstCache, XZDma_DataConfig::DstQos, XZDma_ReadReg, XZDma::Config, XZDma_Config::BaseAddress, XZDMA_CTRL0_OVR_FETCH_MASK, XZDMA_CTRL0_OVR_FETCH_SHIFT, XZDma_WriteReg, XZDMA_CTRL1_SRC_ISSUE_MASK, XZDMA_DATA_ATTR_ARBURST_MASK, XZDMA_DATA_ATTR_ARLEN_MASK, XZDMA_DATA_ATTR_AWBURST_MASK, XZDMA_DATA_ATTR_AWLEN_MASK, XZDMA_DATA_ATTR_ARCACHE_MASK, XZDMA_DATA_ATTR_AWCACHE_MASK, XZDMA_DATA_ATTR_AWQOS_MASK, XZDMA_DATA_ATTR_ARQOS_MASK, XZDMA_DATA_ATTR_ARBURST_SHIFT, XZDMA_DATA_ATTR_ARCACHE_SHIFT, XZDMA_DATA_ATTR_ARQOS_SHIFT, XZDMA_DATA_ATTR_ARLEN_SHIFT, XZDMA_DATA_ATTR_AWBURST_SHIFT, XZDMA_DATA_ATTR_AWCACHE_SHIFT, XZDMA_DATA_ATTR_AWQOS_SHIFT.
Referenced by XZDma_LinearExample, XZDma_LinkedListExample, XZDma_SimpleReadOnlyExample, XZDma_SimpleExample, XZDma_WriteOnlyExample.
void XZDma_GetChDataConfig(XZDma *InstancePtr, XZDma_DataConfig *Configure)
This function gets the data attributes and control configurations of a ZDMA core.
InstancePtr is a pointer to the XZDma instance. Configure is a pointer to the XZDma_ChDataConfig structure which has all the configuration fields. The fields of the structure are: OverFetch - Allows over fetch or not 0 - Not allowed to over-fetch on SRC1 - Allowed to over-fetch on SRC SrcIssue - Outstanding transaction on SRC Range is 1 to 32 SrcBurstType - Burst Type for SRC AXI transaction XZDMA_FIXED_BURST - Fixed burstXZDMA_INCR_BURST - Incremental burst SrcBurstLen - AXI Length for Data Read. Can be max of 16 to be compatible with AXI3 DstBurstType - Burst Type for SRC AXI transaction XZDMA_FIXED_BURST - Fixed burstXZDMA_INCR_BURST - Incremental burst DstBurstLen - AXI Length for Data write. Can be max of 16 to be compatible with AXI3 SrcCache - AXI cache bits for Data readSrcQos - Configurable QoS bits for AXI Data readDstCache - AXI cache bits for Data writeDstQos - Configurable QoS bits for AXI Data write None None.
References XZDma_DataConfig::SrcBurstType, XZDma::DataConfig, XZDma_DataConfig::SrcCache, XZDma_DataConfig::SrcQos, XZDma_DataConfig::SrcBurstLen, XZDma_DataConfig::DstBurstType, XZDma_DataConfig::DstCache, XZDma_DataConfig::DstQos, XZDma_DataConfig::DstBurstLen, XZDma_DataConfig::OverFetch, XZDma_DataConfig::SrcIssue.
Referenced by XZDma_LinearExample, XZDma_LinkedListExample.
s32 XZDma_SetChDscrConfig(XZDma *InstancePtr, XZDma_DscrConfig *Configure)
This function sets the descriptor attributes based on the inputs provided in the structure.
InstancePtr is a pointer to the XZDma instance. Configure is a pointer to the XZDma_ChDscrConfig structure which has all the configuration fields. The fields of the structure are: AxCoherent - AXI transactions generated for the descriptor. 0 - Non coherent1 - Coherent AXCache - AXI cache bit used for DSCR fetch (both on SRC and DST Side)AXQos - QoS bit used for DSCR fetch (both on SRC and DST Side) XST_FAILURE If ZDMA core is not in Idle state and XST_SUCCESS If Configurations are made successfully None.
References XZDma::ChannelState, XZDMA_IDLE, XZDma::DscrConfig, XZDma_DscrConfig::AXCache, XZDma_DscrConfig::AXQos, XZDma_DscrConfig::AxCoherent, XZDMA_DSCR_ATTR_AXCOHRNT_SHIFT, XZDMA_DSCR_ATTR_AXCOHRNT_MASK, XZDMA_DSCR_ATTR_AXCACHE_SHIFT, XZDMA_DSCR_ATTR_AXCACHE_MASK, XZDMA_DSCR_ATTR_AXQOS_MASK, XZDma_WriteReg, XZDma::Config, XZDma_Config::BaseAddress.
void XZDma_GetChDscrConfig(XZDma *InstancePtr, XZDma_DscrConfig *Configure)
This function gets the descriptor attributes of the channel.
InstancePtr is a pointer to the XZDma instance. Configure is a pointer to the XZDma_ChDscrConfig structure which has all the configuration fields. The fields of the structure are: AxCoherent - AXI transactions generated for the descriptor. 0 - Non coherent1 - Coherent AXCache - AXI cache bit used for DSCR fetch (both on SRC and DST Side)AXQos - QoS bit used for DSCR fetch (both on SRC and DST Side) None. None.
References XZDma_DscrConfig::AXCache, XZDma::DscrConfig, XZDma_DscrConfig::AXQos, XZDma_DscrConfig::AxCoherent.
s32 XZDma_Start(XZDma *InstancePtr, XZDma_Transfer *Data, u32 Num)
This function sets all the required fields for initiating data transfer.
Data transfer elements needs to be passed through structure pointer. Data transfer can be done in any of the three modes (simple, Linear or Linked List) based on the selected mode but before calling this API make sure that ZDMA is in Idle state. InstancePtr is a pointer to the XZDma instance. Data is a pointer of array to the XZDma_Transfer structure which has all the configuration fields for initiating data transfer. The fields of the structure are: SrcAddr - Source addressDstAddr - Destination addressSize - size of the data to be transferred in bytesSrcCoherent - AXI transactions generated to process the descriptor payload for source channel 0 - Non coherent1 - Coherent DstCoherent - AXI transactions generated to process the descriptor payload for destination channel 0 - Non coherent1 - Coherent Pause - Valid only for scatter gather mode. Will pause after completion of this descriptor. Num specifies number of array elements of Data pointer. For simple mode Num should be equal to 1For Scatter gather mode (either linear or linked list) Num can be any choice. (But based on which memory should be allocated by Application) It should be less than the return value of XZDma_CreateBDList. XST_SUCCESS - if ZDMA initiated the transfer.XST_FAILURE - if ZDMA has not initiated data transfer. After Pause to resume the transfer need to use the following API XZDma_Resume User should provide allocated memory and descriptor type in scatter gather mode through the following API before calling the start API.XZDma_SetDescriptorType(XZDma *InstancePtr, XZDma_DscrType TypeOfDscr, UINTPTR Dscr_MemPtr, u32 NoOfBytes)
References XZDma::ChannelState, XZDMA_BUSY, XZDma::Descriptor, XZDma_Descriptor::DscrCount, XZDma::IsSgDma, XZDma_ScatterGather, XZDma_Enable.
Referenced by XZDma_LinearExample, XZDma_LinkedListExample, XZDma_SimpleReadOnlyExample, XZDma_SimpleExample, XZDma_WriteOnlyExample.
void XZDma_WOData(XZDma *InstancePtr, u32 *Buffer)
This function preloads the buffers which will be used in write only mode.
In write only mode the data in the provided buffer will be written in destination address for specified size. InstancePtr is a pointer to the XZDma instance. Buffer is a pointer to an array of 64/128 bit data. i.e. pointer to 32 bit array of size 2/4 Array of Size 2 for ADMAArray of Size 4 for GDMA None. Valid only in simple mode. Prior to call this function ZDMA instance should be set in Write only mode by using XZDma_SetMode(XZDma *InstancePtr, u8 IsSgDma, XZDma_Mode Mode) To initiate data transfer after this API need to call XZDma_Start(XZDma *InstancePtr, XZDma_Transfer *Data, u32 Num) In which only destination fields has to be filled.
References XZDma::Config, XZDma_Config::DmaType, XZDma_WriteReg, XZDma_Config::BaseAddress.
Referenced by XZDma_WriteOnlyExample.
void XZDma_Resume(XZDma *InstancePtr)
This function resume the paused state of ZDMA core and starts the transfer from where it has paused.
InstancePtr is a pointer to the XZDma instance. None. Valid only for scatter gather mode.
References XZDma::IsSgDma, XZDma::ChannelState, XZDMA_PAUSE, XZDma_ReadReg, XZDma::Config, XZDma_Config::BaseAddress, XZDMA_CTRL0_CONT_ADDR_MASK, XZDMA_CTRL0_CONT_MASK, XZDMA_BUSY, XZDma_WriteReg.
Referenced by XZDma_LinearExample.
void XZDma_Reset(XZDma *InstancePtr)
This function resets the ZDMA core.
InstancePtr is a pointer to the XZDma instance. None. This function resets all the configurations made previously. Disables all the interrupts and clears interrupt status.
References XZDma::ChannelState, XZDMA_IDLE, XZDma_DisableCh, XZDma_DisableIntr, XZDMA_IXR_ALL_INTR_MASK, XZDma_IntrClear, XZDma::IntrMask, XZDma_WriteReg, XZDma::Config, XZDma_Config::BaseAddress, XZDMA_CTRL0_RESET_VALUE, XZDMA_CTRL1_RESET_VALUE, XZDMA_DATA_ATTR_RESET_VALUE, XZDMA_DSCR_ATTR_RESET_VALUE, XZDma_TotalByteClear, XZDma_GetSrcIntrCnt, XZDma_GetDstIntrCnt, XZDma_Config::IsCacheCoherent, XZDMA_DSCR_ATTR_AXCOHRNT_SHIFT, XZDMA_WORD3_COHRNT_MASK.
Referenced by XZDma_CfgInitialize, XZDma_LinearExample, XZDma_LinkedListExample, XZDma_SimpleExample, XZDma_WriteOnlyExample.
XZDmaState XZDma_ChannelState(XZDma *InstancePtr)
This function returns the state of ZDMA core.
InstancePtr is a pointer to the XZDma instance. This function returns state of ZDMA core XZDMA_IDLE - If ZDMA core is in idle state.XZDMA_PAUSE - If ZDMA is in paused state.XZDMA_BUSY - If ZDMA is in busy state. None. C-style signature: XZDmaState XZDma_ChannelState(XZDma *InstancePtr)
References XZDma_ReadReg, XZDma::Config, XZDma_Config::BaseAddress, XZDMA_STS_ALL_MASK, XZDMA_STS_DONE_MASK, XZDMA_STS_DONE_ERR_MASK, XZDMA_IDLE, XZDMA_STS_PAUSE_MASK, XZDMA_PAUSE, XZDMA_BUSY.
s32 XZDma_SelfTest(XZDma *InstancePtr)
This file contains a diagnostic self-test function for the ZDMA driver.
Refer to the header file xzdma.h for more detailed information. InstancePtr is a pointer to XZDma instance. XST_SUCCESS if the test is successful.XST_FAILURE if the test is failed. None.
References XZDma_ReadReg, XZDma::Config, XZDma_Config::BaseAddress, XZDma_WriteReg, XZDMA_CTRL0_OVR_FETCH_MASK.
Referenced by XZDma_LinearExample, XZDma_LinkedListExample, XZDma_SimpleReadOnlyExample, XZDma_SelfTestExample, XZDma_SimpleExample, XZDma_WriteOnlyExample.
s32 XZDma_Stop(XZDma *InstancePtr)
Stops the ZDMA engine and releases power management resources if supported.
This function asserts the validity of the input instance pointer. If power management (XPM_SUPPORT) is enabled, it releases the power management node associated with the ZDMA instance. If the release fails, an error message is printed. The function returns the status of the operation. InstancePtr is a pointer to the XZDma instance. Status code: XST_SUCCESS if successful.Error code if PM resource release fails (when XPM_SUPPORT is defined). None.
References XZDma::Config, XZDma_Config::BaseAddress.
Referenced by XZDma_WriteOnlyExample.
void XZDma_IntrHandler(void *Instance)
This function is the interrupt handler for the ZDMA core.
This handler reads the pending interrupt from Status register, determines the source of the interrupts and calls the respective callbacks for the interrupts that are enabled in IRQ_ENABLE register, and finally clears the interrupts.The application is responsible for connecting this function to the interrupt system. Application beyond this driver is also responsible for providing callbacks to handle interrupts and installing the callbacks using XZDma_SetCallBack() during initialization phase. . Instance is a pointer to the XZDma instance to be worked on. None. To generate interrupt required interrupts should be enabled.
References XZDma_IntrGetStatus, XZDma_GetIntrMask, XZDMA_IXR_DMA_DONE_MASK, XZDma_DisableIntr, XZDMA_IXR_ALL_INTR_MASK, XZDma::ChannelState, XZDMA_IDLE, XZDma::DoneHandler, XZDma::DoneRef, XZDMA_IXR_ERR_MASK, XZDMA_IXR_DMA_PAUSE_MASK, XZDMA_PAUSE, XZDMA_IXR_AXI_WR_DATA_MASK, XZDMA_IXR_AXI_RD_DATA_MASK, XZDMA_IXR_AXI_RD_DST_DSCR_MASK, XZDMA_IXR_AXI_RD_SRC_DSCR_MASK, XZDma::ErrorHandler, XZDma::ErrorRef, XZDma_IntrClear.
Referenced by XZDma_LinearExample, XZDma_LinkedListExample, XZDma_SimpleReadOnlyExample, XZDma_SimpleExample, XZDma_WriteOnlyExample.
s32 XZDma_SetCallBack(XZDma *InstancePtr, XZDma_Handler HandlerType, void *CallBackFunc, void *CallBackRef)
This routine installs an asynchronous callback function for the given HandlerType.
HandlerType Callback Function Type ----------------------- -------------------------------------------------- XZDMA_HANDLER_DONE Done handler XZDMA_HANDLER_ERROR Error handler InstancePtr is a pointer to the XZDma instance to be worked on. HandlerType specifies which callback is to be attached. CallBackFunc is the address of the callback function. CallBackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS when handler is installed.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XZDMA_HANDLER_DONE, XZDMA_HANDLER_ERROR, XZDma::IsReady, XZDma::DoneHandler, XZDma::DoneRef, XZDma::ErrorHandler, XZDma::ErrorRef.
Referenced by XZDma_LinearExample, XZDma_LinkedListExample, XZDma_SimpleReadOnlyExample, XZDma_SimpleExample, XZDma_WriteOnlyExample.
void XZDma_ScatterGather(XZDma *InstancePtr, XZDma_Transfer *Data, u32 Num)
This function sets all the required fields for initiating data transfer in scatter gather mode.
InstancePtr is a pointer to the XZDma instance. Data is a pointer of array to the XZDma_Transfer structure which has all the configuration fields for initiating data transfer. Num specifies number of array elements of Data pointer. None. None.
References XZDma::Descriptor, XZDma_Descriptor::SrcDscrPtr, XZDma_Descriptor::DstDscrPtr, XZDma_Descriptor::DscrType, XZDMA_LINEAR, XZDma_WriteReg, XZDma::Config, XZDma_Config::BaseAddress, XZDMA_WORD0_LSB_MASK, XZDMA_WORD1_MSB_SHIFT, XZDMA_WORD1_MSB_MASK.
Referenced by XZDma_Start.
void XZDma_Enable(XZDma *InstancePtr)
This function enables all the interrupts which user intended to enable and enables the ZDMA channel for initiating data transfer.
InstancePtr is a pointer to the XZDma instance. None. None.
References XZDma_WriteReg, XZDma::Config, XZDma_Config::BaseAddress, XZDma::IntrMask, XZDMA_IXR_ALL_INTR_MASK, XZDma::ChannelState, XZDMA_BUSY, XZDma_EnableCh.
Referenced by XZDma_Start.