xscuwdt.c
s32 XScuWdt_CfgInitialize(XScuWdt *InstancePtr, XScuWdt_Config *ConfigPtr, u32 EffectiveAddress)
Initialize a specific watchdog timer instance/driver.
This function must be called before other functions of the driver are called. InstancePtr is a pointer to the XScuWdt instance. ConfigPtr is the config structure. EffectiveAddress is the base address for the device. It could be a virtual address if address translation is supported in the system, otherwise it is the physical address. XST_SUCCESS if initialization was successful.XST_DEVICE_IS_STARTED if the device has already been started. This function enables the watchdog mode.
References XScuWdt_Config::BaseAddr, XScuWdt::Config, XScuWdt::IsReady, XScuWdt::IsStarted, XScuWdt_SetWdMode.
Referenced by ScuWdtIntrExample, ScuWdtPolledExample.
void XScuWdt_Start(XScuWdt *InstancePtr)
Start the watchdog counter of the device.
InstancePtr is a pointer to the XScuWdt instance. None. User needs to select the appropriate mode (watchdog/timer) before using this API. See XScuWdt_SetWdMode/XScuWdt_SetTimerMode macros in xscuwdt.h.
References XScuWdt_Config::BaseAddr, XScuWdt::Config, XScuWdt::IsReady, XScuWdt::IsStarted, XSCUWDT_CONTROL_OFFSET, XSCUWDT_CONTROL_WD_ENABLE_MASK, XScuWdt_ReadReg, XScuWdt_WriteReg.
Referenced by ScuWdtIntrExample, ScuWdtPolledExample.
void XScuWdt_Stop(XScuWdt *InstancePtr)
Stop the watchdog timer.
InstancePtr is a pointer to the XScuWdt instance. None. None.
References XScuWdt_Config::BaseAddr, XScuWdt::Config, XScuWdt::IsReady, XScuWdt::IsStarted, XSCUWDT_CONTROL_OFFSET, XSCUWDT_CONTROL_WD_ENABLE_MASK, XScuWdt_ReadReg, XScuWdt_WriteReg.
Referenced by ScuWdtIntrExample, ScuWdtPolledExample.