xscuwdt.h
XSCUWDT_H
< prevent circular inclusions
by using protection macros
XScuWdt_IsWdtExpired
This function is used to check if the watchdog has timed-out and the last reset was caused by the watchdog reset.
InstancePtr is a pointer to the XScuWdt instance. TRUE if the watchdog has expired.FALSE if the watchdog has not expired. C-style signature: int XScuWdt_IsWdtExpired(XScuWdt *InstancePtr)
XScuWdt_IsTimerExpired
This function is used to check if the watchdog counter has reached 0 in timer mode.
InstancePtr is a pointer to the XScuWdt instance. TRUE if the watchdog has expired.FALSE if the watchdog has not expired. C-style signature: int XScuWdt_IsTimerExpired(XScuWdt *InstancePtr)
Referenced by ScuWdtIntrExample.
XScuWdt_RestartWdt
Re-start the watchdog timer.
This macro will read the watchdog load register and write the same value to load register to update the counter register. An application needs to call this function periodically to keep the watchdog from asserting the WDRESETREQ reset request output pin. InstancePtr is a pointer to the XScuWdt instance. None. C-style signature: void XScuWdt_RestartWdt(XScuWdt *InstancePtr)
Referenced by ScuWdtIntrExample, ScuWdtPolledExample.
XScuWdt_LoadWdt
Write to the watchdog timer load register.
This will also update the watchdog counter register with the new value. This macro can be used to change the time-out value. InstancePtr is a pointer to the XScuWdt instance. Value is the value to be written to the Watchdog Load register. None. C-style signature: void XScuWdt_LoadWdt(XScuWdt *InstancePtr, u32 Value)
Referenced by ScuWdtIntrExample, ScuWdtPolledExample, XScuWdt_SelfTest.
XScuWdt_SetWdMode
Put the watchdog timer in Watchdog mode by setting the WD mode bit of the Watchdog control register.
InstancePtr is a pointer to the XScuWdt instance. None. C-style signature: void XScuWdt_SetWdMode(XScuWdt *InstancePtr)
Referenced by ScuWdtPolledExample, XScuWdt_CfgInitialize.
XScuWdt_SetTimerMode
Put the watchdog timer in Timer mode by writing 0x12345678 and 0x87654321 successively to the Watchdog Disable Register.
The software must write 0x12345678 and 0x87654321 successively to the Watchdog Disable Register so that the watchdog mode bit in the Watchdog Control Register is set to zero. InstancePtr is a pointer to the XScuWdt instance. None. C-style signature: void XScuWdt_SetTimerMode(XScuWdt *InstancePtr)
Referenced by ScuWdtIntrExample.
XScuWdt_GetControlReg
Get the contents of the watchdog control register.
InstancePtr is a pointer to the XScuWdt instance. Contents of the watchdog control register. C-style signature: u32 XScuWdt_GetControlReg(XScuWdt *InstancePtr)
Referenced by ScuWdtIntrExample, XScuWdt_SelfTest.
XScuWdt_SetControlReg
Write to the watchdog control register.
InstancePtr is a pointer to the XScuWdt instance. ControlReg is the value to be written to the watchdog control register. None. C-style signature: void XScuWdt_SetControlReg(XScuWdt *InstancePtr, u32 ControlReg)
Referenced by ScuWdtIntrExample, XScuWdt_SelfTest.
XScuWdt_EnableAutoReload
Enable auto-reload mode.
InstancePtr is a pointer to the XScuWdt instance. None. C-style signature: void XScuWdt_EnableAutoReload(XScuWdt *InstancePtr)
XScuWdt_Config XScuWdt_ConfigTable[][]
This table contains configuration information for each watchdog timer device in the system.
Referenced by XScuWdt_LookupConfig.
XScuWdt_Config * XScuWdt_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XScuWdt_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xscuwdt.h for the definition of XScuWdt_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XScuWdt_Config::Name, XScuWdt_ConfigTable.
Referenced by ScuWdtIntrExample, ScuWdtPolledExample.
s32 XScuWdt_SelfTest(XScuWdt *InstancePtr)
Run a self-test on the WDT.
This test stops the watchdog, writes a value to the watchdog load register, starts the watchdog and verifies that the value read from the counter register is less that the value written to the load register. It then restores the control register and the watchdog load register. InstancePtr is a pointer to the XScuWdt instance. XST_SUCCESS if self-test was successful.XST_FAILURE if the WDT is not decrementing. None.
References XScuWdt::IsReady, XSCUWDT_CONTROL_WD_ENABLE_MASK, XSCUWDT_COUNTER_OFFSET, XScuWdt_GetControlReg, XSCUWDT_LOAD_OFFSET, XScuWdt_LoadWdt, XScuWdt_ReadReg, XScuWdt_SetControlReg.
Referenced by ScuWdtIntrExample.
s32 XScuWdt_CfgInitialize(XScuWdt *InstancePtr, XScuWdt_Config *ConfigPtr, u32 EffectiveAddress)
Initialize a specific watchdog timer instance/driver.
This function must be called before other functions of the driver are called. InstancePtr is a pointer to the XScuWdt instance. ConfigPtr is the config structure. EffectiveAddress is the base address for the device. It could be a virtual address if address translation is supported in the system, otherwise it is the physical address. XST_SUCCESS if initialization was successful.XST_DEVICE_IS_STARTED if the device has already been started. This function enables the watchdog mode.
References XScuWdt_Config::BaseAddr, XScuWdt::Config, XScuWdt::IsReady, XScuWdt::IsStarted, XScuWdt_SetWdMode.
Referenced by ScuWdtIntrExample, ScuWdtPolledExample.
void XScuWdt_Start(XScuWdt *InstancePtr)
Start the watchdog counter of the device.
InstancePtr is a pointer to the XScuWdt instance. None. User needs to select the appropriate mode (watchdog/timer) before using this API. See XScuWdt_SetWdMode/XScuWdt_SetTimerMode macros in xscuwdt.h.
References XScuWdt_Config::BaseAddr, XScuWdt::Config, XScuWdt::IsReady, XScuWdt::IsStarted, XSCUWDT_CONTROL_OFFSET, XSCUWDT_CONTROL_WD_ENABLE_MASK, XScuWdt_ReadReg, XScuWdt_WriteReg.
Referenced by ScuWdtIntrExample, ScuWdtPolledExample.
void XScuWdt_Stop(XScuWdt *InstancePtr)
Stop the watchdog timer.
InstancePtr is a pointer to the XScuWdt instance. None. None.
References XScuWdt_Config::BaseAddr, XScuWdt::Config, XScuWdt::IsReady, XScuWdt::IsStarted, XSCUWDT_CONTROL_OFFSET, XSCUWDT_CONTROL_WD_ENABLE_MASK, XScuWdt_ReadReg, XScuWdt_WriteReg.
Referenced by ScuWdtIntrExample, ScuWdtPolledExample.