csi2tx
XCSI2TX_HANDLER_WRG_LANE
XCSI2TX_HANDLER_GSPFIFO_FULL
XCSI2TX_HANDLER_ULPS
XCSI2TX_HANDLER_LINEBUF_FULL
XCSI2TX_HANDLER_WRG_DATATYPE
XCSI2TX_HANDLER_UNDERRUN_PIXEL
XCSI2TX_HANDLER_LCERRVC0
XCSI2TX_HANDLER_LCERRVC1
XCSI2TX_HANDLER_LCERRVC2
XCSI2TX_HANDLER_LCERRVC3
XCSI2TX_CCR_OFFSET
Core Configuration Register.
Referenced by XCsi2Tx_SelfTest, XCsi2Tx_SetLineCountForVC.
XCSI2TX_PCR_OFFSET
XCSI2TX_GIER_OFFSET
Global Interrupt Register.
Referenced by XCsi2Tx_Configure, XCsi2Tx_SelfTest.
XCSI2TX_ISR_OFFSET
Interrupt Status Register.
Referenced by XCsi2Tx_GetIntrStatus, XCsi2Tx_InterruptClear, XCsi2Tx_SelfTest.
XCSI2TX_IER_OFFSET
Interrupt Enable Register.
Referenced by XCsi2Tx_GetIntrEnable, XCsi2Tx_IntrDisable, XCsi2Tx_IntrEnable, XCsi2Tx_SelfTest.
XCSI2TX_SPKTR_OFFSET
Generic Short Packet Entry.
Referenced by XCsi2Tx_GetShortPacket, XCsi2Tx_SelfTest.
XCSI2TX_LINE_COUNT_VC0
Line Count for VC0.
Referenced by XCsi2Tx_GetLineCountForVC, XCsi2Tx_SetLineCountForVC.
XCSI2TX_LINE_COUNT_VC1
Line Count for VC1.
XCSI2TX_LINE_COUNT_VC2
Line Count for VC2.
XCSI2TX_LINE_COUNT_VC3
Line Count for VC3.
XCSI2TX_GSP_OFFSET
XCSI2TX_GIER_GIE_MASK
Global Interrupt Enable bit.
XCSI2TX_GIER_GIE_SHIFT
Shift bits for Global Interrupt Enable.
XCSI2TX_GIER_SET
Enable the Global Interrupts.
XCSI2TX_GIER_RESET
Disable the Global Interrupts.
XCSI2TX_CCR_COREENB_MASK
XCSI2TX_CCR_SOFTRESET_MASK
XCSI2TX_CSR_RIPCD_MASK
XCSI2TX_CCR_ULPS_MASK
XCSI2TX_CCR_CLKMODE_MASK
XCSI2TX_CCR_COREENB_SHIFT
XCSI2TX_CCR_SOFTRESET_SHIFT
XCSI2TX_CSR_RIPCD_SHIFT
XCSI2TX_CCR_ULPS_SHIFT
XCSI2TX_CCR_CLKMODE_SHIFT
XCSI2TX_PCR_LINEGEN_MASK
XCSI2TX_PCR_PIXEL_MASK
XCSI2TX_PCR_MAXLANES_MASK
XCSI2TX_PCR_ACTLANES_MASK
XCSI2TX_PCR_LINEGEN_SHIFT
XCSI2TX_PCR_PIXEL_SHIFT
XCSI2TX_PCR_MAXLANES_SHIFT
XCSI2TX_PCR_ACTLANES_SHIFT
XCSI2TX_IER_ALLINTR_MASK
XCSI2TX_ISR_ALLINTR_MASK
XCSI2TX_UNDERRUN_PIXEL_MASK
XCSI2TX_WRONG_DATATYPE_MASK
XCSI2TX_LINE_BUFF_FULL_MASK
XCSI2TX_DPHY_ULPS_MASK
XCSI_GPSFIFO_MASK
XCSI_INCORT_LANE_MASK
XCSITX_LCSTAT_VC0_IER_MASK
Line Count Status for VC0 IER.
Referenced by XCsi2Tx_IntrDisable, XCsi2Tx_IntrEnable.
XCSITX_LCSTAT_VC1_IER_MASK
Line Count Status for VC1 IER.
Referenced by XCsi2Tx_IntrDisable, XCsi2Tx_IntrEnable.
XCSITX_LCSTAT_VC2_IER_MASK
Line Count Status for VC2 IER.
Referenced by XCsi2Tx_IntrDisable, XCsi2Tx_IntrEnable.
XCSITX_LCSTAT_VC3_IER_MASK
Line Count Status for VC3 IER.
Referenced by XCsi2Tx_IntrDisable, XCsi2Tx_IntrEnable.
XCSITX_LCSTAT_VC0_IER_OFFSET
Line Count Status for VC0 IER Offset.
XCSITX_LCSTAT_VC1_IER_OFFSET
Line Count Status for VC1 IER Offset.
XCSITX_LCSTAT_VC2_IER_OFFSET
Line Count Status for VC2 IER Offset.
XCSITX_LCSTAT_VC3_IER_OFFSET
Line Count Status for VC3 IER Offset.
XCSITX_LCSTAT_VC0_ISR_MASK
Line Count Status for VC0 ISR.
Referenced by XCsi2Tx_InterruptClear, XCsi2Tx_IntrHandler.
XCSITX_LCSTAT_VC1_ISR_MASK
Line Count Status for VC1 ISR.
Referenced by XCsi2Tx_InterruptClear, XCsi2Tx_IntrHandler.
XCSITX_LCSTAT_VC2_ISR_MASK
Line Count Status for VC2 ISR.
Referenced by XCsi2Tx_InterruptClear, XCsi2Tx_IntrHandler.
XCSITX_LCSTAT_VC3_ISR_MASK
Line Count Status for VC3 ISR.
Referenced by XCsi2Tx_InterruptClear, XCsi2Tx_IntrHandler.
XCSITX_LCSTAT_VC0_ISR_OFFSET
Line Count Status for VC0 ISR Offset.
Referenced by XCsi2Tx_IntrHandler.
XCSITX_LCSTAT_VC1_ISR_OFFSET
Line Count Status for VC1 ISR Offset.
Referenced by XCsi2Tx_IntrHandler.
XCSITX_LCSTAT_VC2_ISR_OFFSET
Line Count Status for VC2 ISR Offset.
Referenced by XCsi2Tx_IntrHandler.
XCSITX_LCSTAT_VC3_ISR_OFFSET
Line Count Status for VC3 ISR Offset.
Referenced by XCsi2Tx_IntrHandler.
XCSI2TX_SPKTR_DATA_MASK
XCSI2TX_SPKTR_DATA_SHIFT
XCSI2TX_SPKTR_VC_MASK
XCSI2TX_SPKTR_VC_SHIFT
XCSI2TX_SPKTR_DT_MASK
XCSI2TX_SPKTR_DT_SHIFT
XCsi2Tx_LCStatus
Less no of lines recvd.
typedef void(* XCsi2Tx_CallBack)(void *CallBackRef, u32 Mask))(void *CallBackRef, u32 Mask)
Callback type for all interrupts defined.
CallBackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. Mask is a bit mask indicating the cause of the event. For current core version, this parameter is "OR" of 0 or more XCSI2TX_ISR_*_MASK constants defined in xcsi_hw.h. None None
XCsi2Tx Csi
static void StubErrCallBack(void *Callbackref, u32 ErrorMask)
This routine is a stub for the asynchronous error interrupt callback.
The stub is here in case the upper layer forgot to set the handler. On initialization, Error interrupt handler is set to this callback. It is considered an error for this handler to be invoked. Callbackref is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. ErrorMask is a bit mask indicating the cause of the error. Its value equals 'OR'ing one or more XCSI_ISR_*_MASK values defined in xcsi_hw.h. None. None.
u32 XCsi2Tx_CfgInitialize(XCsi2Tx *InstancePtr, XCsi2Tx_Config *CfgPtr, UINTPTR EffectiveAddr)
Initialize the XCsi2Tx instance provided by the caller based on the given Config structure.
InstancePtr is the XCsi2Tx instance to operate on. CfgPtr is the device configuration structure containing information about a specific CSI. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS Initialization was successful. None.
References XCsi2Tx_Config::BaseAddr, XCsi2Tx::Config, XCsi2Tx::DPhyUlpsCallBack, XCsi2Tx::GSPFIFOCallBack, XCsi2Tx::IncorrectLaneCallBack, XCsi2Tx::IsReady.
Referenced by Csi2TxSelfTestExample.
u32 XCsi2Tx_Reset(XCsi2Tx *InstancePtr)
This function will do a reset of the IP.
This will reset the values of all registers except Core Config and Protocol Config registers. InstancePtr is the XCsi2Tx instance to operate on. XST_SUCCESS On proper reset.XST_FAILURE on timeout and core being stuck in reset None.
Referenced by XCsi2Tx_Configure, XCsi2Tx_SelfTest.
u32 XCsi2Tx_Activate(XCsi2Tx *InstancePtr, u8 Flag)
This function will enable/disable the IP Core to start processing.
InstancePtr is the XCsi2Tx instance to operate on. Flag will be used to indicate Enable or Disable action XST_SUCCESS on successful core enable or disableXST_FAILURE if core disable times out. None.
References XCsi2Tx::IsReady, XCSI2TX_DISABLE, XCSI2TX_ENABLE.
u32 XCsi2Tx_Configure(XCsi2Tx *InstancePtr)
This function will configure the core with proper number of Active Lanes.
InstancePtr is the XCsi2Tx instance to operate on. XST_SUCCESS On configuring the core.XST_FAILURE if active lanes not set correctly None.
References XCsi2Tx::ActiveLanes, XCsi2Tx_Config::BaseAddr, XCsi2Tx::Config, XCsi2Tx::IsReady, XCsi2Tx_GetIntrEnable, XCSI2TX_GIER_OFFSET, XCsi2Tx_IntrEnable, XCsi2Tx_IsActiveLaneCountValid, XCsi2Tx_Reset.
void XCsi2Tx_GetShortPacket(XCsi2Tx *InstancePtr, XCsi2Tx_SPktData *ShortPacketStruct)
This function will get the short packet received in the FIFO from the Generic Short Packet Register and fill up the structure passed from caller.
InstancePtr is the XCsi2Tx instance to operate on ShortPacketStruct is going to be filled up by this function and returned to the caller. None
References XCsi2Tx_Config::BaseAddr, XCsi2Tx::Config, XCsi2Tx_SPktData::Data, XCsi2Tx_SPktData::DataType, XCsi2Tx_SPktData::VirtualChannel, XCSI2TX_SPKTR_OFFSET.
u8 XCsi2Tx_IsActiveLaneCountValid(XCsi2Tx *InstancePtr, u8 ActiveLanesCount)
This function checks the validity of the active lanes parameter.
InstancePtr is a pointer to the Subsystem instance to be worked on. ActiveLanesCount is the lane count to check if valid. 1 if specified Active Lanes is valid.0 otherwise, if the Active Lanes specified isn't valid as per spec and design. None.
References XCsi2Tx::Config, XCsi2Tx_Config::MaxLanesPresent.
Referenced by XCsi2Tx_Configure.
u32 XCsi2Tx_SetLineCountForVC(XCsi2Tx *InstancePtr, u8 VC, u16 LineCount)
This function sets the Line Count for virtual Channel if Frame End Generation feature is enabled.
This is to be called before starting the core. InstancePtr is a pointer to the Subsystem instance to be worked on. VC is which Virtual channel to be configured for (0-3). LineCount is valid line count for the Virtual channel. XST_NO_FEATURE if Frame End generation is not enabledXST_INVALID_PARAM if any param is invalid e.g. VC is always 0 to 3 and Line Count is 0 to 0xFFFF.XST_FAILURE in case the core is already running.XST_SUCCESS otherwise None.
References XCsi2Tx_Config::BaseAddr, XCsi2Tx::Config, XCsi2Tx_Config::FEGenEnabled, XCSI2TX_CCR_OFFSET, XCSI2TX_LINE_COUNT_VC0, XCSI2TX_MAX_VC.
u32 XCsi2Tx_GetLineCountForVC(XCsi2Tx *InstancePtr, u8 VC, u16 *LineCount)
This function gets the Line Count for virtual Channel if Frame End Generation feature is enabled.
InstancePtr is a pointer to the Subsystem instance to be worked on. VC is which Virtual channel to be configured for (0-3). LineCount is pointer to variable to be filled with line count for the Virtual channel XST_NO_FEATURE if Frame End generation is not enabledXST_INVALID_PARAM if any param is invalid e.g. VC is always 0 to 3 and Line Count is 0 to 0xFFFF.XST_SUCCESS otherwise None.
References XCsi2Tx_Config::BaseAddr, XCsi2Tx::Config, XCsi2Tx_Config::FEGenEnabled, XCSI2TX_LINE_COUNT_VC0, XCSI2TX_MAX_VC.
static void XCsi2Tx_BitSet(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask)
This function is used to set bit in a register.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitMask of bit to be set None None
static void XCsi2Tx_BitReset(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask)
This function is used to reset bit in a register.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitMask of bit to be reset None None
static u32 XCsi2Tx_GetBitField(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask, u32 BitShift)
This function is used to get the value of bitfield from register.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitMask of bit fields to be retrieved BitShift is offset of the field in register Bit Field Value in u32 format None
static void XCsi2Tx_SetBitField(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask, u32 BitShift, u32 Value)
This function is used to set the value of bitfield from register.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitMask of bit fields to be retrieved BitShift is offset of the field in register Value is to be set. Passed in u32 format. None None
static void XCsi2Tx_SetSoftReset(XCsi2Tx *InstancePtr)
This function is used to start the soft reset process by setting the soft reset bit in the Core Configuration Register.
InstancePtr is a pointer to the CSI2 instance to be worked on. None None
static void XCsi2Tx_ClearSoftReset(XCsi2Tx *InstancePtr)
This function is used to stop the soft reset process by resetting the soft reset bit in the Core Configuration Register.This is done usually after Reset in Progress is 0.
InstancePtr is a pointer to the CSI Instance to be worked on. None None
static void XCsi2Tx_Disable(XCsi2Tx *InstancePtr)
This function is used to stop the packet processing by resetting Enable core bit in the Core Configuration Register.
InstancePtr is a pointer to the CSI Instance to be worked on. None None
static void XCsi2Tx_Enable(XCsi2Tx *InstancePtr)
This function is used to start the packet processing by setting Enable core bit in the Core Configuration Register.This is done after the configuration of active lanes, interrupt masks, etc.
InstancePtr is a pointer to the CSI Instance to be worked on. None None
static u32 XCsi2Tx_IsCsiEnabled(XCsi2Tx *InstancePtr)
This function is used to check if the Core is enabled by checking the core enable bit.
InstancePtr is a pointer to the CSI Instance to be worked on. 1 - If the CSI core is enabled 0 - If the CSI core is disabled None
static u32 XCsi2Tx_IsUlps(XCsi2Tx *InstancePtr)
This function is used to check if lanes are in ulps mode.
InstancePtr is a pointer to the CSI Instance to be worked on. 1 - ulps mode enter 0 - ulps mode exit None
static void XCsi2Tx_SetUlps(XCsi2Tx *InstancePtr, u32 Value)
This function is used to set lanes in ulps mode.
InstancePtr is a pointer to the CSI Instance to be worked on. Value 1 - ulps mode enter 0 - ulps mode exit None None
static u32 XCsi2Tx_GetMaxLaneCount(XCsi2Tx *InstancePtr)
This function is used to get the number of lanes configured in the IP.
InstancePtr is a pointer to the CSI Instance to be worked on. Max number of lanes available in u32 format None
static u32 XCsi2Tx_GetPixelMode(XCsi2Tx *InstancePtr)
This function is used to get the Pixel Mode.
InstancePtr is a pointer to the CSI Instance to be worked on. 0x0 - Single Pixel Mode 0x1 - Dual Pixel Mode 0x3 - Quad Pixel Mode None
static u32 XCsi2Tx_IsLineGen(XCsi2Tx *InstancePtr)
This function is to get the Line Synchronization packet Generation status.
InstancePtr is a pointer to the CSI Instance to be worked on. 0 : Do not generate 1 : Generate None
static void XCsi2Tx_SetLineGen(XCsi2Tx *InstancePtr, u32 Value)
This function is to set the Line Synchronization packet Generation status.
InstancePtr is a pointer to the CSI Instance to be worked on. Value 0 : Do not generate 1 : Generate None None
static u32 XCsi2Tx_GetActiveLaneCount(XCsi2Tx *InstancePtr)
This function is used to get the actual number of lanes being used by the IP to communicate with a CSI2 Tx.
This is lesser or equal to Max lanes. InstancePtr is a pointer to the CSI Instance to be worked on. Number of lanes being used in u32 format None
static void XCsi2Tx_SetActiveLaneCount(XCsi2Tx *InstancePtr, u32 Value)
This function is used to set the actual number of lanes to be used to communicate with a CSI2 Tx.
This is lesser than or equal to Max lanes. InstancePtr is a pointer to the CSI Instance to be worked on. Value is number of lanes to be made active None None
static u32 XCsi2Tx_IsSoftResetInProgress(XCsi2Tx *InstancePtr)
This function is used to check if a reset is completed or is in progress.
InstancePtr is a pointer to the CSI Instance to be worked on. 1 - If the Soft reset operation is in progress0 - If the Soft reset operation is completed None
static void XCsi2Tx_SetGlobalInterrupt(XCsi2Tx *InstancePtr)
static void XCsi2Tx_ResetGlobalInterrupt(XCsi2Tx *InstancePtr)
This function is used to disable the global interrupts.
This is done after disabling the core. InstancePtr is a pointer to the CSI Instance to be worked on. None None
static u32 XCsi2Tx_GetGSPCount(XCsi2Tx *InstancePtr)
This function is used to get the Short Packet Status.
InstancePtr is a pointer to the CSI Instance to be worked on. Number of Generic Short Packets can be safely written to Generic Short packet FIFO, before it goes full. None
static void XCsi2Tx_SetGSPEntry(XCsi2Tx *InstancePtr, u32 Value)
This function is used to set value to Generic Short Packet Entry.
InstancePtr is a pointer to the CSI Instance to be worked on. Value 31:24 Reserved 23:16 Byte 1 of short packet 15:8 Byte 0 of short packet 7:6 VC value of short packet 5:0 Short packet data type None None
static void XCsi2Tx_SetClkMode(XCsi2Tx *InstancePtr, u8 Value)
This function is used to set the clock mode.
InstancePtr is a pointer to the CSI Instance to be worked on. Value 0 - continuous clock mode 1 - non-continuous clock mode None None
static u32 XCsi2Tx_GetClkMode(XCsi2Tx *InstancePtr)
This function is used to get the clock mode.
InstancePtr is a pointer to the CSI Instance to be worked on. 0 - Continuous Clock Mode1 - Non-continuous Clock Mode None
XCsi2Tx_Config * XCsi2Tx_LookupConfig(UINTPTR BaseAddress)
Look up the hardware configuration for a device instance.
DeviceId is the unique device ID of the device to lookup for The reference to the configuration record in the configuration table (in xcsi2tx_g.c) corresponding to the Device ID or if not found,a NULL pointer is returned. None
Referenced by Csi2TxSelfTestExample.
u32 XCsi2Tx_SelfTest(XCsi2Tx *InstancePtr)
Runs a self-test on the driver/device.
This test checks if the LaneCount present in register matches the one from the generated file. InstancePtr is a pointer to the XCsi instance. XST_SUCCESS if self-test was successfulXST_FAILURE if the read value was not equal to _g.c file None
References XCsi2Tx_Config::BaseAddr, XCsi2Tx::Config, XCsi2Tx::IsReady, XCsi2Tx_Config::MaxLanesPresent, XCSI2TX_CCR_OFFSET, XCSI2TX_GIER_OFFSET, XCSI2TX_IER_OFFSET, XCSI2TX_ISR_OFFSET, XCsi2Tx_Reset, XCSI2TX_SPKTR_OFFSET.
Referenced by Csi2TxSelfTestExample.
void XCsi2Tx_IntrHandler(void *InstancePtr)
This function is the interrupt handler for the CSI2 Tx core.
This handler reads the pending interrupt from the Interrupt Status register, determines the source of the interrupts and calls the respective callbacks for the interrupts that are enabled in Interrupt Enable register, and finally clears the interrupts.The application is responsible for connecting this function to the interrupt system. Application beyond this core is also responsible for providing callbacks to handle interrupts and installing the callbacks using XCsi2Tx_SetCallBack() during initialization phase. InstancePtr is a pointer to the XCsi2Tx core instance. None. Interrupt should be enabled to execute interrupt handler.
References XCsi2Tx::Config, XCsi2Tx::DPhyUlpsCallBack, XCsi2Tx::DPhyUlpsRef, XCsi2Tx_Config::FEGenEnabled, XCsi2Tx::GSPFIFOCallBack, XCsi2Tx::IncorrectLaneCallBack, XCsi2Tx::IncorrectLaneRef, XCsi2Tx::IsReady, XCsi2Tx::LCErrVC0Ref, XCsi2Tx::LCErrVC1Ref, XCsi2Tx::LCErrVC2Ref, XCsi2Tx::LCErrVC3Ref, XCsi2Tx::LineBufferRef, XCsi2Tx::UnderrunPixelRef, XCsi2Tx_GetIntrStatus, XCsi2Tx_InterruptClear, XCSI2TX_LC_LESS_LINES, XCSI2TX_LC_MORE_LINES, XCSITX_LCSTAT_VC0_ISR_MASK, XCSITX_LCSTAT_VC0_ISR_OFFSET, XCSITX_LCSTAT_VC1_ISR_MASK, XCSITX_LCSTAT_VC1_ISR_OFFSET, XCSITX_LCSTAT_VC2_ISR_MASK, XCSITX_LCSTAT_VC2_ISR_OFFSET, XCSITX_LCSTAT_VC3_ISR_MASK, XCSITX_LCSTAT_VC3_ISR_OFFSET.
int XCsi2Tx_SetCallBack(XCsi2Tx *InstancePtr, u32 HandleType, void *Callbackfunc, void *Callbackref)
This routine installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function Type ---------------------------- -------------------------------------------- (XCSI2TX_HANDLER_WRG_LANE) IncorrectLaneCallBack (XCSI2TX_HANDLER_GSPFIFO_FULL) GSPFIFOCallBack (XCSI2TX_HANDLER_ULPS) DPhyUlpsCallBack (XCSI2TX_HANDLER_LINEBUF_FULL) LineBufferCallBack (XCSI2TX_HANDLER_WRG_DATATYPE) WrgDataTypeCallBack (XCSI2TX_HANDLER_UNDERRUN_PIXEL) UnderrunPixelCallBack (XCSI2TX_HANDLER_LCERRVC0) LineCountErrVC0 (XCSI2TX_HANDLER_LCERRVC1) LineCountErrVC1 (XCSI2TX_HANDLER_LCERRVC2) LineCountErrVC2 (XCSI2TX_HANDLER_LCERRVC3) LineCountErrVC3 InstancePtr is the XCsi2Tx instance to operate on HandleType is the type of call back to be registered. Callbackfunc is the pointer to a call back function which is called when a particular event occurs. Callbackref is a void pointer to data to be referenced to by the Callbackfunc XST_SUCCESS when handler is installed.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XCsi2Tx::DPhyUlpsCallBack, XCsi2Tx::DPhyUlpsRef, XCsi2Tx::GSPFIFOCallBack, XCsi2Tx::IncorrectLaneCallBack, XCsi2Tx::IncorrectLaneRef, XCsi2Tx::IsReady, XCsi2Tx::LCErrVC0Ref, XCsi2Tx::LCErrVC1Ref, XCsi2Tx::LCErrVC2Ref, XCsi2Tx::LCErrVC3Ref, XCsi2Tx::LineBufferRef, XCsi2Tx::UnderrunPixelRef.
u32 XCsi2Tx_GetIntrEnable(XCsi2Tx *InstancePtr)
This function will get the interrupt mask set (enabled) in the CSI2 Tx core.
InstancePtr is the XCsi instance to operate on Interrupt Mask with bits set for corresponding interrupt in Interrupt enable register None
References XCsi2Tx_Config::BaseAddr, XCsi2Tx::Config, XCSI2TX_IER_OFFSET.
Referenced by XCsi2Tx_Configure.
void XCsi2Tx_IntrEnable(XCsi2Tx *InstancePtr, u32 Mask)
This function will enable the interrupts present in the interrupt mask passed onto the function.
InstancePtr is the XCsi instance to operate on Mask is the interrupt mask which need to be enabled in core None None
References XCsi2Tx_Config::BaseAddr, XCsi2Tx::Config, XCsi2Tx_Config::FEGenEnabled, XCSI2TX_IER_OFFSET, XCSITX_LCSTAT_VC0_IER_MASK, XCSITX_LCSTAT_VC1_IER_MASK, XCSITX_LCSTAT_VC2_IER_MASK, XCSITX_LCSTAT_VC3_IER_MASK.
Referenced by XCsi2Tx_Configure.
void XCsi2Tx_IntrDisable(XCsi2Tx *InstancePtr, u32 Mask)
This function will disable the interrupts present in the interrupt mask passed onto the function.
InstancePtr is the XCsi instance to operate on Mask is the interrupt mask which need to be enabled in core None None
References XCsi2Tx_Config::BaseAddr, XCsi2Tx::Config, XCsi2Tx_Config::FEGenEnabled, XCSI2TX_IER_OFFSET, XCSITX_LCSTAT_VC0_IER_MASK, XCSITX_LCSTAT_VC1_IER_MASK, XCSITX_LCSTAT_VC2_IER_MASK, XCSITX_LCSTAT_VC3_IER_MASK.
u32 XCsi2Tx_GetIntrStatus(XCsi2Tx *InstancePtr)
This function will get the list of interrupts pending in the Interrupt Status Register of the CSI2 Tx core.
InstancePtr is the XCsi instance to operate on Interrupt Mask with bits set for corresponding interrupt in Interrupt Status register None
References XCsi2Tx_Config::BaseAddr, XCsi2Tx::Config, XCSI2TX_ISR_OFFSET.
Referenced by XCsi2Tx_IntrHandler.
void XCsi2Tx_InterruptClear(XCsi2Tx *InstancePtr, u32 Mask)
This function will clear the interrupts set in the Interrupt Status Register of the CSI2 Tx core.
InstancePtr is the XCsi instance to operate on Mask is Interrupt Mask with bits set for corresponding interrupt to be cleared in the Interrupt Status register None None
References XCsi2Tx_Config::BaseAddr, XCsi2Tx::Config, XCsi2Tx_Config::FEGenEnabled, XCSI2TX_ISR_OFFSET, XCSITX_LCSTAT_VC0_ISR_MASK, XCSITX_LCSTAT_VC1_ISR_MASK, XCSITX_LCSTAT_VC2_ISR_MASK, XCSITX_LCSTAT_VC3_ISR_MASK.
Referenced by XCsi2Tx_IntrHandler.
static u32 XCsi2Tx_ReadReg(UINTPTR BaseAddress, u32 RegOffset)
Static inline function to read data from CSI register space.
BaseAddress is the base address of CSI RegOffset is the register offset. Value of the register. None
static void XCsi2Tx_WriteReg(UINTPTR BaseAddress, u32 RegOffset, u32 Data)
Static inline function to write data to CSI register space.
BaseAddress is the base address of CSI RegOffset is the register offset. Data is the value to be written to the register. None. None.
u32 Csi2TxSelfTestExample(u32 DeviceId)
This function checks if the Max Lane count from the generated file matches the value present in the protocol configuration register.
DeviceId is the CSI2Tx Controller Device id. XST_SUCCESS if Lane Count match XST_FAILURE if Lane Count don't match. None.
References XCsi2Tx_Config::BaseAddr, XCsi2Tx_CfgInitialize, XCsi2Tx_LookupConfig, XCsi2Tx_SelfTest.
Referenced by main.
int main()
The entry point for this example.
It invokes the example function, and reports the execution status. None. XST_SUCCESS if example finishes successfullyXST_FAILURE if example fails. None.
References Csi2TxSelfTestExample.
XCSI2TX_RESET_TIMEOUT
XCSI2TX_H_
Prevent circular inclusions by using protection macros.
XCSI2TX_ENABLE
Flag denoting enabling of CSI.
Referenced by XCsi2Tx_Activate.
XCSI2TX_DISABLE
Flag denoting disabling of CSI.
Referenced by XCsi2Tx_Activate.
XCSI2TX_MAX_LANES
Max Lanes supported by CSI.
XCSI2TX_INACTIVE
XCSI2TX_READY
XCSI2TX_MAX_VC
Max number of Virtual Channels.
Referenced by XCsi2Tx_GetLineCountForVC, XCsi2Tx_SetLineCountForVC.
XCSI2TX_HW_H_
Prevent circular inclusions by using protection macros.
XCSI2TX_GSP_MASK
Number of GSPs can be safely written to GSP FIFO, before it goes full.
XCSI2TX_GSP_SHIFT
GSP_MASK
GSP_DEFAULT
SPKTR_MASK
SPKTR_DEFAULT
IER_MASK
IER_DEFAULT
ISR_MASK
ISR_DEFAULT
GIER_MASK
GIER_DEFAULT
ACT_LANES_MASK
CCR_MASK
CCR_DEFAULT
CSI2TX_DEV_ID