xcsi2tx.c
XCSI2TX_RESET_TIMEOUT
static void StubErrCallBack(void *Callbackref, u32 ErrorMask)
This routine is a stub for the asynchronous error interrupt callback.
The stub is here in case the upper layer forgot to set the handler. On initialization, Error interrupt handler is set to this callback. It is considered an error for this handler to be invoked. Callbackref is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. ErrorMask is a bit mask indicating the cause of the error. Its value equals 'OR'ing one or more XCSI_ISR_*_MASK values defined in xcsi_hw.h. None. None.
u32 XCsi2Tx_CfgInitialize(XCsi2Tx *InstancePtr, XCsi2Tx_Config *CfgPtr, UINTPTR EffectiveAddr)
Initialize the XCsi2Tx instance provided by the caller based on the given Config structure.
InstancePtr is the XCsi2Tx instance to operate on. CfgPtr is the device configuration structure containing information about a specific CSI. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS Initialization was successful. None.
References XCsi2Tx_Config::BaseAddr, XCsi2Tx::Config, XCsi2Tx::DPhyUlpsCallBack, XCsi2Tx::GSPFIFOCallBack, XCsi2Tx::IncorrectLaneCallBack, XCsi2Tx::IsReady.
Referenced by Csi2TxSelfTestExample.
u32 XCsi2Tx_Reset(XCsi2Tx *InstancePtr)
This function will do a reset of the IP.
This will reset the values of all registers except Core Config and Protocol Config registers. InstancePtr is the XCsi2Tx instance to operate on. XST_SUCCESS On proper reset.XST_FAILURE on timeout and core being stuck in reset None.
Referenced by XCsi2Tx_Configure, XCsi2Tx_SelfTest.
u32 XCsi2Tx_Activate(XCsi2Tx *InstancePtr, u8 Flag)
This function will enable/disable the IP Core to start processing.
InstancePtr is the XCsi2Tx instance to operate on. Flag will be used to indicate Enable or Disable action XST_SUCCESS on successful core enable or disableXST_FAILURE if core disable times out. None.
References XCsi2Tx::IsReady, XCSI2TX_DISABLE, XCSI2TX_ENABLE.
u32 XCsi2Tx_Configure(XCsi2Tx *InstancePtr)
This function will configure the core with proper number of Active Lanes.
InstancePtr is the XCsi2Tx instance to operate on. XST_SUCCESS On configuring the core.XST_FAILURE if active lanes not set correctly None.
References XCsi2Tx::ActiveLanes, XCsi2Tx_Config::BaseAddr, XCsi2Tx::Config, XCsi2Tx::IsReady, XCsi2Tx_GetIntrEnable, XCSI2TX_GIER_OFFSET, XCsi2Tx_IntrEnable, XCsi2Tx_IsActiveLaneCountValid, XCsi2Tx_Reset.
void XCsi2Tx_GetShortPacket(XCsi2Tx *InstancePtr, XCsi2Tx_SPktData *ShortPacketStruct)
This function will get the short packet received in the FIFO from the Generic Short Packet Register and fill up the structure passed from caller.
InstancePtr is the XCsi2Tx instance to operate on ShortPacketStruct is going to be filled up by this function and returned to the caller. None
References XCsi2Tx_Config::BaseAddr, XCsi2Tx::Config, XCsi2Tx_SPktData::Data, XCsi2Tx_SPktData::DataType, XCsi2Tx_SPktData::VirtualChannel, XCSI2TX_SPKTR_OFFSET.
u8 XCsi2Tx_IsActiveLaneCountValid(XCsi2Tx *InstancePtr, u8 ActiveLanesCount)
This function checks the validity of the active lanes parameter.
InstancePtr is a pointer to the Subsystem instance to be worked on. ActiveLanesCount is the lane count to check if valid. 1 if specified Active Lanes is valid.0 otherwise, if the Active Lanes specified isn't valid as per spec and design. None.
References XCsi2Tx::Config, XCsi2Tx_Config::MaxLanesPresent.
Referenced by XCsi2Tx_Configure.
u32 XCsi2Tx_SetLineCountForVC(XCsi2Tx *InstancePtr, u8 VC, u16 LineCount)
This function sets the Line Count for virtual Channel if Frame End Generation feature is enabled.
This is to be called before starting the core. InstancePtr is a pointer to the Subsystem instance to be worked on. VC is which Virtual channel to be configured for (0-3). LineCount is valid line count for the Virtual channel. XST_NO_FEATURE if Frame End generation is not enabledXST_INVALID_PARAM if any param is invalid e.g. VC is always 0 to 3 and Line Count is 0 to 0xFFFF.XST_FAILURE in case the core is already running.XST_SUCCESS otherwise None.
References XCsi2Tx_Config::BaseAddr, XCsi2Tx::Config, XCsi2Tx_Config::FEGenEnabled, XCSI2TX_CCR_OFFSET, XCSI2TX_LINE_COUNT_VC0, XCSI2TX_MAX_VC.
u32 XCsi2Tx_GetLineCountForVC(XCsi2Tx *InstancePtr, u8 VC, u16 *LineCount)
This function gets the Line Count for virtual Channel if Frame End Generation feature is enabled.
InstancePtr is a pointer to the Subsystem instance to be worked on. VC is which Virtual channel to be configured for (0-3). LineCount is pointer to variable to be filled with line count for the Virtual channel XST_NO_FEATURE if Frame End generation is not enabledXST_INVALID_PARAM if any param is invalid e.g. VC is always 0 to 3 and Line Count is 0 to 0xFFFF.XST_SUCCESS otherwise None.
References XCsi2Tx_Config::BaseAddr, XCsi2Tx::Config, XCsi2Tx_Config::FEGenEnabled, XCSI2TX_LINE_COUNT_VC0, XCSI2TX_MAX_VC.