xcsi2tx_intr.c
void XCsi2Tx_IntrEnable(XCsi2Tx *InstancePtr, u32 Mask)
This function will enable the interrupts present in the interrupt mask passed onto the function.
InstancePtr is the XCsi instance to operate on Mask is the interrupt mask which need to be enabled in core None None
References XCsi2Tx_Config::BaseAddr, XCsi2Tx::Config, XCsi2Tx_Config::FEGenEnabled, XCSI2TX_IER_OFFSET, XCSITX_LCSTAT_VC0_IER_MASK, XCSITX_LCSTAT_VC1_IER_MASK, XCSITX_LCSTAT_VC2_IER_MASK, XCSITX_LCSTAT_VC3_IER_MASK.
Referenced by XCsi2Tx_Configure.
void XCsi2Tx_IntrDisable(XCsi2Tx *InstancePtr, u32 Mask)
This function will disable the interrupts present in the interrupt mask passed onto the function.
InstancePtr is the XCsi instance to operate on Mask is the interrupt mask which need to be enabled in core None None
References XCsi2Tx_Config::BaseAddr, XCsi2Tx::Config, XCsi2Tx_Config::FEGenEnabled, XCSI2TX_IER_OFFSET, XCSITX_LCSTAT_VC0_IER_MASK, XCSITX_LCSTAT_VC1_IER_MASK, XCSITX_LCSTAT_VC2_IER_MASK, XCSITX_LCSTAT_VC3_IER_MASK.
u32 XCsi2Tx_GetIntrEnable(XCsi2Tx *InstancePtr)
This function will get the interrupt mask set (enabled) in the CSI2 Tx core.
InstancePtr is the XCsi instance to operate on Interrupt Mask with bits set for corresponding interrupt in Interrupt enable register None
References XCsi2Tx_Config::BaseAddr, XCsi2Tx::Config, XCSI2TX_IER_OFFSET.
Referenced by XCsi2Tx_Configure.
u32 XCsi2Tx_GetIntrStatus(XCsi2Tx *InstancePtr)
This function will get the list of interrupts pending in the Interrupt Status Register of the CSI2 Tx core.
InstancePtr is the XCsi instance to operate on Interrupt Mask with bits set for corresponding interrupt in Interrupt Status register None
References XCsi2Tx_Config::BaseAddr, XCsi2Tx::Config, XCSI2TX_ISR_OFFSET.
Referenced by XCsi2Tx_IntrHandler.
void XCsi2Tx_InterruptClear(XCsi2Tx *InstancePtr, u32 Mask)
This function will clear the interrupts set in the Interrupt Status Register of the CSI2 Tx core.
InstancePtr is the XCsi instance to operate on Mask is Interrupt Mask with bits set for corresponding interrupt to be cleared in the Interrupt Status register None None
References XCsi2Tx_Config::BaseAddr, XCsi2Tx::Config, XCsi2Tx_Config::FEGenEnabled, XCSI2TX_ISR_OFFSET, XCSITX_LCSTAT_VC0_ISR_MASK, XCSITX_LCSTAT_VC1_ISR_MASK, XCSITX_LCSTAT_VC2_ISR_MASK, XCSITX_LCSTAT_VC3_ISR_MASK.
Referenced by XCsi2Tx_IntrHandler.
int XCsi2Tx_SetCallBack(XCsi2Tx *InstancePtr, u32 HandleType, void *Callbackfunc, void *Callbackref)
This routine installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function Type ---------------------------- -------------------------------------------- (XCSI2TX_HANDLER_WRG_LANE) IncorrectLaneCallBack (XCSI2TX_HANDLER_GSPFIFO_FULL) GSPFIFOCallBack (XCSI2TX_HANDLER_ULPS) DPhyUlpsCallBack (XCSI2TX_HANDLER_LINEBUF_FULL) LineBufferCallBack (XCSI2TX_HANDLER_WRG_DATATYPE) WrgDataTypeCallBack (XCSI2TX_HANDLER_UNDERRUN_PIXEL) UnderrunPixelCallBack (XCSI2TX_HANDLER_LCERRVC0) LineCountErrVC0 (XCSI2TX_HANDLER_LCERRVC1) LineCountErrVC1 (XCSI2TX_HANDLER_LCERRVC2) LineCountErrVC2 (XCSI2TX_HANDLER_LCERRVC3) LineCountErrVC3 InstancePtr is the XCsi2Tx instance to operate on HandleType is the type of call back to be registered. Callbackfunc is the pointer to a call back function which is called when a particular event occurs. Callbackref is a void pointer to data to be referenced to by the Callbackfunc XST_SUCCESS when handler is installed.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XCsi2Tx::DPhyUlpsCallBack, XCsi2Tx::DPhyUlpsRef, XCsi2Tx::GSPFIFOCallBack, XCsi2Tx::IncorrectLaneCallBack, XCsi2Tx::IncorrectLaneRef, XCsi2Tx::IsReady, XCsi2Tx::LCErrVC0Ref, XCsi2Tx::LCErrVC1Ref, XCsi2Tx::LCErrVC2Ref, XCsi2Tx::LCErrVC3Ref, XCsi2Tx::LineBufferRef, XCsi2Tx::UnderrunPixelRef.
void XCsi2Tx_IntrHandler(void *InstancePtr)
This function is the interrupt handler for the CSI2 Tx core.
This handler reads the pending interrupt from the Interrupt Status register, determines the source of the interrupts and calls the respective callbacks for the interrupts that are enabled in Interrupt Enable register, and finally clears the interrupts.The application is responsible for connecting this function to the interrupt system. Application beyond this core is also responsible for providing callbacks to handle interrupts and installing the callbacks using XCsi2Tx_SetCallBack() during initialization phase. InstancePtr is a pointer to the XCsi2Tx core instance. None. Interrupt should be enabled to execute interrupt handler.
References XCsi2Tx::Config, XCsi2Tx::DPhyUlpsCallBack, XCsi2Tx::DPhyUlpsRef, XCsi2Tx_Config::FEGenEnabled, XCsi2Tx::GSPFIFOCallBack, XCsi2Tx::IncorrectLaneCallBack, XCsi2Tx::IncorrectLaneRef, XCsi2Tx::IsReady, XCsi2Tx::LCErrVC0Ref, XCsi2Tx::LCErrVC1Ref, XCsi2Tx::LCErrVC2Ref, XCsi2Tx::LCErrVC3Ref, XCsi2Tx::LineBufferRef, XCsi2Tx::UnderrunPixelRef, XCsi2Tx_GetIntrStatus, XCsi2Tx_InterruptClear, XCSI2TX_LC_LESS_LINES, XCSI2TX_LC_MORE_LINES, XCSITX_LCSTAT_VC0_ISR_MASK, XCSITX_LCSTAT_VC0_ISR_OFFSET, XCSITX_LCSTAT_VC1_ISR_MASK, XCSITX_LCSTAT_VC1_ISR_OFFSET, XCSITX_LCSTAT_VC2_ISR_MASK, XCSITX_LCSTAT_VC2_ISR_OFFSET, XCSITX_LCSTAT_VC3_ISR_MASK, XCSITX_LCSTAT_VC3_ISR_OFFSET.