xv_demosaic.h
XVDEMOSAIC_IRQ_DONE_MASK
Interrupt mask for frame processing done event.
Referenced by XVDemosaic_InterruptHandler.
XVDEMOSAIC_IRQ_READY_MASK
Interrupt mask for frame ready event.
Referenced by XVDemosaic_InterruptHandler.
XV_demosaic_WriteReg
Writes a value to a Demosaic IP register (bare-metal/RTOS)
Referenced by XV_demosaic_DisableAutoRestart, XV_demosaic_EnableAutoRestart, XV_demosaic_InterruptClear, XV_demosaic_InterruptDisable, XV_demosaic_InterruptEnable, XV_demosaic_InterruptGlobalDisable, XV_demosaic_InterruptGlobalEnable, XV_demosaic_Set_HwReg_bayer_phase, XV_demosaic_Set_HwReg_height, XV_demosaic_Set_HwReg_width, XV_demosaic_Start.
XV_demosaic_ReadReg
Reads a value from a Demosaic IP register (bare-metal/RTOS)
Referenced by XV_demosaic_Get_HwReg_bayer_phase, XV_demosaic_Get_HwReg_height, XV_demosaic_Get_HwReg_width, XV_demosaic_InterruptDisable, XV_demosaic_InterruptEnable, XV_demosaic_InterruptGetEnabled, XV_demosaic_InterruptGetStatus, XV_demosaic_IsDone, XV_demosaic_IsIdle, XV_demosaic_IsReady, XV_demosaic_Start.
XVDEMOSAIC_HandlerType
Handler for processing done event (ap_done)
typedef void(* XVDemosaic_Callback)(void *InstancePtr))(void *InstancePtr)
Callback function type for Demosaic interrupt events.
int XV_demosaic_Initialize(XV_demosaic *InstancePtr, UINTPTR BaseAddress)
Initializes a Demosaic instance using the base address (SDT).
This function looks up the configuration for the specified base address and calls the CfgInitialize function to initialize the Demosaic instance. The instance is initialized with the configuration data, including hardware parameters. This version is used in SDT-based builds. InstancePtr Pointer to the XV_demosaic instance to initialize. BaseAddress The base address of the Demosaic instance. XST_SUCCESS if initialization is successful, XST_DEVICE_NOT_FOUND if the device configuration cannot be found. This function is used in SDT builds. The instance must be properly allocated before calling this function.
References XV_demosaic_Config::BaseAddress, XV_demosaic::IsReady, XV_demosaic_CfgInitialize, XV_demosaic_LookupConfig.
XV_demosaic_Config* XV_demosaic_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the base address (SDT).
This function searches the configuration table for a Demosaic device matching the specified base address. If BaseAddress is 0, it returns the first available configuration. This function is used in SDT-based builds where device lookup is done by base address instead of device ID. BaseAddress The base address of the Demosaic instance, or 0 to return the first available configuration. Pointer to the configuration structure if found, NULL otherwise. This function is used in SDT builds. For non-SDT builds, use the device ID variant of this function.
References XV_demosaic_Config::Name.
Referenced by driverInit, XV_demosaic_Initialize.
int XV_demosaic_CfgInitialize(XV_demosaic *InstancePtr, XV_demosaic_Config *ConfigPtr, UINTPTR EffectiveAddr)
Initializes the Demosaic IP instance.
This function initializes the Demosaic instance by copying the configuration data and setting the effective base address for register access. It marks the instance as ready after successful initialization. InstancePtr Pointer to the XV_demosaic instance to initialize. ConfigPtr Pointer to the configuration structure containing IP parameters. EffectiveAddr The effective base address for the IP registers. XST_SUCCESS on successful initialization. This function is used in bare-metal and RTOS environments (not Linux).
References XV_demosaic_Config::BaseAddress, XV_demosaic::Config, XV_demosaic::IsReady.
Referenced by driverInit, XV_demosaic_Initialize.
void XV_demosaic_Start(XV_demosaic *InstancePtr)
Starts the Demosaic IP core.
This function triggers the Demosaic IP to start processing by setting the AP_START bit in the control register while preserving the auto-restart bit. InstancePtr Pointer to the XV_demosaic instance. None The instance must be initialized and ready before calling this function.
References XV_demosaic_Config::BaseAddress, XV_demosaic::Config, XV_demosaic::IsReady, XV_DEMOSAIC_CTRL_ADDR_AP_CTRL, XV_demosaic_ReadReg, XV_demosaic_WriteReg.
Referenced by videoIpConfig.
u32 XV_demosaic_IsDone(XV_demosaic *InstancePtr)
Checks if the Demosaic IP has completed processing.
This function reads the control register and checks the AP_DONE bit to determine if the IP core has finished processing the current frame. InstancePtr Pointer to the XV_demosaic instance. 1 if processing is done, 0 otherwise. None
References XV_demosaic_Config::BaseAddress, XV_demosaic::Config, XV_demosaic::IsReady, XV_DEMOSAIC_CTRL_ADDR_AP_CTRL, XV_demosaic_ReadReg.
u32 XV_demosaic_IsIdle(XV_demosaic *InstancePtr)
Checks if the Demosaic IP is idle.
This function reads the control register and checks the AP_IDLE bit to determine if the IP core is in idle state (not processing). InstancePtr Pointer to the XV_demosaic instance. 1 if the IP is idle, 0 otherwise. None
References XV_demosaic_Config::BaseAddress, XV_demosaic::Config, XV_demosaic::IsReady, XV_DEMOSAIC_CTRL_ADDR_AP_CTRL, XV_demosaic_ReadReg.
u32 XV_demosaic_IsReady(XV_demosaic *InstancePtr)
Checks if the Demosaic IP is ready for new input.
This function checks the AP_START bit to determine if the IP core is ready to accept a new frame for processing. The IP is ready when the AP_START bit is not set. InstancePtr Pointer to the XV_demosaic instance. 1 if the IP is ready for next input, 0 otherwise. None
References XV_demosaic_Config::BaseAddress, XV_demosaic::Config, XV_demosaic::IsReady, XV_DEMOSAIC_CTRL_ADDR_AP_CTRL, XV_demosaic_ReadReg.
void XV_demosaic_EnableAutoRestart(XV_demosaic *InstancePtr)
Enables auto-restart mode for the Demosaic IP.
This function enables the auto-restart feature, which causes the IP to automatically restart processing after completing each frame without requiring explicit start commands. InstancePtr Pointer to the XV_demosaic instance. None Auto-restart is useful for continuous video stream processing.
References XV_demosaic_Config::BaseAddress, XV_demosaic::Config, XV_demosaic::IsReady, XV_DEMOSAIC_CTRL_ADDR_AP_CTRL, XV_demosaic_WriteReg.
Referenced by videoIpConfig.
void XV_demosaic_DisableAutoRestart(XV_demosaic *InstancePtr)
Disables auto-restart mode for the Demosaic IP.
This function disables the auto-restart feature. The IP will stop after completing each frame and require an explicit start command for the next frame. InstancePtr Pointer to the XV_demosaic instance. None None
References XV_demosaic_Config::BaseAddress, XV_demosaic::Config, XV_demosaic::IsReady, XV_DEMOSAIC_CTRL_ADDR_AP_CTRL, XV_demosaic_WriteReg.
void XV_demosaic_Set_HwReg_width(XV_demosaic *InstancePtr, u32 Data)
Sets the frame width for the Demosaic IP.
This function configures the active image width in pixels that the Demosaic IP will process. InstancePtr Pointer to the XV_demosaic instance. Data The frame width in pixels. None The width must not exceed the MAX_COLS configured in hardware.
References XV_demosaic_Config::BaseAddress, XV_demosaic::Config, XV_demosaic::IsReady, XV_DEMOSAIC_CTRL_ADDR_HWREG_WIDTH_DATA, XV_demosaic_WriteReg.
Referenced by videoIpConfig.
u32 XV_demosaic_Get_HwReg_width(XV_demosaic *InstancePtr)
Gets the configured frame width from the Demosaic IP.
This function reads the current frame width configuration in pixels from the Demosaic IP hardware register. InstancePtr Pointer to the XV_demosaic instance. The configured frame width in pixels. None
References XV_demosaic_Config::BaseAddress, XV_demosaic::Config, XV_demosaic::IsReady, XV_DEMOSAIC_CTRL_ADDR_HWREG_WIDTH_DATA, XV_demosaic_ReadReg.
void XV_demosaic_Set_HwReg_height(XV_demosaic *InstancePtr, u32 Data)
Sets the frame height for the Demosaic IP.
This function configures the active image height in lines that the Demosaic IP will process. InstancePtr Pointer to the XV_demosaic instance. Data The frame height in lines. None The height must not exceed the MAX_ROWS configured in hardware.
References XV_demosaic_Config::BaseAddress, XV_demosaic::Config, XV_demosaic::IsReady, XV_DEMOSAIC_CTRL_ADDR_HWREG_HEIGHT_DATA, XV_demosaic_WriteReg.
Referenced by videoIpConfig.
u32 XV_demosaic_Get_HwReg_height(XV_demosaic *InstancePtr)
Gets the configured frame height from the Demosaic IP.
This function reads the current frame height configuration in lines from the Demosaic IP hardware register. InstancePtr Pointer to the XV_demosaic instance. The configured frame height in lines. None
References XV_demosaic_Config::BaseAddress, XV_demosaic::Config, XV_demosaic::IsReady, XV_DEMOSAIC_CTRL_ADDR_HWREG_HEIGHT_DATA, XV_demosaic_ReadReg.
void XV_demosaic_Set_HwReg_bayer_phase(XV_demosaic *InstancePtr, u32 Data)
Sets the Bayer pattern phase for the Demosaic IP.
This function configures the starting phase of the Bayer color filter array pattern. The phase determines which color (R, G, or B) is at the top-left pixel position. InstancePtr Pointer to the XV_demosaic instance. Data The Bayer phase value (0-3 representing different RGGB patterns). None Valid Bayer phases are typically: 0=RGGB, 1=GRBG, 2=GBRG, 3=BGGR.
References XV_demosaic_Config::BaseAddress, XV_demosaic::Config, XV_demosaic::IsReady, XV_DEMOSAIC_CTRL_ADDR_HWREG_BAYER_PHASE_DATA, XV_demosaic_WriteReg.
Referenced by videoIpConfig.
u32 XV_demosaic_Get_HwReg_bayer_phase(XV_demosaic *InstancePtr)
Gets the configured Bayer pattern phase from the Demosaic IP.
This function reads the current Bayer phase configuration from the Demosaic IP hardware register. InstancePtr Pointer to the XV_demosaic instance. The configured Bayer phase value (0-3). None
References XV_demosaic_Config::BaseAddress, XV_demosaic::Config, XV_demosaic::IsReady, XV_DEMOSAIC_CTRL_ADDR_HWREG_BAYER_PHASE_DATA, XV_demosaic_ReadReg.
void XV_demosaic_InterruptGlobalEnable(XV_demosaic *InstancePtr)
Enables global interrupts for the Demosaic IP.
This function sets the Global Interrupt Enable (GIE) bit, allowing the IP core to generate interrupt signals to the processor. InstancePtr Pointer to the XV_demosaic instance. None Individual interrupt sources must also be enabled using XV_demosaic_InterruptEnable().
References XV_demosaic_Config::BaseAddress, XV_demosaic::Config, XV_demosaic::IsReady, XV_DEMOSAIC_CTRL_ADDR_GIE, XV_demosaic_WriteReg.
void XV_demosaic_InterruptGlobalDisable(XV_demosaic *InstancePtr)
Disables global interrupts for the Demosaic IP.
This function clears the Global Interrupt Enable (GIE) bit, preventing the IP core from generating interrupt signals to the processor. InstancePtr Pointer to the XV_demosaic instance. None This disables all interrupt generation regardless of individual interrupt enable settings.
References XV_demosaic_Config::BaseAddress, XV_demosaic::Config, XV_demosaic::IsReady, XV_DEMOSAIC_CTRL_ADDR_GIE, XV_demosaic_WriteReg.
void XV_demosaic_InterruptEnable(XV_demosaic *InstancePtr, u32 Mask)
Enables specific interrupt sources for the Demosaic IP.
This function sets bits in the Interrupt Enable Register (IER) to enable specific interrupt sources. Multiple interrupts can be enabled by using a bitwise OR of interrupt masks. InstancePtr Pointer to the XV_demosaic instance. Mask Bit mask of interrupts to enable. None Global interrupts must also be enabled using XV_demosaic_InterruptGlobalEnable().
References XV_demosaic_Config::BaseAddress, XV_demosaic::Config, XV_demosaic::IsReady, XV_DEMOSAIC_CTRL_ADDR_IER, XV_demosaic_ReadReg, XV_demosaic_WriteReg.
void XV_demosaic_InterruptDisable(XV_demosaic *InstancePtr, u32 Mask)
Disables specific interrupt sources for the Demosaic IP.
This function clears bits in the Interrupt Enable Register (IER) to disable specific interrupt sources. Multiple interrupts can be disabled by using a bitwise OR of interrupt masks. InstancePtr Pointer to the XV_demosaic instance. Mask Bit mask of interrupts to disable. None None
References XV_demosaic_Config::BaseAddress, XV_demosaic::Config, XV_demosaic::IsReady, XV_DEMOSAIC_CTRL_ADDR_IER, XV_demosaic_ReadReg, XV_demosaic_WriteReg.
void XV_demosaic_InterruptClear(XV_demosaic *InstancePtr, u32 Mask)
Clears pending interrupt flags for the Demosaic IP.
This function clears the specified interrupt status bits by writing to the Interrupt Status Register (ISR). This acknowledges the interrupt and allows new interrupts of the same type to be generated. InstancePtr Pointer to the XV_demosaic instance. Mask Bit mask of interrupt flags to clear. None This should be called in the interrupt handler after servicing the interrupt.
References XV_demosaic_Config::BaseAddress, XV_demosaic::Config, XV_demosaic::IsReady, XV_DEMOSAIC_CTRL_ADDR_ISR, XV_demosaic_WriteReg.
Referenced by XVDemosaic_InterruptHandler.
u32 XV_demosaic_InterruptGetEnabled(XV_demosaic *InstancePtr)
Gets the enabled interrupt sources for the Demosaic IP.
This function reads the Interrupt Enable Register (IER) to determine which interrupt sources are currently enabled. InstancePtr Pointer to the XV_demosaic instance. Bit mask of currently enabled interrupts. None
References XV_demosaic_Config::BaseAddress, XV_demosaic::Config, XV_demosaic::IsReady, XV_DEMOSAIC_CTRL_ADDR_IER, XV_demosaic_ReadReg.
u32 XV_demosaic_InterruptGetStatus(XV_demosaic *InstancePtr)
Gets the current interrupt status for the Demosaic IP.
This function reads the Interrupt Status Register (ISR) to determine which interrupts are currently pending/active. InstancePtr Pointer to the XV_demosaic instance. Bit mask of currently pending/active interrupts. The returned status should be checked and interrupts cleared using XV_demosaic_InterruptClear() in the interrupt handler.
References XV_demosaic_Config::BaseAddress, XV_demosaic::Config, XV_demosaic::IsReady, XV_DEMOSAIC_CTRL_ADDR_ISR, XV_demosaic_ReadReg.
Referenced by XVDemosaic_InterruptHandler.
void XVDemosaic_SetCallback(XV_demosaic *InstancePtr, u32 HandlerType, void *CallbackFunc, void *CallbackRef)
Installs an asynchronous callback function for the given handler type.
This function registers callback functions for different interrupt events. Supported handler types include frame done (XVDEMOSAIC_HANDLER_DONE) and frame ready (XVDEMOSAIC_HANDLER_READY) events. InstancePtr Pointer to the Demosaic IP instance. HandlerType Type of handler (XVDEMOSAIC_HANDLER_DONE or XVDEMOSAIC_HANDLER_READY). CallbackFunc Address of the callback function to be invoked. CallbackRef User data item passed to the callback function when invoked. None Invoking this function for a handler that already has been installed replaces it with the new handler.
References XVDEMOSAIC_HANDLER_DONE, XV_demosaic::FrameDoneCallback, XV_demosaic::CallbackDoneRef, XVDEMOSAIC_HANDLER_READY, XV_demosaic::FrameReadyCallback, XV_demosaic::CallbackReadyRef.
void XVDemosaic_InterruptHandler(XV_demosaic *InstancePtr)
Interrupt handler for the Demosaic IP core.
This handler clears pending interrupts and determines if the source is a frame done or frame ready signal. If the interrupt is valid, it calls the registered callback function for the corresponding event. InstancePtr Pointer to the Demosaic IP instance that just interrupted. None The application is responsible for connecting this function to the interrupt system and providing callbacks using XVDemosaic_SetCallback() during initialization phase.
References XV_demosaic::IsReady, XV_demosaic_InterruptGetStatus, XVDEMOSAIC_IRQ_DONE_MASK, XV_demosaic_InterruptClear, XV_demosaic::FrameDoneCallback, XV_demosaic::CallbackDoneRef, XVDEMOSAIC_IRQ_READY_MASK, XV_demosaic::FrameReadyCallback, XV_demosaic::CallbackReadyRef.