cfupmc
XCfupmc_Config XCfupmc_ConfigTable[][]
static void XCfupmc_ClearIsr(const XCfupmc *InstancePtr, u32 IsrMask)
This function clears CFU ISR.
InstancePtr is a pointer to the XCfupmc instance. IsrMask specifies the bits to be cleared in ISR
static u32 XCfupmc_ReadIsr(const XCfupmc *InstancePtr)
This function reads CFU ISR.
InstancePtr is a pointer to the XCfupmc instance._ 32-bit register value
static u32 XCfupmc_ReadStatus(const XCfupmc *InstancePtr)
This function reads CFU Status.
InstancePtr is a pointer to the XCfupmc instance. 32-bit register value
XCfupmc_Config * XCfupmc_LookupConfig(UINTPTR BaseAddress)
XCfupmc_LookupConfig returns a reference to an XCfupmc_Config structure based on the unique device id, DeviceId.
The return value will refer to an entry in the device configuration table defined in the xcfupmc_g.c file. BaseAddress contains the base address of the device CfgPtr is a reference to a config record in the configuration table (in xcfupmc_g.c) corresponding to DeviceId, or NULL if no match is found.
s32 XCfupmc_CfgInitialize(XCfupmc *InstancePtr, const XCfupmc_Config *CfgPtr, u32 EffectiveAddr)
This function initializes an CFU core.
This function must be called prior to using an CFU driver. InstancePtr is a pointer to the XCfupmc instance. CfgPtr is a reference to a structure containing information about a specific XCfupmc instance. EffectiveAddr is the device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, pass in the physical address instead. XST_SUCCESS if initialization was successful.
References XCfupmc_Config::BaseAddress, XCfupmc::Config, XCfupmc::IsReady.
s32 XCfupmc_SelfTest(const XCfupmc *InstancePtr)
This function runs a self-test on the driver and hardware device.
InstancePtr is a pointer to the XCfupmc instance. XST_SUCCESS if the self-test passed.XST_FAILURE otherwise.
void XCfupmc_MaskRegWrite(const XCfupmc *InstancePtr, u32 Addr, u32 Mask, u32 Val)
This function does CFI register write using MASK register.
InstancePtr is a pointer to the XCfupmc instance. Addr Address of the register to be written Mask Mask of the bit field to be written Val Value of bit field
Referenced by XCfupmc_CfiErrHandler, XCfupmc_ClearIgnoreCfiErr, XCfupmc_ExtErrorHandler, XCfupmc_GlblSeqInit, XCfupmc_SetGlblSigEn.
void XCfupmc_SetGlblSigEn(const XCfupmc *InstancePtr, u8 Enable)
This function enables or disables the global signals.
InstancePtr is a pointer to the XCfupmc instance. Enable pass 0x1 to enable the global signals, 0x0 to disable the global signals.
References XCfupmc_MaskRegWrite.
void XCfupmc_GlblSeqInit(const XCfupmc *InstancePtr)
This function inits the global events to needs to be done before loading the CFI data.
InstancePtr is a pointer to the XCfupmc instance.
References XCfupmc_MaskRegWrite.
void XCfupmc_CfuErrHandler(const XCfupmc *InstancePtr)
This function checks and handles CFU errors.
InstancePtr is a pointer to the XCfupmc instance.
References XCfupmc_ClearCfuIsr.
void XCfupmc_CfiErrHandler(const XCfupmc *InstancePtr)
This function handles CFI errors.
InstancePtr is a pointer to the XCfupmc instance.
References XCfupmc_MaskRegWrite.
void XCfupmc_ExtErrorHandler(const XCfupmc *InstancePtr)
This function is called when bitstream transfer is aborted by user.
InstancePtr is a pointer to the XCfupmc instance.
References XCfupmc_MaskRegWrite.
void XCfupmc_ClearIgnoreCfiErr(const XCfupmc *InstancePtr)
This function clears Ignore CFI ERROR mask in CFU_APB_CFU_CTL.
InstancePtr is a pointer to the XCfupmc instance.
References XCfupmc_MaskRegWrite.
void XCfupmc_ClearCfuIsr(const XCfupmc *InstancePtr)
This function clears CFU ISR.
InstancePtr is a pointer to the XCfupmc instance.
Referenced by XCfupmc_CfuErrHandler.
static u32 XCfupmc_ReadReg(u32 RegOffset)
This macro reads the given register.
RegOffset is the address of the register. The 32-bit value of the register.
static void XCfupmc_WriteReg(u32 RegOffset, u32 Data)
This macro writes the value into the given register.
RegOffset is the address of the register. Data is the 32-bit value to write to the register.
XCFUPMC_HW_H_
XCfupmc_In32
Input operation.
XCfupmc_Out32
Output operation.