
/*******************************************************************
* Copyright (c) 1986-2020 Xilinx, Inc. All rights reserved.
* SPDX-License-Identifier: MIT
*******************************************************************/



#include "xparameters.h"
#include "xcresample.h"

/*
* The configuration table for devices
*/

XCresample_Config XCresample_ConfigTable[] =
{
	{
		XPAR_FMC_SENSOR_INPUT_V_CRESAMPLE_1_DEVICE_ID,
		XPAR_FMC_SENSOR_INPUT_V_CRESAMPLE_1_BASEADDR,
		XPAR_FMC_SENSOR_INPUT_V_CRESAMPLE_1_S_AXIS_VIDEO_FORMAT,
		XPAR_FMC_SENSOR_INPUT_V_CRESAMPLE_1_M_AXIS_VIDEO_FORMAT,
		XPAR_FMC_SENSOR_INPUT_V_CRESAMPLE_1_S_AXI_CLK_FREQ_HZ,
		XPAR_FMC_SENSOR_INPUT_V_CRESAMPLE_1_HAS_INTC_IF,
		XPAR_FMC_SENSOR_INPUT_V_CRESAMPLE_1_HAS_DEBUG,
		XPAR_FMC_SENSOR_INPUT_V_CRESAMPLE_1_MAX_COLS,
		XPAR_FMC_SENSOR_INPUT_V_CRESAMPLE_1_ACTIVE_ROWS,
		XPAR_FMC_SENSOR_INPUT_V_CRESAMPLE_1_ACTIVE_COLS,
		XPAR_FMC_SENSOR_INPUT_V_CRESAMPLE_1_CHROMA_PARITY,
		XPAR_FMC_SENSOR_INPUT_V_CRESAMPLE_1_FIELD_PARITY,
		XPAR_FMC_SENSOR_INPUT_V_CRESAMPLE_1_INTERLACED,
		XPAR_FMC_SENSOR_INPUT_V_CRESAMPLE_1_NUM_H_TAPS,
		XPAR_FMC_SENSOR_INPUT_V_CRESAMPLE_1_NUM_V_TAPS,
		XPAR_FMC_SENSOR_INPUT_V_CRESAMPLE_1_CONVERT_TYPE,
		XPAR_FMC_SENSOR_INPUT_V_CRESAMPLE_1_COEF_WIDTH
	},
	{
		XPAR_HDMI_OUTPUT_V_CRESAMPLE_1_DEVICE_ID,
		XPAR_HDMI_OUTPUT_V_CRESAMPLE_1_BASEADDR,
		XPAR_HDMI_OUTPUT_V_CRESAMPLE_1_S_AXIS_VIDEO_FORMAT,
		XPAR_HDMI_OUTPUT_V_CRESAMPLE_1_M_AXIS_VIDEO_FORMAT,
		XPAR_HDMI_OUTPUT_V_CRESAMPLE_1_S_AXI_CLK_FREQ_HZ,
		XPAR_HDMI_OUTPUT_V_CRESAMPLE_1_HAS_INTC_IF,
		XPAR_HDMI_OUTPUT_V_CRESAMPLE_1_HAS_DEBUG,
		XPAR_HDMI_OUTPUT_V_CRESAMPLE_1_MAX_COLS,
		XPAR_HDMI_OUTPUT_V_CRESAMPLE_1_ACTIVE_ROWS,
		XPAR_HDMI_OUTPUT_V_CRESAMPLE_1_ACTIVE_COLS,
		XPAR_HDMI_OUTPUT_V_CRESAMPLE_1_CHROMA_PARITY,
		XPAR_HDMI_OUTPUT_V_CRESAMPLE_1_FIELD_PARITY,
		XPAR_HDMI_OUTPUT_V_CRESAMPLE_1_INTERLACED,
		XPAR_HDMI_OUTPUT_V_CRESAMPLE_1_NUM_H_TAPS,
		XPAR_HDMI_OUTPUT_V_CRESAMPLE_1_NUM_V_TAPS,
		XPAR_HDMI_OUTPUT_V_CRESAMPLE_1_CONVERT_TYPE,
		XPAR_HDMI_OUTPUT_V_CRESAMPLE_1_COEF_WIDTH
	}
};


