xwdttb_selftest.c
XWT_MAX_SELFTEST_LOOP_COUNT
Loopt count.
Referenced by XWdtTb_SelfTest.
XWT_FW_COUNT
Fist Window count.
Referenced by XWdtTb_SelfTest.
XWT_SW_COUNT
Second window count.
Referenced by XWdtTb_SelfTest.
XWT_GWOR_COUNT
Generic Watchdog Offset Register.
Referenced by XWdtTb_SelfTest.
s32 XWdtTb_SelfTest(const XWdtTb *InstancePtr)
This function runs a self-test on the timebase or window if enabled.
Timebase test verifies that the timebase is incrementing. The watchdog timer is not tested due to the time required to wait for the watchdog timer to expire. The time consumed by this test is dependent on the system clock and the configuration of the dividers in for the input clock of the timebase.Window test verifies that the windowing feature does not generate bad event after enabling window feature with first and second window count. It disables window feature immediately. InstancePtr Pointer to the XWdtTb instance to be worked on. XST_SUCCESS if self-test was successful.XST_WDTTB_TIMER_FAILED if the timebase is not incrementing.XST_FAILURE if self-test was failed.
References XWdtTb_Config::BaseAddr, XWdtTb::Config, XWdtTb::EnableWinMode, XWdtTb::IsReady, XWdtTb_Config::Name, XWdtTb_ReadReg, XWdtTb_WriteReg, XWT_ESR_LBE_MASK, XWT_ESR_LBE_SHIFT, XWT_ESR_OFFSET, XWT_ESR_WEN_MASK, XWT_ESR_WSW_MASK, XWT_FW_COUNT, XWT_FWR_OFFSET, XWT_GWCSR_GWEN_MASK, XWT_GWCSR_OFFSET, XWT_GWOR_COUNT, XWT_GWOR_OFFSET, XWT_GWRR_OFFSET, XWT_MAX_SELFTEST_LOOP_COUNT, XWT_MWR_OFFSET, XWT_SW_COUNT, XWT_SWR_OFFSET, XWT_TBR_OFFSET.
Referenced by GWdtTbExample, GWdtTbSelfTestExample, WdtTbExample, WdtTbIntrExample, WdtTbSelfTestExample, WinWdtIntrExample.