xwdttb_config.c
s32 XWdtTb_DisableWinWdt(XWdtTb *InstancePtr)
Disables window Watchdog Timer feature.
InstancePtr Pointer to the XWdtTb instance to be worked on. XST_SUCESS, if Window WDT feature is disabled.XST_FAILURE, if Window WDT feature is not disabled. Disabling watchdog in first window duration is considered as bade event. It can only be disabled in the second window duration.If fail counter is enabled, watchdog can be disabled only when fail counter is zero.
References XWdtTb_Config::BaseAddr, XWdtTb::Config, XWdtTb::EnableFailCounter, XWdtTb::EnableWinMode, XWdtTb::IsStarted, XWdtTb_ReadReg, XWdtTb_WriteReg, XWT_ESR_FCV_MASK, XWT_ESR_FCV_SHIFT, XWT_ESR_OFFSET, XWT_ESR_WEN_MASK, XWT_ESR_WSW_MASK, XWT_ESR_WSW_SHIFT, XWT_FCR_OFFSET, XWT_FCR_WM_MASK, XWT_ONE, XWT_ZERO.
Referenced by XWdtTb_Stop.
void XWdtTb_EnableTimebaseWdt(XWdtTb *InstancePtr)
Enables timebase Watchdog Timer feature.
InstancePtr Pointer to the XWdtTb instance to be worked on. None. This will start the timebase watchdog timer.
References XWdtTb_Config::BaseAddr, XWdtTb::Config, XWdtTb::IsStarted, XWdtTb_ReadReg, XWdtTb_WriteReg, XWT_CSR0_EWDT1_MASK, XWT_CSR0_WDS_MASK, XWT_CSR0_WRS_MASK, XWT_CSRX_EWDT2_MASK, XWT_TWCSR0_OFFSET, XWT_TWCSR1_OFFSET.
Referenced by XWdtTb_Start.
s32 XWdtTb_DisableTimebaseWdt(XWdtTb *InstancePtr)
Disables timebase Watchdog Timer feature.
InstancePtr Pointer to the XWdtTb instance to be worked on. XST_SUCESS, if Timebase WDT feature is disabled.XST_FAILURE, if Timebase WDT feature is not disabled.
References XWdtTb_Config::BaseAddr, XWdtTb::Config, XWdtTb::IsStarted, XWdtTb_ReadReg, XWdtTb_WriteReg, XWT_CSR0_EWDT1_MASK, XWT_CSRX_EWDT2_MASK, XWT_TWCSR0_OFFSET, XWT_TWCSR1_OFFSET, XWT_ZERO.
Referenced by XWdtTb_Stop.