xwdttb_sinit.c
XWdtTb_Config * XWdtTb_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XWdtTb_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xwdttb.h for the definition of XWdtTb_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XWdtTb_Config::Name, XWdtTb_ConfigTable.
Referenced by GWdtTbExample, GWdtTbSelfTestExample, WdtTbExample, WdtTbIntrExample, WdtTbSelfTestExample, WinWdtIntrExample, XWdtTb_Initialize.