xwdttb.h
XWDTTB_H
by using protection macros
XWdtTb_Event
No bad event.
XWdtTb_Config XWdtTb_ConfigTable[][]
Configuration table.
Referenced by XWdtTb_LookupConfig.
static u32 XWdtTb_GetTbValue(const XWdtTb *InstancePtr)
Returns the current contents of the timebase.
InstancePtr Pointer to the XWdtTb instance to be worked on. The contents of the timebase.
static void XWdtTb_SetRegSpaceAccessMode(const XWdtTb *InstancePtr, u32 AccessMode)
Controls the read/write access to the complete Window WDT register space.
InstancePtr Pointer to the XWdtTb instance to be worked on. AccessMode Specifies a value that needs to be used to provide read/write access to the register space. 1 = Window WDT register space is writable.0 = Window WDT register space is read only. None. When register space is set read only, writes to any register are ignored and does not lead to good or bad event generation.
static u32 XWdtTb_GetRegSpaceAccessMode(const XWdtTb *InstancePtr)
Provides Window WDT register space read only or writable.
InstancePtr Pointer to the XWdtTb instance to be worked on. 1 = Window WDT register space is writable.0 = Window WDT register space is read only.
static u32 XWdtTb_GetLastEvent(const XWdtTb *InstancePtr)
Provides the last bad event and read even after system reset.
InstancePtr Pointer to the XWdtTb instance to be worked on. One of the enumeration value described in XWdtTb_Event. Event can be read after a system reset to determine if the reset was caused by a watchdog timeout.
static u32 XWdtTb_GetFailCounter(const XWdtTb *InstancePtr)
Provides fail count value.
InstancePtr Pointer to the XWdtTb instance to be worked on. Fail counter value. The default value is 5. When fail counter is enabled, it gets incremented for every bad event unless 7 or decrement ed for every good event unless 0. If fail counter is 7 and another bad event happens, reset is generated.When fail counter is disabled, bad event leads to reset.
static u32 XWdtTb_IsResetPending(const XWdtTb *InstancePtr)
States that whether the reset is pending or not when Secondary Sequence Timer(SST) counter has started.
InstancePtr Pointer to the XWdtTb instance to be worked on. 1 = window watchdog reset is pending.0 = window watchdog reset is not pending.
static u32 XWdtTb_GetIntrStatus(const XWdtTb *InstancePtr)
States that whether window watchdog timer has reached at the interrupt programmed point in second window.
InstancePtr Pointer to the XWdtTb instance to be worked on. 1 = when window watchdog timer has reached at the interrupt programmed point in second window.0 = when window watchdog timer did not reach at the interrupt programmed point in second window.
static u32 XWdtTb_IsWrongCfg(const XWdtTb *InstancePtr)
States wrong configuration when second window count is set to zero.
InstancePtr Pointer to the XWdtTb instance to be worked on. 1 = if second window count is set to zero.0 = if second window count is not set to zero.
static void XWdtTb_SetSSTWindow(const XWdtTb *InstancePtr, u32 SST_window_config)
Sets the count value for the Second Sequence Timer window.
InstancePtr Pointer to the XWdtTb instance to be worked on. SST_window_config Specifies the first window count value. None. This function must be called before Window WDT start/enable or after Window WDT stop/disable. For SSTWR window, This option provides additional time to software by delaying the inevitable wwdt_reset assertion/generation by SC count delay
static u32 XWdtTb_ConfigureWDTMode(XWdtTb *InstancePtr, u32 Mode)
Sets configure WDT mode.
InstancePtr Pointer to the XWdtTb instance to be worked on. Mode Specifies the GWDT or WWDT. 0 for GWDT and 1 for WWDT. -XST_SUCESS, if Mode with in the range. -XST_FAILURE,if Mode is out side of range.
static void XWdtTb_StartQASequence(XWdtTb *InstancePtr, u32 Value)
Starts the Q&A mode sequence.
InstancePtr Pointer to the XWdtTb instance to be worked on. Value Specifies the value to be written to token resp register. None
static void XWdtTb_SetFeedbackVal(XWdtTb *InstancePtr, u32 Feedback)
Sets the first feedback value for the TFR .
InstancePtr Pointer to the XWdtTb instance to be worked on. Feedback Feedback to be programmed. None. This function must be called before Window WDT QA start/enable or after Window WDT QA stop/disable.
static u32 XWdtTb_GetFeedbackVal(XWdtTb *InstancePtr)
Reads the Token Feedback Register to return the feedback value.
InstancePtr Pointer to the XWdtTb instance to be worked on. Feedback value programmed in TFR register.
static u32 XWdtTb_GetTokenVal(XWdtTb *InstancePtr)
Reads the ESR Register to return the token value.
InstancePtr Pointer to the XWdtTb instance to be worked on. Token value from ESR.
static void XWdtTb_SetSeedValue(const XWdtTb *InstancePtr, u32 SeedValue)
Sets the seed value for the TFR .
InstancePtr Pointer to the XWdtTb instance to be worked on. SeedValue Used for Input of Seed. None. This function must be called before Window WDT QA start/enable or after Window WDT QA stop/disable.
static u32 XWdtTb_InSecondWindow(XWdtTb *InstancePtr)
Returns true if the watchdog is in second window.
InstancePtr Pointer to the XWdtTb instance to be worked on. TRUE if in second window, otherwise FALSE.
static void XWdtTb_UpdateAnsByte(XWdtTb *InstancePtr, u32 Ans)
Updates the Token Resp Register (TRR) with the answer value provided from user.
InstancePtr Pointer to the XWdtTb instance to be worked on. Ans Value to be programmed. None
static u32 XWdtTb_GetAnsByteCnt(const XWdtTb *InstancePtr)
Reads the Answer byte count from the ESR register.
InstancePtr Pointer to the XWdtTb instance to be worked on. Answer count value
static void XWdtTb_EnableQAMode(XWdtTb *InstancePtr)
Enables the Q&A mode by writing Func_Ctrl register .
InstancePtr Pointer to the XWdtTb instance to be worked on. None.
static void XWdtTb_DisableQAMode(XWdtTb *InstancePtr)
Disables the Q&A mode by writing Func_Ctrl register .
InstancePtr Pointer to the XWdtTb instance to be worked on. None.
s32 XWdtTb_CfgInitialize(XWdtTb *InstancePtr, const XWdtTb_Config *CfgPtr, UINTPTR EffectiveAddr)
Initializes the AXI timebase Watchdog Timer core.
This function must be called prior to using the core. Initialization of the core includes setting up the instance data and ensuring the hardware is in a quiescent state. InstancePtr Pointer to the XWdtTb instance to be worked on. CfgPtr Points to the configuration structure associated with the AXI timebase Watchdog Timer core. EffectiveAddr Base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if initialization was successful.XST_DEVICE_IS_STARTED if the device has already been started.
References XWdtTb_Config::BaseAddr, XWdtTb_Config::Clock, XWdtTb::Config, XWdtTb::EnableFailCounter, XWdtTb::EnableWinMode, XWdtTb_Config::EnableWinWdt, XWdtTb::IsReady, XWdtTb::IsStarted, XWdtTb_Config::MaxCountWidth, XWdtTb_Config::Name, XWdtTb_Config::SstCountWidth, XWdtTb_Initialize, XWdtTb_WriteReg, XWT_GW_WR_MASK, XWT_GW_WR_OFFSET.
Referenced by GWdtTbExample, GWdtTbSelfTestExample, WdtTbExample, WdtTbIntrExample, WdtTbSelfTestExample, WinWdtIntrExample.
s32 XWdtTb_Initialize(XWdtTb *InstancePtr, UINTPTR BaseAddress)
Initializes a specific legacy/window watchdog timer/timebase instance/driver.
This function must be called before other functions of the driver are called. InstancePtr Pointer to the XWdtTb instance to be worked on. BaseAddress contains the base address of the device XST_SUCCESS if initialization was successfulXST_DEVICE_IS_STARTED if the device has already been startedXST_DEVICE_NOT_FOUND if the configuration for device ID/ BaseAddress was not found In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XWdtTb::Config, XWdtTb::EnableFailCounter, XWdtTb::EnableWinMode, XWdtTb::IsReady, XWdtTb::IsStarted, XWdtTb_LookupConfig.
Referenced by XWdtTb_CfgInitialize.
void XWdtTb_Start(XWdtTb *InstancePtr)
Starts the legacy or window watchdog timer.
InstancePtr Pointer to the XWdtTb instance to be worked on. None. For legacy, the timebase is reset to 0 when the Watchdog Timer is started. The timebase is always incrementing.For window, this generates first kick and starts the first window. This step auto clears MWC bit to make address space read only.
References XWdtTb::Config, XWdtTb::EnableWinMode, XWdtTb::IsReady, XWdtTb_Config::Name, XWdtTb_EnableTimebaseWdt.
Referenced by GWdtTbExample, WdtTbExample, WdtTbIntrExample, WinWdtIntrExample.
s32 XWdtTb_Stop(XWdtTb *InstancePtr)
Disables the legacy or window watchdog timer.
It is the caller's responsibility to disconnect the interrupt handler of the watchdog timer from the interrupt source, typically an interrupt controller, and disable the interrupt in the interrupt controller. InstancePtr Pointer to the XWdtTb instance to be worked on. XST_SUCCESS if the legacy/window watchdog was stopped successfully.XST_NO_FEATURE if disable is not supported in legacy watchdog timer.XST_FAILURE if the window watchdog timer cannot be stopped. For legacy, the hardware configuration controls this functionality. If it is not allowed by the hardware the failure will be returned and the timer will continue without interruption.
References XWdtTb::Config, XWdtTb::EnableWinMode, XWdtTb::IsReady, XWdtTb_Config::Name, XWdtTb_DisableTimebaseWdt, XWdtTb_DisableWinWdt.
Referenced by GWdtTbExample, GWdtTbSelfTestExample, WdtTbExample, WdtTbIntrExample, WinWdtIntrExample.
u32 XWdtTb_IsWdtExpired(const XWdtTb *InstancePtr)
Checks if the legacy watchdog timer has expired or window watchdog timer either in second window or not in second window.
This function is used for polled mode in legacy watchdog timer. InstancePtr Pointer to the XWdtTb instance to be worked on. TRUE, if the legacy watchdog timer has expired or window watchdog timer is not in second window.FALSE if the legacy watchdog is not expired or window watchdog is in second window. None.
References XWdtTb_Config::BaseAddr, XWdtTb::Config, XWdtTb::EnableWinMode, XWdtTb::IsReady, XWdtTb_Config::Name, XWdtTb_ReadReg, XWT_CSR0_WDS_MASK, XWT_CSR0_WRS_MASK, XWT_ESR_OFFSET, XWT_ESR_WSW_MASK, XWT_ESR_WSW_SHIFT, XWT_GWCSR_GWS2_MASK, XWT_GWCSR_OFFSET, XWT_TWCSR0_OFFSET.
Referenced by GWdtTbExample, WdtTbExample.
u32 XWdtTb_IsGenericWdtFWExpired(const XWdtTb *InstancePtr)
Checks if the generic watchdog timer has first window expired or not.
InstancePtr Pointer to the XWdtTb instance to be worked on. TRUE, if the generic watchdog timer first window has expired.FALSE if the generic watchdog is not expired first window.
References XWdtTb_Config::BaseAddr, XWdtTb::Config, XWdtTb_ReadReg, XWT_GWCSR_GWS1_MASK, XWT_GWCSR_OFFSET.
Referenced by GWdtTbExample.
void XWdtTb_RestartWdt(const XWdtTb *InstancePtr)
Restarts the legacy or window watchdog timer.
An application needs to call this function periodically to keep the timer from asserting the reset output. InstancePtr Pointer to the XWdtTb instance to be worked on. None.
References XWdtTb_Config::BaseAddr, XWdtTb::Config, XWdtTb::EnableWinMode, XWdtTb::IsReady, XWdtTb_Config::Name, XWdtTb_ReadReg, XWdtTb_WriteReg, XWT_CSR0_WDS_MASK, XWT_CSR0_WRS_MASK, XWT_ESR_OFFSET, XWT_ESR_WSW_MASK, XWT_GWRR_MASK, XWT_GWRR_OFFSET, XWT_TWCSR0_OFFSET.
Referenced by GWdtTbExample, WdtTbExample, WinWdtIntrExample.
XWdtTb_Config * XWdtTb_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XWdtTb_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xwdttb.h for the definition of XWdtTb_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XWdtTb_Config::Name, XWdtTb_ConfigTable.
Referenced by GWdtTbExample, GWdtTbSelfTestExample, WdtTbExample, WdtTbIntrExample, WdtTbSelfTestExample, WinWdtIntrExample, XWdtTb_Initialize.
void XWdtTb_AlwaysEnable(const XWdtTb *InstancePtr)
This function keeps window Watchdog Timer always enabled.
InstancePtr Pointer to the XWdtTb instance to be worked on. None. This must be called before Window WDT is enabled. Once Window WDT is enabled, it can only be disabled by applying reset.
References XWdtTb_Config::BaseAddr, XWdtTb::Config, XWdtTb::EnableWinMode, XWdtTb_ReadReg, XWdtTb_WriteReg, XWT_MWR_AEN_MASK, XWT_MWR_OFFSET.
void XWdtTb_ClearLastEvent(const XWdtTb *InstancePtr)
Clears event(s) that present after system reset.
InstancePtr Pointer to the XWdtTb instance to be worked on. None. Event can be cleared by applying reset to the core followed by writing 111. Writing any other pattern has no effect.
References XWdtTb_Config::BaseAddr, XWdtTb::Config, XWdtTb::EnableWinMode, XWdtTb_ReadReg, XWdtTb_WriteReg, XWT_ESR_LBE_MASK, XWT_ESR_OFFSET, XWT_ESR_WSW_MASK, XWT_ESR_WSW_SHIFT, XWT_ONE.
void XWdtTb_ClearResetPending(const XWdtTb *InstancePtr)
Clears the window watchdog reset pending.
InstancePtr Pointer to the XWdtTb instance to be worked on. None.
References XWdtTb_Config::BaseAddr, XWdtTb::Config, XWdtTb::EnableWinMode, XWdtTb_ReadReg, XWdtTb_WriteReg, XWT_ESR_OFFSET, XWT_ESR_WRP_MASK.
void XWdtTb_IntrClear(const XWdtTb *InstancePtr)
Clears window watchdog timer interrupt (WINT) bit.
InstancePtr Pointer to the XWdtTb instance to be worked on. None.
References XWdtTb_Config::BaseAddr, XWdtTb::Config, XWdtTb::EnableWinMode, XWdtTb_ReadReg, XWdtTb_WriteReg, XWT_ESR_OFFSET, XWT_ESR_WINT_MASK, XWT_ESR_WSW_MASK, XWT_ESR_WSW_SHIFT, XWT_FCR_OFFSET, XWT_FCR_WM_MASK, XWT_ONE.
Referenced by WinWdtIntrExample.
void XWdtTb_SetByteCount(const XWdtTb *InstancePtr, u32 ByteCount)
Sets byte count to determine the interrupt assertion point in the second window configuration.
InstancePtr Pointer to the XWdtTb instance to be worked on. ByteCount Specifies the selected byte count value to be set in the second window configuration. None. This function must be called before Window WDT start/enable or after Window WDT stop/disable.This function must be used along with XWdtTb_SetByteSegment.
References XWdtTb_Config::BaseAddr, XWdtTb::Config, XWdtTb::EnableWinMode, XWdtTb_ReadReg, XWdtTb_WriteReg, XWT_FCR_OFFSET, XWT_FCR_SBC_MASK, XWT_FCR_SBC_SHIFT.
Referenced by WinWdtIntrExample.
u32 XWdtTb_GetByteCount(const XWdtTb *InstancePtr)
Provides byte count value of the selected byte count in the second window configuration.
InstancePtr Pointer to the XWdtTb instance to be worked on. Byte count value of the selected byte count in the second window configuration.
References XWdtTb_Config::BaseAddr, XWdtTb::Config, XWdtTb::EnableWinMode, XWdtTb_ReadReg, XWT_FCR_OFFSET, XWT_FCR_SBC_MASK, XWT_FCR_SBC_SHIFT.
void XWdtTb_SetByteSegment(const XWdtTb *InstancePtr, u32 ByteSegment)
Sets byte segment selection to determine the interrupt assertion point in the second window configuration.
InstancePtr Pointer to the XWdtTb instance to be worked on. ByteSegment Specifies the byte segment selected. 0 = Second window byte 0 selected.1 = Second window byte 1 selected.2 = Second window byte 2 selected.3 = Second window byte 3 selected. None. This function must be called before window WDT start/enable or after Window WDT stop/disable.This function must be used along with XWdtTb_SetByteCount.
References XWdtTb_Config::BaseAddr, XWdtTb::Config, XWdtTb::EnableWinMode, XWdtTb_ReadReg, XWdtTb_WriteReg, XWT_FCR_BSS_MASK, XWT_FCR_BSS_SHIFT, XWT_FCR_OFFSET, XWT_MAX_BYTE_SEGMENT.
Referenced by WinWdtIntrExample.
u32 XWdtTb_GetByteSegment(const XWdtTb *InstancePtr)
Provides byte segment selection in the second window configuration.
InstancePtr Pointer to the XWdtTb instance to be worked on. Byte segment selection value as 0 = Second window byte 0 selected.1 = Second window byte 1 selected.2 = Second window byte 2 selected.3 = Second window byte 3 selected.
References XWdtTb_Config::BaseAddr, XWdtTb::Config, XWdtTb::EnableWinMode, XWdtTb_ReadReg, XWT_FCR_BSS_MASK, XWT_FCR_BSS_SHIFT, XWT_FCR_OFFSET.
void XWdtTb_EnableSst(const XWdtTb *InstancePtr)
Enables Second Sequence Timer(SST) function.
InstancePtr is a pointer to the XWdtTb instance to be worked on. None. This function must be called before Window WDT start/enable or after Window WDT stop/disable.SST provides additional time to software by delaying the inevitable window watchdog reset generation by SST count(SC) delay. This is an independent function and can be enabled in any mode with or without other options.
References XWdtTb_Config::BaseAddr, XWdtTb::Config, XWdtTb::EnableWinMode, XWdtTb_ReadReg, XWdtTb_WriteReg, XWT_FCR_OFFSET, XWT_FCR_SSTE_MASK.
void XWdtTb_DisableSst(const XWdtTb *InstancePtr)
Disables Second Sequence Timer(SST) function.
InstancePtr Pointer to the XWdtTb instance to be worked on. None. This function must be called before Window WDT start/enable or after Window WDT stop/disable.
References XWdtTb_Config::BaseAddr, XWdtTb::Config, XWdtTb::EnableWinMode, XWdtTb_ReadReg, XWdtTb_WriteReg, XWT_FCR_OFFSET, XWT_FCR_SSTE_MASK.
Referenced by WinWdtIntrExample.
void XWdtTb_EnablePsm(const XWdtTb *InstancePtr)
Enables Program Sequence Monitor(PSM) function.
InstancePtr Pointer to the XWdtTb instance to be worked on. None. This function must be called before Window WDT start/enable or after Window WDT stop/disable.PSM enables Task Signature Register comparison. When PSM is enabled, core checks and compares the contents of TSR0 and TSR1 registers at the restart kick/disablement of Window WDT in second window. If they match, no effect. If they do not match, reset is generated either immediately when SST is disabled or after SST count delay when SST is enabled.
References XWdtTb_Config::BaseAddr, XWdtTb::Config, XWdtTb::EnableWinMode, XWdtTb_ReadReg, XWdtTb_WriteReg, XWT_FCR_OFFSET, XWT_FCR_PSME_MASK.
void XWdtTb_DisablePsm(const XWdtTb *InstancePtr)
Disables Program Sequence Monitor (PSM) function.
InstancePtr Pointer to the XWdtTb instance to be worked on. None. This function must be called before Window WDT start/enable or after Window WDT stop/disable.
References XWdtTb_Config::BaseAddr, XWdtTb::Config, XWdtTb::EnableWinMode, XWdtTb_ReadReg, XWdtTb_WriteReg, XWT_FCR_OFFSET, XWT_FCR_PSME_MASK.
Referenced by WinWdtIntrExample.
void XWdtTb_EnableFailCounter(XWdtTb *InstancePtr)
Enables Fail Counter(FC) function.
InstancePtr Pointer to the XWdtTb instance to be worked on. None. This function must be called before Window WDT start/enable or after Window WDT stop/disable.When fail counter is enabled, reset is generated when fail counter is 7 and another bad event happens.When fail counter is disabled, one bad event triggers reset either immediately when SST is disabled or after SST count delay when SST is enabled.
References XWdtTb_Config::BaseAddr, XWdtTb::Config, XWdtTb::EnableFailCounter, XWdtTb::EnableWinMode, XWdtTb_ReadReg, XWdtTb_WriteReg, XWT_FCR_FCE_MASK, XWT_FCR_OFFSET.
void XWdtTb_DisableFailCounter(XWdtTb *InstancePtr)
Disables Fail Counter (FC) function.
InstancePtr Pointer to the XWdtTb instance to be worked on. None. This function must be called before Window WDT start/enable or after Window WDT stop/disable.
References XWdtTb_Config::BaseAddr, XWdtTb::Config, XWdtTb::EnableFailCounter, XWdtTb::EnableWinMode, XWdtTb_ReadReg, XWdtTb_WriteReg, XWT_FCR_FCE_MASK, XWT_FCR_OFFSET.
Referenced by WinWdtIntrExample.
void XWdtTb_EnableExtraProtection(const XWdtTb *InstancePtr)
Provides extra safeguard against unintentional clear of WEN bit.
InstancePtr Pointer to the XWdtTb instance to be worked on. None. This function must be called before Window WDT start/enable or after Window WDT stop/disable.
References XWdtTb_Config::BaseAddr, XWdtTb::Config, XWdtTb::EnableWinMode, XWdtTb_ReadReg, XWdtTb_WriteReg, XWT_FCR_OFFSET, XWT_FCR_WDP_MASK.
void XWdtTb_DisableExtraProtection(const XWdtTb *InstancePtr)
Enables unintentional clear of WEN bit.
InstancePtr Pointer to the XWdtTb instance to be worked on. None. This function must be called before Window WDT start/enable or after Window WDT stop/disable.
References XWdtTb_Config::BaseAddr, XWdtTb::Config, XWdtTb::EnableWinMode, XWdtTb_ReadReg, XWdtTb_WriteReg, XWT_FCR_OFFSET, XWT_FCR_WDP_MASK.
void XWdtTb_SetWindowCount(const XWdtTb *InstancePtr, u32 FirstWinCount, u32 SecondWinCount)
Sets the count value for the first and second window.
InstancePtr Pointer to the XWdtTb instance to be worked on. FirstWinCount Specifies the first window count value. SecondWinCount Specifies the second window count value. None. This function must be called before Window WDT start/enable or after Window WDT stop/disable. For first window, it is recommended that minimum non-zero value should be 15 or more.For second window, minimum value should be sufficiently large to complete required AXILite write transactions at system level.Setting second window count value to zero causes wrong configuration and disables Window WDT feature by clearing WEN bit irrespective of WDP settings.
References XWdtTb_Config::BaseAddr, XWdtTb::Config, XWdtTb::EnableWinMode, XWdtTb_WriteReg, XWT_FWR_OFFSET, XWT_SWR_OFFSET.
Referenced by WinWdtIntrExample.
void XWdtTb_SetGenericWdtWindow(const XWdtTb *InstancePtr, u32 GWOR_config)
Sets the count value for the GWDT_Compare_value_reg0 ,GWDT_Compare_value_reg1 & GWDT_Offset_regs .
InstancePtr Pointer to the XWdtTb instance to be worked on. GWOR_config Specifies the GWDT_Offset_reg count value. None. This function must be called before Window WDT start/enable or after Window WDT stop/disable.
References XWdtTb_Config::BaseAddr, XWdtTb::Config, XWdtTb_WriteReg, XWT_GWOR_OFFSET.
Referenced by GWdtTbExample, WdtTbIntrExample.
void XWdtTb_SetGenericWdtWindowTimeOut(const XWdtTb *InstancePtr, u32 MilliSeconds)
This function sets the count value for the GWDT_Offset_regs .
InstancePtr pointer to the XWdtTb instance to be worked on. MilliSeconds GWDT count value in milliseconds. None. This function must be called before Window WDT start/enable or after Window WDT stop/disable.
References XWdtTb_Config::BaseAddr, XWdtTb_Config::Clock, XWdtTb::Config, XWdtTb_WriteReg, XWT_GWOR_OFFSET, XWT_KILO_HZ, XWT_MAX_TIMEOUT.
u32 XWdtTb_ProgramWDTWidth(const XWdtTb *InstancePtr, u32 width)
Programs the width of Watchdog Timer.
InstancePtr Pointer to the XWdtTb instance to be worked on. width Width of the Watchdog Timer. XST_SUCESS, if window mode is disabled and the width is programmed correctly.XST_FAILURE, if Window mode is enabled or if the width is not in the range of 8-31 This function is applicable only when the window mode is disabled.This function should be called before starting the timer. Valid values for the width are 8-31. Programming any other value returns failure.
References XWdtTb_Config::BaseAddr, XWdtTb::Config, XWdtTb::EnableWinMode, XWdtTb_WriteReg, XWT_END_VALUE, XWT_MWR_OFFSET, XWT_START_VALUE.
u8 XWdtTb_GenAnswer(u8 TokenVal, u8 AnsByteCnt, u8 TokenFdbk)
This routine generates responses based on input token in QA mode.
TokenVal Token value read from TVAL AnsByteCnt Byte on which response is generated TokenFdbk Token feedback value read from TFR Response byte (calculated based on logic given WWDT architecture)
s32 XWdtTb_SelfTest(const XWdtTb *InstancePtr)
This function runs a self-test on the timebase or window if enabled.
Timebase test verifies that the timebase is incrementing. The watchdog timer is not tested due to the time required to wait for the watchdog timer to expire. The time consumed by this test is dependent on the system clock and the configuration of the dividers in for the input clock of the timebase.Window test verifies that the windowing feature does not generate bad event after enabling window feature with first and second window count. It disables window feature immediately. InstancePtr Pointer to the XWdtTb instance to be worked on. XST_SUCCESS if self-test was successful.XST_WDTTB_TIMER_FAILED if the timebase is not incrementing.XST_FAILURE if self-test was failed.
References XWdtTb_Config::BaseAddr, XWdtTb::Config, XWdtTb::EnableWinMode, XWdtTb::IsReady, XWdtTb_Config::Name, XWdtTb_ReadReg, XWdtTb_WriteReg, XWT_ESR_LBE_MASK, XWT_ESR_LBE_SHIFT, XWT_ESR_OFFSET, XWT_ESR_WEN_MASK, XWT_ESR_WSW_MASK, XWT_FW_COUNT, XWT_FWR_OFFSET, XWT_GWCSR_GWEN_MASK, XWT_GWCSR_OFFSET, XWT_GWOR_COUNT, XWT_GWOR_OFFSET, XWT_GWRR_OFFSET, XWT_MAX_SELFTEST_LOOP_COUNT, XWT_MWR_OFFSET, XWT_SW_COUNT, XWT_SWR_OFFSET, XWT_TBR_OFFSET.
Referenced by GWdtTbExample, GWdtTbSelfTestExample, WdtTbExample, WdtTbIntrExample, WdtTbSelfTestExample, WinWdtIntrExample.