xiic_sinit.c
XIic_Config * XIic_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XIic_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xiic.h for the definition of XIic_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XIic_Config::Name, XIic_ConfigTable.
Referenced by IicDynEepromExample, IicEepromExample, IicMultiMasterExample, IicPmbusInterruptSdtExample, IicPmbusPolledExample, IicRepeatedStartExample, IicSelfTestExample, IicSlaveExample, IicTenBitAddrExample, TempSensorExample, XIic_Initialize.
int XIic_Initialize(XIic *InstancePtr, UINTPTR BaseAddress)
Initializes a specific XIic instance.
The initialization entails: Check the device has an entry in the configuration table.Initialize the driver to allow access to the device registers and initialize other subcomponents necessary for the operation of the device.Default options to: 7-bit slave addressingSend messages as a slave deviceRepeated start offGeneral call recognition disabled Clear messageing and error statistics The XIic_Start() function must be called after this function before the device is ready to send and receive data on the IIC bus.Before XIic_Start() is called, the interrupt control must connect the ISR routine to the interrupt handler. This is done by the user, and not XIic_Start() to allow the user to use an interrupt controller of their choice. InstancePtr is a pointer to the XIic instance to be worked on. BaseAddress contains the base address of the device XST_SUCCESS when successfulXST_DEVICE_NOT_FOUND indicates the given device id/BaseAddress isn't foundXST_DEVICE_IS_STARTED indicates the device is started (i.e. interrupts enabled and messaging is possible). Must stop before re-initialization is allowed. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XIic_Config::BaseAddress, XIic_CfgInitialize, XIic_LookupConfig.