xiic_master.c
XIIC_MASTER_INCLUDE
static void SendSlaveAddr(XIic *InstancePtr)
static void RecvMasterData(XIic *InstancePtr)
This function is called when the receive register is full.
The number of bytes received to cause the interrupt is adjustable using the Receive FIFO Depth register. The number of bytes in the register is read in the Receive FIFO occupancy register. Both these registers are zero based values (0-15) such that a value of zero indicates 1 byte.For a Master Receiver to properly signal the end of a message, the data must be read in up to the message length - 1, where control register bits will be set for bus controls to occur on reading of the last byte. InstancePtr is a pointer to the XIic instance to be worked on. None. None.
static void SendMasterData(XIic *InstancePtr)
static int IsBusBusy(XIic *InstancePtr)
int XIic_MasterSend(XIic *InstancePtr, u8 *TxMsgPtr, int ByteCount)
This function sends data as a master on the IIC bus.
If the bus is busy, it will indicate so and then enable an interrupt such that the status handler will be called when the bus is no longer busy. The slave address which has been set with the XIic_SetAddress() function is the address to which the specific data is sent. Sending data on the bus performs a write operation. InstancePtr points to the Iic instance to be worked on. TxMsgPtr points to the data to be transmitted. ByteCount is the number of message bytes to be sent. XST_SUCCESS indicates the message transmission has been initiated.XST_IIC_BUS_BUSY indicates the bus was in use and that the BusNotBusy interrupt is enabled which will update the EventStatus when the bus is no longer busy. None.
References XIic::AddrOfSlave, XIic::BaseAddress, XIic::IsDynamic, XIic::Options, XIic::RecvBufferPtr, XIicStats::RepeatedStarts, XIic::SendBufferPtr, XIic::SendByteCount, XIic::Stats, XIic::TxAddrMode, XIIC_CR_DIR_IS_TX_MASK, XIIC_CR_MSMS_MASK, XIIC_CR_NO_ACK_MASK, XIIC_CR_REG_OFFSET, XIIC_CR_REPEATED_START_MASK, XIIC_INTR_TX_EMPTY_MASK, XIIC_INTR_TX_ERROR_MASK, XIIC_INTR_TX_HALF_MASK, XIic_IntrGlobalDisable, XIic_IntrGlobalEnable, XIIC_MASTER_ROLE, XIic_ReadReg, XIIC_WRITE_OPERATION, XIic_WriteReg.
Referenced by DynEepromWriteData, EepromWriteData, IicMultiMasterExample.
int XIic_MasterRecv(XIic *InstancePtr, u8 *RxMsgPtr, int ByteCount)
This function receives data as a master from a slave device on the IIC bus.
If the bus is busy, it will indicate so and then enable an interrupt such that the status handler will be called when the bus is no longer busy. The slave address which has been set with the XIic_SetAddress() function is the address from which data is received. Receiving data on the bus performs a read operation. InstancePtr is a pointer to the Iic instance to be worked on. RxMsgPtr is a pointer to the data to be transmitted ByteCount is the number of message bytes to be sent XST_SUCCESS indicates the message reception processes has been initiated.XST_IIC_BUS_BUSY indicates the bus was in use and that the BusNotBusy interrupt is enabled which will update the EventStatus when the bus is no longer busy.XST_IIC_GENERAL_CALL_ADDRESS indicates the slave address is set to the the general call address. This is not allowed for Master receive mode.
References XIic::AddrOfSlave, XIic::BaseAddress, IIC_RX_FIFO_DEPTH, XIic::IsDynamic, XIic::Options, XIic::RecvBufferPtr, XIic::RecvByteCount, XIicStats::RepeatedStarts, XIic::SendBufferPtr, XIic::Stats, XIic::TxAddrMode, XIIC_CR_MSMS_MASK, XIIC_CR_REG_OFFSET, XIIC_CR_REPEATED_START_MASK, XIIC_INTR_RX_FULL_MASK, XIIC_INTR_TX_EMPTY_MASK, XIIC_INTR_TX_ERROR_MASK, XIic_IntrGlobalDisable, XIic_IntrGlobalEnable, XIIC_READ_OPERATION, XIic_ReadReg, XIIC_RFD_REG_OFFSET, XIIC_WRITE_OPERATION, XIic_WriteReg.
Referenced by EepromReadData, TempSensorExample.