xiic.h
XII_GENERAL_CALL_OPTION
XII_GENERAL_CALL_OPTION The general call option allows an IIC slave to recognized the general call address. The status handler is called as usual indicating the device has been addressed as a slave with a general call. It is the application's responsibility to perform any special processing for the general call.XII_REPEATED_START_OPTION The repeated start option allows multiple messages to be sent/received on the IIC bus without rearbitrating for the bus. The messages are sent as a series of messages such that the option must be enabled before the 1st message of the series, to prevent an stop condition from being generated on the bus, and disabled before the last message of the series, to allow the stop condition to be generated.XII_SEND_10_BIT_OPTION The send 10 bit option allows 10 bit addresses to be sent on the bus when the device is a master. The device can be configured to respond as to 7 bit addresses even though it may be communicating with other devices that support 10 bit addresses. When this option is not enabled, only 7 bit addresses are sent on the bus.
Referenced by XIic_SetOptions.
XII_REPEATED_START_OPTION
XII_SEND_10_BIT_OPTION
XII_BUS_NOT_BUSY_EVENT
Bus transitioned to not busy.
XII_ARB_LOST_EVENT
Arbitration was lost.
XII_SLAVE_NO_ACK_EVENT
Slave did not ACK (had error)
XII_MASTER_READ_EVENT
Master reading from slave.
XII_MASTER_WRITE_EVENT
Master writing to slave.
XII_GENERAL_CALL_EVENT
General call to all slaves.
XIIC_H
XII_ADDR_TO_SEND_TYPE
Bus address of slave device.
Referenced by IicDynEepromExample, IicEepromExample, IicMultiMasterExample, IicPmbusInterruptSdtExample, IicRepeatedStartExample, TempSensorExample, XIic_SetAddress.
XII_ADDR_TO_RESPOND_TYPE
This device's bus address as slave.
Referenced by IicSlaveExample, IicTenBitAddrExample, XIic_GetAddress, XIic_SetAddress.
typedef void(* XIic_Handler)(void *CallBackRef, int ByteCount))(void *CallBackRef, int ByteCount)
This callback function data type is defined to handle the asynchronous processing of sent and received data of the IIC driver.
The application using this driver is expected to define a handler of this type to support interrupt driven mode. The handlers are called in an interrupt context such that minimal processing should be performed. The handler data type is utilized for both send and receive handlers. CallBackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. Its type is unimportant to the driver component, so it is a void pointer. ByteCount indicates the number of bytes remaining to be sent or received. A value of zero indicates that the requested number of bytes were sent or received.
typedef void(* XIic_StatusHandler)(void *CallBackRef, int StatusEvent))(void *CallBackRef, int StatusEvent)
This callback function data type is defined to handle the asynchronous processing of status events of the IIC driver.
The application using this driver is expected to define a handler of this type to support interrupt driven mode. The handler is called in an interrupt context such that minimal processing should be performed. CallBackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. Its type is unimportant to the driver component, so it is a void pointer. StatusEvent indicates one or more status events that occurred. See the definition of the status events above.
u32 XIic_IsIicBusy(XIic *InstancePtr)
int XIic_Initialize(XIic *InstancePtr, UINTPTR BaseAddress)
Initializes a specific XIic instance.
The initialization entails: Check the device has an entry in the configuration table.Initialize the driver to allow access to the device registers and initialize other subcomponents necessary for the operation of the device.Default options to: 7-bit slave addressingSend messages as a slave deviceRepeated start offGeneral call recognition disabled Clear messageing and error statistics The XIic_Start() function must be called after this function before the device is ready to send and receive data on the IIC bus.Before XIic_Start() is called, the interrupt control must connect the ISR routine to the interrupt handler. This is done by the user, and not XIic_Start() to allow the user to use an interrupt controller of their choice. InstancePtr is a pointer to the XIic instance to be worked on. BaseAddress contains the base address of the device XST_SUCCESS when successfulXST_DEVICE_NOT_FOUND indicates the given device id/BaseAddress isn't foundXST_DEVICE_IS_STARTED indicates the device is started (i.e. interrupts enabled and messaging is possible). Must stop before re-initialization is allowed. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XIic_Config::BaseAddress, XIic_CfgInitialize, XIic_LookupConfig.
XIic_Config * XIic_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XIic_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xiic.h for the definition of XIic_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XIic_Config::Name, XIic_ConfigTable.
Referenced by IicDynEepromExample, IicEepromExample, IicMultiMasterExample, IicPmbusInterruptSdtExample, IicPmbusPolledExample, IicRepeatedStartExample, IicSelfTestExample, IicSlaveExample, IicTenBitAddrExample, TempSensorExample, XIic_Initialize.
int XIic_CfgInitialize(XIic *InstancePtr, XIic_Config *Config, UINTPTR EffectiveAddr)
Initializes a specific XIic instance.
The initialization entails: Initialize the driver to allow access to the device registers and initialize other subcomponents necessary for the operation of the device.Default options to: 7-bit slave addressingSend messages as a slave deviceRepeated start offGeneral call recognition disabled Clear messageing and error statistics The XIic_Start() function must be called after this function before the device is ready to send and receive data on the IIC bus.Before XIic_Start() is called, the interrupt control must connect the ISR routine to the interrupt handler. This is done by the user, and not XIic_Start() to allow the user to use an interrupt controller of their choice. InstancePtr is a pointer to the XIic instance to be worked on. Config is a reference to a structure containing information about a specific IIC device. This function can initialize multiple instance objects with the use of multiple calls giving different Config information on each call. EffectiveAddr is the device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, use Config->BaseAddress for this parameters, passing the physical address instead. XST_SUCCESS when successfulXST_DEVICE_IS_STARTED indicates the device is started (i.e. interrupts enabled and messaging is possible). Must stop before re-initialization is allowed. None.
References XIic_Config::AxiClkFreq, XIic::AxiClkFreq, XIic::BaseAddress, XIic::BNBOnly, XIic_Config::GpOutWidth, XIic::GpOutWidth, XIic_Config::Has10BitAddr, XIic::Has10BitAddr, XIic::IsDynamic, XIic::IsReady, XIic::IsSlaveSetAckOff, XIic::IsStarted, XIic::Options, XIic::RecvBufferPtr, XIic::RecvHandler, XIic::SendBufferPtr, XIic::SendHandler, XIic_Config::SerialClkDelay, XIic::SerialClkDelay, XIic::StatusHandler, XIic_ClearStats, XIic_Reset.
Referenced by IicDynEepromExample, IicEepromExample, IicMultiMasterExample, IicPmbusInterruptSdtExample, IicPmbusPolledExample, IicRepeatedStartExample, IicSelfTestExample, IicSlaveExample, IicTenBitAddrExample, TempSensorExample, XIic_Initialize.
int XIic_Start(XIic *InstancePtr)
This function starts the IIC device and driver by enabling the proper interrupts such that data may be sent and received on the IIC bus.
This function must be called before the functions to send and receive data.Before XIic_Start() is called, the interrupt control must connect the ISR routine to the interrupt handler. This is done by the user, and not XIic_Start() to allow the user to use an interrupt controller of their choice.Start enables: IIC deviceInterrupts: Addressed as slave to allow messages from another masterArbitration Lost to detect Tx arbitration errorsGlobal IIC interrupt InstancePtr is a pointer to the XIic instance to be worked on. XST_SUCCESS always. The device interrupt is connected to the interrupt controller, but no "messaging" interrupts are enabled. Addressed as Slave is enabled to reception of messages when this devices address is written to the bus. The correct messaging interrupts are enabled when sending or receiving via the IicSend() and IicRecv() functions. No action is required by the user to control any IIC interrupts as the driver completely manages all 8 interrupts. Start and Stop control the ability to use the device. Stopping the device completely stops all device interrupts from the processor.
References XIic::BaseAddress, XIic::IsDynamic, XIic::IsReady, XIic::IsStarted, XIIC_CR_ENABLE_DEVICE_MASK, XIIC_CR_REG_OFFSET, XIIC_INTR_AAS_MASK, XIIC_INTR_ARB_LOST_MASK, XIic_IntrGlobalEnable, XIIC_RFD_REG_OFFSET, XIic_WriteIier, XIic_WriteReg.
Referenced by DynEepromReadData, DynEepromWriteData, EepromReadData, EepromWriteData, IicMultiMasterExample, IicPmbusInterruptSdtExample, IicPmbusPolledExample, SlaveReadData, SlaveWriteData, TempSensorExample, TenBitAddrReadData, TenBitAddrWriteData.
int XIic_Stop(XIic *InstancePtr)
This function stops the IIC device and driver such that data is no longer sent or received on the IIC bus.
This function stops the device by disabling interrupts. This function only disables interrupts within the device such that the caller is responsible for disconnecting the interrupt handler of the device from the interrupt source and disabling interrupts at other levels.Due to bus throttling that could hold the bus between messages when using repeated start option, stop will not occur when the device is actively sending or receiving data from the IIC bus or the bus is being throttled by this device, but instead return XST_IIC_BUS_BUSY. InstancePtr is a pointer to the XIic instance to be worked on. XST_SUCCESS indicates all IIC interrupts are disabled. No messages can be received or transmitted until XIic_Start() is called.XST_IIC_BUS_BUSY indicates this device is currently engaged in message traffic and cannot be stopped. None.
References XIic::BaseAddress, XIic::IsStarted, XIIC_CR_MSMS_MASK, XIIC_CR_REG_OFFSET, XIic_IntrGlobalDisable, XIic_IntrGlobalEnable, XIic_ReadReg, XIIC_SR_ADDR_AS_SLAVE_MASK, XIIC_SR_REG_OFFSET.
Referenced by DynEepromReadData, DynEepromWriteData, EepromReadData, EepromWriteData, IicMultiMasterExample, SlaveReadData, SlaveWriteData, TenBitAddrReadData, TenBitAddrWriteData.
void XIic_Reset(XIic *InstancePtr)
Resets the IIC device.
InstancePtr is a pointer to the XIic instance to be worked on. None. The complete IIC core is Reset on giving a software reset to the IIC core. Some previous versions of the core only reset the Interrupt Logic/Registers, please refer to the HW specification for further details about this.
References XIic::BaseAddress, XIic::IsReady, XIIC_RESET_MASK, XIIC_RESETR_OFFSET, XIic_WriteReg.
Referenced by XIic_CfgInitialize, XIic_SelfTest.
int XIic_SetAddress(XIic *InstancePtr, int AddressType, int Address)
This function sets the bus addresses.
The addresses include the device address that the device responds to as a slave, or the slave address to communicate with on the bus. The IIC device hardware is built to allow either 7 or 10 bit slave addressing only at build time rather than at run time. When this device is a master, slave addressing can be selected at run time to match addressing modes for other bus devices.Addresses are represented as hex values with no adjustment for the data direction bit as the software manages address bit placement. Example: For a 7 address written to the device of 1010 011X where X is the transfer direction (send/recv), the address parameter for this function needs to be 01010011 or 0x53 where the correct bit alllignment will be handled for 7 as well as 10 bit devices. This is especially important as the bit placement is not handled the same depending on which options are used such as repeated start. InstancePtr is a pointer to the XIic instance to be worked on. AddressType indicates which address is being modified, the address which this device responds to on the IIC bus as a slave, or the slave address to communicate with when this device is a master. One of the following values must be contained in this argument. XII_ADDR_TO_SEND_TYPE Slave being addressed by a this master XII_ADDR_TO_RESPOND_TYPE Address to respond to as a slave device Address contains the address to be set, 7 bit or 10 bit address. A ten bit address must be within the range: 0 - 1023 and a 7 bit address must be within the range 0 - 127. XST_SUCCESS is returned if the address was successfully set.XST_IIC_NO_10_BIT_ADDRESSING indicates only 7 bit addressing supported.XST_INVALID_PARAM indicates an invalid parameter was specified. Upper bits of 10-bit address is written only when current device is built as a ten bit device.
References XIic::AddrOfSlave, XIic::BaseAddress, XIic::Has10BitAddr, XII_ADDR_TO_RESPOND_TYPE, XII_ADDR_TO_SEND_TYPE, XIIC_ADR_REG_OFFSET, XIIC_TBA_REG_OFFSET, XIic_WriteReg.
Referenced by IicDynEepromExample, IicEepromExample, IicMultiMasterExample, IicPmbusInterruptSdtExample, IicRepeatedStartExample, IicSlaveExample, IicTenBitAddrExample, TempSensorExample.
u16 XIic_GetAddress(XIic *InstancePtr, int AddressType)
This function gets the addresses for the IIC device driver.
The addresses include the device address that the device responds to as a slave, or the slave address to communicate with on the bus. The address returned has the same format whether 7 or 10 bits. InstancePtr is a pointer to the XIic instance to be worked on. AddressType indicates which address, the address which this responds to on the IIC bus as a slave, or the slave address to communicate with when this device is a master. One of the following values must be contained in this argument. XII_ADDR_TO_SEND_TYPE Slave being addressed as a master XII_ADDR_TO_RESPOND_TYPE Slave address to respond to as a slave If neither of the two valid arguments are used, the function returns the address of the slave device The address retrieved. None.
References XIic::AddrOfSlave, XIic::BaseAddress, XIic::Has10BitAddr, XII_ADDR_TO_RESPOND_TYPE, XIIC_ADR_REG_OFFSET, XIic_ReadReg, XIIC_TBA_REG_OFFSET.
int XIic_SetGpOutput(XIic *InstancePtr, u8 OutputValue)
This function sets the contents of the General Purpose Output register for the IIC device driver.
Note that the number of bits in this register is parameterizable in the hardware such that it may not exist. This function checks to ensure that it does exist to prevent bus errors, but does not ensure that the number of bits in the register are sufficient for the value being written (won't cause a bus error). InstancePtr is a pointer to the XIic instance to be worked on. OutputValue contains the value to be written to the register. XST_SUCCESS if the given data is written to the GPO register. XST_NO_FEATURE if the hardware is configured such that this register does not contain any bits to read or write. None.
References XIic::BaseAddress, XIic::GpOutWidth, XIIC_GPO_REG_OFFSET, XIic_WriteReg.
int XIic_GetGpOutput(XIic *InstancePtr, u8 *OutputValuePtr)
This function gets the contents of the General Purpose Output register for the IIC device driver.
Note that the number of bits in this register is parameterizable in the hardware such that it may not exist. This function checks to ensure that it does exist to prevent bus errors. InstancePtr is a pointer to the XIic instance to be worked on. OutputValuePtr contains the value which was read from the register. XST_SUCCESS if the given data is read from the GPO register. XST_NO_FEATURE if the hardware is configured such that this register does not contain any bits to read or write. The OutputValuePtr is also an output as it contains the value read.None.
References XIic::BaseAddress, XIic::GpOutWidth, XIIC_GPO_REG_OFFSET, XIic_ReadReg.
u32 XIic_IsSlave(XIic *InstancePtr)
A function to determine if the device is currently addressed as a slave.
InstancePtr is a pointer to the XIic instance to be worked on. TRUE if the device is addressed as slave. FALSE if the device is NOT addressed as slave. None.
References XIic::BaseAddress, XIic_ReadReg, XIIC_SR_ADDR_AS_SLAVE_MASK, XIIC_SR_REG_OFFSET.
void XIic_SetRecvHandler(XIic *InstancePtr, void *CallBackRef, XIic_Handler FuncPtr)
Sets the receive callback function, the receive handler, which the driver calls when it finishes receiving data.
The number of bytes used to signal when the receive is complete is the number of bytes set in the XIic_Recv function.The handler executes in an interrupt context such that it must minimize the amount of processing performed such as transferring data to a thread context.The number of bytes received is passed to the handler as an argument. InstancePtr is a pointer to the XIic instance to be worked on. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. FuncPtr is the pointer to the callback function. None. The handler is called within interrupt context .
References XIic::IsReady, XIic::RecvCallBackRef, XIic::RecvHandler.
Referenced by IicDynEepromExample, IicEepromExample, IicPmbusInterruptSdtExample, IicRepeatedStartExample, IicSlaveExample, IicTenBitAddrExample, TempSensorExample.
void XIic_SetSendHandler(XIic *InstancePtr, void *CallBackRef, XIic_Handler FuncPtr)
Sets the send callback function, the send handler, which the driver calls when it receives confirmation of sent data.
The handler executes in an interrupt context such that it must minimize the amount of processing performed such as transferring data to a thread context. InstancePtr the pointer to the XIic instance to be worked on. CallBackRef the upper layer callback reference passed back when the callback function is invoked. FuncPtr the pointer to the callback function. None. The handler is called within interrupt context .
References XIic::IsReady, XIic::SendCallBackRef, XIic::SendHandler.
Referenced by IicDynEepromExample, IicEepromExample, IicMultiMasterExample, IicPmbusInterruptSdtExample, IicRepeatedStartExample, IicSlaveExample, IicTenBitAddrExample.
void XIic_SetStatusHandler(XIic *InstancePtr, void *CallBackRef, XIic_StatusHandler FuncPtr)
Sets the status callback function, the status handler, which the driver calls when it encounters conditions which are not data related.
The handler executes in an interrupt context such that it must minimize the amount of processing performed such as transferring data to a thread context. The status events that can be returned are described in xiic.h. InstancePtr points to the XIic instance to be worked on. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. FuncPtr is the pointer to the callback function. None. The handler is called within interrupt context .
References XIic::IsReady, XIic::StatusCallBackRef, XIic::StatusHandler.
Referenced by IicDynEepromExample, IicEepromExample, IicMultiMasterExample, IicPmbusInterruptSdtExample, IicRepeatedStartExample, IicSlaveExample, IicTenBitAddrExample, TempSensorExample.
void XIic_InterruptHandler(void *InstancePtr)
This function is the interrupt handler for the XIic driver.
This function should be connected to the interrupt system.Only one interrupt source is handled for each interrupt allowing higher priority system interrupts quicker response time. InstancePtr is a pointer to the XIic instance to be worked on. None.
References XIicStats::ArbitrationLost, XIic::BaseAddress, XIic::BNBOnly, XIicStats::IicInterrupts, XIic::RecvByteCount, XIicStats::RecvInterrupts, XIic::SendCallBackRef, XIic::SendHandler, XIicStats::SendInterrupts, XIic::Stats, XIicStats::TxErrors, XIIC_INTR_AAS_MASK, XIIC_INTR_ARB_LOST_MASK, XIIC_INTR_BNB_MASK, XIIC_INTR_NAAS_MASK, XIIC_INTR_RX_FULL_MASK, XIIC_INTR_TX_EMPTY_MASK, XIIC_INTR_TX_ERROR_MASK, XIIC_INTR_TX_HALF_MASK, XIic_IsIntrGlobalEnabled, XIic_ReadIier, XIic_ReadIisr, XIic_ReadReg, XIIC_SR_ADDR_AS_SLAVE_MASK, XIIC_SR_REG_OFFSET, XIic_WriteIisr.
Referenced by IicDynEepromExample, IicEepromExample, IicMultiMasterExample, IicPmbusInterruptSdtExample, IicRepeatedStartExample, IicSlaveExample, IicTenBitAddrExample, TempSensorExample.
int XIic_MasterRecv(XIic *InstancePtr, u8 *RxMsgPtr, int ByteCount)
This function receives data as a master from a slave device on the IIC bus.
If the bus is busy, it will indicate so and then enable an interrupt such that the status handler will be called when the bus is no longer busy. The slave address which has been set with the XIic_SetAddress() function is the address from which data is received. Receiving data on the bus performs a read operation. InstancePtr is a pointer to the Iic instance to be worked on. RxMsgPtr is a pointer to the data to be transmitted ByteCount is the number of message bytes to be sent XST_SUCCESS indicates the message reception processes has been initiated.XST_IIC_BUS_BUSY indicates the bus was in use and that the BusNotBusy interrupt is enabled which will update the EventStatus when the bus is no longer busy.XST_IIC_GENERAL_CALL_ADDRESS indicates the slave address is set to the the general call address. This is not allowed for Master receive mode.
References XIic::AddrOfSlave, XIic::BaseAddress, IIC_RX_FIFO_DEPTH, XIic::IsDynamic, XIic::Options, XIic::RecvBufferPtr, XIic::RecvByteCount, XIicStats::RepeatedStarts, XIic::SendBufferPtr, XIic::Stats, XIic::TxAddrMode, XIIC_CR_MSMS_MASK, XIIC_CR_REG_OFFSET, XIIC_CR_REPEATED_START_MASK, XIIC_INTR_RX_FULL_MASK, XIIC_INTR_TX_EMPTY_MASK, XIIC_INTR_TX_ERROR_MASK, XIic_IntrGlobalDisable, XIic_IntrGlobalEnable, XIIC_READ_OPERATION, XIic_ReadReg, XIIC_RFD_REG_OFFSET, XIIC_WRITE_OPERATION, XIic_WriteReg.
Referenced by EepromReadData, TempSensorExample.
int XIic_MasterSend(XIic *InstancePtr, u8 *TxMsgPtr, int ByteCount)
This function sends data as a master on the IIC bus.
If the bus is busy, it will indicate so and then enable an interrupt such that the status handler will be called when the bus is no longer busy. The slave address which has been set with the XIic_SetAddress() function is the address to which the specific data is sent. Sending data on the bus performs a write operation. InstancePtr points to the Iic instance to be worked on. TxMsgPtr points to the data to be transmitted. ByteCount is the number of message bytes to be sent. XST_SUCCESS indicates the message transmission has been initiated.XST_IIC_BUS_BUSY indicates the bus was in use and that the BusNotBusy interrupt is enabled which will update the EventStatus when the bus is no longer busy. None.
References XIic::AddrOfSlave, XIic::BaseAddress, XIic::IsDynamic, XIic::Options, XIic::RecvBufferPtr, XIicStats::RepeatedStarts, XIic::SendBufferPtr, XIic::SendByteCount, XIic::Stats, XIic::TxAddrMode, XIIC_CR_DIR_IS_TX_MASK, XIIC_CR_MSMS_MASK, XIIC_CR_NO_ACK_MASK, XIIC_CR_REG_OFFSET, XIIC_CR_REPEATED_START_MASK, XIIC_INTR_TX_EMPTY_MASK, XIIC_INTR_TX_ERROR_MASK, XIIC_INTR_TX_HALF_MASK, XIic_IntrGlobalDisable, XIic_IntrGlobalEnable, XIIC_MASTER_ROLE, XIic_ReadReg, XIIC_WRITE_OPERATION, XIic_WriteReg.
Referenced by DynEepromWriteData, EepromWriteData, IicMultiMasterExample.
int XIic_DynMasterRecv(XIic *InstancePtr, u8 *RxMsgPtr, u8 ByteCount)
This function receives data as a master from a slave device on the IIC bus.
If the bus is busy, it will indicate so and then enable an interrupt such that the status handler will be called when the bus is no longer busy. The slave address which has been set with the XIic_SetAddress() function is the address from which data is received. Receiving data on the bus performs a read operation. InstancePtr is a pointer to the Iic instance to be worked on. RxMsgPtr is a pointer to the data to be transmitted. ByteCount is the number of message bytes to be sent. - XST_SUCCESS indicates the message reception processes has been initiated. XST_IIC_BUS_BUSY indicates the bus was in use and that the BusNotBusy interrupt is enabled which will update the EventStatus when the bus is no longer busy.XST_IIC_GENERAL_CALL_ADDRESS indicates the slave address is set to the general call address. This is not allowed for Master receive mode. The receive FIFO threshold is a zero based count such that 1 must be subtracted from the desired count to get the correct value. When receiving data it is also necessary to not receive the last byte with the prior bytes because the acknowledge must be setup before the last byte is received.
References XIic::AddrOfSlave, XIic::BaseAddress, IIC_RX_FIFO_DEPTH, XIic::IsDynamic, XIic::RecvBufferPtr, XIic::RecvByteCount, XIicStats::RepeatedStarts, XIic::Stats, XIic::TxAddrMode, XIIC_CR_MSMS_MASK, XIIC_CR_REG_OFFSET, XIIC_CR_REPEATED_START_MASK, XIic_DynSend7BitAddress, XIic_DynSendStop, XIIC_INTR_RX_FULL_MASK, XIIC_INTR_TX_ERROR_MASK, XIic_IntrGlobalDisable, XIic_IntrGlobalEnable, XIIC_READ_OPERATION, XIic_ReadReg, XIIC_RFD_REG_OFFSET, XIic_WriteReg.
Referenced by DynEepromReadData.
int XIic_DynMasterSend(XIic *InstancePtr, u8 *TxMsgPtr, u8 ByteCount)
This function sends data as a Dynamic master on the IIC bus.
If the bus is busy, it will indicate so and then enable an interrupt such that the status handler will be called when the bus is no longer busy. The slave address is sent by using XIic_DynSend7BitAddress(). InstancePtr points to the Iic instance to be worked on. TxMsgPtr points to the data to be transmitted. ByteCount is the number of message bytes to be sent. XST_SUCCESS if successful else XST_FAILURE. None.
References XIic::AddrOfSlave, XIic::BaseAddress, XIic::IsDynamic, XIicStats::RepeatedStarts, XIic::SendBufferPtr, XIic::SendByteCount, XIic::Stats, XIic::TxAddrMode, XIIC_CR_DIR_IS_TX_MASK, XIIC_CR_MSMS_MASK, XIIC_CR_NO_ACK_MASK, XIIC_CR_REG_OFFSET, XIic_DynSend7BitAddress, XIIC_INTR_TX_EMPTY_MASK, XIIC_INTR_TX_ERROR_MASK, XIIC_INTR_TX_HALF_MASK, XIic_IntrGlobalDisable, XIic_IntrGlobalEnable, XIIC_MASTER_ROLE, XIic_ReadReg, XIIC_WRITE_OPERATION, XIic_WriteReg.
Referenced by DynEepromWriteData.
int XIic_DynamicInitialize(XIic *InstancePtr)
void XIic_SlaveInclude(void)
This function includes slave code such that slave events will be processed.
It is necessary to allow slave code to be optional to reduce the size of the driver. This function may be called at any time but must be prior to being selected as a slave on the IIC bus. This function may be called prior to the Cfg_Initialize() function and must be called before any functions in this file are called.None. None.
Referenced by IicSlaveExample, IicTenBitAddrExample.
int XIic_SlaveRecv(XIic *InstancePtr, u8 *RxMsgPtr, int ByteCount)
This function sends data as a slave on the IIC bus and should not be called until an event has occurred that indicates the device has been selected by a master attempting read from the slave (XII_MASTER_READ_EVENT).
If more data is received than specified a No Acknowledge will be sent to signal the Master to stop sending data. Any received data is read to prevent the slave device from throttling the bus. InstancePtr is a pointer to the Iic instance to be worked on. RxMsgPtr is a pointer to the data to be transmitted. ByteCount is the number of message bytes to be sent. XST_SUCCESS indicates the message transmission has been initiated.XST_IIC_NOT_SLAVE indicates the device has not been selected to be a slave on the IIC bus such that data cannot be received.
References XIic::BaseAddress, IIC_RX_FIFO_DEPTH, XIic::RecvBufferPtr, XIic::RecvByteCount, XIic::SendBufferPtr, XIIC_INTR_RX_FULL_MASK, XIic_IntrGlobalDisable, XIic_IntrGlobalEnable, XIic_ReadReg, XIIC_RFD_REG_OFFSET, XIIC_SR_ADDR_AS_SLAVE_MASK, XIIC_SR_REG_OFFSET, XIic_WriteReg.
Referenced by SlaveReadData, TenBitAddrReadData.
int XIic_SlaveSend(XIic *InstancePtr, u8 *TxMsgPtr, int ByteCount)
This function sends data as a slave on the IIC bus and should not be called until an event has occurred that indicates the device has been selected by a master attempting read from the slave (XII_MASTER_READ_EVENT).
InstancePtr is a pointer to the XIic instance to be worked on. TxMsgPtr is a pointer to the data to be transmitted. ByteCount is the number of message bytes to be sent. XST_SUCCESS indicates the message transmission has been initiated.XST_IIC_NOT_SLAVE indicates the device has not been selected to be a slave on the IIC bus such that data cannot be sent. None.
References XIic::BaseAddress, XIic::RecvBufferPtr, XIic::SendBufferPtr, XIic::SendByteCount, XIIC_INTR_TX_EMPTY_MASK, XIIC_INTR_TX_ERROR_MASK, XIIC_INTR_TX_HALF_MASK, XIic_IntrGlobalDisable, XIic_IntrGlobalEnable, XIic_ReadReg, XIIC_SLAVE_ROLE, XIIC_SR_ADDR_AS_SLAVE_MASK, XIIC_SR_REG_OFFSET.
Referenced by SlaveWriteData, TenBitAddrWriteData.
void XIic_GetStats(XIic *InstancePtr, XIicStats *StatsPtr)
Gets a copy of the statistics for an IIC device.
InstancePtr is a pointer to the XIic instance to be worked on. StatsPtr is a pointer to a XIicStats structure which will get a copy of current statistics. None. None.
References XIic::IsReady, XIic::Stats.
void XIic_ClearStats(XIic *InstancePtr)
Clears the statistics for the IIC device by zeroing all counts.
InstancePtr is a pointer to the XIic instance to be worked on. None. None.
References XIic::IsReady, XIic::Stats.
Referenced by XIic_CfgInitialize.
int XIic_SelfTest(XIic *InstancePtr)
Runs a limited self-test on the driver/device.
This test does a read/write test of the Interrupt Registers There is no loopback capabilities for the device such that this test does not send or receive data. InstancePtr is a pointer to the XIic instance to be worked on. XST_SUCCESS if no errors are foundXST_FAILURE if errors are found None.
References XIic::BaseAddress, XIic::IsReady, XIic_IntrGlobalEnable, XIic_IsIntrGlobalEnabled, XIic_ReadIier, XIic_Reset, XIIC_TX_RX_INTERRUPTS, XIic_WriteIier.
Referenced by IicSelfTestExample.
void XIic_SetOptions(XIic *InstancePtr, u32 NewOptions)
This function sets the options for the IIC device driver.
The options control how the device behaves relative to the IIC bus. If an option applies to how messages are sent or received on the IIC bus, it must be set prior to calling functions which send or receive data.To set multiple options, the values must be ORed together. To not change existing options, read/modify/write with the current options using XIic_GetOptions().USAGE EXAMPLE:Read/modify/write to enable repeated start: u8 Options; Options = XIic_GetOptions(&Iic); XIic_SetOptions(&Iic, Options | XII_REPEATED_START_OPTION); Disabling General Call: Options = XIic_GetOptions(&Iic); XIic_SetOptions(&Iic, Options &= ~XII_GENERAL_CALL_OPTION); InstancePtr is a pointer to the XIic instance to be worked on. NewOptions are the options to be set. See xiic.h for a list of the available options. None. Sending or receiving messages with repeated start enabled, and then disabling repeated start, will not take effect until another master transaction is completed. i.e. After using repeated start, the bus will continue to be throttled after repeated start is disabled until a master transaction occurs allowing the IIC to release the bus. Options enabled will have a 1 in its appropriate bit position.
References XIic::BaseAddress, XIic::Options, XII_GENERAL_CALL_OPTION, XIIC_CR_GENERAL_CALL_MASK, XIIC_CR_REG_OFFSET, XIic_IntrGlobalDisable, XIic_IntrGlobalEnable, XIic_ReadReg, XIic_WriteReg.
Referenced by IicTenBitAddrExample.
u32 XIic_GetOptions(XIic *InstancePtr)
This function gets the current options for the IIC device.
Options control the how the device behaves on the IIC bus. See SetOptions for more information on options. InstancePtr is a pointer to the XIic instance to be worked on. The options of the IIC device. See xiic.h for a list of available options. Options enabled will have a 1 in its appropriate bit position.
References XIic::Options.
u32 XIic_SetClk(XIic *InstancePtr, u32 FsclHz)
Sets the serial clock rate for the IIC device.
The device must be idle before setting these device options. The timing register values are calculated according to the input clock frequency and configured scl frequency. For details, please refer the AXI I2C PG and NXP I2C Spec. InstancePtr is a pointer to the XIic instance to be worked on. FsclHz is Clock frequency in Hz(100kHz, 400kHz, 1MHz). XST_SUCCESS if options are successfully set.XST_DEVICE_IS_STARTED if the device is currently transferring data. The transfer must complete or be aborted before setting options.XST_INVALID_PARAM if frequency is unsupported or invalid.
References XIic::AxiClkFreq, XIic::BaseAddress, XIic::IsReady, XIic::SerialClkDelay, XIIC_DTR_REG_OFFSET, XIic_ReadReg.
void XIic_MultiMasterInclude(void)
This function includes multi-master code such that multi-master events are handled properly.
Multi-master events include a loss of arbitration and the bus transitioning from busy to not busy. This function allows the multi-master processing to be optional. This function must be called prior to allowing any multi-master events to occur, such as after the driver is initialized.None. None.
Referenced by IicMultiMasterExample.