xiic_slave_example.c
XIIC_BASEADDRESS
The following constants map to the XPAR parameters created in the xparameters.h file.
They are defined here such that a user can easily change all the needed parameters in one place.
Referenced by IicSlaveExample.
SLAVE_ADDRESS
The following constant defines the address of the IIC device on the IIC bus.
Since the address is only 7 bits, this constant is the address divided by 2.
Referenced by IicSlaveExample.
RECEIVE_COUNT
SEND_COUNT
MAX_DELAY_CNT
Maximum delay count used for timeout handling.
Referenced by SlaveReadData, SlaveWriteData.
XIic IicInstance
u8 WriteBuffer[SEND_COUNT][SEND_COUNT]
The instance of the IIC device.
u8 ReadBuffer[RECEIVE_COUNT][RECEIVE_COUNT]
Write buffer for writing a page.
volatile u8 TransmitComplete
Read buffer for reading a page.
volatile u8 ReceiveComplete
Transmit done flag.
volatile u8 SlaveRead
Receive done flag.
Referenced by SlaveReadData, TenBitAddrReadData.
volatile u8 SlaveWrite
Slave read flag.
Referenced by SlaveWriteData, TenBitAddrWriteData.
int IicSlaveExample(void)
This function writes and reads the data as a slave.
The IIC master on the bus initiates the transfers.XST_SUCCESS if successful else XST_FAILURE. None.
References XIic_Config::BaseAddress, XIic_Config::IntrId, XIic_Config::IntrParent, SLAVE_ADDRESS, SlaveReadData, SlaveWriteData, WriteBuffer, XII_ADDR_TO_RESPOND_TYPE, XIIC_BASEADDRESS, XIic_CfgInitialize, XIic_InterruptHandler, XIic_LookupConfig, XIic_SetAddress, XIic_SetRecvHandler, XIic_SetSendHandler, XIic_SetStatusHandler, XIic_SlaveInclude.
Referenced by main.
int SlaveWriteData(u16 ByteCount)
This function writes a buffer of bytes to the IIC bus when the IIC master initiates a read operation.
ByteCount contains the number of bytes in the buffer to be written. XST_SUCCESS if successful else XST_FAILURE. None.
References XIic::BaseAddress, MAX_DELAY_CNT, SlaveWrite, TransmitComplete, WriteBuffer, XIic_IntrGlobalDisable, XIic_IntrGlobalEnable, XIic_SlaveSend, XIic_Start, XIic_Stop.
Referenced by IicSlaveExample.
int SlaveReadData(u8 *BufferPtr, u16 ByteCount)
This function reads a buffer of bytes when the IIC Master on the bus writes data to the slave device.
BufferPtr contains the address of the data buffer to be filled. ByteCount contains the number of bytes in the buffer to be read. XST_SUCCESS if successful else XST_FAILURE. None
References XIic::BaseAddress, MAX_DELAY_CNT, ReceiveComplete, SlaveRead, XIic_IntrGlobalDisable, XIic_IntrGlobalEnable, XIic_SlaveRecv, XIic_Start, XIic_Stop.
Referenced by IicSlaveExample.
static void StatusHandler(XIic *InstancePtr, int Event)
This Status handler is called asynchronously from an interrupt context and indicates the events that have occurred.
InstancePtr is not used, but contains a pointer to the IIC device driver instance which the handler is being called for. Event indicates whether it is a request for a write or read. None. None.
static void SendHandler(void *CallBackRef, int ByteCount)
This Send handler is called asynchronously from an interrupt context and indicates that data in the specified buffer has been sent.
CallBackRef is a pointer to the IIC device instance. ByteCount is the number of bytes sent. None. None.
static void ReceiveHandler(void *CallBackRef, int ByteCount)
This Receive handler is called asynchronously from an interrupt context and indicates that data in the specified buffer has been received.
CallBackRef is a pointer to the IIC device instance. ByteCount is the number of bytes received. None. None.
int main(void)
Slave write flag.
Main function to call the IIC Slave example.XST_SUCCESS if successful else XST_FAILURE. None.
References IicSlaveExample.