xiic_slave.c
static void AddrAsSlaveHandler(XIic *InstancePtr)
This function is called when the IIC device is Addressed As a Slave (AAS).
This occurs when another device on the bus, a master, has addressed this device to receive a message. InstancePtr is a pointer to the XIic instance to be worked on. None. None.
static void NotAddrAsSlaveHandler(XIic *InstancePtr)
This function is called when the IIC device receives Not Addressed As Slave (NAAS) interrupt which indicates that the master has released the bus implying a data transfer is complete.
InstancePtr is a pointer to the XIic instance to be worked on. None. None.
static void RecvSlaveData(XIic *InstancePtr)
This function handles data received from the IIC bus as a slave.
When the slave expects more than the master has to send, the slave will stall waiting for data.When more data is received than data expected a Nack is done to signal master to stop sending data. The excess data is discarded to prevent bus throttling.The buffer may be full and the master continues to send data if the master and slave have different message lengths. This condition is handled by sending No Ack to the master and reading Rx data until the master stops sending data to prevent but throttling from locking up the bus. To ever receive as a slave again, must know when to renable bus ACKs. NAAS is used to detect when the master is finished sending messages for any mode. InstancePtr is a pointer to the XIic instance to be worked on. None. None.
static void SendSlaveData(XIic *InstancePtr)
This function sends data on the IIC bus as a slave.
When message data has been sent, but the master keeps reading data, the FIFO is filled to prevent bus throttling. There is no way to notify master of this condition. While sending data as a slave a transmit error indicates the master has completed the data transfer.NAAS interrupt signals when repeated start occurred and the msg is finished and BNB signals when the master sent a stop. InstancePtr is a pointer to the XIic instance to be worked on. None. None.
void XIic_SlaveInclude(void)
This function includes slave code such that slave events will be processed.
It is necessary to allow slave code to be optional to reduce the size of the driver. This function may be called at any time but must be prior to being selected as a slave on the IIC bus. This function may be called prior to the Cfg_Initialize() function and must be called before any functions in this file are called.None. None.
Referenced by IicSlaveExample, IicTenBitAddrExample.
int XIic_SlaveSend(XIic *InstancePtr, u8 *TxMsgPtr, int ByteCount)
This function sends data as a slave on the IIC bus and should not be called until an event has occurred that indicates the device has been selected by a master attempting read from the slave (XII_MASTER_READ_EVENT).
InstancePtr is a pointer to the XIic instance to be worked on. TxMsgPtr is a pointer to the data to be transmitted. ByteCount is the number of message bytes to be sent. XST_SUCCESS indicates the message transmission has been initiated.XST_IIC_NOT_SLAVE indicates the device has not been selected to be a slave on the IIC bus such that data cannot be sent. None.
References XIic::BaseAddress, XIic::RecvBufferPtr, XIic::SendBufferPtr, XIic::SendByteCount, XIIC_INTR_TX_EMPTY_MASK, XIIC_INTR_TX_ERROR_MASK, XIIC_INTR_TX_HALF_MASK, XIic_IntrGlobalDisable, XIic_IntrGlobalEnable, XIic_ReadReg, XIIC_SLAVE_ROLE, XIIC_SR_ADDR_AS_SLAVE_MASK, XIIC_SR_REG_OFFSET.
Referenced by SlaveWriteData, TenBitAddrWriteData.
int XIic_SlaveRecv(XIic *InstancePtr, u8 *RxMsgPtr, int ByteCount)
This function sends data as a slave on the IIC bus and should not be called until an event has occurred that indicates the device has been selected by a master attempting read from the slave (XII_MASTER_READ_EVENT).
If more data is received than specified a No Acknowledge will be sent to signal the Master to stop sending data. Any received data is read to prevent the slave device from throttling the bus. InstancePtr is a pointer to the Iic instance to be worked on. RxMsgPtr is a pointer to the data to be transmitted. ByteCount is the number of message bytes to be sent. XST_SUCCESS indicates the message transmission has been initiated.XST_IIC_NOT_SLAVE indicates the device has not been selected to be a slave on the IIC bus such that data cannot be received.
References XIic::BaseAddress, IIC_RX_FIFO_DEPTH, XIic::RecvBufferPtr, XIic::RecvByteCount, XIic::SendBufferPtr, XIIC_INTR_RX_FULL_MASK, XIic_IntrGlobalDisable, XIic_IntrGlobalEnable, XIic_ReadReg, XIIC_RFD_REG_OFFSET, XIIC_SR_ADDR_AS_SLAVE_MASK, XIIC_SR_REG_OFFSET, XIic_WriteReg.
Referenced by SlaveReadData, TenBitAddrReadData.