xiic_low_level_dynamic_eeprom_example.c
IIC_BASE_ADDRESS
The following constants map to the XPAR parameters created in the xparameters.h file.
They are defined here such that a user can easily change all the needed parameters in one place.
Referenced by EepromReadByte, EepromWriteByte, IicLowLevelDynEeprom, main.
EEPROM_TEST_START_ADDRESS
The Starting address in the IIC EEPROM on which this test is performed.
Referenced by EepromReadByte, EepromWriteByte.
EEPROM_ADDRESS
The following constant defines the address of the IIC Slave device on the IIC bus.
Note that since the address is only 7 bits, this constant is the address divided by 2. The 7 bit IIC Slave address of the IIC EEPROM on the ML300/ML310/ML403/ML410/ ML501/ML505/ML507/ML510/SCU200 boards is 0x50. The 7 bit IIC Slave address of the IIC EEPROM on the ML605/SP601/SP605 boards is 0x54. Please refer the User Guide's of the respective boards for further information about the IIC slave address of IIC EEPROM's.
Referenced by IicLowLevelDynEeprom.
PAGE_SIZE
The page size determines how much data should be written at a time.
The ML310/ML300/SCU200/SCU35 board supports a page size of 32 and 16. The write function should be called with this as a maximum byte count.
Referenced by EepromWriteByte, IicLowLevelDynEeprom.
IIC_SLAVE_ADDRESS
MAX_DELAY_CNT
Maximum delay count used for timeout handling.
Referenced by EepromReadByte.
typedef u8 AddressType
The AddressType for ML300/ML310/ML410/ML510/SCU200/SCU35 boards should be u16 as the address pointer in the on board EEPROM is 2 bytes.
The AddressType for ML403/ML501/ML505/ML507/ML605/SP601/SP605 boards should be u8 as the address pointer in the on board EEPROM is 1 bytes.
u8 EepromIicAddr
u8 WriteBuffer[PAGE_SIZE][PAGE_SIZE]
u8 ReadBuffer[PAGE_SIZE][PAGE_SIZE]
Write buffer for writing a page.
int IicLowLevelDynEeprom()
The function uses the low level driver of IIC to read from the IIC EEPROM on the ML300/ML310 board.
The addresses tested starts from 128.XST_SUCCESS if successful else XST_FAILURE. None.
References EEPROM_ADDRESS, EepromIicAddr, EepromReadByte, EepromWriteByte, IIC_BASE_ADDRESS, PAGE_SIZE, WriteBuffer, XIic_ReadReg, XIIC_SR_BUS_BUSY_MASK, XIIC_SR_REG_OFFSET, XIIC_SR_RX_FIFO_EMPTY_MASK, XIIC_SR_TX_FIFO_EMPTY_MASK.
Referenced by main.
u8 EepromReadByte(u8 *BufferPtr, u8 ByteCount)
This function reads a number of bytes from the IIC serial EEPROM into a specified buffer.
BufferPtr contains the address of the data buffer to be filled. ByteCount contains the number of bytes in the buffer to be read. This value is constrained by the page size of the device such that up to 64K may be read in one call. The number of bytes read. A value less than the specified input value indicates an error. None.
References EEPROM_TEST_START_ADDRESS, EepromIicAddr, IIC_BASE_ADDRESS, MAX_DELAY_CNT, XIic_DynRecv, XIic_DynSend, XIic_ReadReg, XIIC_REPEATED_START, XIIC_SR_BUS_BUSY_MASK, XIIC_SR_REG_OFFSET.
Referenced by IicLowLevelDynEeprom, IicLowLevelEeprom, ReadWriteVerify.
u8 EepromWriteByte(u8 *BufferPtr, u8 ByteCount)
This function writes a buffer of bytes to the IIC serial EEPROM.
BufferPtr contains the address of the data to write. ByteCount contains the number of bytes in the buffer to be written. Note that this should not exceed the page size of the EEPROM as noted by the constant PAGE_SIZE. The number of bytes written, a value less than that which was specified as an input indicates an error. one.
References EEPROM_TEST_START_ADDRESS, EepromIicAddr, IIC_BASE_ADDRESS, PAGE_SIZE, WriteBuffer, XIic_DynSend, XIIC_STOP.
Referenced by IicLowLevelDynEeprom, ReadWriteVerify.
int main(void)
Read buffer for reading a page.
Main function to call the low level Dynamic EEPROM example.XST_SUCCESS if successful else XST_FAILURE. None.
References IicLowLevelDynEeprom.