xiic.c
static void XIic_StubStatusHandler(void *CallBackRef, int ErrorCode)
static void XIic_StubHandler(void *CallBackRef, int ByteCount)
int XIic_CfgInitialize(XIic *InstancePtr, XIic_Config *Config, UINTPTR EffectiveAddr)
Initializes a specific XIic instance.
The initialization entails: Initialize the driver to allow access to the device registers and initialize other subcomponents necessary for the operation of the device.Default options to: 7-bit slave addressingSend messages as a slave deviceRepeated start offGeneral call recognition disabled Clear messageing and error statistics The XIic_Start() function must be called after this function before the device is ready to send and receive data on the IIC bus.Before XIic_Start() is called, the interrupt control must connect the ISR routine to the interrupt handler. This is done by the user, and not XIic_Start() to allow the user to use an interrupt controller of their choice. InstancePtr is a pointer to the XIic instance to be worked on. Config is a reference to a structure containing information about a specific IIC device. This function can initialize multiple instance objects with the use of multiple calls giving different Config information on each call. EffectiveAddr is the device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, use Config->BaseAddress for this parameters, passing the physical address instead. XST_SUCCESS when successfulXST_DEVICE_IS_STARTED indicates the device is started (i.e. interrupts enabled and messaging is possible). Must stop before re-initialization is allowed. None.
References XIic_Config::AxiClkFreq, XIic::AxiClkFreq, XIic::BaseAddress, XIic::BNBOnly, XIic_Config::GpOutWidth, XIic::GpOutWidth, XIic_Config::Has10BitAddr, XIic::Has10BitAddr, XIic::IsDynamic, XIic::IsReady, XIic::IsSlaveSetAckOff, XIic::IsStarted, XIic::Options, XIic::RecvBufferPtr, XIic::RecvHandler, XIic::SendBufferPtr, XIic::SendHandler, XIic_Config::SerialClkDelay, XIic::SerialClkDelay, XIic::StatusHandler, XIic_ClearStats, XIic_Reset.
Referenced by IicDynEepromExample, IicEepromExample, IicMultiMasterExample, IicPmbusInterruptSdtExample, IicPmbusPolledExample, IicRepeatedStartExample, IicSelfTestExample, IicSlaveExample, IicTenBitAddrExample, TempSensorExample, XIic_Initialize.
int XIic_Start(XIic *InstancePtr)
This function starts the IIC device and driver by enabling the proper interrupts such that data may be sent and received on the IIC bus.
This function must be called before the functions to send and receive data.Before XIic_Start() is called, the interrupt control must connect the ISR routine to the interrupt handler. This is done by the user, and not XIic_Start() to allow the user to use an interrupt controller of their choice.Start enables: IIC deviceInterrupts: Addressed as slave to allow messages from another masterArbitration Lost to detect Tx arbitration errorsGlobal IIC interrupt InstancePtr is a pointer to the XIic instance to be worked on. XST_SUCCESS always. The device interrupt is connected to the interrupt controller, but no "messaging" interrupts are enabled. Addressed as Slave is enabled to reception of messages when this devices address is written to the bus. The correct messaging interrupts are enabled when sending or receiving via the IicSend() and IicRecv() functions. No action is required by the user to control any IIC interrupts as the driver completely manages all 8 interrupts. Start and Stop control the ability to use the device. Stopping the device completely stops all device interrupts from the processor.
References XIic::BaseAddress, XIic::IsDynamic, XIic::IsReady, XIic::IsStarted, XIIC_CR_ENABLE_DEVICE_MASK, XIIC_CR_REG_OFFSET, XIIC_INTR_AAS_MASK, XIIC_INTR_ARB_LOST_MASK, XIic_IntrGlobalEnable, XIIC_RFD_REG_OFFSET, XIic_WriteIier, XIic_WriteReg.
Referenced by DynEepromReadData, DynEepromWriteData, EepromReadData, EepromWriteData, IicMultiMasterExample, IicPmbusInterruptSdtExample, IicPmbusPolledExample, SlaveReadData, SlaveWriteData, TempSensorExample, TenBitAddrReadData, TenBitAddrWriteData.
int XIic_Stop(XIic *InstancePtr)
This function stops the IIC device and driver such that data is no longer sent or received on the IIC bus.
This function stops the device by disabling interrupts. This function only disables interrupts within the device such that the caller is responsible for disconnecting the interrupt handler of the device from the interrupt source and disabling interrupts at other levels.Due to bus throttling that could hold the bus between messages when using repeated start option, stop will not occur when the device is actively sending or receiving data from the IIC bus or the bus is being throttled by this device, but instead return XST_IIC_BUS_BUSY. InstancePtr is a pointer to the XIic instance to be worked on. XST_SUCCESS indicates all IIC interrupts are disabled. No messages can be received or transmitted until XIic_Start() is called.XST_IIC_BUS_BUSY indicates this device is currently engaged in message traffic and cannot be stopped. None.
References XIic::BaseAddress, XIic::IsStarted, XIIC_CR_MSMS_MASK, XIIC_CR_REG_OFFSET, XIic_IntrGlobalDisable, XIic_IntrGlobalEnable, XIic_ReadReg, XIIC_SR_ADDR_AS_SLAVE_MASK, XIIC_SR_REG_OFFSET.
Referenced by DynEepromReadData, DynEepromWriteData, EepromReadData, EepromWriteData, IicMultiMasterExample, SlaveReadData, SlaveWriteData, TenBitAddrReadData, TenBitAddrWriteData.
void XIic_Reset(XIic *InstancePtr)
Resets the IIC device.
InstancePtr is a pointer to the XIic instance to be worked on. None. The complete IIC core is Reset on giving a software reset to the IIC core. Some previous versions of the core only reset the Interrupt Logic/Registers, please refer to the HW specification for further details about this.
References XIic::BaseAddress, XIic::IsReady, XIIC_RESET_MASK, XIIC_RESETR_OFFSET, XIic_WriteReg.
Referenced by XIic_CfgInitialize, XIic_SelfTest.
int XIic_SetAddress(XIic *InstancePtr, int AddressType, int Address)
This function sets the bus addresses.
The addresses include the device address that the device responds to as a slave, or the slave address to communicate with on the bus. The IIC device hardware is built to allow either 7 or 10 bit slave addressing only at build time rather than at run time. When this device is a master, slave addressing can be selected at run time to match addressing modes for other bus devices.Addresses are represented as hex values with no adjustment for the data direction bit as the software manages address bit placement. Example: For a 7 address written to the device of 1010 011X where X is the transfer direction (send/recv), the address parameter for this function needs to be 01010011 or 0x53 where the correct bit alllignment will be handled for 7 as well as 10 bit devices. This is especially important as the bit placement is not handled the same depending on which options are used such as repeated start. InstancePtr is a pointer to the XIic instance to be worked on. AddressType indicates which address is being modified, the address which this device responds to on the IIC bus as a slave, or the slave address to communicate with when this device is a master. One of the following values must be contained in this argument. XII_ADDR_TO_SEND_TYPE Slave being addressed by a this master XII_ADDR_TO_RESPOND_TYPE Address to respond to as a slave device Address contains the address to be set, 7 bit or 10 bit address. A ten bit address must be within the range: 0 - 1023 and a 7 bit address must be within the range 0 - 127. XST_SUCCESS is returned if the address was successfully set.XST_IIC_NO_10_BIT_ADDRESSING indicates only 7 bit addressing supported.XST_INVALID_PARAM indicates an invalid parameter was specified. Upper bits of 10-bit address is written only when current device is built as a ten bit device.
References XIic::AddrOfSlave, XIic::BaseAddress, XIic::Has10BitAddr, XII_ADDR_TO_RESPOND_TYPE, XII_ADDR_TO_SEND_TYPE, XIIC_ADR_REG_OFFSET, XIIC_TBA_REG_OFFSET, XIic_WriteReg.
Referenced by IicDynEepromExample, IicEepromExample, IicMultiMasterExample, IicPmbusInterruptSdtExample, IicRepeatedStartExample, IicSlaveExample, IicTenBitAddrExample, TempSensorExample.
u16 XIic_GetAddress(XIic *InstancePtr, int AddressType)
This function gets the addresses for the IIC device driver.
The addresses include the device address that the device responds to as a slave, or the slave address to communicate with on the bus. The address returned has the same format whether 7 or 10 bits. InstancePtr is a pointer to the XIic instance to be worked on. AddressType indicates which address, the address which this responds to on the IIC bus as a slave, or the slave address to communicate with when this device is a master. One of the following values must be contained in this argument. XII_ADDR_TO_SEND_TYPE Slave being addressed as a master XII_ADDR_TO_RESPOND_TYPE Slave address to respond to as a slave If neither of the two valid arguments are used, the function returns the address of the slave device The address retrieved. None.
References XIic::AddrOfSlave, XIic::BaseAddress, XIic::Has10BitAddr, XII_ADDR_TO_RESPOND_TYPE, XIIC_ADR_REG_OFFSET, XIic_ReadReg, XIIC_TBA_REG_OFFSET.
int XIic_SetGpOutput(XIic *InstancePtr, u8 OutputValue)
This function sets the contents of the General Purpose Output register for the IIC device driver.
Note that the number of bits in this register is parameterizable in the hardware such that it may not exist. This function checks to ensure that it does exist to prevent bus errors, but does not ensure that the number of bits in the register are sufficient for the value being written (won't cause a bus error). InstancePtr is a pointer to the XIic instance to be worked on. OutputValue contains the value to be written to the register. XST_SUCCESS if the given data is written to the GPO register. XST_NO_FEATURE if the hardware is configured such that this register does not contain any bits to read or write. None.
References XIic::BaseAddress, XIic::GpOutWidth, XIIC_GPO_REG_OFFSET, XIic_WriteReg.
int XIic_GetGpOutput(XIic *InstancePtr, u8 *OutputValuePtr)
This function gets the contents of the General Purpose Output register for the IIC device driver.
Note that the number of bits in this register is parameterizable in the hardware such that it may not exist. This function checks to ensure that it does exist to prevent bus errors. InstancePtr is a pointer to the XIic instance to be worked on. OutputValuePtr contains the value which was read from the register. XST_SUCCESS if the given data is read from the GPO register. XST_NO_FEATURE if the hardware is configured such that this register does not contain any bits to read or write. The OutputValuePtr is also an output as it contains the value read.None.
References XIic::BaseAddress, XIic::GpOutWidth, XIIC_GPO_REG_OFFSET, XIic_ReadReg.
u32 XIic_IsSlave(XIic *InstancePtr)
A function to determine if the device is currently addressed as a slave.
InstancePtr is a pointer to the XIic instance to be worked on. TRUE if the device is addressed as slave. FALSE if the device is NOT addressed as slave. None.
References XIic::BaseAddress, XIic_ReadReg, XIIC_SR_ADDR_AS_SLAVE_MASK, XIIC_SR_REG_OFFSET.
void XIic_SetRecvHandler(XIic *InstancePtr, void *CallBackRef, XIic_Handler FuncPtr)
Sets the receive callback function, the receive handler, which the driver calls when it finishes receiving data.
The number of bytes used to signal when the receive is complete is the number of bytes set in the XIic_Recv function.The handler executes in an interrupt context such that it must minimize the amount of processing performed such as transferring data to a thread context.The number of bytes received is passed to the handler as an argument. InstancePtr is a pointer to the XIic instance to be worked on. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. FuncPtr is the pointer to the callback function. None. The handler is called within interrupt context .
References XIic::IsReady, XIic::RecvCallBackRef, XIic::RecvHandler.
Referenced by IicDynEepromExample, IicEepromExample, IicPmbusInterruptSdtExample, IicRepeatedStartExample, IicSlaveExample, IicTenBitAddrExample, TempSensorExample.
void XIic_SetSendHandler(XIic *InstancePtr, void *CallBackRef, XIic_Handler FuncPtr)
Sets the send callback function, the send handler, which the driver calls when it receives confirmation of sent data.
The handler executes in an interrupt context such that it must minimize the amount of processing performed such as transferring data to a thread context. InstancePtr the pointer to the XIic instance to be worked on. CallBackRef the upper layer callback reference passed back when the callback function is invoked. FuncPtr the pointer to the callback function. None. The handler is called within interrupt context .
References XIic::IsReady, XIic::SendCallBackRef, XIic::SendHandler.
Referenced by IicDynEepromExample, IicEepromExample, IicMultiMasterExample, IicPmbusInterruptSdtExample, IicRepeatedStartExample, IicSlaveExample, IicTenBitAddrExample.
void XIic_SetStatusHandler(XIic *InstancePtr, void *CallBackRef, XIic_StatusHandler FuncPtr)
Sets the status callback function, the status handler, which the driver calls when it encounters conditions which are not data related.
The handler executes in an interrupt context such that it must minimize the amount of processing performed such as transferring data to a thread context. The status events that can be returned are described in xiic.h. InstancePtr points to the XIic instance to be worked on. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. FuncPtr is the pointer to the callback function. None. The handler is called within interrupt context .
References XIic::IsReady, XIic::StatusCallBackRef, XIic::StatusHandler.
Referenced by IicDynEepromExample, IicEepromExample, IicMultiMasterExample, IicPmbusInterruptSdtExample, IicRepeatedStartExample, IicSlaveExample, IicTenBitAddrExample, TempSensorExample.