xiic_dynamic_eeprom_example.c
XIIC_BASEADDRESS
The following constants map to the XPAR parameters created in the xparameters.h file.
They are defined here such that a user can easily change all the needed parameters in one place.
Referenced by IicDynEepromExample, main.
EEPROM_ADDRESS
The following constant defines the address of the IIC Slave device on the IIC bus.
Note that since the address is only 7 bits, this constant is the address divided by 2. The 7 bit IIC Slave address of the IIC EEPROM on the ML300/ML310/ML403/ML510/ ML501/ML505/ML507/ML510/SCU200 boards is 0x50. The 7 bit IIC Slave address of the IIC EEPROM on the ML605/SP601/SP605 boards is 0x54. Please refer the User Guide's of the respective boards for further information about the IIC slave address of IIC EEPROM's.
Referenced by IicDynEepromExample.
PAGE_SIZE
The page size determines how much data should be written at a time.
The ML310/ML300/SCU200/SCU35 board supports a page size of 32 and 16. The write function should be called with this as a maximum byte count.
Referenced by IicDynEepromExample.
EEPROM_TEST_START_ADDRESS
The Starting address in the IIC EEPROM on which this test is performed.
Referenced by DynEepromReadData, IicDynEepromExample.
MAX_DELAY_CNT
Maximum delay count used for timeout handling.
Referenced by DynEepromReadData, DynEepromWriteData.
EventMask
Internal IIC event mask.
Referenced by DynEepromReadData.
Event_Value
Internal event value used for IIC event checking.
Referenced by DynEepromReadData.
typedef u8 AddressType
The AddressType for ML300/ML310/ML410/ML510/SCU200/SCU35 boards should be u16 as the address pointer in the on board EEPROM is 2 bytes.
The AddressType for ML403/ML501/ML505/ML507/ML605/SP601/SP605 boards should be u8 as the address pointer in the on board EEPROM is 1 bytes.
XIic IicInstance
u8 WriteBuffer[sizeof(AddressType)+PAGE_SIZE][sizeof(AddressType)+PAGE_SIZE]
The instance of the IIC device.
Write buffer for writing a page.
Referenced by DynEepromWriteData, EepromReadData, EepromWriteByte, EepromWriteData, IicDynEepromExample, IicEepromExample, IicLowLevelDynEeprom, IicMultiMasterExample, IicRepeatedStartExample, IicSlaveExample, IicTenBitAddrExample, ReadWriteVerify, SlaveWriteData, TenBitAddrWriteData.
u8 ReadBuffer[PAGE_SIZE][PAGE_SIZE]
volatile u8 TransmitComplete
Read buffer for reading a page.
Referenced by DynEepromWriteData, EepromWriteData, IicMultiMasterExample, SlaveWriteData, TenBitAddrWriteData.
volatile u8 ReceiveComplete
Flag to check completion of Transmission.
Referenced by DynEepromReadData, EepromReadData, SlaveReadData, TenBitAddrReadData.
u8 EepromIicAddr
Flag to check completion of Reception.
Referenced by EepromReadByte, EepromWriteByte, IicDynEepromExample, IicEepromExample, IicLowLevelDynEeprom, IicLowLevelEeprom.
int IicDynEepromExample(void)
This function writes, reads, and verifies the data to the IIC EEPROM in Dynamic controller mode.
It does the write as a single page write, performs a buffered read.XST_SUCCESS if successful else XST_FAILURE. None.
References XIic_Config::BaseAddress, DynEepromReadData, DynEepromWriteData, EEPROM_ADDRESS, EEPROM_TEST_START_ADDRESS, EepromIicAddr, XIic_Config::IntrId, XIic_Config::IntrParent, PAGE_SIZE, WriteBuffer, XII_ADDR_TO_SEND_TYPE, XIIC_BASEADDRESS, XIic_CfgInitialize, XIic_InterruptHandler, XIic_LookupConfig, XIic_SetAddress, XIic_SetRecvHandler, XIic_SetSendHandler, XIic_SetStatusHandler.
Referenced by main.
int DynEepromWriteData(u16 ByteCount)
This function writes a buffer of data to the IIC serial EEPROM.
ByteCount contains the number of bytes in the buffer to be written. XST_SUCCESS if successful else XST_FAILURE. The Byte count should not exceed the page size of the EEPROM as noted by the constant PAGE_SIZE.
References MAX_DELAY_CNT, XIic::Stats, TransmitComplete, XIicStats::TxErrors, WriteBuffer, XIic_DynMasterSend, XIic_MasterSend, XIic_Start, XIic_Stop.
Referenced by DynEepromReadData, IicDynEepromExample.
int DynEepromReadData(u8 *BufferPtr, u16 ByteCount)
This function reads data from the IIC serial EEPROM into a specified buffer.
BufferPtr contains the address of the data buffer to be filled. ByteCount contains the number of bytes in the buffer to be read. XST_SUCCESS if successful else XST_FAILURE. None.
References DynEepromWriteData, EEPROM_TEST_START_ADDRESS, Event_Value, EventMask, MAX_DELAY_CNT, ReceiveComplete, XIic_DynMasterRecv, XIic_Start, XIic_Stop.
Referenced by IicDynEepromExample.
static void SendHandler(void *CallBackRef, int ByteCount)
This Send handler is called asynchronously from an interrupt context and indicates that data in the specified buffer has been sent.
CallBackRef is a pointer to the IIC device instance. ByteCount is the number of bytes sent. None. None.
static void ReceiveHandler(void *CallBackRef, int ByteCount)
This Receive handler is called asynchronously from an interrupt context and indicates that data in the specified buffer has been received.
CallBackRef is a pointer to the IIC device instance. ByteCount is the number of bytes received. None. None.
static void StatusHandler(XIic *InstancePtr, int Event)
This Status handler is called asynchronously from an interrupt context and indicates the events that have occurred.
InstancePtr is a pointer to the IIC driver instance for which the handler is being called for. Event indicates the condition that has occurred. None. None.
int main(void)
Variable for storing Eeprom IIC address.
Main function to call the Dynamic EEPROM example.XST_SUCCESS if successful else XST_FAILURE. None.
References IicDynEepromExample.