xiic_eeprom_example.c
XIIC_BASEADDRESS
The following constants map to the XPAR parameters created in the xparameters.h file.
They are defined here such that a user can easily change all the needed parameters in one place.
Referenced by IicEepromExample.
EEPROM_ADDRESS
The following constant defines the address of the IIC Slave device on the IIC bus.
Note that since the address is only 7 bits, this constant is the address divided by 2. The 7 bit IIC Slave address of the IIC EEPROM on the ML300/ML310/ML403/ML410/ ML501/ML505/ML507/ML510/SCU200 boards is 0x50. The 7 bit IIC Slave address of the IIC EEPROM on the ML605/SP601/SP605/KC705/ZC702/ZC706/ZCU102/KCU105 boards is 0x54. Please refer the User Guide's of the respective boards for further information about the IIC slave address of IIC EEPROM's.
Referenced by IicEepromExample.
IIC_MUX_ADDRESS
The IIC_MUX_ADDRESS defines the address of the IIC MUX device on the IIC bus.
Note that since the address is only 7 bits, this constant is the address divided by 2. The IIC Slaves on the KC705/ZC702/ZC706 boards are connected to an IIC MUX. IIC_EEPROM_CHANNEL is the Channel number of EEPROM for IIC Mux. On ZC702 is 0x04. The ZCU102 board uses Mux Address 0x74 with EEPROM channel 0x01,the KCU105 board uses Mux Address 0x75 with EEPROM channel 0x07,and the KC705 board uses Mux Address 0x74 with EEPROM channel 0x08. Please refer the User Guide's of the respective boards for further information about the Channel number to use EEPROM.
IIC_EEPROM_CHANNEL
IIC_MUX_ENABLE
This define should be uncommented if there is IIC MUX on the board to which this EEPROM is connected.
The boards that have IIC MUX are KC705/ZC702/ZC706.
PAGE_SIZE
The page size determines how much data should be written at a time.
The ML310/ML300/SCU200/SCU35 board supports a page size of 32 and 16. The write function should be called with this as a maximum byte count.
Referenced by IicEepromExample.
EEPROM_TEST_START_ADDRESS
The Starting address in the IIC EEPROM on which this test is performed.
Referenced by EepromReadData, IicEepromExample.
MAX_DELAY_CNT
Maximum delay count used for timeout handling.
Referenced by EepromReadData, EepromWriteData.
EventMask
Internal IIC event mask.
Referenced by EepromReadData.
Event_Value
Internal event value used for IIC event checking.
Referenced by EepromReadData.
typedef u8 AddressType
The AddressType for ML300/ML310/ML410/ML510/SCU200/SCU35 boards should be u16 as the address pointer in the on board EEPROM is 2 bytes.
The AddressType for ML403/ML501/ML505/ML507/ML605/SP601/SP605/KC705/ZC702 /ZC706 boards should be u8 as the address pointer in the on board EEPROM is 1 bytes.
XIic IicInstance
u8 WriteBuffer[sizeof(AddressType)+PAGE_SIZE][sizeof(AddressType)+PAGE_SIZE]
The instance of the IIC device.
Write buffer for writing a page.
u8 ReadBuffer[PAGE_SIZE][PAGE_SIZE]
volatile u8 TransmitComplete
Read buffer for reading a page.
volatile u8 ReceiveComplete
Flag to check completion of Transmission.
u8 EepromIicAddr
Flag to check completion of Reception.
int IicEepromExample(void)
This function writes, reads, and verifies the data to the IIC EEPROM.
It does the write as a single page write, performs a buffered read.XST_SUCCESS if successful else XST_FAILURE. None.
References XIic_Config::BaseAddress, EEPROM_ADDRESS, EEPROM_TEST_START_ADDRESS, EepromIicAddr, EepromReadData, EepromWriteData, XIic_Config::IntrId, XIic_Config::IntrParent, PAGE_SIZE, WriteBuffer, XII_ADDR_TO_SEND_TYPE, XIIC_BASEADDRESS, XIic_CfgInitialize, XIic_InterruptHandler, XIic_LookupConfig, XIic_SetAddress, XIic_SetRecvHandler, XIic_SetSendHandler, XIic_SetStatusHandler.
Referenced by main.
int EepromWriteData(u16 ByteCount)
This function writes a buffer of data to the IIC serial EEPROM.
ByteCount contains the number of bytes in the buffer to be written. XST_SUCCESS if successful else XST_FAILURE. The Byte count should not exceed the page size of the EEPROM as noted by the constant PAGE_SIZE.
References MAX_DELAY_CNT, XIic::Stats, TransmitComplete, XIicStats::TxErrors, WriteBuffer, XIic_MasterSend, XIic_Start, XIic_Stop.
Referenced by EepromReadData, IicEepromExample.
int EepromReadData(u8 *BufferPtr, u16 ByteCount)
This function reads data from the IIC serial EEPROM into a specified buffer.
BufferPtr contains the address of the data buffer to be filled. ByteCount contains the number of bytes in the buffer to be read. XST_SUCCESS if successful else XST_FAILURE. None.
References EEPROM_TEST_START_ADDRESS, EepromWriteData, Event_Value, EventMask, MAX_DELAY_CNT, ReceiveComplete, WriteBuffer, XIic_MasterRecv, XIic_Start, XIic_Stop.
Referenced by IicEepromExample.
static void SendHandler(void *CallBackRef, int ByteCount)
This Send handler is called asynchronously from an interrupt context and indicates that data in the specified buffer has been sent.
CallBackRef is a pointer to the IIC device instance. ByteCount is the number of bytes sent. None. None.
static void ReceiveHandler(void *CallBackRef, int ByteCount)
This Receive handler is called asynchronously from an interrupt context and indicates that data in the specified buffer has been received.
CallBackRef is a pointer to the IIC device instance. ByteCount is the number of bytes received. None. None.
static void StatusHandler(XIic *InstancePtr, int Event)
This Status handler is called asynchronously from an interrupt context and indicates the events that have occurred.
InstancePtr is a pointer to the IIC driver instance for which the handler is being called for. Event indicates the condition that has occurred. None. None.
int MuxInit(void)
This function initializes the IIC MUX to select EEPROM.
None. XST_SUCCESS if pass, otherwise XST_FAILURE. None.
int main(void)
Variable for storing Eeprom IIC address.
Main function to call the High level EEPROM example.XST_SUCCESS if successful else XST_FAILURE. None.
References IicEepromExample.