xiic_intr.c
void(* XIic_AddrAsSlaveFuncPtr)(XIic *InstancePtr))(XIic *InstancePtr)
void(* XIic_NotAddrAsSlaveFuncPtr)(XIic *InstancePtr))(XIic *InstancePtr)
void(* XIic_RecvSlaveFuncPtr)(XIic *InstancePtr))(XIic *InstancePtr)
void(* XIic_SendSlaveFuncPtr)(XIic *InstancePtr))(XIic *InstancePtr)
void(* XIic_RecvMasterFuncPtr)(XIic *InstancePtr))(XIic *InstancePtr)
void(* XIic_SendMasterFuncPtr)(XIic *InstancePtr))(XIic *InstancePtr)
void(* XIic_ArbLostFuncPtr)(XIic *InstancePtr))(XIic *InstancePtr)
void(* XIic_BusNotBusyFuncPtr)(XIic *InstancePtr))(XIic *InstancePtr)
static void StubFunction(XIic *InstancePtr)
This function is a stub function that is used for the default function for events that are handled optionally only when the appropriate modules are linked in.
Function pointers are used to handle some events to allow some events to be optionally handled. InstancePtr is a pointer to the XIic instance to be worked on.
static void TxErrorHandler(XIic *InstancePtr)
This interrupt occurs four different ways: Two as master and two as slave.
Master: (1) Transmitter (IMPLIES AN ERROR) The slave receiver did not acknowledge properly. (2) Receiver (Implies Tx complete) Interrupt caused by setting TxAck high in the IIC to indicate to the the last byte has been transmitted. Slave: (3) Transmitter (Implies Tx complete) Interrupt caused by master device indicating last byte of the message has been transmitted. (4) Receiver (IMPLIES AN ERROR) Interrupt caused by setting TxAck high in the IIC to indicate Rx IIC had a problem - set by this device and condition already known and interrupt is not enabled. This interrupt is enabled during Master send and receive and disabled when this device knows it is going to send a negative acknowledge (Ack = No).Signals user of Tx error via status callback sending: XII_TX_ERROR_EVENTWhen MasterRecv has no message to send and only receives one byte of data from the salve device, the TxError must be enabled to catch addressing errors, yet there is not opportunity to disable TxError when there is no data to send allowing disabling on last byte. When the slave sends the only byte the NOAck causes a Tx Error. To disregard this as no real error, when there is data in the Receive FIFO/register then the error was not a device address write error, but a NOACK read error - to be ignored. To work with or without FIFO's, the Rx Data interrupt is used to indicate data is in the Rx register. InstancePtr is a pointer to the XIic instance to be worked on. None.
void XIic_InterruptHandler(void *InstancePtr)
This function is the interrupt handler for the XIic driver.
This function should be connected to the interrupt system.Only one interrupt source is handled for each interrupt allowing higher priority system interrupts quicker response time. InstancePtr is a pointer to the XIic instance to be worked on. None.
References XIicStats::ArbitrationLost, XIic::BaseAddress, XIic::BNBOnly, XIicStats::IicInterrupts, XIic::RecvByteCount, XIicStats::RecvInterrupts, XIic::SendCallBackRef, XIic::SendHandler, XIicStats::SendInterrupts, XIic::Stats, XIicStats::TxErrors, XIIC_INTR_AAS_MASK, XIIC_INTR_ARB_LOST_MASK, XIIC_INTR_BNB_MASK, XIIC_INTR_NAAS_MASK, XIIC_INTR_RX_FULL_MASK, XIIC_INTR_TX_EMPTY_MASK, XIIC_INTR_TX_ERROR_MASK, XIIC_INTR_TX_HALF_MASK, XIic_IsIntrGlobalEnabled, XIic_ReadIier, XIic_ReadIisr, XIic_ReadReg, XIIC_SR_ADDR_AS_SLAVE_MASK, XIIC_SR_REG_OFFSET, XIic_WriteIisr.
Referenced by IicDynEepromExample, IicEepromExample, IicMultiMasterExample, IicPmbusInterruptSdtExample, IicRepeatedStartExample, IicSlaveExample, IicTenBitAddrExample, TempSensorExample.
void XIic_TransmitFifoFill(XIic *InstancePtr, int Role)