xiic_l.c
static unsigned RecvData(UINTPTR BaseAddress, u8 *BufferPtr, unsigned ByteCount, u8 Option)
static unsigned SendData(UINTPTR BaseAddress, u8 *BufferPtr, unsigned ByteCount, u8 Option)
static unsigned DynRecvData(UINTPTR BaseAddress, u8 *BufferPtr, u8 ByteCount)
Receive the specified data from the device that has been previously addressed on the IIC bus.
This function assumes the following: The Rx Fifo occupancy depth has been set to its max.Upon entry, the Rx Fifo is empty.The 7 bit address has been sent.The dynamic stop and number of bytes to receive has been written to Tx Fifo. BaseAddress contains the base address of the IIC Device. BufferPtr points to the buffer to hold the data that is received. ByteCount is the number of bytes to be received. The range of this value is greater than 0 and not higher than 255. The number of bytes remaining to be received. This function contains loops that could cause the function not to return if the hardware is not working.
static unsigned DynSendData(UINTPTR BaseAddress, u8 *BufferPtr, u8 ByteCount, u8 Option)
unsigned XIic_Recv(UINTPTR BaseAddress, u8 Address, u8 *BufferPtr, unsigned ByteCount, u8 Option)
Receive data as a master on the IIC bus.
This function receives the data using polled I/O and blocks until the data has been received. It only supports 7 bit addressing mode of operation. This function returns zero if bus is busy. BaseAddress contains the base address of the IIC device. Address contains the 7 bit IIC address of the device to send the specified data to. BufferPtr points to the data to be sent. ByteCount is the number of bytes to be sent. Option indicates whether to hold or free the bus after reception of data, XIIC_STOP = end with STOP condition, XIIC_REPEATED_START = don't end with STOP condition. The number of bytes received. None.
References XIic_ClearIisr, XIIC_CR_DIR_IS_TX_MASK, XIIC_CR_ENABLE_DEVICE_MASK, XIIC_CR_MSMS_MASK, XIIC_CR_NO_ACK_MASK, XIIC_CR_REG_OFFSET, XIIC_CR_REPEATED_START_MASK, XIIC_INTR_ARB_LOST_MASK, XIIC_INTR_BNB_MASK, XIIC_INTR_RX_FULL_MASK, XIIC_INTR_TX_ERROR_MASK, XIIC_READ_OPERATION, XIic_ReadReg, XIIC_RFD_REG_OFFSET, XIic_Send7BitAddress, XIIC_SR_BUS_BUSY_MASK, XIIC_SR_REG_OFFSET, XIic_WaitBusFree, XIic_WriteReg.
Referenced by EepromReadByte, LowLevelTempSensorExample.
unsigned XIic_Send(UINTPTR BaseAddress, u8 Address, u8 *BufferPtr, unsigned ByteCount, u8 Option)
Send data as a master on the IIC bus.
This function sends the data using polled I/O and blocks until the data has been sent. It only supports 7 bit addressing mode of operation. This function returns zero if bus is busy. BaseAddress contains the base address of the IIC device. Address contains the 7 bit IIC address of the device to send the specified data to. BufferPtr points to the data to be sent. ByteCount is the number of bytes to be sent. Option indicates whether to hold or free the bus after transmitting the data. The number of bytes sent. None.
References XIic_ClearIisr, XIIC_CR_DIR_IS_TX_MASK, XIIC_CR_ENABLE_DEVICE_MASK, XIIC_CR_MSMS_MASK, XIIC_CR_REG_OFFSET, XIIC_CR_REPEATED_START_MASK, XIIC_INTR_ARB_LOST_MASK, XIIC_INTR_BNB_MASK, XIIC_INTR_TX_EMPTY_MASK, XIIC_INTR_TX_ERROR_MASK, XIic_ReadReg, XIic_Send7BitAddress, XIIC_SR_ADDR_AS_SLAVE_MASK, XIIC_SR_BUS_BUSY_MASK, XIIC_SR_REG_OFFSET, XIic_WaitBusFree, XIIC_WRITE_OPERATION, XIic_WriteReg.
Referenced by EepromReadByte, EepromWriteByte.
unsigned XIic_DynRecv(UINTPTR BaseAddress, u8 Address, u8 *BufferPtr, u8 ByteCount)
Receive data as a master on the IIC bus.
This function receives the data using polled I/O and blocks until the data has been received. It only supports 7 bit addressing. This function returns zero if bus is busy. BaseAddress contains the base address of the IIC Device. Address contains the 7 bit IIC Device address of the device to send the specified data to. BufferPtr points to the data to be sent. ByteCount is the number of bytes to be sent. This value can't be greater than 255 and needs to be greater than 0. The number of bytes received. Upon entry to this function, the IIC interface needs to be already enabled in the CR register.
References XIic_ClearIisr, XIic_DynSend7BitAddress, XIic_DynSendStop, XIIC_INTR_ARB_LOST_MASK, XIIC_INTR_BNB_MASK, XIIC_INTR_TX_EMPTY_MASK, XIIC_INTR_TX_ERROR_MASK, XIIC_READ_OPERATION, XIic_ReadReg, XIIC_SR_BUS_BUSY_MASK, XIIC_SR_REG_OFFSET, XIic_WaitBusFree.
Referenced by EepromReadByte.
unsigned XIic_DynSend(UINTPTR BaseAddress, u16 Address, u8 *BufferPtr, u8 ByteCount, u8 Option)
Send data as a master on the IIC bus.
This function sends the data using polled I/O and blocks until the data has been sent. It only supports 7 bit addressing. This function returns zero if bus is busy. BaseAddress contains the base address of the IIC Device. Address contains the 7 bit IIC address of the device to send the specified data to. BufferPtr points to the data to be sent. ByteCount is the number of bytes to be sent. Option : XIIC_STOP = end with STOP condition, XIIC_REPEATED_START = don't end with STOP condition. The number of bytes sent. None.
References XIic_ClearIisr, XIic_DynSend7BitAddress, XIic_DynSendStartStopAddress, XIIC_INTR_ARB_LOST_MASK, XIIC_INTR_BNB_MASK, XIIC_INTR_TX_EMPTY_MASK, XIIC_INTR_TX_ERROR_MASK, XIic_ReadReg, XIIC_SR_BUS_BUSY_MASK, XIIC_SR_REG_OFFSET, XIIC_TX_DYN_STOP_MASK, XIic_WaitBusFree, XIIC_WRITE_OPERATION.
Referenced by EepromReadByte, EepromWriteByte.
int XIic_DynInit(UINTPTR BaseAddress)
u32 XIic_CheckIsBusBusy(UINTPTR BaseAddress)
u32 XIic_WaitBusFree(UINTPTR BaseAddress)
This function will wait until the I2C bus is free or timeout.
BaseAddress contains the base address of the I2C device. XST_SUCCESS if the I2C bus was freed before the timeout.XST_FAILURE otherwise. None.
Referenced by XIic_DynRecv, XIic_DynSend, XIic_Recv, XIic_Send.