mmi_dppsu14
u8 XMmiDp_AuxDebugEnabled
void XMmiDp_ClearGeneralHpdEvent(XMmiDp *InstancePtr)
This function clears XMMIDP_GENERAL_INT0 HPD_EVENT bit.
InstancePtr is a pointer to the XMmiDp instance. None None.
References XMMIDP_GEN_INT0, XMmiDp_ReadReg, XMmiDp_WriteReg.
void XMmiDp_GeneralInterruptEnable(XMmiDp *InstancePtr, u32 Mask)
This function enables XMMIDP_GENERAL_INTERRUPT_0 bits based on the mask.
InstancePtr is a pointer to the XMmiDp instance. Mask specifies the interrupt bits to enable None None.
References XMMIDP_GEN_INT_ENABLE0, XMmiDp_ReadReg, XMmiDp_WriteReg.
void XMmiDp_HpdInterruptEnable(XMmiDp *InstancePtr, u32 Mask)
This function enables XMMIDP_HPD_INTERRUPT_ENABLE bits based on the mask.
InstancePtr is a pointer to the XMmiDp instance. Mask specifies the interrupt bits to enable None None.
References XMmiDp_ReadReg, XMmiDp_WriteReg.
void XMmiDp_GeneralInterruptDisable(XMmiDp *InstancePtr, u32 Mask)
This function disables XMMIDP_GENERAL_INTERRUPT_0 bits based on the mask.
InstancePtr is a pointer to the XMmiDp instance. Mask specifies the interrupt bits to disable None None.
References XMMIDP_GEN_INT_ENABLE0, XMmiDp_ReadReg, XMmiDp_WriteReg.
void XMmiDp_HpdInterruptDisable(XMmiDp *InstancePtr, u32 Mask)
This function disables XMMIDP_HPD_INTERRUPT_ENABLE bits based on the mask.
InstancePtr is a pointer to the XMmiDp instance. Mask specifies the interrupt bits to disable None None.
References XMmiDp_ReadReg, XMmiDp_WriteReg.
void XMmiDp_SetHpdIrqHandler(XMmiDp *InstancePtr, XMmiDp_HpdIrqHandler CallbackFunc, void *CallbackRef)
This function installs a callback function for when a hpd irq event interrupt occurs.
InstancePtr is a pointer to the XMmiDp instance. CallbackFunc is the address to the callback function. CallbackRef is the user data item that will be passed to the callback function when it is invoked. None. None.
void XMmiDp_SetHpdHotPlugHandler(XMmiDp *InstancePtr, XMmiDp_HpdHotPlugHandler CallbackFunc, void *CallbackRef)
This function installs a callback function for when a hpd hotplug interrupt occurs.
InstancePtr is a pointer to the XMmiDp instance. CallbackFunc is the address to the callback function. CallbackRef is the user data item that will be passed to the callback function when it is invoked. None. None.
void XMmiDp_SetHpdHotUnplugHandler(XMmiDp *InstancePtr, XMmiDp_HpdHotUnplugHandler CallbackFunc, void *CallbackRef)
This function installs a callback function for when a hpd hot unplug interrupt occurs.
InstancePtr is a pointer to the XMmiDp instance. CallbackFunc is the address to the callback function. CallbackRef is the user data item that will be passed to the callback function when it is invoked. None. None.
void XMmiDp_HpdInterruptHandler(XMmiDp *InstancePtr)
This function is the HPD Event interrupt handler for the XMmiDp driver.
When an interrupt happens, it first detects what kind of interrupt happened, then decides which callback function to invoke. InstancePtr is a pointer to the XMmiDp instance. None. None.
References XMmiDp_ReadReg, XMmiDp_WriteReg.
Referenced by XMmiDp_GeneralInterruptHandler.
void XMmiDp_GeneralInterruptHandler(XMmiDp *InstancePtr)
This function is the top-level general interrupt handler for the XMmiDp driver.
It reads the GENERAL_INTERRUPT register, dispatches HPD events to XMmiDp_HpdInterruptHandler, and clears all pending event bits. InstancePtr is a pointer to the XMmiDp instance. None. None.
References XMMIDP_GEN_INT0, XMMIDP_GEN_INT_ENABLE0, XMmiDp_HpdInterruptHandler, XMmiDp_ReadReg, XMmiDp_WriteReg.
void XMmiDp_SdpStatusInterruptEnable(XMmiDp *InstancePtr, u32 Mask)
This function enables SDP_STATUS_ENABLE bits based on the mask.
InstancePtr is a pointer to the XMmiDp instance. Mask specifies the interrupt bits to enable None None.
References XMmiDp_ReadReg, XMmiDp_WriteReg.
void XMmiDp_FastLinkTrainEnable(XMmiDp *InstancePtr)
This function enables fast link training in the core controller.
InstancePtr is a pointer to the XDpPsu instance. Phy width val to be used over the main link based on one of the following selects: none. None.
References XMmiDp_RegReadModifyWrite.
void XMmiDp_FastLinkTrainDisable(XMmiDp *InstancePtr)
This function disables fast link training in the core controller.
InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_RegReadModifyWrite.
u32 XMmiDp_GetRxMaxLaneCount(XMmiDp *InstancePtr)
This function gets the max lane count supported from DPCD.
InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_AuxRead.
Referenced by XMmiDp_GetRxCapabilities.
u32 XMmiDp_GetRxMaxLinkRate(XMmiDp *InstancePtr)
This function gets the max link rate supported from Rx DPCD register.
InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_AuxRead.
Referenced by XMmiDp_GetRxCapabilities.
u32 XMmiDp_GetRxMstModeCap(XMmiDp *InstancePtr)
This function reads MST_CAP from Rx DPCD register.
InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_AuxRead, XMMIDP_DPCD_MSTM_CAP.
Referenced by XMmiDp_GetRxCapabilities.
u32 XMmiDp_StartLinkXmit(XMmiDp *InstancePtr)
This function initiates link training sequence with the Rx.
InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_SetDpcdTrainingPattern, XMmiDp_SetPhyLaneCount, XMmiDp_SetPhyLinkRate, XMmiDp_SetPhyPreEmphasis, XMmiDp_SetPhyTrainingPattern, XMmiDp_SetPhyVoltageSwing, XMmiDp_SetPhyXmitEnable.
u32 XMmiDp_SetSinkDpcdLinkCfgField(XMmiDp *InstancePtr)
This function configures DPCD Rx Field.
InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_AuxWrite, XMMIDP_DPCD_LINK_BW_SET, XMmiDp_DpcdReadModifyWrite.
void XDpPSu14_EnableCctlEnhanceFraming(XMmiDp *InstancePtr)
This function configures CCTL enhance framing enable bit.
InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_RegReadModifyWrite.
void XDpPSu14_DisableCctlEnhanceFraming(XMmiDp *InstancePtr)
This function configures CCTL enhance framing enable bit.
InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_RegReadModifyWrite.
void XMmiDp_GetDpcdTrainingAuxRdInterval(XMmiDp *InstancePtr)
This function reads Training Aux Read Interval register of sink DPCD.
InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_AuxRead.
Referenced by XMmiDp_GetRxCapabilities.
u32 XMmiDp_GetTrainingDelay(XMmiDp *InstancePtr)
This function returns the training aux interval.
The lowest time is 400us. All other WaitTimes are direct multiples of lowest time and value read from DPCD register. InstancePtr is a pointer to the XDpPsu instance. WaitTime. None.
Referenced by XMmiDp_TrainingStateChannelEqualization, XMmiDp_TrainingStateClockRecovery.
u32 XMmiDp_GetDpcdLaneStatusAdjReqs(XMmiDp *InstancePtr)
This function will do a burst AUX read from the RX device over the AUX channel.
The contents of the status registers will be stored for later use by XDp_TxCheckClockRecovery, XDp_TxCheckChannelEqualization, and XDp_TxAdjVswingPreemp. InstancePtr is a pointer to the XDp instance. XST_SUCCESS if the AUX read was successful.XST_FAILURE otherwise. None.
References XMmiDp_AuxRead.
Referenced by XMmiDp_CheckLinkStatus, XMmiDp_TrainingStateChannelEqualization, XMmiDp_TrainingStateClockRecovery.
u32 XMmiDp_CheckClockRecovery(XMmiDp *InstancePtr, u8 LaneCount)
This function checks if the RX device's DisplayPort Configuration Data (DPCD) indicates that the clock recovery sequence during link training was successful - the RX device's link clock and data recovery unit has realized and maintained the frequency lock for all lanes currently in use.
InstancePtr is a pointer to the XMmiDp instance. LaneCount is the number of lanes to check. XST_SUCCESS if the RX device's clock recovery PLL has achieved frequency lock for all lanes in use.XST_FAILURE otherwise. None.
Referenced by XMmiDp_CheckLinkStatus, XMmiDp_TrainingStateChannelEqualization, XMmiDp_TrainingStateClockRecovery.
u32 XMmiDp_AdjVswingPreemp(XMmiDp *InstancePtr)
This function reads the adjusted voltage swing and pre-emphasis level settings from the Rx DPCD register and modify the drive settings accordingly during link training.
InstancePtr is a pointer to the XDpPsu instance. XST_SUCCESS if writing the settings was successful.XST_FAILURE otherwise. None.
References XMmiDp_AuxWrite, XMmiDp_SetVswingPreemp.
Referenced by XMmiDp_TrainingStateChannelEqualization, XMmiDp_TrainingStateClockRecovery.
void XMmiDp_SetVswingPreemp(XMmiDp *InstancePtr, u8 *AuxData)
This function sets current voltage swing and pre-emphasis level settings from the LinkConfig structure to Phy and DPCD.
InstancePtr is a pointer to the XDpPsu instance. AuxData is a pointer to the array used for preparing a burst write over the AUX channel. XST_SUCCESS if writing the settings was successful.XST_FAILURE otherwise. None.
References XMmiDp_SetPhyPreEmphasis, XMmiDp_SetPhyVoltageSwing.
Referenced by XMmiDp_AdjVswingPreemp, XMmiDp_SetTrainingPattern.
u32 XMmiDp_SetTrainingPattern(XMmiDp *InstancePtr, XMmiDp_PhyTrainingPattern Pattern)
This function sets the training pattern to be used during link training for both the DisplayPort TX core and the RX device.
InstancePtr is a pointer to the XDp instance. Pattern selects the pattern to be used. XST_SUCCESS if setting the pattern was successful.XST_FAILURE otherwise. None.
References XMmiDp_AuxWrite, XMmiDp_PhyScrambleDisable, XMmiDp_PhyScrambleEnable, XMmiDp_SetPhyTrainingPattern, XMmiDp_SetVswingPreemp.
Referenced by XMmiDp_RunTraining, XMmiDp_TrainingStateChannelEqualization, XMmiDp_TrainingStateClockRecovery.
u32 XMmiDp_SetLinkRate(XMmiDp *InstancePtr, XMmiDp_PhyRate LinkRate)
This function sets the Rx Dpcd link rate as well as Phy link rate.
InstancePtr is a pointer to the XDp instance. LinkRate value to program. None None.
References XMmiDp_PhyWaitReady, XMmiDp_SetDpcdLinkRate, XMmiDp_SetPhyLinkRate, XMmiDp_SetPhyPowerdown.
Referenced by XMmiDp_TrainingStateAdjustLaneCount, XMmiDp_TrainingStateAdjustLinkRate, XMmiDp_TrainingStateClockRecovery.
void XMmiDp_SetLaneCount(XMmiDp *InstancePtr, XMmiDp_PhyLanes LaneCount)
This function sets the Rx Dpcd lane count as well as Phy lane count.
InstancePtr is a pointer to the XDp instance. LaneCount value to program. None None.
References XMmiDp_SetDpcdLaneCount, XMmiDp_SetPhyLaneCount.
Referenced by XMmiDp_TrainingStateAdjustLaneCount, XMmiDp_TrainingStateClockRecovery.
XMmiDp_TrainingState XMmiDp_TrainingStateClockRecovery(XMmiDp *InstancePtr)
This function runs the clock recovery sequence as part of link training.
The sequence is as follows: 0) Start signaling at the minimum voltage swing, pre-emphasis, and post- cursor levels. 1) Transmit training pattern 1 over the main link with symbol scrambling disabled. 2) The clock recovery loop. If clock recovery is unsuccessful after MaxIterations loop iterations, return. 2a) Wait for at least the period of time specified in the RX device's DisplayPort Configuration Data (DPCD) register, TRAINING_AUX_RD_INTERVAL. 2b) Check if all lanes have achieved clock recovery lock. If so, return. 2c) Check if the same voltage swing level has been used 5 consecutive times or if the maximum level has been reached. If so, return. 2d) Adjust the voltage swing, pre-emphasis, and post-cursor levels as requested by the RX device. 2e) Loop back to 2a. InstancePtr is a pointer to the XDp instance. The next training state: XMMIDP__TS_CHANNEL_EQUALIZATION if the clock recovery sequence completed successfully.XMMIDP__TS_FAILURE if writing the drive settings to the RX device was unsuccessful.XMMIDP__TS_ADJUST_LINK_RATE if the clock recovery sequence did not complete successfully. None.
References XMmiDp_AdjVswingPreemp, XMmiDp_CheckClockRecovery, XMmiDp_GetDpcdLaneStatusAdjReqs, XMmiDp_GetTrainingDelay, XMmiDp_SetLaneCount, XMmiDp_SetLinkRate, XMmiDp_SetTrainingPattern, XMmiDp_WaitUs.
Referenced by XMmiDp_RunTraining.
XMmiDp_TrainingState XMmiDp_TrainingStateAdjustLinkRate(XMmiDp *InstancePtr)
This function is reached if either the clock recovery or the channel equalization process failed during training.
As a result, the data rate will be downshifted, and training will be re-attempted (starting with clock recovery) at the reduced data rate. If the data rate is already at 1.62 Gbps, a downshift in lane count will be attempted. InstancePtr is a pointer to the XDp instance. The next training state: XMMIDP_TS_ADJUST_LANE_COUNT if the minimal data rate is already in use. Re-attempt training at a reduced lane count.XMMIDP_TS_CLOCK_RECOVERY otherwise. Re-attempt training. None.
References XMmiDp_SetLinkRate.
Referenced by XMmiDp_RunTraining.
XMmiDp_TrainingState XMmiDp_TrainingStateAdjustLaneCount(XMmiDp *InstancePtr)
This function is reached if either the clock recovery or the channel equalization process failed during training, and a minimal data rate of 1.62 Gbps was being used.
As a result, the number of lanes in use will be reduced, and training will be re-attempted (starting with clock recovery) at this lower lane count.Training will be re-attempted with the maximum data rate being used with the reduced lane count to train at the main link at the maximum bandwidth possible. InstancePtr is a pointer to the XDp instance. The next training state: XMMIDP_TS_FAILURE if only one lane is already in use.XMMIDP_TS_CLOCK_RECOVERY otherwise. Re-attempt training. None.
References XMmiDp_SetLaneCount, XMmiDp_SetLinkRate.
Referenced by XMmiDp_RunTraining.
void XMmiDp_GetDpcdMaxDownspread(XMmiDp *InstancePtr)
This function reads Rx DPCD MaxDownspread register bits.
InstancePtr is a pointer to the XDp instance. None None.
References XMmiDp_AuxRead.
Referenced by XMmiDp_GetRxCapabilities.
void XMmiDp_GetDpcdRev(XMmiDp *InstancePtr)
This function reads Rx DPCD revision number.
InstancePtr is a pointer to the XDp instance. None None.
References XMmiDp_AuxRead, XMMIDP_DPCD_REV.
Referenced by XMmiDp_GetRxCapabilities.
u32 XMmiDp_GetRxCapabilities(XMmiDp *InstancePtr)
This function reads Rx DPCD capability registers to initiate link training.
InstancePtr is a pointer to the XDp instance. XST_SUCCESS if the training process succeeded.XST_FAILURE otherwise. None.
References XMmiDp_AuxRead, XMmiDp_GetDpcdMaxDownspread, XMmiDp_GetDpcdRev, XMmiDp_GetDpcdTrainingAuxRdInterval, XMmiDp_GetRxMaxLaneCount, XMmiDp_GetRxMaxLinkRate, XMmiDp_GetRxMstModeCap.
u32 XMmiDp_CheckChannelEqualization(XMmiDp *InstancePtr, u8 LaneCount)
This function checks if the RX device's DisplayPort Configuration Data (DPCD) indicates that the channel equalization sequence during link training was successful - the RX device has achieved channel equalization, symbol lock, and interlane alignment for all lanes currently in use.
InstancePtr is a pointer to the XDpPsu instance. LaneCount is the number of lanes to check. XST_SUCCESS if the RX device has achieved channel equalization symbol lock, and interlane alignment for all lanes in use.XST_FAILURE otherwise. None.
Referenced by XMmiDp_CheckLinkStatus, XMmiDp_TrainingStateChannelEqualization.
XMmiDp_TrainingState XMmiDp_TrainingStateChannelEqualization(XMmiDp *InstancePtr)
This function runs the channel equalization sequence as part of link training.
The sequence is as follows: 0) Start signaling with the same drive settings used at the end of the clock recovery sequence. 1) Transmit training pattern 2 (or 3) over the main link with symbol scrambling disabled. 2) The channel equalization loop. If channel equalization is unsuccessful after 5 loop iterations, return. 2a) Wait for at least the period of time specified in the RX device's DisplayPort Configuration Data (DPCD) register, TRAINING_AUX_RD_INTERVAL. 2b) Check if all lanes have achieved channel equalization, symbol lock, and interlane alignment. If so, return. 2c) Check if the same voltage swing level has been used 5 consecutive times or if the maximum level has been reached. If so, return. 2d) Adjust the voltage swing, pre-emphasis, and post-cursor levels as requested by the RX device. 2e) Loop back to 2a. For a more detailed description of the channel equalization sequence, see section 3.5.1.2.2 of the DisplayPort 1.4a specification document. InstancePtr is a pointer to the XDp instance. The next training state: XDP_TX_TS_SUCCESS if training succeeded.XDP_TX_TS_FAILURE if writing the drive settings to the RX device was unsuccessful.XDP_TX_TS_ADJUST_LINK_RATE if, after 5 loop iterations, the channel equalization sequence did not complete successfully. None.
References XMmiDp_AdjVswingPreemp, XMmiDp_CheckChannelEqualization, XMmiDp_CheckClockRecovery, XMmiDp_GetDpcdLaneStatusAdjReqs, XMmiDp_GetTrainingDelay, XMmiDp_SetTrainingPattern, XMmiDp_WaitUs.
Referenced by XMmiDp_RunTraining.
u32 XMmiDp_CheckLinkStatus(XMmiDp *InstancePtr, u8 LaneCount)
This function checks if the Rx DisplayPort Configuration Data (DPCD) indicates the receiver has achieved and maintained clock recovery, channel equalization, symbol lock, and interlane alignment for all lanes currently in use.The DP 1.4 spec specifies checking for the above bits max 5 times before retraining link at lower link rate.
InstancePtr is a pointer to the XMmiDp instance. LaneCount is the number of lanes to check. XST_SUCCESS if the RX device has maintained clock recovery, channel equalization, symbol lock, and interlane alignment.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_FAILURE otherwise. None.
References XMmiDp_CheckChannelEqualization, XMmiDp_CheckClockRecovery, XMmiDp_GetDpcdLaneStatusAdjReqs, XMmiDp_IsConnected.
Referenced by XMmiDp_RunTraining.
u32 XMmiDp_RunTraining(XMmiDp *InstancePtr)
This function runs the link training process.
It is implemented as a state machine, with each state returning the next state. First, the clock recovery sequence will be run; if successful, the channel equalization sequence will run. If either the clock recovery or channel equalization sequence failed, the link rate or the number of lanes used will be reduced and training will be re-attempted. If training fails at the minimal data rate, 1.62 Gbps with a single lane, training will no longer re-attempt and fail. InstancePtr is a pointer to the XDp instance. XST_SUCCESS if the training process succeeded.XST_FAILURE otherwise. None.
References XMmiDp_AuxRead, XMmiDp_AuxWrite, XMmiDp_CheckLinkStatus, XMmiDp_SetTrainingPattern, XMmiDp_TrainingStateAdjustLaneCount, XMmiDp_TrainingStateAdjustLinkRate, XMmiDp_TrainingStateChannelEqualization, XMmiDp_TrainingStateClockRecovery.
void XMmiDp_WaitUs(XMmiDp *InstancePtr, u32 MicroSeconds)
This function is the delay/sleep function for the XMmiDp driver.
InstancePtr is a pointer to the XMmiDp instance. MicroSeconds is the number of microseconds to delay/sleep for. None. None.
Referenced by XMmiDp_AuxSoftReset, XMmiDp_CoreSoftResetAll, XMmiDp_InitiateActSeq, XMmiDp_IsConnected, XMmiDp_PhySoftReset, XMmiDp_PhyWaitReady, XMmiDp_SetDpcdLinkQualPattern, XMmiDp_SetDpcdTrainingPattern, XMmiDp_TrainingStateChannelEqualization, XMmiDp_TrainingStateClockRecovery, XMmiDp_WaitActHandledStatus, XMmiDp_WaitPayloadTableUpdateStatus.
static void XMmiDp_ClearAuxData(XMmiDp *InstancePtr)
This function clears the AUX_DATA registers by setting it to 0.
InstancePtr is a pointer to the XMmiDp instance. None.
static void XMmiDp_SetAuxData(XMmiDp *InstancePtr, XMmiDp_AuxTransaction *Request)
This function programs the Aux data to the AUX_DATA registers.
InstancePtr is a pointer to the XMmiDp instance. Request is a pointer to an initialized XMmiDp_AuxTransaction structure containing the required information for issuing an AUX command. None.
static u32 XMmiDp_GetAuxData(XMmiDp *InstancePtr, XMmiDp_AuxTransaction *Request)
This function reads the Aux data from AUX_DATA registers.
InstancePtr is a pointer to the XMmiDp instance. Request is a pointer to an initialized XMmiDp_AuxTransaction structure containing the required information for issuing an AUX command. None.
static u32 XMmiDp_AuxWaitReady(XMmiDp *InstancePtr)
This function waits until another request is no longer in progress.
Check if GENERAL_INTERRUPT_AUX_REPLY_EVENT bit is cleared. If not then wait. InstancePtr is a pointer to the XMmiDp instance. XST_SUCCESS if the the RX device is no longer busy.XST_ERROR_COUNT_MAX otherwise, if a timeout has occurred. None.
static u32 XMmiDp_AuxWaitReply(XMmiDp *InstancePtr)
This function waits for a reply indicating that the most recent AUX request has been received by the RX device.
InstancePtr is a pointer to the XMmiDp instance. XST_SUCCESS if a reply was sent from the RX device.XST_ERROR_COUNT_MAX otherwise, if a timeout has occurred. None.
static u32 XMmiDp_SetAuxRequest(XMmiDp *InstancePtr, XMmiDp_AuxTransaction *Request)
This function submits the supplied AUX request to the RX device over the AUX channel by writing the command, the destination address, (the write buffer for write commands), and the data size to the DisplayPort TX core.
InstancePtr is a pointer to the XMmiDp instance. Request is a pointer to an initialized XMmiDp_AuxTransaction structure containing the required information for issuing an AUX command. XST_SUCCESS if the request was acknowledged.XST_ERROR_COUNT_MAX if waiting for a reply timed out.XST_SEND_ERROR if the request was deferred.XST_FAILURE otherwise, if the request was NACK'ed. None.
void XMmiDp_CoreSoftResetAll(XMmiDp *InstancePtr)
Resets Controller, HDCP, Audio Sampler, and AUX blocks.
PHY and Video stream resets are intentionally excluded. InstancePtr is a pointer to the XMmiDp instance.
References XMmiDp_ReadReg, XMmiDp_WaitUs, XMmiDp_WriteReg.
void XMmiDp_AuxSoftReset(XMmiDp *InstancePtr)
Performs an AUX soft reset by toggling the AUX reset bit.
InstancePtr is a pointer to the XMmiDp instance. None. None.
References XMmiDp_ReadReg, XMmiDp_WaitUs, XMmiDp_WriteReg.
static u32 XMmiDp_AuxRequest(XMmiDp *InstancePtr, XMmiDp_AuxTransaction *Request)
Submits the supplied AUX request to the RX device over the AUX channel.
If waiting for a reply times out, or if the TX core indicates DEFER, the request is resent up to the configured defer/timeout retry limits. InstancePtr is a pointer to the XMmiDp instance. Request is a pointer to an initialized XMmiDp_AuxTransaction structure containing the required information for issuing an AUX command, as well as write/read buffers. XST_SUCCESS if the request was acknowledged.XST_ERROR_COUNT_MAX if resending exceeded defer/timeout limits.XST_FAILURE otherwise (for NACK or AUX transaction failure). None.
static u32 XMmiDp_AuxChanCommand(XMmiDp *InstancePtr, u32 AuxCmdType, u32 Address, u32 Bytes, u8 *Data)
This Api splits the Aux commands into multiple requests, each acting on a maximum of 16 bytes.
InstancePtr is a pointer to the XMmiDp instance. CmdType is the type of AUX command Address is the starting address that the AUX transaction will read/write from/to the RX device. NumBytes is the number of bytes to read/write from/to the RX device. Data is a pointer to the data buffer that contains the data to be read/written from/to the RX device. XST_SUCCESS if the AUX transaction request was acknowledged.XST_ERROR_COUNT_MAX if the AUX request timed out.XST_FAILURE otherwise (if the DisplayPort TX core sees a NACK reply code or if the AUX transaction failed).XST_DEVICE_NOT_FOUND if the sink is disconnected from the TX. None.
u32 XMmiDp_AuxWrite(XMmiDp *InstancePtr, u32 DpcdAddr, u32 Bytes, void *Data)
This function issues a write request over the AUX channel that will write to the RX device's DisplayPort Configuration Data (DPCD) address space.
The write message will be divided into multiple transactions which write a maximum of 16 bytes each. InstancePtr is a pointer to the XMmiDp instance. DpcdAddr is the starting address to write to the RX device. Bytes is the number of bytes to write to the RX device. Data is a pointer to the data buffer that contains the data to be written to the RX device. XST_SUCCESS if the AUX write request was successfully acknowledged.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_ERROR_COUNT_MAX if the AUX request timed out.XST_FAILURE otherwise. None.
References XMmiDp_IsConnected.
Referenced by XMmiDp_AdjVswingPreemp, XMmiDp_DpcdReadModifyWrite, XMmiDp_RunTraining, XMmiDp_SetDpcdLinkRate, XMmiDp_SetDpcdTrainingPattern, XMmiDp_SetSinkDpcdLinkCfgField, XMmiDp_SetTrainingPattern.
u32 XMmiDp_AuxRead(XMmiDp *InstancePtr, u32 DpcdAddr, u32 Bytes, void *Data)
This function issues a read request over the AUX channel that will read from the RX device's DisplayPort Configuration Data (DPCD) address space.
The read message will be divided into multiple transactions which read a maximum of 16 bytes each. InstancePtr is a pointer to the XMmiDp instance. DpcdAddress is the starting address to read from the RX device. Bytes is the number of bytes to read from the RX device. Data is a pointer to the data buffer that will be filled with read data. XST_SUCCESS if the AUX read request was successfully acknowledged.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_ERROR_COUNT_MAX if the AUX request timed out.XST_FAILURE otherwise. None.
References XMmiDp_IsConnected.
Referenced by XMmiDp_DpcdReadModifyWrite, XMmiDp_GetDpcdLaneStatusAdjReqs, XMmiDp_GetDpcdMaxDownspread, XMmiDp_GetDpcdRev, XMmiDp_GetDpcdTrainingAuxRdInterval, XMmiDp_GetRxCapabilities, XMmiDp_GetRxMaxLaneCount, XMmiDp_GetRxMaxLinkRate, XMmiDp_GetRxMstModeCap, XMmiDp_RunTraining, XMmiDp_SetDpcdTrainingPattern, XMmiDp_WaitActHandledStatus, XMmiDp_WaitPayloadTableUpdateStatus.
u32 XMmiDp_I2cWrite(XMmiDp *InstancePtr, u32 I2cAddr, u32 Bytes, void *Data)
This function performs an I2C write over the AUX channel.
InstancePtr is a pointer to the XMmiDp instance. IicAddress is the address on the I2C bus of the target device. BytesToWrite is the number of bytes to write. WriteData is a pointer to a buffer which will be used as the data source for the write. XST_SUCCESS if the I2C write has successfully completed with no errors.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_ERROR_COUNT_MAX if the AUX request timed out.XST_FAILURE otherwise. None.
References XMmiDp_IsConnected.
u32 XMmiDp_I2cRead(XMmiDp *InstancePtr, u32 I2cAddr, u16 Offset, u32 Bytes, void *Data)
This function performs an I2C read over the AUX channel.
The read message will be divided into multiple transactions if the requested data spans multiple segments. The segment pointer is automatically incremented and the offset is calibrated as needed. E.g. For an overall offset of: 128, an I2C read is done on segptr=0; offset=128.256, an I2C read is done on segptr=1; offset=0.384, an I2C read is done on segptr=1; offset=128.512, an I2C read is done on segptr=2; offset=0.etc. InstancePtr is a pointer to the XMmiDp instance. IicAddress is the address on the I2C bus of the target device. Offset is the offset at specified address of targeted I2C device that the read will start from. Bytes is the number of bytes to read. ReadData is a pointer to a buffer that will be filled with the I2C read data. XST_SUCCESS if the I2C write has successfully completed with no errors.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_ERROR_COUNT_MAX if the AUX request timed out.XST_FAILURE otherwise. None.
References XMmiDp_IsConnected.
Referenced by XMmiDp_GetEdidBlock.
void XMmiDp_RegReadModifyWrite(XMmiDp *InstancePtr, u32 RegOffset, u32 Mask, u32 Shift, u32 Val)
This helper api reads value from register, computes the new value and writes to the register.
InstancePtr is a pointer to the XMmiDp instance. Register offset to read/write values Mask value Shift value Val to be written None. None.
References XMmiDp_ReadReg, XMmiDp_WriteReg.
Referenced by XDpPSu14_DisableCctlEnhanceFraming, XDpPSu14_EnableCctlEnhanceFraming, XMmiDp_DisableVideoStream, XMmiDp_EnableVideoStream, XMmiDp_FastLinkTrainDisable, XMmiDp_FastLinkTrainEnable, XMmiDp_MstModeEnable, XMmiDp_PhyScrambleDisable, XMmiDp_PhyScrambleEnable, XMmiDp_PhySSCDisable, XMmiDp_PhySSCEnable, XMmiDp_SetPhyLaneCount, XMmiDp_SetPhyLinkRate, XMmiDp_SetPhyPowerdown, XMmiDp_SetPhyPreEmphasis, XMmiDp_SetPhyTrainingPattern, XMmiDp_SetPhyVoltageSwing, XMmiDp_SetPhyWidth, XMmiDp_SetPhyXmitDisable, XMmiDp_SetPhyXmitEnable.
u32 XMmiDp_DpcdReadModifyWrite(XMmiDp *InstancePtr, u32 DpcdReg, u32 Mask, u32 Shift, u32 Val)
This helper api reads value from DPCD, computes the new value and writes to the DPCD register.
InstancePtr is a pointer to the XMmiDp instance. Register offset to read/write values Mask value Shift value Val to be written XST_SUCCESS if AUX read and write both succeed.Error code propagated from XMmiDp_AuxRead() on read failure.Error code propagated from XMmiDp_AuxWrite() on write failure. None.
References XMmiDp_AuxRead, XMmiDp_AuxWrite.
Referenced by XMmiDp_SetDpcdLaneCount, XMmiDp_SetDpcdLinkQualPattern, XMmiDp_SetDpcdPreEmphasis, XMmiDp_SetDpcdVoltageSwing, XMmiDp_SetSinkDpcdLinkCfgField.
u8 XMmiDp_GetLaneCount(XMmiDp *InstancePtr, u8 NumLanes)
u8 XMmiDp_GetNumLanes(XMmiDp *InstancePtr, u8 LaneCount)
void XMmiDp_SetDpcdLaneCount(XMmiDp *InstancePtr)
This function sets the number of lanes to be used by the main link for both the DisplayPort TX core and the RX device.
InstancePtr is a pointer to the XMmiDp instance. LaneCount is the number of lanes to be used over the main link. None. None.
References XMmiDp_DpcdReadModifyWrite.
Referenced by XMmiDp_SetLaneCount.
void XMmiDp_SetPhyLaneCount(XMmiDp *InstancePtr, XMmiDp_PhyLanes LaneCount)
This function sets the number of lanes to be used by the main link for both the DisplayPort TX core and the RX device.
InstancePtr is a pointer to the XMmiDp instance. LaneCount is the number of lanes to be used over the main link. None. None.
References XMmiDp_RegReadModifyWrite.
Referenced by XMmiDp_SetLaneCount, XMmiDp_StartLinkXmit.
u16 XMmiDp_GetLinkRate(XMmiDp *InstancePtr, u8 LinkBW)
u8 XMmiDp_GetLinkBW(XMmiDp *InstancePtr, u8 LinkRate)
void XMmiDp_SetDpcdLinkRate(XMmiDp *InstancePtr)
This function sets the dpcd link bw to be used by the main link for both the DisplayPort TX core and the RX device.
InstancePtr is a pointer to the XDpPsu instance. LinkRate is the link rate to be used over the main link based on one of the following selects: XMMIDP_LINK_BW_SET_162GBPS = 0x06 (for a 1.62 Gbps data rate)XMMIDP_LINK_BW_SET_270GBPS = 0x0A (for a 2.70 Gbps data rate)XMMIDP_LINK_BW_SET_540GBPS = 0x14 (for a 5.40 Gbps data rate)XMMIDP_LINK_BW_SET_810GBPS = 0x1E (for a 8.10 Gbps data rate) none. None.
References XMmiDp_AuxWrite, XMMIDP_DPCD_LINK_BW_SET.
Referenced by XMmiDp_SetLinkRate.
void XMmiDp_SetPhyLinkRate(XMmiDp *InstancePtr, XMmiDp_PhyRate LinkRate)
This function sets the data rate to be used by the main link for both the DisplayPort TX core and the RX device.
InstancePtr is a pointer to the XDpPsu instance. LinkRate is the link rate to be used over the main link based on one of the following selects: XMMIDP_LINK_BW_SET_162GBPS = 0x06 (for a 1.62 Gbps data rate)XMMIDP_LINK_BW_SET_270GBPS = 0x0A (for a 2.70 Gbps data rate)XMMIDP_LINK_BW_SET_540GBPS = 0x14 (for a 5.40 Gbps data rate)XMMIDP_LINK_BW_SET_810GBPS = 0x1E (for a 8.10 Gbps data rate) none. None.
References XMmiDp_RegReadModifyWrite, XMmiDp_SetPhyWidth.
Referenced by XMmiDp_SetLinkRate, XMmiDp_StartLinkXmit.
void XMmiDp_SetDpcdLinkQualPattern(XMmiDp *InstancePtr, XMmiDp_PhyTrainingPattern Pattern)
This function sets the DPCD Link qual_0 training pattern to be used by the main link for both the DisplayPort TX core and the RX device.
InstancePtr is a pointer to the XDpPsu instance. Pattern select to be used over the main link based on one of the following selects: XMMIDP_PHY_NO_TRAIN = 0x0, XMMIDP_PHY_TPS1 = 0x1, XMMIDP_PHY_TPS2 = 0x2, XMMIDP_PHY_TPS3 = 0x3, XMMIDP_PHY_TPS4 = 0x4, XMMIDP_PHY_SYMBOL_ERR_RATE = 0x5, XMMIDP_PHY_PRBS7 = 0x6, XMMIDP_PHY_CUSTOMPAT = 0x7, XMMIDP_PHY_CP2520_PAT_1 = 0x8, XMMIDP_PHY_CP2520_PAT_2 = 0x9, none. None.
References XMmiDp_DpcdReadModifyWrite, XMmiDp_WaitUs.
void XMmiDp_SetDpcdTrainingPattern(XMmiDp *InstancePtr, XMmiDp_PhyTrainingPattern Pattern)
This function sets the DPCD training pattern to be used by the main link for both the DisplayPort TX core and the RX device.
InstancePtr is a pointer to the XDpPsu instance. Pattern select to be used over the main link based on one of the following selects: XMMIDP_PHY_NO_TRAIN = 0x0, XMMIDP_PHY_TPS1 = 0x1, XMMIDP_PHY_TPS2 = 0x2, XMMIDP_PHY_TPS3 = 0x3, XMMIDP_PHY_TPS4 = 0x4, XMMIDP_PHY_SYMBOL_ERR_RATE = 0x5, XMMIDP_PHY_PRBS7 = 0x6, XMMIDP_PHY_CUSTOMPAT = 0x7, XMMIDP_PHY_CP2520_PAT_1 = 0x8, XMMIDP_PHY_CP2520_PAT_2 = 0x9, none. None.
References XMmiDp_AuxRead, XMmiDp_AuxWrite, XMmiDp_WaitUs.
Referenced by XMmiDp_StartLinkXmit.
void XMmiDp_SetPhyTrainingPattern(XMmiDp *InstancePtr, XMmiDp_PhyTrainingPattern Pattern)
This function sets the training pattern to be used by the main link for both the DisplayPort TX core and the RX device.
InstancePtr is a pointer to the XDpPsu instance. Pattern select to be used over the main link based on one of the following selects: XMMIDP_PHY_NO_TRAIN = 0x0, XMMIDP_PHY_TPS1 = 0x1, XMMIDP_PHY_TPS2 = 0x2, XMMIDP_PHY_TPS3 = 0x3, XMMIDP_PHY_TPS4 = 0x4, XMMIDP_PHY_SYMBOL_ERR_RATE = 0x5, XMMIDP_PHY_PRBS7 = 0x6, XMMIDP_PHY_CUSTOMPAT = 0x7, XMMIDP_PHY_CP2520_PAT_1 = 0x8, XMMIDP_PHY_CP2520_PAT_2 = 0x9, none. None.
References XMmiDp_RegReadModifyWrite.
Referenced by XMmiDp_SetTrainingPattern, XMmiDp_StartLinkXmit.
static void XMmiDp_GetVoltageSwingMask(u32 Lane, u32 *VsShift, u32 *VsMask)
void XMmiDp_SetDpcdVoltageSwing(XMmiDp *InstancePtr, XMmiDp_PhyVSwing *VsLevel)
This function sets the DPCD VoltageSwing levels int the DisplayPort TX core.
InstancePtr is a pointer to the XDpPsu instance. VoltageSwing for each lane to be used over the main link based on one of the following selects: XMMIDP_PHY_VSWING_LEVEL0XMMIDP_PHY_VSWING_LEVEL1XMMIDP_PHY_VSWING_LEVEL2XMMIDP_PHY_VSWING_LEVEL3 none. None.
References XMmiDp_DpcdReadModifyWrite.
void XMmiDp_SetPhyVoltageSwing(XMmiDp *InstancePtr, u8 *VsLevel)
This function sets the VoltageSwing levels in the DisplayPort TX core.
InstancePtr is a pointer to the XDpPsu instance. VoltageSwing for each lane to be used over the main link based on one of the following selects: XMMIDP_PHY_VSWING_LEVEL0XMMIDP_PHY_VSWING_LEVEL1XMMIDP_PHY_VSWING_LEVEL2XMMIDP_PHY_VSWING_LEVEL3 none. None.
References XMmiDp_RegReadModifyWrite.
Referenced by XMmiDp_SetVswingPreemp, XMmiDp_StartLinkXmit.
static void XMmiDp_GetPreEmphasisMask(u32 Lane, u32 *PeShift, u32 *PeMask)
void XMmiDp_SetDpcdPreEmphasis(XMmiDp *InstancePtr, XMmiDp_PhyPreEmp *PeLevel)
This function sets the DPCD VoltagePreEmphasis levels for the DisplayPort TX PHY.
InstancePtr is a pointer to the XDpPsu instance. VoltageSwing for each lane to be used over the main link based on one of the following selects: PHYPREEMP_LEVEL0PHYPREEMP_LEVEL1PHYPREEMP_LEVEL2PHYPREEMP_LEVEL3 none. None.
References XMmiDp_DpcdReadModifyWrite.
void XMmiDp_SetPhyPreEmphasis(XMmiDp *InstancePtr, u8 *PeLevel)
This function sets the VoltagePreEmphasis levels for the DisplayPort TX PHY.
InstancePtr is a pointer to the XDpPsu instance. VoltageSwing for each lane to be used over the main link based on one of the following selects: XMMIDP_PHY_PREEMP_LEVEL0XMMIDP_PHY_PREEMP_LEVEL1XMMIDP_PHY_PREEMP_LEVEL2XMMIDP_PHY_PREEMP_LEVEL3 none. None.
References XMmiDp_RegReadModifyWrite.
Referenced by XMmiDp_SetVswingPreemp, XMmiDp_StartLinkXmit.
void XMmiDp_SetPhyXmitEnable(XMmiDp *InstancePtr)
This function enables phy transfer for lanes.
InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_RegReadModifyWrite.
Referenced by XMmiDp_StartLinkXmit.
void XMmiDp_SetPhyXmitDisable(XMmiDp *InstancePtr)
This function disables phy transfer for lanes.
InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_RegReadModifyWrite.
void XMmiDp_PhyScrambleEnable(XMmiDp *InstancePtr)
This function enables phy scrambler over the main link through CCTL register.
InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_RegReadModifyWrite.
Referenced by XMmiDp_SetTrainingPattern.
void XMmiDp_PhyScrambleDisable(XMmiDp *InstancePtr)
This function disable phy scrambler.
InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_RegReadModifyWrite.
Referenced by XMmiDp_SetTrainingPattern.
u32 XMmiDp_IsConnected(XMmiDp *InstancePtr)
This function checks if there is a connected RX device.
InstancePtr is a pointer to the XMmiDp instance. 1 if there is a connection.0 if there is no connection.
References XMmiDp_ReadReg, XMmiDp_WaitUs.
Referenced by XMmiDp_AuxRead, XMmiDp_AuxWrite, XMmiDp_CheckLinkStatus, XMmiDp_I2cRead, XMmiDp_I2cWrite.
void XMmiDp_CfgInitialize(XMmiDp *InstancePtr, u32 BaseAddr)
This function initializes the configuration for the XMmiDp Instance.
InstancePtr is a pointer to the XMmiDp instance. BaseAddr sets the base address of the DP instance None.
u32 XMmiDp_PhyWaitReady(XMmiDp *InstancePtr)
This function waits for the DisplayPort PHY to come out of reset.
InstancePtr is a pointer to the XMmiDp instance. XST_ERROR_COUNT_MAX if the PHY failed to be ready.XST_SUCCESS otherwise. None.
References XMmiDp_ReadReg, XMmiDp_WaitUs.
Referenced by XMmiDp_PhySoftReset, XMmiDp_SetLinkRate.
void XMmiDp_PhySoftReset(XMmiDp *InstancePtr)
This function does a PHY Soft reset.
InstancePtr is a pointer to the XMmiDp instance. Reset is the type of reset to assert. None. None.
References XMmiDp_PhyWaitReady, XMmiDp_ReadReg, XMmiDp_WaitUs, XMmiDp_WriteReg.
u32 XMmiDp_GetEdidBlock(XMmiDp *InstancePtr, u8 *Data, u8 BlockNum)
This function retrieves connected RX devices Extended Display Identification given the block number.
A block num of 0 represents the base EDID. InstancePtr is a pointer to the XMmiDp instance. Data is a pointer to the data buffer to save the block data to BlockNum is the EDID block number to retrieve. XST_SUCCESS if the block read has successfully completed with no errors.XST_ERROR_COUNT_MAX if a time out occurred while attempting to read the requested block.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_FAILURE otherwise. None.
References XMmiDp_I2cRead.
void XMmiDp_PhySSCEnable(XMmiDp *InstancePtr)
This function enables SSC on the PHY.
InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_RegReadModifyWrite.
void XMmiDp_PhySSCDisable(XMmiDp *InstancePtr)
This function disables SSC on the PHY.
InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_RegReadModifyWrite.
void XMmiDp_Initialize(XMmiDp *InstancePtr)
This function Initializes the XMmiDp Instance structure.
InstancePtr is a pointer to the XDpPsu instance. none. None.
void XMmiDp_SetPhyPowerdown(XMmiDp *InstancePtr, XMmiDp_PhyPwrDown Control)
This function sets the phy powerdown control val.
InstancePtr is a pointer to the XDpPsu instance. Powerdown val is the link rate to be used over the main link based on one of the following selects: none. None.
References XMmiDp_RegReadModifyWrite.
Referenced by XMmiDp_SetLinkRate.
void XMmiDp_SetPhyWidth(XMmiDp *InstancePtr, XMmiDp_PhyWidth Width)
This function sets the phy width control val.
InstancePtr is a pointer to the XDpPsu instance. Phy width val to be used over the main link based on one of the following selects: none. None.
References XMmiDp_RegReadModifyWrite.
Referenced by XMmiDp_SetPhyLinkRate.
void XMmiDp_SetAux_250Us_Cnt_Limit(XMmiDp *InstancePtr, u16 Limit)
This function sets the AUX_250US_CNT_LIMIT.
InstancePtr is a pointer to the XDpPsu instance. Aux 250Us count limit none. None.
References XMmiDp_WriteReg.
void XMmiDp_SetAux_2000Us_Cnt_Limit(XMmiDp *InstancePtr, u16 Limit)
This function sets the AUX_2000US_CNT_LIMIT.
InstancePtr is a pointer to the XDpPsu instance. Aux 2000Us count limit none. None.
References XMmiDp_WriteReg.
void XMmiDp_SetAux_100000Us_Cnt_Limit(XMmiDp *InstancePtr, u32 Limit)
This function sets the AUX_100000US_CNT_LIMIT.
InstancePtr is a pointer to the XDpPsu instance. Aux 100000Us count limit none. None.
References XMmiDp_WriteReg.
void XMmiDp_SetPmConfig1(XMmiDp *InstancePtr, u32 Val)
This function sets PM_COFIG1 register.
InstancePtr is a pointer to the XDpPsu instance. RegVal none. None.
References XMmiDp_WriteReg.
void XMmiDp_SetPmConfig2(XMmiDp *InstancePtr, u32 Val)
This function sets PM_COFIG2 register.
InstancePtr is a pointer to the XDpPsu instance. RegVal none. None.
References XMmiDp_WriteReg.
void XMmiDp_SetAuxDebug(u8 Enable)
This function enables or disables runtime AUX debug prints.
Enable is 1 to enable debug prints, 0 to disable. None. None.
void XMmiDp_DisableVideoStream(XMmiDp *InstancePtr, u8 Stream)
This function disables video stream.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_RegReadModifyWrite.
void XMmiDp_EnableVideoStream(XMmiDp *InstancePtr, u8 Stream)
This function enabless video stream.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_RegReadModifyWrite.
void XMmiDp_ClearMsaValues(XMmiDp *InstancePtr, u8 Stream)
This function clears MSA values.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_WriteReg.
Referenced by XMmiDp_ClearVideoController.
void XMmiDp_ClearVideoConfigValues(XMmiDp *InstancePtr, u8 Stream)
This function clears out Video Config Register values.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_WriteReg.
Referenced by XMmiDp_ClearVideoController.
void XMmiDp_SetVInputPolarityCtrl(XMmiDp *InstancePtr, u8 Stream)
This function sets the video input polarity control.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_WriteReg.
Referenced by XMmiDp_ConfigureVideoController.
void XMmiDp_SetVideoConfig1(XMmiDp *InstancePtr, u8 Stream)
This function sets the video config1 register.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMMIDP_VIDEO_CONFIG1, XMmiDp_WriteReg.
Referenced by XMmiDp_ConfigureVideoController.
void XMmiDp_SetVideoConfig2(XMmiDp *InstancePtr, u8 Stream)
This function sets the video config2 register.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_WriteReg.
Referenced by XMmiDp_ConfigureVideoController.
void XMmiDp_SetVideoConfig3(XMmiDp *InstancePtr, u8 Stream)
This function sets the video config3 register.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_WriteReg.
Referenced by XMmiDp_ConfigureVideoController.
void XMmiDp_SetVideoConfig4(XMmiDp *InstancePtr, u8 Stream)
This function sets the video config4 register.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_WriteReg.
Referenced by XMmiDp_ConfigureVideoController.
void XMmiDp_SetVideoConfig5(XMmiDp *InstancePtr, u8 Stream)
This function sets the video config5 register.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_WriteReg.
Referenced by XMmiDp_ConfigureVideoController.
void XMmiDp_SetVSampleCtrl(XMmiDp *InstancePtr, u8 Stream)
This function sets the vsample register.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_WriteReg.
Referenced by XMmiDp_ConfigureVideoController.
void XMmiDp_SetVideoMsa1(XMmiDp *InstancePtr, u8 Stream)
This function sets video msa1 register.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_WriteReg.
Referenced by XMmiDp_ConfigureVideoController.
void XMmiDp_SetVideoMsa2(XMmiDp *InstancePtr, u8 Stream)
This function sets video msa2 register.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_WriteReg.
Referenced by XMmiDp_ConfigureVideoController.
void XMmiDp_SetVideoMsa3(XMmiDp *InstancePtr, u8 Stream)
This function sets video msa3 register.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_WriteReg.
Referenced by XMmiDp_ConfigureVideoController.
void XMmiDp_SetHBlankInterval(XMmiDp *InstancePtr, u8 Stream)
This function sets video HBlankInterval register.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_WriteReg.
Referenced by XMmiDp_ConfigureVideoController.
void XMmiDp_ConfigureVideoController(XMmiDp *InstancePtr, u8 Stream)
This is helper api that programs the VideoController MSA, VideoConfig registers for a specific stream.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_SetHBlankInterval, XMmiDp_SetVideoConfig1, XMmiDp_SetVideoConfig2, XMmiDp_SetVideoConfig3, XMmiDp_SetVideoConfig4, XMmiDp_SetVideoConfig5, XMmiDp_SetVideoMsa1, XMmiDp_SetVideoMsa2, XMmiDp_SetVideoMsa3, XMmiDp_SetVInputPolarityCtrl, XMmiDp_SetVSampleCtrl.
void XMmiDp_ClearVideoController(XMmiDp *InstancePtr)
This is helper api that clears the VideoController MSA, VideoConfig registers for a specific stream.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_ClearMsaValues, XMmiDp_ClearVideoConfigValues.
void XMmiDp_SetMsaBpc(XMmiDp *InstancePtr, u8 Stream, u8 BitsPerColor)
This function sets the bits per color value of the video stream.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. BitsPerColor is the new number of bits per color to use. None.
void XMmiDp_SetPixModeSel(XMmiDp *InstancePtr, u8 Stream, XMmiDp_PPC PixModeSel)
This function sets the pixel mode of the video stream.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. PixModeSel. None.
void XMmiDp_SetVideoMapping(XMmiDp *InstancePtr, u8 Stream, XMmiDp_VidMap VidMap)
This function sets the video format of the video stream.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Video input mapping. None.
void XMmiDp_SetVidStreamEnable(XMmiDp *InstancePtr, u8 Stream, u8 StreamEnable)
This function sets the video stream to enable or disable.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Enable or Disable. None.
void XMmiDp_SetAudStreamInterfaceSel(XMmiDp *InstancePtr, u8 Stream, u8 InterfaceSel)
This function sets the audio stream interface.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Audio interface I2S or SPDIF . None.
void XMmiDp_SetAudDataInputEn(XMmiDp *InstancePtr, u8 Stream, u8 ActiveDataInput)
This function sets the active audio data input.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Active data input on different channels. None.
void XMmiDp_SetAudDataWidth(XMmiDp *InstancePtr, u8 Stream, u8 DataWidth)
This function sets the audio data width val(16 bit - 24 bit).
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Audio Data Width. None.
void XMmiDp_SetAudHbrModeEn(XMmiDp *InstancePtr, u8 Stream, u8 HbrModeEn)
This function sets the audio input is operating in HBR mode or not.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Audio HBR mode en or disable None.
void XMmiDp_SetAudNumChannels(XMmiDp *InstancePtr, u8 Stream, u8 NumChannels)
This function sets the audio num of channels used.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Audio num channels None.
void XMmiDp_SetAudMuteFlag(XMmiDp *InstancePtr, u8 Stream, u8 AudioMute)
This function controls the audio mute flag in VB-ID.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Audio mute clear or set None.
void XMmiDp_SetAudPktId(XMmiDp *InstancePtr, u8 Stream, u8 PktId)
This function defines first byte of audio SDP and audio timestamp SDP header.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Audio Packet Id None.
void XMmiDp_SetAudTimeStampVerNum(XMmiDp *InstancePtr, u8 Stream, u8 VerNum)
This function defines audio timestamp version num.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Audio timestamp version number None.
void XMmiDp_SetAudClkMultFs(XMmiDp *InstancePtr, u8 Stream, u8 ClkMultFs)
This function defines audio clock frequency multiplier in relation to audio sample rate Fs.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Audio clock frequency multiplier None.
void XMmiDp_SetAudioConfig1(XMmiDp *InstancePtr, u8 Stream)
This function programs the AUDIO_CONFIG1 registers.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. None.
References XMmiDp_WriteReg.
Referenced by XMmiDp_ConfigureAudioController.
void XMmiDp_SetSdpVertAudTimeStampEn(XMmiDp *InstancePtr, u8 Stream, u8 EnAudTimeStamp)
This function enables audio timestamp for sdp vertical ctrl.
When set, dptx sends out audio timestamp SDP once every video frame during vertical blanking period. InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Audio timestamp sdp enable/disable. None.
void XMmiDp_SetSdpVertAudStreamEn(XMmiDp *InstancePtr, u8 Stream, u8 EnAudStream)
This function enables audio stream during vertical blanking .
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Audio stream enable/disable. None.
void XMmiDp_SetSdpVertEn(XMmiDp *InstancePtr, u8 Stream, u32 EnVerticalSdp)
This function sets SDP to be sent out during vertical intervals using data from SDP_REGISTER_BANK .
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Enable SDP during vertical intervals. None.
void XMmiDp_SetSdpVertEn128Bytes(XMmiDp *InstancePtr, u8 Stream, u8 En128Bytes)
This function sets 128 bytes of SDP by using SDP_REGISTER_BANK 1,2,3 and 4.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Enable/Disable 128BytesSdp. None.
void XMmiDp_SetDisableExternalSdp(XMmiDp *InstancePtr, u8 Stream, u8 DisExternalSdp)
This function disables external SDP when set.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Enable/Disable external SDP. None.
void XMmiDp_SetSdpVertFixedPriority(XMmiDp *InstancePtr, u8 Stream, u8 EnFixedPriority)
This function sets scheduler searches for next SDP to transmit based on fixed priority.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Enable/Disable fixed priority SDP scheduler. None.
void XMmiDp_SetSdpVerticalCtrl(XMmiDp *InstancePtr, u8 Stream)
This function programs the SDP_VERTICAL_CTRL registers.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. None.
References XMmiDp_WriteReg.
Referenced by XMmiDp_ConfigureAudioController.
void XMmiDp_SetSdpHorAudTimeStampEn(XMmiDp *InstancePtr, u8 Stream, u8 EnAudTimeStamp)
This function enables audio timestamp for sdp horizontal ctrl.
When set, dptx sends out audio timestamp SDP once every video frame during horizontal blanking period. InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Audio timestamp sdp enable/disable. None.
void XMmiDp_SetSdpHorAudStreamEn(XMmiDp *InstancePtr, u8 Stream, u8 EnAudStream)
This function enables audio stream during horizontal blanking .
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Audio stream enable/disable. None.
void XMmiDp_SetSdpHorizontalEn(XMmiDp *InstancePtr, u8 Stream, u32 EnHorizontalSdp)
This function sets SDP to be sent out during horizontal intervals using data from SDP_REGISTER_BANK .
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Enable SDP during horizontal intervals. None.
void XMmiDp_SetSdpHorFixedPriority(XMmiDp *InstancePtr, u8 Stream, u8 EnFixedPriority)
This function sets scheduler searches for next SDP to transmit based on fixed priority.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Enable/Disable fixed priority SDP scheduler. None.
void XMmiDp_SetSdpHorizontalCtrl(XMmiDp *InstancePtr, u8 Stream)
This function programs the SDP_HORIZONTAL_CTRL registers.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. None.
References XMmiDp_WriteReg.
Referenced by XMmiDp_ConfigureAudioController.
void XMmiDp_ConfigureAudioController(XMmiDp *InstancePtr, u8 Stream)
This function programs DpTx Audio Controller.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. None.
References XMmiDp_SetAudioConfig1, XMmiDp_SetSdpHorizontalCtrl, XMmiDp_SetSdpVerticalCtrl.
void XMmiDp_SetSdpManualCtrl(XMmiDp *InstancePtr, u8 Stream, u32 SdpManualCtrl)
This function sets the Sdp manual mode.
Setting this bit causes corresponding SDP to be transmitted once. InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Enable/Disable Sdp Manual Ctrl None.
void XMmiDp_SetSdpCfg1HBlankOvr(XMmiDp *InstancePtr, u8 Stream, u8 SdpHBlankOvr)
This function overrides the number of available bytes required to transmit a 16 byte SDP during Horizontal blanking period.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. SdpHBlankOver None.
void XMmiDp_SetSdpCfgr2HBlankOvr(XMmiDp *InstancePtr, u8 Stream, u8 SdpHBlankOvr)
void XMmiDp_SetSdpCfgr3HBlankOvr(XMmiDp *InstancePtr, u8 Stream, u8 SdpHBlankOvr)
void XMmiDp_SetSdpCfg1VBlankOvr(XMmiDp *InstancePtr, u8 Stream, u8 SdpVBlankOvr)
This function overrides the number of available bytes required to transmit a 16 byte SDP during Vertical blanking period.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. SdpVBlankOver None.
void XMmiDp_SetSdpCfg2VBlankOvr(XMmiDp *InstancePtr, u8 Stream, u8 SdpVBlankOvr)
void XMmiDp_SetSdpCfg3VBlankOvr(XMmiDp *InstancePtr, u8 Stream, u8 SdpVBlankOvr)
void XMmiDp_SetSdpConfig(XMmiDp *InstancePtr, u8 Stream)
This function sets the SDP_CONFIG_X registers.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_WriteReg.
void XMmiDp_SetSdpRegBank(XMmiDp *InstancePtr, u8 Stream, u32 SdpReg)
This function defines the header and data for SDP.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. SdpReg None.
void XMmiDp_SetControllerScrambleDis(XMmiDp *InstancePtr, u8 Stream, u8 ScrambleDis)
This function sets the Scramble control for DpTx.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Controller enable or disable None.
void XMmiDp_SetControllerEnhanceFramingEn(XMmiDp *InstancePtr, u8 Stream, u8 EnhanceFramingEn)
This function sets the enhanced framing control for DpTx.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Controller enable or disable None.
void XMmiDp_SetControllerEnhanceFramingWithFecEn(XMmiDp *InstancePtr, u8 Stream, u8 EnhanceFramingWithFecEn)
This function sets the enhanced framing control with FEC feature for DpTx.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Controller enable or disable None.
void XMmiDp_SetControllerFastLinkTrainEn(XMmiDp *InstancePtr, u8 Stream, u8 FastLinkTrainEn)
This function sets default fast link training for DpTx.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Controller enable or disable None.
void XMmiDp_SetControllerScaleDownModeEn(XMmiDp *InstancePtr, u8 Stream, u8 ScaleDownModeEn)
This function scales down debounce filter on HPD input for DpTx.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Controller enable or disable None.
void XMmiDp_SetControllerDisableInterleaving(XMmiDp *InstancePtr, u8 Stream, u8 DisableInterleaving)
This function disables SPD nibble interleaving DpTx.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Controller enable or disable None.
void XMmiDp_SetControllerSelAuxTimeout32Ms(XMmiDp *InstancePtr, u8 Stream, u8 SelAuxTimeout32Ms)
This function sets aux reply timeout to either 400us or 3.2ms DpTx.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. 0x0 for 400us, 0x1 for 3.2ms None.
void XMmiDp_SetControllerMstModeEn(XMmiDp *InstancePtr, u8 Stream, u8 MstModeEn)
This function enables MST mode for DpTx.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Controller enable/disable None.
void XMmiDp_SetControllerFecEn(XMmiDp *InstancePtr, u8 Stream, u8 FecEn)
This function enables FEC feature for DpTx.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Controller enable/disable None.
void XMmiDp_SetControllereDpEn(XMmiDp *InstancePtr, u8 Stream, u8 eDpEn)
This function sets DpTx in eDP mode.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Controller enable/disable None.
void XMmiDp_SetControllerInitiateMstActSeq(XMmiDp *InstancePtr, u8 Stream, u8 InitiateMstActSeq)
This function use in MST mode only triggers link to start ACT sequence with DpRx of branch.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Controller enable/disable None.
void XMmiDp_SetCoreCtrl(XMmiDp *InstancePtr, u8 Stream)
This function sets the core controller register.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_WriteReg.
void XMmiDp_MstModeEnable(XMmiDp *InstancePtr)
This function enables mst mode in the core controller.
InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_RegReadModifyWrite.
void XMmiDp_MstActSeqEnable(XMmiDp *InstancePtr)
This function enables mst act seq in the core controller.
InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_WriteReg.
Referenced by XMmiDp_InitiateActSeq.
u32 XMmiDp_WaitPayloadTableUpdateStatus(XMmiDp *InstancePtr)
This function waits for VC_PAYLOAD_TABLE_UPDATE status bit to be set.
status. This ensures successful update of VC_PAYLOAD_TABLE. InstancePtr is a pointer to the XDpPsu instance. XST_SUCCESS/XST_FAILURE. None.
References XMmiDp_AuxRead, XMmiDp_WaitUs.
u32 XMmiDp_WaitActHandledStatus(XMmiDp *InstancePtr)
This function waits for ACT_Handled status bit to be set.
status. This ensures successful handling of ACT trigger. InstancePtr is a pointer to the XDpPsu instance. XST_SUCCESS/XST_FAILURE. None.
References XMmiDp_AuxRead, XMmiDp_WaitUs.
Referenced by XMmiDp_InitiateActSeq.
u32 XMmiDp_InitiateActSeq(XMmiDp *InstancePtr)
This function initiates CCTL ACT sequence between DpTx and DpRx of the immediate branch device connected.
Check DPCD Payload table update status. This ensures successful handling of ACT trigger sequence. InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_MstActSeqEnable, XMmiDp_ReadReg, XMmiDp_WaitActHandledStatus, XMmiDp_WaitUs.
void XMmiDp_SetMstVcpTable0(XMmiDp *InstancePtr, u32 Payload)
This function sets the virtual channel payload allocation table.
InstancePtr is a pointer to the XMmiDp instance. u32 Payload slot for each stream None.
References XMmiDp_WriteReg.
void XMmiDp_SetMstVcpTable1(XMmiDp *InstancePtr, u32 Payload)
void XMmiDp_SetMstVcpTable2(XMmiDp *InstancePtr, u32 Payload)
void XMmiDp_SetMstVcpTable3(XMmiDp *InstancePtr, u32 Payload)
void XMmiDp_SetMstVcpTable4(XMmiDp *InstancePtr, u32 Payload)
void XMmiDp_SetMstVcpTable5(XMmiDp *InstancePtr, u32 Payload)
void XMmiDp_SetMstVcpTable6(XMmiDp *InstancePtr, u32 Payload)
void XMmiDp_SetMstVcpTable7(XMmiDp *InstancePtr, u32 Payload)
void XMmiDp_ComputeMisc0(XMmiDp *InstancePtr, u8 Stream, XVidC_ColorFormat ColorFormat)
Computes the MSA Misc0 field from the stream's BitsPerColor and the supplied color format, and stores the result in MsaConfig[Stream].Misc0.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream ID (XMMIDP_STREAM_ID1..ID4). ColorFormat is the color format (RGB, YCbCr 4:4:4/4:2:2). None.
Referenced by XMmiDp_SetVidControllerUseStdVidMode.
void XMmiDp_ComputeHBlankInterval(XMmiDp *InstancePtr, u8 Stream, XVidC_ColorFormat ColorFormat)
Computes the HBlankInterval register value from the stream's HBlank, BitsPerColor, and the supplied color format, and stores the result in MsaConfig[Stream].HBlankInterval.
HBlankInterval = HBlank (pixels) x BytesPerPixel. InstancePtr is a pointer to the XMmiDp instance. Stream is the stream ID (XMMIDP_STREAM_ID1..ID4). ColorFormat is the color format (RGB, YCbCr 4:4:4/4:2:2/4:2:0). None.
Referenced by XMmiDp_SetVidControllerUseStdVidMode.
void XMmiDp_ComputeTuParams(XMmiDp *InstancePtr, u8 Stream, XVidC_ColorFormat ColorFormat)
Computes AvgBytesPerTu, AvgBytesPerTuFrac, InitThreshold, and InitThresholdHi for the VIDEO_CONFIG5 register using the stream's pixel clock, color depth, link config, and blanking parameters.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream ID (XMMIDP_STREAM_ID1..ID4). ColorFormat is the color format (RGB, YCbCr 4:4:4/4:2:2/4:2:0). None.
Referenced by XMmiDp_SetVidControllerUseStdVidMode.
void XMmiDp_SetVidControllerUseStdVidMode(XMmiDp *InstancePtr, XVidC_VideoMode VideoMode, u8 Stream, XVidC_ColorFormat ColorFormat)
Configures the video controller with standard video mode timing parameters including HActive, VActive, sync widths, blanking intervals, pixel clock, and dynamically computed MSA and transfer unit parameters.
InstancePtr is a pointer to the XMmiDp instance. VideoMode is the standard video mode to configure. Stream is the stream ID (XMMIDP_STREAM_ID1..ID4). ColorFormat is the color format (RGB, YCbCr 4:4:4/4:2:2/4:2:0). None.
References XMmiDp_ComputeHBlankInterval, XMmiDp_ComputeMisc0, XMmiDp_ComputeTuParams.
XMMIDP_CR_TIMEOUT_COUNT
XMMIDP_MAX_VSLEVEL_CNT
XMMIDP_LINK_CR_DONE_AUX_RD_INTERVAL
XMMIDP_TRAINING_AUX_RD_BASE_DELAY_US
XMMIDP_TRAINING_AUX_RD_DELAY_MULT
XMMIDP_LANE_STATUS_ADJ_REQS_SIZE
XMMIDP_EQ_MAX_ITERATIONS
XMMIDP_LINK_STATUS_MAX_RETRIES
XMMIDP_TRAINING_PATTERN_SET_SIZE
XMMIDP_AUX_MAX_DATA_WRITE_SIZE
XMMIDP_AUX_MAX_TIMEOUT_COUNT
XMMIDP_AUX_MAX_DEFER_COUNT
XMMIDP_AUX_MAX_WAIT
XMMIDP_IS_CONNECTED_MAX_TIMEOUT_COUNT
XMMIDP_AUX_REPLY_TIMEOUT_TIMER
XMMIDP_AUX_REQUEST_TIMEOUT_TIMER
XMMIDP_AUX_MAX_DATA_BYTES
XMMIDP_EDID_BLOCK_SIZE
XMmiDp_AuxDbg
XMMIDP_EDID_ADDR
XMMIDP_SEGPTR_ADDR
XMMIDP_MAX_SEGMENT_SIZE
XMMIDP_VCP_TABLE_MAX_TIMEOUT_COUNT
XMMIDP_STREAM_OFFSET
XMMIDP_TU_SIZE
XMMIDP_TU_AVG_MAX
XMMIDP_TU_FRAC_SCALE
XMMIDP_BITS_PER_BYTE
XMMIDP_MHZ_TO_HZ
XMMIDP_YCBCR420_BW_DIVISOR
XMMIDP_TU_LOW_AVG_BOUNDARY
XMMIDP_TU_THRESHOLD_LOW_AVG
XMMIDP_TU_HBLANK_NARROW_420
XMMIDP_TU_THRESHOLD_NARROW_420
XMMIDP_TU_HBLANK_NARROW
XMMIDP_TU_THRESHOLD_NARROW
XMMIDP_TU_THRESHOLD_DEFAULT
XMMIDP_INIT_THRESHOLD_LO_MASK
XMMIDP_INIT_THRESHOLD_LO_BITS
XMMIDP_INIT_THRESHOLD_HI_MASK