xmmidp_phy.c
XMMIDP_AUX_MAX_DATA_WRITE_SIZE
XMMIDP_AUX_MAX_TIMEOUT_COUNT
XMMIDP_AUX_MAX_DEFER_COUNT
XMMIDP_AUX_MAX_WAIT
XMMIDP_IS_CONNECTED_MAX_TIMEOUT_COUNT
XMMIDP_AUX_REPLY_TIMEOUT_TIMER
XMMIDP_AUX_REQUEST_TIMEOUT_TIMER
XMMIDP_AUX_MAX_DATA_BYTES
XMMIDP_EDID_BLOCK_SIZE
XMmiDp_AuxDbg
XMMIDP_EDID_ADDR
XMMIDP_SEGPTR_ADDR
XMMIDP_MAX_SEGMENT_SIZE
u8 XMmiDp_AuxDebugEnabled
void XMmiDp_WaitUs(XMmiDp *InstancePtr, u32 MicroSeconds)
This function is the delay/sleep function for the XMmiDp driver.
InstancePtr is a pointer to the XMmiDp instance. MicroSeconds is the number of microseconds to delay/sleep for. None. None.
Referenced by XMmiDp_AuxSoftReset, XMmiDp_CoreSoftResetAll, XMmiDp_InitiateActSeq, XMmiDp_IsConnected, XMmiDp_PhySoftReset, XMmiDp_PhyWaitReady, XMmiDp_SetDpcdLinkQualPattern, XMmiDp_SetDpcdTrainingPattern, XMmiDp_TrainingStateChannelEqualization, XMmiDp_TrainingStateClockRecovery, XMmiDp_WaitActHandledStatus, XMmiDp_WaitPayloadTableUpdateStatus.
static void XMmiDp_ClearAuxData(XMmiDp *InstancePtr)
This function clears the AUX_DATA registers by setting it to 0.
InstancePtr is a pointer to the XMmiDp instance. None.
static void XMmiDp_SetAuxData(XMmiDp *InstancePtr, XMmiDp_AuxTransaction *Request)
This function programs the Aux data to the AUX_DATA registers.
InstancePtr is a pointer to the XMmiDp instance. Request is a pointer to an initialized XMmiDp_AuxTransaction structure containing the required information for issuing an AUX command. None.
static u32 XMmiDp_GetAuxData(XMmiDp *InstancePtr, XMmiDp_AuxTransaction *Request)
This function reads the Aux data from AUX_DATA registers.
InstancePtr is a pointer to the XMmiDp instance. Request is a pointer to an initialized XMmiDp_AuxTransaction structure containing the required information for issuing an AUX command. None.
static u32 XMmiDp_AuxWaitReady(XMmiDp *InstancePtr)
This function waits until another request is no longer in progress.
Check if GENERAL_INTERRUPT_AUX_REPLY_EVENT bit is cleared. If not then wait. InstancePtr is a pointer to the XMmiDp instance. XST_SUCCESS if the the RX device is no longer busy.XST_ERROR_COUNT_MAX otherwise, if a timeout has occurred. None.
static u32 XMmiDp_AuxWaitReply(XMmiDp *InstancePtr)
This function waits for a reply indicating that the most recent AUX request has been received by the RX device.
InstancePtr is a pointer to the XMmiDp instance. XST_SUCCESS if a reply was sent from the RX device.XST_ERROR_COUNT_MAX otherwise, if a timeout has occurred. None.
static u32 XMmiDp_SetAuxRequest(XMmiDp *InstancePtr, XMmiDp_AuxTransaction *Request)
This function submits the supplied AUX request to the RX device over the AUX channel by writing the command, the destination address, (the write buffer for write commands), and the data size to the DisplayPort TX core.
InstancePtr is a pointer to the XMmiDp instance. Request is a pointer to an initialized XMmiDp_AuxTransaction structure containing the required information for issuing an AUX command. XST_SUCCESS if the request was acknowledged.XST_ERROR_COUNT_MAX if waiting for a reply timed out.XST_SEND_ERROR if the request was deferred.XST_FAILURE otherwise, if the request was NACK'ed. None.
void XMmiDp_CoreSoftResetAll(XMmiDp *InstancePtr)
Resets Controller, HDCP, Audio Sampler, and AUX blocks.
PHY and Video stream resets are intentionally excluded. InstancePtr is a pointer to the XMmiDp instance.
References XMmiDp_ReadReg, XMmiDp_WaitUs, XMmiDp_WriteReg.
void XMmiDp_AuxSoftReset(XMmiDp *InstancePtr)
Performs an AUX soft reset by toggling the AUX reset bit.
InstancePtr is a pointer to the XMmiDp instance. None. None.
References XMmiDp_ReadReg, XMmiDp_WaitUs, XMmiDp_WriteReg.
static u32 XMmiDp_AuxRequest(XMmiDp *InstancePtr, XMmiDp_AuxTransaction *Request)
Submits the supplied AUX request to the RX device over the AUX channel.
If waiting for a reply times out, or if the TX core indicates DEFER, the request is resent up to the configured defer/timeout retry limits. InstancePtr is a pointer to the XMmiDp instance. Request is a pointer to an initialized XMmiDp_AuxTransaction structure containing the required information for issuing an AUX command, as well as write/read buffers. XST_SUCCESS if the request was acknowledged.XST_ERROR_COUNT_MAX if resending exceeded defer/timeout limits.XST_FAILURE otherwise (for NACK or AUX transaction failure). None.
static u32 XMmiDp_AuxChanCommand(XMmiDp *InstancePtr, u32 AuxCmdType, u32 Address, u32 Bytes, u8 *Data)
This Api splits the Aux commands into multiple requests, each acting on a maximum of 16 bytes.
InstancePtr is a pointer to the XMmiDp instance. CmdType is the type of AUX command Address is the starting address that the AUX transaction will read/write from/to the RX device. NumBytes is the number of bytes to read/write from/to the RX device. Data is a pointer to the data buffer that contains the data to be read/written from/to the RX device. XST_SUCCESS if the AUX transaction request was acknowledged.XST_ERROR_COUNT_MAX if the AUX request timed out.XST_FAILURE otherwise (if the DisplayPort TX core sees a NACK reply code or if the AUX transaction failed).XST_DEVICE_NOT_FOUND if the sink is disconnected from the TX. None.
u32 XMmiDp_AuxWrite(XMmiDp *InstancePtr, u32 DpcdAddr, u32 Bytes, void *Data)
This function issues a write request over the AUX channel that will write to the RX device's DisplayPort Configuration Data (DPCD) address space.
The write message will be divided into multiple transactions which write a maximum of 16 bytes each. InstancePtr is a pointer to the XMmiDp instance. DpcdAddr is the starting address to write to the RX device. Bytes is the number of bytes to write to the RX device. Data is a pointer to the data buffer that contains the data to be written to the RX device. XST_SUCCESS if the AUX write request was successfully acknowledged.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_ERROR_COUNT_MAX if the AUX request timed out.XST_FAILURE otherwise. None.
References XMmiDp_IsConnected.
Referenced by XMmiDp_AdjVswingPreemp, XMmiDp_DpcdReadModifyWrite, XMmiDp_RunTraining, XMmiDp_SetDpcdLinkRate, XMmiDp_SetDpcdTrainingPattern, XMmiDp_SetSinkDpcdLinkCfgField, XMmiDp_SetTrainingPattern.
u32 XMmiDp_AuxRead(XMmiDp *InstancePtr, u32 DpcdAddr, u32 Bytes, void *Data)
This function issues a read request over the AUX channel that will read from the RX device's DisplayPort Configuration Data (DPCD) address space.
The read message will be divided into multiple transactions which read a maximum of 16 bytes each. InstancePtr is a pointer to the XMmiDp instance. DpcdAddress is the starting address to read from the RX device. Bytes is the number of bytes to read from the RX device. Data is a pointer to the data buffer that will be filled with read data. XST_SUCCESS if the AUX read request was successfully acknowledged.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_ERROR_COUNT_MAX if the AUX request timed out.XST_FAILURE otherwise. None.
References XMmiDp_IsConnected.
Referenced by XMmiDp_DpcdReadModifyWrite, XMmiDp_GetDpcdLaneStatusAdjReqs, XMmiDp_GetDpcdMaxDownspread, XMmiDp_GetDpcdRev, XMmiDp_GetDpcdTrainingAuxRdInterval, XMmiDp_GetRxCapabilities, XMmiDp_GetRxMaxLaneCount, XMmiDp_GetRxMaxLinkRate, XMmiDp_GetRxMstModeCap, XMmiDp_RunTraining, XMmiDp_SetDpcdTrainingPattern, XMmiDp_WaitActHandledStatus, XMmiDp_WaitPayloadTableUpdateStatus.
u32 XMmiDp_I2cWrite(XMmiDp *InstancePtr, u32 I2cAddr, u32 Bytes, void *Data)
This function performs an I2C write over the AUX channel.
InstancePtr is a pointer to the XMmiDp instance. IicAddress is the address on the I2C bus of the target device. BytesToWrite is the number of bytes to write. WriteData is a pointer to a buffer which will be used as the data source for the write. XST_SUCCESS if the I2C write has successfully completed with no errors.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_ERROR_COUNT_MAX if the AUX request timed out.XST_FAILURE otherwise. None.
References XMmiDp_IsConnected.
u32 XMmiDp_I2cRead(XMmiDp *InstancePtr, u32 I2cAddr, u16 Offset, u32 Bytes, void *Data)
This function performs an I2C read over the AUX channel.
The read message will be divided into multiple transactions if the requested data spans multiple segments. The segment pointer is automatically incremented and the offset is calibrated as needed. E.g. For an overall offset of: 128, an I2C read is done on segptr=0; offset=128.256, an I2C read is done on segptr=1; offset=0.384, an I2C read is done on segptr=1; offset=128.512, an I2C read is done on segptr=2; offset=0.etc. InstancePtr is a pointer to the XMmiDp instance. IicAddress is the address on the I2C bus of the target device. Offset is the offset at specified address of targeted I2C device that the read will start from. Bytes is the number of bytes to read. ReadData is a pointer to a buffer that will be filled with the I2C read data. XST_SUCCESS if the I2C write has successfully completed with no errors.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_ERROR_COUNT_MAX if the AUX request timed out.XST_FAILURE otherwise. None.
References XMmiDp_IsConnected.
Referenced by XMmiDp_GetEdidBlock.
void XMmiDp_RegReadModifyWrite(XMmiDp *InstancePtr, u32 RegOffset, u32 Mask, u32 Shift, u32 Val)
This helper api reads value from register, computes the new value and writes to the register.
InstancePtr is a pointer to the XMmiDp instance. Register offset to read/write values Mask value Shift value Val to be written None. None.
References XMmiDp_ReadReg, XMmiDp_WriteReg.
Referenced by XDpPSu14_DisableCctlEnhanceFraming, XDpPSu14_EnableCctlEnhanceFraming, XMmiDp_DisableVideoStream, XMmiDp_EnableVideoStream, XMmiDp_FastLinkTrainDisable, XMmiDp_FastLinkTrainEnable, XMmiDp_MstModeEnable, XMmiDp_PhyScrambleDisable, XMmiDp_PhyScrambleEnable, XMmiDp_PhySSCDisable, XMmiDp_PhySSCEnable, XMmiDp_SetPhyLaneCount, XMmiDp_SetPhyLinkRate, XMmiDp_SetPhyPowerdown, XMmiDp_SetPhyPreEmphasis, XMmiDp_SetPhyTrainingPattern, XMmiDp_SetPhyVoltageSwing, XMmiDp_SetPhyWidth, XMmiDp_SetPhyXmitDisable, XMmiDp_SetPhyXmitEnable.
u32 XMmiDp_DpcdReadModifyWrite(XMmiDp *InstancePtr, u32 DpcdReg, u32 Mask, u32 Shift, u32 Val)
This helper api reads value from DPCD, computes the new value and writes to the DPCD register.
InstancePtr is a pointer to the XMmiDp instance. Register offset to read/write values Mask value Shift value Val to be written XST_SUCCESS if AUX read and write both succeed.Error code propagated from XMmiDp_AuxRead() on read failure.Error code propagated from XMmiDp_AuxWrite() on write failure. None.
References XMmiDp_AuxRead, XMmiDp_AuxWrite.
Referenced by XMmiDp_SetDpcdLaneCount, XMmiDp_SetDpcdLinkQualPattern, XMmiDp_SetDpcdPreEmphasis, XMmiDp_SetDpcdVoltageSwing, XMmiDp_SetSinkDpcdLinkCfgField.
u8 XMmiDp_GetLaneCount(XMmiDp *InstancePtr, u8 NumLanes)
u8 XMmiDp_GetNumLanes(XMmiDp *InstancePtr, u8 LaneCount)
void XMmiDp_SetDpcdLaneCount(XMmiDp *InstancePtr)
This function sets the number of lanes to be used by the main link for both the DisplayPort TX core and the RX device.
InstancePtr is a pointer to the XMmiDp instance. LaneCount is the number of lanes to be used over the main link. None. None.
References XMmiDp_DpcdReadModifyWrite.
Referenced by XMmiDp_SetLaneCount.
void XMmiDp_SetPhyLaneCount(XMmiDp *InstancePtr, XMmiDp_PhyLanes LaneCount)
This function sets the number of lanes to be used by the main link for both the DisplayPort TX core and the RX device.
InstancePtr is a pointer to the XMmiDp instance. LaneCount is the number of lanes to be used over the main link. None. None.
References XMmiDp_RegReadModifyWrite.
Referenced by XMmiDp_SetLaneCount, XMmiDp_StartLinkXmit.
u16 XMmiDp_GetLinkRate(XMmiDp *InstancePtr, u8 LinkBW)
u8 XMmiDp_GetLinkBW(XMmiDp *InstancePtr, u8 LinkRate)
void XMmiDp_SetDpcdLinkRate(XMmiDp *InstancePtr)
This function sets the dpcd link bw to be used by the main link for both the DisplayPort TX core and the RX device.
InstancePtr is a pointer to the XDpPsu instance. LinkRate is the link rate to be used over the main link based on one of the following selects: XMMIDP_LINK_BW_SET_162GBPS = 0x06 (for a 1.62 Gbps data rate)XMMIDP_LINK_BW_SET_270GBPS = 0x0A (for a 2.70 Gbps data rate)XMMIDP_LINK_BW_SET_540GBPS = 0x14 (for a 5.40 Gbps data rate)XMMIDP_LINK_BW_SET_810GBPS = 0x1E (for a 8.10 Gbps data rate) none. None.
References XMmiDp_AuxWrite, XMMIDP_DPCD_LINK_BW_SET.
Referenced by XMmiDp_SetLinkRate.
void XMmiDp_SetPhyLinkRate(XMmiDp *InstancePtr, XMmiDp_PhyRate LinkRate)
This function sets the data rate to be used by the main link for both the DisplayPort TX core and the RX device.
InstancePtr is a pointer to the XDpPsu instance. LinkRate is the link rate to be used over the main link based on one of the following selects: XMMIDP_LINK_BW_SET_162GBPS = 0x06 (for a 1.62 Gbps data rate)XMMIDP_LINK_BW_SET_270GBPS = 0x0A (for a 2.70 Gbps data rate)XMMIDP_LINK_BW_SET_540GBPS = 0x14 (for a 5.40 Gbps data rate)XMMIDP_LINK_BW_SET_810GBPS = 0x1E (for a 8.10 Gbps data rate) none. None.
References XMmiDp_RegReadModifyWrite, XMmiDp_SetPhyWidth.
Referenced by XMmiDp_SetLinkRate, XMmiDp_StartLinkXmit.
void XMmiDp_SetDpcdLinkQualPattern(XMmiDp *InstancePtr, XMmiDp_PhyTrainingPattern Pattern)
This function sets the DPCD Link qual_0 training pattern to be used by the main link for both the DisplayPort TX core and the RX device.
InstancePtr is a pointer to the XDpPsu instance. Pattern select to be used over the main link based on one of the following selects: XMMIDP_PHY_NO_TRAIN = 0x0, XMMIDP_PHY_TPS1 = 0x1, XMMIDP_PHY_TPS2 = 0x2, XMMIDP_PHY_TPS3 = 0x3, XMMIDP_PHY_TPS4 = 0x4, XMMIDP_PHY_SYMBOL_ERR_RATE = 0x5, XMMIDP_PHY_PRBS7 = 0x6, XMMIDP_PHY_CUSTOMPAT = 0x7, XMMIDP_PHY_CP2520_PAT_1 = 0x8, XMMIDP_PHY_CP2520_PAT_2 = 0x9, none. None.
References XMmiDp_DpcdReadModifyWrite, XMmiDp_WaitUs.
void XMmiDp_SetDpcdTrainingPattern(XMmiDp *InstancePtr, XMmiDp_PhyTrainingPattern Pattern)
This function sets the DPCD training pattern to be used by the main link for both the DisplayPort TX core and the RX device.
InstancePtr is a pointer to the XDpPsu instance. Pattern select to be used over the main link based on one of the following selects: XMMIDP_PHY_NO_TRAIN = 0x0, XMMIDP_PHY_TPS1 = 0x1, XMMIDP_PHY_TPS2 = 0x2, XMMIDP_PHY_TPS3 = 0x3, XMMIDP_PHY_TPS4 = 0x4, XMMIDP_PHY_SYMBOL_ERR_RATE = 0x5, XMMIDP_PHY_PRBS7 = 0x6, XMMIDP_PHY_CUSTOMPAT = 0x7, XMMIDP_PHY_CP2520_PAT_1 = 0x8, XMMIDP_PHY_CP2520_PAT_2 = 0x9, none. None.
References XMmiDp_AuxRead, XMmiDp_AuxWrite, XMmiDp_WaitUs.
Referenced by XMmiDp_StartLinkXmit.
void XMmiDp_SetPhyTrainingPattern(XMmiDp *InstancePtr, XMmiDp_PhyTrainingPattern Pattern)
This function sets the training pattern to be used by the main link for both the DisplayPort TX core and the RX device.
InstancePtr is a pointer to the XDpPsu instance. Pattern select to be used over the main link based on one of the following selects: XMMIDP_PHY_NO_TRAIN = 0x0, XMMIDP_PHY_TPS1 = 0x1, XMMIDP_PHY_TPS2 = 0x2, XMMIDP_PHY_TPS3 = 0x3, XMMIDP_PHY_TPS4 = 0x4, XMMIDP_PHY_SYMBOL_ERR_RATE = 0x5, XMMIDP_PHY_PRBS7 = 0x6, XMMIDP_PHY_CUSTOMPAT = 0x7, XMMIDP_PHY_CP2520_PAT_1 = 0x8, XMMIDP_PHY_CP2520_PAT_2 = 0x9, none. None.
References XMmiDp_RegReadModifyWrite.
Referenced by XMmiDp_SetTrainingPattern, XMmiDp_StartLinkXmit.
static void XMmiDp_GetVoltageSwingMask(u32 Lane, u32 *VsShift, u32 *VsMask)
void XMmiDp_SetDpcdVoltageSwing(XMmiDp *InstancePtr, XMmiDp_PhyVSwing *VsLevel)
This function sets the DPCD VoltageSwing levels int the DisplayPort TX core.
InstancePtr is a pointer to the XDpPsu instance. VoltageSwing for each lane to be used over the main link based on one of the following selects: XMMIDP_PHY_VSWING_LEVEL0XMMIDP_PHY_VSWING_LEVEL1XMMIDP_PHY_VSWING_LEVEL2XMMIDP_PHY_VSWING_LEVEL3 none. None.
References XMmiDp_DpcdReadModifyWrite.
void XMmiDp_SetPhyVoltageSwing(XMmiDp *InstancePtr, u8 *VsLevel)
This function sets the VoltageSwing levels in the DisplayPort TX core.
InstancePtr is a pointer to the XDpPsu instance. VoltageSwing for each lane to be used over the main link based on one of the following selects: XMMIDP_PHY_VSWING_LEVEL0XMMIDP_PHY_VSWING_LEVEL1XMMIDP_PHY_VSWING_LEVEL2XMMIDP_PHY_VSWING_LEVEL3 none. None.
References XMmiDp_RegReadModifyWrite.
Referenced by XMmiDp_SetVswingPreemp, XMmiDp_StartLinkXmit.
static void XMmiDp_GetPreEmphasisMask(u32 Lane, u32 *PeShift, u32 *PeMask)
void XMmiDp_SetDpcdPreEmphasis(XMmiDp *InstancePtr, XMmiDp_PhyPreEmp *PeLevel)
This function sets the DPCD VoltagePreEmphasis levels for the DisplayPort TX PHY.
InstancePtr is a pointer to the XDpPsu instance. VoltageSwing for each lane to be used over the main link based on one of the following selects: PHYPREEMP_LEVEL0PHYPREEMP_LEVEL1PHYPREEMP_LEVEL2PHYPREEMP_LEVEL3 none. None.
References XMmiDp_DpcdReadModifyWrite.
void XMmiDp_SetPhyPreEmphasis(XMmiDp *InstancePtr, u8 *PeLevel)
This function sets the VoltagePreEmphasis levels for the DisplayPort TX PHY.
InstancePtr is a pointer to the XDpPsu instance. VoltageSwing for each lane to be used over the main link based on one of the following selects: XMMIDP_PHY_PREEMP_LEVEL0XMMIDP_PHY_PREEMP_LEVEL1XMMIDP_PHY_PREEMP_LEVEL2XMMIDP_PHY_PREEMP_LEVEL3 none. None.
References XMmiDp_RegReadModifyWrite.
Referenced by XMmiDp_SetVswingPreemp, XMmiDp_StartLinkXmit.
void XMmiDp_SetPhyXmitEnable(XMmiDp *InstancePtr)
This function enables phy transfer for lanes.
InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_RegReadModifyWrite.
Referenced by XMmiDp_StartLinkXmit.
void XMmiDp_SetPhyXmitDisable(XMmiDp *InstancePtr)
This function disables phy transfer for lanes.
InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_RegReadModifyWrite.
void XMmiDp_PhyScrambleEnable(XMmiDp *InstancePtr)
This function enables phy scrambler over the main link through CCTL register.
InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_RegReadModifyWrite.
Referenced by XMmiDp_SetTrainingPattern.
void XMmiDp_PhyScrambleDisable(XMmiDp *InstancePtr)
This function disable phy scrambler.
InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_RegReadModifyWrite.
Referenced by XMmiDp_SetTrainingPattern.
u32 XMmiDp_IsConnected(XMmiDp *InstancePtr)
This function checks if there is a connected RX device.
InstancePtr is a pointer to the XMmiDp instance. 1 if there is a connection.0 if there is no connection.
References XMmiDp_ReadReg, XMmiDp_WaitUs.
Referenced by XMmiDp_AuxRead, XMmiDp_AuxWrite, XMmiDp_CheckLinkStatus, XMmiDp_I2cRead, XMmiDp_I2cWrite.
void XMmiDp_CfgInitialize(XMmiDp *InstancePtr, u32 BaseAddr)
This function initializes the configuration for the XMmiDp Instance.
InstancePtr is a pointer to the XMmiDp instance. BaseAddr sets the base address of the DP instance None.
u32 XMmiDp_PhyWaitReady(XMmiDp *InstancePtr)
This function waits for the DisplayPort PHY to come out of reset.
InstancePtr is a pointer to the XMmiDp instance. XST_ERROR_COUNT_MAX if the PHY failed to be ready.XST_SUCCESS otherwise. None.
References XMmiDp_ReadReg, XMmiDp_WaitUs.
Referenced by XMmiDp_PhySoftReset, XMmiDp_SetLinkRate.
void XMmiDp_PhySoftReset(XMmiDp *InstancePtr)
This function does a PHY Soft reset.
InstancePtr is a pointer to the XMmiDp instance. Reset is the type of reset to assert. None. None.
References XMmiDp_PhyWaitReady, XMmiDp_ReadReg, XMmiDp_WaitUs, XMmiDp_WriteReg.
u32 XMmiDp_GetEdidBlock(XMmiDp *InstancePtr, u8 *Data, u8 BlockNum)
This function retrieves connected RX devices Extended Display Identification given the block number.
A block num of 0 represents the base EDID. InstancePtr is a pointer to the XMmiDp instance. Data is a pointer to the data buffer to save the block data to BlockNum is the EDID block number to retrieve. XST_SUCCESS if the block read has successfully completed with no errors.XST_ERROR_COUNT_MAX if a time out occurred while attempting to read the requested block.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_FAILURE otherwise. None.
References XMmiDp_I2cRead.
void XMmiDp_PhySSCEnable(XMmiDp *InstancePtr)
This function enables SSC on the PHY.
InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_RegReadModifyWrite.
void XMmiDp_PhySSCDisable(XMmiDp *InstancePtr)
This function disables SSC on the PHY.
InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_RegReadModifyWrite.
void XMmiDp_Initialize(XMmiDp *InstancePtr)
This function Initializes the XMmiDp Instance structure.
InstancePtr is a pointer to the XDpPsu instance. none. None.
void XMmiDp_SetPhyPowerdown(XMmiDp *InstancePtr, XMmiDp_PhyPwrDown Control)
This function sets the phy powerdown control val.
InstancePtr is a pointer to the XDpPsu instance. Powerdown val is the link rate to be used over the main link based on one of the following selects: none. None.
References XMmiDp_RegReadModifyWrite.
Referenced by XMmiDp_SetLinkRate.
void XMmiDp_SetPhyWidth(XMmiDp *InstancePtr, XMmiDp_PhyWidth Width)
This function sets the phy width control val.
InstancePtr is a pointer to the XDpPsu instance. Phy width val to be used over the main link based on one of the following selects: none. None.
References XMmiDp_RegReadModifyWrite.
Referenced by XMmiDp_SetPhyLinkRate.
void XMmiDp_SetAux_250Us_Cnt_Limit(XMmiDp *InstancePtr, u16 Limit)
This function sets the AUX_250US_CNT_LIMIT.
InstancePtr is a pointer to the XDpPsu instance. Aux 250Us count limit none. None.
References XMmiDp_WriteReg.
void XMmiDp_SetAux_2000Us_Cnt_Limit(XMmiDp *InstancePtr, u16 Limit)
This function sets the AUX_2000US_CNT_LIMIT.
InstancePtr is a pointer to the XDpPsu instance. Aux 2000Us count limit none. None.
References XMmiDp_WriteReg.
void XMmiDp_SetAux_100000Us_Cnt_Limit(XMmiDp *InstancePtr, u32 Limit)
This function sets the AUX_100000US_CNT_LIMIT.
InstancePtr is a pointer to the XDpPsu instance. Aux 100000Us count limit none. None.
References XMmiDp_WriteReg.
void XMmiDp_SetPmConfig1(XMmiDp *InstancePtr, u32 Val)
This function sets PM_COFIG1 register.
InstancePtr is a pointer to the XDpPsu instance. RegVal none. None.
References XMmiDp_WriteReg.
void XMmiDp_SetPmConfig2(XMmiDp *InstancePtr, u32 Val)
This function sets PM_COFIG2 register.
InstancePtr is a pointer to the XDpPsu instance. RegVal none. None.
References XMmiDp_WriteReg.
void XMmiDp_SetAuxDebug(u8 Enable)
This function enables or disables runtime AUX debug prints.
Enable is 1 to enable debug prints, 0 to disable. None. None.