xmmidp_stream.c
XMMIDP_VCP_TABLE_MAX_TIMEOUT_COUNT
XMMIDP_STREAM_OFFSET
XMMIDP_TU_SIZE
XMMIDP_TU_AVG_MAX
XMMIDP_TU_FRAC_SCALE
XMMIDP_BITS_PER_BYTE
XMMIDP_MHZ_TO_HZ
XMMIDP_YCBCR420_BW_DIVISOR
XMMIDP_TU_LOW_AVG_BOUNDARY
XMMIDP_TU_THRESHOLD_LOW_AVG
XMMIDP_TU_HBLANK_NARROW_420
XMMIDP_TU_THRESHOLD_NARROW_420
XMMIDP_TU_HBLANK_NARROW
XMMIDP_TU_THRESHOLD_NARROW
XMMIDP_TU_THRESHOLD_DEFAULT
XMMIDP_INIT_THRESHOLD_LO_MASK
XMMIDP_INIT_THRESHOLD_LO_BITS
XMMIDP_INIT_THRESHOLD_HI_MASK
void XMmiDp_DisableVideoStream(XMmiDp *InstancePtr, u8 Stream)
This function disables video stream.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_RegReadModifyWrite.
void XMmiDp_EnableVideoStream(XMmiDp *InstancePtr, u8 Stream)
This function enabless video stream.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_RegReadModifyWrite.
void XMmiDp_ClearMsaValues(XMmiDp *InstancePtr, u8 Stream)
This function clears MSA values.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_WriteReg.
Referenced by XMmiDp_ClearVideoController.
void XMmiDp_ClearVideoConfigValues(XMmiDp *InstancePtr, u8 Stream)
This function clears out Video Config Register values.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_WriteReg.
Referenced by XMmiDp_ClearVideoController.
void XMmiDp_SetVInputPolarityCtrl(XMmiDp *InstancePtr, u8 Stream)
This function sets the video input polarity control.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_WriteReg.
Referenced by XMmiDp_ConfigureVideoController.
void XMmiDp_SetVideoConfig1(XMmiDp *InstancePtr, u8 Stream)
This function sets the video config1 register.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMMIDP_VIDEO_CONFIG1, XMmiDp_WriteReg.
Referenced by XMmiDp_ConfigureVideoController.
void XMmiDp_SetVideoConfig2(XMmiDp *InstancePtr, u8 Stream)
This function sets the video config2 register.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_WriteReg.
Referenced by XMmiDp_ConfigureVideoController.
void XMmiDp_SetVideoConfig3(XMmiDp *InstancePtr, u8 Stream)
This function sets the video config3 register.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_WriteReg.
Referenced by XMmiDp_ConfigureVideoController.
void XMmiDp_SetVideoConfig4(XMmiDp *InstancePtr, u8 Stream)
This function sets the video config4 register.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_WriteReg.
Referenced by XMmiDp_ConfigureVideoController.
void XMmiDp_SetVideoConfig5(XMmiDp *InstancePtr, u8 Stream)
This function sets the video config5 register.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_WriteReg.
Referenced by XMmiDp_ConfigureVideoController.
void XMmiDp_SetVSampleCtrl(XMmiDp *InstancePtr, u8 Stream)
This function sets the vsample register.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_WriteReg.
Referenced by XMmiDp_ConfigureVideoController.
void XMmiDp_SetVideoMsa1(XMmiDp *InstancePtr, u8 Stream)
This function sets video msa1 register.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_WriteReg.
Referenced by XMmiDp_ConfigureVideoController.
void XMmiDp_SetVideoMsa2(XMmiDp *InstancePtr, u8 Stream)
This function sets video msa2 register.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_WriteReg.
Referenced by XMmiDp_ConfigureVideoController.
void XMmiDp_SetVideoMsa3(XMmiDp *InstancePtr, u8 Stream)
This function sets video msa3 register.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_WriteReg.
Referenced by XMmiDp_ConfigureVideoController.
void XMmiDp_SetHBlankInterval(XMmiDp *InstancePtr, u8 Stream)
This function sets video HBlankInterval register.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_WriteReg.
Referenced by XMmiDp_ConfigureVideoController.
void XMmiDp_ConfigureVideoController(XMmiDp *InstancePtr, u8 Stream)
This is helper api that programs the VideoController MSA, VideoConfig registers for a specific stream.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_SetHBlankInterval, XMmiDp_SetVideoConfig1, XMmiDp_SetVideoConfig2, XMmiDp_SetVideoConfig3, XMmiDp_SetVideoConfig4, XMmiDp_SetVideoConfig5, XMmiDp_SetVideoMsa1, XMmiDp_SetVideoMsa2, XMmiDp_SetVideoMsa3, XMmiDp_SetVInputPolarityCtrl, XMmiDp_SetVSampleCtrl.
void XMmiDp_ClearVideoController(XMmiDp *InstancePtr)
This is helper api that clears the VideoController MSA, VideoConfig registers for a specific stream.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_ClearMsaValues, XMmiDp_ClearVideoConfigValues.
void XMmiDp_SetMsaBpc(XMmiDp *InstancePtr, u8 Stream, u8 BitsPerColor)
This function sets the bits per color value of the video stream.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. BitsPerColor is the new number of bits per color to use. None.
void XMmiDp_SetPixModeSel(XMmiDp *InstancePtr, u8 Stream, XMmiDp_PPC PixModeSel)
This function sets the pixel mode of the video stream.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. PixModeSel. None.
void XMmiDp_SetVideoMapping(XMmiDp *InstancePtr, u8 Stream, XMmiDp_VidMap VidMap)
This function sets the video format of the video stream.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Video input mapping. None.
void XMmiDp_SetVidStreamEnable(XMmiDp *InstancePtr, u8 Stream, u8 StreamEnable)
This function sets the video stream to enable or disable.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Enable or Disable. None.
void XMmiDp_SetAudStreamInterfaceSel(XMmiDp *InstancePtr, u8 Stream, u8 InterfaceSel)
This function sets the audio stream interface.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Audio interface I2S or SPDIF . None.
void XMmiDp_SetAudDataInputEn(XMmiDp *InstancePtr, u8 Stream, u8 ActiveDataInput)
This function sets the active audio data input.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Active data input on different channels. None.
void XMmiDp_SetAudDataWidth(XMmiDp *InstancePtr, u8 Stream, u8 DataWidth)
This function sets the audio data width val(16 bit - 24 bit).
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Audio Data Width. None.
void XMmiDp_SetAudHbrModeEn(XMmiDp *InstancePtr, u8 Stream, u8 HbrModeEn)
This function sets the audio input is operating in HBR mode or not.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Audio HBR mode en or disable None.
void XMmiDp_SetAudNumChannels(XMmiDp *InstancePtr, u8 Stream, u8 NumChannels)
This function sets the audio num of channels used.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Audio num channels None.
void XMmiDp_SetAudMuteFlag(XMmiDp *InstancePtr, u8 Stream, u8 AudioMute)
This function controls the audio mute flag in VB-ID.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Audio mute clear or set None.
void XMmiDp_SetAudPktId(XMmiDp *InstancePtr, u8 Stream, u8 PktId)
This function defines first byte of audio SDP and audio timestamp SDP header.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Audio Packet Id None.
void XMmiDp_SetAudTimeStampVerNum(XMmiDp *InstancePtr, u8 Stream, u8 VerNum)
This function defines audio timestamp version num.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Audio timestamp version number None.
void XMmiDp_SetAudClkMultFs(XMmiDp *InstancePtr, u8 Stream, u8 ClkMultFs)
This function defines audio clock frequency multiplier in relation to audio sample rate Fs.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Audio clock frequency multiplier None.
void XMmiDp_SetAudioConfig1(XMmiDp *InstancePtr, u8 Stream)
This function programs the AUDIO_CONFIG1 registers.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. None.
References XMmiDp_WriteReg.
Referenced by XMmiDp_ConfigureAudioController.
void XMmiDp_SetSdpVertAudTimeStampEn(XMmiDp *InstancePtr, u8 Stream, u8 EnAudTimeStamp)
This function enables audio timestamp for sdp vertical ctrl.
When set, dptx sends out audio timestamp SDP once every video frame during vertical blanking period. InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Audio timestamp sdp enable/disable. None.
void XMmiDp_SetSdpVertAudStreamEn(XMmiDp *InstancePtr, u8 Stream, u8 EnAudStream)
This function enables audio stream during vertical blanking .
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Audio stream enable/disable. None.
void XMmiDp_SetSdpVertEn(XMmiDp *InstancePtr, u8 Stream, u32 EnVerticalSdp)
This function sets SDP to be sent out during vertical intervals using data from SDP_REGISTER_BANK .
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Enable SDP during vertical intervals. None.
void XMmiDp_SetSdpVertEn128Bytes(XMmiDp *InstancePtr, u8 Stream, u8 En128Bytes)
This function sets 128 bytes of SDP by using SDP_REGISTER_BANK 1,2,3 and 4.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Enable/Disable 128BytesSdp. None.
void XMmiDp_SetDisableExternalSdp(XMmiDp *InstancePtr, u8 Stream, u8 DisExternalSdp)
This function disables external SDP when set.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Enable/Disable external SDP. None.
void XMmiDp_SetSdpVertFixedPriority(XMmiDp *InstancePtr, u8 Stream, u8 EnFixedPriority)
This function sets scheduler searches for next SDP to transmit based on fixed priority.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Enable/Disable fixed priority SDP scheduler. None.
void XMmiDp_SetSdpVerticalCtrl(XMmiDp *InstancePtr, u8 Stream)
This function programs the SDP_VERTICAL_CTRL registers.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. None.
References XMmiDp_WriteReg.
Referenced by XMmiDp_ConfigureAudioController.
void XMmiDp_SetSdpHorAudTimeStampEn(XMmiDp *InstancePtr, u8 Stream, u8 EnAudTimeStamp)
This function enables audio timestamp for sdp horizontal ctrl.
When set, dptx sends out audio timestamp SDP once every video frame during horizontal blanking period. InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Audio timestamp sdp enable/disable. None.
void XMmiDp_SetSdpHorAudStreamEn(XMmiDp *InstancePtr, u8 Stream, u8 EnAudStream)
This function enables audio stream during horizontal blanking .
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Audio stream enable/disable. None.
void XMmiDp_SetSdpHorizontalEn(XMmiDp *InstancePtr, u8 Stream, u32 EnHorizontalSdp)
This function sets SDP to be sent out during horizontal intervals using data from SDP_REGISTER_BANK .
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Enable SDP during horizontal intervals. None.
void XMmiDp_SetSdpHorFixedPriority(XMmiDp *InstancePtr, u8 Stream, u8 EnFixedPriority)
This function sets scheduler searches for next SDP to transmit based on fixed priority.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Enable/Disable fixed priority SDP scheduler. None.
void XMmiDp_SetSdpHorizontalCtrl(XMmiDp *InstancePtr, u8 Stream)
This function programs the SDP_HORIZONTAL_CTRL registers.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. None.
References XMmiDp_WriteReg.
Referenced by XMmiDp_ConfigureAudioController.
void XMmiDp_ConfigureAudioController(XMmiDp *InstancePtr, u8 Stream)
This function programs DpTx Audio Controller.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. None.
References XMmiDp_SetAudioConfig1, XMmiDp_SetSdpHorizontalCtrl, XMmiDp_SetSdpVerticalCtrl.
void XMmiDp_SetSdpManualCtrl(XMmiDp *InstancePtr, u8 Stream, u32 SdpManualCtrl)
This function sets the Sdp manual mode.
Setting this bit causes corresponding SDP to be transmitted once. InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Enable/Disable Sdp Manual Ctrl None.
void XMmiDp_SetSdpCfg1HBlankOvr(XMmiDp *InstancePtr, u8 Stream, u8 SdpHBlankOvr)
This function overrides the number of available bytes required to transmit a 16 byte SDP during Horizontal blanking period.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. SdpHBlankOver None.
void XMmiDp_SetSdpCfgr2HBlankOvr(XMmiDp *InstancePtr, u8 Stream, u8 SdpHBlankOvr)
void XMmiDp_SetSdpCfgr3HBlankOvr(XMmiDp *InstancePtr, u8 Stream, u8 SdpHBlankOvr)
void XMmiDp_SetSdpCfg1VBlankOvr(XMmiDp *InstancePtr, u8 Stream, u8 SdpVBlankOvr)
This function overrides the number of available bytes required to transmit a 16 byte SDP during Vertical blanking period.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. SdpVBlankOver None.
void XMmiDp_SetSdpCfg2VBlankOvr(XMmiDp *InstancePtr, u8 Stream, u8 SdpVBlankOvr)
void XMmiDp_SetSdpCfg3VBlankOvr(XMmiDp *InstancePtr, u8 Stream, u8 SdpVBlankOvr)
void XMmiDp_SetSdpConfig(XMmiDp *InstancePtr, u8 Stream)
This function sets the SDP_CONFIG_X registers.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_WriteReg.
void XMmiDp_SetSdpRegBank(XMmiDp *InstancePtr, u8 Stream, u32 SdpReg)
This function defines the header and data for SDP.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. SdpReg None.
void XMmiDp_SetControllerScrambleDis(XMmiDp *InstancePtr, u8 Stream, u8 ScrambleDis)
This function sets the Scramble control for DpTx.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Controller enable or disable None.
void XMmiDp_SetControllerEnhanceFramingEn(XMmiDp *InstancePtr, u8 Stream, u8 EnhanceFramingEn)
This function sets the enhanced framing control for DpTx.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Controller enable or disable None.
void XMmiDp_SetControllerEnhanceFramingWithFecEn(XMmiDp *InstancePtr, u8 Stream, u8 EnhanceFramingWithFecEn)
This function sets the enhanced framing control with FEC feature for DpTx.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Controller enable or disable None.
void XMmiDp_SetControllerFastLinkTrainEn(XMmiDp *InstancePtr, u8 Stream, u8 FastLinkTrainEn)
This function sets default fast link training for DpTx.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Controller enable or disable None.
void XMmiDp_SetControllerScaleDownModeEn(XMmiDp *InstancePtr, u8 Stream, u8 ScaleDownModeEn)
This function scales down debounce filter on HPD input for DpTx.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Controller enable or disable None.
void XMmiDp_SetControllerDisableInterleaving(XMmiDp *InstancePtr, u8 Stream, u8 DisableInterleaving)
This function disables SPD nibble interleaving DpTx.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Controller enable or disable None.
void XMmiDp_SetControllerSelAuxTimeout32Ms(XMmiDp *InstancePtr, u8 Stream, u8 SelAuxTimeout32Ms)
This function sets aux reply timeout to either 400us or 3.2ms DpTx.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. 0x0 for 400us, 0x1 for 3.2ms None.
void XMmiDp_SetControllerMstModeEn(XMmiDp *InstancePtr, u8 Stream, u8 MstModeEn)
This function enables MST mode for DpTx.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Controller enable/disable None.
void XMmiDp_SetControllerFecEn(XMmiDp *InstancePtr, u8 Stream, u8 FecEn)
This function enables FEC feature for DpTx.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Controller enable/disable None.
void XMmiDp_SetControllereDpEn(XMmiDp *InstancePtr, u8 Stream, u8 eDpEn)
This function sets DpTx in eDP mode.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Controller enable/disable None.
void XMmiDp_SetControllerInitiateMstActSeq(XMmiDp *InstancePtr, u8 Stream, u8 InitiateMstActSeq)
This function use in MST mode only triggers link to start ACT sequence with DpRx of branch.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream number for which to set the color depth. Controller enable/disable None.
void XMmiDp_SetCoreCtrl(XMmiDp *InstancePtr, u8 Stream)
This function sets the core controller register.
InstancePtr is a pointer to the XDpPsu instance. Stream is the stream number for which to enable or disable video stream. None. None.
References XMmiDp_WriteReg.
void XMmiDp_MstModeEnable(XMmiDp *InstancePtr)
This function enables mst mode in the core controller.
InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_RegReadModifyWrite.
void XMmiDp_MstActSeqEnable(XMmiDp *InstancePtr)
This function enables mst act seq in the core controller.
InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_WriteReg.
Referenced by XMmiDp_InitiateActSeq.
u32 XMmiDp_WaitPayloadTableUpdateStatus(XMmiDp *InstancePtr)
This function waits for VC_PAYLOAD_TABLE_UPDATE status bit to be set.
status. This ensures successful update of VC_PAYLOAD_TABLE. InstancePtr is a pointer to the XDpPsu instance. XST_SUCCESS/XST_FAILURE. None.
References XMmiDp_AuxRead, XMmiDp_WaitUs.
u32 XMmiDp_WaitActHandledStatus(XMmiDp *InstancePtr)
This function waits for ACT_Handled status bit to be set.
status. This ensures successful handling of ACT trigger. InstancePtr is a pointer to the XDpPsu instance. XST_SUCCESS/XST_FAILURE. None.
References XMmiDp_AuxRead, XMmiDp_WaitUs.
Referenced by XMmiDp_InitiateActSeq.
u32 XMmiDp_InitiateActSeq(XMmiDp *InstancePtr)
This function initiates CCTL ACT sequence between DpTx and DpRx of the immediate branch device connected.
Check DPCD Payload table update status. This ensures successful handling of ACT trigger sequence. InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_MstActSeqEnable, XMmiDp_ReadReg, XMmiDp_WaitActHandledStatus, XMmiDp_WaitUs.
void XMmiDp_SetMstVcpTable0(XMmiDp *InstancePtr, u32 Payload)
This function sets the virtual channel payload allocation table.
InstancePtr is a pointer to the XMmiDp instance. u32 Payload slot for each stream None.
References XMmiDp_WriteReg.
void XMmiDp_SetMstVcpTable1(XMmiDp *InstancePtr, u32 Payload)
void XMmiDp_SetMstVcpTable2(XMmiDp *InstancePtr, u32 Payload)
void XMmiDp_SetMstVcpTable3(XMmiDp *InstancePtr, u32 Payload)
void XMmiDp_SetMstVcpTable4(XMmiDp *InstancePtr, u32 Payload)
void XMmiDp_SetMstVcpTable5(XMmiDp *InstancePtr, u32 Payload)
void XMmiDp_SetMstVcpTable6(XMmiDp *InstancePtr, u32 Payload)
void XMmiDp_SetMstVcpTable7(XMmiDp *InstancePtr, u32 Payload)
void XMmiDp_ComputeMisc0(XMmiDp *InstancePtr, u8 Stream, XVidC_ColorFormat ColorFormat)
Computes the MSA Misc0 field from the stream's BitsPerColor and the supplied color format, and stores the result in MsaConfig[Stream].Misc0.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream ID (XMMIDP_STREAM_ID1..ID4). ColorFormat is the color format (RGB, YCbCr 4:4:4/4:2:2). None.
Referenced by XMmiDp_SetVidControllerUseStdVidMode.
void XMmiDp_ComputeHBlankInterval(XMmiDp *InstancePtr, u8 Stream, XVidC_ColorFormat ColorFormat)
Computes the HBlankInterval register value from the stream's HBlank, BitsPerColor, and the supplied color format, and stores the result in MsaConfig[Stream].HBlankInterval.
HBlankInterval = HBlank (pixels) x BytesPerPixel. InstancePtr is a pointer to the XMmiDp instance. Stream is the stream ID (XMMIDP_STREAM_ID1..ID4). ColorFormat is the color format (RGB, YCbCr 4:4:4/4:2:2/4:2:0). None.
Referenced by XMmiDp_SetVidControllerUseStdVidMode.
void XMmiDp_ComputeTuParams(XMmiDp *InstancePtr, u8 Stream, XVidC_ColorFormat ColorFormat)
Computes AvgBytesPerTu, AvgBytesPerTuFrac, InitThreshold, and InitThresholdHi for the VIDEO_CONFIG5 register using the stream's pixel clock, color depth, link config, and blanking parameters.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream ID (XMMIDP_STREAM_ID1..ID4). ColorFormat is the color format (RGB, YCbCr 4:4:4/4:2:2/4:2:0). None.
Referenced by XMmiDp_SetVidControllerUseStdVidMode.
void XMmiDp_SetVidControllerUseStdVidMode(XMmiDp *InstancePtr, XVidC_VideoMode VideoMode, u8 Stream, XVidC_ColorFormat ColorFormat)
Configures the video controller with standard video mode timing parameters including HActive, VActive, sync widths, blanking intervals, pixel clock, and dynamically computed MSA and transfer unit parameters.
InstancePtr is a pointer to the XMmiDp instance. VideoMode is the standard video mode to configure. Stream is the stream ID (XMMIDP_STREAM_ID1..ID4). ColorFormat is the color format (RGB, YCbCr 4:4:4/4:2:2/4:2:0). None.
References XMmiDp_ComputeHBlankInterval, XMmiDp_ComputeMisc0, XMmiDp_ComputeTuParams.