xmmidp_link.c
XMMIDP_CR_TIMEOUT_COUNT
XMMIDP_MAX_VSLEVEL_CNT
XMMIDP_LINK_CR_DONE_AUX_RD_INTERVAL
XMMIDP_TRAINING_AUX_RD_BASE_DELAY_US
XMMIDP_TRAINING_AUX_RD_DELAY_MULT
XMMIDP_LANE_STATUS_ADJ_REQS_SIZE
XMMIDP_EQ_MAX_ITERATIONS
XMMIDP_LINK_STATUS_MAX_RETRIES
XMMIDP_TRAINING_PATTERN_SET_SIZE
void XMmiDp_FastLinkTrainEnable(XMmiDp *InstancePtr)
This function enables fast link training in the core controller.
InstancePtr is a pointer to the XDpPsu instance. Phy width val to be used over the main link based on one of the following selects: none. None.
References XMmiDp_RegReadModifyWrite.
void XMmiDp_FastLinkTrainDisable(XMmiDp *InstancePtr)
This function disables fast link training in the core controller.
InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_RegReadModifyWrite.
u32 XMmiDp_GetRxMaxLaneCount(XMmiDp *InstancePtr)
This function gets the max lane count supported from DPCD.
InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_AuxRead.
Referenced by XMmiDp_GetRxCapabilities.
u32 XMmiDp_GetRxMaxLinkRate(XMmiDp *InstancePtr)
This function gets the max link rate supported from Rx DPCD register.
InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_AuxRead.
Referenced by XMmiDp_GetRxCapabilities.
u32 XMmiDp_GetRxMstModeCap(XMmiDp *InstancePtr)
This function reads MST_CAP from Rx DPCD register.
InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_AuxRead, XMMIDP_DPCD_MSTM_CAP.
Referenced by XMmiDp_GetRxCapabilities.
u32 XMmiDp_StartLinkXmit(XMmiDp *InstancePtr)
This function initiates link training sequence with the Rx.
InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_SetDpcdTrainingPattern, XMmiDp_SetPhyLaneCount, XMmiDp_SetPhyLinkRate, XMmiDp_SetPhyPreEmphasis, XMmiDp_SetPhyTrainingPattern, XMmiDp_SetPhyVoltageSwing, XMmiDp_SetPhyXmitEnable.
u32 XMmiDp_SetSinkDpcdLinkCfgField(XMmiDp *InstancePtr)
This function configures DPCD Rx Field.
InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_AuxWrite, XMMIDP_DPCD_LINK_BW_SET, XMmiDp_DpcdReadModifyWrite.
void XDpPSu14_EnableCctlEnhanceFraming(XMmiDp *InstancePtr)
This function configures CCTL enhance framing enable bit.
InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_RegReadModifyWrite.
void XDpPSu14_DisableCctlEnhanceFraming(XMmiDp *InstancePtr)
This function configures CCTL enhance framing enable bit.
InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_RegReadModifyWrite.
void XMmiDp_GetDpcdTrainingAuxRdInterval(XMmiDp *InstancePtr)
This function reads Training Aux Read Interval register of sink DPCD.
InstancePtr is a pointer to the XDpPsu instance. none. None.
References XMmiDp_AuxRead.
Referenced by XMmiDp_GetRxCapabilities.
u32 XMmiDp_GetTrainingDelay(XMmiDp *InstancePtr)
This function returns the training aux interval.
The lowest time is 400us. All other WaitTimes are direct multiples of lowest time and value read from DPCD register. InstancePtr is a pointer to the XDpPsu instance. WaitTime. None.
Referenced by XMmiDp_TrainingStateChannelEqualization, XMmiDp_TrainingStateClockRecovery.
u32 XMmiDp_GetDpcdLaneStatusAdjReqs(XMmiDp *InstancePtr)
This function will do a burst AUX read from the RX device over the AUX channel.
The contents of the status registers will be stored for later use by XDp_TxCheckClockRecovery, XDp_TxCheckChannelEqualization, and XDp_TxAdjVswingPreemp. InstancePtr is a pointer to the XDp instance. XST_SUCCESS if the AUX read was successful.XST_FAILURE otherwise. None.
References XMmiDp_AuxRead.
Referenced by XMmiDp_CheckLinkStatus, XMmiDp_TrainingStateChannelEqualization, XMmiDp_TrainingStateClockRecovery.
u32 XMmiDp_CheckClockRecovery(XMmiDp *InstancePtr, u8 LaneCount)
This function checks if the RX device's DisplayPort Configuration Data (DPCD) indicates that the clock recovery sequence during link training was successful - the RX device's link clock and data recovery unit has realized and maintained the frequency lock for all lanes currently in use.
InstancePtr is a pointer to the XMmiDp instance. LaneCount is the number of lanes to check. XST_SUCCESS if the RX device's clock recovery PLL has achieved frequency lock for all lanes in use.XST_FAILURE otherwise. None.
Referenced by XMmiDp_CheckLinkStatus, XMmiDp_TrainingStateChannelEqualization, XMmiDp_TrainingStateClockRecovery.
u32 XMmiDp_AdjVswingPreemp(XMmiDp *InstancePtr)
This function reads the adjusted voltage swing and pre-emphasis level settings from the Rx DPCD register and modify the drive settings accordingly during link training.
InstancePtr is a pointer to the XDpPsu instance. XST_SUCCESS if writing the settings was successful.XST_FAILURE otherwise. None.
References XMmiDp_AuxWrite, XMmiDp_SetVswingPreemp.
Referenced by XMmiDp_TrainingStateChannelEqualization, XMmiDp_TrainingStateClockRecovery.
void XMmiDp_SetVswingPreemp(XMmiDp *InstancePtr, u8 *AuxData)
This function sets current voltage swing and pre-emphasis level settings from the LinkConfig structure to Phy and DPCD.
InstancePtr is a pointer to the XDpPsu instance. AuxData is a pointer to the array used for preparing a burst write over the AUX channel. XST_SUCCESS if writing the settings was successful.XST_FAILURE otherwise. None.
References XMmiDp_SetPhyPreEmphasis, XMmiDp_SetPhyVoltageSwing.
Referenced by XMmiDp_AdjVswingPreemp, XMmiDp_SetTrainingPattern.
u32 XMmiDp_SetTrainingPattern(XMmiDp *InstancePtr, XMmiDp_PhyTrainingPattern Pattern)
This function sets the training pattern to be used during link training for both the DisplayPort TX core and the RX device.
InstancePtr is a pointer to the XDp instance. Pattern selects the pattern to be used. XST_SUCCESS if setting the pattern was successful.XST_FAILURE otherwise. None.
References XMmiDp_AuxWrite, XMmiDp_PhyScrambleDisable, XMmiDp_PhyScrambleEnable, XMmiDp_SetPhyTrainingPattern, XMmiDp_SetVswingPreemp.
Referenced by XMmiDp_RunTraining, XMmiDp_TrainingStateChannelEqualization, XMmiDp_TrainingStateClockRecovery.
u32 XMmiDp_SetLinkRate(XMmiDp *InstancePtr, XMmiDp_PhyRate LinkRate)
This function sets the Rx Dpcd link rate as well as Phy link rate.
InstancePtr is a pointer to the XDp instance. LinkRate value to program. None None.
References XMmiDp_PhyWaitReady, XMmiDp_SetDpcdLinkRate, XMmiDp_SetPhyLinkRate, XMmiDp_SetPhyPowerdown.
Referenced by XMmiDp_TrainingStateAdjustLaneCount, XMmiDp_TrainingStateAdjustLinkRate, XMmiDp_TrainingStateClockRecovery.
void XMmiDp_SetLaneCount(XMmiDp *InstancePtr, XMmiDp_PhyLanes LaneCount)
This function sets the Rx Dpcd lane count as well as Phy lane count.
InstancePtr is a pointer to the XDp instance. LaneCount value to program. None None.
References XMmiDp_SetDpcdLaneCount, XMmiDp_SetPhyLaneCount.
Referenced by XMmiDp_TrainingStateAdjustLaneCount, XMmiDp_TrainingStateClockRecovery.
XMmiDp_TrainingState XMmiDp_TrainingStateClockRecovery(XMmiDp *InstancePtr)
This function runs the clock recovery sequence as part of link training.
The sequence is as follows: 0) Start signaling at the minimum voltage swing, pre-emphasis, and post- cursor levels. 1) Transmit training pattern 1 over the main link with symbol scrambling disabled. 2) The clock recovery loop. If clock recovery is unsuccessful after MaxIterations loop iterations, return. 2a) Wait for at least the period of time specified in the RX device's DisplayPort Configuration Data (DPCD) register, TRAINING_AUX_RD_INTERVAL. 2b) Check if all lanes have achieved clock recovery lock. If so, return. 2c) Check if the same voltage swing level has been used 5 consecutive times or if the maximum level has been reached. If so, return. 2d) Adjust the voltage swing, pre-emphasis, and post-cursor levels as requested by the RX device. 2e) Loop back to 2a. InstancePtr is a pointer to the XDp instance. The next training state: XMMIDP__TS_CHANNEL_EQUALIZATION if the clock recovery sequence completed successfully.XMMIDP__TS_FAILURE if writing the drive settings to the RX device was unsuccessful.XMMIDP__TS_ADJUST_LINK_RATE if the clock recovery sequence did not complete successfully. None.
References XMmiDp_AdjVswingPreemp, XMmiDp_CheckClockRecovery, XMmiDp_GetDpcdLaneStatusAdjReqs, XMmiDp_GetTrainingDelay, XMmiDp_SetLaneCount, XMmiDp_SetLinkRate, XMmiDp_SetTrainingPattern, XMmiDp_WaitUs.
Referenced by XMmiDp_RunTraining.
XMmiDp_TrainingState XMmiDp_TrainingStateAdjustLinkRate(XMmiDp *InstancePtr)
This function is reached if either the clock recovery or the channel equalization process failed during training.
As a result, the data rate will be downshifted, and training will be re-attempted (starting with clock recovery) at the reduced data rate. If the data rate is already at 1.62 Gbps, a downshift in lane count will be attempted. InstancePtr is a pointer to the XDp instance. The next training state: XMMIDP_TS_ADJUST_LANE_COUNT if the minimal data rate is already in use. Re-attempt training at a reduced lane count.XMMIDP_TS_CLOCK_RECOVERY otherwise. Re-attempt training. None.
References XMmiDp_SetLinkRate.
Referenced by XMmiDp_RunTraining.
XMmiDp_TrainingState XMmiDp_TrainingStateAdjustLaneCount(XMmiDp *InstancePtr)
This function is reached if either the clock recovery or the channel equalization process failed during training, and a minimal data rate of 1.62 Gbps was being used.
As a result, the number of lanes in use will be reduced, and training will be re-attempted (starting with clock recovery) at this lower lane count.Training will be re-attempted with the maximum data rate being used with the reduced lane count to train at the main link at the maximum bandwidth possible. InstancePtr is a pointer to the XDp instance. The next training state: XMMIDP_TS_FAILURE if only one lane is already in use.XMMIDP_TS_CLOCK_RECOVERY otherwise. Re-attempt training. None.
References XMmiDp_SetLaneCount, XMmiDp_SetLinkRate.
Referenced by XMmiDp_RunTraining.
void XMmiDp_GetDpcdMaxDownspread(XMmiDp *InstancePtr)
This function reads Rx DPCD MaxDownspread register bits.
InstancePtr is a pointer to the XDp instance. None None.
References XMmiDp_AuxRead.
Referenced by XMmiDp_GetRxCapabilities.
void XMmiDp_GetDpcdRev(XMmiDp *InstancePtr)
This function reads Rx DPCD revision number.
InstancePtr is a pointer to the XDp instance. None None.
References XMmiDp_AuxRead, XMMIDP_DPCD_REV.
Referenced by XMmiDp_GetRxCapabilities.
u32 XMmiDp_GetRxCapabilities(XMmiDp *InstancePtr)
This function reads Rx DPCD capability registers to initiate link training.
InstancePtr is a pointer to the XDp instance. XST_SUCCESS if the training process succeeded.XST_FAILURE otherwise. None.
References XMmiDp_AuxRead, XMmiDp_GetDpcdMaxDownspread, XMmiDp_GetDpcdRev, XMmiDp_GetDpcdTrainingAuxRdInterval, XMmiDp_GetRxMaxLaneCount, XMmiDp_GetRxMaxLinkRate, XMmiDp_GetRxMstModeCap.
u32 XMmiDp_CheckChannelEqualization(XMmiDp *InstancePtr, u8 LaneCount)
This function checks if the RX device's DisplayPort Configuration Data (DPCD) indicates that the channel equalization sequence during link training was successful - the RX device has achieved channel equalization, symbol lock, and interlane alignment for all lanes currently in use.
InstancePtr is a pointer to the XDpPsu instance. LaneCount is the number of lanes to check. XST_SUCCESS if the RX device has achieved channel equalization symbol lock, and interlane alignment for all lanes in use.XST_FAILURE otherwise. None.
Referenced by XMmiDp_CheckLinkStatus, XMmiDp_TrainingStateChannelEqualization.
XMmiDp_TrainingState XMmiDp_TrainingStateChannelEqualization(XMmiDp *InstancePtr)
This function runs the channel equalization sequence as part of link training.
The sequence is as follows: 0) Start signaling with the same drive settings used at the end of the clock recovery sequence. 1) Transmit training pattern 2 (or 3) over the main link with symbol scrambling disabled. 2) The channel equalization loop. If channel equalization is unsuccessful after 5 loop iterations, return. 2a) Wait for at least the period of time specified in the RX device's DisplayPort Configuration Data (DPCD) register, TRAINING_AUX_RD_INTERVAL. 2b) Check if all lanes have achieved channel equalization, symbol lock, and interlane alignment. If so, return. 2c) Check if the same voltage swing level has been used 5 consecutive times or if the maximum level has been reached. If so, return. 2d) Adjust the voltage swing, pre-emphasis, and post-cursor levels as requested by the RX device. 2e) Loop back to 2a. For a more detailed description of the channel equalization sequence, see section 3.5.1.2.2 of the DisplayPort 1.4a specification document. InstancePtr is a pointer to the XDp instance. The next training state: XDP_TX_TS_SUCCESS if training succeeded.XDP_TX_TS_FAILURE if writing the drive settings to the RX device was unsuccessful.XDP_TX_TS_ADJUST_LINK_RATE if, after 5 loop iterations, the channel equalization sequence did not complete successfully. None.
References XMmiDp_AdjVswingPreemp, XMmiDp_CheckChannelEqualization, XMmiDp_CheckClockRecovery, XMmiDp_GetDpcdLaneStatusAdjReqs, XMmiDp_GetTrainingDelay, XMmiDp_SetTrainingPattern, XMmiDp_WaitUs.
Referenced by XMmiDp_RunTraining.
u32 XMmiDp_CheckLinkStatus(XMmiDp *InstancePtr, u8 LaneCount)
This function checks if the Rx DisplayPort Configuration Data (DPCD) indicates the receiver has achieved and maintained clock recovery, channel equalization, symbol lock, and interlane alignment for all lanes currently in use.The DP 1.4 spec specifies checking for the above bits max 5 times before retraining link at lower link rate.
InstancePtr is a pointer to the XMmiDp instance. LaneCount is the number of lanes to check. XST_SUCCESS if the RX device has maintained clock recovery, channel equalization, symbol lock, and interlane alignment.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_FAILURE otherwise. None.
References XMmiDp_CheckChannelEqualization, XMmiDp_CheckClockRecovery, XMmiDp_GetDpcdLaneStatusAdjReqs, XMmiDp_IsConnected.
Referenced by XMmiDp_RunTraining.
u32 XMmiDp_RunTraining(XMmiDp *InstancePtr)
This function runs the link training process.
It is implemented as a state machine, with each state returning the next state. First, the clock recovery sequence will be run; if successful, the channel equalization sequence will run. If either the clock recovery or channel equalization sequence failed, the link rate or the number of lanes used will be reduced and training will be re-attempted. If training fails at the minimal data rate, 1.62 Gbps with a single lane, training will no longer re-attempt and fail. InstancePtr is a pointer to the XDp instance. XST_SUCCESS if the training process succeeded.XST_FAILURE otherwise. None.
References XMmiDp_AuxRead, XMmiDp_AuxWrite, XMmiDp_CheckLinkStatus, XMmiDp_SetTrainingPattern, XMmiDp_TrainingStateAdjustLaneCount, XMmiDp_TrainingStateAdjustLinkRate, XMmiDp_TrainingStateChannelEqualization, XMmiDp_TrainingStateClockRecovery.