tft
XTFT_AR_OFFSET
Address Reg (Video memory) Offset.
Referenced by XTft_SetFrameBaseAddr.
XTFT_CR_OFFSET
Control Register Offset.
Referenced by XTft_DisableDisplay, XTft_EnableDisplay, XTft_ScanNormal, XTft_ScanReverse.
XTFT_IESR_OFFSET
Interrupt Enable and Status Reg Offset.
Referenced by XTft_GetVsyncStatus, XTft_IntrDisable, XTft_IntrEnable.
XTFT_AR_LSB_OFFSET
Address Reg LSB (Video memory) Offset.
Referenced by XTft_SetFrameBaseAddr.
XTFT_AR_MSB_OFFSET
Address Reg MSB (Video memory) Offset.
Referenced by XTft_SetFrameBaseAddr.
XTFT_CR_TDE_MASK
TFT Display Enable Bit Mask.
Referenced by XTft_DisableDisplay, XTft_EnableDisplay.
XTFT_CR_DPS_MASK
TFT Display Scan Control Bit Mask.
Referenced by XTft_ScanNormal, XTft_ScanReverse.
XTFT_IESR_VADDRLATCH_STATUS_MASK
TFT Video Address Latch Status Bit Mask.
Referenced by TftExample, XTft_GetVsyncStatus.
XTFT_IESR_IE_MASK
TFT Interrupt Enable Mask.
Referenced by XTft_IntrDisable, XTft_IntrEnable.
u8 XTft_VidChars[96][12][96][12]
Character array of 96 characters with each character having dimensions of width 8 and height 12 pixels.
It starts with space as first character.
XTft_Config XTft_ConfigTable[][]
The configuration table for TFT devices in the table.
Each device should have an entry in this table.
XTft_Config XTft_ConfigTable[][]
The configuration table for TFT devices in the table.
Each device should have an entry in this table.
static void XTft_WriteChar(XTft *InstancePtr, u8 CharValue, u32 ColStartVal, u32 RowStartVal, u32 FgColor, u32 BgColor)
This function writes a particular character onto the screen using the character bitmap values.
InstancePtr is a pointer to the XTft instance. CharValue is the value of the ASCII character. ColStartVal is the value of the starting column. The valid values are 0 to (XTFT_DISPLAY_WIDTH - 1). RowStartVal is the value of the starting row. The valid values are 0 to (XTFT_DISPLAY_HEIGHT - 1). FgColor is the value with which the pixels will be filled to highlight the character. BgColor is the value with which the pixels will be filled with a different color from foreground. None. It must be taken care that the ASCII character which is to be written has value greater than 31 as character bitmap array starts with space as its first character.
int XTft_CfgInitialize(XTft *InstancePtr, XTft_Config *ConfigPtr, UINTPTR EffectiveAddr)
This function initializes a TFT Driver Instance.
InstancePtr is a pointer to the XTft instance. ConfigPtr is a pointer to a XTft_Config configuration structure.This structure will contain the requested configuration for the device. Typically, this is a local structure and the content of which will be copied into the configuration structure within XTft. EffectiveAddr is the device base address in the virtual memory address space. If the address translation is not used then the physical address is passed. Unexpected errors may occur if the address mapping is changed after this function is invoked. XST_SUCCESS if successful.XST_FAILURE if unsuccessful. None.
References XTft_Config::BaseAddress, XTft::BgColor, XTft::ColVal, XTft::FgColor, XTft::IsReady, XTft::RowVal, XTft::TftConfig, XTft_Config::VideoMemBaseAddr, XTFT_DEF_BGCOLOR, XTFT_DEF_COLVAL, XTFT_DEF_FGCOLOR, XTFT_DEF_ROWVAL, XTFT_DISPLAY_HEIGHT, XTFT_DISPLAY_WIDTH, XTft_FillScreen.
Referenced by TftExample.
void XTft_SetPos(XTft *InstancePtr, u32 ColVal, u32 RowVal)
This function updates the column, row position in the Instance structure of driver.
InstancePtr is a pointer to the XTft instance. ColVal is the column number to which ColVal member of Instance structure is updated. The valid values are 0 to (XTFT_DISPLAY_WIDTH - 1). RowVal is the row number to which RowVal member of Instance structure is updated. The valid values are 0 to (XTFT_DISPLAY_HEIGHT - 1). None. None.
References XTft::ColVal, XTft::IsReady, XTft::RowVal, XTFT_DISPLAY_HEIGHT, XTFT_DISPLAY_WIDTH.
Referenced by XTft_Write.
void XTft_SetPosChar(XTft *InstancePtr, u32 ColVal, u32 RowVal)
This function changes the column, row position in the Instance structure of driver.
It is used to correct the position for the next character to be written if column and row position cross limits. InstancePtr is a pointer to the XTft instance. ColVal is the column number to which ColVal member of Instance structure is updated. If ColVal crosses (XTFT_DISPLAY_WIDTH - 1) - XTFT_CHAR_WIDTH, position is moved to next line. The valid values are 0 to (XTFT_DISPLAY_WIDTH - 1). RowVal is the row number to which RowVal member of Instance structure is updated. If RowVal crosses (XTFT_DISPLAY_HEIGHT - 1)- XTFT_CHAR_HEIGHT, the first line will be deleted. The valid values are 0 to (XTFT_DISPLAY_HEIGHT - 1). None. This function differs from the function XTft_SetPos because you cannot move to any position on the screen as we have to check for enough space for a character to be written.
References XTft::ColVal, XTft::IsReady, XTft::RowVal, XTFT_CHAR_HEIGHT, XTFT_CHAR_WIDTH, XTFT_DEF_COLVAL, XTFT_DISPLAY_HEIGHT, XTFT_DISPLAY_WIDTH, XTft_Scroll.
Referenced by XTft_Write.
void XTft_SetColor(XTft *InstancePtr, u32 FgColor, u32 BgColor)
This function changes the color values in the instance structure of driver.
InstancePtr is a pointer to the XTft instance. FgColor is the color with which member FgColor of Instance structure is updated. BgColor is the color with which member BgColor of Instance structure is updated. None. Color Values must be 32bit. They can range from 0x0 to 0xFFFFFFFF, out of these only 18 bits are valid data. These 18 bits contain the Red, Green, Blue color values with 6 bits each and bit positions as Red[8-13], Green[16-21], Blue[24-29].
References XTft::BgColor, XTft::FgColor, XTft::IsReady.
Referenced by TftExample.
void XTft_SetPixel(XTft *InstancePtr, u32 ColVal, u32 RowVal, u32 PixelVal)
This function sets the pixel with the given color at the given column, row position.
InstancePtr is a pointer to the XTft instance. ColVal represents the column on the screen. The valid values are 0 to (XTFT_DISPLAY_WIDTH - 1). RowVal represents the row on the screen. The valid values are 0 to (XTFT_DISPLAY_HEIGHT - 1). PixelVal represents the color with which it will be filled on screen. None. This API is independent of the interface the TFT Controller is connected to. The data is written to the Video Memory.
References XTft::IsReady, XTft::TftConfig, XTft_Config::VideoMemBaseAddr, XTFT_DISPLAY_BUFFER_WIDTH, XTFT_DISPLAY_HEIGHT, XTFT_DISPLAY_WIDTH.
Referenced by XTft_FillScreen, XTft_Scroll.
void XTft_GetPixel(XTft *InstancePtr, u32 ColVal, u32 RowVal, u32 *PixelVal)
This function gets the color of the pixel at the given column, row position.
InstancePtr is a pointer to the XTft instance. ColVal represents the column on the screen. The valid values are 0 to (XTFT_DISPLAY_WIDTH - 1). RowVal represents the row on the screen. The valid values are 0 to (XTFT_DISPLAY_HEIGHT - 1). PixelVal stores the color value on the screen pointed by given Column and Row position. None. This API is independent of the interface the TFT Controller is connected to. The data is read from the Video Memory.
References XTft::IsReady, XTft::TftConfig, XTft_Config::VideoMemBaseAddr, XTFT_DISPLAY_BUFFER_WIDTH, XTFT_DISPLAY_HEIGHT, XTFT_DISPLAY_WIDTH.
Referenced by XTft_Scroll.
void XTft_Write(XTft *InstancePtr, u8 CharValue)
This function performs one of the following three operations based on the CharValue passed :
Move the position to the next line at the same position.Move the position to the next line.Write a particular character and update the column position by the width of the character. InstancePtr is a pointer to the XTft instance. CharValue is the ASCII code value of the character to be written. None. As the character bitmap array does not support some of the ASCII values, to support some of those which carry significance in display are added in the switch case. If there is a necessity for any other characters, it can be added here.
References XTft::BgColor, XTft::ColVal, XTft::FgColor, XTft::IsReady, XTft::RowVal, XTFT_CHAR_HEIGHT, XTFT_CHAR_WIDTH, XTFT_DEF_COLVAL, XTft_SetPos, XTft_SetPosChar.
Referenced by TftExample.
void XTft_Scroll(XTft *InstancePtr)
This function inserts a new blank line at the bottom of the screen, it deletes the first line and moves the remaining lines up by one line.
InstancePtr is a pointer to the XTft instance. None. None.
References XTft::BgColor, XTft::IsReady, XTFT_CHAR_HEIGHT, XTFT_DEF_COLVAL, XTFT_DISPLAY_HEIGHT, XTFT_DISPLAY_WIDTH, XTft_FillScreen, XTft_GetPixel, XTft_SetPixel.
Referenced by TftExample, XTft_SetPosChar.
void XTft_ClearScreen(XTft *InstancePtr)
This function re-initializes all the pixels to the default background color.
InstancePtr is a pointer to the XTft instance. None. None.
References XTft::BgColor, XTft::ColVal, XTft::IsReady, XTft::RowVal, XTFT_DEF_COLVAL, XTFT_DEF_ROWVAL, XTFT_DISPLAY_HEIGHT, XTFT_DISPLAY_WIDTH, XTft_FillScreen.
Referenced by TftExample.
void XTft_FillScreen(XTft *InstancePtr, u32 ColStartVal, u32 RowStartVal, u32 ColEndVal, u32 RowEndVal, u32 PixelVal)
This function fills the screen with the range defined by the start and end values of column and row with the color passed as argument.
InstancePtr is a pointer to the XTft instance. ColStartVal is the value of the starting column. The valid values are 0 to (XTFT_DISPLAY_WIDTH - 1). RowStartVal is the value of the starting row. The valid values are 0 to (XTFT_DISPLAY_HEIGHT - 1). ColEndVal is the value of the ending column. The valid values are 0 to (XTFT_DISPLAY_WIDTH - 1). RowEndVal is the value of the ending row. The valid values are 0 to (XTFT_DISPLAY_HEIGHT - 1). PixelVal represents the color with which it will be filled on screen. None. It must be taken care to pass values such that column start position should not exceed column end position, same is the case with row position.
References XTft::IsReady, XTFT_DISPLAY_HEIGHT, XTFT_DISPLAY_WIDTH, XTft_SetPixel.
Referenced by XTft_CfgInitialize, XTft_ClearScreen, XTft_Scroll.
void XTft_EnableDisplay(XTft *InstancePtr)
This function enables the TFT display by setting the Display Enable bit in the Control register.
InstancePtr is a pointer to the XTft instance. None. None.
References XTft::IsReady, XTFT_CR_OFFSET, XTFT_CR_TDE_MASK, XTft_ReadReg, XTft_WriteReg.
Referenced by TftExample.
void XTft_DisableDisplay(XTft *InstancePtr)
This function disables the TFT display by clearing the Display Enable bit in the Control register.
InstancePtr is a pointer to the XTft instance. None. None.
References XTft::IsReady, XTFT_CR_OFFSET, XTFT_CR_TDE_MASK, XTft_ReadReg, XTft_WriteReg.
Referenced by TftExample.
void XTft_ScanReverse(XTft *InstancePtr)
This function enables reverse scan by setting the Display Scan Control(DPS) bit in the Control register.
InstancePtr is a pointer to the XTft instance. None. By default the scan direction is reverse, the image we see in reverse scan mode is the horizontal and vertical mirror image of the image in normal scan mode.
References XTft::IsReady, XTFT_CR_DPS_MASK, XTFT_CR_OFFSET, XTft_ReadReg, XTft_WriteReg.
void XTft_ScanNormal(XTft *InstancePtr)
This function enables normal scan by clearing the Display Scan Control(DPS) bit in the Control register.
InstancePtr is a pointer to the XTft instance. None. None.
References XTft::IsReady, XTFT_CR_DPS_MASK, XTFT_CR_OFFSET, XTft_ReadReg, XTft_WriteReg.
void XTft_SetFrameBaseAddr(XTft *InstancePtr, UINTPTR NewFrameBaseAddr)
This function changes the Video Memory Base address stored in the Address Register.
InstancePtr is a pointer to the XTft instance. NewFrameBaseAddr is the new memory address value to be written to the Address register. None. The new memory address must be in the address range of external memory and it must be taken care that 2MB memory is available from this new address so that frame data to 640*480 screen can be written.
References XTft_Config::AddrWidth, XTft::IsReady, XTft::TftConfig, XTft_Config::VideoMemBaseAddr, XTFT_AR_LSB_OFFSET, XTFT_AR_MSB_OFFSET, XTFT_AR_OFFSET, XTft_WriteReg.
Referenced by TftExample.
void XTft_WriteReg(XTft *InstancePtr, u32 RegOffset, u32 Data)
Write a value to a TFT register.
A 32 bit write is performed. InstancePtr is a pointer to the XTft instance. RegOffset is the register offset from the base to write to. Data is the data written to the register. None. None.
References XTft_Config::BaseAddress, XTft::IsReady, XTft::TftConfig.
Referenced by XTft_DisableDisplay, XTft_EnableDisplay, XTft_IntrDisable, XTft_IntrEnable, XTft_ScanNormal, XTft_ScanReverse, XTft_SetFrameBaseAddr.
u32 XTft_ReadReg(XTft *InstancePtr, u32 RegOffset)
Read a value from a TFT register.
A 32 bit read is performed. InstancePtr is a pointer to the XTft instance. RegOffset is the register offset from the base to read from. Data read from the register. None.
References XTft_Config::BaseAddress, XTft::IsReady, XTft::TftConfig.
Referenced by XTft_DisableDisplay, XTft_EnableDisplay, XTft_GetVsyncStatus, XTft_IntrDisable, XTft_IntrEnable, XTft_ScanNormal, XTft_ScanReverse.
void XTft_IntrEnable(XTft *InstancePtr)
This function enables the Vsync Interrupt in the Interrupt Enable and Status Register.
InstancePtr is a pointer to the XTft instance. None. None.
References XTft::IsReady, XTFT_IESR_IE_MASK, XTFT_IESR_OFFSET, XTft_ReadReg, XTft_WriteReg.
void XTft_IntrDisable(XTft *InstancePtr)
This function disables the Vsync Interrupt in the Interrupt Enable and Status Register.
InstancePtr is a pointer to the XTft instance. None. None.
References XTft::IsReady, XTFT_IESR_IE_MASK, XTFT_IESR_OFFSET, XTft_ReadReg, XTft_WriteReg.
int XTft_GetVsyncStatus(XTft *InstancePtr)
This function gets the Vsync(Video address latch) status from the Interrupt Enable and Status Register.
InstancePtr is a pointer to the XTft instance. TRUE if Vsync pulse has occurred after displaying the current frame.FALSE if the TFT core has not completed displaying the current frame. Vsync(Video address latch) Status bit will be cleared by the HW after it loads the address from the Address Register and starts displaying the Frame.
References XTft::IsReady, XTFT_IESR_OFFSET, XTFT_IESR_VADDRLATCH_STATUS_MASK, XTft_ReadReg.
Referenced by TftExample.
XTft_Config * XTft_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XTft_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xtft.h for the definition of XTft_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XTft_Config::Name.
Referenced by TftExample.
XTFT_H
XTFT_ASCIICHAR_OFFSET
As the first bitmap available in the Character Bitmap array is "space" whose value is 32 in the ASCII character table, this offset enables us to move to this first character in the array.
To achieve this we subtract this offset from the char value actually received to the XTft_WriteChar function. Similarly to move to any other character this offset must be subtracted.
XTFT_DEF_FGCOLOR
The default color is white for foreground and black for background.
These values can range from 0 to 0xFFFFFFFF as each color is ranging from 0 to 3F. The default value for column and row is 0.Foreground Color - White
Referenced by XTft_CfgInitialize.
XTFT_DEF_BGCOLOR
Background Color - Black.
Referenced by XTft_CfgInitialize.
XTFT_DEF_COLVAL
Default Column Value.
Referenced by XTft_CfgInitialize, XTft_ClearScreen, XTft_Scroll, XTft_SetPosChar, XTft_Write.
XTFT_DEF_ROWVAL
Default Row Value.
Referenced by XTft_CfgInitialize, XTft_ClearScreen.
XTFT_CHARCODE_H
GenPixels
Compression method for the character bitmaps.
a7 is bit value at 8th position. a6 is bit value at 7th position. a5 is bit value at 6th position. a4 is bit value at 5th position. a3 is bit value at 4th position. a2 is bit value at 3rd position. a1 is bit value at 2nd position. a0 is bit value at 1st position. Bit Value - either 0 or 1. C-style signature: int GenPixels(int a7, int a6, int a5, int a4, int a3, int a2, int a1, int a0).
XTFT_HW_H
XTFT_CHAR_WIDTH
Dimension Definitions.
Character width
Referenced by XTft_SetPosChar, XTft_Write.
XTFT_CHAR_HEIGHT
Character height.
Referenced by XTft_Scroll, XTft_SetPosChar, XTft_Write.
XTFT_DISPLAY_WIDTH
Width of the screen.
Referenced by XTft_CfgInitialize, XTft_ClearScreen, XTft_FillScreen, XTft_GetPixel, XTft_Scroll, XTft_SetPixel, XTft_SetPos, XTft_SetPosChar.
XTFT_DISPLAY_HEIGHT
Height of the screen.
Referenced by XTft_CfgInitialize, XTft_ClearScreen, XTft_FillScreen, XTft_GetPixel, XTft_Scroll, XTft_SetPixel, XTft_SetPos, XTft_SetPosChar.
XTFT_DISPLAY_BUFFER_WIDTH
Buffer width of a line.
Referenced by XTft_GetPixel, XTft_SetPixel.
XTFT_DCR_REG_SHIFT
Reg Shift for DCR Access.