vprocss
XVPROCSS_VDMA_CH_UPDATE
XVprocSs_Config XVprocSs_ConfigTable[][]
void XVprocSs_VdmaStart(XVprocSs *XVprocSsPtr)
This Function Starts the VDMA (Video Direct Memory Access) engine for the given Video Processing Subsystem instance.
This function initiates both the write and read channels of the VDMA associated with the specified XVprocSs instance. It checks if the VDMA pointer is valid before starting the DMA operations. XVprocSsPtr Pointer to the XVprocSs instance containing the VDMA configuration.
References XVprocSs::VdmaPtr.
void XVprocSs_VdmaStop(XVprocSs *XVprocSsPtr)
This Function Stops the VDMA (Video Direct Memory Access) engine for the given Video Processing Subsystem instance.
This function stops both the write and read channels of the VDMA associated with the specified XVprocSs instance. It checks if the VDMA pointer is valid before starting the DMA operations. XVprocSsPtr Pointer to the XVprocSs instance containing the VDMA configuration.
References XVprocSs::VdmaPtr.
Referenced by XVprocSs_Stop.
void XVprocSs_VdmaReset(XVprocSs *XVprocSsPtr)
This function resets Read and Write channels.
XVprocSsPtr is the pointer to the VPSS instance
References XVprocSs::VdmaPtr, XVPROCSS_EVT_OPERR_VDMA, XVprocSs_LogWrite.
Referenced by XVprocSs_Reset.
int XVprocSs_VdmaWriteSetup(XVprocSs *XVprocSsPtr, UINTPTR WrBaseAddress, XVidC_VideoWindow *window, u32 FrameWidth, u32 FrameHeight, u32 PixelWidthInBits)
This function sets up the write channel.
XVprocSsPtr is the pointer to the VPSS instance. WrBaseAddress is the address in DDR where frame buffers are located window is pointer to sub-frame window FrameWidth is the active width of the stream to be written FrameHeight is the active height of the stream to be written PixelWidthInBits is Bits Per Pixel required for the stream XST_SUCCESS if the setup is successful, XST_FAILURE otherwise.
References XVprocSs::VdmaPtr, XVPROCSS_EVT_CFGERR_VDMA, XVprocSs_LogWrite.
Referenced by XVprocSs_VdmaSetWinToDnScaleMode, XVprocSs_VdmaSetWinToUpScaleMode.
int XVprocSs_VdmaReadSetup(XVprocSs *XVprocSsPtr, UINTPTR RdBaseAddress, XVidC_VideoWindow *window, u32 FrameWidth, u32 FrameHeight, u32 PixelWidthInBits)
This function sets up the read channel.
XVprocSsPtr is the pointer to the VPSS instance. RdBaseAddress is the address in DDR where frame buffers are located window is pointer to sub-frame window FrameWidth is the active width of the stream to be read FrameHeight is the active height of the stream to be read PixelWidthInBits is Bits Per Pixel required for the stream XST_SUCCESS if the setup is successful, XST_FAILURE otherwise. None.
References XVprocSs::VdmaPtr, XVPROCSS_EVT_CFGERR_VDMA, XVprocSs_LogWrite.
Referenced by XVprocSs_VdmaSetWinToDnScaleMode, XVprocSs_VdmaSetWinToUpScaleMode.
int XVprocSs_VdmaStartTransfer(XVprocSs *XVprocSsPtr)
This function starts the transfer on Read/Write channels.
Both channels must have been configured before this call is made XVprocSsPtr is the pointer to the VPSS instance. XST_SUCCESS if the setup is successful, XST_FAILURE otherwise. Currently the return value is ignored at subsystem level.
References XVprocSs::VdmaPtr, XVPROCSS_EVT_OPERR_VDMA, XVprocSs_LogWrite.
Referenced by XVprocSs_Start, XVprocSs_UpdateZoomPipWindow.
void XVprocSs_VdmaSetWinToDnScaleMode(XVprocSs *XVprocSsPtr, u32 updateCh)
This function configures the VDMA RD/WR channel for down scale mode.
XVprocSsPtr is the pointer to the VPSS instance. updateCh defines VDMA channel (RD/WR or RD+WR) to update
References XVprocSs::CtxtData, XVprocSs::FrameBufBaseaddr, XVprocSs_ContextData::PixelWidthInBits, XVprocSs::VidOut, XVprocSs_GetZoomPipWindow, XVprocSs_IsPipModeOn, XVprocSs_VdmaReadSetup, XVprocSs_VdmaWriteSetup.
Referenced by XVprocSs_SetupRouterDataFlow, XVprocSs_UpdateZoomPipWindow.
void XVprocSs_VdmaSetWinToUpScaleMode(XVprocSs *XVprocSsPtr, u32 updateCh)
This function configures the VDMA RD/WR channel for UP scale (or 1:1) mode.
XVprocSsPtr is the pointer to the VPSS instance. updateCh defines VDMA channel (RD/WR or RD+WR) to update
References XVprocSs::CtxtData, XVprocSs::FrameBufBaseaddr, XVprocSs_ContextData::PixelWidthInBits, XVprocSs_ContextData::VidInHeight, XVprocSs_ContextData::VidInWidth, XVprocSs_GetZoomPipWindow, XVprocSs_IsZoomModeOn, XVprocSs_VdmaReadSetup, XVprocSs_VdmaWriteSetup.
Referenced by XVprocSs_SetupRouterDataFlow, XVprocSs_UpdateZoomPipWindow.
void XVprocSs_VdmaDbgReportStatus(XVprocSs *XVprocSsPtr, u32 PixelWidthInBits)
XVprocSs_VdmaDbgReportStatus - Used for reporting the status of the VDMA IP.
This function prints debug information about the current status of the VDMA (Video Direct Memory Access) associated with the given XVprocSs instance. It reports both the read and write channel settings, including height, width, and stride, with values interpreted according to the specified pixel width in bits. The function also clears DMA channel errors and dumps relevant register values for both channels. XVprocSsPtr : Pointer to the XVprocSs instance containing the VDMA pointer. PixelWidthInBits : The width of a pixel in bits, used to calculate bytes per pixel and interpret register values.
References XVprocSs::VdmaPtr.
Referenced by XVprocSs_ReportSubcoreStatus.
int XVprocSs_SubcoreInitResetAxis(XVprocSs *XVprocSsPtr)
This function initializes the included sub-core to it's static configuration.
XVprocSsPtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS/XST_FAILURE
References XVprocSs_Config::BaseAddress, XVprocSs::Config, XVprocSs_Config::HighAddress, XVprocSs_Config::RstAxis, XVprocSs::RstAxisPtr, XVPROCSS_EVT_INIT_RESAXIS, XVprocSs_LogWrite.
Referenced by XVprocSs_CfgInitialize.
int XVprocSs_SubcoreInitResetAximm(XVprocSs *XVprocSsPtr)
This function initializes the included sub-core to it's static configuration.
XVprocSsPtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS/XST_FAILURE
References XVprocSs_Config::BaseAddress, XVprocSs::Config, XVprocSs_Config::HighAddress, XVprocSs_Config::RstAximm, XVprocSs::RstAximmPtr, XVPROCSS_EVT_INIT_RESAXIM, XVprocSs_LogWrite.
Referenced by XVprocSs_CfgInitialize.
int XVprocSs_SubcoreInitRouter(XVprocSs *XVprocSsPtr)
This function initializes the included sub-core to it's static configuration.
XVprocSsPtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS/XST_FAILURE
References XVprocSs_Config::BaseAddress, XVprocSs::Config, XVprocSs_Config::HighAddress, XVprocSs_Config::Router, XVprocSs::RouterPtr, XVPROCSS_EVT_INIT_ROUTER, XVprocSs_LogWrite.
Referenced by XVprocSs_CfgInitialize.
int XVprocSs_SubcoreInitCsc(XVprocSs *XVprocSsPtr)
This function initializes the included sub-core to it's static configuration.
XVprocSsPtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS/XST_FAILURE
References XVprocSs_Config::BaseAddress, XVprocSs::Config, XVprocSs_Config::Csc, XVprocSs::CscPtr, XVprocSs_Config::HighAddress, XVPROCSS_EVT_CFG_CSC, XVprocSs_LogWrite.
Referenced by XVprocSs_CfgInitialize.
int XVprocSs_SubcoreInitHScaler(XVprocSs *XVprocSsPtr)
This function initializes the included sub-core to it's static configuration.
XVprocSsPtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS/XST_FAILURE
References XVprocSs_Config::BaseAddress, XVprocSs::Config, XVprocSs_Config::HighAddress, XVprocSs_Config::Hscale, XVprocSs::HscalerPtr, XVPROCSS_EVT_CFG_HSCALER, XVprocSs_LogWrite.
Referenced by XVprocSs_CfgInitialize.
int XVprocSs_SubcoreInitVScaler(XVprocSs *XVprocSsPtr)
This function initializes the included sub-core to it's static configuration.
XVprocSsPtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS/XST_FAILURE
References XVprocSs_Config::BaseAddress, XVprocSs::Config, XVprocSs_Config::HighAddress, XVprocSs_Config::Vscale, XVprocSs::VscalerPtr, XVPROCSS_EVT_CFG_VSCALER, XVprocSs_LogWrite.
Referenced by XVprocSs_CfgInitialize.
int XVprocSs_SubcoreInitHCrsmplr(XVprocSs *XVprocSsPtr)
This function initializes the included sub-core to it's static configuration.
XVprocSsPtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS/XST_FAILURE
References XVprocSs_Config::BaseAddress, XVprocSs::Config, XVprocSs_Config::HCrsmplr, XVprocSs::HcrsmplrPtr, XVprocSs_Config::HighAddress, XVPROCSS_EVT_CFG_HCR, XVprocSs_LogWrite.
Referenced by XVprocSs_CfgInitialize.
int XVprocSs_SubcoreInitVCrsmpleIn(XVprocSs *XVprocSsPtr)
This function initializes the included sub-core to it's static configuration.
XVprocSsPtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS/XST_FAILURE
References XVprocSs_Config::BaseAddress, XVprocSs::Config, XVprocSs_Config::HighAddress, XVprocSs_Config::VCrsmplrIn, XVprocSs::VcrsmplrInPtr, XVPROCSS_EVT_CFG_VCRI, XVprocSs_LogWrite.
Referenced by XVprocSs_CfgInitialize.
int XVprocSs_SubcoreInitVCrsmpleOut(XVprocSs *XVprocSsPtr)
This function initializes the included sub-core to it's static configuration.
XVprocSsPtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS/XST_FAILURE
References XVprocSs_Config::BaseAddress, XVprocSs::Config, XVprocSs_Config::HighAddress, XVprocSs_Config::VCrsmplrOut, XVprocSs::VcrsmplrOutPtr, XVPROCSS_EVT_CFG_VCRO, XVprocSs_LogWrite.
Referenced by XVprocSs_CfgInitialize.
int XVprocSs_SubcoreInitLetterbox(XVprocSs *XVprocSsPtr)
This function initializes the included sub-core to it's static configuration.
XVprocSsPtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS/XST_FAILURE
References XVprocSs_Config::BaseAddress, XVprocSs::Config, XVprocSs_Config::HighAddress, XVprocSs_Config::Lbox, XVprocSs::LboxPtr, XVPROCSS_EVT_INIT_LBOX, XVprocSs_LogWrite.
Referenced by XVprocSs_CfgInitialize.
int XVprocSs_SubcoreInitVdma(XVprocSs *XVprocSsPtr)
This function initializes the included sub-core to it's static configuration.
XVprocSsPtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS/XST_FAILURE
References XVprocSs_Config::BaseAddress, XVprocSs::Config, XVprocSs_Config::HighAddress, XVprocSs_Config::Vdma, XVprocSs::VdmaPtr, XVPROCSS_EVT_INIT_VDMA, XVprocSs_LogWrite.
Referenced by XVprocSs_CfgInitialize.
int XVprocSs_SubcoreInitDeinterlacer(XVprocSs *XVprocSsPtr)
This function initializes the included sub-core to it's static configuration.
XVprocSsPtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS/XST_FAILURE
References XVprocSs_Config::BaseAddress, XVprocSs::Config, XVprocSs_Config::Deint, XVprocSs::DeintPtr, XVprocSs_Config::HighAddress, XVPROCSS_EVT_CFG_DEINT, XVprocSs_LogWrite.
Referenced by XVprocSs_CfgInitialize.
static int validateWindowSize(const XVidC_VideoWindow *win, const u32 HActive, const u32 VActive)
This function checks to make sure sub-frame is inside full frame.
win is a pointer to the sub-frame window HActive is frame width VActive is frame height XST_SUCCESS if window is valid else XST_FAILURE
static XVprocSs_ScaleMode GetScalingMode(XVprocSs *XVprocSsPtr)
This function computes the scaling mode based on input/output stream resolution.
It also accounts for Zoom or PIP mode, if enabled XVprocSsPtr is a pointer to the Subsystem instance to be worked on. Scaling mode Up/Dpwn or 1:1
int XVprocSs_BuildRoutingTable(XVprocSs *XVprocSsPtr)
This function examines the subsystem Input/Output Stream configuration and builds a routing table for the supported use-case.
The computed routing table is stored in the scratch pad memory XVprocSsPtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS if routing table can be created else XST_FAILURE
References XVprocSs_ContextData::CscIn, XVprocSs_ContextData::CscOut, XVprocSs::CtxtData, XVprocSs_ContextData::HcrIn, XVprocSs_ContextData::HcrOut, XVprocSs_ContextData::RtngTable, XVprocSs_ContextData::RtrNumCores, XVprocSs_ContextData::ScaleMode, XVprocSs_ContextData::StrmCformat, XVprocSs::VdmaPtr, XVprocSs::VidIn, XVprocSs_ContextData::VidInHeight, XVprocSs_ContextData::VidInWidth, XVprocSs::VidOut, XVPROCSS_EVT_CFG_MAX, XVprocSs_LogWrite.
void XVprocSs_ProgRouterMux(XVprocSs *XVprocSsPtr)
This function traverses the computed routing table and sets up the AXIS switch registers, to route the stream through processing cores, in the order defined in the routing map.
XVprocSsPtr is a pointer to the Subsystem instance to be worked on.
References XVprocSs::CtxtData, XVprocSs::RouterPtr, XVprocSs_ContextData::RtngTable, XVprocSs_ContextData::RtrNumCores, XVPROCSS_EVT_CFG_MAX, XVprocSs_LogWrite.
void XVprocSs_SetupRouterDataFlow(XVprocSs *XVprocSsPtr)
This function traverses the routing map built earlier and configures each sub-core in the processing path per its location in the chain.
Each core in the processing path is marked and only marked cores are started All remaining cores stay disabled XVprocSsPtr is a pointer to the Subsystem instance to be worked on.
References XVprocSs_ContextData::CscIn, XVprocSs_ContextData::CscOut, XVprocSs::CscPtr, XVprocSs::CtxtData, XVprocSs_ContextData::DeintBufAddr, XVprocSs::DeintPtr, XVprocSs_ContextData::HcrIn, XVprocSs_ContextData::HcrOut, XVprocSs::HcrsmplrPtr, XVprocSs::HscalerPtr, XVprocSs_ContextData::LboxBkgndColor, XVprocSs::LboxPtr, XVprocSs_ContextData::RdWindow, XVprocSs_ContextData::RtngTable, XVprocSs_ContextData::RtrNumCores, XVprocSs_ContextData::ScaleMode, XVprocSs_ContextData::StartCore, XVprocSs_ContextData::StrmCformat, XVprocSs::VcrsmplrInPtr, XVprocSs::VcrsmplrOutPtr, XVprocSs::VdmaPtr, XVprocSs::VidIn, XVprocSs_ContextData::VidInHeight, XVprocSs_ContextData::VidInWidth, XVprocSs::VidOut, XVprocSs::VscalerPtr, XVprocSs_ContextData::WrWindow, XVPROCSS_EVT_CFG_CSC, XVPROCSS_EVT_CFG_HSCALER, XVPROCSS_EVT_CFG_MAX, XVPROCSS_EVT_CFG_VSCALER, XVprocSs_GetColorDepth, XVprocSs_IsPipModeOn, XVprocSs_IsZoomModeOn, XVprocSs_LogWrite, XVprocSs_Start, XVprocSs_VdmaSetWinToDnScaleMode, XVprocSs_VdmaSetWinToUpScaleMode.
XVprocSs_Config* XVprocSs_LookupConfig(UINTPTR BaseAddress)
This function looks for the device configuration based on the unique device ID.
The table XVprocSs_ConfigTable[] contains the configuration information for each instance of the device in the system. DeviceId is the unique device ID of the device being looked up A pointer to the configuration table entry corresponding to the given device ID, or NULL if no match is found This function searches for and returns a pointer to the XVprocSs_Config structure that matches the specified BaseAddress. If BaseAddress is zero, it returns the first entry in the XVprocSs_ConfigTable. If no matching configuration is found, it returns NULL. BaseAddress is the base address of the device to look up. A pointer to the matching XVprocSs_Config structure if found, otherwise NULL.
Referenced by XSys_Init.
u32 XVprocSs_GetDrvIndex(UINTPTR BaseAddress)
Retrieves the index of the driver configuration in the XVprocSs_ConfigTable that matches the specified BaseAddress.
This function iterates through the XVprocSs_ConfigTable array and compares each entry's BaseAddress with the provided BaseAddress. If a match is found, the corresponding index is returned. If no match is found, the function returns the index at which the Name field is NULL (end of the table). BaseAddress The base address to search for in the configuration table. The index of the matching configuration entry in XVprocSs_ConfigTable. If no match is found, returns the index at the end of the table.
XVDMA_RESET_TIMEOUT
XVPROCSS_VDMA_H_
XVPROCSS_COREINIT_H__
XVPROCSS_AXIS_SWITCH_VIDIN_S0
XVPROCSS_AXIS_SWITCH_VIDOUT_M0
XVPROCSS_ROUTER_H__