periph.h
XPERIPH_H
XPER_GPIO_CHANNEL_1
XPER_GPIO_CHANNEL_2
XPeriph_SetTPGColorFormat
This macro sets the TPG color format.
pPeriph is pointer to the peripheral Instance ColorFormat is the new color format none
Referenced by XPeriph_SetTpgParams.
XPeriph_SetTPGPattern
This macro sets the TPG pattern.
pPeriph is pointer to the peripheral Instance Pattern is the new pattern id none
Referenced by XPeriph_SetTpgParams.
XPeriph_SetTPGWidth
This macro sets TPG active width.
pPeriph Pointer to the peripheral instance whose TPG width is to be set. width The desired width value to set for the TPG. none
Referenced by XPeriph_SetTpgParams.
XPeriph_SetTPGHeight
This macro sets TPG active height.
pPeriph is pointer to the peripheral Instance height is the new active height none
Referenced by XPeriph_SetTpgParams.
XPeriph_SetTPGInterlacedMode
This macro sets TPG Interlaced Mode.
pPeriph is pointer to the peripheral Instance mode is the interlace mode T/F none
Referenced by XPeriph_SetTpgParams.
XPeriph_IsVideoLocked
This macro reads GPIO to check video lock status.
pPeriph is pointer to the peripheral Instance T/F
int XPeriph_PowerOnInit(XPeriph *InstancePtr)
This function initializes system wide common peripherals.
InstancePtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS
References HlsIpReset, Tpg, VidLocMonitor, Vtc, XPeriph_ResetHlsIp.
Referenced by XSys_Init.
void XPeriph_ResetHlsIp(XPeriph *InstancePtr)
This function resets the Hls IP block(s)
InstancePtr is a pointer to the peripheral instance
References XPER_HLSIP_ENABLE, XPER_HLSIP_RESET.
Referenced by XPeriph_PowerOnInit.
void XPeriph_ReportDeviceInfo(XPeriph *InstancePtr)
This function reports system wide common peripherals included in the design.
InstancePtr is a pointer to the Subsystem instance to be worked on.
Referenced by XSys_ReportSystemInfo.
void XPeriph_ConfigTpg(XPeriph *InstancePtr)
This function configures TPG to user defined parameters.
InstancePtr is a pointer to the peripheral instance
void XPeriph_ConfigVtc(XPeriph *InstancePtr, XVidC_VideoStream *StreamPtr, u32 PixPerClk)
This function configures the Video Timing Controller (VTC) for a given peripheral instance based on the provided video stream parameters and the number of pixels per clock.
The function performs the following steps: Disables and resets the VTC generator.Sets the source selection to use generator registers for all timing parameters.Manually writes to the VTC control register to handle the interlace field workaround.Populates the XVtc_Timing structure with horizontal and vertical timing values from the provided video stream, adjusting horizontal counts by the PixPerClk value.Applies a workaround for known VTC offset issues by adjusting vertical porch values.Sets the polarity of all VTC outputs according to the video stream timing.Enables the VTC generator and updates the register configuration. InstancePtr Pointer to the XPeriph instance to configure. StreamPtr Pointer to the XVidC_VideoStream structure containing timing information. PixPerClk Number of pixels processed per clock cycle.
void XPeriph_DisableTpg(XPeriph *InstancePtr)
This function stops TPG IP.
InstancePtr is a pointer to the peripheral instance
void XPeriph_SetTpgParams(XPeriph *InstancePtr, u16 width, u16 height, XVidC_ColorFormat Cformat, u16 Pattern, u16 IsInterlaced)
This function sets the parameters for the Test Pattern Generator (TPG) in the XPeriph instance.
InstancePtr Pointer to the XPeriph instance. width Width of the test pattern to be generated. height Height of the test pattern to be generated. Cformat Color format for the test pattern (of type XVidC_ColorFormat). Pattern Pattern type to be generated. IsInterlaced Flag indicating whether the output should be interlaced (1) or progressive (0).
References XPeriph_SetTPGColorFormat, XPeriph_SetTPGHeight, XPeriph_SetTPGInterlacedMode, XPeriph_SetTPGPattern, XPeriph_SetTPGWidth.
void XPeriph_TpgDbgReportStatus(XPeriph *InstancePtr)
This function reports TPG Status.
InstancePtr is a pointer to the peripheral instance