xvprocss.c
XVPROCSS_RSTMASK_VIDEO_IN
Reset line going out of vpss.
Referenced by XVprocSs_Start.
XVPROCSS_RSTMASK_IP_AXIS
Reset line for vpss internal video IP blocks.
Referenced by XVprocSs_Reset.
XVPROCSS_RSTMASK_IP_AXIMM
Reset line for vpss internal AXI-MM blocks.
Referenced by XVprocSs_Reset.
XVPROCSS_RSTMASK_ALL_BLOCKS
Mask for all AXIS-connected reset lines in the subsystem.
Referenced by XVprocSs_Reset.
const u16 XVprocSs_PixelHStep[3][4][3][4]
Pixel horizontal step lookup table indexed by [Pixels/Clock][Color Depth variation].
GPIO_CH_RESET_SEL
XVprocSs_SubCores subcoreRepo[XPAR_XVPROCSS_NUM_INSTANCES][XPAR_XVPROCSS_NUM_INSTANCES]
Driver instance of all sub-cores included in the design.
Subcore repository indexed by device instance
const char* XVprocSsIpStr[XVPROCSS_SUBCORE_MAX][XVPROCSS_SUBCORE_MAX]
static void SetPowerOnDefaultState(XVprocSs *XVprocSsPtr)
This function configures the Video Processing subsystem internal blocks to power on default configuration.
XVprocSsPtr is a pointer to the Subsystem instance to be worked on. *
static void GetIncludedSubcores(XVprocSs *XVprocSsPtr)
This function queries the subsystem instance configuration to determine the included sub-cores.
For each sub-core that is present in the design the sub-core driver instance is binded with the subsystem sub-core driver handle XVprocSsPtr is a pointer to the Subsystem instance to be worked on. *
static int ValidateSubsystemConfig(XVprocSs *InstancePtr)
This function validates the input and output stream configuration against the Subsystem hardware capabilities.
InstancePtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS if successful else XST_FAILURE
static int ValidateScalerOnlyConfig(XVprocSs *XVprocSsPtr)
This function validates the input and output stream configuration for scaler only configuration.
XVprocSsPtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS if successful else XST_FAILURE This function is applicable only for Stream mode configuration of the subsystem. In this mode only picture resizing is available
static int ValidateCscOnlyConfig(XVprocSs *XVprocSsPtr, u16 Allow422, u16 Allow420)
This function validates the input and output stream configuration for csc only configuration.
pStrmIn is a pointer to the input stream pStrmOut is a pointer to the output stream XST_SUCCESS if successful else XST_FAILURE This function is applicable only for Stream mode configuration of the subsystem. In this mode very limited functionality is available
static int ValidateDeintOnlyConfig(XVprocSs *XVprocSsPtr)
This function validates the input and output stream configuration for deint only configuration.
pStrmIn is a pointer to the input stream pStrmOut is a pointer to the output stream XST_SUCCESS if successful else XST_FAILURE This function is applicable only for Stream mode configuration of the subsystem. In this mode very limited functionality is available
static int ValidateVCResampleOnlyConfig(XVprocSs *XVprocSsPtr)
This function validates the in and out stream configuration for VCResample only configuration.
Converts 420->422 or 422->420. pStrmIn is a pointer to the input stream pStrmOut is a pointer to the output stream XST_SUCCESS if successful else XST_FAILURE This function is applicable only for Stream mode configuration of the subsystem. In this mode very limited functionality is available
static int ValidateHCResampleOnlyConfig(XVprocSs *XVprocSsPtr)
This function validates the input and output stream configuration for the HCResample only configuration.
pStrmIn is a pointer to the input stream pStrmOut is a pointer to the output stream XST_SUCCESS if successful else XST_FAILURE This function is applicable only for Stream mode configuration of the subsystem. In this mode very limited functionality is available
static int SetupModeScalerOnly(XVprocSs *XVprocSsPtr)
This function configures the video subsystem pipeline for ScalerOnly topology of the subsystem.
XVprocSsPtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS if successful else XST_FAILURE If use case is possible the subsystem will configure the sub-cores accordingly else will ignore the request
static int SetupModeCscOnly(XVprocSs *XVprocSsPtr)
This function configures the video subsystem pipeline for CscOnly topology of the subsystem.
XVprocSsPtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS if successful else XST_FAILURE If use case is possible the subsystem will configure the sub-cores accordingly else will ignore the request
static int SetupModeDeintOnly(XVprocSs *XVprocSsPtr)
This function configures the video subsystem pipeline for DeintOnly topology of the subsystem.
XVprocSsPtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS if successful else XST_FAILURE If use case is possible the subsystem will configure the sub-cores accordingly else will ignore the request
static int SetupModeVCResampleOnly(XVprocSs *XVprocSsPtr)
This function configures the video subsystem pipeline for VCResample only topology of the subsystem.
XVprocSsPtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS if successful else XST_FAILURE If use case is possible the subsystem will configure the sub-cores accordingly else will ignore the request
static int SetupModeHCResampleOnly(XVprocSs *XVprocSsPtr)
This function configures the video subsystem pipeline for HCResample only topology of the subsystem.
XVprocSsPtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS if successful else XST_FAILURE If use case is possible the subsystem will configure the sub-cores accordingly else will ignore the request
static int SetupModeMax(XVprocSs *XVprocSsPtr)
This function configures the video subsystem pipeline for Maximum (Full_Fledged) topology.
XVprocSsPtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS if successful else XST_FAILURE
static u32 XVprocSs_GetResetState(XGpio *pReset, u32 channel)
This macro reads the subsystem reset network state.
pReset is a pointer to the Reset IP Block channel is number of reset channel to work upon Reset state -1: Normal -0: Reset
static void XVprocSs_EnableBlock(XGpio *pReset, u32 channel, u32 ipBlock)
This macro enables the IP's connected to subsystem reset network.
pReset is a pointer to the Reset IP Block channel is number of reset channel to work upon ipBlock is the reset line(s) to be activated * * If reset block is not included in the subsystem instance function does not do anything
static void XVprocSs_ResetBlock(XGpio *pReset, u32 channel, u32 ipBlock)
This macro resets the IP connected to subsystem reset network.
pReset is a pointer to the Reset IP Block channel is number of reset channel to work upon ipBlock is the reset line(s) to be asserted * * If reset block is not included in the subsystem instance function does not do anything
static void WaitUs(XVprocSs *XVprocSsPtr, u32 MicroSeconds)
This function routes the delay routine used in the subsystem.
Preference is given to the user registered timer based routine. If no delay handler is registered then it uses the platform specific delay handler XVprocSsPtr is a pointer to the subsystem instance msec is delay required *
void XVprocSs_SetUserTimerHandler(XVprocSs *InstancePtr, XVidC_DelayHandler CallbackFunc, void *CallbackRef)
This function registers the user defined delay/sleep function with subsystem.
InstancePtr is a pointer to the Subsystem instance CallbackFunc is the function pointer to the user defined delay function CallbackRef is the pointer to timer instance used by the delay function
References XVprocSs::UsrDelayUs, XVprocSs::UsrTmrPtr.
void XVprocSs_SetFrameBufBaseaddr(XVprocSs *InstancePtr, UINTPTR addr)
This function sets the base address of the video frame buffers used by the subsystem instance.
InstancePtr is a pointer to the Subsystem instance to be worked on. addr is the base address of the video frame buffers
References XVprocSs::FrameBufBaseaddr.
Referenced by XSys_Init.
int XVprocSs_CfgInitialize(XVprocSs *InstancePtr, XVprocSs_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the video subsystem and included sub-cores.
This function must be called prior to using the subsystem. Initialization includes setting up the instance data for top level as well as all included sub-core therein, and ensuring the hardware is in a known stable state. InstancePtr is a pointer to the Subsystem instance to be worked on. CfgPtr points to the configuration structure associated with the subsystem instance. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if initialization is successful else XST_FAILURE
References XVprocSs_Config::BaseAddress, XVprocSs_Config::ColorDepth, XVprocSs::Config, XVprocSs::CscPtr, XVprocSs::CtxtData, XVprocSs_ContextData::DeintBufAddr, XVprocSs::DeintPtr, XVprocSs::FrameBufBaseaddr, XVprocSs_Config::HasMADI, XVprocSs::HcrsmplrPtr, XVprocSs::HscalerPtr, XVprocSs::IsReady, XVprocSs::LboxPtr, XVprocSs_Config::MaxHeight, XVprocSs_Config::MaxWidth, XVprocSs_Config::NumVidComponents, XVprocSs::RouterPtr, XVprocSs::RstAximmPtr, XVprocSs::RstAxisPtr, XVprocSs::VcrsmplrInPtr, XVprocSs::VcrsmplrOutPtr, XVprocSs::VdmaPtr, XVprocSs::VscalerPtr, XVPROCSS_EVT_CHK_BASEADDR, XVPROCSS_EVT_CHK_TOPO, XVPROCSS_EVT_INIT, XVprocSs_GetSubsystemTopology, XVprocSs_LogWrite, XVprocSs_Reset, XVprocSs_SubcoreInitCsc, XVprocSs_SubcoreInitDeinterlacer, XVprocSs_SubcoreInitHCrsmplr, XVprocSs_SubcoreInitHScaler, XVprocSs_SubcoreInitLetterbox, XVprocSs_SubcoreInitResetAximm, XVprocSs_SubcoreInitResetAxis, XVprocSs_SubcoreInitRouter, XVprocSs_SubcoreInitVCrsmpleIn, XVprocSs_SubcoreInitVCrsmpleOut, XVprocSs_SubcoreInitVdma, XVprocSs_SubcoreInitVScaler.
Referenced by XSys_Init.
void XVprocSs_Start(XVprocSs *InstancePtr)
This function starts the video subsystem including all sub-cores that are included in the processing pipeline for a given use-case.
Video pipe is started from back to front InstancePtr is a pointer to the Subsystem instance to be worked on. Cores are started only if the corresponding start flag in the scratch pad memory is set. This allows to selectively start only those cores included in the processing chain
References XVprocSs::CscPtr, XVprocSs::CtxtData, XVprocSs::DeintPtr, XVprocSs::HcrsmplrPtr, XVprocSs::HscalerPtr, XVprocSs::LboxPtr, XVprocSs::RstAxisPtr, XVprocSs_ContextData::StartCore, XVprocSs::VcrsmplrInPtr, XVprocSs::VcrsmplrOutPtr, XVprocSs::VscalerPtr, XVPROCSS_EDAT_SUCCESS, XVPROCSS_EVT_START_VPSS, XVprocSs_LogWrite, XVPROCSS_RSTMASK_VIDEO_IN, XVprocSs_VdmaStartTransfer.
Referenced by XVprocSs_SetupRouterDataFlow.
void XVprocSs_Stop(XVprocSs *InstancePtr)
This function stops the video subsystem including all sub-cores Stop the video pipe starting from front to back.
InstancePtr is a pointer to the Subsystem instance to be worked on.
References XVprocSs::CscPtr, XVprocSs::DeintPtr, XVprocSs::HcrsmplrPtr, XVprocSs::HscalerPtr, XVprocSs::LboxPtr, XVprocSs::VcrsmplrInPtr, XVprocSs::VcrsmplrOutPtr, XVprocSs::VdmaPtr, XVprocSs::VscalerPtr, XVPROCSS_EDAT_SUCCESS, XVPROCSS_EVT_STOP_VPSS, XVprocSs_LogWrite, XVprocSs_VdmaStop.
void XVprocSs_Reset(XVprocSs *InstancePtr)
This function resets the video subsystem sub-cores.
There are 2 reset networks within the subsystem For cores that are on AXIS interfaceFor cores that are on AXI-MM interface InstancePtr is a pointer to the Subsystem instance to be worked on. * * XVprocSs_Reset,_Start controls vpss resets as shown axis_int -_______________________----------------------------- axis_ext -________________________________________________---- aximm --------_______-------------------------------------- | 100us| 100us| 1000us | 1000us | | _Reset...............................| | Program VSPP IP| _Start
References XVprocSs::CtxtData, XVprocSs::RstAximmPtr, XVprocSs::RstAxisPtr, XVprocSs_ContextData::StartCore, XVPROCSS_EDAT_SUCCESS, XVPROCSS_EVT_RESET_VPSS, XVprocSs_LogWrite, XVPROCSS_RSTMASK_ALL_BLOCKS, XVPROCSS_RSTMASK_IP_AXIMM, XVPROCSS_RSTMASK_IP_AXIS, XVprocSs_VdmaReset.
Referenced by XVprocSs_CfgInitialize.
int XVprocSs_SetVidStreamIn(XVprocSs *InstancePtr, const XVidC_VideoStream *StrmIn)
This function configures the video subsystem input interface.
InstancePtr is a pointer to the Subsystem instance to be worked on. StrmIn is the pointer to input stream configuration XST_SUCCESS
References XVprocSs::VidIn.
Referenced by XSys_SetStreamParam.
int XVprocSs_SetVidStreamOut(XVprocSs *InstancePtr, const XVidC_VideoStream *StrmOut)
This function configures the video subsystem output interface.
InstancePtr is a pointer to the Subsystem instance to be worked on. StrmOut is the pointer to input stream configuration XST_SUCCESS
References XVprocSs::VidOut.
Referenced by XSys_SetStreamParam.
int XVprocSs_SetStreamResolution(XVidC_VideoStream *StreamPtr, const XVidC_VideoMode VmId, XVidC_VideoTiming const *Timing)
This function sets the required subsystem video stream to the user provided stream and timing parameters.
StreamPtr is a pointer to the subsystem video stream to be configured VmId is the Video Mode ID of the new resolution to be set Timing is the timing parameters of the new resolution to be set XST_SUCCESS if successful else XST_FAILURE
void XVprocSs_UpdateZoomPipWindow(XVprocSs *InstancePtr)
This function updates the Pip/Zoom window currently on screen in-place.
This implies the video is not blanked and the new coordinates will update instantly as the function executes InstancePtr is a pointer to the Subsystem instance to be worked on. This function must be called only after the respective mode (PIP/Zoom) has been enabled and user wants to move window to a new location This function is not applicable in Subsystem Stream Mode Configuration
References XVprocSs::CtxtData, XVprocSs::LboxPtr, XVprocSs::VidOut, XVprocSs_ContextData::WrWindow, XVPROCSS_EDAT_SUCCESS, XVPROCSS_EVT_UPDATE_ZPWIN, XVprocSs_IsConfigModeMax, XVprocSs_IsPipModeOn, XVprocSs_LogWrite, XVprocSs_VdmaSetWinToDnScaleMode, XVprocSs_VdmaSetWinToUpScaleMode, XVprocSs_VdmaStartTransfer.
void XVprocSs_SetZoomPipWindow(XVprocSs *InstancePtr, XVprocSs_Win mode, XVidC_VideoWindow *win)
This function allows user to set the Zoom or PIP window.
Scratch pad memory is updated with the new window information InstancePtr is a pointer to the Subsystem instance to be worked on. mode is feature to be updated PIP or ZOOM win is structure that contains window coordinates and size For Zoom mode RD client window is written in scratch pad memory For Pip mode WR client window is written in scratch pad memory This function is not applicable in Subsystem Stream Mode Configuration
References XVprocSs::Config, XVprocSs::CtxtData, XVprocSs_ContextData::PixelHStepSize, XVprocSs_Config::PixPerClock, XVprocSs_ContextData::RdWindow, XVprocSs::VdmaPtr, XVprocSs_ContextData::WrWindow, XVPROCSS_EDAT_SUCCESS, XVPROCSS_EVT_SET_PIPWIN, XVPROCSS_EVT_SET_ZOOMWIN, XVprocSs_IsConfigModeMax, XVprocSs_LogWrite.
void XVprocSs_GetZoomPipWindow(XVprocSs *InstancePtr, XVprocSs_Win mode, XVidC_VideoWindow *win)
This function reads the user defined Zoom/Pip window from scratch pad memory.
InstancePtr is a pointer to the Subsystem instance to be worked on. mode is feature (PIP or ZOOM) whose window coordinates are to be retrieved win is structure that will contain read window coordinates and size For Zoom mode RD client window is read from scratch pad memory For Pip mode WR client window is read from scratch pad memory This function is not applicable in Subsystem Stream Mode Configuration
References XVprocSs::CtxtData, XVprocSs_ContextData::RdWindow, XVprocSs_ContextData::WrWindow, XVPROCSS_EDAT_SUCCESS, XVPROCSS_EVT_GET_ZPWIN, XVprocSs_IsConfigModeMax, XVprocSs_LogWrite.
Referenced by XVprocSs_ReportSubsystemConfig, XVprocSs_VdmaSetWinToDnScaleMode, XVprocSs_VdmaSetWinToUpScaleMode.
void XVprocSs_SetZoomMode(XVprocSs *InstancePtr, u8 OnOff)
This function configures the video subsystem to enable/disable ZOOM feature If ZOOM mode is set to ON but user has not set window coordinates then quarter of input stream resolution at coordinates 0,0 is set as the default zoom window.
InstancePtr is a pointer to the Subsystem instance to be worked on. OnOff is the action required User must call XVprocSs_ConfigureSubsystem() for change to take effect This call has not been added here such that it provides an opportunity to make the change during vertical blanking at system level. This behavior will change once shadow register support is available in sub-core IP's This function is not applicable in Subsystem Stream Mode Configuration
References XVprocSs::CtxtData, XVprocSs_ContextData::PipEn, XVPROCSS_EVT_SET_ZOOMMODE, XVprocSs_IsConfigModeMax, XVprocSs_LogWrite, XVprocSs_ContextData::ZoomEn.
void XVprocSs_SetPipMode(XVprocSs *InstancePtr, u8 OnOff)
This function configures the video subsystem to enable/disable PIP feature If PIP mode is set to ON but user has not set window coordinates then half of input stream resolution at coordinates 0,0 is set as the default zoom window.
InstancePtr is a pointer to the Subsystem instance to be worked on. OnOff is the action required User must call XVprocSs_ConfigureSubsystem() for change to take effect This call has not been added here such that it provides an opportunity to make the change during vertical blanking at system level. This behavior will change once shadow register support is available in sub-core IP's This function is not applicable in Subsystem Stream Mode Configuration
References XVprocSs::CtxtData, XVprocSs_ContextData::PipEn, XVPROCSS_EVT_SET_PIPMODE, XVprocSs_IsConfigModeMax, XVprocSs_LogWrite, XVprocSs_ContextData::ZoomEn.
int XVprocSs_SetSubsystemConfig(XVprocSs *InstancePtr)
This function is the entry point into the video processing subsystem driver processing path.
It will examine the instantiated subsystem configuration mode and the input and output stream configuration. Based on the available information control flow is determined and requisite sub-cores are configured to implement the supported use case InstancePtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS if successful else XST_FAILURE
References XVPROCSS_EVT_CHK_TOPO, XVprocSs_GetSubsystemTopology, XVprocSs_LogWrite.
s32 XVprocSs_GetPictureBrightness(XVprocSs *InstancePtr)
This function returns picture brighntess setting.
InstancePtr is a pointer to the Subsystem instance to be worked on. current value (0-100), if csc subcore is included
References XVprocSs::CscPtr.
void XVprocSs_SetPictureBrightness(XVprocSs *InstancePtr, s32 NewValue)
This function updates picture brighntess setting with specified value.
InstancePtr is a pointer to the Subsystem instance to be worked on. NewValue is the new value to be written Range: 0-100 Applicable only if CSC core is included in the subsystem
References XVprocSs::CscPtr.
s32 XVprocSs_GetPictureContrast(XVprocSs *InstancePtr)
This function returns picture contrast setting.
InstancePtr is a pointer to the Subsystem instance to be worked on. current value (0-100), if csc subcore is included
References XVprocSs::CscPtr.
void XVprocSs_SetPictureContrast(XVprocSs *InstancePtr, s32 NewValue)
This function updates picture contrast setting with specified value.
InstancePtr is a pointer to the Subsystem instance to be worked on. NewValue is the new value to be written Range: 0-100 * * Applicable only if CSC core is included in the subsystem
References XVprocSs::CscPtr.
s32 XVprocSs_GetPictureSaturation(XVprocSs *InstancePtr)
This function returns picture saturation setting.
InstancePtr is a pointer to the Subsystem instance to be worked on. current value (0-100), if csc subcore is included
References XVprocSs::CscPtr.
void XVprocSs_SetPictureSaturation(XVprocSs *InstancePtr, s32 NewValue)
This function updates picture saturation setting with specified value.
InstancePtr is a pointer to the Subsystem instance to be worked on. NewValue is the new value to be written Range: 0-100 * * Applicable only if CSC core is included in the subsystem
References XVprocSs::CscPtr.
s32 XVprocSs_GetPictureGain(XVprocSs *InstancePtr, XVprocSs_ColorChannel ChId)
This function returns picture gain setting for the specified color channel.
InstancePtr is a pointer to the Subsystem instance to be worked on. ChId is the color channel id for which gain is requested current value (0-100), if csc subcore is included
References XVprocSs::CscPtr.
void XVprocSs_SetPictureGain(XVprocSs *InstancePtr, XVprocSs_ColorChannel ChId, s32 NewValue)
This function updates picture gain setting with specified value.
InstancePtr is a pointer to the Subsystem instance to be worked on. ChId is the color channel id for which gain is to be updated NewValue is the new value to be written Range: 0-100 * * Applicable only if CSC core is included in the subsystem
References XVprocSs::CscPtr.
XVidC_ColorStd XVprocSs_GetPictureColorStdIn(XVprocSs *InstancePtr)
This function returns picture color standard setting for input.
InstancePtr is a pointer to the Subsystem instance to be worked on. Current set color standard, if csc core is included XVIDC_BT_2020XVIDC_BT_709XVIDC_BT_601 Else XVIDC_BT_UNKNOWN
References XVprocSs::CscPtr.
XVidC_ColorStd XVprocSs_GetPictureColorStdOut(XVprocSs *InstancePtr)
This function returns picture color standard setting for output.
InstancePtr is a pointer to the Subsystem instance to be worked on. Current set color standard, if csc core is included XVIDC_BT_2020XVIDC_BT_709XVIDC_BT_601 Else XVIDC_BT_UNKNOWN
References XVprocSs::CscPtr.
void XVprocSs_SetPictureColorStdIn(XVprocSs *InstancePtr, XVidC_ColorStd NewVal)
This function sets picture color standard setting for input.
InstancePtr is a pointer to the Subsystem instance to be worked on. NewVal is the required color standard XVIDC_BT_2020XVIDC_BT_709XVIDC_BT_601 * * Applicable only if CSC core is included in the subsystem
References XVprocSs::CscPtr.
void XVprocSs_SetPictureColorStdOut(XVprocSs *InstancePtr, XVidC_ColorStd NewVal)
This function sets picture color standard setting for output.
InstancePtr is a pointer to the Subsystem instance to be worked on. NewVal is the required color standard XVIDC_BT_2020XVIDC_BT_709XVIDC_BT_601 * * Applicable only if CSC core is included in the subsystem
References XVprocSs::CscPtr.
XVidC_ColorRange XVprocSs_GetPictureColorRange(XVprocSs *InstancePtr)
This function returns picture color range for output.
InstancePtr is a pointer to the Subsystem instance to be worked on. Current set output range, if csc core is included XVIDC_CR_16_235XVIDC_CR_16_240 XVIDC_CR_0_255 Else XVIDC_CR_UNKNOWN_RANGE
References XVprocSs::CscPtr.
void XVprocSs_SetPictureColorRange(XVprocSs *InstancePtr, XVidC_ColorRange NewVal)
This function sets picture color range for output.
InstancePtr is a pointer to the Subsystem instance to be worked on. NewVal is the required color range XVIDC_CR_16_235XVIDC_CR_16_240 XVIDC_CR_0_255 * * Applicable only if CSC core is included in the subsystem
References XVprocSs::CscPtr.
int XVprocSs_SetPictureDemoWindow(XVprocSs *InstancePtr, XVidC_VideoWindow *Win)
This function sets picture Demo Window.
Post this function call all further picture settings will apply only within the defined window. Demo window gets reset every time subsystem configuration changes InstancePtr is a pointer to the Subsystem instance to be worked on. Win is the pointer to window coordinates within which picture settings should be applied XST_SUCCESS if window is valid else XST_FAILURE Applicable only if CSC core is included in the subsystem and the Demo Window is enabled
References XVprocSs::CscPtr, XVPROCSS_EVT_CFG_CSC, XVprocSs_LogWrite.
void XVprocSs_SetPIPBackgroundColor(XVprocSs *InstancePtr, XLboxColorId ColorId)
This function sets PIP background color.
InstancePtr is a pointer to the Subsystem instance to be worked on. ColorId is the requested background color XLBOX_BKGND_BLACKXLBOX_BKGND_WHITEXLBOX_BKGND_REDXLBOX_BKGND_GREENXLBOX_BKGND_BLUE * * Applicable only if Letterbox core is included in the subsystem
References XVprocSs::CtxtData, XVprocSs_ContextData::LboxBkgndColor, XVprocSs::LboxPtr, XVprocSs_ContextData::StrmCformat, XVprocSs::VidIn, XVPROCSS_EVT_SET_PIPMODE, XVprocSs_LogWrite.
void XVprocSs_LoadScalerCoeff(XVprocSs *InstancePtr, u32 CoreId, u16 num_phases, u16 num_taps, const short *Coeff)
This function enables user to load external filter coefficients for Scaler cores, independently for H & V.
InstancePtr is a pointer to the Subsystem instance to be worked on. CoreId is the Scaler core to be worked on XVPROCSS_SUBCORE_SCALER_VXVPROCSS_SUBCORE_SCALER_H num_phases is the number of phases supported by Scaler num_taps is the effective taps to be used by Scaler Coeff is the pointer to the filter table to be loaded * * Applicable only if Scaler cores are included in the subsystem
References XVprocSs::HscalerPtr, XVprocSs::VscalerPtr, XVPROCSS_EVT_CFG_HSCALER, XVPROCSS_EVT_CFG_VSCALER, XVprocSs_LogWrite.
void XVprocSs_LoadChromaResamplerCoeff(XVprocSs *InstancePtr, u32 CoreId, u16 num_taps, const short *Coeff)
This function enables user to load external filter coefficients for Chroma Resampler cores, independently for H & V.
InstancePtr is a pointer to the Subsystem instance to be worked on. CoreId is the resampler core to be worked on XVPROCSS_SUBCORE_CR_HXVPROCSS_SUBCORE_CR_V_INXVPROCSS_SUBCORE_CR_V_OUT num_taps is the taps of the resampler hw instance Coeff is the pointer to the filter table to be loaded * * Applicable only if Resampler cores are included in the subsystem
References XVprocSs::HcrsmplrPtr, XVprocSs::VcrsmplrInPtr, XVprocSs::VcrsmplrOutPtr, XVPROCSS_EVT_CFG_HCR, XVPROCSS_EVT_CFG_VCRI, XVPROCSS_EVT_CFG_VCRO, XVprocSs_LogWrite.
void XVprocSs_ReportSubcoreStatus(XVprocSs *InstancePtr, u32 SubcoreId)
This function reports the status of specified sub-core.
InstancePtr is a pointer to the Subsystem instance to be worked on. SubcoreId is the subcore index from the below list XVPROCSS_SUBCORE_SCALER_VXVPROCSS_SUBCORE_SCALER_HXVPROCSS_SUBCORE_VDMAXVPROCSS_SUBCORE_LBOXXVPROCSS_SUBCORE_CR_HXVPROCSS_SUBCORE_CR_V_INXVPROCSS_SUBCORE_CR_V_OUTXVPROCSS_SUBCORE_CSCXVPROCSS_SUBCORE_DEINT *
References XVprocSs::CscPtr, XVprocSs::CtxtData, XVprocSs::DeintPtr, XVprocSs::HcrsmplrPtr, XVprocSs::HscalerPtr, XVprocSs::LboxPtr, XVprocSs_ContextData::PixelWidthInBits, XVprocSs::VcrsmplrInPtr, XVprocSs::VcrsmplrOutPtr, XVprocSs::VscalerPtr, XVprocSs_VdmaDbgReportStatus.
void XVprocSs_ReportSubsystemCoreInfo(XVprocSs *InstancePtr)
This function reports Video Processing Subsystem HW configuration.
InstancePtr is a pointer to the Subsystem instance. *
References XVprocSs_Config::ColorDepth, XVprocSs::Config, XVprocSs::CscPtr, XVprocSs::DeintPtr, XVprocSs::HcrsmplrPtr, XVprocSs::HscalerPtr, XVprocSs::LboxPtr, XVprocSs_Config::MaxHeight, XVprocSs_Config::MaxWidth, XVprocSs_Config::NumVidComponents, XVprocSs_Config::PixPerClock, XVprocSs::RouterPtr, XVprocSs::RstAximmPtr, XVprocSs::RstAxisPtr, XVprocSs::VcrsmplrInPtr, XVprocSs::VcrsmplrOutPtr, XVprocSs::VdmaPtr, XVprocSs::VscalerPtr, XVprocSs_GetSubsystemTopology.
Referenced by XSys_ReportSystemInfo.
void XVprocSs_ReportSubsystemConfig(XVprocSs *InstancePtr)
This function reports the subsystem HW and input/output stream configuration.
InstancePtr is a pointer to the Subsystem instance to be worked on. *
References XVprocSs::CtxtData, XVprocSs_ContextData::RtngTable, XVprocSs::VidIn, XVprocSs::VidOut, XVprocSs_GetPipZoomWinHStepSize, XVprocSs_GetZoomPipWindow, XVprocSs_IsConfigModeMax, XVprocSs_IsPipModeOn, XVprocSs_IsZoomModeOn.