xvprocss.h
XVPROCSS_H
< prevent circular inclusions by using protection macros
XVprocSs_GetSubsystemTopology
This macro returns the subsystem topology.
XVprocSsPtr is a pointer to the Video Processing subsystem instance XVPROCSS_TOPOLOGY_FULL_FLEDGED or XVPROCSS_TOPOLOGY_SCALER_ONLY
Referenced by XVprocSs_CfgInitialize, XVprocSs_ReportSubsystemCoreInfo, XVprocSs_SetSubsystemConfig.
XVprocSs_GetColorDepth
This macro returns the subsystem Color Depth.
XVprocSsPtr is a pointer to the Video Processing subsystem instance Color Depth
Referenced by XVprocSs_SetupRouterDataFlow.
XVprocSs_IsConfigModeMax
This macro checks if subsystem is in Maximum (Full_Fledged) configuration.
XVprocSsPtr is a pointer to the Video Processing subsystem instance Return 1 if condition is TRUE or 0 if FALSE
Referenced by XVprocSs_GetZoomPipWindow, XVprocSs_ReportSubsystemConfig, XVprocSs_SetPipMode, XVprocSs_SetZoomMode, XVprocSs_SetZoomPipWindow, XVprocSs_UpdateZoomPipWindow.
XVprocSs_IsConfigModeSscalerOnly
This macro checks if subsystem configuration is in Scaler Only Mode.
XVprocSsPtr is pointer to the Video Processing subsystem instance Returns 1 if condition is TRUE or 0 if FALSE
XVprocSs_IsConfigModeDeinterlaceOnly
This macro checks if subsystem configuration is in Deinterlace Only Mode.
XVprocSsPtr is pointer to the Video Processing subsystem instance Returns 1 if condition is TRUE or 0 if FALSE
XVprocSs_IsConfigModeCscOnly
This macro checks if subsystem configuration is in CSC Only Mode.
XVprocSsPtr is pointer to the Video Processing subsystem instance Returns 1 if condition is TRUE or 0 if FALSE
XVprocSs_IsConfigModeVCResampleOnly
This macro checks if subsystem configuration is in V Chroma ResampleMode.
XVprocSsPtr is pointer to the Video Processing subsystem instance Returns 1 if condition is TRUE or 0 if FALSE
XVprocSs_IsConfigModeHCResampleOnly
This macro checks if subsystem configuration is in H Chroma Resample Mode.
XVprocSsPtr is pointer to the Video Processing subsystem instance Returns 1 if condition is TRUE or 0 if FALSE
XVprocSs_IsPipModeOn
This macro returns the current state of PIP Mode stored in subsystem internal scratch pad memory.
XVprocSsPtr is a pointer to the Video Processing subsystem instance Returns 1 if PIP mode is ON or 0 if OFF
Referenced by XVprocSs_ReportSubsystemConfig, XVprocSs_SetupRouterDataFlow, XVprocSs_UpdateZoomPipWindow, XVprocSs_VdmaSetWinToDnScaleMode.
XVprocSs_IsZoomModeOn
This macro returns the current state of Zoom Mode stored in subsystem internal scratch pad memory.
XVprocSsPtr is a pointer to the Video Processing subsystem instance Returns 1 if ZOOM mode is ON or 0 if OFF
Referenced by XVprocSs_ReportSubsystemConfig, XVprocSs_SetupRouterDataFlow, XVprocSs_VdmaSetWinToUpScaleMode.
XVprocSs_GetPipZoomWinHStepSize
This macro returns the Pip/Zoom window horizontal increment size.
XVprocSsPtr is a pointer to the Video Processing subsystem instance Pixel H Step size
Referenced by XVprocSs_ReportSubsystemConfig.
XVprocSs_ResetPipModeFlag
This macro clears the PIP mode flag stored in subsystem internal scratch pad memory.
This call has no side-effect XVprocSsPtr is a pointer to the Video Processing subsystem instance None
XVprocSs_ResetZoomModeFlag
This macro clears the ZOOM mode flag stored in subsystem internal scratch pad memory.
This call has no side-effect XVprocSsPtr is pointer to the Video Processing subsystem instance None
XVprocSs_SetStreamColorFormat
This macro sets the specified stream's color format.
It can be used to update input or output stream. This call has no side-effect in isolation. For change to take effect user must trigger processing path reconfiguration by calling XVprocSs_ConfigureSubsystem() Stream is a pointer to the Subsystem Input or Output Stream ColorFormat is the requested color format None
XVprocSs_SetStreamColorDepth
This macro sets the specified stream's color depth.
It can be used to update input or output stream. This call has no side-effect in isolation For change to take effect user must trigger processing path reconfiguration by calling XVprocSs_ConfigureSubsystem() Stream is a pointer to the Subsystem Input or Output Stream ColorDepth is the requested color depth None
XVPROCSS_SUBCORE_ID
XVPROCSS_CONFIG_TOPOLOGY
XVprocSs_Win
XVprocSs_ScaleMode
XVprocSs_ColorChannel
int XVprocSs_CfgInitialize(XVprocSs *InstancePtr, XVprocSs_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the video subsystem and included sub-cores.
This function must be called prior to using the subsystem. Initialization includes setting up the instance data for top level as well as all included sub-core therein, and ensuring the hardware is in a known stable state. InstancePtr is a pointer to the Subsystem instance to be worked on. CfgPtr points to the configuration structure associated with the subsystem instance. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if initialization is successful else XST_FAILURE
References XVprocSs_Config::BaseAddress, XVprocSs_Config::ColorDepth, XVprocSs::Config, XVprocSs::CscPtr, XVprocSs::CtxtData, XVprocSs_ContextData::DeintBufAddr, XVprocSs::DeintPtr, XVprocSs::FrameBufBaseaddr, XVprocSs_Config::HasMADI, XVprocSs::HcrsmplrPtr, XVprocSs::HscalerPtr, XVprocSs::IsReady, XVprocSs::LboxPtr, XVprocSs_Config::MaxHeight, XVprocSs_Config::MaxWidth, XVprocSs_Config::NumVidComponents, XVprocSs::RouterPtr, XVprocSs::RstAximmPtr, XVprocSs::RstAxisPtr, XVprocSs::VcrsmplrInPtr, XVprocSs::VcrsmplrOutPtr, XVprocSs::VdmaPtr, XVprocSs::VscalerPtr, XVPROCSS_EVT_CHK_BASEADDR, XVPROCSS_EVT_CHK_TOPO, XVPROCSS_EVT_INIT, XVprocSs_GetSubsystemTopology, XVprocSs_LogWrite, XVprocSs_Reset, XVprocSs_SubcoreInitCsc, XVprocSs_SubcoreInitDeinterlacer, XVprocSs_SubcoreInitHCrsmplr, XVprocSs_SubcoreInitHScaler, XVprocSs_SubcoreInitLetterbox, XVprocSs_SubcoreInitResetAximm, XVprocSs_SubcoreInitResetAxis, XVprocSs_SubcoreInitRouter, XVprocSs_SubcoreInitVCrsmpleIn, XVprocSs_SubcoreInitVCrsmpleOut, XVprocSs_SubcoreInitVdma, XVprocSs_SubcoreInitVScaler.
Referenced by XSys_Init.
int XVprocSs_SetSubsystemConfig(XVprocSs *InstancePtr)
This function is the entry point into the video processing subsystem driver processing path.
It will examine the instantiated subsystem configuration mode and the input and output stream configuration. Based on the available information control flow is determined and requisite sub-cores are configured to implement the supported use case InstancePtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS if successful else XST_FAILURE
References XVPROCSS_EVT_CHK_TOPO, XVprocSs_GetSubsystemTopology, XVprocSs_LogWrite.
XVprocSs_Config* XVprocSs_LookupConfig(UINTPTR BaseAddress)
This function looks for the device configuration based on the unique device ID.
The table XVprocSs_ConfigTable[] contains the configuration information for each instance of the device in the system. DeviceId is the unique device ID of the device being looked up A pointer to the configuration table entry corresponding to the given device ID, or NULL if no match is found This function searches for and returns a pointer to the XVprocSs_Config structure that matches the specified BaseAddress. If BaseAddress is zero, it returns the first entry in the XVprocSs_ConfigTable. If no matching configuration is found, it returns NULL. BaseAddress is the base address of the device to look up. A pointer to the matching XVprocSs_Config structure if found, otherwise NULL.
Referenced by XSys_Init.
u32 XVprocSs_GetDrvIndex(UINTPTR BaseAddress)
Retrieves the index of the driver configuration in the XVprocSs_ConfigTable that matches the specified BaseAddress.
This function iterates through the XVprocSs_ConfigTable array and compares each entry's BaseAddress with the provided BaseAddress. If a match is found, the corresponding index is returned. If no match is found, the function returns the index at which the Name field is NULL (end of the table). BaseAddress The base address to search for in the configuration table. The index of the matching configuration entry in XVprocSs_ConfigTable. If no match is found, returns the index at the end of the table.
void XVprocSs_Start(XVprocSs *InstancePtr)
This function starts the video subsystem including all sub-cores that are included in the processing pipeline for a given use-case.
Video pipe is started from back to front InstancePtr is a pointer to the Subsystem instance to be worked on. Cores are started only if the corresponding start flag in the scratch pad memory is set. This allows to selectively start only those cores included in the processing chain
References XVprocSs::CscPtr, XVprocSs::CtxtData, XVprocSs::DeintPtr, XVprocSs::HcrsmplrPtr, XVprocSs::HscalerPtr, XVprocSs::LboxPtr, XVprocSs::RstAxisPtr, XVprocSs_ContextData::StartCore, XVprocSs::VcrsmplrInPtr, XVprocSs::VcrsmplrOutPtr, XVprocSs::VscalerPtr, XVPROCSS_EDAT_SUCCESS, XVPROCSS_EVT_START_VPSS, XVprocSs_LogWrite, XVPROCSS_RSTMASK_VIDEO_IN, XVprocSs_VdmaStartTransfer.
Referenced by XVprocSs_SetupRouterDataFlow.
void XVprocSs_Stop(XVprocSs *InstancePtr)
This function stops the video subsystem including all sub-cores Stop the video pipe starting from front to back.
InstancePtr is a pointer to the Subsystem instance to be worked on.
References XVprocSs::CscPtr, XVprocSs::DeintPtr, XVprocSs::HcrsmplrPtr, XVprocSs::HscalerPtr, XVprocSs::LboxPtr, XVprocSs::VcrsmplrInPtr, XVprocSs::VcrsmplrOutPtr, XVprocSs::VdmaPtr, XVprocSs::VscalerPtr, XVPROCSS_EDAT_SUCCESS, XVPROCSS_EVT_STOP_VPSS, XVprocSs_LogWrite, XVprocSs_VdmaStop.
void XVprocSs_Reset(XVprocSs *InstancePtr)
This function resets the video subsystem sub-cores.
There are 2 reset networks within the subsystem For cores that are on AXIS interfaceFor cores that are on AXI-MM interface InstancePtr is a pointer to the Subsystem instance to be worked on. * * XVprocSs_Reset,_Start controls vpss resets as shown axis_int -_______________________----------------------------- axis_ext -________________________________________________---- aximm --------_______-------------------------------------- | 100us| 100us| 1000us | 1000us | | _Reset...............................| | Program VSPP IP| _Start
References XVprocSs::CtxtData, XVprocSs::RstAximmPtr, XVprocSs::RstAxisPtr, XVprocSs_ContextData::StartCore, XVPROCSS_EDAT_SUCCESS, XVPROCSS_EVT_RESET_VPSS, XVprocSs_LogWrite, XVPROCSS_RSTMASK_ALL_BLOCKS, XVPROCSS_RSTMASK_IP_AXIMM, XVPROCSS_RSTMASK_IP_AXIS, XVprocSs_VdmaReset.
Referenced by XVprocSs_CfgInitialize.
int XVprocSs_SetVidStreamIn(XVprocSs *InstancePtr, const XVidC_VideoStream *StrmIn)
This function configures the video subsystem input interface.
InstancePtr is a pointer to the Subsystem instance to be worked on. StrmIn is the pointer to input stream configuration XST_SUCCESS
References XVprocSs::VidIn.
Referenced by XSys_SetStreamParam.
int XVprocSs_SetVidStreamOut(XVprocSs *InstancePtr, const XVidC_VideoStream *StrmOut)
This function configures the video subsystem output interface.
InstancePtr is a pointer to the Subsystem instance to be worked on. StrmOut is the pointer to input stream configuration XST_SUCCESS
References XVprocSs::VidOut.
Referenced by XSys_SetStreamParam.
int XVprocSs_SetStreamResolution(XVidC_VideoStream *StreamPtr, const XVidC_VideoMode VmId, XVidC_VideoTiming const *Timing)
This function sets the required subsystem video stream to the user provided stream and timing parameters.
StreamPtr is a pointer to the subsystem video stream to be configured VmId is the Video Mode ID of the new resolution to be set Timing is the timing parameters of the new resolution to be set XST_SUCCESS if successful else XST_FAILURE
void XVprocSs_SetFrameBufBaseaddr(XVprocSs *InstancePtr, UINTPTR addr)
This function sets the base address of the video frame buffers used by the subsystem instance.
InstancePtr is a pointer to the Subsystem instance to be worked on. addr is the base address of the video frame buffers
References XVprocSs::FrameBufBaseaddr.
Referenced by XSys_Init.
void XVprocSs_SetUserTimerHandler(XVprocSs *InstancePtr, XVidC_DelayHandler CallbackFunc, void *CallbackRef)
This function registers the user defined delay/sleep function with subsystem.
InstancePtr is a pointer to the Subsystem instance CallbackFunc is the function pointer to the user defined delay function CallbackRef is the pointer to timer instance used by the delay function
References XVprocSs::UsrDelayUs, XVprocSs::UsrTmrPtr.
void XVprocSs_SetZoomMode(XVprocSs *InstancePtr, u8 OnOff)
This function configures the video subsystem to enable/disable ZOOM feature If ZOOM mode is set to ON but user has not set window coordinates then quarter of input stream resolution at coordinates 0,0 is set as the default zoom window.
InstancePtr is a pointer to the Subsystem instance to be worked on. OnOff is the action required User must call XVprocSs_ConfigureSubsystem() for change to take effect This call has not been added here such that it provides an opportunity to make the change during vertical blanking at system level. This behavior will change once shadow register support is available in sub-core IP's This function is not applicable in Subsystem Stream Mode Configuration
References XVprocSs::CtxtData, XVprocSs_ContextData::PipEn, XVPROCSS_EVT_SET_ZOOMMODE, XVprocSs_IsConfigModeMax, XVprocSs_LogWrite, XVprocSs_ContextData::ZoomEn.
void XVprocSs_SetPipMode(XVprocSs *InstancePtr, u8 OnOff)
This function configures the video subsystem to enable/disable PIP feature If PIP mode is set to ON but user has not set window coordinates then half of input stream resolution at coordinates 0,0 is set as the default zoom window.
InstancePtr is a pointer to the Subsystem instance to be worked on. OnOff is the action required User must call XVprocSs_ConfigureSubsystem() for change to take effect This call has not been added here such that it provides an opportunity to make the change during vertical blanking at system level. This behavior will change once shadow register support is available in sub-core IP's This function is not applicable in Subsystem Stream Mode Configuration
References XVprocSs::CtxtData, XVprocSs_ContextData::PipEn, XVPROCSS_EVT_SET_PIPMODE, XVprocSs_IsConfigModeMax, XVprocSs_LogWrite, XVprocSs_ContextData::ZoomEn.
void XVprocSs_SetZoomPipWindow(XVprocSs *InstancePtr, XVprocSs_Win mode, XVidC_VideoWindow *win)
This function allows user to set the Zoom or PIP window.
Scratch pad memory is updated with the new window information InstancePtr is a pointer to the Subsystem instance to be worked on. mode is feature to be updated PIP or ZOOM win is structure that contains window coordinates and size For Zoom mode RD client window is written in scratch pad memory For Pip mode WR client window is written in scratch pad memory This function is not applicable in Subsystem Stream Mode Configuration
References XVprocSs::Config, XVprocSs::CtxtData, XVprocSs_ContextData::PixelHStepSize, XVprocSs_Config::PixPerClock, XVprocSs_ContextData::RdWindow, XVprocSs::VdmaPtr, XVprocSs_ContextData::WrWindow, XVPROCSS_EDAT_SUCCESS, XVPROCSS_EVT_SET_PIPWIN, XVPROCSS_EVT_SET_ZOOMWIN, XVprocSs_IsConfigModeMax, XVprocSs_LogWrite.
void XVprocSs_GetZoomPipWindow(XVprocSs *InstancePtr, XVprocSs_Win mode, XVidC_VideoWindow *win)
This function reads the user defined Zoom/Pip window from scratch pad memory.
InstancePtr is a pointer to the Subsystem instance to be worked on. mode is feature (PIP or ZOOM) whose window coordinates are to be retrieved win is structure that will contain read window coordinates and size For Zoom mode RD client window is read from scratch pad memory For Pip mode WR client window is read from scratch pad memory This function is not applicable in Subsystem Stream Mode Configuration
References XVprocSs::CtxtData, XVprocSs_ContextData::RdWindow, XVprocSs_ContextData::WrWindow, XVPROCSS_EDAT_SUCCESS, XVPROCSS_EVT_GET_ZPWIN, XVprocSs_IsConfigModeMax, XVprocSs_LogWrite.
Referenced by XVprocSs_ReportSubsystemConfig, XVprocSs_VdmaSetWinToDnScaleMode, XVprocSs_VdmaSetWinToUpScaleMode.
void XVprocSs_UpdateZoomPipWindow(XVprocSs *InstancePtr)
This function updates the Pip/Zoom window currently on screen in-place.
This implies the video is not blanked and the new coordinates will update instantly as the function executes InstancePtr is a pointer to the Subsystem instance to be worked on. This function must be called only after the respective mode (PIP/Zoom) has been enabled and user wants to move window to a new location This function is not applicable in Subsystem Stream Mode Configuration
References XVprocSs::CtxtData, XVprocSs::LboxPtr, XVprocSs::VidOut, XVprocSs_ContextData::WrWindow, XVPROCSS_EDAT_SUCCESS, XVPROCSS_EVT_UPDATE_ZPWIN, XVprocSs_IsConfigModeMax, XVprocSs_IsPipModeOn, XVprocSs_LogWrite, XVprocSs_VdmaSetWinToDnScaleMode, XVprocSs_VdmaSetWinToUpScaleMode, XVprocSs_VdmaStartTransfer.
s32 XVprocSs_GetPictureBrightness(XVprocSs *InstancePtr)
This function returns picture brighntess setting.
InstancePtr is a pointer to the Subsystem instance to be worked on. current value (0-100), if csc subcore is included
References XVprocSs::CscPtr.
void XVprocSs_SetPictureBrightness(XVprocSs *InstancePtr, s32 NewValue)
This function updates picture brighntess setting with specified value.
InstancePtr is a pointer to the Subsystem instance to be worked on. NewValue is the new value to be written Range: 0-100 Applicable only if CSC core is included in the subsystem
References XVprocSs::CscPtr.
s32 XVprocSs_GetPictureContrast(XVprocSs *InstancePtr)
This function returns picture contrast setting.
InstancePtr is a pointer to the Subsystem instance to be worked on. current value (0-100), if csc subcore is included
References XVprocSs::CscPtr.
void XVprocSs_SetPictureContrast(XVprocSs *InstancePtr, s32 NewValue)
This function updates picture contrast setting with specified value.
InstancePtr is a pointer to the Subsystem instance to be worked on. NewValue is the new value to be written Range: 0-100 * * Applicable only if CSC core is included in the subsystem
References XVprocSs::CscPtr.
s32 XVprocSs_GetPictureSaturation(XVprocSs *InstancePtr)
This function returns picture saturation setting.
InstancePtr is a pointer to the Subsystem instance to be worked on. current value (0-100), if csc subcore is included
References XVprocSs::CscPtr.
void XVprocSs_SetPictureSaturation(XVprocSs *InstancePtr, s32 NewValue)
This function updates picture saturation setting with specified value.
InstancePtr is a pointer to the Subsystem instance to be worked on. NewValue is the new value to be written Range: 0-100 * * Applicable only if CSC core is included in the subsystem
References XVprocSs::CscPtr.
s32 XVprocSs_GetPictureGain(XVprocSs *InstancePtr, XVprocSs_ColorChannel ChId)
This function returns picture gain setting for the specified color channel.
InstancePtr is a pointer to the Subsystem instance to be worked on. ChId is the color channel id for which gain is requested current value (0-100), if csc subcore is included
References XVprocSs::CscPtr.
void XVprocSs_SetPictureGain(XVprocSs *InstancePtr, XVprocSs_ColorChannel ChId, s32 NewValue)
This function updates picture gain setting with specified value.
InstancePtr is a pointer to the Subsystem instance to be worked on. ChId is the color channel id for which gain is to be updated NewValue is the new value to be written Range: 0-100 * * Applicable only if CSC core is included in the subsystem
References XVprocSs::CscPtr.
XVidC_ColorStd XVprocSs_GetPictureColorStdIn(XVprocSs *InstancePtr)
This function returns picture color standard setting for input.
InstancePtr is a pointer to the Subsystem instance to be worked on. Current set color standard, if csc core is included XVIDC_BT_2020XVIDC_BT_709XVIDC_BT_601 Else XVIDC_BT_UNKNOWN
References XVprocSs::CscPtr.
void XVprocSs_SetPictureColorStdIn(XVprocSs *InstancePtr, XVidC_ColorStd NewVal)
This function sets picture color standard setting for input.
InstancePtr is a pointer to the Subsystem instance to be worked on. NewVal is the required color standard XVIDC_BT_2020XVIDC_BT_709XVIDC_BT_601 * * Applicable only if CSC core is included in the subsystem
References XVprocSs::CscPtr.
XVidC_ColorStd XVprocSs_GetPictureColorStdOut(XVprocSs *InstancePtr)
This function returns picture color standard setting for output.
InstancePtr is a pointer to the Subsystem instance to be worked on. Current set color standard, if csc core is included XVIDC_BT_2020XVIDC_BT_709XVIDC_BT_601 Else XVIDC_BT_UNKNOWN
References XVprocSs::CscPtr.
void XVprocSs_SetPictureColorStdOut(XVprocSs *InstancePtr, XVidC_ColorStd NewVal)
This function sets picture color standard setting for output.
InstancePtr is a pointer to the Subsystem instance to be worked on. NewVal is the required color standard XVIDC_BT_2020XVIDC_BT_709XVIDC_BT_601 * * Applicable only if CSC core is included in the subsystem
References XVprocSs::CscPtr.
XVidC_ColorRange XVprocSs_GetPictureColorRange(XVprocSs *InstancePtr)
This function returns picture color range for output.
InstancePtr is a pointer to the Subsystem instance to be worked on. Current set output range, if csc core is included XVIDC_CR_16_235XVIDC_CR_16_240 XVIDC_CR_0_255 Else XVIDC_CR_UNKNOWN_RANGE
References XVprocSs::CscPtr.
void XVprocSs_SetPictureColorRange(XVprocSs *InstancePtr, XVidC_ColorRange NewVal)
This function sets picture color range for output.
InstancePtr is a pointer to the Subsystem instance to be worked on. NewVal is the required color range XVIDC_CR_16_235XVIDC_CR_16_240 XVIDC_CR_0_255 * * Applicable only if CSC core is included in the subsystem
References XVprocSs::CscPtr.
int XVprocSs_SetPictureDemoWindow(XVprocSs *InstancePtr, XVidC_VideoWindow *Win)
This function sets picture Demo Window.
Post this function call all further picture settings will apply only within the defined window. Demo window gets reset every time subsystem configuration changes InstancePtr is a pointer to the Subsystem instance to be worked on. Win is the pointer to window coordinates within which picture settings should be applied XST_SUCCESS if window is valid else XST_FAILURE Applicable only if CSC core is included in the subsystem and the Demo Window is enabled
References XVprocSs::CscPtr, XVPROCSS_EVT_CFG_CSC, XVprocSs_LogWrite.
void XVprocSs_SetPIPBackgroundColor(XVprocSs *InstancePtr, XLboxColorId ColorId)
This function sets PIP background color.
InstancePtr is a pointer to the Subsystem instance to be worked on. ColorId is the requested background color XLBOX_BKGND_BLACKXLBOX_BKGND_WHITEXLBOX_BKGND_REDXLBOX_BKGND_GREENXLBOX_BKGND_BLUE * * Applicable only if Letterbox core is included in the subsystem
References XVprocSs::CtxtData, XVprocSs_ContextData::LboxBkgndColor, XVprocSs::LboxPtr, XVprocSs_ContextData::StrmCformat, XVprocSs::VidIn, XVPROCSS_EVT_SET_PIPMODE, XVprocSs_LogWrite.
void XVprocSs_LoadScalerCoeff(XVprocSs *InstancePtr, u32 CoreId, u16 num_phases, u16 num_taps, const short *Coeff)
This function enables user to load external filter coefficients for Scaler cores, independently for H & V.
InstancePtr is a pointer to the Subsystem instance to be worked on. CoreId is the Scaler core to be worked on XVPROCSS_SUBCORE_SCALER_VXVPROCSS_SUBCORE_SCALER_H num_phases is the number of phases supported by Scaler num_taps is the effective taps to be used by Scaler Coeff is the pointer to the filter table to be loaded * * Applicable only if Scaler cores are included in the subsystem
References XVprocSs::HscalerPtr, XVprocSs::VscalerPtr, XVPROCSS_EVT_CFG_HSCALER, XVPROCSS_EVT_CFG_VSCALER, XVprocSs_LogWrite.
void XVprocSs_LoadChromaResamplerCoeff(XVprocSs *InstancePtr, u32 CoreId, u16 num_taps, const short *Coeff)
This function enables user to load external filter coefficients for Chroma Resampler cores, independently for H & V.
InstancePtr is a pointer to the Subsystem instance to be worked on. CoreId is the resampler core to be worked on XVPROCSS_SUBCORE_CR_HXVPROCSS_SUBCORE_CR_V_INXVPROCSS_SUBCORE_CR_V_OUT num_taps is the taps of the resampler hw instance Coeff is the pointer to the filter table to be loaded * * Applicable only if Resampler cores are included in the subsystem
References XVprocSs::HcrsmplrPtr, XVprocSs::VcrsmplrInPtr, XVprocSs::VcrsmplrOutPtr, XVPROCSS_EVT_CFG_HCR, XVPROCSS_EVT_CFG_VCRI, XVPROCSS_EVT_CFG_VCRO, XVprocSs_LogWrite.
void XVprocSs_ReportSubsystemConfig(XVprocSs *InstancePtr)
This function reports the subsystem HW and input/output stream configuration.
InstancePtr is a pointer to the Subsystem instance to be worked on. *
References XVprocSs::CtxtData, XVprocSs_ContextData::RtngTable, XVprocSs::VidIn, XVprocSs::VidOut, XVprocSs_GetPipZoomWinHStepSize, XVprocSs_GetZoomPipWindow, XVprocSs_IsConfigModeMax, XVprocSs_IsPipModeOn, XVprocSs_IsZoomModeOn.
void XVprocSs_ReportSubsystemCoreInfo(XVprocSs *InstancePtr)
This function reports Video Processing Subsystem HW configuration.
InstancePtr is a pointer to the Subsystem instance. *
References XVprocSs_Config::ColorDepth, XVprocSs::Config, XVprocSs::CscPtr, XVprocSs::DeintPtr, XVprocSs::HcrsmplrPtr, XVprocSs::HscalerPtr, XVprocSs::LboxPtr, XVprocSs_Config::MaxHeight, XVprocSs_Config::MaxWidth, XVprocSs_Config::NumVidComponents, XVprocSs_Config::PixPerClock, XVprocSs::RouterPtr, XVprocSs::RstAximmPtr, XVprocSs::RstAxisPtr, XVprocSs::VcrsmplrInPtr, XVprocSs::VcrsmplrOutPtr, XVprocSs::VdmaPtr, XVprocSs::VscalerPtr, XVprocSs_GetSubsystemTopology.
Referenced by XSys_ReportSystemInfo.
void XVprocSs_ReportSubcoreStatus(XVprocSs *InstancePtr, u32 SubcoreId)
This function reports the status of specified sub-core.
InstancePtr is a pointer to the Subsystem instance to be worked on. SubcoreId is the subcore index from the below list XVPROCSS_SUBCORE_SCALER_VXVPROCSS_SUBCORE_SCALER_HXVPROCSS_SUBCORE_VDMAXVPROCSS_SUBCORE_LBOXXVPROCSS_SUBCORE_CR_HXVPROCSS_SUBCORE_CR_V_INXVPROCSS_SUBCORE_CR_V_OUTXVPROCSS_SUBCORE_CSCXVPROCSS_SUBCORE_DEINT *
References XVprocSs::CscPtr, XVprocSs::CtxtData, XVprocSs::DeintPtr, XVprocSs::HcrsmplrPtr, XVprocSs::HscalerPtr, XVprocSs::LboxPtr, XVprocSs_ContextData::PixelWidthInBits, XVprocSs::VcrsmplrInPtr, XVprocSs::VcrsmplrOutPtr, XVprocSs::VscalerPtr, XVprocSs_VdmaDbgReportStatus.
void XVprocSs_LogReset(XVprocSs *InstancePtr)
This function will reset the driver's logging mechanism.
InstancePtr is a pointer to the XVprocSs core instance. HeadIndex == TailIndex means that the log is empty.
References XVprocSs::Log.
Referenced by XSys_Init.
u16 XVprocSs_LogRead(XVprocSs *InstancePtr)
This function will read the last event from the log.
InstancePtr is a pointer to the XVprocSs core instance. The log data. The read is "destructive" in the sense an event may only be read once, the read pointer then advancing to the next entry. After reading all the events (see routine XVprocSs_LogDisplay), the log will be empty.
References XVprocSs::Log, XVPROCSS_EVT_BUFFSIZE, XVPROCSS_EVT_NONE.
Referenced by XVprocSs_LogDisplay.
void XVprocSs_LogDisplay(XVprocSs *InstancePtr)
This function will read and print the entire event log.
InstancePtr is a pointer to the XVprocSs core instance. After reading out all events, the log will be empty.
References XVPROCSS_EDAT_SUCCESS, XVPROCSS_EVT_CFG_CSC, XVPROCSS_EVT_CFG_DEINT, XVPROCSS_EVT_CFG_HCR, XVPROCSS_EVT_CFG_HSCALER, XVPROCSS_EVT_CFG_MAX, XVPROCSS_EVT_CFG_VCRI, XVPROCSS_EVT_CFG_VCRO, XVPROCSS_EVT_CFG_VPSS, XVPROCSS_EVT_CFG_VSCALER, XVPROCSS_EVT_CFGERR_VDMA, XVPROCSS_EVT_CHK_BASEADDR, XVPROCSS_EVT_CHK_TOPO, XVPROCSS_EVT_GET_ZPWIN, XVPROCSS_EVT_INIT, XVPROCSS_EVT_INIT_LBOX, XVPROCSS_EVT_INIT_RESAXIM, XVPROCSS_EVT_INIT_RESAXIS, XVPROCSS_EVT_INIT_ROUTER, XVPROCSS_EVT_INIT_VDMA, XVPROCSS_EVT_NONE, XVPROCSS_EVT_OPERR_VDMA, XVPROCSS_EVT_RESET_VPSS, XVPROCSS_EVT_SET_PIPMODE, XVPROCSS_EVT_SET_PIPWIN, XVPROCSS_EVT_SET_ZOOMMODE, XVPROCSS_EVT_SET_ZOOMWIN, XVPROCSS_EVT_START_VPSS, XVPROCSS_EVT_STOP_VPSS, XVPROCSS_EVT_UPDATE_ZPWIN, XVprocSs_LogRead.
void XVprocSs_LogWrite(XVprocSs *InstancePtr, XVprocSs_LogEvent Evt, u8 Data)
This function will insert an event in the driver's logging mechanism.
InstancePtr is a pointer to the XVprocSs core instance. Evt is the event type to log. Data is the associated data for the event. The DataBuffer is circular. If full, new events will overwrite oldest events.
References XVprocSs::Log, XVPROCSS_EVT_BUFFSIZE, XVPROCSS_EVT_LAST_ENUM.
Referenced by XVprocSs_BuildRoutingTable, XVprocSs_CfgInitialize, XVprocSs_GetZoomPipWindow, XVprocSs_LoadChromaResamplerCoeff, XVprocSs_LoadScalerCoeff, XVprocSs_ProgRouterMux, XVprocSs_Reset, XVprocSs_SetPictureDemoWindow, XVprocSs_SetPIPBackgroundColor, XVprocSs_SetPipMode, XVprocSs_SetSubsystemConfig, XVprocSs_SetupRouterDataFlow, XVprocSs_SetZoomMode, XVprocSs_SetZoomPipWindow, XVprocSs_Start, XVprocSs_Stop, XVprocSs_SubcoreInitCsc, XVprocSs_SubcoreInitDeinterlacer, XVprocSs_SubcoreInitHCrsmplr, XVprocSs_SubcoreInitHScaler, XVprocSs_SubcoreInitLetterbox, XVprocSs_SubcoreInitResetAximm, XVprocSs_SubcoreInitResetAxis, XVprocSs_SubcoreInitRouter, XVprocSs_SubcoreInitVCrsmpleIn, XVprocSs_SubcoreInitVCrsmpleOut, XVprocSs_SubcoreInitVdma, XVprocSs_SubcoreInitVScaler, XVprocSs_UpdateZoomPipWindow, XVprocSs_VdmaReadSetup, XVprocSs_VdmaReset, XVprocSs_VdmaStartTransfer, XVprocSs_VdmaWriteSetup.