xvprocss_vdma.h
XVPROCSS_VDMA_H_
XVPROCSS_VDMA_CH_UPDATE
void XVprocSs_VdmaStart(XVprocSs *XVprocSsPtr)
This Function Starts the VDMA (Video Direct Memory Access) engine for the given Video Processing Subsystem instance.
This function initiates both the write and read channels of the VDMA associated with the specified XVprocSs instance. It checks if the VDMA pointer is valid before starting the DMA operations. XVprocSsPtr Pointer to the XVprocSs instance containing the VDMA configuration.
References XVprocSs::VdmaPtr.
void XVprocSs_VdmaStop(XVprocSs *XVprocSsPtr)
This Function Stops the VDMA (Video Direct Memory Access) engine for the given Video Processing Subsystem instance.
This function stops both the write and read channels of the VDMA associated with the specified XVprocSs instance. It checks if the VDMA pointer is valid before starting the DMA operations. XVprocSsPtr Pointer to the XVprocSs instance containing the VDMA configuration.
References XVprocSs::VdmaPtr.
Referenced by XVprocSs_Stop.
void XVprocSs_VdmaReset(XVprocSs *XVprocSsPtr)
This function resets Read and Write channels.
XVprocSsPtr is the pointer to the VPSS instance
References XVprocSs::VdmaPtr, XVPROCSS_EVT_OPERR_VDMA, XVprocSs_LogWrite.
Referenced by XVprocSs_Reset.
int XVprocSs_VdmaWriteSetup(XVprocSs *XVprocSsPtr, UINTPTR WrBaseAddress, XVidC_VideoWindow *window, u32 FrameWidth, u32 FrameHeight, u32 PixelWidthInBits)
This function sets up the write channel.
XVprocSsPtr is the pointer to the VPSS instance. WrBaseAddress is the address in DDR where frame buffers are located window is pointer to sub-frame window FrameWidth is the active width of the stream to be written FrameHeight is the active height of the stream to be written PixelWidthInBits is Bits Per Pixel required for the stream XST_SUCCESS if the setup is successful, XST_FAILURE otherwise.
References XVprocSs::VdmaPtr, XVPROCSS_EVT_CFGERR_VDMA, XVprocSs_LogWrite.
Referenced by XVprocSs_VdmaSetWinToDnScaleMode, XVprocSs_VdmaSetWinToUpScaleMode.
int XVprocSs_VdmaReadSetup(XVprocSs *XVprocSsPtr, UINTPTR RdBaseAddress, XVidC_VideoWindow *window, u32 FrameWidth, u32 FrameHeight, u32 PixelWidthInBits)
This function sets up the read channel.
XVprocSsPtr is the pointer to the VPSS instance. RdBaseAddress is the address in DDR where frame buffers are located window is pointer to sub-frame window FrameWidth is the active width of the stream to be read FrameHeight is the active height of the stream to be read PixelWidthInBits is Bits Per Pixel required for the stream XST_SUCCESS if the setup is successful, XST_FAILURE otherwise. None.
References XVprocSs::VdmaPtr, XVPROCSS_EVT_CFGERR_VDMA, XVprocSs_LogWrite.
Referenced by XVprocSs_VdmaSetWinToDnScaleMode, XVprocSs_VdmaSetWinToUpScaleMode.
int XVprocSs_VdmaStartTransfer(XVprocSs *XVprocSsPtr)
This function starts the transfer on Read/Write channels.
Both channels must have been configured before this call is made XVprocSsPtr is the pointer to the VPSS instance. XST_SUCCESS if the setup is successful, XST_FAILURE otherwise. Currently the return value is ignored at subsystem level.
References XVprocSs::VdmaPtr, XVPROCSS_EVT_OPERR_VDMA, XVprocSs_LogWrite.
Referenced by XVprocSs_Start, XVprocSs_UpdateZoomPipWindow.
void XVprocSs_VdmaDbgReportStatus(XVprocSs *XVprocSsPtr, u32 PixelWidthInBits)
XVprocSs_VdmaDbgReportStatus - Used for reporting the status of the VDMA IP.
This function prints debug information about the current status of the VDMA (Video Direct Memory Access) associated with the given XVprocSs instance. It reports both the read and write channel settings, including height, width, and stride, with values interpreted according to the specified pixel width in bits. The function also clears DMA channel errors and dumps relevant register values for both channels. XVprocSsPtr : Pointer to the XVprocSs instance containing the VDMA pointer. PixelWidthInBits : The width of a pixel in bits, used to calculate bytes per pixel and interpret register values.
References XVprocSs::VdmaPtr.
Referenced by XVprocSs_ReportSubcoreStatus.
void XVprocSs_VdmaSetWinToUpScaleMode(XVprocSs *XVprocSsPtr, u32 updateCh)
This function configures the VDMA RD/WR channel for UP scale (or 1:1) mode.
XVprocSsPtr is the pointer to the VPSS instance. updateCh defines VDMA channel (RD/WR or RD+WR) to update
References XVprocSs::CtxtData, XVprocSs::FrameBufBaseaddr, XVprocSs_ContextData::PixelWidthInBits, XVprocSs_ContextData::VidInHeight, XVprocSs_ContextData::VidInWidth, XVprocSs_GetZoomPipWindow, XVprocSs_IsZoomModeOn, XVprocSs_VdmaReadSetup, XVprocSs_VdmaWriteSetup.
Referenced by XVprocSs_SetupRouterDataFlow, XVprocSs_UpdateZoomPipWindow.
void XVprocSs_VdmaSetWinToDnScaleMode(XVprocSs *XVprocSsPtr, u32 updateCh)
This function configures the VDMA RD/WR channel for down scale mode.
XVprocSsPtr is the pointer to the VPSS instance. updateCh defines VDMA channel (RD/WR or RD+WR) to update
References XVprocSs::CtxtData, XVprocSs::FrameBufBaseaddr, XVprocSs_ContextData::PixelWidthInBits, XVprocSs::VidOut, XVprocSs_GetZoomPipWindow, XVprocSs_IsPipModeOn, XVprocSs_VdmaReadSetup, XVprocSs_VdmaWriteSetup.
Referenced by XVprocSs_SetupRouterDataFlow, XVprocSs_UpdateZoomPipWindow.