xvprocss_coreinit.h
XVPROCSS_COREINIT_H__
int XVprocSs_SubcoreInitResetAxis(XVprocSs *XVprocSsPtr)
This function initializes the included sub-core to it's static configuration.
XVprocSsPtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS/XST_FAILURE
References XVprocSs_Config::BaseAddress, XVprocSs::Config, XVprocSs_Config::HighAddress, XVprocSs_Config::RstAxis, XVprocSs::RstAxisPtr, XVPROCSS_EVT_INIT_RESAXIS, XVprocSs_LogWrite.
Referenced by XVprocSs_CfgInitialize.
int XVprocSs_SubcoreInitResetAximm(XVprocSs *XVprocSsPtr)
This function initializes the included sub-core to it's static configuration.
XVprocSsPtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS/XST_FAILURE
References XVprocSs_Config::BaseAddress, XVprocSs::Config, XVprocSs_Config::HighAddress, XVprocSs_Config::RstAximm, XVprocSs::RstAximmPtr, XVPROCSS_EVT_INIT_RESAXIM, XVprocSs_LogWrite.
Referenced by XVprocSs_CfgInitialize.
int XVprocSs_SubcoreInitRouter(XVprocSs *XVprocSsPtr)
This function initializes the included sub-core to it's static configuration.
XVprocSsPtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS/XST_FAILURE
References XVprocSs_Config::BaseAddress, XVprocSs::Config, XVprocSs_Config::HighAddress, XVprocSs_Config::Router, XVprocSs::RouterPtr, XVPROCSS_EVT_INIT_ROUTER, XVprocSs_LogWrite.
Referenced by XVprocSs_CfgInitialize.
int XVprocSs_SubcoreInitCsc(XVprocSs *XVprocSsPtr)
This function initializes the included sub-core to it's static configuration.
XVprocSsPtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS/XST_FAILURE
References XVprocSs_Config::BaseAddress, XVprocSs::Config, XVprocSs_Config::Csc, XVprocSs::CscPtr, XVprocSs_Config::HighAddress, XVPROCSS_EVT_CFG_CSC, XVprocSs_LogWrite.
Referenced by XVprocSs_CfgInitialize.
int XVprocSs_SubcoreInitHScaler(XVprocSs *XVprocSsPtr)
This function initializes the included sub-core to it's static configuration.
XVprocSsPtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS/XST_FAILURE
References XVprocSs_Config::BaseAddress, XVprocSs::Config, XVprocSs_Config::HighAddress, XVprocSs_Config::Hscale, XVprocSs::HscalerPtr, XVPROCSS_EVT_CFG_HSCALER, XVprocSs_LogWrite.
Referenced by XVprocSs_CfgInitialize.
int XVprocSs_SubcoreInitVScaler(XVprocSs *XVprocSsPtr)
This function initializes the included sub-core to it's static configuration.
XVprocSsPtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS/XST_FAILURE
References XVprocSs_Config::BaseAddress, XVprocSs::Config, XVprocSs_Config::HighAddress, XVprocSs_Config::Vscale, XVprocSs::VscalerPtr, XVPROCSS_EVT_CFG_VSCALER, XVprocSs_LogWrite.
Referenced by XVprocSs_CfgInitialize.
int XVprocSs_SubcoreInitHCrsmplr(XVprocSs *XVprocSsPtr)
This function initializes the included sub-core to it's static configuration.
XVprocSsPtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS/XST_FAILURE
References XVprocSs_Config::BaseAddress, XVprocSs::Config, XVprocSs_Config::HCrsmplr, XVprocSs::HcrsmplrPtr, XVprocSs_Config::HighAddress, XVPROCSS_EVT_CFG_HCR, XVprocSs_LogWrite.
Referenced by XVprocSs_CfgInitialize.
int XVprocSs_SubcoreInitVCrsmpleIn(XVprocSs *XVprocSsPtr)
This function initializes the included sub-core to it's static configuration.
XVprocSsPtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS/XST_FAILURE
References XVprocSs_Config::BaseAddress, XVprocSs::Config, XVprocSs_Config::HighAddress, XVprocSs_Config::VCrsmplrIn, XVprocSs::VcrsmplrInPtr, XVPROCSS_EVT_CFG_VCRI, XVprocSs_LogWrite.
Referenced by XVprocSs_CfgInitialize.
int XVprocSs_SubcoreInitVCrsmpleOut(XVprocSs *XVprocSsPtr)
This function initializes the included sub-core to it's static configuration.
XVprocSsPtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS/XST_FAILURE
References XVprocSs_Config::BaseAddress, XVprocSs::Config, XVprocSs_Config::HighAddress, XVprocSs_Config::VCrsmplrOut, XVprocSs::VcrsmplrOutPtr, XVPROCSS_EVT_CFG_VCRO, XVprocSs_LogWrite.
Referenced by XVprocSs_CfgInitialize.
int XVprocSs_SubcoreInitLetterbox(XVprocSs *XVprocSsPtr)
This function initializes the included sub-core to it's static configuration.
XVprocSsPtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS/XST_FAILURE
References XVprocSs_Config::BaseAddress, XVprocSs::Config, XVprocSs_Config::HighAddress, XVprocSs_Config::Lbox, XVprocSs::LboxPtr, XVPROCSS_EVT_INIT_LBOX, XVprocSs_LogWrite.
Referenced by XVprocSs_CfgInitialize.
int XVprocSs_SubcoreInitVdma(XVprocSs *XVprocSsPtr)
This function initializes the included sub-core to it's static configuration.
XVprocSsPtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS/XST_FAILURE
References XVprocSs_Config::BaseAddress, XVprocSs::Config, XVprocSs_Config::HighAddress, XVprocSs_Config::Vdma, XVprocSs::VdmaPtr, XVPROCSS_EVT_INIT_VDMA, XVprocSs_LogWrite.
Referenced by XVprocSs_CfgInitialize.
int XVprocSs_SubcoreInitDeinterlacer(XVprocSs *XVprocSsPtr)
This function initializes the included sub-core to it's static configuration.
XVprocSsPtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS/XST_FAILURE
References XVprocSs_Config::BaseAddress, XVprocSs::Config, XVprocSs_Config::Deint, XVprocSs::DeintPtr, XVprocSs_Config::HighAddress, XVPROCSS_EVT_CFG_DEINT, XVprocSs_LogWrite.
Referenced by XVprocSs_CfgInitialize.