#/******************************************************************************
#* Copyright (c) 2022 Xilinx, Inc.  All rights reserved.
#* SPDX-License-Identifier: MIT
#******************************************************************************/
#  generated by Xilinx.

DEPENDENCY_FLAGS= -MMD -MP
