dp
XDP_PROTOCOL_DP_1_1
DisplayPort protocol version 1.1.
XDP_PROTOCOL_DP_1_2
DisplayPort protocol version 1.2.
XDP_PROTOCOL_DP_1_4
DisplayPort protocol version 1.4.
XDP_LINK_BW_SET_162GBPS
1.62 Gbps link rate.
Referenced by XDp_IsLinkRateValid.
XDP_LINK_BW_SET_270GBPS
2.70 Gbps link rate.
Referenced by XDp_IsLinkRateValid.
XDP_LINK_BW_SET_540GBPS
5.40 Gbps link rate.
Referenced by XDp_IsLinkRateValid.
XDP_LINK_BW_SET_810GBPS
8.10 Gbps link rate.
Referenced by XDp_IsLinkRateValid.
XDP_LANE_COUNT_SET_1
Lane count of 1.
Referenced by XDp_IsLaneCountValid.
XDP_LANE_COUNT_SET_2
Lane count of 2.
Referenced by XDp_IsLaneCountValid.
XDP_LANE_COUNT_SET_4
Lane count of 4.
Referenced by XDp_IsLaneCountValid.
XDP_MAIN_STREAMX_MISC0_BDC_MASK
Bit depth per color component (BDC).
XDP_MAIN_STREAMX_MISC0_BDC_SHIFT
Shift bits for BDC.
XDP_MAIN_STREAMX_MISC0_BDC_6BPC
6 bits per component.
XDP_MAIN_STREAMX_MISC0_BDC_8BPC
8 bits per component.
XDP_MAIN_STREAMX_MISC0_BDC_10BPC
10 bits per component.
XDP_MAIN_STREAMX_MISC0_BDC_12BPC
12 bits per component.
XDP_MAIN_STREAMX_MISC0_BDC_16BPC
16 bits per component.
XDP_MAIN_STREAMX_MISC0_COMPONENT_FORMAT_MASK
Component format.
XDP_MAIN_STREAMX_MISC0_COMPONENT_FORMAT_SHIFT
Shift bits for component format.
XDP_MAIN_STREAMX_MISC0_COMPONENT_FORMAT_RGB
Stream's component format is RGB.
XDP_MAIN_STREAMX_MISC0_COMPONENT_FORMAT_YCBCR422
Stream's component format is YcbCr 4:2:2.
XDP_MAIN_STREAMX_MISC0_COMPONENT_FORMAT_YCBCR444
Stream's component format is YcbCr 4:4:4.
XDP_DPCD_REV
DPCD revision.
XDP_DPCD_MAX_LINK_RATE
Maximum link rate.
XDP_EDID_DPCD_MAX_LINK_RATE
EDID DPCD maximum link rate.
XDP_DPCD_FEATURE_ENUMERATION_LIST
Feature enumeration list.
XDP_DPCD_MAX_LANE_COUNT
Maximum lane count.
XDP_DPCD_MAX_DOWNSPREAD
Maximum downspread.
XDP_DPCD_NORP_PWR_V_CAP
Number of receiver ports and power voltage capability.
XDP_DPCD_DOWNSP_PRESENT
Downstream port present.
XDP_DPCD_ML_CH_CODING_CAP
Main link channel coding capability.
XDP_DPCD_DOWNSP_COUNT_MSA_OUI
Downstream port count MSA OUI.
XDP_DPCD_RX_PORT0_CAP_0
Receiver port 0 capability 0.
XDP_DPCD_RX_PORT0_CAP_1
Receiver port 0 capability 1.
XDP_DPCD_RX_PORT1_CAP_0
Receiver port 1 capability 0.
XDP_DPCD_RX_PORT1_CAP_1
Receiver port 1 capability 1.
XDP_DPCD_I2C_SPEED_CTL_CAP
I2C speed control capability.
XDP_DPCD_EDP_CFG_CAP
eDP configuration capability.
XDP_DPCD_TRAIN_AUX_RD_INTERVAL
Training AUX read interval.
XDP_DPCD_ADAPTER_CAP
Adapter capability.
XDP_DPCD_MSTM_CAP
MST capability.
XDP_DPCD_NUM_AUDIO_EPS
Number of audio endpoints.
XDP_DPCD_AV_GRANULARITY
AV granularity.
XDP_DPCD_AUD_DEC_LAT_7_0
Audio decoder latency bits 7:0.
XDP_DPCD_AUD_DEC_LAT_15_8
Audio decoder latency bits 15:8.
XDP_DPCD_AUD_PP_LAT_7_0
Audio processing latency bits 7:0.
XDP_DPCD_AUD_PP_LAT_15_8
Audio processing latency bits 15:8.
XDP_DPCD_VID_INTER_LAT
Video interlaced latency.
XDP_DPCD_VID_PROG_LAT
Video progressive latency.
XDP_DPCD_REP_LAT
Repeater latency.
XDP_DPCD_AUD_DEL_INS_7_0
Audio delay insertion bits 7:0.
XDP_DPCD_AUD_DEL_INS_15_8
Audio delay insertion bits 15:8.
XDP_DPCD_AUD_DEL_INS_23_16
Audio delay insertion bits 23:16.
XDP_DPCD_GUID
Global unique identifier.
XDP_DPCD_RX_GTC_VALUE_7_0
RX GTC value bits 7:0.
XDP_DPCD_RX_GTC_VALUE_15_8
RX GTC value bits 15:8.
XDP_DPCD_RX_GTC_VALUE_23_16
RX GTC value bits 23:16.
XDP_DPCD_RX_GTC_VALUE_31_24
RX GTC value bits 31:24.
XDP_DPCD_RX_GTC_MSTR_REQ
RX GTC master request.
XDP_DPCD_RX_GTC_FREQ_LOCK_DONE
RX GTC frequency lock done.
XDP_DPCD_DOWNSP_0_CAP
Downstream port 0 capability.
XDP_DPCD_DOWNSP_1_CAP
Downstream port 1 capability.
XDP_DPCD_DOWNSP_2_CAP
Downstream port 2 capability.
XDP_DPCD_DOWNSP_3_CAP
Downstream port 3 capability.
XDP_DPCD_DOWNSP_0_DET_CAP
Downstream port 0 detailed capability.
XDP_DPCD_DOWNSP_1_DET_CAP
Downstream port 1 detailed capability.
XDP_DPCD_DOWNSP_2_DET_CAP
Downstream port 2 detailed capability.
XDP_DPCD_DOWNSP_3_DET_CAP
Downstream port 3 detailed capability.
XDP_DPCD_LINK_BW_SET
Link bandwidth set.
XDP_DPCD_LANE_COUNT_SET
Lane count set.
XDP_DPCD_TP_SET
Training pattern set.
XDP_DPCD_TRAINING_LANE0_SET
Training lane 0 set.
XDP_DPCD_TRAINING_LANE1_SET
Training lane 1 set.
XDP_DPCD_TRAINING_LANE2_SET
Training lane 2 set.
XDP_DPCD_TRAINING_LANE3_SET
Training lane 3 set.
XDP_DPCD_DOWNSPREAD_CTRL
Downspread control.
XDP_DPCD_ML_CH_CODING_SET
Main link channel coding set.
XDP_DPCD_I2C_SPEED_CTL_SET
I2C speed control set.
XDP_DPCD_EDP_CFG_SET
eDP configuration set.
XDP_DPCD_LINK_QUAL_LANE0_SET
Link quality lane 0 set.
XDP_DPCD_LINK_QUAL_LANE1_SET
Link quality lane 1 set.
XDP_DPCD_LINK_QUAL_LANE2_SET
Link quality lane 2 set.
XDP_DPCD_LINK_QUAL_LANE3_SET
Link quality lane 3 set.
XDP_DPCD_TRAINING_LANE0_1_SET2
Training lane 0 and 1 set 2.
XDP_DPCD_TRAINING_LANE2_3_SET2
Training lane 2 and 3 set 2.
XDP_DPCD_MSTM_CTRL
MST control.
XDP_DPCD_AUDIO_DELAY_7_0
Audio delay bits 7:0.
XDP_DPCD_AUDIO_DELAY_15_8
Audio delay bits 15:8.
XDP_DPCD_AUDIO_DELAY_23_6
Audio delay bits 23:16.
XDP_DPCD_UPSTREAM_DEVICE_DP_PWR_NEED
Upstream device DP power need.
XDP_DPCD_FAUX_MODE_CTRL
FAUX mode control.
XDP_DPCD_FAUX_FORWARD_CH_DRIVE_SET
FAUX forward channel drive set.
XDP_DPCD_BACK_CH_STATUS
Back channel status.
XDP_DPCD_FAUX_BACK_CH_SYMBOL_ERROR_COUNT
FAUX back channel symbol error count.
XDP_DPCD_FAUX_BACK_CH_TRAINING_PATTERN_TIME
FAUX back channel training pattern time.
XDP_DPCD_TX_GTC_VALUE_7_0
TX GTC value bits 7:0.
XDP_DPCD_TX_GTC_VALUE_15_8
TX GTC value bits 15:8.
XDP_DPCD_TX_GTC_VALUE_23_16
TX GTC value bits 23:16.
XDP_DPCD_TX_GTC_VALUE_31_24
TX GTC value bits 31:24.
XDP_DPCD_RX_GTC_VALUE_PHASE_SKEW_EN
RX GTC value phase skew enable.
XDP_DPCD_TX_GTC_FREQ_LOCK_DONE
TX GTC frequency lock done.
XDP_DPCD_ADAPTER_CTRL
Adapter control.
XDP_DPCD_BRANCH_DEVICE_CTRL
Branch device control.
XDP_DPCD_PAYLOAD_ALLOCATE_SET
Payload allocate set.
XDP_DPCD_PAYLOAD_ALLOCATE_START_TIME_SLOT
Payload allocate start time slot.
XDP_DPCD_PAYLOAD_ALLOCATE_TIME_SLOT_COUNT
Payload allocate time slot count.
XDP_DPCD_SINK_COUNT
Sink count.
XDP_DPCD_DEVICE_SERVICE_IRQ
Device service IRQ.
XDP_DPCD_STATUS_LANE_0_1
Status lane 0 and 1.
XDP_DPCD_STATUS_LANE_2_3
Status lane 2 and 3.
XDP_DPCD_LANE_ALIGN_STATUS_UPDATED
Lane align status updated.
XDP_DPCD_SINK_STATUS
Sink status.
XDP_DPCD_ADJ_REQ_LANE_0_1
Adjust request lane 0 and 1.
XDP_DPCD_ADJ_REQ_LANE_2_3
Adjust request lane 2 and 3.
XDP_DPCD_TRAINING_SCORE_LANE_0
Training score lane 0.
XDP_DPCD_TRAINING_SCORE_LANE_1
Training score lane 1.
XDP_DPCD_TRAINING_SCORE_LANE_2
Training score lane 2.
XDP_DPCD_TRAINING_SCORE_LANE_3
Training score lane 3.
XDP_DPCD_ADJ_REQ_PC2
Adjust request post-cursor 2.
XDP_DPCD_FAUX_FORWARD_CH_SYMBOL_ERROR_COUNT
FAUX forward channel symbol error count.
XDP_DPCD_SYMBOL_ERROR_COUNT_LANE_0
Symbol error count lane 0.
XDP_DPCD_SYMBOL_ERROR_COUNT_LANE_1
Symbol error count lane 1.
XDP_DPCD_SYMBOL_ERROR_COUNT_LANE_2
Symbol error count lane 2.
XDP_DPCD_SYMBOL_ERROR_COUNT_LANE_3
Symbol error count lane 3.
XDP_DPCD_FAUX_FORWARD_CH_STATUS
FAUX forward channel status.
XDP_DPCD_FAUX_BACK_CH_DRIVE_SET
FAUX back channel drive set.
XDP_DPCD_FAUX_BACK_CH_SYM_ERR_COUNT_CTRL
FAUX back channel symbol error count control.
XDP_DPCD_PAYLOAD_TABLE_UPDATE_STATUS
Payload table update status.
XDP_DPCD_VC_PAYLOAD_ID_SLOT
Virtual channel payload ID slot.
XDP_DPCD_SET_POWER_DP_PWR_VOLTAGE
Set power DP power voltage.
XDP_DPCD_DOWN_REQ
Downstream request.
XDP_DPCD_UP_REP
Upstream reply.
XDP_DPCD_DOWN_REP
Downstream reply.
XDP_DPCD_UP_REQ
Upstream request.
XDP_DPCD_SINK_COUNT_ESI
Sink count ESI.
XDP_DPCD_SINK_DEVICE_SERVICE_IRQ_VECTOR_ESI0
Sink device service IRQ vector ESI0.
XDP_DPCD_SINK_DEVICE_SERVICE_IRQ_VECTOR_ESI1
Sink device service IRQ vector ESI1.
XDP_DPCD_SINK_LINK_SERVICE_IRQ_VECTOR_ESI0
Sink link service IRQ vector ESI0.
XDP_DPCD_SINK_LANE0_1_STATUS
Sink lane 0 and 1 status.
XDP_DPCD_SINK_LANE2_3_STATUS
Sink lane 2 and 3 status.
XDP_DPCD_SINK_ALIGN_STATUS_UPDATED_ESI
Sink align status updated ESI.
XDP_DPCD_SINK_STATUS_ESI
Sink status ESI.
XDP_DPCD_EXT_DPCD_REV
Extended DPCD revision.
XDP_DPCD_EXT_DPCD_MAX_LINK_RATE
Extended DPCD maximum link rate.
XDP_DPCD_RECEIVER_CAP_FIELD_START
Receiver capability field start.
XDP_DPCD_RECEIVER_CAP_FIELD_SIZE
Receiver capability field size.
XDP_DPCD_LINK_CFG_FIELD_START
Link configuration field start.
XDP_DPCD_LINK_CFG_FIELD_SIZE
Link configuration field size.
XDP_DPCD_LINK_SINK_STATUS_FIELD_START
Link sink status field start.
XDP_DPCD_LINK_SINK_STATUS_FIELD_SIZE
Link sink status field size.
XDP_DPCD_REV_MNR_MASK
DPCD revision minor mask.
XDP_DPCD_REV_MJR_MASK
DPCD revision major mask.
XDP_DPCD_REV_MJR_SHIFT
Shift bits for DPCD revision major.
XDP_DPCD_MAX_LINK_RATE_162GBPS
Maximum link rate 1.62 Gbps.
XDP_DPCD_MAX_LINK_RATE_270GBPS
Maximum link rate 2.70 Gbps.
XDP_DPCD_MAX_LINK_RATE_540GBPS
Maximum link rate 5.40 Gbps.
XDP_DPCD_MAX_LINK_RATE_810GBPS
Maximum link rate 8.10 Gbps.
XDP_DPCD_MAX_LANE_COUNT_MASK
Maximum lane count mask.
XDP_DPCD_MAX_LANE_COUNT_1
Maximum lane count 1.
XDP_DPCD_MAX_LANE_COUNT_2
Maximum lane count 2.
XDP_DPCD_MAX_LANE_COUNT_4
Maximum lane count 4.
XDP_DPCD_POST_LT_ADJ_REQ_SUPPORT_MASK
Post link training adjust request support mask.
XDP_DPCD_TPS3_SUPPORT_MASK
Training pattern 3 support mask.
XDP_DPCD_ENHANCED_FRAME_SUPPORT_MASK
Enhanced frame support mask.
VSC_SDP_EXTENSION_FOR_COLORIMETRY_SUPPORTED
VSC SDP extension for colorimetry supported.
XDP_DPCD_MAX_DOWNSPREAD_MASK
Maximum downspread mask.
XDP_DPCD_NO_AUX_HANDSHAKE_LINK_TRAIN_MASK
No AUX handshake link training mask.
XDP_DPCD_TPS4_SUPPORT_MASK
Training pattern 4 support mask.
XDP_DPCD_NORP_MASK
Number of receiver ports mask.
XDP_DPCD_NORP_TYPE_1RP_MASK
Number of receiver ports type 1RP mask.
XDP_DPCD_NORP_TYPE_G2RP_MASK
Number of receiver ports type G2RP mask.
XDP_DPCD_5V_DP_PWR_CAP_MASK
5V DP power capability mask.
XDP_DPCD_12V_DP_PWR_CAP_MASK
12V DP power capability mask.
XDP_DPCD_18V_DP_PWR_CAP_MASK
18V DP power capability mask.
XDP_DPCD_DOWNSP_PRESENT_MASK
Downstream port present mask.
XDP_DPCD_DOWNSP_TYPE_MASK
Downstream port type mask.
XDP_DPCD_DOWNSP_TYPE_SHIFT
Shift bits for downstream port type.
XDP_DPCD_DOWNSP_TYPE_DP
Downstream port type DisplayPort.
XDP_DPCD_DOWNSP_TYPE_AVGA_ADVII
Downstream port type analog VGA/DVI-I.
XDP_DPCD_DOWNSP_TYPE_DVI_HDMI_DPPP
Downstream port type DVI/HDMI/DP++.
XDP_DPCD_DOWNSP_TYPE_OTHERS
Downstream port type others.
XDP_DPCD_DOWNSP_FORMAT_CONV_MASK
Downstream port format conversion mask.
XDP_DPCD_DOWNSP_DCAP_INFO_AVAIL_MASK
Downstream port detailed capability info available mask.
XDP_DPCD_ML_CH_CODING_MASK
Main link channel coding mask.
XDP_DPCD_DOWNSP_COUNT_MASK
Downstream port count mask.
XDP_DPCD_MSA_TIMING_PAR_IGNORED_MASK
MSA timing parameters ignored mask.
XDP_DPCD_OUI_SUPPORT_MASK
OUI support mask.
XDP_DPCD_RX_PORTX_CAP_0_LOCAL_EDID_PRESENT_MASK
RX port local EDID present mask.
XDP_DPCD_RX_PORTX_CAP_0_ASSOC_TO_PRECEDING_PORT_MASK
RX port associated to preceding port mask.
XDP_DPCD_RX_PORTX_CAP_0_HBLACK_EXPANSION_CAPABLE_MASK
RX port horizontal black expansion capable mask.
XDP_DPCD_RX_PORTX_CAP_0_BUFFER_SIZE_UNIT_MASK
RX port buffer size unit mask.
XDP_DPCD_RX_PORTX_CAP_0_BUFFER_SIZE_PER_PORT_MASK
RX port buffer size per port mask.
XDP_DPCD_RX_PORTX_CAP_1_BUFFER_SIZE_MASK
RX port buffer size mask.
XDP_DPCD_I2C_SPEED_CTL_NONE
I2C speed control none.
XDP_DPCD_I2C_SPEED_CTL_1KBIPS
I2C speed control 1 Kbps.
XDP_DPCD_I2C_SPEED_CTL_5KBIPS
I2C speed control 5 Kbps.
XDP_DPCD_I2C_SPEED_CTL_10KBIPS
I2C speed control 10 Kbps.
XDP_DPCD_I2C_SPEED_CTL_100KBIPS
I2C speed control 100 Kbps.
XDP_DPCD_I2C_SPEED_CTL_400KBIPS
I2C speed control 400 Kbps.
XDP_DPCD_I2C_SPEED_CTL_1MBIPS
I2C speed control 1 Mbps.
XDP_DPCD_TRAIN_AUX_RD_INT_MASK
Training AUX read interval mask.
XDP_DPCD_TRAIN_AUX_RD_INT_100_400US
Training AUX read interval 100-400 us.
XDP_DPCD_TRAIN_AUX_RD_INT_4MS
Training AUX read interval 4 ms.
XDP_DPCD_TRAIN_AUX_RD_INT_8MS
Training AUX read interval 8 ms.
XDP_DPCD_TRAIN_AUX_RD_INT_12MS
Training AUX read interval 12 ms.
XDP_DPCD_TRAIN_AUX_RD_INT_16MS
Training AUX read interval 16 ms.
XDP_DPCD_TRAIN_AUX_RD_EXT_RX_CAP_FIELD_PRESENT_MASK
Training AUX read extended RX capability field present mask.
XDP_DPCD_ADAPTOR_CAP_FORCE_LOAD_SENSE_MASK
Adaptor capability force load sense mask.
XDP_DPCD_ADAPTOR_CAP_ALT_I2C_PATTERN_MASK
Adaptor capability alternate I2C pattern mask.
XDP_DPCD_FAUX_CAP_MASK
FAUX capability mask.
XDP_DPCD_MST_CAP_MASK
MST capability mask.
XDP_DPCD_AV_SYNC_DATA_BLK_AV_GRAN_AG_FACTOR_MASK
AV sync data block audio granularity factor mask.
XDP_DPCD_AV_SYNC_DATA_BLK_AV_GRAN_AG_FACTOR_3MS
AV sync data block audio granularity factor 3 ms.
XDP_DPCD_AV_SYNC_DATA_BLK_AV_GRAN_AG_FACTOR_2MS
AV sync data block audio granularity factor 2 ms.
XDP_DPCD_AV_SYNC_DATA_BLK_AV_GRAN_AG_FACTOR_1MS
AV sync data block audio granularity factor 1 ms.
XDP_DPCD_AV_SYNC_DATA_BLK_AV_GRAN_AG_FACTOR_500US
AV sync data block audio granularity factor 500 us.
XDP_DPCD_AV_SYNC_DATA_BLK_AV_GRAN_AG_FACTOR_200US
AV sync data block audio granularity factor 200 us.
XDP_DPCD_AV_SYNC_DATA_BLK_AV_GRAN_AG_FACTOR_100US
AV sync data block audio granularity factor 100 us.
XDP_DPCD_AV_SYNC_DATA_BLK_AV_GRAN_AG_FACTOR_10US
AV sync data block audio granularity factor 10 us.
XDP_DPCD_AV_SYNC_DATA_BLK_AV_GRAN_AG_FACTOR_1US
AV sync data block audio granularity factor 1 us.
XDP_DPCD_AV_SYNC_DATA_BLK_AV_GRAN_VG_FACTOR_MASK
AV sync data block video granularity factor mask.
XDP_DPCD_AV_SYNC_DATA_BLK_AV_GRAN_VG_FACTOR_3MS
AV sync data block video granularity factor 3 ms.
XDP_DPCD_AV_SYNC_DATA_BLK_AV_GRAN_VG_FACTOR_2MS
AV sync data block video granularity factor 2 ms.
XDP_DPCD_AV_SYNC_DATA_BLK_AV_GRAN_VG_FACTOR_1MS
AV sync data block video granularity factor 1 ms.
XDP_DPCD_AV_SYNC_DATA_BLK_AV_GRAN_VG_FACTOR_500US
AV sync data block video granularity factor 500 us.
XDP_DPCD_AV_SYNC_DATA_BLK_AV_GRAN_VG_FACTOR_200US
AV sync data block video granularity factor 200 us.
XDP_DPCD_AV_SYNC_DATA_BLK_AV_GRAN_VG_FACTOR_100US
AV sync data block video granularity factor 100 us.
XDP_DPCD_AV_SYNC_DATA_BLOCK_01_AUD_DEC_LAT_MASK
AV sync data block audio decoder latency mask.
XDP_DPCD_AV_SYNC_DATA_BLOCK_23_AUD_PP_LAT_MASK
AV sync data block audio processing latency mask.
XDP_DPCD_AV_SYNC_DATA_BLOCK_4_VID_INTER_LAT_MASK
AV sync data block video interlaced latency mask.
XDP_DPCD_AV_SYNC_DATA_BLOCK_5_VID_PROG_LAT_MASK
AV sync data block video progressive latency mask.
XDP_DPCD_AV_SYNC_DATA_BLOCK_6_REP_LAT_MASK
AV sync data block repeater latency mask.
XDP_DPCD_AV_SYNC_DATA_BLOCK_789_AUD_DEL_INS_MASK
AV sync data block audio delay insertion mask.
XDP_DPCD_RX_GTC_VALUE_X_RX_GTC_VALUE
RX GTC value mask.
XDP_DPCD_RX_MSTR_REQ_RX_GTC_MSTR_REQ_MASK
RX GTC master request mask.
XDP_DPCD_RX_MSTR_REQ_TX_GTC_VALUE_PAHSE_SKEW_EN_MASK
TX GTC value phase skew enable mask.
XDP_DPCD_RX_GTC_FREQ_LOCK_DONE_MASK
RX GTC frequency lock done mask.
XDP_DPCD_GTC_PHASE_SKEW_OFFSET_X_MASK
GTC phase skew offset mask.
XDP_DPCD_DSC_SUPPORT_MASK
DSC support mask.
XDP_DPCD_DSC_ALGO_REV_DSC_REV_MAJOR_MASK
DSC algorithm revision major mask.
XDP_DPCD_DSC_ALGO_REV_DSC_REV_MINOR_MASK
DSC algorithm revision minor mask.
XDP_DPCD_DSC_RC_BUF_BLK_SZ_MASK
DSC RC buffer block size mask.
XDP_DPCD_DSC_RC_BUF_BLK_SZ_1KB
DSC RC buffer block size 1KB.
XDP_DPCD_DSC_RC_BUF_BLK_SZ_4KB
DSC RC buffer block size 4KB.
XDP_DPCD_DSC_RC_BUF_BLK_SZ_16KB
DSC RC buffer block size 16KB.
XDP_DPCD_DSC_RC_BUF_BLK_SZ_64KB
DSC RC buffer block size 64KB.
XDP_DPCD_DSC_RC_BUF_SZ_MASK
DSC RC buffer size mask.
XDP_DPCD_DSC_SLICE_CAP_1SL_PER_DP_DSC_SINK_DEV_MASK
DSC 1 slice per DP DSC sink device mask.
XDP_DPCD_DSC_SLICE_CAP_2SL_PER_DP_DSC_SINK_DEV_MASK
DSC 2 slices per DP DSC sink device mask.
XDP_DPCD_DSC_SLICE_CAP_4SL_PER_DP_DSC_SINK_DEV_MASK
DSC 4 slices per DP DSC sink device mask.
XDP_DPCD_DSC_SLICE_CAP_6SL_PER_DP_DSC_SINK_DEV_MASK
DSC 6 slices per DP DSC sink device mask.
XDP_DPCD_DSC_SLICE_CAP_8SL_PER_DP_DSC_SINK_DEV_MASK
DSC 8 slices per DP DSC sink device mask.
XDP_DPCD_DSC_SLICE_CAP_10SL_PER_DP_DSC_SINK_DEV_MASK
DSC 10 slices per DP DSC sink device mask.
XDP_DPCD_DSC_SLICE_CAP_12SL_PER_DP_DSC_SINK_DEV_MASK
DSC 12 slices per DP DSC sink device mask.
XDP_DPCD_DSC_LINE_BUFFER_BIT_DEPTH_MASK
DSC line buffer bit depth mask.
XDP_DPCD_DSC_LINE_BUFFER_BIT_DEPTH_9BITS
DSC line buffer bit depth 9 bits.
XDP_DPCD_DSC_LINE_BUFFER_BIT_DEPTH_10BITS
DSC line buffer bit depth 10 bits.
XDP_DPCD_DSC_LINE_BUFFER_BIT_DEPTH_11BITS
DSC line buffer bit depth 11 bits.
XDP_DPCD_DSC_LINE_BUFFER_BIT_DEPTH_12BITS
DSC line buffer bit depth 12 bits.
XDP_DPCD_DSC_LINE_BUFFER_BIT_DEPTH_13BITS
DSC line buffer bit depth 13 bits.
XDP_DPCD_DSC_LINE_BUFFER_BIT_DEPTH_14BITS
DSC line buffer bit depth 14 bits.
XDP_DPCD_DSC_LINE_BUFFER_BIT_DEPTH_15BITS
DSC line buffer bit depth 15 bits.
XDP_DPCD_DSC_LINE_BUFFER_BIT_DEPTH_16BITS
DSC line buffer bit depth 16 bits.
XDP_DPCD_DSC_LINE_BUFFER_BIT_DEPTH_8BITS
DSC line buffer bit depth 8 bits.
XDP_DPCD_DSC_BLOCK_PREDICTION_SUPPORT_MASK
DSC block prediction support mask.
XDP_DPCD_DSC_DECODER_CLR_FRMT_CAP_RGB_MASK
DSC decoder RGB color format capability mask.
XDP_DPCD_DSC_DECODER_CLR_FRMT_CAP_YCRCB444_MASK
DSC decoder YCrCb 4:4:4 color format capability mask.
XDP_DPCD_DSC_DECODER_CLR_FRMT_CAP_YCRCB422_SIMPLE_MASK
DSC decoder YCrCb 4:2:2 simple color format capability mask.
XDP_DPCD_DSC_DECODER_CLR_FRMT_CAP_YCRCB422_NATIVE_MASK
DSC decoder YCrCb 4:2:2 native color format capability mask.
XDP_DPCD_DSC_DECODER_CLR_FRMT_CAP_YCRCB420_NATIVE_MASK
DSC decoder YCrCb 4:2:0 native color format capability mask.
XDP_DPCD_DSC_DECODER_CLR_DEPTH_CAP_8BPC_MASK
DSC decoder 8 bits per color capability mask.
XDP_DPCD_DSC_DECODER_CLR_DEPTH_CAP_10BPC_MASK
DSC decoder 10 bits per color capability mask.
XDP_DPCD_DSC_DECODER_CLR_DEPTH_CAP_12BPC_MASK
DSC decoder 12 bits per color capability mask.
XDP_DPCD_PEAK_DSC_THROUGHPUT_MODE0_MASK
Peak DSC throughput mode 0 mask.
XDP_DPCD_PEAK_DSC_THROUGHPUT_MODE1_MASK
Peak DSC throughput mode 1 mask.
XDP_DPCD_PEAK_DSC_THROUGHPUT_MODEX_NOT_SUPPORTED
Peak DSC throughput mode not supported.
XDP_DPCD_PEAK_DSC_THROUGHPUT_MODEX_340MPS
Peak DSC throughput 340 Mpixels/s.
XDP_DPCD_PEAK_DSC_THROUGHPUT_MODEX_400MPS
Peak DSC throughput 400 Mpixels/s.
XDP_DPCD_PEAK_DSC_THROUGHPUT_MODEX_450MPS
Peak DSC throughput 450 Mpixels/s.
XDP_DPCD_PEAK_DSC_THROUGHPUT_MODEX_500MPS
Peak DSC throughput 500 Mpixels/s.
XDP_DPCD_PEAK_DSC_THROUGHPUT_MODEX_550MPS
Peak DSC throughput 550 Mpixels/s.
XDP_DPCD_PEAK_DSC_THROUGHPUT_MODEX_600MPS
Peak DSC throughput 600 Mpixels/s.
XDP_DPCD_PEAK_DSC_THROUGHPUT_MODEX_650MPS
Peak DSC throughput 650 Mpixels/s.
XDP_DPCD_PEAK_DSC_THROUGHPUT_MODEX_700MPS
Peak DSC throughput 700 Mpixels/s.
XDP_DPCD_PEAK_DSC_THROUGHPUT_MODEX_750MPS
Peak DSC throughput 750 Mpixels/s.
XDP_DPCD_PEAK_DSC_THROUGHPUT_MODEX_800MPS
Peak DSC throughput 800 Mpixels/s.
XDP_DPCD_PEAK_DSC_THROUGHPUT_MODEX_850MPS
Peak DSC throughput 850 Mpixels/s.
XDP_DPCD_PEAK_DSC_THROUGHPUT_MODEX_900MPS
Peak DSC throughput 900 Mpixels/s.
XDP_DPCD_PEAK_DSC_THROUGHPUT_MODEX_950MPS
Peak DSC throughput 950 Mpixels/s.
XDP_DPCD_PEAK_DSC_THROUGHPUT_MODEX_1000MPS
Peak DSC throughput 1000 Mpixels/s.
XDP_DPCD_PEAK_DSC_THROUGHPUT_MODEX_RSVD
Peak DSC throughput mode reserved.
XDP_DPCD_DSC_MAX_SLICE_WIDTH_MASK
DSC maximum slice width mask.
XDP_DPCD_DSC_SLICE_CAP_16SL_PER_DP_DSC_SINK_DEV_MASK
DSC 16 slices per DP DSC sink device mask.
XDP_DPCD_DSC_SLICE_CAP_20SL_PER_DP_DSC_SINK_DEV_MASK
DSC 20 slices per DP DSC sink device mask.
XDP_DPCD_DSC_SLICE_CAP_24SL_PER_DP_DSC_SINK_DEV_MASK
DSC 24 slices per DP DSC sink device mask.
XDP_DPCD_DSC_BPP_INCREMENT_MASK
DSC bits per pixel increment mask.
XDP_DPCD_DSC_BPP_INCREMENT_1H16BPP
DSC bits per pixel increment 1/16 bpp.
XDP_DPCD_DSC_BPP_INCREMENT_1H8BPP
DSC bits per pixel increment 1/8 bpp.
XDP_DPCD_DSC_BPP_INCREMENT_1H4BPP
DSC bits per pixel increment 1/4 bpp.
XDP_DPCD_DSC_BPP_INCREMENT_1H2BPP
DSC bits per pixel increment 1/2 bpp.
XDP_DPCD_DSC_BPP_INCREMENT_1BPP
DSC bits per pixel increment 1 bpp.
XDP_DPCD_DOWNSP_X_CAP_TYPE_MASK
Downstream port capability type mask.
XDP_DPCD_DOWNSP_X_CAP_TYPE_DP
Downstream port type DisplayPort.
XDP_DPCD_DOWNSP_X_CAP_TYPE_AVGA
Downstream port type analog VGA.
XDP_DPCD_DOWNSP_X_CAP_TYPE_DVI
Downstream port type DVI.
XDP_DPCD_DOWNSP_X_CAP_TYPE_HDMI
Downstream port type HDMI.
XDP_DPCD_DOWNSP_X_CAP_TYPE_OTHERS
Downstream port type others.
XDP_DPCD_DOWNSP_X_CAP_TYPE_DPPP
Downstream port type DP++.
XDP_DPCD_DOWNSP_X_CAP_HPD_MASK
Downstream port HPD awareness mask.
XDP_DPCD_DOWNSP_X_CAP_NON_EDID_ATTR_MASK
Downstream port non-EDID attribute mask.
XDP_DPCD_DOWNSP_X_CAP_NON_EDID_ATTR_SHIFT
Downstream port non-EDID attribute shift.
XDP_DPCD_DOWNSP_X_CAP_NON_EDID_ATTR_720_480_I_60
Downstream port 720x480i @ 60Hz.
XDP_DPCD_DOWNSP_X_CAP_NON_EDID_ATTR_720_480_I_50
Downstream port 720x480i @ 50Hz.
XDP_DPCD_DOWNSP_X_CAP_NON_EDID_ATTR_1920_1080_I_60
Downstream port 1920x1080i @ 60Hz.
XDP_DPCD_DOWNSP_X_CAP_NON_EDID_ATTR_1920_1080_I_50
Downstream port 1920x1080i @ 50Hz.
XDP_DPCD_DOWNSP_X_CAP_NON_EDID_ATTR_1280_720_P_60
Downstream port 1280x720p @ 60Hz.
XDP_DPCD_DOWNSP_X_CAP_NON_EDID_ATTR_1280_720_P_50
Downstream port 1280x720p @ 50Hz.
XDP_DPCD_DOWNSP_X_DCAP_MAX_BPC_MASK
Downstream port maximum bits per color mask.
XDP_DPCD_DOWNSP_X_DCAP_MAX_BPC_8
Downstream port maximum 8 bits per color.
XDP_DPCD_DOWNSP_X_DCAP_MAX_BPC_10
Downstream port maximum 10 bits per color.
XDP_DPCD_DOWNSP_X_DCAP_MAX_BPC_12
Downstream port maximum 12 bits per color.
XDP_DPCD_DOWNSP_X_DCAP_MAX_BPC_16
Downstream port maximum 16 bits per color.
XDP_DPCD_DOWNSP_X_DCAP_HDMI_DPPP_FS2FP_MASK
Downstream port HDMI/DP++ frame sequential to frame pack mask.
XDP_DPCD_DOWNSP_X_DCAP_DVI_DL_MASK
Downstream port DVI dual-link mask.
XDP_DPCD_DOWNSP_X_DCAP_DVI_HCD_MASK
Downstream port DVI high color depth mask.
XDP_DPCD_LINK_BW_SET_162GBPS
Link bandwidth 1.62 Gbps.
XDP_DPCD_LINK_BW_SET_270GBPS
Link bandwidth 2.70 Gbps.
XDP_DPCD_LINK_BW_SET_540GBPS
Link bandwidth 5.40 Gbps.
XDP_DPCD_LINK_BW_SET_810GBPS
Link bandwidth 8.10 Gbps.
XDP_DPCD_LANE_COUNT_SET_MASK
Lane count set mask.
XDP_DPCD_LANE_COUNT_SET_1
Lane count set to 1.
XDP_DPCD_LANE_COUNT_SET_2
Lane count set to 2.
XDP_DPCD_LANE_COUNT_SET_4
Lane count set to 4.
XDP_DPCD_ENHANCED_FRAME_EN_MASK
Enhanced frame enable mask.
XDP_DPCD_TP_SEL_MASK
Training pattern select mask.
XDP_DPCD_TP_SEL_OFF
Training pattern off.
XDP_DPCD_TP_SEL_TP1
Training pattern 1.
XDP_DPCD_TP_SEL_TP2
Training pattern 2.
XDP_DPCD_TP_SEL_TP3
Training pattern 3.
XDP_DPCD_TP_SEL_TP4
Training pattern 4.
XDP_DPCD_TP_SET_LQP_MASK
Link quality pattern mask.
XDP_DPCD_TP_SET_LQP_SHIFT
Shift bits for link quality pattern.
XDP_DPCD_TP_SET_LQP_OFF
Link quality pattern off.
XDP_DPCD_TP_SET_LQP_D102_TEST
D10.2 test pattern.
XDP_DPCD_TP_SET_LQP_SER_MES
Symbol error rate measurement pattern.
XDP_DPCD_TP_SET_LQP_PRBS7
PRBS7 pattern.
XDP_DPCD_TP_SET_REC_CLK_OUT_EN_MASK
Recovered clock output enable mask.
XDP_DPCD_TP_SET_SCRAMB_DIS_MASK
Scrambler disable mask.
XDP_DPCD_TP_SET_SE_COUNT_SEL_MASK
Symbol error count select mask.
XDP_DPCD_TP_SET_SE_COUNT_SEL_SHIFT
Shift bits for symbol error count select.
XDP_DPCD_TP_SET_SE_COUNT_SEL_DE_ISE
Disparity error and illegal symbol error.
XDP_DPCD_TP_SET_SE_COUNT_SEL_DE
Disparity error only.
XDP_DPCD_TP_SET_SE_COUNT_SEL_ISE
Illegal symbol error only.
XDP_DPCD_TRAINING_LANEX_SET_VS_MASK
Voltage swing mask.
XDP_DPCD_TRAINING_LANEX_SET_MAX_VS_MASK
Maximum voltage swing reached mask.
XDP_DPCD_TRAINING_LANEX_SET_PE_MASK
Pre-emphasis mask.
XDP_DPCD_TRAINING_LANEX_SET_PE_SHIFT
Shift bits for pre-emphasis.
XDP_DPCD_TRAINING_LANEX_SET_MAX_PE_MASK
Maximum pre-emphasis reached mask.
XDP_DPCD_SPREAD_AMP_MASK
Spread amplitude mask.
XDP_DPCD_MSA_TIMING_PAR_IGNORED_EN_MASK
MSA timing parameters ignored enable mask.
XDP_DPCD_TRAINING_LANE_0_2_SET_PC2_MASK
Post-cursor2 for lane 0/2 mask.
XDP_DPCD_TRAINING_LANE_0_2_SET_MAX_PC2_MASK
Maximum post-cursor2 for lane 0/2 reached mask.
XDP_DPCD_TRAINING_LANE_1_3_SET_PC2_MASK
Post-cursor2 for lane 1/3 mask.
XDP_DPCD_TRAINING_LANE_1_3_SET_PC2_SHIFT
Shift bits for post-cursor2 lane 1/3.
XDP_DPCD_TRAINING_LANE_1_3_SET_MAX_PC2_MASK
Maximum post-cursor2 for lane 1/3 reached mask.
XDP_DPCD_MST_EN_MASK
MST enable mask.
XDP_DPCD_UP_REQ_EN_MASK
Upstream request enable mask.
XDP_DPCD_UP_IS_SRC_MASK
Upstream is source mask.
XDP_DPCD_SINK_COUNT_LOW_MASK
Sink count low bits mask.
XDP_DPCD_SINK_CP_READY_MASK
Sink content protection ready mask.
XDP_DPCD_SINK_COUNT_HIGH_MASK
Sink count high bit mask.
XDP_DPCD_SINK_COUNT_HIGH_LOW_SHIFT
Shift bits for sink count high/low.
XDP_DPCD_STATUS_LANE_0_CR_DONE_MASK
Lane 0 clock recovery done mask.
XDP_DPCD_STATUS_LANE_0_CE_DONE_MASK
Lane 0 channel equalization done mask.
XDP_DPCD_STATUS_LANE_0_SL_DONE_MASK
Lane 0 symbol lock done mask.
XDP_DPCD_STATUS_LANE_1_CR_DONE_MASK
Lane 1 clock recovery done mask.
XDP_DPCD_STATUS_LANE_1_CE_DONE_MASK
Lane 1 channel equalization done mask.
XDP_DPCD_STATUS_LANE_1_SL_DONE_MASK
Lane 1 symbol lock done mask.
XDP_DPCD_STATUS_LANE_2_CR_DONE_MASK
Lane 2 clock recovery done mask.
XDP_DPCD_STATUS_LANE_2_CE_DONE_MASK
Lane 2 channel equalization done mask.
XDP_DPCD_STATUS_LANE_2_SL_DONE_MASK
Lane 2 symbol lock done mask.
XDP_DPCD_STATUS_LANE_3_CR_DONE_MASK
Lane 3 clock recovery done mask.
XDP_DPCD_STATUS_LANE_3_CE_DONE_MASK
Lane 3 channel equalization done mask.
XDP_DPCD_STATUS_LANE_3_SL_DONE_MASK
Lane 3 symbol lock done mask.
XDP_DPCD_LANE_ALIGN_STATUS_UPDATED_IA_DONE_MASK
Interlane align done mask.
XDP_DPCD_LANE_ALIGN_STATUS_UPDATED_DOWNSP_STATUS_CHANGED_MASK
Downstream port status changed mask.
XDP_DPCD_LANE_ALIGN_STATUS_UPDATED_LINK_STATUS_UPDATED_MASK
Link status updated mask.
XDP_DPCD_SINK_STATUS_RX_PORT0_SYNC_STATUS_MASK
RX port 0 sync status mask.
XDP_DPCD_SINK_STATUS_RX_PORT1_SYNC_STATUS_MASK
RX port 1 sync status mask.
XDP_DPCD_ADJ_REQ_LANE_0_2_VS_MASK
Voltage swing adjust request for lane 0/2 mask.
XDP_DPCD_ADJ_REQ_LANE_0_2_PE_MASK
Pre-emphasis adjust request for lane 0/2 mask.
XDP_DPCD_ADJ_REQ_LANE_0_2_PE_SHIFT
Shift bits for pre-emphasis lane 0/2.
XDP_DPCD_ADJ_REQ_LANE_1_3_VS_MASK
Voltage swing adjust request for lane 1/3 mask.
XDP_DPCD_ADJ_REQ_LANE_1_3_VS_SHIFT
Shift bits for voltage swing lane 1/3.
XDP_DPCD_ADJ_REQ_LANE_1_3_PE_MASK
Pre-emphasis adjust request for lane 1/3 mask.
XDP_DPCD_ADJ_REQ_LANE_1_3_PE_SHIFT
Shift bits for pre-emphasis lane 1/3.
XDP_DPCD_ADJ_REQ_PC2_LANE_0_MASK
Post-cursor2 adjust request for lane 0 mask.
XDP_DPCD_ADJ_REQ_PC2_LANE_1_MASK
Post-cursor2 adjust request for lane 1 mask.
XDP_DPCD_ADJ_REQ_PC2_LANE_1_SHIFT
Shift bits for post-cursor2 lane 1.
XDP_DPCD_ADJ_REQ_PC2_LANE_2_MASK
Post-cursor2 adjust request for lane 2 mask.
XDP_DPCD_ADJ_REQ_PC2_LANE_2_SHIFT
Shift bits for post-cursor2 lane 2.
XDP_DPCD_ADJ_REQ_PC2_LANE_3_MASK
Post-cursor2 adjust request for lane 3 mask.
XDP_DPCD_ADJ_REQ_PC2_LANE_3_SHIFT
Shift bits for post-cursor2 lane 3.
XDP_SEGPTR_ADDR
Segment pointer address.
XDP_EDID_ADDR
EDID base address.
XDP_EDID_BLOCK_SIZE
EDID block size in bytes.
XDP_EDID_DTD_DD
Detailed timing descriptor address.
XDP_EDID_PTM
Preferred timing mode.
XDP_EDID_EXT_BLOCK_COUNT
Extension block count offset.
XDP_EDID_DTD_PIXEL_CLK_KHZ_LSB
Pixel clock LSB in kHz.
XDP_EDID_DTD_PIXEL_CLK_KHZ_MSB
Pixel clock MSB in kHz.
XDP_EDID_DTD_HRES_LSB
Horizontal resolution LSB.
XDP_EDID_DTD_HBLANK_LSB
Horizontal blanking LSB.
XDP_EDID_DTD_HRES_HBLANK_U4
Horizontal resolution/blanking upper 4 bits.
XDP_EDID_DTD_VRES_LSB
Vertical resolution LSB.
XDP_EDID_DTD_VBLANK_LSB
Vertical blanking LSB.
XDP_EDID_DTD_VRES_VBLANK_U4
Vertical resolution/blanking upper 4 bits.
XDP_EDID_DTD_HFPORCH_LSB
Horizontal front porch LSB.
XDP_EDID_DTD_HSPW_LSB
Horizontal sync pulse width LSB.
XDP_EDID_DTD_VFPORCH_VSPW_L4
Vertical front porch/sync width lower 4 bits.
XDP_EDID_DTD_XFPORCH_XSPW_U2
Horizontal/vertical front porch/sync width upper 2 bits.
XDP_EDID_DTD_HIMGSIZE_MM_LSB
Horizontal image size in mm LSB.
XDP_EDID_DTD_VIMGSIZE_MM_LSB
Vertical image size in mm LSB.
XDP_EDID_DTD_XIMGSIZE_MM_U4
Horizontal/vertical image size upper 4 bits.
XDP_EDID_DTD_HBORDER
Horizontal border.
XDP_EDID_DTD_VBORDER
Vertical border.
XDP_EDID_DTD_SIGNAL
Signal characteristics.
XDP_EDID_DTD_XRES_XBLANK_U4_XBLANK_MASK
Horizontal/vertical blanking upper bits mask.
XDP_EDID_DTD_XRES_XBLANK_U4_XRES_MASK
Horizontal/vertical resolution upper bits mask.
XDP_EDID_DTD_XRES_XBLANK_U4_XRES_SHIFT
Shift bits for resolution upper bits.
XDP_EDID_DTD_VFPORCH_VSPW_L4_VSPW_MASK
Vertical sync pulse width lower bits mask.
XDP_EDID_DTD_VFPORCH_VSPW_L4_VFPORCH_MASK
Vertical front porch lower bits mask.
XDP_EDID_DTD_VFPORCH_VSPW_L4_VFPORCH_SHIFT
Shift bits for vertical front porch.
XDP_EDID_DTD_XFPORCH_XSPW_U2_HFPORCH_MASK
Horizontal front porch upper bits mask.
XDP_EDID_DTD_XFPORCH_XSPW_U2_HSPW_MASK
Horizontal sync pulse width upper bits mask.
XDP_EDID_DTD_XFPORCH_XSPW_U2_VFPORCH_MASK
Vertical front porch upper bits mask.
XDP_EDID_DTD_XFPORCH_XSPW_U2_VSPW_MASK
Vertical sync pulse width upper bits mask.
XDP_EDID_DTD_XFPORCH_XSPW_U2_HFPORCH_SHIFT
Shift bits for horizontal front porch upper bits.
XDP_EDID_DTD_XFPORCH_XSPW_U2_HSPW_SHIFT
Shift bits for horizontal sync width upper bits.
XDP_EDID_DTD_XFPORCH_XSPW_U2_VFPORCH_SHIFT
Shift bits for vertical front porch upper bits.
XDP_EDID_DTD_XIMGSIZE_MM_U4_VIMGSIZE_MM_MASK
Vertical image size upper bits mask.
XDP_EDID_DTD_XIMGSIZE_MM_U4_HIMGSIZE_MM_MASK
Horizontal image size upper bits mask.
XDP_EDID_DTD_XIMGSIZE_MM_U4_HIMGSIZE_MM_SHIFT
Shift bits for horizontal image size upper bits.
XDP_EDID_DTD_SIGNAL_HPOLARITY_MASK
Horizontal sync polarity mask.
XDP_EDID_DTD_SIGNAL_VPOLARITY_MASK
Vertical sync polarity mask.
XDP_EDID_DTD_SIGNAL_HPOLARITY_SHIFT
Shift bits for horizontal sync polarity.
XDP_EDID_DTD_SIGNAL_VPOLARITY_SHIFT
Shift bits for vertical sync polarity.
XDP_TX_STREAM_ID1
Stream ID 1.
Referenced by Dptx_MstExampleRun.
XDP_TX_STREAM_ID2
Stream ID 2.
Referenced by Dptx_MstExampleRun.
XDP_TX_STREAM_ID3
Stream ID 3.
Referenced by Dptx_MstExampleRun.
XDP_TX_STREAM_ID4
Stream ID 4.
Referenced by Dptx_MstExampleRun.
XDP_TX_AUDIO_CONTROL_LANEX_SET_SHIFT
Shift bits for audio control lane set.
XDP_RX_STREAM_ID1
Stream ID 1.
XDP_RX_STREAM_ID2
Stream ID 2.
XDP_RX_STREAM_ID3
Stream ID 3.
XDP_RX_STREAM_ID4
Stream ID 4.
XDP_SBMSG_LINK_ADDRESS
Link address message.
XDP_SBMSG_CONNECTION_STATUS_NOTIFY
Connection status notify message.
XDP_SBMSG_ENUM_PATH_RESOURCES
Enumerate path resources message.
XDP_SBMSG_ALLOCATE_PAYLOAD
Allocate payload message.
XDP_SBMSG_QUERY_PAYLOAD
Query payload message.
XDP_SBMSG_RESOURCE_STATUS_NOTIFY
Resource status notify message.
XDP_SBMSG_CLEAR_PAYLOAD_ID_TABLE
Clear payload ID table message.
XDP_SBMSG_REMOTE_DPCD_READ
Remote DPCD read message.
XDP_SBMSG_REMOTE_DPCD_WRITE
Remote DPCD write message.
XDP_SBMSG_REMOTE_I2C_READ
Remote I2C read message.
XDP_SBMSG_REMOTE_I2C_WRITE
Remote I2C write message.
XDP_SBMSG_POWER_UP_PHY
Power up PHY message.
XDP_SBMSG_POWER_DOWN_PHY
Power down PHY message.
XDP_SBMSG_SINK_EVENT_NOTIFY
Sink event notify message.
XDP_SBMSG_QUERY_STREAM_ENCRYPT_STATUS
Query stream encryption status message.
XDP_SBMSG_NAK_REASON_WRITE_FAILURE
NAK reason: Write failure.
XDP_SBMSG_NAK_REASON_INVALID_RAD
NAK reason: Invalid RAD.
XDP_SBMSG_NAK_REASON_CRC_FAILURE
NAK reason: CRC failure.
XDP_SBMSG_NAK_REASON_BAD_PARAM
NAK reason: Bad parameter.
XDP_SBMSG_NAK_REASON_DEFER
NAK reason: Defer.
XDP_SBMSG_NAK_REASON_LINK_FAILURE
NAK reason: Link failure.
XDP_SBMSG_NAK_REASON_NO_RESOURCES
NAK reason: No resources.
XDP_SBMSG_NAK_REASON_DPCD_FAIL
NAK reason: DPCD failure.
XDP_SBMSG_NAK_REASON_I2C_NAK
NAK reason: I2C NAK.
XDP_SBMSG_NAK_REASON_ALLOCATE_FAIL
NAK reason: Allocate failure.
XDp_In32
Macro for reading 32-bit values from a DisplayPort register address.
XDp_Out32
Macro for writing 32-bit values to a DisplayPort register address.
XDp_CoreType
XDp_DynamicRange
Dp_Rx_HandlerType
XDp_Tx_HandlerType
typedef void(* XDp_TimerHandler)(void *InstancePtr, u32 MicroSeconds))(void *InstancePtr, u32 MicroSeconds)
Callback type which represents a custom timer wait handler.
This is only used for Microblaze since it doesn't have a native sleep function. To avoid dependency on a hardware timer, the default wait functionality is implemented using loop iterations; this isn't too accurate. If a custom timer handler is used, the user may implement their own wait implementation using a hardware timer (see example/) for better accuracy. InstancePtr is a pointer to the XDp instance. MicroSeconds is the number of microseconds to be passed to the timer function. None.
typedef void(* XDp_IntrHandler)(void *InstancePtr))(void *InstancePtr)
Callback type which represents the handler for interrupts.
InstancePtr is a pointer to the XDp instance. None.
u8 GuidTable[16][XDP_GUID_NBYTES][16][XDP_GUID_NBYTES]
This table contains a list of global unique identifiers (GUIDs) that will be issued when exploring the topology using the algorithm in the XDp_TxFindAccessibleDpDevices function.
XDp_Config XDp_ConfigTable[XPAR_XDP_NUM_INSTANCES][XPAR_XDP_NUM_INSTANCES]
A table of configuration structures containing the configuration information for each DisplayPort TX core in the system.
void XDp_CfgInitialize(XDp *InstancePtr, XDp_Config *ConfigPtr, UINTPTR EffectiveAddr)
This function retrieves the configuration for this DisplayPort instance and fills in the InstancePtr->Config structure.
InstancePtr is a pointer to the XDp instance. ConfigPtr is a pointer to the configuration structure that will be used to copy the settings from. EffectiveAddr is the device base address in the virtual memory space. If the address translation is not used, then the physical address is passed. Unexpected errors may occur if the address mapping is changed after this function is invoked.
References XDp_Config::BaseAddr, XDp::Config, XDp_TxLinkConfig::cr_done_cnt, XDp_TxLinkConfig::cr_done_oldstate, XDp::IsReady, XDp_Tx::LinkConfig, XDp_TxLinkConfig::MaxLaneCount, XDp_GetCoreType.
Referenced by Dp_SelfTestExample, Dptx_SetupExample.
u32 XDp_Initialize(XDp *InstancePtr)
This function prepares the DisplayPort core for use depending on whether the core is operating in TX or RX mode.
InstancePtr is a pointer to the XDp instance. XST_SUCCESS if the DisplayPort core was successfully initialized.XST_FAILURE otherwise. None.
References XDp::IsReady, XDp_GetCoreType.
Referenced by Dptx_SetupExample.
void XDp_SetUserTimerHandler(XDp *InstancePtr, XDp_TimerHandler CallbackFunc, void *CallbackRef)
This function installs a custom delay/sleep function to be used by the XDp driver.
InstancePtr is a pointer to the XDp instance. CallbackFunc is the address to the callback function. CallbackRef is the user data item (microseconds to delay) that will be passed to the custom sleep/delay function when it is invoked. None.
References XDp::UserTimerPtr, XDp::UserTimerWaitUs.
Referenced by Dptx_TimerExample.
void XDp_WaitUs(XDp *InstancePtr, u32 MicroSeconds)
This function is the delay/sleep function for the XDp driver.
For the Zynq family, there exists native sleep functionality. For MicroBlaze however, there does not exist such functionality. In the MicroBlaze case, the default method for delaying is to use a predetermined amount of loop iterations. This method is prone to inaccuracy and dependent on system configuration; for greater accuracy, the user may supply their own delay/sleep handler, pointed to by InstancePtr->UserTimerWaitUs, which may have better accuracy if a hardware timer is used. InstancePtr is a pointer to the XDp instance. MicroSeconds is the number of microseconds to delay/sleep for. None.
References XDp::IsReady, XDp::UserTimerWaitUs.
Referenced by Dptx_MstExampleRun.
u8 XDp_IsLinkRateValid(XDp *InstancePtr, u8 LinkRate)
This function checks the validity of the link rate.
InstancePtr is a pointer to the XDp instance. LinkRate is the link rate to check if valid. 1 if specified link rate is valid.0 otherwise, if the link rate specified isn't valid as per spec, or if it exceeds the capabilities of the TX core. None.
References XDp::Config, XDp_Config::MaxLinkRate, XDP_LINK_BW_SET_162GBPS, XDP_LINK_BW_SET_270GBPS, XDP_LINK_BW_SET_540GBPS, XDP_LINK_BW_SET_810GBPS.
u8 XDp_IsLaneCountValid(XDp *InstancePtr, u8 LaneCount)
This function checks the validity of the lane count.
InstancePtr is a pointer to the XDp instance. LaneCount is the number of lanes to check if valid. 1 if specified lane count is valid.0 otherwise, if the lane count specified isn't valid as per spec, or if it exceeds the capabilities of the TX core. None.
References XDp::Config, XDp_Config::MaxLaneCount, XDP_LANE_COUNT_SET_1, XDP_LANE_COUNT_SET_2, XDP_LANE_COUNT_SET_4.
XDp_Config * XDp_LookupConfig(UINTPTR BaseAddress)
This function looks for the device configuration based on the unique device ID.
The table XDp_ConfigTable[] contains the configuration information for each device in the system. DeviceId is the unique device ID of the device being looked up. A pointer to the configuration table entry corresponding to the given device ID, or NULL if no match is found. None.
Referenced by Dp_SelfTestExample, Dptx_SetupExample.
u32 XDp_TxGetRxCapabilities(XDp *InstancePtr)
u32 XDp_TxTp4Capable(XDp *InstancePtr)
void XDp_InterruptHandler(XDp *InstancePtr)
This function is the interrupt handler for the XDp driver.
When an interrupt happens, this interrupt handler will check which TX/RX mode of operation the core is running in, and will call the appropriate interrupt handler. The called interrupt handler will first detect what kind of interrupt happened, then decides which callback function to invoke. InstancePtr is a pointer to the XDp instance. None.
References XDp::IsReady, XDp_GetCoreType.
u32 XDp_SelfTest(XDp *InstancePtr)
This function runs a self-test on the XDp driver/device depending on whether the core is operating in TX or RX mode.
The sanity test checks whether or not all tested registers hold their default reset values. InstancePtr is a pointer to the XDp instance. XST_SUCCESS if the self-test passed - all tested registers hold their default reset values.XST_FAILURE otherwise. None.
References XDp::IsReady, XDp_GetCoreType.
Referenced by Dp_SelfTestExample.
XDP_AUX_MAX_DEFER_COUNT
XDP_AUX_MAX_TIMEOUT_COUNT
XDP_IS_CONNECTED_MAX_TIMEOUT_COUNT
XPAR_XDPTXSS_NUM_INSTANCES
XPAR_XDPRXSS_NUM_INSTANCES
XDp_GetCoreType
This is function determines whether the DisplayPort core, represented by the XDp structure pointed to, is a transmitter (TX) or a receiver (RX).
InstancePtr is a pointer to the XDp instance. XDP_RX if the core is of type RX. XDP_TX if the core is of type TX. C-style signature: XDp_CoreType XDp_GetCoreType(XDp *InstancePtr)
Referenced by XDp_CfgInitialize, XDp_Initialize, XDp_InterruptHandler, XDp_SelfTest.
XDp_TxCfgSetRGB
The following functions set the color encoding scheme for a given stream.
InstancePtr is a pointer to the XDp instance. Stream is the stream number for which to configure the color encoding scheme for. XST_SUCCESS. C-style signatures: u32 XDp_TxCfgSetRGB(XDp *InstancePtr, u8 Stream) u32 XDp_TxCfgSetSRGB(XDp *InstancePtr, u8 Stream) u32 XDp_TxCfgSetYonly(XDp *InstancePtr, u8 Stream) u32 XDp_TxCfgSetYCbCr422Bt601(XDp *InstancePtr, u8 Stream) u32 XDp_TxCfgSetYCbCr422Bt709(XDp *InstancePtr, u8 Stream) u32 XDp_TxCfgSetYCbCr444Bt601(XDp *InstancePtr, u8 Stream) u32 XDp_TxCfgSetYCbCr444Bt709(XDp *InstancePtr, u8 Stream) u32 XDp_TxCfgSetXvYcc422Bt601(XDp *InstancePtr, u8 Stream) u32 XDp_TxCfgSetXvYcc422Bt709(XDp *InstancePtr, u8 Stream) u32 XDp_TxCfgSetXvYcc444Bt601(XDp *InstancePtr, u8 Stream) u32 XDp_TxCfgSetXvYcc444Bt709(XDp *InstancePtr, u8 Stream) u32 XDp_TxCfgSetAdbRGB(XDp *InstancePtr, u8 Stream)
XDp_TxCfgSetSRGB
XDp_TxCfgSetYonly
XDp_TxCfgSetYCbCr422Bt601
XDp_TxCfgSetYCbCr422Bt709
XDp_TxCfgSetYCbCr444Bt601
XDp_TxCfgSetYCbCr444Bt709
XDp_TxCfgSetXvYcc422Bt601
XDp_TxCfgSetXvYcc422Bt709
XDp_TxCfgSetXvYcc444Bt601
XDp_TxCfgSetXvYcc444Bt709
XDp_TxCfgSetAdbRGB
XDptx_ReadReg
XDprx_ReadReg
XDptx_WriteReg
XDprx_WriteReg
XDptx_Config
XDprx_Config
XDptx_TimerHandler
XDprx_TimerHandler
XDptx_HpdEventHandler
XDptx_HpdPulseHandler
XDprx_IntrHandler
XDptx_LookupConfig
XDprx_LookupConfig
XDptx_CfgInitialize
XDprx_CfgInitialize
XDptx_InitializeTx
XDprx_InitializeRx
XDptx_WaitUs
XDprx_WaitUs
XDptx_SetUserTimerHandler
XDprx_SetUserTimerHandler
XDptx_SelfTest
XDprx_SelfTest
XDptx_HpdInterruptHandler
XDprx_InterruptHandler
XDptx
XDprx
XDPTX
XDPRX
XDp_TxSbMsgLinkAddressReplyDeviceInfo
XDp_TxSbMsgLinkAddressReplyPortDetail
XPAR_XDPTXSS_NUM_INSTANCES
XPAR_XDPRXSS_NUM_INSTANCES
XDP_RX_NUM_I2C_ENTRIES_PER_PORT
The number of I2C user- defined entries in the I2C map of each port.
XDP_GUID_NBYTES
The number of bytes for the global unique ID.
XDP_MAX_NPORTS
The maximum number of ports connected to a DisplayPort device.
XDp_ReadReg
This is a low-level function that reads from the specified register.
BaseAddress is the base address of the device. RegOffset is the register offset to be read from. The 32-bit value of the specified register. C-style signature: u32 XDp_ReadReg(UINTPTR BaseAddress, u32 RegOffset)
Referenced by Dptx_MstExampleRun, Dptx_StartLink.
XDp_WriteReg
This is a low-level function that writes to the specified register.
BaseAddress is the base address of the device. RegOffset is the register offset to write to. Data is the 32-bit data to write to the specified register. None. C-style signature: void XDp_WriteReg(UINTPTR BaseAddress, u32 RegOffset, u32 Data)
Referenced by Dptx_MstExampleRun.
XDP_MAX_LENGTH_SBMSG
XDP_MAX_BYTES_TO_READ
XDP_DOWN_REQ_OFFSET
XDP_MST_DEVICE_DETECTED
XDP_MST_SOURCE_DEVICE_DETECTED
XDP_MST_BRANCH_DEVICE_DETECTED
XDP_MST_SINK_DEVICE_DETECTED