v_mix
XVMix_BackgroundId
XVMix_Scalefactor
XVMix_LayerId
XVMix_LayerType
XVMix_ErrorCodes
typedef void(* XVMix_Callback)(void *CallbackRef))(void *CallbackRef)
Callback type for interrupt.
CallbackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. None. None.
const u8 bkgndColorYUV[XVMIX_BKGND_LAST][3][XVMIX_BKGND_LAST][3]
const u8 bkgndColorRGB[XVMIX_BKGND_LAST][3][XVMIX_BKGND_LAST][3]
const s32 xv_mix_yuv2rgb_coeffs[XVMIX_CSC_MAX_ROWS][XVMIX_CSC_MAX_COLS][XVMIX_CSC_COEFF_SIZE][XVMIX_CSC_MAX_ROWS][XVMIX_CSC_MAX_COLS][XVMIX_CSC_COEFF_SIZE]
const s32 xv_mix_rgb2yuv_coeffs[XVMIX_CSC_MAX_ROWS][XVMIX_CSC_MAX_COLS][XVMIX_CSC_COEFF_SIZE][XVMIX_CSC_MAX_ROWS][XVMIX_CSC_MAX_COLS][XVMIX_CSC_COEFF_SIZE]
static void SetPowerOnDefaultState(XV_Mix_l2 *InstancePtr)
Sets the XV_Mix_l2 instance to its power-on default state.
This function initializes the video mixer instance to a known default state after power-on or reset. The following actions are performed: Disables all video layers.Sets up a default video stream configuration with custom mode, color format, frame rate, color depth, and active video dimensions based on the IP configuration.Applies the default video stream to the mixer.Sets the default background color to blue with the configured color depth.For each layer, if scaling is disabled, updates the layer's maximum width to the IP's maximum width.Enables only the master (stream) layer.Disables interrupts to set up polling mode. InstancePtr Pointer to the XV_Mix_l2 instance to be initialized. None
static int IsWindowValid(XVidC_VideoStream *Strm, XVidC_VideoWindow *Win, XVMix_Scalefactor Scale)
Checks if a given video window is valid within the bounds of a video stream, considering a specified scaling factor.
This function creates a copy of the provided window, applies the scaling factor to its width and height, and then verifies whether the scaled window fits within the active area of the video stream. Strm Pointer to the video stream structure containing timing info. Win Pointer to the video window structure to validate. Scale Scaling factor to apply to the window dimensions. TRUE if the scaled window fits within the stream's active area, FALSE otherwise.
int XVMix_Initialize(XV_Mix_l2 *InstancePtr, UINTPTR BaseAddress)
XVMix_Initialize - Initialize the XV_Mix_l2 instance for SDT flow.
This function initializes the XV_Mix_l2 instance specified by InstancePtr using the hardware configuration at the given BaseAddress. It first asserts that the provided pointer is not NULL, clears the instance memory, and then calls the lower-level XV_mix_Initialize function. If initialization is successful, it sets the instance to its power-on default state. InstancePtr Pointer to the XV_Mix_l2 instance to be initialized. BaseAddress Base address of the hardware configuration to use. XST_SUCCESS if initialization was successful.Error code defined by XV_mix_Initialize otherwise.
References XV_Mix_l2::Mix, XV_mix_Initialize.
void XVMix_InterruptEnable(XV_Mix_l2 *InstancePtr)
Enables interrupts for the XV_Mix_l2 instance.
This function performs the following actions: Asserts that the provided instance pointer is not NULL.Enables the DONE interrupt for the underlying XV_mix hardware.Globally enables interrupts for the XV_mix hardware.Disables the auto-restart feature of the XV_mix hardware. InstancePtr Pointer to the XV_Mix_l2 instance.
References XV_Mix_l2::Mix, XV_mix_DisableAutoRestart, XV_mix_InterruptEnable, XV_mix_InterruptGlobalEnable.
void XVMix_InterruptDisable(XV_Mix_l2 *InstancePtr)
XVMix_InterruptDisable - Disables interrupts for the XV_Mix_l2 instance.
This function disables the DONE interrupt and the global interrupt for the specified XV_Mix_l2 instance. After disabling interrupts, it enables the auto-restart feature to allow the hardware to automatically restart processing without requiring software intervention. InstancePtr Pointer to the XV_Mix_l2 instance. The InstancePtr must not be NULL.
References XV_Mix_l2::Mix, XV_mix_EnableAutoRestart, XV_mix_InterruptDisable, XV_mix_InterruptGlobalDisable.
void XVMix_Start(XV_Mix_l2 *InstancePtr)
Starts the video mixer hardware.
This function asserts that the provided instance pointer is not NULL, and then starts the underlying XV_mix hardware by calling its Start function. InstancePtr Pointer to the XV_Mix_l2 instance to be started.
References XV_Mix_l2::Mix, XV_mix_Start.
void XVMix_Stop(XV_Mix_l2 *InstancePtr)
Stops the XV_Mix_l2 core operation.
This function disables the autostart feature, initiates a flush operation, and waits for the flush to complete or until a timeout occurs. InstancePtr Pointer to the XV_Mix_l2 instance. The function performs the following steps: Asserts that the instance pointer is not NULL.Disables the autostart mode of the core.Sets the flush bit to initiate a flush operation.Waits for the flush operation to complete by polling the flush done status, with a timeout to prevent indefinite waiting.Returns early if the flush operation does not complete within the timeout.
References XV_Mix_l2::Mix, XV_mix_DisableAutoRestart, XV_mix_Get_FlushDone, XV_mix_SetFlushbit.
void XVMix_SetVidStream(XV_Mix_l2 *InstancePtr, const XVidC_VideoStream *StrmIn)
Sets the video stream configuration for the mixer instance.
This function copies the provided video stream structure into the mixer instance, and programs the hardware registers for the active video width and height. InstancePtr Pointer to the XV_Mix_l2 instance. StrmIn Pointer to the input XVidC_VideoStream structure. The function asserts that the input pointers are valid and that the resolution is within the supported range.
References XV_mix::Config, XV_mix_Config::MaxHeight, XV_mix_Config::MaxWidth, XV_Mix_l2::Mix, XV_Mix_l2::Stream, XV_mix_Set_HwReg_height, XV_mix_Set_HwReg_width.
int XVMix_LayerEnable(XV_Mix_l2 *InstancePtr, XVMix_LayerId LayerId)
This function enables the specified layer of the core instance.
InstancePtr is a pointer to core instance to be worked upon LayerId is layer number to be enabled XST_SUCCESS or XST_FAILURE To enable all layers use layer id XVMIX_LAYER_ALL
References XV_Mix_l2::Mix, XV_mix_Get_HwReg_layerEnable, XV_mix_Set_HwReg_layerEnable, XVMix_GetNumLayers, XVMix_IsLogoEnabled.
int XVMix_LayerDisable(XV_Mix_l2 *InstancePtr, XVMix_LayerId LayerId)
This function disables the specified layer of the core instance.
InstancePtr is a pointer to core instance to be worked upon LayerId is layer number to be disabled XST_SUCCESS or XST_FAILURE To disable all layers use layer id XVMIX_LAYER_ALL
References XV_Mix_l2::Mix, XV_mix_Get_HwReg_layerEnable, XV_mix_Set_HwReg_layerEnable, XVMix_GetNumLayers, XVMix_IsLogoEnabled.
int XVMix_IsLayerEnabled(XV_Mix_l2 *InstancePtr, XVMix_LayerId LayerId)
This function returns state of the specified layer [enabled or disabled].
InstancePtr is a pointer to the core instance. LayerId is the layer index for which information is requested Enabled(1)/Disabled(0)
References XV_Mix_l2::Mix, XV_mix_Get_HwReg_layerEnable.
Referenced by XVMix_DbgLayerInfo, XVMix_DbgReportStatus.
void XVMix_SetBackgndColor(XV_Mix_l2 *InstancePtr, XVMix_BackgroundId ColorId, XVidC_ColorDepth bpc)
This function sets the background color to be displayed when stream layer is disabled.
InstancePtr is a pointer to core instance to be worked upon ColorId is requested background color bpc is color depth none
References XV_Mix_l2::Mix, XV_mix_Get_HwReg_video_format, XV_mix_Set_HwReg_background_U_G, XV_mix_Set_HwReg_background_V_B, XV_mix_Set_HwReg_background_Y_R.
int XVMix_SetLayerWindow(XV_Mix_l2 *InstancePtr, XVMix_LayerId LayerId, XVidC_VideoWindow *Win, u32 StrideInBytes)
This function configures the window coordinates of the specified layer.
InstancePtr is a pointer to core instance to be worked upon LayerId is the layer for which window coordinates are to be set Win is the window coordinates in pixels StrideInBytes is the stride of the requested window yuv422 Color space requires 2 Bytes/Pixel yuv444 Color space requires 4 Bytes/Pixel Equation to compute stride is as follows Stride = (Window_Width * (YUV422 ? 2 : 4)) (Applicable only when layer type is Memory) XST_SUCCESS if command is successful else error code with reason Applicable only for Layer1-8 and Logo Layer
References XV_mix_Config::BaseAddress, XV_mix::Config, XV_Mix_l2::Layer, XV_Mix_l2::LogoLayer, XV_mix_Config::MaxHeight, XV_mix_Config::MaxLogoHeight, XV_mix_Config::MaxLogoWidth, XV_Mix_l2::Mix, XV_mix_Config::PixPerClk, XV_Mix_l2::Stream, XV_MIX_CTRL_ADDR_HWREG_LAYERHEIGHT_0_DATA, XV_MIX_CTRL_ADDR_HWREG_LAYERSTARTX_0_DATA, XV_MIX_CTRL_ADDR_HWREG_LAYERSTARTY_0_DATA, XV_MIX_CTRL_ADDR_HWREG_LAYERSTRIDE_0_DATA, XV_MIX_CTRL_ADDR_HWREG_LAYERWIDTH_0_DATA, XV_mix_Set_HwReg_logoHeight, XV_mix_Set_HwReg_logoStartX, XV_mix_Set_HwReg_logoStartY, XV_mix_Set_HwReg_logoWidth, XVMix_GetLayerScaleFactor, XVMix_GetNumLayers, XVMix_IsLayerInterfaceStream, XVMix_IsLogoEnabled.
Referenced by XVMix_LoadLogo.
int XVMix_GetLayerWindow(XV_Mix_l2 *InstancePtr, XVMix_LayerId LayerId, XVidC_VideoWindow *Win)
This function read the window coordinates of the specified layer.
InstancePtr is a pointer to core instance to be worked upon LayerId is the layer for which window coordinates are to be set Win is the pointer to return window coordinates XST_SUCCESS if command is successful else error code with reason Applicable only for Layer1-8 and Logo Layer
References XV_mix_Config::BaseAddress, XV_mix::Config, XV_Mix_l2::Mix, XV_MIX_CTRL_ADDR_HWREG_LAYERHEIGHT_0_DATA, XV_MIX_CTRL_ADDR_HWREG_LAYERSTARTX_0_DATA, XV_MIX_CTRL_ADDR_HWREG_LAYERSTARTY_0_DATA, XV_MIX_CTRL_ADDR_HWREG_LAYERWIDTH_0_DATA, XV_mix_Get_HwReg_logoHeight, XV_mix_Get_HwReg_logoStartX, XV_mix_Get_HwReg_logoStartY, XV_mix_Get_HwReg_logoWidth, XVMix_GetNumLayers, XVMix_IsLogoEnabled.
Referenced by XVMix_DbgLayerInfo, XVMix_MoveLayerWindow, XVMix_SetLayerScaleFactor.
int XVMix_MoveLayerWindow(XV_Mix_l2 *InstancePtr, XVMix_LayerId LayerId, u16 StartX, u16 StartY)
This function moved the window position of the specified layer to new coordinates.
InstancePtr is a pointer to core instance to be worked upon LayerId is the layer for which window position is to be set StartX is the new X position StartY is the new Y position XST_SUCCESS if command is successful else error code with reason Applicable only for Layer1-8 and Logo Layer
References XV_mix_Config::BaseAddress, XV_mix::Config, XV_Mix_l2::Layer, XV_Mix_l2::LogoLayer, XV_Mix_l2::Mix, XV_mix_Config::PixPerClk, XV_Mix_l2::Stream, XV_MIX_CTRL_ADDR_HWREG_LAYERSTARTX_0_DATA, XV_MIX_CTRL_ADDR_HWREG_LAYERSTARTY_0_DATA, XV_mix_Set_HwReg_logoStartX, XV_mix_Set_HwReg_logoStartY, XVMix_GetLayerScaleFactor, XVMix_GetLayerWindow, XVMix_GetNumLayers, XVMix_IsLogoEnabled.
int XVMix_SetLayerScaleFactor(XV_Mix_l2 *InstancePtr, XVMix_LayerId LayerId, XVMix_Scalefactor Scale)
This function configures the scaling factor of the specified layer.
InstancePtr is a pointer to core instance to be worked upon LayerId is the layer to be updated Scale is the scale factor XST_SUCCESS if command is successful else error code with reason Applicable only for Layer1-8 and Logo Layer
References XV_mix_Config::BaseAddress, XV_mix::Config, XV_Mix_l2::Mix, XV_Mix_l2::Stream, XV_MIX_CTRL_ADDR_HWREG_LAYERSCALEFACTOR_0_DATA, XV_mix_Set_HwReg_logoScaleFactor, XVMix_GetLayerWindow, XVMix_GetNumLayers, XVMix_IsLogoEnabled, XVMix_IsScalingEnabled.
int XVMix_GetLayerScaleFactor(XV_Mix_l2 *InstancePtr, XVMix_LayerId LayerId)
This function returns the scaling factor of the specified layer.
InstancePtr is a pointer to core instance to be worked upon LayerId is the layer for which information is requested If layer enabled, current set value, else ~0 Applicable only for Layer1-8 and Logo Layer
References XV_mix_Config::BaseAddress, XV_mix::Config, XV_Mix_l2::Mix, XV_MIX_CTRL_ADDR_HWREG_LAYERSCALEFACTOR_0_DATA, XV_mix_Get_HwReg_logoScaleFactor, XVMix_GetNumLayers, XVMix_IsLogoEnabled, XVMix_IsScalingEnabled.
Referenced by XVMix_DbgLayerInfo, XVMix_MoveLayerWindow, XVMix_SetLayerWindow.
int XVMix_SetLayerAlpha(XV_Mix_l2 *InstancePtr, XVMix_LayerId LayerId, u16 Alpha)
This function configures the Alpha level of the specified layer.
InstancePtr is a pointer to core instance to be worked upon LayerId is the layer to be updated Alpha is the new value XST_SUCCESS if command is successful else error code with reason Applicable only for Layer1-8 and Logo Layer
References XV_mix_Config::BaseAddress, XV_mix::Config, XV_Mix_l2::Mix, XV_MIX_CTRL_ADDR_HWREG_LAYERALPHA_0_DATA, XV_mix_Set_HwReg_logoAlpha, XVMix_GetNumLayers, XVMix_IsAlphaEnabled, XVMix_IsLogoEnabled.
int XVMix_GetLayerAlpha(XV_Mix_l2 *InstancePtr, XVMix_LayerId LayerId)
This function returns the alpha of the specified layer.
InstancePtr is a pointer to core instance to be worked upon LayerId is the layer for which information is requested If layer enabled, current set value, else ~0 Applicable only for Layer1-8 and Logo Layer
References XV_mix_Config::BaseAddress, XV_mix::Config, XV_Mix_l2::Mix, XV_MIX_CTRL_ADDR_HWREG_LAYERALPHA_0_DATA, XV_mix_Get_HwReg_logoAlpha, XVMix_GetNumLayers, XVMix_IsAlphaEnabled, XVMix_IsLogoEnabled.
Referenced by XVMix_DbgLayerInfo.
int XVMix_GetLayerColorFormat(XV_Mix_l2 *InstancePtr, XVMix_LayerId LayerId, XVidC_ColorFormat *Cfmt)
This function reads the color format of the specified layer.
InstancePtr is a pointer to core instance to be worked upon LayerId is the layer to be updated Cfmt is pointer to color format return variable XST_SUCCESS or XST_FAILURE none
References XV_mix_Config::BaseAddress, XV_mix_Config::ColorFormat, XV_mix::Config, XV_Mix_l2::Mix, XV_MIX_CTRL_ADDR_HWREG_LAYERVIDEOFORMAT_0_DATA, XV_mix_Get_HwReg_video_format, XVMix_GetNumLayers.
Referenced by main, XVMix_DbgLayerInfo.
int XVMix_SetLayerBufferAddr(XV_Mix_l2 *InstancePtr, XVMix_LayerId LayerId, UINTPTR Addr)
This function sets the buffer address of the specified layer.
InstancePtr is a pointer to core instance to be worked upon LayerId is the layer to be updated Addr is the absolute address of buffer in memory XST_SUCCESS or XST_FAILURE Applicable only for Layer1-16
References XV_mix_Config::BaseAddress, XV_mix::Config, XV_Mix_l2::Layer, XV_Mix_l2::Mix, XV_mix_Config::PixPerClk, XV_MIX_CTRL_ADDR_HWREG_LAYER1_BUF1_V_DATA, XVMix_GetNumLayers.
UINTPTR XVMix_GetLayerBufferAddr(XV_Mix_l2 *InstancePtr, XVMix_LayerId LayerId)
This function reads the buffer address of the specified layer.
InstancePtr is a pointer to core instance to be worked upon LayerId is the layer to be updated Address of buffer in memory Applicable only for Layer1-16
References XV_mix_Config::BaseAddress, XV_mix::Config, XV_Mix_l2::Mix, XV_MIX_CTRL_ADDR_HWREG_LAYER1_BUF1_V_DATA, XVMix_GetNumLayers.
Referenced by XVMix_DbgLayerInfo.
int XVMix_SetLayerChromaBufferAddr(XV_Mix_l2 *InstancePtr, XVMix_LayerId LayerId, UINTPTR Addr)
This function sets the buffer address of the specified layer for the UV plane for semi-planar formats for the U plane for 3-planar formats.
InstancePtr is a pointer to core instance to be worked upon LayerId is the layer to be updated Addr is the absolute address of second buffer in memory XST_SUCCESS or XST_FAILURE Applicable only for Layer1-16
References XV_mix_Config::BaseAddress, XV_mix::Config, XV_Mix_l2::Layer, XV_Mix_l2::Mix, XV_mix_Config::PixPerClk, XV_MIX_CTRL_ADDR_HWREG_LAYER1_BUF2_V_DATA, XVMix_GetNumLayers.
UINTPTR XVMix_GetLayerChromaBufferAddr(XV_Mix_l2 *InstancePtr, XVMix_LayerId LayerId)
This function reads the buffer address of the specified layer for the UV plane for semi-planar formats and for the U plane for 3-planar formats.
InstancePtr is a pointer to core instance to be worked upon LayerId is the layer to be updated Address of second buffer in memory Applicable only for Layer1-8
References XV_mix_Config::BaseAddress, XV_mix::Config, XV_Mix_l2::Mix, XV_MIX_CTRL_ADDR_HWREG_LAYER1_BUF2_V_DATA, XVMix_GetNumLayers.
Referenced by XVMix_DbgLayerInfo.
int XVMix_SetLayerChromaBuffer2Addr(XV_Mix_l2 *InstancePtr, XVMix_LayerId LayerId, UINTPTR Addr)
Set the chroma buffer address for the specified layer.
This function sets the address of the second chroma buffer for a given layer in the XV_Mix_l2 instance. It checks for valid input parameters, ensures the address is properly aligned according to the AXI memory interface requirements, and writes the address to the appropriate hardware register. The function updates the internal state of the instance with the new buffer address. InstancePtr Pointer to the XV_Mix_l2 instance. LayerId ID of the layer for which the chroma buffer address is to be set. Must be greater than XVMIX_LAYER_MASTER and less than XVMIX_LAYER_LOGO. Addr Physical address of the chroma buffer. Must be non-zero and properly aligned. XST_SUCCESS if the address was set successfully.XVMIX_ERR_MEM_ADDR_MISALIGNED if the address is not properly aligned.XST_FAILURE for other failures (e.g., invalid parameters). The address must be aligned to (2 * PixPerClk * 4) bytes. The function does not perform any memory allocation or buffer management.
References XV_mix_Config::BaseAddress, XV_mix::Config, XV_Mix_l2::Layer, XV_Mix_l2::Mix, XV_mix_Config::PixPerClk, XV_MIX_CTRL_ADDR_HWREG_LAYER1_BUF3_V_DATA, XVMix_GetNumLayers.
UINTPTR XVMix_GetLayerChromaBuffer2Addr(XV_Mix_l2 *InstancePtr, XVMix_LayerId LayerId)
Retrieves the address of the second chroma buffer for a specified layer in the video mixer instance.
InstancePtr : Pointer to the XV_Mix_l2 instance. LayerId : Identifier of the layer for which the chroma buffer address is requested. Must be greater than XVMIX_LAYER_MASTER and less than XVMIX_LAYER_LOGO. The address (UINTPTR) of the second chroma buffer for the specified layer. Returns 0 if the LayerId is invalid or out of range. The function asserts that InstancePtr is not NULL and that LayerId is within the valid range. The function only returns a valid address if LayerId is less than the number of layers configured in the instance.
References XV_mix_Config::BaseAddress, XV_mix::Config, XV_Mix_l2::Mix, XV_MIX_CTRL_ADDR_HWREG_LAYER1_BUF3_V_DATA, XVMix_GetNumLayers.
int XVMix_SetLogoColorKey(XV_Mix_l2 *InstancePtr, XVMix_LogoColorKey ColorKeyData)
Set the logo color key values for the XV_Mix_l2 instance.
This function configures the minimum and maximum RGB values for the logo color key, which are used to enable color keying (transparency) for the logo overlay in the video mixer. The function only sets the color key values if both the logo and logo color key features are enabled in the instance. InstancePtr Pointer to the XV_Mix_l2 instance. ColorKeyData Structure containing the minimum and maximum RGB values for the color key. XST_SUCCESS if the color key values were set successfully.XST_FAILURE if the logo or logo color key feature is not enabled.
References XV_Mix_l2::Mix, XV_mix_Set_HwReg_logoClrKeyMax_B, XV_mix_Set_HwReg_logoClrKeyMax_G, XV_mix_Set_HwReg_logoClrKeyMax_R, XV_mix_Set_HwReg_logoClrKeyMin_B, XV_mix_Set_HwReg_logoClrKeyMin_G, XV_mix_Set_HwReg_logoClrKeyMin_R, XVMix_IsLogoColorKeyEnabled, XVMix_IsLogoEnabled.
int XVMix_GetLogoColorKey(XV_Mix_l2 *InstancePtr, XVMix_LogoColorKey *ColorKeyData)
Retrieves the current logo color key range from the hardware.
InstancePtr Pointer to the XV_Mix_l2 instance. ColorKeyData Pointer to an XVMix_LogoColorKey structure where the color key minimum and maximum RGB values will be stored. This function checks if the logo and logo color key features are enabled. If both are enabled, it reads the minimum and maximum RGB values for the logo color key from the hardware registers and stores them in the provided ColorKeyData structure.XST_SUCCESS if the color key values were successfully retrieved, XST_FAILURE otherwise.
References XV_Mix_l2::Mix, XV_mix_Get_HwReg_logoClrKeyMax_B, XV_mix_Get_HwReg_logoClrKeyMax_G, XV_mix_Get_HwReg_logoClrKeyMax_R, XV_mix_Get_HwReg_logoClrKeyMin_B, XV_mix_Get_HwReg_logoClrKeyMin_G, XV_mix_Get_HwReg_logoClrKeyMin_R, XVMix_IsLogoColorKeyEnabled, XVMix_IsLogoEnabled.
Referenced by XVMix_DbgLayerInfo.
int XVMix_LoadLogo(XV_Mix_l2 *InstancePtr, XVidC_VideoWindow *Win, u8 *RBuffer, u8 *GBuffer, u8 *BBuffer)
Loads a logo image into the mixer hardware.
This function takes separate R, G, and B buffers representing a logo image, and writes the pixel data into the hardware registers of the video mixer for display as a logo overlay. The function supports logos with dimensions and alignment constraints as specified by the hardware configuration. InstancePtr Pointer to the XV_Mix_l2 instance. Win Pointer to an XVidC_VideoWindow structure specifying the position and size of the logo window. RBuffer Pointer to the buffer containing the red channel data. GBuffer Pointer to the buffer containing the green channel data. BBuffer Pointer to the buffer containing the blue channel data. XST_SUCCESS if the logo was loaded successfully.XST_FAILURE if the logo could not be loaded (e.g., invalid parameters or logo not enabled). Preconditions: The logo feature must be enabled in the mixer hardware.The window dimensions and alignment must meet hardware requirements.The input buffers must be valid and sized appropriately for the window. Side Effects: Writes logo pixel data to hardware registers.Updates the logo layer buffer pointers in the instance.
References XV_mix_Config::BaseAddress, XV_mix::Config, XV_Mix_l2::LogoLayer, XV_mix_Config::MaxLogoHeight, XV_mix_Config::MaxLogoWidth, XV_Mix_l2::Mix, XV_mix_Config::PixPerClk, XV_MIX_CTRL_ADDR_HWREG_LOGOB_V_BASE, XV_MIX_CTRL_ADDR_HWREG_LOGOG_V_BASE, XV_MIX_CTRL_ADDR_HWREG_LOGOR_V_BASE, XVMix_IsLogoEnabled, XVMix_SetLayerWindow.
int XVMix_LoadLogoPixelAlpha(XV_Mix_l2 *InstancePtr, XVidC_VideoWindow *Win, u8 *ABuffer)
XVMix_LoadLogoPixelAlpha - Loads per-pixel alpha values for a logo window into the hardware.
InstancePtr Pointer to the XV_Mix_l2 instance. Win Pointer to the XVidC_VideoWindow structure specifying the logo window position and size. ABuffer Pointer to the buffer containing alpha values for each pixel in the logo window. This function loads the per-pixel alpha values from the provided buffer into the hardware registers for the specified logo window. The function checks that the logo and per-pixel alpha features are enabled, and that the window parameters are within valid ranges. The alpha values are packed into 32-bit words (4 pixels per word) and written to the hardware.XST_SUCCESS if the operation is successful, XST_FAILURE otherwise.
References XV_mix_Config::BaseAddress, XV_mix::Config, XV_mix_Config::MaxLogoHeight, XV_mix_Config::MaxLogoWidth, XV_Mix_l2::Mix, XV_mix_Config::PixPerClk, XV_MIX_CTRL_ADDR_HWREG_LOGOA_V_BASE, XVMix_IsLogoEnabled, XVMix_IsLogoPixAlphaEnabled.
void XVMix_DbgReportStatus(XV_Mix_l2 *InstancePtr)
XVMix_DbgReportStatus - Prints the current status and configuration of the mixer instance.
InstancePtr Pointer to the XV_Mix_l2 instance to report status for. This function outputs detailed information about the mixer hardware and its configuration to the standard output using xil_printf. The reported information includes: Pixels per clockColor depthNumber of layersControl register valueLayer enable register valueEnable/disable status of each layer (Master, Layer 1-N, Logo)Background color values (Y/R, U/G, V/B) The function asserts that the provided instance pointer is not NULL. It is intended for debugging and diagnostic purposes.
References XV_mix_Config::BaseAddress, XV_mix::Config, XV_mix_Config::MaxDataWidth, XV_Mix_l2::Mix, XV_mix_Config::PixPerClk, XV_MIX_CTRL_ADDR_AP_CTRL, XV_mix_Get_HwReg_background_U_G, XV_mix_Get_HwReg_background_V_B, XV_mix_Get_HwReg_background_Y_R, XV_mix_Get_HwReg_layerEnable, XVMix_GetNumLayers, XVMix_IsLayerEnabled, XVMix_IsTileFormatEnabled.
void XVMix_DbgLayerInfo(XV_Mix_l2 *InstancePtr, XVMix_LayerId LayerId)
Prints debug information for a specific layer in the video mixer.
InstancePtr Pointer to the XV_Mix_l2 instance. LayerId Identifier of the layer to report (master, logo, or regular layer). This function prints detailed status and configuration information for the specified layer in the video mixer. The information includes: Whether the layer is enabled or disabled.For the master layer: color format, resolution, and stream info.For the logo layer: alpha, scale factor, window position/size, color key data, and pixel alpha status.For regular layers: interface type (memory/stream), buffer addresses, alpha and scaling status/values, color format, window position/size, and stride. The function uses xil_printf for output and is intended for debugging purposes. Assertions are used to validate input parameters.none
References XV_mix_Config::BaseAddress, XV_mix::Config, XV_Mix_l2::Mix, XV_Mix_l2::Stream, XV_MIX_CTRL_ADDR_HWREG_LAYERSTRIDE_0_DATA, XV_mix_Get_HwReg_height, XV_mix_Get_HwReg_width, XVMix_GetLayerAlpha, XVMix_GetLayerBufferAddr, XVMix_GetLayerChromaBufferAddr, XVMix_GetLayerColorFormat, XVMix_GetLayerInterfaceType, XVMix_GetLayerScaleFactor, XVMix_GetLayerWindow, XVMix_GetLogoColorKey, XVMix_IsAlphaEnabled, XVMix_IsLayerEnabled, XVMix_IsLogoColorKeyEnabled, XVMix_IsLogoPixAlphaEnabled, XVMix_IsScalingEnabled.
static void XVMix_SetCoeffForYuvToRgb(XV_Mix_l2 *InstancePtr, XVidC_ColorStd ColorStd, XVidC_ColorRange colorRange, u8 colorDepth)
Sets the coefficients for YUV to RGB color space conversion in the XV_Mix hardware.
This function configures the color space conversion (CSC) matrix coefficients for converting YUV to RGB based on the specified color standard, color range, and color depth. The coefficients are written to the hardware registers of the XV_Mix instance. InstancePtr Pointer to the XV_Mix_l2 instance. ColorStd The color standard to use (e.g., BT.601, BT.709). colorRange The color range (e.g., full range, limited range). colorDepth The color depth in bits per component (e.g., 8, 10, 12). none Applicable for all 16 Layers
static void XVMix_SetCoeffForRgbToYuv(XV_Mix_l2 *InstancePtr, XVidC_ColorStd ColorStd, XVidC_ColorRange colorRange, u8 colorDepth)
Sets the RGB to YUV color space conversion coefficients for the mixer instance.
This function configures the color space conversion (CSC) matrix coefficients in the hardware registers of the mixer to perform RGB to YUV conversion. The coefficients are selected based on the specified color standard, color range, and color depth. The function writes the scaled coefficients to the appropriate hardware registers. InstancePtr Pointer to the XV_Mix_l2 instance. ColorStd The color standard to use (e.g., BT.601, BT.709). colorRange The color range (e.g., full range, limited range). colorDepth The color depth (bits per component).
u32 XVMix_SetCscCoeffs(XV_Mix_l2 *InstancePtr, XVidC_ColorStd colorStandard, XVidC_ColorRange colorRange, u8 colorDepth)
Sets the Color Space Conversion (CSC) coefficients for the XV_Mix_l2 instance.
This function configures the CSC coefficients based on the specified color standard, color range, and color depth. It first checks if the provided color standard and color range are supported. If the CSC coefficient registers are enabled in the hardware, it sets the coefficients for both YUV-to-RGB and RGB-to-YUV conversions. If the registers are not enabled, it returns an error indicating that the feature is not available. InstancePtr Pointer to the XV_Mix_l2 instance. colorStandard Specifies the color standard (e.g., BT.601, BT.709). colorRange Specifies the color range (e.g., full, limited). colorDepth Specifies the color depth (in bits). XST_SUCCESS if the coefficients are set successfully.XST_FAILURE if an unknown color standard or color range is provided.XST_NO_FEATURE if the CSC coefficient registers are not enabled.
References XVMix_IsCscCoeffsRegsEnabled.
void XV_mix_SetFlushbit(XV_mix *InstancePtr)
Sets the flush bit in the control register of the XV_mix hardware instance.
This function reads the current value of the control register, sets the flush bit, and writes the updated value back to the register. The flush bit is typically used to trigger a hardware flush operation, ensuring that any pending data is processed. InstancePtr Pointer to the XV_mix instance. The function asserts that the InstancePtr is not NULL and that the hardware instance is ready before performing the operation.
References XV_mix_Config::BaseAddress, XV_mix::Config, XV_mix::IsReady, XV_MIX_CTRL_ADDR_AP_CTRL, XV_MIX_CTRL_BITS_FLUSH_BIT.
Referenced by XVMix_Stop.
u32 XV_mix_Get_FlushDone(XV_mix *InstancePtr)
Retrieves the flush done status from the XV_mix hardware instance.
This function reads the FLUSH status bit from the AP_CTRL register of the XV_mix hardware core to determine if the flush operation has completed. InstancePtr is a pointer to the XV_mix instance. The value of the FLUSH status bit (non-zero if flush is done, zero otherwise). The function asserts that InstancePtr is not NULL and that the instance is ready before accessing the hardware register.
References XV_mix_Config::BaseAddress, XV_mix::Config, XV_mix::IsReady, XV_MIX_CTRL_ADDR_AP_CTRL, XV_MIX_CTRL_BITS_FLUSH_STATUSBIT.
Referenced by XVMix_Stop.
void XVMix_InterruptHandler(void *InstancePtr)
This function is the interrupt handler for the mixer core driver.
This handler clears the pending interrupt and determined if the source is frame done signal. If yes, starts the next frame processing and calls the registered callback functionThe application is responsible for connecting this function to the interrupt system. Application beyond this driver is also responsible for providing callbacks to handle interrupts and installing the callbacks using XVMix_SetCallback() during initialization phase. InstancePtr is a pointer to the core instance that just interrupted. None.
References XV_Mix_l2::CallbackRef, XV_Mix_l2::FrameDoneCallback, XV_mix::IsReady, XV_Mix_l2::Mix, XV_mix_InterruptClear, XV_mix_InterruptGetStatus, XV_mix_Start.
int XVMix_SetCallback(XV_Mix_l2 *InstancePtr, void *CallbackFunc, void *CallbackRef)
This function installs an asynchronous callback function for Mixer interrupt.
InstancePtr is a pointer to the mixer core instance. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XV_Mix_l2::CallbackRef, XV_Mix_l2::FrameDoneCallback.
XVMIX_MASK_ENABLE_ALL_LAYERS
XVMIX_MASK_DISABLE_ALL_LAYERS
XVMIX_REG_OFFSET
XVMIX_MIN_STRM_WIDTH
XVMIX_MIN_STRM_HEIGHT
XVMIX_MIN_LOGO_WIDTH
XVMIX_MIN_LOGO_HEIGHT
XV_WAIT_FOR_FLUSH_DONE
XV_WAIT_FOR_FLUSH_DONE_TIMEOUT
XV_MIX_L2_H
XVMIX_MAX_SUPPORTED_LAYERS
XVMIX_ALPHA_MIN
XVMIX_ALPHA_MAX
XVMIX_IRQ_DONE_MASK
XVMIX_IRQ_READY_MASK
XVMIX_CSC_COEFF_FRACTIONAL_BITS
XVMIX_CSC_COEFF_DIVISOR
XVMIX_CSC_MAX_ROWS
XVMIX_CSC_MAX_COLS
XVMIX_CSC_MATRIX_SIZE
XVMIX_CSC_COEFF_SIZE
XVMix_GetNumLayers
This macro returns the available layers in IP.
InstancePtr is a pointer to the core instance. Number of layers enabled in HW None.
Referenced by XVMix_DbgReportStatus, XVMix_GetLayerAlpha, XVMix_GetLayerBufferAddr, XVMix_GetLayerChromaBuffer2Addr, XVMix_GetLayerChromaBufferAddr, XVMix_GetLayerColorFormat, XVMix_GetLayerScaleFactor, XVMix_GetLayerWindow, XVMix_LayerDisable, XVMix_LayerEnable, XVMix_MoveLayerWindow, XVMix_SetLayerAlpha, XVMix_SetLayerBufferAddr, XVMix_SetLayerChromaBuffer2Addr, XVMix_SetLayerChromaBufferAddr, XVMix_SetLayerScaleFactor, XVMix_SetLayerWindow.
XVMix_GetBackgndColor
This macro returns the current set background color id.
InstancePtr is a pointer to the core instance. Background color id None.
XVMix_GetLayerInterfaceType
This macro returns the interface type for the specified layer.
InstancePtr is a pointer to the core instance. LayerId is the layer index for which information is requested Layer Interface Type None.
Referenced by XVMix_DbgLayerInfo.
XVMix_IsLogoEnabled
This macro returns if Logo layer is enabled.
InstancePtr is a pointer to the core instance. Enabled(1)/Disabled(0) None.
Referenced by XVMix_GetLayerAlpha, XVMix_GetLayerScaleFactor, XVMix_GetLayerWindow, XVMix_GetLogoColorKey, XVMix_LayerDisable, XVMix_LayerEnable, XVMix_LoadLogo, XVMix_LoadLogoPixelAlpha, XVMix_MoveLayerWindow, XVMix_SetLayerAlpha, XVMix_SetLayerScaleFactor, XVMix_SetLayerWindow, XVMix_SetLogoColorKey.
XVMix_IsLogoColorKeyEnabled
This macro returns if Logo layer color key feature is enabled.
InstancePtr is a pointer to the core instance. Enabled(1)/Disabled(0) None.
Referenced by XVMix_DbgLayerInfo, XVMix_GetLogoColorKey, XVMix_SetLogoColorKey.
XVMix_IsLogoPixAlphaEnabled
This macro returns if Logo layer alpha feature is enabled.
InstancePtr is a pointer to the core instance. Enabled(1)/Disabled(0) None.
Referenced by XVMix_DbgLayerInfo, XVMix_LoadLogoPixelAlpha.
XVMix_IsCscCoeffsRegsEnabled
This macro returns if CSC Coefficient Registers is enabled.
InstancePtr is a pointer to the core instance. Enabled(1)/Disabled(0) None.
Referenced by XVMix_SetCscCoeffs.
XVMix_IsAlphaEnabled
This macro returns if alpha feature of specified layer is available.
InstancePtr is a pointer to the core instance. LayerId is the layer index for which information is requested Enabled(1)/Disabled(0) None.
Referenced by XVMix_DbgLayerInfo, XVMix_GetLayerAlpha, XVMix_SetLayerAlpha.
XVMix_IsTileFormatEnabled
Checks if the tile format is enabled for the given XVMix instance.
This macro evaluates to the value of the IsTileFormat field in the Mix configuration structure of the specified instance. It is used to determine whether the tile format feature is enabled for the XVMix hardware. InstancePtr A pointer to the XVMix instance to be checked. Non-zero if tile format is enabled, zero otherwise.
Referenced by XVMix_DbgReportStatus.
XVMix_IsScalingEnabled
This macro returns if scaling feature of specified layer is available.
InstancePtr is a pointer to the core instance. LayerId is the layer index for which information is requested Enabled(1)/Disabled(0) None.
Referenced by XVMix_DbgLayerInfo, XVMix_GetLayerScaleFactor, XVMix_SetLayerScaleFactor.
XVMix_IsLayerInterfaceStream
This macro check if specified layer interface type is STREAM.
InstancePtr is a pointer to the core instance. LayerId is the layer index for which information is requested TRUE(1)/FALSE(0)
Referenced by main, XVMix_SetLayerWindow.