v_frmbuf_wr
XVFrmbufWr_ErrorCodes
XVFrmbufWr_HandlerType
Handler for ap_done.
static void SetPowerOnDefaultState(XV_FrmbufWr_l2 *InstancePtr)
Sets the XV_FrmbufWr_l2 instance to its power-on default state.
This function initializes the video stream parameters to default values, including resolution (1920x1080 @ 60Hz, progressive), color format (RGB), frame rate (60Hz), color depth, and pixels per clock based on the instance configuration. It also sets the hardware registers for frame width, height, stride, and memory video format. The function disables DONE and READY interrupts to configure the instance in polling mode. InstancePtr Pointer to the XV_FrmbufWr_l2 instance to initialize. None
XVidC_ColorFormat WrMemory2Live(XVidC_ColorFormat MemFmt)
This function maps the memory video formats to the live/stream video formats.
MemFmt is the video format written to memory Live/Stream Video Format associated with that memory format
Referenced by XVFrmbufWr_SetMemFormat.
int XVFrmbufWr_Initialize(XV_FrmbufWr_l2 *InstancePtr, UINTPTR BaseAddress)
XVFrmbufWr_Initialize - Initializes the frame buffer write instance.
This function initializes an XV_FrmbufWr_l2 instance, setting up its internal state and configuring the underlying hardware or driver instance. It clears the instance memory, initializes the lower-level frame buffer write driver, and sets the power-on default state if initialization is successful. InstancePtr Pointer to the XV_FrmbufWr_l2 instance to be initialized. DeviceId Device ID of the frame buffer write core (used in non-SDT builds). XST_SUCCESS if initialization was successful.Error code otherwise.
References XV_FrmbufWr_l2::FrmbufWr, XV_frmbufwr_Initialize.
void XVFrmbufWr_InterruptEnable(XV_FrmbufWr_l2 *InstancePtr, u32 IrqMask)
Enables specific interrupts for the Frame Buffer Write core and globally enables interrupts.
Also disables the auto-restart feature of the Frame Buffer Write core. InstancePtr Pointer to the XV_FrmbufWr_l2 instance. IrqMask Bitmask specifying which interrupts to enable. This function asserts that the provided instance pointer is not NULL, enables the specified interrupts, globally enables interrupts for the core, and clears the auto-restart bit to prevent automatic restarts.
References XV_FrmbufWr_l2::FrmbufWr, XV_frmbufwr_DisableAutoRestart, XV_frmbufwr_InterruptEnable, XV_frmbufwr_InterruptGlobalEnable.
void XVFrmbufWr_InterruptDisable(XV_FrmbufWr_l2 *InstancePtr, u32 IrqMask)
Disable specific interrupts for the Frame Buffer Write core and enable auto-restart.
This function disables the interrupts specified by the IrqMask for the Frame Buffer Write instance pointed to by InstancePtr. It also globally disables all interrupts for the core, and sets the auto-restart bit to enable automatic restarting of the core after completion. InstancePtr Pointer to the XV_FrmbufWr_l2 instance. IrqMask is the interrupt mask the driver interrupt handler passes to the callback function. The function asserts that InstancePtr is not NULL.
References XV_FrmbufWr_l2::FrmbufWr, XV_frmbufwr_EnableAutoRestart, XV_frmbufwr_InterruptDisable, XV_frmbufwr_InterruptGlobalDisable.
void XVFrmbufWr_Start(XV_FrmbufWr_l2 *InstancePtr)
Starts the Frame Buffer Write core.
This function initiates the operation of the Frame Buffer Write (FrmbufWr) core for the given instance. It asserts that the provided instance pointer is not NULL, and then calls the lower-level start function for the hardware core. InstancePtr Pointer to the XV_FrmbufWr_l2 instance to be started.
References XV_FrmbufWr_l2::FrmbufWr, XV_frmbufwr_Start.
Referenced by XVFrameBufferWrCallback.
int XVFrmbufWr_Stop(XV_FrmbufWr_l2 *InstancePtr)
Stops the Frame Buffer Write core.
This function disables the autostart feature and initiates a flush operation on the Frame Buffer Write core. It waits for the flush operation to complete or until a timeout occurs. If the flush does not complete within the allowed time, the function returns a failure status. InstancePtr Pointer to the XV_FrmbufWr_l2 instance. XST_SUCCESS if the flush operation completes successfully.XST_FAILURE if the flush operation does not complete within the timeout.
References XV_FrmbufWr_l2::FrmbufWr, XV_frmbufwr_DisableAutoRestart, XV_frmbufwr_Get_FlushDone, XV_frmbufwr_SetFlushbit.
Referenced by resetIp.
int XVFrmbufWr_WaitForIdle(XV_FrmbufWr_l2 *InstancePtr)
Waits for the Frame Buffer Write core to become idle.
This function polls the status of the Frame Buffer Write hardware core until it becomes idle or a timeout occurs. It checks the idle status by calling XV_frmbufwr_IsIdle() in a loop, up to a maximum number of iterations defined by XVFRMBUFWR_IDLE_TIMEOUT. InstancePtr Pointer to the XV_FrmbufWr_l2 instance. XST_SUCCESS if the core becomes idle within the timeout period.XST_FAILURE if the core does not become idle before the timeout.
References XV_FrmbufWr_l2::FrmbufWr, XV_frmbufwr_IsIdle.
int XVFrmbufWr_SetMemFormat(XV_FrmbufWr_l2 *InstancePtr, u32 StrideInBytes, XVidC_ColorFormat MemFmt, const XVidC_VideoStream *StrmIn)
Configure the memory format and validate parameters for the frame buffer write instance.
This function sets up the memory format for the frame buffer writer, validates the input parameters, and configures the hardware registers if all checks pass. It ensures that the video stream and memory format are compatible, the stride is properly aligned, and the selected memory format is supported by the hardware instance. InstancePtr Pointer to the XV_FrmbufWr_l2 instance. StrideInBytes Stride (in bytes) for each line in memory. MemFmt Desired memory color format (XVidC_ColorFormat). StrmIn Pointer to the input video stream structure (XVidC_VideoStream). XST_SUCCESS if the configuration is successful.XVFRMBUFWR_ERR_FRAME_SIZE_INVALID if the frame size is invalid for the selected format.XVFRMBUFWR_ERR_STRIDE_MISALIGNED if the stride is not properly aligned.XVFRMBUFWR_ERR_VIDEO_FORMAT_MISMATCH if the stream and memory formats do not match.XVFRMBUFWR_ERR_DISABLED_IN_HW if the selected memory format is not supported in hardware. The function asserts that InstancePtr and StrmIn are not NULL.The function copies the input stream structure to the instance.For 4:2:2 and 4:2:0 formats, width and/or height must be even.The stride must be aligned to 2 * PixPerClk * 4 bytes.The memory format must be enabled in the hardware configuration.
References XV_frmbufwr::Config, XV_FrmbufWr_l2::FrmbufWr, XV_frmbufwr_Config::PixPerClk, XV_FrmbufWr_l2::Stream, WrMemory2Live, XV_frmbufwr_Set_HwReg_height, XV_frmbufwr_Set_HwReg_stride, XV_frmbufwr_Set_HwReg_video_format, XV_frmbufwr_Set_HwReg_width, XVFrmbufWr_IsBGR8Enabled, XVFrmbufWr_IsBGRA8Enabled, XVFrmbufWr_IsBGRX8Enabled, XVFrmbufWr_IsRGB16Enabled, XVFrmbufWr_IsRGB8Enabled, XVFrmbufWr_IsRGBA8Enabled, XVFrmbufWr_IsRGBX10Enabled, XVFrmbufWr_IsRGBX12Enabled, XVFrmbufWr_IsRGBX8Enabled, XVFrmbufWr_IsUYVY8Enabled, XVFrmbufWr_IsY10_L16LEEnabled, XVFrmbufWr_IsY10_M16LEEnabled, XVFrmbufWr_IsY10Enabled, XVFrmbufWr_IsY12_L16LEEnabled, XVFrmbufWr_IsY12_M16LEEnabled, XVFrmbufWr_IsY12Enabled, XVFrmbufWr_IsY16Enabled, XVFrmbufWr_IsY8Enabled, XVFrmbufWr_IsY_U_V10_L16LEEnabled, XVFrmbufWr_IsY_U_V10_M16LEEnabled, XVFrmbufWr_IsY_U_V10Enabled, XVFrmbufWr_IsY_U_V12_L16LEEnabled, XVFrmbufWr_IsY_U_V12_M16LEEnabled, XVFrmbufWr_IsY_U_V12Enabled, XVFrmbufWr_IsY_U_V8_420Enabled, XVFrmbufWr_IsY_U_V8Enabled, XVFrmbufWr_IsY_UV10_420_L16LEEnabled, XVFrmbufWr_IsY_UV10_420_M16LEEnabled, XVFrmbufWr_IsY_UV10_420Enabled, XVFrmbufWr_IsY_UV10_L16LEEnabled, XVFrmbufWr_IsY_UV10_M16LEEnabled, XVFrmbufWr_IsY_UV10Enabled, XVFrmbufWr_IsY_UV12_420_L16LEEnabled, XVFrmbufWr_IsY_UV12_420_M16LEEnabled, XVFrmbufWr_IsY_UV12_420Enabled, XVFrmbufWr_IsY_UV12_L16LEEnabled, XVFrmbufWr_IsY_UV12_M16LEEnabled, XVFrmbufWr_IsY_UV12Enabled, XVFrmbufWr_IsY_UV16_420Enabled, XVFrmbufWr_IsY_UV16Enabled, XVFrmbufWr_IsY_UV8_420Enabled, XVFrmbufWr_IsY_UV8Enabled, XVFrmbufWr_IsYUV16Enabled, XVFrmbufWr_IsYUV8Enabled, XVFrmbufWr_IsYUVA8Enabled, XVFrmbufWr_IsYUVX10Enabled, XVFrmbufWr_IsYUVX12Enabled, XVFrmbufWr_IsYUVX8Enabled, XVFrmbufWr_IsYUYV8Enabled.
XVidC_VideoStream* XVFrmbufWr_GetVideoStream(XV_FrmbufWr_l2 *InstancePtr)
Retrieves a pointer to the video stream associated with the given Frame Buffer Write instance.
InstancePtr Pointer to the XV_FrmbufWr_l2 instance. Pointer to the XVidC_VideoStream structure associated with the instance.
References XV_FrmbufWr_l2::Stream.
int XVFrmbufWr_SetBufferAddr(XV_FrmbufWr_l2 *InstancePtr, UINTPTR Addr)
Sets the frame buffer address for the Frame Buffer Write core.
This function validates and sets the memory address for the frame buffer. The address must be aligned to the AXI-MM width, which is calculated as 2 * PixelsPerClock * 4 bytes. If the address is not properly aligned, the function returns an error code indicating misalignment. InstancePtr Pointer to the XV_FrmbufWr_l2 instance. Addr Physical address to be set as the frame buffer base address. XST_SUCCESS if the address is valid and set successfully.XVFRMBUFWR_ERR_MEM_ADDR_MISALIGNED if the address is not properly aligned.XST_FAILURE for other failures. The function asserts that InstancePtr is not NULL and Addr is not zero.The alignment requirement is based on the AXI-MM interface and the core's PixelsPerClock configuration.
References XV_frmbufwr::Config, XV_FrmbufWr_l2::FrmbufWr, XV_frmbufwr_Config::PixPerClk, XV_frmbufwr_Set_HwReg_frm_buffer_V.
UINTPTR XVFrmbufWr_GetBufferAddr(XV_FrmbufWr_l2 *InstancePtr)
Retrieves the current buffer address used by the frame buffer write instance.
InstancePtr : Pointer to the XV_FrmbufWr_l2 instance. The address (UINTPTR) of the current frame buffer. This function asserts that the provided instance pointer is not NULL, then reads and returns the hardware register value corresponding to the frame buffer address.
References XV_FrmbufWr_l2::FrmbufWr, XV_frmbufwr_Get_HwReg_frm_buffer_V.
int XVFrmbufWr_SetChromaBufferAddr(XV_FrmbufWr_l2 *InstancePtr, UINTPTR Addr)
Sets the chroma buffer address for the frame buffer write instance.
This function sets the address of the chroma buffer for the given frame buffer write instance. It checks if the provided address is aligned to the required AXI memory width (2 * PixelsPerClock * 4 bytes). If the address is not properly aligned, the function returns an error code indicating misalignment. Otherwise, it updates the hardware register with the new chroma buffer address. InstancePtr Pointer to the XV_FrmbufWr_l2 instance. Addr Address to be set for the chroma buffer. XST_SUCCESS if the address is valid and set successfully.XVFRMBUFWR_ERR_MEM_ADDR_MISALIGNED if the address is not properly aligned.XST_FAILURE for other failures. The address must be aligned to (2 * PixelsPerClock * 4) bytes. The function asserts that InstancePtr is not NULL and Addr is not zero.
References XV_frmbufwr::Config, XV_FrmbufWr_l2::FrmbufWr, XV_frmbufwr_Config::PixPerClk, XV_frmbufwr_Set_HwReg_frm_buffer2_V.
UINTPTR XVFrmbufWr_GetChromaBufferAddr(XV_FrmbufWr_l2 *InstancePtr)
Retrieves the address of the chroma buffer for the given Frame Buffer Write instance.
InstancePtr Pointer to the XV_FrmbufWr_l2 instance. The address (UINTPTR) of the chroma buffer. This function asserts that the provided instance pointer is not NULL, then reads and returns the chroma buffer address from the hardware register.
References XV_FrmbufWr_l2::FrmbufWr, XV_frmbufwr_Get_HwReg_frm_buffer2_V.
int XVFrmbufWr_SetVChromaBufferAddr(XV_FrmbufWr_l2 *InstancePtr, UINTPTR Addr)
Sets the vertical chroma buffer address for the frame buffer write instance.
This function sets the address for the vertical chroma buffer in the frame buffer write hardware. The address must be aligned to a specific boundary determined by the number of pixels per clock and the data width. If the address is not properly aligned, the function returns an error code. InstancePtr Pointer to the XV_FrmbufWr_l2 instance. Addr Address to be set for the vertical chroma buffer. XST_SUCCESS if the address is valid and set successfully.XVFRMBUFWR_ERR_MEM_ADDR_MISALIGNED if the address is not properly aligned.XST_FAILURE for other failures. The address alignment is calculated as 2 * PixPerClk * 4 bytes. The function asserts that InstancePtr is not NULL and Addr is not zero.
References XV_frmbufwr::Config, XV_FrmbufWr_l2::FrmbufWr, XV_frmbufwr_Config::PixPerClk, XV_frmbufwr_Set_HwReg_frm_buffer3_V.
UINTPTR XVFrmbufWr_GetVChromaBufferAddr(XV_FrmbufWr_l2 *InstancePtr)
Retrieves the address of the chroma buffer (V component) for the given frame buffer write instance.
InstancePtr Pointer to the XV_FrmbufWr_l2 instance. The address (UINTPTR) of the V chroma buffer. The function asserts that InstancePtr is not NULL.
References XV_FrmbufWr_l2::FrmbufWr, XV_frmbufwr_Get_HwReg_frm_buffer3_V.
u32 XVFrmbufWr_GetFieldID(XV_FrmbufWr_l2 *InstancePtr)
Retrieves the current Field ID from the Frame Buffer Write hardware.
InstancePtr : Pointer to the XV_FrmbufWr_l2 instance. This function asserts that the provided instance pointer is not NULL and that the Frame Buffer Write configuration is set to interlaced mode. It then reads and returns the current Field ID from the hardware register.The current Field ID value read from the hardware.
References XV_frmbufwr::Config, XV_FrmbufWr_l2::FrmbufWr, XV_frmbufwr_Config::Interlaced, XV_frmbufwr_Get_HwReg_field_id.
void XVFrmbufWr_DbgReportStatus(XV_FrmbufWr_l2 *InstancePtr)
XVFrmbufWr_DbgReportStatus - Prints the current status and configuration of the Frame Buffer Write core.
InstancePtr Pointer to the XV_FrmbufWr_l2 instance. This function prints a detailed debug report of the Frame Buffer Write (FrmbufWr) core's configuration and status registers to the standard output using xil_printf. The report includes: Pixels per clockColor depth and AXI-MM data widthEnabled color formats (RGBX8, BGRX8, YUVX8, etc.)Interlaced and tile format enable statusControl register valueCurrent width, height, stride, video formatBuffer addresses (luma, chroma, vchroma) The function asserts that the provided instance pointer is not NULL.This function is intended for debugging and diagnostic purposes.none
References XV_frmbufwr_Config::AXIMMDataWidth, XV_frmbufwr_Config::BaseAddress, XV_frmbufwr_Config::BGR8En, XV_frmbufwr_Config::BGRA8En, XV_frmbufwr_Config::BGRX8En, XV_frmbufwr::Config, XV_frmbufwr_Config::EnPartialFrm, XV_frmbufwr_Config::EnSyncSignals, XV_FrmbufWr_l2::FrmbufWr, XV_frmbufwr_Config::Interlaced, XV_frmbufwr_Config::IsTileFormat, XV_frmbufwr_Config::MaxDataWidth, XV_frmbufwr_Config::PixPerClk, XV_frmbufwr_Config::RGB16En, XV_frmbufwr_Config::RGB8En, XV_frmbufwr_Config::RGBA8En, XV_frmbufwr_Config::RGBX10En, XV_frmbufwr_Config::RGBX12En, XV_frmbufwr_Config::RGBX8En, XV_frmbufwr_Config::UYVY8En, XV_FRMBUFWR_CTRL_ADDR_AP_CTRL, XV_frmbufwr_Get_HwReg_frm_buffer2_V, XV_frmbufwr_Get_HwReg_frm_buffer3_V, XV_frmbufwr_Get_HwReg_frm_buffer_V, XV_frmbufwr_Get_HwReg_height, XV_frmbufwr_Get_HwReg_stride, XV_frmbufwr_Get_HwReg_video_format, XV_frmbufwr_Get_HwReg_width, XV_frmbufwr_Config::Y10_L16LEEn, XV_frmbufwr_Config::Y10_M16LEEn, XV_frmbufwr_Config::Y10En, XV_frmbufwr_Config::Y12_L16LEEn, XV_frmbufwr_Config::Y12_M16LEEn, XV_frmbufwr_Config::Y12En, XV_frmbufwr_Config::Y16En, XV_frmbufwr_Config::Y8En, XV_frmbufwr_Config::Y_U_V10_L16LEEn, XV_frmbufwr_Config::Y_U_V10_M16LEEn, XV_frmbufwr_Config::Y_U_V10En, XV_frmbufwr_Config::Y_U_V12_L16LEEn, XV_frmbufwr_Config::Y_U_V12_M16LEEn, XV_frmbufwr_Config::Y_U_V12En, XV_frmbufwr_Config::Y_U_V8_420En, XV_frmbufwr_Config::Y_U_V8En, XV_frmbufwr_Config::Y_UV10_420_L16LEEn, XV_frmbufwr_Config::Y_UV10_420_M16LEEn, XV_frmbufwr_Config::Y_UV10_420En, XV_frmbufwr_Config::Y_UV10_L16LEEn, XV_frmbufwr_Config::Y_UV10_M16LEEn, XV_frmbufwr_Config::Y_UV10En, XV_frmbufwr_Config::Y_UV12_420_L16LEEn, XV_frmbufwr_Config::Y_UV12_420_M16LEEn, XV_frmbufwr_Config::Y_UV12_420En, XV_frmbufwr_Config::Y_UV12_L16LEEn, XV_frmbufwr_Config::Y_UV12_M16LEEn, XV_frmbufwr_Config::Y_UV12En, XV_frmbufwr_Config::Y_UV16_420En, XV_frmbufwr_Config::Y_UV16En, XV_frmbufwr_Config::Y_UV8_420En, XV_frmbufwr_Config::Y_UV8En, XV_frmbufwr_Config::YUV16En, XV_frmbufwr_Config::YUV8En, XV_frmbufwr_Config::YUVA8En, XV_frmbufwr_Config::YUVX10En, XV_frmbufwr_Config::YUVX12En, XV_frmbufwr_Config::YUVX8En, XV_frmbufwr_Config::YUYV8En.
int XVFrmbufWr_SetCallback(XV_FrmbufWr_l2 *InstancePtr, u32 HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function Type ----------------------- -------------------------------------------------- (XVFRMBUFWR_HANDLER_DONE) DoneCallback (XVFRMBUFWR_HANDLER_READY) ReadyCallback InstancePtr is a pointer to the Frame Buffer Write core instance. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. HandlerType specifies the type of handler. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XV_FrmbufWr_l2::CallbackDoneRef, XV_FrmbufWr_l2::CallbackReadyRef, XV_FrmbufWr_l2::FrameDoneCallback, XV_FrmbufWr_l2::FrameReadyCallback, XVFRMBUFWR_HANDLER_DONE, XVFRMBUFWR_HANDLER_READY.
Referenced by main.
void XVFrmbufWr_InterruptHandler(void *InstancePtr)
This function is the interrupt handler for the frame buffer write core driver.
This handler clears the pending interrupt and determined if the source is frame done signal. If yes, starts the next frame processing and calls the registered callback functionThe application is responsible for connecting this function to the interrupt system. Application beyond this driver is also responsible for providing callbacks to handle interrupts and installing the callbacks using XVFrmbufWr_SetCallback() during initialization phase. InstancePtr is a pointer to the core instance that just interrupted. None.
References XV_FrmbufWr_l2::CallbackDoneRef, XV_FrmbufWr_l2::CallbackReadyRef, XV_FrmbufWr_l2::FrameDoneCallback, XV_FrmbufWr_l2::FrameReadyCallback, XV_FrmbufWr_l2::FrmbufWr, XV_frmbufwr::IsReady, XV_frmbufwr_InterruptClear, XV_frmbufwr_InterruptGetStatus.
XVFRMBUFWR_MIN_STRM_WIDTH
XVFRMBUFWR_MIN_STRM_HEIGHT
XVFRMBUFWR_IDLE_TIMEOUT
XV_WAIT_FOR_FLUSH_DONE
XV_WAIT_FOR_FLUSH_DONE_TIMEOUT
XV_FRMBUFWR_L2_H
XVFRMBUFWR_IRQ_DONE_MASK
XVFRMBUFWR_IRQ_READY_MASK