xv_frmbufwr_example.c
DDR_BASEADDR
XVFRMBUFRD_BUFFER_BASEADDR
XVFRMBUFWR_BUFFER_BASEADDR
VIDEO_MONITOR_LOCK_TIMEOUT
FRMBUF_IDLE_TIMEOUT
NUM_TEST_MODES
NUM_TEST_FORMATS
CHROMA_ADDR_OFFSET
V_CHROMA_ADDR_OFFSET
XVMonitor_IsVideoLocked
These macros read GPIO to check video lock and overflow status.
GpioPtr is pointer to the gpio Instance T/F
Referenced by main.
XVMonitor_DidVideoOverflow
VideoFormats ColorFormats[NUM_TEST_FORMATS][NUM_TEST_FORMATS]
XV_FrmbufRd_l2 frmbufrd
XV_frmbufrd_Config frmbufrd_cfg
XV_FrmbufWr_l2 frmbufwr
XV_frmbufwr_Config frmbufwr_cfg
XVtc vtc
XScuGic intc
XGpio vmon
XVidC_VideoStream VidStream
u32 volatile* gpio_hlsIpReset
void resetIp(void)
Resets the HLS (High-Level Synthesis) IP core and stops the frame buffer write operation.
This function performs the following steps: Stops the frame buffer write core and waits for it to become idle.Prints a message indicating that the HLS IP is being reset.Asserts the reset line for the HLS IP by writing 0 to the reset GPIO.Waits for 1 millisecond to ensure the reset is asserted.Deasserts the reset line by writing 1 to the reset GPIO.Waits for another millisecond to allow the IP to come out of reset. This ensures a proper reset sequence for the HLS IP and the frame buffer write core.
References XVFrmbufWr_Stop.
Referenced by main.
static int DriverInit(void)
Initializes the video processing hardware drivers.
This function performs the initialization of the following hardware components: Video Timing Controller (VTC)Frame Buffer Read (frmbufrd)Frame Buffer Write (frmbufwr)Video Lock Monitor GPIO (vmon) The function uses conditional compilation to select between device ID and base address depending on whether SDT is defined. It checks for configuration lookup failures and initialization errors for each component, printing error messages via xil_printf and returning XST_FAILURE on failure. XST_SUCCESS if all components are initialized successfully.XST_FAILURE if any component fails to initialize.
static int SetupInterrupts(void)
static u32 CalcStride(XVidC_ColorFormat Cfmt, u16 AXIMMDataWidth, XVidC_VideoStream *StreamPtr)
CalcStride - Calculate the stride (number of bytes per video line) for a given color format.
This function computes the stride required for a video frame buffer line based on the color format, AXI memory-mapped data width, and the video stream's active width. The stride is aligned to the AXI memory-mapped data width in bytes. Cfmt The color format of the video stream (XVidC_ColorFormat). AXIMMDataWidth The AXI memory-mapped data width in bits. StreamPtr Pointer to the XVidC_VideoStream structure containing video timing information. The stride in bytes, aligned to the AXI memory-mapped data width. Color format to bytes-per-pixel mapping: Y_UV10, Y_UV10_420, Y10: 4 bytes per 3 pixelsY_UV8, Y_UV8_420, Y8, Y_U_V8, Y_U_V10: 1 byte per pixelRGB8, YUV8, BGR8: 3 bytes per pixelRGBX12, YUVX12: 5 bytes per pixelY_UV12, Y_UV12_420, Y12: 3 bytes per 2 pixelsRGB16, YUV16: 6 bytes per pixelYUYV8, UYVY8, Y_UV16, Y_UV16_420, Y16: 2 bytes per pixelDefault: 4 bytes per pixel The stride is calculated as: stride = ceil((width * bytes_per_pixel) / MMWidthBytes) * MMWidthBytes where MMWidthBytes = AXIMMDataWidth / 8.
static int ConfigFrmbuf(u32 StrideInBytes, XVidC_ColorFormat Cfmt, XVidC_VideoStream *StreamPtr)
Configures the Frame Buffer Read and Write IP cores with the specified parameters.
This function stops the frame buffer IPs, resets them, waits for them to become idle, and then configures their memory formats and buffer addresses according to the provided stride, color format, and video stream. It also handles chroma and V buffer addresses for semi-planar and 3-planar color formats, respectively. Interrupts are enabled and the frame buffers are started after configuration. StrideInBytes The stride (in bytes) for the frame buffer memory. Cfmt The color format (XVidC_ColorFormat) to be used for the frame buffer. StreamPtr Pointer to the video stream configuration (XVidC_VideoStream). XST_SUCCESS if configuration is successful.XST_FAILURE if any configuration step fails. This function assumes that the global variables 'frmbufrd' and 'frmbufwr' are properly initialized.The function also assumes that the macros XVFRMBUFRD_BUFFER_BASEADDR, XVFRMBUFWR_BUFFER_BASEADDR, CHROMA_ADDR_OFFSET, and V_CHROMA_ADDR_OFFSET are defined.The function prints error messages via xil_printf if any step fails.
static void ConfigVtc(XVidC_VideoStream *StreamPtr)
Configures the Video Timing Controller (VTC) based on the provided video stream parameters.
This function initializes and sets up the VTC timing structure using the timing information from the given XVidC_VideoStream pointer. It divides the horizontal timing parameters by the number of pixels per clock to match the VTC's requirements, copies the vertical timing parameters, and applies the configuration to the VTC hardware. After configuration, it enables the VTC, its generator, and register updates. StreamPtr Pointer to an XVidC_VideoStream structure containing the video timing parameters. None.
static int ValidateTestCase(u16 PixPerClk, XVidC_VideoMode Mode, u16 DataWidth, VideoFormats Format)
ValidateTestCase - Validates the combination of pixel-per-clock, video mode, data width, and video format for hardware support.
PixPerClk : Number of pixels processed per clock cycle. Mode : Video mode (resolution, refresh rate, etc.) as defined by XVidC_VideoMode. DataWidth : Data width in bits (e.g., 8, 10, 12, 16). Format : Video format structure containing format information, including bit depth. TRUE - If the specified combination of parameters is supported by the hardware. FALSE - If the combination is not supported (with diagnostic messages printed). The function checks: If the selected video mode is supported for the given pixel-per-clock value.If the data width is compatible with the memory video format's bit depth.Prints diagnostic messages if an unsupported combination is detected.
static int CheckVidoutLock(void)
Checks if the video output is locked within a specified timeout period.
This function waits for a short period, then repeatedly checks if the video output is locked by calling XVMonitor_IsVideoLocked(). If the lock is detected within the timeout period, it prints "Locked" and returns TRUE. If the timeout expires without detecting a lock, it prints an error message and returns FALSE.TRUE if the video output is locked within the timeout period, FALSE otherwise.
static int CheckVidinOverflow(void)
Checks for video input overflow condition.
This function monitors the video input for an overflow condition by polling the video monitor for a specified timeout period. If an overflow is detected within the timeout, an error message is printed; otherwise, a message indicating no overflow is printed. TRUE if a video overflow was detected.FALSE if no overflow was detected within the timeout period.
void* XVFrameBufferRdCallback(void *data)
Callback function for Frame Buffer Read interrupt.
This function is called when a Frame Buffer Read interrupt is received. It starts the frame buffer read operation by calling XVFrmbufRd_Start(). data Pointer to user data (unused). Always returns NULL.
Referenced by main.
void* XVFrameBufferWrCallback(void *data)
Callback function for Frame Buffer Write interrupt.
This function is called when a Frame Buffer Write interrupt is received. It starts the frame buffer write operation by invoking XVFrmbufWr_Start(). data Pointer to user data (unused in this implementation). Always returns NULL.
References XVFrmbufWr_Start.
Referenced by main.
int main(void)
Main application entry point for the Frame Buffer Example Design Test.
This function initializes the platform, configures hardware drivers (VTC, frame buffers, GPIO), sets up interrupts, and iterates through all supported video formats and test video modes. For each valid combination, it configures the VTC and frame buffer, checks for video lock and overflow, and tracks pass/fail results. At the end, it prints a summary of the test results.0 on success, 1 on failure.
References XV_frmbufwr_Config::AXIMMDataWidth, XV_frmbufwr::Config, XV_FrmbufWr_l2::FrmbufWr, init_platform, XV_frmbufwr_Config::IntrId, XV_frmbufwr_Config::IntrParent, XV_frmbufwr_Config::MaxDataWidth, XV_frmbufwr_Config::PixPerClk, resetIp, XVFrameBufferRdCallback, XVFrameBufferWrCallback, XVFRMBUFWR_HANDLER_DONE, XVFrmbufWr_SetCallback, XVMonitor_IsVideoLocked.