xv_frmbufwr.h
XV_frmbufwr_WriteReg
XV_frmbufwr_ReadReg
int XV_frmbufwr_Initialize(XV_frmbufwr *InstancePtr, UINTPTR BaseAddress)
Initialize the frame buffer write core instance.
This function initializes an XV_frmbufwr instance using the configuration found for the specified base address. It performs a lookup for the hardware configuration, and if found, initializes the instance with the configuration data. If the configuration is not found, the function marks the instance as not ready and returns an error code. InstancePtr Pointer to the XV_frmbufwr instance to be initialized. BaseAddress Base address of the device to look up the configuration. XST_SUCCESS if initialization is successful.XST_DEVICE_NOT_FOUND if the configuration for the given base address is not found.
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::IsReady, XV_frmbufwr_CfgInitialize, XV_frmbufwr_LookupConfig.
Referenced by XVFrmbufWr_Initialize.
XV_frmbufwr_Config* XV_frmbufwr_LookupConfig(UINTPTR BaseAddress)
XV_frmbufwr_LookupConfig - Looks up the configuration for a frame buffer write instance.
This function searches the XV_frmbufwr_ConfigTable for a configuration entry that matches the specified BaseAddress. If a matching BaseAddress is found, a pointer to the corresponding configuration structure is returned. If the BaseAddress is zero (0), the function returns the first entry in the table. BaseAddress The base address of the device to look up. A pointer to the configuration structure if found, or NULL if no matching entry exists.
References XV_frmbufwr_Config::Name.
Referenced by XV_frmbufwr_Initialize.
int XV_frmbufwr_CfgInitialize(XV_frmbufwr *InstancePtr, XV_frmbufwr_Config *ConfigPtr, UINTPTR EffectiveAddr)
Initialize the XV_frmbufwr instance.
InstancePtr Pointer to the XV_frmbufwr instance to be initialized. ConfigPtr Pointer to the configuration structure. EffectiveAddr Physical base address of the device. This function initializes an XV_frmbufwr instance using the provided configuration structure and base address. It sets up the instance configuration, updates the base address, and marks the instance as ready.: XST_SUCCESS on successful initialization.
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr_Config::IntrId, XV_frmbufwr_Config::IntrParent, XV_frmbufwr::IsReady.
Referenced by XV_frmbufwr_Initialize.
void XV_frmbufwr_Start(XV_frmbufwr *InstancePtr)
Starts the Frame Buffer Write (frmbufwr) hardware core.
This function asserts the start signal of the frmbufwr core by writing to the control register. It preserves the auto-restart bit if it is set. InstancePtr is a pointer to the XV_frmbufwr instance. The hardware core must be properly initialized and ready before calling this function.
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr::IsReady, XV_FRMBUFWR_CTRL_ADDR_AP_CTRL.
Referenced by XVFrmbufWr_Start.
u32 XV_frmbufwr_IsDone(XV_frmbufwr *InstancePtr)
Checks if the Frame Buffer Write (frmbufwr) hardware core has completed its current operation.
This function reads the status register of the frmbufwr core and returns the "done" status bit. InstancePtr is a pointer to the XV_frmbufwr instance. 1 if the operation is done, 0 otherwise. The function asserts that the InstancePtr is not NULL and that the core is ready.
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr::IsReady, XV_FRMBUFWR_CTRL_ADDR_AP_CTRL.
u32 XV_frmbufwr_IsIdle(XV_frmbufwr *InstancePtr)
Checks if the Frame Buffer Write (frmbufwr) core is idle.
This function reads the control register of the Frame Buffer Write core and returns the status of the idle bit. The core is considered idle if the bit is set. InstancePtr is a pointer to the XV_frmbufwr instance. 1 if the core is idle, 0 otherwise. None.
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr::IsReady, XV_FRMBUFWR_CTRL_ADDR_AP_CTRL.
Referenced by XVFrmbufWr_WaitForIdle.
u32 XV_frmbufwr_IsReady(XV_frmbufwr *InstancePtr)
Checks if the XV_frmbufwr instance is ready to accept new input.
This function reads the control register of the frame buffer write core to determine if it is ready for the next operation. It asserts that the provided instance pointer is not NULL and that the instance is marked as ready. The function returns a non-zero value if the core is ready for the next input, and zero otherwise. InstancePtr is a pointer to the XV_frmbufwr instance. 1 if the core is ready for the next input, 0 otherwise.
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr::IsReady, XV_FRMBUFWR_CTRL_ADDR_AP_CTRL.
void XV_frmbufwr_EnableAutoRestart(XV_frmbufwr *InstancePtr)
Enables auto-restart mode for the Frame Buffer Write (frmbufwr) hardware core.
This function sets the auto-restart bit in the control register, allowing the core to automatically restart its operation after completion without requiring software intervention. InstancePtr is a pointer to the XV_frmbufwr instance. The hardware core must be properly initialized and ready before calling this function.
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr::IsReady, XV_FRMBUFWR_CTRL_ADDR_AP_CTRL.
Referenced by XVFrmbufWr_InterruptDisable.
void XV_frmbufwr_DisableAutoRestart(XV_frmbufwr *InstancePtr)
Disables the auto-restart feature of the frame buffer write core.
InstancePtr : Pointer to the XV_frmbufwr instance. This function disables the auto-restart functionality by writing 0 to the AP_CTRL register of the frame buffer write hardware. It asserts that the instance pointer is not NULL and that the core is ready before performing the operation.
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr::IsReady, XV_FRMBUFWR_CTRL_ADDR_AP_CTRL.
Referenced by XVFrmbufWr_InterruptEnable, XVFrmbufWr_Stop.
void XV_frmbufwr_SetFlushbit(XV_frmbufwr *InstancePtr)
Sets the flush bit in the Frame Buffer Write (frmbufwr) control register.
This function sets the flush bit in the AP_CTRL register to trigger a flush operation in the hardware. It reads the current value of the control register, sets the flush bit, and writes the updated value back. InstancePtr is a pointer to the XV_frmbufwr instance. The hardware core must be properly initialized and ready before calling this function.
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr::IsReady, XV_FRMBUFWR_CTRL_ADDR_AP_CTRL, XV_FRMBUFWR_CTRL_BITS_FLUSH_BIT.
Referenced by XVFrmbufWr_Stop.
u32 XV_frmbufwr_Get_FlushDone(XV_frmbufwr *InstancePtr)
Retrieves the flush done status from the Frame Buffer Write core.
This function reads the status register of the Frame Buffer Write hardware instance to determine if the flush operation has completed. It asserts that the provided instance pointer is not NULL and that the instance is ready. InstancePtr is a pointer to the XV_frmbufwr instance. The value of the flush done status bit (non-zero if flush is done, zero otherwise).
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr::IsReady, XV_FRMBUFWR_CTRL_ADDR_AP_CTRL, XV_FRMBUFWR_CTRL_BITS_FLUSH_STATUSBIT.
Referenced by XVFrmbufWr_Stop.
void XV_frmbufwr_Set_HwReg_width(XV_frmbufwr *InstancePtr, u32 Data)
Sets the hardware register value for the frame buffer writer's width parameter.
This function writes the specified width value to the hardware register associated with the frame buffer writer instance. It first asserts that the provided instance pointer is not NULL and that the instance is ready. InstancePtr Pointer to the XV_frmbufwr instance. Data The width value to be written to the hardware register.
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr::IsReady, XV_FRMBUFWR_CTRL_ADDR_HWREG_WIDTH_DATA.
Referenced by XVFrmbufWr_SetMemFormat.
u32 XV_frmbufwr_Get_HwReg_width(XV_frmbufwr *InstancePtr)
Retrieves the value of the hardware register that specifies the width configuration for the frame buffer write instance.
InstancePtr is a pointer to the XV_frmbufwr instance. The width value read from the hardware register. The function asserts that the instance pointer is not NULL and that the instance is ready before accessing the hardware register.
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr::IsReady, XV_FRMBUFWR_CTRL_ADDR_HWREG_WIDTH_DATA.
Referenced by XVFrmbufWr_DbgReportStatus.
void XV_frmbufwr_Set_HwReg_height(XV_frmbufwr *InstancePtr, u32 Data)
Sets the height hardware register for the frame buffer write instance.
This function writes the specified height value to the hardware register responsible for configuring the frame buffer's height. It first asserts that the provided instance pointer is not NULL and that the instance is ready for operation. InstancePtr Pointer to the XV_frmbufwr instance. Data The height value to be written to the hardware register.
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr::IsReady, XV_FRMBUFWR_CTRL_ADDR_HWREG_HEIGHT_DATA.
Referenced by XVFrmbufWr_SetMemFormat.
u32 XV_frmbufwr_Get_HwReg_height(XV_frmbufwr *InstancePtr)
Retrieves the value of the HWREG_HEIGHT hardware register for the specified Frame Buffer Write (frmbufwr) instance.
InstancePtr Pointer to the XV_frmbufwr instance. The current value of the HWREG_HEIGHT register. The InstancePtr must be initialized and ready before calling this function.
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr::IsReady, XV_FRMBUFWR_CTRL_ADDR_HWREG_HEIGHT_DATA.
Referenced by XVFrmbufWr_DbgReportStatus.
void XV_frmbufwr_Set_HwReg_stride(XV_frmbufwr *InstancePtr, u32 Data)
Sets the hardware register stride value for the frame buffer write instance.
This function writes the specified stride value to the hardware register associated with the frame buffer writer. The stride typically represents the number of bytes between the start of one line of pixels and the next in memory. InstancePtr Pointer to the XV_frmbufwr instance. Data The stride value to be written to the hardware register. The InstancePtr must be initialized and ready before calling this function.
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr::IsReady, XV_FRMBUFWR_CTRL_ADDR_HWREG_STRIDE_DATA.
Referenced by XVFrmbufWr_SetMemFormat.
u32 XV_frmbufwr_Get_HwReg_stride(XV_frmbufwr *InstancePtr)
Retrieves the value of the HWREG_STRIDE register from the frame buffer write hardware.
This function reads the stride value (in bytes) from the hardware register, which typically represents the number of bytes between the start of one line of pixels and the start of the next line in memory. InstancePtr is a pointer to the XV_frmbufwr instance. It must be a valid pointer to an initialized XV_frmbufwr structure. The current value of the HWREG_STRIDE register. The function asserts that InstancePtr is not NULL and that the instance is ready before accessing the hardware register.
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr::IsReady, XV_FRMBUFWR_CTRL_ADDR_HWREG_STRIDE_DATA.
Referenced by XVFrmbufWr_DbgReportStatus.
void XV_frmbufwr_Set_HwReg_video_format(XV_frmbufwr *InstancePtr, u32 Data)
Sets the hardware register for the video format in the frame buffer write instance.
This function writes the specified video format data to the hardware register associated with the frame buffer writer. It first asserts that the instance pointer is not NULL and that the instance is ready before performing the register write. InstancePtr Pointer to the XV_frmbufwr instance. Data The video format data to be written to the hardware register.
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr::IsReady, XV_FRMBUFWR_CTRL_ADDR_HWREG_VIDEO_FORMAT_DATA.
Referenced by XVFrmbufWr_SetMemFormat.
u32 XV_frmbufwr_Get_HwReg_video_format(XV_frmbufwr *InstancePtr)
Retrieves the current hardware register value for the video format.
This function reads the value of the HWREG_VIDEO_FORMAT register from the frame buffer write hardware instance specified by InstancePtr. InstancePtr is a pointer to the XV_frmbufwr instance. The value of the HWREG_VIDEO_FORMAT register. The function asserts that InstancePtr is not NULL and that the instance is ready before accessing the hardware register.
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr::IsReady, XV_FRMBUFWR_CTRL_ADDR_HWREG_VIDEO_FORMAT_DATA.
Referenced by XVFrmbufWr_DbgReportStatus.
void XV_frmbufwr_Set_HwReg_frm_buffer_V(XV_frmbufwr *InstancePtr, u64 Data)
Sets the hardware register for the frame buffer virtual address.
This function writes a 64-bit address (Data) to the hardware register associated with the frame buffer. The address is split into two 32-bit values and written to consecutive register addresses. InstancePtr Pointer to the XV_frmbufwr instance. Data 64-bit virtual address to be written to the hardware register. Preconditions: InstancePtr must not be NULL.InstancePtr->IsReady must be set to XIL_COMPONENT_IS_READY.
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr::IsReady, XV_FRMBUFWR_CTRL_ADDR_HWREG_FRM_BUFFER_V_DATA.
Referenced by XVFrmbufWr_SetBufferAddr.
u64 XV_frmbufwr_Get_HwReg_frm_buffer_V(XV_frmbufwr *InstancePtr)
Retrieves the value of the HWREG_FRM_BUFFER_V hardware register.
This function reads a 64-bit value from the hardware register associated with frame buffer V. It reads two 32-bit values from consecutive register addresses, combines them into a single 64-bit value, and returns the result. InstancePtr Pointer to the XV_frmbufwr instance. Must not be NULL and must be initialized. The 64-bit value read from the HWREG_FRM_BUFFER_V register.
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr::IsReady, XV_FRMBUFWR_CTRL_ADDR_HWREG_FRM_BUFFER_V_DATA.
Referenced by XVFrmbufWr_DbgReportStatus, XVFrmbufWr_GetBufferAddr.
void XV_frmbufwr_Set_HwReg_frm_buffer2_V(XV_frmbufwr *InstancePtr, u64 Data)
Sets the value of the HWREG_FRM_BUFFER2_V hardware register for the frame buffer writer.
This function writes a 64-bit value to the hardware register associated with frame buffer 2. The value is split into two 32-bit parts and written to consecutive register addresses. InstancePtr Pointer to the XV_frmbufwr instance. Data 64-bit value to be written to the hardware register. Preconditions: InstancePtr must not be NULL.InstancePtr->IsReady must be set to XIL_COMPONENT_IS_READY.
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr::IsReady, XV_FRMBUFWR_CTRL_ADDR_HWREG_FRM_BUFFER2_V_DATA.
Referenced by XVFrmbufWr_SetChromaBufferAddr.
u64 XV_frmbufwr_Get_HwReg_frm_buffer2_V(XV_frmbufwr *InstancePtr)
Retrieves the 64-bit value of the HWREG_FRM_BUFFER2_V hardware register.
This function reads two 32-bit registers from the hardware, combines them into a 64-bit value, and returns the result. It asserts that the provided instance pointer is not NULL and that the instance is ready before performing the read operations. InstancePtr Pointer to the XV_frmbufwr instance. The 64-bit value read from the HWREG_FRM_BUFFER2_V register.
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr::IsReady, XV_FRMBUFWR_CTRL_ADDR_HWREG_FRM_BUFFER2_V_DATA.
Referenced by XVFrmbufWr_DbgReportStatus, XVFrmbufWr_GetChromaBufferAddr.
void XV_frmbufwr_Set_HwReg_frm_buffer3_V(XV_frmbufwr *InstancePtr, u64 Data)
Sets the hardware register for frame buffer 3 (vertical) in the XV_frmbufwr instance.
This function writes a 64-bit value to the hardware register associated with frame buffer 3's vertical parameter. The value is split into two 32-bit parts and written to consecutive register addresses. InstancePtr Pointer to the XV_frmbufwr instance. Data 64-bit value to be written to the hardware register. Preconditions: InstancePtr must not be NULL.InstancePtr->IsReady must be set to XIL_COMPONENT_IS_READY.
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr::IsReady, XV_FRMBUFWR_CTRL_ADDR_HWREG_FRM_BUFFER3_V_DATA.
Referenced by XVFrmbufWr_SetVChromaBufferAddr.
u64 XV_frmbufwr_Get_HwReg_frm_buffer3_V(XV_frmbufwr *InstancePtr)
Retrieves the 64-bit value of the HWREG_FRM_BUFFER3_V hardware register.
This function reads two 32-bit registers from the hardware to construct a 64-bit value representing the contents of the HWREG_FRM_BUFFER3_V register. It asserts that the provided instance pointer is not NULL and that the instance is ready before performing the read operations. InstancePtr Pointer to the XV_frmbufwr instance. 64-bit value read from the HWREG_FRM_BUFFER3_V register.
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr::IsReady, XV_FRMBUFWR_CTRL_ADDR_HWREG_FRM_BUFFER3_V_DATA.
Referenced by XVFrmbufWr_DbgReportStatus, XVFrmbufWr_GetVChromaBufferAddr.
u32 XV_frmbufwr_Get_HwReg_field_id(XV_frmbufwr *InstancePtr)
Retrieves the value of the HWREG_FIELD_ID register from the frame buffer write hardware.
This function reads the HWREG_FIELD_ID register from the hardware instance specified by InstancePtr. It asserts that the instance pointer is valid, the instance is ready, and the configuration is set to interlaced mode before performing the register read. InstancePtr is a pointer to the XV_frmbufwr instance. The value read from the HWREG_FIELD_ID register. The function asserts that the instance is configured for interlaced mode.
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr_Config::Interlaced, XV_frmbufwr::IsReady, XV_FRMBUFWR_CTRL_ADDR_HWREG_FIELD_ID_DATA.
Referenced by XVFrmbufWr_GetFieldID.
void XV_frmbufwr_Set_HwReg_force_eof(XV_frmbufwr *InstancePtr, u32 Data)
Sets the hardware register to Force EOF value in the frame buffer write instance.
This function writes the Force EOF data to the hardware register associated with the frame buffer writer. It first asserts that the instance pointer is not NULL and that the instance is ready before performing the register write. InstancePtr Pointer to the XV_frmbufwr instance. Data The Force EOF data to be written to the hardware register.
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr::IsReady, XV_FRMBUFWR_CTRL_ADDR_FORCE_EOF_DATA.
u32 XV_frmbufwr_Get_HwReg_force_eof(XV_frmbufwr *InstancePtr)
Retrieves the current hardware register value for the force EOF.
This function reads the value of the HWREG_FORCE_EOF register from the frame buffer write hardware instance specified by InstancePtr. InstancePtr is a pointer to the XV_frmbufwr instance. The value of the HWREG_FORCE_EOF register. The function asserts that InstancePtr is not NULL and that the instance is ready before accessing the hardware register.
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr::IsReady, XV_FRMBUFWR_CTRL_ADDR_FORCE_EOF_DATA.
void XV_frmbufwr_Set_HwReg_partial_frm_cnt(XV_frmbufwr *InstancePtr, u32 Data)
Sets the hardware register for the partial frame count in the frame buffer write instance.
This function writes the specified partial frame count data to the hardware register associated with the frame buffer writer. It first asserts that the instance pointer is not NULL and that the instance is ready before performing the register write. InstancePtr Pointer to the XV_frmbufwr instance. Data The partial frame count data to be written to the hardware register.
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr::IsReady, XV_FRMBUFWR_CTRL_ADDR_PARTIAL_FRM_CNT_DATA.
u32 XV_frmbufwr_Get_HwReg_partial_frm_cnt(XV_frmbufwr *InstancePtr)
Retrieves the current hardware register value for the partial frame count.
This function reads the value of the HWREG_PARTIAL_FRM_CNT register from the frame buffer write hardware instance specified by InstancePtr. InstancePtr is a pointer to the XV_frmbufwr instance. The value of the PARTIAL_FRM_CNT register. The function asserts that InstancePtr is not NULL and that the instance is ready before accessing the hardware register.
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr::IsReady, XV_FRMBUFWR_CTRL_ADDR_PARTIAL_FRM_CNT_DATA.
void XV_frmbufwr_InterruptGlobalEnable(XV_frmbufwr *InstancePtr)
Enables the global interrupt for the Frame Buffer Write (frmbufwr) core.
This function sets the Global Interrupt Enable (GIE) bit in the control register, allowing the core to generate interrupts. It asserts that the provided instance pointer is not NULL and that the core is ready before enabling the interrupt. InstancePtr Pointer to the XV_frmbufwr instance.
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr::IsReady, XV_FRMBUFWR_CTRL_ADDR_GIE.
Referenced by XVFrmbufWr_InterruptEnable.
void XV_frmbufwr_InterruptGlobalDisable(XV_frmbufwr *InstancePtr)
XV_frmbufwr_InterruptGlobalDisable - Disables the global interrupt for the frame buffer write core.
InstancePtr Pointer to the XV_frmbufwr instance. This function disables the global interrupt enable (GIE) bit in the control register of the frame buffer write hardware. It asserts that the provided instance pointer is not NULL and that the instance is ready before performing the operation.
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr::IsReady, XV_FRMBUFWR_CTRL_ADDR_GIE.
Referenced by XVFrmbufWr_InterruptDisable.
void XV_frmbufwr_InterruptEnable(XV_frmbufwr *InstancePtr, u32 Mask)
Enables specific interrupts for the Frame Buffer Write core.
This function sets the bits specified by the Mask parameter in the Interrupt Enable Register (IER) of the Frame Buffer Write hardware instance. Only the interrupts corresponding to the set bits in the Mask will be enabled. InstancePtr Pointer to the XV_frmbufwr instance. Mask Bitmask of interrupts to enable. Each bit corresponds to a specific interrupt. The InstancePtr must be initialized and ready before calling this function.
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr::IsReady, XV_FRMBUFWR_CTRL_ADDR_IER.
Referenced by XVFrmbufWr_InterruptEnable.
void XV_frmbufwr_InterruptDisable(XV_frmbufwr *InstancePtr, u32 Mask)
Disable specific interrupts for the Frame Buffer Write core.
This function disables the interrupts specified by the Mask parameter in the Interrupt Enable Register (IER) of the Frame Buffer Write core. InstancePtr Pointer to the XV_frmbufwr instance. Mask Bitmask of interrupts to disable. Each bit corresponds to a specific interrupt source. The function asserts that the InstancePtr is not NULL and that the core is ready before proceeding.
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr::IsReady, XV_FRMBUFWR_CTRL_ADDR_IER.
Referenced by XVFrmbufWr_InterruptDisable.
void XV_frmbufwr_InterruptClear(XV_frmbufwr *InstancePtr, u32 Mask)
Clears specific interrupt(s) for the Frame Buffer Write (frmbufwr) instance.
This function writes the specified interrupt mask to the Interrupt Status Register (ISR) to clear the corresponding interrupt(s). InstancePtr Pointer to the XV_frmbufwr instance. Mask Bitmask indicating which interrupt(s) to clear. The InstancePtr must be initialized and ready before calling this function.
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr::IsReady, XV_FRMBUFWR_CTRL_ADDR_ISR.
Referenced by XVFrmbufWr_InterruptHandler.
u32 XV_frmbufwr_InterruptGetEnabled(XV_frmbufwr *InstancePtr)
Retrieves the interrupt enable register value for the XV_frmbufwr instance.
This function checks that the provided instance pointer is valid and that the instance is ready. It then reads and returns the value of the Interrupt Enable Register (IER) for the frame buffer write hardware. InstancePtr is a pointer to the XV_frmbufwr instance. The current value of the Interrupt Enable Register (IER).
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr::IsReady, XV_FRMBUFWR_CTRL_ADDR_IER.
u32 XV_frmbufwr_InterruptGetStatus(XV_frmbufwr *InstancePtr)
Retrieves the interrupt status register value for the XV_frmbufwr instance.
This function checks that the provided instance pointer is valid and that the instance is ready. It then reads and returns the value of the Interrupt Status Register (ISR) for the frame buffer write hardware. InstancePtr is a pointer to the XV_frmbufwr instance. The current value of the Interrupt Status Register (ISR).
References XV_frmbufwr_Config::BaseAddress, XV_frmbufwr::Config, XV_frmbufwr::IsReady, XV_FRMBUFWR_CTRL_ADDR_ISR.
Referenced by XVFrmbufWr_InterruptHandler.