xv_axi4s_remap.h
XV_axi4s_remap_WriteReg
Write to AXI4-Stream Remap register (bare-metal)
Referenced by videoIpConfig, XV_axi4s_remap_DisableAutoRestart, XV_axi4s_remap_EnableAutoRestart, XV_axi4s_remap_InterruptClear, XV_axi4s_remap_InterruptDisable, XV_axi4s_remap_InterruptEnable, XV_axi4s_remap_InterruptGlobalDisable, XV_axi4s_remap_InterruptGlobalEnable, XV_axi4s_remap_Set_ColorFormat, XV_axi4s_remap_Set_height, XV_axi4s_remap_Set_inHDMI420, XV_axi4s_remap_Set_inPixClk, XV_axi4s_remap_Set_inPixDrop, XV_axi4s_remap_Set_outHDMI420, XV_axi4s_remap_Set_outPixClk, XV_axi4s_remap_Set_outPixRepeat, XV_axi4s_remap_Set_width, XV_axi4s_remap_Start.
XV_axi4s_remap_ReadReg
Read from AXI4-Stream Remap register (bare-metal)
Referenced by XV_axi4s_remap_Get_ColorFormat, XV_axi4s_remap_Get_height, XV_axi4s_remap_Get_inHDMI420, XV_axi4s_remap_Get_inPixClk, XV_axi4s_remap_Get_inPixDrop, XV_axi4s_remap_Get_outHDMI420, XV_axi4s_remap_Get_outPixClk, XV_axi4s_remap_Get_outPixRepeat, XV_axi4s_remap_Get_width, XV_axi4s_remap_InterruptDisable, XV_axi4s_remap_InterruptEnable, XV_axi4s_remap_InterruptGetEnabled, XV_axi4s_remap_InterruptGetStatus, XV_axi4s_remap_IsDone, XV_axi4s_remap_IsIdle, XV_axi4s_remap_IsReady, XV_axi4s_remap_Start.
int XV_axi4s_remap_Initialize(XV_axi4s_remap *InstancePtr, UINTPTR BaseAddress)
Initialize AXI4-Stream Remap driver instance by base address (SDT)
This function initializes an AXI4-Stream Remap driver instance by looking up the device configuration based on the physical base address, then calling the configuration initialization function with the retrieved configuration. InstancePtr Pointer to the driver instance structure to initialize BaseAddress Physical base address of the hardware instance XST_SUCCESS if initialization completed successfully XST_DEVICE_NOT_FOUND if base address not found in configuration table Other error codes from XV_axi4s_remap_CfgInitialize() This is the SDT (System Device Tree) version that uses base addresses instead of device IDs InstancePtr->IsReady is set to 0 if device lookup fails
References XV_axi4s_remap_Config::BaseAddress, XV_axi4s_remap::IsReady, XV_axi4s_remap_CfgInitialize, XV_axi4s_remap_LookupConfig.
XV_axi4s_remap_Config* XV_axi4s_remap_LookupConfig(UINTPTR BaseAddress)
Lookup configuration structure by base address (SDT)
This function searches the configuration table for an AXI4-Stream Remap device matching the specified base address and returns a pointer to its configuration structure. If BaseAddress is 0, returns the first entry. BaseAddress Physical base address of the device to search for, or 0 to return the first available device Pointer to matching XV_axi4s_remap_Config structure if found NULL if no matching base address is found This is the SDT (System Device Tree) version that uses base addresses instead of device IDs
References XV_axi4s_remap_Config::Name.
Referenced by driverInit, XV_axi4s_remap_Initialize.
int XV_axi4s_remap_CfgInitialize(XV_axi4s_remap *InstancePtr, XV_axi4s_remap_Config *ConfigPtr, UINTPTR EffectiveAddr)
Initialize AXI4-Stream Remap driver with configuration.
This function initializes the AXI4-Stream Remap driver instance with the provided configuration structure and effective base address. It copies the configuration, sets the base address, and marks the driver as ready. InstancePtr Pointer to the driver instance structure to initialize ConfigPtr Pointer to the configuration structure EffectiveAddr Effective base address for the device registers XST_SUCCESS if initialization completed successfully This function is only available in bare-metal builds (not Linux)
References XV_axi4s_remap_Config::BaseAddress, XV_axi4s_remap::Config, XV_axi4s_remap::IsReady.
Referenced by driverInit, XV_axi4s_remap_Initialize.
void XV_axi4s_remap_Start(XV_axi4s_remap *InstancePtr)
Start the AXI4-Stream Remap core operation.
This function starts the AXI4-Stream Remap core by setting the AP_START bit in the control register while preserving the auto-restart setting. InstancePtr Pointer to the initialized driver instance None The driver instance must be ready (IsReady == XIL_COMPONENT_IS_READY)
References XV_axi4s_remap_Config::BaseAddress, XV_axi4s_remap::Config, XV_axi4s_remap::IsReady, XV_AXI4S_REMAP_CTRL_ADDR_AP_CTRL, XV_axi4s_remap_ReadReg, XV_axi4s_remap_WriteReg.
u32 XV_axi4s_remap_IsDone(XV_axi4s_remap *InstancePtr)
Check if the core operation is done.
This function checks the AP_DONE bit in the control register to determine if the current operation has completed. InstancePtr Pointer to the initialized driver instance 1 if operation is done, 0 otherwise The driver instance must be ready (IsReady == XIL_COMPONENT_IS_READY)
References XV_axi4s_remap_Config::BaseAddress, XV_axi4s_remap::Config, XV_axi4s_remap::IsReady, XV_AXI4S_REMAP_CTRL_ADDR_AP_CTRL, XV_axi4s_remap_ReadReg.
u32 XV_axi4s_remap_IsIdle(XV_axi4s_remap *InstancePtr)
Check if the core is idle.
This function checks the AP_IDLE bit in the control register to determine if the core is currently idle and not processing data. InstancePtr Pointer to the initialized driver instance 1 if core is idle, 0 if core is busy The driver instance must be ready (IsReady == XIL_COMPONENT_IS_READY)
References XV_axi4s_remap_Config::BaseAddress, XV_axi4s_remap::Config, XV_axi4s_remap::IsReady, XV_AXI4S_REMAP_CTRL_ADDR_AP_CTRL, XV_axi4s_remap_ReadReg.
u32 XV_axi4s_remap_IsReady(XV_axi4s_remap *InstancePtr)
Check if the core is ready for new input.
This function checks if the core is ready to accept new input by verifying that the AP_START bit is not set. InstancePtr Pointer to the initialized driver instance 1 if core is ready for new input, 0 if core is busy The driver instance must be ready (IsReady == XIL_COMPONENT_IS_READY)
References XV_axi4s_remap_Config::BaseAddress, XV_axi4s_remap::Config, XV_axi4s_remap::IsReady, XV_AXI4S_REMAP_CTRL_ADDR_AP_CTRL, XV_axi4s_remap_ReadReg.
void XV_axi4s_remap_EnableAutoRestart(XV_axi4s_remap *InstancePtr)
Enable automatic restart of the core.
This function enables the auto-restart feature which causes the core to automatically restart processing after completing an operation. InstancePtr Pointer to the initialized driver instance None The driver instance must be ready (IsReady == XIL_COMPONENT_IS_READY)
References XV_axi4s_remap_Config::BaseAddress, XV_axi4s_remap::Config, XV_axi4s_remap::IsReady, XV_AXI4S_REMAP_CTRL_ADDR_AP_CTRL, XV_axi4s_remap_WriteReg.
void XV_axi4s_remap_DisableAutoRestart(XV_axi4s_remap *InstancePtr)
Disable automatic restart of the core.
This function disables the auto-restart feature, requiring manual restart via XV_axi4s_remap_Start() after each operation completes. InstancePtr Pointer to the initialized driver instance None The driver instance must be ready (IsReady == XIL_COMPONENT_IS_READY)
References XV_axi4s_remap_Config::BaseAddress, XV_axi4s_remap::Config, XV_axi4s_remap::IsReady, XV_AXI4S_REMAP_CTRL_ADDR_AP_CTRL, XV_axi4s_remap_WriteReg.
void XV_axi4s_remap_Set_height(XV_axi4s_remap *InstancePtr, u32 Data)
Set the video frame height.
This function configures the height (number of rows) of the video frame to be processed by the AXI4-Stream Remap core. InstancePtr Pointer to the initialized driver instance Data Frame height in pixels None The driver instance must be ready (IsReady == XIL_COMPONENT_IS_READY)
References XV_axi4s_remap_Config::BaseAddress, XV_axi4s_remap::Config, XV_axi4s_remap::IsReady, XV_AXI4S_REMAP_CTRL_ADDR_HEIGHT_DATA, XV_axi4s_remap_WriteReg.
Referenced by videoIpConfig.
u32 XV_axi4s_remap_Get_height(XV_axi4s_remap *InstancePtr)
Get the configured video frame height.
This function reads the currently configured height (number of rows) of the video frame from the AXI4-Stream Remap core. InstancePtr Pointer to the initialized driver instance Configured frame height in pixels The driver instance must be ready (IsReady == XIL_COMPONENT_IS_READY)
References XV_axi4s_remap_Config::BaseAddress, XV_axi4s_remap::Config, XV_axi4s_remap::IsReady, XV_AXI4S_REMAP_CTRL_ADDR_HEIGHT_DATA, XV_axi4s_remap_ReadReg.
void XV_axi4s_remap_Set_width(XV_axi4s_remap *InstancePtr, u32 Data)
Set the video frame width.
This function configures the width (number of columns) of the video frame to be processed by the AXI4-Stream Remap core. InstancePtr Pointer to the initialized driver instance Data Frame width in pixels None The driver instance must be ready (IsReady == XIL_COMPONENT_IS_READY)
References XV_axi4s_remap_Config::BaseAddress, XV_axi4s_remap::Config, XV_axi4s_remap::IsReady, XV_AXI4S_REMAP_CTRL_ADDR_WIDTH_DATA, XV_axi4s_remap_WriteReg.
Referenced by videoIpConfig.
u32 XV_axi4s_remap_Get_width(XV_axi4s_remap *InstancePtr)
Get the configured video frame width.
This function reads the currently configured width (number of columns) of the video frame from the AXI4-Stream Remap core. InstancePtr Pointer to the initialized driver instance Configured frame width in pixels The driver instance must be ready (IsReady == XIL_COMPONENT_IS_READY)
References XV_axi4s_remap_Config::BaseAddress, XV_axi4s_remap::Config, XV_axi4s_remap::IsReady, XV_AXI4S_REMAP_CTRL_ADDR_WIDTH_DATA, XV_axi4s_remap_ReadReg.
void XV_axi4s_remap_Set_ColorFormat(XV_axi4s_remap *InstancePtr, u32 Data)
Set the color format configuration.
This function configures the color format to be used for video stream processing by the AXI4-Stream Remap core. InstancePtr Pointer to the initialized driver instance Data Color format value None The driver instance must be ready (IsReady == XIL_COMPONENT_IS_READY)
References XV_axi4s_remap_Config::BaseAddress, XV_axi4s_remap::Config, XV_axi4s_remap::IsReady, XV_AXI4S_REMAP_CTRL_ADDR_COLORFORMAT_DATA, XV_axi4s_remap_WriteReg.
Referenced by videoIpConfig.
u32 XV_axi4s_remap_Get_ColorFormat(XV_axi4s_remap *InstancePtr)
Get the configured color format.
This function reads the currently configured color format from the AXI4-Stream Remap core. InstancePtr Pointer to the initialized driver instance Configured color format value The driver instance must be ready (IsReady == XIL_COMPONENT_IS_READY)
References XV_axi4s_remap_Config::BaseAddress, XV_axi4s_remap::Config, XV_axi4s_remap::IsReady, XV_AXI4S_REMAP_CTRL_ADDR_COLORFORMAT_DATA, XV_axi4s_remap_ReadReg.
void XV_axi4s_remap_Set_inPixClk(XV_axi4s_remap *InstancePtr, u32 Data)
Set the input pixels per clock.
This function configures the number of pixels per clock cycle for the input video stream. InstancePtr Pointer to the initialized driver instance Data Number of input pixels per clock (1, 2, or 4) None The driver instance must be ready (IsReady == XIL_COMPONENT_IS_READY)
References XV_axi4s_remap_Config::BaseAddress, XV_axi4s_remap::Config, XV_axi4s_remap::IsReady, XV_AXI4S_REMAP_CTRL_ADDR_INPIXCLK_DATA, XV_axi4s_remap_WriteReg.
Referenced by videoIpConfig.
u32 XV_axi4s_remap_Get_inPixClk(XV_axi4s_remap *InstancePtr)
Get the configured input pixels per clock.
This function reads the currently configured number of pixels per clock cycle for the input video stream. InstancePtr Pointer to the initialized driver instance Configured number of input pixels per clock The driver instance must be ready (IsReady == XIL_COMPONENT_IS_READY)
References XV_axi4s_remap_Config::BaseAddress, XV_axi4s_remap::Config, XV_axi4s_remap::IsReady, XV_AXI4S_REMAP_CTRL_ADDR_INPIXCLK_DATA, XV_axi4s_remap_ReadReg.
void XV_axi4s_remap_Set_outPixClk(XV_axi4s_remap *InstancePtr, u32 Data)
Set the output pixels per clock.
This function configures the number of pixels per clock cycle for the output video stream. InstancePtr Pointer to the initialized driver instance Data Number of output pixels per clock (1, 2, or 4) None The driver instance must be ready (IsReady == XIL_COMPONENT_IS_READY)
References XV_axi4s_remap_Config::BaseAddress, XV_axi4s_remap::Config, XV_axi4s_remap::IsReady, XV_AXI4S_REMAP_CTRL_ADDR_OUTPIXCLK_DATA, XV_axi4s_remap_WriteReg.
Referenced by videoIpConfig.
u32 XV_axi4s_remap_Get_outPixClk(XV_axi4s_remap *InstancePtr)
Get the configured output pixels per clock.
This function reads the currently configured number of pixels per clock cycle for the output video stream. InstancePtr Pointer to the initialized driver instance Configured number of output pixels per clock The driver instance must be ready (IsReady == XIL_COMPONENT_IS_READY)
References XV_axi4s_remap_Config::BaseAddress, XV_axi4s_remap::Config, XV_axi4s_remap::IsReady, XV_AXI4S_REMAP_CTRL_ADDR_OUTPIXCLK_DATA, XV_axi4s_remap_ReadReg.
void XV_axi4s_remap_Set_inHDMI420(XV_axi4s_remap *InstancePtr, u32 Data)
Set input HDMI 4:2:0 mode enable.
This function enables or disables HDMI 4:2:0 format processing for the input video stream. InstancePtr Pointer to the initialized driver instance Data 1 to enable HDMI 4:2:0 mode, 0 to disable None The driver instance must be ready (IsReady == XIL_COMPONENT_IS_READY)
References XV_axi4s_remap_Config::BaseAddress, XV_axi4s_remap::Config, XV_axi4s_remap::IsReady, XV_AXI4S_REMAP_CTRL_ADDR_INHDMI420_DATA, XV_axi4s_remap_WriteReg.
Referenced by videoIpConfig.
u32 XV_axi4s_remap_Get_inHDMI420(XV_axi4s_remap *InstancePtr)
Get input HDMI 4:2:0 mode configuration.
This function reads whether HDMI 4:2:0 format processing is enabled for the input video stream. InstancePtr Pointer to the initialized driver instance 1 if HDMI 4:2:0 mode is enabled, 0 if disabled The driver instance must be ready (IsReady == XIL_COMPONENT_IS_READY)
References XV_axi4s_remap_Config::BaseAddress, XV_axi4s_remap::Config, XV_axi4s_remap::IsReady, XV_AXI4S_REMAP_CTRL_ADDR_INHDMI420_DATA, XV_axi4s_remap_ReadReg.
void XV_axi4s_remap_Set_outHDMI420(XV_axi4s_remap *InstancePtr, u32 Data)
Set output HDMI 4:2:0 mode enable.
This function enables or disables HDMI 4:2:0 format processing for the output video stream. InstancePtr Pointer to the initialized driver instance Data 1 to enable HDMI 4:2:0 mode, 0 to disable None The driver instance must be ready (IsReady == XIL_COMPONENT_IS_READY)
References XV_axi4s_remap_Config::BaseAddress, XV_axi4s_remap::Config, XV_axi4s_remap::IsReady, XV_AXI4S_REMAP_CTRL_ADDR_OUTHDMI420_DATA, XV_axi4s_remap_WriteReg.
Referenced by videoIpConfig.
u32 XV_axi4s_remap_Get_outHDMI420(XV_axi4s_remap *InstancePtr)
Get output HDMI 4:2:0 mode configuration.
This function reads whether HDMI 4:2:0 format processing is enabled for the output video stream. InstancePtr Pointer to the initialized driver instance 1 if HDMI 4:2:0 mode is enabled, 0 if disabled The driver instance must be ready (IsReady == XIL_COMPONENT_IS_READY)
References XV_axi4s_remap_Config::BaseAddress, XV_axi4s_remap::Config, XV_axi4s_remap::IsReady, XV_AXI4S_REMAP_CTRL_ADDR_OUTHDMI420_DATA, XV_axi4s_remap_ReadReg.
void XV_axi4s_remap_Set_inPixDrop(XV_axi4s_remap *InstancePtr, u32 Data)
Set input pixel drop enable.
This function enables or disables pixel dropping on the input video stream to adjust the effective pixel rate. InstancePtr Pointer to the initialized driver instance Data 1 to enable pixel drop, 0 to disable None The driver instance must be ready (IsReady == XIL_COMPONENT_IS_READY)
References XV_axi4s_remap_Config::BaseAddress, XV_axi4s_remap::Config, XV_axi4s_remap::IsReady, XV_AXI4S_REMAP_CTRL_ADDR_INPIXDROP_DATA, XV_axi4s_remap_WriteReg.
Referenced by videoIpConfig.
u32 XV_axi4s_remap_Get_inPixDrop(XV_axi4s_remap *InstancePtr)
Get input pixel drop configuration.
This function reads whether pixel dropping is enabled on the input video stream. InstancePtr Pointer to the initialized driver instance 1 if pixel drop is enabled, 0 if disabled The driver instance must be ready (IsReady == XIL_COMPONENT_IS_READY)
References XV_axi4s_remap_Config::BaseAddress, XV_axi4s_remap::Config, XV_axi4s_remap::IsReady, XV_AXI4S_REMAP_CTRL_ADDR_INPIXDROP_DATA, XV_axi4s_remap_ReadReg.
void XV_axi4s_remap_Set_outPixRepeat(XV_axi4s_remap *InstancePtr, u32 Data)
Set output pixel repeat enable.
This function enables or disables pixel repetition on the output video stream to adjust the effective pixel rate. InstancePtr Pointer to the initialized driver instance Data 1 to enable pixel repeat, 0 to disable None The driver instance must be ready (IsReady == XIL_COMPONENT_IS_READY)
References XV_axi4s_remap_Config::BaseAddress, XV_axi4s_remap::Config, XV_axi4s_remap::IsReady, XV_AXI4S_REMAP_CTRL_ADDR_OUTPIXREPEAT_DATA, XV_axi4s_remap_WriteReg.
Referenced by videoIpConfig.
u32 XV_axi4s_remap_Get_outPixRepeat(XV_axi4s_remap *InstancePtr)
Get output pixel repeat configuration.
This function reads whether pixel repetition is enabled on the output video stream. InstancePtr Pointer to the initialized driver instance 1 if pixel repeat is enabled, 0 if disabled The driver instance must be ready (IsReady == XIL_COMPONENT_IS_READY)
References XV_axi4s_remap_Config::BaseAddress, XV_axi4s_remap::Config, XV_axi4s_remap::IsReady, XV_AXI4S_REMAP_CTRL_ADDR_OUTPIXREPEAT_DATA, XV_axi4s_remap_ReadReg.
void XV_axi4s_remap_InterruptGlobalEnable(XV_axi4s_remap *InstancePtr)
Enable global interrupts.
This function enables the global interrupt output from the AXI4-Stream Remap core by setting the Global Interrupt Enable (GIE) bit. InstancePtr Pointer to the initialized driver instance None The driver instance must be ready (IsReady == XIL_COMPONENT_IS_READY) Individual interrupts must also be enabled via InterruptEnable()
References XV_axi4s_remap_Config::BaseAddress, XV_axi4s_remap::Config, XV_axi4s_remap::IsReady, XV_AXI4S_REMAP_CTRL_ADDR_GIE, XV_axi4s_remap_WriteReg.
void XV_axi4s_remap_InterruptGlobalDisable(XV_axi4s_remap *InstancePtr)
Disable global interrupts.
This function disables the global interrupt output from the AXI4-Stream Remap core by clearing the Global Interrupt Enable (GIE) bit. InstancePtr Pointer to the initialized driver instance None The driver instance must be ready (IsReady == XIL_COMPONENT_IS_READY)
References XV_axi4s_remap_Config::BaseAddress, XV_axi4s_remap::Config, XV_axi4s_remap::IsReady, XV_AXI4S_REMAP_CTRL_ADDR_GIE, XV_axi4s_remap_WriteReg.
void XV_axi4s_remap_InterruptEnable(XV_axi4s_remap *InstancePtr, u32 Mask)
Enable specific interrupts.
This function enables individual interrupt sources by setting the corresponding bits in the Interrupt Enable Register (IER). InstancePtr Pointer to the initialized driver instance Mask Bitmask of interrupts to enable (bit 0: ap_done, bit 1: ap_ready) None The driver instance must be ready (IsReady == XIL_COMPONENT_IS_READY) Global interrupts must also be enabled via InterruptGlobalEnable()
References XV_axi4s_remap_Config::BaseAddress, XV_axi4s_remap::Config, XV_axi4s_remap::IsReady, XV_AXI4S_REMAP_CTRL_ADDR_IER, XV_axi4s_remap_ReadReg, XV_axi4s_remap_WriteReg.
void XV_axi4s_remap_InterruptDisable(XV_axi4s_remap *InstancePtr, u32 Mask)
Disable specific interrupts.
This function disables individual interrupt sources by clearing the corresponding bits in the Interrupt Enable Register (IER). InstancePtr Pointer to the initialized driver instance Mask Bitmask of interrupts to disable (bit 0: ap_done, bit 1: ap_ready) None The driver instance must be ready (IsReady == XIL_COMPONENT_IS_READY)
References XV_axi4s_remap_Config::BaseAddress, XV_axi4s_remap::Config, XV_axi4s_remap::IsReady, XV_AXI4S_REMAP_CTRL_ADDR_IER, XV_axi4s_remap_ReadReg, XV_axi4s_remap_WriteReg.
void XV_axi4s_remap_InterruptClear(XV_axi4s_remap *InstancePtr, u32 Mask)
Clear interrupt status flags.
This function clears pending interrupt status bits by writing to the Interrupt Status Register (ISR). This is a toggle-on-write register. InstancePtr Pointer to the initialized driver instance Mask Bitmask of interrupt flags to clear None The driver instance must be ready (IsReady == XIL_COMPONENT_IS_READY) Writing 1 to a bit toggles/clears that interrupt status
References XV_axi4s_remap_Config::BaseAddress, XV_axi4s_remap::Config, XV_axi4s_remap::IsReady, XV_AXI4S_REMAP_CTRL_ADDR_ISR, XV_axi4s_remap_WriteReg.
u32 XV_axi4s_remap_InterruptGetEnabled(XV_axi4s_remap *InstancePtr)
Get enabled interrupt mask.
This function reads the Interrupt Enable Register (IER) to determine which interrupt sources are currently enabled. InstancePtr Pointer to the initialized driver instance Bitmask of enabled interrupts (bit 0: ap_done, bit 1: ap_ready) The driver instance must be ready (IsReady == XIL_COMPONENT_IS_READY)
References XV_axi4s_remap_Config::BaseAddress, XV_axi4s_remap::Config, XV_axi4s_remap::IsReady, XV_AXI4S_REMAP_CTRL_ADDR_IER, XV_axi4s_remap_ReadReg.
u32 XV_axi4s_remap_InterruptGetStatus(XV_axi4s_remap *InstancePtr)
Get interrupt status flags.
This function reads the Interrupt Status Register (ISR) to determine which interrupt conditions are currently pending. InstancePtr Pointer to the initialized driver instance Bitmask of pending interrupt flags (bit 0: ap_done, bit 1: ap_ready) The driver instance must be ready (IsReady == XIL_COMPONENT_IS_READY) Use InterruptClear() to clear pending interrupt flags
References XV_axi4s_remap_Config::BaseAddress, XV_axi4s_remap::Config, XV_axi4s_remap::IsReady, XV_AXI4S_REMAP_CTRL_ADDR_ISR, XV_axi4s_remap_ReadReg.