xv_hscaler.h
XV_hscaler_WriteReg
XV_hscaler_ReadReg
int XV_hscaler_Initialize(XV_hscaler *InstancePtr, UINTPTR BaseAddress)
XV_hscaler_Initialize - Initializes an instance of the XV_hscaler driver.
This function looks up the configuration for a given device using the specified base address, and then initializes the XV_hscaler instance with the found configuration. If the configuration cannot be found, the function sets the instance as not ready and returns an error code. InstancePtr Pointer to the XV_hscaler instance to be initialized. BaseAddress Base address of the device to initialize. XST_SUCCESS if initialization was successful.XST_DEVICE_NOT_FOUND if the device configuration could not be found. The caller must ensure that the InstancePtr is not NULL.This function must be called before using the XV_hscaler instance.
References XV_hscaler_Config::BaseAddress, XV_hscaler::IsReady, XV_hscaler_CfgInitialize, XV_hscaler_LookupConfig.
Referenced by XV_HScalerInitialize.
XV_hscaler_Config* XV_hscaler_LookupConfig(UINTPTR BaseAddress)
XV_hscaler_LookupConfig - Looks up the configuration for a V_HScaler device.
This function searches the XV_hscaler_ConfigTable for a configuration entry that matches the specified BaseAddress. If a matching entry is found, a pointer to its configuration structure is returned. If BaseAddress is zero or NULL, the function returns the first entry in the table. BaseAddress The base address of the device instance to look up. A pointer to the configuration structure if found, or NULL if no matching entry exists.
Referenced by XV_hscaler_Initialize.
int XV_hscaler_CfgInitialize(XV_hscaler *InstancePtr, XV_hscaler_Config *ConfigPtr, UINTPTR EffectiveAddr)
XV_hscaler_CfgInitialize - Initializes an XV_hscaler instance.
InstancePtr is a pointer to the XV_hscaler instance to be worked on. ConfigPtr points to the configuration structure. EffectiveAddr is the base address of the device. XST_SUCCESS if initialization was successful. None. XV_hscaler_CfgInitialize - Initialize an XV_hscaler instance. This function initializes an XV_hscaler instance using the provided configuration structure and effective base address. It copies the configuration, sets the base address, and marks the instance as ready for use. InstancePtr Pointer to the XV_hscaler instance to be initialized. ConfigPtr Pointer to the configuration structure for the device. EffectiveAddr Physical base address of the device. XST_SUCCESS if initialization was successful. Preconditions: InstancePtr must not be NULL.ConfigPtr must not be NULL.EffectiveAddr must not be NULL.
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady.
Referenced by XV_hscaler_Initialize.
void XV_hscaler_Start(XV_hscaler *InstancePtr)
XV_hscaler_Start - Start the HScaler hardware.
InstancePtr is a pointer to the XV_hscaler instance. None This function sets the ap_start bit in the control register to start the hardware. It preserves the auto-restart bit.
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady, XV_HSCALER_CTRL_ADDR_AP_CTRL.
Referenced by XV_HScalerStart.
u32 XV_hscaler_IsDone(XV_hscaler *InstancePtr)
XV_hscaler_IsDone - Check if the HScaler operation is done.
InstancePtr is a pointer to the XV_hscaler instance. This function reads the control register and checks the ap_done bit (bit 1) to determine if the hardware has finished processing.1 if done, 0 otherwise.
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady, XV_HSCALER_CTRL_ADDR_AP_CTRL.
Referenced by XV_HScalerDbgReportStatus.
u32 XV_hscaler_IsIdle(XV_hscaler *InstancePtr)
XV_hscaler_IsIdle - Check if the HScaler hardware is idle.
InstancePtr is a pointer to the XV_hscaler instance. This function reads the control register and checks the ap_idle bit (bit 2) to determine if the hardware is idle.1 if idle, 0 otherwise.
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady, XV_HSCALER_CTRL_ADDR_AP_CTRL.
Referenced by XV_HScalerDbgReportStatus.
u32 XV_hscaler_IsReady(XV_hscaler *InstancePtr)
XV_hscaler_IsReady - Check if HScaler is ready for next input.
InstancePtr is a pointer to the XV_hscaler instance. This function reads the control register and checks the ap_start bit (bit 0) to determine if the hardware is ready for the next input. Returns 1 if ready, 0 otherwise.1 if ready, 0 otherwise.
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady, XV_HSCALER_CTRL_ADDR_AP_CTRL.
Referenced by XV_HScalerDbgReportStatus.
void XV_hscaler_EnableAutoRestart(XV_hscaler *InstancePtr)
XV_hscaler_EnableAutoRestart - Enable auto-restart mode.
InstancePtr is a pointer to the XV_hscaler instance. None This function sets the auto-restart bit (bit 7) in the control register, enabling the hardware to automatically restart after completing an operation.
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady, XV_HSCALER_CTRL_ADDR_AP_CTRL.
Referenced by XV_HScalerStart.
void XV_hscaler_DisableAutoRestart(XV_hscaler *InstancePtr)
XV_hscaler_DisableAutoRestart - Disable auto-restart mode.
InstancePtr is a pointer to the XV_hscaler instance. None This function clears the auto-restart bit (bit 7) in the control register, disabling the hardware from automatically restarting after completing an operation.
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady, XV_HSCALER_CTRL_ADDR_AP_CTRL.
Referenced by XV_HScalerStop.
void XV_hscaler_Set_HwReg_Height(XV_hscaler *InstancePtr, u32 Data)
XV_hscaler_Set_HwReg_Height - Set the HWREG_HEIGHT register.
InstancePtr is a pointer to the XV_hscaler instance. Data is the value to write to HWREG_HEIGHT register. None This function writes the specified value to the HWREG_HEIGHT register of the HScaler hardware.
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady.
Referenced by XV_HScalerSetup.
u32 XV_hscaler_Get_HwReg_Height(XV_hscaler *InstancePtr)
XV_hscaler_Get_HwReg_Height - Get HWREG_HEIGHT register value.
InstancePtr is a pointer to the XV_hscaler instance. This function reads the HWREG_HEIGHT register from the HScaler hardware and returns its value.Value of HWREG_HEIGHT register.
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady.
Referenced by XV_HScalerDbgReportStatus.
void XV_hscaler_Set_HwReg_WidthIn(XV_hscaler *InstancePtr, u32 Data)
XV_hscaler_Set_HwReg_WidthIn - Set HWREG_WIDTHIN register.
InstancePtr is a pointer to the XV_hscaler instance. Data is the value to write to HWREG_WIDTHIN register. None This function writes the specified value to the HWREG_WIDTHIN register of the HScaler hardware.
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady.
Referenced by XV_HScalerSetup.
u32 XV_hscaler_Get_HwReg_WidthIn(XV_hscaler *InstancePtr)
XV_hscaler_Get_HwReg_WidthIn - Get HWREG_WIDTHIN register value.
InstancePtr is a pointer to the XV_hscaler instance. This function reads the HWREG_WIDTHIN register from the HScaler hardware and returns its value.Value of HWREG_WIDTHIN register.
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady.
Referenced by XV_HScalerDbgReportStatus.
void XV_hscaler_Set_HwReg_WidthOut(XV_hscaler *InstancePtr, u32 Data)
XV_hscaler_Set_HwReg_WidthOut - Set HWREG_WIDTHOUT register.
InstancePtr is a pointer to the XV_hscaler instance. Data is the value to write to HWREG_WIDTHOUT register. None This function writes the specified value to the HWREG_WIDTHOUT register of the HScaler hardware.
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady.
Referenced by XV_HScalerSetup.
u32 XV_hscaler_Get_HwReg_WidthOut(XV_hscaler *InstancePtr)
XV_hscaler_Get_HwReg_WidthOut - Get HWREG_WIDTHOUT register value.
InstancePtr is a pointer to the XV_hscaler instance. This function reads the HWREG_WIDTHOUT register from the HScaler hardware and returns its value.Value of HWREG_WIDTHOUT register.
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady.
Referenced by XV_HScalerDbgReportStatus.
void XV_hscaler_Set_HwReg_ColorMode(XV_hscaler *InstancePtr, u32 Data)
XV_hscaler_Set_HwReg_ColorMode - Set HWREG_COLORMODE register.
InstancePtr is a pointer to the XV_hscaler instance. Data is the value to write to HWREG_COLORMODE register. None This function writes the specified value to the HWREG_COLORMODE register of the HScaler hardware.
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady.
Referenced by XV_HScalerSetup.
u32 XV_hscaler_Get_HwReg_ColorMode(XV_hscaler *InstancePtr)
XV_hscaler_Get_HwReg_ColorMode - Get HWREG_COLORMODE register value.
InstancePtr is a pointer to the XV_hscaler instance. This function reads the HWREG_COLORMODE register from the HScaler hardware and returns its value.Value of HWREG_COLORMODE register.
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady.
Referenced by XV_HScalerDbgReportStatus.
void XV_hscaler_Set_HwReg_ColorModeOut(XV_hscaler *InstancePtr, u32 Data)
XV_hscaler_Set_HwReg_ColorModeOut - Set HWREG_COLORMODEOUT reg.
InstancePtr is a pointer to the XV_hscaler instance. Data is the value to write to HWREG_COLORMODEOUT reg. None This function writes the specified value to the HWREG_COLORMODEOUT register of the HScaler hardware.
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady.
Referenced by XV_HScalerSetup.
u32 XV_hscaler_Get_HwReg_ColorModeOut(XV_hscaler *InstancePtr)
XV_hscaler_Get_HwReg_ColorModeOut - Get HWREG_COLORMODEOUT reg value.
InstancePtr is a pointer to the XV_hscaler instance. This function reads the HWREG_COLORMODEOUT register from the HScaler hardware and returns its value.Value of HWREG_COLORMODEOUT register.
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady.
Referenced by XV_HScalerDbgReportStatus.
void XV_hscaler_Set_HwReg_PixelRate(XV_hscaler *InstancePtr, u32 Data)
This function sets the hardware register pixel rate.
InstancePtr Pointer to the XV_hscaler instance. Data The value to set in the hardware register pixel rate. None
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady.
Referenced by XV_HScalerSetup.
u32 XV_hscaler_Get_HwReg_PixelRate(XV_hscaler *InstancePtr)
This function gets the hardware register pixel rate.
InstancePtr Pointer to the XV_hscaler instance. The value of the hardware register pixel rate.
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady.
Referenced by XV_HScalerDbgReportStatus.
UINTPTR XV_hscaler_Get_HwReg_hfltCoeff_BaseAddress(XV_hscaler *InstancePtr)
This function gets the base address of the hardware register hfltCoeff.
InstancePtr Pointer to the XV_hscaler instance. The base address of the hardware register hfltCoeff.
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady.
Referenced by XV_HScalerDbgReportStatus.
UINTPTR XV_hscaler_Get_HwReg_hfltCoeff_HighAddress(XV_hscaler *InstancePtr)
This function gets the high address of the hardware register hfltCoeff.
InstancePtr Pointer to the XV_hscaler instance. The high address of the hardware register hfltCoeff.
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady.
u32 XV_hscaler_Get_HwReg_hfltCoeff_TotalBytes(XV_hscaler *InstancePtr)
This function gets the total bytes of the hardware register hfltCoeff.
InstancePtr Pointer to the XV_hscaler instance. The total bytes of the hardware register hfltCoeff.
References XV_hscaler::IsReady.
u32 XV_hscaler_Get_HwReg_hfltCoeff_BitWidth(XV_hscaler *InstancePtr)
This function gets the bit width of the hardware register hfltCoeff.
InstancePtr Pointer to the XV_hscaler instance. The bit width of the hardware register hfltCoeff.
References XV_hscaler::IsReady.
u32 XV_hscaler_Get_HwReg_hfltCoeff_Depth(XV_hscaler *InstancePtr)
This function gets the depth of the hardware register hfltCoeff.
InstancePtr Pointer to the XV_hscaler instance. The depth of the hardware register hfltCoeff.
References XV_hscaler::IsReady.
u32 XV_hscaler_Write_HwReg_hfltCoeff_Words(XV_hscaler *InstancePtr, int offset, int *data, int length)
This function writes words to the hardware register hfltCoeff.
InstancePtr Pointer to the XV_hscaler instance. offset The offset to start writing. data Pointer to the data to write. length The number of words to write. The number of words written.
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady.
u32 XV_hscaler_Read_HwReg_hfltCoeff_Words(XV_hscaler *InstancePtr, int offset, int *data, int length)
This function reads words from the hardware register hfltCoeff.
InstancePtr Pointer to the XV_hscaler instance. offset The offset to start reading. data Pointer to the buffer to store the read data. length The number of words to read. The number of words read.
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady.
u32 XV_hscaler_Write_HwReg_hfltCoeff_Bytes(XV_hscaler *InstancePtr, int offset, char *data, int length)
This function writes bytes to the hardware register hfltCoeff.
InstancePtr Pointer to the XV_hscaler instance. offset The offset to start writing. data Pointer to the data to write. length The number of bytes to write. The number of bytes written.
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady.
u32 XV_hscaler_Read_HwReg_hfltCoeff_Bytes(XV_hscaler *InstancePtr, int offset, char *data, int length)
This function reads bytes from the hardware register hfltCoeff.
InstancePtr Pointer to the XV_hscaler instance. offset The offset to start reading. data Pointer to the buffer to store the read data. length The number of bytes to read. The number of bytes read.
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady.
UINTPTR XV_hscaler_Get_HwReg_phasesH_V_BaseAddress(XV_hscaler *InstancePtr)
This function gets the base address of the hardware register phasesH_V.
InstancePtr Pointer to the XV_hscaler instance. The base address of the hardware register phasesH_V.
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady.
UINTPTR XV_hscaler_Get_HwReg_phasesH_V_HighAddress(XV_hscaler *InstancePtr)
function gets the high address of the hardware register phasesH_V.
InstancePtr Pointer to the XV_hscaler instance. The high address of the hardware register phasesH_V.
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady.
u32 XV_hscaler_Get_HwReg_phasesH_V_TotalBytes(XV_hscaler *InstancePtr)
This function gets the total bytes of the hardware register phasesH_V.
InstancePtr Pointer to the XV_hscaler instance. The total bytes of the hardware register phasesH_V.
References XV_hscaler::IsReady.
u32 XV_hscaler_Get_HwReg_phasesH_V_BitWidth(XV_hscaler *InstancePtr)
This function gets the bit width of the hardware register phasesH_V.
InstancePtr Pointer to the XV_hscaler instance. The bit width of the hardware register phasesH_V.
References XV_hscaler::IsReady.
u32 XV_hscaler_Get_HwReg_phasesH_V_Depth(XV_hscaler *InstancePtr)
This function gets the depth of the hardware register phasesH_V.
InstancePtr Pointer to the XV_hscaler instance. The depth of the hardware register phasesH_V.
References XV_hscaler::IsReady.
u32 XV_hscaler_Write_HwReg_phasesH_V_Words(XV_hscaler *InstancePtr, int offset, int *data, int length)
This function writes words to the hardware register phasesH_V.
InstancePtr Pointer to the XV_hscaler instance. offset The offset to start writing. data Pointer to the data to write. length The number of words to write. The number of words written.
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady.
u32 XV_hscaler_Read_HwReg_phasesH_V_Words(XV_hscaler *InstancePtr, int offset, int *data, int length)
This function reads words from the hardware register phasesH_V.
InstancePtr Pointer to the XV_hscaler instance. offset The offset to start reading. data Pointer to the buffer to store the read data. length The number of words to read. The number of words read.
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady.
u32 XV_hscaler_Write_HwReg_phasesH_V_Bytes(XV_hscaler *InstancePtr, int offset, char *data, int length)
This function writes bytes to the hardware register phasesH_V.
InstancePtr Pointer to the XV_hscaler instance. offset The offset to start writing. data Pointer to the data to write. length The number of bytes to write. The number of bytes written.
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady.
u32 XV_hscaler_Read_HwReg_phasesH_V_Bytes(XV_hscaler *InstancePtr, int offset, char *data, int length)
This function reads bytes from the hardware register phasesH_V.
InstancePtr Pointer to the XV_hscaler instance. offset The offset to start reading. data Pointer to the buffer to store the read data. length The number of bytes to read. The number of bytes read.
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady.
void XV_hscaler_InterruptGlobalEnable(XV_hscaler *InstancePtr)
This function enables global interrupts.
InstancePtr Pointer to the XV_hscaler instance. None
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady.
void XV_hscaler_InterruptGlobalDisable(XV_hscaler *InstancePtr)
This function disables global interrupts.
InstancePtr Pointer to the XV_hscaler instance. None
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady.
void XV_hscaler_InterruptEnable(XV_hscaler *InstancePtr, u32 Mask)
This function enables specific interrupts.
InstancePtr Pointer to the XV_hscaler instance. Mask The mask of interrupts to enable. None
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady.
void XV_hscaler_InterruptDisable(XV_hscaler *InstancePtr, u32 Mask)
This function disables specific interrupts.
InstancePtr Pointer to the XV_hscaler instance. Mask The mask of interrupts to disable. None
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady.
void XV_hscaler_InterruptClear(XV_hscaler *InstancePtr, u32 Mask)
This function clears specific interrupts.
InstancePtr Pointer to the XV_hscaler instance. Mask The mask of interrupts to clear. None
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady.
u32 XV_hscaler_InterruptGetEnabled(XV_hscaler *InstancePtr)
This function gets the enabled interrupts.
InstancePtr Pointer to the XV_hscaler instance. The mask of enabled interrupts.
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady.
u32 XV_hscaler_InterruptGetStatus(XV_hscaler *InstancePtr)
This function gets the interrupt status.
InstancePtr Pointer to the XV_hscaler instance. The mask of interrupt status.
References XV_hscaler_Config::BaseAddress, XV_hscaler::Config, XV_hscaler::IsReady.