/******************************************************************************
* Copyright (c) 2014 - 2020 Xilinx, Inc. All rights reserved.
* SPDX-License-Identifier: MIT
******************************************************************************/



#include "xparameters.h"
#include "xcfa.h"

/*
* The configuration table for devices
*/

XCfa_Config XCfa_ConfigTable[] =
{
	{
		XPAR_FMC_SENSOR_INPUT_V_CFA_1_DEVICE_ID,
		XPAR_FMC_SENSOR_INPUT_V_CFA_1_BASEADDR,
		XPAR_FMC_SENSOR_INPUT_V_CFA_1_S_AXIS_VIDEO_DATA_WIDTH,
		XPAR_FMC_SENSOR_INPUT_V_CFA_1_M_AXIS_VIDEO_DATA_WIDTH,
		XPAR_FMC_SENSOR_INPUT_V_CFA_1_S_AXIS_VIDEO_TDATA_WIDTH,
		XPAR_FMC_SENSOR_INPUT_V_CFA_1_M_AXIS_VIDEO_TDATA_WIDTH,
		XPAR_FMC_SENSOR_INPUT_V_CFA_1_S_AXIS_VIDEO_FORMAT,
		XPAR_FMC_SENSOR_INPUT_V_CFA_1_M_AXIS_VIDEO_FORMAT,
		XPAR_FMC_SENSOR_INPUT_V_CFA_1_S_AXIS_VIDEO_TUSER_WIDTH,
		XPAR_FMC_SENSOR_INPUT_V_CFA_1_M_AXIS_VIDEO_TUSER_WIDTH,
		XPAR_FMC_SENSOR_INPUT_V_CFA_1_S_AXI_ADDR_WIDTH,
		XPAR_FMC_SENSOR_INPUT_V_CFA_1_S_AXI_DATA_WIDTH,
		XPAR_FMC_SENSOR_INPUT_V_CFA_1_S_AXI_CLK_FREQ_HZ,
		XPAR_FMC_SENSOR_INPUT_V_CFA_1_BAYER_PHASE,
		XPAR_FMC_SENSOR_INPUT_V_CFA_1_ACTIVE_ROWS,
		XPAR_FMC_SENSOR_INPUT_V_CFA_1_ACTIVE_COLS,
		XPAR_FMC_SENSOR_INPUT_V_CFA_1_MAX_COLS,
		XPAR_FMC_SENSOR_INPUT_V_CFA_1_HAS_INTC_IF,
		XPAR_FMC_SENSOR_INPUT_V_CFA_1_HAS_AXI4_LITE,
		XPAR_FMC_SENSOR_INPUT_V_CFA_1_HAS_DEBUG,
		XPAR_FMC_SENSOR_INPUT_V_CFA_1_HOR_FILT,
		XPAR_FMC_SENSOR_INPUT_V_CFA_1_FRINGE_TOL
	}
};


