/**
 * (c) 2013 Xilinx Inc.
 * XREGDB v0.91
 * XREGCHDR v0.15
 *
 * Generated on: 2018-09-16
 *
 * @file: crp.h
 *
 *
 * This file contains confidential and proprietary information
 * of Xilinx, Inc. and is protected under U.S. and
 * international copyright and other intellectual property
 * laws.
 *
 * DISCLAIMER
 * This disclaimer is not a license and does not grant any
 * rights to the materials distributed herewith. Except as
 * otherwise provided in a valid license issued to you by
 * Xilinx, and to the maximum extent permitted by applicable
 * law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
 * WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
 * AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
 * BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
 * INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
 * (2) Xilinx shall not be liable (whether in contract or tort,
 * including negligence, or under any other theory of
 * liability) for any loss or damage of any kind or nature
 * related to, arising under or in connection with these
 * materials, including for any direct, or any indirect,
 * special, incidental, or consequential loss or damage
 * (including loss of data, profits, goodwill, or any type of
 * loss or damage suffered as a result of any action brought
 * by a third party) even if such damage or loss was
 * reasonably foreseeable or Xilinx had been advised of the
 * possibility of the same.
 *
 * CRITICAL APPLICATIONS
 * Xilinx products are not designed or intended to be fail-
 * safe, or for use in any application requiring fail-safe
 * performance, such as life-support or safety devices or
 * systems, Class III medical devices, nuclear facilities,
 * applications related to the deployment of airbags, or any
 * other applications that could lead to death, personal
 * injury, or severe property or environmental damage
 * (individually and collectively, "Critical
 * Applications"). Customer assumes the sole risk and
 * liability of any use of Xilinx products in Critical
 * Applications, subject only to applicable laws and
 * regulations governing limitations on product liability.
 *
 * THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
 * PART OF THIS FILE AT ALL TIMES.
 *
 * Naming Convention: <MODULE>_<REGISTER>[_<FIELD>[_<DESC>]]
 *     <MODULE>       Module name (e.g. can or usb)
 *     <REGISTER>     Register within the current module
 *     [_<FIELD>]     Bit field within a register
 *     [_<DESC>]      Type of bit field define:
 *         SHIFT:     Least significant bit for the field
 *         WIDTH:     Size of field in bites
 *         MASK:      A masking over a range of bits or a bit to
 *                    be used for setting or clearing
 *
 */

#ifndef _CRP_H_
#define _CRP_H_

#ifdef __cplusplus
extern "C" {
#endif

/**
 * CRP Base Address
 */
#define CRP_BASEADDR      0XF1260000

/**
 * Register: CRP_ERR_CTRL
 */
#define CRP_ERR_CTRL    ( ( CRP_BASEADDR ) + 0X00000000 )

#define CRP_ERR_CTRL_SLVERR_ENABLE_SHIFT   0
#define CRP_ERR_CTRL_SLVERR_ENABLE_WIDTH   1
#define CRP_ERR_CTRL_SLVERR_ENABLE_MASK    0X00000001

/**
 * Register: CRP_IR_STATUS
 */
#define CRP_IR_STATUS    ( ( CRP_BASEADDR ) + 0X00000004 )

#define CRP_IR_STATUS_ADDR_DECODE_ERR_SHIFT   0
#define CRP_IR_STATUS_ADDR_DECODE_ERR_WIDTH   1
#define CRP_IR_STATUS_ADDR_DECODE_ERR_MASK    0X00000001

/**
 * Register: CRP_IR_MASK
 */
#define CRP_IR_MASK    ( ( CRP_BASEADDR ) + 0X00000008 )

#define CRP_IR_MASK_ADDR_DECODE_ERR_SHIFT   0
#define CRP_IR_MASK_ADDR_DECODE_ERR_WIDTH   1
#define CRP_IR_MASK_ADDR_DECODE_ERR_MASK    0X00000001

/**
 * Register: CRP_IR_ENABLE
 */
#define CRP_IR_ENABLE    ( ( CRP_BASEADDR ) + 0X0000000C )

#define CRP_IR_ENABLE_ADDR_DECODE_ERR_SHIFT   0
#define CRP_IR_ENABLE_ADDR_DECODE_ERR_WIDTH   1
#define CRP_IR_ENABLE_ADDR_DECODE_ERR_MASK    0X00000001

/**
 * Register: CRP_IR_DISABLE
 */
#define CRP_IR_DISABLE    ( ( CRP_BASEADDR ) + 0X00000010 )

#define CRP_IR_DISABLE_ADDR_DECODE_ERR_SHIFT   0
#define CRP_IR_DISABLE_ADDR_DECODE_ERR_WIDTH   1
#define CRP_IR_DISABLE_ADDR_DECODE_ERR_MASK    0X00000001

/**
 * Register: CRP_ECO
 */
#define CRP_ECO    ( ( CRP_BASEADDR ) + 0X00000018 )

#define CRP_ECO_ECO_SHIFT   0
#define CRP_ECO_ECO_WIDTH   32
#define CRP_ECO_ECO_MASK    0XFFFFFFFF

/**
 * Register: CRP_WPROT
 */
#define CRP_WPROT    ( ( CRP_BASEADDR ) + 0X0000001C )

#define CRP_WPROT_ACTIVE_SHIFT   0
#define CRP_WPROT_ACTIVE_WIDTH   1
#define CRP_WPROT_ACTIVE_MASK    0X00000001

/**
 * Register: CRP_PLL_CLK_OTHER_DMN
 */
#define CRP_PLL_CLK_OTHER_DMN    ( ( CRP_BASEADDR ) + 0X00000020 )

#define CRP_PLL_CLK_OTHER_DMN_RPLL_BYPASS_SHIFT   1
#define CRP_PLL_CLK_OTHER_DMN_RPLL_BYPASS_WIDTH   1
#define CRP_PLL_CLK_OTHER_DMN_RPLL_BYPASS_MASK    0X00000002

#define CRP_PLL_CLK_OTHER_DMN_APLL_BYPASS_SHIFT   0
#define CRP_PLL_CLK_OTHER_DMN_APLL_BYPASS_WIDTH   1
#define CRP_PLL_CLK_OTHER_DMN_APLL_BYPASS_MASK    0X00000001

/**
 * Register: CRP_PMCPLL_CTRL
 */
#define CRP_PMCPLL_CTRL    ( ( CRP_BASEADDR ) + 0X00000040 )

#define CRP_PMCPLL_CTRL_POST_SRC_SHIFT   24
#define CRP_PMCPLL_CTRL_POST_SRC_WIDTH   3
#define CRP_PMCPLL_CTRL_POST_SRC_MASK    0X07000000

#define CRP_PMCPLL_CTRL_PRE_SRC_SHIFT   20
#define CRP_PMCPLL_CTRL_PRE_SRC_WIDTH   3
#define CRP_PMCPLL_CTRL_PRE_SRC_MASK    0X00700000

#define CRP_PMCPLL_CTRL_CLKOUTDIV_SHIFT   16
#define CRP_PMCPLL_CTRL_CLKOUTDIV_WIDTH   2
#define CRP_PMCPLL_CTRL_CLKOUTDIV_MASK    0X00030000

#define CRP_PMCPLL_CTRL_FBDIV_SHIFT   8
#define CRP_PMCPLL_CTRL_FBDIV_WIDTH   8
#define CRP_PMCPLL_CTRL_FBDIV_MASK    0X0000FF00

#define CRP_PMCPLL_CTRL_BYPASS_SHIFT   3
#define CRP_PMCPLL_CTRL_BYPASS_WIDTH   1
#define CRP_PMCPLL_CTRL_BYPASS_MASK    0X00000008

#define CRP_PMCPLL_CTRL_RESET_SHIFT   0
#define CRP_PMCPLL_CTRL_RESET_WIDTH   1
#define CRP_PMCPLL_CTRL_RESET_MASK    0X00000001

/**
 * Register: CRP_PMCPLL_CFG
 */
#define CRP_PMCPLL_CFG    ( ( CRP_BASEADDR ) + 0X00000044 )

#define CRP_PMCPLL_CFG_LOCK_DLY_SHIFT   25
#define CRP_PMCPLL_CFG_LOCK_DLY_WIDTH   7
#define CRP_PMCPLL_CFG_LOCK_DLY_MASK    0XFE000000

#define CRP_PMCPLL_CFG_LOCK_CNT_SHIFT   13
#define CRP_PMCPLL_CFG_LOCK_CNT_WIDTH   10
#define CRP_PMCPLL_CFG_LOCK_CNT_MASK    0X007FE000

#define CRP_PMCPLL_CFG_LFHF_SHIFT   10
#define CRP_PMCPLL_CFG_LFHF_WIDTH   2
#define CRP_PMCPLL_CFG_LFHF_MASK    0X00000C00

#define CRP_PMCPLL_CFG_CP_SHIFT   5
#define CRP_PMCPLL_CFG_CP_WIDTH   4
#define CRP_PMCPLL_CFG_CP_MASK    0X000001E0

#define CRP_PMCPLL_CFG_RES_SHIFT   0
#define CRP_PMCPLL_CFG_RES_WIDTH   4
#define CRP_PMCPLL_CFG_RES_MASK    0X0000000F

/**
 * Register: CRP_PMCPLL_FRAC_CFG
 */
#define CRP_PMCPLL_FRAC_CFG    ( ( CRP_BASEADDR ) + 0X00000048 )

#define CRP_PMCPLL_FRAC_CFG_ENABLED_SHIFT   31
#define CRP_PMCPLL_FRAC_CFG_ENABLED_WIDTH   1
#define CRP_PMCPLL_FRAC_CFG_ENABLED_MASK    0X80000000

#define CRP_PMCPLL_FRAC_CFG_SEED_SHIFT   22
#define CRP_PMCPLL_FRAC_CFG_SEED_WIDTH   3
#define CRP_PMCPLL_FRAC_CFG_SEED_MASK    0X01C00000

#define CRP_PMCPLL_FRAC_CFG_ALGRTHM_SHIFT   19
#define CRP_PMCPLL_FRAC_CFG_ALGRTHM_WIDTH   1
#define CRP_PMCPLL_FRAC_CFG_ALGRTHM_MASK    0X00080000

#define CRP_PMCPLL_FRAC_CFG_ORDER_SHIFT   18
#define CRP_PMCPLL_FRAC_CFG_ORDER_WIDTH   1
#define CRP_PMCPLL_FRAC_CFG_ORDER_MASK    0X00040000

#define CRP_PMCPLL_FRAC_CFG_DATA_SHIFT   0
#define CRP_PMCPLL_FRAC_CFG_DATA_WIDTH   16
#define CRP_PMCPLL_FRAC_CFG_DATA_MASK    0X0000FFFF

/**
 * Register: CRP_NOCPLL_CTRL
 */
#define CRP_NOCPLL_CTRL    ( ( CRP_BASEADDR ) + 0X00000050 )

#define CRP_NOCPLL_CTRL_POST_SRC_SHIFT   24
#define CRP_NOCPLL_CTRL_POST_SRC_WIDTH   3
#define CRP_NOCPLL_CTRL_POST_SRC_MASK    0X07000000

#define CRP_NOCPLL_CTRL_PRE_SRC_SHIFT   20
#define CRP_NOCPLL_CTRL_PRE_SRC_WIDTH   3
#define CRP_NOCPLL_CTRL_PRE_SRC_MASK    0X00700000

#define CRP_NOCPLL_CTRL_CLKOUTDIV_SHIFT   16
#define CRP_NOCPLL_CTRL_CLKOUTDIV_WIDTH   2
#define CRP_NOCPLL_CTRL_CLKOUTDIV_MASK    0X00030000

#define CRP_NOCPLL_CTRL_FBDIV_SHIFT   8
#define CRP_NOCPLL_CTRL_FBDIV_WIDTH   8
#define CRP_NOCPLL_CTRL_FBDIV_MASK    0X0000FF00

#define CRP_NOCPLL_CTRL_BYPASS_SHIFT   3
#define CRP_NOCPLL_CTRL_BYPASS_WIDTH   1
#define CRP_NOCPLL_CTRL_BYPASS_MASK    0X00000008

#define CRP_NOCPLL_CTRL_RESET_SHIFT   0
#define CRP_NOCPLL_CTRL_RESET_WIDTH   1
#define CRP_NOCPLL_CTRL_RESET_MASK    0X00000001

/**
 * Register: CRP_NOCPLL_CFG
 */
#define CRP_NOCPLL_CFG    ( ( CRP_BASEADDR ) + 0X00000054 )

#define CRP_NOCPLL_CFG_LOCK_DLY_SHIFT   25
#define CRP_NOCPLL_CFG_LOCK_DLY_WIDTH   7
#define CRP_NOCPLL_CFG_LOCK_DLY_MASK    0XFE000000

#define CRP_NOCPLL_CFG_LOCK_CNT_SHIFT   13
#define CRP_NOCPLL_CFG_LOCK_CNT_WIDTH   10
#define CRP_NOCPLL_CFG_LOCK_CNT_MASK    0X007FE000

#define CRP_NOCPLL_CFG_LFHF_SHIFT   10
#define CRP_NOCPLL_CFG_LFHF_WIDTH   2
#define CRP_NOCPLL_CFG_LFHF_MASK    0X00000C00

#define CRP_NOCPLL_CFG_CP_SHIFT   5
#define CRP_NOCPLL_CFG_CP_WIDTH   4
#define CRP_NOCPLL_CFG_CP_MASK    0X000001E0

#define CRP_NOCPLL_CFG_RES_SHIFT   0
#define CRP_NOCPLL_CFG_RES_WIDTH   4
#define CRP_NOCPLL_CFG_RES_MASK    0X0000000F

/**
 * Register: CRP_NOCPLL_FRAC_CFG
 */
#define CRP_NOCPLL_FRAC_CFG    ( ( CRP_BASEADDR ) + 0X00000058 )

#define CRP_NOCPLL_FRAC_CFG_ENABLED_SHIFT   31
#define CRP_NOCPLL_FRAC_CFG_ENABLED_WIDTH   1
#define CRP_NOCPLL_FRAC_CFG_ENABLED_MASK    0X80000000

#define CRP_NOCPLL_FRAC_CFG_SEED_SHIFT   22
#define CRP_NOCPLL_FRAC_CFG_SEED_WIDTH   3
#define CRP_NOCPLL_FRAC_CFG_SEED_MASK    0X01C00000

#define CRP_NOCPLL_FRAC_CFG_ALGRTHM_SHIFT   19
#define CRP_NOCPLL_FRAC_CFG_ALGRTHM_WIDTH   1
#define CRP_NOCPLL_FRAC_CFG_ALGRTHM_MASK    0X00080000

#define CRP_NOCPLL_FRAC_CFG_ORDER_SHIFT   18
#define CRP_NOCPLL_FRAC_CFG_ORDER_WIDTH   1
#define CRP_NOCPLL_FRAC_CFG_ORDER_MASK    0X00040000

#define CRP_NOCPLL_FRAC_CFG_DATA_SHIFT   0
#define CRP_NOCPLL_FRAC_CFG_DATA_WIDTH   16
#define CRP_NOCPLL_FRAC_CFG_DATA_MASK    0X0000FFFF

/**
 * Register: CRP_PLL_STATUS
 */
#define CRP_PLL_STATUS    ( ( CRP_BASEADDR ) + 0X00000060 )

#define CRP_PLL_STATUS_NOCPLL_STABLE_SHIFT   3
#define CRP_PLL_STATUS_NOCPLL_STABLE_WIDTH   1
#define CRP_PLL_STATUS_NOCPLL_STABLE_MASK    0X00000008

#define CRP_PLL_STATUS_PMCPLL_STABLE_SHIFT   2
#define CRP_PLL_STATUS_PMCPLL_STABLE_WIDTH   1
#define CRP_PLL_STATUS_PMCPLL_STABLE_MASK    0X00000004

#define CRP_PLL_STATUS_NOCPLL_LOCK_SHIFT   1
#define CRP_PLL_STATUS_NOCPLL_LOCK_WIDTH   1
#define CRP_PLL_STATUS_NOCPLL_LOCK_MASK    0X00000002

#define CRP_PLL_STATUS_PMCPLL_LOCK_SHIFT   0
#define CRP_PLL_STATUS_PMCPLL_LOCK_WIDTH   1
#define CRP_PLL_STATUS_PMCPLL_LOCK_MASK    0X00000001

/**
 * Register: CRP_PPLL_REG0
 */
#define CRP_PPLL_REG0    ( ( CRP_BASEADDR ) + 0X0000006C )

#define CRP_PPLL_REG0_FREQ_COMP_SHIFT   22
#define CRP_PPLL_REG0_FREQ_COMP_WIDTH   3
#define CRP_PPLL_REG0_FREQ_COMP_MASK    0X01C00000

#define CRP_PPLL_REG0_LOCK_SAT_HIGH_SHIFT   12
#define CRP_PPLL_REG0_LOCK_SAT_HIGH_WIDTH   10
#define CRP_PPLL_REG0_LOCK_SAT_HIGH_MASK    0X003FF000

#define CRP_PPLL_REG0_UNLOCK_CNT_SHIFT   2
#define CRP_PPLL_REG0_UNLOCK_CNT_WIDTH   10
#define CRP_PPLL_REG0_UNLOCK_CNT_MASK    0X00000FFC

/**
 * Register: CRP_PPLL_REG1
 */
#define CRP_PPLL_REG1    ( ( CRP_BASEADDR ) + 0X00000070 )

#define CRP_PPLL_REG1_EN_VCO_DIV1_SHIFT   29
#define CRP_PPLL_REG1_EN_VCO_DIV1_WIDTH   1
#define CRP_PPLL_REG1_EN_VCO_DIV1_MASK    0X20000000

#define CRP_PPLL_REG1_EN_VCO_DIV6_SHIFT   28
#define CRP_PPLL_REG1_EN_VCO_DIV6_WIDTH   1
#define CRP_PPLL_REG1_EN_VCO_DIV6_MASK    0X10000000

#define CRP_PPLL_REG1_EN_SYNC_CK_TEST_SHIFT   27
#define CRP_PPLL_REG1_EN_SYNC_CK_TEST_WIDTH   1
#define CRP_PPLL_REG1_EN_SYNC_CK_TEST_MASK    0X08000000

#define CRP_PPLL_REG1_VCO_STARTUP_HYST_DISABLE_SHIFT   25
#define CRP_PPLL_REG1_VCO_STARTUP_HYST_DISABLE_WIDTH   1
#define CRP_PPLL_REG1_VCO_STARTUP_HYST_DISABLE_MASK    0X02000000

#define CRP_PPLL_REG1_VCO_STARTUP_ALT_EN_SHIFT   24
#define CRP_PPLL_REG1_VCO_STARTUP_ALT_EN_WIDTH   1
#define CRP_PPLL_REG1_VCO_STARTUP_ALT_EN_MASK    0X01000000

#define CRP_PPLL_REG1_VCO_STARTUP_ADJ_SHIFT   23
#define CRP_PPLL_REG1_VCO_STARTUP_ADJ_WIDTH   1
#define CRP_PPLL_REG1_VCO_STARTUP_ADJ_MASK    0X00800000

#define CRP_PPLL_REG1_VCO_KICK_DISABLE_SHIFT   22
#define CRP_PPLL_REG1_VCO_KICK_DISABLE_WIDTH   1
#define CRP_PPLL_REG1_VCO_KICK_DISABLE_MASK    0X00400000

#define CRP_PPLL_REG1_VCO_GATE_CCI_B_SHIFT   21
#define CRP_PPLL_REG1_VCO_GATE_CCI_B_WIDTH   1
#define CRP_PPLL_REG1_VCO_GATE_CCI_B_MASK    0X00200000

#define CRP_PPLL_REG1_VCO_HIGH_RANGE_EN_SHIFT   20
#define CRP_PPLL_REG1_VCO_HIGH_RANGE_EN_WIDTH   1
#define CRP_PPLL_REG1_VCO_HIGH_RANGE_EN_MASK    0X00100000

#define CRP_PPLL_REG1_PFD_STARTUP_SHIFT   19
#define CRP_PPLL_REG1_PFD_STARTUP_WIDTH   1
#define CRP_PPLL_REG1_PFD_STARTUP_MASK    0X00080000

#define CRP_PPLL_REG1_PFD_SHIFT   12
#define CRP_PPLL_REG1_PFD_WIDTH   7
#define CRP_PPLL_REG1_PFD_MASK    0X0007F000

#define CRP_PPLL_REG1_SEL_SLIPD_SHIFT   11
#define CRP_PPLL_REG1_SEL_SLIPD_WIDTH   1
#define CRP_PPLL_REG1_SEL_SLIPD_MASK    0X00000800

#define CRP_PPLL_REG1_SENSE_TEST_EN_SHIFT   10
#define CRP_PPLL_REG1_SENSE_TEST_EN_WIDTH   1
#define CRP_PPLL_REG1_SENSE_TEST_EN_MASK    0X00000400

#define CRP_PPLL_REG1_SPARE_ANALOG_SHIFT   5
#define CRP_PPLL_REG1_SPARE_ANALOG_WIDTH   5
#define CRP_PPLL_REG1_SPARE_ANALOG_MASK    0X000003E0

#define CRP_PPLL_REG1_SPARE_DIGITAL_SHIFT   0
#define CRP_PPLL_REG1_SPARE_DIGITAL_WIDTH   5
#define CRP_PPLL_REG1_SPARE_DIGITAL_MASK    0X0000001F

/**
 * Register: CRP_PPLL_REG2
 */
#define CRP_PPLL_REG2    ( ( CRP_BASEADDR ) + 0X00000074 )

#define CRP_PPLL_REG2_SUP_SEL_VCCINT_SHIFT   28
#define CRP_PPLL_REG2_SUP_SEL_VCCINT_WIDTH   1
#define CRP_PPLL_REG2_SUP_SEL_VCCINT_MASK    0X10000000

#define CRP_PPLL_REG2_SUP_SEL_VCCAUX_SHIFT   27
#define CRP_PPLL_REG2_SUP_SEL_VCCAUX_WIDTH   1
#define CRP_PPLL_REG2_SUP_SEL_VCCAUX_MASK    0X08000000

#define CRP_PPLL_REG2_SUP_SEL_VBG_SHIFT   26
#define CRP_PPLL_REG2_SUP_SEL_VBG_WIDTH   1
#define CRP_PPLL_REG2_SUP_SEL_VBG_MASK    0X04000000

#define CRP_PPLL_REG2_SUP_SEL_AVDD_SHIFT   25
#define CRP_PPLL_REG2_SUP_SEL_AVDD_WIDTH   1
#define CRP_PPLL_REG2_SUP_SEL_AVDD_MASK    0X02000000

#define CRP_PPLL_REG2_SUP_SEL_VBGHALF_SHIFT   24
#define CRP_PPLL_REG2_SUP_SEL_VBGHALF_WIDTH   1
#define CRP_PPLL_REG2_SUP_SEL_VBGHALF_MASK    0X01000000

#define CRP_PPLL_REG2_VLF_HIGH_SEL_SHIFT   18
#define CRP_PPLL_REG2_VLF_HIGH_SEL_WIDTH   2
#define CRP_PPLL_REG2_VLF_HIGH_SEL_MASK    0X000C0000

#define CRP_PPLL_REG2_VLF_VALID_SEL_SHIFT   15
#define CRP_PPLL_REG2_VLF_VALID_SEL_WIDTH   3
#define CRP_PPLL_REG2_VLF_VALID_SEL_MASK    0X00038000

#define CRP_PPLL_REG2_VLF_VALID_PWDN_SHIFT   14
#define CRP_PPLL_REG2_VLF_VALID_PWDN_WIDTH   1
#define CRP_PPLL_REG2_VLF_VALID_PWDN_MASK    0X00004000

#define CRP_PPLL_REG2_VLF_HIGH_PWDN_B_SHIFT   13
#define CRP_PPLL_REG2_VLF_HIGH_PWDN_B_WIDTH   1
#define CRP_PPLL_REG2_VLF_HIGH_PWDN_B_MASK    0X00002000

#define CRP_PPLL_REG2_LF_LOW_SEL_SHIFT   12
#define CRP_PPLL_REG2_LF_LOW_SEL_WIDTH   1
#define CRP_PPLL_REG2_LF_LOW_SEL_MASK    0X00001000

#define CRP_PPLL_REG2_LF_NEN_SHIFT   10
#define CRP_PPLL_REG2_LF_NEN_WIDTH   2
#define CRP_PPLL_REG2_LF_NEN_MASK    0X00000C00

#define CRP_PPLL_REG2_LF_PEN_SHIFT   8
#define CRP_PPLL_REG2_LF_PEN_WIDTH   2
#define CRP_PPLL_REG2_LF_PEN_MASK    0X00000300

#define CRP_PPLL_REG2_MAN_LF_SHIFT   4
#define CRP_PPLL_REG2_MAN_LF_WIDTH   3
#define CRP_PPLL_REG2_MAN_LF_MASK    0X00000070

#define CRP_PPLL_REG2_ANALOG_MISC_SHIFT   0
#define CRP_PPLL_REG2_ANALOG_MISC_WIDTH   4
#define CRP_PPLL_REG2_ANALOG_MISC_MASK    0X0000000F

/**
 * Register: CRP_PPLL_REG3
 */
#define CRP_PPLL_REG3    ( ( CRP_BASEADDR ) + 0X00000078 )

#define CRP_PPLL_REG3_REGLPF_RES_SHORT_SHIFT   24
#define CRP_PPLL_REG3_REGLPF_RES_SHORT_WIDTH   1
#define CRP_PPLL_REG3_REGLPF_RES_SHORT_MASK    0X01000000

#define CRP_PPLL_REG3_CP_RES_L_SHIFT   22
#define CRP_PPLL_REG3_CP_RES_L_WIDTH   2
#define CRP_PPLL_REG3_CP_RES_L_MASK    0X00C00000

#define CRP_PPLL_REG3_CP_RES_H_SHIFT   20
#define CRP_PPLL_REG3_CP_RES_H_WIDTH   2
#define CRP_PPLL_REG3_CP_RES_H_MASK    0X00300000

#define CRP_PPLL_REG3_CP_OPAMP_BN_SHIFT   19
#define CRP_PPLL_REG3_CP_OPAMP_BN_WIDTH   1
#define CRP_PPLL_REG3_CP_OPAMP_BN_MASK    0X00080000

#define CRP_PPLL_REG3_CP_BIAS_TRIP_SET_SHIFT   18
#define CRP_PPLL_REG3_CP_BIAS_TRIP_SET_WIDTH   1
#define CRP_PPLL_REG3_CP_BIAS_TRIP_SET_MASK    0X00040000

#define CRP_PPLL_REG3_HVLF_CNT_TEST_EN_SHIFT   17
#define CRP_PPLL_REG3_HVLF_CNT_TEST_EN_WIDTH   1
#define CRP_PPLL_REG3_HVLF_CNT_TEST_EN_MASK    0X00020000

#define CRP_PPLL_REG3_HVLF_CNT_TEST_SHIFT   11
#define CRP_PPLL_REG3_HVLF_CNT_TEST_WIDTH   6
#define CRP_PPLL_REG3_HVLF_CNT_TEST_MASK    0X0001F800

#define CRP_PPLL_REG3_AVDD_COMP_SET_SHIFT   8
#define CRP_PPLL_REG3_AVDD_COMP_SET_WIDTH   3
#define CRP_PPLL_REG3_AVDD_COMP_SET_MASK    0X00000700

#define CRP_PPLL_REG3_AVDD_VBG_PD_SHIFT   5
#define CRP_PPLL_REG3_AVDD_VBG_PD_WIDTH   3
#define CRP_PPLL_REG3_AVDD_VBG_PD_MASK    0X000000E0

#define CRP_PPLL_REG3_AVDD_VBG_SEL_SHIFT   0
#define CRP_PPLL_REG3_AVDD_VBG_SEL_WIDTH   5
#define CRP_PPLL_REG3_AVDD_VBG_SEL_MASK    0X0000001F

/**
 * Register: CRP_PPLL_REG4
 */
#define CRP_PPLL_REG4    ( ( CRP_BASEADDR ) + 0X0000007C )

#define CRP_PPLL_REG4_FORCE_SENSE_SHORT_SHIFT   29
#define CRP_PPLL_REG4_FORCE_SENSE_SHORT_WIDTH   1
#define CRP_PPLL_REG4_FORCE_SENSE_SHORT_MASK    0X20000000

#define CRP_PPLL_REG4_FRACT_TEST_SEL_SHIFT   26
#define CRP_PPLL_REG4_FRACT_TEST_SEL_WIDTH   3
#define CRP_PPLL_REG4_FRACT_TEST_SEL_MASK    0X1C000000

#define CRP_PPLL_REG4_FRACT_TEST_EN_SHIFT   25
#define CRP_PPLL_REG4_FRACT_TEST_EN_WIDTH   1
#define CRP_PPLL_REG4_FRACT_TEST_EN_MASK    0X02000000

#define CRP_PPLL_REG4_TC_GEN_MODE_SHIFT   24
#define CRP_PPLL_REG4_TC_GEN_MODE_WIDTH   1
#define CRP_PPLL_REG4_TC_GEN_MODE_MASK    0X01000000

#define CRP_PPLL_REG4_TESTOUT3_MUX_SEL_SHIFT   18
#define CRP_PPLL_REG4_TESTOUT3_MUX_SEL_WIDTH   6
#define CRP_PPLL_REG4_TESTOUT3_MUX_SEL_MASK    0X00FC0000

#define CRP_PPLL_REG4_TESTOUT2_MUX_SEL_SHIFT   12
#define CRP_PPLL_REG4_TESTOUT2_MUX_SEL_WIDTH   6
#define CRP_PPLL_REG4_TESTOUT2_MUX_SEL_MASK    0X0003F000

#define CRP_PPLL_REG4_TESTOUT1_MUX_SEL_SHIFT   6
#define CRP_PPLL_REG4_TESTOUT1_MUX_SEL_WIDTH   6
#define CRP_PPLL_REG4_TESTOUT1_MUX_SEL_MASK    0X00000FC0

#define CRP_PPLL_REG4_TESTOUT0_MUX_SEL_SHIFT   0
#define CRP_PPLL_REG4_TESTOUT0_MUX_SEL_WIDTH   6
#define CRP_PPLL_REG4_TESTOUT0_MUX_SEL_MASK    0X0000003F

/**
 * Register: CRP_PPLL_REG5
 */
#define CRP_PPLL_REG5    ( ( CRP_BASEADDR ) + 0X00000080 )

#define CRP_PPLL_REG5_VLF_SWITCH_SEL_SHIFT   9
#define CRP_PPLL_REG5_VLF_SWITCH_SEL_WIDTH   3
#define CRP_PPLL_REG5_VLF_SWITCH_SEL_MASK    0X00000E00

#define CRP_PPLL_REG5_VCO_SINGLE_BAND_DEFAULT_SHIFT   8
#define CRP_PPLL_REG5_VCO_SINGLE_BAND_DEFAULT_WIDTH   1
#define CRP_PPLL_REG5_VCO_SINGLE_BAND_DEFAULT_MASK    0X00000100

#define CRP_PPLL_REG5_VCO_BAND_MODE_SHIFT   7
#define CRP_PPLL_REG5_VCO_BAND_MODE_WIDTH   1
#define CRP_PPLL_REG5_VCO_BAND_MODE_MASK    0X00000080

#define CRP_PPLL_REG5_VLF_HIGH_EN_SHIFT   6
#define CRP_PPLL_REG5_VLF_HIGH_EN_WIDTH   1
#define CRP_PPLL_REG5_VLF_HIGH_EN_MASK    0X00000040

#define CRP_PPLL_REG5_VLF_SWITCH_PWDN_SHIFT   5
#define CRP_PPLL_REG5_VLF_SWITCH_PWDN_WIDTH   1
#define CRP_PPLL_REG5_VLF_SWITCH_PWDN_MASK    0X00000020

#define CRP_PPLL_REG5_TEST_PLL_CK_SEL_SHIFT   2
#define CRP_PPLL_REG5_TEST_PLL_CK_SEL_WIDTH   3
#define CRP_PPLL_REG5_TEST_PLL_CK_SEL_MASK    0X0000001C

#define CRP_PPLL_REG5_FRACT_TEST_CK_SEL_SHIFT   1
#define CRP_PPLL_REG5_FRACT_TEST_CK_SEL_WIDTH   1
#define CRP_PPLL_REG5_FRACT_TEST_CK_SEL_MASK    0X00000002

#define CRP_PPLL_REG5_FBCLK_PREDIV2_SHIFT   0
#define CRP_PPLL_REG5_FBCLK_PREDIV2_WIDTH   1
#define CRP_PPLL_REG5_FBCLK_PREDIV2_MASK    0X00000001

/**
 * Register: CRP_PPLL_REG6
 */
#define CRP_PPLL_REG6    ( ( CRP_BASEADDR ) + 0X00000084 )

#define CRP_PPLL_REG6_CONTROL_1_SHIFT   16
#define CRP_PPLL_REG6_CONTROL_1_WIDTH   16
#define CRP_PPLL_REG6_CONTROL_1_MASK    0XFFFF0000

#define CRP_PPLL_REG6_CONTROL_0_SHIFT   0
#define CRP_PPLL_REG6_CONTROL_0_WIDTH   16
#define CRP_PPLL_REG6_CONTROL_0_MASK    0X0000FFFF

/**
 * Register: CRP_PPLL_REG7
 */
#define CRP_PPLL_REG7    ( ( CRP_BASEADDR ) + 0X00000088 )

#define CRP_PPLL_REG7_CONTROL_3_SHIFT   16
#define CRP_PPLL_REG7_CONTROL_3_WIDTH   16
#define CRP_PPLL_REG7_CONTROL_3_MASK    0XFFFF0000

#define CRP_PPLL_REG7_CONTROL_2_SHIFT   0
#define CRP_PPLL_REG7_CONTROL_2_WIDTH   16
#define CRP_PPLL_REG7_CONTROL_2_MASK    0X0000FFFF

/**
 * Register: CRP_PPLL_REG8
 */
#define CRP_PPLL_REG8    ( ( CRP_BASEADDR ) + 0X00000090 )

#define CRP_PPLL_REG8_CONTROL_5_SHIFT   16
#define CRP_PPLL_REG8_CONTROL_5_WIDTH   16
#define CRP_PPLL_REG8_CONTROL_5_MASK    0XFFFF0000

#define CRP_PPLL_REG8_CONTROL_4_SHIFT   0
#define CRP_PPLL_REG8_CONTROL_4_WIDTH   16
#define CRP_PPLL_REG8_CONTROL_4_MASK    0X0000FFFF

/**
 * Register: CRP_PPLL_REG9
 */
#define CRP_PPLL_REG9    ( ( CRP_BASEADDR ) + 0X00000094 )

#define CRP_PPLL_REG9_CONTROL_7_SHIFT   16
#define CRP_PPLL_REG9_CONTROL_7_WIDTH   16
#define CRP_PPLL_REG9_CONTROL_7_MASK    0XFFFF0000

#define CRP_PPLL_REG9_CONTROL_6_SHIFT   0
#define CRP_PPLL_REG9_CONTROL_6_WIDTH   16
#define CRP_PPLL_REG9_CONTROL_6_MASK    0X0000FFFF

/**
 * Register: CRP_NPLL_REG0
 */
#define CRP_NPLL_REG0    ( ( CRP_BASEADDR ) + 0X0000009C )

#define CRP_NPLL_REG0_FREQ_COMP_SHIFT   22
#define CRP_NPLL_REG0_FREQ_COMP_WIDTH   3
#define CRP_NPLL_REG0_FREQ_COMP_MASK    0X01C00000

#define CRP_NPLL_REG0_LOCK_SAT_HIGH_SHIFT   12
#define CRP_NPLL_REG0_LOCK_SAT_HIGH_WIDTH   10
#define CRP_NPLL_REG0_LOCK_SAT_HIGH_MASK    0X003FF000

#define CRP_NPLL_REG0_UNLOCK_CNT_SHIFT   2
#define CRP_NPLL_REG0_UNLOCK_CNT_WIDTH   10
#define CRP_NPLL_REG0_UNLOCK_CNT_MASK    0X00000FFC

/**
 * Register: CRP_NPLL_REG1
 */
#define CRP_NPLL_REG1    ( ( CRP_BASEADDR ) + 0X000000A0 )

#define CRP_NPLL_REG1_EN_VCO_DIV1_SHIFT   29
#define CRP_NPLL_REG1_EN_VCO_DIV1_WIDTH   1
#define CRP_NPLL_REG1_EN_VCO_DIV1_MASK    0X20000000

#define CRP_NPLL_REG1_EN_VCO_DIV6_SHIFT   28
#define CRP_NPLL_REG1_EN_VCO_DIV6_WIDTH   1
#define CRP_NPLL_REG1_EN_VCO_DIV6_MASK    0X10000000

#define CRP_NPLL_REG1_EN_SYNC_CK_TEST_SHIFT   27
#define CRP_NPLL_REG1_EN_SYNC_CK_TEST_WIDTH   1
#define CRP_NPLL_REG1_EN_SYNC_CK_TEST_MASK    0X08000000

#define CRP_NPLL_REG1_VCO_STARTUP_HYST_DISABLE_SHIFT   25
#define CRP_NPLL_REG1_VCO_STARTUP_HYST_DISABLE_WIDTH   1
#define CRP_NPLL_REG1_VCO_STARTUP_HYST_DISABLE_MASK    0X02000000

#define CRP_NPLL_REG1_VCO_STARTUP_ALT_EN_SHIFT   24
#define CRP_NPLL_REG1_VCO_STARTUP_ALT_EN_WIDTH   1
#define CRP_NPLL_REG1_VCO_STARTUP_ALT_EN_MASK    0X01000000

#define CRP_NPLL_REG1_VCO_STARTUP_ADJ_SHIFT   23
#define CRP_NPLL_REG1_VCO_STARTUP_ADJ_WIDTH   1
#define CRP_NPLL_REG1_VCO_STARTUP_ADJ_MASK    0X00800000

#define CRP_NPLL_REG1_VCO_KICK_DISABLE_SHIFT   22
#define CRP_NPLL_REG1_VCO_KICK_DISABLE_WIDTH   1
#define CRP_NPLL_REG1_VCO_KICK_DISABLE_MASK    0X00400000

#define CRP_NPLL_REG1_VCO_GATE_CCI_B_SHIFT   21
#define CRP_NPLL_REG1_VCO_GATE_CCI_B_WIDTH   1
#define CRP_NPLL_REG1_VCO_GATE_CCI_B_MASK    0X00200000

#define CRP_NPLL_REG1_VCO_HIGH_RANGE_EN_SHIFT   20
#define CRP_NPLL_REG1_VCO_HIGH_RANGE_EN_WIDTH   1
#define CRP_NPLL_REG1_VCO_HIGH_RANGE_EN_MASK    0X00100000

#define CRP_NPLL_REG1_PFD_STARTUP_SHIFT   19
#define CRP_NPLL_REG1_PFD_STARTUP_WIDTH   1
#define CRP_NPLL_REG1_PFD_STARTUP_MASK    0X00080000

#define CRP_NPLL_REG1_PFD_SHIFT   12
#define CRP_NPLL_REG1_PFD_WIDTH   7
#define CRP_NPLL_REG1_PFD_MASK    0X0007F000

#define CRP_NPLL_REG1_SEL_SLIPD_SHIFT   11
#define CRP_NPLL_REG1_SEL_SLIPD_WIDTH   1
#define CRP_NPLL_REG1_SEL_SLIPD_MASK    0X00000800

#define CRP_NPLL_REG1_SENSE_TEST_EN_SHIFT   10
#define CRP_NPLL_REG1_SENSE_TEST_EN_WIDTH   1
#define CRP_NPLL_REG1_SENSE_TEST_EN_MASK    0X00000400

#define CRP_NPLL_REG1_SPARE_ANALOG_SHIFT   5
#define CRP_NPLL_REG1_SPARE_ANALOG_WIDTH   5
#define CRP_NPLL_REG1_SPARE_ANALOG_MASK    0X000003E0

#define CRP_NPLL_REG1_SPARE_DIGITAL_SHIFT   0
#define CRP_NPLL_REG1_SPARE_DIGITAL_WIDTH   5
#define CRP_NPLL_REG1_SPARE_DIGITAL_MASK    0X0000001F

/**
 * Register: CRP_NPLL_REG2
 */
#define CRP_NPLL_REG2    ( ( CRP_BASEADDR ) + 0X000000A4 )

#define CRP_NPLL_REG2_SUP_SEL_VCCINT_SHIFT   28
#define CRP_NPLL_REG2_SUP_SEL_VCCINT_WIDTH   1
#define CRP_NPLL_REG2_SUP_SEL_VCCINT_MASK    0X10000000

#define CRP_NPLL_REG2_SUP_SEL_VCCAUX_SHIFT   27
#define CRP_NPLL_REG2_SUP_SEL_VCCAUX_WIDTH   1
#define CRP_NPLL_REG2_SUP_SEL_VCCAUX_MASK    0X08000000

#define CRP_NPLL_REG2_SUP_SEL_VBG_SHIFT   26
#define CRP_NPLL_REG2_SUP_SEL_VBG_WIDTH   1
#define CRP_NPLL_REG2_SUP_SEL_VBG_MASK    0X04000000

#define CRP_NPLL_REG2_SUP_SEL_AVDD_SHIFT   25
#define CRP_NPLL_REG2_SUP_SEL_AVDD_WIDTH   1
#define CRP_NPLL_REG2_SUP_SEL_AVDD_MASK    0X02000000

#define CRP_NPLL_REG2_SUP_SEL_VBGHALF_SHIFT   24
#define CRP_NPLL_REG2_SUP_SEL_VBGHALF_WIDTH   1
#define CRP_NPLL_REG2_SUP_SEL_VBGHALF_MASK    0X01000000

#define CRP_NPLL_REG2_VLF_HIGH_SEL_SHIFT   18
#define CRP_NPLL_REG2_VLF_HIGH_SEL_WIDTH   2
#define CRP_NPLL_REG2_VLF_HIGH_SEL_MASK    0X000C0000

#define CRP_NPLL_REG2_VLF_VALID_SEL_SHIFT   15
#define CRP_NPLL_REG2_VLF_VALID_SEL_WIDTH   3
#define CRP_NPLL_REG2_VLF_VALID_SEL_MASK    0X00038000

#define CRP_NPLL_REG2_VLF_VALID_PWDN_SHIFT   14
#define CRP_NPLL_REG2_VLF_VALID_PWDN_WIDTH   1
#define CRP_NPLL_REG2_VLF_VALID_PWDN_MASK    0X00004000

#define CRP_NPLL_REG2_VLF_HIGH_PWDN_B_SHIFT   13
#define CRP_NPLL_REG2_VLF_HIGH_PWDN_B_WIDTH   1
#define CRP_NPLL_REG2_VLF_HIGH_PWDN_B_MASK    0X00002000

#define CRP_NPLL_REG2_LF_LOW_SEL_SHIFT   12
#define CRP_NPLL_REG2_LF_LOW_SEL_WIDTH   1
#define CRP_NPLL_REG2_LF_LOW_SEL_MASK    0X00001000

#define CRP_NPLL_REG2_LF_NEN_SHIFT   10
#define CRP_NPLL_REG2_LF_NEN_WIDTH   2
#define CRP_NPLL_REG2_LF_NEN_MASK    0X00000C00

#define CRP_NPLL_REG2_LF_PEN_SHIFT   8
#define CRP_NPLL_REG2_LF_PEN_WIDTH   2
#define CRP_NPLL_REG2_LF_PEN_MASK    0X00000300

#define CRP_NPLL_REG2_MAN_LF_SHIFT   4
#define CRP_NPLL_REG2_MAN_LF_WIDTH   3
#define CRP_NPLL_REG2_MAN_LF_MASK    0X00000070

#define CRP_NPLL_REG2_ANALOG_MISC_SHIFT   0
#define CRP_NPLL_REG2_ANALOG_MISC_WIDTH   4
#define CRP_NPLL_REG2_ANALOG_MISC_MASK    0X0000000F

/**
 * Register: CRP_NPLL_REG3
 */
#define CRP_NPLL_REG3    ( ( CRP_BASEADDR ) + 0X000000A8 )

#define CRP_NPLL_REG3_REGLPF_RES_SHORT_SHIFT   24
#define CRP_NPLL_REG3_REGLPF_RES_SHORT_WIDTH   1
#define CRP_NPLL_REG3_REGLPF_RES_SHORT_MASK    0X01000000

#define CRP_NPLL_REG3_CP_RES_L_SHIFT   22
#define CRP_NPLL_REG3_CP_RES_L_WIDTH   2
#define CRP_NPLL_REG3_CP_RES_L_MASK    0X00C00000

#define CRP_NPLL_REG3_CP_RES_H_SHIFT   20
#define CRP_NPLL_REG3_CP_RES_H_WIDTH   2
#define CRP_NPLL_REG3_CP_RES_H_MASK    0X00300000

#define CRP_NPLL_REG3_CP_OPAMP_BN_SHIFT   19
#define CRP_NPLL_REG3_CP_OPAMP_BN_WIDTH   1
#define CRP_NPLL_REG3_CP_OPAMP_BN_MASK    0X00080000

#define CRP_NPLL_REG3_CP_BIAS_TRIP_SET_SHIFT   18
#define CRP_NPLL_REG3_CP_BIAS_TRIP_SET_WIDTH   1
#define CRP_NPLL_REG3_CP_BIAS_TRIP_SET_MASK    0X00040000

#define CRP_NPLL_REG3_HVLF_CNT_TEST_EN_SHIFT   17
#define CRP_NPLL_REG3_HVLF_CNT_TEST_EN_WIDTH   1
#define CRP_NPLL_REG3_HVLF_CNT_TEST_EN_MASK    0X00020000

#define CRP_NPLL_REG3_HVLF_CNT_TEST_SHIFT   11
#define CRP_NPLL_REG3_HVLF_CNT_TEST_WIDTH   6
#define CRP_NPLL_REG3_HVLF_CNT_TEST_MASK    0X0001F800

#define CRP_NPLL_REG3_AVDD_COMP_SET_SHIFT   8
#define CRP_NPLL_REG3_AVDD_COMP_SET_WIDTH   3
#define CRP_NPLL_REG3_AVDD_COMP_SET_MASK    0X00000700

#define CRP_NPLL_REG3_AVDD_VBG_PD_SHIFT   5
#define CRP_NPLL_REG3_AVDD_VBG_PD_WIDTH   3
#define CRP_NPLL_REG3_AVDD_VBG_PD_MASK    0X000000E0

#define CRP_NPLL_REG3_AVDD_VBG_SEL_SHIFT   0
#define CRP_NPLL_REG3_AVDD_VBG_SEL_WIDTH   5
#define CRP_NPLL_REG3_AVDD_VBG_SEL_MASK    0X0000001F

/**
 * Register: CRP_NPLL_REG4
 */
#define CRP_NPLL_REG4    ( ( CRP_BASEADDR ) + 0X000000AC )

#define CRP_NPLL_REG4_FORCE_SENSE_SHORT_SHIFT   29
#define CRP_NPLL_REG4_FORCE_SENSE_SHORT_WIDTH   1
#define CRP_NPLL_REG4_FORCE_SENSE_SHORT_MASK    0X20000000

#define CRP_NPLL_REG4_FRACT_TEST_SEL_SHIFT   26
#define CRP_NPLL_REG4_FRACT_TEST_SEL_WIDTH   3
#define CRP_NPLL_REG4_FRACT_TEST_SEL_MASK    0X1C000000

#define CRP_NPLL_REG4_FRACT_TEST_EN_SHIFT   25
#define CRP_NPLL_REG4_FRACT_TEST_EN_WIDTH   1
#define CRP_NPLL_REG4_FRACT_TEST_EN_MASK    0X02000000

#define CRP_NPLL_REG4_TC_GEN_MODE_SHIFT   24
#define CRP_NPLL_REG4_TC_GEN_MODE_WIDTH   1
#define CRP_NPLL_REG4_TC_GEN_MODE_MASK    0X01000000

#define CRP_NPLL_REG4_TESTOUT3_MUX_SEL_SHIFT   18
#define CRP_NPLL_REG4_TESTOUT3_MUX_SEL_WIDTH   6
#define CRP_NPLL_REG4_TESTOUT3_MUX_SEL_MASK    0X00FC0000

#define CRP_NPLL_REG4_TESTOUT2_MUX_SEL_SHIFT   12
#define CRP_NPLL_REG4_TESTOUT2_MUX_SEL_WIDTH   6
#define CRP_NPLL_REG4_TESTOUT2_MUX_SEL_MASK    0X0003F000

#define CRP_NPLL_REG4_TESTOUT1_MUX_SEL_SHIFT   6
#define CRP_NPLL_REG4_TESTOUT1_MUX_SEL_WIDTH   6
#define CRP_NPLL_REG4_TESTOUT1_MUX_SEL_MASK    0X00000FC0

#define CRP_NPLL_REG4_TESTOUT0_MUX_SEL_SHIFT   0
#define CRP_NPLL_REG4_TESTOUT0_MUX_SEL_WIDTH   6
#define CRP_NPLL_REG4_TESTOUT0_MUX_SEL_MASK    0X0000003F

/**
 * Register: CRP_NPLL_REG5
 */
#define CRP_NPLL_REG5    ( ( CRP_BASEADDR ) + 0X000000B0 )

#define CRP_NPLL_REG5_VLF_SWITCH_SEL_SHIFT   9
#define CRP_NPLL_REG5_VLF_SWITCH_SEL_WIDTH   3
#define CRP_NPLL_REG5_VLF_SWITCH_SEL_MASK    0X00000E00

#define CRP_NPLL_REG5_VCO_SINGLE_BAND_DEFAULT_SHIFT   8
#define CRP_NPLL_REG5_VCO_SINGLE_BAND_DEFAULT_WIDTH   1
#define CRP_NPLL_REG5_VCO_SINGLE_BAND_DEFAULT_MASK    0X00000100

#define CRP_NPLL_REG5_VCO_BAND_MODE_SHIFT   7
#define CRP_NPLL_REG5_VCO_BAND_MODE_WIDTH   1
#define CRP_NPLL_REG5_VCO_BAND_MODE_MASK    0X00000080

#define CRP_NPLL_REG5_VLF_HIGH_EN_SHIFT   6
#define CRP_NPLL_REG5_VLF_HIGH_EN_WIDTH   1
#define CRP_NPLL_REG5_VLF_HIGH_EN_MASK    0X00000040

#define CRP_NPLL_REG5_VLF_SWITCH_PWDN_SHIFT   5
#define CRP_NPLL_REG5_VLF_SWITCH_PWDN_WIDTH   1
#define CRP_NPLL_REG5_VLF_SWITCH_PWDN_MASK    0X00000020

#define CRP_NPLL_REG5_TEST_PLL_CK_SEL_SHIFT   2
#define CRP_NPLL_REG5_TEST_PLL_CK_SEL_WIDTH   3
#define CRP_NPLL_REG5_TEST_PLL_CK_SEL_MASK    0X0000001C

#define CRP_NPLL_REG5_FRACT_TEST_CK_SEL_SHIFT   1
#define CRP_NPLL_REG5_FRACT_TEST_CK_SEL_WIDTH   1
#define CRP_NPLL_REG5_FRACT_TEST_CK_SEL_MASK    0X00000002

#define CRP_NPLL_REG5_FBCLK_PREDIV2_SHIFT   0
#define CRP_NPLL_REG5_FBCLK_PREDIV2_WIDTH   1
#define CRP_NPLL_REG5_FBCLK_PREDIV2_MASK    0X00000001

/**
 * Register: CRP_NPLL_REG6
 */
#define CRP_NPLL_REG6    ( ( CRP_BASEADDR ) + 0X000000B4 )

#define CRP_NPLL_REG6_CONTROL_1_SHIFT   16
#define CRP_NPLL_REG6_CONTROL_1_WIDTH   16
#define CRP_NPLL_REG6_CONTROL_1_MASK    0XFFFF0000

#define CRP_NPLL_REG6_CONTROL_0_SHIFT   0
#define CRP_NPLL_REG6_CONTROL_0_WIDTH   16
#define CRP_NPLL_REG6_CONTROL_0_MASK    0X0000FFFF

/**
 * Register: CRP_NPLL_REG7
 */
#define CRP_NPLL_REG7    ( ( CRP_BASEADDR ) + 0X000000B8 )

#define CRP_NPLL_REG7_CONTROL_3_SHIFT   16
#define CRP_NPLL_REG7_CONTROL_3_WIDTH   16
#define CRP_NPLL_REG7_CONTROL_3_MASK    0XFFFF0000

#define CRP_NPLL_REG7_CONTROL_2_SHIFT   0
#define CRP_NPLL_REG7_CONTROL_2_WIDTH   16
#define CRP_NPLL_REG7_CONTROL_2_MASK    0X0000FFFF

/**
 * Register: CRP_NPLL_REG8
 */
#define CRP_NPLL_REG8    ( ( CRP_BASEADDR ) + 0X000000C0 )

#define CRP_NPLL_REG8_CONTROL_5_SHIFT   16
#define CRP_NPLL_REG8_CONTROL_5_WIDTH   16
#define CRP_NPLL_REG8_CONTROL_5_MASK    0XFFFF0000

#define CRP_NPLL_REG8_CONTROL_4_SHIFT   0
#define CRP_NPLL_REG8_CONTROL_4_WIDTH   16
#define CRP_NPLL_REG8_CONTROL_4_MASK    0X0000FFFF

/**
 * Register: CRP_NPLL_REG9
 */
#define CRP_NPLL_REG9    ( ( CRP_BASEADDR ) + 0X000000C4 )

#define CRP_NPLL_REG9_CONTROL_7_SHIFT   16
#define CRP_NPLL_REG9_CONTROL_7_WIDTH   16
#define CRP_NPLL_REG9_CONTROL_7_MASK    0XFFFF0000

#define CRP_NPLL_REG9_CONTROL_6_SHIFT   0
#define CRP_NPLL_REG9_CONTROL_6_WIDTH   16
#define CRP_NPLL_REG9_CONTROL_6_MASK    0X0000FFFF

/**
 * Register: CRP_PPLL_TO_XPD_CTRL
 */
#define CRP_PPLL_TO_XPD_CTRL    ( ( CRP_BASEADDR ) + 0X00000100 )

#define CRP_PPLL_TO_XPD_CTRL_CLKACT_SHIFT   25
#define CRP_PPLL_TO_XPD_CTRL_CLKACT_WIDTH   1
#define CRP_PPLL_TO_XPD_CTRL_CLKACT_MASK    0X02000000

#define CRP_PPLL_TO_XPD_CTRL_DIVISOR0_SHIFT   8
#define CRP_PPLL_TO_XPD_CTRL_DIVISOR0_WIDTH   10
#define CRP_PPLL_TO_XPD_CTRL_DIVISOR0_MASK    0X0003FF00

/**
 * Register: CRP_NPLL_TO_XPD_CTRL
 */
#define CRP_NPLL_TO_XPD_CTRL    ( ( CRP_BASEADDR ) + 0X00000104 )

#define CRP_NPLL_TO_XPD_CTRL_CLKACT_SHIFT   25
#define CRP_NPLL_TO_XPD_CTRL_CLKACT_WIDTH   1
#define CRP_NPLL_TO_XPD_CTRL_CLKACT_MASK    0X02000000

#define CRP_NPLL_TO_XPD_CTRL_DIVISOR0_SHIFT   8
#define CRP_NPLL_TO_XPD_CTRL_DIVISOR0_WIDTH   10
#define CRP_NPLL_TO_XPD_CTRL_DIVISOR0_MASK    0X0003FF00

/**
 * Register: CRP_CFU_REF_CTRL
 */
#define CRP_CFU_REF_CTRL    ( ( CRP_BASEADDR ) + 0X00000108 )

#define CRP_CFU_REF_CTRL_CLKACT_SHIFT   25
#define CRP_CFU_REF_CTRL_CLKACT_WIDTH   1
#define CRP_CFU_REF_CTRL_CLKACT_MASK    0X02000000

#define CRP_CFU_REF_CTRL_DIVISOR0_SHIFT   8
#define CRP_CFU_REF_CTRL_DIVISOR0_WIDTH   10
#define CRP_CFU_REF_CTRL_DIVISOR0_MASK    0X0003FF00

#define CRP_CFU_REF_CTRL_SRCSEL_SHIFT   0
#define CRP_CFU_REF_CTRL_SRCSEL_WIDTH   3
#define CRP_CFU_REF_CTRL_SRCSEL_MASK    0X00000007

/**
 * Register: CRP_SPARE_REF_CTRL
 */
#define CRP_SPARE_REF_CTRL    ( ( CRP_BASEADDR ) + 0X00000110 )

#define CRP_SPARE_REF_CTRL_CLKACT_SHIFT   25
#define CRP_SPARE_REF_CTRL_CLKACT_WIDTH   1
#define CRP_SPARE_REF_CTRL_CLKACT_MASK    0X02000000

#define CRP_SPARE_REF_CTRL_DIVISOR0_SHIFT   8
#define CRP_SPARE_REF_CTRL_DIVISOR0_WIDTH   10
#define CRP_SPARE_REF_CTRL_DIVISOR0_MASK    0X0003FF00

#define CRP_SPARE_REF_CTRL_SRCSEL_SHIFT   0
#define CRP_SPARE_REF_CTRL_SRCSEL_WIDTH   3
#define CRP_SPARE_REF_CTRL_SRCSEL_MASK    0X00000007

/**
 * Register: CRP_NPI_REF_CTRL
 */
#define CRP_NPI_REF_CTRL    ( ( CRP_BASEADDR ) + 0X00000114 )

#define CRP_NPI_REF_CTRL_CLKACT_SHIFT   25
#define CRP_NPI_REF_CTRL_CLKACT_WIDTH   1
#define CRP_NPI_REF_CTRL_CLKACT_MASK    0X02000000

#define CRP_NPI_REF_CTRL_DIVISOR0_SHIFT   8
#define CRP_NPI_REF_CTRL_DIVISOR0_WIDTH   10
#define CRP_NPI_REF_CTRL_DIVISOR0_MASK    0X0003FF00

#define CRP_NPI_REF_CTRL_SRCSEL_SHIFT   0
#define CRP_NPI_REF_CTRL_SRCSEL_WIDTH   3
#define CRP_NPI_REF_CTRL_SRCSEL_MASK    0X00000007

/**
 * Register: CRP_QSPI_REF_CTRL
 */
#define CRP_QSPI_REF_CTRL    ( ( CRP_BASEADDR ) + 0X00000118 )

#define CRP_QSPI_REF_CTRL_CLKACT_SHIFT   24
#define CRP_QSPI_REF_CTRL_CLKACT_WIDTH   1
#define CRP_QSPI_REF_CTRL_CLKACT_MASK    0X01000000

#define CRP_QSPI_REF_CTRL_DIVISOR0_SHIFT   8
#define CRP_QSPI_REF_CTRL_DIVISOR0_WIDTH   10
#define CRP_QSPI_REF_CTRL_DIVISOR0_MASK    0X0003FF00

#define CRP_QSPI_REF_CTRL_SRCSEL_SHIFT   0
#define CRP_QSPI_REF_CTRL_SRCSEL_WIDTH   3
#define CRP_QSPI_REF_CTRL_SRCSEL_MASK    0X00000007

/**
 * Register: CRP_OSPI_REF_CTRL
 */
#define CRP_OSPI_REF_CTRL    ( ( CRP_BASEADDR ) + 0X00000120 )

#define CRP_OSPI_REF_CTRL_CLKACT_SHIFT   24
#define CRP_OSPI_REF_CTRL_CLKACT_WIDTH   1
#define CRP_OSPI_REF_CTRL_CLKACT_MASK    0X01000000

#define CRP_OSPI_REF_CTRL_DIVISOR0_SHIFT   8
#define CRP_OSPI_REF_CTRL_DIVISOR0_WIDTH   10
#define CRP_OSPI_REF_CTRL_DIVISOR0_MASK    0X0003FF00

#define CRP_OSPI_REF_CTRL_SRCSEL_SHIFT   0
#define CRP_OSPI_REF_CTRL_SRCSEL_WIDTH   3
#define CRP_OSPI_REF_CTRL_SRCSEL_MASK    0X00000007

/**
 * Register: CRP_SDIO0_REF_CTRL
 */
#define CRP_SDIO0_REF_CTRL    ( ( CRP_BASEADDR ) + 0X00000124 )

#define CRP_SDIO0_REF_CTRL_CLKACT_SHIFT   24
#define CRP_SDIO0_REF_CTRL_CLKACT_WIDTH   1
#define CRP_SDIO0_REF_CTRL_CLKACT_MASK    0X01000000

#define CRP_SDIO0_REF_CTRL_DIVISOR0_SHIFT   8
#define CRP_SDIO0_REF_CTRL_DIVISOR0_WIDTH   10
#define CRP_SDIO0_REF_CTRL_DIVISOR0_MASK    0X0003FF00

#define CRP_SDIO0_REF_CTRL_SRCSEL_SHIFT   0
#define CRP_SDIO0_REF_CTRL_SRCSEL_WIDTH   3
#define CRP_SDIO0_REF_CTRL_SRCSEL_MASK    0X00000007

/**
 * Register: CRP_SDIO1_REF_CTRL
 */
#define CRP_SDIO1_REF_CTRL    ( ( CRP_BASEADDR ) + 0X00000128 )

#define CRP_SDIO1_REF_CTRL_CLKACT_SHIFT   24
#define CRP_SDIO1_REF_CTRL_CLKACT_WIDTH   1
#define CRP_SDIO1_REF_CTRL_CLKACT_MASK    0X01000000

#define CRP_SDIO1_REF_CTRL_DIVISOR0_SHIFT   8
#define CRP_SDIO1_REF_CTRL_DIVISOR0_WIDTH   10
#define CRP_SDIO1_REF_CTRL_DIVISOR0_MASK    0X0003FF00

#define CRP_SDIO1_REF_CTRL_SRCSEL_SHIFT   0
#define CRP_SDIO1_REF_CTRL_SRCSEL_WIDTH   3
#define CRP_SDIO1_REF_CTRL_SRCSEL_MASK    0X00000007

/**
 * Register: CRP_PMC_LSBUS_REF_CTRL
 */
#define CRP_PMC_LSBUS_REF_CTRL    ( ( CRP_BASEADDR ) + 0X0000012C )

#define CRP_PMC_LSBUS_REF_CTRL_CLKACT_SHIFT   24
#define CRP_PMC_LSBUS_REF_CTRL_CLKACT_WIDTH   1
#define CRP_PMC_LSBUS_REF_CTRL_CLKACT_MASK    0X01000000

#define CRP_PMC_LSBUS_REF_CTRL_DIVISOR0_SHIFT   8
#define CRP_PMC_LSBUS_REF_CTRL_DIVISOR0_WIDTH   10
#define CRP_PMC_LSBUS_REF_CTRL_DIVISOR0_MASK    0X0003FF00

#define CRP_PMC_LSBUS_REF_CTRL_SRCSEL_SHIFT   0
#define CRP_PMC_LSBUS_REF_CTRL_SRCSEL_WIDTH   3
#define CRP_PMC_LSBUS_REF_CTRL_SRCSEL_MASK    0X00000007

/**
 * Register: CRP_I2C_REF_CTRL
 */
#define CRP_I2C_REF_CTRL    ( ( CRP_BASEADDR ) + 0X00000130 )

#define CRP_I2C_REF_CTRL_CLKACT_SHIFT   24
#define CRP_I2C_REF_CTRL_CLKACT_WIDTH   1
#define CRP_I2C_REF_CTRL_CLKACT_MASK    0X01000000

#define CRP_I2C_REF_CTRL_DIVISOR0_SHIFT   8
#define CRP_I2C_REF_CTRL_DIVISOR0_WIDTH   10
#define CRP_I2C_REF_CTRL_DIVISOR0_MASK    0X0003FF00

#define CRP_I2C_REF_CTRL_SRCSEL_SHIFT   0
#define CRP_I2C_REF_CTRL_SRCSEL_WIDTH   3
#define CRP_I2C_REF_CTRL_SRCSEL_MASK    0X00000007

/**
 * Register: CRP_EFUSE_REF_CTRL
 */
#define CRP_EFUSE_REF_CTRL    ( ( CRP_BASEADDR ) + 0X00000134 )

#define CRP_EFUSE_REF_CTRL_SRCSEL_SHIFT   2
#define CRP_EFUSE_REF_CTRL_SRCSEL_WIDTH   1
#define CRP_EFUSE_REF_CTRL_SRCSEL_MASK    0X00000004

/**
 * Register: CRP_SYSMON_REF_CTRL
 */
#define CRP_SYSMON_REF_CTRL    ( ( CRP_BASEADDR ) + 0X00000138 )

#define CRP_SYSMON_REF_CTRL_SRCSEL_SHIFT   2
#define CRP_SYSMON_REF_CTRL_SRCSEL_WIDTH   1
#define CRP_SYSMON_REF_CTRL_SRCSEL_MASK    0X00000004

/**
 * Register: CRP_IRO_SUSPEND_REF_CTRL
 */
#define CRP_IRO_SUSPEND_REF_CTRL    ( ( CRP_BASEADDR ) + 0X0000013C )

#define CRP_IRO_SUSPEND_REF_CTRL_DIVISOR0_SHIFT   8
#define CRP_IRO_SUSPEND_REF_CTRL_DIVISOR0_WIDTH   10
#define CRP_IRO_SUSPEND_REF_CTRL_DIVISOR0_MASK    0X0003FF00

/**
 * Register: CRP_USB_SUSPEND_CTRL
 */
#define CRP_USB_SUSPEND_CTRL    ( ( CRP_BASEADDR ) + 0X00000140 )

#define CRP_USB_SUSPEND_CTRL_DIVISOR0_SHIFT   8
#define CRP_USB_SUSPEND_CTRL_DIVISOR0_WIDTH   10
#define CRP_USB_SUSPEND_CTRL_DIVISOR0_MASK    0X0003FF00

/**
 * Register: CRP_SWITCH_TIMEOUT_CTRL
 */
#define CRP_SWITCH_TIMEOUT_CTRL    ( ( CRP_BASEADDR ) + 0X00000144 )

#define CRP_SWITCH_TIMEOUT_CTRL_DIVISOR0_SHIFT   8
#define CRP_SWITCH_TIMEOUT_CTRL_DIVISOR0_WIDTH   10
#define CRP_SWITCH_TIMEOUT_CTRL_DIVISOR0_MASK    0X0003FF00

/**
 * Register: CRP_HSM0_REF_CTRL
 */
#define CRP_HSM0_REF_CTRL    ( ( CRP_BASEADDR ) + 0X00000148 )

#define CRP_HSM0_REF_CTRL_CLKACT_SHIFT   25
#define CRP_HSM0_REF_CTRL_CLKACT_WIDTH   1
#define CRP_HSM0_REF_CTRL_CLKACT_MASK    0X02000000

#define CRP_HSM0_REF_CTRL_DIVISOR0_SHIFT   8
#define CRP_HSM0_REF_CTRL_DIVISOR0_WIDTH   10
#define CRP_HSM0_REF_CTRL_DIVISOR0_MASK    0X0003FF00

#define CRP_HSM0_REF_CTRL_SRCSEL_SHIFT   0
#define CRP_HSM0_REF_CTRL_SRCSEL_WIDTH   3
#define CRP_HSM0_REF_CTRL_SRCSEL_MASK    0X00000007

/**
 * Register: CRP_HSM1_REF_CTRL
 */
#define CRP_HSM1_REF_CTRL    ( ( CRP_BASEADDR ) + 0X0000014C )

#define CRP_HSM1_REF_CTRL_CLKACT_SHIFT   25
#define CRP_HSM1_REF_CTRL_CLKACT_WIDTH   1
#define CRP_HSM1_REF_CTRL_CLKACT_MASK    0X02000000

#define CRP_HSM1_REF_CTRL_DIVISOR0_SHIFT   8
#define CRP_HSM1_REF_CTRL_DIVISOR0_WIDTH   10
#define CRP_HSM1_REF_CTRL_DIVISOR0_MASK    0X0003FF00

#define CRP_HSM1_REF_CTRL_SRCSEL_SHIFT   0
#define CRP_HSM1_REF_CTRL_SRCSEL_WIDTH   3
#define CRP_HSM1_REF_CTRL_SRCSEL_MASK    0X00000007

/**
 * Register: CRP_SAFETY_CHK
 */
#define CRP_SAFETY_CHK    ( ( CRP_BASEADDR ) + 0X00000150 )

#define CRP_SAFETY_CHK_CHK_VAL_SHIFT   0
#define CRP_SAFETY_CHK_CHK_VAL_WIDTH   32
#define CRP_SAFETY_CHK_CHK_VAL_MASK    0XFFFFFFFF

/**
 * Register: CRP_SD_DLL_REF_CTRL
 */
#define CRP_SD_DLL_REF_CTRL    ( ( CRP_BASEADDR ) + 0X00000160 )

#define CRP_SD_DLL_REF_CTRL_CLKACT_SHIFT   25
#define CRP_SD_DLL_REF_CTRL_CLKACT_WIDTH   1
#define CRP_SD_DLL_REF_CTRL_CLKACT_MASK    0X02000000

#define CRP_SD_DLL_REF_CTRL_DIVISOR0_SHIFT   8
#define CRP_SD_DLL_REF_CTRL_DIVISOR0_WIDTH   10
#define CRP_SD_DLL_REF_CTRL_DIVISOR0_MASK    0X0003FF00

#define CRP_SD_DLL_REF_CTRL_SRCSEL_SHIFT   0
#define CRP_SD_DLL_REF_CTRL_SRCSEL_WIDTH   3
#define CRP_SD_DLL_REF_CTRL_SRCSEL_MASK    0X00000007

/**
 * Register: CRP_BOOT_MODE_USER
 */
#define CRP_BOOT_MODE_USER    ( ( CRP_BASEADDR ) + 0X00000200 )

#define CRP_BOOT_MODE_USER_ALT_BOOT_MODE_SHIFT   12
#define CRP_BOOT_MODE_USER_ALT_BOOT_MODE_WIDTH   4
#define CRP_BOOT_MODE_USER_ALT_BOOT_MODE_MASK    0X0000F000

#define CRP_BOOT_MODE_USER_USE_ALT_SHIFT   8
#define CRP_BOOT_MODE_USER_USE_ALT_WIDTH   1
#define CRP_BOOT_MODE_USER_USE_ALT_MASK    0X00000100

#define CRP_BOOT_MODE_USER_BOOT_MODE_SHIFT   0
#define CRP_BOOT_MODE_USER_BOOT_MODE_WIDTH   4
#define CRP_BOOT_MODE_USER_BOOT_MODE_MASK    0X0000000F

/**
 * Register: CRP_BOOT_MODE_POR
 */
#define CRP_BOOT_MODE_POR    ( ( CRP_BASEADDR ) + 0X00000204 )

#define CRP_BOOT_MODE_POR_BOOT_MODE2_SHIFT   8
#define CRP_BOOT_MODE_POR_BOOT_MODE2_WIDTH   4
#define CRP_BOOT_MODE_POR_BOOT_MODE2_MASK    0X00000F00

#define CRP_BOOT_MODE_POR_BOOT_MODE1_SHIFT   4
#define CRP_BOOT_MODE_POR_BOOT_MODE1_WIDTH   4
#define CRP_BOOT_MODE_POR_BOOT_MODE1_MASK    0X000000F0

#define CRP_BOOT_MODE_POR_BOOT_MODE0_SHIFT   0
#define CRP_BOOT_MODE_POR_BOOT_MODE0_WIDTH   4
#define CRP_BOOT_MODE_POR_BOOT_MODE0_MASK    0X0000000F

/**
 * Register: CRP_RESET_REASON
 */
#define CRP_RESET_REASON    ( ( CRP_BASEADDR ) + 0X00000220 )

#define CRP_RESET_REASON_SLR_SYS_SHIFT   10
#define CRP_RESET_REASON_SLR_SYS_WIDTH   1
#define CRP_RESET_REASON_SLR_SYS_MASK    0X00000400

#define CRP_RESET_REASON_SW_SYS_SHIFT   9
#define CRP_RESET_REASON_SW_SYS_WIDTH   1
#define CRP_RESET_REASON_SW_SYS_MASK    0X00000200

#define CRP_RESET_REASON_ERR_SYS_SHIFT   8
#define CRP_RESET_REASON_ERR_SYS_WIDTH   1
#define CRP_RESET_REASON_ERR_SYS_MASK    0X00000100

#define CRP_RESET_REASON_DAP_SYS_SHIFT   7
#define CRP_RESET_REASON_DAP_SYS_WIDTH   1
#define CRP_RESET_REASON_DAP_SYS_MASK    0X00000080

#define CRP_RESET_REASON_ERR_POR_SHIFT   3
#define CRP_RESET_REASON_ERR_POR_WIDTH   1
#define CRP_RESET_REASON_ERR_POR_MASK    0X00000008

#define CRP_RESET_REASON_SLR_POR_SHIFT   2
#define CRP_RESET_REASON_SLR_POR_WIDTH   1
#define CRP_RESET_REASON_SLR_POR_MASK    0X00000004

#define CRP_RESET_REASON_SW_POR_SHIFT   1
#define CRP_RESET_REASON_SW_POR_WIDTH   1
#define CRP_RESET_REASON_SW_POR_MASK    0X00000002

#define CRP_RESET_REASON_EXTERNAL_POR_SHIFT   0
#define CRP_RESET_REASON_EXTERNAL_POR_WIDTH   1
#define CRP_RESET_REASON_EXTERNAL_POR_MASK    0X00000001

/**
 * Register: CRP_CLKMON_STATUS
 */
#define CRP_CLKMON_STATUS    ( ( CRP_BASEADDR ) + 0X00000240 )

#define CRP_CLKMON_STATUS_CNTA7_OVER_ERR_SHIFT   15
#define CRP_CLKMON_STATUS_CNTA7_OVER_ERR_WIDTH   1
#define CRP_CLKMON_STATUS_CNTA7_OVER_ERR_MASK    0X00008000

#define CRP_CLKMON_STATUS_MON7_ERR_SHIFT   14
#define CRP_CLKMON_STATUS_MON7_ERR_WIDTH   1
#define CRP_CLKMON_STATUS_MON7_ERR_MASK    0X00004000

#define CRP_CLKMON_STATUS_CNTA6_OVER_ERR_SHIFT   13
#define CRP_CLKMON_STATUS_CNTA6_OVER_ERR_WIDTH   1
#define CRP_CLKMON_STATUS_CNTA6_OVER_ERR_MASK    0X00002000

#define CRP_CLKMON_STATUS_MON6_ERR_SHIFT   12
#define CRP_CLKMON_STATUS_MON6_ERR_WIDTH   1
#define CRP_CLKMON_STATUS_MON6_ERR_MASK    0X00001000

#define CRP_CLKMON_STATUS_CNTA5_OVER_ERR_SHIFT   11
#define CRP_CLKMON_STATUS_CNTA5_OVER_ERR_WIDTH   1
#define CRP_CLKMON_STATUS_CNTA5_OVER_ERR_MASK    0X00000800

#define CRP_CLKMON_STATUS_MON5_ERR_SHIFT   10
#define CRP_CLKMON_STATUS_MON5_ERR_WIDTH   1
#define CRP_CLKMON_STATUS_MON5_ERR_MASK    0X00000400

#define CRP_CLKMON_STATUS_CNTA4_OVER_ERR_SHIFT   9
#define CRP_CLKMON_STATUS_CNTA4_OVER_ERR_WIDTH   1
#define CRP_CLKMON_STATUS_CNTA4_OVER_ERR_MASK    0X00000200

#define CRP_CLKMON_STATUS_MON4_ERR_SHIFT   8
#define CRP_CLKMON_STATUS_MON4_ERR_WIDTH   1
#define CRP_CLKMON_STATUS_MON4_ERR_MASK    0X00000100

#define CRP_CLKMON_STATUS_CNTA3_OVER_ERR_SHIFT   7
#define CRP_CLKMON_STATUS_CNTA3_OVER_ERR_WIDTH   1
#define CRP_CLKMON_STATUS_CNTA3_OVER_ERR_MASK    0X00000080

#define CRP_CLKMON_STATUS_MON3_ERR_SHIFT   6
#define CRP_CLKMON_STATUS_MON3_ERR_WIDTH   1
#define CRP_CLKMON_STATUS_MON3_ERR_MASK    0X00000040

#define CRP_CLKMON_STATUS_CNTA2_OVER_ERR_SHIFT   5
#define CRP_CLKMON_STATUS_CNTA2_OVER_ERR_WIDTH   1
#define CRP_CLKMON_STATUS_CNTA2_OVER_ERR_MASK    0X00000020

#define CRP_CLKMON_STATUS_MON2_ERR_SHIFT   4
#define CRP_CLKMON_STATUS_MON2_ERR_WIDTH   1
#define CRP_CLKMON_STATUS_MON2_ERR_MASK    0X00000010

#define CRP_CLKMON_STATUS_CNTA1_OVER_ERR_SHIFT   3
#define CRP_CLKMON_STATUS_CNTA1_OVER_ERR_WIDTH   1
#define CRP_CLKMON_STATUS_CNTA1_OVER_ERR_MASK    0X00000008

#define CRP_CLKMON_STATUS_MON1_ERR_SHIFT   2
#define CRP_CLKMON_STATUS_MON1_ERR_WIDTH   1
#define CRP_CLKMON_STATUS_MON1_ERR_MASK    0X00000004

#define CRP_CLKMON_STATUS_CNTA0_OVER_ERR_SHIFT   1
#define CRP_CLKMON_STATUS_CNTA0_OVER_ERR_WIDTH   1
#define CRP_CLKMON_STATUS_CNTA0_OVER_ERR_MASK    0X00000002

#define CRP_CLKMON_STATUS_MON0_ERR_SHIFT   0
#define CRP_CLKMON_STATUS_MON0_ERR_WIDTH   1
#define CRP_CLKMON_STATUS_MON0_ERR_MASK    0X00000001

/**
 * Register: CRP_CLKMON_MASK
 */
#define CRP_CLKMON_MASK    ( ( CRP_BASEADDR ) + 0X00000244 )

#define CRP_CLKMON_MASK_CNTA7_OVER_ERR_SHIFT   15
#define CRP_CLKMON_MASK_CNTA7_OVER_ERR_WIDTH   1
#define CRP_CLKMON_MASK_CNTA7_OVER_ERR_MASK    0X00008000

#define CRP_CLKMON_MASK_MON7_ERR_SHIFT   14
#define CRP_CLKMON_MASK_MON7_ERR_WIDTH   1
#define CRP_CLKMON_MASK_MON7_ERR_MASK    0X00004000

#define CRP_CLKMON_MASK_CNTA6_OVER_ERR_SHIFT   13
#define CRP_CLKMON_MASK_CNTA6_OVER_ERR_WIDTH   1
#define CRP_CLKMON_MASK_CNTA6_OVER_ERR_MASK    0X00002000

#define CRP_CLKMON_MASK_MON6_ERR_SHIFT   12
#define CRP_CLKMON_MASK_MON6_ERR_WIDTH   1
#define CRP_CLKMON_MASK_MON6_ERR_MASK    0X00001000

#define CRP_CLKMON_MASK_CNTA5_OVER_ERR_SHIFT   11
#define CRP_CLKMON_MASK_CNTA5_OVER_ERR_WIDTH   1
#define CRP_CLKMON_MASK_CNTA5_OVER_ERR_MASK    0X00000800

#define CRP_CLKMON_MASK_MON5_ERR_SHIFT   10
#define CRP_CLKMON_MASK_MON5_ERR_WIDTH   1
#define CRP_CLKMON_MASK_MON5_ERR_MASK    0X00000400

#define CRP_CLKMON_MASK_CNTA4_OVER_ERR_SHIFT   9
#define CRP_CLKMON_MASK_CNTA4_OVER_ERR_WIDTH   1
#define CRP_CLKMON_MASK_CNTA4_OVER_ERR_MASK    0X00000200

#define CRP_CLKMON_MASK_MON4_ERR_SHIFT   8
#define CRP_CLKMON_MASK_MON4_ERR_WIDTH   1
#define CRP_CLKMON_MASK_MON4_ERR_MASK    0X00000100

#define CRP_CLKMON_MASK_CNTA3_OVER_ERR_SHIFT   7
#define CRP_CLKMON_MASK_CNTA3_OVER_ERR_WIDTH   1
#define CRP_CLKMON_MASK_CNTA3_OVER_ERR_MASK    0X00000080

#define CRP_CLKMON_MASK_MON3_ERR_SHIFT   6
#define CRP_CLKMON_MASK_MON3_ERR_WIDTH   1
#define CRP_CLKMON_MASK_MON3_ERR_MASK    0X00000040

#define CRP_CLKMON_MASK_CNTA2_OVER_ERR_SHIFT   5
#define CRP_CLKMON_MASK_CNTA2_OVER_ERR_WIDTH   1
#define CRP_CLKMON_MASK_CNTA2_OVER_ERR_MASK    0X00000020

#define CRP_CLKMON_MASK_MON2_ERR_SHIFT   4
#define CRP_CLKMON_MASK_MON2_ERR_WIDTH   1
#define CRP_CLKMON_MASK_MON2_ERR_MASK    0X00000010

#define CRP_CLKMON_MASK_CNTA1_OVER_ERR_SHIFT   3
#define CRP_CLKMON_MASK_CNTA1_OVER_ERR_WIDTH   1
#define CRP_CLKMON_MASK_CNTA1_OVER_ERR_MASK    0X00000008

#define CRP_CLKMON_MASK_MON1_ERR_SHIFT   2
#define CRP_CLKMON_MASK_MON1_ERR_WIDTH   1
#define CRP_CLKMON_MASK_MON1_ERR_MASK    0X00000004

#define CRP_CLKMON_MASK_CNTA0_OVER_ERR_SHIFT   1
#define CRP_CLKMON_MASK_CNTA0_OVER_ERR_WIDTH   1
#define CRP_CLKMON_MASK_CNTA0_OVER_ERR_MASK    0X00000002

#define CRP_CLKMON_MASK_MON0_ERR_SHIFT   0
#define CRP_CLKMON_MASK_MON0_ERR_WIDTH   1
#define CRP_CLKMON_MASK_MON0_ERR_MASK    0X00000001

/**
 * Register: CRP_CLKMON_ENABLE
 */
#define CRP_CLKMON_ENABLE    ( ( CRP_BASEADDR ) + 0X00000248 )

#define CRP_CLKMON_ENABLE_CNTA7_OVER_ERR_SHIFT   15
#define CRP_CLKMON_ENABLE_CNTA7_OVER_ERR_WIDTH   1
#define CRP_CLKMON_ENABLE_CNTA7_OVER_ERR_MASK    0X00008000

#define CRP_CLKMON_ENABLE_MON7_ERR_SHIFT   14
#define CRP_CLKMON_ENABLE_MON7_ERR_WIDTH   1
#define CRP_CLKMON_ENABLE_MON7_ERR_MASK    0X00004000

#define CRP_CLKMON_ENABLE_CNTA6_OVER_ERR_SHIFT   13
#define CRP_CLKMON_ENABLE_CNTA6_OVER_ERR_WIDTH   1
#define CRP_CLKMON_ENABLE_CNTA6_OVER_ERR_MASK    0X00002000

#define CRP_CLKMON_ENABLE_MON6_ERR_SHIFT   12
#define CRP_CLKMON_ENABLE_MON6_ERR_WIDTH   1
#define CRP_CLKMON_ENABLE_MON6_ERR_MASK    0X00001000

#define CRP_CLKMON_ENABLE_CNTA5_OVER_ERR_SHIFT   11
#define CRP_CLKMON_ENABLE_CNTA5_OVER_ERR_WIDTH   1
#define CRP_CLKMON_ENABLE_CNTA5_OVER_ERR_MASK    0X00000800

#define CRP_CLKMON_ENABLE_MON5_ERR_SHIFT   10
#define CRP_CLKMON_ENABLE_MON5_ERR_WIDTH   1
#define CRP_CLKMON_ENABLE_MON5_ERR_MASK    0X00000400

#define CRP_CLKMON_ENABLE_CNTA4_OVER_ERR_SHIFT   9
#define CRP_CLKMON_ENABLE_CNTA4_OVER_ERR_WIDTH   1
#define CRP_CLKMON_ENABLE_CNTA4_OVER_ERR_MASK    0X00000200

#define CRP_CLKMON_ENABLE_MON4_ERR_SHIFT   8
#define CRP_CLKMON_ENABLE_MON4_ERR_WIDTH   1
#define CRP_CLKMON_ENABLE_MON4_ERR_MASK    0X00000100

#define CRP_CLKMON_ENABLE_CNTA3_OVER_ERR_SHIFT   7
#define CRP_CLKMON_ENABLE_CNTA3_OVER_ERR_WIDTH   1
#define CRP_CLKMON_ENABLE_CNTA3_OVER_ERR_MASK    0X00000080

#define CRP_CLKMON_ENABLE_MON3_ERR_SHIFT   6
#define CRP_CLKMON_ENABLE_MON3_ERR_WIDTH   1
#define CRP_CLKMON_ENABLE_MON3_ERR_MASK    0X00000040

#define CRP_CLKMON_ENABLE_CNTA2_OVER_ERR_SHIFT   5
#define CRP_CLKMON_ENABLE_CNTA2_OVER_ERR_WIDTH   1
#define CRP_CLKMON_ENABLE_CNTA2_OVER_ERR_MASK    0X00000020

#define CRP_CLKMON_ENABLE_MON2_ERR_SHIFT   4
#define CRP_CLKMON_ENABLE_MON2_ERR_WIDTH   1
#define CRP_CLKMON_ENABLE_MON2_ERR_MASK    0X00000010

#define CRP_CLKMON_ENABLE_CNTA1_OVER_ERR_SHIFT   3
#define CRP_CLKMON_ENABLE_CNTA1_OVER_ERR_WIDTH   1
#define CRP_CLKMON_ENABLE_CNTA1_OVER_ERR_MASK    0X00000008

#define CRP_CLKMON_ENABLE_MON1_ERR_SHIFT   2
#define CRP_CLKMON_ENABLE_MON1_ERR_WIDTH   1
#define CRP_CLKMON_ENABLE_MON1_ERR_MASK    0X00000004

#define CRP_CLKMON_ENABLE_CNTA0_OVER_ERR_SHIFT   1
#define CRP_CLKMON_ENABLE_CNTA0_OVER_ERR_WIDTH   1
#define CRP_CLKMON_ENABLE_CNTA0_OVER_ERR_MASK    0X00000002

#define CRP_CLKMON_ENABLE_MON0_ERR_SHIFT   0
#define CRP_CLKMON_ENABLE_MON0_ERR_WIDTH   1
#define CRP_CLKMON_ENABLE_MON0_ERR_MASK    0X00000001

/**
 * Register: CRP_CLKMON_DISABLE
 */
#define CRP_CLKMON_DISABLE    ( ( CRP_BASEADDR ) + 0X0000024C )

#define CRP_CLKMON_DISABLE_CNTA7_OVER_ERR_SHIFT   15
#define CRP_CLKMON_DISABLE_CNTA7_OVER_ERR_WIDTH   1
#define CRP_CLKMON_DISABLE_CNTA7_OVER_ERR_MASK    0X00008000

#define CRP_CLKMON_DISABLE_MON7_ERR_SHIFT   14
#define CRP_CLKMON_DISABLE_MON7_ERR_WIDTH   1
#define CRP_CLKMON_DISABLE_MON7_ERR_MASK    0X00004000

#define CRP_CLKMON_DISABLE_CNTA6_OVER_ERR_SHIFT   13
#define CRP_CLKMON_DISABLE_CNTA6_OVER_ERR_WIDTH   1
#define CRP_CLKMON_DISABLE_CNTA6_OVER_ERR_MASK    0X00002000

#define CRP_CLKMON_DISABLE_MON6_ERR_SHIFT   12
#define CRP_CLKMON_DISABLE_MON6_ERR_WIDTH   1
#define CRP_CLKMON_DISABLE_MON6_ERR_MASK    0X00001000

#define CRP_CLKMON_DISABLE_CNTA5_OVER_ERR_SHIFT   11
#define CRP_CLKMON_DISABLE_CNTA5_OVER_ERR_WIDTH   1
#define CRP_CLKMON_DISABLE_CNTA5_OVER_ERR_MASK    0X00000800

#define CRP_CLKMON_DISABLE_MON5_ERR_SHIFT   10
#define CRP_CLKMON_DISABLE_MON5_ERR_WIDTH   1
#define CRP_CLKMON_DISABLE_MON5_ERR_MASK    0X00000400

#define CRP_CLKMON_DISABLE_CNTA4_OVER_ERR_SHIFT   9
#define CRP_CLKMON_DISABLE_CNTA4_OVER_ERR_WIDTH   1
#define CRP_CLKMON_DISABLE_CNTA4_OVER_ERR_MASK    0X00000200

#define CRP_CLKMON_DISABLE_MON4_ERR_SHIFT   8
#define CRP_CLKMON_DISABLE_MON4_ERR_WIDTH   1
#define CRP_CLKMON_DISABLE_MON4_ERR_MASK    0X00000100

#define CRP_CLKMON_DISABLE_CNTA3_OVER_ERR_SHIFT   7
#define CRP_CLKMON_DISABLE_CNTA3_OVER_ERR_WIDTH   1
#define CRP_CLKMON_DISABLE_CNTA3_OVER_ERR_MASK    0X00000080

#define CRP_CLKMON_DISABLE_MON3_ERR_SHIFT   6
#define CRP_CLKMON_DISABLE_MON3_ERR_WIDTH   1
#define CRP_CLKMON_DISABLE_MON3_ERR_MASK    0X00000040

#define CRP_CLKMON_DISABLE_CNTA2_OVER_ERR_SHIFT   5
#define CRP_CLKMON_DISABLE_CNTA2_OVER_ERR_WIDTH   1
#define CRP_CLKMON_DISABLE_CNTA2_OVER_ERR_MASK    0X00000020

#define CRP_CLKMON_DISABLE_MON2_ERR_SHIFT   4
#define CRP_CLKMON_DISABLE_MON2_ERR_WIDTH   1
#define CRP_CLKMON_DISABLE_MON2_ERR_MASK    0X00000010

#define CRP_CLKMON_DISABLE_CNTA1_OVER_ERR_SHIFT   3
#define CRP_CLKMON_DISABLE_CNTA1_OVER_ERR_WIDTH   1
#define CRP_CLKMON_DISABLE_CNTA1_OVER_ERR_MASK    0X00000008

#define CRP_CLKMON_DISABLE_MON1_ERR_SHIFT   2
#define CRP_CLKMON_DISABLE_MON1_ERR_WIDTH   1
#define CRP_CLKMON_DISABLE_MON1_ERR_MASK    0X00000004

#define CRP_CLKMON_DISABLE_CNTA0_OVER_ERR_SHIFT   1
#define CRP_CLKMON_DISABLE_CNTA0_OVER_ERR_WIDTH   1
#define CRP_CLKMON_DISABLE_CNTA0_OVER_ERR_MASK    0X00000002

#define CRP_CLKMON_DISABLE_MON0_ERR_SHIFT   0
#define CRP_CLKMON_DISABLE_MON0_ERR_WIDTH   1
#define CRP_CLKMON_DISABLE_MON0_ERR_MASK    0X00000001

/**
 * Register: CRP_CLKMON_TRIGGER
 */
#define CRP_CLKMON_TRIGGER    ( ( CRP_BASEADDR ) + 0X00000250 )

#define CRP_CLKMON_TRIGGER_CNTA7_OVER_ERR_SHIFT   15
#define CRP_CLKMON_TRIGGER_CNTA7_OVER_ERR_WIDTH   1
#define CRP_CLKMON_TRIGGER_CNTA7_OVER_ERR_MASK    0X00008000

#define CRP_CLKMON_TRIGGER_MON7_ERR_SHIFT   14
#define CRP_CLKMON_TRIGGER_MON7_ERR_WIDTH   1
#define CRP_CLKMON_TRIGGER_MON7_ERR_MASK    0X00004000

#define CRP_CLKMON_TRIGGER_CNTA6_OVER_ERR_SHIFT   13
#define CRP_CLKMON_TRIGGER_CNTA6_OVER_ERR_WIDTH   1
#define CRP_CLKMON_TRIGGER_CNTA6_OVER_ERR_MASK    0X00002000

#define CRP_CLKMON_TRIGGER_MON6_ERR_SHIFT   12
#define CRP_CLKMON_TRIGGER_MON6_ERR_WIDTH   1
#define CRP_CLKMON_TRIGGER_MON6_ERR_MASK    0X00001000

#define CRP_CLKMON_TRIGGER_CNTA5_OVER_ERR_SHIFT   11
#define CRP_CLKMON_TRIGGER_CNTA5_OVER_ERR_WIDTH   1
#define CRP_CLKMON_TRIGGER_CNTA5_OVER_ERR_MASK    0X00000800

#define CRP_CLKMON_TRIGGER_MON5_ERR_SHIFT   10
#define CRP_CLKMON_TRIGGER_MON5_ERR_WIDTH   1
#define CRP_CLKMON_TRIGGER_MON5_ERR_MASK    0X00000400

#define CRP_CLKMON_TRIGGER_CNTA4_OVER_ERR_SHIFT   9
#define CRP_CLKMON_TRIGGER_CNTA4_OVER_ERR_WIDTH   1
#define CRP_CLKMON_TRIGGER_CNTA4_OVER_ERR_MASK    0X00000200

#define CRP_CLKMON_TRIGGER_MON4_ERR_SHIFT   8
#define CRP_CLKMON_TRIGGER_MON4_ERR_WIDTH   1
#define CRP_CLKMON_TRIGGER_MON4_ERR_MASK    0X00000100

#define CRP_CLKMON_TRIGGER_CNTA3_OVER_ERR_SHIFT   7
#define CRP_CLKMON_TRIGGER_CNTA3_OVER_ERR_WIDTH   1
#define CRP_CLKMON_TRIGGER_CNTA3_OVER_ERR_MASK    0X00000080

#define CRP_CLKMON_TRIGGER_MON3_ERR_SHIFT   6
#define CRP_CLKMON_TRIGGER_MON3_ERR_WIDTH   1
#define CRP_CLKMON_TRIGGER_MON3_ERR_MASK    0X00000040

#define CRP_CLKMON_TRIGGER_CNTA2_OVER_ERR_SHIFT   5
#define CRP_CLKMON_TRIGGER_CNTA2_OVER_ERR_WIDTH   1
#define CRP_CLKMON_TRIGGER_CNTA2_OVER_ERR_MASK    0X00000020

#define CRP_CLKMON_TRIGGER_MON2_ERR_SHIFT   4
#define CRP_CLKMON_TRIGGER_MON2_ERR_WIDTH   1
#define CRP_CLKMON_TRIGGER_MON2_ERR_MASK    0X00000010

#define CRP_CLKMON_TRIGGER_CNTA1_OVER_ERR_SHIFT   3
#define CRP_CLKMON_TRIGGER_CNTA1_OVER_ERR_WIDTH   1
#define CRP_CLKMON_TRIGGER_CNTA1_OVER_ERR_MASK    0X00000008

#define CRP_CLKMON_TRIGGER_MON1_ERR_SHIFT   2
#define CRP_CLKMON_TRIGGER_MON1_ERR_WIDTH   1
#define CRP_CLKMON_TRIGGER_MON1_ERR_MASK    0X00000004

#define CRP_CLKMON_TRIGGER_CNTA0_OVER_ERR_SHIFT   1
#define CRP_CLKMON_TRIGGER_CNTA0_OVER_ERR_WIDTH   1
#define CRP_CLKMON_TRIGGER_CNTA0_OVER_ERR_MASK    0X00000002

#define CRP_CLKMON_TRIGGER_MON0_ERR_SHIFT   0
#define CRP_CLKMON_TRIGGER_MON0_ERR_WIDTH   1
#define CRP_CLKMON_TRIGGER_MON0_ERR_MASK    0X00000001

/**
 * Register: CRP_CHKR0_CLKA_UPPER
 */
#define CRP_CHKR0_CLKA_UPPER    ( ( CRP_BASEADDR ) + 0X00000260 )

#define CRP_CHKR0_CLKA_UPPER_THRSHLD_SHIFT   0
#define CRP_CHKR0_CLKA_UPPER_THRSHLD_WIDTH   32
#define CRP_CHKR0_CLKA_UPPER_THRSHLD_MASK    0XFFFFFFFF

/**
 * Register: CRP_CHKR0_CLKA_LOWER
 */
#define CRP_CHKR0_CLKA_LOWER    ( ( CRP_BASEADDR ) + 0X00000264 )

#define CRP_CHKR0_CLKA_LOWER_THRSHLD_SHIFT   0
#define CRP_CHKR0_CLKA_LOWER_THRSHLD_WIDTH   32
#define CRP_CHKR0_CLKA_LOWER_THRSHLD_MASK    0XFFFFFFFF

/**
 * Register: CRP_CHKR0_CLKB_CNT
 */
#define CRP_CHKR0_CLKB_CNT    ( ( CRP_BASEADDR ) + 0X00000268 )

#define CRP_CHKR0_CLKB_CNT_VALUE_SHIFT   0
#define CRP_CHKR0_CLKB_CNT_VALUE_WIDTH   32
#define CRP_CHKR0_CLKB_CNT_VALUE_MASK    0XFFFFFFFF

/**
 * Register: CRP_CHKR0_CTRL
 */
#define CRP_CHKR0_CTRL    ( ( CRP_BASEADDR ) + 0X0000026C )

#define CRP_CHKR0_CTRL_IDLE_STATE_SHIFT   10
#define CRP_CHKR0_CTRL_IDLE_STATE_WIDTH   1
#define CRP_CHKR0_CTRL_IDLE_STATE_MASK    0X00000400

#define CRP_CHKR0_CTRL_START_SINGLE_SHIFT   9
#define CRP_CHKR0_CTRL_START_SINGLE_WIDTH   1
#define CRP_CHKR0_CTRL_START_SINGLE_MASK    0X00000200

#define CRP_CHKR0_CTRL_START_CONTINUOUS_SHIFT   8
#define CRP_CHKR0_CTRL_START_CONTINUOUS_WIDTH   1
#define CRP_CHKR0_CTRL_START_CONTINUOUS_MASK    0X00000100

#define CRP_CHKR0_CTRL_CLKB_MUX_CTRL_SHIFT   6
#define CRP_CHKR0_CTRL_CLKB_MUX_CTRL_WIDTH   1
#define CRP_CHKR0_CTRL_CLKB_MUX_CTRL_MASK    0X00000040

#define CRP_CHKR0_CTRL_CLKA_MUX_CTRL_SHIFT   1
#define CRP_CHKR0_CTRL_CLKA_MUX_CTRL_WIDTH   4
#define CRP_CHKR0_CTRL_CLKA_MUX_CTRL_MASK    0X0000001E

#define CRP_CHKR0_CTRL_ENABLE_SHIFT   0
#define CRP_CHKR0_CTRL_ENABLE_WIDTH   1
#define CRP_CHKR0_CTRL_ENABLE_MASK    0X00000001

/**
 * Register: CRP_CHKR1_CLKA_UPPER
 */
#define CRP_CHKR1_CLKA_UPPER    ( ( CRP_BASEADDR ) + 0X00000270 )

#define CRP_CHKR1_CLKA_UPPER_THRSHLD_SHIFT   0
#define CRP_CHKR1_CLKA_UPPER_THRSHLD_WIDTH   32
#define CRP_CHKR1_CLKA_UPPER_THRSHLD_MASK    0XFFFFFFFF

/**
 * Register: CRP_CHKR1_CLKA_LOWER
 */
#define CRP_CHKR1_CLKA_LOWER    ( ( CRP_BASEADDR ) + 0X00000274 )

#define CRP_CHKR1_CLKA_LOWER_THRSHLD_SHIFT   0
#define CRP_CHKR1_CLKA_LOWER_THRSHLD_WIDTH   32
#define CRP_CHKR1_CLKA_LOWER_THRSHLD_MASK    0XFFFFFFFF

/**
 * Register: CRP_CHKR1_CLKB_CNT
 */
#define CRP_CHKR1_CLKB_CNT    ( ( CRP_BASEADDR ) + 0X00000278 )

#define CRP_CHKR1_CLKB_CNT_VALUE_SHIFT   0
#define CRP_CHKR1_CLKB_CNT_VALUE_WIDTH   32
#define CRP_CHKR1_CLKB_CNT_VALUE_MASK    0XFFFFFFFF

/**
 * Register: CRP_CHKR1_CTRL
 */
#define CRP_CHKR1_CTRL    ( ( CRP_BASEADDR ) + 0X0000027C )

#define CRP_CHKR1_CTRL_IDLE_STATE_SHIFT   10
#define CRP_CHKR1_CTRL_IDLE_STATE_WIDTH   1
#define CRP_CHKR1_CTRL_IDLE_STATE_MASK    0X00000400

#define CRP_CHKR1_CTRL_START_SINGLE_SHIFT   9
#define CRP_CHKR1_CTRL_START_SINGLE_WIDTH   1
#define CRP_CHKR1_CTRL_START_SINGLE_MASK    0X00000200

#define CRP_CHKR1_CTRL_START_CONTINUOUS_SHIFT   8
#define CRP_CHKR1_CTRL_START_CONTINUOUS_WIDTH   1
#define CRP_CHKR1_CTRL_START_CONTINUOUS_MASK    0X00000100

#define CRP_CHKR1_CTRL_CLKB_MUX_CTRL_SHIFT   6
#define CRP_CHKR1_CTRL_CLKB_MUX_CTRL_WIDTH   1
#define CRP_CHKR1_CTRL_CLKB_MUX_CTRL_MASK    0X00000040

#define CRP_CHKR1_CTRL_CLKA_MUX_CTRL_SHIFT   1
#define CRP_CHKR1_CTRL_CLKA_MUX_CTRL_WIDTH   4
#define CRP_CHKR1_CTRL_CLKA_MUX_CTRL_MASK    0X0000001E

#define CRP_CHKR1_CTRL_ENABLE_SHIFT   0
#define CRP_CHKR1_CTRL_ENABLE_WIDTH   1
#define CRP_CHKR1_CTRL_ENABLE_MASK    0X00000001

/**
 * Register: CRP_CHKR2_CLKA_UPPER
 */
#define CRP_CHKR2_CLKA_UPPER    ( ( CRP_BASEADDR ) + 0X00000280 )

#define CRP_CHKR2_CLKA_UPPER_THRSHLD_SHIFT   0
#define CRP_CHKR2_CLKA_UPPER_THRSHLD_WIDTH   32
#define CRP_CHKR2_CLKA_UPPER_THRSHLD_MASK    0XFFFFFFFF

/**
 * Register: CRP_CHKR2_CLKA_LOWER
 */
#define CRP_CHKR2_CLKA_LOWER    ( ( CRP_BASEADDR ) + 0X00000284 )

#define CRP_CHKR2_CLKA_LOWER_THRSHLD_SHIFT   0
#define CRP_CHKR2_CLKA_LOWER_THRSHLD_WIDTH   32
#define CRP_CHKR2_CLKA_LOWER_THRSHLD_MASK    0XFFFFFFFF

/**
 * Register: CRP_CHKR2_CLKB_CNT
 */
#define CRP_CHKR2_CLKB_CNT    ( ( CRP_BASEADDR ) + 0X00000288 )

#define CRP_CHKR2_CLKB_CNT_VALUE_SHIFT   0
#define CRP_CHKR2_CLKB_CNT_VALUE_WIDTH   32
#define CRP_CHKR2_CLKB_CNT_VALUE_MASK    0XFFFFFFFF

/**
 * Register: CRP_CHKR2_CTRL
 */
#define CRP_CHKR2_CTRL    ( ( CRP_BASEADDR ) + 0X0000028C )

#define CRP_CHKR2_CTRL_IDLE_STATE_SHIFT   10
#define CRP_CHKR2_CTRL_IDLE_STATE_WIDTH   1
#define CRP_CHKR2_CTRL_IDLE_STATE_MASK    0X00000400

#define CRP_CHKR2_CTRL_START_SINGLE_SHIFT   9
#define CRP_CHKR2_CTRL_START_SINGLE_WIDTH   1
#define CRP_CHKR2_CTRL_START_SINGLE_MASK    0X00000200

#define CRP_CHKR2_CTRL_START_CONTINUOUS_SHIFT   8
#define CRP_CHKR2_CTRL_START_CONTINUOUS_WIDTH   1
#define CRP_CHKR2_CTRL_START_CONTINUOUS_MASK    0X00000100

#define CRP_CHKR2_CTRL_CLKB_MUX_CTRL_SHIFT   6
#define CRP_CHKR2_CTRL_CLKB_MUX_CTRL_WIDTH   1
#define CRP_CHKR2_CTRL_CLKB_MUX_CTRL_MASK    0X00000040

#define CRP_CHKR2_CTRL_CLKA_MUX_CTRL_SHIFT   1
#define CRP_CHKR2_CTRL_CLKA_MUX_CTRL_WIDTH   4
#define CRP_CHKR2_CTRL_CLKA_MUX_CTRL_MASK    0X0000001E

#define CRP_CHKR2_CTRL_ENABLE_SHIFT   0
#define CRP_CHKR2_CTRL_ENABLE_WIDTH   1
#define CRP_CHKR2_CTRL_ENABLE_MASK    0X00000001

/**
 * Register: CRP_CHKR3_CLKA_UPPER
 */
#define CRP_CHKR3_CLKA_UPPER    ( ( CRP_BASEADDR ) + 0X00000290 )

#define CRP_CHKR3_CLKA_UPPER_THRSHLD_SHIFT   0
#define CRP_CHKR3_CLKA_UPPER_THRSHLD_WIDTH   32
#define CRP_CHKR3_CLKA_UPPER_THRSHLD_MASK    0XFFFFFFFF

/**
 * Register: CRP_CHKR3_CLKA_LOWER
 */
#define CRP_CHKR3_CLKA_LOWER    ( ( CRP_BASEADDR ) + 0X00000294 )

#define CRP_CHKR3_CLKA_LOWER_THRSHLD_SHIFT   0
#define CRP_CHKR3_CLKA_LOWER_THRSHLD_WIDTH   32
#define CRP_CHKR3_CLKA_LOWER_THRSHLD_MASK    0XFFFFFFFF

/**
 * Register: CRP_CHKR3_CLKB_CNT
 */
#define CRP_CHKR3_CLKB_CNT    ( ( CRP_BASEADDR ) + 0X00000298 )

#define CRP_CHKR3_CLKB_CNT_VALUE_SHIFT   0
#define CRP_CHKR3_CLKB_CNT_VALUE_WIDTH   32
#define CRP_CHKR3_CLKB_CNT_VALUE_MASK    0XFFFFFFFF

/**
 * Register: CRP_CHKR3_CTRL
 */
#define CRP_CHKR3_CTRL    ( ( CRP_BASEADDR ) + 0X0000029C )

#define CRP_CHKR3_CTRL_IDLE_STATE_SHIFT   10
#define CRP_CHKR3_CTRL_IDLE_STATE_WIDTH   1
#define CRP_CHKR3_CTRL_IDLE_STATE_MASK    0X00000400

#define CRP_CHKR3_CTRL_START_SINGLE_SHIFT   9
#define CRP_CHKR3_CTRL_START_SINGLE_WIDTH   1
#define CRP_CHKR3_CTRL_START_SINGLE_MASK    0X00000200

#define CRP_CHKR3_CTRL_START_CONTINUOUS_SHIFT   8
#define CRP_CHKR3_CTRL_START_CONTINUOUS_WIDTH   1
#define CRP_CHKR3_CTRL_START_CONTINUOUS_MASK    0X00000100

#define CRP_CHKR3_CTRL_CLKB_MUX_CTRL_SHIFT   6
#define CRP_CHKR3_CTRL_CLKB_MUX_CTRL_WIDTH   1
#define CRP_CHKR3_CTRL_CLKB_MUX_CTRL_MASK    0X00000040

#define CRP_CHKR3_CTRL_CLKA_MUX_CTRL_SHIFT   1
#define CRP_CHKR3_CTRL_CLKA_MUX_CTRL_WIDTH   4
#define CRP_CHKR3_CTRL_CLKA_MUX_CTRL_MASK    0X0000001E

#define CRP_CHKR3_CTRL_ENABLE_SHIFT   0
#define CRP_CHKR3_CTRL_ENABLE_WIDTH   1
#define CRP_CHKR3_CTRL_ENABLE_MASK    0X00000001

/**
 * Register: CRP_CHKR4_CLKA_UPPER
 */
#define CRP_CHKR4_CLKA_UPPER    ( ( CRP_BASEADDR ) + 0X000002A0 )

#define CRP_CHKR4_CLKA_UPPER_THRSHLD_SHIFT   0
#define CRP_CHKR4_CLKA_UPPER_THRSHLD_WIDTH   32
#define CRP_CHKR4_CLKA_UPPER_THRSHLD_MASK    0XFFFFFFFF

/**
 * Register: CRP_CHKR4_CLKA_LOWER
 */
#define CRP_CHKR4_CLKA_LOWER    ( ( CRP_BASEADDR ) + 0X000002A4 )

#define CRP_CHKR4_CLKA_LOWER_THRSHLD_SHIFT   0
#define CRP_CHKR4_CLKA_LOWER_THRSHLD_WIDTH   32
#define CRP_CHKR4_CLKA_LOWER_THRSHLD_MASK    0XFFFFFFFF

/**
 * Register: CRP_CHKR4_CLKB_CNT
 */
#define CRP_CHKR4_CLKB_CNT    ( ( CRP_BASEADDR ) + 0X000002A8 )

#define CRP_CHKR4_CLKB_CNT_VALUE_SHIFT   0
#define CRP_CHKR4_CLKB_CNT_VALUE_WIDTH   32
#define CRP_CHKR4_CLKB_CNT_VALUE_MASK    0XFFFFFFFF

/**
 * Register: CRP_CHKR4_CTRL
 */
#define CRP_CHKR4_CTRL    ( ( CRP_BASEADDR ) + 0X000002AC )

#define CRP_CHKR4_CTRL_IDLE_STATE_SHIFT   10
#define CRP_CHKR4_CTRL_IDLE_STATE_WIDTH   1
#define CRP_CHKR4_CTRL_IDLE_STATE_MASK    0X00000400

#define CRP_CHKR4_CTRL_START_SINGLE_SHIFT   9
#define CRP_CHKR4_CTRL_START_SINGLE_WIDTH   1
#define CRP_CHKR4_CTRL_START_SINGLE_MASK    0X00000200

#define CRP_CHKR4_CTRL_START_CONTINUOUS_SHIFT   8
#define CRP_CHKR4_CTRL_START_CONTINUOUS_WIDTH   1
#define CRP_CHKR4_CTRL_START_CONTINUOUS_MASK    0X00000100

#define CRP_CHKR4_CTRL_CLKB_MUX_CTRL_SHIFT   6
#define CRP_CHKR4_CTRL_CLKB_MUX_CTRL_WIDTH   1
#define CRP_CHKR4_CTRL_CLKB_MUX_CTRL_MASK    0X00000040

#define CRP_CHKR4_CTRL_CLKA_MUX_CTRL_SHIFT   1
#define CRP_CHKR4_CTRL_CLKA_MUX_CTRL_WIDTH   4
#define CRP_CHKR4_CTRL_CLKA_MUX_CTRL_MASK    0X0000001E

#define CRP_CHKR4_CTRL_ENABLE_SHIFT   0
#define CRP_CHKR4_CTRL_ENABLE_WIDTH   1
#define CRP_CHKR4_CTRL_ENABLE_MASK    0X00000001

/**
 * Register: CRP_CHKR5_CLKA_UPPER
 */
#define CRP_CHKR5_CLKA_UPPER    ( ( CRP_BASEADDR ) + 0X000002B0 )

#define CRP_CHKR5_CLKA_UPPER_THRSHLD_SHIFT   0
#define CRP_CHKR5_CLKA_UPPER_THRSHLD_WIDTH   32
#define CRP_CHKR5_CLKA_UPPER_THRSHLD_MASK    0XFFFFFFFF

/**
 * Register: CRP_CHKR5_CLKA_LOWER
 */
#define CRP_CHKR5_CLKA_LOWER    ( ( CRP_BASEADDR ) + 0X000002B4 )

#define CRP_CHKR5_CLKA_LOWER_THRSHLD_SHIFT   0
#define CRP_CHKR5_CLKA_LOWER_THRSHLD_WIDTH   32
#define CRP_CHKR5_CLKA_LOWER_THRSHLD_MASK    0XFFFFFFFF

/**
 * Register: CRP_CHKR5_CLKB_CNT
 */
#define CRP_CHKR5_CLKB_CNT    ( ( CRP_BASEADDR ) + 0X000002B8 )

#define CRP_CHKR5_CLKB_CNT_VALUE_SHIFT   0
#define CRP_CHKR5_CLKB_CNT_VALUE_WIDTH   32
#define CRP_CHKR5_CLKB_CNT_VALUE_MASK    0XFFFFFFFF

/**
 * Register: CRP_CHKR5_CTRL
 */
#define CRP_CHKR5_CTRL    ( ( CRP_BASEADDR ) + 0X000002BC )

#define CRP_CHKR5_CTRL_IDLE_STATE_SHIFT   10
#define CRP_CHKR5_CTRL_IDLE_STATE_WIDTH   1
#define CRP_CHKR5_CTRL_IDLE_STATE_MASK    0X00000400

#define CRP_CHKR5_CTRL_START_SINGLE_SHIFT   9
#define CRP_CHKR5_CTRL_START_SINGLE_WIDTH   1
#define CRP_CHKR5_CTRL_START_SINGLE_MASK    0X00000200

#define CRP_CHKR5_CTRL_START_CONTINUOUS_SHIFT   8
#define CRP_CHKR5_CTRL_START_CONTINUOUS_WIDTH   1
#define CRP_CHKR5_CTRL_START_CONTINUOUS_MASK    0X00000100

#define CRP_CHKR5_CTRL_CLKB_MUX_CTRL_SHIFT   6
#define CRP_CHKR5_CTRL_CLKB_MUX_CTRL_WIDTH   1
#define CRP_CHKR5_CTRL_CLKB_MUX_CTRL_MASK    0X00000040

#define CRP_CHKR5_CTRL_CLKA_MUX_CTRL_SHIFT   1
#define CRP_CHKR5_CTRL_CLKA_MUX_CTRL_WIDTH   4
#define CRP_CHKR5_CTRL_CLKA_MUX_CTRL_MASK    0X0000001E

#define CRP_CHKR5_CTRL_ENABLE_SHIFT   0
#define CRP_CHKR5_CTRL_ENABLE_WIDTH   1
#define CRP_CHKR5_CTRL_ENABLE_MASK    0X00000001

/**
 * Register: CRP_CHKR6_CLKA_UPPER
 */
#define CRP_CHKR6_CLKA_UPPER    ( ( CRP_BASEADDR ) + 0X000002C0 )

#define CRP_CHKR6_CLKA_UPPER_THRSHLD_SHIFT   0
#define CRP_CHKR6_CLKA_UPPER_THRSHLD_WIDTH   32
#define CRP_CHKR6_CLKA_UPPER_THRSHLD_MASK    0XFFFFFFFF

/**
 * Register: CRP_CHKR6_CLKA_LOWER
 */
#define CRP_CHKR6_CLKA_LOWER    ( ( CRP_BASEADDR ) + 0X000002C4 )

#define CRP_CHKR6_CLKA_LOWER_THRSHLD_SHIFT   0
#define CRP_CHKR6_CLKA_LOWER_THRSHLD_WIDTH   32
#define CRP_CHKR6_CLKA_LOWER_THRSHLD_MASK    0XFFFFFFFF

/**
 * Register: CRP_CHKR6_CLKB_CNT
 */
#define CRP_CHKR6_CLKB_CNT    ( ( CRP_BASEADDR ) + 0X000002C8 )

#define CRP_CHKR6_CLKB_CNT_VALUE_SHIFT   0
#define CRP_CHKR6_CLKB_CNT_VALUE_WIDTH   32
#define CRP_CHKR6_CLKB_CNT_VALUE_MASK    0XFFFFFFFF

/**
 * Register: CRP_CHKR6_CTRL
 */
#define CRP_CHKR6_CTRL    ( ( CRP_BASEADDR ) + 0X000002CC )

#define CRP_CHKR6_CTRL_IDLE_STATE_SHIFT   10
#define CRP_CHKR6_CTRL_IDLE_STATE_WIDTH   1
#define CRP_CHKR6_CTRL_IDLE_STATE_MASK    0X00000400

#define CRP_CHKR6_CTRL_START_SINGLE_SHIFT   9
#define CRP_CHKR6_CTRL_START_SINGLE_WIDTH   1
#define CRP_CHKR6_CTRL_START_SINGLE_MASK    0X00000200

#define CRP_CHKR6_CTRL_START_CONTINUOUS_SHIFT   8
#define CRP_CHKR6_CTRL_START_CONTINUOUS_WIDTH   1
#define CRP_CHKR6_CTRL_START_CONTINUOUS_MASK    0X00000100

#define CRP_CHKR6_CTRL_CLKB_MUX_CTRL_SHIFT   6
#define CRP_CHKR6_CTRL_CLKB_MUX_CTRL_WIDTH   1
#define CRP_CHKR6_CTRL_CLKB_MUX_CTRL_MASK    0X00000040

#define CRP_CHKR6_CTRL_CLKA_MUX_CTRL_SHIFT   1
#define CRP_CHKR6_CTRL_CLKA_MUX_CTRL_WIDTH   4
#define CRP_CHKR6_CTRL_CLKA_MUX_CTRL_MASK    0X0000001E

#define CRP_CHKR6_CTRL_ENABLE_SHIFT   0
#define CRP_CHKR6_CTRL_ENABLE_WIDTH   1
#define CRP_CHKR6_CTRL_ENABLE_MASK    0X00000001

/**
 * Register: CRP_CHKR7_CLKA_UPPER
 */
#define CRP_CHKR7_CLKA_UPPER    ( ( CRP_BASEADDR ) + 0X000002D0 )

#define CRP_CHKR7_CLKA_UPPER_THRSHLD_SHIFT   0
#define CRP_CHKR7_CLKA_UPPER_THRSHLD_WIDTH   32
#define CRP_CHKR7_CLKA_UPPER_THRSHLD_MASK    0XFFFFFFFF

/**
 * Register: CRP_CHKR7_CLKA_LOWER
 */
#define CRP_CHKR7_CLKA_LOWER    ( ( CRP_BASEADDR ) + 0X000002D4 )

#define CRP_CHKR7_CLKA_LOWER_THRSHLD_SHIFT   0
#define CRP_CHKR7_CLKA_LOWER_THRSHLD_WIDTH   32
#define CRP_CHKR7_CLKA_LOWER_THRSHLD_MASK    0XFFFFFFFF

/**
 * Register: CRP_CHKR7_CLKB_CNT
 */
#define CRP_CHKR7_CLKB_CNT    ( ( CRP_BASEADDR ) + 0X000002D8 )

#define CRP_CHKR7_CLKB_CNT_VALUE_SHIFT   0
#define CRP_CHKR7_CLKB_CNT_VALUE_WIDTH   32
#define CRP_CHKR7_CLKB_CNT_VALUE_MASK    0XFFFFFFFF

/**
 * Register: CRP_CHKR7_CTRL
 */
#define CRP_CHKR7_CTRL    ( ( CRP_BASEADDR ) + 0X000002DC )

#define CRP_CHKR7_CTRL_IDLE_STATE_SHIFT   10
#define CRP_CHKR7_CTRL_IDLE_STATE_WIDTH   1
#define CRP_CHKR7_CTRL_IDLE_STATE_MASK    0X00000400

#define CRP_CHKR7_CTRL_START_SINGLE_SHIFT   9
#define CRP_CHKR7_CTRL_START_SINGLE_WIDTH   1
#define CRP_CHKR7_CTRL_START_SINGLE_MASK    0X00000200

#define CRP_CHKR7_CTRL_START_CONTINUOUS_SHIFT   8
#define CRP_CHKR7_CTRL_START_CONTINUOUS_WIDTH   1
#define CRP_CHKR7_CTRL_START_CONTINUOUS_MASK    0X00000100

#define CRP_CHKR7_CTRL_CLKB_MUX_CTRL_SHIFT   6
#define CRP_CHKR7_CTRL_CLKB_MUX_CTRL_WIDTH   1
#define CRP_CHKR7_CTRL_CLKB_MUX_CTRL_MASK    0X00000040

#define CRP_CHKR7_CTRL_CLKA_MUX_CTRL_SHIFT   1
#define CRP_CHKR7_CTRL_CLKA_MUX_CTRL_WIDTH   4
#define CRP_CHKR7_CTRL_CLKA_MUX_CTRL_MASK    0X0000001E

#define CRP_CHKR7_CTRL_ENABLE_SHIFT   0
#define CRP_CHKR7_CTRL_ENABLE_WIDTH   1
#define CRP_CHKR7_CTRL_ENABLE_MASK    0X00000001

/**
 * Register: CRP_RST_QSPI
 */
#define CRP_RST_QSPI    ( ( CRP_BASEADDR ) + 0X00000300 )

#define CRP_RST_QSPI_RESET_SHIFT   0
#define CRP_RST_QSPI_RESET_WIDTH   1
#define CRP_RST_QSPI_RESET_MASK    0X00000001

/**
 * Register: CRP_RST_OSPI
 */
#define CRP_RST_OSPI    ( ( CRP_BASEADDR ) + 0X00000304 )

#define CRP_RST_OSPI_RESET_SHIFT   0
#define CRP_RST_OSPI_RESET_WIDTH   1
#define CRP_RST_OSPI_RESET_MASK    0X00000001

/**
 * Register: CRP_RST_SDIO0
 */
#define CRP_RST_SDIO0    ( ( CRP_BASEADDR ) + 0X00000308 )

#define CRP_RST_SDIO0_RESET_SHIFT   0
#define CRP_RST_SDIO0_RESET_WIDTH   1
#define CRP_RST_SDIO0_RESET_MASK    0X00000001

/**
 * Register: CRP_RST_SDIO1
 */
#define CRP_RST_SDIO1    ( ( CRP_BASEADDR ) + 0X0000030C )

#define CRP_RST_SDIO1_RESET_SHIFT   0
#define CRP_RST_SDIO1_RESET_WIDTH   1
#define CRP_RST_SDIO1_RESET_MASK    0X00000001

/**
 * Register: CRP_RST_I2C
 */
#define CRP_RST_I2C    ( ( CRP_BASEADDR ) + 0X00000314 )

#define CRP_RST_I2C_RESET_SHIFT   0
#define CRP_RST_I2C_RESET_WIDTH   1
#define CRP_RST_I2C_RESET_MASK    0X00000001

/**
 * Register: CRP_RST_GPIO
 */
#define CRP_RST_GPIO    ( ( CRP_BASEADDR ) + 0X00000318 )

#define CRP_RST_GPIO_RESET_SHIFT   0
#define CRP_RST_GPIO_RESET_WIDTH   1
#define CRP_RST_GPIO_RESET_MASK    0X00000001

/**
 * Register: CRP_RST_PS
 */
#define CRP_RST_PS    ( ( CRP_BASEADDR ) + 0X0000031C )

#define CRP_RST_PS_PMC_POR_SHIFT   7
#define CRP_RST_PS_PMC_POR_WIDTH   1
#define CRP_RST_PS_PMC_POR_MASK    0X00000080

#define CRP_RST_PS_PS_POR_SHIFT   6
#define CRP_RST_PS_PS_POR_WIDTH   1
#define CRP_RST_PS_PS_POR_MASK    0X00000040

#define CRP_RST_PS_PL_POR_SHIFT   5
#define CRP_RST_PS_PL_POR_WIDTH   1
#define CRP_RST_PS_PL_POR_MASK    0X00000020

#define CRP_RST_PS_PMC_SRST_SHIFT   3
#define CRP_RST_PS_PMC_SRST_WIDTH   1
#define CRP_RST_PS_PMC_SRST_MASK    0X00000008

#define CRP_RST_PS_PS_SRST_SHIFT   2
#define CRP_RST_PS_PS_SRST_WIDTH   1
#define CRP_RST_PS_PS_SRST_MASK    0X00000004

#define CRP_RST_PS_PL_SRST_SHIFT   1
#define CRP_RST_PS_PL_SRST_WIDTH   1
#define CRP_RST_PS_PL_SRST_MASK    0X00000002

/**
 * Register: CRP_RST_NONPS
 */
#define CRP_RST_NONPS    ( ( CRP_BASEADDR ) + 0X00000320 )

#define CRP_RST_NONPS_NOC_RESET_SHIFT   6
#define CRP_RST_NONPS_NOC_RESET_WIDTH   1
#define CRP_RST_NONPS_NOC_RESET_MASK    0X00000040

#define CRP_RST_NONPS_NOC_POR_SHIFT   5
#define CRP_RST_NONPS_NOC_POR_WIDTH   1
#define CRP_RST_NONPS_NOC_POR_MASK    0X00000020

#define CRP_RST_NONPS_NPI_RESET_SHIFT   4
#define CRP_RST_NONPS_NPI_RESET_WIDTH   1
#define CRP_RST_NONPS_NPI_RESET_MASK    0X00000010

#define CRP_RST_NONPS_SYS_RST_1_SHIFT   2
#define CRP_RST_NONPS_SYS_RST_1_WIDTH   1
#define CRP_RST_NONPS_SYS_RST_1_MASK    0X00000004

#define CRP_RST_NONPS_SYS_RST_2_SHIFT   1
#define CRP_RST_NONPS_SYS_RST_2_WIDTH   1
#define CRP_RST_NONPS_SYS_RST_2_MASK    0X00000002

#define CRP_RST_NONPS_SYS_RST_3_SHIFT   0
#define CRP_RST_NONPS_SYS_RST_3_WIDTH   1
#define CRP_RST_NONPS_SYS_RST_3_MASK    0X00000001

/**
 * Register: CRP_RST_SBI
 */
#define CRP_RST_SBI    ( ( CRP_BASEADDR ) + 0X00000324 )

#define CRP_RST_SBI_RESET_SHIFT   0
#define CRP_RST_SBI_RESET_WIDTH   1
#define CRP_RST_SBI_RESET_MASK    0X00000001

/**
 * Register: CRP_RST_PDMA
 */
#define CRP_RST_PDMA    ( ( CRP_BASEADDR ) + 0X00000328 )

#define CRP_RST_PDMA_RESET1_SHIFT   1
#define CRP_RST_PDMA_RESET1_WIDTH   1
#define CRP_RST_PDMA_RESET1_MASK    0X00000002

#define CRP_RST_PDMA_RESET0_SHIFT   0
#define CRP_RST_PDMA_RESET0_WIDTH   1
#define CRP_RST_PDMA_RESET0_MASK    0X00000001

/**
 * Register: CRP_RST_SYSMON
 */
#define CRP_RST_SYSMON    ( ( CRP_BASEADDR ) + 0X0000032C )

#define CRP_RST_SYSMON_SEQ_RST_SHIFT   1
#define CRP_RST_SYSMON_SEQ_RST_WIDTH   1
#define CRP_RST_SYSMON_SEQ_RST_MASK    0X00000002

#define CRP_RST_SYSMON_CFG_RST_SHIFT   0
#define CRP_RST_SYSMON_CFG_RST_WIDTH   1
#define CRP_RST_SYSMON_CFG_RST_MASK    0X00000001

/**
 * Register: CRP_RST_PL
 */
#define CRP_RST_PL    ( ( CRP_BASEADDR ) + 0X00000330 )

#define CRP_RST_PL_RESET3_SHIFT   3
#define CRP_RST_PL_RESET3_WIDTH   1
#define CRP_RST_PL_RESET3_MASK    0X00000008

#define CRP_RST_PL_RESET2_SHIFT   2
#define CRP_RST_PL_RESET2_WIDTH   1
#define CRP_RST_PL_RESET2_MASK    0X00000004

#define CRP_RST_PL_RESET1_SHIFT   1
#define CRP_RST_PL_RESET1_WIDTH   1
#define CRP_RST_PL_RESET1_MASK    0X00000002

#define CRP_RST_PL_RESET0_SHIFT   0
#define CRP_RST_PL_RESET0_WIDTH   1
#define CRP_RST_PL_RESET0_MASK    0X00000001

/**
 * Register: CRP_RST_USB
 */
#define CRP_RST_USB    ( ( CRP_BASEADDR ) + 0X00000334 )

#define CRP_RST_USB_PHY_RST_SHIFT   0
#define CRP_RST_USB_PHY_RST_WIDTH   1
#define CRP_RST_USB_PHY_RST_MASK    0X00000001

/**
 * Register: CRP_RST_DBG
 */
#define CRP_RST_DBG    ( ( CRP_BASEADDR ) + 0X00000400 )

#define CRP_RST_DBG_DPC_SHIFT   1
#define CRP_RST_DBG_DPC_WIDTH   1
#define CRP_RST_DBG_DPC_MASK    0X00000002

#define CRP_RST_DBG_RESET_SHIFT   0
#define CRP_RST_DBG_RESET_WIDTH   1
#define CRP_RST_DBG_RESET_MASK    0X00000001

/**
 * Register: CRP_TEST_PATTERN_REF_CTRL
 */
#define CRP_TEST_PATTERN_REF_CTRL    ( ( CRP_BASEADDR ) + 0X000004F4 )

#define CRP_TEST_PATTERN_REF_CTRL_CLKACT_SHIFT   24
#define CRP_TEST_PATTERN_REF_CTRL_CLKACT_WIDTH   1
#define CRP_TEST_PATTERN_REF_CTRL_CLKACT_MASK    0X01000000

#define CRP_TEST_PATTERN_REF_CTRL_DIVISOR0_SHIFT   8
#define CRP_TEST_PATTERN_REF_CTRL_DIVISOR0_WIDTH   10
#define CRP_TEST_PATTERN_REF_CTRL_DIVISOR0_MASK    0X0003FF00

#define CRP_TEST_PATTERN_REF_CTRL_SRCSEL_SHIFT   0
#define CRP_TEST_PATTERN_REF_CTRL_SRCSEL_WIDTH   3
#define CRP_TEST_PATTERN_REF_CTRL_SRCSEL_MASK    0X00000007

/**
 * Register: CRP_DFT_OSC_REF_CTRL
 */
#define CRP_DFT_OSC_REF_CTRL    ( ( CRP_BASEADDR ) + 0X000004F8 )

#define CRP_DFT_OSC_REF_CTRL_CLKACT_SHIFT   24
#define CRP_DFT_OSC_REF_CTRL_CLKACT_WIDTH   1
#define CRP_DFT_OSC_REF_CTRL_CLKACT_MASK    0X01000000

#define CRP_DFT_OSC_REF_CTRL_DIVISOR0_SHIFT   8
#define CRP_DFT_OSC_REF_CTRL_DIVISOR0_WIDTH   10
#define CRP_DFT_OSC_REF_CTRL_DIVISOR0_MASK    0X0003FF00

#define CRP_DFT_OSC_REF_CTRL_SRCSEL_SHIFT   0
#define CRP_DFT_OSC_REF_CTRL_SRCSEL_WIDTH   3
#define CRP_DFT_OSC_REF_CTRL_SRCSEL_MASK    0X00000007

/**
 * Register: CRP_RCLK_CTRL
 */
#define CRP_RCLK_CTRL    ( ( CRP_BASEADDR ) + 0X000004FC )

#define CRP_RCLK_CTRL_CLKACT_SHIFT   8
#define CRP_RCLK_CTRL_CLKACT_WIDTH   6
#define CRP_RCLK_CTRL_CLKACT_MASK    0X00003F00

#define CRP_RCLK_CTRL_SELECT_SHIFT   0
#define CRP_RCLK_CTRL_SELECT_WIDTH   6
#define CRP_RCLK_CTRL_SELECT_MASK    0X0000003F

/**
 * Register: CRP_PMC_PL0_REF_CTRL
 */
#define CRP_PMC_PL0_REF_CTRL    ( ( CRP_BASEADDR ) + 0X000005C0 )

#define CRP_PMC_PL0_REF_CTRL_CLKACT_SHIFT   24
#define CRP_PMC_PL0_REF_CTRL_CLKACT_WIDTH   1
#define CRP_PMC_PL0_REF_CTRL_CLKACT_MASK    0X01000000

#define CRP_PMC_PL0_REF_CTRL_DIVISOR0_SHIFT   8
#define CRP_PMC_PL0_REF_CTRL_DIVISOR0_WIDTH   10
#define CRP_PMC_PL0_REF_CTRL_DIVISOR0_MASK    0X0003FF00

#define CRP_PMC_PL0_REF_CTRL_SRCSEL_SHIFT   0
#define CRP_PMC_PL0_REF_CTRL_SRCSEL_WIDTH   3
#define CRP_PMC_PL0_REF_CTRL_SRCSEL_MASK    0X00000007

/**
 * Register: CRP_PMC_PL1_REF_CTRL
 */
#define CRP_PMC_PL1_REF_CTRL    ( ( CRP_BASEADDR ) + 0X000005C4 )

#define CRP_PMC_PL1_REF_CTRL_CLKACT_SHIFT   24
#define CRP_PMC_PL1_REF_CTRL_CLKACT_WIDTH   1
#define CRP_PMC_PL1_REF_CTRL_CLKACT_MASK    0X01000000

#define CRP_PMC_PL1_REF_CTRL_DIVISOR0_SHIFT   8
#define CRP_PMC_PL1_REF_CTRL_DIVISOR0_WIDTH   10
#define CRP_PMC_PL1_REF_CTRL_DIVISOR0_MASK    0X0003FF00

#define CRP_PMC_PL1_REF_CTRL_SRCSEL_SHIFT   0
#define CRP_PMC_PL1_REF_CTRL_SRCSEL_WIDTH   3
#define CRP_PMC_PL1_REF_CTRL_SRCSEL_MASK    0X00000007

/**
 * Register: CRP_PMC_PL2_REF_CTRL
 */
#define CRP_PMC_PL2_REF_CTRL    ( ( CRP_BASEADDR ) + 0X000005C8 )

#define CRP_PMC_PL2_REF_CTRL_CLKACT_SHIFT   24
#define CRP_PMC_PL2_REF_CTRL_CLKACT_WIDTH   1
#define CRP_PMC_PL2_REF_CTRL_CLKACT_MASK    0X01000000

#define CRP_PMC_PL2_REF_CTRL_DIVISOR0_SHIFT   8
#define CRP_PMC_PL2_REF_CTRL_DIVISOR0_WIDTH   10
#define CRP_PMC_PL2_REF_CTRL_DIVISOR0_MASK    0X0003FF00

#define CRP_PMC_PL2_REF_CTRL_SRCSEL_SHIFT   0
#define CRP_PMC_PL2_REF_CTRL_SRCSEL_WIDTH   3
#define CRP_PMC_PL2_REF_CTRL_SRCSEL_MASK    0X00000007

/**
 * Register: CRP_PMC_PL3_REF_CTRL
 */
#define CRP_PMC_PL3_REF_CTRL    ( ( CRP_BASEADDR ) + 0X000005CC )

#define CRP_PMC_PL3_REF_CTRL_CLKACT_SHIFT   24
#define CRP_PMC_PL3_REF_CTRL_CLKACT_WIDTH   1
#define CRP_PMC_PL3_REF_CTRL_CLKACT_MASK    0X01000000

#define CRP_PMC_PL3_REF_CTRL_DIVISOR0_SHIFT   8
#define CRP_PMC_PL3_REF_CTRL_DIVISOR0_WIDTH   10
#define CRP_PMC_PL3_REF_CTRL_DIVISOR0_MASK    0X0003FF00

#define CRP_PMC_PL3_REF_CTRL_SRCSEL_SHIFT   0
#define CRP_PMC_PL3_REF_CTRL_SRCSEL_WIDTH   3
#define CRP_PMC_PL3_REF_CTRL_SRCSEL_MASK    0X00000007

/**
 * Register: CRP_PMC_PL0_THR_CTRL
 */
#define CRP_PMC_PL0_THR_CTRL    ( ( CRP_BASEADDR ) + 0X000005D0 )

#define CRP_PMC_PL0_THR_CTRL_CURR_VAL_SHIFT   16
#define CRP_PMC_PL0_THR_CTRL_CURR_VAL_WIDTH   16
#define CRP_PMC_PL0_THR_CTRL_CURR_VAL_MASK    0XFFFF0000

#define CRP_PMC_PL0_THR_CTRL_RUNNING_SHIFT   15
#define CRP_PMC_PL0_THR_CTRL_RUNNING_WIDTH   1
#define CRP_PMC_PL0_THR_CTRL_RUNNING_MASK    0X00008000

#define CRP_PMC_PL0_THR_CTRL_CPU_START_SHIFT   1
#define CRP_PMC_PL0_THR_CTRL_CPU_START_WIDTH   1
#define CRP_PMC_PL0_THR_CTRL_CPU_START_MASK    0X00000002

#define CRP_PMC_PL0_THR_CTRL_CNT_RST_SHIFT   0
#define CRP_PMC_PL0_THR_CTRL_CNT_RST_WIDTH   1
#define CRP_PMC_PL0_THR_CTRL_CNT_RST_MASK    0X00000001

/**
 * Register: CRP_PMC_PL0_THR_CNT
 */
#define CRP_PMC_PL0_THR_CNT    ( ( CRP_BASEADDR ) + 0X000005D4 )

#define CRP_PMC_PL0_THR_CNT_LAST_CNT_SHIFT   0
#define CRP_PMC_PL0_THR_CNT_LAST_CNT_WIDTH   16
#define CRP_PMC_PL0_THR_CNT_LAST_CNT_MASK    0X0000FFFF

/**
 * Register: CRP_PMC_PL1_THR_CTRL
 */
#define CRP_PMC_PL1_THR_CTRL    ( ( CRP_BASEADDR ) + 0X000005D8 )

#define CRP_PMC_PL1_THR_CTRL_CURR_VAL_SHIFT   16
#define CRP_PMC_PL1_THR_CTRL_CURR_VAL_WIDTH   16
#define CRP_PMC_PL1_THR_CTRL_CURR_VAL_MASK    0XFFFF0000

#define CRP_PMC_PL1_THR_CTRL_RUNNING_SHIFT   15
#define CRP_PMC_PL1_THR_CTRL_RUNNING_WIDTH   1
#define CRP_PMC_PL1_THR_CTRL_RUNNING_MASK    0X00008000

#define CRP_PMC_PL1_THR_CTRL_CPU_START_SHIFT   1
#define CRP_PMC_PL1_THR_CTRL_CPU_START_WIDTH   1
#define CRP_PMC_PL1_THR_CTRL_CPU_START_MASK    0X00000002

#define CRP_PMC_PL1_THR_CTRL_CNT_RST_SHIFT   0
#define CRP_PMC_PL1_THR_CTRL_CNT_RST_WIDTH   1
#define CRP_PMC_PL1_THR_CTRL_CNT_RST_MASK    0X00000001

/**
 * Register: CRP_PMC_PL1_THR_CNT
 */
#define CRP_PMC_PL1_THR_CNT    ( ( CRP_BASEADDR ) + 0X000005DC )

#define CRP_PMC_PL1_THR_CNT_LAST_CNT_SHIFT   0
#define CRP_PMC_PL1_THR_CNT_LAST_CNT_WIDTH   16
#define CRP_PMC_PL1_THR_CNT_LAST_CNT_MASK    0X0000FFFF

/**
 * Register: CRP_PMC_PL2_THR_CTRL
 */
#define CRP_PMC_PL2_THR_CTRL    ( ( CRP_BASEADDR ) + 0X000005E0 )

#define CRP_PMC_PL2_THR_CTRL_CURR_VAL_SHIFT   16
#define CRP_PMC_PL2_THR_CTRL_CURR_VAL_WIDTH   16
#define CRP_PMC_PL2_THR_CTRL_CURR_VAL_MASK    0XFFFF0000

#define CRP_PMC_PL2_THR_CTRL_RUNNING_SHIFT   15
#define CRP_PMC_PL2_THR_CTRL_RUNNING_WIDTH   1
#define CRP_PMC_PL2_THR_CTRL_RUNNING_MASK    0X00008000

#define CRP_PMC_PL2_THR_CTRL_CPU_START_SHIFT   1
#define CRP_PMC_PL2_THR_CTRL_CPU_START_WIDTH   1
#define CRP_PMC_PL2_THR_CTRL_CPU_START_MASK    0X00000002

#define CRP_PMC_PL2_THR_CTRL_CNT_RST_SHIFT   0
#define CRP_PMC_PL2_THR_CTRL_CNT_RST_WIDTH   1
#define CRP_PMC_PL2_THR_CTRL_CNT_RST_MASK    0X00000001

/**
 * Register: CRP_PMC_PL2_THR_CNT
 */
#define CRP_PMC_PL2_THR_CNT    ( ( CRP_BASEADDR ) + 0X000005E4 )

#define CRP_PMC_PL2_THR_CNT_LAST_CNT_SHIFT   0
#define CRP_PMC_PL2_THR_CNT_LAST_CNT_WIDTH   16
#define CRP_PMC_PL2_THR_CNT_LAST_CNT_MASK    0X0000FFFF

/**
 * Register: CRP_PMC_PL3_THR_CTRL
 */
#define CRP_PMC_PL3_THR_CTRL    ( ( CRP_BASEADDR ) + 0X000005E8 )

#define CRP_PMC_PL3_THR_CTRL_CURR_VAL_SHIFT   16
#define CRP_PMC_PL3_THR_CTRL_CURR_VAL_WIDTH   16
#define CRP_PMC_PL3_THR_CTRL_CURR_VAL_MASK    0XFFFF0000

#define CRP_PMC_PL3_THR_CTRL_RUNNING_SHIFT   15
#define CRP_PMC_PL3_THR_CTRL_RUNNING_WIDTH   1
#define CRP_PMC_PL3_THR_CTRL_RUNNING_MASK    0X00008000

#define CRP_PMC_PL3_THR_CTRL_CPU_START_SHIFT   1
#define CRP_PMC_PL3_THR_CTRL_CPU_START_WIDTH   1
#define CRP_PMC_PL3_THR_CTRL_CPU_START_MASK    0X00000002

#define CRP_PMC_PL3_THR_CTRL_CNT_RST_SHIFT   0
#define CRP_PMC_PL3_THR_CTRL_CNT_RST_WIDTH   1
#define CRP_PMC_PL3_THR_CTRL_CNT_RST_MASK    0X00000001

/**
 * Register: CRP_PMC_PL3_THR_CNT
 */
#define CRP_PMC_PL3_THR_CNT    ( ( CRP_BASEADDR ) + 0X000005FC )

#define CRP_PMC_PL3_THR_CNT_LAST_CNT_SHIFT   0
#define CRP_PMC_PL3_THR_CNT_LAST_CNT_WIDTH   16
#define CRP_PMC_PL3_THR_CNT_LAST_CNT_MASK    0X0000FFFF

/**
 * Register: CRP_XOSC_SEL
 */
#define CRP_XOSC_SEL    ( ( CRP_BASEADDR ) + 0X00001000 )

#define CRP_XOSC_SEL_DFTOSC_SEL_SHIFT   0
#define CRP_XOSC_SEL_DFTOSC_SEL_WIDTH   3
#define CRP_XOSC_SEL_DFTOSC_SEL_MASK    0X00000007

/**
 * Register: CRP_SCAN_CLEAR_ENABLE
 */
#define CRP_SCAN_CLEAR_ENABLE    ( ( CRP_BASEADDR ) + 0X00001004 )

#define CRP_SCAN_CLEAR_ENABLE_FIRSTSTAGE_SHIFT   0
#define CRP_SCAN_CLEAR_ENABLE_FIRSTSTAGE_WIDTH   1
#define CRP_SCAN_CLEAR_ENABLE_FIRSTSTAGE_MASK    0X00000001

/**
 * Register: CRP_SCAN_CLEAR_START
 */
#define CRP_SCAN_CLEAR_START    ( ( CRP_BASEADDR ) + 0X00001008 )

#define CRP_SCAN_CLEAR_START_SECONDSTAGE_SHIFT   0
#define CRP_SCAN_CLEAR_START_SECONDSTAGE_WIDTH   1
#define CRP_SCAN_CLEAR_START_SECONDSTAGE_MASK    0X00000001

#ifdef __cplusplus
}
#endif


#endif /* _CRP_H_ */
