# Copyright (C) 2023 Advanced Micro Devices, Inc.  All rights reserved.
# SPDX-License-Identifier: MIT
set( CMAKE_EXPORT_COMPILE_COMMANDS ON)
set( CMAKE_INSTALL_MESSAGE LAZY)
set( CMAKE_C_COMPILER armr5-none-eabi-gcc )
set( CMAKE_CXX_COMPILER armr5-none-eabi-g++ )
set( CMAKE_C_COMPILER_LAUNCHER  )
set( CMAKE_CXX_COMPILER_LAUNCHER  )
set( CMAKE_ASM_COMPILER armr5-none-eabi-gcc )
set( CMAKE_AR armr5-none-eabi-ar CACHE FILEPATH "Archiver" )
set( CMAKE_SIZE armr5-none-eabi-size CACHE FILEPATH "Size" )
set( CMAKE_SYSTEM_PROCESSOR "cortexr5" )
set( CMAKE_MACHINE "Versal" )
set( CMAKE_SYSTEM_NAME "Generic" )
set( CMAKE_SPECS_FILE "$ENV{ESW_REPO}/scripts/specs/arm/Xilinx.spec" CACHE STRING "Specs file path for using CMAKE toolchain files" )
set( CMAKE_C_FLAGS "  -O0 -g -Wall -Wextra -fno-tree-loop-distribute-patterns -DSDT -DARMR5 -mfpu=vfpv3-d16 -mfloat-abi=hard -mcpu=cortex-r5 -specs=${CMAKE_SPECS_FILE} -I${CMAKE_INCLUDE_PATH} " CACHE STRING "CFLAGS" )
set( CMAKE_CXX_FLAGS " -O0 -g -Wall -Wextra -fno-tree-loop-distribute-patterns -DSDT -DARMR5 -mfpu=vfpv3-d16 -mfloat-abi=hard -mcpu=cortex-r5 -specs=${CMAKE_SPECS_FILE}" CACHE STRING "CFLAGS" )
set( CMAKE_ASM_FLAGS " -O0 -g -Wall -Wextra -fno-tree-loop-distribute-patterns -DSDT -DARMR5 -mfpu=vfpv3-d16 -mfloat-abi=hard -mcpu=cortex-r5 -specs=${CMAKE_SPECS_FILE} -I${CMAKE_INCLUDE_PATH}" CACHE STRING "ASM FLAGS" )
set( CMAKE_C_LINK_FLAGS " -mfpu=vfpv3-d16 -mfloat-abi=hard -mcpu=cortex-r5 -DARMR5 -mcpu=cortex-r5 -pipe -g -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -L${CMAKE_LIBRARY_PATH}" CACHE STRING "LDFLAGS" )
set( CMAKE_CXX_LINK_FLAGS " -mfpu=vfpv3-d16 -mfloat-abi=hard -mcpu=cortex-r5 -DARMR5 -mcpu=cortex-r5 -pipe -g -feliminate-unused-debug-types -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed" CACHE STRING "LDFLAGS" )
set( CMAKE_C_FLAGS_RELEASE "-DNDEBUG" CACHE STRING "Additional CFLAGS for release" )
set( CMAKE_CXX_FLAGS_RELEASE "-DNDEBUG" CACHE STRING "Additional CXXFLAGS for release" )
set( CMAKE_ASM_FLAGS_RELEASE "-DNDEBUG" CACHE STRING "Additional ASM FLAGS for release" )
