# Copyright (C) 2023 Advanced Micro Devices, Inc.  All rights reserved.
# SPDX-License-Identifier: MIT
set( CMAKE_EXPORT_COMPILE_COMMANDS ON)
set( CMAKE_TRY_COMPILE_PLATFORM_VARIABLES CMAKE_LIBRARY_PATH)
set( CMAKE_INSTALL_MESSAGE LAZY)
set( CMAKE_C_COMPILER mb-gcc )
set( CMAKE_CXX_COMPILER mb-g++ )
set( CMAKE_C_COMPILER_LAUNCHER  )
set( CMAKE_CXX_COMPILER_LAUNCHER  )
set( CMAKE_ASM_COMPILER mb-gcc )
set( CMAKE_AR mb-ar CACHE FILEPATH "Archiver" )
set( CMAKE_SIZE mb-size CACHE FILEPATH "Size" )
set( CMAKE_SYSTEM_PROCESSOR "microblaze" )
set( CMAKE_MACHINE "Versal" )
set( CMAKE_SYSTEM_NAME "Generic" )
set( CMAKE_HW_FLAGS "" )
set( CMAKE_COMPILER_LIB_PATH "" )
set( CMAKE_SPECS_FILE "$ENV{ESW_REPO}/scripts/specs/microblaze/Xilinx.spec" CACHE STRING "Specs file path for using CMAKE toolchain files" )
set( CMAKE_C_FLAGS " ${CMAKE_HW_FLAGS} -O2 -pipe -g -ffunction-sections -fdata-sections -Wall -Wextra -fno-tree-loop-distribute-patterns -DSDT  -specs=${CMAKE_SPECS_FILE} -I${CMAKE_INCLUDE_PATH}" CACHE STRING "CFLAGS" )
set( CMAKE_CXX_FLAGS " ${CMAKE_HW_FLAGS} -O2 -pipe -g -ffunction-sections -fdata-sections -Wall -Wextra -fno-tree-loop-distribute-patterns -specs=${CMAKE_SPECS_FILE}" CACHE STRING "CFLAGS" )
set( CMAKE_ASM_FLAGS " ${CMAKE_HW_FLAGS} -O2 -pipe -g  -DSDT -specs=${CMAKE_SPECS_FILE} -I${CMAKE_INCLUDE_PATH}" CACHE STRING "ASM FLAGS" )
set( CMAKE_C_LINK_FLAGS " ${CMAKE_HW_FLAGS} -Wl,-O2  -Wl,--as-needed  -L${CMAKE_LIBRARY_PATH} -L${CMAKE_COMPILER_LIB_PATH}" CACHE STRING "LDFLAGS" )
set( CMAKE_CXX_LINK_FLAGS " ${CMAKE_HW_FLAGS} -Wl,-O2  -Wl,--as-needed -L${CMAKE_LIBRARY_PATH} -L${CMAKE_COMPILER_LIB_PATH}" CACHE STRING "LDFLAGS" )
set( CMAKE_C_FLAGS_RELEASE "-DNDEBUG" CACHE STRING "Additional CFLAGS for release" )
set( CMAKE_CXX_FLAGS_RELEASE "-DNDEBUG" CACHE STRING "Additional CXXFLAGS for release" )
set( CMAKE_ASM_FLAGS_RELEASE "-DNDEBUG" CACHE STRING "Additional ASM FLAGS for release" )
