mbox
XMB_WRITE_REG_OFFSET
Mbox write register.
XMB_READ_REG_OFFSET
Mbox read register.
XMB_STATUS_REG_OFFSET
Mbox status reg.
Referenced by XMbox_GetStatus.
XMB_ERROR_REG_OFFSET
Mbox Error reg.
XMB_SIT_REG_OFFSET
Mbox send interrupt threshold register.
Referenced by XMbox_SetSendThreshold.
XMB_RIT_REG_OFFSET
Mbox receive interrupt threshold register.
Referenced by XMbox_SetReceiveThreshold.
XMB_IS_REG_OFFSET
Mbox interrupt status register.
Referenced by XMbox_ClearInterrupt, XMbox_GetInterruptStatus.
XMB_IE_REG_OFFSET
Mbox interrupt enable register.
Referenced by XMbox_GetInterruptEnable, XMbox_SetInterruptEnable.
XMB_IP_REG_OFFSET
Mbox interrupt pending register.
XMB_CTRL_REG_OFFSET
Mbox control register.
Referenced by XMbox_ResetFifos.
XMB_STATUS_FIFO_EMPTY
Receive FIFO is Empty.
XMB_STATUS_FIFO_FULL
Send FIFO is Full.
XMB_STATUS_STA
Send FIFO Threshold Status.
XMB_STATUS_RTA
Receive FIFO Threshold Status.
XMB_IX_STA
Send Threshold Active, when the number of Send FIFO entries is less than and equal to Send Interrupt Threshold.
XMB_IX_RTA
Receive Threshold Active, when the number of Receive FIFO entries is greater than Receive Interrupt Threshold.
XMB_IX_ERR
Mailbox Error, when read on empty or write on full.
XMB_ERROR_FIFO_EMPTY
Receive FIFO is Empty.
XMB_ERROR_FIFO_FULL
Send FIFO is Full.
XMB_CTRL_RESET_SEND_FIFO
Clear Send FIFO.
Referenced by XMbox_ResetFifos.
XMB_CTRL_RESET_RECV_FIFO
Clear Receive FIFO.
Referenced by XMbox_ResetFifos.
XMbox_Config XMbox_ConfigTable[][]
XMbox_Config XMbox_ConfigTable[][]
int XMbox_CfgInitialize(XMbox *InstancePtr, XMbox_Config *ConfigPtr, UINTPTR EffectiveAddress)
Initializes a specific mailbox.
InstancePtr is a pointer to the XMbox instance to be worked on. ConfigPtr is the device configuration structure containing required HW build data. EffectiveAddress is the Physical address of the hardware in a Virtual Memory operating system environment. It is the Base Address in a stand alone environment. XST_SUCCESS if initialization was successful None.
References XMbox_Config::BaseAddress, XMbox::Config, XMbox::IsReady.
Referenced by MailboxExample, ProdCon.
int XMbox_Read(XMbox *InstancePtr, u32 *BufferPtr, u32 RequestedBytes, u32 *BytesRecvdPtr)
Reads requested bytes from the mailbox referenced by InstancePtr,into the buffer pointed to by the provided pointer.
The number of bytes must be a multiple of 4 (bytes). If not, the call will fail in an assert.This function is non blocking. InstancePtr is a pointer to the XMbox instance to be worked on. BufferPtr is the buffer to read the mailbox contents into, aligned to a word boundary. RequestedBytes is the number of bytes of data requested. BytesRecvdPtr is the memory that is updated with the number of bytes of data actually read. XST_SUCCESS on success.XST_NO_DATA ifthere was no data in the mailbox. On success, the number of bytes read is returned through the pointer. The call may return with fewer bytes placed in the buffer than requested (not including zero). This is not necessarily an error condition and indicates the amount of data that was currently available in the mailbox.None.
References XMbox_Config::BaseAddress, XMbox::Config, XMbox_Config::RecvID, XMbox_Config::UseFSL, XMbox_FSLIsEmpty, XMbox_FSLReadMBox, XMbox_IsEmptyHw, XMbox_ReadMBox.
Referenced by MailboxExample_Receive.
void XMbox_ReadBlocking(XMbox *InstancePtr, u32 *BufferPtr, u32 RequestedBytes)
Reads requested bytes from the mailbox referenced by InstancePtr,into the buffer pointed to by the provided pointer.
The number of bytes must be a multiple of 4 (bytes). If not, the call will fail in an assert. InstancePtr is a pointer to the XMbox instance to be worked on. BufferPtr is the buffer to read the mailbox contents into, aligned to a word boundary. RequestedBytes is the number of bytes of data requested. The call blocks until the number of bytes requested are available.
References XMbox_Config::BaseAddress, XMbox::Config, XMbox_Config::RecvID, XMbox_Config::UseFSL, XMbox_FSLIsEmpty, XMbox_FSLReadMBox, XMbox_IsEmptyHw, XMbox_ReadMBox.
Referenced by MailboxExample_Receive, ProdCon.
int XMbox_Write(XMbox *InstancePtr, u32 *BufferPtr, u32 RequestedBytes, u32 *BytesSentPtr)
Writes the requested bytes from the buffer pointed to by the provided pointer into the mailbox referenced by InstancePtr.The number of bytes must be a multiple of 4 (bytes).
If not, the call will fail in an assert.This function is non blocking. InstancePtr is a pointer to the XMbox instance to be worked on. BufferPtr is the source data buffer, aligned to a word boundary. RequestedBytes is the number of bytes requested to be written. BytesSentPtr points to memory which is updated with the actual number of bytes written, return value. - XST_SUCCESS on success. - XST_FIFO_NO_ROOM if the fifo was full. On success, the number of bytes successfully written into the destination mailbox is returned in the provided pointer. The call may return with zero. This is not necessarily an error condition and indicates that the mailbox is currently full.The provided buffer pointed to by BufferPtr must be aligned to a word boundary.
References XMbox_Config::BaseAddress, XMbox::Config, XMbox_Config::SendID, XMbox_Config::UseFSL, XMbox_FSLIsFull, XMbox_FSLWriteMBox, XMbox_IsFullHw, XMbox_WriteMBox.
Referenced by MailboxExample_Send.
void XMbox_WriteBlocking(XMbox *InstancePtr, u32 *BufferPtr, u32 RequestedBytes)
Writes the requested bytes from the buffer pointed to by the provided pointer into the mailbox referenced by InstancePtr.
The number of bytes must be a multiple of 4 (bytes). If not, the call will fail in an assert. InstancePtr is a pointer to the XMbox instance to be worked on. BufferPtr is the source data buffer, aligned to a word boundary. RequestedBytes is the number of bytes requested to be written. The call blocks until the number of bytes requested are written. The provided buffer pointed to by BufferPtr must be aligned to a word boundary.
References XMbox_Config::BaseAddress, XMbox::Config, XMbox_Config::SendID, XMbox_Config::UseFSL, XMbox_FSLIsFull, XMbox_FSLWriteMBox, XMbox_IsFullHw, XMbox_WriteMBox.
Referenced by MailboxExample_Send, ProdCon.
u32 XMbox_IsEmpty(XMbox *InstancePtr)
Checks to see if there is data available to be read.
InstancePtr is a pointer to the XMbox instance to be worked on. FALSE if there is data to be read.TRUE is there no data to be read. None.
References XMbox_Config::BaseAddress, XMbox::Config, XMbox_Config::RecvID, XMbox_Config::UseFSL, XMbox_FSLIsEmpty, XMbox_IsEmptyHw.
u32 XMbox_IsFull(XMbox *InstancePtr)
Checks to see if there is room in the write FIFO.
InstancePtr is a pointer to the XMbox instance to be worked on. FALSE if there is room in write FIFO.TRUE if there is room in write FIFO. None.
References XMbox_Config::BaseAddress, XMbox::Config, XMbox_Config::SendID, XMbox_Config::UseFSL, XMbox_FSLIsFull, XMbox_IsFullHw.
int XMbox_Flush(XMbox *InstancePtr)
Resets the mailbox FIFOs by emptying the READ FIFO and making sure the Error Status is zero.
InstancePtr is a pointer to the XMbox instance to be worked on. XST_SUCCESS on success.XST_FAILURE if there are any outstanding errors. Data from read FIFO is thrown away.
References XMbox_Config::BaseAddress, XMbox::Config, XMbox_Config::RecvID, XMbox_Config::UseFSL, XMbox_FSLIsEmpty, XMbox_FSLReadMBox, XMbox_IsEmptyHw, XMbox_ReadMBox.
void XMbox_ResetFifos(XMbox *InstancePtr)
Resets the mailbox FIFOs by clearing the READ and WRITE FIFOs using the hardware control register for memory mapped IO.
InstancePtr is a pointer to the XMbox instance to be worked on. Use XMbox_Flush instead for FSL based access.
References XMbox_Config::BaseAddress, XMbox::Config, XMbox_Config::UseFSL, XMB_CTRL_REG_OFFSET, XMB_CTRL_RESET_RECV_FIFO, XMB_CTRL_RESET_SEND_FIFO, XMbox_WriteReg.
void XMbox_SetInterruptEnable(XMbox *InstancePtr, u32 Mask)
Sets the interrupt enable register for this mailbox.
This function can only be used for Non-FSL interface. If not, the function will fail in an assert. InstancePtr is a pointer to the instance to be worked on. Mask is a logical OR of XMB_IX_* constants found in xmbox_hw.h. None.
References XMbox_Config::BaseAddress, XMbox::Config, XMbox_Config::UseFSL, XMB_IE_REG_OFFSET, XMbox_WriteReg.
u32 XMbox_GetInterruptEnable(XMbox *InstancePtr)
Retrieves the interrupt enable for the mailbox.
AND the result of this function with XMB_IX_* to determine which interrupts of this mailbox are enabled. This function can only be used for Non-FSL interface. If not, the function will fail in an assert. InstancePtr is a pointer to the instance to be worked on. Mask of interrupt bits made up of XMB_IX_* constants found in xmbox_hw.h. None.
References XMbox_Config::BaseAddress, XMbox::Config, XMbox_Config::UseFSL, XMB_IE_REG_OFFSET, XMbox_ReadReg.
u32 XMbox_GetInterruptStatus(XMbox *InstancePtr)
Retrieve the interrupt status for the mailbox.
AND the results of this function with XMB_IX_* to determine which interrupts are currently pending to the processor. This function can only be used for Non-FSL interface. If not, the function will fail in an assert. InstancePtr is a pointer to the instance to be worked on. Mask of interrupt bits made up of XMB_IX_* constants found in xmbox_hw.h.
References XMbox_Config::BaseAddress, XMbox::Config, XMbox_Config::UseFSL, XMB_IS_REG_OFFSET, XMbox_ReadReg.
void XMbox_ClearInterrupt(XMbox *InstancePtr, u32 Mask)
Clears pending interrupts with the provided mask.
This function should be called after the software has serviced the interrupts that are pending. This function clears the corresponding bits of the Interrupt Status Register. This function can only be used for Non-FSL interface. If not, the function will fail in an assert. InstancePtr is a pointer to the instance to be worked on. Mask is a logical OR of XMB_IX_* constants found in xmbox_hw.h. None.
References XMbox_Config::BaseAddress, XMbox::Config, XMbox_Config::UseFSL, XMB_IS_REG_OFFSET, XMbox_WriteReg.
void XMbox_SetSendThreshold(XMbox *InstancePtr, u32 Value)
Sets the Send Interrupt Threshold.
This function can only be used for Non-FSL interface. If not, the function will fail in an assert. InstancePtr is a pointer to the instance to be worked on. Value is a value to set for the SIT. Only lower Log2(FIFO Depth) bits are used. None.
References XMbox_Config::BaseAddress, XMbox::Config, XMbox_Config::UseFSL, XMB_SIT_REG_OFFSET, XMbox_WriteReg.
void XMbox_SetReceiveThreshold(XMbox *InstancePtr, u32 Value)
Set the Receive Interrupt Threshold.
This function can only be used for Non-FSL interface. If not, the function will fail in an assert. InstancePtr is a pointer to the instance to be worked on. Value is a value to set for the RIT. Only lower Log2(FIFO Depth) bits are used. None.
References XMbox_Config::BaseAddress, XMbox::Config, XMbox_Config::UseFSL, XMB_RIT_REG_OFFSET, XMbox_WriteReg.
u32 XMbox_GetStatus(XMbox *InstancePtr)
Returns Status register contents.
This function can only be used for Non-FSL interface. If not, the function will fail in an assert. InstancePtr is a pointer to the instance to be worked on. Value returns Status Register contents. None.
References XMbox_Config::BaseAddress, XMbox::Config, XMbox_Config::UseFSL, XMB_STATUS_REG_OFFSET, XMbox_ReadReg.
XMbox_Config * XMbox_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XMbox_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xmbox.h for the definition of XMbox_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XMbox_Config::Name.
Referenced by MailboxExample, ProdCon.
XMBOX_H
XMBOX_HW_H
XMbox_ReadReg
Read one of the mbox registers.
BaseAddress contains the base address of the mbox device. RegOffset contains the offset from the 1st register of the mbox to select the specific register of the mbox. The value read from the register, a 32 bit value. C-style signature: u32 XMbox_ReadReg(u32 BaseAddress, unsigned RegOffset);
Referenced by XMbox_GetInterruptEnable, XMbox_GetInterruptStatus, XMbox_GetStatus.
XMbox_WriteReg
Write a specified value to a register of a mbox.
BaseAddress is the base address of the mbox device. RegOffset contain the offset from the 1st register of the mbox to select the specific register of the mbox. ValueToWrite is the 32 bit value to be written to the register. None C-style signature: void XMbox_WriteReg(u32 BaseAddress, unsigned RegOffset, u32 ValueToWrite);
Referenced by XMbox_ClearInterrupt, XMbox_ResetFifos, XMbox_SetInterruptEnable, XMbox_SetReceiveThreshold, XMbox_SetSendThreshold.
XMbox_WriteMBox
Write the mbox write register.
BaseAddress contains the base address of the mbox device. ValueToWrite contains the value to be written. None. C-style signature: u32 XMbox_WriteMBox(u32 BaseAddress, u32 ValueToWrite);
Referenced by XMbox_Write, XMbox_WriteBlocking.
XMbox_ReadMBox
Read the mbox read FIFO.
BaseAddress contains the base address of the mbox device. The value read from the register, a 32 bit value. C-style signature: u32 XMbox_ReadMBox(u32 BaseAddress);
Referenced by XMbox_Flush, XMbox_Read, XMbox_ReadBlocking.
XMbox_IsEmptyHw
Checks if the Read FIFO is Empty.
BaseAddress contains the base address of the mbox device. TRUE if the FIFO is empty.FALSE if there is data to be read from the FIFO. C-style signature: u32 XMbox_IsEmptyHw(u32 BaseAddress);
Referenced by XMbox_Flush, XMbox_IsEmpty, XMbox_Read, XMbox_ReadBlocking.
XMbox_IsFullHw
Checks if there is room in the Write FIFO.
BaseAddress contains the base address of the mbox device. FALSE if there is room in FIFO,TRUE if there is no room in the FIFO C-style signature: u32 XMbox_IsFullHw(u32 BaseAddress);
Referenced by XMbox_IsFull, XMbox_Write, XMbox_WriteBlocking.
XMbox_FSLReadMBox
Stub implementation of XMbox_FSLReadMBox for non-MicroBlaze platforms.
ID is unused. Always returns 0. This is an empty stub to allow compilation on non-MicroBlaze platforms. FSL access is only available on MicroBlaze.
Referenced by XMbox_Flush, XMbox_Read, XMbox_ReadBlocking.
XMbox_FSLWriteMBox
Stub implementation of XMbox_FSLWriteMBox for non-MicroBlaze platforms.
ID is unused. ValueToWrite is unused. None. This is an empty stub to allow compilation on non-MicroBlaze platforms. FSL access is only available on MicroBlaze.
Referenced by XMbox_Write, XMbox_WriteBlocking.
XMbox_FSLIsEmpty
Stub implementation of XMbox_FSLIsEmpty for non-MicroBlaze platforms.
ID is unused. Always returns 0. This is an empty stub to allow compilation on non-MicroBlaze platforms. FSL access is only available on MicroBlaze.
Referenced by XMbox_Flush, XMbox_IsEmpty, XMbox_Read, XMbox_ReadBlocking.
XMbox_FSLIsFull
Stub implementation of XMbox_FSLIsFull for non-MicroBlaze platforms.
ID is unused. Always returns 0. This is an empty stub to allow compilation on non-MicroBlaze platforms. FSL access is only available on MicroBlaze.
Referenced by XMbox_IsFull, XMbox_Write, XMbox_WriteBlocking.