xmbox_intr_example.c
MY_CPU_ID
CPU ID definition for multi-processor systems.
Referenced by MailboxExample, main.
MSGSIZ
Size of the buffer for received message.
HELLO_SIZE
Size of the Hello Message.
Referenced by MailboxExample_Receive, MailboxExample_Send.
TIMEOUT_MAX_COUNT
Max count to wait for message.
Referenced by MailboxExample_Receive, MailboxExample_Wait.
MAILBOX_RIT
Mailbox receive interrupt threshold.
MAILBOX_SIT
Mailbox send interrupt threshold.
XMBOX_BASEADDRESS
printf
A smaller footprint printf.
Referenced by MailboxExample_Receive, MailboxExample_Send, MailboxExample_Wait, main.
XMbox Mbox
volatile int IntrCount
volatile int IntrSTACount
volatile int IntrRTACount
volatile int IntrERRCount
char RecvMsg[MSGSIZ][MSGSIZ]
u32 Temp1pad
char* ProducerHello
int MailboxExample(UINTPTR BaseAddress)
This function sends a message to and receives a message from the other processor.
It also uses the interrupt to check whether the other processor has started to send or receive. BaseAddress contains the base address of the device XST_SUCCESS if the test passesXST_FAILURE if the test fails In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XMbox_Config::BaseAddress, XMbox::Config, XMbox_Config::IntrId, XMbox_Config::IntrParent, MailboxExample_Receive, MailboxExample_Send, MailboxExample_Wait, MY_CPU_ID, XMbox_Config::UseFSL, XMbox_CfgInitialize, XMbox_LookupConfig.
Referenced by main.
int MailboxExample_Send(XMbox *MboxInstancePtr, int CPU_Id, int Blocking)
This function sends the hello message to the other processor.
MboxInstancePtr is the instance pointer for the XMbox. CPU_Id is the CPU ID for the program that is running on. Blocking is set to 1 for the send to block till the data is sent. XST_SUCCESS if the send succeedsXST_FAILURE if the send fails None
References HELLO_SIZE, printf, XMbox_Write, XMbox_WriteBlocking.
Referenced by MailboxExample.
int MailboxExample_Receive(XMbox *MboxInstancePtr, int CPU_Id, int Blocking)
This function receives a message from the other processor verifies it's the expected message.
MboxInstancePtr is the instance pointer for the XMbox. CPU_Id is the CPU ID for the program that is running on. Blocking is set to 1 for the receive to block till the data is received. XST_SUCCESS if the receive succeedsXST_FAILURE if the receive fails None
References HELLO_SIZE, printf, TIMEOUT_MAX_COUNT, XMbox_Read, XMbox_ReadBlocking.
Referenced by MailboxExample.
int MailboxExample_Wait(volatile int *Count, char *Name, int Threshold)
This function waits for a particular variable to exceed the threshold value.
If it waits too long, it will time out and returns XST_FAILURE. Count is the pointer to the variable to be examined. Name is the name of the variable. Threshold is the threshold value to be exceeded. XST_SUCCESS if the examined variable exceeds the threshold value.XST_FAILURE if the wait times out. None
References printf, TIMEOUT_MAX_COUNT.
Referenced by MailboxExample.
static void MailboxIntrHandler(void *CallbackRef)
This is the interrupt handler for this example.
CallbackRef is a callback reference passed in by the upper layer when setting the interrupt handler, and is passed back to the upper layer when the interrupt handler is called. None. None.
int main(void)
This function is the main function for the mailbox interrupt example.
XST_SUCCESS if successful, XST_FAILURE if unsuccessful None
References MailboxExample, MY_CPU_ID, printf.