xmbox.h
XMBOX_H
int XMbox_CfgInitialize(XMbox *InstancePtr, XMbox_Config *ConfigPtr, UINTPTR EffectiveAddress)
Initializes a specific mailbox.
InstancePtr is a pointer to the XMbox instance to be worked on. ConfigPtr is the device configuration structure containing required HW build data. EffectiveAddress is the Physical address of the hardware in a Virtual Memory operating system environment. It is the Base Address in a stand alone environment. XST_SUCCESS if initialization was successful None.
References XMbox_Config::BaseAddress, XMbox::Config, XMbox::IsReady.
Referenced by MailboxExample, ProdCon.
int XMbox_Read(XMbox *InstancePtr, u32 *BufferPtr, u32 RequestedBytes, u32 *BytesRecvdPtr)
Reads requested bytes from the mailbox referenced by InstancePtr,into the buffer pointed to by the provided pointer.
The number of bytes must be a multiple of 4 (bytes). If not, the call will fail in an assert.This function is non blocking. InstancePtr is a pointer to the XMbox instance to be worked on. BufferPtr is the buffer to read the mailbox contents into, aligned to a word boundary. RequestedBytes is the number of bytes of data requested. BytesRecvdPtr is the memory that is updated with the number of bytes of data actually read. XST_SUCCESS on success.XST_NO_DATA ifthere was no data in the mailbox. On success, the number of bytes read is returned through the pointer. The call may return with fewer bytes placed in the buffer than requested (not including zero). This is not necessarily an error condition and indicates the amount of data that was currently available in the mailbox.None.
References XMbox_Config::BaseAddress, XMbox::Config, XMbox_Config::RecvID, XMbox_Config::UseFSL, XMbox_FSLIsEmpty, XMbox_FSLReadMBox, XMbox_IsEmptyHw, XMbox_ReadMBox.
Referenced by MailboxExample_Receive.
void XMbox_ReadBlocking(XMbox *InstancePtr, u32 *BufferPtr, u32 RequestedBytes)
Reads requested bytes from the mailbox referenced by InstancePtr,into the buffer pointed to by the provided pointer.
The number of bytes must be a multiple of 4 (bytes). If not, the call will fail in an assert. InstancePtr is a pointer to the XMbox instance to be worked on. BufferPtr is the buffer to read the mailbox contents into, aligned to a word boundary. RequestedBytes is the number of bytes of data requested. The call blocks until the number of bytes requested are available.
References XMbox_Config::BaseAddress, XMbox::Config, XMbox_Config::RecvID, XMbox_Config::UseFSL, XMbox_FSLIsEmpty, XMbox_FSLReadMBox, XMbox_IsEmptyHw, XMbox_ReadMBox.
Referenced by MailboxExample_Receive, ProdCon.
int XMbox_Write(XMbox *InstancePtr, u32 *BufferPtr, u32 RequestedBytes, u32 *BytesSentPtr)
Writes the requested bytes from the buffer pointed to by the provided pointer into the mailbox referenced by InstancePtr.The number of bytes must be a multiple of 4 (bytes).
If not, the call will fail in an assert.This function is non blocking. InstancePtr is a pointer to the XMbox instance to be worked on. BufferPtr is the source data buffer, aligned to a word boundary. RequestedBytes is the number of bytes requested to be written. BytesSentPtr points to memory which is updated with the actual number of bytes written, return value. - XST_SUCCESS on success. - XST_FIFO_NO_ROOM if the fifo was full. On success, the number of bytes successfully written into the destination mailbox is returned in the provided pointer. The call may return with zero. This is not necessarily an error condition and indicates that the mailbox is currently full.The provided buffer pointed to by BufferPtr must be aligned to a word boundary.
References XMbox_Config::BaseAddress, XMbox::Config, XMbox_Config::SendID, XMbox_Config::UseFSL, XMbox_FSLIsFull, XMbox_FSLWriteMBox, XMbox_IsFullHw, XMbox_WriteMBox.
Referenced by MailboxExample_Send.
void XMbox_WriteBlocking(XMbox *InstancePtr, u32 *BufferPtr, u32 RequestedBytes)
Writes the requested bytes from the buffer pointed to by the provided pointer into the mailbox referenced by InstancePtr.
The number of bytes must be a multiple of 4 (bytes). If not, the call will fail in an assert. InstancePtr is a pointer to the XMbox instance to be worked on. BufferPtr is the source data buffer, aligned to a word boundary. RequestedBytes is the number of bytes requested to be written. The call blocks until the number of bytes requested are written. The provided buffer pointed to by BufferPtr must be aligned to a word boundary.
References XMbox_Config::BaseAddress, XMbox::Config, XMbox_Config::SendID, XMbox_Config::UseFSL, XMbox_FSLIsFull, XMbox_FSLWriteMBox, XMbox_IsFullHw, XMbox_WriteMBox.
Referenced by MailboxExample_Send, ProdCon.
u32 XMbox_IsEmpty(XMbox *InstancePtr)
Checks to see if there is data available to be read.
InstancePtr is a pointer to the XMbox instance to be worked on. FALSE if there is data to be read.TRUE is there no data to be read. None.
References XMbox_Config::BaseAddress, XMbox::Config, XMbox_Config::RecvID, XMbox_Config::UseFSL, XMbox_FSLIsEmpty, XMbox_IsEmptyHw.
u32 XMbox_IsFull(XMbox *InstancePtr)
Checks to see if there is room in the write FIFO.
InstancePtr is a pointer to the XMbox instance to be worked on. FALSE if there is room in write FIFO.TRUE if there is room in write FIFO. None.
References XMbox_Config::BaseAddress, XMbox::Config, XMbox_Config::SendID, XMbox_Config::UseFSL, XMbox_FSLIsFull, XMbox_IsFullHw.
int XMbox_Flush(XMbox *InstancePtr)
Resets the mailbox FIFOs by emptying the READ FIFO and making sure the Error Status is zero.
InstancePtr is a pointer to the XMbox instance to be worked on. XST_SUCCESS on success.XST_FAILURE if there are any outstanding errors. Data from read FIFO is thrown away.
References XMbox_Config::BaseAddress, XMbox::Config, XMbox_Config::RecvID, XMbox_Config::UseFSL, XMbox_FSLIsEmpty, XMbox_FSLReadMBox, XMbox_IsEmptyHw, XMbox_ReadMBox.
void XMbox_ResetFifos(XMbox *InstancePtr)
Resets the mailbox FIFOs by clearing the READ and WRITE FIFOs using the hardware control register for memory mapped IO.
InstancePtr is a pointer to the XMbox instance to be worked on. Use XMbox_Flush instead for FSL based access.
References XMbox_Config::BaseAddress, XMbox::Config, XMbox_Config::UseFSL, XMB_CTRL_REG_OFFSET, XMB_CTRL_RESET_RECV_FIFO, XMB_CTRL_RESET_SEND_FIFO, XMbox_WriteReg.
void XMbox_SetInterruptEnable(XMbox *InstancePtr, u32 Mask)
Sets the interrupt enable register for this mailbox.
This function can only be used for Non-FSL interface. If not, the function will fail in an assert. InstancePtr is a pointer to the instance to be worked on. Mask is a logical OR of XMB_IX_* constants found in xmbox_hw.h. None.
References XMbox_Config::BaseAddress, XMbox::Config, XMbox_Config::UseFSL, XMB_IE_REG_OFFSET, XMbox_WriteReg.
u32 XMbox_GetInterruptEnable(XMbox *InstancePtr)
Retrieves the interrupt enable for the mailbox.
AND the result of this function with XMB_IX_* to determine which interrupts of this mailbox are enabled. This function can only be used for Non-FSL interface. If not, the function will fail in an assert. InstancePtr is a pointer to the instance to be worked on. Mask of interrupt bits made up of XMB_IX_* constants found in xmbox_hw.h. None.
References XMbox_Config::BaseAddress, XMbox::Config, XMbox_Config::UseFSL, XMB_IE_REG_OFFSET, XMbox_ReadReg.
u32 XMbox_GetInterruptStatus(XMbox *InstancePtr)
Retrieve the interrupt status for the mailbox.
AND the results of this function with XMB_IX_* to determine which interrupts are currently pending to the processor. This function can only be used for Non-FSL interface. If not, the function will fail in an assert. InstancePtr is a pointer to the instance to be worked on. Mask of interrupt bits made up of XMB_IX_* constants found in xmbox_hw.h.
References XMbox_Config::BaseAddress, XMbox::Config, XMbox_Config::UseFSL, XMB_IS_REG_OFFSET, XMbox_ReadReg.
void XMbox_ClearInterrupt(XMbox *InstancePtr, u32 Mask)
Clears pending interrupts with the provided mask.
This function should be called after the software has serviced the interrupts that are pending. This function clears the corresponding bits of the Interrupt Status Register. This function can only be used for Non-FSL interface. If not, the function will fail in an assert. InstancePtr is a pointer to the instance to be worked on. Mask is a logical OR of XMB_IX_* constants found in xmbox_hw.h. None.
References XMbox_Config::BaseAddress, XMbox::Config, XMbox_Config::UseFSL, XMB_IS_REG_OFFSET, XMbox_WriteReg.
u32 XMbox_GetStatus(XMbox *InstancePtr)
Returns Status register contents.
This function can only be used for Non-FSL interface. If not, the function will fail in an assert. InstancePtr is a pointer to the instance to be worked on. Value returns Status Register contents. None.
References XMbox_Config::BaseAddress, XMbox::Config, XMbox_Config::UseFSL, XMB_STATUS_REG_OFFSET, XMbox_ReadReg.
void XMbox_SetSendThreshold(XMbox *InstancePtr, u32 Value)
Sets the Send Interrupt Threshold.
This function can only be used for Non-FSL interface. If not, the function will fail in an assert. InstancePtr is a pointer to the instance to be worked on. Value is a value to set for the SIT. Only lower Log2(FIFO Depth) bits are used. None.
References XMbox_Config::BaseAddress, XMbox::Config, XMbox_Config::UseFSL, XMB_SIT_REG_OFFSET, XMbox_WriteReg.
void XMbox_SetReceiveThreshold(XMbox *InstancePtr, u32 Value)
Set the Receive Interrupt Threshold.
This function can only be used for Non-FSL interface. If not, the function will fail in an assert. InstancePtr is a pointer to the instance to be worked on. Value is a value to set for the RIT. Only lower Log2(FIFO Depth) bits are used. None.
References XMbox_Config::BaseAddress, XMbox::Config, XMbox_Config::UseFSL, XMB_RIT_REG_OFFSET, XMbox_WriteReg.
XMbox_Config * XMbox_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XMbox_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xmbox.h for the definition of XMbox_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XMbox_Config::Name.
Referenced by MailboxExample, ProdCon.