xilpdi_apis
int XilPdi_ValidateChecksum(const void *Buffer, u32 Length)
This function is used to validate the word checksum for the Image Header table and Partition Headers.
Checksum is based on the formula Checksum = ~ (X1 + X2 + X3 + .... + Xn) Buffer pointer to the data for which checksum should be calculated Length of the buffer for which checksum should be calculated. Last word is taken as expected checksum. XST_SUCCESS for successful checksum validation.XST_FAILURE if checksum validation fails.
References XILPDI_CHECKSUM_MIN_BUF_LEN, XILPDI_INVERT_CHECKSUM.
Referenced by XilPdi_StoreDigestTable, XilPdi_ValidateImgHdrTbl, XilPdi_VerifyImgHdrs, XilPdi_VerifyPrtnHdrs.
int XilPdi_ValidateImgHdrTbl(const XilPdi_ImgHdrTbl *ImgHdrTbl)
This function checks the fields of the Image Header Table and validates them.
Image Header Table contains the fields that are common across all the partitions and images. ImgHdrTbl pointer to the Image Header Table XST_SUCCESS on successful Image Header Table validation.XILPDI_ERR_IHT_CHECKSUM if checksum validation fails.XILPDI_ERR_NO_OF_IMGS if number of images is less than 0 or more than 32.XILPDI_ERR_NO_OF_PRTNS if number of partitions is less than 0 or more than 32.
References XilPdi_ImgHdrTbl::NoOfImgs, XilPdi_ImgHdrTbl::NoOfPrtns, XIH_IHT_LEN, XILPDI_ERR_IHT_CHECKSUM, XilPdi_ValidateChecksum.
int XilPdi_ValidatePrtnHdr(const XilPdi_PrtnHdr *PrtnHdr)
This function validates the Partition Header.
PrtnHdr is pointer to Partition Header XST_SUCCESS on successful Partition Header validation.XILPDI_ERR_ZERO_LENGTH if partition length is 0.XILPDI_ERR_TOTAL_LENGTH if total length does not match encoded and unencoded word length.XILPDI_ERR_PRTN_TYPE if partition type is other than elf, cdo, raw, raw_elf, cfi_gsc and cfi_gsc_unmask.
References XilPdi_PrtnHdr::EncDataWordLen, XilPdi_PrtnHdr::TotalDataWordLen, XilPdi_PrtnHdr::UnEncDataWordLen, XIH_PH_ATTRB_PRTN_TYPE_RSVD.
void XilPdi_ReadBootHdr(const XilPdi_BootHdr **BootHdrPtr)
This function reads the boot header.
BootHdrPtr is pointer to the address of Boot Header
References XIH_BH_PRAM_ADDR.
int XilPdi_ReadImgHdrTbl(XilPdi_MetaHdr *MetaHdrPtr)
This function Reads the Image Header Table.
MetaHdrPtr is pointer to Meta Header table XST_SUCCESS on successful read.Error code on unsuccessful copy of image header table.
References XilPdi_MetaHdr::DeviceCopy, XilPdi_MetaHdr::FlashOfstAddr, XilPdi_MetaHdr::ImgHdrTbl, XilPdi_MetaHdr::MetaHdrOfst, SMAP_BUS_WIDTH_LENGTH, XIH_IHT_LEN.
int XilPdi_ReadIhtAndOptionalData(const XilPdi_MetaHdr *MetaHdrPtr, u8 PdiType)
This function reads IHT and optional data in Image Header Table.
MetaHdrPtr is pointer to Meta Header table. XST_SUCCESS on successful read.Error code on unsuccessful read.
References XilPdi_MetaHdr::ImgHdrTbl, XIH_IHT_LEN, XIH_PMC_RAM_IHT_OP_DATA_STORE_ADDR, XilPdi_ReadOptionalData.
int XilPdi_ReadOptionalData(const XilPdi_MetaHdr *MetaHdrPtr, u8 PdiType)
This function reads optional data in Image Header Table.
MetaHdrPtr is pointer to Meta Header table. PdiType is type of PDI for which optional data is being read XST_SUCCESS on successful read.Error code on unsuccessful copy.
References XilPdi_MetaHdr::DeviceCopy, XilPdi_MetaHdr::FlashOfstAddr, XilPdi_MetaHdr::ImgHdrTbl, XilPdi_MetaHdr::MetaHdrOfst, XilPdi_ImgHdrTbl::OptionalDataLen, SMAP_BUS_WIDTH_LENGTH, XIH_IHT_LEN, XILPDI_OPTIONAL_DATA_MAX_SIZE_16K_BYTES.
Referenced by XilPdi_ReadIhtAndOptionalData.
int XilPdi_StoreDigestTable(XilPdi_MetaHdr *MetaHdrPtr)
This function stores digest table for given data Id.
MetaHdrPtr is pointer to Meta Header table. XST_SUCCESS on successful read.Error code on any failure while reading.
References XilPdi_MetaHdr::DigestTableSize, XilPdi_MetaHdr::ImgHdrTbl, XilPdi_MetaHdr::IsAuthOptimized, XilPdi_ImgHdrTbl::OptionalDataLen, XIH_PMC_RAM_IHT_OP_DATA_STORE_ADDR, XILPDI_OPTIONAL_DATA_WORD_LEN, XILPDI_PARTITION_HASH_DATA_ID, XilPdi_SearchOptionalData, XilPdi_ValidateChecksum.
u64 XilPdi_SearchOptionalData(u64 StartAddress, u64 EndAddress, u32 DataId)
This function searches for optional data address based on given Data ID.
StartAddress is start address of IHT optional data EndAddress is end address of IHT optional data DataId is to identify type of data in data structure Address of desired optional data if given data ID is foundEnd address of IHT optional data if given data ID is not found.
Referenced by XilPdi_StoreDigestTable.
XilPdi_PrtnHashInfo* XilPdi_IsPrtnHashPresent(u32 PrtnNum, u32 HashTableSize)
This function returns address of hash entry for the given partition number.
PrtnNum Number of partition for which hash entry is requested HashTableSize Size of hash table Address of hash entry for the given partition number (to skip authentication) if it present in the hash table.NULL if hash entry is not present for the given partition number (to authenticate the signature as regular flow).
References XIH_PMC_RAM_IHT_OP_DATA_STORE_ADDR.
int XilPdi_ReadImgHdrs(const XilPdi_MetaHdr *MetaHdrPtr)
This function reads the Image Headers from the pdi stored in device (flash/SBI buffer/DDR/SD)
MetaHdrPtr is pointer to Meta Header XST_SUCCESS on successful read.Error code on unsuccessful read.
References XilPdi_MetaHdr::DeviceCopy, XilPdi_MetaHdr::FlashOfstAddr, XilPdi_MetaHdr::ImgHdr, XilPdi_ImgHdrTbl::ImgHdrAddr, XilPdi_MetaHdr::ImgHdrTbl, XilPdi_ImgHdrTbl::NoOfImgs.
int XilPdi_ReadPrtnHdrs(const XilPdi_MetaHdr *MetaHdrPtr)
This function reads the Partition Headers from the pdi stored in device (flash/SBI buffer/DDR/SD)
MetaHdrPtr is pointer to Meta Header XST_SUCCESS on successful read.Error code on unsuccessful read.
References XilPdi_MetaHdr::DeviceCopy, XilPdi_MetaHdr::FlashOfstAddr, XilPdi_MetaHdr::ImgHdrTbl, XilPdi_ImgHdrTbl::NoOfPrtns, XilPdi_MetaHdr::PrtnHdr, XilPdi_ImgHdrTbl::PrtnHdrAddr.
int XilPdi_VerifyPrtnHdrs(const XilPdi_MetaHdr *MetaHdrPtr)
This function verifies Partition Headers.
MetaHdrPtr is pointer to Meta Header table XST_SUCCESS on success.XILPDI_ERR_PH_CHECKSUM on checksum fail.
References XilPdi_MetaHdr::ImgHdrTbl, XilPdi_ImgHdrTbl::NoOfPrtns, XilPdi_MetaHdr::PrtnHdr, XilPdi_ValidateChecksum.
int XilPdi_VerifyImgHdrs(const XilPdi_MetaHdr *MetaHdrPtr)
This function verifies Image headers.
MetaHdrPtr is pointer to Meta Header table. XST_SUCCESS on successful image validation.XILPDI_ERR_IH_CHECKSUM on checksum fail.
References XilPdi_MetaHdr::ImgHdr, XilPdi_MetaHdr::ImgHdrTbl, XilPdi_ImgHdrTbl::NoOfImgs, XilPdi_ValidateChecksum.
XILPDI_PDI_TYPE_PARTIAL_METAHEADER
XILPDI_PDI_TYPE_PARTIAL