xilpdi.h
XIH_MIN_PRTNS
XIH_MIN_IMGS
XIH_BH_IMAGE_IDENT
Boot header identification string.
XLNX pattern
XIH_BH_IMAGE_IDENT_OFFSET
XIH_BH_AES_KEYSRC_OFFSET
Boot header Key source field.
XIH_BH_IMG_ATTRB_OFFSET
SMAP_BUS_WIDTH_LENGTH
SMAP bus width macros.
Referenced by XilPdi_ReadImgHdrTbl, XilPdi_ReadOptionalData.
SMAP_BUS_WIDTH_WORD_LEN
SMAP_BUS_WIDTH_8_WORD1
SMAP_BUS_WIDTH_16_WORD1
SMAP_BUS_WIDTH_32_WORD1
XIH_IHT_LEN
Defines for length of the headers.
Referenced by XilPdi_ReadIhtAndOptionalData, XilPdi_ReadImgHdrTbl, XilPdi_ReadOptionalData, XilPdi_ValidateImgHdrTbl.
XIH_IH_LEN
XIH_PH_LEN
XIH_PRTN_WORD_LEN
XIH_PRTN_WORD_LEN_SHIFT
XIH_IHT_ATTR_PUFHD_MASK
IHT attributes.
XIH_IHT_ATTR_PUFHD_SHIFT
XIH_IHT_ATTR_DPA_CM_MASK
XIH_IHT_ATTR_DPA_CM_SHIFT
XIH_IHT_ATTR_BYPS_MASK
IDCODE checks bypass.
XIH_IHT_ATTR_BYPS_ID_CODE_MASK
Check [17:16] bits to bypass ID Code.
XIH_IHT_ATTR_EOPDI_SYNC_SHIFT
XIH_IHT_ATTR_EOPDI_SYNC_MASK
XIH_IHT_EXT_IDCODE_MASK
XIH_IHT_VERSION_OFFSET
XIH_IHT_IDENT_STRING_OFFSET
XIH_IHT_PPDI_IDENT_VAL
XIH_IHT_FPDI_IDENT_VAL
XIH_PH_ATTRB_DPA_CM_EN_MASK
Prtn Attribute fields.
XIH_PH_ATTRB_DPA_CM_EN_SHIFT
XIH_PH_ATTRB_PRTN_TYPE_MASK
XIH_PH_ATTRB_PRTN_OWNER_MASK
XIH_PH_ATTRB_PUFHD_MASK
XIH_PH_ATTRB_CHECKSUM_MASK
XIH_PH_ATTRB_DSTN_CPU_MASK
XIH_PH_ATTRB_TARGET_EL_MASK
XIH_PH_ATTRB_TZ_SECURE_MASK
XIH_PH_ATTRB_PUFHD_SHIFT
XIH_PH_ATTRB_PRTN_TYPE_RSVD
Prtn Attribute Values.
Referenced by XilPdi_ValidatePrtnHdr.
XIH_PH_ATTRB_PRTN_TYPE_ELF
XIH_PH_ATTRB_PRTN_TYPE_CDO
XIH_PH_ATTRB_PRTN_TYPE_CFI_GSC_UNMASK
XIH_PH_ATTRB_PRTN_OWNER_PLM
XIH_PH_ATTRB_HASH_SHA3
XIH_PH_ATTRB_EL1
XIH_PH_ATTRB_TZ_SECURE
XILPDI_MAX_ENTRIES_FOR_ATF
Number of entries possible in ATF: 2 cores * 3 (EL2 non-secure, EL1 secure and EL1 non-secure)
XILPDI_ERR_IHT_CHECKSUM
Errors during XilPdi processing.
Referenced by XilPdi_ValidateImgHdrTbl.
XILPDI_ERR_NO_OF_PRTNS
XILPDI_ERR_ZERO_LENGTH
XILPDI_ERR_TOTAL_LENGTH
XILPDI_ERR_PRTN_TYPE
XILPDI_ERR_NO_OF_IMGS
XILPDI_ERR_IH_CHECKSUM
XILPDI_ERR_PH_CHECKSUM
XILPDI_ERR_OPTIONAL_DATA_CHECKSUM_FAILED
XILPDI_ERR_NO_VALID_OPTIONAL_DATA
XILPDI_ERR_INVALID_DIGEST_TABLE_SIZE
XILPDI_ERR_OVER_FLOW_OPTIONAL_DATA
XILPDI_ERR_OVER_FLOW_OPTIONAL_DATA_AT_DATA_ID_3
XILPDI_IH_ATTRIB_DELAY_LOAD_SHIFT
Image Header Attributes.
XILPDI_IH_ATTRIB_DELAY_LOAD_MASK
XILPDI_IH_ATTRIB_DELAY_HANDOFF_SHIFT
XILPDI_IH_ATTRIB_DELAY_HANDOFF_MASK
XILPDI_IMG_NAME_ARRAY_SIZE
Array size for image name.
XILPDI_CHECKSUM_MIN_BUF_LEN
Minimum buffer length for checksum.
Referenced by XilPdi_ValidateChecksum.
XILPDI_INVERT_CHECKSUM
Invert checksum.
Referenced by XilPdi_ValidateChecksum.
XILPDI_PARTITION_HASH_DATA_ID
Partition hash data Id.
Referenced by XilPdi_StoreDigestTable.
XIH_PMC_RAM_IHT_OP_DATA_STORE_ADDR
Common address of storing partition hashes for both versal and versal_net.
Referenced by XilPdi_IsPrtnHashPresent, XilPdi_ReadIhtAndOptionalData, XilPdi_StoreDigestTable.
XILPDI_OPTIONAL_DATA_WORD_LEN
Optional data attributes.
Referenced by XilPdi_StoreDigestTable.
XILPDI_OPTIONAL_DATA_DOUBLE_WORD_LEN
XIH_OPT_DATA_HDR_ID_MASK
XIH_OPT_DATA_HDR_LEN_MASK
XIH_OPT_DATA_LEN_SHIFT
XIPLDI_SHA3_HASH_SIZE_IN_BYTES
XILPDI_OPTIONAL_DATA_ID_3_MAX_SIZE_2K_BYTES
XILPDI_OPTIONAL_DATA_MAX_SIZE_16K_BYTES
Maximum size of IHT Optional data for Data Id 3 is 2KB.
Referenced by XilPdi_ReadOptionalData.
XilPdi_Printf
XILPDI_PMCRAM_IHT_COPY_ADDR
XILPDI_PMCRAM_IHT_DATA_ADDR
XILPDI_WORD_LEN_SHIFT
static u32 XilPdi_GetPrtnOwner(const XilPdi_PrtnHdr *PrtnHdr)
This function will return the value of Partition Owner field.
PrtnHdr is pointer to the Partition Header Partition Owner
static u32 XilPdi_GetChecksumType(const XilPdi_PrtnHdr *PrtnHdr)
This function will return the value of Checksum Type field.
PrtnHdr is pointer to the Partition Header Checksum Type
static u32 XilPdi_GetDstnCpu(const XilPdi_PrtnHdr *PrtnHdr)
This function will return the value of Destination Cpu field.
PrtnHdr is pointer to the Partition Header Destination Cpu
static u32 XilPdi_GetEL(const XilPdi_PrtnHdr *PrtnHdr)
This function will return the value of EL field.
PrtnHdr is pointer to the Partition Header EL
static u32 XilPdi_GetTZ(const XilPdi_PrtnHdr *PrtnHdr)
This function will return the value of TrustZone field.
PrtnHdr is pointer to the Partition Header TrustZone Secure or Non-Secure
static u32 XilPdi_GetPrtnType(const XilPdi_PrtnHdr *PrtnHdr)
This function will return the value of Partition Type field.
PrtnHdr is pointer to the Partition Header Partition Type
static u32 XilPdi_GetVecLocation(const XilPdi_PrtnHdr *PrtnHdr)
This function will return the value of HIVEC field.
PrtnHdr is pointer to the Partition Header HIVEC value
static u32 XilPdi_GetPufHdPh(const XilPdi_PrtnHdr *PrtnHdr)
This function will return the value of Puf Header field.
PrtnHdr is pointer to the Partition Header PUF header
static u8 XilPdi_IsDpaCmEnable(const XilPdi_PrtnHdr *PrtnHdr)
This function checks if DpaCm is enabled or not.
PrtnHdr is pointer to the Partition Header TRUE / FALSE
static u8 XilPdi_IsDpaCmEnableMetaHdr(const XilPdi_ImgHdrTbl *IHdrTbl)
This function checks if DpaCm is enabled or not in Metaheader.
IHdrTbl is pointer to the Image Header Table TRUE / FALSE
static u32 XilPdi_GetPufHdMetaHdr(const XilPdi_ImgHdrTbl *IHdrTbl)
This function gets PUF header value from Image Header Table.
IHdrTbl is pointer to the Image Header Table PUF Header Value
static u32 XilPdi_GetDelayLoad(const XilPdi_ImgHdr *ImgHdr)
This function gets Delay Load value from Image Header Table.
ImgHdr is pointer to the Image Header Table Delay Load Value
static u32 XilPdi_GetDelayHandoff(const XilPdi_ImgHdr *ImgHdr)
This function gets Delay Handoff value from Image Header Table.
ImgHdr is pointer to the Image Header Table Delay Handoff Value
static u32 XilPdi_GetSBD(const XilPdi_ImgHdrTbl *ImgHdrTbl)
This function will return the Secondary boot device.
ImgHdrTbl is pointer to the Image Header Table Secondary Boot device
static u8 XilPdi_IsAuthEnabled(const XilPdi_ImgHdrTbl *ImgHdrTblPtr)
This function checks if authentication is enabled or not.
ImgHdrTblPtr is pointer to PDI Image Header Table TRUE if authentication is enabled and false otherwise
static u8 XilPdi_IsEncEnabled(const XilPdi_ImgHdrTbl *ImgHdrTblPtr)
This function checks if encryption is enabled or not.
ImgHdrTblPtr is pointer to PDI Image Header Table TRUE if encryption is enabled and false otherwise
static u32 XilPdi_GetPlmKeySrc(void)
This function returns the PLM encryption key source in Bootheader.
Encryption Key source
int XilPdi_ValidatePrtnHdr(const XilPdi_PrtnHdr *PrtnHdr)
This function validates the Partition Header.
PrtnHdr is pointer to Partition Header XST_SUCCESS on successful Partition Header validation.XILPDI_ERR_ZERO_LENGTH if partition length is 0.XILPDI_ERR_TOTAL_LENGTH if total length does not match encoded and unencoded word length.XILPDI_ERR_PRTN_TYPE if partition type is other than elf, cdo, raw, raw_elf, cfi_gsc and cfi_gsc_unmask.
References XilPdi_PrtnHdr::UnEncDataWordLen, XilPdi_PrtnHdr::EncDataWordLen, XilPdi_PrtnHdr::TotalDataWordLen, XIH_PH_ATTRB_PRTN_TYPE_RSVD.
int XilPdi_ValidateImgHdrTbl(const XilPdi_ImgHdrTbl *ImgHdrTbl)
This function checks the fields of the Image Header Table and validates them.
Image Header Table contains the fields that are common across all the partitions and images. ImgHdrTbl pointer to the Image Header Table XST_SUCCESS on successful Image Header Table validation.XILPDI_ERR_IHT_CHECKSUM if checksum validation fails.XILPDI_ERR_NO_OF_IMGS if number of images is less than 0 or more than 32.XILPDI_ERR_NO_OF_PRTNS if number of partitions is less than 0 or more than 32.
References XilPdi_ValidateChecksum, XIH_IHT_LEN, XILPDI_ERR_IHT_CHECKSUM, XilPdi_ImgHdrTbl::NoOfImgs, XilPdi_ImgHdrTbl::NoOfPrtns.
void XilPdi_ReadBootHdr(const XilPdi_BootHdr **BootHdrPtr)
This function reads the boot header.
BootHdrPtr is pointer to the address of Boot Header
References XIH_BH_PRAM_ADDR.
int XilPdi_ReadImgHdrTbl(XilPdi_MetaHdr *MetaHdrPtr)
This function Reads the Image Header Table.
MetaHdrPtr is pointer to Meta Header table XST_SUCCESS on successful read.Error code on unsuccessful copy of image header table.
References XilPdi_MetaHdr::DeviceCopy, XilPdi_MetaHdr::FlashOfstAddr, XilPdi_MetaHdr::MetaHdrOfst, SMAP_BUS_WIDTH_LENGTH, XilPdi_MetaHdr::ImgHdrTbl, XIH_IHT_LEN.
int XilPdi_VerifyImgHdrs(const XilPdi_MetaHdr *MetaHdrPtr)
This function verifies Image headers.
MetaHdrPtr is pointer to Meta Header table. XST_SUCCESS on successful image validation.XILPDI_ERR_IH_CHECKSUM on checksum fail.
References XilPdi_MetaHdr::ImgHdrTbl, XilPdi_ImgHdrTbl::NoOfImgs, XilPdi_ValidateChecksum, XilPdi_MetaHdr::ImgHdr.
int XilPdi_VerifyPrtnHdrs(const XilPdi_MetaHdr *MetaHdrPtr)
This function verifies Partition Headers.
MetaHdrPtr is pointer to Meta Header table XST_SUCCESS on success.XILPDI_ERR_PH_CHECKSUM on checksum fail.
References XilPdi_MetaHdr::ImgHdrTbl, XilPdi_ImgHdrTbl::NoOfPrtns, XilPdi_ValidateChecksum, XilPdi_MetaHdr::PrtnHdr.
int XilPdi_ReadImgHdrs(const XilPdi_MetaHdr *MetaHdrPtr)
This function reads the Image Headers from the pdi stored in device (flash/SBI buffer/DDR/SD)
MetaHdrPtr is pointer to Meta Header XST_SUCCESS on successful read.Error code on unsuccessful read.
References XilPdi_MetaHdr::ImgHdrTbl, XilPdi_ImgHdrTbl::NoOfImgs, XilPdi_MetaHdr::DeviceCopy, XilPdi_MetaHdr::FlashOfstAddr, XilPdi_ImgHdrTbl::ImgHdrAddr, XilPdi_MetaHdr::ImgHdr.
int XilPdi_ReadPrtnHdrs(const XilPdi_MetaHdr *MetaHdrPtr)
This function reads the Partition Headers from the pdi stored in device (flash/SBI buffer/DDR/SD)
MetaHdrPtr is pointer to Meta Header XST_SUCCESS on successful read.Error code on unsuccessful read.
References XilPdi_MetaHdr::ImgHdrTbl, XilPdi_ImgHdrTbl::NoOfPrtns, XilPdi_MetaHdr::DeviceCopy, XilPdi_MetaHdr::FlashOfstAddr, XilPdi_ImgHdrTbl::PrtnHdrAddr, XilPdi_MetaHdr::PrtnHdr.
int XilPdi_ReadIhtAndOptionalData(const XilPdi_MetaHdr *MetaHdrPtr, u8 PdiType)
This function reads IHT and optional data in Image Header Table.
MetaHdrPtr is pointer to Meta Header table. XST_SUCCESS on successful read.Error code on unsuccessful read.
References XIH_PMC_RAM_IHT_OP_DATA_STORE_ADDR, XIH_IHT_LEN, XilPdi_MetaHdr::ImgHdrTbl, XilPdi_ReadOptionalData.
int XilPdi_ValidateChecksum(const void *Buffer, u32 Length)
This function is used to validate the word checksum for the Image Header table and Partition Headers.
Checksum is based on the formula Checksum = ~ (X1 + X2 + X3 + .... + Xn) Buffer pointer to the data for which checksum should be calculated Length of the buffer for which checksum should be calculated. Last word is taken as expected checksum. XST_SUCCESS for successful checksum validation.XST_FAILURE if checksum validation fails.
References XILPDI_CHECKSUM_MIN_BUF_LEN, XILPDI_INVERT_CHECKSUM.
Referenced by XilPdi_ValidateImgHdrTbl, XilPdi_StoreDigestTable, XilPdi_VerifyPrtnHdrs, XilPdi_VerifyImgHdrs.
XilPdi_PrtnHashInfo* XilPdi_IsPrtnHashPresent(u32 PrtnNum, u32 HashTableSize)
This function returns address of hash entry for the given partition number.
PrtnNum Number of partition for which hash entry is requested HashTableSize Size of hash table Address of hash entry for the given partition number (to skip authentication) if it present in the hash table.NULL if hash entry is not present for the given partition number (to authenticate the signature as regular flow).
References XIH_PMC_RAM_IHT_OP_DATA_STORE_ADDR.
int XilPdi_StoreDigestTable(XilPdi_MetaHdr *MetaHdrPtr)
This function stores digest table for given data Id.
MetaHdrPtr is pointer to Meta Header table. XST_SUCCESS on successful read.Error code on any failure while reading.
References XilPdi_MetaHdr::ImgHdrTbl, XilPdi_ImgHdrTbl::OptionalDataLen, XilPdi_MetaHdr::IsAuthOptimized, XilPdi_SearchOptionalData, XILPDI_PARTITION_HASH_DATA_ID, XILPDI_OPTIONAL_DATA_WORD_LEN, XilPdi_MetaHdr::DigestTableSize, XilPdi_ValidateChecksum, XIH_PMC_RAM_IHT_OP_DATA_STORE_ADDR.
u64 XilPdi_SearchOptionalData(u64 StartAddress, u64 EndAddress, u32 DataId)
This function searches for optional data address based on given Data ID.
StartAddress is start address of IHT optional data EndAddress is end address of IHT optional data DataId is to identify type of data in data structure Address of desired optional data if given data ID is foundEnd address of IHT optional data if given data ID is not found.
Referenced by XilPdi_StoreDigestTable.
int XilPdi_ReadOptionalData(const XilPdi_MetaHdr *MetaHdrPtr, u8 PdiType)
This function reads optional data in Image Header Table.
MetaHdrPtr is pointer to Meta Header table. PdiType is type of PDI for which optional data is being read XST_SUCCESS on successful read.Error code on unsuccessful copy.
References XilPdi_MetaHdr::FlashOfstAddr, XilPdi_MetaHdr::MetaHdrOfst, XIH_IHT_LEN, SMAP_BUS_WIDTH_LENGTH, XilPdi_MetaHdr::ImgHdrTbl, XilPdi_ImgHdrTbl::OptionalDataLen, XILPDI_OPTIONAL_DATA_MAX_SIZE_16K_BYTES, XilPdi_MetaHdr::DeviceCopy.
Referenced by XilPdi_ReadIhtAndOptionalData.