sdiaud
XSdiAud_HandlerType
Audio group change detect handler.
XSdiAud_GrpNum
Group 1.
XSdiAud_SampRate
000 - 48 KHz
XSdiAud_SampSize
0 - 20 Bit Audio Sample
XSdiAud_AesChPair
XSdiAud_Asx
XSdiAud_GrpXChNum
Channel 1 of Group 1/2/3/4.
XSdiAud_VidRate
XSdiAud_VidScan
XSdiAud_VidFam
XSdiAud_NumOfCh
1 channel
XSdiAud_ChNum
channel 1
typedef void(* XSdiAud_Callback)(void *CallbackRef))(void *CallbackRef)
Callback function pointer type for SDI audio events, invoked with a user-defined reference parameter.
XSDIAUD_CNTRL_REG_OFFSET
SDI Audio Module control register offset.
Referenced by XSdiAud_Enable.
XSDIAUD_SOFT_RST_REG_OFFSET
SDI Audio Soft reset register offset.
Referenced by XSdiAud_ConfigReset, XSdiAud_CoreReset.
XSDIAUD_INT_EN_REG_OFFSET
SDI Audio Interrupt enable register offset.
Referenced by XSdiAud_IntrHandler.
XSDIAUD_CORE_VERSION_REG_OFFSET
SDI Audio Core version register offset.
Referenced by XSdiAud_GetCoreVersion.
XSDIAUD_INT_STS_REG_OFFSET
SDI Audio Interrupt status register offset.
Referenced by XSdiAud_GetIntStat, XSdiAud_IntrHandler.
XSDIAUD_EMB_VID_CNTRL_REG_OFFSET
SDI Audio Embed Video control register offset.
Referenced by XSdiAud_Emb_EnExtrnLine, XSdiAud_Emb_SetVidProps.
XSDIAUD_AUD_CNTRL_REG_OFFSET
SDI Audio Audio control register offset.
Referenced by XSdiAud_Emb_SetAsx, XSdiAud_Emb_SetSmpRate, XSdiAud_Emb_SetSmpSize, XSdiAud_Ext_DisableClkPhase, XSdiAud_SetAesChPair.
XSDIAUD_VALID_CH_REG_OFFSET
SDI Audio valid channels register offset.
Referenced by XSdiAud_SetCh.
XSDIAUD_MUTE_CH_REG_OFFSET
SDI Audio mute channels register offset.
Referenced by XSdiAud_MuteCh.
XSDIAUD_ACT_GRP_PRES_REG_OFFSET
SDI Audio group presence register offset.
Referenced by XSdiAud_GetActGrpStatus.
XSDIAUD_EXT_FIFO_OVFLW_ST_REG_OFFSET
SDI Audio Extract FIFO overflow status register offset.
Referenced by XSdiAud_Ext_GetFIFOOvFlwStatus.
XSDIAUD_EXT_CH_STAT0_REG_OFFSET
SDI Audio Extract channel status register0 offset.
Referenced by XSdiAud_GetChStat, XSdiAud_SelfTest.
XSDIAUD_ACT_CH_STAT_REG_OFFSET
SDI Audio active channel status register offset.
Referenced by XSdiAud_Ext_GetAcChStatus.
XSDIAUD_SR_STAT_REG_OFFSET
SDI Audio sample rate status register offset.
Referenced by XSdiAud_Ext_GetSRStatus.
XSDIAUD_ASX_STAT_REG_OFFSET
SDI Audio async channel pair status register offset.
Referenced by XSdiAud_Ext_GetAsxStatus.
XSDIAUD_GUI_PARAM_REG_OFFSET
SDI Audio GUI parameters register offset.
XSDIAUD_CNTRL_EN_SHIFT
SDI Audio Embed enable or Extract enable shift.
XSDIAUD_CNTRL_EN_MASK
SDI Audio Embed enable or Extract enable mask.
Referenced by XSdiAud_Enable.
XSDIAUD_SOFT_RST_ACLK_SHIFT
SDI Audio Embed soft reset aclk shift.
XSDIAUD_SOFT_RST_ACLK_MASK
SDI Audio Embed soft reset aclk mask.
Referenced by XSdiAud_ConfigReset.
XSDIAUD_SOFT_RST_SCLK_SHIFT
SDI Audio soft reset sclk shift.
XSDIAUD_SOFT_RST_SCLK_MASK
SDI Audio soft reset sclk mask.
Referenced by XSdiAud_CoreReset.
XSDIAUD_VER_SHIFT
SDI Audio version shift.
XSDIAUD_VER_MASK
SDI Audio version mask.
XSDIAUD_EMB_VID_CNT_FAMILY_SHIFT
SDI Audio Embed video control family shift.
Referenced by XSdiAud_Emb_SetVidProps.
XSDIAUD_EMB_VID_CNT_FAMILY_MASK
SDI Audio Embed video control family mask.
Referenced by XSdiAud_Emb_SetVidProps.
XSDIAUD_EMB_VID_CNT_RATE_SHIFT
SDI Audio Embed video control rate shift.
Referenced by XSdiAud_Emb_SetVidProps.
XSDIAUD_EMB_VID_CNT_RATE_MASK
SDI Audio Embed video control rate mask.
Referenced by XSdiAud_Emb_SetVidProps.
XSDIAUD_EMB_VID_CNT_SCAN_SHIFT
SDI Audio Embed video control scan shift.
Referenced by XSdiAud_Emb_SetVidProps.
XSDIAUD_EMB_VID_CNT_SCAN_MASK
SDI Audio Embed video control scan mask.
Referenced by XSdiAud_Emb_SetVidProps.
XSDIAUD_EMB_VID_CNT_ELE_SHIFT
SDI Audio Embed video control external line enable shift.
Referenced by XSdiAud_Emb_EnExtrnLine.
XSDIAUD_EMB_VID_CNT_ELE_MASK
SDI Audio Embed video control external line enable mask.
Referenced by XSdiAud_Emb_EnExtrnLine.
XSDIAUD_EMB_AUD_CNT_SR_SHIFT
SDI Audio Embed audio control SD sample rate shift.
XSDIAUD_EMB_AUD_CNT_SR_MASK
SDI Audio Embed audio control SD sample rate mask.
Referenced by XSdiAud_Emb_SetSmpRate.
XSDIAUD_EMB_AUD_CNT_SS_SHIFT
SDI Audio Embed audio control SD sample size shift.
Referenced by XSdiAud_Emb_SetSmpSize.
XSDIAUD_EMB_AUD_CNT_SS_MASK
SDI Audio Embed audio control SD sample size mask.
Referenced by XSdiAud_Emb_SetSmpSize.
XSDIAUD_EMB_AUD_CNT_ASX_SHIFT
SDI Audio Embed audio control asynchronous data flag shift.
Referenced by XSdiAud_Emb_SetAsx.
XSDIAUD_EMB_AUD_CNT_ASX_MASK
SDI Audio Embed audio control asynchronous data flag mask.
Referenced by XSdiAud_Emb_SetAsx.
XSDIAUD_EMB_AUD_CNT_AES_CH_PAIR_SHIFT
SDI Audio Embed audio control aes channel pair shift.
Referenced by XSdiAud_SetAesChPair.
XSDIAUD_EMB_AUD_CNT_AES_CH_PAIR_MASK
SDI Audio Embed audio control aes channel pair mask.
Referenced by XSdiAud_SetAesChPair.
XSDIAUD_EMB_AXIS_CHCOUNT_SHIFT
SDI Audio Embed AXIS channel count shift.
XSDIAUD_EMB_AXIS_CHCOUNT_MASK
SDI Audio Embed AXIS channel count mask.
XSDIAUD_EMD_MUX_CNT_GS_SHIFT
SDI Audio Embed Mux group select shift.
XSDIAUD_EMD_MUX_CNT_GS_MASK
SDI Audio Embed Mux group select mask.
XSDIAUD_GRP_PRESNT_SHIFT
SDI Audio group present value shift.
XSDIAUD_GRP_PRESNT_MASK
SDI Audio group present value mask.
Referenced by XSdiAud_GetActGrpStatus.
XSDIAUD_GRP_PRESNTV_SHIFT
SDI Audio group present valid shift.
XSDIAUD_GRP_PRESNTV_MASK
SDI Audio group present valid mask.
XSDIAUD_INT_EN_AUD_STAT_UPDATE_SHIFT
SDI Audio interrupt status update shift.
XSDIAUD_INT_EN_AUD_STAT_UPDATE_MASK
SDI Audio interrupt status update mask.
XSDIAUD_INT_EN_GRP_CHANGE_SHIFT
SDI Audio interrupt group change detect shift.
XSDIAUD_INT_EN_GRP_CHANGE_MASK
SDI Audio interrupt group change detect mask.
XSDIAUD_INT_EN_CH_CHANGE_SHIFT
SDI Audio interrupt active channel change detect shift.
XSDIAUD_INT_EN_CH_CHANGE_MASK
SDI Audio interrupt active channel change detect mask.
XSDIAUD_INT_EN_SMP_RATE_CHANGE_SHIFT
SDI Audio interrupt sample rate change detect shift.
XSDIAUD_INT_EN_SMP_RATE_CHANGE_MASK
SDI Audio interrupt sample rate change detect mask.
XSDIAUD_INT_EN_ASX_CHANGE_SHIFT
SDI Audio interrupt asynchronous data flag value change detect shift.
XSDIAUD_INT_EN_ASX_CHANGE_MASK
SDI Audio interrupt asynchronous data flag value change detect mask.
XSDIAUD_INT_EN_AES_CS_UPDATE_SHIFT
SDI Audio interrupt aes channel status value update shift.
XSDIAUD_INT_EN_AES_CS_UPDATE_MASK
SDI Audio interrupt aes channel status value update mask.
XSDIAUD_INT_EN_AES_CS_CHANGE_SHIFT
SDI Audio interrupt aes channel status value change shift.
XSDIAUD_INT_EN_AES_CS_CHANGE_MASK
SDI Audio interrupt aes channel status value change mask.
XSDIAUD_EXT_INT_EN_VID_PROP_CHANGE_SHIFT
SDI Audio Extract interrupt video properties change detect shift.
XSDIAUD_EXT_INT_EN_VID_PROP_CHANGE_MASK
SDI Audio Extract interrupt video properties change detect mask.
XSDIAUD_EXT_INT_EN_FIFO_OF_SHIFT
SDI Audio Extract interrupt FIFO overflow detect shift.
XSDIAUD_EXT_INT_EN_FIFO_OF_MASK
SDI Audio Extract interrupt FIFO overflow detect mask.
XSDIAUD_EXT_INT_EN_CERR_SHIFT
SDI Audio Extract interrupt checksum error detect shift.
XSDIAUD_EXT_INT_EN_CERR_MASK
SDI Audio Extract interrupt checksum error detect mask.
XSDIAUD_EXT_INT_EN_PERR_SHIFT
SDI Audio Extract interrupt parity error detect shift.
XSDIAUD_EXT_INT_EN_PERR_MASK
SDI Audio Extract interrupt parity error detect mask.
XSDIAUD_INT_ST_AUD_STAT_UPDATE_SHIFT
SDI Audio interrupt status update shift.
XSDIAUD_INT_ST_AUD_STAT_UPDATE_MASK
SDI Audio interrupt status update mask.
Referenced by XSdiAud_IntrHandler.
XSDIAUD_INT_ST_GRP_CHANGE_SHIFT
SDI Audio interrupt status group change detect shift.
XSDIAUD_INT_ST_GRP_CHANGE_MASK
SDI Audio interrupt status group change detect mask.
Referenced by XSdiAud_IntrHandler.
XSDIAUD_INT_ST_CH_CHANGE_SHIFT
SDI Audio interrupt status active channel change detect shift.
XSDIAUD_INT_ST_CH_CHANGE_MASK
SDI Audio interrupt status active channel change detect mask.
Referenced by XSdiAud_IntrHandler.
XSDIAUD_INT_ST_SMP_RATE_CHANGE_SHIFT
SDI Audio interrupt status sample rate change detect shift.
XSDIAUD_INT_ST_SMP_RATE_CHANGE_MASK
SDI Audio interrupt status sample rate change detect mask.
Referenced by XSdiAud_IntrHandler.
XSDIAUD_INT_ST_ASX_CHANGE_SHIFT
SDI Audio interrupt status asynchronous data flag value change detect shift.
XSDIAUD_INT_ST_ASX_CHANGE_MASK
SDI Audio interrupt status asynchronous data flag value change detect mask.
Referenced by XSdiAud_IntrHandler.
XSDIAUD_INT_ST_AES_CS_UPDATE_SHIFT
SDI Audio interrupt status aes channel status value update shift.
XSDIAUD_INT_ST_AES_CS_UPDATE_MASK
SDI Audio interrupt status aes channel status value update mask.
Referenced by XSdiAud_IntrHandler.
XSDIAUD_INT_ST_AES_CS_CHANGE_SHIFT
SDI Audio interrupt status aes channel status value change shift.
XSDIAUD_INT_ST_AES_CS_CHANGE_MASK
SDI Audio interrupt status aes channel status value change mask.
Referenced by XSdiAud_IntrHandler.
XSDIAUD_EXT_INT_ST_VID_PROP_CHANGE_SHIFT
SDI Audio Extract interrupt status video properties change detect shift.
XSDIAUD_EXT_INT_ST_VID_PROP_CHANGE_MASK
SDI Audio Extract interrupt status video properties change detect mask.
Referenced by XSdiAud_IntrHandler.
XSDIAUD_EXT_INT_ST_FIFO_OF_SHIFT
SDI Audio Extract interrupt status FIFO overflow detect shift.
XSDIAUD_EXT_INT_ST_FIFO_OF_MASK
SDI Audio Extract interrupt status FIFO overflow detect mask.
Referenced by XSdiAud_IntrHandler.
XSDIAUD_EXT_INT_ST_CERR_SHIFT
SDI Audio Extract interrupt status checksum error detect shift.
XSDIAUD_EXT_INT_ST_CERR_MASK
SDI Audio Extract interrupt status checksum error detect mask.
Referenced by XSdiAud_IntrHandler.
XSDIAUD_EXT_INT_ST_PERR_SHIFT
SDI Audio Extract interrupt status parity error detect shift.
XSDIAUD_EXT_INT_ST_PERR_MASK
SDI Audio Extract interrupt status parity error detect mask.
Referenced by XSdiAud_IntrHandler.
XSDIAUD_EXT_AUD_CNT_CP_EN_SHIFT
SDI Audio Extract audio clock phase enable shift.
Referenced by XSdiAud_Ext_DisableClkPhase.
XSDIAUD_EXT_AUD_CNT_CP_EN_MASK
SDI Audio Extract audio clock phase enable mask.
Referenced by XSdiAud_Ext_DisableClkPhase.
XSDIAUD_EXT_AXIS_CHCOUNT_SHIFT
SDI Audio Extract AXIS channel count shift.
XSDIAUD_EXT_AXIS_CHCOUNT_MASK
SDI Audio Extract AXIS channel count mask.
XSDIAUD_EXT_DMUX_GRPS_SHIFT
SDI Audio Extract DMux group select shift.
XSDIAUD_EXT_DMUX_GRPS_MASK
SDI Audio Extract DMux group select mask.
XSDIAUD_EXT_DMUX_MUTE_SHIFT
SDI Audio Extract DMux mute channel shift.
XSDIAUD_EXT_DMUX_MUTEALL_MASK
SDI Audio Extract DMux mute all channels mask.
XSDIAUD_EXT_DMUX_MUTE1_MASK
SDI Audio Extract Dmux mute channel 1 mask.
XSDIAUD_EXT_DMUX_MUTE2_MASK
SDI Audio Extract Dmux mute channel 2 mask.
XSDIAUD_EXT_DMUX_MUTE3_MASK
SDI Audio Extract Dmux mute channel 3 mask.
XSDIAUD_EXT_DMUX_MUTE4_MASK
SDI Audio Extract Dmux mute channel 4 mask.
XSDIAUD_EXT_PKTST_SR_SHIFT
SDI Audio Extract control packet status sampling rate shift.
XSDIAUD_EXT_PKTST_SR_MASK
SDI Audio Extract control packet status sampling rate mask.
XSDIAUD_EXT_PKTST_AC_SHIFT
SDI Audio Extract control packet status group active channel shift.
XSDIAUD_EXT_PKTST_AC_MASK
SDI Audio Extract control packet status group active channel mask.
XSDIAUD_GUI_CHAN_SHIFT
SDI Audio GUI Channels parameter shift.
XSDIAUD_GUI_CHAN_MASK
SDI Audio GUI Channels parameter mask.
XSDIAUD_GUI_STD_SHIFT
SDI Audio GUI UHD SDI standard parameter shift.
XSDIAUD_GUI_STD_MASK
SDI Audio GUI UHD Standard parameter mask.
XSDIAUD_GUI_AUDF_SHIFT
SDI Audio GUI audio function parameter shift.
XSDIAUD_GUI_AUDF_MASK
SDI Audio GUI audio function parameter mask.
XSDIAUD_GUI_AXIE_SHIFT
SDI Audio GUI AXI-lite enable parameter shift.
XSDIAUD_GUI_AXIE_MASK
SDI Audio GUI AXI-lite enable parameter mask.
XSDIAUD_GUI_CHSTAT_EXTR_SHIFT
SDI Audio GUI Channel status extract parameter shift.
XSDIAUD_GUI_CHSTAT_EXTR_MASK
SDI Audio GUI channel status extract parameter mask.
XSdiAud_In32
Input Operations.
XSdiAud_Out32
Output Operations.
XSdiAud_ReadReg
Reads a 32-bit value from a register in the SDI Audio hardware.
BaseAddress The base address of the SDI Audio device. RegOffset The offset of the register to read from the base address. The 32-bit value read from the specified register. This is a macro that directly accesses hardware registers. Ensure that BaseAddress is valid and RegOffset is within the valid register address range.
Referenced by XSdiAud_ConfigReset, XSdiAud_CoreReset, XSdiAud_Emb_EnExtrnLine, XSdiAud_Emb_SetAsx, XSdiAud_Emb_SetSmpRate, XSdiAud_Emb_SetSmpSize, XSdiAud_Emb_SetVidProps, XSdiAud_Enable, XSdiAud_Ext_DisableClkPhase, XSdiAud_Ext_GetAcChStatus, XSdiAud_Ext_GetAsxStatus, XSdiAud_Ext_GetFIFOOvFlwStatus, XSdiAud_Ext_GetSRStatus, XSdiAud_GetActGrpStatus, XSdiAud_GetChStat, XSdiAud_GetCoreVersion, XSdiAud_GetIntStat, XSdiAud_IntrHandler, XSdiAud_SelfTest, XSdiAud_SetAesChPair.
XSdiAud_WriteReg
This function writes a 32-bit value to a register in the SDI Audio hardware.
BaseAddress The base address of the SDI Audio device. RegOffset The offset of the register to write to from the base address. Data The 32-bit value to write to the specified register. This is a macro that directly accesses hardware registers. Ensure that BaseAddress is valid and RegOffset is within the valid register address range. This macro does not perform any error checking on the input parameters. Use with caution to avoid unintended side effects on the hardware.
Referenced by XSdiAud_ConfigReset, XSdiAud_CoreReset, XSdiAud_Emb_EnExtrnLine, XSdiAud_Emb_SetAsx, XSdiAud_Emb_SetSmpRate, XSdiAud_Emb_SetSmpSize, XSdiAud_Emb_SetVidProps, XSdiAud_Enable, XSdiAud_Ext_DisableClkPhase, XSdiAud_MuteCh, XSdiAud_SetAesChPair, XSdiAud_SetCh.
XSdiAud_RegMap XSdiAud_Embed_RegMap[][]
XSdiAud_RegMap XSdiAud_Extract_RegMap[][]
XSdiAud_Config XSdiAud_ConfigTable[][]
u8 XSdiAud_CountBits(u32 n)
int XSdiAud_CfgInitialize(XSdiAud *InstancePtr, XSdiAud_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the XSdiAud.
This function must be called prior to using the core. Initialization of the XSdiAud includes setting up the instance data, and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the XSdiAud instance. CfgPtr points to the configuration structure associated with the XSdiAud. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS : if successful.XST_FAILURE : if version mismatched. None.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSdiAud::IsReady, XSdiAud_Enable, XSdiAud_SelfTest.
Referenced by XSdiAud_Initialize.
void XSdiAud_Enable(XSdiAud *InstancePtr, u8 Enable)
This function enables/disables the XSdiAud.
InstancePtr is a pointer to the XSdiAud instance. Enable specifies TRUE/FALSE value to either enable or disable the XSdiAud.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSdiAud::IsStarted, XSDIAUD_CNTRL_EN_MASK, XSDIAUD_CNTRL_REG_OFFSET, XSdiAud_ReadReg, XSdiAud_WriteReg.
Referenced by XSdiAud_CfgInitialize.
void XSdiAud_GetChStat(XSdiAud *InstancePtr, u8 *ChStatBuf)
This function reads all the Channel Status registers and writes to a buffer.
InstancePtr is a pointer to the XSdiAud instance. ChStatBuf is a pointer to a buffer.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_EXT_CH_STAT0_REG_OFFSET, XSdiAud_ReadReg.
u32 XSdiAud_GetCoreVersion(XSdiAud *InstancePtr)
This function reads the core version register and returns its value.
InstancePtr is a pointer to the XSdiAud instance. core version register value is returned.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_CORE_VERSION_REG_OFFSET, XSdiAud_ReadReg.
u32 XSdiAud_GetIntStat(XSdiAud *InstancePtr)
This function reads the Interrupt Status register and returns its value.
InstancePtr is a pointer to the XSdiAud instance. Interrupt status register value is returned.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_INT_STS_REG_OFFSET, XSdiAud_ReadReg.
void XSdiAud_Emb_SetSmpRate(XSdiAud *InstancePtr, XSdiAud_SampRate XSdiAud_SRate)
This Audio Embed function sets the sampling rate.
InstancePtr is a pointer to the XSdiAud instance. XSdiAud_SRate is the sampling rate, it is enum XSdiAud_SampRate, it can be anyone of these 000 - 48 KHz, 001 - 44.1 KHz, 010 - 32 KHz
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_AUD_CNTRL_REG_OFFSET, XSDIAUD_EMB_AUD_CNT_SR_MASK, XSdiAud_ReadReg, XSDIAUD_SMPLRATE_32, XSdiAud_WriteReg.
void XSdiAud_Emb_SetSmpSize(XSdiAud *InstancePtr, XSdiAud_SampSize XSdiAud_SSize)
This Audio Embed function sets the sample size in only SD Mode.
InstancePtr is a pointer to the XSdiAud instance. XSdiAud_SSize is the sample size, it is enum XSdiAud_SampSize, it can be 0 or 1. 0 - 20 Bit 1 - 24 Bit
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_AUD_CNTRL_REG_OFFSET, XSDIAUD_EMB_AUD_CNT_SS_MASK, XSDIAUD_EMB_AUD_CNT_SS_SHIFT, XSdiAud_ReadReg, XSdiAud_WriteReg.
void XSdiAud_Emb_SetAsx(XSdiAud *InstancePtr, XSdiAud_Asx XSdiAud_Async_data_flag)
This Audio Embed function sets the asynchronous data flag.
InstancePtr is a pointer to the XSdiAud instance. XSdiAud_Async_data_flag is the async data flag, it is enum XSdiAud_Asx, it can be 0 or 1. 0 - Synchronous audio 1 - Asynchronous audio
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_AUD_CNTRL_REG_OFFSET, XSDIAUD_EMB_AUD_CNT_ASX_MASK, XSDIAUD_EMB_AUD_CNT_ASX_SHIFT, XSdiAud_ReadReg, XSdiAud_WriteReg.
void XSdiAud_SetAesChPair(XSdiAud *InstancePtr, XSdiAud_AesChPair XSdiAud_ACP)
This Audio function selects the aes channel pair.
InstancePtr is a pointer to the XSdiAud instance. XSdiAud_ACP is the async data flag, it is enum XSdiAud_AesChPair, it can be any value between 0 to 16.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_AUD_CNTRL_REG_OFFSET, XSDIAUD_EMB_AUD_CNT_AES_CH_PAIR_MASK, XSDIAUD_EMB_AUD_CNT_AES_CH_PAIR_SHIFT, XSdiAud_ReadReg, XSdiAud_WriteReg.
void XSdiAud_Emb_SetVidProps(XSdiAud *InstancePtr, XSdiAud_Emb_Vid_Props *XSdiAud_VP)
This Audio Embed function sets the video properties of the image like transport scan, transport rate and transport family.
InstancePtr is a pointer to the XSdiAud instance. XSdiAud_VP is the struct containing the video family, rate and video scan information.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_EMB_VID_CNT_FAMILY_MASK, XSDIAUD_EMB_VID_CNT_FAMILY_SHIFT, XSDIAUD_EMB_VID_CNT_RATE_MASK, XSDIAUD_EMB_VID_CNT_RATE_SHIFT, XSDIAUD_EMB_VID_CNT_SCAN_MASK, XSDIAUD_EMB_VID_CNT_SCAN_SHIFT, XSDIAUD_EMB_VID_CNTRL_REG_OFFSET, XSdiAud_ReadReg, XSdiAud_Emb_Vid_Props::XSdiAud_TFamily, XSdiAud_Emb_Vid_Props::XSdiAud_TRate, XSdiAud_Emb_Vid_Props::XSdiAud_TScan, XSdiAud_WriteReg.
void XSdiAud_Emb_EnExtrnLine(XSdiAud *InstancePtr, u8 XSdiAud_En)
This Audio Embed function enables the external line number.
InstancePtr is a pointer to the XSdiAud instance. XSdiAud_En can be 0 or 1, 0 is to disable and 1 is to enable
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_EMB_VID_CNT_ELE_MASK, XSDIAUD_EMB_VID_CNT_ELE_SHIFT, XSDIAUD_EMB_VID_CNTRL_REG_OFFSET, XSdiAud_ReadReg, XSdiAud_WriteReg.
void XSdiAud_Ext_DisableClkPhase(XSdiAud *InstancePtr, u8 XSdiAud_SetClkP)
This Audio Extract function sets the clock phase.
InstancePtr is a pointer to the XSdiAud instance. XSdiAud_SetClkP enables the use of clock phase data, 0 is to enable 1 is to disable
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_AUD_CNTRL_REG_OFFSET, XSDIAUD_EXT_AUD_CNT_CP_EN_MASK, XSDIAUD_EXT_AUD_CNT_CP_EN_SHIFT, XSdiAud_ReadReg, XSdiAud_WriteReg.
void XSdiAud_GetActGrpStatus(XSdiAud *InstancePtr, XSdiAud_ActGrpSt *GrpSt)
This function detects the Audio groups and returns the groups which are present.
InstancePtr is a pointer to the XSdiAud instance. GrpSt is a pointer tp no. of active groups and also which groups are active.
References XSdiAud_Config::BaseAddress, BIT, XSdiAud::Config, XSDIAUD_ACT_GRP_PRES_REG_OFFSET, XSDIAUD_GRP_PRESNT_MASK, XSdiAud_ReadReg.
void XSdiAud_SetCh(XSdiAud *InstancePtr, u32 XSdiAudSetChMask)
This function sets the channel valid register.
Based on the mask provided the corresponding channels are embedded/extracted onto sdi. InstancePtr is a pointer to the XSdiAud instance. XSdiAudSetChMask is the 32 bit mask used to set the specific channels.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_VALID_CH_REG_OFFSET, XSdiAud_WriteReg.
void XSdiAud_MuteCh(XSdiAud *InstancePtr, u32 XSdiAudMuteChMask)
This function mutes a specific channel based on the mask provided.
InstancePtr is a pointer to the XSdiAud instance. XSdiAudMuteChMask is a 32 bit mask used to mute specific channels.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_MUTE_CH_REG_OFFSET, XSdiAud_WriteReg.
u8 XSdiAud_Ext_GetFIFOOvFlwStatus(XSdiAud *InstancePtr)
This function reads the FIFO overflow status.
Each bit when read as 1, indicates that RX Sample FIFO for that group is overflowing. InstancePtr is a pointer to the XSdiAud instance. Returns a u8 value, we can know the group overflowing using the bits set in this value.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_EXT_FIFO_OVFLW_ST_REG_OFFSET, XSdiAud_ReadReg.
void XSdiAud_Ext_GetAcChStatus(XSdiAud *InstancePtr, XSdiAud_ActChSt *ActChSt)
This function reads the active channel information decoded from audio control packet.
InstancePtr is a pointer to the XSdiAud instance. ActChSt is the pointer to no. of active channels and the channels active in each group.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_ACT_CH_STAT_REG_OFFSET, XSdiAud_ReadReg.
void XSdiAud_Ext_GetSRStatus(XSdiAud *InstancePtr, XSdiAud_SRSt *SRSt)
This function reads the sample rate information decoded from audio control packet (0 - 48 KHz, 1 - 44.1 KHz, 2 - 32 KHz, 3 - Reserved).
InstancePtr is a pointer to the XSdiAud instance. SRSt is a pointer to the sample rate information of each channel pair.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSdiAud_ReadReg, XSDIAUD_SR_STAT_REG_OFFSET.
void XSdiAud_Ext_GetAsxStatus(XSdiAud *InstancePtr, XSdiAud_AsxSt *AsxSt)
This function reads the ASX information decoded from audio control packet.
Bit 0 - Channel 1 & 2 Asx Bit 1 - Channel 3 & 4 Asx Bit 15 - Channel 31 & 32 Asx InstancePtr is a pointer to the XSdiAud instance. AsxSt is a pointer to the Asx status information of each channel pair.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_ASX_STAT_REG_OFFSET, XSdiAud_ReadReg.
void XSdiAud_ConfigReset(XSdiAud *InstancePtr)
This function is used to soft reset the XSdiAud registers.It resets all the configuration registers.
InstancePtr is a pointer to the XSdiAud instance.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSdiAud_ReadReg, XSDIAUD_SOFT_RST_ACLK_MASK, XSDIAUD_SOFT_RST_REG_OFFSET, XSdiAud_WriteReg.
Referenced by XSdiAud_SelfTest.
void XSdiAud_CoreReset(XSdiAud *InstancePtr, u8 RstCoreEnable)
This function is used to soft reset the XSdiAud core.
InstancePtr is a pointer to the XSdiAud instance. RstCoreEnable is to enable or disable. When set to 1(i.e.enable), it resets the embedded core. When set to 0, it clears the reset (i.e.disable).
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSdiAud_ReadReg, XSDIAUD_SOFT_RST_REG_OFFSET, XSDIAUD_SOFT_RST_SCLK_MASK, XSdiAud_WriteReg.
Referenced by XSdiAud_SelfTest.
static void XSdiAud_IntrClr(XSdiAud *InstancePtr, u32 Mask)
static void XSdiAud_IntrEnable(XSdiAud *InstancePtr, u32 Mask)
static void XSdiAud_IntrDisable(XSdiAud *InstancePtr, u32 Mask)
XSdiAud_Config * XSdiAud_LookupConfig(UINTPTR BaseAddress)
This function returns a reference to an XSdiAud_Config structure based on the core id, DeviceId.
The return value will refer to an entry in the device configuration table defined in the xsdiaud_g.c file. DeviceId is the unique core ID of the XSdiAud core for the lookup operation. returns a reference to a config record in the configuration table corresponding to DeviceId, or NULL if no match is found. None.
Referenced by XSdiAud_Initialize.
int XSdiAud_Initialize(XSdiAud *InstancePtr, UINTPTR BaseAddress)
Initializes a specific XsdiAud instance such that the driver is ready to use.
InstancePtr is a pointer to the XSdiAud instance to be worked on. DeviceId is the unique id of the device controlled by this XSdiAud instance. Passing in a device id associates the generic XSdiAud instance to a specific device, as chosen by the caller or application developer. XST_SUCCESS if successful.XST_DEVICE_NOT_FOUND if the device was not found in the configuration such that initialization could not be accomplished.XST_FAILURE if version mismatched
References XSdiAud_Config::BaseAddress, XSdiAud_CfgInitialize, XSdiAud_LookupConfig.
Referenced by SdiAud_SelfTestExample.
int XSdiAud_SelfTest(XSdiAud *InstancePtr)
Runs a self-test on the driver/device.
The self-test reads the XSdi_Aud registers and verifies the value. InstancePtr is a pointer to the XSdiAud instance. XST_SUCCESS if successful i.e. if the self test passes.XST_FAILURE if unsuccessful i.e. if the self test fails None.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSdiAud_Config::IsEmbed, XSdiAud_Config::LineRate, XSdiAud_Config::MaxNumChannels, XSDIAUD_10_CHANNELS, XSDIAUD_12_CHANNELS, XSDIAUD_14_CHANNELS, XSDIAUD_16_CHANNELS, XSDIAUD_2_CHANNELS, XSDIAUD_32_CHANNELS, XSDIAUD_4_CHANNELS, XSDIAUD_6_CHANNELS, XSDIAUD_8_CHANNELS, XSdiAud_ConfigReset, XSdiAud_CoreReset, XSDIAUD_EXT_CH_STAT0_REG_OFFSET, XSdiAud_GetCh, XSdiAud_GetSdiStd, XSdiAud_IsEmbed, XSdiAud_ReadReg.
Referenced by XSdiAud_CfgInitialize.
void XSdiAud_IntrHandler(void *InstancePtr)
This function is the interrupt handler for the XSdiaud driver.
This handler reads the pending interrupt from the XSdiaud peripheral, determines the source of the interrupts, clears the interrupts and calls call backs accordingly. InstancePtr is a pointer to the XSdiaud instance. None.
References XSdiAud::ActiveChannelChangeDetHandler, XSdiAud::ActiveChannelChangeDetHandlerRef, XSdiAud::AesCsChangeDetHandler, XSdiAud::AesCsChangeDetHandlerRef, XSdiAud::AesCsUpdateDetHandler, XSdiAud::AesCsUpdateDetHandlerRef, XSdiAud::AsxChangeDetHandler, XSdiAud::AsxChangeDetHandlerRef, XSdiAud_Config::BaseAddress, XSdiAud::ChecksumErrDetHandler, XSdiAud::ChecksumErrDetHandlerRef, XSdiAud::Config, XSdiAud::FifoOvrflwDetHandler, XSdiAud::FifoOvrflwDetHandlerRef, XSdiAud::GrpChangeDetHandler, XSdiAud::GrpChangeDetHandlerRef, XSdiAud::IsReady, XSdiAud::ParityErrDetHandler, XSdiAud::ParityErrDetHandlerRef, XSdiAud::SampleRateChangeDetHandler, XSdiAud::SampleRateChangeDetHandlerRef, XSdiAud::StatChangeDetHandler, XSdiAud::StatChangeDetHandlerRef, XSdiAud::VidPropChangeDetHandler, XSdiAud::VidPropChangeDetHandlerRef, XSDIAUD_EXT_INT_ST_CERR_MASK, XSDIAUD_EXT_INT_ST_FIFO_OF_MASK, XSDIAUD_EXT_INT_ST_PERR_MASK, XSDIAUD_EXT_INT_ST_VID_PROP_CHANGE_MASK, XSDIAUD_INT_EN_REG_OFFSET, XSDIAUD_INT_ST_AES_CS_CHANGE_MASK, XSDIAUD_INT_ST_AES_CS_UPDATE_MASK, XSDIAUD_INT_ST_ASX_CHANGE_MASK, XSDIAUD_INT_ST_AUD_STAT_UPDATE_MASK, XSDIAUD_INT_ST_CH_CHANGE_MASK, XSDIAUD_INT_ST_GRP_CHANGE_MASK, XSDIAUD_INT_ST_SMP_RATE_CHANGE_MASK, XSDIAUD_INT_STS_REG_OFFSET, XSdiAud_ReadReg.
int XSdiAud_SetHandler(XSdiAud *InstancePtr, XSdiAud_HandlerType HandlerType, XSdiAud_Callback FuncPtr, void *CallbackRef)
This function installs an asynchronous callback function for the given HandlerType.
HandlerType Callback Function ------------------------------------ ---------------------------------- (XSDIAUD_HANDLER_AUD_GRP_CHNG_DET) GrpChangeDetHandler (XSDIAUD_HANDLER_CNTRL_PKT_CHNG_DET) CntrlPktDetHandler (XSDIAUD_HANDLER_CHSTAT_CHNG_DET) StatChangeDetHandler (XSDIAUD_HANDLER_FIFO_OVRFLW_DET) FifoOvrflwDetHandler (XSDIAUD_HANDLER_PARITY_ERR_DET) ParityErrDetHandler (XSDIAUD_HANDLER_CHECKSUM_ERR_DET) ChecksumErrDetHandler InstancePtr is a pointer to the XSdiAud core instance. HandlerType specifies the type of handler. FuncPtr is a pointer to the callback function. CallbackRef is a reference pointer passed on actual calling of the callback function. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XSdiAud::ActiveChannelChangeDetHandler, XSdiAud::ActiveChannelChangeDetHandlerRef, XSdiAud::AesCsChangeDetHandler, XSdiAud::AesCsChangeDetHandlerRef, XSdiAud::AesCsUpdateDetHandler, XSdiAud::AesCsUpdateDetHandlerRef, XSdiAud::AsxChangeDetHandler, XSdiAud::AsxChangeDetHandlerRef, XSdiAud::ChecksumErrDetHandler, XSdiAud::ChecksumErrDetHandlerRef, XSdiAud::FifoOvrflwDetHandler, XSdiAud::FifoOvrflwDetHandlerRef, XSdiAud::GrpChangeDetHandler, XSdiAud::GrpChangeDetHandlerRef, XSdiAud::ParityErrDetHandler, XSdiAud::ParityErrDetHandlerRef, XSdiAud::SampleRateChangeDetHandler, XSdiAud::SampleRateChangeDetHandlerRef, XSdiAud::StatChangeDetHandler, XSdiAud::StatChangeDetHandlerRef, XSdiAud::VidPropChangeDetHandler, XSdiAud::VidPropChangeDetHandlerRef, XSDIAUD_HANDLER_ACT_CH_CHNG_DET, XSDIAUD_HANDLER_AES_CS_CHANGE_DET, XSDIAUD_HANDLER_AES_CS_UPDATE_DET, XSDIAUD_HANDLER_ASX_CHNG_DET, XSDIAUD_HANDLER_AUD_GRP_CHNG_DET, XSDIAUD_HANDLER_CHECKSUM_ERR_DET, XSDIAUD_HANDLER_CHSTAT_CHNG_DET, XSDIAUD_HANDLER_FIFO_OVRFLW_DET, XSDIAUD_HANDLER_PARITY_ERR_DET, XSDIAUD_HANDLER_SAMPLE_RATE_CHNG_DET, XSDIAUD_HANDLER_VIDEO_PROP_CHNG_DET, XSDIAUD_NUM_HANDLERS.
XSDIAUD_CHSTAT_NUMBER_OF_BYTES
BIT
Audio Embed total number of bytes in the 6 channel status registers.
Referenced by XSdiAud_GetActGrpStatus.
MAX_AUDIO_CHANNELS
MAX_AUDIO_GROUPS
XSdiAud_IsEmbed
This macro returns the XSdiAud operating mode.
InstancePtr is a pointer to the XSdiAud core instance. TRUE : Audio EmbedFALSE : Audio Extract C-style signature: u8 XSdiAud_IsEmbed(XSdiAud *InstancePtr)
Referenced by XSdiAud_SelfTest.
XSdiAud_GetSdiStd
This macro returns the XSdiAud UHD-SDI standard.
InstancePtr is a pointer to the XSdiAud core instance. UHD-SDI standard 0: 3G SDI 1: 6G SDI 2: 12G SDI 8DS 3: 12G SDI 16DS C-style signature: u8 XSdiAud_GetSdiStd(XSdiAud *InstancePtr)
Referenced by XSdiAud_SelfTest.
XSdiAud_GetCh
This macro returns the XSdiAud Channel field of the GUI register.
InstancePtr is a pointer to the XSdiAud core instance. Channel field of the GUI register i.e. a value in between 0 to 7 C-style signature: u8 XSdiAud_GetCh(XSdiAud *InstancePtr)
Referenced by XSdiAud_SelfTest.
ARRAY_SIZE
XSDIAUD_DEFAULT_VALUE
XSDIAUD_VALID_CH_CNT
XSDIAUD_CH_STS_REG_CNT
XSDIAUD_EMBREG_CNT
XSDIAUD_EXTREG_CNT