xsdiaud.c
XSDIAUD_CHSTAT_NUMBER_OF_BYTES
BIT
Audio Embed total number of bytes in the 6 channel status registers.
Referenced by XSdiAud_GetActGrpStatus.
u8 XSdiAud_CountBits(u32 n)
int XSdiAud_CfgInitialize(XSdiAud *InstancePtr, XSdiAud_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the XSdiAud.
This function must be called prior to using the core. Initialization of the XSdiAud includes setting up the instance data, and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the XSdiAud instance. CfgPtr points to the configuration structure associated with the XSdiAud. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS : if successful.XST_FAILURE : if version mismatched. None.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSdiAud::IsReady, XSdiAud_Enable, XSdiAud_SelfTest.
Referenced by XSdiAud_Initialize.
void XSdiAud_Enable(XSdiAud *InstancePtr, u8 Enable)
This function enables/disables the XSdiAud.
InstancePtr is a pointer to the XSdiAud instance. Enable specifies TRUE/FALSE value to either enable or disable the XSdiAud.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSdiAud::IsStarted, XSDIAUD_CNTRL_EN_MASK, XSDIAUD_CNTRL_REG_OFFSET, XSdiAud_ReadReg, XSdiAud_WriteReg.
Referenced by XSdiAud_CfgInitialize.
void XSdiAud_GetChStat(XSdiAud *InstancePtr, u8 *ChStatBuf)
This function reads all the Channel Status registers and writes to a buffer.
InstancePtr is a pointer to the XSdiAud instance. ChStatBuf is a pointer to a buffer.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_EXT_CH_STAT0_REG_OFFSET, XSdiAud_ReadReg.
u32 XSdiAud_GetCoreVersion(XSdiAud *InstancePtr)
This function reads the core version register and returns its value.
InstancePtr is a pointer to the XSdiAud instance. core version register value is returned.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_CORE_VERSION_REG_OFFSET, XSdiAud_ReadReg.
u32 XSdiAud_GetIntStat(XSdiAud *InstancePtr)
This function reads the Interrupt Status register and returns its value.
InstancePtr is a pointer to the XSdiAud instance. Interrupt status register value is returned.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_INT_STS_REG_OFFSET, XSdiAud_ReadReg.
void XSdiAud_Emb_SetSmpRate(XSdiAud *InstancePtr, XSdiAud_SampRate XSdiAud_SRate)
This Audio Embed function sets the sampling rate.
InstancePtr is a pointer to the XSdiAud instance. XSdiAud_SRate is the sampling rate, it is enum XSdiAud_SampRate, it can be anyone of these 000 - 48 KHz, 001 - 44.1 KHz, 010 - 32 KHz
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_AUD_CNTRL_REG_OFFSET, XSDIAUD_EMB_AUD_CNT_SR_MASK, XSdiAud_ReadReg, XSDIAUD_SMPLRATE_32, XSdiAud_WriteReg.
void XSdiAud_Emb_SetSmpSize(XSdiAud *InstancePtr, XSdiAud_SampSize XSdiAud_SSize)
This Audio Embed function sets the sample size in only SD Mode.
InstancePtr is a pointer to the XSdiAud instance. XSdiAud_SSize is the sample size, it is enum XSdiAud_SampSize, it can be 0 or 1. 0 - 20 Bit 1 - 24 Bit
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_AUD_CNTRL_REG_OFFSET, XSDIAUD_EMB_AUD_CNT_SS_MASK, XSDIAUD_EMB_AUD_CNT_SS_SHIFT, XSdiAud_ReadReg, XSdiAud_WriteReg.
void XSdiAud_Emb_SetAsx(XSdiAud *InstancePtr, XSdiAud_Asx XSdiAud_Async_data_flag)
This Audio Embed function sets the asynchronous data flag.
InstancePtr is a pointer to the XSdiAud instance. XSdiAud_Async_data_flag is the async data flag, it is enum XSdiAud_Asx, it can be 0 or 1. 0 - Synchronous audio 1 - Asynchronous audio
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_AUD_CNTRL_REG_OFFSET, XSDIAUD_EMB_AUD_CNT_ASX_MASK, XSDIAUD_EMB_AUD_CNT_ASX_SHIFT, XSdiAud_ReadReg, XSdiAud_WriteReg.
void XSdiAud_SetAesChPair(XSdiAud *InstancePtr, XSdiAud_AesChPair XSdiAud_ACP)
This Audio function selects the aes channel pair.
InstancePtr is a pointer to the XSdiAud instance. XSdiAud_ACP is the async data flag, it is enum XSdiAud_AesChPair, it can be any value between 0 to 16.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_AUD_CNTRL_REG_OFFSET, XSDIAUD_EMB_AUD_CNT_AES_CH_PAIR_MASK, XSDIAUD_EMB_AUD_CNT_AES_CH_PAIR_SHIFT, XSdiAud_ReadReg, XSdiAud_WriteReg.
void XSdiAud_Emb_SetVidProps(XSdiAud *InstancePtr, XSdiAud_Emb_Vid_Props *XSdiAud_VP)
This Audio Embed function sets the video properties of the image like transport scan, transport rate and transport family.
InstancePtr is a pointer to the XSdiAud instance. XSdiAud_VP is the struct containing the video family, rate and video scan information.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_EMB_VID_CNT_FAMILY_MASK, XSDIAUD_EMB_VID_CNT_FAMILY_SHIFT, XSDIAUD_EMB_VID_CNT_RATE_MASK, XSDIAUD_EMB_VID_CNT_RATE_SHIFT, XSDIAUD_EMB_VID_CNT_SCAN_MASK, XSDIAUD_EMB_VID_CNT_SCAN_SHIFT, XSDIAUD_EMB_VID_CNTRL_REG_OFFSET, XSdiAud_ReadReg, XSdiAud_Emb_Vid_Props::XSdiAud_TFamily, XSdiAud_Emb_Vid_Props::XSdiAud_TRate, XSdiAud_Emb_Vid_Props::XSdiAud_TScan, XSdiAud_WriteReg.
void XSdiAud_Emb_EnExtrnLine(XSdiAud *InstancePtr, u8 XSdiAud_En)
This Audio Embed function enables the external line number.
InstancePtr is a pointer to the XSdiAud instance. XSdiAud_En can be 0 or 1, 0 is to disable and 1 is to enable
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_EMB_VID_CNT_ELE_MASK, XSDIAUD_EMB_VID_CNT_ELE_SHIFT, XSDIAUD_EMB_VID_CNTRL_REG_OFFSET, XSdiAud_ReadReg, XSdiAud_WriteReg.
void XSdiAud_Ext_DisableClkPhase(XSdiAud *InstancePtr, u8 XSdiAud_SetClkP)
This Audio Extract function sets the clock phase.
InstancePtr is a pointer to the XSdiAud instance. XSdiAud_SetClkP enables the use of clock phase data, 0 is to enable 1 is to disable
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_AUD_CNTRL_REG_OFFSET, XSDIAUD_EXT_AUD_CNT_CP_EN_MASK, XSDIAUD_EXT_AUD_CNT_CP_EN_SHIFT, XSdiAud_ReadReg, XSdiAud_WriteReg.
void XSdiAud_GetActGrpStatus(XSdiAud *InstancePtr, XSdiAud_ActGrpSt *GrpSt)
This function detects the Audio groups and returns the groups which are present.
InstancePtr is a pointer to the XSdiAud instance. GrpSt is a pointer tp no. of active groups and also which groups are active.
References XSdiAud_Config::BaseAddress, BIT, XSdiAud::Config, XSDIAUD_ACT_GRP_PRES_REG_OFFSET, XSDIAUD_GRP_PRESNT_MASK, XSdiAud_ReadReg.
void XSdiAud_SetCh(XSdiAud *InstancePtr, u32 XSdiAudSetChMask)
This function sets the channel valid register.
Based on the mask provided the corresponding channels are embedded/extracted onto sdi. InstancePtr is a pointer to the XSdiAud instance. XSdiAudSetChMask is the 32 bit mask used to set the specific channels.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_VALID_CH_REG_OFFSET, XSdiAud_WriteReg.
void XSdiAud_MuteCh(XSdiAud *InstancePtr, u32 XSdiAudMuteChMask)
This function mutes a specific channel based on the mask provided.
InstancePtr is a pointer to the XSdiAud instance. XSdiAudMuteChMask is a 32 bit mask used to mute specific channels.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_MUTE_CH_REG_OFFSET, XSdiAud_WriteReg.
u8 XSdiAud_Ext_GetFIFOOvFlwStatus(XSdiAud *InstancePtr)
This function reads the FIFO overflow status.
Each bit when read as 1, indicates that RX Sample FIFO for that group is overflowing. InstancePtr is a pointer to the XSdiAud instance. Returns a u8 value, we can know the group overflowing using the bits set in this value.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_EXT_FIFO_OVFLW_ST_REG_OFFSET, XSdiAud_ReadReg.
void XSdiAud_Ext_GetAcChStatus(XSdiAud *InstancePtr, XSdiAud_ActChSt *ActChSt)
This function reads the active channel information decoded from audio control packet.
InstancePtr is a pointer to the XSdiAud instance. ActChSt is the pointer to no. of active channels and the channels active in each group.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_ACT_CH_STAT_REG_OFFSET, XSdiAud_ReadReg.
void XSdiAud_Ext_GetSRStatus(XSdiAud *InstancePtr, XSdiAud_SRSt *SRSt)
This function reads the sample rate information decoded from audio control packet (0 - 48 KHz, 1 - 44.1 KHz, 2 - 32 KHz, 3 - Reserved).
InstancePtr is a pointer to the XSdiAud instance. SRSt is a pointer to the sample rate information of each channel pair.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSdiAud_ReadReg, XSDIAUD_SR_STAT_REG_OFFSET.
void XSdiAud_Ext_GetAsxStatus(XSdiAud *InstancePtr, XSdiAud_AsxSt *AsxSt)
This function reads the ASX information decoded from audio control packet.
Bit 0 - Channel 1 & 2 Asx Bit 1 - Channel 3 & 4 Asx Bit 15 - Channel 31 & 32 Asx InstancePtr is a pointer to the XSdiAud instance. AsxSt is a pointer to the Asx status information of each channel pair.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_ASX_STAT_REG_OFFSET, XSdiAud_ReadReg.
void XSdiAud_ConfigReset(XSdiAud *InstancePtr)
This function is used to soft reset the XSdiAud registers.It resets all the configuration registers.
InstancePtr is a pointer to the XSdiAud instance.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSdiAud_ReadReg, XSDIAUD_SOFT_RST_ACLK_MASK, XSDIAUD_SOFT_RST_REG_OFFSET, XSdiAud_WriteReg.
Referenced by XSdiAud_SelfTest.
void XSdiAud_CoreReset(XSdiAud *InstancePtr, u8 RstCoreEnable)
This function is used to soft reset the XSdiAud core.
InstancePtr is a pointer to the XSdiAud instance. RstCoreEnable is to enable or disable. When set to 1(i.e.enable), it resets the embedded core. When set to 0, it clears the reset (i.e.disable).
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSdiAud_ReadReg, XSDIAUD_SOFT_RST_REG_OFFSET, XSDIAUD_SOFT_RST_SCLK_MASK, XSdiAud_WriteReg.
Referenced by XSdiAud_SelfTest.