xsdiaud.h
XSdiAud_HandlerType
Audio group change detect handler.
XSdiAud_GrpNum
Group 1.
XSdiAud_SampRate
000 - 48 KHz
XSdiAud_SampSize
0 - 20 Bit Audio Sample
XSdiAud_AesChPair
XSdiAud_Asx
XSdiAud_GrpXChNum
Channel 1 of Group 1/2/3/4.
XSdiAud_VidRate
XSdiAud_VidScan
XSdiAud_VidFam
XSdiAud_NumOfCh
1 channel
XSdiAud_ChNum
channel 1
typedef void(* XSdiAud_Callback)(void *CallbackRef))(void *CallbackRef)
Callback function pointer type for SDI audio events, invoked with a user-defined reference parameter.
MAX_AUDIO_CHANNELS
MAX_AUDIO_GROUPS
static void XSdiAud_IntrClr(XSdiAud *InstancePtr, u32 Mask)
static void XSdiAud_IntrEnable(XSdiAud *InstancePtr, u32 Mask)
static void XSdiAud_IntrDisable(XSdiAud *InstancePtr, u32 Mask)
XSdiAud_Config * XSdiAud_LookupConfig(UINTPTR BaseAddress)
This function returns a reference to an XSdiAud_Config structure based on the core id, DeviceId.
The return value will refer to an entry in the device configuration table defined in the xsdiaud_g.c file. DeviceId is the unique core ID of the XSdiAud core for the lookup operation. returns a reference to a config record in the configuration table corresponding to DeviceId, or NULL if no match is found. None.
Referenced by XSdiAud_Initialize.
int XSdiAud_Initialize(XSdiAud *InstancePtr, UINTPTR BaseAddress)
Initializes a specific XsdiAud instance such that the driver is ready to use.
InstancePtr is a pointer to the XSdiAud instance to be worked on. DeviceId is the unique id of the device controlled by this XSdiAud instance. Passing in a device id associates the generic XSdiAud instance to a specific device, as chosen by the caller or application developer. XST_SUCCESS if successful.XST_DEVICE_NOT_FOUND if the device was not found in the configuration such that initialization could not be accomplished.XST_FAILURE if version mismatched
References XSdiAud_Config::BaseAddress, XSdiAud_CfgInitialize, XSdiAud_LookupConfig.
Referenced by SdiAud_SelfTestExample.
int XSdiAud_CfgInitialize(XSdiAud *InstancePtr, XSdiAud_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the XSdiAud.
This function must be called prior to using the core. Initialization of the XSdiAud includes setting up the instance data, and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the XSdiAud instance. CfgPtr points to the configuration structure associated with the XSdiAud. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS : if successful.XST_FAILURE : if version mismatched. None.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSdiAud::IsReady, XSdiAud_Enable, XSdiAud_SelfTest.
Referenced by XSdiAud_Initialize.
void XSdiAud_Enable(XSdiAud *InstancePtr, u8 Enable)
This function enables/disables the XSdiAud.
InstancePtr is a pointer to the XSdiAud instance. Enable specifies TRUE/FALSE value to either enable or disable the XSdiAud.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSdiAud::IsStarted, XSDIAUD_CNTRL_EN_MASK, XSDIAUD_CNTRL_REG_OFFSET, XSdiAud_ReadReg, XSdiAud_WriteReg.
Referenced by XSdiAud_CfgInitialize.
int XSdiAud_SelfTest(XSdiAud *InstancePtr)
Runs a self-test on the driver/device.
The self-test reads the XSdi_Aud registers and verifies the value. InstancePtr is a pointer to the XSdiAud instance. XST_SUCCESS if successful i.e. if the self test passes.XST_FAILURE if unsuccessful i.e. if the self test fails None.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSdiAud_Config::IsEmbed, XSdiAud_Config::LineRate, XSdiAud_Config::MaxNumChannels, XSDIAUD_10_CHANNELS, XSDIAUD_12_CHANNELS, XSDIAUD_14_CHANNELS, XSDIAUD_16_CHANNELS, XSDIAUD_2_CHANNELS, XSDIAUD_32_CHANNELS, XSDIAUD_4_CHANNELS, XSDIAUD_6_CHANNELS, XSDIAUD_8_CHANNELS, XSdiAud_ConfigReset, XSdiAud_CoreReset, XSDIAUD_EXT_CH_STAT0_REG_OFFSET, XSdiAud_GetCh, XSdiAud_GetSdiStd, XSdiAud_IsEmbed, XSdiAud_ReadReg.
Referenced by XSdiAud_CfgInitialize.
void XSdiAud_CoreReset(XSdiAud *InstancePtr, u8 RstCoreEnable)
This function is used to soft reset the XSdiAud core.
InstancePtr is a pointer to the XSdiAud instance. RstCoreEnable is to enable or disable. When set to 1(i.e.enable), it resets the embedded core. When set to 0, it clears the reset (i.e.disable).
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSdiAud_ReadReg, XSDIAUD_SOFT_RST_REG_OFFSET, XSDIAUD_SOFT_RST_SCLK_MASK, XSdiAud_WriteReg.
Referenced by XSdiAud_SelfTest.
void XSdiAud_ConfigReset(XSdiAud *InstancePtr)
This function is used to soft reset the XSdiAud registers.It resets all the configuration registers.
InstancePtr is a pointer to the XSdiAud instance.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSdiAud_ReadReg, XSDIAUD_SOFT_RST_ACLK_MASK, XSDIAUD_SOFT_RST_REG_OFFSET, XSdiAud_WriteReg.
Referenced by XSdiAud_SelfTest.
void XSdiAud_IntrHandler(void *InstancePtr)
This function is the interrupt handler for the XSdiaud driver.
This handler reads the pending interrupt from the XSdiaud peripheral, determines the source of the interrupts, clears the interrupts and calls call backs accordingly. InstancePtr is a pointer to the XSdiaud instance. None.
References XSdiAud::ActiveChannelChangeDetHandler, XSdiAud::ActiveChannelChangeDetHandlerRef, XSdiAud::AesCsChangeDetHandler, XSdiAud::AesCsChangeDetHandlerRef, XSdiAud::AesCsUpdateDetHandler, XSdiAud::AesCsUpdateDetHandlerRef, XSdiAud::AsxChangeDetHandler, XSdiAud::AsxChangeDetHandlerRef, XSdiAud_Config::BaseAddress, XSdiAud::ChecksumErrDetHandler, XSdiAud::ChecksumErrDetHandlerRef, XSdiAud::Config, XSdiAud::FifoOvrflwDetHandler, XSdiAud::FifoOvrflwDetHandlerRef, XSdiAud::GrpChangeDetHandler, XSdiAud::GrpChangeDetHandlerRef, XSdiAud::IsReady, XSdiAud::ParityErrDetHandler, XSdiAud::ParityErrDetHandlerRef, XSdiAud::SampleRateChangeDetHandler, XSdiAud::SampleRateChangeDetHandlerRef, XSdiAud::StatChangeDetHandler, XSdiAud::StatChangeDetHandlerRef, XSdiAud::VidPropChangeDetHandler, XSdiAud::VidPropChangeDetHandlerRef, XSDIAUD_EXT_INT_ST_CERR_MASK, XSDIAUD_EXT_INT_ST_FIFO_OF_MASK, XSDIAUD_EXT_INT_ST_PERR_MASK, XSDIAUD_EXT_INT_ST_VID_PROP_CHANGE_MASK, XSDIAUD_INT_EN_REG_OFFSET, XSDIAUD_INT_ST_AES_CS_CHANGE_MASK, XSDIAUD_INT_ST_AES_CS_UPDATE_MASK, XSDIAUD_INT_ST_ASX_CHANGE_MASK, XSDIAUD_INT_ST_AUD_STAT_UPDATE_MASK, XSDIAUD_INT_ST_CH_CHANGE_MASK, XSDIAUD_INT_ST_GRP_CHANGE_MASK, XSDIAUD_INT_ST_SMP_RATE_CHANGE_MASK, XSDIAUD_INT_STS_REG_OFFSET, XSdiAud_ReadReg.
int XSdiAud_SetHandler(XSdiAud *InstancePtr, XSdiAud_HandlerType HandlerType, XSdiAud_Callback FuncPtr, void *CallbackRef)
This function installs an asynchronous callback function for the given HandlerType.
HandlerType Callback Function ------------------------------------ ---------------------------------- (XSDIAUD_HANDLER_AUD_GRP_CHNG_DET) GrpChangeDetHandler (XSDIAUD_HANDLER_CNTRL_PKT_CHNG_DET) CntrlPktDetHandler (XSDIAUD_HANDLER_CHSTAT_CHNG_DET) StatChangeDetHandler (XSDIAUD_HANDLER_FIFO_OVRFLW_DET) FifoOvrflwDetHandler (XSDIAUD_HANDLER_PARITY_ERR_DET) ParityErrDetHandler (XSDIAUD_HANDLER_CHECKSUM_ERR_DET) ChecksumErrDetHandler InstancePtr is a pointer to the XSdiAud core instance. HandlerType specifies the type of handler. FuncPtr is a pointer to the callback function. CallbackRef is a reference pointer passed on actual calling of the callback function. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XSdiAud::ActiveChannelChangeDetHandler, XSdiAud::ActiveChannelChangeDetHandlerRef, XSdiAud::AesCsChangeDetHandler, XSdiAud::AesCsChangeDetHandlerRef, XSdiAud::AesCsUpdateDetHandler, XSdiAud::AesCsUpdateDetHandlerRef, XSdiAud::AsxChangeDetHandler, XSdiAud::AsxChangeDetHandlerRef, XSdiAud::ChecksumErrDetHandler, XSdiAud::ChecksumErrDetHandlerRef, XSdiAud::FifoOvrflwDetHandler, XSdiAud::FifoOvrflwDetHandlerRef, XSdiAud::GrpChangeDetHandler, XSdiAud::GrpChangeDetHandlerRef, XSdiAud::ParityErrDetHandler, XSdiAud::ParityErrDetHandlerRef, XSdiAud::SampleRateChangeDetHandler, XSdiAud::SampleRateChangeDetHandlerRef, XSdiAud::StatChangeDetHandler, XSdiAud::StatChangeDetHandlerRef, XSdiAud::VidPropChangeDetHandler, XSdiAud::VidPropChangeDetHandlerRef, XSDIAUD_HANDLER_ACT_CH_CHNG_DET, XSDIAUD_HANDLER_AES_CS_CHANGE_DET, XSDIAUD_HANDLER_AES_CS_UPDATE_DET, XSDIAUD_HANDLER_ASX_CHNG_DET, XSDIAUD_HANDLER_AUD_GRP_CHNG_DET, XSDIAUD_HANDLER_CHECKSUM_ERR_DET, XSDIAUD_HANDLER_CHSTAT_CHNG_DET, XSDIAUD_HANDLER_FIFO_OVRFLW_DET, XSDIAUD_HANDLER_PARITY_ERR_DET, XSDIAUD_HANDLER_SAMPLE_RATE_CHNG_DET, XSDIAUD_HANDLER_VIDEO_PROP_CHNG_DET, XSDIAUD_NUM_HANDLERS.
u32 XSdiAud_GetCoreVersion(XSdiAud *InstancePtr)
This function reads the core version register and returns its value.
InstancePtr is a pointer to the XSdiAud instance. core version register value is returned.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_CORE_VERSION_REG_OFFSET, XSdiAud_ReadReg.
u32 XSdiAud_GetIntStat(XSdiAud *InstancePtr)
This function reads the Interrupt Status register and returns its value.
InstancePtr is a pointer to the XSdiAud instance. Interrupt status register value is returned.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_INT_STS_REG_OFFSET, XSdiAud_ReadReg.
void XSdiAud_Emb_SetSmpRate(XSdiAud *InstancePtr, XSdiAud_SampRate XSdiAud_SRate)
This Audio Embed function sets the sampling rate.
InstancePtr is a pointer to the XSdiAud instance. XSdiAud_SRate is the sampling rate, it is enum XSdiAud_SampRate, it can be anyone of these 000 - 48 KHz, 001 - 44.1 KHz, 010 - 32 KHz
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_AUD_CNTRL_REG_OFFSET, XSDIAUD_EMB_AUD_CNT_SR_MASK, XSdiAud_ReadReg, XSDIAUD_SMPLRATE_32, XSdiAud_WriteReg.
void XSdiAud_Emb_SetSmpSize(XSdiAud *InstancePtr, XSdiAud_SampSize XSdiAud_SSize)
This Audio Embed function sets the sample size in only SD Mode.
InstancePtr is a pointer to the XSdiAud instance. XSdiAud_SSize is the sample size, it is enum XSdiAud_SampSize, it can be 0 or 1. 0 - 20 Bit 1 - 24 Bit
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_AUD_CNTRL_REG_OFFSET, XSDIAUD_EMB_AUD_CNT_SS_MASK, XSDIAUD_EMB_AUD_CNT_SS_SHIFT, XSdiAud_ReadReg, XSdiAud_WriteReg.
void XSdiAud_Emb_SetAsx(XSdiAud *InstancePtr, XSdiAud_Asx XSdiAud_Async_data_flag)
This Audio Embed function sets the asynchronous data flag.
InstancePtr is a pointer to the XSdiAud instance. XSdiAud_Async_data_flag is the async data flag, it is enum XSdiAud_Asx, it can be 0 or 1. 0 - Synchronous audio 1 - Asynchronous audio
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_AUD_CNTRL_REG_OFFSET, XSDIAUD_EMB_AUD_CNT_ASX_MASK, XSDIAUD_EMB_AUD_CNT_ASX_SHIFT, XSdiAud_ReadReg, XSdiAud_WriteReg.
void XSdiAud_SetAesChPair(XSdiAud *InstancePtr, XSdiAud_AesChPair XSdiAud_ACP)
This Audio function selects the aes channel pair.
InstancePtr is a pointer to the XSdiAud instance. XSdiAud_ACP is the async data flag, it is enum XSdiAud_AesChPair, it can be any value between 0 to 16.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_AUD_CNTRL_REG_OFFSET, XSDIAUD_EMB_AUD_CNT_AES_CH_PAIR_MASK, XSDIAUD_EMB_AUD_CNT_AES_CH_PAIR_SHIFT, XSdiAud_ReadReg, XSdiAud_WriteReg.
void XSdiAud_Emb_SetVidProps(XSdiAud *InstancePtr, XSdiAud_Emb_Vid_Props *XSdiAud_VP)
This Audio Embed function sets the video properties of the image like transport scan, transport rate and transport family.
InstancePtr is a pointer to the XSdiAud instance. XSdiAud_VP is the struct containing the video family, rate and video scan information.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_EMB_VID_CNT_FAMILY_MASK, XSDIAUD_EMB_VID_CNT_FAMILY_SHIFT, XSDIAUD_EMB_VID_CNT_RATE_MASK, XSDIAUD_EMB_VID_CNT_RATE_SHIFT, XSDIAUD_EMB_VID_CNT_SCAN_MASK, XSDIAUD_EMB_VID_CNT_SCAN_SHIFT, XSDIAUD_EMB_VID_CNTRL_REG_OFFSET, XSdiAud_ReadReg, XSdiAud_Emb_Vid_Props::XSdiAud_TFamily, XSdiAud_Emb_Vid_Props::XSdiAud_TRate, XSdiAud_Emb_Vid_Props::XSdiAud_TScan, XSdiAud_WriteReg.
void XSdiAud_Emb_EnExtrnLine(XSdiAud *InstancePtr, u8 XSdiAud_En)
This Audio Embed function enables the external line number.
InstancePtr is a pointer to the XSdiAud instance. XSdiAud_En can be 0 or 1, 0 is to disable and 1 is to enable
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_EMB_VID_CNT_ELE_MASK, XSDIAUD_EMB_VID_CNT_ELE_SHIFT, XSDIAUD_EMB_VID_CNTRL_REG_OFFSET, XSdiAud_ReadReg, XSdiAud_WriteReg.
void XSdiAud_Ext_DisableClkPhase(XSdiAud *InstancePtr, u8 XSdiAud_SetClkP)
This Audio Extract function sets the clock phase.
InstancePtr is a pointer to the XSdiAud instance. XSdiAud_SetClkP enables the use of clock phase data, 0 is to enable 1 is to disable
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_AUD_CNTRL_REG_OFFSET, XSDIAUD_EXT_AUD_CNT_CP_EN_MASK, XSDIAUD_EXT_AUD_CNT_CP_EN_SHIFT, XSdiAud_ReadReg, XSdiAud_WriteReg.
void XSdiAud_GetChStat(XSdiAud *InstancePtr, u8 *ChStatBuf)
This function reads all the Channel Status registers and writes to a buffer.
InstancePtr is a pointer to the XSdiAud instance. ChStatBuf is a pointer to a buffer.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_EXT_CH_STAT0_REG_OFFSET, XSdiAud_ReadReg.
void XSdiAud_GetActGrpStatus(XSdiAud *InstancePtr, XSdiAud_ActGrpSt *GrpSt)
This function detects the Audio groups and returns the groups which are present.
InstancePtr is a pointer to the XSdiAud instance. GrpSt is a pointer tp no. of active groups and also which groups are active.
References XSdiAud_Config::BaseAddress, BIT, XSdiAud::Config, XSDIAUD_ACT_GRP_PRES_REG_OFFSET, XSDIAUD_GRP_PRESNT_MASK, XSdiAud_ReadReg.
void XSdiAud_SetCh(XSdiAud *InstancePtr, u32 XSdiAudSetChMask)
This function sets the channel valid register.
Based on the mask provided the corresponding channels are embedded/extracted onto sdi. InstancePtr is a pointer to the XSdiAud instance. XSdiAudSetChMask is the 32 bit mask used to set the specific channels.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_VALID_CH_REG_OFFSET, XSdiAud_WriteReg.
void XSdiAud_MuteCh(XSdiAud *InstancePtr, u32 XSdiAudMuteChMask)
This function mutes a specific channel based on the mask provided.
InstancePtr is a pointer to the XSdiAud instance. XSdiAudMuteChMask is a 32 bit mask used to mute specific channels.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_MUTE_CH_REG_OFFSET, XSdiAud_WriteReg.
u8 XSdiAud_Ext_GetFIFOOvFlwStatus(XSdiAud *InstancePtr)
This function reads the FIFO overflow status.
Each bit when read as 1, indicates that RX Sample FIFO for that group is overflowing. InstancePtr is a pointer to the XSdiAud instance. Returns a u8 value, we can know the group overflowing using the bits set in this value.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_EXT_FIFO_OVFLW_ST_REG_OFFSET, XSdiAud_ReadReg.
void XSdiAud_Ext_GetAcChStatus(XSdiAud *InstancePtr, XSdiAud_ActChSt *ActChSt)
This function reads the active channel information decoded from audio control packet.
InstancePtr is a pointer to the XSdiAud instance. ActChSt is the pointer to no. of active channels and the channels active in each group.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_ACT_CH_STAT_REG_OFFSET, XSdiAud_ReadReg.
void XSdiAud_Ext_GetSRStatus(XSdiAud *InstancePtr, XSdiAud_SRSt *SRSt)
This function reads the sample rate information decoded from audio control packet (0 - 48 KHz, 1 - 44.1 KHz, 2 - 32 KHz, 3 - Reserved).
InstancePtr is a pointer to the XSdiAud instance. SRSt is a pointer to the sample rate information of each channel pair.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSdiAud_ReadReg, XSDIAUD_SR_STAT_REG_OFFSET.
void XSdiAud_Ext_GetAsxStatus(XSdiAud *InstancePtr, XSdiAud_AsxSt *AsxSt)
This function reads the ASX information decoded from audio control packet.
Bit 0 - Channel 1 & 2 Asx Bit 1 - Channel 3 & 4 Asx Bit 15 - Channel 31 & 32 Asx InstancePtr is a pointer to the XSdiAud instance. AsxSt is a pointer to the Asx status information of each channel pair.
References XSdiAud_Config::BaseAddress, XSdiAud::Config, XSDIAUD_ASX_STAT_REG_OFFSET, XSdiAud_ReadReg.