xiicps_options.c
s32 XIicPs_SetOptions(XIicPs *InstancePtr, u32 Options)
Functions for setting and getting data rate, in xiicps_options.c.
Sets the options for the IIC device driver.The options control how the device behaves relative to the IIC bus. The device must be idle rather than busy transferring data before setting these device options. InstancePtr Pointer to the XIicPs instance. Options Contains the specified options to be set. This is a bit mask where a 1 means to turn the option on. One or more bit values may be contained in the mask. See the bit definitions named XIICPS_*_OPTION in xiicps.h. XST_SUCCESS if options are successfully set.XST_DEVICE_IS_STARTED if the device is currently transferring data. The transfer must complete or be aborted before setting options. None.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::Is10BitAddr, XIicPs::IsReady, XIicPs::IsRepeatedStart, XIicPs::Options, XIICPS_10_BIT_ADDR_OPTION, XIICPS_CR_OFFSET, XIicPs_GetOptions, XIICPS_NUM_OPTIONS, XIicPs_ReadReg, XIICPS_REP_START_OPTION, XIicPs_WriteReg.
Referenced by EepromReadDataRepStart, XIicPsSmbusMasterReadBlockData, XIicPsSmbusPolledMasterReadBlockData.
s32 XIicPs_ClearOptions(XIicPs *InstancePtr, u32 Options)
Clears the options for the IIC device driver.
The options control how the device behaves relative to the IIC bus. The device must be idle rather than busy transferring data before setting these device options. InstancePtr Pointer to the XIicPs instance. Options Contains the specified options to be cleared. This is a bit mask where a 1 means to turn the option off. One or more bit values may be contained in the mask. See the bit definitions named XIICPS_*_OPTION in xiicps.h. XST_SUCCESS if options are successfully set.XST_DEVICE_IS_STARTED if the device is currently transferring data. The transfer must complete or be aborted before setting options. None
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::Is10BitAddr, XIicPs::IsReady, XIicPs::IsRepeatedStart, XIicPs::Options, XIICPS_10_BIT_ADDR_OPTION, XIICPS_CR_OFFSET, XIicPs_GetOptions, XIICPS_NUM_OPTIONS, XIicPs_ReadReg, XIICPS_REP_START_OPTION, XIicPs_WriteReg.
Referenced by EepromReadDataRepStart, XIicPsSmbusMasterReadBlockData, XIicPsSmbusPolledMasterReadBlockData.
u32 XIicPs_GetOptions(XIicPs *InstancePtr)
Gets the options for the IIC device.
The options control how the device behaves relative to the IIC bus. InstancePtr Pointer to the XIicPs instance. 32 bit mask of the options, where a 1 means the option is on, and a 0 means to the option is off. One or more bit values may be contained in the mask. See the bit definitions named XIICPS_*_OPTION in the file xiicps.h. None.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::IsReady, XIicPs::IsRepeatedStart, XIICPS_10_BIT_ADDR_OPTION, XIICPS_7_BIT_ADDR_OPTION, XIICPS_CR_OFFSET, XIICPS_NUM_OPTIONS, XIicPs_ReadReg, XIICPS_REP_START_OPTION.
Referenced by XIicPs_CfgInitialize, XIicPs_ClearOptions, XIicPs_SetOptions.
s32 XIicPs_SetSClk(XIicPs *InstancePtr, u32 FsclHz)
Sets the serial clock rate for the IIC device.
The device must be idle rather than busy transferring data before setting these device options.The data rate is set by values in the control register. The formula for determining the correct register values is: Fscl = Fpclk/(22 x (divisor_a+1) x (divisor_b+1)) See the hardware data sheet for a full explanation of setting the serial clock rate. InstancePtr Pointer to the XIicPs instance. FsclHz Clock frequency in Hz. The two most common clock rates are 100KHz and 400KHz. XST_SUCCESS if options are successfully set.XST_DEVICE_IS_STARTED if the device is currently transferring data. The transfer must complete or be aborted before setting options.XST_FAILURE if the Fscl frequency can not be set. The clock can not be faster than the input clock divide by 22.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs_Config::InputClockHz, XIicPs::IsReady, XIICPS_CR_OFFSET, XIicPs_ReadReg, XIICPS_TRANS_SIZE_OFFSET, XIicPs_WriteReg.
Referenced by IicPsMasterIntrExample, IicPsMasterPolledExample, IicPsMultiMasterIntrExample, IicPsMultiMasterPolledExample, IicPsRepeatedStartExample, IicPsSlaveIntrExample, IicPsSlavePolledExample, IicPsSmbusSlaveIntrExample, IicPsSmbusSlavePolledExample, XIicPsSmbusMasterIntrExample.
u32 XIicPs_GetSClk(XIicPs *InstancePtr)
Sets the serial clock rate for the IIC device.
The device must be idle rather than busy transferring data before setting these device options. InstancePtr Pointer to the XIicPs instance. The value of the IIC clock to the nearest Hz based on the control register settings. The actual value may not be exact to to integer math rounding errors. None.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs_Config::InputClockHz, XIicPs::IsReady, XIICPS_CR_OFFSET, XIicPs_ReadReg.
XIICPS_NUM_OPTIONS
Calculated no.
of options
Referenced by XIicPs_ClearOptions, XIicPs_GetOptions, XIicPs_SetOptions.
OptionsMap OptionsTable[][]