xiicps.h
XIICPS_7_BIT_ADDR_OPTION
7-bit address mode
Referenced by XIicPs_GetOptions.
XIICPS_10_BIT_ADDR_OPTION
10-bit address mode
Referenced by XIicPs_ClearOptions, XIicPs_GetOptions, XIicPs_SetOptions.
XIICPS_SLAVE_MON_OPTION
Slave monitor mode.
XIICPS_REP_START_OPTION
Repeated Start.
Referenced by EepromReadDataRepStart, XIicPs_ClearOptions, XIicPs_GetOptions, XIicPs_SetOptions, XIicPsSmbusMasterReadBlockData, XIicPsSmbusPolledMasterReadBlockData.
XIICPS_EVENT_COMPLETE_SEND
Transmit Complete Event.
Referenced by Handler, XIicPs_MasterIntrSend, XIicPs_SlaveInterruptHandler.
XIICPS_EVENT_COMPLETE_RECV
Receive Complete Event.
Referenced by Handler, XIicPs_MasterInterruptHandler, XIicPs_SlaveInterruptHandler.
XIICPS_EVENT_TIME_OUT
Transfer timed out.
Referenced by XIicPs_MasterInterruptHandler, XIicPs_SlaveInterruptHandler.
XIICPS_EVENT_ERROR
Receive error.
Referenced by XIicPs_MasterInterruptHandler, XIicPs_SlaveInterruptHandler.
XIICPS_EVENT_ARB_LOST
Arbitration lost.
Referenced by XIicPs_MasterInterruptHandler.
XIICPS_EVENT_NACK
NACK Received.
Referenced by XIicPs_MasterInterruptHandler, XIicPs_SlaveInterruptHandler.
XIICPS_EVENT_SLAVE_RDY
Slave ready.
Referenced by Handler, XIicPs_MasterInterruptHandler.
XIICPS_EVENT_RX_OVR
RX overflow.
XIICPS_EVENT_TX_OVR
TX overflow.
XIICPS_EVENT_RX_UNF
RX underflow.
s32 XIicPs_CfgInitialize(XIicPs *InstancePtr, XIicPs_Config *ConfigPtr, u32 EffectiveAddr)
Initializes a specific XIicPs instance so that the driver is ready to use.
Functions for general setup, in xiicps.c.The state of the device after initialization is: Device is disabledSlave mode InstancePtr Pointer to the XIicPs instance. ConfigPtr Reference to a structure containing information about a specific IIC device. This function initializes an InstancePtr object for a specific device specified by the contents of Config. EffectiveAddr Device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, use ConfigPtr->BaseAddress for this parameter, passing the physical address instead. The return value is XST_SUCCESS if successful.
References XIicPs_Config::BaseAddress, XIicPs::CallBackRef, XIicPs::Config, XIicPs_Config::InputClockHz, XIicPs::IsReady, XIicPs::IsRepeatedStart, XIicPs::Options, XIicPs_Config::RefClk, XIicPs::StatusHandler, XIicPs_GetOptions, XIicPs_Reset.
Referenced by IicPsMasterIntrExample, IicPsMasterPolledExample, IicPsMultiMasterIntrExample, IicPsMultiMasterPolledExample, IicPsRepeatedStartExample, IicPsSelfTestExample, IicPsSlaveIntrExample, IicPsSlavePolledExample, IicPsSmbusSlaveIntrExample, IicPsSmbusSlavePolledExample, XIicPsSmbusMasterIntrExample.
void XIicPs_Abort(XIicPs *InstancePtr)
Aborts a transfer in progress by resetting the FIFOs.
The byte counts are cleared. InstancePtr Pointer to the XIicPs instance. None.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::IsReady, XIICPS_CR_OFFSET, XIICPS_IDR_OFFSET, XIICPS_IER_OFFSET, XIICPS_IMR_OFFSET, XIICPS_ISR_OFFSET, XIICPS_IXR_ALL_INTR_MASK, XIicPs_ReadReg, XIicPs_WriteReg.
Referenced by XIicPs_Reset.
void XIicPs_Reset(XIicPs *InstancePtr)
Resets the IIC device.
Reset must only be called after the driver has been initialized. The configuration of the device after reset is the same as its configuration after initialization. Any data transfer that is in progress is aborted.The upper layer software is responsible for re-configuring (if necessary) and reenabling interrupts for the IIC device after the reset. InstancePtr Pointer to the XIicPs instance. None.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::IsReady, XIicPs_Abort, XIICPS_CR_OFFSET, XIICPS_IDR_OFFSET, XIICPS_IXR_ALL_INTR_MASK, XIICPS_TIME_OUT_OFFSET, XIicPs_WriteReg.
Referenced by XIicPs_CfgInitialize, XIicPs_SelfTest.
s32 XIicPs_BusIsBusy(XIicPs *InstancePtr)
Checks the availability of the I2C bus.
InstancePtr Pointer to the XIicPs instance. TRUE if the bus is busy. FALSE if the bus is not busy.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs_Config::RefClk, XIicPs_ReadReg, XIICPS_SR_OFFSET.
Referenced by EepromReadDataRepStart, EepromWriteData, IicPsMasterIntrExample, IicPsMasterPolledExample, IicPsMultiMasterIntrExample, IicPsMultiMasterPolledExample, IicPsSlaveIntrExample, IicPsSlavePolledExample, XIicPs_SetupMaster, XIicPsSmbusMasterIntrExample, XIicPsSmbusMasterReadBlockData, XIicPsSmbusMasterWriteBlockData, XIicPsSmbusPolledMasterReadBlockData, XIicPsSmbusPolledMasterWriteBlockData.
s32 TransmitFifoFill(XIicPs *InstancePtr)
Puts more data into the transmit FIFO.
The number of bytes is either the expected number of bytes for this transfer or available space in FIFO, which ever is less. InstancePtr Pointer to the XIicPs instance. Number of bytes left for this instance. This is function is shared by the master and slave.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::SendByteCount, XIicPs_ReadReg, XIicPs_SendByte, XIICPS_TRANS_SIZE_OFFSET.
Referenced by MasterSendData, XIicPs_MasterSend, XIicPs_MasterSendPolled, XIicPs_SlaveInterruptHandler.
s32 XIicPs_BusRecovery(XIicPs *InstancePtr)
Performs I2C bus recovery using the PS I2C controller HOLD feature.
This API is used when the I2C controller is already in Master mode and the bus is stuck due to a slave holding SDA low. The API toggles the HOLD bit to manually generate SCL pulses, allowing the slave to release the bus. InstancePtr Pointer to the XIicPs instance. XST_SUCCESS if recovery sequence is executed. XST_FAILURE if controller is not in Master mode.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIICPS_CR_OFFSET, XIicPs_ReadReg, XIICPS_RECOVERY_DELAY, XIICPS_RECOVERY_PULSES, XIicPs_WriteReg.
void XIicPs_MasterSend(XIicPs *InstancePtr, u8 *MsgPtr, s32 ByteCount, u16 SlaveAddr)
Functions for device as master, in xiicps_master.c.
Initiates an interrupt-driven send in master mode.It tries to send the first FIFO full of data, then lets the interrupt handler to handle the rest of the data if there is any. InstancePtr Pointer to the XIicPs instance. MsgPtr Pointer to the send buffer. ByteCount Number of bytes to be sent. SlaveAddr Address of the slave we are sending to. None. This send routine is for interrupt-driven transfer only.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::IsReady, XIicPs::IsRepeatedStart, XIicPs::IsSend, XIicPs::RecvBufferPtr, XIicPs_Config::RefClk, XIicPs::SendBufferPtr, XIicPs::SendByteCount, SENDING_ROLE, TransmitFifoFill, XIICPS_ADDR_OFFSET, XIICPS_CR_OFFSET, XIicPs_EnableInterrupts, XIICPS_ISR_OFFSET, XIICPS_IXR_ALL_INTR_MASK, XIICPS_IXR_ARB_LOST_MASK, XIICPS_IXR_COMP_MASK, XIICPS_IXR_NACK_MASK, XIICPS_IXR_TO_MASK, XIicPs_ReadReg, XIicPs_SetupMaster, XIicPs_WriteReg.
Referenced by IicPsMasterIntrExample, IicPsMultiMasterIntrExample, XIicPsSmbusMasterReadBlockData, XIicPsSmbusMasterWriteBlockData.
void XIicPs_MasterRecv(XIicPs *InstancePtr, u8 *MsgPtr, s32 ByteCount, u16 SlaveAddr)
Initiates an interrupt-driven receive in master mode.
It sets the transfer size register so the slave can send data. The rest of the work is managed by interrupt handler. InstancePtr Pointer to the XIicPs instance. MsgPtr Pointer to the receive buffer. ByteCount Number of bytes to be received. SlaveAddr Address of the slave we are receiving from. None. This receive routine is for interrupt-driven transfer only.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::CurrByteCount, XIicPs::IsReady, XIicPs::IsRepeatedStart, XIicPs::IsSend, XIicPs::RecvBufferPtr, XIicPs::RecvByteCount, RECVING_ROLE, XIicPs_Config::RefClk, XIicPs::SendBufferPtr, XIicPs::UpdateTxSize, XIICPS_ADDR_OFFSET, XIICPS_CR_OFFSET, XIicPs_EnableInterrupts, XIICPS_ISR_OFFSET, XIICPS_IXR_ALL_INTR_MASK, XIICPS_IXR_ARB_LOST_MASK, XIICPS_IXR_COMP_MASK, XIICPS_IXR_DATA_MASK, XIICPS_IXR_NACK_MASK, XIICPS_IXR_RX_OVR_MASK, XIICPS_IXR_TO_MASK, XIICPS_MAX_TRANSFER_SIZE, XIicPs_ReadReg, XIicPs_SetupMaster, XIICPS_TRANS_SIZE_OFFSET, XIicPs_WriteReg.
Referenced by IicPsMasterIntrExample, IicPsMultiMasterIntrExample, XIicPsSmbusMasterReadBlockData.
s32 XIicPs_MasterSendPolled(XIicPs *InstancePtr, u8 *MsgPtr, s32 ByteCount, u16 SlaveAddr)
Initiates a polled mode send in master mode.
It sends data to the FIFO and waits for the slave to pick them up. If master fails to send data due arbitration lost, will stop transfer and with arbitration lost status. If slave fails to remove data from FIFO, the send fails with time out. InstancePtr Pointer to the XIicPs instance. MsgPtr Pointer to the send buffer. ByteCount Number of bytes to be sent. SlaveAddr Address of the slave we are sending to. XST_SUCCESS if everything went well.XST_FAILURE if timed out.XST_IIC_ARB_LOST if arbitration lost This send routine is for polled mode transfer only.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::IsReady, XIicPs::IsRepeatedStart, XIicPs_Config::RefClk, XIicPs::SendBufferPtr, XIicPs::SendByteCount, SENDING_ROLE, TransmitFifoFill, TX_MAX_LOOPCNT, XIICPS_ADDR_OFFSET, XIICPS_CR_OFFSET, XIICPS_ISR_OFFSET, XIICPS_IXR_ARB_LOST_MASK, XIICPS_IXR_COMP_MASK, XIICPS_IXR_NACK_MASK, XIICPS_IXR_TX_OVR_MASK, XIicPs_ReadReg, XIicPs_SetupMaster, XIICPS_SR_OFFSET, XIicPs_WriteReg.
Referenced by EepromWriteData, IicPsMasterPolledExample, IicPsMultiMasterPolledExample, XIicPsSmbusPolledMasterReadBlockData, XIicPsSmbusPolledMasterWriteBlockData.
s32 XIicPs_MasterRecvPolled(XIicPs *InstancePtr, u8 *MsgPtr, s32 ByteCount, u16 SlaveAddr)
Initiates a polled mode receive in master mode.
It repeatedly sets the transfer size register so the slave can send data to us. It polls the data register for data to come in. If master fails to read data due arbitration lost, will return with arbitration lost status. If slave fails to send us data, it fails with time out. InstancePtr Pointer to the XIicPs instance. MsgPtr Pointer to the receive buffer. ByteCount Number of bytes to be received. SlaveAddr Address of the slave we are receiving from. XST_SUCCESS if everything went well.XST_FAILURE if timed out.XST_IIC_ARB_LOST if arbitration lost This receive routine is for polled mode transfer only.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::IsReady, XIicPs::IsRepeatedStart, XIicPs::RecvBufferPtr, XIicPs::RecvByteCount, RECVING_ROLE, XIicPs_Config::RefClk, XIicPs::UpdateTxSize, XIICPS_ADDR_OFFSET, XIICPS_CR_OFFSET, XIICPS_ISR_OFFSET, XIICPS_IXR_ARB_LOST_MASK, XIICPS_IXR_NACK_MASK, XIICPS_IXR_RX_OVR_MASK, XIICPS_IXR_RX_UNF_MASK, XIicPs_MasterPolledRead, XIICPS_MAX_TRANSFER_SIZE, XIicPs_ReadReg, XIicPs_SetupMaster, XIICPS_TRANS_SIZE_OFFSET, XIicPs_WriteReg.
Referenced by EepromReadDataRepStart, IicPsMasterPolledExample, IicPsMultiMasterPolledExample, XIicPsSmbusPolledMasterReadBlockData.
void XIicPs_EnableSlaveMonitor(XIicPs *InstancePtr, u16 SlaveAddr)
Enables the slave monitor mode.
It enables slave monitor in the control register and enables slave ready interrupt. It then does an address transfer to slave. Interrupt handler will signal the caller if slave responds to the address transfer. InstancePtr Pointer to the XIicPs instance. SlaveAddr Address of the slave to contact. None.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::Is10BitAddr, XIicPs_Config::RefClk, XIICPS_ADDR_OFFSET, XIICPS_CR_OFFSET, XIicPs_EnableInterrupts, XIICPS_IXR_SLV_RDY_MASK, XIicPs_ReadReg, XIICPS_SLV_PAUSE_OFFSET, XIICPS_TRANS_SIZE_OFFSET, XIicPs_WriteReg.
void XIicPs_DisableSlaveMonitor(XIicPs *InstancePtr)
Disables slave monitor mode.
InstancePtr Pointer to the XIicPs instance. None.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs_Config::RefClk, XIICPS_CR_OFFSET, XIicPs_DisableInterrupts, XIICPS_IXR_SLV_RDY_MASK, XIicPs_ReadReg, XIicPs_WriteReg.
void XIicPs_MasterInterruptHandler(XIicPs *InstancePtr)
The interrupt handler for the master mode.
It does the protocol handling for the interrupt-driven transfers.Completion events and errors are signaled to upper layer for proper handling.The interrupts that are handled are: DATA: This case is handled only for master receive data. The master has to request for more data (if there is more data to receive) and read the data from the FIFO.COMP: If the Master is transmitting data and there is more data to be sent then the data is written to the FIFO. If there is no more data to be transmitted then a completion event is signalled to the upper layer by calling the callback handler.If the Master is receiving data then the data is read from the FIFO and the Master has to request for more data (if there is more data to receive). If all the data has been received then a completion event is signalled to the upper layer by calling the callback handler. It is an error if the amount of received data is more than expected.NAK and SLAVE_RDY: This is signalled to the upper layer by calling the callback handler.All Other interrupts: These interrupts are marked as error. This is signalled to the upper layer by calling the callback handler. InstancePtr Pointer to the XIicPs instance. None.
References XIicPs_Config::BaseAddress, XIicPs::CallBackRef, XIicPs::Config, XIicPs::IsReady, XIicPs::IsRepeatedStart, XIicPs::IsSend, XIicPs::RecvByteCount, XIicPs::StatusHandler, XIICPS_CR_OFFSET, XIicPs_DisableInterrupts, XIICPS_EVENT_ARB_LOST, XIICPS_EVENT_COMPLETE_RECV, XIICPS_EVENT_ERROR, XIICPS_EVENT_NACK, XIICPS_EVENT_SLAVE_RDY, XIICPS_EVENT_TIME_OUT, XIICPS_IMR_OFFSET, XIICPS_ISR_OFFSET, XIICPS_IXR_ARB_LOST_MASK, XIICPS_IXR_COMP_MASK, XIICPS_IXR_NACK_MASK, XIICPS_IXR_RX_OVR_MASK, XIICPS_IXR_RX_UNF_MASK, XIICPS_IXR_SLV_RDY_MASK, XIICPS_IXR_TO_MASK, XIICPS_IXR_TX_OVR_MASK, XIicPs_MasterIntrRead, XIicPs_MasterIntrSend, XIicPs_ReadReg, XIicPs_WriteReg.
Referenced by IicPsMasterIntrExample, IicPsMultiMasterIntrExample, IicPsSmbusSlaveIntrExample, XIicPsSmbusMasterIntrExample.
void XIicPs_SetupSlave(XIicPs *InstancePtr, u16 SlaveAddr)
Functions for device as slave, in xiicps_slave.c.
Sets up the device to be a slave. InstancePtr Pointer to the XIicPs instance. SlaveAddr Address of the slave we are receiving from. None. Interrupt is always enabled no matter the transfer is interrupt-driven or polled mode. The device interruption depends on whether the device is connected to an interrupt controller and interrupt for the device is enabled.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::IsReady, XIicPs_Config::RefClk, XIICPS_ADDR_OFFSET, XIICPS_CR_OFFSET, XIicPs_DisableAllInterrupts, XIicPs_WriteReg.
Referenced by IicPsSlaveIntrExample, IicPsSlavePolledExample, IicPsSmbusSlaveIntrExample, IicPsSmbusSlavePolledExample.
void XIicPs_SlaveSend(XIicPs *InstancePtr, u8 *MsgPtr, s32 ByteCount)
Sets up a slave interrupt-driven send.
It set the repeated start for the device with a transfer size larger than FIFO depth. Data processing for the send is initiated by the interrupt handler. InstancePtr Pointer to the XIicPs instance. MsgPtr Pointer to the send buffer. ByteCount Number of bytes to be sent. None. This send routine is for interrupt-driven transfer only.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::IsReady, XIicPs::RecvBufferPtr, XIicPs::SendBufferPtr, XIicPs::SendByteCount, XIicPs_EnableInterrupts, XIICPS_ISR_OFFSET, XIICPS_IXR_ALL_INTR_MASK, XIICPS_IXR_COMP_MASK, XIICPS_IXR_DATA_MASK, XIICPS_IXR_NACK_MASK, XIICPS_IXR_TO_MASK, XIICPS_IXR_TX_OVR_MASK, XIicPs_WriteReg.
Referenced by IicPsSlaveIntrExample.
void XIicPs_SlaveRecv(XIicPs *InstancePtr, u8 *MsgPtr, s32 ByteCount)
Sets up a slave interrupt-driven receive.
Data processing for the receive is handled by the interrupt handler. InstancePtr Pointer to the XIicPs instance. MsgPtr Pointer to the receive buffer. ByteCount Number of bytes to be received. None. This routine is for interrupt-driven transfer only.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::IsReady, XIicPs::RecvBufferPtr, XIicPs::SendBufferPtr, XIicPs_EnableInterrupts, XIICPS_ISR_OFFSET, XIICPS_IXR_ALL_INTR_MASK, XIICPS_IXR_COMP_MASK, XIICPS_IXR_DATA_MASK, XIICPS_IXR_NACK_MASK, XIICPS_IXR_RX_OVR_MASK, XIICPS_IXR_RX_UNF_MASK, XIICPS_IXR_TO_MASK, XIicPs_WriteReg.
Referenced by IicPsSlaveIntrExample.
s32 XIicPs_SlaveSendPolled(XIicPs *InstancePtr, u8 *MsgPtr, s32 ByteCount)
Sends a buffer in polled mode as a slave.
InstancePtr Pointer to the XIicPs instance. MsgPtr Pointer to the send buffer. ByteCount Number of bytes to be sent. XST_SUCCESS if everything went well.XST_FAILURE if master sends us data or master terminates the transfer before all data has sent out. This send routine is for polled mode transfer only.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::IsReady, XIicPs::SendBufferPtr, XIicPs::SendByteCount, XIICPS_ISR_OFFSET, XIICPS_IXR_COMP_MASK, XIICPS_IXR_NACK_MASK, XIicPs_ReadReg, XIicPs_SendByte, XIICPS_SR_OFFSET, XIicPs_WriteReg.
Referenced by IicPsSlavePolledExample.
s32 XIicPs_SlaveRecvPolled(XIicPs *InstancePtr, u8 *MsgPtr, s32 ByteCount)
This function receives a buffer in polled mode as a slave.
InstancePtr Pointer to the XIicPs instance. MsgPtr Pointer to the receive buffer. ByteCount Number of bytes to be received. XST_SUCCESS if everything went well.XST_FAILURE if timed out. This receive routine is for polled mode transfer only.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::IsReady, XIicPs::RecvBufferPtr, XIICPS_ISR_OFFSET, XIICPS_IXR_COMP_MASK, XIICPS_IXR_DATA_MASK, XIicPs_ReadReg, XIicPs_RecvByte, XIICPS_SR_OFFSET, XIicPs_WriteReg.
Referenced by IicPsSlavePolledExample.
void XIicPs_SlaveInterruptHandler(XIicPs *InstancePtr)
The interrupt handler for slave mode.
It does the protocol handling for the interrupt-driven transfers.Completion events and errors are signaled to upper layer for proper handling.The interrupts that are handled are: DATA: If the instance is sending, it means that the master wants to read more data from us. Send more data, and check whether the send is complete.If the instance is receiving, it means that the master has written more data to us. Receive more data, and check whether the receive is complete.COMP: This marks that stop sequence has been sent from the master, transfer is about to terminate. However, for receiving, the master may have written us some data, so receive that first.It is an error if the amount of transferred data is less than expected.NAK: This marks that master does not want our data. It is for send only.Other interrupts: These interrupts are marked as error. InstancePtr Pointer to the XIicPs instance. None.
References XIicPs_Config::BaseAddress, XIicPs::CallBackRef, XIicPs::Config, XIicPs::IsReady, XIicPs::RecvBufferPtr, XIicPs::SendByteCount, SlaveRecvData, XIicPs::StatusHandler, TransmitFifoFill, XIICPS_CR_OFFSET, XIicPs_DisableInterrupts, XIICPS_EVENT_COMPLETE_RECV, XIICPS_EVENT_COMPLETE_SEND, XIICPS_EVENT_ERROR, XIICPS_EVENT_NACK, XIICPS_EVENT_TIME_OUT, XIICPS_IMR_OFFSET, XIICPS_ISR_OFFSET, XIICPS_IXR_COMP_MASK, XIICPS_IXR_DATA_MASK, XIICPS_IXR_NACK_MASK, XIICPS_IXR_RX_OVR_MASK, XIICPS_IXR_RX_UNF_MASK, XIICPS_IXR_TO_MASK, XIICPS_IXR_TX_OVR_MASK, XIicPs_ReadReg, XIicPs_WriteReg.
Referenced by IicPsSlaveIntrExample.
void XIicPsSclHold(XIicPs *InstancePtr, u8 Enable)
Enables/Disables clock stretching (SCL HOLD).
InstancePtr Pointer to the XIicPs instance. Enable Value to enable/disable clock stretching (SCL HOLD). 1 to Enable 0 to Disable
References XIicPs_Config::BaseAddress, XIicPs::Config, XIICPS_CR_OFFSET, XIicPs_ReadReg, XIicPs_WriteReg.
void XIicPsSetTimeOut(XIicPs *InstancePtr, u8 Value)
Sets the timeout value.
InstancePtr Pointer to the XIicPs instance. Value Timeout value.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs_ReadReg, XIICPS_TIME_OUT_OFFSET, XIicPs_WriteReg.
s32 XIicPs_SetOptions(XIicPs *InstancePtr, u32 Options)
Functions for setting and getting data rate, in xiicps_options.c.
Sets the options for the IIC device driver.The options control how the device behaves relative to the IIC bus. The device must be idle rather than busy transferring data before setting these device options. InstancePtr Pointer to the XIicPs instance. Options Contains the specified options to be set. This is a bit mask where a 1 means to turn the option on. One or more bit values may be contained in the mask. See the bit definitions named XIICPS_*_OPTION in xiicps.h. XST_SUCCESS if options are successfully set.XST_DEVICE_IS_STARTED if the device is currently transferring data. The transfer must complete or be aborted before setting options. None.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::Is10BitAddr, XIicPs::IsReady, XIicPs::IsRepeatedStart, XIicPs::Options, XIICPS_10_BIT_ADDR_OPTION, XIICPS_CR_OFFSET, XIicPs_GetOptions, XIICPS_NUM_OPTIONS, XIicPs_ReadReg, XIICPS_REP_START_OPTION, XIicPs_WriteReg.
Referenced by EepromReadDataRepStart, XIicPsSmbusMasterReadBlockData, XIicPsSmbusPolledMasterReadBlockData.
s32 XIicPs_ClearOptions(XIicPs *InstancePtr, u32 Options)
Clears the options for the IIC device driver.
The options control how the device behaves relative to the IIC bus. The device must be idle rather than busy transferring data before setting these device options. InstancePtr Pointer to the XIicPs instance. Options Contains the specified options to be cleared. This is a bit mask where a 1 means to turn the option off. One or more bit values may be contained in the mask. See the bit definitions named XIICPS_*_OPTION in xiicps.h. XST_SUCCESS if options are successfully set.XST_DEVICE_IS_STARTED if the device is currently transferring data. The transfer must complete or be aborted before setting options. None
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::Is10BitAddr, XIicPs::IsReady, XIicPs::IsRepeatedStart, XIicPs::Options, XIICPS_10_BIT_ADDR_OPTION, XIICPS_CR_OFFSET, XIicPs_GetOptions, XIICPS_NUM_OPTIONS, XIicPs_ReadReg, XIICPS_REP_START_OPTION, XIicPs_WriteReg.
Referenced by EepromReadDataRepStart, XIicPsSmbusMasterReadBlockData, XIicPsSmbusPolledMasterReadBlockData.
u32 XIicPs_GetOptions(XIicPs *InstancePtr)
Gets the options for the IIC device.
The options control how the device behaves relative to the IIC bus. InstancePtr Pointer to the XIicPs instance. 32 bit mask of the options, where a 1 means the option is on, and a 0 means to the option is off. One or more bit values may be contained in the mask. See the bit definitions named XIICPS_*_OPTION in the file xiicps.h. None.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::IsReady, XIicPs::IsRepeatedStart, XIICPS_10_BIT_ADDR_OPTION, XIICPS_7_BIT_ADDR_OPTION, XIICPS_CR_OFFSET, XIICPS_NUM_OPTIONS, XIicPs_ReadReg, XIICPS_REP_START_OPTION.
Referenced by XIicPs_CfgInitialize, XIicPs_ClearOptions, XIicPs_SetOptions.
s32 XIicPs_SetSClk(XIicPs *InstancePtr, u32 FsclHz)
Sets the serial clock rate for the IIC device.
The device must be idle rather than busy transferring data before setting these device options.The data rate is set by values in the control register. The formula for determining the correct register values is: Fscl = Fpclk/(22 x (divisor_a+1) x (divisor_b+1)) See the hardware data sheet for a full explanation of setting the serial clock rate. InstancePtr Pointer to the XIicPs instance. FsclHz Clock frequency in Hz. The two most common clock rates are 100KHz and 400KHz. XST_SUCCESS if options are successfully set.XST_DEVICE_IS_STARTED if the device is currently transferring data. The transfer must complete or be aborted before setting options.XST_FAILURE if the Fscl frequency can not be set. The clock can not be faster than the input clock divide by 22.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs_Config::InputClockHz, XIicPs::IsReady, XIICPS_CR_OFFSET, XIicPs_ReadReg, XIICPS_TRANS_SIZE_OFFSET, XIicPs_WriteReg.
Referenced by IicPsMasterIntrExample, IicPsMasterPolledExample, IicPsMultiMasterIntrExample, IicPsMultiMasterPolledExample, IicPsRepeatedStartExample, IicPsSlaveIntrExample, IicPsSlavePolledExample, IicPsSmbusSlaveIntrExample, IicPsSmbusSlavePolledExample, XIicPsSmbusMasterIntrExample.
u32 XIicPs_GetSClk(XIicPs *InstancePtr)
Sets the serial clock rate for the IIC device.
The device must be idle rather than busy transferring data before setting these device options. InstancePtr Pointer to the XIicPs instance. The value of the IIC clock to the nearest Hz based on the control register settings. The actual value may not be exact to to integer math rounding errors. None.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs_Config::InputClockHz, XIicPs::IsReady, XIICPS_CR_OFFSET, XIicPs_ReadReg.
XIICPS_H
by using protection macros
SENDING_ROLE
name Role constants
These constants are used to pass into the device setup routines to set up the device according to transfer direction.Transfer direction is sending
Referenced by XIicPs_MasterSend, XIicPs_MasterSendPolled.
RECVING_ROLE
Transfer direction is receiving.
Referenced by XIicPs_MasterRecv, XIicPs_MasterRecvPolled, XIicPs_SetupMaster.
XIICPS_MAX_TRANSFER_SIZE
Max transfer size.
Referenced by XIicPs_MasterIntrRead, XIicPs_MasterPolledRead, XIicPs_MasterRecv, XIicPs_MasterRecvPolled.
XIicPs_SendByte
Place one byte into the transmit FIFO.
InstancePtr Pointer to the XIicPs instance. None. C-Style signature: void XIicPs_SendByte(XIicPs *InstancePtr)
Referenced by TransmitFifoFill, XIicPs_SlaveSendPolled.
XIicPs_RecvByte
Receive one byte from FIFO.
InstancePtr Pointer to the XIicPs instance. None. C-Style signature: u8 XIicPs_RecvByte(XIicPs *InstancePtr)
Referenced by XIicPs_MasterRead, XIicPs_SlaveRecvPolled.
typedef void(* XIicPs_IntrHandler)(void *CallBackRef, u32 StatusEvent))(void *CallBackRef, u32 StatusEvent)
The handler data type allows the user to define a callback function to respond to interrupt events in the system.
This function is executed in interrupt context, so that the amount of processing should be minimized. CallBackRef Reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. Its type is not important to the driver, so it is a void pointer. StatusEvent Indicates one or more status events that occurred.
XIicPs_Config XIicPs_ConfigTable[][]
Configuration table.
Configuration table.
Referenced by XIicPs_LookupConfig.
static u32 XIicPs_RxDataValidStatus(XIicPs *InstancePtr)
This function is to check if Rx data is valid or not.
InstancePtr Pointer to the XIicPs instance. returns '1' if Rx data is valid, '0' otherwise.
XIicPs_Config * XIicPs_LookupConfig(UINTPTR BaseAddress)
Function for configuration lookup, in xiicps_sinit.c.
Looks up the device configuration based on the unique device ID/BaseAddress.The XIicPs_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xiicps.h for the definition of XIicPs_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XIicPs_Config::Name, XIicPs_ConfigTable.
Referenced by IicPsMasterIntrExample, IicPsMasterPolledExample, IicPsMultiMasterIntrExample, IicPsMultiMasterPolledExample, IicPsRepeatedStartExample, IicPsSelfTestExample, IicPsSlaveIntrExample, IicPsSlavePolledExample, IicPsSmbusSlaveIntrExample, IicPsSmbusSlavePolledExample, XIicPsSmbusMasterIntrExample.
void XIicPs_SetStatusHandler(XIicPs *InstancePtr, void *CallBackRef, XIicPs_IntrHandler FunctionPtr)
Functions for interrupts, in xiicps_intr.c.
Sets the status callback function, the status handler, which the driver calls when it encounter conditions that should be reported to the higher layer software.The handler executes in an interrupt context, so the amount of processing should be minimized.Refer to the xiicps.h file for a list of the Callback events. The events are defined to start with XIICPS_EVENT_*. InstancePtr Pointer to the XIicPs instance. CallBackRef Upper layer callback reference passed back when the callback function is invoked. FunctionPtr Pointer to the callback function. None. The handler is called within interrupt context, so it should finish its work quickly.
References XIicPs::CallBackRef, XIicPs::IsReady, XIicPs::StatusHandler.
Referenced by IicPsMasterIntrExample, IicPsMultiMasterIntrExample, IicPsSlaveIntrExample, IicPsSmbusSlaveIntrExample, XIicPsSmbusMasterIntrExample.
s32 XIicPs_SelfTest(XIicPs *InstancePtr)
Functions for selftest, in xiicps_selftest.c.
Runs a self-test on the driver/device.The self-test is destructive in that a reset of the device is performed in order to check the reset values of the registers and to get the device into a known state.Upon successful return from the self-test, the device is reset. InstancePtr Pointer to the XIicPs instance. XST_SUCCESS if successful.XST_REGISTER_ERROR indicates a register did not read or write correctly. None.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::IsReady, REG_TEST_VALUE, XIICPS_CR_OFFSET, XIICPS_IMR_OFFSET, XIICPS_IXR_ALL_INTR_MASK, XIicPs_ReadReg, XIicPs_Reset, XIICPS_SLV_PAUSE_OFFSET, XIicPs_WriteReg.
Referenced by IicPsMasterIntrExample, IicPsMasterPolledExample, IicPsMultiMasterIntrExample, IicPsMultiMasterPolledExample, IicPsSelfTestExample, IicPsSlaveIntrExample, IicPsSlavePolledExample, IicPsSmbusSlaveIntrExample, IicPsSmbusSlavePolledExample, XIicPsSmbusMasterIntrExample.