xiicps_hw.c
void XIicPs_Reset(XIicPs *InstancePtr)
Resets the IIC device.
Reset must only be called after the driver has been initialized. The configuration of the device after reset is the same as its configuration after initialization. Any data transfer that is in progress is aborted.The upper layer software is responsible for re-configuring (if necessary) and reenabling interrupts for the IIC device after the reset. InstancePtr Pointer to the XIicPs instance. None.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::IsReady, XIicPs_Abort, XIICPS_CR_OFFSET, XIICPS_IDR_OFFSET, XIICPS_IXR_ALL_INTR_MASK, XIICPS_TIME_OUT_OFFSET, XIicPs_WriteReg.
Referenced by XIicPs_CfgInitialize, XIicPs_SelfTest.
void XIicPs_ResetHw(UINTPTR BaseAddress)
Performs the reset sequence to the given I2c interface by configuring the appropriate control bits in the I2c specific registers the i2cps reset sequence involves the following steps Disable all the interrupts Clear the status Clear FIFO's and disable hold bit Clear the line status Update relevant configuration registers with reset values.
BaseAddress Base address of the interface None. This function will not modify the slcr registers that are relevant for I2c controller
References XIICPS_CR_OFFSET, XIICPS_IDR_OFFSET, XIICPS_ISR_OFFSET, XIICPS_IXR_ALL_INTR_MASK, XIicPs_ReadReg, XIICPS_SR_OFFSET, XIICPS_TIME_OUT_OFFSET, XIICPS_TRANS_SIZE_OFFSET, XIicPs_WriteReg.
void XIicPs_MasterRead(XIicPs *InstancePtr, s32 IsHold, s32 *ByteCntPtr)
Receives data byte by byte till Rx data is valid in interrupt master mode.
InstancePtr Pointer to the XIicPs instance. IsHold Hold status. ByteCntPtr Pointer to the byte count. None.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::CurrByteCount, XIicPs::IsRepeatedStart, XIicPs::RecvByteCount, XIicPs::UpdateTxSize, XIICPS_CR_OFFSET, XIicPs_ReadReg, XIicPs_RecvByte, XIicPs_WriteReg.
Referenced by XIicPs_MasterIntrRead, XIicPs_MasterPolledRead.