xiicps_repeated_start_example.c
XIICPS_BASEADDRESS
IIC_SLAVE_ADDR
IIC_SCLK_RATE
MUX_ADDR
MAX_CHANNELS
SLV_MON_LOOP_COUNT
MAX_SIZE
PAGE_SIZE_16
PAGE_SIZE_32
PAGE_SIZE
PAGE_SIZE_64
EEPROM_START_ADDRESS
typedef u16 AddressType
XIicPs IicInstance
u32 Platform
u32 PageSize
u16 EepromSlvAddr
u16 EepromAddr[][]
u16 MuxAddr[][]
XIicPs_Config XIicPs_ConfigTable[XPAR_XIICPS_NUM_INSTANCES][XPAR_XIICPS_NUM_INSTANCES]
This table contains configuration information for each IIC device in the system.
Configuration table.
u8 WriteBuffer[sizeof(AddressType)+MAX_SIZE][sizeof(AddressType)+MAX_SIZE]
u8 ReadBuffer[MAX_SIZE *20][MAX_SIZE *20]
int IicPsRepeatedStartExample(void)
This function writes, reads, and verifies the data to the IIC EEPROM.
Page write is used. Buffered read with repeated start option is done.XST_SUCCESS if successful else XST_FAILURE. None.
References XIicPs_Config::BaseAddress, EepromReadDataRepStart, EepromWriteData, XIicPs_CfgInitialize, XIicPs_LookupConfig, XIicPs_SetSClk.
Referenced by main.
int EepromWriteData(u16 ByteCount)
This function writes a buffer of data to the IIC serial EEPROM.
ByteCount contains the number of bytes in the buffer to be written. XST_SUCCESS if successful else XST_FAILURE. The Byte count should not exceed the page size of the EEPROM as noted by the constant PAGE_SIZE.
References XIicPs::IsRepeatedStart, XIicPs_BusIsBusy, XIicPs_MasterSendPolled.
Referenced by EepromReadDataRepStart, IicPsEepromIntrExample, IicPsEepromPolledExample, IicPsRepeatedStartExample.
static s32 MuxInitChannel(u16 MuxIicAddr, u8 WriteBuffer)
This function initializes the IIC MUX to select the required channel.
MuxAddress and Channel select value. XST_SUCCESS if pass, otherwise XST_FAILURE. None.
int EepromReadDataRepStart(u8 *BufferPtr, u16 ByteCount)
This function reads data from the IIC serial EEPROM into a specified buffer.
BufferPtr contains the address of the data buffer to be filled. ByteCount contains the number of bytes in the buffer to be read. XST_SUCCESS if successful else XST_FAILURE. None.
References EepromWriteData, XIicPs_BusIsBusy, XIicPs_ClearOptions, XIicPs_MasterRecvPolled, XIICPS_REP_START_OPTION, XIicPs_SetOptions.
Referenced by IicPsRepeatedStartExample.
static s32 FindEepromDevice(u16 Address)
This function checks the availability of EEPROM using slave monitor mode.
EEPROM address. XST_SUCCESS if successful, otherwise XST_FAILURE. None.
static s32 IicPsFindEeprom(u16 *Eeprom_Addr, u32 *PageSize)
This function is use to figure out the Eeprom slave device.
addr : u16 variable XST_SUCCESS if successful and also update the epprom slave device address in addr variable else XST_FAILURE. None.
static s32 IicPsConfig(UINTPTR BaseAddress)
This function perform the initial configuration for the IICPS Device.
DeviceId instance. XST_SUCCESS if pass, otherwise XST_FAILURE. None.
static s32 IicPsFindDevice(u16 addr, UINTPTR BaseAddress)
This function is use to figure out the slave device is alive or not.
slave address and Device ID . XST_SUCCESS if successful, otherwise XST_FAILURE. None.
static s32 IicPsSlaveMonitor(u16 Address, UINTPTR BaseAddress)
This function checks the availability of a slave using slave monitor mode.
DeviceId is the Device ID of the IicPs Device and is the XPAR_<IICPS_instance>_DEVICE_ID value from xparameters.h XST_SUCCESS if successful, otherwise XST_FAILURE. None.
static int FindEepromPageSize(u16 EepromAddr, u32 *PageSize_ptr)
This function is used to figure out page size Eeprom slave device.
Eeprom Address Pagesize pointer XST_SUCCESS if successful and also update the epprom slave device pagesize else XST_FAILURE. None.
int main(void)
Main function to call the Iic repeated start example.
XST_SUCCESS if successful else XST_FAILURE. None.
References IicPsRepeatedStartExample.
static s32 EepromReadData(XIicPs *IicInstance, u8 *BufferPtr, u16 ByteCount)
This function reads data from the IIC serial EEPROM into a specified buffer.
BufferPtr contains the address of the data buffer to be filled. ByteCount contains the number of bytes in the buffer to be read. XST_SUCCESS if successful else XST_FAILURE. None.