xiicps_intr.c
void XIicPs_SetStatusHandler(XIicPs *InstancePtr, void *CallBackRef, XIicPs_IntrHandler FunctionPtr)
Functions for interrupts, in xiicps_intr.c.
Sets the status callback function, the status handler, which the driver calls when it encounter conditions that should be reported to the higher layer software.The handler executes in an interrupt context, so the amount of processing should be minimized.Refer to the xiicps.h file for a list of the Callback events. The events are defined to start with XIICPS_EVENT_*. InstancePtr Pointer to the XIicPs instance. CallBackRef Upper layer callback reference passed back when the callback function is invoked. FunctionPtr Pointer to the callback function. None. The handler is called within interrupt context, so it should finish its work quickly.
References XIicPs::CallBackRef, XIicPs::IsReady, XIicPs::StatusHandler.
Referenced by IicPsMasterIntrExample, IicPsMultiMasterIntrExample, IicPsSlaveIntrExample, IicPsSmbusSlaveIntrExample, XIicPsSmbusMasterIntrExample.