xiicps_smbus_intr_master_example.c
XIICPS_BASEADDRESS
IIC_SLAVE_ADDR
IIC_SCLK_RATE
TEST_BUFFER_SIZE
XIicPs Iic
u8 SendBuffer[TEST_BUFFER_SIZE][TEST_BUFFER_SIZE]
u8 RecvBuffer[TEST_BUFFER_SIZE][TEST_BUFFER_SIZE]
u8 Cmd
u8 RecvByteCount
volatile u32 SendComplete
volatile u32 RecvComplete
volatile u32 TotalErrorCount
int XIicPsSmbusMasterIntrExample(UINTPTR BaseAddress)
This function does a minimal test on the Iic device and driver as a design example.
The purpose of this function is to illustrate how to use the XIicPs driver.This function sends and receives data as a smbus master in interrupt driver mode of the IIC. BaseAddress contains the base address of the device XST_SUCCESS if successful, otherwise XST_FAILURE. -In XSCT/classic flow, DeviceId is used to look up the device configuration. -This function contains an infinite loop such that if interrupts are not working it may never return.
References XIicPs_Config::BaseAddress, Handler, XIicPs_Config::IntrId, XIicPs_Config::IntrParent, XIicPs_BusIsBusy, XIicPs_CfgInitialize, XIicPs_LookupConfig, XIicPs_MasterInterruptHandler, XIicPs_SelfTest, XIicPs_SetSClk, XIicPs_SetStatusHandler, XIicPsSmbusMasterReadBlockData, XIicPsSmbusMasterWriteBlockData.
Referenced by main.
int XIicPsSmbusMasterWriteBlockData(XIicPs *InstancePtr, u8 Command, u8 ByteCount, u8 *SendBufferPtr)
This function writes a buffer of data to the smbus slave.
InstancePtr contains the address of XIicPs instance. Command contains send command. ByteCount contains the number of bytes to write. SendBufferPtr contains the address of send buffer. XST_SUCCESS if successful else XST_FAILURE. None
References TotalErrorCount, XIicPs_BusIsBusy, XIicPs_MasterSend.
Referenced by XIicPsSmbusMasterIntrExample.
int XIicPsSmbusMasterReadBlockData(XIicPs *InstancePtr, u8 Command, u8 ByteCount, u8 *RecvBufferPtr)
This function sends a command and reads a buffer of data from the smbus slave.
InstancePtr contains the address of XIicPs instance. Command contains send command. ByteCount contains the number of bytes to read. RecvBufferPtr contains the address of receive buffer. XST_SUCCESS if successful else XST_FAILURE. None
References XIicPs_Config::BaseAddress, XIicPs::Config, TotalErrorCount, XIicPs_BusIsBusy, XIicPs_ClearOptions, XIicPs_DisableAllInterrupts, XIICPS_ISR_OFFSET, XIicPs_MasterRecv, XIicPs_MasterSend, XIicPs_ReadReg, XIICPS_REP_START_OPTION, XIicPs_SetOptions.
Referenced by XIicPsSmbusMasterIntrExample.
void Handler(void *CallBackRef, u32 Event)
This function is the handler which performs processing to handle data events from the IIC.
It is called from an interrupt context such that the amount of processing performed should be minimized.This handler provides an example of how to handle data for the IIC and is application specific. CallBackRef contains a callback reference from the driver, in this case it is the instance pointer for the IIC driver. Event contains the specific kind of event that has occurred. None. None.
int main(void)
Main function to call the example.
XST_SUCCESS if successful, XST_FAILURE if unsuccessful. None.
References XIicPsSmbusMasterIntrExample.