xiicps_slave.c
void XIicPs_SetupSlave(XIicPs *InstancePtr, u16 SlaveAddr)
Functions for device as slave, in xiicps_slave.c.
Sets up the device to be a slave. InstancePtr Pointer to the XIicPs instance. SlaveAddr Address of the slave we are receiving from. None. Interrupt is always enabled no matter the transfer is interrupt-driven or polled mode. The device interruption depends on whether the device is connected to an interrupt controller and interrupt for the device is enabled.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::IsReady, XIicPs_Config::RefClk, XIICPS_ADDR_OFFSET, XIICPS_CR_OFFSET, XIicPs_DisableAllInterrupts, XIicPs_WriteReg.
Referenced by IicPsSlaveIntrExample, IicPsSlavePolledExample, IicPsSmbusSlaveIntrExample, IicPsSmbusSlavePolledExample.
void XIicPs_SlaveSend(XIicPs *InstancePtr, u8 *MsgPtr, s32 ByteCount)
Sets up a slave interrupt-driven send.
It set the repeated start for the device with a transfer size larger than FIFO depth. Data processing for the send is initiated by the interrupt handler. InstancePtr Pointer to the XIicPs instance. MsgPtr Pointer to the send buffer. ByteCount Number of bytes to be sent. None. This send routine is for interrupt-driven transfer only.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::IsReady, XIicPs::RecvBufferPtr, XIicPs::SendBufferPtr, XIicPs::SendByteCount, XIicPs_EnableInterrupts, XIICPS_ISR_OFFSET, XIICPS_IXR_ALL_INTR_MASK, XIICPS_IXR_COMP_MASK, XIICPS_IXR_DATA_MASK, XIICPS_IXR_NACK_MASK, XIICPS_IXR_TO_MASK, XIICPS_IXR_TX_OVR_MASK, XIicPs_WriteReg.
Referenced by IicPsSlaveIntrExample.
void XIicPs_SlaveRecv(XIicPs *InstancePtr, u8 *MsgPtr, s32 ByteCount)
Sets up a slave interrupt-driven receive.
Data processing for the receive is handled by the interrupt handler. InstancePtr Pointer to the XIicPs instance. MsgPtr Pointer to the receive buffer. ByteCount Number of bytes to be received. None. This routine is for interrupt-driven transfer only.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::IsReady, XIicPs::RecvBufferPtr, XIicPs::SendBufferPtr, XIicPs_EnableInterrupts, XIICPS_ISR_OFFSET, XIICPS_IXR_ALL_INTR_MASK, XIICPS_IXR_COMP_MASK, XIICPS_IXR_DATA_MASK, XIICPS_IXR_NACK_MASK, XIICPS_IXR_RX_OVR_MASK, XIICPS_IXR_RX_UNF_MASK, XIICPS_IXR_TO_MASK, XIicPs_WriteReg.
Referenced by IicPsSlaveIntrExample.
s32 XIicPs_SlaveSendPolled(XIicPs *InstancePtr, u8 *MsgPtr, s32 ByteCount)
Sends a buffer in polled mode as a slave.
InstancePtr Pointer to the XIicPs instance. MsgPtr Pointer to the send buffer. ByteCount Number of bytes to be sent. XST_SUCCESS if everything went well.XST_FAILURE if master sends us data or master terminates the transfer before all data has sent out. This send routine is for polled mode transfer only.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::IsReady, XIicPs::SendBufferPtr, XIicPs::SendByteCount, XIICPS_ISR_OFFSET, XIICPS_IXR_COMP_MASK, XIICPS_IXR_NACK_MASK, XIicPs_ReadReg, XIicPs_SendByte, XIICPS_SR_OFFSET, XIicPs_WriteReg.
Referenced by IicPsSlavePolledExample.
s32 XIicPs_SlaveRecvPolled(XIicPs *InstancePtr, u8 *MsgPtr, s32 ByteCount)
This function receives a buffer in polled mode as a slave.
InstancePtr Pointer to the XIicPs instance. MsgPtr Pointer to the receive buffer. ByteCount Number of bytes to be received. XST_SUCCESS if everything went well.XST_FAILURE if timed out. This receive routine is for polled mode transfer only.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::IsReady, XIicPs::RecvBufferPtr, XIICPS_ISR_OFFSET, XIICPS_IXR_COMP_MASK, XIICPS_IXR_DATA_MASK, XIicPs_ReadReg, XIicPs_RecvByte, XIICPS_SR_OFFSET, XIicPs_WriteReg.
Referenced by IicPsSlavePolledExample.
void XIicPs_SlaveInterruptHandler(XIicPs *InstancePtr)
The interrupt handler for slave mode.
It does the protocol handling for the interrupt-driven transfers.Completion events and errors are signaled to upper layer for proper handling.The interrupts that are handled are: DATA: If the instance is sending, it means that the master wants to read more data from us. Send more data, and check whether the send is complete.If the instance is receiving, it means that the master has written more data to us. Receive more data, and check whether the receive is complete.COMP: This marks that stop sequence has been sent from the master, transfer is about to terminate. However, for receiving, the master may have written us some data, so receive that first.It is an error if the amount of transferred data is less than expected.NAK: This marks that master does not want our data. It is for send only.Other interrupts: These interrupts are marked as error. InstancePtr Pointer to the XIicPs instance. None.
References XIicPs_Config::BaseAddress, XIicPs::CallBackRef, XIicPs::Config, XIicPs::IsReady, XIicPs::RecvBufferPtr, XIicPs::SendByteCount, SlaveRecvData, XIicPs::StatusHandler, TransmitFifoFill, XIICPS_CR_OFFSET, XIicPs_DisableInterrupts, XIICPS_EVENT_COMPLETE_RECV, XIICPS_EVENT_COMPLETE_SEND, XIICPS_EVENT_ERROR, XIICPS_EVENT_NACK, XIICPS_EVENT_TIME_OUT, XIICPS_IMR_OFFSET, XIICPS_ISR_OFFSET, XIICPS_IXR_COMP_MASK, XIICPS_IXR_DATA_MASK, XIICPS_IXR_NACK_MASK, XIICPS_IXR_RX_OVR_MASK, XIICPS_IXR_RX_UNF_MASK, XIICPS_IXR_TO_MASK, XIICPS_IXR_TX_OVR_MASK, XIicPs_ReadReg, XIicPs_WriteReg.
Referenced by IicPsSlaveIntrExample.