xiicps.c
s32 XIicPs_CfgInitialize(XIicPs *InstancePtr, XIicPs_Config *ConfigPtr, u32 EffectiveAddr)
Initializes a specific XIicPs instance so that the driver is ready to use.
Functions for general setup, in xiicps.c.The state of the device after initialization is: Device is disabledSlave mode InstancePtr Pointer to the XIicPs instance. ConfigPtr Reference to a structure containing information about a specific IIC device. This function initializes an InstancePtr object for a specific device specified by the contents of Config. EffectiveAddr Device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, use ConfigPtr->BaseAddress for this parameter, passing the physical address instead. The return value is XST_SUCCESS if successful.
References XIicPs_Config::BaseAddress, XIicPs::CallBackRef, XIicPs::Config, XIicPs_Config::InputClockHz, XIicPs::IsReady, XIicPs::IsRepeatedStart, XIicPs::Options, XIicPs_Config::RefClk, XIicPs::StatusHandler, XIicPs_GetOptions, XIicPs_Reset.
Referenced by IicPsMasterIntrExample, IicPsMasterPolledExample, IicPsMultiMasterIntrExample, IicPsMultiMasterPolledExample, IicPsRepeatedStartExample, IicPsSelfTestExample, IicPsSlaveIntrExample, IicPsSlavePolledExample, IicPsSmbusSlaveIntrExample, IicPsSmbusSlavePolledExample, XIicPsSmbusMasterIntrExample.
s32 XIicPs_BusIsBusy(XIicPs *InstancePtr)
Checks the availability of the I2C bus.
InstancePtr Pointer to the XIicPs instance. TRUE if the bus is busy. FALSE if the bus is not busy.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs_Config::RefClk, XIicPs_ReadReg, XIICPS_SR_OFFSET.
Referenced by EepromReadDataRepStart, EepromWriteData, IicPsMasterIntrExample, IicPsMasterPolledExample, IicPsMultiMasterIntrExample, IicPsMultiMasterPolledExample, IicPsSlaveIntrExample, IicPsSlavePolledExample, XIicPs_SetupMaster, XIicPsSmbusMasterIntrExample, XIicPsSmbusMasterReadBlockData, XIicPsSmbusMasterWriteBlockData, XIicPsSmbusPolledMasterReadBlockData, XIicPsSmbusPolledMasterWriteBlockData.
void XIicPs_Abort(XIicPs *InstancePtr)
Aborts a transfer in progress by resetting the FIFOs.
The byte counts are cleared. InstancePtr Pointer to the XIicPs instance. None.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::IsReady, XIICPS_CR_OFFSET, XIICPS_IDR_OFFSET, XIICPS_IER_OFFSET, XIICPS_IMR_OFFSET, XIICPS_ISR_OFFSET, XIICPS_IXR_ALL_INTR_MASK, XIicPs_ReadReg, XIicPs_WriteReg.
Referenced by XIicPs_Reset.
s32 TransmitFifoFill(XIicPs *InstancePtr)
Puts more data into the transmit FIFO.
The number of bytes is either the expected number of bytes for this transfer or available space in FIFO, which ever is less. InstancePtr Pointer to the XIicPs instance. Number of bytes left for this instance. This is function is shared by the master and slave.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::SendByteCount, XIicPs_ReadReg, XIicPs_SendByte, XIICPS_TRANS_SIZE_OFFSET.
Referenced by MasterSendData, XIicPs_MasterSend, XIicPs_MasterSendPolled, XIicPs_SlaveInterruptHandler.
s32 XIicPs_BusRecovery(XIicPs *InstancePtr)
Performs I2C bus recovery using the PS I2C controller HOLD feature.
This API is used when the I2C controller is already in Master mode and the bus is stuck due to a slave holding SDA low. The API toggles the HOLD bit to manually generate SCL pulses, allowing the slave to release the bus. InstancePtr Pointer to the XIicPs instance. XST_SUCCESS if recovery sequence is executed. XST_FAILURE if controller is not in Master mode.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIICPS_CR_OFFSET, XIicPs_ReadReg, XIICPS_RECOVERY_DELAY, XIICPS_RECOVERY_PULSES, XIicPs_WriteReg.
void XIicPsSclHold(XIicPs *InstancePtr, u8 Enable)
Enables/Disables clock stretching (SCL HOLD).
InstancePtr Pointer to the XIicPs instance. Enable Value to enable/disable clock stretching (SCL HOLD). 1 to Enable 0 to Disable
References XIicPs_Config::BaseAddress, XIicPs::Config, XIICPS_CR_OFFSET, XIicPs_ReadReg, XIicPs_WriteReg.
void XIicPsSetTimeOut(XIicPs *InstancePtr, u8 Value)
Sets the timeout value.
InstancePtr Pointer to the XIicPs instance. Value Timeout value.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs_ReadReg, XIICPS_TIME_OUT_OFFSET, XIicPs_WriteReg.
XIICPS_RECOVERY_PULSES
Number of SCL pulses for bus recovery.
Referenced by XIicPs_BusRecovery.
XIICPS_RECOVERY_DELAY
HOLD toggle delay in microseconds (5000 us = 5 ms) for I2C bus recovery.
Referenced by XIicPs_BusRecovery.
static void StubHandler(void *CallBackRef, u32 StatusEvent)
Stub for the status callback.
The stub is here in case the upper layers forget to set the handler. CallBackRef Pointer to the upper layer callback reference. StatusEvent Event that just occurred. None.