xiicps_master.c
void XIicPs_MasterSend(XIicPs *InstancePtr, u8 *MsgPtr, s32 ByteCount, u16 SlaveAddr)
Functions for device as master, in xiicps_master.c.
Initiates an interrupt-driven send in master mode.It tries to send the first FIFO full of data, then lets the interrupt handler to handle the rest of the data if there is any. InstancePtr Pointer to the XIicPs instance. MsgPtr Pointer to the send buffer. ByteCount Number of bytes to be sent. SlaveAddr Address of the slave we are sending to. None. This send routine is for interrupt-driven transfer only.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::IsReady, XIicPs::IsRepeatedStart, XIicPs::IsSend, XIicPs::RecvBufferPtr, XIicPs_Config::RefClk, XIicPs::SendBufferPtr, XIicPs::SendByteCount, SENDING_ROLE, TransmitFifoFill, XIICPS_ADDR_OFFSET, XIICPS_CR_OFFSET, XIicPs_EnableInterrupts, XIICPS_ISR_OFFSET, XIICPS_IXR_ALL_INTR_MASK, XIICPS_IXR_ARB_LOST_MASK, XIICPS_IXR_COMP_MASK, XIICPS_IXR_NACK_MASK, XIICPS_IXR_TO_MASK, XIicPs_ReadReg, XIicPs_SetupMaster, XIicPs_WriteReg.
Referenced by IicPsMasterIntrExample, IicPsMultiMasterIntrExample, XIicPsSmbusMasterReadBlockData, XIicPsSmbusMasterWriteBlockData.
void XIicPs_MasterRecv(XIicPs *InstancePtr, u8 *MsgPtr, s32 ByteCount, u16 SlaveAddr)
Initiates an interrupt-driven receive in master mode.
It sets the transfer size register so the slave can send data. The rest of the work is managed by interrupt handler. InstancePtr Pointer to the XIicPs instance. MsgPtr Pointer to the receive buffer. ByteCount Number of bytes to be received. SlaveAddr Address of the slave we are receiving from. None. This receive routine is for interrupt-driven transfer only.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::CurrByteCount, XIicPs::IsReady, XIicPs::IsRepeatedStart, XIicPs::IsSend, XIicPs::RecvBufferPtr, XIicPs::RecvByteCount, RECVING_ROLE, XIicPs_Config::RefClk, XIicPs::SendBufferPtr, XIicPs::UpdateTxSize, XIICPS_ADDR_OFFSET, XIICPS_CR_OFFSET, XIicPs_EnableInterrupts, XIICPS_ISR_OFFSET, XIICPS_IXR_ALL_INTR_MASK, XIICPS_IXR_ARB_LOST_MASK, XIICPS_IXR_COMP_MASK, XIICPS_IXR_DATA_MASK, XIICPS_IXR_NACK_MASK, XIICPS_IXR_RX_OVR_MASK, XIICPS_IXR_TO_MASK, XIICPS_MAX_TRANSFER_SIZE, XIicPs_ReadReg, XIicPs_SetupMaster, XIICPS_TRANS_SIZE_OFFSET, XIicPs_WriteReg.
Referenced by IicPsMasterIntrExample, IicPsMultiMasterIntrExample, XIicPsSmbusMasterReadBlockData.
s32 XIicPs_MasterSendPolled(XIicPs *InstancePtr, u8 *MsgPtr, s32 ByteCount, u16 SlaveAddr)
Initiates a polled mode send in master mode.
It sends data to the FIFO and waits for the slave to pick them up. If master fails to send data due arbitration lost, will stop transfer and with arbitration lost status. If slave fails to remove data from FIFO, the send fails with time out. InstancePtr Pointer to the XIicPs instance. MsgPtr Pointer to the send buffer. ByteCount Number of bytes to be sent. SlaveAddr Address of the slave we are sending to. XST_SUCCESS if everything went well.XST_FAILURE if timed out.XST_IIC_ARB_LOST if arbitration lost This send routine is for polled mode transfer only.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::IsReady, XIicPs::IsRepeatedStart, XIicPs_Config::RefClk, XIicPs::SendBufferPtr, XIicPs::SendByteCount, SENDING_ROLE, TransmitFifoFill, TX_MAX_LOOPCNT, XIICPS_ADDR_OFFSET, XIICPS_CR_OFFSET, XIICPS_ISR_OFFSET, XIICPS_IXR_ARB_LOST_MASK, XIICPS_IXR_COMP_MASK, XIICPS_IXR_NACK_MASK, XIICPS_IXR_TX_OVR_MASK, XIicPs_ReadReg, XIicPs_SetupMaster, XIICPS_SR_OFFSET, XIicPs_WriteReg.
Referenced by EepromWriteData, IicPsMasterPolledExample, IicPsMultiMasterPolledExample, XIicPsSmbusPolledMasterReadBlockData, XIicPsSmbusPolledMasterWriteBlockData.
s32 XIicPs_MasterRecvPolled(XIicPs *InstancePtr, u8 *MsgPtr, s32 ByteCount, u16 SlaveAddr)
Initiates a polled mode receive in master mode.
It repeatedly sets the transfer size register so the slave can send data to us. It polls the data register for data to come in. If master fails to read data due arbitration lost, will return with arbitration lost status. If slave fails to send us data, it fails with time out. InstancePtr Pointer to the XIicPs instance. MsgPtr Pointer to the receive buffer. ByteCount Number of bytes to be received. SlaveAddr Address of the slave we are receiving from. XST_SUCCESS if everything went well.XST_FAILURE if timed out.XST_IIC_ARB_LOST if arbitration lost This receive routine is for polled mode transfer only.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::IsReady, XIicPs::IsRepeatedStart, XIicPs::RecvBufferPtr, XIicPs::RecvByteCount, RECVING_ROLE, XIicPs_Config::RefClk, XIicPs::UpdateTxSize, XIICPS_ADDR_OFFSET, XIICPS_CR_OFFSET, XIICPS_ISR_OFFSET, XIICPS_IXR_ARB_LOST_MASK, XIICPS_IXR_NACK_MASK, XIICPS_IXR_RX_OVR_MASK, XIICPS_IXR_RX_UNF_MASK, XIicPs_MasterPolledRead, XIICPS_MAX_TRANSFER_SIZE, XIicPs_ReadReg, XIicPs_SetupMaster, XIICPS_TRANS_SIZE_OFFSET, XIicPs_WriteReg.
Referenced by EepromReadDataRepStart, IicPsMasterPolledExample, IicPsMultiMasterPolledExample, XIicPsSmbusPolledMasterReadBlockData.
void XIicPs_EnableSlaveMonitor(XIicPs *InstancePtr, u16 SlaveAddr)
Enables the slave monitor mode.
It enables slave monitor in the control register and enables slave ready interrupt. It then does an address transfer to slave. Interrupt handler will signal the caller if slave responds to the address transfer. InstancePtr Pointer to the XIicPs instance. SlaveAddr Address of the slave to contact. None.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::Is10BitAddr, XIicPs_Config::RefClk, XIICPS_ADDR_OFFSET, XIICPS_CR_OFFSET, XIicPs_EnableInterrupts, XIICPS_IXR_SLV_RDY_MASK, XIicPs_ReadReg, XIICPS_SLV_PAUSE_OFFSET, XIICPS_TRANS_SIZE_OFFSET, XIicPs_WriteReg.
void XIicPs_DisableSlaveMonitor(XIicPs *InstancePtr)
Disables slave monitor mode.
InstancePtr Pointer to the XIicPs instance. None.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs_Config::RefClk, XIICPS_CR_OFFSET, XIicPs_DisableInterrupts, XIICPS_IXR_SLV_RDY_MASK, XIicPs_ReadReg, XIicPs_WriteReg.
void XIicPs_MasterInterruptHandler(XIicPs *InstancePtr)
The interrupt handler for the master mode.
It does the protocol handling for the interrupt-driven transfers.Completion events and errors are signaled to upper layer for proper handling.The interrupts that are handled are: DATA: This case is handled only for master receive data. The master has to request for more data (if there is more data to receive) and read the data from the FIFO.COMP: If the Master is transmitting data and there is more data to be sent then the data is written to the FIFO. If there is no more data to be transmitted then a completion event is signalled to the upper layer by calling the callback handler.If the Master is receiving data then the data is read from the FIFO and the Master has to request for more data (if there is more data to receive). If all the data has been received then a completion event is signalled to the upper layer by calling the callback handler. It is an error if the amount of received data is more than expected.NAK and SLAVE_RDY: This is signalled to the upper layer by calling the callback handler.All Other interrupts: These interrupts are marked as error. This is signalled to the upper layer by calling the callback handler. InstancePtr Pointer to the XIicPs instance. None.
References XIicPs_Config::BaseAddress, XIicPs::CallBackRef, XIicPs::Config, XIicPs::IsReady, XIicPs::IsRepeatedStart, XIicPs::IsSend, XIicPs::RecvByteCount, XIicPs::StatusHandler, XIICPS_CR_OFFSET, XIicPs_DisableInterrupts, XIICPS_EVENT_ARB_LOST, XIICPS_EVENT_COMPLETE_RECV, XIICPS_EVENT_ERROR, XIICPS_EVENT_NACK, XIICPS_EVENT_SLAVE_RDY, XIICPS_EVENT_TIME_OUT, XIICPS_IMR_OFFSET, XIICPS_ISR_OFFSET, XIICPS_IXR_ARB_LOST_MASK, XIICPS_IXR_COMP_MASK, XIICPS_IXR_NACK_MASK, XIICPS_IXR_RX_OVR_MASK, XIICPS_IXR_RX_UNF_MASK, XIICPS_IXR_SLV_RDY_MASK, XIICPS_IXR_TO_MASK, XIICPS_IXR_TX_OVR_MASK, XIicPs_MasterIntrRead, XIicPs_MasterIntrSend, XIicPs_ReadReg, XIicPs_WriteReg.
Referenced by IicPsMasterIntrExample, IicPsMultiMasterIntrExample, IicPsSmbusSlaveIntrExample, XIicPsSmbusMasterIntrExample.
TX_MAX_LOOPCNT
Used to wait in polled function.
Referenced by XIicPs_MasterSendPolled.