xiicps_selftest.c
REG_TEST_VALUE
Register value to write.
Referenced by XIicPs_SelfTest.
s32 XIicPs_SelfTest(XIicPs *InstancePtr)
Functions for selftest, in xiicps_selftest.c.
Runs a self-test on the driver/device.The self-test is destructive in that a reset of the device is performed in order to check the reset values of the registers and to get the device into a known state.Upon successful return from the self-test, the device is reset. InstancePtr Pointer to the XIicPs instance. XST_SUCCESS if successful.XST_REGISTER_ERROR indicates a register did not read or write correctly. None.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::IsReady, REG_TEST_VALUE, XIICPS_CR_OFFSET, XIICPS_IMR_OFFSET, XIICPS_IXR_ALL_INTR_MASK, XIicPs_ReadReg, XIicPs_Reset, XIICPS_SLV_PAUSE_OFFSET, XIicPs_WriteReg.
Referenced by IicPsMasterIntrExample, IicPsMasterPolledExample, IicPsMultiMasterIntrExample, IicPsMultiMasterPolledExample, IicPsSelfTestExample, IicPsSlaveIntrExample, IicPsSlavePolledExample, IicPsSmbusSlaveIntrExample, IicPsSmbusSlavePolledExample, XIicPsSmbusMasterIntrExample.