xiicps_xfer.c
s32 XIicPs_SetupMaster(XIicPs *InstancePtr, s32 Role)
This function prepares a device to transfers as a master.
InstancePtr Pointer to the XIicPs instance. Role Specifies whether the device is sending or receiving. XST_SUCCESS if everything went well.XST_FAILURE if bus is busy. Interrupts are always disabled. The device which needs to use interrupts must setup interrupts after this call.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::Is10BitAddr, RECVING_ROLE, XIicPs_BusIsBusy, XIICPS_CR_OFFSET, XIicPs_DisableAllInterrupts, XIicPs_ReadReg, XIicPs_WriteReg.
Referenced by XIicPs_MasterRecv, XIicPs_MasterRecvPolled, XIicPs_MasterSend, XIicPs_MasterSendPolled.
void MasterSendData(XIicPs *InstancePtr)
This function handles continuation of sending data.
It is invoked from interrupt handler. InstancePtr Pointer to the XIicPs instance. None.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::IsRepeatedStart, XIicPs::SendByteCount, TransmitFifoFill, XIICPS_CR_OFFSET, XIicPs_ReadReg, XIicPs_WriteReg.
Referenced by XIicPs_MasterIntrSend.
void XIicPs_MasterPolledRead(XIicPs *InstancePtr, s32 IsHold, s32 ByteCountVar)
Handles polled mode receive in master mode.
InstancePtr Pointer to the XIicPs instance. IsHold Hold status. ByteCountVar ByteCount. None.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::RecvByteCount, XIicPs::UpdateTxSize, XIICPS_ADDR_OFFSET, XIICPS_ISR_OFFSET, XIICPS_IXR_ARB_LOST_MASK, XIICPS_IXR_NACK_MASK, XIICPS_IXR_RX_OVR_MASK, XIICPS_IXR_RX_UNF_MASK, XIicPs_MasterRead, XIICPS_MAX_TRANSFER_SIZE, XIicPs_ReadReg, XIICPS_TRANS_SIZE_OFFSET, XIicPs_WriteReg.
Referenced by XIicPs_MasterRecvPolled.
void XIicPs_MasterIntrSend(XIicPs *InstancePtr, u32 IntrStatusReg, u32 *StatusEventPtr)
Handles interrupt-driven send in master mode.
InstancePtr Pointer to the XIicPs instance. IntrStatusReg Value of interrupt status register. StatusEventPtr Pointer to the StatusEvent. None.
References XIicPs::IsSend, MasterSendData, XIicPs::SendByteCount, XIICPS_EVENT_COMPLETE_SEND, XIICPS_IXR_COMP_MASK.
Referenced by XIicPs_MasterInterruptHandler.
void XIicPs_MasterIntrRead(XIicPs *InstancePtr, u32 *IntrStatusRegPtr, s32 IsHold)
Handles interrupt-driven receive in master mode.
InstancePtr Pointer to the XIicPs instance. IntrStatusRegPtr Pointer to the interrupt status register. IsHold Hold status. None.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::CurrByteCount, XIicPs::IsSend, XIicPs::RecvByteCount, XIicPs::UpdateTxSize, XIICPS_ADDR_OFFSET, XIicPs_EnableInterrupts, XIICPS_ISR_OFFSET, XIICPS_IXR_ARB_LOST_MASK, XIICPS_IXR_COMP_MASK, XIICPS_IXR_DATA_MASK, XIICPS_IXR_NACK_MASK, XIICPS_IXR_RX_OVR_MASK, XIicPs_MasterRead, XIICPS_MAX_TRANSFER_SIZE, XIicPs_ReadReg, XIICPS_TRANS_SIZE_OFFSET, XIicPs_WriteReg.
Referenced by XIicPs_MasterInterruptHandler.
s32 SlaveRecvData(XIicPs *InstancePtr)
Handles the continuation of receiving data.
It is invoked from interrupt handler. InstancePtr Pointer to the XIicPs instance. Number of bytes still expected by the instance. None.
References XIicPs_Config::BaseAddress, XIicPs::Config, XIicPs::RecvByteCount, XIICPS_DATA_OFFSET, XIicPs_ReadReg, XIICPS_SR_OFFSET.
Referenced by XIicPs_SlaveInterruptHandler.