xiicps_sinit.c
XIicPs_Config * XIicPs_LookupConfig(UINTPTR BaseAddress)
Function for configuration lookup, in xiicps_sinit.c.
Looks up the device configuration based on the unique device ID/BaseAddress.The XIicPs_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xiicps.h for the definition of XIicPs_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XIicPs_Config::Name, XIicPs_ConfigTable.
Referenced by IicPsMasterIntrExample, IicPsMasterPolledExample, IicPsMultiMasterIntrExample, IicPsMultiMasterPolledExample, IicPsRepeatedStartExample, IicPsSelfTestExample, IicPsSlaveIntrExample, IicPsSlavePolledExample, IicPsSmbusSlaveIntrExample, IicPsSmbusSlavePolledExample, XIicPsSmbusMasterIntrExample.