
APP =
APPSOURCES=*.c
OUTS =
MIX_OBJS =
INCLUDES =
BOARD_FLAG =
OBJS =

%.o: %.c
	$(CC) ${LDFLAGS} ${BOARD_FLAG} $(INCLUDES) ${CFLAGS} -c $(APPSOURCES)

all: $(MIX_OBJS)
	$(CC) ${LDFLAGS} $(INCLUDES) $(OBJS) $(MIX_OBJS) -o $(OUTS) -ldfemix

clean:
	rm -rf $(OUTS) *.o
