xdevcfg_reg_readback_example.c
XDC_TYPE_SHIFT
XDC_REGISTER_SHIFT
XDC_OP_SHIFT
XDC_TYPE_1
OPCODE_READ
DCFG_BASEADDR
CRC
FAR
FDRI
FDRO
CMD
CTL0
MASK
STAT
LOUT
COR0
MFWR
CBC
IDCODE
AXSS
COR1
WBSTAR
TIMER
BOOTSTS
CTL1
IDCODE_MASK
XDcfg DcfgInstance
int XDcfgRegReadExample(UINTPTR BaseAddress)
This function reads the configuration registers inside the FPGA.
DeviceId is the unique device id of the device. XST_SUCCESS if successfulXST_FAILURE if unsuccessful None.
References XDcfg_Config::BaseAddr, XDcfg_CfgInitialize, XDcfg_GetConfigReg, XDcfg_LookupConfig, XDcfg_SelfTest.
Referenced by main.
int XDcfg_GetConfigReg(XDcfg *DcfgInstancePtr, u32 ConfigReg, u32 *RegData)
This function returns the value of the specified configuration register.
InstancePtr is a pointer to the XHwIcap instance. ConfigReg is a constant which represents the configuration register value to be returned. RegData is the value of the specified configuration register. XST_SUCCESS if successfulXST_FAILURE if unsuccessful None.
References XDcfg_Config::BaseAddr, XDcfg::Config, XDCFG_DMA_INVALID_ADDRESS, XDcfg_InitiateDma, XDcfg_IntrClear, XDcfg_IntrGetStatus, XDCFG_IXR_D_P_DONE_MASK, XDCFG_IXR_DMA_DONE_MASK, XDCFG_IXR_PCFG_DONE_MASK, XDcfg_ReadReg, XDcfg_RegAddr, XDCFG_STATUS_DMA_CMD_Q_F_MASK, XDCFG_STATUS_OFFSET, XDcfg_Transfer.
Referenced by XDcfgRegReadExample.
u32 XDcfg_RegAddr(u8 Register, u8 OpCode, u8 Size)
Generates a Type 1 packet header that reads back the requested Configuration register.
Register is the address of the register to be read back. OpCode is the read/write operation code. Size is the size of the word to be read. Type 1 packet header to read the specified register None.
Referenced by XDcfg_GetConfigReg.
int main(void)
Main function to call the DevCfg Reg Read example.
None. XST_SUCCESS if successfulXST_FAILURE if unsuccessful None.
References XDcfgRegReadExample.