xdevcfg_sinit.c
XDcfg_Config * XDcfg_LookupConfig(UINTPTR BaseAddress)
Lookup the device configuration based on the unique device ID.
The table contains the configuration info for each device in the system. DeviceId is the unique device ID of the device being looked up. A pointer to the configuration table entry corresponding to the given device ID, or NULL if no match is found. None.
Referenced by DcfgSelfTestExample, XDcfg_IntrExample, XDcfgPolledExample, XDcfgRegReadExample.