xdevcfg_intr.c
void XDcfg_IntrEnable(XDcfg *InstancePtr, u32 Mask)
This function enables the specified interrupts in the device.
InstancePtr is a pointer to the XDcfg instance. Mask is the bit-mask of the interrupts to be enabled. Bit positions of 1 will be enabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XDCFG_INT_* bits defined in xdevcfg_hw.h. None. None.
References XDcfg_Config::BaseAddr, XDcfg::Config, XDcfg::IsReady, XDCFG_INT_MASK_OFFSET, XDcfg_ReadReg, XDcfg_WriteReg.
Referenced by XDcfg_IntrExample.
void XDcfg_IntrDisable(XDcfg *InstancePtr, u32 Mask)
This function disables the specified interrupts in the device.
InstancePtr is a pointer to the XDcfg instance. Mask is the bit-mask of the interrupts to be disabled. Bit positions of 1 will be disabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XDCFG_INT_* bits defined in xdevcfg_hw.h. None. None.
References XDcfg_Config::BaseAddr, XDcfg::Config, XDcfg::IsReady, XDCFG_INT_MASK_OFFSET, XDcfg_ReadReg, XDcfg_WriteReg.
Referenced by XDcfg_IntrExample.
u32 XDcfg_IntrGetEnabled(XDcfg *InstancePtr)
This function returns the enabled interrupts read from the Interrupt Mask Register.
Use the XDCFG_INT_* constants defined in xdevcfg_hw.h to interpret the returned value. InstancePtr is a pointer to the XDcfg instance. A 32-bit value representing the contents of the IMR. None.
References XDcfg_Config::BaseAddr, XDcfg::Config, XDcfg::IsReady, XDCFG_INT_MASK_OFFSET, XDcfg_ReadReg.
u32 XDcfg_IntrGetStatus(XDcfg *InstancePtr)
This function returns the interrupt status read from Interrupt Status Register.
Use the XDCFG_INT_* constants defined in xdevcfg_hw.h to interpret the returned value. InstancePtr is a pointer to the XDcfg instance. A 32-bit value representing the contents of the Interrupt Status register. None.
References XDcfg_Config::BaseAddr, XDcfg::Config, XDcfg::IsReady, XDCFG_INT_STS_OFFSET, XDcfg_ReadReg.
Referenced by XDcfg_GetConfigReg, XDcfg_IntrExample, XDcfgPolledExample.
void XDcfg_IntrClear(XDcfg *InstancePtr, u32 Mask)
This function clears the specified interrupts in the Interrupt Status Register.
InstancePtr is a pointer to the XDcfg instance. Mask is the bit-mask of the interrupts to be cleared. Bit positions of 1 will be cleared. Bit positions of 0 will not change the previous interrupt status. This mask is formed by OR'ing XDCFG_INT_* bits which are defined in xdevcfg_hw.h. None. None.
References XDcfg_Config::BaseAddr, XDcfg::Config, XDcfg::IsReady, XDCFG_INT_STS_OFFSET, XDcfg_WriteReg.
Referenced by XDcfg_GetConfigReg, XDcfg_IntrExample, XDcfgPolledExample.
void XDcfg_InterruptHandler(XDcfg *InstancePtr)
The interrupt handler for the Device Config Interface.
Events are signaled to upper layer for proper handling. InstancePtr is a pointer to the XDcfg instance. None. None.
References XDcfg_Config::BaseAddr, XDcfg::Config, XDcfg::IsReady, XDCFG_INT_STS_OFFSET, XDcfg_ReadReg, XDcfg_WriteReg.
Referenced by XDcfg_IntrExample.
void XDcfg_SetHandler(XDcfg *InstancePtr, void *CallBackFunc, void *CallBackRef)
This function sets the handler that will be called when an event (interrupt) occurs that needs application's attention.
InstancePtr is a pointer to the XDcfg instance CallBackFunc is the address of the callback function. CallBackRef is a user data item that will be passed to the callback function when it is invoked. None. None.
References XDcfg::IsReady.
Referenced by XDcfg_IntrExample.