xdevcfg_selftest.c
int XDcfg_SelfTest(XDcfg *InstancePtr)
Run a self-test on the Device Configuration Interface.
This test does a control register write and reads back the same value. InstancePtr is a pointer to the XDcfg instance. XST_SUCCESS if self-test was successful.XST_FAILURE if fails. None.
References XDcfg::IsReady, XDCFG_CTRL_NIDEN_MASK, XDcfg_GetControlRegister, XDcfg_SetControlRegister.
Referenced by DcfgSelfTestExample, XDcfg_IntrExample, XDcfgPolledExample, XDcfgRegReadExample.