mipi_tx_phy
XMIPI_TX_PHY_MODE_MIN
Lower limit for Mode.
XMIPI_TX_PHY_LOW_POWER_MODE
Lane in Low Power Mode.
XMIPI_TX_PHY_HIGH_POWER_MODE
Lane in High Power Mode.
XMIPI_TX_PHY_ESCAPE_MODE
Lane in Escape Mode.
XMIPI_TX_PHY_MODE_MAX
Upper Limit for mode.
XMIPI_TX_PHY_MAX_LANES_V10
V1.0 supports 4 Lanes.
XMIPI_TX_PHY_HANDLE_MIN
Lower Bound for XMIPI_TX_PHY_HANDLE.
XMIPI_TX_PHY_HANDLE_INIT_TIMER
Handle for Initialization Timer.
XMIPI_TX_PHY_HANDLE_HSTIMEOUT
Handle for HS Timeout.
Referenced by XMipi_Tx_Phy_SelfTest.
XMIPI_TX_PHY_HANDLE_ESCTIMEOUT
Handle for Escape Timeout.
XMIPI_TX_PHY_HANDLE_CLKLANE
Handle for Clock Lane.
XMIPI_TX_PHY_HANDLE_DLANE0
Handle for Data Lane 0.
XMIPI_TX_PHY_HANDLE_DLANE1
Handle for Data Lane 1.
XMIPI_TX_PHY_HANDLE_DLANE2
Handle for Data Lane 2.
XMIPI_TX_PHY_HANDLE_DLANE3
Handle for Data Lane 3.
XMIPI_TX_PHY_HANDLE_MAX
Upper Bound for XMIPI_TX_PHY_HANDLE.
XMIPI_TX_PHY_HS_TIMEOUT_MIN_VALUE
Minimum HS timeout value.
XMIPI_TX_PHY_HS_TIMEOUT_MAX_VALUE
Maximum HS timeout value.
XMIPI_TX_PHY_HS_SETTLE_MAX_VALUE
Maximum HS settle value (9-bit)
XMIPI_TX_PHY_ENABLE_FLAG
Flag to enable PHY core.
XMIPI_TX_PHY_DISABLE_FLAG
Flag to disable PHY core.
XMIPI_TX_PHY_CTRL_REG_OFFSET
Control Register.
XMIPI_TX_PHY_VERSION_REG_OFFSET
Core Version Register.
XMIPI_TX_PHY_INIT_TIMER_REG_OFFSET
Initialization Timer Register.
XMIPI_TX_PHY_HSTIMEOUT_REG_OFFSET
Watchdog timeout in HS mode Register.
XMIPI_TX_PHY_ESCTIMEOUT_REG_OFFSET
Goto Stop state on timeout timer Register.
XMIPI_TX_PHY_CLSTATUS_REG_OFFSET
Clk lane PHY error Status Register.
XMIPI_TX_PHY_DL0STATUS_REG_OFFSET
Data lane 0 PHY error Status Register.
XMIPI_TX_PHY_DL1STATUS_REG_OFFSET
Data lane 1 PHY error Status Register.
XMIPI_TX_PHY_DL2STATUS_REG_OFFSET
Data lane 2 PHY error Status Register.
XMIPI_TX_PHY_DL3STATUS_REG_OFFSET
Data lane 3 PHY error Status Register.
XMIPI_TX_PHY_PROG_SEQ_CTRL_OFFSET
Prog Seq Control Register.
XMIPI_TX_PHY_PROG_SEQ_DATA0_OFFSET
Prog Seq Data Register 0.
XMIPI_TX_PHY_PROG_SEQ_DATA1_OFFSET
Prog Seq Data Register 1.
XMIPI_TX_PHY_CTRL_REG_SOFTRESET_MASK
Soft Reset.
XMIPI_TX_PHY_CTRL_REG_PHYEN_MASK
Enable/Disable controller.
XMIPI_TX_PHY_CTRL_REG_SOFTRESET_OFFSET
Bit offset for Soft Reset.
XMIPI_TX_PHY_CTRL_REG_PHYEN_OFFSET
Bit offset for PHY Enable.
XMIPI_TX_PHY_PROG_SEQ_EN_MASK
Enable/Disable Prog Seq.
XMIPI_TX_PHY_INIT_REG_VAL_MASK
Init Timer value in ns.
XMIPI_TX_PHY_INIT_REG_VAL_OFFSET
Bit offset for Init Timer.
XMIPI_TX_PHY_HSTIMEOUT_REG_TIMEOUT_MASK
HS_TX_TIMEOUT Received.
XMIPI_TX_PHY_HSTIMEOUT_REG_TIMEOUT_OFFSET
Bit offset for Timeout.
XMIPI_TX_PHY_ESCTIMEOUT_REG_VAL_MASK
Escape Timeout Value.
XMIPI_TX_PHY_ESCTIMEOUT_REG_VAL_OFFSET
Bit offset for Escape Timeout.
XMIPI_TX_PHY_CLSTATUS_REG_ERRCTRL_MASK
Clock lane control error.
Only for RX
XMIPI_TX_PHY_CLSTATUS_REG_STOPSTATE_MASK
Clock lane stop state.
XMIPI_TX_PHY_CLSTATUS_REG_INITDONE_MASK
Initialization done bit.
XMIPI_TX_PHY_CLSTATUS_REG_ULPS_MASK
Set in ULPS mode.
XMIPI_TX_PHY_CLSTATUS_REG_MODE_MASK
Low, High, Esc mode.
Combined mask of all clock lane status bits including error control, stop state, initialization done, ULPS, and mode bits
XMIPI_TX_PHY_CLSTATUS_ALLMASK
Combined mask of all clock lane status bits including error control, stop state, initialization done, ULPS, and mode bits.
XMIPI_TX_PHY_CLSTATUS_REG_ERRCTRL_OFFSET
Bit offset for Control Error on Clock.
XMIPI_TX_PHY_CLSTATUS_REG_STOPSTATE_OFFSET
Bit offset for Stop State on Clock.
XMIPI_TX_PHY_CLSTATUS_REG_INITDONE_OFFSET
Bit offset for Initialization Done.
XMIPI_TX_PHY_CLSTATUS_REG_ULPS_OFFSET
Bit offset for ULPS.
XMIPI_TX_PHY_CLSTATUS_REG_MODE_OFFSET
Bit offset for Mode bits.
XMIPI_TX_PHY_DLXSTATUS_REG_PACKETCOUNT_MASK
Packet Count.
XMIPI_TX_PHY_DLXSTATUS_REG_CALIB_STATUS_MASK
Calib status.
XMIPI_TX_PHY_DLXSTATUS_REG_CALIB_COMPLETE_MASK
Calib complete.
XMIPI_TX_PHY_DLXSTATUS_REG_STOP_MASK
Stop State on data lane.
XMIPI_TX_PHY_DLXSTATUS_REG_ESCABRT_MASK
Set on Data Lane Esc timeout occurs.
XMIPI_TX_PHY_DLXSTATUS_REG_HSABRT_MASK
Set on Data Lane HS timeout.
XMIPI_TX_PHY_DLXSTATUS_REG_INITDONE_MASK
Set after initialization.
XMIPI_TX_PHY_DLXSTATUS_REG_ULPS_MASK
Set when MIPI_TX_PHY in ULPS mode.
XMIPI_TX_PHY_DLXSTATUS_REG_MODE_MASK
Control Mode (Esc, Low, High) of Data Lane.
XMIPI_TX_PHY_DLXSTATUS_ALLMASK
Combined mask for all data lane status bits.
Combined mask of all data lane status bits including mode, ULPS, initialization done, HS abort, escape abort, stop state, calibration status, and calibration complete bits
XMIPI_TX_PHY_DLXSTATUS_REG_PACKCOUNT_OFFSET
Bit offset packet count.
XMIPI_TX_PHY_DLXSTATUS_REG_CALIB_STATUS_OFFSET
Bit offset calib status.
XMIPI_TX_PHY_DLXSTATUS_REG_CALIB_COMPLETE_OFFSET
Bit offset Calib complete.
XMIPI_TX_PHY_DLXSTATUS_REG_STOP_OFFSET
Bit offset for Stop State.
XMIPI_TX_PHY_DLXSTATUS_REG_ESCABRT_OFFSET
Bit offset for Escape Abort.
XMIPI_TX_PHY_DLXSTATUS_REG_HSABRT_OFFSET
Bit offset for High Speed Abort.
XMIPI_TX_PHY_DLXSTATUS_REG_INITDONE_OFFSET
Bit offset for Initialization done.
XMIPI_TX_PHY_DLXSTATUS_REG_ULPS_OFFSET
Bit offset for ULPS.
XMIPI_TX_PHY_DLXSTATUS_REG_MODE_OFFSET
Bit offset for Modes.
XMIPI_TX_PHY_HSSETTLE_REG_TIMEOUT_MASK
HS_SETTLE value.
XMIPI_TX_PHY_HSSETTLE_REG_TIMEOUT_OFFSET
Bit offset for HS_SETTLE.
XMipi_Tx_Phy_ProgSeq
Programmable sequence symbol position 0.
u32 XMipi_Tx_Phy_CfgInitialize(XMipi_Tx_Phy *InstancePtr, XMipi_Tx_Phy_Config *CfgPtr, UINTPTR EffectiveAddr)
Initialize the XMipi_Tx_Phy instance provided by the caller based on the given Config structure.
InstancePtr is the XMipi_Tx_Phy instance to operate on. CfgPtr is the device configuration structure containing information about a specific Mipi_Tx_Phy instance. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS Initialization was successful. None.
References XMipi_Tx_Phy_Config::BaseAddr, XMipi_Tx_Phy::Config, XMipi_Tx_Phy::IsReady.
Referenced by Mipi_Tx_PhySelfTestExample.
u32 XMipi_Tx_Phy_Configure(XMipi_Tx_Phy *InstancePtr, u8 Handle, u32 Value)
Configure the registers of the Mipi_Tx_Phy instance.
InstancePtr is the XMipi_Tx_Phy instance to operate on. Handle to one of the registers to be configured Value to be set for the particular Handle of the Mipi_Tx_Phy instance XST_SUCCESS on successful register update.XST_FAILURE If incorrect handle was passed There is a limit on the minimum and maximum values of the HS Timeout register.
u32 XMipi_Tx_Phy_Prog_Seq_Data(XMipi_Tx_Phy *InstancePtr, XMipi_Tx_Phy_ProgSeq bitpos, u32 Value)
Program a symbol value into the programmable sequence table.
This helper masks in the 3-bit symbol value into the correct programmable sequence register (DATA0 or DATA1) based on the requested symbol index. The programmable sequence control is temporarily disabled to avoid partial writes. InstancePtr is the XMipi_Tx_Phy instance. bitpos is the programmable sequence symbol index. Value is the 3-bit symbol value to program. XST_SUCCESS if the symbol was programmed.XST_FAILURE if the control register remained enabled and the write was aborted. The core must be configured for C-PHY mode (IsDphy == 0) and register access must be enabled.
u32 XMipi_Tx_Phy_Get_Seq_Data(XMipi_Tx_Phy *InstancePtr, XMipi_Tx_Phy_ProgSeq bitpos)
Read a programmable sequence register.
InstancePtr is the XMipi_Tx_Phy instance. bitpos is the programmable sequence symbol index. Register contents of DATA0 (symbols 0-9) or DATA1 (symbols 10-13). The core must be configured for C-PHY mode (IsDphy == 0) and register access must be enabled.
u32 XMipi_Tx_Phy_En_Prog_Seq_Ctrl(XMipi_Tx_Phy *InstancePtr)
Enable programmable sequence control.
InstancePtr is the XMipi_Tx_Phy instance. XST_SUCCESS always. The core must be configured for C-PHY mode (IsDphy == 0) and register access must be enabled.
u32 XMipi_Tx_Phy_Dis_Prog_Seq_Ctrl(XMipi_Tx_Phy *InstancePtr)
Disable programmable sequence control.
InstancePtr is the XMipi_Tx_Phy instance. XST_SUCCESS always. The core must be configured for C-PHY mode (IsDphy == 0) and register access must be enabled.
u32 XMipi_Tx_Phy_Get_Prog_Seq_Ctrl(XMipi_Tx_Phy *InstancePtr)
Read the programmable sequence control register.
InstancePtr is the XMipi_Tx_Phy instance. Current contents of the programmable sequence control register. The core must be configured for C-PHY mode (IsDphy == 0) and register access must be enabled.
u8 XMipi_Tx_Phy_GetRegIntfcPresent(XMipi_Tx_Phy *InstancePtr)
Get if register interface is present from the config structure for specified Mipi_Tx_Phy instance.
InstancePtr is the XMipi_Tx_Phy instance to operate on. 1 if register interface is present0 if register interface is absent None.
Referenced by Mipi_Tx_PhySelfTestExample.
u32 XMipi_Tx_Phy_GetInfo(XMipi_Tx_Phy *InstancePtr, u8 Handle)
Get information stored in the Mipi_Tx_Phy instance based on the handle passed.
InstancePtr is the XMipi_Tx_Phy instance to operate on. Handle to one of the registers to be configured The value stored in the corresponding register None.
Referenced by XMipi_Tx_Phy_SelfTest.
void XMipi_Tx_Phy_Reset(XMipi_Tx_Phy *InstancePtr)
This is used to do a soft reset of the Mipi_Tx_Phy IP instance.
The reset takes approx 20 core clock cycles to become effective. InstancePtr is the XMipi_Tx_Phy instance to operate on. None.
void XMipi_Tx_Phy_ClearDataLane(XMipi_Tx_Phy *InstancePtr, u8 DataLane, u32 Mask)
This is used to clear the Abort Error (Escape or High Speed) bits in the Data Lane 0 through 3.
InstancePtr is the XMipi_Tx_Phy instance to operate on. DataLane represents which Data Lane to act upon Mask contains information about which bits to reset None.
u32 XMipi_Tx_Phy_GetClkLaneStatus(XMipi_Tx_Phy *InstancePtr)
This is used to get information about Clock Lane status.
InstancePtr is the XMipi_Tx_Phy instance to operate on. Bitmask containing which of the events have occurred along with the mode of the Clock Lane in DPhy None.
u32 XMipi_Tx_Phy_GetClkLaneMode(XMipi_Tx_Phy *InstancePtr)
This is used to get specific Lane mode information about Clock Lane.
InstancePtr is the XMipi_Tx_Phy instance to operate on. Bitmask containing mode in which the Clock Lane in Mipi_Tx_Phy is in. None.
u32 XMipi_Tx_Phy_GetDataLaneStatus(XMipi_Tx_Phy *InstancePtr, u8 DataLane)
This is used to get information about a Data Lane status.
InstancePtr is the XMipi_Tx_Phy instance to operate on. DataLane for which the status is sought for. Bitmask containing which of the events have occurred along with the mode of the Data Lane in DPhy None.
u8 XMipi_Tx_Phy_GetDLCalibStatus(XMipi_Tx_Phy *InstancePtr, u8 DataLane)
This is used to get Data Lane Calibration status.
InstancePtr is the XMipi_Tx_Phy instance to operate on. DataLane for which the calib status is sought for. XST_SUCCESS - Calibration Complete, Calibration packet received XST_NO_DATA - Calibration Complete, Calibration packet is not received XST_FAILURE - Calibration failed None.
u32 XMipi_Tx_Phy_GetDataLaneMode(XMipi_Tx_Phy *InstancePtr, u8 DataLane)
This is used to get specific Lane mode information about a Data Lane.
InstancePtr is the XMipi_Tx_Phy instance to operate on. DataLane for which the mode info is requested. Bitmask containing mode in which the Data Lane in Mipi_Tx_Phy is in. None.
u16 XMipi_Tx_Phy_GetPacketCount(XMipi_Tx_Phy *InstancePtr, u8 DataLane)
This is used to get count of packets received on each lane.
InstancePtr is the XMipi_Tx_Phy instance to operate on. DataLane for which the mode info is requested. Bitmask containing mode in which the Data Lane in Mipi_Tx_Phy is in. None.
u32 XMipi_Tx_Phy_GetVersionReg(XMipi_Tx_Phy *InstancePtr)
This is used to get Mipi_Tx_Phy Version.
InstancePtr is the XMipi_Tx_Phy instance to operate on. Returns major and minor Version number of this Mipi_Tx_Phy IP None.
void XMipi_Tx_Phy_Activate(XMipi_Tx_Phy *InstancePtr, u8 Flag)
This function is used to enable or disable the Mipi_Tx_Phy core.
InstancePtr is the XMipi_Tx_Phy instance to operate on. Flag denoting whether to enable or disable the Mipi_Tx_Phy core None.
static void XMipi_Tx_Phy_BitSet(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask)
This inline function is used to set bit in a mipi_tx_phy register space.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitMask of bit field to be set None None
static void XMipi_Tx_Phy_BitReset(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask)
This inline function is used to reset bit in a mipi_tx_phy register space.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitMask of bit field to be reset None None
static u32 XMipi_Tx_Phy_GetBitField(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask, u32 BitShift)
This function is used to get the value of bitfield from mipi_tx_phy register space.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitMask of bit field whose value needs to be obtained BitShift is offset of bit field Bit Field Value in u32 format None
static void XMipi_Tx_Phy_SetBitField(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask, u32 BitShift, u32 Value)
This function is used to set the value of bitfield from mipi_tx_phy register space.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitMask of bit field whose value needs to be updated BitShift is offset of bit field Value to be set. Passed in u32 format. None None
XMipi_Tx_Phy_Config * XMipi_Tx_Phy_LookupConfig(UINTPTR BaseAddress)
Look up the hardware configuration for a device instance.
BaseAddress is the BaseAddress of the device to lookup for The reference to the configuration record in the configuration table (in xmipi_tx_phy_g.c) corresponding to the BaseAddr or if not found,a NULL pointer is returned. None
Referenced by Mipi_Tx_PhySelfTestExample.
u32 XMipi_Tx_Phy_SelfTest(XMipi_Tx_Phy *InstancePtr)
Runs a self-test on the driver/device.
This test checks if HS Timeout value present in register matches the one from the generated file. InstancePtr is a pointer to the XMipi_Tx_Phy instance. XST_SUCCESS if self-test was successful XST_FAILURE if the read value was not equal to _g.c file None.
References XMipi_Tx_Phy::Config, XMipi_Tx_Phy_Config::HSTimeOut, XMipi_Tx_Phy_GetInfo, XMIPI_TX_PHY_HANDLE_HSTIMEOUT.
Referenced by Mipi_Tx_PhySelfTestExample.
static u32 XMipi_Tx_Phy_ReadReg(UINTPTR BaseAddress, u32 RegOffset)
This function reads a value from a MIPI_TX_PHY register space.
A 32 bit read is performed. If the component is implemented in a smaller width, only the least significant data is read from the register. The most significant data will be read as 0. BaseAddress is the base address of the XCsiSs core instance. RegOffset is the register offset of the register (defined at the top of this file). The 32-bit value of the register. None.
static void XMipi_Tx_Phy_WriteReg(UINTPTR BaseAddress, u32 RegOffset, u32 Data)
This function writes a value to a MIPI_TX_PHY register space A 32 bit write is performed.
If the component is implemented in a smaller width, only the least significant data is written. BaseAddress is the base address of the XCsiSs core instance. RegOffset is the register offset of the register (defined at the top of this file) to be written. Data is the 32-bit value to write into the register. None. None.
XMIPI_TX_PHY_SOFTRESET_TIMEOUT
Timeout value in loop iterations for soft reset completion.
Ensures at least 20 core clock cycles forreset to take effect.
XMIPI_TX_PHY_H_
Prevent circular inclusions by using protection macros.
XMIPI_TX_PHY_HW_H_
Prevent circular inclusions by using protection macros.
DL_LANE_OFFSET
Register offset between consecutive data lane status registers.