xmipi_tx_phy.h
XMIPI_TX_PHY_MODE_MIN
Lower limit for Mode.
XMIPI_TX_PHY_LOW_POWER_MODE
Lane in Low Power Mode.
XMIPI_TX_PHY_HIGH_POWER_MODE
Lane in High Power Mode.
XMIPI_TX_PHY_ESCAPE_MODE
Lane in Escape Mode.
XMIPI_TX_PHY_MODE_MAX
Upper Limit for mode.
XMIPI_TX_PHY_MAX_LANES_V10
V1.0 supports 4 Lanes.
XMIPI_TX_PHY_HANDLE_MIN
Lower Bound for XMIPI_TX_PHY_HANDLE.
XMIPI_TX_PHY_HANDLE_INIT_TIMER
Handle for Initialization Timer.
XMIPI_TX_PHY_HANDLE_HSTIMEOUT
Handle for HS Timeout.
Referenced by XMipi_Tx_Phy_SelfTest.
XMIPI_TX_PHY_HANDLE_ESCTIMEOUT
Handle for Escape Timeout.
XMIPI_TX_PHY_HANDLE_CLKLANE
Handle for Clock Lane.
XMIPI_TX_PHY_HANDLE_DLANE0
Handle for Data Lane 0.
XMIPI_TX_PHY_HANDLE_DLANE1
Handle for Data Lane 1.
XMIPI_TX_PHY_HANDLE_DLANE2
Handle for Data Lane 2.
XMIPI_TX_PHY_HANDLE_DLANE3
Handle for Data Lane 3.
XMIPI_TX_PHY_HANDLE_MAX
Upper Bound for XMIPI_TX_PHY_HANDLE.
XMIPI_TX_PHY_HS_TIMEOUT_MIN_VALUE
Minimum HS timeout value.
XMIPI_TX_PHY_HS_TIMEOUT_MAX_VALUE
Maximum HS timeout value.
XMIPI_TX_PHY_HS_SETTLE_MAX_VALUE
Maximum HS settle value (9-bit)
XMIPI_TX_PHY_ENABLE_FLAG
Flag to enable PHY core.
XMIPI_TX_PHY_DISABLE_FLAG
Flag to disable PHY core.
XMIPI_TX_PHY_H_
Prevent circular inclusions by using protection macros.
XMipi_Tx_Phy_ProgSeq
Programmable sequence symbol position 0.
static void XMipi_Tx_Phy_BitSet(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask)
This inline function is used to set bit in a mipi_tx_phy register space.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitMask of bit field to be set None None
static void XMipi_Tx_Phy_BitReset(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask)
This inline function is used to reset bit in a mipi_tx_phy register space.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitMask of bit field to be reset None None
static u32 XMipi_Tx_Phy_GetBitField(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask, u32 BitShift)
This function is used to get the value of bitfield from mipi_tx_phy register space.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitMask of bit field whose value needs to be obtained BitShift is offset of bit field Bit Field Value in u32 format None
static void XMipi_Tx_Phy_SetBitField(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask, u32 BitShift, u32 Value)
This function is used to set the value of bitfield from mipi_tx_phy register space.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitMask of bit field whose value needs to be updated BitShift is offset of bit field Value to be set. Passed in u32 format. None None
XMipi_Tx_Phy_Config * XMipi_Tx_Phy_LookupConfig(UINTPTR BaseAddress)
Look up the hardware configuration for a device instance.
BaseAddress is the BaseAddress of the device to lookup for The reference to the configuration record in the configuration table (in xmipi_tx_phy_g.c) corresponding to the BaseAddr or if not found,a NULL pointer is returned. None
Referenced by Mipi_Tx_PhySelfTestExample.
u32 XMipi_Tx_Phy_CfgInitialize(XMipi_Tx_Phy *InstancePtr, XMipi_Tx_Phy_Config *CfgPtr, UINTPTR EffectiveAddr)
Initialize the XMipi_Tx_Phy instance provided by the caller based on the given Config structure.
InstancePtr is the XMipi_Tx_Phy instance to operate on. CfgPtr is the device configuration structure containing information about a specific Mipi_Tx_Phy instance. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS Initialization was successful. None.
References XMipi_Tx_Phy_Config::BaseAddr, XMipi_Tx_Phy::Config, XMipi_Tx_Phy::IsReady.
Referenced by Mipi_Tx_PhySelfTestExample.
u32 XMipi_Tx_Phy_Configure(XMipi_Tx_Phy *InstancePtr, u8 Handle, u32 Value)
Configure the registers of the Mipi_Tx_Phy instance.
InstancePtr is the XMipi_Tx_Phy instance to operate on. Handle to one of the registers to be configured Value to be set for the particular Handle of the Mipi_Tx_Phy instance XST_SUCCESS on successful register update.XST_FAILURE If incorrect handle was passed There is a limit on the minimum and maximum values of the HS Timeout register.
u32 XMipi_Tx_Phy_GetInfo(XMipi_Tx_Phy *InstancePtr, u8 Handle)
Get information stored in the Mipi_Tx_Phy instance based on the handle passed.
InstancePtr is the XMipi_Tx_Phy instance to operate on. Handle to one of the registers to be configured The value stored in the corresponding register None.
Referenced by XMipi_Tx_Phy_SelfTest.
void XMipi_Tx_Phy_Reset(XMipi_Tx_Phy *InstancePtr)
This is used to do a soft reset of the Mipi_Tx_Phy IP instance.
The reset takes approx 20 core clock cycles to become effective. InstancePtr is the XMipi_Tx_Phy instance to operate on. None.
void XMipi_Tx_Phy_ClearDataLane(XMipi_Tx_Phy *InstancePtr, u8 DataLane, u32 Mask)
This is used to clear the Abort Error (Escape or High Speed) bits in the Data Lane 0 through 3.
InstancePtr is the XMipi_Tx_Phy instance to operate on. DataLane represents which Data Lane to act upon Mask contains information about which bits to reset None.
u32 XMipi_Tx_Phy_GetClkLaneStatus(XMipi_Tx_Phy *InstancePtr)
This is used to get information about Clock Lane status.
InstancePtr is the XMipi_Tx_Phy instance to operate on. Bitmask containing which of the events have occurred along with the mode of the Clock Lane in DPhy None.
u32 XMipi_Tx_Phy_GetClkLaneMode(XMipi_Tx_Phy *InstancePtr)
This is used to get specific Lane mode information about Clock Lane.
InstancePtr is the XMipi_Tx_Phy instance to operate on. Bitmask containing mode in which the Clock Lane in Mipi_Tx_Phy is in. None.
u32 XMipi_Tx_Phy_GetDataLaneStatus(XMipi_Tx_Phy *InstancePtr, u8 DataLane)
This is used to get information about a Data Lane status.
InstancePtr is the XMipi_Tx_Phy instance to operate on. DataLane for which the status is sought for. Bitmask containing which of the events have occurred along with the mode of the Data Lane in DPhy None.
u16 XMipi_Tx_Phy_GetPacketCount(XMipi_Tx_Phy *InstancePtr, u8 DataLane)
This is used to get count of packets received on each lane.
InstancePtr is the XMipi_Tx_Phy instance to operate on. DataLane for which the mode info is requested. Bitmask containing mode in which the Data Lane in Mipi_Tx_Phy is in. None.
u8 XMipi_Tx_Phy_GetDLCalibStatus(XMipi_Tx_Phy *InstancePtr, u8 DataLane)
This is used to get Data Lane Calibration status.
InstancePtr is the XMipi_Tx_Phy instance to operate on. DataLane for which the calib status is sought for. XST_SUCCESS - Calibration Complete, Calibration packet received XST_NO_DATA - Calibration Complete, Calibration packet is not received XST_FAILURE - Calibration failed None.
u32 XMipi_Tx_Phy_GetDataLaneMode(XMipi_Tx_Phy *InstancePtr, u8 DataLane)
This is used to get specific Lane mode information about a Data Lane.
InstancePtr is the XMipi_Tx_Phy instance to operate on. DataLane for which the mode info is requested. Bitmask containing mode in which the Data Lane in Mipi_Tx_Phy is in. None.
void XMipi_Tx_Phy_Activate(XMipi_Tx_Phy *InstancePtr, u8 Flag)
This function is used to enable or disable the Mipi_Tx_Phy core.
InstancePtr is the XMipi_Tx_Phy instance to operate on. Flag denoting whether to enable or disable the Mipi_Tx_Phy core None.
u8 XMipi_Tx_Phy_GetRegIntfcPresent(XMipi_Tx_Phy *InstancePtr)
Get if register interface is present from the config structure for specified Mipi_Tx_Phy instance.
InstancePtr is the XMipi_Tx_Phy instance to operate on. 1 if register interface is present0 if register interface is absent None.
Referenced by Mipi_Tx_PhySelfTestExample.
u32 XMipi_Tx_Phy_Prog_Seq_Data(XMipi_Tx_Phy *InstancePtr, XMipi_Tx_Phy_ProgSeq bitpos, u32 Value)
Program a symbol value into the programmable sequence table.
This helper masks in the 3-bit symbol value into the correct programmable sequence register (DATA0 or DATA1) based on the requested symbol index. The programmable sequence control is temporarily disabled to avoid partial writes. InstancePtr is the XMipi_Tx_Phy instance. bitpos is the programmable sequence symbol index. Value is the 3-bit symbol value to program. XST_SUCCESS if the symbol was programmed.XST_FAILURE if the control register remained enabled and the write was aborted. The core must be configured for C-PHY mode (IsDphy == 0) and register access must be enabled.
u32 XMipi_Tx_Phy_Get_Seq_Data(XMipi_Tx_Phy *InstancePtr, XMipi_Tx_Phy_ProgSeq bitpos)
Read a programmable sequence register.
InstancePtr is the XMipi_Tx_Phy instance. bitpos is the programmable sequence symbol index. Register contents of DATA0 (symbols 0-9) or DATA1 (symbols 10-13). The core must be configured for C-PHY mode (IsDphy == 0) and register access must be enabled.
u32 XMipi_Tx_Phy_En_Prog_Seq_Ctrl(XMipi_Tx_Phy *InstancePtr)
Enable programmable sequence control.
InstancePtr is the XMipi_Tx_Phy instance. XST_SUCCESS always. The core must be configured for C-PHY mode (IsDphy == 0) and register access must be enabled.
u32 XMipi_Tx_Phy_Dis_Prog_Seq_Ctrl(XMipi_Tx_Phy *InstancePtr)
Disable programmable sequence control.
InstancePtr is the XMipi_Tx_Phy instance. XST_SUCCESS always. The core must be configured for C-PHY mode (IsDphy == 0) and register access must be enabled.
u32 XMipi_Tx_Phy_Get_Prog_Seq_Ctrl(XMipi_Tx_Phy *InstancePtr)
Read the programmable sequence control register.
InstancePtr is the XMipi_Tx_Phy instance. Current contents of the programmable sequence control register. The core must be configured for C-PHY mode (IsDphy == 0) and register access must be enabled.
u32 XMipi_Tx_Phy_SelfTest(XMipi_Tx_Phy *InstancePtr)
Runs a self-test on the driver/device.
This test checks if HS Timeout value present in register matches the one from the generated file. InstancePtr is a pointer to the XMipi_Tx_Phy instance. XST_SUCCESS if self-test was successful XST_FAILURE if the read value was not equal to _g.c file None.
References XMipi_Tx_Phy::Config, XMipi_Tx_Phy_Config::HSTimeOut, XMipi_Tx_Phy_GetInfo, XMIPI_TX_PHY_HANDLE_HSTIMEOUT.
Referenced by Mipi_Tx_PhySelfTestExample.