xmipi_tx_phy.c
XMIPI_TX_PHY_SOFTRESET_TIMEOUT
Timeout value in loop iterations for soft reset completion.
Ensures at least 20 core clock cycles forreset to take effect.
u32 XMipi_Tx_Phy_CfgInitialize(XMipi_Tx_Phy *InstancePtr, XMipi_Tx_Phy_Config *CfgPtr, UINTPTR EffectiveAddr)
Initialize the XMipi_Tx_Phy instance provided by the caller based on the given Config structure.
InstancePtr is the XMipi_Tx_Phy instance to operate on. CfgPtr is the device configuration structure containing information about a specific Mipi_Tx_Phy instance. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS Initialization was successful. None.
References XMipi_Tx_Phy_Config::BaseAddr, XMipi_Tx_Phy::Config, XMipi_Tx_Phy::IsReady.
Referenced by Mipi_Tx_PhySelfTestExample.
u32 XMipi_Tx_Phy_Configure(XMipi_Tx_Phy *InstancePtr, u8 Handle, u32 Value)
Configure the registers of the Mipi_Tx_Phy instance.
InstancePtr is the XMipi_Tx_Phy instance to operate on. Handle to one of the registers to be configured Value to be set for the particular Handle of the Mipi_Tx_Phy instance XST_SUCCESS on successful register update.XST_FAILURE If incorrect handle was passed There is a limit on the minimum and maximum values of the HS Timeout register.
u32 XMipi_Tx_Phy_Prog_Seq_Data(XMipi_Tx_Phy *InstancePtr, XMipi_Tx_Phy_ProgSeq bitpos, u32 Value)
Program a symbol value into the programmable sequence table.
This helper masks in the 3-bit symbol value into the correct programmable sequence register (DATA0 or DATA1) based on the requested symbol index. The programmable sequence control is temporarily disabled to avoid partial writes. InstancePtr is the XMipi_Tx_Phy instance. bitpos is the programmable sequence symbol index. Value is the 3-bit symbol value to program. XST_SUCCESS if the symbol was programmed.XST_FAILURE if the control register remained enabled and the write was aborted. The core must be configured for C-PHY mode (IsDphy == 0) and register access must be enabled.
u32 XMipi_Tx_Phy_Get_Seq_Data(XMipi_Tx_Phy *InstancePtr, XMipi_Tx_Phy_ProgSeq bitpos)
Read a programmable sequence register.
InstancePtr is the XMipi_Tx_Phy instance. bitpos is the programmable sequence symbol index. Register contents of DATA0 (symbols 0-9) or DATA1 (symbols 10-13). The core must be configured for C-PHY mode (IsDphy == 0) and register access must be enabled.
u32 XMipi_Tx_Phy_En_Prog_Seq_Ctrl(XMipi_Tx_Phy *InstancePtr)
Enable programmable sequence control.
InstancePtr is the XMipi_Tx_Phy instance. XST_SUCCESS always. The core must be configured for C-PHY mode (IsDphy == 0) and register access must be enabled.
u32 XMipi_Tx_Phy_Dis_Prog_Seq_Ctrl(XMipi_Tx_Phy *InstancePtr)
Disable programmable sequence control.
InstancePtr is the XMipi_Tx_Phy instance. XST_SUCCESS always. The core must be configured for C-PHY mode (IsDphy == 0) and register access must be enabled.
u32 XMipi_Tx_Phy_Get_Prog_Seq_Ctrl(XMipi_Tx_Phy *InstancePtr)
Read the programmable sequence control register.
InstancePtr is the XMipi_Tx_Phy instance. Current contents of the programmable sequence control register. The core must be configured for C-PHY mode (IsDphy == 0) and register access must be enabled.
u8 XMipi_Tx_Phy_GetRegIntfcPresent(XMipi_Tx_Phy *InstancePtr)
Get if register interface is present from the config structure for specified Mipi_Tx_Phy instance.
InstancePtr is the XMipi_Tx_Phy instance to operate on. 1 if register interface is present0 if register interface is absent None.
Referenced by Mipi_Tx_PhySelfTestExample.
u32 XMipi_Tx_Phy_GetInfo(XMipi_Tx_Phy *InstancePtr, u8 Handle)
Get information stored in the Mipi_Tx_Phy instance based on the handle passed.
InstancePtr is the XMipi_Tx_Phy instance to operate on. Handle to one of the registers to be configured The value stored in the corresponding register None.
Referenced by XMipi_Tx_Phy_SelfTest.
void XMipi_Tx_Phy_Reset(XMipi_Tx_Phy *InstancePtr)
This is used to do a soft reset of the Mipi_Tx_Phy IP instance.
The reset takes approx 20 core clock cycles to become effective. InstancePtr is the XMipi_Tx_Phy instance to operate on. None.
void XMipi_Tx_Phy_ClearDataLane(XMipi_Tx_Phy *InstancePtr, u8 DataLane, u32 Mask)
This is used to clear the Abort Error (Escape or High Speed) bits in the Data Lane 0 through 3.
InstancePtr is the XMipi_Tx_Phy instance to operate on. DataLane represents which Data Lane to act upon Mask contains information about which bits to reset None.
u32 XMipi_Tx_Phy_GetClkLaneStatus(XMipi_Tx_Phy *InstancePtr)
This is used to get information about Clock Lane status.
InstancePtr is the XMipi_Tx_Phy instance to operate on. Bitmask containing which of the events have occurred along with the mode of the Clock Lane in DPhy None.
u32 XMipi_Tx_Phy_GetClkLaneMode(XMipi_Tx_Phy *InstancePtr)
This is used to get specific Lane mode information about Clock Lane.
InstancePtr is the XMipi_Tx_Phy instance to operate on. Bitmask containing mode in which the Clock Lane in Mipi_Tx_Phy is in. None.
u32 XMipi_Tx_Phy_GetDataLaneStatus(XMipi_Tx_Phy *InstancePtr, u8 DataLane)
This is used to get information about a Data Lane status.
InstancePtr is the XMipi_Tx_Phy instance to operate on. DataLane for which the status is sought for. Bitmask containing which of the events have occurred along with the mode of the Data Lane in DPhy None.
u8 XMipi_Tx_Phy_GetDLCalibStatus(XMipi_Tx_Phy *InstancePtr, u8 DataLane)
This is used to get Data Lane Calibration status.
InstancePtr is the XMipi_Tx_Phy instance to operate on. DataLane for which the calib status is sought for. XST_SUCCESS - Calibration Complete, Calibration packet received XST_NO_DATA - Calibration Complete, Calibration packet is not received XST_FAILURE - Calibration failed None.
u32 XMipi_Tx_Phy_GetDataLaneMode(XMipi_Tx_Phy *InstancePtr, u8 DataLane)
This is used to get specific Lane mode information about a Data Lane.
InstancePtr is the XMipi_Tx_Phy instance to operate on. DataLane for which the mode info is requested. Bitmask containing mode in which the Data Lane in Mipi_Tx_Phy is in. None.
u16 XMipi_Tx_Phy_GetPacketCount(XMipi_Tx_Phy *InstancePtr, u8 DataLane)
This is used to get count of packets received on each lane.
InstancePtr is the XMipi_Tx_Phy instance to operate on. DataLane for which the mode info is requested. Bitmask containing mode in which the Data Lane in Mipi_Tx_Phy is in. None.
u32 XMipi_Tx_Phy_GetVersionReg(XMipi_Tx_Phy *InstancePtr)
This is used to get Mipi_Tx_Phy Version.
InstancePtr is the XMipi_Tx_Phy instance to operate on. Returns major and minor Version number of this Mipi_Tx_Phy IP None.
void XMipi_Tx_Phy_Activate(XMipi_Tx_Phy *InstancePtr, u8 Flag)
This function is used to enable or disable the Mipi_Tx_Phy core.
InstancePtr is the XMipi_Tx_Phy instance to operate on. Flag denoting whether to enable or disable the Mipi_Tx_Phy core None.