xavbuf.h
XAVBuf_VideoFormat
XAVBuf_VideoModes
XAVBuf_VideoStream
XAVBuf_GfxStream
XAVBuf_AudioStream1
XAVBuf_AudioStream2
void XAVBuf_CfgInitialize(XAVBuf *InstancePtr, u32 BaseAddr)
This function initializes the configuration for the AVBuf Instance.
InstancePtr is a pointer to the XAVBuf instance. BaseAddr sets the base address of the AVBuf instance DeviceId is the id of the device from the design. None. Base address and DeviceId is same as the DP Core driver.
void XAVBuf_InputVideoSelect(XAVBuf *InstancePtr, XAVBuf_VideoStream VidStream, XAVBuf_GfxStream GfxStream)
This function selects the source for the Video and Graphics streams that are passed on to the blender block.
InstancePtr is a pointer to the XAVBuf instance. VidStream selects the stream coming from the video sources GfxStream selects the stream coming from the graphics sources None. None.
References XAVBUF_BUF_OUTPUT_AUD_VID_SELECT, XAVBuf_ReadReg, XAVBuf_WriteReg.
void XAVBuf_InputAudioSelect(XAVBuf *InstancePtr, XAVBuf_AudioStream1 AudStream, XAVBuf_AudioStream2 AudioStream2)
This function selects the source for audio streams corresponding to the Video and Graphics streams that are passed on to the blender.
InstancePtr is a pointer to the XAVBuf instance. AudStream1 selects the audio stream source corresponding to the video source selected AudStream2 selects the audio stream source corresponding to the graphics source selected. None. None.
References XAVBUF_BUF_OUTPUT_AUD_VID_SELECT, XAVBuf_ReadReg, XAVBuf_WriteReg.
int XAVBuf_SetInputNonLiveVideoFormat(XAVBuf *InstancePtr, XAVBuf_VideoFormat Format)
This function sets the video format for the non-live video.
InstancePtr is a pointer to the XAVBuf instance. Format is the enum for the non-live video format XST_SUCCESS if the correct format has been set. XST_FAILURE if the format is invalid. None.
References XAVBuf_GetNLiveVideoAttribute.
int XAVBuf_SetInputNonLiveGraphicsFormat(XAVBuf *InstancePtr, XAVBuf_VideoFormat Format)
This function sets the graphics format for the non-live video.
InstancePtr is a pointer to the XAVBuf instance. Format is the enum for the non-live video format XST_SUCCESS if the correct format has been set. XST_FAILURE if the format is invalid. None.
References XAVBuf_GetNLGraphicsAttribute.
int XAVBuf_SetInputLiveVideoFormat(XAVBuf *InstancePtr, XAVBuf_VideoFormat Format)
This function sets the video format for the live video.
InstancePtr is a pointer to the XAVBuf instance. Format is the enum for the non-live video format XST_SUCCESS if the correct format has been set. XST_FAILURE if the format is invalid. None.
References XAVBuf_GetLiveVideoAttribute.
int XAVBuf_SetInputLiveGraphicsFormat(XAVBuf *InstancePtr, XAVBuf_VideoFormat Format)
This function sets the graphics format for the live video.
InstancePtr is a pointer to the XAVBuf instance. Format is the enum for the non-live video format XST_SUCCESS if the correct format has been set. XST_FAILURE if the format is invalid. None.
References XAVBuf_GetLiveVideoAttribute.
int XAVBuf_SetOutputVideoFormat(XAVBuf *InstancePtr, XAVBuf_VideoFormat Format)
This function sets the Output Video Format.
InstancePtr is a pointer to the XAVBuf instance. Format is the enum for the non-live video format XST_SUCCESS if the correct format has been set. XST_FAILURE if the format is invalid. None.
References XAVBuf_GetLiveVideoAttribute.
XAVBuf_VideoAttribute* XAVBuf_GetLiveVideoAttribute(XAVBuf_VideoFormat Format)
This function looks up if the video format is valid or not for the non-live video datapath and returns a pointer to the attributes of the video.
Format takes in the video format for which attributes are being requested. A pointer to the structure XAVBuf_VideoAttribute if the video format is valid, else returns NULL. None.
Referenced by XAVBuf_SetInputLiveGraphicsFormat, XAVBuf_SetInputLiveVideoFormat, XAVBuf_SetOutputVideoFormat.
XAVBuf_VideoAttribute* XAVBuf_GetNLiveVideoAttribute(XAVBuf_VideoFormat Format)
This function looks up if the video format is valid or not and returns a pointer to the attributes of the video.
Format takes in the video format for which attributes are being requested. A pointer to the structure XAVBuf_VideoAttribute if the video format is valid, else returns NULL. None.
Referenced by XAVBuf_SetInputNonLiveVideoFormat.
XAVBuf_VideoAttribute* XAVBuf_GetNLGraphicsAttribute(XAVBuf_VideoFormat Format)
This function looks up if the video format is valid or not and returns a pointer to the attributes of the video.
Format takes in the video format for which attributes are being requested. A pointer to the structure XAVBuf_VideoAttribute if the video format is valid, else returns NULL. None.
Referenced by XAVBuf_SetInputNonLiveGraphicsFormat.
void XAVBuf_SetAudioVideoClkSrc(XAVBuf *InstancePtr, u8 VideoClk, u8 AudioClk)
This function sets the Audio and Video Clock Source and the video timing source.
InstancePtr is a pointer to the XAVBuf instance. VideoClk selects the Video Clock Source AudioClk selects the Audio Clock Source None. System uses PL Clock for Video when Live source is in use.
References XAVBUF_BUF_AUD_VID_CLK_SOURCE, XAVBuf_SoftReset, XAVBuf_WriteReg.
void XAVBuf_ConfigureVideoPipeline(XAVBuf *InstancePtr)
This function configures the Video Pipeline.
InstancePtr is an pointer to the XAVBuf Instance. None. None.
void XAVBuf_ConfigureGraphicsPipeline(XAVBuf *InstancePtr)
This function configures the Graphics Pipeline.
InstancePtr is an pointer to the XAVBuf Instance. None. None.
void XAVBuf_BlendSetBgColor(XAVBuf *InstancePtr, XAVBuf_BlenderBgClr *Color)
This function sets the blender background color.
InstancePtr is an pointer to the XAVBuf Instance. Color is a pointer to the structure XAVBuf_BlenderBgClr None. None.
References XAVBUF_V_BLEND_BG_CLR_0, XAVBUF_V_BLEND_BG_CLR_1, XAVBUF_V_BLEND_BG_CLR_2, XAVBuf_WriteReg.
void XAVBuf_SetBlenderAlpha(XAVBuf *InstancePtr, u8 Alpha, u8 Enable)
This function enables or disables global alpha.
InstancePtr is an pointer to the XAVBuf Instance. Enable sets a software flag for global alpha Alpha sets the value for the global alpha blending None. GlobalAlphaEn = 1, enables the global alpha. GlobalAlphaEn = 0, disables the global alpha. Alpha = 0, passes stream2 Alpha = 255, passes stream1
References XAVBUF_V_BLEND_SET_GLOBAL_ALPHA_REG, XAVBuf_WriteReg.
void XAVBuf_SoftReset(XAVBuf *InstancePtr)
This function applies a soft reset to the Audio Video pipeline.
InstancePtr is a pointer to the XAVBuf instance. None. None.
References XAVBUF_BUF_SRST_REG, XAVBuf_WriteReg.
Referenced by XAVBuf_SetAudioVideoClkSrc.
void XABuf_LineResetDisable(XAVBuf *InstancePtr, u8 Disable)
This function enables End of Line Reset for reduced blanking resolutions.
InstancePtr is a pointer to the XAVBuf Instance. Disable is to be set while using Reduced Blanking Resolutions. None. None.
References XAVBUF_AUD_SOFT_RST, XAVBuf_ReadReg, XAVBuf_WriteReg.
void XAVBuf_ConfigureOutputVideo(XAVBuf *InstancePtr)
This function configures the Output of the Video Pipeline.
InstancePtr is an pointer to the XAVBuf Instance. None. None.
References XAVBUF_V_BLEND_OUTPUT_VID_FORMAT, XAVBuf_WriteReg.
void XAVBuf_AudioSoftReset(XAVBuf *InstancePtr)
This function resets the Audio Pipe.
InstancePtr is a pointer to the XAVBuf Instance. None. Needed when non-live audio is disabled.
References XAVBUF_AUD_SOFT_RST, XAVBuf_ReadReg, XAVBuf_WriteReg.
void XAVBuf_AudioMixerVolumeControl(XAVBuf *InstancePtr, u8 Channel0Volume, u8 Channel1Volume)
This function sets up the scaling factor for Audio Mixer Volume Control.
InstancePtr is a pointer to the XAVBuf instance. Channel0Volume is the volume to be set for Audio from Channel0 Channel1Volume is the volume to be set for Audio from Channel1 None. None.
References XAVBUF_AUD_MIXER_VOLUME_CONTROL, XAVBuf_WriteReg.
void XAVBuf_EnableGraphicsBuffers(XAVBuf *InstancePtr, u8 Enable)
This function enables the graphics interface between the DPDMA and the AVBuf.
InstancePtr is a pointer to the XAVBuf Instance. Enable sets the corresponding buffers. None. None.
References XAVBUF_CHBUF3, XAVBuf_WriteReg.
void XAVBuf_EnableVideoBuffers(XAVBuf *InstancePtr, u8 Enable)
This function enables the video channel interface between the DPDMA and the AVBuf.
InstancePtr is a pointer to the XAVBuf Instance. Enable sets the corresponding buffers. None. None.
References XAVBUF_CHBUF0, XAVBuf_WriteReg.
void XAVBuf_EnableAudio0Buffers(XAVBuf *InstancePtr, u8 Enable)
This function enables the audio interface between the DPDMA and the AVBuf.
InstancePtr is a pointer to the XAVBuf Instance. Enable sets the corresponding buffers. None. None.
References XAVBUF_CHBUF4, XAVBuf_WriteReg.
void XAVBuf_EnableAudio1Buffers(XAVBuf *InstancePtr, u8 Enable)
This function enables the audio interface between the DPDMA and the AVBuf.
InstancePtr is a pointer to the XAVBuf Instance. Enable sets the corresponding buffers. None. None.
References XAVBUF_CHBUF5, XAVBuf_WriteReg.