sysmonpsv_api
XSYSMONPSV_BASEADDR
Sysmon Base Address.
XSYSMONPSV_PCSR_MASK
Sysmon PCSR Mask Reg Offset.
Referenced by XSysMonPsv_EnRegGate, XSysMonPsv_SystemReset.
XSYSMONPSV_PCSR_MASK_SYS_RST_MASK_SHIFT
PCSR Mask Reset Shift.
XSYSMONPSV_PCSR_MASK_SYS_RST_MASK_MASK
PCSR Mask Reset Mask Value.
Referenced by XSysMonPsv_SystemReset.
XSYSMONPSV_PCSR_MASK_GATEREG_SHIFT
PCSR Mask Gate Reg Shift.
XSYSMONPSV_PCSR_MASK_GATEREG_MASK
PCSR Mask Gate Reg Mask.
Referenced by XSysMonPsv_EnRegGate.
XSYSMONPSV_PCSR_CONTROL
PCSR Control Reg Offset.
Referenced by XSysMonPsv_EnRegGate, XSysMonPsv_SystemReset.
XSYSMONPSV_PCSR_CONTROL_SYS_RST_MASK_SHIFT
PCSR Control Reset Shift.
XSYSMONPSV_PCSR_CONTROL_SYS_RST_MASK_MASK
PCSR Control Reset Mask.
Referenced by XSysMonPsv_SystemReset.
XSYSMONPSV_PCSR_CONTROL_GATEREG_SHIFT
PCSR Control Gate Reg Shift.
Referenced by XSysMonPsv_EnRegGate.
XSYSMONPSV_PCSR_CONTROL_GATEREG_MASK
PCSR Control Gate Reg Mask.
XSYSMONPSV_PCSR_LOCK
PCSR Lock Register Offset.
Referenced by XSysMonPsv_InterruptDisable, XSysMonPsv_InterruptEnable, XSysMonPsv_UnlockRegspace, XSysMonPsv_WriteReg32.
XSYSMONPSV_PCSR_LOCK_STATE_SHIFT
PCSR Lock State Shift.
XSYSMONPSV_PCSR_LOCK_STATE_MASK
PCSR Lock State Mask.
XSYSMONPSV_ISR_OFFSET
Interrupt Status Register Offset.
Referenced by XSysMonPsv_InterruptClear, XSysMonPsv_InterruptGetStatus, XSysMonPsv_IntrClear, XSysMonPsv_IntrGetStatus.
XSYSMONPSV_ISR_NEW_DATA3_SHIFT
New Data 3 Shift.
XSYSMONPSV_ISR_NEW_DATA3_MASK
New Data 3 Mask.
XSYSMONPSV_ISR_NEW_DATA2_SHIFT
New Data 2 Shift.
XSYSMONPSV_ISR_NEW_DATA2_MASK
New Data 2 Mask.
XSYSMONPSV_ISR_NEW_DATA1_SHIFT
New Data 1 Shift.
XSYSMONPSV_ISR_NEW_DATA1_MASK
New Data 1 Mask.
XSYSMONPSV_ISR_NEW_DATA0_SHIFT
New Data 0 Shift.
XSYSMONPSV_ISR_NEW_DATA0_MASK
New Data 0 Mask.
XSYSMONPSV_ISR_TEMP_SHIFT
Device Temperature Alarm Shift.
XSYSMONPSV_ISR_TEMP_MASK
Device Temperature Alarm Mask.
XSYSMONPSV_ISR_OT_SHIFT
Device Temperature Alarm Shift.
XSYSMONPSV_ISR_OT_MASK
Device Temperature Alarm Mask.
XSYSMONPSV_ISR_ALARM4_SHIFT
Supply[128-159] Alarm Shift.
XSYSMONPSV_ISR_ALARM4_MASK
Supply[128-159] Alarm Mask.
XSYSMONPSV_ISR_ALARM3_SHIFT
Supply[96-127] Alarm Shift.
XSYSMONPSV_ISR_ALARM3_MASK
Supply[96-127] Alarm Mask.
XSYSMONPSV_ISR_ALARM2_SHIFT
Supply[64-95] Alarm Shift.
XSYSMONPSV_ISR_ALARM2_MASK
Supply[64-95] Alarm Mask.
XSYSMONPSV_ISR_ALARM1_SHIFT
Supply[32-63] Alarm Shift.
XSYSMONPSV_ISR_ALARM1_MASK
Supply[32-63] Alarm Mask.
XSYSMONPSV_ISR_ALARM0_SHIFT
Supply[0-31] Alarm Shift.
XSYSMONPSV_ISR_ALARM0_MASK
Supply[0-31] Alarm Mask.
XSYSMONPSV_IMR0_OFFSET
Interrupt Mask Reg 0 Offset.
Referenced by XSysMonPsv_IntrGetEnabled.
XSYSMONPSV_IMR0_NEW_DATA3_SHIFT
New Data 3 Shift.
XSYSMONPSV_IMR0_NEW_DATA3_MASK
New Data 3 Mask.
XSYSMONPSV_IMR0_NEW_DATA2_SHIFT
New Data 2 Shift.
XSYSMONPSV_IMR0_NEW_DATA2_MASK
New Data 2 Mask.
XSYSMONPSV_IMR0_NEW_DATA1_SHIFT
New Data 1 Shift.
XSYSMONPSV_IMR0_NEW_DATA1_MASK
New Data 1 Mask.
XSYSMONPSV_IMR0_NEW_DATA0_SHIFT
New Data 0 Shift.
XSYSMONPSV_IMR0_NEW_DATA0_MASK
New Data 0 Mask.
XSYSMONPSV_IMR0_TEMP_SHIFT
Device Temperature Alarm Shift.
XSYSMONPSV_IMR0_TEMP_MASK
Device Temperature Alarm Mask.
XSYSMONPSV_IMR0_OT_SHIFT
Device Temperature Alarm Shift.
XSYSMONPSV_IMR0_OT_MASK
Device Temperature Alarm Mask.
XSYSMONPSV_IMR0_ALARM4_SHIFT
Supply[128-159] Alarm Shift.
XSYSMONPSV_IMR0_ALARM4_MASK
Supply[128-159] Alarm Mask.
XSYSMONPSV_IMR0_ALARM3_SHIFT
Supply[96-127] Alarm Shift.
XSYSMONPSV_IMR0_ALARM3_MASK
Supply[96-127] Alarm Mask.
XSYSMONPSV_IMR0_ALARM2_SHIFT
Supply[64-95] Alarm Shift.
XSYSMONPSV_IMR0_ALARM2_MASK
Supply[64-95] Alarm Mask.
XSYSMONPSV_IMR0_ALARM1_SHIFT
Supply[32-63] Alarm Shift.
XSYSMONPSV_IMR0_ALARM1_MASK
Supply[32-63] Alarm Mask.
XSYSMONPSV_IMR0_ALARM0_SHIFT
Supply[0-31] Alarm Shift.
XSYSMONPSV_IMR0_ALARM0_MASK
Supply[0-31] Alarm Mask.
XSYSMONPSV_IER0_OFFSET
Interrupt Enable 0 Offset.
Referenced by XSysMonPsv_InterruptEnable, XSysMonPsv_IntrEnable.
XSYSMONPSV_IER0_NEW_DATA3_SHIFT
New Data 3 Shift.
XSYSMONPSV_IER0_NEW_DATA3_MASK
New Data 3 Mask.
XSYSMONPSV_IER0_NEW_DATA2_SHIFT
New Data 2 Shift.
XSYSMONPSV_IER0_NEW_DATA2_MASK
New Data 2 Mask.
XSYSMONPSV_IER0_NEW_DATA1_SHIFT
New Data 1 Shift.
XSYSMONPSV_IER0_NEW_DATA1_MASK
New Data 1 Mask.
XSYSMONPSV_IER0_NEW_DATA0_SHIFT
New Data 0 Shift.
XSYSMONPSV_IER0_NEW_DATA0_MASK
New Data 0 Mask.
XSYSMONPSV_IER0_TEMP_SHIFT
Device Temperature Alarm Shift.
XSYSMONPSV_IER0_TEMP_MASK
Device Temperature Alarm Mask.
XSYSMONPSV_IER0_OT_SHIFT
Device Temperature Alarm Shift.
XSYSMONPSV_IER0_OT_MASK
Device Temperature Alarm Mask.
XSYSMONPSV_IER0_ALARM4_SHIFT
Supply[128-159] Alarm Shift.
XSYSMONPSV_IER0_ALARM4_MASK
Supply[128-159] Alarm Mask.
XSYSMONPSV_IER0_ALARM3_SHIFT
Supply[96-127] Alarm Shift.
XSYSMONPSV_IER0_ALARM3_MASK
Supply[96-127] Alarm Mask.
XSYSMONPSV_IER0_ALARM2_SHIFT
Supply[64-95] Alarm Shift.
XSYSMONPSV_IER0_ALARM2_MASK
Supply[64-95] Alarm Mask.
XSYSMONPSV_IER0_ALARM1_SHIFT
Supply[32-63] Alarm Shift.
XSYSMONPSV_IER0_ALARM1_MASK
Supply[32-63] Alarm Mask.
XSYSMONPSV_IER0_ALARM0_SHIFT
Supply[0-31] Alarm Shift.
XSYSMONPSV_IER0_ALARM0_MASK
Supply[0-31] Alarm Mask.
XSYSMONPSV_IDR0_OFFSET
Interrupt Disable Reg 0 Offset.
Referenced by XSysMonPsv_InterruptDisable, XSysMonPsv_IntrDisable.
XSYSMONPSV_IDR0_NEW_DATA3_SHIFT
New Data 3 Shift.
XSYSMONPSV_IDR0_NEW_DATA3_MASK
New Data 3 Mask.
XSYSMONPSV_IDR0_NEW_DATA2_SHIFT
New Data 2 Shift.
XSYSMONPSV_IDR0_NEW_DATA2_MASK
New Data 2 Mask.
XSYSMONPSV_IDR0_NEW_DATA1_SHIFT
New Data 1 Shift.
XSYSMONPSV_IDR0_NEW_DATA1_MASK
New Data 1 Mask.
XSYSMONPSV_IDR0_NEW_DATA0_SHIFT
New Data 0 Shift.
XSYSMONPSV_IDR0_NEW_DATA0_MASK
New Data 0 Mask.
XSYSMONPSV_IDR0_TEMP_SHIFT
Device Temperature Alarm Shift.
XSYSMONPSV_IDR0_TEMP_MASK
Device Temperature Alarm Mask.
XSYSMONPSV_IDR0_OT_SHIFT
Device Temperature Alarm Shift.
XSYSMONPSV_IDR0_OT_MASK
Device Temperature Alarm Mask.
XSYSMONPSV_IDR0_ALARM4_SHIFT
Supply[128-159] Alarm Shift.
XSYSMONPSV_IDR0_ALARM4_MASK
Supply[128-159] Alarm Mask.
XSYSMONPSV_IDR0_ALARM3_SHIFT
Supply[96-127] Alarm Shift.
XSYSMONPSV_IDR0_ALARM3_MASK
Supply[96-127] Alarm Mask.
XSYSMONPSV_IDR0_ALARM2_SHIFT
Supply[64-95] Alarm Shift.
XSYSMONPSV_IDR0_ALARM2_MASK
Supply[64-95] Alarm Mask.
XSYSMONPSV_IDR0_ALARM1_SHIFT
Supply[32-63] Alarm Shift.
XSYSMONPSV_IDR0_ALARM1_MASK
Supply[32-63] Alarm Mask.
XSYSMONPSV_IDR0_ALARM0_SHIFT
Supply[0-31] Alarm Shift.
XSYSMONPSV_IDR0_ALARM0_MASK
Supply[0-31] Alarm Mask.
XSYSMONPSV_IMR1_OFFSET
Interrupt Mask Reg 1 Offset.
XSYSMONPSV_IMR1_NEW_DATA3_SHIFT
New Data 3 Shift.
XSYSMONPSV_IMR1_NEW_DATA3_MASK
New Data 3 Mask.
XSYSMONPSV_IMR1_NEW_DATA2_SHIFT
New Data 2 Shift.
XSYSMONPSV_IMR1_NEW_DATA2_MASK
New Data 2 Mask.
XSYSMONPSV_IMR1_NEW_DATA1_SHIFT
New Data 1 Shift.
XSYSMONPSV_IMR1_NEW_DATA1_MASK
New Data 1 Mask.
XSYSMONPSV_IMR1_NEW_DATA0_SHIFT
New Data 0 Shift.
XSYSMONPSV_IMR1_NEW_DATA0_MASK
New Data 0 Mask.
XSYSMONPSV_IMR1_TEMP_SHIFT
Device Temperature Alarm Shift.
XSYSMONPSV_IMR1_TEMP_MASK
Device Temperature Alarm Mask.
XSYSMONPSV_IMR1_OT_SHIFT
Device Temperature Alarm Shift.
XSYSMONPSV_IMR1_OT_MASK
Device Temperature Alarm Mask.
XSYSMONPSV_IMR1_ALARM4_SHIFT
Supply[128-159] Alarm Shift.
XSYSMONPSV_IMR1_ALARM4_MASK
Supply[128-159] Alarm Mask.
XSYSMONPSV_IMR1_ALARM3_SHIFT
Supply[96-127] Alarm Shift.
XSYSMONPSV_IMR1_ALARM3_MASK
Supply[96-127] Alarm Mask.
XSYSMONPSV_IMR1_ALARM2_SHIFT
Supply[64-95] Alarm Shift.
XSYSMONPSV_IMR1_ALARM2_MASK
Supply[64-95] Alarm Mask.
XSYSMONPSV_IMR1_ALARM1_SHIFT
Supply[32-63] Alarm Shift.
XSYSMONPSV_IMR1_ALARM1_MASK
Supply[32-63] Alarm Mask.
XSYSMONPSV_IMR1_ALARM0_SHIFT
Supply[0-31] Alarm Shift.
XSYSMONPSV_IMR1_ALARM0_MASK
Supply[0-31] Alarm Mask.
XSYSMONPSV_IER1_OFFSET
Interrupt Enable Reg 1 Offset.
XSYSMONPSV_IER1_NEW_DATA3_SHIFT
New Data 3 Shift.
XSYSMONPSV_IER1_NEW_DATA3_MASK
New Data 3 Mask.
XSYSMONPSV_IER1_NEW_DATA2_SHIFT
New Data 2 Shift.
XSYSMONPSV_IER1_NEW_DATA2_MASK
New Data 2 Mask.
XSYSMONPSV_IER1_NEW_DATA1_SHIFT
New Data 1 Shift.
XSYSMONPSV_IER1_NEW_DATA1_MASK
New Data 1 Mask.
XSYSMONPSV_IER1_NEW_DATA0_SHIFT
New Data 0 Shift.
XSYSMONPSV_IER1_NEW_DATA0_MASK
New Data 0 Mask.
XSYSMONPSV_IER1_TEMP_SHIFT
Device Temperature Alarm Shift.
XSYSMONPSV_IER1_TEMP_MASK
Device Temperature Alarm Mask.
XSYSMONPSV_IER1_OT_SHIFT
Device Temperature Alarm Shift.
XSYSMONPSV_IER1_OT_MASK
Device Temperature Alarm Mask.
XSYSMONPSV_IER1_ALARM4_SHIFT
Supply[128-159] Alarm Shift.
XSYSMONPSV_IER1_ALARM4_MASK
Supply[128-159] Alarm Mask.
XSYSMONPSV_IER1_ALARM3_SHIFT
Supply[96-127] Alarm Shift.
XSYSMONPSV_IER1_ALARM3_MASK
Supply[96-127] Alarm Mask.
XSYSMONPSV_IER1_ALARM2_SHIFT
Supply[64-95] Alarm Shift.
XSYSMONPSV_IER1_ALARM2_MASK
Supply[64-95] Alarm Mask.
XSYSMONPSV_IER1_ALARM1_SHIFT
Supply[32-63] Alarm Shift.
XSYSMONPSV_IER1_ALARM1_MASK
Supply[32-63] Alarm Mask.
XSYSMONPSV_IER1_ALARM0_SHIFT
Supply[0-31] Alarm Shift.
XSYSMONPSV_IER1_ALARM0_MASK
Supply[0-31] Alarm Mask.
XSYSMONPSV_IDR1_OFFSET
Interrupt Disable Reg 1 Offset.
XSYSMONPSV_IDR1_NEW_DATA3_SHIFT
New Data 3 Shift.
XSYSMONPSV_IDR1_NEW_DATA3_MASK
New Data 3 Mask.
XSYSMONPSV_IDR1_NEW_DATA2_SHIFT
New Data 2 Shift.
XSYSMONPSV_IDR1_NEW_DATA2_MASK
New Data 2 Mask.
XSYSMONPSV_IDR1_NEW_DATA1_SHIFT
New Data 1 Shift.
XSYSMONPSV_IDR1_NEW_DATA1_MASK
New Data 1 Mask.
XSYSMONPSV_IDR1_NEW_DATA0_SHIFT
New Data 0 Shift.
XSYSMONPSV_IDR1_NEW_DATA0_MASK
New Data 0 Mask.
XSYSMONPSV_IDR1_TEMP_SHIFT
Device Temperature Alarm Shift.
XSYSMONPSV_IDR1_TEMP_MASK
Device Temperature Alarm Mask.
XSYSMONPSV_IDR1_OT_SHIFT
Device Temperature Alarm Shift.
XSYSMONPSV_IDR1_OT_MASK
Device Temperature Alarm Mask.
XSYSMONPSV_IDR1_ALARM4_SHIFT
Supply[128-159] Alarm Shift.
XSYSMONPSV_IDR1_ALARM4_MASK
Supply[128-159] Alarm Mask.
XSYSMONPSV_IDR1_ALARM3_SHIFT
Supply[96-127] Alarm Shift.
XSYSMONPSV_IDR1_ALARM3_MASK
Supply[96-127] Alarm Mask.
XSYSMONPSV_IDR1_ALARM2_SHIFT
Supply[64-95] Alarm Shift.
XSYSMONPSV_IDR1_ALARM2_MASK
Supply[64-95] Alarm Mask.
XSYSMONPSV_IDR1_ALARM1_SHIFT
Supply[32-63] Alarm Shift.
XSYSMONPSV_IDR1_ALARM1_MASK
Supply[32-63] Alarm Mask.
XSYSMONPSV_IDR1_ALARM0_SHIFT
Supply[0-31] Alarm Shift.
XSYSMONPSV_IDR1_ALARM0_MASK
Supply[0-31] Alarm Mask.
XSYSMONPSV_CONFIG0
Config0 register.
Referenced by XSysMonPsv_GetSupplyAverageRate, XSysMonPsv_GetTempAverageRate, XSysMonPsv_PMBusEnable, XSysMonPsv_PMBusEnableCmd, XSysMonPsv_SelectExtInterface, XSysMonPsv_SetPMBusAddress, XSysMonPsv_SetSupplyAverageRate, XSysMonPsv_SetTempAverageRate.
XSYSMONPSV_CONFIG0_TEMP_AVERAGE_SHIFT
Temp Average Shift.
Referenced by XSysMonPsv_GetTempAverageRate, XSysMonPsv_SetTempAverageRate.
XSYSMONPSV_CONFIG0_TEMP_AVERAGE_MASK
Temp Average Mask.
Referenced by XSysMonPsv_GetTempAverageRate, XSysMonPsv_SetTempAverageRate.
XSYSMONPSV_CONFIG0_SUPPLY_AVERAGE_SHIFT
Supply Average Shift.
Referenced by XSysMonPsv_GetSupplyAverageRate, XSysMonPsv_SetSupplyAverageRate.
XSYSMONPSV_CONFIG0_SUPPLY_AVERAGE_MASK
Supply Average Mask.
Referenced by XSysMonPsv_GetSupplyAverageRate, XSysMonPsv_SetSupplyAverageRate.
XSYSMONPSV_AVERAGE_0_SAMPLES
No Averaging, Full sample rate.
Referenced by XSysMonPsv_GetSupplyAverageRate, XSysMonPsv_GetTempAverageRate, XSysMonPsv_SetSupplyAverageRate, XSysMonPsv_SetTempAverageRate.
XSYSMONPSV_AVERAGE_2_SAMPLES
Average 2 samples, Full sample rate/2.
Referenced by XSysMonPsv_GetSupplyAverageRate, XSysMonPsv_GetTempAverageRate, XSysMonPsv_SetSupplyAverageRate, XSysMonPsv_SetTempAverageRate.
XSYSMONPSV_AVERAGE_4_SAMPLES
Average 4 samples, Full sample rate/4.
Referenced by XSysMonPsv_GetSupplyAverageRate, XSysMonPsv_GetTempAverageRate, XSysMonPsv_SetSupplyAverageRate, XSysMonPsv_SetTempAverageRate.
XSYSMONPSV_AVERAGE_8_SAMPLES
Average 8 samples, Full sample rate/8.
Referenced by XSysMonPsv_GetSupplyAverageRate, XSysMonPsv_GetTempAverageRate, XSysMonPsv_SetSupplyAverageRate, XSysMonPsv_SetTempAverageRate.
XSYSMONPSV_AVERAGE_16_SAMPLES
Average 16 samples, Full sample rate/16.
Referenced by XSysMonPsv_GetSupplyAverageRate, XSysMonPsv_GetTempAverageRate, XSysMonPsv_SetSupplyAverageRate, XSysMonPsv_SetTempAverageRate.
XSYSMONPSV_CONFIG0_I2C_NOT_PMBUS_SHIFT
I2C Select Shift.
Referenced by XSysMonPsv_SelectExtInterface.
XSYSMONPSV_CONFIG0_I2C_NOT_PMBUS_MASK
I2C Select Mask.
Referenced by XSysMonPsv_SelectExtInterface.
XSYSMONPSV_CONFIG0_PMBUS_UNRESTRICTED_SHIFT
Unrestrict PMBus Shift.
Referenced by XSysMonPsv_PMBusEnableCmd.
XSYSMONPSV_CONFIG0_PMBUS_UNRESTRICTED_MASK
Unrestrict PMBus Mask.
Referenced by XSysMonPsv_PMBusEnableCmd.
XSYSMONPSV_CONFIG0_PMBUS_ENABLE_SHIFT
PMBus Enable Shift.
Referenced by XSysMonPsv_PMBusEnable.
XSYSMONPSV_CONFIG0_PMBUS_ENABLE_MASK
PMBus Enable Mask.
Referenced by XSysMonPsv_PMBusEnable.
XSYSMONPSV_CONFIG0_PMBUS_ADDRESS_SHIFT
PMBus Address Shift.
XSYSMONPSV_CONFIG0_PMBUS_ADDRESS_MASK
PMBus Address Mask.
Referenced by XSysMonPsv_SetPMBusAddress.
XSYSMONPSV_NEW_DATA_FLAG0
New Data Flag Supply[0-31] Offset.
Referenced by XSysMonPsv_IsNewData.
XSYSMONPSV_NEW_DATA_FLAG1
New Data Flag Supply[32-63] Offset.
XSYSMONPSV_NEW_DATA_FLAG2
New Data Flag Supply[64-95] Offset.
XSYSMONPSV_NEW_DATA_FLAG3
New Data Flag Supply[96-127] Offset.
XSYSMONPSV_NEW_DATA_FLAG4
Alarm Flag Supply[128-159] Offset.
XSYSMONPSV_ALARM_FLAG0
Alarm Flag Supply[0-31] Offset.
Referenced by XSysMonPsv_ClearAlarm, XSysMonPsv_IsAlarmCondition, XSysMonPsv_IsAlarmPresent.
XSYSMONPSV_ALARM_FLAG1
Alarm Flag Supply[32-63] Offset.
XSYSMONPSV_ALARM_FLAG2
Alarm Flag Supply[63-95] Offset.
XSYSMONPSV_ALARM_FLAG3
Alarm Flag Supply[96-127] Offset.
XSYSMONPSV_ALARM_FLAG4
Alarm Flag Supply[128-159] Offset.
XSYSMONPSV_DEVICE_TEMP_MAX
Max Device Temperature Offset (Only for SE1 Silicon)
Referenced by XSysMonPsv_ReadDeviceTemp, XSysMonPsv_TempOffset.
XSYSMONPSV_DEVICE_TEMP_MAX_MAX
Device Max Temperature Register Offset.
Referenced by XSysMonPsv_ReadDeviceTemp, XSysMonPsv_TempOffset.
XSYSMONPSV_DEVICE_TEMP
Device Temperature Offset.
Referenced by XSysMonPsv_ReadDeviceTemp.
XSYSMONPSV_DEVICE_TEMP_MIN
Min Device Temperature Offset (Only for SE1 Silicon)
Referenced by XSysMonPsv_ReadDeviceTemp.
XSYSMONPSV_DEVICE_TEMP_MIN_MIN
Device Min Temperature Register Offset.
Referenced by XSysMonPsv_ReadDeviceTemp, XSysMonPsv_TempOffset.
XSYSMONPSV_SUPPLY_MANTISSA_MASK
Supply Mantissa Mask.
Referenced by XSysMonPsv_SupplyRawToProcessed.
XSYSMONPSV_SUPPLY_FMT_MASK
Supply Format Mask.
Referenced by XSysMonPsv_SupplyProcessedToRaw, XSysMonPsv_SupplyRawToProcessed.
XSYSMONPSV_SUPPLY_FMT_SHIFT
Supply Format Shift.
Referenced by XSysMonPsv_SupplyProcessedToRaw, XSysMonPsv_SupplyRawToProcessed.
XSYSMONPSV_SUPPLY_MODE_MASK
Supply Mode Mask.
Referenced by XSysMonPsv_SupplyProcessedToRaw, XSysMonPsv_SupplyRawToProcessed.
XSYSMONPSV_SUPPLY_MODE_SHIFT
Supply Mode Shift.
Referenced by XSysMonPsv_SupplyProcessedToRaw, XSysMonPsv_SupplyRawToProcessed.
XSYSMONPSV_SUPPLY_MANTISSA_SIGN
Supply Mantissa Shift.
Referenced by XSysMonPsv_SupplyRawToProcessed.
XSYSMONPSV_SUPPLY
Supply Base Register Offset.
Referenced by XSysMonPsv_ReadSupplyValue, XSysMonPsv_SupplyOffset.
XSYSMONPSV_SUPPLY_MIN
Min Supply Base Register Offset.
Referenced by XSysMonPsv_ReadSupplyValue.
XSYSMONPSV_SUPPLY_MAX
Max Supply Base Register Offset.
Referenced by XSysMonPsv_ReadSupplyValue.
XSYSMONPSV_ALARM_REG0
Alarm Reg Supply[0-31] Offset.
Referenced by XSysMonPsv_DisableVoltageEvents, XSysMonPsv_EnableVoltageEvents, XSysMonPsv_ReadAlarmConfig, XSysMonPsv_SetAlarmConfig.
XSYSMONPSV_ALARM_REG1
Alarm Reg Supply[32-63] Offset.
XSYSMONPSV_ALARM_REG2
Alarm Reg Supply[64-95] Offset.
XSYSMONPSV_ALARM_REG3
Alarm Reg Supply[96-127] Offset.
XSYSMONPSV_ALARM_REG4
Alarm Reg Supply[128-159] Offset.
XSYSMONPSV_EN_AVG_REG0
Enable Average for Supply Reg Supply[0-31] Offset.
Referenced by XSysMonPsv_EnableSupplyAverage.
XSYSMONPSV_EN_AVG_REG1
Enable Average for Supply Reg Supply[32-63] Offset.
XSYSMONPSV_EN_AVG_REG2
Enable Average for Supply Reg Supply[64-95] Offset.
XSYSMONPSV_EN_AVG_REG3
Enable Average for Supply Reg Supply[96-127] Offset.
XSYSMONPSV_EN_AVG_REG4
Enable Average for Supply Reg Supply[127-159] Offset.
XSYSMONPSV_DEVICE_TEMP_TH
Device Temperature Threshold Falling.
Referenced by XSysMonPsv_GetTempThresholdLower, XSysMonPsv_GetTempThresholdUpper, XSysMonPsv_ReadDevTempThreshold, XSysMonPsv_SetDevTempThreshold, XSysMonPsv_SetTempThresholdLower, XSysMonPsv_SetTempThresholdUpper.
XSYSMONPSV_DEVICE_TEMP_TH_FALLING
Device Temperature Threshold Falling.
Referenced by XSysMonPsv_TempThreshOffset.
XSYSMONPSV_DEVICE_TEMP_TH_RISING
Device Temperature Threshold Rising.
Referenced by XSysMonPsv_TempThreshOffset.
XSYSMONPSV_OT_TEMP_TH
OT Temperature Threshold Base Offset.
Referenced by XSysMonPsv_GetTempThresholdLower, XSysMonPsv_GetTempThresholdUpper, XSysMonPsv_ReadOTTempThreshold, XSysMonPsv_SetOTTempThreshold, XSysMonPsv_SetTempThresholdLower, XSysMonPsv_SetTempThresholdUpper.
XSYSMONPSV_OT_TEMP_TH_FALLING
OT Temperature Threshold Falling.
Referenced by XSysMonPsv_TempThreshOffset.
XSYSMONPSV_OT_TEMP_TH_RISING
OT Temperature Threshold Rising.
Referenced by XSysMonPsv_TempThreshOffset.
XSYSMONPSV_SUPPLY_TH_LOWER
Supply Lower Threshold Offset.
Referenced by XSysMonPsv_ReadSupplyThreshold, XSysMonPsv_SetSupplyLowerThreshold, XSysMonPsv_SupplyThreshOffset.
XSYSMONPSV_SUPPLY_TH_LOWER_VAL_RO_SHIFT
Read-Only Format Shift.
XSYSMONPSV_SUPPLY_TH_LOWER_VAL_RO_MASK
Read-only Format Mask.
XSYSMONPSV_SUPPLY_TH_LOWER_VAL_SHIFT
Threhsold Value Shift.
XSYSMONPSV_SUPPLY_TH_LOWER_VAL_MASK
Threshold Value Mask.
XSYSMONPSV_SUPPLY_TH_UPPER
Supply Upper Threshold Offset.
Referenced by XSysMonPsv_ReadSupplyThreshold, XSysMonPsv_SetSupplyUpperThreshold, XSysMonPsv_SupplyThreshOffset.
XSYSMONPSV_SUPPLY_TH_UPPER_VAL_RO_SHIFT
Read-Only Format Shift.
XSYSMONPSV_SUPPLY_TH_UPPER_VAL_RO_MASK
Read-only Format Mask.
XSYSMONPSV_SUPPLY_TH_UPPER_VAL_SHIFT
Threhsold Value Shift.
XSYSMONPSV_SUPPLY_TH_UPPER_VAL_MASK
Threshold Value Mask.
XSYSMONPSV_NEW_DATA_INT_SRC
New Data Interrupt Supply Source.
Referenced by XSysMonPsv_SetNewDataIntSrc.
XSYSMONPSV_INTR_NEW_DATA_MASK
New Data Interrupt Mask.
Referenced by XSysMonPsv_SetNewDataIntSrc.
XSYSMONPSV_INTR_NEW_DATA_SHIFT
New Data Interrupt Shift.
Referenced by XSysMonPsv_SetNewDataIntSrc.
XSYSMONPSV_NEW_DATA_INT_SRC_ADDR_ID3_SHIFT
New Data Interrupt 3 Source shift.
XSYSMONPSV_NEW_DATA_INT_SRC_ADDR_ID3_MASK
New Data Interrupt 3 Source Mask.
XSYSMONPSV_NEW_DATA_INT_SRC_ADDR_ID2_SHIFT
New Data Interrupt 2 Source shift.
XSYSMONPSV_NEW_DATA_INT_SRC_ADDR_ID2_MASK
New Data Interrupt 2 Source Mask.
XSYSMONPSV_NEW_DATA_INT_SRC_ADDR_ID1_SHIFT
New Data Interrupt 1 Source shift.
Referenced by XSysMonPsv_SetNewDataIntSrc.
XSYSMONPSV_NEW_DATA_INT_SRC_ADDR_ID1_MASK
New Data Interrupt 1 Source Mask.
XSYSMONPSV_NEW_DATA_INT_SRC_ADDR_ID0_SHIFT
New Data Interrupt 0 Source shift.
XSYSMONPSV_NEW_DATA_INT_SRC_ADDR_ID0_MASK
New Data Interrupt 0 Source Mask.
XSYSMONPSV_ALARM_CONFIG
Alarm Mode Config Reg.
Referenced by XSysMonPsv_SetOTMode, XSysMonPsv_SetTempMode.
XSYSMONPSV_ALARM_CONFIG_DEV_ALARM_MODE_SHIFT
Device Temp Alarm Mode Shift.
Referenced by XSysMonPsv_SetTempMode.
XSYSMONPSV_ALARM_CONFIG_DEV_ALARM_MODE_MASK
Device Temp Alarm Mask Shift.
Referenced by XSysMonPsv_SetTempMode.
XSYSMONPSV_ALARM_CONFIG_OT_ALARM_MODE_SHIFT
OT Temp Alarm Mode Shift.
Referenced by XSysMonPsv_SetOTMode.
XSYSMONPSV_ALARM_CONFIG_OT_ALARM_MODE_MASK
OT Temp Alarm.
Referenced by XSysMonPsv_SetOTMode.
XSYSMONPSV_STATUS_RESET
Status Reset Offset.
Referenced by XSysMonPsv_StatusReset.
XSYSMONPSV_STATUS_RESET_SUPPLY_SHIFT
Supply Reset Shift.
Referenced by XSysMonPsv_StatusReset.
XSYSMONPSV_STATUS_RESET_SUPPLY_MASK
Supply Reset Mask.
XSYSMONPSV_STATUS_RESET_DEVICE_TEMP_SHIFT
Temperature Reset Mask.
XSYSMONPSV_STATUS_RESET_DEVICE_TEMP_MASK
Temperature Reset Mask.
XSYSMONPSV_EN_AVG_REG8
Enable Average for Temp Satellite Reg Satellite[1-32] Offset.
Referenced by XSysMonPsv_EnableTempAverage.
XSYSMONPSV_EN_AVG_REG9
Enable Average for Temp Satellite Reg Satellite[33-64] Offset.
XSYSMONPSV_TEMP_SAT
Internal Temp Reg.
Referenced by XSysMonPsv_ReadTempProcessedSat, XSysMonPsv_ReadTempRawSat.
XSysMonPsv_Config XSysMonPsv_ConfigTable[][]
Config Table for sysmon device.
int XSysMonPsv_Xilpm_Init(XSysMonPsv *Instanceptr, XScuGic *const GicInst, XIpiPsu *const IpiInst)
Initializes the XIL PM.
Instanceptr Pointer to the XSysMonPsv instance. GicInst Pointer to XScuGic. IpiInst Pointer to XIpiPsu. XST_SUCCESS if successful else XST_FAILURE or an error code or a reason code.
s64 XSysMonPsv_CfgInitialize(XSysMonPsv *InstancePtr, XSysMonPsv_Config *CfgPtr)
Initializes XSysMonPsv device/instance.
This function must be called prior to using the System Monitor device. InstancePtr Pointer to the XSysMonPsv instance. CfgPtr Points to the XSysMonPsv device configuration structure. XST_SUCCESS if successful. The user needs to first call the XSysMonPsv_LookupConfig() API which returns the Configuration structure pointer which is passed as a parameter to the XSysMonPsv_CfgInitialize() API.
References XSysMonPsv_Config::BaseAddress, XSysMonPsv::Config, XSysMonPsv::IsReady, XSysMonPsv_Config::Supply_List, XSYSMONPSV_MAX_SUPPLIES.
void XSysMonPsv_SystemReset(XSysMonPsv *InstancePtr)
Resets the SystemMonitor.
InstancePtr Pointer to the XSysMonPsv instance. None.
References XSYSMONPSV_PCSR_CONTROL, XSYSMONPSV_PCSR_CONTROL_SYS_RST_MASK_MASK, XSYSMONPSV_PCSR_MASK, XSYSMONPSV_PCSR_MASK_SYS_RST_MASK_MASK, XSysMonPsv_WriteReg32.
void XSysMonPsv_EnRegGate(XSysMonPsv *InstancePtr, u8 Enable)
Gates the register outputs.
InstancePtr Pointer to the XSysMonPsv instance. Enable Flag to enable or disable gate registers. None.
References XSYSMONPSV_PCSR_CONTROL, XSYSMONPSV_PCSR_CONTROL_GATEREG_SHIFT, XSYSMONPSV_PCSR_MASK, XSYSMONPSV_PCSR_MASK_GATEREG_MASK, XSysMonPsv_WriteReg32.
void XSysMonPsv_SetPMBusAddress(XSysMonPsv *InstancePtr, u8 Address)
Sets the PMBus address for the System Monitor.
InstancePtr Pointer to the device instance. Address Value at which the Sysmon will be addressed on the PMBus. None.
References XSYSMONPSV_CONFIG0, XSYSMONPSV_CONFIG0_PMBUS_ADDRESS_MASK, XSysMonPsv_ReadReg32, XSysMonPsv_WriteReg32.
void XSysMonPsv_PMBusEnable(XSysMonPsv *InstancePtr, u8 Enable)
Enables/disbles the PMBus on the System Monitor.
InstancePtr Pointer to the driver instance. Enable Value which enables or disables the PMBus. None. If Enable = 0, PMBus lines will be in tristate. If Enable = 1, PMBus lines will be active.
References XSYSMONPSV_CONFIG0, XSYSMONPSV_CONFIG0_PMBUS_ENABLE_MASK, XSYSMONPSV_CONFIG0_PMBUS_ENABLE_SHIFT, XSysMonPsv_ReadReg32, XSysMonPsv_WriteReg32.
void XSysMonPsv_PMBusEnableCmd(XSysMonPsv *InstancePtr, u8 Enable)
Restricts or de-restrict all PMBs commands.
InstancePtr Pointer to the driver instance. Enable Value which restrics or de-restrict the PMBus commands. None. If Enable = 0, PMBus commands are disabled. If Enable = 1, PMBus commands are enabled.
References XSYSMONPSV_CONFIG0, XSYSMONPSV_CONFIG0_PMBUS_UNRESTRICTED_MASK, XSYSMONPSV_CONFIG0_PMBUS_UNRESTRICTED_SHIFT, XSysMonPsv_ReadReg32, XSysMonPsv_WriteReg32.
void XSysMonPsv_SelectExtInterface(XSysMonPsv *InstancePtr, u8 Interface)
Selects I2C or PMBus interface to which traffic from SMBus is routed.
InstancePtr Pointer to the driver instance. Interface Value which determies where the SMBus traffic gets routed to. None. If Interface = 1, I2C command interface is enabled. If Interface = 0, PMBus command interface is enabled.
References XSYSMONPSV_CONFIG0, XSYSMONPSV_CONFIG0_I2C_NOT_PMBUS_MASK, XSYSMONPSV_CONFIG0_I2C_NOT_PMBUS_SHIFT, XSysMonPsv_ReadReg32, XSysMonPsv_WriteReg32.
void XSysMonPsv_StatusReset(XSysMonPsv *InstancePtr, u8 ResetSupply, u8 ResetTemperature)
Resets the Min and Max values of supplies and temperature to negative and positive saturation respectively.
InstancePtr Pointer to the driver instance. ResetSupply Resets the MIN and MAX values reached by the internal supplies since the last reset. ResetTemperature Resets the MIN and MAX values reached by the device since the last reset. None.
References XSYSMONPSV_STATUS_RESET, XSYSMONPSV_STATUS_RESET_SUPPLY_SHIFT, XSysMonPsv_WriteReg32.
u16 XSysMonPsv_ReadDevTempThreshold(XSysMonPsv *InstancePtr, XSysMonPsv_Threshold ThresholdType)
Returns the device temperature threshold for min and max values in signed Q8.7 format.
InstancePtr Pointer to the driver instance. ThresholdType Enum which indicates the type of threshold. Device Temperature threshold in signed Q8.7 format. To get the value in Deg Celsius, use XSysMonPsv_FixedToFloat.
References XSYSMONPSV_DEVICE_TEMP_TH, XSysMonPsv_ReadReg32.
void XSysMonPsv_SetDevTempThreshold(XSysMonPsv *InstancePtr, XSysMonPsv_Threshold ThresholdType, u16 Value)
Sets Device Temperature Threshold values.
InstancePtr Pointer to the driver instance. ThresholdType Enum which indicates the type of threshold. Value Raw ADC threshold value. None. Use XSysMonPsv_FloatToFixed to get the raw ADC value.
References XSYSMONPSV_DEVICE_TEMP_TH, XSysMonPsv_WriteReg32.
u16 XSysMonPsv_ReadOTTempThreshold(XSysMonPsv *InstancePtr, XSysMonPsv_Threshold ThresholdType)
Returns the OT temperature threshold for min and max values in signed Q8.7 format.
InstancePtr Pointer to the driver instance. ThresholdType Enum which indicates the type of threshold OT Temperature threshold in signed Q8.7 format.
References XSYSMONPSV_OT_TEMP_TH, XSysMonPsv_ReadReg32.
void XSysMonPsv_SetOTTempThreshold(XSysMonPsv *InstancePtr, XSysMonPsv_Threshold ThresholdType, u16 Value)
Sets OT Temperature Threshold values.
InstancePtr Pointer to the driver instance. ThresholdType Enum which indicates the type of threshold. Value Raw ADC threshold value. None. Use XSysMonPsv_FloatToFixed to get the raw ADC value.
References XSYSMONPSV_OT_TEMP_TH, XSysMonPsv_WriteReg32.
u32 XSysMonPsv_ReadDeviceTemp(XSysMonPsv *InstancePtr, XSysMonPsv_Val Value)
Returns the temperature values for the device in signed Q8.7 format.
InstancePtr Pointer to the driver instance. Value Enum which indicates the type of temperature value to be read. Temperature value requested. XSYSMONPSV_INVALID if invalid value requested. XSYSMONPSV_VAL_VREF_MIN and XSYSMONPSV_VAL_VREF_MAX are only supported for ES1 silicon to get min and max temperature values. XSYSMONPSV_VAL_VREF_MIN and XSYSMONPSV_VAL_VREF_MAX are not supported on production silicon. Use XSYSMONPSV_VAL to get the current temperature value on production silicon. XSYSMONPSV_VAL is not supported on ES1 silicon.
References XSYSMONPSV_DEVICE_TEMP, XSYSMONPSV_DEVICE_TEMP_MAX, XSYSMONPSV_DEVICE_TEMP_MAX_MAX, XSYSMONPSV_DEVICE_TEMP_MIN, XSYSMONPSV_DEVICE_TEMP_MIN_MIN, XSYSMONPSV_INVALID, XSysMonPsv_ReadReg32, XSYSMONPSV_VAL, XSYSMONPSV_VAL_MAX, XSYSMONPSV_VAL_MIN, XSYSMONPSV_VAL_VREF_MAX, XSYSMONPSV_VAL_VREF_MIN.
u32 XSysMonPsv_ReadSupplyThreshold(XSysMonPsv *InstancePtr, XSysMonPsv_Supply Supply, XSysMonPsv_Threshold ThresholdType)
Reads the raw value for Supply Threshold.
InstancePtr Pointer to the driver instance. Supply Enum which indicates the desired supply to be read. ThresholdType Enum which indicates the type of threshold. The raw Upper or Lower threshold of the supply XSYSMONPSV_INVALID if the supply hasn't been configured.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_INVALID, XSYSMONPSV_INVALID_SUPPLY, XSysMonPsv_ReadReg32, XSYSMONPSV_SUPPLY_TH_LOWER, XSYSMONPSV_SUPPLY_TH_UPPER, XSYSMONPSV_TH_LOWER.
u32 XSysMonPsv_ReadSupplyValue(XSysMonPsv *InstancePtr, XSysMonPsv_Supply Supply, XSysMonPsv_Val Value)
Reads the raw supply value for requested.
InstancePtr Pointer to the driver instance. Supply Enum which indicates the desired supply to be read. Value Type of reading for the supply. The raw values for min, max or the prevailing supply value. Invalid if the supply is not configured.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_INVALID, XSYSMONPSV_INVALID_SUPPLY, XSysMonPsv_ReadReg32, XSYSMONPSV_SUPPLY, XSYSMONPSV_SUPPLY_MAX, XSYSMONPSV_SUPPLY_MIN, XSYSMONPSV_VAL, XSYSMONPSV_VAL_MIN.
u32 XSysMonPsv_IsNewData(XSysMonPsv *InstancePtr, XSysMonPsv_Supply Supply)
Checks if new data is available for a supply.
InstancePtr Pointer to the driver instance. Supply Enum which indicates the desired supply. True if new data available. False if new data is not available. Invalid if the supply is not configured. None.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_INVALID, XSYSMONPSV_INVALID_SUPPLY, XSYSMONPSV_NEW_DATA_FLAG0, XSysMonPsv_ReadReg32, XSysMonPsv_WriteReg32.
u32 XSysMonPsv_IsAlarmCondition(XSysMonPsv *InstancePtr, XSysMonPsv_Supply Supply)
Checks if the supply value has exceeded the set threshold values.
InstancePtr Pointer to the driver instance. Supply Enum which indicates the desired supply. True if new data available. False if new data is not available. Invalid if the supply is not configured.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_ALARM_FLAG0, XSYSMONPSV_INVALID, XSYSMONPSV_INVALID_SUPPLY, XSysMonPsv_ReadReg32, XSysMonPsv_WriteReg32.
u32 XSysMonPsv_SetSupplyUpperThreshold(XSysMonPsv *InstancePtr, XSysMonPsv_Supply Supply, u32 Value)
Sets the raw value for upper supply threshold.
InstancePtr Pointer to the driver instance. Supply Enum which indicates the desired supply to be configured Value Upper threshold raw value XSYSMONPSV_INVALID if the Supply hasn't been configured XST_SUCCESS otherwise.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_INVALID, XSYSMONPSV_INVALID_SUPPLY, XSYSMONPSV_SUPPLY_TH_UPPER, XSysMonPsv_WriteReg32.
u32 XSysMonPsv_SetSupplyLowerThreshold(XSysMonPsv *InstancePtr, XSysMonPsv_Supply Supply, u32 Value)
Sets the raw value for Lower Supply Threshold.
InstancePtr Pointer to the driver instance. Supply Enum which indicates the desired supply to be configured. Value Lower threshold raw value. XSYSMONPSV_INVALID if the Supply hasn't been configured XST_SUCCESS otherwise.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_INVALID, XSYSMONPSV_INVALID_SUPPLY, XSYSMONPSV_SUPPLY_TH_LOWER, XSysMonPsv_WriteReg32.
void XSysMonPsv_SetTempMode(XSysMonPsv *InstancePtr, u32 Mode)
Sets the alarm mode for temperature alarms.
InstancePtr Pointer to the driver instance. Mode Sets the Hysteresis or window mode. Mode = 1 Hysteresis Mode Mode = 0 Window Mode None.
References XSYSMONPSV_ALARM_CONFIG, XSYSMONPSV_ALARM_CONFIG_DEV_ALARM_MODE_MASK, XSYSMONPSV_ALARM_CONFIG_DEV_ALARM_MODE_SHIFT, XSysMonPsv_ReadReg32, XSysMonPsv_WriteReg32.
Referenced by SysMonPsvIntrExample.
void XSysMonPsv_SetOTMode(XSysMonPsv *InstancePtr, u32 Mode)
Sets the alarm mode for OT alarm.
InstancePtr Pointer to the driver instance. Mode Sets the Hysteresis or Window mode. Mode = XSYSMONPSV_HYSTERESIS Hysteresis Mode Mode = XSYSMONPSV_WINDOW Window Mode None.
References XSYSMONPSV_ALARM_CONFIG, XSYSMONPSV_ALARM_CONFIG_OT_ALARM_MODE_MASK, XSYSMONPSV_ALARM_CONFIG_OT_ALARM_MODE_SHIFT, XSysMonPsv_ReadReg32, XSysMonPsv_WriteReg32.
u32 XSysMonPsv_ReadAlarmConfig(XSysMonPsv *InstancePtr, XSysMonPsv_Supply Supply)
Reads the current supply Alarm Configuration.
InstancePtr Pointer to the driver instance. Supply Supply for which configuration is to be read. TRUE if enabled. FALSE if disabled. XSYSMONPSV_INVALID if invalid SupplyValue.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_ALARM_REG0, XSYSMONPSV_INVALID, XSYSMONPSV_INVALID_SUPPLY, XSysMonPsv_ReadReg32.
u32 XSysMonPsv_SetAlarmConfig(XSysMonPsv *InstancePtr, XSysMonPsv_Supply Supply, u32 Config)
Sets the Alarm configuration for a supply.
InstancePtr Pointer to the driver instance. Supply Supply for which config is to be set. Config Alarm config value. XSYSMONPSV_ENABLE to enable XSYSMONPSV_DISABLE to disable XST_SUCCESS if successful. XSYSMONPSV_INVALID if invalid SupplyValue.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_ALARM_REG0, XSYSMONPSV_INVALID, XSYSMONPSV_INVALID_SUPPLY, XSysMonPsv_ReadReg32, XSysMonPsv_WriteReg32.
int XSysMonPsv_ReadTempProcessed(XSysMonPsv *InstancePtr, XSysMonPsv_TempType Type, float *Val)
Reads the temperature and returns value in degree celsius.
InstancePtr Pointer to the driver instance. Type Minimum and maximum temperature type. Val Processed value in degree celsius. XST_FAILURE if error.XST_SUCCESS if successful.
References XSysMonPsv_Q8P7ToCelsius, XSysMonPsv_ReadReg32, XSysMonPsv_TempOffset.
Referenced by SysMonPsvIntrExample, SysMonPsvPolledExample.
int XSysMonPsv_ReadTempRaw(XSysMonPsv *InstancePtr, XSysMonPsv_TempType Type, u32 *Val)
Reads the temperature and returns value in raw format.
InstancePtr Pointer to the driver instance. Type Minimum and maximum temperature type. Val Value in raw format. XST_FAILURE if error.XST_SUCCESS if successful.
References XSysMonPsv_ReadReg32, XSysMonPsv_TempOffset.
Referenced by SysMonPsvIntrExample.
int XSysMonPsv_ReadTempProcessedSat(XSysMonPsv *InstancePtr, int SatId, float *Val)
Reads the temperature of each satellite in degree celsius.
InstancePtr Pointer to the driver instance. SatId Satellite ID. Val Processed value. XST_FAILURE if error.XST_SUCCESS if successful.
References XSysMonPsv_Q8P7ToCelsius, XSysMonPsv_ReadReg32, XSYSMONPSV_TEMP_SAT.
int XSysMonPsv_ReadTempRawSat(XSysMonPsv *InstancePtr, int SatId, u32 *Val)
Reads the temperature of each satellite in raw format.
InstancePtr Pointer to the driver instance. SatId Satellite ID. Val Raw value. XST_FAILURE if error.XST_SUCCESS if successful.
References XSysMonPsv_ReadReg32, XSYSMONPSV_TEMP_SAT.
int XSysMonPsv_SetTempThresholdUpper(XSysMonPsv *InstancePtr, XSysMonPsv_TempEvt Event, u32 Val)
Sets the temperature upper threshold.
InstancePtr Pointer to the driver instance. Event Temp or OT event type Val Threshold value to be set. XST_FAILURE if error.XST_SUCCESS if successful.
References XSYSMONPSV_DEVICE_TEMP_TH, XSYSMONPSV_OT_EVENT, XSYSMONPSV_OT_TEMP_TH, XSYSMONPSV_TEMP_EVENT, XSysMonPsv_WriteReg32.
Referenced by SysMonPsvIntrExample.
int XSysMonPsv_SetTempThresholdLower(XSysMonPsv *InstancePtr, XSysMonPsv_TempEvt Event, u32 Val)
Sets the temperature lower threshold.
InstancePtr Pointer to the driver instance. Event Temp or OT event type. Val Threshold value to be set. XST_FAILURE if error.XST_SUCCESS if successful.
References XSYSMONPSV_DEVICE_TEMP_TH, XSYSMONPSV_OT_EVENT, XSYSMONPSV_OT_TEMP_TH, XSYSMONPSV_TEMP_EVENT, XSysMonPsv_WriteReg32.
Referenced by SysMonPsvIntrExample.
int XSysMonPsv_GetTempThresholdUpper(XSysMonPsv *InstancePtr, XSysMonPsv_TempEvt Event, u32 *Val)
Gets the temperature upper threshold.
InstancePtr Pointer to the driver instance. Event Temp or OT event type. Val Upper threshold value to be read. XST_FAILURE if errorXST_SUCCESS if successful.
References XSYSMONPSV_DEVICE_TEMP_TH, XSYSMONPSV_OT_EVENT, XSYSMONPSV_OT_TEMP_TH, XSysMonPsv_ReadReg32, XSYSMONPSV_TEMP_EVENT.
Referenced by SysMonPsvIntrExample.
int XSysMonPsv_GetTempThresholdLower(XSysMonPsv *InstancePtr, XSysMonPsv_TempEvt Event, u32 *Val)
Gets the temperature lower threshold.
InstancePtr Pointer to the driver instance. Event Temp or OT event type. Val lower threshold value to be read. XST_FAILURE if errorXST_SUCCESS if successful.
References XSYSMONPSV_DEVICE_TEMP_TH, XSYSMONPSV_OT_EVENT, XSYSMONPSV_OT_TEMP_TH, XSysMonPsv_ReadReg32, XSYSMONPSV_TEMP_EVENT.
Referenced by SysMonPsvIntrExample.
int XSysMonPsv_ReadSupplyProcessed(XSysMonPsv *InstancePtr, int Supply, float *Val)
Reads the voltage for the supply.
InstancePtr Pointer to the driver instance. Supply Voltage supply. Val Float value in Voltage. XST_FAILURE if errorXST_SUCCESS if successful.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_INVALID_SUPPLY, XSYSMONPSV_MAX_SUPPLIES, XSysMonPsv_ReadReg32, XSysMonPsv_SupplyOffset, XSysMonPsv_SupplyRawToProcessed.
Referenced by SysMonPsvIntrExample, SysMonPsvPolledExample.
int XSysMonPsv_ReadSupplyRaw(XSysMonPsv *InstancePtr, u32 Supply, u32 *Val)
Reads the voltage for the supply in raw.
InstancePtr Pointer to the driver instance. Supply Voltage supply. Val Raw voltage. XST_FAILURE if errorXST_SUCCESS if successful.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_INVALID_SUPPLY, XSYSMONPSV_MAX_SUPPLIES, XSysMonPsv_ReadReg32, XSysMonPsv_SupplyOffset.
Referenced by SysMonPsvIntrExample.
int XSysMonPsv_SetSupplyThresholdUpper(XSysMonPsv *InstancePtr, u32 Supply, u32 Val)
Sets the upper threshold voltage for the supply.
InstancePtr Pointer to the driver instance. Supply Voltage supply. Val Upper Threshold Value. XST_FAILURE if errorXST_SUCCESS if successful.
References XSYSMONPSV_EV_DIR_RISING, XSysMonPsv_SupplyThreshOffset, XSysMonPsv_WriteReg32.
Referenced by SysMonPsvIntrExample.
int XSysMonPsv_SetSupplyThresholdLower(XSysMonPsv *InstancePtr, int Supply, u32 Val)
Sets loser threshold voltage for the supply.
InstancePtr Pointer to the driver instance. Supply Voltage supply. Val Threshold Value. XST_FAILURE if errorXST_SUCCESS if successful.
References XSYSMONPSV_EV_DIR_FALLING, XSysMonPsv_SupplyThreshOffset, XSysMonPsv_WriteReg32.
Referenced by SysMonPsvIntrExample.
int XSysMonPsv_GetSupplyThresholdUpper(XSysMonPsv *InstancePtr, u32 Supply, u32 *Val)
Gets the upper threshold voltage for the supply.
InstancePtr Pointer to the driver instance. Supply Voltage supply. Val Threshold Value to be read. XST_FAILURE if errorXST_SUCCESS if successful.
References XSYSMONPSV_EV_DIR_RISING, XSYSMONPSV_MAX_SUPPLIES, XSysMonPsv_ReadReg32, XSysMonPsv_SupplyThreshOffset.
Referenced by SysMonPsvIntrExample.
int XSysMonPsv_GetSupplyThresholdLower(XSysMonPsv *InstancePtr, u32 Supply, u32 *Val)
Gets the lower threshold voltage for the supply.
InstancePtr Pointer to the driver instance. Supply Voltage supply. Val Threshold Value to be read. XST_FAILURE if error.XST_SUCCESS if successful.
References XSYSMONPSV_EV_DIR_FALLING, XSYSMONPSV_MAX_SUPPLIES, XSysMonPsv_ReadReg32, XSysMonPsv_SupplyThreshOffset.
Referenced by SysMonPsvIntrExample.
void XSysMonPsv_EnableTempAverage(XSysMonPsv *InstancePtr, int SatId, u8 Enable)
Enables or Disables temperature satellites averaging.
InstancePtr Pointer to the driver instance. SatId Temperature Satellite id, indexed from 1 to 64. Enable Enable/Disable flag. None
References XSYSMONPSV_EN_AVG_REG8, XSysMonPsv_UpdateReg32.
void XSysMonPsv_SetTempAverageRate(XSysMonPsv *InstancePtr, u8 AverageRate)
Sets temperature satellites average sampling rate value.
InstancePtr Pointer to the driver instance. AverageRate Average Sampling Rate Value to be set. None
References XSYSMONPSV_AVERAGE_0_SAMPLES, XSYSMONPSV_AVERAGE_16_SAMPLES, XSYSMONPSV_AVERAGE_2_SAMPLES, XSYSMONPSV_AVERAGE_4_SAMPLES, XSYSMONPSV_AVERAGE_8_SAMPLES, XSYSMONPSV_CONFIG0, XSYSMONPSV_CONFIG0_TEMP_AVERAGE_MASK, XSYSMONPSV_CONFIG0_TEMP_AVERAGE_SHIFT, XSysMonPsv_UpdateReg32.
int XSysMonPsv_GetTempAverageRate(XSysMonPsv *InstancePtr, u8 *AverageRate)
Gets temperature satellites average sampling rate value.
InstancePtr Pointer to the driver instance. AverageRate Average Sampling Rate Value to be read. XSYSMONPSV_INVALID if invalid value read.XST_SUCCESS if successful.
References XSYSMONPSV_AVERAGE_0_SAMPLES, XSYSMONPSV_AVERAGE_16_SAMPLES, XSYSMONPSV_AVERAGE_2_SAMPLES, XSYSMONPSV_AVERAGE_4_SAMPLES, XSYSMONPSV_AVERAGE_8_SAMPLES, XSYSMONPSV_CONFIG0, XSYSMONPSV_CONFIG0_TEMP_AVERAGE_MASK, XSYSMONPSV_CONFIG0_TEMP_AVERAGE_SHIFT, XSYSMONPSV_INVALID, XSysMonPsv_ReadReg32.
int XSysMonPsv_EnableSupplyAverage(XSysMonPsv *InstancePtr, XSysMonPsv_Supply Supply, u8 Enable)
Enables or Disables voltage supplies averaging.
InstancePtr Pointer to the driver instance. Supply Voltage supply. Enable Enable/Disable flag. XSYSMONPSV_INVALID if invalid supply given.XST_SUCCESS if successful.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_EN_AVG_REG0, XSYSMONPSV_INVALID, XSYSMONPSV_INVALID_SUPPLY, XSysMonPsv_UpdateReg32.
void XSysMonPsv_SetSupplyAverageRate(XSysMonPsv *InstancePtr, u8 AverageRate)
Sets voltage supplies average sampling rate value.
InstancePtr Pointer to the driver instance. AverageRate Average Sampling Rate Value to be set. None
References XSYSMONPSV_AVERAGE_0_SAMPLES, XSYSMONPSV_AVERAGE_16_SAMPLES, XSYSMONPSV_AVERAGE_2_SAMPLES, XSYSMONPSV_AVERAGE_4_SAMPLES, XSYSMONPSV_AVERAGE_8_SAMPLES, XSYSMONPSV_CONFIG0, XSYSMONPSV_CONFIG0_SUPPLY_AVERAGE_MASK, XSYSMONPSV_CONFIG0_SUPPLY_AVERAGE_SHIFT, XSysMonPsv_UpdateReg32.
int XSysMonPsv_GetSupplyAverageRate(XSysMonPsv *InstancePtr, u8 *AverageRate)
Gets voltage supplies average sampling rate value.
InstancePtr Pointer to the driver instance. AverageRate Average Sampling Rate Value to be read. XSYSMONPSV_INVALID if invalid value read.XST_SUCCESS if successful.
References XSYSMONPSV_AVERAGE_0_SAMPLES, XSYSMONPSV_AVERAGE_16_SAMPLES, XSYSMONPSV_AVERAGE_2_SAMPLES, XSYSMONPSV_AVERAGE_4_SAMPLES, XSYSMONPSV_AVERAGE_8_SAMPLES, XSYSMONPSV_CONFIG0, XSYSMONPSV_CONFIG0_SUPPLY_AVERAGE_MASK, XSYSMONPSV_CONFIG0_SUPPLY_AVERAGE_SHIFT, XSYSMONPSV_INVALID, XSysMonPsv_ReadReg32.
void XSysMonPsv_IntrEnable(XSysMonPsv *InstancePtr, u32 Mask, u8 IntrNum)
Enables the specified interrupts in the device.
InstancePtr Pointer to the XSysMonPsv instance. Mask 32 bit-mask of the interrupts to be enabled. Bit positions of 1 will be enabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XSYSMONPSV_IER_* bits defined in xsysmonpsv_hw.h. IntrNum Interrupt enable register to be used. None.
References XSysMonPsv::IsReady, XSYSMONPSV_IER0_OFFSET, XSYSMONPSV_INTR_OFFSET, XSysMonPsv_WriteReg32.
u32 XSysMonPsv_IntrGetEnabled(XSysMonPsv *InstancePtr, u8 IntrNum)
Returns the enabled interrupts read from the Interrupt Mask Register (IMR).
Use the XSYSMONPSV_IMR0_* and XSYSMONPSV_IMR1_* constants defined in xsysmonpsv_hw.h to interpret the returned value. InstancePtr Pointer to the XSysMonPsv instance. IntrNum Interrupt enable register to be used A 32-bit value representing the contents of the Interrupt Mask Registers.
References XSysMonPsv::IsReady, XSYSMONPSV_IMR0_OFFSET, XSYSMONPSV_INTR_OFFSET, XSysMonPsv_ReadReg32.
void XSysMonPsv_IntrDisable(XSysMonPsv *InstancePtr, u32 Mask, u8 IntrNum)
Disables the specified interrupts in the device.
InstancePtr Pointer to the XSysMonPsv instance. Mask 32 bit-mask of the interrupts to be enabled. Bit positions of 1 will be disabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XSYSMONPSV_IDR_* bits defined in xsysmonpsv_hw.h. IntrNum Interrupt disable register to be used. None.
References XSysMonPsv::IsReady, XSYSMONPSV_IDR0_OFFSET, XSYSMONPSV_INTR_OFFSET, XSysMonPsv_WriteReg32.
u32 XSysMonPsv_IntrGetStatus(XSysMonPsv *InstancePtr)
Returns the interrupt status read from Interrupt Status Register(ISR).
Use the XSYSMONPSV_ISR* constants defined in xsysmonpsv_hw.h to interpret the returned value. InstancePtr Pointer to the XSysMonPsv instance. A 32-bit value representing the contents of the Interrupt Status Register (ISR).
References XSysMonPsv::IsReady, XSYSMONPSV_ISR_OFFSET, XSysMonPsv_ReadReg32.
void XSysMonPsv_IntrClear(XSysMonPsv *InstancePtr, u32 Mask)
Clears the specified interrupts in the Interrupt Status Register (ISR).
InstancePtr Pointer to the XSysMonPsv instance. Mask 32 bit-mask of the interrupts to be cleared. Bit positions of 1 will be cleared. Bit positions of 0 will not change the previous interrupt status.* None.
References XSysMonPsv::IsReady, XSYSMONPSV_ISR_OFFSET, XSysMonPsv_WriteReg32.
void XSysMonPsv_SetNewDataIntSrc(XSysMonPsv *InstancePtr, XSysMonPsv_Supply Supply, u32 Mask)
Sets a supply as a source new data interrupt.
InstancePtr Pointer to the XSysMonPsv instance. Supply Enum from the XSysMonPsv_Supply Mask 32 bit Mask for NEW_DATA_n fields in the interrupt registers None.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_INTR_NEW_DATA_MASK, XSYSMONPSV_INTR_NEW_DATA_SHIFT, XSYSMONPSV_NEW_DATA_INT_SRC, XSYSMONPSV_NEW_DATA_INT_SRC_ADDR_ID1_SHIFT, XSysMonPsv_ReadReg32, XSysMonPsv_WriteReg32.
XSysMonPsv_Config* XSysMonPsv_LookupConfig(void)
Looks for the device configuration based on the unique device ID.
The table XSysmonPsu_ConfigTable[] contains the configuration information for each device in the system.A pointer to the configuration table entry corresponding to the given device, or NULL if no match is found.
XSYSMONPSV_INTR_MASK
All interrupt Mask.
XSYSMONPSV_INVALID_SUPPLY
Invalid Supply.
Referenced by XSysMonPsv_ClearAlarm, XSysMonPsv_DisableVoltageEvents, XSysMonPsv_EnableSupplyAverage, XSysMonPsv_EnableVoltageEvents, XSysMonPsv_IsAlarmCondition, XSysMonPsv_IsAlarmPresent, XSysMonPsv_IsNewData, XSysMonPsv_ReadAlarmConfig, XSysMonPsv_ReadSupplyProcessed, XSysMonPsv_ReadSupplyRaw, XSysMonPsv_ReadSupplyThreshold, XSysMonPsv_ReadSupplyValue, XSysMonPsv_SetAlarmConfig, XSysMonPsv_SetSupplyLowerThreshold, XSysMonPsv_SetSupplyUpperThreshold.
XSYSMONPSV_PMBUS_INTERFACE
PMBus interface select.
XSYSMONPSV_I2C_INTERFACE
I2C interface select.
XSYSMONPSV_INVALID
Invalid Val.
Referenced by XSysMonPsv_ClearAlarm, XSysMonPsv_EnableSupplyAverage, XSysMonPsv_GetSupplyAverageRate, XSysMonPsv_GetTempAverageRate, XSysMonPsv_IsAlarmCondition, XSysMonPsv_IsAlarmPresent, XSysMonPsv_IsNewData, XSysMonPsv_ReadAlarmConfig, XSysMonPsv_ReadDeviceTemp, XSysMonPsv_ReadSupplyThreshold, XSysMonPsv_ReadSupplyValue, XSysMonPsv_SetAlarmConfig, XSysMonPsv_SetSupplyLowerThreshold, XSysMonPsv_SetSupplyUpperThreshold.
XSYSMONPSV_EXPONENT_RANGE_16
Voltage exponent val bit.
XSYSMONPSV_QFMT_SIGN
Q format signed bit.
XSYSMONPSV_QFMT_FRACTION
Q format fractional val.
XSYSMONPSV_UP_SAT_SIGNED
Upper limit staurated signed val.
Referenced by XSysMonPsv_SupplyProcessedToRaw.
XSYSMONPSV_UP_SAT
Upper limit saturated unsigned val.
Referenced by XSysMonPsv_SupplyProcessedToRaw.
XSYSMONPSV_LOW_SAT_SIGNED
Lower limit signed saturated val.
Referenced by XSysMonPsv_SupplyProcessedToRaw.
XSYSMONPSV_LOW_SAT
Lower limit unsigned saturated val.
Referenced by XSysMonPsv_SupplyProcessedToRaw.
XSYSMONPSV_BIPOLAR_UP_SAT
Upper limit bipolar saturated val.
XSYSMONPSV_BIPOLAR_LOW_SAT
Lower limit bipolar saturated val.
XSYSMONPSV_UNIPOLAR_UP_SAT
Upper limit unipolar saturated val.
XSYSMONPSV_UNIPOLAR_LOW_SAT
Lower limit unipolar saturated val.
XSYSMONPSV_ENABLE
Enable.
XSYSMONPSV_DISABLE
Disable.
XSYSMONPSV_HYSTERESIS
Hysteresis Mode.
XSYSMONPSV_WINDOW
Window Mode.
XSysMonPsv_ReadReg
This macro reads the given register.
RegisterAddr Register address in the address space of the SYSMONPSV device. The 32-bit value of the register
XSysMonPsv_WriteReg
This macro writes the given register.
RegisterAddr Register address in the address space of the SYSMONPSV device. Data 32-bit value to write to the register. None.
XSYSMONPSV_SECURE_WRITE_DEFAULT
Secure Write Command Payload.
XSYSMONPSV_SECURE_READ_DEFAULT
Secure Read Command Payload.
XSYSMONPSV_SECURE_DEFAULT_PAYLOAD_SIZE
Secure Payload Size.
XSYSMONPSV_H_
< prevent circular inclusions
by using protection macros
XSYSMONPSV_INTR_OFFSET
Interrupt register offset.
Referenced by XSysMonPsv_IntrDisable, XSysMonPsv_IntrEnable, XSysMonPsv_IntrGetEnabled.