xsysmonpsv_intr_example.c
int TempInterruptOccured
int SupplyInterruptOccured
int SysMonPsvIntrExample()
This function runs a test on the System Monitor device using the driver APIs.
This function does the following tasks: Initiate the System Monitor device driver instanceEnable OT interruptSetup call back for interruptsRead supply configuration.Read the latest on-chip temperatures and confiured supplies - XST_SUCCESS if the example has completed successfully. XST_FAILURE if the example has failed.
References Supply_CallbackFunc, Temp_CallbackFunc, XSysMonPsv_EnableVoltageEvents, XSysMonPsv_GetSupplyThresholdLower, XSysMonPsv_GetSupplyThresholdUpper, XSysMonPsv_GetTempThresholdLower, XSysMonPsv_GetTempThresholdUpper, XSYSMONPSV_MILLI_SCALE, XSysMonPsv_ReadSupplyProcessed, XSysMonPsv_ReadSupplyRaw, XSysMonPsv_ReadTempProcessed, XSysMonPsv_ReadTempRaw, XSysMonPsv_SetSupplyThresholdLower, XSysMonPsv_SetSupplyThresholdUpper, XSysMonPsv_SetTempMode, XSysMonPsv_SetTempThresholdLower, XSysMonPsv_SetTempThresholdUpper, XSysMonPsv_Supply_Arr, XSYSMONPSV_TEMP_EVENT, XSYSMONPSV_TEMP_MAX, XSYSMONPSV_TEMP_MIN.
Referenced by main.
void Temp_CallbackFunc(void *data)
Callback function to notify temperature event.
Data is the data needed by the callback function.
Referenced by SysMonPsvIntrExample.
void Supply_CallbackFunc(void *data)
Callback function to notify supply event.
Data is the data needed by the callback function.
Referenced by SysMonPsvIntrExample.
int main(void)
Main function that invokes the intr example in this file.
- XST_SUCCESS if the example has completed successfully. XST_FAILURE if the example has failed.
References SysMonPsvIntrExample.