xsysmonpsv_common.h
XSYSMONPSV_INTR_OFFSET
Interrupt Offset.
XSYSMONPSV_LOCK_CODE
Lock code value.
Referenced by XSysMonPsv_UnlockRegspace, XSysMonPsv_WriteReg32.
XSYSMONPSV_INTR_0_ID
Interrupt unique ID.
XSYSMONPSV_INTR_1_ID
Interrupt unique ID.
XSYSMONPSV_BIT_ALARM0
Bit for supply[0-31].
XSYSMONPSV_BIT_ALARM1
Bit for supply[32-63].
XSYSMONPSV_BIT_ALARM2
Bit for supply[64-95].
XSYSMONPSV_BIT_ALARM3
Bit for supply[96-127].
XSYSMONPSV_BIT_ALARM4
Bit for supply[128-159].
XSYSMONPSV_BIT_ALARM5
Reserved.
XSYSMONPSV_BIT_ALARM6
Reserved.
XSYSMONPSV_BIT_ALARM7
Reserved.
XSYSMONPSV_BIT_OT
Over Temperature bit.
XSYSMONPSV_BIT_TEMP
Temperature bit.
XSYSMONPSV_UP_SAT_SIGNED_VAL
Signed upper saturation value.
Referenced by XSysMonPsv_SupplyProcessedToRaw.
XSYSMONPSV_LOW_SAT_SIGNED_VAL
Signed lower saturation value.
Referenced by XSysMonPsv_SupplyProcessedToRaw.
XSYSMONPSV_UP_SAT_VAL
Upper saturation value.
Referenced by XSysMonPsv_SupplyProcessedToRaw.
XSYSMONPSV_LOW_SAT_VAL
Lower saturation value.
Referenced by XSysMonPsv_SupplyProcessedToRaw.
XSYSMONPSV_MILLI_SCALE
Milli scale factor.
Referenced by SysMonPsvIntrExample, SysMonPsvPolledExample.
compare
Macro to compare threshold with current value.
twoscomp
Macro for 2's complement.
Referenced by XSysMonPsv_Q8P7ToCelsius.
ALARM_REG
Alarm Register offset for supply.
Referenced by XSysMonPsv_DisableVoltageEvents, XSysMonPsv_EnableVoltageEvents.
ALARM_SHIFT
Supply bit in Alarm Register.
Referenced by XSysMonPsv_DisableVoltageEvents, XSysMonPsv_EnableVoltageEvents.
GET_BIT
Macro for bit shifter.
Referenced by XSysMonPsv_EnableVoltageEvents.
XSysMonPsv_EventDir
Rising or falling both direction.
XSysMonPsv_TempType
Current temperature.
XSysMonPsv_TempEvt
Temperature event.
int XSysMonPsv_TempOffset(XSysMonPsv_TempType Type)
Provides the register offset for the different type.
Type Max or Min Temperature Type -XST_FAILURE when fails -Register offset
References XSYSMONPSV_DEVICE_TEMP_MAX, XSYSMONPSV_DEVICE_TEMP_MAX_MAX, XSYSMONPSV_DEVICE_TEMP_MIN_MIN, XSYSMONPSV_TEMP, XSYSMONPSV_TEMP_MAX, XSYSMONPSV_TEMP_MIN.
Referenced by XSysMonPsv_ReadTempProcessed, XSysMonPsv_ReadTempRaw.
int XSysMonPsv_TempThreshOffset(XSysMonPsv_TempEvt Event, XSysMonPsv_EventDir Dir, u32 *Offset)
Provides the temperature threshold (upper or lower) offset.
Event Temp or OT event type. Dir Falling or rising direction Offset Upper or lower threshold offset. - XST_FAILURE when fails XST_SUCCESS when correct params are used.
References XSYSMONPSV_DEVICE_TEMP_TH_FALLING, XSYSMONPSV_DEVICE_TEMP_TH_RISING, XSYSMONPSV_EV_DIR_RISING, XSYSMONPSV_OT_EVENT, XSYSMONPSV_OT_TEMP_TH_FALLING, XSYSMONPSV_OT_TEMP_TH_RISING, XSYSMONPSV_TEMP_EVENT.
u32 XSysMonPsv_SupplyOffset(XSysMonPsv *InstancePtr, int Supply)
Provides the supply offset.
InstancePtr Pointer to the XSysMonPsv instance. Supply Enum which indicates the desired supply. Offset supply.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_SUPPLY.
Referenced by XSysMonPsv_ReadSupplyProcessed, XSysMonPsv_ReadSupplyRaw.
u32 XSysMonPsv_SupplyThreshOffset(XSysMonPsv *InstancePtr, int Supply, XSysMonPsv_EventDir Dir)
Provides the supply threshold (upper or lower) offset.
InstancePtr Pointer to the XSysMonPsv instance. Supply Enum which indicates the desired supply. Dir Type of the direction - falling or rising. Upper or lower threshold offset.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_EV_DIR_RISING, XSYSMONPSV_SUPPLY_TH_LOWER, XSYSMONPSV_SUPPLY_TH_UPPER.
Referenced by XSysMonPsv_GetSupplyThresholdLower, XSysMonPsv_GetSupplyThresholdUpper, XSysMonPsv_SetSupplyThresholdLower, XSysMonPsv_SetSupplyThresholdUpper.
void XSysMonPsv_Q8P7ToCelsius(u32 RawData, int *Val, int *Val2)
Converts Q8P7 To Celsius.
RawData Raw temperature Data. Val Value in Q8P7 format. Val2 Constant 128. None.
References twoscomp.
Referenced by XSysMonPsv_ReadTempProcessed, XSysMonPsv_ReadTempProcessedSat.
void XSysMonPsv_CelsiusToQ8P7(u32 *RawData, int Val, int Val2)
Converts Celsius To Q8P7.
RawData Raw Temperature Data. Val Numerator for conversion to deg C. Val2 Denominator for conversion to deg C in Q8.7 format. None.
void XSysMonPsv_SupplyRawToProcessed(int RawData, int *Val, int *Val2)
Converts raw data to processed.
RawData Raw voltage data. Val Numerator for conversion to volts. Val2 Denominator for conversion to volts. None.
References XSYSMONPSV_SUPPLY_FMT_MASK, XSYSMONPSV_SUPPLY_FMT_SHIFT, XSYSMONPSV_SUPPLY_MANTISSA_MASK, XSYSMONPSV_SUPPLY_MANTISSA_SIGN, XSYSMONPSV_SUPPLY_MODE_MASK, XSYSMONPSV_SUPPLY_MODE_SHIFT.
Referenced by XSysMonPsv_ReadSupplyProcessed.
void XSysMonPsv_SupplyProcessedToRaw(int Val, int Val2, u32 RegVal, u32 *RawData)
Converts processed data to raw.
Val Numerator for conversion to volts. Val2 Denominator for conversion to volts. RegVal Register Value. RawData Converted Raw data. None.
References XSYSMONPSV_LOW_SAT, XSYSMONPSV_LOW_SAT_SIGNED, XSYSMONPSV_LOW_SAT_SIGNED_VAL, XSYSMONPSV_LOW_SAT_VAL, XSYSMONPSV_SUPPLY_FMT_MASK, XSYSMONPSV_SUPPLY_FMT_SHIFT, XSYSMONPSV_SUPPLY_MODE_MASK, XSYSMONPSV_SUPPLY_MODE_SHIFT, XSYSMONPSV_UP_SAT, XSYSMONPSV_UP_SAT_SIGNED, XSYSMONPSV_UP_SAT_SIGNED_VAL, XSYSMONPSV_UP_SAT_VAL.
u32 XSysMonPsv_IsAlarmPresent(XSysMonPsv *InstancePtr, XSysMonPsv_Supply Supply)
Checks if the supply value has exceeded the set threshold values.
InstancePtr Pointer to the driver instance. Supply Enum which indicates the desired supply. True if new data available. False if new data is not available. Invalid if the Supply has not been configured.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_ALARM_FLAG0, XSYSMONPSV_INVALID, XSYSMONPSV_INVALID_SUPPLY, XSysMonPsv_ReadReg32.
u32 XSysMonPsv_ClearAlarm(XSysMonPsv *InstancePtr, XSysMonPsv_Supply Supply)
Clears alarm status.
InstancePtr Pointer to the driver instance. Supply Enum which indicates the desired supply. XST_SUCCESS if the alarm was cleared. XSYSMONPSV_INVALID if the Supply has not been configured.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_ALARM_FLAG0, XSYSMONPSV_INVALID, XSYSMONPSV_INVALID_SUPPLY, XSysMonPsv_ReadReg32, XSysMonPsv_WriteReg32.
int XSysMonPsv_InterruptEnable(XSysMonPsv *InstancePtr, u32 Mask, u8 IntrNum)
Enables the specified interrupts in the device.
InstancePtr Pointer to the driver instance. Mask 32 bit-mask of the interrupts to be enabled. Bit positions of 1 will be enabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XSYSMON_IER_* bits defined in InstancePtr.h. IntrNum Interrupt enable register to be used - XST_FAILURE if error XST_SUCCESS if successful
References XSYSMONPSV_IER0_OFFSET, XSYSMONPSV_PCSR_LOCK, XSysMonPsv_WriteReg32.
Referenced by XSysMonPsv_EnableVoltageEvents.
int XSysMonPsv_InterruptDisable(XSysMonPsv *InstancePtr, u32 Mask, u8 IntrNum)
Disables the specified interrupts in the device.
InstancePtr Pointer to the driver instance. Mask 32 bit-mask of the interrupts to be enabled. Bit positions of 1 will be disabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XSYSMONPSV_IDR_* bits defined in InstancePtr.h. IntrNum Interrupt disable register to be used - XST_FAILURE if error XST_SUCCESS if successful
References XSYSMONPSV_IDR0_OFFSET, XSYSMONPSV_PCSR_LOCK, XSysMonPsv_WriteReg32.
int XSysMonPsv_InterruptGetStatus(XSysMonPsv *InstancePtr, u32 *IntrStatus)
Returns the interrupt status read from Interrupt Status Register(ISR).
Use the XSYSMONPSV_ISR* constants defined in InstancePtr.h to interpret the returned value. InstancePtr Pointer to the driver instance. IntrStatus 32-bit value representing the contents of the Interrupt Status Register (ISR). - XST_FAILURE when NULL Instance is passed XST_SUCCESS if succeeds
References XSYSMONPSV_ISR_OFFSET, XSysMonPsv_ReadReg32.
void XSysMonPsv_InterruptClear(XSysMonPsv *InstancePtr, u32 Mask)
Clears the specified interrupts in the Interrupt Status Register(ISR).
InstancePtr Pointer to the struct InstancePtr. Mask 32 bit-mask of the interrupts to be cleared. Bit positions of 1 will be cleared. Bit positions of 0 will not change the previous interrupt status.* None.
References XSYSMONPSV_ISR_OFFSET, XSysMonPsv_WriteReg32.
void XSysMonPsv_UnlockRegspace(XSysMonPsv *InstancePtr)
Unlocks the register space of InstancePtr hardware.
InstancePtr Pointer to the driver instance. None.
References XSYSMONPSV_LOCK_CODE, XSYSMONPSV_PCSR_LOCK, XSysMonPsv_WriteReg32.