xsysmonpsv.c
s64 XSysMonPsv_CfgInitialize(XSysMonPsv *InstancePtr, XSysMonPsv_Config *CfgPtr)
Initializes XSysMonPsv device/instance.
This function must be called prior to using the System Monitor device. InstancePtr Pointer to the XSysMonPsv instance. CfgPtr Points to the XSysMonPsv device configuration structure. XST_SUCCESS if successful. The user needs to first call the XSysMonPsv_LookupConfig() API which returns the Configuration structure pointer which is passed as a parameter to the XSysMonPsv_CfgInitialize() API.
References XSysMonPsv_Config::BaseAddress, XSysMonPsv::Config, XSysMonPsv::IsReady, XSysMonPsv_Config::Supply_List, XSYSMONPSV_MAX_SUPPLIES.
void XSysMonPsv_SystemReset(XSysMonPsv *InstancePtr)
Resets the SystemMonitor.
InstancePtr Pointer to the XSysMonPsv instance. None.
References XSYSMONPSV_PCSR_CONTROL, XSYSMONPSV_PCSR_CONTROL_SYS_RST_MASK_MASK, XSYSMONPSV_PCSR_MASK, XSYSMONPSV_PCSR_MASK_SYS_RST_MASK_MASK, XSysMonPsv_WriteReg32.
void XSysMonPsv_EnRegGate(XSysMonPsv *InstancePtr, u8 Enable)
Gates the register outputs.
InstancePtr Pointer to the XSysMonPsv instance. Enable Flag to enable or disable gate registers. None.
References XSYSMONPSV_PCSR_CONTROL, XSYSMONPSV_PCSR_CONTROL_GATEREG_SHIFT, XSYSMONPSV_PCSR_MASK, XSYSMONPSV_PCSR_MASK_GATEREG_MASK, XSysMonPsv_WriteReg32.
void XSysMonPsv_SetPMBusAddress(XSysMonPsv *InstancePtr, u8 Address)
Sets the PMBus address for the System Monitor.
InstancePtr Pointer to the device instance. Address Value at which the Sysmon will be addressed on the PMBus. None.
References XSYSMONPSV_CONFIG0, XSYSMONPSV_CONFIG0_PMBUS_ADDRESS_MASK, XSysMonPsv_ReadReg32, XSysMonPsv_WriteReg32.
void XSysMonPsv_PMBusEnable(XSysMonPsv *InstancePtr, u8 Enable)
Enables/disbles the PMBus on the System Monitor.
InstancePtr Pointer to the driver instance. Enable Value which enables or disables the PMBus. None. If Enable = 0, PMBus lines will be in tristate. If Enable = 1, PMBus lines will be active.
References XSYSMONPSV_CONFIG0, XSYSMONPSV_CONFIG0_PMBUS_ENABLE_MASK, XSYSMONPSV_CONFIG0_PMBUS_ENABLE_SHIFT, XSysMonPsv_ReadReg32, XSysMonPsv_WriteReg32.
void XSysMonPsv_PMBusEnableCmd(XSysMonPsv *InstancePtr, u8 Enable)
Restricts or de-restrict all PMBs commands.
InstancePtr Pointer to the driver instance. Enable Value which restrics or de-restrict the PMBus commands. None. If Enable = 0, PMBus commands are disabled. If Enable = 1, PMBus commands are enabled.
References XSYSMONPSV_CONFIG0, XSYSMONPSV_CONFIG0_PMBUS_UNRESTRICTED_MASK, XSYSMONPSV_CONFIG0_PMBUS_UNRESTRICTED_SHIFT, XSysMonPsv_ReadReg32, XSysMonPsv_WriteReg32.
void XSysMonPsv_SelectExtInterface(XSysMonPsv *InstancePtr, u8 Interface)
Selects I2C or PMBus interface to which traffic from SMBus is routed.
InstancePtr Pointer to the driver instance. Interface Value which determies where the SMBus traffic gets routed to. None. If Interface = 1, I2C command interface is enabled. If Interface = 0, PMBus command interface is enabled.
References XSYSMONPSV_CONFIG0, XSYSMONPSV_CONFIG0_I2C_NOT_PMBUS_MASK, XSYSMONPSV_CONFIG0_I2C_NOT_PMBUS_SHIFT, XSysMonPsv_ReadReg32, XSysMonPsv_WriteReg32.
void XSysMonPsv_StatusReset(XSysMonPsv *InstancePtr, u8 ResetSupply, u8 ResetTemperature)
Resets the Min and Max values of supplies and temperature to negative and positive saturation respectively.
InstancePtr Pointer to the driver instance. ResetSupply Resets the MIN and MAX values reached by the internal supplies since the last reset. ResetTemperature Resets the MIN and MAX values reached by the device since the last reset. None.
References XSYSMONPSV_STATUS_RESET, XSYSMONPSV_STATUS_RESET_SUPPLY_SHIFT, XSysMonPsv_WriteReg32.
u16 XSysMonPsv_ReadDevTempThreshold(XSysMonPsv *InstancePtr, XSysMonPsv_Threshold ThresholdType)
Returns the device temperature threshold for min and max values in signed Q8.7 format.
InstancePtr Pointer to the driver instance. ThresholdType Enum which indicates the type of threshold. Device Temperature threshold in signed Q8.7 format. To get the value in Deg Celsius, use XSysMonPsv_FixedToFloat.
References XSYSMONPSV_DEVICE_TEMP_TH, XSysMonPsv_ReadReg32.
void XSysMonPsv_SetDevTempThreshold(XSysMonPsv *InstancePtr, XSysMonPsv_Threshold ThresholdType, u16 Value)
Sets Device Temperature Threshold values.
InstancePtr Pointer to the driver instance. ThresholdType Enum which indicates the type of threshold. Value Raw ADC threshold value. None. Use XSysMonPsv_FloatToFixed to get the raw ADC value.
References XSYSMONPSV_DEVICE_TEMP_TH, XSysMonPsv_WriteReg32.
u16 XSysMonPsv_ReadOTTempThreshold(XSysMonPsv *InstancePtr, XSysMonPsv_Threshold ThresholdType)
Returns the OT temperature threshold for min and max values in signed Q8.7 format.
InstancePtr Pointer to the driver instance. ThresholdType Enum which indicates the type of threshold OT Temperature threshold in signed Q8.7 format.
References XSYSMONPSV_OT_TEMP_TH, XSysMonPsv_ReadReg32.
void XSysMonPsv_SetOTTempThreshold(XSysMonPsv *InstancePtr, XSysMonPsv_Threshold ThresholdType, u16 Value)
Sets OT Temperature Threshold values.
InstancePtr Pointer to the driver instance. ThresholdType Enum which indicates the type of threshold. Value Raw ADC threshold value. None. Use XSysMonPsv_FloatToFixed to get the raw ADC value.
References XSYSMONPSV_OT_TEMP_TH, XSysMonPsv_WriteReg32.
u32 XSysMonPsv_ReadDeviceTemp(XSysMonPsv *InstancePtr, XSysMonPsv_Val Value)
Returns the temperature values for the device in signed Q8.7 format.
InstancePtr Pointer to the driver instance. Value Enum which indicates the type of temperature value to be read. Temperature value requested. XSYSMONPSV_INVALID if invalid value requested. XSYSMONPSV_VAL_VREF_MIN and XSYSMONPSV_VAL_VREF_MAX are only supported for ES1 silicon to get min and max temperature values. XSYSMONPSV_VAL_VREF_MIN and XSYSMONPSV_VAL_VREF_MAX are not supported on production silicon. Use XSYSMONPSV_VAL to get the current temperature value on production silicon. XSYSMONPSV_VAL is not supported on ES1 silicon.
References XSYSMONPSV_DEVICE_TEMP, XSYSMONPSV_DEVICE_TEMP_MAX, XSYSMONPSV_DEVICE_TEMP_MAX_MAX, XSYSMONPSV_DEVICE_TEMP_MIN, XSYSMONPSV_DEVICE_TEMP_MIN_MIN, XSYSMONPSV_INVALID, XSysMonPsv_ReadReg32, XSYSMONPSV_VAL, XSYSMONPSV_VAL_MAX, XSYSMONPSV_VAL_MIN, XSYSMONPSV_VAL_VREF_MAX, XSYSMONPSV_VAL_VREF_MIN.
u32 XSysMonPsv_ReadSupplyThreshold(XSysMonPsv *InstancePtr, XSysMonPsv_Supply Supply, XSysMonPsv_Threshold ThresholdType)
Reads the raw value for Supply Threshold.
InstancePtr Pointer to the driver instance. Supply Enum which indicates the desired supply to be read. ThresholdType Enum which indicates the type of threshold. The raw Upper or Lower threshold of the supply XSYSMONPSV_INVALID if the supply hasn't been configured.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_INVALID, XSYSMONPSV_INVALID_SUPPLY, XSysMonPsv_ReadReg32, XSYSMONPSV_SUPPLY_TH_LOWER, XSYSMONPSV_SUPPLY_TH_UPPER, XSYSMONPSV_TH_LOWER.
u32 XSysMonPsv_ReadSupplyValue(XSysMonPsv *InstancePtr, XSysMonPsv_Supply Supply, XSysMonPsv_Val Value)
Reads the raw supply value for requested.
InstancePtr Pointer to the driver instance. Supply Enum which indicates the desired supply to be read. Value Type of reading for the supply. The raw values for min, max or the prevailing supply value. Invalid if the supply is not configured.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_INVALID, XSYSMONPSV_INVALID_SUPPLY, XSysMonPsv_ReadReg32, XSYSMONPSV_SUPPLY, XSYSMONPSV_SUPPLY_MAX, XSYSMONPSV_SUPPLY_MIN, XSYSMONPSV_VAL, XSYSMONPSV_VAL_MIN.
u32 XSysMonPsv_IsNewData(XSysMonPsv *InstancePtr, XSysMonPsv_Supply Supply)
Checks if new data is available for a supply.
InstancePtr Pointer to the driver instance. Supply Enum which indicates the desired supply. True if new data available. False if new data is not available. Invalid if the supply is not configured. None.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_INVALID, XSYSMONPSV_INVALID_SUPPLY, XSYSMONPSV_NEW_DATA_FLAG0, XSysMonPsv_ReadReg32, XSysMonPsv_WriteReg32.
u32 XSysMonPsv_IsAlarmCondition(XSysMonPsv *InstancePtr, XSysMonPsv_Supply Supply)
Checks if the supply value has exceeded the set threshold values.
InstancePtr Pointer to the driver instance. Supply Enum which indicates the desired supply. True if new data available. False if new data is not available. Invalid if the supply is not configured.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_ALARM_FLAG0, XSYSMONPSV_INVALID, XSYSMONPSV_INVALID_SUPPLY, XSysMonPsv_ReadReg32, XSysMonPsv_WriteReg32.
u32 XSysMonPsv_SetSupplyUpperThreshold(XSysMonPsv *InstancePtr, XSysMonPsv_Supply Supply, u32 Value)
Sets the raw value for upper supply threshold.
InstancePtr Pointer to the driver instance. Supply Enum which indicates the desired supply to be configured Value Upper threshold raw value XSYSMONPSV_INVALID if the Supply hasn't been configured XST_SUCCESS otherwise.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_INVALID, XSYSMONPSV_INVALID_SUPPLY, XSYSMONPSV_SUPPLY_TH_UPPER, XSysMonPsv_WriteReg32.
u32 XSysMonPsv_SetSupplyLowerThreshold(XSysMonPsv *InstancePtr, XSysMonPsv_Supply Supply, u32 Value)
Sets the raw value for Lower Supply Threshold.
InstancePtr Pointer to the driver instance. Supply Enum which indicates the desired supply to be configured. Value Lower threshold raw value. XSYSMONPSV_INVALID if the Supply hasn't been configured XST_SUCCESS otherwise.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_INVALID, XSYSMONPSV_INVALID_SUPPLY, XSYSMONPSV_SUPPLY_TH_LOWER, XSysMonPsv_WriteReg32.
void XSysMonPsv_SetTempMode(XSysMonPsv *InstancePtr, u32 Mode)
Sets the alarm mode for temperature alarms.
InstancePtr Pointer to the driver instance. Mode Sets the Hysteresis or window mode. Mode = 1 Hysteresis Mode Mode = 0 Window Mode None.
References XSYSMONPSV_ALARM_CONFIG, XSYSMONPSV_ALARM_CONFIG_DEV_ALARM_MODE_MASK, XSYSMONPSV_ALARM_CONFIG_DEV_ALARM_MODE_SHIFT, XSysMonPsv_ReadReg32, XSysMonPsv_WriteReg32.
Referenced by SysMonPsvIntrExample.
void XSysMonPsv_SetOTMode(XSysMonPsv *InstancePtr, u32 Mode)
Sets the alarm mode for OT alarm.
InstancePtr Pointer to the driver instance. Mode Sets the Hysteresis or Window mode. Mode = XSYSMONPSV_HYSTERESIS Hysteresis Mode Mode = XSYSMONPSV_WINDOW Window Mode None.
References XSYSMONPSV_ALARM_CONFIG, XSYSMONPSV_ALARM_CONFIG_OT_ALARM_MODE_MASK, XSYSMONPSV_ALARM_CONFIG_OT_ALARM_MODE_SHIFT, XSysMonPsv_ReadReg32, XSysMonPsv_WriteReg32.
u32 XSysMonPsv_ReadAlarmConfig(XSysMonPsv *InstancePtr, XSysMonPsv_Supply Supply)
Reads the current supply Alarm Configuration.
InstancePtr Pointer to the driver instance. Supply Supply for which configuration is to be read. TRUE if enabled. FALSE if disabled. XSYSMONPSV_INVALID if invalid SupplyValue.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_ALARM_REG0, XSYSMONPSV_INVALID, XSYSMONPSV_INVALID_SUPPLY, XSysMonPsv_ReadReg32.
u32 XSysMonPsv_SetAlarmConfig(XSysMonPsv *InstancePtr, XSysMonPsv_Supply Supply, u32 Config)
Sets the Alarm configuration for a supply.
InstancePtr Pointer to the driver instance. Supply Supply for which config is to be set. Config Alarm config value. XSYSMONPSV_ENABLE to enable XSYSMONPSV_DISABLE to disable XST_SUCCESS if successful. XSYSMONPSV_INVALID if invalid SupplyValue.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_ALARM_REG0, XSYSMONPSV_INVALID, XSYSMONPSV_INVALID_SUPPLY, XSysMonPsv_ReadReg32, XSysMonPsv_WriteReg32.
int XSysMonPsv_ReadTempProcessed(XSysMonPsv *InstancePtr, XSysMonPsv_TempType Type, float *Val)
Reads the temperature and returns value in degree celsius.
InstancePtr Pointer to the driver instance. Type Minimum and maximum temperature type. Val Processed value in degree celsius. XST_FAILURE if error.XST_SUCCESS if successful.
References XSysMonPsv_Q8P7ToCelsius, XSysMonPsv_ReadReg32, XSysMonPsv_TempOffset.
Referenced by SysMonPsvIntrExample, SysMonPsvPolledExample.
int XSysMonPsv_ReadTempRaw(XSysMonPsv *InstancePtr, XSysMonPsv_TempType Type, u32 *Val)
Reads the temperature and returns value in raw format.
InstancePtr Pointer to the driver instance. Type Minimum and maximum temperature type. Val Value in raw format. XST_FAILURE if error.XST_SUCCESS if successful.
References XSysMonPsv_ReadReg32, XSysMonPsv_TempOffset.
Referenced by SysMonPsvIntrExample.
int XSysMonPsv_ReadTempProcessedSat(XSysMonPsv *InstancePtr, int SatId, float *Val)
Reads the temperature of each satellite in degree celsius.
InstancePtr Pointer to the driver instance. SatId Satellite ID. Val Processed value. XST_FAILURE if error.XST_SUCCESS if successful.
References XSysMonPsv_Q8P7ToCelsius, XSysMonPsv_ReadReg32, XSYSMONPSV_TEMP_SAT.
int XSysMonPsv_ReadTempRawSat(XSysMonPsv *InstancePtr, int SatId, u32 *Val)
Reads the temperature of each satellite in raw format.
InstancePtr Pointer to the driver instance. SatId Satellite ID. Val Raw value. XST_FAILURE if error.XST_SUCCESS if successful.
References XSysMonPsv_ReadReg32, XSYSMONPSV_TEMP_SAT.
int XSysMonPsv_SetTempThresholdUpper(XSysMonPsv *InstancePtr, XSysMonPsv_TempEvt Event, u32 Val)
Sets the temperature upper threshold.
InstancePtr Pointer to the driver instance. Event Temp or OT event type Val Threshold value to be set. XST_FAILURE if error.XST_SUCCESS if successful.
References XSYSMONPSV_DEVICE_TEMP_TH, XSYSMONPSV_OT_EVENT, XSYSMONPSV_OT_TEMP_TH, XSYSMONPSV_TEMP_EVENT, XSysMonPsv_WriteReg32.
Referenced by SysMonPsvIntrExample.
int XSysMonPsv_SetTempThresholdLower(XSysMonPsv *InstancePtr, XSysMonPsv_TempEvt Event, u32 Val)
Sets the temperature lower threshold.
InstancePtr Pointer to the driver instance. Event Temp or OT event type. Val Threshold value to be set. XST_FAILURE if error.XST_SUCCESS if successful.
References XSYSMONPSV_DEVICE_TEMP_TH, XSYSMONPSV_OT_EVENT, XSYSMONPSV_OT_TEMP_TH, XSYSMONPSV_TEMP_EVENT, XSysMonPsv_WriteReg32.
Referenced by SysMonPsvIntrExample.
int XSysMonPsv_GetTempThresholdUpper(XSysMonPsv *InstancePtr, XSysMonPsv_TempEvt Event, u32 *Val)
Gets the temperature upper threshold.
InstancePtr Pointer to the driver instance. Event Temp or OT event type. Val Upper threshold value to be read. XST_FAILURE if errorXST_SUCCESS if successful.
References XSYSMONPSV_DEVICE_TEMP_TH, XSYSMONPSV_OT_EVENT, XSYSMONPSV_OT_TEMP_TH, XSysMonPsv_ReadReg32, XSYSMONPSV_TEMP_EVENT.
Referenced by SysMonPsvIntrExample.
int XSysMonPsv_GetTempThresholdLower(XSysMonPsv *InstancePtr, XSysMonPsv_TempEvt Event, u32 *Val)
Gets the temperature lower threshold.
InstancePtr Pointer to the driver instance. Event Temp or OT event type. Val lower threshold value to be read. XST_FAILURE if errorXST_SUCCESS if successful.
References XSYSMONPSV_DEVICE_TEMP_TH, XSYSMONPSV_OT_EVENT, XSYSMONPSV_OT_TEMP_TH, XSysMonPsv_ReadReg32, XSYSMONPSV_TEMP_EVENT.
Referenced by SysMonPsvIntrExample.
int XSysMonPsv_ReadSupplyProcessed(XSysMonPsv *InstancePtr, int Supply, float *Val)
Reads the voltage for the supply.
InstancePtr Pointer to the driver instance. Supply Voltage supply. Val Float value in Voltage. XST_FAILURE if errorXST_SUCCESS if successful.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_INVALID_SUPPLY, XSYSMONPSV_MAX_SUPPLIES, XSysMonPsv_ReadReg32, XSysMonPsv_SupplyOffset, XSysMonPsv_SupplyRawToProcessed.
Referenced by SysMonPsvIntrExample, SysMonPsvPolledExample.
int XSysMonPsv_ReadSupplyRaw(XSysMonPsv *InstancePtr, u32 Supply, u32 *Val)
Reads the voltage for the supply in raw.
InstancePtr Pointer to the driver instance. Supply Voltage supply. Val Raw voltage. XST_FAILURE if errorXST_SUCCESS if successful.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_INVALID_SUPPLY, XSYSMONPSV_MAX_SUPPLIES, XSysMonPsv_ReadReg32, XSysMonPsv_SupplyOffset.
Referenced by SysMonPsvIntrExample.
int XSysMonPsv_SetSupplyThresholdUpper(XSysMonPsv *InstancePtr, u32 Supply, u32 Val)
Sets the upper threshold voltage for the supply.
InstancePtr Pointer to the driver instance. Supply Voltage supply. Val Upper Threshold Value. XST_FAILURE if errorXST_SUCCESS if successful.
References XSYSMONPSV_EV_DIR_RISING, XSysMonPsv_SupplyThreshOffset, XSysMonPsv_WriteReg32.
Referenced by SysMonPsvIntrExample.
int XSysMonPsv_SetSupplyThresholdLower(XSysMonPsv *InstancePtr, int Supply, u32 Val)
Sets loser threshold voltage for the supply.
InstancePtr Pointer to the driver instance. Supply Voltage supply. Val Threshold Value. XST_FAILURE if errorXST_SUCCESS if successful.
References XSYSMONPSV_EV_DIR_FALLING, XSysMonPsv_SupplyThreshOffset, XSysMonPsv_WriteReg32.
Referenced by SysMonPsvIntrExample.
int XSysMonPsv_GetSupplyThresholdUpper(XSysMonPsv *InstancePtr, u32 Supply, u32 *Val)
Gets the upper threshold voltage for the supply.
InstancePtr Pointer to the driver instance. Supply Voltage supply. Val Threshold Value to be read. XST_FAILURE if errorXST_SUCCESS if successful.
References XSYSMONPSV_EV_DIR_RISING, XSYSMONPSV_MAX_SUPPLIES, XSysMonPsv_ReadReg32, XSysMonPsv_SupplyThreshOffset.
Referenced by SysMonPsvIntrExample.
int XSysMonPsv_GetSupplyThresholdLower(XSysMonPsv *InstancePtr, u32 Supply, u32 *Val)
Gets the lower threshold voltage for the supply.
InstancePtr Pointer to the driver instance. Supply Voltage supply. Val Threshold Value to be read. XST_FAILURE if error.XST_SUCCESS if successful.
References XSYSMONPSV_EV_DIR_FALLING, XSYSMONPSV_MAX_SUPPLIES, XSysMonPsv_ReadReg32, XSysMonPsv_SupplyThreshOffset.
Referenced by SysMonPsvIntrExample.
void XSysMonPsv_EnableTempAverage(XSysMonPsv *InstancePtr, int SatId, u8 Enable)
Enables or Disables temperature satellites averaging.
InstancePtr Pointer to the driver instance. SatId Temperature Satellite id, indexed from 1 to 64. Enable Enable/Disable flag. None
References XSYSMONPSV_EN_AVG_REG8, XSysMonPsv_UpdateReg32.
void XSysMonPsv_SetTempAverageRate(XSysMonPsv *InstancePtr, u8 AverageRate)
Sets temperature satellites average sampling rate value.
InstancePtr Pointer to the driver instance. AverageRate Average Sampling Rate Value to be set. None
References XSYSMONPSV_AVERAGE_0_SAMPLES, XSYSMONPSV_AVERAGE_16_SAMPLES, XSYSMONPSV_AVERAGE_2_SAMPLES, XSYSMONPSV_AVERAGE_4_SAMPLES, XSYSMONPSV_AVERAGE_8_SAMPLES, XSYSMONPSV_CONFIG0, XSYSMONPSV_CONFIG0_TEMP_AVERAGE_MASK, XSYSMONPSV_CONFIG0_TEMP_AVERAGE_SHIFT, XSysMonPsv_UpdateReg32.
int XSysMonPsv_GetTempAverageRate(XSysMonPsv *InstancePtr, u8 *AverageRate)
Gets temperature satellites average sampling rate value.
InstancePtr Pointer to the driver instance. AverageRate Average Sampling Rate Value to be read. XSYSMONPSV_INVALID if invalid value read.XST_SUCCESS if successful.
References XSYSMONPSV_AVERAGE_0_SAMPLES, XSYSMONPSV_AVERAGE_16_SAMPLES, XSYSMONPSV_AVERAGE_2_SAMPLES, XSYSMONPSV_AVERAGE_4_SAMPLES, XSYSMONPSV_AVERAGE_8_SAMPLES, XSYSMONPSV_CONFIG0, XSYSMONPSV_CONFIG0_TEMP_AVERAGE_MASK, XSYSMONPSV_CONFIG0_TEMP_AVERAGE_SHIFT, XSYSMONPSV_INVALID, XSysMonPsv_ReadReg32.
int XSysMonPsv_EnableSupplyAverage(XSysMonPsv *InstancePtr, XSysMonPsv_Supply Supply, u8 Enable)
Enables or Disables voltage supplies averaging.
InstancePtr Pointer to the driver instance. Supply Voltage supply. Enable Enable/Disable flag. XSYSMONPSV_INVALID if invalid supply given.XST_SUCCESS if successful.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_EN_AVG_REG0, XSYSMONPSV_INVALID, XSYSMONPSV_INVALID_SUPPLY, XSysMonPsv_UpdateReg32.
void XSysMonPsv_SetSupplyAverageRate(XSysMonPsv *InstancePtr, u8 AverageRate)
Sets voltage supplies average sampling rate value.
InstancePtr Pointer to the driver instance. AverageRate Average Sampling Rate Value to be set. None
References XSYSMONPSV_AVERAGE_0_SAMPLES, XSYSMONPSV_AVERAGE_16_SAMPLES, XSYSMONPSV_AVERAGE_2_SAMPLES, XSYSMONPSV_AVERAGE_4_SAMPLES, XSYSMONPSV_AVERAGE_8_SAMPLES, XSYSMONPSV_CONFIG0, XSYSMONPSV_CONFIG0_SUPPLY_AVERAGE_MASK, XSYSMONPSV_CONFIG0_SUPPLY_AVERAGE_SHIFT, XSysMonPsv_UpdateReg32.
int XSysMonPsv_GetSupplyAverageRate(XSysMonPsv *InstancePtr, u8 *AverageRate)
Gets voltage supplies average sampling rate value.
InstancePtr Pointer to the driver instance. AverageRate Average Sampling Rate Value to be read. XSYSMONPSV_INVALID if invalid value read.XST_SUCCESS if successful.
References XSYSMONPSV_AVERAGE_0_SAMPLES, XSYSMONPSV_AVERAGE_16_SAMPLES, XSYSMONPSV_AVERAGE_2_SAMPLES, XSYSMONPSV_AVERAGE_4_SAMPLES, XSYSMONPSV_AVERAGE_8_SAMPLES, XSYSMONPSV_CONFIG0, XSYSMONPSV_CONFIG0_SUPPLY_AVERAGE_MASK, XSYSMONPSV_CONFIG0_SUPPLY_AVERAGE_SHIFT, XSYSMONPSV_INVALID, XSysMonPsv_ReadReg32.