xsysmonpsv.h
XSysMonPsv_Threshold
Lower Threshold.
const char* XSysMonPsv_Supply_Arr[][]
Names of the supplies enabled in the design.
Referenced by SysMonPsvIntrExample, SysMonPsvPolledExample.
XSysMonPsv_Val
Current Value for temperature (for production silicon only) and supply.
XSysMonPsv_VoltageScale
1V unipolar fmt
XSYSMONPSV_H_
< prevent circular inclusions
by using protection macros
XSysMonPsv_GetAlarmMask
This macro returns the XSYSMONPSV_NEW_ALARMn_MASK for a configured supply.
InstancePtr Instance of sysmon driver Supply Type enum of supply enabled A 32 bit mask to be used for configuring interrupts
static float XSysMonPsv_RawToVoltage(u32 AdcData)
Converts raw AdcData into Voltage value.
AdcData System Monitor ADC Raw Data. The Voltage in volts.
static u16 XSysMonPsv_VoltageToRaw(float Volts, XSysMonPsv_VoltageScale Type)
Converts raw AdcData into Voltage value.
Volts Voltage value to be converted. Type Type of supply: Type = 0, Unipolar Type = 1, Bipolar The Voltage in Raw ADC format.
static float XSysMonPsv_FixedToFloat(u32 FixedQFmt)
Converts the fixed point to degree celsius.
FixedQFmt Q8.7 representation of temperature value. The Temperature in degree celsisus.
static u16 XSysMonPsv_FloatToFixed(float Temp)
Converts the floating point to Fixed Q8.7 format.
Temp Temperature value in Deg Celsius. Temperature value in fixed Q8.7 format.
s64 XSysMonPsv_CfgInitialize(XSysMonPsv *InstancePtr, XSysMonPsv_Config *CfgPtr)
Initializes XSysMonPsv device/instance.
This function must be called prior to using the System Monitor device. InstancePtr Pointer to the XSysMonPsv instance. CfgPtr Points to the XSysMonPsv device configuration structure. XST_SUCCESS if successful. The user needs to first call the XSysMonPsv_LookupConfig() API which returns the Configuration structure pointer which is passed as a parameter to the XSysMonPsv_CfgInitialize() API.
References XSysMonPsv::Config, XSysMonPsv_Config::BaseAddress, XSYSMONPSV_MAX_SUPPLIES, XSysMonPsv_Config::Supply_List, XSysMonPsv::IsReady.
void XSysMonPsv_SystemReset(XSysMonPsv *InstancePtr)
Resets the SystemMonitor.
InstancePtr Pointer to the XSysMonPsv instance. None.
References XSysMonPsv_WriteReg32, XSYSMONPSV_PCSR_MASK, XSYSMONPSV_PCSR_MASK_SYS_RST_MASK_MASK, XSYSMONPSV_PCSR_CONTROL, XSYSMONPSV_PCSR_CONTROL_SYS_RST_MASK_MASK.
void XSysMonPsv_EnRegGate(XSysMonPsv *InstancePtr, u8 Enable)
Gates the register outputs.
InstancePtr Pointer to the XSysMonPsv instance. Enable Flag to enable or disable gate registers. None.
References XSysMonPsv_WriteReg32, XSYSMONPSV_PCSR_MASK, XSYSMONPSV_PCSR_MASK_GATEREG_MASK, XSYSMONPSV_PCSR_CONTROL_GATEREG_SHIFT, XSYSMONPSV_PCSR_CONTROL.
void XSysMonPsv_SetPMBusAddress(XSysMonPsv *InstancePtr, u8 Address)
Sets the PMBus address for the System Monitor.
InstancePtr Pointer to the device instance. Address Value at which the Sysmon will be addressed on the PMBus. None.
References XSysMonPsv_ReadReg32, XSYSMONPSV_CONFIG0, XSYSMONPSV_CONFIG0_PMBUS_ADDRESS_MASK, XSysMonPsv_WriteReg32.
void XSysMonPsv_PMBusEnable(XSysMonPsv *InstancePtr, u8 Enable)
Enables/disbles the PMBus on the System Monitor.
InstancePtr Pointer to the driver instance. Enable Value which enables or disables the PMBus. None. If Enable = 0, PMBus lines will be in tristate. If Enable = 1, PMBus lines will be active.
References XSysMonPsv_ReadReg32, XSYSMONPSV_CONFIG0, XSYSMONPSV_CONFIG0_PMBUS_ENABLE_MASK, XSYSMONPSV_CONFIG0_PMBUS_ENABLE_SHIFT, XSysMonPsv_WriteReg32.
void XSysMonPsv_PMBusEnableCmd(XSysMonPsv *InstancePtr, u8 Enable)
Restricts or de-restrict all PMBs commands.
InstancePtr Pointer to the driver instance. Enable Value which restrics or de-restrict the PMBus commands. None. If Enable = 0, PMBus commands are disabled. If Enable = 1, PMBus commands are enabled.
References XSysMonPsv_ReadReg32, XSYSMONPSV_CONFIG0, XSYSMONPSV_CONFIG0_PMBUS_UNRESTRICTED_MASK, XSYSMONPSV_CONFIG0_PMBUS_UNRESTRICTED_SHIFT, XSysMonPsv_WriteReg32.
void XSysMonPsv_SelectExtInterface(XSysMonPsv *InstancePtr, u8 Interface)
Selects I2C or PMBus interface to which traffic from SMBus is routed.
InstancePtr Pointer to the driver instance. Interface Value which determies where the SMBus traffic gets routed to. None. If Interface = 1, I2C command interface is enabled. If Interface = 0, PMBus command interface is enabled.
References XSysMonPsv_ReadReg32, XSYSMONPSV_CONFIG0, XSYSMONPSV_CONFIG0_I2C_NOT_PMBUS_MASK, XSYSMONPSV_CONFIG0_I2C_NOT_PMBUS_SHIFT, XSysMonPsv_WriteReg32.
void XSysMonPsv_StatusReset(XSysMonPsv *InstancePtr, u8 ResetSupply, u8 ResetTemperature)
Resets the Min and Max values of supplies and temperature to negative and positive saturation respectively.
InstancePtr Pointer to the driver instance. ResetSupply Resets the MIN and MAX values reached by the internal supplies since the last reset. ResetTemperature Resets the MIN and MAX values reached by the device since the last reset. None.
References XSYSMONPSV_STATUS_RESET_SUPPLY_SHIFT, XSysMonPsv_WriteReg32, XSYSMONPSV_STATUS_RESET.
u16 XSysMonPsv_ReadDevTempThreshold(XSysMonPsv *InstancePtr, XSysMonPsv_Threshold ThresholdType)
Returns the device temperature threshold for min and max values in signed Q8.7 format.
InstancePtr Pointer to the driver instance. ThresholdType Enum which indicates the type of threshold. Device Temperature threshold in signed Q8.7 format. To get the value in Deg Celsius, use XSysMonPsv_FixedToFloat.
References XSYSMONPSV_DEVICE_TEMP_TH, XSysMonPsv_ReadReg32.
void XSysMonPsv_SetDevTempThreshold(XSysMonPsv *InstancePtr, XSysMonPsv_Threshold ThresholdType, u16 Value)
Sets Device Temperature Threshold values.
InstancePtr Pointer to the driver instance. ThresholdType Enum which indicates the type of threshold. Value Raw ADC threshold value. None. Use XSysMonPsv_FloatToFixed to get the raw ADC value.
References XSYSMONPSV_DEVICE_TEMP_TH, XSysMonPsv_WriteReg32.
u16 XSysMonPsv_ReadOTTempThreshold(XSysMonPsv *InstancePtr, XSysMonPsv_Threshold ThresholdType)
Returns the OT temperature threshold for min and max values in signed Q8.7 format.
InstancePtr Pointer to the driver instance. ThresholdType Enum which indicates the type of threshold OT Temperature threshold in signed Q8.7 format.
References XSYSMONPSV_OT_TEMP_TH, XSysMonPsv_ReadReg32.
void XSysMonPsv_SetOTTempThreshold(XSysMonPsv *InstancePtr, XSysMonPsv_Threshold ThresholdType, u16 Value)
Sets OT Temperature Threshold values.
InstancePtr Pointer to the driver instance. ThresholdType Enum which indicates the type of threshold. Value Raw ADC threshold value. None. Use XSysMonPsv_FloatToFixed to get the raw ADC value.
References XSYSMONPSV_OT_TEMP_TH, XSysMonPsv_WriteReg32.
u32 XSysMonPsv_ReadDeviceTemp(XSysMonPsv *InstancePtr, XSysMonPsv_Val Value)
Returns the temperature values for the device in signed Q8.7 format.
InstancePtr Pointer to the driver instance. Value Enum which indicates the type of temperature value to be read. Temperature value requested. XSYSMONPSV_INVALID if invalid value requested. XSYSMONPSV_VAL_VREF_MIN and XSYSMONPSV_VAL_VREF_MAX are only supported for ES1 silicon to get min and max temperature values. XSYSMONPSV_VAL_VREF_MIN and XSYSMONPSV_VAL_VREF_MAX are not supported on production silicon. Use XSYSMONPSV_VAL to get the current temperature value on production silicon. XSYSMONPSV_VAL is not supported on ES1 silicon.
References XSYSMONPSV_VAL_VREF_MIN, XSYSMONPSV_DEVICE_TEMP_MIN, XSYSMONPSV_VAL_VREF_MAX, XSYSMONPSV_DEVICE_TEMP_MAX, XSYSMONPSV_VAL_MIN, XSYSMONPSV_DEVICE_TEMP_MIN_MIN, XSYSMONPSV_VAL_MAX, XSYSMONPSV_DEVICE_TEMP_MAX_MAX, XSYSMONPSV_VAL, XSYSMONPSV_DEVICE_TEMP, XSYSMONPSV_INVALID, XSysMonPsv_ReadReg32.
u32 XSysMonPsv_ReadSupplyThreshold(XSysMonPsv *InstancePtr, XSysMonPsv_Supply Supply, XSysMonPsv_Threshold ThresholdType)
Reads the raw value for Supply Threshold.
InstancePtr Pointer to the driver instance. Supply Enum which indicates the desired supply to be read. ThresholdType Enum which indicates the type of threshold. The raw Upper or Lower threshold of the supply XSYSMONPSV_INVALID if the supply hasn't been configured.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_INVALID_SUPPLY, XSYSMONPSV_INVALID, XSYSMONPSV_TH_LOWER, XSYSMONPSV_SUPPLY_TH_LOWER, XSYSMONPSV_SUPPLY_TH_UPPER, XSysMonPsv_ReadReg32.
u32 XSysMonPsv_ReadSupplyValue(XSysMonPsv *InstancePtr, XSysMonPsv_Supply Supply, XSysMonPsv_Val Value)
Reads the raw supply value for requested.
InstancePtr Pointer to the driver instance. Supply Enum which indicates the desired supply to be read. Value Type of reading for the supply. The raw values for min, max or the prevailing supply value. Invalid if the supply is not configured.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_INVALID_SUPPLY, XSYSMONPSV_INVALID, XSYSMONPSV_VAL, XSYSMONPSV_SUPPLY, XSYSMONPSV_VAL_MIN, XSYSMONPSV_SUPPLY_MIN, XSYSMONPSV_SUPPLY_MAX, XSysMonPsv_ReadReg32.
u32 XSysMonPsv_IsNewData(XSysMonPsv *InstancePtr, XSysMonPsv_Supply Supply)
Checks if new data is available for a supply.
InstancePtr Pointer to the driver instance. Supply Enum which indicates the desired supply. True if new data available. False if new data is not available. Invalid if the supply is not configured. None.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_INVALID_SUPPLY, XSYSMONPSV_INVALID, XSysMonPsv_ReadReg32, XSYSMONPSV_NEW_DATA_FLAG0, XSysMonPsv_WriteReg32.
u32 XSysMonPsv_IsAlarmCondition(XSysMonPsv *InstancePtr, XSysMonPsv_Supply Supply)
Checks if the supply value has exceeded the set threshold values.
InstancePtr Pointer to the driver instance. Supply Enum which indicates the desired supply. True if new data available. False if new data is not available. Invalid if the supply is not configured.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_INVALID_SUPPLY, XSYSMONPSV_INVALID, XSysMonPsv_ReadReg32, XSYSMONPSV_ALARM_FLAG0, XSysMonPsv_WriteReg32.
u32 XSysMonPsv_SetSupplyUpperThreshold(XSysMonPsv *InstancePtr, XSysMonPsv_Supply Supply, u32 Value)
Sets the raw value for upper supply threshold.
InstancePtr Pointer to the driver instance. Supply Enum which indicates the desired supply to be configured Value Upper threshold raw value XSYSMONPSV_INVALID if the Supply hasn't been configured XST_SUCCESS otherwise.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_INVALID_SUPPLY, XSYSMONPSV_INVALID, XSYSMONPSV_SUPPLY_TH_UPPER, XSysMonPsv_WriteReg32.
u32 XSysMonPsv_SetSupplyLowerThreshold(XSysMonPsv *InstancePtr, XSysMonPsv_Supply Supply, u32 Value)
Sets the raw value for Lower Supply Threshold.
InstancePtr Pointer to the driver instance. Supply Enum which indicates the desired supply to be configured. Value Lower threshold raw value. XSYSMONPSV_INVALID if the Supply hasn't been configured XST_SUCCESS otherwise.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_INVALID_SUPPLY, XSYSMONPSV_INVALID, XSYSMONPSV_SUPPLY_TH_LOWER, XSysMonPsv_WriteReg32.
void XSysMonPsv_SetTempMode(XSysMonPsv *InstancePtr, u32 Mode)
Sets the alarm mode for temperature alarms.
InstancePtr Pointer to the driver instance. Mode Sets the Hysteresis or window mode. Mode = 1 Hysteresis Mode Mode = 0 Window Mode None.
References XSysMonPsv_ReadReg32, XSYSMONPSV_ALARM_CONFIG, XSYSMONPSV_ALARM_CONFIG_DEV_ALARM_MODE_MASK, XSYSMONPSV_ALARM_CONFIG_DEV_ALARM_MODE_SHIFT, XSysMonPsv_WriteReg32.
Referenced by SysMonPsvIntrExample.
void XSysMonPsv_SetOTMode(XSysMonPsv *InstancePtr, u32 Mode)
Sets the alarm mode for OT alarm.
InstancePtr Pointer to the driver instance. Mode Sets the Hysteresis or Window mode. Mode = XSYSMONPSV_HYSTERESIS Hysteresis Mode Mode = XSYSMONPSV_WINDOW Window Mode None.
References XSysMonPsv_ReadReg32, XSYSMONPSV_ALARM_CONFIG, XSYSMONPSV_ALARM_CONFIG_OT_ALARM_MODE_MASK, XSYSMONPSV_ALARM_CONFIG_OT_ALARM_MODE_SHIFT, XSysMonPsv_WriteReg32.
u32 XSysMonPsv_ReadAlarmConfig(XSysMonPsv *InstancePtr, XSysMonPsv_Supply Supply)
Reads the current supply Alarm Configuration.
InstancePtr Pointer to the driver instance. Supply Supply for which configuration is to be read. TRUE if enabled. FALSE if disabled. XSYSMONPSV_INVALID if invalid SupplyValue.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_INVALID_SUPPLY, XSYSMONPSV_INVALID, XSysMonPsv_ReadReg32, XSYSMONPSV_ALARM_REG0.
u32 XSysMonPsv_SetAlarmConfig(XSysMonPsv *InstancePtr, XSysMonPsv_Supply Supply, u32 Config)
Sets the Alarm configuration for a supply.
InstancePtr Pointer to the driver instance. Supply Supply for which config is to be set. Config Alarm config value. XSYSMONPSV_ENABLE to enable XSYSMONPSV_DISABLE to disable XST_SUCCESS if successful. XSYSMONPSV_INVALID if invalid SupplyValue.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_INVALID_SUPPLY, XSYSMONPSV_INVALID, XSysMonPsv_ReadReg32, XSYSMONPSV_ALARM_REG0, XSysMonPsv_WriteReg32.
int XSysMonPsv_ReadTempProcessed(XSysMonPsv *InstancePtr, XSysMonPsv_TempType Type, float *Val)
Reads the temperature and returns value in degree celsius.
InstancePtr Pointer to the driver instance. Type Minimum and maximum temperature type. Val Processed value in degree celsius. XST_FAILURE if error.XST_SUCCESS if successful.
References XSysMonPsv_TempOffset, XSysMonPsv_ReadReg32, XSysMonPsv_Q8P7ToCelsius.
Referenced by SysMonPsvIntrExample, SysMonPsvPolledExample.
int XSysMonPsv_ReadTempRaw(XSysMonPsv *InstancePtr, XSysMonPsv_TempType Type, u32 *Val)
Reads the temperature and returns value in raw format.
InstancePtr Pointer to the driver instance. Type Minimum and maximum temperature type. Val Value in raw format. XST_FAILURE if error.XST_SUCCESS if successful.
References XSysMonPsv_TempOffset, XSysMonPsv_ReadReg32.
Referenced by SysMonPsvIntrExample.
int XSysMonPsv_ReadTempProcessedSat(XSysMonPsv *InstancePtr, int SatId, float *Val)
Reads the temperature of each satellite in degree celsius.
InstancePtr Pointer to the driver instance. SatId Satellite ID. Val Processed value. XST_FAILURE if error.XST_SUCCESS if successful.
References XSYSMONPSV_TEMP_SAT, XSysMonPsv_ReadReg32, XSysMonPsv_Q8P7ToCelsius.
int XSysMonPsv_ReadTempRawSat(XSysMonPsv *InstancePtr, int SatId, u32 *Val)
Reads the temperature of each satellite in raw format.
InstancePtr Pointer to the driver instance. SatId Satellite ID. Val Raw value. XST_FAILURE if error.XST_SUCCESS if successful.
References XSYSMONPSV_TEMP_SAT, XSysMonPsv_ReadReg32.
int XSysMonPsv_SetTempThresholdUpper(XSysMonPsv *InstancePtr, XSysMonPsv_TempEvt Event, u32 Val)
Sets the temperature upper threshold.
InstancePtr Pointer to the driver instance. Event Temp or OT event type Val Threshold value to be set. XST_FAILURE if error.XST_SUCCESS if successful.
References XSYSMONPSV_TEMP_EVENT, XSYSMONPSV_DEVICE_TEMP_TH, XSYSMONPSV_OT_EVENT, XSYSMONPSV_OT_TEMP_TH, XSysMonPsv_WriteReg32.
Referenced by SysMonPsvIntrExample.
int XSysMonPsv_SetTempThresholdLower(XSysMonPsv *InstancePtr, XSysMonPsv_TempEvt Event, u32 Val)
Sets the temperature lower threshold.
InstancePtr Pointer to the driver instance. Event Temp or OT event type. Val Threshold value to be set. XST_FAILURE if error.XST_SUCCESS if successful.
References XSYSMONPSV_TEMP_EVENT, XSYSMONPSV_DEVICE_TEMP_TH, XSYSMONPSV_OT_EVENT, XSYSMONPSV_OT_TEMP_TH, XSysMonPsv_WriteReg32.
Referenced by SysMonPsvIntrExample.
int XSysMonPsv_GetTempThresholdUpper(XSysMonPsv *InstancePtr, XSysMonPsv_TempEvt Event, u32 *Val)
Gets the temperature upper threshold.
InstancePtr Pointer to the driver instance. Event Temp or OT event type. Val Upper threshold value to be read. XST_FAILURE if errorXST_SUCCESS if successful.
References XSYSMONPSV_TEMP_EVENT, XSYSMONPSV_DEVICE_TEMP_TH, XSYSMONPSV_OT_EVENT, XSYSMONPSV_OT_TEMP_TH, XSysMonPsv_ReadReg32.
Referenced by SysMonPsvIntrExample.
int XSysMonPsv_GetTempThresholdLower(XSysMonPsv *InstancePtr, XSysMonPsv_TempEvt Event, u32 *Val)
Gets the temperature lower threshold.
InstancePtr Pointer to the driver instance. Event Temp or OT event type. Val lower threshold value to be read. XST_FAILURE if errorXST_SUCCESS if successful.
References XSYSMONPSV_TEMP_EVENT, XSYSMONPSV_DEVICE_TEMP_TH, XSYSMONPSV_OT_EVENT, XSYSMONPSV_OT_TEMP_TH, XSysMonPsv_ReadReg32.
Referenced by SysMonPsvIntrExample.
int XSysMonPsv_ReadSupplyProcessed(XSysMonPsv *InstancePtr, int Supply, float *Val)
Reads the voltage for the supply.
InstancePtr Pointer to the driver instance. Supply Voltage supply. Val Float value in Voltage. XST_FAILURE if errorXST_SUCCESS if successful.
References XSYSMONPSV_MAX_SUPPLIES, XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_INVALID_SUPPLY, XSysMonPsv_SupplyOffset, XSysMonPsv_ReadReg32, XSysMonPsv_SupplyRawToProcessed.
Referenced by SysMonPsvIntrExample, SysMonPsvPolledExample.
int XSysMonPsv_ReadSupplyRaw(XSysMonPsv *InstancePtr, u32 Supply, u32 *Val)
Reads the voltage for the supply in raw.
InstancePtr Pointer to the driver instance. Supply Voltage supply. Val Raw voltage. XST_FAILURE if errorXST_SUCCESS if successful.
References XSYSMONPSV_MAX_SUPPLIES, XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_INVALID_SUPPLY, XSysMonPsv_SupplyOffset, XSysMonPsv_ReadReg32.
Referenced by SysMonPsvIntrExample.
int XSysMonPsv_SetSupplyThresholdUpper(XSysMonPsv *InstancePtr, u32 Supply, u32 Val)
Sets the upper threshold voltage for the supply.
InstancePtr Pointer to the driver instance. Supply Voltage supply. Val Upper Threshold Value. XST_FAILURE if errorXST_SUCCESS if successful.
References XSysMonPsv_SupplyThreshOffset, XSYSMONPSV_EV_DIR_RISING, XSysMonPsv_WriteReg32.
Referenced by SysMonPsvIntrExample.
int XSysMonPsv_SetSupplyThresholdLower(XSysMonPsv *InstancePtr, int Supply, u32 Val)
Sets loser threshold voltage for the supply.
InstancePtr Pointer to the driver instance. Supply Voltage supply. Val Threshold Value. XST_FAILURE if errorXST_SUCCESS if successful.
References XSysMonPsv_SupplyThreshOffset, XSYSMONPSV_EV_DIR_FALLING, XSysMonPsv_WriteReg32.
Referenced by SysMonPsvIntrExample.
int XSysMonPsv_GetSupplyThresholdUpper(XSysMonPsv *InstancePtr, u32 Supply, u32 *Val)
Gets the upper threshold voltage for the supply.
InstancePtr Pointer to the driver instance. Supply Voltage supply. Val Threshold Value to be read. XST_FAILURE if errorXST_SUCCESS if successful.
References XSYSMONPSV_MAX_SUPPLIES, XSysMonPsv_SupplyThreshOffset, XSYSMONPSV_EV_DIR_RISING, XSysMonPsv_ReadReg32.
Referenced by SysMonPsvIntrExample.
int XSysMonPsv_GetSupplyThresholdLower(XSysMonPsv *InstancePtr, u32 Supply, u32 *Val)
Gets the lower threshold voltage for the supply.
InstancePtr Pointer to the driver instance. Supply Voltage supply. Val Threshold Value to be read. XST_FAILURE if error.XST_SUCCESS if successful.
References XSYSMONPSV_MAX_SUPPLIES, XSysMonPsv_SupplyThreshOffset, XSYSMONPSV_EV_DIR_FALLING, XSysMonPsv_ReadReg32.
Referenced by SysMonPsvIntrExample.
void XSysMonPsv_EnableTempAverage(XSysMonPsv *InstancePtr, int SatId, u8 Enable)
Enables or Disables temperature satellites averaging.
InstancePtr Pointer to the driver instance. SatId Temperature Satellite id, indexed from 1 to 64. Enable Enable/Disable flag. None
References XSysMonPsv_UpdateReg32, XSYSMONPSV_EN_AVG_REG8.
void XSysMonPsv_SetTempAverageRate(XSysMonPsv *InstancePtr, u8 AverageRate)
Sets temperature satellites average sampling rate value.
InstancePtr Pointer to the driver instance. AverageRate Average Sampling Rate Value to be set. None
References XSYSMONPSV_AVERAGE_0_SAMPLES, XSYSMONPSV_AVERAGE_2_SAMPLES, XSYSMONPSV_AVERAGE_4_SAMPLES, XSYSMONPSV_AVERAGE_8_SAMPLES, XSYSMONPSV_AVERAGE_16_SAMPLES, XSYSMONPSV_CONFIG0_TEMP_AVERAGE_SHIFT, XSysMonPsv_UpdateReg32, XSYSMONPSV_CONFIG0, XSYSMONPSV_CONFIG0_TEMP_AVERAGE_MASK.
int XSysMonPsv_GetTempAverageRate(XSysMonPsv *InstancePtr, u8 *AverageRate)
Gets temperature satellites average sampling rate value.
InstancePtr Pointer to the driver instance. AverageRate Average Sampling Rate Value to be read. XSYSMONPSV_INVALID if invalid value read.XST_SUCCESS if successful.
References XSysMonPsv_ReadReg32, XSYSMONPSV_CONFIG0, XSYSMONPSV_CONFIG0_TEMP_AVERAGE_MASK, XSYSMONPSV_CONFIG0_TEMP_AVERAGE_SHIFT, XSYSMONPSV_AVERAGE_0_SAMPLES, XSYSMONPSV_AVERAGE_2_SAMPLES, XSYSMONPSV_AVERAGE_4_SAMPLES, XSYSMONPSV_AVERAGE_8_SAMPLES, XSYSMONPSV_AVERAGE_16_SAMPLES, XSYSMONPSV_INVALID.
int XSysMonPsv_EnableSupplyAverage(XSysMonPsv *InstancePtr, XSysMonPsv_Supply Supply, u8 Enable)
Enables or Disables voltage supplies averaging.
InstancePtr Pointer to the driver instance. Supply Voltage supply. Enable Enable/Disable flag. XSYSMONPSV_INVALID if invalid supply given.XST_SUCCESS if successful.
References XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSYSMONPSV_INVALID_SUPPLY, XSYSMONPSV_INVALID, XSysMonPsv_UpdateReg32, XSYSMONPSV_EN_AVG_REG0.
void XSysMonPsv_SetSupplyAverageRate(XSysMonPsv *InstancePtr, u8 AverageRate)
Sets voltage supplies average sampling rate value.
InstancePtr Pointer to the driver instance. AverageRate Average Sampling Rate Value to be set. None
References XSYSMONPSV_AVERAGE_0_SAMPLES, XSYSMONPSV_AVERAGE_2_SAMPLES, XSYSMONPSV_AVERAGE_4_SAMPLES, XSYSMONPSV_AVERAGE_8_SAMPLES, XSYSMONPSV_AVERAGE_16_SAMPLES, XSYSMONPSV_CONFIG0_SUPPLY_AVERAGE_SHIFT, XSysMonPsv_UpdateReg32, XSYSMONPSV_CONFIG0, XSYSMONPSV_CONFIG0_SUPPLY_AVERAGE_MASK.
int XSysMonPsv_GetSupplyAverageRate(XSysMonPsv *InstancePtr, u8 *AverageRate)
Gets voltage supplies average sampling rate value.
InstancePtr Pointer to the driver instance. AverageRate Average Sampling Rate Value to be read. XSYSMONPSV_INVALID if invalid value read.XST_SUCCESS if successful.
References XSysMonPsv_ReadReg32, XSYSMONPSV_CONFIG0, XSYSMONPSV_CONFIG0_SUPPLY_AVERAGE_MASK, XSYSMONPSV_CONFIG0_SUPPLY_AVERAGE_SHIFT, XSYSMONPSV_AVERAGE_0_SAMPLES, XSYSMONPSV_AVERAGE_2_SAMPLES, XSYSMONPSV_AVERAGE_4_SAMPLES, XSYSMONPSV_AVERAGE_8_SAMPLES, XSYSMONPSV_AVERAGE_16_SAMPLES, XSYSMONPSV_INVALID.
void XSysMonPsv_IntrEnable(XSysMonPsv *InstancePtr, u32 Mask, u8 IntrNum)
Enables the specified interrupts in the device.
InstancePtr Pointer to the XSysMonPsv instance. Mask 32 bit-mask of the interrupts to be enabled. Bit positions of 1 will be enabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XSYSMONPSV_IER_* bits defined in xsysmonpsv_hw.h. IntrNum Interrupt enable register to be used. None.
References XSysMonPsv::IsReady, XSYSMONPSV_IER0_OFFSET, XSYSMONPSV_INTR_OFFSET, XSysMonPsv_WriteReg32.
void XSysMonPsv_IntrDisable(XSysMonPsv *InstancePtr, u32 Mask, u8 IntrNum)
Disables the specified interrupts in the device.
InstancePtr Pointer to the XSysMonPsv instance. Mask 32 bit-mask of the interrupts to be enabled. Bit positions of 1 will be disabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XSYSMONPSV_IDR_* bits defined in xsysmonpsv_hw.h. IntrNum Interrupt disable register to be used. None.
References XSysMonPsv::IsReady, XSYSMONPSV_IDR0_OFFSET, XSYSMONPSV_INTR_OFFSET, XSysMonPsv_WriteReg32.
u32 XSysMonPsv_IntrGetEnabled(XSysMonPsv *InstancePtr, u8 IntrNum)
Returns the enabled interrupts read from the Interrupt Mask Register (IMR).
Use the XSYSMONPSV_IMR0_* and XSYSMONPSV_IMR1_* constants defined in xsysmonpsv_hw.h to interpret the returned value. InstancePtr Pointer to the XSysMonPsv instance. IntrNum Interrupt enable register to be used A 32-bit value representing the contents of the Interrupt Mask Registers.
References XSysMonPsv::IsReady, XSYSMONPSV_IMR0_OFFSET, XSYSMONPSV_INTR_OFFSET, XSysMonPsv_ReadReg32.
u32 XSysMonPsv_IntrGetStatus(XSysMonPsv *InstancePtr)
Returns the interrupt status read from Interrupt Status Register(ISR).
Use the XSYSMONPSV_ISR* constants defined in xsysmonpsv_hw.h to interpret the returned value. InstancePtr Pointer to the XSysMonPsv instance. A 32-bit value representing the contents of the Interrupt Status Register (ISR).
References XSysMonPsv::IsReady, XSysMonPsv_ReadReg32, XSYSMONPSV_ISR_OFFSET.
void XSysMonPsv_IntrClear(XSysMonPsv *InstancePtr, u32 Mask)
Clears the specified interrupts in the Interrupt Status Register (ISR).
InstancePtr Pointer to the XSysMonPsv instance. Mask 32 bit-mask of the interrupts to be cleared. Bit positions of 1 will be cleared. Bit positions of 0 will not change the previous interrupt status.* None.
References XSysMonPsv::IsReady, XSysMonPsv_WriteReg32, XSYSMONPSV_ISR_OFFSET.
void XSysMonPsv_SetNewDataIntSrc(XSysMonPsv *InstancePtr, XSysMonPsv_Supply Supply, u32 Mask)
Sets a supply as a source new data interrupt.
InstancePtr Pointer to the XSysMonPsv instance. Supply Enum from the XSysMonPsv_Supply Mask 32 bit Mask for NEW_DATA_n fields in the interrupt registers None.
References XSYSMONPSV_INTR_NEW_DATA_MASK, XSysMonPsv_ReadReg32, XSYSMONPSV_NEW_DATA_INT_SRC, XSYSMONPSV_INTR_NEW_DATA_SHIFT, XSYSMONPSV_NEW_DATA_INT_SRC_ADDR_ID1_SHIFT, XSysMonPsv::Config, XSysMonPsv_Config::Supply_List, XSysMonPsv_WriteReg32.
XSysMonPsv_Config* XSysMonPsv_LookupConfig(void)
Looks for the device configuration based on the unique device ID.
The table XSysmonPsu_ConfigTable[] contains the configuration information for each device in the system.A pointer to the configuration table entry corresponding to the given device, or NULL if no match is found.