2ve_2vm/server/xloader_plat_secure.c
XLOADER_EFUSE_OBFUS_KEY
eFuse obfuscated key
XLOADER_BBRAM_OBFUS_KEY
BBRAM obfuscated key.
XLOADER_BH_OBFUS_KEY
Boot header obfuscated key.
XLOADER_INVALID_OBFUS_KEY
Invalid obfuscated key.
static int XLoader_RsaPssSignVeirfyKat(void)
This function runs the KAT for RSA PSS verification.
XST_SUCCESS on success and error code on failure
u32 XLoader_GetKekSrc(void)
This function updates KEK red key availability status from boot header.
Decryption Key source status.
References XLOADER_BBRAM_BLK_KEY, XLOADER_BBRAM_RED_KEY, XLOADER_BH_BLK_KEY, XLOADER_BHDR_RED_KEY, XLOADER_EFUSE_BLK_KEY, XLOADER_EFUSE_RED_KEY.
int XLoader_AesObfusKeySelect(u32 PdiKeySrc, u32 DecKeyMask, void *KeySrcPtr)
This function provides Obfuscated Aes Key source.
PdiKeySrc is the Key source given in Pdi DecKeyMask is the current DecKeyMask KeySrcPtr is the pointer to the calculated KeySrc XST_SUCCESS on success and error code on failure PdiKeySrc is the Key source given in Pdi DecKeyMask is the current DecKeyMask KeySrcPtr is the pointer to the calculated KeySrc XST_SUCCESS on success and error code on failure PdiKeySrc is the Key source given in Pdi. DecKeyMask is the current DecKeyMask. KeySrcPtr is the pointer to the calculated KeySrc. XST_SUCCESS on success and error code on failure.
References XLOADER_SEC_AES_KEK_DEC.
int XLoader_AddDeviceStateChangeToScheduler(void)
This function adds periodic checks of the device status change during secure boot.
XST_SUCCESS on success. XLOADER_ERR_ADD_TASK_SCHEDULER if failed to add task to scheduler.
References XLoader_CheckDeviceStateChange, XLOADER_DEVICE_STATE_POLL_INTERVAL, XLOADER_EFUSE_CACHE_JTAG_DIS_MASK, XLOADER_EFUSE_CACHE_SECURITY_CONTROL_OFFSET, XLoader_GetAHWRoT, XLoader_GetSHWRoT.
Referenced by XLoader_Init.
int XLoader_RsaKat(void)
This function runs the KAT for RSA.
XST_SUCCESS on success and error code on failure XST_SUCCESS on success and error code on failure
int XLoader_CheckDeviceStateChange(void *Arg)
This function checks the JTAG device state change.
When Secure gate is opened from close state this API raises an error, if the gate is closed and re-opened again this function recognizes the state change and performs the action configured. Arg is of pointer of void type. XST_SUCCESS on success and error code on failure
References XLoader_CheckAndUpdateSecureState, XLOADER_JTAG_SEC_GATE_CLOSE, XLOADER_JTAG_SEC_GATE_OPEN, XLOADER_PMC_TAP_JTAG_STATUS_0, XLOADER_PMC_TAP_JTAG_STATUS_DAP_STATUS_MASK.
Referenced by XLoader_AddDeviceStateChangeToScheduler, XLoader_UpdateHandler.
static void XLoader_I2Osp(u32 Integer, u32 Size, u8 *Convert)
This function converts a non-negative integer to an octet string of a specified length.
Integer is the variable in which input should be provided. Size holds the required size. Convert is a pointer in which output will be updated. None
int XLoader_MaskGenFunc(XSecure_Sha *ShaInstancePtr, u8 *Out, u32 OutLen, u8 *Input)
Mask generation function with SHA3.
ShaInstancePtr is pointer to the XSecure_Sha3 instance. Out is pointer in which output of this function will be stored. OutLen specifies the required length. Input is pointer which holds the input data for which mask should be calculated which should be 48 bytes length. XST_SUCCESS on success.Errorcode on failure.
int XLoader_CheckSecureStateAuth(volatile u32 *AHWRoT)
This function checks Secure State for Authentication.
AHWRoT - Buffer to store Secure state for authentication XST_SUCCESS on success.XLOADER_ERR_HWROT_BH_AUTH_NOT_ALLOWED if PPK is programmed and boot header authentication is enabled. AHWRoT - Buffer to store Secure state for authentication XST_SUCCESS on success. XLOADER_ERR_GLITCH_DETECTED if glitch is detected. AHWRoT - Buffer to store Secure state for authentication. XST_SUCCESS on success.XLOADER_ERR_HWROT_BH_AUTH_NOT_ALLOWED if PPK is programmed and boot header authentication is enabled. AHWRoT Buffer to store Secure state for authentication. XST_SUCCESS on success.XLOADER_ERR_GLITCH_DETECTED if glitch is detected.
References XLoader_CheckNonZeroPpk.
Referenced by XLoader_SetSecureState.