2vp_p/server/xloader_plat.c
XLOADER_TCM_0
TCM 0.
XLOADER_TCM_1
TCM 1.
XLOADER_RPU_GLBL_CNTL
RPU global control.
XLOADER_TCMCOMB_MASK
TCM combine mask.
XLOADER_TCMCOMB_SHIFT
TCM combine shift.
XLOADER_TRNG_DEVICE_ID
TRNG Device Id.
PLM_VP1802_POR_SETTLE_TIME
Flag indicates POR settle time for VP1802.
static void XLoader_A72Config(u32 CpuId, u32 ExecState, u32 VInitHi)
This function sets Aarch state and vector location for APU.
CpuId CPU ID. ExecState CPU execution state. VInitHi resembles highvec configuration for CPU.
static int XLoader_RequestTCM(u32 TcmId)
This function requests TCM_0_A, TCM_0_B, TCM_1_A and TCM_1_B depending upon input param and R5-0 and R5-1 cores as required for TCMs.
TcmId denotes TCM_0 or TCM_1. XST_SUCCESS on success.XLOADER_ERR_PM_DEV_TCM_0_A if device request for TCM_0_A is failed.XLOADER_ERR_PM_DEV_TCM_0_B if device request for TCM_0_B is failed.XLOADER_ERR_PM_DEV_TCM_1_A if device request for TCM_1_A is failed.XLOADER_ERR_PM_DEV_TCM_1_B if device request for TCM_1_B is failed.
static int XLoader_CheckHandoffCpu(const XilPdi *PdiPtr, const u32 DstnCpu)
This function is used to check whether cpu has handoff address stored in the handoff structure.
PdiPtr is pointer to XilPdi instance. DstnCpu is the cpu which needs to be checked. XST_SUCCESS if the DstnCpu is successfully added to Handoff list.XST_FAILURE if the DstnCpu is already added to Handoff list.
static int XLoader_GetLoadAddr(u32 DstnCpu, u64 *LoadAddrPtr, u32 Len)
This function updates the load address based on the destination CPU.
DstnCpu is destination CPU. LoadAddrPtr is the destination load address pointer. Len is the length of the partition. XST_SUCCESS on success.XLOADER_ERR_TCM_ADDR_OUTOF_RANGE if load address is out of range.
static int XLoader_DumpDdrmcRegisters(void)
This function prints DDRMC register details.
XST_SUCCESS on success.Error code on failure.
static int XLoader_InitTrngInstance(void)
This function initializes the Trng instance.
XST_SUCCESS on success.XLOADER_TRNG_INIT_FAIL if TRNG initialization fails.
int XLoader_UpdateDataMeasurement(const XilPdi *PdiPtr, u64 DataAddr, u32 DataLen)
This function updates the partition data to SHA engine for data measurement only if authentication or checksum is not enabled.
This functions updates the partition data to SHA engine for measurement.If authentication or checksum is enabled, nothing needs to be done as SHA engine would be in use for the authentication/checksum process. PdiPtr Pointer to the XilPdi structure. DataAddr Address of Data for measure the hash. DataLen Length of data for DataMeasument. XST_SUCCESS on success and error code on failure PdiPtr Pointer to the XilPdi structure. DataAddr Address of Data for measure the hash. DataLen Length of data for DataMeasument. XST_SUCCESS on success.Error code on failure. PdiPtr Pointer to the XilPdi structure. DataAddr Address of Data for measure the hash. DataLen Length of data for DataMeasument. XST_SUCCESS on success and error code on failure
References XLoader_ImageMeasureInfo::DataAddr, XLoader_ImageMeasureInfo::DataSize, XLoader_ImageMeasureInfo::Flags, XilPdi::ImageNum, XilPdi::ImagePrtnId, XilPdi::MetaHdr, XLoader_ImageMeasureInfo::PcrInfo, XilPdi::PrtnNum, XLoader_ImageMeasureInfo::SubsystemID, XLoader_DataMeasurement, XLOADER_IMAGE_FULL_AUTHENTICATED, XLOADER_MEASURE_UPDATE.
Referenced by XLoader_PrtnCopy.
XLoader_ImageInfoTbl * XLoader_GetImageInfoTbl(void)
This function provides ImageInfoTbl pointer.
Pointer to ImageInfoTbl Pointer to ImageInfoTbl.
References XLoader_ImageInfoTbl::Count.
Referenced by XLoader_GetImageInfoEntry, XLoader_LoadImageInfoTbl, XLoader_StoreImageInfo.
XLoader_ImageStore * XLoader_GetPdiList(void)
This function provides pointer to PdiList.
Pointer to PdiListpointer to PdiList Pointer to PdiList.
Referenced by XLoader_IsPdiAddrLookup, XLoader_ReadImageStoreCfg, XLoader_RestartImage.
XilPdi_ATFHandoffParams * XLoader_GetATFHandoffParamsAddr(void)
This function returns the ATFHandoffParams structure address to the caller.
Returns ATFHandoffParams structure address ATFHandoffParams structure address.
Referenced by XLoader_PdiInit, XLoader_SetATFHandoffParameters.
XilBootPdiInfo * XLoader_GetBootPdiInfo(void)
This function provides pointer to BootPDI Info.
pointer to BootPDI Info pointer to BootPDI Info.
Referenced by XLoader_RestartImage, Xloader_SaveBootPdiInfo.
int XLoader_StartImage(XilPdi *PdiPtr)
This function is used to start the subsystems in the PDI.
PdiPtr Pdi instance pointer XST_SUCCESS on success.XLOADER_ERR_WAKEUP_A72_0 if waking up the A72-0 failed during handoff.XLOADER_ERR_WAKEUP_A72_1 if waking up the A72-1 failed during handoff.XLOADER_ERR_WAKEUP_R5_0 if waking up the R5-0 failed during handoff.XLOADER_ERR_WAKEUP_R5_1 if waking up the R5-1 failed during handoff.XLOADER_ERR_WAKEUP_R5_L if waking up the R5-L failed during handoff.XLOADER_ERR_WAKEUP_PSM if waking up the PSM failed during handoff.XLOADER_ERR_CONFIG_SUBSYSTEM if subsystem peripheral pre-allocation fails during handoff. PdiPtr Pdi instance pointer XST_SUCCESS on success.XLOADER_ERR_WAKEUP_R52_0 if waking up the R52_0 failed during handoff.XLOADER_ERR_WAKEUP_R52_1 if waking up the R52_1 failed during handoff.XLOADER_ERR_WAKEUP_A78_0 if waking up the A78_0 failed during handoff.XLOADER_ERR_WAKEUP_A78_1 if waking up the A78_1 failed during handoff.XLOADER_ERR_WAKEUP_A78_2 if waking up the A78_2 failed during handoff.XLOADER_ERR_WAKEUP_A78_3 if waking up the A78_3 failed during handoff.XLOADER_ERR_WAKEUP_ASU if waking up the ASU failed during handoff. PdiPtr Pdi instance pointer. XST_SUCCESS on success.XLOADER_ERR_WAKEUP_A72_0 if waking up the A72-0 failed during handoff.XLOADER_ERR_WAKEUP_A72_1 if waking up the A72-1 failed during handoff.XLOADER_ERR_WAKEUP_R5_0 if waking up the R5-0 failed during handoff.XLOADER_ERR_WAKEUP_R5_1 if waking up the R5-1 failed during handoff.XLOADER_ERR_WAKEUP_R5_L if waking up the R5-L failed during handoff.XLOADER_ERR_WAKEUP_PSM if waking up the PSM failed during handoff.XLOADER_ERR_CONFIG_SUBSYSTEM if subsystem peripheral pre-allocation fails during handoff. PdiPtr Pdi instance pointer XST_SUCCESS on success.XLOADER_ERR_WAKEUP_R52_0 if waking up the R52_0 failed during handoff.XLOADER_ERR_WAKEUP_R52_0 if waking up the R52_1 failed during handoff.XLOADER_ERR_WAKEUP_A78_0 if waking up the A78_0 failed during handoff.XLOADER_ERR_WAKEUP_A78_1 if waking up the A78_1 failed during handoff.XLOADER_ERR_WAKEUP_A78_2 if waking up the A78_2 failed during handoff.XLOADER_ERR_WAKEUP_A78_3 if waking up the A78_3 failed during handoff.XLOADER_ERR_WAKEUP_PSM if waking up the PSM failed during handoff.XLOADER_ERR_CONFIG_SUBSYSTEM if subsystem peripheral pre-allocation fails during handoff.
References XLoader_HandoffParam::CpuSettings, XLoader_HandoffParam::HandoffAddr, XilPdi::HandoffParam, XilPdi::ImageNum, XilPdi::MetaHdr, XilPdi::NoOfHandoffCpus, XLoader_Printf.
Referenced by XLoader_RestartImage.
int XLoader_SecureConfigMeasurement(XLoader_SecureParams *SecurePtr, u32 PcrInfo, u32 *DigestIndex, u32 OverWrite)
This function measures the Secure Configuration that is SPK, SPK ID and Encryption Revoke ID and extends to the specified PCR.
SecurePtr Pointer to the XLoader_SecureParams instance. PcrInfo Provides the PCR number and Measurement Index to be extended. DigestIndex Pointer to the DigestIndex across the PCR OverWrite TRUE or FALSE to overwrite the extended digest or not XST_SUCCESS on success.XLOADER_ERR_SECURE_CONFIG_MEASUREMENT if error in Secure config measurement. SecurePtr is pointer to the XLoader_SecureParams instance. PcrInfo provides the PCR number and Measurement Index to be extended. DigestIndex is pointer to the DigestIndex across the PCR. OverWrite TRUE or FALSE to overwrite the extended digest or not. XST_SUCCESS on success.XLOADER_ERR_SECURE_CONFIG_MEASUREMENT if error in Secure config measurement. SecurePtr is pointer to the XLoader_SecureParams instance. PcrInfo provides the PCR number and Measurement Index to be extended. DigestIndex is pointer to the DigestIndex across the PCR OverWrite TRUE or FALSE to overwrite the extended digest or not XST_SUCCESS on success.XLOADER_ERR_SECURE_CONFIG_MEASUREMENT if error in Secure config measurement.
References XLoader_SecureParams::IsAuthenticated, XLoader_SecureParams::IsEncrypted, XLOADER_EFUSE_ROM_RSVD_AUTH_KEYS_TO_HASH_MASK, XLOADER_EFUSE_ROM_RSVD_AUTH_KEYS_TO_HASH_SHIFT, XLOADER_EFUSE_ROM_RSVD_CACHE_ADDRESS.
int XLoader_MeasureNLoad(XilPdi *PdiPtr)
This function measures the partition hashes.
This function measures the partition hashes from the hash block. PdiPtr is pointer to XilPdi instance XST_SUCCESS on success.XLOADER_ERR_DATA_MEASUREMENT if error in data measurement. PdiPtr is pointer to XilPdi instance. XST_SUCCESS on success.XLOADER_ERR_DATA_MEASUREMENT if error in data measurement.
References XLoader_ImageMeasureInfo::DataAddr, XLoader_ImageMeasureInfo::DataSize, XilPdi::DigestIndex, XLoader_ImageMeasureInfo::Flags, XilPdi::ImageNum, XilPdi::MetaHdr, XLoader_ImageMeasureInfo::PcrInfo, XilPdi::PrtnNum, XLoader_ImageMeasureInfo::SubsystemID, XIH_MAX_PRTNS, XLoader_DataMeasurement, XLOADER_IMAGE_FULL_AUTHENTICATED, XLOADER_IMAGE_PARTIALLY_AUTHENTICATED, XLoader_LoadImagePrtns, XLOADER_MEASURE_FINISH, XLOADER_MEASURE_START, XLOADER_MEASURE_UPDATE, XLOADER_PCR_INVALID_VALUE, XLOADER_PCR_MEASUREMENT_INDEX_MASK, XLOADER_PCR_MEASUREMENT_INDEX_SHIFT.
Referenced by XLoader_LoadImage.
int XLoader_DataMeasurement(XLoader_ImageMeasureInfo *ImageInfo)
This function measures the data by calculating SHA3 hash.
ImageInfo Pointer to the XLoader_ImageMeasureInfo structure XST_SUCCESS on successfully measuring the dataXLOADER_ERR_DATA_MEASUREMENT if error in data measurement. ImageInfo Pointer to the XLoader_ImageMeasureInfo structure. XST_SUCCESS on success.XLOADER_ERR_DATA_MEASUREMENT if error in data measurement. ImageInfo Pointer to the XLoader_ImageMeasureInfo structure. XST_SUCCESS on successfully measuring the data.XLOADER_ERR_DATA_MEASUREMENT if error in data measurement.
References XLoader_ImageMeasureInfo::DataAddr, XLoader_ImageMeasureInfo::DataSize, XLoader_ImageMeasureInfo::Flags, XLoader_ImageMeasureInfo::PcrInfo, XLOADER_MEASURE_FINISH, XLOADER_MEASURE_START, XLOADER_MEASURE_UPDATE, XLOADER_PCR_INVALID_VALUE, XLOADER_PCR_NUMBER_MASK.
Referenced by XLoader_HdrMeasurement, XLoader_MeasureNLoad, XLoader_UpdateDataMeasurement.
void XLoader_SetATFHandoffParameters(const XilPdi_PrtnHdr *PrtnHdr)
This function sets the handoff parameters to the ARM Trusted Firmware(ATF).
Some of the inputs for this are taken from image partition header. A pointer to the structure containing these parameters is stored in the PMC_GLOBAL.GLOBAL_GEN_STORAGE4 register, which ATF reads. PrtnHdr is pointer to Partition header details Some of the inputs for this are taken from image partition header. A pointer to the structure containing these parameters is stored in the PMC_GLOBAL.GLOBAL_GEN_STORAGE4 register, which ATF reads. PrtnHdr is pointer to Partition header details.
References XLoader_GetATFHandoffParamsAddr.
Referenced by XLoader_ProcessElf.
int XLoader_GetSDPdiSrcNAddr(u32 SecBootMode, XilPdi *PdiPtr, u32 *PdiSrc, u64 *PdiAddr)
This function is used to get PdiSrc and PdiAddr for Secondary SD boot modes.
SecBootMode is the secondary boot mode value PdiPtr Pointer to PDI instance PdiSrc Pointer to the source of PDI PdiAddr is the pointer to the address of the Pdi XST_SUCCESS on success.XLOADER_ERR_UNSUPPORTED_SEC_BOOT_MODE on unsupported secondary bootmode. SecBootMode is the secondary boot mode value PdiPtr Pointer to the PDI instance PdiSrc is pointer to the source of PDI PdiAddr is the pointer to the address of the Pdi XST_SUCCESS on success.XLOADER_ERR_UNSUPPORTED_SEC_BOOT_MODE on unsupported secondary bootmode. SecBootMode is the secondary boot mode value. PdiPtr Pointer to PDI instance. PdiSrc Pointer to the source of PDI. PdiAddr is the pointer to the address of the Pdi. XST_SUCCESS on success.XLOADER_ERR_UNSUPPORTED_SEC_BOOT_MODE on unsupported secondary bootmode.
References XilPdi::MetaHdr, XLOADER_PDI_SRC_SD0, XLOADER_PDI_SRC_SD1, XLOADER_PDI_SRC_SD1_LS, XLOADER_SD_RAWBOOT_MASK.
int XLoader_ProcessElf(XilPdi *PdiPtr, const XilPdi_PrtnHdr *PrtnHdr, XLoader_PrtnParams *PrtnParams, XLoader_SecureParams *SecureParams)
This function copies the elf partitions to specified destinations.
PdiPtr is pointer to XilPdi instance PrtnHdr is pointer to the partition header PrtnParams is pointer to the structure variable that contains parameters required to process the partition SecureParams is pointer to the instance containing security related params XST_SUCCESS on success.XLOADER_ERR_INVALID_ELF_LOAD_ADDR if the load address of the elf is invalid.XLOADER_ERR_PM_DEV_PSM_PROC if device request for PSM is failed.XLOADER_ERR_PM_DEV_IOCTL_RPU0_SPLIT if IOCTL call to set RPU0 in split mode fails.XLOADER_ERR_PM_DEV_IOCTL_RPU1_SPLIT if IOCTL call to set RPU1 in split mode fails.XLOADER_ERR_PM_DEV_IOCTL_RPU0_LOCKSTEP if IOCTL call to set RPU0 in lockstep mode fails.XLOADER_ERR_PM_DEV_IOCTL_RPU1_LOCKSTEP if IOCTL call to set RPU1 in lockstep mode fails.XLOADER_ERR_INVALID_TCM_ADDR on Invalid TCM address for A72 elfs.XLOADER_ERR_INVALID_CPUID if invalid CPU id is selected. PdiPtr is pointer to XilPdi instance PrtnHdr is pointer to the partition header PrtnParams is pointer to the structure variable that contains parameters required to process the partition SecureParams is pointer to the instance containing security related params XST_SUCCESS on success.XLOADER_ERR_INVALID_ELF_LOAD_ADDR if load address of the elf is invalid.XLOADER_ERR_INVALID_R52_CLUSTER if invalid R52 cluster is selected.XLOADER_ERR_INVALID_CPUID if invalid CPU id is selected. PdiPtr is pointer to XilPdi instance. PrtnHdr is pointer to the partition header. PrtnParams is pointer to the structure variable that contains parameters required to process the partition. SecureParams is pointer to the instance containing security related params. XST_SUCCESS on success.XLOADER_ERR_INVALID_ELF_LOAD_ADDR if the load address of the elf is invalid.XLOADER_ERR_PM_DEV_PSM_PROC if device request for PSM is failed.XLOADER_ERR_PM_DEV_IOCTL_RPU0_SPLIT if IOCTL call to set RPU0 in split mode fails.XLOADER_ERR_PM_DEV_IOCTL_RPU1_SPLIT if IOCTL call to set RPU1 in split mode fails.XLOADER_ERR_PM_DEV_IOCTL_RPU0_LOCKSTEP if IOCTL call to set RPU0 in lockstep mode fails.XLOADER_ERR_PM_DEV_IOCTL_RPU1_LOCKSTEP if IOCTL call to set RPU1 in lockstep mode fails.XLOADER_ERR_INVALID_TCM_ADDR on Invalid TCM address for A72 elfs. XLOADER_ERR_INVALID_CPUID if invalid CPU id is selected. PdiPtr is pointer to XilPdi instance. PrtnHdr is pointer to the partition header. PrtnParams is pointer to the structure variable that contains parameters required to process the partition. SecureParams is pointer to the instance containing security related params. XST_SUCCESS on success.XLOADER_ERR_INVALID_ELF_LOAD_ADDR if the load address of the elf is invalid.XLOADER_ERR_PM_DEV_PSM_PROC if device request for PSM is failed.XLOADER_ERR_PM_DEV_IOCTL_RPU0_SPLIT if IOCTL call to set RPU0 in split mode fails.XLOADER_ERR_PM_DEV_IOCTL_RPU1_SPLIT if IOCTL call to set RPU1 in split mode fails.XLOADER_ERR_PM_DEV_IOCTL_RPU0_LOCKSTEP if IOCTL call to set RPU0 in lockstep mode fails.XLOADER_ERR_PM_DEV_IOCTL_RPU1_LOCKSTEP if IOCTL call to set RPU1 in lockstep mode fails.XLOADER_ERR_INVALID_TCM_ADDR on Invalid TCM address for A72 elfs. PdiPtr is pointer to XilPdi instance PrtnHdr is pointer to the partition header PrtnParams is pointer to the structure variable that contains parameters required to process the partition SecureParams is pointer to the instance containing security related params XST_SUCCESS on success.XLOADER_ERR_INVALID_ELF_LOAD_ADDR if load address of the elf is invalid.XLOADER_ERR_PM_DEV_PSM_PROC if device request for PSM is failed.XLOADER_ERR_INVALID_R52_CLUSTER if invalid R52 cluster is selected.XLOADER_ERR_INVALID_CPUID if invalid CPU id is selected.
References XilPdi::DelayHandoff, XLoader_DeviceCopy::DestAddr, XLoader_PrtnParams::DeviceCopy, XLoader_PrtnParams::DstnCpu, XLoader_ClearATFHandoffParams, XLoader_PrtnCopy, XLOADER_R5_0_TCM_A_BASE_ADDR, XLOADER_R5_0_TCM_A_END_ADDR, XLOADER_R5_0_TCM_B_BASE_ADDR, XLOADER_R5_0_TCM_B_END_ADDR, XLOADER_R5_1_TCM_A_BASE_ADDR, XLOADER_R5_1_TCM_A_END_ADDR, XLOADER_R5_1_TCM_B_BASE_ADDR, XLOADER_R5_1_TCM_B_END_ADDR, XLOADER_R5_LS_TCM_END_ADDR, XLOADER_RPU_GLBL_CNTL, XLoader_SetATFHandoffParameters, XLOADER_TCM_0, XLOADER_TCM_1, XLOADER_TCMCOMB_MASK, XLOADER_TCMCOMB_SHIFT, XLoader_UpdateHandoffParam.
int XLoader_UpdateHandoffParam(XilPdi *PdiPtr)
This function is used to update the handoff parameters.
PdiPtr is pointer to XilPdi instance XST_SUCCESS on success.XLOADER_ERR_NUM_HANDOFF_CPUS when number of CPUs exceed max count. PdiPtr is pointer to XilPdi instance XST_SUCCESS on success.XLOADER_ERR_NUM_HANDOFF_CPUS if number of CPUs exceeds max count. PdiPtr is pointer to XilPdi instance. XST_SUCCESS on success.XLOADER_ERR_NUM_HANDOFF_CPUS when number of CPUs exceed max count.
References XLoader_HandoffParam::CpuSettings, XLoader_HandoffParam::HandoffAddr, XilPdi::HandoffParam, XilPdi::MetaHdr, XilPdi::NoOfHandoffCpus, XilPdi::PrtnNum, XLOADER_MAX_HANDOFF_CPUS.
Referenced by XLoader_ProcessElf.
u8 XLoader_SkipMJtagWorkAround(XilPdi *PdiPtr)
This function checks if MJTAG workaround partition needs to be skipped.
PdiPtr is pointer to PDI instance TRUE if MTAG workaround partition needs to be skipped, else FALSE PdiPtr is pointer to PDI instance. TRUE if MTAG workaround partition needs to be skipped, else FALSE.
References XilPdi::ImageNum, XilPdi::MetaHdr, XilPdi::PdiSrc, XLOADER_PDI_SRC_JTAG.
int XLoader_ProcessDeferredError(void)
This function checks if MJTAG workaround is required.
XLOADER_ERR_DEFERRED_CDO_PROCESS on error while processing CDO but error is deferred till whole CDO processing is completed.
References XLoader_DumpDdrmcRegisters.
void XLoader_PerformInternalPOR(void)
This function check conditions and perform internal POR for VP1802 and VP1502 device if required.
References PdiSrc_t, PLM_VP1802_POR_SETTLE_TIME, XLOADER_PDI_SRC_JTAG, XLOADER_PDI_SRC_SMAP.
void XLoader_ShaInstance1Reset(void)
This Function does the following:
It resets the SHA instance 1.It puts the SHA instance 1 into initialized state.
Referenced by XLoader_LoadImage.
int XLoader_PlatInit(void)
This function initializes the loader with platform specific initializations.
XST_SUCCESS on success and error code on failure XST_SUCCESS always. XST_SUCCESS on success.Error code on failure.