xloader_kat_apis
static void XLoader_ClearKatStatusOnCfg(XilPdi *PdiPtr, u32 PlmKatMask)
This function masks the KAT status based on KatOnConfig value when PDI type is partial pdi.
PdiPtr is pointer to the XilPdi instance PlmKatMask is the mask of the KAT that is going to run
int XLoader_Sha3Kat(XilPdi *PdiPtr)
This function runs SHA3 KAT.
PdiPtr is pointer to the xilpdi instance XST_SUCCESS on successXST_FAILURE if setting SHA3 data context lost failsXLOADER_ERR_KAT_FAILED on SHA3 KAT failure
References XilPdi::PlmKatStatus, XLoader_ClearKatOnPPDI.
Referenced by XLoader_PdiInit.
void XLoader_ClearKatOnPPDI(XilPdi *PdiPtr, u32 PlmKatMask)
This function updates the KAT status.
PdiPtr is pointer to the XilPdi instance PlmKatMask is the mask of the KAT that is going to run
References XilPdi::PdiType.
Referenced by XLoader_AesKatTest, XLoader_Sha3Kat.
int XLoader_AesKatTest(XLoader_SecureParams *SecurePtr)
This function performs KAT test on AES crypto Engine.
SecurePtr Pointer to the XLoader_SecureParams instance. XST_SUCCESS on successXST_FAILURE if setting AES data context lost failsXLOADER_ERR_KAT_FAILED on AES DPACM or AES decrypt KAT failure
References XLoader_SecureParams::AesInstPtr, XLoader_SecureParams::PdiPtr, XilPdi::PlmKatStatus, XLoader_ClearKatOnPPDI, XLOADER_EFUSE_SEC_DPA_DIS_MASK, XLOADER_EFUSE_SEC_MISC1_OFFSET.