xloader_server_apis
XCframe XLoader_CframeIns
CFRAME Driver Instance.
u8 DdrRequested
static int XLoader_ReadAndValidateHdrs(XilPdi *PdiPtr, u32 RegValue, u64 PdiAddr)
This function reads bootheader and metaheader and validates them.
PdiPtr is instance pointer pointing to PDI details RegValue is the value of the Multiboot register PdiAddr is the PDI address XST_SUCCESS on success.XLOADER_ERR_IMGHDR_TBL if PLM is unable to read image header table.XLOADER_ERR_MEMSET_SECURE_PTR if failed to create instance for secure pointer.XLOADER_ERR_UNSUPPORTED_PDI_VER on PDI version used in secure operations is unsupported.XLOADER_ERR_SECURE_NOT_ENABLED on attempt to secure boot in an excluded secure critical code.XLOADER_ERR_GEN_IDCODE on ID code mismatch.XLOADER_ERR_IMGHDR if image header checksum fails.XLOADER_ERR_PRTNHDR if partition header checksum fails.XLOADER_ERR_SECURE_METAHDR if secure metaheader validation fails.
static int XLoader_LoadAndStartSubSystemImages(XilPdi *PdiPtr)
This function is used to load and start images.
It reads meta header, loads the images as present in the PDI and starts images based on hand-off information present in PDI. PdiPtr is Pdi instance pointer XST_SUCCESS on success.XLOADER_ERR_DELAY_ATTRB if both delay handoff and delay load are set for the same image.XLOADER_ERR_NUM_HANDOFF_CPUS if number of CPUs exceed max count.
static int XLoader_LoadAndStartSubSystemPdi(XilPdi *PdiPtr)
This function is used to load the primary and secondary PDIs.
PdiPtr is Pdi instance pointer XST_SUCCESS on success and error code on failure
static int XLoader_LoadAndStartSecondaryPdi(XilPdi *PdiPtr)
This function is used to load the primary and secondary PDIs.
PdiPtr is Pdi instance pointer XST_SUCCESS on success.XLOADER_ERR_UNSUPPORTED_SEC_BOOT_MODE on unsupported secondary boot mode.XLOADER_ERR_MEMSET_PDIPTR if failed to create instance for PdiPtr.
static int XLoader_VerifyImgInfo(const XLoader_ImageInfo *ImageInfo)
This function validates the UIDs in Image Header.
ImageInfo is pointer to the image info in image XST_SUCCESS on success.XLOADER_ERR_DEV_NOT_DEFINED if Device ID of the image to be loaded is not defined.XLOADER_ERR_PARENT_QUERY_VERIFY if Failed to Query Parent ID of an image while verifying its Image UIDs.XLOADER_ERR_INVALID_PARENT_IMG_ID when Invalid ParentImgID is obtained when queried for parent ImgID.XLOADER_ERR_NO_VALID_PARENT_IMG_ENTRY if No Valid Parent Image Entry is found in the ImageInfo Table.XLOADER_ERR_INCOMPATIBLE_CHILD_IMAGE if child image is not compatible with parent image.
static int XLoader_GetChildRelation(u32 ChildImgID, u32 ParentImgID, u32 *IsChild)
This function checks if the given ImgID is a child of Parent ImgID.
ChildImgID is the current ImgID whose relation is to be checked ParentImgID is the ImgID with which the hierarchical ImgIDs are compared in order to get the correct parent-child relationship IsChild is the pointer to the Relation that has to be returned, TRUE if it is a Child, else FALSE XST_SUCCESS on success.XLOADER_ERR_PARENT_QUERY_RELATION_CHECK if parent query fails while checking child relation.
static int XLoader_InvalidateChildImgInfo(u32 ParentImgID, u32 *ChangeCount)
This function invalidates the child image info entries corresponding to the parent image id in the ImageInfo Table.
ParentImgID whose corresponding child image info entries are invalidated ChangeCount points to ChangeCount that has to be modified XST_SUCCESS on success and error code on failure
static int XLoader_ReloadImage(XilPdi *PdiPtr, u32 ImageId, const u32 *FuncID)
This function is used to reload the image only in PDI.
This function will take ImageId as an input and based on the subsystem info available, it will read the image partitions and loads them. PdiPtr is Pdi instance pointer ImageId Id of the image present in PDI FuncID is verified with the FuncID present in PDI XST_SUCCESS on success.XLOADER_ERR_IMG_ID_NOT_FOUND if image id is not found in subsystem when reloading image.XLOADER_ERR_FUNCTION_ID_MISMATCH when Function ID given while loading Image from DDR is not matching with the ID stored in Image Header.
static int XLoader_ClearKeys(XilPdi *PdiPtr)
This function clears AES keys when RedKeyClear is set in PMCRAM.
PdiPtr Pointer to PdiInstance XST_SUCCESS on successErrorCode on failure
static int XLoader_ReadIHsAndPHs(XLoader_SecureParams *SecurePtr)
This function reads the Image Headers and Partition Headers.
SecurePtr is pointer to XLoader_SecureParams XST_SUCCESS on successful read. XST_FAILURE on unsuccessful read.
static int XLoader_VerifyIHsAndPHs(XLoader_SecureParams *SecurePtr)
This function verifies Image headers and Partition headers.
SecurePtr is pointer to XLoader_SecureParams XST_SUCCESS on successful verification. XST_FAILURE on unsuccessful verification.
int XLoader_Init(void)
This function initializes the loader instance and registers loader commands with PLM.
XST_SUCCESS on success and error code on failure
References XLoader_AddDeviceStateChangeToScheduler, XLoader_CframeInit, XLOADER_CL_BEFORE_BOOT, XLoader_IntrInit, XLoader_SetSecureState.
int XLoader_PdiInit(XilPdi *PdiPtr, PdiSrc_t PdiSource, u64 PdiAddr)
This function initializes the PDI instance with required details and read the meta header.
PdiPtr is instance pointer pointing to PDI details PdiSource is source of PDI. It can be any boot Device or DDR PdiAddr is the address at which PDI is located in the PDI source XST_SUCCESS on success.XLOADER_UNSUPPORTED_BOOT_MODE on unsupported boot mode.XLOADER_ERR_UNSUPPORTED_USB_PRIMARY if USB is used as primary boot mode.
References XilPdi::ClearAtfHandoff, XLoader_DeviceOps::Copy, PdiSrcMap::Index, XLoader_DeviceOps::Init, XilPdi::MetaHdr, XilPdi::PdiIndex, XilPdi::PdiSrc, PdiSrc_t, XilPdi::PdiType, XilPdi::SlrType, XLOADER_GET_PDISRC_INFO, XLoader_GetATFHandoffParamsAddr, XLoader_GetPdiInstance, XLOADER_PDI_SRC_USB, XLOADER_PDI_TYPE_FULL, XLOADER_PDISRC_FLAGS_MASK, XLOADER_SD_RAWBOOT_MASK, XLoader_Sha3Kat, XLOADER_SSIT_MONOLITIC.
Referenced by XLoader_InitPdiInstanceForExtractMHAndOptData, XLoader_LoadAsuImage, XLoader_LoadLpdAndPsmElf, XLoader_LoadPdi, XLoader_RestartImage.
int XLoader_LoadPdi(XilPdi *PdiPtr, PdiSrc_t PdiSrc, u64 PdiAddr)
This function provides loading PDI.
PdiPtr is the instance pointer that points to PDI details PdiSrc is source of PDI. It can be in Boot Device or DDR. PdiAddr is the address at PDI is located in the PDI source XST_SUCCESS on success and error code on failure
References XLoader_PdiInit.
XLoader_ImageInfo* XLoader_GetImageInfoEntry(u32 ImgID)
This function returns the ImageInfoEntry by checking if an entry exists for that particular ImgId in the ImgInfoTbl.
ImgID of the the entry that has to be stored Address of ImageInfo Entry in the table
References XLoader_ImageInfoTbl::Count, XLoader_ImageInfo::ImgID, XLoader_GetImageInfoTbl, XLOADER_IMAGE_INFO_TBL_MAX_NUM, XLOADER_INVALID_IMG_ID.
Referenced by XLoader_StoreImageInfo.
int XLoader_StoreImageInfo(const XLoader_ImageInfo *ImageInfo)
This function stores the ImageInfo to Image Info Table.
ImageInfo is a Pointer to ImageInfo that has to be written. XST_SUCCESS on success.XLOADER_ERR_INVALIDATE_CHILD_IMG when invalidating child image entry.XLOADER_ERR_IMAGE_INFO_TBL_OVERFLOW when image info table overflows.XPLMI_ERR_MEMCPY_IMAGE_INFO if failed to copy image info to memory.
References XLoader_ImageInfoTbl::Count, XLoader_ImageInfo::ImgID, XLoader_ImageInfoTbl::IsBufferFull, XLoader_ImageInfo::UID, XLoader_GetImageInfoEntry, XLoader_GetImageInfoTbl, XLOADER_INVALID_IMG_ID, XLOADER_INVALID_UID.
Referenced by XLoader_LoadImage.
int XLoader_LoadImageInfoTbl(u64 DestAddr, u32 MaxSize, u32 *NumEntries)
This function loads the ImageInfo table to the given memory address.
DestAddr is the 64 bit Destination Address MaxSize is the max size of Buffer present at Destination Address NumEntries that are loaded from the Image Info Table XST_SUCCESS on success.XLOADER_ERR_INVALID_DEST_IMGINFOTBL_SIZE if destination buffer size is less than the current length of the image info table.XLOADER_ERR_IMAGE_INFO_TBL_FULL if image info table is full.
References XLoader_ImageInfoTbl::Count, XLoader_ImageInfoTbl::IsBufferFull, XLOADER_ERR_IMAGE_INFO_TBL_FULL, XLOADER_ERR_INVALID_DEST_IMGINFOTBL_SIZE, XLoader_GetImageInfoTbl.
int XLoader_LoadImage(XilPdi *PdiPtr)
This function is used load a image in PDI.
PDI can have multiple images present in it. This can be used to load a single image like PL, APU, RPU. This will load all the partitions that are present in that image. PdiPtr is Pdi instance pointer XST_SUCCESS on success.XLOADER_ERR_SEM_STOP_SCAN if unable to stop SEM scan.XLOADER_ERR_CONFIG_SUBSYSTEM if subsystem configuration fails.XLOADER_ERR_SEM_INIT if unable to start the SEM scan.
References XilPdi::DelayLoad, XilPdi::ImageNum, XilPdi::MetaHdr, XilPdi::PdiSrc, XilPdi::PdiType, XLOADER_INVALID_IMG_ID, XLoader_MeasureNLoad, XLOADER_PDI_SRC_JTAG, XLOADER_PDI_TYPE_FULL, XLoader_SetJtagTapToReset, XLoader_ShaInstance1Reset, XLoader_StoreImageInfo.
int XLoader_RestartImage(u32 ImageId, u32 *FuncID)
This function is used to restart the image in PDI.
This function will take ImageId as an input and based on the subsystem info available, it will read the image partitions, loads them and hand-off to the required CPUs as part of the image load. ImageId Id of the image present in PDI FuncID is verified with the FuncID present in PDI XST_SUCCESS on success and error code on failure
References XLoader_ImageStore::Count, XLoader_ImageStore::ImgList, XLoader_PdiInfo::PdiAddr, XilPdi::PdiSrc, XilBootPdiInfo::PdiSrc, XilPdi::PdiType, XLoader_GetBootPdiInfo, XLoader_GetPdiInstance, XLoader_GetPdiList, XLOADER_PDI_LOAD_COMPLETE, XLOADER_PDI_SRC_DDR, XLOADER_PDI_SRC_JTAG, XLOADER_PDI_SRC_SMAP, XLOADER_PDI_TYPE_FULL, XLoader_PdiInit, XLoader_StartImage.
int XLoader_IdCodeCheck(const XilPdi_ImgHdrTbl *ImgHdrTbl)
This function performs the checks of IDCODE and EXTENDED IDCODE.
It also supports bypass of subset of these checks. ImgHdrTbl pointer to the image header table. XST_SUCCESS on success.XLOADER_ERR_EXT_ID_SI if extended ID code is mismatched with device.XLOADER_ERR_IDCODE on ID code mismatch.XLOADER_ERR_EXT_IDCODE on extended ID code mismatch.
References XLOADER_ERR_EXT_ID_SI, XLOADER_ERR_EXT_IDCODE, XLOADER_ERR_IDCODE.
int XLoader_ReadImageStoreCfg(void)
This function is used to read the Image Store DDR Memory Addr.
XST_SUCCESS on success and error code on failure
References XLoader_ImageStore::ImgList, XLoader_PdiInfo::PdiAddr, XLoader_ImageStore::PdiImgStrAddr, XLoader_ImageStore::PdiImgStrSize, XLOADER_ERR_INVALID_IMAGE_STORE_ADDRESS, XLoader_GetPdiList, XLOADER_IMG_STORE_INVALID_ADDR, XLOADER_IMG_STORE_INVALID_SIZE.
int XLoader_IsPdiAddrLookup(u32 PdiId, u64 *PdiAddr)
This function is used to read the Address based-on PDI Id from Image Store.
PdiId Index of the PDI stored PdiAddr Pointer to the PDI address XST_SUCCESS on successXLOADER_ERR_PDI_LIST_EMPTY if PDI list is emptyXLOADER_ERR_PDI_ADDR_NOT_FOUND if PDI ID not found in list
References XLoader_ImageStore::Count, XLoader_ImageStore::ImgList, XLoader_PdiInfo::PdiAddr, XLoader_PdiInfo::PdiId, XLOADER_ERR_PDI_ADDR_NOT_FOUND, XLOADER_ERR_PDI_LIST_EMPTY, XLoader_GetPdiList.
void Xloader_SaveBootPdiInfo(XilPdi *BootPdiPtr)
This function is used to save the BootPDI info.
BootPdiPtr Pointer to the PDI instance
References XilPdi::DecKeySrc, XilBootPdiInfo::DecKeySrc, XilPdi::MetaHdr, XilBootPdiInfo::MetaHdrOfst, XilPdi::PdiSrc, XilBootPdiInfo::PdiSrc, XilPdi::PlmKatStatus, XilBootPdiInfo::PlmKatStatus, XLoader_GetBootPdiInfo.
XilPdi* XLoader_GetPdiInstance(void)
This function provides PdiInstance pointer.
Pointer to PdiInstance
Referenced by XLoader_LoadAsuImage, XLoader_LoadLpdAndPsmElf, XLoader_PdiInit, XLoader_RestartImage.
int XLoader_InitPdiInstanceForExtractMHAndOptData(XPlmi_Cmd *Cmd, XilPdi *PdiPtr, u64 SrcAddr, u64 DestAddr, u32 DestSize)
This function initializes PDI Instance pointer for extracting Metaheader and OptionalData.
Cmd Pointer to the command structure PdiPtr Pointer to PdiInstance SrcAddr Address of the PDI DestAddr Address of the destination buffer DestSize Size of the destination buffer XST_SUCCESS on successErrorCode on failure
References XLoader_DeviceOps::Copy, XLoader_DeviceOps::Init, XilPdi::IpiMask, XilPdi::MetaHdr, XilPdi::PdiType, XLoader_DeviceOps::Release, XLOADER_CMD_EXTRACT_METAHDR_PDISRC_MASK, XLOADER_ERR_INVALID_METAHEADER_DEST_ADDR, XLOADER_ERR_INVALID_METAHEADER_OFFSET, XLOADER_ERR_INVALID_METAHEADER_SRC_ADDR, XLOADER_ERR_INVALID_PDI_INPUT, XLOADER_GET_OPT_DATA_FLAG, XLOADER_PDI_SRC_DDR, XLOADER_PDI_SRC_IS, XLOADER_PDI_SRC_OSPI, XLoader_PdiInit.
int XLoader_ClearATFHandoffParams(XilPdi *PdiPtr)
This function clears ATF Handoff parameters in case of multi-partitions in APU subsystem.
PdiPtr Pointer to XilPdi instance XST_SUCCESS on successXST_FAILURE on failure
Referenced by XLoader_ProcessElf.
int XLoader_GetImageAndPrtnInfo(XilPdi *PdiPtr, u32 ImageId)
This function provides Image number and partition number of a given ImgId in the PDI instance.
PdiPtr Pdi instance pointer ImageId Image id of a subsystem - XST_SUCCESS on success XST_FAILURE on failure
References XilPdi::ImageNum, XilPdi::MetaHdr, XilPdi::PrtnNum.
Referenced by XLoader_LoadAsuImage, XLoader_LoadLpdAndPsmElf.
static int XLoader_EcdsaSignVerify(const XSecure_EllipticCrvTyp CrvType, const u8 *DataHash, const u8 *Key, const u32 KeySize, const u8 *Signature)
This function verifies the ECDSA signature provided with key components.
CrvType is the type of the ECDSA curve DataHash is pointer to the hash of the data to be authenticated Key is pointer to the ECDSA key. KeySize is the size of the public key component in bytes Signature is pointer to the ECDSA signature XST_SUCCESS on success.XLOADER_SEC_ECDSA_INVLD_KEY_COORDINATES on invalid key coordinated for ECDSA.XLOADER_SEC_ECDSA_AUTH_FAIL if failed to verify ECDSA signature.
static int XLoader_RsaSignVerify(u8 *MsgHash, XLoader_RsaKey *Key, u8 *Signature)
This function initializes the RSA module with provided key and verifies the signature.
MsgHash of the data to be authenticated. Key is pointer to the XSecure_Rsa instance. Signature is pointer to RSA signature for data to be authenticated. XST_SUCCESS on success.XLOADER_SEC_RSA_AUTH_FAIL if failed to verify RSA signature.
static int XLoader_AesDecryption(XLoader_SecureParams *SecurePtr, u64 SrcAddr, u64 DestAddr, u32 Size)
This function decrypts the data.
SecurePtr is pointer to the XLoader_SecureParams SrcAddr is address to the buffer where header/footer present DestAddr is the address to which header / footer is copied Size is the number of bytes to be copied XST_SUCCESS on success.XLOADER_SEC_AES_OPERATION_FAILED on AES operation failure.XLOADER_SEC_DPA_CM_ERR if failed to configure DPA CM.
static int XLoader_AesKeySelect(const XLoader_SecureParams *SecurePtr, XLoader_AesKekInfo *KeyDetails, XSecure_AesKeySrc *KeySrc)
This function helps in key selection.
SecurePtr is pointer to the XLoader_SecureParams KeyDetails is pointer to the key details. KeySrc is pointer to the key source to be updated as key source for decrypting. If key provided is KEK format, this API decrypts and provides the red key source. XST_SUCCESS on success.XLOADER_SEC_DEC_INVALID_KEYSRC_SEL on invalid key source selected for decryption.XLOADER_SEC_AES_KEK_DEC if failed to decrypt KEK.
static int XLoader_PpkCompare(const u32 EfusePpkOffset, const u8 *PpkHash)
This function compares calculated PPK hash with the efuse PPK hash.
EfusePpkOffset is PPK hash address of efuse. PpkHash is pointer to the PPK hash to be verified. XST_SUCCESS on success.XLOADER_SEC_PPK_HASH_COMPARE_FAIL if hash comparison failed.
static int XLoader_DecHdrs(XLoader_SecureParams *SecurePtr, XilPdi_MetaHdr *MetaHdr, u64 BufferAddr)
This function decrypts headers.
SecurePtr Pointer to the XLoader_SecureParams MetaHdr Pointer to the Meta header. BufferAddr Read whole headers to the mentioned buffer address XST_SUCCESS on success.XLOADER_ERR_HDR_NOT_ENCRYPTED image header or partition header is not encrypted.XLOADER_ERR_GLITCH_DETECTED if glitch is detected.XLOADER_ERR_HDR_AES_OP_FAIL if failed due to AES init or Decrypt init or key selection failure.XLOADER_SEC_EFUSE_DPA_CM_MISMATCH_ERROR Metahdr DpaCm & eFuse DpaCm values are not matched.XLOADER_SEC_DPA_CM_ERR if failed to configure DPA CM.XLOADER_ERR_HDR_AES_OP_FAIL if failed to initialize AES or Decrypt or key selection.XLOADER_ERR_HDR_AAD_UPDATE_FAIL if failed to update IHT as AAD during secure header decryption.XLOADER_ERR_HDR_DEC_FAIL if failed to decrypt IH/PH.
static int XLoader_SpkAuthentication(const XLoader_SecureParams *SecurePtr)
This function verifies SPK with PPK.
SecurePtr is pointer to the XLoader_SecureParams instance. XST_SUCCESS on success.XLOADER_SEC_SPK_HASH_CALCULATION_FAIL if SPK hash calculation fails.XLOADER_SEC_BUF_CLEAR_ERR if error in clearing buffer.
static int XLoader_AuthNDecHdrs(XLoader_SecureParams *SecurePtr, XilPdi_MetaHdr *MetaHdr, u64 BufferAddr)
This function authenticates and decrypts the headers.
SecurePtr Pointer to the XLoader_SecureParams MetaHdr Pointer to the Meta header. BufferAddr Read whole headers to the mentioned buffer address. XST_SUCCESS on success.XLOADER_ERR_HDR_HASH_CALC_FAIL if failed to calculate hash for image header or partition header.XLOADER_ERR_HDR_AUTH_FAIL if failed to authenticate for image header or partition header.XLOADER_SEC_BUF_CLEAR_ERR if failed to clear the buffer.XLOADER_SEC_BUF_CLEAR_SUCCESS if successfully cleared buffer.
static int XLoader_AuthHdrs(const XLoader_SecureParams *SecurePtr, XilPdi_MetaHdr *MetaHdr)
This function authenticates image headers and partition headers of image.
SecurePtr Pointer to the XLoader_SecureParams MetaHdr Pointer to the Meta header. XST_SUCCESS on success.XLOADER_ERR_SEC_IH_READ_FAIL if failed to read image header.XLOADER_ERR_SEC_PH_READ_FAIL if failed to read partition header.XLOADER_ERR_HDR_HASH_CALC_FAIL if failed to calculate hash for image header or partition header.XLOADER_ERR_HDR_AUTH_FAIL if failed to authenticate for image header or partition header.XLOADER_SEC_BUF_CLEAR_ERR if failed to clear the buffer.
static int XLoader_CheckAndCompareHashFromIHTOptionalData(XilPdi *PdiPtr, u8 *HashPtr, u32 PrtnHashIndex)
This function checks whether Partition hash is present or not and compares the calculated hash with hash which is present in IHT Optional data for the respective partitions.
PdiPtr is pointer to the xilpdi instance HashPtr is pointer to Hash array PrtnHashIndex is index of partition hash in IHT optional data XST_SUCCESS on success.XLOADER_SEC_PRTN_HASH_NOT_PRESENT_IN_IHT_OP_DATA_ERR if partition hash is not present in IHT optional data.XLOADER_SEC_PRTN_HASH_COMPARE_FAIL_ERR if partition hash comparison fails.
static int XLoader_VerifyAuthHashNUpdateNext(XLoader_SecureParams *SecurePtr, u32 Size, u8 Last)
This function calculates hash and compares with expected hash.
Hash is calculated on AC + Data for first block, encrypts the ECDSA/RSA signature and compares it with the expected hash. After first block, hash is calculated on block of data and compared with the expected hash. SecurePtr is pointer to the XLoader_SecureParams instance Size is size of the data block to be processed which includes padding lengths and hash Last notifies if the block to be processed is last or not XST_SUCCESS on success.XLOADER_ERR_PRTN_HASH_CALC_FAIL if hash calculation fails for partition authentication.XLOADER_ERR_PRTN_AUTH_FAIL if partition authentication fails.XLOADER_ERR_PRTN_HASH_COMPARE_FAIL if failed to compare partition hash.XLOADER_SEC_BUF_CLEAR_ERR if failed to clear buffer.
static int XLoader_SetAesDpaCm(const XSecure_Aes *AesInstPtr, u8 DpaCmCfg)
This function enables or disables DPA counter measures.
AesInstPtr Pointer to the XSecure_Aes instance. DpaCmCfg TRUE - to enable AES DPA counter measureFALSE -to disable AES DPA counter measure XST_SUCCESS if enable/disable of DPA was successful.Error if device doesn't support DPA CM or configuration is not successful
static int XLoader_DecryptBlkKey(const XSecure_Aes *AesInstPtr, const XLoader_AesKekInfo *KeyDetails)
This function decrypts the black key with PUF key and stores in specified destination AES red key register.
AesInstPtr is pointer to the XSecure_Aes instance. KeyDetails is pointer to the XLoader_AesKekInfo instance. XST_SUCCESS on success and error code on failureXLOADER_SEC_PUF_REGN_ERRR if failed to regenerate PUF.XLOADER_SEC_AES_KEK_DEC if failed to decrypt KEK.
static int XLoader_SecureEncOnlyValidations(const XLoader_SecureParams *SecurePtr)
This function validates the encryption keysrc, puf helper data location and eFUSE IV for ENC only case.
SecurePtr is pointer to the XLoader_SecureParams instance. XST_SUCCESS on success.XLOADER_SEC_ENC_ONLY_KEYSRC_ERR if key source is not from efuse black key when encrypt only is enabled.XLOADER_SEC_ENC_ONLY_PUFHD_LOC_ERR if PUFHD location is from eFuse when encrypt only is enabled.
static int XLoader_ValidateIV(const u32 *IHPtr, const u32 *EfusePtr)
IV Criteria check.
IHPtr is the IV to be compared EfusePtr is the eFUSE cache address XST_SUCCESS on success.XLOADER_SEC_IV_METAHDR_RANGE_ERROR on Failure. Example: iv[95:0] - F7F8FDE0 8674A28D C6ED8E37 Bootgen follows the big-endian format so the values stored will beIHPtr[0]=E0FDF8F7 -> IV[64:95] IHPtr[1]=8DA27486 -> IV[32:63] IhPtr[2]=378EEDC6 -> IV[0:31]Our xilnvm driver also follows the same format to store it in eFUSEEfusePtr[0]=C6ED8E37 -> IV[31:0] EfusePtr[1]=8674A28D -> IV[63:32] EfusePtr[2]=F7F8FDE0 -> IV[95:64]]Spec says: IV[95:32] defined by user in meta header should match with eFUSEIV[95:32] IV[31:0] defined by user in meta header should >= eFUSEIV[31:0]
static int XLoader_ClearAesKeysOnCfg(void)
This function clears the AES PUF,RED and expanded keys.
XST_SUCCESS on success.XST_FAILURE if AES key zero or AES reset fails.
int XLoader_SecureAuthInit(XLoader_SecureParams *SecurePtr, const XilPdi_PrtnHdr *PrtnHdr)
This function initializes authentication parameters of XLoader_SecureParams's instance.
SecurePtr is pointer to the XLoader_SecureParams instance. PrtnHdr is pointer to XilPdi_PrtnHdr instance that has to be processed. XST_SUCCESS on success.XLOADER_ERR_INIT_AC_COPY_FAIL if failed to copy authentication certificate from flash device.
Referenced by XLoader_SecureInit.
int XLoader_SecureEncInit(XLoader_SecureParams *SecurePtr, const XilPdi_PrtnHdr *PrtnHdr)
This function initializes encryption parameters of XLoader_SecureParams's instance.
SecurePtr is pointer to the XLoader_SecureParams instance. PrtnHdr is pointer to XilPdi_PrtnHdr instance that has to be processed. XST_SUCCESS on success.XLOADER_ERR_INIT_CHECKSUM_INVLD_WITH_AUTHDEC if both checksum and authentication or encryption are enabled.XLOADER_ERR_PRTN_DECRYPT_NOT_ALLOWED if Partition is not allowed to be encrypted if State of boot is non secure.XLOADER_ERR_GLITCH_DETECTED if glitch is detected.XLOADER_ERR_PRTN_ENC_ONLY_KEYSRC on invalid key source when only encryption is enabled.
Referenced by XLoader_SecureInit.
int XLoader_SecureValidations(const XLoader_SecureParams *SecurePtr)
This function checks if authentication/encryption is compulsory.
SecurePtr is pointer to the XLoader_SecureParams instance. XST_SUCCESS on success.XLOADER_ERR_GLITCH_DETECTED if glitch is detected.XLOADER_ERR_AUTH_EN_PPK_HASH_ZERO if PPK not programmed and authentication is enabledXLOADER_ERR_HWROT_EFUSE_AUTH_COMPULSORY if PPK Programmed but eFuse authentication is disabled.XLOADER_ERR_ENCONLY_ENC_COMPULSORY if encryption is disabled.XLOADER_ERR_METAHDR_KEYSRC_MISMATCH if metaheader Key Source does not match PLM Key Source.
int XLoader_ReadAndVerifySecureHdrs(XLoader_SecureParams *SecurePtr, XilPdi_MetaHdr *MetaHdr)
This function authenticates and/or decrypts the image headers and partition headers and copies the contents to the corresponding structures.
SecurePtr Pointer to the XLoader_SecureParams instance. MetaHdr Pointer to the Meta header table. XST_SUCCESS on success.XLOADER_ERR_HDR_GET_DMA if acquiring DMA fails.XLOADER_ERR_HDR_AES_OP_FAIL if AES initialization fails.XLOADER_ERR_METAHDR_LEN_OVERFLOW on meta header length overflow.XLOADER_ERR_HDR_COPY_FAIL on IH/PH header copy fail.XLOADER_ERR_SEC_IH_READ_FAIL on image header read fail.XLOADER_ERR_SEC_IH_VERIFY_FAIL on image header verify fail.XLOADER_ERR_HDR_NOT_SECURE if neither authentication nor encryption is enabled for IH/PH.XLOADER_ERR_SEC_PH_READ_FAIL if partition header read fails.XLOADER_ERR_SEC_PH_VERIFY_FAIL if partition header verification fails.
int XLoader_VerifySignature(const XLoader_SecureParams *SecurePtr, u8 *Hash, XLoader_AuthKey *AuthKey, u8 *Signature)
This function verifies the signature (RSA/ECDSA) using the provided key and compares the result with the expected hash.
SecurePtr is pointer to the XLoader_SecureParams instance. Hash is pointer to the expected hash to be verified AuthKey is pointer to the RSA/ECDSA public key to be used for verification Signature is pointer to the signature to be verified XST_SUCCESS on successful signature verification.XLOADER_SEC_INVALID_AUTH on invalid authentication type.XLOADER_ERR_RSA_NOT_ENABLED if RSA is excluded from build.XLOADER_ERR_ECDSA_NOT_ENABLED if ECDSA is excluded from build.XLOADER_SEC_CURVE_NOT_SUPPORTED if P-521 curve is not supported.
References XLoader_AuthJtagMessage::AuthHdr, XLoader_SecureParams::AuthJtagMessagePtr.
int XLoader_VerifyRevokeId(u32 RevokeId)
This function validates SPK by verifying if the given SPK ID has been revoked or not.
RevokeId is ID of the SPK to be verified for revocation XST_SUCCESS on success.XLOADER_SEC_REVOCATION_ID_OUTOFRANGE_ERR if revocation ID is out of range.XLOADER_SEC_ID_REVOKED if revocation ID range not verified.
Referenced by XLoader_SecureInit.
int XLoader_IsPpkValid(const u8 *PpkHash)
This function validates PPK hash against eFUSE stored hash.
It iterates through all PPKs and checks if the provided hash matches any valid (non-revoked) PPK. PpkHash Pointer to the PPK hash to be verified. XST_SUCCESS on success.XLOADER_SEC_INVALID_PPK_CHOICE_ERR if invalid PPK selection.XLOADER_SEC_PPK_HASH_COMPARE_FAIL if PPK hash comparison failed.XLOADER_SEC_PPK_HASH_ALLZERO_INVLD if PPK hash is all zeros.XLOADER_SEC_ALL_PPK_REVOKED_ERR if all PPKs are revoked.XLOADER_SEC_SEL_PPK_REVOKED_ERR if selected PPK is revoked.
References XLoader_GetPpkInvalidMaskAndOffset, XLoader_ValidatePpkHash.
int XLoader_PpkVerify(const XLoader_SecureParams *SecurePtr, const u32 PpkSize)
This function verifies PPK.
SecurePtr is pointer to the XLoader_SecureParams instance. PpkSize is Size of the PPK to be verified XST_SUCCESS on success.XLOADER_SEC_ALL_PPK_REVOKED_ERR if all PPKs are revoked.XLOADER_SEC_PPK_HASH_CALCULATION_FAIL if PPK hash calculation failsXLOADER_SEC_ALL_PPK_INVALID_ERR if all PPKs are invalid.XLOADER_SEC_BUF_CLEAR_ERR if failed to clear buffer.
int XLoader_RsaPssSignVerify(u8 *MsgHash, XSecure_Rsa *RsaInstPtr, u8 *Signature, u32 KeySize)
This function encrypts the RSA signature provided and performs required PSS operations to extract salt and calculates M prime hash and compares with hash obtained from EM.
MsgHash of the data to be authenticated. RsaInstPtr is pointer to the XSecure_Rsa instance. Signature is pointer to RSA signature for data to be authenticated. KeySize is size of RSA key in bytes. XST_SUCCESS on success.XLOADER_SEC_MEMSET_ERROR and XLOADER_SEC_RSA_MEMSET_SHA3_ARRAY_FAIL if failed to create memory for RSA SHA3.XLOADER_SEC_MEMSET_ERROR and XLOADER_SEC_RSA_MEMSET_VARSCOM_FAIL if failed to create memory for RSA varscom.XLOADER_SEC_RSA_PSS_ENC_BC_VALUE_NOT_MATCHED if failed to match with RSA ENC 0xbc value.XLOADER_SEC_MASKED_DB_MSB_ERROR if error in RSA EM MSB.XLOADER_SEC_RSA_PSS_SIGN_VERIFY_FAIL if failed to verify RSA PSS signature.XLOADER_SEC_EFUSE_DB_PATTERN_MISMATCH_ERROR if failed to verify database in efuse.XLOADER_SEC_RSA_PSS_HASH_COMPARE_FAILURE if RSA PSS hash is not matched.XLOADER_SEC_BUF_CLEAR_ERR if failed to clear buffer.
static int XLoader_DecryptSecureBlk(XLoader_SecureParams *SecurePtr, u64 SrcAddr)
This function decrypts the secure header/footer.
SecurePtr Pointer to the XLoader_SecureParams SrcAddr Pointer to the buffer where header/footer present XST_SUCCESS on success.XLOADER_SEC_AES_OPERATION_FAILED on AES operation failure.XLOADER_SEC_ENC_DATA_NOT_ALIGNED_ERROR if encrypted data is not 128-bit aligned.
static int XLoader_DataDecrypt(XLoader_SecureParams *SecurePtr, u64 SrcAddr, u64 DestAddr, u32 Size)
This function decrypts the data.
SecurePtr is pointer to the XLoader_SecureParams SrcAddr is pointer to the buffer where header/footer present DestAddr is pointer to the buffer where header/footer should be copied Size is the number of byte sto be copied XST_SUCCESS on success.XLOADER_SEC_AES_OPERATION_FAILED on AES operation failure.XLOADER_SEC_DATA_LEFT_FOR_DECRYPT_ERR if data is still left for decryption.XLOADER_SEC_DECRYPT_REM_DATA_SIZE_MISMATCH if there is a size mismatch for the remaining data left for decryption.
int XLoader_EnableJtag(volatile u32 CfgState)
This function enables the Jtag.
CfgState is the configuration state for DAP XST_SUCCESS on SUCCESSErrorcode upon failure
References XLOADER_DAP_CFG_ENABLE_ALL_DBG_MASK.
Referenced by XLoader_ConfigureJtagState.
int XLoader_DisableJtag(void)
This function disables the Jtag.
XST_SUCCESS on SUCCESSErrorcode upon failure
Referenced by XLoader_ConfigureJtagState.
int XLoader_AuthEncClear(void)
This function is called to clear secure critical data related to authentication and encryption in case of exceptions.
The function also places AES, ECDSA_RSA in reset. XST_SUCCESS on success.XST_FAILURE on failure.
Referenced by XLoader_SecureClear.
int XLoader_ClearAesKey(u32 *DecKeySrc)
This function clears the AES keys when RedKeyClear is set in PMC RAM.
DecKeySrc is pointer to the Decrypt Key source XST_SUCCESS on success.XLOADER_SEC_KEY_CLEAR_FAILED_ERROR if AES key clear fails.
References XLOADER_SEC_KEY_CLEAR_FAILED_ERROR.
int XLoader_ProcessAuthEncPrtn(XLoader_SecureParams *SecurePtr, u64 DestAddr, u32 BlockSize, u8 Last)
This function performs authentication and decryption of the partition.
SecurePtr is pointer to the XLoader_SecureParams instance DestAddr is the address to which data is copied BlockSize is size of the data block to be processed which doesn't include padding lengths and hash Last notifies if the block to be processed is last or not XST_SUCCESS on success.XLOADER_ERR_DMA_TRANSFER if DMA transfer fails while copying.XLOADER_ERR_PRTN_DECRYPT_FAIL if partition decryption fails.XLOADER_SEC_BUF_CLEAR_SUCCESS if successfully cleared buffer.XLOADER_SEC_BUF_CLEAR_ERR if failed to clear buffer.
int XLoader_CheckSecureState(u32 RegVal, u32 Var, u32 ExpectedValue)
This function checks if the secure state of boot matches the expected value or not.
RegVal - Value of secure state stored in register Var - Value of secure state stored in variable ExpectedValue - Expected value of secure state XST_SUCCESS on success.XST_FAILURE if RegVal, Var, or ExpectedValue do not all match.
Referenced by XLoader_SecureInit.
int XLoader_AuthKat(XLoader_SecureParams *SecurePtr)
This function runs RSA or Ecdsa KAT based on pdi.
SecurePtr is pointer to the XLoader_SecureParams instance XST_SUCCESS on success.XLOADER_SEC_INVALID_AUTH on invalid authentication type.XLOADER_ERR_RSA_NOT_ENABLED if RSA is not enabled.XLOADER_ERR_ECDSA_NOT_ENABLED if ECDSA is not enabled.
References XLoader_AuthJtagMessage::AuthHdr, XLoader_SecureParams::AuthJtagMessagePtr.
int XLoader_ImgHdrTblAuth(XLoader_SecureParams *SecurePtr)
This function authenticates the image header table.
SecurePtr is pointer to the XLoader_SecureParams instance XST_SUCCESS on success.XLOADER_ERR_IHT_GET_DMA if acquiring DMA is failed.XLOADER_ERR_IHT_COPY_FAIL if IHT copy fails.XLOADER_ERR_IHT_HASH_CALC_FAIL if IHT hash calculation fails.XLOADER_ERR_IHT_AUTH_FAIL if IHT authentication fails.
int XLoader_DataAuth(XLoader_SecureParams *SecurePtr, u8 *Hash, u8 *Signature)
This function authenticates the data with SPK.
SecurePtr is pointer to the XLoader_SecureParams instance. Hash is a Pointer to the expected hash buffer. Signature pointer points to the signature buffer. XST_SUCCESS on success.XLOADER_SEC_GLITCH_DETECTED_ERROR if glitch is detected.
int XLoader_GetPpkInvalidMaskAndOffset(XLoader_PpkSel PpkSelect, u32 *InvalidMask, u32 *PpkOffset)
This function calculates the invalid mask and PPK offset based on the selected PPK.
PpkSelect is PPK selection of eFUSE. InvalidMask is pointer to store the invalid mask for the selected PPK. PpkOffset is pointer to store the PPK eFUSE offset. XST_SUCCESS on success.XLOADER_SEC_INVALID_PPK_CHOICE_ERR if invalid PPK selection.
References XLOADER_EFUSE_MISC_CTRL_PPK0_INVLD, XLOADER_EFUSE_MISC_CTRL_PPK1_INVLD, XLOADER_EFUSE_MISC_CTRL_PPK2_INVLD, XLOADER_EFUSE_MISC_CTRL_PPK3_INVLD, XLOADER_EFUSE_MISC_CTRL_PPK4_INVLD, XLOADER_EFUSE_MISC_CTRL_PPK5_INVLD, XLOADER_EFUSE_MISC_CTRL_PPK6_INVLD, XLOADER_EFUSE_MISC_CTRL_PPK7_INVLD, XLOADER_EFUSE_MISC_CTRL_PPK8_INVLD, XLOADER_EFUSE_PPK0_START_OFFSET, XLOADER_EFUSE_PPK1_START_OFFSET, XLOADER_EFUSE_PPK2_START_OFFSET, XLOADER_PPK_SEL_0, XLOADER_PPK_SEL_1, XLOADER_PPK_SEL_2.
Referenced by XLoader_IsPpkValid.
int XLoader_IsPpkRevoked(u32 PpkInvldMask)
This function checks if the selected PPK is revoked by reading the PPK invalid bits from eFUSE.
PpkInvldMask is the PPK invalid bit mask to check in eFUSE. XST_SUCCESS if PPK is not revoked.XLOADER_SEC_SEL_PPK_REVOKED_ERR if PPK is revoked (invalid bit set).XLOADER_SEC_ALL_PPK_REVOKED_ERR if all PPKs are revoked.
int XLoader_ValidatePpkHash(const u8 *PpkHash, u32 PpkOffset)
This function compares the provided PPK hash with the hash stored in eFUSE and validates it is not all zeros.
PpkHash is pointer to the PPK hash to be verified. PpkOffset is PPK eFUSE offset. XST_SUCCESS on success.XLOADER_SEC_PPK_HASH_COMPARE_FAIL if hash comparison fails.XLOADER_SEC_PPK_HASH_ALLZERO_INVLD if PPK hash is all zeros.
Referenced by XLoader_IsPpkValid.
static void XLoader_CfiErrHandler(const XCfupmc *InstancePtr)
This function is used for Cframe error handling.
InstancePtr is a pointer to the XCfupmc instance.
static void XLoader_CfuErrHandler(const XCfupmc *InstancePtr)
This function is used for CFU error handling.
InstancePtr is a pointer to the XCfupmc instance.
int XLoader_CframeInit(void)
This function initializes the Cframe driver.
XST_SUCCESS on success.XLOADER_ERR_CFRAME_LOOKUP if CFrame lookup fails.XLOADER_ERR_CFRAME_CFG if CFrame configuration fails.
Referenced by XLoader_CfiSelectiveRead, XLoader_CframeDataClearCheck, XLoader_Init.
void XLoader_CframeErrorHandler(u32 ImageId)
This function is used to check the CFU ISR and PMC_ERR1 and PMC_ERR2 status registers to check for any errors in PL and call corresponding error recovery functions if needed.
ImageId is Id of the image present in PDI
References PMC_GLOBAL_PMC_ERR2_STATUS_CFI_SHIFT.
int XLoader_CframeDataClearCheck(XPlmi_Cmd *Cmd)
This function is used to check if the Cframe data is cleared or not using CRC method.
This function need to be called after CFI house cleaning is done. Cmd is pointer to the command. Command payload parameters are: Block Type XST_SUCCESS on success.XLOADER_INVALID_BLOCKTYPE if block type passed is invalid. Only Type 0, Type 1, and Type 2 are supported.XLOADER_CFI_CFRAME_IS_BUSY if CRAM self check fails as CFI CFrame is busy.XLOADER_CFRAME_CRC_CHECK_FAILED if CFRAME CRC check fails.
References CFRAME_BCAST_REG_FAR_BLOCKTYPE_SHIFT, CFRAME_BCAST_REG_FAR_OFFSET, CFRAME_BCAST_REG_TESTMODE_CRAM_SELF_CHECK_MASK, CFRAME_BCAST_REG_TESTMODE_OFFSET, CFRAME_CRC_POLL_TIMEOUT, CFRAME_MAX_BLOCK_TYPE_COUNT, XLOADER_CFI_CFRAME_IS_BUSY, XLOADER_CFRAME_CRC_CHECK_FAILED, XLOADER_CFRAME_DATACLEAR_CHECK_CMD_ID, XLoader_CframeInit, XLOADER_INVALID_BLOCKTYPE, XPLMI_ZERO.
int XLoader_CfiSelectiveRead(XPlmi_Cmd *Cmd)
This function provides CFI SELECTIVE READ command execution.
Command payload parameters are: - Row, block type and start frame address - Frame count to be read from CFI(1 frame = 25 quad words - High Dest Addr - Low Dest Addr Cmd is pointer to the command structure XST_SUCCESS on success.Error code on failure
References XLOADER_CFI_SEL_READBACK_ID, XLoader_CframeInit, XLOADER_ERR_INVALID_BLOCK_TYPE, XLOADER_ERR_INVALID_ROW, XLOADER_FRAME_COUNT_EXCEEDS_LASTFRAME, XLOADER_INVALID_FRAME_ADDRESS, XLOADER_SELREADBACK_ROW_MASK.
static int XLoader_LoadDdrCpyImg(XPlmi_Cmd *Cmd)
This function provides load DDR copy image execution.
Cmd is pointer to the command structure with the following parameters as payload: Img ID - of ddr copied imageFunc ID - to verify with the FuncID of the image copied to DDR XST_SUCCESS on success and error code on failure
static int XLoader_LoadSubsystemPdi(XPlmi_Cmd *Cmd)
This function provides PDI execution from DDR.
Cmd is pointer to the command structure with the following parameters as payload: PdiSrc - Boot Mode values, DDR, PCIe.PdiAddr - 64bit PDI address located in the Source.Response - stores the partial PDI load status. XST_SUCCESS on successXLOADER_ERR_UNSUPPORTED_SUBSYSTEM_PDISRC on unsupported PDI source.
static int XLoader_GetImageInfo(XPlmi_Cmd *Cmd)
This function provides ImageInfo stored in ImageInfoTbl for a given NodeID.
Command payload parameters are - Node ID Command Response parameters are - Unique ID - Parent Unique ID - Function ID Cmd is pointer to the command structure XST_SUCCESS on success.XLOADER_ERR_INVALID_IMGID on invalid image ID.XLOADER_ERR_NO_VALID_IMG_FOUND on valid image not found in image info table.
static int XLoader_SetImageInfo(XPlmi_Cmd *Cmd)
This function stores image info.
Command payload parameters are - Node ID - Unique ID - Parent Unique ID - Function ID Cmd is pointer to the command structure XST_SUCCESS on success and error code on failure
static int XLoader_GetImageInfoList(XPlmi_Cmd *Cmd)
This function gets ImageInfo Table and copies it into the buffer address passed in the command.
Command payload parameters are 64-bit Buffer AddressMax Size Command Response parameters are Number of Entries Returned Cmd is pointer to the command structure XST_SUCCESS on success, error code on failure
static int XLoader_UpdateMultiboot(XPlmi_Cmd *Cmd)
This function updates multiboot register value during run-time Command payload parameters are.
- BootMode[15:8] - Boot Mode value - FlashType[3:0] - Type of Flash - Image Location - Location of Image in the boot device Cmd is pointer to the command structure XST_SUCCESS on success.XLOADER_ERR_UNSUPPORTED_MULTIBOOT_FLASH_TYPE on unsupported flash type.XLOADER_ERR_UNSUPPORTED_MULTIBOOT_PDISRC on unsupported PDI source.XLOADER_ERR_UNSUPPORTED_FILE_NUM on unsupported file number.XLOADER_ERR_UNSUPPORTED_MULTIBOOT_OFFSET on unsupported multiboot offset.
static int XLoader_AddImageStorePdi(XPlmi_Cmd *Cmd)
This function adds Pdi to ImageStore PdiList Command payload parameters are.
- PDI ID - High PdiAddr - Upper 32 bit value of PdiAddr - Low PdiAddr - Lower 32 bit value of PdiAddr - PDI Size (in words) Cmd is pointer to the command structure XST_SUCCESS on success.XLOADER_ERR_PDI_IMG_STORE_CFG_NOT_SET if image store configuration is not enabled or error.XLOADER_ERR_PDI_IMG_STORE_FULL on PDI image list is full.
static int XLoader_WriteImageStorePdi(XPlmi_Cmd *Cmd)
This function adds Pdi to ImageStore PdiList Command payload parameters are:
- PDI ID - PDI Data Cmd is pointer to the command structure XST_SUCCESS on success.XLOADER_ERR_PDI_IMG_STORE_CFG_NOT_SET if image store configuration is not enabled or error.XLOADER_ERR_PDI_IMG_STORE_FULL on PDI image list is full.
static int XLoader_RemoveImageStorePdi(XPlmi_Cmd *Cmd)
This function removes Pdi from ImageStore PdiList Command payload parameters are.
- PdiId - Id of the PDI to be removed from Image Store Cmd is pointer to the command structure XST_SUCCESS on success.XLOADER_ERR_PDI_LIST_EMPTY if there are no PDI's in the list.XLOADER_ERR_PDI_ADDR_NOT_FOUND if PDI address is invalid.
static void XLoader_GetExportableBuffer(u32 *Buffer, u32 MaskVal, u32 SizeVal)
This function zeroizes non-exportable fields of a buffer.
Buffer is the pointer to the metaheader buffer MaskVal is the exportable mask which is used to zeroise the non-exportable fields of the buffer SizeVal is the size of the buffer in bytes
static int XLoader_ExtractMetaheader(XPlmi_Cmd *Cmd)
This function decrypts the metaheader during run-time and exports it to the user specified location.
Command payload parameters are: Source Buffer Low AddressSource Buffer High AddressDestination Buffer Low AddressDestination Buffer High AddressDestination Buffer SizeData Id | Get Optional data flag | PdiSrc Cmd is pointer to the command structure XST_SUCCESS on success.XLOADER_ERR_INVALID_PDI_INPUT PDI given is not a full PDI or partial PDI.XLOADER_ERR_INVALID_METAHEADER_SRC_ADDR if source address is invalid.XLOADER_ERR_INVALID_METAHEADER_OFFSET if offset is invalid.XLOADER_ERR_INVALID_METAHEADER_DEST_ADDR if destination address is invalid.XLOADER_ERR_INVALID_METAHDR_BUFF_SIZE if buffer size is less than meta header length.
static int XLoader_GetATFHandOffParams(XPlmi_Cmd *Cmd)
This function copies the TF-A handoff parameter structure to the given address.
Command payload parameters are: Destination Buffer High AddressDestination Buffer Low AddressDestination Buffer Size Cmd is pointer to the command structure XST_SUCCESS on success.XLOADER_ERR_INVALID_HANDOFF_PARAM_DEST_ADDR on Invalid destination address.XLOADER_ERR_INVALID_HANDOFF_PARAM_DEST_SIZE on Invalid destination size.
int XLoader_DdrInit(u32 DeviceFlags)
This function is used to initialize for DDR init.
DeviceFlags Loader init prototype requires flags XST_SUCCESS on successXLOADER_ERR_PM_DEV_DDR_0 on device request to DDR fail.
Referenced by XLoader_DumpDdrmcRegisters.
int XLoader_DdrCopy(u64 SrcAddr, u64 DestAddr, u32 Length, u32 FlagsVal)
This function is used to copy the data from DDR to destination address.
SrcAddr of DDR DestAddr is the address of the destination where the data needs to be copied. Length of the bytes to be copied FlagsVal that denote blocking / non-blocking dma XST_SUCCESS on success.XLOADER_DDR_COPY_UNSUPPORTED_PARAMS on invalid params passed.
int XLoader_DdrRelease(void)
This function releases control of DDR.
XST_SUCCESS on successXLOADER_ERR_RELEASE_PM_DEV_DDR_0 on device release fail.
References XLOADER_PDI_SRC_DDR.
int XLoader_MbPmcI2cHandshake(XPlmi_Cmd *Cmd)
This function is a stub to handle the DDR designs where i2c handshake is not required for the DIMM'S.
Cmd is pointer to the command structure. XST_SUCCESS success always
static int XLoader_SbiLoadPdi(void *Data)
This function is the interrupt handler for SBI data ready.
In this handler, PDI is loadeed through SBI interface. SBI interface setting for JTAG/SMAP/AXI/HSDP should be set before this handler. Data Not used as of now, present as a part of general interrupt handler definition. XST_SUCCESS on success and error code on failure. SBI interface setting for JTAG/SMAP/AXI/HSDP should be set before this handler.
int XLoader_IntrInit(void)
This function initializes the loader instance and registers loader commands with PLM.
XST_SUCCESS on success and error code on failure.
Referenced by XLoader_Init.
int XLoader_PpdiEventHandling(PdiSrc_t PdiSrc, u64 PdiAddr, u32 IpiMask)
This function handles the partial PDI event based on status of resources and is applicable only when queuinh mechanism is enabled.
PdiSrc is source of PDI. PdiAddr is the address at which PDI is located in the PDI source IpiMask is mask of IPI channel from which current partial PDI event is received XST_SUCCESS
XSecure_PartialPdiEventParams* XLoader_PpdiEventParamsPtr(void)
This function is used to get the functions related to partial PDI event.
NULL
static int XLoader_PrtnHdrValidation(const XilPdi_PrtnHdr *PrtnHdr, u32 PrtnNum)
This function validates the partition header.
PrtnHdr is pointer to partition header PrtnNum is the partition number in the image to be loaded XST_SUCCESS on success.XLOADER_SUCCESS_NOT_PRTN_OWNER if partition is not owned by PLM.
static int XLoader_ProcessCdo(const XilPdi *PdiPtr, XLoader_DeviceCopy *DeviceCopy, XLoader_SecureParams *SecureParams)
This function is used to process the CDO partition.
It copies and validates if security is enabled. PdiPtr is pointer to XilPdi instance DeviceCopy is pointer to the structure variable with parameters required for copying SecureParams is pointer to the instance containing security related params XST_SUCCESS on success.XLOADER_ERR_INIT_CDO on CDO initialization fail.
static int XLoader_ProcessPrtn(XilPdi *PdiPtr)
This function is used to process the partition.
PdiPtr is pointer to XilPdi instance XST_SUCCESS on success.XLOADER_ERR_COPY_TO_MEM if failed to copy image to DDR.XLOADER_ERR_DELAY_LOAD on errors during copies from SMAP, SBI, PCIE, or JTAG to PMC RAM.
int XLoader_LoadImagePrtns(XilPdi *PdiPtr)
This function loads the partition.
PdiPtr is pointer to XilPdi instance XST_SUCCESS on success.XLOADER_SLD_DETECTED_SKIP_PRTN_PROCESS on secure lockdown.XPLMI_NPI_ERR on NPI errors.
References XilPdi::DelayLoad, XilPdi::ImageNum, XilPdi::ImagePrtnId, XilPdi::MetaHdr, XilPdi::PrtnNum, XLOADER_SUCCESS_NOT_PRTN_OWNER.
Referenced by XLoader_MeasureNLoad.
int XLoader_PrtnCopy(const XilPdi *PdiPtr, const XLoader_DeviceCopy *DeviceCopy, void *SecureParamsPtr)
This function copies partition data to respective target memories.
PdiPtr is pointer to XilPdi instance DeviceCopy is pointer to the structure variable with parameters required for copying SecureParamsPtr is pointer to the instance containing security related params XST_SUCCESS on success and error code on failure
References XLoader_DeviceCopy::DestAddr, XLoader_DeviceCopy::Flags, XLoader_SecureParams::IsCheckSumEnabled, XLoader_DeviceCopy::Len, XilPdi::MetaHdr, XilPdi::PrtnNum, XLoader_SecureTempParams::SecureEn, XLoader_SecureParams::SecureEn, XLoader_DeviceCopy::SrcAddr, XLOADER_BOOT_COPY_OPTIMIZATION_ENABLED, XLOADER_DEVICE_COPY_OPTIMIZATION_MASK, XLoader_GetTempParams, XLoader_SecureCopy, XLoader_UpdateDataMeasurement.
Referenced by XLoader_ProcessElf.
static int XLoader_StartNextChunkCopy(XLoader_SecureParams *SecurePtr, u32 TotalLen, u64 NextBlkAddr, u32 ChunkLen)
This function starts next chunk copy when security is enabled.
SecurePtr is pointer to the XLoader_SecureParams instance. TotalLen is total length of the partition in bytes. NextBlkAddr is the address of the next chunk data to be copied. ChunkLen is size of the data block to be copied. XST_SUCCESS on success.XLOADER_ERR_DATA_COPY_FAIL if failed to copy data to PMC RAM.
static int XLoader_ChecksumInit(XLoader_SecureParams *SecurePtr, const XilPdi_PrtnHdr *PrtnHdr)
This function initializes checksum parameters of XLoader_SecureParams's instance.
SecurePtr is pointer to the XLoader_SecureParams instance. PrtnHdr is pointer to XilPdi_PrtnHdr instance XST_SUCCESS on success.XLOADER_ERR_INIT_INVALID_CHECKSUM_TYPE on unsupported checksum type.XLOADER_ERR_INIT_CHECKSUM_COPY_FAIL if failed to copy checksum from flash device.
static int XLoader_ProcessChecksumPrtn(XLoader_SecureParams *SecurePtr, u64 DestAddr, u32 BlockSize, u8 Last)
This function performs checksum of the partition.
SecurePtr is pointer to the XLoader_SecureParams instance DestAddr is the address to which data is copied BlockSize is size of the data block to be processed which doesn't include padding lengths and hash. Last notifies if the block to be processed is last or not XST_SUCCESS on success.XLOADER_ERR_DMA_TRANSFER if DMA transfer fails to copy.
int XLoader_SecureInit(XLoader_SecureParams *SecurePtr, XilPdi *PdiPtr, u32 PrtnNum)
This function initializes XLoader_SecureParams's instance.
SecurePtr is pointer to the XLoader_SecureParams instance. PdiPtr is pointer to the XilPdi instance PrtnNum is the partition number to be processed XST_SUCCESS on success.XLOADER_ERR_MEMSET_SECURE_PTR if failed to set memory for secure pointer.XLOADER_ERR_INIT_GET_DMA if failed to get DMA instance during initialization.
References XLoader_SecureParams::BlockNum, XLoader_SecureParams::ChunkAddr, XilPdi::MetaHdr, XLoader_SecureParams::NextChunkAddr, XLoader_SecureParams::PdiPtr, XLoader_SecureParams::PmcDmaInstPtr, XLoader_SecureParams::ProcessedLen, XLoader_SecureParams::PrtnHdr, XLoader_CheckSecureState, XLoader_GetAHWRoT, XLoader_GetSHWRoT, XLoader_GetTempParams, XLoader_SecureAuthInit, XLoader_SecureEncInit, XLoader_VerifyRevokeId.
int XLoader_SecureCopy(XLoader_SecureParams *SecurePtr, u64 DestAddr, u32 Size)
This function loads secure non-cdo partitions.
SecurePtr is pointer to the XLoader_SecureParams instance. DestAddr is load address of the partition. Size is unencrypted size of the partition in bytes. XST_SUCCESS on success and error code on failure
References XLoader_SecureParams::ChunkAddr, XLoader_SecureParams::NextChunkAddr, XLoader_SecureParams::ProcessedLen, XLoader_SecureParams::ProcessPrtn, XLoader_SecureParams::RemainingDataLen, XLoader_SecureParams::SecureDataLen, XLOADER_SECURE_CHUNK_SIZE.
Referenced by XLoader_PrtnCopy.
int XLoader_SecureClear(void)
This function is called to clear secure critical data in case of exceptions.
The function also places AES, ECDSA_RSA and SHA3 in reset. XST_SUCCESS on success.XLOADER_ERR_SECURE_CLEAR_FAIL if failed to clear AES, RSA, SHA3 engines.
References XLoader_AuthEncClear, XLOADER_SHA3_RESET_REG, XLOADER_SHA3_RESET_VAL.
int XLoader_VerifyHashNUpdateNext(XLoader_SecureParams *SecurePtr, u64 DataAddr, u32 Size, u8 Last)
This function calculates hash and compares with expected hash.
For every block, hash of next block is updated into expected hash. SecurePtr is pointer to the XLoader_SecureParams instance. DataAddr is the address of the data present in the block Size is size of the data block to be processed Last notifies if the block to be processed is last or not. XST_SUCCESS on success.XLOADER_ERR_PRTN_HASH_CALC_FAIL if failed to calculate hash for partition authentication.XLOADER_ERR_PRTN_HASH_COMPARE_FAIL on partition comparison fail.
References XLoader_SecureParams::BlockNum, XLoader_SecureParams::ChunkAddr, XilPdi::ImagePrtnId, XLoader_SecureParams::IsCdo, XLoader_SecureParams::PdiPtr, XLoader_SecureParams::PmcDmaInstPtr, XLoader_SecureParams::Sha3Hash.
int XLoader_SecureChunkCopy(XLoader_SecureParams *SecurePtr, u64 SrcAddr, u8 Last, u32 BlockSize, u32 TotalSize)
This function copies the data from SrcAddr to chunk memory during processing of secure partitions.
SecurePtr is pointer to the XLoader_SecureParams instance SrcAddr is the source address from which the data is to be processed or copied Last notifies if the block to be processed is last or not BlockSize is size of the data block to be processed which doesn't include padding lengths and hash. TotalSize is pointer to TotalSize which has to be processed XST_SUCCESS on success.XLOADER_ERR_DATA_COPY_FAIL if failed to copy data to PMC RAM.
References XLoader_SecureParams::BlockNum, XLoader_SecureParams::ChunkAddr, XLoader_SecureParams::DmaFlags, XLoader_SecureParams::IsNextChunkCopyStarted, XilPdi::MetaHdr, XLoader_SecureParams::PdiPtr, XLoader_SecureParams::RemainingDataLen.
int XLoader_CheckNonZeroPpk(void)
This function checks if PPK is programmed.
XST_SUCCESS if PPK is programmed.XLOADER_ERR_GLITCH_DETECTED if glitch is detected.XST_FAILURE on failure.
References XLOADER_EFUSE_PPK0_START_OFFSET, XLOADER_EFUSE_PPK2_END_OFFSET.
Referenced by XLoader_CheckSecureStateAuth.
u32 XLoader_GetAHWRoT(const u32 *AHWRoTPtr)
This function returns the state of authenticated boot.
AHWRoTPtr - Always NULL except at time of initialization of SecureStateAHWRoT variable XPLMI_RTCFG_SECURESTATE_AHWROT - PPK fuses are programmedXPLMI_RTCFG_SECURESTATE_EMUL_AHWROT - BHDR auth is enabledXPLMI_RTCFG_SECURESTATE_NONSECURE - Neither PPK fuses are programmed nor BH auth is enabled
Referenced by XLoader_AddDeviceStateChangeToScheduler, XLoader_MeasureRomAndPlm, XLoader_SecureInit, XLoader_SetSecureState.
u32 XLoader_GetSHWRoT(const u32 *SHWRoTPtr)
This function returns the state of encrypted boot.
SHWRoTPtr - Always NULL except at time of initialization of SecureStateSHWRoT variable XPLMI_RTCFG_SECURESTATE_SHWROT - Any DEC only fuse is programmedXPLMI_RTCFG_SECURESTATE_EMUL_SHWROT - PLM is encryptedXPLMI_RTCFG_SECURESTATE_NONSECURE - Neither DEC only fuses are programmed nor PLM is encrypted
Referenced by XLoader_AddDeviceStateChangeToScheduler, XLoader_SecureInit, XLoader_SetSecureState.
int XLoader_SetSecureState(void)
This function reads the value of PPK efuse bits, DEC only efuse bits and fields in bootheader and accordingly sets the Secure State of boot.
XST_SUCCESS on SUCCESS and error code in case of failure. The Secure State of the device will be stored in two 32-bit registers in RTC area of PMCRAM and two global variables -one for authenticated boot and other for encrypted boot, for redundancy.
References XLoader_CheckSecureStateAuth, XLOADER_EFUSE_SEC_DEC_MASK, XLOADER_EFUSE_SEC_MISC0_OFFSET, XLoader_GetAHWRoT, XLoader_GetSHWRoT.
Referenced by XLoader_Init.
XLoader_SecureTempParams* XLoader_GetTempParams(void)
This function returns the pointer to XLoader_SecureTempParams.
Pointer to XLoader_SecureTempParams
Referenced by XLoader_PrtnCopy, XLoader_SecureInit.
static void XLoader_A72Config(u32 CpuId, u32 ExecState, u32 VInitHi)
This function sets Aarch state and vector location for APU.
CpuId CPU ID ExecState CPU execution state VInitHi resembles highvec configuration for CPU
static int XLoader_RequestTCM(u32 TcmId)
This function requests TCM_0_A, TCM_0_B, TCM_1_A and TCM_1_B depending upon input param and R5-0 and R5-1 cores as required for TCMs.
TcmId denotes TCM_0 or TCM_1 XST_SUCCESS on success.XLOADER_ERR_PM_DEV_TCM_0_A if device request for TCM_0_A is failed.XLOADER_ERR_PM_DEV_TCM_0_B if device request for TCM_0_B is failed.XLOADER_ERR_PM_DEV_TCM_1_A if device request for TCM_1_A is failed.XLOADER_ERR_PM_DEV_TCM_1_B if device request for TCM_1_B is failed.
static int XLoader_CheckHandoffCpu(const XilPdi *PdiPtr, const u32 DstnCpu)
This function is used to check whether cpu has handoff address stored in the handoff structure.
PdiPtr is pointer to XilPdi instance DstnCpu is the cpu which needs to be checked XST_SUCCESS if the DstnCpu is successfully added to Handoff listXST_FAILURE if the DstnCpu is already added to Handoff list
static int XLoader_GetLoadAddr(u32 DstnCpu, u64 *LoadAddrPtr, u32 Len)
This function updates the load address based on the destination CPU.
DstnCpu is destination CPU LoadAddrPtr is the destination load address pointer Len is the length of the partition XST_SUCCESS on success.XLOADER_ERR_TCM_ADDR_OUTOF_RANGE if load address is out of range.
static int XLoader_DumpDdrmcRegisters(void)
This function prints DDRMC register details.
XST_SUCCESS on success and error code on failure
int XLoader_UpdateDataMeasurement(const XilPdi *PdiPtr, u64 DataAddr, u32 DataLen)
This function updates the partition data to SHA engine for data measurement only if authentication or checksum is not enabled.
This functions updates the partition data to SHA engine for measurement.If authentication or checksum is enabled, nothing needs to be done as SHA engine would be in use for the authentication/checksum process. PdiPtr Pointer to the XilPdi structure. DataAddr Address of Data for measure the hash. DataLen Length of data for DataMeasument. XST_SUCCESS on success and error code on failure PdiPtr Pointer to the XilPdi structure. DataAddr Address of Data for measure the hash. DataLen Length of data for DataMeasument. XST_SUCCESS on success.Error code on failure. PdiPtr Pointer to the XilPdi structure. DataAddr Address of Data for measure the hash. DataLen Length of data for DataMeasument. XST_SUCCESS on success and error code on failure
References XLoader_ImageMeasureInfo::DataAddr, XLoader_ImageMeasureInfo::DataSize, XLoader_ImageMeasureInfo::Flags, XilPdi::ImageNum, XilPdi::ImagePrtnId, XilPdi::MetaHdr, XLoader_ImageMeasureInfo::PcrInfo, XilPdi::PrtnNum, XLoader_ImageMeasureInfo::SubsystemID, XLoader_DataMeasurement, XLOADER_IMAGE_FULL_AUTHENTICATED, XLOADER_MEASURE_UPDATE.
Referenced by XLoader_PrtnCopy.
XLoader_ImageInfoTbl * XLoader_GetImageInfoTbl(void)
This function provides ImageInfoTbl pointer.
Pointer to ImageInfoTbl Pointer to ImageInfoTbl.
References XLoader_ImageInfoTbl::Count.
Referenced by XLoader_GetImageInfoEntry, XLoader_LoadImageInfoTbl, XLoader_StoreImageInfo.
XLoader_ImageStore * XLoader_GetPdiList(void)
This function provides pointer to PdiList.
Pointer to PdiListpointer to PdiList Pointer to PdiList.
Referenced by XLoader_IsPdiAddrLookup, XLoader_ReadImageStoreCfg, XLoader_RestartImage.
XilPdi_ATFHandoffParams * XLoader_GetATFHandoffParamsAddr(void)
This function returns the ATFHandoffParams structure address to the caller.
Returns ATFHandoffParams structure address ATFHandoffParams structure address.
Referenced by XLoader_PdiInit, XLoader_SetATFHandoffParameters.
XilBootPdiInfo * XLoader_GetBootPdiInfo(void)
This function provides pointer to BootPDI Info.
pointer to BootPDI Info pointer to BootPDI Info.
Referenced by XLoader_RestartImage, Xloader_SaveBootPdiInfo.
int XLoader_StartImage(XilPdi *PdiPtr)
This function is used to start the subsystems in the PDI.
PdiPtr Pdi instance pointer XST_SUCCESS on success.XLOADER_ERR_WAKEUP_A72_0 if waking up the A72-0 failed during handoff.XLOADER_ERR_WAKEUP_A72_1 if waking up the A72-1 failed during handoff.XLOADER_ERR_WAKEUP_R5_0 if waking up the R5-0 failed during handoff.XLOADER_ERR_WAKEUP_R5_1 if waking up the R5-1 failed during handoff.XLOADER_ERR_WAKEUP_R5_L if waking up the R5-L failed during handoff.XLOADER_ERR_WAKEUP_PSM if waking up the PSM failed during handoff.XLOADER_ERR_CONFIG_SUBSYSTEM if subsystem peripheral pre-allocation fails during handoff. PdiPtr Pdi instance pointer XST_SUCCESS on success.XLOADER_ERR_WAKEUP_R52_0 if waking up the R52_0 failed during handoff.XLOADER_ERR_WAKEUP_R52_1 if waking up the R52_1 failed during handoff.XLOADER_ERR_WAKEUP_A78_0 if waking up the A78_0 failed during handoff.XLOADER_ERR_WAKEUP_A78_1 if waking up the A78_1 failed during handoff.XLOADER_ERR_WAKEUP_A78_2 if waking up the A78_2 failed during handoff.XLOADER_ERR_WAKEUP_A78_3 if waking up the A78_3 failed during handoff.XLOADER_ERR_WAKEUP_ASU if waking up the ASU failed during handoff. PdiPtr Pdi instance pointer. XST_SUCCESS on success.XLOADER_ERR_WAKEUP_A72_0 if waking up the A72-0 failed during handoff.XLOADER_ERR_WAKEUP_A72_1 if waking up the A72-1 failed during handoff.XLOADER_ERR_WAKEUP_R5_0 if waking up the R5-0 failed during handoff.XLOADER_ERR_WAKEUP_R5_1 if waking up the R5-1 failed during handoff.XLOADER_ERR_WAKEUP_R5_L if waking up the R5-L failed during handoff.XLOADER_ERR_WAKEUP_PSM if waking up the PSM failed during handoff.XLOADER_ERR_CONFIG_SUBSYSTEM if subsystem peripheral pre-allocation fails during handoff. PdiPtr Pdi instance pointer XST_SUCCESS on success.XLOADER_ERR_WAKEUP_R52_0 if waking up the R52_0 failed during handoff.XLOADER_ERR_WAKEUP_R52_0 if waking up the R52_1 failed during handoff.XLOADER_ERR_WAKEUP_A78_0 if waking up the A78_0 failed during handoff.XLOADER_ERR_WAKEUP_A78_1 if waking up the A78_1 failed during handoff.XLOADER_ERR_WAKEUP_A78_2 if waking up the A78_2 failed during handoff.XLOADER_ERR_WAKEUP_A78_3 if waking up the A78_3 failed during handoff.XLOADER_ERR_WAKEUP_PSM if waking up the PSM failed during handoff.XLOADER_ERR_CONFIG_SUBSYSTEM if subsystem peripheral pre-allocation fails during handoff.
References XLoader_HandoffParam::CpuSettings, XLoader_HandoffParam::HandoffAddr, XilPdi::HandoffParam, XilPdi::ImageNum, XilPdi::MetaHdr, XilPdi::NoOfHandoffCpus, XLoader_Printf.
Referenced by XLoader_RestartImage.
int XLoader_MeasureNLoad(XilPdi *PdiPtr)
This function measures the partition hashes.
This function measures the partition hashes from the hash block. PdiPtr is pointer to XilPdi instance XST_SUCCESS on success.XLOADER_ERR_DATA_MEASUREMENT if error in data measurement. PdiPtr is pointer to XilPdi instance. XST_SUCCESS on success.XLOADER_ERR_DATA_MEASUREMENT if error in data measurement.
References XLoader_ImageMeasureInfo::DataAddr, XLoader_ImageMeasureInfo::DataSize, XilPdi::DigestIndex, XLoader_ImageMeasureInfo::Flags, XilPdi::ImageNum, XilPdi::MetaHdr, XLoader_ImageMeasureInfo::PcrInfo, XilPdi::PrtnNum, XLoader_ImageMeasureInfo::SubsystemID, XIH_MAX_PRTNS, XLoader_DataMeasurement, XLOADER_IMAGE_FULL_AUTHENTICATED, XLOADER_IMAGE_PARTIALLY_AUTHENTICATED, XLoader_LoadImagePrtns, XLOADER_MEASURE_FINISH, XLOADER_MEASURE_START, XLOADER_MEASURE_UPDATE, XLOADER_PCR_INVALID_VALUE, XLOADER_PCR_MEASUREMENT_INDEX_MASK, XLOADER_PCR_MEASUREMENT_INDEX_SHIFT.
Referenced by XLoader_LoadImage.
int XLoader_MeasureRomAndPlm(void)
This function extends the image hashes of ROM and PLM data.
XST_SUCCESS on successful extensionerror code on failure
References XLoader_GetAHWRoT.
int XLoader_DataMeasurement(XLoader_ImageMeasureInfo *ImageInfo)
This function measures the data by calculating SHA3 hash.
ImageInfo Pointer to the XLoader_ImageMeasureInfo structure XST_SUCCESS on successfully measuring the dataXLOADER_ERR_DATA_MEASUREMENT if error in data measurement. ImageInfo Pointer to the XLoader_ImageMeasureInfo structure. XST_SUCCESS on success.XLOADER_ERR_DATA_MEASUREMENT if error in data measurement. ImageInfo Pointer to the XLoader_ImageMeasureInfo structure. XST_SUCCESS on successfully measuring the data.XLOADER_ERR_DATA_MEASUREMENT if error in data measurement.
References XLoader_ImageMeasureInfo::DataAddr, XLoader_ImageMeasureInfo::DataSize, XLoader_ImageMeasureInfo::Flags, XLoader_ImageMeasureInfo::PcrInfo, XLOADER_MEASURE_FINISH, XLOADER_MEASURE_START, XLOADER_MEASURE_UPDATE, XLOADER_PCR_INVALID_VALUE, XLOADER_PCR_NUMBER_MASK.
Referenced by XLoader_HdrMeasurement, XLoader_MeasureNLoad, XLoader_UpdateDataMeasurement.
void XLoader_SetATFHandoffParameters(const XilPdi_PrtnHdr *PrtnHdr)
This function sets the handoff parameters to the ARM Trusted Firmware(ATF).
Some of the inputs for this are taken from image partition header. A pointer to the structure containing these parameters is stored in the PMC_GLOBAL.GLOBAL_GEN_STORAGE4 register, which ATF reads. PrtnHdr is pointer to Partition header details Some of the inputs for this are taken from image partition header. A pointer to the structure containing these parameters is stored in the PMC_GLOBAL.GLOBAL_GEN_STORAGE4 register, which ATF reads. PrtnHdr is pointer to Partition header details.
References XLoader_GetATFHandoffParamsAddr.
Referenced by XLoader_ProcessElf.
void XLoader_SetJtagTapToReset(void)
This function is used to run MJTAG solution workaround in which JTAG Tap state will be set to reset.
Referenced by XLoader_LoadImage.
int XLoader_GetSDPdiSrcNAddr(u32 SecBootMode, XilPdi *PdiPtr, u32 *PdiSrc, u64 *PdiAddr)
This function is used to get PdiSrc and PdiAddr for Secondary SD boot modes.
SecBootMode is the secondary boot mode value PdiPtr Pointer to PDI instance PdiSrc Pointer to the source of PDI PdiAddr is the pointer to the address of the Pdi XST_SUCCESS on success.XLOADER_ERR_UNSUPPORTED_SEC_BOOT_MODE on unsupported secondary bootmode. SecBootMode is the secondary boot mode value PdiPtr Pointer to the PDI instance PdiSrc is pointer to the source of PDI PdiAddr is the pointer to the address of the Pdi XST_SUCCESS on success.XLOADER_ERR_UNSUPPORTED_SEC_BOOT_MODE on unsupported secondary bootmode. SecBootMode is the secondary boot mode value. PdiPtr Pointer to PDI instance. PdiSrc Pointer to the source of PDI. PdiAddr is the pointer to the address of the Pdi. XST_SUCCESS on success.XLOADER_ERR_UNSUPPORTED_SEC_BOOT_MODE on unsupported secondary bootmode.
References XilPdi::MetaHdr, XLOADER_PDI_SRC_SD0, XLOADER_PDI_SRC_SD1, XLOADER_PDI_SRC_SD1_LS, XLOADER_SD_RAWBOOT_MASK.
int XLoader_ProcessElf(XilPdi *PdiPtr, const XilPdi_PrtnHdr *PrtnHdr, XLoader_PrtnParams *PrtnParams, XLoader_SecureParams *SecureParams)
This function copies the elf partitions to specified destinations.
PdiPtr is pointer to XilPdi instance PrtnHdr is pointer to the partition header PrtnParams is pointer to the structure variable that contains parameters required to process the partition SecureParams is pointer to the instance containing security related params XST_SUCCESS on success.XLOADER_ERR_INVALID_ELF_LOAD_ADDR if the load address of the elf is invalid.XLOADER_ERR_PM_DEV_PSM_PROC if device request for PSM is failed.XLOADER_ERR_PM_DEV_IOCTL_RPU0_SPLIT if IOCTL call to set RPU0 in split mode fails.XLOADER_ERR_PM_DEV_IOCTL_RPU1_SPLIT if IOCTL call to set RPU1 in split mode fails.XLOADER_ERR_PM_DEV_IOCTL_RPU0_LOCKSTEP if IOCTL call to set RPU0 in lockstep mode fails.XLOADER_ERR_PM_DEV_IOCTL_RPU1_LOCKSTEP if IOCTL call to set RPU1 in lockstep mode fails.XLOADER_ERR_INVALID_TCM_ADDR on Invalid TCM address for A72 elfs.XLOADER_ERR_INVALID_CPUID if invalid CPU id is selected. PdiPtr is pointer to XilPdi instance PrtnHdr is pointer to the partition header PrtnParams is pointer to the structure variable that contains parameters required to process the partition SecureParams is pointer to the instance containing security related params XST_SUCCESS on success.XLOADER_ERR_INVALID_ELF_LOAD_ADDR if load address of the elf is invalid.XLOADER_ERR_INVALID_R52_CLUSTER if invalid R52 cluster is selected.XLOADER_ERR_INVALID_CPUID if invalid CPU id is selected. PdiPtr is pointer to XilPdi instance. PrtnHdr is pointer to the partition header. PrtnParams is pointer to the structure variable that contains parameters required to process the partition. SecureParams is pointer to the instance containing security related params. XST_SUCCESS on success.XLOADER_ERR_INVALID_ELF_LOAD_ADDR if the load address of the elf is invalid.XLOADER_ERR_PM_DEV_PSM_PROC if device request for PSM is failed.XLOADER_ERR_PM_DEV_IOCTL_RPU0_SPLIT if IOCTL call to set RPU0 in split mode fails.XLOADER_ERR_PM_DEV_IOCTL_RPU1_SPLIT if IOCTL call to set RPU1 in split mode fails.XLOADER_ERR_PM_DEV_IOCTL_RPU0_LOCKSTEP if IOCTL call to set RPU0 in lockstep mode fails.XLOADER_ERR_PM_DEV_IOCTL_RPU1_LOCKSTEP if IOCTL call to set RPU1 in lockstep mode fails.XLOADER_ERR_INVALID_TCM_ADDR on Invalid TCM address for A72 elfs. XLOADER_ERR_INVALID_CPUID if invalid CPU id is selected. PdiPtr is pointer to XilPdi instance. PrtnHdr is pointer to the partition header. PrtnParams is pointer to the structure variable that contains parameters required to process the partition. SecureParams is pointer to the instance containing security related params. XST_SUCCESS on success.XLOADER_ERR_INVALID_ELF_LOAD_ADDR if the load address of the elf is invalid.XLOADER_ERR_PM_DEV_PSM_PROC if device request for PSM is failed.XLOADER_ERR_PM_DEV_IOCTL_RPU0_SPLIT if IOCTL call to set RPU0 in split mode fails.XLOADER_ERR_PM_DEV_IOCTL_RPU1_SPLIT if IOCTL call to set RPU1 in split mode fails.XLOADER_ERR_PM_DEV_IOCTL_RPU0_LOCKSTEP if IOCTL call to set RPU0 in lockstep mode fails.XLOADER_ERR_PM_DEV_IOCTL_RPU1_LOCKSTEP if IOCTL call to set RPU1 in lockstep mode fails.XLOADER_ERR_INVALID_TCM_ADDR on Invalid TCM address for A72 elfs. PdiPtr is pointer to XilPdi instance PrtnHdr is pointer to the partition header PrtnParams is pointer to the structure variable that contains parameters required to process the partition SecureParams is pointer to the instance containing security related params XST_SUCCESS on success.XLOADER_ERR_INVALID_ELF_LOAD_ADDR if load address of the elf is invalid.XLOADER_ERR_PM_DEV_PSM_PROC if device request for PSM is failed.XLOADER_ERR_INVALID_R52_CLUSTER if invalid R52 cluster is selected.XLOADER_ERR_INVALID_CPUID if invalid CPU id is selected.
References XilPdi::DelayHandoff, XLoader_DeviceCopy::DestAddr, XLoader_PrtnParams::DeviceCopy, XLoader_PrtnParams::DstnCpu, XLoader_ClearATFHandoffParams, XLoader_PrtnCopy, XLOADER_R5_0_TCM_A_BASE_ADDR, XLOADER_R5_0_TCM_A_END_ADDR, XLOADER_R5_0_TCM_B_BASE_ADDR, XLOADER_R5_0_TCM_B_END_ADDR, XLOADER_R5_1_TCM_A_BASE_ADDR, XLOADER_R5_1_TCM_A_END_ADDR, XLOADER_R5_1_TCM_B_BASE_ADDR, XLOADER_R5_1_TCM_B_END_ADDR, XLOADER_R5_LS_TCM_END_ADDR, XLOADER_RPU_GLBL_CNTL, XLoader_SetATFHandoffParameters, XLOADER_TCM_0, XLOADER_TCM_1, XLOADER_TCMCOMB_MASK, XLOADER_TCMCOMB_SHIFT, XLoader_UpdateHandoffParam.
int XLoader_UpdateHandoffParam(XilPdi *PdiPtr)
This function is used to update the handoff parameters.
PdiPtr is pointer to XilPdi instance XST_SUCCESS on success.XLOADER_ERR_NUM_HANDOFF_CPUS when number of CPUs exceed max count. PdiPtr is pointer to XilPdi instance XST_SUCCESS on success.XLOADER_ERR_NUM_HANDOFF_CPUS if number of CPUs exceeds max count. PdiPtr is pointer to XilPdi instance. XST_SUCCESS on success.XLOADER_ERR_NUM_HANDOFF_CPUS when number of CPUs exceed max count.
References XLoader_HandoffParam::CpuSettings, XLoader_HandoffParam::HandoffAddr, XilPdi::HandoffParam, XilPdi::MetaHdr, XilPdi::NoOfHandoffCpus, XilPdi::PrtnNum, XLOADER_MAX_HANDOFF_CPUS.
Referenced by XLoader_ProcessElf.
u8 XLoader_SkipMJtagWorkAround(XilPdi *PdiPtr)
This function checks if MJTAG workaround partition needs to be skipped.
PdiPtr is pointer to PDI instance TRUE if MTAG workaround partition needs to be skipped, else FALSE PdiPtr is pointer to PDI instance. TRUE if MTAG workaround partition needs to be skipped, else FALSE.
References XilPdi::ImageNum, XilPdi::MetaHdr, XilPdi::PdiSrc, XLOADER_PDI_SRC_JTAG.
int XLoader_ProcessDeferredError(void)
This function checks if MJTAG workaround is required.
XLOADER_ERR_DEFERRED_CDO_PROCESS on error while processing CDO but error is deferred till whole CDO processing is completed.
References XLoader_DumpDdrmcRegisters.
void XLoader_PerformInternalPOR(void)
This function check conditions and perform internal POR for VP1802 and VP1502 device if required.
References PdiSrc_t, PLM_VP1802_POR_SETTLE_TIME, XLOADER_PDI_SRC_JTAG, XLOADER_PDI_SRC_SMAP.
int Xloader_SsitEoPdiSync(XilPdi *PdiPtr)
This function will sync the PDI load status with master if End of PDI SYNC bit is enabled in IHT.
PdiPtr is pointer to PDI instance -XST_SUCCESS if no issue in EoPDI sync -XPLMI_ERR_SSIT_EOPDI_SYNC if error in EoPDI Sync
References XilPdi::MetaHdr, XilPdi::SlrType, XLOADER_SSIT_MONOLITIC.
void XLoader_ShaInstance1Reset(void)
This Function does the following:
It resets the SHA instance 1.It puts the SHA instance 1 into initialized state.
Referenced by XLoader_LoadImage.
static void XLoader_I2Osp(u32 Integer, u32 Size, u8 *Convert)
This function converts a non-negative integer to an octet string of a specified length.
Integer is the variable in which input should be provided. Size holds the required size. Convert is a pointer in which output will be updated.
u32 XLoader_GetKekSrc(void)
This function updates KEK red key availability status from boot header.
Decryption Key source status.
References XLOADER_BBRAM_BLK_KEY, XLOADER_BBRAM_RED_KEY, XLOADER_BH_BLK_KEY, XLOADER_BHDR_RED_KEY, XLOADER_EFUSE_BLK_KEY, XLOADER_EFUSE_RED_KEY.
int XLoader_AesObfusKeySelect(u32 PdiKeySrc, u32 DecKeyMask, void *KeySrcPtr)
This function provides Obfuscated Aes Key source.
PdiKeySrc is the Key source given in Pdi DecKeyMask is the current DecKeyMask KeySrcPtr is the pointer to the calculated KeySrc XST_SUCCESS on success and error code on failure PdiKeySrc is the Key source given in Pdi DecKeyMask is the current DecKeyMask KeySrcPtr is the pointer to the calculated KeySrc XST_SUCCESS on success and error code on failure PdiKeySrc is the Key source given in Pdi. DecKeyMask is the current DecKeyMask. KeySrcPtr is the pointer to the calculated KeySrc. XST_SUCCESS on success and error code on failure.
References XLOADER_SEC_AES_KEK_DEC.
int XLoader_RsaKat(void)
This function runs the KAT for RSA.
XST_SUCCESS on success and error code on failure XST_SUCCESS on success and error code on failure
int XLoader_MaskGenFunc(XSecure_Sha3 *Sha3InstancePtr, u8 *Out, u32 OutLen, u8 *Input)
Mask generation function with SHA3.
Sha3InstancePtr is pointer to the XSecure_Sha3 instance. Out is pointer in which output of this function will be stored. OutLen specifies the required length. Input is pointer which holds the input data for which mask should be calculated which should be 48 bytes length. XST_SUCCESS on success.XLOADER_SEC_BUF_CLEAR_ERR if failed to clear buffer. Sha3InstancePtr is pointer to the XSecure_Sha3 instance. Out is pointer in which output of this function will be stored. OutLen specifies the required length. Input is pointer which holds the input data for which mask should be calculated which should be 48 bytes length. XST_SUCCESS on success.Errorcode on failure.
int XLoader_CheckSecureStateAuth(volatile u32 *AHWRoT)
This function checks Secure State for Authentication.
AHWRoT - Buffer to store Secure state for authentication XST_SUCCESS on success.XLOADER_ERR_HWROT_BH_AUTH_NOT_ALLOWED if PPK is programmed and boot header authentication is enabled. AHWRoT - Buffer to store Secure state for authentication XST_SUCCESS on success. XLOADER_ERR_GLITCH_DETECTED if glitch is detected. AHWRoT - Buffer to store Secure state for authentication. XST_SUCCESS on success.XLOADER_ERR_HWROT_BH_AUTH_NOT_ALLOWED if PPK is programmed and boot header authentication is enabled. AHWRoT Buffer to store Secure state for authentication. XST_SUCCESS on success.XLOADER_ERR_GLITCH_DETECTED if glitch is detected.
References XLoader_CheckNonZeroPpk.
Referenced by XLoader_SetSecureState.
static int XLoader_CheckHandoffCpu(const XilPdi *PdiPtr, const u32 DstnCpu, const u32 DstnCluster)
This function is used to check whether cpu has handoff address stored in the handoff structure.
PdiPtr is pointer to XilPdi instance DstnCpu is the cpu which needs to be checked DstnCluster is the cluster which needs to be checked XST_SUCCESS if the DstnCpu is successfully added to Handoff list.XST_FAILURE if the DstnCpu is already added to Handoff list
static int XLoader_InitTrngInstance(void)
This function initializes the Trng instance.
XST_SUCCESS on success.XLOADER_TRNG_INIT_FAIL if TRNG initialization fails.
int XLoader_ReadDdrCryptoPerfCounters(XPlmi_Cmd *Cmd)
This function reads DDR crypto performance counters of given DDR device id.
Cmd is pointer to the command structure XST_SUCCESS on success. ErrorCode on Failure.
References XLOADER_CMD_GET_DDR_DEVICE_ID, XLOADER_DDR_CRYPTO_MAIN_OFFSET, XLOADER_DDR_PERF_MON_CNT0_OFFSET, XLOADER_DDR_PERF_MON_CNT1_OFFSET, XLOADER_DDR_PERF_MON_CNT2_OFFSET, XLOADER_DDR_PERF_MON_CNT3_OFFSET, XLOADER_ERR_DDR_DEVICE_ID, XLOADER_ERR_PCOMPLETE_NOT_DONE.
int XLoader_UpdateHandler(XPlmi_ModuleOp Op)
This function provides update handler for xilloader.
Op is the module operation variable XST_SUCCESS on success and error code on failure
References XLOADER_AUTH_JTAG_INT_STATUS_POLL_INTERVAL, XLoader_CheckDeviceStateChange, XLOADER_DEVICE_STATE_POLL_INTERVAL.
int XLoader_PlatInit(void)
This function initializes the loader with platform specific initializations.
XST_SUCCESS on success and error code on failure XST_SUCCESS always. XST_SUCCESS on success.Error code on failure.
int XLoader_HdrMeasurement(XilPdi *PdiPtr)
This function measures the PDI's meta header data by calculating the hash using SHA3.
PdiPtr is the pointer to PDI instance XST_SUCCESS on success.XLOADER_ERR_HDR_MEASUREMENT if error in meta header measurement.
References XLoader_ImageMeasureInfo::DataAddr, XLoader_ImageMeasureInfo::DataSize, XLoader_ImageMeasureInfo::Flags, XilPdi::MetaHdr, XLoader_ImageMeasureInfo::PcrInfo, XLoader_ImageMeasureInfo::SubsystemID, XLoader_DataMeasurement, XLOADER_MEASURE_FINISH, XLOADER_MEASURE_START, XLOADER_MEASURE_UPDATE.
int XLoader_SecureConfigMeasurement(XLoader_SecureParams *SecurePtr, u32 PcrInfo, u32 *DigestIndex, u32 OverWrite)
This function measures the Secure Configuration that is SPK, SPK ID and Encryption Revoke ID and extends to the specified PCR.
SecurePtr Pointer to the XLoader_SecureParams instance. PcrInfo Provides the PCR number and Measurement Index to be extended. DigestIndex Pointer to the DigestIndex across the PCR OverWrite TRUE or FALSE to overwrite the extended digest or not XST_SUCCESS on success.XLOADER_ERR_SECURE_CONFIG_MEASUREMENT if error in Secure config measurement. SecurePtr is pointer to the XLoader_SecureParams instance. PcrInfo provides the PCR number and Measurement Index to be extended. DigestIndex is pointer to the DigestIndex across the PCR. OverWrite TRUE or FALSE to overwrite the extended digest or not. XST_SUCCESS on success.XLOADER_ERR_SECURE_CONFIG_MEASUREMENT if error in Secure config measurement. SecurePtr is pointer to the XLoader_SecureParams instance. PcrInfo provides the PCR number and Measurement Index to be extended. DigestIndex is pointer to the DigestIndex across the PCR OverWrite TRUE or FALSE to overwrite the extended digest or not XST_SUCCESS on success.XLOADER_ERR_SECURE_CONFIG_MEASUREMENT if error in Secure config measurement.
References XLoader_SecureParams::IsAuthenticated, XLoader_SecureParams::IsEncrypted, XLOADER_EFUSE_ROM_RSVD_AUTH_KEYS_TO_HASH_MASK, XLOADER_EFUSE_ROM_RSVD_AUTH_KEYS_TO_HASH_SHIFT, XLOADER_EFUSE_ROM_RSVD_CACHE_ADDRESS.
int XLoader_ConfigureJtagState(XPlmi_Cmd *Cmd)
This function enables or disable Jtag Access Command payload parameters are.
- Flag (enable / disable) Cmd is pointer to the command structure XST_SUCCESS on success.XLOADER_ERR_INVALID_JTAG_OPERATION
References XLOADER_CMD_CONFIG_JTAG_STATE_FLAG_INDEX, XLOADER_CMD_CONFIG_JTAG_STATE_FLAG_MASK, XLOADER_CONFIG_DAP_STATE_NONSECURE_DBG, XLOADER_CONFIG_JTAG_STATE_FLAG_DISABLE, XLOADER_CONFIG_JTAG_STATE_FLAG_ENABLE, XLoader_DisableJtag, XLoader_EnableJtag, XLOADER_ERR_INVALID_JTAG_OPERATION, XLOADER_PMC_TAP_LOCK_ADDR, XLOADER_PMC_TAP_LOCK_VAL, XLOADER_PMC_TAP_UNLOCK_VAL.
int XLoader_CheckAndUpdateSecureState(void)
This function checks and updates the secure state configuration.
XST_SUCCESS on success.Error code on failure
References XLOADER_SEC_STATE_CONFIG_MEASUREMENT_ERROR.
Referenced by XLoader_CheckDeviceStateChange.
int XLoader_LoadAsuImage(void)
This function loads the ASU firmware image from DDR during In-Place ASU Update.
XST_SUCCESS on success.Error code on failure
References XilPdi::NoOfHandoffCpus, XilPdi::PdiType, XLOADER_ERR_MEMSET_PDIPTR, XLoader_GetImageAndPrtnInfo, XLoader_GetPdiInstance, XLoader_LoadImage, XLOADER_PDI_SRC_DDR, XLoader_PdiInit.
static int XLoader_RsaPssSignVeirfyKat(void)
This function runs the KAT for RSA PSS verification.
XST_SUCCESS on success and error code on failure
int XLoader_AddDeviceStateChangeToScheduler(void)
This function adds periodic checks of the device status change during secure boot.
XST_SUCCESS on success. XLOADER_ERR_ADD_TASK_SCHEDULER if failed to add task to scheduler.
References XLoader_CheckDeviceStateChange, XLOADER_DEVICE_STATE_POLL_INTERVAL, XLOADER_EFUSE_CACHE_JTAG_DIS_MASK, XLOADER_EFUSE_CACHE_SECURITY_CONTROL_OFFSET, XLoader_GetAHWRoT, XLoader_GetSHWRoT.
Referenced by XLoader_Init.
int XLoader_CheckDeviceStateChange(void *Arg)
This function checks the JTAG device state change.
When Secure gate is opened from close state this API raises an error, if the gate is closed and re-opened again this function recognizes the state change and performs the action configured. Arg is of pointer of void type. XST_SUCCESS on success and error code on failure
References XLoader_CheckAndUpdateSecureState, XLOADER_JTAG_SEC_GATE_CLOSE, XLOADER_JTAG_SEC_GATE_OPEN, XLOADER_PMC_TAP_JTAG_STATUS_0, XLOADER_PMC_TAP_JTAG_STATUS_DAP_STATUS_MASK.
Referenced by XLoader_AddDeviceStateChangeToScheduler, XLoader_UpdateHandler.
int XLoader_MaskGenFunc(XSecure_Sha *ShaInstancePtr, u8 *Out, u32 OutLen, u8 *Input)
Mask generation function with SHA3.
ShaInstancePtr is pointer to the XSecure_Sha3 instance. Out is pointer in which output of this function will be stored. OutLen specifies the required length. Input is pointer which holds the input data for which mask should be calculated which should be 48 bytes length. XST_SUCCESS on success.Errorcode on failure.
int XLoader_LoadLpdAndPsmElf(void)
This function will load the LPD and PSM ELF file from DDR.
XST_SUCCESS on success.Error code on failure
References XilPdi::NoOfHandoffCpus, XilPdi::PdiType, XLOADER_ERR_MEMSET_PDIPTR, XLoader_GetImageAndPrtnInfo, XLoader_GetPdiInstance, XLoader_LoadImage, XLOADER_PDI_SRC_DDR, XLoader_PdiInit.
XLOADER_IMAGE_INFO_TBL_MAX_NUM
Maximum number of image info tables in the available buffer.
Referenced by XLoader_GetImageInfoEntry.
XLOADER_RSA_PSS_MSB_PADDING_MASK
RSA PSS MSB padding mask.
XLOADER_RSA_EM_MSB_INDEX
RSA EM MSB Index.
XLOADER_PUF_SHUT_GLB_VAR_FLTR_EN_SHIFT
Shift for Global Variation Filter in PUF shutter value.
XLOADER_AES_RESET_VAL
AES Reset value.
XLOADER_AES_RESET_REG
AES Reset register address.
XLOADER_ECDSA_RSA_RESET_REG
ECDSA RSA Reset register address.
XLOADER_ECDSA_RSA_RESET_VAL
ECDSA RSA Reset value.
XLOADER_GET_PRTN_HASH_INDEX
Get partition hash index depending on full/IPU/partial/full metaheader PDI.
CFRAME_BCAST_REG_TESTMODE_OFFSET
Test mode offset.
Referenced by XLoader_CframeDataClearCheck.
CFRAME_BCAST_REG_TESTMODE_CRAM_SELF_CHECK_MASK
CRAM self check mask.
Referenced by XLoader_CframeDataClearCheck.
CFRAME_BCAST_REG_FAR_OFFSET
CFrame address register offset.
Referenced by XLoader_CframeDataClearCheck.
CFRAME_BCAST_REG_FAR_BLOCKTYPE_SHIFT
CFrame address register block type shift.
Referenced by XLoader_CframeDataClearCheck.
CFRAME_MAX_BLOCK_TYPE_COUNT
CFrame maximum block type count.
Referenced by XLoader_CframeDataClearCheck.
XPLMI_ZERO
Zero.
Referenced by XLoader_CframeDataClearCheck.
CFRAME_CRC_POLL_TIMEOUT
CRC poll time out.
Referenced by XLoader_CframeDataClearCheck.
XLOADER_CFRAME_DATACLEAR_CHECK_CMD_ID
Data clear check command Id.
Referenced by XLoader_CframeDataClearCheck.
PMC_GLOBAL_PMC_ERR2_STATUS_CFI_SHIFT
CFI Non-Correctable Error shift.
Referenced by XLoader_CframeErrorHandler.
XLOADER_SBI_DELAY_IN_MICROSEC
Flag indicates SBI delay in micro second.
XLOADER_LOG_LEVEL_MASK
Flag indicates Log level mask.
XLOADER_SBI_CTRL_INTERFACE_AXI_SLAVE
SBI PCIE PDI load.
XLOADER_SUCCESS_NOT_PRTN_OWNER
Indicates that PLM is not the partition owner.
Referenced by XLoader_LoadImagePrtns.
XLOADER_BOOT_COPY_OPTIMIZATION_ENABLED
Indicates Boot Device Copy Optimization is Enabled.
Referenced by XLoader_PrtnCopy.
XLOADER_SHA3_RESET_REG
SHA3 Reset register address.
Referenced by XLoader_SecureClear.
XLOADER_SHA3_RESET_VAL
SHA3 Reset value.
Referenced by XLoader_SecureClear.
XLOADER_TCM_0
TCM 0.
Referenced by XLoader_ProcessElf.
XLOADER_TCM_1
TCM 1.
Referenced by XLoader_ProcessElf.
XLOADER_RPU_GLBL_CNTL
RPU global control.
Referenced by XLoader_ProcessElf.
XLOADER_TCMCOMB_MASK
TCM combine mask.
Referenced by XLoader_ProcessElf.
XLOADER_TCMCOMB_SHIFT
TCM combine shift.
Referenced by XLoader_ProcessElf.
PLM_VP1802_POR_SETTLE_TIME
Flag indicates POR settle time for VP1802.
Referenced by XLoader_PerformInternalPOR.
XLOADER_IMAGE_INFO_VERSION
Image version information.
XLOADER_IMAGE_INFO_LCVERSION
Image lowest compatible version information.
XLOADER_PDI_LIST_VERSION
PDI version list.
XLOADER_PDI_LIST_LCVERSION
PDI lowest compatible version list.
XLOADER_ATF_HANDOFF_PARAMS_VERSION
ATF handoff parameters version.
XLOADER_ATF_HANDOFF_PARAMS_LCVERSION
ATF handoff parameters lowest compatible version.
XLOADER_BOOTPDI_INFO_PARAMS_VERSION
BootPDI info version.
XLOADER_BOOTPDI_INFO_PARAMS_LCVERSION
BootPDI info lowest compatible version.
XLOADER_CMD_GET_DDR_DEVICE_ID
DDR device id.
Referenced by XLoader_ReadDdrCryptoPerfCounters.
XLOADER_DDR_CRYPTO_MAIN_OFFSET
DDR crypto block offset from ub.
Referenced by XLoader_ReadDdrCryptoPerfCounters.
XLOADER_DDR_PERF_MON_CNT0_OFFSET
Counter 0 offset.
Referenced by XLoader_ReadDdrCryptoPerfCounters.
XLOADER_DDR_PERF_MON_CNT1_OFFSET
Counter 1 offset.
Referenced by XLoader_ReadDdrCryptoPerfCounters.
XLOADER_DDR_PERF_MON_CNT2_OFFSET
Counter 2 offset.
Referenced by XLoader_ReadDdrCryptoPerfCounters.
XLOADER_DDR_PERF_MON_CNT3_OFFSET
Counter 3 offset.
Referenced by XLoader_ReadDdrCryptoPerfCounters.
XLOADER_CMD_CONFIG_JTAG_STATE_FLAG_INDEX
Index in the Payload of ConfigureJtagState command where JTAG state flag is present.
Referenced by XLoader_ConfigureJtagState.
XLOADER_CMD_CONFIG_JTAG_STATE_FLAG_MASK
Mask for JTAG state flag.
Referenced by XLoader_ConfigureJtagState.
XLOADER_CONFIG_JTAG_STATE_FLAG_ENABLE
Value of JTAG state flag if enabled.
Referenced by XLoader_ConfigureJtagState.
XLOADER_CONFIG_JTAG_STATE_FLAG_DISABLE
Value of JTAG state flag if disabled.
Referenced by XLoader_ConfigureJtagState.
XLOADER_TRNG_DEVICE_ID
TRNG Device Id.
XLOADER_PCR_MEASUREMENT_INDEX_MASK
Mask for PCR Measurement index.
Referenced by XLoader_MeasureNLoad.
XLOADER_PCR_MEASUREMENT_INDEX_SHIFT
Shift for PCR measurement index.
Referenced by XLoader_MeasureNLoad.
XLOADER_EFUSE_ROM_RSVD_CACHE_ADDRESS
ROM Reserved eFuse cache offset.
Referenced by XLoader_SecureConfigMeasurement.
XLOADER_EFUSE_ROM_RSVD_AUTH_KEYS_TO_HASH_MASK
AUTH_KEYS_TO_HASH eFuse bit mask.
Referenced by XLoader_SecureConfigMeasurement.
XLOADER_EFUSE_ROM_RSVD_AUTH_KEYS_TO_HASH_SHIFT
AUTH_KEYS_TO_HASH eFuse bit shift.
Referenced by XLoader_SecureConfigMeasurement.
XLOADER_EFUSE_OBFUS_KEY
eFuse obfuscated key
XLOADER_BBRAM_OBFUS_KEY
BBRAM obfuscated key.
XLOADER_BH_OBFUS_KEY
Boot header obfuscated key.
XLOADER_INVALID_OBFUS_KEY
Invalid obfuscated key.
XLOADER_TCM_0
TCM 0.
XLOADER_TCM_1
TCM 1.
XLOADER_RPU_GLBL_CNTL
RPU global control.
XLOADER_TCMCOMB_MASK
TCM combine mask.
XLOADER_TCMCOMB_SHIFT
TCM combine shift.
PLM_VP1802_POR_SETTLE_TIME
Flag indicates POR settle time for VP1802.
XLOADER_TCM_0
TCM 0.
XLOADER_TCM_1
TCM 1.
XLOADER_RPU_GLBL_CNTL
RPU global control.
XLOADER_TCMCOMB_MASK
TCM combine mask.
XLOADER_TCMCOMB_SHIFT
TCM combine shift.
XLOADER_TRNG_DEVICE_ID
TRNG Device Id.
PLM_VP1802_POR_SETTLE_TIME
Flag indicates POR settle time for VP1802.
XLOADER_EFUSE_OBFUS_KEY
eFuse obfuscated key
XLOADER_BBRAM_OBFUS_KEY
BBRAM obfuscated key.
XLOADER_BH_OBFUS_KEY
Boot header obfuscated key.
XLOADER_INVALID_OBFUS_KEY
Invalid obfuscated key.
XLOADER_IMAGE_INFO_VERSION
Image version information.
XLOADER_IMAGE_INFO_LCVERSION
Image lowest compatible version information.
XLOADER_PDI_LIST_VERSION
PDI version list.
XLOADER_PDI_LIST_LCVERSION
PDI lowest compatible version list.
XLOADER_ATF_HANDOFF_PARAMS_VERSION
ATF handoff parameters version.
XLOADER_ATF_HANDOFF_PARAMS_LCVERSION
ATF handoff parameters lowest compatible version.
XLOADER_BOOTPDI_INFO_PARAMS_VERSION
BootPDI info version.
XLOADER_BOOTPDI_INFO_PARAMS_LCVERSION
BootPDI info lowest compatible version.
XLOADER_CMD_GET_DDR_DEVICE_ID
DDR device id.
XLOADER_DDR_CRYPTO_MAIN_OFFSET
DDR crypto block offset from ub.
XLOADER_DDR_PERF_MON_CNT0_OFFSET
Counter 0 offset.
XLOADER_DDR_PERF_MON_CNT1_OFFSET
Counter 1 offset.
XLOADER_DDR_PERF_MON_CNT2_OFFSET
Counter 2 offset.
XLOADER_DDR_PERF_MON_CNT3_OFFSET
Counter 3 offset.
XLOADER_CMD_CONFIG_JTAG_STATE_FLAG_INDEX
Index in the Payload of ConfigureJtagState command where JTAG state flag is present.
XLOADER_CMD_CONFIG_JTAG_STATE_FLAG_MASK
Mask for JTAG state flag.
XLOADER_CONFIG_JTAG_STATE_FLAG_ENABLE
Value of JTAG state flag if enabled.
XLOADER_CONFIG_JTAG_STATE_FLAG_DISABLE
Value of JTAG state flag if disabled.
XLOADER_EFUSE_ROM_RSVD_CACHE_ADDRESS
ROM Reserved eFuse cache offset.
XLOADER_EFUSE_ROM_RSVD_AUTH_KEYS_TO_HASH_MASK
AUTH_KEYS_TO_HASH eFuse bit mask.
XLOADER_EFUSE_ROM_RSVD_AUTH_KEYS_TO_HASH_SHIFT
AUTH_KEYS_TO_HASH eFuse bit shift.
XLOADER_PCR_MEASUREMENT_INDEX_MASK
Mask for PCR Measurement index.
XLOADER_PCR_MEASUREMENT_INDEX_SHIFT
Shift for PCR Measurement index.
XLOADER_EFUSE_OBFUS_KEY
eFuse obfuscated key
XLOADER_BBRAM_OBFUS_KEY
BBRAM obfuscated key.
XLOADER_BH_OBFUS_KEY
Boot header obfuscated key.