xloader_client_apis
XSecure_ClientInstance SecureClientInstance
Secure client instance used for XilSecure IPI operations.
u8 Sha3Hash[XLOADER_SHA3_HASH_LEN_IN_BYTES][XLOADER_SHA3_HASH_LEN_IN_BYTES]
SHA3 digest output buffer aligned to 64 bytes and placed in .data.Sha3Hash section.
The attributes ensure alignment and linker section placement for secure hash operations.
u8 NextHash[XLOADER_SHA3_HASH_LEN_IN_BYTES][XLOADER_SHA3_HASH_LEN_IN_BYTES]
Buffer holding trailing hash bytes for chunked verification.
XilLoader_HBSignParams HBSignParams
Hash Block authentication certificate parameters aligned to 64 bytes.
XilLoader_HashBlock HashBlock0
Boot Header Hash Block 0 storage aligned to 64 bytes and placed in .data.HashBlock0 section.
XilLoader_HashBlock HashBlock
Authenticated hash block storage aligned to 64 bytes and placed in .data.HashBlock section.
XSecure_ClientInstance SecureClientInstance
u8 NextHash[XLOADER_SHA3_HASH_LEN_IN_BYTES][XLOADER_SHA3_HASH_LEN_IN_BYTES]
u8 Sha3Hash[XLOADER_SHA3_HASH_LEN_IN_BYTES][XLOADER_SHA3_HASH_LEN_IN_BYTES]
int XLoader_LoadPartialPdi(XLoader_ClientInstance *InstancePtr, XLoader_PdiSrc PdiSrc, u64 PdiAddr, u32 *PlmErrStatus)
This function sends IPI request to provides PDI execution.
InstancePtr Pointer to the client instance. PdiSrc Boot Mode values, DDR, PCIe. PdiAddr 64bit PDI address located in the Source. PlmErrStatus Used to store the plm error status. XST_SUCCESS on success.XST_FAILURE on failure.
References PAYLOAD_ARG_CNT, RESPONSE_ARG_CNT, XLOADER_ADDR_HIGH_SHIFT, XLOADER_CMD_ID_LOAD_SUBSYSTEM_PDI, XLoader_SendRequest.
int XLoader_LoadImage(XLoader_ClientInstance *InstancePtr, u32 NodeId, u32 FunctionId)
This function sends IPI request to Load image.
InstancePtr Pointer to the client instance. NodeId Node id of ddr copied image. FunctionId To verify with the FuncID of the image copied to DDR. XST_SUCCESS on success.XST_FAILURE on failure.
References PAYLOAD_ARG_CNT, XLOADER_CMD_ID_LOAD_DDRCPY_IMG, XLoader_SendRequest.
Referenced by XLoader_LoadAsuImage, XLoader_LoadLpdAndPsmElf.
int XLoader_GetImageInfo(XLoader_ClientInstance *InstancePtr, u32 NodeId, XLoader_ImageInfo *ImageInfo)
This function sends IPI request to get image information.
InstancePtr Pointer to the client instance. NodeId Node id of ddr copied image. ImageInfo Pointer to the structure XLoader_ImageInfo which is used to store the image information. XST_SUCCESS on success.XST_FAILURE on failure.
References XLoader_ImageInfo::FuncID, XLoader_ImageInfo::ImgID, PAYLOAD_ARG_CNT, XLoader_ImageInfo::PUID, RESPONSE_ARG_CNT, XLoader_ImageInfo::UID, XLOADER_CMD_ID_GET_IMAGE_INFO, XLoader_SendRequest.
int XLoader_GetImageInfoList(XLoader_ClientInstance *InstancePtr, u64 Buff_Addr, u32 Maxsize, u32 *NumEntries)
This function sends IPI request to gets ImageInfo Table.
InstancePtr Pointer to the client instance. Buff_Addr Buffer address to copy the ImageInfo. Maxsize Maximum size requires in bytes. NumEntries To get the number of entries returned. XST_SUCCESS on success.XST_FAILURE on failure.
References PAYLOAD_ARG_CNT, RESPONSE_ARG_CNT, XLOADER_ADDR_HIGH_SHIFT, XLOADER_CMD_ID_GET_IMAGE_INFO_LIST, XLOADER_MSB_MASK, XLoader_SendRequest.
int XLoader_ExtractMetaheader(XLoader_ClientInstance *InstancePtr, u64 PdiSrcAddr, u64 DestBuffAddr, u32 DestBuffSize)
This function sends IPI request to Extract meta header.
InstancePtr Pointer to the client instance. PdiSrcAddr Address of the pdi. DestBuffAddr Address to export the pdi. DestBuffSize size of the destination buffer in bytes. XST_SUCCESS on success.XST_FAILURE on failure.
References PAYLOAD_ARG_CNT, XLOADER_ADDR_HIGH_SHIFT, XLOADER_CMD_ID_EXTRACT_METAHEADER, XLoader_SendRequest.
int XLoader_UpdateMultiboot(XLoader_ClientInstance *InstancePtr, XLoader_PdiSrc BootMode, XLoader_FlashType Type, u32 ImageLocation)
This function sends IPI request to update multiboot.
InstancePtr Pointer to the client instance. BootMode Pdi boot source Type Flash type ImageLocation Location of Image in the boot device. XST_SUCCESS on success.XST_FAILURE on failure.
References PAYLOAD_ARG_CNT, XLOADER_CMD_ID_UPDATE_MULTIBOOT, XLoader_SendRequest.
Referenced by main.
int XLoader_AddImageStorePdi(XLoader_ClientInstance *InstancePtr, u32 PdiId, const u64 PdiAddr, u32 PdiSize)
This function sends IPI request to add Image store pdi.
InstancePtr Pointer to the client instance. PdiId Id of the pdi. PdiAddr Address to store Image store pdi's maintained by PLM. PdiSize Size of pdi in words. XST_SUCCESS on success.XST_FAILURE on failure.
References PAYLOAD_ARG_CNT, XLOADER_ADDR_HIGH_SHIFT, XLOADER_CMD_ID_ADD_IMAGESTORE_PDI, XLoader_SendRequest.
Referenced by main.
int XLoader_RemoveImageStorePdi(XLoader_ClientInstance *InstancePtr, u32 PdiId)
This function sends IPI request to remove Image store pdi.
InstancePtr Pointer to the client instance. PdiId Id of the PDI to be removed from Image Store. XST_SUCCESS on success.XST_FAILURE on failure.
References PAYLOAD_ARG_CNT, XLOADER_CMD_ID_REMOVE_IMAGESTORE_PDI, XLoader_SendRequest.
int XLoader_GetATFHandOffParams(XLoader_ClientInstance *InstancePtr, u64 BuffAddr, u32 Size, u32 *BufferSize)
This function sends IPI request to get ATF Handoff parameters.
InstancePtr Pointer to the client instance (Input). BuffAddr Address to store the handoff parameter information (Input). Size Maximum number of bytes that can be stored in the buffer (Input). BufferSize To get the size of the buffer in bytes (Output). XST_SUCCESS on success.XST_FAILURE on failure.
References PAYLOAD_ARG_CNT, RESPONSE_ARG_CNT, XLOADER_ADDR_HIGH_SHIFT, XLOADER_CMD_ID_GET_ATF_HANDOFF_PARAMS, XLoader_SendRequest.
int XLoader_CfiSelectiveReadback(XLoader_ClientInstance *InstancePtr, XLoader_CfiSelReadbackParams *SelectiveReadbackPtr)
This function sends IPI request to read selective frames from configuration memory.
InstancePtr Pointer to the client instance SelectiveReadbackPtr Pointer to structure which contains parameters of CFI selective readback command XST_SUCCESS on success.XST_FAILURE on failure.
References XLoader_CfiSelReadbackParams::Blocktype, XLoader_CfiSelReadbackParams::DestAddr, XLoader_CfiSelReadbackParams::FrameAddr, XLoader_CfiSelReadbackParams::FrameCnt, PAYLOAD_ARG_CNT, XLoader_CfiSelReadbackParams::Row, XLoader_ClientInstance::SlrIndex, XLOADER_ADDR_HIGH_SHIFT, XLOADER_CFI_SEL_READBACK_ID, XLOADER_SELREADBACK_BLKTYPE_START_POS, XLOADER_SELREADBACK_ROW_MASK, XLOADER_SELREADBACK_ROW_START_POS, XLoader_SendRequest, XLOADER_SLEREADBACK_BLKTYPE_MASK, XLOADER_SLEREADBACK_FRAMEADDR_MASK, XLOADER_SLR_INDEX_SHIFT.
int XLoader_InputSlrIndex(XLoader_ClientInstance *InstancePtr, u32 SlrIndex)
Adds the SLR Index.
InstancePtr is a pointer to instance XLoader_ClientInstance SlrIndex - SLR index number - XST_SUCCESS - On valid input SlrIndex. XST_FAILURE - On non valid input SlrIndex
References XLoader_ClientInstance::SlrIndex, XLOADER_SLR_INDEX_3.
int XLoader_GetOptionalData(XLoader_ClientInstance *InstancePtr, const XLoader_OptionalDataInfo *OptionalDataInfo, u64 DestAddr, u32 *DestSize)
This function sends IPI request to get optional data from the PDI available in DDR or Image Store.
InstancePtr Pointer to the client instance. OptionalDataInfo Pointer to XLoader_OptionalDataInfo structure DestAddr Address of the output buffer wheren optional data shall be copied DestSize Size of destination buffer in bytes XST_SUCCESS on success.XST_FAILURE on failure.
References XLoader_OptionalDataInfo::DataId, PAYLOAD_ARG_CNT, XLoader_OptionalDataInfo::PdiAddrHigh, XLoader_OptionalDataInfo::PdiAddrLow, XLoader_OptionalDataInfo::PdiId, XLoader_OptionalDataInfo::PdiSrc, RESPONSE_ARG_CNT, XLOADER_ADDR_HIGH_SHIFT, XLOADER_CMD_ID_EXTRACT_METAHEADER, XLOADER_DATA_ID_SHIFT, XLOADER_GET_OPT_DATA_FLAG, XLOADER_PDI_SRC_DDR, XLOADER_PDI_SRC_IS, XLOADER_PDI_SRC_OSPI, XLoader_SendRequest.
int XLoader_SendRequest(XLoader_ClientInstance *InstancePtr, u32 *PayloadBuf, u32 PayloadLen, u32 *ResponseBuf, u32 ResponseLen)
This function sends request to PLM through either SMC or IPI mailbox based on the execution environment.
For EL1 non-secure AArch64 applications, SMC is used. For other environments, IPI mailbox is used. InstancePtr Pointer to the client instance PayloadBuf Pointer to the payload message PayloadLen Length of the payload message ResponseBuf Pointer to store response values (can be NULL) ResponseLen Length of the response buffer (can be 0 if ResponseBuf is NULL) XST_SUCCESS If the request is successfulXST_FAILURE If there is a failureXST_INVALID_PARAM If input parameters are invalid
References XLoader_ClientInstance::MailboxPtr, XLoader_ClientInstance::Response, RESPONSE_ARG_CNT, XLoader_ProcessMailbox.
Referenced by XLoader_AddImageStorePdi, XLoader_CfiSelectiveReadback, XLoader_ExtractMetaheader, XLoader_GetATFHandOffParams, XLoader_GetImageInfo, XLoader_GetImageInfoList, XLoader_GetOptionalData, XLoader_LoadImage, XLoader_LoadPartialPdi, XLoader_RemoveImageStorePdi, XLoader_UpdateMultiboot.
int XLoader_ProcessMailbox(XLoader_ClientInstance *ClientPtr, u32 *MsgPtr, u32 MsgLen)
This function sends IPI request to the target module and gets the response from it.
ClientPtr Pointer to the client instance. MsgPtr Pointer to the payload message. MsgLen Length of the message. XST_SUCCESS - If the IPI send and receive is successful.XST_FAILURE - If there is a failure. Payload consists of API id and call arguments to be written in IPI buffer.
References XLoader_ClientInstance::MailboxPtr, XLoader_ClientInstance::Response, RESPONSE_ARG_CNT, XLOADER_TARGET_IPI_INT_MASK.
Referenced by XLoader_ConfigureJtagState, XLoader_ReadDdrCryptoPerfCounters, XLoader_SendRequest.
int XLoader_ClientInit(XLoader_ClientInstance *InstancePtr, XMailbox *MailboxPtr)
This function sets the instance of mailbox.
InstancePtr Pointer to the client instance. MailboxPtr Pointer to the mailbox instance. XST_SUCCESS On successful initialization.XST_FAILURE On failure.
References XLoader_ClientInstance::MailboxPtr.
Referenced by main.
static int XLoader_ComputeSha3Hash(u64 DataAddr, u32 DataSize, u64 HashOut)
This function computes SHA3-384 hash over the given data using xilsecure IPI.
DataAddr Address of the data to hash DataSize Size of the data in bytes HashOut Buffer (minimum 48 bytes, 64-byte aligned) to store hash XST_SUCCESS on successError code on failure
static int XLoader_ValidateBhHBCertAndAuth(XLoader_ClientInstance *InstancePtr, const u64 PdiAddr, u64 *MhOffset)
This function validates the Boot Header Hash Block certificate and authenticates it.
The BH HB cert starts immediately after the Boot Header (at PdiAddr + SMAP_WD_PATTERN_SIZE + BH_SIZE). On success, MhOffset is set to the byte offset of the IHT. InstancePtr Pointer to XLoader_ClientInstance PdiAddr Base address of the PDI in memory MhOffset Output: byte offset from PdiAddr to the IHT XST_SUCCESS on successError code on failure
static int XLoader_VerifyPlmNPmcCdoAuth(u64 PdiAddr, u64 BhAddr)
This function calculates hash and verifies hash of PLM & PMC CDO.
PdiAddr Address where authenticated PDI is present BhAddr Address where boot header is present XST_SUCCESS on success and error code on failure
static int XLoader_ValidateMhAndPrtnAuth(XLoader_ClientInstance *InstancePtr, const u64 PdiAddr, const u64 MhOffset, u32 PrtnStartIdx, const u32 PdiType)
This function validates the MetaHeader (IHT) Hash Block cert and authenticates all partitions starting from PrtnStartIdx.
For each partition, a SHA3 hash of the partition data is computed and compared against the corresponding entry in the IHT Hash Block. InstancePtr Pointer to XLoader_ClientInstance PdiAddr Base address of the PDI in memory MhOffset Byte offset from PdiAddr to the IHT PrtnStartIdx Partition index to start from (1 for full PDI, 0 for partial PDI) PdiType Type of PDI (full or partial) to determine hash block indexing XST_SUCCESS on successError code on failure
static int XLoader_VerifyPrtnAuth(u64 PdiAddr, const XilLoader_PrtnHdr *PrtnHdr, u64 PrtnIdx, const u32 PdiType)
This function calculates hash and verifies hash of each partition.
PdiAddr Address where authenticated PDI is present PrtnHdr Pointer to partition header information PrtnIdx Partition index in the hash block PdiType Type of PDI (full or partial) to determine hash block indexing XST_SUCCESS on success and error code on failure
static int XLoader_VerifyAuthHashBlock(XLoader_ClientInstance *InstancePtr, u64 HBSignParamsAddr, u64 HBInstanceAddr)
This function fills payload and sends IPI request for verifying signature for the provided hash.
InstancePtr Pointer to XLoader_ClientInstance HBSignParamsAddr Address where hash block sign parameters are present HBInstanceAddr Address where hash block instance is present XST_SUCCESS on successXST_FAILURE on failure
int XLoader_ConfigureJtagState(XLoader_ClientInstance *InstancePtr, u32 Flag)
This function sends IPI request to configure jtag status.
InstancePtr Pointer to the client instance. Flag To enable / disable jtag. XST_SUCCESS on success.XST_FAILURE on failure.
References PAYLOAD_ARG_CNT, XLOADER_CMD_ID_CONFIG_JTAG_STATE, XLoader_ProcessMailbox.
int XLoader_ReadDdrCryptoPerfCounters(XLoader_ClientInstance *InstancePtr, u32 NodeId, XLoader_DDRCounters *CryptoCounters)
This function sends IPI request to read DDR crypto performance counters.
InstancePtr Pointer to the client instance. NodeId DDR device id. CryptoCounters To read DDR crypto counters. XST_SUCCESS on success.XST_FAILURE on failure.
References XLoader_DDRCounters::DDRCounter0, XLoader_DDRCounters::DDRCounter1, XLoader_DDRCounters::DDRCounter2, XLoader_DDRCounters::DDRCounter3, XLoader_ClientInstance::MailboxPtr, PAYLOAD_ARG_CNT, XLoader_ClientInstance::Response, XLOADER_CMD_ID_READ_DDR_CRYPTO_COUNTERS, XLoader_ProcessMailbox.
int XLoader_ValidatePdiAuth(XLoader_ClientInstance *InstancePtr, const u64 PdiAddr, const u32 PdiType)
This function sends IPI request to validate authenticated PDI based on PDI type.
InstancePtr Pointer to XLoader_ClientInstance PdiAddr Address where authenticated PDI is present PdiType Value to indicate full or partial PDI XST_SUCCESS on success and error code on failure This function has external linkage and is declared in xloader_plat_client.h for use by application code. InstancePtr - Pointer to XLoader_ClientInstance PdiAddr - Address where authenticated PDI is present PdiType - Value to indicate Full or Partial PDI XST_SUCCESS on success and error code on failure
References XLoader_ClientInstance::MailboxPtr, XLoader_Client_Printf, XLOADER_DEBUG_GENERAL, XLOADER_PDI_TYPE_FULL, XLOADER_SMAP_WD_PATTERN_SIZE.
static int XLoader_VerifyPrtnAuth(XLoader_ClientInstance *InstancePtr, u64 PrtnAddr, u32 PrtnLen, u32 PrtnIdx, u64 ACAddr, XilPdi_HashTblInfo *HashTblInfo)
This function calculates hash and verifies signature for each partition.
InstancePtr - Pointer to XLoader_ClientInstance PrtnAddr - Address where partition is present PrtnLen - Length of partition PrtnIdx - Index of the partition ACAddr - Address where Authentication Certificate of partition is present HashTblInfo - Pointer to Hash Table Information XST_SUCCESS on success and error code on failure
static int XLoader_VerifyDataAuth(XLoader_ClientInstance *InstancePtr, u64 HashAddr, u64 ACAddr, u32 SignatureSelect)
This function fills payload and sends IPI request for verifying signature for the provided hash.
InstancePtr - Pointer to XLoader_ClientInstance HashAddr - Address where hash is present ACAddr - Address where authentication certificate is present SignatureSelect - To select signature in authentication certificate TRUE - Header signatureFALSE - Image signature XST_SUCCESS on success and error code on failure
static int XLoader_ValidateBhAndPlmNPmcCdoAuth(XLoader_ClientInstance *InstancePtr, const u64 PdiAddr, u64 *MhOffset)
This function sends IPI request to validate Boot Header, PLM and PMC CDO authentication.
InstancePtr - Pointer to XLoader_ClientInstance PdiAddr - Address where authenticated PDI is present MhOffset - Pointer to Meta Header Offset XST_SUCCESS on success and error code on failure
static int XLoader_ValidateMhAndPrtnAuth(XLoader_ClientInstance *InstancePtr, const u64 PdiAddr, const u64 MhOffset, const u32 PrtnStartIdx)
This function sends IPI request to validate Meta Header and partition authentication.
InstancePtr - Pointer to XLoader_ClientInstance PdiAddr - Address where authenticated PDI is present MhOffset - Offset where meta header is present PrtnStartIdx - Partition start offset i.e. 0 for PPDI and 1 for Full PDI XST_SUCCESS on success and error code on failure
static int XLoader_VerifyPlmNPmcCdoAuth(XLoader_ClientInstance *InstancePtr, u64 PdiAddr, u64 BhAddr)
This function calculates hash and verifies signature for each partition.
InstancePtr - Pointer to XLoader_ClientInstance PdiAddr - Address where authenticated PDI is present BhAddr - Address where bootheader is present XST_SUCCESS on success and error code on failure
u64 XLoader_SearchOptionalData(u64 StartAddress, u64 EndAddress, u32 DataId)
This function search offset of optional data address.
StartAddress is start address of IHT optional data EndAddress is end address of IHT optional data DataId is to identify type of data in data structure Offset on getting successful optional data offset address for given data Id.
References XIH_OPT_DATA_HDR_ID_MASK, XIH_OPT_DATA_HDR_LEN_MASK, XIH_OPT_DATA_HDR_LEN_SHIFT, XLOADER_WORD_LEN_SHIFT.
static int XLoader_CheckAndCompareHashFromIHTOptionalData(u64 HashAddr, XilPdi_HashTblInfo *HashTblInfo, u32 PrtnHashIndex)
This function checks whether Partition hash is present or not and compares the claculated hash with hash which is present in IHT Optional data for the respective partitions.
HashAddr is Address fo the calculated Hash HashTblInfo is pointer to Hash table info PrtnHashIndex is index of partition hash in IHT optional data XST_SUCCESS on success error code on failure
static int XLoader_IsAuthOptimized(u64 OptionalDataStartAddr, u32 OptionalDataLen, XilPdi_HashTblInfo *HashTbl)
This function checks whether Authentication optimization is enabled or not.
OptionalDataStartAddr is start address of IHT optional data OptionalDataLen is size of IHT optional data HashTbl is pointer to XilPdi_HashTblInfo XST_SUCCESS On Success XST_FAILURE On Failure
XLOADER_ADDR_HIGH_SHIFT
Shift value to get higher 32 bit address.
Referenced by XLoader_AddImageStorePdi, XLoader_CfiSelectiveReadback, XLoader_ExtractMetaheader, XLoader_GetATFHandOffParams, XLoader_GetImageInfoList, XLoader_GetOptionalData, XLoader_LoadPartialPdi.
XLOADER_MSB_MASK
Mask for MSB bit.
Referenced by XLoader_GetImageInfoList.
XLOADER_SELREADBACK_ROW_START_POS
Row field start bit position.
Referenced by XLoader_CfiSelectiveReadback.
XLOADER_SELREADBACK_BLKTYPE_START_POS
Block type field start bit position.
Referenced by XLoader_CfiSelectiveReadback.
XLOADER_SELREADBACK_ROW_MASK
Mask for row.
Referenced by XLoader_CfiSelectiveRead, XLoader_CfiSelectiveReadback.
XLOADER_SLEREADBACK_BLKTYPE_MASK
Mask for block type.
Referenced by XLoader_CfiSelectiveReadback.
XLOADER_SLEREADBACK_FRAMEADDR_MASK
Mask for frame address.
Referenced by XLoader_CfiSelectiveReadback.
XLOADER_SMAP_WD_PATTERN_SIZE
Size of SMAP width pattern.
Referenced by XLoader_ValidatePdiAuth.
XLOADER_BH_SIZE
Size of bootheader.
XLOADER_BH_IMG_ATTRB_SIGNED_IMG_MASK
Mask for signed image in BH.
XLOADER_SHA3_HASH_LEN_IN_BYTES
SHA3-384 hash length.
XLOADER_WORD_LEN
Word length in bytes.
XLOADER_WORD_LEN_SHIFT
Shift to convert word in bytes.
XLOADER_IHT_SIZE
Size of Image Header Table in bytes.
XLOADER_IH_MAX_PRTNS
Maximum number of partitions in the IHT.
XLOADER_IH_SIZE
Size of Image Header in bytes.
XLOADER_PHT_SIZE
Size of Partition Header Table in bytes.
XLOADER_SECURE_CHUNK_SIZE
32K
Referenced by XLoader_SecureCopy.
XLOADER_SECURE_PLM_PMC_CHUNK_SIZE
16K
XLOADER_HB0_INDEX_0_BH
0th for Boot Header Hash
XLOADER_HB0_INDEX_1_PLM
1st for PLM
XLOADER_HB0_INDEX_2_PMC_DATA
2nd for PMC Data
XLOADER_HB0_INDEX_3_HB1
3rd for Hash Block 1
XLOADER_HB1_INDEX_0_MH
0th for Meta Header
XLOADER_SMAP_WD_PATTERN_SIZE
Size of SMAP width pattern.
XLOADER_BH_SIZE_WO_PADDING
Size of bootheader without padding.
XLOADER_BH_SIZE
Size of bootheader.
XLOADER_IHT_SIZE
Size of Image Header Table.
XLOADER_BH_IMG_ATTRB_SIGNED_IMG_MASK
Mask for signed image in bootheader.
XLOADER_RSA_4096_KEY_SIZE
RSA 4096 key size.
XLOADER_SPK_SIZE
Size of Secondary Public Key(in bytes) in Authentication Certificate.
XLOADER_PPK_SIZE
Size of Primary Public Key(in bytes) in Authentication Certificate.
XLOADER_SPK_SIG_SIZE
Size of SPK signature(in bytes) in Authentication Certificate.
XLOADER_BHDR_SIG_SIZE
Size of Bootheader signature(in bytes) in Authentication Certificate.
XLOADER_PARTITION_SIG_SIZE
Size of Partition signature(in bytes) in Authentication Certificate.
XLOADER_AUTH_HEADER_SIZE
Size of Authentication header(in bytes) in Authentication Certificate.
XLOADER_AUTH_CERT_USER_DATA
Size of User Data(in bytes) in Authentication Certificate.
XLOADER_AUTH_CERT_MIN_SIZE
Minimum Size of Authentication Certificate(in bytes)
XIH_MAX_PRTNS
Max number of partitions.
Referenced by XLoader_MeasureNLoad.
XLOADER_SECURE_CHUNK_SIZE
32K
XLOADER_SHA3_HASH_LEN_IN_BYTES
Length of SHA3 Hash in bytes.
XLOADER_WORD_LEN
Length of word in bytes.
XLOADER_WORD_LEN_SHIFT
Shift to convert word in bytes.
Referenced by XLoader_SearchOptionalData.
XLOADER_PARTITION_SIZE
Size of partition in bytes.
XIH_OPT_DATA_HDR_ID_MASK
Optional data id mask.
Referenced by XLoader_SearchOptionalData.
XIH_OPT_DATA_HDR_LEN_MASK
Optional data length mask.
Referenced by XLoader_SearchOptionalData.
XIH_OPT_DATA_HDR_LEN_SHIFT
shift value to extract optional data length
Referenced by XLoader_SearchOptionalData.
XIH_OPT_DATA_LEN_OFFSET
Optional data length offset.
XIH_OPT_DATA_DEF_LEN
Default optional data length.
XIH_OPT_HASH_TBL_DATA_ID
Optional data id for hash table.