net/server/xloader_plat.h
XLOADER_SECURE_CHUNK_SIZE
Secure chunk size 32K.
XLOADER_PDI_SRC_JTAG
PDI source JTAG.
XLOADER_PDI_SRC_QSPI24
PDI source QSPI24.
XLOADER_PDI_SRC_QSPI32
PDI source QSPI32.
XLOADER_PDI_SRC_SDLS_B0
PDI source SDLS_B0.
XLOADER_PDI_SRC_EMMC0
PDI source EMMC0.
XLOADER_PDI_SRC_SD_B1
PDI source SD_B1.
XLOADER_PDI_SRC_EMMC1
PDI source EMMC1.
XLOADER_PDI_SRC_USB
PDI source USB.
XLOADER_PDI_SRC_OSPI
PDI source OSPI.
XLOADER_PDI_SRC_SBI
PDI source SBI.
XLOADER_PDI_SRC_SMAP
PDI source SMAP.
XLOADER_PDI_SRC_PCIE
PDI source PCIE.
XLOADER_PDI_SRC_SDLS_B1
PDI source SDLS_B1.
XLOADER_PDI_SRC_DDR
PDI source DDR.
XLOADER_PDI_SRC_IS
PDI source Image Store.
XLOADER_PDI_SRC_INVALID
PDI source invalid.
XLOADER_APU_CLUSTER0
APU cluster 0.
XLOADER_APU_CLUSTER1
APU cluster 1.
XLOADER_APU_CLUSTER2
APU cluster 2.
XLOADER_APU_CLUSTER3
APU cluster 3.
XLOADER_APU_CORE0
APU core 0.
XLOADER_APU_CORE1
APU core 1.
XLOADER_APU_CORE2
APU core 2.
XLOADER_APU_CORE3
APU core 3.
XLOADER_RPU_CLUSTERA
RPU cluster A.
XLOADER_RPU_CLUSTERB
RPU cluster B.
XLOADER_RPU_CORE0
RPU core 0.
XLOADER_RPU_CORE1
RPU core 1.
XLOADER_IMAGE_INFO_DS_ID
Image information data structure Id.
XLOADER_BOOTPDI_INFO_DS_ID
Boot PDI Info data structure Id.
XLOADER_PDI_LIST_DS_ID
PDI list data structure Id.
XLOADER_ATF_HANDOFF_PARAMS_DS_ID
ATF handoff parameters data structure Id.
XLOADER_IMAGE_INFO_PTR_DS_ID
Image information data structure Id.
XLOADER_SHA3_1_DEVICE_ID
SHA3_1 device Id.
XLOADER_MEASURE_START
Data measure start.
XLOADER_MEASURE_UPDATE
Data measure update.
XLOADER_MEASURE_FINISH
Data measure finish.
XLOADER_GET_PDISRC_INFO
Get PDI source info.
@6
0x1 - XLOADER_ERR_FAILURE
static int XLoader_MeasureRomAndPlm(void)
This function extends the image hashes of ROM and PLM data.
XST_SUCCESS on successful extensionerror code on failure
static u8 XLoader_IsDFxApplicable(u32 NodeId)
This function is used to check if the given NodeId is applicable for DFx.
NodeId is Image ID TRUE if applicable, else FALSE
static u8 XLoader_IsPdiSrcSD(u32 PdiSrc)
This function is used to check if the given PdiSrc is SD.
PdiSrc is the source of Pdi TRUE if SD, else FALSE
static u8 XLoader_IsPdiSrcSD0(u8 PdiSrc)
This function is used to check if the given PdiSrc is SD0.
PdiSrc is the source of Pdi TRUE if SD0, else FALSE
static u8 XLoader_SkipMJtagWorkAround(XilPdi *PdiPtr)
This function checks if MJTAG workaround partition needs to be skipped.
PdiPtr is pointer to PDI instance FALSE
static void XLoader_PerformInternalPOR(void)
This function check conditions and perform internal POR for VP1802 and VP1502 device if required.
None.
static void XLoader_SetJtagTapToReset(void)
This function is used to run MJTAG solution workaround in which JTAG Tap state will be set to reset.
None
static int Xloader_SsitEoPdiSync(XilPdi *PdiPtr)
This function will sync the PDI load status with master.
PdiPtr is pointer to PDI instance -XST_SUCCESS return success
XLoader_ImageInfoTbl* XLoader_GetImageInfoTbl(void)
This function provides ImageInfoTbl pointer.
Pointer to ImageInfoTbl Pointer to ImageInfoTbl.
References XLoader_ImageInfoTbl::Count.
Referenced by XLoader_GetImageInfoEntry, XLoader_StoreImageInfo, XLoader_LoadImageInfoTbl.
int XLoader_StartImage(XilPdi *PdiPtr)
This function is used to start the subsystems in the PDI.
PdiPtr Pdi instance pointer XST_SUCCESS on success.XLOADER_ERR_WAKEUP_A72_0 if waking up the A72-0 failed during handoff.XLOADER_ERR_WAKEUP_A72_1 if waking up the A72-1 failed during handoff.XLOADER_ERR_WAKEUP_R5_0 if waking up the R5-0 failed during handoff.XLOADER_ERR_WAKEUP_R5_1 if waking up the R5-1 failed during handoff.XLOADER_ERR_WAKEUP_R5_L if waking up the R5-L failed during handoff.XLOADER_ERR_WAKEUP_PSM if waking up the PSM failed during handoff.XLOADER_ERR_CONFIG_SUBSYSTEM if subsystem peripheral pre-allocation fails during handoff. PdiPtr Pdi instance pointer XST_SUCCESS on success.XLOADER_ERR_WAKEUP_R52_0 if waking up the R52_0 failed during handoff.XLOADER_ERR_WAKEUP_R52_1 if waking up the R52_1 failed during handoff.XLOADER_ERR_WAKEUP_A78_0 if waking up the A78_0 failed during handoff.XLOADER_ERR_WAKEUP_A78_1 if waking up the A78_1 failed during handoff.XLOADER_ERR_WAKEUP_A78_2 if waking up the A78_2 failed during handoff.XLOADER_ERR_WAKEUP_A78_3 if waking up the A78_3 failed during handoff.XLOADER_ERR_WAKEUP_ASU if waking up the ASU failed during handoff. PdiPtr Pdi instance pointer. XST_SUCCESS on success.XLOADER_ERR_WAKEUP_A72_0 if waking up the A72-0 failed during handoff.XLOADER_ERR_WAKEUP_A72_1 if waking up the A72-1 failed during handoff.XLOADER_ERR_WAKEUP_R5_0 if waking up the R5-0 failed during handoff.XLOADER_ERR_WAKEUP_R5_1 if waking up the R5-1 failed during handoff.XLOADER_ERR_WAKEUP_R5_L if waking up the R5-L failed during handoff.XLOADER_ERR_WAKEUP_PSM if waking up the PSM failed during handoff.XLOADER_ERR_CONFIG_SUBSYSTEM if subsystem peripheral pre-allocation fails during handoff. PdiPtr Pdi instance pointer XST_SUCCESS on success.XLOADER_ERR_WAKEUP_R52_0 if waking up the R52_0 failed during handoff.XLOADER_ERR_WAKEUP_R52_0 if waking up the R52_1 failed during handoff.XLOADER_ERR_WAKEUP_A78_0 if waking up the A78_0 failed during handoff.XLOADER_ERR_WAKEUP_A78_1 if waking up the A78_1 failed during handoff.XLOADER_ERR_WAKEUP_A78_2 if waking up the A78_2 failed during handoff.XLOADER_ERR_WAKEUP_A78_3 if waking up the A78_3 failed during handoff.XLOADER_ERR_WAKEUP_PSM if waking up the PSM failed during handoff.XLOADER_ERR_CONFIG_SUBSYSTEM if subsystem peripheral pre-allocation fails during handoff.
References XilPdi::MetaHdr, XilPdi::ImageNum, XilPdi::NoOfHandoffCpus, XilPdi::HandoffParam, XLoader_HandoffParam::CpuSettings, XLoader_HandoffParam::HandoffAddr, XLoader_Printf.
Referenced by XLoader_RestartImage.
int XLoader_GetSDPdiSrcNAddr(u32 SecBootMode, XilPdi *PdiPtr, u32 *PdiSrc, u64 *PdiAddr)
This function is used to get PdiSrc and PdiAddr for Secondary SD boot modes.
SecBootMode is the secondary boot mode value PdiPtr Pointer to PDI instance PdiSrc Pointer to the source of PDI PdiAddr is the pointer to the address of the Pdi XST_SUCCESS on success.XLOADER_ERR_UNSUPPORTED_SEC_BOOT_MODE on unsupported secondary bootmode. SecBootMode is the secondary boot mode value PdiPtr Pointer to the PDI instance PdiSrc is pointer to the source of PDI PdiAddr is the pointer to the address of the Pdi XST_SUCCESS on success.XLOADER_ERR_UNSUPPORTED_SEC_BOOT_MODE on unsupported secondary bootmode. SecBootMode is the secondary boot mode value. PdiPtr Pointer to PDI instance. PdiSrc Pointer to the source of PDI. PdiAddr is the pointer to the address of the Pdi. XST_SUCCESS on success.XLOADER_ERR_UNSUPPORTED_SEC_BOOT_MODE on unsupported secondary bootmode.
References XLOADER_PDI_SRC_SD0, XLOADER_SD_RAWBOOT_MASK, XilPdi::MetaHdr, XLOADER_PDI_SRC_SD1, XLOADER_PDI_SRC_SD1_LS.
int XLoader_UpdateHandoffParam(XilPdi *PdiPtr)
This function is used to update the handoff parameters.
PdiPtr is pointer to XilPdi instance XST_SUCCESS on success.XLOADER_ERR_NUM_HANDOFF_CPUS when number of CPUs exceed max count. PdiPtr is pointer to XilPdi instance XST_SUCCESS on success.XLOADER_ERR_NUM_HANDOFF_CPUS if number of CPUs exceeds max count. PdiPtr is pointer to XilPdi instance. XST_SUCCESS on success.XLOADER_ERR_NUM_HANDOFF_CPUS when number of CPUs exceed max count.
References XLOADER_MAX_HANDOFF_CPUS, XilPdi::PrtnNum, XilPdi::MetaHdr, XilPdi::NoOfHandoffCpus, XilPdi::HandoffParam, XLoader_HandoffParam::CpuSettings, XLoader_HandoffParam::HandoffAddr.
Referenced by XLoader_ProcessElf.
int XLoader_DumpDdrmcRegisters(void)
int XLoader_ProcessDeferredError(void)
This function checks if MJTAG workaround is required.
XLOADER_ERR_DEFERRED_CDO_PROCESS on error while processing CDO but error is deferred till whole CDO processing is completed.
References XLoader_DumpDdrmcRegisters.
int XLoader_ProcessElf(XilPdi *PdiPtr, const XilPdi_PrtnHdr *PrtnHdr, XLoader_PrtnParams *PrtnParams, XLoader_SecureParams *SecureParams)
This function copies the elf partitions to specified destinations.
PdiPtr is pointer to XilPdi instance PrtnHdr is pointer to the partition header PrtnParams is pointer to the structure variable that contains parameters required to process the partition SecureParams is pointer to the instance containing security related params XST_SUCCESS on success.XLOADER_ERR_INVALID_ELF_LOAD_ADDR if the load address of the elf is invalid.XLOADER_ERR_PM_DEV_PSM_PROC if device request for PSM is failed.XLOADER_ERR_PM_DEV_IOCTL_RPU0_SPLIT if IOCTL call to set RPU0 in split mode fails.XLOADER_ERR_PM_DEV_IOCTL_RPU1_SPLIT if IOCTL call to set RPU1 in split mode fails.XLOADER_ERR_PM_DEV_IOCTL_RPU0_LOCKSTEP if IOCTL call to set RPU0 in lockstep mode fails.XLOADER_ERR_PM_DEV_IOCTL_RPU1_LOCKSTEP if IOCTL call to set RPU1 in lockstep mode fails.XLOADER_ERR_INVALID_TCM_ADDR on Invalid TCM address for A72 elfs.XLOADER_ERR_INVALID_CPUID if invalid CPU id is selected. PdiPtr is pointer to XilPdi instance PrtnHdr is pointer to the partition header PrtnParams is pointer to the structure variable that contains parameters required to process the partition SecureParams is pointer to the instance containing security related params XST_SUCCESS on success.XLOADER_ERR_INVALID_ELF_LOAD_ADDR if load address of the elf is invalid.XLOADER_ERR_INVALID_R52_CLUSTER if invalid R52 cluster is selected.XLOADER_ERR_INVALID_CPUID if invalid CPU id is selected. PdiPtr is pointer to XilPdi instance. PrtnHdr is pointer to the partition header. PrtnParams is pointer to the structure variable that contains parameters required to process the partition. SecureParams is pointer to the instance containing security related params. XST_SUCCESS on success.XLOADER_ERR_INVALID_ELF_LOAD_ADDR if the load address of the elf is invalid.XLOADER_ERR_PM_DEV_PSM_PROC if device request for PSM is failed.XLOADER_ERR_PM_DEV_IOCTL_RPU0_SPLIT if IOCTL call to set RPU0 in split mode fails.XLOADER_ERR_PM_DEV_IOCTL_RPU1_SPLIT if IOCTL call to set RPU1 in split mode fails.XLOADER_ERR_PM_DEV_IOCTL_RPU0_LOCKSTEP if IOCTL call to set RPU0 in lockstep mode fails.XLOADER_ERR_PM_DEV_IOCTL_RPU1_LOCKSTEP if IOCTL call to set RPU1 in lockstep mode fails.XLOADER_ERR_INVALID_TCM_ADDR on Invalid TCM address for A72 elfs. XLOADER_ERR_INVALID_CPUID if invalid CPU id is selected. PdiPtr is pointer to XilPdi instance. PrtnHdr is pointer to the partition header. PrtnParams is pointer to the structure variable that contains parameters required to process the partition. SecureParams is pointer to the instance containing security related params. XST_SUCCESS on success.XLOADER_ERR_INVALID_ELF_LOAD_ADDR if the load address of the elf is invalid.XLOADER_ERR_PM_DEV_PSM_PROC if device request for PSM is failed.XLOADER_ERR_PM_DEV_IOCTL_RPU0_SPLIT if IOCTL call to set RPU0 in split mode fails.XLOADER_ERR_PM_DEV_IOCTL_RPU1_SPLIT if IOCTL call to set RPU1 in split mode fails.XLOADER_ERR_PM_DEV_IOCTL_RPU0_LOCKSTEP if IOCTL call to set RPU0 in lockstep mode fails.XLOADER_ERR_PM_DEV_IOCTL_RPU1_LOCKSTEP if IOCTL call to set RPU1 in lockstep mode fails.XLOADER_ERR_INVALID_TCM_ADDR on Invalid TCM address for A72 elfs. PdiPtr is pointer to XilPdi instance PrtnHdr is pointer to the partition header PrtnParams is pointer to the structure variable that contains parameters required to process the partition SecureParams is pointer to the instance containing security related params XST_SUCCESS on success.XLOADER_ERR_INVALID_ELF_LOAD_ADDR if load address of the elf is invalid.XLOADER_ERR_PM_DEV_PSM_PROC if device request for PSM is failed.XLOADER_ERR_INVALID_R52_CLUSTER if invalid R52 cluster is selected.XLOADER_ERR_INVALID_CPUID if invalid CPU id is selected.
References XLoader_PrtnParams::DeviceCopy, XLoader_DeviceCopy::DestAddr, XLoader_PrtnParams::DstnCpu, XLOADER_TCM_0, XLOADER_TCM_1, XLOADER_R5_1_TCM_A_BASE_ADDR, XLOADER_R5_1_TCM_A_END_ADDR, XLOADER_R5_1_TCM_B_BASE_ADDR, XLOADER_R5_1_TCM_B_END_ADDR, XLOADER_RPU_GLBL_CNTL, XLOADER_TCMCOMB_MASK, XLOADER_TCMCOMB_SHIFT, XLOADER_R5_0_TCM_A_BASE_ADDR, XLOADER_R5_0_TCM_A_END_ADDR, XLOADER_R5_0_TCM_B_BASE_ADDR, XLOADER_R5_0_TCM_B_END_ADDR, XLOADER_R5_LS_TCM_END_ADDR, XLoader_PrtnCopy, XLoader_ClearATFHandoffParams, XLoader_SetATFHandoffParameters, XilPdi::DelayHandoff, XLoader_UpdateHandoffParam.
XLoader_ImageStore* XLoader_GetPdiList(void)
This function provides pointer to PdiList.
Pointer to PdiListpointer to PdiList Pointer to PdiList.
Referenced by XLoader_RestartImage, XLoader_ReadImageStoreCfg, XLoader_IsPdiAddrLookup.
int XLoader_UpdateHandler(XPlmi_ModuleOp Op)
This function provides update handler for xilloader.
Op is the module operation variable XST_SUCCESS on success and error code on failure
References XLOADER_AUTH_JTAG_INT_STATUS_POLL_INTERVAL, XLoader_CheckDeviceStateChange, XLOADER_DEVICE_STATE_POLL_INTERVAL.
int XLoader_PlatInit(void)
This function initializes the loader with platform specific initializations.
XST_SUCCESS on success and error code on failure XST_SUCCESS always. XST_SUCCESS on success.Error code on failure.
int XLoader_HdrMeasurement(XilPdi *PdiPtr)
This function measures the PDI's meta header data by calculating the hash using SHA3.
PdiPtr is the pointer to PDI instance XST_SUCCESS on success.XLOADER_ERR_HDR_MEASUREMENT if error in meta header measurement.
References XilPdi::MetaHdr, XLoader_ImageMeasureInfo::SubsystemID, XLoader_ImageMeasureInfo::PcrInfo, XLoader_ImageMeasureInfo::Flags, XLOADER_MEASURE_START, XLoader_DataMeasurement, XLoader_ImageMeasureInfo::DataAddr, XLoader_ImageMeasureInfo::DataSize, XLOADER_MEASURE_UPDATE, XLOADER_MEASURE_FINISH.
int XLoader_DataMeasurement(XLoader_ImageMeasureInfo *ImageInfo)
This function measures the data by calculating SHA3 hash.
ImageInfo Pointer to the XLoader_ImageMeasureInfo structure XST_SUCCESS on successfully measuring the dataXLOADER_ERR_DATA_MEASUREMENT if error in data measurement. ImageInfo Pointer to the XLoader_ImageMeasureInfo structure. XST_SUCCESS on success.XLOADER_ERR_DATA_MEASUREMENT if error in data measurement. ImageInfo Pointer to the XLoader_ImageMeasureInfo structure. XST_SUCCESS on successfully measuring the data.XLOADER_ERR_DATA_MEASUREMENT if error in data measurement.
References XLoader_ImageMeasureInfo::PcrInfo, XLOADER_PCR_INVALID_VALUE, XLoader_ImageMeasureInfo::Flags, XLOADER_MEASURE_START, XLOADER_MEASURE_UPDATE, XLoader_ImageMeasureInfo::DataAddr, XLoader_ImageMeasureInfo::DataSize, XLOADER_MEASURE_FINISH, XLOADER_PCR_NUMBER_MASK.
Referenced by XLoader_UpdateDataMeasurement, XLoader_MeasureNLoad, XLoader_HdrMeasurement.
int XLoader_SecureConfigMeasurement(XLoader_SecureParams *SecurePtr, u32 PcrInfo, u32 *DigestIndex, u32 OverWrite)
This function measures the Secure Configuration that is SPK, SPK ID and Encryption Revoke ID and extends to the specified PCR.
SecurePtr Pointer to the XLoader_SecureParams instance. PcrInfo Provides the PCR number and Measurement Index to be extended. DigestIndex Pointer to the DigestIndex across the PCR OverWrite TRUE or FALSE to overwrite the extended digest or not XST_SUCCESS on success.XLOADER_ERR_SECURE_CONFIG_MEASUREMENT if error in Secure config measurement. SecurePtr is pointer to the XLoader_SecureParams instance. PcrInfo provides the PCR number and Measurement Index to be extended. DigestIndex is pointer to the DigestIndex across the PCR. OverWrite TRUE or FALSE to overwrite the extended digest or not. XST_SUCCESS on success.XLOADER_ERR_SECURE_CONFIG_MEASUREMENT if error in Secure config measurement. SecurePtr is pointer to the XLoader_SecureParams instance. PcrInfo provides the PCR number and Measurement Index to be extended. DigestIndex is pointer to the DigestIndex across the PCR OverWrite TRUE or FALSE to overwrite the extended digest or not XST_SUCCESS on success.XLOADER_ERR_SECURE_CONFIG_MEASUREMENT if error in Secure config measurement.
References XLoader_SecureParams::IsAuthenticated, XLoader_SecureParams::IsEncrypted, XLOADER_EFUSE_ROM_RSVD_CACHE_ADDRESS, XLOADER_EFUSE_ROM_RSVD_AUTH_KEYS_TO_HASH_MASK, XLOADER_EFUSE_ROM_RSVD_AUTH_KEYS_TO_HASH_SHIFT.
XilBootPdiInfo* XLoader_GetBootPdiInfo(void)
This function provides pointer to BootPDI Info.
pointer to BootPDI Info pointer to BootPDI Info.
Referenced by XLoader_RestartImage, Xloader_SaveBootPdiInfo.
int XLoader_ConfigureJtagState(XPlmi_Cmd *Cmd)
This function enables or disable Jtag Access Command payload parameters are.
- Flag (enable / disable) Cmd is pointer to the command structure XST_SUCCESS on success.XLOADER_ERR_INVALID_JTAG_OPERATION
References XLOADER_CMD_CONFIG_JTAG_STATE_FLAG_INDEX, XLOADER_CMD_CONFIG_JTAG_STATE_FLAG_MASK, XLOADER_CONFIG_JTAG_STATE_FLAG_ENABLE, XLOADER_CONFIG_JTAG_STATE_FLAG_DISABLE, XLOADER_ERR_INVALID_JTAG_OPERATION, XLOADER_PMC_TAP_LOCK_ADDR, XLOADER_PMC_TAP_UNLOCK_VAL, XLoader_EnableJtag, XLOADER_CONFIG_DAP_STATE_NONSECURE_DBG, XLoader_DisableJtag, XLOADER_PMC_TAP_LOCK_VAL.
int XLoader_ReadDdrCryptoPerfCounters(XPlmi_Cmd *Cmd)
This function reads DDR crypto performance counters of given DDR device id.
Cmd is pointer to the command structure XST_SUCCESS on success. ErrorCode on Failure.
References XLOADER_CMD_GET_DDR_DEVICE_ID, XLOADER_ERR_DDR_DEVICE_ID, XLOADER_ERR_PCOMPLETE_NOT_DONE, XLOADER_DDR_CRYPTO_MAIN_OFFSET, XLOADER_DDR_PERF_MON_CNT0_OFFSET, XLOADER_DDR_PERF_MON_CNT1_OFFSET, XLOADER_DDR_PERF_MON_CNT2_OFFSET, XLOADER_DDR_PERF_MON_CNT3_OFFSET.
int XLoader_LoadLpdAndPsmElf(void)
This function will load the LPD and PSM ELF file from DDR.
XST_SUCCESS on success.Error code on failure
References XLoader_GetPdiInstance, XLOADER_ERR_MEMSET_PDIPTR, XilPdi::PdiType, XLoader_PdiInit, XLOADER_PDI_SRC_DDR, XLoader_GetImageAndPrtnInfo, XLoader_LoadImage, XilPdi::NoOfHandoffCpus.
int XLoader_CheckAndUpdateSecureState(void)
This function checks and updates the secure state configuration.
XST_SUCCESS on success.Error code on failure
References XLOADER_SEC_STATE_CONFIG_MEASUREMENT_ERROR.
Referenced by XLoader_CheckDeviceStateChange.
int XLoader_MeasureNLoad(XilPdi *PdiPtr)
This function measures the partition hashes.
This function measures the partition hashes from the hash block. PdiPtr is pointer to XilPdi instance XST_SUCCESS on success.XLOADER_ERR_DATA_MEASUREMENT if error in data measurement. PdiPtr is pointer to XilPdi instance. XST_SUCCESS on success.XLOADER_ERR_DATA_MEASUREMENT if error in data measurement.
References XilPdi::MetaHdr, XilPdi::ImageNum, XilPdi::PrtnNum, XilPdi::DigestIndex, XLOADER_PCR_MEASUREMENT_INDEX_MASK, XLOADER_PCR_MEASUREMENT_INDEX_SHIFT, XLOADER_IMAGE_FULL_AUTHENTICATED, XLOADER_IMAGE_PARTIALLY_AUTHENTICATED, XLoader_LoadImagePrtns, XLoader_ImageMeasureInfo::PcrInfo, XLoader_ImageMeasureInfo::Flags, XLOADER_MEASURE_START, XLoader_ImageMeasureInfo::SubsystemID, XLoader_DataMeasurement, XLoader_ImageMeasureInfo::DataSize, XLOADER_MEASURE_UPDATE, XLoader_ImageMeasureInfo::DataAddr, XLOADER_MEASURE_FINISH, XIH_MAX_PRTNS, XLOADER_PCR_INVALID_VALUE.
Referenced by XLoader_LoadImage.
void XLoader_ShaInstance1Reset(void)
This Function does the following:
It resets the SHA instance 1.It puts the SHA instance 1 into initialized state.
Referenced by XLoader_LoadImage.
int XLoader_UpdateDataMeasurement(const XilPdi *PdiPtr, u64 DataAddr, u32 DataLen)
This function updates the partition data to SHA engine for data measurement only if authentication or checksum is not enabled.
This functions updates the partition data to SHA engine for measurement.If authentication or checksum is enabled, nothing needs to be done as SHA engine would be in use for the authentication/checksum process. PdiPtr Pointer to the XilPdi structure. DataAddr Address of Data for measure the hash. DataLen Length of data for DataMeasument. XST_SUCCESS on success and error code on failure PdiPtr Pointer to the XilPdi structure. DataAddr Address of Data for measure the hash. DataLen Length of data for DataMeasument. XST_SUCCESS on success.Error code on failure. PdiPtr Pointer to the XilPdi structure. DataAddr Address of Data for measure the hash. DataLen Length of data for DataMeasument. XST_SUCCESS on success and error code on failure
References XilPdi::MetaHdr, XilPdi::ImageNum, XilPdi::PrtnNum, XLOADER_IMAGE_FULL_AUTHENTICATED, XLoader_ImageMeasureInfo::DataAddr, XLoader_ImageMeasureInfo::DataSize, XLoader_ImageMeasureInfo::PcrInfo, XLoader_ImageMeasureInfo::SubsystemID, XLoader_ImageMeasureInfo::Flags, XLOADER_MEASURE_UPDATE, XLoader_DataMeasurement, XilPdi::ImagePrtnId.
Referenced by XLoader_PrtnCopy.