xloader_client.c
XLOADER_ADDR_HIGH_SHIFT
Shift value to get higher 32 bit address.
Referenced by XLoader_AddImageStorePdi, XLoader_CfiSelectiveReadback, XLoader_ExtractMetaheader, XLoader_GetATFHandOffParams, XLoader_GetImageInfoList, XLoader_GetOptionalData, XLoader_LoadPartialPdi.
XLOADER_MSB_MASK
Mask for MSB bit.
Referenced by XLoader_GetImageInfoList.
XLOADER_SELREADBACK_ROW_START_POS
Row field start bit position.
Referenced by XLoader_CfiSelectiveReadback.
XLOADER_SELREADBACK_BLKTYPE_START_POS
Block type field start bit position.
Referenced by XLoader_CfiSelectiveReadback.
XLOADER_SELREADBACK_ROW_MASK
Mask for row.
Referenced by XLoader_CfiSelectiveRead, XLoader_CfiSelectiveReadback.
XLOADER_SLEREADBACK_BLKTYPE_MASK
Mask for block type.
Referenced by XLoader_CfiSelectiveReadback.
XLOADER_SLEREADBACK_FRAMEADDR_MASK
Mask for frame address.
Referenced by XLoader_CfiSelectiveReadback.
int XLoader_LoadPartialPdi(XLoader_ClientInstance *InstancePtr, XLoader_PdiSrc PdiSrc, u64 PdiAddr, u32 *PlmErrStatus)
This function sends IPI request to provides PDI execution.
InstancePtr Pointer to the client instance. PdiSrc Boot Mode values, DDR, PCIe. PdiAddr 64bit PDI address located in the Source. PlmErrStatus Used to store the plm error status. XST_SUCCESS on success.XST_FAILURE on failure.
References PAYLOAD_ARG_CNT, RESPONSE_ARG_CNT, XLOADER_ADDR_HIGH_SHIFT, XLOADER_CMD_ID_LOAD_SUBSYSTEM_PDI, XLoader_SendRequest.
int XLoader_LoadImage(XLoader_ClientInstance *InstancePtr, u32 NodeId, u32 FunctionId)
This function sends IPI request to Load image.
InstancePtr Pointer to the client instance. NodeId Node id of ddr copied image. FunctionId To verify with the FuncID of the image copied to DDR. XST_SUCCESS on success.XST_FAILURE on failure.
References PAYLOAD_ARG_CNT, XLOADER_CMD_ID_LOAD_DDRCPY_IMG, XLoader_SendRequest.
Referenced by XLoader_LoadAsuImage, XLoader_LoadLpdAndPsmElf.
int XLoader_GetImageInfo(XLoader_ClientInstance *InstancePtr, u32 NodeId, XLoader_ImageInfo *ImageInfo)
This function sends IPI request to get image information.
InstancePtr Pointer to the client instance. NodeId Node id of ddr copied image. ImageInfo Pointer to the structure XLoader_ImageInfo which is used to store the image information. XST_SUCCESS on success.XST_FAILURE on failure.
References XLoader_ImageInfo::FuncID, XLoader_ImageInfo::ImgID, PAYLOAD_ARG_CNT, XLoader_ImageInfo::PUID, RESPONSE_ARG_CNT, XLoader_ImageInfo::UID, XLOADER_CMD_ID_GET_IMAGE_INFO, XLoader_SendRequest.
int XLoader_GetImageInfoList(XLoader_ClientInstance *InstancePtr, u64 Buff_Addr, u32 Maxsize, u32 *NumEntries)
This function sends IPI request to gets ImageInfo Table.
InstancePtr Pointer to the client instance. Buff_Addr Buffer address to copy the ImageInfo. Maxsize Maximum size requires in bytes. NumEntries To get the number of entries returned. XST_SUCCESS on success.XST_FAILURE on failure.
References PAYLOAD_ARG_CNT, RESPONSE_ARG_CNT, XLOADER_ADDR_HIGH_SHIFT, XLOADER_CMD_ID_GET_IMAGE_INFO_LIST, XLOADER_MSB_MASK, XLoader_SendRequest.
int XLoader_ExtractMetaheader(XLoader_ClientInstance *InstancePtr, u64 PdiSrcAddr, u64 DestBuffAddr, u32 DestBuffSize)
This function sends IPI request to Extract meta header.
InstancePtr Pointer to the client instance. PdiSrcAddr Address of the pdi. DestBuffAddr Address to export the pdi. DestBuffSize size of the destination buffer in bytes. XST_SUCCESS on success.XST_FAILURE on failure.
References PAYLOAD_ARG_CNT, XLOADER_ADDR_HIGH_SHIFT, XLOADER_CMD_ID_EXTRACT_METAHEADER, XLoader_SendRequest.
int XLoader_UpdateMultiboot(XLoader_ClientInstance *InstancePtr, XLoader_PdiSrc BootMode, XLoader_FlashType Type, u32 ImageLocation)
This function sends IPI request to update multiboot.
InstancePtr Pointer to the client instance. BootMode Pdi boot source Type Flash type ImageLocation Location of Image in the boot device. XST_SUCCESS on success.XST_FAILURE on failure.
References PAYLOAD_ARG_CNT, XLOADER_CMD_ID_UPDATE_MULTIBOOT, XLoader_SendRequest.
Referenced by main.
int XLoader_AddImageStorePdi(XLoader_ClientInstance *InstancePtr, u32 PdiId, const u64 PdiAddr, u32 PdiSize)
This function sends IPI request to add Image store pdi.
InstancePtr Pointer to the client instance. PdiId Id of the pdi. PdiAddr Address to store Image store pdi's maintained by PLM. PdiSize Size of pdi in words. XST_SUCCESS on success.XST_FAILURE on failure.
References PAYLOAD_ARG_CNT, XLOADER_ADDR_HIGH_SHIFT, XLOADER_CMD_ID_ADD_IMAGESTORE_PDI, XLoader_SendRequest.
Referenced by main.
int XLoader_RemoveImageStorePdi(XLoader_ClientInstance *InstancePtr, u32 PdiId)
This function sends IPI request to remove Image store pdi.
InstancePtr Pointer to the client instance. PdiId Id of the PDI to be removed from Image Store. XST_SUCCESS on success.XST_FAILURE on failure.
References PAYLOAD_ARG_CNT, XLOADER_CMD_ID_REMOVE_IMAGESTORE_PDI, XLoader_SendRequest.
int XLoader_GetATFHandOffParams(XLoader_ClientInstance *InstancePtr, u64 BuffAddr, u32 Size, u32 *BufferSize)
This function sends IPI request to get ATF Handoff parameters.
InstancePtr Pointer to the client instance (Input). BuffAddr Address to store the handoff parameter information (Input). Size Maximum number of bytes that can be stored in the buffer (Input). BufferSize To get the size of the buffer in bytes (Output). XST_SUCCESS on success.XST_FAILURE on failure.
References PAYLOAD_ARG_CNT, RESPONSE_ARG_CNT, XLOADER_ADDR_HIGH_SHIFT, XLOADER_CMD_ID_GET_ATF_HANDOFF_PARAMS, XLoader_SendRequest.
int XLoader_CfiSelectiveReadback(XLoader_ClientInstance *InstancePtr, XLoader_CfiSelReadbackParams *SelectiveReadbackPtr)
This function sends IPI request to read selective frames from configuration memory.
InstancePtr Pointer to the client instance SelectiveReadbackPtr Pointer to structure which contains parameters of CFI selective readback command XST_SUCCESS on success.XST_FAILURE on failure.
References XLoader_CfiSelReadbackParams::Blocktype, XLoader_CfiSelReadbackParams::DestAddr, XLoader_CfiSelReadbackParams::FrameAddr, XLoader_CfiSelReadbackParams::FrameCnt, PAYLOAD_ARG_CNT, XLoader_CfiSelReadbackParams::Row, XLoader_ClientInstance::SlrIndex, XLOADER_ADDR_HIGH_SHIFT, XLOADER_CFI_SEL_READBACK_ID, XLOADER_SELREADBACK_BLKTYPE_START_POS, XLOADER_SELREADBACK_ROW_MASK, XLOADER_SELREADBACK_ROW_START_POS, XLoader_SendRequest, XLOADER_SLEREADBACK_BLKTYPE_MASK, XLOADER_SLEREADBACK_FRAMEADDR_MASK, XLOADER_SLR_INDEX_SHIFT.
int XLoader_InputSlrIndex(XLoader_ClientInstance *InstancePtr, u32 SlrIndex)
Adds the SLR Index.
InstancePtr is a pointer to instance XLoader_ClientInstance SlrIndex - SLR index number - XST_SUCCESS - On valid input SlrIndex. XST_FAILURE - On non valid input SlrIndex
References XLoader_ClientInstance::SlrIndex, XLOADER_SLR_INDEX_3.
int XLoader_GetOptionalData(XLoader_ClientInstance *InstancePtr, const XLoader_OptionalDataInfo *OptionalDataInfo, u64 DestAddr, u32 *DestSize)
This function sends IPI request to get optional data from the PDI available in DDR or Image Store.
InstancePtr Pointer to the client instance. OptionalDataInfo Pointer to XLoader_OptionalDataInfo structure DestAddr Address of the output buffer wheren optional data shall be copied DestSize Size of destination buffer in bytes XST_SUCCESS on success.XST_FAILURE on failure.
References XLoader_OptionalDataInfo::DataId, PAYLOAD_ARG_CNT, XLoader_OptionalDataInfo::PdiAddrHigh, XLoader_OptionalDataInfo::PdiAddrLow, XLoader_OptionalDataInfo::PdiId, XLoader_OptionalDataInfo::PdiSrc, RESPONSE_ARG_CNT, XLOADER_ADDR_HIGH_SHIFT, XLOADER_CMD_ID_EXTRACT_METAHEADER, XLOADER_DATA_ID_SHIFT, XLOADER_GET_OPT_DATA_FLAG, XLOADER_PDI_SRC_DDR, XLOADER_PDI_SRC_IS, XLOADER_PDI_SRC_OSPI, XLoader_SendRequest.