xloader_mailbox.c
int XLoader_ProcessMailbox(XLoader_ClientInstance *ClientPtr, u32 *MsgPtr, u32 MsgLen)
This function sends IPI request to the target module and gets the response from it.
ClientPtr Pointer to the client instance. MsgPtr Pointer to the payload message. MsgLen Length of the message. XST_SUCCESS - If the IPI send and receive is successful.XST_FAILURE - If there is a failure. Payload consists of API id and call arguments to be written in IPI buffer.
References XLoader_ClientInstance::MailboxPtr, XLoader_ClientInstance::Response, RESPONSE_ARG_CNT, XLOADER_TARGET_IPI_INT_MASK.
Referenced by XLoader_ConfigureJtagState, XLoader_ReadDdrCryptoPerfCounters, XLoader_SendRequest.
int XLoader_ClientInit(XLoader_ClientInstance *InstancePtr, XMailbox *MailboxPtr)
This function sets the instance of mailbox.
InstancePtr Pointer to the client instance. MailboxPtr Pointer to the mailbox instance. XST_SUCCESS On successful initialization.XST_FAILURE On failure.
References XLoader_ClientInstance::MailboxPtr.
Referenced by main.