xloader_secure.c
XLOADER_SHA3_RESET_REG
SHA3 Reset register address.
Referenced by XLoader_SecureClear.
XLOADER_SHA3_RESET_VAL
SHA3 Reset value.
Referenced by XLoader_SecureClear.
static int XLoader_StartNextChunkCopy(XLoader_SecureParams *SecurePtr, u32 TotalLen, u64 NextBlkAddr, u32 ChunkLen)
This function starts next chunk copy when security is enabled.
SecurePtr is pointer to the XLoader_SecureParams instance. TotalLen is total length of the partition in bytes. NextBlkAddr is the address of the next chunk data to be copied. ChunkLen is size of the data block to be copied. XST_SUCCESS on success.XLOADER_ERR_DATA_COPY_FAIL if failed to copy data to PMC RAM.
static int XLoader_ChecksumInit(XLoader_SecureParams *SecurePtr, const XilPdi_PrtnHdr *PrtnHdr)
This function initializes checksum parameters of XLoader_SecureParams's instance.
SecurePtr is pointer to the XLoader_SecureParams instance. PrtnHdr is pointer to XilPdi_PrtnHdr instance XST_SUCCESS on success.XLOADER_ERR_INIT_INVALID_CHECKSUM_TYPE on unsupported checksum type.XLOADER_ERR_INIT_CHECKSUM_COPY_FAIL if failed to copy checksum from flash device.
static int XLoader_ProcessChecksumPrtn(XLoader_SecureParams *SecurePtr, u64 DestAddr, u32 BlockSize, u8 Last)
This function performs checksum of the partition.
SecurePtr is pointer to the XLoader_SecureParams instance DestAddr is the address to which data is copied BlockSize is size of the data block to be processed which doesn't include padding lengths and hash. Last notifies if the block to be processed is last or not XST_SUCCESS on success.XLOADER_ERR_DMA_TRANSFER if DMA transfer fails to copy.
int XLoader_SecureInit(XLoader_SecureParams *SecurePtr, XilPdi *PdiPtr, u32 PrtnNum)
This function initializes XLoader_SecureParams's instance.
SecurePtr is pointer to the XLoader_SecureParams instance. PdiPtr is pointer to the XilPdi instance PrtnNum is the partition number to be processed XST_SUCCESS on success.XLOADER_ERR_MEMSET_SECURE_PTR if failed to set memory for secure pointer.XLOADER_ERR_INIT_GET_DMA if failed to get DMA instance during initialization.
References XLoader_SecureParams::BlockNum, XLoader_SecureParams::ChunkAddr, XilPdi::MetaHdr, XLoader_SecureParams::NextChunkAddr, XLoader_SecureParams::PdiPtr, XLoader_SecureParams::PmcDmaInstPtr, XLoader_SecureParams::ProcessedLen, XLoader_SecureParams::PrtnHdr, XLoader_CheckSecureState, XLoader_GetAHWRoT, XLoader_GetSHWRoT, XLoader_GetTempParams, XLoader_SecureAuthInit, XLoader_SecureEncInit, XLoader_VerifyRevokeId.
int XLoader_SecureCopy(XLoader_SecureParams *SecurePtr, u64 DestAddr, u32 Size)
This function loads secure non-cdo partitions.
SecurePtr is pointer to the XLoader_SecureParams instance. DestAddr is load address of the partition. Size is unencrypted size of the partition in bytes. XST_SUCCESS on success and error code on failure
References XLoader_SecureParams::ChunkAddr, XLoader_SecureParams::NextChunkAddr, XLoader_SecureParams::ProcessedLen, XLoader_SecureParams::ProcessPrtn, XLoader_SecureParams::RemainingDataLen, XLoader_SecureParams::SecureDataLen, XLOADER_SECURE_CHUNK_SIZE.
Referenced by XLoader_PrtnCopy.
int XLoader_SecureClear(void)
This function is called to clear secure critical data in case of exceptions.
The function also places AES, ECDSA_RSA and SHA3 in reset. XST_SUCCESS on success.XLOADER_ERR_SECURE_CLEAR_FAIL if failed to clear AES, RSA, SHA3 engines.
References XLoader_AuthEncClear, XLOADER_SHA3_RESET_REG, XLOADER_SHA3_RESET_VAL.
int XLoader_VerifyHashNUpdateNext(XLoader_SecureParams *SecurePtr, u64 DataAddr, u32 Size, u8 Last)
This function calculates hash and compares with expected hash.
For every block, hash of next block is updated into expected hash. SecurePtr is pointer to the XLoader_SecureParams instance. DataAddr is the address of the data present in the block Size is size of the data block to be processed Last notifies if the block to be processed is last or not. XST_SUCCESS on success.XLOADER_ERR_PRTN_HASH_CALC_FAIL if failed to calculate hash for partition authentication.XLOADER_ERR_PRTN_HASH_COMPARE_FAIL on partition comparison fail.
References XLoader_SecureParams::BlockNum, XLoader_SecureParams::ChunkAddr, XilPdi::ImagePrtnId, XLoader_SecureParams::IsCdo, XLoader_SecureParams::PdiPtr, XLoader_SecureParams::PmcDmaInstPtr, XLoader_SecureParams::Sha3Hash.
int XLoader_SecureChunkCopy(XLoader_SecureParams *SecurePtr, u64 SrcAddr, u8 Last, u32 BlockSize, u32 TotalSize)
This function copies the data from SrcAddr to chunk memory during processing of secure partitions.
SecurePtr is pointer to the XLoader_SecureParams instance SrcAddr is the source address from which the data is to be processed or copied Last notifies if the block to be processed is last or not BlockSize is size of the data block to be processed which doesn't include padding lengths and hash. TotalSize is pointer to TotalSize which has to be processed XST_SUCCESS on success.XLOADER_ERR_DATA_COPY_FAIL if failed to copy data to PMC RAM.
References XLoader_SecureParams::BlockNum, XLoader_SecureParams::ChunkAddr, XLoader_SecureParams::DmaFlags, XLoader_SecureParams::IsNextChunkCopyStarted, XilPdi::MetaHdr, XLoader_SecureParams::PdiPtr, XLoader_SecureParams::RemainingDataLen.
int XLoader_CheckNonZeroPpk(void)
This function checks if PPK is programmed.
XST_SUCCESS if PPK is programmed.XLOADER_ERR_GLITCH_DETECTED if glitch is detected.XST_FAILURE on failure.
References XLOADER_EFUSE_PPK0_START_OFFSET, XLOADER_EFUSE_PPK2_END_OFFSET.
Referenced by XLoader_CheckSecureStateAuth.
u32 XLoader_GetAHWRoT(const u32 *AHWRoTPtr)
This function returns the state of authenticated boot.
AHWRoTPtr - Always NULL except at time of initialization of SecureStateAHWRoT variable XPLMI_RTCFG_SECURESTATE_AHWROT - PPK fuses are programmedXPLMI_RTCFG_SECURESTATE_EMUL_AHWROT - BHDR auth is enabledXPLMI_RTCFG_SECURESTATE_NONSECURE - Neither PPK fuses are programmed nor BH auth is enabled
Referenced by XLoader_AddDeviceStateChangeToScheduler, XLoader_MeasureRomAndPlm, XLoader_SecureInit, XLoader_SetSecureState.
u32 XLoader_GetSHWRoT(const u32 *SHWRoTPtr)
This function returns the state of encrypted boot.
SHWRoTPtr - Always NULL except at time of initialization of SecureStateSHWRoT variable XPLMI_RTCFG_SECURESTATE_SHWROT - Any DEC only fuse is programmedXPLMI_RTCFG_SECURESTATE_EMUL_SHWROT - PLM is encryptedXPLMI_RTCFG_SECURESTATE_NONSECURE - Neither DEC only fuses are programmed nor PLM is encrypted
Referenced by XLoader_AddDeviceStateChangeToScheduler, XLoader_SecureInit, XLoader_SetSecureState.
int XLoader_SetSecureState(void)
This function reads the value of PPK efuse bits, DEC only efuse bits and fields in bootheader and accordingly sets the Secure State of boot.
XST_SUCCESS on SUCCESS and error code in case of failure. The Secure State of the device will be stored in two 32-bit registers in RTC area of PMCRAM and two global variables -one for authenticated boot and other for encrypted boot, for redundancy.
References XLoader_CheckSecureStateAuth, XLOADER_EFUSE_SEC_DEC_MASK, XLOADER_EFUSE_SEC_MISC0_OFFSET, XLoader_GetAHWRoT, XLoader_GetSHWRoT.
Referenced by XLoader_Init.
XLoader_SecureTempParams* XLoader_GetTempParams(void)
This function returns the pointer to XLoader_SecureTempParams.
Pointer to XLoader_SecureTempParams
Referenced by XLoader_PrtnCopy, XLoader_SecureInit.