xloader_cfi.c
CFRAME_BCAST_REG_TESTMODE_OFFSET
Test mode offset.
Referenced by XLoader_CframeDataClearCheck.
CFRAME_BCAST_REG_TESTMODE_CRAM_SELF_CHECK_MASK
CRAM self check mask.
Referenced by XLoader_CframeDataClearCheck.
CFRAME_BCAST_REG_FAR_OFFSET
CFrame address register offset.
Referenced by XLoader_CframeDataClearCheck.
CFRAME_BCAST_REG_FAR_BLOCKTYPE_SHIFT
CFrame address register block type shift.
Referenced by XLoader_CframeDataClearCheck.
CFRAME_MAX_BLOCK_TYPE_COUNT
CFrame maximum block type count.
Referenced by XLoader_CframeDataClearCheck.
XPLMI_ZERO
Zero.
Referenced by XLoader_CframeDataClearCheck.
CFRAME_CRC_POLL_TIMEOUT
CRC poll time out.
Referenced by XLoader_CframeDataClearCheck.
XLOADER_CFRAME_DATACLEAR_CHECK_CMD_ID
Data clear check command Id.
Referenced by XLoader_CframeDataClearCheck.
PMC_GLOBAL_PMC_ERR2_STATUS_CFI_SHIFT
CFI Non-Correctable Error shift.
Referenced by XLoader_CframeErrorHandler.
XCframe XLoader_CframeIns
CFRAME Driver Instance.
static void XLoader_CfiErrHandler(const XCfupmc *InstancePtr)
This function is used for Cframe error handling.
InstancePtr is a pointer to the XCfupmc instance.
static void XLoader_CfuErrHandler(const XCfupmc *InstancePtr)
This function is used for CFU error handling.
InstancePtr is a pointer to the XCfupmc instance.
int XLoader_CframeInit(void)
This function initializes the Cframe driver.
XST_SUCCESS on success.XLOADER_ERR_CFRAME_LOOKUP if CFrame lookup fails.XLOADER_ERR_CFRAME_CFG if CFrame configuration fails.
Referenced by XLoader_CfiSelectiveRead, XLoader_CframeDataClearCheck, XLoader_Init.
void XLoader_CframeErrorHandler(u32 ImageId)
This function is used to check the CFU ISR and PMC_ERR1 and PMC_ERR2 status registers to check for any errors in PL and call corresponding error recovery functions if needed.
ImageId is Id of the image present in PDI
References PMC_GLOBAL_PMC_ERR2_STATUS_CFI_SHIFT.
int XLoader_CframeDataClearCheck(XPlmi_Cmd *Cmd)
This function is used to check if the Cframe data is cleared or not using CRC method.
This function need to be called after CFI house cleaning is done. Cmd is pointer to the command. Command payload parameters are: Block Type XST_SUCCESS on success.XLOADER_INVALID_BLOCKTYPE if block type passed is invalid. Only Type 0, Type 1, and Type 2 are supported.XLOADER_CFI_CFRAME_IS_BUSY if CRAM self check fails as CFI CFrame is busy.XLOADER_CFRAME_CRC_CHECK_FAILED if CFRAME CRC check fails.
References CFRAME_BCAST_REG_FAR_BLOCKTYPE_SHIFT, CFRAME_BCAST_REG_FAR_OFFSET, CFRAME_BCAST_REG_TESTMODE_CRAM_SELF_CHECK_MASK, CFRAME_BCAST_REG_TESTMODE_OFFSET, CFRAME_CRC_POLL_TIMEOUT, CFRAME_MAX_BLOCK_TYPE_COUNT, XLOADER_CFI_CFRAME_IS_BUSY, XLOADER_CFRAME_CRC_CHECK_FAILED, XLOADER_CFRAME_DATACLEAR_CHECK_CMD_ID, XLoader_CframeInit, XLOADER_INVALID_BLOCKTYPE, XPLMI_ZERO.
int XLoader_CfiSelectiveRead(XPlmi_Cmd *Cmd)
This function provides CFI SELECTIVE READ command execution.
Command payload parameters are: - Row, block type and start frame address - Frame count to be read from CFI(1 frame = 25 quad words - High Dest Addr - Low Dest Addr Cmd is pointer to the command structure XST_SUCCESS on success.Error code on failure
References XLOADER_CFI_SEL_READBACK_ID, XLoader_CframeInit, XLOADER_ERR_INVALID_BLOCK_TYPE, XLOADER_ERR_INVALID_ROW, XLOADER_FRAME_COUNT_EXCEEDS_LASTFRAME, XLOADER_INVALID_FRAME_ADDRESS, XLOADER_SELREADBACK_ROW_MASK.