xloader_auth_enc.c
XLOADER_RSA_PSS_MSB_PADDING_MASK
RSA PSS MSB padding mask.
XLOADER_RSA_EM_MSB_INDEX
RSA EM MSB Index.
XLOADER_PUF_SHUT_GLB_VAR_FLTR_EN_SHIFT
Shift for Global Variation Filter in PUF shutter value.
XLOADER_AES_RESET_VAL
AES Reset value.
XLOADER_AES_RESET_REG
AES Reset register address.
XLOADER_ECDSA_RSA_RESET_REG
ECDSA RSA Reset register address.
XLOADER_ECDSA_RSA_RESET_VAL
ECDSA RSA Reset value.
XLOADER_GET_PRTN_HASH_INDEX
Get partition hash index depending on full/IPU/partial/full metaheader PDI.
static int XLoader_EcdsaSignVerify(const XSecure_EllipticCrvTyp CrvType, const u8 *DataHash, const u8 *Key, const u32 KeySize, const u8 *Signature)
This function verifies the ECDSA signature provided with key components.
CrvType is the type of the ECDSA curve DataHash is pointer to the hash of the data to be authenticated Key is pointer to the ECDSA key. KeySize is the size of the public key component in bytes Signature is pointer to the ECDSA signature XST_SUCCESS on success.XLOADER_SEC_ECDSA_INVLD_KEY_COORDINATES on invalid key coordinated for ECDSA.XLOADER_SEC_ECDSA_AUTH_FAIL if failed to verify ECDSA signature.
static int XLoader_RsaSignVerify(u8 *MsgHash, XLoader_RsaKey *Key, u8 *Signature)
This function initializes the RSA module with provided key and verifies the signature.
MsgHash of the data to be authenticated. Key is pointer to the XSecure_Rsa instance. Signature is pointer to RSA signature for data to be authenticated. XST_SUCCESS on success.XLOADER_SEC_RSA_AUTH_FAIL if failed to verify RSA signature.
static int XLoader_AesDecryption(XLoader_SecureParams *SecurePtr, u64 SrcAddr, u64 DestAddr, u32 Size)
This function decrypts the data.
SecurePtr is pointer to the XLoader_SecureParams SrcAddr is address to the buffer where header/footer present DestAddr is the address to which header / footer is copied Size is the number of bytes to be copied XST_SUCCESS on success.XLOADER_SEC_AES_OPERATION_FAILED on AES operation failure.XLOADER_SEC_DPA_CM_ERR if failed to configure DPA CM.
static int XLoader_AesKeySelect(const XLoader_SecureParams *SecurePtr, XLoader_AesKekInfo *KeyDetails, XSecure_AesKeySrc *KeySrc)
This function helps in key selection.
SecurePtr is pointer to the XLoader_SecureParams KeyDetails is pointer to the key details. KeySrc is pointer to the key source to be updated as key source for decrypting. If key provided is KEK format, this API decrypts and provides the red key source. XST_SUCCESS on success.XLOADER_SEC_DEC_INVALID_KEYSRC_SEL on invalid key source selected for decryption.XLOADER_SEC_AES_KEK_DEC if failed to decrypt KEK.
static int XLoader_PpkCompare(const u32 EfusePpkOffset, const u8 *PpkHash)
This function compares calculated PPK hash with the efuse PPK hash.
EfusePpkOffset is PPK hash address of efuse. PpkHash is pointer to the PPK hash to be verified. XST_SUCCESS on success.XLOADER_SEC_PPK_HASH_COMPARE_FAIL if hash comparison failed.
static int XLoader_DecHdrs(XLoader_SecureParams *SecurePtr, XilPdi_MetaHdr *MetaHdr, u64 BufferAddr)
This function decrypts headers.
SecurePtr Pointer to the XLoader_SecureParams MetaHdr Pointer to the Meta header. BufferAddr Read whole headers to the mentioned buffer address XST_SUCCESS on success.XLOADER_ERR_HDR_NOT_ENCRYPTED image header or partition header is not encrypted.XLOADER_ERR_GLITCH_DETECTED if glitch is detected.XLOADER_ERR_HDR_AES_OP_FAIL if failed due to AES init or Decrypt init or key selection failure.XLOADER_SEC_EFUSE_DPA_CM_MISMATCH_ERROR Metahdr DpaCm & eFuse DpaCm values are not matched.XLOADER_SEC_DPA_CM_ERR if failed to configure DPA CM.XLOADER_ERR_HDR_AES_OP_FAIL if failed to initialize AES or Decrypt or key selection.XLOADER_ERR_HDR_AAD_UPDATE_FAIL if failed to update IHT as AAD during secure header decryption.XLOADER_ERR_HDR_DEC_FAIL if failed to decrypt IH/PH.
static int XLoader_SpkAuthentication(const XLoader_SecureParams *SecurePtr)
This function verifies SPK with PPK.
SecurePtr is pointer to the XLoader_SecureParams instance. XST_SUCCESS on success.XLOADER_SEC_SPK_HASH_CALCULATION_FAIL if SPK hash calculation fails.XLOADER_SEC_BUF_CLEAR_ERR if error in clearing buffer.
static int XLoader_AuthNDecHdrs(XLoader_SecureParams *SecurePtr, XilPdi_MetaHdr *MetaHdr, u64 BufferAddr)
This function authenticates and decrypts the headers.
SecurePtr Pointer to the XLoader_SecureParams MetaHdr Pointer to the Meta header. BufferAddr Read whole headers to the mentioned buffer address. XST_SUCCESS on success.XLOADER_ERR_HDR_HASH_CALC_FAIL if failed to calculate hash for image header or partition header.XLOADER_ERR_HDR_AUTH_FAIL if failed to authenticate for image header or partition header.XLOADER_SEC_BUF_CLEAR_ERR if failed to clear the buffer.XLOADER_SEC_BUF_CLEAR_SUCCESS if successfully cleared buffer.
static int XLoader_AuthHdrs(const XLoader_SecureParams *SecurePtr, XilPdi_MetaHdr *MetaHdr)
This function authenticates image headers and partition headers of image.
SecurePtr Pointer to the XLoader_SecureParams MetaHdr Pointer to the Meta header. XST_SUCCESS on success.XLOADER_ERR_SEC_IH_READ_FAIL if failed to read image header.XLOADER_ERR_SEC_PH_READ_FAIL if failed to read partition header.XLOADER_ERR_HDR_HASH_CALC_FAIL if failed to calculate hash for image header or partition header.XLOADER_ERR_HDR_AUTH_FAIL if failed to authenticate for image header or partition header.XLOADER_SEC_BUF_CLEAR_ERR if failed to clear the buffer.
static int XLoader_CheckAndCompareHashFromIHTOptionalData(XilPdi *PdiPtr, u8 *HashPtr, u32 PrtnHashIndex)
This function checks whether Partition hash is present or not and compares the calculated hash with hash which is present in IHT Optional data for the respective partitions.
PdiPtr is pointer to the xilpdi instance HashPtr is pointer to Hash array PrtnHashIndex is index of partition hash in IHT optional data XST_SUCCESS on success.XLOADER_SEC_PRTN_HASH_NOT_PRESENT_IN_IHT_OP_DATA_ERR if partition hash is not present in IHT optional data.XLOADER_SEC_PRTN_HASH_COMPARE_FAIL_ERR if partition hash comparison fails.
static int XLoader_VerifyAuthHashNUpdateNext(XLoader_SecureParams *SecurePtr, u32 Size, u8 Last)
This function calculates hash and compares with expected hash.
Hash is calculated on AC + Data for first block, encrypts the ECDSA/RSA signature and compares it with the expected hash. After first block, hash is calculated on block of data and compared with the expected hash. SecurePtr is pointer to the XLoader_SecureParams instance Size is size of the data block to be processed which includes padding lengths and hash Last notifies if the block to be processed is last or not XST_SUCCESS on success.XLOADER_ERR_PRTN_HASH_CALC_FAIL if hash calculation fails for partition authentication.XLOADER_ERR_PRTN_AUTH_FAIL if partition authentication fails.XLOADER_ERR_PRTN_HASH_COMPARE_FAIL if failed to compare partition hash.XLOADER_SEC_BUF_CLEAR_ERR if failed to clear buffer.
static int XLoader_SetAesDpaCm(const XSecure_Aes *AesInstPtr, u8 DpaCmCfg)
This function enables or disables DPA counter measures.
AesInstPtr Pointer to the XSecure_Aes instance. DpaCmCfg TRUE - to enable AES DPA counter measureFALSE -to disable AES DPA counter measure XST_SUCCESS if enable/disable of DPA was successful.Error if device doesn't support DPA CM or configuration is not successful
static int XLoader_DecryptBlkKey(const XSecure_Aes *AesInstPtr, const XLoader_AesKekInfo *KeyDetails)
This function decrypts the black key with PUF key and stores in specified destination AES red key register.
AesInstPtr is pointer to the XSecure_Aes instance. KeyDetails is pointer to the XLoader_AesKekInfo instance. XST_SUCCESS on success and error code on failureXLOADER_SEC_PUF_REGN_ERRR if failed to regenerate PUF.XLOADER_SEC_AES_KEK_DEC if failed to decrypt KEK.
static int XLoader_SecureEncOnlyValidations(const XLoader_SecureParams *SecurePtr)
This function validates the encryption keysrc, puf helper data location and eFUSE IV for ENC only case.
SecurePtr is pointer to the XLoader_SecureParams instance. XST_SUCCESS on success.XLOADER_SEC_ENC_ONLY_KEYSRC_ERR if key source is not from efuse black key when encrypt only is enabled.XLOADER_SEC_ENC_ONLY_PUFHD_LOC_ERR if PUFHD location is from eFuse when encrypt only is enabled.
static int XLoader_ValidateIV(const u32 *IHPtr, const u32 *EfusePtr)
IV Criteria check.
IHPtr is the IV to be compared EfusePtr is the eFUSE cache address XST_SUCCESS on success.XLOADER_SEC_IV_METAHDR_RANGE_ERROR on Failure. Example: iv[95:0] - F7F8FDE0 8674A28D C6ED8E37 Bootgen follows the big-endian format so the values stored will beIHPtr[0]=E0FDF8F7 -> IV[64:95] IHPtr[1]=8DA27486 -> IV[32:63] IhPtr[2]=378EEDC6 -> IV[0:31]Our xilnvm driver also follows the same format to store it in eFUSEEfusePtr[0]=C6ED8E37 -> IV[31:0] EfusePtr[1]=8674A28D -> IV[63:32] EfusePtr[2]=F7F8FDE0 -> IV[95:64]]Spec says: IV[95:32] defined by user in meta header should match with eFUSEIV[95:32] IV[31:0] defined by user in meta header should >= eFUSEIV[31:0]
static int XLoader_ClearAesKeysOnCfg(void)
This function clears the AES PUF,RED and expanded keys.
XST_SUCCESS on success.XST_FAILURE if AES key zero or AES reset fails.
int XLoader_SecureAuthInit(XLoader_SecureParams *SecurePtr, const XilPdi_PrtnHdr *PrtnHdr)
This function initializes authentication parameters of XLoader_SecureParams's instance.
SecurePtr is pointer to the XLoader_SecureParams instance. PrtnHdr is pointer to XilPdi_PrtnHdr instance that has to be processed. XST_SUCCESS on success.XLOADER_ERR_INIT_AC_COPY_FAIL if failed to copy authentication certificate from flash device.
Referenced by XLoader_SecureInit.
int XLoader_SecureEncInit(XLoader_SecureParams *SecurePtr, const XilPdi_PrtnHdr *PrtnHdr)
This function initializes encryption parameters of XLoader_SecureParams's instance.
SecurePtr is pointer to the XLoader_SecureParams instance. PrtnHdr is pointer to XilPdi_PrtnHdr instance that has to be processed. XST_SUCCESS on success.XLOADER_ERR_INIT_CHECKSUM_INVLD_WITH_AUTHDEC if both checksum and authentication or encryption are enabled.XLOADER_ERR_PRTN_DECRYPT_NOT_ALLOWED if Partition is not allowed to be encrypted if State of boot is non secure.XLOADER_ERR_GLITCH_DETECTED if glitch is detected.XLOADER_ERR_PRTN_ENC_ONLY_KEYSRC on invalid key source when only encryption is enabled.
Referenced by XLoader_SecureInit.
int XLoader_SecureValidations(const XLoader_SecureParams *SecurePtr)
This function checks if authentication/encryption is compulsory.
SecurePtr is pointer to the XLoader_SecureParams instance. XST_SUCCESS on success.XLOADER_ERR_GLITCH_DETECTED if glitch is detected.XLOADER_ERR_AUTH_EN_PPK_HASH_ZERO if PPK not programmed and authentication is enabledXLOADER_ERR_HWROT_EFUSE_AUTH_COMPULSORY if PPK Programmed but eFuse authentication is disabled.XLOADER_ERR_ENCONLY_ENC_COMPULSORY if encryption is disabled.XLOADER_ERR_METAHDR_KEYSRC_MISMATCH if metaheader Key Source does not match PLM Key Source.
int XLoader_ReadAndVerifySecureHdrs(XLoader_SecureParams *SecurePtr, XilPdi_MetaHdr *MetaHdr)
This function authenticates and/or decrypts the image headers and partition headers and copies the contents to the corresponding structures.
SecurePtr Pointer to the XLoader_SecureParams instance. MetaHdr Pointer to the Meta header table. XST_SUCCESS on success.XLOADER_ERR_HDR_GET_DMA if acquiring DMA fails.XLOADER_ERR_HDR_AES_OP_FAIL if AES initialization fails.XLOADER_ERR_METAHDR_LEN_OVERFLOW on meta header length overflow.XLOADER_ERR_HDR_COPY_FAIL on IH/PH header copy fail.XLOADER_ERR_SEC_IH_READ_FAIL on image header read fail.XLOADER_ERR_SEC_IH_VERIFY_FAIL on image header verify fail.XLOADER_ERR_HDR_NOT_SECURE if neither authentication nor encryption is enabled for IH/PH.XLOADER_ERR_SEC_PH_READ_FAIL if partition header read fails.XLOADER_ERR_SEC_PH_VERIFY_FAIL if partition header verification fails.
int XLoader_VerifySignature(const XLoader_SecureParams *SecurePtr, u8 *Hash, XLoader_AuthKey *AuthKey, u8 *Signature)
This function verifies the signature (RSA/ECDSA) using the provided key and compares the result with the expected hash.
SecurePtr is pointer to the XLoader_SecureParams instance. Hash is pointer to the expected hash to be verified AuthKey is pointer to the RSA/ECDSA public key to be used for verification Signature is pointer to the signature to be verified XST_SUCCESS on successful signature verification.XLOADER_SEC_INVALID_AUTH on invalid authentication type.XLOADER_ERR_RSA_NOT_ENABLED if RSA is excluded from build.XLOADER_ERR_ECDSA_NOT_ENABLED if ECDSA is excluded from build.XLOADER_SEC_CURVE_NOT_SUPPORTED if P-521 curve is not supported.
References XLoader_AuthJtagMessage::AuthHdr, XLoader_SecureParams::AuthJtagMessagePtr.
int XLoader_VerifyRevokeId(u32 RevokeId)
This function validates SPK by verifying if the given SPK ID has been revoked or not.
RevokeId is ID of the SPK to be verified for revocation XST_SUCCESS on success.XLOADER_SEC_REVOCATION_ID_OUTOFRANGE_ERR if revocation ID is out of range.XLOADER_SEC_ID_REVOKED if revocation ID range not verified.
Referenced by XLoader_SecureInit.
int XLoader_IsPpkValid(const u8 *PpkHash)
This function validates PPK hash against eFUSE stored hash.
It iterates through all PPKs and checks if the provided hash matches any valid (non-revoked) PPK. PpkHash Pointer to the PPK hash to be verified. XST_SUCCESS on success.XLOADER_SEC_INVALID_PPK_CHOICE_ERR if invalid PPK selection.XLOADER_SEC_PPK_HASH_COMPARE_FAIL if PPK hash comparison failed.XLOADER_SEC_PPK_HASH_ALLZERO_INVLD if PPK hash is all zeros.XLOADER_SEC_ALL_PPK_REVOKED_ERR if all PPKs are revoked.XLOADER_SEC_SEL_PPK_REVOKED_ERR if selected PPK is revoked.
References XLoader_GetPpkInvalidMaskAndOffset, XLoader_ValidatePpkHash.
int XLoader_PpkVerify(const XLoader_SecureParams *SecurePtr, const u32 PpkSize)
This function verifies PPK.
SecurePtr is pointer to the XLoader_SecureParams instance. PpkSize is Size of the PPK to be verified XST_SUCCESS on success.XLOADER_SEC_ALL_PPK_REVOKED_ERR if all PPKs are revoked.XLOADER_SEC_PPK_HASH_CALCULATION_FAIL if PPK hash calculation failsXLOADER_SEC_ALL_PPK_INVALID_ERR if all PPKs are invalid.XLOADER_SEC_BUF_CLEAR_ERR if failed to clear buffer.
int XLoader_RsaPssSignVerify(u8 *MsgHash, XSecure_Rsa *RsaInstPtr, u8 *Signature, u32 KeySize)
This function encrypts the RSA signature provided and performs required PSS operations to extract salt and calculates M prime hash and compares with hash obtained from EM.
MsgHash of the data to be authenticated. RsaInstPtr is pointer to the XSecure_Rsa instance. Signature is pointer to RSA signature for data to be authenticated. KeySize is size of RSA key in bytes. XST_SUCCESS on success.XLOADER_SEC_MEMSET_ERROR and XLOADER_SEC_RSA_MEMSET_SHA3_ARRAY_FAIL if failed to create memory for RSA SHA3.XLOADER_SEC_MEMSET_ERROR and XLOADER_SEC_RSA_MEMSET_VARSCOM_FAIL if failed to create memory for RSA varscom.XLOADER_SEC_RSA_PSS_ENC_BC_VALUE_NOT_MATCHED if failed to match with RSA ENC 0xbc value.XLOADER_SEC_MASKED_DB_MSB_ERROR if error in RSA EM MSB.XLOADER_SEC_RSA_PSS_SIGN_VERIFY_FAIL if failed to verify RSA PSS signature.XLOADER_SEC_EFUSE_DB_PATTERN_MISMATCH_ERROR if failed to verify database in efuse.XLOADER_SEC_RSA_PSS_HASH_COMPARE_FAILURE if RSA PSS hash is not matched.XLOADER_SEC_BUF_CLEAR_ERR if failed to clear buffer.
static int XLoader_DecryptSecureBlk(XLoader_SecureParams *SecurePtr, u64 SrcAddr)
This function decrypts the secure header/footer.
SecurePtr Pointer to the XLoader_SecureParams SrcAddr Pointer to the buffer where header/footer present XST_SUCCESS on success.XLOADER_SEC_AES_OPERATION_FAILED on AES operation failure.XLOADER_SEC_ENC_DATA_NOT_ALIGNED_ERROR if encrypted data is not 128-bit aligned.
static int XLoader_DataDecrypt(XLoader_SecureParams *SecurePtr, u64 SrcAddr, u64 DestAddr, u32 Size)
This function decrypts the data.
SecurePtr is pointer to the XLoader_SecureParams SrcAddr is pointer to the buffer where header/footer present DestAddr is pointer to the buffer where header/footer should be copied Size is the number of byte sto be copied XST_SUCCESS on success.XLOADER_SEC_AES_OPERATION_FAILED on AES operation failure.XLOADER_SEC_DATA_LEFT_FOR_DECRYPT_ERR if data is still left for decryption.XLOADER_SEC_DECRYPT_REM_DATA_SIZE_MISMATCH if there is a size mismatch for the remaining data left for decryption.
int XLoader_EnableJtag(volatile u32 CfgState)
This function enables the Jtag.
CfgState is the configuration state for DAP XST_SUCCESS on SUCCESSErrorcode upon failure
References XLOADER_DAP_CFG_ENABLE_ALL_DBG_MASK.
Referenced by XLoader_ConfigureJtagState.
int XLoader_DisableJtag(void)
This function disables the Jtag.
XST_SUCCESS on SUCCESSErrorcode upon failure
Referenced by XLoader_ConfigureJtagState.
int XLoader_AuthEncClear(void)
This function is called to clear secure critical data related to authentication and encryption in case of exceptions.
The function also places AES, ECDSA_RSA in reset. XST_SUCCESS on success.XST_FAILURE on failure.
Referenced by XLoader_SecureClear.
int XLoader_ClearAesKey(u32 *DecKeySrc)
This function clears the AES keys when RedKeyClear is set in PMC RAM.
DecKeySrc is pointer to the Decrypt Key source XST_SUCCESS on success.XLOADER_SEC_KEY_CLEAR_FAILED_ERROR if AES key clear fails.
References XLOADER_SEC_KEY_CLEAR_FAILED_ERROR.
int XLoader_ProcessAuthEncPrtn(XLoader_SecureParams *SecurePtr, u64 DestAddr, u32 BlockSize, u8 Last)
This function performs authentication and decryption of the partition.
SecurePtr is pointer to the XLoader_SecureParams instance DestAddr is the address to which data is copied BlockSize is size of the data block to be processed which doesn't include padding lengths and hash Last notifies if the block to be processed is last or not XST_SUCCESS on success.XLOADER_ERR_DMA_TRANSFER if DMA transfer fails while copying.XLOADER_ERR_PRTN_DECRYPT_FAIL if partition decryption fails.XLOADER_SEC_BUF_CLEAR_SUCCESS if successfully cleared buffer.XLOADER_SEC_BUF_CLEAR_ERR if failed to clear buffer.
int XLoader_CheckSecureState(u32 RegVal, u32 Var, u32 ExpectedValue)
This function checks if the secure state of boot matches the expected value or not.
RegVal - Value of secure state stored in register Var - Value of secure state stored in variable ExpectedValue - Expected value of secure state XST_SUCCESS on success.XST_FAILURE if RegVal, Var, or ExpectedValue do not all match.
Referenced by XLoader_SecureInit.
int XLoader_AuthKat(XLoader_SecureParams *SecurePtr)
This function runs RSA or Ecdsa KAT based on pdi.
SecurePtr is pointer to the XLoader_SecureParams instance XST_SUCCESS on success.XLOADER_SEC_INVALID_AUTH on invalid authentication type.XLOADER_ERR_RSA_NOT_ENABLED if RSA is not enabled.XLOADER_ERR_ECDSA_NOT_ENABLED if ECDSA is not enabled.
References XLoader_AuthJtagMessage::AuthHdr, XLoader_SecureParams::AuthJtagMessagePtr.
int XLoader_ImgHdrTblAuth(XLoader_SecureParams *SecurePtr)
This function authenticates the image header table.
SecurePtr is pointer to the XLoader_SecureParams instance XST_SUCCESS on success.XLOADER_ERR_IHT_GET_DMA if acquiring DMA is failed.XLOADER_ERR_IHT_COPY_FAIL if IHT copy fails.XLOADER_ERR_IHT_HASH_CALC_FAIL if IHT hash calculation fails.XLOADER_ERR_IHT_AUTH_FAIL if IHT authentication fails.
int XLoader_DataAuth(XLoader_SecureParams *SecurePtr, u8 *Hash, u8 *Signature)
This function authenticates the data with SPK.
SecurePtr is pointer to the XLoader_SecureParams instance. Hash is a Pointer to the expected hash buffer. Signature pointer points to the signature buffer. XST_SUCCESS on success.XLOADER_SEC_GLITCH_DETECTED_ERROR if glitch is detected.
int XLoader_GetPpkInvalidMaskAndOffset(XLoader_PpkSel PpkSelect, u32 *InvalidMask, u32 *PpkOffset)
This function calculates the invalid mask and PPK offset based on the selected PPK.
PpkSelect is PPK selection of eFUSE. InvalidMask is pointer to store the invalid mask for the selected PPK. PpkOffset is pointer to store the PPK eFUSE offset. XST_SUCCESS on success.XLOADER_SEC_INVALID_PPK_CHOICE_ERR if invalid PPK selection.
References XLOADER_EFUSE_MISC_CTRL_PPK0_INVLD, XLOADER_EFUSE_MISC_CTRL_PPK1_INVLD, XLOADER_EFUSE_MISC_CTRL_PPK2_INVLD, XLOADER_EFUSE_MISC_CTRL_PPK3_INVLD, XLOADER_EFUSE_MISC_CTRL_PPK4_INVLD, XLOADER_EFUSE_MISC_CTRL_PPK5_INVLD, XLOADER_EFUSE_MISC_CTRL_PPK6_INVLD, XLOADER_EFUSE_MISC_CTRL_PPK7_INVLD, XLOADER_EFUSE_MISC_CTRL_PPK8_INVLD, XLOADER_EFUSE_PPK0_START_OFFSET, XLOADER_EFUSE_PPK1_START_OFFSET, XLOADER_EFUSE_PPK2_START_OFFSET, XLOADER_PPK_SEL_0, XLOADER_PPK_SEL_1, XLOADER_PPK_SEL_2.
Referenced by XLoader_IsPpkValid.
int XLoader_IsPpkRevoked(u32 PpkInvldMask)
This function checks if the selected PPK is revoked by reading the PPK invalid bits from eFUSE.
PpkInvldMask is the PPK invalid bit mask to check in eFUSE. XST_SUCCESS if PPK is not revoked.XLOADER_SEC_SEL_PPK_REVOKED_ERR if PPK is revoked (invalid bit set).XLOADER_SEC_ALL_PPK_REVOKED_ERR if all PPKs are revoked.
int XLoader_ValidatePpkHash(const u8 *PpkHash, u32 PpkOffset)
This function compares the provided PPK hash with the hash stored in eFUSE and validates it is not all zeros.
PpkHash is pointer to the PPK hash to be verified. PpkOffset is PPK eFUSE offset. XST_SUCCESS on success.XLOADER_SEC_PPK_HASH_COMPARE_FAIL if hash comparison fails.XLOADER_SEC_PPK_HASH_ALLZERO_INVLD if PPK hash is all zeros.
Referenced by XLoader_IsPpkValid.