xloader_generic.h
int XLoader_SendRequest(XLoader_ClientInstance *InstancePtr, u32 *PayloadBuf, u32 PayloadLen, u32 *ResponseBuf, u32 ResponseLen)
This function sends request to PLM through either SMC or IPI mailbox based on the execution environment.
For EL1 non-secure AArch64 applications, SMC is used. For other environments, IPI mailbox is used. InstancePtr Pointer to the client instance PayloadBuf Pointer to the payload message PayloadLen Length of the payload message ResponseBuf Pointer to store response values (can be NULL) ResponseLen Length of the response buffer (can be 0 if ResponseBuf is NULL) XST_SUCCESS If the request is successfulXST_FAILURE If there is a failureXST_INVALID_PARAM If input parameters are invalid
References RESPONSE_ARG_CNT, XLoader_ClientInstance::MailboxPtr, XLoader_ProcessMailbox, XLoader_ClientInstance::Response.
Referenced by XLoader_LoadPartialPdi, XLoader_LoadImage, XLoader_GetImageInfo, XLoader_GetImageInfoList, XLoader_ExtractMetaheader, XLoader_UpdateMultiboot, XLoader_AddImageStorePdi, XLoader_RemoveImageStorePdi, XLoader_GetATFHandOffParams, XLoader_CfiSelectiveReadback, XLoader_GetOptionalData.