xloader.c
XLOADER_IMAGE_INFO_TBL_MAX_NUM
Maximum number of image info tables in the available buffer.
Referenced by XLoader_GetImageInfoEntry.
static int XLoader_ReadAndValidateHdrs(XilPdi *PdiPtr, u32 RegValue, u64 PdiAddr)
This function reads bootheader and metaheader and validates them.
PdiPtr is instance pointer pointing to PDI details RegValue is the value of the Multiboot register PdiAddr is the PDI address XST_SUCCESS on success.XLOADER_ERR_IMGHDR_TBL if PLM is unable to read image header table.XLOADER_ERR_MEMSET_SECURE_PTR if failed to create instance for secure pointer.XLOADER_ERR_UNSUPPORTED_PDI_VER on PDI version used in secure operations is unsupported.XLOADER_ERR_SECURE_NOT_ENABLED on attempt to secure boot in an excluded secure critical code.XLOADER_ERR_GEN_IDCODE on ID code mismatch.XLOADER_ERR_IMGHDR if image header checksum fails.XLOADER_ERR_PRTNHDR if partition header checksum fails.XLOADER_ERR_SECURE_METAHDR if secure metaheader validation fails.
static int XLoader_LoadAndStartSubSystemImages(XilPdi *PdiPtr)
This function is used to load and start images.
It reads meta header, loads the images as present in the PDI and starts images based on hand-off information present in PDI. PdiPtr is Pdi instance pointer XST_SUCCESS on success.XLOADER_ERR_DELAY_ATTRB if both delay handoff and delay load are set for the same image.XLOADER_ERR_NUM_HANDOFF_CPUS if number of CPUs exceed max count.
static int XLoader_LoadAndStartSubSystemPdi(XilPdi *PdiPtr)
This function is used to load the primary and secondary PDIs.
PdiPtr is Pdi instance pointer XST_SUCCESS on success and error code on failure
static int XLoader_LoadAndStartSecondaryPdi(XilPdi *PdiPtr)
This function is used to load the primary and secondary PDIs.
PdiPtr is Pdi instance pointer XST_SUCCESS on success.XLOADER_ERR_UNSUPPORTED_SEC_BOOT_MODE on unsupported secondary boot mode.XLOADER_ERR_MEMSET_PDIPTR if failed to create instance for PdiPtr.
static int XLoader_VerifyImgInfo(const XLoader_ImageInfo *ImageInfo)
This function validates the UIDs in Image Header.
ImageInfo is pointer to the image info in image XST_SUCCESS on success.XLOADER_ERR_DEV_NOT_DEFINED if Device ID of the image to be loaded is not defined.XLOADER_ERR_PARENT_QUERY_VERIFY if Failed to Query Parent ID of an image while verifying its Image UIDs.XLOADER_ERR_INVALID_PARENT_IMG_ID when Invalid ParentImgID is obtained when queried for parent ImgID.XLOADER_ERR_NO_VALID_PARENT_IMG_ENTRY if No Valid Parent Image Entry is found in the ImageInfo Table.XLOADER_ERR_INCOMPATIBLE_CHILD_IMAGE if child image is not compatible with parent image.
static int XLoader_GetChildRelation(u32 ChildImgID, u32 ParentImgID, u32 *IsChild)
This function checks if the given ImgID is a child of Parent ImgID.
ChildImgID is the current ImgID whose relation is to be checked ParentImgID is the ImgID with which the hierarchical ImgIDs are compared in order to get the correct parent-child relationship IsChild is the pointer to the Relation that has to be returned, TRUE if it is a Child, else FALSE XST_SUCCESS on success.XLOADER_ERR_PARENT_QUERY_RELATION_CHECK if parent query fails while checking child relation.
static int XLoader_InvalidateChildImgInfo(u32 ParentImgID, u32 *ChangeCount)
This function invalidates the child image info entries corresponding to the parent image id in the ImageInfo Table.
ParentImgID whose corresponding child image info entries are invalidated ChangeCount points to ChangeCount that has to be modified XST_SUCCESS on success and error code on failure
static int XLoader_ReloadImage(XilPdi *PdiPtr, u32 ImageId, const u32 *FuncID)
This function is used to reload the image only in PDI.
This function will take ImageId as an input and based on the subsystem info available, it will read the image partitions and loads them. PdiPtr is Pdi instance pointer ImageId Id of the image present in PDI FuncID is verified with the FuncID present in PDI XST_SUCCESS on success.XLOADER_ERR_IMG_ID_NOT_FOUND if image id is not found in subsystem when reloading image.XLOADER_ERR_FUNCTION_ID_MISMATCH when Function ID given while loading Image from DDR is not matching with the ID stored in Image Header.
static int XLoader_ClearKeys(XilPdi *PdiPtr)
This function clears AES keys when RedKeyClear is set in PMCRAM.
PdiPtr Pointer to PdiInstance XST_SUCCESS on successErrorCode on failure
static int XLoader_ReadIHsAndPHs(XLoader_SecureParams *SecurePtr)
This function reads the Image Headers and Partition Headers.
SecurePtr is pointer to XLoader_SecureParams XST_SUCCESS on successful read. XST_FAILURE on unsuccessful read.
static int XLoader_VerifyIHsAndPHs(XLoader_SecureParams *SecurePtr)
This function verifies Image headers and Partition headers.
SecurePtr is pointer to XLoader_SecureParams XST_SUCCESS on successful verification. XST_FAILURE on unsuccessful verification.
int XLoader_Init(void)
This function initializes the loader instance and registers loader commands with PLM.
XST_SUCCESS on success and error code on failure
References XLoader_AddDeviceStateChangeToScheduler, XLoader_CframeInit, XLOADER_CL_BEFORE_BOOT, XLoader_IntrInit, XLoader_SetSecureState.
int XLoader_PdiInit(XilPdi *PdiPtr, PdiSrc_t PdiSource, u64 PdiAddr)
This function initializes the PDI instance with required details and read the meta header.
PdiPtr is instance pointer pointing to PDI details PdiSource is source of PDI. It can be any boot Device or DDR PdiAddr is the address at which PDI is located in the PDI source XST_SUCCESS on success.XLOADER_UNSUPPORTED_BOOT_MODE on unsupported boot mode.XLOADER_ERR_UNSUPPORTED_USB_PRIMARY if USB is used as primary boot mode.
References XilPdi::ClearAtfHandoff, XLoader_DeviceOps::Copy, PdiSrcMap::Index, XLoader_DeviceOps::Init, XilPdi::MetaHdr, XilPdi::PdiIndex, XilPdi::PdiSrc, PdiSrc_t, XilPdi::PdiType, XilPdi::SlrType, XLOADER_GET_PDISRC_INFO, XLoader_GetATFHandoffParamsAddr, XLoader_GetPdiInstance, XLOADER_PDI_SRC_USB, XLOADER_PDI_TYPE_FULL, XLOADER_PDISRC_FLAGS_MASK, XLOADER_SD_RAWBOOT_MASK, XLoader_Sha3Kat, XLOADER_SSIT_MONOLITIC.
Referenced by XLoader_InitPdiInstanceForExtractMHAndOptData, XLoader_LoadAsuImage, XLoader_LoadLpdAndPsmElf, XLoader_LoadPdi, XLoader_RestartImage.
int XLoader_LoadPdi(XilPdi *PdiPtr, PdiSrc_t PdiSrc, u64 PdiAddr)
This function provides loading PDI.
PdiPtr is the instance pointer that points to PDI details PdiSrc is source of PDI. It can be in Boot Device or DDR. PdiAddr is the address at PDI is located in the PDI source XST_SUCCESS on success and error code on failure
References XLoader_PdiInit.
XLoader_ImageInfo* XLoader_GetImageInfoEntry(u32 ImgID)
This function returns the ImageInfoEntry by checking if an entry exists for that particular ImgId in the ImgInfoTbl.
ImgID of the the entry that has to be stored Address of ImageInfo Entry in the table
References XLoader_ImageInfoTbl::Count, XLoader_ImageInfo::ImgID, XLoader_GetImageInfoTbl, XLOADER_IMAGE_INFO_TBL_MAX_NUM, XLOADER_INVALID_IMG_ID.
Referenced by XLoader_StoreImageInfo.
int XLoader_StoreImageInfo(const XLoader_ImageInfo *ImageInfo)
This function stores the ImageInfo to Image Info Table.
ImageInfo is a Pointer to ImageInfo that has to be written. XST_SUCCESS on success.XLOADER_ERR_INVALIDATE_CHILD_IMG when invalidating child image entry.XLOADER_ERR_IMAGE_INFO_TBL_OVERFLOW when image info table overflows.XPLMI_ERR_MEMCPY_IMAGE_INFO if failed to copy image info to memory.
References XLoader_ImageInfoTbl::Count, XLoader_ImageInfo::ImgID, XLoader_ImageInfoTbl::IsBufferFull, XLoader_ImageInfo::UID, XLoader_GetImageInfoEntry, XLoader_GetImageInfoTbl, XLOADER_INVALID_IMG_ID, XLOADER_INVALID_UID.
Referenced by XLoader_LoadImage.
int XLoader_LoadImageInfoTbl(u64 DestAddr, u32 MaxSize, u32 *NumEntries)
This function loads the ImageInfo table to the given memory address.
DestAddr is the 64 bit Destination Address MaxSize is the max size of Buffer present at Destination Address NumEntries that are loaded from the Image Info Table XST_SUCCESS on success.XLOADER_ERR_INVALID_DEST_IMGINFOTBL_SIZE if destination buffer size is less than the current length of the image info table.XLOADER_ERR_IMAGE_INFO_TBL_FULL if image info table is full.
References XLoader_ImageInfoTbl::Count, XLoader_ImageInfoTbl::IsBufferFull, XLOADER_ERR_IMAGE_INFO_TBL_FULL, XLOADER_ERR_INVALID_DEST_IMGINFOTBL_SIZE, XLoader_GetImageInfoTbl.
int XLoader_LoadImage(XilPdi *PdiPtr)
This function is used load a image in PDI.
PDI can have multiple images present in it. This can be used to load a single image like PL, APU, RPU. This will load all the partitions that are present in that image. PdiPtr is Pdi instance pointer XST_SUCCESS on success.XLOADER_ERR_SEM_STOP_SCAN if unable to stop SEM scan.XLOADER_ERR_CONFIG_SUBSYSTEM if subsystem configuration fails.XLOADER_ERR_SEM_INIT if unable to start the SEM scan.
References XilPdi::DelayLoad, XilPdi::ImageNum, XilPdi::MetaHdr, XilPdi::PdiSrc, XilPdi::PdiType, XLOADER_INVALID_IMG_ID, XLoader_MeasureNLoad, XLOADER_PDI_SRC_JTAG, XLOADER_PDI_TYPE_FULL, XLoader_SetJtagTapToReset, XLoader_ShaInstance1Reset, XLoader_StoreImageInfo.
int XLoader_RestartImage(u32 ImageId, u32 *FuncID)
This function is used to restart the image in PDI.
This function will take ImageId as an input and based on the subsystem info available, it will read the image partitions, loads them and hand-off to the required CPUs as part of the image load. ImageId Id of the image present in PDI FuncID is verified with the FuncID present in PDI XST_SUCCESS on success and error code on failure
References XLoader_ImageStore::Count, XLoader_ImageStore::ImgList, XLoader_PdiInfo::PdiAddr, XilPdi::PdiSrc, XilBootPdiInfo::PdiSrc, XilPdi::PdiType, XLoader_GetBootPdiInfo, XLoader_GetPdiInstance, XLoader_GetPdiList, XLOADER_PDI_LOAD_COMPLETE, XLOADER_PDI_SRC_DDR, XLOADER_PDI_SRC_JTAG, XLOADER_PDI_SRC_SMAP, XLOADER_PDI_TYPE_FULL, XLoader_PdiInit, XLoader_StartImage.
int XLoader_IdCodeCheck(const XilPdi_ImgHdrTbl *ImgHdrTbl)
This function performs the checks of IDCODE and EXTENDED IDCODE.
It also supports bypass of subset of these checks. ImgHdrTbl pointer to the image header table. XST_SUCCESS on success.XLOADER_ERR_EXT_ID_SI if extended ID code is mismatched with device.XLOADER_ERR_IDCODE on ID code mismatch.XLOADER_ERR_EXT_IDCODE on extended ID code mismatch.
References XLOADER_ERR_EXT_ID_SI, XLOADER_ERR_EXT_IDCODE, XLOADER_ERR_IDCODE.
int XLoader_ReadImageStoreCfg(void)
This function is used to read the Image Store DDR Memory Addr.
XST_SUCCESS on success and error code on failure
References XLoader_ImageStore::ImgList, XLoader_PdiInfo::PdiAddr, XLoader_ImageStore::PdiImgStrAddr, XLoader_ImageStore::PdiImgStrSize, XLOADER_ERR_INVALID_IMAGE_STORE_ADDRESS, XLoader_GetPdiList, XLOADER_IMG_STORE_INVALID_ADDR, XLOADER_IMG_STORE_INVALID_SIZE.
int XLoader_IsPdiAddrLookup(u32 PdiId, u64 *PdiAddr)
This function is used to read the Address based-on PDI Id from Image Store.
PdiId Index of the PDI stored PdiAddr Pointer to the PDI address XST_SUCCESS on successXLOADER_ERR_PDI_LIST_EMPTY if PDI list is emptyXLOADER_ERR_PDI_ADDR_NOT_FOUND if PDI ID not found in list
References XLoader_ImageStore::Count, XLoader_ImageStore::ImgList, XLoader_PdiInfo::PdiAddr, XLoader_PdiInfo::PdiId, XLOADER_ERR_PDI_ADDR_NOT_FOUND, XLOADER_ERR_PDI_LIST_EMPTY, XLoader_GetPdiList.
void Xloader_SaveBootPdiInfo(XilPdi *BootPdiPtr)
This function is used to save the BootPDI info.
BootPdiPtr Pointer to the PDI instance
References XilPdi::DecKeySrc, XilBootPdiInfo::DecKeySrc, XilPdi::MetaHdr, XilBootPdiInfo::MetaHdrOfst, XilPdi::PdiSrc, XilBootPdiInfo::PdiSrc, XilPdi::PlmKatStatus, XilBootPdiInfo::PlmKatStatus, XLoader_GetBootPdiInfo.
XilPdi* XLoader_GetPdiInstance(void)
This function provides PdiInstance pointer.
Pointer to PdiInstance
Referenced by XLoader_LoadAsuImage, XLoader_LoadLpdAndPsmElf, XLoader_PdiInit, XLoader_RestartImage.
int XLoader_InitPdiInstanceForExtractMHAndOptData(XPlmi_Cmd *Cmd, XilPdi *PdiPtr, u64 SrcAddr, u64 DestAddr, u32 DestSize)
This function initializes PDI Instance pointer for extracting Metaheader and OptionalData.
Cmd Pointer to the command structure PdiPtr Pointer to PdiInstance SrcAddr Address of the PDI DestAddr Address of the destination buffer DestSize Size of the destination buffer XST_SUCCESS on successErrorCode on failure
References XLoader_DeviceOps::Copy, XLoader_DeviceOps::Init, XilPdi::IpiMask, XilPdi::MetaHdr, XilPdi::PdiType, XLoader_DeviceOps::Release, XLOADER_CMD_EXTRACT_METAHDR_PDISRC_MASK, XLOADER_ERR_INVALID_METAHEADER_DEST_ADDR, XLOADER_ERR_INVALID_METAHEADER_OFFSET, XLOADER_ERR_INVALID_METAHEADER_SRC_ADDR, XLOADER_ERR_INVALID_PDI_INPUT, XLOADER_GET_OPT_DATA_FLAG, XLOADER_PDI_SRC_DDR, XLOADER_PDI_SRC_IS, XLOADER_PDI_SRC_OSPI, XLoader_PdiInit.
int XLoader_ClearATFHandoffParams(XilPdi *PdiPtr)
This function clears ATF Handoff parameters in case of multi-partitions in APU subsystem.
PdiPtr Pointer to XilPdi instance XST_SUCCESS on successXST_FAILURE on failure
Referenced by XLoader_ProcessElf.
int XLoader_GetImageAndPrtnInfo(XilPdi *PdiPtr, u32 ImageId)
This function provides Image number and partition number of a given ImgId in the PDI instance.
PdiPtr Pdi instance pointer ImageId Image id of a subsystem - XST_SUCCESS on success XST_FAILURE on failure
References XilPdi::ImageNum, XilPdi::MetaHdr, XilPdi::PrtnNum.
Referenced by XLoader_LoadAsuImage, XLoader_LoadLpdAndPsmElf.