xloader_auth_enc.h
XLOADER_RSA_SIG_EXP_BYTE
< Macro definitions related to RSA PSS padding
XLOADER_RSA_EM_MSB_EXP_BYTE
XLOADER_I2OSP_INT_LIMIT
XLOADER_RSA_PSS_SALT_LEN
Salt length for RSA PSS padding.
XLOADER_RSA_PSS_PADDING1
XLOADER_RSA_PSS_BUFFER_LEN
XLOADER_PPDI_RED_KEY_CLR_MASK
< Masks are used to determine if KAT for the respective crypto hardware has already been run or not.
Red key clear mask
XLOADER_RSA_4096_KEY_SIZE
RSA 4096 key size.
Size of Primary Public Key(in bytes) in Authentication Certificate
XLOADER_SPK_SIG_SIZE
Size of SPK signature(in bytes) in Authentication Certificate.
XLOADER_BHDR_SIG_SIZE
Size of Bootheader signature(in bytes) in Authentication Certificate.
XLOADER_PARTITION_SIG_SIZE
Size of Partition signature(in bytes) in Authentication Certificate.
XLOADER_AUTH_HEADER_SIZE
Size of Authentication header(in bytes) in Authentication Certificate.
XLOADER_AUTH_CERT_USER_DATA
Size of User Data(in bytes) in Authentication Certificate.
XLOADER_OPTIMIZED_AUTH_CERT_MIN_SIZE
Minimum Size of Optimized Authentication Certificate(in bytes)
XLOADER_AC_AH_REVOKE_ID_MASK
Mask for Revocation ID.
XLOADER_ECDSA_P384_KEYSIZE
Key size(in bytes) for ECDSA P-384 curve.
XLOADER_ECDSA_P521_KEYSIZE
Key size(in bytes) for ECDSA P-521 curve.
XLOADER_ECDSA_MAX_KEYSIZE
ECDSA Max Key size(in bytes)
XLOADER_SECURE_HDR_SIZE
Secure Header Size(in bytes)
XLOADER_SECURE_GCM_TAG_SIZE
GCM Tag Size(in bytes)
XLOADER_SECURE_HDR_TOTAL_SIZE
Total size of Secure Header (in bytes)
XLOADER_128_BIT_ALIGNED_MASK
Mask to check if data is 128-bit aligned.
AES key source
XLOADER_EFUSE_KEY
eFUSE Key
XLOADER_EFUSE_BLK_KEY
eFUSE Black Key
Referenced by XLoader_GetKekSrc.
XLOADER_BBRAM_KEY
BBRAM Key.
XLOADER_BBRAM_BLK_KEY
BBRAM Black Key.
Referenced by XLoader_GetKekSrc.
XLOADER_BH_BLK_KEY
Boot Header Black Key.
Referenced by XLoader_GetKekSrc.
XLOADER_EFUSE_USR_KEY0
eFUSE User Key 0
XLOADER_EFUSE_USR_BLK_KEY0
eFUSE User key 0 Black
XLOADER_EFUSE_USR_KEY1
eFUSE User Key 1
XLOADER_EFUSE_USR_BLK_KEY1
eFUSE User key 1 Black
XLOADER_USR_KEY0
User Key 0.
XLOADER_USR_KEY1
User Key 1.
XLOADER_USR_KEY2
User Key 2.
XLOADER_USR_KEY3
User Key 3.
XLOADER_USR_KEY4
User Key 4.
XLOADER_USR_KEY5
User Key 5.
XLOADER_USR_KEY6
User Key 6.
XLOADER_USR_KEY7
User Key 7.
eFUSE related macro definitions Misc Ctrl register address
XLOADER_EFUSE_MISC_CTRL_PPK0_INVLD
PPK0 invalid value.
Referenced by XLoader_GetPpkInvalidMaskAndOffset.
XLOADER_EFUSE_MISC_CTRL_PPK1_INVLD
PPK1 invalid value.
Referenced by XLoader_GetPpkInvalidMaskAndOffset.
XLOADER_EFUSE_MISC_CTRL_PPK2_INVLD
PPK2 invalid value.
Referenced by XLoader_GetPpkInvalidMaskAndOffset.
XLOADER_EFUSE_PPK_HASH_LEN
PPK hash length stored in eFUSE.
XLOADER_EFUSE_MISC_CTRL_ALL_PPK_INVLD
All PPKs invalid value for PPK0-PPK2.
XLOADER_SECURE_IV_LEN
Secure IV length in words.
XLOADER_SECURE_IV_NUM_ROWS
No.
of eFUSE rows for Secure IV
XLOADER_EFUSE_IV_METAHDR_START_OFFSET
Metaheader IV start register address.
XLOADER_EFUSE_IV_METAHDR_END_OFFSET
Metaheader IV end register address.
XLOADER_EFUSE_IV_BLACK_OBFUS_START_OFFSET
Black IV start register address.
XLOADER_EFUSE_IV_BLACK_OBFUS_END_OFFSET
Black IV start register address.
XLOADER_EFUSE_REVOCATION_ID_0_OFFSET
Revocation ID 0 register address.
XLOADER_EFUSE_REVOCATION_ID_7_OFFSET
Revocation ID 7 register address.
XLOADER_EFUSE_SEC_MISC1_OFFSET
Security Misc1 register address.
Referenced by XLoader_AesKatTest.
XLOADER_EFUSE_SEC_DPA_DIS_MASK
DPA CM disabled mask.
Referenced by XLoader_AesKatTest.
XLOADER_EFUSE_DNA_START_OFFSET
DNA start register address.
XLOADER_EFUSE_DNA_NUM_ROWS
Number of eFUSE rows for DNA.
XLOADER_EFUSE_DNA_LEN_IN_BYTES
Size of DNA(in bytes)
XLOADER_AC_AH_DNA_MASK
Mask for DNA in Authentication Certificate.
XLOADER_REVOCATION_IDMAX
Maximum value of Revocation ID.
XLOADER_PUF_HD_EFUSE
Value of PUF HD stored in efuse.
KEK key decryption status
XLOADER_BBRAM_RED_KEY
Decrypted key stored in BBRAM.
Referenced by XLoader_GetKekSrc.
XLOADER_BHDR_RED_KEY
Decrypted key stored in Bootheader.
Referenced by XLoader_GetKekSrc.
XLOADER_EFUSE_RED_KEY
Decrypted key stored in eFUSE AES key.
Referenced by XLoader_GetKekSrc.
XLOADER_EFUSE_USR0_RED_KEY
Decrypted key stored in eFUSE User 0 key.
XLOADER_EFUSE_USR1_RED_KEY
Decrypted key stored in eFUSE User 1 key.
XLOADER_EFUSE_CACHE_SECURITY_CONTROL_OFFSET
Security Control register address.
Referenced by XLoader_AddDeviceStateChangeToScheduler.
XLOADER_PMC_TAP_AUTH_JTAG_DATA_OFFSET
Authenticated JTAG Data start register address.
XLOADER_AUTH_JTAG_IDWORD
Authenticated JTAG ID word.
XLOADER_PMC_TAP_DAP_CFG_OFFSET
DAP CFG register address.
XLOADER_PMC_TAP_INST_MASK_1_OFFSET
Instruction Mask 1 register address.
XLOADER_PMC_TAP_DAP_SECURITY_OFFSET
DAP security register address.
XLOADER_PMC_TAP_AUTH_JTAG_INT_STATUS_OFFSET
Authenticated JTAG interrupt status register address.
XLOADER_CRP_RST_DBG_OFFSET
CRP reset debug register address.
XLOADER_PMC_TAP_AUTH_JTAG_INT_STATUS_MASK
Mask for Authenticated JTAG interrupt status.
XLOADER_AUTH_JTAG_DIS_MASK
Mask for disabling Authenticated JTAG.
XLOADER_AUTH_JTAG_LOCK_DIS_MASK
Mask for disabling Authenticated JTAG after secure lockdown.
XLOADER_AUTH_JTAG_DATA_LEN_IN_WORDS
Authenticated JTAG data length(in words)
XLOADER_AUTH_JTAG_DATA_AH_LENGTH
Length of Authentication Header in Authenticated JTAG message.
XLOADER_AUTH_JTAG_MAX_ATTEMPTS
Maximum allowed attempts to authenticate JTAG message.
XLOADER_AUTH_JTAG_PADDING_SIZE
Authenticated JTAG padding size.
XLOADER_AUTH_JTAG_SHA_PADDING_SIZE
Authenticated SHA padding size.
XLOADER_ENABLE_AUTH_JTAG_SIGNATURE_SIZE
Authenticated JTAG signature size.
XLOADER_CONFIG_DAP_STATE_SECURE_DBG
DAP State enable secure Debug.
XLOADER_CONFIG_DAP_STATE_NONSECURE_DBG
DAP State enable non-secure Debug.
Referenced by XLoader_ConfigureJtagState.
XLOADER_CONFIG_DAP_STATE_ALL_DBG
DAP State enable all Debug modes.
XLOADER_DAP_SECURITY_GATE_DISABLE_MASK
MAsk to disable DAP security gate.
XLOADER_DAP_CFG_SPNIDEN_MASK
Mask to enable secure non-invasive debug.
XLOADER_DAP_CFG_SPIDEN_MASK
Mask to enable secure invasive debug.
XLOADER_DAP_CFG_NIDEN_MASK
Mask to enable non-secure non-invasive debug.
XLOADER_DAP_CFG_DBGEN_MASK
Mask to enable non-secure invasive debug.
XLOADER_DAP_CFG_ENABLE_ALL_DBG_MASK
Mask to enable all types of debug.
Referenced by XLoader_EnableJtag.
XLOADER_CRP_RST_DBG_ENABLE_MASK
Mask to enable debug for CRP_RST.
XLOADER_PMC_TAP_INST_DISABLE_MASK_0
Value to unmask instructions for Instruction mask 0 register.
XLOADER_PMC_TAP_INST_DISABLE_MASK_1
Value to unmask instructions for Instruction mask 1 register.
XLOADER_CRP_RST_DBG_DPC_MASK
Value to reset DPC within the PMC only.
XLOADER_CRP_RST_DBG_RESET_MASK
Value to reset all debug in the LPD/FPD.
XLOADER_DAP_TIMEOUT_DISABLED
Timeout disabled for DAP.
XLOADER_PDI_DPACM_ENABLED
DPA counter measures are enabled in PDI.
XLOADER_PDI_DPACM_DISABLED
DPA counter measures are disabled in PDI.
Misc Control register address
EFUSE_CACHE_MISC_CTRL_CRYPTO_KAT_EN_MASK
Mask to enable running of KAT for Crypto engines.
XLOADER_KAT_DONE
Value to indicate that KAT is done.
XLOADER_WORD_IN_BITS
Word length in bits.
XLOADER_WORD_IN_BITS_SHIFT
Value to shift word.
XLOADER_WORD_IN_BITS_MASK
Value to mask word.
XLOADER_NOLOAD_VAL
To indicate no load.
XLOADER_SPK_SIZE
Size of Secondary Public Key(in bytes) in Authentication Certificate.
XLOADER_PPK_SIZE
Size of Primary Public Key(in bytes) in Authentication Certificate.
XLOADER_AUTH_CERT_MIN_SIZE
Minimum Size of Authentication Certificate(in bytes)
XLOADER_AC_AH_PUB_STRENGTH_MASK
Mask for Public Strength in Authentication Certificate.
XLOADER_AC_AH_PUB_STRENGTH_SHIFT
Shift for Public Strength in Authentication Certificate.
XLOADER_PUB_STRENGTH_ECDSA_P384
Value of ECDSA P-384 as Public Strength in Authentication Certificate.
XLOADER_PUB_STRENGTH_RSA_4096
Value of RSA 4096 as Public Strength in Authentication Certificate.
XLOADER_PUB_STRENGTH_ECDSA_P521
Value of ECDSA P-521 as Public Strength in Authentication Certificate.
XLOADER_MAX_TOTAL_KEY_SIZE
Maximum size of authentication key.
XLOADER_HB_PPDI_PRTN_HASH_IDX_OFFSET
Partition Hash index offset in HashBlock for partial PDI.
XLOADER_PUF_HD_BHDR
Value of PUF HD stored in bootheader.
XLoader_AuthType
0x0 - ECDSA
XLoader_PpkSel
0 - PPK 0
typedef struct XLoader_SecureParams XLoader_SecureParams
Structure to hold secure parameters.
static int XLoader_UpdateMinorErr(XLoader_SecErrCodes Minor1, int Minor2)
This function updates security related minor error codes for Xilloader.
Minor1 To specify the cause of failure of security operation Minor2 Libraries / Drivers error code as defined in respective modules If MSB of Minor1 is set then error in clearing of security buffer (16th bit) If bit next to MSB is set then security buffer was successfully cleared (15th bit) For eg: 0x02 : Incorrect authentication type selected 0x42 : Incorrect authentication type selected and buffer was successfully cleared 0x82 : Incorrect authentication type selected and error in clearing buffer
static u32 XLoader_GetAuthPubAlgo(const u32 *AuthHdrPtr)
This function returns the public algorithm used for authentication.
AuthHdrPtr is a pointer to the Authentication header of the AC. - XLOADER_PUB_STRENGTH_ECDSA_P384 XLOADER_PUB_STRENGTH_RSA_4096XLOADER_PUB_STRENGTH_ECDSA_P521
int XLoader_ReadAndVerifySecureHdrs(XLoader_SecureParams *SecurePtr, XilPdi_MetaHdr *MetaHdr)
This function authenticates and/or decrypts the image headers and partition headers and copies the contents to the corresponding structures.
SecurePtr Pointer to the XLoader_SecureParams instance. MetaHdr Pointer to the Meta header table. XST_SUCCESS on success.XLOADER_ERR_HDR_GET_DMA if acquiring DMA fails.XLOADER_ERR_HDR_AES_OP_FAIL if AES initialization fails.XLOADER_ERR_METAHDR_LEN_OVERFLOW on meta header length overflow.XLOADER_ERR_HDR_COPY_FAIL on IH/PH header copy fail.XLOADER_ERR_SEC_IH_READ_FAIL on image header read fail.XLOADER_ERR_SEC_IH_VERIFY_FAIL on image header verify fail.XLOADER_ERR_HDR_NOT_SECURE if neither authentication nor encryption is enabled for IH/PH.XLOADER_ERR_SEC_PH_READ_FAIL if partition header read fails.XLOADER_ERR_SEC_PH_VERIFY_FAIL if partition header verification fails.
int XLoader_SecureValidations(const XLoader_SecureParams *SecurePtr)
This function checks if authentication/encryption is compulsory.
SecurePtr is pointer to the XLoader_SecureParams instance. XST_SUCCESS on success.XLOADER_ERR_GLITCH_DETECTED if glitch is detected.XLOADER_ERR_AUTH_EN_PPK_HASH_ZERO if PPK not programmed and authentication is enabledXLOADER_ERR_HWROT_EFUSE_AUTH_COMPULSORY if PPK Programmed but eFuse authentication is disabled.XLOADER_ERR_ENCONLY_ENC_COMPULSORY if encryption is disabled.XLOADER_ERR_METAHDR_KEYSRC_MISMATCH if metaheader Key Source does not match PLM Key Source.
int XLoader_SecureAuthInit(XLoader_SecureParams *SecurePtr, const XilPdi_PrtnHdr *PrtnHdr)
This function initializes authentication parameters of XLoader_SecureParams's instance.
SecurePtr is pointer to the XLoader_SecureParams instance. PrtnHdr is pointer to XilPdi_PrtnHdr instance that has to be processed. XST_SUCCESS on success.XLOADER_ERR_INIT_AC_COPY_FAIL if failed to copy authentication certificate from flash device.
Referenced by XLoader_SecureInit.
int XLoader_SecureEncInit(XLoader_SecureParams *SecurePtr, const XilPdi_PrtnHdr *PrtnHdr)
This function initializes encryption parameters of XLoader_SecureParams's instance.
SecurePtr is pointer to the XLoader_SecureParams instance. PrtnHdr is pointer to XilPdi_PrtnHdr instance that has to be processed. XST_SUCCESS on success.XLOADER_ERR_INIT_CHECKSUM_INVLD_WITH_AUTHDEC if both checksum and authentication or encryption are enabled.XLOADER_ERR_PRTN_DECRYPT_NOT_ALLOWED if Partition is not allowed to be encrypted if State of boot is non secure.XLOADER_ERR_GLITCH_DETECTED if glitch is detected.XLOADER_ERR_PRTN_ENC_ONLY_KEYSRC on invalid key source when only encryption is enabled.
Referenced by XLoader_SecureInit.
int XLoader_AuthEncClear(void)
This function is called to clear secure critical data related to authentication and encryption in case of exceptions.
The function also places AES, ECDSA_RSA in reset. XST_SUCCESS on success.XST_FAILURE on failure.
Referenced by XLoader_SecureClear.
int XLoader_ProcessAuthEncPrtn(XLoader_SecureParams *SecurePtr, u64 DestAddr, u32 BlockSize, u8 Last)
This function performs authentication and decryption of the partition.
SecurePtr is pointer to the XLoader_SecureParams instance DestAddr is the address to which data is copied BlockSize is size of the data block to be processed which doesn't include padding lengths and hash Last notifies if the block to be processed is last or not XST_SUCCESS on success.XLOADER_ERR_DMA_TRANSFER if DMA transfer fails while copying.XLOADER_ERR_PRTN_DECRYPT_FAIL if partition decryption fails.XLOADER_SEC_BUF_CLEAR_SUCCESS if successfully cleared buffer.XLOADER_SEC_BUF_CLEAR_ERR if failed to clear buffer.
int XLoader_RsaPssSignVerify(u8 *MsgHash, XSecure_Rsa *RsaInstPtr, u8 *Signature, u32 KeySize)
This function encrypts the RSA signature provided and performs required PSS operations to extract salt and calculates M prime hash and compares with hash obtained from EM.
MsgHash of the data to be authenticated. RsaInstPtr is pointer to the XSecure_Rsa instance. Signature is pointer to RSA signature for data to be authenticated. KeySize is size of RSA key in bytes. XST_SUCCESS on success.XLOADER_SEC_MEMSET_ERROR and XLOADER_SEC_RSA_MEMSET_SHA3_ARRAY_FAIL if failed to create memory for RSA SHA3.XLOADER_SEC_MEMSET_ERROR and XLOADER_SEC_RSA_MEMSET_VARSCOM_FAIL if failed to create memory for RSA varscom.XLOADER_SEC_RSA_PSS_ENC_BC_VALUE_NOT_MATCHED if failed to match with RSA ENC 0xbc value.XLOADER_SEC_MASKED_DB_MSB_ERROR if error in RSA EM MSB.XLOADER_SEC_RSA_PSS_SIGN_VERIFY_FAIL if failed to verify RSA PSS signature.XLOADER_SEC_EFUSE_DB_PATTERN_MISMATCH_ERROR if failed to verify database in efuse.XLOADER_SEC_RSA_PSS_HASH_COMPARE_FAILURE if RSA PSS hash is not matched.XLOADER_SEC_BUF_CLEAR_ERR if failed to clear buffer.
int XLoader_IsPpkValid(const u8 *PpkHash)
This function validates PPK hash against eFUSE stored hash.
It iterates through all PPKs and checks if the provided hash matches any valid (non-revoked) PPK. PpkHash Pointer to the PPK hash to be verified. XST_SUCCESS on success.XLOADER_SEC_INVALID_PPK_CHOICE_ERR if invalid PPK selection.XLOADER_SEC_PPK_HASH_COMPARE_FAIL if PPK hash comparison failed.XLOADER_SEC_PPK_HASH_ALLZERO_INVLD if PPK hash is all zeros.XLOADER_SEC_ALL_PPK_REVOKED_ERR if all PPKs are revoked.XLOADER_SEC_SEL_PPK_REVOKED_ERR if selected PPK is revoked.
References XLoader_GetPpkInvalidMaskAndOffset, XLoader_ValidatePpkHash.
int XLoader_ClearAesKey(u32 *DecKeySrc)
This function clears the AES keys when RedKeyClear is set in PMC RAM.
DecKeySrc is pointer to the Decrypt Key source XST_SUCCESS on success.XLOADER_SEC_KEY_CLEAR_FAILED_ERROR if AES key clear fails.
References XLOADER_SEC_KEY_CLEAR_FAILED_ERROR.
int XLoader_IsPpkRevoked(u32 PpkInvldMask)
This function checks if the selected PPK is revoked by reading the PPK invalid bits from eFUSE.
PpkInvldMask is the PPK invalid bit mask to check in eFUSE. XST_SUCCESS if PPK is not revoked.XLOADER_SEC_SEL_PPK_REVOKED_ERR if PPK is revoked (invalid bit set).XLOADER_SEC_ALL_PPK_REVOKED_ERR if all PPKs are revoked.
int XLoader_ValidatePpkHash(const u8 *PpkHash, u32 PpkOffset)
This function compares the provided PPK hash with the hash stored in eFUSE and validates it is not all zeros.
PpkHash is pointer to the PPK hash to be verified. PpkOffset is PPK eFUSE offset. XST_SUCCESS on success.XLOADER_SEC_PPK_HASH_COMPARE_FAIL if hash comparison fails.XLOADER_SEC_PPK_HASH_ALLZERO_INVLD if PPK hash is all zeros.
Referenced by XLoader_IsPpkValid.
int XLoader_GetPpkInvalidMaskAndOffset(XLoader_PpkSel PpkSelect, u32 *InvalidMask, u32 *PpkOffset)
This function calculates the invalid mask and PPK offset based on the selected PPK.
PpkSelect is PPK selection of eFUSE. InvalidMask is pointer to store the invalid mask for the selected PPK. PpkOffset is pointer to store the PPK eFUSE offset. XST_SUCCESS on success.XLOADER_SEC_INVALID_PPK_CHOICE_ERR if invalid PPK selection.
References XLOADER_PPK_SEL_0, XLOADER_EFUSE_MISC_CTRL_PPK0_INVLD, XLOADER_EFUSE_PPK0_START_OFFSET, XLOADER_PPK_SEL_1, XLOADER_EFUSE_MISC_CTRL_PPK1_INVLD, XLOADER_EFUSE_PPK1_START_OFFSET, XLOADER_PPK_SEL_2, XLOADER_EFUSE_MISC_CTRL_PPK2_INVLD, XLOADER_EFUSE_PPK2_START_OFFSET, XLOADER_EFUSE_MISC_CTRL_PPK3_INVLD, XLOADER_EFUSE_MISC_CTRL_PPK4_INVLD, XLOADER_EFUSE_MISC_CTRL_PPK5_INVLD, XLOADER_EFUSE_MISC_CTRL_PPK6_INVLD, XLOADER_EFUSE_MISC_CTRL_PPK7_INVLD, XLOADER_EFUSE_MISC_CTRL_PPK8_INVLD.
Referenced by XLoader_IsPpkValid.
int XLoader_CheckSecureStateAuth(volatile u32 *AHWRoT)
This function checks Secure State for Authentication.
AHWRoT - Buffer to store Secure state for authentication XST_SUCCESS on success. XLOADER_ERR_GLITCH_DETECTED if glitch is detected. AHWRoT - Buffer to store Secure state for authentication. XST_SUCCESS on success.XLOADER_ERR_HWROT_BH_AUTH_NOT_ALLOWED if PPK is programmed and boot header authentication is enabled. AHWRoT Buffer to store Secure state for authentication. XST_SUCCESS on success.XLOADER_ERR_GLITCH_DETECTED if glitch is detected. AHWRoT - Buffer to store Secure state for authentication XST_SUCCESS on success.XLOADER_ERR_HWROT_BH_AUTH_NOT_ALLOWED if PPK is programmed and boot header authentication is enabled. AHWRoT - Buffer to store Secure state for authentication XST_SUCCESS on success. XLOADER_ERR_GLITCH_DETECTED if glitch is detected. AHWRoT - Buffer to store Secure state for authentication. XST_SUCCESS on success.XLOADER_ERR_HWROT_BH_AUTH_NOT_ALLOWED if PPK is programmed and boot header authentication is enabled. AHWRoT Buffer to store Secure state for authentication. XST_SUCCESS on success.XLOADER_ERR_GLITCH_DETECTED if glitch is detected.
References XLoader_CheckNonZeroPpk.
Referenced by XLoader_SetSecureState.
int XLoader_CheckSecureState(u32 RegVal, u32 Var, u32 ExpectedValue)
This function checks if the secure state of boot matches the expected value or not.
RegVal - Value of secure state stored in register Var - Value of secure state stored in variable ExpectedValue - Expected value of secure state XST_SUCCESS on success.XST_FAILURE if RegVal, Var, or ExpectedValue do not all match.
Referenced by XLoader_SecureInit.
int XLoader_ImgHdrTblAuth(XLoader_SecureParams *SecurePtr)
This function authenticates the image header table.
SecurePtr is pointer to the XLoader_SecureParams instance XST_SUCCESS on success.XLOADER_ERR_IHT_GET_DMA if acquiring DMA is failed.XLOADER_ERR_IHT_COPY_FAIL if IHT copy fails.XLOADER_ERR_IHT_HASH_CALC_FAIL if IHT hash calculation fails.XLOADER_ERR_IHT_AUTH_FAIL if IHT authentication fails.
int XLoader_DataAuth(XLoader_SecureParams *SecurePtr, u8 *Hash, u8 *Signature)
This function authenticates the data with SPK.
SecurePtr is pointer to the XLoader_SecureParams instance. Hash is a Pointer to the expected hash buffer. Signature pointer points to the signature buffer. XST_SUCCESS on success.XLOADER_SEC_GLITCH_DETECTED_ERROR if glitch is detected.
int XLoader_VerifySignature(const XLoader_SecureParams *SecurePtr, u8 *Hash, XLoader_AuthKey *AuthKey, u8 *Signature)
This function verifies the signature (RSA/ECDSA) using the provided key and compares the result with the expected hash.
SecurePtr is pointer to the XLoader_SecureParams instance. Hash is pointer to the expected hash to be verified AuthKey is pointer to the RSA/ECDSA public key to be used for verification Signature is pointer to the signature to be verified XST_SUCCESS on successful signature verification.XLOADER_SEC_INVALID_AUTH on invalid authentication type.XLOADER_ERR_RSA_NOT_ENABLED if RSA is excluded from build.XLOADER_ERR_ECDSA_NOT_ENABLED if ECDSA is excluded from build.XLOADER_SEC_CURVE_NOT_SUPPORTED if P-521 curve is not supported.
References XLoader_SecureParams::AuthJtagMessagePtr, XLoader_AuthJtagMessage::AuthHdr.
int XLoader_PpkVerify(const XLoader_SecureParams *SecurePtr, const u32 PpkSize)
This function verifies PPK.
SecurePtr is pointer to the XLoader_SecureParams instance. PpkSize is Size of the PPK to be verified XST_SUCCESS on success.XLOADER_SEC_ALL_PPK_REVOKED_ERR if all PPKs are revoked.XLOADER_SEC_PPK_HASH_CALCULATION_FAIL if PPK hash calculation failsXLOADER_SEC_ALL_PPK_INVALID_ERR if all PPKs are invalid.XLOADER_SEC_BUF_CLEAR_ERR if failed to clear buffer.
int XLoader_VerifyRevokeId(u32 RevokeId)
This function validates SPK by verifying if the given SPK ID has been revoked or not.
RevokeId is ID of the SPK to be verified for revocation XST_SUCCESS on success.XLOADER_SEC_REVOCATION_ID_OUTOFRANGE_ERR if revocation ID is out of range.XLOADER_SEC_ID_REVOKED if revocation ID range not verified.
Referenced by XLoader_SecureInit.
int XLoader_AuthKat(XLoader_SecureParams *SecurePtr)
This function runs RSA or Ecdsa KAT based on pdi.
SecurePtr is pointer to the XLoader_SecureParams instance XST_SUCCESS on success.XLOADER_SEC_INVALID_AUTH on invalid authentication type.XLOADER_ERR_RSA_NOT_ENABLED if RSA is not enabled.XLOADER_ERR_ECDSA_NOT_ENABLED if ECDSA is not enabled.
References XLoader_SecureParams::AuthJtagMessagePtr, XLoader_AuthJtagMessage::AuthHdr.