canps
XCANPS_MODE_CONFIG
Configuration mode.
Referenced by CanPsPolledExample, XCanPs_EnterMode, XCanPs_GetMode, XCanPs_SelfTest, XCanPs_SetBaudRatePrescaler, XCanPs_SetBitTiming, XCanPs_SetRxIntrWatermark, XCanPs_SetTxIntrWatermark.
XCANPS_MODE_NORMAL
Normal mode.
Referenced by XCanPs_EnterMode, XCanPs_GetMode.
XCANPS_MODE_LOOPBACK
Loop Back mode.
Referenced by CanPsIntrExample, CanPsPolledExample, CanPsWatermarkIntrExample, XCanPs_EnterMode, XCanPs_GetMode, XCanPs_SelfTest.
XCANPS_MODE_SLEEP
Sleep mode.
Referenced by XCanPs_EnterMode, XCanPs_GetMode.
XCANPS_MODE_SNOOP
Snoop mode.
Referenced by XCanPs_EnterMode, XCanPs_GetMode.
XCANPS_HANDLER_SEND
Handler type for frame sending interrupt.
Referenced by CanPsIntrExample, CanPsWatermarkIntrExample, XCanPs_SetHandler.
XCANPS_HANDLER_RECV
Handler type for frame reception interrupt.
Referenced by CanPsIntrExample, CanPsWatermarkIntrExample, XCanPs_SetHandler.
XCANPS_HANDLER_ERROR
Handler type for error interrupt.
Referenced by CanPsIntrExample, CanPsWatermarkIntrExample, XCanPs_SetHandler.
XCANPS_HANDLER_EVENT
Handler type for all other interrupts.
Referenced by CanPsIntrExample, CanPsWatermarkIntrExample, XCanPs_SetHandler.
XCANPS_SRR_OFFSET
Software Reset Register.
Referenced by XCanPs_EnterMode, XCanPs_Reset, XCanPs_ResetHw.
XCANPS_MSR_OFFSET
Mode Select Register.
Referenced by XCanPs_EnterMode.
XCANPS_BRPR_OFFSET
Baud Rate Prescaler.
Referenced by XCanPs_GetBaudRatePrescaler, XCanPs_SetBaudRatePrescaler.
XCANPS_BTR_OFFSET
Bit Timing Register.
Referenced by XCanPs_GetBitTiming, XCanPs_SetBitTiming.
XCANPS_ECR_OFFSET
Error Counter Register.
Referenced by XCanPs_GetBusErrorCounter.
XCANPS_ESR_OFFSET
Error Status Register.
Referenced by XCanPs_ClearBusErrorStatus, XCanPs_GetBusErrorStatus.
XCANPS_SR_OFFSET
Status Register.
Referenced by XCanPs_GetStatus.
XCANPS_ISR_OFFSET
Interrupt Status Register.
Referenced by XCanPs_IntrGetStatus, XCanPs_SelfTest.
XCANPS_IER_OFFSET
Interrupt Enable Register.
Referenced by XCanPs_IntrDisable, XCanPs_IntrEnable, XCanPs_IntrGetEnabled.
XCANPS_ICR_OFFSET
Interrupt Clear Register.
Referenced by XCanPs_IntrClear.
XCANPS_TCR_OFFSET
Timestamp Control Register.
XCANPS_WIR_OFFSET
Watermark Interrupt Reg.
Referenced by XCanPs_GetRxIntrWatermark, XCanPs_GetTxIntrWatermark, XCanPs_SetRxIntrWatermark, XCanPs_SetTxIntrWatermark.
XCANPS_TXFIFO_ID_OFFSET
TX FIFO ID.
Referenced by XCanPs_Send.
XCANPS_TXFIFO_DLC_OFFSET
TX FIFO DLC.
Referenced by XCanPs_Send.
XCANPS_TXFIFO_DW1_OFFSET
TX FIFO Data Word 1.
Referenced by XCanPs_Send.
XCANPS_TXFIFO_DW2_OFFSET
TX FIFO Data Word 2.
Referenced by XCanPs_Send.
XCANPS_TXHPB_ID_OFFSET
TX High Priority Buffer ID.
Referenced by XCanPs_SendHighPriority.
XCANPS_TXHPB_DLC_OFFSET
TX High Priority Buffer DLC.
Referenced by XCanPs_SendHighPriority.
XCANPS_TXHPB_DW1_OFFSET
TX High Priority Buf Data 1.
Referenced by XCanPs_SendHighPriority.
XCANPS_TXHPB_DW2_OFFSET
TX High Priority Buf Data Word 2.
Referenced by XCanPs_SendHighPriority.
XCANPS_RXFIFO_ID_OFFSET
RX FIFO ID.
Referenced by XCanPs_Recv.
XCANPS_RXFIFO_DLC_OFFSET
RX FIFO DLC.
Referenced by XCanPs_Recv.
XCANPS_RXFIFO_DW1_OFFSET
RX FIFO Data Word 1.
Referenced by XCanPs_Recv.
XCANPS_RXFIFO_DW2_OFFSET
RX FIFO Data Word 2.
Referenced by XCanPs_Recv.
XCANPS_AFR_OFFSET
Acceptance Filter Register.
Referenced by XCanPs_AcceptFilterDisable, XCanPs_AcceptFilterEnable, XCanPs_AcceptFilterGetEnabled.
XCANPS_AFMR1_OFFSET
Acceptance Filter Mask 1.
Referenced by XCanPs_AcceptFilterGet, XCanPs_AcceptFilterSet.
XCANPS_AFIR1_OFFSET
Acceptance Filter ID 1.
Referenced by XCanPs_AcceptFilterGet, XCanPs_AcceptFilterSet.
XCANPS_AFMR2_OFFSET
Acceptance Filter Mask 2.
Referenced by XCanPs_AcceptFilterGet, XCanPs_AcceptFilterSet.
XCANPS_AFIR2_OFFSET
Acceptance Filter ID 2.
Referenced by XCanPs_AcceptFilterGet, XCanPs_AcceptFilterSet.
XCANPS_AFMR3_OFFSET
Acceptance Filter Mask 3.
Referenced by XCanPs_AcceptFilterGet, XCanPs_AcceptFilterSet.
XCANPS_AFIR3_OFFSET
Acceptance Filter ID 3.
Referenced by XCanPs_AcceptFilterGet, XCanPs_AcceptFilterSet.
XCANPS_AFMR4_OFFSET
Acceptance Filter Mask 4.
Referenced by XCanPs_AcceptFilterGet, XCanPs_AcceptFilterSet.
XCANPS_AFIR4_OFFSET
Acceptance Filter ID 4.
Referenced by XCanPs_AcceptFilterGet, XCanPs_AcceptFilterSet.
XCANPS_SRR_CEN_MASK
Can Enable.
Referenced by XCanPs_EnterMode.
XCANPS_SRR_SRST_MASK
Reset.
Referenced by XCanPs_Reset, XCanPs_ResetHw.
XCANPS_MSR_SNOOP_MASK
Snoop Mode Select.
Referenced by XCanPs_EnterMode.
XCANPS_MSR_LBACK_MASK
Loop Back Mode Select.
Referenced by XCanPs_EnterMode.
XCANPS_MSR_SLEEP_MASK
Sleep Mode Select.
Referenced by XCanPs_EnterMode.
XCANPS_BRPR_BRP_MASK
Baud Rate Prescaler.
XCANPS_BTR_SJW_MASK
Synchronization Jump Width.
Referenced by XCanPs_GetBitTiming, XCanPs_SetBitTiming.
XCANPS_BTR_SJW_SHIFT
Shift Value for SJW.
Referenced by XCanPs_GetBitTiming, XCanPs_SetBitTiming.
XCANPS_BTR_TS2_MASK
Time Segment 2.
Referenced by XCanPs_GetBitTiming, XCanPs_SetBitTiming.
XCANPS_BTR_TS2_SHIFT
Shift Value for TS2.
Referenced by XCanPs_GetBitTiming, XCanPs_SetBitTiming.
XCANPS_BTR_TS1_MASK
Time Segment 1.
Referenced by XCanPs_GetBitTiming, XCanPs_SetBitTiming.
XCANPS_ECR_REC_MASK
Receive Error Counter.
Referenced by XCanPs_GetBusErrorCounter.
XCANPS_ECR_REC_SHIFT
Shift Value for REC.
Referenced by XCanPs_GetBusErrorCounter.
XCANPS_ECR_TEC_MASK
Transmit Error Counter.
Referenced by XCanPs_GetBusErrorCounter.
XCANPS_ESR_ACKER_MASK
ACK Error.
XCANPS_ESR_BERR_MASK
Bit Error.
XCANPS_ESR_STER_MASK
Stuff Error.
XCANPS_ESR_FMER_MASK
Form Error.
XCANPS_ESR_CRCER_MASK
CRC Error.
XCANPS_SR_SNOOP_MASK
Snoop Mask.
Referenced by XCanPs_GetMode.
XCANPS_SR_ACFBSY_MASK
Acceptance Filter busy.
XCANPS_SR_TXFLL_MASK
TX FIFO is full.
XCANPS_SR_TXBFLL_MASK
TX High Priority Buffer full.
XCANPS_SR_ESTAT_MASK
Error Status.
XCANPS_SR_ESTAT_SHIFT
Shift value for ESTAT.
XCANPS_SR_ERRWRN_MASK
Error Warning.
XCANPS_SR_BBSY_MASK
Bus Busy.
XCANPS_SR_BIDLE_MASK
Bus Idle.
XCANPS_SR_NORMAL_MASK
Normal Mode.
Referenced by XCanPs_GetMode.
XCANPS_SR_SLEEP_MASK
Sleep Mode.
Referenced by XCanPs_GetMode.
XCANPS_SR_LBACK_MASK
Loop Back Mode.
XCANPS_SR_CONFIG_MASK
Configuration Mode.
Referenced by XCanPs_GetMode.
XCANPS_IXR_TXFEMP_MASK
Tx Fifo Empty Interrupt.
XCANPS_IXR_TXFWMEMP_MASK
Tx Fifo Watermark Empty.
Referenced by CanPsWatermarkIntrExample, XCanPs_IntrHandler.
XCANPS_IXR_RXFWMFLL_MASK
Rx FIFO Watermark Full.
Referenced by XCanPs_IntrHandler.
XCANPS_IXR_WKUP_MASK
Wake up Interrupt.
Referenced by XCanPs_IntrHandler.
XCANPS_IXR_SLP_MASK
Sleep Interrupt.
Referenced by XCanPs_IntrHandler.
XCANPS_IXR_BSOFF_MASK
Bus Off Interrupt.
Referenced by XCanPs_IntrHandler.
XCANPS_IXR_ERROR_MASK
Error Interrupt.
Referenced by XCanPs_IntrHandler.
XCANPS_IXR_RXNEMP_MASK
RX FIFO Not Empty Interrupt.
Referenced by CanPsWatermarkIntrExample, XCanPs_IntrHandler, XCanPs_Recv, XCanPs_SelfTest.
XCANPS_IXR_RXOFLW_MASK
RX FIFO Overflow Interrupt.
Referenced by XCanPs_IntrHandler.
XCANPS_IXR_RXUFLW_MASK
RX FIFO Underflow Interrupt.
Referenced by XCanPs_IntrHandler.
XCANPS_IXR_RXOK_MASK
New Message Received Intr.
Referenced by CanPsWatermarkIntrExample.
XCANPS_IXR_TXBFLL_MASK
TX High Priority Buf Full.
Referenced by XCanPs_IntrHandler.
XCANPS_IXR_TXFLL_MASK
TX FIFO Full Interrupt.
Referenced by XCanPs_IntrHandler.
XCANPS_IXR_TXOK_MASK
TX Successful Interrupt.
Referenced by CanPsWatermarkIntrExample, XCanPs_IntrHandler.
XCANPS_IXR_ARBLST_MASK
Arbitration Lost Interrupt.
Referenced by XCanPs_IntrHandler.
XCANPS_IXR_ALL
Basic interrupts.
Referenced by CanPsIntrExample, CanPsWatermarkIntrExample.
XCANPS_TCR_CTS_MASK
Clear Timestamp counter mask.
XCANPS_WIR_FW_MASK
Rx Full Threshold mask.
Referenced by XCanPs_GetRxIntrWatermark, XCanPs_SetRxIntrWatermark, XCanPs_SetTxIntrWatermark.
XCANPS_WIR_EW_MASK
Tx Empty Threshold mask.
Referenced by XCanPs_GetTxIntrWatermark, XCanPs_SetRxIntrWatermark, XCanPs_SetTxIntrWatermark.
XCANPS_WIR_EW_SHIFT
Tx Empty Threshold shift.
Referenced by XCanPs_GetTxIntrWatermark, XCanPs_SetTxIntrWatermark.
XCANPS_IDR_ID1_MASK
Standard Messg Identifier.
XCANPS_IDR_ID1_SHIFT
Shift Value for ID1.
XCANPS_IDR_SRR_MASK
Substitute Remote TX Req.
XCANPS_IDR_SRR_SHIFT
Shift Value for SRR.
XCANPS_IDR_IDE_MASK
Identifier Extension.
XCANPS_IDR_IDE_SHIFT
Shift Value for IDE.
XCANPS_IDR_ID2_MASK
Extended Message Ident.
XCANPS_IDR_ID2_SHIFT
Shift Value for ID2.
XCANPS_IDR_RTR_MASK
Remote TX Request.
XCANPS_DLCR_DLC_MASK
Data Length Code.
XCANPS_DLCR_DLC_SHIFT
Shift Value for DLC.
XCANPS_DLCR_TIMESTAMP_MASK
Timestamp Mask (Rx only)
Referenced by XCanPs_SelfTest.
XCANPS_DW1R_DB0_MASK
Data Byte 0.
XCANPS_DW1R_DB0_SHIFT
Shift Value for Data Byte 0.
XCANPS_DW1R_DB1_MASK
Data Byte 1.
XCANPS_DW1R_DB1_SHIFT
Shift Value for Data Byte 1.
XCANPS_DW1R_DB2_MASK
Data Byte 2.
XCANPS_DW1R_DB2_SHIFT
Shift Value for Data Byte 2.
XCANPS_DW1R_DB3_MASK
Data Byte 3.
XCANPS_DW2R_DB4_MASK
Data Byte 4.
XCANPS_DW2R_DB4_SHIFT
Shift Value for Data Byte 4.
XCANPS_DW2R_DB5_MASK
Data Byte 5.
XCANPS_DW2R_DB5_SHIFT
Shift Value for Data Bbyet 5.
XCANPS_DW2R_DB6_MASK
Data Byte 6.
XCANPS_DW2R_DB6_SHIFT
Shift Value for Data Byte 6.
XCANPS_DW2R_DB7_MASK
Data Byte 7.
XCANPS_AFR_UAF4_MASK
Use Acceptance Filter No.4.
Referenced by XCanPs_AcceptFilterGet, XCanPs_AcceptFilterSet.
XCANPS_AFR_UAF3_MASK
Use Acceptance Filter No.3.
Referenced by XCanPs_AcceptFilterGet, XCanPs_AcceptFilterSet.
XCANPS_AFR_UAF2_MASK
Use Acceptance Filter No.2.
Referenced by XCanPs_AcceptFilterGet, XCanPs_AcceptFilterSet.
XCANPS_AFR_UAF1_MASK
Use Acceptance Filter No.1.
Referenced by XCanPs_AcceptFilterGet, XCanPs_AcceptFilterSet.
XCANPS_AFR_UAF_ALL_MASK
Mask for Acceptance Filers.
Referenced by XCanPs_AcceptFilterDisable, XCanPs_AcceptFilterEnable.
XCANPS_MAX_FRAME_SIZE
Maximum CAN frame length in bytes.
typedef void(* XCanPs_SendRecvHandler)(void *CallBackRef))(void *CallBackRef)
Callback type for frame sending and reception interrupts.
CallBackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked.
typedef void(* XCanPs_ErrorHandler)(void *CallBackRef, u32 ErrorMask))(void *CallBackRef, u32 ErrorMask)
Callback type for error interrupt.
CallBackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. ErrorMask is a bit mask indicating the cause of the error. Its value equals 'OR'ing one or more XCANPS_ESR_* values defined in xcanps_hw.h
typedef void(* XCanPs_EventHandler)(void *CallBackRef, u32 Mask))(void *CallBackRef, u32 Mask)
Callback type for all kinds of interrupts except sending frame interrupt, receiving frame interrupt, and error interrupt.
CallBackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. Mask is a bit mask indicating the pending interrupts. Its value equals 'OR'ing one or more XCANPS_IXR_* defined in xcanps_hw.h
XCanPs_Config XCanPs_ConfigTable[][]
This table contains configuration information for each CAN device in the system.
Referenced by XCanPs_LookupConfig.
XCanPs_Config XCanPs_ConfigTable[XPAR_XCANPS_NUM_INSTANCES][XPAR_XCANPS_NUM_INSTANCES]
This table contains configuration information for each CAN device in the system.
Referenced by XCanPs_LookupConfig.
u32 TxFrame[XCANPS_MAX_FRAME_SIZE_IN_WORDS][XCANPS_MAX_FRAME_SIZE_IN_WORDS]
Buffers to hold frames to send and receive.
These are declared as global so that they are not on the stack.Txframe buffer
u32 RxFrame[XCANPS_MAX_FRAME_SIZE_IN_WORDS][XCANPS_MAX_FRAME_SIZE_IN_WORDS]
Rxframe buffer.
static void StubHandler(void)
This routine is a stub for the asynchronous callbacks.
The stub is here in case the upper layer forgot to set the handler(s). On initialization, all handlers are set to this callback. It is considered an error for this handler to be invoked.
s32 XCanPs_CfgInitialize(XCanPs *InstancePtr, XCanPs_Config *ConfigPtr, UINTPTR EffectiveAddr)
This function initializes a XCanPs instance/driver.
The initialization entails: Initialize all members of the XCanPs structure.Reset the CAN device. The CAN device will enter Configuration Mode immediately after the reset is finished. InstancePtr is a pointer to the XCanPs instance. ConfigPtr points to the XCanPs device configuration structure. EffectiveAddr is the device base address in the virtual memory address space. If the address translation is not used then the physical address is passed. Unexpected errors may occur if the address mapping is changed after this function is invoked. XST_SUCCESS always. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::ErrorHandler, XCanPs::EventHandler, XCanPs::IsBusy, XCanPs::IsReady, XCanPs::RecvHandler, XCanPs::SendHandler, XCanPs_Reset.
Referenced by CanPsIntrExample, CanPsPolledExample, CanPsWatermarkIntrExample.
void XCanPs_Reset(XCanPs *InstancePtr)
This function resets the CAN device.
Calling this function resets the device immediately, and any pending transmission or reception is terminated at once. Both Object Layer and Transfer Layer are reset. This function does not reset the Physical Layer. All registers are reset to the default values, and no previous status will be restored. TX FIFO, RX FIFO and TX High Priority Buffer are also reset.When a reset is required due to an internal error, the driver notifies the upper layer software of this need through the error status code or interrupts. The upper layer software is responsible for calling this Reset function and then re-configuring the device.The CAN device will be in Configuration Mode immediately after this function returns. InstancePtr is a pointer to the XCanPs instance. None. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCANPS_SRR_OFFSET, XCANPS_SRR_SRST_MASK, XCanPs_WriteReg.
Referenced by XCanPs_CfgInitialize, XCanPs_SelfTest.
u8 XCanPs_GetMode(XCanPs *InstancePtr)
This routine returns the current operation mode of the CAN device.
InstancePtr is a pointer to the XCanPs instance. XCANPS_MODE_CONFIG if the device is in Configuration Mode.XCANPS_MODE_SLEEP if the device is in Sleep Mode.XCANPS_MODE_NORMAL if the device is in Normal Mode.XCANPS_MODE_LOOPBACK if the device is in Loop Back Mode.XCANPS_MODE_SNOOP if the device is in Snoop Mode. None.
References XCanPs::IsReady, XCanPs_GetStatus, XCANPS_MODE_CONFIG, XCANPS_MODE_LOOPBACK, XCANPS_MODE_NORMAL, XCANPS_MODE_SLEEP, XCANPS_MODE_SNOOP, XCANPS_SR_CONFIG_MASK, XCANPS_SR_NORMAL_MASK, XCANPS_SR_SLEEP_MASK, XCANPS_SR_SNOOP_MASK.
Referenced by CanPsIntrExample, CanPsPolledExample, CanPsWatermarkIntrExample, XCanPs_EnterMode, XCanPs_SelfTest, XCanPs_SetBaudRatePrescaler, XCanPs_SetBitTiming, XCanPs_SetRxIntrWatermark, XCanPs_SetTxIntrWatermark.
void XCanPs_EnterMode(XCanPs *InstancePtr, u8 OperationMode)
This function allows the CAN device to enter one of the following operation modes:
- Configuration Mode: Pass in parameter XCANPS_MODE_CONFIG - Sleep Mode: Pass in parameter XCANPS_MODE_SLEEP - Normal Mode: Pass in parameter XCANPS_MODE_NORMAL - Loop Back Mode: Pass in parameter XCANPS_MODE_LOOPBACK. - Snoop Mode: Pass in parameter XCANPS_MODE_SNOOP. Read the xcanps.h file and device specification for detailed description of each operation mode. InstancePtr is a pointer to the XCanPs instance. OperationMode specify which operation mode to enter. Valid value is any of XCANPS_MODE_* defined in xcanps.h. Multiple modes can not be entered at the same time. None. This function does NOT ensure CAN device enters the specified operation mode before it returns the control to the caller. The caller is responsible for checking current operation mode using XCanPs_GetMode().
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCanPs_GetMode, XCANPS_MODE_CONFIG, XCANPS_MODE_LOOPBACK, XCANPS_MODE_NORMAL, XCANPS_MODE_SLEEP, XCANPS_MODE_SNOOP, XCANPS_MSR_LBACK_MASK, XCANPS_MSR_OFFSET, XCANPS_MSR_SLEEP_MASK, XCANPS_MSR_SNOOP_MASK, XCANPS_SRR_CEN_MASK, XCANPS_SRR_OFFSET, XCanPs_WriteReg.
Referenced by CanPsIntrExample, CanPsPolledExample, CanPsWatermarkIntrExample, XCanPs_SelfTest.
u32 XCanPs_GetStatus(XCanPs *InstancePtr)
This function returns Status value from Status Register (SR).
Use the XCANPS_SR_* constants defined in xcanps_hw.h to interpret the returned value. InstancePtr is a pointer to the XCanPs instance. The 32-bit value read from Status Register. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCanPs_ReadReg, XCANPS_SR_OFFSET.
Referenced by XCanPs_GetMode.
void XCanPs_GetBusErrorCounter(XCanPs *InstancePtr, u8 *RxErrorCount, u8 *TxErrorCount)
This function reads Receive and Transmit error counters.
InstancePtr is a pointer to the XCanPs instance. RxErrorCount is a pointer to data in which the Receive Error counter value is returned. TxErrorCount is a pointer to data in which the Transmit Error counter value is returned. None. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCANPS_ECR_OFFSET, XCANPS_ECR_REC_MASK, XCANPS_ECR_REC_SHIFT, XCANPS_ECR_TEC_MASK, XCanPs_ReadReg.
u32 XCanPs_GetBusErrorStatus(XCanPs *InstancePtr)
This function reads Error Status value from Error Status Register (ESR).
Use the XCANPS_ESR_* constants defined in xcanps_hw.h to interpret the returned value. InstancePtr is a pointer to the XCanPs instance. The 32-bit value read from Error Status Register. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCANPS_ESR_OFFSET, XCanPs_ReadReg.
Referenced by XCanPs_IntrHandler.
void XCanPs_ClearBusErrorStatus(XCanPs *InstancePtr, u32 Mask)
This function clears Error Status bit(s) previously set in Error Status Register (ESR).
Use the XCANPS_ESR_* constants defined in xcanps_hw.h to create the value to pass in. If a bit was cleared in Error Status Register before this function is called, it will not be modified. InstancePtr is a pointer to the XCanPs instance. Mask is he 32-bit mask used to clear bits in Error Status Register. Multiple XCANPS_ESR_* values can be 'OR'ed to clear multiple bits. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCANPS_ESR_OFFSET, XCanPs_WriteReg.
Referenced by XCanPs_IntrHandler.
s32 XCanPs_Send(XCanPs *InstancePtr, u32 *FramePtr)
This function sends a CAN Frame.
If the TX FIFO is not full then the given frame is written into the the TX FIFO otherwise, it returns an error code immediately. This function does not wait for the given frame being sent to CAN bus. InstancePtr is a pointer to the XCanPs instance. FramePtr is a pointer to a 32-bit aligned buffer containing the CAN frame to be sent. XST_SUCCESS if TX FIFO was not full and the given frame was written into the FIFO.XST_FIFO_NO_ROOM if there is no room in the TX FIFO for the given frame.XST_DEVICE_BUSY if a transfer is already in progress. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsBusy, XCanPs::IsReady, XCanPs_IsTxFifoFull, XCANPS_TXFIFO_DLC_OFFSET, XCANPS_TXFIFO_DW1_OFFSET, XCANPS_TXFIFO_DW2_OFFSET, XCANPS_TXFIFO_ID_OFFSET, XCanPs_WriteReg.
Referenced by XCanPs_SelfTest.
s32 XCanPs_Recv(XCanPs *InstancePtr, u32 *FramePtr)
This function receives a CAN Frame.
This function first checks if RX FIFO is empty, if not, it then reads a frame from the RX FIFO into the given buffer. This function returns error code immediately if there is no frame in the RX FIFO. InstancePtr is a pointer to the XCanPs instance. FramePtr is a pointer to a 32-bit aligned buffer where the CAN frame to be written. XST_SUCCESS if RX FIFO was not empty and a frame was read from RX FIFO successfully and written into the given buffer.XST_NO_DATA if there is no frame to be received from the FIFO. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCanPs_IntrClear, XCanPs_IsRxEmpty, XCANPS_IXR_RXNEMP_MASK, XCanPs_ReadReg, XCANPS_RXFIFO_DLC_OFFSET, XCANPS_RXFIFO_DW1_OFFSET, XCANPS_RXFIFO_DW2_OFFSET, XCANPS_RXFIFO_ID_OFFSET.
Referenced by XCanPs_SelfTest.
s32 XCanPs_SendHighPriority(XCanPs *InstancePtr, u32 *FramePtr)
This routine sends a CAN High Priority frame.
This function first checks if TX High Priority Buffer is empty. If yes, it then writes the given frame into the Buffer. If not, this function returns immediately. This function does not wait for the given frame being sent to CAN bus. InstancePtr is a pointer to the XCanPs instance. FramePtr is a pointer to a 32-bit aligned buffer containing the CAN High Priority frame to be sent. XST_SUCCESS if TX High Priority Buffer was not full and the given frame was written into the buffer.XST_FIFO_NO_ROOM if there is no room in the TX High Priority Buffer for this frame.XST_DEVICE_BUSY if a transfer is already in progress. If the frame needs to be sent immediately and not delayed by processor's interrupt handling, the caller should disable interrupt at processor level before invoking this function.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsBusy, XCanPs::IsReady, XCanPs_IsHighPriorityBufFull, XCANPS_TXHPB_DLC_OFFSET, XCANPS_TXHPB_DW1_OFFSET, XCANPS_TXHPB_DW2_OFFSET, XCANPS_TXHPB_ID_OFFSET, XCanPs_WriteReg.
void XCanPs_AcceptFilterEnable(XCanPs *InstancePtr, u32 FilterIndexes)
This routine enables individual acceptance filters.
Up to 4 filters could be enabled. InstancePtr is a pointer to the XCanPs instance. FilterIndexes specifies which filter(s) to enable. Use any XCANPS_AFR_UAF*_MASK to enable one filter, and "Or" multiple XCANPS_AFR_UAF*_MASK values if multiple filters need to be enabled. Any filter not specified in this parameter will keep its previous enable/disable setting. None. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCANPS_AFR_OFFSET, XCANPS_AFR_UAF_ALL_MASK, XCanPs_ReadReg, XCanPs_WriteReg.
void XCanPs_AcceptFilterDisable(XCanPs *InstancePtr, u32 FilterIndexes)
This routine disables individual acceptance filters.
Up to 4 filters could be disabled. If all acceptance filters are disabled then all the received frames are stored in the RX FIFO. InstancePtr is a pointer to the XCanPs instance. FilterIndexes specifies which filter(s) to disable. Use any XCANPS_AFR_UAF*_MASK to disable one filter, and "Or" multiple XCANPS_AFR_UAF*_MASK values if multiple filters need to be disabled. Any filter not specified in this parameter will keep its previous enable/disable setting. If all acceptance filters are disabled then all received frames are stored in the RX FIFO. None. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCANPS_AFR_OFFSET, XCANPS_AFR_UAF_ALL_MASK, XCanPs_ReadReg, XCanPs_WriteReg.
u32 XCanPs_AcceptFilterGetEnabled(XCanPs *InstancePtr)
This function returns enabled acceptance filters.
Use XCANPS_AFR_UAF*_MASK defined in xcanps_hw.h to interpret the returned value. If no acceptance filters are enabled then all received frames are stored in the RX FIFO. InstancePtr is a pointer to the XCanPs instance. The value stored in Acceptance Filter Register. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCANPS_AFR_OFFSET, XCanPs_ReadReg.
Referenced by XCanPs_AcceptFilterSet.
s32 XCanPs_AcceptFilterSet(XCanPs *InstancePtr, u32 FilterIndex, u32 MaskValue, u32 IdValue)
This function sets values to the Acceptance Filter Mask Register (AFMR) and Acceptance Filter ID Register (AFIR) for the specified Acceptance Filter.
Use XCANPS_IDR_* defined in xcanps_hw.h to create the values to set the filter. Read the xcanps.h file and device specification for details.This function should be called only after: The given filter is disabled by calling XCanPs_AcceptFilterDisable()And the CAN device is ready to accept writes to AFMR and AFIR, i.e., XCanPs_IsAcceptFilterBusy() returns FALSE. InstancePtr is a pointer to the XCanPs instance. FilterIndex defines which Acceptance Filter Mask and ID Register to set. Use any single XCANPS_AFR_UAF*_MASK value. MaskValue is the value to write to the chosen Acceptance Filter Mask Register. IdValue is the value to write to the chosen Acceptance Filter ID Register. XST_SUCCESS if the values were set successfully.XST_FAILURE if the given filter was not disabled, or the CAN device was not ready to accept writes to AFMR and AFIR. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCanPs_AcceptFilterGetEnabled, XCANPS_AFIR1_OFFSET, XCANPS_AFIR2_OFFSET, XCANPS_AFIR3_OFFSET, XCANPS_AFIR4_OFFSET, XCANPS_AFMR1_OFFSET, XCANPS_AFMR2_OFFSET, XCANPS_AFMR3_OFFSET, XCANPS_AFMR4_OFFSET, XCANPS_AFR_UAF1_MASK, XCANPS_AFR_UAF2_MASK, XCANPS_AFR_UAF3_MASK, XCANPS_AFR_UAF4_MASK, XCanPs_IsAcceptFilterBusy, XCanPs_WriteReg.
void XCanPs_AcceptFilterGet(XCanPs *InstancePtr, u32 FilterIndex, u32 *MaskValue, u32 *IdValue)
This function reads the values of the Acceptance Filter Mask and ID Register for the specified Acceptance Filter.
Use XCANPS_IDR_* defined in xcanps_hw.h to interpret the values. Read the xcanps.h file and device specification for details. InstancePtr is a pointer to the XCanPs instance. FilterIndex defines which Acceptance Filter Mask Register to get Mask and ID from. Use any single XCANPS_FILTER_* value. MaskValue is a pointer to the data in which the Mask value read from the chosen Acceptance Filter Mask Register is returned. IdValue is a pointer to the data in which the ID value read from the chosen Acceptance Filter ID Register is returned. None. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCANPS_AFIR1_OFFSET, XCANPS_AFIR2_OFFSET, XCANPS_AFIR3_OFFSET, XCANPS_AFIR4_OFFSET, XCANPS_AFMR1_OFFSET, XCANPS_AFMR2_OFFSET, XCANPS_AFMR3_OFFSET, XCANPS_AFMR4_OFFSET, XCANPS_AFR_UAF1_MASK, XCANPS_AFR_UAF2_MASK, XCANPS_AFR_UAF3_MASK, XCANPS_AFR_UAF4_MASK, XCanPs_ReadReg.
s32 XCanPs_SetBaudRatePrescaler(XCanPs *InstancePtr, u8 Prescaler)
This routine sets Baud Rate Prescaler value.
The system clock for the CAN controller is divided by (Prescaler + 1) to generate the quantum clock needed for sampling and synchronization. Read the device specification for details.Baud Rate Prescaler can be set only if the CAN device is in Configuration Mode. Call XCanPs_EnterMode() to enter Configuration Mode before using this function. InstancePtr is a pointer to the XCanPs instance. Prescaler is the value to set. Valid values are from 0 to 255. XST_SUCCESS if the Baud Rate Prescaler value is set successfully.XST_FAILURE if CAN device is not in Configuration Mode. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCANPS_BRPR_OFFSET, XCanPs_GetMode, XCANPS_MODE_CONFIG, XCanPs_WriteReg.
Referenced by CanPsPolledExample, XCanPs_SelfTest.
u8 XCanPs_GetBaudRatePrescaler(XCanPs *InstancePtr)
This routine gets Baud Rate Prescaler value.
The system clock for the CAN controller is divided by (Prescaler + 1) to generate the quantum clock needed for sampling and synchronization. Read the device specification for details. InstancePtr is a pointer to the XCanPs instance. Current used Baud Rate Prescaler value. The value's range is from 0 to 255. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCANPS_BRPR_OFFSET, XCanPs_ReadReg.
s32 XCanPs_SetBitTiming(XCanPs *InstancePtr, u8 SyncJumpWidth, u8 TimeSegment2, u8 TimeSegment1)
This routine sets Bit time.
Time segment 1, Time segment 2 and Synchronization Jump Width are set in this function. Device specification requires the values passed into this function be one less than the actual values of these fields. Read the device specification for details.Bit time can be set only if the CAN device is in Configuration Mode. Call XCanPs_EnterMode() to enter Configuration Mode before using this function. InstancePtr is a pointer to the XCanPs instance. SyncJumpWidth is the Synchronization Jump Width value to set. Valid values are from 0 to 3. TimeSegment2 is the Time Segment 2 value to set. Valid values are from 0 to 7. TimeSegment1 is the Time Segment 1 value to set. Valid values are from 0 to 15. XST_SUCCESS if the Bit time is set successfully.XST_FAILURE if CAN device is not in Configuration Mode. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCANPS_BTR_OFFSET, XCANPS_BTR_SJW_MASK, XCANPS_BTR_SJW_SHIFT, XCANPS_BTR_TS1_MASK, XCANPS_BTR_TS2_MASK, XCANPS_BTR_TS2_SHIFT, XCanPs_GetMode, XCANPS_MODE_CONFIG, XCanPs_WriteReg.
Referenced by CanPsPolledExample, XCanPs_SelfTest.
void XCanPs_GetBitTiming(XCanPs *InstancePtr, u8 *SyncJumpWidth, u8 *TimeSegment2, u8 *TimeSegment1)
This routine gets Bit time.
Time segment 1, Time segment 2 and Synchronization Jump Width values are read in this function. According to device specification, the actual value of each of these fields is one more than the value read. Read the device specification for details. InstancePtr is a pointer to the XCanPs instance. SyncJumpWidth will store the Synchronization Jump Width value after this function returns. Its value ranges from 0 to 3. TimeSegment2 will store the Time Segment 2 value after this function returns. Its value ranges from 0 to 7. TimeSegment1 will store the Time Segment 1 value after this function returns. Its value ranges from 0 to 15. None. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCANPS_BTR_OFFSET, XCANPS_BTR_SJW_MASK, XCANPS_BTR_SJW_SHIFT, XCANPS_BTR_TS1_MASK, XCANPS_BTR_TS2_MASK, XCANPS_BTR_TS2_SHIFT, XCanPs_ReadReg.
s32 XCanPs_SetRxIntrWatermark(XCanPs *InstancePtr, u8 Threshold)
This routine sets the Rx Full threshold in the Watermark Interrupt Register.
InstancePtr is a pointer to the XCanPs instance. Threshold is the threshold to be set. The valid values are from 1 to 63. XST_FAILURE - If the CAN device is not in Configuration Mode.XST_SUCCESS - If the Rx Full threshold is set in Watermark Interrupt Register. The threshold can only be set when the CAN device is in the configuration mode.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCanPs_GetMode, XCANPS_MODE_CONFIG, XCanPs_ReadReg, XCANPS_WIR_EW_MASK, XCANPS_WIR_FW_MASK, XCANPS_WIR_OFFSET, XCanPs_WriteReg.
u8 XCanPs_GetRxIntrWatermark(XCanPs *InstancePtr)
This routine gets the Rx Full threshold from the Watermark Interrupt Register.
InstancePtr is a pointer to the XCanPs instance. The Rx FIFO full watermark threshold value. The valid values are 1 to 63. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCanPs_ReadReg, XCANPS_WIR_FW_MASK, XCANPS_WIR_OFFSET.
s32 XCanPs_SetTxIntrWatermark(XCanPs *InstancePtr, u8 Threshold)
This routine sets the Tx Empty Threshold in the Watermark Interrupt Register.
InstancePtr is a pointer to the XCanPs instance. Threshold is the threshold to be set. The valid values are from 1 to 63. XST_FAILURE - If the CAN device is not in Configuration Mode.XST_SUCCESS - If the threshold is set in Watermark Interrupt Register. The threshold can only be set when the CAN device is in the configuration mode.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCanPs_GetMode, XCANPS_MODE_CONFIG, XCanPs_ReadReg, XCANPS_WIR_EW_MASK, XCANPS_WIR_EW_SHIFT, XCANPS_WIR_FW_MASK, XCANPS_WIR_OFFSET, XCanPs_WriteReg.
u8 XCanPs_GetTxIntrWatermark(XCanPs *InstancePtr)
This routine gets the Tx Empty threshold from Watermark Interrupt Register.
InstancePtr is a pointer to the XCanPs instance. The Tx Empty FIFO threshold value. The valid values are 1 to 63. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCanPs_ReadReg, XCANPS_WIR_EW_MASK, XCANPS_WIR_EW_SHIFT, XCANPS_WIR_OFFSET.
s32 XCanPs_SelfTest(XCanPs *InstancePtr)
This function runs a self-test on the CAN driver/device.
The test resets the device, sets up the Loop Back mode, sends a standard frame, receives the frame, verifies the contents, and resets the device again.Note that this is a destructive test in that resets of the device are performed. Refer the device specification for the device status after the reset operation. InstancePtr is a pointer to the XCanPs instance. XST_SUCCESS if the self-test passed. i.e., the frame received via the internal loop back has the same contents as the frame sent. XST_FAILURE Otherwise. If the CAN device does not work properly, this function may enter an infinite loop and will never return to the caller. If XST_FAILURE is returned, the device is not reset so that the caller could have a chance to check reason(s) causing the failure.
References XCanPs::IsReady, XCanPs_CreateDlcValue, XCanPs_CreateIdValue, XCANPS_DLCR_TIMESTAMP_MASK, XCanPs_EnterMode, XCanPs_GetMode, XCANPS_ISR_OFFSET, XCANPS_IXR_RXNEMP_MASK, XCANPS_MAX_FRAME_SIZE_IN_WORDS, XCANPS_MODE_CONFIG, XCANPS_MODE_LOOPBACK, XCanPs_ReadReg, XCanPs_Recv, XCanPs_Reset, XCanPs_Send, XCanPs_SetBaudRatePrescaler, XCanPs_SetBitTiming.
Referenced by CanPsIntrExample, CanPsPolledExample, CanPsWatermarkIntrExample.
void XCanPs_IntrEnable(XCanPs *InstancePtr, u32 Mask)
This routine enables interrupt(s).
Use the XCANPS_IXR_* constants defined in xcanps_hw.h to create the bit-mask to enable interrupts. InstancePtr is a pointer to the XCanPs instance. Mask is the mask to enable. Bit positions of 1 will be enabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XCANPS_IXR_* bits defined in xcanps_hw.h. None. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCANPS_IER_OFFSET, XCanPs_IntrGetEnabled, XCanPs_WriteReg.
Referenced by CanPsIntrExample, CanPsWatermarkIntrExample.
void XCanPs_IntrDisable(XCanPs *InstancePtr, u32 Mask)
This routine disables interrupt(s).
Use the XCANPS_IXR_* constants defined in xcanps_hw.h to create the bit-mask to disable interrupt(s). InstancePtr is a pointer to the XCanPs instance. Mask is the mask to disable. Bit positions of 1 will be disabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XCANPS_IXR_* bits defined in xcanps_hw.h. None. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCANPS_IER_OFFSET, XCanPs_IntrGetEnabled, XCanPs_WriteReg.
Referenced by CanPsWatermarkIntrExample.
u32 XCanPs_IntrGetEnabled(XCanPs *InstancePtr)
This routine returns enabled interrupt(s).
Use the XCANPS_IXR_* constants defined in xcanps_hw.h to interpret the returned value. InstancePtr is a pointer to the XCanPs instance. Enabled interrupt(s) in a 32-bit format. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCANPS_IER_OFFSET, XCanPs_ReadReg.
Referenced by XCanPs_IntrDisable, XCanPs_IntrEnable, XCanPs_IntrHandler.
u32 XCanPs_IntrGetStatus(XCanPs *InstancePtr)
This routine returns interrupt status read from Interrupt Status Register.
Use the XCANPS_IXR_* constants defined in xcanps_hw.h to interpret the returned value. InstancePtr is a pointer to the XCanPs instance. The value stored in Interrupt Status Register. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCANPS_ISR_OFFSET, XCanPs_ReadReg.
Referenced by XCanPs_IntrClear, XCanPs_IntrHandler.
void XCanPs_IntrClear(XCanPs *InstancePtr, u32 Mask)
This function clears interrupt(s).
Every bit set in Interrupt Status Register indicates that a specific type of interrupt is occurring, and this function clears one or more interrupts by writing a bit mask to Interrupt Clear Register. InstancePtr is a pointer to the XCanPs instance. Mask is the mask to clear. Bit positions of 1 will be cleared. Bit positions of 0 will not change the previous interrupt status. This mask is formed by OR'ing XCANPS_IXR_* bits defined in xcanps_hw.h. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCANPS_ICR_OFFSET, XCanPs_IntrGetStatus, XCanPs_WriteReg.
Referenced by XCanPs_IntrHandler, XCanPs_Recv.
void XCanPs_IntrHandler(void *InstancePtr)
This routine is the interrupt handler for the CAN driver.
This handler reads the interrupt status from the ISR, determines the source of the interrupts, calls according callbacks, and finally clears the interrupts.Application beyond this driver is responsible for providing callbacks to handle interrupts and installing the callbacks using XCanPs_SetHandler() during initialization phase. An example delivered with this driver demonstrates how this could be done. InstancePtr is a pointer to the XCanPs instance that just interrupted. None. None.
References XCanPs::ErrorHandler, XCanPs::ErrorRef, XCanPs::EventHandler, XCanPs::EventRef, XCanPs::IsReady, XCanPs::RecvHandler, XCanPs::RecvRef, XCanPs::SendHandler, XCanPs::SendRef, XCanPs_ClearBusErrorStatus, XCanPs_GetBusErrorStatus, XCanPs_IntrClear, XCanPs_IntrGetEnabled, XCanPs_IntrGetStatus, XCANPS_IXR_ARBLST_MASK, XCANPS_IXR_BSOFF_MASK, XCANPS_IXR_ERROR_MASK, XCANPS_IXR_RXFWMFLL_MASK, XCANPS_IXR_RXNEMP_MASK, XCANPS_IXR_RXOFLW_MASK, XCANPS_IXR_RXUFLW_MASK, XCANPS_IXR_SLP_MASK, XCANPS_IXR_TXBFLL_MASK, XCANPS_IXR_TXFLL_MASK, XCANPS_IXR_TXFWMEMP_MASK, XCANPS_IXR_TXOK_MASK, XCANPS_IXR_WKUP_MASK.
Referenced by CanPsIntrExample, CanPsWatermarkIntrExample.
s32 XCanPs_SetHandler(XCanPs *InstancePtr, u32 HandlerType, void *CallBackFunc, void *CallBackRef)
This routine installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function Type ----------------------- ------------------------ XCANPS_HANDLER_SEND XCanPs_SendRecvHandler XCANPS_HANDLER_RECV XCanPs_SendRecvHandler XCANPS_HANDLER_ERROR XCanPs_ErrorHandler XCANPS_HANDLER_EVENT XCanPs_EventHandlerHandlerType Invoked by this driver when: ------------------------------------------------------------------------- XCANPS_HANDLER_SEND A frame transmitted by a call to XCanPs_Send() has been sent successfully.XCANPS_HANDLER_RECV A frame(s) has been received and is sitting in the RX FIFO.XCANPS_HANDLER_ERROR An error interrupt is occurring.XCANPS_HANDLER_EVENT Any other kind of interrupt is occurring. InstancePtr is a pointer to the XCanPs instance. HandlerType specifies which handler is to be attached. CallBackFunc is the address of the callback function. CallBackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS when handler is installed.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XCanPs::ErrorHandler, XCanPs::ErrorRef, XCanPs::EventHandler, XCanPs::EventRef, XCanPs::IsReady, XCanPs::RecvHandler, XCanPs::RecvRef, XCanPs::SendHandler, XCanPs::SendRef, XCANPS_HANDLER_ERROR, XCANPS_HANDLER_EVENT, XCANPS_HANDLER_RECV, XCANPS_HANDLER_SEND.
Referenced by CanPsIntrExample, CanPsWatermarkIntrExample.
XCanPs_Config * XCanPs_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XCanPs_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xcanps.h for the definition of XCanPs_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XCanPs_Config::Name, XCanPs_ConfigTable.
Referenced by CanPsIntrExample, CanPsPolledExample, CanPsWatermarkIntrExample.
void XCanPs_ResetHw(UINTPTR BaseAddr)
This function resets the CAN device.
Calling this function resets the device immediately, and any pending transmission or reception is terminated at once. Both Object Layer and Transfer Layer are reset. This function does not reset the Physical Layer. All registers are reset to the default values, and no previous status will be restored. TX FIFO, RX FIFO and TX High Priority Buffer are also reset.The CAN device will be in Configuration Mode immediately after this function returns. BaseAddr is the baseaddress of the interface. None. None.
References XCANPS_SRR_OFFSET, XCANPS_SRR_SRST_MASK, XCanPs_WriteReg.
XCANPS_H
by using protection macros
XCanPs_IsTxDone
This macro checks if the transmission is complete.
InstancePtr is a pointer to the XCanPs instance. TRUE if the transmission is done.FALSE if the transmission is not done. C-Style signature: int XCanPs_IsTxDone(XCanPs *InstancePtr)
XCanPs_IsTxFifoFull
This macro checks if the transmission FIFO is full.
InstancePtr is a pointer to the XCanPs instance. TRUE if TX FIFO is full.FALSE if the TX FIFO is NOT full. C-Style signature: int XCanPs_IsTxFifoFull(XCanPs *InstancePtr)
Referenced by XCanPs_Send.
XCanPs_IsHighPriorityBufFull
This macro checks if the Transmission High Priority Buffer is full.
InstancePtr is a pointer to the XCanPs instance. TRUE if the TX High Priority Buffer is full.FALSE if the TX High Priority Buffer is NOT full. C-Style signature: int XCanPs_IsHighPriorityBufFull(XCanPs *InstancePtr)
Referenced by XCanPs_SendHighPriority.
XCanPs_IsRxEmpty
This macro checks if the receive FIFO is empty.
InstancePtr is a pointer to the XCanPs instance. TRUE if RX FIFO is empty.FALSE if the RX FIFO is NOT empty. C-Style signature: int XCanPs_IsRxEmpty(XCanPs *InstancePtr)
Referenced by XCanPs_Recv.
XCanPs_IsAcceptFilterBusy
This macro checks if the CAN device is ready for the driver to change Acceptance Filter Identifier Registers (AFIR) and Acceptance Filter Mask Registers (AFMR).
AFIR and AFMR for a filter are changeable only after the filter is disabled and this routine returns FALSE. The filter can be disabled using the XCanPs_AcceptFilterDisable function.Use the XCanPs_Accept_* functions for configuring the acceptance filters. InstancePtr is a pointer to the XCanPs instance. TRUE if the device is busy and NOT ready to accept writes to AFIR and AFMR.FALSE if the device is ready to accept writes to AFIR and AFMR. C-Style signature: int XCanPs_IsAcceptFilterBusy(XCanPs *InstancePtr)
Referenced by XCanPs_AcceptFilterSet.
XCanPs_CreateIdValue
This macro calculates CAN message identifier value given identifier field values.
StandardId contains Standard Message ID value. SubRemoteTransReq contains Substitute Remote Transmission Request value. IdExtension contains Identifier Extension value. ExtendedId contains Extended Message ID value. RemoteTransReq contains Remote Transmission Request value. Message Identifier value. C-Style signature: u32 XCanPs_CreateIdValue(u32 StandardId, u32 SubRemoteTransReq, u32 IdExtension, u32 ExtendedId, u32 RemoteTransReq) Read the CAN specification for meaning of each parameter.
Referenced by XCanPs_SelfTest.
XCanPs_CreateDlcValue
This macro calculates value for Data Length Code register given Data Length Code value.
DataLengCode indicates Data Length Code value. Value that can be assigned to Data Length Code register. C-Style signature: u32 XCanPs_CreateDlcValue(u32 DataLengCode) Read the CAN specification for meaning of Data Length Code.
Referenced by XCanPs_SelfTest.
XCanPs_ClearTimestamp
This macro clears the timestamp in the Timestamp Control Register.
InstancePtr is a pointer to the XCanPs instance. None. C-Style signature: void XCanPs_ClearTimestamp(XCanPs *InstancePtr)
XCANPS_HW_H
by using protection macros
XCANPS_TXBUF_ID_OFFSET
TX High Priority Buffer ID.
XCANPS_TXBUF_DLC_OFFSET
TX High Priority Buffer DLC.
XCANPS_TXBUF_DW1_OFFSET
TX High Priority Buf Data 1.
XCANPS_TXBUF_DW2_OFFSET
TX High Priority Buf Data Word 2.
XCANPS_RXFWIR_RXFLL_MASK
Rx Full Threshold mask.
XCANPS_RXWIR_OFFSET
Watermark Interrupt Reg.
XCANPS_IXR_RXFLL_MASK
Rx FIFO Watermark Full.
XCanPs_ReadReg
This macro reads the given register.
BaseAddr is the base address of the device. RegOffset is the register offset to be read. The 32-bit value of the register None.
Referenced by XCanPs_AcceptFilterDisable, XCanPs_AcceptFilterEnable, XCanPs_AcceptFilterGet, XCanPs_AcceptFilterGetEnabled, XCanPs_GetBaudRatePrescaler, XCanPs_GetBitTiming, XCanPs_GetBusErrorCounter, XCanPs_GetBusErrorStatus, XCanPs_GetRxIntrWatermark, XCanPs_GetStatus, XCanPs_GetTxIntrWatermark, XCanPs_IntrGetEnabled, XCanPs_IntrGetStatus, XCanPs_Recv, XCanPs_SelfTest, XCanPs_SetRxIntrWatermark, XCanPs_SetTxIntrWatermark.
XCanPs_WriteReg
This macro writes the given register.
BaseAddr is the base address of the device. RegOffset is the register offset to be written. Data is the 32-bit value to write to the register. None. None.
Referenced by XCanPs_AcceptFilterDisable, XCanPs_AcceptFilterEnable, XCanPs_AcceptFilterSet, XCanPs_ClearBusErrorStatus, XCanPs_EnterMode, XCanPs_IntrClear, XCanPs_IntrDisable, XCanPs_IntrEnable, XCanPs_Reset, XCanPs_ResetHw, XCanPs_Send, XCanPs_SendHighPriority, XCanPs_SetBaudRatePrescaler, XCanPs_SetBitTiming, XCanPs_SetRxIntrWatermark, XCanPs_SetTxIntrWatermark.
XCANPS_MAX_FRAME_SIZE_IN_WORDS
Flag for Max Frame size.
Referenced by XCanPs_SelfTest.
FRAME_DATA_LENGTH
Frame Data field length.