xcanps.c
static void StubHandler(void)
This routine is a stub for the asynchronous callbacks.
The stub is here in case the upper layer forgot to set the handler(s). On initialization, all handlers are set to this callback. It is considered an error for this handler to be invoked.
s32 XCanPs_CfgInitialize(XCanPs *InstancePtr, XCanPs_Config *ConfigPtr, UINTPTR EffectiveAddr)
This function initializes a XCanPs instance/driver.
The initialization entails: Initialize all members of the XCanPs structure.Reset the CAN device. The CAN device will enter Configuration Mode immediately after the reset is finished. InstancePtr is a pointer to the XCanPs instance. ConfigPtr points to the XCanPs device configuration structure. EffectiveAddr is the device base address in the virtual memory address space. If the address translation is not used then the physical address is passed. Unexpected errors may occur if the address mapping is changed after this function is invoked. XST_SUCCESS always. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::ErrorHandler, XCanPs::EventHandler, XCanPs::IsBusy, XCanPs::IsReady, XCanPs::RecvHandler, XCanPs::SendHandler, XCanPs_Reset.
Referenced by CanPsIntrExample, CanPsPolledExample, CanPsWatermarkIntrExample.
void XCanPs_Reset(XCanPs *InstancePtr)
This function resets the CAN device.
Calling this function resets the device immediately, and any pending transmission or reception is terminated at once. Both Object Layer and Transfer Layer are reset. This function does not reset the Physical Layer. All registers are reset to the default values, and no previous status will be restored. TX FIFO, RX FIFO and TX High Priority Buffer are also reset.When a reset is required due to an internal error, the driver notifies the upper layer software of this need through the error status code or interrupts. The upper layer software is responsible for calling this Reset function and then re-configuring the device.The CAN device will be in Configuration Mode immediately after this function returns. InstancePtr is a pointer to the XCanPs instance. None. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCANPS_SRR_OFFSET, XCANPS_SRR_SRST_MASK, XCanPs_WriteReg.
Referenced by XCanPs_CfgInitialize, XCanPs_SelfTest.
u8 XCanPs_GetMode(XCanPs *InstancePtr)
This routine returns the current operation mode of the CAN device.
InstancePtr is a pointer to the XCanPs instance. XCANPS_MODE_CONFIG if the device is in Configuration Mode.XCANPS_MODE_SLEEP if the device is in Sleep Mode.XCANPS_MODE_NORMAL if the device is in Normal Mode.XCANPS_MODE_LOOPBACK if the device is in Loop Back Mode.XCANPS_MODE_SNOOP if the device is in Snoop Mode. None.
References XCanPs::IsReady, XCanPs_GetStatus, XCANPS_MODE_CONFIG, XCANPS_MODE_LOOPBACK, XCANPS_MODE_NORMAL, XCANPS_MODE_SLEEP, XCANPS_MODE_SNOOP, XCANPS_SR_CONFIG_MASK, XCANPS_SR_NORMAL_MASK, XCANPS_SR_SLEEP_MASK, XCANPS_SR_SNOOP_MASK.
Referenced by CanPsIntrExample, CanPsPolledExample, CanPsWatermarkIntrExample, XCanPs_EnterMode, XCanPs_SelfTest, XCanPs_SetBaudRatePrescaler, XCanPs_SetBitTiming, XCanPs_SetRxIntrWatermark, XCanPs_SetTxIntrWatermark.
void XCanPs_EnterMode(XCanPs *InstancePtr, u8 OperationMode)
This function allows the CAN device to enter one of the following operation modes:
- Configuration Mode: Pass in parameter XCANPS_MODE_CONFIG - Sleep Mode: Pass in parameter XCANPS_MODE_SLEEP - Normal Mode: Pass in parameter XCANPS_MODE_NORMAL - Loop Back Mode: Pass in parameter XCANPS_MODE_LOOPBACK. - Snoop Mode: Pass in parameter XCANPS_MODE_SNOOP. Read the xcanps.h file and device specification for detailed description of each operation mode. InstancePtr is a pointer to the XCanPs instance. OperationMode specify which operation mode to enter. Valid value is any of XCANPS_MODE_* defined in xcanps.h. Multiple modes can not be entered at the same time. None. This function does NOT ensure CAN device enters the specified operation mode before it returns the control to the caller. The caller is responsible for checking current operation mode using XCanPs_GetMode().
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCanPs_GetMode, XCANPS_MODE_CONFIG, XCANPS_MODE_LOOPBACK, XCANPS_MODE_NORMAL, XCANPS_MODE_SLEEP, XCANPS_MODE_SNOOP, XCANPS_MSR_LBACK_MASK, XCANPS_MSR_OFFSET, XCANPS_MSR_SLEEP_MASK, XCANPS_MSR_SNOOP_MASK, XCANPS_SRR_CEN_MASK, XCANPS_SRR_OFFSET, XCanPs_WriteReg.
Referenced by CanPsIntrExample, CanPsPolledExample, CanPsWatermarkIntrExample, XCanPs_SelfTest.
u32 XCanPs_GetStatus(XCanPs *InstancePtr)
This function returns Status value from Status Register (SR).
Use the XCANPS_SR_* constants defined in xcanps_hw.h to interpret the returned value. InstancePtr is a pointer to the XCanPs instance. The 32-bit value read from Status Register. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCanPs_ReadReg, XCANPS_SR_OFFSET.
Referenced by XCanPs_GetMode.
void XCanPs_GetBusErrorCounter(XCanPs *InstancePtr, u8 *RxErrorCount, u8 *TxErrorCount)
This function reads Receive and Transmit error counters.
InstancePtr is a pointer to the XCanPs instance. RxErrorCount is a pointer to data in which the Receive Error counter value is returned. TxErrorCount is a pointer to data in which the Transmit Error counter value is returned. None. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCANPS_ECR_OFFSET, XCANPS_ECR_REC_MASK, XCANPS_ECR_REC_SHIFT, XCANPS_ECR_TEC_MASK, XCanPs_ReadReg.
u32 XCanPs_GetBusErrorStatus(XCanPs *InstancePtr)
This function reads Error Status value from Error Status Register (ESR).
Use the XCANPS_ESR_* constants defined in xcanps_hw.h to interpret the returned value. InstancePtr is a pointer to the XCanPs instance. The 32-bit value read from Error Status Register. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCANPS_ESR_OFFSET, XCanPs_ReadReg.
Referenced by XCanPs_IntrHandler.
void XCanPs_ClearBusErrorStatus(XCanPs *InstancePtr, u32 Mask)
This function clears Error Status bit(s) previously set in Error Status Register (ESR).
Use the XCANPS_ESR_* constants defined in xcanps_hw.h to create the value to pass in. If a bit was cleared in Error Status Register before this function is called, it will not be modified. InstancePtr is a pointer to the XCanPs instance. Mask is he 32-bit mask used to clear bits in Error Status Register. Multiple XCANPS_ESR_* values can be 'OR'ed to clear multiple bits. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCANPS_ESR_OFFSET, XCanPs_WriteReg.
Referenced by XCanPs_IntrHandler.
s32 XCanPs_Send(XCanPs *InstancePtr, u32 *FramePtr)
This function sends a CAN Frame.
If the TX FIFO is not full then the given frame is written into the the TX FIFO otherwise, it returns an error code immediately. This function does not wait for the given frame being sent to CAN bus. InstancePtr is a pointer to the XCanPs instance. FramePtr is a pointer to a 32-bit aligned buffer containing the CAN frame to be sent. XST_SUCCESS if TX FIFO was not full and the given frame was written into the FIFO.XST_FIFO_NO_ROOM if there is no room in the TX FIFO for the given frame.XST_DEVICE_BUSY if a transfer is already in progress. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsBusy, XCanPs::IsReady, XCanPs_IsTxFifoFull, XCANPS_TXFIFO_DLC_OFFSET, XCANPS_TXFIFO_DW1_OFFSET, XCANPS_TXFIFO_DW2_OFFSET, XCANPS_TXFIFO_ID_OFFSET, XCanPs_WriteReg.
Referenced by XCanPs_SelfTest.
s32 XCanPs_Recv(XCanPs *InstancePtr, u32 *FramePtr)
This function receives a CAN Frame.
This function first checks if RX FIFO is empty, if not, it then reads a frame from the RX FIFO into the given buffer. This function returns error code immediately if there is no frame in the RX FIFO. InstancePtr is a pointer to the XCanPs instance. FramePtr is a pointer to a 32-bit aligned buffer where the CAN frame to be written. XST_SUCCESS if RX FIFO was not empty and a frame was read from RX FIFO successfully and written into the given buffer.XST_NO_DATA if there is no frame to be received from the FIFO. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCanPs_IntrClear, XCanPs_IsRxEmpty, XCANPS_IXR_RXNEMP_MASK, XCanPs_ReadReg, XCANPS_RXFIFO_DLC_OFFSET, XCANPS_RXFIFO_DW1_OFFSET, XCANPS_RXFIFO_DW2_OFFSET, XCANPS_RXFIFO_ID_OFFSET.
Referenced by XCanPs_SelfTest.
s32 XCanPs_SendHighPriority(XCanPs *InstancePtr, u32 *FramePtr)
This routine sends a CAN High Priority frame.
This function first checks if TX High Priority Buffer is empty. If yes, it then writes the given frame into the Buffer. If not, this function returns immediately. This function does not wait for the given frame being sent to CAN bus. InstancePtr is a pointer to the XCanPs instance. FramePtr is a pointer to a 32-bit aligned buffer containing the CAN High Priority frame to be sent. XST_SUCCESS if TX High Priority Buffer was not full and the given frame was written into the buffer.XST_FIFO_NO_ROOM if there is no room in the TX High Priority Buffer for this frame.XST_DEVICE_BUSY if a transfer is already in progress. If the frame needs to be sent immediately and not delayed by processor's interrupt handling, the caller should disable interrupt at processor level before invoking this function.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsBusy, XCanPs::IsReady, XCanPs_IsHighPriorityBufFull, XCANPS_TXHPB_DLC_OFFSET, XCANPS_TXHPB_DW1_OFFSET, XCANPS_TXHPB_DW2_OFFSET, XCANPS_TXHPB_ID_OFFSET, XCanPs_WriteReg.
void XCanPs_AcceptFilterEnable(XCanPs *InstancePtr, u32 FilterIndexes)
This routine enables individual acceptance filters.
Up to 4 filters could be enabled. InstancePtr is a pointer to the XCanPs instance. FilterIndexes specifies which filter(s) to enable. Use any XCANPS_AFR_UAF*_MASK to enable one filter, and "Or" multiple XCANPS_AFR_UAF*_MASK values if multiple filters need to be enabled. Any filter not specified in this parameter will keep its previous enable/disable setting. None. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCANPS_AFR_OFFSET, XCANPS_AFR_UAF_ALL_MASK, XCanPs_ReadReg, XCanPs_WriteReg.
void XCanPs_AcceptFilterDisable(XCanPs *InstancePtr, u32 FilterIndexes)
This routine disables individual acceptance filters.
Up to 4 filters could be disabled. If all acceptance filters are disabled then all the received frames are stored in the RX FIFO. InstancePtr is a pointer to the XCanPs instance. FilterIndexes specifies which filter(s) to disable. Use any XCANPS_AFR_UAF*_MASK to disable one filter, and "Or" multiple XCANPS_AFR_UAF*_MASK values if multiple filters need to be disabled. Any filter not specified in this parameter will keep its previous enable/disable setting. If all acceptance filters are disabled then all received frames are stored in the RX FIFO. None. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCANPS_AFR_OFFSET, XCANPS_AFR_UAF_ALL_MASK, XCanPs_ReadReg, XCanPs_WriteReg.
u32 XCanPs_AcceptFilterGetEnabled(XCanPs *InstancePtr)
This function returns enabled acceptance filters.
Use XCANPS_AFR_UAF*_MASK defined in xcanps_hw.h to interpret the returned value. If no acceptance filters are enabled then all received frames are stored in the RX FIFO. InstancePtr is a pointer to the XCanPs instance. The value stored in Acceptance Filter Register. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCANPS_AFR_OFFSET, XCanPs_ReadReg.
Referenced by XCanPs_AcceptFilterSet.
s32 XCanPs_AcceptFilterSet(XCanPs *InstancePtr, u32 FilterIndex, u32 MaskValue, u32 IdValue)
This function sets values to the Acceptance Filter Mask Register (AFMR) and Acceptance Filter ID Register (AFIR) for the specified Acceptance Filter.
Use XCANPS_IDR_* defined in xcanps_hw.h to create the values to set the filter. Read the xcanps.h file and device specification for details.This function should be called only after: The given filter is disabled by calling XCanPs_AcceptFilterDisable()And the CAN device is ready to accept writes to AFMR and AFIR, i.e., XCanPs_IsAcceptFilterBusy() returns FALSE. InstancePtr is a pointer to the XCanPs instance. FilterIndex defines which Acceptance Filter Mask and ID Register to set. Use any single XCANPS_AFR_UAF*_MASK value. MaskValue is the value to write to the chosen Acceptance Filter Mask Register. IdValue is the value to write to the chosen Acceptance Filter ID Register. XST_SUCCESS if the values were set successfully.XST_FAILURE if the given filter was not disabled, or the CAN device was not ready to accept writes to AFMR and AFIR. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCanPs_AcceptFilterGetEnabled, XCANPS_AFIR1_OFFSET, XCANPS_AFIR2_OFFSET, XCANPS_AFIR3_OFFSET, XCANPS_AFIR4_OFFSET, XCANPS_AFMR1_OFFSET, XCANPS_AFMR2_OFFSET, XCANPS_AFMR3_OFFSET, XCANPS_AFMR4_OFFSET, XCANPS_AFR_UAF1_MASK, XCANPS_AFR_UAF2_MASK, XCANPS_AFR_UAF3_MASK, XCANPS_AFR_UAF4_MASK, XCanPs_IsAcceptFilterBusy, XCanPs_WriteReg.
void XCanPs_AcceptFilterGet(XCanPs *InstancePtr, u32 FilterIndex, u32 *MaskValue, u32 *IdValue)
This function reads the values of the Acceptance Filter Mask and ID Register for the specified Acceptance Filter.
Use XCANPS_IDR_* defined in xcanps_hw.h to interpret the values. Read the xcanps.h file and device specification for details. InstancePtr is a pointer to the XCanPs instance. FilterIndex defines which Acceptance Filter Mask Register to get Mask and ID from. Use any single XCANPS_FILTER_* value. MaskValue is a pointer to the data in which the Mask value read from the chosen Acceptance Filter Mask Register is returned. IdValue is a pointer to the data in which the ID value read from the chosen Acceptance Filter ID Register is returned. None. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCANPS_AFIR1_OFFSET, XCANPS_AFIR2_OFFSET, XCANPS_AFIR3_OFFSET, XCANPS_AFIR4_OFFSET, XCANPS_AFMR1_OFFSET, XCANPS_AFMR2_OFFSET, XCANPS_AFMR3_OFFSET, XCANPS_AFMR4_OFFSET, XCANPS_AFR_UAF1_MASK, XCANPS_AFR_UAF2_MASK, XCANPS_AFR_UAF3_MASK, XCANPS_AFR_UAF4_MASK, XCanPs_ReadReg.
s32 XCanPs_SetBaudRatePrescaler(XCanPs *InstancePtr, u8 Prescaler)
This routine sets Baud Rate Prescaler value.
The system clock for the CAN controller is divided by (Prescaler + 1) to generate the quantum clock needed for sampling and synchronization. Read the device specification for details.Baud Rate Prescaler can be set only if the CAN device is in Configuration Mode. Call XCanPs_EnterMode() to enter Configuration Mode before using this function. InstancePtr is a pointer to the XCanPs instance. Prescaler is the value to set. Valid values are from 0 to 255. XST_SUCCESS if the Baud Rate Prescaler value is set successfully.XST_FAILURE if CAN device is not in Configuration Mode. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCANPS_BRPR_OFFSET, XCanPs_GetMode, XCANPS_MODE_CONFIG, XCanPs_WriteReg.
Referenced by CanPsPolledExample, XCanPs_SelfTest.
u8 XCanPs_GetBaudRatePrescaler(XCanPs *InstancePtr)
This routine gets Baud Rate Prescaler value.
The system clock for the CAN controller is divided by (Prescaler + 1) to generate the quantum clock needed for sampling and synchronization. Read the device specification for details. InstancePtr is a pointer to the XCanPs instance. Current used Baud Rate Prescaler value. The value's range is from 0 to 255. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCANPS_BRPR_OFFSET, XCanPs_ReadReg.
s32 XCanPs_SetBitTiming(XCanPs *InstancePtr, u8 SyncJumpWidth, u8 TimeSegment2, u8 TimeSegment1)
This routine sets Bit time.
Time segment 1, Time segment 2 and Synchronization Jump Width are set in this function. Device specification requires the values passed into this function be one less than the actual values of these fields. Read the device specification for details.Bit time can be set only if the CAN device is in Configuration Mode. Call XCanPs_EnterMode() to enter Configuration Mode before using this function. InstancePtr is a pointer to the XCanPs instance. SyncJumpWidth is the Synchronization Jump Width value to set. Valid values are from 0 to 3. TimeSegment2 is the Time Segment 2 value to set. Valid values are from 0 to 7. TimeSegment1 is the Time Segment 1 value to set. Valid values are from 0 to 15. XST_SUCCESS if the Bit time is set successfully.XST_FAILURE if CAN device is not in Configuration Mode. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCANPS_BTR_OFFSET, XCANPS_BTR_SJW_MASK, XCANPS_BTR_SJW_SHIFT, XCANPS_BTR_TS1_MASK, XCANPS_BTR_TS2_MASK, XCANPS_BTR_TS2_SHIFT, XCanPs_GetMode, XCANPS_MODE_CONFIG, XCanPs_WriteReg.
Referenced by CanPsPolledExample, XCanPs_SelfTest.
void XCanPs_GetBitTiming(XCanPs *InstancePtr, u8 *SyncJumpWidth, u8 *TimeSegment2, u8 *TimeSegment1)
This routine gets Bit time.
Time segment 1, Time segment 2 and Synchronization Jump Width values are read in this function. According to device specification, the actual value of each of these fields is one more than the value read. Read the device specification for details. InstancePtr is a pointer to the XCanPs instance. SyncJumpWidth will store the Synchronization Jump Width value after this function returns. Its value ranges from 0 to 3. TimeSegment2 will store the Time Segment 2 value after this function returns. Its value ranges from 0 to 7. TimeSegment1 will store the Time Segment 1 value after this function returns. Its value ranges from 0 to 15. None. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCANPS_BTR_OFFSET, XCANPS_BTR_SJW_MASK, XCANPS_BTR_SJW_SHIFT, XCANPS_BTR_TS1_MASK, XCANPS_BTR_TS2_MASK, XCANPS_BTR_TS2_SHIFT, XCanPs_ReadReg.
s32 XCanPs_SetRxIntrWatermark(XCanPs *InstancePtr, u8 Threshold)
This routine sets the Rx Full threshold in the Watermark Interrupt Register.
InstancePtr is a pointer to the XCanPs instance. Threshold is the threshold to be set. The valid values are from 1 to 63. XST_FAILURE - If the CAN device is not in Configuration Mode.XST_SUCCESS - If the Rx Full threshold is set in Watermark Interrupt Register. The threshold can only be set when the CAN device is in the configuration mode.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCanPs_GetMode, XCANPS_MODE_CONFIG, XCanPs_ReadReg, XCANPS_WIR_EW_MASK, XCANPS_WIR_FW_MASK, XCANPS_WIR_OFFSET, XCanPs_WriteReg.
u8 XCanPs_GetRxIntrWatermark(XCanPs *InstancePtr)
This routine gets the Rx Full threshold from the Watermark Interrupt Register.
InstancePtr is a pointer to the XCanPs instance. The Rx FIFO full watermark threshold value. The valid values are 1 to 63. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCanPs_ReadReg, XCANPS_WIR_FW_MASK, XCANPS_WIR_OFFSET.
s32 XCanPs_SetTxIntrWatermark(XCanPs *InstancePtr, u8 Threshold)
This routine sets the Tx Empty Threshold in the Watermark Interrupt Register.
InstancePtr is a pointer to the XCanPs instance. Threshold is the threshold to be set. The valid values are from 1 to 63. XST_FAILURE - If the CAN device is not in Configuration Mode.XST_SUCCESS - If the threshold is set in Watermark Interrupt Register. The threshold can only be set when the CAN device is in the configuration mode.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCanPs_GetMode, XCANPS_MODE_CONFIG, XCanPs_ReadReg, XCANPS_WIR_EW_MASK, XCANPS_WIR_EW_SHIFT, XCANPS_WIR_FW_MASK, XCANPS_WIR_OFFSET, XCanPs_WriteReg.
u8 XCanPs_GetTxIntrWatermark(XCanPs *InstancePtr)
This routine gets the Tx Empty threshold from Watermark Interrupt Register.
InstancePtr is a pointer to the XCanPs instance. The Tx Empty FIFO threshold value. The valid values are 1 to 63. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCanPs_ReadReg, XCANPS_WIR_EW_MASK, XCANPS_WIR_EW_SHIFT, XCANPS_WIR_OFFSET.