xcanps_intr.c
void XCanPs_IntrEnable(XCanPs *InstancePtr, u32 Mask)
This routine enables interrupt(s).
Use the XCANPS_IXR_* constants defined in xcanps_hw.h to create the bit-mask to enable interrupts. InstancePtr is a pointer to the XCanPs instance. Mask is the mask to enable. Bit positions of 1 will be enabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XCANPS_IXR_* bits defined in xcanps_hw.h. None. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCANPS_IER_OFFSET, XCanPs_IntrGetEnabled, XCanPs_WriteReg.
Referenced by CanPsIntrExample, CanPsWatermarkIntrExample.
void XCanPs_IntrDisable(XCanPs *InstancePtr, u32 Mask)
This routine disables interrupt(s).
Use the XCANPS_IXR_* constants defined in xcanps_hw.h to create the bit-mask to disable interrupt(s). InstancePtr is a pointer to the XCanPs instance. Mask is the mask to disable. Bit positions of 1 will be disabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XCANPS_IXR_* bits defined in xcanps_hw.h. None. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCANPS_IER_OFFSET, XCanPs_IntrGetEnabled, XCanPs_WriteReg.
Referenced by CanPsWatermarkIntrExample.
u32 XCanPs_IntrGetEnabled(XCanPs *InstancePtr)
This routine returns enabled interrupt(s).
Use the XCANPS_IXR_* constants defined in xcanps_hw.h to interpret the returned value. InstancePtr is a pointer to the XCanPs instance. Enabled interrupt(s) in a 32-bit format. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCANPS_IER_OFFSET, XCanPs_ReadReg.
Referenced by XCanPs_IntrDisable, XCanPs_IntrEnable, XCanPs_IntrHandler.
u32 XCanPs_IntrGetStatus(XCanPs *InstancePtr)
This routine returns interrupt status read from Interrupt Status Register.
Use the XCANPS_IXR_* constants defined in xcanps_hw.h to interpret the returned value. InstancePtr is a pointer to the XCanPs instance. The value stored in Interrupt Status Register. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCANPS_ISR_OFFSET, XCanPs_ReadReg.
Referenced by XCanPs_IntrClear, XCanPs_IntrHandler.
void XCanPs_IntrClear(XCanPs *InstancePtr, u32 Mask)
This function clears interrupt(s).
Every bit set in Interrupt Status Register indicates that a specific type of interrupt is occurring, and this function clears one or more interrupts by writing a bit mask to Interrupt Clear Register. InstancePtr is a pointer to the XCanPs instance. Mask is the mask to clear. Bit positions of 1 will be cleared. Bit positions of 0 will not change the previous interrupt status. This mask is formed by OR'ing XCANPS_IXR_* bits defined in xcanps_hw.h. None.
References XCanPs_Config::BaseAddr, XCanPs::CanConfig, XCanPs::IsReady, XCANPS_ICR_OFFSET, XCanPs_IntrGetStatus, XCanPs_WriteReg.
Referenced by XCanPs_IntrHandler, XCanPs_Recv.
void XCanPs_IntrHandler(void *InstancePtr)
This routine is the interrupt handler for the CAN driver.
This handler reads the interrupt status from the ISR, determines the source of the interrupts, calls according callbacks, and finally clears the interrupts.Application beyond this driver is responsible for providing callbacks to handle interrupts and installing the callbacks using XCanPs_SetHandler() during initialization phase. An example delivered with this driver demonstrates how this could be done. InstancePtr is a pointer to the XCanPs instance that just interrupted. None. None.
References XCanPs::ErrorHandler, XCanPs::ErrorRef, XCanPs::EventHandler, XCanPs::EventRef, XCanPs::IsReady, XCanPs::RecvHandler, XCanPs::RecvRef, XCanPs::SendHandler, XCanPs::SendRef, XCanPs_ClearBusErrorStatus, XCanPs_GetBusErrorStatus, XCanPs_IntrClear, XCanPs_IntrGetEnabled, XCanPs_IntrGetStatus, XCANPS_IXR_ARBLST_MASK, XCANPS_IXR_BSOFF_MASK, XCANPS_IXR_ERROR_MASK, XCANPS_IXR_RXFWMFLL_MASK, XCANPS_IXR_RXNEMP_MASK, XCANPS_IXR_RXOFLW_MASK, XCANPS_IXR_RXUFLW_MASK, XCANPS_IXR_SLP_MASK, XCANPS_IXR_TXBFLL_MASK, XCANPS_IXR_TXFLL_MASK, XCANPS_IXR_TXFWMEMP_MASK, XCANPS_IXR_TXOK_MASK, XCANPS_IXR_WKUP_MASK.
Referenced by CanPsIntrExample, CanPsWatermarkIntrExample.
s32 XCanPs_SetHandler(XCanPs *InstancePtr, u32 HandlerType, void *CallBackFunc, void *CallBackRef)
This routine installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function Type ----------------------- ------------------------ XCANPS_HANDLER_SEND XCanPs_SendRecvHandler XCANPS_HANDLER_RECV XCanPs_SendRecvHandler XCANPS_HANDLER_ERROR XCanPs_ErrorHandler XCANPS_HANDLER_EVENT XCanPs_EventHandlerHandlerType Invoked by this driver when: ------------------------------------------------------------------------- XCANPS_HANDLER_SEND A frame transmitted by a call to XCanPs_Send() has been sent successfully.XCANPS_HANDLER_RECV A frame(s) has been received and is sitting in the RX FIFO.XCANPS_HANDLER_ERROR An error interrupt is occurring.XCANPS_HANDLER_EVENT Any other kind of interrupt is occurring. InstancePtr is a pointer to the XCanPs instance. HandlerType specifies which handler is to be attached. CallBackFunc is the address of the callback function. CallBackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS when handler is installed.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XCanPs::ErrorHandler, XCanPs::ErrorRef, XCanPs::EventHandler, XCanPs::EventRef, XCanPs::IsReady, XCanPs::RecvHandler, XCanPs::RecvRef, XCanPs::SendHandler, XCanPs::SendRef, XCANPS_HANDLER_ERROR, XCANPS_HANDLER_EVENT, XCANPS_HANDLER_RECV, XCANPS_HANDLER_SEND.
Referenced by CanPsIntrExample, CanPsWatermarkIntrExample.