xcanps_sinit.c
XCanPs_Config * XCanPs_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XCanPs_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xcanps.h for the definition of XCanPs_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XCanPs_Config::Name, XCanPs_ConfigTable.
Referenced by CanPsIntrExample, CanPsPolledExample, CanPsWatermarkIntrExample.