xcanps_selftest.c
XCANPS_MAX_FRAME_SIZE_IN_WORDS
Flag for Max Frame size.
Referenced by XCanPs_SelfTest.
FRAME_DATA_LENGTH
Frame Data field length.
u32 TxFrame[XCANPS_MAX_FRAME_SIZE_IN_WORDS][XCANPS_MAX_FRAME_SIZE_IN_WORDS]
Buffers to hold frames to send and receive.
These are declared as global so that they are not on the stack.Txframe buffer
u32 RxFrame[XCANPS_MAX_FRAME_SIZE_IN_WORDS][XCANPS_MAX_FRAME_SIZE_IN_WORDS]
Rxframe buffer.
s32 XCanPs_SelfTest(XCanPs *InstancePtr)
This function runs a self-test on the CAN driver/device.
The test resets the device, sets up the Loop Back mode, sends a standard frame, receives the frame, verifies the contents, and resets the device again.Note that this is a destructive test in that resets of the device are performed. Refer the device specification for the device status after the reset operation. InstancePtr is a pointer to the XCanPs instance. XST_SUCCESS if the self-test passed. i.e., the frame received via the internal loop back has the same contents as the frame sent. XST_FAILURE Otherwise. If the CAN device does not work properly, this function may enter an infinite loop and will never return to the caller. If XST_FAILURE is returned, the device is not reset so that the caller could have a chance to check reason(s) causing the failure.
References XCanPs::IsReady, XCanPs_CreateDlcValue, XCanPs_CreateIdValue, XCANPS_DLCR_TIMESTAMP_MASK, XCanPs_EnterMode, XCanPs_GetMode, XCANPS_ISR_OFFSET, XCANPS_IXR_RXNEMP_MASK, XCANPS_MAX_FRAME_SIZE_IN_WORDS, XCANPS_MODE_CONFIG, XCANPS_MODE_LOOPBACK, XCanPs_ReadReg, XCanPs_Recv, XCanPs_Reset, XCanPs_Send, XCanPs_SetBaudRatePrescaler, XCanPs_SetBitTiming.
Referenced by CanPsIntrExample, CanPsPolledExample, CanPsWatermarkIntrExample.