
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version:
* DO NOT EDIT.
*
* Copyright (C) 2010-2019 Xilinx, Inc. All Rights Reserved.*
*Permission is hereby granted, free of charge, to any person obtaining a copy
*of this software and associated documentation files (the Software), to deal
*in the Software without restriction, including without limitation the rights
*to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
*copies of the Software, and to permit persons to whom the Software is
*furnished to do so, subject to the following conditions:
*
*The above copyright notice and this permission notice shall be included in
*all copies or substantial portions of the Software.
*
*THE SOFTWARE IS PROVIDED AS IS, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
*IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
*FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
*THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
*LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
*OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
*SOFTWARE.
*
*
*

*
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xdmapcie.h"

/*
* The configuration table for devices
*/

XDmaPcie_Config XDmaPcie_ConfigTable[XPAR_XDMAPCIE_NUM_INSTANCES] =
{
	{
		XPAR_XDMA_0_DEVICE_ID,
		XPAR_XDMA_0_BASEADDR,
		XPAR_XDMA_0_AXIBAR_NUM,
		XPAR_XDMA_0_INCLUDE_BAROFFSET_REG,
		XPAR_XDMA_0_INCLUDE_RC,
		XPAR_XDMA_0_BASEADDR,
		XPAR_XDMA_0_AXIBAR_0,
		XPAR_XDMA_0_AXIBAR_1,
		XPAR_XDMA_0_AXIBAR_HIGHADDR_0,
		XPAR_XDMA_0_AXIBAR_HIGHADDR_1
	}
};
