axipcie
XAXIPCIE_PCIE_CORE_OFFSET
PCI Express hard core configuration register offset.
Referenced by XAxiPcie_ReadLocalConfigSpace, XAxiPcie_WriteLocalConfigSpace.
XAXIPCIE_VSECC_OFFSET
VSEC Capability Register.
Referenced by XAxiPcie_GetVsecCapability.
XAXIPCIE_VSECH_OFFSET
VSEC Header Register.
Referenced by XAxiPcie_GetVsecHeader.
XAXIPCIE_BI_OFFSET
Bridge Info Register.
Referenced by XAxiPcie_CfgInitialize, XAxiPcie_GetBridgeInfo.
XAXIPCIE_BSC_OFFSET
Bridge Status and Control Register.
Referenced by XAxiPcie_DisableGlobalInterrupt, XAxiPcie_EnableGlobalInterrupt.
XAXIPCIE_ID_OFFSET
Interrupt Decode Register.
Referenced by XAxiPcie_ClearPendingInterrupts, XAxiPcie_GetPendingInterrupts.
XAXIPCIE_IM_OFFSET
Interrupt Mask Register.
Referenced by XAxiPcie_DisableInterrupts, XAxiPcie_EnableInterrupts, XAxiPcie_GetEnabledInterrupts.
XAXIPCIE_BL_OFFSET
Bus Location Register.
Referenced by XAxiPcie_GetRequesterId.
XAXIPCIE_PHYSC_OFFSET
Physical status and Control Register.
Referenced by XAxiPcie_GetPhyStatusCtrl.
XAXIPCIE_RPSC_OFFSET
Root Port Status & Control Register.
Referenced by XAxiPcie_GetRootPortStatusCtrl, XAxiPcie_SetRootPortStatusCtrl.
XAXIPCIE_RPMSIB_UPPER_OFFSET
Root Port MSI Base 1 Register Upper 32 bits from 64 bit address are written.
Referenced by XAxiPcie_SetRootPortMSIBase.
XAXIPCIE_RPMSIB_LOWER_OFFSET
Root Port MSI Base 2 Register Lower 32 bits from 64 bit address are written.
Referenced by XAxiPcie_SetRootPortMSIBase.
XAXIPCIE_RPEFR_OFFSET
Root Port Error FIFO Read Register.
Referenced by XAxiPcie_ClearRootPortErrFIFOMsg, XAxiPcie_GetRootPortErrFIFOMsg.
XAXIPCIE_RPIFR1_OFFSET
Root Port Interrupt FIFO Read1 Register.
Referenced by XAxiPcie_ClearRootPortIntFIFOReg, XAxiPcie_GetRootPortIntFIFOReg.
XAXIPCIE_RPIFR2_OFFSET
Root Port Interrupt FIFO Read2 Register.
Referenced by XAxiPcie_GetRootPortIntFIFOReg.
XAXIPCIE_AXIBAR2PCIBAR_0U_OFFSET
AXIBAR 2 PCIBAR translation 0 upper 32 bits.
Referenced by XAxiPcie_GetLocalBusBar2PcieBar, XAxiPcie_SetLocalBusBar2PcieBar.
XAXIPCIE_AXIBAR2PCIBAR_0L_OFFSET
AXIBAR to PCIBAR translation 0 lower 32 bits.
Referenced by XAxiPcie_GetLocalBusBar2PcieBar, XAxiPcie_SetLocalBusBar2PcieBar.
XAXIPCIE_AXIBAR2PCIBAR_1U_OFFSET
AXIBAR to PCIBAR translation 1 upper 32 bits.
XAXIPCIE_AXIBAR2PCIBAR_1L_OFFSET
AXIBAR to PCIBAR translation 1 lower 32 bits.
XAXIPCIE_AXIBAR2PCIBAR_2U_OFFSET
AXIBAR to PCIBAR translation 2 upper 32 bits.
XAXIPCIE_AXIBAR2PCIBAR_2L_OFFSET
AXIBAR to PCIBAR translation 2 lower 32 bits.
XAXIPCIE_AXIBAR2PCIBAR_3U_OFFSET
AXIBAR to PCIBAR translation 3 upper 32 bits.
XAXIPCIE_AXIBAR2PCIBAR_3L_OFFSET
AXIBAR to PCIBAR translation 3 lower 32 bits.
XAXIPCIE_AXIBAR2PCIBAR_4U_OFFSET
AXIBAR to PCIBAR translation 4 upper 32 bits.
XAXIPCIE_AXIBAR2PCIBAR_4L_OFFSET
AXIBAR to PCIBAR translation 4 lower 32 bits.
XAXIPCIE_AXIBAR2PCIBAR_5U_OFFSET
AXIBAR to PCIBAR translation 5 upper 32 bits.
XAXIPCIE_AXIBAR2PCIBAR_5L_OFFSET
AXIBAR to PCIBAR translation 5 lower 32 bits.
XAXIPCIE_VSECC_ID_MASK
Vsec capability Id.
Referenced by XAxiPcie_GetVsecCapability.
XAXIPCIE_VSECC_VER_MASK
Version of capability Structure.
Referenced by XAxiPcie_GetVsecCapability.
XAXIPCIE_VSECC_NEXT_MASK
Offset to next capability.
Referenced by XAxiPcie_GetVsecCapability.
XAXIPCIE_VSECC_VER_SHIFT
VSEC Version shift.
Referenced by XAxiPcie_GetVsecCapability.
XAXIPCIE_VSECC_NEXT_SHIFT
Next capability offset shift.
Referenced by XAxiPcie_GetVsecCapability.
XAXIPCIE_VSECH_ID_MASK
Vsec structure Id.
Referenced by XAxiPcie_GetVsecHeader.
XAXIPCIE_VSECH_REV_MASK
Vsec header version.
Referenced by XAxiPcie_GetVsecHeader.
XAXIPCIE_VSECH_LEN_MASK
Length of Vsec capability structure.
Referenced by XAxiPcie_GetVsecHeader.
XAXIPCIE_VSECH_REV_SHIFT
Vsec version shift.
Referenced by XAxiPcie_GetVsecHeader.
XAXIPCIE_VSECH_LEN_SHIFT
Vsec length shift.
Referenced by XAxiPcie_GetVsecHeader.
XAXIPCIE_BI_GEN2_MASK
PCIe Gen2 Speed Support Mask.
Referenced by XAxiPcie_GetBridgeInfo.
XAXIPCIE_BI_RP_MASK
PCIe Root Port Support.
Referenced by XAxiPcie_GetBridgeInfo.
XAXIPCIE_UP_CONFIG_CAPABLE
Up Config Capable.
XAXIPCIE_BI_ECAM_SIZE_MASK
ECAM size.
Referenced by XAxiPcie_CfgInitialize, XAxiPcie_GetBridgeInfo.
XAXIPCIE_BI_RP_SHIFT
PCIe Root Port Shift.
Referenced by XAxiPcie_GetBridgeInfo.
XAXIPCIE_BI_ECAM_SIZE_SHIFT
PCIe ECAM Size Shift.
Referenced by XAxiPcie_CfgInitialize, XAxiPcie_GetBridgeInfo.
XAXIPCIE_BSC_ECAM_BUSY_MASK
ECAM Busy Status.
XAXIPCIE_BSC_GI_MASK
Global Interrupt Disable.
Referenced by XAxiPcie_DisableGlobalInterrupt, XAxiPcie_EnableGlobalInterrupt.
XAXIPCIE_BSC_RW1C_MASK
RW Permissions to RW1C Registers.
XAXIPCIE_BSC_RO_MASK
RW Permissions to RO Registers.
XAXIPCIE_BSC_GI_SHIFT
Global Interrupt Disable Shift.
Referenced by XAxiPcie_DisableGlobalInterrupt, XAxiPcie_EnableGlobalInterrupt.
XAXIPCIE_BSC_RW1C_SHIFT
RW1C Shift.
XAXIPCIE_BSC_RO_SHIFT
RO as RW Shift.
XAXIPCIE_ID_LINK_DOWN_MASK
Link Down Mask.
XAXIPCIE_ID_ECRC_ERR_MASK
Rx Packet CRC failed.
XAXIPCIE_ID_STR_ERR_MASK
Streaming Error Mask.
XAXIPCIE_ID_HOT_RST_MASK
Hot Reset Mask.
XAXIPCIE_ID_CFG_COMPL_STATE_MASK
Cfg Completion Status Mask.
XAXIPCIE_ID_CFG_TIMEOUT_MASK
Cfg timeout Mask.
XAXIPCIE_ID_CORRECTABLE_ERR_MASK
Correctable Error Mask.
XAXIPCIE_ID_NONFATAL_ERR_MASK
Non-Fatal Error Mask.
XAXIPCIE_ID_FATAL_ERR_MASK
Fatal Error Mask.
XAXIPCIE_ID_INTX_INTERRUPT
INTX Interrupt.
XAXIPCIE_ID_MSI_INTERRUPT
MSI Interrupt.
XAXIPCIE_ID_UNSUPP_CMPL_MASK
Slave Unsupported Request Mask.
XAXIPCIE_ID_UNEXP_CMPL_MASK
Slave Unexpected Completion Mask.
XAXIPCIE_ID_CMPL_TIMEOUT_MASK
Slave completion Time Mask.
XAXIPCIE_ID_SLV_EP_MASK
Slave Error Poison Mask.
XAXIPCIE_ID_CMPL_ABT_MASK
Slave completion Abort Mask.
XAXIPCIE_ID_ILL_BURST_MASK
Slave Illegal Burst Mask.
XAXIPCIE_ID_DECODE_ERR_MASK
Master Decode Error Interrupt Mask.
XAXIPCIE_ID_SLAVE_ERR_MASK
Master Slave Error Interrupt Mask.
XAXIPCIE_ID_MASTER_EP_MASK
Master Error Poison Mask.
XAXIPCIE_ID_CLEAR_ALL_MASK
Mask of all Interrupts.
Referenced by PCIeEndPointInitialize, PcieInitRootComplex.
XAXIPCIE_IM_ENABLE_ALL_MASK
Enable All Interrupts.
Referenced by PCIeEndPointInitialize, PcieInitRootComplex.
XAXIPCIE_IM_DISABLE_ALL_MASK
Disable All Interrupts.
Referenced by XAxiPcie_CfgInitialize.
XAXIPCIE_BL_FUNC_MASK
Requester ID Function Number.
Referenced by XAxiPcie_GetRequesterId.
XAXIPCIE_BL_DEV_MASK
Requester ID Device Number.
Referenced by XAxiPcie_GetRequesterId.
XAXIPCIE_BL_BUS_MASK
Requester ID Bus Number.
Referenced by XAxiPcie_GetRequesterId.
XAXIPCIE_BL_PORT_MASK
Requester ID Port Number.
Referenced by XAxiPcie_GetRequesterId.
XAXIPCIE_BL_DEV_SHIFT
Requester ID Device Number Shift Value.
Referenced by XAxiPcie_GetRequesterId.
XAXIPCIE_BL_BUS_SHIFT
Requester ID Bus Number Shift Value.
Referenced by XAxiPcie_GetRequesterId.
XAXIPCIE_BL_PORT_SHIFT
Requester ID Bus Number Shift Value.
Referenced by XAxiPcie_GetRequesterId.
XAXIPCIE_PHYSC_LINK_RATE_MASK
Link Rate.
XAXIPCIE_PHYSC_LINK_WIDTH_MASK
Link Width Mask.
XAXIPCIE_PHYSC_LTSSM_STATE_MASK
LTSSM State Mask.
XAXIPCIE_PHYSC_LANE_REV_MASK
Lane Reversal Mask.
XAXIPCIE_PHYSC_LINK_UP_MASK
Link Up Status Mask.
XAXIPCIE_PHYSC_DLW_MASK
Directed Link Width to change Mask.
XAXIPCIE_PHYSC_DLWS_MASK
Directed Link Width Speed to change Mask.
XAXIPCIE_PHYSC_DLA_MASK
Directed Link Change change to reliability or Autonomus Mask.
XAXIPCIE_PHYSC_DLC_MASK
Directed Link change Mask.
XAXIPCIE_PHYSC_LINK_WIDTH_SHIFT
Link Status Shift.
XAXIPCIE_PHYSC_LTSSM_STATE_SHIFT
LTSSM State Shift.
XAXIPCIE_PHYSC_LANE_REV_SHIFT
Lane Reversal Shift.
XAXIPCIE_PHYSC_LINK_UP_SHIFT
Link Up Status Shift.
XAXIPCIE_PHYSC_DLW_SHIFT
Directed Link Width to change Shift.
XAXIPCIE_PHYSC_DLWS_SHIFT
Directed Link Width Speed to change Shift.
XAXIPCIE_PHYSC_DLA_SHIFT
Directed Link change to reliability or Autonomus Shift.
XAXIPCIE_PHYSC_DLC_SHIFT
Directed Link change Shift.
XAXIPCIE_RPSC_MASK
Root Port Register mask.
Referenced by XAxiPcie_SetRootPortStatusCtrl.
XAXIPCIE_RPSC_BRIDGE_ENABLE_MASK
Bridge Enable Mask.
Referenced by PCIeEnumerateFabric.
XAXIPCIE_RPSC_ERR_FIFO_NOT_EMPTY_MASK
Root Port Error FIFO Not Empty.
XAXIPCIE_RPSC_ERR_FIFO_OVERFLOW_MASK
Root Port Error FIFO Overflow.
XAXIPCIE_RPSC_INT_FIFO_NOT_EMPTY_MASK
Root Port Interrupt FIFO Not Empty.
XAXIPCIE_RPSC_INT_FIFO_OVERFLOW_MASK
Root Port Interrupt FIFO Overflow.
XAXIPCIE_RPSC_COMP_TIMEOUT_MASK
Root Port Completion Timeout.
XAXIPCIE_RPSC_ERR_FIFO_NOT_EMPTY_SHIFT
Root Port Error FIFO Empty Shift.
XAXIPCIE_RPSC_ERR_FIFO_OVERFLOW_SHIFT
Root Port Error FIFO Overflow Shift.
XAXIPCIE_RPSC_INT_FIFO_NOT_EMPTY_SHIFT
Root Port Interrupt FIFO Empty Shift.
XAXIPCIE_RPSC_INT_FIFO_OVERFLOW_SHIFT
Root Port Interrupt FIFO Overflow Shift.
XAXIPCIE_RPSC_COMP_TIMEOUT_SHIFT
Root Port Completion Timeout Shift.
XAXIPCIE_RPMSIB_UPPER_MASK
Upper 32 bits of 64 bit MSI Base Address.
Referenced by XAxiPcie_SetRootPortMSIBase.
XAXIPCIE_RPMSIB_UPPER_SHIFT
XAXIPCIE_RPMSIB_LOWER_MASK
Lower 32 bits of 64 bit MSI Base Address.
Referenced by XAxiPcie_SetRootPortMSIBase.
XAXIPCIE_RPEFR_REQ_ID_MASK
Requester of Error Msg.
Referenced by XAxiPcie_GetRootPortErrFIFOMsg.
XAXIPCIE_RPEFR_ERR_TYPE_MASK
Type of Error.
Referenced by XAxiPcie_GetRootPortErrFIFOMsg.
XAXIPCIE_RPEFR_ERR_VALID_MASK
Error Read Succeeded Status.
Referenced by XAxiPcie_GetRootPortErrFIFOMsg.
XAXIPCIE_RPEFR_ERR_TYPE_SHIFT
Type of Error Shift.
Referenced by XAxiPcie_GetRootPortErrFIFOMsg.
XAXIPCIE_RPEFR_ERR_VALID_SHIFT
Error Read Succeeded Status Shift.
Referenced by XAxiPcie_GetRootPortErrFIFOMsg.
XAXIPCIE_RPIFR1_REQ_ID_MASK
Requester Id of Interrupt Message.
Referenced by XAxiPcie_GetRootPortIntFIFOReg.
XAXIPCIE_RPIFR1_MSI_ADDR_MASK
MSI Address.
Referenced by XAxiPcie_GetRootPortIntFIFOReg.
XAXIPCIE_RPIFR1_INTR_LINE_MASK
Intr Line Mask.
XAXIPCIE_RPIFR1_INTR_ASSERT_MASK
Whether Interrupt INTx is asserted.
XAXIPCIE_RPIFR1_MSIINTR_VALID_MASK
Whether Interrupt is MSI or INTx.
Referenced by XAxiPcie_GetRootPortIntFIFOReg.
XAXIPCIE_RPIFR1_INTR_VALID_MASK
Interrupt Read Succeeded Status.
Referenced by XAxiPcie_GetRootPortIntFIFOReg.
XAXIPCIE_RPIFR1_MSI_ADDR_SHIFT
MSI Address Shift.
Referenced by XAxiPcie_GetRootPortIntFIFOReg.
XAXIPCIE_RPIFR1_MSIINTR_VALID_SHIFT
MSI/INTx Interrupt Shift.
Referenced by XAxiPcie_GetRootPortIntFIFOReg.
XAXIPCIE_RPIFR1_INTR_VALID_SHIFT
Interrupt Read Valid Shift.
Referenced by XAxiPcie_GetRootPortIntFIFOReg.
XAXIPCIE_RPIFR2_MSG_DATA_MASK
Pay Load for MSI Message.
Referenced by XAxiPcie_GetRootPortIntFIFOReg.
XAXIPCIE_ECAM_MASK
Mask of all valid bits.
XAXIPCIE_ECAM_BUS_MASK
Bus Number Mask.
XAXIPCIE_ECAM_DEV_MASK
Device Number Mask.
XAXIPCIE_ECAM_FUN_MASK
Function Number Mask.
XAXIPCIE_ECAM_REG_MASK
Register Number Mask.
XAXIPCIE_ECAM_BYT_MASK
Byte Address Mask.
XAXIPCIE_ECAM_BUS_SHIFT
Bus Number Shift Value.
XAXIPCIE_ECAM_DEV_SHIFT
Device Number Shift Value.
XAXIPCIE_ECAM_FUN_SHIFT
Function Number Shift Value.
XAXIPCIE_ECAM_REG_SHIFT
Register Number Shift Value.
XAXIPCIE_ECAM_BYT_SHIFT
Byte Offset Shift Value.
XAxiPcie_Config XAxiPcie_ConfigTable[][]
XAxiPcie_Config* XAxiPcie_LookupConfig(UINTPTR BaseAddress)
Lookup the device configuration based on the unique device ID.
The table ConfigTable contains the configuration info for each device in the system. DeviceId is the device identifier to lookup. XAxiPcie configuration structure pointer if DeviceID is found.NULL if DeviceID is not found. None
Referenced by PCIeEndPointInitialize, PcieInitRootComplex.
int XAxiPcie_CfgInitialize(XAxiPcie *InstancePtr, XAxiPcie_Config *CfgPtr, UINTPTR EffectiveAddress)
Initialize the XAxiPcie instance provided by the caller based on the given Config structure.
InstancePtr is the XAxiPcie instance to operate on.The memory of the pointer references must be pre-allocated by the caller. CfgPtr is the device configuration structure containing required HW build data. EffectiveAddress is the Physical address of the hardware in a Virtual Memory operating system environment.It is the Base Address in a stand alone environment. - XST_SUCCESS Initialization was successful. None.
References XAxiPcie_Config::BaseAddress, XAxiPcie::Config, XAxiPcie::IsReady, XAxiPcie::MaxNumOfBuses, XAXIPCIE_BI_ECAM_SIZE_MASK, XAXIPCIE_BI_ECAM_SIZE_SHIFT, XAXIPCIE_BI_OFFSET, XAxiPcie_DisableInterrupts, XAXIPCIE_IM_DISABLE_ALL_MASK, XAxiPcie_ReadReg.
Referenced by PCIeEndPointInitialize, PcieInitRootComplex.
void XAxiPcie_GetVsecCapability(XAxiPcie *InstancePtr, u8 VsecNum, u16 *VsecIdPtr, u8 *VersionPtr, u16 *NextCapPtr)
This API is used to read the VSEC Capability Register.
InstancePtr is the XAxiPcie instance to operate on. VsecNum is a VSEC register number as there are two registers. Possible values are. XAXIPCIE_VSEC1 (0)XAXIPCIE_VSEC2 (1) VsecIdPtr is a pointer to a variable where the driver will pass back the Vendor Specific Enhanced Capability ID. VersionPtr is a pointer to a variable where the driver will . pass back the Version of VSEC. NextCapPtr is a pointer to a variable where the driver will pass back the Next Capability offset. None. None
References XAxiPcie_Config::BaseAddress, XAxiPcie::Config, XAxiPcie::IsReady, XAxiPcie_ReadReg, XAXIPCIE_VSECC_ID_MASK, XAXIPCIE_VSECC_NEXT_MASK, XAXIPCIE_VSECC_NEXT_SHIFT, XAXIPCIE_VSECC_OFFSET, XAXIPCIE_VSECC_VER_MASK, XAXIPCIE_VSECC_VER_SHIFT.
void XAxiPcie_GetVsecHeader(XAxiPcie *InstancePtr, u8 VsecNum, u16 *VsecIdPtr, u8 *RevisionPtr, u16 *LengthPtr)
This API is used to read the VSEC Header Register.
InstancePtr is the XAxiPcie instance to operate on. VsecNum is a VSEC register number as there are two registers. Possible values are. XAXIPCIE_VSEC1 (0)XAXIPCIE_VSEC2 (1) VsecIdPtr is a pointer to a variable where the driver will pass back the VSEC header structure Id. RevisionPtr is a pointer to a variable where the driver will pass back the Revision of VSEC capability Structure. LengthPtr is a pointer to a variable where the driver will pass . back the length of the VSEC capability structure. None. None
References XAxiPcie_Config::BaseAddress, XAxiPcie::Config, XAxiPcie::IsReady, XAxiPcie_ReadReg, XAXIPCIE_VSECH_ID_MASK, XAXIPCIE_VSECH_LEN_MASK, XAXIPCIE_VSECH_LEN_SHIFT, XAXIPCIE_VSECH_OFFSET, XAXIPCIE_VSECH_REV_MASK, XAXIPCIE_VSECH_REV_SHIFT.
void XAxiPcie_GetBridgeInfo(XAxiPcie *InstancePtr, u8 *Gen2Ptr, u8 *RootPortPtr, u8 *ECAMSizePtr)
This API Reads the Bridge info register.
InstancePtr is the XAxiPcie instance to operate on. Gen2Ptr is a pointer to a variable indicating whether underlying PCIe block support PCIe Gen2 Speed. RootPortPtr is a pointer to a variable indication whether underlying PCIe block is root port. ECAMSizePtr is a pointer to a variable where it indicates ECAM size. Value is between 1 to 8. Total address bits dedicated to ECAM is 20 + ECAM size. None. None
References XAxiPcie_Config::BaseAddress, XAxiPcie::Config, XAxiPcie::IsReady, XAXIPCIE_BI_ECAM_SIZE_MASK, XAXIPCIE_BI_ECAM_SIZE_SHIFT, XAXIPCIE_BI_GEN2_MASK, XAXIPCIE_BI_OFFSET, XAXIPCIE_BI_RP_MASK, XAXIPCIE_BI_RP_SHIFT, XAxiPcie_ReadReg.
void XAxiPcie_GetRequesterId(XAxiPcie *InstancePtr, u8 *BusNumPtr, u8 *DevNumPtr, u8 *FunNumPtr, u8 *PortNumPtr)
Read the Bus Location register.
InstancePtr is the XAxiPcie instance to operate on. BusNumPtr is a pointer to a variable where the driver will pass back the bus number of requester ID assigned to IP. DevNumPtr is a pointer to a variable where the driver will pass back the device number of requester ID assigned to IP. FunNumPtr is a pointer to a variable where the driver will pass back the function number of requester ID assigned to IP. PortNumPtr is a pointer to a variable where the driver will pass back the Port number of requester ID assigned to IP. None. None
References XAxiPcie_Config::BaseAddress, XAxiPcie::Config, XAxiPcie::IsReady, XAXIPCIE_BL_BUS_MASK, XAXIPCIE_BL_BUS_SHIFT, XAXIPCIE_BL_DEV_MASK, XAXIPCIE_BL_DEV_SHIFT, XAXIPCIE_BL_FUNC_MASK, XAXIPCIE_BL_OFFSET, XAXIPCIE_BL_PORT_MASK, XAXIPCIE_BL_PORT_SHIFT, XAxiPcie_ReadReg.
Referenced by PCIeEndPointInitialize, PcieInitRootComplex.
void XAxiPcie_GetPhyStatusCtrl(XAxiPcie *InstancePtr, u32 *PhyState)
This API is used to read the Phy Status/Control Register.
InstancePtr is the XAxiPcie instance to operate on. PhyState is a pointer to a variable where the driver will pass back Current physical status. None. None.
References XAxiPcie_Config::BaseAddress, XAxiPcie::Config, XAxiPcie::IsReady, XAXIPCIE_PHYSC_OFFSET, XAxiPcie_ReadReg.
void XAxiPcie_GetRootPortStatusCtrl(XAxiPcie *InstancePtr, u32 *StatusPtr)
Read Root Port Status/Control Register.
InstancePtr is the PCIe component to operate on. StatusPtr is a pointer to a variable where the driver will pass back the root port status. None. This function is valid only when IP is configured as a root complex.
References XAxiPcie_Config::BaseAddress, XAxiPcie::Config, XAxiPcie_Config::IncludeRootComplex, XAxiPcie::IsReady, XAxiPcie_ReadReg, XAXIPCIE_RPSC_OFFSET.
Referenced by PCIeEnumerateFabric.
void XAxiPcie_SetRootPortStatusCtrl(XAxiPcie *InstancePtr, u32 StatusData)
Write Value in Root Port Status/Control Register.
InstancePtr is the PCIe component to operate on. StatusData is data to set. None. This function is valid only when IP is configured as a root complex.
References XAxiPcie_Config::BaseAddress, XAxiPcie::Config, XAxiPcie_Config::IncludeRootComplex, XAxiPcie::IsReady, XAXIPCIE_RPSC_MASK, XAXIPCIE_RPSC_OFFSET, XAxiPcie_WriteReg.
Referenced by PCIeEnumerateFabric.
int XAxiPcie_SetRootPortMSIBase(XAxiPcie *InstancePtr, unsigned long long MsiBase)
Write MSI Base Address to Root Port MSI Base Address Register.
InstancePtr is the PCIe component to operate on. MsiBase is 64 bit base address for MSI.This address should be 4kB aligned always. XST_SUCCESS if success or XST_FAILURE if failure . This function is valid only when IP is configured as a root complex.
References XAxiPcie_Config::BaseAddress, XAxiPcie::Config, XAxiPcie_Config::IncludeRootComplex, XAxiPcie::IsReady, XAXIPCIE_RPMSIB_LOWER_MASK, XAXIPCIE_RPMSIB_LOWER_OFFSET, XAXIPCIE_RPMSIB_UPPER_MASK, XAXIPCIE_RPMSIB_UPPER_OFFSET, XAxiPcie_WriteReg.
void XAxiPcie_GetRootPortErrFIFOMsg(XAxiPcie *InstancePtr, u16 *ReqIdPtr, u8 *ErrType, u8 *ErrValid)
Read Root Port Error FIFO Message.
InstancePtr is the PCIe component to operate on. ReqIdPtr is a variable where the driver will pass back the requester Id of error message. ErrType is a variable where the driver will pass back the type of error message ErrValid is a variable where the driver will pass back the status of read operation of error message. None. This function is valid only when IP is configured as a root complex.
References XAxiPcie_Config::BaseAddress, XAxiPcie::Config, XAxiPcie_Config::IncludeRootComplex, XAxiPcie::IsReady, XAxiPcie_ReadReg, XAXIPCIE_RPEFR_ERR_TYPE_MASK, XAXIPCIE_RPEFR_ERR_TYPE_SHIFT, XAXIPCIE_RPEFR_ERR_VALID_MASK, XAXIPCIE_RPEFR_ERR_VALID_SHIFT, XAXIPCIE_RPEFR_OFFSET, XAXIPCIE_RPEFR_REQ_ID_MASK.
void XAxiPcie_ClearRootPortErrFIFOMsg(XAxiPcie *InstancePtr)
Clear Root Port Error FIFO Message.
InstancePtr is the PCIe component to operate on. None. This function is valid only when IP is configured as a root complex.
References XAxiPcie_Config::BaseAddress, XAxiPcie::Config, XAxiPcie_Config::IncludeRootComplex, XAxiPcie::IsReady, XAXIPCIE_RPEFR_OFFSET, XAxiPcie_WriteReg.
int XAxiPcie_GetRootPortIntFIFOReg(XAxiPcie *InstancePtr, u16 *ReqIdPtr, u16 *MsiAddr, u8 *MsiInt, u8 *IntValid, u16 *MsiMsgData)
Read Root Port Interrupt FIFO message Register 1 & 2.
InstancePtr is the PCIe component to operate on. ReqIdPtr is a variable where the driver will pass back the requester Id of error message. MsiAddr is a variable where the driver will pass back the MSI address for which interrupt message received. MsiInt is a variable where the driver will pass back the type of interrupt message received (MSI/INTx). IntValid is a variable where the driver will pass back the status of read operation of interrupt message. MsiMsgData is a variable where the driver will pass back the MSI data received. MsiMsgData if MSI interrupt is observed or 0 if there is no MSI interrupt. This function is valid only when IP is configured as a root complex.
References XAxiPcie_Config::BaseAddress, XAxiPcie::Config, XAxiPcie_Config::IncludeRootComplex, XAxiPcie::IsReady, XAxiPcie_ReadReg, XAXIPCIE_RPIFR1_INTR_VALID_MASK, XAXIPCIE_RPIFR1_INTR_VALID_SHIFT, XAXIPCIE_RPIFR1_MSI_ADDR_MASK, XAXIPCIE_RPIFR1_MSI_ADDR_SHIFT, XAXIPCIE_RPIFR1_MSIINTR_VALID_MASK, XAXIPCIE_RPIFR1_MSIINTR_VALID_SHIFT, XAXIPCIE_RPIFR1_OFFSET, XAXIPCIE_RPIFR1_REQ_ID_MASK, XAXIPCIE_RPIFR2_MSG_DATA_MASK, XAXIPCIE_RPIFR2_OFFSET.
void XAxiPcie_ClearRootPortIntFIFOReg(XAxiPcie *InstancePtr)
Clear Root Port FIFO Interrupt message Register 1 & 2.
InstancePtr is the PCIe component to operate on None. This function is valid only when IP is configured as a root complex.Clearing any one Interrupt FIFO register clears both registers.
References XAxiPcie_Config::BaseAddress, XAxiPcie::Config, XAxiPcie_Config::IncludeRootComplex, XAxiPcie::IsReady, XAXIPCIE_RPIFR1_OFFSET, XAxiPcie_WriteReg.
void XAxiPcie_GetLocalBusBar2PcieBar(XAxiPcie *InstancePtr, u8 BarNumber, XAxiPcie_BarAddr *BarAddrPtr)
Read PCIe address translation vector that corresponds to one of AXI local bus bars passed by the caller.
InstancePtr is the XAxiPcie instance to operate on. BarNumber is AXI bar number (0 - 5) passed by caller. BarAddrPtr is a pointer to a variable where the driver will . pass back translation vector. None. None.
References XAxiPcie_Config::BaseAddress, XAxiPcie::Config, XAxiPcie_Config::IncludeBarOffsetReg, XAxiPcie_BarAddr::LowerAddr, XAxiPcie_BarAddr::UpperAddr, XAXIPCIE_AXIBAR2PCIBAR_0L_OFFSET, XAXIPCIE_AXIBAR2PCIBAR_0U_OFFSET, XAxiPcie_ReadReg.
Referenced by PcieInitRootComplex.
void XAxiPcie_SetLocalBusBar2PcieBar(XAxiPcie *InstancePtr, u8 BarNumber, XAxiPcie_BarAddr *BarAddrPtr)
Write PCIe address translation vector that corresponds to one of AXI local bus bars passed by the caller.
InstancePtr is the XAxiPcie instance to operate on. BarNumber is AXI bar number (0 - 5) passed by caller. BarAddrPtr is a pointer to a variable where the driver will pass back translation vector. None. None.
References XAxiPcie_Config::BaseAddress, XAxiPcie::Config, XAxiPcie_Config::IncludeBarOffsetReg, XAxiPcie_BarAddr::LowerAddr, XAxiPcie_BarAddr::UpperAddr, XAXIPCIE_AXIBAR2PCIBAR_0L_OFFSET, XAXIPCIE_AXIBAR2PCIBAR_0U_OFFSET, XAxiPcie_WriteReg.
Referenced by PcieInitRootComplex.
void XAxiPcie_ReadLocalConfigSpace(XAxiPcie *InstancePtr, u16 Offset, u32 *DataPtr)
Read 32-bit value from one of this IP own configuration space.
Location is identified by its offset from the beginning of the configuration space. InstancePtr is the XAxiPcie instance to operate on. Offset from beginning of IP own configuration space. DataPtr is a pointer to a variable where the driver will pass back the value read from the specified location. None None
References XAxiPcie_Config::BaseAddress, XAxiPcie::Config, XAxiPcie::IsReady, XAXIPCIE_PCIE_CORE_OFFSET, XAxiPcie_ReadReg.
Referenced by PCIeEndPointInitialize, PcieInitRootComplex.
void XAxiPcie_WriteLocalConfigSpace(XAxiPcie *InstancePtr, u16 Offset, u32 Data)
Write 32-bit value to one of this IP own configuration space.
Location is identified by its offset from the beginning of the configuration space. InstancePtr is the PCIe component to operate on. Offset from beginning of IP own configuration space. Data to be written to the specified location. None This function is valid only when IP is configured as a root complex.
References XAxiPcie_Config::BaseAddress, XAxiPcie::Config, XAxiPcie_Config::IncludeRootComplex, XAxiPcie::IsReady, XAXIPCIE_PCIE_CORE_OFFSET, XAxiPcie_WriteReg.
Referenced by PcieInitRootComplex.
void XAxiPcie_ReadRemoteConfigSpace(XAxiPcie *InstancePtr, u8 Bus, u8 Device, u8 Function, u16 Offset, u32 *DataPtr)
Read 32-bit value from external PCIe Function's configuration space.
External PCIe function is identified by its Requester ID (Bus#, Device#, Function#). Location is identified by its offset from the beginning of the configuration space. InstancePtr is the PCIe component to operate on. Bus is the external PCIe function's Bus number. Device is the external PCIe function's Device number. Function is the external PCIe function's Function number. Offset from beggininng of PCIe function's configuration space. DataPtr is a pointer to a variable where the driver will pass back the value read from the specified location. None This function is valid only when IP is configured as a root complex. The XAxiPcie_ReadLocalConfigSpace API should be used for reading the local config space.
References XAxiPcie_Config::BaseAddress, XAxiPcie::Config, XAxiPcie_Config::IncludeRootComplex, XAxiPcie::IsReady, XAxiPcie::MaxNumOfBuses, XAxiPcie_IsEcamBusy, XAxiPcie_ReadReg.
Referenced by PCIeEnumerateFabric.
void XAxiPcie_WriteRemoteConfigSpace(XAxiPcie *InstancePtr, u8 Bus, u8 Device, u8 Function, u16 Offset, u32 Data)
Write 32-bit value to external PCIe function's configuration space.
External PCIe function is identified by its Requester ID (Bus#, Device#, Function#). Location is identified by its offset from the beginning of the configuration space. InstancePtr is the PCIe component to operate on. Bus is the external PCIe function's Bus number. Device is the external PCIe function's Device number. Function is the external PCIe function's Function number. Offset from beggininng of PCIe function's configuration space. Data to be written to the specified location. None This function is valid only when IP is configured as a root complex. The XAxiPcie_WriteLocalConfigSpace should be used for writing to local config space.
References XAxiPcie_Config::BaseAddress, XAxiPcie::Config, XAxiPcie_Config::IncludeRootComplex, XAxiPcie::IsReady, XAxiPcie::MaxNumOfBuses, XAxiPcie_IsEcamBusy, XAxiPcie_ReadReg, XAxiPcie_WriteReg.
Referenced by PCIeEnumerateFabric.
void XAxiPcie_EnableGlobalInterrupt(XAxiPcie *InstancePtr)
Enable the Global Interrupt.
InstancePtr is the XAxiPcie instance to operate on. None This bit is in the Bridge Status and Control Register.
References XAxiPcie_Config::BaseAddress, XAxiPcie::Config, XAxiPcie::IsReady, XAXIPCIE_BSC_GI_MASK, XAXIPCIE_BSC_GI_SHIFT, XAXIPCIE_BSC_OFFSET, XAxiPcie_ReadReg, XAxiPcie_WriteReg.
void XAxiPcie_DisableGlobalInterrupt(XAxiPcie *InstancePtr)
Disable the Global Interrupt.
InstancePtr is the XAxiPcie instance to operate on. None This bit is in the Bridge Status and Control Register.
References XAxiPcie_Config::BaseAddress, XAxiPcie::Config, XAxiPcie::IsReady, XAXIPCIE_BSC_GI_MASK, XAXIPCIE_BSC_GI_SHIFT, XAXIPCIE_BSC_OFFSET, XAxiPcie_ReadReg, XAxiPcie_WriteReg.
void XAxiPcie_EnableInterrupts(XAxiPcie *InstancePtr, u32 EnableMask)
Enable the IP interrupt bits passed into "EnableMask".
InstancePtr is the XAxiPcie instance to operate on. EnableMask is the bit pattern for interrupts wanted to be enabled. None If an interrupt is already enabled before calling this function, it will stay enabled regardless of the value of "EnableMask" passed from the caller.
References XAxiPcie_Config::BaseAddress, XAxiPcie::Config, XAxiPcie::IsReady, XAXIPCIE_IM_OFFSET, XAxiPcie_ReadReg, XAxiPcie_WriteReg.
void XAxiPcie_DisableInterrupts(XAxiPcie *InstancePtr, u32 DisableMask)
Disable the IP interrupt bits passed into "DisableMask".
InstancePtr is the XAxiPcie instance to operate on. DisableMask is the bit pattern for interrupts wanted to be disabled. None If an interrupt is already disabled before calling this function, it will stay disabled regardless of the value of "DisableMask" passed from the caller.
References XAxiPcie_Config::BaseAddress, XAxiPcie::Config, XAxiPcie::IsReady, XAXIPCIE_IM_OFFSET, XAxiPcie_ReadReg, XAxiPcie_WriteReg.
Referenced by PCIeEndPointInitialize, PcieInitRootComplex, XAxiPcie_CfgInitialize.
void XAxiPcie_GetEnabledInterrupts(XAxiPcie *InstancePtr, u32 *EnabledMaskPtr)
Get the currently enabled interrupt bits of the IP and pass them back to the caller into "EnabledMask".
InstancePtr is the XAxiPcie instance to operate on. EnabledMaskPtr is a pointer to a variable where the driver will pass back the enabled interrupt bits after reading them from IP. None. None.
References XAxiPcie_Config::BaseAddress, XAxiPcie::Config, XAxiPcie::IsReady, XAXIPCIE_IM_OFFSET, XAxiPcie_ReadReg.
Referenced by PCIeEndPointInitialize, PcieInitRootComplex.
void XAxiPcie_GetPendingInterrupts(XAxiPcie *InstancePtr, u32 *PendingMaskPtr)
Get the currently pending interrupt bits of the IP and pass them back to the caller into "PendingMask".
InstancePtr is the XAxiPcie instance to operate on. PendingMaskPtr is a pointer to a variable where the driver will pass back the pending interrupt bits after reading them from IP. None. None.
References XAxiPcie_Config::BaseAddress, XAxiPcie::Config, XAxiPcie::IsReady, XAXIPCIE_ID_OFFSET, XAxiPcie_ReadReg.
Referenced by PCIeEndPointInitialize, PcieInitRootComplex.
void XAxiPcie_ClearPendingInterrupts(XAxiPcie *InstancePtr, u32 ClearMask)
Clear the currently pending interrupt bits of the IP passed from the caller into "ClearMask".
InstancePtr is the XAxiPcie instance to operate on. ClearMask is the bit pattern for pending interrupts wanted to be cleared. None. None.
References XAxiPcie_Config::BaseAddress, XAxiPcie::Config, XAxiPcie::IsReady, XAXIPCIE_ID_OFFSET, XAxiPcie_ReadReg, XAxiPcie_WriteReg.
Referenced by PCIeEndPointInitialize, PcieInitRootComplex.
XAXIPCIE_H
XAXIPCIE_IS_RC
ALIGN_4KB
XAXIPCIE_VSEC1
First VSEC Register.
XAXIPCIE_VSEC2
Second VSEC Register.
XAxiPcie_GetRequestId
XAxiPcie_IsLinkUp
Check whether link is up or not.
InstancePtr is the XAxiPcie instance to operate on. TRUE if link is upFALSE if link is down None
Referenced by PCIeEndPointInitialize, PcieInitRootComplex.
XAxiPcie_IsEcamBusy
Check whether ECAM is busy or not.
InstancePtr is the XAxiPcie instance to operate on. TRUE if ECAM is busyFALSE if ECAM is idel This function is valid only when IP is configured as a root complex
Referenced by XAxiPcie_ReadRemoteConfigSpace, XAxiPcie_WriteRemoteConfigSpace.
XAXIPCIE_HW_H
XAXIPCIE_VSEC2_OFFSET_WRT_VSEC1
XAxiPcie_ReadReg
Macro to read register.
BaseAddress is the base address of the PCIe. RegOffset is the register offset. Value of the register. C-style signature: u32 XAxiPcie_ReadReg(u32 BaseAddress, u32 RegOffset)
Referenced by XAxiPcie_CfgInitialize, XAxiPcie_ClearPendingInterrupts, XAxiPcie_DisableGlobalInterrupt, XAxiPcie_DisableInterrupts, XAxiPcie_EnableGlobalInterrupt, XAxiPcie_EnableInterrupts, XAxiPcie_GetBridgeInfo, XAxiPcie_GetEnabledInterrupts, XAxiPcie_GetLocalBusBar2PcieBar, XAxiPcie_GetPendingInterrupts, XAxiPcie_GetPhyStatusCtrl, XAxiPcie_GetRequesterId, XAxiPcie_GetRootPortErrFIFOMsg, XAxiPcie_GetRootPortIntFIFOReg, XAxiPcie_GetRootPortStatusCtrl, XAxiPcie_GetVsecCapability, XAxiPcie_GetVsecHeader, XAxiPcie_ReadLocalConfigSpace, XAxiPcie_ReadRemoteConfigSpace, XAxiPcie_WriteRemoteConfigSpace.
XAxiPcie_WriteReg
Macro to write register.
BaseAddress is the base address of the PCIe. RegOffset is the register offset. Data is the data to write. None C-style signature: void XAxiPcie_WriteReg(u32 BaseAddress, u32 RegOffset, u32 Data)
Referenced by XAxiPcie_ClearPendingInterrupts, XAxiPcie_ClearRootPortErrFIFOMsg, XAxiPcie_ClearRootPortIntFIFOReg, XAxiPcie_DisableGlobalInterrupt, XAxiPcie_DisableInterrupts, XAxiPcie_EnableGlobalInterrupt, XAxiPcie_EnableInterrupts, XAxiPcie_SetLocalBusBar2PcieBar, XAxiPcie_SetRootPortMSIBase, XAxiPcie_SetRootPortStatusCtrl, XAxiPcie_WriteLocalConfigSpace, XAxiPcie_WriteRemoteConfigSpace.