xaxipcie_intr.c
void XAxiPcie_EnableGlobalInterrupt(XAxiPcie *InstancePtr)
Enable the Global Interrupt.
InstancePtr is the XAxiPcie instance to operate on. None This bit is in the Bridge Status and Control Register.
References XAxiPcie::IsReady, XAxiPcie_ReadReg, XAxiPcie::Config, XAxiPcie_Config::BaseAddress, XAXIPCIE_BSC_OFFSET, XAXIPCIE_BSC_GI_MASK, XAXIPCIE_BSC_GI_SHIFT, XAxiPcie_WriteReg.
void XAxiPcie_DisableGlobalInterrupt(XAxiPcie *InstancePtr)
Disable the Global Interrupt.
InstancePtr is the XAxiPcie instance to operate on. None This bit is in the Bridge Status and Control Register.
References XAxiPcie::IsReady, XAxiPcie_ReadReg, XAxiPcie::Config, XAxiPcie_Config::BaseAddress, XAXIPCIE_BSC_OFFSET, XAXIPCIE_BSC_GI_MASK, XAXIPCIE_BSC_GI_SHIFT, XAxiPcie_WriteReg.
void XAxiPcie_EnableInterrupts(XAxiPcie *InstancePtr, u32 EnableMask)
Enable the IP interrupt bits passed into "EnableMask".
InstancePtr is the XAxiPcie instance to operate on. EnableMask is the bit pattern for interrupts wanted to be enabled. None If an interrupt is already enabled before calling this function, it will stay enabled regardless of the value of "EnableMask" passed from the caller.
References XAxiPcie::IsReady, XAxiPcie_ReadReg, XAxiPcie::Config, XAxiPcie_Config::BaseAddress, XAXIPCIE_IM_OFFSET, XAxiPcie_WriteReg.
void XAxiPcie_DisableInterrupts(XAxiPcie *InstancePtr, u32 DisableMask)
Disable the IP interrupt bits passed into "DisableMask".
InstancePtr is the XAxiPcie instance to operate on. DisableMask is the bit pattern for interrupts wanted to be disabled. None If an interrupt is already disabled before calling this function, it will stay disabled regardless of the value of "DisableMask" passed from the caller.
References XAxiPcie::IsReady, XAxiPcie_ReadReg, XAxiPcie::Config, XAxiPcie_Config::BaseAddress, XAXIPCIE_IM_OFFSET, XAxiPcie_WriteReg.
Referenced by XAxiPcie_CfgInitialize, PCIeEndPointInitialize, PcieInitRootComplex.
void XAxiPcie_GetEnabledInterrupts(XAxiPcie *InstancePtr, u32 *EnabledMaskPtr)
Get the currently enabled interrupt bits of the IP and pass them back to the caller into "EnabledMask".
InstancePtr is the XAxiPcie instance to operate on. EnabledMaskPtr is a pointer to a variable where the driver will pass back the enabled interrupt bits after reading them from IP. None. None.
References XAxiPcie::IsReady, XAxiPcie_ReadReg, XAxiPcie::Config, XAxiPcie_Config::BaseAddress, XAXIPCIE_IM_OFFSET.
Referenced by PCIeEndPointInitialize, PcieInitRootComplex.
void XAxiPcie_GetPendingInterrupts(XAxiPcie *InstancePtr, u32 *PendingMaskPtr)
Get the currently pending interrupt bits of the IP and pass them back to the caller into "PendingMask".
InstancePtr is the XAxiPcie instance to operate on. PendingMaskPtr is a pointer to a variable where the driver will pass back the pending interrupt bits after reading them from IP. None. None.
References XAxiPcie::IsReady, XAxiPcie_ReadReg, XAxiPcie::Config, XAxiPcie_Config::BaseAddress, XAXIPCIE_ID_OFFSET.
Referenced by PCIeEndPointInitialize, PcieInitRootComplex.
void XAxiPcie_ClearPendingInterrupts(XAxiPcie *InstancePtr, u32 ClearMask)
Clear the currently pending interrupt bits of the IP passed from the caller into "ClearMask".
InstancePtr is the XAxiPcie instance to operate on. ClearMask is the bit pattern for pending interrupts wanted to be cleared. None. None.
References XAxiPcie::IsReady, XAxiPcie_WriteReg, XAxiPcie::Config, XAxiPcie_Config::BaseAddress, XAXIPCIE_ID_OFFSET, XAxiPcie_ReadReg.
Referenced by PCIeEndPointInitialize, PcieInitRootComplex.