llfifo
XLLF_ISR_OFFSET
Interrupt Status.
XLLF_IER_OFFSET
Interrupt Enable.
XLLF_TDFR_OFFSET
Transmit Reset.
XLLF_TDFV_OFFSET
Transmit Vacancy.
Referenced by XLlFifo_iTxVacancy.
XLLF_TDFD_OFFSET
Transmit Data.
Referenced by XLlFifo_TxPutWord.
XLLF_AXI4_TDFD_OFFSET
Axi4 Transmit Data.
Referenced by XLlFifo_TxPutWord.
XLLF_TLF_OFFSET
Transmit Length.
Referenced by XLlFifo_iTxSetLen.
XLLF_RDFR_OFFSET
Receive Reset.
XLLF_RDFO_OFFSET
Receive Occupancy.
Referenced by XLlFifo_iRxOccupancy.
XLLF_RDFD_OFFSET
Receive Data.
Referenced by XLlFifo_RxGetWord.
XLLF_AXI4_RDFD_OFFSET
Axi4 Receive Data.
Referenced by XLlFifo_RxGetWord.
XLLF_RLF_OFFSET
Receive Length.
Referenced by XLlFifo_iRxGetLen.
XLLF_LLR_OFFSET
Local Link Reset.
Referenced by XLlFifo_CfgInitialize, XLlFifo_Initialize.
XLLF_TDR_OFFSET
Transmit Destination.
XLLF_RDR_OFFSET
Receive Destination.
XLLF_INT_RPURE_MASK
Receive under-read.
XLLF_INT_RPORE_MASK
Receive over-read.
XLLF_INT_RPUE_MASK
Receive underrun (empty)
XLLF_INT_TPOE_MASK
Transmit overrun.
XLLF_INT_TC_MASK
Transmit complete.
XLLF_INT_RC_MASK
Receive complete.
XLLF_INT_TSE_MASK
Transmit length mismatch.
XLLF_INT_TRC_MASK
Transmit reset complete.
XLLF_INT_RRC_MASK
Receive reset complete.
XLLF_INT_TFPF_MASK
Tx FIFO Programmable Full, AXI FIFO MM2S Only.
XLLF_INT_TFPE_MASK
Tx FIFO Programmable Empty AXI FIFO MM2S Only.
XLLF_INT_RFPF_MASK
Rx FIFO Programmable Full AXI FIFO MM2S Only.
XLLF_INT_RFPE_MASK
Rx FIFO Programmable Empty AXI FIFO MM2S Only.
XLLF_INT_ALL_MASK
All the ints.
Referenced by XLlFifoInterruptExample.
XLLF_INT_ERROR_MASK
Error status ints.
XLLF_INT_RXERROR_MASK
Receive Error status ints.
XLLF_INT_TXERROR_MASK
Transmit Error status ints.
XLLF_RDFR_RESET_MASK
receive reset value
Referenced by XLlFifo_CfgInitialize, XLlFifo_Initialize.
XLLF_TDFR_RESET_MASK
Transmit reset value.
XLLF_LLR_RESET_MASK
Local Link reset value.
typedef struct XLlFifo XLlFifo
This typedef defines a run-time instance of an XLlFifo device.
typedef struct XLlFifo_Config XLlFifo_Config
typedef int(* XStrm_XferFnType)(void *FifoInstance, void *BufPtr, unsigned WordCount))(void *FifoInstance, void *BufPtr, unsigned WordCount)
typedef u32(* XStrm_GetLenFnType)(void *FifoInstance))(void *FifoInstance)
typedef void(* XStrm_SetLenFnType)(void *FifoInstance, u32 ByteCount))(void *FifoInstance, u32 ByteCount)
typedef u32(* XStrm_GetOccupancyFnType)(void *FifoInstance))(void *FifoInstance)
typedef u32(* XStrm_GetVacancyFnType)(void *FifoInstance))(void *FifoInstance)
typedef struct XStrm_RxFifoStreamer XStrm_RxFifoStreamer
This typedef defines a run-time instance of a receive byte-streamer.
typedef struct XStrm_TxFifoStreamer XStrm_TxFifoStreamer
This typedef defines a run-time instance of a transmit byte-streamer.
XLlFifo_Config XLlFifo_ConfigTable[][]
u32 XLlFifo_iRxOccupancy(XLlFifo *InstancePtr)
XLlFifo_iRxOccupancy returns the number of 32-bit words available (occupancy) to be read from the receive channel of the FIFO, specified by InstancePtr.
InstancePtr references the FIFO on which to operate. XLlFifo_iRxOccupancy returns the occupancy count in 32-bit words for the specified FIFO.
References XLlFifo::BaseAddress, XLLF_RDFO_OFFSET, XLlFifo_ReadReg.
Referenced by XLlFifo_CfgInitialize, XLlFifo_Initialize.
u32 XLlFifo_iRxGetLen(XLlFifo *InstancePtr)
XLlFifo_iRxGetLen notifies the hardware that the program is ready to receive the next frame from the receive channel of the FIFO specified by InstancePtr.
Note that the program must first call XLlFifo_iRxGetLen before pulling data out of the receive channel of the FIFO with XLlFifo_Read. InstancePtr references the FIFO on which to operate. XLlFifo_iRxGetLen returns the number of bytes available in the next frame.
References XLlFifo::BaseAddress, XLLF_RLF_OFFSET, XLlFifo_ReadReg.
Referenced by XLlFifo_CfgInitialize, XLlFifo_Initialize.
int XLlFifo_iRead_Aligned(XLlFifo *InstancePtr, void *BufPtr, unsigned WordCount)
XLlFifo_iRead_Aligned reads, WordCount, words from the FIFO referenced by InstancePtr to the block of memory, referenced by BufPtr.
XLlFifo_iRead_Aligned assumes that BufPtr is already aligned according to the following hardware limitations: ppc - aligned on 32 bit boundaries to avoid performance penalties from unaligned exception handling. microblaze - aligned on 32 bit boundaries as microblaze does not handle unaligned transfers.Care must be taken to ensure that the number of words read with one or more calls to XLlFifo_Read() does not exceed the number of bytes (rounded up to the nearest whole 32 bit word) available given from the last call to XLlFifo_RxGetLen(). InstancePtr references the FIFO on which to operate. BufPtr specifies the memory address to place the data read. WordCount specifies the number of 32 bit words to read. XLlFifo_iRead_Aligned always returns XST_SUCCESS. Error handling is otherwise handled through hardware exceptions and interrupts.
References XLlFifo_RxGetWord.
Referenced by XLlFifo_CfgInitialize, XLlFifo_Initialize.
u32 XLlFifo_iTxVacancy(XLlFifo *InstancePtr)
XLlFifo_iTxVacancy returns the number of unused 32 bit words available (vacancy) in the send channel of the FIFO, specified by InstancePtr.
InstancePtr references the FIFO on which to operate. XLlFifo_iTxVacancy returns the vacancy count in 32-bit words for the specified FIFO.
References XLlFifo::BaseAddress, XLLF_TDFV_OFFSET, XLlFifo_ReadReg.
Referenced by TxSend, XLlFifo_CfgInitialize, XLlFifo_Initialize.
void XLlFifo_iTxSetLen(XLlFifo *InstancePtr, u32 Bytes)
XLlFifo_iTxSetLen begins a hardware transfer of data out of the transmit channel of the FIFO, specified by InstancePtr.
Bytes specifies the number of bytes in the frame to transmit.Note that Bytes (rounded up to the nearest whole 32 bit word) must be same number of words just written using one or more calls to XLlFifo_iWrite_Aligned() InstancePtr references the FIFO on which to operate. Bytes specifies the number of bytes to transmit. N/A
References XLlFifo::BaseAddress, XLLF_TLF_OFFSET, XLlFifo_WriteReg.
Referenced by TxSend, XLlFifo_CfgInitialize, XLlFifo_Initialize.
int XLlFifo_iWrite_Aligned(XLlFifo *InstancePtr, void *BufPtr, unsigned WordCount)
XLlFifo_iWrite_Aligned writes, WordCount, words to the FIFO referenced by InstancePtr from the block of memory, referenced by BufPtr.
XLlFifo_iWrite_Aligned assumes that BufPtr is already aligned according to the following hardware limitations: ppc - aligned on 32 bit boundaries to avoid performance penalties from unaligned exception handling. microblaze - aligned on 32 bit boundaries as microblaze does not handle unaligned transfers.Care must be taken to ensure that the number of words written with one or more calls to XLlFifo_iWrite_Aligned() matches the number of bytes (rounded up to the nearest whole 32 bit word) given in the next call to XLlFifo_iTxSetLen(). InstancePtr references the FIFO on which to operate. BufPtr specifies the memory address to place the data read. WordCount specifies the number of 32 bit words to read. XLlFifo_iWrite_Aligned always returns XST_SUCCESS. Error handling is otherwise handled through hardware exceptions and interrupts. C Signature: int XLlFifo_iWrite_Aligned(XLlFifo *InstancePtr, void *BufPtr, unsigned WordCount);
References XLlFifo_TxPutWord.
Referenced by XLlFifo_CfgInitialize, XLlFifo_Initialize.
int XLlFifo_CfgInitialize(XLlFifo *InstancePtr, XLlFifo_Config *Config, UINTPTR EffectiveAddress)
XLlFifo_CfgInitialize initializes an XPS_ll_Fifo device along with the InstancePtr that references it.
InstancePtr is a pointer to the Axi Streaming FIFO instance to be worked on. Config references the structure holding the hardware configuration for the Axi Streaming FIFO core to initialize. EffectiveAddress is the device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, use Config->BaseAddress for this parameters, passing the physical address instead. N/A
References XLlFifo::Axi4BaseAddress, XLlFifo::BaseAddress, XLlFifo::Datainterface, XLlFifo::IntId, XLlFifo::IntrParent, XLlFifo::IsReady, XLlFifo::RxStreamer, XLlFifo::TxStreamer, XLLF_LLR_OFFSET, XLLF_RDFR_RESET_MASK, XLlFifo_iRead_Aligned, XLlFifo_iRxGetLen, XLlFifo_iRxOccupancy, XLlFifo_iTxSetLen, XLlFifo_iTxVacancy, XLlFifo_iWrite_Aligned, XLlFifo_RxReset, XLlFifo_TxReset, XLlFifo_WriteReg, XStrm_RxInitialize, XStrm_TxInitialize.
Referenced by XLlFifoInterruptExample.
u32 XLlFifo_RxGetWord(XLlFifo *InstancePtr)
XLlFifo_RxGetWord reads one 32 bit word from the FIFO specified by InstancePtr.
XLlFifo_RxGetLen or XLlFifo_iRxGetLen must be called before calling XLlFifo_RxGetWord. Otherwise, the hardware will raise an Over Read Exception. InstancePtr references the FIFO on which to operate. XLlFifo_RxGetWord returns the 32 bit word read from the FIFO. C-style signature: u32 XLlFifo_RxGetWord(XLlFifo *InstancePtr)
References XLlFifo::Datainterface, XLLF_AXI4_RDFD_OFFSET, XLLF_RDFD_OFFSET, XLlFifo_ReadReg.
Referenced by XLlFifo_iRead_Aligned.
void XLlFifo_TxPutWord(XLlFifo *InstancePtr, u32 Word)
XLlFifo_TxPutWord writes the 32 bit word, Word to the FIFO specified by InstancePtr.
InstancePtr references the FIFO on which to operate. Word is the data word to be written to FIFO. N/A C-style signature: void XLlFifo_TxPutWord(XLlFifo *InstancePtr, u32 Word)
References XLlFifo::Datainterface, XLLF_AXI4_TDFD_OFFSET, XLLF_TDFD_OFFSET, XLlFifo_WriteReg.
Referenced by TxSend, XLlFifo_iWrite_Aligned.
void XLlFifo_Initialize(XLlFifo *InstancePtr, UINTPTR BaseAddress)
XLlFifo_Initialize initializes an XPS_ll_Fifo device along with the InstancePtr that references it.
InstancePtr references the memory instance to be associated with the FIFO device upon initialization. BaseAddress is the processor address used to access the base address of the Fifo device. N/A
References XLlFifo::Axi4BaseAddress, XLlFifo::BaseAddress, XLlFifo::IsReady, XLlFifo::RxStreamer, XLlFifo::TxStreamer, XLLF_LLR_OFFSET, XLLF_RDFR_RESET_MASK, XLlFifo_iRead_Aligned, XLlFifo_iRxGetLen, XLlFifo_iRxOccupancy, XLlFifo_iTxSetLen, XLlFifo_iTxVacancy, XLlFifo_iWrite_Aligned, XLlFifo_RxReset, XLlFifo_TxReset, XLlFifo_WriteReg, XStrm_RxInitialize, XStrm_TxInitialize.
XLlFifo_Config * XLlFfio_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XLlFifo_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xllfifo.h for the definition of XLlFifo_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
Referenced by XLlFifoInterruptExample.
void XStrm_RxInitialize(XStrm_RxFifoStreamer *InstancePtr, unsigned FifoWidth, void *FifoInstance, XStrm_XferFnType ReadFn, XStrm_GetLenFnType GetLenFn, XStrm_GetOccupancyFnType GetOccupancyFn)
XStrm_RxInitialize initializes the XStrm_RxFifoStreamer object referenced by InstancePtr.
InstancePtr references the tx streamer on which to operate. FifoWidth specifies the FIFO keyhole size in bytes. FifoInstance references the FIFO driver instance that this streamer object should use to transfer data into the the actual fifo. ReadFn specifies a routine to use to read data from the actual FIFO. It is assumed that this read routine will handle only reads from an aligned buffer. (Otherwise, why are we using this streamer driver?) GetLenFn specifies a routine to use to initiate a receive on the actual FIFO. GetOccupancyFn specifies a routine to use to retrieve the occupancy in the actual FIFO. The true occupancy value needs to come through this streamer driver because it holds some of the bytes. N/A
References XStrm_RxFifoStreamer::FifoInstance, XStrm_RxFifoStreamer::FifoWidth, XStrm_RxFifoStreamer::GetLenFn, XStrm_RxFifoStreamer::GetOccupancyFn, XStrm_RxFifoStreamer::HeadIndex, XStrm_RxFifoStreamer::ReadFn.
Referenced by XLlFifo_CfgInitialize, XLlFifo_Initialize.
void XStrm_TxInitialize(XStrm_TxFifoStreamer *InstancePtr, unsigned FifoWidth, void *FifoInstance, XStrm_XferFnType WriteFn, XStrm_SetLenFnType SetLenFn, XStrm_GetVacancyFnType GetVacancyFn)
XStrm_TxInitialize initializes the XStrm_TxFifoStreamer object referenced by InstancePtr.
InstancePtr references the tx streamer on which to operate. FifoWidth specifies the FIFO keyhole size in bytes. FifoInstance references the FIFO driver instance that this streamer object should use to transfer data into the the actual fifo. WriteFn specifies a routine to use to write data into the actual FIFO. It is assumed that this write routine will handle only writes from an aligned buffer. (Otherwise, why are we using this streamer driver?) SetLenFn specifies a routine to use to initiate a transmit on the actual FIFO. GetVacancyFn specifies a routine to use to retrieve the vacancy in the actual FIFO. The true vacancy value needs to come through this streamer driver because it holds some of the bytes. N/A
References XStrm_TxFifoStreamer::FifoInstance, XStrm_TxFifoStreamer::FifoWidth, XStrm_TxFifoStreamer::GetVacancyFn, XStrm_TxFifoStreamer::SetLenFn, XStrm_TxFifoStreamer::TailIndex, XStrm_TxFifoStreamer::WriteFn.
Referenced by XLlFifo_CfgInitialize, XLlFifo_Initialize.
u32 XStrm_RxGetLen(XStrm_RxFifoStreamer *InstancePtr)
XStrm_RxGetLen notifies the hardware that the program is ready to receive the next frame from the receive channel of the FIFO, specified by InstancePtr.
Note that the program must first call XStrm_RxGetLen before pulling data out of the receive channel of the FIFO with XStrm_Read. InstancePtr references the FIFO on which to operate. XStrm_RxGetLen returns the number of bytes available in the next frame.
References XStrm_RxFifoStreamer::FifoInstance, XStrm_RxFifoStreamer::FifoWidth, XStrm_RxFifoStreamer::FrmByteCnt, XStrm_RxFifoStreamer::GetLenFn, XStrm_RxFifoStreamer::HeadIndex.
void XStrm_Read(XStrm_RxFifoStreamer *InstancePtr, void *BufPtr, unsigned Bytes)
XStrm_Read reads Bytes bytes from the FIFO specified by InstancePtr to the block of memory, referenced by BufPtr.
Care must be taken to ensure that the number of bytes read with one or more calls to XStrm_Read() does not exceed the number of bytes available given from the last call to XStrm_RxGetLen(). InstancePtr references the FIFO on which to operate. BufPtr specifies the memory address to place the data read. Bytes specifies the number of bytes to read. N/A
References XStrm_RxFifoStreamer::FifoInstance, XStrm_RxFifoStreamer::FifoWidth, XStrm_RxFifoStreamer::FrmByteCnt, XStrm_RxFifoStreamer::HeadIndex, XStrm_RxFifoStreamer::ReadFn.
void XStrm_TxSetLen(XStrm_TxFifoStreamer *InstancePtr, u32 Bytes)
XStrm_TxSetLen flushes to the FIFO, specified by InstancePtr, any bytes remaining in internal buffers and begins a hardware transfer of data out of the transmit channel of the FIFO.
Bytes specifies the number of bytes in the frame to transmit. InstancePtr references the FIFO Streamer on which to operate. Bytes specifies the frame length in bytes. N/A
References XStrm_TxFifoStreamer::FifoInstance, XStrm_TxFifoStreamer::TailIndex, XStrm_TxFifoStreamer::WriteFn.
void XStrm_Write(XStrm_TxFifoStreamer *InstancePtr, void *BufPtr, unsigned Bytes)
XStrm_Write writes Bytes bytes of the block of memory, referenced by BufPtr, to the transmit channel of the FIFO referenced by InstancePtr.
Care must be taken to ensure that the number of bytes written with one or more calls to XStrm_Write() matches the number of bytes given in the next call to XStrm_TxSetLen(). InstancePtr references the FIFO on which to operate. BufPtr specifies the memory address of data to write. Bytes specifies the number of bytes to write. N/A
References XStrm_TxFifoStreamer::FifoInstance, XStrm_TxFifoStreamer::FifoWidth, XStrm_TxFifoStreamer::TailIndex, XStrm_TxFifoStreamer::WriteFn.
FIFO_WIDTH_BYTES
XLLFIFO_H
XLlFifo_Reset
XLlFifo_Reset resets both the Tx and Rx channels and the local link interface the FIFO specified by InstancePtr.
XLlFifo_TxReset resets also sends a reset pulse to the downstream device (e.g. TEMAC). XLlFifo_Reset drops any bytes in the FIFO not yet retrieved. XLlFifo_Reset drops any bytes in the FIFO not yet transmitted. InstancePtr references the FIFO on which to operate. N/A C-style signature: void XLlFifo_Reset(XLlFifo *InstancePtr)
XLlFifo_Status
XLlFifo_Status returns a bit mask of the interrupt status register (ISR) for the FIFO specified by InstancePtr.
XLlFifo_Status can be used to query the status of the FIFO without having to have interrupts enabled. InstancePtr references the FIFO on which to operate. XLlFifo_IntStatus returns a bit mask of the status conditions. The mask will be a set of bitwise or'd values from the XLLF_INT_*_MASK preprocessor symbols. C-style signature: u32 XLlFifo_IntStatus(XLlFifo *InstancePtr)
Referenced by XLlFifoInterruptExample.
XLlFifo_IntEnable
XLlFifo_IntEnable enables the interrupts specified in Mask for the FIFO specified by InstancePtr.
The corresponding interrupt for each bit set to 1 in Mask, will be enabled. InstancePtr references the FIFO on which to operate. Mask contains a bit mask of the interrupts to enable. The mask can be formed using a set of bitwise or'd values from the XLLF_INT_*_MASK preprocessor symbols. N/A C-style signature: void XLlFifo_IntEnable(XLlFifo *InstancePtr, u32 Mask)
Referenced by XLlFifoInterruptExample.
XLlFifo_IntDisable
XLlFifo_IntDisable disables the interrupts specified in Mask for the FIFO specified by InstancePtr.
The corresponding interrupt for each bit set to 1 in Mask, will be disabled. In other words, XLlFifo_IntDisable uses the "set a bit to clear it" scheme. InstancePtr references the FIFO on which to operate. Mask contains a bit mask of the interrupts to disable. The mask can be formed using a set of bitwise or'd values from the XLLF_INT_*_MASK preprocessor symbols. N/A C-style signature: void XLlFifo_IntDisable(XLlFifo *InstancePtr, u32 Mask)
XLlFifo_IntPending
XLlFifo_IntPending returns a bit mask of the pending interrupts for the FIFO specified by InstancePtr.
Each bit set to 1 in the return value represents a pending interrupt. InstancePtr references the FIFO on which to operate. XLlFifo_IntPending returns a bit mask of the interrupts that are pending. The mask will be a set of bitwise or'd values from the XLLF_INT_*_MASK preprocessor symbols. C-style signature: u32 XLlFifo_IntPending(XLlFifo *InstancePtr)
XLlFifo_IntClear
XLlFifo_IntClear clears pending interrupts specified in Mask for the FIFO specified by InstancePtr.
The corresponding pending interrupt for each bit set to 1 in Mask, will be cleared. In other words, XLlFifo_IntClear uses the "set a bit to clear it" scheme. InstancePtr references the FIFO on which to operate. Mask contains a bit mask of the pending interrupts to clear. The mask can be formed using a set of bitwise or'd values from the XLLF_INT_*_MASK preprocessor symbols. C-style signature: void XLlFifo_IntClear(XLlFifo *InstancePtr, u32 Mask)
Referenced by XLlFifoInterruptExample.
XLlFifo_RxReset
XLlFifo_RxReset resets the receive channel of the FIFO specified by InstancePtr.
XLlFifo_RxReset drops any bytes in the FIFO not yet retrieved.The calling software may want to test for the completion of the reset by reading the interrupt status (IS) register and testing for the Rx Reset complete (RRC) bit. InstancePtr references the FIFO on which to operate. N/A C-style signature: void XLlFifo_RxReset(XLlFifo *InstancePtr)
Referenced by XLlFifo_CfgInitialize, XLlFifo_Initialize.
XLlFifo_IsRxEmpty
XLlFifo_IsRxEmpty returns true if the receive channel of the FIFO, specified by InstancePtr, is empty.
InstancePtr references the FIFO on which to operate. XLlFifo_IsRxEmpty returns TRUE when the receive channel of the FIFO is empty. Otherwise, XLlFifo_IsRxEmpty returns FALSE. C-style signature: int XLlFifo_IsRxEmpty(XLlFifo *InstancePtr)
XLlFifo_RxOccupancy
XLlFifo_RxOccupancy returns the number of 32-bit words available (occupancy) to be read from the receive channel of the FIFO, specified by InstancePtr.
The xps_ll_fifo core uses the same fifo to store data values and frame length values. Upon initialization, the XLlFifo_RxOccupancy will give the value of 1, which means one length value (a reserved fifo location) and no data values. InstancePtr references the FIFO on which to operate. XLlFifo_RxOccupancy returns the occupancy count for the specified packet FIFO. C Signature: u32 XLlFifo_RxOccupancy(XLlFifo *InstancePtr)
XLlFifo_RxGetLen
XLlFifo_RxGetLen notifies the hardware that the program is ready to receive the next frame from the receive channel of the FIFO, specified by InstancePtr.
Note that the program must first call XLlFifo_RxGetLen before pulling data out of the receive channel of the FIFO with XLlFifo_Read. InstancePtr references the FIFO on which to operate. XLlFifo_RxGetLen returns the number of bytes available in the next frame. C Signature: u32 XLlFifo_RxGetLen(XLlFifo *InstancePtr)
XLlFifo_Read
XLlFifo_Read reads Bytes bytes from the receive channel of the FIFO referenced by InstancePtr to the block of memory, referenced by BufPtr.
Care must be taken to ensure that the number of bytes read with one or more calls to XLlFifo_Read() does not exceed the number of bytes available given from the last call to XLlFifo_RxGetLen(). InstancePtr references the FIFO on which to operate. BufPtr specifies the memory address to place the data read. Bytes specifies the number of bytes to read. N/A Error handling is handled through hardware exceptions and interrupts. C Signature: void XLlFifo_Read(XLlFifo *InstancePtr, void *BufPtr, unsigned Bytes)
XLlFifo_TxReset
XLlFifo_TxReset resets the transmit channel of the FIFO specified by InstancePtr.
XLlFifo_TxReset drops any bytes in the FIFO not yet transmitted.The calling software may want to test for the completion of the reset by reading the interrupt status (IS) register and testing for the Tx Reset complete (TRC) bit. InstancePtr references the FIFO on which to operate. N/A C-style signature: void XLlFifo_TxReset(XLlFifo *InstancePtr)
Referenced by XLlFifo_CfgInitialize, XLlFifo_Initialize.
XLlFifo_IsTxDone
XLlFifo_IsTxDone returns true if the transmission in the transmit channel of the FIFO, specified by InstancePtr, is complete.
XLlFifo_IsTxDone works only if the TC bit in the IS register is cleared before sending a frame. InstancePtr references the FIFO on which to operate. XLlFifo_IsTxDone returns TRUE when the transmit channel of the FIFO is complete. Otherwise, XLlFifo_IsTxDone returns FALSE. C-style signature: int XLlFifo_IsTxDone(XLlFifo *InstancePtr)
XLlFifo_IsRxDone
XLlFifo_IsRxDone returns true if the reception in the receive channel of the FIFO, specified by InstancePtr, is complete.
XLlFifo_IsRxDone works only if the RC bit in the ISR register is cleared before receiving a frame. InstancePtr references the FIFO on which to operate. XLlFifo_IsRxDone returns TRUE when the receive channel of the FIFO is complete. Otherwise, XLlFifo_IsRxDone returns FALSE. C-style signature: int XLlFifo_IsRxDone(XLlFifo *InstancePtr)
XLlFifo_TxVacancy
XLlFifo_TxVacancy returns the number of unused 32 bit words available (vacancy) in the send channel of the FIFO specified by InstancePtr.
The xps_ll_fifo core uses tXLLF_he same fifo to store data values and frame length values. Upon initialization, the XLlFifo_TxVacancy will give the value of FIFO_WIDTH - 1, which means one length value used (a reserved fifo location) and no data values yet present. InstancePtr references the FIFO on which to operate. XLlFifo_TxVacancy returns the vacancy count in 32-bit words for the specified FIFO. C-style signature: u32 XLlFifo_TxVacancy(XLlFifo *InstancePtr)
XLlFifo_TxSetLen
XLlFifo_TxSetLen begins a hardware transfer of Bytes bytes out of the transmit channel of the FIFO specified by InstancePtr.
InstancePtr references the FIFO on which to operate. Bytes specifies the frame length in bytes. N/A C Signature: void XLlFifo_TxSetLen(XLlFifo *InstancePtr, u32 Bytes)
XLlFifo_Write
XLlFifo_Write writes Bytes bytes of the block of memory, referenced by BufPtr, to the transmit channel of the FIFO referenced by InstancePtr.
Care must be taken to ensure that the number of bytes written with one or more calls to XLlFifo_Write() matches the number of bytes given in the next call to XLlFifo_TxSetLen(). InstancePtr references the FIFO on which to operate. BufPtr specifies the memory address of data to write. Bytes specifies the number of bytes to write. N/A Error handling is handled through hardware exceptions and interrupts. C Signature: void XLlFifo_Write(XLlFifo *InstancePtr, void *BufPtr, unsigned Bytes)
XLlFifo_WriteTdr
XLlFifo_WriteTdr writes to the Transmit Destination Register (TDR)
The TDR stores the destination address corresponding to the packet to be transmitted. When presenting a transmit packet to the AXI4-Stream FIFO core the following sequence should be followed Write the destination address into TDR first,Write the packet data to the Transmit Data FIFO nextWrite the length of the packet into the Transmit Length Register. InstancePtr references the FIFO on which to operate. Tdest is the Transmit Destination address to be written to TDR. N/A C Signature: void XLlFifo_WriteTdr(XLlFifo *InstancePtr, u32 Tdest);
XLlFifo_ReadRdr
XLlFifo_ReadTdr returns the contents of the Receive Destination Register(RDR).
The RDR contains destination address corresponding to the valid packet that is received. The RDR should only be read when a receive packet is available for processing (the receive occupancy is not zero). Once the RDR is read, the receive packet data should be read from the receive data FIFO before the RDR is read again. The RDR values are stored in the receive data FIFO by the AXI4-Stream FIFO core with the data of each packet. The RDR value for the subsequent packet to be processed is moved to the RDR when the previous RDR value has been read. InstancePtr references the FIFO on which to operate. The Receive Destination address read from the RDR. C Signature: u32 XLlFifo_ReadRdr(XLlFifo *InstancePtr)
XLLFIFO_HW_H
XLlFifo_reg_name
XLlFifo_print_reg_o
XLlFifo_print_reg_i
XLlFifo_ReadReg
XLlFifo_ReadReg returns the value of the register at the offset, RegOffset, from the memory mapped base address, BaseAddress.
BaseAddress specifies the base address of the device. RegOffset specifies the offset from BaseAddress. XLlFifo_ReadReg returns the value of the specified register. C-style signature: u32 XLlFifo_ReadReg(u32 BaseAddress, u32 RegOffset)
Referenced by XLlFifo_iRxGetLen, XLlFifo_iRxOccupancy, XLlFifo_iTxVacancy, XLlFifo_RxGetWord.
XLlFifo_WriteReg
XLlFifo_WriteReg writes the value, Value, to the register at the offset, RegOffset, from the memory mapped base address, BaseAddress.
BaseAddress specifies the base address of the device. RegOffset specifies the offset from BaseAddress. Value is value to write to the register. N/A C-style signature: void XLlFifo_WriteReg(u32 BaseAddress, u32 RegOffset, u32 Value)
Referenced by XLlFifo_CfgInitialize, XLlFifo_Initialize, XLlFifo_iTxSetLen, XLlFifo_TxPutWord.
min
XSTREAMER_H
LARGEST_FIFO_KEYHOLE_SIZE_WORDS
XStrm_TxVacancy
XStrm_RxOccupancy
XStrm_IsRxInternalEmpty