xllfifo.c
FIFO_WIDTH_BYTES
u32 XLlFifo_iRxOccupancy(XLlFifo *InstancePtr)
XLlFifo_iRxOccupancy returns the number of 32-bit words available (occupancy) to be read from the receive channel of the FIFO, specified by InstancePtr.
InstancePtr references the FIFO on which to operate. XLlFifo_iRxOccupancy returns the occupancy count in 32-bit words for the specified FIFO.
References XLlFifo::BaseAddress, XLLF_RDFO_OFFSET, XLlFifo_ReadReg.
Referenced by XLlFifo_CfgInitialize, XLlFifo_Initialize.
u32 XLlFifo_iRxGetLen(XLlFifo *InstancePtr)
XLlFifo_iRxGetLen notifies the hardware that the program is ready to receive the next frame from the receive channel of the FIFO specified by InstancePtr.
Note that the program must first call XLlFifo_iRxGetLen before pulling data out of the receive channel of the FIFO with XLlFifo_Read. InstancePtr references the FIFO on which to operate. XLlFifo_iRxGetLen returns the number of bytes available in the next frame.
References XLlFifo::BaseAddress, XLLF_RLF_OFFSET, XLlFifo_ReadReg.
Referenced by XLlFifo_CfgInitialize, XLlFifo_Initialize.
int XLlFifo_iRead_Aligned(XLlFifo *InstancePtr, void *BufPtr, unsigned WordCount)
XLlFifo_iRead_Aligned reads, WordCount, words from the FIFO referenced by InstancePtr to the block of memory, referenced by BufPtr.
XLlFifo_iRead_Aligned assumes that BufPtr is already aligned according to the following hardware limitations: ppc - aligned on 32 bit boundaries to avoid performance penalties from unaligned exception handling. microblaze - aligned on 32 bit boundaries as microblaze does not handle unaligned transfers.Care must be taken to ensure that the number of words read with one or more calls to XLlFifo_Read() does not exceed the number of bytes (rounded up to the nearest whole 32 bit word) available given from the last call to XLlFifo_RxGetLen(). InstancePtr references the FIFO on which to operate. BufPtr specifies the memory address to place the data read. WordCount specifies the number of 32 bit words to read. XLlFifo_iRead_Aligned always returns XST_SUCCESS. Error handling is otherwise handled through hardware exceptions and interrupts.
References XLlFifo_RxGetWord.
Referenced by XLlFifo_CfgInitialize, XLlFifo_Initialize.
u32 XLlFifo_iTxVacancy(XLlFifo *InstancePtr)
XLlFifo_iTxVacancy returns the number of unused 32 bit words available (vacancy) in the send channel of the FIFO, specified by InstancePtr.
InstancePtr references the FIFO on which to operate. XLlFifo_iTxVacancy returns the vacancy count in 32-bit words for the specified FIFO.
References XLlFifo::BaseAddress, XLLF_TDFV_OFFSET, XLlFifo_ReadReg.
Referenced by TxSend, XLlFifo_CfgInitialize, XLlFifo_Initialize.
void XLlFifo_iTxSetLen(XLlFifo *InstancePtr, u32 Bytes)
XLlFifo_iTxSetLen begins a hardware transfer of data out of the transmit channel of the FIFO, specified by InstancePtr.
Bytes specifies the number of bytes in the frame to transmit.Note that Bytes (rounded up to the nearest whole 32 bit word) must be same number of words just written using one or more calls to XLlFifo_iWrite_Aligned() InstancePtr references the FIFO on which to operate. Bytes specifies the number of bytes to transmit. N/A
References XLlFifo::BaseAddress, XLLF_TLF_OFFSET, XLlFifo_WriteReg.
Referenced by TxSend, XLlFifo_CfgInitialize, XLlFifo_Initialize.
int XLlFifo_iWrite_Aligned(XLlFifo *InstancePtr, void *BufPtr, unsigned WordCount)
XLlFifo_iWrite_Aligned writes, WordCount, words to the FIFO referenced by InstancePtr from the block of memory, referenced by BufPtr.
XLlFifo_iWrite_Aligned assumes that BufPtr is already aligned according to the following hardware limitations: ppc - aligned on 32 bit boundaries to avoid performance penalties from unaligned exception handling. microblaze - aligned on 32 bit boundaries as microblaze does not handle unaligned transfers.Care must be taken to ensure that the number of words written with one or more calls to XLlFifo_iWrite_Aligned() matches the number of bytes (rounded up to the nearest whole 32 bit word) given in the next call to XLlFifo_iTxSetLen(). InstancePtr references the FIFO on which to operate. BufPtr specifies the memory address to place the data read. WordCount specifies the number of 32 bit words to read. XLlFifo_iWrite_Aligned always returns XST_SUCCESS. Error handling is otherwise handled through hardware exceptions and interrupts. C Signature: int XLlFifo_iWrite_Aligned(XLlFifo *InstancePtr, void *BufPtr, unsigned WordCount);
References XLlFifo_TxPutWord.
Referenced by XLlFifo_CfgInitialize, XLlFifo_Initialize.
int XLlFifo_CfgInitialize(XLlFifo *InstancePtr, XLlFifo_Config *Config, UINTPTR EffectiveAddress)
XLlFifo_CfgInitialize initializes an XPS_ll_Fifo device along with the InstancePtr that references it.
InstancePtr is a pointer to the Axi Streaming FIFO instance to be worked on. Config references the structure holding the hardware configuration for the Axi Streaming FIFO core to initialize. EffectiveAddress is the device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, use Config->BaseAddress for this parameters, passing the physical address instead. N/A
References XLlFifo::Axi4BaseAddress, XLlFifo::BaseAddress, XLlFifo::Datainterface, XLlFifo::IntId, XLlFifo::IntrParent, XLlFifo::IsReady, XLlFifo::RxStreamer, XLlFifo::TxStreamer, XLLF_LLR_OFFSET, XLLF_RDFR_RESET_MASK, XLlFifo_iRead_Aligned, XLlFifo_iRxGetLen, XLlFifo_iRxOccupancy, XLlFifo_iTxSetLen, XLlFifo_iTxVacancy, XLlFifo_iWrite_Aligned, XLlFifo_RxReset, XLlFifo_TxReset, XLlFifo_WriteReg, XStrm_RxInitialize, XStrm_TxInitialize.
Referenced by XLlFifoInterruptExample.
u32 XLlFifo_RxGetWord(XLlFifo *InstancePtr)
XLlFifo_RxGetWord reads one 32 bit word from the FIFO specified by InstancePtr.
XLlFifo_RxGetLen or XLlFifo_iRxGetLen must be called before calling XLlFifo_RxGetWord. Otherwise, the hardware will raise an Over Read Exception. InstancePtr references the FIFO on which to operate. XLlFifo_RxGetWord returns the 32 bit word read from the FIFO. C-style signature: u32 XLlFifo_RxGetWord(XLlFifo *InstancePtr)
References XLlFifo::Datainterface, XLLF_AXI4_RDFD_OFFSET, XLLF_RDFD_OFFSET, XLlFifo_ReadReg.
Referenced by XLlFifo_iRead_Aligned.
void XLlFifo_TxPutWord(XLlFifo *InstancePtr, u32 Word)
XLlFifo_TxPutWord writes the 32 bit word, Word to the FIFO specified by InstancePtr.
InstancePtr references the FIFO on which to operate. Word is the data word to be written to FIFO. N/A C-style signature: void XLlFifo_TxPutWord(XLlFifo *InstancePtr, u32 Word)
References XLlFifo::Datainterface, XLLF_AXI4_TDFD_OFFSET, XLLF_TDFD_OFFSET, XLlFifo_WriteReg.
Referenced by TxSend, XLlFifo_iWrite_Aligned.
void XLlFifo_Initialize(XLlFifo *InstancePtr, UINTPTR BaseAddress)
XLlFifo_Initialize initializes an XPS_ll_Fifo device along with the InstancePtr that references it.
InstancePtr references the memory instance to be associated with the FIFO device upon initialization. BaseAddress is the processor address used to access the base address of the Fifo device. N/A
References XLlFifo::Axi4BaseAddress, XLlFifo::BaseAddress, XLlFifo::IsReady, XLlFifo::RxStreamer, XLlFifo::TxStreamer, XLLF_LLR_OFFSET, XLLF_RDFR_RESET_MASK, XLlFifo_iRead_Aligned, XLlFifo_iRxGetLen, XLlFifo_iRxOccupancy, XLlFifo_iTxSetLen, XLlFifo_iTxVacancy, XLlFifo_iWrite_Aligned, XLlFifo_RxReset, XLlFifo_TxReset, XLlFifo_WriteReg, XStrm_RxInitialize, XStrm_TxInitialize.