xstreamer.h
XSTREAMER_H
LARGEST_FIFO_KEYHOLE_SIZE_WORDS
XStrm_TxVacancy
XStrm_RxOccupancy
XStrm_IsRxInternalEmpty
typedef int(* XStrm_XferFnType)(void *FifoInstance, void *BufPtr, unsigned WordCount))(void *FifoInstance, void *BufPtr, unsigned WordCount)
typedef u32(* XStrm_GetLenFnType)(void *FifoInstance))(void *FifoInstance)
typedef void(* XStrm_SetLenFnType)(void *FifoInstance, u32 ByteCount))(void *FifoInstance, u32 ByteCount)
typedef u32(* XStrm_GetOccupancyFnType)(void *FifoInstance))(void *FifoInstance)
typedef u32(* XStrm_GetVacancyFnType)(void *FifoInstance))(void *FifoInstance)
typedef struct XStrm_RxFifoStreamer XStrm_RxFifoStreamer
This typedef defines a run-time instance of a receive byte-streamer.
typedef struct XStrm_TxFifoStreamer XStrm_TxFifoStreamer
This typedef defines a run-time instance of a transmit byte-streamer.
void XStrm_RxInitialize(XStrm_RxFifoStreamer *InstancePtr, unsigned FifoWidth, void *FifoInstance, XStrm_XferFnType ReadFn, XStrm_GetLenFnType GetLenFn, XStrm_GetOccupancyFnType GetOccupancyFn)
XStrm_RxInitialize initializes the XStrm_RxFifoStreamer object referenced by InstancePtr.
InstancePtr references the tx streamer on which to operate. FifoWidth specifies the FIFO keyhole size in bytes. FifoInstance references the FIFO driver instance that this streamer object should use to transfer data into the the actual fifo. ReadFn specifies a routine to use to read data from the actual FIFO. It is assumed that this read routine will handle only reads from an aligned buffer. (Otherwise, why are we using this streamer driver?) GetLenFn specifies a routine to use to initiate a receive on the actual FIFO. GetOccupancyFn specifies a routine to use to retrieve the occupancy in the actual FIFO. The true occupancy value needs to come through this streamer driver because it holds some of the bytes. N/A
References XStrm_RxFifoStreamer::FifoInstance, XStrm_RxFifoStreamer::FifoWidth, XStrm_RxFifoStreamer::GetLenFn, XStrm_RxFifoStreamer::GetOccupancyFn, XStrm_RxFifoStreamer::HeadIndex, XStrm_RxFifoStreamer::ReadFn.
Referenced by XLlFifo_CfgInitialize, XLlFifo_Initialize.
void XStrm_TxInitialize(XStrm_TxFifoStreamer *InstancePtr, unsigned FifoWidth, void *FifoInstance, XStrm_XferFnType WriteFn, XStrm_SetLenFnType SetLenFn, XStrm_GetVacancyFnType GetVacancyFn)
XStrm_TxInitialize initializes the XStrm_TxFifoStreamer object referenced by InstancePtr.
InstancePtr references the tx streamer on which to operate. FifoWidth specifies the FIFO keyhole size in bytes. FifoInstance references the FIFO driver instance that this streamer object should use to transfer data into the the actual fifo. WriteFn specifies a routine to use to write data into the actual FIFO. It is assumed that this write routine will handle only writes from an aligned buffer. (Otherwise, why are we using this streamer driver?) SetLenFn specifies a routine to use to initiate a transmit on the actual FIFO. GetVacancyFn specifies a routine to use to retrieve the vacancy in the actual FIFO. The true vacancy value needs to come through this streamer driver because it holds some of the bytes. N/A
References XStrm_TxFifoStreamer::FifoInstance, XStrm_TxFifoStreamer::FifoWidth, XStrm_TxFifoStreamer::GetVacancyFn, XStrm_TxFifoStreamer::SetLenFn, XStrm_TxFifoStreamer::TailIndex, XStrm_TxFifoStreamer::WriteFn.
Referenced by XLlFifo_CfgInitialize, XLlFifo_Initialize.
void XStrm_TxSetLen(XStrm_TxFifoStreamer *InstancePtr, u32 Bytes)
XStrm_TxSetLen flushes to the FIFO, specified by InstancePtr, any bytes remaining in internal buffers and begins a hardware transfer of data out of the transmit channel of the FIFO.
Bytes specifies the number of bytes in the frame to transmit. InstancePtr references the FIFO Streamer on which to operate. Bytes specifies the frame length in bytes. N/A
References XStrm_TxFifoStreamer::FifoInstance, XStrm_TxFifoStreamer::TailIndex, XStrm_TxFifoStreamer::WriteFn.
void XStrm_Write(XStrm_TxFifoStreamer *InstancePtr, void *BufPtr, unsigned Bytes)
XStrm_Write writes Bytes bytes of the block of memory, referenced by BufPtr, to the transmit channel of the FIFO referenced by InstancePtr.
Care must be taken to ensure that the number of bytes written with one or more calls to XStrm_Write() matches the number of bytes given in the next call to XStrm_TxSetLen(). InstancePtr references the FIFO on which to operate. BufPtr specifies the memory address of data to write. Bytes specifies the number of bytes to write. N/A
References XStrm_TxFifoStreamer::FifoInstance, XStrm_TxFifoStreamer::FifoWidth, XStrm_TxFifoStreamer::TailIndex, XStrm_TxFifoStreamer::WriteFn.
u32 XStrm_RxGetLen(XStrm_RxFifoStreamer *InstancePtr)
XStrm_RxGetLen notifies the hardware that the program is ready to receive the next frame from the receive channel of the FIFO, specified by InstancePtr.
Note that the program must first call XStrm_RxGetLen before pulling data out of the receive channel of the FIFO with XStrm_Read. InstancePtr references the FIFO on which to operate. XStrm_RxGetLen returns the number of bytes available in the next frame.
References XStrm_RxFifoStreamer::FifoInstance, XStrm_RxFifoStreamer::FifoWidth, XStrm_RxFifoStreamer::FrmByteCnt, XStrm_RxFifoStreamer::GetLenFn, XStrm_RxFifoStreamer::HeadIndex.
void XStrm_Read(XStrm_RxFifoStreamer *InstancePtr, void *BufPtr, unsigned Bytes)
XStrm_Read reads Bytes bytes from the FIFO specified by InstancePtr to the block of memory, referenced by BufPtr.
Care must be taken to ensure that the number of bytes read with one or more calls to XStrm_Read() does not exceed the number of bytes available given from the last call to XStrm_RxGetLen(). InstancePtr references the FIFO on which to operate. BufPtr specifies the memory address to place the data read. Bytes specifies the number of bytes to read. N/A
References XStrm_RxFifoStreamer::FifoInstance, XStrm_RxFifoStreamer::FifoWidth, XStrm_RxFifoStreamer::FrmByteCnt, XStrm_RxFifoStreamer::HeadIndex, XStrm_RxFifoStreamer::ReadFn.