video_common
XVIDC_EDID_HEADER
EDID header field offset.
XVIDC_EDID_VPI_ID_MAN_NAME0
Vendor/product ID manufacturer name byte 0 offset.
Referenced by XVidC_EdidGetManName.
XVIDC_EDID_VPI_ID_MAN_NAME1
Vendor/product ID manufacturer name byte 1 offset.
Referenced by XVidC_EdidGetManName.
XVIDC_EDID_VPI_ID_PROD_CODE_LSB
Vendor/product ID product code LSB offset.
XVIDC_EDID_VPI_ID_PROD_CODE_MSB
Vendor/product ID product code MSB offset.
XVIDC_EDID_VPI_ID_SN0
Vendor/product ID serial number byte 0 offset.
XVIDC_EDID_VPI_ID_SN1
Vendor/product ID serial number byte 1 offset.
XVIDC_EDID_VPI_ID_SN2
Vendor/product ID serial number byte 2 offset.
XVIDC_EDID_VPI_ID_SN3
Vendor/product ID serial number byte 3 offset.
XVIDC_EDID_VPI_WEEK_MAN
Vendor/product ID week of manufacture offset.
XVIDC_EDID_VPI_YEAR
Vendor/product ID year of manufacture/model offset.
XVIDC_EDID_STRUCT_VER
EDID structure version number offset.
XVIDC_EDID_STRUCT_REV
EDID structure revision number offset.
XVIDC_EDID_BDISP_VID
Basic display video input definition offset.
Referenced by XVidC_EdidGetColorDepth.
XVIDC_EDID_BDISP_H_SSAR
Basic display horizontal screen size or aspect ratio offset.
XVIDC_EDID_BDISP_V_SSAR
Basic display vertical screen size or aspect ratio offset.
XVIDC_EDID_BDISP_GAMMA
Basic display gamma offset.
XVIDC_EDID_BDISP_FEATURE
Basic display feature support offset.
XVIDC_EDID_CC_RG_LOW
Color characteristics red/green low bits offset.
Referenced by XVidC_EdidGetCcGreenX, XVidC_EdidGetCcGreenY, XVidC_EdidGetCcRedX, XVidC_EdidGetCcRedY.
XVIDC_EDID_CC_BW_LOW
Color characteristics blue/white low bits offset.
Referenced by XVidC_EdidGetCcBlueX, XVidC_EdidGetCcBlueY, XVidC_EdidGetCcWhiteX, XVidC_EdidGetCcWhiteY.
XVIDC_EDID_CC_REDX_HIGH
Color characteristics red X high bits offset.
Referenced by XVidC_EdidGetCcRedX.
XVIDC_EDID_CC_REDY_HIGH
Color characteristics red Y high bits offset.
Referenced by XVidC_EdidGetCcRedY.
XVIDC_EDID_CC_GREENX_HIGH
Color characteristics green X high bits offset.
Referenced by XVidC_EdidGetCcGreenX.
XVIDC_EDID_EST_TIMINGS_I
Established timings I offset.
XVIDC_EDID_EST_TIMINGS_II
Established timings II offset.
XVIDC_EDID_EST_TIMINGS_MAN
Manufacturer established timings offset.
XVIDC_EDID_STD_TIMINGS_H
Standard timing horizontal resolution offset (N=1-8)
XVIDC_EDID_STD_TIMINGS_AR_FRR
Standard timing aspect ratio and field refresh rate offset (N=1-8)
XVIDC_EDID_18BYTE_DESCRIPTOR
18-byte descriptor block offset (N=1-4)
XVIDC_EDID_PTM
Preferred timing mode offset (first 18-byte descriptor)
XVIDC_EDID_DTD_PTM_PIXEL_CLK_KHZ_LSB
DTD/PTM pixel clock in kHz LSB offset.
XVIDC_EDID_DTD_PTM_PIXEL_CLK_KHZ_MSB
DTD/PTM pixel clock in kHz MSB offset.
XVIDC_EDID_DTD_PTM_HRES_LSB
DTD/PTM horizontal addressable pixels LSB offset.
XVIDC_EDID_DTD_PTM_HBLANK_LSB
DTD/PTM horizontal blanking pixels LSB offset.
XVIDC_EDID_DTD_PTM_HRES_HBLANK_U4
DTD/PTM horizontal res/blanking upper 4 bits offset.
XVIDC_EDID_DTD_PTM_VRES_LSB
DTD/PTM vertical addressable lines LSB offset.
XVIDC_EDID_DTD_PTM_VBLANK_LSB
DTD/PTM vertical blanking lines LSB offset.
XVIDC_EDID_DTD_PTM_VRES_VBLANK_U4
DTD/PTM vertical res/blanking upper 4 bits offset.
XVIDC_EDID_DTD_PTM_HFPORCH_LSB
DTD/PTM horizontal front porch pixels LSB offset.
XVIDC_EDID_DTD_PTM_HSPW_LSB
DTD/PTM horizontal sync pulse width LSB offset.
XVIDC_EDID_DTD_PTM_VFPORCH_VSPW_L4
DTD/PTM vertical front porch and sync pulse width lower 4 bits offset.
XVIDC_EDID_DTD_PTM_XFPORCH_XSPW_U2
DTD/PTM horizontal/vertical front porch and sync pulse width upper 2 bits offset.
XVIDC_EDID_DTD_PTM_HIMGSIZE_MM_LSB
DTD/PTM horizontal display size in mm LSB offset.
XVIDC_EDID_DTD_PTM_VIMGSIZE_MM_LSB
DTD/PTM vertical display size in mm LSB offset.
XVIDC_EDID_DTD_PTM_XIMGSIZE_MM_U4
DTD/PTM horizontal/vertical display size upper 4 bits offset.
XVIDC_EDID_DTD_PTM_HBORDER
DTD/PTM horizontal border pixels offset.
XVIDC_EDID_DTD_PTM_VBORDER
DTD/PTM vertical border lines offset.
XVIDC_EDID_DTD_PTM_SIGNAL
DTD/PTM signal features offset.
XVIDC_EDID_EXT_BLK_COUNT
Extension block count offset.
XVIDC_EDID_CHECKSUM
EDID checksum offset.
XVIDC_EDID_CC_GREENY_HIGH
Color characteristics green Y high bits offset.
Color characteristics green Y high bits offset (duplicate definition)
Referenced by XVidC_EdidGetCcGreenY.
XVIDC_EDID_CC_GREENY_HIGH
Color characteristics green Y high bits offset.
Color characteristics green Y high bits offset (duplicate definition)
XVIDC_EDID_CC_BLUEX_HIGH
Color characteristics blue X high bits offset.
Color characteristics blue X high bits offset (duplicate definition)
Referenced by XVidC_EdidGetCcBlueX.
XVIDC_EDID_CC_BLUEX_HIGH
Color characteristics blue X high bits offset.
Color characteristics blue X high bits offset (duplicate definition)
XVIDC_EDID_CC_BLUEY_HIGH
Color characteristics blue Y high bits offset.
Color characteristics blue Y high bits offset (duplicate definition)
Referenced by XVidC_EdidGetCcBlueY.
XVIDC_EDID_CC_BLUEY_HIGH
Color characteristics blue Y high bits offset.
Color characteristics blue Y high bits offset (duplicate definition)
XVIDC_EDID_CC_WHITEX_HIGH
Color characteristics white X high bits offset.
Color characteristics white point X high bits offset (duplicate definition)
Referenced by XVidC_EdidGetCcWhiteX.
XVIDC_EDID_CC_WHITEX_HIGH
Color characteristics white X high bits offset.
Color characteristics white point X high bits offset (duplicate definition)
XVIDC_EDID_CC_WHITEY_HIGH
Color characteristics white Y high bits offset.
Color characteristics white point Y high bits offset (duplicate definition)
Referenced by XVidC_EdidGetCcWhiteY.
XVIDC_EDID_CC_WHITEY_HIGH
Color characteristics white Y high bits offset.
Color characteristics white point Y high bits offset (duplicate definition)
XVIDC_EDID_VPI_ID_MAN_NAME0_CHAR0_SHIFT
Manufacturer name character 0 bit shift.
Referenced by XVidC_EdidGetManName.
XVIDC_EDID_VPI_ID_MAN_NAME0_CHAR0_MASK
Manufacturer name character 0 bit mask.
Referenced by XVidC_EdidGetManName.
XVIDC_EDID_VPI_ID_MAN_NAME0_CHAR1_MASK
Manufacturer name character 1 low bits mask.
Referenced by XVidC_EdidGetManName.
XVIDC_EDID_VPI_ID_MAN_NAME0_CHAR1_POS
Manufacturer name character 1 bit position.
Referenced by XVidC_EdidGetManName.
XVIDC_EDID_VPI_ID_MAN_NAME1_CHAR1_SHIFT
Manufacturer name character 1 high bits shift.
Referenced by XVidC_EdidGetManName.
XVIDC_EDID_VPI_ID_MAN_NAME1_CHAR2_MASK
Manufacturer name character 2 bit mask.
Referenced by XVidC_EdidGetManName.
XVIDC_EDID_BDISP_VID_VSI_SHIFT
Video signal interface bit shift.
XVIDC_EDID_BDISP_VID_VSI_MASK
Video signal interface bit mask (0=analog, 1=digital)
XVIDC_EDID_BDISP_VID_ANA_SLS_SHIFT
Analog signal level standard bit shift.
XVIDC_EDID_BDISP_VID_ANA_SLS_MASK
Analog signal level standard bit mask.
XVIDC_EDID_BDISP_VID_ANA_SLS_0700_0300_1000
Analog signal level 0.700/0.300/1.000 V.
XVIDC_EDID_BDISP_VID_ANA_SLS_0714_0286_1000
Analog signal level 0.714/0.286/1.000 V.
XVIDC_EDID_BDISP_VID_ANA_SLS_1000_0400_1400
Analog signal level 1.000/0.400/1.400 V.
XVIDC_EDID_BDISP_VID_ANA_SLS_0700_0000_0700
Analog signal level 0.700/0.000/0.700 V.
XVIDC_EDID_BDISP_VID_ANA_VID_SETUP_MASK
Analog blank-to-black setup expected bit mask.
XVIDC_EDID_BDISP_VID_ANA_SEP_SYNC_HV_MASK
Analog separate sync H and V signals supported bit mask.
XVIDC_EDID_BDISP_VID_ANA_COMP_SYNC_H_MASK
Analog composite sync signal on H bit mask.
XVIDC_EDID_BDISP_VID_ANA_COMP_SYNC_G_MASK
Analog composite sync signal on green bit mask.
XVIDC_EDID_BDISP_VID_ANA_SERR_V_SYNC_MASK
Analog serration on V sync pulse bit mask.
XVIDC_EDID_BDISP_VID_DIG_BPC_SHIFT
Digital bits per color bit shift.
Referenced by XVidC_EdidGetColorDepth.
XVIDC_EDID_BDISP_VID_DIG_BPC_MASK
Digital bits per color bit mask.
Referenced by XVidC_EdidGetColorDepth.
XVIDC_EDID_BDISP_VID_DIG_BPC_UNDEF
Digital bits per color undefined.
XVIDC_EDID_BDISP_VID_DIG_BPC_6
Digital 6 bits per color.
Referenced by XVidC_EdidGetColorDepth.
XVIDC_EDID_BDISP_VID_DIG_BPC_8
Digital 8 bits per color.
Referenced by XVidC_EdidGetColorDepth.
XVIDC_EDID_BDISP_VID_DIG_BPC_10
Digital 10 bits per color.
Referenced by XVidC_EdidGetColorDepth.
XVIDC_EDID_BDISP_VID_DIG_BPC_12
Digital 12 bits per color.
Referenced by XVidC_EdidGetColorDepth.
XVIDC_EDID_BDISP_VID_DIG_BPC_14
Digital 14 bits per color.
Referenced by XVidC_EdidGetColorDepth.
XVIDC_EDID_BDISP_VID_DIG_BPC_16
Digital 16 bits per color.
Referenced by XVidC_EdidGetColorDepth.
XVIDC_EDID_BDISP_VID_DIG_VIS_MASK
Digital video interface standard bit mask.
XVIDC_EDID_BDISP_VID_DIG_VIS_UNDEF
Digital video interface standard undefined.
XVIDC_EDID_BDISP_VID_DIG_VIS_DVI
Digital video interface standard DVI.
XVIDC_EDID_BDISP_VID_DIG_VIS_HDMIA
Digital video interface standard HDMI-A.
XVIDC_EDID_BDISP_VID_DIG_VIS_HDMIB
Digital video interface standard HDMI-B.
XVIDC_EDID_BDISP_VID_DIG_VIS_MDDI
Digital video interface standard MDDI.
XVIDC_EDID_BDISP_VID_DIG_VIS_DP
Digital video interface standard DisplayPort.
XVIDC_EDID_BDISP_FEATURE_PM_STANDBY_MASK
Feature support standby power management bit mask.
XVIDC_EDID_BDISP_FEATURE_PM_SUSPEND_MASK
Feature support suspend power management bit mask.
XVIDC_EDID_BDISP_FEATURE_PM_OFF_VLP_MASK
Feature support active-off/very low power bit mask.
XVIDC_EDID_BDISP_FEATURE_ANA_COLORTYPE_SHIFT
Feature support analog display color type bit shift.
XVIDC_EDID_BDISP_FEATURE_ANA_COLORTYPE_MASK
Feature support analog display color type bit mask.
XVIDC_EDID_BDISP_FEATURE_ANA_COLORTYPE_MCG
Analog display color type monochrome/grayscale.
XVIDC_EDID_BDISP_FEATURE_ANA_COLORTYPE_RGB
Analog display color type RGB color.
XVIDC_EDID_BDISP_FEATURE_ANA_COLORTYPE_NRGB
Analog display color type non-RGB color.
XVIDC_EDID_BDISP_FEATURE_ANA_COLORTYPE_UNDEF
Analog display color type undefined.
XVIDC_EDID_BDISP_FEATURE_DIG_COLORENC_YCRCB444_MASK
Feature support digital YCrCb 4:4:4 color encoding bit mask.
XVIDC_EDID_BDISP_FEATURE_DIG_COLORENC_YCRCB422_MASK
Feature support digital YCrCb 4:2:2 color encoding bit mask.
XVIDC_EDID_BDISP_FEATURE_SRGB_DEF_MASK
Feature support sRGB is default color space bit mask.
XVIDC_EDID_BDISP_FEATURE_PTM_INC_MASK
Feature support preferred timing mode included bit mask.
XVIDC_EDID_BDISP_FEATURE_CONTFREQ_MASK
Feature support continuous frequency operation bit mask.
XVIDC_EDID_CC_HIGH_SHIFT
Color characteristics high bits shift value.
Referenced by XVidC_EdidGetCcBlueX, XVidC_EdidGetCcBlueY, XVidC_EdidGetCcGreenX, XVidC_EdidGetCcGreenY, XVidC_EdidGetCcRedX, XVidC_EdidGetCcRedY, XVidC_EdidGetCcWhiteX, XVidC_EdidGetCcWhiteY.
XVIDC_EDID_CC_RBX_LOW_SHIFT
Red/Blue X coordinate low bits shift.
Referenced by XVidC_EdidGetCcBlueX, XVidC_EdidGetCcRedX.
XVIDC_EDID_CC_RBY_LOW_SHIFT
Red/Blue Y coordinate low bits shift.
Referenced by XVidC_EdidGetCcBlueY, XVidC_EdidGetCcRedY.
XVIDC_EDID_CC_RBY_LOW_MASK
Red/Blue Y coordinate low bits mask.
Referenced by XVidC_EdidGetCcBlueY, XVidC_EdidGetCcRedY.
XVIDC_EDID_CC_GWX_LOW_SHIFT
Green/White X coordinate low bits shift.
Referenced by XVidC_EdidGetCcGreenX, XVidC_EdidGetCcWhiteX.
XVIDC_EDID_CC_GWX_LOW_MASK
Green/White X coordinate low bits mask.
Referenced by XVidC_EdidGetCcGreenX, XVidC_EdidGetCcWhiteX.
XVIDC_EDID_CC_GWY_LOW_MASK
Green/White Y coordinate low bits mask.
Referenced by XVidC_EdidGetCcGreenY, XVidC_EdidGetCcWhiteY.
XVIDC_EDID_EST_TIMINGS_I_720x400_70_MASK
Established timing: 720x400 @ 70Hz bit mask.
XVIDC_EDID_EST_TIMINGS_I_720x400_88_MASK
Established timing: 720x400 @ 88Hz bit mask.
XVIDC_EDID_EST_TIMINGS_I_640x480_60_MASK
Established timing: 640x480 @ 60Hz bit mask.
XVIDC_EDID_EST_TIMINGS_I_640x480_67_MASK
Established timing: 640x480 @ 67Hz bit mask.
XVIDC_EDID_EST_TIMINGS_I_640x480_72_MASK
Established timing: 640x480 @ 72Hz bit mask.
XVIDC_EDID_EST_TIMINGS_I_640x480_75_MASK
Established timing: 640x480 @ 75Hz bit mask.
XVIDC_EDID_EST_TIMINGS_I_800x600_56_MASK
Established timing: 800x600 @ 56Hz bit mask.
XVIDC_EDID_EST_TIMINGS_I_800x600_60_MASK
Established timing: 800x600 @ 60Hz bit mask.
XVIDC_EDID_EST_TIMINGS_II_800x600_72_MASK
Established timing: 800x600 @ 72Hz bit mask.
XVIDC_EDID_EST_TIMINGS_II_800x600_75_MASK
Established timing: 800x600 @ 75Hz bit mask.
XVIDC_EDID_EST_TIMINGS_II_832x624_75_MASK
Established timing: 832x624 @ 75Hz bit mask.
XVIDC_EDID_EST_TIMINGS_II_1024x768_87_MASK
Established timing: 1024x768 @ 87Hz interlaced bit mask.
XVIDC_EDID_EST_TIMINGS_II_1024x768_60_MASK
Established timing: 1024x768 @ 60Hz bit mask.
XVIDC_EDID_EST_TIMINGS_II_1024x768_70_MASK
Established timing: 1024x768 @ 70Hz bit mask.
XVIDC_EDID_EST_TIMINGS_II_1024x768_75_MASK
Established timing: 1024x768 @ 75Hz bit mask.
XVIDC_EDID_EST_TIMINGS_II_1280x1024_75_MASK
Established timing: 1280x1024 @ 75Hz bit mask.
XVIDC_EDID_EST_TIMINGS_MAN_1152x870_75_MASK
Manufacturer established timing: 1152x870 @ 75Hz bit mask.
XVIDC_EDID_EST_TIMINGS_MAN_MASK
Manufacturer established timings bit mask.
XVIDC_EDID_STD_TIMINGS_AR_SHIFT
Standard timings aspect ratio bit shift.
XVIDC_EDID_STD_TIMINGS_AR_16_10
Standard timing aspect ratio: 16:10.
Referenced by XVidC_EdidGetStdTimingsV.
XVIDC_EDID_STD_TIMINGS_AR_4_3
Standard timing aspect ratio: 4:3.
Referenced by XVidC_EdidGetStdTimingsV.
XVIDC_EDID_STD_TIMINGS_AR_5_4
Standard timing aspect ratio: 5:4.
Referenced by XVidC_EdidGetStdTimingsV.
XVIDC_EDID_STD_TIMINGS_AR_16_9
Standard timing aspect ratio: 16:9.
Referenced by XVidC_EdidGetStdTimingsV.
XVIDC_EDID_STD_TIMINGS_FRR_MASK
Standard timings field refresh rate bit mask.
XVIDC_EDID_DTD_PTM_XRES_XBLANK_U4_XBLANK_MASK
DTD/PTM horizontal/vertical resolution and blanking upper 4 bits: blanking mask.
XVIDC_EDID_DTD_PTM_XRES_XBLANK_U4_XRES_MASK
DTD/PTM horizontal/vertical resolution and blanking upper 4 bits: resolution mask.
XVIDC_EDID_DTD_PTM_XRES_XBLANK_U4_XRES_SHIFT
DTD/PTM horizontal/vertical resolution and blanking upper 4 bits: resolution shift.
XVIDC_EDID_DTD_PTM_VFPORCH_VSPW_L4_VSPW_MASK
DTD/PTM vertical front porch and sync pulse width lower 4 bits: sync pulse width mask.
XVIDC_EDID_DTD_PTM_VFPORCH_VSPW_L4_VFPORCH_MASK
DTD/PTM vertical front porch and sync pulse width lower 4 bits: front porch mask.
XVIDC_EDID_DTD_PTM_VFPORCH_VSPW_L4_VFPORCH_SHIFT
DTD/PTM vertical front porch and sync pulse width lower 4 bits: front porch shift.
XVIDC_EDID_DTD_PTM_XFPORCH_XSPW_U2_HFPORCH_MASK
DTD/PTM horizontal front porch upper 2 bits mask.
XVIDC_EDID_DTD_PTM_XFPORCH_XSPW_U2_HSPW_MASK
DTD/PTM horizontal sync pulse width upper 2 bits mask.
XVIDC_EDID_DTD_PTM_XFPORCH_XSPW_U2_VFPORCH_MASK
DTD/PTM vertical front porch upper 2 bits mask.
XVIDC_EDID_DTD_PTM_XFPORCH_XSPW_U2_VSPW_MASK
DTD/PTM vertical sync pulse width upper 2 bits mask.
XVIDC_EDID_DTD_PTM_XFPORCH_XSPW_U2_HFPORCH_SHIFT
DTD/PTM horizontal front porch upper 2 bits shift.
XVIDC_EDID_DTD_PTM_XFPORCH_XSPW_U2_HSPW_SHIFT
DTD/PTM horizontal sync pulse width upper 2 bits shift.
XVIDC_EDID_DTD_PTM_XFPORCH_XSPW_U2_VFPORCH_SHIFT
DTD/PTM vertical front porch upper 2 bits shift.
XVIDC_EDID_DTD_PTM_XIMGSIZE_MM_U4_VIMGSIZE_MM_MASK
DTD/PTM vertical image size upper 4 bits mask.
XVIDC_EDID_DTD_PTM_XIMGSIZE_MM_U4_HIMGSIZE_MM_MASK
DTD/PTM horizontal image size upper 4 bits mask.
XVIDC_EDID_DTD_PTM_XIMGSIZE_MM_U4_HIMGSIZE_MM_SHIFT
DTD/PTM horizontal image size upper 4 bits shift.
XVIDC_EDID_DTD_PTM_SIGNAL_INTERLACED_MASK
DTD/PTM interlaced bit mask.
XVIDC_EDID_DTD_PTM_SIGNAL_INTERLACED_SHIFT
DTD/PTM interlaced bit shift.
XVIDC_EDID_DTD_PTM_SIGNAL_HPOLARITY_MASK
DTD/PTM horizontal polarity bit mask.
XVIDC_EDID_DTD_PTM_SIGNAL_VPOLARITY_MASK
DTD/PTM vertical polarity bit mask.
XVIDC_EDID_DTD_PTM_SIGNAL_HPOLARITY_SHIFT
DTD/PTM horizontal polarity bit shift.
XVIDC_EDID_DTD_PTM_SIGNAL_VPOLARITY_SHIFT
DTD/PTM vertical polarity bit shift.
XVidC_VideoMode
720x480 @ 60Hz interlaced
XVidC_VideoFormat
Progressive scan.
XVidC_FrameRate
24 Hz refresh rate
XVidC_ColorDepth
6 bits per component
XVidC_PixelsPerClock
1 pixel per clock
XVidC_ColorFormat
RGB streaming format.
XVidC_TileSize
32-byte tile size
XVidC_AspectRatio
4:3 aspect ratio
XVidC_ColorStd
ITU-R BT.2020 color standard.
XVidC_ColorRange
Limited range 16-235.
XVidC_3DFormat
Frame packing.
XVidC_3DSamplingMethod
Horizontal sub-sampling.
XVidC_3DSamplingPosition
Odd/Left, Odd/Right.
XVidC_Eotf
Traditional Gamma SDR.
typedef void(* XVidC_DelayHandler)(void *TimerPtr, u32 Delay))(void *TimerPtr, u32 Delay)
Callback type which represents a custom timer wait handler.
This is only used for Microblaze since it doesn't have a native sleep function. To avoid dependency on a hardware timer, the default wait functionality is implemented using loop iterations; this isn't too accurate. Therefore a custom timer handler is used, the user may implement their own wait implementation. TimerPtr is a pointer to the timer instance. Delay is the duration (msec/usec) to be passed to the timer function.
const XVidC_VideoTimingMode XVidC_VideoTimingModes[XVIDC_VM_NUM_SUPPORTED][XVIDC_VM_NUM_SUPPORTED]
This table contains the main stream attributes for various standard resolutions.
Each entry is of the format: 1) ID: XVIDC_VM_<HRES>x<VRES>_<FRAME RATE (HZ)>_<P|I>(RB = Reduced Blanking) 2) Resolution naming: "<HRES>x<VRES>@<FRAME RATE (HZ)>" 3) Frame rate: XVIDC_FR<FRAME RATE (HZ)> 4) Video timing structure: 1) Horizontal active resolution (pixels) 2) Horizontal front porch (pixels) 3) Horizontal sync width (pixels) 4) Horizontal back porch (pixels) 5) Horizontal total (pixels) 6) Horizontal sync polarity (0=negative|1=positive) 7) Vertical active resolution (lines) 8) Frame 0: Vertical front porch (lines) 9) Frame 0: Vertical sync width (lines) 10) Frame 0: Vertical back porch (lines) 11) Frame 0: Vertical total (lines) 12) Frame 1: Vertical front porch (lines) 13) Frame 1: Vertical sync width (lines) 14) Frame 1: Vertical back porch (lines) 15) Frame 1: Vertical total (lines) 16) Vertical sync polarity (0=negative|1=positive)
Referenced by Edid_PrintSuppVmTable.
const XVidC_VideoTimingMode* XVidC_CustomTimingModes
int XVidC_NumCustomModes
const XVidC_VideoTimingMode XVidC_VideoTimingModes[XVIDC_VM_NUM_SUPPORTED][XVIDC_VM_NUM_SUPPORTED]
This table contains the main stream attributes for various standard resolutions.
Each entry is of the format: 1) ID: XVIDC_VM_<HRES>x<VRES>_<FRAME RATE (HZ)>_<P|I>(RB = Reduced Blanking) 2) Resolution naming: "<HRES>x<VRES>@<FRAME RATE (HZ)>" 3) Frame rate: XVIDC_FR<FRAME RATE (HZ)> 4) Video timing structure: 1) Horizontal active resolution (pixels) 2) Horizontal front porch (pixels) 3) Horizontal sync width (pixels) 4) Horizontal back porch (pixels) 5) Horizontal total (pixels) 6) Horizontal sync polarity (0=negative|1=positive) 7) Vertical active resolution (lines) 8) Frame 0: Vertical front porch (lines) 9) Frame 0: Vertical sync width (lines) 10) Frame 0: Vertical back porch (lines) 11) Frame 0: Vertical total (lines) 12) Frame 1: Vertical front porch (lines) 13) Frame 1: Vertical sync width (lines) 14) Frame 1: Vertical back porch (lines) 15) Frame 1: Vertical total (lines) 16) Vertical sync polarity (0=negative|1=positive)
Referenced by Edid_PrintSuppVmTable.
static const XVidC_VideoTimingMode * XVidC_GetCustomVideoModeData(XVidC_VideoMode VmId)
This function returns the pointer to video mode data at the provided index of the custom video mode table.
VmId specifies the resolution ID. Pointer to XVidC_VideoTimingMode structure based on the given video mode. None.
static u8 XVidC_IsVtmRb(const char *VideoModeStr, u8 RbN)
This function returns whether or not the video timing mode is a reduced blanking mode or not.
VideoModeStr specifies the resolution name string. RbN specifies the type of reduced blanking: 0 = No Reduced Blanking1 = RB2 = RB2 If the reduced blanking type is compatible with the video mode: 0 = Not supported1 = Video mode supports the RB type None.
u32 XVidC_RegisterCustomTimingModes(const XVidC_VideoTimingMode *CustomTable, u16 NumElems)
This function registers a user-defined custom video mode timing table with video_common.
Functions which search the available video modes, or take VmId as an input, will operate on or check the custom video mode timing table in addition to the pre-defined video mode timing table (XVidC_VideoTimingModes). CustomTable is a pointer to the user-defined custom vide mode timing table to register. NumElems is the number of video modes supported by CustomTable. Status code. XST_SUCCESS if the custom table was successfully registered.XST_FAILURE if an existing custom table is already present. IDs in the custom table may not conflict with IDs reserved by the XVidC_VideoMode enum.
References XVIDC_VM_CUSTOM.
void XVidC_UnregisterCustomTimingModes(void)
This function unregisters the user-defined custom video mode timing table previously registered by XVidC_RegisterCustomTimingModes().
None.
u64 XVidC_GetPixelClockHzByHVFr(u32 HTotal, u32 VTotal, u8 FrameRate)
This function calculates pixel clock based on the inputs.
HTotal specifies horizontal total. VTotal specifies vertical total. FrameRate specifies rate at which frames are generated. Pixel clock in Hz. None.
Referenced by XVidC_ReportStreamInfo.
u64 XVidC_GetPixelClockHzByVmId(XVidC_VideoMode VmId)
This function calculates pixel clock from video mode.
VmId specifies the resolution id. Pixel clock in Hz. None.
References XVidC_VideoTiming::F0PVTotal, XVidC_VideoTiming::F1VTotal, XVidC_VideoTimingMode::FrameRate, XVidC_VideoTiming::HTotal, XVidC_VideoTimingMode::Timing, XVidC_GetVideoModeData, XVidC_IsInterlaced.
Referenced by XVidC_ReportStreamInfo.
XVidC_VideoFormat XVidC_GetVideoFormat(XVidC_VideoMode VmId)
This function checks if the input video mode is interlaced/progressive based on its ID from the video timings table.
VmId specifies the resolution ID from the video timings table. Video format. XVIDC_VF_PROGRESSIVEXVIDC_VF_INTERLACED None.
References XVidC_VideoTiming::F1VTotal, XVidC_VideoTimingMode::Timing, XVidC_GetVideoModeData, XVIDC_VF_INTERLACED, XVIDC_VF_PROGRESSIVE, XVIDC_VF_UNKNOWN.
Referenced by XVidC_IsInterlaced.
u8 XVidC_IsInterlaced(XVidC_VideoMode VmId)
This function checks if the input video mode is interlaced based on its ID from the video timings table.
VmId specifies the resolution ID from the video timings table. 1 if the video timing with the supplied table ID is interlaced; 0 if the video timing is progressive. None.
References XVidC_GetVideoFormat, XVIDC_VF_INTERLACED.
Referenced by XVidC_GetPixelClockHzByVmId, XVidC_GetVideoModeIdRb, XVidC_SetVideoStream.
XVidC_VideoMode XVidC_GetVideoModeIdWBlanking(const XVidC_VideoTiming *Timing, u32 FrameRate, u8 IsInterlaced)
This function returns the Video Mode ID that matches the detected input timing, frame rate and I/P flag.
Timing is the pointer to timing parameters to match FrameRate specifies refresh rate in HZ IsInterlaced is flag. 0 = Progressive 1 = Interlaced. Id of a supported video mode. This is an extension of XVidC_GetVideoModeId API to include blanking information in match process. No attempt is made to search for reduced blanking entries, if any.
References XVidC_VideoTiming::F0PVBackPorch, XVidC_VideoTiming::F0PVFrontPorch, XVidC_VideoTiming::F0PVSyncWidth, XVidC_VideoTiming::F0PVTotal, XVidC_VideoTiming::HActive, XVidC_VideoTiming::HBackPorch, XVidC_VideoTiming::HFrontPorch, XVidC_VideoTiming::HSyncWidth, XVidC_VideoTiming::HTotal, XVidC_VideoTiming::VActive, XVidC_GetTimingInfo, XVidC_GetVideoModeId, XVIDC_VM_NOT_SUPPORTED.
XVidC_VideoMode XVidC_GetVideoModeId(u32 Width, u32 Height, u32 FrameRate, u8 IsInterlaced)
This function returns the Video Mode ID that matches the detected input width, height, frame rate and I/P flag.
Width specifies the number pixels per scanline. Height specifies the number of scanline's. FrameRate specifies refresh rate in HZ IsInterlaced is flag. 0 = Progressive1 = Interlaced. Id of a supported video mode. None.
References XVidC_VideoTimingMode::FrameRate, XVidC_VideoTiming::HActive, XVidC_VideoTimingMode::Timing, XVidC_VideoTiming::VActive, XVidC_VideoTimingMode::VmId, XVIDC_VM_INTL_END, XVIDC_VM_INTL_START, XVIDC_VM_NOT_SUPPORTED, XVIDC_VM_PROG_END, XVIDC_VM_PROG_START.
Referenced by XVidC_GetVideoModeIdRb, XVidC_GetVideoModeIdWBlanking.
XVidC_VideoMode XVidC_GetVideoModeIdExtensive(XVidC_VideoTiming *Timing, u32 FrameRate, u8 IsInterlaced, u8 IsExtensive)
This function returns the Video Mode ID that matches the detected input timing, frame rate and I/P flag.
Timing is the pointer to timing parameters to match FrameRate specifies refresh rate in HZ IsInterlaced is flag. 0 = Progressive 1 = Interlaced. IsExtensive is flag. 0 = Basic matching of timing parameters 1 = Extensive matching of timing parameters Id of a supported video mode. This function attempts to search for reduced blanking entries, if any.
References XVidC_VideoTiming::F0PVFrontPorch, XVidC_VideoTiming::F0PVSyncWidth, XVidC_VideoTiming::F0PVTotal, XVidC_VideoTiming::F1VFrontPorch, XVidC_VideoTiming::F1VSyncWidth, XVidC_VideoTiming::F1VTotal, XVidC_VideoTimingMode::FrameRate, XVidC_VideoTiming::HActive, XVidC_VideoTiming::HFrontPorch, XVidC_VideoTiming::HSyncWidth, XVidC_VideoTiming::HTotal, XVidC_VideoTimingMode::Timing, XVidC_VideoTiming::VActive, XVidC_VideoTimingMode::VmId, XVidC_VideoTiming::VSyncPolarity, XVIDC_VM_INTL_END, XVIDC_VM_INTL_START, XVIDC_VM_NOT_SUPPORTED, XVIDC_VM_PROG_END, XVIDC_VM_PROG_START.
XVidC_VideoMode XVidC_GetVideoModeIdRb(u32 Width, u32 Height, u32 FrameRate, u8 IsInterlaced, u8 RbN)
This function returns the video mode ID that matches the detected input width, height, frame rate, interlaced or progressive, and reduced blanking.
Width specifies the number pixels per scanline. Height specifies the number of scanline's. FrameRate specifies refresh rate in HZ IsInterlaced specifies interlaced or progressive mode: 0 = Progressive1 = Interlaced. RbN specifies the type of reduced blanking: 0 = No reduced blanking1 = RB2 = RB2 ID of a supported video mode. None.
References XVidC_VideoTimingMode::FrameRate, XVidC_VideoTiming::HActive, XVidC_VideoTimingMode::Timing, XVidC_VideoTiming::VActive, XVidC_GetVideoModeData, XVidC_GetVideoModeId, XVidC_GetVideoModeStr, XVidC_IsInterlaced, XVIDC_VM_NOT_SUPPORTED.
const XVidC_VideoTimingMode * XVidC_GetVideoModeData(XVidC_VideoMode VmId)
This function returns the pointer to video mode data at index provided.
VmId specifies the resolution id. Pointer to XVidC_VideoTimingMode structure based on the given video mode. None.
References XVIDC_VM_NUM_SUPPORTED.
Referenced by XVidC_GetFrameRate, XVidC_GetFrameRateStr, XVidC_GetPixelClockHzByVmId, XVidC_GetTimingInfo, XVidC_GetVideoFormat, XVidC_GetVideoModeIdRb, XVidC_GetVideoModeStr, XVidC_ReportStreamInfo.
const char * XVidC_GetVideoModeStr(XVidC_VideoMode VmId)
This function returns the resolution name for index specified.
VmId specifies the resolution id. Pointer to a resolution name string. None.
References XVidC_VideoTimingMode::Name, XVidC_GetVideoModeData, XVIDC_VM_CUSTOM.
Referenced by XVidC_GetVideoModeIdRb, XVidC_ReportStreamInfo.
const char * XVidC_GetFrameRateStr(XVidC_VideoMode VmId)
This function returns the frame rate name for index specified.
VmId specifies the resolution id. Pointer to a frame rate name string. None.
References XVidC_VideoTimingMode::FrameRate, XVIDC_FR_100HZ, XVIDC_FR_120HZ, XVIDC_FR_144HZ, XVIDC_FR_200HZ, XVIDC_FR_240HZ, XVIDC_FR_24HZ, XVIDC_FR_25HZ, XVIDC_FR_30HZ, XVIDC_FR_48HZ, XVIDC_FR_50HZ, XVIDC_FR_56HZ, XVIDC_FR_60HZ, XVIDC_FR_65HZ, XVIDC_FR_67HZ, XVIDC_FR_70HZ, XVIDC_FR_72HZ, XVIDC_FR_75HZ, XVIDC_FR_85HZ, XVIDC_FR_87HZ, XVIDC_FR_88HZ, XVIDC_FR_96HZ, XVidC_GetVideoModeData.
Referenced by XVidC_ReportStreamInfo.
const char * XVidC_Get3DFormatStr(XVidC_3DFormat Format)
This function returns a string representation of the enumerated type, XVidC_3DFormat.
Format specifies the value to convert. Pointer to the converted string. None.
References XVIDC_3D_FIELD_ALTERNATIVE, XVIDC_3D_FRAME_PACKING, XVIDC_3D_LINE_ALTERNATIVE, XVIDC_3D_SIDE_BY_SIDE_FULL, XVIDC_3D_SIDE_BY_SIDE_HALF, XVIDC_3D_TOP_AND_BOTTOM_HALF.
Referenced by XVidC_ReportStreamInfo.
const char * XVidC_GetColorFormatStr(XVidC_ColorFormat ColorFormatId)
This function returns the color format name for index specified.
ColorFormatId specifies the index of color format space. Pointer to a color space name string. None.
References XVIDC_CSF_MEM_BGR8, XVIDC_CSF_MEM_BGRA8, XVIDC_CSF_MEM_BGRX8, XVIDC_CSF_MEM_R_G_B8, XVIDC_CSF_MEM_RGB16, XVIDC_CSF_MEM_RGB565, XVIDC_CSF_MEM_RGB8, XVIDC_CSF_MEM_RGBA8, XVIDC_CSF_MEM_RGBX10, XVIDC_CSF_MEM_RGBX12, XVIDC_CSF_MEM_RGBX8, XVIDC_CSF_MEM_UYVY8, XVIDC_CSF_MEM_Y10, XVIDC_CSF_MEM_Y10_L16LE, XVIDC_CSF_MEM_Y10_M16LE, XVIDC_CSF_MEM_Y12, XVIDC_CSF_MEM_Y12_L16LE, XVIDC_CSF_MEM_Y12_M16LE, XVIDC_CSF_MEM_Y16, XVIDC_CSF_MEM_Y8, XVIDC_CSF_MEM_Y_U_V10, XVIDC_CSF_MEM_Y_U_V10_L16LE, XVIDC_CSF_MEM_Y_U_V10_M16LE, XVIDC_CSF_MEM_Y_U_V12, XVIDC_CSF_MEM_Y_U_V12_L16LE, XVIDC_CSF_MEM_Y_U_V12_M16LE, XVIDC_CSF_MEM_Y_U_V8, XVIDC_CSF_MEM_Y_U_V8_420, XVIDC_CSF_MEM_Y_UV10, XVIDC_CSF_MEM_Y_UV10_420, XVIDC_CSF_MEM_Y_UV10_420_L16LE, XVIDC_CSF_MEM_Y_UV10_420_M16LE, XVIDC_CSF_MEM_Y_UV10_L16LE, XVIDC_CSF_MEM_Y_UV10_M16LE, XVIDC_CSF_MEM_Y_UV12, XVIDC_CSF_MEM_Y_UV12_420, XVIDC_CSF_MEM_Y_UV12_420_L16LE, XVIDC_CSF_MEM_Y_UV12_420_M16LE, XVIDC_CSF_MEM_Y_UV12_L16LE, XVIDC_CSF_MEM_Y_UV12_M16LE, XVIDC_CSF_MEM_Y_UV16, XVIDC_CSF_MEM_Y_UV16_420, XVIDC_CSF_MEM_Y_UV8, XVIDC_CSF_MEM_Y_UV8_420, XVIDC_CSF_MEM_YUV16, XVIDC_CSF_MEM_YUV8, XVIDC_CSF_MEM_YUVA8, XVIDC_CSF_MEM_YUVX10, XVIDC_CSF_MEM_YUVX12, XVIDC_CSF_MEM_YUVX8, XVIDC_CSF_MEM_YUYV8, XVIDC_CSF_RGB, XVIDC_CSF_RGBA, XVIDC_CSF_YCBCR_420, XVIDC_CSF_YCBCR_422, XVIDC_CSF_YCBCR_444, XVIDC_CSF_YCRCB_420, XVIDC_CSF_YCRCB_422, XVIDC_CSF_YCRCB_444, XVIDC_CSF_YCRCBA_444, XVIDC_CSF_YONLY.
Referenced by XVidC_ReportStreamInfo.
XVidC_FrameRate XVidC_GetFrameRate(XVidC_VideoMode VmId)
This function returns the frame rate for index specified.
VmId specifies the resolution id. Frame rate in Hz. None.
References XVidC_VideoTimingMode::FrameRate, XVIDC_FR_NUM_SUPPORTED, XVidC_GetVideoModeData.
Referenced by XVidC_SetVideoStream.
const XVidC_VideoTiming * XVidC_GetTimingInfo(XVidC_VideoMode VmId)
This function returns the timing parameters for specified resolution.
VmId specifies the resolution id. Pointer to a XVidC_VideoTiming structure. None.
References XVidC_VideoTimingMode::Timing, XVidC_GetVideoModeData.
Referenced by XVidC_GetVideoModeIdWBlanking, XVidC_SetVideoStream.
u32 XVidC_SetVideoStream(XVidC_VideoStream *VidStrmPtr, XVidC_VideoMode VmId, XVidC_ColorFormat ColorFormat, XVidC_ColorDepth Bpc, XVidC_PixelsPerClock Ppc)
This function sets the VideoStream structure for the specified video format.
VidStrmPtr is a pointer to the XVidC_VideoStream structure to be set. VmId specifies the resolution ID. ColorFormat specifies the color format type. Bpc specifies the color depth/bits per color component. Ppc specifies the pixels per clock. Status code. XST_SUCCESS if the timing for the supplied ID was found.XST_FAILURE, otherwise. None.
References XVidC_VideoStream::ColorDepth, XVidC_VideoStream::ColorFormatId, XVidC_3DInfo::Format, XVidC_VideoStream::FrameRate, XVidC_VideoStream::Info_3D, XVidC_VideoStream::Is3D, XVidC_VideoStream::IsInterlaced, XVidC_3DSamplingInfo::Method, XVidC_VideoStream::PixPerClk, XVidC_3DSamplingInfo::Position, XVidC_3DInfo::Sampling, XVidC_VideoStream::Timing, XVidC_VideoStream::VmId, XVIDC_3D_SAMPLING_UNKNOWN, XVIDC_3D_SAMPPOS_UNKNOWN, XVIDC_3D_UNKNOWN, XVIDC_BPC_10, XVIDC_BPC_12, XVIDC_BPC_14, XVIDC_BPC_16, XVIDC_BPC_6, XVIDC_BPC_8, XVIDC_BPC_UNKNOWN, XVIDC_CSF_NUM_SUPPORTED, XVidC_GetFrameRate, XVidC_GetTimingInfo, XVidC_IsInterlaced, XVIDC_PPC_1, XVIDC_PPC_2, XVIDC_PPC_4, XVIDC_PPC_8.
Referenced by XVidC_Set3DVideoStream.
u32 XVidC_Set3DVideoStream(XVidC_VideoStream *VidStrmPtr, XVidC_VideoMode VmId, XVidC_ColorFormat ColorFormat, XVidC_ColorDepth Bpc, XVidC_PixelsPerClock Ppc, XVidC_3DInfo *Info3DPtr)
This function sets the VideoStream structure for the specified 3D video format.
VidStrmPtr is a pointer to the XVidC_VideoStream structure to be set. VmId specifies the resolution ID. ColorFormat specifies the color format type. Bpc specifies the color depth/bits per color component. Ppc specifies the pixels per clock. Info3DPtr is a pointer to a XVidC_3DInfo structure. Status code. XST_SUCCESS if the timing for the supplied ID was found.XST_FAILURE, otherwise. None.
References XVidC_VideoTiming::F0PVTotal, XVidC_VideoTiming::F1VBackPorch, XVidC_VideoTiming::F1VFrontPorch, XVidC_VideoTiming::F1VSyncWidth, XVidC_VideoTiming::F1VTotal, XVidC_3DInfo::Format, XVidC_VideoStream::Info_3D, XVidC_VideoStream::Is3D, XVidC_VideoStream::IsInterlaced, XVidC_VideoStream::Timing, XVidC_VideoTiming::VActive, XVIDC_3D_FRAME_PACKING, XVidC_SetVideoStream.
void XVidC_ReportStreamInfo(const XVidC_VideoStream *Stream)
This function prints the stream information on STDIO/UART console.
Stream is a pointer to video stream. None.
References XVidC_VideoStream::ColorDepth, XVidC_VideoStream::ColorFormatId, XVidC_VideoTiming::F0PVTotal, XVidC_3DInfo::Format, XVidC_VideoStream::FrameRate, XVidC_VideoTiming::HActive, XVidC_VideoTiming::HTotal, XVidC_VideoStream::Info_3D, XVidC_VideoStream::Is3D, XVidC_VideoStream::IsDSCompressed, XVidC_VideoStream::IsInterlaced, XVidC_VideoStream::PixPerClk, XVidC_VideoStream::Timing, XVidC_VideoStream::UncompressedTiming, XVidC_VideoTiming::VActive, XVidC_VideoStream::VmId, XVidC_Get3DFormatStr, XVidC_GetColorFormatStr, XVidC_GetFrameRateStr, XVidC_GetPixelClockHzByHVFr, XVidC_GetPixelClockHzByVmId, XVidC_GetVideoModeData, XVidC_GetVideoModeStr, XVIDC_VM_CUSTOM.
void XVidC_ReportTiming(const XVidC_VideoTiming *Timing, u8 IsInterlaced)
This function prints timing information on STDIO/Uart console.
Timing is a pointer to Video Timing structure of the stream. IsInterlaced is a TRUE/FALSE flag that denotes the timing parameter is for interlaced/progressive stream. None.
References XVidC_VideoTiming::F0PVBackPorch, XVidC_VideoTiming::F0PVFrontPorch, XVidC_VideoTiming::F0PVSyncWidth, XVidC_VideoTiming::F0PVTotal, XVidC_VideoTiming::F1VBackPorch, XVidC_VideoTiming::F1VFrontPorch, XVidC_VideoTiming::F1VSyncWidth, XVidC_VideoTiming::F1VTotal, XVidC_VideoTiming::HActive, XVidC_VideoTiming::HBackPorch, XVidC_VideoTiming::HFrontPorch, XVidC_VideoTiming::HSyncPolarity, XVidC_VideoTiming::HSyncWidth, XVidC_VideoTiming::HTotal, XVidC_VideoTiming::VActive, XVidC_VideoTiming::VSyncPolarity.
static u32 XVidC_EdidIsVideoTimingSupportedPreferredTiming(const u8 *EdidRaw, const XVidC_VideoTimingMode *VtMode)
Checks whether or not a specified video timing mode is the preferred timing of the supplied base Extended Display Identification Data (EDID).
EdidRaw is the supplied base EDID to check the timing against. VtMode is the video timing mode to check for support. Status code. XST_SUCCESS if the video timing mode is the preferred timing as specified in the base EDID.XST_FAILURE otherwise. None.
static u32 XVidC_EdidIsVideoTimingSupportedEstablishedTimings(const u8 *EdidRaw, const XVidC_VideoTimingMode *VtMode)
Checks whether or not a specified video timing mode is supported in the established timings field of the supplied base Extended Display Identification Data (EDID).
EdidRaw is the supplied base EDID to check the timing against. VtMode is the video timing mode to check for support. Status code. XST_SUCCESS if the video timing mode is supported in the base EDID's established timings field.XST_FAILURE otherwise. None.
static u32 XVidC_EdidIsVideoTimingSupportedStandardTimings(const u8 *EdidRaw, const XVidC_VideoTimingMode *VtMode)
Checks whether or not a specified video timing mode is supported in the standard timings field of the supplied base Extended Display Identification Data (EDID).
EdidRaw is the supplied base EDID to check the timing against. VtMode is the video timing mode to check for support. Status code. XST_SUCCESS if the video timing mode is supported in the base EDID's standard timings fields.XST_FAILURE otherwise. None.
static int XVidC_CalculatePower(u8 Base, u8 Power)
Perform a power operation.
Base is b in the power operation, b^n. Power is n in the power operation, b^n. Base^Power (Base to the power of Power). None.
static int XVidC_CalculateBinaryFraction_QFormat(u16 Val, u8 DecPtIndex)
Convert a fractional binary number into a fixed point Q0.DecPtIndex number Binary digits to the right of the decimal point represent 2^-1 to 2^-(DecPtIndex+1).
Binary digits to the left of the decimal point represent 2^0, 2^1, etc. For a given Q format, using an unsigned integer container with n fractional bits: its range is [0, 2^-n] its resolution is 2^n Val is the binary representation of the fraction. DecPtIndex is the index of the decimal point in the binary number. The decimal point is between the binary digits at Val's indices (DecPtIndex -1) and (DecPtIndex). DecPtIndex will determine the Q format resolution. Fixed point representation of the fractional part of the binary number in Q format. None.
void XVidC_EdidGetManName(const u8 *EdidRaw, char ManName[4])
Get the manufacturer name as specified in the vendor and product ID field of the supplied base Extended Display Identification Data (EDID).
EdidRaw is the supplied base EDID to retrieve the manufacturer name from. ManName is the string that will be modified to hold the retrieved manufacturer name. The ManName argument is modified with the manufacturer name.
References XVIDC_EDID_VPI_ID_MAN_NAME0, XVIDC_EDID_VPI_ID_MAN_NAME0_CHAR0_MASK, XVIDC_EDID_VPI_ID_MAN_NAME0_CHAR0_SHIFT, XVIDC_EDID_VPI_ID_MAN_NAME0_CHAR1_MASK, XVIDC_EDID_VPI_ID_MAN_NAME0_CHAR1_POS, XVIDC_EDID_VPI_ID_MAN_NAME1, XVIDC_EDID_VPI_ID_MAN_NAME1_CHAR1_SHIFT, XVIDC_EDID_VPI_ID_MAN_NAME1_CHAR2_MASK.
XVidC_ColorDepth XVidC_EdidGetColorDepth(const u8 *EdidRaw)
Get the color bit depth (bits per primary color) as specified in the basic display parameters and features, video input definition field of the supplied base Extended Display Identification Data (EDID).
EdidRaw is the supplied base EDID to retrieve color depth information from. The number of bits per primary color as specified by the supplied base EDID. None.
References XVIDC_BPC_10, XVIDC_BPC_12, XVIDC_BPC_14, XVIDC_BPC_16, XVIDC_BPC_6, XVIDC_BPC_8, XVIDC_BPC_UNKNOWN, XVIDC_EDID_BDISP_VID, XVIDC_EDID_BDISP_VID_DIG_BPC_10, XVIDC_EDID_BDISP_VID_DIG_BPC_12, XVIDC_EDID_BDISP_VID_DIG_BPC_14, XVIDC_EDID_BDISP_VID_DIG_BPC_16, XVIDC_EDID_BDISP_VID_DIG_BPC_6, XVIDC_EDID_BDISP_VID_DIG_BPC_8, XVIDC_EDID_BDISP_VID_DIG_BPC_MASK, XVIDC_EDID_BDISP_VID_DIG_BPC_SHIFT.
int XVidC_EdidGetCcRedX(const u8 *EdidRaw)
Calculates the x chromaticity coordinate for red by converting a 10 bit binary fraction representation from the supplied base Extended Display Identification Data (EDID) to a integer in Q0.10 Format.
To convert back to float divide the fixed point value by 2^10. EdidRaw is the supplied base EDID to retrieve chromaticity information from. The x chromatacity coordinate for red. All values will be accurate to +/-0.0005.
References XVIDC_EDID_CC_HIGH_SHIFT, XVIDC_EDID_CC_RBX_LOW_SHIFT, XVIDC_EDID_CC_REDX_HIGH, XVIDC_EDID_CC_RG_LOW.
int XVidC_EdidGetCcRedY(const u8 *EdidRaw)
Calculates the y chromaticity coordinate for red by converting a 10 bit binary fraction representation from the supplied base Extended Display Identification Data (EDID) to a integer in Q0.10 Format.
To convert back to float divide the fixed point value by 2^10. EdidRaw is the supplied base EDID to retrieve chromaticity information from. The y chromatacity coordinate for red. All values will be accurate to +/-0.0005.
References XVIDC_EDID_CC_HIGH_SHIFT, XVIDC_EDID_CC_RBY_LOW_MASK, XVIDC_EDID_CC_RBY_LOW_SHIFT, XVIDC_EDID_CC_REDY_HIGH, XVIDC_EDID_CC_RG_LOW.
int XVidC_EdidGetCcGreenX(const u8 *EdidRaw)
Calculates the x chromaticity coordinate for green by converting a 10 bit binary fraction representation from the supplied base Extended Display Identification Data (EDID) to a integer in Q0.10 Format.
To convert back to float divide the fixed point value by 2^10. EdidRaw is the supplied base EDID to retrieve chromaticity information from. The x chromatacity coordinate for green. All values will be accurate to +/-0.0005.
References XVIDC_EDID_CC_GREENX_HIGH, XVIDC_EDID_CC_GWX_LOW_MASK, XVIDC_EDID_CC_GWX_LOW_SHIFT, XVIDC_EDID_CC_HIGH_SHIFT, XVIDC_EDID_CC_RG_LOW.
int XVidC_EdidGetCcGreenY(const u8 *EdidRaw)
Calculates the y chromaticity coordinate for green by converting a 10 bit binary fraction representation from the supplied base Extended Display Identification Data (EDID) to a integer in Q0.10 Format.
To convert back to float divide the fixed point value by 2^10. EdidRaw is the supplied base EDID to retrieve chromaticity information from. The y chromatacity coordinate for green. All values will be accurate to +/-0.0005.
References XVIDC_EDID_CC_GREENY_HIGH, XVIDC_EDID_CC_GWY_LOW_MASK, XVIDC_EDID_CC_HIGH_SHIFT, XVIDC_EDID_CC_RG_LOW.
int XVidC_EdidGetCcBlueX(const u8 *EdidRaw)
Calculates the x chromaticity coordinate for blue by converting a 10 bit binary fraction representation from the supplied base Extended Display Identification Data (EDID) to a integer in Q0.10 Format.
To convert back to float divide the fixed point value by 2^10. EdidRaw is the supplied base EDID to retrieve chromaticity information from. The x chromatacity coordinate for blue. All values will be accurate to +/-0.0005.
References XVIDC_EDID_CC_BLUEX_HIGH, XVIDC_EDID_CC_BW_LOW, XVIDC_EDID_CC_HIGH_SHIFT, XVIDC_EDID_CC_RBX_LOW_SHIFT.
int XVidC_EdidGetCcBlueY(const u8 *EdidRaw)
Calculates the y chromaticity coordinate for blue by converting a 10 bit binary fraction representation from the supplied base Extended Display Identification Data (EDID) to a integer in Q0.10 Format.
To convert back to float divide the fixed point value by 2^10. EdidRaw is the supplied base EDID to retrieve chromaticity information from. The y chromatacity coordinate for blue. All values will be accurate to +/-0.0005.
References XVIDC_EDID_CC_BLUEY_HIGH, XVIDC_EDID_CC_BW_LOW, XVIDC_EDID_CC_HIGH_SHIFT, XVIDC_EDID_CC_RBY_LOW_MASK, XVIDC_EDID_CC_RBY_LOW_SHIFT.
int XVidC_EdidGetCcWhiteX(const u8 *EdidRaw)
Calculates the x chromaticity coordinate for white by converting a 10 bit binary fraction representation from the supplied base Extended Display Identification Data (EDID) to a integer in Q0.10 Format.
To convert back to float divide the fixed point value by 2^10. EdidRaw is the supplied base EDID to retrieve chromaticity information from. The x chromatacity coordinate for white. All values will be accurate to +/-0.0005.
References XVIDC_EDID_CC_BW_LOW, XVIDC_EDID_CC_GWX_LOW_MASK, XVIDC_EDID_CC_GWX_LOW_SHIFT, XVIDC_EDID_CC_HIGH_SHIFT, XVIDC_EDID_CC_WHITEX_HIGH.
int XVidC_EdidGetCcWhiteY(const u8 *EdidRaw)
Calculates the y chromaticity coordinate for white by converting a 10 bit binary fraction representation from the supplied base Extended Display Identification Data (EDID) to an integer in Q0.10 Format.
To convert back to float divide the fixed point value by 2^10. EdidRaw is the supplied base EDID to retrieve chromaticity information from. The y chromatacity coordinate for white. All values will be accurate to +/-0.0005.
References XVIDC_EDID_CC_BW_LOW, XVIDC_EDID_CC_GWY_LOW_MASK, XVIDC_EDID_CC_HIGH_SHIFT, XVIDC_EDID_CC_WHITEY_HIGH.
u16 XVidC_EdidGetStdTimingsV(const u8 *EdidRaw, u8 StdTimingsNum)
Retrieves the active vertical resolution from the standard timings field of the supplied base Extended Display Identification Data (EDID).
EdidRaw is the supplied base EDID to check the timing against. StdTimingsNum specifies which one of the standard timings to retrieve from the standard timings field. The vertical active resolution of the specified standard timing from the supplied base EDID. StdTimingsNum is an index 1-8.
References XVIDC_EDID_STD_TIMINGS_AR_16_10, XVIDC_EDID_STD_TIMINGS_AR_16_9, XVIDC_EDID_STD_TIMINGS_AR_4_3, XVIDC_EDID_STD_TIMINGS_AR_5_4, XVidC_EdidGetStdTimingsAr, XVidC_EdidGetStdTimingsH.
u32 XVidC_EdidIsVideoTimingSupported(const u8 *EdidRaw, const XVidC_VideoTimingMode *VtMode)
Checks whether or not a specified video timing mode is supported as specified in the supplied base Extended Display Identification Data (EDID).
The preferred timing, established timings (I, II, II), and the standard timings fields are checked for support. EdidRaw is the supplied base EDID to check the timing against. VtMode is the video timing mode to check for support. Status code. XST_SUCCESS if the video timing mode is supported as specified in the supplied base EDID.XST_FAILURE otherwise. None.
Referenced by Edid_PrintSuppVmTable.
XVidC_IsStream3D
This macro check if video stream is 3D or 2D.
VidStreamPtr is a pointer to the XVidC_VideoStream structure. 3D(1)/2D(0) C-style signature: u8 XDp_IsStream3D(XVidC_VideoStream *VidStreamPtr)
XVidC_EdidIsHeaderValid
Check if EDID header matches valid signature.
E EDID data array
Referenced by Edid_PrintDecodeBase.
XVidC_EdidGetIdProdCode
Get product code from EDID.
E EDID data array
XVidC_EdidGetIdSn
Extract 32-bit serial number from EDID.
E EDID data array
XVidC_EdidGetManWeek
Get week of manufacture from EDID.
E EDID data array
XVidC_EdidGetModManYear
Get model/manufacture year from EDID.
E EDID data array
XVidC_EdidIsYearModel
Check if year field represents model year (week=0xFF)
E EDID data array
XVidC_EdidIsYearMan
Check if year field represents manufacture year (week!=0xFF)
E EDID data array
XVidC_EdidGetStructVer
Get EDID structure version number.
E EDID data array
XVidC_EdidGetStructRev
Get EDID structure revision number.
E EDID data array
XVidC_EdidIsDigitalSig
Check if display uses digital signal input.
E EDID data array
XVidC_EdidIsAnalogSig
Check if display uses analog signal input.
E EDID data array
XVidC_EdidGetAnalogSigLvlStd
Get analog signal level standard.
E EDID data array
XVidC_EdidGetAnalogSigVidSetup
Get analog video setup (blank-to-black setup/pedestal)
E EDID data array
XVidC_EdidSuppAnalogSigSepSyncHv
Check if analog separate sync H and V supported.
E EDID data array
XVidC_EdidSuppAnalogSigCompSyncH
Check if analog composite sync on H supported.
E EDID data array
XVidC_EdidSuppAnalogSigCompSyncG
Check if analog composite sync on G (green) supported.
E EDID data array
XVidC_EdidSuppAnalogSigSerrVsync
Check if analog serration on V sync pulse supported.
E EDID data array
XVidC_EdidGetDigitalSigIfaceStd
Get digital signal video interface standard.
E EDID data array
XVidC_EdidIsSsArDefined
Check if screen size or aspect ratio is defined.
E EDID data array
XVidC_EdidGetSsArH
Get horizontal screen size or aspect ratio value.
E EDID data array
XVidC_EdidGetSsArV
Get vertical screen size or aspect ratio value.
E EDID data array
XVidC_EdidIsSsArSs
Check if values represent screen size (both non-zero)
E EDID data array
XVidC_EdidIsSsArArL
Check if values represent landscape aspect ratio (H non-zero, V zero)
E EDID data array
XVidC_EdidIsSsArArP
Check if values represent portrait aspect ratio (H zero, V non-zero)
E EDID data array
XVidC_EdidGetSsArArL
Calculate landscape aspect ratio.
E EDID data array
XVidC_EdidGetSsArArP
Calculate portrait aspect ratio.
E EDID data array
XVidC_EdidIsGammaInExt
Check if gamma value is stored in extension block.
E EDID data array
XVidC_EdidGetGamma
Calculate gamma value from EDID.
E EDID data array
XVidC_EdidSuppFeaturePmStandby
Check if standby power management supported.
E EDID data array
XVidC_EdidSuppFeaturePmSuspend
Check if suspend power management supported.
E EDID data array
XVidC_EdidSuppFeaturePmOffVlp
Check if active-off/very low power supported.
E EDID data array
XVidC_EdidGetFeatureAnaColorType
Get analog display color type.
E EDID data array
XVidC_EdidSuppFeatureDigColorEncYCrCb444
Check if digital YCrCb 4:4:4 color encoding supported.
E EDID data array
XVidC_EdidSuppFeatureDigColorEncYCrCb422
Check if digital YCrCb 4:2:2 color encoding supported.
E EDID data array
XVidC_EdidIsFeatureSrgbDef
Check if sRGB is default color space.
E EDID data array
XVidC_EdidIsFeaturePtmInc
Check if preferred timing mode included.
E EDID data array
XVidC_EdidIsFeatureContFreq
Check if continuous frequency operation supported.
E EDID data array
XVidC_EdidSuppEstTimings720x400_70
Check if 720x400 @ 70Hz timing supported.
E EDID data array
XVidC_EdidSuppEstTimings720x400_88
Check if 720x400 @ 88Hz timing supported.
E EDID data array
XVidC_EdidSuppEstTimings640x480_60
Check if 640x480 @ 60Hz timing supported.
E EDID data array
XVidC_EdidSuppEstTimings640x480_67
Check if 640x480 @ 67Hz timing supported.
E EDID data array
XVidC_EdidSuppEstTimings640x480_72
Check if 640x480 @ 72Hz timing supported.
E EDID data array
XVidC_EdidSuppEstTimings640x480_75
Check if 640x480 @ 75Hz timing supported.
E EDID data array
XVidC_EdidSuppEstTimings800x600_56
Check if 800x600 @ 56Hz timing supported.
E EDID data array
XVidC_EdidSuppEstTimings800x600_60
Check if 800x600 @ 60Hz timing supported.
E EDID data array
XVidC_EdidSuppEstTimings800x600_72
Check if 800x600 @ 72Hz timing supported.
E EDID data array
XVidC_EdidSuppEstTimings800x600_75
Check if 800x600 @ 75Hz timing supported.
E EDID data array
XVidC_EdidSuppEstTimings832x624_75
Check if 832x624 @ 75Hz timing supported.
E EDID data array
XVidC_EdidSuppEstTimings1024x768_87
Check if 1024x768 @ 87Hz interlaced timing supported.
E EDID data array
XVidC_EdidSuppEstTimings1024x768_60
Check if 1024x768 @ 60Hz timing supported.
E EDID data array
XVidC_EdidSuppEstTimings1024x768_70
Check if 1024x768 @ 70Hz timing supported.
E EDID data array
XVidC_EdidSuppEstTimings1024x768_75
Check if 1024x768 @ 75Hz timing supported.
E EDID data array
XVidC_EdidSuppEstTimings1280x1024_75
Check if 1280x1024 @ 75Hz timing supported.
E EDID data array
XVidC_EdidSuppEstTimings1152x870_75
Check if 1152x870 @ 75Hz manufacturer timing supported.
E EDID data array
XVidC_EdidGetTimingsMan
Get manufacturer-specific established timings.
E EDID data array
XVidC_EdidGetStdTimingsH
Get standard timing horizontal resolution.
E EDID data array N Standard timing index (0-7)
Referenced by XVidC_EdidGetStdTimingsV.
XVidC_EdidGetStdTimingsAr
Get standard timing aspect ratio.
E EDID data array N Standard timing index (0-7)
Referenced by XVidC_EdidGetStdTimingsV.
XVidC_EdidGetStdTimingsFrr
Get standard timing field refresh rate.
E EDID data array N Standard timing index (0-7)
XVidC_EdidIsDtdPtmInterlaced
Check if DTD/PTM uses interlaced scan.
E EDID data array
XVidC_EdidGetExtBlkCount
Get number of EDID extension blocks.
E EDID data array
Referenced by Edid_PrintDecodeBase.
XVidC_EdidGetChecksum
Get EDID base block checksum.
E EDID data array
Referenced by Edid_PrintDecodeBase.