xvidc.c
const XVidC_VideoTimingMode XVidC_VideoTimingModes[XVIDC_VM_NUM_SUPPORTED][XVIDC_VM_NUM_SUPPORTED]
This table contains the main stream attributes for various standard resolutions.
Each entry is of the format: 1) ID: XVIDC_VM_<HRES>x<VRES>_<FRAME RATE (HZ)>_<P|I>(RB = Reduced Blanking) 2) Resolution naming: "<HRES>x<VRES>@<FRAME RATE (HZ)>" 3) Frame rate: XVIDC_FR<FRAME RATE (HZ)> 4) Video timing structure: 1) Horizontal active resolution (pixels) 2) Horizontal front porch (pixels) 3) Horizontal sync width (pixels) 4) Horizontal back porch (pixels) 5) Horizontal total (pixels) 6) Horizontal sync polarity (0=negative|1=positive) 7) Vertical active resolution (lines) 8) Frame 0: Vertical front porch (lines) 9) Frame 0: Vertical sync width (lines) 10) Frame 0: Vertical back porch (lines) 11) Frame 0: Vertical total (lines) 12) Frame 1: Vertical front porch (lines) 13) Frame 1: Vertical sync width (lines) 14) Frame 1: Vertical back porch (lines) 15) Frame 1: Vertical total (lines) 16) Vertical sync polarity (0=negative|1=positive)
Referenced by Edid_PrintSuppVmTable.
const XVidC_VideoTimingMode* XVidC_CustomTimingModes
int XVidC_NumCustomModes
static const XVidC_VideoTimingMode * XVidC_GetCustomVideoModeData(XVidC_VideoMode VmId)
This function returns the pointer to video mode data at the provided index of the custom video mode table.
VmId specifies the resolution ID. Pointer to XVidC_VideoTimingMode structure based on the given video mode. None.
static u8 XVidC_IsVtmRb(const char *VideoModeStr, u8 RbN)
This function returns whether or not the video timing mode is a reduced blanking mode or not.
VideoModeStr specifies the resolution name string. RbN specifies the type of reduced blanking: 0 = No Reduced Blanking1 = RB2 = RB2 If the reduced blanking type is compatible with the video mode: 0 = Not supported1 = Video mode supports the RB type None.
u32 XVidC_RegisterCustomTimingModes(const XVidC_VideoTimingMode *CustomTable, u16 NumElems)
This function registers a user-defined custom video mode timing table with video_common.
Functions which search the available video modes, or take VmId as an input, will operate on or check the custom video mode timing table in addition to the pre-defined video mode timing table (XVidC_VideoTimingModes). CustomTable is a pointer to the user-defined custom vide mode timing table to register. NumElems is the number of video modes supported by CustomTable. Status code. XST_SUCCESS if the custom table was successfully registered.XST_FAILURE if an existing custom table is already present. IDs in the custom table may not conflict with IDs reserved by the XVidC_VideoMode enum.
References XVIDC_VM_CUSTOM.
void XVidC_UnregisterCustomTimingModes(void)
This function unregisters the user-defined custom video mode timing table previously registered by XVidC_RegisterCustomTimingModes().
None.
u64 XVidC_GetPixelClockHzByHVFr(u32 HTotal, u32 VTotal, u8 FrameRate)
This function calculates pixel clock based on the inputs.
HTotal specifies horizontal total. VTotal specifies vertical total. FrameRate specifies rate at which frames are generated. Pixel clock in Hz. None.
Referenced by XVidC_ReportStreamInfo.
u64 XVidC_GetPixelClockHzByVmId(XVidC_VideoMode VmId)
This function calculates pixel clock from video mode.
VmId specifies the resolution id. Pixel clock in Hz. None.
References XVidC_VideoTiming::F0PVTotal, XVidC_VideoTiming::F1VTotal, XVidC_VideoTimingMode::FrameRate, XVidC_VideoTiming::HTotal, XVidC_VideoTimingMode::Timing, XVidC_GetVideoModeData, XVidC_IsInterlaced.
Referenced by XVidC_ReportStreamInfo.
XVidC_VideoFormat XVidC_GetVideoFormat(XVidC_VideoMode VmId)
This function checks if the input video mode is interlaced/progressive based on its ID from the video timings table.
VmId specifies the resolution ID from the video timings table. Video format. XVIDC_VF_PROGRESSIVEXVIDC_VF_INTERLACED None.
References XVidC_VideoTiming::F1VTotal, XVidC_VideoTimingMode::Timing, XVidC_GetVideoModeData, XVIDC_VF_INTERLACED, XVIDC_VF_PROGRESSIVE, XVIDC_VF_UNKNOWN.
Referenced by XVidC_IsInterlaced.
u8 XVidC_IsInterlaced(XVidC_VideoMode VmId)
This function checks if the input video mode is interlaced based on its ID from the video timings table.
VmId specifies the resolution ID from the video timings table. 1 if the video timing with the supplied table ID is interlaced; 0 if the video timing is progressive. None.
References XVidC_GetVideoFormat, XVIDC_VF_INTERLACED.
Referenced by XVidC_GetPixelClockHzByVmId, XVidC_GetVideoModeIdRb, XVidC_SetVideoStream.
XVidC_VideoMode XVidC_GetVideoModeIdWBlanking(const XVidC_VideoTiming *Timing, u32 FrameRate, u8 IsInterlaced)
This function returns the Video Mode ID that matches the detected input timing, frame rate and I/P flag.
Timing is the pointer to timing parameters to match FrameRate specifies refresh rate in HZ IsInterlaced is flag. 0 = Progressive 1 = Interlaced. Id of a supported video mode. This is an extension of XVidC_GetVideoModeId API to include blanking information in match process. No attempt is made to search for reduced blanking entries, if any.
References XVidC_VideoTiming::F0PVBackPorch, XVidC_VideoTiming::F0PVFrontPorch, XVidC_VideoTiming::F0PVSyncWidth, XVidC_VideoTiming::F0PVTotal, XVidC_VideoTiming::HActive, XVidC_VideoTiming::HBackPorch, XVidC_VideoTiming::HFrontPorch, XVidC_VideoTiming::HSyncWidth, XVidC_VideoTiming::HTotal, XVidC_VideoTiming::VActive, XVidC_GetTimingInfo, XVidC_GetVideoModeId, XVIDC_VM_NOT_SUPPORTED.
XVidC_VideoMode XVidC_GetVideoModeId(u32 Width, u32 Height, u32 FrameRate, u8 IsInterlaced)
This function returns the Video Mode ID that matches the detected input width, height, frame rate and I/P flag.
Width specifies the number pixels per scanline. Height specifies the number of scanline's. FrameRate specifies refresh rate in HZ IsInterlaced is flag. 0 = Progressive1 = Interlaced. Id of a supported video mode. None.
References XVidC_VideoTimingMode::FrameRate, XVidC_VideoTiming::HActive, XVidC_VideoTimingMode::Timing, XVidC_VideoTiming::VActive, XVidC_VideoTimingMode::VmId, XVIDC_VM_INTL_END, XVIDC_VM_INTL_START, XVIDC_VM_NOT_SUPPORTED, XVIDC_VM_PROG_END, XVIDC_VM_PROG_START.
Referenced by XVidC_GetVideoModeIdRb, XVidC_GetVideoModeIdWBlanking.
XVidC_VideoMode XVidC_GetVideoModeIdExtensive(XVidC_VideoTiming *Timing, u32 FrameRate, u8 IsInterlaced, u8 IsExtensive)
This function returns the Video Mode ID that matches the detected input timing, frame rate and I/P flag.
Timing is the pointer to timing parameters to match FrameRate specifies refresh rate in HZ IsInterlaced is flag. 0 = Progressive 1 = Interlaced. IsExtensive is flag. 0 = Basic matching of timing parameters 1 = Extensive matching of timing parameters Id of a supported video mode. This function attempts to search for reduced blanking entries, if any.
References XVidC_VideoTiming::F0PVFrontPorch, XVidC_VideoTiming::F0PVSyncWidth, XVidC_VideoTiming::F0PVTotal, XVidC_VideoTiming::F1VFrontPorch, XVidC_VideoTiming::F1VSyncWidth, XVidC_VideoTiming::F1VTotal, XVidC_VideoTimingMode::FrameRate, XVidC_VideoTiming::HActive, XVidC_VideoTiming::HFrontPorch, XVidC_VideoTiming::HSyncWidth, XVidC_VideoTiming::HTotal, XVidC_VideoTimingMode::Timing, XVidC_VideoTiming::VActive, XVidC_VideoTimingMode::VmId, XVidC_VideoTiming::VSyncPolarity, XVIDC_VM_INTL_END, XVIDC_VM_INTL_START, XVIDC_VM_NOT_SUPPORTED, XVIDC_VM_PROG_END, XVIDC_VM_PROG_START.
XVidC_VideoMode XVidC_GetVideoModeIdRb(u32 Width, u32 Height, u32 FrameRate, u8 IsInterlaced, u8 RbN)
This function returns the video mode ID that matches the detected input width, height, frame rate, interlaced or progressive, and reduced blanking.
Width specifies the number pixels per scanline. Height specifies the number of scanline's. FrameRate specifies refresh rate in HZ IsInterlaced specifies interlaced or progressive mode: 0 = Progressive1 = Interlaced. RbN specifies the type of reduced blanking: 0 = No reduced blanking1 = RB2 = RB2 ID of a supported video mode. None.
References XVidC_VideoTimingMode::FrameRate, XVidC_VideoTiming::HActive, XVidC_VideoTimingMode::Timing, XVidC_VideoTiming::VActive, XVidC_GetVideoModeData, XVidC_GetVideoModeId, XVidC_GetVideoModeStr, XVidC_IsInterlaced, XVIDC_VM_NOT_SUPPORTED.
const XVidC_VideoTimingMode * XVidC_GetVideoModeData(XVidC_VideoMode VmId)
This function returns the pointer to video mode data at index provided.
VmId specifies the resolution id. Pointer to XVidC_VideoTimingMode structure based on the given video mode. None.
References XVIDC_VM_NUM_SUPPORTED.
Referenced by XVidC_GetFrameRate, XVidC_GetFrameRateStr, XVidC_GetPixelClockHzByVmId, XVidC_GetTimingInfo, XVidC_GetVideoFormat, XVidC_GetVideoModeIdRb, XVidC_GetVideoModeStr, XVidC_ReportStreamInfo.
const char * XVidC_GetVideoModeStr(XVidC_VideoMode VmId)
This function returns the resolution name for index specified.
VmId specifies the resolution id. Pointer to a resolution name string. None.
References XVidC_VideoTimingMode::Name, XVidC_GetVideoModeData, XVIDC_VM_CUSTOM.
Referenced by XVidC_GetVideoModeIdRb, XVidC_ReportStreamInfo.
const char * XVidC_GetFrameRateStr(XVidC_VideoMode VmId)
This function returns the frame rate name for index specified.
VmId specifies the resolution id. Pointer to a frame rate name string. None.
References XVidC_VideoTimingMode::FrameRate, XVIDC_FR_100HZ, XVIDC_FR_120HZ, XVIDC_FR_144HZ, XVIDC_FR_200HZ, XVIDC_FR_240HZ, XVIDC_FR_24HZ, XVIDC_FR_25HZ, XVIDC_FR_30HZ, XVIDC_FR_48HZ, XVIDC_FR_50HZ, XVIDC_FR_56HZ, XVIDC_FR_60HZ, XVIDC_FR_65HZ, XVIDC_FR_67HZ, XVIDC_FR_70HZ, XVIDC_FR_72HZ, XVIDC_FR_75HZ, XVIDC_FR_85HZ, XVIDC_FR_87HZ, XVIDC_FR_88HZ, XVIDC_FR_96HZ, XVidC_GetVideoModeData.
Referenced by XVidC_ReportStreamInfo.
const char * XVidC_Get3DFormatStr(XVidC_3DFormat Format)
This function returns a string representation of the enumerated type, XVidC_3DFormat.
Format specifies the value to convert. Pointer to the converted string. None.
References XVIDC_3D_FIELD_ALTERNATIVE, XVIDC_3D_FRAME_PACKING, XVIDC_3D_LINE_ALTERNATIVE, XVIDC_3D_SIDE_BY_SIDE_FULL, XVIDC_3D_SIDE_BY_SIDE_HALF, XVIDC_3D_TOP_AND_BOTTOM_HALF.
Referenced by XVidC_ReportStreamInfo.
const char * XVidC_GetColorFormatStr(XVidC_ColorFormat ColorFormatId)
This function returns the color format name for index specified.
ColorFormatId specifies the index of color format space. Pointer to a color space name string. None.
References XVIDC_CSF_MEM_BGR8, XVIDC_CSF_MEM_BGRA8, XVIDC_CSF_MEM_BGRX8, XVIDC_CSF_MEM_R_G_B8, XVIDC_CSF_MEM_RGB16, XVIDC_CSF_MEM_RGB565, XVIDC_CSF_MEM_RGB8, XVIDC_CSF_MEM_RGBA8, XVIDC_CSF_MEM_RGBX10, XVIDC_CSF_MEM_RGBX12, XVIDC_CSF_MEM_RGBX8, XVIDC_CSF_MEM_UYVY8, XVIDC_CSF_MEM_Y10, XVIDC_CSF_MEM_Y10_L16LE, XVIDC_CSF_MEM_Y10_M16LE, XVIDC_CSF_MEM_Y12, XVIDC_CSF_MEM_Y12_L16LE, XVIDC_CSF_MEM_Y12_M16LE, XVIDC_CSF_MEM_Y16, XVIDC_CSF_MEM_Y8, XVIDC_CSF_MEM_Y_U_V10, XVIDC_CSF_MEM_Y_U_V10_L16LE, XVIDC_CSF_MEM_Y_U_V10_M16LE, XVIDC_CSF_MEM_Y_U_V12, XVIDC_CSF_MEM_Y_U_V12_L16LE, XVIDC_CSF_MEM_Y_U_V12_M16LE, XVIDC_CSF_MEM_Y_U_V8, XVIDC_CSF_MEM_Y_U_V8_420, XVIDC_CSF_MEM_Y_UV10, XVIDC_CSF_MEM_Y_UV10_420, XVIDC_CSF_MEM_Y_UV10_420_L16LE, XVIDC_CSF_MEM_Y_UV10_420_M16LE, XVIDC_CSF_MEM_Y_UV10_L16LE, XVIDC_CSF_MEM_Y_UV10_M16LE, XVIDC_CSF_MEM_Y_UV12, XVIDC_CSF_MEM_Y_UV12_420, XVIDC_CSF_MEM_Y_UV12_420_L16LE, XVIDC_CSF_MEM_Y_UV12_420_M16LE, XVIDC_CSF_MEM_Y_UV12_L16LE, XVIDC_CSF_MEM_Y_UV12_M16LE, XVIDC_CSF_MEM_Y_UV16, XVIDC_CSF_MEM_Y_UV16_420, XVIDC_CSF_MEM_Y_UV8, XVIDC_CSF_MEM_Y_UV8_420, XVIDC_CSF_MEM_YUV16, XVIDC_CSF_MEM_YUV8, XVIDC_CSF_MEM_YUVA8, XVIDC_CSF_MEM_YUVX10, XVIDC_CSF_MEM_YUVX12, XVIDC_CSF_MEM_YUVX8, XVIDC_CSF_MEM_YUYV8, XVIDC_CSF_RGB, XVIDC_CSF_RGBA, XVIDC_CSF_YCBCR_420, XVIDC_CSF_YCBCR_422, XVIDC_CSF_YCBCR_444, XVIDC_CSF_YCRCB_420, XVIDC_CSF_YCRCB_422, XVIDC_CSF_YCRCB_444, XVIDC_CSF_YCRCBA_444, XVIDC_CSF_YONLY.
Referenced by XVidC_ReportStreamInfo.
XVidC_FrameRate XVidC_GetFrameRate(XVidC_VideoMode VmId)
This function returns the frame rate for index specified.
VmId specifies the resolution id. Frame rate in Hz. None.
References XVidC_VideoTimingMode::FrameRate, XVIDC_FR_NUM_SUPPORTED, XVidC_GetVideoModeData.
Referenced by XVidC_SetVideoStream.
const XVidC_VideoTiming * XVidC_GetTimingInfo(XVidC_VideoMode VmId)
This function returns the timing parameters for specified resolution.
VmId specifies the resolution id. Pointer to a XVidC_VideoTiming structure. None.
References XVidC_VideoTimingMode::Timing, XVidC_GetVideoModeData.
Referenced by XVidC_GetVideoModeIdWBlanking, XVidC_SetVideoStream.
u32 XVidC_SetVideoStream(XVidC_VideoStream *VidStrmPtr, XVidC_VideoMode VmId, XVidC_ColorFormat ColorFormat, XVidC_ColorDepth Bpc, XVidC_PixelsPerClock Ppc)
This function sets the VideoStream structure for the specified video format.
VidStrmPtr is a pointer to the XVidC_VideoStream structure to be set. VmId specifies the resolution ID. ColorFormat specifies the color format type. Bpc specifies the color depth/bits per color component. Ppc specifies the pixels per clock. Status code. XST_SUCCESS if the timing for the supplied ID was found.XST_FAILURE, otherwise. None.
References XVidC_VideoStream::ColorDepth, XVidC_VideoStream::ColorFormatId, XVidC_3DInfo::Format, XVidC_VideoStream::FrameRate, XVidC_VideoStream::Info_3D, XVidC_VideoStream::Is3D, XVidC_VideoStream::IsInterlaced, XVidC_3DSamplingInfo::Method, XVidC_VideoStream::PixPerClk, XVidC_3DSamplingInfo::Position, XVidC_3DInfo::Sampling, XVidC_VideoStream::Timing, XVidC_VideoStream::VmId, XVIDC_3D_SAMPLING_UNKNOWN, XVIDC_3D_SAMPPOS_UNKNOWN, XVIDC_3D_UNKNOWN, XVIDC_BPC_10, XVIDC_BPC_12, XVIDC_BPC_14, XVIDC_BPC_16, XVIDC_BPC_6, XVIDC_BPC_8, XVIDC_BPC_UNKNOWN, XVIDC_CSF_NUM_SUPPORTED, XVidC_GetFrameRate, XVidC_GetTimingInfo, XVidC_IsInterlaced, XVIDC_PPC_1, XVIDC_PPC_2, XVIDC_PPC_4, XVIDC_PPC_8.
Referenced by XVidC_Set3DVideoStream.
u32 XVidC_Set3DVideoStream(XVidC_VideoStream *VidStrmPtr, XVidC_VideoMode VmId, XVidC_ColorFormat ColorFormat, XVidC_ColorDepth Bpc, XVidC_PixelsPerClock Ppc, XVidC_3DInfo *Info3DPtr)
This function sets the VideoStream structure for the specified 3D video format.
VidStrmPtr is a pointer to the XVidC_VideoStream structure to be set. VmId specifies the resolution ID. ColorFormat specifies the color format type. Bpc specifies the color depth/bits per color component. Ppc specifies the pixels per clock. Info3DPtr is a pointer to a XVidC_3DInfo structure. Status code. XST_SUCCESS if the timing for the supplied ID was found.XST_FAILURE, otherwise. None.
References XVidC_VideoTiming::F0PVTotal, XVidC_VideoTiming::F1VBackPorch, XVidC_VideoTiming::F1VFrontPorch, XVidC_VideoTiming::F1VSyncWidth, XVidC_VideoTiming::F1VTotal, XVidC_3DInfo::Format, XVidC_VideoStream::Info_3D, XVidC_VideoStream::Is3D, XVidC_VideoStream::IsInterlaced, XVidC_VideoStream::Timing, XVidC_VideoTiming::VActive, XVIDC_3D_FRAME_PACKING, XVidC_SetVideoStream.
void XVidC_ReportStreamInfo(const XVidC_VideoStream *Stream)
This function prints the stream information on STDIO/UART console.
Stream is a pointer to video stream. None.
References XVidC_VideoStream::ColorDepth, XVidC_VideoStream::ColorFormatId, XVidC_VideoTiming::F0PVTotal, XVidC_3DInfo::Format, XVidC_VideoStream::FrameRate, XVidC_VideoTiming::HActive, XVidC_VideoTiming::HTotal, XVidC_VideoStream::Info_3D, XVidC_VideoStream::Is3D, XVidC_VideoStream::IsDSCompressed, XVidC_VideoStream::IsInterlaced, XVidC_VideoStream::PixPerClk, XVidC_VideoStream::Timing, XVidC_VideoStream::UncompressedTiming, XVidC_VideoTiming::VActive, XVidC_VideoStream::VmId, XVidC_Get3DFormatStr, XVidC_GetColorFormatStr, XVidC_GetFrameRateStr, XVidC_GetPixelClockHzByHVFr, XVidC_GetPixelClockHzByVmId, XVidC_GetVideoModeData, XVidC_GetVideoModeStr, XVIDC_VM_CUSTOM.
void XVidC_ReportTiming(const XVidC_VideoTiming *Timing, u8 IsInterlaced)
This function prints timing information on STDIO/Uart console.
Timing is a pointer to Video Timing structure of the stream. IsInterlaced is a TRUE/FALSE flag that denotes the timing parameter is for interlaced/progressive stream. None.
References XVidC_VideoTiming::F0PVBackPorch, XVidC_VideoTiming::F0PVFrontPorch, XVidC_VideoTiming::F0PVSyncWidth, XVidC_VideoTiming::F0PVTotal, XVidC_VideoTiming::F1VBackPorch, XVidC_VideoTiming::F1VFrontPorch, XVidC_VideoTiming::F1VSyncWidth, XVidC_VideoTiming::F1VTotal, XVidC_VideoTiming::HActive, XVidC_VideoTiming::HBackPorch, XVidC_VideoTiming::HFrontPorch, XVidC_VideoTiming::HSyncPolarity, XVidC_VideoTiming::HSyncWidth, XVidC_VideoTiming::HTotal, XVidC_VideoTiming::VActive, XVidC_VideoTiming::VSyncPolarity.