dfeequ
XDfeEqu_StateId
Not ready state.
typedef __u32 u32
typedef __u16 u16
typedef __u8 u8
typedef __s32 s32
typedef __s16 s16
typedef __u64 u64
typedef __s64 s64
typedef __s8 s8
typedef enum XDfeEqu_StateId XDfeEqu_StateId
XDfeEqu * XDfeEqu_InstanceInit(const char *DeviceNodeName)
API initialises one instance of an Equalizer driver.
Traverse "/sys/bus/platform/device" directory (in Linux), to find registered EQU device with the name DeviceNodeName. The first available slot in the instances array XDfeEqu_Equalizer[] will be taken as a DeviceNodeName object. On success it moves the state machine to a Ready state, while on failure stays in a Not Ready state. DeviceNodeName Device node name. Pointer to the instance if successful.NULL on error.
References XDfeEqu::Device, XDfeEqu::NodeName, XDfeEqu::StateId, XDFEEQU_NODE_NAME_MAX_LENGTH, XDFEEQU_STATE_NOT_READY, XDFEEQU_STATE_READY, XST_FAILURE, XST_SUCCESS.
Referenced by XDfeEqu_PassThroughExample, XDfeEqu_SelfExample.
void XDfeEqu_InstanceClose(XDfeEqu *InstancePtr)
API closes the instance of an Equalizer driver and moves the state machine to a Not Ready state.
InstancePtr Pointer to the Equalizer instance.
References XDfeEqu::Device, XDfeEqu::NodeName, XDfeEqu::StateId, XDFEEQU_STATE_NOT_READY.
Referenced by XDfeEqu_PassThroughExample, XDfeEqu_SelfExample.
void XDfeEqu_Reset(XDfeEqu *InstancePtr)
Resets Equalizer and puts block into a reset state.
InstancePtr Pointer to the Equalizer instance.
References XDfeEqu::StateId, XDFEEQU_STATE_NOT_READY, XDFEEQU_STATE_RESET.
Referenced by XDfeEqu_PassThroughExample, XDfeEqu_SelfExample.
void XDfeEqu_Configure(XDfeEqu *InstancePtr, XDfeEqu_Cfg *Cfg)
Reads configuration from device tree/xparameters.h and IP registers.
Removes S/W reset and moves the state machine to a Configured state. InstancePtr Pointer to the Equalizer instance. Cfg Configuration data container.
References XDfeEqu_ModelParameters::ComplexModel, XDfeEqu_Config::ComplexModel, XDfeEqu::Config, XDfeEqu_Version::Major, XDfeEqu_Version::Minor, XDfeEqu_Cfg::ModelParams, XDfeEqu_ModelParameters::NumChannels, XDfeEqu_Config::NumChannels, XDfeEqu_Version::Patch, XDfeEqu_Version::Revision, XDfeEqu_ModelParameters::SampleWidth, XDfeEqu_Config::SampleWidth, XDfeEqu::StateId, XDfeEqu_ModelParameters::TuserWidth, XDfeEqu_Config::TuserWidth, XDfeEqu_Cfg::Version, XDFEEQU_STATE_CONFIGURED, XDFEEQU_STATE_RESET.
Referenced by XDfeEqu_PassThroughExample, XDfeEqu_SelfExample.
void XDfeEqu_Initialize(XDfeEqu *InstancePtr, const XDfeEqu_EqConfig *Config)
DFE Equalizer driver one time initialisation and moves the state machine to a Initialised state.
InstancePtr Pointer to the Equalizer instance. Config Configuration data container.
References XDfeEqu_EqConfig::DatapathMode, XDfeEqu_Trigger::Mode, XDfeEqu::StateId, XDfeEqu_Trigger::TriggerEnable, XDFEEQU_DATAPATH_MODE_REAL, XDFEEQU_STATE_CONFIGURED, XDFEEQU_STATE_INITIALISED.
Referenced by XDfeEqu_PassThroughExample, XDfeEqu_SelfExample.
void XDfeEqu_Activate(XDfeEqu *InstancePtr, bool EnableLowPower)
Activates channel Equalizer moves the state machine to an Activated state.
InstancePtr Pointer to the Equalizer instance. EnableLowPower Flag indicating low power.
References XDfeEqu::StateId, XDFEEQU_STATE_INITIALISED, XDFEEQU_STATE_OPERATIONAL.
Referenced by XDfeEqu_PassThroughExample, XDfeEqu_SelfExample.
void XDfeEqu_Deactivate(XDfeEqu *InstancePtr)
Deactivates Equalizer and moves the state machine to Initialised state.
InstancePtr Pointer to the Equalizer instance.
References XDfeEqu::StateId, XDFEEQU_STATE_INITIALISED, XDFEEQU_STATE_OPERATIONAL.
Referenced by XDfeEqu_PassThroughExample, XDfeEqu_SelfExample.
XDfeEqu_StateId XDfeEqu_GetStateID(XDfeEqu *InstancePtr)
Gets a state machine state id.
InstancePtr Pointer to the Equalizer instance. State machine StateID
References XDfeEqu::StateId.
void XDfeEqu_Update(const XDfeEqu *InstancePtr, const XDfeEqu_EqConfig *Config)
Updates Equalizer mode.
Config.DatapathMode defines real or complex Equalizer mode. Config.RealDatapathSet and Config.ImDatapathSet defines which coefficient set to be used in real or complex mode. Config.Flush = 1 instructs to flush the buffers. InstancePtr Pointer to the Equalizer instance. Config configuration container.
References XDfeEqu_EqConfig::DatapathMode, XDfeEqu_EqConfig::Flush, XDfeEqu_EqConfig::ImDatapathSet, XDfeEqu_EqConfig::RealDatapathSet, XDFEEQU_DATAPATH_MODE_COMPLEX.
void XDfeEqu_GetTriggersCfg(const XDfeEqu *InstancePtr, XDfeEqu_TriggerCfg *TriggerCfg)
Returns current trigger configuration.
InstancePtr Pointer to the Equalizer instance. TriggerCfg Trigger configuration container.
References XDfeEqu_TriggerCfg::Activate, XDfeEqu_TriggerCfg::LowPower, XDfeEqu_Trigger::Mode, XDfeEqu::StateId, XDfeEqu_Trigger::StateOutput, XDfeEqu_Trigger::TriggerEnable, XDfeEqu_Trigger::TUSERBit, XDfeEqu_Trigger::TuserEdgeLevel, XDfeEqu_TriggerCfg::Update, XDFEEQU_STATE_NOT_READY.
void XDfeEqu_SetTriggersCfg(const XDfeEqu *InstancePtr, XDfeEqu_TriggerCfg *TriggerCfg)
Sets trigger configuration.
InstancePtr Pointer to the Equalizer instance. TriggerCfg Trigger configuration container.
References XDfeEqu_TriggerCfg::Activate, XDfeEqu_TriggerCfg::LowPower, XDfeEqu_Trigger::Mode, XDfeEqu::StateId, XDfeEqu_Trigger::StateOutput, XDfeEqu_Trigger::TriggerEnable, XDfeEqu_Trigger::TUSERBit, XDfeEqu_Trigger::TuserEdgeLevel, XDfeEqu_TriggerCfg::Update, XDFEEQU_STATE_INITIALISED.
Referenced by XDfeEqu_PassThroughExample.
void XDfeEqu_LoadCoefficients(const XDfeEqu *InstancePtr, u32 ChannelField, u32 Mode, u32 Shift, const XDfeEqu_Coefficients *EqCoeffs)
Sets Equalizer filter coefficients in Real, Complex or Matrix mode.
InstancePtr Pointer to the Equalizer instance. ChannelField Flag in which bits indicate the channel is enabled. Mode Equalizer mode. Shift Coefficient shift value. EqCoeffs Equalizer coefficients container.
References XDfeEqu_Coefficients::Num, XDfeEqu_Coefficients::Set, XDfeEqu::StateId, XDFEEQU_DATAPATH_MODE_COMPLEX, XDFEEQU_DATAPATH_MODE_REAL, XDFEEQU_NUM_COEFF, XDFEEQU_STATE_OPERATIONAL.
Referenced by XDfeEqu_PassThroughExample.
void XDfeEqu_GetActiveSets(const XDfeEqu *InstancePtr, u32 *RealSet, u32 *ImagSet)
Gets used coefficients settings.
InstancePtr Pointer to the Equalizer instance. RealSet Pointer to a real value. ImagSet Pointer to an imaginary value.
References XDfeEqu::StateId, XDFEEQU_STATE_OPERATIONAL.
void XDfeEqu_SetTUserDelay(const XDfeEqu *InstancePtr, u32 Delay)
Sets the delay, which will be added to TUSER and TLAST (delay matched through the IP).
InstancePtr Pointer to the Equalizer instance. Delay Requested delay variable.
References XDfeEqu::StateId, XDFEEQU_STATE_INITIALISED.
u32 XDfeEqu_GetTUserDelay(const XDfeEqu *InstancePtr)
Reads the delay, which will be added to TUSER and TLAST (delay matched through the IP).
InstancePtr Pointer to the Equalizer instance. Delay value
u32 XDfeEqu_GetTDataDelay(const XDfeEqu *InstancePtr, u32 Tap)
Returns data latency + tap, where the tap is between 0 and 23 in real mode and between 0 and 11 in complex mode.
InstancePtr Pointer to the Equalizer instance. Tap Tap value. Data latency value.
References XDFEEQU_TAP_MAX.
void XDfeEqu_GetVersions(const XDfeEqu *InstancePtr, XDfeEqu_Version *SwVersion, XDfeEqu_Version *HwVersion)
This API gets the driver and HW design version.
SwVersion Driver version number. HwVersion HW version number.
References XDfeEqu_Version::Major, XDfeEqu_Version::Minor, XDfeEqu_Version::Patch, XDfeEqu_Version::Revision, XDfeEqu::StateId, XDFEEQU_DRIVER_VERSION_MAJOR, XDFEEQU_DRIVER_VERSION_MINOR, XDFEEQU_STATE_NOT_READY.
Referenced by XDfeEqu_PassThroughExample, XDfeEqu_SelfExample.
void XDfeEqu_GetEventStatus(const XDfeEqu *InstancePtr, XDfeEqu_Status *Status)
Gets event status.
InstancePtr Pointer to the Equalizer instance. Status Equalizer status container.
References XDfeEqu_Status::IStatus, XDfeEqu_Status::QStatus, XDFEEQU_CHANNEL_NUM.
void XDfeEqu_ClearEventStatus(const XDfeEqu *InstancePtr, const XDfeEqu_Status *Status)
Clears Equalizer status.
The channel status will be cleared for any IStatus or QStatus not equal 0. InstancePtr Pointer to the Equalizer instance. Status Equalizer status container. The Status registers are only present for a given channel when it is present in the configured IP. The number of channels present is given by CONFIG.NUM_CHANNELS.
References XDfeEqu_Status::IStatus, XDfeEqu_Status::QStatus, XDFEEQU_CHANNEL_NUM.
void XDfeEqu_SetInterruptMask(const XDfeEqu *InstancePtr, const XDfeEqu_InterruptMask *InterruptMask)
Enables an Equalizer status for channel ID.
InstancePtr Pointer to the Equalizer instance. InterruptMask Equalizer interrupt mask container. The Status Mask registers are only present for a given channel when it is present in the configured IP. The number of channels present is given by CONFIG.NUM_CHANNELS.
References XDfeEqu_InterruptMask::Mask, XDFEEQU_CHANNEL_NUM.
void XDfeEqu_GetInterruptMask(const XDfeEqu *InstancePtr, XDfeEqu_InterruptMask *InterruptMask)
Gets interrupt mask.
InstancePtr Pointer to the Equalizer instance. InterruptMask Equalizer interrupt mask container.
References XDfeEqu_InterruptMask::Mask, XDFEEQU_CHANNEL_NUM.
int XDfeEqu_SelfExample()
This function runs the DFE Equalizer device using the driver APIs.
This function does the following tasks: Create and system initialize the device driver instance.Read SW and HW version numbers.Reset the device.Configure the device.Initialize the device.Activate the device.DeActivate the device. XST_SUCCESS if the example has completed successfully.XST_FAILURE if the example has failed.//! [testexample1]
References XDfeEqu_EqConfig::DatapathMode, XDfeEqu_Version::Major, XDfeEqu_Version::Minor, XDfeEqu_Version::Patch, XDfeEqu_Version::Revision, XDfeEqu_Activate, XDfeEqu_Configure, XDfeEqu_Deactivate, XDfeEqu_GetVersions, XDfeEqu_Initialize, XDfeEqu_InstanceClose, XDfeEqu_InstanceInit, XDfeEqu_Reset, XST_FAILURE, XST_SUCCESS.
Referenced by main.
int XDfeEqu_PassThroughExample()
This function runs the DFE Equalizer device using the driver APIs.
This function does the following tasks: Create and system initialize the device driver instance.Read SW and HW version numbers.Reset the device.Configure the device.Initialize the device.Set the triggersActivate the device.Load an equalizer coefficients.DeActivate the device. XST_SUCCESS if the example has completed successfully.XST_FAILURE if the example has failed.//! [testexample2]
References XDfeEqu_TriggerCfg::Activate, XDfeEqu_Coefficients::Coefficients, XDfeEqu_EqConfig::DatapathMode, XDfeEqu_Version::Major, XDfeEqu_Version::Minor, XDfeEqu_Trigger::Mode, XDfeEqu_Version::Patch, XDfeEqu_Version::Revision, XDfeEqu_Trigger::TUSERBit, XDfeEqu_Trigger::TuserEdgeLevel, XDfeEqu_TriggerCfg::Update, XDfeEqu_Activate, XDfeEqu_Configure, XDfeEqu_Deactivate, XDfeEqu_GetVersions, XDfeEqu_Initialize, XDfeEqu_InstanceClose, XDfeEqu_InstanceInit, XDfeEqu_LoadCoefficients, XDfeEqu_Reset, XDfeEqu_SetTriggersCfg, XST_FAILURE, XST_SUCCESS.
Referenced by main.
XDFEEQU_TAP_MAX
Maximum tap value.
Referenced by XDfeEqu_GetTDataDelay.
XDFEEQU_DRIVER_VERSION_MINOR
Driver's minor version number.
Referenced by XDfeEqu_GetVersions.
XDFEEQU_DRIVER_VERSION_MAJOR
Driver's major version number.
Referenced by XDfeEqu_GetVersions.
XDFEEQU_MAX_NUM_INSTANCES
Maximum number of driver instances running at the same time.
XDFEEQU_INSTANCE_EXISTS
XST_SUCCESS
Success flag.
Referenced by main, XDfeEqu_InstanceInit, XDfeEqu_PassThroughExample, XDfeEqu_SelfExample, XDfeSi570_SetMgtOscillator.
XST_FAILURE
Failure flag.
Referenced by main, XDfeEqu_InstanceInit, XDfeEqu_PassThroughExample, XDfeEqu_SelfExample, XDfeSi570_SetMgtOscillator.
XDFEEQU_NODE_NAME_MAX_LENGTH
Node name maximum length.
Referenced by XDfeEqu_InstanceInit.
XDFEEQU_ANT_NUM_MAX
Maximum anntena number.
XDFEEQU_CHANNEL_NUM
Maximum channel number.
Referenced by XDfeEqu_ClearEventStatus, XDfeEqu_GetEventStatus, XDfeEqu_GetInterruptMask, XDfeEqu_SetInterruptMask.
XDFEEQU_MAX_NUMBER_OF_UNITS_COMPLEX
Complex units number.
XDFEEQU_MAX_NUMBER_OF_UNITS_REAL
Real units number.
XDFEEQU_NUM_COEFF
Maximum number of coefficients.
Referenced by XDfeEqu_LoadCoefficients.
XDFEEQU_DATAPATH_MODE_REAL
Real mode.
Referenced by XDfeEqu_Initialize, XDfeEqu_LoadCoefficients.
XDFEEQU_DATAPATH_MODE_COMPLEX
Complex mode.
Referenced by XDfeEqu_LoadCoefficients, XDfeEqu_Update.
XDFEEQU_COMPATIBLE_STRING
Device name property.
XDFEEQU_PLATFORM_DEVICE_DIR
Device location in a file system.
XDFEEQU_COMPATIBLE_PROPERTY
Device tree property.
XDFEEQU_BUS_NAME
System bus name.
XDFEEQU_BASEADDR_PROPERTY
Base address property.
XDFEEQU_BASEADDR_SIZE
Base address bit-size.
XDFEEQU_COMPLEX_MODE_CFG
Complex mode enabled property.
XDFEEQU_COMPONENT_NAME_CFG
Component name property.
XDFEEQU_DATA_IWIDTH_CFG
Data IWIDTH property.
XDFEEQU_DATA_OWIDTH_CFG
Data OWIDTH property.
XDFEEQU_MAX_SAMPLE_RATE_CFG
Sample rate property.
XDFEEQU_NUM_CHANNELS_CFG
Number of channels property.
XDFEEQU_TUSER_WIDTH_CFG
Width of the TUSER bus.
XDFEEQU_USE_EMULATION_CFG
Use emulation property.