xdfeequ_examples.c
int XDfeSi570_SetMgtOscillator(double CurrentFrequency, double NewFrequency)
This function: initialize I2C bus, reads current state of si570, calculates parameters for si570 MGT oscillator new frequency, writes them to si570 and resets PL to use the new frequency.
CurrentFrequency MGT oscillator current frequency. NewFrequency MGT oscillator new frequency. None None
References XST_FAILURE, XST_SUCCESS.
Referenced by main.
int XDfeEqu_SelfExample()
This function runs the DFE Equalizer device using the driver APIs.
This function does the following tasks: Create and system initialize the device driver instance.Read SW and HW version numbers.Reset the device.Configure the device.Initialize the device.Activate the device.DeActivate the device. XST_SUCCESS if the example has completed successfully.XST_FAILURE if the example has failed.//! [testexample1]
References XST_SUCCESS, XST_FAILURE, XDfeEqu_InstanceInit, XDfeEqu_GetVersions, XDfeEqu_Version::Major, XDfeEqu_Version::Minor, XDfeEqu_Version::Revision, XDfeEqu_Version::Patch, XDfeEqu_Reset, XDfeEqu_Configure, XDfeEqu_EqConfig::DatapathMode, XDfeEqu_Initialize, XDfeEqu_Activate, XDfeEqu_Deactivate, XDfeEqu_InstanceClose.
Referenced by main.
int XDfeEqu_PassThroughExample()
This function runs the DFE Equalizer device using the driver APIs.
This function does the following tasks: Create and system initialize the device driver instance.Read SW and HW version numbers.Reset the device.Configure the device.Initialize the device.Set the triggersActivate the device.Load an equalizer coefficients.DeActivate the device. XST_SUCCESS if the example has completed successfully.XST_FAILURE if the example has failed.//! [testexample2]
References XST_SUCCESS, XST_FAILURE, XDfeEqu_InstanceInit, XDfeEqu_GetVersions, XDfeEqu_Version::Major, XDfeEqu_Version::Minor, XDfeEqu_Version::Revision, XDfeEqu_Version::Patch, XDfeEqu_Reset, XDfeEqu_Configure, XDfeEqu_EqConfig::DatapathMode, XDfeEqu_Initialize, XDfeEqu_TriggerCfg::Activate, XDfeEqu_Trigger::Mode, XDfeEqu_Trigger::TuserEdgeLevel, XDfeEqu_Trigger::TUSERBit, XDfeEqu_TriggerCfg::Update, XDfeEqu_SetTriggersCfg, XDfeEqu_Activate, XDfeEqu_Coefficients::Coefficients, XDfeEqu_LoadCoefficients, XDfeEqu_Deactivate, XDfeEqu_InstanceClose.
Referenced by main.
int main(void)
Main function that initialise si570 and runs examples.
None. XST_SUCCESS if the example has completed successfully.XST_FAILURE if the example has failed.
References XDfeEqu_PassThroughExample, XDfeEqu_SelfExample, XDfeSi570_SetMgtOscillator, XST_FAILURE, XST_SUCCESS.