vtc
XVTC_HANDLER_FRAMESYNC
A frame sync event interrupt type.
Referenced by XVtc_SetCallBack.
XVTC_HANDLER_LOCK
A signal lock event interrupt type.
Referenced by XVtc_SetCallBack.
XVTC_HANDLER_DETECTOR
A detector event interrupt type.
Referenced by XVtc_SetCallBack.
XVTC_HANDLER_GENERATOR
A generator event interrupt type.
Referenced by XVtc_SetCallBack.
XVTC_HANDLER_ERROR
An error condition interrupt type.
Referenced by XVtc_SetCallBack.
XVTC_EN_GENERATOR
To enable generator.
XVTC_EN_DETECTOR
To enable detector.
XVTC_REG_ADDRGAP
Register address gap.
Referenced by XVtc_GetFSync, XVtc_SetFSync.
XVTC_VMODE_720P
Video mode 720P.
Referenced by XVtc_ConvTiming2VideoMode, XVtc_ConvVideoMode2Timing.
XVTC_VMODE_1080P
Video mode 1080P.
Referenced by XVtc_ConvTiming2VideoMode, XVtc_ConvVideoMode2Timing.
XVTC_VMODE_480P
Video mode 480P.
Referenced by XVtc_ConvTiming2VideoMode, XVtc_ConvVideoMode2Timing.
XVTC_VMODE_576P
Video mode 576P.
Referenced by XVtc_ConvTiming2VideoMode, XVtc_ConvVideoMode2Timing.
XVTC_VMODE_VGA
Video mode VGA.
Referenced by XVtc_ConvTiming2VideoMode, XVtc_ConvVideoMode2Timing.
XVTC_VMODE_SVGA
Video mode SVGA.
Referenced by XVtc_ConvTiming2VideoMode, XVtc_ConvVideoMode2Timing.
XVTC_VMODE_XGA
Video mode XGA.
Referenced by XVtc_ConvTiming2VideoMode, XVtc_ConvVideoMode2Timing.
XVTC_VMODE_SXGA
Video mode SXGA.
Referenced by XVtc_ConvTiming2VideoMode, XVtc_ConvVideoMode2Timing.
XVTC_VMODE_WXGAPLUS
Video mode WXGAPlus.
Referenced by XVtc_ConvTiming2VideoMode, XVtc_ConvVideoMode2Timing.
XVTC_VMODE_WSXGAPLUS
Video mode WSXGAPlus.
Referenced by XVtc_ConvTiming2VideoMode, XVtc_ConvVideoMode2Timing.
XVTC_VMODE_1080I
Video mode 1080I.
Referenced by XVtc_ConvTiming2VideoMode, XVtc_ConvVideoMode2Timing.
XVTC_VMODE_NTSC
Video mode NTSC.
Referenced by XVtc_ConvTiming2VideoMode, XVtc_ConvVideoMode2Timing.
XVTC_VMODE_PAL
Video mode PAL.
Referenced by XVtc_ConvTiming2VideoMode, XVtc_ConvVideoMode2Timing.
XVtc_RegUpdate
XVTC_CTL_OFFSET
Control Register Offset.
Referenced by XVtc_Disable, XVtc_DisableDetector, XVtc_DisableGenerator, XVtc_Enable, XVtc_EnableDetector, XVtc_EnableGenerator, XVtc_GetSource, XVtc_SetSource.
XVTC_ISR_OFFSET
Status/Interrupt Status Register Offset.
XVTC_ERROR_OFFSET
Error Register Offset.
XVTC_IER_OFFSET
Interrupt Enable Register Offset.
XVTC_VER_OFFSET
Version Register Offset.
Referenced by XVtc_GetVersion, XVtc_SelfTest.
XVTC_ADAPTIVE_CTL_OFFSET
Adaptive-Sync Control Offset.
Referenced by XVtc_DisableAdaptiveSync, XVtc_SetAdaptiveSyncMode.
XVTC_VFP_STRETCH_OFFSET
VFP Stretch Limit Offset.
Referenced by XVtc_SetVfpStretchLimit.
XVTC_DASIZE_OFFSET
Detector Active Size Offset.
Referenced by XVtc_GetDetector.
XVTC_DTSTAT_OFFSET
Detector Timing Status Offset.
XVTC_DFENC_OFFSET
Detector Encoding Offset.
Referenced by XVtc_GetDetector.
XVTC_DPOL_OFFSET
Detector Polarity Offset.
Referenced by XVtc_GetDetectorPolarity.
XVTC_DHSIZE_OFFSET
Detector Frame Horizontal Size Offset.
Referenced by XVtc_GetDetector.
XVTC_DVSIZE_OFFSET
Detector Frame Vertical Size Offset.
Referenced by XVtc_GetDetector.
XVTC_DHSYNC_OFFSET
Detector Horizontal sync Offset.
Referenced by XVtc_GetDetector.
XVTC_DVBHOFF_OFFSET
Detector Frame/F0 Vblank Horizontal Offset.
Referenced by XVtc_GetDetectorHoriOffset.
XVTC_DVSYNC_OFFSET
Detector Frame/F0 Vertical Sync Offset.
Referenced by XVtc_GetDetector.
XVTC_DVSHOFF_OFFSET
Detector Frame/F0 Vsync Horizontal Offset.
Referenced by XVtc_GetDetectorHoriOffset.
XVTC_DVBHOFF_F1_OFFSET
Detector Field 1 Vblank Horizontal Offset.
Referenced by XVtc_GetDetectorHoriOffset.
XVTC_DVSYNC_F1_OFFSET
Detector Field 1 Vertical Sync Offset.
Referenced by XVtc_GetDetector.
XVTC_DVSHOFF_F1_OFFSET
Detector Field 1 Vsync Horizontal Offset.
Referenced by XVtc_GetDetectorHoriOffset.
XVTC_GASIZE_OFFSET
Generator Active Size Offset.
Referenced by XVtc_GetGenerator, XVtc_SetGenerator.
XVTC_GTSTAT_OFFSET
Generator Timing Status Offset.
XVTC_GFENC_OFFSET
Generator Encoding Offset.
Referenced by XVtc_GetGenerator, XVtc_GetSkipLine, XVtc_GetSkipPixel, XVtc_SetGenerator, XVtc_SetSkipLine, XVtc_SetSkipPixel.
XVTC_GPOL_OFFSET
Generator Polarity Offset.
Referenced by XVtc_GetPolarity, XVtc_SetPolarity.
XVTC_GHSIZE_OFFSET
Generator Frame Horizontal Size Offset.
Referenced by XVtc_GetGenerator, XVtc_SetGenerator.
XVTC_GVSIZE_OFFSET
Generator Frame Vertical Size Offset.
Referenced by XVtc_GetGenerator, XVtc_SetGenerator.
XVTC_GHSYNC_OFFSET
Generator Horizontal Sync Offset.
Referenced by XVtc_GetGenerator, XVtc_SetGenerator.
XVTC_GVBHOFF_OFFSET
Generator Frame/F0 Vblank Horizontal Offset.
Referenced by XVtc_GetGeneratorHoriOffset, XVtc_SetGeneratorHoriOffset.
XVTC_GVSYNC_OFFSET
Generator Frame/F0 Vertical Sync Offset.
Referenced by XVtc_GetGenerator, XVtc_SetGenerator.
XVTC_GVSHOFF_OFFSET
Generator Frame/F0 Vsync horizontal Offset.
Referenced by XVtc_GetGeneratorHoriOffset, XVtc_SetGeneratorHoriOffset.
XVTC_GVBHOFF_F1_OFFSET
Generator Field 1 Vblank Horizontal Offset.
Referenced by XVtc_GetGeneratorHoriOffset, XVtc_SetGeneratorHoriOffset.
XVTC_GVSYNC_F1_OFFSET
Generator Field 1 Vertical Sync Offset.
Referenced by XVtc_GetDetector, XVtc_GetGenerator, XVtc_SetGenerator.
XVTC_GVSHOFF_F1_OFFSET
Generator Field 1 Vsync horizontal Offset.
Referenced by XVtc_GetGeneratorHoriOffset, XVtc_SetGeneratorHoriOffset.
XVTC_GASIZE_F1_OFFSET
Generator Field 1 Active Size Offset.
Referenced by XVtc_SetGenerator.
XVTC_FS00_OFFSET
Frame Sync 00 Config Register Offset.
Referenced by XVtc_GetFSync, XVtc_SetFSync.
XVTC_FS01_OFFSET
Frame Sync 01 Config Register Offset.
XVTC_FS02_OFFSET
Frame Sync 02 Config Register Offset.
XVTC_FS03_OFFSET
Frame Sync 03 Config Register Offset.
XVTC_FS04_OFFSET
Frame Sync 04 Config Register Offset.
XVTC_FS05_OFFSET
Frame Sync 05 Config Register Offset.
XVTC_FS06_OFFSET
Frame Sync 06 Config Register Offset.
XVTC_FS07_OFFSET
Frame Sync 07 Config Register Offset.
XVTC_FS08_OFFSET
Frame Sync 08 Config Register Offset.
XVTC_FS09_OFFSET
Frame Sync 09 Config Register Offset.
XVTC_FS10_OFFSET
Frame Sync 10 Config Register Offset.
XVTC_FS11_OFFSET
Frame Sync 11 Config Register Offset.
XVTC_FS12_OFFSET
Frame Sync 12 Config Register Offset.
XVTC_FS13_OFFSET
Frame Sync 13 Config Register Offset.
XVTC_FS14_OFFSET
Frame Sync 14 Config Register Offset.
XVTC_FS15_OFFSET
Frame Sync 15 Config Register Offset.
XVTC_GGD_OFFSET
Generator Global Delay Register Offset.
Referenced by XVtc_GetDelay, XVtc_SetDelay.
XVTC_CTL_RESET_MASK
Software Reset Mask.
XVTC_CTL_SRST_MASK
Frame Sync'ed Software Reset Mask.
XVTC_CTL_FIPSS_MASK
Field ID Output Polarity Source Mask.
Referenced by XVtc_GetSource, XVtc_SetSource.
XVTC_CTL_ACPSS_MASK
Active Chroma Output Polarity Source Mask.
Referenced by XVtc_GetSource, XVtc_SetSource.
XVTC_CTL_AVPSS_MASK
Active Video Output Polarity Source Mask.
Referenced by XVtc_GetSource, XVtc_SetSource.
XVTC_CTL_HSPSS_MASK
Horizontal Sync Output Polarity Source Mask.
Referenced by XVtc_GetSource, XVtc_SetSource.
XVTC_CTL_VSPSS_MASK
Vertical Sync Output Polarity Source Mask.
Referenced by XVtc_GetSource, XVtc_SetSource.
XVTC_CTL_HBPSS_MASK
Horizontal Blank Output Polarity Source Mask.
Referenced by XVtc_GetSource, XVtc_SetSource.
XVTC_CTL_VBPSS_MASK
Vertical Blank Output Polarity Source Mask.
Referenced by XVtc_GetSource, XVtc_SetSource.
XVTC_CTL_INTERLACE_MASK
Interlaced mode.
Referenced by XVtc_GetSource, XVtc_SetSource.
XVTC_CTL_VCSS_MASK
Generator Chroma Polarity and Encoding Source Select Mask.
Referenced by XVtc_GetSource, XVtc_SetSource.
XVTC_CTL_VASS_MASK
Generator Vertical Blank Offset Source Select Mask.
Referenced by XVtc_GetSource, XVtc_SetSource.
XVTC_CTL_VBSS_MASK
Generator Vertical Sync End (Back porch start) Source Select Mask.
Referenced by XVtc_GetSource, XVtc_SetSource.
XVTC_CTL_VSSS_MASK
Generator Vertical Sync Start Source Select Mask.
Referenced by XVtc_GetSource, XVtc_SetSource.
XVTC_CTL_VFSS_MASK
Generator Vertical Active Size Source Select Mask.
Referenced by XVtc_GetSource, XVtc_SetSource.
XVTC_CTL_VTSS_MASK
Generator Vertical Total Source Select (Frame Size) Mask.
Referenced by XVtc_GetSource, XVtc_SetSource.
XVTC_CTL_HBSS_MASK
Horizontal Back Porch Start Register Source Select (Sync End) Mask.
Referenced by XVtc_GetSource, XVtc_SetSource.
XVTC_CTL_HSSS_MASK
Horizontal Sync Start Register Source Select Mask.
Referenced by XVtc_GetSource, XVtc_SetSource.
XVTC_CTL_HFSS_MASK
Horizontal Front Porch Start Register Source Select (Active Size) Mask.
Referenced by XVtc_GetSource, XVtc_SetSource.
XVTC_CTL_HTSS_MASK
Horizontal Total Register Source Select (Frame Size) Mask.
Referenced by XVtc_GetSource, XVtc_SetSource.
XVTC_CTL_ALLSS_MASK
Bit mask for all source select Mask.
Referenced by XVtc_SetSource.
XVTC_CTL_SE_MASK
Enable Sync with Detector.
XVTC_CTL_DE_MASK
VTC Detector Enable.
Referenced by XVtc_DisableDetector, XVtc_EnableDetector.
XVTC_CTL_GE_MASK
VTC Generator Enable.
Referenced by XVtc_DisableGenerator, XVtc_EnableGenerator.
XVTC_CTL_RU_MASK
VTC Register Update.
XVTC_CTL_SW_MASK
VTC Core Enable.
Referenced by XVtc_Disable, XVtc_Enable.
XVTC_ADAPTIVE_ENABLE_MASK
VTC Adaptive-Sync enable mask.
Referenced by XVtc_DisableAdaptiveSync, XVtc_SetAdaptiveSyncMode.
XVTC_ADAPTIVE_MODE_MASK
VTC Adaptive-Sync mode mask.
Referenced by XVtc_SetAdaptiveSyncMode.
XVTC_IXR_FSYNC15_MASK
Frame Sync Interrupt 15 Mask.
XVTC_IXR_FSYNC14_MASK
Frame Sync Interrupt 14 Mask.
XVTC_IXR_FSYNC13_MASK
Frame Sync Interrupt 13 Mask.
XVTC_IXR_FSYNC12_MASK
Frame Sync Interrupt 12 Mask.
XVTC_IXR_FSYNC11_MASK
Frame Sync Interrupt 11 Mask.
XVTC_IXR_FSYNC10_MASK
Frame Sync Interrupt 10 Mask.
XVTC_IXR_FSYNC09_MASK
Frame Sync Interrupt 09 Mask.
XVTC_IXR_FSYNC08_MASK
Frame Sync Interrupt 08 Mask.
XVTC_IXR_FSYNC07_MASK
Frame Sync Interrupt 07 Mask.
XVTC_IXR_FSYNC06_MASK
Frame Sync Interrupt 06 Mask.
XVTC_IXR_FSYNC05_MASK
Frame Sync Interrupt 05 Mask.
XVTC_IXR_FSYNC04_MASK
Frame Sync Interrupt 04 Mask.
XVTC_IXR_FSYNC03_MASK
Frame Sync Interrupt 03 Mask.
XVTC_IXR_FSYNC02_MASK
Frame Sync Interrupt 02 Mask.
XVTC_IXR_FSYNC01_MASK
Frame Sync Interrupt 01 Mask.
XVTC_IXR_FSYNC00_MASK
Frame Sync Interrupt 00 Mask.
XVTC_IXR_FSYNCALL_MASK
All Frame Sync Interrupt 0-15 Mask.
Referenced by XVtc_IntrHandler.
XVTC_IXR_G_AV_MASK
Generator Active Video Intr Mask.
XVTC_IXR_G_VBLANK_MASK
Generator VBLANK Interrupt Mask.
XVTC_IXR_G_ALL_MASK
All Generator interrupts Mask.
Referenced by XVtc_IntrHandler.
XVTC_IXR_D_AV_MASK
Detector Active Video Interrupt Mask.
XVTC_IXR_D_VBLANK_MASK
Detector VBLANK Interrupt Mask.
XVTC_IXR_D_ALL_MASK
All Detector Interrupts Mask.
Referenced by XVtc_IntrHandler.
XVTC_IXR_LOL_MASK
Lock Loss Mask.
XVTC_IXR_LO_MASK
Lock Mask.
XVTC_IXR_LOCKALL_MASK
All Signal Lock interrupt Mask.
Referenced by XVtc_IntrHandler.
XVTC_IXR_ALLINTR_MASK
Mask for all interrupts Mask.
XVTC_IXR_SPURIOUS_INTR_MASK
XVTC_ERR_ACL_MASK
Active Chroma Signal Lock Mask.
XVTC_ERR_AVL_MASK
Active Video Signal Lock Mask.
XVTC_ERR_HSL_MASK
Horizontal Sync Signal Lock Mask.
XVTC_ERR_VSL_MASK
Vertical Sync Signal Lock Mask.
XVTC_ERR_HBL_MASK
Horizontal Blank Signal Lock Mask.
XVTC_ERR_VBL_MASK
Vertical Blank Signal Lock Mask.
XVTC_VER_MAJOR_MASK
Major Version Mask.
XVTC_VER_MAJOR_SHIFT
Major Version Bit Shift.
XVTC_VER_MINOR_MASK
Minor Version Mask.
XVTC_VER_MINOR_SHIFT
Minor Version Bit Shift.
XVTC_VER_REV_MASK
Revision Version Mask.
XVTC_VER_REV_SHIFT
Revision Version Bit Shift.
XVTC_VER_IREV_MASK
Internal Revision Version Mask.
XVTC_VER_IREV_SHIFT
Internal Revision Bit Shift.
XVTC_ASIZE_VERT_MASK
Total number of lines (including blanking) for frame or field 1.
Referenced by XVtc_GetGenerator, XVtc_SetGenerator.
XVTC_ASIZE_VERT_SHIFT
Bit shift for End Cycle or Line Count.
Referenced by XVtc_GetGenerator, XVtc_SetGenerator.
XVTC_ASIZE_HORI_MASK
Horizontal Active Frame Size.The width of the frame without blanking in number of pixels or clocks.
Referenced by XVtc_GetGenerator, XVtc_SetGenerator.
XVTC_STAT_AVIDEO_MASK
Active Video Interrupt Status.Mask.
XVTC_STAT_VBLANK_MASK
Vertical Blank Interrupt Status Mask.
XVTC_STAT_LOCKED_MASK
Lock Status.
Set High when all signals have locked. (Detector only) Mask
XVTC_ENC_GACPS_MASK
Generator Active Chroma Pixel Skip/Parity Mask.
Referenced by XVtc_GetSkipPixel, XVtc_SetSkipPixel.
XVTC_ENC_CPARITY_MASK
Chroma Line Parity Mask.
Referenced by XVtc_GetDetector, XVtc_GetGenerator, XVtc_SetGenerator.
XVTC_ENC_CPARITY_SHIFT
Bit shift for Active Chroma Line Parity.
Referenced by XVtc_GetDetector, XVtc_GetGenerator, XVtc_SetGenerator.
XVTC_ENC_FPARITY_MASK
Field Parity Mask.
XVTC_ENC_PROG_MASK
Progressive/Interlaced Mask.
Referenced by XVtc_GetDetector, XVtc_GetGenerator, XVtc_SetGenerator.
XVTC_ENC_PROG_SHIFT
Progressive/Interlaced Shift.
Referenced by XVtc_GetDetector, XVtc_GetGenerator, XVtc_SetGenerator.
XVTC_ENC_GACLS_MASK
Generator Active Chroma Line Skip/parity Mask.
Referenced by XVtc_GetSkipLine, XVtc_SetSkipLine.
XVTC_POL_FIP_MASK
Field ID Output Polarity Mask.
Referenced by XVtc_GetDetectorPolarity, XVtc_GetPolarity, XVtc_SetPolarity.
XVTC_POL_ACP_MASK
Active Chroma Output Polarity Mask.
Referenced by XVtc_GetDetectorPolarity, XVtc_GetPolarity, XVtc_SetPolarity.
XVTC_POL_AVP_MASK
Active Video Output Polarity Mask.
Referenced by XVtc_GetDetectorPolarity, XVtc_GetPolarity, XVtc_SetPolarity.
XVTC_POL_HSP_MASK
Horizontal Sync Output Polarity Mask.
Referenced by XVtc_GetDetectorPolarity, XVtc_GetPolarity, XVtc_SetPolarity.
XVTC_POL_VSP_MASK
Vertical Sync Output Polarity Mask.
Referenced by XVtc_GetDetectorPolarity, XVtc_GetPolarity, XVtc_SetPolarity.
XVTC_POL_HBP_MASK
Horizontal Blank Output Polarity Mask.
Referenced by XVtc_GetDetectorPolarity, XVtc_GetPolarity, XVtc_SetPolarity.
XVTC_POL_VBP_MASK
Vertical Blank Output Polarity Mask.
Referenced by XVtc_GetDetectorPolarity, XVtc_GetPolarity, XVtc_SetPolarity.
XVTC_POL_ALLP_MASK
Bit mask for all polarity bits Mask.
Referenced by XVtc_SetPolarity.
XVTC_VSIZE_F1_MASK
Total number of lines (including blanking) for frame or field 1.
Referenced by XVtc_GetGenerator, XVtc_SetGenerator.
XVTC_VSIZE_F1_SHIFT
Bit shift for End Cycle or Line Count.
Referenced by XVtc_GetGenerator, XVtc_SetGenerator.
XVTC_VSIZE_F0_MASK
Total number of lines (including blanking) for frame or field 0.
Referenced by XVtc_GetGenerator, XVtc_SetGenerator.
XVTC_SB_END_MASK
End cycle or line count of horizontal sync, vertical sync or vertical blank.
Referenced by XVtc_SetGenerator.
XVTC_SB_END_SHIFT
Bit shift for End Cycle or Line Count.
Referenced by XVtc_GetDetector, XVtc_GetGenerator, XVtc_SetGenerator.
XVTC_SB_START_MASK
Start cycle or line count of horizontal sync, vertical sync or vertical blank.
Referenced by XVtc_GetDetector, XVtc_GetGenerator, XVtc_SetGenerator.
XVTC_XVXHOX_HEND_MASK
Horizontal Offset End Mask.
Referenced by XVtc_GetDetectorHoriOffset, XVtc_GetGeneratorHoriOffset, XVtc_SetGeneratorHoriOffset.
XVTC_XVXHOX_HEND_SHIFT
Horizontal End Shift.
Referenced by XVtc_GetDetectorHoriOffset, XVtc_GetGeneratorHoriOffset, XVtc_SetGeneratorHoriOffset.
XVTC_XVXHOX_HSTART_MASK
Horizontal Offset Start Offset.
Referenced by XVtc_GetDetectorHoriOffset, XVtc_GetGeneratorHoriOffset, XVtc_SetGeneratorHoriOffset.
XVTC_FSXX_VSTART_MASK
Vertical line count during which current Frame Sync is active Mask.
Referenced by XVtc_GetFSync, XVtc_SetFSync.
XVTC_FSXX_VSTART_SHIFT
Bit shift for the vertical line count.
Referenced by XVtc_GetFSync, XVtc_SetFSync.
XVTC_FSXX_HSTART_MASK
Horizontal cycle count during which current Frame Sync is active Mask.
Referenced by XVtc_GetFSync, XVtc_SetFSync.
XVTC_GGD_VDELAY_MASK
Total lines per frame to delay generator output Mask.
Referenced by XVtc_GetDelay, XVtc_SetDelay.
XVTC_GGD_VDELAY_SHIFT
Bit shift for the total lines.
Referenced by XVtc_GetDelay, XVtc_SetDelay.
XVTC_GGD_HDELAY_MASK
Total clock cycles per line to delay generator output Mask.
Referenced by XVtc_GetDelay, XVtc_SetDelay.
XVTC_CTL
XVTC_ISR
XVTC_ERROR
XVTC_IER
XVTC_VER
XVTC_DASIZE
XVTC_DTSTAT
XVTC_DFENC
XVTC_DPOL
XVTC_DHSIZE
XVTC_DVSIZE
XVTC_DHSYNC
XVTC_DVBHOFF
XVTC_DVSYNC
XVTC_DVSHOFF
XVTC_DVBHOFF_F1
XVTC_DVSYNC_F1
XVTC_DVSHOFF_F1
XVTC_GASIZE
XVTC_GTSTAT
XVTC_GFENC
XVTC_GPOL
XVTC_GHSIZE
XVTC_GVSIZE
XVTC_GHSYNC
XVTC_GVBHOFF
XVTC_GVSYNC
XVTC_GVSHOFF
XVTC_GVBHOFF_F1
XVTC_GVSYNC_F1
XVTC_GVSHOFF_F1
XVTC_FS00
XVTC_FS01
XVTC_FS02
XVTC_FS03
XVTC_FS04
XVTC_FS05
XVTC_FS06
XVTC_FS07
XVTC_FS08
XVTC_FS09
XVTC_FS10
XVTC_FS11
XVTC_FS12
XVTC_FS13
XVTC_FS14
XVTC_FS15
XVTC_GGD
XVtc_In32
Input Operations.
XVtc_Out32
Output Operations.
XVtc_ReadReg
This function macro reads the given register.
BaseAddress is the base address of the VTC core. RegOffset is the register offset of the register (defined at top of this file). The 32-bit value of the register. C-style signature: u32 XVtc_ReadReg(u32 BaseAddress, u32 RegOffset)
Referenced by XVtc_Disable, XVtc_DisableAdaptiveSync, XVtc_DisableDetector, XVtc_DisableGenerator, XVtc_Enable, XVtc_EnableDetector, XVtc_EnableGenerator, XVtc_GetDelay, XVtc_GetDetector, XVtc_GetDetectorHoriOffset, XVtc_GetDetectorPolarity, XVtc_GetFSync, XVtc_GetGenerator, XVtc_GetGeneratorHoriOffset, XVtc_GetPolarity, XVtc_GetSkipLine, XVtc_GetSkipPixel, XVtc_GetSource, XVtc_GetVersion, XVtc_SelfTest, XVtc_SetAdaptiveSyncMode, XVtc_SetGenerator, XVtc_SetPolarity, XVtc_SetSkipLine, XVtc_SetSkipPixel, XVtc_SetSource.
XVtc_WriteReg
Write the given register.
BaseAddress is the base address of the VTC core. RegOffset is the register offset of the register (defined at top of this file) to be written. Data is the 32-bit value to write to the register. None. C-style signature: void XVtc_WriteReg(u32 BaseAddress, u32 RegOffset, u32 Data)
Referenced by XVtc_Disable, XVtc_DisableAdaptiveSync, XVtc_DisableDetector, XVtc_DisableGenerator, XVtc_Enable, XVtc_EnableDetector, XVtc_EnableGenerator, XVtc_SetAdaptiveSyncMode, XVtc_SetDelay, XVtc_SetFSync, XVtc_SetGenerator, XVtc_SetGeneratorHoriOffset, XVtc_SetPolarity, XVtc_SetSkipLine, XVtc_SetSkipPixel, XVtc_SetSource, XVtc_SetVfpStretchLimit.
XVtc_AdaptiveSyncMode
typedef void(* XVtc_CallBack)(void *CallBackRef, u32 Mask))(void *CallBackRef, u32 Mask)
Callback type for all interrupts except error interrupt.
CallBackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. Mask is a bit mask indicating the cause of the event. For current core version, this parameter is "OR" of 0 or more XVTC_IXR_*_MASK constants defined in xvtc_hw.h. None. None.
typedef void(* XVtc_ErrorCallBack)(void *CallBackRef, u32 ErrorMask))(void *CallBackRef, u32 ErrorMask)
Callback type for Error interrupt.
CallBackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. ErrorMask is a bit mask indicating the cause of the error. For current core version, this parameter always have value 0 and could be ignored. None. None.
static void StubCallBack(void *CallBackRef, u32 Mask)
This routine is a stub for the asynchronous callbacks.
The stub is here in case the upper layer forgot to set the handlers. On initialization, all handlers except error handler are set to this callback. It is considered an error for this handler to be invoked. CallBackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. None. None.
static void StubErrCallBack(void *CallBackRef, u32 ErrorMask)
This routine is a stub for the asynchronous error interrupt callback.
The stub is here in case the upper layer forgot to set the handler. On initialization, Error interrupt handler is set to this callback. It is considered an error for this handler to be invoked. CallBackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. ErrorMask is a bit mask indicating the cause of the error. Its value equals 'OR'ing one or more XVTC_IXR_*_MASK values defined in xvtc_hw.h. None. None.
int XVtc_CfgInitialize(XVtc *InstancePtr, XVtc_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the VTC core.
This function must be called prior to using the VTC core. Initialization of the VTC includes setting up the instance data, and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the VTC core instance to be worked on. CfgPtr points to the configuration structure associated with the VTC core. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if XVtc_CfgInitialize was successful. None.
References XVtc_Config::BaseAddress, XVtc::Config, XVtc::DetectorCallBack, XVtc::ErrCallBack, XVtc::FrameSyncCallBack, XVtc::GeneratorCallBack, XVtc_Config::IntrId, XVtc_Config::IntrParent, XVtc::IsReady, XVtc::LockCallBack.
Referenced by XVtcSelfTestExample.
void XVtc_EnableGenerator(XVtc *InstancePtr)
This function enables the VTC Generator core.
InstancePtr is a pointer to the VTC instance to be worked on. None. None.
References XVtc_Config::BaseAddress, XVtc::Config, XVtc::IsReady, XVTC_CTL_GE_MASK, XVTC_CTL_OFFSET, XVtc_ReadReg, XVtc_WriteReg.
void XVtc_EnableDetector(XVtc *InstancePtr)
This function enables the VTC Detector core.
InstancePtr is a pointer to the VTC instance to be worked on. None. None.
References XVtc_Config::BaseAddress, XVtc::Config, XVtc::IsReady, XVTC_CTL_DE_MASK, XVTC_CTL_OFFSET, XVtc_ReadReg, XVtc_WriteReg.
void XVtc_Enable(XVtc *InstancePtr)
This function enables the Detector and Generator at same time of the VTC core.
InstancePtr is a pointer to the VTC instance to be worked on. None. None.
References XVtc_Config::BaseAddress, XVtc::Config, XVtc::IsReady, XVTC_CTL_OFFSET, XVTC_CTL_SW_MASK, XVtc_ReadReg, XVtc_WriteReg.
void XVtc_DisableGenerator(XVtc *InstancePtr)
This function disables the VTC Generator core.
InstancePtr is a pointer to the VTC instance to be worked on. None. None.
References XVtc_Config::BaseAddress, XVtc::Config, XVtc::IsReady, XVTC_CTL_GE_MASK, XVTC_CTL_OFFSET, XVtc_ReadReg, XVtc_WriteReg.
void XVtc_DisableDetector(XVtc *InstancePtr)
This function disables the VTC Detector core.
InstancePtr is a pointer to the VTC instance to be worked on. None. None.
References XVtc_Config::BaseAddress, XVtc::Config, XVtc::IsReady, XVTC_CTL_DE_MASK, XVTC_CTL_OFFSET, XVtc_ReadReg, XVtc_WriteReg.
void XVtc_Disable(XVtc *InstancePtr)
This function disables the Detector and Generator at same time of the VTC core.
InstancePtr is a pointer to the VTC instance to be worked on. None. None.
References XVtc_Config::BaseAddress, XVtc::Config, XVtc::IsReady, XVTC_CTL_OFFSET, XVTC_CTL_SW_MASK, XVtc_ReadReg, XVtc_WriteReg.
void XVtc_SetPolarity(XVtc *InstancePtr, XVtc_Polarity *PolarityPtr)
This function sets up the output polarity of the VTC core.
InstancePtr is a pointer to the VTC instance to be worked on. PolarityPtr points to a Polarity configuration structure with the setting to use on the VTC core. None. None.
References XVtc_Polarity::ActiveChromaPol, XVtc_Polarity::ActiveVideoPol, XVtc_Config::BaseAddress, XVtc::Config, XVtc_Polarity::FieldIdPol, XVtc_Polarity::HBlankPol, XVtc_Polarity::HSyncPol, XVtc::IsReady, XVtc_Polarity::VBlankPol, XVtc_Polarity::VSyncPol, XVTC_GPOL_OFFSET, XVTC_POL_ACP_MASK, XVTC_POL_ALLP_MASK, XVTC_POL_AVP_MASK, XVTC_POL_FIP_MASK, XVTC_POL_HBP_MASK, XVTC_POL_HSP_MASK, XVTC_POL_VBP_MASK, XVTC_POL_VSP_MASK, XVtc_ReadReg, XVtc_WriteReg.
Referenced by XVtc_SetGeneratorTiming.
void XVtc_GetPolarity(XVtc *InstancePtr, XVtc_Polarity *PolarityPtr)
This function gets the output polarity setting used by the VTC core.
InstancePtr is a pointer to the VTC instance to be worked on. PolarityPtr points to a Polarity configuration structure that will be populated with the setting used on the VTC core after this function returns. None. None.
References XVtc_Polarity::ActiveChromaPol, XVtc_Polarity::ActiveVideoPol, XVtc_Config::BaseAddress, XVtc::Config, XVtc_Polarity::FieldIdPol, XVtc_Polarity::HBlankPol, XVtc_Polarity::HSyncPol, XVtc::IsReady, XVtc_Polarity::VBlankPol, XVtc_Polarity::VSyncPol, XVTC_GPOL_OFFSET, XVTC_POL_ACP_MASK, XVTC_POL_AVP_MASK, XVTC_POL_FIP_MASK, XVTC_POL_HBP_MASK, XVTC_POL_HSP_MASK, XVTC_POL_VBP_MASK, XVTC_POL_VSP_MASK, XVtc_ReadReg.
Referenced by XVtc_GetGeneratorTiming.
void XVtc_GetDetectorPolarity(XVtc *InstancePtr, XVtc_Polarity *PolarityPtr)
This function gets the input polarity setting used by the VTC core.
InstancePtr is a pointer to the VTC instance to be worked on. PolarityPtr points to a Polarity configuration structure that will be populated with the setting used on the VTC core after this function returns. None. None.
References XVtc_Polarity::ActiveChromaPol, XVtc_Polarity::ActiveVideoPol, XVtc_Config::BaseAddress, XVtc::Config, XVtc_Polarity::FieldIdPol, XVtc_Polarity::HBlankPol, XVtc_Polarity::HSyncPol, XVtc::IsReady, XVtc_Polarity::VBlankPol, XVtc_Polarity::VSyncPol, XVTC_DPOL_OFFSET, XVTC_POL_ACP_MASK, XVTC_POL_AVP_MASK, XVTC_POL_FIP_MASK, XVTC_POL_HBP_MASK, XVTC_POL_HSP_MASK, XVTC_POL_VBP_MASK, XVTC_POL_VSP_MASK, XVtc_ReadReg.
Referenced by XVtc_GetDetectorTiming.
void XVtc_SetSource(XVtc *InstancePtr, XVtc_SourceSelect *SourcePtr)
This function sets up the source selecting of the VTC core.
InstancePtr is a pointer to the VTC instance to be worked on SourcePtr points to a Source Selecting configuration structure with the setting to use on the VTC device. None. None.
References XVtc_SourceSelect::ActiveChromaPolSrc, XVtc_SourceSelect::ActiveVideoPolSrc, XVtc_Config::BaseAddress, XVtc::Config, XVtc_SourceSelect::FieldIdPolSrc, XVtc_SourceSelect::HBackPorchSrc, XVtc_SourceSelect::HBlankPolSrc, XVtc_SourceSelect::HFrontPorchSrc, XVtc_SourceSelect::HSyncPolSrc, XVtc_SourceSelect::HSyncSrc, XVtc_SourceSelect::HTotalSrc, XVtc_SourceSelect::InterlacedMode, XVtc::IsReady, XVtc_SourceSelect::VActiveSrc, XVtc_SourceSelect::VBackPorchSrc, XVtc_SourceSelect::VBlankPolSrc, XVtc_SourceSelect::VChromaSrc, XVtc_SourceSelect::VFrontPorchSrc, XVtc_SourceSelect::VSyncPolSrc, XVtc_SourceSelect::VSyncSrc, XVtc_SourceSelect::VTotalSrc, XVTC_CTL_ACPSS_MASK, XVTC_CTL_ALLSS_MASK, XVTC_CTL_AVPSS_MASK, XVTC_CTL_FIPSS_MASK, XVTC_CTL_HBPSS_MASK, XVTC_CTL_HBSS_MASK, XVTC_CTL_HFSS_MASK, XVTC_CTL_HSPSS_MASK, XVTC_CTL_HSSS_MASK, XVTC_CTL_HTSS_MASK, XVTC_CTL_INTERLACE_MASK, XVTC_CTL_OFFSET, XVTC_CTL_VASS_MASK, XVTC_CTL_VBPSS_MASK, XVTC_CTL_VBSS_MASK, XVTC_CTL_VCSS_MASK, XVTC_CTL_VFSS_MASK, XVTC_CTL_VSPSS_MASK, XVTC_CTL_VSSS_MASK, XVTC_CTL_VTSS_MASK, XVtc_ReadReg, XVtc_WriteReg.
void XVtc_GetSource(XVtc *InstancePtr, XVtc_SourceSelect *SourcePtr)
This function gets the source select setting used by the VTC core.
InstancePtr is a pointer to the VTC instance to be worked on. SourcePtr points to a source select configuration structure that will be populated with the setting used on the VTC core after this function returns. None. None.
References XVtc_SourceSelect::ActiveChromaPolSrc, XVtc_SourceSelect::ActiveVideoPolSrc, XVtc_Config::BaseAddress, XVtc::Config, XVtc_SourceSelect::FieldIdPolSrc, XVtc_SourceSelect::HBackPorchSrc, XVtc_SourceSelect::HBlankPolSrc, XVtc_SourceSelect::HFrontPorchSrc, XVtc_SourceSelect::HSyncPolSrc, XVtc_SourceSelect::HSyncSrc, XVtc_SourceSelect::HTotalSrc, XVtc_SourceSelect::InterlacedMode, XVtc::IsReady, XVtc_SourceSelect::VActiveSrc, XVtc_SourceSelect::VBackPorchSrc, XVtc_SourceSelect::VBlankPolSrc, XVtc_SourceSelect::VChromaSrc, XVtc_SourceSelect::VFrontPorchSrc, XVtc_SourceSelect::VSyncPolSrc, XVtc_SourceSelect::VSyncSrc, XVtc_SourceSelect::VTotalSrc, XVTC_CTL_ACPSS_MASK, XVTC_CTL_AVPSS_MASK, XVTC_CTL_FIPSS_MASK, XVTC_CTL_HBPSS_MASK, XVTC_CTL_HBSS_MASK, XVTC_CTL_HFSS_MASK, XVTC_CTL_HSPSS_MASK, XVTC_CTL_HSSS_MASK, XVTC_CTL_HTSS_MASK, XVTC_CTL_INTERLACE_MASK, XVTC_CTL_OFFSET, XVTC_CTL_VASS_MASK, XVTC_CTL_VBPSS_MASK, XVTC_CTL_VBSS_MASK, XVTC_CTL_VCSS_MASK, XVTC_CTL_VFSS_MASK, XVTC_CTL_VSPSS_MASK, XVTC_CTL_VSSS_MASK, XVTC_CTL_VTSS_MASK, XVtc_ReadReg.
void XVtc_SetSkipLine(XVtc *InstancePtr, int GeneratorChromaSkip)
This function sets up the line skip setting of the Generator in the VTC core.
InstancePtr is a pointer to the VTC instance to be worked on. GeneratorChromaSkip indicates whether to skip 1 line between active chroma for the Generator module. Use Non-0 value for this parameter to skip 1 line, and 0 to not skip lines. None. None.
References XVtc_Config::BaseAddress, XVtc::Config, XVtc::IsReady, XVTC_ENC_GACLS_MASK, XVTC_GFENC_OFFSET, XVtc_ReadReg, XVtc_WriteReg.
void XVtc_GetSkipLine(XVtc *InstancePtr, int *GeneratorChromaSkipPtr)
This function gets the line skip setting used by the Generator in the VTC core.
InstancePtr is a pointer to the VTC instance to be worked on. GeneratorChromaSkipPtr will point to the value indicating whether one line is skipped between active chroma for the Generator module after this function returns. Value 1 means that 1 line is skipped and zero means that no lines are skipped. None. None.
References XVtc_Config::BaseAddress, XVtc::Config, XVtc::IsReady, XVTC_ENC_GACLS_MASK, XVTC_GFENC_OFFSET, XVtc_ReadReg.
void XVtc_SetSkipPixel(XVtc *InstancePtr, int GeneratorChromaSkip)
This function sets up the pixel skip setting of the Generator in the VTC core.
InstancePtr is a pointer to the VTC instance to be worked on. GeneratorChromaSkip indicates whether to skip 1 pixel between active chroma for the Generator module. Use Non-0 value for this parameter to skip 1 pixel, and 0 to not skip pixels None. None.
References XVtc_Config::BaseAddress, XVtc::Config, XVtc::IsReady, XVTC_ENC_GACPS_MASK, XVTC_GFENC_OFFSET, XVtc_ReadReg, XVtc_WriteReg.
void XVtc_GetSkipPixel(XVtc *InstancePtr, int *GeneratorChromaSkipPtr)
This function gets the pixel skip setting used by the Generator in the VTC core.
InstancePtr is a pointer to the VTC instance to be worked on. GeneratorChromaSkipPtr will point to the value indicating whether one pixel is skipped between active chroma for the Generator module after this function returns. Value 1 means that 1 pixel is skipped and zero means that no pixels are skipped. None. None.
References XVtc_Config::BaseAddress, XVtc::Config, XVtc::IsReady, XVTC_ENC_GACPS_MASK, XVTC_GFENC_OFFSET, XVtc_ReadReg.
void XVtc_SetDelay(XVtc *InstancePtr, int VertDelay, int HoriDelay)
This function sets up the Generator delay setting of the VTC core.
InstancePtr is a pointer to the VTC instance to be worked on. VertDelay indicates the number of total lines per frame to delay the generator output. The valid range is from 0 to 4095. HoriDelay indicates the number of total clock cycles per line to delay the generator output. The valid range is from 0 to 4095. None. None.
References XVtc_Config::BaseAddress, XVtc::Config, XVtc::IsReady, XVTC_GGD_HDELAY_MASK, XVTC_GGD_OFFSET, XVTC_GGD_VDELAY_MASK, XVTC_GGD_VDELAY_SHIFT, XVtc_WriteReg.
void XVtc_GetDelay(XVtc *InstancePtr, int *VertDelayPtr, int *HoriDelayPtr)
This function gets the Generator delay setting used by the VTC core.
InstancePtr is a pointer to the VTC instance to be worked on. VertDelayPtr will point to a value indicating the number of total lines per frame to delay the generator output after this function returns. HoriDelayPtr will point to a value indicating the number of total clock cycles per line to delay the generator output after this function returns. None. None.
References XVtc_Config::BaseAddress, XVtc::Config, XVtc::IsReady, XVTC_GGD_HDELAY_MASK, XVTC_GGD_OFFSET, XVTC_GGD_VDELAY_MASK, XVTC_GGD_VDELAY_SHIFT, XVtc_ReadReg.
void XVtc_SetFSync(XVtc *InstancePtr, u16 FrameSyncIndex, u16 VertStart, u16 HoriStart)
This function sets up the SYNC setting of a frame sync used by the VTC core.
InstancePtr is a pointer to the VTC instance to be worked on. FrameSyncIndex indicates the index number of the frame sync. The valid range is from 0 to 15. VertStart indicates the vertical line count during which the frame sync is active. The valid range is from 0 to 4095. HoriStart indicates the horizontal cycle count during which the frame sync is active. The valid range is from 0 to 4095. None. None.
References XVtc_Config::BaseAddress, XVtc::Config, XVtc::IsReady, XVTC_FS00_OFFSET, XVTC_FSXX_HSTART_MASK, XVTC_FSXX_VSTART_MASK, XVTC_FSXX_VSTART_SHIFT, XVTC_REG_ADDRGAP, XVtc_WriteReg.
void XVtc_GetFSync(XVtc *InstancePtr, u16 FrameSyncIndex, u16 *VertStartPtr, u16 *HoriStartPtr)
This function gets the SYNC setting of a frame sync used by the VTC core.
InstancePtr is a pointer to the VTC instance to be worked on. FrameSyncIndex indicates the index number of the frame sync. The valid range is from 0 to 15. VertStartPtr will point to the value that indicates the vertical line count during which the frame sync is active once this function returns. HoriStartPtr will point to the value that indicates the horizontal cycle count during which the frame sync is active once this function returns. None.
References XVtc_Config::BaseAddress, XVtc::Config, XVtc::IsReady, XVTC_FS00_OFFSET, XVTC_FSXX_HSTART_MASK, XVTC_FSXX_VSTART_MASK, XVTC_FSXX_VSTART_SHIFT, XVtc_ReadReg, XVTC_REG_ADDRGAP.
void XVtc_SetGeneratorHoriOffset(XVtc *InstancePtr, XVtc_HoriOffsets *HoriOffsets)
This function sets the VBlank/VSync Horizontal Offsets for the Generator in a VTC device.
InstancePtr is a pointer to the VTC device instance to be worked on. HoriOffsets points to a VBlank/VSync Horizontal Offset configuration with the setting to use on the VTC device. NONE.
References XVtc_Config::BaseAddress, XVtc::Config, XVtc::IsReady, XVtc_HoriOffsets::V0BlankHoriEnd, XVtc_HoriOffsets::V0BlankHoriStart, XVtc_HoriOffsets::V0SyncHoriEnd, XVtc_HoriOffsets::V0SyncHoriStart, XVtc_HoriOffsets::V1BlankHoriEnd, XVtc_HoriOffsets::V1BlankHoriStart, XVtc_HoriOffsets::V1SyncHoriEnd, XVtc_HoriOffsets::V1SyncHoriStart, XVTC_GVBHOFF_F1_OFFSET, XVTC_GVBHOFF_OFFSET, XVTC_GVSHOFF_F1_OFFSET, XVTC_GVSHOFF_OFFSET, XVtc_WriteReg, XVTC_XVXHOX_HEND_MASK, XVTC_XVXHOX_HEND_SHIFT, XVTC_XVXHOX_HSTART_MASK.
Referenced by XVtc_SetGenerator, XVtc_SetGeneratorTiming.
void XVtc_GetGeneratorHoriOffset(XVtc *InstancePtr, XVtc_HoriOffsets *HoriOffsets)
This function gets the VBlank/VSync Horizontal Offsets currently used by the Generator in the VTC core.
InstancePtr is a pointer to the VTC instance to be worked on. HoriOffsets points to a VBlank/VSync Horizontal Offset configuration structure that will be populated with the setting currently used on the Generator in the given VTC device after this function returns. None. None.
References XVtc_Config::BaseAddress, XVtc::Config, XVtc::IsReady, XVtc_HoriOffsets::V0BlankHoriEnd, XVtc_HoriOffsets::V0BlankHoriStart, XVtc_HoriOffsets::V0SyncHoriEnd, XVtc_HoriOffsets::V0SyncHoriStart, XVtc_HoriOffsets::V1BlankHoriEnd, XVtc_HoriOffsets::V1BlankHoriStart, XVtc_HoriOffsets::V1SyncHoriEnd, XVtc_HoriOffsets::V1SyncHoriStart, XVTC_GVBHOFF_F1_OFFSET, XVTC_GVBHOFF_OFFSET, XVTC_GVSHOFF_F1_OFFSET, XVTC_GVSHOFF_OFFSET, XVtc_ReadReg, XVTC_XVXHOX_HEND_MASK, XVTC_XVXHOX_HEND_SHIFT, XVTC_XVXHOX_HSTART_MASK.
Referenced by XVtc_GetGeneratorTiming.
void XVtc_GetDetectorHoriOffset(XVtc *InstancePtr, XVtc_HoriOffsets *HoriOffsets)
This function gets the VBlank/VSync Horizontal Offsets detected by the Detector in the VTC core.
InstancePtr is a pointer to the VTC instance to be worked on. HoriOffsets points to a VBlank/VSync Horizontal Offset configuration structure that will be populated with the setting detected on the Detector in the given VTC device after this function returns. None. None.
References XVtc_Config::BaseAddress, XVtc::Config, XVtc::IsReady, XVtc_HoriOffsets::V0BlankHoriEnd, XVtc_HoriOffsets::V0BlankHoriStart, XVtc_HoriOffsets::V0SyncHoriEnd, XVtc_HoriOffsets::V0SyncHoriStart, XVtc_HoriOffsets::V1BlankHoriEnd, XVtc_HoriOffsets::V1BlankHoriStart, XVtc_HoriOffsets::V1SyncHoriEnd, XVtc_HoriOffsets::V1SyncHoriStart, XVTC_DVBHOFF_F1_OFFSET, XVTC_DVBHOFF_OFFSET, XVTC_DVSHOFF_F1_OFFSET, XVTC_DVSHOFF_OFFSET, XVtc_ReadReg, XVTC_XVXHOX_HEND_MASK, XVTC_XVXHOX_HEND_SHIFT, XVTC_XVXHOX_HSTART_MASK.
Referenced by XVtc_GetDetectorTiming.
void XVtc_SetGenerator(XVtc *InstancePtr, XVtc_Signal *SignalCfgPtr)
This function sets up VTC signal to be used by the Generator module in the VTC core.
InstancePtr is a pointer to the VTC instance to be worked on. SignalCfgPtr is a pointer to the VTC signal configuration to be used by the Generator module in the VTC core. None. None.
References XVtc_Config::BaseAddress, XVtc::Config, XVtc_Signal::HActiveStart, XVtc_Signal::HBackPorchStart, XVtc_Signal::HFrontPorchStart, XVtc_Signal::HSyncStart, XVtc_Signal::HTotal, XVtc_Signal::Interlaced, XVtc::IsReady, XVtc_Signal::OriginMode, XVtc_Signal::V0ActiveStart, XVtc_Signal::V0BackPorchStart, XVtc_HoriOffsets::V0BlankHoriEnd, XVtc_HoriOffsets::V0BlankHoriStart, XVtc_Signal::V0ChromaStart, XVtc_Signal::V0FrontPorchStart, XVtc_HoriOffsets::V0SyncHoriEnd, XVtc_HoriOffsets::V0SyncHoriStart, XVtc_Signal::V0SyncStart, XVtc_Signal::V0Total, XVtc_Signal::V1BackPorchStart, XVtc_HoriOffsets::V1BlankHoriEnd, XVtc_HoriOffsets::V1BlankHoriStart, XVtc_HoriOffsets::V1SyncHoriEnd, XVtc_HoriOffsets::V1SyncHoriStart, XVtc_Signal::V1SyncStart, XVtc_Signal::V1Total, XVTC_ASIZE_HORI_MASK, XVTC_ASIZE_VERT_MASK, XVTC_ASIZE_VERT_SHIFT, XVTC_ENC_CPARITY_MASK, XVTC_ENC_CPARITY_SHIFT, XVTC_ENC_PROG_MASK, XVTC_ENC_PROG_SHIFT, XVTC_GASIZE_F1_OFFSET, XVTC_GASIZE_OFFSET, XVTC_GFENC_OFFSET, XVTC_GHSIZE_OFFSET, XVTC_GHSYNC_OFFSET, XVTC_GVSIZE_OFFSET, XVTC_GVSYNC_F1_OFFSET, XVTC_GVSYNC_OFFSET, XVtc_ReadReg, XVTC_SB_END_MASK, XVTC_SB_END_SHIFT, XVTC_SB_START_MASK, XVtc_SetGeneratorHoriOffset, XVTC_VSIZE_F0_MASK, XVTC_VSIZE_F1_MASK, XVTC_VSIZE_F1_SHIFT, XVtc_WriteReg.
Referenced by XVtc_SetGeneratorTiming.
void XVtc_GetGenerator(XVtc *InstancePtr, XVtc_Signal *SignalCfgPtr)
This function gets the VTC signal setting used by the Generator module in the VTC core.
InstancePtr is a pointer to the VTC instance to be worked on. SignalCfgPtr is a pointer to a VTC signal configuration which will be populated with the setting used by the Generator module in the VTC core once this function returns. None. None.
References XVtc_Config::BaseAddress, XVtc::Config, XVtc_Signal::HActiveStart, XVtc_Signal::HBackPorchStart, XVtc_Signal::HFrontPorchStart, XVtc_Signal::HSyncStart, XVtc_Signal::HTotal, XVtc_Signal::Interlaced, XVtc::IsReady, XVtc_Signal::OriginMode, XVtc_Signal::V0ActiveStart, XVtc_Signal::V0BackPorchStart, XVtc_Signal::V0ChromaStart, XVtc_Signal::V0FrontPorchStart, XVtc_Signal::V0SyncStart, XVtc_Signal::V0Total, XVtc_Signal::V1ActiveStart, XVtc_Signal::V1BackPorchStart, XVtc_Signal::V1ChromaStart, XVtc_Signal::V1FrontPorchStart, XVtc_Signal::V1SyncStart, XVtc_Signal::V1Total, XVTC_ASIZE_HORI_MASK, XVTC_ASIZE_VERT_MASK, XVTC_ASIZE_VERT_SHIFT, XVTC_ENC_CPARITY_MASK, XVTC_ENC_CPARITY_SHIFT, XVTC_ENC_PROG_MASK, XVTC_ENC_PROG_SHIFT, XVTC_GASIZE_OFFSET, XVTC_GFENC_OFFSET, XVTC_GHSIZE_OFFSET, XVTC_GHSYNC_OFFSET, XVTC_GVSIZE_OFFSET, XVTC_GVSYNC_F1_OFFSET, XVTC_GVSYNC_OFFSET, XVtc_ReadReg, XVTC_SB_END_SHIFT, XVTC_SB_START_MASK, XVTC_VSIZE_F0_MASK, XVTC_VSIZE_F1_MASK, XVTC_VSIZE_F1_SHIFT.
Referenced by XVtc_GetGeneratorTiming.
void XVtc_GetDetector(XVtc *InstancePtr, XVtc_Signal *SignalCfgPtr)
This function gets the VTC signal setting used by the Detector module in the VTC core.
InstancePtr is a pointer to the VTC instance to be worked on. SignalCfgPtr is a pointer to a VTC signal configuration which will be populated with the setting used by the Detector module in the VTC core once this function returns. None. None.
References XVtc_Config::BaseAddress, XVtc::Config, XVtc_Signal::HActiveStart, XVtc_Signal::HBackPorchStart, XVtc_Signal::HFrontPorchStart, XVtc_Signal::HSyncStart, XVtc_Signal::HTotal, XVtc_Signal::Interlaced, XVtc::IsReady, XVtc_Signal::OriginMode, XVtc_Signal::V0ActiveStart, XVtc_Signal::V0BackPorchStart, XVtc_Signal::V0ChromaStart, XVtc_Signal::V0FrontPorchStart, XVtc_Signal::V0SyncStart, XVtc_Signal::V0Total, XVtc_Signal::V1ActiveStart, XVtc_Signal::V1BackPorchStart, XVtc_Signal::V1ChromaStart, XVtc_Signal::V1FrontPorchStart, XVtc_Signal::V1SyncStart, XVtc_Signal::V1Total, XVTC_DASIZE_OFFSET, XVTC_DFENC_OFFSET, XVTC_DHSIZE_OFFSET, XVTC_DHSYNC_OFFSET, XVTC_DVSIZE_OFFSET, XVTC_DVSYNC_F1_OFFSET, XVTC_DVSYNC_OFFSET, XVTC_ENC_CPARITY_MASK, XVTC_ENC_CPARITY_SHIFT, XVTC_ENC_PROG_MASK, XVTC_ENC_PROG_SHIFT, XVTC_GVSYNC_F1_OFFSET, XVtc_ReadReg, XVTC_SB_END_SHIFT, XVTC_SB_START_MASK.
Referenced by XVtc_GetDetectorTiming.
u32 XVtc_GetVersion(XVtc *InstancePtr)
This function facilitates software identification of exact version of the VTC hardware (h/w).
InstancePtr is a pointer to the XVtc instance. Version, contents of a Version register. None.
References XVtc_Config::BaseAddress, XVtc::Config, XVtc_ReadReg, XVTC_VER_OFFSET.
void XVtc_ConvVideoMode2Timing(XVtc *InstancePtr, u16 Mode, XVtc_Timing *TimingPtr)
This function converts the video mode integer into the video timing information stored within the XVtc_Timing pointer.
InstancePtr is a pointer to the VTC instance to be worked on. Mode is a u16 int defined as macro to one of the predefined Video Modes. TimingPtr is a pointer to a VTC Video Timing Structure. None. None.
References XVtc_Timing::HActiveVideo, XVtc_Timing::HBackPorch, XVtc_Timing::HFrontPorch, XVtc_Timing::HSyncPolarity, XVtc_Timing::HSyncWidth, XVtc_Timing::Interlaced, XVtc::IsReady, XVtc_Timing::V0BackPorch, XVtc_Timing::V0FrontPorch, XVtc_Timing::V0SyncWidth, XVtc_Timing::V1BackPorch, XVtc_Timing::V1FrontPorch, XVtc_Timing::V1SyncWidth, XVtc_Timing::VActiveVideo, XVtc_Timing::VSyncPolarity, XVTC_VMODE_1080I, XVTC_VMODE_1080P, XVTC_VMODE_480P, XVTC_VMODE_576P, XVTC_VMODE_720P, XVTC_VMODE_NTSC, XVTC_VMODE_PAL, XVTC_VMODE_SVGA, XVTC_VMODE_SXGA, XVTC_VMODE_VGA, XVTC_VMODE_WSXGAPLUS, XVTC_VMODE_WXGAPLUS, XVTC_VMODE_XGA.
Referenced by XVtc_SetGeneratorVideoMode.
void XVtc_ConvTiming2Signal(XVtc *InstancePtr, XVtc_Timing *TimingPtr, XVtc_Signal *SignalCfgPtr, XVtc_HoriOffsets *HOffPtr, XVtc_Polarity *PolarityPtr)
This function converts the video timing structure into the VTC signal configuration structure, horizontal offsets structure and the polarity structure.
InstancePtr is a pointer to the VTC instance to be worked on. TimingPtr is a pointer to a Video Timing structure to be read. SignalCfgPtr is a pointer to a VTC signal configuration to be set. HOffPtr is a pointer to a VTC horizontal offsets structure to be set. PolarityPtr is a pointer to a VTC polarity structure to be set. None. None.
References XVtc_Polarity::ActiveChromaPol, XVtc_Polarity::ActiveVideoPol, XVtc_Polarity::FieldIdPol, XVtc_Signal::HActiveStart, XVtc_Timing::HActiveVideo, XVtc_Timing::HBackPorch, XVtc_Signal::HBackPorchStart, XVtc_Polarity::HBlankPol, XVtc_Timing::HFrontPorch, XVtc_Signal::HFrontPorchStart, XVtc_Polarity::HSyncPol, XVtc_Timing::HSyncPolarity, XVtc_Signal::HSyncStart, XVtc_Timing::HSyncWidth, XVtc_Signal::HTotal, XVtc_Signal::Interlaced, XVtc_Timing::Interlaced, XVtc::IsReady, XVtc_Signal::OriginMode, XVtc_Signal::V0ActiveStart, XVtc_Timing::V0BackPorch, XVtc_Signal::V0BackPorchStart, XVtc_HoriOffsets::V0BlankHoriEnd, XVtc_HoriOffsets::V0BlankHoriStart, XVtc_Signal::V0ChromaStart, XVtc_Timing::V0FrontPorch, XVtc_Signal::V0FrontPorchStart, XVtc_HoriOffsets::V0SyncHoriEnd, XVtc_HoriOffsets::V0SyncHoriStart, XVtc_Signal::V0SyncStart, XVtc_Timing::V0SyncWidth, XVtc_Signal::V0Total, XVtc_Signal::V1ActiveStart, XVtc_Timing::V1BackPorch, XVtc_Signal::V1BackPorchStart, XVtc_HoriOffsets::V1BlankHoriEnd, XVtc_HoriOffsets::V1BlankHoriStart, XVtc_Signal::V1ChromaStart, XVtc_Timing::V1FrontPorch, XVtc_Signal::V1FrontPorchStart, XVtc_HoriOffsets::V1SyncHoriEnd, XVtc_HoriOffsets::V1SyncHoriStart, XVtc_Signal::V1SyncStart, XVtc_Timing::V1SyncWidth, XVtc_Signal::V1Total, XVtc_Timing::VActiveVideo, XVtc_Polarity::VBlankPol, XVtc_Polarity::VSyncPol, XVtc_Timing::VSyncPolarity.
Referenced by XVtc_SetGeneratorTiming.
void XVtc_ConvSignal2Timing(XVtc *InstancePtr, XVtc_Signal *SignalCfgPtr, XVtc_HoriOffsets *HOffPtr, XVtc_Polarity *PolarityPtr, XVtc_Timing *TimingPtr)
This function converts the VTC signal structure, horizontal offsets structure and the polarity structure into the Video Timing structure.
InstancePtr is a pointer to the VTC instance to be worked on. SignalCfgPtr is a pointer to a VTC signal configuration to be read HOffPtr is a pointer to a VTC horizontal offsets structure to be read PolarityPtr is a pointer to a VTC polarity structure to be read. TimingPtr is a pointer to a Video Timing structure to be set. None. None.
References XVtc_Timing::HActiveVideo, XVtc_Timing::HBackPorch, XVtc_Signal::HBackPorchStart, XVtc_Timing::HFrontPorch, XVtc_Signal::HFrontPorchStart, XVtc_Polarity::HSyncPol, XVtc_Timing::HSyncPolarity, XVtc_Signal::HSyncStart, XVtc_Timing::HSyncWidth, XVtc_Signal::HTotal, XVtc_Signal::Interlaced, XVtc_Timing::Interlaced, XVtc::IsReady, XVtc_Signal::OriginMode, XVtc_Timing::V0BackPorch, XVtc_Signal::V0BackPorchStart, XVtc_Timing::V0FrontPorch, XVtc_Signal::V0FrontPorchStart, XVtc_Signal::V0SyncStart, XVtc_Timing::V0SyncWidth, XVtc_Signal::V0Total, XVtc_Timing::V1BackPorch, XVtc_Signal::V1BackPorchStart, XVtc_Timing::V1FrontPorch, XVtc_Signal::V1FrontPorchStart, XVtc_Signal::V1SyncStart, XVtc_Timing::V1SyncWidth, XVtc_Signal::V1Total, XVtc_Timing::VActiveVideo, XVtc_Polarity::VSyncPol, XVtc_Timing::VSyncPolarity.
Referenced by XVtc_GetDetectorTiming, XVtc_GetGeneratorTiming.
u16 XVtc_ConvTiming2VideoMode(XVtc *InstancePtr, XVtc_Timing *TimingPtr)
This function converts the video timing structure into predefined video mode values returned as a short integer.
InstancePtr is a pointer to the VTC instance to be worked on. TimingPtr is a pointer to a Video Timing structure to be read. VideoMode is the video mode of the VTC core. None.
References XVtc_Timing::HActiveVideo, XVtc_Timing::Interlaced, XVtc::IsReady, XVtc_Timing::VActiveVideo, XVTC_VMODE_1080I, XVTC_VMODE_1080P, XVTC_VMODE_480P, XVTC_VMODE_576P, XVTC_VMODE_720P, XVTC_VMODE_NTSC, XVTC_VMODE_PAL, XVTC_VMODE_SVGA, XVTC_VMODE_SXGA, XVTC_VMODE_VGA, XVTC_VMODE_WSXGAPLUS, XVTC_VMODE_WXGAPLUS, XVTC_VMODE_XGA.
Referenced by XVtc_GetDetectorVideoMode, XVtc_GetGeneratorVideoMode.
void XVtc_SetGeneratorTiming(XVtc *InstancePtr, XVtc_Timing *TimingPtr)
This function sets up the generator (Polarity, H/V values and horizontal offsets) by reading the configuration from a video timing structure.
InstancePtr is a pointer to the VTC instance to be worked on. TimingPtr is a pointer to a Video Timing Structure to be read. None. None.
References XVtc::IsReady, XVtc_ConvTiming2Signal, XVtc_SetGenerator, XVtc_SetGeneratorHoriOffset, XVtc_SetPolarity.
Referenced by XVtc_SetGeneratorVideoMode.
void XVtc_SetGeneratorVideoMode(XVtc *InstancePtr, u16 Mode)
This function sets up the generator (Polarity, H/V values and horizontal offsets) by reading the configuration from a video mode short integer.
InstancePtr is a pointer to the VTC instance to be worked on. Mode is a short integer predefined video mode. None. None.
References XVtc::IsReady, XVtc_ConvVideoMode2Timing, XVtc_SetGeneratorTiming.
void XVtc_GetGeneratorTiming(XVtc *InstancePtr, XVtc_Timing *TimingPtr)
This function gets the video timing structure settings currently used by generator in the VTC core.
InstancePtr is a pointer to the VTC instance to be worked on. TimingPtr is a pointer to a Video Timing Structure to be set. None. None.
References XVtc::IsReady, XVtc_Signal::OriginMode, XVtc_ConvSignal2Timing, XVtc_GetGenerator, XVtc_GetGeneratorHoriOffset, XVtc_GetPolarity.
Referenced by XVtc_GetGeneratorVideoMode.
u16 XVtc_GetGeneratorVideoMode(XVtc *InstancePtr)
This function gets the video mode currently used by the generator in the VTC core.
If the video mode is unknown or not recognized, then 0 will be returned. InstancePtr is a pointer to the VTC instance to be worked on. VideoMode is the video mode of the VTC core. Note.
References XVtc::IsReady, XVtc_ConvTiming2VideoMode, XVtc_GetGeneratorTiming.
void XVtc_GetDetectorTiming(XVtc *InstancePtr, XVtc_Timing *TimingPtr)
This function gets the video timing structure settings currently reported by the detector in the VTC core.
InstancePtr is a pointer to the VTC instance to be worked on. TimingPtr is a pointer to a Video Timing structure to be set. None. None.
References XVtc::IsReady, XVtc_Signal::OriginMode, XVtc_ConvSignal2Timing, XVtc_GetDetector, XVtc_GetDetectorHoriOffset, XVtc_GetDetectorPolarity.
Referenced by XVtc_GetDetectorVideoMode.
u16 XVtc_GetDetectorVideoMode(XVtc *InstancePtr)
This function gets the video mode currently reported by the detector in the VTC core.
If the video mode is unknown or not recognized, then 0 will be returned. InstancePtr is a pointer to the VTC instance to be worked on. VideoMode is the video mode of the VTC core. None.
References XVtc::IsReady, XVtc_ConvTiming2VideoMode, XVtc_GetDetectorTiming.
void XVtc_SetAdaptiveSyncMode(XVtc *InstancePtr, XVtc_AdaptiveSyncMode Mode)
This function sets the vertical front porch stretch mechanism in VTC core to support Adaptive-Sync feature.
VTC core supports two types of stretch mechanisms. 1.Fixed stretch mode 2. Auto adjust mode InstancePtr is a pointer to the VTC instance mode is the type of mode that is being set. None. Modification of this register is fine irrespective of whether VTC has started or not.
References XVtc_Config::BaseAddress, XVtc::Config, XVtc::IsReady, XVTC_ADAPTIVE_CTL_OFFSET, XVTC_ADAPTIVE_ENABLE_MASK, XVTC_ADAPTIVE_MODE_MASK, XVtc_ReadReg, XVtc_WriteReg.
void XVtc_DisableAdaptiveSync(XVtc *InstancePtr)
This function disable Adaptive-Sync in VTC core.
InstancePtr is a pointer to the VTC instance to be worked on. None. None.
References XVtc_Config::BaseAddress, XVtc::Config, XVtc::IsReady, XVTC_ADAPTIVE_CTL_OFFSET, XVTC_ADAPTIVE_ENABLE_MASK, XVtc_ReadReg, XVtc_WriteReg.
void XVtc_SetVfpStretchLimit(XVtc *InstancePtr, u32 StretchLimit)
This function sets vertical front porch stretch limit.
InstancePtr is a pointer to the VTC instance to be worked on. StretchLimit is the vertical front porch stretch limit to be set. None. None.
References XVtc_Config::BaseAddress, XVtc::Config, XVtc::IsReady, XVTC_VFP_STRETCH_OFFSET, XVtc_WriteReg.
XVtc_Config * XVtc_LookupConfig(UINTPTR BaseAddress)
This function returns a reference to an XVtc_Config structure based on the core id, DeviceId.
The return value will refer to an entry in the device configuration table defined in the xvtc_g.c file. DeviceId is the unique core ID of the VTC core for the lookup operation. XVtc_LookupConfig returns a reference to a config record in the configuration table (in xvtc_g.c) corresponding to DeviceId, or NULL if no match is found. None.
Referenced by XVtcSelfTestExample.
void XVtc_IntrHandler(void *InstancePtr)
This function is the interrupt handler for the VTC core.
This handler reads the pending interrupt from the IER/ISR, determines the source of the interrupts, calls according callbacks and finally clears the interrupts.The application is responsible for connecting this function to the interrupt system. Application beyond this driver is also responsible for providing callbacks to handle interrupts and installing the callbacks using XVtc_SetCallBack() during initialization phase. InstancePtr is a pointer to the XVtc instance that just interrupted. None. None.
References XVtc::DetectorCallBack, XVtc::DetectorRef, XVtc::ErrCallBack, XVtc::ErrRef, XVtc::FrameSyncCallBack, XVtc::FrameSyncRef, XVtc::GeneratorCallBack, XVtc::GeneratorRef, XVtc::IsReady, XVtc::LockCallBack, XVtc::LockRef, XVtc_IntrClear, XVtc_IntrGetPending, XVTC_IXR_D_ALL_MASK, XVTC_IXR_FSYNCALL_MASK, XVTC_IXR_G_ALL_MASK, XVTC_IXR_LOCKALL_MASK.
int XVtc_SetCallBack(XVtc *InstancePtr, u32 HandlerType, void *CallBackFunc, void *CallBackRef)
This routine installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function Type ----------------------- -------------------------------------------------- XVTC_HANDLER_FRAMESYNC XVtc_FrameSyncCallBack XVTC_HANDLER_LOCK XVtc_LockCallBack XVTC_HANDLER_DETECTOR XVtc_DetectorCallBack XVTC_HANDLER_GENERATOR XVtc_GeneratorCallBack XVTC_HANDLER_ERROR XVtc_ErrCallBackHandlerType Invoked by this driver when: ----------------------- -------------------------------------------------- XVTC_HANDLER_FRAMESYNC A frame sync event happens XVTC_HANDLER_LOCK A signal lock event happens XVTC_HANDLER_DETECTOR A detector related event happens XVTC_HANDLER_GENERATOR A generator related event happens XVTC_HANDLER_ERROR An error condition happens InstancePtr is a pointer to the XVtc instance to be worked on. HandlerType specifies which callback is to be attached. CallBackFunc is the address of the callback function. CallBackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS when handler is installed.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XVtc::DetectorCallBack, XVtc::DetectorRef, XVtc::ErrCallBack, XVtc::ErrRef, XVtc::FrameSyncCallBack, XVtc::FrameSyncRef, XVtc::GeneratorCallBack, XVtc::GeneratorRef, XVtc::IsReady, XVtc::LockCallBack, XVtc::LockRef, XVTC_HANDLER_DETECTOR, XVTC_HANDLER_ERROR, XVTC_HANDLER_FRAMESYNC, XVTC_HANDLER_GENERATOR, XVTC_HANDLER_LOCK.
int XVtc_SelfTest(XVtc *InstancePtr)
This function reads version register of the VTC core and compares with zero as part of self test.
InstancePtr is a pointer to the XVtc instance. XST_SUCCESS if the Version register read test was successful.XST_FAILURE if the Version register read test failed. None.
References XVtc_ReadReg, XVTC_VER_OFFSET.
Referenced by XVtcSelfTestExample.
XVTC_H_
Prevent circular inclusions by using protection macros.
XVtc_Reset
This function macro resets the VTC core.
InstancePtr is a pointer to the VTC instance to be worked on. None. C-style signature: void XVtc_Reset(XVtc *InstancePtr)
XVtc_SyncReset
This function macro resets the VTC core after the next input frame is complete.
InstancePtr is a pointer to the VTC core instance to be worked on. None. C-style signature: void XVtc_SyncReset(XVtc *InstancePtr)
XVtc_EnableSync
This function macro enables synchronization of the Generator with the Detector on the given VTC core.
InstancePtr is a pointer to the VTC core instance to be worked on. None. C-style signature: void XVtc_EnableSync(XVtc *InstancePtr)
XVtc_RegUpdateEnable
This function macro enables updating timing registers at the end of each Generator frame.
InstancePtr is a pointer to the VTC core instance to be worked on. None. C-style signature: void XVtc_RegUpdateEnable(XVtc *InstancePtr)
XVtc_RegUpdateDisable
This function macro disables updating timing registers at the end of each Generator frame.
InstancePtr is a pointer to the VTC core instance to be worked on. None. C-style signature: void XVtc_RegUpdateDisable(XVtc *InstancePtr)
XVtc_DisableSync
This function macro disables synchronization of the Generator with the Detector on the given VTC core.
InstancePtr is a pointer to the VTC core instance to be worked on. None. C-style signature: void XVtc_DisableSync(XVtc *InstancePtr)
XVtc_GetDetectionStatus
This function macro gets the status of the Detector in the VTC core.
InstancePtr is a pointer to the VTC core instance to be worked on. The Detector status. Use XVTC_DS_* in xvtc_hw.h to interpret the returned value. C-style signature: u32 XVtc_GetDetectionStatus(XVtc *InstancePtr)
XVtc_IntrEnable
This function macro enables individual interrupts of the VTC core by updating the IRQ_ENABLE register.
InstancePtr is a pointer to the VTC core instance to be worked on. IntrType is the bit-mask of the interrupts to be enabled. Bit positions of 1 will be enabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XVTC_IXR_*_MASK bits defined in xvtc_hw.h. None. The existing enabled interrupt(s) will remain enabled. C-style signature: void XVtc_IntrEnable(XVtc *InstancePtr, u32 IntrType)
XVtc_IntrDisable
This function macro disables individual interrupts of the VTC core by updating the IRQ_ENABLE register.
InstancePtr is a pointer to the VTC core instance to be worked on. IntrType is the bit-mask of the interrupts to be disabled. Bit positions of 1 will be disabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XVTC_IXR_*_MASK bits defined in xvtc_hw.h. None. Any other interrupt not covered by parameter IntrType, if enabled before this macro is called, will remain enabled. C-style signature: void XVtc_IntrDisable(XVtc *InstancePtr, u32 IntrType)
XVtc_StatusGetPending
This function macro returns the pending interrupt status of the VTC core read from the Status register.
InstancePtr is a pointer to the VTC core instance to be worked on. The status of pending interrupts of the VTC core. Use XVTC_IXR_*_MASK constants defined in xvtc_hw.h to interpret this value. C-style signature: u32 XVtc_StatusGePending(XVtc *InstancePtr)
XVtc_IntrGetPending
This function macro returns the pending interrupts of the VTC core for the interrupts that have been enabled.
InstancePtr is a pointer to the VTC core instance to be worked on. The pending interrupts of the VTC core. Use XVTC_IXR_*_MASK constants defined in xvtc_hw.h to interpret this value. The returned value is a logical AND of the contents of the STATUS Register and the IRQ_ENABLE Register. C-style signature: u32 XVtc_IntrGetPending(XVtc *InstancePtr)
Referenced by XVtc_IntrHandler.
XVtc_IntrClear
This function macro clears/acknowledges pending interrupts of the VTC core in the Status register.
Bit positions of 1 will be cleared. InstancePtr is a pointer to the VTC core instance to be worked on. IntrType is the pending interrupts to clear/acknowledge. Use OR'ing of XVTC_IXR_*_MASK constants defined in xvtc_hw.h to create this parameter value. None. C-style signature: void XVtc_IntrClear(XVtc *InstancePtr, u32 IntrType)
Referenced by XVtc_IntrHandler.
XVtc_Sync_Reset
This function macro resets the VTC core after the next input frame is complete.
InstancePtr is a pointer to the VTC core instance to be worked on. None. C-style signature: void XVtc_Sync_Reset(XVtc *InstancePtr)
XVTC_HW_H_
prevent circular inclusions by using protection macros
XPAR_XVTC_NUM_INSTANCES