spi
XSP_MASTER_OPTION
The Master option configures the SPI device as a master. By default, the device is a slave.The Active Low Clock option configures the device's clock polarity. Setting this option means the clock is active low and the SCK signal idles high. By default, the clock is active high and SCK idles low.The Clock Phase option configures the SPI device for one of two transfer formats. A clock phase of 0, the default, means data if valid on the first SCK edge (rising or falling) after the slave select (SS) signal has been asserted. A clock phase of 1 means data is valid on the second SCK edge (rising or falling) after SS has been asserted.The Loopback option configures the SPI device for loopback mode. Data is looped back from the transmitter to the receiver.The Manual Slave Select option, which is default, causes the device not to automatically drive the slave select. The driver selects the device at the start of a transfer and deselects it at the end of a transfer. If this option is off, then the device automatically toggles the slave select signal between bytes in a transfer.
Referenced by main, SpiIntrExample, SpiPolledExample, XSpi_SetOptions.
XSP_CLK_ACTIVE_LOW_OPTION
XSP_CLK_PHASE_1_OPTION
XSP_LOOPBACK_OPTION
XSP_MANUAL_SSELECT_OPTION
XSP_DGIER_OFFSET
Global Intr Enable Reg.
XSP_IISR_OFFSET
Interrupt status Reg.
XSP_IIER_OFFSET
Interrupt Enable Reg.
XSP_SRR_OFFSET
Software Reset register.
Referenced by XSpi_Reset.
XSP_CR_OFFSET
Control register.
Referenced by XSpi_Abort, XSpi_CfgInitialize, XSpi_LowLevelExample, XSpi_Start.
XSP_SR_OFFSET
Status Register.
Referenced by XSpi_LowLevelExample.
XSP_DTR_OFFSET
Data transmit.
Referenced by XSpi_CfgInitialize, XSpi_InterruptHandler, XSpi_LowLevelExample, XSpi_Transfer.
XSP_DRR_OFFSET
Data receive.
Referenced by XSpi_CfgInitialize, XSpi_InterruptHandler, XSpi_LowLevelExample, XSpi_Transfer.
XSP_SSR_OFFSET
32-bit slave select
XSP_TFO_OFFSET
Tx FIFO occupancy.
Referenced by XSpi_SelfTest.
XSP_RFO_OFFSET
Rx FIFO occupancy.
Referenced by XSpi_SelfTest.
XSP_GINTR_ENABLE_MASK
Global interrupt enable.
XSP_INTR_MODE_FAULT_MASK
Mode fault error.
Referenced by XSpi_InterruptHandler.
XSP_INTR_SLAVE_MODE_FAULT_MASK
Selected as slave while disabled.
Referenced by XSpi_InterruptHandler.
XSP_INTR_TX_EMPTY_MASK
DTR/TxFIFO is empty.
Referenced by XSpi_InterruptHandler, XSpi_Transfer.
XSP_INTR_TX_UNDERRUN_MASK
DTR/TxFIFO underrun.
Referenced by XSpi_InterruptHandler.
XSP_INTR_RX_FULL_MASK
DRR/RxFIFO is full.
XSP_INTR_RX_OVERRUN_MASK
DRR/RxFIFO overrun.
Referenced by XSpi_InterruptHandler.
XSP_INTR_TX_HALF_EMPTY_MASK
TxFIFO is half empty.
Referenced by XSpi_InterruptHandler.
XSP_INTR_SLAVE_MODE_MASK
Slave select mode.
Referenced by XSpi_InterruptHandler.
XSP_INTR_RX_NOT_EMPTY_MASK
RxFIFO not empty.
Referenced by XSpi_InterruptHandler.
XSP_INTR_CPOL_CPHA_ERR_MASK
The following bits are available only in axi_qspi Interrupt Status and Interrupt Enable registers.
CPOL/CPHA error
XSP_INTR_SLAVE_MODE_ERR_MASK
Slave mode error.
XSP_INTR_MSB_ERR_MASK
MSB Error.
XSP_INTR_LOOP_BACK_ERR_MASK
Loop back error.
XSP_INTR_CMD_ERR_MASK
'Invalid cmd' error
Referenced by XSpi_InterruptHandler.
XSP_INTR_ALL
Mask for all the interrupts in the IP Interrupt Registers.
XSP_INTR_DFT_MASK
The interrupts we want at startup.
We add the TX_EMPTY interrupt in later when we're getting ready to transfer data. The others we don't care about for now.
Referenced by XSpi_Start.
XSP_CR_LOOPBACK_MASK
Local loopback mode.
Referenced by XSpi_LowLevelExample, XSpi_Transfer.
XSP_CR_ENABLE_MASK
System enable.
Referenced by XSpi_CfgInitialize, XSpi_LowLevelExample, XSpi_Start, XSpi_Stop.
XSP_CR_MASTER_MODE_MASK
Enable master mode.
Referenced by XSpi_CfgInitialize, XSpi_LowLevelExample, XSpi_Transfer.
XSP_CR_CLK_POLARITY_MASK
Clock polarity high or low.
XSP_CR_CLK_PHASE_MASK
Clock phase 0 or 1.
XSP_CR_TXFIFO_RESET_MASK
Reset transmit FIFO.
Referenced by XSpi_Abort, XSpi_CfgInitialize, XSpi_Start.
XSP_CR_RXFIFO_RESET_MASK
Reset receive FIFO.
Referenced by XSpi_Abort, XSpi_CfgInitialize, XSpi_Start.
XSP_CR_MANUAL_SS_MASK
Manual slave select assert.
XSP_CR_TRANS_INHIBIT_MASK
Master transaction inhibit.
Referenced by XSpi_Abort, XSpi_CfgInitialize, XSpi_InterruptHandler, XSpi_LowLevelExample, XSpi_Transfer.
XSP_CR_RESET_DONE_MASK
FIFO reset complete.
Referenced by XSpi_Abort, XSpi_CfgInitialize, XSpi_Start.
XSP_CR_LSB_MSB_FIRST_MASK
LSB/MSB first data format select.
The default data format is MSB first. The LSB first data format is not available in all versions of the Xilinx Spi Device whereas the MSB first data format is supported by all the versions of the Xilinx Spi Devices. Please check the HW specification to see if this feature is supported or not.
XSP_CR_XIP_CLK_PHASE_MASK
Clock phase 0 or 1.
XSP_CR_XIP_CLK_POLARITY_MASK
Clock polarity high or low.
XSP_SR_RX_EMPTY_MASK
Receive Reg/FIFO is empty.
Referenced by XSpi_CfgInitialize, XSpi_InterruptHandler, XSpi_LowLevelExample, XSpi_Transfer.
XSP_SR_RX_FULL_MASK
Receive Reg/FIFO is full.
XSP_SR_TX_EMPTY_MASK
Transmit Reg/FIFO is empty.
Referenced by XSpi_LowLevelExample.
XSP_SR_TX_FULL_MASK
Transmit Reg/FIFO is full.
Referenced by XSpi_LowLevelExample, XSpi_Transfer.
XSP_SR_MODE_FAULT_MASK
Mode fault error.
XSP_SR_SLAVE_MODE_MASK
Slave mode select.
XSP_SR_CPOL_CPHA_ERR_MASK
CPOL/CPHA error.
XSP_SR_SLAVE_MODE_ERR_MASK
Slave mode error.
XSP_SR_MSB_ERR_MASK
MSB Error.
XSP_SR_LOOP_BACK_ERR_MASK
Loop back error.
XSP_SR_CMD_ERR_MASK
'Invalid cmd' error
XSP_SR_XIP_RX_EMPTY_MASK
Receive Reg/FIFO is empty.
XSP_SR_XIP_RX_FULL_MASK
Receive Reg/FIFO is full.
XSP_SR_XIP_MASTER_MODF_MASK
Receive Reg/FIFO is full.
XSP_SR_XIP_CPHPL_ERROR_MASK
Clock Phase,Clock Polarity Error.
XSP_SR_XIP_AXI_ERROR_MASK
AXI Transaction Error.
XSP_TFO_MASK
XSP_RFO_MASK
XSP_DATAWIDTH_BYTE
Tx/Rx Reg is Byte Wide.
Referenced by XSpi_CfgInitialize, XSpi_InterruptHandler, XSpi_Transfer.
XSP_DATAWIDTH_HALF_WORD
Tx/Rx Reg is Half Word (16 bit) Wide.
Referenced by XSpi_InterruptHandler, XSpi_Transfer.
XSP_DATAWIDTH_WORD
Tx/Rx Reg is Word (32 bit) Wide.
Referenced by XSpi_InterruptHandler, XSpi_Transfer.
XSP_STANDARD_MODE
XSP_DUAL_MODE
XSP_QUAD_MODE
typedef void(* XSpi_StatusHandler)(void *CallBackRef, u32 StatusEvent, unsigned int ByteCount))(void *CallBackRef, u32 StatusEvent, unsigned int ByteCount)
The handler data type allows the user to define a callback function to handle the asynchronous processing of the SPI driver.
The application using this driver is expected to define a handler of this type to support interrupt driven mode. The handler executes in an interrupt context such that minimal processing should be performed. CallBackRef A callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. Its type is unimportant to the driver component, so it is a void pointer. StatusEvent Indicates one or more status events that occurred. See the XSpi_SetStatusHandler() for details on the status events that can be passed in the callback. ByteCount Indicates how many bytes of data were successfully transferred. This may be less than the number of bytes requested if the status event indicates an error.
XSpi_Config XSpi_ConfigTable[XPAR_XSPI_NUM_INSTANCES][XPAR_XSPI_NUM_INSTANCES]
This table contains configuration information for each SPI device in the system.
XSpi_Config XSpi_ConfigTable[][]
This table contains configuration information for each SPI device in the system.
OptionsMap OptionsTable[][]
XSpi_Config XSpi_ConfigTable[][]
This table contains configuration information for each SPI device in the system.
static void StubStatusHandler(void *CallBackRef, u32 StatusEvent, unsigned int ByteCount)
This is a stub for the status callback.
The stub is here in case the upper layers forget to set the handler. CallBackRef is a pointer to the upper layer callback reference StatusEvent is the event that just occurred. ByteCount is the number of bytes transferred up until the event occurred. None. None.
void XSpi_Abort(XSpi *InstancePtr)
Aborts a transfer in progress by setting the stop bit in the control register, then resetting the FIFOs if present.
The byte counts are cleared and the busy flag is set to false. InstancePtr is a pointer to the XSpi instance to be worked on. None. This function does a read/modify/write of the control register. The user of this function needs to take care of critical sections.
References XSpi::BaseAddr, XSpi::HasFifos, XSpi::IsBusy, XSpi::RemainingBytes, XSpi::RequestedBytes, XSpi::SlaveSelectMask, XSP_CR_OFFSET, XSP_CR_RESET_DONE_MASK, XSP_CR_RXFIFO_RESET_MASK, XSP_CR_TRANS_INHIBIT_MASK, XSP_CR_TXFIFO_RESET_MASK, XSpi_GetControlReg, XSpi_SetControlReg, XSpi_SetSlaveSelectReg.
Referenced by XSpi_InterruptHandler, XSpi_Reset.
int XSpi_CfgInitialize(XSpi *InstancePtr, XSpi_Config *Config, UINTPTR EffectiveAddr)
Initializes a specific XSpi instance such that the driver is ready to use.
The state of the device after initialization is: Device is disabledSlave modeActive high clock polarityClock phase 0 InstancePtr is a pointer to the XSpi instance to be worked on. Config is a reference to a structure containing information about a specific SPI device. This function initializes an InstancePtr object for a specific device specified by the contents of Config. This function can initialize multiple instance objects with the use of multiple calls giving different Config information on each call. EffectiveAddr is the device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, use Config->BaseAddress for this parameters, passing the physical address instead. XST_SUCCESS if successful.XST_DEVICE_IS_STARTED if the device is started. It must be stopped to re-initialize. None.
References XSpi_Config::AxiFullBaseAddress, XSpi::BaseAddr, XSpi_Stats::BytesTransferred, XSpi_Config::DataWidth, XSpi::DataWidth, XSpi_Config::FifosDepth, XSpi::FifosDepth, XSpi::FlashBaseAddr, XSpi_Config::HasFifos, XSpi::HasFifos, XSpi::IsBusy, XSpi::IsReady, XSpi::IsStarted, XSpi_Stats::ModeFaults, XSpi_Stats::NumInterrupts, XSpi_Config::NumSlaveBits, XSpi::NumSlaveBits, XSpi::RecvBufferPtr, XSpi_Stats::RecvOverruns, XSpi::RemainingBytes, XSpi::RequestedBytes, XSpi::SendBufferPtr, XSpi_Stats::SlaveModeFaults, XSpi_Config::SlaveOnly, XSpi::SlaveOnly, XSpi::SlaveSelectMask, XSpi::SlaveSelectReg, XSpi_Config::SpiMode, XSpi::SpiMode, XSpi::Stats, XSpi::StatusHandler, XSpi_Config::Use_Startup, XSpi_Config::XipMode, XSpi::XipMode, XSpi_Stats::XmitUnderruns, XSP_CR_ENABLE_MASK, XSP_CR_MASTER_MODE_MASK, XSP_CR_OFFSET, XSP_CR_RESET_DONE_MASK, XSP_CR_RXFIFO_RESET_MASK, XSP_CR_TRANS_INHIBIT_MASK, XSP_CR_TXFIFO_RESET_MASK, XSP_DATAWIDTH_BYTE, XSP_DRR_OFFSET, XSP_DTR_OFFSET, XSP_SR_RX_EMPTY_MASK, XSpi_GetControlReg, XSpi_GetStatusReg, XSpi_ReadReg, XSpi_Reset, XSpi_SetControlReg, XSpi_WriteReg.
Referenced by main, SpiIntrExample, SpiPolledExample, SpiSelfTestExample, SpiXipExample, XSpi_Initialize.
int XSpi_Start(XSpi *InstancePtr)
This function enables interrupts for the SPI device.
If the Spi driver is used in interrupt mode, it is up to the user to connect the SPI interrupt handler to the interrupt controller before this function is called. If the Spi driver is used in polled mode the user has to disable the Global Interrupts after this function is called. If the device is configured with FIFOs, the FIFOs are reset at this time. InstancePtr is a pointer to the XSpi instance to be worked on. XST_SUCCESS if the device is successfully startedXST_DEVICE_IS_STARTED if the device was already started. None.
References XSpi::BaseAddr, XSpi::IsReady, XSpi::IsStarted, XSP_CR_ENABLE_MASK, XSP_CR_OFFSET, XSP_CR_RESET_DONE_MASK, XSP_CR_RXFIFO_RESET_MASK, XSP_CR_TXFIFO_RESET_MASK, XSP_INTR_DFT_MASK, XSpi_GetControlReg, XSpi_IntrEnable, XSpi_IntrGlobalEnable, XSpi_SetControlReg.
Referenced by main, SpiIntrExample, SpiPolledExample.
int XSpi_Stop(XSpi *InstancePtr)
This function stops the SPI device by disabling interrupts and disabling the device itself.
Interrupts are disabled only within the device itself. If desired, the caller is responsible for disabling interrupts in the interrupt controller and disconnecting the interrupt handler from the interrupt controller.In interrupt mode, if the device is in progress of transferring data on the SPI bus, this function returns a status indicating the device is busy. The user will be notified via the status handler when the transfer is complete, and at that time can again try to stop the device. As a master, we do not allow the device to be stopped while a transfer is in progress because the slave may be left in a bad state. As a slave, we do not allow the device to be stopped while a transfer is in progress because the master is not done with its transfer yet. InstancePtr is a pointer to the XSpi instance to be worked on. XST_SUCCESS if the device is successfully started. XST_DEVICE_BUSY if a transfer is in progress and cannot be stopped. This function makes use of internal resources that are shared between the XSpi_Stop() and XSpi_SetOptions() functions. So if one task might be setting device options while another is trying to stop the device, the user is is required to provide protection of this shared data (typically using a semaphore).
References XSpi::IsBusy, XSpi::IsReady, XSpi::IsStarted, XSP_CR_ENABLE_MASK, XSpi_GetControlReg, XSpi_IntrGlobalDisable, XSpi_SetControlReg.
void XSpi_Reset(XSpi *InstancePtr)
Resets the SPI device by writing to the Software Reset register.
Reset must only be called after the driver has been initialized. The configuration of the device after reset is the same as its configuration after initialization. Refer to the XSpi_Initialize function for more details. This is a hard reset of the device. Any data transfer that is in progress is aborted.The upper layer software is responsible for re-configuring (if necessary) and restarting the SPI device after the reset. InstancePtr is a pointer to the XSpi instance to be worked on. None. None.
References XSpi::BaseAddr, XSpi::IsReady, XSpi::IsStarted, XSpi::SlaveSelectMask, XSpi::SlaveSelectReg, XSP_SRR_OFFSET, XSP_SRR_RESET_MASK, XSpi_Abort, XSpi_WriteReg.
Referenced by XSpi_CfgInitialize, XSpi_SelfTest.
int XSpi_Transfer(XSpi *InstancePtr, u8 *SendBufPtr, u8 *RecvBufPtr, unsigned int ByteCount)
Transfers the specified data on the SPI bus.
If the SPI device is configured to be a master, this function initiates bus communication and sends/receives the data to/from the selected SPI slave. If the SPI device is configured to be a slave, this function prepares the data to be sent/received when selected by a master. For every byte sent, a byte is received.This function/driver operates in interrupt mode and polled mode. In interrupt mode this function is non-blocking and the transfer is initiated by this function and completed by the interrupt service routine.In polled mode this function is blocking and the control exits this function only after all the requested data is transferred. The caller has the option of providing two different buffers for send and receive, or one buffer for both send and receive, or no buffer for receive. The receive buffer must be at least as big as the send buffer to prevent unwanted memory writes. This implies that the byte count passed in as an argument must be the smaller of the two buffers if they differ in size. Here are some sample usages: XSpi_Transfer(InstancePtr, SendBuf, RecvBuf, ByteCount) The caller wishes to send and receive, and provides two different buffers for send and receive. XSpi_Transfer(InstancePtr, SendBuf, NULL, ByteCount) The caller wishes only to send and does not care about the received data. The driver ignores the received data in this case. XSpi_Transfer(InstancePtr, SendBuf, SendBuf, ByteCount) The caller wishes to send and receive, but provides the same buffer for doing both. The driver sends the data and overwrites the send buffer with received data as it transfers the data. XSpi_Transfer(InstancePtr, RecvBuf, RecvBuf, ByteCount) The caller wishes to only receive and does not care about sending data. In this case, the caller must still provide a send buffer, but it can be the same as the receive buffer if the caller does not care what it sends. The device must send N bytes of data if it wishes to receive N bytes of data. In interrupt mode, though this function takes a buffer as an argument, the driver can only transfer a limited number of bytes at time. It transfers only one byte at a time if there are no FIFOs, or it can transfer the number of bytes up to the size of the FIFO if FIFOs exist. In interrupt mode a call to this function only starts the transfer, the subsequent transfer of the data is performed by the interrupt service routine until the entire buffer has been transferred.The status callback function is called when the entire buffer has been sent/received.In polled mode this function is blocking and the control exits this function only after all the requested data is transferred. As a master, the SetSlaveSelect function must be called prior to this function. InstancePtr is a pointer to the XSpi instance to be worked on. SendBufPtr is a pointer to a buffer of data which is to be sent. This buffer must not be NULL. RecvBufPtr is a pointer to a buffer which will be filled with received data. This argument can be NULL if the caller does not wish to receive data. ByteCount contains the number of bytes to send/receive. The number of bytes received always equals the number of bytes sent. -XST_SUCCESS if the buffers are successfully handed off to the driver for transfer. Otherwise, returns: XST_DEVICE_IS_STOPPED if the device must be started before transferring data.XST_DEVICE_BUSY indicates that a data transfer is already in progress. This is determined by the driver.XST_SPI_NO_SLAVE indicates the device is configured as a master and a slave has not yet been selected. This function is not thread-safe. The higher layer software must ensure that no two threads are transferring data on the SPI bus at the same time.
References XSpi::BaseAddr, XSpi_Stats::BytesTransferred, XSpi::DataWidth, XSpi::FifosDepth, XSpi::IsBusy, XSpi::IsReady, XSpi::IsStarted, XSpi::RecvBufferPtr, XSpi::RemainingBytes, XSpi::RequestedBytes, XSpi::SendBufferPtr, XSpi::SlaveSelectMask, XSpi::SlaveSelectReg, XSpi::Stats, XSP_CR_LOOPBACK_MASK, XSP_CR_MASTER_MODE_MASK, XSP_CR_TRANS_INHIBIT_MASK, XSP_DATAWIDTH_BYTE, XSP_DATAWIDTH_HALF_WORD, XSP_DATAWIDTH_WORD, XSP_DRR_OFFSET, XSP_DTR_OFFSET, XSP_INTR_TX_EMPTY_MASK, XSP_SR_RX_EMPTY_MASK, XSP_SR_TX_FULL_MASK, XSpi_GetControlReg, XSpi_GetStatusReg, XSpi_IntrClear, XSpi_IntrEnable, XSpi_IntrGetStatus, XSpi_IntrGlobalDisable, XSpi_IntrGlobalEnable, XSpi_IsIntrGlobalEnabled, XSpi_ReadReg, XSpi_SetControlReg, XSpi_SetSlaveSelectReg, XSpi_WriteReg.
Referenced by EepromRead, EepromWrite, SpiAtmelFlashPageErase, SpiAtmelFlashRead, SpiAtmelFlashWrite, SpiFlashBulkErase, SpiFlashEnableHPM, SpiFlashGetStatus, SpiFlashQuadEnable, SpiFlashRead, SpiFlashSectorErase, SpiFlashWrite, SpiFlashWriteEnable, SpiIntelFlashBulkErase, SpiIntelFlashGetStatus, SpiIntelFlashRead, SpiIntelFlashSectorErase, SpiIntelFlashWrite, SpiIntelFlashWriteEnable, SpiIntelFlashWriteStatus, SpiIntrExample, SpiPolledExample, SpiStmFlashBulkErase, SpiStmFlashGetStatus, SpiStmFlashRead, SpiStmFlashSectorErase, SpiStmFlashWrite, SpiStmFlashWriteEnable.
int XSpi_SetSlaveSelect(XSpi *InstancePtr, u32 SlaveMask)
Selects or deselect the slave with which the master communicates.
Each slave that can be selected is represented in the slave select register by a bit. The argument passed to this function is the bit mask with a 1 in the bit position of the slave being selected. Only one slave can be selected.The user is not allowed to deselect the slave while a transfer is in progress. If no transfer is in progress, the user can select a new slave, which implicitly deselects the current slave. In order to explicitly deselect the current slave, a zero can be passed in as the argument to the function. InstancePtr is a pointer to the XSpi instance to be worked on. SlaveMask is a 32-bit mask with a 1 in the bit position of the slave being selected. Only one slave can be selected. The SlaveMask can be zero if the slave is being deselected. XST_SUCCESS if the slave is selected or deselected successfully. XST_DEVICE_BUSY if a transfer is in progress, slave cannot be changedXST_SPI_TOO_MANY_SLAVES if more than one slave is being selected. This function only sets the slave which will be selected when a transfer occurs. The slave is not selected when the SPI is idle. The slave select has no affect when the device is configured as a slave.
References XSpi::IsBusy, XSpi::IsReady, XSpi::NumSlaveBits, XSpi::SlaveSelectReg.
Referenced by main.
u32 XSpi_GetSlaveSelect(XSpi *InstancePtr)
Gets the current slave select bit mask for the SPI device.
InstancePtr is a pointer to the XSpi instance to be worked on. The value returned is a 32-bit mask with a 1 in the bit position of the slave currently selected. The value may be zero if no slaves are selected. This API is used to get the current slave select bit mask that was set using the XSpi_SetSlaveSelect API. This API deos not read the register from the core and returns the slave select register stored in the instance pointer.
References XSpi::IsReady, XSpi::SlaveSelectReg.
void XSpi_SetStatusHandler(XSpi *InstancePtr, void *CallBackRef, XSpi_StatusHandler FuncPtr)
Sets the status callback function, the status handler, which the driver calls when it encounters conditions that should be reported to the higher layer software.
The handler executes in an interrupt context, so it must minimize the amount of processing performed such as transferring data to a thread context. One of the following status events is passed to the status handler. XST_SPI_MODE_FAULT A mode fault error occurred, meaning another master tried to select this device as a slave when this device was configured to be a master. Any transfer in progress is aborted. XST_SPI_TRANSFER_DONE The requested data transfer is done XST_SPI_TRANSMIT_UNDERRUN As a slave device, the master clocked data but there were none available in the transmit register/FIFO. This typically means the slave application did not issue a transfer request fast enough, or the processor/driver could not fill the transmit register/FIFO fast enough. XST_SPI_RECEIVE_OVERRUN The SPI device lost data. Data was received but the receive data register/FIFO was full. This indicates that the device is receiving data faster than the processor/driver can consume it. XST_SPI_SLAVE_MODE_FAULT A slave SPI device was selected as a slave while it was disabled. This indicates the master is already transferring data (which is being dropped until the slave application issues a transfer). InstancePtr is a pointer to the XSpi instance to be worked on. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. FuncPtr is the pointer to the callback function. None. The handler is called within interrupt context, so it should do its work quickly and queue potentially time-consuming work to a task-level thread.
References XSpi::IsReady, XSpi::StatusHandler, XSpi::StatusRef.
Referenced by main, SpiIntrExample.
void XSpi_InterruptHandler(void *InstancePtr)
The interrupt handler for SPI interrupts.
This function must be connected by the user to an interrupt source. This function does not save and restore the processor context such that the user must provide this processing.The interrupts that are handled are: Mode Fault Error. This interrupt is generated if this device is selected as a slave when it is configured as a master. The driver aborts any data transfer that is in progress by resetting FIFOs (if present) and resetting its buffer pointers. The upper layer software is informed of the error.Data Transmit Register (FIFO) Empty. This interrupt is generated when the transmit register or FIFO is empty. The driver uses this interrupt during a transmission to continually send/receive data until there is no more data to send/receive.Data Transmit Register (FIFO) Underrun. This interrupt is generated when the SPI device, when configured as a slave, attempts to read an empty DTR/FIFO. An empty DTR/FIFO usually means that software is not giving the device data in a timely manner. No action is taken by the driver other than to inform the upper layer software of the error.Data Receive Register (FIFO) Overrun. This interrupt is generated when the SPI device attempts to write a received byte to an already full DRR/FIFO. A full DRR/FIFO usually means software is not emptying the data in a timely manner. No action is taken by the driver other than to inform the upper layer software of the error.Slave Mode Fault Error. This interrupt is generated if a slave device is selected as a slave while it is disabled. No action is taken by the driver other than to inform the upper layer software of the error.Command Error. This interrupt occurs when the first byte in the Tx FIFO, after the CS is asserted, doesn't match any command in the Lookup table. This interrupt is valid only for axi_qspi. InstancePtr is a pointer to the XSpi instance to be worked on. None. The slave select register is being set to deselect the slave when a transfer is complete. This is being done regardless of whether it is a slave or a master since the hardware does not drive the slave select as a slave.
References XSpi::BaseAddr, XSpi_Stats::BytesTransferred, XSpi::DataWidth, XSpi::FifosDepth, XSpi::IsBusy, XSpi_Stats::ModeFaults, XSpi_Stats::NumInterrupts, XSpi::RecvBufferPtr, XSpi_Stats::RecvOverruns, XSpi::RemainingBytes, XSpi::RequestedBytes, XSpi::SendBufferPtr, XSpi_Stats::SlaveModeFaults, XSpi::SlaveSelectMask, XSpi::Stats, XSpi::StatusHandler, XSpi::StatusRef, XSpi_Stats::XmitUnderruns, XSP_CR_TRANS_INHIBIT_MASK, XSP_DATAWIDTH_BYTE, XSP_DATAWIDTH_HALF_WORD, XSP_DATAWIDTH_WORD, XSP_DRR_OFFSET, XSP_DTR_OFFSET, XSP_INTR_CMD_ERR_MASK, XSP_INTR_MODE_FAULT_MASK, XSP_INTR_RX_NOT_EMPTY_MASK, XSP_INTR_RX_OVERRUN_MASK, XSP_INTR_SLAVE_MODE_FAULT_MASK, XSP_INTR_SLAVE_MODE_MASK, XSP_INTR_TX_EMPTY_MASK, XSP_INTR_TX_HALF_EMPTY_MASK, XSP_INTR_TX_UNDERRUN_MASK, XSP_SR_RX_EMPTY_MASK, XSpi_Abort, XSpi_GetControlReg, XSpi_GetStatusReg, XSpi_IntrClear, XSpi_IntrDisable, XSpi_IntrGetStatus, XSpi_ReadReg, XSpi_SetControlReg, XSpi_SetSlaveSelectReg, XSpi_WriteReg.
Referenced by main, SpiIntrExample.
int XSpi_Initialize(XSpi *InstancePtr, UINTPTR BaseAddress)
Initializes a specific XSpi instance such that the driver is ready to use.
The state of the device after initialization is: Device is disabledSlave modeActive high clock polarityClock phase 0 InstancePtr is a pointer to the XSpi instance to be worked on. BaseAddress contains the base address of the device - XST_SUCCESS if successful. - XST_DEVICE_IS_STARTED if the device is started. It must be stopped to re-initialize. - XST_DEVICE_NOT_FOUND if the device was not found in the configuration such that initialization could not be accomplished. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XSpi_Config::BaseAddress, XSpi_CfgInitialize, XSpi_LookupConfig.
XSpi_Config * XSpi_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XSpi_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xspi.h for the definition of XSpi_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XSpi_Config::Name.
Referenced by main, SpiIntrExample, SpiPolledExample, SpiSelfTestExample, SpiXipExample, XSpi_Initialize.
int XSpi_SelfTest(XSpi *InstancePtr)
Runs a self-test on the driver/device.
The self-test is destructive in that a reset of the device is performed in order to check the reset values of the registers and to get the device into a known state. A simple loopback test is also performed to verify that transmit and receive are working properly. The device is changed to master mode for the loopback test, since only a master can initiate a data transfer.Upon successful return from the self-test, the device is reset. InstancePtr is a pointer to the XSpi instance to be worked on. XST_SUCCESS if successful. XST_REGISTER_ERROR indicates a register did not read or write correctly. XST_LOOPBACK_ERROR if a loopback error occurred. None.
References XSpi::BaseAddr, XSpi::HasFifos, XSpi::IsReady, XSpi::SlaveSelectMask, XSpi::SpiMode, XSpi::XipMode, XSP_RFO_OFFSET, XSP_TFO_OFFSET, XSpi_GetControlReg, XSpi_GetSlaveSelectReg, XSpi_GetStatusReg, XSpi_ReadReg, XSpi_Reset.
Referenced by SpiIntrExample, SpiPolledExample, SpiSelfTestExample.
void XSpi_GetStats(XSpi *InstancePtr, XSpi_Stats *StatsPtr)
Gets a copy of the statistics for an SPI device.
InstancePtr is a pointer to the XSpi instance to be worked on. StatsPtr is a pointer to a XSpi_Stats structure which will get a copy of current statistics. None. Statistics are not updated in polled mode of operation.
References XSpi_Stats::BytesTransferred, XSpi::IsReady, XSpi_Stats::ModeFaults, XSpi_Stats::NumInterrupts, XSpi_Stats::RecvOverruns, XSpi_Stats::SlaveModeFaults, XSpi::Stats, XSpi_Stats::XmitUnderruns.
void XSpi_ClearStats(XSpi *InstancePtr)
Clears the statistics for the SPI device.
InstancePtr is a pointer to the XSpi instance to be worked on. None. Statistics are not updated in polled mode of operation.
References XSpi_Stats::BytesTransferred, XSpi::IsReady, XSpi_Stats::ModeFaults, XSpi_Stats::NumInterrupts, XSpi_Stats::RecvOverruns, XSpi_Stats::SlaveModeFaults, XSpi::Stats, XSpi_Stats::XmitUnderruns.
int XSpi_SetOptions(XSpi *InstancePtr, u32 Options)
This function sets the options for the SPI device driver.
The options control how the device behaves relative to the SPI bus. The device must be idle rather than busy transferring data before setting these device options. InstancePtr is a pointer to the XSpi instance to be worked on. Options contains the specified options to be set. This is a bit mask where a 1 means to turn the option on, and a 0 means to turn the option off. One or more bit values may be contained in the mask. See the bit definitions named XSP_*_OPTIONS in the file xspi.h. -XST_SUCCESS if options are successfully set. XST_DEVICE_BUSY if the device is currently transferring data. The transfer must complete or be aborted before setting options.XST_SPI_SLAVE_ONLY if the caller attempted to configure a slave-only device as a master. This function makes use of internal resources that are shared between the XSpi_Stop() and XSpi_SetOptions() functions. So if one task might be setting device options while another is trying to stop the device, the user is required to provide protection of this shared data (typically using a semaphore).
References XSpi::IsBusy, XSpi::IsReady, XSpi::SlaveOnly, XSP_MASTER_OPTION, XSpi_GetControlReg, XSpi_SetControlReg.
Referenced by main, SpiIntrExample, SpiPolledExample.
u32 XSpi_GetOptions(XSpi *InstancePtr)
This function gets the options for the SPI device.
The options control how the device behaves relative to the SPI bus. InstancePtr is a pointer to the XSpi instance to be worked on. Options contains the specified options to be set. This is a bit mask where a 1 means to turn the option on, and a 0 means to turn the option off. One or more bit values may be contained in the mask. See the bit definitions named XSP_*_OPTIONS in the file xspi.h.None.
References XSpi::IsReady, XSpi_GetControlReg.
static int LoopbackTest(XSpi *InstancePtr)
XSPI_H
XSpi_IntrGlobalEnable
This macro writes to the global interrupt enable register to enable interrupts from the device.
Interrupts enabled using XSpi_IntrEnable() will not occur until the global interrupt enable bit is set by using this function. InstancePtr is a pointer to the XSpi instance to be worked on. None. C-Style signature: void XSpi_IntrGlobalEnable(XSpi *InstancePtr);
Referenced by XSpi_Start, XSpi_Transfer.
XSpi_IntrGlobalDisable
This macro disables all interrupts for the device by writing to the Global interrupt enable register.
InstancePtr is a pointer to the XSpi instance to be worked on. None. C-Style signature: void XSpi_IntrGlobalDisable(XSpi *InstancePtr);
Referenced by SpiPolledExample, XSpi_Stop, XSpi_Transfer.
XSpi_IsIntrGlobalEnabled
This function determines if interrupts are enabled at the global level by reading the global interrupt register.
InstancePtr is a pointer to the XSpi instance to be worked on. TRUE if global interrupts are enabled.FALSE if global interrupts are disabled. C-Style signature: int XSpi_IsIntrGlobalEnabled(XSpi *InstancePtr);
Referenced by XSpi_Transfer.
XSpi_IntrGetStatus
This function gets the contents of the Interrupt Status Register.
This register indicates the status of interrupt sources for the device. The status is independent of whether interrupts are enabled such that the status register may also be polled when interrupts are not enabled. InstancePtr is a pointer to the XSpi instance to be worked on. A status which contains the value read from the Interrupt Status Register. C-Style signature: u32 XSpi_IntrGetStatus(XSpi *InstancePtr);
Referenced by XSpi_InterruptHandler, XSpi_Transfer.
XSpi_IntrClear
This function clears the specified interrupts in the Interrupt status Register.
The interrupt is cleared by writing to this register with the bits to be cleared set to a one and all others bits to zero. Setting a bit which is zero within this register causes an interrupt to be generated.This function writes only the specified value to the register such that some status bits may be set and others cleared. It is the caller's responsibility to get the value of the register prior to setting the value to prevent an destructive behavior. InstancePtr is a pointer to the XSpi instance to be worked on. ClearMask is the Bitmask for interrupts to be cleared. Bit positions of "1" clears the interrupt. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XSP_INTR_* bits defined in xspi_l.h. None. C-Style signature: void XSpi_IntrClear(XSpi *InstancePtr, u32 ClearMask);
Referenced by XSpi_InterruptHandler, XSpi_Transfer.
XSpi_IntrEnable
This function sets the contents of the Interrupt Enable Register.
InstancePtr is a pointer to the XSpi instance to be worked on. EnableMask is the bitmask of the interrupts to be enabled. Bit positions of 1 will be enabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XSP_INTR_* bits defined in xspi_l.h. None. C-Style signature: void XSpi_IntrEnable(XSpi *InstancePtr, u32 EnableMask);
Referenced by XSpi_Start, XSpi_Transfer.
XSpi_IntrDisable
Disable the specified Interrupts in the Interrupt Enable Register.
InstancePtr is a pointer to the XSpi instance to be worked on. DisableMask is the bitmask of the interrupts to be disabled. Bit positions of 1 will be disabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XSP_INTR_* bits defined in xspi_l.h. None. C-Style signature: void XSpi_IntrDisable(XSpi *InstancePtr, u32 DisableMask);
Referenced by XSpi_InterruptHandler.
XSpi_IntrGetEnabled
This function gets the contents of the Interrupt Enable Register.
InstancePtr is a pointer to the XSpi instance to be worked on. The contents read from the Interrupt Enable Register. C-Style signature: u32 XSpi_IntrGetEnabled(XSpi *InstancePtr)
XSpi_SetControlReg
Set the contents of the control register.
Use the XSP_CR_* constants defined above to create the bit-mask to be written to the register. InstancePtr is a pointer to the XSpi instance to be worked on. Mask is the 32-bit value to write to the control register. None. C-Style signature: void XSpi_SetControlReg(XSpi *InstancePtr, u32 Mask);
Referenced by XSpi_Abort, XSpi_CfgInitialize, XSpi_InterruptHandler, XSpi_SetOptions, XSpi_Start, XSpi_Stop, XSpi_Transfer.
XSpi_GetControlReg
Get the contents of the control register.
Use the XSP_CR_* constants defined above to interpret the bit-mask returned. InstancePtr is a pointer to the XSpi instance to be worked on. A 32-bit value representing the contents of the control register. C-Style signature: u32 XSpi_GetControlReg(XSpi *InstancePtr);
Referenced by XSpi_Abort, XSpi_CfgInitialize, XSpi_GetOptions, XSpi_InterruptHandler, XSpi_SelfTest, XSpi_SetOptions, XSpi_Start, XSpi_Stop, XSpi_Transfer.
XSpi_GetStatusReg
Get the contents of the status register.
Use the XSP_SR_* constants defined above to interpret the bit-mask returned. InstancePtr is a pointer to the XSpi instance to be worked on. An 32-bit value representing the contents of the status register. C-Style signature: u8 XSpi_GetStatusReg(XSpi *InstancePtr);
Referenced by XSpi_CfgInitialize, XSpi_InterruptHandler, XSpi_SelfTest, XSpi_Transfer.
XSpi_SetXipControlReg
Set the contents of the XIP control register.
Use the XSP_CR_XIP_* constants defined above to create the bit-mask to be written to the register. InstancePtr is a pointer to the XSpi instance to be worked on. Mask is the 32-bit value to write to the control register. None. C-Style signature: void XSpi_SetXipControlReg(XSpi *InstancePtr, u32 Mask);
XSpi_GetXipControlReg
Get the contents of the XIP control register.
Use the XSP_CR_XIP_* constants defined above to interpret the bit-mask returned. InstancePtr is a pointer to the XSpi instance to be worked on. A 32-bit value representing the contents of the control register. C-Style signature: u32 XSpi_GetXipControlReg(XSpi *InstancePtr);
XSpi_GetXipStatusReg
Get the contents of the status register.
Use the XSP_SR_XIP_* constants defined above to interpret the bit-mask returned. InstancePtr is a pointer to the XSpi instance to be worked on. An 32-bit value representing the contents of the status register. C-Style signature: u8 XSpi_GetXipStatusReg(XSpi *InstancePtr);
XSpi_SetSlaveSelectReg
Set the contents of the slave select register.
Each bit in the mask corresponds to a slave select line. Only one slave should be selected at any one time. InstancePtr is a pointer to the XSpi instance to be worked on. Mask is the 32-bit value to write to the slave select register. None. C-Style signature: void XSpi_SetSlaveSelectReg(XSpi *InstancePtr, u32 Mask);
Referenced by XSpi_Abort, XSpi_InterruptHandler, XSpi_Transfer.
XSpi_GetSlaveSelectReg
Get the contents of the slave select register.
Each bit in the mask corresponds to a slave select line. Only one slave should be selected at any one time. InstancePtr is a pointer to the XSpi instance to be worked on. The 32-bit value in the slave select register. C-Style signature: u32 XSpi_GetSlaveSelectReg(XSpi *InstancePtr);
Referenced by XSpi_SelfTest.
XSpi_Enable
Enable the device and uninhibit master transactions.
Preserves the current contents of the control register. InstancePtr is a pointer to the XSpi instance to be worked on. None. C-Style signature: void XSpi_Enable(XSpi *InstancePtr);
XSpi_Disable
Disable the device.
Preserves the current contents of the control register. InstancePtr is a pointer to the XSpi instance to be worked on. None. C-Style signature: void XSpi_Disable(XSpi *InstancePtr);
XSPI_I_H
XSPI_L_H
XSpi_In32
XSpi_Out32
XSpi_ReadReg
Read from the specified Spi device register.
BaseAddress contains the base address of the device. RegOffset contains the offset from the 1st register of the device to select the specific register. The value read from the register. C-Style signature: u32 XSpi_ReadReg(u32 BaseAddress, u32 RegOffset);
Referenced by XSpi_CfgInitialize, XSpi_InterruptHandler, XSpi_LowLevelExample, XSpi_SelfTest, XSpi_Transfer.
XSpi_WriteReg
Write to the specified Spi device register.
BaseAddress contains the base address of the device. RegOffset contains the offset from the 1st register of the device to select the specific register. RegisterValue is the value to be written to the register. None. C-Style signature: void XSpi_WriteReg(u32 BaseAddress, u32 RegOffset, u32 RegisterValue);
Referenced by XSpi_CfgInitialize, XSpi_InterruptHandler, XSpi_LowLevelExample, XSpi_Reset, XSpi_Transfer.
XSP_SRR_RESET_MASK
SPI Software Reset Register (SRR) mask.
Referenced by XSpi_Reset.
XSP_NUM_OPTIONS
XSP_SR_RESET_STATE
XSP_CR_RESET_STATE
XSP_HALF_WORD_TESTBYTE
XSP_WORD_TESTBYTE