xspi_intel_flash_example.c
INTEL_SPI_SELECT
INTEL_COMMAND_RANDOM_READ
INTEL_COMMAND_PAGEPROGRAM_WRITE
INTEL_COMMAND_WRITE_ENABLE
INTEL_COMMAND_SECTOR_ERASE
INTEL_COMMAND_BULK_ERASE
INTEL_COMMAND_STATUSREG_READ
INTEL_COMMAND_STATUSREG_WRITE
INTEL_READ_WRITE_EXTRA_BYTES
INTEL_WRITE_ENABLE_BYTES
INTEL_SECTOR_ERASE_BYTES
INTEL_BULK_ERASE_BYTES
INTEL_STATUS_READ_BYTES
INTEL_STATUS_WRITE_BYTES
INTEL_FLASH_SR_IS_READY_MASK
INTEL_DISABLE_PROTECTION_ALL
INTEL_FLASH_PAGE_SIZE
INTEL_FLASH_TEST_ADDRESS
INTEL_FLASH_TEST_BYTE
BYTE1
BYTE2
BYTE3
BYTE4
BYTE5
INTEL_DUMMYBYTE
XSpi Spi
volatile int TransferInProgress
int ErrorCount
u8 ReadBuffer[INTEL_FLASH_PAGE_SIZE+INTEL_READ_WRITE_EXTRA_BYTES][INTEL_FLASH_PAGE_SIZE+INTEL_READ_WRITE_EXTRA_BYTES]
u8 WriteBuffer[INTEL_FLASH_PAGE_SIZE+INTEL_READ_WRITE_EXTRA_BYTES][INTEL_FLASH_PAGE_SIZE+INTEL_READ_WRITE_EXTRA_BYTES]
int SpiIntelFlashWriteEnable(XSpi *SpiPtr)
This function enables writes to the Intel Serial Flash memory.
SpiPtr is a pointer to the instance of the Spi device. XST_SUCCESS if successful else XST_FAILURE. None.
References XSpi_Transfer.
Referenced by main.
int SpiIntelFlashWrite(XSpi *SpiPtr, u32 Addr, u32 ByteCount)
This function writes the data to the specified locations in the Intel Serial Flash memory.
SpiPtr is a pointer to the instance of the Spi device. Addr is the address in the Buffer, where to write the data. ByteCount is the number of bytes to be written. XST_SUCCESS if successful else XST_FAILURE. A minimum of one byte and a maximum of one Page can be written using this API.
References XSpi_Transfer.
Referenced by main.
int SpiIntelFlashRead(XSpi *SpiPtr, u32 Addr, u32 ByteCount)
This function reads the data from the Intel Serial Flash Memory.
SpiPtr is a pointer to the instance of the Spi device. Addr is the starting address in the Flash Memory from which the data is to be read. ByteCount is the number of bytes to be read. XST_SUCCESS if successful else XST_FAILURE. None.
References XSpi_Transfer.
Referenced by main.
int SpiIntelFlashBulkErase(XSpi *SpiPtr)
This function erases the entire contents of the Intel Serial Flash.
SpiPtr is a pointer to the instance of the Spi device. XST_SUCCESS if successful else XST_FAILURE. The erased bytes will read as 0xFF.
References XSpi_Transfer.
int SpiIntelFlashSectorErase(XSpi *SpiPtr, u32 Addr)
This function erases the contents of the specified Sector in the Intel Serial Flash.
SpiPtr is a pointer to the instance of the Spi device. Addr is the address within a sector of the Buffer, which is to be erased. XST_SUCCESS if successful else XST_FAILURE. The erased bytes will read as 0xFF.
References XSpi_Transfer.
Referenced by main.
int SpiIntelFlashGetStatus(XSpi *SpiPtr)
This function reads the Status register of the Intel Serial Flash.
SpiPtr is a pointer to the instance of the Spi device. XST_SUCCESS if successful else XST_FAILURE. The status register content is stored at the second byte pointed by the ReadBuffer.
References XSpi_Transfer.
int SpiIntelFlashWriteStatus(XSpi *SpiPtr, u8 StatusRegister)
This function writes to the Status register of the Intel Flash.
SpiPtr is a pointer to the instance of the Spi device. StatusRegister is the value to be written to the status register of the flash device. XST_SUCCESS if successful else XST_FAILURE. The status register content is stored at the second byte pointed by the ReadPtr.
References XSpi_Transfer.
Referenced by main.
int SpiIntelFlashWaitForFlashNotBusy(void)
This function waits till the Intel Serial Flash is ready to accept next command.
None XST_SUCCESS if successful else XST_FAILURE. This function reads the status register of the Buffer and waits . till the WIP bit of the status register becomes 0.
void SpiHandler(void *CallBackRef, u32 StatusEvent, unsigned int ByteCount)
This function is the handler which performs processing for the SPI driver.
It is called from an interrupt context such that the amount of processing performed should be minimized. It is called when a transfer of SPI data completes or an error occurs.This handler provides an example of how to handle SPI interrupts and is application specific. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. StatusEvent is the event that just occurred. ByteCount is the number of bytes transferred up until the event occurred. None. None.
int main(void)
Main function to execute the Flash example.
XST_SUCCESS if successful else XST_FAILURE. None
References XSpi_Config::BaseAddress, XSpi_Config::IntrId, XSpi_Config::IntrParent, SpiHandler, SpiIntelFlashRead, SpiIntelFlashSectorErase, SpiIntelFlashWrite, SpiIntelFlashWriteEnable, SpiIntelFlashWriteStatus, XSP_MASTER_OPTION, XSpi_CfgInitialize, XSpi_InterruptHandler, XSpi_LookupConfig, XSpi_SetOptions, XSpi_SetSlaveSelect, XSpi_SetStatusHandler, XSpi_Start.