xspi_options.c
XSP_NUM_OPTIONS
OptionsMap OptionsTable[][]
int XSpi_SetOptions(XSpi *InstancePtr, u32 Options)
This function sets the options for the SPI device driver.
The options control how the device behaves relative to the SPI bus. The device must be idle rather than busy transferring data before setting these device options. InstancePtr is a pointer to the XSpi instance to be worked on. Options contains the specified options to be set. This is a bit mask where a 1 means to turn the option on, and a 0 means to turn the option off. One or more bit values may be contained in the mask. See the bit definitions named XSP_*_OPTIONS in the file xspi.h. -XST_SUCCESS if options are successfully set. XST_DEVICE_BUSY if the device is currently transferring data. The transfer must complete or be aborted before setting options.XST_SPI_SLAVE_ONLY if the caller attempted to configure a slave-only device as a master. This function makes use of internal resources that are shared between the XSpi_Stop() and XSpi_SetOptions() functions. So if one task might be setting device options while another is trying to stop the device, the user is required to provide protection of this shared data (typically using a semaphore).
References XSpi::IsBusy, XSpi::IsReady, XSpi::SlaveOnly, XSP_MASTER_OPTION, XSpi_GetControlReg, XSpi_SetControlReg.
Referenced by main, SpiIntrExample, SpiPolledExample.
u32 XSpi_GetOptions(XSpi *InstancePtr)
This function gets the options for the SPI device.
The options control how the device behaves relative to the SPI bus. InstancePtr is a pointer to the XSpi instance to be worked on. Options contains the specified options to be set. This is a bit mask where a 1 means to turn the option on, and a 0 means to turn the option off. One or more bit values may be contained in the mask. See the bit definitions named XSP_*_OPTIONS in the file xspi.h.None.
References XSpi::IsReady, XSpi_GetControlReg.