xspi_atmel_flash_example.c
ATMEL_SPI_SELECT
ATMEL_COMMAND_READ
ATMEL_COMMAND_WRITE
ATMEL_COMMAND_STATUSREG_READ
ATMEL_COMMAND_PAGE_ERASE
ATMEL_READ_WRITE_EXTRA_BYTES
ATMEL_PAGE_ERASE_BYTES
ATMEL_STATUS_READ_BYTES
ATMEL_COMMAND_OFFSET
ATMEL_ADDRESS_BYTE1_OFFSET
ATMEL_ADDRESS_BYTE2_OFFSET
ATMEL_ADDRESS_BYTE3_OFFSET
ATMEL_FLASH_SR_IS_READY_MASK
ATMEL_PAGE_SIZE
ATMEL_FLASH_TEST_ADDRESS
ATMEL_TEST_BYTE
ATMEL_DUMMYBYTE
ATMEL_INITBYTE
XSpi Spi
volatile int TransferInProgress
int ErrorCount
u8 ReadBuffer[ATMEL_PAGE_SIZE+ATMEL_READ_WRITE_EXTRA_BYTES][ATMEL_PAGE_SIZE+ATMEL_READ_WRITE_EXTRA_BYTES]
u8 WriteBuffer[ATMEL_PAGE_SIZE+ATMEL_READ_WRITE_EXTRA_BYTES][ATMEL_PAGE_SIZE+ATMEL_READ_WRITE_EXTRA_BYTES]
void SpiHandler(void *CallBackRef, u32 StatusEvent, unsigned int ByteCount)
This function is the handler which performs processing for the SPI driver.
This function setups the interrupt system such that interrupts can occur for the SPI driver.It is called from an interrupt context such that the amount of processing performed should be minimized. It is called when a transfer of SPI data completes or an error occurs.This handler provides an example of how to handle SPI interrupts and is application specific. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. StatusEvent is the event that just occurred. ByteCount is the number of bytes transferred up until the event occurred. None. None. It is called from an interrupt context such that the amount of processing performed should be minimized. It is called when a transfer of SPI data completes or an error occurs.This handler provides an example of how to handle SPI interrupts but is application specific. CallBackRef is a reference passed to the handler. StatusEvent is the status of the SPI . ByteCount is the number of bytes transferred. None None. This function is application specific since the actual system may or may not have an interrupt controller. The SPI device could be directly connected to a processor without an interrupt controller. The user should modify this function to fit the application. SpiInstance contains a pointer to the instance of the XSpi component which is going to be connected to the interrupt controller. XST_SUCCESS if successful, else XST_FAILURE. None. This function is the handler which performs processing for the SPI driver. It is called from an interrupt context such that the amount of processing to be performed should be minimized. This handler provides an example of how to handle SPI interrupts but is application specific. CallBackRef is a reference passed to the handler. StatusEvent is the status of the SPI. ByteCount is the number of bytes transferred. None. None.
Referenced by main.
int SpiAtmelFlashRead(XSpi *SpiPtr, u32 Address, u16 ByteCount)
This function reads data from the Atmel Flash device connected to the SPI interface.
SpiPtr is a pointer to the SPI driver component to use. Address is the address from which the data is to be read from the Flash. ByteCount is the number of bytes to read. XST_SUCCESS if successful else XST_FAILURE. None.
References XSpi_Transfer.
Referenced by main.
int SpiAtmelFlashWrite(XSpi *SpiPtr, u32 Address, u16 ByteCount)
This function writes to the Atmel Flash device connected to the SPI interface.
SpiPtr is a pointer to the SPI driver component to use. Address is the address to which the data is written. ByteCount contains the number of bytes to write. XST_SUCCESS if successful else XST_FAILURE. None.
References XSpi_Transfer.
Referenced by main.
int SpiAtmelFlashPageErase(XSpi *SpiPtr, u32 Address)
This function erases the contents of the specified Page in the Flash.
SpiPtr is a pointer to the SPI driver component to use. Address contains the address of the page to be erased. XST_SUCCESS if successful else XST_FAILURE. None.
References XSpi_Transfer.
Referenced by main.
static int SpiAtmelFlashWaitForFlashNotBusy(XSpi *SpiPtr)
This function waits till the flash is ready to accept next command.
SpiPtr is a pointer to the SPI driver component to use. XST_SUCCESS if successful else XST_FAILURE. None.
int main(void)
Main function to execute the Atmel Flash example.
XST_SUCCESS if successful else XST_FAILURE. None
References XSpi_Config::BaseAddress, XSpi_Config::IntrId, XSpi_Config::IntrParent, SpiAtmelFlashPageErase, SpiAtmelFlashRead, SpiAtmelFlashWrite, SpiHandler, XSP_MASTER_OPTION, XSpi_CfgInitialize, XSpi_InterruptHandler, XSpi_LookupConfig, XSpi_SetOptions, XSpi_SetSlaveSelect, XSpi_SetStatusHandler, XSpi_Start.