xspi_selftest.c
XSP_SR_RESET_STATE
XSP_CR_RESET_STATE
XSP_HALF_WORD_TESTBYTE
XSP_WORD_TESTBYTE
static int LoopbackTest(XSpi *InstancePtr)
int XSpi_SelfTest(XSpi *InstancePtr)
Runs a self-test on the driver/device.
The self-test is destructive in that a reset of the device is performed in order to check the reset values of the registers and to get the device into a known state. A simple loopback test is also performed to verify that transmit and receive are working properly. The device is changed to master mode for the loopback test, since only a master can initiate a data transfer.Upon successful return from the self-test, the device is reset. InstancePtr is a pointer to the XSpi instance to be worked on. XST_SUCCESS if successful. XST_REGISTER_ERROR indicates a register did not read or write correctly. XST_LOOPBACK_ERROR if a loopback error occurred. None.
References XSpi::BaseAddr, XSpi::HasFifos, XSpi::IsReady, XSpi::SlaveSelectMask, XSpi::SpiMode, XSpi::XipMode, XSP_RFO_OFFSET, XSP_TFO_OFFSET, XSpi_GetControlReg, XSpi_GetSlaveSelectReg, XSpi_GetStatusReg, XSpi_ReadReg, XSpi_Reset.
Referenced by SpiIntrExample, SpiPolledExample, SpiSelfTestExample.