xspi_numonyx_flash_quad_example.c
SPI_SELECT
COMMAND_PAGE_PROGRAM
COMMAND_QUAD_WRITE
COMMAND_RANDOM_READ
COMMAND_DUAL_READ
COMMAND_DUAL_IO_READ
COMMAND_QUAD_READ
COMMAND_QUAD_IO_READ
COMMAND_WRITE_ENABLE
COMMAND_SECTOR_ERASE
COMMAND_BULK_ERASE
COMMAND_STATUSREG_READ
READ_WRITE_EXTRA_BYTES
This definitions specify the EXTRA bytes in each of the command transactions.
This count includes Command byte, address bytes and any don't care bytes needed.
Referenced by main, SpiFlashRead, SpiFlashWrite.
WRITE_ENABLE_BYTES
SECTOR_ERASE_BYTES
BULK_ERASE_BYTES
STATUS_READ_BYTES
STATUS_WRITE_BYTES
FLASH_SR_IS_READY_MASK
PAGE_SIZE
FLASH_TEST_ADDRESS
BYTE1
BYTE2
BYTE3
BYTE4
BYTE5
BYTE6
BYTE7
BYTE8
DUAL_READ_DUMMY_BYTES
QUAD_READ_DUMMY_BYTES
DUAL_IO_READ_DUMMY_BYTES
QUAD_IO_READ_DUMMY_BYTES
XSpi Spi
volatile int TransferInProgress
int ErrorCount
u8 ReadBuffer[PAGE_SIZE+READ_WRITE_EXTRA_BYTES+4][PAGE_SIZE+READ_WRITE_EXTRA_BYTES+4]
u8 WriteBuffer[PAGE_SIZE+READ_WRITE_EXTRA_BYTES][PAGE_SIZE+READ_WRITE_EXTRA_BYTES]
u8 TestByte
int SpiFlashWriteEnable(XSpi *SpiPtr)
This function enables writes to the Numonyx Serial Flash memory.
This function enables writes to the Winbond Serial Flash memory. SpiPtr is a pointer to the instance of the Spi device. XST_SUCCESS if successful else XST_FAILURE. None
References XSpi_Transfer.
Referenced by main, SpiFlashEnableHPM, SpiFlashQuadEnable.
int SpiFlashWrite(XSpi *SpiPtr, u32 Addr, u32 ByteCount, u8 WriteCmd)
This function writes the data to the specified locations in the Numonyx Serial Flash memory.
This function writes the data to the specified locations in the Winbond Serial Flash memory. SpiPtr is a pointer to the instance of the Spi device. Addr is the address in the Buffer, where to write the data. ByteCount is the number of bytes to be written. XST_SUCCESS if successful else XST_FAILURE. None SpiPtr is a pointer to the instance of the Spi device. Addr is the address in the Buffer, where to write the data. ByteCount is the number of bytes to be written. WriteCmd is the command used for writing data to flash. XST_SUCCESS if successful else XST_FAILURE. None
References READ_WRITE_EXTRA_BYTES, XSpi_Transfer.
Referenced by main.
int SpiFlashRead(XSpi *SpiPtr, u32 Addr, u32 ByteCount, u8 ReadCmd)
This function reads the data from the Numonyx Serial Flash Memory.
This function reads the data from the Winbond Serial Flash Memory. SpiPtr is a pointer to the instance of the Spi device. Addr is the starting address in the Flash Memory from which the data is to be read. ByteCount is the number of bytes to be read. XST_SUCCESS if successful else XST_FAILURE. None SpiPtr is a pointer to the instance of the Spi device. Addr is the starting address in the Flash Memory from which the data is to be read. ByteCount is the number of bytes to be read. ReadCmd is the command used for reading data from flash. XST_SUCCESS if successful else XST_FAILURE. None
References READ_WRITE_EXTRA_BYTES, XSpi_Transfer.
Referenced by main.
int SpiFlashBulkErase(XSpi *SpiPtr)
This function erases the entire contents of the Numonyx Serial Flash device.
This function erases the entire contents of the Winbond Serial Flash device. SpiPtr is a pointer to the instance of the Spi device. XST_SUCCESS if successful else XST_FAILURE. The erased bytes will read as 0xFF.
References XSpi_Transfer.
int SpiFlashSectorErase(XSpi *SpiPtr, u32 Addr)
This function erases the contents of the specified Sector in the Numonyx Serial Flash device.
This function erases the contents of the specified Sector in the Winbond Serial Flash device. SpiPtr is a pointer to the instance of the Spi device. Addr is the address within a sector of the Buffer, which is to be erased. XST_SUCCESS if successful else XST_FAILURE. The erased bytes will be read back as 0xFF.
References XSpi_Transfer.
Referenced by main.
int SpiFlashGetStatus(XSpi *SpiPtr)
This function reads the Status register of the Numonyx Flash.
This function reads the Status register of the Winbond Flash. SpiPtr is a pointer to the instance of the Spi device. XST_SUCCESS if successful else XST_FAILURE. The status register content is stored at the second byte pointed by the ReadBuffer.
References XSpi_Transfer.
int SpiFlashQuadEnable(XSpi *SpiPtr)
This function sets the QuadEnable bit in Winbond flash.
SpiPtr is a pointer to the instance of the Spi device. XST_SUCCESS if successful else XST_FAILURE. None.
References SpiFlashWriteEnable, XSpi_Transfer.
Referenced by main.
int SpiFlashEnableHPM(XSpi *SpiPtr)
This function enabled High Performance Mode in Winbond flash, so that data can be read from the flash using DIO and QIO commands.
SpiPtr is a pointer to the instance of the Spi device. XST_SUCCESS if successful else XST_FAILURE. None.
References SpiFlashWriteEnable, XSpi_Transfer.
Referenced by main.
int SpiFlashWaitForFlashReady(void)
This function waits till the Numonyx serial Flash is ready to accept next command.
None XST_SUCCESS if successful else XST_FAILURE. This function reads the status register of the Buffer and waits . till the WIP bit of the status register becomes 0.
void SpiHandler(void *CallBackRef, u32 StatusEvent, unsigned int ByteCount)
This function is the handler which performs processing for the SPI driver.
It is called from an interrupt context such that the amount of processing performed should be minimized. It is called when a transfer of SPI data completes or an error occurs.This handler provides an example of how to handle SPI interrupts and is application specific. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. StatusEvent is the event that just occurred. ByteCount is the number of bytes transferred up until the event occurred. None. None.
int main(void)
Main function to run the quad flash example.
XST_SUCCESS if successful else XST_FAILURE. None
References XSpi_Config::BaseAddress, XSpi_Config::IntrId, XSpi_Config::IntrParent, READ_WRITE_EXTRA_BYTES, SpiFlashRead, SpiFlashSectorErase, SpiFlashWrite, SpiFlashWriteEnable, SpiHandler, XSP_MASTER_OPTION, XSpi_CfgInitialize, XSpi_InterruptHandler, XSpi_LookupConfig, XSpi_SetOptions, XSpi_SetSlaveSelect, XSpi_SetStatusHandler, XSpi_Start.