xspi_stm_flash_example.c
STM_SPI_SELECT
STM_COMMAND_RANDOM_READ
STM_COMMAND_PAGEPROGRAM_WRITE
STM_COMMAND_WRITE_ENABLE
STM_COMMAND_SECTOR_ERASE
STM_COMMAND_BULK_ERASE
STM_COMMAND_STATUSREG_READ
STM_READ_WRITE_EXTRA_BYTES
This definitions specify the EXTRA bytes in each of the command transactions.
This count includes Command byte, address bytes and any don't care bytes needed.
Referenced by main, SpiStmFlashRead, SpiStmFlashWrite.
STM_WRITE_ENABLE_BYTES
STM_SECTOR_ERASE_BYTES
STM_BULK_ERASE_BYTES
STM_STATUS_READ_BYTES
STM_STATUS_WRITE_BYTES
STM_FLASH_SR_IS_READY_MASK
STM_PAGE_SIZE
STM_FLASH_TEST_ADDRESS
STM_FLASH_TEST_BYTE
BYTE1
BYTE2
BYTE3
BYTE4
BYTE5
STM_DUMMYBYTE
XSpi Spi
volatile int TransferInProgress
int ErrorCount
u8 ReadBuffer[STM_PAGE_SIZE+STM_READ_WRITE_EXTRA_BYTES][STM_PAGE_SIZE+STM_READ_WRITE_EXTRA_BYTES]
u8 WriteBuffer[STM_PAGE_SIZE+STM_READ_WRITE_EXTRA_BYTES][STM_PAGE_SIZE+STM_READ_WRITE_EXTRA_BYTES]
int SpiStmFlashWriteEnable(XSpi *SpiPtr)
This function enables writes to the STM Serial Flash memory.
SpiPtr is a pointer to the instance of the Spi device. XST_SUCCESS if successful else XST_FAILURE. None
References XSpi_Transfer.
Referenced by main.
int SpiStmFlashWrite(XSpi *SpiPtr, u32 Addr, u32 ByteCount)
This function writes the data to the specified locations in the STM Serial Flash memory.
SpiPtr is a pointer to the instance of the Spi device. Addr is the address in the Buffer, where to write the data. ByteCount is the number of bytes to be written. XST_SUCCESS if successful else XST_FAILURE. None
References STM_READ_WRITE_EXTRA_BYTES, XSpi_Transfer.
Referenced by main.
int SpiStmFlashRead(XSpi *SpiPtr, u32 Addr, u32 ByteCount)
This function reads the data from the STM Serial Flash Memory.
SpiPtr is a pointer to the instance of the Spi device. Addr is the starting address in the Flash Memory from which the data is to be read. ByteCount is the number of bytes to be read. XST_SUCCESS if successful else XST_FAILURE. None
References STM_READ_WRITE_EXTRA_BYTES, XSpi_Transfer.
Referenced by main.
int SpiStmFlashBulkErase(XSpi *SpiPtr)
This function erases the entire contents of the STM Serial Flash device.
SpiPtr is a pointer to the instance of the Spi device. XST_SUCCESS if successful else XST_FAILURE. The erased bytes will read as 0xFF.
References XSpi_Transfer.
int SpiStmFlashSectorErase(XSpi *SpiPtr, u32 Addr)
This function erases the contents of the specified Sector in the STM Serial Flash device.
SpiPtr is a pointer to the instance of the Spi device. Addr is the address within a sector of the Buffer, which is to be erased. XST_SUCCESS if successful else XST_FAILURE. The erased bytes will be read back as 0xFF.
References XSpi_Transfer.
Referenced by main.
int SpiStmFlashGetStatus(XSpi *SpiPtr)
This function reads the Status register of the STM Flash.
SpiPtr is a pointer to the instance of the Spi device. XST_SUCCESS if successful else XST_FAILURE. The status register content is stored at the second byte pointed by the ReadBuffer.
References XSpi_Transfer.
int SpiStmFlashWaitForFlashNotBusy(void)
This function waits till the STM serial Flash is ready to accept next command.
None XST_SUCCESS if successful else XST_FAILURE. This function reads the status register of the Buffer and waits . till the WIP bit of the status register becomes 0.
void SpiHandler(void *CallBackRef, u32 StatusEvent, unsigned int ByteCount)
This function is the handler which performs processing for the SPI driver.
It is called from an interrupt context such that the amount of processing performed should be minimized. It is called when a transfer of SPI data completes or an error occurs.This handler provides an example of how to handle SPI interrupts and is application specific. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. StatusEvent is the event that just occurred. ByteCount is the number of bytes transferred up until the event occurred. None. None.
int main(void)
Main function to execute the Flash example.
XST_SUCCESS if successful else XST_FAILURE. None
References XSpi_Config::BaseAddress, XSpi_Config::IntrId, XSpi_Config::IntrParent, SpiHandler, SpiStmFlashRead, SpiStmFlashSectorErase, SpiStmFlashWrite, SpiStmFlashWriteEnable, STM_READ_WRITE_EXTRA_BYTES, XSP_MASTER_OPTION, XSpi_CfgInitialize, XSpi_InterruptHandler, XSpi_LookupConfig, XSpi_SetOptions, XSpi_SetSlaveSelect, XSpi_SetStatusHandler, XSpi_Start.