xspi_sinit.c
XSpi_Config XSpi_ConfigTable[][]
This table contains configuration information for each SPI device in the system.
XSpi_Config * XSpi_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XSpi_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xspi.h for the definition of XSpi_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XSpi_Config::Name.
Referenced by main, SpiIntrExample, SpiPolledExample, SpiSelfTestExample, SpiXipExample, XSpi_Initialize.
int XSpi_Initialize(XSpi *InstancePtr, UINTPTR BaseAddress)
Initializes a specific XSpi instance such that the driver is ready to use.
The state of the device after initialization is: Device is disabledSlave modeActive high clock polarityClock phase 0 InstancePtr is a pointer to the XSpi instance to be worked on. BaseAddress contains the base address of the device - XST_SUCCESS if successful. - XST_DEVICE_IS_STARTED if the device is started. It must be stopped to re-initialize. - XST_DEVICE_NOT_FOUND if the device was not found in the configuration such that initialization could not be accomplished. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XSpi_Config::BaseAddress, XSpi_CfgInitialize, XSpi_LookupConfig.