xv_frmbufrd.c
int XV_frmbufrd_CfgInitialize(XV_frmbufrd *InstancePtr, XV_frmbufrd_Config *ConfigPtr, UINTPTR EffectiveAddr)
XV_frmbufrd_CfgInitialize - Initializes a XV_frmbufrd instance.
InstancePtr Pointer to the XV_frmbufrd instance to initialize. ConfigPtr Pointer to the configuration structure. EffectiveAddr Base address of the hardware instance. This function sets up the driver instance with the provided configuration and base address. It also marks the instance as ready for use.XST_SUCCESS on successful initialization.
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd_Config::IntrId, XV_frmbufrd_Config::IntrParent, XV_frmbufrd::IsReady.
Referenced by XV_frmbufrd_Initialize.
void XV_frmbufrd_Start(XV_frmbufrd *InstancePtr)
Starts the Frame Buffer Read core.
This function initiates the operation of the Frame Buffer Read (frmbufrd) hardware core. It asserts that the provided instance pointer is valid and that the core is ready. The function reads the current control register value, preserves the auto-restart bit, and sets the start bit to begin processing. InstancePtr Pointer to the XV_frmbufrd instance.
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd::IsReady.
Referenced by XVFrmbufRd_Start.
u32 XV_frmbufrd_IsDone(XV_frmbufrd *InstancePtr)
Checks if the Frame Buffer Read core has completed its operation.
This function reads the control register to determine if the hardware core has finished processing. It asserts that the instance pointer is valid and the core is ready, then checks the 'done' bit in the control register. InstancePtr Pointer to the XV_frmbufrd instance. 1 if the operation is done, 0 otherwise.
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd::IsReady.
u32 XV_frmbufrd_IsIdle(XV_frmbufrd *InstancePtr)
Checks if the XV_frmbufrd hardware core is currently idle.
This function reads the control register of the frame buffer read core and extracts the idle status bit. It asserts that the provided instance pointer is not NULL and that the instance is ready before accessing the hardware. InstancePtr is a pointer to the XV_frmbufrd instance. 1 if the core is idle, 0 otherwise.
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd::IsReady.
Referenced by XVFrmbufRd_WaitForIdle.
u32 XV_frmbufrd_IsReady(XV_frmbufrd *InstancePtr)
Checks if the Frame Buffer Read core is ready to accept new input.
This function reads the control register and checks the 'ap_start' bit to determine if the hardware core is ready for the next operation. If 'ap_start' is not set, the core is ready for new input. InstancePtr Pointer to the XV_frmbufrd instance. 1 if the core is ready for new input, 0 otherwise.
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd::IsReady.
void XV_frmbufrd_EnableAutoRestart(XV_frmbufrd *InstancePtr)
Enables auto-restart mode for the Frame Buffer Read core.
This function sets the auto-restart bit in the control register, allowing the hardware core to automatically restart its operation after completing the current task. It asserts that the provided instance pointer is valid and that the core is ready. InstancePtr Pointer to the XV_frmbufrd instance.
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd::IsReady.
Referenced by XVFrmbufRd_InterruptDisable.
void XV_frmbufrd_DisableAutoRestart(XV_frmbufrd *InstancePtr)
Disable the auto-restart feature of the Frame Buffer Read core.
This function disables the auto-restart capability by writing 0 to the AP_CTRL register of the Frame Buffer Read hardware. When auto-restart is disabled, the core will not automatically restart its operation after completing a frame; instead, it will require explicit re-enablement. InstancePtr Pointer to the XV_frmbufrd instance. The function asserts that the instance pointer is not NULL and that the core is ready before performing the operation.
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd::IsReady.
Referenced by XVFrmbufRd_InterruptEnable, XVFrmbufRd_Stop.
void XV_frmbufrd_SetFlushbit(XV_frmbufrd *InstancePtr)
Sets the flush bit in the Frame Buffer Read (frmbufrd) control register.
This function reads the current value of the control register, sets the flush bit, and writes the updated value back to the register. Setting the flush bit typically initiates a flush operation in the hardware, ensuring that any buffered data is processed or cleared as required. InstancePtr Pointer to the XV_frmbufrd instance. The function asserts that the InstancePtr is not NULL and that the instance is ready before performing the register operations.
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd::IsReady, XV_FRMBUFRD_CTRL_BITS_FLUSH_BIT.
Referenced by XVFrmbufRd_Stop.
u32 XV_frmbufrd_Get_FlushDone(XV_frmbufrd *InstancePtr)
Retrieves the flush done status from the Frame Buffer Read core.
This function reads the control register of the Frame Buffer Read (frmbufrd) instance and extracts the flush status bit, indicating whether the flush operation has completed. InstancePtr is a pointer to the XV_frmbufrd instance. The value of the flush done status bit (non-zero if flush is done, zero otherwise). None.
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd::IsReady, XV_FRMBUFRD_CTRL_BITS_FLUSH_STATUSBIT.
Referenced by XVFrmbufRd_Stop.
void XV_frmbufrd_Set_HwReg_width(XV_frmbufrd *InstancePtr, u32 Data)
Sets the hardware register value for the frame buffer reader width.
This function writes the specified width value to the hardware register associated with the frame buffer reader instance. InstancePtr Pointer to the XV_frmbufrd instance. Data The width value to be written to the hardware register. The InstancePtr must be initialized and ready before calling this function.
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd::IsReady, XV_FRMBUFRD_CTRL_ADDR_HWREG_WIDTH_DATA.
Referenced by XVFrmbufRd_SetMemFormat.
u32 XV_frmbufrd_Get_HwReg_width(XV_frmbufrd *InstancePtr)
Retrieves the hardware register value for the frame buffer reader width.
This function reads the width value from the hardware register associated with the frame buffer reader instance specified by InstancePtr. InstancePtr is a pointer to the XV_frmbufrd instance. The width value read from the hardware register. The InstancePtr must be initialized and ready before calling this function.
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd::IsReady, XV_FRMBUFRD_CTRL_ADDR_HWREG_WIDTH_DATA.
Referenced by XVFrmbufRd_DbgReportStatus.
void XV_frmbufrd_Set_HwReg_height(XV_frmbufrd *InstancePtr, u32 Data)
Sets the hardware register value for the frame buffer reader's height parameter.
This function writes the specified height value to the HWREG_HEIGHT register of the frame buffer reader hardware. It first asserts that the provided instance pointer is not NULL and that the instance is ready for operation. InstancePtr Pointer to the XV_frmbufrd instance. Data The height value to be written to the hardware register.
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd::IsReady, XV_FRMBUFRD_CTRL_ADDR_HWREG_HEIGHT_DATA.
Referenced by XVFrmbufRd_SetMemFormat.
u32 XV_frmbufrd_Get_HwReg_height(XV_frmbufrd *InstancePtr)
Retrieves the value of the hardware register that holds the frame buffer height.
This function reads the height value from the hardware register associated with the frame buffer read IP core. It asserts that the provided instance pointer is not NULL and that the instance is ready before accessing the register. InstancePtr is a pointer to the XV_frmbufrd instance. The height value read from the hardware register.
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd::IsReady, XV_FRMBUFRD_CTRL_ADDR_HWREG_HEIGHT_DATA.
Referenced by XVFrmbufRd_DbgReportStatus.
void XV_frmbufrd_Set_HwReg_stride(XV_frmbufrd *InstancePtr, u32 Data)
Sets the hardware register stride value for the frame buffer reader instance.
This function writes the specified stride value to the hardware register associated with the frame buffer reader. The stride typically represents the number of bytes between the start of one line of pixels and the next in memory. InstancePtr Pointer to the XV_frmbufrd instance. Data The stride value to be set in the hardware register. The instance pointer must be valid and the instance must be ready before calling this function.
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd::IsReady, XV_FRMBUFRD_CTRL_ADDR_HWREG_STRIDE_DATA.
Referenced by XVFrmbufRd_SetMemFormat.
u32 XV_frmbufrd_Get_HwReg_stride(XV_frmbufrd *InstancePtr)
Retrieves the current value of the hardware register that specifies the stride (number of bytes per line) for the frame buffer read instance.
InstancePtr Pointer to the XV_frmbufrd instance. Must not be NULL.Instance must be initialized and ready. The value of the HWREG_STRIDE register. This function asserts if the instance pointer is NULL or the instance is not ready.
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd::IsReady, XV_FRMBUFRD_CTRL_ADDR_HWREG_STRIDE_DATA.
Referenced by XVFrmbufRd_DbgReportStatus.
void XV_frmbufrd_Set_HwReg_video_format(XV_frmbufrd *InstancePtr, u32 Data)
Sets the hardware register for the video format in the Frame Buffer Read core.
This function writes the specified video format data to the hardware register responsible for configuring the video format of the Frame Buffer Read (frmbufrd) core. It first asserts that the provided instance pointer is not NULL and that the instance is ready before performing the register write. InstancePtr Pointer to the XV_frmbufrd instance. Data The video format data to be written to the hardware register.
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd::IsReady, XV_FRMBUFRD_CTRL_ADDR_HWREG_VIDEO_FORMAT_DATA.
Referenced by XVFrmbufRd_SetMemFormat.
u32 XV_frmbufrd_Get_HwReg_video_format(XV_frmbufrd *InstancePtr)
Retrieves the current hardware register value for the video format.
This function reads the HWREG_VIDEO_FORMAT register from the frame buffer reader hardware and returns its value. It asserts that the provided instance pointer is not NULL and that the instance is ready before accessing the hardware register. InstancePtr Pointer to the XV_frmbufrd instance. The value of the HWREG_VIDEO_FORMAT hardware register.
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd::IsReady, XV_FRMBUFRD_CTRL_ADDR_HWREG_VIDEO_FORMAT_DATA.
Referenced by XVFrmbufRd_DbgReportStatus.
void XV_frmbufrd_Set_HwReg_frm_buffer_V(XV_frmbufrd *InstancePtr, u64 Data)
Sets the hardware register for the frame buffer address in the XV_frmbufrd instance.
This function writes a 64-bit frame buffer address (Data) to the hardware registers associated with the frame buffer reader. The address is split into two 32-bit values and written to consecutive register addresses. InstancePtr Pointer to the XV_frmbufrd instance. Data 64-bit frame buffer address to be set in the hardware register. Preconditions: InstancePtr must not be NULL.InstancePtr->IsReady must be set to XIL_COMPONENT_IS_READY.
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd::IsReady, XV_FRMBUFRD_CTRL_ADDR_HWREG_FRM_BUFFER_V_DATA.
Referenced by XVFrmbufRd_SetBufferAddr.
u64 XV_frmbufrd_Get_HwReg_frm_buffer_V(XV_frmbufrd *InstancePtr)
Retrieves the 64-bit value of the HWREG_FRM_BUFFER_V hardware register.
This function reads two 32-bit values from the hardware register at the specified base address and register offset, combines them into a single 64-bit value, and returns it. InstancePtr Pointer to the XV_frmbufrd instance. Must not be NULL.The instance must be initialized and ready. The 64-bit value read from the HWREG_FRM_BUFFER_V register.
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd::IsReady, XV_FRMBUFRD_CTRL_ADDR_HWREG_FRM_BUFFER_V_DATA.
Referenced by XVFrmbufRd_DbgReportStatus, XVFrmbufRd_GetBufferAddr.
void XV_frmbufrd_Set_HwReg_frm_buffer2_V(XV_frmbufrd *InstancePtr, u64 Data)
Sets the hardware register for frame buffer 2 virtual address.
This function writes a 64-bit address (Data) to the hardware register associated with frame buffer 2. The address is split into two 32-bit values and written to consecutive register addresses. InstancePtr Pointer to the XV_frmbufrd instance. Data 64-bit virtual address to be set for frame buffer 2. Preconditions: InstancePtr must not be NULL.InstancePtr->IsReady must be set to XIL_COMPONENT_IS_READY.
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd::IsReady, XV_FRMBUFRD_CTRL_ADDR_HWREG_FRM_BUFFER2_V_DATA.
Referenced by XVFrmbufRd_SetChromaBufferAddr.
u64 XV_frmbufrd_Get_HwReg_frm_buffer2_V(XV_frmbufrd *InstancePtr)
Retrieves the 64-bit value from the HWREG_FRM_BUFFER2_V hardware register.
This function reads two consecutive 32-bit registers from the hardware to construct a 64-bit value representing the HWREG_FRM_BUFFER2_V register. It first asserts that the provided instance pointer is valid and that the hardware component is ready before performing the read operations. InstancePtr Pointer to the XV_frmbufrd instance. The 64-bit value read from the HWREG_FRM_BUFFER2_V register.
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd::IsReady, XV_FRMBUFRD_CTRL_ADDR_HWREG_FRM_BUFFER2_V_DATA.
Referenced by XVFrmbufRd_DbgReportStatus, XVFrmbufRd_GetChromaBufferAddr.
void XV_frmbufrd_Set_HwReg_frm_buffer3_V(XV_frmbufrd *InstancePtr, u64 Data)
Sets the hardware register for frame buffer 3 virtual address.
This function writes a 64-bit address (Data) to the hardware register associated with frame buffer 3 in the frame buffer read IP core. The address is split into two 32-bit values and written to consecutive register addresses. InstancePtr Pointer to the XV_frmbufrd instance. Data 64-bit virtual address to be set for frame buffer 3. The InstancePtr must be initialized and ready before calling this function.
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd::IsReady, XV_FRMBUFRD_CTRL_ADDR_HWREG_FRM_BUFFER3_V_DATA.
Referenced by XVFrmbufRd_SetVChromaBufferAddr.
u64 XV_frmbufrd_Get_HwReg_frm_buffer3_V(XV_frmbufrd *InstancePtr)
Retrieves the 64-bit value from the HWREG_FRM_BUFFER3_V hardware register.
This function reads two 32-bit registers from the hardware, combines them into a 64-bit value, and returns the result. It asserts that the provided instance pointer is not NULL and that the instance is ready before performing the read operations. InstancePtr Pointer to the XV_frmbufrd instance. The 64-bit value read from the HWREG_FRM_BUFFER3_V register.
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd::IsReady, XV_FRMBUFRD_CTRL_ADDR_HWREG_FRM_BUFFER3_V_DATA.
Referenced by XVFrmbufRd_DbgReportStatus, XVFrmbufRd_GetVChromaBufferAddr.
void XV_frmbufrd_Set_HwReg_field_id(XV_frmbufrd *InstancePtr, u32 Data)
Sets the HWREG_FIELD_ID register for the frame buffer reader instance.
This function writes the specified data value to the hardware register responsible for the field ID in the frame buffer reader. It asserts that the instance pointer is not NULL, the instance is ready, and the configuration is set to interlaced mode before performing the register write. InstancePtr Pointer to the XV_frmbufrd instance. Data Value to be written to the HWREG_FIELD_ID register.
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd_Config::Interlaced, XV_frmbufrd::IsReady, XV_FRMBUFRD_CTRL_ADDR_HWREG_FIELD_ID_DATA.
Referenced by XVFrmbufRd_SetFieldID.
u32 XV_frmbufrd_Get_HwReg_field_id(XV_frmbufrd *InstancePtr)
Retrieves the value of the HWREG_FIELD_ID register from the frame buffer reader instance.
This function asserts that the provided instance pointer is valid, the instance is ready, and that the configuration is set to interlaced mode. It then reads and returns the value of the HWREG_FIELD_ID register from the hardware. InstancePtr Pointer to the XV_frmbufrd instance. The value of the HWREG_FIELD_ID register.
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd_Config::Interlaced, XV_frmbufrd::IsReady, XV_FRMBUFRD_CTRL_ADDR_HWREG_FIELD_ID_DATA.
Referenced by XVFrmbufRd_GetFieldID.
void XV_frmbufrd_Set_HwReg_fidOutMode(XV_frmbufrd *InstancePtr, u32 Data)
Sets the value of the HWREG_FIDOUTMODE hardware register for the frame buffer reader.
This function writes the specified data value to the HWREG_FIDOUTMODE register of the frame buffer reader hardware instance pointed to by InstancePtr. InstancePtr Pointer to the XV_frmbufrd instance. Data The value to be written to the HWREG_FIDOUTMODE register. The InstancePtr must be initialized and ready before calling this function.
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd::IsReady, XV_FRMBUFRD_CTRL_ADDR_HWREG_FIDOUTMODE_DATA.
Referenced by XVFrmbufRd_Set_FidOutMode.
u32 XV_frmbufrd_Get_HwReg_fidOutMode(XV_frmbufrd *InstancePtr)
Retrieves the value of the HWREG_FIDOUTMODE hardware register for the specified Frame Buffer Read (frmbufrd) instance.
InstancePtr Pointer to the XV_frmbufrd instance. Must not be NULL.The instance must be initialized and ready. The current value of the HWREG_FIDOUTMODE register. This function asserts if the input pointer is NULL or the instance is not ready.
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd::IsReady, XV_FRMBUFRD_CTRL_ADDR_HWREG_FIDOUTMODE_DATA.
Referenced by XVFrmbufRd_Get_FidOutMode.
u32 XV_frmbufrd_Get_HwReg_fid_error(XV_frmbufrd *InstancePtr)
Retrieves the value of the HWREG_FID_ERROR register from the frame buffer reader instance.
This function reads the hardware register that indicates a frame ID error from the specified XV_frmbufrd instance. It asserts that the instance pointer is not NULL and that the instance is ready before accessing the register. InstancePtr Pointer to the XV_frmbufrd instance. The value of the HWREG_FID_ERROR register.
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd::IsReady, XV_FRMBUFRD_CTRL_ADDR_HWREG_FID_ERROR_DATA.
Referenced by XVFrmbufRd_Get_FidErrorCount, XVFrmbufRd_Get_FidErrorOut.
u32 XV_frmbufrd_Get_HwReg_field_out(XV_frmbufrd *InstancePtr)
Retrieves the value of the HWREG_FIELD_OUT hardware register for the given XV_frmbufrd instance.
This function reads the value from the HWREG_FIELD_OUT register using the base address specified in the instance's configuration. It asserts that the instance pointer is not NULL and that the instance is ready before performing the read operation. InstancePtr Pointer to the XV_frmbufrd instance. The value read from the HWREG_FIELD_OUT register.
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd::IsReady, XV_FRMBUFRD_CTRL_ADDR_HWREG_FIELD_OUT_DATA.
Referenced by XVFrmbufRd_Get_FieldOut.
void XV_frmbufrd_InterruptGlobalEnable(XV_frmbufrd *InstancePtr)
Enables the global interrupt for the Frame Buffer Read core.
This function sets the global interrupt enable (GIE) bit in the hardware, allowing the core to generate interrupts. It asserts that the provided instance pointer is valid and that the core is ready before enabling the interrupt. InstancePtr Pointer to the XV_frmbufrd instance.
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd::IsReady, XV_FRMBUFRD_CTRL_ADDR_GIE.
Referenced by XVFrmbufRd_InterruptEnable.
void XV_frmbufrd_InterruptGlobalDisable(XV_frmbufrd *InstancePtr)
Disables the global interrupt for the Frame Buffer Read core.
This function disables all interrupts generated by the Frame Buffer Read hardware by clearing the Global Interrupt Enable (GIE) register. InstancePtr Pointer to the XV_frmbufrd instance. The instance pointer must be valid and the core must be ready before calling this function.
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd::IsReady, XV_FRMBUFRD_CTRL_ADDR_GIE.
Referenced by XVFrmbufRd_InterruptDisable.
void XV_frmbufrd_InterruptEnable(XV_frmbufrd *InstancePtr, u32 Mask)
Enables specific interrupts for the Frame Buffer Read core.
This function sets the bits specified by the Mask parameter in the Interrupt Enable Register (IER) of the Frame Buffer Read hardware. Only the interrupts corresponding to the set bits in Mask will be enabled. InstancePtr Pointer to the XV_frmbufrd instance. Mask Bitmask of interrupts to enable. The InstancePtr must be initialized and ready before calling this function.
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd::IsReady, XV_FRMBUFRD_CTRL_ADDR_IER.
Referenced by XVFrmbufRd_InterruptEnable.
void XV_frmbufrd_InterruptDisable(XV_frmbufrd *InstancePtr, u32 Mask)
Disable specific interrupts for the Frame Buffer Read (frmbufrd) instance.
This function disables the interrupts specified by the Mask parameter for the given XV_frmbufrd instance. It reads the current interrupt enable register, clears the bits specified by Mask, and writes the updated value back to the register. InstancePtr Pointer to the XV_frmbufrd instance. Mask Bitmask of interrupts to disable. The InstancePtr must be initialized and ready before calling this function.
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd::IsReady, XV_FRMBUFRD_CTRL_ADDR_IER.
Referenced by XVFrmbufRd_InterruptDisable.
void XV_frmbufrd_InterruptClear(XV_frmbufrd *InstancePtr, u32 Mask)
Clears the specified interrupt(s) for the Frame Buffer Read (frmbufrd) instance.
This function writes the provided interrupt mask to the Interrupt Status Register (ISR) to clear the corresponding interrupt(s) for the given XV_frmbufrd instance. InstancePtr Pointer to the XV_frmbufrd instance. Mask Bitmask indicating which interrupt(s) to clear. The InstancePtr must be initialized and ready before calling this function.
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd::IsReady, XV_FRMBUFRD_CTRL_ADDR_ISR.
Referenced by XVFrmbufRd_InterruptHandler.
u32 XV_frmbufrd_InterruptGetEnabled(XV_frmbufrd *InstancePtr)
Retrieves the interrupt enable register value for the Frame Buffer Read (frmbufrd) instance.
This function checks that the provided instance pointer is valid and that the instance is ready. It then reads and returns the value of the Interrupt Enable Register (IER) from the hardware. InstancePtr Pointer to the XV_frmbufrd instance. The current value of the Interrupt Enable Register (IER).
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd::IsReady, XV_FRMBUFRD_CTRL_ADDR_IER.
u32 XV_frmbufrd_InterruptGetStatus(XV_frmbufrd *InstancePtr)
Retrieves the interrupt status register value for the Frame Buffer Read (frmbufrd) instance.
This function asserts that the provided instance pointer is valid and that the instance is ready. It then reads and returns the value of the Interrupt Status Register (ISR) from the hardware, indicating which interrupts are currently active. InstancePtr Pointer to the XV_frmbufrd instance. The current value of the Interrupt Status Register (ISR).
References XV_frmbufrd_Config::BaseAddress, XV_frmbufrd::Config, XV_frmbufrd::IsReady, XV_FRMBUFRD_CTRL_ADDR_ISR.
Referenced by XVFrmbufRd_InterruptHandler.