axiethernet
XAE_PROMISC_OPTION
< XAE_PROMISC_OPTION specifies the Axi Ethernet device to accept all incoming packets.
This driver sets this option to disabled (cleared) by default.XAE_JUMBO_OPTION specifies the Axi Ethernet device to accept jumbo frames for transmit and receive. This driver sets this option to disabled (cleared) by default.
Referenced by XAxiEthernet_ClearOptions, XAxiEthernet_SetOptions.
XAE_JUMBO_OPTION
XAE_VLAN_OPTION specifies the Axi Ethernet device to enable VLAN support for transmit and receive.
This driver sets this option to disabled (cleared) by default.
Referenced by AxiEthernetSgDmaIntrExtVlanExample, XAxiEthernet_ClearOptions, XAxiEthernet_SetOptions.
XAE_VLAN_OPTION
XAE_FLOW_CONTROL_OPTION specifies the Axi Ethernet device to recognize received flow control frames.
This driver sets this option to enabled (set) by default.
Referenced by XAxiEthernet_ClearOptions, XAxiEthernet_SetOptions.
XAE_FLOW_CONTROL_OPTION
XAE_FCS_STRIP_OPTION specifies the Axi Ethernet device to strip FCS and PAD from received frames.
Note that PAD from VLAN frames is not stripped. This driver sets this option to enabled (set) by default.
Referenced by XAxiEthernet_ClearOptions, XAxiEthernet_SetOptions.
XAE_FCS_STRIP_OPTION
XAE_FCS_INSERT_OPTION specifies the Axi Ethernet device to generate the FCS field and add PAD automatically for outgoing frames.
This driver sets this option to enabled (set) by default.
Referenced by XAxiEthernet_ClearOptions, XAxiEthernet_SetOptions.
XAE_FCS_INSERT_OPTION
XAE_LENTYPE_ERR_OPTION specifies the Axi Ethernet device to enable Length/Type error checking (mismatched type/length field) for received frames.
This driver sets this option to enabled (set) by default.
Referenced by XAxiEthernet_ClearOptions, XAxiEthernet_SetOptions.
XAE_LENTYPE_ERR_OPTION
XAE_TRANSMITTER_ENABLE_OPTION specifies the Axi Ethernet device transmitter to be enabled.
This driver sets this option to enabled (set) by default.
Referenced by XAxiEthernet_ClearOptions, XAxiEthernet_SetOptions.
XAE_TRANSMITTER_ENABLE_OPTION
XAE_RECEIVER_ENABLE_OPTION specifies the Axi Ethernet device receiver to be enabled.
This driver sets this option to enabled (set) by default.
Referenced by AxiEthernetPingReqExample, AxiEthernetSgDmaFullChecksumOffloadExample, AxiEthernetSgDmaIntrCoalescingExample, AxiEthernetSgDmaIntrExtMulticastExample, AxiEthernetSgDmaIntrExtVlanExample, AxiEthernetSgDmaIntrMultiFrameExample, AxiEthernetSgDmaIntrSingleFrameExample, AxiEthernetSgDmaMultiFrameExample, AxiEthernetSgDmaPartialChecksumOffloadExample, AxiEthernetSgDmaSingleFrameExample, XAxiEthernet_ClearOptions, XAxiEthernet_SetOptions, XAxiEthernet_Start.
XAE_RECEIVER_ENABLE_OPTION
XAE_BROADCAST_OPTION specifies the Axi Ethernet device to receive frames sent to the broadcast Ethernet address.
This driver sets this option to enabled (set) by default.
Referenced by AxiEthernetPingReqExample, AxiEthernetSgDmaFullChecksumOffloadExample, AxiEthernetSgDmaIntrCoalescingExample, AxiEthernetSgDmaIntrExtMulticastExample, AxiEthernetSgDmaIntrExtVlanExample, AxiEthernetSgDmaIntrMultiFrameExample, AxiEthernetSgDmaIntrSingleFrameExample, AxiEthernetSgDmaMultiFrameExample, AxiEthernetSgDmaPartialChecksumOffloadExample, AxiEthernetSgDmaSingleFrameExample, XAxiEthernet_ClearOptions, XAxiEthernet_SetOptions, XAxiEthernet_Start.
XAE_BROADCAST_OPTION
XAE_MULTICAST_OPTION specifies the Axi Ethernet device to receive frames sent to Ethernet addresses that are programmed into the Multicast Address Table (MAT).
This driver sets this option to disabled (cleared) by default.
Referenced by XAxiEthernet_ClearOptions, XAxiEthernet_SetOptions.
XAE_MULTICAST_OPTION
XAE_EXT_MULTICAST_OPTION specifies the Axi Ethernet device to receive frames sent to Ethernet addresses that are programmed into the Multicast Address Table.
This driver sets this option to be dependent on HW configuration by default.
Referenced by XAxiEthernet_ClearOptions, XAxiEthernet_SetOptions.
XAE_EXT_MULTICAST_OPTION
XAE_EXT_TXVLAN_TRAN_OPTION specifies the Axi Ethernet device to enable transmit VLAN translation.
This driver sets this option to be dependent on HW configuration by default.
Referenced by AxiEthernetSgDmaIntrExtMulticastExample.
XAE_EXT_TXVLAN_TRAN_OPTION
XAE_EXT_RXVLAN_TRAN_OPTION specifies the Axi Ethernet device to enable receive VLAN translation.
This driver sets this option to be dependent on HW configuration by default.
Referenced by AxiEthernetSgDmaIntrExtVlanExample.
XAE_EXT_RXVLAN_TRAN_OPTION
XAE_EXT_TXVLAN_TAG_OPTION specifies the Axi Ethernet device to enable transmit VLAN tagging.
This driver sets this option to be dependent during HW build time by default.
Referenced by AxiEthernetSgDmaIntrExtVlanExample.
XAE_EXT_TXVLAN_TAG_OPTION
XAE_EXT_RXVLAN_TAG_OPTION specifies the Axi Ethernet device to enable receive VLAN tagging.
This driver sets this option to be dependent during HW build time by default.
Referenced by AxiEthernetSgDmaIntrExtVlanExample.
XAE_EXT_RXVLAN_TAG_OPTION
XAE_EXT_TXVLAN_STRP_OPTION specifies the Axi Ethernet device to enable transmit VLAN stripping.
This driver sets this option to be dependent during HW build time by default.
XAE_EXT_TXVLAN_STRP_OPTION
XAE_EXT_RXVLAN_STRP_OPTION specifies the Axi Ethernet device to enable receive VLAN stripping.
This driver sets this option to be dependent during HW build time by default.
XAE_EXT_RXVLAN_STRP_OPTION
XAE_DEFAULT_OPTIONS
XAE_DEFAULT_OPTIONS specify the options set in XAxiEthernet_Reset() and XAxiEthernet_CfgInitialize()
Referenced by AxiEthernetSgDmaIntrExtMulticastExample, XAxiEthernet_Reset, XAxiEthernet_SetOptions.
XAE_RAF_OFFSET
Reset and Address filter.
Referenced by XAxiEthernet_ClearBadFrmRcvOption, XAxiEthernet_ClearOptions, XAxiEthernet_GetVStripMode, XAxiEthernet_GetVTagMode, XAxiEthernet_SetBadFrmRcvOption, XAxiEthernet_SetOptions, XAxiEthernet_SetVStripMode, XAxiEthernet_SetVTagMode.
XAE_TPF_OFFSET
Tx Pause Frame.
Referenced by XAxiEthernet_SendPausePacket.
XAE_IFGP_OFFSET
Tx Inter-frame gap adjustment.
XAE_IS_OFFSET
Interrupt status.
Referenced by XAxiEthernet_Reset, XAxiEthernet_Stop.
XAE_IP_OFFSET
Interrupt pending.
Referenced by XAxiEthernet_Stop.
XAE_IE_OFFSET
Interrupt enable.
Referenced by XAxiEthernet_Stop.
XAE_TTAG_OFFSET
Tx VLAN TAG.
Referenced by XAxiEthernet_GetVTagValue, XAxiEthernet_SetVTagValue.
XAE_RTAG_OFFSET
Rx VLAN TAG.
Referenced by XAxiEthernet_GetVTagValue, XAxiEthernet_SetVTagValue.
XAE_UAWL_OFFSET
Unicast address word lower.
Referenced by XAxiEthernet_GetMacAddress, XAxiEthernet_SetMacAddress.
XAE_UAWU_OFFSET
Unicast address word upper.
Referenced by XAxiEthernet_GetMacAddress, XAxiEthernet_SetMacAddress.
XAE_TPID0_OFFSET
VLAN TPID0 register.
Referenced by XAxiEthernet_ClearTpid, XAxiEthernet_GetTpid, XAxiEthernet_SetTpid.
XAE_TPID1_OFFSET
VLAN TPID1 register.
Referenced by XAxiEthernet_ClearTpid, XAxiEthernet_GetTpid, XAxiEthernet_SetTpid.
XAE_RXBL_OFFSET
Received Bytes, LSW.
XAE_RXBU_OFFSET
Received Bytes, MSW.
XAE_TXBL_OFFSET
Transmitted Bytes, LSW.
XAE_TXBU_OFFSET
Transmitted Bytes, MSW.
XAE_RXUNDRL_OFFSET
Count of undersize(less than 64 bytes) frames received, LSW.
XAE_RXUNDRU_OFFSET
Count of undersize(less than 64 bytes) frames received, MSW.
XAE_RXFRAGL_OFFSET
Count of undersized(less than 64 bytes) and bad FCS frames received, LSW.
XAE_RXFRAGU_OFFSET
Count of undersized(less than 64 bytes) and bad FCS frames received, MSW.
XAE_RX64BL_OFFSET
Count of 64 bytes frames received, LSW.
XAE_RX64BU_OFFSET
Count of 64 bytes frames received, MSW.
XAE_RX65B127L_OFFSET
Count of 65-127 bytes Frames received, LSW.
XAE_RX65B127U_OFFSET
Count of 65-127 bytes Frames received, MSW.
XAE_RX128B255L_OFFSET
Count of 128-255 bytes Frames received, LSW.
XAE_RX128B255U_OFFSET
Count of 128-255 bytes frames received, MSW.
XAE_RX256B511L_OFFSET
Count of 256-511 bytes Frames received, LSW.
XAE_RX256B511U_OFFSET
Count of 256-511 bytes frames received, MSW.
XAE_RX512B1023L_OFFSET
Count of 512-1023 bytes frames received, LSW.
XAE_RX512B1023U_OFFSET
Count of 512-1023 bytes frames received, MSW.
XAE_RX1024BL_OFFSET
Count of 1024-MAX bytes frames received, LSW.
XAE_RX1024BU_OFFSET
Count of 1024-MAX bytes frames received, MSW.
XAE_RXOVRL_OFFSET
Count of oversize frames received, LSW.
XAE_RXOVRU_OFFSET
Count of oversize frames received, MSW.
XAE_TX64BL_OFFSET
Count of 64 bytes frames transmitted, LSW.
XAE_TX64BU_OFFSET
Count of 64 bytes frames transmitted, MSW.
XAE_TX65B127L_OFFSET
Count of 65-127 bytes frames transmitted, LSW.
XAE_TX65B127U_OFFSET
Count of 65-127 bytes frames transmitted, MSW.
XAE_TX128B255L_OFFSET
Count of 128-255 bytes frames transmitted, LSW.
XAE_TX128B255U_OFFSET
Count of 128-255 bytes frames transmitted, MSW.
XAE_TX256B511L_OFFSET
Count of 256-511 bytes frames transmitted, LSW.
XAE_TX256B511U_OFFSET
Count of 256-511 bytes frames transmitted, MSW.
XAE_TX512B1023L_OFFSET
Count of 512-1023 bytes frames transmitted, LSW.
XAE_TX512B1023U_OFFSET
Count of 512-1023 bytes frames transmitted, MSW.
XAE_TX1024L_OFFSET
Count of 1024-MAX bytes frames transmitted, LSW.
XAE_TX1024U_OFFSET
Count of 1024-MAX bytes frames transmitted, MSW.
XAE_TXOVRL_OFFSET
Count of oversize frames transmitted, LSW.
XAE_TXOVRU_OFFSET
Count of oversize frames transmitted, MSW.
XAE_RXFL_OFFSET
Count of frames received OK, LSW.
XAE_RXFU_OFFSET
Count of frames received OK, MSW.
XAE_RXFCSERL_OFFSET
Count of frames received with FCS error and at least 64 bytes, LSW.
XAE_RXFCSERU_OFFSET
Count of frames received with FCS error and at least 64 bytes,MSW.
XAE_RXBCSTFL_OFFSET
Count of broadcast frames received, LSW.
XAE_RXBCSTFU_OFFSET
Count of broadcast frames received, MSW.
XAE_RXMCSTFL_OFFSET
Count of multicast frames received, LSW.
XAE_RXMCSTFU_OFFSET
Count of multicast frames received, MSW.
XAE_RXCTRFL_OFFSET
Count of control frames received, LSW.
XAE_RXCTRFU_OFFSET
Count of control frames received, MSW.
XAE_RXLTERL_OFFSET
Count of frames received with length error, LSW.
XAE_RXLTERU_OFFSET
Count of frames received with length error, MSW.
XAE_RXVLANFL_OFFSET
Count of VLAN tagged frames received, LSW.
XAE_RXVLANFU_OFFSET
Count of VLAN tagged frames received, MSW.
XAE_RXPFL_OFFSET
Count of pause frames received, LSW.
XAE_RXPFU_OFFSET
Count of pause frames received, MSW.
XAE_RXUOPFL_OFFSET
Count of control frames received with unsupported opcode, LSW.
XAE_RXUOPFU_OFFSET
Count of control frames received with unsupported opcode, MSW.
XAE_TXFL_OFFSET
Count of frames transmitted OK, LSW.
XAE_TXFU_OFFSET
Count of frames transmitted OK, MSW.
XAE_TXBCSTFL_OFFSET
Count of broadcast frames transmitted OK, LSW.
XAE_TXBCSTFU_OFFSET
Count of broadcast frames transmitted, MSW.
XAE_TXMCSTFL_OFFSET
Count of multicast frames transmitted, LSW.
XAE_TXMCSTFU_OFFSET
Count of multicast frames transmitted, MSW.
XAE_TXUNDRERL_OFFSET
Count of frames transmitted underrun error, LSW.
XAE_TXUNDRERU_OFFSET
Count of frames transmitted underrun error, MSW.
XAE_TXCTRFL_OFFSET
Count of control frames transmitted, LSW.
XAE_TXCTRFU_OFFSET
Count of control frames, transmitted, MSW.
XAE_TXVLANFL_OFFSET
Count of VLAN tagged frames transmitted, LSW.
XAE_TXVLANFU_OFFSET
Count of VLAN tagged frames transmitted, MSW.
XAE_TXPFL_OFFSET
Count of pause frames transmitted, LSW.
XAE_TXPFU_OFFSET
Count of pause frames transmitted, MSW.
XAE_TXSCL_OFFSET
Single Collision Frames Transmitted OK, LSW.
XAE_TXSCU_OFFSET
Single Collision Frames Transmitted OK, MSW.
XAE_TXMCL_OFFSET
Multiple Collision Frames Transmitted OK, LSW.
XAE_TXMCU_OFFSET
Multiple Collision Frames Transmitted OK, MSW.
XAE_TXDEFL_OFFSET
Deferred Tx Frames, LSW.
XAE_TXDEFU_OFFSET
Deferred Tx Frames, MSW.
XAE_TXLTCL_OFFSET
Frames transmitted with late Collisions, LSW.
XAE_TXLTCU_OFFSET
Frames transmitted with late Collisions, MSW.
XAE_TXAECL_OFFSET
Frames aborted with excessive Collisions, LSW.
XAE_TXAECU_OFFSET
Frames aborted with excessive Collisions, MSW.
XAE_TXEDEFL_OFFSET
Transmit Frames with excessive Defferal, LSW.
XAE_TXEDEFU_OFFSET
Transmit Frames with excessive Defferal, MSW.
XAE_RXAERL_OFFSET
Frames received with alignment errors, LSW.
XAE_RXAERU_OFFSET
Frames received with alignment errors, MSW.
XAE_RCW0_OFFSET
Rx Configuration Word 0.
Referenced by XAxiEthernet_GetMacPauseAddress, XAxiEthernet_SetMacPauseAddress.
XAE_RCW1_OFFSET
Rx Configuration Word 1.
Referenced by XAxiEthernet_ClearOptions, XAxiEthernet_DisableControlFrameLenCheck, XAxiEthernet_EnableControlFrameLenCheck, XAxiEthernet_GetMacPauseAddress, XAxiEthernet_SetMacPauseAddress, XAxiEthernet_SetOptions, XAxiEthernet_Start, XAxiEthernet_Stop.
XAE_TC_OFFSET
Tx Configuration.
Referenced by XAxiEthernet_ClearOptions, XAxiEthernet_SetOptions, XAxiEthernet_Start.
XAE_FCC_OFFSET
Flow Control Configuration.
Referenced by XAxiEthernet_ClearOptions, XAxiEthernet_SetOptions.
XAE_EMMC_OFFSET
EMAC mode configuration.
Referenced by XAxiEthernet_GetOperatingSpeed, XAxiEthernet_SetOperatingSpeed.
XAE_RXFC_OFFSET
Rx Max Frm Config Register.
XAE_TXFC_OFFSET
Tx Max Frm Config Register.
XAE_TX_TIMESTAMP_ADJ_OFFSET
Transmitter time stamp adjust control Register.
XAE_PHYC_OFFSET
RGMII/SGMII configuration.
Referenced by XAxiEthernet_GetRgmiiStatus, XAxiEthernet_GetSgmiiStatus.
XAE_IDREG_OFFSET
Identification Register.
XAE_ARREG_OFFSET
Ability Register.
XAE_MDIO_MC_OFFSET
MII Management Config.
Referenced by XAxiEthernet_PhySetMdioDivisor.
XAE_MDIO_MCR_OFFSET
MII Management Control.
XAE_MDIO_MWD_OFFSET
MII Management Write Data.
XAE_MDIO_MRD_OFFSET
MII Management Read Data.
XAE_MDIO_MIS_OFFSET
MII Management Interrupt Status.
XAE_MDIO_MIP_OFFSET
MII Management Interrupt Pending register offse.
XAE_MDIO_MIE_OFFSET
MII Management Interrupt Enable register offset.
XAE_MDIO_MIC_OFFSET
MII Management Interrupt Clear register offset.
XAE_UAW0_OFFSET
Unicast address word 0.
Referenced by XAxiEthernet_GetMacAddress, XAxiEthernet_SetMacAddress.
XAE_UAW1_OFFSET
Unicast address word 1.
Referenced by XAxiEthernet_GetMacAddress, XAxiEthernet_SetMacAddress.
XAE_FMI_OFFSET
Filter Mask Index.
Referenced by XAxiEthernet_ClearOptions, XAxiEthernet_MulticastAdd, XAxiEthernet_MulticastClear, XAxiEthernet_MulticastGet, XAxiEthernet_SetOptions.
XAE_AF0_OFFSET
Address Filter 0.
Referenced by XAxiEthernet_MulticastAdd, XAxiEthernet_MulticastClear, XAxiEthernet_MulticastGet.
XAE_AF1_OFFSET
Address Filter 1.
Referenced by XAxiEthernet_MulticastAdd, XAxiEthernet_MulticastClear, XAxiEthernet_MulticastGet.
XAE_TX_VLAN_DATA_OFFSET
TX VLAN data table address.
Referenced by XAxiEthernet_GetVidTable, XAxiEthernet_SetVidTable.
XAE_RX_VLAN_DATA_OFFSET
RX VLAN data table address.
Referenced by XAxiEthernet_GetVidTable, XAxiEthernet_SetVidTable.
XAE_MCAST_TABLE_OFFSET
Multicast table address.
Referenced by XAxiEthernet_AddExtMulticastGroup, XAxiEthernet_ClearExtMulticastGroup, XAxiEthernet_DumpExtMulticastGroup, XAxiEthernet_GetExtMulticastGroup.
XAE_RAF_MCSTREJ_MASK
Reject receive multicast destination address.
Referenced by XAxiEthernet_ClearOptions, XAxiEthernet_SetOptions.
XAE_RAF_BCSTREJ_MASK
Reject receive broadcast destination address.
Referenced by XAxiEthernet_ClearOptions, XAxiEthernet_SetOptions.
XAE_RAF_TXVTAGMODE_MASK
Tx VLAN TAG mode.
Referenced by XAxiEthernet_ClearOptions, XAxiEthernet_GetVTagMode, XAxiEthernet_SetOptions, XAxiEthernet_SetVTagMode.
XAE_RAF_RXVTAGMODE_MASK
Rx VLAN TAG mode.
Referenced by XAxiEthernet_ClearOptions, XAxiEthernet_GetVTagMode, XAxiEthernet_SetOptions, XAxiEthernet_SetVTagMode.
XAE_RAF_TXVSTRPMODE_MASK
Tx VLAN STRIP mode.
Referenced by XAxiEthernet_ClearOptions, XAxiEthernet_GetVStripMode, XAxiEthernet_SetOptions, XAxiEthernet_SetVStripMode.
XAE_RAF_RXVSTRPMODE_MASK
Rx VLAN STRIP mode.
Referenced by XAxiEthernet_ClearOptions, XAxiEthernet_GetVStripMode, XAxiEthernet_SetOptions, XAxiEthernet_SetVStripMode.
XAE_RAF_NEWFNCENBL_MASK
New function mode.
Referenced by XAxiEthernet_ClearOptions, XAxiEthernet_SetOptions.
XAE_RAF_EMULTIFLTRENBL_MASK
Extended Multicast Filtering mode.
Referenced by XAxiEthernet_ClearOptions, XAxiEthernet_SetOptions.
XAE_RAF_STATSRST_MASK
Statistics Counter Reset.
XAE_RAF_RXBADFRMEN_MASK
Receive Bad Frame Enable.
Referenced by XAxiEthernet_ClearBadFrmRcvOption, XAxiEthernet_SetBadFrmRcvOption.
XAE_RAF_TXVTAGMODE_SHIFT
Tx Tag mode shift bits.
Referenced by XAxiEthernet_GetVTagMode, XAxiEthernet_SetOptions, XAxiEthernet_SetVTagMode.
XAE_RAF_RXVTAGMODE_SHIFT
Rx Tag mode shift bits.
Referenced by XAxiEthernet_GetVTagMode, XAxiEthernet_SetOptions, XAxiEthernet_SetVTagMode.
XAE_RAF_TXVSTRPMODE_SHIFT
Tx strip mode shift bits.
Referenced by XAxiEthernet_GetVStripMode, XAxiEthernet_SetOptions, XAxiEthernet_SetVStripMode.
XAE_RAF_RXVSTRPMODE_SHIFT
Rx Strip mode shift bits.
Referenced by XAxiEthernet_GetVStripMode, XAxiEthernet_SetOptions, XAxiEthernet_SetVStripMode.
XAE_TPF_TPFV_MASK
Tx pause frame value.
Referenced by XAxiEthernet_SendPausePacket.
XAE_TFGP_IFGP_MASK
Transmit inter-frame gap adjustment value.
XAE_INT_HARDACSCMPLT_MASK
Hard register access complete.
XAE_INT_AUTONEG_MASK
Auto negotiation complete.
XAE_INT_RXCMPIT_MASK
Rx complete.
XAE_INT_RXRJECT_MASK
Rx frame rejected.
Referenced by AxiEthernetPollForRxStatus, AxiEthernetSgDmaIntrExample, AxiEthernetSingleFrameIntrExample, XAxiEthernet_Stop.
XAE_INT_RXFIFOOVR_MASK
Rx fifo overrun.
Referenced by AxiEthernetPollForRxStatus, AxiEthernetSgDmaIntrExample, AxiEthernetSingleFrameIntrExample.
XAE_INT_TXCMPIT_MASK
Tx complete.
XAE_INT_RXDCMLOCK_MASK
Rx Dcm Lock.
XAE_INT_MGTRDY_MASK
MGT clock Lock.
Referenced by XAxiEthernet_Reset.
XAE_INT_PHYRSTCMPLT_MASK
Phy Reset complete.
XAE_INT_ALL_MASK
All the ints.
XAE_INT_RECV_ERROR_MASK
INT bits that indicate receive errors.
Referenced by AxiEthernetSgDmaFullChecksumOffloadExample, AxiEthernetSgDmaIntrExtMulticastExample, AxiEthernetSgDmaIntrExtVlanExample, AxiEthernetSgDmaIntrSingleFrameExample, AxiEthernetSgDmaPartialChecksumOffloadExample.
XAE_TPID_0_MASK
TPID 0.
Referenced by XAxiEthernet_ClearTpid, XAxiEthernet_GetTpid, XAxiEthernet_SetTpid.
XAE_TPID_1_MASK
TPID 1.
Referenced by XAxiEthernet_ClearTpid, XAxiEthernet_SetTpid.
XAE_RCW1_RST_MASK
Reset.
XAE_RCW1_JUM_MASK
Jumbo frame enable.
Referenced by XAxiEthernet_ClearOptions, XAxiEthernet_SetOptions.
XAE_RCW1_FCS_MASK
In-Band FCS enable (FCS not stripped)
Referenced by XAxiEthernet_ClearOptions, XAxiEthernet_SetOptions.
XAE_RCW1_RX_MASK
Receiver enable.
Referenced by XAxiEthernet_ClearOptions, XAxiEthernet_SetOptions, XAxiEthernet_Start, XAxiEthernet_Stop.
XAE_RCW1_VLAN_MASK
VLAN frame enable.
Referenced by XAxiEthernet_ClearOptions, XAxiEthernet_SetOptions.
XAE_RCW1_LT_DIS_MASK
Length/type field valid check disable.
Referenced by XAxiEthernet_ClearOptions, XAxiEthernet_SetOptions.
XAE_RCW1_CL_DIS_MASK
Control frame Length check disable.
Referenced by XAxiEthernet_DisableControlFrameLenCheck, XAxiEthernet_EnableControlFrameLenCheck.
XAE_RCW1_1588_TIMESTAMP_EN_MASK
Inband 1588 time stamp enable.
XAE_RCW1_PAUSEADDR_MASK
Pause frame source address bits [47:32].Bits [31:0] are stored in register RCW0.
Referenced by XAxiEthernet_SetMacPauseAddress.
XAE_TC_RST_MASK
Reset.
XAE_TC_JUM_MASK
Jumbo frame enable.
Referenced by XAxiEthernet_ClearOptions, XAxiEthernet_SetOptions.
XAE_TC_FCS_MASK
In-Band FCS enable (FCS not generated)
Referenced by XAxiEthernet_ClearOptions, XAxiEthernet_SetOptions.
XAE_TC_TX_MASK
Transmitter enable.
Referenced by XAxiEthernet_ClearOptions, XAxiEthernet_SetOptions, XAxiEthernet_Start.
XAE_TC_VLAN_MASK
VLAN frame enable.
Referenced by XAxiEthernet_ClearOptions, XAxiEthernet_SetOptions.
XAE_TC_IFG_MASK
Inter-frame gap adjustment enable.
XAE_TC_1588_CMD_EN_MASK
1588 Cmd field enable
XAE_FCC_FCRX_MASK
Rx flow control enable.
Referenced by XAxiEthernet_ClearOptions, XAxiEthernet_SetOptions.
XAE_FCC_FCTX_MASK
Tx flow control enable.
XAE_EMMC_LINKSPEED_MASK
Link speed.
Referenced by XAxiEthernet_GetOperatingSpeed, XAxiEthernet_SetOperatingSpeed.
XAE_EMMC_RGMII_MASK
RGMII mode enable.
XAE_EMMC_SGMII_MASK
SGMII mode enable.
XAE_EMMC_GPCS_MASK
1000BaseX mode enable
XAE_EMMC_HOST_MASK
Host interface enable.
XAE_EMMC_TX16BIT
16 bit Tx client enable
XAE_EMMC_RX16BIT
16 bit Rx client enable
XAE_EMMC_LINKSPD_10
Link Speed mask for 10 Mbit.
Referenced by XAxiEthernet_GetOperatingSpeed.
XAE_EMMC_LINKSPD_100
Link Speed mask for 100 Mbit.
Referenced by XAxiEthernet_GetOperatingSpeed, XAxiEthernet_SetOperatingSpeed.
XAE_EMMC_LINKSPD_1000
Link Speed mask for 1000 Mbit.
Referenced by XAxiEthernet_GetOperatingSpeed, XAxiEthernet_SetOperatingSpeed.
XAE_PHYC_SGMIILINKSPEED_MASK
SGMII link speed mask.
Referenced by XAxiEthernet_GetSgmiiStatus.
XAE_PHYC_RGMIILINKSPEED_MASK
RGMII link speed.
Referenced by XAxiEthernet_GetRgmiiStatus.
XAE_PHYC_RGMIIHD_MASK
RGMII Half-duplex.
Referenced by XAxiEthernet_GetRgmiiStatus.
XAE_PHYC_RGMIILINK_MASK
RGMII link status.
Referenced by XAxiEthernet_GetRgmiiStatus.
XAE_PHYC_RGLINKSPD_10
RGMII link 10 Mbit.
Referenced by XAxiEthernet_GetRgmiiStatus.
XAE_PHYC_RGLINKSPD_100
RGMII link 100 Mbit.
Referenced by XAxiEthernet_GetRgmiiStatus.
XAE_PHYC_RGLINKSPD_1000
RGMII link 1000 Mbit.
Referenced by XAxiEthernet_GetRgmiiStatus.
XAE_PHYC_SGLINKSPD_10
SGMII link 10 Mbit.
Referenced by XAxiEthernet_GetSgmiiStatus.
XAE_PHYC_SGLINKSPD_100
SGMII link 100 Mbit.
Referenced by XAxiEthernet_GetSgmiiStatus.
XAE_PHYC_SGLINKSPD_1000
SGMII link 1000 Mbit.
Referenced by XAxiEthernet_GetSgmiiStatus.
XAE_MDIO_MC_MDIOEN_MASK
MII management enable.
Referenced by XAxiEthernet_PhySetMdioDivisor.
XAE_MDIO_MC_CLOCK_DIVIDE_MAX
Maximum MDIO divisor.
Referenced by XAxiEthernet_PhySetMdioDivisor.
XAE_MDIO_MCR_PHYAD_MASK
Phy Address Mask.
XAE_MDIO_MCR_PHYAD_SHIFT
Phy Address Shift.
XAE_MDIO_MCR_REGAD_MASK
Reg Address Mask.
XAE_MDIO_MCR_REGAD_SHIFT
Reg Address Shift.
XAE_MDIO_MCR_OP_MASK
Operation Code Mask.
XAE_MDIO_MCR_OP_SHIFT
Operation Code Shift.
XAE_MDIO_MCR_OP_READ_MASK
Op Code Read Mask.
XAE_MDIO_MCR_OP_WRITE_MASK
Op Code Write Mask.
XAE_MDIO_MCR_INITIATE_MASK
Ready Mask.
XAE_MDIO_MCR_READY_MASK
Ready Mask.
XAE_MDIO_INT_MIIM_RDY_MASK
MIIM Interrupt.
XAE_UAW1_UNICASTADDR_MASK
Station address bits [47:32] Station address bits [31:0] are stored in register UAW0.
Referenced by XAxiEthernet_SetMacAddress.
XAE_FMI_PM_MASK
Promiscuous mode enable.
Referenced by XAxiEthernet_ClearOptions, XAxiEthernet_SetOptions.
XAE_FMI_IND_MASK
Index Mask.
XAE_BD_RX_USR2_BCAST_MASK
XAE_BD_RX_USR2_IP_MCAST_MASK
XAE_BD_RX_USR2_MCAST_MASK
XAE_MAW1_RNW_MASK
Multicast address table register read enable.
XAE_MAW1_ADDR_MASK
Multicast address table register address.
XAE_MAW1_MULTICADDR_MASK
Multicast address bits [47:32] Multicast address bits [31:0] are stored in register MAW0.
XAE_MAW1_MATADDR_SHIFT_MASK
Number of bits to shift right to align with XAE_MAW1_CAMADDR_MASK.
XAE_SPEED_10_MBPS
Speed of 10 Mbps.
Referenced by AxiEthernetUtilConfigureInternalPhy, AxiEthernetUtilEnterLoopback, XAxiEthernet_GetOperatingSpeed, XAxiEthernet_GetRgmiiStatus, XAxiEthernet_GetSgmiiStatus, XAxiEthernet_SetOperatingSpeed.
XAE_SPEED_100_MBPS
Speed of 100 Mbps.
Referenced by AxiEthernetUtilConfigureInternalPhy, AxiEthernetUtilEnterLoopback, XAxiEthernet_GetOperatingSpeed, XAxiEthernet_GetRgmiiStatus, XAxiEthernet_GetSgmiiStatus, XAxiEthernet_SetOperatingSpeed.
XAE_SPEED_1000_MBPS
Speed of 1000 Mbps.
Referenced by AxiEthernetUtilConfigureInternalPhy, AxiEthernetUtilEnterLoopback, XAxiEthernet_GetOperatingSpeed, XAxiEthernet_GetRgmiiStatus, XAxiEthernet_GetSgmiiStatus, XAxiEthernet_SetOperatingSpeed.
XAE_SPEED_2500_MBPS
Speed of 2500 Mbps.
Referenced by AxiEthernetUtilConfigureInternalPhy, AxiEthernetUtilEnterLoopback, XAxiEthernet_SetOperatingSpeed.
XAE_SOFT_TEMAC_LOW_SPEED
For soft cores with 10/100 Mbps speed.
XAE_SOFT_TEMAC_HIGH_SPEED
For soft cores with 10/100/1000 Mbps speed.
XAE_HARD_TEMAC_TYPE
For hard TEMAC cores used virtex-6.
XAE_PHY_ADDR_LIMIT
Max limit while accessing and searching for available PHYs.
XAE_PHY_REG_NUM_LIMIT
Max register limit in PHY as mandated by the spec.
XAE_RST_DEFAULT_TIMEOUT_VAL
Timeout in us used while checking if the core had come out of reset or for the driver API to wait for before returning a failure case.
Referenced by XAxiEthernet_Reset.
XAE_VLAN_TABL_STRP_FLD_LEN
Strip field length in vlan table used for extended vlan features.
Referenced by XAxiEthernet_SetVidTable.
XAE_VLAN_TABL_TAG_FLD_LEN
Tag field length in vlan table used for extended vlan features.
Referenced by XAxiEthernet_SetVidTable.
XAE_MAX_VLAN_TABL_ENTRY
Max possible number of entries in vlan table used for extended vlan features.
Referenced by XAxiEthernet_GetVidTable, XAxiEthernet_SetVidTable.
XAE_VLAN_TABL_VID_START_OFFSET
VID field start offset in each entry in the VLAN table.
Referenced by XAxiEthernet_GetVidTable, XAxiEthernet_SetVidTable.
XAE_VLAN_TABL_STRP_STRT_OFFSET
Strip field start offset in each entry in the VLAN table.
Referenced by XAxiEthernet_GetVidTable, XAxiEthernet_SetVidTable.
XAE_VLAN_TABL_STRP_ENTRY_MASK
Mask used to extract the the strip field from an entry in VLAN table.
Referenced by XAxiEthernet_GetVidTable.
XAE_VLAN_TABL_TAG_ENTRY_MASK
Mask used to extract the the tag field from an entry in VLAN table.
Referenced by XAxiEthernet_GetVidTable.
typedef struct XAxiEthernet_Config XAxiEthernet_Config
This typedef contains configuration information for a Axi Ethernet device.
typedef struct XAxiEthernet XAxiEthernet
struct XAxiEthernet is the type for Axi Ethernet driver instance data.
The calling code is required to use a unique instance of this structure for every Axi Ethernet device used in the system. A reference to a structure of this type is then passed to the driver API functions.
static void InitHw(XAxiEthernet *InstancePtr)
int XAxiEthernet_CfgInitialize(XAxiEthernet *InstancePtr, XAxiEthernet_Config *CfgPtr, UINTPTR EffectiveAddress)
XAxiEthernet_CfgInitialize initializes an AXI Ethernet device along with the InstancePtr that references it.
The PHY is setup independently from the Ethernet core. Use the MII or whatever other interface may be present for setup. InstancePtr references the memory instance to be associated with the AXI Ethernet core instance upon initialization. CfgPtr references the structure holding the hardware configuration for the Axi Ethernet core to initialize. EffectiveAddress is the processor address used to access the base address of the AXI Ethernet instance. In systems with an MMU and virtual memory, EffectiveAddress is the virtual address mapped to the physical in ConfigPtr->Config.BaseAddress. In systems without an active MMU, EffectiveAddress should be set to the same value as ConfigPtr->Config.BaseAddress. XST_SUCCESS. None.
References XAxiEthernet_Config::AxiDevBaseAddress, XAxiEthernet::AxiDevType, XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet_Config::IntrId, XAxiEthernet_Config::IntrParent, XAxiEthernet::IsReady, XAxiEthernet::PhyMode, XAxiEthernet_Config::PhyType, XAxiEthernet_Get_Phy_Interface, XAxiEthernet_Reset.
Referenced by AxiEthernetExtVlanExample, AxiEthernetFifoIntrExample, AxiEthernetMcastExample, AxiEthernetPingReqExample, AxiEthernetPolledExample, AxiEthernetSgDmaIntrExample, AxiEthernetSgDmaPollExample, main.
int XAxiEthernet_Initialize(XAxiEthernet *InstancePtr, XAxiEthernet_Config *CfgPtr, UINTPTR EffectiveAddress)
XAxiEthernet_Initialize initializes an AXI Ethernet device along with the InstancePtr that references it.
The PHY is setup independently from the Ethernet core. Use the MII or whatever other interface may be present for setup. InstancePtr references the memory instance to be associated with the AXI Ethernet core instance upon initialization. CfgPtr references the structure holding the hardware configuration for the Axi Ethernet core to initialize. EffectiveAddress is the processor address used to access the base address of the AXI Ethernet instance. In systems with an MMU and virtual memory, EffectiveAddress is the virtual address mapped to the physical in ConfigPtr->Config.BaseAddress. In systems without an active MMU, EffectiveAddress should be set to the same value as ConfigPtr->Config.BaseAddress. XST_SUCCESS. When user calls this function he should ensure the hardware is in a quiescent state by resetting all the hardware Configurations.
References XAxiEthernet_Config::AxiDevBaseAddress, XAxiEthernet::AxiDevType, XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet_Config::IntrId, XAxiEthernet_Config::IntrParent, XAxiEthernet::IsReady.
void XAxiEthernet_Start(XAxiEthernet *InstancePtr)
XAxiEthernet_Start starts the Axi Ethernet device as follows:
- Enable transmitter if XAE_TRANSMIT_ENABLE_OPTION is set - Enable receiver if XAE_RECEIVER_ENABLE_OPTION is set InstancePtr is a pointer to the Axi Ethernet instance to be worked on. None. None.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::IsStarted, XAxiEthernet::Options, XAE_RCW1_OFFSET, XAE_RCW1_RX_MASK, XAE_RECEIVER_ENABLE_OPTION, XAE_TC_OFFSET, XAE_TC_TX_MASK, XAE_TRANSMITTER_ENABLE_OPTION, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
Referenced by AxiEthernetMultipleFramesIntrExample, AxiEthernetMultipleFramesPolledExample, AxiEthernetPingReqExample, AxiEthernetSgDmaFullChecksumOffloadExample, AxiEthernetSgDmaIntrCoalescingExample, AxiEthernetSgDmaIntrExtMulticastExample, AxiEthernetSgDmaIntrExtVlanExample, AxiEthernetSgDmaIntrMultiFrameExample, AxiEthernetSgDmaIntrSingleFrameExample, AxiEthernetSgDmaMultiFrameExample, AxiEthernetSgDmaPartialChecksumOffloadExample, AxiEthernetSgDmaSingleFrameExample, AxiEthernetSingleFrameIntrExample, AxiEthernetSingleFrameNonContIntrExample, AxiEthernetSingleFramePolledExample.
void XAxiEthernet_Stop(XAxiEthernet *InstancePtr)
XAxiEthernet_Stop gracefully stops the Axi Ethernet device as follows:
- Disable all interrupts from this device - Disable the receiver XAxiEthernet_Stop does not modify any of the current device options.Since the transmitter is not disabled, frames currently in internal buffers or in process by a DMA engine are allowed to be transmitted. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. None None.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::IsStarted, XAE_IE_OFFSET, XAE_INT_RXRJECT_MASK, XAE_IP_OFFSET, XAE_IS_OFFSET, XAE_RCW1_OFFSET, XAE_RCW1_RX_MASK, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
Referenced by AxiEthernetExtVlanExample, AxiEthernetFifoIntrExample, AxiEthernetMcastExample, AxiEthernetMultipleFramesIntrExample, AxiEthernetMultipleFramesPolledExample, AxiEthernetResetDevice, AxiEthernetSgDmaFullChecksumOffloadExample, AxiEthernetSgDmaIntrCoalescingExample, AxiEthernetSgDmaIntrExample, AxiEthernetSgDmaIntrMultiFrameExample, AxiEthernetSgDmaIntrSingleFrameExample, AxiEthernetSgDmaMultiFrameExample, AxiEthernetSgDmaPartialChecksumOffloadExample, AxiEthernetSgDmaPollExample, AxiEthernetSgDmaSingleFrameExample, AxiEthernetSingleFrameIntrExample, AxiEthernetSingleFrameNonContIntrExample, AxiEthernetSingleFramePolledExample, XAxiEthernet_Reset.
void XAxiEthernet_Reset(XAxiEthernet *InstancePtr)
XAxiEthernet_Reset does not perform a soft reset of the AxiEthernet core.
AxiEthernet hardware is reset by the device connected to the AXI4-Stream interface. This function inserts some delay before proceeding to check for MgtRdy bit. The delay is necessary to be at a safe side. It takes a while for the reset process to complete and for any of the AxiEthernet registers to be accessed. It then checks for MgtRdy bit in IS register to know if AxiEthernet reset is completed or not. Subsequently it calls one more driver function to complete the AxiEthernet hardware initialization. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. It is the responsibility of the user to reset the AxiEthernet hardware before using it. AxiEthernet hardware should be reset through the device connected to the AXI4-Stream interface of AxiEthernet.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::Options, XAE_DEFAULT_OPTIONS, XAE_INT_MGTRDY_MASK, XAE_IS_OFFSET, XAE_RST_DEFAULT_TIMEOUT_VAL, XAxiEthernet_Stop.
Referenced by AxiEthernetResetDevice, XAxiEthernet_CfgInitialize.
int XAxiEthernet_SetMacAddress(XAxiEthernet *InstancePtr, void *AddressPtr)
XAxiEthernet_SetMacAddress sets the MAC address for the Axi Ethernet device, specified by InstancePtr to the MAC address specified by AddressPtr.
The Axi Ethernet device must be stopped before calling this function. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. AddressPtr is a reference to the 6-byte MAC address to set. XST_SUCCESS on successful completion.XST_DEVICE_IS_STARTED if the Axi Ethernet device has not stopped, This routine also supports the extended/new VLAN and multicast mode. The XAE_RAF_NEWFNCENBL_MASK bit dictates which offset will be configured.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::IsStarted, XAE_UAW0_OFFSET, XAE_UAW1_OFFSET, XAE_UAW1_UNICASTADDR_MASK, XAE_UAWL_OFFSET, XAE_UAWU_OFFSET, XAxiEthernet_IsExtFuncCap, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
Referenced by AxiEthernetExtVlanExample, AxiEthernetFifoIntrExample, AxiEthernetMcastExample, AxiEthernetPingReqExample, AxiEthernetPolledExample, AxiEthernetResetDevice, AxiEthernetSgDmaIntrExample, AxiEthernetSgDmaIntrExtMulticastExample, AxiEthernetSgDmaIntrMultiFrameExample, AxiEthernetSgDmaIntrSingleFrameExample, AxiEthernetSgDmaSingleFrameExample.
void XAxiEthernet_GetMacAddress(XAxiEthernet *InstancePtr, void *AddressPtr)
XAxiEthernet_GetMacAddress gets the MAC address for the Axi Ethernet, specified by InstancePtr into the memory buffer specified by AddressPtr.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. AddressPtr references the memory buffer to store the retrieved MAC address. This memory buffer must be at least 6 bytes in length. None. This routine also supports the extended/new VLAN and multicast mode. The XAE_RAF_NEWFNCENBL_MASK bit dictates which offset will be configured.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAE_UAW0_OFFSET, XAE_UAW1_OFFSET, XAE_UAWL_OFFSET, XAE_UAWU_OFFSET, XAxiEthernet_IsExtFuncCap, XAxiEthernet_ReadReg.
Referenced by AxiEthernetResetDevice.
static u32 XAxiEthernet_UpdateDepOptions(XAxiEthernet *InstancePtr)
XAxiEthernet_UpdateDepOption check and update dependent options for new/extended features.
This is a helper function that is meant to be called by XAxiEthernet_SetOptions() and XAxiEthernet_ClearOptions(). InstancePtr is a pointer to the Axi Ethernet instance to be worked on. Dependent options that are required to set/clear per hardware requirement. This helper function collects the dependent OPTION(s) per hardware design. When conflicts arises, extended features have precedence over legacy ones. Two operations to be considered, Adding extended options. If XATE_VLAN_OPTION is enabled and enable one of extended VLAN options, XATE_VLAN_OPTION should be off and configure to hardware. However, axi-ethernet instance Options variable still holds XATE_VLAN_OPTION so when all of the extended feature are removed, XATE_VLAN_OPTION can be effective and configured to hardware.Removing extended options. Remove extended option can not just remove the selected extended option and dependent options. All extended options need to be verified and remained when one or more extended options are enabled. Dependent options are : XAE_VLAN_OPTION,XAE_JUMBO_OPTIONXAE_FCS_INSERT_OPTION,XAE_FCS_STRIP_OPTIONXAE_PROMISC_OPTION.
int XAxiEthernet_SetOptions(XAxiEthernet *InstancePtr, u32 Options)
XAxiEthernet_SetOptions enables the options, Options for the Axi Ethernet, specified by InstancePtr.
Axi Ethernet should be stopped with XAxiEthernet_Stop() before changing options. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. Options is a bitmask of OR'd XAE_*_OPTION values for options to set. Options not specified are not affected. XST_SUCCESS on successful completion.XST_DEVICE_IS_STARTED if the device has not been stopped. See xaxiethernet.h for a description of the available options.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::IsStarted, XAxiEthernet::Options, XAE_BROADCAST_OPTION, XAE_DEFAULT_OPTIONS, XAE_FCC_FCRX_MASK, XAE_FCC_OFFSET, XAE_FCS_INSERT_OPTION, XAE_FCS_STRIP_OPTION, XAE_FLOW_CONTROL_OPTION, XAE_FMI_OFFSET, XAE_FMI_PM_MASK, XAE_JUMBO_OPTION, XAE_LENTYPE_ERR_OPTION, XAE_MULTICAST_OPTION, XAE_PROMISC_OPTION, XAE_RAF_BCSTREJ_MASK, XAE_RAF_EMULTIFLTRENBL_MASK, XAE_RAF_MCSTREJ_MASK, XAE_RAF_NEWFNCENBL_MASK, XAE_RAF_OFFSET, XAE_RAF_RXVSTRPMODE_MASK, XAE_RAF_RXVSTRPMODE_SHIFT, XAE_RAF_RXVTAGMODE_MASK, XAE_RAF_RXVTAGMODE_SHIFT, XAE_RAF_TXVSTRPMODE_MASK, XAE_RAF_TXVSTRPMODE_SHIFT, XAE_RAF_TXVTAGMODE_MASK, XAE_RAF_TXVTAGMODE_SHIFT, XAE_RCW1_FCS_MASK, XAE_RCW1_JUM_MASK, XAE_RCW1_LT_DIS_MASK, XAE_RCW1_OFFSET, XAE_RCW1_RX_MASK, XAE_RCW1_VLAN_MASK, XAE_RECEIVER_ENABLE_OPTION, XAE_TC_FCS_MASK, XAE_TC_JUM_MASK, XAE_TC_OFFSET, XAE_TC_TX_MASK, XAE_TC_VLAN_MASK, XAE_TRANSMITTER_ENABLE_OPTION, XAE_VLAN_OPTION, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
Referenced by AxiEthernetPingReqExample, AxiEthernetResetDevice, AxiEthernetSgDmaFullChecksumOffloadExample, AxiEthernetSgDmaIntrCoalescingExample, AxiEthernetSgDmaIntrExtMulticastExample, AxiEthernetSgDmaIntrExtVlanExample, AxiEthernetSgDmaIntrMultiFrameExample, AxiEthernetSgDmaIntrSingleFrameExample, AxiEthernetSgDmaMultiFrameExample, AxiEthernetSgDmaPartialChecksumOffloadExample, AxiEthernetSgDmaSingleFrameExample.
int XAxiEthernet_ClearOptions(XAxiEthernet *InstancePtr, u32 Options)
XAxiEthernet_ClearOptions clears the options, Options for the Axi Ethernet, specified by InstancePtr.
Axi Ethernet should be stopped with XAxiEthernet_Stop() before changing options. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. Options is a bitmask of OR'd XAE_*_OPTION values for options to clear. Options not specified are not affected. XST_SUCCESS on successful completion.XST_DEVICE_IS_STARTED if the device has not been stopped. See xaxiethernet.h for a description of the available options.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::IsStarted, XAxiEthernet::Options, XAE_BROADCAST_OPTION, XAE_FCC_FCRX_MASK, XAE_FCC_OFFSET, XAE_FCS_INSERT_OPTION, XAE_FCS_STRIP_OPTION, XAE_FLOW_CONTROL_OPTION, XAE_FMI_OFFSET, XAE_FMI_PM_MASK, XAE_JUMBO_OPTION, XAE_LENTYPE_ERR_OPTION, XAE_MULTICAST_OPTION, XAE_PROMISC_OPTION, XAE_RAF_BCSTREJ_MASK, XAE_RAF_EMULTIFLTRENBL_MASK, XAE_RAF_MCSTREJ_MASK, XAE_RAF_NEWFNCENBL_MASK, XAE_RAF_OFFSET, XAE_RAF_RXVSTRPMODE_MASK, XAE_RAF_RXVTAGMODE_MASK, XAE_RAF_TXVSTRPMODE_MASK, XAE_RAF_TXVTAGMODE_MASK, XAE_RCW1_FCS_MASK, XAE_RCW1_JUM_MASK, XAE_RCW1_LT_DIS_MASK, XAE_RCW1_OFFSET, XAE_RCW1_RX_MASK, XAE_RCW1_VLAN_MASK, XAE_RECEIVER_ENABLE_OPTION, XAE_TC_FCS_MASK, XAE_TC_JUM_MASK, XAE_TC_OFFSET, XAE_TC_TX_MASK, XAE_TC_VLAN_MASK, XAE_TRANSMITTER_ENABLE_OPTION, XAE_VLAN_OPTION, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
Referenced by AxiEthernetResetDevice, AxiEthernetSgDmaIntrCoalescingExample, AxiEthernetSgDmaIntrExtMulticastExample.
u32 XAxiEthernet_GetOptions(XAxiEthernet *InstancePtr)
XAxiEthernet_GetOptions returns the current option settings.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. Returns a bitmask of XAE_*_OPTION constants, each bit specifying an option that is currently active. See xaxiethernet.h for a description of the available options.
References XAxiEthernet::IsReady, XAxiEthernet::Options.
Referenced by AxiEthernetResetDevice.
u16 XAxiEthernet_GetOperatingSpeed(XAxiEthernet *InstancePtr)
XAxiEthernet_GetOperatingSpeed gets the current operating link speed.
This may be the value set by XAxiEthernet_SetOperatingSpeed() or a hardware default. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. Returns the link speed in units of megabits per second (10 / 100 / 1000). Can return a value of 0, in case it does not get a valid speed from EMMC. None.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAE_EMMC_LINKSPD_10, XAE_EMMC_LINKSPD_100, XAE_EMMC_LINKSPD_1000, XAE_EMMC_LINKSPEED_MASK, XAE_EMMC_OFFSET, XAE_SPEED_1000_MBPS, XAE_SPEED_100_MBPS, XAE_SPEED_10_MBPS, XAxiEthernet_ReadReg.
int XAxiEthernet_SetOperatingSpeed(XAxiEthernet *InstancePtr, u16 Speed)
XAxiEthernet_SetOperatingSpeed sets the current operating link speed.
For any traffic to be passed, this speed must match the current MII/GMII/SGMII/RGMII link speed. InstancePtr references the Axi Ethernet on which to operate. Speed is the speed to set in units of Mbps. Valid values are 10, 100, or 1000. - XST_SUCCESS on successful setting of speed. XST_FAILURE, if the speed cannot be set for the present hardware configuration. None.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAE_EMMC_LINKSPD_100, XAE_EMMC_LINKSPD_1000, XAE_EMMC_LINKSPEED_MASK, XAE_EMMC_OFFSET, XAE_SPEED_1000_MBPS, XAE_SPEED_100_MBPS, XAE_SPEED_10_MBPS, XAE_SPEED_2500_MBPS, XAxiEthernet_Get_Phy_Interface, XAxiEthernet_GetTemacType, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
Referenced by AxiEthernetExtVlanExample, AxiEthernetFifoIntrExample, AxiEthernetMcastExample, AxiEthernetPolledExample, AxiEthernetSgDmaIntrExample, AxiEthernetSgDmaPollExample.
void XAxiEthernet_SetBadFrmRcvOption(XAxiEthernet *InstancePtr)
XAxiEthernet_SetBadFrmRcvOption is used to enable the bad frame receive option.
If enabled, this option ensures that bad receive frames are allowed and passed to the AXI4-Stream interface as if they are good frames. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. None. None
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAE_RAF_OFFSET, XAE_RAF_RXBADFRMEN_MASK, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
void XAxiEthernet_ClearBadFrmRcvOption(XAxiEthernet *InstancePtr)
XAxiEthernet_ClearBadFrmRcvOption is used to disable the bad frame receive option.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. None. None.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAE_RAF_OFFSET, XAE_RAF_RXBADFRMEN_MASK, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
void XAxiEthernet_DisableControlFrameLenCheck(XAxiEthernet *InstancePtr)
XAxiEthernet_DisableControlFrameLenCheck is used to disable the length check for control frames (pause frames).
This means once the API is called, control frames larger than the minimum frame length are accepted. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. None. None.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAE_RCW1_CL_DIS_MASK, XAE_RCW1_OFFSET, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
void XAxiEthernet_EnableControlFrameLenCheck(XAxiEthernet *InstancePtr)
XAxiEthernet_EnableControlFrameLenCheck is used to enable the length check for control frames (pause frames).
After calling the API, all control frames received will be checked for proper length (less than minimum frame length). By default, upon normal start up, control frame length check is enabled. Hence this API needs to be called only if previously the control frame length check has been disabled by calling the API XAxiEthernet_DisableControlFrameLenCheck. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. None. None.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAE_RCW1_CL_DIS_MASK, XAE_RCW1_OFFSET, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
void XAxiEthernet_PhySetMdioDivisor(XAxiEthernet *InstancePtr, u8 Divisor)
XAxiEthernet_PhySetMdioDivisor sets the MDIO clock divisor in the Axi Ethernet,specified by InstancePtr to the value, Divisor.
This function must be called once after each reset prior to accessing MII PHY registers.From the Virtex-6(TM) and Spartan-6 (TM) Embedded Tri-Mode Ethernet MAC User's Guide, the following equation governs the MDIO clock to the PHY: f[HOSTCLK] f[MDC] = ----------------------- (1 + Divisor) * 2 where f[HOSTCLK] is the bus clock frequency in MHz, and f[MDC] is the MDIO clock frequency in MHz to the PHY. Typically, f[MDC] should not exceed 2.5 MHz. Some PHYs can tolerate faster speeds which means faster access. InstancePtr references the Axi Ethernet instance on which to operate. Divisor is the divisor value to set within the range of 0 to XAE_MDIO_MC_CLK_DVD_MAX. None.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAE_MDIO_MC_CLOCK_DIVIDE_MAX, XAE_MDIO_MC_MDIOEN_MASK, XAE_MDIO_MC_OFFSET, XAxiEthernet_WriteReg.
void XAxiEthernet_PhyRead(XAxiEthernet *InstancePtr, u32 PhyAddress, u32 RegisterNum, u16 *PhyDataPtr)
void XAxiEthernet_PhyWrite(XAxiEthernet *InstancePtr, u32 PhyAddress, u32 RegisterNum, u16 PhyData)
u8 XAxiEthernet_Get_Phy_Interface(XAxiEthernet *InstancePtr)
XAxiEthernet_Get_Phy_Interface returns the type of PHY interface being used by the given instance, specified by InstancePtr.
XAxiEthernet_GetPhysicalInterface returns the type of PHY interface being used by the given instance, specified by InstancePtr. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. The Physical Interface type which is one of XAE_PHY_TYPE_x where x is MII, GMII, RGMII_1_3, RGMII_2_0, SGMII, or 1000BASE_X (defined in xaxiethernet.h). C-style signature: int XAxiEthernet_Get_Phy_Interface(XAxiEthernet *InstancePtr) InstancePtr is a pointer to the Axi Ethernet instance to be worked on. The Physical Interface type which is one of XAE_PHY_TYPE_x where x is MII, GMII, RGMII_1_3, RGMII_2_0, SGMII, or 1000BASE_X (defined in xaxiethernet.h). C-style signature: int XAxiEthernet_GetPhysicalInterface(XAxiEthernet *InstancePtr)
References XAxiEthernet::Config, XAxiEthernet::PhyMode, XAxiEthernet_Config::PhyType.
Referenced by AxiEthernetExtVlanExample, AxiEthernetFifoIntrExample, AxiEthernetMcastExample, AxiEthernetSgDmaIntrExample, AxiEthernetSgDmaPollExample, AxiEthernetUtilEnterLoopback, XAxiEthernet_CfgInitialize, XAxiEthernet_GetRgmiiStatus, XAxiEthernet_GetSgmiiStatus, XAxiEthernet_SetOperatingSpeed.
XAxiEthernet_Config * XAxiEthernet_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
A table contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration table entry corresponding to the given device ID/BaseAddress, or NULL if no match is found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XAxiEthernet_Config::Name.
Referenced by AxiEthernetExtVlanExample, AxiEthernetFifoIntrExample, AxiEthernetMcastExample, AxiEthernetPingReqExample, AxiEthernetPolledExample, AxiEthernetSgDmaIntrExample, AxiEthernetSgDmaPollExample, main.
int XAxiEthernet_SetMacPauseAddress(XAxiEthernet *InstancePtr, void *AddressPtr)
XAxiEthernet_SetMacPauseAddress sets the MAC address used for pause frames to AddressPtr.
AddressPtr will be the address the Axi Ethernet device will recognize as being for pause frames. Pause frames transmitted with XAxiEthernet_SendPausePacket() will also use this address. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. AddressPtr is a pointer to the 6-byte Ethernet address to set. XST_SUCCESS on successful completion.XST_DEVICE_IS_STARTED if the Axi Ethernet device is not stopped. None.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::IsStarted, XAE_RCW0_OFFSET, XAE_RCW1_OFFSET, XAE_RCW1_PAUSEADDR_MASK, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
void XAxiEthernet_GetMacPauseAddress(XAxiEthernet *InstancePtr, void *AddressPtr)
XAxiEthernet_GetMacPauseAddress gets the MAC address used for pause frames for the Axi Ethernet device specified by InstancePtr.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. AddressPtr references the memory buffer to store the retrieved MAC address. This memory buffer must be at least 6 bytes in length. None. None.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAE_RCW0_OFFSET, XAE_RCW1_OFFSET, XAxiEthernet_ReadReg.
int XAxiEthernet_SendPausePacket(XAxiEthernet *InstancePtr, u16 PauseValue)
XAxiEthernet_SendPausePacket sends a pause packet with the value of PauseValue.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. PauseValue is the pause value in units of 512 bit times. XST_SUCCESS on successful completion.XST_DEVICE_IS_STARTED if the Axi Ethernet device is not stopped. None.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::IsStarted, XAE_TPF_OFFSET, XAE_TPF_TPFV_MASK, XAxiEthernet_WriteReg.
int XAxiEthernet_GetSgmiiStatus(XAxiEthernet *InstancePtr, u16 *SpeedPtr)
XAxiEthernet_GetSgmiiStatus get the state of the link when using the SGMII media interface.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. SpeedPtr references the location to store the result, which is the auto negotiated link speed in units of Mbits/sec, either 0, 10, 100, or 1000. XST_SUCCESS on successful completion.XST_NO_FEATURE if the Axi Ethernet device is not using an SGMII interface, Currently SGMII PHY does not support half duplex mode.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAE_PHYC_OFFSET, XAE_PHYC_SGLINKSPD_10, XAE_PHYC_SGLINKSPD_100, XAE_PHYC_SGLINKSPD_1000, XAE_PHYC_SGMIILINKSPEED_MASK, XAE_SPEED_1000_MBPS, XAE_SPEED_100_MBPS, XAE_SPEED_10_MBPS, XAxiEthernet_Get_Phy_Interface, XAxiEthernet_ReadReg.
int XAxiEthernet_GetRgmiiStatus(XAxiEthernet *InstancePtr, u16 *SpeedPtr, int *IsFullDuplexPtr, int *IsLinkUpPtr)
XAxiEthernet_GetRgmiiStatus get the state of the link when using the RGMII media interface.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. SpeedPtr references the location to store the result, which is the auto negotiated link speed in units of Mbits/sec, either 0, 10, 100, or 1000. IsFullDuplexPtr references the value that is set by this function to indicate full duplex operation. IsFullDuplexPtr is set to TRUE when the RGMII link is operating in full duplex mode, otherwise it is set to FALSE. IsLinkUpPtr references the value that is set by this function to indicate the link status.IsLinkUpPtr is set to TRUE when the RGMII link up, otherwise it is set to FALSE. XST_SUCCESS on successful completion.XST_NO_FEATURE if the Axi Ethernet device is not using an RGMII interface, None.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAE_PHYC_OFFSET, XAE_PHYC_RGLINKSPD_10, XAE_PHYC_RGLINKSPD_100, XAE_PHYC_RGLINKSPD_1000, XAE_PHYC_RGMIIHD_MASK, XAE_PHYC_RGMIILINK_MASK, XAE_PHYC_RGMIILINKSPEED_MASK, XAE_SPEED_1000_MBPS, XAE_SPEED_100_MBPS, XAE_SPEED_10_MBPS, XAxiEthernet_Get_Phy_Interface, XAxiEthernet_ReadReg.
int XAxiEthernet_MulticastAdd(XAxiEthernet *InstancePtr, void *AddressPtr, int Entry)
XAxiEthernet_MulticastAdd adds the Ethernet address, AddressPtr to the Axi Ethernet device's multicast filter list, at list index Entry.
The address referenced by AddressPtr may be of any unicast, multicast, or broadcast address form. The hardware for the Axi Ethernet device can hold up to C_Number_of_Table_Entries addresses in this filter list. The device must be stopped to use this function. Once an Ethernet address is programmed, the Axi Ethernet device will begin receiving data sent from that address. The Axi Ethernet hardware does not have a control bit to disable multicast filtering. The only way to prevent the Axi Ethernet device from receiving messages from an Ethernet address in the Multicast Address Table (MAT) is to clear it with XAxiEthernet_MulticastClear(). InstancePtr is a pointer to the Axi Ethernet instance to be worked on. AddressPtr is a pointer to the 6-byte Ethernet address to set. The previous address at the location Entry (if any) is overwritten with the value at AddressPtr. Entry is the hardware storage location to program this address and must be between 0 to (C_Number_of_Table_Entries - 1). XST_SUCCESS on successful completion.XST_DEVICE_IS_STARTED.if the Axi Ethernet device is not stopped. This routine works only with normal multicast filtering feature. A maximum of 4 multicast addresses can be stored in the HW provided multicast table.To use the extended multicast feature, extended multicast filtering must be enabled by using driver API XAxiEthernet_SetOptions with proper option fields set. Once extended multicast filtering is enabled, the APIs XAxiEthernet_[Add|Clear|Get]ExtMulticastGroup() must be used to manage multicast address groups.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::IsStarted, XAE_AF0_OFFSET, XAE_AF1_OFFSET, XAE_FMI_OFFSET, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
void XAxiEthernet_MulticastGet(XAxiEthernet *InstancePtr, void *AddressPtr, int Entry)
XAxiEthernet_MulticastGet gets the Ethernet address stored at index Entry in the Axi Ethernet device's multicast filter list.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. AddressPtr references the memory buffer to store the retrieved Ethernet address. This memory buffer must be at least 6 bytes in length. Entry is the hardware storage location from which to retrieve the address and must be between 0 to (C_Number_of_Table_Entries - 1) None. This routine works only with normal multicast filtering feature. A maximum of 4 multicast addresses can be stored in the HW provided multicast table.To use the extended multicast feature, extended multicast filtering must be enabled by using driver API XAxiEthernet_SetOptions with proper option fields set. Once extended multicast filtering is enabled, the APIs XAxiEthernet_[Add|Clear|Get]ExtMulticastGroup() must be used to manage multicast address groups.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAE_AF0_OFFSET, XAE_AF1_OFFSET, XAE_FMI_OFFSET, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
int XAxiEthernet_MulticastClear(XAxiEthernet *InstancePtr, int Entry)
XAxiEthernet_MulticastClear clears the Ethernet address stored at index Entry in the Axi Ethernet device's multicast filter list.
The device must be stopped to use this function. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. Entry is the HW storage location used when this address was added. It must be between 0 to (C_Number_of_Table_Entries - 1). XST_SUCCESS on successful completion.XST_DEVICE_IS_STARTED.if the Axi Ethernet device is not stopped. This routine works only with normal multicast filtering feature. A maximum of 4 multicast addresses can be stored in the HW provided multicast table.To use the extended multicast feature, extended multicast filtering must be enabled by using driver API XAxiEthernet_SetOptions with proper option fields set. Once extended multicast filtering is enabled, the APIs XAxiEthernet_[Add|Clear|Get]ExtMulticastGroup() must be used to manage multicast address groups.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::IsStarted, XAE_AF0_OFFSET, XAE_AF1_OFFSET, XAE_FMI_OFFSET, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
int XAxiEthernet_SetTpid(XAxiEthernet *InstancePtr, u16 Tpid, u8 Entry)
XAxiEthernet_SetTpid sets the VLAN Tag Protocol Identifier(TPID).
Four values can be configured - 0x8100, 0x9100, 0x9200, 0x88A8. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. Tpid is a hex value to be added to the TPID table. The four values that can be added are 0x8100, 0x9100, 0x9200, 0x88A8. Entry is the hardware storage location to program this address and must be between 0..XAE_TPID_MAX_ENTRIES. XST_SUCCESS on successful completion.XST_DEVICE_IS_STARTED, if the Axi Ethernet device is not stopped.XST_NO_FEATURE if the Axi Ethernet does not enable or have the VLAN tag capability.XST_INVALID_PARAM if Tpid is not one of supported values. The device must be stopped to use this function.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::IsStarted, XAE_TPID0_OFFSET, XAE_TPID1_OFFSET, XAE_TPID_0_MASK, XAE_TPID_1_MASK, XAxiEthernet_IsExtFuncCap, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
Referenced by AxiEthernetSgDmaIntrExtVlanExample.
int XAxiEthernet_ClearTpid(XAxiEthernet *InstancePtr, u8 Entry)
XAxiEthernet_ClearTpid clears the VLAN Tag Protocol Identifier(TPID).
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. Entry is the hardware storage location to program this address and must be between 0..XAE_TPID_MAX_ENTRIES. XST_SUCCESS on successful completion.XST_DEVICE_IS_STARTED if the Axi Ethernet device is not stopped.XST_NO_FEATURE if the Axi Ethernet does not enable or have the VLAN tag capability. The device must be stopped to use this function.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::IsStarted, XAE_TPID0_OFFSET, XAE_TPID1_OFFSET, XAE_TPID_0_MASK, XAE_TPID_1_MASK, XAxiEthernet_IsExtFuncCap, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
void XAxiEthernet_GetTpid(XAxiEthernet *InstancePtr, u16 *TpidPtr, u8 Entry)
XAxiEthernet_GetTpid gets the VLAN Tag Protocol Identifier value (TPID).
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. TpidPtr references the location to store the result. Entry is the hardware storage location to program this address and must be between 0..XAE_TPID_MAX_ENTRIES. None. None.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAE_TPID0_OFFSET, XAE_TPID1_OFFSET, XAE_TPID_0_MASK, XAxiEthernet_ReadReg.
int XAxiEthernet_SetVTagMode(XAxiEthernet *InstancePtr, u32 Mode, int Dir)
XAxiEthernet_SetVTagMode configures the VLAN tagging mode.
Four modes can be configured, XAE_VTAG_NONE for no tagging.XAE_VTAG_ALL to tag all frames.XAE_VTAG_EXISTED to tag already tagged frames.XAE_VTAG_SELECT to tag selected already tagged frames based on VID value. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. Mode is the VLAN tag mode. Value must be between b'00-b'11. Dir must be either XAE_TX or XAE_RX. XST_SUCCESS. on successful completion.XST_DEVICE_IS_STARTED if the Axi Ethernet device is not stopped.XST_NO_FEATURE if the Axi Ethernet does not enable or have the TX VLAN tag capability.XST_INVALID_PARAM if Mode is not one of supported modes. The device must be stopped to use this function. The fourth mode (specified by XAE_VTAG_SELECT) requires a method for specifying which tagged frames should receive an additional VLAN tag. The VLAN translation table 'tag enabled' is referenced. That configuration is handled in XAxiEthernet_SetVidTable().Mode value shifting is handled in this function. No shifting is required to call this function.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::IsStarted, XAE_RAF_OFFSET, XAE_RAF_RXVTAGMODE_MASK, XAE_RAF_RXVTAGMODE_SHIFT, XAE_RAF_TXVTAGMODE_MASK, XAE_RAF_TXVTAGMODE_SHIFT, XAxiEthernet_IsExtFuncCap, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
Referenced by AxiEthernetSgDmaIntrExtVlanExample.
void XAxiEthernet_GetVTagMode(XAxiEthernet *InstancePtr, u8 *ModePtr, int Dir)
XAxiEthernet_GetVTagMode gets VLAN tagging mode.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. ModePtr references the location to store the VLAN tag mode. Value is between b'00-b'11. Dir must be either XAE_TX or XAE_RX. None. The device must be stopped to use this function. Mode value shifting is handled in this function. No shifting is required to call this function.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAE_RAF_OFFSET, XAE_RAF_RXVTAGMODE_MASK, XAE_RAF_RXVTAGMODE_SHIFT, XAE_RAF_TXVTAGMODE_MASK, XAE_RAF_TXVTAGMODE_SHIFT, XAxiEthernet_ReadReg.
int XAxiEthernet_SetVStripMode(XAxiEthernet *InstancePtr, u32 Mode, int Dir)
XAxiEthernet_SetVStripMode configures the VLAN strip mode.
Three modes can be configured : XAE_VSTRP_NONE for no stripping.XAE_VSTRP_ALL to strip one tag from all frames.XAE_VSTRP_SELECT to strip one tag from already selected tagged frames based on VID value. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. Mode is the VLAN strip mode. Value must be b'00, b'01, or b'11. Dir must be either XAE_TX or XAE_RX. XST_SUCCESS on successful completion., returns XST_SUCCESS.XST_DEVICE_IS_STARTED if the Axi Ethernet device is not stopped.XST_NO_FEATURE if the Axi Ethernet does not enable or have the TX VLAN strip capability.XST_INVALID_PARAM if Mode is not one of supported modes. The device must be stopped to use this function. The third mode (specified by XAE_VSTRP_SELECT) requires a method for specifying which tagged frames should be stripped. The VLAN translation table 'stripped enabled' is referenced. That configuration is handled in XAxiEthernet_SetVidTable().Mode value shifting is handled in this function. No shifting is required to call this function.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::IsStarted, XAE_RAF_OFFSET, XAE_RAF_RXVSTRPMODE_MASK, XAE_RAF_RXVSTRPMODE_SHIFT, XAE_RAF_TXVSTRPMODE_MASK, XAE_RAF_TXVSTRPMODE_SHIFT, XAxiEthernet_IsExtFuncCap, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
Referenced by AxiEthernetSgDmaIntrExtVlanExample.
void XAxiEthernet_GetVStripMode(XAxiEthernet *InstancePtr, u8 *ModePtr, int Dir)
XAxiEthernet_GetVStripMode gets the VLAN stripping mode.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. ModePtr references the location to store the VLAN strip mode returned by this function. Value is b'00, b'01 or b'11. Refer XAE_VTSRAP_* in xaxiethernet.h file for the details. Dir must be either XAE_TX or XAE_RX. None. Mode value shifting is handled in this function. No shifting is required to call this function.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAE_RAF_OFFSET, XAE_RAF_RXVSTRPMODE_MASK, XAE_RAF_RXVSTRPMODE_SHIFT, XAE_RAF_TXVSTRPMODE_MASK, XAE_RAF_TXVSTRPMODE_SHIFT, XAxiEthernet_ReadReg.
int XAxiEthernet_SetVTagValue(XAxiEthernet *InstancePtr, u32 VTagValue, int Dir)
XAxiEthernet_SetVTagValue configures the VLAN tagging value.
The device must be stopped to use this function. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. VTagValue is the VLAN tag value to be configured. A 32bit value. TPID, one of the following 16 bit values, 0x8100, 0x88a8, 0x9100, 0x9200. Priority, 3 bits CFI, 1 bit VID, 12 bits Dir must be either XAE_TX or XAE_RX. XST_SUCCESS on successful completion, returns .XST_DEVICE_IS_STARTED if the Axi Ethernet device is not stopped.XST_NO_FEATURE if the Axi Ethernet does not enable/have TX VLAN tag capability.XST_INVALID_PARAM, if the TPID is not one the four supported values. The four supported TPID values are 0x8100, 0x88a8, 0x9100, 0x9200. XAxiEthernet_SetVTagValue performs verification on TPID only.Ethernet VLAN frames' VLAN type/length(2B) and tag control information(2B). Bit layout : bbbb bbbb bbbb bbbb bbb b bbbb bbbb bbbb \ / | | \ VID (12b) / \ / | CFI bit (1b) TPID (16b) priority bit (3b)
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::IsStarted, XAE_RTAG_OFFSET, XAE_TTAG_OFFSET, XAxiEthernet_IsExtFuncCap, XAxiEthernet_WriteReg.
Referenced by AxiEthernetSgDmaIntrExtVlanExample.
void XAxiEthernet_GetVTagValue(XAxiEthernet *InstancePtr, u32 *VTagValuePtr, int Dir)
XAxiEthernet_GetVTagValue gets the configured VLAN tagging value.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. VTagValuePtr references the location to store the result. Format is TPID, one of the following 16 bit values, 0x8100, 0x88a8, 0x9100, 0x9200. Priority, 3 bits CFI, 1 bit VID, 12 bits Dir must be either XAE_TX or XAE_RX. None. Ethernet VLAN frames' VLAN type/length(2B) and tag control information(2B). Bit layout : bbbb bbbb bbbb bbbb bbb b bbbb bbbb bbbb \ / | | \ VID (12b) / \ / | CFI bit (1b) TPID (16b) priority bit (3b)
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAE_RTAG_OFFSET, XAE_TTAG_OFFSET, XAxiEthernet_ReadReg.
int XAxiEthernet_SetVidTable(XAxiEthernet *InstancePtr, u32 Entry, u32 Vid, u8 Strip, u8 Tag, int Dir)
XAxiEthernet_SetVidTable sets VID table includes new VLAN ID, strip and tag enable bits.
The device must be stopped to use this function. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. Entry is the hardware storage location/index to program updated VID value, strip, or tag value. The value must be between 0..0xFFF. Vid is updated/translated Vid value to be programmed. Strip is strip enable indication for Vid. Tag is tag enable indication for Vid. Dir must be either XAE_TX or XAE_RX. XST_SUCCESS on successful completion.XST_DEVICE_IS_STARTED if the Axi Ethernet device is not stopped.XST_NO_FEATURE if the Axi Ethernet does not enable/have extended functionalities. The hardware requires the table to be 'indexed' with Entry and must be 0x000..0xFFF.Bits layout is bbbb bbbb bbbb b b VLAN ID (12b), | | | VLAN double tag enable bit VLAN strip enable bitTo disable translation indexed by Entry, Set Vid = Entry.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::IsStarted, XAE_MAX_VLAN_TABL_ENTRY, XAE_RX_VLAN_DATA_OFFSET, XAE_TX_VLAN_DATA_OFFSET, XAE_VLAN_TABL_STRP_FLD_LEN, XAE_VLAN_TABL_STRP_STRT_OFFSET, XAE_VLAN_TABL_TAG_FLD_LEN, XAE_VLAN_TABL_VID_START_OFFSET, XAxiEthernet_IsExtFuncCap, XAxiEthernet_WriteReg.
Referenced by AxiEthernetSgDmaIntrExtVlanExample.
void XAxiEthernet_GetVidTable(XAxiEthernet *InstancePtr, u32 Entry, u32 *VidPtr, u8 *StripPtr, u8 *TagPtr, int Dir)
XAxiEthernet_GetVidTable gets VID table content includes new VLAN ID, strip and tag enable bits.
The device must be stopped to use this function. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. Entry is the hardware storage location/index to program updated VID value, strip, or tag value. The value must be between 0..0xFFF. VidPtr references the location to store the result. This function stores the Vid value indexed by Entry into this location. StripPtr references the location to store the result. This function stores the strip enable bit value indexed by Entry into this location. TagPtr references the location to store the result. This function stores the tag enable bit value indexed by Entry into this location. Dir must be either XAE_TX or XAE_RX. None. The hardware requires the table to be 'indexed' with Entry and must be 0x000..0xFFF.Bits layout is bbbb bbbb bbbb b b VLAN ID (12b), | | | VLAN double tag enable bit VLAN strip enable bit
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAE_MAX_VLAN_TABL_ENTRY, XAE_RX_VLAN_DATA_OFFSET, XAE_TX_VLAN_DATA_OFFSET, XAE_VLAN_TABL_STRP_ENTRY_MASK, XAE_VLAN_TABL_STRP_STRT_OFFSET, XAE_VLAN_TABL_TAG_ENTRY_MASK, XAE_VLAN_TABL_VID_START_OFFSET, XAxiEthernet_ReadReg.
int XAxiEthernet_AddExtMulticastGroup(XAxiEthernet *InstancePtr, void *AddressPtr)
XAxiEthernet_AddExtMulticastGroup adds an entry to the multicast Ethernet address table.
The new entry, represents a group of MAC addresses based on the contents of AddressPtr. AddressPtr is one member of the MAC address set in the newly added entry.The device must be stopped to use this function. Once an Ethernet address is programmed, the Axi Ethernet device will begin receiving data sent from that address. The Axi Ethernet hardware does not have a control bit to disable multicast filtering. The only way to prevent the Axi Ethernet device from receiving messages from an Ethernet address in the multicast table is to clear it with XAxiEthernet_ClearExtMulticastGroup(). InstancePtr is a pointer to the Axi Ethernet instance to be worked on. AddressPtr is a pointer to the 6-byte Ethernet address to add. XST_SUCCESS.on successful completion.XST_DEVICE_IS_STARTED if the Axi Ethernet device is not stopped.XST_INVALID_PARAM if the input MAC address is not between 01:00:5E:00:00:00 and 01:00:5E:7F:FF:FF per RFC1112. This routine consider all 2**23 possible multicast Ethernet addresses to be 8Mx1 bit or 1M bytes memory area. All defined multicast addresses are from 01.00.5E.00.00.00 to 01.00.5E.7F.FF.FF The most significant 25 bit out of 48 bit are static, so they will not be part of calculation.The hardware requires to 'index' with bit 22-8, 15 bits in total. The least significant byte/8 bits are considered a group.This API operates at a group (256 MAC addresses) for hardware to do the first layer address filtering. It is user's responsibility to provision this table appropriately.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::IsStarted, XAE_MCAST_TABLE_OFFSET, XAxiEthernet_IsExtFuncCap, XAxiEthernet_IsExtMcastEnable, XAxiEthernet_WriteReg.
Referenced by AxiEthernetSgDmaIntrExtMulticastExample.
int XAxiEthernet_ClearExtMulticastGroup(XAxiEthernet *InstancePtr, void *AddressPtr)
XAxiEthernet_ClearExtMulticastGroup clears input multicast Ethernet address group from table.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. AddressPtr is a pointer to the 6-byte Ethernet address to clear. XST_SUCCESS on successful completion, returns XST_SUCCESS.XST_DEVICE_IS_STARTED if the Axi Ethernet device is not stoppedXST_INVALID_PARAM if input MAC address is not between 01:00:5E:00:00:00 and 01:00:5E:7F:FF:FF per RFC1112. Please reference XAxiEthernet_AddExtMulticastGroup for multicast address index and bit value calculation.In table, hardware requires to 'index' with bit 22-8, 15 bits in total. The least significant byte/8 bits are considered a group.There is a scenario that might introduce issues: When multicast tables are programmed initially to accept 01:00:5E:12:34:56 and 01:00:5E:12:34:78 but later decided to clear 01:00:5E:12:34:78. Without validating all possible combinations at the indexed entry, multicast table might be misconfigured and drop frames.When clearing a multicast address table entry, note that a whole group of mac addresses will no longer be accepted - this because an entry in the table represents multiple(256) mac addresses.The device must be stopped to use this function. This API operates at a group (256 MAC addresses) level for hardware to perform the first layer address filtering. It is user's responsibility to provision this table appropriately.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::IsStarted, XAE_MCAST_TABLE_OFFSET, XAxiEthernet_IsExtFuncCap, XAxiEthernet_IsExtMcastEnable, XAxiEthernet_WriteReg.
int XAxiEthernet_GetExtMulticastGroup(XAxiEthernet *InstancePtr, void *AddressPtr)
XAxiEthernet_GetExtMulticastGroup returns whether the given Ethernet address group is stored in the table.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. AddressPtr is a pointer to the 6-byte Ethernet address. TRUE if it is an acceptable multicast MAC address and the group is present in the table.FALSE if it is not a valid multicast MAC address or the group was not found in the table. In the table, hardware requires to 'index' with bit 22-8, 15 bits in total. The least significant byte/8 bits are considered a group. This API operates at a group (256 MAC addresses) level.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAE_MCAST_TABLE_OFFSET, XAxiEthernet_ReadReg.
Referenced by AxiEthernetSgDmaIntrExtMulticastExample.
void XAxiEthernet_DumpExtMulticastGroup(XAxiEthernet *InstancePtr)
XAxiEthernet_DumpExtMulticastGroup dumps ALL provisioned acceptable multicast MAC in the Axi Ethernet device's multicast table.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. None. Hardware requires to 'index' with bit 22-8, 15 bits in total. The least significant byte/8 bits are considered a set.This API operates at a set (256 MAC addresses) level.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAE_MCAST_TABLE_OFFSET, XAxiEthernet_ReadReg.
xdbg_stmnt(extern int indent_on)
XAXIETHERNET_H
XAE_MDIO_DIV_DFT
Default MDIO clock divisor.
XAE_MAC_ADDR_SIZE
XAE_MTU
XAE_JUMBO_MTU
XAE_HDR_SIZE
XAE_HDR_VLAN_SIZE
XAE_TRL_SIZE
XAE_MAX_FRAME_SIZE
XAE_MAX_VLAN_FRAME_SIZE
XAE_MAX_JUMBO_FRAME_SIZE
XAE_PHY_TYPE_RGMII
XAE_PHY_TYPE_RGMII_ID
XAE_PHY_TYPE_RGMII_RXID
XAE_PHY_TYPE_RGMII_TXID
XAE_PHY_INTERFACE_MODE_NA
XAE_PHY_TYPE_MII
XAE_PHY_TYPE_GMII
XAE_PHY_TYPE_SGMII
XAE_PHY_TYPE_RGMII_1_3
XAE_PHY_TYPE_RGMII_2_0
XAE_PHY_TYPE_1000BASE_X
XAE_TPID_MAX_ENTRIES
XAE_VTAG_NONE
XAE_VTAG_ALL
XAE_VTAG_EXISTED
XAE_VTAG_SELECT
XAE_DEFAULT_TXVTAG_MODE
XAE_DEFAULT_RXVTAG_MODE
XAE_VSTRP_NONE
XAE_VSTRP_ALL
XAE_VSTRP_SELECT
XAE_DEFAULT_TXVSTRP_MODE
XAE_DEFAULT_RXVSTRP_MODE
XAE_RX
XAE_TX
XAE_SOFT_TEMAC_10_100_MBPS
XAE_SOFT_TEMAC_10_100_1000_MBPS
XAE_HARD_TEMC
XPAR_AXI_FIFO
XPAR_AXI_DMA
XPAR_AXI_MCDMA
XAE_AXIDEVTYPE_MASK
XAE_AXIBASEADDR_MASK
XAxiEthernet_IsStarted
XAxiEthernet_IsStarted reports if the device is in the started or stopped state.
To be in the started state, the calling code must have made a successful call to XAxiEthernet_Start. To be in the stopped state, XAxiEthernet_Stop or XAxiEthernet_CfgInitialize function must have been called. InstancePtr is a pointer to the of Axi Ethernet instance to be worked on. TRUE if the device has been started.FALSE.if the device has not been started C-style signature: u32 XAxiEthernet_IsStarted(XAxiEthernet *InstancePtr)
XAxiEthernet_IsDma
XAxiEthernet_IsDma reports if the device is currently connected to DMA.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. TRUE if the Axi Ethernet device is connected DMA.FALSE.if the Axi Ethernet device is NOT connected to DMA C-style signature: u32 XAxiEthernet_IsDma(XAxiEthernet *InstancePtr)
XAxiEthernet_IsFifo
XAxiEthernet_IsFifo reports if the device is currently connected to a fifo core.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. TRUE if the Axi Ethernet device is connected to a fifoFALSE if the Axi Ethernet device is NOT connected to a fifo. C-style signature: u32 XAxiEthernet_IsFifo(XAxiEthernet *InstancePtr)
XAxiEthernet_IsMcDma
XAxiEthernet_IsMcDma reports if the device is currently connected to MCDMA.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. TRUE if the Axi Ethernet device is connected MCDMA.FALSE.if the Axi Ethernet device is NOT connected to MCDMA C-style signature: u32 XAxiEthernet_IsMcDma(XAxiEthernet *InstancePtr)
XAxiEthernet_AxiDevBaseAddress
XAxiEthernet_AxiDevBaseAddress reports the base address of the core connected to the Axi Ethernet's Axi4 Stream interface.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. The base address of the core connected to the Axi Ethernet's streaming interface. C-style signature: u32 XAxiEthernet_AxiDevBaseAddress(XAxiEthernet *InstancePtr)
XAxiEthernet_IsRecvFrameDropped
XAxiEthernet_IsRecvFrameDropped determines if the device thinks it has dropped a receive frame.
The device interrupt status register is read to determine this. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. TRUE if a frame has been droppedFALSE if a frame has NOT been dropped. C-style signature: u32 XAxiEthernet_IsRecvFrameDropped(XAxiEthernet *InstancePtr)
XAxiEthernet_IsRxPartialCsum
XAxiEthernet_IsRxPartialCsum determines if the device is configured with partial checksum offloading on the receive channel.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. TRUE if the device is configured with partial checksum offloading on the receive channel.FALSE.if the device is not configured with partial checksum offloading on the receive side. C-style signature: u32 XAxiEthernet_IsRxPartialCsum(XAxiEthernet *InstancePtr)
Referenced by AxiEthernetSgDmaIntrExample, AxiEthernetSgDmaPartialChecksumOffloadExample, AxiEthernetSgDmaPollExample.
XAxiEthernet_IsTxPartialCsum
XAxiEthernet_IsTxPartialCsum determines if the device is configured with partial checksum offloading on the transmit channel.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. TRUE if the device is configured with partial checksum offloading on the transmit side.FALSE.if the device is not configured with partial checksum offloading on the transmit side. C-style signature: u32 XAxiEthernet_IsTxPartialCsum(XAxiEthernet *InstancePtr)
Referenced by AxiEthernetSgDmaIntrExample, AxiEthernetSgDmaPartialChecksumOffloadExample, AxiEthernetSgDmaPollExample.
XAxiEthernet_IsRxFullCsum
XAxiEthernet_IsRxFullCsum determines if the device is configured with full checksum offloading on the receive channel.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. TRUE if the device is configured with full checksum offloading on the receive channel.FALSE.if the device is not configured with full checksum offloading on the receive side. C-style signature: u32 XAxiEthernet_IsRxFullCsum(XAxiEthernet *InstancePtr)
Referenced by AxiEthernetSgDmaIntrExample, AxiEthernetSgDmaPollExample.
XAxiEthernet_IsTxFullCsum
XAxiEthernet_IsTxFullCsum determines if the device is configured with full checksum offloading on the transmit channel.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. TRUE if the device is configured with full checksum offloading on the transmit side.FALSE.if the device is not configured with full checksum offloading on the transmit side. C-style signature: u32 XAxiEthernet_IsTxFullCsum(XAxiEthernet *InstancePtr)
Referenced by AxiEthernetSgDmaIntrExample, AxiEthernetSgDmaPollExample.
XAxiEthernet_GetIntStatus
XAxiEthernet_GetIntStatus returns a bit mask of the interrupt status register (ISR).
XAxiEthernet_GetIntStatus can be used to query the status without having to have interrupts enabled. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. Returns a bit mask of the interrupt status conditions. The mask will be a set of bit wise or'd values from the XAE_INT_*_MASK definitions in xaxitemac_hw.h file. C-style signature: u32 XAxiEthernet_GetIntStatus(XAxiEthernet *InstancePtr)
Referenced by AxiEthernetPollForRxStatus.
XAxiEthernet_IntEnable
XAxiEthernet_IntEnable enables the interrupts specified in Mask.
The corresponding interrupt for each bit set to 1 in Mask, will be enabled. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. Mask contains a bit mask of the interrupts to enable. The mask can be formed using a set of bit wise or'd values from the XAE_INT_*_MASK definitions in xaxitemac_hw.h file. None. C-style signature: void XAxiEthernet_IntEnable(XAxiEthernet *InstancePtr, u32 Mask)
Referenced by AxiEthernetSgDmaFullChecksumOffloadExample, AxiEthernetSgDmaIntrExtMulticastExample, AxiEthernetSgDmaIntrExtVlanExample, AxiEthernetSgDmaIntrSingleFrameExample, AxiEthernetSgDmaPartialChecksumOffloadExample, AxiEthernetSingleFrameIntrExample.
XAxiEthernet_IntDisable
XAxiEthernet_IntDisable disables the interrupts specified in Mask.
The corresponding interrupt for each bit set to 1 in Mask, will be disabled. In other words, XAxiEthernet_IntDisable uses the "set a bit to clear it" scheme. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. Mask contains a bit mask of the interrupts to disable. The mask can be formed using a set of bit wise or'd values from the XAE_INT_*_MASK definitions in xaxitemac_hw.h file None. C-style signature: void XAxiEthernet_IntDisable(XAxiEthernet *InstancePtr, u32 Mask)
XAxiEthernet_IntPending
XAxiEthernet_IntPending returns a bit mask of the pending interrupts.
Each bit set to 1 in the return value represents a pending interrupt. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. Returns a bit mask of the interrupts that are pending. The mask will be a set of bit wise or'd values from the XAE_INT_*_MASK definitions in xaxitemac_hw.h file. C-style signature: u32 XAxiEthernet_IntPending(XAxiEthernet *InstancePtr)
Referenced by AxiEthernetSgDmaIntrExample.
XAxiEthernet_IntClear
XAxiEthernet_IntClear clears pending interrupts specified in Mask.
The corresponding pending interrupt for each bit set to 1 in Mask, will be cleared. In other words, XAxiEthernet_IntClear uses the "set a bit to clear it" scheme. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. Mask contains a bit mask of the pending interrupts to clear. The mask can be formed using a set of bit wise or'd values from the XAE_INT_*_MASK definitions in xaxitemac_hw.h file. C-style signature: void XAxiEthernet_IntClear(XAxiEthernet *InstancePtr, u32 Mask)
Referenced by AxiEthernetSgDmaIntrExample.
XAxiEthernet_IsExtFuncCap
XAxiEthernet_IsExtFuncCap determines if the device is capable of the new/extend VLAN and multicast features.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. TRUE if the device is capable and configured with extended Multicast and VLAN Tagging/Stripping and Translation.TRUE if the device is NOT capable and NOT configured with extended Multicast and VLAN Tagging/Stripping and Translation. C-style signature: u32 XAxiEthernet_IsExtFuncCap(XAxiEthernet *InstancePtr)
Referenced by XAxiEthernet_AddExtMulticastGroup, XAxiEthernet_ClearExtMulticastGroup, XAxiEthernet_ClearTpid, XAxiEthernet_GetMacAddress, XAxiEthernet_SetMacAddress, XAxiEthernet_SetTpid, XAxiEthernet_SetVidTable, XAxiEthernet_SetVStripMode, XAxiEthernet_SetVTagMode, XAxiEthernet_SetVTagValue.
XAxiEthernet_IsExtMcastEnable
XAxiEthernet_IsExtMcastEnable determines if the extended multicast features is enabled.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. TRUE if the extended multicast features are enabled.FALSE if the extended multicast features are NOT enabled : This function indicates when extended Multicast is enabled in HW, extended multicast mode in wrapper can be tested. C-style signature: u32 XAxiEthernet_IsExtMcastEnable(XAxiEthernet *InstancePtr)
Referenced by XAxiEthernet_AddExtMulticastGroup, XAxiEthernet_ClearExtMulticastGroup.
XAxiEthernet_IsExtMcast
XAxiEthernet_IsExtMcast determines if the device is built with new/extended multicast features.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. TRUE if the device is built with extended multicast features.FALSE if the device is not built with the extended multicast features. This function indicates when hardware is built with extended Multicast feature. C-style signature: u32 XAxiEthernet_IsExtMcast(XAxiEthernet *InstancePtr)
Referenced by AxiEthernetMcastExample, AxiEthernetSgDmaIntrExtMulticastExample.
XAxiEthernet_IsTxVlanStrp
XAxiEthernet_IsTxVlanStrp determines if the device is configured with transmit VLAN stripping on the transmit channel.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. TRUE if the device is configured with VLAN stripping on the Transmit channel.FALSE if the device is NOT configured with VLAN stripping on the Transmit channel. C-style signature: u32 XAxiEthernet_IsTxVlanStrp(XAxiEthernet *InstancePtr)
Referenced by AxiEthernetExtVlanExample, AxiEthernetSgDmaIntrExample, AxiEthernetSgDmaIntrExtVlanExample, AxiEthernetSgDmaPollExample.
XAxiEthernet_IsRxVlanStrp
XAxiEthernet_IsRxVlanStrp determines if the device is configured with receive VLAN stripping on the receive channel.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. TRUE if the device is configured with VLAN stripping on the Receive channel.FALSE if the device is NOT configured with VLAN stripping on the Receive channel. C-style signature: u32 XAxiEthernet_IsRxVlanTran(XAxiEthernet *InstancePtr)
Referenced by AxiEthernetExtVlanExample, AxiEthernetSgDmaIntrExample, AxiEthernetSgDmaIntrExtVlanExample, AxiEthernetSgDmaPollExample.
XAxiEthernet_IsTxVlanTran
XAxiEthernet_IsTxVlanTran determines if the device is configured with transmit VLAN translation on the transmit channel.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. TRUE if the device is configured with VLAN translation on the Transmit channel.FALSE if the device is NOT configured with VLAN translation on the Transmit channel. C-style signature: u32 XAxiEthernet_IsTxVlanTran(XAxiEthernet *InstancePtr)
Referenced by AxiEthernetExtVlanExample, AxiEthernetSgDmaIntrExample, AxiEthernetSgDmaIntrExtVlanExample, AxiEthernetSgDmaPollExample.
XAxiEthernet_IsRxVlanTran
XAxiEthernet_IsRxVlanTran determines if the device is configured with receive VLAN translation on the receive channel.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. TRUE if the device is configured with VLAN translation on the Receive channel.FALSE if the device is NOT configured with VLAN translation on the Receive channel. C-style signature: u32 XAxiEthernet_IsRxVlanTran(XAxiEthernet *InstancePtr)
Referenced by AxiEthernetExtVlanExample, AxiEthernetSgDmaIntrExample, AxiEthernetSgDmaIntrExtVlanExample, AxiEthernetSgDmaPollExample.
XAxiEthernet_IsTxVlanTag
XAxiEthernet_IsTxVlanTag determines if the device is configured with transmit VLAN tagging on the transmit channel.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. TRUE if the device is configured with VLAN tagging on the Transmit channel.FALSE if the device is NOT configured with VLAN tagging on the Transmit channel. C-style signature: u32 XAxiEthernet_IsTxVlanTag(XAxiEthernet *InstancePtr)
Referenced by AxiEthernetExtVlanExample, AxiEthernetSgDmaIntrExample, AxiEthernetSgDmaIntrExtVlanExample, AxiEthernetSgDmaPollExample.
XAxiEthernet_IsRxVlanTag
XAxiEthernet_IsRxVlanTag determines if the device is configured with receive VLAN tagging on the receive channel.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. TRUE if the device is configured with VLAN tagging on the Receive channel.FALSE if the device is NOT configured with VLAN tagging on the Receive channel. C-style signature: u32 XAxiEthernet_IsRxVlanTag(XAxiEthernet *InstancePtr)
Referenced by AxiEthernetExtVlanExample, AxiEthernetSgDmaIntrExample, AxiEthernetSgDmaIntrExtVlanExample, AxiEthernetSgDmaPollExample.
XAxiEthernet_GetTemacType
XAxiEthernet_GetTemacType returns the Axi Ethernet type of the core.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. Returns the values of TemacType, which can be XAE_SOFT_TEMAC_10_100_MBPS (0) for Soft Temac Core with speed 10/100 Mbps. XAE_SOFT_TEMAC_10_100_1000_MBPS (1) for Soft Temac core with speed 10/100/1000 Mbps XAE_HARD_TEMC (2) for Hard Temac Core for Virtex-6 C-style signature: u32 XAxiEthernet_GetTemacType(XAxiEthernet *InstancePtr)
Referenced by XAxiEthernet_SetOperatingSpeed.
XAxiEthernet_IsAvbConfigured
XAxiEthernet_IsAvbConfigured returns determines if Ethernet AVB.is configured in the hardware or not.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. TRUE if the device is configured with Ethernet AVB.FALSE if the device is NOT configured with Ethernet AVB. C-style signature: u32 XAxiEthernet_IsAvbConfigured(XAxiEthernet *InstancePtr)
XAxiEthernet_IsSgmiiOverLvdsEnabled
XAxiEthernet_IsSgmiiOverLvdsEnabled determines if SGMII over LVDS is enabled in the hardware or not.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. TRUE if the device is configured with SGMII over LVDS.FALSE if the device is NOT configured with SGMII over LVDS. C-style signature: u32 XAxiEthernet_IsSgmiiOverLvdsEnabled(XAxiEthernet *InstancePtr)
XAxiEthernet_IsStatsConfigured
XAxiEthernet_IsStatsConfigured returns determines if Statistics gathering.
is configured in the hardware or not. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. TRUE if the device is configured with statistics gathering.FALSE if the device is NOT configured with statistics gathering. C-style signature: u32 XAxiEthernet_IsStatsConfigured(XAxiEthernet *InstancePtr)
XAXIETHERNET_HW_H
XAxiEthernet_indent
XAxiEthernet_reg_name
XAxiEthernet_print_reg_o
XAxiEthernet_print_reg_i
XAxiEthernet_ReadReg
XAxiEthernet_ReadReg returns the value read from the register specified by RegOffset.
BaseAddress is the base address of the Axi Ethernet device. RegOffset is the offset of the register to be read. Returns the 32-bit value of the register. C-style signature: u32 XAxiEthernet_ReadReg(u32 BaseAddress, u32 RegOffset)
Referenced by XAxiEthernet_ClearBadFrmRcvOption, XAxiEthernet_ClearOptions, XAxiEthernet_ClearTpid, XAxiEthernet_DisableControlFrameLenCheck, XAxiEthernet_DumpExtMulticastGroup, XAxiEthernet_EnableControlFrameLenCheck, XAxiEthernet_GetExtMulticastGroup, XAxiEthernet_GetMacAddress, XAxiEthernet_GetMacPauseAddress, XAxiEthernet_GetOperatingSpeed, XAxiEthernet_GetRgmiiStatus, XAxiEthernet_GetSgmiiStatus, XAxiEthernet_GetTpid, XAxiEthernet_GetVidTable, XAxiEthernet_GetVStripMode, XAxiEthernet_GetVTagMode, XAxiEthernet_GetVTagValue, XAxiEthernet_MulticastAdd, XAxiEthernet_MulticastClear, XAxiEthernet_MulticastGet, XAxiEthernet_SetBadFrmRcvOption, XAxiEthernet_SetMacAddress, XAxiEthernet_SetMacPauseAddress, XAxiEthernet_SetOperatingSpeed, XAxiEthernet_SetOptions, XAxiEthernet_SetTpid, XAxiEthernet_SetVStripMode, XAxiEthernet_SetVTagMode, XAxiEthernet_Start, XAxiEthernet_Stop.
XAxiEthernet_WriteReg
XAxiEthernet_WriteReg, writes Data to the register specified by RegOffset.
BaseAddress is the base address of the Axi Ethernet device. RegOffset is the offset of the register to be written. Data is the 32-bit value to write to the register. None. C-style signature: void XAxiEthernet_WriteReg(u32 BaseAddress, u32 RegOffset, u32 Data)
Referenced by XAxiEthernet_AddExtMulticastGroup, XAxiEthernet_ClearBadFrmRcvOption, XAxiEthernet_ClearExtMulticastGroup, XAxiEthernet_ClearOptions, XAxiEthernet_ClearTpid, XAxiEthernet_DisableControlFrameLenCheck, XAxiEthernet_EnableControlFrameLenCheck, XAxiEthernet_MulticastAdd, XAxiEthernet_MulticastClear, XAxiEthernet_MulticastGet, XAxiEthernet_PhySetMdioDivisor, XAxiEthernet_SendPausePacket, XAxiEthernet_SetBadFrmRcvOption, XAxiEthernet_SetMacAddress, XAxiEthernet_SetMacPauseAddress, XAxiEthernet_SetOperatingSpeed, XAxiEthernet_SetOptions, XAxiEthernet_SetTpid, XAxiEthernet_SetVidTable, XAxiEthernet_SetVStripMode, XAxiEthernet_SetVTagMode, XAxiEthernet_SetVTagValue, XAxiEthernet_Start, XAxiEthernet_Stop.