xavb_ptp_bmca.c
void XAvb_DecodeTxAnnounceFrame(XAvb *InstancePtr)
A New Announce Packet has been written to this device to transmit.
We need to decode it and rerun the Best Master Clock Algorithm (BMCA) InstancePtr is a pointer to the XAvb instance to be worked on None. But an updated True/False decision as to whether this device should operate as a clock master or a slave is written into the CurrentBmc data structure. None.
References XAvb_Config::BaseAddress, XAvb_ClockQuality::clockClass, XAvb_ClockIdentity::ClockIdentityLower, XAvb_ClockIdentity::ClockIdentityUpper, XAvb_BmcData::ClockQuality, XAvb::Config, XAvb::CurrentBmc, XAvb_BmcData::GrandmasterIdentity, XAvb_BmcData::GrandmasterPriority1, XAvb_BmcData::GrandmasterPriority2, XAvb_BmcData::IAmTheRtcMaster, XAvb_BecomeRtcMaster, XAvb_BestMasterClockAlgorithm, XAvb_ReadAnnounceFrame, XAvb_UpdateBmcRecords.
Referenced by XAvb_DecodeRxAnnounceFrame, XAvb_Start.
void XAvb_DecodeRxAnnounceFrame(XAvb *InstancePtr, u32 PtpFrameBaseAddr)
A New Announce Packet has been received.
We need to decode it and rerun the Best Master Clock Algorithm (BMCA) InstancePtr is a pointer to the XAvb instance to be worked on PtpFrameBaseAddr is the base address of the received Announce Packet in the Rx PTP Packet Buffer None. But an updated True/False decision as to whether this device should operate as a clock master or a slave is written into the CurrentBmc data structure. None.
References XAvb_BmcData::AnnounceIntervalDuration, XAvb_Config::BaseAddress, XAvb_ClockQuality::clockClass, XAvb_ClockIdentity::ClockIdentityLower, XAvb_ClockIdentity::ClockIdentityUpper, XAvb_BmcData::ClockQuality, XAvb::Config, XAvb_Counters::CounterAnnounceInterval, XAvb::CurrentBmc, XAvb_BmcData::GrandmasterIdentity, XAvb_BmcData::GrandmasterPriority1, XAvb_BmcData::GrandmasterPriority2, XAvb_BmcData::IAmTheRtcMaster, XAvb_BmcData::logMessageInterval, XAvb::portIdLocal, XAvb::PtpCounters, XAvb_BmcData::SourcePortIdentity, XAvb_BmcData::stepsRemoved, XAvb_BecomeRtcSlave, XAvb_BestMasterClockAlgorithm, XAvb_CompareClockIdentity, XAvb_ComparePortIdentity, XAvb_ConvertLogMeanToDuration, XAvb_DecodeTxAnnounceFrame, XAvb_ReadAnnounceFrame, XAvb_ReadAnnounceReceiptTimeout, XAvb_UpdateBmcRecords.
Referenced by XAvb_PtpRxInterruptHandler.
void XAvb_ReadAnnounceFrame(u32 BaseAddress, u32 PtpFrameBaseAddr, XAvb_BmcData *AnnounceFrame)
A New Announce Packet is to be analyzed.
This function will read in the packet, decode it, and extract the relevant information fields to the "AnnounceFrame" data pointer. BaseAddress is the base address of the device PtpFrameBaseAddr is the base address of the received Announce Packet in the Rx PTP Packet Buffer AnnounceFrame is a pointer to a suitable data structure, designed to record the useful fields from the received Announce Packet The AnnounceFrame data structure is updated. None.
References XAvb_ClockQuality::clockAccuracy, XAvb_ClockQuality::clockClass, XAvb_PortIdentity::ClockIdentityLower, XAvb_ClockIdentity::ClockIdentityLower, XAvb_PortIdentity::ClockIdentityUpper, XAvb_ClockIdentity::ClockIdentityUpper, XAvb_BmcData::ClockQuality, XAvb_BmcData::GrandmasterIdentity, XAvb_BmcData::GrandmasterPriority1, XAvb_BmcData::GrandmasterPriority2, XAvb_ClockQuality::offsetScaledLogVariance, XAvb_BmcData::SourcePortIdentity, XAvb_BmcData::stepsRemoved, XAvb_GetPortIdentity, XAvb_ReadPtpBuffer, XAvb_ReorderWord.
Referenced by XAvb_BecomeRtcMaster, XAvb_DecodeRxAnnounceFrame, XAvb_DecodeTxAnnounceFrame.
void XAvb_ReadAnnounceReceiptTimeout(u32 BaseAddress, u32 PtpFrameBaseAddr, XAvb_BmcData *AnnounceFrame)
This function reads the logMessageinteval from an RX PTP Buffer and updates the AnnounceFrame struct with the value read.
BaseAddress is the base address of the device PtpFrameBaseAddr is the base address of the received Announce Packet in the Rx PTP Packet Buffer AnnounceFrame is a pointer to a suitable data structure, designed to record the useful fields from the received Announce Packet The AnnounceFrame data structure is updated. None.
References XAvb_BmcData::logMessageInterval, XAvb_ReadPtpBuffer, XAvb_ReorderWord.
Referenced by XAvb_DecodeRxAnnounceFrame.
u32 XAvb_BestMasterClockAlgorithm(XAvb_BmcData *AnnounceFrame, XAvb_BmcData *CurrentBmc)
This function will accept the data pointer to the current BMCA records, accept a pointer to an equivalent data structure for the new Announce Packet.
The Best Master Clock Algorithm (BMCA) is then performed on these two data structures by comparing the data fields CurrentBmc is a pointer to a suitable data structure, designed to record the current fields from the current Grand Master's Announce Packet. AnnounceFrame is a pointer to a suitable data structure, designed to record the useful fields from the received Announce Packet An updated True/False decision as to whether there is to be a change of Grand Master in the network. None.
References XAvb_ClockQuality::clockAccuracy, XAvb_ClockQuality::clockClass, XAvb_PortIdentity::ClockIdentityLower, XAvb_ClockIdentity::ClockIdentityLower, XAvb_PortIdentity::ClockIdentityUpper, XAvb_ClockIdentity::ClockIdentityUpper, XAvb_BmcData::ClockQuality, XAvb_BmcData::GrandmasterIdentity, XAvb_BmcData::GrandmasterPriority1, XAvb_BmcData::GrandmasterPriority2, XAvb_ClockQuality::offsetScaledLogVariance, XAvb_PortIdentity::PortNumber, XAvb_BmcData::SourcePortIdentity, XAvb_BmcData::stepsRemoved.
Referenced by XAvb_DecodeRxAnnounceFrame, XAvb_DecodeTxAnnounceFrame.
void XAvb_UpdateBmcRecords(XAvb_BmcData *NewMaster, XAvb_BmcData *CurrentBmc)
This function will accept the data pointer to the current BMCA records, accept an equivalent pointer to a new (winning) Grand Masters Announce Packet information.
The CurrentBmc data structure is then updated with the information from the NewMaster. NewMaster is a pointer to a suitable data structure which has recorded the relevant Announce Packet fields of the new (winning) Grand Master. CurrentBmc is a pointer to a suitable data structure which has recorded the current fields of the current Grand Master's Announce Packet. The CurrentBmc data structure is updated. None.
References XAvb_PortIdentity::ClockIdentityLower, XAvb_ClockIdentity::ClockIdentityLower, XAvb_PortIdentity::ClockIdentityUpper, XAvb_ClockIdentity::ClockIdentityUpper, XAvb_BmcData::ClockQuality, XAvb_BmcData::GrandmasterIdentity, XAvb_BmcData::GrandmasterPriority1, XAvb_BmcData::GrandmasterPriority2, XAvb_PortIdentity::PortNumber, XAvb_BmcData::SourcePortIdentity, XAvb_BmcData::stepsRemoved.
Referenced by XAvb_BecomeRtcMaster, XAvb_DecodeRxAnnounceFrame, XAvb_DecodeTxAnnounceFrame.
void XAvb_BecomeRtcMaster(XAvb *InstancePtr, u8 txAnnounceHasWon)
This function will make any adjustments needed when the node becomes the Grand Master, including resetting the RTC to its nominal value.
InstancePtr is a pointer to the XAvb instance to be worked on txAnnounceHasWon indicates that this function has been called from the function XAvb_DecodeTxAnnounceFrame(). Is this is set then this function has no need to repeat actions that have been already performed. None. None.
References XAvb_Config::BaseAddress, XAvb::Config, XAvb::CurrentBmc, XAvb::GMDiscCallBackRef, XAvb::GMDiscHandler, XAvb_BmcData::IAmTheRtcMaster, XAvb_ReadAnnounceFrame, XAVB_RTC_INCREMENT_NOMINAL_RATE, XAVB_RTC_INCREMENT_OFFSET, XAvb_UpdateBmcRecords, XAvb_WriteReg.
Referenced by XAvb_DecodeTxAnnounceFrame, XAvb_PtpTimerInterruptHandler, XAvb_Reset.
void XAvb_BecomeRtcSlave(XAvb *InstancePtr)
This function will make any adjustments needed when the node becomes a PTP slave.
InstancePtr is a pointer to the XAvb instance to be worked on None. None.
References XAvb_Counters::CounterSyncInterval, XAvb::CurrentBmc, XAvb::GMDiscCallBackRef, XAvb::GMDiscHandler, XAvb_BmcData::IAmTheRtcMaster, XAvb::PtpCounters.
Referenced by XAvb_DecodeRxAnnounceFrame.
void XAvb_ChangePTPLockStatus(XAvb *InstancePtr, u8 locked)
Operations needed when PTP locks or unlocks.
InstancePtr is a pointer to the XAvb instance to be worked on locked is 1 if changing to locked status, zero if unlocked None. None.
References XAvb::GMDiscCallBackRef, XAvb::GMDiscHandler, XAvb::PTPLocked, XAvb_ChangePeerASCapability.
Referenced by XAvb_UpdateRtcIncrement.
void XAvb_ChangePeerASCapability(XAvb *InstancePtr, u8 capable)
Operations needed when the peer's AS capability changes.
InstancePtr is a pointer to the XAvb instance to be worked on capable is 1 if the peer is ASCapable, 0 otherwise None. None.
References XAvb::PeerASCapable.
Referenced by XAvb_CalcDelay, XAvb_ChangePTPLockStatus, XAvb_DecodeRxPDelayResp, XAvb_PtpTimerInterruptHandler, XAvb_Reset, XAvb_Start.
void XAvb_SetGMDiscontinuityHandler(XAvb *InstancePtr, XAvb_Handler FuncPtr, void *CallBackRef)
This function sets the handler that will be called when a GM discontinuity event is identified by the driver.
The purpose of the handler is to allow application specific processing to be performed. InstancePtr is a pointer to the XAvb instance. FuncPtr is the pointer to the callback function. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. None. There is no assert on the CallBackRef since the driver doesn't know what it is (nor should it)
References XAvb::GMDiscCallBackRef, XAvb::GMDiscHandler, XAvb::IsReady.
Referenced by main.