xavb_ptp_packets.c
u32 XAvb_CompareClockIdentity(u32 BaseAddress, XAvb_ClockIdentity Identity1, XAvb_ClockIdentity Identity2)
A function to compare two ClockIdentity values.
BaseAddress is the base address of the device Identity1 is the first ClockIdentity to be compared Identity2 is the second ClockIdentity to be compared 1 if the two values are equal, 0 if not equal
References XAvb_ClockIdentity::ClockIdentityLower, XAvb_ClockIdentity::ClockIdentityUpper.
Referenced by XAvb_DecodeRxAnnounceFrame.
u32 XAvb_ComparePortIdentity(u32 BaseAddress, XAvb_PortIdentity Identity1, XAvb_PortIdentity Identity2)
A function to compare two PortIdentity values.
BaseAddress is the base address of the device Identity1 is the first sourcePortIdentity to be compared Identity2 is the second sourcePortIdentity to be compared 1 if the two values are equal, 0 if not equal None.
References XAvb_PortIdentity::ClockIdentityLower, XAvb_PortIdentity::ClockIdentityUpper, XAvb_PortIdentity::PortNumber.
Referenced by XAvb_DecodeRxAnnounceFrame, XAvb_DecodeRxFollowUp, XAvb_DecodeRxPDelayResp, XAvb_DecodeRxPDelayRespFollowUp, XAvb_DecodeRxSync.
void XAvb_GetPortIdentity(u32 BaseAddress, u32 PtpFrameBaseAddr, u32 PortIdOffset, XAvb_PortIdentity *portID)
A function to extract portIdentity information from a received PTP frame.
This can be any portIdentity field (header portIdentity, requestingPortIdentity, etc.) BaseAddress is the base address of the device PtpFrameBaseAddr is the base address of the received Announce Packet in the Rx PTP Packet Buffer PortIdOffset is the packet offset of the first byte of the portIdentity field to be parsed portID is the XAvb_PortIdentity struct that the data will be written to. None, but portID will be updated with the portIdentity information None.
References XAvb_PortIdentity::ClockIdentityLower, XAvb_PortIdentity::ClockIdentityUpper, XAvb_PortIdentity::PortNumber, XAvb_ReadPtpBuffer, XAvb_ReorderWord.
Referenced by XAvb_DecodeRxFollowUp, XAvb_DecodeRxPDelayResp, XAvb_DecodeRxPDelayRespFollowUp, XAvb_DecodeRxSync, XAvb_ReadAnnounceFrame.
void XAvb_WriteToMultipleTxPtpFrames(u32 BaseAddress, u32 PtpFieldAddress, u32 Data, u32 DataBitEnable, u8 BufferEnable)
A function to write common data (eg the Source Address) to all PTP frames stored in the Tx PTP Packet buffer.
BaseAddress is the base address of the device PtpFieldAddress is the offset address of the relevant field in PTP frames. Data is the common data to be written to all Tx PTP frame templates DataBitEnable allows only selected bits of the 32-bit Data word to be modified. BufferEnable allows the selected buffer to be selected: there are 8 PTP buffers - these are encoded as one-hot. For example, 0x3F will write the selected data to the first 6 buffers only. None. But the Tx PTP Packet Buffer is written to as requested None.
References XAvb_ReadPtpBuffer, XAvb_WritePtpBuffer.
Referenced by main, XAvb_SetupSourcePortIdentity.
u32 XAvb_ReorderWord(u32 Data)
This function switches the bytes in a 4-byte word, swapping the MSB for the LSB, and vice-versa.
Data is the 4-byte input data word The input data word with the bytes swapped (most significant down to least significant None.
Referenced by main, XAvb_CalcRtcOffset, XAvb_CaptureNanoSec, XAvb_DecodeRxFollowUp, XAvb_DecodeRxPDelayResp, XAvb_DecodeRxPDelayRespFollowUp, XAvb_DecodeRxSignaling, XAvb_DecodeRxSync, XAvb_GetPortIdentity, XAvb_IncSequenceId, XAvb_IsRxFramePTP, XAvb_MasterSendFollowUp, XAvb_MasterSendSync, XAvb_ReadAnnounceFrame, XAvb_ReadAnnounceReceiptTimeout, XAvb_SendPDelayReq, XAvb_SendPDelayResp, XAvb_SendPDelayRespFollowUp, XAvb_SetupSourcePortIdentity.
u32 XAvb_IncSequenceId(u32 BaseAddress, u32 PtpFrameBaseAddress)
A function to increment the sequenceId in a PTP frame template.
BaseAddress is the base address of the device PtpFrameBaseAddress is the base address of the TX PTP Buffer whose SequenceID is to be incremented None. But the relevant TX PTP Packet Buffer is written to with the updated SequenceID None.
References XAvb_ReadPtpBuffer, XAvb_ReorderWord, XAvb_WritePtpBuffer.
Referenced by XAvb_MasterSendAnnounce, XAvb_MasterSendSync, XAvb_SendPDelayReq.
void XAvb_WaitOnTxPtpQueue(XAvb *InstancePtr)
The software drivers are kept simple by only requesting a single PTP frame to be transmitted at a time.
This function checks (and if necessary waits) until the previously request PTP frame has been transmitted. InstancePtr is a pointer to the XAvb instance to be worked on None. None.
References XAvb_Config::BaseAddress, XAvb::Config, XAVB_PTP_TX_CONTROL_OFFSET, XAvb_ReadReg.
Referenced by XAvb_MasterSendAnnounce, XAvb_MasterSendFollowUp, XAvb_MasterSendSync, XAvb_SendPDelayReq, XAvb_SendPDelayResp, XAvb_SendPDelayRespFollowUp.
void XAvb_MasterSendAnnounce(XAvb *InstancePtr)
A function to format then request the transmission of a PTP Announce Packet.
InstancePtr is a pointer to the XAvb instance to be worked on None. But the relevant Tx PTP Packet Buffer is written to with the updated PTP fields, and then the Tx PTP Packet Buffer Control Register is written to request the frame transmission. None.
References XAvb_Config::BaseAddress, XAvb::Config, XAvb_IncSequenceId, XAVB_PTP_TX_CONTROL_OFFSET, XAvb_ReadReg, XAVB_RTC_NANOSEC_VALUE_OFFSET, XAVB_RTC_SEC_LOWER_VALUE_OFFSET, XAvb_WaitOnTxPtpQueue, XAvb_WriteReg.
Referenced by XAvb_PtpTimerInterruptHandler.
void XAvb_MasterSendSync(XAvb *InstancePtr)
A function to format then request the transmission of a PTP Sync Packet.
InstancePtr is a pointer to the XAvb instance to be worked on None. But the relevant Tx PTP Packet Buffer is written to with the updated PTP fields, and then the Tx PTP Packet Buffer Control Register is written to request the frame transmission. None.
References XAvb_Config::BaseAddress, XAvb::Config, XAvb_PtpStruct::Nanosec, XAvb::PtpRecords, XAvb_IncSequenceId, XAVB_PTP_TX_CONTROL_OFFSET, XAvb_ReadPtpBuffer, XAvb_ReadReg, XAvb_ReorderWord, XAVB_RTC_NANOSEC_VALUE_OFFSET, XAVB_RTC_SEC_LOWER_VALUE_OFFSET, XAVB_RTC_SEC_UPPER_VALUE_OFFSET, XAvb_WaitOnTxPtpQueue, XAvb_WritePtpBuffer, XAvb_WriteReg.
Referenced by XAvb_PtpTimerInterruptHandler.
void XAvb_MasterSendFollowUp(XAvb *InstancePtr)
A function to format then request the transmission of a PTP Follow-Up Packet.
InstancePtr is a pointer to the XAvb instance to be worked on None. But the relevant Tx PTP Packet Buffer is written to with the updated PTP fields, and then the Tx PTP Packet Buffer Control Register is written to request the frame transmission. None.
References XAvb_Config::BaseAddress, XAvb::Config, XAvb_PtpStruct::Nanosec, XAvb::PtpRecords, XAVB_ONE_SECOND, XAVB_PTP_TX_CONTROL_OFFSET, XAvb_ReadPtpBuffer, XAvb_ReadReg, XAvb_ReorderWord, XAVB_RTC_NANOSEC_OFFSET, XAvb_WaitOnTxPtpQueue, XAvb_WritePtpBuffer, XAvb_WriteReg.
Referenced by XAvb_PtpTimerInterruptHandler.
void XAvb_SendPDelayReq(XAvb *InstancePtr)
A function to format then request the transmission of a PTP PDelay Request Packet.
InstancePtr is a pointer to the XAvb instance to be worked on None. But the relevant Tx PTP Packet Buffer is written to with the updated PTP fields, and then the Tx PTP Packet Buffer Control Register is written to request the frame transmission. None.
References XAvb_Config::BaseAddress, XAvb::Config, XAvb_SequenceIdStruct::PDelayReqSequenceId, XAvb_PtpStruct::PDelayTimestampT1, XAvb::PtpRecords, XAvb::SequenceIdRecords, XAvb_IncSequenceId, XAVB_PTP_TX_CONTROL_OFFSET, XAvb_ReadPtpBuffer, XAvb_ReorderWord, XAvb_WaitOnTxPtpQueue, XAvb_WriteReg.
Referenced by XAvb_PtpTimerInterruptHandler.
void XAvb_SendPDelayResp(XAvb *InstancePtr, u32 PtpFrameBaseAddr)
A function to format then request the transmission of a PTP PDelay Response Packet.
InstancePtr is a pointer to the XAvb instance to be worked on PtpFrameBaseAddr is the base address of the received Announce Packet in the Rx PTP Packet Buffer None. But the relevant Tx PTP Packet Buffer is written to with the updated PTP fields, and then the Tx PTP Packet Buffer Control Register is written to request the frame transmission. None.
References XAvb_Config::BaseAddress, XAvb::Config, XAvb_PtpStruct::NsOffsetForPDelayResp, XAvb::PtpRecords, XAVB_ONE_SECOND, XAVB_PTP_TX_CONTROL_OFFSET, XAvb_ReadPtpBuffer, XAvb_ReadReg, XAvb_ReorderWord, XAVB_RTC_NANOSEC_OFFSET, XAVB_RTC_NANOSEC_VALUE_OFFSET, XAVB_RTC_SEC_LOWER_VALUE_OFFSET, XAVB_RTC_SEC_UPPER_VALUE_OFFSET, XAvb_WaitOnTxPtpQueue, XAvb_WritePtpBuffer, XAvb_WriteReg.
Referenced by XAvb_PtpRxInterruptHandler.
void XAvb_SendPDelayRespFollowUp(XAvb *InstancePtr)
A function to format then request the transmission of a PTP PDelay Response Follow-Up Packet.
InstancePtr is a pointer to the XAvb instance to be worked on None. But the relevant Tx PTP Packet Buffer is written to with the updated PTP fields, and then the Tx PTP Packet Buffer Control Register is written to request the frame transmission. None.
References XAvb_Config::BaseAddress, XAvb::Config, XAvb_RtcFormat::NanoSeconds, XAvb_PtpStruct::NsOffsetForPDelayResp, XAvb::PtpRecords, XAvb_RtcFormat::SecondsLower, XAvb_RtcFormat::SecondsUpper, XAVB_ONE_SECOND, XAVB_PTP_TX_CONTROL_OFFSET, XAvb_ReadPtpBuffer, XAvb_ReadRtc, XAvb_ReorderWord, XAvb_WaitOnTxPtpQueue, XAvb_WritePtpBuffer, XAvb_WriteReg.
Referenced by XAvb_PtpRxInterruptHandler.
u32 XAvb_IsRxFramePTP(XAvb *InstancePtr, u32 PtpFrameBaseAddr)
A function to check that various fields in the received frame contain the expected values which define it as a valid AVB PTP frame.
If this check does not pass then the frame should not be decoded and used. InstancePtr is a pointer to the XAvb instance to be worked on PtpFrameBaseAddr is the base address of the received Announce Packet in the Rx PTP Packet Buffer An updated True/False decision as to whether this received frame really is a valid PTP type. None.
References XAvb_Config::BaseAddress, XAvb::Config, XAvb_ReadPtpBuffer, XAvb_ReorderWord.
Referenced by XAvb_PtpRxInterruptHandler.
void XAvb_DecodeRxSync(XAvb *InstancePtr, u32 PtpFrameBaseAddr)
A function to decode a received PTP Sync Packet.
InstancePtr is a pointer to the XAvb instance to be worked on PtpFrameBaseAddr is the base address of the received Announce Packet in the Rx PTP Packet Buffer None. None.
References XAvb_Config::BaseAddress, XAvb_PortIdentity::ClockIdentityLower, XAvb_PortIdentity::ClockIdentityUpper, XAvb::Config, XAvb_Counters::CounterSyncInterval, XAvb::CurrentBmc, XAvb_BmcData::IAmTheRtcMaster, XAvb::latestMDSyncReceive, XAvb_MDSyncReceive::logMessageInterval, XAvb_PortIdentity::PortNumber, XAvb::PtpCounters, XAvb::PtpRecords, XAvb::SequenceIdRecords, XAvb_PtpStruct::SlaveSyncTimestamp, XAvb_BmcData::SourcePortIdentity, XAvb_MDSyncReceive::SyncIntervalDuration, XAvb_SequenceIdStruct::SyncSequenceId, XAvb_ComparePortIdentity, XAvb_ConvertLogMeanToDuration, XAvb_GetPortIdentity, XAvb_ReadPtpBuffer, XAvb_ReorderWord.
Referenced by XAvb_PtpRxInterruptHandler.
void XAvb_DecodeRxFollowUp(XAvb *InstancePtr, u32 PtpFrameBaseAddr)
A function to decode a received PTP Follow-up Packet.
InstancePtr is a pointer to the XAvb instance to be worked on PtpFrameBaseAddr is the base address of the received Announce Packet in the Rx PTP Packet Buffer None. None.
References XAvb_Config::BaseAddress, XAvb::Config, XAvb_Counters::CounterSyncEvents, XAvb::CurrentBmc, XAvb_SequenceIdStruct::FollowUpSequenceId, XAvb_BmcData::IAmTheRtcMaster, XAvb_PtpStruct::MasterCorrectionField, XAvb_PtpStruct::NewMasterTime, XAvb_PtpStruct::NewSlaveTime, XAvb_SequenceIdStruct::NewSyncSequenceId, XAvb_PtpStruct::OldMasterTime, XAvb_PtpStruct::OldSlaveTime, XAvb_SequenceIdStruct::OldSyncSequenceId, XAvb::PtpCounters, XAvb::PtpRecords, XAvb::SequenceIdRecords, XAvb_BmcData::SourcePortIdentity, XAvb_SequenceIdStruct::SyncSequenceId, XAvb_CalcRtcOffset, XAvb_ComparePortIdentity, XAvb_GetPortIdentity, XAvb_ReadPtpBuffer, XAvb_ReorderWord, XAvb_UpdateRtcIncrement.
Referenced by XAvb_PtpRxInterruptHandler.
void XAvb_DecodeRxPDelayResp(XAvb *InstancePtr, u32 PtpFrameBaseAddr)
A function to decode a received PDelayResp Packet.
InstancePtr is a pointer to the XAvb instance to be worked on PtpFrameBaseAddr is the base address of the received Announce Packet in the Rx PTP Packet Buffer None. None.
References XAvb_Config::BaseAddress, XAvb::Config, XAvb_SequenceIdStruct::PDelayReqSequenceId, XAvb_SequenceIdStruct::PDelayRespSequenceId, XAvb_PtpStruct::PDelayTimestampT2, XAvb_PtpStruct::PDelayTimestampT4, XAvb::portIdLocal, XAvb::PtpRecords, XAvb_StateMachineData::rcvdPDelayResp, XAvb_StateMachineData::respPortIdentity, XAvb_StateMachineData::respReqPortIdentity, XAvb::SequenceIdRecords, XAvb::StateMachineData, XAvb_CaptureNanoSec, XAvb_ChangePeerASCapability, XAvb_ComparePortIdentity, XAvb_GetPortIdentity, XAvb_ReadPtpBuffer, XAvb_ReorderWord.
Referenced by XAvb_PtpRxInterruptHandler.
void XAvb_DecodeRxPDelayRespFollowUp(XAvb *InstancePtr, u32 PtpFrameBaseAddr)
A function to decode a received PDelayRespFollowUp Packet.
InstancePtr is a pointer to the XAvb instance to be worked on PtpFrameBaseAddr is the base address of the received Announce Packet in the Rx PTP Packet Buffer None. None.
References XAvb_Config::BaseAddress, XAvb::Config, XAvb_SequenceIdStruct::PDelayFollowUpSequenceId, XAvb_SequenceIdStruct::PDelayRespSequenceId, XAvb_PtpStruct::PDelayTimestampT3, XAvb::PtpRecords, XAvb_StateMachineData::rcvdPDelayResp, XAvb_StateMachineData::rcvdPDelayRespFollowUp, XAvb_StateMachineData::respPortIdentity, XAvb_StateMachineData::respReqPortIdentity, XAvb::SequenceIdRecords, XAvb::StateMachineData, XAvb_CalcDelay, XAvb_CaptureNanoSec, XAvb_ComparePortIdentity, XAvb_GetPortIdentity, XAvb_ReadPtpBuffer, XAvb_ReorderWord.
Referenced by XAvb_PtpRxInterruptHandler.
void XAvb_DecodeRxSignaling(XAvb *InstancePtr, u32 PtpFrameBaseAddr)
A function to decode a received Signalling Packet and modify the TX PTP Buffers based on the requested values.
InstancePtr is a pointer to the XAvb instance to be worked on PtpFrameBaseAddr is the base address of the received Signaling Packet in the Rx PTP Packet Buffer None. None.
References XAvb_SignallingFrameData::AnnounceIntervalDuration, XAvb_Config::BaseAddress, XAvb::Config, XAvb_SignallingFrameData::LinkDelayIntervalDuration, XAvb::SignallingFrameData, XAvb_SignallingFrameData::SyncIntervalDuration, XAvb_ReadPtpBuffer, XAvb_ReorderWord, XAvb_UpdateIntervalDuration, XAvb_UpdateLogMeanMessageInterval.
Referenced by XAvb_PtpRxInterruptHandler.
u16 XAvb_UpdateIntervalDuration(u16 currentIntervalDuration, char logMeanVal)
A function to update a PTP message Interval Duration (defined as a fraction of 128 seconds).
If the endpoint cannot support a requested logMeanVal then do not perform the conversion - return the current value. currentIntervalDuration is the Interval Duration to be updated logMeanVal is the base2 value that is to be converted logMeanVal represented as a fraction of 128 This endpoint only supports logMeanValues >=-7 and <=8.
References XAvb_ConvertLogMeanToDuration.
Referenced by XAvb_DecodeRxSignaling.
u16 XAvb_ConvertLogMeanToDuration(char logMeanVal)
A function to convert a logMean (power of 2) value into a fraction of 128 that is compatible with Signalling data.
logMeanVal is the base2 value that is to be converted logMeanVal represented as a fraction of 128 None.
Referenced by XAvb_DecodeRxAnnounceFrame, XAvb_DecodeRxSync, XAvb_Reset, XAvb_UpdateIntervalDuration.
char XAvb_ConvertDurationToLogMean(u16 fractionalVal)
A function to convert a fraction of 128 value that is compatible with Signalling data into a logMean (power of 2) value;.
fractionalVal is the Signalling data value that is to be converted fractionalVal represented as logMean (power of 2) value None.
Referenced by XAvb_UpdateLogMeanMessageInterval.
void XAvb_UpdateLogMeanMessageInterval(u32 BaseAddress, u32 PtpFrameBaseAddr, u16 intervalDuration)
A function to update the logMeanMessageInterval field in a PTP packet.
BaseAddress is the base address of the device PtpFrameBaseAddr is the base address of the TX PTP Buffer to be updated intervalDuration is the "fraction of 128" value of the data to be written None. But the relevant Tx PTP Packet Buffer is written to with the updated logMeanMessageInterval None.
References XAvb_ConvertDurationToLogMean, XAvb_ReadPtpBuffer, XAvb_WritePtpBuffer.
Referenced by XAvb_DecodeRxSignaling, XAvb_Reset.
void XAvb_SetupSourcePortIdentity(XAvb *InstancePtr, XAvb_PortIdentity systemIdentity)
This function updates the portIdLocal local copy of the sourcePortIdentity and writes this value into the TX PTP frame buffer templates.
The fields that are written are: o sourcePortIdentity for all default PTP frames o Announce:: grandmasterIdentity o Announce:: TLV clockIdentity InstancePtr is a pointer to the XAvb instance to be worked on systemIdentity is the clockIdentity and portNumber for this endpoint None. Announce::TLV. By default the tlvType and length field are set up in the BRAM, assuming that N = 1.
References XAvb_Config::BaseAddress, XAvb_PortIdentity::ClockIdentityLower, XAvb_PortIdentity::ClockIdentityUpper, XAvb::Config, XAvb::portIdLocal, XAvb_PortIdentity::PortNumber, XAvb_ReadPtpBuffer, XAvb_ReorderWord, XAvb_WritePtpBuffer, XAvb_WriteToMultipleTxPtpFrames.
Referenced by main.