xavb_rtc_sync.c
u32 XAvb_CaptureNanoSec(u32 BaseAddress, u32 PtpFrameBaseAddr)
References XAvb_ReadPtpBuffer, XAvb_ReorderWord.
Referenced by XAvb_DecodeRxPDelayResp, XAvb_DecodeRxPDelayRespFollowUp, XAvb_CalcRtcOffset.
void XAvb_CalcDelay(XAvb *InstancePtr)
References XAvb::PtpRecords, XAvb_PtpStruct::PDelayTimestampT1, XAvb_PtpStruct::PDelayTimestampT2, XAvb_PtpStruct::PDelayTimestampT3, XAvb_PtpStruct::PDelayTimestampT4, XAVB_ONE_SECOND, XAVB_NEIGHBOR_PROP_DELAY_THRESH, XAvb_PtpStruct::LinkDelay, XAvb_ChangePeerASCapability.
Referenced by XAvb_DecodeRxPDelayRespFollowUp.
void XAvb_CalcRtcOffset(XAvb *InstancePtr, u32 PtpFrameBaseAddr)
References XAvb_ReadRtc, XAvb::Config, XAvb_Config::BaseAddress, XAvb_CaptureNanoSec, XAvb_ReadPtpBuffer, XAvb_ReorderWord, XAvb::PtpRecords, XAvb_PtpStruct::MasterCorrectionField, XAvb_PtpStruct::LinkDelay, XAVB_ONE_SECOND, XAvb_RtcFormat::NanoSeconds, XAvb_PtpStruct::SlaveSyncTimestamp, XAvb_PtpStruct::NewSlaveTime, XAvb_PtpStruct::NewMasterTime, XAvb_Adjust8kClock, XAvb_ReadReg, XAVB_RTC_NANOSEC_OFFSET, XAvb_RtcFormat::SecondsLower, XAvb_RtcFormat::SecondsUpper, XAVB_RTC_SEC_LOWER_VALUE_OFFSET, XAvb_WriteRtcOffset.
Referenced by XAvb_DecodeRxFollowUp.
void XAvb_Adjust8kClock(u32 BaseAddress, u32 NewOffset)
References XAvb_ReadReg, XAVB_RTC_NANOSEC_OFFSET, XAVB_PERIOD_8KHZ, XAVB_RTC_8K_OFFSET_OFFSET, XAvb_WriteReg.
Referenced by XAvb_CalcRtcOffset.
void XAvb_UpdateRtcIncrement(XAvb *InstancePtr)
References XAvb::SequenceIdRecords, XAvb_SequenceIdStruct::OldSyncSequenceId, XAvb_SequenceIdStruct::NewSyncSequenceId, XAvb::PtpRecords, XAvb_PtpStruct::NewMasterTime, XAvb_PtpStruct::OldMasterTime, XAvb_PtpStruct::NewSlaveTime, XAvb_PtpStruct::OldSlaveTime, XAVB_ONE_SECOND, XAVB_CLOCK_LOCK_THRESHOLD, XAvb_ChangePTPLockStatus, XAvb_ReadReg, XAvb::Config, XAvb_Config::BaseAddress, XAVB_RTC_INCREMENT_OFFSET, XAVB_RTC_INCREMENT_NOMINAL_RATE, XAVB_RTC_400PPM_OFFSET, XAvb_WriteReg.
Referenced by XAvb_DecodeRxFollowUp.