xavb_hw.c
void XAvbMac_ReadStats(u32 BaseAddress, u32 CounterId, XAvb_Uint64 *Value)
This function reads the given Ethernet Statistic Register.
BaseAddress is the base address of the device CounterID is the Statistic Counter to be read Value a pointer to the read value of the 64-bit value of the counter and it is updated by this function None. The CounterID's defined here are the same as the Statistic Counter Addresses as used with the TEMAC core. Since each counter is 8-bytes wide, we must multiply these Counter ID's by 8 (or a left shift of 3) when mapping this into the PLB memory map. The 64-bit counter value is read as two separate 32-bit accesses.
References XAvb_Uint64::Lower, XAvb_Uint64::Upper.
void XAvb_ReadRtc(u32 BaseAddress, XAvb_RtcFormat *RtcValue)
This function reads the current Real Time Counter (RTC) value.
BaseAddress is the base address of the device RtcValue is a pointer to a struct in which to store the value read from the RTC (The RTC 48-bit seconds field and the 32-bit ns field of this struct are updated). None This is provided as a basic function since the ns field MUST be read before the seconds/epoch registers (reading the ns samples the entire RTC in hardware).
References XAvb_RtcFormat::NanoSeconds, XAvb_RtcFormat::SecondsLower, XAvb_RtcFormat::SecondsUpper, XAVB_RTC_NANOSEC_VALUE_OFFSET, XAVB_RTC_SEC_LOWER_VALUE_OFFSET, XAVB_RTC_SEC_UPPER_VALUE_OFFSET.
Referenced by XAvb_CalcRtcOffset, XAvb_SendPDelayRespFollowUp.
void XAvb_WriteRtcOffset(u32 BaseAddress, XAvb_RtcFormat *RtcValue)
This function writes to the Real Time Counter (RTC) Offset Registers.
BaseAddress is the base address of the device RtcValue is the nanoseconds and seconds offset values that should be written to the RTC. None This is provided as a basic function since the ns field MUST be written after the seconds/epoch offset registers (writing to the ns offset registers samples the entire RTC offset in hardware).
References XAvb_RtcFormat::NanoSeconds, XAvb_RtcFormat::SecondsLower, XAvb_RtcFormat::SecondsUpper, XAVB_RTC_NANOSEC_OFFSET, XAVB_RTC_SEC_LOWER_OFFSET, XAVB_RTC_SEC_UPPER_OFFSET.
Referenced by XAvb_CalcRtcOffset.