xavb.c
XAvb_Config XAvb_ConfigTable[][]
volatile u8 EchoPTPFramesReceived
static void XAvb_StubHandler(void *CallBackRef, u32 TimestampsUncertain)
XStatus XAvb_CfgInitialize(XAvb *InstancePtr, XAvb_Config *ConfigPtr, u32 EffectiveAddress)
A function to initialise variables in the data structure records.
InstancePtr is a pointer to the XAvb instance to be worked on ConfigPtr is the Configuration Pointer EffectiveAddress is the base address of the Configuration Pointer XST_SUCCESS if initialization was successfulXST_DEVICE_NOT_FOUND if device configuration information was not found for a device with the supplied device ID.* None.
References XAvb_Config::BaseAddress, XAvb::Config, XAvb::GMDiscHandler, XAvb::IsReady.
Referenced by main.
void XAvb_Reset(XAvb *InstancePtr)
This function resets all of the AVB device driver functions to the start-up (reset) defaults.
InstancePtr is a pointer to the Xavb instance to be worked on. None. None.
References XAvb_SignallingFrameData::AnnounceIntervalDuration, XAvb_Config::BaseAddress, XAvb::Config, XAvb_Counters::CounterAnnounceInterval, XAvb_Counters::CounterLinkDelayInterval, XAvb_Counters::CounterSyncEvents, XAvb_Counters::CounterSyncInterval, XAvb::IsReady, XAvb::latestMDSyncReceive, XAvb_PtpStruct::LinkDelay, XAvb_SignallingFrameData::LinkDelayIntervalDuration, XAvb_StateMachineData::lostResponses, XAvb::PtpCounters, XAvb::PtpIsRunning, XAvb::PtpRecords, XAvb_StateMachineData::rcvdPDelayResp, XAvb_StateMachineData::rcvdPDelayRespFollowUp, XAvb_Counters::RxPtpHardPointer, XAvb_Counters::RxPtpSoftPointer, XAvb::SignallingFrameData, XAvb::StateMachineData, XAvb_SignallingFrameData::SyncIntervalDuration, XAvb_MDSyncReceive::SyncIntervalDuration, XAvb_BecomeRtcMaster, XAvb_ChangePeerASCapability, XAvb_ConvertLogMeanToDuration, XAVB_SW_RESET_OFFSET, XAvb_UpdateLogMeanMessageInterval, XAvb_WriteReg.
Referenced by main, XAvb_Stop.
void XAvb_Start(XAvb *InstancePtr)
This function will start the PTP drivers running.
InstancePtr is a pointer to the Xavb instance to be worked on. None. None.
References XAvb::IsReady, XAvb::PtpIsRunning, XAvb_ChangePeerASCapability, XAvb_DecodeTxAnnounceFrame.
Referenced by main.
void XAvb_Stop(XAvb *InstancePtr)
This function will stop the PTP drivers from running.
InstancePtr is a pointer to the Xavb instance to be worked on. None. None.
References XAvb::IsReady, XAvb_Reset.
void XAvb_PtpTimerInterruptHandler(XAvb *InstancePtr)
The Interrupt subroutine for the "interruptPtpTimer" signal.
This interrupt fires regularly on a 1/128 second period (based on the RTC). InstancePtr is a pointer to the XAvb instance to be worked on None. None.
References XAvb_BmcData::AnnounceIntervalDuration, XAvb_SignallingFrameData::AnnounceIntervalDuration, XAvb_Config::BaseAddress, XAvb::Config, XAvb_Counters::CounterAnnounceInterval, XAvb_Counters::CounterLinkDelayInterval, XAvb_Counters::CounterSyncInterval, XAvb::CurrentBmc, XAvb_BmcData::IAmTheRtcMaster, XAvb::latestMDSyncReceive, XAvb_SignallingFrameData::LinkDelayIntervalDuration, XAvb_StateMachineData::lostResponses, XAvb::PeerASCapable, XAvb::PtpCounters, XAvb::PtpIsRunning, XAvb_StateMachineData::rcvdPDelayResp, XAvb_StateMachineData::rcvdPDelayRespFollowUp, XAvb::SignallingFrameData, XAvb::StateMachineData, XAvb_SignallingFrameData::SyncIntervalDuration, XAvb_MDSyncReceive::SyncIntervalDuration, XAVB_ALLOWED_LOST_RESPONSES, XAVB_ANNOUNCE_RECEIPT_TIMEOUT, XAvb_BecomeRtcMaster, XAvb_ChangePeerASCapability, XAvb_MasterSendAnnounce, XAvb_MasterSendFollowUp, XAvb_MasterSendSync, XAVB_RTC_CLEAR_INT_OFFSET, XAvb_SendPDelayReq, XAVB_SYNC_RECEIPT_TIMEOUT, XAvb_WriteReg.
void XAvb_PtpRxInterruptHandler(XAvb *InstancePtr)
The Interrupt subroutine for the "interrupt_ptp_rx" signal.
This interrupt fires whenever a PTP frame has been received. The main function is to identify, decode, and act on the type of PTP frame received. InstancePtr is a pointer to the XAvb instance to be worked on None. None.
References XAvb_Config::BaseAddress, XAvb::Config, XAvb::PtpCounters, XAvb::PtpIsRunning, XAvb_Counters::RxPtpHardPointer, XAvb_Counters::RxPtpSoftPointer, XAvb_DecodeRxAnnounceFrame, XAvb_DecodeRxFollowUp, XAvb_DecodeRxPDelayResp, XAvb_DecodeRxPDelayRespFollowUp, XAvb_DecodeRxSignaling, XAvb_DecodeRxSync, XAvb_IsRxFramePTP, XAVB_PTP_RX_CONTROL_OFFSET, XAvb_ReadPtpBuffer, XAvb_ReadReg, XAvb_SendPDelayResp, XAvb_SendPDelayRespFollowUp.
void XAvb_SetupRxFilterControlPcp(XAvb *InstancePtr, u32 VlanPriority, u8 SrClass)
A function to set the VLAN PCP field for either SR A or B traffic in the RX Filtering Control Register - such that AV traffic is correctly filtered by the RX Splitter.
InstancePtr is a pointer to the XAvb instance to be worked on VlanPriority contains the 3-bit value to be written to the register in the correct bit positions as defined in the address map SrClass is '0' if VLAN Priority (PCP) A is to be updated and is '1' if VLAN Priority (PCP) B is to be updated None. None.
References XAvb_Config::BaseAddress, XAvb::Config, XAvb_ReadReg, XAVB_RX_FILTER_CONTROL, XAvb_WriteReg.
void XAvb_SetupRxFilterControlVid(XAvb *InstancePtr, u32 VlanVid, u8 SrClass)
A function to set the VLAN VID field for either SR A or B traffic in the RX Filtering Control Register - such that AV traffic is correctly filtered by the RX Splitter.
InstancePtr is a pointer to the XAvb instance to be worked on VlanVid contains the 12-bit value to be written to the register in the correct bit positions as defined in the address map SrClass is '0' if VLAN VID A is to be updated and is '1' if VLAN VID B is to be updated None. None.
References XAvb_Config::BaseAddress, XAvb::Config, XAvb_ReadReg, XAVB_RX_FILTER_CONTROL, XAvb_WriteReg.
void XAvb_SetupRxFilterControlMatchMode(XAvb *InstancePtr, u32 VlanMatchMode)
A function to set the VLAN Match Mode field for the RX Filtering Control Register - such that AV traffic is correctly filtered by the RX Splitter.
InstancePtr is a pointer to the XAvb instance to be worked on VlanMatchMode contains the 1-bit value to be written to the register in the correct bit position as defined in the address map None. None.
References XAvb_Config::BaseAddress, XAvb::Config, XAvb_ReadReg, XAVB_RX_FILTER_CONTROL, XAvb_WriteReg.