xavb.h
XAVB_TX_MAC_LATENCY_IN_NS
XAVB_RX_MAC_LATENCY_IN_NS
XAVB_PTP_TX_SYNC
XAVB_PTP_TX_FOLLOW_UP
XAVB_PTP_TX_PDELAYREQ
XAVB_PTP_TX_PDELAYRESP
XAVB_PTP_TX_PDELAYRESP_FOLLOW_UP
XAVB_PTP_TX_ANNOUNCE
XAVB_PTP_TX_SIGNALING
XAVB_PTP_TYPE_SYNC
XAVB_PTP_TYPE_FOLLOW_UP
XAVB_PTP_TYPE_PDELAYREQ
XAVB_PTP_TYPE_PDELAYRESP
XAVB_PTP_TYPE_PDELAYRESP_FOLLOW_UP
XAVB_PTP_TYPE_ANNOUNCE
XAVB_PTP_TYPE_SIGNALING
XAVB_PTP_PKT_CAPTURED_TIMESTAMP_OFFSET
XAVB_PTP_TX_PKT_SA_UPPER_OFFSET
XAVB_PTP_TX_PKT_SA_LOWER_OFFSET
XAVB_PTP_TX_PKT_TYPE_OFFSET
XAVB_PTP_TX_PKT_CORRECTION_FIELD_OFFSET
XAVB_PTP_TX_PKT_PORTID_UPPER_OFFSET
XAVB_PTP_TX_PKT_PORTID_MID_OFFSET
XAVB_PTP_TX_PKT_PORTID_LOWER_OFFSET
XAVB_PTP_TX_PKT_SEQUENCEID_OFFSET
XAVB_PTP_TX_PKT_TIMESTAMP_UPPER_OFFSET
XAVB_PTP_TX_PKT_TIMESTAMP_MID_OFFSET
XAVB_PTP_TX_PKT_TIMESTAMP_LOWER_OFFSET
XAVB_PTP_TX_PKT_REQ_PORTID_UPPER_OFFSET
XAVB_PTP_TX_PKT_REQ_PORTID_MID_OFFSET
XAVB_PTP_TX_PKT_REQ_PORTID_LOWER_OFFSET
XAVB_PTP_TX_PKT_ANNOUNCE_CURR_UTCOFF_OFFSET
XAVB_PTP_TX_PKT_ANNOUNCE_QUAL_LOW_PRI2_GMID_HI_OFFSET
XAVB_PTP_TX_PKT_ANNOUNCE_GMID_MID_OFFSET
XAVB_PTP_TX_PKT_ANNOUNCE_GMID_LOW_STEPSREMOVED_HI_OFFSET
XAVB_PTP_TX_PKT_ANNOUNCE_STEPSREMOVED_LOW_TIMESRC_OFFSET
XAVB_PTP_TX_PKT_ANNOUNCE_TLVLEN_PATHSEQ_START_OFFSET
XAVB_PDELAY_LOG_MEAN_MESSAGE_INT
XAVB_DEFAULT_LOG_MEAN_SYNC_INTERVAL
XAVB_DEFAULT_LOG_MEAN_PDELAY_REQ_INTERVAL
XAVB_DEFAULT_LOG_MEAN_ANNOUNCE_INTERVAL
XAVB_PKT_TYPE_DISABLED
XAVB_MAX_SUPPORTED_LOG_MEAN_INTERVAL
XAVB_MIN_SUPPORTED_LOG_MEAN_INTERVAL
XAVB_ANNOUNCE_RECEIPT_TIMEOUT
XAVB_ANNOUNCE_RECEIPT_TIMEOUT is the number of announce intervals without the receipt of an Announce message from the GM that are allowed before the GM is assumed to be no longer present and BMCA should be run again.
Referenced by XAvb_PtpTimerInterruptHandler.
XAVB_SYNC_RECEIPT_TIMEOUT
XAVB_SYNC_RECEIPT_TIMEOUT is the number of sync intervals without the receipt of an Sync message from the GM that are allowed before the GM is assumed to be no longer present and BMCA should be run again.
Referenced by XAvb_PtpTimerInterruptHandler.
XAVB_NEIGHBOR_PROP_DELAY_THRESH
XAVB_NEIGHBOR_PROP_DELAY_THRESH is the maximum allowed delay (in nanosecs) across a full duplex link for which the AVB protocol is allowed to function.
Although this parameter is defined in the IEEE spec, no default is defined.
Referenced by XAvb_CalcDelay.
XAVB_ALLOWED_LOST_RESPONSES
XAVB_ALLOWED_LOST_RESPONSES is the number of Pdelay_Req messages for which a valid response is not received, above which the Peer should no longer be considered ASCapable.
Referenced by XAvb_PtpTimerInterruptHandler.
XAVB_PTP_RX_PKT_SA_UPPER_OFFSET
XAVB_PTP_RX_PKT_SA_LOWER_OFFSET
XAVB_PTP_RX_PKT_TYPE_OFFSET
XAVB_PTP_RX_PKT_CORRECTION_FIELD_OFFSET
XAVB_PTP_RX_PKT_PORTID_UPPER_OFFSET
XAVB_PTP_RX_PKT_PORTID_MID_OFFSET
XAVB_PTP_RX_PKT_PORTID_LOWER_OFFSET
XAVB_PTP_RX_PKT_SEQUENCEID_OFFSET
XAVB_PTP_RX_PKT_TIMESTAMP_UPPER_OFFSET
XAVB_PTP_RX_PKT_TIMESTAMP_MID_OFFSET
XAVB_PTP_RX_PKT_TIMESTAMP_LOWER_OFFSET
XAVB_PTP_RX_PKT_REQ_PORTID_UPPER_OFFSET
XAVB_PTP_RX_PKT_REQ_PORTID_MID_OFFSET
XAVB_PTP_RX_PKT_REQ_PORTID_LOWER_OFFSET
XAVB_PTP_RX_PKT_ANNOUNCE_PRI1_QUAL_HI_OFFSET
XAVB_PTP_RX_PKT_ANNOUNCE_QUAL_LOW_PRI2_GMID_HI_OFFSET
XAVB_PTP_RX_PKT_ANNOUNCE_GMID_MID_OFFSET
XAVB_PTP_RX_PKT_ANNOUNCE_GMID_LOW_STEPSREMOVED_HI_OFFSET
XAVB_PTP_RX_PKT_ANNOUNCE_STEPSREMOVED_LOW_TIMESRC_OFFSET
XAVB_PTP_RX_PKT_SIGNALING_DELAY_INTERVAL_OFFSET
XAVB_PTP_ETHERTYPE
XAVB_PTP_VERSION_PTP
XAVB_ONE_SECOND
Value in ns.
Referenced by XAvb_CalcDelay, XAvb_CalcRtcOffset, XAvb_MasterSendFollowUp, XAvb_SendPDelayResp, XAvb_SendPDelayRespFollowUp, XAvb_UpdateRtcIncrement.
XAVB_PERIOD_8KHZ
Value in ns.
Referenced by XAvb_Adjust8kClock.
XAVB_CLOCK_LOCK_THRESHOLD
Value in ns.
Referenced by XAvb_UpdateRtcIncrement.
XAVB_NUM_SYNC_FU_PAIR_CALC_RTC_INCREMENT
XAVB_H
typedef void(* XAvb_Handler)(void *CallBackRef, u32 TimestampsUncertain))(void *CallBackRef, u32 TimestampsUncertain)
Callback function.
The first argument is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. The second argument is a '1' if a Grandmaster Discontinuity event has occurred otherwise it is '0'.
XStatus XAvb_CfgInitialize(XAvb *InstancePtr, XAvb_Config *ConfigPtr, u32 EffectiveAddress)
A function to initialise variables in the data structure records.
InstancePtr is a pointer to the XAvb instance to be worked on ConfigPtr is the Configuration Pointer EffectiveAddress is the base address of the Configuration Pointer XST_SUCCESS if initialization was successfulXST_DEVICE_NOT_FOUND if device configuration information was not found for a device with the supplied device ID.* None.
References XAvb_Config::BaseAddress, XAvb::Config, XAvb::GMDiscHandler, XAvb::IsReady.
Referenced by main.
XAvb_Config* XAvb_LookupConfig(u16 DeviceId)
void XAvb_Reset(XAvb *InstancePtr)
This function resets all of the AVB device driver functions to the start-up (reset) defaults.
InstancePtr is a pointer to the Xavb instance to be worked on. None. None.
References XAvb_SignallingFrameData::AnnounceIntervalDuration, XAvb_Config::BaseAddress, XAvb::Config, XAvb_Counters::CounterAnnounceInterval, XAvb_Counters::CounterLinkDelayInterval, XAvb_Counters::CounterSyncEvents, XAvb_Counters::CounterSyncInterval, XAvb::IsReady, XAvb::latestMDSyncReceive, XAvb_PtpStruct::LinkDelay, XAvb_SignallingFrameData::LinkDelayIntervalDuration, XAvb_StateMachineData::lostResponses, XAvb::PtpCounters, XAvb::PtpIsRunning, XAvb::PtpRecords, XAvb_StateMachineData::rcvdPDelayResp, XAvb_StateMachineData::rcvdPDelayRespFollowUp, XAvb_Counters::RxPtpHardPointer, XAvb_Counters::RxPtpSoftPointer, XAvb::SignallingFrameData, XAvb::StateMachineData, XAvb_SignallingFrameData::SyncIntervalDuration, XAvb_MDSyncReceive::SyncIntervalDuration, XAvb_BecomeRtcMaster, XAvb_ChangePeerASCapability, XAvb_ConvertLogMeanToDuration, XAVB_SW_RESET_OFFSET, XAvb_UpdateLogMeanMessageInterval, XAvb_WriteReg.
Referenced by main, XAvb_Stop.
void XAvb_Start(XAvb *InstancePtr)
This function will start the PTP drivers running.
InstancePtr is a pointer to the Xavb instance to be worked on. None. None.
References XAvb::IsReady, XAvb::PtpIsRunning, XAvb_ChangePeerASCapability, XAvb_DecodeTxAnnounceFrame.
Referenced by main.
void XAvb_Stop(XAvb *InstancePtr)
This function will stop the PTP drivers from running.
InstancePtr is a pointer to the Xavb instance to be worked on. None. None.
References XAvb::IsReady, XAvb_Reset.
void XAvb_PtpTimerInterruptHandler(XAvb *InstancePtr)
The Interrupt subroutine for the "interruptPtpTimer" signal.
This interrupt fires regularly on a 1/128 second period (based on the RTC). InstancePtr is a pointer to the XAvb instance to be worked on None. None.
References XAvb_BmcData::AnnounceIntervalDuration, XAvb_SignallingFrameData::AnnounceIntervalDuration, XAvb_Config::BaseAddress, XAvb::Config, XAvb_Counters::CounterAnnounceInterval, XAvb_Counters::CounterLinkDelayInterval, XAvb_Counters::CounterSyncInterval, XAvb::CurrentBmc, XAvb_BmcData::IAmTheRtcMaster, XAvb::latestMDSyncReceive, XAvb_SignallingFrameData::LinkDelayIntervalDuration, XAvb_StateMachineData::lostResponses, XAvb::PeerASCapable, XAvb::PtpCounters, XAvb::PtpIsRunning, XAvb_StateMachineData::rcvdPDelayResp, XAvb_StateMachineData::rcvdPDelayRespFollowUp, XAvb::SignallingFrameData, XAvb::StateMachineData, XAvb_SignallingFrameData::SyncIntervalDuration, XAvb_MDSyncReceive::SyncIntervalDuration, XAVB_ALLOWED_LOST_RESPONSES, XAVB_ANNOUNCE_RECEIPT_TIMEOUT, XAvb_BecomeRtcMaster, XAvb_ChangePeerASCapability, XAvb_MasterSendAnnounce, XAvb_MasterSendFollowUp, XAvb_MasterSendSync, XAVB_RTC_CLEAR_INT_OFFSET, XAvb_SendPDelayReq, XAVB_SYNC_RECEIPT_TIMEOUT, XAvb_WriteReg.
void XAvb_PtpRxInterruptHandler(XAvb *InstancePtr)
The Interrupt subroutine for the "interrupt_ptp_rx" signal.
This interrupt fires whenever a PTP frame has been received. The main function is to identify, decode, and act on the type of PTP frame received. InstancePtr is a pointer to the XAvb instance to be worked on None. None.
References XAvb_Config::BaseAddress, XAvb::Config, XAvb::PtpCounters, XAvb::PtpIsRunning, XAvb_Counters::RxPtpHardPointer, XAvb_Counters::RxPtpSoftPointer, XAvb_DecodeRxAnnounceFrame, XAvb_DecodeRxFollowUp, XAvb_DecodeRxPDelayResp, XAvb_DecodeRxPDelayRespFollowUp, XAvb_DecodeRxSignaling, XAvb_DecodeRxSync, XAvb_IsRxFramePTP, XAVB_PTP_RX_CONTROL_OFFSET, XAvb_ReadPtpBuffer, XAvb_ReadReg, XAvb_SendPDelayResp, XAvb_SendPDelayRespFollowUp.
void XAvb_SetupRxFilterControlPcp(XAvb *InstancePtr, u32 VlanPriority, u8 SrClass)
A function to set the VLAN PCP field for either SR A or B traffic in the RX Filtering Control Register - such that AV traffic is correctly filtered by the RX Splitter.
InstancePtr is a pointer to the XAvb instance to be worked on VlanPriority contains the 3-bit value to be written to the register in the correct bit positions as defined in the address map SrClass is '0' if VLAN Priority (PCP) A is to be updated and is '1' if VLAN Priority (PCP) B is to be updated None. None.
References XAvb_Config::BaseAddress, XAvb::Config, XAvb_ReadReg, XAVB_RX_FILTER_CONTROL, XAvb_WriteReg.
void XAvb_SetupRxFilterControlVid(XAvb *InstancePtr, u32 VlanVid, u8 SrClass)
A function to set the VLAN VID field for either SR A or B traffic in the RX Filtering Control Register - such that AV traffic is correctly filtered by the RX Splitter.
InstancePtr is a pointer to the XAvb instance to be worked on VlanVid contains the 12-bit value to be written to the register in the correct bit positions as defined in the address map SrClass is '0' if VLAN VID A is to be updated and is '1' if VLAN VID B is to be updated None. None.
References XAvb_Config::BaseAddress, XAvb::Config, XAvb_ReadReg, XAVB_RX_FILTER_CONTROL, XAvb_WriteReg.
void XAvb_SetupRxFilterControlMatchMode(XAvb *InstancePtr, u32 VlanMatchMode)
A function to set the VLAN Match Mode field for the RX Filtering Control Register - such that AV traffic is correctly filtered by the RX Splitter.
InstancePtr is a pointer to the XAvb instance to be worked on VlanMatchMode contains the 1-bit value to be written to the register in the correct bit position as defined in the address map None. None.
References XAvb_Config::BaseAddress, XAvb::Config, XAvb_ReadReg, XAVB_RX_FILTER_CONTROL, XAvb_WriteReg.
u32 XAvb_ReorderWord(u32 Data)
This function switches the bytes in a 4-byte word, swapping the MSB for the LSB, and vice-versa.
Data is the 4-byte input data word The input data word with the bytes swapped (most significant down to least significant None.
Referenced by main, XAvb_CalcRtcOffset, XAvb_CaptureNanoSec, XAvb_DecodeRxFollowUp, XAvb_DecodeRxPDelayResp, XAvb_DecodeRxPDelayRespFollowUp, XAvb_DecodeRxSignaling, XAvb_DecodeRxSync, XAvb_GetPortIdentity, XAvb_IncSequenceId, XAvb_IsRxFramePTP, XAvb_MasterSendFollowUp, XAvb_MasterSendSync, XAvb_ReadAnnounceFrame, XAvb_ReadAnnounceReceiptTimeout, XAvb_SendPDelayReq, XAvb_SendPDelayResp, XAvb_SendPDelayRespFollowUp, XAvb_SetupSourcePortIdentity.
u32 XAvb_CompareClockIdentity(u32 BaseAddress, XAvb_ClockIdentity Identity1, XAvb_ClockIdentity Identity2)
A function to compare two ClockIdentity values.
BaseAddress is the base address of the device Identity1 is the first ClockIdentity to be compared Identity2 is the second ClockIdentity to be compared 1 if the two values are equal, 0 if not equal
References XAvb_ClockIdentity::ClockIdentityLower, XAvb_ClockIdentity::ClockIdentityUpper.
Referenced by XAvb_DecodeRxAnnounceFrame.
u32 XAvb_ComparePortIdentity(u32 BaseAddress, XAvb_PortIdentity Identity1, XAvb_PortIdentity Identity2)
A function to compare two PortIdentity values.
BaseAddress is the base address of the device Identity1 is the first sourcePortIdentity to be compared Identity2 is the second sourcePortIdentity to be compared 1 if the two values are equal, 0 if not equal None.
References XAvb_PortIdentity::ClockIdentityLower, XAvb_PortIdentity::ClockIdentityUpper, XAvb_PortIdentity::PortNumber.
Referenced by XAvb_DecodeRxAnnounceFrame, XAvb_DecodeRxFollowUp, XAvb_DecodeRxPDelayResp, XAvb_DecodeRxPDelayRespFollowUp, XAvb_DecodeRxSync.
void XAvb_WriteToMultipleTxPtpFrames(u32 BaseAddress, u32 Address, u32 Data, u32 DataBitEnable, u8 BufferEnable)
A function to write common data (eg the Source Address) to all PTP frames stored in the Tx PTP Packet buffer.
BaseAddress is the base address of the device PtpFieldAddress is the offset address of the relevant field in PTP frames. Data is the common data to be written to all Tx PTP frame templates DataBitEnable allows only selected bits of the 32-bit Data word to be modified. BufferEnable allows the selected buffer to be selected: there are 8 PTP buffers - these are encoded as one-hot. For example, 0x3F will write the selected data to the first 6 buffers only. None. But the Tx PTP Packet Buffer is written to as requested None.
References XAvb_ReadPtpBuffer, XAvb_WritePtpBuffer.
Referenced by main, XAvb_SetupSourcePortIdentity.
u32 XAvb_IncSequenceId(u32 BaseAddress, u32 PTPFrameBaseAddress)
A function to increment the sequenceId in a PTP frame template.
BaseAddress is the base address of the device PtpFrameBaseAddress is the base address of the TX PTP Buffer whose SequenceID is to be incremented None. But the relevant TX PTP Packet Buffer is written to with the updated SequenceID None.
References XAvb_ReadPtpBuffer, XAvb_ReorderWord, XAvb_WritePtpBuffer.
Referenced by XAvb_MasterSendAnnounce, XAvb_MasterSendSync, XAvb_SendPDelayReq.
void XAvb_GetPortIdentity(u32 BaseAddress, u32 PtpFrameBaseAddr, u32 PortIdOffset, XAvb_PortIdentity *portID)
A function to extract portIdentity information from a received PTP frame.
This can be any portIdentity field (header portIdentity, requestingPortIdentity, etc.) BaseAddress is the base address of the device PtpFrameBaseAddr is the base address of the received Announce Packet in the Rx PTP Packet Buffer PortIdOffset is the packet offset of the first byte of the portIdentity field to be parsed portID is the XAvb_PortIdentity struct that the data will be written to. None, but portID will be updated with the portIdentity information None.
References XAvb_PortIdentity::ClockIdentityLower, XAvb_PortIdentity::ClockIdentityUpper, XAvb_PortIdentity::PortNumber, XAvb_ReadPtpBuffer, XAvb_ReorderWord.
Referenced by XAvb_DecodeRxFollowUp, XAvb_DecodeRxPDelayResp, XAvb_DecodeRxPDelayRespFollowUp, XAvb_DecodeRxSync, XAvb_ReadAnnounceFrame.
void XAvb_WaitOnTxPtpQueue(XAvb *InstancePtr)
The software drivers are kept simple by only requesting a single PTP frame to be transmitted at a time.
This function checks (and if necessary waits) until the previously request PTP frame has been transmitted. InstancePtr is a pointer to the XAvb instance to be worked on None. None.
References XAvb_Config::BaseAddress, XAvb::Config, XAVB_PTP_TX_CONTROL_OFFSET, XAvb_ReadReg.
Referenced by XAvb_MasterSendAnnounce, XAvb_MasterSendFollowUp, XAvb_MasterSendSync, XAvb_SendPDelayReq, XAvb_SendPDelayResp, XAvb_SendPDelayRespFollowUp.
void XAvb_MasterSendAnnounce(XAvb *InstancePtr)
A function to format then request the transmission of a PTP Announce Packet.
InstancePtr is a pointer to the XAvb instance to be worked on None. But the relevant Tx PTP Packet Buffer is written to with the updated PTP fields, and then the Tx PTP Packet Buffer Control Register is written to request the frame transmission. None.
References XAvb_Config::BaseAddress, XAvb::Config, XAvb_IncSequenceId, XAVB_PTP_TX_CONTROL_OFFSET, XAvb_ReadReg, XAVB_RTC_NANOSEC_VALUE_OFFSET, XAVB_RTC_SEC_LOWER_VALUE_OFFSET, XAvb_WaitOnTxPtpQueue, XAvb_WriteReg.
Referenced by XAvb_PtpTimerInterruptHandler.
void XAvb_MasterSendSync(XAvb *InstancePtr)
A function to format then request the transmission of a PTP Sync Packet.
InstancePtr is a pointer to the XAvb instance to be worked on None. But the relevant Tx PTP Packet Buffer is written to with the updated PTP fields, and then the Tx PTP Packet Buffer Control Register is written to request the frame transmission. None.
References XAvb_Config::BaseAddress, XAvb::Config, XAvb_PtpStruct::Nanosec, XAvb::PtpRecords, XAvb_IncSequenceId, XAVB_PTP_TX_CONTROL_OFFSET, XAvb_ReadPtpBuffer, XAvb_ReadReg, XAvb_ReorderWord, XAVB_RTC_NANOSEC_VALUE_OFFSET, XAVB_RTC_SEC_LOWER_VALUE_OFFSET, XAVB_RTC_SEC_UPPER_VALUE_OFFSET, XAvb_WaitOnTxPtpQueue, XAvb_WritePtpBuffer, XAvb_WriteReg.
Referenced by XAvb_PtpTimerInterruptHandler.
void XAvb_MasterSendFollowUp(XAvb *InstancePtr)
A function to format then request the transmission of a PTP Follow-Up Packet.
InstancePtr is a pointer to the XAvb instance to be worked on None. But the relevant Tx PTP Packet Buffer is written to with the updated PTP fields, and then the Tx PTP Packet Buffer Control Register is written to request the frame transmission. None.
References XAvb_Config::BaseAddress, XAvb::Config, XAvb_PtpStruct::Nanosec, XAvb::PtpRecords, XAVB_ONE_SECOND, XAVB_PTP_TX_CONTROL_OFFSET, XAvb_ReadPtpBuffer, XAvb_ReadReg, XAvb_ReorderWord, XAVB_RTC_NANOSEC_OFFSET, XAvb_WaitOnTxPtpQueue, XAvb_WritePtpBuffer, XAvb_WriteReg.
Referenced by XAvb_PtpTimerInterruptHandler.
void XAvb_SendPDelayReq(XAvb *InstancePtr)
A function to format then request the transmission of a PTP PDelay Request Packet.
InstancePtr is a pointer to the XAvb instance to be worked on None. But the relevant Tx PTP Packet Buffer is written to with the updated PTP fields, and then the Tx PTP Packet Buffer Control Register is written to request the frame transmission. None.
References XAvb_Config::BaseAddress, XAvb::Config, XAvb_SequenceIdStruct::PDelayReqSequenceId, XAvb_PtpStruct::PDelayTimestampT1, XAvb::PtpRecords, XAvb::SequenceIdRecords, XAvb_IncSequenceId, XAVB_PTP_TX_CONTROL_OFFSET, XAvb_ReadPtpBuffer, XAvb_ReorderWord, XAvb_WaitOnTxPtpQueue, XAvb_WriteReg.
Referenced by XAvb_PtpTimerInterruptHandler.
void XAvb_SendPDelayResp(XAvb *InstancePtr, u32 PtpFrameBaseAddr)
A function to format then request the transmission of a PTP PDelay Response Packet.
InstancePtr is a pointer to the XAvb instance to be worked on PtpFrameBaseAddr is the base address of the received Announce Packet in the Rx PTP Packet Buffer None. But the relevant Tx PTP Packet Buffer is written to with the updated PTP fields, and then the Tx PTP Packet Buffer Control Register is written to request the frame transmission. None.
References XAvb_Config::BaseAddress, XAvb::Config, XAvb_PtpStruct::NsOffsetForPDelayResp, XAvb::PtpRecords, XAVB_ONE_SECOND, XAVB_PTP_TX_CONTROL_OFFSET, XAvb_ReadPtpBuffer, XAvb_ReadReg, XAvb_ReorderWord, XAVB_RTC_NANOSEC_OFFSET, XAVB_RTC_NANOSEC_VALUE_OFFSET, XAVB_RTC_SEC_LOWER_VALUE_OFFSET, XAVB_RTC_SEC_UPPER_VALUE_OFFSET, XAvb_WaitOnTxPtpQueue, XAvb_WritePtpBuffer, XAvb_WriteReg.
Referenced by XAvb_PtpRxInterruptHandler.
void XAvb_SendPDelayRespFollowUp(XAvb *InstancePtr)
A function to format then request the transmission of a PTP PDelay Response Follow-Up Packet.
InstancePtr is a pointer to the XAvb instance to be worked on None. But the relevant Tx PTP Packet Buffer is written to with the updated PTP fields, and then the Tx PTP Packet Buffer Control Register is written to request the frame transmission. None.
References XAvb_Config::BaseAddress, XAvb::Config, XAvb_RtcFormat::NanoSeconds, XAvb_PtpStruct::NsOffsetForPDelayResp, XAvb::PtpRecords, XAvb_RtcFormat::SecondsLower, XAvb_RtcFormat::SecondsUpper, XAVB_ONE_SECOND, XAVB_PTP_TX_CONTROL_OFFSET, XAvb_ReadPtpBuffer, XAvb_ReadRtc, XAvb_ReorderWord, XAvb_WaitOnTxPtpQueue, XAvb_WritePtpBuffer, XAvb_WriteReg.
Referenced by XAvb_PtpRxInterruptHandler.
u32 XAvb_IsRxFramePTP(XAvb *InstancePtr, u32 PtpFrameBaseAddr)
A function to check that various fields in the received frame contain the expected values which define it as a valid AVB PTP frame.
If this check does not pass then the frame should not be decoded and used. InstancePtr is a pointer to the XAvb instance to be worked on PtpFrameBaseAddr is the base address of the received Announce Packet in the Rx PTP Packet Buffer An updated True/False decision as to whether this received frame really is a valid PTP type. None.
References XAvb_Config::BaseAddress, XAvb::Config, XAvb_ReadPtpBuffer, XAvb_ReorderWord.
Referenced by XAvb_PtpRxInterruptHandler.
void XAvb_DecodeRxSync(XAvb *InstancePtr, u32 PtpFrameBaseAddr)
A function to decode a received PTP Sync Packet.
InstancePtr is a pointer to the XAvb instance to be worked on PtpFrameBaseAddr is the base address of the received Announce Packet in the Rx PTP Packet Buffer None. None.
References XAvb_Config::BaseAddress, XAvb_PortIdentity::ClockIdentityLower, XAvb_PortIdentity::ClockIdentityUpper, XAvb::Config, XAvb_Counters::CounterSyncInterval, XAvb::CurrentBmc, XAvb_BmcData::IAmTheRtcMaster, XAvb::latestMDSyncReceive, XAvb_MDSyncReceive::logMessageInterval, XAvb_PortIdentity::PortNumber, XAvb::PtpCounters, XAvb::PtpRecords, XAvb::SequenceIdRecords, XAvb_PtpStruct::SlaveSyncTimestamp, XAvb_BmcData::SourcePortIdentity, XAvb_MDSyncReceive::SyncIntervalDuration, XAvb_SequenceIdStruct::SyncSequenceId, XAvb_ComparePortIdentity, XAvb_ConvertLogMeanToDuration, XAvb_GetPortIdentity, XAvb_ReadPtpBuffer, XAvb_ReorderWord.
Referenced by XAvb_PtpRxInterruptHandler.
void XAvb_DecodeRxFollowUp(XAvb *InstancePtr, u32 PtpFrameBaseAddr)
A function to decode a received PTP Follow-up Packet.
InstancePtr is a pointer to the XAvb instance to be worked on PtpFrameBaseAddr is the base address of the received Announce Packet in the Rx PTP Packet Buffer None. None.
References XAvb_Config::BaseAddress, XAvb::Config, XAvb_Counters::CounterSyncEvents, XAvb::CurrentBmc, XAvb_SequenceIdStruct::FollowUpSequenceId, XAvb_BmcData::IAmTheRtcMaster, XAvb_PtpStruct::MasterCorrectionField, XAvb_PtpStruct::NewMasterTime, XAvb_PtpStruct::NewSlaveTime, XAvb_SequenceIdStruct::NewSyncSequenceId, XAvb_PtpStruct::OldMasterTime, XAvb_PtpStruct::OldSlaveTime, XAvb_SequenceIdStruct::OldSyncSequenceId, XAvb::PtpCounters, XAvb::PtpRecords, XAvb::SequenceIdRecords, XAvb_BmcData::SourcePortIdentity, XAvb_SequenceIdStruct::SyncSequenceId, XAvb_CalcRtcOffset, XAvb_ComparePortIdentity, XAvb_GetPortIdentity, XAvb_ReadPtpBuffer, XAvb_ReorderWord, XAvb_UpdateRtcIncrement.
Referenced by XAvb_PtpRxInterruptHandler.
void XAvb_DecodeRxPDelayResp(XAvb *InstancePtr, u32 PtpFrameBaseAddr)
A function to decode a received PDelayResp Packet.
InstancePtr is a pointer to the XAvb instance to be worked on PtpFrameBaseAddr is the base address of the received Announce Packet in the Rx PTP Packet Buffer None. None.
References XAvb_Config::BaseAddress, XAvb::Config, XAvb_SequenceIdStruct::PDelayReqSequenceId, XAvb_SequenceIdStruct::PDelayRespSequenceId, XAvb_PtpStruct::PDelayTimestampT2, XAvb_PtpStruct::PDelayTimestampT4, XAvb::portIdLocal, XAvb::PtpRecords, XAvb_StateMachineData::rcvdPDelayResp, XAvb_StateMachineData::respPortIdentity, XAvb_StateMachineData::respReqPortIdentity, XAvb::SequenceIdRecords, XAvb::StateMachineData, XAvb_CaptureNanoSec, XAvb_ChangePeerASCapability, XAvb_ComparePortIdentity, XAvb_GetPortIdentity, XAvb_ReadPtpBuffer, XAvb_ReorderWord.
Referenced by XAvb_PtpRxInterruptHandler.
void XAvb_DecodeRxPDelayRespFollowUp(XAvb *InstancePtr, u32 PtpFrameBaseAddr)
A function to decode a received PDelayRespFollowUp Packet.
InstancePtr is a pointer to the XAvb instance to be worked on PtpFrameBaseAddr is the base address of the received Announce Packet in the Rx PTP Packet Buffer None. None.
References XAvb_Config::BaseAddress, XAvb::Config, XAvb_SequenceIdStruct::PDelayFollowUpSequenceId, XAvb_SequenceIdStruct::PDelayRespSequenceId, XAvb_PtpStruct::PDelayTimestampT3, XAvb::PtpRecords, XAvb_StateMachineData::rcvdPDelayResp, XAvb_StateMachineData::rcvdPDelayRespFollowUp, XAvb_StateMachineData::respPortIdentity, XAvb_StateMachineData::respReqPortIdentity, XAvb::SequenceIdRecords, XAvb::StateMachineData, XAvb_CalcDelay, XAvb_CaptureNanoSec, XAvb_ComparePortIdentity, XAvb_GetPortIdentity, XAvb_ReadPtpBuffer, XAvb_ReorderWord.
Referenced by XAvb_PtpRxInterruptHandler.
void XAvb_DecodeRxSignaling(XAvb *InstancePtr, u32 PtpFrameBaseAddr)
A function to decode a received Signalling Packet and modify the TX PTP Buffers based on the requested values.
InstancePtr is a pointer to the XAvb instance to be worked on PtpFrameBaseAddr is the base address of the received Signaling Packet in the Rx PTP Packet Buffer None. None.
References XAvb_SignallingFrameData::AnnounceIntervalDuration, XAvb_Config::BaseAddress, XAvb::Config, XAvb_SignallingFrameData::LinkDelayIntervalDuration, XAvb::SignallingFrameData, XAvb_SignallingFrameData::SyncIntervalDuration, XAvb_ReadPtpBuffer, XAvb_ReorderWord, XAvb_UpdateIntervalDuration, XAvb_UpdateLogMeanMessageInterval.
Referenced by XAvb_PtpRxInterruptHandler.
u16 XAvb_UpdateIntervalDuration(u16 currentIntervalDuration, char logMeanVal)
A function to update a PTP message Interval Duration (defined as a fraction of 128 seconds).
If the endpoint cannot support a requested logMeanVal then do not perform the conversion - return the current value. currentIntervalDuration is the Interval Duration to be updated logMeanVal is the base2 value that is to be converted logMeanVal represented as a fraction of 128 This endpoint only supports logMeanValues >=-7 and <=8.
References XAvb_ConvertLogMeanToDuration.
Referenced by XAvb_DecodeRxSignaling.
u16 XAvb_ConvertLogMeanToDuration(char logMeanVal)
A function to convert a logMean (power of 2) value into a fraction of 128 that is compatible with Signalling data.
logMeanVal is the base2 value that is to be converted logMeanVal represented as a fraction of 128 None.
Referenced by XAvb_DecodeRxAnnounceFrame, XAvb_DecodeRxSync, XAvb_Reset, XAvb_UpdateIntervalDuration.
char XAvb_ConvertDurationToLogMean(u16 fractionalVal)
A function to convert a fraction of 128 value that is compatible with Signalling data into a logMean (power of 2) value;.
fractionalVal is the Signalling data value that is to be converted fractionalVal represented as logMean (power of 2) value None.
Referenced by XAvb_UpdateLogMeanMessageInterval.
void XAvb_UpdateLogMeanMessageInterval(u32 BaseAddress, u32 PtpFrameBaseAddr, u16 intervalDuration)
A function to update the logMeanMessageInterval field in a PTP packet.
BaseAddress is the base address of the device PtpFrameBaseAddr is the base address of the TX PTP Buffer to be updated intervalDuration is the "fraction of 128" value of the data to be written None. But the relevant Tx PTP Packet Buffer is written to with the updated logMeanMessageInterval None.
References XAvb_ConvertDurationToLogMean, XAvb_ReadPtpBuffer, XAvb_WritePtpBuffer.
Referenced by XAvb_DecodeRxSignaling, XAvb_Reset.
void XAvb_SetupSourcePortIdentity(XAvb *InstancePtr, XAvb_PortIdentity systemIdentity)
This function updates the portIdLocal local copy of the sourcePortIdentity and writes this value into the TX PTP frame buffer templates.
The fields that are written are: o sourcePortIdentity for all default PTP frames o Announce:: grandmasterIdentity o Announce:: TLV clockIdentity InstancePtr is a pointer to the XAvb instance to be worked on systemIdentity is the clockIdentity and portNumber for this endpoint None. Announce::TLV. By default the tlvType and length field are set up in the BRAM, assuming that N = 1.
References XAvb_Config::BaseAddress, XAvb_PortIdentity::ClockIdentityLower, XAvb_PortIdentity::ClockIdentityUpper, XAvb::Config, XAvb::portIdLocal, XAvb_PortIdentity::PortNumber, XAvb_ReadPtpBuffer, XAvb_ReorderWord, XAvb_WritePtpBuffer, XAvb_WriteToMultipleTxPtpFrames.
Referenced by main.
void XAvb_DecodeTxAnnounceFrame(XAvb *InstancePtr)
A New Announce Packet has been written to this device to transmit.
We need to decode it and rerun the Best Master Clock Algorithm (BMCA) InstancePtr is a pointer to the XAvb instance to be worked on None. But an updated True/False decision as to whether this device should operate as a clock master or a slave is written into the CurrentBmc data structure. None.
References XAvb_Config::BaseAddress, XAvb_ClockQuality::clockClass, XAvb_ClockIdentity::ClockIdentityLower, XAvb_ClockIdentity::ClockIdentityUpper, XAvb_BmcData::ClockQuality, XAvb::Config, XAvb::CurrentBmc, XAvb_BmcData::GrandmasterIdentity, XAvb_BmcData::GrandmasterPriority1, XAvb_BmcData::GrandmasterPriority2, XAvb_BmcData::IAmTheRtcMaster, XAvb_BecomeRtcMaster, XAvb_BestMasterClockAlgorithm, XAvb_ReadAnnounceFrame, XAvb_UpdateBmcRecords.
Referenced by XAvb_DecodeRxAnnounceFrame, XAvb_Start.
void XAvb_DecodeRxAnnounceFrame(XAvb *InstancePtr, u32 PtpFrameBaseAddr)
A New Announce Packet has been received.
We need to decode it and rerun the Best Master Clock Algorithm (BMCA) InstancePtr is a pointer to the XAvb instance to be worked on PtpFrameBaseAddr is the base address of the received Announce Packet in the Rx PTP Packet Buffer None. But an updated True/False decision as to whether this device should operate as a clock master or a slave is written into the CurrentBmc data structure. None.
References XAvb_BmcData::AnnounceIntervalDuration, XAvb_Config::BaseAddress, XAvb_ClockQuality::clockClass, XAvb_ClockIdentity::ClockIdentityLower, XAvb_ClockIdentity::ClockIdentityUpper, XAvb_BmcData::ClockQuality, XAvb::Config, XAvb_Counters::CounterAnnounceInterval, XAvb::CurrentBmc, XAvb_BmcData::GrandmasterIdentity, XAvb_BmcData::GrandmasterPriority1, XAvb_BmcData::GrandmasterPriority2, XAvb_BmcData::IAmTheRtcMaster, XAvb_BmcData::logMessageInterval, XAvb::portIdLocal, XAvb::PtpCounters, XAvb_BmcData::SourcePortIdentity, XAvb_BmcData::stepsRemoved, XAvb_BecomeRtcSlave, XAvb_BestMasterClockAlgorithm, XAvb_CompareClockIdentity, XAvb_ComparePortIdentity, XAvb_ConvertLogMeanToDuration, XAvb_DecodeTxAnnounceFrame, XAvb_ReadAnnounceFrame, XAvb_ReadAnnounceReceiptTimeout, XAvb_UpdateBmcRecords.
Referenced by XAvb_PtpRxInterruptHandler.
void XAvb_ReadAnnounceFrame(u32 BaseAddress, u32 PtpFrameBaseAddr, XAvb_BmcData *AnnounceFrame)
A New Announce Packet is to be analyzed.
This function will read in the packet, decode it, and extract the relevant information fields to the "AnnounceFrame" data pointer. BaseAddress is the base address of the device PtpFrameBaseAddr is the base address of the received Announce Packet in the Rx PTP Packet Buffer AnnounceFrame is a pointer to a suitable data structure, designed to record the useful fields from the received Announce Packet The AnnounceFrame data structure is updated. None.
References XAvb_ClockQuality::clockAccuracy, XAvb_ClockQuality::clockClass, XAvb_PortIdentity::ClockIdentityLower, XAvb_ClockIdentity::ClockIdentityLower, XAvb_PortIdentity::ClockIdentityUpper, XAvb_ClockIdentity::ClockIdentityUpper, XAvb_BmcData::ClockQuality, XAvb_BmcData::GrandmasterIdentity, XAvb_BmcData::GrandmasterPriority1, XAvb_BmcData::GrandmasterPriority2, XAvb_ClockQuality::offsetScaledLogVariance, XAvb_BmcData::SourcePortIdentity, XAvb_BmcData::stepsRemoved, XAvb_GetPortIdentity, XAvb_ReadPtpBuffer, XAvb_ReorderWord.
Referenced by XAvb_BecomeRtcMaster, XAvb_DecodeRxAnnounceFrame, XAvb_DecodeTxAnnounceFrame.
void XAvb_ReadAnnounceReceiptTimeout(u32 BaseAddress, u32 PtpFrameBaseAddr, XAvb_BmcData *AnnounceFrame)
This function reads the logMessageinteval from an RX PTP Buffer and updates the AnnounceFrame struct with the value read.
BaseAddress is the base address of the device PtpFrameBaseAddr is the base address of the received Announce Packet in the Rx PTP Packet Buffer AnnounceFrame is a pointer to a suitable data structure, designed to record the useful fields from the received Announce Packet The AnnounceFrame data structure is updated. None.
References XAvb_BmcData::logMessageInterval, XAvb_ReadPtpBuffer, XAvb_ReorderWord.
Referenced by XAvb_DecodeRxAnnounceFrame.
void XAvb_UpdateBmcRecords(XAvb_BmcData *NewMaster, XAvb_BmcData *CurrentBmc)
This function will accept the data pointer to the current BMCA records, accept an equivalent pointer to a new (winning) Grand Masters Announce Packet information.
The CurrentBmc data structure is then updated with the information from the NewMaster. NewMaster is a pointer to a suitable data structure which has recorded the relevant Announce Packet fields of the new (winning) Grand Master. CurrentBmc is a pointer to a suitable data structure which has recorded the current fields of the current Grand Master's Announce Packet. The CurrentBmc data structure is updated. None.
References XAvb_PortIdentity::ClockIdentityLower, XAvb_ClockIdentity::ClockIdentityLower, XAvb_PortIdentity::ClockIdentityUpper, XAvb_ClockIdentity::ClockIdentityUpper, XAvb_BmcData::ClockQuality, XAvb_BmcData::GrandmasterIdentity, XAvb_BmcData::GrandmasterPriority1, XAvb_BmcData::GrandmasterPriority2, XAvb_PortIdentity::PortNumber, XAvb_BmcData::SourcePortIdentity, XAvb_BmcData::stepsRemoved.
Referenced by XAvb_BecomeRtcMaster, XAvb_DecodeRxAnnounceFrame, XAvb_DecodeTxAnnounceFrame.
u32 XAvb_BestMasterClockAlgorithm(XAvb_BmcData *AnnounceFrame, XAvb_BmcData *CurrentBmc)
This function will accept the data pointer to the current BMCA records, accept a pointer to an equivalent data structure for the new Announce Packet.
The Best Master Clock Algorithm (BMCA) is then performed on these two data structures by comparing the data fields CurrentBmc is a pointer to a suitable data structure, designed to record the current fields from the current Grand Master's Announce Packet. AnnounceFrame is a pointer to a suitable data structure, designed to record the useful fields from the received Announce Packet An updated True/False decision as to whether there is to be a change of Grand Master in the network. None.
References XAvb_ClockQuality::clockAccuracy, XAvb_ClockQuality::clockClass, XAvb_PortIdentity::ClockIdentityLower, XAvb_ClockIdentity::ClockIdentityLower, XAvb_PortIdentity::ClockIdentityUpper, XAvb_ClockIdentity::ClockIdentityUpper, XAvb_BmcData::ClockQuality, XAvb_BmcData::GrandmasterIdentity, XAvb_BmcData::GrandmasterPriority1, XAvb_BmcData::GrandmasterPriority2, XAvb_ClockQuality::offsetScaledLogVariance, XAvb_PortIdentity::PortNumber, XAvb_BmcData::SourcePortIdentity, XAvb_BmcData::stepsRemoved.
Referenced by XAvb_DecodeRxAnnounceFrame, XAvb_DecodeTxAnnounceFrame.
void XAvb_BecomeRtcMaster(XAvb *InstancePtr, u8 txAnnounceHasWon)
This function will make any adjustments needed when the node becomes the Grand Master, including resetting the RTC to its nominal value.
InstancePtr is a pointer to the XAvb instance to be worked on txAnnounceHasWon indicates that this function has been called from the function XAvb_DecodeTxAnnounceFrame(). Is this is set then this function has no need to repeat actions that have been already performed. None. None.
References XAvb_Config::BaseAddress, XAvb::Config, XAvb::CurrentBmc, XAvb::GMDiscCallBackRef, XAvb::GMDiscHandler, XAvb_BmcData::IAmTheRtcMaster, XAvb_ReadAnnounceFrame, XAVB_RTC_INCREMENT_NOMINAL_RATE, XAVB_RTC_INCREMENT_OFFSET, XAvb_UpdateBmcRecords, XAvb_WriteReg.
Referenced by XAvb_DecodeTxAnnounceFrame, XAvb_PtpTimerInterruptHandler, XAvb_Reset.
void XAvb_BecomeRtcSlave(XAvb *InstancePtr)
This function will make any adjustments needed when the node becomes a PTP slave.
InstancePtr is a pointer to the XAvb instance to be worked on None. None.
References XAvb_Counters::CounterSyncInterval, XAvb::CurrentBmc, XAvb::GMDiscCallBackRef, XAvb::GMDiscHandler, XAvb_BmcData::IAmTheRtcMaster, XAvb::PtpCounters.
Referenced by XAvb_DecodeRxAnnounceFrame.
void XAvb_ChangePTPLockStatus(XAvb *InstancePtr, u8 locked)
Operations needed when PTP locks or unlocks.
InstancePtr is a pointer to the XAvb instance to be worked on locked is 1 if changing to locked status, zero if unlocked None. None.
References XAvb::GMDiscCallBackRef, XAvb::GMDiscHandler, XAvb::PTPLocked, XAvb_ChangePeerASCapability.
Referenced by XAvb_UpdateRtcIncrement.
void XAvb_ChangePeerASCapability(XAvb *InstancePtr, u8 capable)
Operations needed when the peer's AS capability changes.
InstancePtr is a pointer to the XAvb instance to be worked on capable is 1 if the peer is ASCapable, 0 otherwise None. None.
References XAvb::PeerASCapable.
Referenced by XAvb_CalcDelay, XAvb_ChangePTPLockStatus, XAvb_DecodeRxPDelayResp, XAvb_PtpTimerInterruptHandler, XAvb_Reset, XAvb_Start.
void XAvb_SetGMDiscontinuityHandler(XAvb *InstancePtr, XAvb_Handler FuncPtr, void *CallBackRef)
This function sets the handler that will be called when a GM discontinuity event is identified by the driver.
The purpose of the handler is to allow application specific processing to be performed. InstancePtr is a pointer to the XAvb instance. FuncPtr is the pointer to the callback function. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. None. There is no assert on the CallBackRef since the driver doesn't know what it is (nor should it)
References XAvb::GMDiscCallBackRef, XAvb::GMDiscHandler, XAvb::IsReady.
Referenced by main.
u32 XAvb_CaptureNanoSec(u32 BaseAddress, u32 PtpFrameBaseAddr)
References XAvb_ReadPtpBuffer, XAvb_ReorderWord.
Referenced by XAvb_CalcRtcOffset, XAvb_DecodeRxPDelayResp, XAvb_DecodeRxPDelayRespFollowUp.
void XAvb_CalcDelay(XAvb *InstancePtr)
References XAvb_PtpStruct::LinkDelay, XAvb_PtpStruct::PDelayTimestampT1, XAvb_PtpStruct::PDelayTimestampT2, XAvb_PtpStruct::PDelayTimestampT3, XAvb_PtpStruct::PDelayTimestampT4, XAvb::PtpRecords, XAvb_ChangePeerASCapability, XAVB_NEIGHBOR_PROP_DELAY_THRESH, XAVB_ONE_SECOND.
Referenced by XAvb_DecodeRxPDelayRespFollowUp.
void XAvb_CalcRtcOffset(XAvb *InstancePtr, u32 PtpFrameBaseAddr)
References XAvb_Config::BaseAddress, XAvb::Config, XAvb_PtpStruct::LinkDelay, XAvb_PtpStruct::MasterCorrectionField, XAvb_RtcFormat::NanoSeconds, XAvb_PtpStruct::NewMasterTime, XAvb_PtpStruct::NewSlaveTime, XAvb::PtpRecords, XAvb_RtcFormat::SecondsLower, XAvb_RtcFormat::SecondsUpper, XAvb_PtpStruct::SlaveSyncTimestamp, XAvb_Adjust8kClock, XAvb_CaptureNanoSec, XAVB_ONE_SECOND, XAvb_ReadPtpBuffer, XAvb_ReadReg, XAvb_ReadRtc, XAvb_ReorderWord, XAVB_RTC_NANOSEC_OFFSET, XAVB_RTC_SEC_LOWER_VALUE_OFFSET, XAvb_WriteRtcOffset.
Referenced by XAvb_DecodeRxFollowUp.
void XAvb_UpdateRtcIncrement(XAvb *InstancePtr)
References XAvb_Config::BaseAddress, XAvb::Config, XAvb_PtpStruct::NewMasterTime, XAvb_PtpStruct::NewSlaveTime, XAvb_SequenceIdStruct::NewSyncSequenceId, XAvb_PtpStruct::OldMasterTime, XAvb_PtpStruct::OldSlaveTime, XAvb_SequenceIdStruct::OldSyncSequenceId, XAvb::PtpRecords, XAvb::SequenceIdRecords, XAvb_ChangePTPLockStatus, XAVB_CLOCK_LOCK_THRESHOLD, XAVB_ONE_SECOND, XAvb_ReadReg, XAVB_RTC_400PPM_OFFSET, XAVB_RTC_INCREMENT_NOMINAL_RATE, XAVB_RTC_INCREMENT_OFFSET, XAvb_WriteReg.
Referenced by XAvb_DecodeRxFollowUp.
void XAvb_Adjust8kClock(u32 BaseAddress, u32 NewOffset)
References XAVB_PERIOD_8KHZ, XAvb_ReadReg, XAVB_RTC_8K_OFFSET_OFFSET, XAVB_RTC_NANOSEC_OFFSET, XAvb_WriteReg.
Referenced by XAvb_CalcRtcOffset.