xaxiethernet_example_util.c
PHY_DETECT_REG
This function detects the PHY address by looking for successful MII status register contents (PHY register 1).
It looks for a PHY that supports auto-negotiation and 10Mbps full-duplex and half-duplex. So, this code won't work for PHYs that don't support those features, but it's a bit more general purpose than matching a specific PHY manufacturer ID.Note also that on some (older) Xilinx ML4xx boards, PHY address 0 does not properly respond to this query. But, since the default is 0 and assuming no other address responds, then it seems to work OK. The Axi Ethernet driver instance The address of the PHY (defaults to 0 if none detected) None.
PHY_DETECT_MASK
PHY_R0_CTRL_REG
Set PHY to loopback mode.
This works with the marvell PHY common on ML40x evaluation boards Speed is the loopback speed 10, 100, or 1000 Mbit
Referenced by AxiEthernetPingReqExample, AxiEthernetUtilConfigureInternalPhy, AxiEthernetUtilEnterLoopback.
PHY_R3_PHY_IDENT_REG
PHY_R0_RESET
PHY_R0_LOOPBACK
PHY_R0_ANEG_ENABLE
PHY_R0_DFT_SPD_MASK
PHY_R0_DFT_SPD_10
PHY_R0_DFT_SPD_100
PHY_R0_DFT_SPD_1000
PHY_R0_DFT_SPD_2500
PHY_R0_ISOLATE
PHY_R20_EXTND_CTRL_REG
PHY_R27_EXTND_STS_REG
PHY_R20_DFT_SPD_10
PHY_R20_DFT_SPD_100
PHY_R20_DFT_SPD_1000
PHY_R20_RX_DLY
PHY_R27_MAC_CONFIG_GMII
PHY_R27_MAC_CONFIG_MII
PHY_R27_MAC_CONFIG_RGMII
PHY_R27_MAC_CONFIG_SGMII
PHY_R22_PAGE_ADDR_REG
PHY_PG2_R21_CTRL_REG
PHY_REG21_10
PHY_REG21_100
PHY_REG21_1000
MARVEL_PHY_88E1111_MODEL
MARVEL_PHY_88E1116R_MODEL
PHY_MODEL_NUM_MASK
TI_PHY_IDENTIFIER
TI_PHY_MODEL
TI_PHY_CR
TI_PHY_PHYCTRL
TI_PHY_CR_SGMII_EN
TI_PHY_ADDDR
TI_PHY_CFGR2
TI_PHY_SGMIITYPE
TI_PHY_CFGR2_SGMII_AUTONEG_EN
TI_PHY_SGMIICLK_EN
TI_PHY_CR_DEVAD_EN
TI_PHY_CR_DEVAD_DATAEN
char AxiEthernetMAC[6][6]
void AxiEthernetUtilFrameHdrFormatMAC(EthernetFrame *FramePtr, char *DestAddr)
Set the MAC addresses in the frame.
FramePtr is the pointer to the frame. DestAddr is the Destination MAC address. None. None.
Referenced by AxiEthernetMultipleFramesIntrExample, AxiEthernetMultipleFramesPolledExample, AxiEthernetSgDmaFullChecksumOffloadExample, AxiEthernetSgDmaIntrCoalescingExample, AxiEthernetSgDmaIntrExtMulticastExample, AxiEthernetSgDmaIntrExtVlanExample, AxiEthernetSgDmaIntrMultiFrameExample, AxiEthernetSgDmaIntrSingleFrameExample, AxiEthernetSgDmaMultiFrameExample, AxiEthernetSgDmaPartialChecksumOffloadExample, AxiEthernetSgDmaSingleFrameExample, AxiEthernetSingleFrameIntrExample, AxiEthernetSingleFrameNonContIntrExample, AxiEthernetSingleFramePolledExample.
void AxiEthernetUtilFrameHdrFormatType(EthernetFrame *FramePtr, u16 FrameType)
Set the frame type for the specified frame.
FramePtr is the pointer to the frame. FrameType is the Type to set in frame. None. None.
Referenced by AxiEthernetMultipleFramesIntrExample, AxiEthernetMultipleFramesPolledExample, AxiEthernetSgDmaFullChecksumOffloadExample, AxiEthernetSgDmaIntrCoalescingExample, AxiEthernetSgDmaIntrExtMulticastExample, AxiEthernetSgDmaIntrMultiFrameExample, AxiEthernetSgDmaIntrSingleFrameExample, AxiEthernetSgDmaMultiFrameExample, AxiEthernetSgDmaPartialChecksumOffloadExample, AxiEthernetSgDmaSingleFrameExample, AxiEthernetSingleFrameIntrExample, AxiEthernetSingleFrameNonContIntrExample, AxiEthernetSingleFramePolledExample.
void AxiEthernetUtilFrameSetPayloadData(EthernetFrame *FramePtr, int PayloadSize)
This function places a pattern in the payload section of a frame.
The pattern is a 8 bit incrementing series of numbers starting with 0. Once the pattern reaches 256, then the pattern changes to a 16 bit incrementing pattern: 0, 1, 2, ... 254, 255, 00, 00, 00, 01, 00, 02, ... FramePtr is a pointer to the frame to change. PayloadSize is the number of bytes in the payload that will be set. None. None.
Referenced by AxiEthernetMultipleFramesIntrExample, AxiEthernetMultipleFramesPolledExample, AxiEthernetSgDmaFullChecksumOffloadExample, AxiEthernetSgDmaIntrCoalescingExample, AxiEthernetSgDmaIntrExtMulticastExample, AxiEthernetSgDmaIntrMultiFrameExample, AxiEthernetSgDmaIntrSingleFrameExample, AxiEthernetSgDmaMultiFrameExample, AxiEthernetSgDmaPartialChecksumOffloadExample, AxiEthernetSgDmaSingleFrameExample, AxiEthernetSingleFrameIntrExample, AxiEthernetSingleFramePolledExample.
void AxiEthernetUtilFrameHdrVlanFormatVid(EthernetFrame *FramePtr, u32 VlanNumber, u32 Vid)
Set the frame VLAN info for the specified frame.
FramePtr is the pointer to the frame. VlanNumber is the VlanValue insertion position to set in frame. Vid is the 4 bytes Vlan value (TPID, Priority, CFI, VID) to be set in frame. None. None.
Referenced by AxiEthernetSgDmaIntrExtVlanExample.
void AxiEthernetUtilFrameHdrVlanFormatType(EthernetFrame *FramePtr, u16 FrameType, u32 VlanNumber)
Set the frame type for the specified frame.
FramePtr is the pointer to the frame. FrameType is the Type to set in frame. VlanNumber is the VLAN friendly adjusted insertion position to set in frame. None. None.
Referenced by AxiEthernetSgDmaIntrExtVlanExample.
void AxiEthernetUtilFrameSetVlanPayloadData(EthernetFrame *FramePtr, int PayloadSize, u32 VlanNumber)
This function places a pattern in the payload section of a frame.
The pattern is a 8 bit incrementing series of numbers starting with 0. Once the pattern reaches 256, then the pattern changes to a 16 bit incrementing pattern: 0, 1, 2, ... 254, 255, 00, 00, 00, 01, 00, 02, ... FramePtr is a pointer to the frame to change. PayloadSize is the number of bytes in the payload that will be set. VlanNumber is the VLAN friendly adjusted insertion position to set in frame. None. None.
Referenced by AxiEthernetSgDmaIntrExtVlanExample.
int AxiEthernetUtilFrameVerify(EthernetFrame *CheckFrame, EthernetFrame *ActualFrame)
This function verifies the frame data against a CheckFrame.
Validation occurs by comparing the ActualFrame to the header of the CheckFrame. If the headers match, then the payload of ActualFrame is verified for the same pattern Util_FrameSetPayloadData() generates. CheckFrame is a pointer to a frame containing the 14 byte header that should be present in the ActualFrame parameter. ActualFrame is a pointer to a frame to validate. XST_SUCCESS if successful.XST_FAILURE in case of failure. None.
Referenced by AxiEthernetMultipleFramesIntrExample, AxiEthernetMultipleFramesPolledExample, AxiEthernetSgDmaIntrExample, AxiEthernetSgDmaIntrExtMulticastExample, AxiEthernetSgDmaIntrExtVlanExample, AxiEthernetSgDmaIntrSingleFrameExample, AxiEthernetSgDmaPollExample, AxiEthernetSingleFramePolledExample.
void AxiEthernetUtilFrameMemClear(EthernetFrame *FramePtr)
This function sets all bytes of a frame to 0.
FramePtr is a pointer to the frame itself. None. None.
Referenced by AxiEthernetMultipleFramesIntrExample, AxiEthernetSgDmaIntrExtMulticastExample, AxiEthernetSgDmaIntrExtVlanExample, AxiEthernetSgDmaIntrMultiFrameExample, AxiEthernetSgDmaIntrSingleFrameExample, AxiEthernetSgDmaMultiFrameExample, AxiEthernetSgDmaPartialChecksumOffloadExample, AxiEthernetSgDmaSingleFrameExample, AxiEthernetSingleFrameIntrExample, AxiEthernetSingleFrameNonContIntrExample, AxiEthernetSingleFramePolledExample.
u32 AxiEthernetDetectPHY(XAxiEthernet *AxiEthernetInstancePtr)
int AxiEthernetUtilEnterLoopback(XAxiEthernet *AxiEthernetInstancePtr, int Speed)
This function sets the PHY to loopback mode.
This works with the marvell PHY common on ML40x evaluation boards. AxiEthernetInstancePtr is a pointer to the instance of the AxiEthernet component. Speed is the loopback speed 10, 100, or 1000 Mbit. XST_SUCCESS if successful.XST_FAILURE, in case of failure.. None.
References AxiEthernetUtilConfigureInternalPhy, AxiEthernetUtilErrorTrap, AxiEthernetUtilPhyDelay, XAxiEthernet::Config, PHY_R0_CTRL_REG, XAxiEthernet_Config::PhyAddr, XAE_SPEED_1000_MBPS, XAE_SPEED_100_MBPS, XAE_SPEED_10_MBPS, XAE_SPEED_2500_MBPS, XAxiEthernet_Get_Phy_Interface.
Referenced by AxiEthernetExtVlanExample, AxiEthernetFifoIntrExample, AxiEthernetMcastExample, AxiEthernetPolledExample, AxiEthernetSgDmaIntrExample, AxiEthernetSgDmaPollExample.
void AxiEthernetUtilErrorTrap(char *Message)
This function is called by example code when an error is detected.
It can be set as a breakpoint with a debugger or it can be used to print out the given message if there is a UART or STDIO device. Message is the text explaining the error None None
Referenced by AxiEthernetExtVlanExample, AxiEthernetFifoIntrExample, AxiEthernetMcastExample, AxiEthernetMultipleFramesIntrExample, AxiEthernetMultipleFramesPolledExample, AxiEthernetPolledExample, AxiEthernetPollForRxStatus, AxiEthernetPollForTxStatus, AxiEthernetResetDevice, AxiEthernetSgDmaFullChecksumOffloadExample, AxiEthernetSgDmaIntrCoalescingExample, AxiEthernetSgDmaIntrExample, AxiEthernetSgDmaIntrExtMulticastExample, AxiEthernetSgDmaIntrExtVlanExample, AxiEthernetSgDmaIntrMultiFrameExample, AxiEthernetSgDmaIntrSingleFrameExample, AxiEthernetSgDmaMultiFrameExample, AxiEthernetSgDmaPartialChecksumOffloadExample, AxiEthernetSgDmaPollExample, AxiEthernetSgDmaSingleFrameExample, AxiEthernetSingleFrameIntrExample, AxiEthernetSingleFrameNonContIntrExample, AxiEthernetSingleFramePolledExample, AxiEthernetUtilConfigureInternalPhy, AxiEthernetUtilEnterLoopback, main.
void AxiEthernetUtilPhyDelay(unsigned int Seconds)
For Microblaze we use an assembly loop that is roughly the same regardless of optimization level, although caches and memory access time can make the delay vary.
Just keep in mind that after resetting or updating the PHY modes, the PHY typically needs time to recover.None None
Referenced by AxiEthernetExtVlanExample, AxiEthernetFifoIntrExample, AxiEthernetMcastExample, AxiEthernetPolledExample, AxiEthernetSgDmaIntrExample, AxiEthernetSgDmaPollExample, AxiEthernetUtilConfigureInternalPhy, AxiEthernetUtilEnterLoopback.
int AxiEthernetUtilConfigureInternalPhy(XAxiEthernet *AxiEthernetInstancePtr, int Speed)
This function configures the internal phy for SGMII and 1000baseX modes.
AxiEthernetInstancePtr is a pointer to the instance of the AxiEthernet component. Speed is the loopback speed 10, 100, or 1000 Mbit. XST_SUCCESS if successful.XST_FAILURE, in case of failure.. None.
References AxiEthernetUtilErrorTrap, AxiEthernetUtilPhyDelay, XAxiEthernet::Config, PHY_R0_CTRL_REG, XAxiEthernet_Config::PhyAddr, XAE_SPEED_1000_MBPS, XAE_SPEED_100_MBPS, XAE_SPEED_10_MBPS, XAE_SPEED_2500_MBPS.
Referenced by AxiEthernetUtilEnterLoopback.
int AxiEtherentConfigureTIPhy(XAxiEthernet *AxiEthernetInstancePtr, u32 PhyAddr)