xaxiethernet_example_polled.c
AXIETHERNET_DEVICE_ID
FIFO_DEVICE_ID
volatile int Padding
volatile int ExternalLoopback
EthernetFrame TxFrame
EthernetFrame RxFrame
XAxiEthernet AxiEthernetInstance
XLlFifo FifoInstance
int AxiEthernetPolledExample(u16 AxiEthernetDeviceId, u16 FifoDeviceId)
This function demonstrates the usage of the Axi Ethernet by sending and receiving frames in polled mode.
AxiEthernetDeviceId is device ID of the AxiEthernet Device , typically XPAR_<AXIETHERNET_instance>_DEVICE_ID value from xparameters.h FifoDeviceId is device ID of the Fifo device taken from xparameters.h -XST_SUCCESS to indicate success -XST_FAILURE to indicate failure AxiFifo hardware must be initialized before initializing AxiEthernet. Since AxiFifo reset line is connected to the AxiEthernet reset line, a reset of AxiFifo hardware during its initialization would reset AxiEthernet.
References XAxiEthernet_Config::AxiDevBaseAddress, AxiEthernetMultipleFramesPolledExample, AxiEthernetSingleFramePolledExample, AxiEthernetUtilEnterLoopback, AxiEthernetUtilErrorTrap, AxiEthernetUtilPhyDelay, XAxiEthernet_Config::BaseAddress, XAxiEthernet_CfgInitialize, XAxiEthernet_LookupConfig, XAxiEthernet_SetMacAddress, XAxiEthernet_SetOperatingSpeed.
Referenced by main.
int AxiEthernetSingleFramePolledExample(void)
This function demonstrates the usage of the Axi Ethernet by sending and receiving a single frame in polled mode.
None. -XST_SUCCESS to indicate success -XST_FAILURE to indicate failure None.
References AxiEthernetPollForRxStatus, AxiEthernetPollForTxStatus, AxiEthernetUtilErrorTrap, AxiEthernetUtilFrameHdrFormatMAC, AxiEthernetUtilFrameHdrFormatType, AxiEthernetUtilFrameMemClear, AxiEthernetUtilFrameSetPayloadData, AxiEthernetUtilFrameVerify, XAxiEthernet_Start, XAxiEthernet_Stop.
Referenced by AxiEthernetPolledExample.
int AxiEthernetMultipleFramesPolledExample(void)
This example uses polled mode to queue up multiple frames in the packet FIFOs before sending them in a single burst.
Receive packets are handled in a similar way. None. -XST_SUCCESS to indicate success -XST_FAILURE to indicate failure None.
References AxiEthernetPollForRxStatus, AxiEthernetPollForTxStatus, AxiEthernetResetDevice, AxiEthernetUtilErrorTrap, AxiEthernetUtilFrameHdrFormatMAC, AxiEthernetUtilFrameHdrFormatType, AxiEthernetUtilFrameSetPayloadData, AxiEthernetUtilFrameVerify, XAxiEthernet_Start, XAxiEthernet_Stop.
Referenced by AxiEthernetPolledExample.
int AxiEthernetPollForTxStatus(void)
This functions polls the Tx status and waits for an indication that a frame has been transmitted successfully or a transmit related error has occurred.
If an error is reported, it handles all the possible error conditions. None. XST_SUCCESS, Tx has completedXST_NO_DATA, Timeout. Tx failure.XST_FIFO_ERROR, Error in the FIFO. None.
References AxiEthernetResetDevice, AxiEthernetUtilErrorTrap.
Referenced by AxiEthernetMultipleFramesPolledExample, AxiEthernetSingleFramePolledExample.
int AxiEthernetPollForRxStatus(void)
This functions polls the Rx status and waits for an indication that a frame has arrived or a receive related error has occurred.
If an error is reported, handle all the possible error conditions. None. XST_SUCCESS, a frame has been receivedXST_NO_DATA, Timeout. Rx failure.XST_FIFO_ERROR, Error in the FIFO.XST_DATA_LOST, a frame has been dropped None.
References AxiEthernetResetDevice, AxiEthernetUtilErrorTrap, XAE_INT_RXFIFOOVR_MASK, XAE_INT_RXRJECT_MASK, XAxiEthernet_GetIntStatus.
Referenced by AxiEthernetMultipleFramesPolledExample, AxiEthernetSingleFramePolledExample.
int AxiEthernetResetDevice(void)
This function resets the device but preserves the options set by the user.
None. -XST_SUCCESS if reset is successful -XST_FAILURE. if reset is not successful None.
References AxiEthernetUtilErrorTrap, XAxiEthernet_ClearOptions, XAxiEthernet_GetMacAddress, XAxiEthernet_GetOptions, XAxiEthernet_Reset, XAxiEthernet_SetMacAddress, XAxiEthernet_SetOptions, XAxiEthernet_Stop.
Referenced by AxiEthernetFifoIntrExample, AxiEthernetMultipleFramesPolledExample, AxiEthernetPollForRxStatus, AxiEthernetPollForTxStatus.
int main(void)
This is the main function for the AxiEthernet example.
This function is not included if the example is generated from the TestAppGen test tool. None. -XST_SUCCESS to indicate success -XST_FAILURE to indicate failure None.
References AXIETHERNET_DEVICE_ID, AxiEthernetPolledExample, AxiEthernetUtilErrorTrap.