xaxiethernet.c
static void InitHw(XAxiEthernet *InstancePtr)
int XAxiEthernet_CfgInitialize(XAxiEthernet *InstancePtr, XAxiEthernet_Config *CfgPtr, UINTPTR EffectiveAddress)
XAxiEthernet_CfgInitialize initializes an AXI Ethernet device along with the InstancePtr that references it.
The PHY is setup independently from the Ethernet core. Use the MII or whatever other interface may be present for setup. InstancePtr references the memory instance to be associated with the AXI Ethernet core instance upon initialization. CfgPtr references the structure holding the hardware configuration for the Axi Ethernet core to initialize. EffectiveAddress is the processor address used to access the base address of the AXI Ethernet instance. In systems with an MMU and virtual memory, EffectiveAddress is the virtual address mapped to the physical in ConfigPtr->Config.BaseAddress. In systems without an active MMU, EffectiveAddress should be set to the same value as ConfigPtr->Config.BaseAddress. XST_SUCCESS. None.
References XAxiEthernet_Config::AxiDevBaseAddress, XAxiEthernet::AxiDevType, XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet_Config::IntrId, XAxiEthernet_Config::IntrParent, XAxiEthernet::IsReady, XAxiEthernet::PhyMode, XAxiEthernet_Config::PhyType, XAxiEthernet_Get_Phy_Interface, XAxiEthernet_Reset.
Referenced by AxiEthernetExtVlanExample, AxiEthernetFifoIntrExample, AxiEthernetMcastExample, AxiEthernetPingReqExample, AxiEthernetPolledExample, AxiEthernetSgDmaIntrExample, AxiEthernetSgDmaPollExample, main.
int XAxiEthernet_Initialize(XAxiEthernet *InstancePtr, XAxiEthernet_Config *CfgPtr, UINTPTR EffectiveAddress)
XAxiEthernet_Initialize initializes an AXI Ethernet device along with the InstancePtr that references it.
The PHY is setup independently from the Ethernet core. Use the MII or whatever other interface may be present for setup. InstancePtr references the memory instance to be associated with the AXI Ethernet core instance upon initialization. CfgPtr references the structure holding the hardware configuration for the Axi Ethernet core to initialize. EffectiveAddress is the processor address used to access the base address of the AXI Ethernet instance. In systems with an MMU and virtual memory, EffectiveAddress is the virtual address mapped to the physical in ConfigPtr->Config.BaseAddress. In systems without an active MMU, EffectiveAddress should be set to the same value as ConfigPtr->Config.BaseAddress. XST_SUCCESS. When user calls this function he should ensure the hardware is in a quiescent state by resetting all the hardware Configurations.
References XAxiEthernet_Config::AxiDevBaseAddress, XAxiEthernet::AxiDevType, XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet_Config::IntrId, XAxiEthernet_Config::IntrParent, XAxiEthernet::IsReady.
void XAxiEthernet_Start(XAxiEthernet *InstancePtr)
XAxiEthernet_Start starts the Axi Ethernet device as follows:
- Enable transmitter if XAE_TRANSMIT_ENABLE_OPTION is set - Enable receiver if XAE_RECEIVER_ENABLE_OPTION is set InstancePtr is a pointer to the Axi Ethernet instance to be worked on. None. None.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::IsStarted, XAxiEthernet::Options, XAE_RCW1_OFFSET, XAE_RCW1_RX_MASK, XAE_RECEIVER_ENABLE_OPTION, XAE_TC_OFFSET, XAE_TC_TX_MASK, XAE_TRANSMITTER_ENABLE_OPTION, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
Referenced by AxiEthernetMultipleFramesIntrExample, AxiEthernetMultipleFramesPolledExample, AxiEthernetPingReqExample, AxiEthernetSgDmaFullChecksumOffloadExample, AxiEthernetSgDmaIntrCoalescingExample, AxiEthernetSgDmaIntrExtMulticastExample, AxiEthernetSgDmaIntrExtVlanExample, AxiEthernetSgDmaIntrMultiFrameExample, AxiEthernetSgDmaIntrSingleFrameExample, AxiEthernetSgDmaMultiFrameExample, AxiEthernetSgDmaPartialChecksumOffloadExample, AxiEthernetSgDmaSingleFrameExample, AxiEthernetSingleFrameIntrExample, AxiEthernetSingleFrameNonContIntrExample, AxiEthernetSingleFramePolledExample.
void XAxiEthernet_Stop(XAxiEthernet *InstancePtr)
XAxiEthernet_Stop gracefully stops the Axi Ethernet device as follows:
- Disable all interrupts from this device - Disable the receiver XAxiEthernet_Stop does not modify any of the current device options.Since the transmitter is not disabled, frames currently in internal buffers or in process by a DMA engine are allowed to be transmitted. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. None None.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::IsStarted, XAE_IE_OFFSET, XAE_INT_RXRJECT_MASK, XAE_IP_OFFSET, XAE_IS_OFFSET, XAE_RCW1_OFFSET, XAE_RCW1_RX_MASK, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
Referenced by AxiEthernetExtVlanExample, AxiEthernetFifoIntrExample, AxiEthernetMcastExample, AxiEthernetMultipleFramesIntrExample, AxiEthernetMultipleFramesPolledExample, AxiEthernetResetDevice, AxiEthernetSgDmaFullChecksumOffloadExample, AxiEthernetSgDmaIntrCoalescingExample, AxiEthernetSgDmaIntrExample, AxiEthernetSgDmaIntrMultiFrameExample, AxiEthernetSgDmaIntrSingleFrameExample, AxiEthernetSgDmaMultiFrameExample, AxiEthernetSgDmaPartialChecksumOffloadExample, AxiEthernetSgDmaPollExample, AxiEthernetSgDmaSingleFrameExample, AxiEthernetSingleFrameIntrExample, AxiEthernetSingleFrameNonContIntrExample, AxiEthernetSingleFramePolledExample, XAxiEthernet_Reset.
void XAxiEthernet_Reset(XAxiEthernet *InstancePtr)
XAxiEthernet_Reset does not perform a soft reset of the AxiEthernet core.
AxiEthernet hardware is reset by the device connected to the AXI4-Stream interface. This function inserts some delay before proceeding to check for MgtRdy bit. The delay is necessary to be at a safe side. It takes a while for the reset process to complete and for any of the AxiEthernet registers to be accessed. It then checks for MgtRdy bit in IS register to know if AxiEthernet reset is completed or not. Subsequently it calls one more driver function to complete the AxiEthernet hardware initialization. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. It is the responsibility of the user to reset the AxiEthernet hardware before using it. AxiEthernet hardware should be reset through the device connected to the AXI4-Stream interface of AxiEthernet.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::Options, XAE_DEFAULT_OPTIONS, XAE_INT_MGTRDY_MASK, XAE_IS_OFFSET, XAE_RST_DEFAULT_TIMEOUT_VAL, XAxiEthernet_Stop.
Referenced by AxiEthernetResetDevice, XAxiEthernet_CfgInitialize.
int XAxiEthernet_SetMacAddress(XAxiEthernet *InstancePtr, void *AddressPtr)
XAxiEthernet_SetMacAddress sets the MAC address for the Axi Ethernet device, specified by InstancePtr to the MAC address specified by AddressPtr.
The Axi Ethernet device must be stopped before calling this function. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. AddressPtr is a reference to the 6-byte MAC address to set. XST_SUCCESS on successful completion.XST_DEVICE_IS_STARTED if the Axi Ethernet device has not stopped, This routine also supports the extended/new VLAN and multicast mode. The XAE_RAF_NEWFNCENBL_MASK bit dictates which offset will be configured.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::IsStarted, XAE_UAW0_OFFSET, XAE_UAW1_OFFSET, XAE_UAW1_UNICASTADDR_MASK, XAE_UAWL_OFFSET, XAE_UAWU_OFFSET, XAxiEthernet_IsExtFuncCap, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
Referenced by AxiEthernetExtVlanExample, AxiEthernetFifoIntrExample, AxiEthernetMcastExample, AxiEthernetPingReqExample, AxiEthernetPolledExample, AxiEthernetResetDevice, AxiEthernetSgDmaIntrExample, AxiEthernetSgDmaIntrExtMulticastExample, AxiEthernetSgDmaIntrMultiFrameExample, AxiEthernetSgDmaIntrSingleFrameExample, AxiEthernetSgDmaSingleFrameExample.
void XAxiEthernet_GetMacAddress(XAxiEthernet *InstancePtr, void *AddressPtr)
XAxiEthernet_GetMacAddress gets the MAC address for the Axi Ethernet, specified by InstancePtr into the memory buffer specified by AddressPtr.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. AddressPtr references the memory buffer to store the retrieved MAC address. This memory buffer must be at least 6 bytes in length. None. This routine also supports the extended/new VLAN and multicast mode. The XAE_RAF_NEWFNCENBL_MASK bit dictates which offset will be configured.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAE_UAW0_OFFSET, XAE_UAW1_OFFSET, XAE_UAWL_OFFSET, XAE_UAWU_OFFSET, XAxiEthernet_IsExtFuncCap, XAxiEthernet_ReadReg.
Referenced by AxiEthernetResetDevice.
static u32 XAxiEthernet_UpdateDepOptions(XAxiEthernet *InstancePtr)
XAxiEthernet_UpdateDepOption check and update dependent options for new/extended features.
This is a helper function that is meant to be called by XAxiEthernet_SetOptions() and XAxiEthernet_ClearOptions(). InstancePtr is a pointer to the Axi Ethernet instance to be worked on. Dependent options that are required to set/clear per hardware requirement. This helper function collects the dependent OPTION(s) per hardware design. When conflicts arises, extended features have precedence over legacy ones. Two operations to be considered, Adding extended options. If XATE_VLAN_OPTION is enabled and enable one of extended VLAN options, XATE_VLAN_OPTION should be off and configure to hardware. However, axi-ethernet instance Options variable still holds XATE_VLAN_OPTION so when all of the extended feature are removed, XATE_VLAN_OPTION can be effective and configured to hardware.Removing extended options. Remove extended option can not just remove the selected extended option and dependent options. All extended options need to be verified and remained when one or more extended options are enabled. Dependent options are : XAE_VLAN_OPTION,XAE_JUMBO_OPTIONXAE_FCS_INSERT_OPTION,XAE_FCS_STRIP_OPTIONXAE_PROMISC_OPTION.
int XAxiEthernet_SetOptions(XAxiEthernet *InstancePtr, u32 Options)
XAxiEthernet_SetOptions enables the options, Options for the Axi Ethernet, specified by InstancePtr.
Axi Ethernet should be stopped with XAxiEthernet_Stop() before changing options. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. Options is a bitmask of OR'd XAE_*_OPTION values for options to set. Options not specified are not affected. XST_SUCCESS on successful completion.XST_DEVICE_IS_STARTED if the device has not been stopped. See xaxiethernet.h for a description of the available options.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::IsStarted, XAxiEthernet::Options, XAE_BROADCAST_OPTION, XAE_DEFAULT_OPTIONS, XAE_FCC_FCRX_MASK, XAE_FCC_OFFSET, XAE_FCS_INSERT_OPTION, XAE_FCS_STRIP_OPTION, XAE_FLOW_CONTROL_OPTION, XAE_FMI_OFFSET, XAE_FMI_PM_MASK, XAE_JUMBO_OPTION, XAE_LENTYPE_ERR_OPTION, XAE_MULTICAST_OPTION, XAE_PROMISC_OPTION, XAE_RAF_BCSTREJ_MASK, XAE_RAF_EMULTIFLTRENBL_MASK, XAE_RAF_MCSTREJ_MASK, XAE_RAF_NEWFNCENBL_MASK, XAE_RAF_OFFSET, XAE_RAF_RXVSTRPMODE_MASK, XAE_RAF_RXVSTRPMODE_SHIFT, XAE_RAF_RXVTAGMODE_MASK, XAE_RAF_RXVTAGMODE_SHIFT, XAE_RAF_TXVSTRPMODE_MASK, XAE_RAF_TXVSTRPMODE_SHIFT, XAE_RAF_TXVTAGMODE_MASK, XAE_RAF_TXVTAGMODE_SHIFT, XAE_RCW1_FCS_MASK, XAE_RCW1_JUM_MASK, XAE_RCW1_LT_DIS_MASK, XAE_RCW1_OFFSET, XAE_RCW1_RX_MASK, XAE_RCW1_VLAN_MASK, XAE_RECEIVER_ENABLE_OPTION, XAE_TC_FCS_MASK, XAE_TC_JUM_MASK, XAE_TC_OFFSET, XAE_TC_TX_MASK, XAE_TC_VLAN_MASK, XAE_TRANSMITTER_ENABLE_OPTION, XAE_VLAN_OPTION, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
Referenced by AxiEthernetPingReqExample, AxiEthernetResetDevice, AxiEthernetSgDmaFullChecksumOffloadExample, AxiEthernetSgDmaIntrCoalescingExample, AxiEthernetSgDmaIntrExtMulticastExample, AxiEthernetSgDmaIntrExtVlanExample, AxiEthernetSgDmaIntrMultiFrameExample, AxiEthernetSgDmaIntrSingleFrameExample, AxiEthernetSgDmaMultiFrameExample, AxiEthernetSgDmaPartialChecksumOffloadExample, AxiEthernetSgDmaSingleFrameExample.
int XAxiEthernet_ClearOptions(XAxiEthernet *InstancePtr, u32 Options)
XAxiEthernet_ClearOptions clears the options, Options for the Axi Ethernet, specified by InstancePtr.
Axi Ethernet should be stopped with XAxiEthernet_Stop() before changing options. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. Options is a bitmask of OR'd XAE_*_OPTION values for options to clear. Options not specified are not affected. XST_SUCCESS on successful completion.XST_DEVICE_IS_STARTED if the device has not been stopped. See xaxiethernet.h for a description of the available options.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::IsStarted, XAxiEthernet::Options, XAE_BROADCAST_OPTION, XAE_FCC_FCRX_MASK, XAE_FCC_OFFSET, XAE_FCS_INSERT_OPTION, XAE_FCS_STRIP_OPTION, XAE_FLOW_CONTROL_OPTION, XAE_FMI_OFFSET, XAE_FMI_PM_MASK, XAE_JUMBO_OPTION, XAE_LENTYPE_ERR_OPTION, XAE_MULTICAST_OPTION, XAE_PROMISC_OPTION, XAE_RAF_BCSTREJ_MASK, XAE_RAF_EMULTIFLTRENBL_MASK, XAE_RAF_MCSTREJ_MASK, XAE_RAF_NEWFNCENBL_MASK, XAE_RAF_OFFSET, XAE_RAF_RXVSTRPMODE_MASK, XAE_RAF_RXVTAGMODE_MASK, XAE_RAF_TXVSTRPMODE_MASK, XAE_RAF_TXVTAGMODE_MASK, XAE_RCW1_FCS_MASK, XAE_RCW1_JUM_MASK, XAE_RCW1_LT_DIS_MASK, XAE_RCW1_OFFSET, XAE_RCW1_RX_MASK, XAE_RCW1_VLAN_MASK, XAE_RECEIVER_ENABLE_OPTION, XAE_TC_FCS_MASK, XAE_TC_JUM_MASK, XAE_TC_OFFSET, XAE_TC_TX_MASK, XAE_TC_VLAN_MASK, XAE_TRANSMITTER_ENABLE_OPTION, XAE_VLAN_OPTION, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
Referenced by AxiEthernetResetDevice, AxiEthernetSgDmaIntrCoalescingExample, AxiEthernetSgDmaIntrExtMulticastExample.
u32 XAxiEthernet_GetOptions(XAxiEthernet *InstancePtr)
XAxiEthernet_GetOptions returns the current option settings.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. Returns a bitmask of XAE_*_OPTION constants, each bit specifying an option that is currently active. See xaxiethernet.h for a description of the available options.
References XAxiEthernet::IsReady, XAxiEthernet::Options.
Referenced by AxiEthernetResetDevice.
u16 XAxiEthernet_GetOperatingSpeed(XAxiEthernet *InstancePtr)
XAxiEthernet_GetOperatingSpeed gets the current operating link speed.
This may be the value set by XAxiEthernet_SetOperatingSpeed() or a hardware default. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. Returns the link speed in units of megabits per second (10 / 100 / 1000). Can return a value of 0, in case it does not get a valid speed from EMMC. None.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAE_EMMC_LINKSPD_10, XAE_EMMC_LINKSPD_100, XAE_EMMC_LINKSPD_1000, XAE_EMMC_LINKSPEED_MASK, XAE_EMMC_OFFSET, XAE_SPEED_1000_MBPS, XAE_SPEED_100_MBPS, XAE_SPEED_10_MBPS, XAxiEthernet_ReadReg.
int XAxiEthernet_SetOperatingSpeed(XAxiEthernet *InstancePtr, u16 Speed)
XAxiEthernet_SetOperatingSpeed sets the current operating link speed.
For any traffic to be passed, this speed must match the current MII/GMII/SGMII/RGMII link speed. InstancePtr references the Axi Ethernet on which to operate. Speed is the speed to set in units of Mbps. Valid values are 10, 100, or 1000. - XST_SUCCESS on successful setting of speed. XST_FAILURE, if the speed cannot be set for the present hardware configuration. None.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAE_EMMC_LINKSPD_100, XAE_EMMC_LINKSPD_1000, XAE_EMMC_LINKSPEED_MASK, XAE_EMMC_OFFSET, XAE_SPEED_1000_MBPS, XAE_SPEED_100_MBPS, XAE_SPEED_10_MBPS, XAE_SPEED_2500_MBPS, XAxiEthernet_Get_Phy_Interface, XAxiEthernet_GetTemacType, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
Referenced by AxiEthernetExtVlanExample, AxiEthernetFifoIntrExample, AxiEthernetMcastExample, AxiEthernetPolledExample, AxiEthernetSgDmaIntrExample, AxiEthernetSgDmaPollExample.
void XAxiEthernet_SetBadFrmRcvOption(XAxiEthernet *InstancePtr)
XAxiEthernet_SetBadFrmRcvOption is used to enable the bad frame receive option.
If enabled, this option ensures that bad receive frames are allowed and passed to the AXI4-Stream interface as if they are good frames. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. None. None
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAE_RAF_OFFSET, XAE_RAF_RXBADFRMEN_MASK, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
void XAxiEthernet_ClearBadFrmRcvOption(XAxiEthernet *InstancePtr)
XAxiEthernet_ClearBadFrmRcvOption is used to disable the bad frame receive option.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. None. None.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAE_RAF_OFFSET, XAE_RAF_RXBADFRMEN_MASK, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
void XAxiEthernet_DisableControlFrameLenCheck(XAxiEthernet *InstancePtr)
XAxiEthernet_DisableControlFrameLenCheck is used to disable the length check for control frames (pause frames).
This means once the API is called, control frames larger than the minimum frame length are accepted. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. None. None.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAE_RCW1_CL_DIS_MASK, XAE_RCW1_OFFSET, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
void XAxiEthernet_EnableControlFrameLenCheck(XAxiEthernet *InstancePtr)
XAxiEthernet_EnableControlFrameLenCheck is used to enable the length check for control frames (pause frames).
After calling the API, all control frames received will be checked for proper length (less than minimum frame length). By default, upon normal start up, control frame length check is enabled. Hence this API needs to be called only if previously the control frame length check has been disabled by calling the API XAxiEthernet_DisableControlFrameLenCheck. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. None. None.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAE_RCW1_CL_DIS_MASK, XAE_RCW1_OFFSET, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
void XAxiEthernet_PhySetMdioDivisor(XAxiEthernet *InstancePtr, u8 Divisor)
XAxiEthernet_PhySetMdioDivisor sets the MDIO clock divisor in the Axi Ethernet,specified by InstancePtr to the value, Divisor.
This function must be called once after each reset prior to accessing MII PHY registers.From the Virtex-6(TM) and Spartan-6 (TM) Embedded Tri-Mode Ethernet MAC User's Guide, the following equation governs the MDIO clock to the PHY: f[HOSTCLK] f[MDC] = ----------------------- (1 + Divisor) * 2 where f[HOSTCLK] is the bus clock frequency in MHz, and f[MDC] is the MDIO clock frequency in MHz to the PHY. Typically, f[MDC] should not exceed 2.5 MHz. Some PHYs can tolerate faster speeds which means faster access. InstancePtr references the Axi Ethernet instance on which to operate. Divisor is the divisor value to set within the range of 0 to XAE_MDIO_MC_CLK_DVD_MAX. None.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAE_MDIO_MC_CLOCK_DIVIDE_MAX, XAE_MDIO_MC_MDIOEN_MASK, XAE_MDIO_MC_OFFSET, XAxiEthernet_WriteReg.
void XAxiEthernet_PhyRead(XAxiEthernet *InstancePtr, u32 PhyAddress, u32 RegisterNum, u16 *PhyDataPtr)
void XAxiEthernet_PhyWrite(XAxiEthernet *InstancePtr, u32 PhyAddress, u32 RegisterNum, u16 PhyData)
u8 XAxiEthernet_Get_Phy_Interface(XAxiEthernet *InstancePtr)
XAxiEthernet_Get_Phy_Interface returns the type of PHY interface being used by the given instance, specified by InstancePtr.
XAxiEthernet_GetPhysicalInterface returns the type of PHY interface being used by the given instance, specified by InstancePtr. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. The Physical Interface type which is one of XAE_PHY_TYPE_x where x is MII, GMII, RGMII_1_3, RGMII_2_0, SGMII, or 1000BASE_X (defined in xaxiethernet.h). C-style signature: int XAxiEthernet_Get_Phy_Interface(XAxiEthernet *InstancePtr) InstancePtr is a pointer to the Axi Ethernet instance to be worked on. The Physical Interface type which is one of XAE_PHY_TYPE_x where x is MII, GMII, RGMII_1_3, RGMII_2_0, SGMII, or 1000BASE_X (defined in xaxiethernet.h). C-style signature: int XAxiEthernet_GetPhysicalInterface(XAxiEthernet *InstancePtr)
References XAxiEthernet::Config, XAxiEthernet::PhyMode, XAxiEthernet_Config::PhyType.
Referenced by AxiEthernetExtVlanExample, AxiEthernetFifoIntrExample, AxiEthernetMcastExample, AxiEthernetSgDmaIntrExample, AxiEthernetSgDmaPollExample, AxiEthernetUtilEnterLoopback, XAxiEthernet_CfgInitialize, XAxiEthernet_GetRgmiiStatus, XAxiEthernet_GetSgmiiStatus, XAxiEthernet_SetOperatingSpeed.