xaxiethernet_mcdma_ping_req_example.c
XAXIETHERNET_BASEADDRESS
NUM_OF_PING_REQ_PKTS
RXBD_CNT
TXBD_CNT
BD_ALIGNMENT
ECHO_REPLY
HW_TYPE
ARP_REQUEST
ARP_REPLY
IDEN_NUM
IP_VERSION
BROADCAST_ADDR
CORRECT_CHECKSUM_VALUE
ARP_REQ_PKT_SIZE
ICMP_PKT_SIZE
IP_ADDR_SIZE
NUM_RX_PACK_CHECK_REQ
NUM_PACK_CHECK_RX_PACK
DELAY
SRC_MAC_ADDR_LOC
MAC_ADDR_LEN
ETHER_PROTO_TYPE_LOC
IP_ADDR_LEN
IP_START_LOC
IP_HEADER_INFO_LEN
IP_HEADER_LEN
IP_CHECKSUM_LOC
IP_REQ_SRC_IP_LOC
IP_REQ_DEST_IP_LOC
ICMP_KNOWN_DATA_LEN
ICMP_ECHO_FIELD_LOC
ICMP_DATA_START_LOC
ICMP_DATA_LEN
ICMP_DATA_CHECKSUM_LOC
ICMP_IDEN_FIELD_LOC
ICMP_DATA_LOC
ICMP_SEQ_NO_LOC
ICMP_DATA_FIELD_LEN
ICMP_KNOWN_DATA_LOC
ARP_REQ_STATUS_LOC
ARP_REQ_SRC_IP_LOC
RXBD_SPACE_BYTES
TXBD_SPACE_BYTES
XAE_ETHER_PROTO_TYPE_IP
IP Protocol.
Referenced by ProcessRecvFrame, SendArpReqFrame, SendEchoReqFrame.
XAE_ETHER_PROTO_TYPE_ARP
ARP Protocol.
Referenced by ProcessRecvFrame, SendArpReqFrame.
XAE_ETHER_PROTO_TYPE_VLAN
VLAN Tagged.
XAE_ARP_PACKET_SIZE
Max ARP packet size.
XAE_HEADER_IP_LENGTH_OFFSET
IP Length Offset.
XAE_VLAN_TAG_SIZE
VLAN Tag Size.
PHY_R0_CTRL_REG
PHY_R3_PHY_IDENT_REG
PHY_R0_RESET
PHY_R0_LOOPBACK
PHY_R0_ANEG_ENABLE
PHY_R0_DFT_SPD_MASK
PHY_R0_DFT_SPD_10
PHY_R0_DFT_SPD_100
PHY_R0_DFT_SPD_1000
PHY_R0_ISOLATE
PHY_R20_EXTND_CTRL_REG
PHY_R27_EXTND_STS_REG
PHY_R20_DFT_SPD_10
PHY_R20_DFT_SPD_100
PHY_R20_DFT_SPD_1000
PHY_R20_RX_DLY
PHY_R27_MAC_CONFIG_GMII
PHY_R27_MAC_CONFIG_MII
PHY_R27_MAC_CONFIG_RGMII
PHY_R27_MAC_CONFIG_SGMII
PHY_R22_PAGE_ADDR_REG
PHY_PG2_R21_CTRL_REG
PHY_REG21_10
PHY_REG21_100
PHY_REG21_1000
MARVEL_PHY_88E1111_MODEL
MARVEL_PHY_88E1116R_MODEL
PHY_MODEL_NUM_MASK
TI_PHY_IDENTIFIER
TI_PHY_MODEL
TI_PHY_CR
TI_PHY_PHYCTRL
TI_PHY_CR_SGMII_EN
TI_PHY_ADDDR
TI_PHY_CFGR2
TI_PHY_SGMIITYPE
TI_PHY_CFGR2_SGMII_AUTONEG_EN
TI_PHY_SGMIICLK_EN
TI_PHY_CR_DEVAD_EN
TI_PHY_CR_DEVAD_DATAEN
typedef unsigned char EthernetFrame[XAE_MAX_JUMBO_FRAME_SIZE][XAE_MAX_JUMBO_FRAME_SIZE]
volatile int ExternalLoopback
u8 LocalMacAddr[6][6]
u8 LocalIpAddress[IP_ADDR_SIZE][IP_ADDR_SIZE]
u8 DestIpAddress[IP_ADDR_SIZE][IP_ADDR_SIZE]
u16 DestMacAddr[MAC_ADDR_LEN][MAC_ADDR_LEN]
XAxiEthernet AxiEthernetInstance
XMcdma DmaInstance
u16 IcmpData[ICMP_KNOWN_DATA_LEN][ICMP_KNOWN_DATA_LEN]
u16 IpHeaderInfo[IP_HEADER_INFO_LEN][IP_HEADER_INFO_LEN]
u8 RxFrame[NUM_OF_PING_REQ_PKTS *XAE_JUMBO_MTU][NUM_OF_PING_REQ_PKTS *XAE_JUMBO_MTU]
u8 TxFrame[NUM_OF_PING_REQ_PKTS *XAE_JUMBO_MTU][NUM_OF_PING_REQ_PKTS *XAE_JUMBO_MTU]
char RxBdSpace[RXBD_SPACE_BYTES][RXBD_SPACE_BYTES]
char TxBdSpace[TXBD_SPACE_BYTES][TXBD_SPACE_BYTES]
volatile u32 RecvFrameLength
UINTPTR TxBuffPtr
UINTPTR RxBuffPtr
volatile int FramesTx
volatile int FramesRx
volatile int TxCount
volatile int RxCount
volatile int Padding
int SeqNum
int NumOfPingReqPkts
int Mcdma_ChanId
int AxiEthernetPingReqExample(XAxiEthernet *AxiEthernetInstancePtr, XMcdma *DmaInstancePtr, UINTPTR AxiEthernetBaseAddress)
The entry point for the AxiEthernet driver to ping request example in polled mode.
This function will generate specified number of request packets as defined in "NUM_OF_PING_REQ_PKTS. AxiEthernetInstancePtr is a pointer to the instance of the AxiEthernet component. DmaInstancePtr is a pointer to the instance of the AXI MCDMA component. AxiEthernetBaseAddress contains the base address of the AxiEthernet device XST_FAILURE to indicate failure, otherwise it will return XST_SUCCESS. AxiMcdma hardware must be initialized before initializing AxiEthernet. Since AxiMcdma reset line is connected to the AxiEthernet reset line, a reset of AxiMcdma hardware during its initialization would reset AxiEthernet.
References XAxiEthernet_Config::AxiDevBaseAddress, XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet_Config::Enable_1588, PHY_R0_CTRL_REG, XAxiEthernet_Config::PhyAddr, ProcessRecvFrame, SendArpReqFrame, SendEchoReqFrame, XAE_RECEIVER_ENABLE_OPTION, XAE_TRANSMITTER_ENABLE_OPTION, XAxiEthernet_CfgInitialize, XAxiEthernet_LookupConfig, XAxiEthernet_SetMacAddress, XAxiEthernet_SetOptions, XAxiEthernet_Start.
Referenced by main.
void SendArpReqFrame(XAxiEthernet *AxiEthernetInstancePtr, XMcdma *DmaInstancePtr, u8 ChanId)
This function will send a ARP request packet.
AxiEthernetInstancePtr is a pointer to the instance of the Axi Ethernet component. DmaInstancePtr is a pointer to the instance of the Dma component. ChanId is the MCDMA Channel number to be operate on. None. None.
References XAE_ETHER_PROTO_TYPE_ARP, XAE_ETHER_PROTO_TYPE_IP.
Referenced by AxiEthernetPingReqExample.
void SendEchoReqFrame(XAxiEthernet *AxiEthernetInstancePtr, XMcdma *DmaInstancePtr, u8 ChanId)
This function will send a Echo request packet.
AxiEthernetInstancePtr is a pointer to the instance of the Axi Ethernet component. DmaInstancePtr is a pointer to the instance of the Dma component. ChanId is the MCDMA Channel number to be operate on. None. None.
References XAE_ETHER_PROTO_TYPE_IP.
Referenced by AxiEthernetPingReqExample, ProcessRecvFrame.
int ProcessRecvFrame(XAxiEthernet *AxiEthernetInstancePtr, XMcdma *DmaInstancePtr, u8 ChanId)
This function will process the received packet.
This function sends the echo request packet based on the ARP reply packet. AxiEthernetInstancePtr is a pointer to the instance of the Axi Ethernet component. DmaInstancePtr is a pointer to the instance of the Dma component. ChanId is the MCDMA Channel number to be operate on. XST_SUCCESS is returned when an echo reply is received. Otherwise, XST_FAILURE is returned. This assumes MAC does not strip padding or CRC.
References SendEchoReqFrame, XAE_ETHER_PROTO_TYPE_ARP, XAE_ETHER_PROTO_TYPE_IP.
Referenced by AxiEthernetPingReqExample.
int XAxienet_Send(XAxiEthernet *AxiEthernetInstancePtr, XMcdma *DmaInstancePtr, u8 ChanId, UINTPTR TxFrame, u32 len)
int XAxiEnet_Recv(XMcdma *DmaInstancePtr)
int PhySetup(XAxiEthernet *AxiEthernetInstancePtr)
int RxSetup(XMcdma *McDmaInstPtr, XAxiEthernet *AxiEthernetInstancePtr, u8 ChanId, u32 NumPkts)
static u16 CheckSumCalculation(u16 *RxFramePtr, int StartLoc, int Length)
This function calculates the checksum and returns a 16 bit result.
RxFramePtr is a 16 bit pointer for the data to which checksum is to be calculated. StartLoc is the starting location of the data from which the checksum has to be calculated. Length is the number of halfwords(16 bits) to which checksum is to be calculated. It returns a 16 bit checksum value. This can also be used for calculating checksum. The ones complement of this return value will give the final checksum.
static int CompareData(u16 *LhsPtr, u16 *RhsPtr, int LhsLoc, int RhsLoc, int Count)
This function checks the match for the specified number of half words.
LhsPtr is a LHS entity pointer. RhsPtr is a RHS entity pointer. LhsLoc is a LHS entity location. RhsLoc is a RHS entity location. Count is the number of location which has to compared. XST_SUCCESS is returned when both the entities are same, otherwise XST_FAILURE is returned. None.
static int RxBdSetup(XMcdma *McDmaInstPtr, XAxiEthernet *AxiEthernetInstancePtr)
This function setup the buffer descriptor chain for the Ingress mcdma Channels.
DmaInstancePtr is a pointer to the instance of the Dma component. AxiEthernetInstancePtr is a pointer to the instance of the Axi Ethernet component. -XST_SUCCESS to indicate success -XST_FAILURE to indicate failure
static int TxBdSetup(XMcdma *McDmaInstPtr, XAxiEthernet *AxiEthernetInstancePtr)
This function setup the buffer descriptor chain for the Egress Channels.
DmaInstancePtr is a pointer to the instance of the Dma component. AxiEthernetInstancePtr is a pointer to the instance of the Axi Ethernet component. -XST_SUCCESS to indicate success -XST_FAILURE to indicate failure
int main()
This function is the main function of the Ping Request example in polled mode.
None. XST_FAILURE to indicate failure, otherwise it will return XST_SUCCESS after sending specified number of packets as defined in "NUM_OF_PING_REQ_PKTS" . None.
References AXIETHERNET_DEVICE_ID, AxiEthernetPingReqExample.
static void PollTxData(XMcdma *McDmaInstPtr, u16 Chan_id)
int CheckTxDmaResult(XMcdma *InstancePtr)
static int PollRxData(XMcdma *McDmaInstPtr, u32 Chan_id)
int GetBufAddr()
int GetRxBufAddr()