xaxiethernet_example_intr_mcdma.c
XAXIETHERNET_BASEADDRESS
RXBD_CNT
TXBD_CNT
BD_ALIGNMENT
PAYLOAD_SIZE
BD_USR0_OFFSET
BD_USR1_OFFSET
BD_USR2_OFFSET
PARTIAL_CSUM_ENABLE
FULL_CSUM_ENABLE
TX_CS_INIT_OFFSET
RCV_FRM_NOT_CORRUPTED
IP_VERSION_4
IP_HEADER_VERSION
IP_HEADER_LEN_IN_WORDS
IP_HEADER_LENGTH
IP_HEADER_PROTOCOL_TCP
IP_HEADER_PROTOCOL_UDP
TCP_HEADER_LEN_IN_WORDS
TCP_HEADER_LENGTH
FULL_CSUM_STATUS_MASK
FULL_CSUM_VALIDATED
IP_TCP_CSUMS_NOT_CHECKED
IP_CSUM_OK_TCP_NOT_CHECKED
TCP_CSUM_NOT_CHECKED_IP_NOT_OK
IP_CSUM_OK_TCP_NOT_OK
DUMMY_TCP_PORT_1
DUMMY_TCP_PORT_2
RXBD_SPACE_BYTES
TXBD_SPACE_BYTES
BLOCK_SIZE_2MB
EthernetFrame TxFrame
EthernetFrame RxFrame
XAxiEthernet AxiEthernetInstance
XMcdma DmaInstance
char RxBdSpace[RXBD_SPACE_BYTES][RXBD_SPACE_BYTES]
char TxBdSpace[TXBD_SPACE_BYTES][TXBD_SPACE_BYTES]
volatile int FramesRx
volatile int FramesTx
volatile int DeviceErrors
volatile int Padding
volatile int ExternalLoopback
volatile int Hascsum
int AxiEthernetSgDmaIntrExample(XAxiEthernet *AxiEthernetInstancePtr, XMcdma *DmaInstancePtr, UINTPTR AxiEthernetBaseAddress)
This function demonstrates the usage usage of the Axi Ethernet by sending and receiving frames in interrupt driven MCDMA mode.
AxiEthernetInstancePtr is a pointer to the instance of the AxiEthernet component. DmaInstancePtr is a pointer to the instance of the AXI MCDMA component. AxiEthernetBaseAddress contains the base address of the AxiEthernet device -XST_SUCCESS to indicate success -XST_FAILURE to indicate failure AxiMcdma hardware must be initialized before initializing AxiEthernet. Since AxiMcdma reset line is connected to the AxiEthernet reset line, a reset of AxiMcdma hardware during its initialization would reset AxiEthernet.In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XAxiEthernet_Config::AxiDevBaseAddress, AxiEthernetSgDmaFullChecksumOffloadExample, AxiEthernetSgDmaIntrMultiFrameExample, AxiEthernetSgDmaIntrSingleFrameExample, AxiEthernetSgDmaPartialChecksumOffloadExample, AxiEthernetUtilEnterLoopback, AxiEthernetUtilErrorTrap, AxiEthernetUtilFrameVerify, AxiEthernetUtilPhyDelay, XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet_Config::Enable_1588, XAxiEthernet_Config::IntrId, XAxiEthernet_Config::IntrParent, XAxiEthernet_Config::Speed, XAE_INT_RXFIFOOVR_MASK, XAE_INT_RXRJECT_MASK, XAxiEthernet_CfgInitialize, XAxiEthernet_Get_Phy_Interface, XAxiEthernet_IntClear, XAxiEthernet_IntPending, XAxiEthernet_IsRxFullCsum, XAxiEthernet_IsRxPartialCsum, XAxiEthernet_IsRxVlanStrp, XAxiEthernet_IsRxVlanTag, XAxiEthernet_IsRxVlanTran, XAxiEthernet_IsTxFullCsum, XAxiEthernet_IsTxPartialCsum, XAxiEthernet_IsTxVlanStrp, XAxiEthernet_IsTxVlanTag, XAxiEthernet_IsTxVlanTran, XAxiEthernet_LookupConfig, XAxiEthernet_SetOperatingSpeed, XAxiEthernet_Stop.
Referenced by main.
int AxiEthernetSgDmaIntrSingleFrameExample(XAxiEthernet *AxiEthernetInstancePtr, XMcdma *DmaInstancePtr, u8 ChanId)
This function demonstrates the usage of the Axi Ethernet by sending and receiving a single frame in SGDMA interrupt mode.
The source packet will be described by two descriptors. It will be received into a buffer described by a single descriptor. AxiEthernetInstancePtr is a pointer to the instance of the Axi Ethernet component. DmaInstancePtr is a pointer to the instance of the Dma component. ChanId is the MCDMA Channel number to be operate on. -XST_SUCCESS to indicate success -XST_FAILURE to indicate failure None.
References AxiEthernetUtilErrorTrap, AxiEthernetUtilFrameHdrFormatMAC, AxiEthernetUtilFrameHdrFormatType, AxiEthernetUtilFrameMemClear, AxiEthernetUtilFrameSetPayloadData, XAE_RECEIVER_ENABLE_OPTION, XAE_TRANSMITTER_ENABLE_OPTION, XAxiEthernet_SetMacAddress, XAxiEthernet_SetOptions, XAxiEthernet_Start, XAxiEthernet_Stop.
Referenced by AxiEthernetSgDmaIntrExample.
int AxiEthernetSgDmaIntrMultiFrameExample(XAxiEthernet *AxiEthernetInstancePtr, XMcdma *DmaInstancePtr, u8 ChanId)
This function demonstrates the usage of the Axi Ethernet by sending and receiving a multiple frames in MCDMA interrupt mode.
Each source packet will be described by two descriptors. It will be received into a buffer described by a single descriptor. AxiEthernetInstancePtr is a pointer to the instance of the Axi Ethernet component. DmaInstancePtr is a pointer to the instance of the Dma component. ChanId is the MCDMA Channel number to be operate on. -XST_SUCCESS to indicate success -XST_FAILURE to indicate failure None.
References AxiEthernetUtilErrorTrap, AxiEthernetUtilFrameHdrFormatMAC, AxiEthernetUtilFrameHdrFormatType, AxiEthernetUtilFrameMemClear, AxiEthernetUtilFrameSetPayloadData, XAE_RECEIVER_ENABLE_OPTION, XAE_TRANSMITTER_ENABLE_OPTION, XAxiEthernet_SetMacAddress, XAxiEthernet_SetOptions, XAxiEthernet_Start, XAxiEthernet_Stop.
Referenced by AxiEthernetSgDmaIntrExample.
int AxiEthernetSgDmaPartialChecksumOffloadExample(XAxiEthernet *AxiEthernetInstancePtr, XMcdma *DmaInstancePtr, u8 ChanId)
This example sends and receives a single packet in loopback mode with checksum offloading support.
The transmit frame will be che cksummed over the entire Ethernet payload and inserted into the last 2 bytes of the frame.On receive, HW should calculate the Ethernet payload checksum and return a value of 0xFFFF which means the payload data was likely not corrupted. AxiEthernetInstancePtr is a pointer to the instance of the AxiEthernet component. DmaInstancePtr is a pointer to the instance of the Dma component. ChanId is the MCDMA Channel number to be operate on. -XST_SUCCESS to indicate success -XST_FAILURE to indicate failure None. The transmit frame will be che cksummed over the entire Ethernet payload and inserted into the last 2 bytes of the frame.On receive, HW should calculate the Ethernet payload checksum and return a value of 0xFFFF which means the payload data was likely not corrupted. AxiEthernetInstancePtr is a pointer to the instance of the AxiEthernet component. DmaInstancePtr is a pointer to the instance of the Dma component. -XST_SUCCESS to indicate success -XST_FAILURE to indicate failure None.
References AxiEthernetUtilErrorTrap, AxiEthernetUtilFrameHdrFormatMAC, AxiEthernetUtilFrameHdrFormatType, AxiEthernetUtilFrameMemClear, AxiEthernetUtilFrameSetPayloadData, XAE_INT_RECV_ERROR_MASK, XAE_RECEIVER_ENABLE_OPTION, XAE_TRANSMITTER_ENABLE_OPTION, XAxiEthernet_IntEnable, XAxiEthernet_IsRxPartialCsum, XAxiEthernet_IsTxPartialCsum, XAxiEthernet_SetOptions, XAxiEthernet_Start, XAxiEthernet_Stop.
Referenced by AxiEthernetSgDmaIntrExample, AxiEthernetSgDmaPollExample.
int AxiEthernetSgDmaFullChecksumOffloadExample(XAxiEthernet *AxiEthernetInstancePtr, XMcdma *DmaInstancePtr, u8 ChanId)
This example sends and receives a single packet in loopback mode with full checksum offloading support.
An Ethernet frame is formed with IP header, TCP header and payload. The hardware calculates the IP Header checksum and populates it at the appropriate location in the IP header. Similarly, the hardware calculates the TCP Pseudo header from IP header and calculates TCP checksum for TCP Pseudo header, TCP header and TCP payload. It then populates the checksum in the TCP header. The Ethernet frame is then looped back and received. The hardware validates the IP header checksum and the TCP checksum. The example retrieves the checksum validation information from the AXI4- Stream Appword2. AxiEthernetInstancePtr is a pointer to the instance of the AxiEthernet component. DmaInstancePtr is a pointer to the instance of the Dma component. ChanId is the MCDMA Channel number to be operate on. -XST_SUCCESS to indicate success -XST_FAILURE to indicate failure None. An Ethernet frame is formed with IP header, TCP header and payload. The hardware calculates the IP Header checksum and populates it at the appropriate location in the IP header. Similarly, the hardware calculates the TCP Pseudo header from IP header and calculates TCP checksum for TCP Pseudo header, TCP header and TCP payload. It then populates the checksum in the TCP header. The Ethernet frame is then looped back and received. The hardware validates the IP header checksum and the TCP checksum. The example retrieves the checksum validation information from the AXI4- Stream Appword2. AxiEthernetInstancePtr is a pointer to the instance of the AxiEthernet component. DmaInstancePtr is a pointer to the instance of the Dma component. -XST_SUCCESS to indicate success -XST_FAILURE to indicate failure None.
References AxiEthernetUtilErrorTrap, AxiEthernetUtilFrameHdrFormatMAC, AxiEthernetUtilFrameHdrFormatType, AxiEthernetUtilFrameSetPayloadData, XAE_INT_RECV_ERROR_MASK, XAE_RECEIVER_ENABLE_OPTION, XAE_TRANSMITTER_ENABLE_OPTION, XAxiEthernet_IntEnable, XAxiEthernet_SetOptions, XAxiEthernet_Start, XAxiEthernet_Stop.
Referenced by AxiEthernetSgDmaIntrExample, AxiEthernetSgDmaPollExample.
static int RxBdSetup(XMcdma *McDmaInstPtr, XAxiEthernet *AxiEthernetInstancePtr, XAxiEthernet_Config *MacCfgPtr)
This function setup the buffer descriptor chain for the Ingress mcdma Channels.
McDmaInstancePtr is a pointer to the instance of the Dma component. AxiEthernetInstancePtr is a pointer to the instance of the Axi Ethernet component. MacCfgPtr is a pointer to the config instance of the Axi Ethernet component. AxiEthernetIntrId is interrupt Id of the MAC instance. -XST_SUCCESS to indicate success -XST_FAILURE to indicate failure
static int TxBdSetup(XMcdma *McDmaInstPtr, XAxiEthernet *AxiEthernetInstancePtr, XAxiEthernet_Config *MacCfgPtr)
This function setup the buffer descriptor chain for the Egress mcdma Channels.
McDmaInstancePtr is a pointer to the instance of the Dma component. AxiEthernetInstancePtr is a pointer to the instance of the Axi Ethernet component. MacCfgPtr is a pointer to the config instance of the Axi Ethernet component. AxiEthernetIntrId is interrupt Id of the MAC instance. -XST_SUCCESS to indicate success -XST_FAILURE to indicate failure
static void DoneHandler(void *CallBackRef, u32 Chan_id)
static void ErrorHandler(void *CallBackRef, u32 Chan_id, u32 Mask)
static void TxDoneHandler(void *CallBackRef, u32 Chan_id)
static void TxErrorHandler(void *CallBackRef, u32 Chan_id, u32 Mask)
static void AxiEthernetErrorHandler(XAxiEthernet *AxiEthernet)
This is the Error handler callback function and this function increments the the error counter so that the main thread knows the number of errors.
AxiEthernet is a reference to the Axi Ethernet device instance. None. None.
void AxiEthernetPHYRegistersDump(XAxiEthernet *AxiEthernetInstancePtr)
int main(void)
This is the main function for the Axi Ethernet example.
This function is not included if the example is generated from the TestAppGen test tool. None. - XST_SUCCESS to indicate success. XST_FAILURE to indicate failure None.
References AXIETHERNET_DEVICE_ID, AxiEthernetSgDmaIntrExample, AxiEthernetUtilErrorTrap.
u16 Swap8(u8 Data)
void AxiEnthernetSetMAC(char *MacAddr, u8 ChanId)