xaxiethernet_control.c
int XAxiEthernet_MulticastAdd(XAxiEthernet *InstancePtr, void *AddressPtr, int Entry)
XAxiEthernet_MulticastAdd adds the Ethernet address, AddressPtr to the Axi Ethernet device's multicast filter list, at list index Entry.
The address referenced by AddressPtr may be of any unicast, multicast, or broadcast address form. The hardware for the Axi Ethernet device can hold up to C_Number_of_Table_Entries addresses in this filter list. The device must be stopped to use this function. Once an Ethernet address is programmed, the Axi Ethernet device will begin receiving data sent from that address. The Axi Ethernet hardware does not have a control bit to disable multicast filtering. The only way to prevent the Axi Ethernet device from receiving messages from an Ethernet address in the Multicast Address Table (MAT) is to clear it with XAxiEthernet_MulticastClear(). InstancePtr is a pointer to the Axi Ethernet instance to be worked on. AddressPtr is a pointer to the 6-byte Ethernet address to set. The previous address at the location Entry (if any) is overwritten with the value at AddressPtr. Entry is the hardware storage location to program this address and must be between 0 to (C_Number_of_Table_Entries - 1). XST_SUCCESS on successful completion.XST_DEVICE_IS_STARTED.if the Axi Ethernet device is not stopped. This routine works only with normal multicast filtering feature. A maximum of 4 multicast addresses can be stored in the HW provided multicast table.To use the extended multicast feature, extended multicast filtering must be enabled by using driver API XAxiEthernet_SetOptions with proper option fields set. Once extended multicast filtering is enabled, the APIs XAxiEthernet_[Add|Clear|Get]ExtMulticastGroup() must be used to manage multicast address groups.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::IsStarted, XAE_AF0_OFFSET, XAE_AF1_OFFSET, XAE_FMI_OFFSET, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
void XAxiEthernet_MulticastGet(XAxiEthernet *InstancePtr, void *AddressPtr, int Entry)
XAxiEthernet_MulticastGet gets the Ethernet address stored at index Entry in the Axi Ethernet device's multicast filter list.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. AddressPtr references the memory buffer to store the retrieved Ethernet address. This memory buffer must be at least 6 bytes in length. Entry is the hardware storage location from which to retrieve the address and must be between 0 to (C_Number_of_Table_Entries - 1) None. This routine works only with normal multicast filtering feature. A maximum of 4 multicast addresses can be stored in the HW provided multicast table.To use the extended multicast feature, extended multicast filtering must be enabled by using driver API XAxiEthernet_SetOptions with proper option fields set. Once extended multicast filtering is enabled, the APIs XAxiEthernet_[Add|Clear|Get]ExtMulticastGroup() must be used to manage multicast address groups.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAE_AF0_OFFSET, XAE_AF1_OFFSET, XAE_FMI_OFFSET, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
int XAxiEthernet_MulticastClear(XAxiEthernet *InstancePtr, int Entry)
XAxiEthernet_MulticastClear clears the Ethernet address stored at index Entry in the Axi Ethernet device's multicast filter list.
The device must be stopped to use this function. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. Entry is the HW storage location used when this address was added. It must be between 0 to (C_Number_of_Table_Entries - 1). XST_SUCCESS on successful completion.XST_DEVICE_IS_STARTED.if the Axi Ethernet device is not stopped. This routine works only with normal multicast filtering feature. A maximum of 4 multicast addresses can be stored in the HW provided multicast table.To use the extended multicast feature, extended multicast filtering must be enabled by using driver API XAxiEthernet_SetOptions with proper option fields set. Once extended multicast filtering is enabled, the APIs XAxiEthernet_[Add|Clear|Get]ExtMulticastGroup() must be used to manage multicast address groups.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::IsStarted, XAE_AF0_OFFSET, XAE_AF1_OFFSET, XAE_FMI_OFFSET, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
int XAxiEthernet_SetMacPauseAddress(XAxiEthernet *InstancePtr, void *AddressPtr)
XAxiEthernet_SetMacPauseAddress sets the MAC address used for pause frames to AddressPtr.
AddressPtr will be the address the Axi Ethernet device will recognize as being for pause frames. Pause frames transmitted with XAxiEthernet_SendPausePacket() will also use this address. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. AddressPtr is a pointer to the 6-byte Ethernet address to set. XST_SUCCESS on successful completion.XST_DEVICE_IS_STARTED if the Axi Ethernet device is not stopped. None.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::IsStarted, XAE_RCW0_OFFSET, XAE_RCW1_OFFSET, XAE_RCW1_PAUSEADDR_MASK, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
void XAxiEthernet_GetMacPauseAddress(XAxiEthernet *InstancePtr, void *AddressPtr)
XAxiEthernet_GetMacPauseAddress gets the MAC address used for pause frames for the Axi Ethernet device specified by InstancePtr.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. AddressPtr references the memory buffer to store the retrieved MAC address. This memory buffer must be at least 6 bytes in length. None. None.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAE_RCW0_OFFSET, XAE_RCW1_OFFSET, XAxiEthernet_ReadReg.
int XAxiEthernet_SendPausePacket(XAxiEthernet *InstancePtr, u16 PauseValue)
XAxiEthernet_SendPausePacket sends a pause packet with the value of PauseValue.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. PauseValue is the pause value in units of 512 bit times. XST_SUCCESS on successful completion.XST_DEVICE_IS_STARTED if the Axi Ethernet device is not stopped. None.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::IsStarted, XAE_TPF_OFFSET, XAE_TPF_TPFV_MASK, XAxiEthernet_WriteReg.
int XAxiEthernet_GetSgmiiStatus(XAxiEthernet *InstancePtr, u16 *SpeedPtr)
XAxiEthernet_GetSgmiiStatus get the state of the link when using the SGMII media interface.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. SpeedPtr references the location to store the result, which is the auto negotiated link speed in units of Mbits/sec, either 0, 10, 100, or 1000. XST_SUCCESS on successful completion.XST_NO_FEATURE if the Axi Ethernet device is not using an SGMII interface, Currently SGMII PHY does not support half duplex mode.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAE_PHYC_OFFSET, XAE_PHYC_SGLINKSPD_10, XAE_PHYC_SGLINKSPD_100, XAE_PHYC_SGLINKSPD_1000, XAE_PHYC_SGMIILINKSPEED_MASK, XAE_SPEED_1000_MBPS, XAE_SPEED_100_MBPS, XAE_SPEED_10_MBPS, XAxiEthernet_Get_Phy_Interface, XAxiEthernet_ReadReg.
int XAxiEthernet_GetRgmiiStatus(XAxiEthernet *InstancePtr, u16 *SpeedPtr, int *IsFullDuplexPtr, int *IsLinkUpPtr)
XAxiEthernet_GetRgmiiStatus get the state of the link when using the RGMII media interface.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. SpeedPtr references the location to store the result, which is the auto negotiated link speed in units of Mbits/sec, either 0, 10, 100, or 1000. IsFullDuplexPtr references the value that is set by this function to indicate full duplex operation. IsFullDuplexPtr is set to TRUE when the RGMII link is operating in full duplex mode, otherwise it is set to FALSE. IsLinkUpPtr references the value that is set by this function to indicate the link status.IsLinkUpPtr is set to TRUE when the RGMII link up, otherwise it is set to FALSE. XST_SUCCESS on successful completion.XST_NO_FEATURE if the Axi Ethernet device is not using an RGMII interface, None.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAE_PHYC_OFFSET, XAE_PHYC_RGLINKSPD_10, XAE_PHYC_RGLINKSPD_100, XAE_PHYC_RGLINKSPD_1000, XAE_PHYC_RGMIIHD_MASK, XAE_PHYC_RGMIILINK_MASK, XAE_PHYC_RGMIILINKSPEED_MASK, XAE_SPEED_1000_MBPS, XAE_SPEED_100_MBPS, XAE_SPEED_10_MBPS, XAxiEthernet_Get_Phy_Interface, XAxiEthernet_ReadReg.
int XAxiEthernet_SetTpid(XAxiEthernet *InstancePtr, u16 Tpid, u8 Entry)
XAxiEthernet_SetTpid sets the VLAN Tag Protocol Identifier(TPID).
Four values can be configured - 0x8100, 0x9100, 0x9200, 0x88A8. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. Tpid is a hex value to be added to the TPID table. The four values that can be added are 0x8100, 0x9100, 0x9200, 0x88A8. Entry is the hardware storage location to program this address and must be between 0..XAE_TPID_MAX_ENTRIES. XST_SUCCESS on successful completion.XST_DEVICE_IS_STARTED, if the Axi Ethernet device is not stopped.XST_NO_FEATURE if the Axi Ethernet does not enable or have the VLAN tag capability.XST_INVALID_PARAM if Tpid is not one of supported values. The device must be stopped to use this function.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::IsStarted, XAE_TPID0_OFFSET, XAE_TPID1_OFFSET, XAE_TPID_0_MASK, XAE_TPID_1_MASK, XAxiEthernet_IsExtFuncCap, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
Referenced by AxiEthernetSgDmaIntrExtVlanExample.
int XAxiEthernet_ClearTpid(XAxiEthernet *InstancePtr, u8 Entry)
XAxiEthernet_ClearTpid clears the VLAN Tag Protocol Identifier(TPID).
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. Entry is the hardware storage location to program this address and must be between 0..XAE_TPID_MAX_ENTRIES. XST_SUCCESS on successful completion.XST_DEVICE_IS_STARTED if the Axi Ethernet device is not stopped.XST_NO_FEATURE if the Axi Ethernet does not enable or have the VLAN tag capability. The device must be stopped to use this function.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::IsStarted, XAE_TPID0_OFFSET, XAE_TPID1_OFFSET, XAE_TPID_0_MASK, XAE_TPID_1_MASK, XAxiEthernet_IsExtFuncCap, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
void XAxiEthernet_GetTpid(XAxiEthernet *InstancePtr, u16 *TpidPtr, u8 Entry)
XAxiEthernet_GetTpid gets the VLAN Tag Protocol Identifier value (TPID).
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. TpidPtr references the location to store the result. Entry is the hardware storage location to program this address and must be between 0..XAE_TPID_MAX_ENTRIES. None. None.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAE_TPID0_OFFSET, XAE_TPID1_OFFSET, XAE_TPID_0_MASK, XAxiEthernet_ReadReg.
int XAxiEthernet_SetVTagMode(XAxiEthernet *InstancePtr, u32 Mode, int Dir)
XAxiEthernet_SetVTagMode configures the VLAN tagging mode.
Four modes can be configured, XAE_VTAG_NONE for no tagging.XAE_VTAG_ALL to tag all frames.XAE_VTAG_EXISTED to tag already tagged frames.XAE_VTAG_SELECT to tag selected already tagged frames based on VID value. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. Mode is the VLAN tag mode. Value must be between b'00-b'11. Dir must be either XAE_TX or XAE_RX. XST_SUCCESS. on successful completion.XST_DEVICE_IS_STARTED if the Axi Ethernet device is not stopped.XST_NO_FEATURE if the Axi Ethernet does not enable or have the TX VLAN tag capability.XST_INVALID_PARAM if Mode is not one of supported modes. The device must be stopped to use this function. The fourth mode (specified by XAE_VTAG_SELECT) requires a method for specifying which tagged frames should receive an additional VLAN tag. The VLAN translation table 'tag enabled' is referenced. That configuration is handled in XAxiEthernet_SetVidTable().Mode value shifting is handled in this function. No shifting is required to call this function.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::IsStarted, XAE_RAF_OFFSET, XAE_RAF_RXVTAGMODE_MASK, XAE_RAF_RXVTAGMODE_SHIFT, XAE_RAF_TXVTAGMODE_MASK, XAE_RAF_TXVTAGMODE_SHIFT, XAxiEthernet_IsExtFuncCap, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
Referenced by AxiEthernetSgDmaIntrExtVlanExample.
void XAxiEthernet_GetVTagMode(XAxiEthernet *InstancePtr, u8 *ModePtr, int Dir)
XAxiEthernet_GetVTagMode gets VLAN tagging mode.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. ModePtr references the location to store the VLAN tag mode. Value is between b'00-b'11. Dir must be either XAE_TX or XAE_RX. None. The device must be stopped to use this function. Mode value shifting is handled in this function. No shifting is required to call this function.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAE_RAF_OFFSET, XAE_RAF_RXVTAGMODE_MASK, XAE_RAF_RXVTAGMODE_SHIFT, XAE_RAF_TXVTAGMODE_MASK, XAE_RAF_TXVTAGMODE_SHIFT, XAxiEthernet_ReadReg.
int XAxiEthernet_SetVStripMode(XAxiEthernet *InstancePtr, u32 Mode, int Dir)
XAxiEthernet_SetVStripMode configures the VLAN strip mode.
Three modes can be configured : XAE_VSTRP_NONE for no stripping.XAE_VSTRP_ALL to strip one tag from all frames.XAE_VSTRP_SELECT to strip one tag from already selected tagged frames based on VID value. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. Mode is the VLAN strip mode. Value must be b'00, b'01, or b'11. Dir must be either XAE_TX or XAE_RX. XST_SUCCESS on successful completion., returns XST_SUCCESS.XST_DEVICE_IS_STARTED if the Axi Ethernet device is not stopped.XST_NO_FEATURE if the Axi Ethernet does not enable or have the TX VLAN strip capability.XST_INVALID_PARAM if Mode is not one of supported modes. The device must be stopped to use this function. The third mode (specified by XAE_VSTRP_SELECT) requires a method for specifying which tagged frames should be stripped. The VLAN translation table 'stripped enabled' is referenced. That configuration is handled in XAxiEthernet_SetVidTable().Mode value shifting is handled in this function. No shifting is required to call this function.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::IsStarted, XAE_RAF_OFFSET, XAE_RAF_RXVSTRPMODE_MASK, XAE_RAF_RXVSTRPMODE_SHIFT, XAE_RAF_TXVSTRPMODE_MASK, XAE_RAF_TXVSTRPMODE_SHIFT, XAxiEthernet_IsExtFuncCap, XAxiEthernet_ReadReg, XAxiEthernet_WriteReg.
Referenced by AxiEthernetSgDmaIntrExtVlanExample.
void XAxiEthernet_GetVStripMode(XAxiEthernet *InstancePtr, u8 *ModePtr, int Dir)
XAxiEthernet_GetVStripMode gets the VLAN stripping mode.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. ModePtr references the location to store the VLAN strip mode returned by this function. Value is b'00, b'01 or b'11. Refer XAE_VTSRAP_* in xaxiethernet.h file for the details. Dir must be either XAE_TX or XAE_RX. None. Mode value shifting is handled in this function. No shifting is required to call this function.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAE_RAF_OFFSET, XAE_RAF_RXVSTRPMODE_MASK, XAE_RAF_RXVSTRPMODE_SHIFT, XAE_RAF_TXVSTRPMODE_MASK, XAE_RAF_TXVSTRPMODE_SHIFT, XAxiEthernet_ReadReg.
int XAxiEthernet_SetVTagValue(XAxiEthernet *InstancePtr, u32 VTagValue, int Dir)
XAxiEthernet_SetVTagValue configures the VLAN tagging value.
The device must be stopped to use this function. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. VTagValue is the VLAN tag value to be configured. A 32bit value. TPID, one of the following 16 bit values, 0x8100, 0x88a8, 0x9100, 0x9200. Priority, 3 bits CFI, 1 bit VID, 12 bits Dir must be either XAE_TX or XAE_RX. XST_SUCCESS on successful completion, returns .XST_DEVICE_IS_STARTED if the Axi Ethernet device is not stopped.XST_NO_FEATURE if the Axi Ethernet does not enable/have TX VLAN tag capability.XST_INVALID_PARAM, if the TPID is not one the four supported values. The four supported TPID values are 0x8100, 0x88a8, 0x9100, 0x9200. XAxiEthernet_SetVTagValue performs verification on TPID only.Ethernet VLAN frames' VLAN type/length(2B) and tag control information(2B). Bit layout : bbbb bbbb bbbb bbbb bbb b bbbb bbbb bbbb \ / | | \ VID (12b) / \ / | CFI bit (1b) TPID (16b) priority bit (3b)
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::IsStarted, XAE_RTAG_OFFSET, XAE_TTAG_OFFSET, XAxiEthernet_IsExtFuncCap, XAxiEthernet_WriteReg.
Referenced by AxiEthernetSgDmaIntrExtVlanExample.
void XAxiEthernet_GetVTagValue(XAxiEthernet *InstancePtr, u32 *VTagValuePtr, int Dir)
XAxiEthernet_GetVTagValue gets the configured VLAN tagging value.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. VTagValuePtr references the location to store the result. Format is TPID, one of the following 16 bit values, 0x8100, 0x88a8, 0x9100, 0x9200. Priority, 3 bits CFI, 1 bit VID, 12 bits Dir must be either XAE_TX or XAE_RX. None. Ethernet VLAN frames' VLAN type/length(2B) and tag control information(2B). Bit layout : bbbb bbbb bbbb bbbb bbb b bbbb bbbb bbbb \ / | | \ VID (12b) / \ / | CFI bit (1b) TPID (16b) priority bit (3b)
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAE_RTAG_OFFSET, XAE_TTAG_OFFSET, XAxiEthernet_ReadReg.
int XAxiEthernet_SetVidTable(XAxiEthernet *InstancePtr, u32 Entry, u32 Vid, u8 Strip, u8 Tag, int Dir)
XAxiEthernet_SetVidTable sets VID table includes new VLAN ID, strip and tag enable bits.
The device must be stopped to use this function. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. Entry is the hardware storage location/index to program updated VID value, strip, or tag value. The value must be between 0..0xFFF. Vid is updated/translated Vid value to be programmed. Strip is strip enable indication for Vid. Tag is tag enable indication for Vid. Dir must be either XAE_TX or XAE_RX. XST_SUCCESS on successful completion.XST_DEVICE_IS_STARTED if the Axi Ethernet device is not stopped.XST_NO_FEATURE if the Axi Ethernet does not enable/have extended functionalities. The hardware requires the table to be 'indexed' with Entry and must be 0x000..0xFFF.Bits layout is bbbb bbbb bbbb b b VLAN ID (12b), | | | VLAN double tag enable bit VLAN strip enable bitTo disable translation indexed by Entry, Set Vid = Entry.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::IsStarted, XAE_MAX_VLAN_TABL_ENTRY, XAE_RX_VLAN_DATA_OFFSET, XAE_TX_VLAN_DATA_OFFSET, XAE_VLAN_TABL_STRP_FLD_LEN, XAE_VLAN_TABL_STRP_STRT_OFFSET, XAE_VLAN_TABL_TAG_FLD_LEN, XAE_VLAN_TABL_VID_START_OFFSET, XAxiEthernet_IsExtFuncCap, XAxiEthernet_WriteReg.
Referenced by AxiEthernetSgDmaIntrExtVlanExample.
void XAxiEthernet_GetVidTable(XAxiEthernet *InstancePtr, u32 Entry, u32 *VidPtr, u8 *StripPtr, u8 *TagPtr, int Dir)
XAxiEthernet_GetVidTable gets VID table content includes new VLAN ID, strip and tag enable bits.
The device must be stopped to use this function. InstancePtr is a pointer to the Axi Ethernet instance to be worked on. Entry is the hardware storage location/index to program updated VID value, strip, or tag value. The value must be between 0..0xFFF. VidPtr references the location to store the result. This function stores the Vid value indexed by Entry into this location. StripPtr references the location to store the result. This function stores the strip enable bit value indexed by Entry into this location. TagPtr references the location to store the result. This function stores the tag enable bit value indexed by Entry into this location. Dir must be either XAE_TX or XAE_RX. None. The hardware requires the table to be 'indexed' with Entry and must be 0x000..0xFFF.Bits layout is bbbb bbbb bbbb b b VLAN ID (12b), | | | VLAN double tag enable bit VLAN strip enable bit
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAE_MAX_VLAN_TABL_ENTRY, XAE_RX_VLAN_DATA_OFFSET, XAE_TX_VLAN_DATA_OFFSET, XAE_VLAN_TABL_STRP_ENTRY_MASK, XAE_VLAN_TABL_STRP_STRT_OFFSET, XAE_VLAN_TABL_TAG_ENTRY_MASK, XAE_VLAN_TABL_VID_START_OFFSET, XAxiEthernet_ReadReg.
int XAxiEthernet_AddExtMulticastGroup(XAxiEthernet *InstancePtr, void *AddressPtr)
XAxiEthernet_AddExtMulticastGroup adds an entry to the multicast Ethernet address table.
The new entry, represents a group of MAC addresses based on the contents of AddressPtr. AddressPtr is one member of the MAC address set in the newly added entry.The device must be stopped to use this function. Once an Ethernet address is programmed, the Axi Ethernet device will begin receiving data sent from that address. The Axi Ethernet hardware does not have a control bit to disable multicast filtering. The only way to prevent the Axi Ethernet device from receiving messages from an Ethernet address in the multicast table is to clear it with XAxiEthernet_ClearExtMulticastGroup(). InstancePtr is a pointer to the Axi Ethernet instance to be worked on. AddressPtr is a pointer to the 6-byte Ethernet address to add. XST_SUCCESS.on successful completion.XST_DEVICE_IS_STARTED if the Axi Ethernet device is not stopped.XST_INVALID_PARAM if the input MAC address is not between 01:00:5E:00:00:00 and 01:00:5E:7F:FF:FF per RFC1112. This routine consider all 2**23 possible multicast Ethernet addresses to be 8Mx1 bit or 1M bytes memory area. All defined multicast addresses are from 01.00.5E.00.00.00 to 01.00.5E.7F.FF.FF The most significant 25 bit out of 48 bit are static, so they will not be part of calculation.The hardware requires to 'index' with bit 22-8, 15 bits in total. The least significant byte/8 bits are considered a group.This API operates at a group (256 MAC addresses) for hardware to do the first layer address filtering. It is user's responsibility to provision this table appropriately.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::IsStarted, XAE_MCAST_TABLE_OFFSET, XAxiEthernet_IsExtFuncCap, XAxiEthernet_IsExtMcastEnable, XAxiEthernet_WriteReg.
Referenced by AxiEthernetSgDmaIntrExtMulticastExample.
int XAxiEthernet_ClearExtMulticastGroup(XAxiEthernet *InstancePtr, void *AddressPtr)
XAxiEthernet_ClearExtMulticastGroup clears input multicast Ethernet address group from table.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. AddressPtr is a pointer to the 6-byte Ethernet address to clear. XST_SUCCESS on successful completion, returns XST_SUCCESS.XST_DEVICE_IS_STARTED if the Axi Ethernet device is not stoppedXST_INVALID_PARAM if input MAC address is not between 01:00:5E:00:00:00 and 01:00:5E:7F:FF:FF per RFC1112. Please reference XAxiEthernet_AddExtMulticastGroup for multicast address index and bit value calculation.In table, hardware requires to 'index' with bit 22-8, 15 bits in total. The least significant byte/8 bits are considered a group.There is a scenario that might introduce issues: When multicast tables are programmed initially to accept 01:00:5E:12:34:56 and 01:00:5E:12:34:78 but later decided to clear 01:00:5E:12:34:78. Without validating all possible combinations at the indexed entry, multicast table might be misconfigured and drop frames.When clearing a multicast address table entry, note that a whole group of mac addresses will no longer be accepted - this because an entry in the table represents multiple(256) mac addresses.The device must be stopped to use this function. This API operates at a group (256 MAC addresses) level for hardware to perform the first layer address filtering. It is user's responsibility to provision this table appropriately.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAxiEthernet::IsStarted, XAE_MCAST_TABLE_OFFSET, XAxiEthernet_IsExtFuncCap, XAxiEthernet_IsExtMcastEnable, XAxiEthernet_WriteReg.
int XAxiEthernet_GetExtMulticastGroup(XAxiEthernet *InstancePtr, void *AddressPtr)
XAxiEthernet_GetExtMulticastGroup returns whether the given Ethernet address group is stored in the table.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. AddressPtr is a pointer to the 6-byte Ethernet address. TRUE if it is an acceptable multicast MAC address and the group is present in the table.FALSE if it is not a valid multicast MAC address or the group was not found in the table. In the table, hardware requires to 'index' with bit 22-8, 15 bits in total. The least significant byte/8 bits are considered a group. This API operates at a group (256 MAC addresses) level.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet::IsReady, XAE_MCAST_TABLE_OFFSET, XAxiEthernet_ReadReg.
Referenced by AxiEthernetSgDmaIntrExtMulticastExample.
void XAxiEthernet_DumpExtMulticastGroup(XAxiEthernet *InstancePtr)
XAxiEthernet_DumpExtMulticastGroup dumps ALL provisioned acceptable multicast MAC in the Axi Ethernet device's multicast table.
InstancePtr is a pointer to the Axi Ethernet instance to be worked on. None. Hardware requires to 'index' with bit 22-8, 15 bits in total. The least significant byte/8 bits are considered a set.This API operates at a set (256 MAC addresses) level.
References XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAE_MCAST_TABLE_OFFSET, XAxiEthernet_ReadReg.