xaxiethernet_sinit.c
XAxiEthernet_Config * XAxiEthernet_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
A table contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration table entry corresponding to the given device ID/BaseAddress, or NULL if no match is found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XAxiEthernet_Config::Name.
Referenced by AxiEthernetExtVlanExample, AxiEthernetFifoIntrExample, AxiEthernetMcastExample, AxiEthernetPingReqExample, AxiEthernetPolledExample, AxiEthernetSgDmaIntrExample, AxiEthernetSgDmaPollExample, main.