xaxiethernet_example_intr_fifo.c
XAXIETHERNET_BASEADDRESS
PAYLOAD_SIZE
EthernetFrame TxFrame
EthernetFrame RxFrame
volatile int DeferRx
volatile int FramesRx
volatile int FramesRxInts
volatile int FramesTxInts
volatile int DeviceErrors
volatile int FrameDataErrors
volatile int Padding
volatile int ExternalLoopback
XAxiEthernet AxiEthernetInstance
XLlFifo FifoInstance
static void AxiEthernetErrorHandler(XAxiEthernet *AxiEthernet)
This is the Error handler callback function and this function increments the the error counter so that the main thread knows the number of errors.
AxiEthernet is a reference to the AxiEthernet device instance. None. None.
static void FifoHandler(XLlFifo *Fifo)
This is the Fifo handler function and will increment a shared counter that can be tested by the main thread of operation.
Fifo is a reference to the Fifo instance. None. None.
int AxiEthernetFifoIntrExample(XAxiEthernet *AxiEthernetInstancePtr, XLlFifo *FifoInstancePtr, UINTPTR AxiEthernetBaseAddress)
This function demonstrates the usage usage of the Axi Ethernet by sending and receiving frames in interrupt driven fifo mode.
IntcInstancePtr is a pointer to the instance of the Intc component. AxiEthernetInstancePtr is a pointer to the instance of the Axi Ethernet component. FifoInstancePtr is a pointer to the instance of the AXIFIFO component. AxiEthernetDeviceId is Device ID of the Axi Ethernet Device , typically XPAR_<AXIETHERNET_instance>_DEVICE_ID value from xparameters.h. FifoDeviceId is the Interrupt ID and is typically XPAR_<INTC_instance>_<AXIETHERNET_instance>_VEC_ID value from xparameters.h. AxiEthernetIntrId is the Interrupt ID and is typically XPAR_<INTC_instance>_<AXIETHERNET_instance>_VEC_ID value from xparameters.h. FifoIntrId is the interrupt id for fifo. XST_SUCCESS to indicate success.XST_FAILURE.to indicate failure. AxiFifo hardware must be initialized before initializing AxiEthernet. Since AxiFifo reset line is connected to the AxiEthernet reset line, a reset of AxiFifo hardware during its initialization would reset AxiEthernet.
References XAxiEthernet_Config::AxiDevBaseAddress, AxiEthernetMultipleFramesIntrExample, AxiEthernetResetDevice, AxiEthernetSingleFrameIntrExample, AxiEthernetSingleFrameNonContIntrExample, AxiEthernetUtilEnterLoopback, AxiEthernetUtilErrorTrap, AxiEthernetUtilPhyDelay, XAxiEthernet_Config::BaseAddress, XAxiEthernet::Config, XAxiEthernet_Config::IntrId, XAxiEthernet_Config::IntrParent, XAxiEthernet_CfgInitialize, XAxiEthernet_Get_Phy_Interface, XAxiEthernet_LookupConfig, XAxiEthernet_SetMacAddress, XAxiEthernet_SetOperatingSpeed, XAxiEthernet_Stop.
Referenced by main.
int AxiEthernetSingleFrameIntrExample(XAxiEthernet *AxiEthernetInstancePtr, XLlFifo *FifoInstancePtr)
This function demonstrates the usage of the Axi Ethernet by sending and receiving a single frame in interrupt mode.
AxiEthernetInstancePtr is a pointer to the instance of the AxiEthernet component. FifoInstancePtr is a pointer to the instance of the Fifo component. XST_SUCCESS to indicate success.XST_FAILURE.to indicate failure. None.
References AxiEthernetUtilErrorTrap, AxiEthernetUtilFrameHdrFormatMAC, AxiEthernetUtilFrameHdrFormatType, AxiEthernetUtilFrameMemClear, AxiEthernetUtilFrameSetPayloadData, XAE_INT_RXFIFOOVR_MASK, XAE_INT_RXRJECT_MASK, XAxiEthernet_IntEnable, XAxiEthernet_Start, XAxiEthernet_Stop.
Referenced by AxiEthernetFifoIntrExample.
int AxiEthernetSingleFrameNonContIntrExample(XAxiEthernet *AxiEthernetInstancePtr, XLlFifo *FifoInstancePtr)
This example sends a packet from non-contiguous memory locations.
The header is stored in one area. The payload data is calculated and written to the packet FIFO one byte at a time. AxiEthernetInstancePtr is a pointer to the instance of the AxiEthernet component. FifoInstancePtr is a pointer to the instance of the Fifo component. XST_SUCCESS to indicate success.XST_FAILURE.to indicate failure. None.
References AxiEthernetUtilErrorTrap, AxiEthernetUtilFrameHdrFormatMAC, AxiEthernetUtilFrameHdrFormatType, AxiEthernetUtilFrameMemClear, XAxiEthernet_Start, XAxiEthernet_Stop.
Referenced by AxiEthernetFifoIntrExample.
int AxiEthernetMultipleFramesIntrExample(XAxiEthernet *AxiEthernetInstancePtr, XLlFifo *FifoInstancePtr)
This example sends and receives a batch of frames.
Frame reception is handled in this function and not in the callback function.Use this method of reception when interrupt latency is important. AxiEthernetInstancePtr is a pointer to the instance of the AxiEthernet component. FifoInstancePtr is a pointer to the instance of the Fifo component. XST_SUCCESS to indicate success.XST_FAILURE.to indicate failure. None.
References AxiEthernetUtilErrorTrap, AxiEthernetUtilFrameHdrFormatMAC, AxiEthernetUtilFrameHdrFormatType, AxiEthernetUtilFrameMemClear, AxiEthernetUtilFrameSetPayloadData, AxiEthernetUtilFrameVerify, XAxiEthernet_Start, XAxiEthernet_Stop.
Referenced by AxiEthernetFifoIntrExample.
static void FifoRecvHandler(XLlFifo *Fifo)
This is the Receive handler callback function for examples 1 and 2.
It will increment a shared counter, receive and validate the frame. Fifo is a reference to the Fifo device instance. None. None.
static int AxiEthernetResetDevice(XAxiEthernet *AxiEthernetInstancePtr, XLlFifo *FifoInstancePtr)
This function resets the device but preserves the options set by the user.
AxiEthernetInstancePtr is a pointer to the instance of the AxiEthernet component. FifoInstancePtr is a pointer to the instance of the Fifo component. - XST_SUCCESS to indicate success. XST_FAILURE.to indicate failure. None.
int main(void)
This is the main function for the Axi Ethernet example.
This function is not included if the example is generated from the TestAppGen test tool. None. XST_SUCCESS to indicate success.XST_FAILURE.to indicate failure. None.
References AXIETHERNET_DEVICE_ID, AxiEthernetFifoIntrExample, AxiEthernetUtilErrorTrap.
static void FifoErrorHandler(XLlFifo *Fifo, u32 Pending)
This is the Error handler callback function and this function increments the the error counter so that the main thread knows the number of errors.
Fifo is a reference to the AxiEthernet device instance. Pending is a bitmask of the pending interrupts. None. None.