qspipsu_api
typedef void(* XQspiPsu_StatusHandler)(const void *CallBackRef, u32 StatusEvent, u32 ByteCount))(const void *CallBackRef, u32 StatusEvent, u32 ByteCount)
The handler data type allows the user to define a callback function to handle the asynchronous processing for the QSPIPSU device.
The application using this driver is expected to define a handler of this type to support interrupt driven mode. The handler executes in an interrupt context, so only minimal processing should be performed. CallBackRef Callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. Its type is not important to the driver, so it is a void pointer. StatusEvent Holds one or more status events that have occurred. See XQspiPsu_SetStatusHandler() for details on the status events that can be passed in the callback. ByteCount Indicates how many bytes of data were successfully transferred. This may be less than the number of bytes requested if the status event indicates an error.
XQspiPsu_Config XQspiPsu_ConfigTable[][]
This table contains configuration information for each QSPIPSU device in the system.
Referenced by XQspiPsu_LookupConfig.
XQspiPsu_Config XQspiPsu_ConfigTable[XPAR_XQSPIPSU_NUM_INSTANCES][XPAR_XQSPIPSU_NUM_INSTANCES]
This table contains configuration information for each QSPIPSU device in the system.
Referenced by XQspiPsu_LookupConfig.
OptionsMap OptionsTable[][]
s32 XQspiPsu_CfgInitialize(XQspiPsu *InstancePtr, const XQspiPsu_Config *ConfigPtr, UINTPTR EffectiveAddr)
Initializes a specific XQspiPsu instance as such the driver is ready to use.
InstancePtr Pointer to the XQspiPsu instance. ConfigPtr Reference to a structure containing information about a specific QSPIPSU device. This function initializes an InstancePtr object for a specific device specified by the contents of Config. EffectiveAddr Device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, use ConfigPtr->Config. BaseAddress for this device. XST_SUCCESS if successful.XST_DEVICE_IS_STARTED if the device is already started. It must be stopped to re-initialize. None.
References XQspiPsu_Config::BaseAddress, XQspiPsu_Config::BaudRateDiv, XQspiPsu_Config::BusWidth, XQspiPsu::Config, XQspiPsu_Config::ConnectionMode, XQspiPsu::GenFifoBufferPtr, XQspiPsu::GenFifoBus, XQspiPsu::GenFifoCS, XQspiPsu::GenFifoEntries, XQspiPsu_Config::InputClockHz, XQspiPsu::IsBusy, XQspiPsu_Config::IsCacheCoherent, XQspiPsu_Config::IsFbClock, XQspiPsu::IsManualstart, XQspiPsu::IsReady, XQspiPsu::IsUnaligned, XQspiPsu::ReadMode, XQspiPsu::RecvBufferPtr, XQspiPsu_Config::RefClk, XQspiPsu::RxBytes, XQspiPsu::SendBufferPtr, XQspiPsu::StatusHandler, XQspiPsu::TxBytes, XQspiPsu_Enable, XQSPIPSU_READMODE_DMA, XQspiPsu_Reset, XQspiPsu_Select.
Referenced by QspiPsuFlashNonBlockingReadExample, QspiPsuInterruptFlashExample, QspiPsuPolledFlashExample, QspiPsuWriteProtectFlashExample.
void XQspiPsu_Idle(const XQspiPsu *InstancePtr)
Stops the transfer of data to internal DST FIFO from stream interface and also stops the issuing of new write commands to memory.
By calling this API, any ongoing Dma transfers will be paused and DMA will not issue AXI write commands to memory InstancePtr Pointer to the XQspiPsu instance. None. None.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu::IsReady, XQspiPsu_Config::RefClk, XQSPIPSU_EN_OFFSET, XQspiPsu_ReadReg, XQspiPsu_WriteReg.
void XQspiPsu_Reset(XQspiPsu *InstancePtr)
Resets the QSPIPSU device.
Reset must only be called after the driver has been initialized. Any data transfer that is in progress is aborted.The upper layer software is responsible for re-configuring (if necessary) and restarting the QSPIPSU device after the reset. InstancePtr Pointer to the XQspiPsu instance. None. None.
References XQspiPsu_Abort, XQspiPsu_SetDefaultConfig.
Referenced by XQspiPsu_CfgInitialize.
void XQspiPsu_Abort(XQspiPsu *InstancePtr)
Aborts a transfer in progress.
InstancePtr Pointer to the XQspiPsu instance. None. None.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu::GenFifoEntries, XQspiPsu::IsBusy, MAX_DELAY_CNT, XQspiPsu::ReadMode, XQspiPsu::RxBytes, XQspiPsu::TxBytes, XQSPIPSU_CFG_OFFSET, XQSPIPSU_FIFO_CTRL_OFFSET, XQSPIPSU_IDR_OFFSET, XQSPIPSU_ISR_OFFSET, XQSPIPSU_READMODE_DMA, XQspiPsu_ReadReg, XQspiPsu_WriteReg.
Referenced by XQspiPsu_Reset.
void XQspiPsu_PollDataHandler(XQspiPsu *InstancePtr, u32 StatusReg)
This is the handler for polling functionality of controller.
It reads data from RXFIFO, since when data from the flash device (status data) matched with configured value in poll_cfg, then controller writes the matched data into RXFIFO. InstancePtr Pointer to the XQspiPsu instance. StatusReg Interrupt status Register value. None. None.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu::IsBusy, XQspiPsu::IsReady, XQspiPsu::ReadMode, XQspiPsu::StatusHandler, XQspiPsu::StatusRef, XQSPIPSU_IDR_OFFSET, XQSPIPSU_READMODE_DMA, XQspiPsu_ReadReg, XQSPIPSU_RXD_OFFSET, XQspiPsu_SetReadMode, XQspiPsu_WriteReg.
Referenced by XQspiPsu_InterruptHandler.
s32 XQspiPsu_PolledTransfer(XQspiPsu *InstancePtr, XQspiPsu_Msg *Msg, u32 NumMsg)
Performs a transfer on the bus in polled mode.
The messages passed are all transferred on the bus between one CS assert and de-assert. InstancePtr Pointer to the XQspiPsu instance. Msg Pointer to the structure containing transfer data. NumMsg Number of messages to be transferred. XST_SUCCESS if successful.XST_FAILURE if transfer fails.XST_DEVICE_BUSY if a transfer is already in progress. None.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu_Msg::Flags, XQspiPsu::IsBusy, XQspiPsu::IsReady, MAX_DELAY_CNT, XQspiPsu_Config::RefClk, XQSPIPSU_DMA_BYTES_MAX, XQSPIPSU_ISR_OFFSET, XQSPIPSU_MSG_FLAG_RX, XQspiPsu_PolledMessageTransfer.
Referenced by FlashRegisterRead, FlashRegisterWrite.
s32 XQspiPsu_InterruptTransfer(XQspiPsu *InstancePtr, XQspiPsu_Msg *Msg, u32 NumMsg)
Initiates a transfer on the bus and enables interrupts.
The transfer is completed by the interrupt handler. The messages passed are all transferred on the bus between one CS assert and de-assert. InstancePtr Pointer to the XQspiPsu instance. Msg Pointer to the structure containing transfer data. NumMsg Number of messages to be transferred. XST_SUCCESS if successful.XST_FAILURE if transfer fails.XST_DEVICE_BUSY if a transfer is already in progress. None.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu_Msg::Flags, XQspiPsu::IsBusy, XQspiPsu::IsReady, XQspiPsu::Msg, XQspiPsu::MsgCnt, XQspiPsu::NumMsg, XQspiPsu::ReadMode, XQspiPsu_Config::RefClk, XQSPIPSU_DMA_BYTES_MAX, XQspiPsu_GenFifoEntryData, XQSPIPSU_IER_OFFSET, XQSPIPSU_MSG_FLAG_POLL, XQSPIPSU_MSG_FLAG_RX, XQspiPsu_PollDataConfig, XQSPIPSU_READMODE_DMA, XQspiPsu_WriteReg.
Referenced by BulkErase, DieErase, FlashEnableQuadMode, FlashEnterExit4BAddMode, FlashErase, FlashRead, FlashReadID, FlashWrite, MultiDieRead.
s32 XQspiPsu_InterruptHandler(XQspiPsu *InstancePtr)
Handles interrupt based transfers by acting on GENFIFO and DMA interurpts.
InstancePtr Pointer to the XQspiPsu instance. XST_SUCCESS if successful.XST_FAILURE if transfer fails. None.
References XQspiPsu_Msg::Flags, XQspiPsu::IsReady, XQspiPsu::Msg, XQspiPsu::MsgCnt, XQspiPsu::NumMsg, XQspiPsu_IntrDataTransfer, XQspiPsu_IntrDummyDataTransfer, XQSPIPSU_MSG_FLAG_POLL, XQSPIPSU_MSG_FLAG_RX, XQSPIPSU_MSG_FLAG_TX, XQspiPsu_PollDataHandler.
Referenced by QspiPsuInterruptFlashExample, QspiPsuWriteProtectFlashExample.
void XQspiPsu_SetStatusHandler(XQspiPsu *InstancePtr, void *CallBackRef, XQspiPsu_StatusHandler FuncPointer)
Sets the status callback function, the status handler, which the driver calls when it encounters conditions that should be reported to upper layer software.
The handler executes in an interrupt context, so it must minimize the amount of processing performed. One of the following status events is passed to the status handler.XST_SPI_TRANSFER_DONE The requested data transfer is doneXST_SPI_TRANSMIT_UNDERRUN As a slave device, the master clocked data but there were none available in the transmit register/FIFO. This typically means the slave application did not issue a transfer request fast enough, or the processor/driver could not fill the transmit register/FIFO fast enough.XST_SPI_RECEIVE_OVERRUN The QSPIPSU device lost data. Data was received but the receive data register/FIFO was full. InstancePtr Pointer to the XQspiPsu instance. CallBackRef Upper layer callback reference passed back when the callback function is invoked. FuncPointer Pointer to the callback function. None. The handler is called within interrupt context, so it should do its work quickly and queue potentially time-consuming work to a task-level thread.
References XQspiPsu::IsReady, XQspiPsu::StatusHandler, XQspiPsu::StatusRef.
Referenced by QspiPsuInterruptFlashExample, QspiPsuWriteProtectFlashExample.
void XQspiPsu_WriteProtectToggle(const XQspiPsu *InstancePtr, u32 Toggle)
Enables/disables Write Protect pin on the flash parts.
InstancePtr Pointer to the QSPIPSU driver component to use. Toggle Value of the GPIO pin None By default, the Write Protect pin as per the QSPI controller is driven High which means no write protection. Calling this function once will enable the protection.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu_Config::ConnectionMode, XQspiPsu::IsReady, XQSPIPSU_CONNECTION_MODE_SINGLE, XQSPIPSU_GPIO_OFFSET, XQspiPsu_WriteReg.
Referenced by QspiPsuWriteProtectFlashExample.
s32 XQspiPsu_StartDmaTransfer(XQspiPsu *InstancePtr, XQspiPsu_Msg *Msg, u32 NumMsg)
Starts a DMA transfer.
InstancePtr Pointer to the XQspiPsu instance. Msg Pointer to the structure containing transfer data. NumMsg Number of messages to be transferred. XST_SUCCESS if successful.XST_FAILURE if ByteCount is greater than XQSPIPSU_DMA_BYTES_MAX.XST_DEVICE_BUSY if a transfer is already in progress. None.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu_Msg::Flags, XQspiPsu::IsBusy, XQspiPsu::IsManualstart, XQspiPsu::IsReady, MAX_DELAY_CNT, XQspiPsu::Msg, XQspiPsu::ReadMode, XQspiPsu::TxBytes, XQSPIPSU_CFG_OFFSET, XQSPIPSU_DMA_BYTES_MAX, XQspiPsu_GenFifoEntryData, XQSPIPSU_ISR_OFFSET, XQSPIPSU_MSG_FLAG_RX, XQSPIPSU_READMODE_DMA, XQSPIPSU_READMODE_IO, XQspiPsu_ReadReg, XQspiPsu_WriteReg.
s32 XQspiPsu_CheckDmaDone(XQspiPsu *InstancePtr)
Checks for DMA transfer complete.
InstancePtr Pointer to the XQspiPsu instance. XST_SUCCESS if DMA transfer complete.XST_FAILURE if DMA transfer is not completed. None.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu::IsBusy, XQspiPsu_Config::IsCacheCoherent, XQspiPsu::IsManualstart, XQspiPsu::IsReady, MAX_DELAY_CNT, XQspiPsu::Msg, XQspiPsu_Msg::RxAddr64bit, XQspiPsu_Msg::RxBfrPtr, XQspiPsu::RxBytes, XQspiPsu_Msg::Xfer64bit, XQSPIPSU_CFG_OFFSET, XQSPIPSU_ISR_OFFSET, XQspiPsu_ReadReg, XQSPIPSU_RXADDR_OVER_32BIT, XQspiPsu_WriteReg.
static void XQspiPsu_ManualStartEnable(XQspiPsu *InstancePtr)
Enables the manual start option.
InstancePtr Pointer to the XQspiPsu instance. None None.
static void XQspiPsu_GenFifoEntryCSAssert(const XQspiPsu *InstancePtr)
Writes the GENFIFO entry to assert CS.
InstancePtr Pointer to the XQspiPsu instance. None None.
static void XQspiPsu_GenFifoEntryCSDeAssert(const XQspiPsu *InstancePtr)
Writes the GENFIFO entry to de-assert CS.
InstancePtr Pointer to the XQspiPsu instance. None None.
static void StubStatusHandler(const void *CallBackRef, u32 StatusEvent, u32 ByteCount)
Stub for the status callback.
The stub is here in case the upper layers forget to set the handler. CallBackRef Pointer to the upper layer callback reference StatusEvent Event that just occurred. ByteCount Number of bytes transferred up until the event occurred. None. None.
XQspiPsu_Config * XQspiPsu_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XQspiPsu_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xqspipsu.h for the definition of XQspiPsu_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XQspiPsu_Config::Name, XQspiPsu_ConfigTable.
Referenced by QspiPsuFlashNonBlockingReadExample, QspiPsuInterruptFlashExample, QspiPsuPolledFlashExample, QspiPsuWriteProtectFlashExample.
s32 XQspiPsu_SetClkPrescaler(const XQspiPsu *InstancePtr, u8 Prescaler)
Configures the clock according to the prescaler passed.
InstancePtr Pointer to the XQspiPsu instance. Prescaler Clock prescaler to be set. XST_SUCCESS if successful.XST_DEVICE_IS_STARTED if the device is already started.XST_DEVICE_BUSY if the device is currently transferring data. It must be stopped to re-initialize.XST_FAILURE if Prescaler value is less than FreqDiv when feedback clock is not enabled. None.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu_Config::InputClockHz, XQspiPsu::IsBusy, XQspiPsu_Config::IsFbClock, XQspiPsu::IsReady, XQSPIPSU_CFG_OFFSET, XQSPIPSU_CR_PRESC_MAXIMUM, XQSPIPSU_FREQ_37_5MHZ, XQspiPsu_ReadReg, XQspiPsu_WriteReg.
Referenced by QspiPsuFlashNonBlockingReadExample, QspiPsuInterruptFlashExample, QspiPsuPolledFlashExample, QspiPsuWriteProtectFlashExample.
void XQspiPsu_SelectFlash(XQspiPsu *InstancePtr, u8 FlashCS, u8 FlashBus)
Used to tell the QSPIPSU driver the hardware flash configuration being used.
This API should be called at least once in the application. If desired, it can be called multiple times when switching between communicating to different flash devices/using different configs. InstancePtr Pointer to the XQspiPsu instance. FlashCS Flash Chip Select. FlashBus Flash Bus (Upper, Lower or Both). XST_SUCCESS if successful.XST_DEVICE_IS_STARTED if the device is already started. It must be stopped to re-initialize. If this function is not called at least once in the application, the driver assumes there is a single flash connected to the lower bus and CS line.
References XQspiPsu::GenFifoBus, XQspiPsu::GenFifoCS, XQspiPsu::IsReady, XQSPIPSU_SELECT_FLASH_BUS_BOTH, XQSPIPSU_SELECT_FLASH_BUS_LOWER, XQSPIPSU_SELECT_FLASH_BUS_UPPER, XQSPIPSU_SELECT_FLASH_CS_BOTH, XQSPIPSU_SELECT_FLASH_CS_LOWER, XQSPIPSU_SELECT_FLASH_CS_UPPER.
Referenced by FlashErase, GetRealAddr, QspiPsuConfigurePoll, QspiPsuFlashNonBlockingReadExample, QspiPsuInterruptFlashExample, QspiPsuPolledFlashExample, QspiPsuWriteProtectFlashExample.
s32 XQspiPsu_SetOptions(XQspiPsu *InstancePtr, u32 Options)
Sets the options for the QSPIPSU device driver.The options control how the device behaves relative to the QSPIPSU bus.
The device must be idle rather than busy transferring data before setting these device options. InstancePtr Pointer to the XQspiPsu instance. Options Contains the specified options to be set. This is a bit mask where a 1 indicates the option should be turned ON and a 0 indicates no action. One or more bit values may be contained in the mask. See the bit definitions named XQSPIPSU_*_OPTIONS in the file xqspipsu.h. XST_SUCCESS if options are successfully set.XST_DEVICE_BUSY if the device is currently transferring data. The transfer must complete or be aborted before setting options. This function is not thread-safe.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu::IsBusy, XQspiPsu::IsManualstart, XQspiPsu::IsReady, XQSPIPS_BASEADDR, XQSPIPS_LQSPI_CFG_RST_STATE, XQSPIPS_LQSPI_CR_4_BYTE_STATE, XQSPIPS_LQSPI_CR_RST_STATE, XQSPIPSU_CFG_OFFSET, XQSPIPSU_EN_OFFSET, XQSPIPSU_LQSPI_CR_LINEAR_MASK, XQSPIPSU_LQSPI_CR_OFFSET, XQSPIPSU_LQSPI_LESS_THEN_SIXTEENMB, XQSPIPSU_LQSPI_MODE_OPTION, XQSPIPSU_MANUAL_START_OPTION, XQSPIPSU_NUM_OPTIONS, XQspiPsu_ReadReg, XQspiPsu_WriteReg.
Referenced by QspiPsuFlashNonBlockingReadExample, QspiPsuInterruptFlashExample, QspiPsuPolledFlashExample, QspiPsuWriteProtectFlashExample.
s32 XQspiPsu_ClearOptions(XQspiPsu *InstancePtr, u32 Options)
Resets the options for the QSPIPSU device driver.
The options control how the device behaves relative to the QSPIPSU bus. The device must be idle rather than busy transferring data before setting these device options. InstancePtr Pointer to the XQspiPsu instance. Options Contains the specified options to be set. This is a bit mask where a 1 indicates the option should be turned OFF and a 0 indicates no action. One or more bit values may be contained in the mask. See the bit definitions named XQSPIPSU_*_OPTIONS in the file xqspipsu.h. XST_SUCCESS if options are successfully set.XST_DEVICE_BUSY if the device is currently transferring data. The transfer must complete or be aborted before setting options. This function is not thread-safe.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu::IsBusy, XQspiPsu::IsManualstart, XQspiPsu::IsReady, XQSPIPSU_CFG_OFFSET, XQSPIPSU_MANUAL_START_OPTION, XQSPIPSU_NUM_OPTIONS, XQspiPsu_ReadReg, XQspiPsu_WriteReg.
u32 XQspiPsu_GetOptions(const XQspiPsu *InstancePtr)
Gets the options for the QSPIPSU device.
The options control how the device behaves relative to the QSPIPSU bus. InstancePtr Pointer to the XQspiPsu instance. Options contains the specified options currently set. This is a bit value where a 1 means the option is on, and a 0 means the option is off. See the bit definitions named XQSPIPSU_*_OPTIONS in file xqspipsu.h.None.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu::IsReady, XQSPIPSU_CFG_OFFSET, XQSPIPSU_NUM_OPTIONS, XQspiPsu_ReadReg.
s32 XQspiPsu_SetReadMode(XQspiPsu *InstancePtr, u32 Mode)
Sets the Read mode for the QSPIPSU device driver.
The device must be idle rather than busy transferring data before setting Read mode options. InstancePtr Pointer to the XQspiPsu instance. Mode Contains the specified Mode to be set. See the bit definitions named XQSPIPSU_READMODE_* in the file xqspipsu.h. XST_SUCCESS if options are successfully set.XST_DEVICE_BUSY if the device is currently transferring data. The transfer must complete or be aborted before setting Mode. This function is not thread-safe.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu::IsBusy, XQspiPsu::IsReady, XQspiPsu::ReadMode, XQSPIPSU_CFG_OFFSET, XQSPIPSU_READMODE_DMA, XQSPIPSU_READMODE_IO, XQspiPsu_ReadReg, XQspiPsu_WriteReg.
Referenced by XQspiPsu_PollDataHandler.
void XQspiPsu_SetWP(const XQspiPsu *InstancePtr, u8 Value)
Sets the Write Protect and Hold options for the QSPIPSU device driver.
The device must be idle rather than busy transferring data before setting Write Protect and Hold options. InstancePtr Pointer to the XQspiPsu instance. Value Value of the WP_HOLD bit in configuration register None This function is not thread-safe. This function can only be used with single flash configuration and x1/x2 data mode. This function cannot be used with x4 data mode and dual parallel and stacked flash configuration.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu::IsBusy, XQspiPsu::IsReady, XQSPIPSU_CFG_OFFSET, XQspiPsu_ReadReg, XQspiPsu_WriteReg.
Referenced by QspiPsuWriteProtectFlashExample.
void XQspiPsu_GenFifoEntryData(XQspiPsu *InstancePtr, XQspiPsu_Msg *Msg)
Writes the GENFIFO entries to transmit the messages requested.
InstancePtr Pointer to the XQspiPsu instance. Msg Pointer to the structure containing transfer data. XST_SUCCESS if successful.XST_FAILURE if transfer fails.XST_DEVICE_BUSY if a transfer is already in progress.
References XQspiPsu_Config::BaseAddress, XQspiPsu_Msg::BusWidth, XQspiPsu_Msg::ByteCount, XQspiPsu::Config, XQspiPsu_Msg::Flags, XQspiPsu::GenFifoBus, XQspiPsu::GenFifoCS, XQspiPsu::IsReady, XQspiPsu::IsUnaligned, XQspiPsu::ReadMode, XQSPIPSU_CFG_OFFSET, XQSPIPSU_GEN_FIFO_OFFSET, XQspiPsu_GenFifoEntryDataLen, XQSPIPSU_MSG_FLAG_RX, XQSPIPSU_MSG_FLAG_STRIPE, XQSPIPSU_READMODE_DMA, XQSPIPSU_READMODE_IO, XQspiPsu_ReadReg, XQspiPsu_SelectSpiMode, XQspiPsu_TXRXSetup, XQspiPsu_WriteReg.
Referenced by XQspiPsu_InterruptTransfer, XQspiPsu_IntrDummyDataTransfer, XQspiPsu_IntrRecvData, XQspiPsu_PolledMessageTransfer, XQspiPsu_StartDmaTransfer.
void XQspiPsu_PollDataConfig(XQspiPsu *InstancePtr, XQspiPsu_Msg *FlashMsg)
Enables the polling functionality of controller.
InstancePtr Pointer to the XQspiPsu instance. FlashMsg Pointer to the structure containing transfer data. None
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu_Msg::Flags, XQspiPsu::GenFifoBus, XQspiPsu::GenFifoCS, XQspiPsu::IsReady, XQspiPsu::Msg, XQspiPsu::MsgCnt, XQspiPsu::NumMsg, XQspiPsu_Msg::PollStatusCmd, XQspiPsu_Msg::PollTimeout, XQSPIPSU_CFG_OFFSET, XQspiPsu_CreatePollDataConfig, XQSPIPSU_GEN_FIFO_OFFSET, XQSPIPSU_IER_OFFSET, XQSPIPSU_MSG_FLAG_STRIPE, XQSPIPSU_POLL_CFG_OFFSET, XQspiPsu_ReadReg, XQspiPsu_WriteReg.
Referenced by XQspiPsu_InterruptTransfer.
s32 XQspiPsu_PolledMessageTransfer(XQspiPsu *InstancePtr, XQspiPsu_Msg *Msg, u32 NumMsg)
Performs a transfer on the bus in polled mode.
The messages passed are all transferred on the bus between one CS assert and de-assert. InstancePtr Pointer to the XQspiPsu instance. Msg Pointer to the structure containing transfer data. NumMsg Number of messages to be transferred. XST_SUCCESS if successful.XST_FAILURE if transfer fails.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu::IsUnaligned, XQspiPsu::ReadMode, XQspiPsu::RxBytes, XQspiPsu::TxBytes, XQSPIPSU_CFG_OFFSET, XQspiPsu_GenFifoEntryData, XQSPIPSU_ISR_OFFSET, XQSPIPSU_MSG_FLAG_RX, XQSPIPSU_MSG_FLAG_TX, XQspiPsu_PolledRecvData, XQspiPsu_PolledSendData, XQSPIPSU_READMODE_DMA, XQspiPsu_ReadReg, XQspiPsu_WriteReg.
Referenced by XQspiPsu_PolledTransfer.
void XQspiPsu_IntrDataTransfer(XQspiPsu *InstancePtr, u32 *QspiPsuStatusReg, u8 *DeltaMsgCnt)
Transfers Tx and Rx data.
InstancePtr Pointer to the XQspiPsu instance. QspiPsuStatusReg Status of QSPI status register. DeltaMsgCnt Message count flag. None.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu_Msg::Flags, XQspiPsu::Msg, XQspiPsu::MsgCnt, XQspiPsu::NumMsg, XQspiPsu::ReadMode, XQspiPsu::StatusHandler, XQspiPsu::StatusRef, XQspiPsu_IntrRecvData, XQspiPsu_IntrSendData, XQSPIPSU_ISR_OFFSET, XQSPIPSU_MSG_FLAG_RX, XQSPIPSU_MSG_FLAG_TX, XQSPIPSU_READMODE_DMA, XQspiPsu_ReadReg, XQspiPsu_WriteReg.
Referenced by XQspiPsu_InterruptHandler.
void XQspiPsu_IntrDummyDataTransfer(XQspiPsu *InstancePtr, u32 QspiPsuStatusReg, u8 DeltaMsgCnt)
Transfers Dummy byte.
InstancePtr Pointer to the XQspiPsu instance. QspiPsuStatusReg Status of QSPI status register. DeltaMsgCnt Message count flag. None.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu::IsBusy, XQspiPsu::IsUnaligned, XQspiPsu::Msg, XQspiPsu::MsgCnt, XQspiPsu::NumMsg, XQspiPsu::ReadMode, XQspiPsu_Config::RefClk, XQspiPsu::StatusHandler, XQspiPsu::StatusRef, XQSPIPSU_CFG_OFFSET, XQspiPsu_GenFifoEntryData, XQSPIPSU_IDR_OFFSET, XQSPIPSU_READMODE_DMA, XQspiPsu_ReadReg, XQspiPsu_WriteReg.
Referenced by XQspiPsu_InterruptHandler.
void XQspiPsu_FillTxFifo(XQspiPsu *InstancePtr, XQspiPsu_Msg *Msg, u32 Size)
Fills the TX FIFO as long as there is room in the FIFO or the bytes required to be transmitted.
InstancePtr Pointer to the XQspiPsu instance. Msg Pointer to the structure containing transfer data. Size Number of bytes to be transmitted. None None.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu::IsReady, XQspiPsu_Msg::TxBfrPtr, XQspiPsu::TxBytes, XQSPIPSU_TXD_OFFSET, XQspiPsu_WriteReg.
Referenced by XQspiPsu_IntrSendData, XQspiPsu_PolledSendData, XQspiPsu_TXSetup.
void XQspiPsu_TXSetup(XQspiPsu *InstancePtr, XQspiPsu_Msg *Msg)
Checks the TX buffer in the message and setup the TX FIFO as required.
InstancePtr Pointer to the XQspiPsu instance. Msg Pointer to the structure containing transfer data. None None.
References XQspiPsu_Msg::ByteCount, XQspiPsu::IsReady, XQspiPsu::SendBufferPtr, XQspiPsu_Msg::TxBfrPtr, XQspiPsu::TxBytes, XQspiPsu_FillTxFifo.
Referenced by XQspiPsu_TXRXSetup.
void XQspiPsu_SetupRxDma(const XQspiPsu *InstancePtr, XQspiPsu_Msg *Msg)
Sets up the RX DMA operation.
InstancePtr Pointer to the XQspiPsu instance. Msg Pointer to the structure containing transfer data. None None.
References XQspiPsu_Config::BaseAddress, XQspiPsu_Msg::ByteCount, XQspiPsu::Config, XQspiPsu_Config::IsCacheCoherent, XQspiPsu::IsReady, XQspiPsu_Msg::RxBfrPtr, XQspiPsu::RxBytes, XQSPIPSU_QSPIDMA_DST_ADDR_OFFSET, XQspiPsu_WriteReg.
Referenced by XQspiPsu_RXSetup.
void XQspiPsu_Setup64BRxDma(const XQspiPsu *InstancePtr, XQspiPsu_Msg *Msg)
Sets up the RX DMA operation on a 32-bit Machine For 64-bit DMA transfers.
InstancePtr Pointer to the XQspiPsu instance. Msg Pointer to the structure containing transfer data. None None.
References XQspiPsu_Config::BaseAddress, XQspiPsu_Msg::ByteCount, XQspiPsu::Config, XQspiPsu::IsReady, XQspiPsu_Msg::RxAddr64bit, XQspiPsu::RxBytes, XQSPIPSU_QSPIDMA_DST_ADDR_OFFSET, XQspiPsu_WriteReg.
Referenced by XQspiPsu_RXSetup.
u32 XQspiPsu_SetIOMode(XQspiPsu *InstancePtr, XQspiPsu_Msg *Msg)
Reads remaining bytes after the completion of a DMA transfer using I/O mode.
InstancePtr Pointer to the XQspiPsu instance. Msg Pointer to the structure containing transfer data. XST_SUCCESS if successful.XST_FAILURE if transfer fails.XST_DEVICE_BUSY if a transfer is already in progress. None.
References XQspiPsu_Config::BaseAddress, XQspiPsu_Msg::ByteCount, XQspiPsu::Config, XQspiPsu::IsReady, XQspiPsu::IsUnaligned, XQspiPsu::ReadMode, XQspiPsu_Msg::RxBfrPtr, XQspiPsu::RxBytes, XQSPIPSU_CFG_OFFSET, XQSPIPSU_READMODE_IO, XQspiPsu_ReadReg, XQspiPsu_WriteReg.
Referenced by XQspiPsu_IntrRecvData, XQspiPsu_PolledRecvData.
void XQspiPsu_RXSetup(XQspiPsu *InstancePtr, XQspiPsu_Msg *Msg)
Checks the RX buffers in the message and setup the RX DMA as required.
InstancePtr Pointer to the XQspiPsu instance. Msg Pointer to the structure containing transfer data. None
References XQspiPsu_Msg::ByteCount, XQspiPsu::IsReady, XQspiPsu::ReadMode, XQspiPsu_Msg::RxAddr64bit, XQspiPsu::RxBytes, XQspiPsu_Msg::Xfer64bit, XQSPIPSU_READMODE_DMA, XQSPIPSU_RXADDR_OVER_32BIT, XQspiPsu_Setup64BRxDma, XQspiPsu_SetupRxDma.
Referenced by XQspiPsu_TXRXSetup.
void XQspiPsu_TXRXSetup(XQspiPsu *InstancePtr, XQspiPsu_Msg *Msg, u32 *GenFifoEntry)
Checks the TX/RX buffers in the message and setups up the GENFIFO entries, TX FIFO, or RX DMA as required.
InstancePtr Pointer to the XQspiPsu instance. Msg Pointer to the structure containing transfer data. GenFifoEntry Pointer to the variable in which GENFIFO mask is returned to calling function None
References XQspiPsu_Msg::Flags, XQspiPsu::IsReady, XQspiPsu::RecvBufferPtr, XQspiPsu::RxBytes, XQspiPsu::SendBufferPtr, XQspiPsu::TxBytes, XQSPIPSU_MSG_FLAG_RX, XQSPIPSU_MSG_FLAG_TX, XQspiPsu_RXSetup, XQspiPsu_TXSetup.
Referenced by XQspiPsu_GenFifoEntryData.
void XQspiPsu_GenFifoEntryDataLen(XQspiPsu *InstancePtr, XQspiPsu_Msg *Msg, u32 *GenFifoEntry)
Writes the data length to GENFIFO entries to be transmitted or received.
InstancePtr Pointer to the XQspiPsu instance. Msg Pointer to the structure containing transfer data. GenFifoEntry Pointer to the variable in which GENFIFO mask is returned to the calling function. XST_SUCCESS if successful.XST_FAILURE if transfer fails.XST_DEVICE_BUSY if a transfer is already in progress.
References XQspiPsu_Config::BaseAddress, XQspiPsu_Msg::ByteCount, XQspiPsu::Config, XQspiPsu::IsReady, XQSPIPSU_GEN_FIFO_OFFSET, XQSPIPSU_GENFIFO_EXP_START, XQSPIPSU_GENFIFO_IMM_DATA_MASK, XQspiPsu_WriteReg.
Referenced by XQspiPsu_GenFifoEntryData.
u32 XQspiPsu_CreatePollDataConfig(const XQspiPsu *InstancePtr, const XQspiPsu_Msg *FlashMsg)
Creates Poll configuration register data to write.
InstancePtr Pointer to the XQspiPsu instance. FlashMsg Pointer to the structure containing transfer data. None
References XQspiPsu::GenFifoBus, XQspiPsu::IsReady, XQspiPsu_Msg::PollBusMask, XQspiPsu_Msg::PollData, XQSPIPSU_SELECT_FLASH_BUS_LOWER.
Referenced by XQspiPsu_PollDataConfig.
u32 XQspiPsu_SelectSpiMode(u8 SpiMode)
Selects SPI mode - x1 or x2 or x4.
SpiMode spi or dual or quad. Mask to set desired SPI mode in GENFIFO entry.
References XQSPIPSU_SELECT_MODE_DUALSPI, XQSPIPSU_SELECT_MODE_QUADSPI, XQSPIPSU_SELECT_MODE_SPI.
Referenced by XQspiPsu_GenFifoEntryData.
void XQspiPsu_SetDefaultConfig(XQspiPsu *InstancePtr)
Enables and initializes DMA Mode, set little endain, disable poll timeout, clears prescalar bits and reset thresholds.
InstancePtr Pointer to the XQspiPsu instance. None.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQSPIPSU_CFG_OFFSET, XQSPIPSU_GF_THRESHOLD_OFFSET, XQSPIPSU_LPBK_DLY_ADJ_OFFSET, XQspiPsu_ReadReg, XQSPIPSU_TX_THRESHOLD_OFFSET, XQspiPsu_WriteReg.
Referenced by XQspiPsu_Reset.
void XQspiPsu_ReadRxFifo(XQspiPsu *InstancePtr, XQspiPsu_Msg *Msg, s32 Size)
Reads the specified number of bytes from RX FIFO.
InstancePtr Pointer to the XQspiPsu instance. Msg Pointer to the structure containing transfer data. Size Number of bytes to be read. None
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu::IsReady, XQspiPsu_Msg::RxBfrPtr, XQspiPsu::RxBytes, XQspiPsu_ReadReg, XQSPIPSU_RXD_OFFSET.
Referenced by XQspiPsu_IORead.
void XQspiPsu_IORead(XQspiPsu *InstancePtr, XQspiPsu_Msg *Msg, u32 StatusReg)
Reads data from RXFifo in I/O mode.
InstancePtr Pointer to the XQspiPsu instance. Msg Pointer to the structure containing transfer data. StatusReg Interrupt status Register value. None.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu::IsReady, XQspiPsu::RxBytes, XQspiPsu_ReadReg, XQspiPsu_ReadRxFifo.
Referenced by XQspiPsu_IntrRecvData, XQspiPsu_PolledRecvData.
s32 XQspiPsu_PolledSendData(XQspiPsu *InstancePtr, XQspiPsu_Msg *Msg, s32 Index)
Transfers Tx data on the bus in polled mode.
InstancePtr Pointer to the XQspiPsu instance. Msg Pointer to the structure containing transfer data. Index Msg index to transfer. XST_SUCCESS if successful.XST_FAILURE if transfer fails.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, MAX_DELAY_CNT, XQspiPsu::TxBytes, XQspiPsu_FillTxFifo, XQSPIPSU_ISR_OFFSET.
Referenced by XQspiPsu_PolledMessageTransfer.
s32 XQspiPsu_PolledRecvData(XQspiPsu *InstancePtr, XQspiPsu_Msg *Msg, s32 Index, u32 *IOPending)
Transfers Rx data on the bus in polled mode.
InstancePtr Pointer to the XQspiPsu instance. Msg Pointer to the structure containing transfer data. Index Msg index to transfer. IOPending I/O mode transfer status. XST_SUCCESS if successful.XST_FAILURE if transfer fails.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu_Config::IsCacheCoherent, MAX_DELAY_CNT, XQspiPsu::ReadMode, XQspiPsu::RxBytes, XQspiPsu_IORead, XQSPIPSU_ISR_OFFSET, XQSPIPSU_READMODE_DMA, XQspiPsu_ReadReg, XQSPIPSU_RXADDR_OVER_32BIT, XQspiPsu_SetIOMode, XQspiPsu_WriteReg.
Referenced by XQspiPsu_PolledMessageTransfer.
void XQspiPsu_IntrSendData(XQspiPsu *InstancePtr, u32 QspiPsuStatusReg, u8 *DeltaMsgCnt)
Performs a transfer of Tx data on the bus in interrupt mode.
InstancePtr Pointer to the XQspiPsu instance. QspiPsuStatusReg Status QSPI status register. DeltaMsgCnt Message count flag. None.
References XQspiPsu_Msg::Flags, XQspiPsu::Msg, XQspiPsu::MsgCnt, XQspiPsu::TxBytes, XQspiPsu_FillTxFifo, XQSPIPSU_MSG_FLAG_RX.
Referenced by XQspiPsu_IntrDataTransfer.
void XQspiPsu_IntrRecvData(XQspiPsu *InstancePtr, u32 QspiPsuStatusReg, u32 DmaIntrStatusReg, u8 *DeltaMsgCnt)
Performs a transfer of Rx data on the busin interrupt mode.
InstancePtr Pointer to the XQspiPsu instance. QspiPsuStatusReg Status QSPI status register. DmaIntrStatusReg Status DMA interrupt register. DeltaMsgCnt Message count flag. None.
References XQspiPsu::Config, XQspiPsu_Config::IsCacheCoherent, XQspiPsu::Msg, XQspiPsu::MsgCnt, XQspiPsu::ReadMode, XQspiPsu::RxBytes, XQspiPsu_GenFifoEntryData, XQspiPsu_IORead, XQSPIPSU_READMODE_DMA, XQSPIPSU_RXADDR_OVER_32BIT, XQspiPsu_SetIOMode.
Referenced by XQspiPsu_IntrDataTransfer.
MAX_DELAY_CNT
Max delay count.
Referenced by BulkErase, DieErase, FlashEnableQuadMode, FlashEnterExit4BAddMode, FlashErase, FlashRead, FlashReadID, FlashRegisterWrite, FlashWrite, MultiDieRead, XQspiPsu_Abort, XQspiPsu_CheckDmaDone, XQspiPsu_PolledTransfer, XQspiPsu_StartDmaTransfer.
XQSPIPSU_H_
< prevent circular inclusions
by using protection macros
BYTES256_PER_PAGE
Definitions for Intel, STM, Winbond and Spansion Serial Flash Device geometry.
256 Bytes per Page
BYTES512_PER_PAGE
512 Bytes per Page
BYTES1024_PER_PAGE
1024 Bytes per Page
PAGES16_PER_SECTOR
16 Pages per Sector
PAGES128_PER_SECTOR
128 Pages per Sector
PAGES256_PER_SECTOR
256 Pages per Sector
PAGES512_PER_SECTOR
512 Pages per Sector
PAGES1024_PER_SECTOR
1024 Pages per Sector
NUM_OF_SECTORS2
2 Sectors
NUM_OF_SECTORS4
4 Sectors
NUM_OF_SECTORS8
8 Sector
NUM_OF_SECTORS16
16 Sectors
NUM_OF_SECTORS32
32 Sectors
NUM_OF_SECTORS64
64 Sectors
NUM_OF_SECTORS128
128 Sectors
NUM_OF_SECTORS256
256 Sectors
NUM_OF_SECTORS512
512 Sectors
NUM_OF_SECTORS1024
1024 Sectors
NUM_OF_SECTORS2048
2048 Sectors
NUM_OF_SECTORS4096
4096 Sectors
NUM_OF_SECTORS8192
8192 Sectors
SECTOR_SIZE_64K
64K Sector
SECTOR_SIZE_128K
128K Sector
SECTOR_SIZE_256K
256K Sector
SECTOR_SIZE_512K
512K Sector
XQSPIPSU_READMODE_DMA
DMA read mode.
Referenced by XQspiPsu_Abort, XQspiPsu_CfgInitialize, XQspiPsu_GenFifoEntryData, XQspiPsu_InterruptTransfer, XQspiPsu_IntrDataTransfer, XQspiPsu_IntrDummyDataTransfer, XQspiPsu_IntrRecvData, XQspiPsu_PollDataHandler, XQspiPsu_PolledMessageTransfer, XQspiPsu_PolledRecvData, XQspiPsu_RXSetup, XQspiPsu_SetReadMode, XQspiPsu_StartDmaTransfer.
XQSPIPSU_READMODE_IO
IO read mode.
Referenced by XQspiPsu_GenFifoEntryData, XQspiPsu_SetIOMode, XQspiPsu_SetReadMode, XQspiPsu_StartDmaTransfer.
XQSPIPSU_SELECT_FLASH_CS_LOWER
Select lower flash.
Referenced by FlashErase, GetRealAddr, QspiPsuConfigurePoll, QspiPsuFlashNonBlockingReadExample, QspiPsuInterruptFlashExample, QspiPsuPolledFlashExample, QspiPsuWriteProtectFlashExample, XQspiPsu_SelectFlash.
XQSPIPSU_SELECT_FLASH_CS_UPPER
Select upper flash.
Referenced by FlashErase, GetRealAddr, XQspiPsu_SelectFlash.
XQSPIPSU_SELECT_FLASH_CS_BOTH
Select both flash.
Referenced by GetRealAddr, QspiPsuConfigurePoll, XQspiPsu_SelectFlash.
XQSPIPSU_SELECT_FLASH_BUS_LOWER
Select lower bus flash.
Referenced by FlashErase, GetRealAddr, QspiPsuConfigurePoll, QspiPsuFlashNonBlockingReadExample, QspiPsuInterruptFlashExample, QspiPsuPolledFlashExample, QspiPsuWriteProtectFlashExample, XQspiPsu_CreatePollDataConfig, XQspiPsu_SelectFlash.
XQSPIPSU_SELECT_FLASH_BUS_UPPER
Select upper bus flash.
Referenced by XQspiPsu_SelectFlash.
XQSPIPSU_SELECT_FLASH_BUS_BOTH
Select both bus flash.
Referenced by GetRealAddr, QspiPsuConfigurePoll, XQspiPsu_SelectFlash.
XQSPIPSU_SELECT_MODE_SPI
Select SPI mode.
Referenced by BulkErase, DieErase, FlashEnableQuadMode, FlashEnterExit4BAddMode, FlashErase, FlashRead, FlashReadID, FlashRegisterRead, FlashRegisterWrite, FlashWrite, MultiDieRead, QspiPsuConfigurePoll, XQspiPsu_SelectSpiMode.
XQSPIPSU_SELECT_MODE_DUALSPI
Select dual SPI mode.
Referenced by FlashRead, MultiDieRead, XQspiPsu_SelectSpiMode.
XQSPIPSU_SELECT_MODE_QUADSPI
Select quad SPI mode.
Referenced by FlashRead, MultiDieRead, XQspiPsu_SelectSpiMode.
XQSPIPSU_GENFIFO_CS_SETUP
Chip select setup in GENFIO.
XQSPIPSU_GENFIFO_CS_HOLD
Chip select hold in GENFIFO.
XQSPIPSU_CLK_ACTIVE_LOW_OPTION
Clk Active low option.
XQSPIPSU_CLK_PHASE_1_OPTION
Clk phase 1 option.
XQSPIPSU_MANUAL_START_OPTION
Manual start option.
Referenced by QspiPsuFlashNonBlockingReadExample, QspiPsuInterruptFlashExample, QspiPsuPolledFlashExample, QspiPsuWriteProtectFlashExample, XQspiPsu_ClearOptions, XQspiPsu_SetOptions.
XQSPIPSU_LQSPI_MODE_OPTION
LQSPI mode option.
Referenced by XQspiPsu_SetOptions.
XQSPIPSU_LQSPI_LESS_THEN_SIXTEENMB
LQSPI less Than 16 MB.
Referenced by XQspiPsu_SetOptions.
XQSPIPSU_GENFIFO_EXP_START
Genfifo start.
Referenced by XQspiPsu_GenFifoEntryDataLen.
XQSPIPSU_DMA_BYTES_MAX
DMA bytes max.
Referenced by XQspiPsu_InterruptTransfer, XQspiPsu_PolledTransfer, XQspiPsu_StartDmaTransfer.
XQSPIPSU_CLK_PRESCALE_2
Clock prescale 2.
XQSPIPSU_CLK_PRESCALE_4
Clock prescale 4.
XQSPIPSU_CLK_PRESCALE_8
Clock prescale 8.
Referenced by QspiPsuFlashNonBlockingReadExample, QspiPsuInterruptFlashExample, QspiPsuPolledFlashExample, QspiPsuWriteProtectFlashExample.
XQSPIPSU_CLK_PRESCALE_16
Clock prescale 16.
XQSPIPSU_CLK_PRESCALE_32
Clock prescale 32.
XQSPIPSU_CLK_PRESCALE_64
Clock prescale 64.
XQSPIPSU_CLK_PRESCALE_128
Clock prescale 128.
XQSPIPSU_CLK_PRESCALE_256
Clock prescale 256.
XQSPIPSU_CR_PRESC_MAXIMUM
Prescale max.
Referenced by XQspiPsu_SetClkPrescaler.
XQSPIPSU_CONNECTION_MODE_SINGLE
Single mode connection.
Referenced by GetRealAddr, MultiDieRead, XQspiPsu_WriteProtectToggle.
XQSPIPSU_CONNECTION_MODE_STACKED
Stacked mode connection.
Referenced by DieErase, FlashErase, GetRealAddr.
XQSPIPSU_CONNECTION_MODE_PARALLEL
Parallel mode connection.
Referenced by BulkErase, DieErase, FlashEnableQuadMode, FlashEnterExit4BAddMode, FlashErase, FlashRead, FlashWrite, GetRealAddr, MultiDieRead, QspiPsuConfigurePoll, QspiPsuFlashNonBlockingReadExample, QspiPsuInterruptFlashExample, QspiPsuPolledFlashExample, QspiPsuWriteProtectFlashExample.
XQSPIPSU_FREQ_37_5MHZ
Frequency 375 Mhz.
Referenced by XQspiPsu_SetClkPrescaler.
XQSPIPSU_FREQ_40MHZ
Frequency 40 Mhz.
XQSPIPSU_FREQ_100MHZ
Frequency 100 Mhz.
XQSPIPSU_FREQ_150MHZ
Frequency 150 Mhz.
XQSPIPSU_MSG_FLAG_STRIPE
Stripe Msg flag.
Referenced by BulkErase, DieErase, FlashEnableQuadMode, FlashEnterExit4BAddMode, FlashErase, FlashRead, FlashWrite, MultiDieRead, QspiPsuConfigurePoll, XQspiPsu_GenFifoEntryData, XQspiPsu_PollDataConfig.
XQSPIPSU_MSG_FLAG_RX
Rx Msg flag.
Referenced by BulkErase, DieErase, FlashEnableQuadMode, FlashEnterExit4BAddMode, FlashErase, FlashRead, FlashReadID, FlashRegisterRead, FlashRegisterWrite, FlashWrite, MultiDieRead, XQspiPsu_GenFifoEntryData, XQspiPsu_InterruptHandler, XQspiPsu_InterruptTransfer, XQspiPsu_IntrDataTransfer, XQspiPsu_IntrSendData, XQspiPsu_PolledMessageTransfer, XQspiPsu_PolledTransfer, XQspiPsu_StartDmaTransfer, XQspiPsu_TXRXSetup.
XQSPIPSU_MSG_FLAG_TX
Tx Msg flag.
Referenced by BulkErase, DieErase, FlashEnableQuadMode, FlashEnterExit4BAddMode, FlashErase, FlashRead, FlashReadID, FlashRegisterRead, FlashRegisterWrite, FlashWrite, MultiDieRead, XQspiPsu_InterruptHandler, XQspiPsu_IntrDataTransfer, XQspiPsu_PolledMessageTransfer, XQspiPsu_TXRXSetup.
XQSPIPSU_MSG_FLAG_POLL
POLL Msg flag.
Referenced by QspiPsuConfigurePoll, XQspiPsu_InterruptHandler, XQspiPsu_InterruptTransfer.
XQSPIPSU_RXADDR_OVER_32BIT
Rx address over 32 bit.
Referenced by XQspiPsu_CheckDmaDone, XQspiPsu_IntrRecvData, XQspiPsu_PolledRecvData, XQspiPsu_RXSetup.
XQSPIPSU_SET_WP
GQSPI configuration to toggle WP of flash.
Referenced by QspiPsuWriteProtectFlashExample.
XQspiPsu_Select
select QSPI controller
Referenced by XQspiPsu_CfgInitialize.
XQspiPsu_Enable
Enable QSPI Controller.
Referenced by XQspiPsu_CfgInitialize.
XQspiPsu_Disable
Disable QSPI controller.
XQspiPsu_GetLqspiConfigReg
Read Configuration register of LQSPI Controller.
Referenced by XQspiPsu_LqspiRead.
XQSPIPSU_NUM_OPTIONS
Number of options in option table.
Referenced by XQspiPsu_ClearOptions, XQspiPsu_GetOptions, XQspiPsu_SetOptions.
MAX_DELAY_CNT
Max delay count.
Referenced by XQspiPsu_PolledRecvData, XQspiPsu_PolledSendData.