xqspipsu_options.c
XQSPIPSU_NUM_OPTIONS
Number of options in option table.
Referenced by XQspiPsu_ClearOptions, XQspiPsu_GetOptions, XQspiPsu_SetOptions.
OptionsMap OptionsTable[][]
s32 XQspiPsu_SetOptions(XQspiPsu *InstancePtr, u32 Options)
Sets the options for the QSPIPSU device driver.The options control how the device behaves relative to the QSPIPSU bus.
The device must be idle rather than busy transferring data before setting these device options. InstancePtr Pointer to the XQspiPsu instance. Options Contains the specified options to be set. This is a bit mask where a 1 indicates the option should be turned ON and a 0 indicates no action. One or more bit values may be contained in the mask. See the bit definitions named XQSPIPSU_*_OPTIONS in the file xqspipsu.h. XST_SUCCESS if options are successfully set.XST_DEVICE_BUSY if the device is currently transferring data. The transfer must complete or be aborted before setting options. This function is not thread-safe.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu::IsBusy, XQspiPsu::IsManualstart, XQspiPsu::IsReady, XQSPIPS_BASEADDR, XQSPIPS_LQSPI_CFG_RST_STATE, XQSPIPS_LQSPI_CR_4_BYTE_STATE, XQSPIPS_LQSPI_CR_RST_STATE, XQSPIPSU_CFG_OFFSET, XQSPIPSU_EN_OFFSET, XQSPIPSU_LQSPI_CR_LINEAR_MASK, XQSPIPSU_LQSPI_CR_OFFSET, XQSPIPSU_LQSPI_LESS_THEN_SIXTEENMB, XQSPIPSU_LQSPI_MODE_OPTION, XQSPIPSU_MANUAL_START_OPTION, XQSPIPSU_NUM_OPTIONS, XQspiPsu_ReadReg, XQspiPsu_WriteReg.
Referenced by QspiPsuFlashNonBlockingReadExample, QspiPsuInterruptFlashExample, QspiPsuPolledFlashExample, QspiPsuWriteProtectFlashExample.
s32 XQspiPsu_ClearOptions(XQspiPsu *InstancePtr, u32 Options)
Resets the options for the QSPIPSU device driver.
The options control how the device behaves relative to the QSPIPSU bus. The device must be idle rather than busy transferring data before setting these device options. InstancePtr Pointer to the XQspiPsu instance. Options Contains the specified options to be set. This is a bit mask where a 1 indicates the option should be turned OFF and a 0 indicates no action. One or more bit values may be contained in the mask. See the bit definitions named XQSPIPSU_*_OPTIONS in the file xqspipsu.h. XST_SUCCESS if options are successfully set.XST_DEVICE_BUSY if the device is currently transferring data. The transfer must complete or be aborted before setting options. This function is not thread-safe.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu::IsBusy, XQspiPsu::IsManualstart, XQspiPsu::IsReady, XQSPIPSU_CFG_OFFSET, XQSPIPSU_MANUAL_START_OPTION, XQSPIPSU_NUM_OPTIONS, XQspiPsu_ReadReg, XQspiPsu_WriteReg.
u32 XQspiPsu_GetOptions(const XQspiPsu *InstancePtr)
Gets the options for the QSPIPSU device.
The options control how the device behaves relative to the QSPIPSU bus. InstancePtr Pointer to the XQspiPsu instance. Options contains the specified options currently set. This is a bit value where a 1 means the option is on, and a 0 means the option is off. See the bit definitions named XQSPIPSU_*_OPTIONS in file xqspipsu.h.None.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu::IsReady, XQSPIPSU_CFG_OFFSET, XQSPIPSU_NUM_OPTIONS, XQspiPsu_ReadReg.
s32 XQspiPsu_SetClkPrescaler(const XQspiPsu *InstancePtr, u8 Prescaler)
Configures the clock according to the prescaler passed.
InstancePtr Pointer to the XQspiPsu instance. Prescaler Clock prescaler to be set. XST_SUCCESS if successful.XST_DEVICE_IS_STARTED if the device is already started.XST_DEVICE_BUSY if the device is currently transferring data. It must be stopped to re-initialize.XST_FAILURE if Prescaler value is less than FreqDiv when feedback clock is not enabled. None.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu_Config::InputClockHz, XQspiPsu::IsBusy, XQspiPsu_Config::IsFbClock, XQspiPsu::IsReady, XQSPIPSU_CFG_OFFSET, XQSPIPSU_CR_PRESC_MAXIMUM, XQSPIPSU_FREQ_37_5MHZ, XQspiPsu_ReadReg, XQspiPsu_WriteReg.
Referenced by QspiPsuFlashNonBlockingReadExample, QspiPsuInterruptFlashExample, QspiPsuPolledFlashExample, QspiPsuWriteProtectFlashExample.
void XQspiPsu_SelectFlash(XQspiPsu *InstancePtr, u8 FlashCS, u8 FlashBus)
Used to tell the QSPIPSU driver the hardware flash configuration being used.
This API should be called at least once in the application. If desired, it can be called multiple times when switching between communicating to different flash devices/using different configs. InstancePtr Pointer to the XQspiPsu instance. FlashCS Flash Chip Select. FlashBus Flash Bus (Upper, Lower or Both). XST_SUCCESS if successful.XST_DEVICE_IS_STARTED if the device is already started. It must be stopped to re-initialize. If this function is not called at least once in the application, the driver assumes there is a single flash connected to the lower bus and CS line.
References XQspiPsu::GenFifoBus, XQspiPsu::GenFifoCS, XQspiPsu::IsReady, XQSPIPSU_SELECT_FLASH_BUS_BOTH, XQSPIPSU_SELECT_FLASH_BUS_LOWER, XQSPIPSU_SELECT_FLASH_BUS_UPPER, XQSPIPSU_SELECT_FLASH_CS_BOTH, XQSPIPSU_SELECT_FLASH_CS_LOWER, XQSPIPSU_SELECT_FLASH_CS_UPPER.
Referenced by FlashErase, GetRealAddr, QspiPsuConfigurePoll, QspiPsuFlashNonBlockingReadExample, QspiPsuInterruptFlashExample, QspiPsuPolledFlashExample, QspiPsuWriteProtectFlashExample.
s32 XQspiPsu_SetReadMode(XQspiPsu *InstancePtr, u32 Mode)
Sets the Read mode for the QSPIPSU device driver.
The device must be idle rather than busy transferring data before setting Read mode options. InstancePtr Pointer to the XQspiPsu instance. Mode Contains the specified Mode to be set. See the bit definitions named XQSPIPSU_READMODE_* in the file xqspipsu.h. XST_SUCCESS if options are successfully set.XST_DEVICE_BUSY if the device is currently transferring data. The transfer must complete or be aborted before setting Mode. This function is not thread-safe.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu::IsBusy, XQspiPsu::IsReady, XQspiPsu::ReadMode, XQSPIPSU_CFG_OFFSET, XQSPIPSU_READMODE_DMA, XQSPIPSU_READMODE_IO, XQspiPsu_ReadReg, XQspiPsu_WriteReg.
Referenced by XQspiPsu_PollDataHandler.
void XQspiPsu_SetWP(const XQspiPsu *InstancePtr, u8 Value)
Sets the Write Protect and Hold options for the QSPIPSU device driver.
The device must be idle rather than busy transferring data before setting Write Protect and Hold options. InstancePtr Pointer to the XQspiPsu instance. Value Value of the WP_HOLD bit in configuration register None This function is not thread-safe. This function can only be used with single flash configuration and x1/x2 data mode. This function cannot be used with x4 data mode and dual parallel and stacked flash configuration.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu::IsBusy, XQspiPsu::IsReady, XQSPIPSU_CFG_OFFSET, XQspiPsu_ReadReg, XQspiPsu_WriteReg.
Referenced by QspiPsuWriteProtectFlashExample.