xqspipsu_xfer.c
MAX_DELAY_CNT
Max delay count.
Referenced by XQspiPsu_PolledRecvData, XQspiPsu_PolledSendData.
s32 XQspiPsu_PolledSendData(XQspiPsu *InstancePtr, XQspiPsu_Msg *Msg, s32 Index)
Transfers Tx data on the bus in polled mode.
InstancePtr Pointer to the XQspiPsu instance. Msg Pointer to the structure containing transfer data. Index Msg index to transfer. XST_SUCCESS if successful.XST_FAILURE if transfer fails.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, MAX_DELAY_CNT, XQspiPsu::TxBytes, XQspiPsu_FillTxFifo, XQSPIPSU_ISR_OFFSET.
Referenced by XQspiPsu_PolledMessageTransfer.
s32 XQspiPsu_PolledRecvData(XQspiPsu *InstancePtr, XQspiPsu_Msg *Msg, s32 Index, u32 *IOPending)
Transfers Rx data on the bus in polled mode.
InstancePtr Pointer to the XQspiPsu instance. Msg Pointer to the structure containing transfer data. Index Msg index to transfer. IOPending I/O mode transfer status. XST_SUCCESS if successful.XST_FAILURE if transfer fails.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu_Config::IsCacheCoherent, MAX_DELAY_CNT, XQspiPsu::ReadMode, XQspiPsu::RxBytes, XQspiPsu_IORead, XQSPIPSU_ISR_OFFSET, XQSPIPSU_READMODE_DMA, XQspiPsu_ReadReg, XQSPIPSU_RXADDR_OVER_32BIT, XQspiPsu_SetIOMode, XQspiPsu_WriteReg.
Referenced by XQspiPsu_PolledMessageTransfer.
void XQspiPsu_IntrSendData(XQspiPsu *InstancePtr, u32 QspiPsuStatusReg, u8 *DeltaMsgCnt)
Performs a transfer of Tx data on the bus in interrupt mode.
InstancePtr Pointer to the XQspiPsu instance. QspiPsuStatusReg Status QSPI status register. DeltaMsgCnt Message count flag. None.
References XQspiPsu_Msg::Flags, XQspiPsu::Msg, XQspiPsu::MsgCnt, XQspiPsu::TxBytes, XQspiPsu_FillTxFifo, XQSPIPSU_MSG_FLAG_RX.
Referenced by XQspiPsu_IntrDataTransfer.
void XQspiPsu_IntrRecvData(XQspiPsu *InstancePtr, u32 QspiPsuStatusReg, u32 DmaIntrStatusReg, u8 *DeltaMsgCnt)
Performs a transfer of Rx data on the busin interrupt mode.
InstancePtr Pointer to the XQspiPsu instance. QspiPsuStatusReg Status QSPI status register. DmaIntrStatusReg Status DMA interrupt register. DeltaMsgCnt Message count flag. None.
References XQspiPsu::Config, XQspiPsu_Config::IsCacheCoherent, XQspiPsu::Msg, XQspiPsu::MsgCnt, XQspiPsu::ReadMode, XQspiPsu::RxBytes, XQspiPsu_GenFifoEntryData, XQspiPsu_IORead, XQSPIPSU_READMODE_DMA, XQSPIPSU_RXADDR_OVER_32BIT, XQspiPsu_SetIOMode.
Referenced by XQspiPsu_IntrDataTransfer.