xqspipsu_control.c
void XQspiPsu_GenFifoEntryData(XQspiPsu *InstancePtr, XQspiPsu_Msg *Msg)
Writes the GENFIFO entries to transmit the messages requested.
InstancePtr Pointer to the XQspiPsu instance. Msg Pointer to the structure containing transfer data. XST_SUCCESS if successful.XST_FAILURE if transfer fails.XST_DEVICE_BUSY if a transfer is already in progress.
References XQspiPsu_Config::BaseAddress, XQspiPsu_Msg::BusWidth, XQspiPsu_Msg::ByteCount, XQspiPsu::Config, XQspiPsu_Msg::Flags, XQspiPsu::GenFifoBus, XQspiPsu::GenFifoCS, XQspiPsu::IsReady, XQspiPsu::IsUnaligned, XQspiPsu::ReadMode, XQSPIPSU_CFG_OFFSET, XQSPIPSU_GEN_FIFO_OFFSET, XQspiPsu_GenFifoEntryDataLen, XQSPIPSU_MSG_FLAG_RX, XQSPIPSU_MSG_FLAG_STRIPE, XQSPIPSU_READMODE_DMA, XQSPIPSU_READMODE_IO, XQspiPsu_ReadReg, XQspiPsu_SelectSpiMode, XQspiPsu_TXRXSetup, XQspiPsu_WriteReg.
Referenced by XQspiPsu_InterruptTransfer, XQspiPsu_IntrDummyDataTransfer, XQspiPsu_IntrRecvData, XQspiPsu_PolledMessageTransfer, XQspiPsu_StartDmaTransfer.
void XQspiPsu_PollDataConfig(XQspiPsu *InstancePtr, XQspiPsu_Msg *FlashMsg)
Enables the polling functionality of controller.
InstancePtr Pointer to the XQspiPsu instance. FlashMsg Pointer to the structure containing transfer data. None
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu_Msg::Flags, XQspiPsu::GenFifoBus, XQspiPsu::GenFifoCS, XQspiPsu::IsReady, XQspiPsu::Msg, XQspiPsu::MsgCnt, XQspiPsu::NumMsg, XQspiPsu_Msg::PollStatusCmd, XQspiPsu_Msg::PollTimeout, XQSPIPSU_CFG_OFFSET, XQspiPsu_CreatePollDataConfig, XQSPIPSU_GEN_FIFO_OFFSET, XQSPIPSU_IER_OFFSET, XQSPIPSU_MSG_FLAG_STRIPE, XQSPIPSU_POLL_CFG_OFFSET, XQspiPsu_ReadReg, XQspiPsu_WriteReg.
Referenced by XQspiPsu_InterruptTransfer.
s32 XQspiPsu_PolledMessageTransfer(XQspiPsu *InstancePtr, XQspiPsu_Msg *Msg, u32 NumMsg)
Performs a transfer on the bus in polled mode.
The messages passed are all transferred on the bus between one CS assert and de-assert. InstancePtr Pointer to the XQspiPsu instance. Msg Pointer to the structure containing transfer data. NumMsg Number of messages to be transferred. XST_SUCCESS if successful.XST_FAILURE if transfer fails.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu::IsUnaligned, XQspiPsu::ReadMode, XQspiPsu::RxBytes, XQspiPsu::TxBytes, XQSPIPSU_CFG_OFFSET, XQspiPsu_GenFifoEntryData, XQSPIPSU_ISR_OFFSET, XQSPIPSU_MSG_FLAG_RX, XQSPIPSU_MSG_FLAG_TX, XQspiPsu_PolledRecvData, XQspiPsu_PolledSendData, XQSPIPSU_READMODE_DMA, XQspiPsu_ReadReg, XQspiPsu_WriteReg.
Referenced by XQspiPsu_PolledTransfer.
void XQspiPsu_IntrDataTransfer(XQspiPsu *InstancePtr, u32 *QspiPsuStatusReg, u8 *DeltaMsgCnt)
Transfers Tx and Rx data.
InstancePtr Pointer to the XQspiPsu instance. QspiPsuStatusReg Status of QSPI status register. DeltaMsgCnt Message count flag. None.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu_Msg::Flags, XQspiPsu::Msg, XQspiPsu::MsgCnt, XQspiPsu::NumMsg, XQspiPsu::ReadMode, XQspiPsu::StatusHandler, XQspiPsu::StatusRef, XQspiPsu_IntrRecvData, XQspiPsu_IntrSendData, XQSPIPSU_ISR_OFFSET, XQSPIPSU_MSG_FLAG_RX, XQSPIPSU_MSG_FLAG_TX, XQSPIPSU_READMODE_DMA, XQspiPsu_ReadReg, XQspiPsu_WriteReg.
Referenced by XQspiPsu_InterruptHandler.
void XQspiPsu_IntrDummyDataTransfer(XQspiPsu *InstancePtr, u32 QspiPsuStatusReg, u8 DeltaMsgCnt)
Transfers Dummy byte.
InstancePtr Pointer to the XQspiPsu instance. QspiPsuStatusReg Status of QSPI status register. DeltaMsgCnt Message count flag. None.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu::IsBusy, XQspiPsu::IsUnaligned, XQspiPsu::Msg, XQspiPsu::MsgCnt, XQspiPsu::NumMsg, XQspiPsu::ReadMode, XQspiPsu_Config::RefClk, XQspiPsu::StatusHandler, XQspiPsu::StatusRef, XQSPIPSU_CFG_OFFSET, XQspiPsu_GenFifoEntryData, XQSPIPSU_IDR_OFFSET, XQSPIPSU_READMODE_DMA, XQspiPsu_ReadReg, XQspiPsu_WriteReg.
Referenced by XQspiPsu_InterruptHandler.