xqspipsu_sinit.c
XQspiPsu_Config * XQspiPsu_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XQspiPsu_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xqspipsu.h for the definition of XQspiPsu_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XQspiPsu_Config::Name, XQspiPsu_ConfigTable.
Referenced by QspiPsuFlashNonBlockingReadExample, QspiPsuInterruptFlashExample, QspiPsuPolledFlashExample, QspiPsuWriteProtectFlashExample.