xqspipsu.c
MAX_DELAY_CNT
Max delay count.
Referenced by BulkErase, DieErase, FlashEnableQuadMode, FlashEnterExit4BAddMode, FlashErase, FlashRead, FlashReadID, FlashRegisterWrite, FlashWrite, MultiDieRead, XQspiPsu_Abort, XQspiPsu_CheckDmaDone, XQspiPsu_PolledTransfer, XQspiPsu_StartDmaTransfer.
s32 XQspiPsu_CfgInitialize(XQspiPsu *InstancePtr, const XQspiPsu_Config *ConfigPtr, UINTPTR EffectiveAddr)
Initializes a specific XQspiPsu instance as such the driver is ready to use.
InstancePtr Pointer to the XQspiPsu instance. ConfigPtr Reference to a structure containing information about a specific QSPIPSU device. This function initializes an InstancePtr object for a specific device specified by the contents of Config. EffectiveAddr Device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, use ConfigPtr->Config. BaseAddress for this device. XST_SUCCESS if successful.XST_DEVICE_IS_STARTED if the device is already started. It must be stopped to re-initialize. None.
References XQspiPsu_Config::BaseAddress, XQspiPsu_Config::BaudRateDiv, XQspiPsu_Config::BusWidth, XQspiPsu::Config, XQspiPsu_Config::ConnectionMode, XQspiPsu::GenFifoBufferPtr, XQspiPsu::GenFifoBus, XQspiPsu::GenFifoCS, XQspiPsu::GenFifoEntries, XQspiPsu_Config::InputClockHz, XQspiPsu::IsBusy, XQspiPsu_Config::IsCacheCoherent, XQspiPsu_Config::IsFbClock, XQspiPsu::IsManualstart, XQspiPsu::IsReady, XQspiPsu::IsUnaligned, XQspiPsu::ReadMode, XQspiPsu::RecvBufferPtr, XQspiPsu_Config::RefClk, XQspiPsu::RxBytes, XQspiPsu::SendBufferPtr, XQspiPsu::StatusHandler, XQspiPsu::TxBytes, XQspiPsu_Enable, XQSPIPSU_READMODE_DMA, XQspiPsu_Reset, XQspiPsu_Select.
Referenced by QspiPsuFlashNonBlockingReadExample, QspiPsuInterruptFlashExample, QspiPsuPolledFlashExample, QspiPsuWriteProtectFlashExample.
void XQspiPsu_Idle(const XQspiPsu *InstancePtr)
Stops the transfer of data to internal DST FIFO from stream interface and also stops the issuing of new write commands to memory.
By calling this API, any ongoing Dma transfers will be paused and DMA will not issue AXI write commands to memory InstancePtr Pointer to the XQspiPsu instance. None. None.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu::IsReady, XQspiPsu_Config::RefClk, XQSPIPSU_EN_OFFSET, XQspiPsu_ReadReg, XQspiPsu_WriteReg.
void XQspiPsu_Reset(XQspiPsu *InstancePtr)
Resets the QSPIPSU device.
Reset must only be called after the driver has been initialized. Any data transfer that is in progress is aborted.The upper layer software is responsible for re-configuring (if necessary) and restarting the QSPIPSU device after the reset. InstancePtr Pointer to the XQspiPsu instance. None. None.
References XQspiPsu_Abort, XQspiPsu_SetDefaultConfig.
Referenced by XQspiPsu_CfgInitialize.
void XQspiPsu_Abort(XQspiPsu *InstancePtr)
Aborts a transfer in progress.
InstancePtr Pointer to the XQspiPsu instance. None. None.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu::GenFifoEntries, XQspiPsu::IsBusy, MAX_DELAY_CNT, XQspiPsu::ReadMode, XQspiPsu::RxBytes, XQspiPsu::TxBytes, XQSPIPSU_CFG_OFFSET, XQSPIPSU_FIFO_CTRL_OFFSET, XQSPIPSU_IDR_OFFSET, XQSPIPSU_ISR_OFFSET, XQSPIPSU_READMODE_DMA, XQspiPsu_ReadReg, XQspiPsu_WriteReg.
Referenced by XQspiPsu_Reset.
void XQspiPsu_PollDataHandler(XQspiPsu *InstancePtr, u32 StatusReg)
This is the handler for polling functionality of controller.
It reads data from RXFIFO, since when data from the flash device (status data) matched with configured value in poll_cfg, then controller writes the matched data into RXFIFO. InstancePtr Pointer to the XQspiPsu instance. StatusReg Interrupt status Register value. None. None.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu::IsBusy, XQspiPsu::IsReady, XQspiPsu::ReadMode, XQspiPsu::StatusHandler, XQspiPsu::StatusRef, XQSPIPSU_IDR_OFFSET, XQSPIPSU_READMODE_DMA, XQspiPsu_ReadReg, XQSPIPSU_RXD_OFFSET, XQspiPsu_SetReadMode, XQspiPsu_WriteReg.
Referenced by XQspiPsu_InterruptHandler.
s32 XQspiPsu_PolledTransfer(XQspiPsu *InstancePtr, XQspiPsu_Msg *Msg, u32 NumMsg)
Performs a transfer on the bus in polled mode.
The messages passed are all transferred on the bus between one CS assert and de-assert. InstancePtr Pointer to the XQspiPsu instance. Msg Pointer to the structure containing transfer data. NumMsg Number of messages to be transferred. XST_SUCCESS if successful.XST_FAILURE if transfer fails.XST_DEVICE_BUSY if a transfer is already in progress. None.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu_Msg::Flags, XQspiPsu::IsBusy, XQspiPsu::IsReady, MAX_DELAY_CNT, XQspiPsu_Config::RefClk, XQSPIPSU_DMA_BYTES_MAX, XQSPIPSU_ISR_OFFSET, XQSPIPSU_MSG_FLAG_RX, XQspiPsu_PolledMessageTransfer.
Referenced by FlashRegisterRead, FlashRegisterWrite.
s32 XQspiPsu_InterruptTransfer(XQspiPsu *InstancePtr, XQspiPsu_Msg *Msg, u32 NumMsg)
Initiates a transfer on the bus and enables interrupts.
The transfer is completed by the interrupt handler. The messages passed are all transferred on the bus between one CS assert and de-assert. InstancePtr Pointer to the XQspiPsu instance. Msg Pointer to the structure containing transfer data. NumMsg Number of messages to be transferred. XST_SUCCESS if successful.XST_FAILURE if transfer fails.XST_DEVICE_BUSY if a transfer is already in progress. None.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu_Msg::Flags, XQspiPsu::IsBusy, XQspiPsu::IsReady, XQspiPsu::Msg, XQspiPsu::MsgCnt, XQspiPsu::NumMsg, XQspiPsu::ReadMode, XQspiPsu_Config::RefClk, XQSPIPSU_DMA_BYTES_MAX, XQspiPsu_GenFifoEntryData, XQSPIPSU_IER_OFFSET, XQSPIPSU_MSG_FLAG_POLL, XQSPIPSU_MSG_FLAG_RX, XQspiPsu_PollDataConfig, XQSPIPSU_READMODE_DMA, XQspiPsu_WriteReg.
Referenced by BulkErase, DieErase, FlashEnableQuadMode, FlashEnterExit4BAddMode, FlashErase, FlashRead, FlashReadID, FlashWrite, MultiDieRead.
s32 XQspiPsu_InterruptHandler(XQspiPsu *InstancePtr)
Handles interrupt based transfers by acting on GENFIFO and DMA interurpts.
InstancePtr Pointer to the XQspiPsu instance. XST_SUCCESS if successful.XST_FAILURE if transfer fails. None.
References XQspiPsu_Msg::Flags, XQspiPsu::IsReady, XQspiPsu::Msg, XQspiPsu::MsgCnt, XQspiPsu::NumMsg, XQspiPsu_IntrDataTransfer, XQspiPsu_IntrDummyDataTransfer, XQSPIPSU_MSG_FLAG_POLL, XQSPIPSU_MSG_FLAG_RX, XQSPIPSU_MSG_FLAG_TX, XQspiPsu_PollDataHandler.
Referenced by QspiPsuInterruptFlashExample, QspiPsuWriteProtectFlashExample.
void XQspiPsu_SetStatusHandler(XQspiPsu *InstancePtr, void *CallBackRef, XQspiPsu_StatusHandler FuncPointer)
Sets the status callback function, the status handler, which the driver calls when it encounters conditions that should be reported to upper layer software.
The handler executes in an interrupt context, so it must minimize the amount of processing performed. One of the following status events is passed to the status handler.XST_SPI_TRANSFER_DONE The requested data transfer is doneXST_SPI_TRANSMIT_UNDERRUN As a slave device, the master clocked data but there were none available in the transmit register/FIFO. This typically means the slave application did not issue a transfer request fast enough, or the processor/driver could not fill the transmit register/FIFO fast enough.XST_SPI_RECEIVE_OVERRUN The QSPIPSU device lost data. Data was received but the receive data register/FIFO was full. InstancePtr Pointer to the XQspiPsu instance. CallBackRef Upper layer callback reference passed back when the callback function is invoked. FuncPointer Pointer to the callback function. None. The handler is called within interrupt context, so it should do its work quickly and queue potentially time-consuming work to a task-level thread.
References XQspiPsu::IsReady, XQspiPsu::StatusHandler, XQspiPsu::StatusRef.
Referenced by QspiPsuInterruptFlashExample, QspiPsuWriteProtectFlashExample.
void XQspiPsu_WriteProtectToggle(const XQspiPsu *InstancePtr, u32 Toggle)
Enables/disables Write Protect pin on the flash parts.
InstancePtr Pointer to the QSPIPSU driver component to use. Toggle Value of the GPIO pin None By default, the Write Protect pin as per the QSPI controller is driven High which means no write protection. Calling this function once will enable the protection.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu_Config::ConnectionMode, XQspiPsu::IsReady, XQSPIPSU_CONNECTION_MODE_SINGLE, XQSPIPSU_GPIO_OFFSET, XQspiPsu_WriteReg.
Referenced by QspiPsuWriteProtectFlashExample.
s32 XQspiPsu_StartDmaTransfer(XQspiPsu *InstancePtr, XQspiPsu_Msg *Msg, u32 NumMsg)
Starts a DMA transfer.
InstancePtr Pointer to the XQspiPsu instance. Msg Pointer to the structure containing transfer data. NumMsg Number of messages to be transferred. XST_SUCCESS if successful.XST_FAILURE if ByteCount is greater than XQSPIPSU_DMA_BYTES_MAX.XST_DEVICE_BUSY if a transfer is already in progress. None.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu_Msg::Flags, XQspiPsu::IsBusy, XQspiPsu::IsManualstart, XQspiPsu::IsReady, MAX_DELAY_CNT, XQspiPsu::Msg, XQspiPsu::ReadMode, XQspiPsu::TxBytes, XQSPIPSU_CFG_OFFSET, XQSPIPSU_DMA_BYTES_MAX, XQspiPsu_GenFifoEntryData, XQSPIPSU_ISR_OFFSET, XQSPIPSU_MSG_FLAG_RX, XQSPIPSU_READMODE_DMA, XQSPIPSU_READMODE_IO, XQspiPsu_ReadReg, XQspiPsu_WriteReg.
s32 XQspiPsu_CheckDmaDone(XQspiPsu *InstancePtr)
Checks for DMA transfer complete.
InstancePtr Pointer to the XQspiPsu instance. XST_SUCCESS if DMA transfer complete.XST_FAILURE if DMA transfer is not completed. None.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu::IsBusy, XQspiPsu_Config::IsCacheCoherent, XQspiPsu::IsManualstart, XQspiPsu::IsReady, MAX_DELAY_CNT, XQspiPsu::Msg, XQspiPsu_Msg::RxAddr64bit, XQspiPsu_Msg::RxBfrPtr, XQspiPsu::RxBytes, XQspiPsu_Msg::Xfer64bit, XQSPIPSU_CFG_OFFSET, XQSPIPSU_ISR_OFFSET, XQspiPsu_ReadReg, XQSPIPSU_RXADDR_OVER_32BIT, XQspiPsu_WriteReg.