xqspipsu_hw.c
void XQspiPsu_FillTxFifo(XQspiPsu *InstancePtr, XQspiPsu_Msg *Msg, u32 Size)
Fills the TX FIFO as long as there is room in the FIFO or the bytes required to be transmitted.
InstancePtr Pointer to the XQspiPsu instance. Msg Pointer to the structure containing transfer data. Size Number of bytes to be transmitted. None None.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu::IsReady, XQspiPsu_Msg::TxBfrPtr, XQspiPsu::TxBytes, XQSPIPSU_TXD_OFFSET, XQspiPsu_WriteReg.
Referenced by XQspiPsu_IntrSendData, XQspiPsu_PolledSendData, XQspiPsu_TXSetup.
void XQspiPsu_TXSetup(XQspiPsu *InstancePtr, XQspiPsu_Msg *Msg)
Checks the TX buffer in the message and setup the TX FIFO as required.
InstancePtr Pointer to the XQspiPsu instance. Msg Pointer to the structure containing transfer data. None None.
References XQspiPsu_Msg::ByteCount, XQspiPsu::IsReady, XQspiPsu::SendBufferPtr, XQspiPsu_Msg::TxBfrPtr, XQspiPsu::TxBytes, XQspiPsu_FillTxFifo.
Referenced by XQspiPsu_TXRXSetup.
void XQspiPsu_SetupRxDma(const XQspiPsu *InstancePtr, XQspiPsu_Msg *Msg)
Sets up the RX DMA operation.
InstancePtr Pointer to the XQspiPsu instance. Msg Pointer to the structure containing transfer data. None None.
References XQspiPsu_Config::BaseAddress, XQspiPsu_Msg::ByteCount, XQspiPsu::Config, XQspiPsu_Config::IsCacheCoherent, XQspiPsu::IsReady, XQspiPsu_Msg::RxBfrPtr, XQspiPsu::RxBytes, XQSPIPSU_QSPIDMA_DST_ADDR_OFFSET, XQspiPsu_WriteReg.
Referenced by XQspiPsu_RXSetup.
void XQspiPsu_Setup64BRxDma(const XQspiPsu *InstancePtr, XQspiPsu_Msg *Msg)
Sets up the RX DMA operation on a 32-bit Machine For 64-bit DMA transfers.
InstancePtr Pointer to the XQspiPsu instance. Msg Pointer to the structure containing transfer data. None None.
References XQspiPsu_Config::BaseAddress, XQspiPsu_Msg::ByteCount, XQspiPsu::Config, XQspiPsu::IsReady, XQspiPsu_Msg::RxAddr64bit, XQspiPsu::RxBytes, XQSPIPSU_QSPIDMA_DST_ADDR_OFFSET, XQspiPsu_WriteReg.
Referenced by XQspiPsu_RXSetup.
u32 XQspiPsu_SetIOMode(XQspiPsu *InstancePtr, XQspiPsu_Msg *Msg)
Reads remaining bytes after the completion of a DMA transfer using I/O mode.
InstancePtr Pointer to the XQspiPsu instance. Msg Pointer to the structure containing transfer data. XST_SUCCESS if successful.XST_FAILURE if transfer fails.XST_DEVICE_BUSY if a transfer is already in progress. None.
References XQspiPsu_Config::BaseAddress, XQspiPsu_Msg::ByteCount, XQspiPsu::Config, XQspiPsu::IsReady, XQspiPsu::IsUnaligned, XQspiPsu::ReadMode, XQspiPsu_Msg::RxBfrPtr, XQspiPsu::RxBytes, XQSPIPSU_CFG_OFFSET, XQSPIPSU_READMODE_IO, XQspiPsu_ReadReg, XQspiPsu_WriteReg.
Referenced by XQspiPsu_IntrRecvData, XQspiPsu_PolledRecvData.
void XQspiPsu_RXSetup(XQspiPsu *InstancePtr, XQspiPsu_Msg *Msg)
Checks the RX buffers in the message and setup the RX DMA as required.
InstancePtr Pointer to the XQspiPsu instance. Msg Pointer to the structure containing transfer data. None
References XQspiPsu_Msg::ByteCount, XQspiPsu::IsReady, XQspiPsu::ReadMode, XQspiPsu_Msg::RxAddr64bit, XQspiPsu::RxBytes, XQspiPsu_Msg::Xfer64bit, XQSPIPSU_READMODE_DMA, XQSPIPSU_RXADDR_OVER_32BIT, XQspiPsu_Setup64BRxDma, XQspiPsu_SetupRxDma.
Referenced by XQspiPsu_TXRXSetup.
void XQspiPsu_TXRXSetup(XQspiPsu *InstancePtr, XQspiPsu_Msg *Msg, u32 *GenFifoEntry)
Checks the TX/RX buffers in the message and setups up the GENFIFO entries, TX FIFO, or RX DMA as required.
InstancePtr Pointer to the XQspiPsu instance. Msg Pointer to the structure containing transfer data. GenFifoEntry Pointer to the variable in which GENFIFO mask is returned to calling function None
References XQspiPsu_Msg::Flags, XQspiPsu::IsReady, XQspiPsu::RecvBufferPtr, XQspiPsu::RxBytes, XQspiPsu::SendBufferPtr, XQspiPsu::TxBytes, XQSPIPSU_MSG_FLAG_RX, XQSPIPSU_MSG_FLAG_TX, XQspiPsu_RXSetup, XQspiPsu_TXSetup.
Referenced by XQspiPsu_GenFifoEntryData.
void XQspiPsu_GenFifoEntryDataLen(XQspiPsu *InstancePtr, XQspiPsu_Msg *Msg, u32 *GenFifoEntry)
Writes the data length to GENFIFO entries to be transmitted or received.
InstancePtr Pointer to the XQspiPsu instance. Msg Pointer to the structure containing transfer data. GenFifoEntry Pointer to the variable in which GENFIFO mask is returned to the calling function. XST_SUCCESS if successful.XST_FAILURE if transfer fails.XST_DEVICE_BUSY if a transfer is already in progress.
References XQspiPsu_Config::BaseAddress, XQspiPsu_Msg::ByteCount, XQspiPsu::Config, XQspiPsu::IsReady, XQSPIPSU_GEN_FIFO_OFFSET, XQSPIPSU_GENFIFO_EXP_START, XQSPIPSU_GENFIFO_IMM_DATA_MASK, XQspiPsu_WriteReg.
Referenced by XQspiPsu_GenFifoEntryData.
u32 XQspiPsu_CreatePollDataConfig(const XQspiPsu *InstancePtr, const XQspiPsu_Msg *FlashMsg)
Creates Poll configuration register data to write.
InstancePtr Pointer to the XQspiPsu instance. FlashMsg Pointer to the structure containing transfer data. None
References XQspiPsu::GenFifoBus, XQspiPsu::IsReady, XQspiPsu_Msg::PollBusMask, XQspiPsu_Msg::PollData, XQSPIPSU_SELECT_FLASH_BUS_LOWER.
Referenced by XQspiPsu_PollDataConfig.
u32 XQspiPsu_SelectSpiMode(u8 SpiMode)
Selects SPI mode - x1 or x2 or x4.
SpiMode spi or dual or quad. Mask to set desired SPI mode in GENFIFO entry.
References XQSPIPSU_SELECT_MODE_DUALSPI, XQSPIPSU_SELECT_MODE_QUADSPI, XQSPIPSU_SELECT_MODE_SPI.
Referenced by XQspiPsu_GenFifoEntryData.
void XQspiPsu_SetDefaultConfig(XQspiPsu *InstancePtr)
Enables and initializes DMA Mode, set little endain, disable poll timeout, clears prescalar bits and reset thresholds.
InstancePtr Pointer to the XQspiPsu instance. None.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQSPIPSU_CFG_OFFSET, XQSPIPSU_GF_THRESHOLD_OFFSET, XQSPIPSU_LPBK_DLY_ADJ_OFFSET, XQspiPsu_ReadReg, XQSPIPSU_TX_THRESHOLD_OFFSET, XQspiPsu_WriteReg.
Referenced by XQspiPsu_Reset.
void XQspiPsu_ReadRxFifo(XQspiPsu *InstancePtr, XQspiPsu_Msg *Msg, s32 Size)
Reads the specified number of bytes from RX FIFO.
InstancePtr Pointer to the XQspiPsu instance. Msg Pointer to the structure containing transfer data. Size Number of bytes to be read. None
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu::IsReady, XQspiPsu_Msg::RxBfrPtr, XQspiPsu::RxBytes, XQspiPsu_ReadReg, XQSPIPSU_RXD_OFFSET.
Referenced by XQspiPsu_IORead.
void XQspiPsu_IORead(XQspiPsu *InstancePtr, XQspiPsu_Msg *Msg, u32 StatusReg)
Reads data from RXFifo in I/O mode.
InstancePtr Pointer to the XQspiPsu instance. Msg Pointer to the structure containing transfer data. StatusReg Interrupt status Register value. None.
References XQspiPsu_Config::BaseAddress, XQspiPsu::Config, XQspiPsu::IsReady, XQspiPsu::RxBytes, XQspiPsu_ReadReg, XQspiPsu_ReadRxFifo.
Referenced by XQspiPsu_IntrRecvData, XQspiPsu_PolledRecvData.