nandps
XNANDPS_MEMC_STATUS_STATE_MASK
Memory controller operating state mask.
XNANDPS_MEMC_STATUS_INT_EN0_MASK
Memory controller interface 0 interrupt enable mask.
XNANDPS_MEMC_STATUS_INT_EN1_MASK
Memory controller interface 1 interrupt enable mask.
XNANDPS_MEMC_STATUS_INT_STATUS0_MASK
Memory controller interface 0 interrupt status mask.
XNANDPS_MEMC_STATUS_INT_STATUS1_MASK
Memory controller interface 1 interrupt status mask.
XNANDPS_MEMC_STATUS_RAW_INT_STATUS0_MASK
Memory controller interface 0 raw interrupt status mask.
XNANDPS_MEMC_STATUS_RAW_INT_STATUS1_MASK
Memory controller interface 1 raw interrupt status mask.
XNANDPS_MEMC_STATUS_ECC_INT_EN0_MASK
Memory controller interface 0 ECC interrupt enable mask.
XNANDPS_MEMC_STATUS_ECC_INT_EN1_MASK
Memory controller interface 1 ECC interrupt enable mask.
XNANDPS_MEMC_STATUS_ECC_INT0_MASK
Memory controller interface 0 ECC interrupt status mask.
XNANDPS_MEMC_STATUS_ECC_INT1_MASK
Memory controller interface 1 ECC interrupt status mask.
XNANDPS_MEMC_STATUS_RAW_ECC_INT0_MASK
Memory controller interface 0 raw ECC interrupt status mask.
XNANDPS_MEMC_STATUS_RAW_ECC_INT1_MASK
Memory controller interface 1 raw ECC interrupt status mask.
XNANDPS_MEMC_IF_CONFIG_MEMORY_TYPE0_MASK
Memory controller interface 0 type mask.
XNANDPS_MEMC_IF_CONFIG_MEMORY_CHIPS0_MASK
Memory controller interface 0 chip select mask.
XNANDPS_MEMC_IF_CONFIG_MEMORY_WIDTH0_MASK
Memory controller interface 0 data width mask.
XNANDPS_MEMC_IF_CONFIG_REMAP0_MASK
Memory controller interface 0 remap0 mask.
XNANDPS_MEMC_IF_CONFIG_MEMORY_TYPE1_MASK
Memory controller interface 1 type mask.
XNANDPS_MEMC_IF_CONFIG_MEMORY_CHIPS1_MASK
Memory controller interface 1 chip select mask.
XNANDPS_MEMC_IF_CONFIG_MEMORY_WIDTH1_MASK
Memory controller interface 1 data width mask.
XNANDPS_MEMC_IF_CONFIG_REMAP1_MASK
Memory controller interface 1 remap0 mask.
XNANDPS_MEMC_IF_CONFIG_EX_MONITORS_MASK
Memory controller interface exclusive masks mask.
XNANDPS_MEMC_SET_CONFIG_INT_ENABLE0_MASK
Memory controller interfce0 interrupt enable mask.
XNANDPS_MEMC_SET_CONFIG_INT_ENABLE1_MASK
Memory controller interfce1 interrupt enable mask.
XNANDPS_MEMC_SET_CONFIG_LOW_POWER_REQ_MASK
Memory controller low power state mask.
XNANDPS_MEMC_SET_CONFIG_ECC_INT_ENABLE0_MASK
Memory controller interfce0 ECC interrupt enable mask.
XNANDPS_MEMC_SET_CONFIG_ECC_INT_ENABLE1_MASK
Memory controller interfce1 ECC interrupt enable mask.
XNANDPS_MEMC_CLR_CONFIG_INT_DISABLE0_MASK
Memory controller interface 0 interrupt disable mask.
XNANDPS_MEMC_CLR_CONFIG_INT_DISABLE1_MASK
Memory controller interface 1 interrupt disable mask.
XNANDPS_MEMC_CLR_CONFIG_LOW_POWER_EXIT_MASK
Memory controller low power exit mask.
XNANDPS_MEMC_CLR_CONFIG_INT_CLR0_MASK
Memory controller interface0 interrupt clear mask.
XNANDPS_MEMC_CLR_CONFIG_INT_CLR1_MASK
Memory controller interface1 interrupt clear mask.
Referenced by XNandPs_EraseBlock, XNandPs_Read, XNandPs_ReadCache, XNandPs_ReadSpareBytes, XNandPs_WriteSpareBytes.
XNANDPS_MEMC_CLR_CONFIG_ECC_INT_DISABLE0_MASK
Memory controller interface0 ECC interrupt disable mask.
XNANDPS_MEMC_CLR_CONFIG_ECC_INT_DISABLE1_MASK
Memory controller interface1 ECC interrupt disable mask.
XNANDPS_DIRECT_CMD_ADDR_MASK
Direct command address mask.
XNANDPS_DIRECT_CMD_SET_CRE_MASK
Direct command set cre mask.
XNANDPS_DIRECT_CMD_TYPE_MASK
Direct command type mask.
XNANDPS_DIRECT_CMD_CHIP_SELECT_MASK
Direct command chip select mask.
XNANDPS_DIRECT_CMD_SET_CRE_SHIFT
Direct command set_cre shift.
XNANDPS_DIRECT_CMD_CMD_TYPE_SHIFT
Direct command cmd_type shift.
XNANDPS_DIRECT_CMD_CHIP_SELECT_SHIFT
Direct command chip select shift.
XNANDPS_SET_CYCLES_SET_T0_MASK
Set cycles set_t0 mask.
XNANDPS_SET_CYCLES_SET_T1_MASK
Set cycles set_t1 mask.
XNANDPS_SET_CYCLES_SET_T2_MASK
Set cycles set_t2 mask.
XNANDPS_SET_CYCLES_SET_T3_MASK
Set cycles set_t3 mask.
XNANDPS_SET_CYCLES_SET_T4_MASK
Set cycles set_t4 mask.
XNANDPS_SET_CYCLES_SET_T5_MASK
Set cycles set_t5 mask.
XNANDPS_SET_CYCLES_SET_T6_MASK
Set cycles set_t6 mask.
XNANDPS_SET_CYCLES_SET_T0_SHIFT
Set cycles set_t0 shift.
XNANDPS_SET_CYCLES_SET_T1_SHIFT
Set cycles set_t1 shift.
XNANDPS_SET_CYCLES_SET_T2_SHIFT
Set cycles set_t2 shift.
XNANDPS_SET_CYCLES_SET_T3_SHIFT
Set cycles set_t3 shift.
XNANDPS_SET_CYCLES_SET_T4_SHIFT
Set cycles set_t4 shift.
XNANDPS_SET_CYCLES_SET_T5_SHIFT
Set cycles set_t5 shift.
XNANDPS_SET_CYCLES_SET_T6_SHIFT
Set cycles set_t6 shift.
XNANDPS_SET_OPMODE_SET_MW_MASK
Set opmode set memory width mask.
XNANDPS_SET_OPMODE_SET_RD_SYNC_MASK
Set opmode set rd_sync mask.
XNANDPS_SET_OPMODE_SET_RD_BL_MASK
Set opmode set rd_bl mask.
XNANDPS_SET_OPMODE_SET_WR_SYNC_MASK
Set opmode set wr_sync mask.
XNANDPS_SET_OPMODE_SET_WR_BL_MASK
Set opmode set wr_bl mask.
XNANDPS_SET_OPMODE_SET_BAA_MASK
Set opmode set baa mask.
XNANDPS_SET_OPMODE_SET_ADV_MASK
Set opmode set adv mask.
XNANDPS_SET_OPMODE_SET_BLS_MASK
Set opmode set bls mask.
XNANDPS_SET_OPMODE_SET_BURST_ALIGN_MASK
Set opmode set burst align mask.
XNANDPS_SET_OPMODE_MW_8_BITS
Set opmode memory width value for 8-bit flash.
XNANDPS_SET_OPMODE_MW_16_BITS
Set opmode memory width value for 16-bit flash.
XNANDPS_SET_OPMODE_MW_32_BITS
Set opmode memory width value for 32-bit flash.
XNANDPS_REFRESH_PERIOD_0_MASK
Interface 0 refresh period mask.
XNANDPS_REFRESH_PERIOD_1_MASK
Interface 1 refresh period mask.
XNANDPS_OPMODE_MW_MASK
Opmode Memory width mask.
XNANDPS_OPMODE_RD_SYNC_MASK
Opmode rd_sync mask.
XNANDPS_OPMODE_RD_BL_MASK
Opmode rd_bl mask.
XNANDPS_OPMODE_WR_SYNC_MASK
Opmode wr_sync mask.
XNANDPS_OPMODE_WR_BL_MASK
Opmode BAA mask.
XNANDPS_OPMODE_BAA_MASK
Opmode ADV mask.
XNANDPS_OPMODE_ADV_MASK
Opmode BLS mask.
XNANDPS_OPMODE_BLS_MASK
Opmode Burst align mask.
XNANDPS_OPMODE_BURST_ALIGN_MASK
Opmode Address mask.
XNANDPS_OPMODE_ADDRESS_MASK
Opmode Address match mask.
XNANDPS_OPMODE_ADDRESS_MATCH_MASK
XNANDPS_USER_STATUS_MASK
User status mask.
XNANDPS_USER_CONFIG_MASK
User config mask.
XNANDPS_ECC_STATUS_RAW_INT_STATUS_MASK
Ecc status raw_int_status mask.
XNANDPS_ECC_STATUS_MASK
Ecc status ecc_status mask.
XNANDPS_ECC_LAST_MASK
Ecc status ecc_last mask.
XNANDPS_ECC_READ_NOT_WRITE_MASK
Ecc status ecc_read_not_write mask.
XNANDPS_ECC_VALID_MASK
Ecc status ecc_valid mask.
XNANDPS_ECC_FAIL_MASK
Ecc status ecc_fail mask.
XNANDPS_ECC_CAN_CORRECT_MASK
Ecc status ecc_can_correct mask.
XNANDPS_ECC_READ_MASK
Ecc status ecc_read mask.
XNANDPS_ECC_MEMCFG_PAGE_SIZE_MASK
Ecc cfg page_size mask.
XNANDPS_ECC_MEMCFG_ECC_MODE_MASK
Ecc cfg ecc_mode mask.
XNANDPS_ECC_MEMCFG_ECC_READ_END_MASK
Ecc cfg ecc_read_end mask.
XNANDPS_ECC_MEMCFG_ECC_JUMP_MASK
Ecc cfg ecc_jump mask.
XNANDPS_ECC_MEMCFG_IGNORE_ADD8_MASK
Ecc cfg ecc_ignore_add_eight mask.
XNANDPS_ECC_MEMCFG_ECC_INT_PASS_MASK
Ecc cfg ecc_int_pass mask.
XNANDPS_ECC_MEMCFG_ECC_INT_ABORT_MASK
Ecc cfg ecc_int_abort mask.
XNANDPS_ECC_MEMCFG_ECC_EXTRA_BLOCK_MASK
Ecc cfg ecc_extra_block mask.
XNANDPS_ECC_MEMCFG_ECC_EXTRA_BLOCK_SIZE_MASK
Ecc cfg ecc_extra_block_size mask.
XNANDPS_ECC_MEMCFG_PAGE_SIZE_SHIFT
Ecc cfg page_size shift.
XNANDPS_ECC_MEMCFG_ECC_MODE_SHIFT
Ecc cfg ecc_mode shift.
XNANDPS_ECC_MEMCFG_ECC_READ_END_SHIFT
Ecc cfg ecc_read_end shift.
XNANDPS_ECC_MEMCFG_ECC_JUMP_SHIFT
Ecc cfg ecc_jump shift.
XNANDPS_ECC_MEMCFG_IGNORE_ADD8_SHIFT
Ecc cfg ecc_ignore_add_eight shift.
XNANDPS_ECC_MEMCFG_ECC_INT_PASS_SHIFT
Ecc cfg ecc_int_pass shift.
XNANDPS_ECC_MEMCFG_ECC_INT_ABORT_SHIFT
Ecc cfg ecc_int_abort shift.
XNANDPS_ECC_MEMCFG_ECC_EXTRA_BLOCK_SHIFT
Ecc cfg ecc_extra_block shift.
XNANDPS_ECC_MEMCFG_ECC_EXTRA_BLOCK_SIZE_SHIFT
Ecc cfg ecc_extra_block_size shift.
XNANDPS_ECC_MEMCFG_PAGE_SIZE_512
ECC cfg page size value for 512 byte page.
XNANDPS_ECC_MEMCFG_PAGE_SIZE_1024
ECC cfg page size value for 1024 byte page.
XNANDPS_ECC_MEMCFG_PAGE_SIZE_2048
ECC cfg page size value for 2048 byte page.
XNandPs_EccMode
No ECC.
OnfiCommandsEnum
ONFI Read.
typedef struct XNandPsTag XNandPs
The XNandPs driver instance data.
The user is required to allocate a variable of this type for every flash device in the system. A pointer to a variable of this type is then passed to the driver API functions.
u32 NandOob16[][]
Ecc position for 16 bytes spare area.
u32 NandOob32[][]
Ecc position for 32 bytes spare area.
u32 NandOob64[][]
Ecc position for 64 bytes spare area.
XNandPs_CommandFormat OnfiCommands[][]
ONFI commands.
ONFI commands.
XNandPs_Config XNandPs_ConfigTable[XPAR_XNANDPS_NUM_INSTANCES][XPAR_XNANDPS_NUM_INSTANCES]
This table contains configuration information for each System Monitor/ADC device in the system.
XNandPs_CommandFormat OnfiCommands[][]
This structure defines the onfi command format sent to the flash.
ONFI commands.
XNandPs_Config XNandPs_ConfigTable[][]
This table contains configuration information for each System Monitor/ADC device in the system.
static int XNandPs_EccHwInit(XNandPs *InstancePtr)
This function initializes the HW ECC block based on flash.
InstancePtr is a pointer to the XNandPs instance. XST_SUCCESS if successful.XST_FAILURE if the flash is not supported. None
static int XNandPs_EccSwInit(XNandPs *InstancePtr)
This function initializes the software variables related to ECC generation, ECC checking and writing ECC bytes in spare bytes.
InstancePtr is a pointer to the XNandPs instance. XST_SUCCESS if successful.XST_FAILURE if the flash is not supported. None
static int XNandPs_ReadPage_HwEcc(XNandPs *InstancePtr, u8 *DstPtr)
This function reads a specific page from NAND device using HW ECC block.
It checks for the ECC errors and corrects single bit errors. The multiple bit error are reported as failure. InstancePtr is a pointer to the XNandPs instance. DstPtr is a pointer to the destination buffer. XST_SUCCESS if successful.XST_FAILURE if fail. None
static int XNandPs_ReadPage(XNandPs *InstancePtr, u8 *DstPtr)
This function reads a specific page from NAND device.
This doesn't use the HW ECC block for checking ECC errors. InstancePtr is a pointer to the XNandPs instance. DstPtr is a pointer to the destination buffer. XST_SUCCESS if successful.XST_FAILURE if fail. None
static int XNandPs_WritePage_HwEcc(XNandPs *InstancePtr, u8 *SrcPtr)
This function writes a specific page in the NAND device using HW ECC block.
The ECC code is written into the spare bytes of the page. InstancePtr is a pointer to the XNandPs instance. SrcPtr is a pointer to the source buffer. XST_SUCCESS if successful.XST_FAILURE if fail. None
static int XNandPs_WritePage(XNandPs *InstancePtr, u8 *SrcPtr)
This function writes a specific page in the NAND device.
This doesn't use the HW ECC block for ECC code generation. InstancePtr is a pointer to the XNandPs instance. SrcPtr is a pointer to the source buffer. XST_SUCCESS if successful.XST_FAILURE if fail. None
static int XNandPs_EccCalculate(XNandPs *InstancePtr, u8 *EccData)
This function calculates the ECC value from the ECC registers.
InstancePtr is a pointer to the XNandPs instance. EccData is the buffer to fill the ECC value. XST_SUCCESS if successful.XST_FAILURE if fail. None
static int XNandPs_EccCorrect(u8 *Buf, u8 *EccCalc, u8 *EccCode)
This function corrects the ECC errors.
Buf is the buffer which holds the data read from the page. EccCalc is the calculated ECC value. EccCode is the ECC read from the spare area. XST_SUCCESS if the ECC error is corrected.XST_FAILURE if the ECC error is not corrected. None
static void XNandPs_ReadBuf(XNandPs *InstancePtr, u8 *Buf, u32 Length)
This function reads the page data from the AXI Data Phase Address.
InstancePtr is a pointer to the XNandPs instance. Buf is the buffer pointer to store the byte. Length is the number of bytes to read. None.
static void XNandPs_WriteBuf(XNandPs *InstancePtr, u8 *Buf, u32 Length)
This function writes the data to the AXI Data Phase Address.
InstancePtr is a pointer to the XNandPs instance. Buf is the buffer pointer to write the data from. Length is the number of bytes to write. None.
static int XNandPs_IsBusy(XNandPs *InstancePtr)
This function checks whether SMC controller busy in processing a request.
InstancePtr is a pointer to the XNandPs instance. - TRUE if SMC is busy FALSE if SMC is free None.
void XNandPs_SendCommand(XNandPs *InstancePtr, XNandPs_CommandFormat *Command, int Page, int Column)
This function sends a NAND command to the flash device.
InstancePtr is the pointer to XNandPs structure Command is the NAND command to send Page is the page offset required for specific commands Column the column offset required for specific commands None None
References XNandPs_CommandFormat::AddrCycles, XNandPs_Geometry::ColAddrCycles, XNandPsTag::CommandPhaseAddr, XNandPsTag::Config, XNandPsTag::DataPhaseAddr, XNandPs_CommandFormat::EndCmd, XNandPs_CommandFormat::EndCmdValid, XNandPs_Config::FlashBase, XNandPs_Geometry::FlashWidth, XNandPsTag::Geometry, ONFI_CMD_BLOCK_ERASE1, ONFI_CMD_PAGE_PROG1, ONFI_CMD_READ1, XNandPs_Geometry::RowAddrCycles, XNandPs_CommandFormat::StartCmd, XNANDPS_ADDR_CYCLES_SHIFT, XNANDPS_CLEAR_CS_SHIFT, XNANDPS_CMD_PHASE, XNANDPS_COLUMN_NOT_VALID, XNANDPS_COMMAND_PHASE_MASK, XNANDPS_DATA_PHASE, XNANDPS_DATA_PHASE_MASK, XNANDPS_ECC_LAST_SHIFT, XNANDPS_END_CMD_SHIFT, XNANDPS_END_CMD_VALID_SHIFT, XNANDPS_FLASH_WIDTH_16, XNANDPS_PAGE_NOT_VALID, XNANDPS_START_CMD_SHIFT, XNandPs_WriteReg.
Referenced by Onfi_CmdReadStatus, XNandPs_EraseBlock, XNandPs_Read, XNandPs_ReadCache, XNandPs_ReadSpareBytes, XNandPs_Write, XNandPs_WriteCache, XNandPs_WriteSpareBytes.
static void XNandPs_EccSetCfg(XNandPs *InstancePtr, u32 EccConfig)
This function initializes the HW ECC block based on flash.
InstancePtr is a pointer to the XNandPs instance. EccConfig is the value of ECC config to update. None None
static void XNandPs_EccSetMemCmd1(XNandPs *InstancePtr, u32 EccCmd)
This function writes ECC MEM CMD1 register with EccCmd value.
InstancePtr is a pointer to the XNandPs instance. EccCmd is register value to write. None None
static void XNandPs_EccSetMemCmd2(XNandPs *InstancePtr, u32 EccCmd)
This function writes ECC MEM CMD2 register with EccCmd value.
InstancePtr is a pointer to the XNandPs instance. EccCmd is register value to write. None None
static void XNandPs_EccDisable(XNandPs *InstancePtr)
This function disables ECC block.
InstancePtr is a pointer to the XNandPs instance. None None
void XNandPs_InitBbtDesc(XNandPs *InstancePtr)
This function initializes the Bad Block Table(BBT) descriptors with a predefined pattern for searching Bad Block Table(BBT) in flash.
InstancePtr is a pointer to the XNandPs instance. NONE
References XNandPsTag::BbPattern, XNandPsTag::BbtDesc, XNandPsTag::BbtMirrorDesc, XNandPs_Geometry::BytesPerPage, XNandPsTag::EccMode, XNandPsTag::Geometry, XNandPsTag::IsReady, XNandPs_BadBlockPattern::Length, XNandPs_BbtDesc::MaxBlocks, XNandPs_BadBlockPattern::Offset, XNandPs_BadBlockPattern::Options, XNandPs_BbtDesc::PageOffset, XNandPs_BadBlockPattern::Pattern, XNandPs_BbtDesc::SigLength, XNandPs_BbtDesc::Signature, XNandPs_BbtDesc::SigOffset, XNandPs_BbtDesc::Valid, XNandPs_BbtDesc::VerOffset, XNandPs_BbtDesc::Version, XNANDPS_BB_PATTERN, XNANDPS_BB_PATTERN_LENGTH_LARGE_PAGE, XNANDPS_BB_PATTERN_LENGTH_SMALL_PAGE, XNANDPS_BB_PATTERN_OFFSET_LARGE_PAGE, XNANDPS_BB_PATTERN_OFFSET_SMALL_PAGE, XNANDPS_BBT_DESC_MAX_BLOCKS, XNANDPS_BBT_DESC_PAGE_OFFSET, XNANDPS_BBT_DESC_SIG_LEN, XNANDPS_BBT_DESC_SIG_OFFSET, XNANDPS_BBT_DESC_VER_OFFSET, XNANDPS_BBT_SCAN_2ND_PAGE, XNANDPS_ECC_ONDIE.
Referenced by XNandPs_CfgInitialize.
int XNandPs_ScanBbt(XNandPs *InstancePtr)
This function reads the Bad Block Table(BBT) if present in flash.
If not it scans the flash for detecting factory marked bad blocks and creates a bad block table and write the Bad Block Table(BBT) into the flash. InstancePtr is a pointer to the XNandPs instance. XST_SUCCESS if successful.XST_FAILURE if fail.
References XNandPsTag::BbtDesc, XNandPsTag::BbtMirrorDesc, XNandPsTag::IsReady.
Referenced by XNandPs_CfgInitialize.
u8 Onfi_CmdReadStatus(XNandPs *InstancePtr)
This function sends read status command to the flash device.
InstancePtr is a pointer to the XNandPs instance. flash status value read None
References XNandPsTag::Config, XNandPsTag::DataPhaseAddr, XNandPs_Config::FlashWidth, READ_STATUS, XNANDPS_COLUMN_NOT_VALID, XNANDPS_FLASH_WIDTH_16, XNANDPS_PAGE_NOT_VALID, XNandPs_SendCommand.
Referenced by XNandPs_EraseBlock, XNandPs_ReadCache, XNandPs_ReadSpareBytes, XNandPs_Write, XNandPs_WriteCache, XNandPs_WriteSpareBytes.
int Onfi_NandInit(XNandPs *InstancePtr)
This function initializes the NAND flash and gets the geometry information.
InstancePtr is a pointer to the XNandPs instance. XST_SUCCESS if successful.XST_FAILURE if failed. None
References OnfiNand_Geometry::AddrCycles, XNandPs_CommandFormat::AddrCycles, BLOCK_ERASE, XNandPs_Geometry::BlockSize, OnfiNand_Geometry::BlocksPerLun, XNandPs_Geometry::BlocksPerLun, OnfiNand_Geometry::BytesPerPage, XNandPs_Geometry::BytesPerPage, CHANGE_READ_COLUMN, CHANGE_WRITE_COLUMN, XNandPs_Geometry::ColAddrCycles, XNandPs_Geometry::DeviceSize, XNandPsTag::EccMode, OnfiNand_Geometry::Features, XNandPsTag::Features, XNandPs_Geometry::FlashWidth, XNandPsTag::Geometry, XNandPs_Geometry::NumBlocks, XNandPs_Geometry::NumLun, OnfiNand_Geometry::NumLuns, XNandPs_Geometry::NumPages, ONFI_ID_LEN, OnfiNand_Geometry::OptionalCmds, PAGE_PROGRAM, OnfiNand_Geometry::PagesPerBlock, XNandPs_Geometry::PagesPerBlock, READ, XNandPs_Geometry::RowAddrCycles, OnfiNand_Geometry::SpareBytesPerPage, XNandPs_Geometry::SpareBytesPerPage, XNANDPS_ECC_HW, XNANDPS_ECC_NONE, XNANDPS_ECC_ONDIE, XNANDPS_FLASH_WIDTH_16, XNANDPS_FLASH_WIDTH_8, XNANDPS_MAX_BLOCKS, XNANDPS_MAX_LUNS, XNANDPS_MAX_PAGE_SIZE, XNANDPS_MAX_PAGES_PER_BLOCK, XNANDPS_MAX_SPARE_SIZE, XNANDPS_MAX_TARGETS.
Referenced by XNandPs_CfgInitialize.
int XNandPs_CfgInitialize(XNandPs *InstancePtr, XNandPs_Config *ConfigPtr, u32 SmcBaseAddr, u32 FlashBaseAddr)
This function initializes a specific XNandPs device/instance.
This function must be called prior to using the flash device to read or write any data. InstancePtr is a pointer to the XNandPs instance. ConfigPtr points to the XNandPs device configuration structure. SmcBaseAddr is the base address of SMC controller. FlashBaseAddr is the base address of NAND flash. XST_SUCCESS if successful.XST_FAILURE if fail. The user needs to first call the XNandPs_LookupConfig() API which returns the Configuration structure pointer which is passed as a parameter to the XNandPs_CfgInitialize() API.
References XNandPs_Geometry::BytesPerPage, XNandPsTag::Config, XNandPsTag::DataBuf, XNandPsTag::EccMode, XNandPs_Config::FlashBase, XNandPs_Config::FlashWidth, XNandPs_Geometry::FlashWidth, XNandPsTag::Geometry, XNandPsTag::IsReady, Onfi_NandInit, XNandPsTag::ReadPage, XNandPs_Config::SmcBase, XNandPsTag::SpareBufPtr, XNandPsTag::WritePage, XNANDPS_CLR_CONFIG, XNANDPS_ECC_HW, XNANDPS_ECC_NONE, XNANDPS_ECC_ONDIE, XNandPs_InitBbtDesc, XNANDPS_MEMC_CLR_CONFIG_OFFSET, XNandPs_ScanBbt, XNandPs_WriteReg.
Referenced by NandReadWriteCacheExample, NandReadWriteExample, NandSkipBlockExample.
int XNandPs_Read(XNandPs *InstancePtr, u64 Offset, u32 Length, void *DestPtr, u8 *UserSparePtr)
This function reads the data from the Flash device and copies it into the specified user buffer.
It doesn't check for the bad blocks while reading the flash pages that cross block boundary. User must take care of handling bad blocks. InstancePtr is the pointer to the XNandPs instance. Offset is the flash data address to read from. Length is number of bytes to read. DestPtr is the destination address to copy data to. UserSparePtr is the user buffer to which spare data must be copied. XST_SUCCESS if successful.XST_FAILURE if fail. This function reads sequential pages from the Flash device.
References XNandPs_Geometry::BytesPerPage, XNandPsTag::Config, XNandPsTag::DataBuf, XNandPs_Geometry::DeviceSize, XNandPsTag::Geometry, XNandPsTag::IsReady, READ, XNandPsTag::ReadPage, XNandPs_Config::SmcBase, XNandPsTag::SpareBufPtr, XNandPs_Geometry::SpareBytesPerPage, XNANDPS_ECC_CMD1, XNANDPS_ECC_CMD2, XNANDPS_MEMC_CLR_CONFIG_INT_CLR1_MASK, XNANDPS_MEMC_CLR_CONFIG_OFFSET, XNandPs_SendCommand, XNandPs_WriteReg.
Referenced by NandReadWriteExample, XNandPs_ReadCache, XNandPs_SkipRead.
int XNandPs_ReadCache(XNandPs *InstancePtr, u64 Offset, u32 Length, void *DestPtr, u8 *UserSparePtr)
This function reads the data from the Flash device using read page cache command and copies it into the specified user buffer.
It doesn't check for the bad blocks while reading the flash pages that cross block boundary. User must take care of handling bad blocks. InstancePtr is the pointer to the XNandPs instance. Offset is the flash data address to read from. Length is number of bytes to read. DestPtr is the destination address to copy data to. UserSparePtr is the user buffer to which spare data must be copied. XST_SUCCESS if successful.XST_FAILURE if fail. This function reads sequential pages from the Flash device.
References XNandPs_Geometry::BytesPerPage, CHANGE_READ_COLUMN, XNandPsTag::Config, XNandPsTag::DataBuf, XNandPs_Geometry::DeviceSize, XNandPsTag::Features, XNandPsTag::Geometry, XNandPsTag::IsReady, ONFI_CMD_CHANGE_READ_COLUMN1, ONFI_CMD_CHANGE_READ_COLUMN2, ONFI_CMD_PAGE_CACHE_PROGRAM1, ONFI_CMD_READ_CACHE_ENHANCED1, ONFI_CMD_READ_CACHE_ENHANCED2, Onfi_CmdReadStatus, ONFI_STATUS_FAIL, READ, READ_CACHE_END_SEQ, READ_CACHE_RANDOM, XNandPsTag::ReadPage, XNandPs_Config::SmcBase, XNandPsTag::SpareBufPtr, XNandPs_Geometry::SpareBytesPerPage, XNANDPS_COLUMN_NOT_VALID, XNANDPS_ECC_MEMCOMMAND1_RD_CMD_END_VALID_MASK, XNANDPS_MEMC_CLR_CONFIG_INT_CLR1_MASK, XNANDPS_MEMC_CLR_CONFIG_OFFSET, XNANDPS_PAGE_NOT_VALID, XNandPs_Read, XNandPs_SendCommand, XNandPs_WriteReg.
Referenced by NandReadWriteCacheExample.
int XNandPs_Write(XNandPs *InstancePtr, u64 Offset, u32 Length, void *SrcPtr, u8 *UserSparePtr)
This function programs the flash device(s) with data specified in the user buffer.
The source and destination address must be aligned to the width of the flash's data bus. It doesn't check for the bad blocks while writing to the flash pages that cross block boundary. User must take care of handling bad blocks. InstancePtr is the pointer to the XNandPs instance. Offset is the flash data address to write to. Length is number of bytes to write. SrcPtr is the source address to write the data from. UserSparePtr is the user buffer which contains buffer to write into spare data area. XST_SUCCESS if successful.XST_FAILURE if fail.XST_NAND_WRITE_PROTECTED if the flash is write protected. This function writes number of sequential pages into the Flash device.
References XNandPs_Geometry::BytesPerPage, XNandPsTag::DataBuf, XNandPs_Geometry::DeviceSize, XNandPsTag::Geometry, XNandPsTag::IsReady, Onfi_CmdReadStatus, ONFI_STATUS_WP, PAGE_PROGRAM, XNandPsTag::SpareBufPtr, XNandPs_Geometry::SpareBytesPerPage, XNandPsTag::WritePage, XNandPs_SendCommand.
Referenced by NandReadWriteExample, XNandPs_SkipWrite, XNandPs_WriteCache.
int XNandPs_WriteCache(XNandPs *InstancePtr, u64 Offset, u32 Length, void *SrcPtr, u8 *UserSparePtr)
This function programs the flash device(s) with data specified in the user buffer using program cache command.
The source and destination address must be aligned to the width of the flash's data bus. It doesn't check for the bad blocks while writing to the flash pages that cross block boundary. User must take care of handling bad blocks. InstancePtr is the pointer to the XNandPs instance. Offset is the flash data address to write to. Length is number of bytes to write. SrcPtr is the source address to write the data from. UserSparePtr is the user buffer which contains buffer to write into spare data area. XST_SUCCESS if successful.XST_FAILURE if fail.XST_NAND_WRITE_PROTECTED if the flash is write protected. This function writes number of sequential pages into the Flash device.
References XNandPs_Geometry::BytesPerPage, XNandPsTag::DataBuf, XNandPs_Geometry::DeviceSize, XNandPsTag::Geometry, XNandPsTag::IsReady, Onfi_CmdReadStatus, ONFI_STATUS_WP, PAGE_CACHE_PROGRAM, PAGE_PROGRAM, XNandPsTag::SpareBufPtr, XNandPs_Geometry::SpareBytesPerPage, XNandPsTag::WritePage, XNandPs_SendCommand, XNandPs_Write.
Referenced by NandReadWriteCacheExample.
int XNandPs_ReadSpareBytes(XNandPs *InstancePtr, u32 Page, u8 *Buf)
This function reads the spare area of a page.
InstancePtr is the pointer to the XNandPs instance. Page is the page number from where spare data is read. Buf is pointer to the buffer where the spare data is filled. XST_SUCCESS if successful.XST_FAILURE if fail. None.
References XNandPs_Geometry::BytesPerPage, XNandPsTag::Config, XNandPsTag::DataPhaseAddr, XNandPsTag::EccMode, XNandPs_Config::FlashBase, XNandPsTag::Geometry, Onfi_CmdReadStatus, ONFI_STATUS_FAIL, READ, XNandPs_Config::SmcBase, XNandPs_Geometry::SpareBytesPerPage, XNANDPS_ADDR_CYCLES_SHIFT, XNANDPS_AXI_DATA_WIDTH, XNANDPS_CLR_CS, XNANDPS_COMMAND_PHASE_MASK, XNANDPS_ECC_HW, XNANDPS_END_CMD_SHIFT, XNANDPS_END_CMD_VALID_SHIFT, XNANDPS_MEMC_CLR_CONFIG_INT_CLR1_MASK, XNANDPS_MEMC_CLR_CONFIG_OFFSET, XNandPs_SendCommand, XNANDPS_START_CMD_SHIFT, XNandPs_WriteReg.
int XNandPs_WriteSpareBytes(XNandPs *InstancePtr, u32 Page, u8 *Buf)
This function write to the spare area of a page.
InstancePtr is the pointer to the XNandPs instance. Page is the page number to write. Buf is pointer to the buffer which holds the data. XST_SUCCESS if successful.XST_FAILURE if fail. None.
References XNandPs_Geometry::BytesPerPage, XNandPsTag::Config, XNandPsTag::DataPhaseAddr, XNandPsTag::EccMode, XNandPsTag::Geometry, Onfi_CmdReadStatus, ONFI_STATUS_FAIL, PAGE_PROGRAM, XNandPs_Config::SmcBase, XNandPs_Geometry::SpareBytesPerPage, XNANDPS_AXI_DATA_WIDTH, XNANDPS_CLR_CS, XNANDPS_ECC_HW, XNANDPS_MEMC_CLR_CONFIG_INT_CLR1_MASK, XNANDPS_MEMC_CLR_CONFIG_OFFSET, XNandPs_SendCommand, XNandPs_WriteReg.
int XNandPs_EraseBlock(XNandPs *InstancePtr, u32 BlockNum)
This function erases a specific block in the NAND device.
InstancePtr is a pointer to the XNandPs instance. BlockNum is the block number of the device. XST_SUCCESS if successful.XST_FAILURE if fail.XST_NAND_WRITE_PROTECTED if the flash is write protected. None
References BLOCK_ERASE, XNandPsTag::Config, XNandPsTag::Geometry, XNandPsTag::IsReady, Onfi_CmdReadStatus, ONFI_STATUS_WP, XNandPs_Geometry::PagesPerBlock, XNandPs_Config::SmcBase, XNANDPS_COLUMN_NOT_VALID, XNANDPS_MEMC_CLR_CONFIG_INT_CLR1_MASK, XNANDPS_MEMC_CLR_CONFIG_OFFSET, XNandPs_SendCommand, XNandPs_WriteReg.
Referenced by NandReadWriteCacheExample, NandReadWriteExample, XNandPs_SkipErase.
XNandPs_Config * XNandPs_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XNandPs_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xnandps.h for the definition of XNandPs_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XNandPs_Config::Name.
Referenced by NandReadWriteCacheExample, NandReadWriteExample, NandSkipBlockExample.
static int XNandPs_ReadBbt(XNandPs *InstancePtr)
< For memcpy and memset
This function searches the Bad Block Table(BBT) in flash and loads into the memory based Bad Block Table(BBT). InstancePtr is the pointer to the XNandPs instance. XST_SUCCESS if successful.XST_FAILURE if fail.
static int XNandPs_SearchBbt(XNandPs *InstancePtr, XNandPs_BbtDesc *Desc)
This function searches the BBT in flash.
InstancePtr is the pointer to the XNandPs instance. Desc is the BBT descriptor pattern to search. XST_SUCCESS if successful.XST_FAILURE if fail.
static void XNandPs_CreateBbt(XNandPs *InstancePtr)
This function scans the NAND flash for factory marked bad blocks and creates a RAM based Bad Block Table(BBT).
InstancePtr is a pointer to the XNandPs instance. NONE
static void XNandPs_ConvertBbt(XNandPs *InstancePtr, u8 *Buf)
This function converts the Bad Block Table(BBT) read from the flash to the RAM based Bad Block Table(BBT).
InstancePtr is a pointer to the XNandPs instance. Buf is the buffer which contains BBT read from flash. NONE.
static int XNandPs_WriteBbt(XNandPs *InstancePtr, XNandPs_BbtDesc *Desc, XNandPs_BbtDesc *MirrorDesc)
This function writes Bad Block Table(BBT) from RAM to flash.
InstancePtr is the pointer to the XNandPs instance. Desc is the BBT descriptor to be written to flash. MirrorDesc is the mirror BBT descriptor. XST_SUCCESS if successful.XST_FAILURE if fail.
static int XNandPs_MarkBbt(XNandPs *InstancePtr, XNandPs_BbtDesc *Desc)
This function marks the block containing Bad Block Table as reserved and updates the BBT.
InstancePtr is the pointer to the XNandPs instance. Desc is the BBT descriptor pointer. XST_SUCCESS if successful.XST_FAILURE if fail.
static int XNandPs_UpdateBbt(XNandPs *InstancePtr)
This function updates the primary and mirror Bad Block Table(BBT) in the flash.
InstancePtr is the pointer to the XNandPs instance. XST_SUCCESS if successful.XST_FAILURE if fail.
int XNandPs_IsBlockBad(XNandPs *InstancePtr, u32 Block)
This function checks whether a block is bad or not.
InstancePtr is the pointer to the XNandPs instance. Block is the block number. XST_SUCCESS if successful.XST_FAILURE if fail.
References XNandPsTag::Bbt, XNandPsTag::IsReady, XNANDPS_BBT_BLOCK_SHIFT, XNandPs_BbtBlockShift, XNANDPS_BLOCK_GOOD, XNANDPS_BLOCK_TYPE_MASK.
Referenced by NandReadWriteCacheExample, NandReadWriteExample, XNandPs_CalculateLength, XNandPs_SkipErase, XNandPs_SkipRead, XNandPs_SkipWrite.
int XNandPs_MarkBlockBad(XNandPs *InstancePtr, u32 Block)
This function marks a block as bad in the RAM based Bad Block Table(BBT).
It also updates the Bad Block Table(BBT) in the flash. InstancePtr is the pointer to the XNandPs instance. Block is the block number. XST_SUCCESS if successful.XST_FAILURE if fail.
References XNandPsTag::Bbt, XNandPsTag::IsReady, XNANDPS_BBT_BLOCK_SHIFT, XNandPs_BbtBlockShift, XNANDPS_BLOCK_BAD, XNANDPS_BLOCK_TYPE_MASK.
static void Onfi_ReadData(XNandPs *InstancePtr, u8 *Buf, u32 Length)
This function reads the data from flash.
It is used for reading the control information from flash like ID and Parameter page. InstancePtr is a pointer to the XNandPs instance. Buf is the buffer pointer to read the data. Length is the length of data to read. None None
static void Onfi_CmdReset(XNandPs *InstancePtr)
This function sends reset command to the flash device.
InstancePtr is a pointer to the XNandPs instance. None None
static void Onfi_CmdReadId(XNandPs *InstancePtr, u8 Address)
This function sends read ID command to the flash device.
InstancePtr is a pointer to the XNandPs instance. None None
static void Onfi_CmdReadParamPage(XNandPs *InstancePtr)
This function sends read parameter page command to the flash device.
InstancePtr is a pointer to the XNandPs instance. None None
static unsigned long Onfi_Crc16(u8 *Buf)
This function calculates the CRC on the parameter page buffer.
This is taken from the ONFI 1.0 specification. Buf is the parameter page buffer. CRC value calculated. None
static int Onfi_ReadParamPage(XNandPs *InstancePtr, u8 *Buf)
This function reads the NAND flash parameter page defined by ONFI 1.0 specification.
InstancePtr is a pointer to the XNandPs instance. Buf is a buffer pointer to fill the data. XST_SUCCESS if parameter page read successfully.XST_FAILURE if parameter page is not read successfully. None
static void Onfi_WriteData(XNandPs *InstancePtr, u8 *Buf, u32 Length)
This function writes command data to flash.
It is used for writing the control information like set features. InstancePtr is a pointer to the XNandPs instance. Buf is the buffer pointer to write the data. Length is the length of data to write. None None
static void Onfi_GetFeature(XNandPs *InstancePtr, u8 Feature, u8 *Val)
This function sends Get Feature command to the flash device.
InstancePtr is a pointer to the XNandPs instance. Feature is the feature value to read. None None
static void Onfi_SetFeature(XNandPs *InstancePtr, u8 Feature, u8 *Val)
This function sends Set Feature command to the flash device.
InstancePtr is a pointer to the XNandPs instance. Feature is the feature value to Set. None None
XNANDPS_H
XNANDPS_MAX_TARGETS
Max number of targets supported.
Referenced by Onfi_NandInit.
XNANDPS_MAX_BLOCKS
Max number of Blocks.
Referenced by Onfi_NandInit.
XNANDPS_MAX_PAGE_SIZE
Max page size of NAND flash.
Referenced by Onfi_NandInit.
XNANDPS_MAX_SPARE_SIZE
Max spare bytes of a NAND flash page.
Referenced by Onfi_NandInit.
XNANDPS_MAX_LUNS
Max number of LUNs.
Referenced by Onfi_NandInit.
XNANDPS_MAX_PAGES_PER_BLOCK
Max number pages per block.
Referenced by Onfi_NandInit.
XNANDPS_ECC_BLOCK_SIZE
ECC block size.
XNANDPS_ECC_BYTES
ECC bytes per ECC block.
XNANDPS_PAGE_SIZE_512
Page size 512.
XNANDPS_PAGE_SIZE_1024
Page size 1024.
XNANDPS_PAGE_SIZE_2048
Page size 2048.
XNANDPS_PAGE_SIZE_4096
Page size 4096.
XNANDPS_PAGE_SIZE_8192
Page size 8192.
XNANDPS_SPARE_SIZE_8
Spare bytes size 8.
XNANDPS_SPARE_SIZE_16
Spare bytes size 16.
XNANDPS_SPARE_SIZE_32
Spare bytes size 32.
XNANDPS_SPARE_SIZE_64
Spare bytes size 64.
XNANDPS_SPARE_SIZE_128
Spare bytes size 128.
XNANDPS_SPARE_SIZE_256
Spare bytes size 256.
XNANDPS_FLASH_WIDTH_8
NAND Flash width 8-bit.
Referenced by Onfi_NandInit.
XNANDPS_FLASH_WIDTH_16
NAND Flash width 16-bit.
Referenced by Onfi_CmdReadStatus, Onfi_NandInit, XNandPs_SendCommand.
XNANDPS_END_CMD_NONE
No End command.
XNANDPS_END_CMD_INVALID
End command invalid.
XNANDPS_CMD_PHASE
End command in command phase.
Referenced by XNandPs_SendCommand.
XNANDPS_DATA_PHASE
End command in data phase.
Referenced by XNandPs_SendCommand.
XNANDPS_PAGE_NOT_VALID
Page is not valid in command phase.
Referenced by Onfi_CmdReadStatus, XNandPs_ReadCache, XNandPs_SendCommand.
XNANDPS_COLUMN_NOT_VALID
Column is not valid in command phase.
Referenced by Onfi_CmdReadStatus, XNandPs_EraseBlock, XNandPs_ReadCache, XNandPs_SendCommand.
XNANDPS_AXI_DATA_WIDTH
AXI Data width for last transaction while reading and writing.
Referenced by XNandPs_ReadSpareBytes, XNandPs_WriteSpareBytes.
XNANDPS_START_CMD_SHIFT
Start command shift.
Referenced by XNandPs_ReadSpareBytes, XNandPs_SendCommand.
XNANDPS_END_CMD_SHIFT
End command shift.
Referenced by XNandPs_ReadSpareBytes, XNandPs_SendCommand.
XNANDPS_END_CMD_VALID_SHIFT
End command valid shift.
Referenced by XNandPs_ReadSpareBytes, XNandPs_SendCommand.
XNANDPS_ADDR_CYCLES_SHIFT
Address cycles shift.
Referenced by XNandPs_ReadSpareBytes, XNandPs_SendCommand.
XNANDPS_CHIP_ADDR_SHIFT
Chip address shift.
XNANDPS_ECC_LAST_SHIFT
Ecc last shift.
Referenced by XNandPs_SendCommand.
XNANDPS_CLEAR_CS_SHIFT
clear chip select shift
Referenced by XNandPs_SendCommand.
XNANDPS_COMMAND_PHASE_MASK
Command phase mask.
Referenced by XNandPs_ReadSpareBytes, XNandPs_SendCommand.
XNANDPS_DATA_PHASE_MASK
Data phase mask.
Referenced by XNandPs_SendCommand.
XNANDPS_ECC_CORRECT_BYTE_MASK
ECC error correction byte position mask, bits[11:3] of error code.
XNANDPS_ECC_CORRECT_BIT_MASK
ECC error correction bit position mask, bits[0:2] of error code.
XNANDPS_CLR_CONFIG
Interrupt settings.
Referenced by XNandPs_CfgInitialize.
XNANDPS_ECC_MEMCFG
ECC memory configuration settings.
XNANDPS_ECC_CMD1
ECC command 1 settings.
Referenced by XNandPs_Read.
XNANDPS_ECC_CMD2
ECC command 2 settings.
Referenced by XNandPs_Read.
XNANDPS_CLR_CS
set Clear chip select
Referenced by XNandPs_ReadSpareBytes, XNandPs_WriteSpareBytes.
XNANDPS_ECC_LAST
set Ecc last
OneHot
OneHot is used to check if one and only one bit is set.
This Macro returns 1 if the value passed is OneHot.
BBM_H
XNANDPS_BLOCK_GOOD
Block is good.
Referenced by XNandPs_IsBlockBad.
XNANDPS_BLOCK_BAD
Block is bad.
Referenced by XNandPs_MarkBlockBad.
XNANDPS_BLOCK_RESERVED
Reserved block.
XNANDPS_BLOCK_FACTORY_BAD
Factory marked bad block.
XNANDPS_FLASH_BLOCK_GOOD
Block is good.
XNANDPS_FLASH_BLOCK_BAD
Block is bad.
XNANDPS_FLASH_BLOCK_RESERVED
Reserved block.
XNANDPS_FLASH_BLOCK_FACTORY_BAD
Factory marked bad block.
XNANDPS_BBT_SCAN_2ND_PAGE
Scan the second page for bad block information.
Referenced by XNandPs_InitBbtDesc.
XNANDPS_BBT_DESC_PAGE_OFFSET
Page offset of Bad Block Table Desc.
Referenced by XNandPs_InitBbtDesc.
XNANDPS_BBT_DESC_SIG_OFFSET
Bad Block Table signature offset.
Referenced by XNandPs_InitBbtDesc.
XNANDPS_BBT_DESC_VER_OFFSET
Bad block Table version offset.
Referenced by XNandPs_InitBbtDesc.
XNANDPS_BBT_DESC_SIG_LEN
Bad block Table signature length.
Referenced by XNandPs_InitBbtDesc.
XNANDPS_BBT_DESC_MAX_BLOCKS
Bad block Table max blocks.
Referenced by XNandPs_InitBbtDesc.
XNANDPS_BBT_BLOCK_SHIFT
Block shift value for a block in BBT.
Referenced by XNandPs_IsBlockBad, XNandPs_MarkBlockBad.
XNANDPS_BBT_ENTRY_NUM_BLOCKS
Num of blocks in one BBT entry.
XNANDPS_BB_PATTERN_OFFSET_SMALL_PAGE
Bad block pattern offset in a page.
Referenced by XNandPs_InitBbtDesc.
XNANDPS_BB_PATTERN_LENGTH_SMALL_PAGE
Bad block pattern length.
Referenced by XNandPs_InitBbtDesc.
XNANDPS_BB_PATTERN_OFFSET_LARGE_PAGE
Bad block pattern offset in a large page.
Referenced by XNandPs_InitBbtDesc.
XNANDPS_BB_PATTERN_LENGTH_LARGE_PAGE
Bad block pattern length.
Referenced by XNandPs_InitBbtDesc.
XNANDPS_BB_PATTERN
Bad block pattern to search in a page.
Referenced by XNandPs_InitBbtDesc.
XNANDPS_BLOCK_TYPE_MASK
Block type mask.
Referenced by XNandPs_IsBlockBad, XNandPs_MarkBlockBad.
XNANDPS_BLOCK_SHIFT_MASK
Block shift mask for a Bad Block Table entry byte.
XNandPs_BbtBlockShift
This macro returns the Block shift value corresponding to a Block.
Block is the block number. Block shift value None.
Referenced by XNandPs_IsBlockBad, XNandPs_MarkBlockBad.
XNANDPS_HW_H
XNANDPS_MEMC_STATUS_OFFSET
Controller status reg, RO.
XNANDPS_MEMC_IF_CONFIG_OFFSET
Interface config reg, RO.
XNANDPS_MEMC_SET_CONFIG_OFFSET
Set configuration reg, WO.
XNANDPS_MEMC_CLR_CONFIG_OFFSET
Clear config reg, WO.
Referenced by XNandPs_CfgInitialize, XNandPs_EraseBlock, XNandPs_Read, XNandPs_ReadCache, XNandPs_ReadSpareBytes, XNandPs_WriteSpareBytes.
XNANDPS_DIRECT_CMD_OFFSET
Direct command reg, WO.
XNANDPS_SET_CYCLES_OFFSET
Set cycles register, WO.
XNANDPS_SET_OPMODE_OFFSET
Set opmode register, WO.
XNANDPS_REFRESH_PERIOD_0_OFFSET
Refresh period_0 reg, RW.
XNANDPS_REFRESH_PERIOD_1_OFFSET
Refresh period_1 reg, RW.
XNANDPS_IF0_CHIP_0_CONFIG_OFFSET
Interface 0 chip 0 config.
XNANDPS_IF0_CHIP_1_CONFIG_OFFSET
Interface 0 chip 1 config.
XNANDPS_IF0_CHIP_2_CONFIG_OFFSET
Interface 0 chip 2 config.
XNANDPS_IF0_CHIP_3_CONFIG_OFFSET
Interface 0 chip 3 config.
XNANDPS_IF1_CHIP_0_CONFIG_OFFSET
Interface 1 chip 0 config.
XNANDPS_IF1_CHIP_1_CONFIG_OFFSET
Interface 1 chip 1 config.
XNANDPS_IF1_CHIP_2_CONFIG_OFFSET
Interface 1 chip 2 config.
XNANDPS_IF1_CHIP_3_CONFIG_OFFSET
Interface 1 chip 3 config.
XNANDPS_FLASH_CYCLES
NAND & SRAM cycle,RO.
XNANDPS_OPMODE
Chip opmode reg, RO.
XNANDPS_USER_STATUS_OFFSET
User status reg, RO.
XNANDPS_USER_CONFIG_OFFSET
User config reg, WO.
XNANDPS_IF0_ECC_OFFSET
Interface 0 ECC register.
XNANDPS_IF1_ECC_OFFSET
Interface 1 ECC register.
XNANDPS_ECC_STATUS_OFFSET
ECC status register.
XNANDPS_ECC_MEMCFG_OFFSET
ECC mem config reg.
XNANDPS_ECC_MEMCMD1_OFFSET
ECC mem com1 reg.
XNANDPS_ECC_MEMCMD2_OFFSET
ECC mem com2 reg.
XNANDPS_ECC_ADDR0_OFFSET
ECC address0 reg.
XNANDPS_ECC_ADDR1_OFFSET
ECC address1 reg.
XNANDPS_ECC_VALUE0_OFFSET
ECC value 0 reg.
XNANDPS_ECC_VALUE1_OFFSET
ECC value 1 reg.
XNANDPS_ECC_VALUE2_OFFSET
ECC value 2 reg.
XNANDPS_ECC_VALUE3_OFFSET
ECC value 3 reg.
XNANDPS_ECC_VALUE4_OFFSET
ECC value 4 reg.
XNANDPS_INTGTEST_OFFSET
Integration test offset.
XNANDPS_PERIPH_ID0_OFFSET
Peripheral id0 register.
XNANDPS_PERIPH_ID1_OFFSET
Peripheral id1 register.
XNANDPS_PERIPH_ID2_OFFSET
Peripheral id2 register.
XNANDPS_PERIPH_ID3_OFFSET
Peripheral id3 register.
XNANDPS_PCELL_ID0_OFFSET
Primecell id0 register.
XNANDPS_PCELL_ID1_OFFSET
Primecell id1 register.
XNANDPS_PCELL_ID2_OFFSET
Primecell id2 register.
XNANDPS_PCELL_ID3_OFFSET
Primecell id3 register.
ONFI_H
ONFI_CMD_READ1
ONFI Read command (1st cycle)
Referenced by XNandPs_SendCommand.
ONFI_CMD_READ2
ONFI Read command (2nd cycle)
ONFI_CMD_CHANGE_READ_COLUMN1
ONFI Change Read Column command (1st cycle)
Referenced by XNandPs_ReadCache.
ONFI_CMD_CHANGE_READ_COLUMN2
ONFI Change Read Column command (2nd cycle)
Referenced by XNandPs_ReadCache.
ONFI_CMD_BLOCK_ERASE1
ONFI Block Erase (1st cycle)
Referenced by XNandPs_SendCommand.
ONFI_CMD_BLOCK_ERASE2
ONFI Block Erase (2nd cycle)
ONFI_CMD_READ_STATUS
ONFI Read status command.
ONFI_CMD_PAGE_PROG1
ONFI Page Program command (1st cycle)
Referenced by XNandPs_SendCommand.
ONFI_CMD_PAGE_PROG2
ONFI Page Program command (2nd cycle)
ONFI_CMD_CHANGE_WRITE_COLUMN
ONFI Change Write Column command.
ONFI_CMD_READ_ID
ONFI Read ID command.
ONFI_CMD_READ_PARAM_PAGE
ONFI Read Parameter Page command.
ONFI_CMD_RESET
ONFI Reset command.
ONFI_CMD_COPYBACK_READ1
ONFI Copyback Read command (1st cycle)
ONFI_CMD_COPYBACK_READ2
ONFI Copyback Read command (2nd cycle)
ONFI_CMD_READ_CACHE_ENHANCED1
ONFI Read cache enhanced command (1st cycle)
Referenced by XNandPs_ReadCache.
ONFI_CMD_READ_CACHE_ENHANCED2
ONFI Read cache enhanced command (2nd cycle)
Referenced by XNandPs_ReadCache.
ONFI_CMD_READ_CACHE
ONFI Read cache command.
ONFI_CMD_READ_CACHE_END
ONFI Read cache end command.
ONFI_CMD_BLOCK_ERASE_INTERLEAVED2
ONFI Block Erase interleaved command (2nd cycle)
ONFI_CMD_READ_STATUS_ENHANCED
ONFI Read Status enhanced command.
ONFI_CMD_PAGE_PROGRAM_INTERLEAVED2
ONFI Page Program interleaved command (2nd cycle)
ONFI_CMD_PAGE_CACHE_PROGRAM1
ONFI Page cache program (1st cycle)
Referenced by XNandPs_ReadCache.
ONFI_CMD_PAGE_CACHE_PROGRAM2
ONFI Page cache program (2nd cycle)
ONFI_CMD_COPYBACK_PROGRAM1
ONFI Copyback program command (1st cycle)
ONFI_CMD_COPYBACK_PROGRAM2
ONFI Copyback program command (2nd cycle)
ONFI_CMD_COPYBACK_PROGRAM_INTERLEAVED2
ONFI Copyback program interleaved command (2nd cycle)
ONFI_CMD_READ_UNIQUEID
ONFI Read Unique ID command.
ONFI_CMD_GET_FEATURES
ONFI Get features command.
ONFI_CMD_SET_FEATURES
ONFI Set features command.
ONFI_STATUS_FAIL
ONFI Status Register : FAIL.
Referenced by XNandPs_ReadCache, XNandPs_ReadSpareBytes, XNandPs_WriteSpareBytes.
ONFI_STATUS_FAILC
ONFI Status Register : FAILC.
ONFI_STATUS_ARDY
ONFI Status Register : ARDY.
ONFI_STATUS_RDY
ONFI Status Register : RDY.
ONFI_STATUS_WP
ONFI Status Register : WR.
Referenced by XNandPs_EraseBlock, XNandPs_Write, XNandPs_WriteCache.
ONFI_ID_LEN
ONFI ID Length.
Referenced by Onfi_NandInit.
ONFI_CRC_INIT
ONFI CRC16 Initialization constant.
ONFI_CRC_POLYNOM
ONFI CRC16 polynomial.
ONFI_CRC_ORDER
ONFI CRC16 order.
ONFI_PARAM_PAGE_LEN
ONFI Parameter page length.
ONFI_CRC_LEN
ONFI CRC16 length.
ONFI_SIGNATURE_LEN
ONFI Signature Length.