xnandps.c
u32 NandOob16[][]
Ecc position for 16 bytes spare area.
u32 NandOob32[][]
Ecc position for 32 bytes spare area.
u32 NandOob64[][]
Ecc position for 64 bytes spare area.
XNandPs_CommandFormat OnfiCommands[][]
ONFI commands.
ONFI commands.
static int XNandPs_EccHwInit(XNandPs *InstancePtr)
This function initializes the HW ECC block based on flash.
InstancePtr is a pointer to the XNandPs instance. XST_SUCCESS if successful.XST_FAILURE if the flash is not supported. None
static int XNandPs_EccSwInit(XNandPs *InstancePtr)
This function initializes the software variables related to ECC generation, ECC checking and writing ECC bytes in spare bytes.
InstancePtr is a pointer to the XNandPs instance. XST_SUCCESS if successful.XST_FAILURE if the flash is not supported. None
static int XNandPs_ReadPage_HwEcc(XNandPs *InstancePtr, u8 *DstPtr)
This function reads a specific page from NAND device using HW ECC block.
It checks for the ECC errors and corrects single bit errors. The multiple bit error are reported as failure. InstancePtr is a pointer to the XNandPs instance. DstPtr is a pointer to the destination buffer. XST_SUCCESS if successful.XST_FAILURE if fail. None
static int XNandPs_ReadPage(XNandPs *InstancePtr, u8 *DstPtr)
This function reads a specific page from NAND device.
This doesn't use the HW ECC block for checking ECC errors. InstancePtr is a pointer to the XNandPs instance. DstPtr is a pointer to the destination buffer. XST_SUCCESS if successful.XST_FAILURE if fail. None
static int XNandPs_WritePage_HwEcc(XNandPs *InstancePtr, u8 *SrcPtr)
This function writes a specific page in the NAND device using HW ECC block.
The ECC code is written into the spare bytes of the page. InstancePtr is a pointer to the XNandPs instance. SrcPtr is a pointer to the source buffer. XST_SUCCESS if successful.XST_FAILURE if fail. None
static int XNandPs_WritePage(XNandPs *InstancePtr, u8 *SrcPtr)
This function writes a specific page in the NAND device.
This doesn't use the HW ECC block for ECC code generation. InstancePtr is a pointer to the XNandPs instance. SrcPtr is a pointer to the source buffer. XST_SUCCESS if successful.XST_FAILURE if fail. None
static int XNandPs_EccCalculate(XNandPs *InstancePtr, u8 *EccData)
This function calculates the ECC value from the ECC registers.
InstancePtr is a pointer to the XNandPs instance. EccData is the buffer to fill the ECC value. XST_SUCCESS if successful.XST_FAILURE if fail. None
static int XNandPs_EccCorrect(u8 *Buf, u8 *EccCalc, u8 *EccCode)
This function corrects the ECC errors.
Buf is the buffer which holds the data read from the page. EccCalc is the calculated ECC value. EccCode is the ECC read from the spare area. XST_SUCCESS if the ECC error is corrected.XST_FAILURE if the ECC error is not corrected. None
static void XNandPs_ReadBuf(XNandPs *InstancePtr, u8 *Buf, u32 Length)
This function reads the page data from the AXI Data Phase Address.
InstancePtr is a pointer to the XNandPs instance. Buf is the buffer pointer to store the byte. Length is the number of bytes to read. None.
static void XNandPs_WriteBuf(XNandPs *InstancePtr, u8 *Buf, u32 Length)
This function writes the data to the AXI Data Phase Address.
InstancePtr is a pointer to the XNandPs instance. Buf is the buffer pointer to write the data from. Length is the number of bytes to write. None.
static int XNandPs_IsBusy(XNandPs *InstancePtr)
This function checks whether SMC controller busy in processing a request.
InstancePtr is a pointer to the XNandPs instance. - TRUE if SMC is busy FALSE if SMC is free None.
void XNandPs_SendCommand(XNandPs *InstancePtr, XNandPs_CommandFormat *Command, int Page, int Column)
This function sends a NAND command to the flash device.
InstancePtr is the pointer to XNandPs structure Command is the NAND command to send Page is the page offset required for specific commands Column the column offset required for specific commands None None
References XNandPs_CommandFormat::AddrCycles, XNandPs_Geometry::ColAddrCycles, XNandPsTag::CommandPhaseAddr, XNandPsTag::Config, XNandPsTag::DataPhaseAddr, XNandPs_CommandFormat::EndCmd, XNandPs_CommandFormat::EndCmdValid, XNandPs_Config::FlashBase, XNandPs_Geometry::FlashWidth, XNandPsTag::Geometry, ONFI_CMD_BLOCK_ERASE1, ONFI_CMD_PAGE_PROG1, ONFI_CMD_READ1, XNandPs_Geometry::RowAddrCycles, XNandPs_CommandFormat::StartCmd, XNANDPS_ADDR_CYCLES_SHIFT, XNANDPS_CLEAR_CS_SHIFT, XNANDPS_CMD_PHASE, XNANDPS_COLUMN_NOT_VALID, XNANDPS_COMMAND_PHASE_MASK, XNANDPS_DATA_PHASE, XNANDPS_DATA_PHASE_MASK, XNANDPS_ECC_LAST_SHIFT, XNANDPS_END_CMD_SHIFT, XNANDPS_END_CMD_VALID_SHIFT, XNANDPS_FLASH_WIDTH_16, XNANDPS_PAGE_NOT_VALID, XNANDPS_START_CMD_SHIFT, XNandPs_WriteReg.
Referenced by Onfi_CmdReadStatus, XNandPs_EraseBlock, XNandPs_Read, XNandPs_ReadCache, XNandPs_ReadSpareBytes, XNandPs_Write, XNandPs_WriteCache, XNandPs_WriteSpareBytes.
static void XNandPs_EccSetCfg(XNandPs *InstancePtr, u32 EccConfig)
This function initializes the HW ECC block based on flash.
InstancePtr is a pointer to the XNandPs instance. EccConfig is the value of ECC config to update. None None
static void XNandPs_EccSetMemCmd1(XNandPs *InstancePtr, u32 EccCmd)
This function writes ECC MEM CMD1 register with EccCmd value.
InstancePtr is a pointer to the XNandPs instance. EccCmd is register value to write. None None
static void XNandPs_EccSetMemCmd2(XNandPs *InstancePtr, u32 EccCmd)
This function writes ECC MEM CMD2 register with EccCmd value.
InstancePtr is a pointer to the XNandPs instance. EccCmd is register value to write. None None
static void XNandPs_EccDisable(XNandPs *InstancePtr)
This function disables ECC block.
InstancePtr is a pointer to the XNandPs instance. None None
void XNandPs_InitBbtDesc(XNandPs *InstancePtr)
This function initializes the Bad Block Table(BBT) descriptors with a predefined pattern for searching Bad Block Table(BBT) in flash.
InstancePtr is a pointer to the XNandPs instance. NONE
References XNandPsTag::BbPattern, XNandPsTag::BbtDesc, XNandPsTag::BbtMirrorDesc, XNandPs_Geometry::BytesPerPage, XNandPsTag::EccMode, XNandPsTag::Geometry, XNandPsTag::IsReady, XNandPs_BadBlockPattern::Length, XNandPs_BbtDesc::MaxBlocks, XNandPs_BadBlockPattern::Offset, XNandPs_BadBlockPattern::Options, XNandPs_BbtDesc::PageOffset, XNandPs_BadBlockPattern::Pattern, XNandPs_BbtDesc::SigLength, XNandPs_BbtDesc::Signature, XNandPs_BbtDesc::SigOffset, XNandPs_BbtDesc::Valid, XNandPs_BbtDesc::VerOffset, XNandPs_BbtDesc::Version, XNANDPS_BB_PATTERN, XNANDPS_BB_PATTERN_LENGTH_LARGE_PAGE, XNANDPS_BB_PATTERN_LENGTH_SMALL_PAGE, XNANDPS_BB_PATTERN_OFFSET_LARGE_PAGE, XNANDPS_BB_PATTERN_OFFSET_SMALL_PAGE, XNANDPS_BBT_DESC_MAX_BLOCKS, XNANDPS_BBT_DESC_PAGE_OFFSET, XNANDPS_BBT_DESC_SIG_LEN, XNANDPS_BBT_DESC_SIG_OFFSET, XNANDPS_BBT_DESC_VER_OFFSET, XNANDPS_BBT_SCAN_2ND_PAGE, XNANDPS_ECC_ONDIE.
Referenced by XNandPs_CfgInitialize.
int XNandPs_ScanBbt(XNandPs *InstancePtr)
This function reads the Bad Block Table(BBT) if present in flash.
If not it scans the flash for detecting factory marked bad blocks and creates a bad block table and write the Bad Block Table(BBT) into the flash. InstancePtr is a pointer to the XNandPs instance. XST_SUCCESS if successful.XST_FAILURE if fail.
References XNandPsTag::BbtDesc, XNandPsTag::BbtMirrorDesc, XNandPsTag::IsReady.
Referenced by XNandPs_CfgInitialize.
u8 Onfi_CmdReadStatus(XNandPs *InstancePtr)
This function sends read status command to the flash device.
InstancePtr is a pointer to the XNandPs instance. flash status value read None
References XNandPsTag::Config, XNandPsTag::DataPhaseAddr, XNandPs_Config::FlashWidth, READ_STATUS, XNANDPS_COLUMN_NOT_VALID, XNANDPS_FLASH_WIDTH_16, XNANDPS_PAGE_NOT_VALID, XNandPs_SendCommand.
Referenced by XNandPs_EraseBlock, XNandPs_ReadCache, XNandPs_ReadSpareBytes, XNandPs_Write, XNandPs_WriteCache, XNandPs_WriteSpareBytes.
int Onfi_NandInit(XNandPs *InstancePtr)
This function initializes the NAND flash and gets the geometry information.
InstancePtr is a pointer to the XNandPs instance. XST_SUCCESS if successful.XST_FAILURE if failed. None
References OnfiNand_Geometry::AddrCycles, XNandPs_CommandFormat::AddrCycles, BLOCK_ERASE, XNandPs_Geometry::BlockSize, OnfiNand_Geometry::BlocksPerLun, XNandPs_Geometry::BlocksPerLun, OnfiNand_Geometry::BytesPerPage, XNandPs_Geometry::BytesPerPage, CHANGE_READ_COLUMN, CHANGE_WRITE_COLUMN, XNandPs_Geometry::ColAddrCycles, XNandPs_Geometry::DeviceSize, XNandPsTag::EccMode, OnfiNand_Geometry::Features, XNandPsTag::Features, XNandPs_Geometry::FlashWidth, XNandPsTag::Geometry, XNandPs_Geometry::NumBlocks, XNandPs_Geometry::NumLun, OnfiNand_Geometry::NumLuns, XNandPs_Geometry::NumPages, ONFI_ID_LEN, OnfiNand_Geometry::OptionalCmds, PAGE_PROGRAM, OnfiNand_Geometry::PagesPerBlock, XNandPs_Geometry::PagesPerBlock, READ, XNandPs_Geometry::RowAddrCycles, OnfiNand_Geometry::SpareBytesPerPage, XNandPs_Geometry::SpareBytesPerPage, XNANDPS_ECC_HW, XNANDPS_ECC_NONE, XNANDPS_ECC_ONDIE, XNANDPS_FLASH_WIDTH_16, XNANDPS_FLASH_WIDTH_8, XNANDPS_MAX_BLOCKS, XNANDPS_MAX_LUNS, XNANDPS_MAX_PAGE_SIZE, XNANDPS_MAX_PAGES_PER_BLOCK, XNANDPS_MAX_SPARE_SIZE, XNANDPS_MAX_TARGETS.
Referenced by XNandPs_CfgInitialize.
int XNandPs_CfgInitialize(XNandPs *InstancePtr, XNandPs_Config *ConfigPtr, u32 SmcBaseAddr, u32 FlashBaseAddr)
This function initializes a specific XNandPs device/instance.
This function must be called prior to using the flash device to read or write any data. InstancePtr is a pointer to the XNandPs instance. ConfigPtr points to the XNandPs device configuration structure. SmcBaseAddr is the base address of SMC controller. FlashBaseAddr is the base address of NAND flash. XST_SUCCESS if successful.XST_FAILURE if fail. The user needs to first call the XNandPs_LookupConfig() API which returns the Configuration structure pointer which is passed as a parameter to the XNandPs_CfgInitialize() API.
References XNandPs_Geometry::BytesPerPage, XNandPsTag::Config, XNandPsTag::DataBuf, XNandPsTag::EccMode, XNandPs_Config::FlashBase, XNandPs_Config::FlashWidth, XNandPs_Geometry::FlashWidth, XNandPsTag::Geometry, XNandPsTag::IsReady, Onfi_NandInit, XNandPsTag::ReadPage, XNandPs_Config::SmcBase, XNandPsTag::SpareBufPtr, XNandPsTag::WritePage, XNANDPS_CLR_CONFIG, XNANDPS_ECC_HW, XNANDPS_ECC_NONE, XNANDPS_ECC_ONDIE, XNandPs_InitBbtDesc, XNANDPS_MEMC_CLR_CONFIG_OFFSET, XNandPs_ScanBbt, XNandPs_WriteReg.
Referenced by NandReadWriteCacheExample, NandReadWriteExample, NandSkipBlockExample.
int XNandPs_Read(XNandPs *InstancePtr, u64 Offset, u32 Length, void *DestPtr, u8 *UserSparePtr)
This function reads the data from the Flash device and copies it into the specified user buffer.
It doesn't check for the bad blocks while reading the flash pages that cross block boundary. User must take care of handling bad blocks. InstancePtr is the pointer to the XNandPs instance. Offset is the flash data address to read from. Length is number of bytes to read. DestPtr is the destination address to copy data to. UserSparePtr is the user buffer to which spare data must be copied. XST_SUCCESS if successful.XST_FAILURE if fail. This function reads sequential pages from the Flash device.
References XNandPs_Geometry::BytesPerPage, XNandPsTag::Config, XNandPsTag::DataBuf, XNandPs_Geometry::DeviceSize, XNandPsTag::Geometry, XNandPsTag::IsReady, READ, XNandPsTag::ReadPage, XNandPs_Config::SmcBase, XNandPsTag::SpareBufPtr, XNandPs_Geometry::SpareBytesPerPage, XNANDPS_ECC_CMD1, XNANDPS_ECC_CMD2, XNANDPS_MEMC_CLR_CONFIG_INT_CLR1_MASK, XNANDPS_MEMC_CLR_CONFIG_OFFSET, XNandPs_SendCommand, XNandPs_WriteReg.
Referenced by NandReadWriteExample, XNandPs_ReadCache, XNandPs_SkipRead.
int XNandPs_ReadCache(XNandPs *InstancePtr, u64 Offset, u32 Length, void *DestPtr, u8 *UserSparePtr)
This function reads the data from the Flash device using read page cache command and copies it into the specified user buffer.
It doesn't check for the bad blocks while reading the flash pages that cross block boundary. User must take care of handling bad blocks. InstancePtr is the pointer to the XNandPs instance. Offset is the flash data address to read from. Length is number of bytes to read. DestPtr is the destination address to copy data to. UserSparePtr is the user buffer to which spare data must be copied. XST_SUCCESS if successful.XST_FAILURE if fail. This function reads sequential pages from the Flash device.
References XNandPs_Geometry::BytesPerPage, CHANGE_READ_COLUMN, XNandPsTag::Config, XNandPsTag::DataBuf, XNandPs_Geometry::DeviceSize, XNandPsTag::Features, XNandPsTag::Geometry, XNandPsTag::IsReady, ONFI_CMD_CHANGE_READ_COLUMN1, ONFI_CMD_CHANGE_READ_COLUMN2, ONFI_CMD_PAGE_CACHE_PROGRAM1, ONFI_CMD_READ_CACHE_ENHANCED1, ONFI_CMD_READ_CACHE_ENHANCED2, Onfi_CmdReadStatus, ONFI_STATUS_FAIL, READ, READ_CACHE_END_SEQ, READ_CACHE_RANDOM, XNandPsTag::ReadPage, XNandPs_Config::SmcBase, XNandPsTag::SpareBufPtr, XNandPs_Geometry::SpareBytesPerPage, XNANDPS_COLUMN_NOT_VALID, XNANDPS_ECC_MEMCOMMAND1_RD_CMD_END_VALID_MASK, XNANDPS_MEMC_CLR_CONFIG_INT_CLR1_MASK, XNANDPS_MEMC_CLR_CONFIG_OFFSET, XNANDPS_PAGE_NOT_VALID, XNandPs_Read, XNandPs_SendCommand, XNandPs_WriteReg.
Referenced by NandReadWriteCacheExample.
int XNandPs_Write(XNandPs *InstancePtr, u64 Offset, u32 Length, void *SrcPtr, u8 *UserSparePtr)
This function programs the flash device(s) with data specified in the user buffer.
The source and destination address must be aligned to the width of the flash's data bus. It doesn't check for the bad blocks while writing to the flash pages that cross block boundary. User must take care of handling bad blocks. InstancePtr is the pointer to the XNandPs instance. Offset is the flash data address to write to. Length is number of bytes to write. SrcPtr is the source address to write the data from. UserSparePtr is the user buffer which contains buffer to write into spare data area. XST_SUCCESS if successful.XST_FAILURE if fail.XST_NAND_WRITE_PROTECTED if the flash is write protected. This function writes number of sequential pages into the Flash device.
References XNandPs_Geometry::BytesPerPage, XNandPsTag::DataBuf, XNandPs_Geometry::DeviceSize, XNandPsTag::Geometry, XNandPsTag::IsReady, Onfi_CmdReadStatus, ONFI_STATUS_WP, PAGE_PROGRAM, XNandPsTag::SpareBufPtr, XNandPs_Geometry::SpareBytesPerPage, XNandPsTag::WritePage, XNandPs_SendCommand.
Referenced by NandReadWriteExample, XNandPs_SkipWrite, XNandPs_WriteCache.
int XNandPs_WriteCache(XNandPs *InstancePtr, u64 Offset, u32 Length, void *SrcPtr, u8 *UserSparePtr)
This function programs the flash device(s) with data specified in the user buffer using program cache command.
The source and destination address must be aligned to the width of the flash's data bus. It doesn't check for the bad blocks while writing to the flash pages that cross block boundary. User must take care of handling bad blocks. InstancePtr is the pointer to the XNandPs instance. Offset is the flash data address to write to. Length is number of bytes to write. SrcPtr is the source address to write the data from. UserSparePtr is the user buffer which contains buffer to write into spare data area. XST_SUCCESS if successful.XST_FAILURE if fail.XST_NAND_WRITE_PROTECTED if the flash is write protected. This function writes number of sequential pages into the Flash device.
References XNandPs_Geometry::BytesPerPage, XNandPsTag::DataBuf, XNandPs_Geometry::DeviceSize, XNandPsTag::Geometry, XNandPsTag::IsReady, Onfi_CmdReadStatus, ONFI_STATUS_WP, PAGE_CACHE_PROGRAM, PAGE_PROGRAM, XNandPsTag::SpareBufPtr, XNandPs_Geometry::SpareBytesPerPage, XNandPsTag::WritePage, XNandPs_SendCommand, XNandPs_Write.
Referenced by NandReadWriteCacheExample.
int XNandPs_ReadSpareBytes(XNandPs *InstancePtr, u32 Page, u8 *Buf)
This function reads the spare area of a page.
InstancePtr is the pointer to the XNandPs instance. Page is the page number from where spare data is read. Buf is pointer to the buffer where the spare data is filled. XST_SUCCESS if successful.XST_FAILURE if fail. None.
References XNandPs_Geometry::BytesPerPage, XNandPsTag::Config, XNandPsTag::DataPhaseAddr, XNandPsTag::EccMode, XNandPs_Config::FlashBase, XNandPsTag::Geometry, Onfi_CmdReadStatus, ONFI_STATUS_FAIL, READ, XNandPs_Config::SmcBase, XNandPs_Geometry::SpareBytesPerPage, XNANDPS_ADDR_CYCLES_SHIFT, XNANDPS_AXI_DATA_WIDTH, XNANDPS_CLR_CS, XNANDPS_COMMAND_PHASE_MASK, XNANDPS_ECC_HW, XNANDPS_END_CMD_SHIFT, XNANDPS_END_CMD_VALID_SHIFT, XNANDPS_MEMC_CLR_CONFIG_INT_CLR1_MASK, XNANDPS_MEMC_CLR_CONFIG_OFFSET, XNandPs_SendCommand, XNANDPS_START_CMD_SHIFT, XNandPs_WriteReg.
int XNandPs_WriteSpareBytes(XNandPs *InstancePtr, u32 Page, u8 *Buf)
This function write to the spare area of a page.
InstancePtr is the pointer to the XNandPs instance. Page is the page number to write. Buf is pointer to the buffer which holds the data. XST_SUCCESS if successful.XST_FAILURE if fail. None.
References XNandPs_Geometry::BytesPerPage, XNandPsTag::Config, XNandPsTag::DataPhaseAddr, XNandPsTag::EccMode, XNandPsTag::Geometry, Onfi_CmdReadStatus, ONFI_STATUS_FAIL, PAGE_PROGRAM, XNandPs_Config::SmcBase, XNandPs_Geometry::SpareBytesPerPage, XNANDPS_AXI_DATA_WIDTH, XNANDPS_CLR_CS, XNANDPS_ECC_HW, XNANDPS_MEMC_CLR_CONFIG_INT_CLR1_MASK, XNANDPS_MEMC_CLR_CONFIG_OFFSET, XNandPs_SendCommand, XNandPs_WriteReg.
int XNandPs_EraseBlock(XNandPs *InstancePtr, u32 BlockNum)
This function erases a specific block in the NAND device.
InstancePtr is a pointer to the XNandPs instance. BlockNum is the block number of the device. XST_SUCCESS if successful.XST_FAILURE if fail.XST_NAND_WRITE_PROTECTED if the flash is write protected. None
References BLOCK_ERASE, XNandPsTag::Config, XNandPsTag::Geometry, XNandPsTag::IsReady, Onfi_CmdReadStatus, ONFI_STATUS_WP, XNandPs_Geometry::PagesPerBlock, XNandPs_Config::SmcBase, XNANDPS_COLUMN_NOT_VALID, XNANDPS_MEMC_CLR_CONFIG_INT_CLR1_MASK, XNANDPS_MEMC_CLR_CONFIG_OFFSET, XNandPs_SendCommand, XNandPs_WriteReg.
Referenced by NandReadWriteCacheExample, NandReadWriteExample, XNandPs_SkipErase.