xnandps_bbm.c
static int XNandPs_ReadBbt(XNandPs *InstancePtr)
< For memcpy and memset
This function searches the Bad Block Table(BBT) in flash and loads into the memory based Bad Block Table(BBT). InstancePtr is the pointer to the XNandPs instance. XST_SUCCESS if successful.XST_FAILURE if fail.
static int XNandPs_SearchBbt(XNandPs *InstancePtr, XNandPs_BbtDesc *Desc)
This function searches the BBT in flash.
InstancePtr is the pointer to the XNandPs instance. Desc is the BBT descriptor pattern to search. XST_SUCCESS if successful.XST_FAILURE if fail.
static void XNandPs_CreateBbt(XNandPs *InstancePtr)
This function scans the NAND flash for factory marked bad blocks and creates a RAM based Bad Block Table(BBT).
InstancePtr is a pointer to the XNandPs instance. NONE
static void XNandPs_ConvertBbt(XNandPs *InstancePtr, u8 *Buf)
This function converts the Bad Block Table(BBT) read from the flash to the RAM based Bad Block Table(BBT).
InstancePtr is a pointer to the XNandPs instance. Buf is the buffer which contains BBT read from flash. NONE.
static int XNandPs_WriteBbt(XNandPs *InstancePtr, XNandPs_BbtDesc *Desc, XNandPs_BbtDesc *MirrorDesc)
This function writes Bad Block Table(BBT) from RAM to flash.
InstancePtr is the pointer to the XNandPs instance. Desc is the BBT descriptor to be written to flash. MirrorDesc is the mirror BBT descriptor. XST_SUCCESS if successful.XST_FAILURE if fail.
static int XNandPs_MarkBbt(XNandPs *InstancePtr, XNandPs_BbtDesc *Desc)
This function marks the block containing Bad Block Table as reserved and updates the BBT.
InstancePtr is the pointer to the XNandPs instance. Desc is the BBT descriptor pointer. XST_SUCCESS if successful.XST_FAILURE if fail.
static int XNandPs_UpdateBbt(XNandPs *InstancePtr)
This function updates the primary and mirror Bad Block Table(BBT) in the flash.
InstancePtr is the pointer to the XNandPs instance. XST_SUCCESS if successful.XST_FAILURE if fail.
int XNandPs_ReadSpareBytes(XNandPs *InstancePtr, u32 Page, u8 *Buf)
This function reads the spare area of a page.
InstancePtr is the pointer to the XNandPs instance. Page is the page number from where spare data is read. Buf is pointer to the buffer where the spare data is filled. XST_SUCCESS if successful.XST_FAILURE if fail. None.
References XNandPs_Geometry::BytesPerPage, XNandPsTag::Config, XNandPsTag::DataPhaseAddr, XNandPsTag::EccMode, XNandPs_Config::FlashBase, XNandPsTag::Geometry, Onfi_CmdReadStatus, ONFI_STATUS_FAIL, READ, XNandPs_Config::SmcBase, XNandPs_Geometry::SpareBytesPerPage, XNANDPS_ADDR_CYCLES_SHIFT, XNANDPS_AXI_DATA_WIDTH, XNANDPS_CLR_CS, XNANDPS_COMMAND_PHASE_MASK, XNANDPS_ECC_HW, XNANDPS_END_CMD_SHIFT, XNANDPS_END_CMD_VALID_SHIFT, XNANDPS_MEMC_CLR_CONFIG_INT_CLR1_MASK, XNANDPS_MEMC_CLR_CONFIG_OFFSET, XNandPs_SendCommand, XNANDPS_START_CMD_SHIFT, XNandPs_WriteReg.
void XNandPs_InitBbtDesc(XNandPs *InstancePtr)
This function initializes the Bad Block Table(BBT) descriptors with a predefined pattern for searching Bad Block Table(BBT) in flash.
InstancePtr is a pointer to the XNandPs instance. NONE
References XNandPsTag::BbPattern, XNandPsTag::BbtDesc, XNandPsTag::BbtMirrorDesc, XNandPs_Geometry::BytesPerPage, XNandPsTag::EccMode, XNandPsTag::Geometry, XNandPsTag::IsReady, XNandPs_BadBlockPattern::Length, XNandPs_BbtDesc::MaxBlocks, XNandPs_BadBlockPattern::Offset, XNandPs_BadBlockPattern::Options, XNandPs_BbtDesc::PageOffset, XNandPs_BadBlockPattern::Pattern, XNandPs_BbtDesc::SigLength, XNandPs_BbtDesc::Signature, XNandPs_BbtDesc::SigOffset, XNandPs_BbtDesc::Valid, XNandPs_BbtDesc::VerOffset, XNandPs_BbtDesc::Version, XNANDPS_BB_PATTERN, XNANDPS_BB_PATTERN_LENGTH_LARGE_PAGE, XNANDPS_BB_PATTERN_LENGTH_SMALL_PAGE, XNANDPS_BB_PATTERN_OFFSET_LARGE_PAGE, XNANDPS_BB_PATTERN_OFFSET_SMALL_PAGE, XNANDPS_BBT_DESC_MAX_BLOCKS, XNANDPS_BBT_DESC_PAGE_OFFSET, XNANDPS_BBT_DESC_SIG_LEN, XNANDPS_BBT_DESC_SIG_OFFSET, XNANDPS_BBT_DESC_VER_OFFSET, XNANDPS_BBT_SCAN_2ND_PAGE, XNANDPS_ECC_ONDIE.
Referenced by XNandPs_CfgInitialize.
int XNandPs_ScanBbt(XNandPs *InstancePtr)
This function reads the Bad Block Table(BBT) if present in flash.
If not it scans the flash for detecting factory marked bad blocks and creates a bad block table and write the Bad Block Table(BBT) into the flash. InstancePtr is a pointer to the XNandPs instance. XST_SUCCESS if successful.XST_FAILURE if fail.
References XNandPsTag::BbtDesc, XNandPsTag::BbtMirrorDesc, XNandPsTag::IsReady.
Referenced by XNandPs_CfgInitialize.
int XNandPs_IsBlockBad(XNandPs *InstancePtr, u32 Block)
This function checks whether a block is bad or not.
InstancePtr is the pointer to the XNandPs instance. Block is the block number. XST_SUCCESS if successful.XST_FAILURE if fail.
References XNandPsTag::Bbt, XNandPsTag::IsReady, XNANDPS_BBT_BLOCK_SHIFT, XNandPs_BbtBlockShift, XNANDPS_BLOCK_GOOD, XNANDPS_BLOCK_TYPE_MASK.
Referenced by NandReadWriteCacheExample, NandReadWriteExample, XNandPs_CalculateLength, XNandPs_SkipErase, XNandPs_SkipRead, XNandPs_SkipWrite.
int XNandPs_MarkBlockBad(XNandPs *InstancePtr, u32 Block)
This function marks a block as bad in the RAM based Bad Block Table(BBT).
It also updates the Bad Block Table(BBT) in the flash. InstancePtr is the pointer to the XNandPs instance. Block is the block number. XST_SUCCESS if successful.XST_FAILURE if fail.
References XNandPsTag::Bbt, XNandPsTag::IsReady, XNANDPS_BBT_BLOCK_SHIFT, XNandPs_BbtBlockShift, XNANDPS_BLOCK_BAD, XNANDPS_BLOCK_TYPE_MASK.