xnandps_sinit.c
XNandPs_Config XNandPs_ConfigTable[][]
This table contains configuration information for each System Monitor/ADC device in the system.
XNandPs_Config * XNandPs_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XNandPs_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xnandps.h for the definition of XNandPs_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XNandPs_Config::Name.
Referenced by NandReadWriteCacheExample, NandReadWriteExample, NandSkipBlockExample.