xnandps_skip_example.c
NAND_TEST_OFFSET
Flash Test Offset.
Referenced by NandSkipBlockExample.
NAND_TEST_LENGTH
Test Length.
Referenced by NandSkipBlockExample.
XNandPs NandInstance
XNandPs* NandInstPtr
u8 ReadBuffer[NAND_TEST_LENGTH][NAND_TEST_LENGTH]
u8 WriteBuffer[NAND_TEST_LENGTH][NAND_TEST_LENGTH]
int NandSkipBlockExample(UINTPTR BaseAddress)
This function runs a test on the NAND flash device using the basic driver functions.
The function does the following tasks: Initialize the driver.Erase the required length of bytes by taking bad blocks into account.Write the number of bytes from given offset by taking bad blocks into account.Read the number of bytes from given offset by taking bad blocks into account.Compare the data read against the data Written. BaseAddress contains the base address of the device XST_SUCCESS if successful.XST_FAILURE if failed. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XNandPs_Config::FlashBase, NAND_TEST_LENGTH, NAND_TEST_OFFSET, ReadBuffer, XNandPs_Config::SmcBase, WriteBuffer, XNandPs_CfgInitialize, XNandPs_LookupConfig, XNandPs_SkipErase, XNandPs_SkipRead, XNandPs_SkipWrite.
Referenced by main.
int XNandPs_SkipRead(XNandPs *InstancePtr, u64 Offset, u32 Length, void *DestPtr)
This function reads the data from the Flash device and copies it into the specified user buffer.
This function considers bad blocks and skips them to read next blocks. InstancePtr is the pointer to the XNandPs instance. Offset is the flash data address to read from. Length is number of bytes to read. DestPtr is the destination address to copy data to. XST_SUCCESS if successful.XST_FAILURE if fail. None.
References XNandPs_Geometry::BlockSize, XNandPs_Geometry::DeviceSize, XNandPsTag::Geometry, XNandPs_CalculateLength, XNandPs_IsBlockBad, XNandPs_Read.
Referenced by NandSkipBlockExample.
int XNandPs_SkipWrite(XNandPs *InstancePtr, u64 Offset, u32 Length, void *SrcPtr)
This function programs the flash device(s) with data specified in the user buffer.
This function considers bad blocks and skips them. InstancePtr is the pointer to the XNandPs instance. Offset is the flash data address to write to. Length is number of bytes to write. SrcPtr is the source address to write the data from. XST_SUCCESS if successful.XST_FAILURE if fail. None.
References XNandPs_Geometry::BlockSize, XNandPs_Geometry::DeviceSize, XNandPsTag::Geometry, XNandPs_CalculateLength, XNandPs_IsBlockBad, XNandPs_Write.
Referenced by NandSkipBlockExample.
int XNandPs_SkipErase(XNandPs *InstancePtr, u64 Offset, u32 Length)
This function erases length bytes in the flash device from a given offset.
The Offset and Length must be block aligned. This functions skips bad blocks. InstancePtr is the pointer to the XNand instance. Offset is the flash address to start erasing from. Length is number of bytes to erase. XST_SUCCESS if successful.XST_FAILURE if error in erase. None.
References XNandPs_Geometry::BlockSize, XNandPsTag::Geometry, XNandPs_Geometry::NumBlocks, XNandPs_EraseBlock, XNandPs_IsBlockBad.
Referenced by NandSkipBlockExample.
int main(void)
Main function to execute the Skip Block based Nand read/write example.
XST_SUCCESS if the example has completed successfully.XST_FAILURE if the example has failed. None.
References NandSkipBlockExample.
u32 XNandPs_CalculateLength(XNandPs *InstancePtr, u64 Offset, u32 Length)
This function returns the length including bad blocks from a given offset and length.
InstancePtr is the pointer to the XNandPs instance. Offset is the flash data address to read from. Length is number of bytes to read. Return actual length including bad blocks. None.
References XNandPs_Geometry::BlockSize, XNandPs_Geometry::DeviceSize, XNandPsTag::Geometry, XNandPs_IsBlockBad.
Referenced by XNandPs_SkipRead, XNandPs_SkipWrite.