xnandps.h
XNANDPS_H
XNANDPS_MAX_TARGETS
Max number of targets supported.
Referenced by Onfi_NandInit.
XNANDPS_MAX_BLOCKS
Max number of Blocks.
Referenced by Onfi_NandInit.
XNANDPS_MAX_PAGE_SIZE
Max page size of NAND flash.
Referenced by Onfi_NandInit.
XNANDPS_MAX_SPARE_SIZE
Max spare bytes of a NAND flash page.
Referenced by Onfi_NandInit.
XNANDPS_MAX_LUNS
Max number of LUNs.
Referenced by Onfi_NandInit.
XNANDPS_MAX_PAGES_PER_BLOCK
Max number pages per block.
Referenced by Onfi_NandInit.
XNANDPS_ECC_BLOCK_SIZE
ECC block size.
XNANDPS_ECC_BYTES
ECC bytes per ECC block.
XNANDPS_PAGE_SIZE_512
Page size 512.
XNANDPS_PAGE_SIZE_1024
Page size 1024.
XNANDPS_PAGE_SIZE_2048
Page size 2048.
XNANDPS_PAGE_SIZE_4096
Page size 4096.
XNANDPS_PAGE_SIZE_8192
Page size 8192.
XNANDPS_SPARE_SIZE_8
Spare bytes size 8.
XNANDPS_SPARE_SIZE_16
Spare bytes size 16.
XNANDPS_SPARE_SIZE_32
Spare bytes size 32.
XNANDPS_SPARE_SIZE_64
Spare bytes size 64.
XNANDPS_SPARE_SIZE_128
Spare bytes size 128.
XNANDPS_SPARE_SIZE_256
Spare bytes size 256.
XNANDPS_FLASH_WIDTH_8
NAND Flash width 8-bit.
Referenced by Onfi_NandInit.
XNANDPS_FLASH_WIDTH_16
NAND Flash width 16-bit.
Referenced by Onfi_CmdReadStatus, Onfi_NandInit, XNandPs_SendCommand.
XNANDPS_END_CMD_NONE
No End command.
XNANDPS_END_CMD_INVALID
End command invalid.
XNANDPS_CMD_PHASE
End command in command phase.
Referenced by XNandPs_SendCommand.
XNANDPS_DATA_PHASE
End command in data phase.
Referenced by XNandPs_SendCommand.
XNANDPS_PAGE_NOT_VALID
Page is not valid in command phase.
Referenced by Onfi_CmdReadStatus, XNandPs_ReadCache, XNandPs_SendCommand.
XNANDPS_COLUMN_NOT_VALID
Column is not valid in command phase.
Referenced by Onfi_CmdReadStatus, XNandPs_EraseBlock, XNandPs_ReadCache, XNandPs_SendCommand.
XNANDPS_AXI_DATA_WIDTH
AXI Data width for last transaction while reading and writing.
Referenced by XNandPs_ReadSpareBytes, XNandPs_WriteSpareBytes.
XNANDPS_START_CMD_SHIFT
Start command shift.
Referenced by XNandPs_ReadSpareBytes, XNandPs_SendCommand.
XNANDPS_END_CMD_SHIFT
End command shift.
Referenced by XNandPs_ReadSpareBytes, XNandPs_SendCommand.
XNANDPS_END_CMD_VALID_SHIFT
End command valid shift.
Referenced by XNandPs_ReadSpareBytes, XNandPs_SendCommand.
XNANDPS_ADDR_CYCLES_SHIFT
Address cycles shift.
Referenced by XNandPs_ReadSpareBytes, XNandPs_SendCommand.
XNANDPS_CHIP_ADDR_SHIFT
Chip address shift.
XNANDPS_ECC_LAST_SHIFT
Ecc last shift.
Referenced by XNandPs_SendCommand.
XNANDPS_CLEAR_CS_SHIFT
clear chip select shift
Referenced by XNandPs_SendCommand.
XNANDPS_COMMAND_PHASE_MASK
Command phase mask.
Referenced by XNandPs_ReadSpareBytes, XNandPs_SendCommand.
XNANDPS_DATA_PHASE_MASK
Data phase mask.
Referenced by XNandPs_SendCommand.
XNANDPS_ECC_CORRECT_BYTE_MASK
ECC error correction byte position mask, bits[11:3] of error code.
XNANDPS_ECC_CORRECT_BIT_MASK
ECC error correction bit position mask, bits[0:2] of error code.
XNANDPS_CLR_CONFIG
Interrupt settings.
Referenced by XNandPs_CfgInitialize.
XNANDPS_ECC_MEMCFG
ECC memory configuration settings.
XNANDPS_ECC_CMD1
ECC command 1 settings.
Referenced by XNandPs_Read.
XNANDPS_ECC_CMD2
ECC command 2 settings.
Referenced by XNandPs_Read.
XNANDPS_CLR_CS
set Clear chip select
Referenced by XNandPs_ReadSpareBytes, XNandPs_WriteSpareBytes.
XNANDPS_ECC_LAST
set Ecc last
OneHot
OneHot is used to check if one and only one bit is set.
This Macro returns 1 if the value passed is OneHot.
XNandPs_EccMode
No ECC.
typedef struct XNandPsTag XNandPs
The XNandPs driver instance data.
The user is required to allocate a variable of this type for every flash device in the system. A pointer to a variable of this type is then passed to the driver API functions.
XNandPs_Config * XNandPs_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XNandPs_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xnandps.h for the definition of XNandPs_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XNandPs_Config::Name.
Referenced by NandReadWriteCacheExample, NandReadWriteExample, NandSkipBlockExample.
int XNandPs_CfgInitialize(XNandPs *InstancePtr, XNandPs_Config *ConfigPtr, u32 SmcBaseAddr, u32 FlashBaseAddr)
This function initializes a specific XNandPs device/instance.
This function must be called prior to using the flash device to read or write any data. InstancePtr is a pointer to the XNandPs instance. ConfigPtr points to the XNandPs device configuration structure. SmcBaseAddr is the base address of SMC controller. FlashBaseAddr is the base address of NAND flash. XST_SUCCESS if successful.XST_FAILURE if fail. The user needs to first call the XNandPs_LookupConfig() API which returns the Configuration structure pointer which is passed as a parameter to the XNandPs_CfgInitialize() API.
References XNandPs_Geometry::BytesPerPage, XNandPsTag::Config, XNandPsTag::DataBuf, XNandPsTag::EccMode, XNandPs_Config::FlashBase, XNandPs_Config::FlashWidth, XNandPs_Geometry::FlashWidth, XNandPsTag::Geometry, XNandPsTag::IsReady, Onfi_NandInit, XNandPsTag::ReadPage, XNandPs_Config::SmcBase, XNandPsTag::SpareBufPtr, XNandPsTag::WritePage, XNANDPS_CLR_CONFIG, XNANDPS_ECC_HW, XNANDPS_ECC_NONE, XNANDPS_ECC_ONDIE, XNandPs_InitBbtDesc, XNANDPS_MEMC_CLR_CONFIG_OFFSET, XNandPs_ScanBbt, XNandPs_WriteReg.
Referenced by NandReadWriteCacheExample, NandReadWriteExample, NandSkipBlockExample.
int XNandPs_Read(XNandPs *InstancePtr, u64 Offset, u32 Length, void *DestPtr, u8 *UserSparePtr)
This function reads the data from the Flash device and copies it into the specified user buffer.
It doesn't check for the bad blocks while reading the flash pages that cross block boundary. User must take care of handling bad blocks. InstancePtr is the pointer to the XNandPs instance. Offset is the flash data address to read from. Length is number of bytes to read. DestPtr is the destination address to copy data to. UserSparePtr is the user buffer to which spare data must be copied. XST_SUCCESS if successful.XST_FAILURE if fail. This function reads sequential pages from the Flash device.
References XNandPs_Geometry::BytesPerPage, XNandPsTag::Config, XNandPsTag::DataBuf, XNandPs_Geometry::DeviceSize, XNandPsTag::Geometry, XNandPsTag::IsReady, READ, XNandPsTag::ReadPage, XNandPs_Config::SmcBase, XNandPsTag::SpareBufPtr, XNandPs_Geometry::SpareBytesPerPage, XNANDPS_ECC_CMD1, XNANDPS_ECC_CMD2, XNANDPS_MEMC_CLR_CONFIG_INT_CLR1_MASK, XNANDPS_MEMC_CLR_CONFIG_OFFSET, XNandPs_SendCommand, XNandPs_WriteReg.
Referenced by NandReadWriteExample, XNandPs_ReadCache, XNandPs_SkipRead.
int XNandPs_ReadCache(XNandPs *InstancePtr, u64 Offset, u32 Length, void *DestPtr, u8 *UserSparePtr)
This function reads the data from the Flash device using read page cache command and copies it into the specified user buffer.
It doesn't check for the bad blocks while reading the flash pages that cross block boundary. User must take care of handling bad blocks. InstancePtr is the pointer to the XNandPs instance. Offset is the flash data address to read from. Length is number of bytes to read. DestPtr is the destination address to copy data to. UserSparePtr is the user buffer to which spare data must be copied. XST_SUCCESS if successful.XST_FAILURE if fail. This function reads sequential pages from the Flash device.
References XNandPs_Geometry::BytesPerPage, CHANGE_READ_COLUMN, XNandPsTag::Config, XNandPsTag::DataBuf, XNandPs_Geometry::DeviceSize, XNandPsTag::Features, XNandPsTag::Geometry, XNandPsTag::IsReady, ONFI_CMD_CHANGE_READ_COLUMN1, ONFI_CMD_CHANGE_READ_COLUMN2, ONFI_CMD_PAGE_CACHE_PROGRAM1, ONFI_CMD_READ_CACHE_ENHANCED1, ONFI_CMD_READ_CACHE_ENHANCED2, Onfi_CmdReadStatus, ONFI_STATUS_FAIL, READ, READ_CACHE_END_SEQ, READ_CACHE_RANDOM, XNandPsTag::ReadPage, XNandPs_Config::SmcBase, XNandPsTag::SpareBufPtr, XNandPs_Geometry::SpareBytesPerPage, XNANDPS_COLUMN_NOT_VALID, XNANDPS_ECC_MEMCOMMAND1_RD_CMD_END_VALID_MASK, XNANDPS_MEMC_CLR_CONFIG_INT_CLR1_MASK, XNANDPS_MEMC_CLR_CONFIG_OFFSET, XNANDPS_PAGE_NOT_VALID, XNandPs_Read, XNandPs_SendCommand, XNandPs_WriteReg.
Referenced by NandReadWriteCacheExample.
int XNandPs_Write(XNandPs *InstancePtr, u64 Offset, u32 Length, void *SrcPtr, u8 *UserSparePtr)
This function programs the flash device(s) with data specified in the user buffer.
The source and destination address must be aligned to the width of the flash's data bus. It doesn't check for the bad blocks while writing to the flash pages that cross block boundary. User must take care of handling bad blocks. InstancePtr is the pointer to the XNandPs instance. Offset is the flash data address to write to. Length is number of bytes to write. SrcPtr is the source address to write the data from. UserSparePtr is the user buffer which contains buffer to write into spare data area. XST_SUCCESS if successful.XST_FAILURE if fail.XST_NAND_WRITE_PROTECTED if the flash is write protected. This function writes number of sequential pages into the Flash device.
References XNandPs_Geometry::BytesPerPage, XNandPsTag::DataBuf, XNandPs_Geometry::DeviceSize, XNandPsTag::Geometry, XNandPsTag::IsReady, Onfi_CmdReadStatus, ONFI_STATUS_WP, PAGE_PROGRAM, XNandPsTag::SpareBufPtr, XNandPs_Geometry::SpareBytesPerPage, XNandPsTag::WritePage, XNandPs_SendCommand.
Referenced by NandReadWriteExample, XNandPs_SkipWrite, XNandPs_WriteCache.
int XNandPs_WriteCache(XNandPs *InstancePtr, u64 Offset, u32 Length, void *SrcPtr, u8 *UserSparePtr)
This function programs the flash device(s) with data specified in the user buffer using program cache command.
The source and destination address must be aligned to the width of the flash's data bus. It doesn't check for the bad blocks while writing to the flash pages that cross block boundary. User must take care of handling bad blocks. InstancePtr is the pointer to the XNandPs instance. Offset is the flash data address to write to. Length is number of bytes to write. SrcPtr is the source address to write the data from. UserSparePtr is the user buffer which contains buffer to write into spare data area. XST_SUCCESS if successful.XST_FAILURE if fail.XST_NAND_WRITE_PROTECTED if the flash is write protected. This function writes number of sequential pages into the Flash device.
References XNandPs_Geometry::BytesPerPage, XNandPsTag::DataBuf, XNandPs_Geometry::DeviceSize, XNandPsTag::Geometry, XNandPsTag::IsReady, Onfi_CmdReadStatus, ONFI_STATUS_WP, PAGE_CACHE_PROGRAM, PAGE_PROGRAM, XNandPsTag::SpareBufPtr, XNandPs_Geometry::SpareBytesPerPage, XNandPsTag::WritePage, XNandPs_SendCommand, XNandPs_Write.
Referenced by NandReadWriteCacheExample.
int XNandPs_ReadSpareBytes(XNandPs *InstancePtr, u32 Page, u8 *Buf)
This function reads the spare area of a page.
InstancePtr is the pointer to the XNandPs instance. Page is the page number from where spare data is read. Buf is pointer to the buffer where the spare data is filled. XST_SUCCESS if successful.XST_FAILURE if fail. None.
References XNandPs_Geometry::BytesPerPage, XNandPsTag::Config, XNandPsTag::DataPhaseAddr, XNandPsTag::EccMode, XNandPs_Config::FlashBase, XNandPsTag::Geometry, Onfi_CmdReadStatus, ONFI_STATUS_FAIL, READ, XNandPs_Config::SmcBase, XNandPs_Geometry::SpareBytesPerPage, XNANDPS_ADDR_CYCLES_SHIFT, XNANDPS_AXI_DATA_WIDTH, XNANDPS_CLR_CS, XNANDPS_COMMAND_PHASE_MASK, XNANDPS_ECC_HW, XNANDPS_END_CMD_SHIFT, XNANDPS_END_CMD_VALID_SHIFT, XNANDPS_MEMC_CLR_CONFIG_INT_CLR1_MASK, XNANDPS_MEMC_CLR_CONFIG_OFFSET, XNandPs_SendCommand, XNANDPS_START_CMD_SHIFT, XNandPs_WriteReg.
int XNandPs_WriteSpareBytes(XNandPs *InstancePtr, u32 Page, u8 *Buf)
This function write to the spare area of a page.
InstancePtr is the pointer to the XNandPs instance. Page is the page number to write. Buf is pointer to the buffer which holds the data. XST_SUCCESS if successful.XST_FAILURE if fail. None.
References XNandPs_Geometry::BytesPerPage, XNandPsTag::Config, XNandPsTag::DataPhaseAddr, XNandPsTag::EccMode, XNandPsTag::Geometry, Onfi_CmdReadStatus, ONFI_STATUS_FAIL, PAGE_PROGRAM, XNandPs_Config::SmcBase, XNandPs_Geometry::SpareBytesPerPage, XNANDPS_AXI_DATA_WIDTH, XNANDPS_CLR_CS, XNANDPS_ECC_HW, XNANDPS_MEMC_CLR_CONFIG_INT_CLR1_MASK, XNANDPS_MEMC_CLR_CONFIG_OFFSET, XNandPs_SendCommand, XNandPs_WriteReg.
int XNandPs_EraseBlock(XNandPs *InstancePtr, u32 BlockNum)
This function erases a specific block in the NAND device.
InstancePtr is a pointer to the XNandPs instance. BlockNum is the block number of the device. XST_SUCCESS if successful.XST_FAILURE if fail.XST_NAND_WRITE_PROTECTED if the flash is write protected. None
References BLOCK_ERASE, XNandPsTag::Config, XNandPsTag::Geometry, XNandPsTag::IsReady, Onfi_CmdReadStatus, ONFI_STATUS_WP, XNandPs_Geometry::PagesPerBlock, XNandPs_Config::SmcBase, XNANDPS_COLUMN_NOT_VALID, XNANDPS_MEMC_CLR_CONFIG_INT_CLR1_MASK, XNANDPS_MEMC_CLR_CONFIG_OFFSET, XNandPs_SendCommand, XNandPs_WriteReg.
Referenced by NandReadWriteCacheExample, NandReadWriteExample, XNandPs_SkipErase.