xnandps_bbm.h
BBM_H
XNANDPS_BLOCK_GOOD
Block is good.
Referenced by XNandPs_IsBlockBad.
XNANDPS_BLOCK_BAD
Block is bad.
Referenced by XNandPs_MarkBlockBad.
XNANDPS_BLOCK_RESERVED
Reserved block.
XNANDPS_BLOCK_FACTORY_BAD
Factory marked bad block.
XNANDPS_FLASH_BLOCK_GOOD
Block is good.
XNANDPS_FLASH_BLOCK_BAD
Block is bad.
XNANDPS_FLASH_BLOCK_RESERVED
Reserved block.
XNANDPS_FLASH_BLOCK_FACTORY_BAD
Factory marked bad block.
XNANDPS_BBT_SCAN_2ND_PAGE
Scan the second page for bad block information.
Referenced by XNandPs_InitBbtDesc.
XNANDPS_BBT_DESC_PAGE_OFFSET
Page offset of Bad Block Table Desc.
Referenced by XNandPs_InitBbtDesc.
XNANDPS_BBT_DESC_SIG_OFFSET
Bad Block Table signature offset.
Referenced by XNandPs_InitBbtDesc.
XNANDPS_BBT_DESC_VER_OFFSET
Bad block Table version offset.
Referenced by XNandPs_InitBbtDesc.
XNANDPS_BBT_DESC_SIG_LEN
Bad block Table signature length.
Referenced by XNandPs_InitBbtDesc.
XNANDPS_BBT_DESC_MAX_BLOCKS
Bad block Table max blocks.
Referenced by XNandPs_InitBbtDesc.
XNANDPS_BBT_BLOCK_SHIFT
Block shift value for a block in BBT.
Referenced by XNandPs_IsBlockBad, XNandPs_MarkBlockBad.
XNANDPS_BBT_ENTRY_NUM_BLOCKS
Num of blocks in one BBT entry.
XNANDPS_BB_PATTERN_OFFSET_SMALL_PAGE
Bad block pattern offset in a page.
Referenced by XNandPs_InitBbtDesc.
XNANDPS_BB_PATTERN_LENGTH_SMALL_PAGE
Bad block pattern length.
Referenced by XNandPs_InitBbtDesc.
XNANDPS_BB_PATTERN_OFFSET_LARGE_PAGE
Bad block pattern offset in a large page.
Referenced by XNandPs_InitBbtDesc.
XNANDPS_BB_PATTERN_LENGTH_LARGE_PAGE
Bad block pattern length.
Referenced by XNandPs_InitBbtDesc.
XNANDPS_BB_PATTERN
Bad block pattern to search in a page.
Referenced by XNandPs_InitBbtDesc.
XNANDPS_BLOCK_TYPE_MASK
Block type mask.
Referenced by XNandPs_IsBlockBad, XNandPs_MarkBlockBad.
XNANDPS_BLOCK_SHIFT_MASK
Block shift mask for a Bad Block Table entry byte.
XNandPs_BbtBlockShift
This macro returns the Block shift value corresponding to a Block.
Block is the block number. Block shift value None.
Referenced by XNandPs_IsBlockBad, XNandPs_MarkBlockBad.
int XNandPs_IsBlockBad(XNandPs *InstancePtr, u32 Block)
This function checks whether a block is bad or not.
InstancePtr is the pointer to the XNandPs instance. Block is the block number. XST_SUCCESS if successful.XST_FAILURE if fail.
References XNandPsTag::Bbt, XNandPsTag::IsReady, XNANDPS_BBT_BLOCK_SHIFT, XNandPs_BbtBlockShift, XNANDPS_BLOCK_GOOD, XNANDPS_BLOCK_TYPE_MASK.
Referenced by NandReadWriteCacheExample, NandReadWriteExample, XNandPs_CalculateLength, XNandPs_SkipErase, XNandPs_SkipRead, XNandPs_SkipWrite.
int XNandPs_MarkBlockBad(XNandPs *InstancePtr, u32 Block)
This function marks a block as bad in the RAM based Bad Block Table(BBT).
It also updates the Bad Block Table(BBT) in the flash. InstancePtr is the pointer to the XNandPs instance. Block is the block number. XST_SUCCESS if successful.XST_FAILURE if fail.
References XNandPsTag::Bbt, XNandPsTag::IsReady, XNANDPS_BBT_BLOCK_SHIFT, XNandPs_BbtBlockShift, XNANDPS_BLOCK_BAD, XNANDPS_BLOCK_TYPE_MASK.