xnandps_onfi.c
XNandPs_CommandFormat OnfiCommands[][]
This structure defines the onfi command format sent to the flash.
ONFI commands.
static void Onfi_ReadData(XNandPs *InstancePtr, u8 *Buf, u32 Length)
This function reads the data from flash.
It is used for reading the control information from flash like ID and Parameter page. InstancePtr is a pointer to the XNandPs instance. Buf is the buffer pointer to read the data. Length is the length of data to read. None None
static void Onfi_CmdReset(XNandPs *InstancePtr)
This function sends reset command to the flash device.
InstancePtr is a pointer to the XNandPs instance. None None
static void Onfi_CmdReadId(XNandPs *InstancePtr, u8 Address)
This function sends read ID command to the flash device.
InstancePtr is a pointer to the XNandPs instance. None None
static void Onfi_CmdReadParamPage(XNandPs *InstancePtr)
This function sends read parameter page command to the flash device.
InstancePtr is a pointer to the XNandPs instance. None None
static unsigned long Onfi_Crc16(u8 *Buf)
This function calculates the CRC on the parameter page buffer.
This is taken from the ONFI 1.0 specification. Buf is the parameter page buffer. CRC value calculated. None
static int Onfi_ReadParamPage(XNandPs *InstancePtr, u8 *Buf)
This function reads the NAND flash parameter page defined by ONFI 1.0 specification.
InstancePtr is a pointer to the XNandPs instance. Buf is a buffer pointer to fill the data. XST_SUCCESS if parameter page read successfully.XST_FAILURE if parameter page is not read successfully. None
void XNandPs_SendCommand(XNandPs *InstancePtr, XNandPs_CommandFormat *Command, int Page, int Column)
This function sends a NAND command to the flash device.
InstancePtr is the pointer to XNandPs structure Command is the NAND command to send Page is the page offset required for specific commands Column the column offset required for specific commands None None
References XNandPs_CommandFormat::AddrCycles, XNandPs_Geometry::ColAddrCycles, XNandPsTag::CommandPhaseAddr, XNandPsTag::Config, XNandPsTag::DataPhaseAddr, XNandPs_CommandFormat::EndCmd, XNandPs_CommandFormat::EndCmdValid, XNandPs_Config::FlashBase, XNandPs_Geometry::FlashWidth, XNandPsTag::Geometry, ONFI_CMD_BLOCK_ERASE1, ONFI_CMD_PAGE_PROG1, ONFI_CMD_READ1, XNandPs_Geometry::RowAddrCycles, XNandPs_CommandFormat::StartCmd, XNANDPS_ADDR_CYCLES_SHIFT, XNANDPS_CLEAR_CS_SHIFT, XNANDPS_CMD_PHASE, XNANDPS_COLUMN_NOT_VALID, XNANDPS_COMMAND_PHASE_MASK, XNANDPS_DATA_PHASE, XNANDPS_DATA_PHASE_MASK, XNANDPS_ECC_LAST_SHIFT, XNANDPS_END_CMD_SHIFT, XNANDPS_END_CMD_VALID_SHIFT, XNANDPS_FLASH_WIDTH_16, XNANDPS_PAGE_NOT_VALID, XNANDPS_START_CMD_SHIFT, XNandPs_WriteReg.
Referenced by Onfi_CmdReadStatus, XNandPs_EraseBlock, XNandPs_Read, XNandPs_ReadCache, XNandPs_ReadSpareBytes, XNandPs_Write, XNandPs_WriteCache, XNandPs_WriteSpareBytes.
static void Onfi_WriteData(XNandPs *InstancePtr, u8 *Buf, u32 Length)
This function writes command data to flash.
It is used for writing the control information like set features. InstancePtr is a pointer to the XNandPs instance. Buf is the buffer pointer to write the data. Length is the length of data to write. None None
u8 Onfi_CmdReadStatus(XNandPs *InstancePtr)
This function sends read status command to the flash device.
InstancePtr is a pointer to the XNandPs instance. flash status value read None
References XNandPsTag::Config, XNandPsTag::DataPhaseAddr, XNandPs_Config::FlashWidth, READ_STATUS, XNANDPS_COLUMN_NOT_VALID, XNANDPS_FLASH_WIDTH_16, XNANDPS_PAGE_NOT_VALID, XNandPs_SendCommand.
Referenced by XNandPs_EraseBlock, XNandPs_ReadCache, XNandPs_ReadSpareBytes, XNandPs_Write, XNandPs_WriteCache, XNandPs_WriteSpareBytes.
static void Onfi_GetFeature(XNandPs *InstancePtr, u8 Feature, u8 *Val)
This function sends Get Feature command to the flash device.
InstancePtr is a pointer to the XNandPs instance. Feature is the feature value to read. None None
static void Onfi_SetFeature(XNandPs *InstancePtr, u8 Feature, u8 *Val)
This function sends Set Feature command to the flash device.
InstancePtr is a pointer to the XNandPs instance. Feature is the feature value to Set. None None
int Onfi_NandInit(XNandPs *InstancePtr)
This function initializes the NAND flash and gets the geometry information.
InstancePtr is a pointer to the XNandPs instance. XST_SUCCESS if successful.XST_FAILURE if failed. None
References OnfiNand_Geometry::AddrCycles, XNandPs_CommandFormat::AddrCycles, BLOCK_ERASE, XNandPs_Geometry::BlockSize, OnfiNand_Geometry::BlocksPerLun, XNandPs_Geometry::BlocksPerLun, OnfiNand_Geometry::BytesPerPage, XNandPs_Geometry::BytesPerPage, CHANGE_READ_COLUMN, CHANGE_WRITE_COLUMN, XNandPs_Geometry::ColAddrCycles, XNandPs_Geometry::DeviceSize, XNandPsTag::EccMode, OnfiNand_Geometry::Features, XNandPsTag::Features, XNandPs_Geometry::FlashWidth, XNandPsTag::Geometry, XNandPs_Geometry::NumBlocks, XNandPs_Geometry::NumLun, OnfiNand_Geometry::NumLuns, XNandPs_Geometry::NumPages, ONFI_ID_LEN, OnfiNand_Geometry::OptionalCmds, PAGE_PROGRAM, OnfiNand_Geometry::PagesPerBlock, XNandPs_Geometry::PagesPerBlock, READ, XNandPs_Geometry::RowAddrCycles, OnfiNand_Geometry::SpareBytesPerPage, XNandPs_Geometry::SpareBytesPerPage, XNANDPS_ECC_HW, XNANDPS_ECC_NONE, XNANDPS_ECC_ONDIE, XNANDPS_FLASH_WIDTH_16, XNANDPS_FLASH_WIDTH_8, XNANDPS_MAX_BLOCKS, XNANDPS_MAX_LUNS, XNANDPS_MAX_PAGE_SIZE, XNANDPS_MAX_PAGES_PER_BLOCK, XNANDPS_MAX_SPARE_SIZE, XNANDPS_MAX_TARGETS.
Referenced by XNandPs_CfgInitialize.