wdtps
XWDTPS_ZMR_OFFSET
Zero Mode Register.
Referenced by XWdtPs_DisableOutput, XWdtPs_EnableOutput, XWdtPs_SelfTest, XWdtPs_Start, XWdtPs_Stop.
XWDTPS_CCR_OFFSET
Counter Control Register.
Referenced by XWdtPs_GetControlValue, XWdtPs_SetControlValue.
XWDTPS_RESTART_OFFSET
Restart Register.
XWDTPS_SR_OFFSET
Status Register.
XWDTPS_ZMR_WDEN_MASK
enable the WDT
Referenced by XWdtPs_Start, XWdtPs_Stop.
XWDTPS_ZMR_RSTEN_MASK
enable the reset output
Referenced by XWdtPs_DisableOutput, XWdtPs_EnableOutput.
XWDTPS_ZMR_IRQEN_MASK
enable the IRQ output
Referenced by XWdtPs_DisableOutput, XWdtPs_EnableOutput.
XWDTPS_ZMR_RSTLN_MASK
set length of reset pulse
Referenced by XWdtPs_SelfTest.
XWDTPS_ZMR_RSTLN_SHIFT
shift for reset pulse
XWDTPS_ZMR_IRQLN_MASK
set length of interrupt pulse
XWDTPS_ZMR_IRQLN_SHIFT
shift for interrupt pulse
XWDTPS_ZMR_ZKEY_MASK
mask for writing access key
XWDTPS_ZMR_ZKEY_VAL
access key, 0xABC << 12
Referenced by XWdtPs_DisableOutput, XWdtPs_EnableOutput, XWdtPs_SelfTest, XWdtPs_Start, XWdtPs_Stop.
XWDTPS_CCR_CLKSEL_MASK
counter clock prescale
Referenced by XWdtPs_GetControlValue, XWdtPs_SetControlValue.
XWDTPS_CCR_CRV_MASK
counter reset value
Referenced by XWdtPs_GetControlValue, XWdtPs_SetControlValue.
XWDTPS_CCR_CRV_SHIFT
shift for writing value
Referenced by XWdtPs_GetControlValue, XWdtPs_SetControlValue.
XWDTPS_CCR_CKEY_MASK
mask for writing access key
XWDTPS_CCR_CKEY_VAL
access key, 0x248 << 14
Referenced by XWdtPs_SetControlValue.
XWDTPS_CCR_PSCALE_0008
divide clock by 8
Referenced by WdtPsIntrExample, WdtPsPolledExample.
XWDTPS_CCR_PSCALE_0064
divide clock by 64
XWDTPS_CCR_PSCALE_0512
divide clock by 512
XWDTPS_CCR_PSCALE_4096
divide clock by 4096
XWDTPS_RESTART_KEY_VAL
valid key
XWDTPS_SR_WDZ_MASK
time out occurred
XWdtPs_Config XWdtPs_ConfigTable[][]
Configuration table.
Configuration table.
Referenced by XWdtPs_LookupConfig.
XWdtPs_Config XWdtPs_ConfigTable[XPAR_XWDTPS_NUM_INSTANCES][XPAR_XWDTPS_NUM_INSTANCES]
This table contains configuration information for each watchdog timer device in the system.
Configuration table.
Referenced by XWdtPs_LookupConfig.
s32 XWdtPs_CfgInitialize(XWdtPs *InstancePtr, XWdtPs_Config *ConfigPtr, UINTPTR EffectiveAddress)
Initialize a specific watchdog timer instance/driver.
This function must be called before other functions of the driver are called. InstancePtr is a pointer to the XWdtPs instance. ConfigPtr is the config structure. EffectiveAddress is the base address for the device. It could be a virtual address if address translation is supported in the system, otherwise it is the physical address. XST_SUCCESS if initialization was successful.XST_DEVICE_IS_STARTED if the device has already been started. None.
References XWdtPs_Config::BaseAddress, XWdtPs::Config, XWdtPs::IsReady, XWdtPs::IsStarted.
Referenced by WdtPsIntrExample, WdtPsPolledExample, WdtPsSelfTestExample.
void XWdtPs_Start(XWdtPs *InstancePtr)
Start the watchdog timer of the device.
InstancePtr is a pointer to the XWdtPs instance. None. None.
References XWdtPs_Config::BaseAddress, XWdtPs::Config, XWdtPs::IsReady, XWdtPs::IsStarted, XWdtPs_ReadReg, XWdtPs_WriteReg, XWDTPS_ZMR_OFFSET, XWDTPS_ZMR_WDEN_MASK, XWDTPS_ZMR_ZKEY_VAL.
Referenced by WdtPsIntrExample, WdtPsPolledExample.
void XWdtPs_Stop(XWdtPs *InstancePtr)
Disable the watchdog timer.
It is the caller's responsibility to disconnect the interrupt handler of the watchdog timer from the interrupt source, typically an interrupt controller, and disable the interrupt in the interrupt controller. InstancePtr is a pointer to the XWdtPs instance. None. None.
References XWdtPs_Config::BaseAddress, XWdtPs::Config, XWdtPs::IsReady, XWdtPs::IsStarted, XWdtPs_ReadReg, XWdtPs_WriteReg, XWDTPS_ZMR_OFFSET, XWDTPS_ZMR_WDEN_MASK, XWDTPS_ZMR_ZKEY_VAL.
Referenced by WdtPsIntrExample.
void XWdtPs_EnableOutput(XWdtPs *InstancePtr, u8 Signal)
Enables the indicated signal/output.
Performs a read/modify/write cycle to update the value correctly. InstancePtr is a pointer to the XWdtPs instance. Signal is the desired signal/output. Valid Signal Values are XWDTPS_RESET_SIGNAL and XWDTPS_IRQ_SIGNAL. Only one of them can be specified at a time. None. None.
References XWdtPs_Config::BaseAddress, XWdtPs::Config, XWdtPs::IsReady, XWDTPS_IRQ_SIGNAL, XWdtPs_ReadReg, XWDTPS_RESET_SIGNAL, XWdtPs_WriteReg, XWDTPS_ZMR_IRQEN_MASK, XWDTPS_ZMR_OFFSET, XWDTPS_ZMR_RSTEN_MASK, XWDTPS_ZMR_ZKEY_VAL.
Referenced by WdtPsIntrExample.
void XWdtPs_DisableOutput(XWdtPs *InstancePtr, u8 Signal)
Disables the indicated signal/output.
Performs a read/modify/write cycle to update the value correctly. InstancePtr is a pointer to the XWdtPs instance. Signal is the desired signal/output. Valid Signal Values are XWDTPS_RESET_SIGNAL and XWDTPS_IRQ_SIGNAL Only one of them can be specified at a time. None. None.
References XWdtPs_Config::BaseAddress, XWdtPs::Config, XWdtPs::IsReady, XWDTPS_IRQ_SIGNAL, XWdtPs_ReadReg, XWDTPS_RESET_SIGNAL, XWdtPs_WriteReg, XWDTPS_ZMR_IRQEN_MASK, XWDTPS_ZMR_OFFSET, XWDTPS_ZMR_RSTEN_MASK, XWDTPS_ZMR_ZKEY_VAL.
Referenced by WdtPsIntrExample, WdtPsPolledExample.
u32 XWdtPs_GetControlValue(XWdtPs *InstancePtr, u8 Control)
Returns the current control setting for the indicated signal/output.
The register referenced is the Counter Control Register (XWDTPS_CCR_OFFSET) InstancePtr is a pointer to the XWdtPs instance. Control is the desired signal/output. Valid Control Values are XWDTPS_CLK_PRESCALE and XWDTPS_COUNTER_RESET. Only one of them can be specified at a time. The contents of the requested control field in the Counter Control Register (XWDTPS_CCR_OFFSET). If the Control is XWDTPS_CLK_PRESCALE then use the definitions XWDTEPB_CCR_PSCALE_XXXX. If the Control is XWDTPS_COUNTER_RESET then the values are 0x0 to 0xFFF. This is the Counter Restart value in the CCR register. None.
References XWdtPs_Config::BaseAddress, XWdtPs::Config, XWdtPs::IsReady, XWDTPS_CCR_CLKSEL_MASK, XWDTPS_CCR_CRV_MASK, XWDTPS_CCR_CRV_SHIFT, XWDTPS_CCR_OFFSET, XWDTPS_CLK_PRESCALE, XWDTPS_COUNTER_RESET, XWdtPs_ReadReg.
void XWdtPs_SetControlValue(XWdtPs *InstancePtr, u8 Control, u32 Value)
Updates the current control setting for the indicated signal/output with the provided value.
Performs a read/modify/write cycle to update the value correctly. The register referenced is the Counter Control Register (XWDTPS_CCR_OFFSET) InstancePtr is a pointer to the XWdtPs instance. Control is the desired signal/output. Valid Control Values are XWDTPS_CLK_PRESCALE and XWDTPS_COUNTER_RESET. Only one of them can be specified at a time. Value is the desired control value. If the Control is XWDTPS_CLK_PRESCALE then use the definitions XWDTEPB_CCR_PSCALE_XXXX. If the Control is XWDTPS_COUNTER_RESET then the valid values are 0x0 to 0xFFF, this sets the counter restart value of the CCR register. None. None.
References XWdtPs_Config::BaseAddress, XWdtPs::Config, XWdtPs::IsReady, XWDTPS_CCR_CKEY_VAL, XWDTPS_CCR_CLKSEL_MASK, XWDTPS_CCR_CRV_MASK, XWDTPS_CCR_CRV_SHIFT, XWDTPS_CCR_OFFSET, XWDTPS_CLK_PRESCALE, XWDTPS_COUNTER_RESET, XWdtPs_ReadReg, XWdtPs_WriteReg.
Referenced by WdtPsIntrExample, WdtPsPolledExample.
XWdtPs_Config * XWdtPs_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XWdtPs_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xwdtps.h for the definition of XWdtPs_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XWdtPs_Config::Name, XWdtPs_ConfigTable.
Referenced by WdtPsIntrExample, WdtPsPolledExample, WdtPsSelfTestExample.
s32 XWdtPs_SelfTest(XWdtPs *InstancePtr)
Run a self-test on the timebase.
This test verifies that the register access locking functions. This is tested by trying to alter a register without setting the key value and verifying that the register contents did not change. InstancePtr is a pointer to the XWdtPs instance. XST_SUCCESS if self-test was successful.XST_FAILURE if self-test was not successful. None.
References XWdtPs_Config::BaseAddress, XWdtPs::Config, XWdtPs::IsReady, XWdtPs_ReadReg, XWdtPs_WriteReg, XWDTPS_ZMR_OFFSET, XWDTPS_ZMR_RSTLN_MASK, XWDTPS_ZMR_ZKEY_VAL.
Referenced by WdtPsIntrExample, WdtPsSelfTestExample.
XWDTPS_H
by using protection macros
XWDTPS_RESET_SIGNAL
Reset signal request.
Referenced by WdtPsIntrExample, WdtPsPolledExample, XWdtPs_DisableOutput, XWdtPs_EnableOutput.
XWDTPS_IRQ_SIGNAL
IRQ signal request.
Referenced by WdtPsIntrExample, XWdtPs_DisableOutput, XWdtPs_EnableOutput.
XWDTPS_CLK_PRESCALE
Clock Prescale request.
Referenced by WdtPsIntrExample, WdtPsPolledExample, XWdtPs_GetControlValue, XWdtPs_SetControlValue.
XWDTPS_COUNTER_RESET
Counter Reset request.
Referenced by WdtPsIntrExample, WdtPsPolledExample, XWdtPs_GetControlValue, XWdtPs_SetControlValue.
XWdtPs_IsWdtExpired
Check if the watchdog timer has expired.
This function is used for polled mode and it is also used to check if the last reset was caused by the watchdog timer. InstancePtr is a pointer to the XWdtPs instance. TRUE if the watchdog has expired.FALSE if the watchdog has not expired. C-style signature: int XWdtPs_IsWdtExpired(XWdtPs *InstancePtr)
Referenced by WdtPsIntrExample, WdtPsPolledExample.
XWdtPs_RestartWdt
Restart the watchdog timer.
An application needs to call this function periodically to keep the timer from asserting the enabled output. InstancePtr is a pointer to the XWdtPs instance. None. C-style signature: void XWdtPs_RestartWdt(XWdtPs *InstancePtr)
Referenced by WdtPsIntrExample, WdtPsPolledExample.
XWDTPS_HW_H
by using protection macros
XWdtPs_ReadReg
Read the given register.
BaseAddress is the base address of the device RegOffset is the register offset to be read The 32-bit value of the register C-style signature: u32 XWdtPs_ReadReg(UINTPTR BaseAddress, u32 RegOffset)
Referenced by XWdtPs_DisableOutput, XWdtPs_EnableOutput, XWdtPs_GetControlValue, XWdtPs_SelfTest, XWdtPs_SetControlValue, XWdtPs_Start, XWdtPs_Stop.
XWdtPs_WriteReg
Write the given register.
BaseAddress is the base address of the device RegOffset is the register offset to be written Data is the 32-bit value to write to the register None. C-style signature: void XWdtPs_WriteReg(UINTPTR BaseAddress, u32 RegOffset, u32 Data)
Referenced by XWdtPs_DisableOutput, XWdtPs_EnableOutput, XWdtPs_SelfTest, XWdtPs_SetControlValue, XWdtPs_Start, XWdtPs_Stop.