usb
XUSB_EP_DIRECTION_IN
Endpoint direction IN.
Referenced by InitUsbInterface.
XUSB_EP_DIRECTION_OUT
Endpoint direction OUT.
Referenced by InitUsbInterface, SetConfiguration.
XUSB_EP_HIGH_SPEED
High Speed.
Referenced by Ep1IntrHandler, GetDescriptor, main, Read10, ReadTransfer, Write10, WriteTransfer, XUsb_IntrHandler.
XUSB_EP_FULL_SPEED
Full Speed.
Referenced by XUsb_CfgInitialize, XUsb_IntrHandler.
XUSB_MAX_ENDPOINTS
Maximum End Points.
Referenced by XUsb_CfgInitialize, XUsb_EpConfigure, XUsb_EpDataRecv, XUsb_EpDataSend, XUsb_EpDisable, XUsb_EpEnable, XUsb_EpIsoTransferConfigure, XUsb_EpStall, XUsb_EpUnstall.
XUSB_EP_NUMBER_ZERO
End point Zero.
Referenced by XUsb_IntrHandler.
XUSB_DEVICEADDR_MAX
Max device address.
Referenced by XUsb_SetDeviceAddress.
XUSB_DISCONNECTED
Disconnected state.
Referenced by DmaIntrHandler, ProcessRxCmd, Read10, Write10.
XUSB_RESET
Reset State.
Referenced by InitUsbInterface, UsbIfIntrHandler.
TEST_J
Chirp J Test.
Referenced by EP0ProcessInToken, XUsb_SetTestMode.
TEST_K
Chirp K Test.
Referenced by XUsb_SetTestMode.
TEST_SE0_NAK
Chirp SE0 Test.
Referenced by XUsb_SetTestMode.
TEST_PKT
Packet Test.
Referenced by XUsb_SetTestMode.
XUSB_EP0_CONFIG_OFFSET
EP0 Config Reg Offset.
Referenced by XUsb_CfgInitialize.
XUSB_EP1_CONFIG_OFFSET
EP1 Config Reg Offset.
XUSB_SETUP_PKT_ADDR_OFFSET
Setup Packet Address.
Referenced by Chapter9.
XUSB_EP0_RAMBASE_OFFSET
EP0 RAM buffer Register.
XUSB_ADDRESS_OFFSET
Address Register.
Referenced by XUsb_SetDeviceAddress.
XUSB_CONTROL_OFFSET
Control Register.
Referenced by XUsb_SieReset, XUsb_Start, XUsb_Stop.
XUSB_STATUS_OFFSET
Status Register.
Referenced by Ep2IntrHandler, main, XUsb_IntrHandler.
XUSB_FRAMENUM_OFFSET
Frame Number Register.
Referenced by XUsb_GetFrameNum.
XUSB_IER_OFFSET
Interrupt Enable Reg.
Referenced by XUsb_IntrDisable, XUsb_IntrEnable, XUsb_IntrHandler.
XUSB_BUFFREADY_OFFSET
Buffer Ready Register.
Referenced by Ep0IntrHandler, EP0ProcessInToken, EP0ProcessOutToken, GetConfiguration, GetInterface, GetMaxLUN, GetStatus, InitUsbInterface, LoadEP0, SetConfiguration, SetupControlWriteStatusStage, XUsb_EpConfigure, XUsb_EpDataRecv, XUsb_EpDataSend.
XUSB_TESTMODE_OFFSET
Test Mode Register.
Referenced by XUsb_SetTestMode.
XUSB_ECR_OFFSET
USB Error Count Reg.
Referenced by XUsb_ReadErrorCounters.
XUSB_UPAR_OFFSET
USB ULPI PHY Access Reg.
Referenced by XUsb_UlpiPhyReadRegister, XUsb_UlpiPhyWriteRegister.
XUSB_DMA_RESET_OFFSET
DMA Soft Reset Register.
Referenced by XUsb_DmaReset.
XUSB_DMA_CONTROL_OFFSET
DMA Control Register.
Referenced by XUsb_EpDataRecv, XUsb_EpDataSend.
XUSB_DMA_DSAR_ADDR_OFFSET
DMA source Address Reg.
Referenced by XUsb_DmaTransfer.
XUSB_DMA_DSAR_ADDR_OFFSET_LSB
DMA source Address Reg for LSB.
Referenced by XUsb_DmaTransfer.
XUSB_DMA_DSAR_ADDR_OFFSET_MSB
DMA source Address Reg for MSB.
Referenced by XUsb_DmaTransfer.
XUSB_DMA_DDAR_ADDR_OFFSET
DMA destination Addr Reg.
Referenced by XUsb_DmaTransfer.
XUSB_DMA_DDAR_ADDR_OFFSET_LSB
DMA destination Addr Reg LSB.
Referenced by XUsb_DmaTransfer.
XUSB_DMA_DDAR_ADDR_OFFSET_MSB
DMA destination Addr Reg MSB.
Referenced by XUsb_DmaTransfer.
XUSB_DMA_LENGTH_OFFSET
DMA Length Register.
Referenced by XUsb_DmaTransfer.
XUSB_DMA_STATUS_OFFSET
DMA Status Register.
Referenced by Ep1IntrHandler, Ep2IntrHandler, main, ProcessRxCmd, Read10, Write10.
XUSB_ADDRESS_ADDR_MASK
Address Mask.
XUSB_CONTROL_USB_READY_MASK
USB ready Mask.
Referenced by XUsb_Start, XUsb_Stop.
XUSB_REMOTE_WAKEUP_MASK
Remote Wakeup Mask.
XUSB_CONTROL_SIE_RESET_MASK
Soft Reset Mask.
Referenced by XUsb_SieReset.
XUSB_STATUS_GLOBAL_INTR_MASK
Global Intr Enable.
Referenced by main, UsbKbdExample, UsbMouseExample.
XUSB_STATUS_PHY_ACCESS_MASK
PHY access complete.
Referenced by main, UsbIfPhyIntrHandler, XUsb_IntrHandler.
XUSB_STATUS_BITSTUFF_ERR_MASK
USB Bit stuff error.
XUSB_STATUS_PID_ERR_MASK
USB PID error.
XUSB_STATUS_CRC_ERR_MASK
USB CRC error.
XUSB_STATUS_DMA_DONE_MASK
DMA done.
Referenced by DmaIntrHandler.
XUSB_STATUS_DMA_ERROR_MASK
DMA error.
Referenced by DmaIntrHandler.
XUSB_STATUS_RESUME_MASK
USB resume Mask.
XUSB_STATUS_RESET_MASK
USB Reset Mask.
Referenced by Ep0IntrHandler, main, UsbIfIntrHandler, UsbKbdExample, UsbMouseExample.
XUSB_STATUS_SUSPEND_MASK
USB Suspend Mask.
Referenced by Ep0IntrHandler, main, UsbIfIntrHandler, UsbKbdExample, UsbMouseExample.
XUSB_STATUS_DISCONNECT_MASK
USB Disconnect Mask.
Referenced by Ep0IntrHandler, main, UsbIfIntrHandler, UsbKbdExample, UsbMouseExample.
XUSB_STATUS_FIFO_BUFF_RDY_MASK
FIFO Buff Ready Mask.
Referenced by Ep0IntrHandler, main, UsbKbdExample, UsbMouseExample.
XUSB_STATUS_FIFO_BUFF_FREE_MASK
FIFO Buff Free Mask.
Referenced by Ep0IntrHandler, main, UsbKbdExample, UsbMouseExample.
XUSB_STATUS_SETUP_PACKET_MASK
Setup packet received.
Referenced by Ep0IntrHandler.
XUSB_STATUS_SOF_PACKET_MASK
SOF packet received.
XUSB_STATUS_HIGH_SPEED_MASK
USB Speed Mask.
Referenced by XUsb_IntrHandler.
XUSB_STATUS_EP7_BUFF2_COMP_MASK
EP 7 Buff 2 Processed.
XUSB_STATUS_EP6_BUFF2_COMP_MASK
EP 6 Buff 2 Processed.
XUSB_STATUS_EP5_BUFF2_COMP_MASK
EP 5 Buff 2 Processed.
XUSB_STATUS_EP4_BUFF2_COMP_MASK
EP 4 Buff 2 Processed.
XUSB_STATUS_EP3_BUFF2_COMP_MASK
EP 3 Buff 2 Processed.
XUSB_STATUS_EP2_BUFF2_COMP_MASK
EP 2 Buff 2 Processed.
Referenced by main.
XUSB_STATUS_EP1_BUFF2_COMP_MASK
EP 1 Buff 2 Processed.
Referenced by main, UsbKbdExample, UsbMouseExample, XUsb_IntrHandler.
XUSB_STATUS_EP7_BUFF1_COMP_MASK
EP 7 Buff 1 Processed.
XUSB_STATUS_EP6_BUFF1_COMP_MASK
EP 6 Buff 1 Processed.
XUSB_STATUS_EP5_BUFF1_COMP_MASK
EP 5 Buff 1 Processed.
XUSB_STATUS_EP4_BUFF1_COMP_MASK
EP 4 Buff 1 Processed.
XUSB_STATUS_EP3_BUFF1_COMP_MASK
EP 3 Buff 1 Processed.
XUSB_STATUS_EP2_BUFF1_COMP_MASK
EP 2 Buff 1 Processed.
Referenced by main.
XUSB_STATUS_EP1_BUFF1_COMP_MASK
EP 1 Buff 1 Processed.
Referenced by main, UsbKbdExample, UsbMouseExample, XUsb_IntrHandler.
XUSB_STATUS_EP0_BUFF1_COMP_MASK
EP 0 Buff 1 Processed.
Referenced by main, UsbKbdExample, UsbMouseExample, XUsb_IntrHandler.
XUSB_STATUS_EP_BUFF2_SHIFT
EP buffer offset.
Referenced by InitUsbInterface, SetConfiguration, XUsb_EpConfigure, XUsb_EpDataRecv, XUsb_EpDataSend.
XUSB_FRAMENUM_FRAME_MASK
Frame Number Mask.
XUSB_FRAMENUM_MICRO_FRAME_MASK
Micro Frame Mask.
XUSB_FRAMENUM_FRAME_SHIFT
Frame Number Shift.
XUSB_BUFFREADY_EP7_BUFF2_MASK
EP 7 Buff 2 Ready.
XUSB_BUFFREADY_EP6_BUFF2_MASK
EP 6 Buff 2 Ready.
XUSB_BUFFREADY_EP5_BUFF2_MASK
EP 5 Buff 2 Ready.
XUSB_BUFFREADY_EP4_BUFF2_MASK
EP 4 Buff 2 Ready.
XUSB_BUFFREADY_EP3_BUFF2_MASK
EP 3 Buff 2 Ready.
XUSB_BUFFREADY_EP2_BUFF2_MASK
EP 2 Buff 2 Ready.
Referenced by Ep2IntrHandler.
XUSB_BUFFREADY_EP1_BUFF2_MASK
EP 1 Buff 2 Ready.
Referenced by Ep1IntrHandler.
XUSB_BUFFREADY_EP7_BUFF1_MASK
EP 7 Buff 1 Ready.
XUSB_BUFFREADY_EP6_BUFF1_MASK
EP 6 Buff 1 Ready.
XUSB_BUFFREADY_EP5_BUFF1_MASK
EP 5 Buff 1 Ready.
XUSB_BUFFREADY_EP4_BUFF1_MASK
EP 4 Buff 1 Ready.
XUSB_BUFFREADY_EP3_BUFF1_MASK
EP 3 Buff 1 Ready.
XUSB_BUFFREADY_EP2_BUFF1_MASK
EP 2 Buff 1 Ready.
Referenced by Ep2IntrHandler.
XUSB_BUFFREADY_EP1_BUFF1_MASK
EP 1 Buff 1 Ready.
Referenced by Ep1IntrHandler.
XUSB_BUFFREADY_EP0_BUFF_MASK
EP 0 Buffer Ready.
Referenced by Ep0IntrHandler.
XUSB_STATUS_INTR_EVENT_MASK
XUSB_STATUS_INTR_BUFF_COMP_ALL_MASK
XUSB_STATUS_DMA_EVENT_MASK
XUSB_STATUS_ERROR_EVENT_MASK
XUSB_STATUS_INTR_ALL_MASK
All Interrupts Mask.
Referenced by XUsb_IntrDisable, XUsb_IntrEnable.
XUSB_TESTMODE_J_MASK
Test Mode J.
XUSB_TESTMODE_K_MASK
Test Mode K.
XUSB_TESTMODE_SE0_NAK_MASK
Test Mode SE0 NAK.
XUSB_TESTMODE_TEST_PKT_MASK
Test Packet Mode.
XUSB_ECR_BITSTUFF_ERRCNT_MASK
Bit Stuff error counter.
Referenced by XUsb_ReadErrorCounters.
XUSB_ECR_PID_ERRCNT_MASK
PID error counter.
Referenced by XUsb_ReadErrorCounters.
XUSB_ECR_CRC_ERRCNT_MASK
CRC error counter.
Referenced by XUsb_ReadErrorCounters.
XUSB_ECR_BITSTUFF_ERRCNT_SHIFT
XUSB_ECR_PID_ERRCNT_SHIFT
XUSB_ECR_CRC_ERRCNT_SHIFT
XUSB_UPAR_REG_DATA_MASK
PHY Data register.
Referenced by XUsb_UlpiPhyReadRegister.
XUSB_UPAR_REG_ADDR_MASK
PHY Address register.
XUSB_UPAR_READ_WRITE_MASK
PHY Read/Write Transaction selection bit.
Referenced by XUsb_UlpiPhyWriteRegister.
XUSB_UPAR_BUSY_MASK
PHY access enable.
Referenced by XUsb_UlpiPhyReadRegister, XUsb_UlpiPhyWriteRegister.
XUSB_UPAR_REG_DATA_SHIFT
XUSB_EP_CFGSTATUS_OFFSET
Endpoint Config Status.
XUSB_EP_BUF0COUNT_OFFSET
Buffer 0 Count.
Referenced by EP0ProcessInToken, EP0ProcessOutToken, Ep1IntrHandler, GetConfiguration, GetInterface, GetMaxLUN, GetStatus, LoadEP0, SetupControlWriteStatusStage, XUsb_EpConfigure, XUsb_EpDataSend.
XUSB_EP_BUF1COUNT_OFFSET
Buffer 1 Count.
Referenced by Ep1IntrHandler, XUsb_EpConfigure, XUsb_EpDataSend.
XUSB_EP_CFG_VALID_MASK
Endpoint Valid bit.
Referenced by XUsb_EpDisable, XUsb_EpEnable.
XUSB_EP_CFG_STALL_MASK
Endpoint Stall bit.
Referenced by GetStatus, XUsb_EpStall, XUsb_EpUnstall.
XUSB_EP_CFG_OUT_IN_MASK
Endpoint OUT/IN cfg.
XUSB_EP_CFG_ISO_MASK
Endpoint ISO config.
XUSB_EP_CFG_DATA_TOGGLE_MASK
Endpoint Data toggle.
Referenced by Ep0IntrHandler, EP0ProcessInToken, SetClearFeature, SetupControlWriteStatusStage.
XUSB_EP_CFG_BUF_SELECT_MASK
Endpoint Buff Select.
XUSB_EP_CFG_PACKET_SIZE_MASK
Endpoint Packet Size.
XUBS_EP_CFG_ISOTRANS_MASK
Isochronous Transfer.
XUSB_EP_CFG_BASE_MASK
Endpoint Base Mask.
XUSB_EP_CFG_VALID_SHIFT
Endpoint Valid bit Shift.
XUSB_EP_CFG_STALL_SHIFT
Endpoint Stall bit Shift.
Referenced by GetStatus.
XUSB_EP_CFG_OUT_IN_SHIFT
Endpoint OUT/IN config.
Referenced by XUsb_EpConfigure.
XUSB_EP_CFG_ISO_SHIFT
Endpoint ISO config Shft.
Referenced by XUsb_EpConfigure.
XUSB_EP_CFG_DATA_TOGGLE_SHIFT
Endpoint Data toggle.
XUSB_EP_CFG_BUF_SELECT_SHIFT
Endpoint Buf Select Shft.
XUSB_EP_CFG_PACKET_SIZE_SHIFT
Endpoint Pkt Size Shift.
Referenced by XUsb_EpConfigure.
XUSB_EP_CFG_ISOTRANS_SHIFT
Endpoint Isotrans Shift.
Referenced by XUsb_EpIsoTransferConfigure.
XUSB_DMA_RESET_VALUE
DMA Reset value.
Referenced by XUsb_DmaReset.
XUSB_DMA_WRITE_TO_DPRAM
DPRAM is the destination address for DMA transfer.
XUSB_DMA_READ_FROM_DPRAM
DPRAM is the source address for DMA transfer.
Referenced by XUsb_EpDataRecv.
XUSB_DMA_DMASR_BUSY
DMA busy.
Referenced by Ep1IntrHandler, Ep2IntrHandler, main, ProcessRxCmd, Read10, Write10.
XUSB_DMA_DMASR_ERROR
DMA Error.
XUSB_DMA_DMACR_DIR_MASK
DMA direction.
XUSB_HSIC_CONTROL_REGISTER
HSIC Control Register.
XUSB_HSIC_STATUS_REGISTER
HSIC Status Register.
XUSB_HSIC_STROBE_REGISTER
HSIC Strobe Register.
XUSB_HSIC_DATA_REGISTER
HSIC Data Register.
XUSB_HSIC_CR_SOFTRESET_MASK
PHY Soft reset mask.
XUSB_HSIC_CR_CONNECT_MASK
PHY issues connect mask.
XUSB_HSIC_CR_REMOTEWKP_ENABLE_MASK
Enable Remote Wake-up signal forwarding to HSIC.
XUSB_HSIC_SR_LINKSTATUS_MASK
Link Status.
XUSB_HSIC_SR_VBUSSTATE_MASK
VBUS State.
XUSB_HSIC_SR_CONNECT_MASK
Connect signaling issued from device to host.
XUSB_HSIC_SR_CDERR_MASK
Carrier Detect Error.
XUSB_HSIC_SR_FRAMEERR_MASK
Frame decoding Error.
XUSB_HSIC_SR_TXFIFO_UNDERRUN_MASK
PHY Transmit FIFO underrun mask.
XUSB_HSIC_SR_ELFIFO_OVERRUN_MASK
Elasticity FIFO overrun mask.
XUSB_HSIC_STROBE_IDELAY_MASK
IDELAY value for HSIC strobe input for receive.
XUSB_HSIC_STROBE_READY_MASK
IDELAY block ready mask.
XUSB_HSIC_DATA_IDELAY_MASK
IDELAY value for HSIC data input for receive.
XUSB_HSIC_DATA_READY_MASK
IDELAY block ready mask.
typedef void(* XUsb_EpHandlerFunc)(void *CallBackRef, u8 EpNum, u32 EventType))(void *CallBackRef, u8 EpNum, u32 EventType)
This data type defines the callback function to be used for Endpoint handlers.
CallBackRef is the Callback reference passed in by the upper layer when setting the handler, and is passed back to the upper layer when the handler is called. EpNum is the endpoint that caused the event. EventType is the type of the event that occurred on that endpoint.
typedef void(* XUsb_IntrHandlerFunc)(void *CallBackRef, u32 InterruptType))(void *CallBackRef, u32 InterruptType)
This data type defines the callback function to be used for the general interrupt handler.
CallBackRef is the Callback reference passed in by the upper layer when setting the handler, and is passed back to the upper layer when the handler is called. InterruptType is the type of the event that caused the interrupt.
XUsb_Config XUsb_ConfigTable[XPAR_XUSB_NUM_INSTANCES][XPAR_XUSB_NUM_INSTANCES]
This table contains the configuration information for each of the USB devices in the system.
XUsb_Config XUsb_ConfigTable[][]
This table contains the configuration information for each of the USB devices in the system.
static void StubHandler(void)
This routine is a stub for the asynchronous callbacks.
The stub is here in case the upper layer forgot to set the handler. On initialization, all handlers are set to this callback. It is considered an error for this handler to be invoked. None. None. None.
int XUsb_CfgInitialize(XUsb *InstancePtr, XUsb_Config *ConfigPtr, UINTPTR EffectiveAddr)
This function initializes a XUsb instance/driver.
Setup / Initialize and DMA functions.The initialization entails: Initialize all members of the XUsb structure. InstancePtr is a pointer to the XUsb instance of the USB device. ConfigPtr is a pointer to a XUsb_Config configuration structure. This structure will contain the requested configuration for the device. Typically, this is a local structure and the content of which will be copied into the configuration structure within XUsb. EffectiveAddr is the device base address in the virtual memory address space. If the address translation is not used then the physical address is passed. Unexpected errors may occur if the address mapping is changed after this function is invoked. XST_SUCCESS no errors occurred.XST_FAILURE an error occurred during initialization. After calling XUsb_CfgInitialize() the USB device IS NOT READY for use. Before the USB device can be used its parameters must be configured. See xusb.h for details. Implemented in the file xusb.c
References XUsb_Config::AddrWidth, XUsb_Config::BaseAddress, XUsb::Config, XUsb_DeviceConfig::CurrentSpeed, XUsb::DeviceConfig, XUsb_Config::DmaEnabled, XUsb::EndPointOffset, XUsb::HandlerFunc, XUsb::IsReady, XUsb_DeviceConfig::NumEndpoints, XUSB_EP0_CONFIG_OFFSET, XUSB_EP_FULL_SPEED, XUSB_MAX_ENDPOINTS.
Referenced by main, UsbKbdExample, UsbMouseExample.
int XUsb_ConfigureDevice(XUsb *InstancePtr, XUsb_DeviceConfig *CfgPtr)
This function initializes USB End points.
InstancePtr is a pointer to the XUsb instance. CfgPtr is pointer to a XUsb_Config configuration structure. This structure will contain the requested configuration for the device. Typically, this is a local structure and the content of which will be copied into the configuration structure within XUsb. XST_SUCCESS no errors occurred.XST_FAILURE an error occurred during initialization. None.
References XUsb_EpConfig::Buffer0Count, XUsb_EpConfig::Buffer0Ready, XUsb_EpConfig::Buffer1Count, XUsb_EpConfig::Buffer1Ready, XUsb_EpConfig::CurBufNum, XUsb::DeviceConfig, XUsb_DeviceConfig::Ep, XUsb_EpConfig::EpType, XUsb_DeviceConfig::NumEndpoints, XUsb_EpConfig::OutIn, XUsb_EpConfig::RamBase, XUsb_EpConfig::Size, XUsb_EpConfigure.
Referenced by InitUsbInterface.
void XUsb_Start(XUsb *InstancePtr)
This function starts the USB Device.
InstancePtr is a pointer to the XUsb instance. None. None.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb::IsReady, XUSB_CONTROL_OFFSET, XUSB_CONTROL_USB_READY_MASK, XUsb_WriteReg.
Referenced by main, UsbIfIntrHandler, UsbKbdExample, UsbMouseExample, XUsb_SetTestMode.
void XUsb_Stop(XUsb *InstancePtr)
This function stops the USB device.
InstancePtr is a pointer to the XUsb instance. None. None.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb::IsReady, XUSB_CONTROL_OFFSET, XUSB_CONTROL_USB_READY_MASK, XUsb_ReadReg, XUsb_WriteReg.
Referenced by UsbIfIntrHandler, XUsb_SetTestMode.
u32 XUsb_GetFrameNum(const XUsb *InstancePtr)
This function returns the current frame number.
InstancePtr is a pointer to the XUsb instance. The current frame number.. None.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb::IsReady, XUSB_FRAMENUM_OFFSET, XUsb_ReadReg.
int XUsb_SetDeviceAddress(XUsb *InstancePtr, u8 Address)
This function sets the USB device address.
InstancePtr is a pointer to the XUsb instance. Address is the device address to be set. XST_SUCCESS: Address set successfully.XST_INVALID_PARAM: Invalid parameter passed. None.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb::IsReady, XUSB_ADDRESS_OFFSET, XUSB_DEVICEADDR_MAX, XUsb_WriteReg.
Referenced by EP0ProcessInToken, main, UsbIfIntrHandler, UsbKbdExample, UsbMouseExample.
void XUsb_SetTestMode(XUsb *InstancePtr, u8 TestMode, u8 *BufPtr)
This function sets the USB device into a given test mode.
InstancePtr is a pointer to the XUsb instance. TestMode is the type of test to be performed. BufPtr is a pointer to the buffer containing the test packet. None. If the test mode is Test packet(TEST_PKT), then user needs to pass the address of the buffer containing the test packet. In other cases, the BufPtr parameter is not used and the user can send a NULL or any value. BufPtr parameter should be 32 bit aligned.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb::IsReady, TEST_J, TEST_K, TEST_PKT, TEST_SE0_NAK, XUsb_Start, XUsb_Stop, XUSB_TESTMODE_OFFSET, XUsb_WriteReg.
Referenced by EP0ProcessInToken.
void XUsb_DmaReset(XUsb *InstancePtr)
This function resets the DMA module of the USB device.
InstancePtr is a pointer to the XUsb instance. None. After the DMA reset, only the DMA related logic part of the USB device will be reset and all the DMA related registers will be reset to the default values. Upon DMA Reset, any DMA transfer in progress will be stopped.
References XUsb_Config::BaseAddress, XUsb::Config, XUSB_DMA_RESET_OFFSET, XUSB_DMA_RESET_VALUE, XUsb_WriteReg.
void XUsb_DmaTransfer(XUsb *InstancePtr, UINTPTR *SrcAddr, UINTPTR *DstAddr, u16 Length)
This function sets the DMA registers with the given values to initiate a DMA data transfer.
This function is called by the XUsb_EpDataSend and XUsb_EpDataRecv functions. InstancePtr is a pointer to the XUsb instance. SrcAddr is the source address from where the data is to be read. DstAddr is the destination address to where the data is to be written. Length is the amount of data that can be transferred. The maximum data transfer can be 1024. None. This function doesn't guarantee that the transfer is done successfully. This function only initiates the DMA transfer.
References XUsb_Config::AddrWidth, XUsb_Config::BaseAddress, XUsb::Config, XUSB_DMA_DDAR_ADDR_OFFSET, XUSB_DMA_DDAR_ADDR_OFFSET_LSB, XUSB_DMA_DDAR_ADDR_OFFSET_MSB, XUSB_DMA_DSAR_ADDR_OFFSET, XUSB_DMA_DSAR_ADDR_OFFSET_LSB, XUSB_DMA_DSAR_ADDR_OFFSET_MSB, XUSB_DMA_LENGTH_OFFSET, XUsb_WriteReg.
Referenced by XUsb_EpDataRecv, XUsb_EpDataSend.
void XUsb_ReadErrorCounters(XUsb *InstancePtr, u8 *BitStuffErrors, u8 *PidErrors, u8 *CrcErrors)
This function reads the USB error counter register and returns the error counters information.
InstancePtr is a pointer to the XUsb instance. BitStuffErrors is a pointer to the 8 bit bitstuff error counter. PidErrors is a pointer to the 8 bit pid error counter. CrcErrors is a pointer to the 8 bit crc error counter. None. None.
References XUsb_Config::BaseAddress, XUsb::Config, XUSB_ECR_BITSTUFF_ERRCNT_MASK, XUSB_ECR_CRC_ERRCNT_MASK, XUSB_ECR_OFFSET, XUSB_ECR_PID_ERRCNT_MASK, XUsb_ReadReg.
u8 XUsb_UlpiPhyReadRegister(XUsb *InstancePtr, u8 RegAddr)
This function initiates the USB ULPI PHY register read transaction.
This function returns the busy status if the earlier transaction is still in progress and returns the PHY register data upon successful read transaction. InstancePtr is a pointer to the XUsb instance. RegAddr is the address of the PHY register. Register dataXST_DEVICE_BUSY: The previous PHY transaction is still in progress. This function waits till the BUSY bit is cleared in the ULPI PHY resgiter and then reads the register. The user of this API should note that the PHY interrupt should be ignored during read operation.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb_ReadReg, XUSB_UPAR_BUSY_MASK, XUSB_UPAR_OFFSET, XUSB_UPAR_REG_DATA_MASK, XUsb_WriteReg.
Referenced by main.
int XUsb_UlpiPhyWriteRegister(XUsb *InstancePtr, u8 RegAddr, u8 UlpiPhyRegData)
This function initiates the USB ULPI PHY register write transaction.
This function returns the busy status if the earlier transaction is still in progress and returns a success upon successful write transaction initiation. InstancePtr is a pointer to the XUsb instance. RegAddr is the address of the PHY register. counter. UlpiPhyRegData is the data to be written to PHY register. XST_SUCCESS: Read transaction initiated successfully.XST_DEVICE_BUSY: The previous PHY transaction is still in progress. None.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb_ReadReg, XUSB_UPAR_BUSY_MASK, XUSB_UPAR_OFFSET, XUSB_UPAR_READ_WRITE_MASK, XUsb_WriteReg.
Referenced by main.
void XUsb_SieReset(XUsb *InstancePtr)
This function resets the Serial Interface Engine.
InstancePtr is a pointer to the XUsb instance. None. After the SIE reset, only the SIE state machine logic part of the USB device will be reset and starts from Init state.
References XUsb_Config::BaseAddress, XUsb::Config, XUSB_CONTROL_OFFSET, XUSB_CONTROL_SIE_RESET_MASK, XUsb_ReadReg, XUsb_WriteReg.
void XUsb_EpEnable(const XUsb *InstancePtr, u8 EpNum)
This function enables the specified endpoint for all operations.
InstancePtr is a pointer to the XUsb instance. EpNum is the endpoint number which has to be enabled for operations. None. None.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb::EndPointOffset, XUsb::IsReady, XUSB_EP_CFG_VALID_MASK, XUSB_MAX_ENDPOINTS, XUsb_ReadReg, XUsb_WriteReg.
Referenced by InitUsbInterface.
void XUsb_EpDisable(const XUsb *InstancePtr, u8 EpNum)
This function disables the specified endpoint for all operations.
InstancePtr is a pointer to the XUsb instance. EpNum is the endpoint number which has to be disabled for operations. None. None.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb::EndPointOffset, XUsb::IsReady, XUSB_EP_CFG_VALID_MASK, XUSB_MAX_ENDPOINTS, XUsb_ReadReg, XUsb_WriteReg.
void XUsb_EpConfigure(XUsb *InstancePtr, u8 EpNum, XUsb_EpConfig *EpCfgPtr)
This function configures a specific end point with the given configuration data.
InstancePtr is a pointer to the XUsb instance. EpNum is the endpoint number which has to be configured. EpCfgPtr is a pointer to the endpoint configuration structure. None. None.
References XUsb_Config::BaseAddress, XUsb_EpConfig::Buffer0Count, XUsb_EpConfig::Buffer0Ready, XUsb_EpConfig::Buffer1Count, XUsb_EpConfig::Buffer1Ready, XUsb::Config, XUsb::EndPointOffset, XUsb_EpConfig::EpType, XUsb_EpConfig::OutIn, XUsb_EpConfig::RamBase, XUsb_EpConfig::Size, XUSB_BUFFREADY_OFFSET, XUSB_EP_BUF0COUNT_OFFSET, XUSB_EP_BUF1COUNT_OFFSET, XUSB_EP_CFG_ISO_SHIFT, XUSB_EP_CFG_OUT_IN_SHIFT, XUSB_EP_CFG_PACKET_SIZE_SHIFT, XUSB_MAX_ENDPOINTS, XUSB_STATUS_EP_BUFF2_SHIFT, XUsb_WriteReg.
Referenced by XUsb_ConfigureDevice.
int XUsb_EpDataSend(XUsb *InstancePtr, u8 EpNum, u8 *BufferPtr, u32 BufferLen)
This function copies the transmit data to the end point buffer and enables the buffer for transmission.
InstancePtr is a pointer to the XUsb instance. EpNum is the endpoint number. BufferPtr is a pointer to buffer containing the data to be sent. BufferLen is the number of data bytes to be sent. XST_SUCCESS if successful.XST_FAILURE if the send operation could not be performed due to non availability of the ping pong buffers in the DPRAM. Success doesn't imply that the data is actually transmitted, it only confirms that the DPRAM buffer is updated with send data and the core is enabled for transmitting the data.
References XUsb_Config::BaseAddress, XUsb_EpConfig::Buffer0Ready, XUsb_EpConfig::Buffer1Ready, XUsb::Config, XUsb_EpConfig::CurBufNum, XUsb::DeviceConfig, XUsb_Config::DmaEnabled, XUsb::EndPointOffset, XUsb_DeviceConfig::Ep, XUsb::IsReady, XUSB_BUFFREADY_OFFSET, XUSB_DMA_BRR_CTRL, XUSB_DMA_CONTROL_OFFSET, XUsb_DmaTransfer, XUSB_EP_BUF0COUNT_OFFSET, XUSB_EP_BUF1COUNT_OFFSET, XUSB_MAX_ENDPOINTS, XUSB_STATUS_EP_BUFF2_SHIFT, XUsb_WriteReg.
Referenced by DmaIntrHandler, Ep1IntrHandler, Ep2IntrHandler, GpioIsr, main, ProcessRxCmd, Read10, ReadTransfer, WriteTransfer.
int XUsb_EpDataRecv(XUsb *InstancePtr, u8 EpNum, u8 *BufferPtr, u32 BufferLen)
This function copies the received data from end point buffer to the buffer passed and then makes the device ready for receiving data again into the same end point buffer.
InstancePtr is a pointer to the XUsb instance. EpNum is the endpoint number. BufferPtr is a pointer to buffer where data is to be copied. BufferLen is the number of data bytes to be received. XST_SUCCESS if successful.XST_FAILURE if there is no received data in any of the ping pong buffers. None
References XUsb_Config::BaseAddress, XUsb_EpConfig::Buffer0Ready, XUsb_EpConfig::Buffer1Ready, XUsb::Config, XUsb_EpConfig::CurBufNum, XUsb::DeviceConfig, XUsb_Config::DmaEnabled, XUsb_DeviceConfig::Ep, XUsb::IsReady, XUSB_BUFFREADY_OFFSET, XUSB_DMA_BRR_CTRL, XUSB_DMA_CONTROL_OFFSET, XUSB_DMA_READ_FROM_DPRAM, XUsb_DmaTransfer, XUSB_MAX_ENDPOINTS, XUSB_STATUS_EP_BUFF2_SHIFT, XUsb_WriteReg.
Referenced by Ep2IntrHandler, main, Write10, WriteTransfer.
void XUsb_EpStall(const XUsb *InstancePtr, u8 EpNum)
This function stalls operations for the specified endpoint.
InstancePtr is a pointer to the XUsb instance. EpNum is the endpoint number which has to be stalled for operations. None. This function does not guaranty the Stall operation, it only sets the Stall bit in the Endpoint configuration register.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb::EndPointOffset, XUsb::IsReady, XUSB_EP_CFG_STALL_MASK, XUSB_MAX_ENDPOINTS, XUsb_ReadReg, XUsb_WriteReg.
Referenced by Ep0IntrHandler, ExecuteCommand, GetDescriptor, GetInterface, GetStatus, SetClearFeature, SetConfiguration, SetDescriptor, SetInterface.
void XUsb_EpUnstall(const XUsb *InstancePtr, u8 EpNum)
This function unstalls operations for the specified endpoint.
InstancePtr is a pointer to the XUsb instance. EpNum is the endpoint number for which the unstall operations are to be carried out. None. This function does not guaranty the Stall operation, it only sets the Stall bit in the Endpoint configuration register.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb::EndPointOffset, XUsb::IsReady, XUSB_EP_CFG_STALL_MASK, XUSB_MAX_ENDPOINTS, XUsb_ReadReg, XUsb_WriteReg.
Referenced by SetClearFeature.
void XUsb_EpIsoTransferConfigure(XUsb *InstancePtr, u8 EpNum, u8 NoOfTransfers)
This function sets the number of isochronous transfers in a microframe for a given endpoint.
InstancePtr is a pointer to the XUsb instance. EpNum is the endpoint number. NoOfTransfers is the number of transfers in a microframe. None The values allowed for number of transfers is 1, 2 and 3. This function should be called after all the endpoints are configured. The allowed value for EpNum is 1 to 7
References XUsb_Config::BaseAddress, XUsb::Config, XUsb::EndPointOffset, XUsb::IsReady, XUSB_EP_CFG_ISOTRANS_SHIFT, XUSB_MAX_ENDPOINTS, XUsb_ReadReg, XUsb_WriteReg.
void XUsb_IntrEnable(XUsb *InstancePtr, u32 Mask)
This function enables the specified interrupts.
InstancePtr is a pointer to the XUsb instance. Mask is the bit-mask of the interrupts to be enabled. Bit positions of 1 will be enabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XUSB_STATUS_*_MASK bits defined in xusb_l.h. None. None.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb::IsReady, XUSB_IER_OFFSET, XUsb_ReadReg, XUSB_STATUS_INTR_ALL_MASK, XUsb_WriteReg.
Referenced by Ep0IntrHandler, main, UsbIfIntrHandler, UsbKbdExample, UsbMouseExample.
void XUsb_IntrDisable(XUsb *InstancePtr, u32 Mask)
This function disables the specified interrupts.
InstancePtr is a pointer to the XUsb instance. Mask is the bit-mask of the interrupts to be disabled. Bit positions of 1 will be enabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XUSB_STATUS_*_MASK bits defined in xusb_l.h. None. None.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb::IsReady, XUSB_IER_OFFSET, XUsb_ReadReg, XUSB_STATUS_INTR_ALL_MASK, XUsb_WriteReg.
Referenced by UsbIfIntrHandler.
void XUsb_IntrHandler(void *InstancePtr)
This function is the interrupt handler for the USB driver.
This function is the first-level interrupt handler for the USB core. All USB interrupts will be handled here. Depending on the type of the interrupt, second level interrupt handler may be called. Second level interrupt handlers will be registered by the user using the XUsb_IntrSetHandler() and/or XUsb_EpSetHandler() functions.This handler reads the interrupt status from the Interrupt Status Register, determines the source of the interrupts, calls the corresponding callbacks and finally clears the interrupts.The interrupt from the USB driver has to be connected to the interrupt controller and the handler has to be registered with the interrupt system.Applications using this driver are responsible for providing the callbacks to handle interrupts and installing the callbacks using XUsb_SetHandler() during the initialization phase. InstancePtr is a pointer to the XUsb instance that just interrupted. None. No user handler is defined for the DMA interrupts. The DMA interrupt status is updated in the DMA status variables defined under the USB driver instance.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb_DeviceConfig::CurrentSpeed, XUsb::DeviceConfig, XUsb_Config::DmaEnabled, XUsb_DeviceConfig::Ep, XUsb_EpConfig::HandlerFunc, XUsb::HandlerFunc, XUsb_EpConfig::HandlerRef, XUsb_DeviceConfig::NumEndpoints, XUSB_EP_FULL_SPEED, XUSB_EP_HIGH_SPEED, XUSB_EP_NUMBER_ZERO, XUSB_IER_OFFSET, XUsb_ReadReg, XUSB_STATUS_EP0_BUFF1_COMP_MASK, XUSB_STATUS_EP1_BUFF1_COMP_MASK, XUSB_STATUS_EP1_BUFF2_COMP_MASK, XUSB_STATUS_HIGH_SPEED_MASK, XUSB_STATUS_OFFSET, XUSB_STATUS_PHY_ACCESS_MASK.
Referenced by main, UsbKbdExample, UsbMouseExample.
void XUsb_IntrSetHandler(XUsb *InstancePtr, void *CallBackFunc, void *CallBackRef)
This function installs an asynchronous callback function for the general interrupt (interrupts other than the endpoint and error interrupts).
InstancePtr is a pointer to the XUsb instance. CallBackFunc is the address of the callback function. CallBackRef is a user data item that will be passed to the callback function when it is invoked. None. Invoking this function for a handler that already has been installed replaces it with the new handler. The user can disable a handler by setting the callback function pointer to NULL.
References XUsb::HandlerFunc, XUsb::IsReady.
Referenced by main, UsbKbdExample, UsbMouseExample.
void XUsb_EpSetHandler(XUsb *InstancePtr, u8 EpNum, XUsb_EpHandlerFunc *CallBackFunc, void *CallBackRef)
This function sets the handler for endpoint events.
InstancePtr is a Pointer to the XUsb instance. EpNum is the Number of the endpoint. CallBackFunc is the address of the callback function. It can be NULL if the user wants to disable the handler entry. CallBackRef is a user data item that will be passed to the callback function when it is invoked. This can be NULL. None. Invoking this function for a handler that already has been installed replaces it with the new handler. The user can disable a handler by setting the callback function pointer to NULL.
References XUsb::DeviceConfig, XUsb_DeviceConfig::Ep, XUsb_EpConfig::HandlerFunc, XUsb_EpConfig::HandlerRef.
Referenced by main, UsbKbdExample, UsbMouseExample.
void XUsb_ErrIntrSetHandler(XUsb *InstancePtr, void *CallBackFunc, void *CallBackRef)
This function installs an asynchronous callback function for the error events.
InstancePtr is a pointer to the XUsb instance. CallBackFunc is the address of the callback function. CallBackRef is a user data item that will be passed to the callback function when it is invoked. None. Invoking this function for a handler that already has been installed replaces it with the new handler. The user can disable a handler by setting the callback function pointer to NULL.
References XUsb::IsReady.
void XUsb_DmaIntrSetHandler(XUsb *InstancePtr, void *CallBackFunc, void *CallBackRef)
This function installs an asynchronous callback function for the DMA events.
InstancePtr is a pointer to the XUsb instance. CallBackFunc is the address of the callback function. CallBackRef is a user data item that will be passed to the callback function when it is invoked. None. Invoking this function for a handler that already has been installed replaces it with the new handler. The user can disable a handler by setting the callback function pointer to NULL.
References XUsb::IsReady.
Referenced by main.
void XUsb_UlpiIntrSetHandler(XUsb *InstancePtr, void *CallBackFunc, void *CallBackRef)
This function installs an asynchronous callback function for the ULPI PHY events.
InstancePtr is a pointer to the XUsb instance. CallBackFunc is the address of the callback function. CallBackRef is a user data item that will be passed to the callback function when it is invoked. None. Invoking this function for a handler that already has been installed replaces it with the new handler. The user can disable a handler by setting the callback function pointer to NULL.
References XUsb::IsReady.
Referenced by main.
XUsb_Config * XUsb_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
A table contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found.NULL if the specified device ID/BaseAddress was not found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
Referenced by main, UsbKbdExample, UsbMouseExample.
XUSB_L_H
XUSB_DMA_BRR_CTRL
DMA bufready ctrl bit.
Referenced by XUsb_EpDataRecv, XUsb_EpDataSend.
XUsb_In32
XUsb_Out32
XUsb_ReadReg
Read from the specified USB device register.
BaseAddress contains the base address of the device. RegOffset contains the offset from the 1st register of the device to select the specific register. The value read from the register. C-Style signature: u32 XUsb_ReadReg(UINTPTR BaseAddress, u32 RegOffset);
Referenced by Ep0IntrHandler, EP0ProcessInToken, EP0ProcessOutToken, Ep1IntrHandler, Ep2IntrHandler, GetStatus, main, ProcessRxCmd, Read10, SetClearFeature, SetupControlWriteStatusStage, Write10, XUsb_EpDisable, XUsb_EpEnable, XUsb_EpIsoTransferConfigure, XUsb_EpStall, XUsb_EpUnstall, XUsb_GetFrameNum, XUsb_IntrDisable, XUsb_IntrEnable, XUsb_IntrHandler, XUsb_ReadErrorCounters, XUsb_SieReset, XUsb_Stop, XUsb_UlpiPhyReadRegister, XUsb_UlpiPhyWriteRegister.
XUsb_WriteReg
Write to the specified USB device register.
BaseAddress contains the base address of the device. RegOffset contains the offset from the 1st register of the device to select the specific register. RegisterValue is the value to be written to the register. None. C-Style signature: void XUsb_WriteReg(UINTPTR BaseAddress, u32 RegOffset, u32 RegisterValue);
Referenced by Ep0IntrHandler, EP0ProcessInToken, EP0ProcessOutToken, GetConfiguration, GetInterface, GetMaxLUN, GetStatus, InitUsbInterface, LoadEP0, SetClearFeature, SetConfiguration, SetupControlWriteStatusStage, UsbIfIntrHandler, XUsb_DmaReset, XUsb_DmaTransfer, XUsb_EpConfigure, XUsb_EpDataRecv, XUsb_EpDataSend, XUsb_EpDisable, XUsb_EpEnable, XUsb_EpIsoTransferConfigure, XUsb_EpStall, XUsb_EpUnstall, XUsb_IntrDisable, XUsb_IntrEnable, XUsb_SetDeviceAddress, XUsb_SetTestMode, XUsb_SieReset, XUsb_Start, XUsb_Stop, XUsb_UlpiPhyReadRegister, XUsb_UlpiPhyWriteRegister.