xusb_keyboard.c
XGPIO_BASEADDRESS
XUSB_BASEADDRESS
GPIO_ALL_BUTTONS
EXIT_BUTTON
BUTTON_CHANNEL
BUTTON_INTERRUPT
XUsb UsbInstance
XGpio Gpio
XUsb_Config* UsbConfigPtr
XGpio_Config* GpioConfigPtr
volatile int StopTest
int MaxMsgLength
int UsbKbdExample(UINTPTR UsbBaseAddress, UINTPTR GpioBaseAddress)
This function implements the USB Keyboard example.
The Key board action can be seen on the PC as and when any of the push buttons SW3 or SW4 or SW5 or SW7 on the ML403 evaluation board is pressed. UsbBaseAddress is the base address of the USB device. GpioBaseAddress is the base address of the GPIO device. XST_SUCCESS if successful.XST_FAILURE if test fails. In XSCT/classic flow, UsbId and GpioId are used to look up the device configuration.
References XUsb_Config::BaseAddress, XUsb_DeviceConfig::CurrentConfiguration, XUsb::DeviceConfig, Ep0IntrHandler, Ep1IntrHandler, GpioIsr, InitUsbInterface, XUsb_Config::IntrId, XUsb_Config::IntrParent, UsbIfIntrHandler, XUsb_CfgInitialize, XUsb_EpSetHandler, XUsb_IntrEnable, XUsb_IntrHandler, XUsb_IntrSetHandler, XUsb_LookupConfig, XUsb_SetDeviceAddress, XUsb_Start, XUSB_STATUS_DISCONNECT_MASK, XUSB_STATUS_EP0_BUFF1_COMP_MASK, XUSB_STATUS_EP1_BUFF1_COMP_MASK, XUSB_STATUS_EP1_BUFF2_COMP_MASK, XUSB_STATUS_FIFO_BUFF_FREE_MASK, XUSB_STATUS_FIFO_BUFF_RDY_MASK, XUSB_STATUS_GLOBAL_INTR_MASK, XUSB_STATUS_RESET_MASK, XUSB_STATUS_SUSPEND_MASK.
Referenced by main.
void GpioIsr(void *InstancePtr)
This function is the Interrupt Service Routine for the GPIO device.
This function will detect the push button on the board has changed state and then prepare data to be sent to the host. InstancePtr is the GPIO component to operate on. It is a void pointer and in this case will be a pointer to the GPIO instance. None. None. This function will detect the push button on the board has changed state and then prepare data to be sent to the host upon receiving the Get InstancePtr is the GPIO component to operate on. It is a void pointer to meet the interface of an interrupt processing function. None. None.
References XUsb_EpDataSend.
Referenced by UsbKbdExample, UsbMouseExample.
int main(void)
This function is the main function of the USB Keyboard example.
None. XST_SUCCESS if successful,XST_FAILURE if unsuccessful. None.
References UsbKbdExample.
void InitUsbInterface(XUsb *InstancePtr)
This function initializes the USB device for Keyboard example.
This is the USB initialization function.The following is the configuration. EP0 : CONTROL end point, Bidirectional, Packet size 64 bytes.EP1 : NON_ISOCHRONOUS, INTERRUPT_IN, packet size of 16 bytes. InstancePtr is a pointer to the XUsb instance. None. None.
References XUsb::DeviceConfig, XUsb_DeviceConfig::Ep, XUsb_EpConfig::EpType, XUsb_DeviceConfig::NumEndpoints, XUsb_EpConfig::OutIn, XUsb_EpConfig::RamBase, XUsb_EpConfig::Size, XUsb_ConfigureDevice, XUSB_EP_DIRECTION_IN, XUSB_EP_DIRECTION_OUT, XUsb_EpEnable.
void UsbIfIntrHandler(void *CallBackRef, u32 IntrStatus)
This function is the interrupt handler for the USB keyboard example.
This function is the interrupt handler for the USB mass storage device application. CallBackRef is the callback reference passed from the interrupt handler, which in our case is a pointer to the driver instance. IntrStatus is a bit mask indicating pending interrupts. None. Each interrupt source is disabled upon reception. This is to avoid the repetitive occurrence of the same event. This is done because these event conditions exist for few milliseconds.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb_DeviceConfig::CurrentConfiguration, XUsb::DeviceConfig, InitUsbInterface, XUsb_DeviceConfig::Status, XUsb_IntrDisable, XUsb_IntrEnable, XUSB_RESET, XUsb_SetDeviceAddress, XUsb_Start, XUSB_STATUS_DISCONNECT_MASK, XUSB_STATUS_RESET_MASK, XUSB_STATUS_SUSPEND_MASK, XUsb_Stop, XUsb_WriteReg.
void Ep0IntrHandler(void *CallBackRef, u8 EpNum, u32 IntrStatus)
This function is the interrupt handler for the USB End point Zero events.
CallBackRef is the callback reference passed from the interrupt. handler, which in our case is a pointer to the driver instance. EpNum is the end point number. IntrStatus is a bit mask indicating pending interrupts. None. EpNum is not used in this function as the handler is attached specific to end point zero. This parameter is useful when a single handler is used for processing all end point interrupts.
References Chapter9, EP0ProcessInToken, EP0ProcessOutToken, XUSB_BUFFREADY_EP0_BUFF_MASK, XUsb_EpStall, XUsb_IntrEnable, XUSB_STATUS_DISCONNECT_MASK, XUSB_STATUS_FIFO_BUFF_FREE_MASK, XUSB_STATUS_FIFO_BUFF_RDY_MASK, XUSB_STATUS_RESET_MASK, XUSB_STATUS_SETUP_PACKET_MASK, XUSB_STATUS_SUSPEND_MASK.
void Ep1IntrHandler(void *CallBackRef, u8 EpNum, u32 IntrStatus)
This function is the interrupt handler for the USB End point one events.
CallBackRef is the callback reference passed from the interrupt handler, which in our case is a pointer to the driver instance. EpNum is the end point number. IntrStatus is a bit mask indicating pending interrupts. None. EpNum is not used in this function as the handler is attached specific to end point one. This parameter is useful when a single handler is used for processing all end point interrupts.
References XUsb_EpConfig::Buffer0Ready, XUsb_EpConfig::Buffer1Ready, XUsb::DeviceConfig, XUsb_DeviceConfig::Ep, XUSB_BUFFREADY_EP1_BUFF1_MASK, XUSB_BUFFREADY_EP1_BUFF2_MASK.