xusb_intr.c
void XUsb_IntrEnable(XUsb *InstancePtr, u32 Mask)
This function enables the specified interrupts.
InstancePtr is a pointer to the XUsb instance. Mask is the bit-mask of the interrupts to be enabled. Bit positions of 1 will be enabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XUSB_STATUS_*_MASK bits defined in xusb_l.h. None. None.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb::IsReady, XUSB_IER_OFFSET, XUsb_ReadReg, XUSB_STATUS_INTR_ALL_MASK, XUsb_WriteReg.
Referenced by Ep0IntrHandler, main, UsbIfIntrHandler, UsbKbdExample, UsbMouseExample.
void XUsb_IntrDisable(XUsb *InstancePtr, u32 Mask)
This function disables the specified interrupts.
InstancePtr is a pointer to the XUsb instance. Mask is the bit-mask of the interrupts to be disabled. Bit positions of 1 will be enabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XUSB_STATUS_*_MASK bits defined in xusb_l.h. None. None.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb::IsReady, XUSB_IER_OFFSET, XUsb_ReadReg, XUSB_STATUS_INTR_ALL_MASK, XUsb_WriteReg.
Referenced by UsbIfIntrHandler.
void XUsb_IntrHandler(void *InstancePtr)
This function is the interrupt handler for the USB driver.
This function is the first-level interrupt handler for the USB core. All USB interrupts will be handled here. Depending on the type of the interrupt, second level interrupt handler may be called. Second level interrupt handlers will be registered by the user using the XUsb_IntrSetHandler() and/or XUsb_EpSetHandler() functions.This handler reads the interrupt status from the Interrupt Status Register, determines the source of the interrupts, calls the corresponding callbacks and finally clears the interrupts.The interrupt from the USB driver has to be connected to the interrupt controller and the handler has to be registered with the interrupt system.Applications using this driver are responsible for providing the callbacks to handle interrupts and installing the callbacks using XUsb_SetHandler() during the initialization phase. InstancePtr is a pointer to the XUsb instance that just interrupted. None. No user handler is defined for the DMA interrupts. The DMA interrupt status is updated in the DMA status variables defined under the USB driver instance.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb_DeviceConfig::CurrentSpeed, XUsb::DeviceConfig, XUsb_Config::DmaEnabled, XUsb_DeviceConfig::Ep, XUsb_EpConfig::HandlerFunc, XUsb::HandlerFunc, XUsb_EpConfig::HandlerRef, XUsb_DeviceConfig::NumEndpoints, XUSB_EP_FULL_SPEED, XUSB_EP_HIGH_SPEED, XUSB_EP_NUMBER_ZERO, XUSB_IER_OFFSET, XUsb_ReadReg, XUSB_STATUS_EP0_BUFF1_COMP_MASK, XUSB_STATUS_EP1_BUFF1_COMP_MASK, XUSB_STATUS_EP1_BUFF2_COMP_MASK, XUSB_STATUS_HIGH_SPEED_MASK, XUSB_STATUS_OFFSET, XUSB_STATUS_PHY_ACCESS_MASK.
Referenced by main, UsbKbdExample, UsbMouseExample.
void XUsb_IntrSetHandler(XUsb *InstancePtr, void *CallBackFunc, void *CallBackRef)
This function installs an asynchronous callback function for the general interrupt (interrupts other than the endpoint and error interrupts).
InstancePtr is a pointer to the XUsb instance. CallBackFunc is the address of the callback function. CallBackRef is a user data item that will be passed to the callback function when it is invoked. None. Invoking this function for a handler that already has been installed replaces it with the new handler. The user can disable a handler by setting the callback function pointer to NULL.
References XUsb::HandlerFunc, XUsb::IsReady.
Referenced by main, UsbKbdExample, UsbMouseExample.
void XUsb_EpSetHandler(XUsb *InstancePtr, u8 EpNum, XUsb_EpHandlerFunc *CallBackFunc, void *CallBackRef)
This function sets the handler for endpoint events.
InstancePtr is a Pointer to the XUsb instance. EpNum is the Number of the endpoint. CallBackFunc is the address of the callback function. It can be NULL if the user wants to disable the handler entry. CallBackRef is a user data item that will be passed to the callback function when it is invoked. This can be NULL. None. Invoking this function for a handler that already has been installed replaces it with the new handler. The user can disable a handler by setting the callback function pointer to NULL.
References XUsb::DeviceConfig, XUsb_DeviceConfig::Ep, XUsb_EpConfig::HandlerFunc, XUsb_EpConfig::HandlerRef.
Referenced by main, UsbKbdExample, UsbMouseExample.
void XUsb_ErrIntrSetHandler(XUsb *InstancePtr, void *CallBackFunc, void *CallBackRef)
This function installs an asynchronous callback function for the error events.
InstancePtr is a pointer to the XUsb instance. CallBackFunc is the address of the callback function. CallBackRef is a user data item that will be passed to the callback function when it is invoked. None. Invoking this function for a handler that already has been installed replaces it with the new handler. The user can disable a handler by setting the callback function pointer to NULL.
References XUsb::IsReady.
void XUsb_DmaIntrSetHandler(XUsb *InstancePtr, void *CallBackFunc, void *CallBackRef)
This function installs an asynchronous callback function for the DMA events.
InstancePtr is a pointer to the XUsb instance. CallBackFunc is the address of the callback function. CallBackRef is a user data item that will be passed to the callback function when it is invoked. None. Invoking this function for a handler that already has been installed replaces it with the new handler. The user can disable a handler by setting the callback function pointer to NULL.
References XUsb::IsReady.
Referenced by main.
void XUsb_UlpiIntrSetHandler(XUsb *InstancePtr, void *CallBackFunc, void *CallBackRef)
This function installs an asynchronous callback function for the ULPI PHY events.
InstancePtr is a pointer to the XUsb instance. CallBackFunc is the address of the callback function. CallBackRef is a user data item that will be passed to the callback function when it is invoked. None. Invoking this function for a handler that already has been installed replaces it with the new handler. The user can disable a handler by setting the callback function pointer to NULL.
References XUsb::IsReady.
Referenced by main.