xusb_storage.h
RAMDISKSECTORS
RAMBLOCKS
MS_SCSI_CMD_SET
CLASS_MASS_STORAGE
MS_BULK_ONLY
SCSI_READ_10
SCSI_READ_12
SCSI_WRITE_10
SCSI_WRITE_12
SCSI_VERIFY
SCSI_INQUIRY
SCSI_READ_FORMAT_CAPACITIES
SCSI_MODE_SENSE
SCSI_READ_CAPACITY
SCSI_TEST_UNIT_READY
SCSI_REQUEST_SENSE
SCSI_MEDIA_REMOVAL
USBCSW_SIGNATURE
USBCSW_LENGTH
MODESENSE_RETURNALL
CMD_PASSED
CMD_FAILED
PHASE_ERROR
NO_ERROR
ERR_NOTERASED
ERR_NOFREEBLOCKS
ERR_USBABORT
ERR_CMDFAILED
ERR_ECC
ERR_BADBZ
ERR_DSMM
FORMATTED_CURRENT
UNFORMATTED
BLOCK_SIZE
EP_CONTROL
Control Endpoint.
EP_ISOCHRONOUS
Isochronous Endpoint.
EP_BULK
Bulk Endpoint.
EP_INTERRUPT
Interrupt Endpoint.
typedef struct SCSI_MODESENSE_CDB * PSCSI_MODESENSE_CDB
typedef struct SCSI_MEDIA_REMOVAL_TYPE * PSCSI_MEDIA_REMOVAL_TYPE
typedef struct REQUEST_SENSE * PREQUEST_SENSE
typedef struct INQUIRY * PINQUIRY
typedef struct CAPACITY_LIST * PCAPACITY_LIST
typedef struct READ_CAPACITY * PREAD_CAPACITY
typedef struct MODESENSE_MPL * PMODESENSE_MPL
typedef struct MODESENSE_RWER * PMODESENSE_RWER
typedef struct MODESENSE_FD * PMODESENSE_FD
typedef struct MODESENSE_RBAC * PMODESENSE_RBAC
typedef struct MODESENSE_TP * PMODESENSE_TP
typedef struct MODE_SENSE_REPLY_SHORT * PMODE_SENSE_REPLY_SHORT
typedef struct MODE_SENSE_REPLY_ALL * PMODE_SENSE_REPLY_ALL
typedef struct USBCBW * PUSBCBW
typedef struct USBCSW * PUSBCSW
u8 Read10Abort
u8 Write10Abort
u8 ErrCode
u16 MaxControlSize
USB_CMD_BUF Ch9_CmdBuf
IntChar UsbMemData
u32 RamDisk[RAMDISKSECTORS][RAMBLOCKS][RAMDISKSECTORS][RAMBLOCKS]
volatile u8 CharLba[4][4]
volatile u32 IntLba
union @1 Lba
volatile u8 CharBlockCount[4][4]
volatile u32 IntBlockCount
union @2 BlockCount
USBCBW CmdBlock
USBCSW CmdStatusBlock
USB_STD_DEV_DESC DeviceDescriptor
USB_STD_QUAL_DESC QualifierDescriptor
FPGA1_CONFIGURATION HsUsbConfig
FPGA1_CONFIGURATION FsUsbConfig
USB_STD_STRING_DESC LangId
USB_STD_STRING_MAN_DESC Manufacturer
USB_STD_STRING_PS_DESC ProductString
USB_STD_STRING_SN_DESC SerialNumber
REQUEST_SENSE Prss
INQUIRY Piq
CAPACITY_LIST Pcl
READ_CAPACITY Prc
PSCSI_MEDIA_REMOVAL_TYPE Pmr
MODE_SENSE_REPLY_SHORT Pmsd_s
MODE_SENSE_REPLY_ALL Pmsd_l
PSCSI_MODESENSE_CDB Pms_cdb
void InitUsbInterface(XUsb *InstancePtr)
This is the USB initialization function.
This example initializes the device for Mass Storage Application. The following configuration is done. EP0 : CONTROL end point, Bidirectional, Packet size 64 bytes.EP1 : NON_ISOCHRONOUS, BULK_IN, packet size 512 bytes.EP2 : NON_ISOCHRONOUS, BULK_OUT, packet size 512 bytes InstancePtr is a pointer to the XUsb instance. None. None. This is the USB initialization function.The following is the configuration. EP0 : CONTROL end point, Bidirectional, Packet size 64 bytes.EP1 : NON_ISOCHRONOUS, INTERRUPT_IN, packet size of 16 bytes. InstancePtr is a pointer to the XUsb instance. None. None. This example initializes the device for Microphone Application. The following configuration is done. EP0 : CONTROL end point, Bidirectional, Packet size 64 bytes.EP1 : ISOCHRONOUS, BULK_IN, packet size 1024 bytes. InstancePtr is a pointer to the XUsb instance. None. None. This example initializes the USB device for USB mouse example. The following configuration is done. EP0 : CONTROL end point, Bidirectional, Packet size 64 bytes.EP1 : NON_ISOCHRONOUS, INTERRUPT_IN, packet size of 16 bytes. InstancePtr is a pointer to the XUsb instance. None. None.
References XUsb_Config::BaseAddress, XUsb_EpConfig::Buffer0Ready, XUsb_EpConfig::Buffer1Ready, XUsb::Config, XUsb::DeviceConfig, XUsb_DeviceConfig::Ep, XUsb_EpConfig::EpType, XUsb_DeviceConfig::NumEndpoints, XUsb_EpConfig::OutIn, XUsb_EpConfig::RamBase, XUsb_EpConfig::Size, XUsb_DeviceConfig::Status, XUSB_BUFFREADY_OFFSET, XUsb_ConfigureDevice, XUSB_EP_DIRECTION_IN, XUSB_EP_DIRECTION_OUT, XUsb_EpEnable, XUSB_RESET, XUSB_STATUS_EP_BUFF2_SHIFT, XUsb_WriteReg.
void UsbIfIntrHandler(void *CallBackRef, u32 IntrStatus)
This function is the interrupt handler for the USB mass storage device application.
CallBackRef is the callback reference passed from the interrupt handler, which in our case is a pointer to the driver instance. IntrStatus is a bit mask indicating pending interrupts. None. None. This function is the interrupt handler for the USB mass storage device application. CallBackRef is the callback reference passed from the interrupt handler, which in our case is a pointer to the driver instance. IntrStatus is a bit mask indicating pending interrupts. None. Each interrupt source is disabled upon reception. This is to avoid the repetitive occurrence of the same event. This is done because these event conditions exist for few milliseconds. This function is the interrupt handler for the USB mass storage device application. CallBackRef is the callback reference passed from the interrupt handler, which in our case is a pointer to the driver instance. IntrStatus is a bit mask indicating pending interrupts. None. None. This function is the interrupt handler for the USB mass storage device application. CallBackRef is the callback reference passed from to the function, which in our case is a pointer to the driver instance. IntrStatus is a bit mask indicating pending interrupts. None. None.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb_DeviceConfig::CurrentConfiguration, XUsb::DeviceConfig, InitUsbInterface, XUsb_DeviceConfig::Status, XUsb_IntrDisable, XUsb_IntrEnable, XUSB_RESET, XUsb_SetDeviceAddress, XUsb_Start, XUSB_STATUS_DISCONNECT_MASK, XUSB_STATUS_RESET_MASK, XUSB_STATUS_SUSPEND_MASK, XUsb_Stop, XUsb_WriteReg.
Referenced by main, UsbKbdExample, UsbMouseExample.
void EpIntrHandler(void *CallBackRef, u8 EpNum, u32 IntrStatus)
void Ep0IntrHandler(void *CallBackRef, u8 EpNum, u32 IntrStatus)
This function is the interrupt handler for the USB End point Zero events.
CallBackRef is the callback reference passed from the interrupt. handler, which in our case is a pointer to the driver instance. EpNum is the end point number. IntrStatus is a bit mask indicating pending interrupts. None. EpNum is not used in this function as the handler is attached specific to end point zero. This parameter is useful when a single handler is used for processing all end point interrupts. This function is the interrupt handler for the USB End point Zero events. CallBackRef is the callback reference passed from the caller function, which in our case is a pointer to the driver instance. EpNum is the end point number. IntrStatus is a bit mask indicating pending interrupts. None. EpNum is not used in this function as the handler is attached specific to end point zero. This parameter is useful when a single handler is used for processing all end point interrupts.
References XUsb_Config::BaseAddress, Chapter9, XUsb::Config, XUsb::EndPointOffset, EP0ProcessInToken, EP0ProcessOutToken, GetMaxLUN, MassStorageReset, XUSB_BUFFREADY_EP0_BUFF_MASK, XUSB_BUFFREADY_OFFSET, XUSB_EP_CFG_DATA_TOGGLE_MASK, XUsb_EpStall, XUsb_IntrEnable, XUsb_ReadReg, XUSB_STATUS_DISCONNECT_MASK, XUSB_STATUS_FIFO_BUFF_FREE_MASK, XUSB_STATUS_FIFO_BUFF_RDY_MASK, XUSB_STATUS_RESET_MASK, XUSB_STATUS_SETUP_PACKET_MASK, XUSB_STATUS_SUSPEND_MASK, XUsb_WriteReg.
Referenced by main, UsbKbdExample, UsbMouseExample.
void Ep1IntrHandler(void *CallBackRef, u8 EpNum, u32 IntrStatus)
This function is the interrupt handler for the USB End point one events.
CallBackRef is the callback reference passed from the interrupt handler, which in our case is a pointer to the driver instance. EpNum is the end point number. IntrStatus is a bit mask indicating pending interrupts. None. EpNum is not used in this function as the handler is attached specific to end point one. This parameter is useful when a single handler is used for processing all end point interrupts. This function is the interrupt handler for the USB End point one events. CallBackRef is the callback reference passed from the caller function, which in our case is a pointer to the driver instance. IntrStatus is a bit mask indicating pending interrupts. None. EpNum is not used in this function as the handler is attached specific to end point one. This parameter is useful when a single handler is used for processing all end point interrupts.
References XUsb_Config::BaseAddress, XUsb_EpConfig::Buffer0Count, XUsb_EpConfig::Buffer0Ready, XUsb_EpConfig::Buffer1Count, XUsb_EpConfig::Buffer1Ready, XUsb::Config, XUsb_DeviceConfig::CurrentSpeed, XUsb::DeviceConfig, XUsb_Config::DmaEnabled, XUsb::EndPointOffset, XUsb_DeviceConfig::Ep, ReadTransfer, XUSB_BUFFREADY_EP1_BUFF1_MASK, XUSB_BUFFREADY_EP1_BUFF2_MASK, XUSB_DMA_DMASR_BUSY, XUSB_DMA_STATUS_OFFSET, XUSB_EP_BUF0COUNT_OFFSET, XUSB_EP_BUF1COUNT_OFFSET, XUSB_EP_HIGH_SPEED, XUsb_EpDataSend, XUsb_ReadReg.
Referenced by main, UsbKbdExample, UsbMouseExample.
void Ep2IntrHandler(void *CallBackRef, u8 EpNum, u32 IntrStatus)
This function is the interrupt handler for the USB End point two events.
CallBackRef is the callback reference passed from the interrupt handler, which in our case is a pointer to the driver instance. EpNum is the end point number. IntrStatus is a bit mask indicating pending interrupts. None. EpNum is not used in this function as the handler is attached specific to end point two. This parameter is useful when a single handler is used for processing all end point interrupts. This function is the interrupt handler for the USB End point two events. CallBackRef is the callback reference passed from the caller function, which in our case is a pointer to the driver instance. IntrStatus is a bit mask indicating pending interrupts. None. EpNum is not used in this function as the handler is attached specific to end point two. This parameter is useful when a single handler is used for processing all end point interrupts.
References XUsb_Config::BaseAddress, XUsb_EpConfig::Buffer0Ready, XUsb_EpConfig::Buffer1Ready, XUsb::Config, XUsb::DeviceConfig, XUsb_Config::DmaEnabled, XUsb_DeviceConfig::Ep, WriteTransfer, XUSB_BUFFREADY_EP2_BUFF1_MASK, XUSB_BUFFREADY_EP2_BUFF2_MASK, XUSB_DMA_DMASR_BUSY, XUSB_DMA_STATUS_OFFSET, XUsb_EpDataRecv, XUsb_EpDataSend, XUsb_ReadReg, XUSB_STATUS_OFFSET.
Referenced by main.
void ProcessRxCmd(XUsb *InstancePtr)
This function processes mass storage specific commands and sends the required response.
InstancePtr is a pointer to the XUsb instance. None. None.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb::DeviceConfig, XUsb_Config::DmaEnabled, Read10, XUsb_DeviceConfig::Status, Write10, XUSB_DISCONNECTED, XUSB_DMA_DMASR_BUSY, XUSB_DMA_STATUS_OFFSET, XUsb_EpDataSend, XUsb_ReadReg.
Referenced by DmaIntrHandler, main.
void Read10(XUsb *InstancePtr, PUSBCBW pCmdBlock, PUSBCSW pStatusBlock)
This function implements the transmission of data from the device to the READ request from the USB Host.
InstancePtr is a pointer to the XUsb instance. pCmdBlock is a pointer to the Mass Storage Command Block wrapper. pStatusBlock is a pointer to the Mass Storage Status wrapper. None. None.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb_DeviceConfig::CurrentSpeed, XUsb::DeviceConfig, XUsb_Config::DmaEnabled, XUsb_DeviceConfig::Status, XUSB_DISCONNECTED, XUSB_DMA_DMASR_BUSY, XUSB_DMA_STATUS_OFFSET, XUSB_EP_HIGH_SPEED, XUsb_EpDataSend, XUsb_ReadReg.
Referenced by ProcessRxCmd.
void Write10(XUsb *InstancePtr, PUSBCBW pCmdBlock, PUSBCSW pStatusBlock)
This function implements the reception of data in the USB device for the write request from the USB Host.
InstancePtr is a pointer to the XUsb instance. pCmdBlock is a pointer to the Mass Storage Command Block wrapper. pStatusBlock is a pointer to the Mass Storage Status wrapper. None. None.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb_DeviceConfig::CurrentSpeed, XUsb::DeviceConfig, XUsb_Config::DmaEnabled, XUsb_DeviceConfig::Status, XUSB_DISCONNECTED, XUSB_DMA_DMASR_BUSY, XUSB_DMA_STATUS_OFFSET, XUSB_EP_HIGH_SPEED, XUsb_EpDataRecv, XUsb_ReadReg.
Referenced by ProcessRxCmd.
void RequestSense(XUsb *InstancePtr, PUSBCBW pCmdBlock, PUSBCSW pStatusBlock)
void Media_Removal(PUSBCBW pCmdBlock, PUSBCSW pStatusBlock)
void ModeSense(XUsb *InstancePtr, PUSBCBW pCmdBlock, PUSBCSW pStatusBlock)
void ReadCapacity(XUsb *InstancePtr, PUSBCBW pCmdBlock, PUSBCSW pStatusBlock)
void RFC(XUsb *InstancePtr, PUSBCBW pCmdBlock, PUSBCSW pStatusBlock)
void Inquiry(XUsb *InstancePtr, PUSBCBW pCmdBlock, PUSBCSW pStatusBlock)
void MassStorageReset(XUsb *InstancePtr)
This routine is called when a RESET class command is received.
InstancePtr is a pointer to the XUsb instance of the controller. None. None.
References SetupControlWriteStatusStage.
Referenced by Ep0IntrHandler.
void GetMaxLUN(XUsb *InstancePtr)
This routine is called when a GETMAXLUN class command is received.
InstancePtr is a pointer to the XUsb instance of the controller. None. None.
References XUsb_Config::BaseAddress, XUsb_EpConfig::Buffer0Ready, XUsb::Config, XUsb::DeviceConfig, XUsb::EndPointOffset, XUsb_DeviceConfig::Ep, XUsb_EpConfig::RamBase, XUSB_BUFFREADY_OFFSET, XUSB_EP_BUF0COUNT_OFFSET, XUsb_WriteReg.
Referenced by Ep0IntrHandler.