xusb_cp9.h
void EP0ProcessOutToken(XUsb *InstancePtr)
This routine is called when an OUT transaction for Endpoint Zero is received.
InstancePtr is a pointer to the XUsb instance of the controller. None. None.
References XUsb_Config::BaseAddress, XUsb_EpConfig::Buffer0Ready, XUsb::Config, XUsb::DeviceConfig, XUsb_DeviceConfig::Ep, ExecuteCommand, XUSB_BUFFREADY_OFFSET, XUSB_EP_BUF0COUNT_OFFSET, XUsb_ReadReg, XUsb_WriteReg.
Referenced by Ep0IntrHandler.
void EP0ProcessInToken(XUsb *InstancePtr)
This routine is called when IN transaction for Endpoint Zero is received.
InstancePtr is a pointer to the XUsb instance of the controller. None. None.
References XUsb_Config::BaseAddress, XUsb_EpConfig::Buffer0Ready, XUsb::Config, XUsb::DeviceConfig, XUsb::EndPointOffset, XUsb_DeviceConfig::Ep, LoadEP0, TEST_J, XUSB_BUFFREADY_OFFSET, XUSB_EP_BUF0COUNT_OFFSET, XUSB_EP_CFG_DATA_TOGGLE_MASK, XUsb_ReadReg, XUsb_SetDeviceAddress, XUsb_SetTestMode, XUsb_WriteReg.
Referenced by Ep0IntrHandler.
int Chapter9(XUsb *InstancePtr)
This routine is called when a chapter 9 command is received.
InstancePtr is a pointer to the XUsb instance of the controller. The setup request value to be processed by the upper layer. None.
References XUsb_Config::BaseAddress, XUsb::Config, ExecuteCommand, XUSB_SETUP_PKT_ADDR_OFFSET.
Referenced by Ep0IntrHandler.
int ExecuteCommand(XUsb *InstancePtr)
This function executes the chapter 9 command processing.
InstancePtr is a pointer to the XUsb instance of the controller. The request value to be processed by the upper layer if the request is not handled. XST_SUCCESS if the request is successfully processed. None.
References GetConfiguration, GetDescriptor, GetInterface, GetStatus, SetClearFeature, SetConfiguration, SetDescriptor, SetInterface, SetupControlWriteStatusStage, XUsb_EpStall.
Referenced by Chapter9, EP0ProcessOutToken.
void GetInterface(XUsb *InstancePtr)
This function responds to the GET_INTERFACE command.
InstancePtr is a pointer to the XUsb instance of the controller. None. None.
References XUsb_Config::BaseAddress, XUsb_EpConfig::Buffer0Ready, XUsb::Config, XUsb::DeviceConfig, XUsb::EndPointOffset, XUsb_DeviceConfig::Ep, XUSB_BUFFREADY_OFFSET, XUSB_EP_BUF0COUNT_OFFSET, XUsb_EpStall, XUsb_WriteReg.
Referenced by ExecuteCommand.
void SetInterface(XUsb *InstancePtr)
This function responds to the SET_INTERFACE command.
InstancePtr is a pointer to the XUsb instance of the controller. None. None.
References SetupControlWriteStatusStage, XUsb_EpStall.
Referenced by ExecuteCommand.
void SetupControlWriteStatusStage(XUsb *InstancePtr)
This function sets the basic Control status words.
InstancePtr is a pointer to the XUsb instance of the controller. None. None.
References XUsb_Config::BaseAddress, XUsb_EpConfig::Buffer0Count, XUsb::Config, XUsb::DeviceConfig, XUsb::EndPointOffset, XUsb_DeviceConfig::Ep, XUSB_BUFFREADY_OFFSET, XUSB_EP_BUF0COUNT_OFFSET, XUSB_EP_CFG_DATA_TOGGLE_MASK, XUsb_ReadReg, XUsb_WriteReg.
Referenced by ExecuteCommand, MassStorageReset, SetClearFeature, SetConfiguration, SetInterface.
void GetStatus(XUsb *InstancePtr)
This routine is called when a GET_STATUS command is received.
InstancePtr is a pointer to the XUsb instance of the controller. None. None.
References XUsb_Config::BaseAddress, XUsb_EpConfig::Buffer0Ready, XUsb::Config, XUsb::DeviceConfig, XUsb::EndPointOffset, XUsb_DeviceConfig::Ep, XUsb_EpConfig::RamBase, XUSB_BUFFREADY_OFFSET, XUSB_EP_BUF0COUNT_OFFSET, XUSB_EP_CFG_STALL_MASK, XUSB_EP_CFG_STALL_SHIFT, XUsb_EpStall, XUsb_ReadReg, XUsb_WriteReg.
Referenced by ExecuteCommand.
void GetDescriptor(XUsb *InstancePtr)
This routine is called when a GET_DESCRIPTOR command is received.
InstancePtr is a pointer to the XUsb instance of the controller. None. None.
References XUsb_DeviceConfig::CurrentSpeed, XUsb::DeviceConfig, LoadEP0, XUSB_EP_HIGH_SPEED, XUsb_EpStall.
Referenced by ExecuteCommand.
void SetDescriptor(XUsb *InstancePtr)
This routine is called when a SET_DESCRIPTOR command is received.
InstancePtr is a pointer to the XUsb instance of the controller. None. None.
References XUsb_EpStall.
Referenced by ExecuteCommand.
void GetConfiguration(XUsb *InstancePtr)
This routine is called when a GET_CONFIGURATION command is received.
InstancePtr is a pointer to the XUsb instance of the controller. None. None.
References XUsb_Config::BaseAddress, XUsb_EpConfig::Buffer0Ready, XUsb::Config, XUsb_DeviceConfig::CurrentConfiguration, XUsb::DeviceConfig, XUsb::EndPointOffset, XUsb_DeviceConfig::Ep, XUsb_EpConfig::RamBase, XUSB_BUFFREADY_OFFSET, XUSB_EP_BUF0COUNT_OFFSET, XUsb_WriteReg.
Referenced by ExecuteCommand.
void SetConfiguration(XUsb *InstancePtr)
This routine is called when a SET_CONFIGURATION command is received.
InstancePtr is a pointer to the XUsb instance of the controller. None. None.
References XUsb_Config::BaseAddress, XUsb_EpConfig::Buffer0Ready, XUsb_EpConfig::Buffer1Ready, XUsb::Config, XUsb_DeviceConfig::CurrentConfiguration, XUsb::DeviceConfig, XUsb_DeviceConfig::Ep, InitUsbInterface, XUsb_DeviceConfig::NumEndpoints, XUsb_EpConfig::OutIn, SetupControlWriteStatusStage, XUSB_BUFFREADY_OFFSET, XUSB_EP_DIRECTION_OUT, XUsb_EpStall, XUSB_STATUS_EP_BUFF2_SHIFT, XUsb_WriteReg.
Referenced by ExecuteCommand.
void SetClearFeature(XUsb *InstancePtr, int flag)
This routine is called when a SET_FEATURE or a CLEAR_FEATURE command is received.
InstancePtr is a pointer to the XUsb instance of the controller. flag specifies whether it is a SET_FEATURE (TRUE)or a CLEAR_FEATURE (FALSE) command. None. None.
References XUsb::Config, XUsb::DeviceConfig, XUsb_DeviceConfig::Ep, XUsb_EpConfig::OutIn, SetupControlWriteStatusStage, XUSB_EP_CFG_DATA_TOGGLE_MASK, XUsb_EpStall, XUsb_EpUnstall, XUsb_ReadReg, XUsb_WriteReg.
Referenced by ExecuteCommand.
void LoadEP0(XUsb *InstancePtr)
This routine copies the EP0 related data to the DPRAM.
InstancePtr is a pointer to the XUsb instance of the controller. None. None.
References XUsb_Config::BaseAddress, XUsb_EpConfig::Buffer0Ready, XUsb::Config, XUsb::DeviceConfig, XUsb_DeviceConfig::Ep, XUsb_EpConfig::RamBase, XUSB_BUFFREADY_OFFSET, XUSB_EP_BUF0COUNT_OFFSET, XUsb_WriteReg.
Referenced by EP0ProcessInToken, GetDescriptor.
void InitUsbInterface(XUsb *InstancePtr)
This is the USB initialization function.
This example initializes the device for Mass Storage Application. The following configuration is done. EP0 : CONTROL end point, Bidirectional, Packet size 64 bytes.EP1 : NON_ISOCHRONOUS, BULK_IN, packet size 512 bytes.EP2 : NON_ISOCHRONOUS, BULK_OUT, packet size 512 bytes InstancePtr is a pointer to the XUsb instance. None. None. This is the USB initialization function.The following is the configuration. EP0 : CONTROL end point, Bidirectional, Packet size 64 bytes.EP1 : NON_ISOCHRONOUS, INTERRUPT_IN, packet size of 16 bytes. InstancePtr is a pointer to the XUsb instance. None. None. This example initializes the device for Microphone Application. The following configuration is done. EP0 : CONTROL end point, Bidirectional, Packet size 64 bytes.EP1 : ISOCHRONOUS, BULK_IN, packet size 1024 bytes. InstancePtr is a pointer to the XUsb instance. None. None. This example initializes the USB device for USB mouse example. The following configuration is done. EP0 : CONTROL end point, Bidirectional, Packet size 64 bytes.EP1 : NON_ISOCHRONOUS, INTERRUPT_IN, packet size of 16 bytes. InstancePtr is a pointer to the XUsb instance. None. None.
Referenced by main, SetConfiguration, UsbIfIntrHandler, UsbKbdExample, UsbMouseExample.