xusb_endpoint.c
void XUsb_EpEnable(const XUsb *InstancePtr, u8 EpNum)
This function enables the specified endpoint for all operations.
InstancePtr is a pointer to the XUsb instance. EpNum is the endpoint number which has to be enabled for operations. None. None.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb::EndPointOffset, XUsb::IsReady, XUSB_EP_CFG_VALID_MASK, XUSB_MAX_ENDPOINTS, XUsb_ReadReg, XUsb_WriteReg.
Referenced by InitUsbInterface.
void XUsb_EpDisable(const XUsb *InstancePtr, u8 EpNum)
This function disables the specified endpoint for all operations.
InstancePtr is a pointer to the XUsb instance. EpNum is the endpoint number which has to be disabled for operations. None. None.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb::EndPointOffset, XUsb::IsReady, XUSB_EP_CFG_VALID_MASK, XUSB_MAX_ENDPOINTS, XUsb_ReadReg, XUsb_WriteReg.
void XUsb_EpStall(const XUsb *InstancePtr, u8 EpNum)
This function stalls operations for the specified endpoint.
InstancePtr is a pointer to the XUsb instance. EpNum is the endpoint number which has to be stalled for operations. None. This function does not guaranty the Stall operation, it only sets the Stall bit in the Endpoint configuration register.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb::EndPointOffset, XUsb::IsReady, XUSB_EP_CFG_STALL_MASK, XUSB_MAX_ENDPOINTS, XUsb_ReadReg, XUsb_WriteReg.
Referenced by Ep0IntrHandler, ExecuteCommand, GetDescriptor, GetInterface, GetStatus, SetClearFeature, SetConfiguration, SetDescriptor, SetInterface.
void XUsb_EpUnstall(const XUsb *InstancePtr, u8 EpNum)
This function unstalls operations for the specified endpoint.
InstancePtr is a pointer to the XUsb instance. EpNum is the endpoint number for which the unstall operations are to be carried out. None. This function does not guaranty the Stall operation, it only sets the Stall bit in the Endpoint configuration register.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb::EndPointOffset, XUsb::IsReady, XUSB_EP_CFG_STALL_MASK, XUSB_MAX_ENDPOINTS, XUsb_ReadReg, XUsb_WriteReg.
Referenced by SetClearFeature.
void XUsb_EpConfigure(XUsb *InstancePtr, u8 EpNum, XUsb_EpConfig *EpCfgPtr)
This function configures a specific end point with the given configuration data.
InstancePtr is a pointer to the XUsb instance. EpNum is the endpoint number which has to be configured. EpCfgPtr is a pointer to the endpoint configuration structure. None. None.
References XUsb_Config::BaseAddress, XUsb_EpConfig::Buffer0Count, XUsb_EpConfig::Buffer0Ready, XUsb_EpConfig::Buffer1Count, XUsb_EpConfig::Buffer1Ready, XUsb::Config, XUsb::EndPointOffset, XUsb_EpConfig::EpType, XUsb_EpConfig::OutIn, XUsb_EpConfig::RamBase, XUsb_EpConfig::Size, XUSB_BUFFREADY_OFFSET, XUSB_EP_BUF0COUNT_OFFSET, XUSB_EP_BUF1COUNT_OFFSET, XUSB_EP_CFG_ISO_SHIFT, XUSB_EP_CFG_OUT_IN_SHIFT, XUSB_EP_CFG_PACKET_SIZE_SHIFT, XUSB_MAX_ENDPOINTS, XUSB_STATUS_EP_BUFF2_SHIFT, XUsb_WriteReg.
Referenced by XUsb_ConfigureDevice.
int XUsb_EpDataSend(XUsb *InstancePtr, u8 EpNum, u8 *BufferPtr, u32 BufferLen)
This function copies the transmit data to the end point buffer and enables the buffer for transmission.
InstancePtr is a pointer to the XUsb instance. EpNum is the endpoint number. BufferPtr is a pointer to buffer containing the data to be sent. BufferLen is the number of data bytes to be sent. XST_SUCCESS if successful.XST_FAILURE if the send operation could not be performed due to non availability of the ping pong buffers in the DPRAM. Success doesn't imply that the data is actually transmitted, it only confirms that the DPRAM buffer is updated with send data and the core is enabled for transmitting the data.
References XUsb_Config::BaseAddress, XUsb_EpConfig::Buffer0Ready, XUsb_EpConfig::Buffer1Ready, XUsb::Config, XUsb_EpConfig::CurBufNum, XUsb::DeviceConfig, XUsb_Config::DmaEnabled, XUsb::EndPointOffset, XUsb_DeviceConfig::Ep, XUsb::IsReady, XUSB_BUFFREADY_OFFSET, XUSB_DMA_BRR_CTRL, XUSB_DMA_CONTROL_OFFSET, XUsb_DmaTransfer, XUSB_EP_BUF0COUNT_OFFSET, XUSB_EP_BUF1COUNT_OFFSET, XUSB_MAX_ENDPOINTS, XUSB_STATUS_EP_BUFF2_SHIFT, XUsb_WriteReg.
Referenced by DmaIntrHandler, Ep1IntrHandler, Ep2IntrHandler, GpioIsr, main, ProcessRxCmd, Read10, ReadTransfer, WriteTransfer.
int XUsb_EpDataRecv(XUsb *InstancePtr, u8 EpNum, u8 *BufferPtr, u32 BufferLen)
This function copies the received data from end point buffer to the buffer passed and then makes the device ready for receiving data again into the same end point buffer.
InstancePtr is a pointer to the XUsb instance. EpNum is the endpoint number. BufferPtr is a pointer to buffer where data is to be copied. BufferLen is the number of data bytes to be received. XST_SUCCESS if successful.XST_FAILURE if there is no received data in any of the ping pong buffers. None
References XUsb_Config::BaseAddress, XUsb_EpConfig::Buffer0Ready, XUsb_EpConfig::Buffer1Ready, XUsb::Config, XUsb_EpConfig::CurBufNum, XUsb::DeviceConfig, XUsb_Config::DmaEnabled, XUsb_DeviceConfig::Ep, XUsb::IsReady, XUSB_BUFFREADY_OFFSET, XUSB_DMA_BRR_CTRL, XUSB_DMA_CONTROL_OFFSET, XUSB_DMA_READ_FROM_DPRAM, XUsb_DmaTransfer, XUSB_MAX_ENDPOINTS, XUSB_STATUS_EP_BUFF2_SHIFT, XUsb_WriteReg.
Referenced by Ep2IntrHandler, main, Write10, WriteTransfer.
void XUsb_EpIsoTransferConfigure(XUsb *InstancePtr, u8 EpNum, u8 NoOfTransfers)
This function sets the number of isochronous transfers in a microframe for a given endpoint.
InstancePtr is a pointer to the XUsb instance. EpNum is the endpoint number. NoOfTransfers is the number of transfers in a microframe. None The values allowed for number of transfers is 1, 2 and 3. This function should be called after all the endpoints are configured. The allowed value for EpNum is 1 to 7
References XUsb_Config::BaseAddress, XUsb::Config, XUsb::EndPointOffset, XUsb::IsReady, XUSB_EP_CFG_ISOTRANS_SHIFT, XUSB_MAX_ENDPOINTS, XUsb_ReadReg, XUsb_WriteReg.