xusb_storage_polled_mode.c
XUSB_BASEADDRESS
READ_COMMAND
WRITE_COMMAND
XUsb UsbInstance
XUsb_Config* UsbConfigPtr
volatile u8 CmdFlag
volatile u8 FirstPkt
u8* WrRamDiskPtr
u8* RdRamDiskPtr
volatile u8 RdIndex
volatile u8 WrIndex
volatile u32 IntrStatus
int main()
This main function starts the USB application.
None. XST_SUCCESS if successful.XST_FAILURE if test fails. None.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb_DeviceConfig::CurrentConfiguration, XUsb_DeviceConfig::CurrentSpeed, XUsb::DeviceConfig, XUsb_Config::DmaEnabled, Ep0IntrHandler, Ep1IntrHandler, Ep2IntrHandler, InitUsbInterface, ProcessRxCmd, UsbIfIntrHandler, XUsb_CfgInitialize, XUSB_DMA_DMASR_BUSY, XUSB_DMA_STATUS_OFFSET, XUSB_EP_HIGH_SPEED, XUsb_EpDataRecv, XUsb_LookupConfig, XUsb_ReadReg, XUsb_SetDeviceAddress, XUsb_Start, XUSB_STATUS_DISCONNECT_MASK, XUSB_STATUS_EP0_BUFF1_COMP_MASK, XUSB_STATUS_EP1_BUFF1_COMP_MASK, XUSB_STATUS_EP1_BUFF2_COMP_MASK, XUSB_STATUS_EP2_BUFF1_COMP_MASK, XUSB_STATUS_EP2_BUFF2_COMP_MASK, XUSB_STATUS_OFFSET, XUSB_STATUS_RESET_MASK.
void InitUsbInterface(XUsb *InstancePtr)
This is the USB initialization function.
This example initializes the device for Mass Storage Application. The following configuration is done. EP0 : CONTROL end point, Bidirectional, Packet size 64 bytes.EP1 : NON_ISOCHRONOUS, BULK_IN, packet size 512 bytes.EP2 : NON_ISOCHRONOUS, BULK_OUT, packet size 512 bytes InstancePtr is a pointer to the XUsb instance. None. None.
References XUsb_Config::BaseAddress, XUsb_EpConfig::Buffer0Ready, XUsb_EpConfig::Buffer1Ready, XUsb::Config, XUsb::DeviceConfig, XUsb_DeviceConfig::Ep, XUsb_EpConfig::EpType, XUsb_DeviceConfig::NumEndpoints, XUsb_EpConfig::OutIn, XUsb_EpConfig::RamBase, XUsb_EpConfig::Size, XUsb_DeviceConfig::Status, XUSB_BUFFREADY_OFFSET, XUsb_ConfigureDevice, XUSB_EP_DIRECTION_IN, XUSB_EP_DIRECTION_OUT, XUsb_EpEnable, XUSB_RESET, XUSB_STATUS_EP_BUFF2_SHIFT, XUsb_WriteReg.
Referenced by main, SetConfiguration, UsbIfIntrHandler, UsbKbdExample, UsbMouseExample.
void UsbIfIntrHandler(void *CallBackRef, u32 IntrStatus)
This function processes the reset and disconnect conditions of the USB mass storage device.
This function is the interrupt handler for the USB mass storage device application. CallBackRef is the callback reference passed from to the function, which in our case is a pointer to the driver instance. IntrStatus is a bit mask indicating pending interrupts. None. None.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb_DeviceConfig::CurrentConfiguration, XUsb::DeviceConfig, InitUsbInterface, XUsb_DeviceConfig::Status, XUsb_IntrDisable, XUsb_IntrEnable, XUSB_RESET, XUsb_SetDeviceAddress, XUsb_Start, XUSB_STATUS_DISCONNECT_MASK, XUSB_STATUS_RESET_MASK, XUSB_STATUS_SUSPEND_MASK, XUsb_Stop, XUsb_WriteReg.
void Ep0IntrHandler(void *CallBackRef, u8 EpNum, u32 IntrStatus)
This function processes the USB End point Zero events.
This function is the interrupt handler for the USB End point Zero events. CallBackRef is the callback reference passed from the caller function, which in our case is a pointer to the driver instance. EpNum is the end point number. IntrStatus is a bit mask indicating pending interrupts. None. EpNum is not used in this function as the handler is attached specific to end point zero. This parameter is useful when a single handler is used for processing all end point interrupts.
References Chapter9, EP0ProcessInToken, EP0ProcessOutToken, GetMaxLUN, MassStorageReset, XUSB_BUFFREADY_EP0_BUFF_MASK, XUsb_EpStall, XUsb_IntrEnable, XUSB_STATUS_DISCONNECT_MASK, XUSB_STATUS_FIFO_BUFF_FREE_MASK, XUSB_STATUS_FIFO_BUFF_RDY_MASK, XUSB_STATUS_RESET_MASK, XUSB_STATUS_SETUP_PACKET_MASK, XUSB_STATUS_SUSPEND_MASK.
void Ep1IntrHandler(void *CallBackRef, u8 EpNum, u32 IntrStatus)
This function processes the USB End point one events.
This function is the interrupt handler for the USB End point one events. CallBackRef is the callback reference passed from the caller function, which in our case is a pointer to the driver instance. IntrStatus is a bit mask indicating pending interrupts. None. EpNum is not used in this function as the handler is attached specific to end point one. This parameter is useful when a single handler is used for processing all end point interrupts.
References XUsb_Config::BaseAddress, XUsb_EpConfig::Buffer0Ready, XUsb_EpConfig::Buffer1Ready, XUsb::Config, XUsb::DeviceConfig, XUsb_Config::DmaEnabled, XUsb_DeviceConfig::Ep, ReadTransfer, XUSB_BUFFREADY_EP1_BUFF1_MASK, XUSB_BUFFREADY_EP1_BUFF2_MASK, XUSB_DMA_DMASR_BUSY, XUSB_DMA_STATUS_OFFSET, XUsb_EpDataSend, XUsb_ReadReg.
void Ep2IntrHandler(void *CallBackRef, u8 EpNum, u32 IntrStatus)
This function processes the USB End point two events.
This function is the interrupt handler for the USB End point two events. CallBackRef is the callback reference passed from the caller function, which in our case is a pointer to the driver instance. IntrStatus is a bit mask indicating pending interrupts. None. EpNum is not used in this function as the handler is attached specific to end point two. This parameter is useful when a single handler is used for processing all end point interrupts.
References XUsb_Config::BaseAddress, XUsb_EpConfig::Buffer0Ready, XUsb_EpConfig::Buffer1Ready, XUsb::Config, XUsb::DeviceConfig, XUsb_Config::DmaEnabled, XUsb_DeviceConfig::Ep, WriteTransfer, XUSB_BUFFREADY_EP2_BUFF1_MASK, XUSB_BUFFREADY_EP2_BUFF2_MASK, XUSB_DMA_DMASR_BUSY, XUSB_DMA_STATUS_OFFSET, XUsb_EpDataRecv, XUsb_EpDataSend, XUsb_ReadReg, XUSB_STATUS_OFFSET.
void ProcessRxCmd(XUsb *InstancePtr)
This function processes mass storage specific commands and sends the required response.
InstancePtr is a pointer to the XUsb instance. None. None.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb::DeviceConfig, XUsb_Config::DmaEnabled, Read10, XUsb_DeviceConfig::Status, Write10, XUSB_DISCONNECTED, XUSB_DMA_DMASR_BUSY, XUSB_DMA_STATUS_OFFSET, XUsb_EpDataSend, XUsb_ReadReg.
void Read10(XUsb *InstancePtr, PUSBCBW pCmdBlock, PUSBCSW pStatusBlock)
This function implements the transmission of data from the device to the READ request from the USB Host.
InstancePtr is a pointer to the XUsb instance. pCmdBlock is a pointer to the Mass Storage Command Block wrapper. pStatusBlock is a pointer to the Mass Storage Status wrapper. None. None.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb_DeviceConfig::CurrentSpeed, XUsb::DeviceConfig, XUsb_Config::DmaEnabled, XUsb_DeviceConfig::Status, XUSB_DISCONNECTED, XUSB_DMA_DMASR_BUSY, XUSB_DMA_STATUS_OFFSET, XUSB_EP_HIGH_SPEED, XUsb_EpDataSend, XUsb_ReadReg.
void Write10(XUsb *InstancePtr, PUSBCBW pCmdBlock, PUSBCSW pStatusBlock)
This function implements the reception of data in the USB device for the write request from the USB Host.
InstancePtr is a pointer to the XUsb instance. pCmdBlock is a pointer to the Mass Storage Command Block wrapper. pStatusBlock is a pointer to the Mass Storage Status wrapper. None. None.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb::DeviceConfig, XUsb_Config::DmaEnabled, XUsb_DeviceConfig::Status, XUSB_DISCONNECTED, XUSB_DMA_DMASR_BUSY, XUSB_DMA_STATUS_OFFSET, XUsb_EpDataRecv, XUsb_ReadReg.
void MassStorageReset(XUsb *InstancePtr)
This routine is called when a RESET class command is received.
InstancePtr is a pointer to the XUsb instance of the controller. None. None.
References SetupControlWriteStatusStage.
void GetMaxLUN(XUsb *InstancePtr)
This routine is called when a GETMAXLUN class command is received.
InstancePtr is a pointer to the XUsb instance of the controller. None. None.
References XUsb_Config::BaseAddress, XUsb_EpConfig::Buffer0Ready, XUsb::Config, XUsb::DeviceConfig, XUsb::EndPointOffset, XUsb_DeviceConfig::Ep, XUsb_EpConfig::RamBase, XUSB_BUFFREADY_OFFSET, XUSB_EP_BUF0COUNT_OFFSET, XUsb_WriteReg.