xusb.c
static void StubHandler(void)
This routine is a stub for the asynchronous callbacks.
The stub is here in case the upper layer forgot to set the handler. On initialization, all handlers are set to this callback. It is considered an error for this handler to be invoked. None. None. None.
int XUsb_CfgInitialize(XUsb *InstancePtr, XUsb_Config *ConfigPtr, UINTPTR EffectiveAddr)
This function initializes a XUsb instance/driver.
Setup / Initialize and DMA functions.The initialization entails: Initialize all members of the XUsb structure. InstancePtr is a pointer to the XUsb instance of the USB device. ConfigPtr is a pointer to a XUsb_Config configuration structure. This structure will contain the requested configuration for the device. Typically, this is a local structure and the content of which will be copied into the configuration structure within XUsb. EffectiveAddr is the device base address in the virtual memory address space. If the address translation is not used then the physical address is passed. Unexpected errors may occur if the address mapping is changed after this function is invoked. XST_SUCCESS no errors occurred.XST_FAILURE an error occurred during initialization. After calling XUsb_CfgInitialize() the USB device IS NOT READY for use. Before the USB device can be used its parameters must be configured. See xusb.h for details. Implemented in the file xusb.c
References XUsb_Config::AddrWidth, XUsb_Config::BaseAddress, XUsb::Config, XUsb_DeviceConfig::CurrentSpeed, XUsb::DeviceConfig, XUsb_Config::DmaEnabled, XUsb::EndPointOffset, XUsb::HandlerFunc, XUsb::IsReady, XUsb_DeviceConfig::NumEndpoints, XUSB_EP0_CONFIG_OFFSET, XUSB_EP_FULL_SPEED, XUSB_MAX_ENDPOINTS.
Referenced by main, UsbKbdExample, UsbMouseExample.
int XUsb_ConfigureDevice(XUsb *InstancePtr, XUsb_DeviceConfig *CfgPtr)
This function initializes USB End points.
InstancePtr is a pointer to the XUsb instance. CfgPtr is pointer to a XUsb_Config configuration structure. This structure will contain the requested configuration for the device. Typically, this is a local structure and the content of which will be copied into the configuration structure within XUsb. XST_SUCCESS no errors occurred.XST_FAILURE an error occurred during initialization. None.
References XUsb_EpConfig::Buffer0Count, XUsb_EpConfig::Buffer0Ready, XUsb_EpConfig::Buffer1Count, XUsb_EpConfig::Buffer1Ready, XUsb_EpConfig::CurBufNum, XUsb::DeviceConfig, XUsb_DeviceConfig::Ep, XUsb_EpConfig::EpType, XUsb_DeviceConfig::NumEndpoints, XUsb_EpConfig::OutIn, XUsb_EpConfig::RamBase, XUsb_EpConfig::Size, XUsb_EpConfigure.
Referenced by InitUsbInterface.
void XUsb_Start(XUsb *InstancePtr)
This function starts the USB Device.
InstancePtr is a pointer to the XUsb instance. None. None.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb::IsReady, XUSB_CONTROL_OFFSET, XUSB_CONTROL_USB_READY_MASK, XUsb_WriteReg.
Referenced by main, UsbIfIntrHandler, UsbKbdExample, UsbMouseExample, XUsb_SetTestMode.
void XUsb_Stop(XUsb *InstancePtr)
This function stops the USB device.
InstancePtr is a pointer to the XUsb instance. None. None.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb::IsReady, XUSB_CONTROL_OFFSET, XUSB_CONTROL_USB_READY_MASK, XUsb_ReadReg, XUsb_WriteReg.
Referenced by UsbIfIntrHandler, XUsb_SetTestMode.
u32 XUsb_GetFrameNum(const XUsb *InstancePtr)
This function returns the current frame number.
InstancePtr is a pointer to the XUsb instance. The current frame number.. None.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb::IsReady, XUSB_FRAMENUM_OFFSET, XUsb_ReadReg.
int XUsb_SetDeviceAddress(XUsb *InstancePtr, u8 Address)
This function sets the USB device address.
InstancePtr is a pointer to the XUsb instance. Address is the device address to be set. XST_SUCCESS: Address set successfully.XST_INVALID_PARAM: Invalid parameter passed. None.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb::IsReady, XUSB_ADDRESS_OFFSET, XUSB_DEVICEADDR_MAX, XUsb_WriteReg.
Referenced by EP0ProcessInToken, main, UsbIfIntrHandler, UsbKbdExample, UsbMouseExample.
void XUsb_SetTestMode(XUsb *InstancePtr, u8 TestMode, u8 *BufPtr)
This function sets the USB device into a given test mode.
InstancePtr is a pointer to the XUsb instance. TestMode is the type of test to be performed. BufPtr is a pointer to the buffer containing the test packet. None. If the test mode is Test packet(TEST_PKT), then user needs to pass the address of the buffer containing the test packet. In other cases, the BufPtr parameter is not used and the user can send a NULL or any value. BufPtr parameter should be 32 bit aligned.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb::IsReady, TEST_J, TEST_K, TEST_PKT, TEST_SE0_NAK, XUsb_Start, XUsb_Stop, XUSB_TESTMODE_OFFSET, XUsb_WriteReg.
Referenced by EP0ProcessInToken.
void XUsb_DmaReset(XUsb *InstancePtr)
This function resets the DMA module of the USB device.
InstancePtr is a pointer to the XUsb instance. None. After the DMA reset, only the DMA related logic part of the USB device will be reset and all the DMA related registers will be reset to the default values. Upon DMA Reset, any DMA transfer in progress will be stopped.
References XUsb_Config::BaseAddress, XUsb::Config, XUSB_DMA_RESET_OFFSET, XUSB_DMA_RESET_VALUE, XUsb_WriteReg.
void XUsb_DmaTransfer(XUsb *InstancePtr, UINTPTR *SrcAddr, UINTPTR *DstAddr, u16 Length)
This function sets the DMA registers with the given values to initiate a DMA data transfer.
This function is called by the XUsb_EpDataSend and XUsb_EpDataRecv functions. InstancePtr is a pointer to the XUsb instance. SrcAddr is the source address from where the data is to be read. DstAddr is the destination address to where the data is to be written. Length is the amount of data that can be transferred. The maximum data transfer can be 1024. None. This function doesn't guarantee that the transfer is done successfully. This function only initiates the DMA transfer.
References XUsb_Config::AddrWidth, XUsb_Config::BaseAddress, XUsb::Config, XUSB_DMA_DDAR_ADDR_OFFSET, XUSB_DMA_DDAR_ADDR_OFFSET_LSB, XUSB_DMA_DDAR_ADDR_OFFSET_MSB, XUSB_DMA_DSAR_ADDR_OFFSET, XUSB_DMA_DSAR_ADDR_OFFSET_LSB, XUSB_DMA_DSAR_ADDR_OFFSET_MSB, XUSB_DMA_LENGTH_OFFSET, XUsb_WriteReg.
Referenced by XUsb_EpDataRecv, XUsb_EpDataSend.
void XUsb_ReadErrorCounters(XUsb *InstancePtr, u8 *BitStuffErrors, u8 *PidErrors, u8 *CrcErrors)
This function reads the USB error counter register and returns the error counters information.
InstancePtr is a pointer to the XUsb instance. BitStuffErrors is a pointer to the 8 bit bitstuff error counter. PidErrors is a pointer to the 8 bit pid error counter. CrcErrors is a pointer to the 8 bit crc error counter. None. None.
References XUsb_Config::BaseAddress, XUsb::Config, XUSB_ECR_BITSTUFF_ERRCNT_MASK, XUSB_ECR_CRC_ERRCNT_MASK, XUSB_ECR_OFFSET, XUSB_ECR_PID_ERRCNT_MASK, XUsb_ReadReg.
u8 XUsb_UlpiPhyReadRegister(XUsb *InstancePtr, u8 RegAddr)
This function initiates the USB ULPI PHY register read transaction.
This function returns the busy status if the earlier transaction is still in progress and returns the PHY register data upon successful read transaction. InstancePtr is a pointer to the XUsb instance. RegAddr is the address of the PHY register. Register dataXST_DEVICE_BUSY: The previous PHY transaction is still in progress. This function waits till the BUSY bit is cleared in the ULPI PHY resgiter and then reads the register. The user of this API should note that the PHY interrupt should be ignored during read operation.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb_ReadReg, XUSB_UPAR_BUSY_MASK, XUSB_UPAR_OFFSET, XUSB_UPAR_REG_DATA_MASK, XUsb_WriteReg.
Referenced by main.
int XUsb_UlpiPhyWriteRegister(XUsb *InstancePtr, u8 RegAddr, u8 UlpiPhyRegData)
This function initiates the USB ULPI PHY register write transaction.
This function returns the busy status if the earlier transaction is still in progress and returns a success upon successful write transaction initiation. InstancePtr is a pointer to the XUsb instance. RegAddr is the address of the PHY register. counter. UlpiPhyRegData is the data to be written to PHY register. XST_SUCCESS: Read transaction initiated successfully.XST_DEVICE_BUSY: The previous PHY transaction is still in progress. None.
References XUsb_Config::BaseAddress, XUsb::Config, XUsb_ReadReg, XUSB_UPAR_BUSY_MASK, XUSB_UPAR_OFFSET, XUSB_UPAR_READ_WRITE_MASK, XUsb_WriteReg.
Referenced by main.
void XUsb_SieReset(XUsb *InstancePtr)
This function resets the Serial Interface Engine.
InstancePtr is a pointer to the XUsb instance. None. After the SIE reset, only the SIE state machine logic part of the USB device will be reset and starts from Init state.
References XUsb_Config::BaseAddress, XUsb::Config, XUSB_CONTROL_OFFSET, XUSB_CONTROL_SIE_RESET_MASK, XUsb_ReadReg, XUsb_WriteReg.