xusb_dma_intr_storage.c
READ_COMMAND
WRITE_COMMAND
XUSB_BASEADDRESS
XUsb UsbInstance
XUsb_Config* UsbConfigPtr
volatile u8 CmdFlag
volatile u8 FirstPkt
u8* WrRamDiskPtr
u8* RdRamDiskPtr
volatile u8 RdIndex
volatile u8 WrIndex
volatile u8 TxDmaTransfer
volatile u8 RxDmaTransfer
volatile u8 ResponseSent
volatile u8 SendStatus
volatile u8 RdResponseSent
volatile u8 WrDataPhase
volatile u8 TwoRxInterrupts
volatile u8 TwoTxInterrupts
void ReadTransfer(XUsb *InstancePtr)
This function implements the reception of data in the USB device for the READ request from the USB Host.
InstancePtr is a pointer to the XUsb instance. None. None.
References XUsb_DeviceConfig::CurrentSpeed, XUsb::DeviceConfig, XUSB_EP_HIGH_SPEED, XUsb_EpDataSend.
Referenced by DmaIntrHandler, Ep1IntrHandler.
void WriteTransfer(XUsb *InstancePtr)
This function implements the reception of data in the USB device for the WRITE request from the USB Host.
InstancePtr is a pointer to the XUsb instance. None. None.
References XUsb_DeviceConfig::CurrentSpeed, XUsb::DeviceConfig, XUSB_EP_HIGH_SPEED, XUsb_EpDataRecv, XUsb_EpDataSend.
Referenced by DmaIntrHandler, Ep2IntrHandler.
void DmaIntrHandler(void *CallBackRef, u32 IntrStatus)
This function is the interrupt handler for the USB DMA events.
CallBackRef is the callback reference passed from the interrupt handler, which in our case is a pointer to the driver instance. IntrStatus is a bit mask indicating pending interrupts. None. None.
References XUsb::DeviceConfig, ProcessRxCmd, ReadTransfer, XUsb_DeviceConfig::Status, WriteTransfer, XUSB_DISCONNECTED, XUsb_EpDataSend, XUSB_STATUS_DMA_DONE_MASK, XUSB_STATUS_DMA_ERROR_MASK.
Referenced by main.
int main()
This main function starts the USB application.
None. XST_SUCCESS if successful.XST_FAILURE if test fails. None.
References XUsb_Config::BaseAddress, XUsb_DeviceConfig::CurrentConfiguration, XUsb::DeviceConfig, DmaIntrHandler, Ep0IntrHandler, Ep1IntrHandler, Ep2IntrHandler, InitUsbInterface, XUsb_Config::IntrId, XUsb_Config::IntrParent, UsbIfIntrHandler, XUsb_CfgInitialize, XUsb_DmaIntrSetHandler, XUsb_EpSetHandler, XUsb_IntrEnable, XUsb_IntrHandler, XUsb_IntrSetHandler, XUsb_LookupConfig, XUsb_SetDeviceAddress, XUsb_Start, XUSB_STATUS_DISCONNECT_MASK, XUSB_STATUS_EP0_BUFF1_COMP_MASK, XUSB_STATUS_EP1_BUFF1_COMP_MASK, XUSB_STATUS_EP1_BUFF2_COMP_MASK, XUSB_STATUS_EP2_BUFF1_COMP_MASK, XUSB_STATUS_EP2_BUFF2_COMP_MASK, XUSB_STATUS_FIFO_BUFF_FREE_MASK, XUSB_STATUS_FIFO_BUFF_RDY_MASK, XUSB_STATUS_GLOBAL_INTR_MASK, XUSB_STATUS_RESET_MASK, XUSB_STATUS_SUSPEND_MASK.
void InitUsbInterface(XUsb *InstancePtr)
This is the USB initialization function.
This example initializes the device for Mass Storage Application. The following configuration is done. EP0 : CONTROL end point, Bidirectional, Packet size 64 bytes.EP1 : NON_ISOCHRONOUS, BULK_IN, packet size 512 bytes.EP2 : NON_ISOCHRONOUS, BULK_OUT, packet size 512 bytes InstancePtr is a pointer to the XUsb instance. None. None.
void UsbIfIntrHandler(void *CallBackRef, u32 IntrStatus)
This function is the interrupt handler for the USB mass storage device application.
CallBackRef is the callback reference passed from the interrupt handler, which in our case is a pointer to the driver instance. IntrStatus is a bit mask indicating pending interrupts. None. None.
Referenced by main, UsbKbdExample, UsbMouseExample.
void Ep0IntrHandler(void *CallBackRef, u8 EpNum, u32 IntrStatus)
This function is the interrupt handler for the USB End point Zero events.
CallBackRef is the callback reference passed from the interrupt. handler, which in our case is a pointer to the driver instance. EpNum is the end point number. IntrStatus is a bit mask indicating pending interrupts. None. EpNum is not used in this function as the handler is attached specific to end point zero. This parameter is useful when a single handler is used for processing all end point interrupts.
Referenced by main, UsbKbdExample, UsbMouseExample.
void Ep1IntrHandler(void *CallBackRef, u8 EpNum, u32 IntrStatus)
This function is the interrupt handler for the USB End point one events.
CallBackRef is the callback reference passed from the interrupt handler, which in our case is a pointer to the driver instance. EpNum is the end point number. IntrStatus is a bit mask indicating pending interrupts. None. EpNum is not used in this function as the handler is attached specific to end point one. This parameter is useful when a single handler is used for processing all end point interrupts.
Referenced by main, UsbKbdExample, UsbMouseExample.
void Ep2IntrHandler(void *CallBackRef, u8 EpNum, u32 IntrStatus)
This function is the interrupt handler for the USB End point two events.
CallBackRef is the callback reference passed from the interrupt handler, which in our case is a pointer to the driver instance. EpNum is the end point number. IntrStatus is a bit mask indicating pending interrupts. None. EpNum is not used in this function as the handler is attached specific to end point two. This parameter is useful when a single handler is used for processing all end point interrupts.
Referenced by main.
void ProcessRxCmd(XUsb *InstancePtr)
This function processes mass storage specific commands and sends the required response.
InstancePtr is a pointer to the XUsb instance. None. None.
Referenced by DmaIntrHandler, main.
void Read10(XUsb *InstancePtr, PUSBCBW pCmdBlock, PUSBCSW pStatusBlock)
This function implements the transmission of data from the device to the READ request from the USB Host.
InstancePtr is a pointer to the XUsb instance. pCmdBlock is a pointer to the Mass Storage Command Block wrapper. pStatusBlock is a pointer to the Mass Storage Status wrapper. None. None.
Referenced by ProcessRxCmd.
void Write10(XUsb *InstancePtr, PUSBCBW pCmdBlock, PUSBCSW pStatusBlock)
This function implements the reception of data in the USB device for the write request from the USB Host.
InstancePtr is a pointer to the XUsb instance. pCmdBlock is a pointer to the Mass Storage Command Block wrapper. pStatusBlock is a pointer to the Mass Storage Status wrapper. None. None.
Referenced by ProcessRxCmd.
void MassStorageReset(XUsb *InstancePtr)
This routine is called when a RESET class command is received.
InstancePtr is a pointer to the XUsb instance of the controller. None. None.
Referenced by Ep0IntrHandler.
void GetMaxLUN(XUsb *InstancePtr)
This routine is called when a GETMAXLUN class command is received.
InstancePtr is a pointer to the XUsb instance of the controller. None. None.
Referenced by Ep0IntrHandler.