xusb_sinit.c
XUsb_Config XUsb_ConfigTable[][]
This table contains the configuration information for each of the USB devices in the system.
XUsb_Config * XUsb_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
A table contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found.NULL if the specified device ID/BaseAddress was not found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
Referenced by main, UsbKbdExample, UsbMouseExample.