xdp.h
XPAR_XDPTXSS_NUM_INSTANCES
XPAR_XDPRXSS_NUM_INSTANCES
XDp_GetCoreType
This is function determines whether the DisplayPort core, represented by the XDp structure pointed to, is a transmitter (TX) or a receiver (RX).
InstancePtr is a pointer to the XDp instance. XDP_RX if the core is of type RX. XDP_TX if the core is of type TX. C-style signature: XDp_CoreType XDp_GetCoreType(XDp *InstancePtr)
Referenced by XDp_CfgInitialize, XDp_Initialize, XDp_InterruptHandler, XDp_SelfTest.
XDp_TxCfgSetRGB
The following functions set the color encoding scheme for a given stream.
InstancePtr is a pointer to the XDp instance. Stream is the stream number for which to configure the color encoding scheme for. XST_SUCCESS. C-style signatures: u32 XDp_TxCfgSetRGB(XDp *InstancePtr, u8 Stream) u32 XDp_TxCfgSetSRGB(XDp *InstancePtr, u8 Stream) u32 XDp_TxCfgSetYonly(XDp *InstancePtr, u8 Stream) u32 XDp_TxCfgSetYCbCr422Bt601(XDp *InstancePtr, u8 Stream) u32 XDp_TxCfgSetYCbCr422Bt709(XDp *InstancePtr, u8 Stream) u32 XDp_TxCfgSetYCbCr444Bt601(XDp *InstancePtr, u8 Stream) u32 XDp_TxCfgSetYCbCr444Bt709(XDp *InstancePtr, u8 Stream) u32 XDp_TxCfgSetXvYcc422Bt601(XDp *InstancePtr, u8 Stream) u32 XDp_TxCfgSetXvYcc422Bt709(XDp *InstancePtr, u8 Stream) u32 XDp_TxCfgSetXvYcc444Bt601(XDp *InstancePtr, u8 Stream) u32 XDp_TxCfgSetXvYcc444Bt709(XDp *InstancePtr, u8 Stream) u32 XDp_TxCfgSetAdbRGB(XDp *InstancePtr, u8 Stream)
XDp_TxCfgSetSRGB
XDp_TxCfgSetYonly
XDp_TxCfgSetYCbCr422Bt601
XDp_TxCfgSetYCbCr422Bt709
XDp_TxCfgSetYCbCr444Bt601
XDp_TxCfgSetYCbCr444Bt709
XDp_TxCfgSetXvYcc422Bt601
XDp_TxCfgSetXvYcc422Bt709
XDp_TxCfgSetXvYcc444Bt601
XDp_TxCfgSetXvYcc444Bt709
XDp_TxCfgSetAdbRGB
XDptx_ReadReg
XDprx_ReadReg
XDptx_WriteReg
XDprx_WriteReg
XDptx_Config
XDprx_Config
XDptx_TimerHandler
XDprx_TimerHandler
XDptx_HpdEventHandler
XDptx_HpdPulseHandler
XDprx_IntrHandler
XDptx_LookupConfig
XDprx_LookupConfig
XDptx_CfgInitialize
XDprx_CfgInitialize
XDptx_InitializeTx
XDprx_InitializeRx
XDptx_WaitUs
XDprx_WaitUs
XDptx_SetUserTimerHandler
XDprx_SetUserTimerHandler
XDptx_SelfTest
XDprx_SelfTest
XDptx_HpdInterruptHandler
XDprx_InterruptHandler
XDptx
XDprx
XDPTX
XDPRX
XDp_TxSbMsgLinkAddressReplyDeviceInfo
XDp_TxSbMsgLinkAddressReplyPortDetail
XDp_CoreType
XDp_DynamicRange
Dp_Rx_HandlerType
XDp_Tx_HandlerType
typedef void(* XDp_TimerHandler)(void *InstancePtr, u32 MicroSeconds))(void *InstancePtr, u32 MicroSeconds)
Callback type which represents a custom timer wait handler.
This is only used for Microblaze since it doesn't have a native sleep function. To avoid dependency on a hardware timer, the default wait functionality is implemented using loop iterations; this isn't too accurate. If a custom timer handler is used, the user may implement their own wait implementation using a hardware timer (see example/) for better accuracy. InstancePtr is a pointer to the XDp instance. MicroSeconds is the number of microseconds to be passed to the timer function. None.
typedef void(* XDp_IntrHandler)(void *InstancePtr))(void *InstancePtr)
Callback type which represents the handler for interrupts.
InstancePtr is a pointer to the XDp instance. None.
XDp_Config * XDp_LookupConfig(UINTPTR BaseAddress)
This function looks for the device configuration based on the unique device ID.
The table XDp_ConfigTable[] contains the configuration information for each device in the system. DeviceId is the unique device ID of the device being looked up. A pointer to the configuration table entry corresponding to the given device ID, or NULL if no match is found. None.
Referenced by Dp_SelfTestExample, Dptx_SetupExample.
void XDp_CfgInitialize(XDp *InstancePtr, XDp_Config *ConfigPtr, UINTPTR EffectiveAddr)
This function retrieves the configuration for this DisplayPort instance and fills in the InstancePtr->Config structure.
InstancePtr is a pointer to the XDp instance. ConfigPtr is a pointer to the configuration structure that will be used to copy the settings from. EffectiveAddr is the device base address in the virtual memory space. If the address translation is not used, then the physical address is passed. Unexpected errors may occur if the address mapping is changed after this function is invoked.
References XDp_Config::BaseAddr, XDp::Config, XDp::IsReady, XDp_GetCoreType.
Referenced by Dp_SelfTestExample, Dptx_SetupExample.
u32 XDp_Initialize(XDp *InstancePtr)
This function prepares the DisplayPort core for use depending on whether the core is operating in TX or RX mode.
InstancePtr is a pointer to the XDp instance. XST_SUCCESS if the DisplayPort core was successfully initialized.XST_FAILURE otherwise. None.
References XDp::IsReady, XDp_GetCoreType.
Referenced by Dptx_SetupExample.
u32 XDp_TxGetRxCapabilities(XDp *InstancePtr)
void XDp_SetUserTimerHandler(XDp *InstancePtr, XDp_TimerHandler CallbackFunc, void *CallbackRef)
This function installs a custom delay/sleep function to be used by the XDp driver.
InstancePtr is a pointer to the XDp instance. CallbackFunc is the address to the callback function. CallbackRef is the user data item (microseconds to delay) that will be passed to the custom sleep/delay function when it is invoked. None.
References XDp::UserTimerPtr, XDp::UserTimerWaitUs.
Referenced by Dptx_TimerExample.
void XDp_WaitUs(XDp *InstancePtr, u32 MicroSeconds)
This function is the delay/sleep function for the XDp driver.
For the Zynq family, there exists native sleep functionality. For MicroBlaze however, there does not exist such functionality. In the MicroBlaze case, the default method for delaying is to use a predetermined amount of loop iterations. This method is prone to inaccuracy and dependent on system configuration; for greater accuracy, the user may supply their own delay/sleep handler, pointed to by InstancePtr->UserTimerWaitUs, which may have better accuracy if a hardware timer is used. InstancePtr is a pointer to the XDp instance. MicroSeconds is the number of microseconds to delay/sleep for. None.
References XDp::IsReady, XDp::UserTimerWaitUs.
Referenced by Dptx_MstExampleRun.
u8 XDp_IsLaneCountValid(XDp *InstancePtr, u8 LaneCount)
This function checks the validity of the lane count.
InstancePtr is a pointer to the XDp instance. LaneCount is the number of lanes to check if valid. 1 if specified lane count is valid.0 otherwise, if the lane count specified isn't valid as per spec, or if it exceeds the capabilities of the TX core. None.
References XDp::Config, XDp_Config::MaxLaneCount, XDP_LANE_COUNT_SET_1, XDP_LANE_COUNT_SET_2, XDP_LANE_COUNT_SET_4.
u8 XDp_IsLinkRateValid(XDp *InstancePtr, u8 LinkRate)
This function checks the validity of the link rate.
InstancePtr is a pointer to the XDp instance. LinkRate is the link rate to check if valid. 1 if specified link rate is valid.0 otherwise, if the link rate specified isn't valid as per spec, or if it exceeds the capabilities of the TX core. None.
References XDp::Config, XDp_Config::MaxLinkRate, XDP_LINK_BW_SET_162GBPS, XDP_LINK_BW_SET_270GBPS, XDP_LINK_BW_SET_540GBPS.
void XDp_InterruptHandler(XDp *InstancePtr)
This function is the interrupt handler for the XDp driver.
When an interrupt happens, this interrupt handler will check which TX/RX mode of operation the core is running in, and will call the appropriate interrupt handler. The called interrupt handler will first detect what kind of interrupt happened, then decides which callback function to invoke. InstancePtr is a pointer to the XDp instance. None.
References XDp::IsReady, XDp_GetCoreType.
u32 XDp_SelfTest(XDp *InstancePtr)
This function runs a self-test on the XDp driver/device depending on whether the core is operating in TX or RX mode.
The sanity test checks whether or not all tested registers hold their default reset values. InstancePtr is a pointer to the XDp instance. XST_SUCCESS if the self-test passed - all tested registers hold their default reset values.XST_FAILURE otherwise. None.
References XDp::IsReady, XDp_GetCoreType.
Referenced by Dp_SelfTestExample.