xdp_tx_example_common.c
static void Dptx_StartVideoStream(XDp *InstancePtr)
This function will start sending a video stream over the main link.
The settings to be used are as follows: 8 bits per color.Video timing and screen resolution used:The connected monitor's preferred timing is used to determine the video resolution (and associated timings) for the stream. InstancePtr is a pointer to the XDp instance. None. The Dptx_StreamSrc* are intentionally left for the user to implement since configuration of the stream source is application-specific. The Extended Display Identification Data (EDID) is read in order to obtain the video resolution and timings. If this read fails, a resolution of 640x480 is used at a refresh rate of 60Hz.
u32 Dptx_Run(XDp *InstancePtr)
This function will configure and establish a link with the receiver device, afterwards, a video stream will start to be sent over the main link.
InstancePtr is a pointer to the XDp instance. LaneCount is the number of lanes to use over the main link. LinkRate is the link rate to use over the main link. XST_SUCCESS if main link was successfully established.XST_FAILURE otherwise. None.
References Dptx_StartLink.
Referenced by Dptx_AudioExample, Dptx_TimerExample.
u32 Dptx_SetupExample(XDp *InstancePtr, u16 DeviceId)
This function will setup and initialize the DisplayPort TX core.
The core's configuration parameters will be retrieved based on the configuration to the DisplayPort TX core instance with the specified device ID. InstancePtr is a pointer to the XDp instance. DeviceId is the unique device ID of the DisplayPort TX core instance. XST_SUCCESS if the device configuration was found and obtained and if the main link was successfully established.XST_FAILURE otherwise. None.
References XDp_Config::BaseAddr, XDp_CfgInitialize, XDp_Initialize, XDp_LookupConfig.
Referenced by Dptx_AudioExample, Dptx_IntrExample, Dptx_MstExample, Dptx_PollExample, Dptx_TimerExample.
u32 Dptx_StartLink(XDp *InstancePtr)
This function will configure and establish a link with the receiver device.
InstancePtr is a pointer to the XDp instance. XST_SUCCESS the if main link was successfully established.XST_FAILURE otherwise. None.
References XDp_Config::BaseAddr, XDp::Config, XDp_TxLinkConfig::LaneCount, XDp_Tx::LinkConfig, XDp_TxLinkConfig::LinkRate, XDp_TxLinkConfig::MaxLaneCount, XDp_TxLinkConfig::MaxLinkRate, XDp_TxLinkConfig::PeLevel, XDp_TxLinkConfig::VsLevel, XDp_ReadReg.
Referenced by Dptx_MstExampleRun, Dptx_Run.