xdp.c
XDP_AUX_MAX_DEFER_COUNT
XDP_AUX_MAX_TIMEOUT_COUNT
XDP_IS_CONNECTED_MAX_TIMEOUT_COUNT
static u32 XDp_WaitPhyReady(XDp *InstancePtr, u32 Mask)
This function waits for the DisplayPort PHY to come out of reset.
InstancePtr is a pointer to the XDp instance. XST_ERROR_COUNT_MAX if the PHY failed to be ready.XST_SUCCESS otherwise. None.
void XDp_CfgInitialize(XDp *InstancePtr, XDp_Config *ConfigPtr, UINTPTR EffectiveAddr)
This function retrieves the configuration for this DisplayPort instance and fills in the InstancePtr->Config structure.
InstancePtr is a pointer to the XDp instance. ConfigPtr is a pointer to the configuration structure that will be used to copy the settings from. EffectiveAddr is the device base address in the virtual memory space. If the address translation is not used, then the physical address is passed. Unexpected errors may occur if the address mapping is changed after this function is invoked.
References XDp_Config::BaseAddr, XDp::Config, XDp::IsReady, XDp_GetCoreType.
Referenced by Dp_SelfTestExample, Dptx_SetupExample.
u32 XDp_Initialize(XDp *InstancePtr)
This function prepares the DisplayPort core for use depending on whether the core is operating in TX or RX mode.
InstancePtr is a pointer to the XDp instance. XST_SUCCESS if the DisplayPort core was successfully initialized.XST_FAILURE otherwise. None.
References XDp::IsReady, XDp_GetCoreType.
Referenced by Dptx_SetupExample.
void XDp_SetUserTimerHandler(XDp *InstancePtr, XDp_TimerHandler CallbackFunc, void *CallbackRef)
This function installs a custom delay/sleep function to be used by the XDp driver.
InstancePtr is a pointer to the XDp instance. CallbackFunc is the address to the callback function. CallbackRef is the user data item (microseconds to delay) that will be passed to the custom sleep/delay function when it is invoked. None.
References XDp::UserTimerPtr, XDp::UserTimerWaitUs.
Referenced by Dptx_TimerExample.
void XDp_WaitUs(XDp *InstancePtr, u32 MicroSeconds)
This function is the delay/sleep function for the XDp driver.
For the Zynq family, there exists native sleep functionality. For MicroBlaze however, there does not exist such functionality. In the MicroBlaze case, the default method for delaying is to use a predetermined amount of loop iterations. This method is prone to inaccuracy and dependent on system configuration; for greater accuracy, the user may supply their own delay/sleep handler, pointed to by InstancePtr->UserTimerWaitUs, which may have better accuracy if a hardware timer is used. InstancePtr is a pointer to the XDp instance. MicroSeconds is the number of microseconds to delay/sleep for. None.
References XDp::IsReady, XDp::UserTimerWaitUs.
Referenced by Dptx_MstExampleRun.
u8 XDp_IsLinkRateValid(XDp *InstancePtr, u8 LinkRate)
This function checks the validity of the link rate.
InstancePtr is a pointer to the XDp instance. LinkRate is the link rate to check if valid. 1 if specified link rate is valid.0 otherwise, if the link rate specified isn't valid as per spec, or if it exceeds the capabilities of the TX core. None.
References XDp::Config, XDp_Config::MaxLinkRate, XDP_LINK_BW_SET_162GBPS, XDP_LINK_BW_SET_270GBPS, XDP_LINK_BW_SET_540GBPS.
u8 XDp_IsLaneCountValid(XDp *InstancePtr, u8 LaneCount)
This function checks the validity of the lane count.
InstancePtr is a pointer to the XDp instance. LaneCount is the number of lanes to check if valid. 1 if specified lane count is valid.0 otherwise, if the lane count specified isn't valid as per spec, or if it exceeds the capabilities of the TX core. None.
References XDp::Config, XDp_Config::MaxLaneCount, XDP_LANE_COUNT_SET_1, XDP_LANE_COUNT_SET_2, XDP_LANE_COUNT_SET_4.