xilsfl
XSFL_DUAL_BYTE_OP_DISABLE
Macros to enable/disable Dual Byte opcode.
Referenced by XSfl_FlashSetSDRDDRMode.
XSFL_DUAL_BYTE_OP_INVERT
XSFL_DUAL_BYTE_OP_SAME
XSFL_EDGE_MODE_SDR_PHY
Macros to select different edge modes like SDR+NON-PHY, SDR+PHY and DDR+PHY.
Referenced by XSfl_FlashInit.
XSFL_EDGE_MODE_SDR_NON_PHY
XSFL_EDGE_MODE_DDR_PHY
XSFL_SELECT_FLASH_CS0
Macros to select CS0 and CS1.
Referenced by SflReadWriteExample, XSfl_FlashInit, XSfl_FlashSetSDRDDRMode, XSfl_GetRealAddr.
XSFL_SELECT_FLASH_CS1
XSFL_CONNECTION_MODE_SINGLE
Macros to select SINGLE, STACKED and PARALLEL connection modes.
XSFL_CONNECTION_MODE_STACKED
typedef union XSfl_UserConfig XSfl_UserConfig
This typedef contains configuration information for a flash/controller device.
The user is required to allocate a variable of this type. A variable of this type is then passed to the library API functions.
u32 XSfl_FlashInit(u8 *SflHandler, XSfl_UserConfig SflUserOptions, u8 ControllerInfo)
This function initializes controller interface and serial nor flash connected.
SflUserOptions contains the controller and flash configuration info. ControllerInfo contains the type of controller. SFL index on successful initialization, else Error codes.
References XSfl_FlashInfo::AddrSize, XSfl_CntrlInfo::BusWidth, XSfl_CntrlInfo::ChipSelectNum, XSfl_Interface::CntrlInfo, XSfl_CntrlInfo::CntrlType, XSfl_FlashInfo::ConnectionMode, XSfl_CntrlInfo::DeviceReset, XSfl_FlashInfo::FlashIndex, XFlashInfo::FlashType, XSfl_CntrlInfo::RefClockHz, XSfl_CntrlInfo::SdrDdrMode, XFlashInfo::SdrMaxFreq, XSfl_Interface::SflFlashInfo, XSFL_EDGE_MODE_SDR_PHY, XSfl_FlashEnableQuadMode, XSfl_FlashEnterExit4BAddMode, XSfl_FlashIdRead, XSfl_FlashSetSDRDDRMode, XSFL_OSPI_CNTRL, XSFL_SELECT_FLASH_CS0.
Referenced by SflReadWriteExample.
u32 XSfl_FlashErase(u8 SflHandler, u32 Address, u32 ByteCount)
This function erases the serial nor flash connected to the specific interface.
SflHandler is a pointer to the Sfl interface component to use. Address is the sector offset address of the flash at which data to be erased. ByteCount contains the total size to be erased. XST_SUCCESS if successful, else error code.
References XSfl_Interface::SflFlashInfo, XSfl_SectorErase.
Referenced by SflReadWriteExample.
u32 XSfl_FlashWrite(u8 SflHandler, u32 Address, u32 ByteCount, u8 *WriteBfrPtr)
This function writes to the serial nor flash connected to the interface driver.
SflHandler is a index to the Sfl interface component to use. Address contains the address to write data to in the Flash. ByteCount contains the number of bytes to be write. WriteBfrPtr is Pointer to the write buffer (which is to be transmitted) XST_SUCCESS if successful, else error code.
References XSfl_Interface::SflFlashInfo, XSfl_FlashPageWrite.
Referenced by SflReadWriteExample.
u32 XSfl_FlashReadStart(u8 SflHandler, u32 Address, u32 ByteCount, u8 *ReadBfrPtr, u64 RxAddr64bit)
This function reads from the flash connected to the specific interface.
SflHandler is a index to the Sfl interface component to use. Address contains the address of the flash that needs to be read. ByteCount contains the total size to be erased. ReadBfrPtr is the pointer to the read buffer to which valid received data should be written RxAddr64bit is of the 64bit address of destination read buffer to which valid received data should be written. XST_SUCCESS if successful, else error code.
References XSfl_FlashNonBlockingReadProcess.
Referenced by SflReadWriteExample.
u32 XSfl_FlashReadDone(u8 SflHandler)
This function used to check read completion status of serial Flash connected to the Specific interface.
SflHandler is a pointer to the Sfl interface driver component to use. XST_SUCCESS if successful, else error code.
References XSfl_FlashTransferDone.
Referenced by SflReadWriteExample.
u32 XSfl_FlashGetInfo(u8 SflHandler, u8 Option, u32 *DataPtr)
This function used to get details serial Flash connected to the Specific interface.
SflHandler is a pointer to the Sfl interface driver component to use. Option is to get specific details of the flash. DataPtr is the pointer to the flash info to be copied. XST_SUCCESS if successful, else error code.
References XSfl_FlashInfo::FlashIndex, XFlashInfo::FlashType, XSfl_Interface::SflFlashInfo.
Referenced by SflReadWriteExample.
u32 XSfl_FlashRead(u8 SflHandler, u32 Address, u32 ByteCount, u8 *ReadBfrPtr, u64 RxAddr64bit)
This function performs read from the flash.
SflHandler is a index to the Sfl interface component to use. Address contains the address of the flash that needs to be read. ByteCount contains the total size to be erased. ReadBfrPtr is the pointer to the read buffer to which valid received data should be written RxAddr64bit is of the 64bit address of destination read buffer to which valid received data should be written. XST_SUCCESS if successful, else error code.
References XSfl_FlashReadProcess.
Referenced by SflReadWriteExample.
XSFL_FLASH_PROTO_1_1_1
Macros to select Read and Write prototype.
Referenced by XSfl_FlashIdRead.
XSFL_FLASH_PROTO_1_0_1
XSFL_FLASH_PROTO_1_1_2
XSFL_FLASH_PROTO_1_1_8
XSFL_FLASH_PROTO_1_8_8
XSFL_FLASH_PROTO_8_8_8
XSFL_FLASH_PROTO_8_0_0
XSFL_FLASH_PROTO_8_8_0
XSFL_FLASH_PROTO_8_0_8
XSFL_FLASH_PROTO_1_1_4
XSFL_FLASH_PROTO_4_4_4
XSFL_FLASH_ID
XSFL_DEVICE_SIZE
XSFL_SECT_SIZE
XSFL_PAGE_SIZE
XSFL_FLASH_TYPE
XSFL_X1_BUS_WIDTH
XSFL_X2_BUS_WIDTH
XSFL_X4_BUS_WIDTH
XSFL_X8_BUS_WIDTH
XSFL_WB_QUAD_ENABLE_BIT
Winbond QE bit: Status Register-2 bit[1] (SR2[1]).
Setting this bit enables Quad SPI transfers.
Referenced by XSfl_FlashEnableQuadMode.
u64 XSfl_Msg::RxAddr64bit
Provide 64-bit read address for 32-bit platform.
Referenced by XSfl_FlashNonBlockingReadProcess, XSfl_FlashReadProcess.
u32 XSfl_Msg::ByteCount
Number of bytes to read or write.
Referenced by XSfl_FlashCmdTransfer, XSfl_FlashIdRead, XSfl_FlashNonBlockingReadProcess, XSfl_FlashPageWrite, XSfl_FlashReadProcess, XSfl_FlashRegisterReadWrite, XSfl_SectorErase, XSfl_WaitforStatusDone.
u32 XSfl_Msg::Addr
Device Address.
Referenced by XSfl_FlashCmdTransfer, XSfl_FlashNonBlockingReadProcess, XSfl_FlashPageWrite, XSfl_FlashReadProcess, XSfl_FlashRegisterReadWrite, XSfl_SectorErase, XSfl_WaitforStatusDone.
u8* XSfl_Msg::TxBfrPtr
Write buffer pointer.
Referenced by XSfl_FlashCmdTransfer, XSfl_FlashIdRead, XSfl_FlashNonBlockingReadProcess, XSfl_FlashPageWrite, XSfl_FlashReadProcess, XSfl_FlashRegisterReadWrite, XSfl_SectorErase, XSfl_WaitforStatusDone.
u8* XSfl_Msg::RxBfrPtr
Read buffer pointer.
Referenced by XSfl_FlashCmdTransfer, XSfl_FlashIdRead, XSfl_FlashNonBlockingReadProcess, XSfl_FlashPageWrite, XSfl_FlashReadProcess, XSfl_FlashRegisterReadWrite, XSfl_SectorErase, XSfl_WaitforStatusDone.
u8 XSfl_Msg::Opcode
Opcode/Command.
Referenced by XSfl_FlashCmdTransfer, XSfl_FlashIdRead, XSfl_FlashNonBlockingReadProcess, XSfl_FlashPageWrite, XSfl_FlashReadProcess, XSfl_FlashRegisterReadWrite, XSfl_SectorErase, XSfl_WaitforStatusDone.
u8 XSfl_Msg::Dummy
Number of dummy cycles for opcode.
Referenced by XSfl_FlashCmdTransfer, XSfl_FlashIdRead, XSfl_FlashNonBlockingReadProcess, XSfl_FlashPageWrite, XSfl_FlashReadProcess, XSfl_FlashRegisterReadWrite, XSfl_SectorErase, XSfl_WaitforStatusDone.
u8 XSfl_Msg::Xfer64bit
Set to 1 when reading from 64-bit addr otherwise 0.
Referenced by XSfl_FlashNonBlockingReadProcess, XSfl_FlashReadProcess.
u8 XSfl_Msg::DualByteOpCode
Extended opcode in dual-byte opcode mode.
Referenced by XSfl_FlashCmdTransfer, XSfl_FlashNonBlockingReadProcess, XSfl_FlashPageWrite, XSfl_FlashReadProcess, XSfl_FlashRegisterReadWrite, XSfl_SectorErase, XSfl_WaitforStatusDone.
u8 XSfl_Msg::Addrsize
Size of address in bytes.
Referenced by XSfl_FlashCmdTransfer, XSfl_FlashIdRead, XSfl_FlashNonBlockingReadProcess, XSfl_FlashPageWrite, XSfl_FlashReadProcess, XSfl_FlashRegisterReadWrite, XSfl_SectorErase, XSfl_WaitforStatusDone.
u8 XSfl_Msg::Addrvalid
1 if Address is required for opcode, 0 otherwise
Referenced by XSfl_FlashCmdTransfer, XSfl_FlashIdRead, XSfl_FlashNonBlockingReadProcess, XSfl_FlashPageWrite, XSfl_FlashReadProcess, XSfl_FlashRegisterReadWrite, XSfl_SectorErase, XSfl_WaitforStatusDone.
u8 XSfl_Msg::Proto
Indicate number of Cmd-Addr-Data lines.
Referenced by XSfl_FlashCmdTransfer, XSfl_FlashIdRead, XSfl_FlashNonBlockingReadProcess, XSfl_FlashPageWrite, XSfl_FlashReadProcess, XSfl_FlashRegisterReadWrite, XSfl_SectorErase, XSfl_WaitforStatusDone.
u32 XSfl_FlashInfo::FlashIndex
Index in the flash_info structure.
Referenced by XSfl_FlashCmdTransfer, XSfl_FlashGetInfo, XSfl_FlashIdRead, XSfl_FlashInit, XSfl_FlashNonBlockingReadProcess, XSfl_FlashPageWrite, XSfl_FlashReadProcess, XSfl_FlashRegisterReadWrite, XSfl_FlashSetSDRDDRMode, XSfl_GetRealAddr, XSfl_SectorErase, XSfl_WaitforStatusDone.
u32 XSfl_FlashInfo::DeviceSize
u32 XSfl_FlashInfo::SectSize
u32 XSfl_FlashInfo::SectCount
u32 XSfl_FlashInfo::PageSize
u32 XSfl_FlashInfo::PageCount
u8 XSfl_FlashInfo::ConnectionMode
Type of connection (single/stacked/parallel)
Referenced by XSfl_FlashEnterExit4BAddMode, XSfl_FlashInit, XSfl_FlashNonBlockingReadProcess, XSfl_FlashReadProcess, XSfl_FlashSetSDRDDRMode, XSfl_GetRealAddr.
u8 XSfl_FlashInfo::FlashMake
vendor info
Referenced by XSfl_FlashEnableQuadMode, XSfl_FlashEnterExit4BAddMode, XSfl_FlashIdRead.
u8 XSfl_FlashInfo::AddrSize
Size of address in bytes.
Referenced by XSfl_FlashInit, XSfl_FlashNonBlockingReadProcess, XSfl_FlashPageWrite, XSfl_FlashReadProcess, XSfl_SectorErase.
u32* XSfl_CntrlInfo::DeviceIdData
Contains Device Id Data information.
Is used for configuring SDR/DDR mode
Referenced by XSfl_FlashIdRead.
u32 XSfl_CntrlInfo::OpMode
Operating Mode DAC or INDAC.
Referenced by XSfl_FlashNonBlockingReadProcess, XSfl_FlashReadProcess.
u32 XSfl_CntrlInfo::RefClockHz
Input clock frequency.
Referenced by XSfl_FlashInit.
u8 XSfl_CntrlInfo::DeviceId
ID of controller device.
Referenced by XSfl_FlashCmdTransfer, XSfl_FlashIdRead, XSfl_FlashNonBlockingReadProcess, XSfl_FlashPageWrite, XSfl_FlashReadProcess, XSfl_FlashRegisterReadWrite, XSfl_SectorErase, XSfl_WaitforStatusDone.
u8 XSfl_CntrlInfo::ChipSelectNum
Chip select information.
Referenced by XSfl_FlashInit.
u8 XSfl_CntrlInfo::SdrDdrMode
Edge mode can be SDR or DDR.
Referenced by XSfl_FlashCmdTransfer, XSfl_FlashInit, XSfl_FlashNonBlockingReadProcess, XSfl_FlashPageWrite, XSfl_FlashReadProcess, XSfl_FlashRegisterReadWrite, XSfl_FlashSetSDRDDRMode, XSfl_SectorErase, XSfl_WaitforStatusDone.
u8 XSfl_CntrlInfo::CntrlType
Type of the interface controller.
Referenced by XSfl_FlashInit.
u8 XSfl_CntrlInfo::BusWidth
Bus width available on board.
Referenced by XSfl_FlashInit, XSfl_FlashNonBlockingReadProcess, XSfl_FlashReadProcess.
u32(* XSfl_CntrlInfo::RxTunning)())()
Callback reference for Rx tuning.
u32(* XSfl_CntrlInfo::SelectFlash)(u8 ChipSelNum))(u8 ChipSelNum)
Callback reference for chip select.
Referenced by XSfl_FlashEnableQuadMode, XSfl_FlashEnterExit4BAddMode, XSfl_FlashIdRead, XSfl_FlashSetSDRDDRMode, XSfl_GetRealAddr.
u32(* XSfl_CntrlInfo::Transfer)(u8 Index, XSfl_Msg *SflMsg))(u8 Index, XSfl_Msg *SflMsg)
Callback reference for interface transfer function.
Referenced by XSfl_FlashCmdTransfer, XSfl_FlashIdRead, XSfl_FlashPageWrite, XSfl_FlashReadProcess, XSfl_FlashRegisterReadWrite, XSfl_SectorErase, XSfl_WaitforStatusDone.
u32(* XSfl_CntrlInfo::NonBlockingTransfer)(u8 Index, XSfl_Msg *SflMsg))(u8 Index, XSfl_Msg *SflMsg)
Callback reference for interface non blocking transfer function.
Referenced by XSfl_FlashNonBlockingReadProcess.
u32(* XSfl_CntrlInfo::SetSdrDdr)(u8 Mode, u8 DualByteOpCode))(u8 Mode, u8 DualByteOpCode)
Callback reference for controller configs.
Referenced by XSfl_FlashSetSDRDDRMode.
u32(* XSfl_CntrlInfo::TransferDone)(u8 Index))(u8 Index)
Callback reference for flash read status.
Referenced by XSfl_FlashNonBlockingReadProcess, XSfl_FlashTransferDone.
u32(* XSfl_CntrlInfo::DeviceReset)(u8 Type))(u8 Type)
Callback reference for Device reset.
Referenced by XSfl_FlashInit.
XSfl_CntrlInfo XSfl_Interface::CntrlInfo
Controller specific information.
Referenced by XSfl_FlashCmdTransfer, XSfl_FlashEnableQuadMode, XSfl_FlashEnterExit4BAddMode, XSfl_FlashIdRead, XSfl_FlashInit, XSfl_FlashNonBlockingReadProcess, XSfl_FlashPageWrite, XSfl_FlashReadProcess, XSfl_FlashRegisterReadWrite, XSfl_FlashSetSDRDDRMode, XSfl_FlashTransferDone, XSfl_GetRealAddr, XSfl_SectorErase, XSfl_WaitforStatusDone.
XSfl_FlashInfo XSfl_Interface::SflFlashInfo
Flash Specific information.
Referenced by XSfl_FlashCmdTransfer, XSfl_FlashEnableQuadMode, XSfl_FlashEnterExit4BAddMode, XSfl_FlashErase, XSfl_FlashGetInfo, XSfl_FlashIdRead, XSfl_FlashInit, XSfl_FlashNonBlockingReadProcess, XSfl_FlashPageWrite, XSfl_FlashReadProcess, XSfl_FlashRegisterReadWrite, XSfl_FlashSetSDRDDRMode, XSfl_FlashWrite, XSfl_GetRealAddr, XSfl_SectorErase, XSfl_WaitforStatusDone.
u32 XSfl_Interface::Quirks
Quirks to handle specific use cases.
Referenced by XSfl_FlashNonBlockingReadProcess, XSfl_FlashReadProcess.
int XSfl::Index
XSfl_Interface XSfl::Instance[XSFL_NUM_INSTANCES][XSFL_NUM_INSTANCES]
u32 XSfl_UserConfig::Ospi_Conig::BaseAddress
Base address of the device.
u8 XSfl_UserConfig::Ospi_Conig::ReadMode
Operating Mode DAC or INDAC.
u8 XSfl_UserConfig::Ospi_Conig::ChipSelect
Chip select information.
u32 XSfl_UserConfig::Ospi_Conig::Quirks
Quirks to handle specific use cases.
struct XSfl_UserConfig::Ospi_Conig XSfl_UserConfig::Ospi_Config
u32 XFlashInfo::jedec_id
u32 XFlashInfo::SectSize
u32 XFlashInfo::NumSect
u32 XFlashInfo::PageSize
u32 XFlashInfo::NumPage
u32 XFlashInfo::FlashDeviceSize
u32 XFlashInfo::SectMask
u32 XFlashInfo::ReadCmd
u32 XFlashInfo::WriteCmd
u32 XFlashInfo::EraseCmd
u32 XFlashInfo::Proto
Indicate number of Cmd-Addr-Data lines.
Referenced by XSfl_FlashNonBlockingReadProcess, XSfl_FlashReadProcess.
u32 XFlashInfo::SdrMaxFreq
Max support frequency of flash in SDR mode.
Referenced by XSfl_FlashInit.
u32 XFlashInfo::DummyCycles
u8 XFlashInfo::StatusCmd
u8 XFlashInfo::NumDie
u8 XFlashInfo::FSRFlag
Indicates Flag Status Register.
u8 XFlashInfo::ExtOpCodeType
Extended opcode in dual-byte opcode mode.
Referenced by XSfl_FlashSetSDRDDRMode.
u8 XFlashInfo::FlashType
Indicates the type of the flash device.
Referenced by XSfl_FlashGetInfo, XSfl_FlashInit, XSfl_FlashSetSDRDDRMode.
const XFlashInfo Flash_Config_Table[][]
XSfl SflInstance
XSfl_Msg SflMsg
const XFlashInfo Flash_Config_Table[][]
u32 XSfl_OspiInit(XSfl_Interface *Ptr, const XSfl_UserConfig *UserConfig)
u32 XSfl_FlashIdRead(XSfl_Interface *SflInstancePtr, u8 ChipSelNum, u8 *SflReadBuffer)
Reads the flash ID and identifies the flash in FCT table.
SflInstancePtr is a pointer to the XSfl_Interface driver component to use. ChipSelNum is the chip select number. SflReadBuffer is pointer to the read buffer to store flash id. XST_SUCCESS if successful, otherwise error code.
References XSfl_Msg::Addrsize, XSfl_Msg::Addrvalid, XSfl_Msg::ByteCount, XSfl_Interface::CntrlInfo, XSfl_CntrlInfo::DeviceId, XSfl_CntrlInfo::DeviceIdData, XSfl_Msg::Dummy, XSfl_FlashInfo::FlashIndex, XSfl_FlashInfo::FlashMake, XSfl_Msg::Opcode, XSfl_Msg::Proto, XSfl_Msg::RxBfrPtr, XSfl_CntrlInfo::SelectFlash, XSfl_Interface::SflFlashInfo, XSfl_CntrlInfo::Transfer, XSfl_Msg::TxBfrPtr, XSfl_CalculateFCTIndex, XSFL_FLASH_PROTO_1_1_1.
Referenced by XSfl_FlashInit.
u32 XSfl_CalculateFCTIndex(u32 ReadId, u32 *FCTIndex)
This function used to Identifies the flash in FCT table.
XST_SUCCESS if successful, otherwise XST_FAILURE.
Referenced by XSfl_FlashIdRead.
u32 XSfl_FlashSetSDRDDRMode(XSfl_Interface *SflInstancePtr, int Mode)
This API enters the flash device into Octal DDR mode or exit from octal DDR mode (switches to Extended SPI mode).
SflInstancePtr is a pointer to the XSfl_Interface driver component to use. Mode is either 1 or 0 if 1 then enter octal DDR mode if 0 exits. - XST_SUCCESS if successful. error code if it fails.
References XSfl_Interface::CntrlInfo, XSfl_FlashInfo::ConnectionMode, XFlashInfo::ExtOpCodeType, XSfl_FlashInfo::FlashIndex, XFlashInfo::FlashType, XSfl_CntrlInfo::SdrDdrMode, XSfl_CntrlInfo::SelectFlash, XSfl_CntrlInfo::SetSdrDdr, XSfl_Interface::SflFlashInfo, XSFL_DUAL_BYTE_OP_DISABLE, XSfl_FlashCmdTransfer, XSfl_FlashRegisterReadWrite, XSFL_SELECT_FLASH_CS0.
Referenced by XSfl_FlashInit.
u32 XSfl_FlashEnterExit4BAddMode(XSfl_Interface *SflInstancePtr, int Enable, u8 ChipSelNum)
This API enters the flash device into 4 bytes addressing mode.
As per the Micron spec, before issuing the command to enter into 4 byte addr mode, a write enable command is issued. SflInstancePtr is a pointer to the XSfl_Interface driver component to use. Enable is a either 1 or 0 if 1 then enters 4 byte if 0 exits. ChipSelNum is the chip select number. - XST_SUCCESS if successful. error code if it fails.
References XSfl_Interface::CntrlInfo, XSfl_FlashInfo::ConnectionMode, XSfl_FlashInfo::FlashMake, XSfl_CntrlInfo::SelectFlash, XSfl_Interface::SflFlashInfo, XSfl_FlashCmdTransfer, XSfl_WaitforStatusDone.
Referenced by XSfl_FlashInit.
u32 XSfl_GetRealAddr(XSfl_Interface *SflInstancePtr, u32 Address)
This functions translates the address based on the type of interconnection.
In case of stacked, this function asserts the corresponding slave select. SflInstancePtr is a pointer to the interface driver component to use. Address which is to be accessed (for erase, write or read) RealAddr is the translated address - for single it is unchanged; for stacked, the lower flash size is subtracted; In addition to get the actual address to work on flash this function also selects the CS based on the configuration detected.
References XSfl_Interface::CntrlInfo, XSfl_FlashInfo::ConnectionMode, XSfl_FlashInfo::FlashIndex, XSfl_CntrlInfo::SelectFlash, XSfl_Interface::SflFlashInfo, XSFL_SELECT_FLASH_CS0.
Referenced by XSfl_FlashNonBlockingReadProcess, XSfl_FlashPageWrite, XSfl_FlashReadProcess, XSfl_SectorErase.
u32 XSfl_SectorErase(XSfl_Interface *SflInstancePtr, u32 Address)
This function used to erase the sectors of the serial nor flash connected to the specific interface.
Sfl_Handler is a pointer to the XSfl interface component to use. Address contains the address of the first sector which needs to be erased. XST_SUCCESS if successful, else error code.
References XSfl_Msg::Addr, XSfl_Msg::Addrsize, XSfl_FlashInfo::AddrSize, XSfl_Msg::Addrvalid, XSfl_Msg::ByteCount, XSfl_Interface::CntrlInfo, XSfl_CntrlInfo::DeviceId, XSfl_Msg::DualByteOpCode, XSfl_Msg::Dummy, XSfl_FlashInfo::FlashIndex, XSfl_Msg::Opcode, XSfl_Msg::Proto, XSfl_Msg::RxBfrPtr, XSfl_CntrlInfo::SdrDdrMode, XSfl_Interface::SflFlashInfo, XSfl_CntrlInfo::Transfer, XSfl_Msg::TxBfrPtr, XSfl_FlashCmdTransfer, XSfl_GetRealAddr, XSfl_WaitforStatusDone.
Referenced by XSfl_FlashErase.
u32 XSfl_FlashPageWrite(XSfl_Interface *SflInstancePtr, u32 Address, u32 ByteCount, u8 *WriteBfrPtr)
This function writes to the serial nor flash connected to the specific interface.
Sfl_Handler is a index to the Sfl interface component to use. Address contains the address of the first page which needs to be written. ByteCount contains the number of bytes to write. WriteBfrPtr is Pointer to the write buffer (which is to be transmitted) XST_SUCCESS if successful, else Error code.
References XSfl_Msg::Addr, XSfl_Msg::Addrsize, XSfl_FlashInfo::AddrSize, XSfl_Msg::Addrvalid, XSfl_Msg::ByteCount, XSfl_Interface::CntrlInfo, XSfl_CntrlInfo::DeviceId, XSfl_Msg::DualByteOpCode, XSfl_Msg::Dummy, XSfl_FlashInfo::FlashIndex, XSfl_Msg::Opcode, XSfl_Msg::Proto, XSfl_Msg::RxBfrPtr, XSfl_CntrlInfo::SdrDdrMode, XSfl_Interface::SflFlashInfo, XSfl_CntrlInfo::Transfer, XSfl_Msg::TxBfrPtr, XSfl_FlashCmdTransfer, XSfl_GetRealAddr, XSfl_WaitforStatusDone.
Referenced by XSfl_FlashWrite.
u32 XSfl_FlashReadProcess(XSfl_Interface *SflInstancePtr, u32 Address, u32 ByteCount, u8 *ReadBfrPtr, u64 RxAddr64bit)
This function performs read from the serial nor flash connected to specific interface.
Sfl_Handler is a index to the XSfl interface component to use. Address contains the address of the flash that needs to be read. ByteCount contains the total size to be erased. ReadBfrPtr is the pointer to the read buffer to which valid received data should be written RxAddr64bit is of the 64bit address of destination read buffer to which valid received data should be written. XST_SUCCESS if successful, else Error code.
References XSfl_Msg::Addr, XSfl_Msg::Addrsize, XSfl_FlashInfo::AddrSize, XSfl_Msg::Addrvalid, XSfl_CntrlInfo::BusWidth, XSfl_Msg::ByteCount, XSfl_Interface::CntrlInfo, XSfl_FlashInfo::ConnectionMode, XSfl_CntrlInfo::DeviceId, XSfl_Msg::DualByteOpCode, XSfl_Msg::Dummy, XSfl_FlashInfo::FlashIndex, XSfl_Msg::Opcode, XSfl_CntrlInfo::OpMode, XFlashInfo::Proto, XSfl_Msg::Proto, XSfl_Interface::Quirks, XSfl_Msg::RxAddr64bit, XSfl_Msg::RxBfrPtr, XSfl_CntrlInfo::SdrDdrMode, XSfl_Interface::SflFlashInfo, XSfl_CntrlInfo::Transfer, XSfl_Msg::TxBfrPtr, XSfl_Msg::Xfer64bit, XSFL_BROKEN_DMA, XSfl_GetRealAddr, XSFL_RXADDR_OVER_32BIT.
Referenced by XSfl_FlashRead.
u32 XSfl_FlashTransferDone(XSfl_Interface *SflInstancePtr)
This function used to check read completion status the serial Flash connected to the Specific interface.
Sfl_Handler is a pointer to the XSfl interface driver component to use. XST_SUCCESS if successful, else error code.
References XSfl_Interface::CntrlInfo, XSfl_CntrlInfo::TransferDone.
Referenced by XSfl_FlashReadDone.
u32 XSfl_WaitforStatusDone(XSfl_Interface *SflInstancePtr)
This API can be used to read status of the flash status register.
SflInstancePtr is a pointer to the interface driver component to use. XST_SUCCESS if successful, else error code. This API can only be used for one flash at a time.
References XSfl_Msg::Addr, XSfl_Msg::Addrsize, XSfl_Msg::Addrvalid, XSfl_Msg::ByteCount, XSfl_Interface::CntrlInfo, XSfl_CntrlInfo::DeviceId, XSfl_Msg::DualByteOpCode, XSfl_Msg::Dummy, XSfl_FlashInfo::FlashIndex, XSfl_Msg::Opcode, XSfl_Msg::Proto, XSfl_Msg::RxBfrPtr, XSfl_CntrlInfo::SdrDdrMode, XSfl_Interface::SflFlashInfo, XSfl_CntrlInfo::Transfer, XSfl_Msg::TxBfrPtr.
Referenced by XSfl_FlashEnableQuadMode, XSfl_FlashEnterExit4BAddMode, XSfl_FlashPageWrite, XSfl_SectorErase.
u32 XSfl_FlashRegisterReadWrite(XSfl_Interface *SflInstancePtr, u8 *RxBfrPtr, u8 *TxBfrPtr, u32 *CmdBufferPtr, u8 Addrvalid)
This API can be used to Read/write to a flash register.
SflInstancePtr is a pointer to the interface driver component to use. RxBfrPtr is the pointer to store the read value from flash. TxBfrPtr is the pointer to value to be written into flash. CmdBufferPtr is the pointer that holds command, address and dummy. Addrvalid defines the specific read/write requires address or not. XST_SUCCESS if successful, else error code. This API can only be used for one flash at a time.
References XSfl_Msg::Addr, XSfl_Msg::Addrsize, XSfl_Msg::Addrvalid, XSfl_Msg::ByteCount, XSfl_Interface::CntrlInfo, XSfl_CntrlInfo::DeviceId, XSfl_Msg::DualByteOpCode, XSfl_Msg::Dummy, XSfl_FlashInfo::FlashIndex, XSfl_Msg::Opcode, XSfl_Msg::Proto, XSfl_Msg::RxBfrPtr, XSfl_CntrlInfo::SdrDdrMode, XSfl_Interface::SflFlashInfo, XSfl_CntrlInfo::Transfer, XSfl_Msg::TxBfrPtr.
Referenced by XSfl_FlashEnableQuadMode, XSfl_FlashSetSDRDDRMode.
u32 XSfl_FlashCmdTransfer(XSfl_Interface *SflInstancePtr, u8 Cmd)
This API can be used to transfer the command to the flash.
SflInstancePtr is a pointer to the interface driver component to use. Cmd is the command to be transferred to the flash. XST_SUCCESS if successful, else error code. This API can only be used for one flash at a time.
References XSfl_Msg::Addr, XSfl_Msg::Addrsize, XSfl_Msg::Addrvalid, XSfl_Msg::ByteCount, XSfl_Interface::CntrlInfo, XSfl_CntrlInfo::DeviceId, XSfl_Msg::DualByteOpCode, XSfl_Msg::Dummy, XSfl_FlashInfo::FlashIndex, XSfl_Msg::Opcode, XSfl_Msg::Proto, XSfl_Msg::RxBfrPtr, XSfl_CntrlInfo::SdrDdrMode, XSfl_Interface::SflFlashInfo, XSfl_CntrlInfo::Transfer, XSfl_Msg::TxBfrPtr.
Referenced by XSfl_FlashEnableQuadMode, XSfl_FlashEnterExit4BAddMode, XSfl_FlashPageWrite, XSfl_FlashSetSDRDDRMode, XSfl_SectorErase.
u32 XSfl_FlashNonBlockingReadProcess(XSfl_Interface *SflInstancePtr, u32 Address, u32 ByteCount, u8 *ReadBfrPtr, u64 RxAddr64bit)
This function performs non-blocking read from the serial nor flash connected to specific interface.
Sfl_Handler is a index to the XSfl interface component to use. Address contains the address of the flash that needs to be read. ByteCount contains the total size to be erased. ReadBfrPtr is the pointer to the read buffer to which valid received data should be written RxAddr64bit is of the 64bit address of destination read buffer to which valid received data should be written. XST_SUCCESS if successful, else Error code.
References XSfl_Msg::Addr, XSfl_Msg::Addrsize, XSfl_FlashInfo::AddrSize, XSfl_Msg::Addrvalid, XSfl_CntrlInfo::BusWidth, XSfl_Msg::ByteCount, XSfl_Interface::CntrlInfo, XSfl_FlashInfo::ConnectionMode, XSfl_CntrlInfo::DeviceId, XSfl_Msg::DualByteOpCode, XSfl_Msg::Dummy, XSfl_FlashInfo::FlashIndex, XSfl_CntrlInfo::NonBlockingTransfer, XSfl_Msg::Opcode, XSfl_CntrlInfo::OpMode, XFlashInfo::Proto, XSfl_Msg::Proto, XSfl_Interface::Quirks, XSfl_Msg::RxAddr64bit, XSfl_Msg::RxBfrPtr, XSfl_CntrlInfo::SdrDdrMode, XSfl_Interface::SflFlashInfo, XSfl_CntrlInfo::TransferDone, XSfl_Msg::TxBfrPtr, XSfl_Msg::Xfer64bit, XSFL_BROKEN_DMA, XSfl_GetRealAddr, XSFL_RXADDR_OVER_32BIT.
Referenced by XSfl_FlashReadStart.
u32 XSfl_FlashEnableQuadMode(XSfl_Interface *SflInstancePtr, u8 ChipSelNum)
This function enables Quad mode for flashes which require to enable it before using Quad commands.
SflInstancePtr is a pointer to the interface driver component to use. ChipSelNum is the chip select number. XST_SUCCESS if successful, else XST_FAILURE.
References XSfl_Interface::CntrlInfo, XSfl_FlashInfo::FlashMake, XSfl_CntrlInfo::SelectFlash, XSfl_Interface::SflFlashInfo, XSfl_FlashCmdTransfer, XSfl_FlashRegisterReadWrite, XSfl_WaitforStatusDone, XSFL_WB_QUAD_ENABLE_BIT, XSFL_WB_READ_STATUS_REG2_CMD, XSFL_WB_WRITE_STATUS_REG2_CMD, XSFL_WINBOND_ID_BYTE0.
Referenced by XSfl_FlashInit.
XSFL_NUM_INSTANCES
XSFL_RXADDR_OVER_32BIT
Rx address over 32 bit.
Referenced by XSfl_FlashNonBlockingReadProcess, XSfl_FlashReadProcess.
XSFL_SDR_NON_PHY_MAX_FREQ
XSFL_WRITE_STATUS_CMD
XSFL_WRITE_DISABLE_CMD
XSFL_WRITE_ENABLE_CMD
XSFL_BULK_ERASE_CMD
XSFL_DIE_ERASE_CMD
XSFL_READ_ID
XSFL_READ_CONFIG_CMD
XSFL_WRITE_CONFIG_CMD
XSFL_READ_STATUS_CMD
XSFL_READ_FLAG_STATUS_CMD
XSFL_READ_CMD_4B
XSFL_WRITE_CMD_4B
XSFL_SEC_ERASE_CMD_4B
XSFL_READ_CMD_OCTAL_4B
XSFL_READ_CMD_OCTAL_IO_4B
XSFL_READ_CMD_OCTAL_DDR
XSFL_WRITE_CMD_OCTAL_4B
XSFL_ENTER_4B_ADDR_MODE
XSFL_EXIT_4B_ADDR_MODE
XSFL_WRITE_CONFIG_REG
XSFL_READ_CONFIG_REG
XSFL_DUAL_READ_CMD
XSFL_QUAD_READ_CMD
XSFL_DUAL_READ_CMD_4B
XSFL_QUAD_READ_CMD_4B
XSFL_QUAD_WRITE_CMD
XSFL_DUAL_WRITE_CMD
XSFL_QUAD_SEC_ERASE_CMD
XSFL_WRITE_CMD
XSFL_READ_CMD
XSFL_NO_CMD
No command / dummy command value (0x00)
XSFL_WB_READ_STATUS_REG2_CMD
Command for reading the status register 2.
This command is used to retrieve the status of the second status register. Winbond Read SR2 (0x35) coincides with XSFL_READ_CONFIG_CMD.
Referenced by XSfl_FlashEnableQuadMode.
XSFL_WB_WRITE_STATUS_REG2_CMD
Write Status Register 2 command.
This command is used to write the status register 2.
Referenced by XSfl_FlashEnableQuadMode.
XSFL_WINBOND_ID_BYTE0
The first byte of the Winbond ID.
Referenced by XSfl_FlashEnableQuadMode.
XSFL_SIXTEENMB
XSFL_FLASH_PAGE_SIZE_256
XSFL_FLASH_SECTOR_SIZE_4KB
XSFL_FLASH_SECTOR_SIZE_256KB
XSFL_FLASH_SECTOR_SIZE_64KB
XSFL_FLASH_SECTOR_SIZE_128KB
XSFL_FLASH_DEVICE_SIZE_128M
XSFL_FLASH_DEVICE_SIZE_256M
XSFL_FLASH_DEVICE_SIZE_512M
XSFL_FLASH_DEVICE_SIZE_1G
XSFL_FLASH_DEVICE_SIZE_2G
XSFL_MICRON_OCTAL_ID_BYTE0
XSFL_MICRON_BP_BITS_MASK
XSFL_CONFIG_REG2_VOLATILE_ADDR_MX
Controller Type.
XSFL_OSPI_CNTRL
Flag to use DMA or not.
Referenced by SflReadWriteExample, XSfl_FlashInit.
XSFL_BROKEN_DMA
Max Byte count in Stig Mode.
Referenced by SflReadWriteExample, XSfl_FlashNonBlockingReadProcess, XSfl_FlashReadProcess.
XSFL_MAX_STIG_BYTE_CNT
XSFL_QSPI_FLASH
XSFL_OSPI_FLASH
XILSFL_CONTROL_H
< prevent circular inclusions
by using protection macros
XSFL_COMMAND_OFFSET
XSFL_ADDRESS_OFFSET
XSFL_ADDRESS_SIZE_OFFSET
XSFL_DUMMY_OFFSET
XSFL_FLASH_DUMMY_CYCLES_0
XSFL_FLASH_DUMMY_CYCLES_8
XSFL_FLASH_DUMMY_CYCLES_10
XSFL_FLASH_DUMMY_CYCLES_16
XSFL_FLASH_DUMMY_CYCLES_20
XSFL_FLASH_DUMMY_CYCLES_21
XSFL_FLASH_FREQUENCY_166_MHZ
XSFL_FLASH_FREQUENCY_150_MHZ
XSFL_FLASH_FREQUENCY_133_MHZ
Flash frequency of 133 MHz.
XSFL_BUFFER_ARRAY_LEN