xilsfl_interface.c
u32 XSfl_FlashRegisterReadWrite(XSfl_Interface *SflInstancePtr, u8 *RxBfrPtr, u8 *TxBfrPtr, u32 *CmdBufferPtr, u8 Addrvalid)
This API can be used to Read/write to a flash register.
SflInstancePtr is a pointer to the interface driver component to use. RxBfrPtr is the pointer to store the read value from flash. TxBfrPtr is the pointer to value to be written into flash. CmdBufferPtr is the pointer that holds command, address and dummy. Addrvalid defines the specific read/write requires address or not. XST_SUCCESS if successful, else error code. This API can only be used for one flash at a time.
References XSfl_Msg::Addr, XSfl_Msg::Addrsize, XSfl_Msg::Addrvalid, XSfl_Msg::ByteCount, XSfl_Interface::CntrlInfo, XSfl_CntrlInfo::DeviceId, XSfl_Msg::DualByteOpCode, XSfl_Msg::Dummy, XSfl_FlashInfo::FlashIndex, XSfl_Msg::Opcode, XSfl_Msg::Proto, XSfl_Msg::RxBfrPtr, XSfl_CntrlInfo::SdrDdrMode, XSfl_Interface::SflFlashInfo, XSfl_CntrlInfo::Transfer, XSfl_Msg::TxBfrPtr.
Referenced by XSfl_FlashEnableQuadMode, XSfl_FlashSetSDRDDRMode.
u32 XSfl_FlashCmdTransfer(XSfl_Interface *SflInstancePtr, u8 Cmd)
This API can be used to transfer the command to the flash.
SflInstancePtr is a pointer to the interface driver component to use. Cmd is the command to be transferred to the flash. XST_SUCCESS if successful, else error code. This API can only be used for one flash at a time.
References XSfl_Msg::Addr, XSfl_Msg::Addrsize, XSfl_Msg::Addrvalid, XSfl_Msg::ByteCount, XSfl_Interface::CntrlInfo, XSfl_CntrlInfo::DeviceId, XSfl_Msg::DualByteOpCode, XSfl_Msg::Dummy, XSfl_FlashInfo::FlashIndex, XSfl_Msg::Opcode, XSfl_Msg::Proto, XSfl_Msg::RxBfrPtr, XSfl_CntrlInfo::SdrDdrMode, XSfl_Interface::SflFlashInfo, XSfl_CntrlInfo::Transfer, XSfl_Msg::TxBfrPtr.
Referenced by XSfl_FlashEnableQuadMode, XSfl_FlashEnterExit4BAddMode, XSfl_FlashPageWrite, XSfl_FlashSetSDRDDRMode, XSfl_SectorErase.
u32 XSfl_WaitforStatusDone(XSfl_Interface *SflInstancePtr)
This API can be used to read status of the flash status register.
SflInstancePtr is a pointer to the interface driver component to use. XST_SUCCESS if successful, else error code. This API can only be used for one flash at a time.
References XSfl_Msg::Addr, XSfl_Msg::Addrsize, XSfl_Msg::Addrvalid, XSfl_Msg::ByteCount, XSfl_Interface::CntrlInfo, XSfl_CntrlInfo::DeviceId, XSfl_Msg::DualByteOpCode, XSfl_Msg::Dummy, XSfl_FlashInfo::FlashIndex, XSfl_Msg::Opcode, XSfl_Msg::Proto, XSfl_Msg::RxBfrPtr, XSfl_CntrlInfo::SdrDdrMode, XSfl_Interface::SflFlashInfo, XSfl_CntrlInfo::Transfer, XSfl_Msg::TxBfrPtr.
Referenced by XSfl_FlashEnableQuadMode, XSfl_FlashEnterExit4BAddMode, XSfl_FlashPageWrite, XSfl_SectorErase.
u32 XSfl_GetRealAddr(XSfl_Interface *SflInstancePtr, u32 Address)
This functions translates the address based on the type of interconnection.
In case of stacked, this function asserts the corresponding slave select. SflInstancePtr is a pointer to the interface driver component to use. Address which is to be accessed (for erase, write or read) RealAddr is the translated address - for single it is unchanged; for stacked, the lower flash size is subtracted; In addition to get the actual address to work on flash this function also selects the CS based on the configuration detected.
References XSfl_Interface::CntrlInfo, XSfl_FlashInfo::ConnectionMode, XSfl_FlashInfo::FlashIndex, XSfl_CntrlInfo::SelectFlash, XSfl_Interface::SflFlashInfo, XSFL_SELECT_FLASH_CS0.
Referenced by XSfl_FlashNonBlockingReadProcess, XSfl_FlashPageWrite, XSfl_FlashReadProcess, XSfl_SectorErase.