xilsfl_control.h
XILSFL_CONTROL_H
< prevent circular inclusions
by using protection macros
XSFL_COMMAND_OFFSET
XSFL_ADDRESS_OFFSET
XSFL_ADDRESS_SIZE_OFFSET
XSFL_DUMMY_OFFSET
u32 XSfl_OspiInit(XSfl_Interface *Ptr, const XSfl_UserConfig *UserConfig)
u32 XSfl_FlashIdRead(XSfl_Interface *SflInstancePtr, u8 ChipSelNum, u8 *SflReadBuffer)
Reads the flash ID and identifies the flash in FCT table.
SflInstancePtr is a pointer to the XSfl_Interface driver component to use. ChipSelNum is the chip select number. SflReadBuffer is pointer to the read buffer to store flash id. XST_SUCCESS if successful, otherwise error code.
References XSfl_Msg::Addrsize, XSfl_Msg::Addrvalid, XSfl_Msg::ByteCount, XSfl_Interface::CntrlInfo, XSfl_CntrlInfo::DeviceId, XSfl_CntrlInfo::DeviceIdData, XSfl_Msg::Dummy, XSfl_FlashInfo::FlashIndex, XSfl_FlashInfo::FlashMake, XSfl_Msg::Opcode, XSfl_Msg::Proto, XSfl_Msg::RxBfrPtr, XSfl_CntrlInfo::SelectFlash, XSfl_Interface::SflFlashInfo, XSfl_CntrlInfo::Transfer, XSfl_Msg::TxBfrPtr, XSfl_CalculateFCTIndex, XSFL_FLASH_PROTO_1_1_1.
Referenced by XSfl_FlashInit.
u32 XSfl_CalculateFCTIndex(u32 ReadId, u32 *FCTIndex)
This function used to Identifies the flash in FCT table.
XST_SUCCESS if successful, otherwise XST_FAILURE.
Referenced by XSfl_FlashIdRead.
u32 XSfl_FlashSetSDRDDRMode(XSfl_Interface *SflInstancePtr, int Mode)
This API enters the flash device into Octal DDR mode or exit from octal DDR mode (switches to Extended SPI mode).
SflInstancePtr is a pointer to the XSfl_Interface driver component to use. Mode is either 1 or 0 if 1 then enter octal DDR mode if 0 exits. - XST_SUCCESS if successful. error code if it fails.
References XSfl_Interface::CntrlInfo, XSfl_FlashInfo::ConnectionMode, XFlashInfo::ExtOpCodeType, XSfl_FlashInfo::FlashIndex, XFlashInfo::FlashType, XSfl_CntrlInfo::SdrDdrMode, XSfl_CntrlInfo::SelectFlash, XSfl_CntrlInfo::SetSdrDdr, XSfl_Interface::SflFlashInfo, XSFL_DUAL_BYTE_OP_DISABLE, XSfl_FlashCmdTransfer, XSfl_FlashRegisterReadWrite, XSFL_SELECT_FLASH_CS0.
Referenced by XSfl_FlashInit.
u32 XSfl_FlashEnterExit4BAddMode(XSfl_Interface *SflInstancePtr, int Enable, u8 ChipSelNum)
This API enters the flash device into 4 bytes addressing mode.
As per the Micron spec, before issuing the command to enter into 4 byte addr mode, a write enable command is issued. SflInstancePtr is a pointer to the XSfl_Interface driver component to use. Enable is a either 1 or 0 if 1 then enters 4 byte if 0 exits. ChipSelNum is the chip select number. - XST_SUCCESS if successful. error code if it fails.
References XSfl_Interface::CntrlInfo, XSfl_FlashInfo::ConnectionMode, XSfl_FlashInfo::FlashMake, XSfl_CntrlInfo::SelectFlash, XSfl_Interface::SflFlashInfo, XSfl_FlashCmdTransfer, XSfl_WaitforStatusDone.
Referenced by XSfl_FlashInit.
u32 XSfl_GetRealAddr(XSfl_Interface *SflInstancePtr, u32 Address)
This functions translates the address based on the type of interconnection.
In case of stacked, this function asserts the corresponding slave select. SflInstancePtr is a pointer to the interface driver component to use. Address which is to be accessed (for erase, write or read) RealAddr is the translated address - for single it is unchanged; for stacked, the lower flash size is subtracted; In addition to get the actual address to work on flash this function also selects the CS based on the configuration detected.
References XSfl_Interface::CntrlInfo, XSfl_FlashInfo::ConnectionMode, XSfl_FlashInfo::FlashIndex, XSfl_CntrlInfo::SelectFlash, XSfl_Interface::SflFlashInfo, XSFL_SELECT_FLASH_CS0.
Referenced by XSfl_FlashNonBlockingReadProcess, XSfl_FlashPageWrite, XSfl_FlashReadProcess, XSfl_SectorErase.
u32 XSfl_SectorErase(XSfl_Interface *SflInstancePtr, u32 Address)
This function used to erase the sectors of the serial nor flash connected to the specific interface.
Sfl_Handler is a pointer to the XSfl interface component to use. Address contains the address of the first sector which needs to be erased. XST_SUCCESS if successful, else error code.
References XSfl_Msg::Addr, XSfl_Msg::Addrsize, XSfl_FlashInfo::AddrSize, XSfl_Msg::Addrvalid, XSfl_Msg::ByteCount, XSfl_Interface::CntrlInfo, XSfl_CntrlInfo::DeviceId, XSfl_Msg::DualByteOpCode, XSfl_Msg::Dummy, XSfl_FlashInfo::FlashIndex, XSfl_Msg::Opcode, XSfl_Msg::Proto, XSfl_Msg::RxBfrPtr, XSfl_CntrlInfo::SdrDdrMode, XSfl_Interface::SflFlashInfo, XSfl_CntrlInfo::Transfer, XSfl_Msg::TxBfrPtr, XSfl_FlashCmdTransfer, XSfl_GetRealAddr, XSfl_WaitforStatusDone.
Referenced by XSfl_FlashErase.
u32 XSfl_FlashPageWrite(XSfl_Interface *SflInstancePtr, u32 Address, u32 ByteCount, u8 *WriteBfrPtr)
This function writes to the serial nor flash connected to the specific interface.
Sfl_Handler is a index to the Sfl interface component to use. Address contains the address of the first page which needs to be written. ByteCount contains the number of bytes to write. WriteBfrPtr is Pointer to the write buffer (which is to be transmitted) XST_SUCCESS if successful, else Error code.
References XSfl_Msg::Addr, XSfl_Msg::Addrsize, XSfl_FlashInfo::AddrSize, XSfl_Msg::Addrvalid, XSfl_Msg::ByteCount, XSfl_Interface::CntrlInfo, XSfl_CntrlInfo::DeviceId, XSfl_Msg::DualByteOpCode, XSfl_Msg::Dummy, XSfl_FlashInfo::FlashIndex, XSfl_Msg::Opcode, XSfl_Msg::Proto, XSfl_Msg::RxBfrPtr, XSfl_CntrlInfo::SdrDdrMode, XSfl_Interface::SflFlashInfo, XSfl_CntrlInfo::Transfer, XSfl_Msg::TxBfrPtr, XSfl_FlashCmdTransfer, XSfl_GetRealAddr, XSfl_WaitforStatusDone.
Referenced by XSfl_FlashWrite.
u32 XSfl_FlashReadProcess(XSfl_Interface *SflInstancePtr, u32 Address, u32 ByteCount, u8 *ReadBfrPtr, u64 RxAddr64bit)
This function performs read from the serial nor flash connected to specific interface.
Sfl_Handler is a index to the XSfl interface component to use. Address contains the address of the flash that needs to be read. ByteCount contains the total size to be erased. ReadBfrPtr is the pointer to the read buffer to which valid received data should be written RxAddr64bit is of the 64bit address of destination read buffer to which valid received data should be written. XST_SUCCESS if successful, else Error code.
References XSfl_Msg::Addr, XSfl_Msg::Addrsize, XSfl_FlashInfo::AddrSize, XSfl_Msg::Addrvalid, XSfl_CntrlInfo::BusWidth, XSfl_Msg::ByteCount, XSfl_Interface::CntrlInfo, XSfl_FlashInfo::ConnectionMode, XSfl_CntrlInfo::DeviceId, XSfl_Msg::DualByteOpCode, XSfl_Msg::Dummy, XSfl_FlashInfo::FlashIndex, XSfl_Msg::Opcode, XSfl_CntrlInfo::OpMode, XFlashInfo::Proto, XSfl_Msg::Proto, XSfl_Interface::Quirks, XSfl_Msg::RxAddr64bit, XSfl_Msg::RxBfrPtr, XSfl_CntrlInfo::SdrDdrMode, XSfl_Interface::SflFlashInfo, XSfl_CntrlInfo::Transfer, XSfl_Msg::TxBfrPtr, XSfl_Msg::Xfer64bit, XSFL_BROKEN_DMA, XSfl_GetRealAddr, XSFL_RXADDR_OVER_32BIT.
Referenced by XSfl_FlashRead.
u32 XSfl_FlashTransferDone(XSfl_Interface *SflInstancePtr)
This function used to check read completion status the serial Flash connected to the Specific interface.
Sfl_Handler is a pointer to the XSfl interface driver component to use. XST_SUCCESS if successful, else error code.
References XSfl_Interface::CntrlInfo, XSfl_CntrlInfo::TransferDone.
Referenced by XSfl_FlashReadDone.
u32 XSfl_WaitforStatusDone(XSfl_Interface *SflInstancePtr)
This API can be used to read status of the flash status register.
SflInstancePtr is a pointer to the interface driver component to use. XST_SUCCESS if successful, else error code. This API can only be used for one flash at a time.
References XSfl_Msg::Addr, XSfl_Msg::Addrsize, XSfl_Msg::Addrvalid, XSfl_Msg::ByteCount, XSfl_Interface::CntrlInfo, XSfl_CntrlInfo::DeviceId, XSfl_Msg::DualByteOpCode, XSfl_Msg::Dummy, XSfl_FlashInfo::FlashIndex, XSfl_Msg::Opcode, XSfl_Msg::Proto, XSfl_Msg::RxBfrPtr, XSfl_CntrlInfo::SdrDdrMode, XSfl_Interface::SflFlashInfo, XSfl_CntrlInfo::Transfer, XSfl_Msg::TxBfrPtr.
Referenced by XSfl_FlashEnableQuadMode, XSfl_FlashEnterExit4BAddMode, XSfl_FlashPageWrite, XSfl_SectorErase.
u32 XSfl_FlashRegisterReadWrite(XSfl_Interface *SflInstancePtr, u8 *RxBfrPtr, u8 *TxBfrPtr, u32 *CmdBufferPtr, u8 Addrvalid)
This API can be used to Read/write to a flash register.
SflInstancePtr is a pointer to the interface driver component to use. RxBfrPtr is the pointer to store the read value from flash. TxBfrPtr is the pointer to value to be written into flash. CmdBufferPtr is the pointer that holds command, address and dummy. Addrvalid defines the specific read/write requires address or not. XST_SUCCESS if successful, else error code. This API can only be used for one flash at a time.
References XSfl_Msg::Addr, XSfl_Msg::Addrsize, XSfl_Msg::Addrvalid, XSfl_Msg::ByteCount, XSfl_Interface::CntrlInfo, XSfl_CntrlInfo::DeviceId, XSfl_Msg::DualByteOpCode, XSfl_Msg::Dummy, XSfl_FlashInfo::FlashIndex, XSfl_Msg::Opcode, XSfl_Msg::Proto, XSfl_Msg::RxBfrPtr, XSfl_CntrlInfo::SdrDdrMode, XSfl_Interface::SflFlashInfo, XSfl_CntrlInfo::Transfer, XSfl_Msg::TxBfrPtr.
Referenced by XSfl_FlashEnableQuadMode, XSfl_FlashSetSDRDDRMode.
u32 XSfl_FlashCmdTransfer(XSfl_Interface *SflInstancePtr, u8 Cmd)
This API can be used to transfer the command to the flash.
SflInstancePtr is a pointer to the interface driver component to use. Cmd is the command to be transferred to the flash. XST_SUCCESS if successful, else error code. This API can only be used for one flash at a time.
References XSfl_Msg::Addr, XSfl_Msg::Addrsize, XSfl_Msg::Addrvalid, XSfl_Msg::ByteCount, XSfl_Interface::CntrlInfo, XSfl_CntrlInfo::DeviceId, XSfl_Msg::DualByteOpCode, XSfl_Msg::Dummy, XSfl_FlashInfo::FlashIndex, XSfl_Msg::Opcode, XSfl_Msg::Proto, XSfl_Msg::RxBfrPtr, XSfl_CntrlInfo::SdrDdrMode, XSfl_Interface::SflFlashInfo, XSfl_CntrlInfo::Transfer, XSfl_Msg::TxBfrPtr.
Referenced by XSfl_FlashEnableQuadMode, XSfl_FlashEnterExit4BAddMode, XSfl_FlashPageWrite, XSfl_FlashSetSDRDDRMode, XSfl_SectorErase.
u32 XSfl_FlashNonBlockingReadProcess(XSfl_Interface *SflInstancePtr, u32 Address, u32 ByteCount, u8 *ReadBfrPtr, u64 RxAddr64bit)
This function performs non-blocking read from the serial nor flash connected to specific interface.
Sfl_Handler is a index to the XSfl interface component to use. Address contains the address of the flash that needs to be read. ByteCount contains the total size to be erased. ReadBfrPtr is the pointer to the read buffer to which valid received data should be written RxAddr64bit is of the 64bit address of destination read buffer to which valid received data should be written. XST_SUCCESS if successful, else Error code.
References XSfl_Msg::Addr, XSfl_Msg::Addrsize, XSfl_FlashInfo::AddrSize, XSfl_Msg::Addrvalid, XSfl_CntrlInfo::BusWidth, XSfl_Msg::ByteCount, XSfl_Interface::CntrlInfo, XSfl_FlashInfo::ConnectionMode, XSfl_CntrlInfo::DeviceId, XSfl_Msg::DualByteOpCode, XSfl_Msg::Dummy, XSfl_FlashInfo::FlashIndex, XSfl_CntrlInfo::NonBlockingTransfer, XSfl_Msg::Opcode, XSfl_CntrlInfo::OpMode, XFlashInfo::Proto, XSfl_Msg::Proto, XSfl_Interface::Quirks, XSfl_Msg::RxAddr64bit, XSfl_Msg::RxBfrPtr, XSfl_CntrlInfo::SdrDdrMode, XSfl_Interface::SflFlashInfo, XSfl_CntrlInfo::TransferDone, XSfl_Msg::TxBfrPtr, XSfl_Msg::Xfer64bit, XSFL_BROKEN_DMA, XSfl_GetRealAddr, XSFL_RXADDR_OVER_32BIT.
Referenced by XSfl_FlashReadStart.
u32 XSfl_FlashEnableQuadMode(XSfl_Interface *SflInstancePtr, u8 ChipSelNum)
This function enables Quad mode for flashes which require to enable it before using Quad commands.
SflInstancePtr is a pointer to the interface driver component to use. ChipSelNum is the chip select number. XST_SUCCESS if successful, else XST_FAILURE.
References XSfl_Interface::CntrlInfo, XSfl_FlashInfo::FlashMake, XSfl_CntrlInfo::SelectFlash, XSfl_Interface::SflFlashInfo, XSfl_FlashCmdTransfer, XSfl_FlashRegisterReadWrite, XSfl_WaitforStatusDone, XSFL_WB_QUAD_ENABLE_BIT, XSFL_WB_READ_STATUS_REG2_CMD, XSFL_WB_WRITE_STATUS_REG2_CMD, XSFL_WINBOND_ID_BYTE0.
Referenced by XSfl_FlashInit.