xilsfl.c
u32 XSfl_FlashInit(u8 *SflHandler, XSfl_UserConfig SflUserOptions, u8 ControllerInfo)
This function initializes controller interface and serial nor flash connected.
SflUserOptions contains the controller and flash configuration info. ControllerInfo contains the type of controller. SFL index on successful initialization, else Error codes.
References XSfl_FlashInfo::AddrSize, XSfl_CntrlInfo::BusWidth, XSfl_CntrlInfo::ChipSelectNum, XSfl_Interface::CntrlInfo, XSfl_CntrlInfo::CntrlType, XSfl_FlashInfo::ConnectionMode, XSfl_CntrlInfo::DeviceReset, XSfl_FlashInfo::FlashIndex, XFlashInfo::FlashType, XSfl_CntrlInfo::RefClockHz, XSfl_CntrlInfo::SdrDdrMode, XFlashInfo::SdrMaxFreq, XSfl_Interface::SflFlashInfo, XSFL_EDGE_MODE_SDR_PHY, XSfl_FlashEnableQuadMode, XSfl_FlashEnterExit4BAddMode, XSfl_FlashIdRead, XSfl_FlashSetSDRDDRMode, XSFL_OSPI_CNTRL, XSFL_SELECT_FLASH_CS0.
Referenced by SflReadWriteExample.
u32 XSfl_FlashReadStart(u8 SflHandler, u32 Address, u32 ByteCount, u8 *ReadBfrPtr, u64 RxAddr64bit)
This function reads from the flash connected to the specific interface.
SflHandler is a index to the Sfl interface component to use. Address contains the address of the flash that needs to be read. ByteCount contains the total size to be erased. ReadBfrPtr is the pointer to the read buffer to which valid received data should be written RxAddr64bit is of the 64bit address of destination read buffer to which valid received data should be written. XST_SUCCESS if successful, else error code.
References XSfl_FlashNonBlockingReadProcess.
Referenced by SflReadWriteExample.
u32 XSfl_FlashReadDone(u8 SflHandler)
This function used to check read completion status of serial Flash connected to the Specific interface.
SflHandler is a pointer to the Sfl interface driver component to use. XST_SUCCESS if successful, else error code.
References XSfl_FlashTransferDone.
Referenced by SflReadWriteExample.
u32 XSfl_FlashRead(u8 SflHandler, u32 Address, u32 ByteCount, u8 *ReadBfrPtr, u64 RxAddr64bit)
This function performs read from the flash.
SflHandler is a index to the Sfl interface component to use. Address contains the address of the flash that needs to be read. ByteCount contains the total size to be erased. ReadBfrPtr is the pointer to the read buffer to which valid received data should be written RxAddr64bit is of the 64bit address of destination read buffer to which valid received data should be written. XST_SUCCESS if successful, else error code.
References XSfl_FlashReadProcess.
Referenced by SflReadWriteExample.
u32 XSfl_FlashWrite(u8 SflHandler, u32 Address, u32 ByteCount, u8 *WriteBfrPtr)
This function writes to the serial nor flash connected to the interface driver.
SflHandler is a index to the Sfl interface component to use. Address contains the address to write data to in the Flash. ByteCount contains the number of bytes to be write. WriteBfrPtr is Pointer to the write buffer (which is to be transmitted) XST_SUCCESS if successful, else error code.
References XSfl_Interface::SflFlashInfo, XSfl_FlashPageWrite.
Referenced by SflReadWriteExample.
u32 XSfl_FlashErase(u8 SflHandler, u32 Address, u32 ByteCount)
This function erases the serial nor flash connected to the specific interface.
SflHandler is a pointer to the Sfl interface component to use. Address is the sector offset address of the flash at which data to be erased. ByteCount contains the total size to be erased. XST_SUCCESS if successful, else error code.
References XSfl_Interface::SflFlashInfo, XSfl_SectorErase.
Referenced by SflReadWriteExample.
u32 XSfl_FlashGetInfo(u8 SflHandler, u8 Option, u32 *DataPtr)
This function used to get details serial Flash connected to the Specific interface.
SflHandler is a pointer to the Sfl interface driver component to use. Option is to get specific details of the flash. DataPtr is the pointer to the flash info to be copied. XST_SUCCESS if successful, else error code.
References XSfl_FlashInfo::FlashIndex, XFlashInfo::FlashType, XSfl_Interface::SflFlashInfo.
Referenced by SflReadWriteExample.
XSfl SflInstance