xilsfl.h
XSFL_DUAL_BYTE_OP_DISABLE
Macros to enable/disable Dual Byte opcode.
Referenced by XSfl_FlashSetSDRDDRMode.
XSFL_DUAL_BYTE_OP_INVERT
XSFL_DUAL_BYTE_OP_SAME
XSFL_EDGE_MODE_SDR_PHY
Macros to select different edge modes like SDR+NON-PHY, SDR+PHY and DDR+PHY.
Referenced by XSfl_FlashInit.
XSFL_EDGE_MODE_SDR_NON_PHY
XSFL_EDGE_MODE_DDR_PHY
XSFL_SELECT_FLASH_CS0
Macros to select CS0 and CS1.
Referenced by SflReadWriteExample, XSfl_FlashInit, XSfl_FlashSetSDRDDRMode, XSfl_GetRealAddr.
XSFL_SELECT_FLASH_CS1
XSFL_CONNECTION_MODE_SINGLE
Macros to select SINGLE, STACKED and PARALLEL connection modes.
XSFL_CONNECTION_MODE_STACKED
XSFL_FLASH_PROTO_1_1_1
Macros to select Read and Write prototype.
Referenced by XSfl_FlashIdRead.
XSFL_FLASH_PROTO_1_0_1
XSFL_FLASH_PROTO_1_1_2
XSFL_FLASH_PROTO_1_1_8
XSFL_FLASH_PROTO_1_8_8
XSFL_FLASH_PROTO_8_8_8
XSFL_FLASH_PROTO_8_0_0
XSFL_FLASH_PROTO_8_8_0
XSFL_FLASH_PROTO_8_0_8
XSFL_FLASH_PROTO_1_1_4
XSFL_FLASH_PROTO_4_4_4
XSFL_FLASH_ID
XSFL_DEVICE_SIZE
XSFL_SECT_SIZE
XSFL_PAGE_SIZE
XSFL_FLASH_TYPE
XSFL_X1_BUS_WIDTH
XSFL_X2_BUS_WIDTH
XSFL_X4_BUS_WIDTH
XSFL_X8_BUS_WIDTH
XSFL_WB_QUAD_ENABLE_BIT
Winbond QE bit: Status Register-2 bit[1] (SR2[1]).
Setting this bit enables Quad SPI transfers.
Referenced by XSfl_FlashEnableQuadMode.
typedef union XSfl_UserConfig XSfl_UserConfig
This typedef contains configuration information for a flash/controller device.
The user is required to allocate a variable of this type. A variable of this type is then passed to the library API functions.
u32 XSfl_FlashInit(u8 *SflHandler, XSfl_UserConfig SflUserOptions, u8 ControllerInfo)
This function initializes controller interface and serial nor flash connected.
SflUserOptions contains the controller and flash configuration info. ControllerInfo contains the type of controller. SFL index on successful initialization, else Error codes.
References XSfl_FlashInfo::AddrSize, XSfl_CntrlInfo::BusWidth, XSfl_CntrlInfo::ChipSelectNum, XSfl_Interface::CntrlInfo, XSfl_CntrlInfo::CntrlType, XSfl_FlashInfo::ConnectionMode, XSfl_CntrlInfo::DeviceReset, XSfl_FlashInfo::FlashIndex, XFlashInfo::FlashType, XSfl_CntrlInfo::RefClockHz, XSfl_CntrlInfo::SdrDdrMode, XFlashInfo::SdrMaxFreq, XSfl_Interface::SflFlashInfo, XSFL_EDGE_MODE_SDR_PHY, XSfl_FlashEnableQuadMode, XSfl_FlashEnterExit4BAddMode, XSfl_FlashIdRead, XSfl_FlashSetSDRDDRMode, XSFL_OSPI_CNTRL, XSFL_SELECT_FLASH_CS0.
Referenced by SflReadWriteExample.
u32 XSfl_FlashErase(u8 SflHandler, u32 Address, u32 ByteCount)
This function erases the serial nor flash connected to the specific interface.
SflHandler is a pointer to the Sfl interface component to use. Address is the sector offset address of the flash at which data to be erased. ByteCount contains the total size to be erased. XST_SUCCESS if successful, else error code.
References XSfl_Interface::SflFlashInfo, XSfl_SectorErase.
Referenced by SflReadWriteExample.
u32 XSfl_FlashWrite(u8 SflHandler, u32 Address, u32 ByteCount, u8 *WriteBfrPtr)
This function writes to the serial nor flash connected to the interface driver.
SflHandler is a index to the Sfl interface component to use. Address contains the address to write data to in the Flash. ByteCount contains the number of bytes to be write. WriteBfrPtr is Pointer to the write buffer (which is to be transmitted) XST_SUCCESS if successful, else error code.
References XSfl_Interface::SflFlashInfo, XSfl_FlashPageWrite.
Referenced by SflReadWriteExample.
u32 XSfl_FlashReadStart(u8 SflHandler, u32 Address, u32 ByteCount, u8 *ReadBfrPtr, u64 RxAddr64bit)
This function reads from the flash connected to the specific interface.
SflHandler is a index to the Sfl interface component to use. Address contains the address of the flash that needs to be read. ByteCount contains the total size to be erased. ReadBfrPtr is the pointer to the read buffer to which valid received data should be written RxAddr64bit is of the 64bit address of destination read buffer to which valid received data should be written. XST_SUCCESS if successful, else error code.
References XSfl_FlashNonBlockingReadProcess.
Referenced by SflReadWriteExample.
u32 XSfl_FlashReadDone(u8 SflHandler)
This function used to check read completion status of serial Flash connected to the Specific interface.
SflHandler is a pointer to the Sfl interface driver component to use. XST_SUCCESS if successful, else error code.
References XSfl_FlashTransferDone.
Referenced by SflReadWriteExample.
u32 XSfl_FlashGetInfo(u8 SflHandler, u8 Option, u32 *DataPtr)
This function used to get details serial Flash connected to the Specific interface.
SflHandler is a pointer to the Sfl interface driver component to use. Option is to get specific details of the flash. DataPtr is the pointer to the flash info to be copied. XST_SUCCESS if successful, else error code.
References XSfl_FlashInfo::FlashIndex, XFlashInfo::FlashType, XSfl_Interface::SflFlashInfo.
Referenced by SflReadWriteExample.
u32 XSfl_FlashRead(u8 SflHandler, u32 Address, u32 ByteCount, u8 *ReadBfrPtr, u64 RxAddr64bit)
This function performs read from the flash.
SflHandler is a index to the Sfl interface component to use. Address contains the address of the flash that needs to be read. ByteCount contains the total size to be erased. ReadBfrPtr is the pointer to the read buffer to which valid received data should be written RxAddr64bit is of the 64bit address of destination read buffer to which valid received data should be written. XST_SUCCESS if successful, else error code.
References XSfl_FlashReadProcess.
Referenced by SflReadWriteExample.
XSFL_NUM_INSTANCES
XSFL_RXADDR_OVER_32BIT
Rx address over 32 bit.
Referenced by XSfl_FlashNonBlockingReadProcess, XSfl_FlashReadProcess.
XSFL_SDR_NON_PHY_MAX_FREQ
XSFL_WRITE_STATUS_CMD
XSFL_WRITE_DISABLE_CMD
XSFL_WRITE_ENABLE_CMD
XSFL_BULK_ERASE_CMD
XSFL_DIE_ERASE_CMD
XSFL_READ_ID
XSFL_READ_CONFIG_CMD
XSFL_WRITE_CONFIG_CMD
XSFL_READ_STATUS_CMD
XSFL_READ_FLAG_STATUS_CMD
XSFL_READ_CMD_4B
XSFL_WRITE_CMD_4B
XSFL_SEC_ERASE_CMD_4B
XSFL_READ_CMD_OCTAL_4B
XSFL_READ_CMD_OCTAL_IO_4B
XSFL_READ_CMD_OCTAL_DDR
XSFL_WRITE_CMD_OCTAL_4B
XSFL_ENTER_4B_ADDR_MODE
XSFL_EXIT_4B_ADDR_MODE
XSFL_WRITE_CONFIG_REG
XSFL_READ_CONFIG_REG
XSFL_DUAL_READ_CMD
XSFL_QUAD_READ_CMD
XSFL_DUAL_READ_CMD_4B
XSFL_QUAD_READ_CMD_4B
XSFL_QUAD_WRITE_CMD
XSFL_DUAL_WRITE_CMD
XSFL_QUAD_SEC_ERASE_CMD
XSFL_WRITE_CMD
XSFL_READ_CMD
XSFL_NO_CMD
No command / dummy command value (0x00)
XSFL_WB_READ_STATUS_REG2_CMD
Command for reading the status register 2.
This command is used to retrieve the status of the second status register. Winbond Read SR2 (0x35) coincides with XSFL_READ_CONFIG_CMD.
Referenced by XSfl_FlashEnableQuadMode.
XSFL_WB_WRITE_STATUS_REG2_CMD
Write Status Register 2 command.
This command is used to write the status register 2.
Referenced by XSfl_FlashEnableQuadMode.
XSFL_WINBOND_ID_BYTE0
The first byte of the Winbond ID.
Referenced by XSfl_FlashEnableQuadMode.
XSFL_SIXTEENMB
XSFL_FLASH_PAGE_SIZE_256
XSFL_FLASH_SECTOR_SIZE_4KB
XSFL_FLASH_SECTOR_SIZE_256KB
XSFL_FLASH_SECTOR_SIZE_64KB
XSFL_FLASH_SECTOR_SIZE_128KB
XSFL_FLASH_DEVICE_SIZE_128M
XSFL_FLASH_DEVICE_SIZE_256M
XSFL_FLASH_DEVICE_SIZE_512M
XSFL_FLASH_DEVICE_SIZE_1G
XSFL_FLASH_DEVICE_SIZE_2G
XSFL_MICRON_OCTAL_ID_BYTE0
XSFL_MICRON_BP_BITS_MASK
XSFL_CONFIG_REG2_VOLATILE_ADDR_MX
Controller Type.
XSFL_OSPI_CNTRL
Flag to use DMA or not.
Referenced by SflReadWriteExample, XSfl_FlashInit.
XSFL_BROKEN_DMA
Max Byte count in Stig Mode.
Referenced by SflReadWriteExample, XSfl_FlashNonBlockingReadProcess, XSfl_FlashReadProcess.
XSFL_MAX_STIG_BYTE_CNT
XSFL_QSPI_FLASH
XSFL_OSPI_FLASH