xnvm_mailbox_apis
int XNvm_SendRequest(const XNvm_ClientInstance *InstancePtr, u32 *PayloadBuf, u32 PayloadLen, u32 *ResponseBuf, u32 ResponseLen)
This function sends request to PLM through either SMC or IPI mailbox based on the execution environment.
For EL1 non-secure AArch64 applications, SMC is used. For other environments, IPI mailbox is used. InstancePtr Pointer to the client instance PayloadBuf Pointer to the payload message PayloadLen Length of the payload message ResponseBuf Pointer to store response values (can be NULL) ResponseLen Length of response buffer (pass 0U when ResponseBuf is NULL) XST_SUCCESS If the request is successfulXST_FAILURE If there is a failureXST_INVALID_PARAM If input parameters are invalid This is a generic API that internally handles SMC or Mailbox communication based on the build configuration.
References XNvm_ProcessMailbox.
Referenced by XNvm_BbramLockUsrDataWrite, XNvm_BbramReadUsrData, XNvm_BbramWriteAesKey, XNvm_BbramWriteUsrData, XNvm_BbramZeroize, XNvm_EfuseAesKeyCrcCheck, XNvm_EfuseReadBootEnvCtrlBits, XNvm_EfuseReadDecOnly, XNvm_EfuseReadDna, XNvm_EfuseReadIv, XNvm_EfuseReadMiscCtrlBits, XNvm_EfuseReadOffchipRevokeId, XNvm_EfuseReadPpkHash, XNvm_EfuseReadPuf, XNvm_EfuseReadPufSecCtrlBits, XNvm_EfuseReadRevocationId, XNvm_EfuseReadSecCtrlBits, XNvm_EfuseReadSecMisc1Bits, XNvm_EfuseReadUserFuses, XNvm_EfuseRevokePpk, XNvm_EfuseWrite, XNvm_EfuseWriteIVs, XNvm_EfuseWritePuf, XNvm_EfuseWriteRevocationId, XNvm_EfuseWriteUserFuses.
int XNvm_ProcessMailbox(XMailbox *MailboxPtr, u32 *MsgPtr, u32 MsgLen)
This function sends IPI request to the target module and gets the response from it.
MailboxPtr Pointer to mailbox instance MsgPtr Pointer to the payload message MsgLen Length of the message XST_SUCCESS If the IPI send and receive is successfulXST_FAILURE If there is a failure Payload consists of API id and call arguments to be written in IPI buffer
Referenced by XNvm_EfuseAesKeyCrcCheck, XNvm_EfuseReadBootEnvCtrlBits, XNvm_EfuseReadBootModeDis, XNvm_EfuseReadDecOnly, XNvm_EfuseReadDmeMode, XNvm_EfuseReadDmeRevokeId, XNvm_EfuseReadDna, XNvm_EfuseReadFipsInfoBits, XNvm_EfuseReadIv, XNvm_EfuseReadMiscCtrlBits, XNvm_EfuseReadOffchipRevokeId, XNvm_EfuseReadPpkHash, XNvm_EfuseReadPuf, XNvm_EfuseReadPufSecCtrlBits, XNvm_EfuseReadRevocationId, XNvm_EfuseReadRomRsvdBits, XNvm_EfuseReadSecCtrlBits, XNvm_EfuseReadSecMisc1Bits, XNvm_EfuseReadUserFuses, XNvm_EfuseWrite, XNvm_EfuseWriteBootEnvCtrlBits, XNvm_EfuseWriteBootModeDis, XNvm_EfuseWriteDecOnly, XNvm_EfuseWriteDiceUds, XNvm_EfuseWriteDmeMode, XNvm_EfuseWriteFipsInfo, XNvm_EfuseWriteGlitchConfigBits, XNvm_EfuseWriteIVs, XNvm_EfuseWriteMiscCtrlBits, XNvm_EfuseWriteOffChipRevocationId, XNvm_EfuseWritePlmUpdate, XNvm_EfuseWritePuf, XNvm_EfuseWritePufCtrlBits, XNvm_EfuseWriteRevocationId, XNvm_EfuseWriteRomRsvdBits, XNvm_EfuseWriteSecCtrlBits, XNvm_EfuseWriteSecMisc1Bits, XNvm_SendRequest, XNvm_WriteDmePrivateKey, XNvm_WriteDmeRevoke.
int XNvm_ClientInit(XNvm_ClientInstance *const InstancePtr, XMailbox *const MailboxPtr)
This function sets the instance of mailbox.
InstancePtr Pointer to the client instance MailboxPtr Pointer to the mailbox instance XST_SUCCESS On successful initializationXST_FAILURE On failure
Referenced by main.