xnvm_util_apis
XNVM_POLL_TIMEOUT
Poll timeout during CRC verification.
Referenced by XNvm_EfuseCheckAesKeyCrc.
XNvm_EfuseOpMode
eFuse read mode
XNvm_EfuseRdMode
eFuse normal read
u32 XNvm_AesCrcCalc(const u32 *Key)
This function calculates CRC of AES key.
Key - Pointer to the little-endian formatted key for which CRC has to be calculated. CRC of AES key. Key - Pointer to the key for which CRC has to be calculated. CRC of AES key.
References REVERSE_POLYNOMIAL.
int XNvm_EfuseCheckAesKeyCrc(u32 CrcRegOffSet, u32 CrcDoneMask, u32 CrcPassMask, u32 Crc)
This function performs the CRC check of AES key/User0 key/User1 key.
CrcRegOffSet - Register offset of respective CRC register CrcDoneMask - Respective CRC done mask in status register CrcPassMask - Respective CRC pass mask in status register Crc - A 32 bit CRC value of an expected AES key. XST_SUCCESS - On successful CRC check.XNVM_EFUSE_ERR_CRC_VERIFICATION - If AES boot key integrity check is failed.XST_FAILURE - If AES boot key integrity check has not finished. Expected CRC calculation steps: Convert the key provided at XNVM_EFUSE_AES_KEY into hexadecimal little-endian format.Calculate the CRC on this little-endian formatted AES key using XNvm_AesCrcCalc() function.Provide the calculated CRC as the value of expected CRC. CrcRegOffSet - Register offset of respective CRC register CrcDoneMask - Respective CRC done mask in status register CrcPassMask - Respective CRC pass mask in status register Crc - A 32 bit CRC value of an expected AES key. XST_SUCCESS On successful CRC check.XNVM_EFUSE_ERR_CRC_VERIFICATION If AES boot key integrity check is failed.XST_FAILURE If AES boot key integrity check has not finished. For Calculating the CRC of the AES key use the XNvm_AesCrcCalc() function.
References XNVM_EFUSE_CTRL_BASEADDR, XNVM_EFUSE_CTRL_WR_LOCKED, XNVM_EFUSE_ERR_CRC_VERIFICATION, XNVM_EFUSE_STATUS_REG_OFFSET, XNVM_EFUSE_WR_LOCK_REG_OFFSET, XNVM_EFUSE_WRITE_LOCKED, XNvm_EfuseLockController, XNvm_EfuseReadReg, XNvm_EfuseUnlockController, XNvm_EfuseWriteReg, XNVM_POLL_TIMEOUT.
Referenced by XNvm_EfuseValidateAesKeyWriteReq, XNvm_EfuseValidateDecOnlyRequest, XNvm_EfuseWriteUds.
int XNvm_ZeroizeAndVerify(u8 *DataPtr, const u32 Length)
This function zeroizes the memory and verifies that the memory has been correctly zeroized.
DataPtr Pointer to the memory which need to be zeroized. Length Length of the data in bytes. XST_SUCCESS: If Zeroization is successful.XST_FAILURE: If Zeroization is not successful. This function zeroizes the memory and verifies that the memory has been correctly zeroized. DataPtr Pointer to the memory which need to be zeroized. Length Length of the data in bytes. XST_SUCCESS If Zeroization is successful.XST_FAILURE If Zeroization is not successful.
Referenced by XNvm_EfuseReadIv, XNvm_EfuseReadPuf.
u32 XNvm_EfuseReadReg(u32 BaseAddress, u32 RegOffset)
This function reads the given register.
BaseAddress - eFuse controller base address. RegOffset - Register offset from the base address. The 32-bit value of the register. BaseAddress is the eFuse controller base address. RegOffset is the register offset from the base address. The 32-bit value of the register.
Referenced by XNvm_EfuseCacheReload, XNvm_EfuseCheckAesKeyCrc, XNvm_EfuseCheckForTBits, XNvm_EfuseCheckZeros, XNvm_EfuseDisablePowerDown, XNvm_EfuseDisableProgramming, XNvm_EfuseEnableProgramming, XNvm_EfuseIsPufHelperDataEmpty, XNvm_EfuseLockController, XNvm_EfuseReadProtectionBits, XNvm_EfuseResetReadMode, XNvm_EfuseSetReadMode, XNvm_EfuseUnlockController, XNvm_EfuseValidateAesKeyWriteReq, XNvm_EfuseValidateDecOnlyRequest, XNvm_EfuseValidateFipsInfo, XNvm_EfuseValidatePpkHashWriteReq, XNvm_EfuseWriteCrc, XNvm_EfuseWritePuf, XNvm_EfuseWriteUds, XNvm_IsDmeModeEn.
void XNvm_EfuseWriteReg(u32 BaseAddress, u32 RegOffset, u32 Data)
This function writes the value into the given register.
BaseAddress - eFuse controller base address. RegOffset - Register offset from the base address. Data - 32-bit value to be written to the register. BaseAddress is the eFuse controller base address. RegOffset is the register offset from the base address. Data is the 32-bit value to be written to the register.
Referenced by XNvm_EfuseCacheReload, XNvm_EfuseCheckAesKeyCrc, XNvm_EfuseDisablePowerDown, XNvm_EfuseEnableProgramming, XNvm_EfuseInitTimers, XNvm_EfuseLockController, XNvm_EfuseSetRefClk, XNvm_EfuseSetupController, XNvm_EfuseUnlockController.
int XNvm_EfuseLockController(void)
This function locks the eFUSE Controller to prevent accidental writes to eFUSE controller registers.
XST_SUCCESS - eFUSE controller locked.XNVM_EFUSE_ERR_LOCK - Failed to lock eFUSE controller register access. XST_SUCCESS eFUSE controller locked.XNVM_EFUSE_ERR_LOCK Failed to lock eFUSE controller register access.
References XNVM_EFUSE_CTRL_BASEADDR, XNVM_EFUSE_CTRL_WR_LOCKED, XNVM_EFUSE_ERR_LOCK, XNVM_EFUSE_WR_LOCK_REG_OFFSET, XNVM_EFUSE_WR_UNLOCK_PASSCODE, XNVM_EFUSE_WRITE_LOCKED, XNvm_EfuseReadReg, XNvm_EfuseWriteReg.
Referenced by XNvm_EfuseCheckAesKeyCrc, XNvm_EfuseWrite, XNvm_EfuseWritePuf.
int XNvm_EfuseUnlockController(void)
This function unlocks the eFUSE Controller for writing to its registers.
XST_SUCCESS - eFUSE controller unlocked.XNVM_EFUSE_ERR_UNLOCK - Failed to unlock eFUSE controller register access. XST_SUCCESS eFUSE controller locked.XNVM_EFUSE_ERR_UNLOCK Failed to unlock eFUSE controller register access.
References XNVM_EFUSE_CTRL_BASEADDR, XNVM_EFUSE_CTRL_WR_UNLOCKED, XNVM_EFUSE_ERR_UNLOCK, XNVM_EFUSE_WR_LOCK_REG_OFFSET, XNVM_EFUSE_WR_UNLOCK_PASSCODE, XNVM_EFUSE_WRITE_UNLOCKED, XNvm_EfuseReadReg, XNvm_EfuseWriteReg.
Referenced by XNvm_EfuseCheckAesKeyCrc, XNvm_EfuseSetupController.
int XNvm_EfuseSetupController(XNvm_EfuseOpMode Op, XNvm_EfuseRdMode RdMode, u32 EfuseClkFreq)
This function sets up eFUSE controller for given operation and read mode.
Op - Operation to be performed read/program(write). RdMode - Read mode for eFUSE read operation. EfuseClkFreq - Input Clock frequency for timers initialization. XST_SUCCESS - eFUSE controller setup for given op.XNVM_EFUSE_ERR_UNLOCK - Failed to unlock eFUSE controller register access.XNVM_EFUSE_ERR_PGM_TBIT_PATTERN - Error in T-Bit pattern.XST_FAILURE - Error on set read mode failure.
References XNVM_EFUSE_CTRL_BASEADDR, XNVM_EFUSE_MODE_PGM, XNVM_EFUSE_TEST_CTRL_REG_OFFSET, XNvm_EfuseCheckForTBits, XNvm_EfuseEnableProgramming, XNvm_EfuseInitTimers, XNvm_EfuseSetReadMode, XNvm_EfuseUnlockController, XNvm_EfuseWriteReg.
Referenced by XNvm_EfuseCacheLoadNPrgmProtectionBits, XNvm_EfuseWrite, XNvm_EfuseWriteAesKey, XNvm_EfuseWriteBootEnvCtrlBits, XNvm_EfuseWriteBootModeDisable, XNvm_EfuseWriteCrc, XNvm_EfuseWriteDecOnly, XNvm_EfuseWriteDisableInplacePlmUpdate, XNvm_EfuseWriteDmeMode, XNvm_EfuseWriteDmeRevoke, XNvm_EfuseWriteDmeUserKey, XNvm_EfuseWriteFipsInfo, XNvm_EfuseWriteGlitchConfigBits, XNvm_EfuseWriteIv, XNvm_EfuseWriteMisc1Bits, XNvm_EfuseWriteMiscCtrlBits, XNvm_EfuseWriteOffChipRevokeID, XNvm_EfuseWritePpkHash, XNvm_EfuseWritePuf, XNvm_EfuseWritePufSecCtrl, XNvm_EfuseWriteRevocationID, XNvm_EfuseWriteRomRsvdBits, XNvm_EfuseWriteSecCtrlBits, XNvm_EfuseWriteUds.
int XNvm_EfuseResetReadMode(void)
This function disables Margin Read mode of eFUSE controller.
XST_SUCCESS - if resetting read mode is successful.XST_FAILURE - if there is a failure XST_SUCCESS If resetting read mode is successful.XST_FAILURE If there is a failure
int XNvm_EfuseDisableProgramming(void)
This function disables programming mode of eFUSE controller.
XST_SUCCESS - if eFUSE programming is disabled successfully.XST_FAILURE - if there is a failure XST_SUCCESS If eFUSE programming is disabled successfully.XST_FAILURE If there is a failure
int XNvm_ValidateAesKey(const char *Key)
Validate the input string contains valid AES key.
Key - Pointer to AES key. XST_SUCCESS On valid input AES key string.XST_INVALID_PARAM On invalid length of the input string.XST_FAILURE On non hexadecimal character in string Key - Pointer to AES key. - XST_SUCCESS - On valid input AES key string. XST_INVALID_PARAM - On invalid length of the input string.XST_FAILURE - On non hexadecimal character in string
References XNVM_128_BITS_AES_KEY_LEN_IN_CHARS, XNVM_256_BITS_AES_KEY_LEN_IN_CHARS, XNVM_MAX_AES_KEY_LEN_IN_CHARS.