xnvm_spartan_ultrascaleplus_efuse_apis
XNVM_EFUSE_PPK_HASH_LEN_IN_BITS
PPK hash length in bits.
XNVM_EFUSE_DEF_PPK_HASH_SIZE_IN_WORDS
Default PPK hash size in words.
XNVM_EFUSE_PPK_HASH_SIZE_IN_BYTES
PPK hash size in bytes.
XNVM_EFUSE_PPK_END
Last PPK.
XNVM_EFUSE_PGM_TIMEOUT_VAL
Program timeout value.
XNVM_EFUSE_RD_TIMEOUT_VAL
Read timeout value.
XNVM_EFUSE_CACHE_LOAD_TIMEOUT_VAL
Cache load timeout value.
Referenced by XNvm_EfuseCacheReload.
XNvm_EfuseIvType
IV range.
XNvm_EfusePpkType
eFuse PPK 0
@0
0x2 - Error efuse unlock
int XNvm_EfuseWrite(XNvm_EfuseData *EfuseData)
This function is used to program the eFUSE of spartan ultrascale plus, based on user inputs.
EfuseData Pointer to the XNvm_EfuseData. XST_SUCCESS if programs successfully.XNVM_EFUSE_ERR_INVALID_PARAM - On invalid parameterXNVM_EFUSE_ERR_NTHG_TO_BE_PROGRAMMED - Nothing to be programmedXNVM_EFUSE_ERR_BEFORE_PROGRAMMING - Error before programming After eFUSE programming is complete, the cache is automatically reloaded so all programmed eFUSE bits can be directly read from cache.
References XNvm_EfuseData::AesKeys, XNvm_EfuseData::AesRevokeId, XNvm_EfuseData::DecOnly, XNvm_EfuseData::EfuseClkFreq, XNvm_EfuseData::Ivs, XNvm_EfuseData::PpkHash, XNvm_EfuseData::SecCtrlBits, XNvm_EfuseData::SpkRevokeId, XNvm_EfuseData::SysMonInstPtr, XNvm_EfuseData::UserFuse, XNvm_EfuseData::XilinxCtrl, XNVM_EFUSE_ERR_BEFORE_PROGRAMMING, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_ERR_NTHG_TO_BE_PROGRAMMED, XNVM_EFUSE_MARGIN_RD, XNVM_EFUSE_MODE_PGM, XNvm_EfuseCacheReload, XNvm_EfuseDisableProgramming, XNvm_EfuseLockController, XNvm_EfuseReadSecCtrlBits, XNvm_EfuseResetReadMode, XNvm_EfuseSetupController, XNvm_EfuseTempAndVoltChecks.
Referenced by XNvm_EfuseRevokePpk, XNvm_EfuseWriteIVs, XNvm_EfuseWriteRevocationId, XNvm_EfuseWriteUserFuses.
int XNvm_EfuseReadSecCtrlBits(XNvm_EfuseSecCtrlBits *SecCtrlBits)
This function reads secure control bits and CRC_EN register bits from eFUSE cache.
SecCtrlBits - Pointer to XNvm_EfuseSecCtrlBits where secure control bits are read. Device-specific behavior: **SPARTANUPLUS devices:** - Supports PPK0, PPK1, and PPK2 (three PPK hashes) - PPK hash size: 256 bits (32 bytes) - Reads Ppk2lck and Ppk2Invld bits for PPK2 - PPK2 eFUSE registers are shared between PPK2 hash and PUF hash storage - The HashPufOrKey bit determines which hash type is stored: * When HashPufOrKey = 0: PPK2 registers contain PPK2 hash * When HashPufOrKey = 1: PPK2 registers contain PUF hash - When programming PUF hash: * Ppk2Invld must be 0 (PPK2 register not invalidated) * Ppk2lck must be 0 (PPK2 register not write-locked) * PPK2 registers must not be already programmed * HashPufOrKey must be set to 1 to indicate PUF hash usage **SPARTANUPLUSAES1 devices:** - Supports only PPK0 and PPK1 (two PPK hashes) - PPK hash size: 384 bits (48 bytes) - Ppk2lck and Ppk2Invld fields are not available - Reads Ppk1lck and Ppk1Invld bits for PPK1 - PPK1 eFUSE registers are shared between PPK1 hash and PUF hash storage - The HashPufOrKey bit determines which hash type is stored: * When HashPufOrKey = 0: PPK1 registers contain PPK1 hash * When HashPufOrKey = 1: PPK1 registers contain PUF hash - When programming PUF hash: * Ppk1Invld must be 0 (PPK1 register not invalidated) * Ppk1lck must be 0 (PPK1 register not write-locked) * PPK1 registers must not be already programmed * HashPufOrKey must be set to 1 to indicate PUF hash usage XST_SUCCESS - Specified data read.XNVM_EFUSE_ERR_INVALID_PARAM - Invalid parameter.XNVM_EFUSE_ERR_CACHE_PARITY - Parity Error exist in cache. This function reads secure control bits and CRC_EN register bits from eFUSE cache. SecCtrlBits - Pointer to the Xnvm_SecCtrlBits which holds the read secure control bits. XST_SUCCESS On Successful read.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_CACHE_PARITY Error while Cache reload.
int XNvm_EfuseReadPpkHash(XNvm_EfusePpkType PpkType, u32 *PpkData, u32 PpkSize)
This function reads PPK0/1/2 hash based on XNvm_EfusePpkType from eFUSE cache.
PpkType - is of type XNvm_EfusePpkType i.e. PPK0/1/2. PpkData - Pointer to the PPK data. PpkSize - Size of PPK it is either 32 or 48 bytes. XST_SUCCESS - Specified data read.XNVM_EFUSE_ERR_INVALID_PARAM - Invalid input parameter.XST_FAILURE - Error in cache read operation.
References XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_PPK0, XNVM_EFUSE_PPK1, XNVM_EFUSE_PPK2, XNVM_EFUSE_PPK_HASH_256_SIZE_IN_BYTES, XNVM_EFUSE_PPK_HASH_384_SIZE_IN_BYTES, XNVM_EFUSE_WORD_LEN, XNvm_EfuseReadCacheRange.
int XNvm_EfuseReadSpkRevokeId(u32 *SpkRevokeData, u32 SpkRevokeRow)
This function reads SPK revoke id from eFUSE cache.
SpkRevokeData - is pointer to SPK revoke data. SpkRevokeRow - SPK revoke row to be read it can be either 0/1/2. XST_SUCCESS - Specified data read.XNVM_EFUSE_ERR_INVALID_PARAM - On invalid parameter
References XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_MAX_SPK_REVOKE_ID, XNVM_EFUSE_WORD_LEN.
int XNvm_EfuseReadAesRevokeId(u32 *AesRevokeData)
This function reads AES revoke id from eFUSE cache.
AesRevokeData - is pointer to AES revoke data. XST_SUCCESS - Specified data read.XNVM_EFUSE_ERR_INVALID_PARAM - On invalid parameter
References XNVM_EFUSE_ERR_INVALID_PARAM.
int XNvm_EfuseReadUserFuse(u32 *UserFuseData)
This function reads user efuses from eFUSE cache.
UserFuseData - is pointer to AES revoke data. XST_SUCCESS - Specified data read.XNVM_EFUSE_ERR_INVALID_PARAM - On invalid parameter
References XNVM_EFUSE_ERR_INVALID_PARAM.
int XNvm_EfuseReadIv(XNvm_EfuseIvType IvType, u32 *IvData)
This function reads IV based on XNvm_EfuseIvType from eFUSE cache.
IvType - is of type XNvm_EfuseIvType. IvData - Pointer to the iv data. XST_SUCCESS - Specified data read.XNVM_EFUSE_ERR_INVALID_PARAM - On invalid parameter
References XNVM_EFUSE_AES_IV_RANGE, XNVM_EFUSE_AES_IV_SIZE_IN_WORDS, XNVM_EFUSE_BLACK_IV, XNVM_EFUSE_ERR_INVALID_PARAM, XNvm_EfuseReadCacheRange.
int XNvm_EfuseReadDna(u32 *Dna)
This function reads DNA from eFUSE cache.
Dna - Pointer to the DNA data. XST_SUCCESS - Specified data read.XNVM_EFUSE_ERR_INVALID_PARAM - On invalid parameter
References XNVM_EFUSE_DNA_SIZE_IN_WORDS, XNVM_EFUSE_ERR_INVALID_PARAM, XNvm_EfuseReadCacheRange.
int XNvm_EfuseReadDecOnly(u32 *DecOnly)
This function reads DEC only fuses from eFUSE cache.
DecOnly - Pointer to the DEC only efuse data. XST_SUCCESS - Specified data read.XNVM_EFUSE_ERR_INVALID_PARAM - On invalid parameter This function reads DEC only fuses from eFUSE cache. DecOnly - Pointer to the DecOnly efuse data. XST_SUCCESS On Successful read.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_RD_DEC_ONLY Error in reading in Dec_only efuses. If DecOnly eFuse is programmed that means boot can happen in only Symmetric HWRoT boot mode.
int XNvm_EfuseReadXilinxCtrl(XNvm_EfuseXilinxCtrl *XilinxCtrl)
This function reads Xilinx Ctrl fuse from eFUSE cache.
XilinxCtrl - Pointer to the XilinxCtrl efuse data. XST_SUCCESS - Specified data read.XNVM_EFUSE_ERR_INVALID_PARAM - On invalid parameter
References XNvm_EfuseXilinxCtrl::PrgmDisSJtag, XNvm_EfuseXilinxCtrl::PrgmOspiResetRecoveryDelayCtrl, XNvm_EfuseXilinxCtrl::PrgmPufHDInvld, XNvm_EfuseXilinxCtrl::PrgmRomOspiCmdSeqCtrl, XNvm_EfuseXilinxCtrl::PrgmRomRsvdOspiDevResetChoice, XNVM_EFUSE_ERR_INVALID_PARAM.
XNVM_EFUSE_WORD_LEN
Word length.
Referenced by XNvm_EfuseReadPpkHash, XNvm_EfuseReadSpkRevokeId.
XNVM_EFUSE_BITS_IN_A_BYTE
Number of bits in a byte.
XNVM_EFUSE_AES_KEY_SIZE_IN_WORDS
AES key size in words.
XNVM_EFUSE_PPK_HASH_256_SIZE_IN_BYTES
PPK hash size in bytes for parts-SU10P,SU25P,SU35P.
Referenced by XNvm_EfuseReadPpkHash.
XNVM_EFUSE_PPK_HASH_384_SIZE_IN_BYTES
PPK hash size in bytes for all other parts except SU10P,SU25P,SU35P.
Referenced by XNvm_EfuseReadPpkHash.
XNVM_EFUSE_AES_IV_SIZE_IN_BYTES
AES IV size in bytes.
XNVM_EFUSE_AES_IV_SIZE_IN_WORDS
AES IV size in words.
Referenced by XNvm_EfuseReadIv.
XNVM_EFUSE_PPK0_HASH_START_ROW
PPK0 hash start row.
XNVM_EFUSE_PPK1_HASH_START_ROW
PPK1 hash start row.
XNVM_EFUSE_PPK2_HASH_START_ROW
PPK2 hash start row.
XNVM_EFUSE_PPK0_START_COL
PPK0 hash start column.
XNVM_EFUSE_PPK0_END_COL
PPK0 hash end column.
XNVM_EFUSE_PPK1_START_COL
PPK1 hash start column.
XNVM_EFUSE_PPK1_END_COL
PPK1 hash end column.
XNVM_EFUSE_PPK2_START_COL
PPK2 hash start column.
XNVM_EFUSE_PPK2_END_COL
PPK2 hash end column.
XNVM_EFUSE_PPK_HASH_NUM_OF_ROWS
PPK hash number of rows.
Referenced by XNvm_EfuseReadPpkHash.
XNVM_EFUSE_SPK_REVOKE_ID_START_ROW
SPK revoke ID start row.
XNVM_EFUSE_SPK_REVOKE_ID_START_COL
SPK revoke ID start column.
XNVM_EFUSE_AES_KEY_START_ROW
AES key start row.
XNVM_EFUSE_AES_KEY_START_COL
AES key start column.
XNVM_EFUSE_AES_KEY_END_COL
AES key end column.
XNVM_EFUSE_AES_KEY_NUM_OF_ROWS
AES key number of rows.
XNVM_EFUSE_AES_IV_START_ROW
AES IV start row.
XNVM_EFUSE_AES_IV_START_COL
AES IV start column.
XNVM_EFUSE_AES_IV_END_COL
AES IV end column.
XNVM_EFUSE_AES_REVOKE_ID_START_ROW
AES revoke ID start row.
XNVM_EFUSE_AES_REVOKE_ID_START_COL
AES revoke ID start column.
XNVM_EFUSE_AES_REVOKE_ID_END_COL
AES revoke ID end column.
XNVM_EFUSE_AES_REVOKE_ID_NUM_OF_ROWS
AES revoke ID number of rows.
XNVM_EFUSE_USER_FUSE_START_ROW
User efuse start row.
Referenced by XNvm_EfuseReadUserFuses.
XNVM_EFUSE_USER_FUSE_START_COL
User efuse start column.
XNVM_EFUSE_USER_FUSE_END_COL
User efuse end column.
XNVM_EFUSE_USER_FUSE_NUM_OF_ROWS
User efuse number of rows.
XNVM_EFUSE_DEC_ONLY_START_ROW
Decrypt only start row.
XNVM_EFUSE_DEC_ONLY_START_COL
Decrypt only start column.
XNVM_EFUSE_DEC_ONLY_END_COL
Decrypt only end column.
XNVM_EFUSE_DEC_ONLY_NUM_OF_ROWS
Decrypt only number of rows.
Referenced by XNvm_EfuseWriteDecOnly.
XNVM_EFUSE_XILINX_CTRL_START_ROW
Xilinx control bits start row.
XNVM_EFUSE_AES_IV_NUM_OF_ROWS
AES IV number of rows.
XNVM_EFUSE_MAX_BITS_IN_ROW
Maximum bits in a row.
Referenced by XNvm_EfuseWriteOffChipRevokeID, XNvm_EfuseWriteRevocationId.
XNVM_EFUSE_MAX_SPK_REVOKE_ID
Maximum SPK revoke id.
Referenced by XNvm_EfuseReadSpkRevokeId.
XNVM_EFUSE_DNA_SIZE_IN_WORDS
DNA size in words.
Referenced by XNvm_EfuseReadDna.
XNVM_MAX_REVOKE_ID_FUSES
Maximum revocation ID eFuses.
Referenced by XNvm_EfuseWriteOffChipRevokeID, XNvm_EfuseWriteRevocationID, XNvm_EfuseWriteRevocationId.
XNVM_EFUSE_PROGRAM_VERIFY
Verify eFuses after programming.
XNVM_EFUSE_WRITE_LOCKED
Efuse write locked.
Referenced by XNvm_EfuseCheckAesKeyCrc, XNvm_EfuseLockController.
XNVM_EFUSE_WRITE_UNLOCKED
Efuse write unlocked.
Referenced by XNvm_EfuseUnlockController.
XNVM_EFUSE_CFG_ENABLE_PGM
Enable efuse programming.
Referenced by XNvm_EfuseDisableProgramming, XNvm_EfuseEnableProgramming.
XNVM_EFUSE_CFG_MARGIN_RD
Enable efuse margin read.
Referenced by XNvm_EfuseResetReadMode, XNvm_EfuseSetReadMode.
XNVM_EFUSE_STATUS_TBIT_0
Tbit 0 value.
Referenced by XNvm_EfuseCheckForTBits.
XNVM_EFUSE_ADDR_COLUMN_SHIFT
Column shift.
XNVM_EFUSE_ADDR_ROW_SHIFT
Row shift.
XNVM_EFUSE_ISR_PGM_DONE
Program done value.
XNVM_EFUSE_ISR_PGM_ERROR
Program error value.
XNVM_EFUSE_ISR_RD_DONE
Read done value.
XNVM_EFUSE_ISR_CACHE_ERROR
Cache error value.
Referenced by XNvm_EfuseCacheReload, XNvm_EfuseCheckZeros.
XNVM_EFUSE_STS_CACHE_DONE
Cache done value.
XNVM_EFUSE_CACHE_DEC_EFUSE_ONLY_MASK
Decrypt only efuse mask.
Referenced by XNvm_EfuseValidateDecOnlyRequest, XNvm_EfuseWriteDecOnly.
XNVM_EFUSE_SEC_DEF_VAL_ALL_BIT_SET
All bit set mask.
XNVM_EFUSE_SEC_DEF_VAL_BYTE_SET
Byte mask.
XNVM_EFUSE_CRC_AES_ZEROS
CRC for Aes zero key.
Referenced by XNvm_EfuseValidateAesKeyWriteReq, XNvm_EfuseValidateDecOnlyRequest.
XNVM_EFUSE_PUFHD_INVLD_EFUSE_VAL
Puf Invalid.
XNVM_SET_EFUSE_CLOCK_FREQUENCY_SRC_FROM_USER
Set efuse clock frequency from user.