xnvm_efuse_server_apis
XNVM_EFUSE_CTRL_WR_LOCKED
eFuse control write locked
Referenced by XNvm_EfuseCheckAesKeyCrc, XNvm_EfuseLockController.
XNVM_EFUSE_CTRL_WR_UNLOCKED
eFuse control write unlocked
Referenced by XNvm_EfuseUnlockController.
XNVM_EFUSE_FULL_RANGE_TEMP_MIN
Minimum temperature for full range check.
XNVM_EFUSE_FULL_RANGE_TEMP_MAX
Maximum temperature for full range check.
XNVM_EFUSE_TEMP_LP_MIN
Minimum temperature for low power range check.
XNVM_EFUSE_TEMP_LP_MAX
Maximum temperature for low power range check.
XNVM_EFUSE_TEMP_MP_MIN
Minimum temperature for medium power range check.
XNVM_EFUSE_TEMP_MP_MAX
Maximum temperature for medium power range check.
XNVM_EFUSE_TEMP_HP_MIN
Minimum temperature for high power range check.
XNVM_EFUSE_TEMP_HP_MAX
Maximum temperature for high power range check.
XNVM_EFUSE_FULL_RANGE_CHECK
To check both voltage and temperature in full range.
XNVM_EFUSE_LP_RANGE_CHECK
To check both voltage and temperature in low power range.
XNVM_EFUSE_MP_RANGE_CHECK
To check both voltage and temperature in medium power range.
XNVM_EFUSE_HP_RANGE_CHECK
To check both voltage and temperature in high power range.
XNVM_EFUSE_VCC_PMC_LP_MIN
Minimum voltage for low power range check.
XNVM_EFUSE_VCC_PMC_LP_MAX
Maximum voltage for low power range check.
XNVM_EFUSE_VCC_PMC_MP_MIN
Minimum voltage for medium power range check.
XNVM_EFUSE_VCC_PMC_MP_MAX
Maximum voltage for medium power range check.
XNVM_EFUSE_VCC_PMC_HP_MIN
Minimum voltage for high power range check.
XNVM_EFUSE_VCC_PMC_HP_MAX
Maximum voltage for high power range check.
XNVM_EFUSE_CRC_AES_ZEROS
CRC for Aes zero key.
XNVM_EFUSE_TOTAL_NUM_OF_ROWS
Efuse total number of rows.
XNVM_EFUSE_TOTAL_PPK_HASH_ROWS
PPK hash number of eFuse rows.
XNVM_EFUSE_WORD_LEN
eFuse word length
XNVM_EFUSE_SEC_DEF_VAL_ALL_BIT_SET
Default secure value for 32 bit.
Referenced by XNvm_EfuseWritePuf.
XNVM_EFUSE_SYSMON_VCCPMC_AMUX_CTRL
Sysmon VCCPMC Amux ctrl value.
XNVM_EFUSE_SYSMON_VCCPMC_ABUS_SW1
Sysmon VCCPMC Abus sw1 value.
XNVM_EFUSE_SYSMON_VCCPMC_ABUS_SW0
Sysmon VCCPMC Abus sw0 value.
XNVM_EFUSE_SYSMON_VCCPMC_MODE
Sysmon VCCPMC mode value.
XNVM_EFUSE_SYSMON_NUM_MEASURE_REGS
Sysmon number of measurement registers.
XNVM_EFUSE_SYSMON_NUM_SUPPLIES_PER_FLAG
Sysmon number of supplies per flag.
XNVM_EFUSE_SYSMONPSV_TIMEOUT
Sysmon Psv timeout value.
XNVM_EFUSE_FRACTION_MUL_VALUE
Fraction multiplier value.
XNVM_NUM_OF_CACHE_ADDR_PER_PAGE
Number of cache addresses per page.
XNVM_EFUSE_PPK_3_PPK_4_ENABLE
PPK3 and PPK4 enable bits mask.
XNVM_EFUSE_NUM_OF_PPKS
Total number of PPKS.
XNvm_EfuseOpMode
eFuse read mode
XNvm_EfuseRdMode
eFuse normal read
XNvm_EfuseType
Efuse page 0.
int XNvm_EfuseCacheReload(void)
This function reloads the eFUSE cache, so that eFUSE values can be directly read from cache.
XST_SUCCESS On successful cache reload.XNVM_EFUSE_ERR_CACHE_LOAD Error while loading the cache. Not recommended to call this API frequently,if this API is called all the cache memory is reloaded by reading eFUSE array, reading eFUSE bit multiple times may diminish the life time.
References XNVM_EFUSE_CACHE_LOAD_MASK, XNVM_EFUSE_CACHE_LOAD_REG_OFFSET, XNVM_EFUSE_CACHE_LOAD_TIMEOUT_VAL, XNVM_EFUSE_CTRL_BASEADDR, XNVM_EFUSE_ERR_CACHE_LOAD, XNVM_EFUSE_ISR_CACHE_ERROR, XNVM_EFUSE_ISR_REG_OFFSET, XNVM_EFUSE_STATUS_CACHE_DONE, XNVM_EFUSE_STATUS_REG_OFFSET, XNvm_EfuseReadReg, XNvm_EfuseWriteReg.
Referenced by XNvm_EfuseWrite.
void XNvm_EfuseDisablePowerDown(void)
This function disables power down of eFUSE macros.
References XNVM_EFUSE_CTRL_BASEADDR, XNVM_EFUSE_PD_ENABLE, XNVM_EFUSE_PD_REG_OFFSET, XNvm_EfuseReadReg, XNvm_EfuseWriteReg, XNVM_ONE_MICRO_SECOND.
Referenced by XNvm_EfuseSetupController.
int XNvm_EfuseSetReadMode(XNvm_EfuseRdMode RdMode)
This function sets read mode of eFUSE controller.
RdMode - Mode to be used for eFUSE read. XST_SUCCESS If Setting read mode is successful.XST_FAILURE If there is a failure
References XNVM_EFUSE_CFG_MARGIN_RD, XNVM_EFUSE_CFG_NORMAL_RD, XNVM_EFUSE_CFG_REG_OFFSET, XNVM_EFUSE_CTRL_BASEADDR, XNVM_EFUSE_CTRL_CFG_MARGIN_RD_MASK, XNVM_EFUSE_NORMAL_RD, XNVM_EFUSE_SEC_DEF_VAL_ALL_BIT_SET, XNVM_EFUSE_SEC_DEF_VAL_BYTE_SET, XNvm_EfuseReadReg.
Referenced by XNvm_EfuseSetupController.
void XNvm_EfuseSetRefClk(void)
This function sets reference clock of eFUSE controller.
References XNVM_CRP_BASE_ADDR, XNVM_CRP_EFUSE_REF_CLK_REG_OFFSET, XNVM_CRP_EFUSE_REF_CLK_SELSRC, XNvm_EfuseWriteReg.
Referenced by XNvm_EfuseSetupController.
void XNvm_EfuseEnableProgramming(void)
This function enables programming mode of eFUSE controller.
References XNVM_EFUSE_CFG_ENABLE_PGM, XNVM_EFUSE_CFG_REG_OFFSET, XNVM_EFUSE_CTRL_BASEADDR, XNvm_EfuseReadReg, XNvm_EfuseWriteReg.
Referenced by XNvm_EfuseSetupController.
int XNvm_EfuseDisableProgramming(void)
This function disables programming mode of eFUSE controller.
XST_SUCCESS - if eFUSE programming is disabled successfully.XST_FAILURE - if there is a failure XST_SUCCESS If eFUSE programming is disabled successfully.XST_FAILURE If there is a failure
References XNVM_EFUSE_CFG_ENABLE_PGM, XNVM_EFUSE_CFG_REG_OFFSET, XNVM_EFUSE_CTRL_BASEADDR, XNvm_EfuseReadReg.
Referenced by XNvm_EfuseWrite, XNvm_EfuseWritePuf.
int XNvm_EfuseResetReadMode(void)
This function disables Margin Read mode of eFUSE controller.
XST_SUCCESS - if resetting read mode is successful.XST_FAILURE - if there is a failure XST_SUCCESS If resetting read mode is successful.XST_FAILURE If there is a failure
References XNVM_EFUSE_CFG_MARGIN_RD, XNVM_EFUSE_CFG_REG_OFFSET, XNVM_EFUSE_CTRL_BASEADDR, XNvm_EfuseReadReg.
Referenced by XNvm_EfuseWrite, XNvm_EfuseWritePuf.
void XNvm_EfuseInitTimers(void)
This function initializes eFUSE controller timers.
References XNVM_EFUSE_CTRL_BASEADDR, XNVM_EFUSE_TPGM_DIV, XNVM_EFUSE_TPGM_REG_OFFSET, XNVM_EFUSE_TRD_DIV, XNVM_EFUSE_TRD_REG_OFFSET, XNVM_EFUSE_TRDM_REG_OFFSET, XNVM_EFUSE_TRMD_DIV, XNVM_EFUSE_TSU_H_CS_DIV, XNVM_EFUSE_TSU_H_CS_REG_OFFSET, XNVM_EFUSE_TSU_H_PS_CS_DIV, XNVM_EFUSE_TSU_H_PS_CS_REG_OFFSET, XNVM_EFUSE_TSU_H_PS_DIV, XNVM_EFUSE_TSU_H_PS_REG_OFFSET, XNvm_EfuseWriteReg, XNVM_PSU_PSS_REF_CLK_FREQ.
Referenced by XNvm_EfuseSetupController.
int XNvm_EfuseSetupController(XNvm_EfuseOpMode Op, XNvm_EfuseRdMode RdMode)
This function setups eFUSE controller for given operation and read mode.
Op - Operation to be performed read/program(write). RdMode - Read mode for eFUSE read operation. XST_SUCCESS eFUSE controller setup for given op.XNVM_EFUSE_ERR_UNLOCK Failed to unlock eFUSE controller register access.XST_FAILURE If eFUSE controller is not unlockedXNVM_EFUSE_ERR_PGM_TBIT_PATTERN If TBITS pattern is not matched with the expected value.
References XNVM_EFUSE_CTRL_BASEADDR, XNVM_EFUSE_MODE_PGM, XNVM_EFUSE_TEST_CTRL_REG_OFFSET, XNvm_EfuseCheckForTBits, XNvm_EfuseDisablePowerDown, XNvm_EfuseEnableProgramming, XNvm_EfuseInitTimers, XNvm_EfuseSetReadMode, XNvm_EfuseSetRefClk, XNvm_EfuseUnlockController, XNvm_EfuseWriteReg.
int XNvm_EfuseCheckForTBits(void)
This function checks whether Tbits are programmed or not.
XST_SUCCESS On Success.XNVM_EFUSE_ERR_PGM_TBIT_PATTERN Error in T-Bit pattern.
References XNVM_EFUSE_CTRL_BASEADDR, XNVM_EFUSE_ERR_PGM_TBIT_PATTERN, XNVM_EFUSE_STATUS_REG_OFFSET, XNVM_EFUSE_STATUS_TBIT_0, XNVM_EFUSE_STATUS_TBIT_1, XNVM_EFUSE_STATUS_TBIT_2, XNvm_EfuseReadReg.
Referenced by XNvm_EfuseSetupController.
u32 XNvm_GetSysmonSupplyRegId(UINTPTR SysmonpsvSatBaseAddr)
This function reads root register ID where measurement is stored in Root SysMon.
SysmonpsvSatBaseAddr - Pointer to SysMon base address SupplyReg Id - On successful match foundXNVM_EFUSE_SEC_DEF_VAL_ALL_BIT_SET - When no matching supply found
References XNVM_EFUSE_SEC_DEF_VAL_ALL_BIT_SET, XNVM_EFUSE_SYSMON_NUM_MEASURE_REGS, XNVM_EFUSE_SYSMON_SAT_ADDR_ID_MASK, XNVM_EFUSE_SYSMON_SAT_ADDR_ID_SHIFT, XNVM_EFUSE_SYSMON_SAT_CONFIG_ABUS_SW0_MASK, XNVM_EFUSE_SYSMON_SAT_CONFIG_ABUS_SW0_SHIFT, XNVM_EFUSE_SYSMON_SAT_CONFIG_ABUS_SW1_MASK, XNVM_EFUSE_SYSMON_SAT_CONFIG_ABUS_SW1_SHIFT, XNVM_EFUSE_SYSMON_SAT_CONFIG_AMUX_CTRL_MASK, XNVM_EFUSE_SYSMON_SAT_CONFIG_AMUX_CTRL_SHIFT, XNVM_EFUSE_SYSMON_SAT_CONFIG_MODE_MASK, XNVM_EFUSE_SYSMON_SAT_CONFIG_MODE_SHIFT, XNVM_EFUSE_SYSMON_VCCPMC_ABUS_SW0, XNVM_EFUSE_SYSMON_VCCPMC_ABUS_SW1, XNVM_EFUSE_SYSMON_VCCPMC_AMUX_CTRL, XNVM_EFUSE_SYSMON_VCCPMC_MODE, XNVM_EFUSE_SYSMONPSV_SAT_MEASURE0_OFFSET, XNVM_EFUSE_WORD_LEN.
Referenced by XNvm_EfuseTempAndVoltChecks.
int XNvm_EfuseTempAndVoltChecks(const XSysMonPsv *SysMonInstPtr)
This function performs the Temperature and Voltage checks to ensure that they are in limits before eFuse programming.
SysMonInstPtr - Pointer to SysMon instance. XST_SUCCESS - On successful Voltage and Temperature checks.XNVM_EFUSE_ERR_INVALID_PARAM - Input validation failure.XNVM_EFUSE_ERROR_READ_VOLTAGE_OUT_OF_RANGE - Voltage is out of rangeXNVM_EFUSE_ERROR_READ_TEMPERATURE_OUT_OF_RANGE - Temperature is out of range
References XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_ERROR_NO_SUPPLIES_ENABLED, XNVM_EFUSE_ERROR_READ_TMEPERATURE_OUT_OF_RANGE, XNVM_EFUSE_ERROR_READ_VOLTAGE_OUT_OF_RANGE, XNVM_EFUSE_ERROR_SYSMON_NO_NEW_DATA, XNVM_EFUSE_FRACTION_MUL_VALUE, XNVM_EFUSE_SEC_DEF_VAL_ALL_BIT_SET, XNVM_EFUSE_SYSMON_LOCK_CODE, XNVM_EFUSE_SYSMON_NUM_SUPPLIES_PER_FLAG, XNVM_EFUSE_SYSMONPSV_SAT0_BASEADDR, XNVM_EFUSE_SYSMONPSV_SAT1_BASEADDR, XNVM_EFUSE_SYSMONPSV_TIMEOUT, XNVM_EFUSE_WORD_LEN, XNvm_GetSysmonSupplyRegId.
Referenced by XNvm_EfuseWrite, XNvm_EfuseWriteAesKey, XNvm_EfuseWriteBootEnvCtrlBits, XNvm_EfuseWriteBootModeDisable, XNvm_EfuseWriteCrc, XNvm_EfuseWriteDecOnly, XNvm_EfuseWriteDisableInplacePlmUpdate, XNvm_EfuseWriteDmeMode, XNvm_EfuseWriteDmeRevoke, XNvm_EfuseWriteDmeUserKey, XNvm_EfuseWriteFipsInfo, XNvm_EfuseWriteGlitchConfigBits, XNvm_EfuseWriteIv, XNvm_EfuseWriteMisc1Bits, XNvm_EfuseWriteMiscCtrlBits, XNvm_EfuseWriteOffChipRevokeID, XNvm_EfuseWritePpkHash, XNvm_EfuseWritePuf, XNvm_EfuseWritePufSecCtrl, XNvm_EfuseWriteRevocationID, XNvm_EfuseWriteRomRsvdBits, XNvm_EfuseWriteSecCtrlBits, XNvm_EfuseWriteUds.
u32 XNvm_EfuseReadProtectionBits(u32 Mask)
This function reads the corresponding eFuse protection bits.
Mask Efuse Protection bit mask value. Return protection bits value as specified by Mask
References XNVM_EFUSE_CACHE_BASEADDR, XNVM_EFUSE_PROTECTION_BIT_CLEAR, XNVM_EFUSE_TBITS_XILINX_CTRL_ROW, XNvm_EfuseReadReg.
static int XNvm_EfuseReadCache(u32 Row, u32 *RowData)
This function reads 32-bit data from cache specified by Row.
Row - Starting Row number (0-based addressing). RowData - Pointer to memory location where read 32-bit row data is to be stored. XST_SUCCESS Specified data read.XNVM_EFUSE_ERR_INVALID_PARAM Input validation failure.XNVM_EFUSE_ERR_CACHE_PARITY Parity Error exist in cache.
static int XNvm_EfusePgmBit(XNvm_EfuseType Page, u32 Row, u32 Col)
This function sets the specified bit in the eFUSE.
Page - It is an enum variable of type XNvm_EfuseType. Row - It is an 32-bit Row number (0-based addressing). Col - It is an 32-bit Col number (0-based addressing). XST_SUCCESS Specified bit set in eFUSE.XNVM_EFUSE_ERR_PGM_TIMEOUT eFUSE programming timed out.XNVM_EFUSE_ERR_PGM eFUSE programming failed.
static int XNvm_EfuseVerifyBit(XNvm_EfuseType Page, u32 Row, u32 Col)
This function verify the specified bit set in the eFUSE.
Page - It is an enum variable of type XNvm_EfuseType. Row - It is an 32-bit Row number (0-based addressing). Col - It is an 32-bit Col number (0-based addressing). XST_SUCCESS Specified bit set in eFUSE (Aes and user key eFuses cannot be verified as they don't have eFuse cache, hence those cases are skipped and returns Success).XNVM_EFUSE_ERR_PGM_VERIFY Verification failed, specified bit is not set.XNVM_EFUSE_ERR_PGM_TIMEOUT If Programming timeout has occurred.XST_FAILURE Unexpected error.
static int XNvm_EfusePgmAndVerifyBit(XNvm_EfuseType Page, u32 Row, u32 Col)
This function sets and then verifies the specified bit in the eFUSE.
Page - It is an enum variable of type XNvm_EfuseType. Row - It is an 32-bit Row number (0-based addressing). Col - It is an 32-bit Col number (0-based addressing). XST_SUCCESS Specified bit set in eFUSE.XNVM_EFUSE_ERR_INVALID_PARAM Input validation failure.XNVM_EFUSE_ERR_PGM_TIMEOUT eFUSE programming timed out.XNVM_EFUSE_ERR_PGM eFUSE programming failed.XNVM_EFUSE_ERR_PGM_VERIFY Verification failed, specified bit is not set.XST_FAILURE Unexpected error.
static int XNvm_EfuseCacheLoadAndProtectionChecks(void)
This function reloads the cache of eFUSE so that can be directly read from cache.
XST_SUCCESS On successful cache reload.XNVM_EFUSE_ERR_CACHE_LOAD Error while loading the cache. Not recommended to call this API frequently,if this API is called all the cache memory is reloaded by reading eFUSE array, reading eFUSE bit multiple times may diminish the life time.
static int XNvm_EfusePgmAndVerifyRows(u32 StartRow, u32 RowCount, XNvm_EfuseType EfuseType, const u32 *RowData)
This function sets and then verifies the specified bits in the eFUSE.
StartRow - Starting Row number (0-based addressing). RowCount - Number of Rows to be written. EfuseType - It is an enum object of type XNvm_EfuseType. RowData - Pointer to memory location where bitmap to be written is stored. Only bit set are used for programming eFUSE. XST_SUCCESS Specified bit set in eFUSE.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.
static int XNvm_EfuseCheckZeros(u32 RowStart, u32 RowEnd)
This function is used to check if given eFUSE rows contains zeros.
RowStart - Row number from which verification has to be started. RowEnd - Row number till which verification has to be ended. XST_SUCCESS If eFUSE rows contains zeros.XST_FAILURE If eFUSE rows doesn't contain zeros.
static int XNvm_EfuseComputeProgrammableBits(const u32 *ReqData, u32 *PrgmData, u32 StartRow, u32 EndRow)
This function is used to compute the eFuse bits to be programmed to the eFuse.
ReqData - Pointer to the user provided eFuse data to be written. PrgmData - Pointer to the computed eFuse bits to be programmed, which means that this API fills only unprogrammed and valid bits. StartRow - A 32 bit StartRow value of an expected Programmable Bits. EndRow - A 32 bit EndRow value of an expected Programmable Bits. XST_SUCCESS If the eFuse data computation is successful.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_CACHE_PARITY Error in Cache reload.
static int XNvm_EfuseValidateWriteReq(const XNvm_EfuseData *WriteChecks)
This function performs pre checks for programming all the specified bits.
WriteChecks - Pointer to the XNvm_EfuseData which holds eFuse data to be programmed. XST_SUCCESS If all the conditions for programming is satisfied.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_WRITE_AES_KEY Error in writing Aes key.XNVM_EFUSE_ERR_FUSE_PROTECTED Efuse is write protected.XNVM_EFUSE_ERR_WRITE_PPK0_HASH Error in writing ppk0 hash.XNVM_EFUSE_ERR_WRITE_PPK1_HASH Error in writing ppk1 hash.XNVM_EFUSE_ERR_WRITE_PPK2_HASH Error in writing ppk2 hash.XNVM_EFUSE_ERR_BIT_CANT_REVERT Efuse bit can't be reverted.XNVM_EFUSE_ERR_WRITE_REVOCATION_IDS Error in writing Revocation id efuses.XNVM_EFUSE_ERR_AES_SHOULD_BE_PRGMD Aes key should be programmed to program DEC_ONLY.XNVM_EFUSE_ERR_BLKOBFUS_IV_SHOULD_BE_PRGMD Blk Obfuscated IV should be programmed to program DEC_ONLY.XNVM_EFUSE_ERR_WRITE_USER0_KEY Error in writing User key 0.XNVM_EFUSE_ERR_WRITE_USER1_KEY Error in writing User key 1.
static int XNvm_EfuseValidateIVsWriteReq(const XNvm_EfuseIvs *EfuseIv)
This function validates all IVs requested for programming.
EfuseIv - Pointer to XNvm_EfuseIvs structure which holds IV data to be programmed to eFUSE. XST_SUCCESS If validation is successful.XNVM_EFUSE_ERR_INVALID_PARAM Input validation failure.XNVM_EFUSE_ERR_WRITE_META_HEADER_IV_RANGE Error in Metaheader IV range write request.XNVM_EFUSE_ERR_BLK_OBFUS_IV_ALREADY_PRGMD Error in Blk Obfus Iv write request.XNVM_EFUSE_ERR_WRITE_PLM_IV_RANGE Error in Plm Iv range write request.XNVM_EFUSE_ERR_WRITE_DATA_PARTITION_IV_RANGE Error in Data Partition Iv range write request.
static int XNvm_EfuseValidateAesWriteReq(const XNvm_EfuseAesKeys *Keys)
This function validates all Aes keys requested for programming.
Keys - Pointer to XNvm_EfuseAesKeys structure. XST_SUCCESS If validation is successful.XNVM_EFUSE_ERR_RD_SEC_CTRL_BITS Error in reading Sec Ctrl efuses.XNVM_EFUSE_ERR_AES_ALREADY_PRGMD Aes key already programmed.XNVM_EFUSE_ERR_USER_KEY0_ALREADY_PRGMD User key 0 is already programmed.XNVM_EFUSE_ERR_USER_KEY1_ALREADY_PRGMD User key 1 is already programmed.XNVM_EFUSE_ERR_FUSE_PROTECTED Efuse is write protected.XNVM_EFUSE_ERR_WRITE_AES_KEY Error in writing Aes key.XNVM_EFUSE_ERR_WRITE_USER0_KEY Error in writing User key 0.XNVM_EFUSE_ERR_WRITE_USER1_KEY Error in writing User key 1.
static int XNvm_EfuseValidatePpkWriteReq(const XNvm_EfusePpkHash *Hash)
This function Validates all PPK Hash requested for programming.
Hash - Pointer to XNvm_EfusePpkHash structure which holds PpkHash data to be programmed to eFuse. XST_SUCCESS If reads successfully.XNVM_EFUSE_ERR_RD_SEC_CTRL_BITS Error in reading SecCtrl eFusesXNVM_EFUSE_ERR_PPK0_HASH_ALREADY_PRGMD Ppk0 hash already programmed.XNVM_EFUSE_ERR_PPK1_HASH_ALREADY_PRGMD Ppk1 hash already programmed.XNVM_EFUSE_ERR_PPK2_HASH_ALREADY_PRGMD Ppk2 hash already programmed.XNVM_EFUSE_ERR_FUSE_PROTECTED Efuse is write protected.XNVM_EFUSE_ERR_WRITE_PPK0_HASH Error in writing ppk0 hash.XNVM_EFUSE_ERR_WRITE_PPK1_HASH Error in writing ppk1 hash.XNVM_EFUSE_ERR_WRITE_PPK2_HASH Error in writing ppk2 hash.
static int XNvm_EfuseValidateUserFusesWriteReq(const XNvm_EfuseUserData *WriteUserFuses)
This function Validates all user fuses requested for programming.
WriteUserFuses - Pointer to XNvm_EfuseUserData structure. XST_SUCCESS If programming is successful.XNVM_EFUSE_ERR_BIT_CANT_REVERT Efuse bit can't be reverted.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_USER_FUSE_PGM_NOT_ALLOWED UserFuse program not allowed due to additional PPKs
static int XNvm_EfuseValidateDecOnlyWriteReq(const XNvm_EfuseData *WriteReq)
This function validates DEC_ONLY eFuse programming request.
WriteReq - Pointer to XNvm_EfuseData structure, which holds eFuse data to be programmed. XST_SUCCESS If validation is successful.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_DEC_ONLY_KEY_MUST_BE_PRGMD Aes key should be programmed for DEC_ONLY eFuse programming.XNVM_EFUSE_ERR_DEC_ONLY_IV_MUST_BE_PRGMD Blk IV should be programmed for DEC_ONLY eFuse programming.XNVM_EFUSE_ERR_DEC_ONLY_ALREADY_PRGMD If DEC_ONLY eFuse already programmed.
static int XNvm_EfuseValidateIV(const u32 *Iv, u32 Row)
This function validates single IV requested for programming bit by bit.
Iv - Pointer to Iv data to be programmed. Row - Start row of the Iv to be validated. XST_SUCCESS If validation is successful.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_BIT_CANT_REVERT If requested to revert the already programmed bit.XNVM_EFUSE_ERR_BEFORE_PROGRAMMING Error before programming
static int XNvm_ValidateBootEnvCtrlWriteReq(const XNvm_EfuseBootEnvCtrlBits *BootEnvCtrl)
This function Validates BootEncCtrl row for programming.
BootEnvCtrl - Pointer to BootEnvCtrl structure. XST_SUCCESS If programming is successful.XNVM_EFUSE_ERR_BOOT_ENV_CTRL_ALREADY_PRGMD Requested bits are already programmed.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.
static int XNvm_EfuseWritePufAux(u32 Aux)
This function programs the eFUSEs with the PUF Aux.
Aux - A 32-bit Aux to program the eFUSE. XST_SUCCESS If programs successfully.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.
static int XNvm_EfuseWritePufChash(u32 Chash)
This function programs the eFUSEs with the PUF Chash.
Chash - A 32-bit Chash to program the eFUSE. XST_SUCCESS If programs successfully.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.
static int XNvm_EfuseWritePufSynData(const u32 *SynData)
This function programs the eFUSEs with the PUF syndrome data.
SynData - Pointer to the Puf Syndrome data to program the eFUSE. XST_SUCCESS If programs successfully.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter. To generate PufSyndromeData please use XPuf_Registration API.
static int XNvm_EfuseWritePufSecCtrl(const XNvm_EfusePufSecCtrlBits *PufSecCtrlBits)
This function programs Puf control bits specified by user.
PufSecCtrlBits - Pointer to the XNvm_EfusePufSecCtrlBits structure, which holds the PufSecCtrlBits data to be written to the eFuse. XST_SUCCESS On success.XNVM_EFUSE_ERR_INVALID_PARAM Invalid parameter.XNVM_EFUSE_ERR_WRITE_PUF_REGEN_DIS Error while writing PUF_REGEN_DIS.XNVM_EFUSE_ERR_WRITE_PUF_HD_INVLD Error while writing PUF_HD_INVLD.XNVM_EFUSE_ERR_WRITE_PUF_SYN_LK Error while writing PUF_SYN_LK.XNVM_EFUSE_ERR_WRITE_PUF_TEST2_DIS Error while writing PUF_TEST2_DIS.XNVM_EFUSE_ERR_WRITE_PUF_DIS Error while writing PUF_DIS.
static int XNvm_EfuseIsPufHelperDataEmpty(void)
This function checks whether PUF is already programmed or not.
XST_SUCCESS If all rows are zero.XNVM_EFUSE_ERR_PUF_SYN_ALREADY_PRGMD Puf Syn data already programmed.XNVM_EFUSE_ERR_PUF_CHASH_ALREADY_PRGMD Puf chash already programmed.XNVM_EFUSE_ERR_PUF_AUX_ALREADY_PRGMD Puf Aux is already programmed.
static int XNvm_EfuseWriteSecCtrl(const XNvm_EfuseSecCtrlBits *SecCtrl)
This function programs secure control bits specified by user.
SecCtrl - Pointer to the XNvm_EfuseSecCtrlBits structure, which holds SecCtrlBits to be written to eFuse. XST_SUCCESS Specified bit set in eFUSE.XNVM_EFUSE_ERROR_INVALID_PARAM Invalid Parameter.XNVM_EFUSE_ERR_WRITE_AES_DIS Error while writing AES_DISXNVM_EFUSE_ERR_WRITE_PPK0_WR_LK Error while writing PPK0_WR_LK.XNVM_EFUSE_ERR_WRITE_PPK1_WR_LK Error while writing PPK1_WR_LK.XNVM_EFUSE_ERR_WRITE_PPK2_WR_LK Error while writing PPK2_WR_LK.XNVM_EFUSE_ERR_WRITE_AES_CRC_LK_BIT_0 Error while writing AES_CRC_LK_BIT_0.XNVM_EFUSE_ERR_WRITE_AES_CRC_LK_BIT_1 Error while writing AES_CRC_LK_BIT_1.XNVM_EFUSE_ERR_WRITE_AES_WR_LK Error while writing AES_WR_LK.XNVM_EFUSE_ERR_WRITE_USER_KEY0_WR_LK Error while writing USER_KEY0_WR_LK.XNVM_EFUSE_ERR_WRITE_USER_KEY1_WR_LK Error while writing USER_KEY1_WR_LK.XNVM_EFUSE_ERR_WRITE_USER_KEY0_CRC_LK Error while writing USER_KEY0_CRC_LK.XNVM_EFUSE_ERR_WRITE_USER_KEY1_CRC_LK Error while writing USER_KEY1_CRC_LK.XNVM_EFUSE_ERR_WRITE_SECDBG_DIS_BIT_0 Error while writing SECDBG_DIS_BIT_0.XNVM_EFUSE_ERR_WRITE_SECDBG_DIS_BIT_1 Error while writing SECDBG_DIS_BIT_1.XNVM_EFUSE_ERR_WRITE_BOOTENV_WR_LK Error while writing BOOTENV_WR_LK.XNVM_EFUSE_ERR_WRITE_REG_INIT_DIS_BIT_0 Error while writing REG_INIT_DIS_BIT_0.XNVM_EFUSE_ERR_WRITE_REG_INIT_DIS_BIT_1 Error while writing REG_INIT_DIS_BIT_1.XNVM_EFUSE_ERR_WRITE_HWTSTBITS_DIS Error while writing HWTSTBITS_DIS.XNVM_EFUSE_ERR_WRITE_PMC_SC_EN_BIT_0 Error while writing PMC_SC_EN_BIT_0XNVM_EFUSE_ERR_WRITE_PMC_SC_EN_BIT_1 Error while writing PMC_SC_EN_BIT_1XNVM_EFUSE_ERR_WRITE_PMC_SC_EN_BIT_2 Error while writing PMC_SC_EN_BIT_2
static int XNvm_EfusePrgmGlitchCfgValues(const XNvm_EfuseGlitchCfgBits *WriteGlitchCfg)
This function program Glitch Configuration.
WriteGlitchCfg - Pointer to glitch configuration data to be programmed to eFuse. XST_SUCCESS On Success.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_WRITE_GLITCH_CFG Error in programming of glitch configuration.
static int XNvm_EfusePrgmGlitchWriteLock(const XNvm_EfuseGlitchCfgBits *WriteGlitchCfg)
This function programs Glitch Write lock bit.
WriteGlitchCfg - Pointer to glitch configuration data to be written to eFuse. XST_SUCCESS On Success.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_WRITE_GLITCH_WRLK Error in programming glitch write lock.
static int XNvm_EfusePrgmGdRomMonEn(const XNvm_EfuseGlitchCfgBits *WriteGlitchCfg)
This function enables the glitch detection monitoring by ROM.
WriteGlitchCfg - Pointer to glitch configuration data. XST_SUCCESS On Success.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_WRITE_GD_ROM_BITS Error in programming of Glitch ROM monitor.
static int XNvm_EfusePrgmGdRomHaltBootEn(const XNvm_EfuseGlitchCfgBits *WriteGlitchCfg)
This function enables the halt boot by ROM upon glitch detection.
WriteGlitchCfg - Pointer to glitch configuration data to be written to eFuse. XST_SUCCESS On Success.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_WRITE_GD_ROM_BITS Error in programming of Glitch ROM monitor.
static int XNvm_EfusePrgmAesKeys(const XNvm_EfuseAesKeys *Keys)
This function is used to program below eFuses - AES key User key 0 User key 1.
Keys - Pointer to the XNvm_EfuseAesKeys structure, which holds Aes key data to be programmed to eFuse. XST_SUCCESS Specified data read.XNVM_EFUSE_ERR_INVALID_PARAM Invalid input parameterXNVM_EFUSE_ERR_BEFORE_PROGRAMMING Error before programming eFuse.XNVM_EFUSE_ERR_WRITE_AES_KEY Error while writing AES key.XNVM_EFUSE_ERR_WRITE_USER_KEY0 Error while writing User key0.XNVM_EFUSE_ERR_WRITE_USER_KEY1 Error while writing User key1.
static int XNvm_EfusePrgmPpkHash(const XNvm_EfusePpkHash *Hash)
This function is used to program below eFuses - PPK0/PPK1/PPK2 hash.
Hash - Pointer to the XNvm_EfusePpkHash structure which holds ppk hash data to be programmed to eFuse. XST_SUCCESS Specified data read.XNVM_EFUSE_ERR_INVALID_PARAM Invalid input parameter.XNVM_EFUSE_ERR_WRITE_PPK0_HASH Error while writing PPK0 Hash.XNVM_EFUSE_ERR_WRITE_PPK1_HASH Error while writing PPK1 Hash.XNVM_EFUSE_ERR_WRITE_PPK2_HASH Error while writing PPK2 Hash.
static int XNvm_EfusePrgmDecOnly(const XNvm_EfuseDecOnly *DecOnly)
This function is used to program below DEC_ONLY fuses.
DecOnly - Pointer to XNvm_EfuseDecOnly structure which holds DecOnly flag which says to program eFuse. XST_SUCCESS Specified data read.XNVM_EFUSE_ERR_INVALID_PARAM Invalid input parameter.XNVM_EFUSE_ERR_WRITE_DEC_EFUSE_ONLY Error in DEC_ONLY programming.
static int XNvm_EfusePrgmUserFuses(const XNvm_EfuseUserData *WriteUserFuses)
This function Programs User eFuses.
WriteUserFuses - Pointer to the XNvm_EfuseUserData structure. XST_SUCCESS If programming is successful.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_PGM_TIMEOUT eFUSE programming timed out.XNVM_EFUSE_ERR_PGM eFUSE programming failed.XNVM_EFUSE_ERR_PGM_VERIFY Verification failed, specified bit is not set.
static int XNvm_EfusePrgmIVs(const XNvm_EfuseIvs *Ivs)
This function is used to program all IVs.
Ivs - Pointer to the XNvm_EfuseIvs structure which holds IV data to be programmed to eFuse. XST_SUCCESS Specified data readXNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_WRITE_META_HEADER_IV_RANGE Error while writing Meta header Iv range.XNVM_EFUSE_ERR_WRITE_BLK_IV Error while writing BlkObfus IV.XNVM_EFUSE_ERR_WRITE_PLM_IV_RANGE Error while writing PLM IV.XNVM_EFUSE_ERR_WRITE_DATA_PARTITION_IV_RANGE Error while writing Data Partition IV.
static int XNvm_EfusePrgmPpkRevokeFuses(const XNvm_EfuseMiscCtrlBits *PpkSelect)
This function revokes the Ppk.
PpkSelect - Pointer to XNvm_EfuseMiscCtrlBits structure which holds PPK_INVALID bits data to be programmed to eFuse. XST_SUCCESS On Successful write of Ppk revoke efuses.XNVM_EFUSE_ERR_RD_MISC_CTRL_BITS Error in reading Misc_Ctrl eFUSEsXNVM_EFUSE_ERR_WRITE_PPK0_INVALID_BIT_0 Error in writing PPK0 Invalid bit0.XNVM_EFUSE_ERR_WRITE_PPK0_INVALID_BIT_1 Error in writing PPK0 Invalid bit1.XNVM_EFUSE_ERR_WRITE_PPK1_INVALID_BIT_0 Error in writing PPK1 Invalid bit0.XNVM_EFUSE_ERR_WRITE_PPK1_INVALID_BIT_1 Error in writing PPK1 Invalid bit1.XNVM_EFUSE_ERR_WRITE_PPK2_INVALID_BIT_0 Error in writing PPK2 Invalid bit0.XNVM_EFUSE_ERR_WRITE_PPK2_INVALID_BIT_1 Error in writing PPK2 Invalid bit1.
static int XNvm_EfusePrgmHaltBootonError(const XNvm_EfuseMiscCtrlBits *MiscCtrlData)
This function enables halt boot on general errors other than environmental and glitch identified by ROM.
MiscCtrlData - Pointer to XNvm_EfuseMiscCtrlBits structure which holds MiscCtrlBits data to be programmed to eFuse XST_SUCCESS On Success.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_WRITE_HALT_BOOT_BITS Error in programming of ROM flow control halt boot bits for generic and environment errors.
static int XNvm_EfusePrgmHaltBootEnvError(const XNvm_EfuseMiscCtrlBits *MiscCtrlData)
This function enables the halt boot on environmental errors identified by ROM.
MiscCtrlData - Pointer to XNvm_EfuseMiscCtrlBits structure which holds MiscCtrlBits data to be programmed to eFuse XST_SUCCESS On Success.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_WRITE_HALT_BOOT_BITS Error in programming of ROM flow control halt boot bits for generic and environment errors.
static int XNvm_EfusePrgmRevocationIdFuses(const XNvm_EfuseRevokeIds *RevokeIds)
This function programs Revocation Id eFuses.
RevokeIds - Pointer to XNvm_RevokeIdEfuse that contains Revocation Id to write. XST_SUCCESS On successful write of Revocation Id.XNVM_EFUSE_ERR_WRITE_REVOCATION_IDS Error in writing revoke id eFuses.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.
static int XNvm_EfusePrgmCryptoKatEn(const XNvm_EfuseMiscCtrlBits *MiscCtrlData)
This function programs CryptoKat eFuse in MiscCtrl eFuse row.
MiscCtrlData - Pointer to XNvm_EfuseMiscCtrlBits structure which holds MiscCtrlBits data to be programmed to eFuse XST_SUCCESS On Success.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_WRITE_CRYPTO_KAT_EN Error in writing CryptoKat eFuse.
static int XNvm_EfusePrgmLbistEn(const XNvm_EfuseMiscCtrlBits *MiscCtrlData)
This function programs LbistEn eFUSE in MiscCtrl eFUSE row.
MiscCtrlData - Pointer to XNvm_EfuseMiscCtrlBits structure which holds MiscCtrlBits data to be programmed to eFUSE. XST_SUCCESS On Success.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_WRITE_LBIST_EN Error in writing LbistEn eFUSE.
static int XNvm_EfusePrgmSafetyMissionEn(const XNvm_EfuseMiscCtrlBits *MiscCtrlData)
This function programs SafetyMissionEn eFUSE in MiscCtrl eFUSE row.
MiscCtrlData - Pointer to XNvm_EfuseMiscCtrlBits structure which holds MiscCtrlBits data to be programmed to eFUSE XST_SUCCESS On Success.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_WRITE_SAFETY_MISSION_EN Error in writing SafetyMissionEn eFUSE.
static int XNvm_EfusePrgmProtectionEfuse(void)
This function Programs Protection eFuses.
XST_SUCCESS If protection efuse programming is successful.XNVM_EFUSE_ERR_WRITE_ROW_43_0_PROT Error in programming Row 43 protection bit 0.XNVM_EFUSE_ERR_WRITE_ROW_43_1_PROT Error in programming Row 43 protection bit 1.XNVM_EFUSE_ERR_WRITE_ROW_57_0_PROT Error in programming Row 57 protection bit 0.XNVM_EFUSE_ERR_WRITE_ROW_57_1_PROT Error in programming Row 57 protection bit 1.XNVM_EFUSE_ERR_WRITE_ROW64_87_0_PROT Error in programming Row 64_87 protection bit 0.XNVM_EFUSE_ERR_WRITE_ROW64_87_1_PROT Error in programming Row 64_87 protection bit 1.XNVM_EFUSE_ERR_WRITE_ROW96_99_0_PROT Error in programming Row 96_99 protection bit 0.XNVM_EFUSE_ERR_WRITE_ROW96_99_1_PROT Error in programming Row 96_99 protection bit 1.XNVM_EFUSE_ERR_WRITE_ROW_40_PROT Error in programming Row 40 protection bit.XNVM_EFUSE_ERR_WRITE_ROW_37_PROT Error in programming Row 37 protection bit.XNVM_EFUSE_ERR_WRITE_ROW_42_PROT Error in programming row 42 protection bit.XNVM_EFUSE_ERR_WRITE_ROW_58_PROT Error in programming row 58 protection bit.
static int XNvm_EfusePrgmOffChipRevokeFuses(const XNvm_EfuseOffChipIds *OffChipIds)
This function programs OffChip Revoke eFuses.
OffChipIds - Pointer to XNvm_EfuseOffChipIds that contains OffChipId to write. XST_SUCCESS On successful write of OffChipId.XNVM_EFUSE_ERR_WRITE_OFFCHIP_REVOKE_IDS Error in writing OffChipId eFuses.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.
static int XNvm_EfuseWriteBootEnvCtrl(const XNvm_EfuseBootEnvCtrlBits *BootEnvCtrl)
This function programs Boot Environmental Control eFuses with values specified by user.
BootEnvCtrl Pointer to the XNvm_EfuseBootEnvCtrlBits structure, which holds the XNvm_EfuseBootEnvCtrlBits data to be written to the eFuse. XST_SUCCESS On success.XNVM_EFUSE_ERR_INVALID_PARAM Invalid parameter.XNVM_EFUSE_ERR_WRITE_BOOT_ENV_CTRL Error while writing BOOT_ENV_CTRL ROW.
static int XNvm_EfuseWriteSecMisc1Fuses(const XNvm_EfuseSecMisc1Bits *Misc1Bits)
This function programs security miscellaneous1 eFuses specified by user.
Misc1Bits Pointer to the XNvm_EfuseSecMisc1Bits structure, which holds the XNvm_EfuseSecMisc1Bits data to be written to the eFuse. XST_SUCCESS On success.XNVM_EFUSE_ERR_INVALID_PARAM Invalid parameter.XNVM_EFUSE_ERR_WRITE_SECURITY_MISC_1 Error while writing SECURITY_MISC1 ROW.
static int XNvm_EfuseIsAdditionalPpkEn(void)
This function is used to read the miscellaneous eFUSE control Enable bits from cache.
XST_SUCCESS On Successful read.XST_FAILURE On Read failureXNVM_EFUSE_5_PPKS_FEATURE_NOT_SUPPORTED On enable bits are not set.
int XNvm_EfuseWrite(const XNvm_EfuseData *WriteNvm)
This function is used as a wrapper to program below eFuses AES key User key 0 User key 1 PPK0/PPK1/PPK2/PPK3/PPK4 hash IVs Revocation Ids User Fuses Secure and Control bits.
Miscellaneous Control bits. Security Miscellaneous1 bits. BootEnvCtrl bits. WriteNvm - Pointer to Efuse data to be written. XST_SUCCESS On Specified data write.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_NTHG_TO_BE_PROGRAMMED If nothing is programmed.XNVM_EFUSE_ERR_BEFORE_PROGRAMMING If error before programming.XNVM_EFUSE_ERR_LOCK Lock eFUSE Control Register. After eFUSE programming is complete, the cache is automatically reloaded so all programmed eFUSE bits can be directly read from cache. If there is any CACHE_ERROR, user can reboot the system to reload the cache.
References XNvm_EfuseData::AesKeys, XNvm_EfuseData::BootEnvCtrl, XNvm_EfuseMiscCtrlBits::CryptoKatEn, XNvm_EfuseData::DecOnly, XNvm_EfuseData::EnvMonitorDis, XNvm_EfuseGlitchCfgBits::GdHaltBootEn, XNvm_EfuseGlitchCfgBits::GdRomMonitorEn, XNvm_EfuseData::GlitchCfgBits, XNvm_EfuseGlitchCfgBits::GlitchDetWrLk, XNvm_EfuseMiscCtrlBits::HaltBootEnv, XNvm_EfuseMiscCtrlBits::HaltBootError, XNvm_EfuseData::Ivs, XNvm_EfuseMiscCtrlBits::LbistEn, XNvm_EfuseData::Misc1Bits, XNvm_EfuseData::MiscCtrlBits, XNvm_EfuseData::OffChipIds, XNvm_EfuseData::PpkHash, XNvm_EfuseData::RevokeIds, XNvm_EfuseMiscCtrlBits::SafetyMissionEn, XNvm_EfuseData::SecCtrlBits, XNvm_EfuseData::SysMonInstPtr, XNvm_EfuseData::UserFuses, XNVM_EFUSE_ERR_BEFORE_PROGRAMMING, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_ERR_NTHG_TO_BE_PROGRAMMED, XNVM_EFUSE_MARGIN_RD, XNVM_EFUSE_MODE_PGM, XNvm_EfuseDisableProgramming, XNvm_EfuseLockController, XNvm_EfuseResetReadMode, XNvm_EfuseSetupController, XNvm_EfuseTempAndVoltChecks.
int XNvm_EfuseReadSecCtrlBits(XNvm_EfuseSecCtrlBits *SecCtrlBits)
This function is used to read the eFUSE secure control bits from cache.
This function reads secure control bits and CRC_EN register bits from eFUSE cache. SecCtrlBits - Pointer to the Xnvm_SecCtrlBits which holds the read secure control bits. XST_SUCCESS On Successful read.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_CACHE_PARITY Error while Cache reload.
References XNvm_EfuseSecCtrlBits::AesCrcLk, XNvm_EfuseSecCtrlBits::AesDis, XNvm_EfuseSecCtrlBits::AesRdlk, XNvm_EfuseSecCtrlBits::AesWrLk, XNvm_EfuseSecCtrlBits::BootEnvWrLk, XNvm_EfuseSecCtrlBits::CrcEn, XNvm_EfuseSecCtrlBits::CrcRmaDis, XNvm_EfuseSecCtrlBits::CrcRmaEn, XNvm_EfuseSecCtrlBits::DftDis, XNvm_EfuseSecCtrlBits::HashPufOrKey, XNvm_EfuseSecCtrlBits::HwTstBitsDis, XNvm_EfuseSecCtrlBits::JtagDis, XNvm_EfuseSecCtrlBits::JtagErrDis, XNvm_EfuseSecCtrlBits::JtagErrOutDis, XNvm_EfuseSecCtrlBits::Lckdwn, XNvm_EfuseSecCtrlBits::PmcScEn, XNvm_EfuseSecCtrlBits::Ppk0Invld, XNvm_EfuseSecCtrlBits::Ppk0lck, XNvm_EfuseSecCtrlBits::Ppk0WrLk, XNvm_EfuseSecCtrlBits::Ppk1Invld, XNvm_EfuseSecCtrlBits::Ppk1lck, XNvm_EfuseSecCtrlBits::Ppk1WrLk, XNvm_EfuseSecCtrlBits::Ppk2Invld, XNvm_EfuseSecCtrlBits::Ppk2lck, XNvm_EfuseSecCtrlBits::Ppk2WrLk, XNvm_EfuseSecCtrlBits::PufTes2Dis, XNvm_EfuseSecCtrlBits::RegInitDis, XNvm_EfuseSecCtrlBits::RmaDis, XNvm_EfuseSecCtrlBits::RmaEn, XNvm_EfuseSecCtrlBits::ScanClearEn, XNvm_EfuseSecCtrlBits::SecDbgDis, XNvm_EfuseSecCtrlBits::SecLockDbgDis, XNvm_EfuseSecCtrlBits::UserKey0CrcLk, XNvm_EfuseSecCtrlBits::UserKey0WrLk, XNvm_EfuseSecCtrlBits::UserKey1CrcLk, XNvm_EfuseSecCtrlBits::UserKey1WrLk, XNvm_EfuseSecCtrlBits::UserWrlk, XNVM_EFUSE_CACHE_SECURITY_CONTROL_AES_CRC_LK_1_0_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_AES_CRC_LK_1_0_SHIFT, XNVM_EFUSE_CACHE_SECURITY_CONTROL_AES_DIS_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_AES_WR_LK_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_AES_WR_LK_SHIFT, XNVM_EFUSE_CACHE_SECURITY_CONTROL_BOOT_ENV_WR_LK_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_BOOT_ENV_WR_LK_SHIFT, XNVM_EFUSE_CACHE_SECURITY_CONTROL_HWTSTBITS_DIS_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_HWTSTBITS_DIS_SHIFT, XNVM_EFUSE_CACHE_SECURITY_CONTROL_JTAG_DIS_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_JTAG_DIS_SHIFT, XNVM_EFUSE_CACHE_SECURITY_CONTROL_JTAG_ERROR_OUT_DIS_SHIFT, XNVM_EFUSE_CACHE_SECURITY_CONTROL_JTAG_ERROUT_DIS_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PMC_SC_EN_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PMC_SC_EN_SHIFT, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PPK0_WR_LK_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PPK0_WR_LK_SHIFT, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PPK1_WR_LK_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PPK1_WR_LK_SHIFT, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PPK2_WR_LK_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PPK2_WR_LK_SHIFT, XNVM_EFUSE_CACHE_SECURITY_CONTROL_REG_INIT_DIS_1_0_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_REG_INIT_DIS_1_0_SHIFT, XNVM_EFUSE_CACHE_SECURITY_CONTROL_SEC_DEBUG_DIS_1_0_SHIFT, XNVM_EFUSE_CACHE_SECURITY_CONTROL_SEC_DEBUG_DIS_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_SEC_LOCK_DBG_DIS_1_0_SHIFT, XNVM_EFUSE_CACHE_SECURITY_CONTROL_SEC_LOCK_DBG_DIS_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_USR_KEY_0_CRC_LK_0_SHIFT, XNVM_EFUSE_CACHE_SECURITY_CONTROL_USR_KEY_0_CRC_LK_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_USR_KEY_0_WR_LK_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_USR_KEY_0_WR_LK_SHIFT, XNVM_EFUSE_CACHE_SECURITY_CONTROL_USR_KEY_1_CRC_LK_0_SHIFT, XNVM_EFUSE_CACHE_SECURITY_CONTROL_USR_KEY_1_CRC_LK_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_USR_KEY_1_WR_LK_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_USR_KEY_1_WR_LK_SHIFT, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_SECURITY_CONTROL_ROW.
int XNvm_EfuseReadSecMisc1Bits(XNvm_EfuseSecMisc1Bits *SecMisc1Bits)
This function is used to read the security miscellaneous1 bits from cache.
SecMisc1Bits - Pointer to the XNvm_EfuseSecMisc1Bits which holds the security miscellaneous1 control bits. XST_SUCCESS On Successful read.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_CACHE_PARITY Error while Cache reload.
References XNvm_EfuseSecMisc1Bits::LpdMbistEn, XNvm_EfuseSecMisc1Bits::LpdNocScEn, XNvm_EfuseSecMisc1Bits::PmcMbistEn, XNvm_EfuseSecMisc1Bits::SysmonTempMonEn, XNvm_EfuseSecMisc1Bits::SysmonVoltMonEn, XNVM_EFUSE_CACHE_SEC_MISC_1_LPD_MBIST_EN_2_0_MASK, XNVM_EFUSE_CACHE_SEC_MISC_1_LPD_MBIST_EN_2_0_SHIFT, XNVM_EFUSE_CACHE_SEC_MISC_1_LPD_NOC_SC_EN_2_0_MASK, XNVM_EFUSE_CACHE_SEC_MISC_1_LPD_NOC_SC_EN_2_0_SHIFT, XNVM_EFUSE_CACHE_SEC_MISC_1_PMC_MBIST_EN_2_0_MASK, XNVM_EFUSE_CACHE_SEC_MISC_1_PMC_MBIST_EN_2_0_SHIFT, XNVM_EFUSE_CACHE_SEC_MISC_1_SYSMON_TEMP_MON_EN_1_0_MASK, XNVM_EFUSE_CACHE_SEC_MISC_1_SYSMON_TEMP_MON_EN_1_0_SHIFT, XNVM_EFUSE_CACHE_SEC_MISC_1_SYSMON_VOLT_MON_EN_1_0_MASK, XNVM_EFUSE_CACHE_SEC_MISC_1_SYSMON_VOLT_MON_EN_1_0_SHIFT, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_SECURITY_MISC_1_ROW.
int XNvm_EfuseReadBootEnvCtrlBits(XNvm_EfuseBootEnvCtrlBits *BootEnvCtrlBits)
This function reads the Boot Environmental Control bits from cache.
BootEnvCtrlBits - Pointer to the XNvm_EfuseBootEnvCtrlBits which holds the Boot Environmental control bits. XST_SUCCESS On Successful read.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_CACHE_PARITY Error while Cache reload.
References XNvm_EfuseBootEnvCtrlBits::SysmonTempCold, XNvm_EfuseBootEnvCtrlBits::SysmonTempEn, XNvm_EfuseBootEnvCtrlBits::SysmonTempHot, XNvm_EfuseBootEnvCtrlBits::SysmonVoltEn, XNvm_EfuseBootEnvCtrlBits::SysmonVoltPmc, XNvm_EfuseBootEnvCtrlBits::SysmonVoltPslp, XNvm_EfuseBootEnvCtrlBits::SysmonVoltSoc, XNVM_EFUSE_BOOT_ENV_CTRL_ROW, XNVM_EFUSE_CACHE_BOOT_ENV_CTRL_SYSMON_TEMP_COLD_MASK, XNVM_EFUSE_CACHE_BOOT_ENV_CTRL_SYSMON_TEMP_COLD_SHIFT, XNVM_EFUSE_CACHE_BOOT_ENV_CTRL_SYSMON_TEMP_EN_MASK, XNVM_EFUSE_CACHE_BOOT_ENV_CTRL_SYSMON_TEMP_EN_SHIFT, XNVM_EFUSE_CACHE_BOOT_ENV_CTRL_SYSMON_TEMP_HOT_MASK, XNVM_EFUSE_CACHE_BOOT_ENV_CTRL_SYSMON_TEMP_HOT_SHIFT, XNVM_EFUSE_CACHE_BOOT_ENV_CTRL_SYSMON_VOLT_EN_MASK, XNVM_EFUSE_CACHE_BOOT_ENV_CTRL_SYSMON_VOLT_EN_SHIFT, XNVM_EFUSE_CACHE_BOOT_ENV_CTRL_SYSMON_VOLT_PMC_MASK, XNVM_EFUSE_CACHE_BOOT_ENV_CTRL_SYSMON_VOLT_PMC_SHIFT, XNVM_EFUSE_CACHE_BOOT_ENV_CTRL_SYSMON_VOLT_PSLP_MASK, XNVM_EFUSE_CACHE_BOOT_ENV_CTRL_SYSMON_VOLT_PSLP_SHIFT, XNVM_EFUSE_CACHE_BOOT_ENV_CTRL_SYSMON_VOLT_SOC_MASK, XNVM_EFUSE_CACHE_BOOT_ENV_CTRL_SYSMON_VOLT_SOC_SHIFT, XNVM_EFUSE_ERR_INVALID_PARAM.
int XNvm_EfuseWritePuf(const XNvm_EfusePufHd *PufHelperData)
This function programs the eFUSEs with the PUF helper data.
PufHelperData - Pointer to the Puf helper data to be written to eFuse. XST_SUCCESS If programs successfully.XNVM_EFUSE_ERR_INVALID_PARAM Input validation failureXNVM_EFUSE_ERR_RD_PUF_SEC_CTRL Error while reading PufSecCtrl.XNVM_EFUSE_ERR_WRITE_PUF_HELPER_DATA Error while writing Puf helper data.XNVM_EFUSE_ERR_WRITE_PUF_SYN_DATA Error while writing Puf Syndata.XNVM_EFUSE_ERR_WRITE_PUF_CHASH Error while writing Puf Chash. XNVM_EFUSE_ERR_WRITE_PUF_AUX Error while writing Puf Aux. XNVM_EFUSE_ERR_FUSE_PROTECTED Error if Puf is protected from writeXNVM_EFUSE_ERR_BEFORE_PROGRAMMING Error before programming To generate PufSyndromeData please use XPuf_Registration API.
References XNvm_EfusePufHd::Aux, XNvm_EfusePufHd::Chash, XNvm_EfusePufHd::EfuseSynData, XNvm_EfusePufHd::EnvMonitorDis, XNvm_EfusePufHd::PrgmPufHelperData, XNvm_EfusePufHd::PrgmPufSecCtrlBits, XNvm_EfusePufHd::PufSecCtrlBits, XNvm_EfusePufHd::SysMonInstPtr, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PUF_DIS_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PUF_SYN_LK_MASK, XNVM_EFUSE_ERR_BEFORE_PROGRAMMING, XNVM_EFUSE_ERR_FUSE_PROTECTED, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_ERR_WRITE_PUF_AUX, XNVM_EFUSE_ERR_WRITE_PUF_CHASH, XNVM_EFUSE_ERR_WRITE_PUF_HELPER_DATA, XNVM_EFUSE_ERR_WRITE_PUF_SYN_DATA, XNVM_EFUSE_MARGIN_RD, XNVM_EFUSE_MODE_PGM, XNVM_EFUSE_SEC_DEF_VAL_ALL_BIT_SET, XNVM_EFUSE_SECURITY_CONTROL_ROW, XNvm_EfuseDisableProgramming, XNvm_EfuseLockController, XNvm_EfuseResetReadMode, XNvm_EfuseSetupController, XNvm_EfuseTempAndVoltChecks.
int XNvm_EfuseReadPufSecCtrlBits(XNvm_EfusePufSecCtrlBits *PufSecCtrlBits)
This function is used to read the Puf eFUSE secure control bits from cache.
PufSecCtrlBits - Pointer to the XNvm_PufSecCtrlBits, which holds the read secure control bits. XST_SUCCESS On Successful read.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_CACHE_PARITY Error while Cache reload.
References XNvm_EfusePufSecCtrlBits::PufDis, XNvm_EfusePufSecCtrlBits::PufHdInvalid, XNvm_EfusePufSecCtrlBits::PufRegenDis, XNvm_EfusePufSecCtrlBits::PufSynLk, XNvm_EfusePufSecCtrlBits::PufTest2Dis, XNVM_EFUSE_CACHE_PUF_ECC_PUF_CTRL_HD_INVLD_MASK, XNVM_EFUSE_CACHE_PUF_ECC_PUF_CTRL_PUF_HD_INVLD_SHIFT, XNVM_EFUSE_CACHE_PUF_ECC_PUF_CTRL_PUF_REGEN_DIS_SHIFT, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PUF_DIS_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PUF_DIS_SHIFT, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PUF_SYN_LK_SHIFT, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PUF_TEST2_DIS_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PUF_TEST2_DIS_SHIFT, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_PUF_AUX_ROW, XNVM_EFUSE_SECURITY_CONTROL_ROW.
int XNvm_EfuseReadMiscCtrlBits(XNvm_EfuseMiscCtrlBits *MiscCtrlBits)
This function is used to read the miscellaneous eFUSE control bits from cache.
MiscCtrlBits - Pointer to the XNvm_MiscCtrlBits which holds the read secure control bits. XST_SUCCESS On Successful read.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_CACHE_PARITY Error while Cache reload.
References XNvm_EfuseMiscCtrlBits::CryptoKatEn, XNvm_EfuseMiscCtrlBits::GlitchDetHaltBootEn, XNvm_EfuseMiscCtrlBits::GlitchDetRomMonitorEn, XNvm_EfuseMiscCtrlBits::HaltBootEnv, XNvm_EfuseMiscCtrlBits::HaltBootError, XNvm_EfuseMiscCtrlBits::LbistEn, XNvm_EfuseMiscCtrlBits::Ppk0Invalid, XNvm_EfuseMiscCtrlBits::Ppk1Invalid, XNvm_EfuseMiscCtrlBits::Ppk2Invalid, XNvm_EfuseMiscCtrlBits::SafetyMissionEn, XNVM_EFUSE_CACHE_MISC_CTRL_ADD_PPK_1_0_MASK, XNVM_EFUSE_CACHE_MISC_CTRL_ADD_PPK_EN_SHIFT, XNVM_EFUSE_CACHE_MISC_CTRL_CRYPTO_KAT_EN_MASK, XNVM_EFUSE_CACHE_MISC_CTRL_CRYPTO_KAT_EN_SHIFT, XNVM_EFUSE_CACHE_MISC_CTRL_GD_HALT_BOOT_EN_1_0_MASK, XNVM_EFUSE_CACHE_MISC_CTRL_GD_HALT_BOOT_EN_1_0_SHIFT, XNVM_EFUSE_CACHE_MISC_CTRL_GD_ROM_MONITOR_EN_MASK, XNVM_EFUSE_CACHE_MISC_CTRL_GD_ROM_MONITOR_EN_SHIFT, XNVM_EFUSE_CACHE_MISC_CTRL_HALT_BOOT_ENV_1_0_MASK, XNVM_EFUSE_CACHE_MISC_CTRL_HALT_BOOT_ENV_1_0_SHIFT, XNVM_EFUSE_CACHE_MISC_CTRL_HALT_BOOT_ERROR_1_0_MASK, XNVM_EFUSE_CACHE_MISC_CTRL_HALT_BOOT_ERROR_1_0_SHIFT, XNVM_EFUSE_CACHE_MISC_CTRL_LBIST_EN_MASK, XNVM_EFUSE_CACHE_MISC_CTRL_LBIST_EN_SHIFT, XNVM_EFUSE_CACHE_MISC_CTRL_PPK0_INVLD_1_0_MASK, XNVM_EFUSE_CACHE_MISC_CTRL_PPK0_INVLD_1_0_SHIFT, XNVM_EFUSE_CACHE_MISC_CTRL_PPK1_INVLD_1_0_MASK, XNVM_EFUSE_CACHE_MISC_CTRL_PPK1_INVLD_1_0_SHIFT, XNVM_EFUSE_CACHE_MISC_CTRL_PPK2_INVLD_1_0_MASK, XNVM_EFUSE_CACHE_MISC_CTRL_PPK2_INVLD_1_0_SHIFT, XNVM_EFUSE_CACHE_MISC_CTRL_PPK3_INVLD_1_0_MASK, XNVM_EFUSE_CACHE_MISC_CTRL_PPK3_INVLD_1_0_SHIFT, XNVM_EFUSE_CACHE_MISC_CTRL_PPK4_INVLD_1_0_MASK, XNVM_EFUSE_CACHE_MISC_CTRL_PPK4_INVLD_1_0_SHIFT, XNVM_EFUSE_CACHE_MISC_CTRL_SAFETY_MISSION_EN_MASK, XNVM_EFUSE_CACHE_MISC_CTRL_SAFETY_MISSION_EN_SHIFT, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_MISC_CTRL_ROW.
int XNvm_EfuseWriteIVs(XNvm_EfuseIvs *EfuseIv, XSysMonPsv *SysMonInstPtr)
This function programs the eFUSEs with the IV.
EfuseIv - Pointer to the XNvm_EfuseIvs, which contains IVs data to be written to the Efuse.. SysMonInstPtr - Pointer to the XSysMonPsv structure which contains XSysmonPsv driver instance data XST_SUCCESS On Successful Write.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_WRITE_META_HEADER_IV Error while writing MetaHeader Iv.XNVM_EFUSE_ERR_WRITE_BLK_OBFUS_IV Error while writing BlkObfus IV.XNVM_EFUSE_ERR_WRITE_PLM IV Error while writing PLM IV.XNVM_EFUSE_ERR_WRITE_DATA_PARTITION_IV Error while writing Data Partition IV.XNVM_EFUSE_ERR_NTHG_TO_BE_PROGRAMMED If NULL request is sent.
References XNvm_EfuseData::EnvMonitorDis, XNvm_EfuseData::Ivs, XNvm_EfuseData::SysMonInstPtr, XNVM_EFUSE_ERR_NTHG_TO_BE_PROGRAMMED, XNvm_EfuseWrite.
int XNvm_EfuseReadIv(XNvm_Iv *EfuseIv, XNvm_IvType IvType)
This function is used to read IV eFUSE bits from cache.
EfuseIv - Pointer to the XNvm_Iv, which contains read IV data. IvType - Iv to be read. XST_SUCCESS On Successful read.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_RD_META_HEADER_IV_RANGE Error while reading MetaHeader IV.XNVM_EFUSE_ERR_RD_BLACK_IV Error while reading BlkObfus IV.XNVM_EFUSE_ERR_RD_PLM_IV_RANGE Error while reading PLM IV.XNVM_EFUSE_ERR_RD_DATA_PARTITION_IV_RANGE Error while reading Data Partition IV.XNVM_EFUSE_ERR_IN_ZEROIZATION Error in zeroization.
References XNvm_Iv::Iv, XNVM_EFUSE_BLACK_IV, XNVM_EFUSE_BLACK_OBFUS_IV_START_ROW, XNVM_EFUSE_DATA_PARTITION_IV_RANGE, XNVM_EFUSE_DATA_PARTITION_IV_START_ROW, XNVM_EFUSE_ERR_IN_ZEROIZATION, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_ERR_RD_BLACK_IV, XNVM_EFUSE_ERR_RD_DATA_PARTITION_IV_RANGE, XNVM_EFUSE_ERR_RD_META_HEADER_IV_RANGE, XNVM_EFUSE_ERR_RD_PLM_IV_RANGE, XNVM_EFUSE_IV_NUM_OF_ROWS, XNVM_EFUSE_META_HEADER_IV_RANGE, XNVM_EFUSE_META_HEADER_IV_START_ROW, XNVM_EFUSE_PLM_IV_RANGE, XNVM_EFUSE_PLM_IV_START_ROW, XNvm_EfuseReadCacheRange, XNvm_ZeroizeAndVerify.
int XNvm_EfuseReadPuf(XNvm_EfusePufHd *PufHelperData)
This function reads the PUF helper data from eFUSE cache.
PufHelperData - Pointer to XNvm_EfusePufHd which holds the PUF helper data read from eFUSEs. XST_SUCCESS On successful read.XNVM_EFUSE_ERR_RD_PUF_SYN_DATA Error while reading SYN_DATA.XNVM_EFUSE_ERR_RD_PUF_CHASH Error while reading CHASH.XNVM_EFUSE_ERR_RD_PUF_AUX Error while reading AUX.
References XNvm_EfusePufHd::Aux, XNvm_EfusePufHd::Chash, XNvm_EfusePufHd::EfuseSynData, XNVM_EFUSE_CACHE_PUF_ECC_PUF_CTRL_ECC_23_0_MASK, XNVM_EFUSE_ERR_IN_ZEROIZATION, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_ERR_RD_PUF_AUX, XNVM_EFUSE_ERR_RD_PUF_CHASH, XNVM_EFUSE_ERR_RD_PUF_SYN_DATA, XNVM_EFUSE_PAGE_2, XNVM_EFUSE_PUF_AUX_ROW, XNVM_EFUSE_PUF_CHASH_ROW, XNVM_EFUSE_PUF_SYN_DATA_NUM_OF_ROWS, XNVM_EFUSE_PUF_SYN_START_ROW, XNvm_EfuseReadCacheRange, XNVM_NUM_OF_ROWS_PER_PAGE, XNvm_ZeroizeAndVerify.
int XNvm_EfuseReadDna(XNvm_Dna *EfuseDna)
This function is used to read Dna eFUSE bits from cache.
EfuseDna - Pointer to the XNvm_Dna, which holds the read DNA. XST_SUCCESS On Successful read.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid parameter.XNVM_EFUSE_ERR_RD_DNA Error in reading DNA efuses.
References XNvm_Dna::Dna, XNVM_EFUSE_DNA_NUM_OF_ROWS, XNVM_EFUSE_DNA_START_ROW, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_ERR_RD_DNA, XNvm_EfuseReadCacheRange.
int XNvm_EfuseReadDecOnly(u32 *DecOnly)
This function is used to read DecEfuseOnly eFUSE bits from cache.
This function reads DEC only fuses from eFUSE cache. DecOnly - Pointer to the DecOnly efuse data. XST_SUCCESS On Successful read.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_RD_DEC_ONLY Error in reading in Dec_only efuses. If DecOnly eFuse is programmed that means boot can happen in only Symmetric HWRoT boot mode.
References XNVM_EFUSE_DEC_EFUSE_ONLY_ROW, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_ERR_RD_DEC_ONLY.
int XNvm_EfuseReadPpkHash(XNvm_PpkHash *EfusePpk, XNvm_PpkType PpkType)
This function reads the Ppk Hash from eFUSE cache.
EfusePpk - Pointer to XNvm_PpkHash which holds the PpkHash from eFUSE Cache. PpkType - Type of the Ppk to be programmed. XST_SUCCESS On Successful read.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_RD_PPK_HASH Error while reading PPK Hash.
References XNvm_PpkHash::Hash, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_ERR_RD_PPK_HASH, XNVM_EFUSE_PPK0, XNVM_EFUSE_PPK1, XNVM_EFUSE_PPK2, XNVM_EFUSE_PPK_0_HASH_START_ROW, XNVM_EFUSE_PPK_1_HASH_START_ROW, XNVM_EFUSE_PPK_2_HASH_START_ROW, XNVM_EFUSE_PPK_3_HASH_START_ROW, XNVM_EFUSE_PPK_4_HASH_START_ROW, XNVM_EFUSE_PPK_HASH_NUM_OF_ROWS, XNvm_EfuseReadCacheRange.
int XNvm_EfuseRevokePpk(XNvm_PpkType PpkRevoke, XSysMonPsv *SysMonInstPtr)
This function revokes the Ppk.
PpkRevoke - Xnvm_RevokePpkFlags that tells which Ppk to revoke. SysMonInstPtr - Pointer to the XSysMonPsv structure which contains XSysmonPsv driver instance data XST_SUCCESS On Successful Revocation.XNVM_EFUSE_ERR_INVALID_PARAM Input validation failure.
References XNvm_EfuseData::EnvMonitorDis, XNvm_EfuseData::MiscCtrlBits, XNvm_EfuseMiscCtrlBits::Ppk0Invalid, XNvm_EfuseMiscCtrlBits::Ppk1Invalid, XNvm_EfuseMiscCtrlBits::Ppk2Invalid, XNvm_EfuseData::SysMonInstPtr, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_PPK0, XNVM_EFUSE_PPK1, XNVM_EFUSE_PPK2, XNvm_EfuseWrite.
int XNvm_EfuseWriteRevocationId(u32 RevokeId, XSysMonPsv *SysMonInstPtr)
This function writes Revocation eFuses.
RevokeId - RevokeId number to program Revocation Id eFuses. SysMonInstPtr - Pointer to the XSysMonPsv structure which contains XSysmonPsv driver instance data XST_SUCCESS On successful write to eFuse.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_LOCK Error while Locking the controller. Example: If the revoke id to program is 64, it will program the 0th bit of the REVOCATION_ID_2 eFuse row.
References XNvm_EfuseData::EnvMonitorDis, XNvm_EfuseRevokeIds::PrgmRevokeId, XNvm_EfuseRevokeIds::RevokeId, XNvm_EfuseData::RevokeIds, XNvm_EfuseData::SysMonInstPtr, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_MAX_BITS_IN_ROW, XNvm_EfuseWrite, XNVM_MAX_REVOKE_ID_FUSES.
int XNvm_EfuseReadRevocationId(u32 *RevokeFusePtr, XNvm_RevocationId RevokeFuseNum)
This function reads the Revocation Fuse from eFUSE cache.
RevokeFusePtr - Pointer to the data which hold the Revocation IDs from eFUSE Cache. RevokeFuseNum - Revocation ID fuse number to read. XST_SUCCESS On successful read.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_CACHE_PARITY Error in Cache reload.
References XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_REVOCATION_ID_0_ROW, XNVM_EFUSE_REVOCATION_ID_7.
int XNvm_EfuseReadOffchipRevokeId(u32 *OffchipIdPtr, XNvm_OffchipId OffchipIdNum)
This function reads the Offchip revoke eFuse value from eFUSE cache.
OffchipIdPtr - Pointer to the data which hold the Offchip revoke ID values. OffchipIdNum - Offchip fuse number to read. XST_SUCCESS On successful read.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_CACHE_PARITY Error in Cache reload.
References XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_OFFCHIP_REVOKE_0_ROW, XNVM_EFUSE_OFFCHIP_REVOKE_ID_0, XNVM_EFUSE_OFFCHIP_REVOKE_ID_7.
int XNvm_EfuseReadUserFuses(const XNvm_EfuseUserData *UserFusesData)
This function reads User eFuses from Cache.
UserFusesData - UserFuseData to be read from eFuse Cache. XST_SUCCESS If reads successfully.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_RD_USER_FUSES Error in reading User fuses.
References XNvm_EfuseUserData::NumOfUserFuses, XNvm_EfuseUserData::StartUserFuseNum, XNvm_EfuseUserData::UserFuseData, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_ERR_RD_USER_FUSES, XNVM_EFUSE_USER_FUSE_START_ROW, XNvm_EfuseReadCacheRange, XNVM_NUM_OF_USER_FUSES, XNVM_USER_FUSE_END_NUM, XNVM_USER_FUSE_START_NUM.
int XNvm_EfuseWriteUserFuses(XNvm_EfuseUserData *WriteUserFuses, XSysMonPsv *SysMonInstPtr)
This function Programs User eFuses.
WriteUserFuses - Pointer to the XNvm_EfuseUserData structure. SysMonInstPtr - Pointer to the XSysMonPsv structure which contains XSysmonPsv driver instance data XST_SUCCESS If programming is successful.XNVM_EFUSE_ERR_NTHG_TO_BE_PROGRAMMED If NULL request is sent.
References XNvm_EfuseData::EnvMonitorDis, XNvm_EfuseData::SysMonInstPtr, XNvm_EfuseData::UserFuses, XNVM_EFUSE_ERR_NTHG_TO_BE_PROGRAMMED, XNvm_EfuseWrite.
int XNvm_EfuseReadCacheRange(u32 StartRow, u8 RowCount, u32 *RowData)
This function reads 32-bit rows from eFUSE cache.
StartRow - Starting Row number (0-based addressing). RowCount - Number of Rows to be read. RowData - Pointer to memory location where read 32-bit row data(s) is to be stored. XST_SUCCESS Specified data read.XNVM_EFUSE_ERR_INVALID_PARAM Input validation failure.XNVM_EFUSE_ERR_CACHE_PARITY Parity Error exist in cache.
Referenced by XNvm_EfuseReadDna, XNvm_EfuseReadIv, XNvm_EfuseReadPpkHash, XNvm_EfuseReadPuf, XNvm_EfuseReadUserFuses.
static int XNvm_EfuseProtectionChecks(void)
This function performs the Protection checks when the eFuse cache is reloaded.
XST_SUCCESS On successful protection checks.XNVM_EFUSE_ERR_IN_PROTECTION_CHECK Error in protection checkXNVM_EFUSE_ERR_ANCHOR_BIT_PATTERN Error in Anchor bits pattern
static int XNvm_EfusePrgmIv(XNvm_IvType IvType, XNvm_Iv *EfuseIv)
This function is used to program below IV eFuses XNVM_EFUSE_ERR_WRITE_META_HEADER_IV / XNVM_EFUSE_ERR_WRITE_BLK_OBFUS_IV / XNVM_EFUSE_ERR_WRITE_PLM_IV / XNVM_EFUSE_ERR_WRITE_DATA_PARTITION_IV.
IvType - Type of IV eFuses to be programmmed EfuseIv - Pointer to the XNvm_Iv structure which holds IV to be programmed to eFuse. XST_SUCCESS On Successful Programming.XNVM_EFUSE_ERR_WRITE_META_HEADER_IV Error while writing Meta Iv.XNVM_EFUSE_ERR_WRITE_BLK_OBFUS_IV Error while writing BlkObfus IV.XNVM_EFUSE_ERR_WRITE_PLM_IV Error while writing PLM IV.XNVM_EFUSE_ERR_WRITE_DATA_PARTITION_IV Error while writing Data Partition IV.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid input parameter.XNVM_EFUSE_ERR_BEFORE_PROGRAMMING Error before programming.
static int XNvm_EfusePrgmPpkHash(XNvm_PpkType PpkType, XNvm_PpkHash *EfuseHash)
This function is used to program below eFuses PPK0/PPK1/PPK2 hash.
PpkType - Type of ppk hash to be programmed(PPK0/PPK1/PPK2) EfuseHash - Pointer to the XNvm_PpkHash structure which holds PPK hash to be programmed to eFuse. XST_SUCCESS On Successful Programming.XNVM_EFUSE_ERR_WRITE_PPK0_HASH Error while writing PPK0 Hash.XNVM_EFUSE_ERR_WRITE_PPK1_HASH Error while writing PPK1 Hash.XNVM_EFUSE_ERR_WRITE_PPK2_HASH Error while writing PPK2 Hash.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid input parameter.XNVM_EFUSE_ERR_BEFORE_PROGRAMMING Error before programming.
static int XNvm_EfusePrgmAesKey(XNvm_AesKeyType KeyType, XNvm_AesKey *EfuseKey)
This function is used to program below eFuses AES key/User key 0/User key 1.
KeyType - Type of key to be programmed (AesKey/UserKey0/UserKey1) EfuseKey - Pointer to the XNvm_AesKey structure, which holds Aes key to be programmed to eFuse. XST_SUCCESS On Successful Programming.XNVM_EFUSE_ERR_WRITE_AES_KEY Error while writing AES key.XNVM_EFUSE_ERR_WRITE_USER_KEY0 Error while writing User key 0.XNVM_EFUSE_ERR_WRITE_USER_KEY1 Error while writing User key 1.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid input parameter.
static int XNvm_EfusePgmAndVerifyData(XNvm_EfusePrgmInfo *EfusePrgmInfo, const u32 *RowData)
This function sets and then verifies the specified bits in the eFUSE.
EfusePrgmInfo - Pointer to XNvm_EfusePrgmInfo structure stores the info required to program the eFuses RowData - Pointer to memory location where bitmap to be written is stored. Only bit set are used for programming eFUSE. XST_SUCCESS Specified bit set in eFUSE.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.
static int XNvm_EfusePgmAndVerifyBit(XNvm_EfuseType Page, u32 Row, u32 Col, u32 SkipVerify)
This function sets and then verifies the specified bit in the eFUSE.
Page - It is an enum variable of type XNvm_EfuseType. Row - It is an 32-bit Row number (0-based addressing). Col - It is an 32-bit Col number (0-based addressing). SkipVerify - Skips verification of bit if set to non zero XST_SUCCESS Specified bit set in eFUSE.XNVM_EFUSE_ERR_PGM_TIMEOUT eFUSE programming timed out.XNVM_EFUSE_ERR_PGM eFUSE programming failed.XNVM_EFUSE_ERR_PGM_VERIFY Verification failed, specified bit is not set.XST_FAILURE Unexpected error.
static int XNvm_EfuseCloseController(void)
This function performs all close operation of eFuse controller, resets the read mode, disables programming mode and locks the controller back.
XST_SUCCESS On Successful close.XST_FAILURE On Failure.
static int XNvm_EfusePrgmFipsInfo(u32 FipsMode, u32 FipsVersion)
This function is used to program FIPS mode and FIPS version eFuses.
FipsMode - Fips mode to be written to eFuses. FipsVersion - Fips version to be written to eFuses. XST_SUCCESS On successful write.XST_FAILURE Upon failure.
static int XNvm_EfusePrgmDmeUserKey(XNvm_DmeKeyType KeyType, const XNvm_DmeKey *EfuseKey)
This function programs DME userkey eFuses.
KeyType - DME UserKey0/1/2/3. EfuseKey - Pointer to the XNvm_DmeKey structure. XST_SUCCESS On successful write. XNVM_EFUSE_ERR_INVALID_PARAM On invalid input parameter. XNVM_ERR_DME_KEY_ALREADY_PROGRAMMED If requested DME key is already programmed.
static int XNvm_EfuseWriteRoSwapEn(u32 RoSwap)
This function programs the eFUSEs with th RO_SWAP_EN.
RoSwap - A 32-bit RoSwap to program the eFUSE. XST_SUCCESS if programs successfully.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid input parameter.XNVM_EFUSE_ERR_BEFORE_PROGRAMMING Error before programming.
static int XNvm_UdsCrcCalc(const u32 *Uds)
This function calculates CRC of UDS.
Uds - Pointer to buffer which contains UDS CRC of UDS.
static int XNvm_EfuseCacheReloadAndProtectionChecks(void)
This function reloads the cache of eFUSE and check protection eFuses.
XST_SUCCESS On Successful Cache Reload.XNVM_EFUSE_ERR_CACHE_LOAD Error while loading the cache. Not recommended to call this API frequently,if this API is called all the cache memory is reloaded by reading eFUSE array, reading eFUSE bit multiple times may diminish the life time.
static int XNvm_EfusePrgmProtectionBits(void)
This function programs the Protection eFuses.
XST_SUCCESS If protection efuse programming is successful.XNVM_EFUSE_ERR_WRITE_ROW_0_SEC_CTRL_0_PROT Error while writing SecCtrl Prot 0 eFuseXNVM_EFUSE_ERR_WRITE_ROW_0_SEC_CTRL_1_PROT Error while writing SecCtrl Prot 1 eFuseXNVM_EFUSE_ERR_WRITE_ROW_0_SEC_MISC0_0_PROT Error while writing MiscCtrl Prot 0 eFuseXNVM_EFUSE_ERR_WRITE_ROW_0_SEC_MISC0_1_PROT Error while writing MiscCtrl Prot 1 eFuseXNVM_EFUSE_ERR_WRITE_ROW_0_PPK_HASH_0_PROT Error while writing PpkHash Prot 0 eFuseXNVM_EFUSE_ERR_WRITE_ROW_0_PPK_HASH_1_PROT Error while writing PpkHash Prot 1 eFuseXNVM_EFUSE_ERR_WRITE_ROW_0_METAHEADER_0_PROT Error while writing MetaHeader IV Prot 0 eFuseXNVM_EFUSE_ERR_WRITE_ROW_0_METAHEADER_1_PROT Error while writing MetaHeader IV Prot 1 eFuseXNVM_EFUSE_ERR_WRITE_ROW_0_CRC_0_PROT Error while writing CRC Prot 0 eFuseXNVM_EFUSE_ERR_WRITE_ROW_0_CRC_1_PROT Error while writing CRC Prot 1 eFuseXNVM_EFUSE_ERR_WRITE_ROW_0_PUF_CHASH_PROT Error while writing Puf CHash Prot eFuseXNVM_EFUSE_ERR_WRITE_ROW_0_SEC_MISC1_PROT Error while writing SecMisc1 Prot eFuse
static int XNvm_EfuseChangeEndianness(u8 *Dest, u8 *Src, u32 Size)
This function changes the endianness of Data of given size.
Dest Pointer to the destination buffer Src Pointer to the source buffer Size Size of the Data XST_SUCCESS On successful conversionXNVM_EFUSE_ERR_INVALID_PARAM If size is not word-alignedXST_FAILURE On failure
static int XNvm_EfuseReadRow(XNvm_EfuseType Page, u32 Row, u32 *RegData)
This function verify the specified bit set in the eFUSE.
Page - It is an enum variable of type XNvm_EfuseType. Row - It is an 32-bit Row number (0-based addressing). RegData - Pointer to the register value. XST_SUCCESS Specified bit set in eFUSE.XNVM_EFUSE_ERR_PGM_VERIFY Verification failed, specified bit is not set.XNVM_EFUSE_ERR_PGM_TIMEOUT If Programming timeout has occurred.XST_FAILURE Unexpected error.
static u32 XNvm_EfuseCalculateCrc32(const u8 *Data, u32 Len)
This function Calculates the 32-bit CRC using CRC32 algorithm.
This function uses lookup table to speedup the calculation. Data - Input Data over which CRC is to be calculated Len - Length of the input data Crc - 32-bit CRC Value
static int XNvm_EfuseValidateCrc(void)
This function calculate CRC on below eFUSE cache registers and compares against eFUSE CRC value.
Register Name Register Address ANLG_TRIM_0 0xF1250004 ANLG_TRIM_1 0xF1250008 ANLG_TRIM_2 0xF125000C IP_DISABLE_1 0xF125001C DNA_0 0xF1250020 DNA_1 0xF1250024 DNA_2 0xF1250028 DNA_3 0xF125002C TRIM_BRAM 0xF1250098 TRIM_URAM 0xF125009C PMC_BISR_0 0xF12500D8 PMC_BISR_1 0xF12500DC ANLG_TRIM_5 0xF12500E0 ALNG_TRIM_6 0xF12500F4 ANLG_TRIM_7 0xF12500F8 ME_ID_CODE 0xF12500FC XPORT_DFT 0xF125018C TRIM_AMS_4 0xF1250190 TRIM_AMS_5 0xF1250194 TRIM_AMS_6 0xF1250198 TRIM_AMS_7 0xF125019C TRIM_AMS_8 0xF12501A0 TRIM_AMS_9 0xF12501A4 TRIM_AMS_10 0xF12501A8 TRIM_AMS_11 0xF12501AC TRIM_AMS_12 0xF12501B0 TRIM_CFRM_VGG_0 0xF12501B4 TRIM_CFRM_VGG_1 0xF12501B8 TRIM_CFRM_VGG_2 0xF12501BC TRIM_CRAM 0xF12501C0 NIDB_0 0xF12501C4 NIDB_1 0xF12501C8 NIDB_2 0xF12501CC TRIM_AMS_0 0xF12501F4 TRIM_AMS_1 0xF12501F8 TRIM_AMS_2 0xF12501FC TRIM_AMS_3 0xF1250200 XST_SUCCESS - Up on SuccessXST_FAILURE - Error as calculated CRC and CRC value written in eFuse doesn't match.
int XNvm_EfuseWriteAesKey(u32 EnvDisFlag, XNvm_AesKeyType KeyType, XNvm_AesKey *EfuseKey)
This function is used to take care of prerequisites to program below eFuses AES key User key 0 User key 1.
EnvDisFlag - Environmental monitoring flag set by the user. when set to true it will not check for voltage and temperature limits. KeyType - Type of key to be programmed(AesKey/UserKey0/UserKey1) EfuseKey - Pointer to the XNvm_AesKey structure, which holds Aes key to be programmed to eFuse. XST_SUCCESS On Successful Write.XNVM_EFUSE_ERR_BEFORE_PROGRAMMING Error before programming eFuse.XNVM_EFUSE_ERR_WRITE_AES_KEY Error while writing AES key.XNVM_EFUSE_ERR_WRITE_USER_KEY0 Error while writing User key0.XNVM_EFUSE_ERR_WRITE_USER_KEY1 Error while writing User key1.
References XNVM_EFUSE_AES_KEY, XNVM_EFUSE_ERR_BEFORE_PROGRAMMING, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_MARGIN_RD, XNVM_EFUSE_MODE_PGM, XNVM_EFUSE_USER_KEY_0, XNVM_EFUSE_USER_KEY_1, XNvm_EfuseSetupController, XNvm_EfuseTempAndVoltChecks, XNvm_EfuseValidateAesKeyWriteReq.
int XNvm_EfuseWritePpkHash(u32 EnvDisFlag, XNvm_PpkType PpkType, XNvm_PpkHash *EfuseHash)
This function is used to to take care of prerequisitis to program below eFuses PPK0_HASH PPK1_HASH PPK2_HASH.
EnvDisFlag - Environmental monitoring flag set by the user. when set to true it will not check for voltage and temperature limits. PpkType - Type of ppk hash to be programmed(PPK0/PPK1/PPK2) EfuseHash - Pointer to the XNvm_PpkHash structure which holds PPK hash to be programmed to eFuse. XST_SUCCESS On Successful Write.XNVM_EFUSE_ERR_WRITE_PPK0_HASH Error while writing PPK0 Hash.XNVM_EFUSE_ERR_WRITE_PPK1_HASH Error while writing PPK1 Hash.XNVM_EFUSE_ERR_WRITE_PPK2_HASH Error while writing PPK2 Hash.
References XNVM_EFUSE_ERR_BEFORE_PROGRAMMING, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_MARGIN_RD, XNVM_EFUSE_MODE_PGM, XNVM_EFUSE_PPK0, XNVM_EFUSE_PPK1, XNVM_EFUSE_PPK2, XNvm_EfuseSetupController, XNvm_EfuseTempAndVoltChecks, XNvm_EfuseValidatePpkHashWriteReq.
int XNvm_EfuseWriteIv(u32 EnvDisFlag, XNvm_IvType IvType, XNvm_Iv *EfuseIv)
This function is used to to take care of prerequisitis to program below IV eFuses XNVM_EFUSE_ERR_WRITE_META_HEADER_IV XNVM_EFUSE_ERR_WRITE_BLK_OBFUS_IV XNVM_EFUSE_ERR_WRITE_PLM_IV XNVM_EFUSE_ERR_WRITE_DATA_PARTITION_IV.
EnvDisFlag - Environmental monitoring flag set by the user. when set to true it will not check for voltage and temperature limits. IvType - Type of IV eFuses to be programmmed EfuseIv - Pointer to the XNvm_EfuseIvs structure which holds IV to be programmed to eFuse. XST_SUCCESS On Successful Write.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_WRITE_META_HEADER_IV Error while writing Meta Iv.XNVM_EFUSE_ERR_WRITE_BLK_OBFUS_IV Error while writing BlkObfus IV.XNVM_EFUSE_ERR_WRITE_PLM_IV Error while writing PLM IV.XNVM_EFUSE_ERR_WRITE_DATA_PARTITION_IV Error while writing Data Partition IV.
References XNVM_EFUSE_BLACK_IV, XNVM_EFUSE_DATA_PARTITION_IV_RANGE, XNVM_EFUSE_ERR_BEFORE_PROGRAMMING, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_MARGIN_RD, XNVM_EFUSE_META_HEADER_IV_RANGE, XNVM_EFUSE_MODE_PGM, XNVM_EFUSE_PLM_IV_RANGE, XNvm_EfuseSetupController, XNvm_EfuseTempAndVoltChecks, XNvm_EfuseValidateIvWriteReq.
int XNvm_EfuseWriteGlitchConfigBits(u32 EnvDisFlag, u32 GlitchConfig)
This function is used to program Glitch Configuration given by the user.
EnvDisFlag - Environmental monitoring flag set by the user. when set to true it will not check for voltage and temperature limits. GlitchConfig - Pointer to the Glitch configuration XST_SUCCESS On Successful Write.XNVM_EFUSE_ERR_WRITE_GLITCH_CFG Error in programming of glitch configuration.XNVM_EFUSE_ERR_WRITE_GLITCH_WRLK Error in programming glitch write lock.
References XNvm_EfusePrgmInfo::ColEnd, XNvm_EfusePrgmInfo::ColStart, XNvm_EfusePrgmInfo::EfuseType, XNvm_EfusePrgmInfo::NumOfRows, XNvm_EfusePrgmInfo::StartRow, XNVM_EFUSE_ANLG_TRIM_3_START_ROW, XNVM_EFUSE_CACHE_ANLG_TRIM_3_OFFSET, XNVM_EFUSE_ERR_BEFORE_PROGRAMMING, XNVM_EFUSE_ERR_WRITE_GLITCH_CFG, XNVM_EFUSE_ERR_WRITE_GLITCH_WRLK, XNVM_EFUSE_GLITCH_CONFIG_DATA_MASK, XNVM_EFUSE_GLITCH_DET_CONFIG_END_COL_NUM, XNVM_EFUSE_GLITCH_DET_CONFIG_NUM_OF_ROWS, XNVM_EFUSE_GLITCH_DET_CONFIG_START_COL_NUM, XNVM_EFUSE_GLITCH_DET_WR_LK_COL_NUM, XNVM_EFUSE_GLITCH_DET_WR_LK_ROW, XNVM_EFUSE_MARGIN_RD, XNVM_EFUSE_MODE_PGM, XNVM_EFUSE_PAGE_0, XNVM_EFUSE_PROGRAM_VERIFY, XNvm_EfuseSetupController, XNvm_EfuseTempAndVoltChecks.
int XNvm_EfuseWriteDecOnly(u32 EnvDisFlag)
This function is used to program below DEC_ONLY fuses.
EnvDisFlag - Environmental monitoring flag set by the user, when set to true it will not check for voltage and temperature limits. XST_SUCCESS If DEC_ONLY eFuse is programmed successfully.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_WRITE_DEC_EFUSE_ONLY Error in DEC_ONLY programming.XNVM_EFUSE_ERR_CACHE_PARITY Error in Cache reload after programming.
References XNvm_EfusePrgmInfo::ColEnd, XNvm_EfusePrgmInfo::ColStart, XNvm_EfusePrgmInfo::EfuseType, XNvm_EfusePrgmInfo::NumOfRows, XNvm_EfusePrgmInfo::StartRow, XNVM_EFUSE_CACHE_DEC_EFUSE_ONLY_MASK, XNVM_EFUSE_DEC_ONLY_END_COL_NUM, XNVM_EFUSE_DEC_ONLY_NUM_OF_ROWS, XNVM_EFUSE_DEC_ONLY_START_COL_NUM, XNVM_EFUSE_ERR_BEFORE_PROGRAMMING, XNVM_EFUSE_ERR_WRITE_DEC_EFUSE_ONLY, XNVM_EFUSE_MARGIN_RD, XNVM_EFUSE_MODE_PGM, XNVM_EFUSE_PAGE_0, XNVM_EFUSE_SECURITY_MISC_0_START_ROW, XNvm_EfuseSetupController, XNvm_EfuseTempAndVoltChecks, XNvm_EfuseValidateDecOnlyRequest.
int XNvm_EfuseWriteRevocationID(u32 EnvDisFlag, u32 RevokeIdNum)
This function writes Revocation eFuses.
EnvDisFlag - Environmental monitoring flag set by the user, when set to true it will not check for voltage and temperature limits. RevokeIdNum - RevokeId number to program Revocation Id eFuses. XST_SUCCESS On successful write to eFuse.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_LOCK Error while Locking the controller. Example: If the revoke id to program is 64, it will program the 0th bit of the REVOCATION_ID_2 eFuse row.
References XNVM_EFUSE_BITS_IN_A_BYTE, XNVM_EFUSE_ERR_BEFORE_PROGRAMMING, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_ERR_WRITE_REVOCATION_IDS, XNVM_EFUSE_MARGIN_RD, XNVM_EFUSE_MODE_PGM, XNVM_EFUSE_PAGE_0, XNVM_EFUSE_PROGRAM_VERIFY, XNVM_EFUSE_REVOKE_ID_0_TO_127_START_COL_NUM, XNVM_EFUSE_REVOKE_ID_127, XNVM_EFUSE_REVOKE_ID_128_TO_255_START_COL_NUM, XNVM_EFUSE_REVOKE_ID_START_ROW, XNvm_EfuseSetupController, XNvm_EfuseTempAndVoltChecks, XNVM_MAX_REVOKE_ID_FUSES.
int XNvm_EfuseWriteOffChipRevokeID(u32 EnvDisFlag, u32 OffchipIdNum)
This function programs OffChip Revoke eFuses.
EnvDisFlag - Environmental monitoring flag set by the user, when set to true it will not check for voltage and temperature limits. OffchipIdNum - OffchipIdNum number to program OffchipId eFuses. XST_SUCCESS On successful write of OffChipId.XNVM_EFUSE_ERR_WRITE_OFFCHIP_REVOKE_IDS Error in writing OffChipId eFuses.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_CACHE_PARITY Error in Cache reload.
References XNVM_EFUSE_ERR_BEFORE_PROGRAMMING, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_ERR_WRITE_OFFCHIP_REVOKE_IDS, XNVM_EFUSE_MARGIN_RD, XNVM_EFUSE_MAX_BITS_IN_ROW, XNVM_EFUSE_MODE_PGM, XNVM_EFUSE_OFFCHIP_REVOKE_ID_START_ROW, XNVM_EFUSE_PAGE_0, XNVM_EFUSE_PROGRAM_VERIFY, XNvm_EfuseSetupController, XNvm_EfuseTempAndVoltChecks, XNVM_MAX_REVOKE_ID_FUSES.
int XNvm_EfuseWriteMiscCtrlBits(u32 EnvDisFlag, u32 MiscCtrlBits)
This function programs MiscCtrl eFuses.
EnvDisFlag - Environmental monitoring flag set by the user, when set to true it will not check for voltage and temperature limits. MiscCtrlBits - MiscCtrl data to be written to eFuses. XST_SUCCESS On successful write.XNVM_EFUSE_ERR_WRITE_MISC_CTRL_BITS Error while writing MiscCtrlBitsXNVM_EFUSE_ERR_BEFORE_PROGRAMMING Error before programming.
References XNvm_EfusePrgmInfo::ColEnd, XNvm_EfusePrgmInfo::ColStart, XNvm_EfusePrgmInfo::EfuseType, XNvm_EfusePrgmInfo::NumOfRows, XNvm_EfusePrgmInfo::StartRow, XNVM_EFUSE_CACHE_MISC_CTRL_OFFSET, XNVM_EFUSE_ERR_BEFORE_PROGRAMMING, XNVM_EFUSE_ERR_WRITE_MISC_CTRL_BITS, XNVM_EFUSE_MARGIN_RD, XNVM_EFUSE_MISC_CTRL_END_COL_NUM, XNVM_EFUSE_MISC_CTRL_NUM_OF_ROWS, XNVM_EFUSE_MISC_CTRL_START_COL_NUM, XNVM_EFUSE_MISC_CTRL_START_ROW, XNVM_EFUSE_MODE_PGM, XNVM_EFUSE_PAGE_0, XNvm_EfuseSetupController, XNvm_EfuseTempAndVoltChecks.
int XNvm_EfuseWriteSecCtrlBits(u32 EnvDisFlag, u32 SecCtrlBits)
This function programs SecCtrl eFuses.
EnvDisFlag - Environmental monitoring flag set by the user, when set to true it will not check for voltage and temperature limits. SecCtrlBits - SecCtrl data to be written to eFuses. XST_SUCCESS On successful write.XNVM_EFUSE_ERR_WRITE_SEC_CTRL_BITS Error while writing SecCtrlBitsXNVM_EFUSE_ERR_BEFORE_PROGRAMMING Error before programming.
References XNvm_EfusePrgmInfo::ColEnd, XNvm_EfusePrgmInfo::ColStart, XNvm_EfusePrgmInfo::EfuseType, XNvm_EfusePrgmInfo::NumOfRows, XNvm_EfusePrgmInfo::StartRow, XNVM_EFUSE_CACHE_SECURITY_CONTROL_OFFSET, XNVM_EFUSE_ERR_BEFORE_PROGRAMMING, XNVM_EFUSE_ERR_WRITE_SEC_CTRL_BITS, XNVM_EFUSE_MARGIN_RD, XNVM_EFUSE_MODE_PGM, XNVM_EFUSE_PAGE_0, XNVM_EFUSE_SEC_CTRL_END_COL_NUM, XNVM_EFUSE_SEC_CTRL_NUM_OF_ROWS, XNVM_EFUSE_SEC_CTRL_START_COL_NUM, XNVM_EFUSE_SEC_CTRL_START_ROW, XNvm_EfuseSetupController, XNvm_EfuseTempAndVoltChecks.
int XNvm_EfuseWriteMisc1Bits(u32 EnvDisFlag, u32 Misc1Bits)
This function programs Misc1Ctrl eFuses.
EnvDisFlag - Environmental monitoring flag set by the user, when set to true it will not check for voltage and temperature limits. Misc1Bits - Misc1Bits data to be written to eFuses. XST_SUCCESS On successful write.XNVM_EFUSE_ERR_WRITE_MISC1_CTRL_BITS Error while writing Misc1CtrlBitsXNVM_EFUSE_ERR_BEFORE_PROGRAMMING Error before programming.
References XNvm_EfusePrgmInfo::ColEnd, XNvm_EfusePrgmInfo::ColStart, XNvm_EfusePrgmInfo::EfuseType, XNvm_EfusePrgmInfo::NumOfRows, XNvm_EfusePrgmInfo::StartRow, XNVM_EFUSE_CACHE_SECURITY_MISC_1_OFFSET, XNVM_EFUSE_ERR_BEFORE_PROGRAMMING, XNVM_EFUSE_ERR_WRITE_MISC1_CTRL_BITS, XNVM_EFUSE_MARGIN_RD, XNVM_EFUSE_MODE_PGM, XNVM_EFUSE_PAGE_0, XNVM_EFUSE_SECURITY_MISC1_END_COL_NUM, XNVM_EFUSE_SECURITY_MISC1_NUM_OF_ROWS, XNVM_EFUSE_SECURITY_MISC1_START_COL_NUM, XNVM_EFUSE_SECURITY_MISC1_START_ROW, XNvm_EfuseSetupController, XNvm_EfuseTempAndVoltChecks.
int XNvm_EfuseWriteBootEnvCtrlBits(u32 EnvDisFlag, u32 BootEnvCtrlBits)
This function programs BootEnvCtrl eFuses.
EnvDisFlag - Environmental monitoring flag set by the user, when set to true it will not check for voltage and temperature limits. BootEnvCtrlBits - BootEnvCtrl data to be written to eFuses. XST_SUCCESS On successful write.XNVM_EFUSE_ERR_WRITE_BOOT_ENV_CTRL Error while writing BootEnvCtrl BitsXNVM_EFUSE_ERR_BEFORE_PROGRAMMING Error before programming.
References XNvm_EfusePrgmInfo::ColEnd, XNvm_EfusePrgmInfo::ColStart, XNvm_EfusePrgmInfo::EfuseType, XNvm_EfusePrgmInfo::NumOfRows, XNvm_EfusePrgmInfo::StartRow, XNVM_EFUSE_BOOT_ENV_CTRL_END_COL_NUM, XNVM_EFUSE_BOOT_ENV_CTRL_NUM_OF_ROWS, XNVM_EFUSE_BOOT_ENV_CTRL_START_COL_NUM, XNVM_EFUSE_BOOT_ENV_CTRL_START_ROW, XNVM_EFUSE_CACHE_BOOT_ENV_CTRL_OFFSET, XNVM_EFUSE_ERR_BEFORE_PROGRAMMING, XNVM_EFUSE_ERR_WRITE_BOOT_ENV_CTRL, XNVM_EFUSE_MARGIN_RD, XNVM_EFUSE_MODE_PGM, XNVM_EFUSE_PAGE_0, XNvm_EfuseSetupController, XNvm_EfuseTempAndVoltChecks.
int XNvm_EfuseWriteFipsInfo(u32 EnvDisFlag, u32 FipsMode, u32 FipsVersion)
This function is used to to take care of prerequisitis to program FIPS mode and FIPS version eFuses.
EnvDisFlag - Environmental monitoring flag set by the user, when set to true it will not check for voltage and temperature limits. FipsMode - Fips mode to be written to eFuses. FipsVersion - Fips version to be written to eFuses. XST_SUCCESS On successful write.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid input parameter. XNVM_EFUSE_ERR_BEFORE_PROGRAMMING Error before programming.
References XNVM_EFUSE_ERR_BEFORE_PROGRAMMING, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_MARGIN_RD, XNVM_EFUSE_MAX_FIPS_MODE, XNVM_EFUSE_MAX_FIPS_VERSION, XNVM_EFUSE_MODE_PGM, XNvm_EfuseSetupController, XNvm_EfuseTempAndVoltChecks, XNvm_EfuseValidateFipsInfo.
int XNvm_EfuseWriteUds(u32 EnvDisFlag, XNvm_Uds *EfuseUds)
This function programs UDS eFuses.
EnvDisFlag - Environmental monitoring flag set by the user, when set to true it will not check for voltage and temperature limits. EfuseUds - Pointer to the XNvm_Uds structure. XST_SUCCESS On successful write.XNVM_EFUSE_ERR_WRITE_UDS On failure in UDS write. XNVM_EFUSE_ERR_INVALID_PARAM On Invalid input parameter. XNVM_EFUSE_ERR_BEFORE_PROGRAMMING Error before programming.
References XNvm_EfusePrgmInfo::ColEnd, XNvm_EfusePrgmInfo::ColStart, XNvm_EfusePrgmInfo::EfuseType, XNvm_EfusePrgmInfo::NumOfRows, XNvm_EfusePrgmInfo::SkipVerify, XNvm_EfusePrgmInfo::StartRow, XNVM_EFUSE_CACHE_BASEADDR, XNVM_EFUSE_CACHE_SECURITY_CONTROL_OFFSET, XNVM_EFUSE_CACHE_SECURITY_CONTROL_UDS_WR_LK_MASK, XNVM_EFUSE_CTRL_STATUS_UDS_DICE_CRC_DONE_MASK, XNVM_EFUSE_CTRL_STATUS_UDS_DICE_CRC_PASS_MASK, XNVM_EFUSE_CTRL_UDS_DICE_CRC_OFFSET, XNVM_EFUSE_DICE_UDS_0_TO_63_END_COL_NUM, XNVM_EFUSE_DICE_UDS_0_TO_63_NUM_OF_ROWS, XNVM_EFUSE_DICE_UDS_0_TO_63_START_COL_NUM, XNVM_EFUSE_DICE_UDS_0_TO_63_START_ROW, XNVM_EFUSE_DICE_UDS_192_TO_255_END_COL_NUM, XNVM_EFUSE_DICE_UDS_192_TO_255_NUM_OF_ROWS, XNVM_EFUSE_DICE_UDS_192_TO_255_START_COL_NUM, XNVM_EFUSE_DICE_UDS_192_TO_255_START_ROW, XNVM_EFUSE_DICE_UDS_256_TO_383_END_COL_NUM, XNVM_EFUSE_DICE_UDS_256_TO_383_NUM_OF_ROWS, XNVM_EFUSE_DICE_UDS_256_TO_383_START_COL_NUM, XNVM_EFUSE_DICE_UDS_256_TO_383_START_ROW, XNVM_EFUSE_DICE_UDS_64_TO_191_END_COL_NUM, XNVM_EFUSE_DICE_UDS_64_TO_191_NUM_OF_ROWS, XNVM_EFUSE_DICE_UDS_64_TO_191_START_COL_NUM, XNVM_EFUSE_DICE_UDS_64_TO_191_START_ROW, XNVM_EFUSE_ERR_BEFORE_PROGRAMMING, XNVM_EFUSE_ERR_FUSE_PROTECTED, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_ERR_WRITE_UDS, XNVM_EFUSE_MARGIN_RD, XNVM_EFUSE_MODE_PGM, XNVM_EFUSE_PAGE_0, XNVM_EFUSE_SKIP_VERIFY, XNvm_EfuseCheckAesKeyCrc, XNvm_EfuseReadReg, XNvm_EfuseSetupController, XNvm_EfuseTempAndVoltChecks.
int XNvm_EfuseWriteDmeUserKey(u32 EnvDisFlag, XNvm_DmeKeyType KeyType, XNvm_DmeKey *EfuseKey)
This function programs DME userkey eFuses.
EnvDisFlag - Environmental monitoring flag set by the user, when set to true it will not check for voltage and temperature limits. KeyType - DME Key type DME_USER_KEY_0/1/2/3 EfuseKey - Pointer to DME userkey structure. XST_SUCCESS On successful write.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid input parameter.XNVM_EFUSE_ERR_BEFORE_PROGRAMMING Error before programming.
References XNVM_EFUSE_ERR_BEFORE_PROGRAMMING, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_MARGIN_RD, XNVM_EFUSE_MODE_PGM, XNvm_EfuseSetupController, XNvm_EfuseTempAndVoltChecks, XNvm_IsDmeModeEn.
int XNvm_EfuseWriteDmeRevoke(u32 EnvDisFlag, XNvm_DmeRevoke RevokeNum)
This function programs DME Revoke eFuses.
EnvDisFlag - Environmental monitoring flag set by the user, when set to true it will not check for voltage and temperature limits. RevokeNum - DmeRevoke eFuse number. XST_SUCCESS On successful write.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid input parameter.XNVM_EFUSE_ERR_BEFORE_PROGRAMMING Error before programming.XNVM_EFUSE_ERR_WRITE_DME_REVOKE_0 Error while writing DmeRevoke 0.XNVM_EFUSE_ERR_WRITE_DME_REVOKE_1 Error while writing DmeRevoke 1.XNVM_EFUSE_ERR_WRITE_DME_REVOKE_2 Error while writing DmeRevoke 2.XNVM_EFUSE_ERR_WRITE_DME_REVOKE_3 Error while writing DmeRevoke 3.
References XNVM_EFUSE_DME_REVOKE_0_0_COL_NUM, XNVM_EFUSE_DME_REVOKE_0_1_COL_NUM, XNVM_EFUSE_DME_REVOKE_0_AND_1_ROW, XNVM_EFUSE_DME_REVOKE_1_0_COL_NUM, XNVM_EFUSE_DME_REVOKE_1_1_COL_NUM, XNVM_EFUSE_DME_REVOKE_2_0_COL_NUM, XNVM_EFUSE_DME_REVOKE_2_1_COL_NUM, XNVM_EFUSE_DME_REVOKE_2_AND_3_ROW, XNVM_EFUSE_DME_REVOKE_3_0_COL_NUM, XNVM_EFUSE_DME_REVOKE_3_1_COL_NUM, XNVM_EFUSE_ERR_BEFORE_PROGRAMMING, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_ERR_WRITE_DME_REVOKE_0, XNVM_EFUSE_ERROR_BYTE_SHIFT, XNVM_EFUSE_MARGIN_RD, XNVM_EFUSE_MODE_PGM, XNVM_EFUSE_PAGE_0, XNVM_EFUSE_PROGRAM_VERIFY, XNvm_EfuseSetupController, XNvm_EfuseTempAndVoltChecks.
int XNvm_EfuseWriteDisableInplacePlmUpdate(u32 EnvDisFlag)
This function programs PLM_UPDATE eFuse.
EnvDisFlag - Environmental monitoring flag set by the user, when set to true it will not check for voltage and temperature limits. XST_SUCCESS On successful write.XNVM_EFUSE_ERR_WRITE_PLM_UPDATE Error while writing PlmUpdate eFuse.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid input parameter.XNVM_EFUSE_ERR_BEFORE_PROGRAMMING Error before programming.
References XNVM_EFUSE_DISABLE_PLM_UPDATE_COL_NUM, XNVM_EFUSE_DISABLE_PLM_UPDATE_ROW, XNVM_EFUSE_ERR_BEFORE_PROGRAMMING, XNVM_EFUSE_ERR_WRITE_PLM_UPDATE, XNVM_EFUSE_MARGIN_RD, XNVM_EFUSE_MODE_PGM, XNVM_EFUSE_PAGE_0, XNVM_EFUSE_PROGRAM_VERIFY, XNvm_EfuseSetupController, XNvm_EfuseTempAndVoltChecks.
int XNvm_EfuseWriteBootModeDisable(u32 EnvDisFlag, u32 BootModeMask)
This function programs BootModeDisable eFuses.
EnvDisFlag - Environmental monitoring flag set by the user, when set to true it will not check for voltage and temperature limits. BootModeMask - BootModeMask to be programmed to BootModeDisable eFuses. XST_SUCCESS On successful write.XNVM_EFUSE_ERR_WRITE_BOOT_MODE_DISABLE Error while writing BootModeDisable eFuses.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid input parameter.XNVM_EFUSE_ERR_BEFORE_PROGRAMMING Error before programming.
References XNvm_EfusePrgmInfo::ColEnd, XNvm_EfusePrgmInfo::ColStart, XNvm_EfusePrgmInfo::EfuseType, XNvm_EfusePrgmInfo::NumOfRows, XNvm_EfusePrgmInfo::StartRow, XNVM_EFUSE_BOOT_MODE_END_COL_NUM, XNVM_EFUSE_BOOT_MODE_NUM_OF_ROWS, XNVM_EFUSE_BOOT_MODE_START_COL_NUM, XNVM_EFUSE_BOOT_MODE_START_ROW, XNVM_EFUSE_ERR_BEFORE_PROGRAMMING, XNVM_EFUSE_ERR_WRITE_BOOT_MODE_DISABLE, XNVM_EFUSE_MARGIN_RD, XNVM_EFUSE_MODE_PGM, XNVM_EFUSE_PAGE_0, XNvm_EfuseSetupController, XNvm_EfuseTempAndVoltChecks.
int XNvm_EfuseWriteDmeMode(u32 EnvDisFlag, u32 DmeMode)
This function programs DmeMode eFuses.
EnvDisFlag - Environmental monitoring flag set by the user, when set to true it will not check for voltage and temperature limits. DmeMode - DmeMode eFuses to be written. XST_SUCCESS On successful write.XNVM_EFUSE_ERR_WRITE_DME_MODE Error while writing DmeMode eFuse.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid input parameter.XNVM_EFUSE_ERR_BEFORE_PROGRAMMING Error before programming.
References XNvm_EfusePrgmInfo::ColEnd, XNvm_EfusePrgmInfo::ColStart, XNvm_EfusePrgmInfo::EfuseType, XNvm_EfusePrgmInfo::NumOfRows, XNvm_EfusePrgmInfo::StartRow, XNVM_EFUSE_DME_MODE_END_COL_NUM, XNVM_EFUSE_DME_MODE_NUM_OF_ROWS, XNVM_EFUSE_DME_MODE_START_COL_NUM, XNVM_EFUSE_DME_MODE_START_ROW, XNVM_EFUSE_ERR_BEFORE_PROGRAMMING, XNVM_EFUSE_ERR_WRITE_DME_MODE, XNVM_EFUSE_ERROR_DME_NOT_SUPPORTED, XNVM_EFUSE_MARGIN_RD, XNVM_EFUSE_MODE_PGM, XNVM_EFUSE_PAGE_0, XNvm_EfuseSetupController, XNvm_EfuseTempAndVoltChecks.
int XNvm_EfuseWriteCrc(u32 EnvDisFlag, u32 Crc)
This function programs EFUSE_CRC_SALT eFuses.
EnvDisFlag - Environmental monitoring flag set by the user, when set to true it will not check for voltage and temperature limits. Crc - Crc value to be written. XST_SUCCESS On successful write. XNVM_EFUSE_ERR_WRITE_CRC_SALT Error while writing Crc salt eFuses.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid input parameter.XNVM_EFUSE_ERR_BEFORE_PROGRAMMING Error before programming.
References XNvm_EfusePrgmInfo::ColEnd, XNvm_EfusePrgmInfo::ColStart, XNvm_EfusePrgmInfo::EfuseType, XNvm_EfusePrgmInfo::NumOfRows, XNvm_EfusePrgmInfo::StartRow, XNVM_EFUSE_CACHE_BASEADDR, XNVM_EFUSE_CACHE_CRC_OFFSET, XNVM_EFUSE_CRC_END_COL_NUM, XNVM_EFUSE_CRC_NUM_OF_ROWS, XNVM_EFUSE_CRC_ROW, XNVM_EFUSE_CRC_SALT, XNVM_EFUSE_CRC_SALT_END_COL_NUM, XNVM_EFUSE_CRC_SALT_NUM_OF_ROWS, XNVM_EFUSE_CRC_SALT_ROW, XNVM_EFUSE_CRC_SALT_START_COL_NUM, XNVM_EFUSE_CRC_START_COL_NUM, XNVM_EFUSE_ERR_BEFORE_PROGRAMMING, XNVM_EFUSE_ERR_WRITE_CRC, XNVM_EFUSE_ERR_WRITE_CRC_SALT, XNVM_EFUSE_MARGIN_RD, XNVM_EFUSE_MODE_PGM, XNVM_EFUSE_PAGE_0, XNvm_EfuseReadReg, XNvm_EfuseSetupController, XNvm_EfuseTempAndVoltChecks.
int XNvm_EfuseWritePuf(const XNvm_EfusePufHdAddr *PufHelperData)
This function programs PUF ctrl and PUF helper data, Chash and Aux.
PufHelperData - Pointer to XNvm_EfusePufHdAddr structure XST_SUCCESS On successful write.XNVM_EFUSE_ERR_WRITE_PUF_HELPER_DATA Error while writing Puf helper data.XNVM_EFUSE_ERR_WRITE_PUF_SYN_DATA Error while writing Puf Syndata.XNVM_EFUSE_ERR_WRITE_PUF_CHASH Error while writing Puf Chash.XNVM_EFUSE_ERR_WRITE_PUF_AUX Error while writing Puf Aux.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid input parameter.XNVM_EFUSE_ERR_BEFORE_PROGRAMMING Error before programming. To generate PufSyndromeData please use XPuf_Registration API.
References XNVM_EFUSE_CACHE_BASEADDR, XNVM_EFUSE_CACHE_PUF_ECC_PUF_CTRL_OFFSET, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PUF_DIS_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PUF_SYN_LK_MASK, XNVM_EFUSE_ERR_BEFORE_PROGRAMMING, XNVM_EFUSE_ERR_FUSE_PROTECTED, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_ERR_WRITE_PUF_AUX, XNVM_EFUSE_ERR_WRITE_PUF_CHASH, XNVM_EFUSE_ERR_WRITE_PUF_HELPER_DATA, XNVM_EFUSE_ERR_WRITE_PUF_SYN_DATA, XNVM_EFUSE_ERR_WRITE_RO_SWAP, XNVM_EFUSE_MARGIN_RD, XNVM_EFUSE_MODE_PGM, XNVM_EFUSE_SEC_DEF_VAL_ALL_BIT_SET, XNvm_EfuseIsPufHelperDataEmpty, XNvm_EfuseReadReg, XNvm_EfuseSetupController, XNvm_EfuseTempAndVoltChecks.
int XNvm_EfuseWritePufSecCtrl(u32 EnvDisFlag, u32 PufCtrlBits)
This function programs Puf control bits specified by user.
EnvDisFlag - Environmental monitoring flag set by the user, when set to true it will not check for voltage and temperature limits. PufCtrlBits - PufCtrlBits input to be programmed XST_SUCCESS On success.XNVM_EFUSE_ERR_INVALID_PARAM Invalid parameter.XNVM_EFUSE_ERR_WRITE_PUF_REGEN_DIS Error while writing PUF_REGEN_DIS.XNVM_EFUSE_ERR_WRITE_PUF_HD_INVLD Error while writing PUF_HD_INVLD.XNVM_EFUSE_ERR_WRITE_PUF_SYN_LK Error while writing PUF_SYN_LK.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid input parameter.XNVM_EFUSE_ERR_BEFORE_PROGRAMMING Error before programming.
References XNVM_EFUSE_ERR_BEFORE_PROGRAMMING, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_ERR_WRITE_PUF_SEC_CTRL_BITS, XNVM_EFUSE_MARGIN_RD, XNVM_EFUSE_MODE_PGM, XNVM_EFUSE_PAGE_0, XNVM_EFUSE_PROGRAM_VERIFY, XNVM_EFUSE_PUF_AUX_ROW, XNVM_EFUSE_PUF_CTRL_PUF_HD_INVLD_MASK, XNVM_EFUSE_PUF_CTRL_PUF_REGEN_DIS_MASK, XNVM_EFUSE_PUF_CTRL_PUF_REGIS_DIS_MASK, XNVM_EFUSE_PUF_HD_INVLD_COL_NUM, XNVM_EFUSE_PUF_REGEN_DIS_COL_NUM, XNVM_EFUSE_PUF_REGIS_DIS_COL_NUM, XNVM_EFUSE_PUF_SEC_CTRL_INVLD_MASK, XNvm_EfuseSetupController, XNvm_EfuseTempAndVoltChecks, XNvm_EfuseWritePufSecCtrl.
Referenced by XNvm_EfuseWritePufSecCtrl.
int XNvm_EfuseCacheLoadNPrgmProtectionBits(void)
This function reloads the cache of eFUSE so that can be directly read from cache and programs required protections eFuses.
XST_SUCCESS On Successful Cache Reload.XNVM_EFUSE_ERR_CACHE_LOAD Error while loading the cache.XNVM_EFUSE_ERR_BEFORE_PROGRAMMING Error before programming. Not recommended to call this API frequently,if this API is called all the cache memory is reloaded by reading eFUSE array, reading eFUSE bit multiple times may diminish the life time.
References XNVM_EFUSE_ERR_BEFORE_PROGRAMMING, XNVM_EFUSE_MARGIN_RD, XNVM_EFUSE_MODE_PGM, XNvm_EfuseSetupController.
int XNvm_EfuseWriteRomRsvdBits(u32 EnvDisFlag, u32 RomRsvdBits)
This function programs ROM Rsvd Bits eFuses.
EnvDisFlag - Environmental monitoring flag set by the user, when set to true it will not check for voltage and temperature limits. RomRsvdBits - RomRsvdBits to be programmed to RomRsvd eFUSE bits XST_SUCCESS On successful write.XNVM_EFUSE_ERR_WRITE_ROM_RSVD Error while writing ROM Rsvd eFuse bits.XNVM_EFUSE_ERR_BEFORE_PROGRAMMING Error before programming.
References XNvm_EfusePrgmInfo::ColEnd, XNvm_EfusePrgmInfo::ColStart, XNvm_EfusePrgmInfo::EfuseType, XNvm_EfusePrgmInfo::NumOfRows, XNvm_EfusePrgmInfo::StartRow, XNVM_EFUSE_CACHE_ROM_RSVD_OFFSET, XNVM_EFUSE_ERR_BEFORE_PROGRAMMING, XNVM_EFUSE_ERR_WRITE_ROM_RSVD_BITS, XNVM_EFUSE_MARGIN_RD, XNVM_EFUSE_MODE_PGM, XNVM_EFUSE_PAGE_0, XNVM_EFUSE_ROM_RSVD_END_COL, XNVM_EFUSE_ROM_RSVD_NUM_OF_ROWS, XNVM_EFUSE_ROM_RSVD_START_COL, XNVM_EFUSE_ROM_RSVD_START_ROW, XNvm_EfuseSetupController, XNvm_EfuseTempAndVoltChecks.
XNVM_EFUSE_SYSMON_LOCK_CODE
System monitor lock code for eFUSE operations.
Referenced by XNvm_EfuseTempAndVoltChecks.
XNVM_EFUSE_PROTECTION_BIT_CLEAR
To check the corresponding protection eFuse is set or not.
Referenced by XNvm_EfuseReadProtectionBits.
XNVM_EFUSE_ERROR_BYTE_SHIFT
Byte shift used in error code.
Referenced by XNvm_EfuseValidateAesKeyWriteReq, XNvm_EfuseValidateIvWriteReq, XNvm_EfuseValidatePpkHashWriteReq, XNvm_EfuseWriteDmeRevoke.
XNVM_EFUSE_ERROR_NIBBLE_SHIFT
Nibble shift used in error code.
Referenced by XNvm_EfuseValidateAesKeyWriteReq, XNvm_EfuseValidatePpkHashWriteReq.
XNVM_EFUSE_MAX_FIPS_MODE
Max value of FIPS mode.
Referenced by XNvm_EfuseWriteFipsInfo.
XNVM_EFUSE_BITS_IN_A_BYTE
Number of bits in a byte.
Referenced by XNvm_EfuseWriteRevocationID.
XNVM_EFUSE_SEC_DEF_VAL_ALL_BIT_SET
Secure Default Value for a register.
Referenced by XNvm_EfuseWritePuf.
XNVM_EFUSE_BYTE_MASK
Mask for 8 bits.
REVERSE_POLYNOMIAL
Value used in CRC calculation to reverse a polynomial.
XNVM_EFUSE_SKIP_VERIFY
Skip verification of eFuses after programming.
Referenced by XNvm_EfuseWriteUds.
XNVM_EFUSE_PROGRAM_VERIFY
Verify eFuses after programming.
Referenced by XNvm_EfuseWriteDisableInplacePlmUpdate, XNvm_EfuseWriteDmeRevoke, XNvm_EfuseWriteGlitchConfigBits, XNvm_EfuseWriteOffChipRevokeID, XNvm_EfuseWritePufSecCtrl, XNvm_EfuseWriteRevocationID.
XNVM_EFUSE_CRC_SALT
CRC salt value.
Referenced by XNvm_EfuseWriteCrc.
XNVM_EFUSE_REVOKE_ID_127
Efuse revoke ID.
Referenced by XNvm_EfuseWriteRevocationID.
XNVM_EFUSE_PUF_SEC_CTRL_INVLD_MASK
Mask for PUF control bits in PUF_ECC_PUF_CTRL register in EFUSE_CACHE module.
Referenced by XNvm_EfuseWritePufSecCtrl.
XNVM_EFUSE_PUF_CTRL_PUF_REGEN_DIS_MASK
Mask for PUF_REGEN_DISABLE.
Referenced by XNvm_EfuseWritePufSecCtrl.
XNVM_EFUSE_PUF_CTRL_PUF_HD_INVLD_MASK
Mask for PUF_HD_INVLD.
Referenced by XNvm_EfuseWritePufSecCtrl.
XNVM_EFUSE_PUF_CTRL_PUF_REGIS_DIS_MASK
Mask for PUF_REGIS_DIS.
Referenced by XNvm_EfuseWritePufSecCtrl.
XNVM_EFUSE_DME_KEY_SIZE_IN_BYTES
DME key size in bytes.
XNVM_EFUSE_DME_0_USER_EFUSE_CACHE_OFFSET
DME 0 corresponding User eFuse offset.
XNVM_EFUSE_DME_1_USER_EFUSE_CACHE_OFFSET
DME 1 corresponding User eFuse offset.
XNVM_EFUSE_DME_2_USER_EFUSE_CACHE_OFFSET
DME 2 corresponding User eFuse offset.
XNVM_EFUSE_DME_3_USER_EFUSE_CACHE_OFFSET
DME 3 corresponding User eFuse offset.
XNVM_EFUSE_PPK_HASH_UPPER_WORD_START_OFFSET
PPK HASH upper 128 bit hash start word offset.
XNVM_EFUSE_LAST_ROW_IN_PAGE
Row number of last eFuse row in page.
XNVM_EFUSE_CACHE_ANLG_TRIM_0
ANLG_TRIM_0 eFuse cache offset.
XNVM_EFUSE_CACHE_ANLG_TRIM_1
ANLG_TRIM_1 eFuse cache offset.
XNVM_EFUSE_CACHE_ANLG_TRIM_2
ANLG_TRIM_2 eFuse cache offset.
XNVM_EFUSE_CACHE_IP_DISABLE_1
IP_DISABLE_1 eFuse cache offset.
XNVM_EFUSE_CACHE_DNA_0
DNA_0 eFuse cache offset.
XNVM_EFUSE_CACHE_DNA_1
DNA_1 eFuse cache offset.
XNVM_EFUSE_CACHE_DNA_2
DNA_2 eFuse cache offset.
XNVM_EFUSE_CACHE_DNA_3
DNA_3 eFuse cache offset.
XNVM_EFUSE_CACHE_TRIM_BRAM
TRIM_BRAM eFuse cache offset.
XNVM_EFUSE_CACHE_TRIM_URAM
TRIM_URAM eFuse cache offset.
XNVM_EFUSE_CACHE_PMC_BISR_0
PMC_BISR_0 eFuse cache offset.
XNVM_EFUSE_CACHE_PMC_BISR_1
PMC_BISR_1 eFuse cache offset.
XNVM_EFUSE_CACHE_ANLG_TRIM_5
ANLG_TRIM_5 eFuse cache offset.
XNVM_EFUSE_CACHE_ANLG_TRIM_6
ANLG_TRIM_6 eFuse cache offset.
XNVM_EFUSE_CACHE_ANLG_TRIM_7
ANLG_TRIM_7 eFuse cache offset.
XNVM_EFUSE_CACHE_ME_ID_CODE
ME_ID_CODE eFuse cache offset.
XNVM_EFUSE_CACHE_EXPORT_DFT
EXPORT_DFT eFuse cache offset.
XNVM_EFUSE_CACHE_TRIM_AMS_4
TRIM_AMS_4 eFuse cache offset.
XNVM_EFUSE_CACHE_TRIM_AMS_5
TRIM_AMS_5 eFuse cache offset.
XNVM_EFUSE_CACHE_TRIM_AMS_6
TRIM_AMS_6 eFuse cache offset.
XNVM_EFUSE_CACHE_TRIM_AMS_7
TRIM_AMS_7 eFuse cache offset.
XNVM_EFUSE_CACHE_TRIM_AMS_8
TRIM_AMS_8 eFuse cache offset.
XNVM_EFUSE_CACHE_TRIM_AMS_9
TRIM_AMS_9 eFuse cache offset.
XNVM_EFUSE_CACHE_TRIM_AMS_10
TRIM_AMS_10 eFuse cache offset.
XNVM_EFUSE_CACHE_TRIM_AMS_11
TRIM_AMS_11 eFuse cache offset.
XNVM_EFUSE_CACHE_TRIM_AMS_12
TRIM_AMS_12 eFuse cache offset.
XNVM_EFUSE_CACHE_TRIM_CFRM_VGG_0
TRIM_CFRM_VGG_0 eFuse cache offset.
XNVM_EFUSE_CACHE_TRIM_CFRM_VGG_1
TRIM_CFRM_VGG_1 eFuse cache offset.
XNVM_EFUSE_CACHE_TRIM_CFRM_VGG_2
TRIM_CFRM_VGG_2 eFuse cache offset.
XNVM_EFUSE_CACHE_TRIM_CRAM
TRIM_CRAM eFuse cache offset.
XNVM_EFUSE_CACHE_NIDB_0
NIDB_0 eFuse cache offset.
XNVM_EFUSE_CACHE_NIDB_1
NIDB_1 eFuse cache offset.
XNVM_EFUSE_CACHE_NIDB_2
NIDB_2 eFuse cache offset.
XNVM_EFUSE_CACHE_TRIM_AMS_0
TRIM_AMS_0 eFuse cache offset.
XNVM_EFUSE_CACHE_TRIM_AMS_1
TRIM_AMS_1 eFuse cache offset.
XNVM_EFUSE_CACHE_TRIM_AMS_2
TRIM_AMS_2 eFuse cache offset.
XNVM_EFUSE_CACHE_TRIM_AMS_3
TRIM_AMS_3 eFuse cache offset.
XNVM_EFUSE_CACHE_ME_ID_CODE_3_0_MASK
ME_ID_CODE_3_0_MASK.
XNVM_CRC_DATA_WORD_COUNT
CRC DATA word count.
XNVM_CRC_DATA_BYTE_COUNT
CRC data byte count.