spartanup/xnvm_efuse.c
XNVM_GET_8_BIT_VAL
API to extract bit mask.
static int XNvm_EfuseValidateAesWriteReq(const XNvm_EfuseAesKeys *AesKey)
< Prototype declarations for xilnvm efuse API's
This function validates AES efuse keys write request. AesKey - Pointer to XNvm_EfuseAesKeys. XST_SUCCESS - On success.XNVM_EFUSE_ERR_RD_SEC_CTRL_BITS - Error reading security control bits.XNVM_EFUSE_ERR_FUSE_PROTECTED | XNVM_EFUSE_ERR_WRITE_AES_KEY - AES fuses are protected.XNVM_EFUSE_ERR_AES_ALREADY_PRGMD - AES key is already programmed.
static int XNvm_EfuseValidatePpkWriteReq(const XNvm_EfusePpkHash *PpkHash)
This function validates PPK efuses write request.
PpkHash - Pointer to XNvm_EfusePpkHash. XST_SUCCESS - On success.XNVM_EFUSE_ERR_INVALID_PARAM - Invalid parameter.XNVM_EFUSE_ERR_PPK0_HASH_ALREADY_PRGMD - PPK0 hash is already programmed.XNVM_EFUSE_ERR_PPK1_HASH_ALREADY_PRGMD - PPK1 hash is already programmed.XNVM_EFUSE_ERR_PPK2_HASH_ALREADY_PRGMD - PPK2 hash is already programmed.
static int XNvm_EfuseValidateIvsWriteReq(const XNvm_EfuseAesIvs *Ivs)
This function validates IV efuses write request.
Ivs - Pointer to XNvm_EfuseAesIvs. XST_SUCCESS - On success.XNVM_EFUSE_ERR_BEFORE_PROGRAMMING | XNVM_EFUSE_ERR_BIT_CANT_REVERT - IV bits cannot be reverted.
static int XNvm_EfuseValidateDecOnlyWriteReq(const XNvm_EfuseData *EfuseData)
This function validates Deconly efuses write request.
EfuseData - Pointer to XNvm_EfuseData. XST_SUCCESS - On success.XNVM_EFUSE_ERR_DEC_ONLY_KEY_MUST_BE_PRGMD - AES key must be programmed before DEC_ONLY.XNVM_EFUSE_ERR_DEC_ONLY_HASH_OR_PUF_KEY_MUST_BE_PRGMD - Hash or PUF key must be programmed.XNVM_EFUSE_ERR_DEC_ONLY_ALREADY_PRGMD - DEC_ONLY is already programmed.
static int XNvm_EfuseValidateBeforeWriteReq(const XNvm_EfuseData *EfuseData)
This function validates user configured write requests before programming.
EfuseData - Pointer to XNvm_EfuseData. XST_SUCCESS - On success.XST_FAILURE - On validation failure.
static int XNvm_EfusePrgmAesKey(const XNvm_EfuseAesKeys *AesKey)
This function programs AES key and validates the CRC of the provided key with programmed key.
AesKey - Pointer to XNvm_EfuseAesKeys. XST_SUCCESS - On successful programming.XNVM_EFUSE_ERR_WRITE_AES_KEY - Error in AES key programming.
static int XNvm_EfusePrgmPpkHash(XNvm_EfusePpkHash *PpkHash)
This function programs PPK0/1/2 hash based on user request.
PpkHash - Pointer to XNvm_EfusePpkHash. XST_SUCCESS - On successful programming.XNVM_EFUSE_ERR_WRITE_PPK0_HASH - Error in PPK0 hash programming.XNVM_EFUSE_ERR_WRITE_PPK1_HASH - Error in PPK1 hash programming.XNVM_EFUSE_ERR_WRITE_PPK2_HASH - Error in PPK2 hash programming.
static int XNvm_EfusePrgmIv(XNvm_EfuseAesIvs *AesIv)
This function programs IV in to efuses.
AesIv - Pointer to XNvm_EfuseAesIvs. XST_SUCCESS - On successful programming.XNVM_EFUSE_ERR_WRITE_IV - Error in IV programming.
static int XNvm_EfusePrgmUserFuse(const XNvm_EfuseUserFuse *UserFuse)
This function programs user fuse.
UserFuse - Pointer to XNvm_EfuseUserFuse. XST_SUCCESS - On successful programming.XNVM_EFUSE_ERR_WRITE_USER_FUSE - Error in user fuse programming.
static int XNvm_EfusePrgmSpkRevokeId(const XNvm_EfuseSpkRevokeId *SpkRevokeId)
This function programs SPK revoke id based on user choice.
SpkRevokeId - Pointer to XNvm_EfuseSpkRevokeId. XST_SUCCESS - On successful programming.XNVM_EFUSE_ERR_WRITE_SPK_REVOKE_ID - Error in SPK revoke ID programming.
static int XNvm_EfusePrgmAesRevokeId(const XNvm_EfuseAesRevokeId *AesRevokeId)
This function programs AES revoke id based on user choice.
AesRevokeId - Pointer to XNvm_EfuseAesRevokeId. XST_SUCCESS - On successful programming.XNVM_EFUSE_ERR_WRITE_AES_REVOKE_ID - Error in AES revoke ID programming.
static int XNvm_EfusePrgmDecOnly(const XNvm_EfuseDecOnly *DecOnly)
This function programs DEC only fuses.
DecOnly - Pointer to XNvm_EfuseDecOnly. XST_SUCCESS - On successful programming.XNVM_EFUSE_ERR_WRITE_DEC_ONLY - Error in DEC only programming.
static int XNvm_EfusePrgmSecCtrlBits(const XNvm_EfuseSecCtrlBits *SecCtrl)
This function programs secure control bits.
SecCtrl - Pointer to XNvm_EfuseSecCtrl. XST_SUCCESS - On successful programming.XNVM_EFUSE_ERR_WRITE_AES_DIS - Error in AES disable programming.XNVM_EFUSE_ERR_WRITE_JTAG_DIS - Error in JTAG disable programming.XNVM_EFUSE_ERR_WRITE_PPK2_WR_LCK - Error in PPK2 write lock programming.XNVM_EFUSE_ERR_WRITE_PPK1_WR_LCK - Error in PPK1 write lock programming.XNVM_EFUSE_ERR_WRITE_PPK0_WR_LCK - Error in PPK0 write lock programming.XNVM_EFUSE_ERR_WRITE_AES_RD_WR_LCK0 - Error in AES read/write lock 0 programming.XNVM_EFUSE_ERR_WRITE_AES_RD_WR_LCK1 - Error in AES read/write lock 1 programming.XNVM_EFUSE_ERR_WRITE_PPK2_INVLD_0 - Error in PPK2 invalid 0 programming.XNVM_EFUSE_ERR_WRITE_PPK2_INVLD_1 - Error in PPK2 invalid 1 programming.XNVM_EFUSE_ERR_WRITE_PPK1_INVLD_0 - Error in PPK1 invalid 0 programming.XNVM_EFUSE_ERR_WRITE_PPK1_INVLD_1 - Error in PPK1 invalid 1 programming.XNVM_EFUSE_ERR_WRITE_PPK0_INVLD_0 - Error in PPK0 invalid 0 programming.XNVM_EFUSE_ERR_WRITE_PPK0_INVLD_1 - Error in PPK0 invalid 1 programming.XNVM_EFUSE_ERR_WRITE_PUF_TEST2_DIS - Error in PUF test2 disable programming.XNVM_EFUSE_ERR_WRITE_RMA_ENABLE_0 - Error in RMA enable 0 programming.XNVM_EFUSE_ERR_WRITE_RMA_ENABLE_1 - Error in RMA enable 1 programming.XNVM_EFUSE_ERR_WRITE_DFT_DIS_0 - Error in DFT disable 0 programming.XNVM_EFUSE_ERR_WRITE_DFT_DIS_1 - Error in DFT disable 1 programming.XNVM_EFUSE_ERR_WRITE_CRC_EN - Error in CRC enable programming.XNVM_EFUSE_ERR_WRITE_HASH_PUF_OR_KEY - Error in hash PUF or key programming.XNVM_EFUSE_ERR_WRITE_USER_WR_LK - Error in user write lock programming.XNVM_EFUSE_ERR_WRITE_JTAG_ERR_OUT_DIS - Error in JTAG error output disable programming.
static int XNvm_EfuseComputeProgrammableBits(const u32 *ReqData, u32 *PrgmData, u32 StartOffset, u32 EndOffset)
This function is used to compute the eFuse bits to be programmed to the eFuse.
ReqData - Pointer to the user provided eFuse data to be written. PrgmData - Pointer to the computed eFuse bits to be programmed, which means that this API fills only unprogrammed and valid bits. StartOffset - A 32 bit Start Cache offset of an expected Programmable Bits. EndOffset - A 32 bit End Cache offset of an expected Programmable Bits. XST_SUCCESS - if the eFuse data computation is successful.XNVM_EFUSE_ERR_INVALID_PARAM - On Invalid Parameter.XNVM_EFUSE_ERR_CACHE_PARITY - Error in Cache reload.
static int XNvm_EfuseCacheReload(void)
This function reloads the cache of eFUSE so that can be directly read from cache.
XST_SUCCESS - on successful cache reload.XNVM_EFUSE_ERR_CACHE_LOAD - Error while loading the cache. Not recommended to call this API frequently,if this API is called all the cache memory is reloaded by reading eFUSE array, reading eFUSE bit multiple times may diminish the life time.
static int XNvm_EfusePgmAndVerifyData(const XNvm_EfusePrgmInfo *EfusePrgmInfo, const u32 *RowData)
This function sets and then verifies the specified bits in the eFUSE.
EfusePrgmInfo - Pointer to XNvm_EfusePrgmInfo structure stores the info required to program the eFuses RowData - Pointer to memory location where bitmap to be written is stored. Only bit set are used for programming eFUSE. XST_SUCCESS - Specified bit set in eFUSE.XNVM_EFUSE_ERR_INVALID_PARAM - On Invalid Parameter.
static int XNvm_EfusePgmBit(u32 Row, u32 Col)
This function sets the specified bit in the eFUSE.
Row - It is an 32-bit Row number (0-based addressing). Col - It is an 32-bit Col number (0-based addressing). XST_SUCCESS - Specified bit set in eFUSE.XNVM_EFUSE_ERR_PGM_TIMEOUT - eFUSE programming timed out.XNVM_EFUSE_ERR_PGM - eFUSE programming failed.
static int XNvm_EfuseReadRow(u32 Row, u32 *RegData)
This function verify the specified bit set in the eFUSE.
Row - It is an 32-bit Row number (0-based addressing). RegData - Pointer to the register value. XST_SUCCESS - Specified bit set in eFUSE.XNVM_EFUSE_ERR_PGM_VERIFY - Verification failed, specified bit is not set.XNVM_EFUSE_ERR_PGM_TIMEOUT - If Programming timeout has occurred.XST_FAILURE - Unexpected error.
static int XNvm_EfuseVerifyBit(u32 Row, u32 Col)
This function verify the specified bit set in the eFUSE.
Row - It is an 32-bit Row number (0-based addressing). Col - It is an 32-bit Col number (0-based addressing). XST_SUCCESS - Specified bit set in eFUSE.XNVM_EFUSE_ERR_PGM_VERIFY - Verification failed, specified bit is not set.XNVM_EFUSE_ERR_PGM_TIMEOUT - If Programming timeout has occurred.XST_FAILURE - Unexpected error.
static int XNvm_EfusePgmAndVerifyBit(u32 Row, u32 Col, u32 SkipVerify)
This function sets and then verifies the specified bit in the eFUSE.
Row - It is an 32-bit Row number (0-based addressing). Col - It is an 32-bit Col number (0-based addressing). SkipVerify - Skips verification of bit if set to non zero XST_SUCCESS - Specified bit set in eFUSE.XNVM_EFUSE_ERR_PGM_TIMEOUT - eFUSE programming timed out.XNVM_EFUSE_ERR_PGM - eFUSE programming failed.XNVM_EFUSE_ERR_PGM_VERIFY - Verification failed, specified bit is not set.XST_FAILURE - Unexpected error.
static int XNvm_EfuseReadCache(u32 Offset, u32 *RowData)
This function reads 32-bit data from cache specified by Row.
Offset - Offset from which data should be read (0-based addressing). RowData - Pointer to memory location where read 32-bit row data is to be stored. XST_SUCCESS - Specified data read.XNVM_EFUSE_ERR_CACHE_PARITY - Parity Error exist in cache.
static int XNvm_EfuseReadCacheRange(u32 StartOffset, u8 OffsetCount, u32 *RowData)
This function reads 32-bit rows from eFUSE cache.
StartOffset - Starting Row number (0-based addressing). OffsetCount - Number of offset to be read. RowData - Pointer to memory location where read 32-bit row data(s) is to be stored. XST_SUCCESS - Specified data read. XNVM_EFUSE_ERR_CACHE_PARITY - Parity Error exist in cache.
static int XNvm_EfuseCheckZeros(u32 OffsetStart, u32 OffsetEnd)
This function is used verify eFUSEs for Zeros.
OffsetStart - Row number from which verification has to be started. OffsetEnd - Row number till which verification has to be ended. XST_SUCCESS - if efuses are not programmed.XST_FAILURE - if efuses are already programmed.
static int XNvm_EfusePrgmPufHDInvld(const XNvm_EfuseXilinxCtrl *PufHDInvld)
This function is used to program PUFHD_INVLD fuses.
PufHDInvld - Pointer to XNvm_EfuseXilinxCtrl structure which holds PufHDInvld flag which says to program eFuse. XST_SUCCESS Specified data read.XNVM_EFUSE_ERR_INVALID_PARAM Invalid input parameter.XNVM_EFUSE_ERR_WRITE_PUF_HD_INVLD Error in PUFHD_INVLD programming.
static int XNvm_EfusePrgmRomOspiCmdSeqCtrl(const XNvm_EfuseXilinxCtrl *XilinxCtrl)
This function is used to program ROM_OSPI_CMD_SEQ_CTRL eFuse bits.
XilinxCtrl - Pointer to XNvm_EfuseXilinxCtrl structure which holds PrgmRomOspiCmdSeqCtrl value to program into eFuse. XST_SUCCESS On successful programming.XNVM_EFUSE_ERR_INVALID_PARAM On NULL pointer input.XNVM_EFUSE_ERR_WRITE_ROM_OSPI_CMD_SEQ_CTRL Error in ROM_OSPI_CMD_SEQ_CTRL efuse programming.
static int XNvm_EfusePrgmXilinxCtrl(const XNvm_EfuseXilinxCtrl *XilinxCtrl)
This function is used to program XILINX_CTRL fuses.
XilinxCtrl - Pointer to XNvm_EfuseXilinxCtrl structure which holds PufHDInvld, PrgmDisSJtag, PrgmOspiResetRecoveryDelayCtrl, PrgmRomRsvdOspiDevResetChoice and PrgmRomOspiCmdSeqCtrl flags which say to program eFuse. XST_SUCCESS Specified data read.XNVM_EFUSE_ERR_INVALID_PARAM Invalid input parameter.XNVM_EFUSE_ERR_WRITE_PUF_HD_INVLD Error in PUFHD_INVLD programming.XNVM_EFUSE_ERR_WRITE_DIS_SJTAG Error in DIS_SJTAG programming.XNVM_EFUSE_ERR_WRITE_OSPI_RESET_RECOVERY_DELAY_CTRL Error in OSPI Reset Recovery Delay Control programming.XNVM_EFUSE_ERR_WRITE_ROM_RSVD_OSPI_DEV_RESET_CHOICE Error in ROM RSVD OSPI Device Reset Choice programming.XNVM_EFUSE_ERR_WRITE_ROM_OSPI_CMD_SEQ_CTRL Error in ROM OSPI Cmd Seq Ctrl programming.
static int XNvm_EfuseInitClockAndValidateFreq(XNvm_EfuseData *EfuseData)
Initializes the eFUSE clock and validates its frequency.
This function sets up the Efuse clock configuration required for eFUSE programming and verifies that the clock frequency is within the supported range for reliable operation. EfuseData Pointer to the XNvm_EfuseData. XST_SUCCESS Clock initialization and frequency validation were successful.XNVM_EFUSE_ERR_INVALID_FREQUENCY If clock frequency is invalid.
int XNvm_EfuseWrite(XNvm_EfuseData *EfuseData)
This function is used to program the eFUSE of spartan ultrascale plus, based on user inputs.
EfuseData Pointer to the XNvm_EfuseData. XST_SUCCESS if programs successfully.XNVM_EFUSE_ERR_INVALID_PARAM - On invalid parameterXNVM_EFUSE_ERR_NTHG_TO_BE_PROGRAMMED - Nothing to be programmedXNVM_EFUSE_ERR_BEFORE_PROGRAMMING - Error before programming After eFUSE programming is complete, the cache is automatically reloaded so all programmed eFUSE bits can be directly read from cache.
References XNVM_EFUSE_ERR_INVALID_PARAM, XNvm_EfuseData::AesKeys, XNvm_EfuseData::AesRevokeId, XNvm_EfuseData::DecOnly, XNvm_EfuseData::Ivs, XNvm_EfuseData::PpkHash, XNvm_EfuseData::SecCtrlBits, XNvm_EfuseData::SpkRevokeId, XNvm_EfuseData::XilinxCtrl, XNvm_EfuseData::UserFuse, XNVM_EFUSE_ERR_NTHG_TO_BE_PROGRAMMED, XNvm_EfuseTempAndVoltChecks, XNvm_EfuseData::SysMonInstPtr, XNvm_EfuseSetupController, XNVM_EFUSE_MODE_PGM, XNVM_EFUSE_MARGIN_RD, XNvm_EfuseData::EfuseClkFreq, XNVM_EFUSE_ERR_BEFORE_PROGRAMMING, XNvm_EfuseCacheReload, XNvm_EfuseResetReadMode, XNvm_EfuseDisableProgramming, XNvm_EfuseLockController, XNvm_EfuseReadSecCtrlBits.
Referenced by XNvm_EfuseWriteIVs, XNvm_EfuseRevokePpk, XNvm_EfuseWriteRevocationId, XNvm_EfuseWriteUserFuses.
int XNvm_EfuseReadSecCtrlBits(XNvm_EfuseSecCtrlBits *SecCtrlBits)
This function reads secure control bits and CRC_EN register bits from eFUSE cache.
SecCtrlBits - Pointer to XNvm_EfuseSecCtrlBits where secure control bits are read. Device-specific behavior: **SPARTANUPLUS devices:** - Supports PPK0, PPK1, and PPK2 (three PPK hashes) - PPK hash size: 256 bits (32 bytes) - Reads Ppk2lck and Ppk2Invld bits for PPK2 - PPK2 eFUSE registers are shared between PPK2 hash and PUF hash storage - The HashPufOrKey bit determines which hash type is stored: * When HashPufOrKey = 0: PPK2 registers contain PPK2 hash * When HashPufOrKey = 1: PPK2 registers contain PUF hash - When programming PUF hash: * Ppk2Invld must be 0 (PPK2 register not invalidated) * Ppk2lck must be 0 (PPK2 register not write-locked) * PPK2 registers must not be already programmed * HashPufOrKey must be set to 1 to indicate PUF hash usage **SPARTANUPLUSAES1 devices:** - Supports only PPK0 and PPK1 (two PPK hashes) - PPK hash size: 384 bits (48 bytes) - Ppk2lck and Ppk2Invld fields are not available - Reads Ppk1lck and Ppk1Invld bits for PPK1 - PPK1 eFUSE registers are shared between PPK1 hash and PUF hash storage - The HashPufOrKey bit determines which hash type is stored: * When HashPufOrKey = 0: PPK1 registers contain PPK1 hash * When HashPufOrKey = 1: PPK1 registers contain PUF hash - When programming PUF hash: * Ppk1Invld must be 0 (PPK1 register not invalidated) * Ppk1lck must be 0 (PPK1 register not write-locked) * PPK1 registers must not be already programmed * HashPufOrKey must be set to 1 to indicate PUF hash usage XST_SUCCESS - Specified data read.XNVM_EFUSE_ERR_INVALID_PARAM - Invalid parameter.XNVM_EFUSE_ERR_CACHE_PARITY - Parity Error exist in cache.
Referenced by XNvm_EfuseWrite.
int XNvm_EfuseReadPpkHash(XNvm_EfusePpkType PpkType, u32 *PpkData, u32 PpkSize)
This function reads PPK0/1/2 hash based on XNvm_EfusePpkType from eFUSE cache.
PpkType - is of type XNvm_EfusePpkType i.e. PPK0/1/2. PpkData - Pointer to the PPK data. PpkSize - Size of PPK it is either 32 or 48 bytes. XST_SUCCESS - Specified data read.XNVM_EFUSE_ERR_INVALID_PARAM - Invalid input parameter.XST_FAILURE - Error in cache read operation.
References XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_PPK_HASH_256_SIZE_IN_BYTES, XNVM_EFUSE_PPK_HASH_384_SIZE_IN_BYTES, XNVM_EFUSE_PPK2, XNVM_EFUSE_PPK0, XNVM_EFUSE_WORD_LEN, XNVM_EFUSE_PPK1, XNvm_EfuseReadCacheRange.
int XNvm_EfuseReadSpkRevokeId(u32 *SpkRevokeData, u32 SpkRevokeRow)
This function reads SPK revoke id from eFUSE cache.
SpkRevokeData - is pointer to SPK revoke data. SpkRevokeRow - SPK revoke row to be read it can be either 0/1/2. XST_SUCCESS - Specified data read.XNVM_EFUSE_ERR_INVALID_PARAM - On invalid parameter
References XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_MAX_SPK_REVOKE_ID, XNVM_EFUSE_WORD_LEN.
int XNvm_EfuseReadAesRevokeId(u32 *AesRevokeData)
This function reads AES revoke id from eFUSE cache.
AesRevokeData - is pointer to AES revoke data. XST_SUCCESS - Specified data read.XNVM_EFUSE_ERR_INVALID_PARAM - On invalid parameter
References XNVM_EFUSE_ERR_INVALID_PARAM.
int XNvm_EfuseReadUserFuse(u32 *UserFuseData)
This function reads user efuses from eFUSE cache.
UserFuseData - is pointer to AES revoke data. XST_SUCCESS - Specified data read.XNVM_EFUSE_ERR_INVALID_PARAM - On invalid parameter
References XNVM_EFUSE_ERR_INVALID_PARAM.
int XNvm_EfuseReadIv(XNvm_EfuseIvType IvType, u32 *IvData)
This function reads IV based on XNvm_EfuseIvType from eFUSE cache.
IvType - is of type XNvm_EfuseIvType. IvData - Pointer to the iv data. XST_SUCCESS - Specified data read.XNVM_EFUSE_ERR_INVALID_PARAM - On invalid parameter
References XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_AES_IV_RANGE, XNVM_EFUSE_BLACK_IV, XNvm_EfuseReadCacheRange, XNVM_EFUSE_AES_IV_SIZE_IN_WORDS.
int XNvm_EfuseReadDna(u32 *Dna)
This function reads DNA from eFUSE cache.
Dna - Pointer to the DNA data. XST_SUCCESS - Specified data read.XNVM_EFUSE_ERR_INVALID_PARAM - On invalid parameter
References XNVM_EFUSE_ERR_INVALID_PARAM, XNvm_EfuseReadCacheRange, XNVM_EFUSE_DNA_SIZE_IN_WORDS.
int XNvm_EfuseReadDecOnly(u32 *DecOnly)
This function reads DEC only fuses from eFUSE cache.
DecOnly - Pointer to the DEC only efuse data. XST_SUCCESS - Specified data read.XNVM_EFUSE_ERR_INVALID_PARAM - On invalid parameter
int XNvm_EfuseReadXilinxCtrl(XNvm_EfuseXilinxCtrl *XilinxCtrl)
This function reads Xilinx Ctrl fuse from eFUSE cache.
XilinxCtrl - Pointer to the XilinxCtrl efuse data. XST_SUCCESS - Specified data read.XNVM_EFUSE_ERR_INVALID_PARAM - On invalid parameter
References XNVM_EFUSE_ERR_INVALID_PARAM, XNvm_EfuseXilinxCtrl::PrgmPufHDInvld, XNvm_EfuseXilinxCtrl::PrgmDisSJtag, XNvm_EfuseXilinxCtrl::PrgmOspiResetRecoveryDelayCtrl, XNvm_EfuseXilinxCtrl::PrgmRomRsvdOspiDevResetChoice, XNvm_EfuseXilinxCtrl::PrgmRomOspiCmdSeqCtrl.