spartanup/xnvm_utils.c
static int XNvm_EfuseSetReadMode(XNvm_EfuseRdMode RdMode)
This function sets read mode of eFUSE controller.
RdMode - Mode to be used for eFUSE read. XST_SUCCESS - if Setting read mode is successful.XST_FAILURE - if there is a failure
static int XNvm_EfuseCheckForTBits(void)
This function checks whether Tbits are programmed or not.
XST_SUCCESS - On Success.XNVM_EFUSE_ERR_PGM_TBIT_PATTERN - Error in T-Bit pattern.
static void XNvm_EfuseEnableProgramming(void)
This function enabled programming mode of eFUSE controller.
static void XNvm_EfuseInitTimers(u32 ClkFreq)
This function initializes eFUSE controller timers.
int XNvm_EfuseDisableProgramming(void)
This function disables programming mode of eFUSE controller.
XST_SUCCESS - if eFUSE programming is disabled successfully.XST_FAILURE - if there is a failure
Referenced by XNvm_EfuseWrite, XNvm_EfuseWritePuf.
int XNvm_EfuseResetReadMode(void)
This function disables Margin Read mode of eFUSE controller.
XST_SUCCESS - if resetting read mode is successful.XST_FAILURE - if there is a failure
Referenced by XNvm_EfuseWrite, XNvm_EfuseWritePuf.
int XNvm_EfuseSetupController(XNvm_EfuseOpMode Op, XNvm_EfuseRdMode RdMode, u32 EfuseClkFreq)
This function sets up eFUSE controller for given operation and read mode.
Op - Operation to be performed read/program(write). RdMode - Read mode for eFUSE read operation. EfuseClkFreq - Input Clock frequency for timers initialization. XST_SUCCESS - eFUSE controller setup for given op.XNVM_EFUSE_ERR_UNLOCK - Failed to unlock eFUSE controller register access.XNVM_EFUSE_ERR_PGM_TBIT_PATTERN - Error in T-Bit pattern.XST_FAILURE - Error on set read mode failure.
References XNvm_EfuseUnlockController, XNVM_EFUSE_MODE_PGM, XNvm_EfuseEnableProgramming, XNvm_EfuseSetReadMode, XNvm_EfuseInitTimers, XNvm_EfuseWriteReg, XNVM_EFUSE_CTRL_BASEADDR, XNVM_EFUSE_TEST_CTRL_REG_OFFSET, XNvm_EfuseCheckForTBits.
Referenced by XNvm_EfuseWrite, XNvm_EfuseWritePuf, XNvm_EfuseWriteAesKey, XNvm_EfuseWritePpkHash, XNvm_EfuseWriteIv, XNvm_EfuseWriteGlitchConfigBits, XNvm_EfuseWriteDecOnly, XNvm_EfuseWriteRevocationID, XNvm_EfuseWriteOffChipRevokeID, XNvm_EfuseWriteMiscCtrlBits, XNvm_EfuseWriteSecCtrlBits, XNvm_EfuseWriteMisc1Bits, XNvm_EfuseWriteBootEnvCtrlBits, XNvm_EfuseWriteFipsInfo, XNvm_EfuseWriteUds, XNvm_EfuseWriteDmeUserKey, XNvm_EfuseWriteDmeRevoke, XNvm_EfuseWriteDisableInplacePlmUpdate, XNvm_EfuseWriteBootModeDisable, XNvm_EfuseWriteDmeMode, XNvm_EfuseWriteCrc, XNvm_EfuseWritePufSecCtrl, XNvm_EfuseCacheLoadNPrgmProtectionBits, XNvm_EfuseWriteRomRsvdBits.
u32 XNvm_EfuseReadReg(u32 BaseAddress, u32 RegOffset)
This function reads the given register.
BaseAddress - eFuse controller base address. RegOffset - Register offset from the base address. The 32-bit value of the register.
Referenced by XNvm_EfuseWriteUds, XNvm_EfuseWriteCrc, XNvm_EfuseWritePuf, XNvm_EfuseCacheReload, XNvm_EfuseDisablePowerDown, XNvm_EfuseSetReadMode, XNvm_EfuseEnableProgramming, XNvm_EfuseDisableProgramming, XNvm_EfuseResetReadMode, XNvm_EfuseCheckForTBits, XNvm_EfuseReadProtectionBits, XNvm_EfuseLockController, XNvm_EfuseUnlockController, XNvm_EfuseCheckAesKeyCrc, XNvm_EfuseValidateAesKeyWriteReq, XNvm_EfuseValidatePpkHashWriteReq, XNvm_EfuseCheckZeros, XNvm_EfuseIsPufHelperDataEmpty, XNvm_EfuseValidateDecOnlyRequest, XNvm_EfuseValidateFipsInfo, XNvm_IsDmeModeEn.
void XNvm_EfuseWriteReg(u32 BaseAddress, u32 RegOffset, u32 Data)
This function writes the value into the given register.
BaseAddress - eFuse controller base address. RegOffset - Register offset from the base address. Data - 32-bit value to be written to the register.
Referenced by XNvm_EfuseCacheReload, XNvm_EfuseDisablePowerDown, XNvm_EfuseSetRefClk, XNvm_EfuseEnableProgramming, XNvm_EfuseInitTimers, XNvm_EfuseSetupController, XNvm_EfuseLockController, XNvm_EfuseUnlockController, XNvm_EfuseCheckAesKeyCrc.
int XNvm_EfuseLockController(void)
This function locks the eFUSE Controller to prevent accidental writes to eFUSE controller registers.
XST_SUCCESS - eFUSE controller locked.XNVM_EFUSE_ERR_LOCK - Failed to lock eFUSE controller register access.
Referenced by XNvm_EfuseWrite, XNvm_EfuseWritePuf, XNvm_EfuseCheckAesKeyCrc.
int XNvm_EfuseUnlockController(void)
This function unlocks the eFUSE Controller for writing to its registers.
XST_SUCCESS - eFUSE controller unlocked.XNVM_EFUSE_ERR_UNLOCK - Failed to unlock eFUSE controller register access.
Referenced by XNvm_EfuseSetupController, XNvm_EfuseCheckAesKeyCrc.
u32 XNvm_AesCrcCalc(const u32 *Key)
This function calculates CRC of AES key.
Key - Pointer to the little-endian formatted key for which CRC has to be calculated. CRC of AES key.
int XNvm_ZeroizeAndVerify(u8 *DataPtr, const u32 Length)
This function zeroizes the memory and verifies that the memory has been correctly zeroized.
DataPtr Pointer to the memory which need to be zeroized. Length Length of the data in bytes. XST_SUCCESS: If Zeroization is successful.XST_FAILURE: If Zeroization is not successful.
Referenced by XNvm_EfuseReadIv, XNvm_EfuseReadPuf.
int XNvm_EfuseCheckAesKeyCrc(u32 CrcRegOffSet, u32 CrcDoneMask, u32 CrcPassMask, u32 Crc)
This function performs the CRC check of AES key/User0 key/User1 key.
CrcRegOffSet - Register offset of respective CRC register CrcDoneMask - Respective CRC done mask in status register CrcPassMask - Respective CRC pass mask in status register Crc - A 32 bit CRC value of an expected AES key. XST_SUCCESS - On successful CRC check.XNVM_EFUSE_ERR_CRC_VERIFICATION - If AES boot key integrity check is failed.XST_FAILURE - If AES boot key integrity check has not finished. Expected CRC calculation steps: Convert the key provided at XNVM_EFUSE_AES_KEY into hexadecimal little-endian format.Calculate the CRC on this little-endian formatted AES key using XNvm_AesCrcCalc() function.Provide the calculated CRC as the value of expected CRC.
Referenced by XNvm_EfuseWriteUds, XNvm_EfuseValidateAesKeyWriteReq, XNvm_EfuseValidateDecOnlyRequest.