versal_gen/versal/server/xnvm_efuse.h
XNVM_USER_FUSE_START_NUM
User eFuse start number.
Referenced by XNvm_EfuseReadUserFuses.
XNVM_USER_FUSE_END_NUM
User eFuse end number.
Referenced by XNvm_EfuseReadUserFuses.
XNVM_NUM_OF_USER_FUSES
Number of user eFuses.
Referenced by XNvm_EfuseReadUserFuses.
XNVM_EFUSE_PROTECTION_BIT_SECURITY_CONTROL_MASK
Security control protection bit mask.
XNVM_EFUSE_PROTECTION_BIT_SECURITY_MISC_0_MASK
Security misc 0 control protection bit mask.
XNVM_EFUSE_PROTECTION_BIT_PPK_0_HASH_MASK
PPK 0 hash protection bit mask.
XNVM_EFUSE_PROTECTION_BIT_META_HEADER_IV_MASK
Meta header IV protection bit mask.
XNVM_EFUSE_BOOTENVCTRL_ANLGTRIMX_TRIMAMS_MASK
Boot env ctrl ANLGTRIMX TRIMAMS protection bit mask.
XNVM_EFUSE_PROTECTION_BIT_MISC_CTRL_MASK
Misc control protection bit mask.
XNVM_EFUSE_PROTECTION_BIT_PUF_CHASH_MASK
PUF CHASH protection bit mask.
XNVM_EFUSE_PROTECTION_BIT_SECURITY_MISC_1_MASK
Security misc 1 protection bit mask.
XNVM_PUF_FORMATTED_SYN_DATA_LEN_IN_WORDS
PUF syndrome length definitions for Versal eFuse.
XNVM_PUF_ROW_UPPER_NIBBLE_MASK
Mask to extract upper nibble of a PUF row.
XNVM_MAX_REVOKE_ID_FUSES
Maximum eFuses in a row.
XNvm_SecCtrlBitColumns
Aes disable.
XNvm_MiscCtrlBitColumns
Ppk0 invalid bit 0.
int XNvm_EfuseWrite(const XNvm_EfuseData *WriteNvm)
This function is used as a wrapper to program below eFuses AES key User key 0 User key 1 PPK0/PPK1/PPK2/PPK3/PPK4 hash IVs Revocation Ids User Fuses Secure and Control bits.
Miscellaneous Control bits. Security Miscellaneous1 bits. BootEnvCtrl bits. WriteNvm - Pointer to Efuse data to be written. XST_SUCCESS On Specified data write.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_NTHG_TO_BE_PROGRAMMED If nothing is programmed.XNVM_EFUSE_ERR_BEFORE_PROGRAMMING If error before programming.XNVM_EFUSE_ERR_LOCK Lock eFUSE Control Register. After eFUSE programming is complete, the cache is automatically reloaded so all programmed eFUSE bits can be directly read from cache. If there is any CACHE_ERROR, user can reboot the system to reload the cache.
References XNVM_EFUSE_ERR_INVALID_PARAM, XNvm_EfuseData::AesKeys, XNvm_EfuseData::PpkHash, XNvm_EfuseData::DecOnly, XNvm_EfuseData::SecCtrlBits, XNvm_EfuseData::RevokeIds, XNvm_EfuseData::MiscCtrlBits, XNvm_EfuseData::Ivs, XNvm_EfuseData::UserFuses, XNvm_EfuseData::GlitchCfgBits, XNvm_EfuseData::BootEnvCtrl, XNvm_EfuseData::Misc1Bits, XNvm_EfuseData::OffChipIds, XNVM_EFUSE_ERR_NTHG_TO_BE_PROGRAMMED, XNvm_EfuseData::EnvMonitorDis, XNvm_EfuseData::SysMonInstPtr, XNvm_EfuseTempAndVoltChecks, XNVM_EFUSE_ERR_BEFORE_PROGRAMMING, XNvm_EfuseSetupController, XNVM_EFUSE_MODE_PGM, XNVM_EFUSE_MARGIN_RD, XNvm_EfuseGlitchCfgBits::GlitchDetWrLk, XNvm_EfuseGlitchCfgBits::GdRomMonitorEn, XNvm_EfuseGlitchCfgBits::GdHaltBootEn, XNvm_EfuseMiscCtrlBits::HaltBootError, XNvm_EfuseMiscCtrlBits::HaltBootEnv, XNvm_EfuseMiscCtrlBits::CryptoKatEn, XNvm_EfuseMiscCtrlBits::LbistEn, XNvm_EfuseMiscCtrlBits::SafetyMissionEn, XNvm_EfuseResetReadMode, XNvm_EfuseDisableProgramming, XNvm_EfuseLockController.
int XNvm_EfuseWriteIVs(XNvm_EfuseIvs *EfuseIv, XSysMonPsv *SysMonInstPtr)
This function programs the eFUSEs with the IV.
EfuseIv - Pointer to the XNvm_EfuseIvs, which contains IVs data to be written to the Efuse.. SysMonInstPtr - Pointer to the XSysMonPsv structure which contains XSysmonPsv driver instance data XST_SUCCESS On Successful Write.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_WRITE_META_HEADER_IV Error while writing MetaHeader Iv.XNVM_EFUSE_ERR_WRITE_BLK_OBFUS_IV Error while writing BlkObfus IV.XNVM_EFUSE_ERR_WRITE_PLM IV Error while writing PLM IV.XNVM_EFUSE_ERR_WRITE_DATA_PARTITION_IV Error while writing Data Partition IV.XNVM_EFUSE_ERR_NTHG_TO_BE_PROGRAMMED If NULL request is sent.
References XNVM_EFUSE_ERR_NTHG_TO_BE_PROGRAMMED, XNvm_EfuseData::EnvMonitorDis, XNvm_EfuseData::SysMonInstPtr, XNvm_EfuseData::Ivs, XNvm_EfuseWrite.
int XNvm_EfuseRevokePpk(XNvm_PpkType PpkRevoke, XSysMonPsv *SysMonInstPtr)
This function revokes the Ppk.
PpkRevoke - Xnvm_RevokePpkFlags that tells which Ppk to revoke. SysMonInstPtr - Pointer to the XSysMonPsv structure which contains XSysmonPsv driver instance data XST_SUCCESS On Successful Revocation.XNVM_EFUSE_ERR_INVALID_PARAM Input validation failure.
References XNVM_EFUSE_PPK0, XNVM_EFUSE_PPK1, XNVM_EFUSE_PPK2, XNVM_EFUSE_ERR_INVALID_PARAM, XNvm_EfuseMiscCtrlBits::Ppk0Invalid, XNvm_EfuseMiscCtrlBits::Ppk1Invalid, XNvm_EfuseMiscCtrlBits::Ppk2Invalid, XNvm_EfuseData::EnvMonitorDis, XNvm_EfuseData::SysMonInstPtr, XNvm_EfuseData::MiscCtrlBits, XNvm_EfuseWrite.
int XNvm_EfuseWriteRevocationId(u32 RevokeId, XSysMonPsv *SysMonInstPtr)
This function writes Revocation eFuses.
RevokeId - RevokeId number to program Revocation Id eFuses. SysMonInstPtr - Pointer to the XSysMonPsv structure which contains XSysmonPsv driver instance data XST_SUCCESS On successful write to eFuse.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_LOCK Error while Locking the controller. Example: If the revoke id to program is 64, it will program the 0th bit of the REVOCATION_ID_2 eFuse row.
References XNVM_MAX_REVOKE_ID_FUSES, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_MAX_BITS_IN_ROW, XNvm_EfuseData::EnvMonitorDis, XNvm_EfuseData::SysMonInstPtr, XNvm_EfuseRevokeIds::RevokeId, XNvm_EfuseRevokeIds::PrgmRevokeId, XNvm_EfuseData::RevokeIds, XNvm_EfuseWrite.
int XNvm_EfuseWriteUserFuses(XNvm_EfuseUserData *WriteUserFuses, XSysMonPsv *SysMonInstPtr)
This function Programs User eFuses.
WriteUserFuses - Pointer to the XNvm_EfuseUserData structure. SysMonInstPtr - Pointer to the XSysMonPsv structure which contains XSysmonPsv driver instance data XST_SUCCESS If programming is successful.XNVM_EFUSE_ERR_NTHG_TO_BE_PROGRAMMED If NULL request is sent.
References XNVM_EFUSE_ERR_NTHG_TO_BE_PROGRAMMED, XNvm_EfuseData::EnvMonitorDis, XNvm_EfuseData::SysMonInstPtr, XNvm_EfuseData::UserFuses, XNvm_EfuseWrite.
int XNvm_EfuseReadIv(XNvm_Iv *EfuseIv, XNvm_IvType IvType)
This function is used to read IV eFUSE bits from cache.
EfuseIv - Pointer to the XNvm_Iv, which contains read IV data. IvType - Iv to be read. XST_SUCCESS On Successful read.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_RD_META_HEADER_IV_RANGE Error while reading MetaHeader IV.XNVM_EFUSE_ERR_RD_BLACK_IV Error while reading BlkObfus IV.XNVM_EFUSE_ERR_RD_PLM_IV_RANGE Error while reading PLM IV.XNVM_EFUSE_ERR_RD_DATA_PARTITION_IV_RANGE Error while reading Data Partition IV.XNVM_EFUSE_ERR_IN_ZEROIZATION Error in zeroization.
References XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_BLACK_IV, XNVM_EFUSE_PLM_IV_RANGE, XNVM_EFUSE_DATA_PARTITION_IV_RANGE, XNVM_EFUSE_META_HEADER_IV_RANGE, XNvm_EfuseReadCacheRange, XNVM_EFUSE_META_HEADER_IV_START_ROW, XNVM_EFUSE_IV_NUM_OF_ROWS, XNvm_Iv::Iv, XNVM_EFUSE_ERR_RD_META_HEADER_IV_RANGE, XNVM_EFUSE_BLACK_OBFUS_IV_START_ROW, XNVM_EFUSE_ERR_RD_BLACK_IV, XNVM_EFUSE_PLM_IV_START_ROW, XNVM_EFUSE_ERR_RD_PLM_IV_RANGE, XNVM_EFUSE_DATA_PARTITION_IV_START_ROW, XNVM_EFUSE_ERR_RD_DATA_PARTITION_IV_RANGE, XNvm_ZeroizeAndVerify, XNVM_EFUSE_ERR_IN_ZEROIZATION.
int XNvm_EfuseReadRevocationId(u32 *RevokeFusePtr, XNvm_RevocationId RevokeFuseNum)
This function reads the Revocation Fuse from eFUSE cache.
RevokeFusePtr - Pointer to the data which hold the Revocation IDs from eFUSE Cache. RevokeFuseNum - Revocation ID fuse number to read. XST_SUCCESS On successful read.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_CACHE_PARITY Error in Cache reload.
References XNVM_EFUSE_REVOCATION_ID_7, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_REVOCATION_ID_0_ROW.
int XNvm_EfuseReadUserFuses(const XNvm_EfuseUserData *UserFusesData)
This function reads User eFuses from Cache.
UserFusesData - UserFuseData to be read from eFuse Cache. XST_SUCCESS If reads successfully.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_RD_USER_FUSES Error in reading User fuses.
References XNVM_EFUSE_ERR_INVALID_PARAM, XNvm_EfuseUserData::StartUserFuseNum, XNVM_USER_FUSE_START_NUM, XNVM_USER_FUSE_END_NUM, XNvm_EfuseUserData::UserFuseData, XNvm_EfuseUserData::NumOfUserFuses, XNVM_NUM_OF_USER_FUSES, XNVM_EFUSE_USER_FUSE_START_ROW, XNvm_EfuseReadCacheRange, XNVM_EFUSE_ERR_RD_USER_FUSES.
int XNvm_EfuseReadMiscCtrlBits(XNvm_EfuseMiscCtrlBits *MiscCtrlBits)
This function is used to read the miscellaneous eFUSE control bits from cache.
MiscCtrlBits - Pointer to the XNvm_MiscCtrlBits which holds the read secure control bits. XST_SUCCESS On Successful read.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_CACHE_PARITY Error while Cache reload.
References XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_MISC_CTRL_ROW, XNvm_EfuseMiscCtrlBits::GlitchDetHaltBootEn, XNVM_EFUSE_CACHE_MISC_CTRL_GD_HALT_BOOT_EN_1_0_MASK, XNVM_EFUSE_CACHE_MISC_CTRL_GD_HALT_BOOT_EN_1_0_SHIFT, XNvm_EfuseMiscCtrlBits::GlitchDetRomMonitorEn, XNVM_EFUSE_CACHE_MISC_CTRL_GD_ROM_MONITOR_EN_MASK, XNVM_EFUSE_CACHE_MISC_CTRL_GD_ROM_MONITOR_EN_SHIFT, XNvm_EfuseMiscCtrlBits::HaltBootError, XNVM_EFUSE_CACHE_MISC_CTRL_HALT_BOOT_ERROR_1_0_MASK, XNVM_EFUSE_CACHE_MISC_CTRL_HALT_BOOT_ERROR_1_0_SHIFT, XNvm_EfuseMiscCtrlBits::HaltBootEnv, XNVM_EFUSE_CACHE_MISC_CTRL_HALT_BOOT_ENV_1_0_MASK, XNVM_EFUSE_CACHE_MISC_CTRL_HALT_BOOT_ENV_1_0_SHIFT, XNvm_EfuseMiscCtrlBits::CryptoKatEn, XNVM_EFUSE_CACHE_MISC_CTRL_CRYPTO_KAT_EN_MASK, XNVM_EFUSE_CACHE_MISC_CTRL_CRYPTO_KAT_EN_SHIFT, XNvm_EfuseMiscCtrlBits::LbistEn, XNVM_EFUSE_CACHE_MISC_CTRL_LBIST_EN_MASK, XNVM_EFUSE_CACHE_MISC_CTRL_LBIST_EN_SHIFT, XNvm_EfuseMiscCtrlBits::SafetyMissionEn, XNVM_EFUSE_CACHE_MISC_CTRL_SAFETY_MISSION_EN_MASK, XNVM_EFUSE_CACHE_MISC_CTRL_SAFETY_MISSION_EN_SHIFT, XNvm_EfuseMiscCtrlBits::Ppk0Invalid, XNVM_EFUSE_CACHE_MISC_CTRL_PPK0_INVLD_1_0_MASK, XNVM_EFUSE_CACHE_MISC_CTRL_PPK0_INVLD_1_0_SHIFT, XNvm_EfuseMiscCtrlBits::Ppk1Invalid, XNVM_EFUSE_CACHE_MISC_CTRL_PPK1_INVLD_1_0_MASK, XNVM_EFUSE_CACHE_MISC_CTRL_PPK1_INVLD_1_0_SHIFT, XNvm_EfuseMiscCtrlBits::Ppk2Invalid, XNVM_EFUSE_CACHE_MISC_CTRL_PPK2_INVLD_1_0_MASK, XNVM_EFUSE_CACHE_MISC_CTRL_PPK2_INVLD_1_0_SHIFT, XNVM_EFUSE_CACHE_MISC_CTRL_PPK3_INVLD_1_0_MASK, XNVM_EFUSE_CACHE_MISC_CTRL_PPK3_INVLD_1_0_SHIFT, XNVM_EFUSE_CACHE_MISC_CTRL_PPK4_INVLD_1_0_MASK, XNVM_EFUSE_CACHE_MISC_CTRL_PPK4_INVLD_1_0_SHIFT, XNVM_EFUSE_CACHE_MISC_CTRL_ADD_PPK_1_0_MASK, XNVM_EFUSE_CACHE_MISC_CTRL_ADD_PPK_EN_SHIFT.
int XNvm_EfuseReadSecCtrlBits(XNvm_EfuseSecCtrlBits *SecCtrlBits)
This function reads secure control bits and CRC_EN register bits from eFUSE cache.
SecCtrlBits - Pointer to XNvm_EfuseSecCtrlBits where secure control bits are read. Device-specific behavior: **SPARTANUPLUS devices:** - Supports PPK0, PPK1, and PPK2 (three PPK hashes) - PPK hash size: 256 bits (32 bytes) - Reads Ppk2lck and Ppk2Invld bits for PPK2 - PPK2 eFUSE registers are shared between PPK2 hash and PUF hash storage - The HashPufOrKey bit determines which hash type is stored: * When HashPufOrKey = 0: PPK2 registers contain PPK2 hash * When HashPufOrKey = 1: PPK2 registers contain PUF hash - When programming PUF hash: * Ppk2Invld must be 0 (PPK2 register not invalidated) * Ppk2lck must be 0 (PPK2 register not write-locked) * PPK2 registers must not be already programmed * HashPufOrKey must be set to 1 to indicate PUF hash usage **SPARTANUPLUSAES1 devices:** - Supports only PPK0 and PPK1 (two PPK hashes) - PPK hash size: 384 bits (48 bytes) - Ppk2lck and Ppk2Invld fields are not available - Reads Ppk1lck and Ppk1Invld bits for PPK1 - PPK1 eFUSE registers are shared between PPK1 hash and PUF hash storage - The HashPufOrKey bit determines which hash type is stored: * When HashPufOrKey = 0: PPK1 registers contain PPK1 hash * When HashPufOrKey = 1: PPK1 registers contain PUF hash - When programming PUF hash: * Ppk1Invld must be 0 (PPK1 register not invalidated) * Ppk1lck must be 0 (PPK1 register not write-locked) * PPK1 registers must not be already programmed * HashPufOrKey must be set to 1 to indicate PUF hash usage XST_SUCCESS - Specified data read.XNVM_EFUSE_ERR_INVALID_PARAM - Invalid parameter.XNVM_EFUSE_ERR_CACHE_PARITY - Parity Error exist in cache. This function reads secure control bits and CRC_EN register bits from eFUSE cache. SecCtrlBits - Pointer to the Xnvm_SecCtrlBits which holds the read secure control bits. XST_SUCCESS On Successful read.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_CACHE_PARITY Error while Cache reload.
References XNVM_EFUSE_ERR_INVALID_PARAM, XNvm_EfuseSecCtrlBits::ScanClearEn, XNvm_EfuseSecCtrlBits::AesDis, XNvm_EfuseSecCtrlBits::RmaDis, XNvm_EfuseSecCtrlBits::RmaEn, XNvm_EfuseSecCtrlBits::JtagDis, XNvm_EfuseSecCtrlBits::PufTes2Dis, XNvm_EfuseSecCtrlBits::HashPufOrKey, XNvm_EfuseSecCtrlBits::Ppk0lck, XNvm_EfuseSecCtrlBits::Ppk0Invld, XNvm_EfuseSecCtrlBits::Ppk1lck, XNvm_EfuseSecCtrlBits::Ppk1Invld, XNvm_EfuseSecCtrlBits::Ppk2lck, XNvm_EfuseSecCtrlBits::Ppk2Invld, XNvm_EfuseSecCtrlBits::AesRdlk, XNvm_EfuseSecCtrlBits::JtagErrDis, XNvm_EfuseSecCtrlBits::UserWrlk, XNvm_EfuseSecCtrlBits::CrcEn, XNvm_EfuseSecCtrlBits::DftDis, XNvm_EfuseSecCtrlBits::Lckdwn, XNvm_EfuseSecCtrlBits::CrcRmaDis, XNvm_EfuseSecCtrlBits::CrcRmaEn, XNVM_EFUSE_SECURITY_CONTROL_ROW, XNVM_EFUSE_CACHE_SECURITY_CONTROL_AES_DIS_MASK, XNvm_EfuseSecCtrlBits::JtagErrOutDis, XNVM_EFUSE_CACHE_SECURITY_CONTROL_JTAG_ERROUT_DIS_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_JTAG_ERROR_OUT_DIS_SHIFT, XNVM_EFUSE_CACHE_SECURITY_CONTROL_JTAG_DIS_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_JTAG_DIS_SHIFT, XNvm_EfuseSecCtrlBits::HwTstBitsDis, XNVM_EFUSE_CACHE_SECURITY_CONTROL_HWTSTBITS_DIS_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_HWTSTBITS_DIS_SHIFT, XNvm_EfuseSecCtrlBits::Ppk0WrLk, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PPK0_WR_LK_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PPK0_WR_LK_SHIFT, XNvm_EfuseSecCtrlBits::Ppk1WrLk, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PPK1_WR_LK_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PPK1_WR_LK_SHIFT, XNvm_EfuseSecCtrlBits::Ppk2WrLk, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PPK2_WR_LK_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PPK2_WR_LK_SHIFT, XNvm_EfuseSecCtrlBits::AesCrcLk, XNVM_EFUSE_CACHE_SECURITY_CONTROL_AES_CRC_LK_1_0_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_AES_CRC_LK_1_0_SHIFT, XNvm_EfuseSecCtrlBits::AesWrLk, XNVM_EFUSE_CACHE_SECURITY_CONTROL_AES_WR_LK_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_AES_WR_LK_SHIFT, XNvm_EfuseSecCtrlBits::UserKey0CrcLk, XNVM_EFUSE_CACHE_SECURITY_CONTROL_USR_KEY_0_CRC_LK_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_USR_KEY_0_CRC_LK_0_SHIFT, XNvm_EfuseSecCtrlBits::UserKey0WrLk, XNVM_EFUSE_CACHE_SECURITY_CONTROL_USR_KEY_0_WR_LK_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_USR_KEY_0_WR_LK_SHIFT, XNvm_EfuseSecCtrlBits::UserKey1CrcLk, XNVM_EFUSE_CACHE_SECURITY_CONTROL_USR_KEY_1_CRC_LK_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_USR_KEY_1_CRC_LK_0_SHIFT, XNvm_EfuseSecCtrlBits::UserKey1WrLk, XNVM_EFUSE_CACHE_SECURITY_CONTROL_USR_KEY_1_WR_LK_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_USR_KEY_1_WR_LK_SHIFT, XNvm_EfuseSecCtrlBits::SecDbgDis, XNVM_EFUSE_CACHE_SECURITY_CONTROL_SEC_DEBUG_DIS_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_SEC_DEBUG_DIS_1_0_SHIFT, XNvm_EfuseSecCtrlBits::SecLockDbgDis, XNVM_EFUSE_CACHE_SECURITY_CONTROL_SEC_LOCK_DBG_DIS_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_SEC_LOCK_DBG_DIS_1_0_SHIFT, XNvm_EfuseSecCtrlBits::PmcScEn, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PMC_SC_EN_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PMC_SC_EN_SHIFT, XNvm_EfuseSecCtrlBits::BootEnvWrLk, XNVM_EFUSE_CACHE_SECURITY_CONTROL_BOOT_ENV_WR_LK_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_BOOT_ENV_WR_LK_SHIFT, XNvm_EfuseSecCtrlBits::RegInitDis, XNVM_EFUSE_CACHE_SECURITY_CONTROL_REG_INIT_DIS_1_0_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_REG_INIT_DIS_1_0_SHIFT.
Referenced by XNvm_EfuseWrite.
int XNvm_EfuseReadPpkHash(XNvm_PpkHash *EfusePpk, XNvm_PpkType PpkType)
This function reads the Ppk Hash from eFUSE cache.
EfusePpk - Pointer to XNvm_PpkHash which holds the PpkHash from eFUSE Cache. PpkType - Type of the Ppk to be programmed. XST_SUCCESS On Successful read.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_RD_PPK_HASH Error while reading PPK Hash.
References XNVM_EFUSE_PPK_0_HASH_START_ROW, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_PPK0, XNVM_EFUSE_PPK1, XNVM_EFUSE_PPK_1_HASH_START_ROW, XNVM_EFUSE_PPK2, XNVM_EFUSE_PPK_2_HASH_START_ROW, XNVM_EFUSE_PPK_3_HASH_START_ROW, XNVM_EFUSE_PPK_4_HASH_START_ROW, XNvm_EfuseReadCacheRange, XNVM_EFUSE_PPK_HASH_NUM_OF_ROWS, XNvm_PpkHash::Hash, XNVM_EFUSE_ERR_RD_PPK_HASH.
int XNvm_EfuseReadDecOnly(u32 *DecOnly)
This function reads DEC only fuses from eFUSE cache.
DecOnly - Pointer to the DEC only efuse data. XST_SUCCESS - Specified data read.XNVM_EFUSE_ERR_INVALID_PARAM - On invalid parameter This function reads DEC only fuses from eFUSE cache. DecOnly - Pointer to the DecOnly efuse data. XST_SUCCESS On Successful read.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_RD_DEC_ONLY Error in reading in Dec_only efuses. If DecOnly eFuse is programmed that means boot can happen in only Symmetric HWRoT boot mode.
References XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_DEC_EFUSE_ONLY_ROW, XNVM_EFUSE_ERR_RD_DEC_ONLY.
int XNvm_EfuseReadDna(XNvm_Dna *EfuseDna)
This function is used to read Dna eFUSE bits from cache.
EfuseDna - Pointer to the XNvm_Dna, which holds the read DNA. XST_SUCCESS On Successful read.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid parameter.XNVM_EFUSE_ERR_RD_DNA Error in reading DNA efuses.
References XNVM_EFUSE_ERR_INVALID_PARAM, XNvm_EfuseReadCacheRange, XNVM_EFUSE_DNA_START_ROW, XNVM_EFUSE_DNA_NUM_OF_ROWS, XNvm_Dna::Dna, XNVM_EFUSE_ERR_RD_DNA.
int XNvm_EfuseReadCacheRange(u32 StartRow, u8 RowCount, u32 *RowData)
This function reads 32-bit rows from eFUSE cache.
StartRow - Starting Row number (0-based addressing). RowCount - Number of Rows to be read. RowData - Pointer to memory location where read 32-bit row data(s) is to be stored. XST_SUCCESS Specified data read.XNVM_EFUSE_ERR_INVALID_PARAM Input validation failure.XNVM_EFUSE_ERR_CACHE_PARITY Parity Error exist in cache.
Referenced by XNvm_EfuseReadPpkHash, XNvm_EfuseReadIv, XNvm_EfuseReadDna, XNvm_EfuseReadPuf, XNvm_EfuseReadUserFuses.
int XNvm_EfuseWritePuf(const XNvm_EfusePufHd *PufHelperData)
This function programs the eFUSEs with the PUF helper data.
PufHelperData - Pointer to the Puf helper data to be written to eFuse. XST_SUCCESS If programs successfully.XNVM_EFUSE_ERR_INVALID_PARAM Input validation failureXNVM_EFUSE_ERR_RD_PUF_SEC_CTRL Error while reading PufSecCtrl.XNVM_EFUSE_ERR_WRITE_PUF_HELPER_DATA Error while writing Puf helper data.XNVM_EFUSE_ERR_WRITE_PUF_SYN_DATA Error while writing Puf Syndata.XNVM_EFUSE_ERR_WRITE_PUF_CHASH Error while writing Puf Chash. XNVM_EFUSE_ERR_WRITE_PUF_AUX Error while writing Puf Aux. XNVM_EFUSE_ERR_FUSE_PROTECTED Error if Puf is protected from writeXNVM_EFUSE_ERR_BEFORE_PROGRAMMING Error before programming To generate PufSyndromeData please use XPuf_Registration API.
References XNVM_EFUSE_SEC_DEF_VAL_ALL_BIT_SET, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_SECURITY_CONTROL_ROW, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PUF_DIS_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PUF_SYN_LK_MASK, XNVM_EFUSE_ERR_FUSE_PROTECTED, XNVM_EFUSE_ERR_WRITE_PUF_HELPER_DATA, XNvm_EfusePufHd::EnvMonitorDis, XNvm_EfusePufHd::SysMonInstPtr, XNvm_EfuseTempAndVoltChecks, XNVM_EFUSE_ERR_BEFORE_PROGRAMMING, XNvm_EfuseSetupController, XNVM_EFUSE_MODE_PGM, XNVM_EFUSE_MARGIN_RD, XNvm_EfusePufHd::PrgmPufHelperData, XNvm_EfusePufHd::EfuseSynData, XNVM_EFUSE_ERR_WRITE_PUF_SYN_DATA, XNvm_EfusePufHd::Chash, XNVM_EFUSE_ERR_WRITE_PUF_CHASH, XNvm_EfusePufHd::Aux, XNVM_EFUSE_ERR_WRITE_PUF_AUX, XNvm_EfusePufHd::PrgmPufSecCtrlBits, XNvm_EfusePufHd::PufSecCtrlBits, XNvm_EfuseResetReadMode, XNvm_EfuseDisableProgramming, XNvm_EfuseLockController.
int XNvm_EfuseReadPuf(XNvm_EfusePufHd *PufHelperData)
This function reads the PUF helper data from eFUSE cache.
PufHelperData - Pointer to XNvm_EfusePufHd which holds the PUF helper data read from eFUSEs. XST_SUCCESS On successful read.XNVM_EFUSE_ERR_RD_PUF_SYN_DATA Error while reading SYN_DATA.XNVM_EFUSE_ERR_RD_PUF_CHASH Error while reading CHASH.XNVM_EFUSE_ERR_RD_PUF_AUX Error while reading AUX.
References XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_PUF_SYN_START_ROW, XNVM_NUM_OF_ROWS_PER_PAGE, XNVM_EFUSE_PAGE_2, XNvm_EfuseReadCacheRange, XNVM_EFUSE_PUF_SYN_DATA_NUM_OF_ROWS, XNvm_EfusePufHd::EfuseSynData, XNVM_EFUSE_ERR_RD_PUF_SYN_DATA, XNVM_EFUSE_PUF_CHASH_ROW, XNvm_EfusePufHd::Chash, XNVM_EFUSE_ERR_RD_PUF_CHASH, XNVM_EFUSE_PUF_AUX_ROW, XNvm_EfusePufHd::Aux, XNVM_EFUSE_ERR_RD_PUF_AUX, XNVM_EFUSE_CACHE_PUF_ECC_PUF_CTRL_ECC_23_0_MASK, XNvm_ZeroizeAndVerify, XNVM_EFUSE_ERR_IN_ZEROIZATION.
int XNvm_EfuseReadPufSecCtrlBits(XNvm_EfusePufSecCtrlBits *PufSecCtrlBits)
This function is used to read the Puf eFUSE secure control bits from cache.
PufSecCtrlBits - Pointer to the XNvm_PufSecCtrlBits, which holds the read secure control bits. XST_SUCCESS On Successful read.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_CACHE_PARITY Error while Cache reload.
References XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_PUF_AUX_ROW, XNVM_EFUSE_SECURITY_CONTROL_ROW, XNvm_EfusePufSecCtrlBits::PufRegenDis, XNVM_EFUSE_CACHE_PUF_ECC_PUF_CTRL_PUF_REGEN_DIS_SHIFT, XNvm_EfusePufSecCtrlBits::PufHdInvalid, XNVM_EFUSE_CACHE_PUF_ECC_PUF_CTRL_HD_INVLD_MASK, XNVM_EFUSE_CACHE_PUF_ECC_PUF_CTRL_PUF_HD_INVLD_SHIFT, XNvm_EfusePufSecCtrlBits::PufTest2Dis, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PUF_TEST2_DIS_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PUF_TEST2_DIS_SHIFT, XNvm_EfusePufSecCtrlBits::PufDis, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PUF_DIS_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PUF_DIS_SHIFT, XNvm_EfusePufSecCtrlBits::PufSynLk, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PUF_SYN_LK_SHIFT.
int XNvm_EfuseReadSecMisc1Bits(XNvm_EfuseSecMisc1Bits *SecMisc1Bits)
This function is used to read the security miscellaneous1 bits from cache.
SecMisc1Bits - Pointer to the XNvm_EfuseSecMisc1Bits which holds the security miscellaneous1 control bits. XST_SUCCESS On Successful read.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_CACHE_PARITY Error while Cache reload.
References XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_SECURITY_MISC_1_ROW, XNvm_EfuseSecMisc1Bits::LpdMbistEn, XNVM_EFUSE_CACHE_SEC_MISC_1_LPD_MBIST_EN_2_0_MASK, XNVM_EFUSE_CACHE_SEC_MISC_1_LPD_MBIST_EN_2_0_SHIFT, XNvm_EfuseSecMisc1Bits::PmcMbistEn, XNVM_EFUSE_CACHE_SEC_MISC_1_PMC_MBIST_EN_2_0_MASK, XNVM_EFUSE_CACHE_SEC_MISC_1_PMC_MBIST_EN_2_0_SHIFT, XNvm_EfuseSecMisc1Bits::LpdNocScEn, XNVM_EFUSE_CACHE_SEC_MISC_1_LPD_NOC_SC_EN_2_0_MASK, XNVM_EFUSE_CACHE_SEC_MISC_1_LPD_NOC_SC_EN_2_0_SHIFT, XNvm_EfuseSecMisc1Bits::SysmonVoltMonEn, XNVM_EFUSE_CACHE_SEC_MISC_1_SYSMON_VOLT_MON_EN_1_0_MASK, XNVM_EFUSE_CACHE_SEC_MISC_1_SYSMON_VOLT_MON_EN_1_0_SHIFT, XNvm_EfuseSecMisc1Bits::SysmonTempMonEn, XNVM_EFUSE_CACHE_SEC_MISC_1_SYSMON_TEMP_MON_EN_1_0_MASK, XNVM_EFUSE_CACHE_SEC_MISC_1_SYSMON_TEMP_MON_EN_1_0_SHIFT.
int XNvm_EfuseReadBootEnvCtrlBits(XNvm_EfuseBootEnvCtrlBits *BootEnvCtrlBits)
This function reads the Boot Environmental Control bits from cache.
BootEnvCtrlBits - Pointer to the XNvm_EfuseBootEnvCtrlBits which holds the Boot Environmental control bits. XST_SUCCESS On Successful read.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_CACHE_PARITY Error while Cache reload.
References XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_BOOT_ENV_CTRL_ROW, XNvm_EfuseBootEnvCtrlBits::SysmonTempEn, XNVM_EFUSE_CACHE_BOOT_ENV_CTRL_SYSMON_TEMP_EN_MASK, XNVM_EFUSE_CACHE_BOOT_ENV_CTRL_SYSMON_TEMP_EN_SHIFT, XNvm_EfuseBootEnvCtrlBits::SysmonVoltEn, XNVM_EFUSE_CACHE_BOOT_ENV_CTRL_SYSMON_VOLT_EN_MASK, XNVM_EFUSE_CACHE_BOOT_ENV_CTRL_SYSMON_VOLT_EN_SHIFT, XNvm_EfuseBootEnvCtrlBits::SysmonTempHot, XNVM_EFUSE_CACHE_BOOT_ENV_CTRL_SYSMON_TEMP_HOT_MASK, XNVM_EFUSE_CACHE_BOOT_ENV_CTRL_SYSMON_TEMP_HOT_SHIFT, XNvm_EfuseBootEnvCtrlBits::SysmonVoltPmc, XNVM_EFUSE_CACHE_BOOT_ENV_CTRL_SYSMON_VOLT_PMC_MASK, XNVM_EFUSE_CACHE_BOOT_ENV_CTRL_SYSMON_VOLT_PMC_SHIFT, XNvm_EfuseBootEnvCtrlBits::SysmonVoltPslp, XNVM_EFUSE_CACHE_BOOT_ENV_CTRL_SYSMON_VOLT_PSLP_MASK, XNVM_EFUSE_CACHE_BOOT_ENV_CTRL_SYSMON_VOLT_PSLP_SHIFT, XNvm_EfuseBootEnvCtrlBits::SysmonVoltSoc, XNVM_EFUSE_CACHE_BOOT_ENV_CTRL_SYSMON_VOLT_SOC_MASK, XNVM_EFUSE_CACHE_BOOT_ENV_CTRL_SYSMON_VOLT_SOC_SHIFT, XNvm_EfuseBootEnvCtrlBits::SysmonTempCold, XNVM_EFUSE_CACHE_BOOT_ENV_CTRL_SYSMON_TEMP_COLD_MASK, XNVM_EFUSE_CACHE_BOOT_ENV_CTRL_SYSMON_TEMP_COLD_SHIFT.
int XNvm_EfuseReadOffchipRevokeId(u32 *OffchipIdPtr, XNvm_OffchipId OffchipIdNum)
This function reads the Offchip revoke eFuse value from eFUSE cache.
OffchipIdPtr - Pointer to the data which hold the Offchip revoke ID values. OffchipIdNum - Offchip fuse number to read. XST_SUCCESS On successful read.XNVM_EFUSE_ERR_INVALID_PARAM On Invalid Parameter.XNVM_EFUSE_ERR_CACHE_PARITY Error in Cache reload.
References XNVM_EFUSE_OFFCHIP_REVOKE_ID_0, XNVM_EFUSE_OFFCHIP_REVOKE_ID_7, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_OFFCHIP_REVOKE_0_ROW.