xnvm_efuse_common.h
XNVM_EFUSE_CTRL_WR_LOCKED
eFuse control write locked
Referenced by XNvm_EfuseCheckAesKeyCrc, XNvm_EfuseLockController.
XNVM_EFUSE_CTRL_WR_UNLOCKED
eFuse control write unlocked
Referenced by XNvm_EfuseUnlockController.
XNVM_EFUSE_FULL_RANGE_TEMP_MIN
Minimum temperature for full range check.
XNVM_EFUSE_FULL_RANGE_TEMP_MAX
Maximum temperature for full range check.
XNVM_EFUSE_TEMP_LP_MIN
Minimum temperature for low power range check.
XNVM_EFUSE_TEMP_LP_MAX
Maximum temperature for low power range check.
XNVM_EFUSE_TEMP_MP_MIN
Minimum temperature for medium power range check.
XNVM_EFUSE_TEMP_MP_MAX
Maximum temperature for medium power range check.
XNVM_EFUSE_TEMP_HP_MIN
Minimum temperature for high power range check.
XNVM_EFUSE_TEMP_HP_MAX
Maximum temperature for high power range check.
XNVM_EFUSE_FULL_RANGE_CHECK
To check both voltage and temperature in full range.
XNVM_EFUSE_LP_RANGE_CHECK
To check both voltage and temperature in low power range.
XNVM_EFUSE_MP_RANGE_CHECK
To check both voltage and temperature in medium power range.
XNVM_EFUSE_HP_RANGE_CHECK
To check both voltage and temperature in high power range.
XNVM_EFUSE_VCC_PMC_LP_MIN
Minimum voltage for low power range check.
XNVM_EFUSE_VCC_PMC_LP_MAX
Maximum voltage for low power range check.
XNVM_EFUSE_VCC_PMC_MP_MIN
Minimum voltage for medium power range check.
XNVM_EFUSE_VCC_PMC_MP_MAX
Maximum voltage for medium power range check.
XNVM_EFUSE_VCC_PMC_HP_MIN
Minimum voltage for high power range check.
XNVM_EFUSE_VCC_PMC_HP_MAX
Maximum voltage for high power range check.
XNVM_EFUSE_SYSMON_LOCK_CODE
System monitor lock code for eFUSE operations.
Referenced by XNvm_EfuseTempAndVoltChecks.
XNVM_EFUSE_PROTECTION_BIT_CLEAR
To check the corresponding protection eFuse is set or not.
Referenced by XNvm_EfuseReadProtectionBits.
XNvm_EfuseOpMode
eFuse read mode
XNvm_EfuseRdMode
eFuse normal read
XNvm_EfuseType
Efuse page 0.
int XNvm_EfuseCacheReload(void)
This function reloads the eFUSE cache, so that eFUSE values can be directly read from cache.
XST_SUCCESS On successful cache reload.XNVM_EFUSE_ERR_CACHE_LOAD Error while loading the cache. Not recommended to call this API frequently,if this API is called all the cache memory is reloaded by reading eFUSE array, reading eFUSE bit multiple times may diminish the life time.
References XNVM_EFUSE_CACHE_LOAD_MASK, XNVM_EFUSE_CACHE_LOAD_REG_OFFSET, XNVM_EFUSE_CACHE_LOAD_TIMEOUT_VAL, XNVM_EFUSE_CTRL_BASEADDR, XNVM_EFUSE_ERR_CACHE_LOAD, XNVM_EFUSE_ISR_CACHE_ERROR, XNVM_EFUSE_ISR_REG_OFFSET, XNVM_EFUSE_STATUS_CACHE_DONE, XNVM_EFUSE_STATUS_REG_OFFSET, XNvm_EfuseReadReg, XNvm_EfuseWriteReg.
Referenced by XNvm_EfuseWrite.
void XNvm_EfuseDisablePowerDown(void)
This function disables power down of eFUSE macros.
References XNVM_EFUSE_CTRL_BASEADDR, XNVM_EFUSE_PD_ENABLE, XNVM_EFUSE_PD_REG_OFFSET, XNvm_EfuseReadReg, XNvm_EfuseWriteReg, XNVM_ONE_MICRO_SECOND.
Referenced by XNvm_EfuseSetupController.
int XNvm_EfuseSetReadMode(XNvm_EfuseRdMode RdMode)
This function sets read mode of eFUSE controller.
RdMode - Mode to be used for eFUSE read. XST_SUCCESS If Setting read mode is successful.XST_FAILURE If there is a failure
References XNVM_EFUSE_CFG_MARGIN_RD, XNVM_EFUSE_CFG_NORMAL_RD, XNVM_EFUSE_CFG_REG_OFFSET, XNVM_EFUSE_CTRL_BASEADDR, XNVM_EFUSE_CTRL_CFG_MARGIN_RD_MASK, XNVM_EFUSE_NORMAL_RD, XNVM_EFUSE_SEC_DEF_VAL_ALL_BIT_SET, XNVM_EFUSE_SEC_DEF_VAL_BYTE_SET, XNvm_EfuseReadReg.
Referenced by XNvm_EfuseSetupController.
void XNvm_EfuseSetRefClk(void)
This function sets reference clock of eFUSE controller.
References XNVM_CRP_BASE_ADDR, XNVM_CRP_EFUSE_REF_CLK_REG_OFFSET, XNVM_CRP_EFUSE_REF_CLK_SELSRC, XNvm_EfuseWriteReg.
Referenced by XNvm_EfuseSetupController.
void XNvm_EfuseEnableProgramming(void)
This function enables programming mode of eFUSE controller.
References XNVM_EFUSE_CFG_ENABLE_PGM, XNVM_EFUSE_CFG_REG_OFFSET, XNVM_EFUSE_CTRL_BASEADDR, XNvm_EfuseReadReg, XNvm_EfuseWriteReg.
Referenced by XNvm_EfuseSetupController.
int XNvm_EfuseDisableProgramming(void)
This function disables programming mode of eFUSE controller.
XST_SUCCESS - if eFUSE programming is disabled successfully.XST_FAILURE - if there is a failure XST_SUCCESS If eFUSE programming is disabled successfully.XST_FAILURE If there is a failure
References XNVM_EFUSE_CFG_ENABLE_PGM, XNVM_EFUSE_CFG_REG_OFFSET, XNVM_EFUSE_CTRL_BASEADDR, XNvm_EfuseReadReg.
Referenced by XNvm_EfuseWrite, XNvm_EfuseWritePuf.
int XNvm_EfuseResetReadMode(void)
This function disables Margin Read mode of eFUSE controller.
XST_SUCCESS - if resetting read mode is successful.XST_FAILURE - if there is a failure XST_SUCCESS If resetting read mode is successful.XST_FAILURE If there is a failure
References XNVM_EFUSE_CFG_MARGIN_RD, XNVM_EFUSE_CFG_REG_OFFSET, XNVM_EFUSE_CTRL_BASEADDR, XNvm_EfuseReadReg.
Referenced by XNvm_EfuseWrite, XNvm_EfuseWritePuf.
void XNvm_EfuseInitTimers(void)
This function initializes eFUSE controller timers.
References XNVM_EFUSE_CTRL_BASEADDR, XNVM_EFUSE_TPGM_DIV, XNVM_EFUSE_TPGM_REG_OFFSET, XNVM_EFUSE_TRD_DIV, XNVM_EFUSE_TRD_REG_OFFSET, XNVM_EFUSE_TRDM_REG_OFFSET, XNVM_EFUSE_TRMD_DIV, XNVM_EFUSE_TSU_H_CS_DIV, XNVM_EFUSE_TSU_H_CS_REG_OFFSET, XNVM_EFUSE_TSU_H_PS_CS_DIV, XNVM_EFUSE_TSU_H_PS_CS_REG_OFFSET, XNVM_EFUSE_TSU_H_PS_DIV, XNVM_EFUSE_TSU_H_PS_REG_OFFSET, XNvm_EfuseWriteReg, XNVM_PSU_PSS_REF_CLK_FREQ.
Referenced by XNvm_EfuseSetupController.
int XNvm_EfuseSetupController(XNvm_EfuseOpMode Op, XNvm_EfuseRdMode RdMode)
This function setups eFUSE controller for given operation and read mode.
Op - Operation to be performed read/program(write). RdMode - Read mode for eFUSE read operation. XST_SUCCESS eFUSE controller setup for given op.XNVM_EFUSE_ERR_UNLOCK Failed to unlock eFUSE controller register access.XST_FAILURE If eFUSE controller is not unlockedXNVM_EFUSE_ERR_PGM_TBIT_PATTERN If TBITS pattern is not matched with the expected value.
References XNVM_EFUSE_CTRL_BASEADDR, XNVM_EFUSE_MODE_PGM, XNVM_EFUSE_TEST_CTRL_REG_OFFSET, XNvm_EfuseCheckForTBits, XNvm_EfuseDisablePowerDown, XNvm_EfuseEnableProgramming, XNvm_EfuseInitTimers, XNvm_EfuseSetReadMode, XNvm_EfuseSetRefClk, XNvm_EfuseUnlockController, XNvm_EfuseWriteReg.
int XNvm_EfuseCheckForTBits(void)
This function checks whether Tbits are programmed or not.
XST_SUCCESS On Success.XNVM_EFUSE_ERR_PGM_TBIT_PATTERN Error in T-Bit pattern.
References XNVM_EFUSE_CTRL_BASEADDR, XNVM_EFUSE_ERR_PGM_TBIT_PATTERN, XNVM_EFUSE_STATUS_REG_OFFSET, XNVM_EFUSE_STATUS_TBIT_0, XNVM_EFUSE_STATUS_TBIT_1, XNVM_EFUSE_STATUS_TBIT_2, XNvm_EfuseReadReg.
Referenced by XNvm_EfuseSetupController.
u32 XNvm_GetSysmonSupplyRegId(UINTPTR SysmonpsvSatBaseAddr)
This function reads root register ID where measurement is stored in Root SysMon.
SysmonpsvSatBaseAddr - Pointer to SysMon base address SupplyReg Id - On successful match foundXNVM_EFUSE_SEC_DEF_VAL_ALL_BIT_SET - When no matching supply found
References XNVM_EFUSE_SEC_DEF_VAL_ALL_BIT_SET, XNVM_EFUSE_SYSMON_NUM_MEASURE_REGS, XNVM_EFUSE_SYSMON_SAT_ADDR_ID_MASK, XNVM_EFUSE_SYSMON_SAT_ADDR_ID_SHIFT, XNVM_EFUSE_SYSMON_SAT_CONFIG_ABUS_SW0_MASK, XNVM_EFUSE_SYSMON_SAT_CONFIG_ABUS_SW0_SHIFT, XNVM_EFUSE_SYSMON_SAT_CONFIG_ABUS_SW1_MASK, XNVM_EFUSE_SYSMON_SAT_CONFIG_ABUS_SW1_SHIFT, XNVM_EFUSE_SYSMON_SAT_CONFIG_AMUX_CTRL_MASK, XNVM_EFUSE_SYSMON_SAT_CONFIG_AMUX_CTRL_SHIFT, XNVM_EFUSE_SYSMON_SAT_CONFIG_MODE_MASK, XNVM_EFUSE_SYSMON_SAT_CONFIG_MODE_SHIFT, XNVM_EFUSE_SYSMON_VCCPMC_ABUS_SW0, XNVM_EFUSE_SYSMON_VCCPMC_ABUS_SW1, XNVM_EFUSE_SYSMON_VCCPMC_AMUX_CTRL, XNVM_EFUSE_SYSMON_VCCPMC_MODE, XNVM_EFUSE_SYSMONPSV_SAT_MEASURE0_OFFSET, XNVM_EFUSE_WORD_LEN.
Referenced by XNvm_EfuseTempAndVoltChecks.
int XNvm_EfuseTempAndVoltChecks(const XSysMonPsv *SysMonInstPtr)
This function performs the Temperature and Voltage checks to ensure that they are in limits before eFuse programming.
SysMonInstPtr - Pointer to SysMon instance. XST_SUCCESS - On successful Voltage and Temperature checks.XNVM_EFUSE_ERR_INVALID_PARAM - Input validation failure.XNVM_EFUSE_ERROR_READ_VOLTAGE_OUT_OF_RANGE - Voltage is out of rangeXNVM_EFUSE_ERROR_READ_TEMPERATURE_OUT_OF_RANGE - Temperature is out of range
References XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_ERROR_NO_SUPPLIES_ENABLED, XNVM_EFUSE_ERROR_READ_TMEPERATURE_OUT_OF_RANGE, XNVM_EFUSE_ERROR_READ_VOLTAGE_OUT_OF_RANGE, XNVM_EFUSE_ERROR_SYSMON_NO_NEW_DATA, XNVM_EFUSE_FRACTION_MUL_VALUE, XNVM_EFUSE_SEC_DEF_VAL_ALL_BIT_SET, XNVM_EFUSE_SYSMON_LOCK_CODE, XNVM_EFUSE_SYSMON_NUM_SUPPLIES_PER_FLAG, XNVM_EFUSE_SYSMONPSV_SAT0_BASEADDR, XNVM_EFUSE_SYSMONPSV_SAT1_BASEADDR, XNVM_EFUSE_SYSMONPSV_TIMEOUT, XNVM_EFUSE_WORD_LEN, XNvm_GetSysmonSupplyRegId.
Referenced by XNvm_EfuseWrite, XNvm_EfuseWriteAesKey, XNvm_EfuseWriteBootEnvCtrlBits, XNvm_EfuseWriteBootModeDisable, XNvm_EfuseWriteCrc, XNvm_EfuseWriteDecOnly, XNvm_EfuseWriteDisableInplacePlmUpdate, XNvm_EfuseWriteDmeMode, XNvm_EfuseWriteDmeRevoke, XNvm_EfuseWriteDmeUserKey, XNvm_EfuseWriteFipsInfo, XNvm_EfuseWriteGlitchConfigBits, XNvm_EfuseWriteIv, XNvm_EfuseWriteMisc1Bits, XNvm_EfuseWriteMiscCtrlBits, XNvm_EfuseWriteOffChipRevokeID, XNvm_EfuseWritePpkHash, XNvm_EfuseWritePuf, XNvm_EfuseWritePufSecCtrl, XNvm_EfuseWriteRevocationID, XNvm_EfuseWriteRomRsvdBits, XNvm_EfuseWriteSecCtrlBits, XNvm_EfuseWriteUds.
u32 XNvm_EfuseReadProtectionBits(u32 Mask)
This function reads the corresponding eFuse protection bits.
Mask Efuse Protection bit mask value. Return protection bits value as specified by Mask
References XNVM_EFUSE_CACHE_BASEADDR, XNVM_EFUSE_PROTECTION_BIT_CLEAR, XNVM_EFUSE_TBITS_XILINX_CTRL_ROW, XNvm_EfuseReadReg.