xnvm_validate.c
XNVM_EFUSE_CACHE_DME_FIPS_DME_MODE_MASK
DME mode mask.
Referenced by XNvm_IsDmeModeEn.
static int XNvm_EfuseValidateIV(const u32 *Iv, u32 IvOffset)
This function validates IV requested for programming bit by bit with cache IV to check if the request is to revert the already programmed eFuse.
Iv - Pointer to Iv data to be programmed. IvOffset - Offset of the Iv to be vaildated. XST_SUCCESS - if validation is successful.XNVM_EFUSE_ERR_INVALID_PARAM - On Invalid Parameter.XNVM_EFUSE_ERR_BIT_CANT_REVERT - if requested to revert the already programmed bit.
int XNvm_EfuseValidateAesKeyWriteReq(XNvm_AesKeyType KeyType)
This function validates AES key/User Key 0/User key 1 requested for programming into eFUSEs.
KeyType - Type of AES key requested to be validated. Possible options are AES key, User0 key and User1 key. XST_SUCCESS - if validation is successful.XNVM_EFUSE_ERR_AES_ALREADY_PRGMD - Aes key already programmed.XNVM_EFUSE_ERR_USER_KEY0_ALREADY_PRGMD - User key 0 is already programmed.XNVM_EFUSE_ERR_USER_KEY1_ALREADY_PRGMD - User key 1 is already programmed.XNVM_EFUSE_ERR_FUSE_PROTECTED - eFuse is write protected.XNVM_EFUSE_ERR_WRITE_AES_KEY - Error in writing Aes key.XNVM_EFUSE_ERR_WRITE_USER0_KEY - Error in writing User key 0.XNVM_EFUSE_ERR_WRITE_USER1_KEY - Error in writing User key 1.
References XNvm_EfuseReadReg, XNVM_EFUSE_CACHE_BASEADDR, XNVM_EFUSE_CACHE_SECURITY_CONTROL_OFFSET, XNVM_EFUSE_CACHE_SECURITY_CONTROL_AES_DIS_MASK, XNVM_EFUSE_ERR_WRITE_AES_KEY, XNVM_EFUSE_ERR_AES_DISABLED, XNVM_EFUSE_AES_KEY, XNVM_EFUSE_AES_CRC_REG_OFFSET, XNVM_EFUSE_CTRL_STATUS_AES_CRC_DONE_MASK, XNVM_EFUSE_CTRL_STATUS_AES_CRC_PASS_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_AES_WR_LK_MASK, XNVM_EFUSE_USER_KEY_0, XNVM_EFUSE_AES_USR_KEY0_CRC_REG_OFFSET, XNVM_EFUSE_CTRL_STATUS_AES_USER_KEY_0_CRC_DONE_MASK, XNVM_EFUSE_CTRL_STATUS_AES_USER_KEY_0_CRC_PASS_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_USR_KEY_0_WR_LK_MASK, XNVM_EFUSE_USER_KEY_1, XNVM_EFUSE_AES_USR_KEY1_CRC_REG_OFFSET, XNVM_EFUSE_CTRL_STATUS_AES_USER_KEY_1_CRC_DONE_MASK, XNVM_EFUSE_CTRL_STATUS_AES_USER_KEY_1_CRC_PASS_MASK, XNVM_EFUSE_CACHE_SECURITY_CONTROL_USR_KEY_1_WR_LK_MASK, XNVM_EFUSE_ERR_FUSE_PROTECTED, XNVM_EFUSE_ERROR_BYTE_SHIFT, XNvm_EfuseCheckAesKeyCrc, XNVM_EFUSE_CRC_AES_ZEROS, XNVM_EFUSE_ERR_AES_ALREADY_PRGMD, XNVM_EFUSE_ERROR_NIBBLE_SHIFT.
Referenced by XNvm_EfuseWriteAesKey.
int XNvm_EfuseValidatePpkHashWriteReq(XNvm_PpkType PpkType)
This function validates PPK Hash requested for programming.
PpkType - PpkHash0/PpkHash1/PpkHash2 type of PpkHash request to be validated XST_SUCCESS - if validates successfully.XNVM_EFUSE_ERR_PPK0_HASH_ALREADY_PRGMD - Ppk0 hash already programmed.XNVM_EFUSE_ERR_PPK1_HASH_ALREADY_PRGMD - Ppk1 hash already programmed.XNVM_EFUSE_ERR_PPK2_HASH_ALREADY_PRGMD - Ppk2 hash already programmed.XNVM_EFUSE_ERR_FUSE_PROTECTED - eFuse is write protected.XNVM_EFUSE_ERR_WRITE_PPK0_HASH - Error in writing ppk0 hash.XNVM_EFUSE_ERR_WRITE_PPK1_HASH - Error in writing ppk1 hash.XNVM_EFUSE_ERR_WRITE_PPK2_HASH - Error in writing ppk2 hash.
References XNvm_EfuseReadReg, XNVM_EFUSE_CACHE_BASEADDR, XNVM_EFUSE_CACHE_SECURITY_CONTROL_OFFSET, XNVM_EFUSE_PPK0, XNVM_EFUSE_CACHE_PPK0_HASH_0_OFFSET, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PPK0_WR_LK_MASK, XNVM_EFUSE_PPK1, XNVM_EFUSE_CACHE_PPK1_HASH_0_OFFSET, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PPK1_WR_LK_MASK, XNVM_EFUSE_PPK2, XNVM_EFUSE_CACHE_PPK2_HASH_0_OFFSET, XNVM_EFUSE_CACHE_SECURITY_CONTROL_PPK2_WR_LK_MASK, XNVM_EFUSE_ERR_INVALID_PARAM, XNvm_EfuseCheckZeros, XNVM_EFUSE_PPK_HASH_NUM_OF_CACHE_ROWS, XNVM_EFUSE_ERR_PPK0_HASH_ALREADY_PRGMD, XNVM_EFUSE_ERROR_NIBBLE_SHIFT, XNVM_EFUSE_ERR_FUSE_PROTECTED, XNVM_EFUSE_ERR_WRITE_PPK0_HASH, XNVM_EFUSE_ERROR_BYTE_SHIFT.
Referenced by XNvm_EfuseWritePpkHash.
int XNvm_EfuseValidateIvWriteReq(XNvm_IvType IvType, XNvm_Iv *EfuseIv)
This function validates all IVs requested for programming.
IvType - IvType to be validated EfuseIv - Pointer to XNvm_EfuseIvs structure which holds IV data to be programmed to eFuse. XST_SUCCESS - if validation is successful.XNVM_EFUSE_ERR_WRITE_META_HEADER_IV_RANGE - Error in Metaheader IV range write request.XNVM_EFUSE_ERR_BLK_OBFUS_IV_ALREADY_PRGMD - Error in Blk Obfus Iv write request.XNVM_EFUSE_ERR_WRITE_PLM_IV_RANGE - Error in Plm Iv range write request.XNVM_EFUSE_ERR_WRITE_DATA_PARTITION_IV_RANGE - Error in Data Partition Iv range write request.
References XNVM_EFUSE_BLACK_IV, XNvm_EfuseCheckZeros, XNVM_EFUSE_CACHE_BLACK_IV_0_OFFSET, XNVM_EFUSE_IV_NUM_OF_CACHE_ROWS, XNVM_EFUSE_ERR_BLK_OBFUS_IV_ALREADY_PRGMD, XNVM_EFUSE_META_HEADER_IV_RANGE, XNVM_EFUSE_CACHE_METAHEADER_IV_RANGE_0_OFFSET, XNVM_EFUSE_PLM_IV_RANGE, XNVM_EFUSE_CACHE_PLM_IV_RANGE_0_OFFSET, XNVM_EFUSE_DATA_PARTITION_IV_RANGE, XNVM_EFUSE_CACHE_DATA_PARTITION_IV_RANGE_0_OFFSET, XNVM_EFUSE_ERR_INVALID_PARAM, XNvm_Iv::Iv, XNVM_EFUSE_ERR_WRITE_META_HEADER_IV_RANGE, XNVM_EFUSE_ERROR_BYTE_SHIFT.
Referenced by XNvm_EfuseWriteIv.
int XNvm_EfuseCheckZeros(u32 CacheOffset, u32 Count)
This function is used verify eFuse for Zeros.
CacheOffset - Cache Offset from which verification has to be started. Count - Number of rows till which verification has to be ended. XST_SUCCESS - if eFuses are not programmed.XST_FAILURE - if eFuses are already programmed.
References XNvm_EfuseCheckZeros, XNVM_WORD_LEN, XNvm_EfuseReadReg, XNVM_EFUSE_CTRL_BASEADDR, XNVM_EFUSE_ISR_REG_OFFSET, XNVM_EFUSE_ISR_CACHE_ERROR, XNVM_EFUSE_ERR_CACHE_PARITY, XNVM_EFUSE_CACHE_BASEADDR.
Referenced by XNvm_EfuseValidatePpkHashWriteReq, XNvm_EfuseValidateIvWriteReq, XNvm_EfuseCheckZeros, XNvm_EfuseIsPufHelperDataEmpty.
int XNvm_EfuseIsPufHelperDataEmpty(void)
This function checks whether PUF is already programmed or not.
XST_SUCCESS - if all rows are zero.XNVM_EFUSE_ERR_PUF_SYN_ALREADY_PRGMD - Puf Syn data already programmed.XNVM_EFUSE_ERR_PUF_CHASH_ALREADY_PRGMD - Puf chash already programmed.XNVM_EFUSE_ERR_PUF_AUX_ALREADY_PRGMD - Puf Aux is already programmed.
References XNvm_EfuseIsPufHelperDataEmpty, XNvm_EfuseCheckZeros, XNVM_EFUSE_CACHE_PUF_CHASH_OFFSET, XNVM_EFUSE_PUF_CHASH_NUM_OF_ROWS, XNVM_EFUSE_ERR_PUF_CHASH_ALREADY_PRGMD, XNvm_EfuseReadReg, XNVM_EFUSE_CACHE_BASEADDR, XNVM_EFUSE_CACHE_PUF_ECC_PUF_CTRL_OFFSET, XNVM_EFUSE_CACHE_PUF_ECC_PUF_CTRL_ECC_23_0_MASK, XNVM_EFUSE_ERR_PUF_AUX_ALREADY_PRGMD, XNVM_EFUSE_CACHE_PUF_SYN_DATA_OFFSET, XNVM_EFUSE_PUF_SYN_DATA_NUM_OF_ROWS, XNVM_EFUSE_ERR_PUF_SYN_ALREADY_PRGMD.
Referenced by XNvm_EfuseWritePuf, XNvm_EfuseIsPufHelperDataEmpty, XNvm_EfuseValidateDecOnlyRequest.
int XNvm_EfuseValidateDecOnlyRequest(void)
This function validates DEC_ONLY eFuse programming request.
XST_SUCCESS - if validation is successful.XNVM_EFUSE_ERR_INVALID_PARAM - On Invalid Parameter. XNVM_EFUSE_ERR_DEC_ONLY_KEY_MUST_BE_PRGMD- Aes key should be programmed for DEC_ONLY eFuse programming.XNVM_EFUSE_ERR_DEC_ONLY_PUF_HD_MUST_BE_PRGMD - Puf helper should be programmed for DEC_ONLY eFuse programming.
References XNvm_EfuseReadReg, XNVM_EFUSE_CACHE_BASEADDR, XNVM_EFUSE_CACHE_SECURITY_MISC_0_OFFSET, XNVM_EFUSE_CACHE_DEC_EFUSE_ONLY_MASK, XNvm_EfuseCheckAesKeyCrc, XNVM_EFUSE_AES_CRC_REG_OFFSET, XNVM_EFUSE_CTRL_STATUS_AES_CRC_DONE_MASK, XNVM_EFUSE_CTRL_STATUS_AES_CRC_PASS_MASK, XNVM_EFUSE_CRC_AES_ZEROS, XNVM_EFUSE_ERR_DEC_ONLY_KEY_MUST_BE_PRGMD, XNvm_EfuseIsPufHelperDataEmpty, XNVM_EFUSE_ERR_DEC_ONLY_PUF_HD_MUST_BE_PRGMD, XNVM_EFUSE_ERR_DEC_ONLY_ALREADY_PRGMD.
Referenced by XNvm_EfuseWriteDecOnly.
int XNvm_EfuseValidateFipsInfo(u32 FipsMode, u32 FipsVersion)
This function is used to validate FIPS mode and FIPS version inputs before programming.
FipsMode - Fips mode to be written to eFuses. FipsVersion - Fips version to be written to eFuses. XST_SUCCESS - On successful validation.XNVM_EFUSE_ERR_BEFORE_PROGRAMMING | XNVM_EFUSE_ERR_BIT_CANT_REVERT - On attempt to revert already programmed bits.
References XNvm_EfuseReadReg, XNVM_EFUSE_CACHE_BASEADDR, XNVM_EFUSE_CACHE_IP_DISABLE_OFFSET, XNVM_EFUSE_FIPS_VERSION_0_MASK, XNVM_EFUSE_FIPS_VERSION_2_1_MASK, XNVM_EFUSE_CACHE_IP_DISABLE_0_FIPS_VERSION_0_SHIFT, XNVM_EFUSE_CACHE_IP_DISABLE_0_FIPS_VERSION_2_1_SHIFT, XNVM_EFUSE_ERR_BEFORE_PROGRAMMING, XNVM_EFUSE_ERR_BIT_CANT_REVERT, XNVM_EFUSE_CACHE_DME_FIPS_OFFSET, XNVM_EFUSE_CACHE_DME_FIPS_FIPS_MODE_MASK, XNVM_EFUSE_CACHE_DME_FIPS_FIPS_MODE_SHIFT.
Referenced by XNvm_EfuseWriteFipsInfo.
int XNvm_IsDmeModeEn(void)
This function checks DME Mode is enabled or disabled.
XST_SUCCESS - if DME Mode is not set.XNVM_EFUSE_ERROR_DME_MODE_SET | XNVM_EFUSE_ERR_BEFORE_PROGRAMMING if DME Mode is set.
References XNvm_EfuseReadReg, XNVM_EFUSE_CACHE_BASEADDR, XNVM_EFUSE_CACHE_DME_FIPS_OFFSET, XNVM_EFUSE_CACHE_DME_FIPS_DME_MODE_MASK, XNVM_EFUSE_ERROR_DME_MODE_SET, XNVM_EFUSE_ERR_BEFORE_PROGRAMMING.
Referenced by XNvm_EfuseWriteDmeUserKey, XNvm_EfuseReadUserFuses.