xnvm_efuse_common.c
XNVM_ONE_MICRO_SECOND
One Micro Second Timeout.
Referenced by XNvm_EfuseDisablePowerDown.
XNVM_EFUSE_TPGM_DIV
TPGM Divisor value.
Referenced by XNvm_EfuseInitTimers.
XNVM_EFUSE_TRD_DIV
TRD Divisor value.
Referenced by XNvm_EfuseInitTimers.
XNVM_EFUSE_TRMD_DIV
TRMD Divisor value.
Referenced by XNvm_EfuseInitTimers.
XNVM_EFUSE_TSU_H_PS_DIV
TSU_H_PS Divisor value.
Referenced by XNvm_EfuseInitTimers.
XNVM_EFUSE_TSU_H_PS_CS_DIV
TSU_H_PS_CS Divisor value.
Referenced by XNvm_EfuseInitTimers.
XNVM_EFUSE_TSU_H_CS_DIV
TSU_H_CS Divisor value.
Referenced by XNvm_EfuseInitTimers.
XNVM_EFUSE_SEC_DEF_VAL_ALL_BIT_SET
Default secure value for 32 bit.
Referenced by XNvm_EfuseSetReadMode, XNvm_EfuseTempAndVoltChecks, XNvm_GetSysmonSupplyRegId.
XNVM_EFUSE_SEC_DEF_VAL_BYTE_SET
Default secure value for 8 bit.
Referenced by XNvm_EfuseSetReadMode.
XNVM_EFUSE_SYSMON_VCCPMC_AMUX_CTRL
Sysmon VCCPMC Amux ctrl value.
Referenced by XNvm_GetSysmonSupplyRegId.
XNVM_EFUSE_SYSMON_VCCPMC_ABUS_SW1
Sysmon VCCPMC Abus sw1 value.
Referenced by XNvm_GetSysmonSupplyRegId.
XNVM_EFUSE_SYSMON_VCCPMC_ABUS_SW0
Sysmon VCCPMC Abus sw0 value.
Referenced by XNvm_GetSysmonSupplyRegId.
XNVM_EFUSE_SYSMON_VCCPMC_MODE
Sysmon VCCPMC mode value.
Referenced by XNvm_GetSysmonSupplyRegId.
XNVM_EFUSE_SYSMON_NUM_MEASURE_REGS
Sysmon number of measurement registers.
Referenced by XNvm_GetSysmonSupplyRegId.
XNVM_EFUSE_SYSMON_NUM_SUPPLIES_PER_FLAG
Sysmon number of supplies per flag.
Referenced by XNvm_EfuseTempAndVoltChecks.
XNVM_EFUSE_SYSMONPSV_TIMEOUT
Sysmon Psv timeout value.
Referenced by XNvm_EfuseTempAndVoltChecks.
XNVM_EFUSE_FRACTION_MUL_VALUE
Fraction multiplier value.
Referenced by XNvm_EfuseTempAndVoltChecks.
XNVM_EFUSE_WORD_LEN
eFuse word length
Referenced by XNvm_EfuseTempAndVoltChecks, XNvm_GetSysmonSupplyRegId.
static int XNvm_EfusePmcVoltageCheck(float Voltage)
This function checks VCC_PMC voltage checks for LP,MP and HP devices based on the Efuse value.
XST_SUCCESS On VCC_PMC within thresholds.XST_FAILURE On VCC_PMC not within thresholds.
static int XNvm_EfuseTemparatureCheck(float Temparature)
This function checks device Temperature for LP,MP and HP devices based on the Efuse value.
XST_SUCCESS On Temperature within thresholds.XST_FAILURE On Temperature not within thresholds.
int XNvm_EfuseCacheReload(void)
This function reloads the eFUSE cache, so that eFUSE values can be directly read from cache.
XST_SUCCESS On successful cache reload.XNVM_EFUSE_ERR_CACHE_LOAD Error while loading the cache. Not recommended to call this API frequently,if this API is called all the cache memory is reloaded by reading eFUSE array, reading eFUSE bit multiple times may diminish the life time.
References XNvm_EfuseWriteReg, XNVM_EFUSE_CTRL_BASEADDR, XNVM_EFUSE_CACHE_LOAD_REG_OFFSET, XNVM_EFUSE_CACHE_LOAD_MASK, XNVM_EFUSE_STATUS_REG_OFFSET, XNVM_EFUSE_STATUS_CACHE_DONE, XNVM_EFUSE_CACHE_LOAD_TIMEOUT_VAL, XNVM_EFUSE_ERR_CACHE_LOAD, XNvm_EfuseReadReg, XNVM_EFUSE_ISR_REG_OFFSET, XNVM_EFUSE_ISR_CACHE_ERROR.
Referenced by XNvm_EfuseWrite.
void XNvm_EfuseDisablePowerDown(void)
This function disables power down of eFUSE macros.
References XNVM_EFUSE_PD_ENABLE, XNvm_EfuseReadReg, XNVM_EFUSE_CTRL_BASEADDR, XNVM_EFUSE_PD_REG_OFFSET, XNVM_ONE_MICRO_SECOND, XNvm_EfuseWriteReg.
Referenced by XNvm_EfuseSetupController.
int XNvm_EfuseSetReadMode(XNvm_EfuseRdMode RdMode)
This function sets read mode of eFUSE controller.
RdMode - Mode to be used for eFUSE read. XST_SUCCESS If Setting read mode is successful.XST_FAILURE If there is a failure
References XNVM_EFUSE_SEC_DEF_VAL_ALL_BIT_SET, XNVM_EFUSE_SEC_DEF_VAL_BYTE_SET, XNvm_EfuseReadReg, XNVM_EFUSE_CTRL_BASEADDR, XNVM_EFUSE_CFG_REG_OFFSET, XNVM_EFUSE_NORMAL_RD, XNVM_EFUSE_CFG_NORMAL_RD, XNVM_EFUSE_CFG_MARGIN_RD, XNVM_EFUSE_CTRL_CFG_MARGIN_RD_MASK.
Referenced by XNvm_EfuseSetupController.
void XNvm_EfuseSetRefClk(void)
This function sets reference clock of eFUSE controller.
References XNvm_EfuseWriteReg, XNVM_CRP_BASE_ADDR, XNVM_CRP_EFUSE_REF_CLK_REG_OFFSET, XNVM_CRP_EFUSE_REF_CLK_SELSRC.
Referenced by XNvm_EfuseSetupController.
void XNvm_EfuseEnableProgramming(void)
This function enables programming mode of eFUSE controller.
References XNvm_EfuseReadReg, XNVM_EFUSE_CTRL_BASEADDR, XNVM_EFUSE_CFG_REG_OFFSET, XNVM_EFUSE_CFG_ENABLE_PGM, XNvm_EfuseWriteReg.
Referenced by XNvm_EfuseSetupController.
int XNvm_EfuseDisableProgramming(void)
This function disables programming mode of eFUSE controller.
XST_SUCCESS If eFUSE programming is disabled successfully.XST_FAILURE If there is a failure
References XNvm_EfuseReadReg, XNVM_EFUSE_CTRL_BASEADDR, XNVM_EFUSE_CFG_REG_OFFSET, XNVM_EFUSE_CFG_ENABLE_PGM.
int XNvm_EfuseResetReadMode(void)
This function disables Margin Read mode of eFUSE controller.
XST_SUCCESS If resetting read mode is successful.XST_FAILURE If there is a failure
References XNvm_EfuseReadReg, XNVM_EFUSE_CTRL_BASEADDR, XNVM_EFUSE_CFG_REG_OFFSET, XNVM_EFUSE_CFG_MARGIN_RD.
void XNvm_EfuseInitTimers(void)
This function initializes eFUSE controller timers.
References XNVM_PSU_PSS_REF_CLK_FREQ, XNVM_EFUSE_TPGM_DIV, XNvm_EfuseWriteReg, XNVM_EFUSE_CTRL_BASEADDR, XNVM_EFUSE_TPGM_REG_OFFSET, XNVM_EFUSE_TRD_DIV, XNVM_EFUSE_TRD_REG_OFFSET, XNVM_EFUSE_TRMD_DIV, XNVM_EFUSE_TRDM_REG_OFFSET, XNVM_EFUSE_TSU_H_PS_DIV, XNVM_EFUSE_TSU_H_PS_REG_OFFSET, XNVM_EFUSE_TSU_H_PS_CS_DIV, XNVM_EFUSE_TSU_H_PS_CS_REG_OFFSET, XNVM_EFUSE_TSU_H_CS_DIV, XNVM_EFUSE_TSU_H_CS_REG_OFFSET.
Referenced by XNvm_EfuseSetupController.
int XNvm_EfuseSetupController(XNvm_EfuseOpMode Op, XNvm_EfuseRdMode RdMode)
This function setups eFUSE controller for given operation and read mode.
Op - Operation to be performed read/program(write). RdMode - Read mode for eFUSE read operation. XST_SUCCESS eFUSE controller setup for given op.XNVM_EFUSE_ERR_UNLOCK Failed to unlock eFUSE controller register access.XST_FAILURE If eFUSE controller is not unlockedXNVM_EFUSE_ERR_PGM_TBIT_PATTERN If TBITS pattern is not matched with the expected value.
References XNvm_EfuseUnlockController, XNvm_EfuseDisablePowerDown, XNvm_EfuseSetRefClk, XNVM_EFUSE_MODE_PGM, XNvm_EfuseEnableProgramming, XNvm_EfuseSetReadMode, XNvm_EfuseInitTimers, XNvm_EfuseWriteReg, XNVM_EFUSE_CTRL_BASEADDR, XNVM_EFUSE_TEST_CTRL_REG_OFFSET, XNvm_EfuseCheckForTBits.
int XNvm_EfuseCheckForTBits(void)
This function checks whether Tbits are programmed or not.
XST_SUCCESS On Success.XNVM_EFUSE_ERR_PGM_TBIT_PATTERN Error in T-Bit pattern.
References XNVM_EFUSE_STATUS_TBIT_0, XNVM_EFUSE_STATUS_TBIT_1, XNVM_EFUSE_STATUS_TBIT_2, XNvm_EfuseReadReg, XNVM_EFUSE_CTRL_BASEADDR, XNVM_EFUSE_STATUS_REG_OFFSET, XNVM_EFUSE_ERR_PGM_TBIT_PATTERN.
Referenced by XNvm_EfuseSetupController.
u32 XNvm_GetSysmonSupplyRegId(UINTPTR SysmonpsvSatBaseAddr)
This function reads root register ID where measurement is stored in Root SysMon.
SysmonpsvSatBaseAddr - Pointer to SysMon base address SupplyReg Id - On successful match foundXNVM_EFUSE_SEC_DEF_VAL_ALL_BIT_SET - When no matching supply found
References XNVM_EFUSE_SEC_DEF_VAL_ALL_BIT_SET, XNVM_EFUSE_SYSMON_NUM_MEASURE_REGS, XNVM_EFUSE_SYSMONPSV_SAT_MEASURE0_OFFSET, XNVM_EFUSE_WORD_LEN, XNVM_EFUSE_SYSMON_SAT_CONFIG_ABUS_SW0_MASK, XNVM_EFUSE_SYSMON_SAT_CONFIG_ABUS_SW0_SHIFT, XNVM_EFUSE_SYSMON_SAT_CONFIG_ABUS_SW1_MASK, XNVM_EFUSE_SYSMON_SAT_CONFIG_ABUS_SW1_SHIFT, XNVM_EFUSE_SYSMON_SAT_CONFIG_AMUX_CTRL_MASK, XNVM_EFUSE_SYSMON_SAT_CONFIG_AMUX_CTRL_SHIFT, XNVM_EFUSE_SYSMON_SAT_CONFIG_MODE_MASK, XNVM_EFUSE_SYSMON_SAT_CONFIG_MODE_SHIFT, XNVM_EFUSE_SYSMON_VCCPMC_ABUS_SW1, XNVM_EFUSE_SYSMON_VCCPMC_ABUS_SW0, XNVM_EFUSE_SYSMON_VCCPMC_AMUX_CTRL, XNVM_EFUSE_SYSMON_VCCPMC_MODE, XNVM_EFUSE_SYSMON_SAT_ADDR_ID_MASK, XNVM_EFUSE_SYSMON_SAT_ADDR_ID_SHIFT.
Referenced by XNvm_EfuseTempAndVoltChecks.
int XNvm_EfuseTempAndVoltChecks(const XSysMonPsv *SysMonInstPtr)
This function performs the Temperature and Voltage checks to ensure that they are in limits before eFuse programming.
SysMonInstPtr - Pointer to SysMon instance. XST_SUCCESS - On successful Voltage and Temperature checks.XNVM_EFUSE_ERR_INVALID_PARAM - Input validation failure.XNVM_EFUSE_ERROR_READ_VOLTAGE_OUT_OF_RANGE - Voltage is out of rangeXNVM_EFUSE_ERROR_READ_TEMPERATURE_OUT_OF_RANGE - Temperature is out of range
References XNVM_EFUSE_SEC_DEF_VAL_ALL_BIT_SET, XNVM_EFUSE_ERR_INVALID_PARAM, XNVM_EFUSE_SYSMON_LOCK_CODE, XNvm_GetSysmonSupplyRegId, XNVM_EFUSE_SYSMONPSV_SAT0_BASEADDR, XNVM_EFUSE_SYSMONPSV_SAT1_BASEADDR, XNVM_EFUSE_ERROR_NO_SUPPLIES_ENABLED, XNVM_EFUSE_WORD_LEN, XNVM_EFUSE_SYSMON_NUM_SUPPLIES_PER_FLAG, XNVM_EFUSE_SYSMONPSV_TIMEOUT, XNVM_EFUSE_ERROR_SYSMON_NO_NEW_DATA, XNVM_EFUSE_FRACTION_MUL_VALUE, XNVM_EFUSE_ERROR_READ_VOLTAGE_OUT_OF_RANGE, XNVM_EFUSE_ERROR_READ_TMEPERATURE_OUT_OF_RANGE.
Referenced by XNvm_EfuseWrite, XNvm_EfuseWritePuf, XNvm_EfuseWriteAesKey, XNvm_EfuseWritePpkHash, XNvm_EfuseWriteIv, XNvm_EfuseWriteGlitchConfigBits, XNvm_EfuseWriteDecOnly, XNvm_EfuseWriteRevocationID, XNvm_EfuseWriteOffChipRevokeID, XNvm_EfuseWriteMiscCtrlBits, XNvm_EfuseWriteSecCtrlBits, XNvm_EfuseWriteMisc1Bits, XNvm_EfuseWriteBootEnvCtrlBits, XNvm_EfuseWriteFipsInfo, XNvm_EfuseWriteUds, XNvm_EfuseWriteDmeUserKey, XNvm_EfuseWriteDmeRevoke, XNvm_EfuseWriteDisableInplacePlmUpdate, XNvm_EfuseWriteBootModeDisable, XNvm_EfuseWriteDmeMode, XNvm_EfuseWriteCrc, XNvm_EfuseWritePufSecCtrl, XNvm_EfuseWriteRomRsvdBits.
u32 XNvm_EfuseReadProtectionBits(u32 Mask)
This function reads the corresponding eFuse protection bits.
Mask Efuse Protection bit mask value. Return protection bits value as specified by Mask
References XNVM_EFUSE_PROTECTION_BIT_CLEAR, XNvm_EfuseReadReg, XNVM_EFUSE_CACHE_BASEADDR, XNVM_EFUSE_TBITS_XILINX_CTRL_ROW.