xnvm_mailbox.h
int XNvm_ProcessMailbox(XMailbox *MailboxPtr, u32 *MsgPtr, u32 MsgLen)
This function sends IPI request to the target module and gets the response from it.
MailboxPtr Pointer to mailbox instance MsgPtr Pointer to the payload message MsgLen Length of the message XST_SUCCESS If the IPI send and receive is successfulXST_FAILURE If there is a failure Payload consists of API id and call arguments to be written in IPI buffer
Referenced by XNvm_EfuseWrite, XNvm_EfuseWriteIVs, XNvm_EfuseWriteDiceUds, XNvm_WriteDmePrivateKey, XNvm_WriteDmeRevoke, XNvm_EfuseWriteDmeMode, XNvm_EfuseReadDmeMode, XNvm_EfuseWriteSecCtrlBits, XNvm_EfuseWritePufCtrlBits, XNvm_EfuseWriteMiscCtrlBits, XNvm_EfuseWriteBootModeDis, XNvm_EfuseWriteSecMisc1Bits, XNvm_EfuseWriteBootEnvCtrlBits, XNvm_EfuseWriteRomRsvdBits, XNvm_EfuseWriteGlitchConfigBits, XNvm_EfuseWritePlmUpdate, XNvm_EfuseWriteDecOnly, XNvm_EfuseWriteFipsInfo, XNvm_EfuseWriteRevocationId, XNvm_EfuseWriteOffChipRevocationId, XNvm_EfuseWritePuf, XNvm_EfuseReadPuf, XNvm_EfuseReadIv, XNvm_EfuseReadRevocationId, XNvm_EfuseReadUserFuses, XNvm_EfuseReadMiscCtrlBits, XNvm_EfuseReadSecCtrlBits, XNvm_EfuseReadSecMisc1Bits, XNvm_EfuseReadBootEnvCtrlBits, XNvm_EfuseReadRomRsvdBits, XNvm_EfuseReadFipsInfoBits, XNvm_EfuseReadPufSecCtrlBits, XNvm_EfuseReadOffchipRevokeId, XNvm_EfuseReadPpkHash, XNvm_EfuseReadDecOnly, XNvm_EfuseReadBootModeDis, XNvm_EfuseReadDmeRevokeId, XNvm_EfuseReadDna, XNvm_EfuseAesKeyCrcCheck, XNvm_SendRequest.
int XNvm_ClientInit(XNvm_ClientInstance *const InstancePtr, XMailbox *const MailboxPtr)
This function sets the instance of mailbox.
InstancePtr Pointer to the client instance MailboxPtr Pointer to the mailbox instance XST_SUCCESS On successful initializationXST_FAILURE On failure
Referenced by main.