xnvm_generic.c
int XNvm_SendRequest(const XNvm_ClientInstance *InstancePtr, u32 *PayloadBuf, u32 PayloadLen, u32 *ResponseBuf, u32 ResponseLen)
This function sends request to PLM through either SMC or IPI mailbox based on the execution environment.
For EL1 non-secure AArch64 applications, SMC is used. For other environments, IPI mailbox is used. InstancePtr Pointer to the client instance PayloadBuf Pointer to the payload message PayloadLen Length of the payload message ResponseBuf Pointer to store response values (can be NULL) ResponseLen Length of response buffer (pass 0U when ResponseBuf is NULL) XST_SUCCESS If the request is successfulXST_FAILURE If there is a failureXST_INVALID_PARAM If input parameters are invalid This is a generic API that internally handles SMC or Mailbox communication based on the build configuration.
References XNvm_ProcessMailbox.
Referenced by XNvm_BbramLockUsrDataWrite, XNvm_BbramReadUsrData, XNvm_BbramWriteAesKey, XNvm_BbramWriteUsrData, XNvm_BbramZeroize, XNvm_EfuseAesKeyCrcCheck, XNvm_EfuseReadBootEnvCtrlBits, XNvm_EfuseReadDecOnly, XNvm_EfuseReadDna, XNvm_EfuseReadIv, XNvm_EfuseReadMiscCtrlBits, XNvm_EfuseReadOffchipRevokeId, XNvm_EfuseReadPpkHash, XNvm_EfuseReadPuf, XNvm_EfuseReadPufSecCtrlBits, XNvm_EfuseReadRevocationId, XNvm_EfuseReadSecCtrlBits, XNvm_EfuseReadSecMisc1Bits, XNvm_EfuseReadUserFuses, XNvm_EfuseRevokePpk, XNvm_EfuseWrite, XNvm_EfuseWriteIVs, XNvm_EfuseWritePuf, XNvm_EfuseWriteRevocationId, XNvm_EfuseWriteUserFuses.