xi3c_intr_example.c
XI3C_BASEADDRESS
I3C_DATALEN
I3C_SLAVE_ADDR
XI3c Xi3c_Instance
XI3c* InstancePtr
volatile u32 TransferComplete
volatile u32 TotalErrorCount
int I3cMasterIntrExample(UINTPTR BaseAddress)
This function does a minimal test on the I3c device and driver as a design example.
The purpose of this function is to illustrate how to use the XI3c driver.This function sends and receives data through the I3C.This function uses interrupt driver mode of the I3C. DeviceId is the Device ID of the I3c Device and is the XPAR_<I3C_instance>_DEVICE_ID value from xparameters.h XST_SUCCESS if successful, otherwise XST_FAILURE.
References XI3c_Config::BaseAddress, Handler, XI3c_Config::IntrId, XI3c_Config::IntrParent, XI3C_BusInit, XI3c_CfgInitialize, XI3c_LookupConfig, XI3c_MasterInterruptHandler, XI3c_MasterRecv, XI3c_MasterSend, XI3c_SendTransferCmd, XI3c_SetStatusHandler.
Referenced by main.
void Handler(u32 Event)
This function is the handler which updates transfer status up on events from the I3C.
It is called from an interrupt context such that the amount of processing performed should be minimized.None. None.
Referenced by I3cMasterIntrExample, I3cSlaveIntrExample.
int main(void)
Main function to call the interrupt example.
XST_SUCCESS if successful, XST_FAILURE if unsuccessful. None.
References I3cMasterIntrExample.