xi3c_slave.c
static s32 XI3c_SlaveEvent(XI3c *InstancePtr, u16 ByteCount)
static s32 XI3c_SlaveSetMWL(XI3c *InstancePtr, u16 ByteCount)
static s32 XI3c_SlaveSetMRL(XI3c *InstancePtr, u16 ByteCount)
static s32 XI3c_RstGrpAddr(XI3c *InstancePtr, u16 ByteCount)
static s32 XI3c_SetGrpAddr(XI3c *InstancePtr, u16 ByteCount)
static s32 XI3c_RstAction(XI3c *InstancePtr, u16 ByteCount)
static s32 XI3c_SlaveHandleCCC(XI3c *InstancePtr, u32 ResponseData)
static s32 XI3c_SlaveHandleRecv(XI3c *InstancePtr, u16 ByteCount)
static s32 XI3c_SlaveTransferHandle(XI3c *InstancePtr)
s32 XI3c_SlaveSend(XI3c *InstancePtr, u8 *MsgPtr, u16 ByteCount)
This function initiates a interrupt mode send in slave mode.
InstancePtr is a pointer to the XI3c instance. MsgPtr is the pointer to the send buffer. ByteCount is the number of bytes to be sent. - XST_SUCCESS if everything went well. XST_NO_DATA if MsgPtr is NULL. Error code if any error. None.
References XI3c::Config, XI3c_Config::RwFifoDepth, XI3c::SendBufferPtr, XI3c::SendByteCount, XI3c_FillSlaveSendCount, XI3c_GetMRL, XI3c_WrFifoLevel, XI3c_WriteTxFifo.
Referenced by I3cSlaveIntrExample.
s32 XI3c_SlaveRecv(XI3c *InstancePtr, u8 *MsgPtr)
This function initiates a interrupt mode receive in slave mode.
InstancePtr is a pointer to the XI3c instance. MsgPtr is the pointer to the recv buffer. XST_SUCCESS if everything went well.XST_NO_DATA if MsgPtr is NULL. None.
References XI3c::RecvBufferPtr.
Referenced by I3cSlaveIntrExample.
s32 XI3c_SlaveSendPolled(XI3c *InstancePtr, u8 *MsgPtr, u16 ByteCount)
This function initiates a polled mode send in slave mode.
It sends data to the FIFO and the master to pick them up. InstancePtr is a pointer to the XI3c instance. MsgPtr is the pointer to the send buffer. ByteCount is the number of bytes to be sent. XST_SUCCESS if everything went well.XST_SEND_ERROR if any error.XST_NO_DATA if MsgPtr is NULL. Caller need to wait for response after calling this function.
References XI3c::Config, XI3c_Config::RwFifoDepth, XI3c::SendBufferPtr, XI3c::SendByteCount, XI3c_FillSlaveSendCount, XI3c_GetMRL, XI3c_WrFifoLevel, XI3c_WriteTxFifo.
Referenced by I3cSlavePolledExample.
s32 XI3c_SlaveRecvPolled(XI3c *InstancePtr, u8 *MsgPtr)
This function initiates a polled mode receive in slave mode.
InstancePtr is a pointer to the XI3c instance. MsgPtr is the pointer to the send buffer. XST_SUCCESS if everything went well.XST_RECV_ERROR if any error.XST_NO_DATA if MsgPtr is NULL. None.
References XI3c::RecvBufferPtr.
Referenced by I3cSlavePolledExample.
void XI3c_SlaveInterruptHandler(XI3c *InstancePtr)
The interrupt handler for the slave mode.
It does the slave side protocol handling for the interrupt-driven transfers.If the slave is receiving data then the data is read from the FIFO and the slave has to send data on master request data need to write to FIFO. If all the data has been transferred then a completion event is signalled to the upper layer by calling the callback handler. InstancePtr is a pointer to the XI3c instance. None. None.
References XI3c_Config::BaseAddress, XI3c::Config, XI3c::DirectCCC, XI3c::Error, XI3c::StatusHandler, XI3C_INTR_RESP_NOT_EMPTY_MASK, XI3C_INTR_STATUS_OFFSET, XI3c_ReadReg, XI3c_WriteReg.
Referenced by I3cSlaveIntrExample.