xi3c.c
u8 XI3C_DynaAddrList[][]
void XI3c_ConfigIbi(XI3c *InstancePtr, u8 DevCount)
This configure target address and BCR register values of available devices to the controller RAM.
InstancePtr is a pointer to the XI3c instance. DevCount is the number of slave devices present. None. None.
References XI3c::IsReady.
Referenced by XI3c_CfgInitialize.
void XI3C_BusInit(XI3c *InstancePtr)
Initializes the XI3c slaves devices by disable/enable events and reset dynamic addresses.
InstancePtr is a pointer to the XI3c instance. None. None.
References XI3c_SendTransferCmd.
Referenced by I3cMasterDaaExample, I3cMasterIntrExample, I3cMasterPolledExample, XI3c_CfgInitialize.
s32 XI3c_CfgInitialize(XI3c *InstancePtr, XI3c_Config *ConfigPtr, u32 EffectiveAddr)
Initializes a specific XI3c instance such that the driver is ready to use.
InstancePtr is a pointer to the XI3c instance. ConfigPtr is a reference to a structure containing information about a specific I3C device. This function initializes an InstancePtr object for a specific device specified by the contents of Config. EffectiveAddr is the device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, use ConfigPtr->BaseAddress for this parameter, passing the physical address instead. The return value is XST_SUCCESS if successful. None.
References XI3c_Config::BaseAddress, XI3c::Config, XI3c::CurDeviceCount, XI3c_Config::DeviceCount, XI3c_Config::DeviceRole, XI3c_Config::HjCapable, XI3c_Config::IbiCapable, XI3c_Config::InputClockHz, XI3c::IsReady, XI3c_Config::RwFifoDepth, XI3c_Config::WrThreshold, XI3C_BusInit, XI3c_ConfigIbi, XI3c_DynaAddrAssign, XI3c_EnableREInterrupts, XI3C_INTR_HJ_MASK, XI3C_INTR_RESP_NOT_EMPTY_MASK.
Referenced by I3cMasterDaaExample, I3cMasterIntrExample, I3cMasterPolledExample, I3cSlaveIntrExample, I3cSlavePolledExample.
void XI3c_FillCmdFifo(XI3c *InstancePtr, XI3c_Cmd *Cmd)
Fill I3C Command fifo.
InstancePtr is a pointer to the XI3c instance. TransferCmd is a pointer to the XI3c_Cmd instance. None. None.
References XI3c_Config::BaseAddress, XI3c::Config, XI3C_CMD_FIFO_OFFSET, XI3c_WriteReg.
Referenced by XI3c_MasterRecv, XI3c_MasterRecvPolled, XI3c_MasterSend, XI3c_MasterSendPolled, XI3c_SendTransferCmd.
void XI3c_WriteTxFifo(XI3c *InstancePtr)
Fill I3C Write Tx FIFO.
BaseAddress contains the base address of the device. None. None.
References XI3c_Config::BaseAddress, XI3c::Config, XI3c::SendBufferPtr, XI3c::SendByteCount, XI3C_WR_FIFO_OFFSET, XI3c_WriteReg.
Referenced by XI3c_DynaAddrAssign, XI3c_MasterInterruptHandler, XI3c_MasterSend, XI3c_MasterSendPolled, XI3c_SendTransferCmd, XI3c_SlaveSend, XI3c_SlaveSendPolled.
void XI3c_ReadRxFifo(XI3c *InstancePtr)
Read RX I3C FIFO.
BaseAddress contains the base address of the device. None. None.
References XI3c_Config::BaseAddress, XI3c::Config, XI3c::RecvBufferPtr, XI3c::RecvByteCount, XI3C_RD_FIFO_OFFSET, XI3c_ReadReg.
Referenced by XI3c_IbiRecvPolled, XI3c_MasterInterruptHandler, XI3c_MasterRecvPolled.
s32 XI3c_DynaAddrAssign(XI3c *InstancePtr, u8 DynaAddr[], u8 DevCount)
This function sends dynamic Address Assignment for available devices.
InstancePtr is a pointer to the XI3c instance. DynaAddr is an array of dynamic addresses. DevCount is the number of slave devices present. XST_SUCCESS if everything went well.XST_FAILURE if any error. None.
References XI3c_SlaveInfo::Bcr, XI3c::CurDeviceCount, XI3c_SlaveInfo::Dcr, XI3c_SlaveInfo::DynaAddr, XI3c_SlaveInfo::Id, XI3c::IsReady, XI3c::SendBufferPtr, XI3c::SendByteCount, XI3c_MasterRecvPolled, XI3c_SendTransferCmd, XI3c::XI3c_SlaveInfoTable, XI3c_WriteTxFifo.
Referenced by I3cMasterDaaExample, XI3c_CfgInitialize, XI3c_MasterInterruptHandler.