xi3c.h
XI3C_H
by using protection macros
XI3C_MAXDAACOUNT
XI3C_MAXDATA_LENGTH
XI3C_SLAVEINFO_READ_BYTECOUNT
TIMEOUT_COUNTER
Wait for 2 sec in worst case.
Referenced by XI3c_IbiRecvPolled.
XI3C_BROADCAST_ADDRESS
WORD_TO_BYTE
XI3C_CEIL_DIV
XI3C_CCC_BRDCAST_MAX_VAL
XI3C_CCC_BRDCAST_ENEC
XI3C_CCC_BRDCAST_DISEC
XI3C_CCC_BRDCAST_ENTAS
XI3C_CCC_BRDCAST_ENTAS1
XI3C_CCC_BRDCAST_ENTAS2
XI3C_CCC_BRDCAST_ENTAS3
XI3C_CCC_BRDCAST_RSTDAA
XI3C_CCC_BRDCAST_ENTDAA
XI3C_CCC_BRDCAST_DEFTGTS
XI3C_CCC_BRDCAST_SETMWL
XI3C_CCC_BRDCAST_SETMRL
XI3C_CCC_BRDCAST_RSTACT
XI3C_CCC_BRDCAST_RSTGRPA
XI3C_CCC_BRDCAST_SETAASA
XI3C_CCC_ENEC
XI3C_CCC_DISEC
XI3C_CCC_ENTAS0
XI3C_CCC_ENTAS1
XI3C_CCC_ENTAS2
XI3C_CCC_ENTAS3
XI3C_CCC_SETDASA
XI3C_CCC_SETNEWDA
XI3C_CCC_SETMWL
XI3C_CCC_SETMRL
XI3C_CCC_GETMWL
XI3C_CCC_GETMRL
XI3C_CCC_GETPID
XI3C_CCC_GETBCR
XI3C_CCC_GETDCR
XI3C_CCC_GETSTATUS
XI3C_CCC_GETMXDS
XI3C_CCC_GETCAPS
XI3C_CCC_RSTACT
XI3C_CCC_SETGRPA
XI3C_CCC_RSTGRPA
XI3c_BusIsBusy
Checks whether the I3C bus is busy.
InstancePtr is a pointer to the XI3c instance. None. C-style signature: s32 XI3c_BusIsBusy(XI3c *InstancePtr)
XI3c_GetDynaAddr
Gets the dynamic address of the I3C.
InstancePtr is a pointer to the XI3c instance. None. The address returned includes parity. C-style signature: u8 XI3c_GetDynaAddr(XI3c *InstancePtr)
XI3c_SetSclHighTime
Sets scl high time of I3C.
InstancePtr is a pointer to the XI3c instance. Val is scl high time value to be set. None. Caller need to update other timing parameters if required. C-style signature: void XI3c_SetSclHighTime(XI3c *InstancePtr, u32 Val)
XI3c_GetSclHighTime
Gets scl high time of I3C.
InstancePtr is a pointer to the XI3c instance. None. C-style signature: u32 XI3c_GetSclHighTime(XI3c *InstancePtr)
XI3c_SetSclLowTime
Sets scl low time of I3C.
InstancePtr is a pointer to the XI3c instance. Val is scl low time value to be set. None. Caller need to update other timing parameters if required. C-style signature: void XI3c_SetSclLowTime(XI3c *InstancePtr, u32 Val)
XI3c_GetSclLowTime
Gets scl low time of I3C.
InstancePtr is a pointer to the XI3c instance. None. C-style signature: u32 XI3c_GetSclLowTime(XI3c *InstancePtr)
XI3c_SetSdaHoldTime
Sets sda hold time of I3C.
InstancePtr is a pointer to the XI3c instance. Val is sda hold time value to be set. None. Caller need to update other timing parameters if required. C-style signature: void XI3c_SetSdaHoldTime(XI3c *InstancePtr, u32 Val)
XI3c_GetSdaHoldTime
Gets sda hold time of I3C.
InstancePtr is a pointer to the XI3c instance. None. C-style signature: u32 XI3c_GetSdaHoldTime(XI3c *InstancePtr)
XI3c_SetBusIdleTime
Sets bus idle time of I3C.
InstancePtr is a pointer to the XI3c instance. Val is bus idle time value to be set. None. Caller need to update other timing parameters if required. C-style signature: void XI3c_SetBusIdleTime(XI3c *InstancePtr, u32 Val)
XI3c_GetBusIdleTime
Gets bus idle time of I3C.
InstancePtr is a pointer to the XI3c instance. None. C-style signature: u32 XI3c_GetBusIdleTime(XI3c *InstancePtr)
XI3c_SetTsuStartTime
Sets Tsu Start time of I3C.
InstancePtr is a pointer to the XI3c instance. Val is Tsu Start time value to be set. None. Caller need to update other timing parameters if required. C-style signature: void XI3c_SetTsuStartTime(XI3c *InstancePtr, u32 Val)
XI3c_GetTsuStartTime
Gets Tsu Start time of I3C.
InstancePtr is a pointer to the XI3c instance. None. C-style signature: u32 XI3c_GetTsuStartTime(XI3c *InstancePtr)
XI3c_SetThdStartTime
Sets Thd Start time of I3C.
InstancePtr is a pointer to the XI3c instance. Val is Thd Start time value to be set. None. Caller need to update other timing parameters if required. C-style signature: void XI3c_SetThdStartTime(XI3c *InstancePtr, u32 Val)
XI3c_GetThdStartTime
This function gets Thd Start time.
InstancePtr is a pointer to the XI3c instance. None. C-style signature: u32 XI3c_GetThdStartTime(XI3c *InstancePtr)
XI3c_SetTsuStopTime
Sets Tsu Stop time of I3C.
InstancePtr is a pointer to the XI3c instance. Val is Tsu Stop time value to be set. None. Caller need to update other timing parameters if required. C-style signature: void XI3c_SetTsuStopTime(XI3c *InstancePtr, u32 Val)
XI3c_GetTsuStopTime
Gets Tsu Stop time of I3C.
InstancePtr is a pointer to the XI3c instance. None. C-style signature: u32 XI3c_GetTsuStopTime(XI3c *InstancePtr)
XI3c_SetSclOdHighTime
Sets Scl open drain high time of I3C.
InstancePtr is a pointer to the XI3c instance. Val is Scl open drain high time value to be set. None. Caller need to update other timing parameters if required. C-style signature: void XI3c_SetSclOdHighTime(XI3c *InstancePtr, u32 Val)
XI3c_GetSclOdHighTime
Gets Scl open drain high time of I3C.
InstancePtr is a pointer to the XI3c instance. None. C-style signature: u32 XI3c_GetSclOdHighTime(XI3c *InstancePtr)
XI3c_SetSclOdLowTime
Sets Scl open drain low time of I3C.
InstancePtr is a pointer to the XI3c instance. Val is Scl open drain low time value to be set. None. Caller need to update other timing parameters if required. C-style signature: void XI3c_SetSclOdLowTime(XI3c *InstancePtr, u32 Val)
XI3c_GetSclOdLowTime
Gets Scl open drain low time of I3C.
InstancePtr is a pointer to the XI3c instance. None. C-style signature: u32 XI3c_GetSclOdLowTime(XI3c *InstancePtr)
XI3c_GetRevisionNumber
Gets Core Revision number of I3C.
InstancePtr is a pointer to the XI3c instance. None. C-style signature: u32 XI3c_GetRevisionNumber(XI3c *InstancePtr)
Referenced by XI3c_SetSClk.
XI3c_GetResponseData
Gets Response data of I3C.
InstancePtr is a pointer to the XI3c instance. Response value. C-style signature: u32 XI3c_GetResponseData(XI3c *InstancePtr)
XI3c_GetErrorStatus
Gets error status from response of I3C.
InstancePtr is a pointer to the XI3c instance. 0 if no error. error code if any error. C-style signature: u32 XI3c_GetErrorStatus(XI3c *InstancePtr)
Referenced by I3cSlavePolledExample.
XI3c_IsDyncAddrAssigned
Check the dynamic address assignment status of I3C in slave mode.
InstancePtr is a pointer to the XI3c instance. 1 if address assigned. 0 if address not assigned. C-style signature: u32 XI3c_IsDyncAddrAssigned(XI3c *InstancePtr)
Referenced by I3cSlaveIntrExample, I3cSlavePolledExample.
XI3c_IsRespAvailable
Check the response status of I3C.
InstancePtr is a pointer to the XI3c instance. 1 if response available. 0 if response not available. C-style signature: u32 XI3c_IsRespAvailable(XI3c *InstancePtr)
Referenced by I3cSlavePolledExample.
XI3c_SetDeviceStatus
Sets device status of I3C.
InstancePtr is a pointer to the XI3c instance. Format1 value of Device status. Format2 value of Device status. None. C-style signature: void XI3c_SetDeviceStatus(XI3c *InstancePtr, u16 Format1, u16 Format2)
XI3c_SetMaxDataSpeed
Sets device Max data speed.
InstancePtr is a pointer to the XI3c instance. Format1 value of Device status. Format3 value of Device status. None. C-style signature: void XI3c_SetMaxDataSpeed(XI3c *InstancePtr, u16 Format1, u8 Format3)
XI3c_SetCapsFormat1
Sets device capabilities format1.
InstancePtr is a pointer to the XI3c instance. Caps1 of target device. Caps2 of target device. Caps3 of target device. Caps4 of target device. None. C-style signature: void XI3c_SetCapsFormat1(XI3c *InstancePtr, u8 Cap1, u8 Cap2, u8 Cap3, u8 Cap4)
XI3c_SetCapsFormat2
Sets device capabilities format2.
InstancePtr is a pointer to the XI3c instance. Caps1 of target device. Caps2 of target device. None. C-style signature: void XI3c_SetCapsFormat2(XI3c *InstancePtr, u8 Cap1, u8 Cap2)
typedef void(* XI3c_IntrHandler)(u32 StatusEvent))(u32 StatusEvent)
The handler data type allows the user to define a callback function to respond to interrupt events in the system.
This function is executed in interrupt context, so amount of processing should be minimized. CallBackRef is the callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. Its type is not important to the driver, so it is a void pointer. StatusEvent indicates one or more status events that occurred.
XI3c_Config XI3c_ConfigTable[][]
Configuration table.
Configuration table.
Referenced by XI3c_LookupConfig.
u8 XI3C_DynaAddrList[][]
XI3c_Config* XI3c_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID.
A table contains the configuration info for each device in the system. DeviceId contains the ID of the device to look up the configuration for. A pointer to the configuration found or NULL if the specified device ID was not found. See xi3c.h for the definition of XI3c_Config. None.
References XI3c_ConfigTable.
Referenced by I3cMasterDaaExample, I3cMasterIntrExample, I3cMasterPolledExample, I3cSlaveIntrExample, I3cSlavePolledExample.
s32 XI3c_CfgInitialize(XI3c *InstancePtr, XI3c_Config *ConfigPtr, u32 EffectiveAddr)
Initializes a specific XI3c instance such that the driver is ready to use.
InstancePtr is a pointer to the XI3c instance. ConfigPtr is a reference to a structure containing information about a specific I3C device. This function initializes an InstancePtr object for a specific device specified by the contents of Config. EffectiveAddr is the device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, use ConfigPtr->BaseAddress for this parameter, passing the physical address instead. The return value is XST_SUCCESS if successful. None.
References XI3c_Config::BaseAddress, XI3c::Config, XI3c::CurDeviceCount, XI3c_Config::DeviceCount, XI3c_Config::DeviceRole, XI3c_Config::HjCapable, XI3c_Config::IbiCapable, XI3c_Config::InputClockHz, XI3c::IsReady, XI3c_Config::RwFifoDepth, XI3c_Config::WrThreshold, XI3C_BusInit, XI3c_ConfigIbi, XI3c_DynaAddrAssign, XI3c_EnableREInterrupts, XI3C_INTR_HJ_MASK, XI3C_INTR_RESP_NOT_EMPTY_MASK.
Referenced by I3cMasterDaaExample, I3cMasterIntrExample, I3cMasterPolledExample, I3cSlaveIntrExample, I3cSlavePolledExample.
void XI3c_FillCmdFifo(XI3c *InstancePtr, XI3c_Cmd *Cmd)
Fill I3C Command fifo.
InstancePtr is a pointer to the XI3c instance. TransferCmd is a pointer to the XI3c_Cmd instance. None. None.
References XI3c_Config::BaseAddress, XI3c::Config, XI3C_CMD_FIFO_OFFSET, XI3c_WriteReg.
Referenced by XI3c_MasterRecv, XI3c_MasterRecvPolled, XI3c_MasterSend, XI3c_MasterSendPolled, XI3c_SendTransferCmd.
void XI3c_WriteTxFifo(XI3c *InstancePtr)
Fill I3C Write Tx FIFO.
BaseAddress contains the base address of the device. None. None.
References XI3c_Config::BaseAddress, XI3c::Config, XI3c::SendBufferPtr, XI3c::SendByteCount, XI3C_WR_FIFO_OFFSET, XI3c_WriteReg.
Referenced by XI3c_DynaAddrAssign, XI3c_MasterInterruptHandler, XI3c_MasterSend, XI3c_MasterSendPolled, XI3c_SendTransferCmd, XI3c_SlaveSend, XI3c_SlaveSendPolled.
void XI3c_ReadRxFifo(XI3c *InstancePtr)
Read RX I3C FIFO.
BaseAddress contains the base address of the device. None. None.
References XI3c_Config::BaseAddress, XI3c::Config, XI3c::RecvBufferPtr, XI3c::RecvByteCount, XI3C_RD_FIFO_OFFSET, XI3c_ReadReg.
Referenced by XI3c_IbiRecvPolled, XI3c_MasterInterruptHandler, XI3c_MasterRecvPolled.
s32 XI3c_SendTransferCmd(XI3c *InstancePtr, XI3c_Cmd *Cmd, u8 Data)
This function sends the command.
InstancePtr is a pointer to the XI3c instance. Cmd is a pointer to the XI3c_Cmd. Data is the command value. XST_SUCCESS if everything went well.XST_FAILURE if any error. None.
References XI3c::IsReady, XI3c::SendBufferPtr, XI3c::SendByteCount, XI3c_FillCmdFifo, XI3c_WriteTxFifo.
Referenced by I3cMasterDaaExample, I3cMasterIntrExample, I3cMasterPolledExample, XI3C_BusInit, XI3c_DynaAddrAssign.
s32 XI3c_DynaAddrAssign(XI3c *InstancePtr, u8 DynaAddr[], u8 DevCount)
This function sends dynamic Address Assignment for available devices.
InstancePtr is a pointer to the XI3c instance. DynaAddr is an array of dynamic addresses. DevCount is the number of slave devices present. XST_SUCCESS if everything went well.XST_FAILURE if any error. None.
References XI3c_SlaveInfo::Bcr, XI3c::CurDeviceCount, XI3c_SlaveInfo::Dcr, XI3c_SlaveInfo::DynaAddr, XI3c_SlaveInfo::Id, XI3c::IsReady, XI3c::SendBufferPtr, XI3c::SendByteCount, XI3c_MasterRecvPolled, XI3c_SendTransferCmd, XI3c::XI3c_SlaveInfoTable, XI3c_WriteTxFifo.
Referenced by I3cMasterDaaExample, XI3c_CfgInitialize, XI3c_MasterInterruptHandler.
s32 XI3c_SetSClk(XI3c *InstancePtr, u32 SclkHz, u8 Mode)
Sets I3C Scl clock frequency.
InstancePtr is a pointer to the XI3c instance. SclkHz is Scl clock to be configured in Hz. Mode is the mode of operation I2C/I3C. The return value is XST_SUCCESS if successful. None.
References XI3c_Config::BaseAddress, XI3c::Config, XI3c_Config::InputClockHz, XI3c_GetRevisionNumber, XI3C_OD_SCL_HIGH_TIME_OFFSET, XI3C_OD_SCL_LOW_TIME_OFFSET, XI3C_SCL_HIGH_TIME_OFFSET, XI3C_SCL_LOW_TIME_OFFSET, XI3C_SDA_HOLD_TIME_OFFSET, XI3C_THD_START_OFFSET, XI3C_TSU_START_OFFSET, XI3C_TSU_STOP_OFFSET, XI3c_WriteReg.
void XI3C_BusInit(XI3c *InstancePtr)
Initializes the XI3c slaves devices by disable/enable events and reset dynamic addresses.
InstancePtr is a pointer to the XI3c instance. None. None.
References XI3c_SendTransferCmd.
Referenced by I3cMasterDaaExample, I3cMasterIntrExample, I3cMasterPolledExample, XI3c_CfgInitialize.
void XI3c_SetStatusHandler(XI3c *InstancePtr, XI3c_IntrHandler FunctionPtr)
This function sets the status handler, which the driver calls when it encounters conditions that should be reported to the higher layer software.
The handler executes in an interrupt context, so the amount of processing should be minimizedRefer to the xi3c.h file for a list of events. The events are defined to start with XI3C_EVENT_*. InstancePtr is a pointer to the XI3c instance. FunctionPtr is the pointer to the callback function. None. The handler is called within interrupt context, so it should finish its work quickly.
References XI3c::IsReady, XI3c::StatusHandler.
Referenced by I3cMasterIntrExample, I3cSlaveIntrExample.
s32 XI3c_MasterSend(XI3c *InstancePtr, XI3c_Cmd *Cmd, u8 *MsgPtr, u16 ByteCount)
This function initiates a interrupt mode send in master mode.
It sends data to the FIFO and waits for the slave to pick them up. If master fails to send data due arbitration lost or any other, will stop transfer with status. InstancePtr is a pointer to the XI3c instance. Cmd is a pointer to the XI3c_Cmd instance. MsgPtr is the pointer to the send buffer. ByteCount is the number of bytes to be sent. None. None.
References XI3c_Config::BaseAddress, XI3c::Config, XI3c::SendBufferPtr, XI3c::SendByteCount, XI3c_Config::WrThreshold, XI3c_EnableFEInterrupts, XI3c_EnableREInterrupts, XI3c_FillCmdFifo, XI3C_INTR_RESP_NOT_EMPTY_MASK, XI3C_INTR_WR_FIFO_ALMOST_FULL_MASK, XI3c_WrFifoLevel, XI3c_WriteTxFifo.
Referenced by I3cMasterIntrExample.
s32 XI3c_MasterRecv(XI3c *InstancePtr, XI3c_Cmd *Cmd, u8 *MsgPtr, u16 ByteCount)
This function initiates a interrupt mode receive in master mode.
It sets the transfer size register so the slave can send data to us. The rest of the work is managed by interrupt handler. InstancePtr is a pointer to the XI3c instance. Cmd is a pointer to the XI3c_Cmd instance. MsgPtr is the pointer to the recv buffer. ByteCount is the number of bytes to be recv. None. None.
References XI3c_Config::BaseAddress, XI3c::Config, XI3c::RecvBufferPtr, XI3c::RecvByteCount, XI3c_EnableREInterrupts, XI3c_FillCmdFifo, XI3C_INTR_RD_FULL_MASK, XI3C_INTR_RESP_NOT_EMPTY_MASK.
Referenced by I3cMasterIntrExample.
s32 XI3c_MasterSendPolled(XI3c *InstancePtr, XI3c_Cmd *Cmd, u8 *MsgPtr, u16 ByteCount)
This function initiates a polled mode send in master mode.
It sends data to the FIFO and waits for the slave to pick them up. If master fails to send data due arbitration lost or any other error, will stop transfer status. InstancePtr is a pointer to the XI3c instance. Cmd is a pointer to the XI3c_Cmd instance. MsgPtr is the pointer to the send buffer. ByteCount is the number of bytes to be sent. XST_SUCCESS if everything went well.XST_SEND_ERROR if any error. None.
References XI3c::SendBufferPtr, XI3c::SendByteCount, XI3c_FillCmdFifo, XI3c_WrFifoLevel, XI3c_WriteTxFifo.
Referenced by I3cMasterDaaExample, I3cMasterPolledExample.
s32 XI3c_MasterRecvPolled(XI3c *InstancePtr, XI3c_Cmd *Cmd, u8 *MsgPtr, u16 ByteCount)
This function initiates a polled mode receive in master mode.
It repeatedly sets the transfer size register so the slave can send data to us. It polls the data register for data to come in. If master fails to read data due arbitration lost or any other error, will return with status. InstancePtr is a pointer to the XI3c instance. Cmd is a pointer to the XI3c_Cmd instance. MsgPtr is the pointer to the send buffer. ByteCount is the number of bytes to be sent. XST_SUCCESS if everything went well.XST_RECV_ERROR if any error. None.
References XI3c::RecvBufferPtr, XI3c::RecvByteCount, XI3c_FillCmdFifo, XI3c_RdFifoLevel, XI3c_ReadRxFifo.
Referenced by I3cMasterDaaExample, I3cMasterPolledExample, XI3c_DynaAddrAssign.
void XI3c_MasterInterruptHandler(XI3c *InstancePtr)
The interrupt handler for the master mode.
It does the protocol handling for the interrupt-driven transfers.If the Master is receiving data then the data is read from the FIFO and the Master has to request for more data (if there is more data to receive). If all the data has been received then a completion event is signalled to the upper layer by calling the callback handler. It is an error if the amount of received data is more than expected. InstancePtr is a pointer to the XI3c instance. None. None.
References XI3c_Config::BaseAddress, XI3c::Config, XI3c::CurDeviceCount, XI3c::Error, XI3c_Config::IbiCapable, XI3c::RecvByteCount, XI3c::SendByteCount, XI3c::StatusHandler, XI3c_DisableFEInterrupts, XI3c_DisableREInterrupts, XI3c_DynaAddrAssign, XI3C_INTR_HJ_MASK, XI3C_INTR_IBI_MASK, XI3C_INTR_RD_FULL_MASK, XI3C_INTR_RESP_NOT_EMPTY_MASK, XI3C_INTR_STATUS_OFFSET, XI3C_INTR_WR_FIFO_ALMOST_FULL_MASK, XI3c_RdFifoLevel, XI3c_ReadReg, XI3c_ReadRxFifo, XI3C_RESP_STATUS_FIFO_OFFSET, XI3c_RespFifoNotEmpty, XI3c_RxFifoNotEmpty, XI3c_WrFifoLevel, XI3c_WriteReg, XI3c_WriteTxFifo.
Referenced by I3cMasterIntrExample.
s32 XI3c_IbiRecv(XI3c *InstancePtr, u8 *MsgPtr)
This function setup for receive during IBI in interrupt mode.
It enables the required interrupts for performing read operation during IBI. InstancePtr is a pointer to the XI3c instance. MsgPtr is the pointer to the recv buffer. XST_SUCCESS if everything went well.XST_NO_DATA if message buffer is NULL. None.
References XI3c_Config::BaseAddress, XI3c::Config, XI3c::RecvBufferPtr, XI3c_EnableREInterrupts, XI3C_INTR_IBI_MASK, XI3C_INTR_RESP_NOT_EMPTY_MASK.
s32 XI3c_IbiRecvPolled(XI3c *InstancePtr, u8 *MsgPtr)
This function receives data during IBI in polled mode.
It polls the data register for data to come in during IBI. If master fails to read data due to any error, it will return with status. InstancePtr is a pointer to the XI3c instance. MsgPtr is the pointer to the recv buffer. XST_SUCCESS if everything went well.XST_RECV_ERROR if any error. None.
References XI3c_Config::BaseAddress, XI3c::Config, XI3c::RecvBufferPtr, XI3c::RecvByteCount, TIMEOUT_COUNTER, XI3c_RdFifoLevel, XI3c_ReadRxFifo, XI3c_RespFifoNotEmpty, XI3c_RxFifoNotEmpty, XI3C_SR_OFFSET, XI3C_SR_RD_FIFO_NOT_EMPTY_MASK.
s32 XI3c_SlaveSend(XI3c *InstancePtr, u8 *MsgPtr, u16 ByteCount)
This function initiates a interrupt mode send in slave mode.
InstancePtr is a pointer to the XI3c instance. MsgPtr is the pointer to the send buffer. ByteCount is the number of bytes to be sent. - XST_SUCCESS if everything went well. XST_NO_DATA if MsgPtr is NULL. Error code if any error. None.
References XI3c::Config, XI3c_Config::RwFifoDepth, XI3c::SendBufferPtr, XI3c::SendByteCount, XI3c_FillSlaveSendCount, XI3c_GetMRL, XI3c_WrFifoLevel, XI3c_WriteTxFifo.
Referenced by I3cSlaveIntrExample.
s32 XI3c_SlaveRecv(XI3c *InstancePtr, u8 *MsgPtr)
This function initiates a interrupt mode receive in slave mode.
InstancePtr is a pointer to the XI3c instance. MsgPtr is the pointer to the recv buffer. XST_SUCCESS if everything went well.XST_NO_DATA if MsgPtr is NULL. None.
References XI3c::RecvBufferPtr.
Referenced by I3cSlaveIntrExample.
s32 XI3c_SlaveSendPolled(XI3c *InstancePtr, u8 *MsgPtr, u16 ByteCount)
This function initiates a polled mode send in slave mode.
It sends data to the FIFO and the master to pick them up. InstancePtr is a pointer to the XI3c instance. MsgPtr is the pointer to the send buffer. ByteCount is the number of bytes to be sent. XST_SUCCESS if everything went well.XST_SEND_ERROR if any error.XST_NO_DATA if MsgPtr is NULL. Caller need to wait for response after calling this function.
References XI3c::Config, XI3c_Config::RwFifoDepth, XI3c::SendBufferPtr, XI3c::SendByteCount, XI3c_FillSlaveSendCount, XI3c_GetMRL, XI3c_WrFifoLevel, XI3c_WriteTxFifo.
Referenced by I3cSlavePolledExample.
s32 XI3c_SlaveRecvPolled(XI3c *InstancePtr, u8 *MsgPtr)
This function initiates a polled mode receive in slave mode.
InstancePtr is a pointer to the XI3c instance. MsgPtr is the pointer to the send buffer. XST_SUCCESS if everything went well.XST_RECV_ERROR if any error.XST_NO_DATA if MsgPtr is NULL. None.
References XI3c::RecvBufferPtr.
Referenced by I3cSlavePolledExample.
void XI3c_SlaveInterruptHandler(XI3c *InstancePtr)
The interrupt handler for the slave mode.
It does the slave side protocol handling for the interrupt-driven transfers.If the slave is receiving data then the data is read from the FIFO and the slave has to send data on master request data need to write to FIFO. If all the data has been transferred then a completion event is signalled to the upper layer by calling the callback handler. InstancePtr is a pointer to the XI3c instance. None. None.
References XI3c_Config::BaseAddress, XI3c::Config, XI3c::DirectCCC, XI3c::Error, XI3c::StatusHandler, XI3C_INTR_RESP_NOT_EMPTY_MASK, XI3C_INTR_STATUS_OFFSET, XI3c_ReadReg, XI3c_WriteReg.
Referenced by I3cSlaveIntrExample.
static void XI3c_Enable(XI3c *InstancePtr, u8 Enable)
Enables/Disables the I3C.
To execute I3C transactions this has to be Enabled. Any data transfer that is in progress is aborted when disabled and no further I3C transactions will happen till I3C enabled. InstancePtr is a pointer to the XI3c instance. Enable is flag indicates to enable or disable the I3C. None. None.
static void XI3c_Abort(XI3c *InstancePtr)
Abort allows controller to kill existing transcation.
In response Abort request, Controller issues a stop condition after existing transcation is finished. Abort bit is auto cleared after Abort is completed. InstancePtr is a pointer to the XI3c instance. None. None.
static void XI3c_Resume(XI3c *InstancePtr)
Resume allows controller to resume the controller from Abort/Error State.
Resume bit will be auto cleared once controller resumes the operation. After Controller goes to Abort/Eroor State. User should handle the necessary action to Abort/Error state (ex: Clearing FIFOs etc) InstancePtr is a pointer to the XI3c instance. None. None.
static void XI3c_EnableIbi(XI3c *InstancePtr)
Enable IBI capability.
InstancePtr is a pointer to the XI3c instance. None. None.
static void XI3c_EnableHotjoin(XI3c *InstancePtr)
Enable Hot Join capability.
InstancePtr is a pointer to the XI3c instance. None. None.
static void XI3c_UpdateAddrBcr(XI3c *InstancePtr, u16 DevIndex)
Update the slave address and BCR register values of available device to the controller RAM.
InstancePtr is a pointer to the XI3c instance. Slave device index of XI3c_SlaveInfoTable. None. None.
static void XI3c_Reset(XI3c *InstancePtr)
Resets the I3C device.
Reset must only be called after the driver has been initialized. The configuration of the device after reset is the same as its configuration after initialization. Any data transfer that is in progress is aborted.The upper layer software is responsible for re-configuring (if necessary) and reenabling interrupts for the I3C device after the reset. InstancePtr is a pointer to the XI3c instance. None. None.
static void XI3c_ResetFifos(XI3c *InstancePtr)
Resets the fifos of I3C device.
Reset must only be called after the driver has been initialized. Any data transfer that is in progress is aborted. InstancePtr is a pointer to the XI3c instance. None. None.
static u8 XI3c_GetOddParity(u8 Addr)
Calculates the Odd parity for the dynamic address.
Addr is a dynamic address. - 0 if Addr has odd parity. 1 if Addr has even parity. None.