xi3c_sinit.c
XI3c_Config* XI3c_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID.
A table contains the configuration info for each device in the system. DeviceId contains the ID of the device to look up the configuration for. A pointer to the configuration found or NULL if the specified device ID was not found. See xi3c.h for the definition of XI3c_Config. None.
References XI3c_ConfigTable.
Referenced by I3cMasterDaaExample, I3cMasterIntrExample, I3cMasterPolledExample, I3cSlaveIntrExample, I3cSlavePolledExample.