xi3c_master.c
static s32 XI3c_GetResponse(XI3c *InstancePtr)
This function reads the response.
It waits for the response from slave and reads the response. InstancePtr is a pointer to the XI3c instance. Response code on success.XST_TIMEOUT on timeout.
s32 XI3c_SendTransferCmd(XI3c *InstancePtr, XI3c_Cmd *Cmd, u8 Data)
This function sends the command.
InstancePtr is a pointer to the XI3c instance. Cmd is a pointer to the XI3c_Cmd. Data is the command value. XST_SUCCESS if everything went well.XST_FAILURE if any error. None.
References XI3c::IsReady, XI3c::SendBufferPtr, XI3c::SendByteCount, XI3c_FillCmdFifo, XI3c_WriteTxFifo.
Referenced by I3cMasterDaaExample, I3cMasterIntrExample, I3cMasterPolledExample, XI3C_BusInit, XI3c_DynaAddrAssign.
s32 XI3c_MasterSend(XI3c *InstancePtr, XI3c_Cmd *Cmd, u8 *MsgPtr, u16 ByteCount)
This function initiates a interrupt mode send in master mode.
It sends data to the FIFO and waits for the slave to pick them up. If master fails to send data due arbitration lost or any other, will stop transfer with status. InstancePtr is a pointer to the XI3c instance. Cmd is a pointer to the XI3c_Cmd instance. MsgPtr is the pointer to the send buffer. ByteCount is the number of bytes to be sent. None. None.
References XI3c_Config::BaseAddress, XI3c::Config, XI3c::SendBufferPtr, XI3c::SendByteCount, XI3c_Config::WrThreshold, XI3c_EnableFEInterrupts, XI3c_EnableREInterrupts, XI3c_FillCmdFifo, XI3C_INTR_RESP_NOT_EMPTY_MASK, XI3C_INTR_WR_FIFO_ALMOST_FULL_MASK, XI3c_WrFifoLevel, XI3c_WriteTxFifo.
Referenced by I3cMasterIntrExample.
s32 XI3c_MasterRecv(XI3c *InstancePtr, XI3c_Cmd *Cmd, u8 *MsgPtr, u16 ByteCount)
This function initiates a interrupt mode receive in master mode.
It sets the transfer size register so the slave can send data to us. The rest of the work is managed by interrupt handler. InstancePtr is a pointer to the XI3c instance. Cmd is a pointer to the XI3c_Cmd instance. MsgPtr is the pointer to the recv buffer. ByteCount is the number of bytes to be recv. None. None.
References XI3c_Config::BaseAddress, XI3c::Config, XI3c::RecvBufferPtr, XI3c::RecvByteCount, XI3c_EnableREInterrupts, XI3c_FillCmdFifo, XI3C_INTR_RD_FULL_MASK, XI3C_INTR_RESP_NOT_EMPTY_MASK.
Referenced by I3cMasterIntrExample.
s32 XI3c_MasterSendPolled(XI3c *InstancePtr, XI3c_Cmd *Cmd, u8 *MsgPtr, u16 ByteCount)
This function initiates a polled mode send in master mode.
It sends data to the FIFO and waits for the slave to pick them up. If master fails to send data due arbitration lost or any other error, will stop transfer status. InstancePtr is a pointer to the XI3c instance. Cmd is a pointer to the XI3c_Cmd instance. MsgPtr is the pointer to the send buffer. ByteCount is the number of bytes to be sent. XST_SUCCESS if everything went well.XST_SEND_ERROR if any error. None.
References XI3c::SendBufferPtr, XI3c::SendByteCount, XI3c_FillCmdFifo, XI3c_WrFifoLevel, XI3c_WriteTxFifo.
Referenced by I3cMasterDaaExample, I3cMasterPolledExample.
s32 XI3c_MasterRecvPolled(XI3c *InstancePtr, XI3c_Cmd *Cmd, u8 *MsgPtr, u16 ByteCount)
This function initiates a polled mode receive in master mode.
It repeatedly sets the transfer size register so the slave can send data to us. It polls the data register for data to come in. If master fails to read data due arbitration lost or any other error, will return with status. InstancePtr is a pointer to the XI3c instance. Cmd is a pointer to the XI3c_Cmd instance. MsgPtr is the pointer to the send buffer. ByteCount is the number of bytes to be sent. XST_SUCCESS if everything went well.XST_RECV_ERROR if any error. None.
References XI3c::RecvBufferPtr, XI3c::RecvByteCount, XI3c_FillCmdFifo, XI3c_RdFifoLevel, XI3c_ReadRxFifo.
Referenced by I3cMasterDaaExample, I3cMasterPolledExample, XI3c_DynaAddrAssign.
static void XI3c_IbiReadRxFifo(XI3c *InstancePtr)
This function reads the Rx Fifo during IBI.
InstancePtr is a pointer to the XI3c instance. None
void XI3c_SetStatusHandler(XI3c *InstancePtr, XI3c_IntrHandler FunctionPtr)
This function sets the status handler, which the driver calls when it encounters conditions that should be reported to the higher layer software.
The handler executes in an interrupt context, so the amount of processing should be minimizedRefer to the xi3c.h file for a list of events. The events are defined to start with XI3C_EVENT_*. InstancePtr is a pointer to the XI3c instance. FunctionPtr is the pointer to the callback function. None. The handler is called within interrupt context, so it should finish its work quickly.
References XI3c::IsReady, XI3c::StatusHandler.
Referenced by I3cMasterIntrExample, I3cSlaveIntrExample.
void XI3c_MasterInterruptHandler(XI3c *InstancePtr)
The interrupt handler for the master mode.
It does the protocol handling for the interrupt-driven transfers.If the Master is receiving data then the data is read from the FIFO and the Master has to request for more data (if there is more data to receive). If all the data has been received then a completion event is signalled to the upper layer by calling the callback handler. It is an error if the amount of received data is more than expected. InstancePtr is a pointer to the XI3c instance. None. None.
References XI3c_Config::BaseAddress, XI3c::Config, XI3c::CurDeviceCount, XI3c::Error, XI3c_Config::IbiCapable, XI3c::RecvByteCount, XI3c::SendByteCount, XI3c::StatusHandler, XI3c_DisableFEInterrupts, XI3c_DisableREInterrupts, XI3c_DynaAddrAssign, XI3C_INTR_HJ_MASK, XI3C_INTR_IBI_MASK, XI3C_INTR_RD_FULL_MASK, XI3C_INTR_RESP_NOT_EMPTY_MASK, XI3C_INTR_STATUS_OFFSET, XI3C_INTR_WR_FIFO_ALMOST_FULL_MASK, XI3c_RdFifoLevel, XI3c_ReadReg, XI3c_ReadRxFifo, XI3C_RESP_STATUS_FIFO_OFFSET, XI3c_RespFifoNotEmpty, XI3c_RxFifoNotEmpty, XI3c_WrFifoLevel, XI3c_WriteReg, XI3c_WriteTxFifo.
Referenced by I3cMasterIntrExample.
s32 XI3c_IbiRecv(XI3c *InstancePtr, u8 *MsgPtr)
This function setup for receive during IBI in interrupt mode.
It enables the required interrupts for performing read operation during IBI. InstancePtr is a pointer to the XI3c instance. MsgPtr is the pointer to the recv buffer. XST_SUCCESS if everything went well.XST_NO_DATA if message buffer is NULL. None.
References XI3c_Config::BaseAddress, XI3c::Config, XI3c::RecvBufferPtr, XI3c_EnableREInterrupts, XI3C_INTR_IBI_MASK, XI3C_INTR_RESP_NOT_EMPTY_MASK.
s32 XI3c_IbiRecvPolled(XI3c *InstancePtr, u8 *MsgPtr)
This function receives data during IBI in polled mode.
It polls the data register for data to come in during IBI. If master fails to read data due to any error, it will return with status. InstancePtr is a pointer to the XI3c instance. MsgPtr is the pointer to the recv buffer. XST_SUCCESS if everything went well.XST_RECV_ERROR if any error. None.
References XI3c_Config::BaseAddress, XI3c::Config, XI3c::RecvBufferPtr, XI3c::RecvByteCount, TIMEOUT_COUNTER, XI3c_RdFifoLevel, XI3c_ReadRxFifo, XI3c_RespFifoNotEmpty, XI3c_RxFifoNotEmpty, XI3C_SR_OFFSET, XI3C_SR_RD_FIFO_NOT_EMPTY_MASK.