xv_tpg.h
XVTPG_IRQ_DONE_MASK
Interrupt mask for frame processing done event.
Referenced by XVTpg_InterruptHandler.
XVTPG_IRQ_READY_MASK
Interrupt mask for ready for next frame event.
Referenced by XVTpg_InterruptHandler.
XV_tpg_WriteReg
Write a value to a register.
Referenced by videoIpConfig, XV_tpg_DisableAutoRestart, XV_tpg_EnableAutoRestart, XV_tpg_InterruptClear, XV_tpg_InterruptDisable, XV_tpg_InterruptEnable, XV_tpg_InterruptGlobalDisable, XV_tpg_InterruptGlobalEnable, XV_tpg_Set_bckgndId, XV_tpg_Set_boxColorB, XV_tpg_Set_boxColorG, XV_tpg_Set_boxColorR, XV_tpg_Set_boxSize, XV_tpg_Set_colorFormat, XV_tpg_Set_crossHairX, XV_tpg_Set_crossHairY, XV_tpg_Set_dpDynamicRange, XV_tpg_Set_dpYUVCoef, XV_tpg_Set_enableInput, XV_tpg_Set_height, XV_tpg_Set_Interlaced, XV_tpg_Set_maskId, XV_tpg_Set_motionEn, XV_tpg_Set_motionSpeed, XV_tpg_Set_ovrlayId, XV_tpg_Set_passthruEndX, XV_tpg_Set_passthruEndY, XV_tpg_Set_passthruStartX, XV_tpg_Set_passthruStartY, XV_tpg_Set_Polarity, XV_tpg_Set_width, XV_tpg_Set_ZplateHorContDelta, XV_tpg_Set_ZplateHorContStart, XV_tpg_Set_ZplateVerContDelta, XV_tpg_Set_ZplateVerContStart, XV_tpg_Start.
XV_tpg_ReadReg
Read a value from a register.
Referenced by XV_tpg_Get_bckgndId, XV_tpg_Get_boxColorB, XV_tpg_Get_boxColorG, XV_tpg_Get_boxColorR, XV_tpg_Get_boxSize, XV_tpg_Get_colorFormat, XV_tpg_Get_crossHairX, XV_tpg_Get_crossHairY, XV_tpg_Get_dpDynamicRange, XV_tpg_Get_dpYUVCoef, XV_tpg_Get_enableInput, XV_tpg_Get_fieldId, XV_tpg_Get_height, XV_tpg_Get_maskId, XV_tpg_Get_motionEnStatus, XV_tpg_Get_motionSpeed, XV_tpg_Get_ovrlayId, XV_tpg_Get_passthruEndX, XV_tpg_Get_passthruEndY, XV_tpg_Get_passthruStartX, XV_tpg_Get_passthruStartY, XV_tpg_Get_width, XV_tpg_Get_ZplateHorContDelta, XV_tpg_Get_ZplateHorContStart, XV_tpg_Get_ZplateVerContDelta, XV_tpg_Get_ZplateVerContStart, XV_tpg_InterruptDisable, XV_tpg_InterruptEnable, XV_tpg_InterruptGetEnabled, XV_tpg_InterruptGetStatus, XV_tpg_IsDone, XV_tpg_IsIdle, XV_tpg_IsReady, XV_tpg_Start.
XTpg_PatternId
Horizontal ramp pattern.
XVTPG_HandlerType
Handler for ap_done.
typedef void(* XVTpg_Callback)(void *InstancePtr))(void *InstancePtr)
Callback function pointer type for TPG events.
InstancePtr is a pointer to the XV_tpg instance.
int XV_tpg_Initialize(XV_tpg *InstancePtr, UINTPTR BaseAddress)
Initialize the XV_tpg instance.
This function initializes the XV_tpg instance by looking up the device configuration based on the base address and calling the configuration initialization function. InstancePtr Pointer to the XV_tpg instance to initialize BaseAddress Base address of the TPG device to initialize XST_SUCCESS if initialization succeeds XST_DEVICE_NOT_FOUND if device configuration is not found This is the SDT version that uses base address for initialization
References XV_tpg_Config::BaseAddress, XV_tpg::IsReady, XV_tpg_CfgInitialize, XV_tpg_LookupConfig.
XV_tpg_Config* XV_tpg_LookupConfig(UINTPTR BaseAddress)
Look up the device configuration based on the base address.
This function searches the configuration table for the device configuration matching the specified base address. BaseAddress Base address of the TPG device to search for Pointer to XV_tpg_Config structure if found, NULL otherwise This is the SDT version that uses base address for lookup
Referenced by driverInit, XV_tpg_Initialize.
int XV_tpg_CfgInitialize(XV_tpg *InstancePtr, XV_tpg_Config *ConfigPtr, UINTPTR EffectiveAddr)
Configure and initialize the TPG core instance.
This function initializes the TPG instance with the provided configuration and effective base address. It copies the configuration data and sets the ready flag to indicate successful initialization. InstancePtr Pointer to the XV_tpg instance to be initialized ConfigPtr Pointer to the configuration structure EffectiveAddr Effective base address of the TPG hardware XST_SUCCESS on successful initialization This function is only available for non-Linux systems
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg_Config::IntrId, XV_tpg_Config::IntrParent, XV_tpg::IsReady.
Referenced by driverInit, XV_tpg_Initialize.
void XV_tpg_Start(XV_tpg *InstancePtr)
Start the TPG core.
This function starts the TPG core by setting the AP_START bit in the control register while preserving the auto-restart bit. InstancePtr Pointer to the XV_tpg instance None Instance must be initialized and ready before calling this function
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_AP_CTRL, XV_tpg_ReadReg, XV_tpg_WriteReg.
u32 XV_tpg_IsDone(XV_tpg *InstancePtr)
Check if TPG core processing is done.
This function checks the AP_DONE bit in the control register to determine if the current frame processing is complete. InstancePtr Pointer to the XV_tpg instance 1 if processing is done, 0 otherwise None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_AP_CTRL, XV_tpg_ReadReg.
u32 XV_tpg_IsIdle(XV_tpg *InstancePtr)
Check if TPG core is idle.
This function checks the AP_IDLE bit in the control register to determine if the TPG core is in idle state. InstancePtr Pointer to the XV_tpg instance 1 if core is idle, 0 otherwise None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_AP_CTRL, XV_tpg_ReadReg.
u32 XV_tpg_IsReady(XV_tpg *InstancePtr)
Check if TPG core is ready for next input.
This function checks the AP_START bit to determine if the core is ready to accept new input data. InstancePtr Pointer to the XV_tpg instance 1 if ready for next input, 0 if busy None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_AP_CTRL, XV_tpg_ReadReg.
void XV_tpg_EnableAutoRestart(XV_tpg *InstancePtr)
Enable auto-restart mode.
This function enables auto-restart mode for the TPG core, allowing it to automatically restart after each frame completion. InstancePtr Pointer to the XV_tpg instance None None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_AP_CTRL, XV_tpg_WriteReg.
void XV_tpg_DisableAutoRestart(XV_tpg *InstancePtr)
Disable auto-restart mode.
This function disables auto-restart mode for the TPG core. InstancePtr Pointer to the XV_tpg instance None None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_AP_CTRL, XV_tpg_WriteReg.
void XV_tpg_Set_height(XV_tpg *InstancePtr, u32 Data)
Set the height of the output frame.
This function sets the height of the frame to be generated by the TPG core. InstancePtr Pointer to the XV_tpg instance Data Height value in pixels None None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_HEIGHT_DATA, XV_tpg_WriteReg.
Referenced by videoIpConfig.
u32 XV_tpg_Get_height(XV_tpg *InstancePtr)
Get the current height setting.
This function retrieves the current height setting of the TPG core. InstancePtr Pointer to the XV_tpg instance Current height value in pixels None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_HEIGHT_DATA, XV_tpg_ReadReg.
void XV_tpg_Set_width(XV_tpg *InstancePtr, u32 Data)
Set the width of the output frame.
This function sets the width of the frame to be generated by the TPG core. InstancePtr Pointer to the XV_tpg instance Data Width value in pixels None None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_WIDTH_DATA, XV_tpg_WriteReg.
Referenced by videoIpConfig.
u32 XV_tpg_Get_width(XV_tpg *InstancePtr)
Get the current width setting.
This function retrieves the current width setting of the TPG core. InstancePtr Pointer to the XV_tpg instance Current width value in pixels None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_WIDTH_DATA, XV_tpg_ReadReg.
void XV_tpg_Set_bckgndId(XV_tpg *InstancePtr, u32 Data)
Set the background pattern ID.
This function sets the background test pattern ID for the TPG core. InstancePtr Pointer to the XV_tpg instance Data Background pattern ID value None None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_BCKGNDID_DATA, XV_tpg_WriteReg.
Referenced by videoIpConfig.
u32 XV_tpg_Get_bckgndId(XV_tpg *InstancePtr)
Get the current background pattern ID.
This function retrieves the current background pattern ID setting. InstancePtr Pointer to the XV_tpg instance Current background pattern ID value None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_BCKGNDID_DATA, XV_tpg_ReadReg.
Referenced by XV_tpg_Set_motionEn.
void XV_tpg_Set_motionEn(XV_tpg *InstancePtr, u32 Data)
Enable motion for color bar pattern.
This function enables motion animation for the color bar background pattern. InstancePtr Pointer to the XV_tpg instance Data Motion enable value (1 = enable, 0 = disable) None Motion is only applicable when background pattern is set to color bars
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XTPG_BKGND_COLOR_BARS, XV_TPG_CTRL_ADDR_BCK_MOTION_EN_DATA, XV_tpg_Get_bckgndId, XV_tpg_WriteReg.
u32 XV_tpg_Get_motionEnStatus(XV_tpg *InstancePtr)
Get motion enable status for color bar pattern.
This function retrieves the current motion enable status for color bars. InstancePtr Pointer to the XV_tpg instance Motion enable status (1 = enabled, 0 = disabled) None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_BCK_MOTION_EN_DATA, XV_TPG_CTRL_ADDR_MOTION_EN_MASK, XV_tpg_ReadReg.
void XV_tpg_Set_ovrlayId(XV_tpg *InstancePtr, u32 Data)
Set the overlay pattern ID.
This function sets the overlay test pattern ID for the TPG core. InstancePtr Pointer to the XV_tpg instance Data Overlay pattern ID value None None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_OVRLAYID_DATA, XV_tpg_WriteReg.
Referenced by videoIpConfig.
u32 XV_tpg_Get_ovrlayId(XV_tpg *InstancePtr)
Get the current overlay pattern ID.
This function retrieves the current overlay pattern ID setting. InstancePtr Pointer to the XV_tpg instance Current overlay pattern ID value None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_OVRLAYID_DATA, XV_tpg_ReadReg.
void XV_tpg_Set_maskId(XV_tpg *InstancePtr, u32 Data)
Set the color mask ID.
This function sets the color mask ID to control which color components are enabled in the output. InstancePtr Pointer to the XV_tpg instance Data Color mask ID value None None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_MASKID_DATA, XV_tpg_WriteReg.
u32 XV_tpg_Get_maskId(XV_tpg *InstancePtr)
Get the current color mask ID.
This function retrieves the current color mask ID setting. InstancePtr Pointer to the XV_tpg instance Current color mask ID value None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_MASKID_DATA, XV_tpg_ReadReg.
void XV_tpg_Set_motionSpeed(XV_tpg *InstancePtr, u32 Data)
Set the motion speed.
This function sets the variance of the test pattern between consecutive frames when motion is enabled. InstancePtr Pointer to the XV_tpg instance Data Motion speed value None None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_MOTIONSPEED_DATA, XV_tpg_WriteReg.
u32 XV_tpg_Get_motionSpeed(XV_tpg *InstancePtr)
Get the current motion speed setting.
This function retrieves the current motion speed value. InstancePtr Pointer to the XV_tpg instance Current motion speed value None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_MOTIONSPEED_DATA, XV_tpg_ReadReg.
void XV_tpg_Set_colorFormat(XV_tpg *InstancePtr, u32 Data)
Set the color format.
This function sets the color format for the output video stream. InstancePtr Pointer to the XV_tpg instance Data Color format value None None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_COLORFORMAT_DATA, XV_tpg_WriteReg.
Referenced by videoIpConfig.
u32 XV_tpg_Get_colorFormat(XV_tpg *InstancePtr)
Get the current color format setting.
This function retrieves the current color format configuration. InstancePtr Pointer to the XV_tpg instance Current color format value None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_COLORFORMAT_DATA, XV_tpg_ReadReg.
void XV_tpg_Set_crossHairX(XV_tpg *InstancePtr, u32 Data)
Set horizontal crosshair location.
This function sets the horizontal (X) coordinate for the crosshair overlay. InstancePtr Pointer to the XV_tpg instance Data Horizontal crosshair position in pixels None None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_CROSSHAIRX_DATA, XV_tpg_WriteReg.
u32 XV_tpg_Get_crossHairX(XV_tpg *InstancePtr)
Get horizontal crosshair location.
This function retrieves the current horizontal crosshair position. InstancePtr Pointer to the XV_tpg instance Current horizontal crosshair position in pixels None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_CROSSHAIRX_DATA, XV_tpg_ReadReg.
void XV_tpg_Set_crossHairY(XV_tpg *InstancePtr, u32 Data)
Set vertical crosshair location.
This function sets the vertical (Y) coordinate for the crosshair overlay. InstancePtr Pointer to the XV_tpg instance Data Vertical crosshair position in pixels None None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_CROSSHAIRY_DATA, XV_tpg_WriteReg.
u32 XV_tpg_Get_crossHairY(XV_tpg *InstancePtr)
Get vertical crosshair location.
This function retrieves the current vertical crosshair position. InstancePtr Pointer to the XV_tpg instance Current vertical crosshair position in pixels None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_CROSSHAIRY_DATA, XV_tpg_ReadReg.
void XV_tpg_Set_ZplateHorContStart(XV_tpg *InstancePtr, u32 Data)
Set zone plate horizontal control start value.
This function sets the horizontal component starting point based on sinusoidal values for the zone plate test pattern. InstancePtr Pointer to the XV_tpg instance Data Horizontal control start value None None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_ZPLATEHORCONTSTART_DATA, XV_tpg_WriteReg.
u32 XV_tpg_Get_ZplateHorContStart(XV_tpg *InstancePtr)
Get zone plate horizontal control start value.
This function retrieves the current horizontal control start value. InstancePtr Pointer to the XV_tpg instance Current horizontal control start value None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_ZPLATEHORCONTSTART_DATA, XV_tpg_ReadReg.
void XV_tpg_Set_ZplateHorContDelta(XV_tpg *InstancePtr, u32 Data)
Set zone plate horizontal control delta value.
This function sets the variance (delta) between horizontal components for the zone plate pattern. InstancePtr Pointer to the XV_tpg instance Data Horizontal control delta value None None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_ZPLATEHORCONTDELTA_DATA, XV_tpg_WriteReg.
u32 XV_tpg_Get_ZplateHorContDelta(XV_tpg *InstancePtr)
Get zone plate horizontal control delta value.
This function retrieves the current horizontal control delta value. InstancePtr Pointer to the XV_tpg instance Current horizontal control delta value None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_ZPLATEHORCONTDELTA_DATA, XV_tpg_ReadReg.
void XV_tpg_Set_ZplateVerContStart(XV_tpg *InstancePtr, u32 Data)
Set zone plate vertical control start value.
This function sets the vertical component starting point based on sinusoidal values for the zone plate test pattern. InstancePtr Pointer to the XV_tpg instance Data Vertical control start value None None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_ZPLATEVERCONTSTART_DATA, XV_tpg_WriteReg.
u32 XV_tpg_Get_ZplateVerContStart(XV_tpg *InstancePtr)
Get zone plate vertical control start value.
This function retrieves the current vertical control start value. InstancePtr Pointer to the XV_tpg instance Current vertical control start value None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_ZPLATEVERCONTSTART_DATA, XV_tpg_ReadReg.
void XV_tpg_Set_ZplateVerContDelta(XV_tpg *InstancePtr, u32 Data)
Set zone plate vertical control delta value.
This function sets the variance (delta) between vertical components for the zone plate pattern. InstancePtr Pointer to the XV_tpg instance Data Vertical control delta value None None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_ZPLATEVERCONTDELTA_DATA, XV_tpg_WriteReg.
u32 XV_tpg_Get_ZplateVerContDelta(XV_tpg *InstancePtr)
Get zone plate vertical control delta value.
This function retrieves the current vertical control delta value. InstancePtr Pointer to the XV_tpg instance Current vertical control delta value None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_ZPLATEVERCONTDELTA_DATA, XV_tpg_ReadReg.
void XV_tpg_Set_boxSize(XV_tpg *InstancePtr, u32 Data)
Set the box size.
This function sets the size of the foreground box overlay. InstancePtr Pointer to the XV_tpg instance Data Box size value in pixels None None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_BOXSIZE_DATA, XV_tpg_WriteReg.
u32 XV_tpg_Get_boxSize(XV_tpg *InstancePtr)
Get the current box size.
This function retrieves the current box size setting. InstancePtr Pointer to the XV_tpg instance Current box size value in pixels None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_BOXSIZE_DATA, XV_tpg_ReadReg.
void XV_tpg_Set_boxColorR(XV_tpg *InstancePtr, u32 Data)
Set box red color component.
This function sets the Y or R (red/luma) component value for the box overlay. InstancePtr Pointer to the XV_tpg instance Data Red/luma component value None None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_BOXCOLORR_DATA, XV_tpg_WriteReg.
u32 XV_tpg_Get_boxColorR(XV_tpg *InstancePtr)
Get box red color component.
This function retrieves the Y or R component value of the box. InstancePtr Pointer to the XV_tpg instance Current red/luma component value None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_BOXCOLORR_DATA, XV_tpg_ReadReg.
void XV_tpg_Set_boxColorG(XV_tpg *InstancePtr, u32 Data)
Set box green color component.
This function sets the U or G (green/chroma U) component value for the box. InstancePtr Pointer to the XV_tpg instance Data Green/chroma U component value None None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_BOXCOLORG_DATA, XV_tpg_WriteReg.
u32 XV_tpg_Get_boxColorG(XV_tpg *InstancePtr)
Get box green color component.
This function retrieves the U or G component value of the box. InstancePtr Pointer to the XV_tpg instance Current green/chroma U component value None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_BOXCOLORG_DATA, XV_tpg_ReadReg.
void XV_tpg_Set_boxColorB(XV_tpg *InstancePtr, u32 Data)
Set box blue color component.
This function sets the V or B (blue/chroma V) component value for the box. InstancePtr Pointer to the XV_tpg instance Data Blue/chroma V component value None None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_BOXCOLORB_DATA, XV_tpg_WriteReg.
u32 XV_tpg_Get_boxColorB(XV_tpg *InstancePtr)
Get box blue color component.
This function retrieves the V or B component value of the box. InstancePtr Pointer to the XV_tpg instance Current blue/chroma V component value None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_BOXCOLORB_DATA, XV_tpg_ReadReg.
void XV_tpg_Set_enableInput(XV_tpg *InstancePtr, u32 Data)
Enable input video stream passthrough.
This function enables the input video stream passthrough mode. InstancePtr Pointer to the XV_tpg instance Data Enable value (1 = enable, 0 = disable) None None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_ENABLEINPUT_DATA, XV_TPG_CTRL_ADDR_FIELDID_DATA, XV_TPG_CTRL_ADDR_FIELDID_PASSTHR_MASK, XV_TPG_CTRL_ADDR_FIELDID_PASSTHR_SHIFT, XV_tpg_Get_fieldId, XV_tpg_WriteReg.
Referenced by videoIpConfig.
u32 XV_tpg_Get_enableInput(XV_tpg *InstancePtr)
Get input enable status.
This function retrieves the current input video stream enable status. InstancePtr Pointer to the XV_tpg instance Current enable status (1 = enabled, 0 = disabled) None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_ENABLEINPUT_DATA, XV_tpg_ReadReg.
void XV_tpg_Set_passthruStartX(XV_tpg *InstancePtr, u32 Data)
Set passthrough window left boundary.
This function sets the left (starting X) boundary of the passthrough window. InstancePtr Pointer to the XV_tpg instance Data Left boundary X coordinate in pixels None None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_PASSTHRUSTARTX_DATA, XV_tpg_WriteReg.
Referenced by videoIpConfig.
u32 XV_tpg_Get_passthruStartX(XV_tpg *InstancePtr)
Get passthrough window left boundary.
This function retrieves the current left boundary of the passthrough window. InstancePtr Pointer to the XV_tpg instance Current left boundary X coordinate None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_PASSTHRUSTARTX_DATA, XV_tpg_ReadReg.
void XV_tpg_Set_passthruStartY(XV_tpg *InstancePtr, u32 Data)
Set passthrough window upper boundary.
This function sets the upper (starting Y) boundary of the passthrough window. InstancePtr Pointer to the XV_tpg instance Data Upper boundary Y coordinate in pixels None None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_PASSTHRUSTARTY_DATA, XV_tpg_WriteReg.
Referenced by videoIpConfig.
u32 XV_tpg_Get_passthruStartY(XV_tpg *InstancePtr)
Get passthrough window upper boundary.
This function retrieves the current upper boundary of the passthrough window. InstancePtr Pointer to the XV_tpg instance Current upper boundary Y coordinate None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_PASSTHRUSTARTY_DATA, XV_tpg_ReadReg.
void XV_tpg_Set_passthruEndX(XV_tpg *InstancePtr, u32 Data)
Set passthrough window right boundary.
This function sets the right (ending X) boundary of the passthrough window. InstancePtr Pointer to the XV_tpg instance Data Right boundary X coordinate in pixels None None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_PASSTHRUENDX_DATA, XV_tpg_WriteReg.
Referenced by videoIpConfig.
u32 XV_tpg_Get_passthruEndX(XV_tpg *InstancePtr)
Get passthrough window right boundary.
This function retrieves the current right boundary of the passthrough window. InstancePtr Pointer to the XV_tpg instance Current right boundary X coordinate None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_PASSTHRUENDX_DATA, XV_tpg_ReadReg.
void XV_tpg_Set_passthruEndY(XV_tpg *InstancePtr, u32 Data)
Set passthrough window lower boundary.
This function sets the lower (ending Y) boundary of the passthrough window. InstancePtr Pointer to the XV_tpg instance Data Lower boundary Y coordinate in pixels None None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_PASSTHRUENDY_DATA, XV_tpg_WriteReg.
Referenced by videoIpConfig.
u32 XV_tpg_Get_passthruEndY(XV_tpg *InstancePtr)
Get passthrough window lower boundary.
This function retrieves the current lower boundary of the passthrough window. InstancePtr Pointer to the XV_tpg instance Current lower boundary Y coordinate None
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_PASSTHRUENDY_DATA, XV_tpg_ReadReg.
void XV_tpg_Set_dpDynamicRange(XV_tpg *InstancePtr, u32 Data)
Sets the dynamic range of DisplayPort color square in RGB.
InstancePtr is a pointer to the XV_tpg instance. Data is the dynamic range value to be set. None. Asserts if the pointer is NULL or instance is not ready.
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_DPDYNAMICRANGE_DATA, XV_tpg_WriteReg.
u32 XV_tpg_Get_dpDynamicRange(XV_tpg *InstancePtr)
Gets the dynamic range of DisplayPort color square in RGB.
InstancePtr is a pointer to the XV_tpg instance. The dynamic range value of DisplayPort color square in RGB. Asserts if the pointer is NULL or instance is not ready.
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_DPDYNAMICRANGE_DATA, XV_tpg_ReadReg.
void XV_tpg_Set_dpYUVCoef(XV_tpg *InstancePtr, u32 Data)
Sets the coefficients of DisplayPort color square in YUV.
InstancePtr is a pointer to the XV_tpg instance. Data is the YUV coefficient value to be set. None. Asserts if the pointer is NULL or instance is not ready.
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_DPYUVCOEF_DATA, XV_tpg_WriteReg.
u32 XV_tpg_Get_dpYUVCoef(XV_tpg *InstancePtr)
Gets the coefficients of DisplayPort color square in YUV.
InstancePtr is a pointer to the XV_tpg instance. The YUV coefficient value of DisplayPort color square. Asserts if the pointer is NULL or instance is not ready.
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_DPYUVCOEF_DATA, XV_tpg_ReadReg.
void XV_tpg_Set_Interlaced(XV_tpg *InstancePtr, _Bool Data)
Enables or disables the interlaced video pattern.
InstancePtr is a pointer to the XV_tpg instance. Data is a boolean value to enable (TRUE) or disable (FALSE) interlaced mode. None. Asserts if the pointer is NULL or instance is not ready.
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_FIELDID_DATA, XV_TPG_CTRL_ADDR_FIELDID_INTERLACED_MASK, XV_TPG_CTRL_ADDR_FIELDID_INTERLACED_SHIFT, XV_tpg_Get_fieldId, XV_tpg_WriteReg.
void XV_tpg_Set_Polarity(XV_tpg *InstancePtr, _Bool Data)
Sets the field polarity for interlaced video.
InstancePtr is a pointer to the XV_tpg instance. Data is a boolean value to set the field polarity. None. Asserts if the pointer is NULL or instance is not ready.
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_FIELDID_DATA, XV_TPG_CTRL_ADDR_FIELDID_POLARITY_MASK, XV_TPG_CTRL_ADDR_FIELDID_POLARITY_SHIFT, XV_tpg_Get_fieldId, XV_tpg_WriteReg.
u32 XV_tpg_Get_fieldId(XV_tpg *InstancePtr)
Gets the field ID for the current frame.
InstancePtr is a pointer to the XV_tpg instance. The field ID value. Asserts if the pointer is NULL or instance is not ready.
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_FIELDID_DATA, XV_tpg_ReadReg.
Referenced by XV_tpg_Set_enableInput, XV_tpg_Set_Interlaced, XV_tpg_Set_Polarity.
void XV_tpg_InterruptGlobalEnable(XV_tpg *InstancePtr)
Enables the global interrupts.
InstancePtr is a pointer to the XV_tpg instance. None. Asserts if the pointer is NULL or instance is not ready.
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_GIE, XV_tpg_WriteReg.
void XV_tpg_InterruptGlobalDisable(XV_tpg *InstancePtr)
Disables the global interrupts.
InstancePtr is a pointer to the XV_tpg instance. None. Asserts if the pointer is NULL or instance is not ready.
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_GIE, XV_tpg_WriteReg.
void XV_tpg_InterruptEnable(XV_tpg *InstancePtr, u32 Mask)
Enables the interrupts specified by the mask.
InstancePtr is a pointer to the XV_tpg instance. Mask is the interrupt mask value to enable specific interrupts. None. Asserts if the pointer is NULL or instance is not ready.
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_IER, XV_tpg_ReadReg, XV_tpg_WriteReg.
void XV_tpg_InterruptDisable(XV_tpg *InstancePtr, u32 Mask)
Disables the interrupts specified by the mask.
InstancePtr is a pointer to the XV_tpg instance. Mask is the interrupt mask value to disable specific interrupts. None. Asserts if the pointer is NULL or instance is not ready.
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_IER, XV_tpg_ReadReg, XV_tpg_WriteReg.
void XV_tpg_InterruptClear(XV_tpg *InstancePtr, u32 Mask)
Clears the interrupts specified by the mask.
InstancePtr is a pointer to the XV_tpg instance. Mask is the interrupt mask value to clear specific interrupts. None. Asserts if the pointer is NULL or instance is not ready.
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_ISR, XV_tpg_WriteReg.
Referenced by XVTpg_InterruptHandler.
u32 XV_tpg_InterruptGetEnabled(XV_tpg *InstancePtr)
Reports the currently enabled interrupts.
InstancePtr is a pointer to the XV_tpg instance. The current interrupt enable status mask. Asserts if the pointer is NULL or instance is not ready.
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_IER, XV_tpg_ReadReg.
u32 XV_tpg_InterruptGetStatus(XV_tpg *InstancePtr)
Reports the current interrupt status.
InstancePtr is a pointer to the XV_tpg instance. The current interrupt status mask. Asserts if the pointer is NULL or instance is not ready.
References XV_tpg_Config::BaseAddress, XV_tpg::Config, XV_tpg::IsReady, XV_TPG_CTRL_ADDR_ISR, XV_tpg_ReadReg.
Referenced by XVTpg_InterruptHandler.
void XVTpg_SetCallback(XV_tpg *InstancePtr, u32 HandlerType, void *CallbackFunc, void *CallbackRef)
Install an asynchronous callback function for interrupt handling.
This function installs an asynchronous callback function for the given HandlerType: HandlerType Callback Function Type (XVTPG_HANDLER_DONE) DoneCallback (XVTPG_HANDLER_READY) ReadyCallback InstancePtr is a pointer to the tpg IP instance. HandlerType is the type of handler to be installed (DONE or READY). CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. None Invoking this function for a handler that already has been installed replaces it with the new handler.
References XVTPG_HANDLER_DONE, XV_tpg::FrameDoneCallback, XV_tpg::CallbackDoneRef, XVTPG_HANDLER_READY, XV_tpg::FrameReadyCallback, XV_tpg::CallbackReadyRef.
void XVTpg_InterruptHandler(XV_tpg *InstancePtr)
This function is the interrupt handler for the TPG core driver.
This handler clears the pending interrupt and determined if the source is frame done signal. If yes, starts the next frame processing and calls the registered callback functionThe application is responsible for connecting this function to the interrupt system. Application beyond this driver is also responsible for providing callbacks to handle interrupts and installing the callbacks using XVTpg_SetCallback() during initialization phase. InstancePtr is a pointer to the core instance that just interrupted. None. None.
References XV_tpg::IsReady, XV_tpg_InterruptGetStatus, XVTPG_IRQ_DONE_MASK, XV_tpg_InterruptClear, XV_tpg::FrameDoneCallback, XV_tpg::CallbackDoneRef, XVTPG_IRQ_READY_MASK, XV_tpg::FrameReadyCallback, XV_tpg::CallbackReadyRef.