prc
XPRC_DEBUG_GENERAL
xprc_dbg_current_types
xprc_dbgcore_current_types
xprc_printf
xprc_core_printf
XPRC_MAX_NUMBER_OF_VSMS
Maximum Number Of Vsms.
Referenced by XPrc_GetBsAddress, XPrc_GetBsId, XPrc_GetBsSize, XPrc_GetRmBsIndex, XPrc_GetRmClearingBsIndex, XPrc_GetRmControl, XPrc_GetTriggerToRmMapping, XPrc_IsSwTriggerPending, XPrc_ReadStatusReg, XPrc_SendProceedCommand, XPrc_SendRestartWithNoStatusCommand, XPrc_SendRestartWithStatusCommand, XPrc_SendShutdownCommand, XPrc_SendSwTrigger, XPrc_SendUserControlCommand, XPrc_SetBsAddress, XPrc_SetBsId, XPrc_SetBsSize, XPrc_SetRmBsIndex, XPrc_SetRmClearingBsIndex, XPrc_SetRmControl, XPrc_SetTriggerToRmMapping.
XPRC_VSM_NUM_GENERAL_REGISTERS
Number Of General registers.
XPRC_VSM_REGISTERS_PER_TRIGGER
Registers per Trigger.
XPRC_VSM_REGISTERS_PER_RM
Registers per Rm.
XPRC_VSM_REGISTERS_PER_BS
Registers per Bs.
XPRC_CR_VS_FULL
Virtual Socket In Full State.
Referenced by Xprc_Check_RestartWithStatus_Command, XPrc_SendRestartWithStatusCommand.
XPRC_CR_VS_EMPTY
Virtual Socket In Empty State.
Referenced by Xprc_Check_RestartWithStatus_Command, XPrc_SendRestartWithStatusCommand.
XPRC_CR_DEFAULT_BYTE
Byte field Information for Control register Commands.
Referenced by XPrc_SendProceedCommand, XPrc_SendRestartWithNoStatusCommand, XPrc_SendShutdownCommand.
XPRC_CR_DEFAULT_HALFWORD
Halfword field information for Control register Commands.
Referenced by XPrc_SendProceedCommand, XPrc_SendRestartWithNoStatusCommand, XPrc_SendShutdownCommand, XPrc_SendUserControlCommand.
XPRC_SR_SHUTDOWN_ON
Vsm In Shutdown State.
Referenced by XPrc_IsVsmInShutdown.
XPRC_SR_SHUTDOWN_OFF
Vsm not In Shutdown State.
Referenced by XPrc_IsVsmInShutdown.
XPRC_SW_TRIGGER_PENDING
Software Trigger is Pending.
Referenced by XPrc_IsSwTriggerPending.
XPRC_NO_SW_TRIGGER_PENDING
Software Trigger is not Pending.
Referenced by XPrc_IsSwTriggerPending.
XPRC_RM_CR_MAX_RESETDURATION
Maximum Number of Reset duration.
Referenced by XPrc_SetRmControl.
XPRC_REG_TABLE_ROW
Register Table Row.
Referenced by XPrc_IsSwTriggerPending, XPrc_ReadStatusReg, XPrc_SelfTest, XPrc_SendSwTrigger.
CP_FIFO_TYPE_LUTRAM
Fifo Value for Lutram.
CP_FIFO_TYPE_BLOCKRAM
Fifo Value for Blockram.
XPRC_VSM_GENERAL_REG_BANK
General registers.
Referenced by XPrc_GetRegisterAddress.
XPRC_VSM_TRIGGER_REG_BANK
Trigger to Rm register.
Referenced by XPrc_GetRegisterAddress.
XPRC_VSM_RM_REG_BANK
Rm Information register.
Referenced by XPrc_GetRegisterAddress.
XPRC_VSM_BS_REG_BANK
Bs Information register.
Referenced by XPrc_GetRegisterAddress.
XPRC_DEFAULT_BANKID
Default Bank Identifier.
Referenced by XPrc_GetRegisterAddress.
XPRC_STATUS_REG_TABLE_ID
Status register Table ID.
Referenced by XPrc_GetRegisterAddress.
XPRC_CONTROL_REG_TABLE_ID
Control register Table ID.
Referenced by XPrc_GetRegisterAddress.
XPRC_SW_TRIGGER_REG_TABLE_ID
Sw Trigger register Table ID.
Referenced by XPrc_GetRegisterAddress.
XPRC_TRIGGER_REG_TABLE_ID
Trigger register Table ID.
Referenced by XPrc_GetRegisterAddress.
XPRC_RM_BS_INDEX_REG_TABLE_ID
RmBs Index register Table ID.
Referenced by XPrc_GetRegisterAddress.
XPRC_RM_CONTROL_REG_TABLE_ID
Rm Control register Table ID.
Referenced by XPrc_GetRegisterAddress.
XPRC_BS_ID_REG_TABLE_ID
Bs Identifier register Table ID.
Referenced by XPrc_GetRegisterAddress.
XPRC_BS_ADDRESS_REG_TABLE_ID
Bs Address register Table ID.
Referenced by XPrc_GetRegisterAddress.
XPRC_BS_SIZE_REG_TABLE_ID
Bs Size register Table ID.
Referenced by XPrc_GetRegisterAddress.
XPRC_DEFAULT_TABLEID
Default Table Identifier within the Bank.
Referenced by XPrc_GetRegisterAddress.
XPRC_STATUS_REG
Status register.
Referenced by XPrc_GetRegisterAddress, XPrc_ReadStatusReg, XPrc_SelfTest.
XPRC_CONTROL_REG
Control register.
Referenced by XPrc_GetRegisterAddress.
XPRC_SW_TRIGGER_REG
Sw Trigger register.
Referenced by XPrc_GetRegisterAddress, XPrc_IsSwTriggerPending, XPrc_SendSwTrigger.
XPRC_TRIGGER_REG
Trigger register.
Referenced by XPrc_GetRegisterAddress, XPrc_GetTriggerToRmMapping, XPrc_SetTriggerToRmMapping.
XPRC_RM_BS_INDEX_REG
RmBs Index register.
Referenced by XPrc_GetRegisterAddress, XPrc_GetRmBsIndex, XPrc_GetRmClearingBsIndex, XPrc_SetRmBsIndex, XPrc_SetRmClearingBsIndex.
XPRC_RM_CONTROL_REG
Rm Control register.
Referenced by XPrc_GetRegisterAddress, XPrc_GetRmControl, XPrc_SetRmControl.
XPRC_BS_ID_REG
Bs Identifier register.
Referenced by XPrc_GetBsId, XPrc_GetRegisterAddress, XPrc_SetBsId.
XPRC_BS_ADDRESS_REG
Bs Address register.
Referenced by XPrc_GetBsAddress, XPrc_GetRegisterAddress, XPrc_SetBsAddress.
XPRC_BS_SIZE_REG
Bs Size register.
Referenced by XPrc_GetBsSize, XPrc_GetRegisterAddress, XPrc_SetBsSize.
XPRC_CR_SHUTDOWN_CMD
Shutdown Command.
Referenced by XPrc_SendShutdownCommand.
XPRC_CR_RESTART_NO_STATUS_CMD
Restart With No Status Command.
Referenced by XPrc_SendRestartWithNoStatusCommand.
XPRC_CR_RESTART_WITH_STATUS_CMD
Restart With Status Command.
Referenced by XPrc_SendRestartWithStatusCommand.
XPRC_CR_OK_TO_PROCEED_CMD
Proceed Command.
Referenced by XPrc_SendProceedCommand.
XPRC_CR_USER_CTRL_CMD
User Control Command.
Referenced by XPrc_SendUserControlCommand.
XPRC_CR_CMD_FIELD_LSB
Command Field LSB.
XPRC_CR_CMD_FIELD_WIDTH
Command Field Width.
XPRC_CR_CMD_FIELD_MSB
Command Field MSB.
XPRC_CR_BYTE_FIELD_LSB
Byte Field LSB.
XPRC_CR_BYTE_FIELD_WIDTH
Byte Field Width.
XPRC_CR_BYTE_FIELD_MSB
Byte Field MSB.
XPRC_CR_HALFWORD_FIELD_LSB
Halfword Field LSB.
XPRC_CR_HALFWORD_FIELD_WIDTH
Halfword Field Width.
XPRC_CR_HALFWORD_FIELD_MSB
Halfword Field MSB.
XPRC_CR_USER_CONTROL_RM_SHUTDOWN_REQ_BIT
Rm Shutdown Required.
Referenced by Xprc_Check_User_Command.
XPRC_CR_USER_CONTROL_RM_DECOUPLE_BIT
Rm Decouple.
Referenced by Xprc_Check_User_Command, XPrc_SendUserControlCommand.
XPRC_CR_USER_CONTROL_SW_SHUTDOWN_REQ_BIT
Sw_Shutdown Required.
Referenced by Xprc_Check_User_Command, XPrc_SendUserControlCommand.
XPRC_CR_USER_CONTROL_SW_STARTUP_REQ_BIT
Sw Startup Required.
Referenced by Xprc_Check_User_Command, XPrc_SendUserControlCommand.
XPRC_CR_USER_CONTROL_RM_RESET_BIT
Rm Reset.
Referenced by Xprc_Check_User_Command, XPrc_SendUserControlCommand.
XPRC_SR_SHUTDOWN_MASK
Shutdown State Mask.
Referenced by XPrc_IsVsmInShutdown.
XPRC_SR_STATE_MASK
Vsm State Mask.
Referenced by XPrc_GetVsmState.
XPRC_SR_STATE_EMPTY
Empty State Of VSM.
Referenced by Xprc_Check_RestartWithStatus_Command, XPrc_PrintVsmStatus.
XPRC_SR_STATE_HW_SHUTDOWN
Hardware Shutdown State of VSM.
Referenced by XPrc_PrintVsmStatus.
XPRC_SR_STATE_SW_SHUTDOWN
Software Shutdown State of VSM.
Referenced by XPrc_PrintVsmStatus.
XPRC_SR_STATE_RM_UNLOAD
Reconfigurable Module Unload State Of VSM.
Referenced by XPrc_PrintVsmStatus.
XPRC_SR_STATE_RM_LOAD
Reconfigurable Module Load State Of VSM.
Referenced by XPrc_PrintVsmStatus.
XPRC_SR_STATE_SW_STARTUP
Software Startup State of VSM.
Referenced by XPrc_PrintVsmStatus.
XPRC_SR_STATE_RM_RESET
Reset State of VSM.
Referenced by XPrc_PrintVsmStatus.
XPRC_SR_STATE_FULL
Full State Of VSM.
Referenced by Xprc_Check_RestartWithStatus_Command, XPrc_Example, XPrc_PrintVsmStatus.
XPRC_SR_ERROR_SHIFT
Error Shift.
Referenced by XPrc_GetVsmErrorStatus.
XPRC_SR_ERROR_MASK
Error Codes Mask.
Referenced by XPrc_GetVsmErrorStatus.
XPRC_SR_UNKNOWN_ERROR
Unknown Error.
XPRC_SR_BS_COMPATIBLE_ERROR
Bitstream Compatible Error.
Referenced by XPrc_PrintVsmStatus.
XPRC_SR_DECOMPRESS_BAD_FORMAT_ERROR
Bad compression format error.
Referenced by XPrc_PrintVsmStatus.
XPRC_SR_DECOMPRESS_BAD_SIZE_ERROR
Bad compression size error.
Referenced by XPrc_PrintVsmStatus.
XPRC_SR_FETCH_AND_CP_LOST_ERROR
Fetch and Lost Error.
Referenced by XPrc_PrintVsmStatus.
XPRC_SR_FETCH_AND_BS_ERROR
Fetch and Bitstream Error.
Referenced by XPrc_PrintVsmStatus.
XPRC_SR_FETCH_ERROR
Fetch Error.
Referenced by XPrc_PrintVsmStatus.
XPRC_SR_CP_LOST_ERROR
CP Lost Error.
Referenced by XPrc_PrintVsmStatus.
XPRC_SR_BS_ERROR
Bitstream Error.
Referenced by XPrc_PrintVsmStatus.
XPRC_SR_BAD_CONFIG_ERROR
Bad Configuration Error.
Referenced by XPrc_PrintVsmStatus.
XPRC_SR_NO_ERROR
No Error.
Referenced by XPrc_PrintVsmStatus.
XPRC_SR_RMID_SHIFT
Rm Identifier Shift.
Referenced by XPrc_GetRmIdFromStatus.
XPRC_SR_RMID_MASK
Rm Identifier Mask.
Referenced by XPrc_GetRmIdFromStatus.
XPRC_SR_BSID_SHIFT
Bs Identifier Shift.
Referenced by XPrc_GetBsIdFromStatus.
XPRC_SR_BSID_MASK
Bs Identifier Mask.
Referenced by XPrc_GetBsIdFromStatus.
XPRC_SW_TRIGGER_ID_MASK
Sw Trigger Id Mask.
Referenced by XPrc_IsSwTriggerPending.
XPRC_SW_TRIGGER_PENDING_MASK
Sw Trigger Pending Mask.
Referenced by XPrc_IsSwTriggerPending.
XPRC_RM_BS_INDEX_SHIFT
Rm Bs Index Shift.
XPRC_RM_BS_INDEX_MASK
Rm Bs Index Mask.
Referenced by XPrc_GetRmBsIndex.
XPRC_RM_CLEARING_BS_INDEX_SHIFT
Clearing Bs Index Shift.
Referenced by XPrc_GetRmClearingBsIndex, XPrc_SetRmClearingBsIndex.
XPRC_RM_CLEARING_BS_INDEX_MASK
Clearing Bs Index Mask.
XPRC_RM_CR_SHUTDOWN_REQUIRED_SHIFT
Shutdown Required Shift.
Referenced by XPrc_GetRmControl, XPrc_SetRmControl.
XPRC_RM_CR_STARTUP_REQUIRED_SHIFT
Startup Required Shift.
Referenced by XPrc_GetRmControl, XPrc_SetRmControl.
XPRC_RM_CR_RESET_REQUIRED_SHIFT
Reset Required Shift.
Referenced by XPrc_GetRmControl, XPrc_SetRmControl.
XPRC_RM_CR_RESET_DURATION_SHIFT
Reset Duration Shift.
Referenced by XPrc_GetRmControl, XPrc_SetRmControl.
XPRC_RM_CR_SHUTDOWN_REQUIRED_MASK
Shutdown Required Mask.
Referenced by XPrc_GetRmControl, XPrc_SetRmControl.
XPRC_RM_CR_STARTUP_REQUIRED_MASK
Startup Required Mask.
Referenced by XPrc_GetRmControl, XPrc_SetRmControl.
XPRC_RM_CR_RESET_REQUIRED_MASK
Reset Required Mask.
Referenced by XPrc_GetRmControl, XPrc_SetRmControl.
XPRC_RM_CR_RESET_DURATION_MASK
Reset Duration Mask.
Referenced by XPrc_GetRmControl, XPrc_SetRmControl.
XPRC_RM_CR_NO_SHUTDOWN_REQUIRED
No Shutdown Required.
XPRC_RM_CR_HW_SHUTDOWN_REQUIRED
Hardware Only Shutdown Required.
XPRC_RM_CR_HW_SW_SHUTDOWN_REQUIRED
Hardware Shutdown and then Software Shutdown Required.
XPRC_RM_CR_SW_HW_SHUTDOWN_REQUIRED
Software Shutdown and then Hardware Shutdown Required.
Referenced by XPrc_SetRmControl.
XPRC_RM_CR_STARTUP_NOT_REQUIRED
Startup Not Required.
Referenced by XPrc_SetRmControl.
XPRC_RM_CR_SW_STARTUP_REQUIRED
Software Only Startup Required.
Referenced by XPrc_SetRmControl.
XPRC_RM_CR_NO_RESET_REQUIRED
No Reset Required.
XPRC_RM_CR_LOW_RESET_REQUIRED
Low Reset Required.
XPRC_RM_CR_HIGH_RESET_REQUIRED
High Reset Required.
Referenced by XPrc_SetRmControl.
XPrc_Config XPrc_ConfigTable[][]
static u32 XPrc_GetRegisterOffset(XPrc *InstancePtr, u32 VsmId, u8 BankId, u8 TableInBank, u8 TableRow)
This function used to build the offset address for a register in a VSM.
The register addresses are encoded as follows: [VSM Selector] [Bank Selector] [Row in the table][table][00]VSM Selector : The ID of the VSM. 0 = VSM0, 1 = VSM1, etc Table Selector : There are 4 tables of registers in each VSM. 3 are implemented as LUTRAM and 1 is just implemented using flops. General Registers (Flops)Trigger to RM Mapping Table (LUTRAM)RM Information Table (LUTRAM)BS Information Table (LUTRAM) Row in the table : This is the address of the register within the table.Table : The RM and BS banks implement several types of registers, each using its own LUTRAM table. This field specifies which LUTRAM to access. InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. BankId is an identifier to represent the bank of registers to access. TableInBank is the table within the bank register. TableRow is the address of the register within the table. Offset of the register. None.
static void XPrc_SendCommand(XPrc *InstancePtr, u16 VsmId, u8 Cmd, u8 Byte, u16 Halfword)
This function sends a command(Shutdown, Restart With No Status, Restart With Status, Proceed, User Control) to a Virtual Socket Manager.
InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. Cmd is a Control Register command (Shutdown, Restart with no Status, Restart with Status, Proceed, User control). Byte is an 8-bit field containing extra information for the selected command. Halfword is a 16-bit field containing extra information for the selected command. None. None.
static u16 XPrc_GetOffsetForTableType(u8 TableId)
This function works out the register offset within a bank for a given register table.
Registers in the PRC are organised into banks. Some banks only have one type of register. Some banks have multiple types of registers. TableId is the register table. Offset for the table within a bank. None.
s32 XPrc_CfgInitialize(XPrc *InstancePtr, XPrc_Config *ConfigPtr, u32 EffectiveAddr)
This function initializes a PRC instance.
InstancePtr is a pointer to the PRC instance. ConfigPtr points to the XPrc device configuration structure. EffectiveAddr is the device base address in the virtual memory address space. If the address translation is not used then the physical address should be passed. XST_SUCCESS if initialisation was successful. None.
References XPrc::Config, XPrc::IsReady.
Referenced by XPrc_Example, XPrc_SelfTestExample.
void XPrc_SendShutdownCommand(XPrc *InstancePtr, u16 VsmId)
This function instructs the Virtual Socket Manager to enter the shutdown state.
InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. None. None.
References XPrc::IsReady, XPRC_CR_DEFAULT_BYTE, XPRC_CR_DEFAULT_HALFWORD, XPRC_CR_SHUTDOWN_CMD, XPRC_MAX_NUMBER_OF_VSMS.
Referenced by Xprc_Check_RestartWithStatus_Command, XPrc_Example.
void XPrc_SendRestartWithNoStatusCommand(XPrc *InstancePtr, u16 VsmId)
This function is used to restart a Virtual Socket Manager in shutdown if the Virtual Socket has not been modified during shutdown.
InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. None. None.
References XPrc::IsReady, XPRC_CR_DEFAULT_BYTE, XPRC_CR_DEFAULT_HALFWORD, XPRC_CR_RESTART_NO_STATUS_CMD, XPRC_MAX_NUMBER_OF_VSMS.
Referenced by Xprc_Check_RestartWithStatus_Command, Xprc_Restart_VSMs.
void XPrc_SendRestartWithStatusCommand(XPrc *InstancePtr, u16 VsmId, u8 Full, u16 RmId)
This function is used to restart a Virtual Socket Manager in shutdown if the Virtual Socket has been modified during shutdown.
InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. Full = 0, if Virtual Socket is empty, Full = 1, if Virtual Socket is full. RmId is the identifier of the Reconfigurable Module loaded while the VSM was in shutdown. None. None.
References XPrc::IsReady, XPRC_CR_RESTART_WITH_STATUS_CMD, XPRC_CR_VS_EMPTY, XPRC_CR_VS_FULL, XPRC_MAX_NUMBER_OF_VSMS.
Referenced by Xprc_Check_RestartWithStatus_Command.
void XPrc_SendProceedCommand(XPrc *InstancePtr, u16 VsmId)
This function instructs the Virtual Socket Manager to proceed with processing the Reconfigurable Module.
InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. None. None.
References XPrc::IsReady, XPRC_CR_DEFAULT_BYTE, XPRC_CR_DEFAULT_HALFWORD, XPRC_CR_OK_TO_PROCEED_CMD, XPRC_MAX_NUMBER_OF_VSMS.
void XPrc_SendUserControlCommand(XPrc *InstancePtr, u16 VsmId, u8 Rm_Shutdown_Req, u8 Rm_Decouple, u8 Sw_Shutdown_Req, u8 Sw_Startup_Req, u8 Rm_Reset)
This function is used to set the values of Rm_Shutdown_Req, Rm_Decouple, Sw_Shutdown_Req, Sw_Startup_Req, Rm_Reset signals.
It can only be used when the VSM is in the shutdown state. InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. Rm_Shutdown_Req => Set to 1 to inform the RM Reconfigurable Module that it is to be removed. Rm_Decouple => Set to 1 to enable any external Virtual Socket decoupling logic. Sw_Shutdown_Req => Set to 1 to inform software that the active Reconfigurable Module is to be removed. Sw_Startup_Req => Set to 1 to inform software that the new Reconfigurable Module has been loaded Rm_Reset => Reset signal from the IP to the RM. None. None.
References XPrc::IsReady, XPRC_CR_DEFAULT_HALFWORD, XPRC_CR_USER_CONTROL_RM_DECOUPLE_BIT, XPRC_CR_USER_CONTROL_RM_RESET_BIT, XPRC_CR_USER_CONTROL_SW_SHUTDOWN_REQ_BIT, XPRC_CR_USER_CONTROL_SW_STARTUP_REQ_BIT, XPRC_CR_USER_CTRL_CMD, XPRC_MAX_NUMBER_OF_VSMS.
Referenced by Xprc_Check_User_Command.
void XPrc_SetTriggerToRmMapping(XPrc *InstancePtr, u16 VsmId, u16 TriggerId, u16 RmId)
This function is used to set a Trigger to Reconfigurable Module mapping in a Virtual Socket Manager.
InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. TriggerId specifies the trigger to modify. RmId specifies Reconfigurable Module to load when trigger TriggerId occurs. None. None.
References XPrc::Config, XPrc::IsReady, XPrc_GetRegisterAddress, XPRC_MAX_NUMBER_OF_VSMS, XPRC_TRIGGER_REG, XPrc_WriteReg.
Referenced by Xprc_Check_TriggerRmMapping.
u32 XPrc_GetTriggerToRmMapping(XPrc *InstancePtr, u16 VsmId, u16 TriggerId)
This function gets a Trigger to Reconfigurable Module mapping in a Virtual Socket Manager.
InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. TriggerId specifies the trigger to query. The identifier of the Reconfigurable Module that will be loaded when trigger TriggerId occurs. None.
References XPrc::IsReady, XPrc_GetRegisterAddress, XPRC_MAX_NUMBER_OF_VSMS, XPrc_ReadReg, XPRC_TRIGGER_REG.
Referenced by Xprc_Check_TriggerRmMapping.
void XPrc_SetRmBsIndex(XPrc *InstancePtr, u16 VsmId, u16 RmId, u16 BsIndex)
This function sets the BS_INDEX field in the RM_BS_INDEX register to specify which row of the Bitstream Information tables holds the partial bitstream for the Reconfigurable Module in the Virtual Socket Manager.
InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. RmId is the identifier of the Reconfigurable Module. BsIndex is the row number in the Bitstream Information register bank that holds information about the partial bitstream for the Reconfigurable Module. None. This overwrites the entire BS Index register so care is required in Ultrascale parts where clearing bitstreams are required. In those parts, use this first and then call XPrc_SetRmClearingBsIndex.
References XPrc::Config, XPrc::IsReady, XPrc_GetRegisterAddress, XPRC_MAX_NUMBER_OF_VSMS, XPRC_RM_BS_INDEX_REG, XPrc_WriteReg.
Referenced by Xprc_Check_BsIndex_Reg, Xprc_Program_PRC.
void XPrc_SetRmClearingBsIndex(XPrc *InstancePtr, u16 VsmId, u16 RmId, u16 ClearingBsIndex)
This function set the CLEAR_BS_INDEX field in the RM_BS_INDEX register to specify which row of the BS Information tables holds the clearing bitstream for the Reconfigurable Module in the Virtual Socket Manager.
InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. RmId is the identifier of the Reconfigurable Module. bitstream. ClearingBsIndex is the row number in the Bitstream Information register bank that holds information about the clearing bitstream for the Reconfigurable Module. None. This is only needed when the device being managed is an UltraScale device. This must be called after XPrc_SetRmBsIndex
References XPrc::Config, XPrc::IsReady, XPrc_GetRegisterAddress, XPRC_MAX_NUMBER_OF_VSMS, XPrc_ReadReg, XPRC_RM_BS_INDEX_REG, XPRC_RM_CLEARING_BS_INDEX_SHIFT, XPrc_WriteReg.
u32 XPrc_GetRmBsIndex(XPrc *InstancePtr, u16 VsmId, u16 RmId)
This function get the BS_INDEX field from the RM_BS_INDEX register for the Reconfigurable Module in the Virtual Socket Manager.
InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. RmId is the identifier of the Reconfigurable Module. Returns BS_INDEX. This is the row number in the Bitstream Information register bank that holds information about the partial bitstream for the Reconfigurable Module. None.
References XPrc::IsReady, XPrc_GetRegisterAddress, XPRC_MAX_NUMBER_OF_VSMS, XPrc_ReadReg, XPRC_RM_BS_INDEX_MASK, XPRC_RM_BS_INDEX_REG.
Referenced by Xprc_Check_BsIndex_Reg.
u16 XPrc_GetRmClearingBsIndex(XPrc *InstancePtr, u16 VsmId, u16 RmId)
This function get the CLEAR_BS_INDEX field from the RM_BS_INDEX register for the Reconfigurable Module in the Virtual Socket Manager.
InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. RmId is the identifier of the Reconfigurable Module. Returns CLEAR_BS_INDEX. This is the row number in the Bitstream Information register bank that holds information about the clearing bitstream for the Reconfigurable Module. This is only needed when the device being managed is an UltraScale device.
References XPrc::IsReady, XPrc_GetRegisterAddress, XPRC_MAX_NUMBER_OF_VSMS, XPrc_ReadReg, XPRC_RM_BS_INDEX_REG, XPRC_RM_CLEARING_BS_INDEX_SHIFT.
void XPrc_SetRmControl(XPrc *InstancePtr, u16 VsmId, u16 RmId, u8 ShutdownRequired, u8 StartupRequired, u8 ResetRequired, u8 ResetDuration)
This function set the control information for Reconfigurable Module.
InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. RmId is the identifier of the Reconfigurable Module. ShutdownRequired value for the Reconfigurable Module. XPRC_RM_CR_NO_SHUTDOWN_REQUIRED(00): No Reconfigurable Module shutdown is required.XPRC_RM_CR_HW_SHUTDOWN_REQUIRED(01) : Hardware Reconfigurable Module shutdown is required.XPRC_RM_CR_HW_SW_SHUTDOWN_REQUIRED(10) : Hardware then software shutdown is required.XPRC_RM_CR_SW_HW_SHUTDOWN_REQUIRED(11) : Software then hardware shutdown is required. StartupRequired value for the Reconfigurable Module. XPRC_RM_CR_STARTUP_NOT_REQUIRED (0) : No start-up is requiredXPRC_RM_CR_SW_STARTUP_REQUIRED (1) : Software start-up is required. ResetRequired value for the Reconfigurable Module. XPRC_RM_CR_NO_RESET_REQUIRED(00): No Reconfigurable Module Reset is required.01: RESERVED.XPRC_RM_CR_LOW_RESET_REQUIRED(10) : Active-Low Reconfigurable Module reset is required.XPRC_RM_CR_HIGH_RESET_REQUIRED(11) : Active-High Reconfigurable Module reset is required. ResetDuration value for the Reconfigurable Module. The maximum reset duration is 256 clock cycles. None. None.
References XPrc::Config, XPrc::IsReady, XPrc_GetRegisterAddress, XPRC_MAX_NUMBER_OF_VSMS, XPRC_RM_CONTROL_REG, XPRC_RM_CR_HIGH_RESET_REQUIRED, XPRC_RM_CR_MAX_RESETDURATION, XPRC_RM_CR_RESET_DURATION_MASK, XPRC_RM_CR_RESET_DURATION_SHIFT, XPRC_RM_CR_RESET_REQUIRED_MASK, XPRC_RM_CR_RESET_REQUIRED_SHIFT, XPRC_RM_CR_SHUTDOWN_REQUIRED_MASK, XPRC_RM_CR_SHUTDOWN_REQUIRED_SHIFT, XPRC_RM_CR_STARTUP_NOT_REQUIRED, XPRC_RM_CR_STARTUP_REQUIRED_MASK, XPRC_RM_CR_STARTUP_REQUIRED_SHIFT, XPRC_RM_CR_SW_HW_SHUTDOWN_REQUIRED, XPRC_RM_CR_SW_STARTUP_REQUIRED, XPrc_WriteReg.
Referenced by Xprc_Check_RmControl_Reg, Xprc_Program_PRC.
void XPrc_GetRmControl(XPrc *InstancePtr, u16 VsmId, u16 RmId, u8 *ShutdownRequired, u8 *StartupRequired, u8 *ResetRequired, u8 *ResetDuration)
This function get the control information for Reconfigurable Module.
InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. RmId is the identifier of the Reconfigurable Module. ShutdownRequired value for the Reconfigurable Module. XPRC_RM_CR_NO_SHUTDOWN_REQUIRED(00): No Reconfigurable Module shutdown is required.XPRC_RM_CR_HW_SHUTDOWN_REQUIRED(01) : Hardware Reconfigurable Module shutdown is required.XPRC_RM_CR_HW_SW_SHUTDOWN_REQUIRED(10) : Hardware then software shutdown is required.XPRC_RM_CR_SW_HW_SHUTDOWN_REQUIRED(11) : Software then hardware shutdown is required. StartupRequired value for the Reconfigurable Module. XPRC_RM_CR_STARTUP_NOT_REQUIRED (0) : No start-up is requiredXPRC_RM_CR_SW_STARTUP_REQUIRED (1) : Software start-up is required. ResetRequired value for the Reconfigurable Module. XPRC_RM_CR_NO_RESET_REQUIRED(00): No Reconfigurable Module Reset is required.01: RESERVED.XPRC_RM_CR_LOW_RESET_REQUIRED(10) : Active-Low Reconfigurable Module reset is required.XPRC_RM_CR_HIGH_RESET_REQUIRED(11) : Active-High Reconfigurable Module reset is required. ResetDuration value for the Reconfigurable Module. The maximum reset duration is 256 clock cycles. None. None.
References XPrc::Config, XPrc::IsReady, XPrc_GetRegisterAddress, XPRC_MAX_NUMBER_OF_VSMS, XPrc_ReadReg, XPRC_RM_CONTROL_REG, XPRC_RM_CR_RESET_DURATION_MASK, XPRC_RM_CR_RESET_DURATION_SHIFT, XPRC_RM_CR_RESET_REQUIRED_MASK, XPRC_RM_CR_RESET_REQUIRED_SHIFT, XPRC_RM_CR_SHUTDOWN_REQUIRED_MASK, XPRC_RM_CR_SHUTDOWN_REQUIRED_SHIFT, XPRC_RM_CR_STARTUP_REQUIRED_MASK, XPRC_RM_CR_STARTUP_REQUIRED_SHIFT.
Referenced by Xprc_Check_RmControl_Reg.
void XPrc_SetBsId(XPrc *InstancePtr, u16 VsmId, u16 BsIndex, u16 BsId)
This function sets the Bitstream Identifier.
InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. BsIndex is the row number in the Bitstream Information register bank that holds information about the bitstream. BsId is the identifier of the bitstream referenced by BsIndex. None. When the device being managed is 7 Series or UltraScale+, BsID can only be 0. When the device being managed is UltraScale, BsID can be 0 or 1
References XPrc::Config, XPrc::IsReady, XPRC_BS_ID_REG, XPrc_GetRegisterAddress, XPRC_MAX_NUMBER_OF_VSMS, XPrc_WriteReg.
u32 XPrc_GetBsId(XPrc *InstancePtr, u16 VsmId, u16 BsIndex)
This function get the Bitstream Identifier.
InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. BsIndex is the row number in the Bitstream Information register bank that holds information about the bitstream. BsId, which is the identifier of the bitstream referenced by BsIndex. When the device being managed is 7 Series or UltraScale+, BsID can only be 0. When the device being managed is UltraScale, BsID can be 0 or 1
References XPrc::IsReady, XPRC_BS_ID_REG, XPrc_GetRegisterAddress, XPRC_MAX_NUMBER_OF_VSMS, XPrc_ReadReg.
void XPrc_SetBsSize(XPrc *InstancePtr, u16 VsmId, u16 BsIndex, u32 BsSize)
This function sets the Bitstream size in bytes.
InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. BsIndex is the row number in the Bitstream Information register bank that holds information about the bitstream. BsSize is the bitstream size in bytes. None. None.
References XPrc::Config, XPrc::IsReady, XPRC_BS_SIZE_REG, XPrc_GetRegisterAddress, XPRC_MAX_NUMBER_OF_VSMS, XPrc_WriteReg.
Referenced by Xprc_Check_BsSize_Reg, Xprc_Program_PRC.
u32 XPrc_GetBsSize(XPrc *InstancePtr, u16 VsmId, u16 BsIndex)
This function get the Bitstream size in bytes.
InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. BsIndex is the row number in the Bitstream Information register bank that holds information about the bitstream. The bitstream size in bytes. None.
References XPrc::Config, XPrc::IsReady, XPRC_BS_SIZE_REG, XPrc_GetRegisterAddress, XPRC_MAX_NUMBER_OF_VSMS, XPrc_ReadReg.
Referenced by Xprc_Check_BsSize_Reg.
void XPrc_SetBsAddress(XPrc *InstancePtr, u16 VsmId, u16 BsIndex, u32 BsAddress)
This function sets the Address of the Bitstream.
InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. BsIndex is the row number in the Bitstream Information register bank that holds information about the bitstream. BsAddress is the address of the bitstream in memory. None. None.
References XPrc::Config, XPrc::IsReady, XPRC_BS_ADDRESS_REG, XPrc_GetRegisterAddress, XPRC_MAX_NUMBER_OF_VSMS, XPrc_WriteReg.
Referenced by Xprc_Check_BsAddress_Reg, Xprc_Program_PRC.
u32 XPrc_GetBsAddress(XPrc *InstancePtr, u16 VsmId, u16 BsIndex)
This function get the Address of the Bitstream.
InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. BsIndex is the row number in the Bitstream Information register bank that holds information about the bitstream. The address of the bitstream in memory None.
References XPrc::Config, XPrc::IsReady, XPRC_BS_ADDRESS_REG, XPrc_GetRegisterAddress, XPRC_MAX_NUMBER_OF_VSMS, XPrc_ReadReg.
Referenced by Xprc_Check_BsAddress_Reg.
u32 XPrc_ReadStatusReg(XPrc *InstancePtr, u16 VsmId)
This function is used to read the VSM's Status Register.
InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. Returns the contents of the VSM's status register. None.
References XPrc::IsReady, XPrc_GetRegisterAddress, XPRC_MAX_NUMBER_OF_VSMS, XPrc_ReadReg, XPRC_REG_TABLE_ROW, XPRC_STATUS_REG.
Referenced by Xprc_Check_RestartWithStatus_Command, XPrc_Example, XPrc_GetBsIdFromStatus, XPrc_GetRmIdFromStatus, XPrc_GetVsmErrorStatus, XPrc_GetVsmState, XPrc_IsVsmInShutdown, XPrc_PrintVsmStatus.
u8 XPrc_IsVsmInShutdown(XPrc *InstancePtr, u32 VsmIdOrStatus)
This function is used to identify whether a VSM is in the Shutdown state or not.
InstancePtr is a pointer to the PRC instance. VsmIdOrStatus is an identifier of the VSM to access or a pre-read status word. XPRC_SR_SHUTDOWN_ON when VSM is in Shutdown State.XPRC_SR_SHUTDOWN_OFF when VSM is not in Shutdown State. There are two modes of operation. If InstancePtr is NULL then VsmIdOrStatus contains a previously read status value. Just decode it. If InstancePtr is not NULL then read a fresh status value.
References XPrc_ReadStatusReg, XPRC_SR_SHUTDOWN_MASK, XPRC_SR_SHUTDOWN_OFF, XPRC_SR_SHUTDOWN_ON.
Referenced by Xprc_Check_RestartWithStatus_Command, XPrc_Example, XPrc_PrintVsmStatus, Xprc_Restart_VSMs.
u32 XPrc_GetVsmState(XPrc *InstancePtr, u32 VsmIdOrStatus)
This function is used to get a VSM's state.
Each VSM exist in two states 1. Active State Shutdown State InstancePtr is a pointer to the PRC instance. VsmIdOrStatus is an identifier of the VSM to access or a pre-read status word. State of VSM. There are two modes of operation. If InstancePtr is NULL then VsmIdOrStatus contains a previously read status value. Just decode it. If InstancePtr is not NULL then read a fresh status value.
References XPrc_ReadStatusReg, XPRC_SR_STATE_MASK.
Referenced by Xprc_Check_RestartWithStatus_Command, XPrc_Example, XPrc_PrintVsmStatus.
u32 XPrc_GetVsmErrorStatus(XPrc *InstancePtr, u32 VsmIdOrStatus)
This function is used to get a VSM's Error Status.
InstancePtr is a pointer to the PRC instance. VsmIdOrStatus is an identifier of the VSM to access or a pre-read status word. 0 if there's no error.Error code if there is an error. There are two modes of operation. If InstancePtr is NULL then VsmIdOrStatus contains a previously read status value. Just decode it. If InstancePtr is not NULL then read a fresh status value.
References XPrc_ReadStatusReg, XPRC_SR_ERROR_MASK, XPRC_SR_ERROR_SHIFT.
Referenced by XPrc_PrintVsmStatus.
u32 XPrc_GetRmIdFromStatus(XPrc *InstancePtr, u32 VsmIdOrStatus)
This function is used to extract the identifier of a Reconfigurable Module from a VSM's status register.
InstancePtr is a pointer to the PRC instance. VsmIdOrStatus is the identifier of the VSM to access or a pre-read status word. RM Identifier There are two modes of operation. If InstancePtr is NULL then VsmIdOrStatus contains a previously read status value. Just decode it. If InstancePtr is not NULL then read a fresh status value.
References XPrc_ReadStatusReg, XPRC_SR_RMID_MASK, XPRC_SR_RMID_SHIFT.
Referenced by Xprc_Check_RestartWithStatus_Command, XPrc_Example, XPrc_PrintVsmStatus.
u32 XPrc_GetBsIdFromStatus(XPrc *InstancePtr, u32 VsmIdOrStatus)
This function is used to extract the identifier of a Bitstream from a VSM's status register.
InstancePtr is a pointer to the PRC instance. VsmIdOrStatus is the identifier of the VSM to access or a pre-read status word. BS Identifier There are two modes of operation. If InstancePtr is NULL then VsmIdOrStatus contains a previously read status value. Just decode it. If InstancePtr is not NULL then read a fresh status value.
References XPrc_ReadStatusReg, XPRC_SR_BSID_MASK, XPRC_SR_BSID_SHIFT.
Referenced by XPrc_PrintVsmStatus.
void XPrc_PrintVsmStatus(XPrc *InstancePtr, u32 VsmIdOrStatus, char *Prefix)
This function is used to Print the VSM Status.
InstancePtr is a pointer to the PRC instance. VsmIdOrStatus is an identifier of the VSM to access or a pre-read status word. Prefix is a text string that will prefix each line of output. None. None.
References XPrc_GetBsIdFromStatus, XPrc_GetRmIdFromStatus, XPrc_GetVsmErrorStatus, XPrc_GetVsmState, XPrc_IsVsmInShutdown, XPrc_ReadStatusReg, XPRC_SR_BAD_CONFIG_ERROR, XPRC_SR_BS_COMPATIBLE_ERROR, XPRC_SR_BS_ERROR, XPRC_SR_CP_LOST_ERROR, XPRC_SR_DECOMPRESS_BAD_FORMAT_ERROR, XPRC_SR_DECOMPRESS_BAD_SIZE_ERROR, XPRC_SR_FETCH_AND_BS_ERROR, XPRC_SR_FETCH_AND_CP_LOST_ERROR, XPRC_SR_FETCH_ERROR, XPRC_SR_NO_ERROR, XPRC_SR_STATE_EMPTY, XPRC_SR_STATE_FULL, XPRC_SR_STATE_HW_SHUTDOWN, XPRC_SR_STATE_RM_LOAD, XPRC_SR_STATE_RM_RESET, XPRC_SR_STATE_RM_UNLOAD, XPRC_SR_STATE_SW_SHUTDOWN, XPRC_SR_STATE_SW_STARTUP.
Referenced by XPrc_Example.
void XPrc_SendSwTrigger(XPrc *InstancePtr, u16 VsmId, u16 TriggerId)
This function sends a software trigger to a Virtual Socket Manager.
InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. TriggerId is the trigger to send. None. None.
References XPrc::Config, XPrc::IsReady, XPrc_GetRegisterAddress, XPRC_MAX_NUMBER_OF_VSMS, XPRC_REG_TABLE_ROW, XPRC_SW_TRIGGER_REG, XPrc_WriteReg.
Referenced by XPrc_Example.
u8 XPrc_IsSwTriggerPending(XPrc *InstancePtr, u16 VsmId, u16 *TriggerId)
This function is used to find out if there is a Software Trigger pending in a VSM.
InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. TriggerId is a pointer to a variable that will hold the trigger ID that's in the register. This is the last trigger written to the register and may or may not still be pending. XPRC_SW_TRIGGER_PENDING(1) if software trigger is pendingXPRC_NO_SW_TRIGGER_PENDING(0) if software trigger is not pending. None.
References XPrc::IsReady, XPrc_GetRegisterAddress, XPRC_MAX_NUMBER_OF_VSMS, XPRC_NO_SW_TRIGGER_PENDING, XPrc_ReadReg, XPRC_REG_TABLE_ROW, XPRC_SW_TRIGGER_ID_MASK, XPRC_SW_TRIGGER_PENDING, XPRC_SW_TRIGGER_PENDING_MASK, XPRC_SW_TRIGGER_REG.
u32 XPrc_GetRegisterAddress(XPrc *InstancePtr, u32 VsmId, u8 RegisterType, u16 TableRow)
The register offsets for the PRC are dynamic.
These could become awkward to use as each Trigger, VS, RM and BS require their own registers so looking up hard wired names would be clumsy. For example a reference to a constant PRC_VS3_TRIGGER7 would be difficult to generate in a loop that iterated over each VS and Trigger.This function gets the address offset for a register in the PRC. As this is a Direct Hardware Interface, it cannot use device configuration parameters, and multiple instances are supported through the base address. InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. RegisterType is the type of register(XPRC_STATUS_REG, XPRC_CONTROL_REG, XPRC_SW_TRIGGER_REG, XPRC_TRIGGER_REG, etc) TableRow is the row of the table(trigger_id, rm_id, rm_bs_index). Address of the register. None
References XPrc::Config, XPRC_BS_ADDRESS_REG, XPRC_BS_ADDRESS_REG_TABLE_ID, XPRC_BS_ID_REG, XPRC_BS_ID_REG_TABLE_ID, XPRC_BS_SIZE_REG, XPRC_BS_SIZE_REG_TABLE_ID, XPRC_CONTROL_REG, XPRC_CONTROL_REG_TABLE_ID, XPRC_DEFAULT_BANKID, XPRC_DEFAULT_TABLEID, XPRC_RM_BS_INDEX_REG, XPRC_RM_BS_INDEX_REG_TABLE_ID, XPRC_RM_CONTROL_REG, XPRC_RM_CONTROL_REG_TABLE_ID, XPRC_STATUS_REG, XPRC_STATUS_REG_TABLE_ID, XPRC_SW_TRIGGER_REG, XPRC_SW_TRIGGER_REG_TABLE_ID, XPRC_TRIGGER_REG, XPRC_TRIGGER_REG_TABLE_ID, XPRC_VSM_BS_REG_BANK, XPRC_VSM_GENERAL_REG_BANK, XPRC_VSM_RM_REG_BANK, XPRC_VSM_TRIGGER_REG_BANK.
Referenced by XPrc_GetBsAddress, XPrc_GetBsId, XPrc_GetBsSize, XPrc_GetRmBsIndex, XPrc_GetRmClearingBsIndex, XPrc_GetRmControl, XPrc_GetTriggerToRmMapping, XPrc_IsSwTriggerPending, XPrc_ReadStatusReg, XPrc_SelfTest, XPrc_SendSwTrigger, XPrc_SetBsAddress, XPrc_SetBsId, XPrc_SetBsSize, XPrc_SetRmBsIndex, XPrc_SetRmClearingBsIndex, XPrc_SetRmControl, XPrc_SetTriggerToRmMapping.
XPrc_Config * XPrc_LookupConfig(UINTPTR BaseAddress)
This function Looks for the device configuration based on the unique device ID.
The table XPrc_ConfigTable[] contains the configuration information for each device in the system. DeviceId is the unique device ID of the device being looked up. A pointer to the configuration table entry corresponding to the given device ID, or NULL if no match was found. None.
Referenced by XPrc_Example, XPrc_SelfTestExample.
s32 XPrc_SelfTest(XPrc *InstancePtr)
This function runs a self-test on the PRC driver.
This self test reads from the status register. InstancePtr is a pointer to the XPrc instance. XST_SUCCESS if the test is successful. None
References XPrc::IsReady, XPrc_GetRegisterAddress, XPrc_ReadReg, XPRC_REG_TABLE_ROW, XPRC_STATUS_REG.
Referenced by XPrc_Example, XPrc_SelfTestExample.
XPRC_H_
XPrc_GetNumberOfVsms
This macro is used to get the Number of Virtual Socket Managers.
InstancePtr is a pointer to the PRC instance. Number of Vsms. None.
Referenced by Xprc_Check_BsAddress_Reg, Xprc_Check_BsIndex_Reg, Xprc_Check_BsSize_Reg, Xprc_Check_RestartWithStatus_Command, Xprc_Check_RmControl_Reg, Xprc_Check_TriggerRmMapping, Xprc_Check_User_Command, XPrc_Example, Xprc_Program_PRC, Xprc_Restart_VSMs.
XPrc_GetRequiresClearBitstreams
This macro is used to find if Clearing Bitstreams are required.
InstancePtr is a pointer to the PRC instance. 0 if Clearing Bitstreams are not required, 1 if they are. Clearing Bitstreams are only required when the device being managed is an UltraScale device.
XPrc_GetCpArbitrationProtocol
This macro is used to get the CAP Arbitration protocol.
InstancePtr is a pointer to the PRC instance. Returns the value of the CAP arbitration protocol. None.
XPrc_GetHasAxiLiteIf
This macro is used to discover if the AXI4-Lite register interface is enabled or disabled.
InstancePtr is a pointer to the PRC instance. Returns a value when AXI4-Lite interface is enabled or disabled. This interface must be enabled for the driver to function.
XPrc_GetResetActiveLevel
This macro is used to discover if the core's reset is active low (0) or active high (1).
InstancePtr is a pointer to the PRC instance. 1 if the core's reset is active high, 0 if it's active low. None.
XPrc_GetCpFifoDepth
This macro returns the depth of FIFO in the fetch path.
InstancePtr is a pointer to the PRC instance. Return Fifo depth value. None.
XPrc_GetCpFifoType
This macro returns the type of the FIFO in the fetch path.
InstancePtr is a pointer to the PRC instance. Returns CP_FIFO_TYPE_LUTRAM for Lutram typeCP_FIFO_TYPE_BLOCKRAM for blockram type None.
XPrc_GetCpFamily
This macro returns the family type of the device being managed.
InstancePtr is a pointer to the PRC instance. Returns 7, 8 or 9 for 7 Series, Ultrascale and UltraScale+. None.
XPrc_GetCdcStages
This macro returns the number of synchronization stages used when crossing between clock domains.
InstancePtr is a pointer to the PRC instance. Returns the number of CDC stages. None.
XPrc_GetCpCompression
This macro tells the PRC whether partial bitstreams are compressed or not.
InstancePtr is a pointer to the PRC instance. Returns 0 if PRC is same as before. Returns 1 if decompression block is added to hardware. None.
XPrc_GetRegVsmMsb
This macro is used to get the Virtual Socket Manager Select MSB.
InstancePtr is a pointer to the PRC instance. Msb of Virtual Socket Manager. None.
XPrc_GetRegVsmLsb
This macro is used to get the Virtual Socket Manager Select LSB.
InstancePtr is a pointer to the PRC instance. Lsb of Virtual Socket Manager. None.
XPrc_GetRegBankMsb
This macro is used to get the Bank Select MSB.
InstancePtr is a pointer to the PRC instance. Msb of Bank register. None.
XPrc_GetRegBankLsb
This macro is used to get the Bank Select LSB.
InstancePtr is a pointer to the PRC instance. Lsb of Bank register. None.
XPrc_GetRegSelectMsb
This macro is used to get the Register Select MSB.
InstancePtr is a pointer to the PRC instance. Msb of Register selected. None.
XPrc_GetRegSelectLsb
This macro is used to get the Register Select LSB.
InstancePtr is a pointer to the PRC instance. Lsb of Register selected. None.
XPrc_GetNumRms
This macro is used to get the number of Reconfigurable Modules in a VSM.
InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. The number of RMs that this VSM has. None.
Referenced by Xprc_Check_RestartWithStatus_Command, XPrc_Example, Xprc_Program_PRC.
XPrc_GetNumRmsAllocated
This macro returns the number of Reconfigurable Modules that have been allocated in this VSM.
InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. Number of RMs allocated in the VSM. None.
Referenced by Xprc_Check_BsAddress_Reg, Xprc_Check_BsIndex_Reg, Xprc_Check_BsSize_Reg, Xprc_Check_RmControl_Reg, Xprc_Check_TriggerRmMapping.
XPrc_GetStartInShutdown
This macro returns if the VSM starts in the Shutdown state.
InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. 1 if the VSM starts in Shutdown State, 0 if it starts in the active state. None.
XPrc_GetNumTriggersAllocated
This macro returns the number of triggers that the Virtual Socket Manager has.
InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. Number of triggers allocated in the Virtual Socket Manager. None.
Referenced by Xprc_Check_TriggerRmMapping.
XPrc_GetShutdownOnError
This macro returns whether the VSM will enter the shutdown state if an error is detected.
InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. Returns 1 if the VSM will enter the shutdown state on an error, 0 if it doesn't. None
XPrc_GetHasPorRm
This macro returns whether the VSM contains an RM in the initial configuration bitstream.
InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. Returns 1 if the VSM has an RM in the initial bitstream and 0 if it doesn't. This will always return 1 when the device being managed is an UltraScale device.
XPrc_GetPorRm
This macro returns the RM in the initial configuration bitstream for this VSM.
The returned value is only valid if XPrc_GetHasPorRm() returns 1 for this VSM. InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. Returns a RM identifier. None.
XPrc_GetHasAxisStatus
This macro returns 1 if the AXI4-Stream Status Channel is enabled for this VSM, and 0 if it's disabled.
InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. Returns 1 when the AXI4-Stream Status channel is enabled and 0 when it is disabled. None.
XPrc_GetHasAxisControl
This macro returns 1 if the AXI4-Stream Control Channel is enabled for this VSM, and 0 if it's disabled.
InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. Returns 1 when the AXI4-Stream Control channel is enabled and 0 when it is disabled. None.
XPrc_GetSkipRmStartupAfterReset
This macro returns whether the VSM will skip the Reconfigurable Module startup steps after a reset.
InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. Returns 1 when the RM startup steps are skipped, and 0 when they aren't. None.
XPrc_GetNumHwTriggers
This macro returns the number of hardware triggers that the VSM has.
InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. Returns the number of hardware triggers. None.
XPRC_HW_H_
XPrc_In32
XPrc_Out32
XPrc_WriteReg
This macro writes a value to a PRC register.
A 32 bit write is performed. Address is the address of the register to write to. Data is the data written to the register. None. C-style signature: void XPRC_WriteReg(u32 Address, u32 Data)
Referenced by XPrc_SendSwTrigger, XPrc_SetBsAddress, XPrc_SetBsId, XPrc_SetBsSize, XPrc_SetRmBsIndex, XPrc_SetRmClearingBsIndex, XPrc_SetRmControl, XPrc_SetTriggerToRmMapping.
XPrc_ReadReg
This macro reads a value from a PRC register.
A 32 bit read is performed. Address is the address of the register to read from. Data read from the register. C-style signature: u32 XPrc_ReadReg(u32 Address)
Referenced by XPrc_GetBsAddress, XPrc_GetBsId, XPrc_GetBsSize, XPrc_GetRmBsIndex, XPrc_GetRmClearingBsIndex, XPrc_GetRmControl, XPrc_GetTriggerToRmMapping, XPrc_IsSwTriggerPending, XPrc_ReadStatusReg, XPrc_SelfTest, XPrc_SetRmClearingBsIndex.