xprc_selftest_example.c
XPRC_BASEADDR
The following constants map to the XPAR parameters created in the xparameters.h file.
They are defined here such that a user can easily change all the needed parameters in one place.
Referenced by main.
XPrc Prc
u32 XPrc_SelfTestExample(UINTPTR BaseAddress)
This function does a minimal test on the PRC device and driver as a design example.
The purpose of this function is to illustrate how to use the XPrc component. DeviceId is the XPAR_<prc_instance>_DEVICE_ID value from xparameters.h. XST_SUCCESS if successful.XST_FAILURE if failed. None.
References XPrc_CfgInitialize, XPrc_LookupConfig, XPrc_SelfTest.
Referenced by main.
u32 XPrc_GetRegisterAddress(XPrc *InstancePtr, u32 VsmId, u8 RegisterType, u16 TableRow)
The register offsets for the PRC are dynamic.
These could become awkward to use as each Trigger, VS, RM and BS require their own registers so looking up hard wired names would be clumsy. For example a reference to a constant PRC_VS3_TRIGGER7 would be difficult to generate in a loop that iterated over each VS and Trigger.This function gets the address offset for a register in the PRC. As this is a Direct Hardware Interface, it cannot use device configuration parameters, and multiple instances are supported through the base address. InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. RegisterType is the type of register(XPRC_STATUS_REG, XPRC_CONTROL_REG, XPRC_SW_TRIGGER_REG, XPRC_TRIGGER_REG, etc) TableRow is the row of the table(trigger_id, rm_id, rm_bs_index). Address of the register. None
References XPRC_STATUS_REG, XPRC_VSM_GENERAL_REG_BANK, XPRC_STATUS_REG_TABLE_ID, XPRC_CONTROL_REG, XPRC_CONTROL_REG_TABLE_ID, XPRC_SW_TRIGGER_REG, XPRC_SW_TRIGGER_REG_TABLE_ID, XPRC_TRIGGER_REG, XPRC_VSM_TRIGGER_REG_BANK, XPRC_TRIGGER_REG_TABLE_ID, XPRC_RM_BS_INDEX_REG, XPRC_VSM_RM_REG_BANK, XPRC_RM_BS_INDEX_REG_TABLE_ID, XPRC_RM_CONTROL_REG, XPRC_RM_CONTROL_REG_TABLE_ID, XPRC_BS_ID_REG, XPRC_VSM_BS_REG_BANK, XPRC_BS_ID_REG_TABLE_ID, XPRC_BS_ADDRESS_REG, XPRC_BS_ADDRESS_REG_TABLE_ID, XPRC_BS_SIZE_REG, XPRC_BS_SIZE_REG_TABLE_ID, XPRC_DEFAULT_BANKID, XPRC_DEFAULT_TABLEID, XPrc::Config.
Referenced by XPrc_SetTriggerToRmMapping, XPrc_GetTriggerToRmMapping, XPrc_SetRmBsIndex, XPrc_SetRmClearingBsIndex, XPrc_GetRmBsIndex, XPrc_GetRmClearingBsIndex, XPrc_SetRmControl, XPrc_GetRmControl, XPrc_SetBsId, XPrc_GetBsId, XPrc_SetBsSize, XPrc_GetBsSize, XPrc_SetBsAddress, XPrc_GetBsAddress, XPrc_ReadStatusReg, XPrc_SendSwTrigger, XPrc_IsSwTriggerPending, XPrc_SelfTest.
u32 XPrc_GetRegisterOffset(XPrc *InstancePtr, u32 VsmId, u8 BankId, u8 TableInBank, u8 TableRow)
u16 XPrc_GetOffsetForTableType(u8 TableId)
int main(void)
This is the main function to call the example.
None. XST_SUCCESS if successful.XST_FAILURE if failed. None.
References XPRC_BASEADDR, XPRC_DEVICE_ID, XPrc_SelfTestExample.