xprc_selftest.c
u32 XPrc_GetRegisterAddress(XPrc *InstancePtr, u32 VsmId, u8 RegisterType, u16 TableRow)
The register offsets for the PRC are dynamic.
These could become awkward to use as each Trigger, VS, RM and BS require their own registers so looking up hard wired names would be clumsy. For example a reference to a constant PRC_VS3_TRIGGER7 would be difficult to generate in a loop that iterated over each VS and Trigger.This function gets the address offset for a register in the PRC. As this is a Direct Hardware Interface, it cannot use device configuration parameters, and multiple instances are supported through the base address. InstancePtr is a pointer to the PRC instance. VsmId is the identifier of the VSM to access. RegisterType is the type of register(XPRC_STATUS_REG, XPRC_CONTROL_REG, XPRC_SW_TRIGGER_REG, XPRC_TRIGGER_REG, etc) TableRow is the row of the table(trigger_id, rm_id, rm_bs_index). Address of the register. None
References XPrc::Config, XPRC_BS_ADDRESS_REG, XPRC_BS_ADDRESS_REG_TABLE_ID, XPRC_BS_ID_REG, XPRC_BS_ID_REG_TABLE_ID, XPRC_BS_SIZE_REG, XPRC_BS_SIZE_REG_TABLE_ID, XPRC_CONTROL_REG, XPRC_CONTROL_REG_TABLE_ID, XPRC_DEFAULT_BANKID, XPRC_DEFAULT_TABLEID, XPRC_RM_BS_INDEX_REG, XPRC_RM_BS_INDEX_REG_TABLE_ID, XPRC_RM_CONTROL_REG, XPRC_RM_CONTROL_REG_TABLE_ID, XPRC_STATUS_REG, XPRC_STATUS_REG_TABLE_ID, XPRC_SW_TRIGGER_REG, XPRC_SW_TRIGGER_REG_TABLE_ID, XPRC_TRIGGER_REG, XPRC_TRIGGER_REG_TABLE_ID, XPRC_VSM_BS_REG_BANK, XPRC_VSM_GENERAL_REG_BANK, XPRC_VSM_RM_REG_BANK, XPRC_VSM_TRIGGER_REG_BANK.
Referenced by XPrc_GetBsAddress, XPrc_GetBsId, XPrc_GetBsSize, XPrc_GetRmBsIndex, XPrc_GetRmClearingBsIndex, XPrc_GetRmControl, XPrc_GetTriggerToRmMapping, XPrc_IsSwTriggerPending, XPrc_ReadStatusReg, XPrc_SelfTest, XPrc_SendSwTrigger, XPrc_SetBsAddress, XPrc_SetBsId, XPrc_SetBsSize, XPrc_SetRmBsIndex, XPrc_SetRmClearingBsIndex, XPrc_SetRmControl, XPrc_SetTriggerToRmMapping.
s32 XPrc_SelfTest(XPrc *InstancePtr)
This function runs a self-test on the PRC driver.
This self test reads from the status register. InstancePtr is a pointer to the XPrc instance. XST_SUCCESS if the test is successful. None
References XPrc::IsReady, XPrc_GetRegisterAddress, XPrc_ReadReg, XPRC_REG_TABLE_ROW, XPRC_STATUS_REG.
Referenced by XPrc_Example, XPrc_SelfTestExample.