xprc_example.c
XPRC_DEVICE_ID
The following constants map to the XPAR parameters created in the xparameters.h file.
They are defined here such that a user can easily change all the needed parameters in one place.
Referenced by main.
XGPIO_USR_ACCESS_DEVICE_ID
XGPIO_VSM_SHIFT_DEVICE_ID
XGPIO_VSM_COUNT_DEVICE_ID
XPrc Prc
u32 XPrc_Example(u16 DeviceId)
This function does a minimal test on the PRC device and driver as a design example.
DeviceId is the XPAR_<prc_instance>_DEVICE_ID value from xparameters.h. XST_SUCCESS if successfulXST_FAILURE if failed None.
References XPrc_CfgInitialize, Xprc_Check_BsAddress_Reg, Xprc_Check_BsIndex_Reg, Xprc_Check_BsSize_Reg, Xprc_Check_RestartWithStatus_Command, Xprc_Check_RmControl_Reg, Xprc_Check_TriggerRmMapping, Xprc_Check_User_Command, XPrc_GetNumberOfVsms, XPrc_GetNumRms, XPrc_GetRmIdFromStatus, XPrc_GetVsmState, XPrc_IsVsmInShutdown, XPrc_LookupConfig, XPrc_PrintVsmStatus, Xprc_Program_PRC, XPrc_ReadStatusReg, Xprc_Restart_VSMs, XPrc_SelfTest, XPrc_SendShutdownCommand, XPrc_SendSwTrigger, XPRC_SR_STATE_FULL.
Referenced by main.
u32 Xprc_Check_User_Command(u16 VsmId, XGpio ShiftVsmGpio, XGpio CountVsmGpio)
This function is used to test the User Command.
VsmId is the identifier of the VSM to access. ShiftVsmGpio is Instance of the GPIO attached to the PRC's Shift VSM. CountVsmGpio is Instance of the GPIO attached to the PRC's Count VSM. XST_SUCCESS if successful.XST_FAILURE if failed. This is only valid for this particular configuration of the PRC so it cannot be used in a general PRC test case. This is configuration dependent because each VSM has its own GPIO.
References XPRC_CR_USER_CONTROL_RM_DECOUPLE_BIT, XPRC_CR_USER_CONTROL_RM_RESET_BIT, XPRC_CR_USER_CONTROL_RM_SHUTDOWN_REQ_BIT, XPRC_CR_USER_CONTROL_SW_SHUTDOWN_REQ_BIT, XPRC_CR_USER_CONTROL_SW_STARTUP_REQ_BIT, XPrc_GetNumberOfVsms, XPrc_SendUserControlCommand.
Referenced by XPrc_Example.
u32 Xprc_Check_RestartWithStatus_Command(u16 VsmId)
This function is used to test the Restart with Status Command.
Flip the VSM state and set a new RM. Check the status is as expected. Flip the VSM state back to what it was and set the original RM. Check the status is as expected VsmId is the identifier of the VSM to access. XST_SUCCESS if successful.XST_FAILURE if failed. None.
References XPRC_CR_VS_EMPTY, XPRC_CR_VS_FULL, XPrc_GetNumberOfVsms, XPrc_GetNumRms, XPrc_GetRmIdFromStatus, XPrc_GetVsmState, XPrc_IsVsmInShutdown, XPrc_ReadStatusReg, XPrc_SendRestartWithNoStatusCommand, XPrc_SendRestartWithStatusCommand, XPrc_SendShutdownCommand, XPRC_SR_STATE_EMPTY, XPRC_SR_STATE_FULL.
Referenced by XPrc_Example.
u32 Xprc_Check_TriggerRmMapping(u16 VsmId)
This function is used to test that we can set/get the Trigger to RM mapping registers.
For each trigger allocated, set the value of the RM it will load. VsmId is the identifier of the VSM to access. XST_SUCCESS if successful.XST_FAILURE if failed. The width of this register is set by the number of allocated RMs, so we can't use any number greater than that or else it will alias.
References XPrc_GetNumberOfVsms, XPrc_GetNumRmsAllocated, XPrc_GetNumTriggersAllocated, XPrc_GetTriggerToRmMapping, XPrc_SetTriggerToRmMapping.
Referenced by XPrc_Example.
u32 Xprc_Check_BsIndex_Reg(u16 VsmId)
This function is used to test that we can set/get the BS Index registers.
VsmId is the identifier of the VSM to access. XST_SUCCESS if successful.XST_FAILURE if failed. None.
References XPrc_GetNumberOfVsms, XPrc_GetNumRmsAllocated, XPrc_GetRmBsIndex, XPrc_SetRmBsIndex.
Referenced by XPrc_Example.
u32 Xprc_Check_RmControl_Reg(u16 VsmId)
This function is used to test that we can set/get the RM Control registers.
VsmId is the identifier of the VSM to access. XST_SUCCESS if successful.XST_FAILURE if failed. The RM Control register contains the following fields: Name | Min value | Max value | Shutdown Required | 0 | 3 | Startup Required | 0 | 1 | Reset Required | 0 | 3 | Reset Duration | 0 | 255 |
References XPrc_GetNumberOfVsms, XPrc_GetNumRmsAllocated, XPrc_GetRmControl, XPrc_SetRmControl.
Referenced by XPrc_Example.
u32 Xprc_Check_BsSize_Reg(u16 VsmId)
This function is used to test that we can set/get the BS Size registers.
VsmId is the identifier of the VSM to access. XST_SUCCESS if successful.XST_FAILURE if failed. None.
References XPrc_GetBsSize, XPrc_GetNumberOfVsms, XPrc_GetNumRmsAllocated, XPrc_SetBsSize.
Referenced by XPrc_Example.
u32 Xprc_Check_BsAddress_Reg(u16 VsmId)
This function is used to test that we can set/get the BS Address registers.
VsmId is the identifier of the VSM to access. XST_SUCCESS if successful.XST_FAILURE if failed. None.
References XPrc_GetBsAddress, XPrc_GetNumberOfVsms, XPrc_GetNumRmsAllocated, XPrc_SetBsAddress.
Referenced by XPrc_Example.
u32 Xprc_Program_PRC(u16 VsmId)
This function is used to Program the PRC.
VsmId is the identifier of the VSM to access. XST_SUCCESS if successful.XST_FAILURE if failed. For each allocated RM in each VSM, generate a partial bitstream and store it in memory. Program the PRC to point at it.
References XPrc_GetNumberOfVsms, XPrc_GetNumRms, XPrc_SetBsAddress, XPrc_SetBsSize, XPrc_SetRmBsIndex, XPrc_SetRmControl.
Referenced by XPrc_Example.
void Xprc_Restart_VSMs(u16 VsmId)
This function is used to Restart the VSMs.
VsmId is the identifier of the VSM to access. XST_SUCCESS if successful.XST_FAILURE if failed. None.
References XPrc_GetNumberOfVsms, XPrc_IsVsmInShutdown, XPrc_SendRestartWithNoStatusCommand.
Referenced by XPrc_Example.
int main(void)
This is the main function to call the example.
None. XST_SUCCESS if successful.XST_FAILURE if failed. None.
References XPRC_DEVICE_ID, XPrc_Example.