xdpdma_video_example.h
LaneCount_t
LinkRate_t
int DpdmaVideoExample(Run_Config *RunCfgPtr)
The purpose of this function is to illustrate how to use the XDpDma device driver in Graphics overlay mode.
RunCfgPtr is a pointer to the application configuration structure. XST_SUCCESS if successful, else XST_FAILURE. None.
References GraphicsOverlay, InitDpDmaSubsystem, InitRunConfig, SetupInterrupts.
Referenced by main.
void InitRunConfig(Run_Config *RunCfgPtr)
The purpose of this function is to initialize the application configuration.
RunCfgPtr is a pointer to the application configuration structure. None. None.
Referenced by DpdmaVideoExample.
int InitDpDmaSubsystem(Run_Config *RunCfgPtr)
The purpose of this function is to initialize the DP Subsystem (XDpDma, XAVBuf, XDpPsu)
RunCfgPtr is a pointer to the application configuration structure. None. None.
References XDpDma_CfgInitialize, XDpDma_LookupConfig, XDpDma_SetGraphicsFormat, XDpDma_SetQOS.
Referenced by DpdmaVideoExample, DpPsu_Run.
void SetupInterrupts(Run_Config *RunCfgPtr)
The purpose of this function is to setup call back functions for the DP controller interrupts.
RunCfgPtr is a pointer to the application configuration structure. None. None.
References DpPsu_IsrHpdEvent, DpPsu_IsrHpdPulse, XDpDma_InterruptEnable, XDpDma_InterruptHandler.
Referenced by DpdmaVideoExample.
u8* GraphicsOverlay(u8 *Frame)
The purpose of this function is to generate a Graphics frame of the format RGBA8888 which generates an overlay on 1/2 of the bottom of the screen.
This is just to illustrate the functionality of the graphics overlay. RunCfgPtr is a pointer to the application configuration structure. Frame is a pointer to a buffer which is going to be populated with rendered frame Returns a pointer to the frame. None.
Referenced by DpdmaVideoExample.
void DpPsu_SetupVideoStream(Run_Config *RunCfgPtr)
This function is called to setup the VideoStream with its video and MSA attributes.
RunCfgPtr is a pointer to the application configuration structure. None. Use the XDpPsu_SetHpdEventHandler driver function to set this function as the handler for HPD pulses.
Referenced by DpPsu_IsrHpdPulse, DpPsu_Run.
void DpPsu_Run(Run_Config *RunCfgPtr)
This function will configure and establish a link with the receiver device, afterwards, a video stream will start to be sent over the main link.
RunCfgPtr is a pointer to the application configuration structure. XST_SUCCESS if main link was successfully established.XST_FAILURE otherwise. None.
References DpPsu_SetupVideoStream, InitDpDmaSubsystem, XDpDma_DisplayGfxFrameBuffer, XDpDma_SetChannelState.
Referenced by DpPsu_IsrHpdEvent.
void DpPsu_IsrHpdEvent(void *ref)
This function is called when a Hot-Plug-Detect (HPD) event is received by the DisplayPort TX core.
The XDPPSU_INTERRUPT_STATUS_HPD_EVENT_MASK bit of the core's XDPPSU_INTERRUPT_STATUS register indicates that an HPD event has occurred. InstancePtr is a pointer to the XDpPsu instance. None. Use the XDpPsu_SetHpdEventHandler driver function to set this function as the handler for HPD pulses.
References DpPsu_Run.
Referenced by SetupInterrupts.
void DpPsu_IsrHpdPulse(void *ref)
This function is called when a Hot-Plug-Detect (HPD) pulse is received by the DisplayPort TX core.
The XDPPSU_INTERRUPT_STATUS_HPD_PULSE_DETECTED_MASK bit of the core's XDPPSU_INTERRUPT_STATUS register indicates that an HPD event has occurred. InstancePtr is a pointer to the XDpPsu instance. None. Use the XDpPsu_SetHpdPulseHandler driver function to set this function as the handler for HPD pulses.
References DpPsu_SetupVideoStream.
Referenced by SetupInterrupts.