xdpdma_intr.c
void XDpDma_InterruptEnable(XDpDma *InstancePtr, u32 Mask)
This function enables the interrupts that are required.
InstancePtr is pointer to the instance of DPDMA Mask is mask to XDPDMA_IEN register None. None.
References XDPDMA_IEN, XDpDma_WriteReg.
Referenced by SetupInterrupts.
void XDpDma_InterruptHandler(XDpDma *InstancePtr)
This function handles the interrupts generated by DPDMA.
InstancePtr is pointer to the instance of the DPDMA None. None.
References XDPDMA_ISR, XDpDma_ReadReg, XDpDma_SetChannelState, XDpDma_VSyncHandler, XDpDma_WriteReg.
Referenced by SetupInterrupts.
void XDpDma_VSyncHandler(XDpDma *InstancePtr)
This function handles frame new frames on VSync.
InstancePtr is pointer to the instance of the driver. None. None.
References XDPDMA_ISR, XDpDma_ReTrigger, XDpDma_SetChannelState, XDpDma_SetupChannel, XDpDma_Trigger, XDpDma_WriteReg.
Referenced by XDpDma_InterruptHandler.