xdpdma_video_example.c
DPPSU_BASEADDR
AVBUF_BASEADDR
DPDMA_BASEADDR
INTC_BASEADDR
BUFFERSIZE
LINESIZE
STRIDE
XDpDma DpDma
XDpPsu DpPsu
XAVBuf AVBuf
XScuGic Intr
Run_Config RunCfg
u8 Frame[BUFFERSIZE][BUFFERSIZE]
XDpDma_FrameBuffer FrameBuffer
int main()
Main function to call the DPDMA Video example.
None XST_SUCCESS if successful, otherwise XST_FAILURE. None
References DpdmaVideoExample.
int DpdmaVideoExample(Run_Config *RunCfgPtr)
The purpose of this function is to illustrate how to use the XDpDma device driver in Graphics overlay mode.
RunCfgPtr is a pointer to the application configuration structure. XST_SUCCESS if successful, else XST_FAILURE. None.
References GraphicsOverlay, InitDpDmaSubsystem, InitRunConfig, SetupInterrupts.
Referenced by main.
void InitRunConfig(Run_Config *RunCfgPtr)
The purpose of this function is to initialize the application configuration.
RunCfgPtr is a pointer to the application configuration structure. None. None.
Referenced by DpdmaVideoExample.
int InitDpDmaSubsystem(Run_Config *RunCfgPtr)
The purpose of this function is to initialize the DP Subsystem (XDpDma, XAVBuf, XDpPsu)
RunCfgPtr is a pointer to the application configuration structure. None. None.
References XDpDma_CfgInitialize, XDpDma_LookupConfig, XDpDma_SetGraphicsFormat, XDpDma_SetQOS.
Referenced by DpdmaVideoExample, DpPsu_Run.
void SetupInterrupts(Run_Config *RunCfgPtr)
The purpose of this function is to setup call back functions for the DP controller interrupts.
RunCfgPtr is a pointer to the application configuration structure. None. None.
References DpPsu_IsrHpdEvent, DpPsu_IsrHpdPulse, XDpDma_InterruptEnable, XDpDma_InterruptHandler.
Referenced by DpdmaVideoExample.
u8* GraphicsOverlay(u8 *Frame)
The purpose of this function is to generate a Graphics frame of the format RGBA8888 which generates an overlay on 1/2 of the bottom of the screen.
This is just to illustrate the functionality of the graphics overlay. RunCfgPtr is a pointer to the application configuration structure. Frame is a pointer to a buffer which is going to be populated with rendered frame Returns a pointer to the frame. None.
Referenced by DpdmaVideoExample.