xdpdma.c
XDPDMA_CH_OFFSET
XDPDMA_WAIT_TIMEOUT
XDPDMA_AUDIO_ALIGNMENT
XDPDMA_VIDEO_CHANNEL0
XDPDMA_VIDEO_CHANNEL1
XDPDMA_VIDEO_CHANNEL2
XDPDMA_GRAPHICS_CHANNEL
XDPDMA_AUDIO_CHANNEL0
XDPDMA_AUDIO_CHANNEL1
XDPDMA_DESC_PREAMBLE
XDPDMA_DESC_IGNR_DONE
XDPDMA_DESC_UPDATE
XDPDMA_DESC_COMP_INTR
XDPDMA_DESC_LAST_FRAME
XDPDMA_DESC_DONE_SHIFT
XDPDMA_QOS_MIN
XDPDMA_QOS_MAX
static u32 XDpDma_GetPendingTransaction(XDpDma *InstancePtr, u32 ChannelNum)
This function returns the number of outstanding transactions on a given channel.
InstancePtr is a pointer to the driver instance. ChannelNum is the channel number on which the operation is being carried out. Number of pending transactions. None.
static int XDpDma_WaitPendingTransaction(XDpDma *InstancePtr, u8 ChannelNum)
This function waits until the outstanding transactions are completed.
InstancePtr is a pointer to the driver instance. ChannelNum is the channel number on which the operation is being carried out. XST_SUCCESS when all the pending transactions are complete before timeout. XST_FAILURE if timeout occurs before pending transactions are completed. None.
static int XDpDma_ConfigChannelState(XDpDma *InstancePtr, u8 ChannelNum, XDpDma_ChannelState Enable)
This function controls the hardware channels of the DPDMA.
InstancePtr is a pointer to the driver instance. ChannelNum is the physical channel number of the DPDMA. ChannelState is an enum of type XDpDma_ChannelState. XST_SUCCESS when the mentioned channel is enabled successfully. XST_FAILURE when the mentioned channel fails to be enabled. None.
static void XDpDma_UpdateVideoDescriptor(XDpDma_Channel *Channel)
This function updates the descriptor that is not currently active on a Video/Graphics channel.
InstancePtr is a pointer to the driver instance. Channel is a pointer to the channel on which the operation is to be carried out. None. None.
static void XDpDma_SetDescriptorAddress(XDpDma *InstancePtr, u8 ChannelNum)
This function programs the address of the descriptor about to be active.
InstancePtr is a pointer to the DPDMA instance. Channel is an enum of the channel for which the descriptor address is to be set. Descriptor for next operation. None.
static void XDpDma_SetupAudioDescriptor(XDpDma_Descriptor *CurrDesc, u32 DataSize, u64 BuffAddr, XDpDma_Descriptor *NextDesc)
This functions sets the Audio Descriptor for Data Transfer.
CurrDesc is a pointer to the descriptor to be initialized DataSize is the payload size of the buffer to be transferred BuffAddr is the payload address None. None.
void XDpDma_CfgInitialize(XDpDma *InstancePtr, XDpDma_Config *CfgPtr)
This functions retrieves the configuration for this DPDMA driver and fills in the InstancePtr->Config structure.
InstancePtr is a pointer to the driver instance. CfgPtr is a pointer to the configuration structure that will be used to copy the settings from. None. None.
Referenced by InitDpDmaSubsystem.
int XDpDma_SetChannelState(XDpDma *InstancePtr, XDpDma_ChannelType Channel, XDpDma_ChannelState ChannelState)
This functions controls the states in which a channel should go into.
InstancePtr is a pointer to the driver instance. Channel is an enum of XDpDma_ChannelType. ChannelState is an enum of type XDpDma_ChannelState. XST_SUCCESS when the mentioned channel is enabled successfully. XST_FAILURE when the mentioned channel fails to be enabled. None.
Referenced by DpPsu_Run, XDpDma_InterruptHandler, XDpDma_VSyncHandler.
int XDpDma_SetVideoFormat(XDpDma *InstancePtr, XAVBuf_VideoFormat Format)
This function allocates DPDMA Video Channels depending on the number of planes in the video.
InstancePtr is a pointer to the driver instance. Format is the video format to be used for the DPDMA transfer XST_SUCCESS, When the format is valid Video Format. XST_FAILURE, When the format is not valid Video Format None.
int XDpDma_SetGraphicsFormat(XDpDma *InstancePtr, XAVBuf_VideoFormat Format)
This function allocates DPDMA Graphics Channels.
InstancePtr is a pointer to the driver instance. Format is the video format to be used for the DPDMA transfer XST_SUCCESS, When the format is a valid Graphics Format. XST_FAILURE, When the format is not valid Graphics Format. None.
Referenced by InitDpDmaSubsystem.
void XDpDma_SetQOS(XDpDma *InstancePtr, u8 QOS)
This function starts the operation on the a given channel.
InstancePtr is a pointer to the driver instance. QOS is the Quality of Service value to be selected. None. .
References XDPDMA_CH0_CNTL, XDpDma_ReadModifyWrite.
Referenced by InitDpDmaSubsystem.
int XDpDma_Trigger(XDpDma *InstancePtr, XDpDma_ChannelType Channel)
This function Triggers DPDMA to start the transaction.
InstancePtr is a pointer to the XDpDma instance. Channel is the XDpDma_ChannelType on which the transaction is to be triggered. XST_SUCCESS The channel has successfully been Triggered. XST_FAILURE When the triggering Video and Graphics channel without setting the Video Formats. None.
References XDPDMA_GBL, XDpDma_WriteReg.
Referenced by XDpDma_VSyncHandler.
int XDpDma_ReTrigger(XDpDma *InstancePtr, XDpDma_ChannelType Channel)
This function Retriggers DPDMA to fetch data from new descriptor.
InstancePtr is a pointer to the XDpDma instance. Channel is the XDpDma_ChannelType on which the transaction is to be retriggered. XST_SUCCESS The channel has successfully been Triggered. XST_FAILURE When the triggering Video and Graphics channel without setting the Video Formats. None.
References XDPDMA_GBL, XDpDma_WriteReg.
Referenced by XDpDma_VSyncHandler.
void XDpDma_InitVideoDescriptor(XDpDma_Descriptor *CurrDesc, XDpDma_FrameBuffer *FrameBuffer)
This function initializes Video Descriptor for Video and Graphics channel.
CurrDesc is a pointer to the current Descriptor of Video or Graphics Channel. FrameBuffer is a pointer to the Frame Buffer structure None. None.
Referenced by XDpDma_SetupChannel.
void XDpDma_InitAudioDescriptor(XDpDma_AudioChannel *Channel, XDpDma_AudioBuffer *AudioBuffer)
This function initializes Descriptors for transactions on Audio Channel.
Channel is a pointer to the XDpDma_AudioChannel instance AudioBuffer is a pointer to the Audio Buffer structure None. None.
Referenced by XDpDma_PlayAudio, XDpDma_SetupChannel.
void XDpDma_DisplayVideoFrameBuffer(XDpDma *InstancePtr, XDpDma_FrameBuffer *Plane0, XDpDma_FrameBuffer *Plane1, XDpDma_FrameBuffer *Plane2)
This function sets the next Frame Buffers to be displayed on the Video Channel.
InstancePtr is pointer to the instance of DPDMA. Plane0 is a pointer to the Frame Buffer structure. Plane1 is a pointer to the Frame Buffer structure. Plane2 is a pointer to the Frame Buffer structure. None. For interleaved mode use Plane0. For semi-planar mode use Plane0 and Plane1. For planar mode use Plane0, Plane1 and Plane2
void XDpDma_DisplayGfxFrameBuffer(XDpDma *InstancePtr, XDpDma_FrameBuffer *Plane)
This function sets the next Frame Buffers to be displayed on the Graphics Channel.
InstancePtr is pointer to the instance of DPDMA. Plane is a pointer to the Frame Buffer structure. None. None.
Referenced by DpPsu_Run.
int XDpDma_PlayAudio(XDpDma *InstancePtr, XDpDma_AudioBuffer *Buffer, u8 ChannelNum)
This function sets the next Audio Buffer to be played on Audio Channel 0.
InstancePtr is pointer to the instance of DPDMA. Buffer is a pointer to the attributes of the Audio information to be played. ChannelNum selects between Audio Channel 0 and Audio Channel 1 XST_SUCCESS when the play audio request is successful. XST_FAILURE when the play audio request fails, user has to retry to play the audio. The user has to schedule new audio buffer before half the audio information is consumed by DPDMA to have a seamless playback.
References XDpDma_InitAudioDescriptor.
void XDpDma_SetupChannel(XDpDma *InstancePtr, XDpDma_ChannelType Channel)
This function sets the channel with the latest framebuffer and the available descriptor for transfer on the next Vsync.
InstancePtr is pointer to the instance of DPDMA. Channel indicates which channels are being setup for transfer. None. None.
References XDpDma_InitAudioDescriptor, XDpDma_InitVideoDescriptor.
Referenced by XDpDma_VSyncHandler.