xdppsu_interrupt.c
XDpDma_FrameBuffer FrameBuffer
static u32 DpPsu_Wakeup(Run_Config *RunCfgPtr)
This function is called to wake-up the monitor from sleep.
RunCfgPtr is a pointer to the application configuration structure. None. None.
static u32 DpPsu_Hpd_Train(Run_Config *RunCfgPtr)
This function is called to initiate training with the source device, using the predefined source configuration as well as the sink capabilities.
RunCfgPtr is a pointer to the application configuration structure. XST_SUCCESS if the function executes correctly. XST_FAILURE if the function fails to execute correctly None.
void DpPsu_Run(Run_Config *RunCfgPtr)
This function will configure and establish a link with the receiver device, afterwards, a video stream will start to be sent over the main link.
RunCfgPtr is a pointer to the application configuration structure. XST_SUCCESS if main link was successfully established.XST_FAILURE otherwise. None.
References DpPsu_SetupVideoStream, InitDpDmaSubsystem, XDpDma_DisplayGfxFrameBuffer, XDpDma_SetChannelState.
Referenced by DpPsu_IsrHpdEvent.
void DpPsu_IsrHpdEvent(void *ref)
This function is called when a Hot-Plug-Detect (HPD) event is received by the DisplayPort TX core.
The XDPPSU_INTERRUPT_STATUS_HPD_EVENT_MASK bit of the core's XDPPSU_INTERRUPT_STATUS register indicates that an HPD event has occurred. InstancePtr is a pointer to the XDpPsu instance. None. Use the XDpPsu_SetHpdEventHandler driver function to set this function as the handler for HPD pulses.
References DpPsu_Run.
Referenced by SetupInterrupts.
void DpPsu_IsrHpdPulse(void *ref)
This function is called when a Hot-Plug-Detect (HPD) pulse is received by the DisplayPort TX core.
The XDPPSU_INTERRUPT_STATUS_HPD_PULSE_DETECTED_MASK bit of the core's XDPPSU_INTERRUPT_STATUS register indicates that an HPD event has occurred. InstancePtr is a pointer to the XDpPsu instance. None. Use the XDpPsu_SetHpdPulseHandler driver function to set this function as the handler for HPD pulses.
References DpPsu_SetupVideoStream.
Referenced by SetupInterrupts.
void DpPsu_SetupVideoStream(Run_Config *RunCfgPtr)
This function is called to setup the VideoStream with its video and MSA attributes.
RunCfgPtr is a pointer to the application configuration structure. None. Use the XDpPsu_SetHpdEventHandler driver function to set this function as the handler for HPD pulses.
Referenced by DpPsu_IsrHpdPulse, DpPsu_Run.