xpciepsu.c
u32 XPciePsu_ReadReg(UINTPTR BaseAddr, u32 RegOffset)
This function reads a register value from specified offset.
BaseAddr BaseAddr of the register RegOffset Offset from the base address to be read Register value
Referenced by main, XPciePsu_Egress_EP_BridgeInitialize, XPciePsu_EP_BridgeInitialize, XPciePsu_EP_IntrHandler, XPciePsu_EP_SetupEgress, XPciePsu_EP_SetupIngress, XPciePsu_EP_WaitForEnumeration, XPciePsu_EP_WaitForLinkup, XPciePsu_ReadConfigSpace, XPciePsu_ReadLocalConfigSpace, XPciePsu_WriteConfigSpace.
void XPciePsu_WriteReg(UINTPTR BaseAddr, u32 RegOffset, u32 Val)
This function writes a register value to specified offset.
BaseAddr Base Address of the register RegOffset Offset from the base address to be written Val Value to be written none
Referenced by main, XPciePsu_Egress_EP_BridgeInitialize, XPciePsu_EP_BridgeInitialize, XPciePsu_EP_IntrHandler, XPciePsu_EP_SetupEgress, XPciePsu_EP_SetupIngress, XPciePsu_WriteConfigSpace, XPciePsu_WriteLocalConfigSpace.
static u32 XPciePsu_GetMaxBusNo(u32 EcamSize)
This function writes a register value to specified offset.
BaseAddr Base Address of the register RegOffset Offset from the base address to be written Val Value to be written none This function gets the Maximum supported Bus Number EcamSize Size of the ECAM space Maximum supported number of buses
static int XPciePsu_PhyReady(XPciePsu_Config *InstancePtr)
This function looks for phy is ready or not.
InstancePtr pointer to XPciePsu_Config Instance Pointer 1 if phy is ready 0 if phy is not ready
static int XPciePsu_PcieLinkUp(XPciePsu_Config *InstancePtr)
This function looks for PCIe link is up or not.
InstancePtr pointer to XPciePsu_Config Instance Pointer 1 if link is up 0 if link is down
static int XPciePsu_PcieLinkUpTimeout(XPciePsu_Config *InstancePtr)
This function waits for phy link to come up till XPCIEPSU_LINK_WAIT_MAX_RETRIES times.
InstancePtr pointer to XPciePsu_Config Instance Pointer 1 if link is up 0 if link up fail
static int XPciePsu_BridgeInit(XPciePsu *InstancePtr)
This function initializes PCIe bridge.
Enables/Disables required channels, checks for links, ECAM, Interrupts. InstancePtr pointer to XPciePsu Instance Pointer 0 if success error value on failure
u32 XPciePsu_ComposeExternalConfigAddress(u8 Bus, u8 Device, u8 Function, u16 Offset)
This function Composes configuration space location.
Bus Device Function Offset location address of the composed address
References XPCIEPSU_ECAM_BUS_MASK, XPCIEPSU_ECAM_BUS_SHIFT, XPCIEPSU_ECAM_DEV_MASK, XPCIEPSU_ECAM_DEV_SHIFT, XPCIEPSU_ECAM_FUN_MASK, XPCIEPSU_ECAM_FUN_SHIFT, XPCIEPSU_ECAM_MASK, XPCIEPSU_ECAM_REG_MASK, XPCIEPSU_ECAM_REG_SHIFT.
Referenced by XPciePsu_ReadConfigSpace, XPciePsu_WriteConfigSpace.
u8 XPciePsu_ReadConfigSpace(XPciePsu *InstancePtr, u8 Bus, u8 Device, u8 Function, u16 Offset, u32 *DataPtr)
This function read from remote configuration space location.
InstancePtr pointer to XPciePsu Instance Pointer Bus Device Function Offset location of the address to read data from. DataPtr pointer store date available in the offset XST_SUCCESS on success XST_FAILURE on failure.
References XPciePsu_ComposeExternalConfigAddress, XPciePsu_ReadReg.
Referenced by XPciePsu_HasCapability, XPciePsu_PrintAllCapabilites.
u8 XPciePsu_WriteConfigSpace(XPciePsu *InstancePtr, u8 Bus, u8 Device, u8 Function, u16 Offset, u32 Data)
This function write to remote configuration space location.
InstancePtr pointer to XPciePsu Instance Pointer Bus Device Function Offset location of the address to write data. Data to be written on to the offset XST_SUCCESS on success XST_FAILURE on failure.
References XPciePsu_ComposeExternalConfigAddress, XPciePsu_ReadReg, XPciePsu_WriteReg.
u8 XPciePsu_ReadLocalConfigSpace(XPciePsu *InstancePtr, u16 Offset, u32 *DataPtr)
Read 32-bit value from one of this IP own configuration space.
Location is identified by its offset from the beginning of the configuration space. InstancePtr is the XPciePsu instance to operate on. Offset from beginning of IP own configuration space. DataPtr is a pointer to a variable where the driver will pass back the value read from the specified location. XST_SUCCESS on success XST_FAILURE on failure. None
References XPciePsu_ReadReg.
Referenced by PcieInitRootComplex.
u8 XPciePsu_WriteLocalConfigSpace(XPciePsu *InstancePtr, u16 Offset, u32 Data)
Write 32-bit value to one of this IP own configuration space.
Location is identified by its offset from the beginning of the configuration space. InstancePtr is the PCIe component to operate on. Offset from beggininng of IP own configuration space. Data to be written to the specified location. XST_SUCCESS on success XST_FAILURE on failure. This function is valid only when IP is configured as a root complex.
References XPciePsu_WriteReg.
Referenced by PcieInitRootComplex.
static u32 XPciePsu_PositionRightmostSetbit(u64 Size)
static u32 XPciePsu_ReserveBarMem(XPciePsu *InstancePtr, u32 Size)
This function reserves bar memory address.
InstancePtr pointer to XPciePsu Instance Pointer BarType differentiate 32 or 64 bit bar type Size of the Bar Request bar address
int XPciePsu_CompareSizes(const void *FirstReqSize, const void *SecondReqSize)
This function Compare two different sizes.
FirstReqSize is First Variable to compare size SecondReqSize is Second Variable to compare size Difference of sizes, Zero for Equal
static void XPciePsu_AlignBarResources(u64 *Value, u8 MaxBars, u32 *Index)
This function Aligns BAR Resources.
Value Combination of Location and Offset value MaxBars Maximum Requested BARs Index is a Bar Numbers void
static void XPciePsu_BarMemoryAlloc(XPciePsu *InstancePtr, u8 Bus, u8 Device, u8 Function, u64 *Value, u8 MaxBars, u32 *Index, u64 *Size, u8 BarAllocControl)
This function Allocates Bar Memory.
InstancePtr pointer to XPciePsu Instance Pointer Bus Device Function Value is a Combination of Location and Offset value MaxBars Maximum Requested BARs,6 for EP and 2 for bridge Index is a BAR Number Size of the Bar Request BarAllocControl is to differentiate Unsorted and Sorted Bar Sizes Void
static int XPciePsu_AllocBarSpace(XPciePsu *InstancePtr, u32 Headertype, u8 Bus, u8 Device, u8 Function)
This function Composes configuration space location.
InstancePtr pointer to XPciePsu Instance Pointer headerType u32 type0 or type1 header Bus Device Function int XST_SUCCESS on success err on fail
static void XPciePsu_IncreamentNpMem(XPciePsu *InstancePtr)
This function increments to next 1Mb page starting position of non prefetchable memory.
InstancePtr pointer to XPciePsu Instance Pointer
static void XPciePsu_FetchDevicesInBus(XPciePsu *InstancePtr, u8 BusNum)
This function discovers the system topology and assigns bus numbers and system resources.
Assigns primary, secondary and subordinate bus numbers. Assigns memory to prefetchable and non-prefetchable memory locations. enables end-points and bridges. InstancePtr pointer to XPciePsu Instance Pointer bus_num to scans for connected bridges/endpoints on it. none
u8 XPciePsu_EnumerateBus(XPciePsu *InstancePtr)
This function starts PCIe enumeration.
InstancePtr pointer to XPciePsu Instance Pointer 1 if success 0 if fails
Referenced by main.
u32 XPciePsu_CfgInitialize(XPciePsu *InstancePtr, const XPciePsu_Config *CfgPtr, UINTPTR EffectiveBrgAddress)
This function initializes the config space and PCIe bridge.
InstancePtr pointer to XPciePsu Instance Pointer CfgPtr pointer to XPciePsu_Config instrance Pointer. EffectiveBrgAddress config brigReg address XST_SUCCESS on success err on failure
Referenced by PcieInitRootComplex.