xpciepsu_ep.c
void XPciePsu_EP_CfgInitialize(XPciePsu *PciePsuPtr, const XPciePsu_Config *ConfigPtr)
This function initializes the config space.
PciePsuPtr pointer to XPciePsu Instance Pointer ConfigPtr pointer to XPciePsu_Config instrance Pointer. XST_SUCCESS on success err on failure
Referenced by XPciePsu_InitEndPoint.
void XPciePsu_EP_BridgeInitialize(XPciePsu *PciePsuPtr)
This function initializes PCIe bridge.
PciePsuPtr pointer to XPciePsu Instance Pointer
References XPciePsu_ReadReg, XPciePsu_WriteReg.
void XPciePsu_Egress_EP_BridgeInitialize(XPciePsu *PciePsuPtr)
This function initializes Egress PCIe bridge.
PciePsuPtr pointer to XPciePsu Instance Pointer
References XPciePsu_ReadReg, XPciePsu_WriteReg.
Referenced by main.
void XPciePsu_EP_WaitForLinkup(XPciePsu *PciePsuPtr)
This function waits for Pcie link to come up.
PciePsuPtr pointer to XPciePsu_Config Instance Pointer
References XPciePsu_ReadReg.
Referenced by main.
void XPciePsu_EP_WaitForEnumeration(XPciePsu *PciePsuPtr)
This function waits for host to enumerate.
On x86 BIOS sets memory enable bit On ARM64 it is set when driver gets inserted PciePsuPtr pointer to XPciePsu_Config Instance Pointer
References XPciePsu_ReadReg.
static void XPciePSU_ReadBar(XPciePsu *PciePsuPtr, u32 BarNum, u32 *BarLo, u32 *BarHi)
This function read bar address of specific bar number.
PciePsuPtr pointer to XPciePsu_Config Instance Pointer BarNum BarLo BarHi
void Do_Egress_Test(u32 *egress_src_lo)
This function does Egress test.
egress source address
Referenced by XPciePsu_EP_SetupEgress.
int XPciePsu_EP_SetupIngress(XPciePsu *PciePsuPtr, u32 IngressNum, u32 BarNum, u64 Dst)
This function sets up ingress translation.
PciePsuPtr pointer to XPciePsu_Config Instance Pointer IngressNum ingress must be 0 to 7 BarNum bar no to setup ingress Dst 32 or 64 bit destination address XST_SUCCESS if setup is successful XST_FAILURE if setup is fail
References XPciePsu_ReadReg, XPciePsu_WriteReg.
int XPciePsu_EP_SetupEgress(XPciePsu *PciePsuPtr, u32 EgressNum)
This function sets up Egress translation.
PciePsuPtr pointer to XPciePsu_Config Instance Pointer EgressNum ingress must be 0 to 7 XST_SUCCESS if setup is successful XST_FAILURE if setup is fail
References Do_Egress_Test, XPciePsu_ReadReg, XPciePsu_WriteReg.
Referenced by main.