xpciepsu_egress_ep_enable_example.c
EGRESS_NUM
PS_PCIE_AXI_INTR_ID
XPciePsu PciePsuInstance
XScuGic INTCinst
int XPciePsu_InitEndPoint(XPciePsu *PciePsuPtr, UINTPTR BrigReg)
This function initializes a PSU PCIe EndPoint complex.
PciePsuPtr is a pointer to an instance of XPciePsu data structure represents a root complex. DeviceId is PSU PCIe root complex unique ID - XST_SUCCESS if successful. XST_FAILURE if unsuccessful. None.
References XPciePsu_EP_CfgInitialize, XPciePsu_LookupConfig.
Referenced by main.
void XPciePsu_EP_IntrHandler(XPciePsu *PciePsuPtr)
This function handles doorbell interrupts for PCIE Endpoint.
PciePsuPtr is a pointer to an instance of XPciePsu data -None None
References XPciePsu_ReadReg, XPciePsu_WriteReg.
Referenced by XPciePsu_EP_InitIntr.
int XPciePsu_EP_InitIntr(void)
This function Initializes interrupts for PCIe EndPoint.
None - XST_SUCCESS if successful XST_FAILURE if unsuccessful None
References XPciePsu_EP_IntrHandler.
Referenced by main.
int main()
This function is the entry point for PCIe EndPoint Example.
None - XST_SUCCESS if successful XST_FAILURE if unsuccessful. None.
References XPciePsu_Egress_EP_BridgeInitialize, XPciePsu_EP_InitIntr, XPciePsu_EP_SetupEgress, XPciePsu_EP_WaitForLinkup, XPciePsu_InitEndPoint, XPciePsu_ReadReg, XPciePsu_WriteReg.