xpciepsu_ep.h
INGRESS_SIZE
COMMAND_REG
BAR0_OFFSET_LO
BAR0_OFFSET_HI
PCIE_ENUMERATED_STATUS
PCIE_DMA_REG_ACCESS_DISABLE
ECAM_BASE
EGRESS_SRC_LO
EGRESS_SRC_HI
HANDSHAKE_DONE_OFFSET
HANDSHAKE_DONE
EGRESS_BUF_ADDR0_OFFSET
EGRESS_BUF_ADDR1_OFFSET
DREG_CONTROL
DREG_BASE_LO
DREG_BASE_HI
INGRESS0_CONTROL
INGRESS0_SRC_BASE_LO
INGRESS0_SRC_BASE_HI
INGRESS0_DST_BASE_LO
INGRESS0_DST_BASE_HI
EGRESS0_CONTROL
EGRESS0_SRC_BASE_LO
EGRESS0_SRC_BASE_HI
EGRESS0_DST_BASE_LO
EGRESS0_DST_BASE_HI
MSGF_DMA_MASK
PCIE_LINK_UP
ECAM_ENABLE
INGRESS_ENABLE
INGRESS_SECURITY_ENABLE
DMA_ENABLE
BREG_SIZE
DMA0_CHAN_AXI_INTR
AXI_INTR_ENABLE
MSGF_DMA_INTR_ENABLE
BREG_SIZE_SHIFT
INGRESS_SIZE_SHIFT
BREG_SIZE_MASK
INGRESS_SIZE_MASK
INGRESS_SIZE_ENCODING
INGRESS_RD_WR_ATTR
ENUMERATION_WAIT_TIME
DMA0_CHAN_AXI_INTR_STATUS
AXI_INTR_STATUS
DMA0_CHAN_SCRATCH0
DMA_PCIE_INTR_ASSRT_REG_OFFSET
PCIE_INTR_STATUS
INGRESS_TEST_DONE
INGRESS_MIN_SIZE
INGRESS_TRANS_SET_OFFSET
EGRESS_SIZE
EGRESS_SIZE_SHIFT
EGRESS_ENABLE
EGRESS_SECURITY_ENABLE
EGRESS_SIZE_MASK
EGRESS_SIZE_ENCODING
EGRESS_MIN_SIZE
EGRESS_TEST_DONE
void XPciePsu_EP_BridgeInitialize(XPciePsu *PciePsuPtr)
This function initializes PCIe bridge.
PciePsuPtr pointer to XPciePsu Instance Pointer
References XPciePsu_ReadReg, XPciePsu_WriteReg.
void XPciePsu_EP_CfgInitialize(XPciePsu *PciePsuPtr, const XPciePsu_Config *ConfigPtr)
This function initializes the config space.
PciePsuPtr pointer to XPciePsu Instance Pointer ConfigPtr pointer to XPciePsu_Config instrance Pointer. XST_SUCCESS on success err on failure
Referenced by XPciePsu_InitEndPoint.
void XPciePsu_EP_WaitForLinkup(XPciePsu *PciePsuPtr)
This function waits for Pcie link to come up.
PciePsuPtr pointer to XPciePsu_Config Instance Pointer
References XPciePsu_ReadReg.
Referenced by main.
void XPciePsu_EP_WaitForEnumeration(XPciePsu *PciePsuPtr)
This function waits for host to enumerate.
On x86 BIOS sets memory enable bit On ARM64 it is set when driver gets inserted PciePsuPtr pointer to XPciePsu_Config Instance Pointer
References XPciePsu_ReadReg.
int XPciePsu_EP_SetupIngress(XPciePsu *PciePsuPtr, u32 IngressNum, u32 BarNum, u64 Dst)
This function sets up ingress translation.
PciePsuPtr pointer to XPciePsu_Config Instance Pointer IngressNum ingress must be 0 to 7 BarNum bar no to setup ingress Dst 32 or 64 bit destination address XST_SUCCESS if setup is successful XST_FAILURE if setup is fail
References XPciePsu_ReadReg, XPciePsu_WriteReg.
void XPciePsu_Egress_EP_BridgeInitialize(XPciePsu *PciePsuPtr)
This function initializes Egress PCIe bridge.
PciePsuPtr pointer to XPciePsu Instance Pointer
References XPciePsu_ReadReg, XPciePsu_WriteReg.
Referenced by main.
void Do_Egress_Test(u32 *egress_src_lo)
This function does Egress test.
egress source address
Referenced by XPciePsu_EP_SetupEgress.
int XPciePsu_EP_SetupEgress(XPciePsu *PciePsuPtr, u32 IngressNum)
This function sets up Egress translation.
PciePsuPtr pointer to XPciePsu_Config Instance Pointer EgressNum ingress must be 0 to 7 XST_SUCCESS if setup is successful XST_FAILURE if setup is fail
References Do_Egress_Test, XPciePsu_ReadReg, XPciePsu_WriteReg.
Referenced by main.