xnandpsu_bbm.h
XNANDPSU_BBM_H
XNANDPSU_BLOCK_GOOD
Block is good.
Referenced by XNandPsu_IsBlockBad.
XNANDPSU_BLOCK_BAD
Block is bad.
Referenced by XNandPsu_MarkBlockBad.
XNANDPSU_BLOCK_RESERVED
Reserved block.
Referenced by XNandPsu_IsBlockBad.
XNANDPSU_BLOCK_FACTORY_BAD
Factory marked bad block.
XNANDPSU_FLASH_BLOCK_GOOD
Block is good.
XNANDPSU_FLASH_BLOCK_BAD
Block is bad.
XNANDPSU_FLASH_BLOCK_RESERVED
Reserved block.
XNANDPSU_FLASH_BLOCK_FAC_BAD
Factory marked bad block.
XNANDPSU_BBT_SCAN_2ND_PAGE
Scan the second page for bad block information.
Referenced by XNandPsu_InitBbtDesc.
XNANDPSU_BBT_DESC_PAGE_OFFSET
Page offset of Bad Block Table Desc.
Referenced by XNandPsu_InitBbtDesc.
XNANDPSU_BBT_DESC_SIG_OFFSET
Bad Block Table signature offset.
Referenced by XNandPsu_InitBbtDesc.
XNANDPSU_BBT_DESC_VER_OFFSET
Bad block Table version offset.
Referenced by XNandPsu_InitBbtDesc.
XNANDPSU_NO_OOB_BBT_DESC_SIG_OFFSET
Bad Block Table signature offset in page memory.
XNANDPSU_NO_OOB_BBT_DESC_VER_OFFSET
Bad block Table version offset in page memory.
XNANDPSU_BBT_DESC_SIG_LEN
Bad block Table signature length.
Referenced by XNandPsu_InitBbtDesc.
XNANDPSU_BBT_DESC_MAX_BLOCKS
Bad block Table max blocks.
Referenced by XNandPsu_InitBbtDesc.
XNANDPSU_BBT_BLOCK_SHIFT
Block shift value for a block in BBT.
Referenced by XNandPsu_IsBlockBad, XNandPsu_MarkBlockBad, XNandPsu_ScanBbt.
XNANDPSU_BBT_ENTRY_NUM_BLOCKS
Num of blocks in one BBT entry.
XNANDPSU_BB_PTRN_OFF_SML_PAGE
Bad block pattern offset in a page.
Referenced by XNandPsu_InitBbtDesc.
XNANDPSU_BB_PTRN_LEN_SML_PAGE
Bad block pattern length.
Referenced by XNandPsu_InitBbtDesc.
XNANDPSU_BB_PTRN_OFF_LARGE_PAGE
Bad block pattern offset in a large page.
Referenced by XNandPsu_InitBbtDesc.
XNANDPSU_BB_PTRN_LEN_LARGE_PAGE
Bad block pattern length.
Referenced by XNandPsu_InitBbtDesc.
XNANDPSU_BB_PATTERN
Bad block pattern to search in a page.
Referenced by XNandPsu_InitBbtDesc.
XNANDPSU_BLOCK_TYPE_MASK
Block type mask.
Referenced by XNandPsu_IsBlockBad, XNandPsu_MarkBlockBad.
XNANDPSU_BLOCK_SHIFT_MASK
Block shift mask for a Bad Block Table entry byte.
XNANDPSU_ONDIE_SIG_OFFSET
XNANDPSU_ONDIE_VER_OFFSET
XNANDPSU_BBT_VERSION_LENGTH
XNANDPSU_BBT_SIG_LENGTH
XNANDPSU_BBT_BUF_LENGTH
XNandPsu_BbtBlockShift
This macro returns the Block shift value corresponding to a Block.
Block is the block number. Block shift value None.
Referenced by XNandPsu_IsBlockBad, XNandPsu_MarkBlockBad.
void XNandPsu_InitBbtDesc(XNandPsu *InstancePtr)
This function initializes the Bad Block Table(BBT) descriptors with a predefined pattern for searching Bad Block Table(BBT) in flash.
InstancePtr is a pointer to the XNandPsu instance. NONE
References XNandPsu::BbPattern, XNandPsu::BbtDesc, XNandPsu::BbtMirrorDesc, XNandPsu_Geometry::BytesPerPage, XNandPsu::EccMode, XNandPsu::Geometry, XNandPsu_BadBlockPattern::Length, XNandPsu_BbtDesc::MaxBlocks, XNandPsu_Geometry::NumTargetBlocks, XNandPsu_BadBlockPattern::Offset, XNandPsu_BadBlockPattern::Options, XNandPsu_BbtDesc::PageOffset, XNandPsu_BadBlockPattern::Pattern, XNandPsu_BbtDesc::SigLength, XNandPsu_BbtDesc::Signature, XNandPsu_BbtDesc::SigOffset, XNandPsu_BbtDesc::Valid, XNandPsu_BbtDesc::VerOffset, XNandPsu_BbtDesc::Version, XNANDPSU_BB_PATTERN, XNANDPSU_BB_PTRN_LEN_LARGE_PAGE, XNANDPSU_BB_PTRN_LEN_SML_PAGE, XNANDPSU_BB_PTRN_OFF_LARGE_PAGE, XNANDPSU_BB_PTRN_OFF_SML_PAGE, XNANDPSU_BBT_DESC_MAX_BLOCKS, XNANDPSU_BBT_DESC_PAGE_OFFSET, XNANDPSU_BBT_DESC_SIG_LEN, XNANDPSU_BBT_DESC_SIG_OFFSET, XNANDPSU_BBT_DESC_VER_OFFSET, XNANDPSU_BBT_SCAN_2ND_PAGE, XNANDPSU_MAX_TARGETS.
Referenced by XNandPsu_CfgInitialize.
s32 XNandPsu_IsBlockBad(XNandPsu *InstancePtr, u32 Block)
This function checks whether a block is bad or not.
InstancePtr is the pointer to the XNandPsu instance. Block is the block number. XST_SUCCESS if successful.XST_FAILURE if fail.
References XNandPsu::Bbt, XNandPsu::IsReady, XNANDPSU_BBT_BLOCK_SHIFT, XNandPsu_BbtBlockShift, XNANDPSU_BLOCK_GOOD, XNANDPSU_BLOCK_RESERVED, XNANDPSU_BLOCK_TYPE_MASK.
Referenced by XNandPsu_Erase, XNandPsu_Read, XNandPsu_Write.