xnandpsu_bbm.c
static s32 XNandPsu_ReadBbt(XNandPsu *InstancePtr, u32 Target)
< For Xil_MemCpy and memset
This function searches the Bad Block Table(BBT) in flash and loads into the memory based Bad Block Table(BBT). InstancePtr is the pointer to the XNandPsu instance. XST_SUCCESS if successful.XST_FAILURE if fail.
static s32 XNandPsu_SearchBbt(XNandPsu *InstancePtr, XNandPsu_BbtDesc *Desc, u32 Target)
This function searches the BBT in flash.
InstancePtr is the pointer to the XNandPsu instance. Desc is the BBT descriptor pattern to search. XST_SUCCESS if successful.XST_FAILURE if fail.
static void XNandPsu_CreateBbt(XNandPsu *InstancePtr, u32 Target)
This function scans the NAND flash for factory marked bad blocks and creates a RAM based Bad Block Table(BBT).
InstancePtr is a pointer to the XNandPsu instance. NONE
static void XNandPsu_ConvertBbt(XNandPsu *InstancePtr, u8 *Buf, u32 Target)
This function converts the Bad Block Table(BBT) read from the flash to the RAM based Bad Block Table(BBT).
InstancePtr is a pointer to the XNandPsu instance. Buf is the buffer which contains BBT read from flash. NONE.
static s32 XNandPsu_WriteBbt(XNandPsu *InstancePtr, XNandPsu_BbtDesc *Desc, XNandPsu_BbtDesc *MirrorDesc, u32 Target)
This function writes Bad Block Table(BBT) from RAM to flash.
InstancePtr is the pointer to the XNandPsu instance. Desc is the BBT descriptor to be written to flash. MirrorDesc is the mirror BBT descriptor. XST_SUCCESS if successful.XST_FAILURE if fail.
static s32 XNandPsu_MarkBbt(XNandPsu *InstancePtr, XNandPsu_BbtDesc *Desc, u32 Target)
This function marks the block containing Bad Block Table as reserved and updates the BBT.
InstancePtr is the pointer to the XNandPsu instance. Desc is the BBT descriptor pointer. XST_SUCCESS if successful.XST_FAILURE if fail.
static s32 XNandPsu_UpdateBbt(XNandPsu *InstancePtr, u32 Target)
This function updates the primary and mirror Bad Block Table(BBT) in the flash.
InstancePtr is the pointer to the XNandPsu instance. XST_SUCCESS if successful.XST_FAILURE if fail.
void XNandPsu_InitBbtDesc(XNandPsu *InstancePtr)
This function initializes the Bad Block Table(BBT) descriptors with a predefined pattern for searching Bad Block Table(BBT) in flash.
InstancePtr is a pointer to the XNandPsu instance. NONE
References XNandPsu::BbPattern, XNandPsu::BbtDesc, XNandPsu::BbtMirrorDesc, XNandPsu_Geometry::BytesPerPage, XNandPsu::EccMode, XNandPsu::Geometry, XNandPsu_BadBlockPattern::Length, XNandPsu_BbtDesc::MaxBlocks, XNandPsu_Geometry::NumTargetBlocks, XNandPsu_BadBlockPattern::Offset, XNandPsu_BadBlockPattern::Options, XNandPsu_BbtDesc::PageOffset, XNandPsu_BadBlockPattern::Pattern, XNandPsu_BbtDesc::SigLength, XNandPsu_BbtDesc::Signature, XNandPsu_BbtDesc::SigOffset, XNandPsu_BbtDesc::Valid, XNandPsu_BbtDesc::VerOffset, XNandPsu_BbtDesc::Version, XNANDPSU_BB_PATTERN, XNANDPSU_BB_PTRN_LEN_LARGE_PAGE, XNANDPSU_BB_PTRN_LEN_SML_PAGE, XNANDPSU_BB_PTRN_OFF_LARGE_PAGE, XNANDPSU_BB_PTRN_OFF_SML_PAGE, XNANDPSU_BBT_DESC_MAX_BLOCKS, XNANDPSU_BBT_DESC_PAGE_OFFSET, XNANDPSU_BBT_DESC_SIG_LEN, XNANDPSU_BBT_DESC_SIG_OFFSET, XNANDPSU_BBT_DESC_VER_OFFSET, XNANDPSU_BBT_SCAN_2ND_PAGE, XNANDPSU_MAX_TARGETS.
Referenced by XNandPsu_CfgInitialize.
s32 XNandPsu_ScanBbt(XNandPsu *InstancePtr)
This function reads the Bad Block Table(BBT) if present in flash.
If not it scans the flash for detecting factory marked bad blocks and creates a bad block table and write the Bad Block Table(BBT) into the flash. InstancePtr is a pointer to the XNandPsu instance. XST_SUCCESS if successful.XST_FAILURE if fail.
References XNandPsu::Bbt, XNandPsu::BbtDesc, XNandPsu::BbtMirrorDesc, XNandPsu::Geometry, XNandPsu::IsReady, XNandPsu_Geometry::NumBlocks, XNandPsu_Geometry::NumTargets, XNANDPSU_BBT_BLOCK_SHIFT.
Referenced by XNandPsu_CfgInitialize.
s32 XNandPsu_IsBlockBad(XNandPsu *InstancePtr, u32 Block)
This function checks whether a block is bad or not.
InstancePtr is the pointer to the XNandPsu instance. Block is the block number. XST_SUCCESS if successful.XST_FAILURE if fail.
References XNandPsu::Bbt, XNandPsu::IsReady, XNANDPSU_BBT_BLOCK_SHIFT, XNandPsu_BbtBlockShift, XNANDPSU_BLOCK_GOOD, XNANDPSU_BLOCK_RESERVED, XNANDPSU_BLOCK_TYPE_MASK.
Referenced by XNandPsu_Erase, XNandPsu_Read, XNandPsu_Write.
s32 XNandPsu_MarkBlockBad(XNandPsu *InstancePtr, u32 Block)
This function marks a block as bad in the RAM based Bad Block Table(BBT).
It also updates the Bad Block Table(BBT) in the flash. InstancePtr is the pointer to the XNandPsu instance. Block is the block number. XST_SUCCESS if successful.XST_FAILURE if fail.
References XNandPsu::Bbt, XNandPsu::Geometry, XNandPsu::IsReady, XNandPsu_Geometry::NumTargetBlocks, XNANDPSU_BBT_BLOCK_SHIFT, XNandPsu_BbtBlockShift, XNANDPSU_BLOCK_BAD, XNANDPSU_BLOCK_TYPE_MASK.