xnandpsu.h
XNANDPSU_H
XNANDPSU_DEBUG
XNANDPSU_MAX_TARGETS
ce_n0, ce_n1
Referenced by XNandPsu_InitBbtDesc.
XNANDPSU_MAX_PKT_SIZE
Max packet size.
XNANDPSU_MAX_PKT_COUNT
Max packet count.
XNANDPSU_PAGE_SIZE_512
512 bytes page
XNANDPSU_PAGE_SIZE_2K
2K bytes page
XNANDPSU_PAGE_SIZE_4K
4K bytes page
XNANDPSU_PAGE_SIZE_8K
8K bytes page
XNANDPSU_PAGE_SIZE_16K
16K bytes page
XNANDPSU_PAGE_SIZE_1K_16BIT
16-bit 2K bytes page
XNANDPSU_MAX_PAGE_SIZE
Max page size supported.
XNANDPSU_HAMMING
Hamming Flash.
XNANDPSU_BCH
BCH Flash.
XNANDPSU_MAX_BLOCKS
Max number of Blocks.
XNANDPSU_MAX_SPARE_SIZE
Max spare bytes of a NAND flash page of 16K.
XNANDPSU_MAX_LUNS
Max number of LUNs.
XNANDPSU_MAX_PAGES_PER_BLOCK
Max number pages per block.
XNANDPSU_INTR_POLL_TIMEOUT
XNANDPSU_SDR_CLK
XNANDPSU_NVDDR_CLK_0
XNANDPSU_NVDDR_CLK_1
XNANDPSU_NVDDR_CLK_2
XNANDPSU_NVDDR_CLK_3
XNANDPSU_NVDDR_CLK_4
XNANDPSU_NVDDR_CLK_5
XNANDPSU_MAX_TIMING_MODE
XNandPsu_SetBits
This macro sets the bitmask in the register.
InstancePtr is a pointer to the XNandPsu instance of the controller. RegOffset is the register offset. BitMask is the bitmask. C-style signature: void XNandPsu_SetBits(XNandPsu *InstancePtr, u32 RegOffset, u32 BitMask)
XNandPsu_ClrBits
This macro clears the bitmask in the register.
InstancePtr is a pointer to the XNandPsu instance of the controller. RegOffset is the register offset. BitMask is the bitmask. C-style signature: void XNandPsu_ClrBits(XNandPsu *InstancePtr, u32 RegOffset, u32 BitMask)
XNandPsu_ReadModifyWrite
This macro clears and updates the bitmask in the register.
InstancePtr is a pointer to the XNandPsu instance of the controller. RegOffset is the register offset. Mask is the bitmask. Value is the register value to write. C-style signature: void XNandPsu_ReadModifyWrite(XNandPsu *InstancePtr, u32 RegOffset, u32 Mask, u32 Val)
XNandPsu_IntrSigEnable
This macro enables bitmask in Interrupt Signal Enable register.
InstancePtr is a pointer to the XNandPsu instance of the controller. Mask is the bitmask. C-style signature: void XNandPsu_IntrSigEnable(XNandPsu *InstancePtr, u32 Mask)
XNandPsu_IntrSigClear
This macro clears bitmask in Interrupt Signal Enable register.
InstancePtr is a pointer to the XNandPsu instance of the controller. Mask is the bitmask. C-style signature: void XNandPsu_IntrSigClear(XNandPsu *InstancePtr, u32 Mask)
XNandPsu_IntrStsEnable
This macro enables bitmask in Interrupt Status Enable register.
InstancePtr is a pointer to the XNandPsu instance of the controller. Mask is the bitmask. C-style signature: void XNandPsu_IntrStsEnable(XNandPsu *InstancePtr, u32 Mask)
IS_ONFI
This macro checks for the ONFI ID.
Buff is the buffer holding ONFI ID none.
XNandPsu_DataInterface
Single Data Rate.
XNandPsu_TimingMode
XNandPsu_SWMode
Polling.
XNandPsu_DmaMode
PIO Mode.
XNandPsu_EccMode
s32 XNandPsu_CfgInitialize(XNandPsu *InstancePtr, XNandPsu_Config *ConfigPtr, u32 EffectiveAddr)
This function initializes a specific XNandPsu instance.
This function must be called prior to using the NAND flash device to read or write any data. InstancePtr is a pointer to the XNandPsu instance. ConfigPtr points to XNandPsu device configuration structure. EffectiveAddr is the base address of NAND flash controller. XST_SUCCESS if successful.XST_FAILURE if fail. The user needs to first call the XNandPsu_LookupConfig() API which returns the Configuration structure pointer which is passed as a parameter to the XNandPsu_CfgInitialize() API.
References XNandPsu_Config::BaseAddress, XNandPsu::DmaMode, XNandPsu::Ecc_Stat_PerPage_flips, XNandPsu::Ecc_Stats_total_flips, XNandPsu::EccMode, XNandPsu::Features, XNandPsu_Config::IsCacheCoherent, XNandPsu::IsReady, XNandPsu::Mode, XNandPsu_InitBbtDesc, XNANDPSU_MDMA, XNANDPSU_POLLING, XNandPsu_ScanBbt.
Referenced by NandReadWriteExample.
s32 XNandPsu_Erase(XNandPsu *InstancePtr, u64 Offset, u64 Length)
This function erases the flash.
InstancePtr is a pointer to the XNandPsu instance. Offset is the starting offset of flash to erase. Length is the number of bytes to erase. XST_SUCCESS if successful.XST_FAILURE if failed. The Offset and Length should be aligned to block size boundary to get better results.
References XNandPsu_Geometry::BlockSize, XNandPsu_Geometry::DeviceSize, XNandPsu::Geometry, XNandPsu::IsReady, XNandPsu_Geometry::NumTargetBlocks, XNandPsu_EraseBlock, XNandPsu_IsBlockBad.
Referenced by NandReadWriteExample.
s32 XNandPsu_Write(XNandPsu *InstancePtr, u64 Offset, u64 Length, u8 *SrcBuf)
This function writes to the flash.
InstancePtr is a pointer to the XNandPsu instance. Offset is the starting offset of flash to write. Length is the number of bytes to write. SrcBuf is the source data buffer to write. XST_SUCCESS if successful.XST_FAILURE if failed. None
References XNandPsu_Geometry::BlockSize, XNandPsu_Geometry::BytesPerPage, XNandPsu_Geometry::DeviceSize, XNandPsu::Geometry, XNandPsu::IsReady, XNandPsu_Geometry::NumTargetPages, XNandPsu_Geometry::TargetSize, XNandPsu_IsBlockBad.
Referenced by NandReadWriteExample.
s32 XNandPsu_Read(XNandPsu *InstancePtr, u64 Offset, u64 Length, u8 *DestBuf)
This function reads from the flash.
InstancePtr is a pointer to the XNandPsu instance. Offset is the starting offset of flash to read. Length is the number of bytes to read. DestBuf is the destination data buffer to fill in. XST_SUCCESS if successful.XST_FAILURE if failed. None
References XNandPsu_Geometry::BlockSize, XNandPsu_Geometry::BytesPerPage, XNandPsu_Geometry::DeviceSize, XNandPsu::Geometry, XNandPsu_Config::IsCacheCoherent, XNandPsu::IsReady, XNandPsu_Geometry::NumTargetPages, XNandPsu_Geometry::TargetSize, XNandPsu_IsBlockBad.
Referenced by NandReadWriteExample.
s32 XNandPsu_EraseBlock(XNandPsu *InstancePtr, u32 Target, u32 Block)
This function sends ONFI block erase command to the flash.
InstancePtr is a pointer to the XNandPsu instance. Target is the chip select value. Block is the block to erase. XST_SUCCESS if successful.XST_FAILURE if failed. None
References XNandPsu::Geometry, XNandPsu::IsReady, ONFI_CMD_BLK_ERASE1, ONFI_CMD_BLK_ERASE2, XNandPsu_Geometry::PagesPerBlock, XNandPsu_Geometry::RowAddrCycles, XNANDPSU_INTR_STS_EN_OFFSET, XNANDPSU_INTR_STS_EN_TRANS_COMP_STS_EN_MASK, XNandPsu_Prepare_Cmd, XNANDPSU_PROG_BLK_ERASE_MASK, XNANDPSU_PROG_OFFSET, XNandPsu_WriteReg.
Referenced by XNandPsu_Erase.
s32 XNandPsu_WriteSpareBytes(XNandPsu *InstancePtr, u32 Page, u8 *Buf)
This function sends ONFI Program Page command to flash.
InstancePtr is a pointer to the XNandPsu instance. Page is the page address value to program. Buf is the data buffer to program. XST_SUCCESS if successful.XST_FAILURE if failed. None
References XNandPsu_Geometry::BytesPerPage, XNandPsu_Geometry::ColAddrCycles, XNandPsu::DmaMode, XNandPsu::EccCfg, XNandPsu::EccMode, XNandPsu::Geometry, XNandPsu_Config::IsCacheCoherent, XNandPsu::IsReady, XNandPsu_Geometry::NumTargetPages, ONFI_CMD_PG_PROG1, ONFI_CMD_PG_PROG2, XNandPsu_Geometry::RowAddrCycles, XNandPsu_Geometry::SpareBytesPerPage, XNANDPSU_INTR_STS_EN_BUFF_WR_RDY_STS_EN_MASK, XNANDPSU_INTR_STS_EN_OFFSET, XNANDPSU_INTR_STS_EN_TRANS_COMP_STS_EN_MASK, XNANDPSU_MDMA, XNandPsu_Prepare_Cmd, XNANDPSU_PROG_CHNG_ROW_ADDR_MASK, XNANDPSU_PROG_OFFSET, XNANDPSU_PROG_PG_PROG_MASK, XNandPsu_WriteReg.
s32 XNandPsu_ReadSpareBytes(XNandPsu *InstancePtr, u32 Page, u8 *Buf)
This function reads spare bytes from flash.
InstancePtr is a pointer to the XNandPsu instance. Page is the page address value to read. Buf is the data buffer to fill in. XST_SUCCESS if successful.XST_FAILURE if failed. None
References XNandPsu_Geometry::BytesPerPage, XNandPsu_Geometry::ColAddrCycles, XNandPsu::DmaMode, XNandPsu::Geometry, XNandPsu_Config::IsCacheCoherent, XNandPsu::IsReady, XNandPsu_Geometry::NumTargetPages, ONFI_CMD_RD1, ONFI_CMD_RD2, XNandPsu_Geometry::RowAddrCycles, XNandPsu_Geometry::SpareBytesPerPage, XNANDPSU_INTR_STS_EN_BUFF_RD_RDY_STS_EN_MASK, XNANDPSU_INTR_STS_EN_OFFSET, XNANDPSU_INTR_STS_EN_TRANS_COMP_STS_EN_MASK, XNANDPSU_MDMA, XNandPsu_Prepare_Cmd, XNANDPSU_PROG_OFFSET, XNANDPSU_PROG_RD_MASK, XNandPsu_WriteReg.
s32 XNandPsu_ChangeTimingMode(XNandPsu *InstancePtr, XNandPsu_DataInterface NewIntf, XNandPsu_TimingMode NewMode)
This function changes the data interface and timing mode.
InstancePtr is a pointer to the XNandPsu instance. NewIntf is the new data interface. NewMode is the new timing mode. XST_SUCCESS if successful.XST_FAILURE if failed. None
References XNandPsu_Config::BaseAddress, XNandPsu::Geometry, XNandPsu::IsReady, XNandPsu_Geometry::NumTargets, XNANDPSU_DATA_INTF_DATA_INTF_SHIFT, XNANDPSU_DATA_INTF_OFFSET, XNandPsu_GetFeature, XNANDPSU_NVDDR, XNANDPSU_SDR, XNandPsu_SetFeature, XNandPsu_WriteReg.
Referenced by NandReadWriteExample.
s32 XNandPsu_GetFeature(XNandPsu *InstancePtr, u32 Target, u8 Feature, u8 *Buf)
This function sends ONFI Get Feature command to flash.
InstancePtr is a pointer to the XNandPsu instance. Target is the chip select value. Feature is the feature selector. Buf is the buffer to fill feature value. XST_SUCCESS if successful.XST_FAILURE if failed. None
References XNandPsu::IsReady, ONFI_CMD_GET_FEATURES, ONFI_CMD_INVALID, XNANDPSU_INTR_STS_EN_BUFF_RD_RDY_STS_EN_MASK, XNANDPSU_INTR_STS_EN_OFFSET, XNANDPSU_NVDDR, XNandPsu_Prepare_Cmd, XNANDPSU_PROG_GET_FEATURES_MASK, XNANDPSU_PROG_OFFSET, XNandPsu_WriteReg.
Referenced by XNandPsu_ChangeTimingMode.
s32 XNandPsu_SetFeature(XNandPsu *InstancePtr, u32 Target, u8 Feature, u8 *Buf)
This function sends ONFI Set Feature command to flash.
InstancePtr is a pointer to the XNandPsu instance. Target is the chip select value. Feature is the feature selector. Buf is the feature value to send. XST_SUCCESS if successful.XST_FAILURE if failed. None
References XNandPsu::IsReady, ONFI_CMD_INVALID, ONFI_CMD_SET_FEATURES, XNANDPSU_INTR_STS_EN_BUFF_WR_RDY_STS_EN_MASK, XNANDPSU_INTR_STS_EN_OFFSET, XNANDPSU_NVDDR, XNandPsu_Prepare_Cmd, XNANDPSU_PROG_OFFSET, XNANDPSU_PROG_SET_FEATURES_MASK, XNandPsu_WriteReg.
Referenced by XNandPsu_ChangeTimingMode.
s32 XNandPsu_ScanBbt(XNandPsu *InstancePtr)
This function reads the Bad Block Table(BBT) if present in flash.
If not it scans the flash for detecting factory marked bad blocks and creates a bad block table and write the Bad Block Table(BBT) into the flash. InstancePtr is a pointer to the XNandPsu instance. XST_SUCCESS if successful.XST_FAILURE if fail.
References XNandPsu::Bbt, XNandPsu::BbtDesc, XNandPsu::BbtMirrorDesc, XNandPsu::Geometry, XNandPsu::IsReady, XNandPsu_Geometry::NumBlocks, XNandPsu_Geometry::NumTargets, XNANDPSU_BBT_BLOCK_SHIFT.
Referenced by XNandPsu_CfgInitialize.
s32 XNandPsu_MarkBlockBad(XNandPsu *InstancePtr, u32 Block)
This function marks a block as bad in the RAM based Bad Block Table(BBT).
It also updates the Bad Block Table(BBT) in the flash. InstancePtr is the pointer to the XNandPsu instance. Block is the block number. XST_SUCCESS if successful.XST_FAILURE if fail.
References XNandPsu::Bbt, XNandPsu::Geometry, XNandPsu::IsReady, XNandPsu_Geometry::NumTargetBlocks, XNANDPSU_BBT_BLOCK_SHIFT, XNandPsu_BbtBlockShift, XNANDPSU_BLOCK_BAD, XNANDPSU_BLOCK_TYPE_MASK.
void XNandPsu_EnableDmaMode(XNandPsu *InstancePtr)
This function enables DMA mode of controller operation.
InstancePtr is a pointer to the XNandPsu instance. None None
References XNandPsu::DmaMode, XNandPsu::IsReady, XNANDPSU_MDMA.
Referenced by NandReadWriteExample.
void XNandPsu_DisableDmaMode(XNandPsu *InstancePtr)
This function disables DMA mode of driver/controller operation.
InstancePtr is a pointer to the XNandPsu instance. None None
References XNandPsu::DmaMode, XNandPsu::IsReady, XNANDPSU_PIO.
void XNandPsu_EnableEccMode(XNandPsu *InstancePtr)
This function enables ECC mode of driver/controller operation.
InstancePtr is a pointer to the XNandPsu instance. None None
References XNandPsu::EccMode, XNandPsu::IsReady.
void XNandPsu_DisableEccMode(XNandPsu *InstancePtr)
This function disables ECC mode of driver/controller operation.
InstancePtr is a pointer to the XNandPsu instance. None None
References XNandPsu::EccMode, XNandPsu::IsReady.
void XNandPsu_Prepare_Cmd(XNandPsu *InstancePtr, u8 Cmd1, u8 Cmd2, u8 EccState, u8 DmaMode, u8 AddrCycles)
This function prepares command to be written into command register.
InstancePtr is a pointer to the XNandPsu instance. Cmd1 is the first Onfi Command. Cmd2 is the second Onfi Command. EccState is the flag to set Ecc State. DmaMode is the flag to set DMA mode. AddrCycles is the number of Address Cycles. None None
References XNandPsu::DmaMode, XNandPsu::EccMode, XNANDPSU_CMD_ADDR_CYCLES_SHIFT, XNANDPSU_CMD_CMD2_MASK, XNANDPSU_CMD_CMD2_SHIFT, XNANDPSU_CMD_DMA_EN_SHIFT, XNANDPSU_CMD_ECC_ON_SHIFT, XNANDPSU_CMD_OFFSET, XNANDPSU_MDMA, XNandPsu_WriteReg.
Referenced by XNandPsu_EraseBlock, XNandPsu_GetFeature, XNandPsu_ReadSpareBytes, XNandPsu_SetFeature, XNandPsu_WriteSpareBytes.
XNandPsu_Config * XNandPsu_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XNandPsu_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xnandpsu.h for the definition of XNandPsu_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XNandPsu_Config::Name.
Referenced by NandReadWriteExample.