xnandpsu.c
const XNandPsu_EccMatrix EccMatrix[][]
static s32 XNandPsu_FlashInit(XNandPsu *InstancePtr)
This function initializes the NAND flash and gets the geometry information.
InstancePtr is a pointer to the XNandPsu instance. XST_SUCCESS if successful.XST_FAILURE if failed. None
static s32 XNandPsu_InitGeometry(XNandPsu *InstancePtr, OnfiParamPage *Param)
This function initializes the geometry information from ONFI parameter page.
InstancePtr is a pointer to the XNandPsu instance. Param is pointer to the ONFI parameter page. XST_SUCCESS if successful.XST_FAILURE if failed. None
static void XNandPsu_InitFeatures(XNandPsu *InstancePtr, OnfiParamPage *Param)
This function initializes the feature list from ONFI parameter page.
InstancePtr is a pointer to the XNandPsu instance. Param is pointer to ONFI parameter page buffer. None None
static void XNandPsu_InitDataInterface(XNandPsu *InstancePtr, OnfiParamPage *Param)
This function initializes the Data Interface from ONFI parameter page.
InstancePtr is a pointer to the XNandPsu instance. Param is pointer to ONFI parameter page buffer. None None
static void XNandPsu_InitTimingMode(XNandPsu *InstancePtr, OnfiParamPage *Param)
This function initializes the Timing mode from ONFI parameter page.
InstancePtr is a pointer to the XNandPsu instance. Param is pointer to ONFI parameter page buffer. None None
static s32 XNandPsu_PollRegTimeout(XNandPsu *InstancePtr, u32 RegOffset, u32 Mask, u32 Timeout)
This function polls for a register bit set status till the timeout.
InstancePtr is a pointer to the XNandPsu instance. RegOffset is the offset of register. Mask is the bitmask. Timeout is the timeout value. XST_SUCCESS if successful.XST_FAILURE if failed. None
static void XNandPsu_SetPktSzCnt(XNandPsu *InstancePtr, u32 PktSize, u32 PktCount)
This function sets packet size and packet count values in packet register.
InstancePtr is a pointer to the XNandPsu instance. PktSize is the packet size. PktCount is the packet count. None None
static void XNandPsu_SetPageColAddr(XNandPsu *InstancePtr, u32 Page, u16 Col)
This function sets Page and Column values in the Memory address registers.
InstancePtr is a pointer to the XNandPsu instance. Page is the page value. Col is the column value. None None
static void XNandPsu_SetPageSize(XNandPsu *InstancePtr)
This function sets the size of page in Command Register.
InstancePtr is a pointer to the XNandPsu instance. None None
static void XNandPsu_SelectChip(XNandPsu *InstancePtr, u32 Target)
This function sets the chip select value in memory address2 register.
InstancePtr is a pointer to the XNandPsu instance. Target is the chip select value. None None
static s32 XNandPsu_OnfiReset(XNandPsu *InstancePtr, u32 Target)
This function sends ONFI Reset command to the flash.
InstancePtr is a pointer to the XNandPsu instance. Target is the chip select value. XST_SUCCESS if successful.XST_FAILURE if failed. None
static s32 XNandPsu_OnfiReadStatus(XNandPsu *InstancePtr, u32 Target, u16 *OnfiStatus)
This function sends ONFI Read Status command to the flash.
InstancePtr is a pointer to the XNandPsu instance. Target is the chip select value. OnfiStatus is the ONFI status value to return. XST_SUCCESS if successful.XST_FAILURE if failed. None
static s32 XNandPsu_OnfiReadId(XNandPsu *InstancePtr, u32 Target, u8 IdAddr, u32 IdLen, u8 *Buf)
This function sends ONFI Read ID command to the flash.
InstancePtr is a pointer to the XNandPsu instance. Target is the chip select value. Buf is the ONFI ID value to return. XST_SUCCESS if successful.XST_FAILURE if failed. None
static s32 XNandPsu_OnfiReadParamPage(XNandPsu *InstancePtr, u32 Target, u8 *Buf)
This function sends the ONFI Read Parameter Page command to flash.
InstancePtr is a pointer to the XNandPsu instance. Target is the chip select value. PrmIndex is the index of parameter page. Buf is the parameter page information to return. XST_SUCCESS if successful.XST_FAILURE if failed. None
static s32 XNandPsu_ProgramPage(XNandPsu *InstancePtr, u32 Target, u32 Page, u32 Col, u8 *Buf)
This function sends ONFI Program Page command to flash.
InstancePtr is a pointer to the XNandPsu instance. Target is the chip select value. Page is the page address value to program. Col is the column address value to program. Buf is the data buffer to program. XST_SUCCESS if successful.XST_FAILURE if failed. None
static s32 XNandPsu_ReadPage(XNandPsu *InstancePtr, u32 Target, u32 Page, u32 Col, u8 *Buf)
This function sends ONFI Read Page command to flash.
InstancePtr is a pointer to the XNandPsu instance. Target is the chip select value. Page is the page address value to read. Col is the column address value to read. Buf is the data buffer to fill in. XST_SUCCESS if successful.XST_FAILURE if failed. None
static s32 XNandPsu_CheckOnDie(XNandPsu *InstancePtr)
This function checks if the flash supports on-die ECC.
InstancePtr is a pointer to the XNandPsu instance. Param is pointer to ONFI parameter page. None None
static void XNandPsu_SetEccAddrSize(XNandPsu *InstancePtr)
This function setup the Ecc Register.
InstancePtr is a pointer to the XNandPsu instance. None None
static s32 XNandPsu_ChangeReadColumn(XNandPsu *InstancePtr, u32 Target, u32 Col, u32 PktSize, u32 PktCount, u8 *Buf)
This function issues change read column and reads the data into buffer specified by user.
InstancePtr is a pointer to the XNandPsu instance. Target is the chip select value. Col is the coulmn address. PktSize is the number of bytes to read. PktCount is the number of transactions to read. Buf is the data buffer to fill in. XST_SUCCESS if successful.XST_FAILURE if failed. None
static s32 XNandPsu_ChangeWriteColumn(XNandPsu *InstancePtr, u32 Target, u32 Col, u32 PktSize, u32 PktCount, u8 *Buf)
This function issues change read column and reads the data into buffer specified by user.
InstancePtr is a pointer to the XNandPsu instance. Target is the chip select value. Col is the coulmn address. PktSize is the number of bytes to read. PktCount is the number of transactions to read. Buf is the data buffer to fill in. XST_SUCCESS if successful.XST_FAILURE if failed. None
static s32 XNandPsu_InitExtEcc(XNandPsu *InstancePtr, OnfiExtPrmPage *ExtPrm)
This function initializes extended parameter page ECC information.
InstancePtr is a pointer to the XNandPsu instance. ExtPrm is the Extended parameter page buffer. XST_SUCCESS if successful.XST_FAILURE if failed. None
static s32 XNandPsu_Data_ReadWrite(XNandPsu *InstancePtr, u8 *Buf, u32 PktCount, u32 PktSize, u32 Operation, u8 DmaMode)
This function Read/Writes data from the nand controller.
InstancePtr is a pointer to the XNandPsu instance. Buf is the data buffer. PktCount is the number packet chunks. PktSize is the size of the packet. Operation is 1 for write and 0 for read. DmaMode is 1 for Dma and 0 for PIO. XST_SUCCESS if successful.XST_FAILURE if failed. None
static s32 XNandPsu_WaitFor_Transfer_Complete(XNandPsu *InstancePtr)
This function waits for the transfer complete event.
InstancePtr is a pointer to the XNandPsu instance. XST_SUCCESS if successful.XST_FAILURE if failed. Expects that transfer complete event was set before calling this function.
static s32 XNandPsu_Device_Ready(XNandPsu *InstancePtr, u32 Target)
This function waits for the device ready stataus.
InstancePtr is a pointer to the XNandPsu instance. Target is the chipselect value. XST_SUCCESS if successful.XST_FAILURE if failed. None
static void XNandPsu_Fifo_Read(XNandPsu *InstancePtr, u8 *Buf, u32 Size)
This function reads data from the fifo.
InstancePtr is a pointer to the XNandPsu instance. Buf is the buffer pointer. Size of the Buffer. None None
static void XNandPsu_Fifo_Write(XNandPsu *InstancePtr, u8 *Buffer, u32 Size)
This function writes data to the fifo.
InstancePtr is a pointer to the XNandPsu instance. Buf is the buffer pointer. Size of the Buffer. None None
static void XNandPsu_Update_DmaAddr(XNandPsu *InstancePtr, u8 *Buf)
This function configures the given dma address to the controller.
InstancePtr is a pointer to the XNandPsu instance. Buf is the buffer pointer. None None
s32 XNandPsu_CfgInitialize(XNandPsu *InstancePtr, XNandPsu_Config *ConfigPtr, u32 EffectiveAddr)
This function initializes a specific XNandPsu instance.
This function must be called prior to using the NAND flash device to read or write any data. InstancePtr is a pointer to the XNandPsu instance. ConfigPtr points to XNandPsu device configuration structure. EffectiveAddr is the base address of NAND flash controller. XST_SUCCESS if successful.XST_FAILURE if fail. The user needs to first call the XNandPsu_LookupConfig() API which returns the Configuration structure pointer which is passed as a parameter to the XNandPsu_CfgInitialize() API.
References XNandPsu_Config::BaseAddress, XNandPsu::DmaMode, XNandPsu::Ecc_Stat_PerPage_flips, XNandPsu::Ecc_Stats_total_flips, XNandPsu::EccMode, XNandPsu::Features, XNandPsu_Config::IsCacheCoherent, XNandPsu::IsReady, XNandPsu::Mode, XNandPsu_InitBbtDesc, XNANDPSU_MDMA, XNANDPSU_POLLING, XNandPsu_ScanBbt.
Referenced by NandReadWriteExample.
void XNandPsu_EnableDmaMode(XNandPsu *InstancePtr)
This function enables DMA mode of controller operation.
InstancePtr is a pointer to the XNandPsu instance. None None
References XNandPsu::DmaMode, XNandPsu::IsReady, XNANDPSU_MDMA.
Referenced by NandReadWriteExample.
void XNandPsu_DisableDmaMode(XNandPsu *InstancePtr)
This function disables DMA mode of driver/controller operation.
InstancePtr is a pointer to the XNandPsu instance. None None
References XNandPsu::DmaMode, XNandPsu::IsReady, XNANDPSU_PIO.
void XNandPsu_EnableEccMode(XNandPsu *InstancePtr)
This function enables ECC mode of driver/controller operation.
InstancePtr is a pointer to the XNandPsu instance. None None
References XNandPsu::EccMode, XNandPsu::IsReady.
void XNandPsu_DisableEccMode(XNandPsu *InstancePtr)
This function disables ECC mode of driver/controller operation.
InstancePtr is a pointer to the XNandPsu instance. None None
References XNandPsu::EccMode, XNandPsu::IsReady.
static void XNandPsu_SetEccSpareCmd(XNandPsu *InstancePtr, u16 SpareCmd, u8 AddrCycles)
This function setup the Ecc Spare Command Register.
InstancePtr is a pointer to the XNandPsu instance. None None
static s32 XNandPsu_CalculateLength(XNandPsu *InstancePtr, u64 Offset, u64 Length)
This function returns the length including bad blocks from a given offset and length.
InstancePtr is the pointer to the XNandPsu instance. Offset is the flash data address to read from. Length is number of bytes to read. Return actual length including bad blocks. None.
s32 XNandPsu_Write(XNandPsu *InstancePtr, u64 Offset, u64 Length, u8 *SrcBuf)
This function writes to the flash.
InstancePtr is a pointer to the XNandPsu instance. Offset is the starting offset of flash to write. Length is the number of bytes to write. SrcBuf is the source data buffer to write. XST_SUCCESS if successful.XST_FAILURE if failed. None
References XNandPsu_Geometry::BlockSize, XNandPsu_Geometry::BytesPerPage, XNandPsu_Geometry::DeviceSize, XNandPsu::Geometry, XNandPsu::IsReady, XNandPsu_Geometry::NumTargetPages, XNandPsu_Geometry::TargetSize, XNandPsu_IsBlockBad.
Referenced by NandReadWriteExample.
s32 XNandPsu_Read(XNandPsu *InstancePtr, u64 Offset, u64 Length, u8 *DestBuf)
This function reads from the flash.
InstancePtr is a pointer to the XNandPsu instance. Offset is the starting offset of flash to read. Length is the number of bytes to read. DestBuf is the destination data buffer to fill in. XST_SUCCESS if successful.XST_FAILURE if failed. None
References XNandPsu_Geometry::BlockSize, XNandPsu_Geometry::BytesPerPage, XNandPsu_Geometry::DeviceSize, XNandPsu::Geometry, XNandPsu_Config::IsCacheCoherent, XNandPsu::IsReady, XNandPsu_Geometry::NumTargetPages, XNandPsu_Geometry::TargetSize, XNandPsu_IsBlockBad.
Referenced by NandReadWriteExample.
s32 XNandPsu_Erase(XNandPsu *InstancePtr, u64 Offset, u64 Length)
This function erases the flash.
InstancePtr is a pointer to the XNandPsu instance. Offset is the starting offset of flash to erase. Length is the number of bytes to erase. XST_SUCCESS if successful.XST_FAILURE if failed. The Offset and Length should be aligned to block size boundary to get better results.
References XNandPsu_Geometry::BlockSize, XNandPsu_Geometry::DeviceSize, XNandPsu::Geometry, XNandPsu::IsReady, XNandPsu_Geometry::NumTargetBlocks, XNandPsu_EraseBlock, XNandPsu_IsBlockBad.
Referenced by NandReadWriteExample.
s32 XNandPsu_WriteSpareBytes(XNandPsu *InstancePtr, u32 Page, u8 *Buf)
This function sends ONFI Program Page command to flash.
InstancePtr is a pointer to the XNandPsu instance. Page is the page address value to program. Buf is the data buffer to program. XST_SUCCESS if successful.XST_FAILURE if failed. None
References XNandPsu_Geometry::BytesPerPage, XNandPsu_Geometry::ColAddrCycles, XNandPsu::DmaMode, XNandPsu::EccCfg, XNandPsu::EccMode, XNandPsu::Geometry, XNandPsu_Config::IsCacheCoherent, XNandPsu::IsReady, XNandPsu_Geometry::NumTargetPages, ONFI_CMD_PG_PROG1, ONFI_CMD_PG_PROG2, XNandPsu_Geometry::RowAddrCycles, XNandPsu_Geometry::SpareBytesPerPage, XNANDPSU_INTR_STS_EN_BUFF_WR_RDY_STS_EN_MASK, XNANDPSU_INTR_STS_EN_OFFSET, XNANDPSU_INTR_STS_EN_TRANS_COMP_STS_EN_MASK, XNANDPSU_MDMA, XNandPsu_Prepare_Cmd, XNANDPSU_PROG_CHNG_ROW_ADDR_MASK, XNANDPSU_PROG_OFFSET, XNANDPSU_PROG_PG_PROG_MASK, XNandPsu_WriteReg.
s32 XNandPsu_ReadSpareBytes(XNandPsu *InstancePtr, u32 Page, u8 *Buf)
This function reads spare bytes from flash.
InstancePtr is a pointer to the XNandPsu instance. Page is the page address value to read. Buf is the data buffer to fill in. XST_SUCCESS if successful.XST_FAILURE if failed. None
References XNandPsu_Geometry::BytesPerPage, XNandPsu_Geometry::ColAddrCycles, XNandPsu::DmaMode, XNandPsu::Geometry, XNandPsu_Config::IsCacheCoherent, XNandPsu::IsReady, XNandPsu_Geometry::NumTargetPages, ONFI_CMD_RD1, ONFI_CMD_RD2, XNandPsu_Geometry::RowAddrCycles, XNandPsu_Geometry::SpareBytesPerPage, XNANDPSU_INTR_STS_EN_BUFF_RD_RDY_STS_EN_MASK, XNANDPSU_INTR_STS_EN_OFFSET, XNANDPSU_INTR_STS_EN_TRANS_COMP_STS_EN_MASK, XNANDPSU_MDMA, XNandPsu_Prepare_Cmd, XNANDPSU_PROG_OFFSET, XNANDPSU_PROG_RD_MASK, XNandPsu_WriteReg.
s32 XNandPsu_EraseBlock(XNandPsu *InstancePtr, u32 Target, u32 Block)
This function sends ONFI block erase command to the flash.
InstancePtr is a pointer to the XNandPsu instance. Target is the chip select value. Block is the block to erase. XST_SUCCESS if successful.XST_FAILURE if failed. None
References XNandPsu::Geometry, XNandPsu::IsReady, ONFI_CMD_BLK_ERASE1, ONFI_CMD_BLK_ERASE2, XNandPsu_Geometry::PagesPerBlock, XNandPsu_Geometry::RowAddrCycles, XNANDPSU_INTR_STS_EN_OFFSET, XNANDPSU_INTR_STS_EN_TRANS_COMP_STS_EN_MASK, XNandPsu_Prepare_Cmd, XNANDPSU_PROG_BLK_ERASE_MASK, XNANDPSU_PROG_OFFSET, XNandPsu_WriteReg.
Referenced by XNandPsu_Erase.
s32 XNandPsu_GetFeature(XNandPsu *InstancePtr, u32 Target, u8 Feature, u8 *Buf)
This function sends ONFI Get Feature command to flash.
InstancePtr is a pointer to the XNandPsu instance. Target is the chip select value. Feature is the feature selector. Buf is the buffer to fill feature value. XST_SUCCESS if successful.XST_FAILURE if failed. None
References XNandPsu::IsReady, ONFI_CMD_GET_FEATURES, ONFI_CMD_INVALID, XNANDPSU_INTR_STS_EN_BUFF_RD_RDY_STS_EN_MASK, XNANDPSU_INTR_STS_EN_OFFSET, XNANDPSU_NVDDR, XNandPsu_Prepare_Cmd, XNANDPSU_PROG_GET_FEATURES_MASK, XNANDPSU_PROG_OFFSET, XNandPsu_WriteReg.
Referenced by XNandPsu_ChangeTimingMode.
s32 XNandPsu_SetFeature(XNandPsu *InstancePtr, u32 Target, u8 Feature, u8 *Buf)
This function sends ONFI Set Feature command to flash.
InstancePtr is a pointer to the XNandPsu instance. Target is the chip select value. Feature is the feature selector. Buf is the feature value to send. XST_SUCCESS if successful.XST_FAILURE if failed. None
References XNandPsu::IsReady, ONFI_CMD_INVALID, ONFI_CMD_SET_FEATURES, XNANDPSU_INTR_STS_EN_BUFF_WR_RDY_STS_EN_MASK, XNANDPSU_INTR_STS_EN_OFFSET, XNANDPSU_NVDDR, XNandPsu_Prepare_Cmd, XNANDPSU_PROG_OFFSET, XNANDPSU_PROG_SET_FEATURES_MASK, XNandPsu_WriteReg.
Referenced by XNandPsu_ChangeTimingMode.
static void XNandPsu_ChangeClockFreq(XNandPsu *InstancePtr, u32 ClockFreq)
This function changes clock frequency of flash controller.
InstancePtr is a pointer to the XNandPsu instance. ClockFreq is the clock frequency to change. None None
s32 XNandPsu_ChangeTimingMode(XNandPsu *InstancePtr, XNandPsu_DataInterface NewIntf, XNandPsu_TimingMode NewMode)
This function changes the data interface and timing mode.
InstancePtr is a pointer to the XNandPsu instance. NewIntf is the new data interface. NewMode is the new timing mode. XST_SUCCESS if successful.XST_FAILURE if failed. None
References XNandPsu_Config::BaseAddress, XNandPsu::Geometry, XNandPsu::IsReady, XNandPsu_Geometry::NumTargets, XNANDPSU_DATA_INTF_DATA_INTF_SHIFT, XNANDPSU_DATA_INTF_OFFSET, XNandPsu_GetFeature, XNANDPSU_NVDDR, XNANDPSU_SDR, XNandPsu_SetFeature, XNandPsu_WriteReg.
Referenced by NandReadWriteExample.
void XNandPsu_Prepare_Cmd(XNandPsu *InstancePtr, u8 Cmd1, u8 Cmd2, u8 EccState, u8 DmaMode, u8 AddrCycles)
This function prepares command to be written into command register.
InstancePtr is a pointer to the XNandPsu instance. Cmd1 is the first Onfi Command. Cmd2 is the second Onfi Command. EccState is the flag to set Ecc State. DmaMode is the flag to set DMA mode. AddrCycles is the number of Address Cycles. None None
References XNandPsu::DmaMode, XNandPsu::EccMode, XNANDPSU_CMD_ADDR_CYCLES_SHIFT, XNANDPSU_CMD_CMD2_MASK, XNANDPSU_CMD_CMD2_SHIFT, XNANDPSU_CMD_DMA_EN_SHIFT, XNANDPSU_CMD_ECC_ON_SHIFT, XNANDPSU_CMD_OFFSET, XNANDPSU_MDMA, XNandPsu_WriteReg.
Referenced by XNandPsu_EraseBlock, XNandPsu_GetFeature, XNandPsu_ReadSpareBytes, XNandPsu_SetFeature, XNandPsu_WriteSpareBytes.