/**
 * (c) 2013 Xilinx Inc.
 * XREGDB v0.91
 * XREGCHDR v0.15
 *
 * Generated on: 2018-12-08
 *
 * @file: lpd_iou_slcr.h
 *
 *
 * This file contains confidential and proprietary information
 * of Xilinx, Inc. and is protected under U.S. and
 * international copyright and other intellectual property
 * laws.
 *
 * DISCLAIMER
 * This disclaimer is not a license and does not grant any
 * rights to the materials distributed herewith. Except as
 * otherwise provided in a valid license issued to you by
 * Xilinx, and to the maximum extent permitted by applicable
 * law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
 * WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
 * AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
 * BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
 * INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
 * (2) Xilinx shall not be liable (whether in contract or tort,
 * including negligence, or under any other theory of
 * liability) for any loss or damage of any kind or nature
 * related to, arising under or in connection with these
 * materials, including for any direct, or any indirect,
 * special, incidental, or consequential loss or damage
 * (including loss of data, profits, goodwill, or any type of
 * loss or damage suffered as a result of any action brought
 * by a third party) even if such damage or loss was
 * reasonably foreseeable or Xilinx had been advised of the
 * possibility of the same.
 *
 * CRITICAL APPLICATIONS
 * Xilinx products are not designed or intended to be fail-
 * safe, or for use in any application requiring fail-safe
 * performance, such as life-support or safety devices or
 * systems, Class III medical devices, nuclear facilities,
 * applications related to the deployment of airbags, or any
 * other applications that could lead to death, personal
 * injury, or severe property or environmental damage
 * (individually and collectively, "Critical
 * Applications"). Customer assumes the sole risk and
 * liability of any use of Xilinx products in Critical
 * Applications, subject only to applicable laws and
 * regulations governing limitations on product liability.
 *
 * THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
 * PART OF THIS FILE AT ALL TIMES.
 *
 * Naming Convention: <MODULE>_<REGISTER>[_<FIELD>[_<DESC>]]
 *     <MODULE>       Module name (e.g. can or usb)
 *     <REGISTER>     Register within the current module
 *     [_<FIELD>]     Bit field within a register
 *     [_<DESC>]      Type of bit field define:
 *         SHIFT:     Least significant bit for the field
 *         WIDTH:     Size of field in bites
 *         MASK:      A masking over a range of bits or a bit to
 *                    be used for setting or clearing
 *
 */

#ifndef _LPD_IOU_SLCR_H_
#define _LPD_IOU_SLCR_H_

#ifdef __cplusplus
extern "C" {
#endif

/**
 * LPD_IOU_SLCR Base Address
 */
#define LPD_IOU_SLCR_BASEADDR      0XFF080000

/**
 * Register: LPD_IOU_SLCR_MIO_PIN_0
 */
#define LPD_IOU_SLCR_MIO_PIN_0    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000000 )

#define LPD_IOU_SLCR_MIO_PIN_0_L3_SEL_SHIFT   7
#define LPD_IOU_SLCR_MIO_PIN_0_L3_SEL_WIDTH   3
#define LPD_IOU_SLCR_MIO_PIN_0_L3_SEL_MASK    0X00000380

#define LPD_IOU_SLCR_MIO_PIN_0_L2_SEL_SHIFT   5
#define LPD_IOU_SLCR_MIO_PIN_0_L2_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_0_L2_SEL_MASK    0X00000060

#define LPD_IOU_SLCR_MIO_PIN_0_L1_SEL_SHIFT   3
#define LPD_IOU_SLCR_MIO_PIN_0_L1_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_0_L1_SEL_MASK    0X00000018

#define LPD_IOU_SLCR_MIO_PIN_0_L0_SEL_SHIFT   1
#define LPD_IOU_SLCR_MIO_PIN_0_L0_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_0_L0_SEL_MASK    0X00000006

/**
 * Register: LPD_IOU_SLCR_MIO_PIN_1
 */
#define LPD_IOU_SLCR_MIO_PIN_1    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000004 )

#define LPD_IOU_SLCR_MIO_PIN_1_L3_SEL_SHIFT   7
#define LPD_IOU_SLCR_MIO_PIN_1_L3_SEL_WIDTH   3
#define LPD_IOU_SLCR_MIO_PIN_1_L3_SEL_MASK    0X00000380

#define LPD_IOU_SLCR_MIO_PIN_1_L2_SEL_SHIFT   5
#define LPD_IOU_SLCR_MIO_PIN_1_L2_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_1_L2_SEL_MASK    0X00000060

#define LPD_IOU_SLCR_MIO_PIN_1_L1_SEL_SHIFT   3
#define LPD_IOU_SLCR_MIO_PIN_1_L1_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_1_L1_SEL_MASK    0X00000018

#define LPD_IOU_SLCR_MIO_PIN_1_L0_SEL_SHIFT   1
#define LPD_IOU_SLCR_MIO_PIN_1_L0_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_1_L0_SEL_MASK    0X00000006

/**
 * Register: LPD_IOU_SLCR_MIO_PIN_2
 */
#define LPD_IOU_SLCR_MIO_PIN_2    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000008 )

#define LPD_IOU_SLCR_MIO_PIN_2_L3_SEL_SHIFT   7
#define LPD_IOU_SLCR_MIO_PIN_2_L3_SEL_WIDTH   3
#define LPD_IOU_SLCR_MIO_PIN_2_L3_SEL_MASK    0X00000380

#define LPD_IOU_SLCR_MIO_PIN_2_L2_SEL_SHIFT   5
#define LPD_IOU_SLCR_MIO_PIN_2_L2_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_2_L2_SEL_MASK    0X00000060

#define LPD_IOU_SLCR_MIO_PIN_2_L1_SEL_SHIFT   3
#define LPD_IOU_SLCR_MIO_PIN_2_L1_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_2_L1_SEL_MASK    0X00000018

#define LPD_IOU_SLCR_MIO_PIN_2_L0_SEL_SHIFT   1
#define LPD_IOU_SLCR_MIO_PIN_2_L0_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_2_L0_SEL_MASK    0X00000006

/**
 * Register: LPD_IOU_SLCR_MIO_PIN_3
 */
#define LPD_IOU_SLCR_MIO_PIN_3    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X0000000C )

#define LPD_IOU_SLCR_MIO_PIN_3_L3_SEL_SHIFT   7
#define LPD_IOU_SLCR_MIO_PIN_3_L3_SEL_WIDTH   3
#define LPD_IOU_SLCR_MIO_PIN_3_L3_SEL_MASK    0X00000380

#define LPD_IOU_SLCR_MIO_PIN_3_L2_SEL_SHIFT   5
#define LPD_IOU_SLCR_MIO_PIN_3_L2_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_3_L2_SEL_MASK    0X00000060

#define LPD_IOU_SLCR_MIO_PIN_3_L1_SEL_SHIFT   3
#define LPD_IOU_SLCR_MIO_PIN_3_L1_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_3_L1_SEL_MASK    0X00000018

#define LPD_IOU_SLCR_MIO_PIN_3_L0_SEL_SHIFT   1
#define LPD_IOU_SLCR_MIO_PIN_3_L0_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_3_L0_SEL_MASK    0X00000006

/**
 * Register: LPD_IOU_SLCR_MIO_PIN_4
 */
#define LPD_IOU_SLCR_MIO_PIN_4    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000010 )

#define LPD_IOU_SLCR_MIO_PIN_4_L3_SEL_SHIFT   7
#define LPD_IOU_SLCR_MIO_PIN_4_L3_SEL_WIDTH   3
#define LPD_IOU_SLCR_MIO_PIN_4_L3_SEL_MASK    0X00000380

#define LPD_IOU_SLCR_MIO_PIN_4_L2_SEL_SHIFT   5
#define LPD_IOU_SLCR_MIO_PIN_4_L2_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_4_L2_SEL_MASK    0X00000060

#define LPD_IOU_SLCR_MIO_PIN_4_L1_SEL_SHIFT   3
#define LPD_IOU_SLCR_MIO_PIN_4_L1_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_4_L1_SEL_MASK    0X00000018

#define LPD_IOU_SLCR_MIO_PIN_4_L0_SEL_SHIFT   1
#define LPD_IOU_SLCR_MIO_PIN_4_L0_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_4_L0_SEL_MASK    0X00000006

/**
 * Register: LPD_IOU_SLCR_MIO_PIN_5
 */
#define LPD_IOU_SLCR_MIO_PIN_5    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000014 )

#define LPD_IOU_SLCR_MIO_PIN_5_L3_SEL_SHIFT   7
#define LPD_IOU_SLCR_MIO_PIN_5_L3_SEL_WIDTH   3
#define LPD_IOU_SLCR_MIO_PIN_5_L3_SEL_MASK    0X00000380

#define LPD_IOU_SLCR_MIO_PIN_5_L2_SEL_SHIFT   5
#define LPD_IOU_SLCR_MIO_PIN_5_L2_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_5_L2_SEL_MASK    0X00000060

#define LPD_IOU_SLCR_MIO_PIN_5_L1_SEL_SHIFT   3
#define LPD_IOU_SLCR_MIO_PIN_5_L1_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_5_L1_SEL_MASK    0X00000018

#define LPD_IOU_SLCR_MIO_PIN_5_L0_SEL_SHIFT   1
#define LPD_IOU_SLCR_MIO_PIN_5_L0_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_5_L0_SEL_MASK    0X00000006

/**
 * Register: LPD_IOU_SLCR_MIO_PIN_6
 */
#define LPD_IOU_SLCR_MIO_PIN_6    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000018 )

#define LPD_IOU_SLCR_MIO_PIN_6_L3_SEL_SHIFT   7
#define LPD_IOU_SLCR_MIO_PIN_6_L3_SEL_WIDTH   3
#define LPD_IOU_SLCR_MIO_PIN_6_L3_SEL_MASK    0X00000380

#define LPD_IOU_SLCR_MIO_PIN_6_L2_SEL_SHIFT   5
#define LPD_IOU_SLCR_MIO_PIN_6_L2_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_6_L2_SEL_MASK    0X00000060

#define LPD_IOU_SLCR_MIO_PIN_6_L1_SEL_SHIFT   3
#define LPD_IOU_SLCR_MIO_PIN_6_L1_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_6_L1_SEL_MASK    0X00000018

#define LPD_IOU_SLCR_MIO_PIN_6_L0_SEL_SHIFT   1
#define LPD_IOU_SLCR_MIO_PIN_6_L0_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_6_L0_SEL_MASK    0X00000006

/**
 * Register: LPD_IOU_SLCR_MIO_PIN_7
 */
#define LPD_IOU_SLCR_MIO_PIN_7    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X0000001C )

#define LPD_IOU_SLCR_MIO_PIN_7_L3_SEL_SHIFT   7
#define LPD_IOU_SLCR_MIO_PIN_7_L3_SEL_WIDTH   3
#define LPD_IOU_SLCR_MIO_PIN_7_L3_SEL_MASK    0X00000380

#define LPD_IOU_SLCR_MIO_PIN_7_L2_SEL_SHIFT   5
#define LPD_IOU_SLCR_MIO_PIN_7_L2_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_7_L2_SEL_MASK    0X00000060

#define LPD_IOU_SLCR_MIO_PIN_7_L1_SEL_SHIFT   3
#define LPD_IOU_SLCR_MIO_PIN_7_L1_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_7_L1_SEL_MASK    0X00000018

#define LPD_IOU_SLCR_MIO_PIN_7_L0_SEL_SHIFT   1
#define LPD_IOU_SLCR_MIO_PIN_7_L0_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_7_L0_SEL_MASK    0X00000006

/**
 * Register: LPD_IOU_SLCR_MIO_PIN_8
 */
#define LPD_IOU_SLCR_MIO_PIN_8    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000020 )

#define LPD_IOU_SLCR_MIO_PIN_8_L3_SEL_SHIFT   7
#define LPD_IOU_SLCR_MIO_PIN_8_L3_SEL_WIDTH   3
#define LPD_IOU_SLCR_MIO_PIN_8_L3_SEL_MASK    0X00000380

#define LPD_IOU_SLCR_MIO_PIN_8_L2_SEL_SHIFT   5
#define LPD_IOU_SLCR_MIO_PIN_8_L2_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_8_L2_SEL_MASK    0X00000060

#define LPD_IOU_SLCR_MIO_PIN_8_L1_SEL_SHIFT   3
#define LPD_IOU_SLCR_MIO_PIN_8_L1_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_8_L1_SEL_MASK    0X00000018

#define LPD_IOU_SLCR_MIO_PIN_8_L0_SEL_SHIFT   1
#define LPD_IOU_SLCR_MIO_PIN_8_L0_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_8_L0_SEL_MASK    0X00000006

/**
 * Register: LPD_IOU_SLCR_MIO_PIN_9
 */
#define LPD_IOU_SLCR_MIO_PIN_9    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000024 )

#define LPD_IOU_SLCR_MIO_PIN_9_L3_SEL_SHIFT   7
#define LPD_IOU_SLCR_MIO_PIN_9_L3_SEL_WIDTH   3
#define LPD_IOU_SLCR_MIO_PIN_9_L3_SEL_MASK    0X00000380

#define LPD_IOU_SLCR_MIO_PIN_9_L2_SEL_SHIFT   5
#define LPD_IOU_SLCR_MIO_PIN_9_L2_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_9_L2_SEL_MASK    0X00000060

#define LPD_IOU_SLCR_MIO_PIN_9_L1_SEL_SHIFT   3
#define LPD_IOU_SLCR_MIO_PIN_9_L1_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_9_L1_SEL_MASK    0X00000018

#define LPD_IOU_SLCR_MIO_PIN_9_L0_SEL_SHIFT   1
#define LPD_IOU_SLCR_MIO_PIN_9_L0_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_9_L0_SEL_MASK    0X00000006

/**
 * Register: LPD_IOU_SLCR_MIO_PIN_10
 */
#define LPD_IOU_SLCR_MIO_PIN_10    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000028 )

#define LPD_IOU_SLCR_MIO_PIN_10_L3_SEL_SHIFT   7
#define LPD_IOU_SLCR_MIO_PIN_10_L3_SEL_WIDTH   3
#define LPD_IOU_SLCR_MIO_PIN_10_L3_SEL_MASK    0X00000380

#define LPD_IOU_SLCR_MIO_PIN_10_L2_SEL_SHIFT   5
#define LPD_IOU_SLCR_MIO_PIN_10_L2_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_10_L2_SEL_MASK    0X00000060

#define LPD_IOU_SLCR_MIO_PIN_10_L1_SEL_SHIFT   3
#define LPD_IOU_SLCR_MIO_PIN_10_L1_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_10_L1_SEL_MASK    0X00000018

#define LPD_IOU_SLCR_MIO_PIN_10_L0_SEL_SHIFT   1
#define LPD_IOU_SLCR_MIO_PIN_10_L0_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_10_L0_SEL_MASK    0X00000006

/**
 * Register: LPD_IOU_SLCR_MIO_PIN_11
 */
#define LPD_IOU_SLCR_MIO_PIN_11    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X0000002C )

#define LPD_IOU_SLCR_MIO_PIN_11_L3_SEL_SHIFT   7
#define LPD_IOU_SLCR_MIO_PIN_11_L3_SEL_WIDTH   3
#define LPD_IOU_SLCR_MIO_PIN_11_L3_SEL_MASK    0X00000380

#define LPD_IOU_SLCR_MIO_PIN_11_L2_SEL_SHIFT   5
#define LPD_IOU_SLCR_MIO_PIN_11_L2_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_11_L2_SEL_MASK    0X00000060

#define LPD_IOU_SLCR_MIO_PIN_11_L1_SEL_SHIFT   3
#define LPD_IOU_SLCR_MIO_PIN_11_L1_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_11_L1_SEL_MASK    0X00000018

#define LPD_IOU_SLCR_MIO_PIN_11_L0_SEL_SHIFT   1
#define LPD_IOU_SLCR_MIO_PIN_11_L0_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_11_L0_SEL_MASK    0X00000006

/**
 * Register: LPD_IOU_SLCR_MIO_PIN_12
 */
#define LPD_IOU_SLCR_MIO_PIN_12    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000030 )

#define LPD_IOU_SLCR_MIO_PIN_12_L3_SEL_SHIFT   7
#define LPD_IOU_SLCR_MIO_PIN_12_L3_SEL_WIDTH   3
#define LPD_IOU_SLCR_MIO_PIN_12_L3_SEL_MASK    0X00000380

#define LPD_IOU_SLCR_MIO_PIN_12_L2_SEL_SHIFT   5
#define LPD_IOU_SLCR_MIO_PIN_12_L2_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_12_L2_SEL_MASK    0X00000060

#define LPD_IOU_SLCR_MIO_PIN_12_L1_SEL_SHIFT   3
#define LPD_IOU_SLCR_MIO_PIN_12_L1_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_12_L1_SEL_MASK    0X00000018

#define LPD_IOU_SLCR_MIO_PIN_12_L0_SEL_SHIFT   1
#define LPD_IOU_SLCR_MIO_PIN_12_L0_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_12_L0_SEL_MASK    0X00000006

/**
 * Register: LPD_IOU_SLCR_MIO_PIN_13
 */
#define LPD_IOU_SLCR_MIO_PIN_13    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000034 )

#define LPD_IOU_SLCR_MIO_PIN_13_L3_SEL_SHIFT   7
#define LPD_IOU_SLCR_MIO_PIN_13_L3_SEL_WIDTH   3
#define LPD_IOU_SLCR_MIO_PIN_13_L3_SEL_MASK    0X00000380

#define LPD_IOU_SLCR_MIO_PIN_13_L2_SEL_SHIFT   5
#define LPD_IOU_SLCR_MIO_PIN_13_L2_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_13_L2_SEL_MASK    0X00000060

#define LPD_IOU_SLCR_MIO_PIN_13_L1_SEL_SHIFT   3
#define LPD_IOU_SLCR_MIO_PIN_13_L1_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_13_L1_SEL_MASK    0X00000018

#define LPD_IOU_SLCR_MIO_PIN_13_L0_SEL_SHIFT   1
#define LPD_IOU_SLCR_MIO_PIN_13_L0_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_13_L0_SEL_MASK    0X00000006

/**
 * Register: LPD_IOU_SLCR_MIO_PIN_14
 */
#define LPD_IOU_SLCR_MIO_PIN_14    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000038 )

#define LPD_IOU_SLCR_MIO_PIN_14_L3_SEL_SHIFT   7
#define LPD_IOU_SLCR_MIO_PIN_14_L3_SEL_WIDTH   3
#define LPD_IOU_SLCR_MIO_PIN_14_L3_SEL_MASK    0X00000380

#define LPD_IOU_SLCR_MIO_PIN_14_L2_SEL_SHIFT   5
#define LPD_IOU_SLCR_MIO_PIN_14_L2_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_14_L2_SEL_MASK    0X00000060

#define LPD_IOU_SLCR_MIO_PIN_14_L1_SEL_SHIFT   3
#define LPD_IOU_SLCR_MIO_PIN_14_L1_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_14_L1_SEL_MASK    0X00000018

#define LPD_IOU_SLCR_MIO_PIN_14_L0_SEL_SHIFT   1
#define LPD_IOU_SLCR_MIO_PIN_14_L0_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_14_L0_SEL_MASK    0X00000006

/**
 * Register: LPD_IOU_SLCR_MIO_PIN_15
 */
#define LPD_IOU_SLCR_MIO_PIN_15    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X0000003C )

#define LPD_IOU_SLCR_MIO_PIN_15_L3_SEL_SHIFT   7
#define LPD_IOU_SLCR_MIO_PIN_15_L3_SEL_WIDTH   3
#define LPD_IOU_SLCR_MIO_PIN_15_L3_SEL_MASK    0X00000380

#define LPD_IOU_SLCR_MIO_PIN_15_L2_SEL_SHIFT   5
#define LPD_IOU_SLCR_MIO_PIN_15_L2_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_15_L2_SEL_MASK    0X00000060

#define LPD_IOU_SLCR_MIO_PIN_15_L1_SEL_SHIFT   3
#define LPD_IOU_SLCR_MIO_PIN_15_L1_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_15_L1_SEL_MASK    0X00000018

#define LPD_IOU_SLCR_MIO_PIN_15_L0_SEL_SHIFT   1
#define LPD_IOU_SLCR_MIO_PIN_15_L0_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_15_L0_SEL_MASK    0X00000006

/**
 * Register: LPD_IOU_SLCR_MIO_PIN_16
 */
#define LPD_IOU_SLCR_MIO_PIN_16    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000040 )

#define LPD_IOU_SLCR_MIO_PIN_16_L3_SEL_SHIFT   7
#define LPD_IOU_SLCR_MIO_PIN_16_L3_SEL_WIDTH   3
#define LPD_IOU_SLCR_MIO_PIN_16_L3_SEL_MASK    0X00000380

#define LPD_IOU_SLCR_MIO_PIN_16_L2_SEL_SHIFT   5
#define LPD_IOU_SLCR_MIO_PIN_16_L2_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_16_L2_SEL_MASK    0X00000060

#define LPD_IOU_SLCR_MIO_PIN_16_L1_SEL_SHIFT   3
#define LPD_IOU_SLCR_MIO_PIN_16_L1_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_16_L1_SEL_MASK    0X00000018

#define LPD_IOU_SLCR_MIO_PIN_16_L0_SEL_SHIFT   1
#define LPD_IOU_SLCR_MIO_PIN_16_L0_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_16_L0_SEL_MASK    0X00000006

/**
 * Register: LPD_IOU_SLCR_MIO_PIN_17
 */
#define LPD_IOU_SLCR_MIO_PIN_17    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000044 )

#define LPD_IOU_SLCR_MIO_PIN_17_L3_SEL_SHIFT   7
#define LPD_IOU_SLCR_MIO_PIN_17_L3_SEL_WIDTH   3
#define LPD_IOU_SLCR_MIO_PIN_17_L3_SEL_MASK    0X00000380

#define LPD_IOU_SLCR_MIO_PIN_17_L2_SEL_SHIFT   5
#define LPD_IOU_SLCR_MIO_PIN_17_L2_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_17_L2_SEL_MASK    0X00000060

#define LPD_IOU_SLCR_MIO_PIN_17_L1_SEL_SHIFT   3
#define LPD_IOU_SLCR_MIO_PIN_17_L1_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_17_L1_SEL_MASK    0X00000018

#define LPD_IOU_SLCR_MIO_PIN_17_L0_SEL_SHIFT   1
#define LPD_IOU_SLCR_MIO_PIN_17_L0_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_17_L0_SEL_MASK    0X00000006

/**
 * Register: LPD_IOU_SLCR_MIO_PIN_18
 */
#define LPD_IOU_SLCR_MIO_PIN_18    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000048 )

#define LPD_IOU_SLCR_MIO_PIN_18_L3_SEL_SHIFT   7
#define LPD_IOU_SLCR_MIO_PIN_18_L3_SEL_WIDTH   3
#define LPD_IOU_SLCR_MIO_PIN_18_L3_SEL_MASK    0X00000380

#define LPD_IOU_SLCR_MIO_PIN_18_L2_SEL_SHIFT   5
#define LPD_IOU_SLCR_MIO_PIN_18_L2_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_18_L2_SEL_MASK    0X00000060

#define LPD_IOU_SLCR_MIO_PIN_18_L1_SEL_SHIFT   3
#define LPD_IOU_SLCR_MIO_PIN_18_L1_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_18_L1_SEL_MASK    0X00000018

#define LPD_IOU_SLCR_MIO_PIN_18_L0_SEL_SHIFT   1
#define LPD_IOU_SLCR_MIO_PIN_18_L0_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_18_L0_SEL_MASK    0X00000006

/**
 * Register: LPD_IOU_SLCR_MIO_PIN_19
 */
#define LPD_IOU_SLCR_MIO_PIN_19    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X0000004C )

#define LPD_IOU_SLCR_MIO_PIN_19_L3_SEL_SHIFT   7
#define LPD_IOU_SLCR_MIO_PIN_19_L3_SEL_WIDTH   3
#define LPD_IOU_SLCR_MIO_PIN_19_L3_SEL_MASK    0X00000380

#define LPD_IOU_SLCR_MIO_PIN_19_L2_SEL_SHIFT   5
#define LPD_IOU_SLCR_MIO_PIN_19_L2_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_19_L2_SEL_MASK    0X00000060

#define LPD_IOU_SLCR_MIO_PIN_19_L1_SEL_SHIFT   3
#define LPD_IOU_SLCR_MIO_PIN_19_L1_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_19_L1_SEL_MASK    0X00000018

#define LPD_IOU_SLCR_MIO_PIN_19_L0_SEL_SHIFT   1
#define LPD_IOU_SLCR_MIO_PIN_19_L0_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_19_L0_SEL_MASK    0X00000006

/**
 * Register: LPD_IOU_SLCR_MIO_PIN_20
 */
#define LPD_IOU_SLCR_MIO_PIN_20    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000050 )

#define LPD_IOU_SLCR_MIO_PIN_20_L3_SEL_SHIFT   7
#define LPD_IOU_SLCR_MIO_PIN_20_L3_SEL_WIDTH   3
#define LPD_IOU_SLCR_MIO_PIN_20_L3_SEL_MASK    0X00000380

#define LPD_IOU_SLCR_MIO_PIN_20_L2_SEL_SHIFT   5
#define LPD_IOU_SLCR_MIO_PIN_20_L2_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_20_L2_SEL_MASK    0X00000060

#define LPD_IOU_SLCR_MIO_PIN_20_L1_SEL_SHIFT   3
#define LPD_IOU_SLCR_MIO_PIN_20_L1_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_20_L1_SEL_MASK    0X00000018

#define LPD_IOU_SLCR_MIO_PIN_20_L0_SEL_SHIFT   1
#define LPD_IOU_SLCR_MIO_PIN_20_L0_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_20_L0_SEL_MASK    0X00000006

/**
 * Register: LPD_IOU_SLCR_MIO_PIN_21
 */
#define LPD_IOU_SLCR_MIO_PIN_21    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000054 )

#define LPD_IOU_SLCR_MIO_PIN_21_L3_SEL_SHIFT   7
#define LPD_IOU_SLCR_MIO_PIN_21_L3_SEL_WIDTH   3
#define LPD_IOU_SLCR_MIO_PIN_21_L3_SEL_MASK    0X00000380

#define LPD_IOU_SLCR_MIO_PIN_21_L2_SEL_SHIFT   5
#define LPD_IOU_SLCR_MIO_PIN_21_L2_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_21_L2_SEL_MASK    0X00000060

#define LPD_IOU_SLCR_MIO_PIN_21_L1_SEL_SHIFT   3
#define LPD_IOU_SLCR_MIO_PIN_21_L1_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_21_L1_SEL_MASK    0X00000018

#define LPD_IOU_SLCR_MIO_PIN_21_L0_SEL_SHIFT   1
#define LPD_IOU_SLCR_MIO_PIN_21_L0_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_21_L0_SEL_MASK    0X00000006

/**
 * Register: LPD_IOU_SLCR_MIO_PIN_22
 */
#define LPD_IOU_SLCR_MIO_PIN_22    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000058 )

#define LPD_IOU_SLCR_MIO_PIN_22_L3_SEL_SHIFT   7
#define LPD_IOU_SLCR_MIO_PIN_22_L3_SEL_WIDTH   3
#define LPD_IOU_SLCR_MIO_PIN_22_L3_SEL_MASK    0X00000380

#define LPD_IOU_SLCR_MIO_PIN_22_L2_SEL_SHIFT   5
#define LPD_IOU_SLCR_MIO_PIN_22_L2_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_22_L2_SEL_MASK    0X00000060

#define LPD_IOU_SLCR_MIO_PIN_22_L1_SEL_SHIFT   3
#define LPD_IOU_SLCR_MIO_PIN_22_L1_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_22_L1_SEL_MASK    0X00000018

#define LPD_IOU_SLCR_MIO_PIN_22_L0_SEL_SHIFT   1
#define LPD_IOU_SLCR_MIO_PIN_22_L0_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_22_L0_SEL_MASK    0X00000006

/**
 * Register: LPD_IOU_SLCR_MIO_PIN_23
 */
#define LPD_IOU_SLCR_MIO_PIN_23    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X0000005C )

#define LPD_IOU_SLCR_MIO_PIN_23_L3_SEL_SHIFT   7
#define LPD_IOU_SLCR_MIO_PIN_23_L3_SEL_WIDTH   3
#define LPD_IOU_SLCR_MIO_PIN_23_L3_SEL_MASK    0X00000380

#define LPD_IOU_SLCR_MIO_PIN_23_L2_SEL_SHIFT   5
#define LPD_IOU_SLCR_MIO_PIN_23_L2_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_23_L2_SEL_MASK    0X00000060

#define LPD_IOU_SLCR_MIO_PIN_23_L1_SEL_SHIFT   3
#define LPD_IOU_SLCR_MIO_PIN_23_L1_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_23_L1_SEL_MASK    0X00000018

#define LPD_IOU_SLCR_MIO_PIN_23_L0_SEL_SHIFT   1
#define LPD_IOU_SLCR_MIO_PIN_23_L0_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_23_L0_SEL_MASK    0X00000006

/**
 * Register: LPD_IOU_SLCR_MIO_PIN_24
 */
#define LPD_IOU_SLCR_MIO_PIN_24    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000060 )

#define LPD_IOU_SLCR_MIO_PIN_24_L3_SEL_SHIFT   7
#define LPD_IOU_SLCR_MIO_PIN_24_L3_SEL_WIDTH   3
#define LPD_IOU_SLCR_MIO_PIN_24_L3_SEL_MASK    0X00000380

#define LPD_IOU_SLCR_MIO_PIN_24_L2_SEL_SHIFT   5
#define LPD_IOU_SLCR_MIO_PIN_24_L2_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_24_L2_SEL_MASK    0X00000060

#define LPD_IOU_SLCR_MIO_PIN_24_L1_SEL_SHIFT   3
#define LPD_IOU_SLCR_MIO_PIN_24_L1_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_24_L1_SEL_MASK    0X00000018

#define LPD_IOU_SLCR_MIO_PIN_24_L0_SEL_SHIFT   1
#define LPD_IOU_SLCR_MIO_PIN_24_L0_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_24_L0_SEL_MASK    0X00000006

/**
 * Register: LPD_IOU_SLCR_MIO_PIN_25
 */
#define LPD_IOU_SLCR_MIO_PIN_25    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000064 )

#define LPD_IOU_SLCR_MIO_PIN_25_L3_SEL_SHIFT   7
#define LPD_IOU_SLCR_MIO_PIN_25_L3_SEL_WIDTH   3
#define LPD_IOU_SLCR_MIO_PIN_25_L3_SEL_MASK    0X00000380

#define LPD_IOU_SLCR_MIO_PIN_25_L2_SEL_SHIFT   5
#define LPD_IOU_SLCR_MIO_PIN_25_L2_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_25_L2_SEL_MASK    0X00000060

#define LPD_IOU_SLCR_MIO_PIN_25_L1_SEL_SHIFT   3
#define LPD_IOU_SLCR_MIO_PIN_25_L1_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_25_L1_SEL_MASK    0X00000018

#define LPD_IOU_SLCR_MIO_PIN_25_L0_SEL_SHIFT   1
#define LPD_IOU_SLCR_MIO_PIN_25_L0_SEL_WIDTH   2
#define LPD_IOU_SLCR_MIO_PIN_25_L0_SEL_MASK    0X00000006

/**
 * Register: LPD_IOU_SLCR_BNK2_EN_RX
 */
#define LPD_IOU_SLCR_BNK2_EN_RX    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000100 )

#define LPD_IOU_SLCR_BNK2_EN_RX_BNK2_EN_RX_SHIFT   0
#define LPD_IOU_SLCR_BNK2_EN_RX_BNK2_EN_RX_WIDTH   26
#define LPD_IOU_SLCR_BNK2_EN_RX_BNK2_EN_RX_MASK    0X03FFFFFF

/**
 * Register: LPD_IOU_SLCR_BNK2_SEL_RX0
 */
#define LPD_IOU_SLCR_BNK2_SEL_RX0    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000104 )

#define LPD_IOU_SLCR_BNK2_SEL_RX0_BNK2_SEL_RX_SHIFT   0
#define LPD_IOU_SLCR_BNK2_SEL_RX0_BNK2_SEL_RX_WIDTH   32
#define LPD_IOU_SLCR_BNK2_SEL_RX0_BNK2_SEL_RX_MASK    0XFFFFFFFF

/**
 * Register: LPD_IOU_SLCR_BNK2_SEL_RX1
 */
#define LPD_IOU_SLCR_BNK2_SEL_RX1    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000108 )

#define LPD_IOU_SLCR_BNK2_SEL_RX1_BNK2_SEL_RX_SHIFT   0
#define LPD_IOU_SLCR_BNK2_SEL_RX1_BNK2_SEL_RX_WIDTH   20
#define LPD_IOU_SLCR_BNK2_SEL_RX1_BNK2_SEL_RX_MASK    0X000FFFFF

/**
 * Register: LPD_IOU_SLCR_BNK2_EN_RX_SCHMITT_HYST
 */
#define LPD_IOU_SLCR_BNK2_EN_RX_SCHMITT_HYST    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X0000010C )

#define LPD_IOU_SLCR_BNK2_EN_RX_SCHMITT_HYST_BNK2_EN_RX_SCHMITT_HYST_SHIFT   0
#define LPD_IOU_SLCR_BNK2_EN_RX_SCHMITT_HYST_BNK2_EN_RX_SCHMITT_HYST_WIDTH   26
#define LPD_IOU_SLCR_BNK2_EN_RX_SCHMITT_HYST_BNK2_EN_RX_SCHMITT_HYST_MASK    0X03FFFFFF

/**
 * Register: LPD_IOU_SLCR_BNK2_EN_WK_PD
 */
#define LPD_IOU_SLCR_BNK2_EN_WK_PD    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000110 )

#define LPD_IOU_SLCR_BNK2_EN_WK_PD_BNK2_EN_WK_PD_SHIFT   0
#define LPD_IOU_SLCR_BNK2_EN_WK_PD_BNK2_EN_WK_PD_WIDTH   26
#define LPD_IOU_SLCR_BNK2_EN_WK_PD_BNK2_EN_WK_PD_MASK    0X03FFFFFF

/**
 * Register: LPD_IOU_SLCR_BNK2_EN_WK_PU
 */
#define LPD_IOU_SLCR_BNK2_EN_WK_PU    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000114 )

#define LPD_IOU_SLCR_BNK2_EN_WK_PU_BNK2_EN_WK_PU_SHIFT   0
#define LPD_IOU_SLCR_BNK2_EN_WK_PU_BNK2_EN_WK_PU_WIDTH   26
#define LPD_IOU_SLCR_BNK2_EN_WK_PU_BNK2_EN_WK_PU_MASK    0X03FFFFFF

/**
 * Register: LPD_IOU_SLCR_BNK2_SEL_DRV0
 */
#define LPD_IOU_SLCR_BNK2_SEL_DRV0    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000118 )

#define LPD_IOU_SLCR_BNK2_SEL_DRV0_BNK2_SEL_DRV_SHIFT   0
#define LPD_IOU_SLCR_BNK2_SEL_DRV0_BNK2_SEL_DRV_WIDTH   32
#define LPD_IOU_SLCR_BNK2_SEL_DRV0_BNK2_SEL_DRV_MASK    0XFFFFFFFF

/**
 * Register: LPD_IOU_SLCR_BNK2_SEL_DRV1
 */
#define LPD_IOU_SLCR_BNK2_SEL_DRV1    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X0000011C )

#define LPD_IOU_SLCR_BNK2_SEL_DRV1_BNK2_SEL_DRV_SHIFT   0
#define LPD_IOU_SLCR_BNK2_SEL_DRV1_BNK2_SEL_DRV_WIDTH   20
#define LPD_IOU_SLCR_BNK2_SEL_DRV1_BNK2_SEL_DRV_MASK    0X000FFFFF

/**
 * Register: LPD_IOU_SLCR_BNK2_SEL_SLEW
 */
#define LPD_IOU_SLCR_BNK2_SEL_SLEW    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000120 )

#define LPD_IOU_SLCR_BNK2_SEL_SLEW_BNK2_SEL_SLEW_SHIFT   0
#define LPD_IOU_SLCR_BNK2_SEL_SLEW_BNK2_SEL_SLEW_WIDTH   26
#define LPD_IOU_SLCR_BNK2_SEL_SLEW_BNK2_SEL_SLEW_MASK    0X03FFFFFF

/**
 * Register: LPD_IOU_SLCR_BNK2_EN_DFT_OPT_INV
 */
#define LPD_IOU_SLCR_BNK2_EN_DFT_OPT_INV    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000124 )

#define LPD_IOU_SLCR_BNK2_EN_DFT_OPT_INV_BNK2_EN_DFT_OPT_INV_SHIFT   0
#define LPD_IOU_SLCR_BNK2_EN_DFT_OPT_INV_BNK2_EN_DFT_OPT_INV_WIDTH   26
#define LPD_IOU_SLCR_BNK2_EN_DFT_OPT_INV_BNK2_EN_DFT_OPT_INV_MASK    0X03FFFFFF

/**
 * Register: LPD_IOU_SLCR_BNK2_EN_PAD2PAD_LOOPBACK
 */
#define LPD_IOU_SLCR_BNK2_EN_PAD2PAD_LOOPBACK    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000128 )

#define LPD_IOU_SLCR_BNK2_EN_PAD2PAD_LOOPBACK_BNK2_EN_PAD2PAD_LOOPBACK_SHIFT   0
#define LPD_IOU_SLCR_BNK2_EN_PAD2PAD_LOOPBACK_BNK2_EN_PAD2PAD_LOOPBACK_WIDTH   13
#define LPD_IOU_SLCR_BNK2_EN_PAD2PAD_LOOPBACK_BNK2_EN_PAD2PAD_LOOPBACK_MASK    0X00001FFF

/**
 * Register: LPD_IOU_SLCR_BNK2_RX_SPARE0
 */
#define LPD_IOU_SLCR_BNK2_RX_SPARE0    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X0000012C )

#define LPD_IOU_SLCR_BNK2_RX_SPARE0_BNK2_RX_SPARE_SHIFT   0
#define LPD_IOU_SLCR_BNK2_RX_SPARE0_BNK2_RX_SPARE_WIDTH   32
#define LPD_IOU_SLCR_BNK2_RX_SPARE0_BNK2_RX_SPARE_MASK    0XFFFFFFFF

/**
 * Register: LPD_IOU_SLCR_BNK2_RX_SPARE1
 */
#define LPD_IOU_SLCR_BNK2_RX_SPARE1    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000130 )

#define LPD_IOU_SLCR_BNK2_RX_SPARE1_BNK2_RX_SPARE_SHIFT   0
#define LPD_IOU_SLCR_BNK2_RX_SPARE1_BNK2_RX_SPARE_WIDTH   20
#define LPD_IOU_SLCR_BNK2_RX_SPARE1_BNK2_RX_SPARE_MASK    0X000FFFFF

/**
 * Register: LPD_IOU_SLCR_BNK2_TX_SPARE0
 */
#define LPD_IOU_SLCR_BNK2_TX_SPARE0    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000134 )

#define LPD_IOU_SLCR_BNK2_TX_SPARE0_BNK2_TX_SPARE_SHIFT   0
#define LPD_IOU_SLCR_BNK2_TX_SPARE0_BNK2_TX_SPARE_WIDTH   32
#define LPD_IOU_SLCR_BNK2_TX_SPARE0_BNK2_TX_SPARE_MASK    0XFFFFFFFF

/**
 * Register: LPD_IOU_SLCR_BNK2_TX_SPARE1
 */
#define LPD_IOU_SLCR_BNK2_TX_SPARE1    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000138 )

#define LPD_IOU_SLCR_BNK2_TX_SPARE1_BNK2_TX_SPARE_SHIFT   0
#define LPD_IOU_SLCR_BNK2_TX_SPARE1_BNK2_TX_SPARE_WIDTH   20
#define LPD_IOU_SLCR_BNK2_TX_SPARE1_BNK2_TX_SPARE_MASK    0X000FFFFF

/**
 * Register: LPD_IOU_SLCR_BNK2_SEL_EN1P8
 */
#define LPD_IOU_SLCR_BNK2_SEL_EN1P8    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X0000013C )

#define LPD_IOU_SLCR_BNK2_SEL_EN1P8_BNK2_SEL_EN1P8_SHIFT   0
#define LPD_IOU_SLCR_BNK2_SEL_EN1P8_BNK2_SEL_EN1P8_WIDTH   1
#define LPD_IOU_SLCR_BNK2_SEL_EN1P8_BNK2_SEL_EN1P8_MASK    0X00000001

/**
 * Register: LPD_IOU_SLCR_BNK2_EN_B_POR_DETECT
 */
#define LPD_IOU_SLCR_BNK2_EN_B_POR_DETECT    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000140 )

#define LPD_IOU_SLCR_BNK2_EN_B_POR_DETECT_BNK2_EN_B_POR_DETECT_SHIFT   0
#define LPD_IOU_SLCR_BNK2_EN_B_POR_DETECT_BNK2_EN_B_POR_DETECT_WIDTH   1
#define LPD_IOU_SLCR_BNK2_EN_B_POR_DETECT_BNK2_EN_B_POR_DETECT_MASK    0X00000001

/**
 * Register: LPD_IOU_SLCR_BNK2_LPF_BYP_POR_DETECT
 */
#define LPD_IOU_SLCR_BNK2_LPF_BYP_POR_DETECT    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000144 )

#define LPD_IOU_SLCR_BNK2_LPF_BYP_POR_DETECT_BNK2_LPF_BYP_POR_DETECT_SHIFT   0
#define LPD_IOU_SLCR_BNK2_LPF_BYP_POR_DETECT_BNK2_LPF_BYP_POR_DETECT_WIDTH   1
#define LPD_IOU_SLCR_BNK2_LPF_BYP_POR_DETECT_BNK2_LPF_BYP_POR_DETECT_MASK    0X00000001

/**
 * Register: LPD_IOU_SLCR_BNK2_EN_LATCH
 */
#define LPD_IOU_SLCR_BNK2_EN_LATCH    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000148 )

#define LPD_IOU_SLCR_BNK2_EN_LATCH_BNK2_EN_LATCH_SHIFT   0
#define LPD_IOU_SLCR_BNK2_EN_LATCH_BNK2_EN_LATCH_WIDTH   1
#define LPD_IOU_SLCR_BNK2_EN_LATCH_BNK2_EN_LATCH_MASK    0X00000001

/**
 * Register: LPD_IOU_SLCR_BNK2_VBG_LPF_BYP_B
 */
#define LPD_IOU_SLCR_BNK2_VBG_LPF_BYP_B    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X0000014C )

#define LPD_IOU_SLCR_BNK2_VBG_LPF_BYP_B_BNK2_VBG_LPF_BYP_B_SHIFT   0
#define LPD_IOU_SLCR_BNK2_VBG_LPF_BYP_B_BNK2_VBG_LPF_BYP_B_WIDTH   1
#define LPD_IOU_SLCR_BNK2_VBG_LPF_BYP_B_BNK2_VBG_LPF_BYP_B_MASK    0X00000001

/**
 * Register: LPD_IOU_SLCR_BNK2_EN_AMP_B
 */
#define LPD_IOU_SLCR_BNK2_EN_AMP_B    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000150 )

#define LPD_IOU_SLCR_BNK2_EN_AMP_B_BNK2_EN_AMP_B_SHIFT   0
#define LPD_IOU_SLCR_BNK2_EN_AMP_B_BNK2_EN_AMP_B_WIDTH   2
#define LPD_IOU_SLCR_BNK2_EN_AMP_B_BNK2_EN_AMP_B_MASK    0X00000003

/**
 * Register: LPD_IOU_SLCR_BNK2_SPARE_BIAS
 */
#define LPD_IOU_SLCR_BNK2_SPARE_BIAS    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000154 )

#define LPD_IOU_SLCR_BNK2_SPARE_BIAS_BNK2_SPARE_BIAS_SHIFT   0
#define LPD_IOU_SLCR_BNK2_SPARE_BIAS_BNK2_SPARE_BIAS_WIDTH   4
#define LPD_IOU_SLCR_BNK2_SPARE_BIAS_BNK2_SPARE_BIAS_MASK    0X0000000F

/**
 * Register: LPD_IOU_SLCR_BNK2_DRIVER_BIAS
 */
#define LPD_IOU_SLCR_BNK2_DRIVER_BIAS    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000158 )

#define LPD_IOU_SLCR_BNK2_DRIVER_BIAS_BNK2_DRIVER_BIAS_SHIFT   0
#define LPD_IOU_SLCR_BNK2_DRIVER_BIAS_BNK2_DRIVER_BIAS_WIDTH   15
#define LPD_IOU_SLCR_BNK2_DRIVER_BIAS_BNK2_DRIVER_BIAS_MASK    0X00007FFF

/**
 * Register: LPD_IOU_SLCR_BNK2_VMODE
 */
#define LPD_IOU_SLCR_BNK2_VMODE    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X0000015C )

#define LPD_IOU_SLCR_BNK2_VMODE_BNK2_VMODE_SHIFT   0
#define LPD_IOU_SLCR_BNK2_VMODE_BNK2_VMODE_WIDTH   1
#define LPD_IOU_SLCR_BNK2_VMODE_BNK2_VMODE_MASK    0X00000001

/**
 * Register: LPD_IOU_SLCR_BNK2_SEL_AUX_IO_RX
 */
#define LPD_IOU_SLCR_BNK2_SEL_AUX_IO_RX    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000160 )

#define LPD_IOU_SLCR_BNK2_SEL_AUX_IO_RX_BNK2_SEL_AUX_IO_RX_SHIFT   0
#define LPD_IOU_SLCR_BNK2_SEL_AUX_IO_RX_BNK2_SEL_AUX_IO_RX_WIDTH   26
#define LPD_IOU_SLCR_BNK2_SEL_AUX_IO_RX_BNK2_SEL_AUX_IO_RX_MASK    0X03FFFFFF

/**
 * Register: LPD_IOU_SLCR_BNK2_EN_TX_HS_MODE
 */
#define LPD_IOU_SLCR_BNK2_EN_TX_HS_MODE    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000164 )

#define LPD_IOU_SLCR_BNK2_EN_TX_HS_MODE_BNK2_EN_TX_HS_MODE_SHIFT   0
#define LPD_IOU_SLCR_BNK2_EN_TX_HS_MODE_BNK2_EN_TX_HS_MODE_WIDTH   26
#define LPD_IOU_SLCR_BNK2_EN_TX_HS_MODE_BNK2_EN_TX_HS_MODE_MASK    0X03FFFFFF

/**
 * Register: LPD_IOU_SLCR_MIO_LOOPBACK
 */
#define LPD_IOU_SLCR_MIO_LOOPBACK    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000200 )

#define LPD_IOU_SLCR_MIO_LOOPBACK_I2C0_LOOP_I2C1_SHIFT   3
#define LPD_IOU_SLCR_MIO_LOOPBACK_I2C0_LOOP_I2C1_WIDTH   1
#define LPD_IOU_SLCR_MIO_LOOPBACK_I2C0_LOOP_I2C1_MASK    0X00000008

#define LPD_IOU_SLCR_MIO_LOOPBACK_CAN0_LOOP_CAN1_SHIFT   2
#define LPD_IOU_SLCR_MIO_LOOPBACK_CAN0_LOOP_CAN1_WIDTH   1
#define LPD_IOU_SLCR_MIO_LOOPBACK_CAN0_LOOP_CAN1_MASK    0X00000004

#define LPD_IOU_SLCR_MIO_LOOPBACK_UA0_LOOP_UA1_SHIFT   1
#define LPD_IOU_SLCR_MIO_LOOPBACK_UA0_LOOP_UA1_WIDTH   1
#define LPD_IOU_SLCR_MIO_LOOPBACK_UA0_LOOP_UA1_MASK    0X00000002

#define LPD_IOU_SLCR_MIO_LOOPBACK_SPI0_LOOP_SPI1_SHIFT   0
#define LPD_IOU_SLCR_MIO_LOOPBACK_SPI0_LOOP_SPI1_WIDTH   1
#define LPD_IOU_SLCR_MIO_LOOPBACK_SPI0_LOOP_SPI1_MASK    0X00000001

/**
 * Register: LPD_IOU_SLCR_MIO_MST_TRI0
 */
#define LPD_IOU_SLCR_MIO_MST_TRI0    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000204 )

#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_25_TRI_SHIFT   25
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_25_TRI_WIDTH   1
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_25_TRI_MASK    0X02000000

#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_24_TRI_SHIFT   24
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_24_TRI_WIDTH   1
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_24_TRI_MASK    0X01000000

#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_23_TRI_SHIFT   23
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_23_TRI_WIDTH   1
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_23_TRI_MASK    0X00800000

#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_22_TRI_SHIFT   22
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_22_TRI_WIDTH   1
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_22_TRI_MASK    0X00400000

#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_21_TRI_SHIFT   21
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_21_TRI_WIDTH   1
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_21_TRI_MASK    0X00200000

#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_20_TRI_SHIFT   20
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_20_TRI_WIDTH   1
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_20_TRI_MASK    0X00100000

#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_19_TRI_SHIFT   19
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_19_TRI_WIDTH   1
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_19_TRI_MASK    0X00080000

#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_18_TRI_SHIFT   18
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_18_TRI_WIDTH   1
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_18_TRI_MASK    0X00040000

#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_17_TRI_SHIFT   17
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_17_TRI_WIDTH   1
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_17_TRI_MASK    0X00020000

#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_16_TRI_SHIFT   16
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_16_TRI_WIDTH   1
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_16_TRI_MASK    0X00010000

#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_15_TRI_SHIFT   15
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_15_TRI_WIDTH   1
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_15_TRI_MASK    0X00008000

#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_14_TRI_SHIFT   14
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_14_TRI_WIDTH   1
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_14_TRI_MASK    0X00004000

#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_13_TRI_SHIFT   13
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_13_TRI_WIDTH   1
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_13_TRI_MASK    0X00002000

#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_12_TRI_SHIFT   12
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_12_TRI_WIDTH   1
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_12_TRI_MASK    0X00001000

#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_11_TRI_SHIFT   11
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_11_TRI_WIDTH   1
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_11_TRI_MASK    0X00000800

#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_10_TRI_SHIFT   10
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_10_TRI_WIDTH   1
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_10_TRI_MASK    0X00000400

#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_09_TRI_SHIFT   9
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_09_TRI_WIDTH   1
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_09_TRI_MASK    0X00000200

#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_08_TRI_SHIFT   8
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_08_TRI_WIDTH   1
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_08_TRI_MASK    0X00000100

#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_07_TRI_SHIFT   7
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_07_TRI_WIDTH   1
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_07_TRI_MASK    0X00000080

#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_06_TRI_SHIFT   6
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_06_TRI_WIDTH   1
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_06_TRI_MASK    0X00000040

#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_05_TRI_SHIFT   5
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_05_TRI_WIDTH   1
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_05_TRI_MASK    0X00000020

#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_04_TRI_SHIFT   4
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_04_TRI_WIDTH   1
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_04_TRI_MASK    0X00000010

#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_03_TRI_SHIFT   3
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_03_TRI_WIDTH   1
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_03_TRI_MASK    0X00000008

#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_02_TRI_SHIFT   2
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_02_TRI_WIDTH   1
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_02_TRI_MASK    0X00000004

#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_01_TRI_SHIFT   1
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_01_TRI_WIDTH   1
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_01_TRI_MASK    0X00000002

#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_00_TRI_SHIFT   0
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_00_TRI_WIDTH   1
#define LPD_IOU_SLCR_MIO_MST_TRI0_PIN_00_TRI_MASK    0X00000001

/**
 * Register: LPD_IOU_SLCR_WDT_CLK_SEL
 */
#define LPD_IOU_SLCR_WDT_CLK_SEL    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000300 )

#define LPD_IOU_SLCR_WDT_CLK_SEL_SELECT_SHIFT   0
#define LPD_IOU_SLCR_WDT_CLK_SEL_SELECT_WIDTH   1
#define LPD_IOU_SLCR_WDT_CLK_SEL_SELECT_MASK    0X00000001

/**
 * Register: LPD_IOU_SLCR_CAN_MIO_CTRL
 */
#define LPD_IOU_SLCR_CAN_MIO_CTRL    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000310 )

#define LPD_IOU_SLCR_CAN_MIO_CTRL_CAN1_RXIN_REG_SHIFT   23
#define LPD_IOU_SLCR_CAN_MIO_CTRL_CAN1_RXIN_REG_WIDTH   1
#define LPD_IOU_SLCR_CAN_MIO_CTRL_CAN1_RXIN_REG_MASK    0X00800000

#define LPD_IOU_SLCR_CAN_MIO_CTRL_CAN1_REF_SEL_SHIFT   22
#define LPD_IOU_SLCR_CAN_MIO_CTRL_CAN1_REF_SEL_WIDTH   1
#define LPD_IOU_SLCR_CAN_MIO_CTRL_CAN1_REF_SEL_MASK    0X00400000

#define LPD_IOU_SLCR_CAN_MIO_CTRL_CAN1_MUX_SHIFT   15
#define LPD_IOU_SLCR_CAN_MIO_CTRL_CAN1_MUX_WIDTH   7
#define LPD_IOU_SLCR_CAN_MIO_CTRL_CAN1_MUX_MASK    0X003F8000

#define LPD_IOU_SLCR_CAN_MIO_CTRL_CAN0_RXIN_REG_SHIFT   8
#define LPD_IOU_SLCR_CAN_MIO_CTRL_CAN0_RXIN_REG_WIDTH   1
#define LPD_IOU_SLCR_CAN_MIO_CTRL_CAN0_RXIN_REG_MASK    0X00000100

#define LPD_IOU_SLCR_CAN_MIO_CTRL_CAN0_REF_SEL_SHIFT   7
#define LPD_IOU_SLCR_CAN_MIO_CTRL_CAN0_REF_SEL_WIDTH   1
#define LPD_IOU_SLCR_CAN_MIO_CTRL_CAN0_REF_SEL_MASK    0X00000080

#define LPD_IOU_SLCR_CAN_MIO_CTRL_CAN0_MUX_SHIFT   0
#define LPD_IOU_SLCR_CAN_MIO_CTRL_CAN0_MUX_WIDTH   7
#define LPD_IOU_SLCR_CAN_MIO_CTRL_CAN0_MUX_MASK    0X0000007F

/**
 * Register: LPD_IOU_SLCR_GEM_CLK_CTRL
 */
#define LPD_IOU_SLCR_GEM_CLK_CTRL    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000320 )

#define LPD_IOU_SLCR_GEM_CLK_CTRL_TSU_CLK_LB_SEL_SHIFT   22
#define LPD_IOU_SLCR_GEM_CLK_CTRL_TSU_CLK_LB_SEL_WIDTH   1
#define LPD_IOU_SLCR_GEM_CLK_CTRL_TSU_CLK_LB_SEL_MASK    0X00400000

#define LPD_IOU_SLCR_GEM_CLK_CTRL_TSU_CLK_SEL_SHIFT   20
#define LPD_IOU_SLCR_GEM_CLK_CTRL_TSU_CLK_SEL_WIDTH   2
#define LPD_IOU_SLCR_GEM_CLK_CTRL_TSU_CLK_SEL_MASK    0X00300000

#define LPD_IOU_SLCR_GEM_CLK_CTRL_GEM1_FIFO_CLK_SEL_SHIFT   7
#define LPD_IOU_SLCR_GEM_CLK_CTRL_GEM1_FIFO_CLK_SEL_WIDTH   1
#define LPD_IOU_SLCR_GEM_CLK_CTRL_GEM1_FIFO_CLK_SEL_MASK    0X00000080

#define LPD_IOU_SLCR_GEM_CLK_CTRL_GEM1_REF_SRC_SEL_SHIFT   6
#define LPD_IOU_SLCR_GEM_CLK_CTRL_GEM1_REF_SRC_SEL_WIDTH   1
#define LPD_IOU_SLCR_GEM_CLK_CTRL_GEM1_REF_SRC_SEL_MASK    0X00000040

#define LPD_IOU_SLCR_GEM_CLK_CTRL_GEM1_RX_SRC_SEL_SHIFT   5
#define LPD_IOU_SLCR_GEM_CLK_CTRL_GEM1_RX_SRC_SEL_WIDTH   1
#define LPD_IOU_SLCR_GEM_CLK_CTRL_GEM1_RX_SRC_SEL_MASK    0X00000020

#define LPD_IOU_SLCR_GEM_CLK_CTRL_GEM0_FIFO_CLK_SEL_SHIFT   2
#define LPD_IOU_SLCR_GEM_CLK_CTRL_GEM0_FIFO_CLK_SEL_WIDTH   1
#define LPD_IOU_SLCR_GEM_CLK_CTRL_GEM0_FIFO_CLK_SEL_MASK    0X00000004

#define LPD_IOU_SLCR_GEM_CLK_CTRL_GEM0_REF_SRC_SEL_SHIFT   1
#define LPD_IOU_SLCR_GEM_CLK_CTRL_GEM0_REF_SRC_SEL_WIDTH   1
#define LPD_IOU_SLCR_GEM_CLK_CTRL_GEM0_REF_SRC_SEL_MASK    0X00000002

#define LPD_IOU_SLCR_GEM_CLK_CTRL_GEM0_RX_SRC_SEL_SHIFT   0
#define LPD_IOU_SLCR_GEM_CLK_CTRL_GEM0_RX_SRC_SEL_WIDTH   1
#define LPD_IOU_SLCR_GEM_CLK_CTRL_GEM0_RX_SRC_SEL_MASK    0X00000001

/**
 * Register: LPD_IOU_SLCR_GEM0_IOU_COHERENT_CTRL
 */
#define LPD_IOU_SLCR_GEM0_IOU_COHERENT_CTRL    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000324 )

#define LPD_IOU_SLCR_GEM0_IOU_COHERENT_CTRL_GEM0_AXI_COH_SHIFT   0
#define LPD_IOU_SLCR_GEM0_IOU_COHERENT_CTRL_GEM0_AXI_COH_WIDTH   4
#define LPD_IOU_SLCR_GEM0_IOU_COHERENT_CTRL_GEM0_AXI_COH_MASK    0X0000000F

/**
 * Register: LPD_IOU_SLCR_GEM0_IOU_INTERCONNECT_ROUTE
 */
#define LPD_IOU_SLCR_GEM0_IOU_INTERCONNECT_ROUTE    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000328 )

#define LPD_IOU_SLCR_GEM0_IOU_INTERCONNECT_ROUTE_GEM0_SHIFT   0
#define LPD_IOU_SLCR_GEM0_IOU_INTERCONNECT_ROUTE_GEM0_WIDTH   1
#define LPD_IOU_SLCR_GEM0_IOU_INTERCONNECT_ROUTE_GEM0_MASK    0X00000001

/**
 * Register: LPD_IOU_SLCR_GEM0_IOU_INTERCONNECT_QOS
 */
#define LPD_IOU_SLCR_GEM0_IOU_INTERCONNECT_QOS    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X0000032C )

#define LPD_IOU_SLCR_GEM0_IOU_INTERCONNECT_QOS_GEM0_QOS_SHIFT   0
#define LPD_IOU_SLCR_GEM0_IOU_INTERCONNECT_QOS_GEM0_QOS_WIDTH   4
#define LPD_IOU_SLCR_GEM0_IOU_INTERCONNECT_QOS_GEM0_QOS_MASK    0X0000000F

/**
 * Register: LPD_IOU_SLCR_GEM1_IOU_COHERENT_CTRL
 */
#define LPD_IOU_SLCR_GEM1_IOU_COHERENT_CTRL    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000344 )

#define LPD_IOU_SLCR_GEM1_IOU_COHERENT_CTRL_GEM1_AXI_COH_SHIFT   0
#define LPD_IOU_SLCR_GEM1_IOU_COHERENT_CTRL_GEM1_AXI_COH_WIDTH   4
#define LPD_IOU_SLCR_GEM1_IOU_COHERENT_CTRL_GEM1_AXI_COH_MASK    0X0000000F

/**
 * Register: LPD_IOU_SLCR_GEM1_IOU_INTERCONNECT_ROUTE
 */
#define LPD_IOU_SLCR_GEM1_IOU_INTERCONNECT_ROUTE    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000348 )

#define LPD_IOU_SLCR_GEM1_IOU_INTERCONNECT_ROUTE_GEM1_SHIFT   0
#define LPD_IOU_SLCR_GEM1_IOU_INTERCONNECT_ROUTE_GEM1_WIDTH   1
#define LPD_IOU_SLCR_GEM1_IOU_INTERCONNECT_ROUTE_GEM1_MASK    0X00000001

/**
 * Register: LPD_IOU_SLCR_GEM1_IOU_INTERCONNECT_QOS
 */
#define LPD_IOU_SLCR_GEM1_IOU_INTERCONNECT_QOS    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X0000034C )

#define LPD_IOU_SLCR_GEM1_IOU_INTERCONNECT_QOS_GEM1_QOS_SHIFT   0
#define LPD_IOU_SLCR_GEM1_IOU_INTERCONNECT_QOS_GEM1_QOS_WIDTH   4
#define LPD_IOU_SLCR_GEM1_IOU_INTERCONNECT_QOS_GEM1_QOS_MASK    0X0000000F

/**
 * Register: LPD_IOU_SLCR_IOU_TTC_APB_CLK
 */
#define LPD_IOU_SLCR_IOU_TTC_APB_CLK    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000360 )

#define LPD_IOU_SLCR_IOU_TTC_APB_CLK_TTC3_SEL_SHIFT   6
#define LPD_IOU_SLCR_IOU_TTC_APB_CLK_TTC3_SEL_WIDTH   2
#define LPD_IOU_SLCR_IOU_TTC_APB_CLK_TTC3_SEL_MASK    0X000000C0

#define LPD_IOU_SLCR_IOU_TTC_APB_CLK_TTC2_SEL_SHIFT   4
#define LPD_IOU_SLCR_IOU_TTC_APB_CLK_TTC2_SEL_WIDTH   2
#define LPD_IOU_SLCR_IOU_TTC_APB_CLK_TTC2_SEL_MASK    0X00000030

#define LPD_IOU_SLCR_IOU_TTC_APB_CLK_TTC1_SEL_SHIFT   2
#define LPD_IOU_SLCR_IOU_TTC_APB_CLK_TTC1_SEL_WIDTH   2
#define LPD_IOU_SLCR_IOU_TTC_APB_CLK_TTC1_SEL_MASK    0X0000000C

#define LPD_IOU_SLCR_IOU_TTC_APB_CLK_TTC0_SEL_SHIFT   0
#define LPD_IOU_SLCR_IOU_TTC_APB_CLK_TTC0_SEL_WIDTH   2
#define LPD_IOU_SLCR_IOU_TTC_APB_CLK_TTC0_SEL_MASK    0X00000003

/**
 * Register: LPD_IOU_SLCR_LPD_MIO_SEL
 */
#define LPD_IOU_SLCR_LPD_MIO_SEL    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000410 )

#define LPD_IOU_SLCR_LPD_MIO_SEL_WWDT1_SEL_SHIFT   17
#define LPD_IOU_SLCR_LPD_MIO_SEL_WWDT1_SEL_WIDTH   1
#define LPD_IOU_SLCR_LPD_MIO_SEL_WWDT1_SEL_MASK    0X00020000

#define LPD_IOU_SLCR_LPD_MIO_SEL_WWDT0_SEL_SHIFT   16
#define LPD_IOU_SLCR_LPD_MIO_SEL_WWDT0_SEL_WIDTH   1
#define LPD_IOU_SLCR_LPD_MIO_SEL_WWDT0_SEL_MASK    0X00010000

#define LPD_IOU_SLCR_LPD_MIO_SEL_I2C1_SEL_SHIFT   15
#define LPD_IOU_SLCR_LPD_MIO_SEL_I2C1_SEL_WIDTH   1
#define LPD_IOU_SLCR_LPD_MIO_SEL_I2C1_SEL_MASK    0X00008000

#define LPD_IOU_SLCR_LPD_MIO_SEL_I2C0_SEL_SHIFT   14
#define LPD_IOU_SLCR_LPD_MIO_SEL_I2C0_SEL_WIDTH   1
#define LPD_IOU_SLCR_LPD_MIO_SEL_I2C0_SEL_MASK    0X00004000

#define LPD_IOU_SLCR_LPD_MIO_SEL_CAN1_SEL_SHIFT   13
#define LPD_IOU_SLCR_LPD_MIO_SEL_CAN1_SEL_WIDTH   1
#define LPD_IOU_SLCR_LPD_MIO_SEL_CAN1_SEL_MASK    0X00002000

#define LPD_IOU_SLCR_LPD_MIO_SEL_CAN0_SEL_SHIFT   12
#define LPD_IOU_SLCR_LPD_MIO_SEL_CAN0_SEL_WIDTH   1
#define LPD_IOU_SLCR_LPD_MIO_SEL_CAN0_SEL_MASK    0X00001000

#define LPD_IOU_SLCR_LPD_MIO_SEL_UART1_SEL_SHIFT   11
#define LPD_IOU_SLCR_LPD_MIO_SEL_UART1_SEL_WIDTH   1
#define LPD_IOU_SLCR_LPD_MIO_SEL_UART1_SEL_MASK    0X00000800

#define LPD_IOU_SLCR_LPD_MIO_SEL_UART0_SEL_SHIFT   10
#define LPD_IOU_SLCR_LPD_MIO_SEL_UART0_SEL_WIDTH   1
#define LPD_IOU_SLCR_LPD_MIO_SEL_UART0_SEL_MASK    0X00000400

#define LPD_IOU_SLCR_LPD_MIO_SEL_TTC3_SEL_SHIFT   9
#define LPD_IOU_SLCR_LPD_MIO_SEL_TTC3_SEL_WIDTH   1
#define LPD_IOU_SLCR_LPD_MIO_SEL_TTC3_SEL_MASK    0X00000200

#define LPD_IOU_SLCR_LPD_MIO_SEL_TTC2_SEL_SHIFT   8
#define LPD_IOU_SLCR_LPD_MIO_SEL_TTC2_SEL_WIDTH   1
#define LPD_IOU_SLCR_LPD_MIO_SEL_TTC2_SEL_MASK    0X00000100

#define LPD_IOU_SLCR_LPD_MIO_SEL_TTC1_SEL_SHIFT   7
#define LPD_IOU_SLCR_LPD_MIO_SEL_TTC1_SEL_WIDTH   1
#define LPD_IOU_SLCR_LPD_MIO_SEL_TTC1_SEL_MASK    0X00000080

#define LPD_IOU_SLCR_LPD_MIO_SEL_TTC0_SEL_SHIFT   6
#define LPD_IOU_SLCR_LPD_MIO_SEL_TTC0_SEL_WIDTH   1
#define LPD_IOU_SLCR_LPD_MIO_SEL_TTC0_SEL_MASK    0X00000040

#define LPD_IOU_SLCR_LPD_MIO_SEL_SPI1_SEL_SHIFT   5
#define LPD_IOU_SLCR_LPD_MIO_SEL_SPI1_SEL_WIDTH   1
#define LPD_IOU_SLCR_LPD_MIO_SEL_SPI1_SEL_MASK    0X00000020

#define LPD_IOU_SLCR_LPD_MIO_SEL_SPI0_SEL_SHIFT   4
#define LPD_IOU_SLCR_LPD_MIO_SEL_SPI0_SEL_WIDTH   1
#define LPD_IOU_SLCR_LPD_MIO_SEL_SPI0_SEL_MASK    0X00000010

#define LPD_IOU_SLCR_LPD_MIO_SEL_GEM1_MDIO_SEL_SHIFT   3
#define LPD_IOU_SLCR_LPD_MIO_SEL_GEM1_MDIO_SEL_WIDTH   1
#define LPD_IOU_SLCR_LPD_MIO_SEL_GEM1_MDIO_SEL_MASK    0X00000008

#define LPD_IOU_SLCR_LPD_MIO_SEL_GEM1RGMII_SEL_SHIFT   2
#define LPD_IOU_SLCR_LPD_MIO_SEL_GEM1RGMII_SEL_WIDTH   1
#define LPD_IOU_SLCR_LPD_MIO_SEL_GEM1RGMII_SEL_MASK    0X00000004

#define LPD_IOU_SLCR_LPD_MIO_SEL_GEM0_MDIO_SEL_SHIFT   1
#define LPD_IOU_SLCR_LPD_MIO_SEL_GEM0_MDIO_SEL_WIDTH   1
#define LPD_IOU_SLCR_LPD_MIO_SEL_GEM0_MDIO_SEL_MASK    0X00000002

#define LPD_IOU_SLCR_LPD_MIO_SEL_GEM0RGMII_SEL_SHIFT   0
#define LPD_IOU_SLCR_LPD_MIO_SEL_GEM0RGMII_SEL_WIDTH   1
#define LPD_IOU_SLCR_LPD_MIO_SEL_GEM0RGMII_SEL_MASK    0X00000001

/**
 * Register: LPD_IOU_SLCR_USB_IOU_INTERCONNECT_ROUTE
 */
#define LPD_IOU_SLCR_USB_IOU_INTERCONNECT_ROUTE    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000428 )

#define LPD_IOU_SLCR_USB_IOU_INTERCONNECT_ROUTE_USB_SHIFT   0
#define LPD_IOU_SLCR_USB_IOU_INTERCONNECT_ROUTE_USB_WIDTH   1
#define LPD_IOU_SLCR_USB_IOU_INTERCONNECT_ROUTE_USB_MASK    0X00000001

/**
 * Register: LPD_IOU_SLCR_USB_IOU_INTERCONNECT_QOS
 */
#define LPD_IOU_SLCR_USB_IOU_INTERCONNECT_QOS    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X0000042C )

#define LPD_IOU_SLCR_USB_IOU_INTERCONNECT_QOS_USB_QOS_SHIFT   0
#define LPD_IOU_SLCR_USB_IOU_INTERCONNECT_QOS_USB_QOS_WIDTH   4
#define LPD_IOU_SLCR_USB_IOU_INTERCONNECT_QOS_USB_QOS_MASK    0X0000000F

/**
 * Register: LPD_IOU_SLCR_SMID_FOR_USB
 */
#define LPD_IOU_SLCR_SMID_FOR_USB    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000430 )

#define LPD_IOU_SLCR_SMID_FOR_USB_SMID_CONFIG_USB_SHIFT   0
#define LPD_IOU_SLCR_SMID_FOR_USB_SMID_CONFIG_USB_WIDTH   1
#define LPD_IOU_SLCR_SMID_FOR_USB_SMID_CONFIG_USB_MASK    0X00000001

/**
 * Register: LPD_IOU_SLCR_CTRL
 */
#define LPD_IOU_SLCR_CTRL    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000600 )

#define LPD_IOU_SLCR_CTRL_SLVERR_ENABLE_SHIFT   0
#define LPD_IOU_SLCR_CTRL_SLVERR_ENABLE_WIDTH   1
#define LPD_IOU_SLCR_CTRL_SLVERR_ENABLE_MASK    0X00000001

/**
 * Register: LPD_IOU_SLCR_ISR
 */
#define LPD_IOU_SLCR_ISR    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000700 )

#define LPD_IOU_SLCR_ISR_ADDR_DECODE_ERR_SHIFT   0
#define LPD_IOU_SLCR_ISR_ADDR_DECODE_ERR_WIDTH   1
#define LPD_IOU_SLCR_ISR_ADDR_DECODE_ERR_MASK    0X00000001

/**
 * Register: LPD_IOU_SLCR_IMR
 */
#define LPD_IOU_SLCR_IMR    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000704 )

#define LPD_IOU_SLCR_IMR_ADDR_DECODE_ERR_SHIFT   0
#define LPD_IOU_SLCR_IMR_ADDR_DECODE_ERR_WIDTH   1
#define LPD_IOU_SLCR_IMR_ADDR_DECODE_ERR_MASK    0X00000001

/**
 * Register: LPD_IOU_SLCR_IER
 */
#define LPD_IOU_SLCR_IER    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000708 )

#define LPD_IOU_SLCR_IER_ADDR_DECODE_ERR_SHIFT   0
#define LPD_IOU_SLCR_IER_ADDR_DECODE_ERR_WIDTH   1
#define LPD_IOU_SLCR_IER_ADDR_DECODE_ERR_MASK    0X00000001

/**
 * Register: LPD_IOU_SLCR_IDR
 */
#define LPD_IOU_SLCR_IDR    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X0000070C )

#define LPD_IOU_SLCR_IDR_ADDR_DECODE_ERR_SHIFT   0
#define LPD_IOU_SLCR_IDR_ADDR_DECODE_ERR_WIDTH   1
#define LPD_IOU_SLCR_IDR_ADDR_DECODE_ERR_MASK    0X00000001

/**
 * Register: LPD_IOU_SLCR_ITR
 */
#define LPD_IOU_SLCR_ITR    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000710 )

#define LPD_IOU_SLCR_ITR_ADDR_DECODE_ERR_SHIFT   0
#define LPD_IOU_SLCR_ITR_ADDR_DECODE_ERR_WIDTH   1
#define LPD_IOU_SLCR_ITR_ADDR_DECODE_ERR_MASK    0X00000001

/**
 * Register: LPD_IOU_SLCR_PARITY_ISR
 */
#define LPD_IOU_SLCR_PARITY_ISR    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000714 )

#define LPD_IOU_SLCR_PARITY_ISR_PERR_WWDT0_APB_SHIFT   24
#define LPD_IOU_SLCR_PARITY_ISR_PERR_WWDT0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ISR_PERR_WWDT0_APB_MASK    0X01000000

#define LPD_IOU_SLCR_PARITY_ISR_PERR_USB_XS_SHIFT   23
#define LPD_IOU_SLCR_PARITY_ISR_PERR_USB_XS_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ISR_PERR_USB_XS_MASK    0X00800000

#define LPD_IOU_SLCR_PARITY_ISR_PERR_USB_XM_IOU_SHIFT   22
#define LPD_IOU_SLCR_PARITY_ISR_PERR_USB_XM_IOU_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ISR_PERR_USB_XM_IOU_MASK    0X00400000

#define LPD_IOU_SLCR_PARITY_ISR_PERR_USB_APB_SHIFT   21
#define LPD_IOU_SLCR_PARITY_ISR_PERR_USB_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ISR_PERR_USB_APB_MASK    0X00200000

#define LPD_IOU_SLCR_PARITY_ISR_PERR_UART1_APB_SHIFT   20
#define LPD_IOU_SLCR_PARITY_ISR_PERR_UART1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ISR_PERR_UART1_APB_MASK    0X00100000

#define LPD_IOU_SLCR_PARITY_ISR_PERR_UART0_APB_SHIFT   19
#define LPD_IOU_SLCR_PARITY_ISR_PERR_UART0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ISR_PERR_UART0_APB_MASK    0X00080000

#define LPD_IOU_SLCR_PARITY_ISR_PERR_TTC3_APB_SHIFT   18
#define LPD_IOU_SLCR_PARITY_ISR_PERR_TTC3_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ISR_PERR_TTC3_APB_MASK    0X00040000

#define LPD_IOU_SLCR_PARITY_ISR_PERR_TTC2_APB_SHIFT   17
#define LPD_IOU_SLCR_PARITY_ISR_PERR_TTC2_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ISR_PERR_TTC2_APB_MASK    0X00020000

#define LPD_IOU_SLCR_PARITY_ISR_PERR_TTC1_APB_SHIFT   16
#define LPD_IOU_SLCR_PARITY_ISR_PERR_TTC1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ISR_PERR_TTC1_APB_MASK    0X00010000

#define LPD_IOU_SLCR_PARITY_ISR_PERR_TTC0_APB_SHIFT   15
#define LPD_IOU_SLCR_PARITY_ISR_PERR_TTC0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ISR_PERR_TTC0_APB_MASK    0X00008000

#define LPD_IOU_SLCR_PARITY_ISR_PERR_SPI1_APB_SHIFT   14
#define LPD_IOU_SLCR_PARITY_ISR_PERR_SPI1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ISR_PERR_SPI1_APB_MASK    0X00004000

#define LPD_IOU_SLCR_PARITY_ISR_PERR_IOU_SPI0_APB_SHIFT   13
#define LPD_IOU_SLCR_PARITY_ISR_PERR_IOU_SPI0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ISR_PERR_IOU_SPI0_APB_MASK    0X00002000

#define LPD_IOU_SLCR_PARITY_ISR_PERR_SCNTR2_APB_SHIFT   12
#define LPD_IOU_SLCR_PARITY_ISR_PERR_SCNTR2_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ISR_PERR_SCNTR2_APB_MASK    0X00001000

#define LPD_IOU_SLCR_PARITY_ISR_PERR_SCNTR1_APB_SHIFT   11
#define LPD_IOU_SLCR_PARITY_ISR_PERR_SCNTR1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ISR_PERR_SCNTR1_APB_MASK    0X00000800

#define LPD_IOU_SLCR_PARITY_ISR_PERR_IOUSLCR_SECURE_APB_SHIFT   10
#define LPD_IOU_SLCR_PARITY_ISR_PERR_IOUSLCR_SECURE_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ISR_PERR_IOUSLCR_SECURE_APB_MASK    0X00000400

#define LPD_IOU_SLCR_PARITY_ISR_PERR_IOUSLCR_APB_SHIFT   9
#define LPD_IOU_SLCR_PARITY_ISR_PERR_IOUSLCR_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ISR_PERR_IOUSLCR_APB_MASK    0X00000200

#define LPD_IOU_SLCR_PARITY_ISR_PERR_IOU_GEM1_APB_SHIFT   8
#define LPD_IOU_SLCR_PARITY_ISR_PERR_IOU_GEM1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ISR_PERR_IOU_GEM1_APB_MASK    0X00000100

#define LPD_IOU_SLCR_PARITY_ISR_PERR_IOU_GEM0_APB_SHIFT   7
#define LPD_IOU_SLCR_PARITY_ISR_PERR_IOU_GEM0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ISR_PERR_IOU_GEM0_APB_MASK    0X00000080

#define LPD_IOU_SLCR_PARITY_ISR_PERR_I2C1_APB_SHIFT   6
#define LPD_IOU_SLCR_PARITY_ISR_PERR_I2C1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ISR_PERR_I2C1_APB_MASK    0X00000040

#define LPD_IOU_SLCR_PARITY_ISR_PERR_I2C0_APB_SHIFT   5
#define LPD_IOU_SLCR_PARITY_ISR_PERR_I2C0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ISR_PERR_I2C0_APB_MASK    0X00000020

#define LPD_IOU_SLCR_PARITY_ISR_PERR_GPIO_APB_SHIFT   4
#define LPD_IOU_SLCR_PARITY_ISR_PERR_GPIO_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ISR_PERR_GPIO_APB_MASK    0X00000010

#define LPD_IOU_SLCR_PARITY_ISR_PERR_GEM1_IOU_SHIFT   3
#define LPD_IOU_SLCR_PARITY_ISR_PERR_GEM1_IOU_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ISR_PERR_GEM1_IOU_MASK    0X00000008

#define LPD_IOU_SLCR_PARITY_ISR_PERR_GEM0_IOU_SHIFT   2
#define LPD_IOU_SLCR_PARITY_ISR_PERR_GEM0_IOU_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ISR_PERR_GEM0_IOU_MASK    0X00000004

#define LPD_IOU_SLCR_PARITY_ISR_PERR_CAN1_APB_SHIFT   1
#define LPD_IOU_SLCR_PARITY_ISR_PERR_CAN1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ISR_PERR_CAN1_APB_MASK    0X00000002

#define LPD_IOU_SLCR_PARITY_ISR_PERR_CAN0_APB_SHIFT   0
#define LPD_IOU_SLCR_PARITY_ISR_PERR_CAN0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ISR_PERR_CAN0_APB_MASK    0X00000001

/**
 * Register: LPD_IOU_SLCR_PARITY_IMR
 */
#define LPD_IOU_SLCR_PARITY_IMR    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000718 )

#define LPD_IOU_SLCR_PARITY_IMR_PERR_WWDT0_APB_SHIFT   24
#define LPD_IOU_SLCR_PARITY_IMR_PERR_WWDT0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IMR_PERR_WWDT0_APB_MASK    0X01000000

#define LPD_IOU_SLCR_PARITY_IMR_PERR_USB_XS_SHIFT   23
#define LPD_IOU_SLCR_PARITY_IMR_PERR_USB_XS_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IMR_PERR_USB_XS_MASK    0X00800000

#define LPD_IOU_SLCR_PARITY_IMR_PERR_USB_XM_IOU_SHIFT   22
#define LPD_IOU_SLCR_PARITY_IMR_PERR_USB_XM_IOU_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IMR_PERR_USB_XM_IOU_MASK    0X00400000

#define LPD_IOU_SLCR_PARITY_IMR_PERR_USB_APB_SHIFT   21
#define LPD_IOU_SLCR_PARITY_IMR_PERR_USB_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IMR_PERR_USB_APB_MASK    0X00200000

#define LPD_IOU_SLCR_PARITY_IMR_PERR_UART1_APB_SHIFT   20
#define LPD_IOU_SLCR_PARITY_IMR_PERR_UART1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IMR_PERR_UART1_APB_MASK    0X00100000

#define LPD_IOU_SLCR_PARITY_IMR_PERR_UART0_APB_SHIFT   19
#define LPD_IOU_SLCR_PARITY_IMR_PERR_UART0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IMR_PERR_UART0_APB_MASK    0X00080000

#define LPD_IOU_SLCR_PARITY_IMR_PERR_TTC3_APB_SHIFT   18
#define LPD_IOU_SLCR_PARITY_IMR_PERR_TTC3_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IMR_PERR_TTC3_APB_MASK    0X00040000

#define LPD_IOU_SLCR_PARITY_IMR_PERR_TTC2_APB_SHIFT   17
#define LPD_IOU_SLCR_PARITY_IMR_PERR_TTC2_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IMR_PERR_TTC2_APB_MASK    0X00020000

#define LPD_IOU_SLCR_PARITY_IMR_PERR_TTC1_APB_SHIFT   16
#define LPD_IOU_SLCR_PARITY_IMR_PERR_TTC1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IMR_PERR_TTC1_APB_MASK    0X00010000

#define LPD_IOU_SLCR_PARITY_IMR_PERR_TTC0_APB_SHIFT   15
#define LPD_IOU_SLCR_PARITY_IMR_PERR_TTC0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IMR_PERR_TTC0_APB_MASK    0X00008000

#define LPD_IOU_SLCR_PARITY_IMR_PERR_SPI1_APB_SHIFT   14
#define LPD_IOU_SLCR_PARITY_IMR_PERR_SPI1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IMR_PERR_SPI1_APB_MASK    0X00004000

#define LPD_IOU_SLCR_PARITY_IMR_PERR_IOU_SPI0_APB_SHIFT   13
#define LPD_IOU_SLCR_PARITY_IMR_PERR_IOU_SPI0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IMR_PERR_IOU_SPI0_APB_MASK    0X00002000

#define LPD_IOU_SLCR_PARITY_IMR_PERR_SCNTR2_APB_SHIFT   12
#define LPD_IOU_SLCR_PARITY_IMR_PERR_SCNTR2_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IMR_PERR_SCNTR2_APB_MASK    0X00001000

#define LPD_IOU_SLCR_PARITY_IMR_PERR_SCNTR1_APB_SHIFT   11
#define LPD_IOU_SLCR_PARITY_IMR_PERR_SCNTR1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IMR_PERR_SCNTR1_APB_MASK    0X00000800

#define LPD_IOU_SLCR_PARITY_IMR_PERR_IOUSLCR_SECURE_APB_SHIFT   10
#define LPD_IOU_SLCR_PARITY_IMR_PERR_IOUSLCR_SECURE_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IMR_PERR_IOUSLCR_SECURE_APB_MASK    0X00000400

#define LPD_IOU_SLCR_PARITY_IMR_PERR_IOUSLCR_APB_SHIFT   9
#define LPD_IOU_SLCR_PARITY_IMR_PERR_IOUSLCR_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IMR_PERR_IOUSLCR_APB_MASK    0X00000200

#define LPD_IOU_SLCR_PARITY_IMR_PERR_IOU_GEM1_APB_SHIFT   8
#define LPD_IOU_SLCR_PARITY_IMR_PERR_IOU_GEM1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IMR_PERR_IOU_GEM1_APB_MASK    0X00000100

#define LPD_IOU_SLCR_PARITY_IMR_PERR_IOU_GEM0_APB_SHIFT   7
#define LPD_IOU_SLCR_PARITY_IMR_PERR_IOU_GEM0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IMR_PERR_IOU_GEM0_APB_MASK    0X00000080

#define LPD_IOU_SLCR_PARITY_IMR_PERR_I2C1_APB_SHIFT   6
#define LPD_IOU_SLCR_PARITY_IMR_PERR_I2C1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IMR_PERR_I2C1_APB_MASK    0X00000040

#define LPD_IOU_SLCR_PARITY_IMR_PERR_I2C0_APB_SHIFT   5
#define LPD_IOU_SLCR_PARITY_IMR_PERR_I2C0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IMR_PERR_I2C0_APB_MASK    0X00000020

#define LPD_IOU_SLCR_PARITY_IMR_PERR_GPIO_APB_SHIFT   4
#define LPD_IOU_SLCR_PARITY_IMR_PERR_GPIO_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IMR_PERR_GPIO_APB_MASK    0X00000010

#define LPD_IOU_SLCR_PARITY_IMR_PERR_GEM1_IOU_SHIFT   3
#define LPD_IOU_SLCR_PARITY_IMR_PERR_GEM1_IOU_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IMR_PERR_GEM1_IOU_MASK    0X00000008

#define LPD_IOU_SLCR_PARITY_IMR_PERR_GEM0_IOU_SHIFT   2
#define LPD_IOU_SLCR_PARITY_IMR_PERR_GEM0_IOU_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IMR_PERR_GEM0_IOU_MASK    0X00000004

#define LPD_IOU_SLCR_PARITY_IMR_PERR_CAN1_APB_SHIFT   1
#define LPD_IOU_SLCR_PARITY_IMR_PERR_CAN1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IMR_PERR_CAN1_APB_MASK    0X00000002

#define LPD_IOU_SLCR_PARITY_IMR_PERR_CAN0_APB_SHIFT   0
#define LPD_IOU_SLCR_PARITY_IMR_PERR_CAN0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IMR_PERR_CAN0_APB_MASK    0X00000001

/**
 * Register: LPD_IOU_SLCR_PARITY_IER
 */
#define LPD_IOU_SLCR_PARITY_IER    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X0000071C )

#define LPD_IOU_SLCR_PARITY_IER_PERR_WWDT0_APB_SHIFT   24
#define LPD_IOU_SLCR_PARITY_IER_PERR_WWDT0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IER_PERR_WWDT0_APB_MASK    0X01000000

#define LPD_IOU_SLCR_PARITY_IER_PERR_USB_XS_SHIFT   23
#define LPD_IOU_SLCR_PARITY_IER_PERR_USB_XS_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IER_PERR_USB_XS_MASK    0X00800000

#define LPD_IOU_SLCR_PARITY_IER_PERR_USB_XM_IOU_SHIFT   22
#define LPD_IOU_SLCR_PARITY_IER_PERR_USB_XM_IOU_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IER_PERR_USB_XM_IOU_MASK    0X00400000

#define LPD_IOU_SLCR_PARITY_IER_PERR_USB_APB_SHIFT   21
#define LPD_IOU_SLCR_PARITY_IER_PERR_USB_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IER_PERR_USB_APB_MASK    0X00200000

#define LPD_IOU_SLCR_PARITY_IER_PERR_UART1_APB_SHIFT   20
#define LPD_IOU_SLCR_PARITY_IER_PERR_UART1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IER_PERR_UART1_APB_MASK    0X00100000

#define LPD_IOU_SLCR_PARITY_IER_PERR_UART0_APB_SHIFT   19
#define LPD_IOU_SLCR_PARITY_IER_PERR_UART0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IER_PERR_UART0_APB_MASK    0X00080000

#define LPD_IOU_SLCR_PARITY_IER_PERR_TTC3_APB_SHIFT   18
#define LPD_IOU_SLCR_PARITY_IER_PERR_TTC3_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IER_PERR_TTC3_APB_MASK    0X00040000

#define LPD_IOU_SLCR_PARITY_IER_PERR_TTC2_APB_SHIFT   17
#define LPD_IOU_SLCR_PARITY_IER_PERR_TTC2_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IER_PERR_TTC2_APB_MASK    0X00020000

#define LPD_IOU_SLCR_PARITY_IER_PERR_TTC1_APB_SHIFT   16
#define LPD_IOU_SLCR_PARITY_IER_PERR_TTC1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IER_PERR_TTC1_APB_MASK    0X00010000

#define LPD_IOU_SLCR_PARITY_IER_PERR_TTC0_APB_SHIFT   15
#define LPD_IOU_SLCR_PARITY_IER_PERR_TTC0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IER_PERR_TTC0_APB_MASK    0X00008000

#define LPD_IOU_SLCR_PARITY_IER_PERR_SPI1_APB_SHIFT   14
#define LPD_IOU_SLCR_PARITY_IER_PERR_SPI1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IER_PERR_SPI1_APB_MASK    0X00004000

#define LPD_IOU_SLCR_PARITY_IER_PERR_IOU_SPI0_APB_SHIFT   13
#define LPD_IOU_SLCR_PARITY_IER_PERR_IOU_SPI0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IER_PERR_IOU_SPI0_APB_MASK    0X00002000

#define LPD_IOU_SLCR_PARITY_IER_PERR_SCNTR2_APB_SHIFT   12
#define LPD_IOU_SLCR_PARITY_IER_PERR_SCNTR2_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IER_PERR_SCNTR2_APB_MASK    0X00001000

#define LPD_IOU_SLCR_PARITY_IER_PERR_SCNTR1_APB_SHIFT   11
#define LPD_IOU_SLCR_PARITY_IER_PERR_SCNTR1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IER_PERR_SCNTR1_APB_MASK    0X00000800

#define LPD_IOU_SLCR_PARITY_IER_PERR_IOUSLCR_SECURE_APB_SHIFT   10
#define LPD_IOU_SLCR_PARITY_IER_PERR_IOUSLCR_SECURE_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IER_PERR_IOUSLCR_SECURE_APB_MASK    0X00000400

#define LPD_IOU_SLCR_PARITY_IER_PERR_IOUSLCR_APB_SHIFT   9
#define LPD_IOU_SLCR_PARITY_IER_PERR_IOUSLCR_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IER_PERR_IOUSLCR_APB_MASK    0X00000200

#define LPD_IOU_SLCR_PARITY_IER_PERR_IOU_GEM1_APB_SHIFT   8
#define LPD_IOU_SLCR_PARITY_IER_PERR_IOU_GEM1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IER_PERR_IOU_GEM1_APB_MASK    0X00000100

#define LPD_IOU_SLCR_PARITY_IER_PERR_IOU_GEM0_APB_SHIFT   7
#define LPD_IOU_SLCR_PARITY_IER_PERR_IOU_GEM0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IER_PERR_IOU_GEM0_APB_MASK    0X00000080

#define LPD_IOU_SLCR_PARITY_IER_PERR_I2C1_APB_SHIFT   6
#define LPD_IOU_SLCR_PARITY_IER_PERR_I2C1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IER_PERR_I2C1_APB_MASK    0X00000040

#define LPD_IOU_SLCR_PARITY_IER_PERR_I2C0_APB_SHIFT   5
#define LPD_IOU_SLCR_PARITY_IER_PERR_I2C0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IER_PERR_I2C0_APB_MASK    0X00000020

#define LPD_IOU_SLCR_PARITY_IER_PERR_GPIO_APB_SHIFT   4
#define LPD_IOU_SLCR_PARITY_IER_PERR_GPIO_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IER_PERR_GPIO_APB_MASK    0X00000010

#define LPD_IOU_SLCR_PARITY_IER_PERR_GEM1_IOU_SHIFT   3
#define LPD_IOU_SLCR_PARITY_IER_PERR_GEM1_IOU_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IER_PERR_GEM1_IOU_MASK    0X00000008

#define LPD_IOU_SLCR_PARITY_IER_PERR_GEM0_IOU_SHIFT   2
#define LPD_IOU_SLCR_PARITY_IER_PERR_GEM0_IOU_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IER_PERR_GEM0_IOU_MASK    0X00000004

#define LPD_IOU_SLCR_PARITY_IER_PERR_CAN1_APB_SHIFT   1
#define LPD_IOU_SLCR_PARITY_IER_PERR_CAN1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IER_PERR_CAN1_APB_MASK    0X00000002

#define LPD_IOU_SLCR_PARITY_IER_PERR_CAN0_APB_SHIFT   0
#define LPD_IOU_SLCR_PARITY_IER_PERR_CAN0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IER_PERR_CAN0_APB_MASK    0X00000001

/**
 * Register: LPD_IOU_SLCR_PARITY_IDR
 */
#define LPD_IOU_SLCR_PARITY_IDR    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000720 )

#define LPD_IOU_SLCR_PARITY_IDR_PERR_WWDT0_APB_SHIFT   24
#define LPD_IOU_SLCR_PARITY_IDR_PERR_WWDT0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IDR_PERR_WWDT0_APB_MASK    0X01000000

#define LPD_IOU_SLCR_PARITY_IDR_PERR_USB_XS_SHIFT   23
#define LPD_IOU_SLCR_PARITY_IDR_PERR_USB_XS_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IDR_PERR_USB_XS_MASK    0X00800000

#define LPD_IOU_SLCR_PARITY_IDR_PERR_USB_XM_IOU_SHIFT   22
#define LPD_IOU_SLCR_PARITY_IDR_PERR_USB_XM_IOU_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IDR_PERR_USB_XM_IOU_MASK    0X00400000

#define LPD_IOU_SLCR_PARITY_IDR_PERR_USB_APB_SHIFT   21
#define LPD_IOU_SLCR_PARITY_IDR_PERR_USB_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IDR_PERR_USB_APB_MASK    0X00200000

#define LPD_IOU_SLCR_PARITY_IDR_PERR_UART1_APB_SHIFT   20
#define LPD_IOU_SLCR_PARITY_IDR_PERR_UART1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IDR_PERR_UART1_APB_MASK    0X00100000

#define LPD_IOU_SLCR_PARITY_IDR_PERR_UART0_APB_SHIFT   19
#define LPD_IOU_SLCR_PARITY_IDR_PERR_UART0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IDR_PERR_UART0_APB_MASK    0X00080000

#define LPD_IOU_SLCR_PARITY_IDR_PERR_TTC3_APB_SHIFT   18
#define LPD_IOU_SLCR_PARITY_IDR_PERR_TTC3_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IDR_PERR_TTC3_APB_MASK    0X00040000

#define LPD_IOU_SLCR_PARITY_IDR_PERR_TTC2_APB_SHIFT   17
#define LPD_IOU_SLCR_PARITY_IDR_PERR_TTC2_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IDR_PERR_TTC2_APB_MASK    0X00020000

#define LPD_IOU_SLCR_PARITY_IDR_PERR_TTC1_APB_SHIFT   16
#define LPD_IOU_SLCR_PARITY_IDR_PERR_TTC1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IDR_PERR_TTC1_APB_MASK    0X00010000

#define LPD_IOU_SLCR_PARITY_IDR_PERR_TTC0_APB_SHIFT   15
#define LPD_IOU_SLCR_PARITY_IDR_PERR_TTC0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IDR_PERR_TTC0_APB_MASK    0X00008000

#define LPD_IOU_SLCR_PARITY_IDR_PERR_SPI1_APB_SHIFT   14
#define LPD_IOU_SLCR_PARITY_IDR_PERR_SPI1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IDR_PERR_SPI1_APB_MASK    0X00004000

#define LPD_IOU_SLCR_PARITY_IDR_PERR_IOU_SPI0_APB_SHIFT   13
#define LPD_IOU_SLCR_PARITY_IDR_PERR_IOU_SPI0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IDR_PERR_IOU_SPI0_APB_MASK    0X00002000

#define LPD_IOU_SLCR_PARITY_IDR_PERR_SCNTR2_APB_SHIFT   12
#define LPD_IOU_SLCR_PARITY_IDR_PERR_SCNTR2_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IDR_PERR_SCNTR2_APB_MASK    0X00001000

#define LPD_IOU_SLCR_PARITY_IDR_PERR_SCNTR1_APB_SHIFT   11
#define LPD_IOU_SLCR_PARITY_IDR_PERR_SCNTR1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IDR_PERR_SCNTR1_APB_MASK    0X00000800

#define LPD_IOU_SLCR_PARITY_IDR_PERR_IOUSLCR_SECURE_APB_SHIFT   10
#define LPD_IOU_SLCR_PARITY_IDR_PERR_IOUSLCR_SECURE_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IDR_PERR_IOUSLCR_SECURE_APB_MASK    0X00000400

#define LPD_IOU_SLCR_PARITY_IDR_PERR_IOUSLCR_APB_SHIFT   9
#define LPD_IOU_SLCR_PARITY_IDR_PERR_IOUSLCR_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IDR_PERR_IOUSLCR_APB_MASK    0X00000200

#define LPD_IOU_SLCR_PARITY_IDR_PERR_IOU_GEM1_APB_SHIFT   8
#define LPD_IOU_SLCR_PARITY_IDR_PERR_IOU_GEM1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IDR_PERR_IOU_GEM1_APB_MASK    0X00000100

#define LPD_IOU_SLCR_PARITY_IDR_PERR_IOU_GEM0_APB_SHIFT   7
#define LPD_IOU_SLCR_PARITY_IDR_PERR_IOU_GEM0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IDR_PERR_IOU_GEM0_APB_MASK    0X00000080

#define LPD_IOU_SLCR_PARITY_IDR_PERR_I2C1_APB_SHIFT   6
#define LPD_IOU_SLCR_PARITY_IDR_PERR_I2C1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IDR_PERR_I2C1_APB_MASK    0X00000040

#define LPD_IOU_SLCR_PARITY_IDR_PERR_I2C0_APB_SHIFT   5
#define LPD_IOU_SLCR_PARITY_IDR_PERR_I2C0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IDR_PERR_I2C0_APB_MASK    0X00000020

#define LPD_IOU_SLCR_PARITY_IDR_PERR_GPIO_APB_SHIFT   4
#define LPD_IOU_SLCR_PARITY_IDR_PERR_GPIO_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IDR_PERR_GPIO_APB_MASK    0X00000010

#define LPD_IOU_SLCR_PARITY_IDR_PERR_GEM1_IOU_SHIFT   3
#define LPD_IOU_SLCR_PARITY_IDR_PERR_GEM1_IOU_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IDR_PERR_GEM1_IOU_MASK    0X00000008

#define LPD_IOU_SLCR_PARITY_IDR_PERR_GEM0_IOU_SHIFT   2
#define LPD_IOU_SLCR_PARITY_IDR_PERR_GEM0_IOU_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IDR_PERR_GEM0_IOU_MASK    0X00000004

#define LPD_IOU_SLCR_PARITY_IDR_PERR_CAN1_APB_SHIFT   1
#define LPD_IOU_SLCR_PARITY_IDR_PERR_CAN1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IDR_PERR_CAN1_APB_MASK    0X00000002

#define LPD_IOU_SLCR_PARITY_IDR_PERR_CAN0_APB_SHIFT   0
#define LPD_IOU_SLCR_PARITY_IDR_PERR_CAN0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_IDR_PERR_CAN0_APB_MASK    0X00000001

/**
 * Register: LPD_IOU_SLCR_PARITY_ITR
 */
#define LPD_IOU_SLCR_PARITY_ITR    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000724 )

#define LPD_IOU_SLCR_PARITY_ITR_PERR_WWDT0_APB_SHIFT   24
#define LPD_IOU_SLCR_PARITY_ITR_PERR_WWDT0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ITR_PERR_WWDT0_APB_MASK    0X01000000

#define LPD_IOU_SLCR_PARITY_ITR_PERR_USB_XS_SHIFT   23
#define LPD_IOU_SLCR_PARITY_ITR_PERR_USB_XS_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ITR_PERR_USB_XS_MASK    0X00800000

#define LPD_IOU_SLCR_PARITY_ITR_PERR_USB_XM_IOU_SHIFT   22
#define LPD_IOU_SLCR_PARITY_ITR_PERR_USB_XM_IOU_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ITR_PERR_USB_XM_IOU_MASK    0X00400000

#define LPD_IOU_SLCR_PARITY_ITR_PERR_USB_APB_SHIFT   21
#define LPD_IOU_SLCR_PARITY_ITR_PERR_USB_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ITR_PERR_USB_APB_MASK    0X00200000

#define LPD_IOU_SLCR_PARITY_ITR_PERR_UART1_APB_SHIFT   20
#define LPD_IOU_SLCR_PARITY_ITR_PERR_UART1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ITR_PERR_UART1_APB_MASK    0X00100000

#define LPD_IOU_SLCR_PARITY_ITR_PERR_UART0_APB_SHIFT   19
#define LPD_IOU_SLCR_PARITY_ITR_PERR_UART0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ITR_PERR_UART0_APB_MASK    0X00080000

#define LPD_IOU_SLCR_PARITY_ITR_PERR_TTC3_APB_SHIFT   18
#define LPD_IOU_SLCR_PARITY_ITR_PERR_TTC3_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ITR_PERR_TTC3_APB_MASK    0X00040000

#define LPD_IOU_SLCR_PARITY_ITR_PERR_TTC2_APB_SHIFT   17
#define LPD_IOU_SLCR_PARITY_ITR_PERR_TTC2_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ITR_PERR_TTC2_APB_MASK    0X00020000

#define LPD_IOU_SLCR_PARITY_ITR_PERR_TTC1_APB_SHIFT   16
#define LPD_IOU_SLCR_PARITY_ITR_PERR_TTC1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ITR_PERR_TTC1_APB_MASK    0X00010000

#define LPD_IOU_SLCR_PARITY_ITR_PERR_TTC0_APB_SHIFT   15
#define LPD_IOU_SLCR_PARITY_ITR_PERR_TTC0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ITR_PERR_TTC0_APB_MASK    0X00008000

#define LPD_IOU_SLCR_PARITY_ITR_PERR_SPI1_APB_SHIFT   14
#define LPD_IOU_SLCR_PARITY_ITR_PERR_SPI1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ITR_PERR_SPI1_APB_MASK    0X00004000

#define LPD_IOU_SLCR_PARITY_ITR_PERR_IOU_SPI0_APB_SHIFT   13
#define LPD_IOU_SLCR_PARITY_ITR_PERR_IOU_SPI0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ITR_PERR_IOU_SPI0_APB_MASK    0X00002000

#define LPD_IOU_SLCR_PARITY_ITR_PERR_SCNTR2_APB_SHIFT   12
#define LPD_IOU_SLCR_PARITY_ITR_PERR_SCNTR2_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ITR_PERR_SCNTR2_APB_MASK    0X00001000

#define LPD_IOU_SLCR_PARITY_ITR_PERR_SCNTR1_APB_SHIFT   11
#define LPD_IOU_SLCR_PARITY_ITR_PERR_SCNTR1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ITR_PERR_SCNTR1_APB_MASK    0X00000800

#define LPD_IOU_SLCR_PARITY_ITR_PERR_IOUSLCR_SECURE_APB_SHIFT   10
#define LPD_IOU_SLCR_PARITY_ITR_PERR_IOUSLCR_SECURE_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ITR_PERR_IOUSLCR_SECURE_APB_MASK    0X00000400

#define LPD_IOU_SLCR_PARITY_ITR_PERR_IOUSLCR_APB_SHIFT   9
#define LPD_IOU_SLCR_PARITY_ITR_PERR_IOUSLCR_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ITR_PERR_IOUSLCR_APB_MASK    0X00000200

#define LPD_IOU_SLCR_PARITY_ITR_PERR_IOU_GEM1_APB_SHIFT   8
#define LPD_IOU_SLCR_PARITY_ITR_PERR_IOU_GEM1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ITR_PERR_IOU_GEM1_APB_MASK    0X00000100

#define LPD_IOU_SLCR_PARITY_ITR_PERR_IOU_GEM0_APB_SHIFT   7
#define LPD_IOU_SLCR_PARITY_ITR_PERR_IOU_GEM0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ITR_PERR_IOU_GEM0_APB_MASK    0X00000080

#define LPD_IOU_SLCR_PARITY_ITR_PERR_I2C1_APB_SHIFT   6
#define LPD_IOU_SLCR_PARITY_ITR_PERR_I2C1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ITR_PERR_I2C1_APB_MASK    0X00000040

#define LPD_IOU_SLCR_PARITY_ITR_PERR_I2C0_APB_SHIFT   5
#define LPD_IOU_SLCR_PARITY_ITR_PERR_I2C0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ITR_PERR_I2C0_APB_MASK    0X00000020

#define LPD_IOU_SLCR_PARITY_ITR_PERR_GPIO_APB_SHIFT   4
#define LPD_IOU_SLCR_PARITY_ITR_PERR_GPIO_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ITR_PERR_GPIO_APB_MASK    0X00000010

#define LPD_IOU_SLCR_PARITY_ITR_PERR_GEM1_IOU_SHIFT   3
#define LPD_IOU_SLCR_PARITY_ITR_PERR_GEM1_IOU_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ITR_PERR_GEM1_IOU_MASK    0X00000008

#define LPD_IOU_SLCR_PARITY_ITR_PERR_GEM0_IOU_SHIFT   2
#define LPD_IOU_SLCR_PARITY_ITR_PERR_GEM0_IOU_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ITR_PERR_GEM0_IOU_MASK    0X00000004

#define LPD_IOU_SLCR_PARITY_ITR_PERR_CAN1_APB_SHIFT   1
#define LPD_IOU_SLCR_PARITY_ITR_PERR_CAN1_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ITR_PERR_CAN1_APB_MASK    0X00000002

#define LPD_IOU_SLCR_PARITY_ITR_PERR_CAN0_APB_SHIFT   0
#define LPD_IOU_SLCR_PARITY_ITR_PERR_CAN0_APB_WIDTH   1
#define LPD_IOU_SLCR_PARITY_ITR_PERR_CAN0_APB_MASK    0X00000001

/**
 * Register: LPD_IOU_SLCR_WPROT0
 */
#define LPD_IOU_SLCR_WPROT0    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000728 )

#define LPD_IOU_SLCR_WPROT0_ACTIVE_SHIFT   0
#define LPD_IOU_SLCR_WPROT0_ACTIVE_WIDTH   1
#define LPD_IOU_SLCR_WPROT0_ACTIVE_MASK    0X00000001

/**
 * Register: LPD_IOU_SLCR_ECO
 */
#define LPD_IOU_SLCR_ECO    ( ( LPD_IOU_SLCR_BASEADDR ) + 0X00000730 )

#define LPD_IOU_SLCR_ECO_FIELD_SHIFT   0
#define LPD_IOU_SLCR_ECO_FIELD_WIDTH   32
#define LPD_IOU_SLCR_ECO_FIELD_MASK    0XFFFFFFFF

#ifdef __cplusplus
}
#endif


#endif /* _LPD_IOU_SLCR_H_ */
