hdcp22_rx
XHdcp22_Rx_Protocol
HDCP22 over HDMI.
XHdcp22_Rx_Mode
HDCP22 receiver.
XHdcp22_Rx_HandlerType
Undefined.
XHdcp22_Rx_StateType
Undefined.
XHdcp22_Rx_AuthenticationType
Unauthenticated.
XHdcp22_Rx_LogEvt
XHdcp22_Rx_TopologyField
XHdcp22_Rx_MessageIds
AKE_Init message ID.
XHdcp22_Rx_ErrorFlag
No errors.
XHdcp22_Rx_DdcFlag
Clear DDC flag.
XHdcp22_Rx_LogData
Reset event.
XHdcp22_Rx_TestFlags
No directed test.
XHdcp22_Rx_TestMode
Test mode disabled.
XHdcp22_Rx_TestDdcAccess
Write-Only.
XHdcp22_Rx_TestState
typedef void*(* XHdcp22_Rx_StateFunc)(void *InstancePtr))(void *InstancePtr)
Type for pointer to state function.
typedef void(* XHdcp22_Rx_RunHandler)(void *HandlerRef))(void *HandlerRef)
Type for pointer to single input function.
typedef void(* XHdcp22_Rx_SetHandler)(void *HandlerRef, u32 Data))(void *HandlerRef, u32 Data)
Type for pointer to two input function.
typedef u32(* XHdcp22_Rx_GetHandler)(void *HandlerRef))(void *HandlerRef)
Type for pointer to single input function with a return value.
static int XHdcp22Rx_InitializeCipher(XHdcp22_Rx *InstancePtr)
This function is called to initialize the cipher.
InstancePtr is a pointer to the XHdcp22_Rx core instance. XST_SUCCESS or XST_FAILURE. None.
static int XHdcp22Rx_InitializeMmult(XHdcp22_Rx *InstancePtr)
This function is called to initialize the modular multiplier.
InstancePtr is a pointer to the XHdcp22_Rx core instance. XST_SUCCESS or XST_FAILURE. None.
static int XHdcp22Rx_InitializeRng(XHdcp22_Rx *InstancePtr)
This function is called to initialize the random number generator.
InstancePtr is a pointer to the XHdcp22_Rx core instance. XST_SUCCESS or XST_FAILURE. None.
static int XHdcp22Rx_InitializeTimer(XHdcp22_Rx *InstancePtr)
This function is called to initialize the timer.
InstancePtr is a pointer to the XHdcp22_Rx core instance. XST_SUCCESS or XST_FAILURE. None.
static int XHdcp22Rx_ComputeBaseAddress(UINTPTR BaseAddress, UINTPTR SubcoreOffset, UINTPTR *SubcoreAddressPtr)
This function computes the subcore absolute address on axi-lite interface Subsystem is mapped at an absolute address and all included sub-cores are at pre-defined offset from the subsystem base address.
To access the subcore register map from host CPU an absolute address is required. BaseAddress is the base address of the subsystem instance SubcoreOffset is the offset of the the subcore instance SubcoreAddressPtr is the computed base address of the subcore instance XST_SUCCESS if base address computation is successful and within subsystem address range else XST_FAILURE
static int XHdcp22Rx_GenerateRrx(XHdcp22_Rx *InstancePtr, u8 *RrxPtr)
This function is used to get a random value Rrx of 64bits for AKEInit.
When the test mode is set to XHDCP22_RX_TESTMODE_NO_TX a preloaded test value is copied into the array with pointer RrxPtr. Otherwise, a random value is generated and copied. InstancePtr is a pointer to the XHdcp22_Rx core instance. RrxPtr is a pointer to an array where the 64bit Rrx is to be copied. XST_SUCCESS or XST_FAILURE. None.
static u8 XHdcp22Rx_IsWriteMessageAvailable(XHdcp22_Rx *InstancePtr)
This function is used to check if a complete message is available in the write message buffer.
The DDC flag is cleared when a message available is detected. InstancePtr is a pointer to the XHdcp22_Rx core instance. TRUE or FALSE. None.
static u8 XHdcp22Rx_IsReadMessageComplete(XHdcp22_Rx *InstancePtr)
This function is used to check if a complete message has been read out of the read message buffer, indicating that the buffer is empty.
The DDC flag is cleared when a read message complete has been detected. InstancePtr is a pointer to the XHdcp22_Rx core instance. TRUE or FALSE. None.
static void XHdcp22Rx_SetRxStatus(XHdcp22_Rx *InstancePtr, u16 MessageSize, u8 ReauthReq, u8 TopologyReady)
This function sets the DDC RxStatus registers (0x70-0x71) MessageSize bits.
The HDCP22-RX state machine calls this function immediately after writing a complete message into the read message buffer. The repeater READY bit can also be updated in conjunction to the message size. InstancePtr is a pointer to the XHdcp22_Rx core instance. MessageSize indicates the size in bytes of the message available in the read message buffer. ReauthReq is set to TRUE to assert the REAUTH_REQ bit. TopologyReady is set to TRUE to assert the READY bit. None. None.
static void XHdcp22Rx_SetDdcReauthReq(XHdcp22_Rx *InstancePtr)
This function sets the DDC RxStatus registers (0x70-0x71) ReauthReq bit and clears the link integrity error flag.
Setting the ReauthReq bit signals the transmitter to re-initiate authentication. InstancePtr is a pointer to the XHdcp22_Rx core instance. None. None.
static void XHdcp22Rx_ResetDdc(XHdcp22_Rx *InstancePtr, u8 ClrWrBuffer, u8 ClrRdBuffer, u8 ClrReady, u8 ClrReauthReq)
This function resets the HDCP22-RX DDC registers to their default values and clears the read/write message buffers.
The DDC status flag is set to it's initial state and the DDC error flags are cleared. InstancePtr is a pointer to the XHdcp22_Rx core instance. ClrWrBuffer is TRUE to clear the write message buffer. ClrRdBuffer is TRUE to clear the read message buffer. ClrReady is TRUE to clear the READY bit. ClrReauthReq is set to TRUE to clear the REAUTH_REQ bit. None. None.
static void XHdcp22Rx_ResetAfterError(XHdcp22_Rx *InstancePtr)
This function resets the HDCP22-RX system after an error event.
The driver calls this function when recovering from error conditions. InstancePtr is a pointer to the XHdcp22_Rx core instance. None. None.
static void XHdcp22Rx_ResetParams(XHdcp22_Rx *InstancePtr)
This function resets the HDCP22-RX parameters stored in memory during the authentication process.
InstancePtr is a pointer to the XHdcp22_Rx core instance. None. This function is called each time an AKE_Init message is received.
static int XHdcp22Rx_PollMessage(XHdcp22_Rx *InstancePtr)
This function uses polling to read a complete message out of the read message buffer.
InstancePtr is a pointer to the XHdcp22_Rx core instance. Size of message read out of read message buffer. None.
static void XHdcp22Rx_TimerHandler(void *CallbackRef, u8 TmrCntNumber)
This function handles timer interrupts.
CallbackRef refers to a XHdcp22_Rx structure TmrCntNumber the number of used timer. None. None.
static void XHdcp22Rx_StartTimer(XHdcp22_Rx *InstancePtr, u32 TimeOut_mSec, u8 ReasonId)
This function starts the count down timer needed for checking protocol timeouts.
InstancePtr is a pointer to the XHdcp22_Rx core instance. TimeOut_mSec is the timeout for the next status update. XST_SUCCESS or XST_FAILURE. None.
static void XHdcp22Rx_StopTimer(XHdcp22_Rx *InstancePtr)
This function stops the count down timer used for protocol timeouts.
InstancePtr is a pointer to the XHdcp22_Rx core instance. TimeOut_mSec is the timeout for the next status update. XST_SUCCESS or XST_FAILURE. None.
static void * XHdcp22Rx_StateB0(XHdcp22_Rx *InstancePtr)
This function implements the Receiver State B0 (Unauthenticated).
In this state the receiver is awaiting the reception of AKE_Init from the transmitter to trigger the authentication protocol. InstancePtr is a pointer to the XHdcp22_Rx core instance. Pointer to the function that implements the next state. When an unexpected or malformed message is received the system is reset to a known state to allow graceful recovery from error.
static void * XHdcp22Rx_StateB1(XHdcp22_Rx *InstancePtr)
This function implements the Receiver State B1 (ComputeKm).
In this state the receiver makes the AKESendCert message available for reading by the transmitter in response to AKEInit. If AKENoStoredKm is received, the receiver decrypts Km with KprivRx and calculates HPrime. If AKEStoredKm is received it decrypts Ekh(Km) to derive Km and calculate HPrime. It makes AKESendHPrime message available for reading immediately after computation of HPrime to ensure that the message is received by the transmitter within the specified 1s timeout at the transmitter for NoStoredKm and 200ms timeout for StoredKm. When AKENoStoredKm is received the AKESendPairingInfo message is made available to the transmitter for reading after within 200ms after AKESendHPrime message is received by the transmitter. InstancePtr is a pointer to the XHdcp22_Rx core instance. Pointer to the function that implements the next state. When an unexpected or malformed message is received the system is reset to the default state B0 to allow graceful recovery from error.
static void * XHdcp22Rx_StateB2(XHdcp22_Rx *InstancePtr)
This function implements the Receiver State B2 (Compute_LPrime).
The receiver computes LPrime required during locality check and makes LCSendLPrime message available for reading by the transmitter. InstancePtr is a pointer to the XHdcp22_Rx core instance. Pointer to the function that implements the next state. When an unexpected or malformed message is received the system is reset to the default state B0 to allow graceful recovery from error.
static void * XHdcp22Rx_StateB3(XHdcp22_Rx *InstancePtr)
This function implements the Receiver State B3 (ComputeKs).
The receiver decrypts Edkey(Ks) to derive Ks. The cipher is updated with the session key and enabled within 200ms after the encrypted session key is received. InstancePtr is a pointer to the XHdcp22_Rx core instance. Pointer to the function that implements the next state. When an unexpected or malformed message is received the system is reset to the default state B0 to allow graceful recovery from error.
static void * XHdcp22Rx_StateB4(XHdcp22_Rx *InstancePtr)
This function implements the Receiver State B4 (Authenticated).
The receiver has completed the authentication protocol. This function executes the XHDCP22_RX_HANDLER_AUTHENTICATED user callback function on transition to this state. An ongoing link integrity check is performed external to the HDCP22-RX system to detect synchronization mismatches between transmitter and receiver. RxStatus REAUTH_REQ bit is set if 50 consecutive data island CRC errors are detected. Setting the REAUTH_REQ bit signals the transmitter to re-initiate authentication. InstancePtr is a pointer to the XHdcp22_Rx core instance. Pointer to the function that implements the next state. When an unexpected or malformed message is received the system is reset to the default state B0 to allow graceful recovery from error.
static void * XHdcp22Rx_StateC4(XHdcp22_Rx *InstancePtr)
This function implements the Repeater State C4 (WaitForDownstream).
In this state the receiver upstream is waiting for all downstream HDCP-protected interface ports of the HDCP Repeater to enter one of the following states: Unconnected (State P0), Unauthenticated (State P1), Authenticated (State F5), or ReceiverIdListAck (State F8). This state checks if the topology table is available for upstream propagation based on the flag set in the function XHdcp22Rx_SetTopologyUpdate by the higher level repeater function. InstancePtr is a pointer to the XHdcp22_Rx core instance. Pointer to the function that implements the next state. If a link integrity problem is detected during this state then the REAUTH_REQ bit is set in the RxStatus register. If the RepeaterAuth_Stream_Manage message is received then transition to State C7 then return back to this state.
static void * XHdcp22Rx_StateC5(XHdcp22_Rx *InstancePtr)
This function implements the Repeater State C5 (AssembleReceiverIdList).
If MAX_DEVS_EXCEEDED or MAX_CASCADE_EXCEEDED is not set then this state calculates VPrime based on the Receiver ID List in the topology table. After VPrime is calculated the Repeaterauth_Send_ReceiverID_List message is populated based on the topology table, VPrime computation, and current seq_num_V counter value. seq_num_V is initialized to a value of zero after AKE_Init and is incremented by one after the transmission of every RepeaterAuth_Send_ReceiverID_List message. The upstream transmitter is responsible for detecting roll over of seq_num_V. The READY bit is asserted once the Repeaterauth_Send_ReceiverID_List message is made available to the upstream and a watchdog timer is set to detect if the acknowledgement arrives within a 2 second period. If the topology maximum flags are asserted in the topology table then the state machine transitions to StateC0 immediately after the Repeaterauth_Send_ReceiverID_List message is read, and the REAUTH_REQ bit is set the in the RxStatus register. InstancePtr is a pointer to the XHdcp22_Rx core instance. Pointer to the function that implements the next state. If a link integrity problem is detected during this state then the REAUTH_REQ bit is set in the RxStatus register. If the RepeaterAuth_Stream_Manage message is received then transition to State C7 then return back to this state.
static void * XHdcp22Rx_StateC6(XHdcp22_Rx *InstancePtr)
This function implements the Repeater State C6 (VerifyReceiverIdListAck).
The RepeaterAuth_Send_Ack message should be available for the receiver upstream interface within two seconds from when the READY bit in the RxStatus register was set in State C5. If the message is not available within the two second window then the state machine transitions back into the un-authenticated state. If the message is received in-time and the least significant 128-bits of V and VPrime match, this indicated successful upstream transmission of topology information and triggers a transition to State C7. If there is a mismatch then the state machine transitions back to the un-authenticated state, and the REAUTH_REQ bit is set in the RxStatus Register. InstancePtr is a pointer to the XHdcp22_Rx core instance. Pointer to the function that implements the next state. If a link integrity problem is detected during this state then the REAUTH_REQ bit is set in the RxStatus register. If the RepeaterAuth_Stream_Manage message is received then transition to State C7 then return back to this state.
static void * XHdcp22Rx_StateC7(XHdcp22_Rx *InstancePtr)
This function implements the Repeater State C7 (ContentStreamManagement).
This state waits to receive the RepeaterAuth_Stream_Manage message from the upstream transmitter. Once the message is received the MPrime value is computed and made available to the upstream transmitter to read as part of the RepeaterAuth_Stream_Ready message. Note that state executes in parallel with the upstream propagation of topology information (State C4, State C5, and State C6). A transition in to this state may occur from State C4, State C5, or State C6 if content stream management information is received from the upstream transmitter. Also, the transition from State C7 may return to the appropriate state to allow undisrupted operation. InstancePtr is a pointer to the XHdcp22_Rx core instance. Pointer to the function that implements the next state. If a link integrity problem is detected during this state then the REAUTH_REQ bit is set in the RxStatus register. If the RepeaterAuth_Stream_Manage message is received then transition to State C7 then return back to this state.
static void * XHdcp22Rx_StateC8(XHdcp22_Rx *InstancePtr)
This function implements the Receiver State C8 (Authenticated).
The repeater has completed the authentication protocol. Upon detection of any changes to the topology a transition back to State C5 (AssembleReceiverIdList) occurs. Change to the topology occur when a repeater downstream port has transitioned to the following: authenticated, unauthenticated, or unconnected. This function executes the XHDCP22_RX_HANDLER_AUTHENTICATED user callback function on transition to this state. An ongoing link integrity check is performed external to the HDCP22-RX system to detect synchronization mismatches between transmitter and receiver. RxStatus REAUTH_REQ bit is set if 50 consecutive data island CRC errors are detected. Setting the REAUTH_REQ bit signals the transmitter to re-initiate authentication. InstancePtr is a pointer to the XHdcp22_Rx core instance. Pointer to the function that implements the next state. When an unexpected or malformed message is received the system is reset to the default state B0 to allow graceful recovery from error.
static int XHdcp22Rx_ProcessMessageAKEInit(XHdcp22_Rx *InstancePtr)
This function processes the AKE_Init message received from the transmitter.
The stored authentication parameters are reset so that no state information is stored between authentication attempts. The DDC registers are reset to their default value including the REAUTH_REQ flag. The cipher is disabled. InstancePtr is a pointer to the XHdcp22_Rx core instance. - XST_SUCCESS if message processed successfully. XST_FAILURE if message size is incorrect. None.
static int XHdcp22Rx_ProcessMessageAKENoStoredKm(XHdcp22_Rx *InstancePtr)
This function processes the AKE_No_Stored_km message received from the transmitter.
The RSAES-OAEP operation decrypts Km with the receiver private key. InstancePtr is a pointer to the XHdcp22_Rx core instance. - XST_SUCCESS if message processed successfully. XST_FAILURE if message size is incorrect or Km decryption failed. None.
static int XHdcp22Rx_ProcessMessageAKEStoredKm(XHdcp22_Rx *InstancePtr)
This function processes the AKE_Stored_km message received from the transmitter.
Decrypts Ekh(Km) using AES with the received m as input and Kh as key into the AES module. InstancePtr is a pointer to the XHdcp22_Rx core instance. - XST_SUCCESS if message processed successfully. XST_FAILURE if message size is incorrect. None.
static int XHdcp22Rx_ProcessMessageLCInit(XHdcp22_Rx *InstancePtr)
This function processes the LC_Init message received from the transmitter.
The locality check attempts is incremented for each LCInit message received. The random nonce Rn is recorded. InstancePtr is a pointer to the XHdcp22_Rx core instance. - XST_SUCCESS if message processed successfully. XST_FAILURE if message size is incorrect. None.
static int XHdcp22Rx_ProcessMessageSKESendEks(XHdcp22_Rx *InstancePtr)
This function processes the SKE_Send_Eks message received from the transmitter.
The session key Ks is decrypted and written to the cipher. InstancePtr is a pointer to the XHdcp22_Rx core instance. - XST_SUCCESS if message processed successfully. XST_FAILURE if message size is incorrect. The cipher must be enabled within 200ms after receiving SKESendEks.
static int XHdcp22Rx_ProcessMessageRepeaterAuthSendAck(XHdcp22_Rx *InstancePtr)
This function processes the RepeaterAuth_Send_Ack message received from the upstream transmitter.
The least significant 128-bits of the value V are compared against VPrime. The timer is stopped. InstancePtr is a pointer to the XHdcp22_Rx core instance. - XST_SUCCESS when V and VPrime match. XST_FAILURE when V and VPrime do not match. The RepeaterAuth_Send_Ack message must be available for the repeater upstream interface within 2 seconds after asserting the READY bit in the RxStatus register.
static int XHdcp22Rx_ProcessMessageRepeaterAuthStreamManage(XHdcp22_Rx *InstancePtr)
This function processes the RepeaterAuth_Repeater_Manage message.
The message values seq_num_M and StreamID_Type are stored for later computation of MPrime. The user callback function type XHDCP22_RX_HANDLER_STREAM_MANAGE_REQUEST is executed. InstancePtr is a pointer to the XHdcp22_Rx core instance. - XST_SUCCESS if message processed successfully. XST_FAILURE if message size is incorrect. After receiving RepeaterAuth_Repeater_Manage message the repeater upstream interface has 100ms to respond with the RepeaterAuth_Stream_Ready message. Detection of seq_num_M roll-over is the responsibility of the upstream transmitter.
static int XHdcp22Rx_SendMessageAKESendCert(XHdcp22_Rx *InstancePtr)
This function generates the AKE_Send_Cert message and writes it into the read message buffer.
After the complete message has been written to the buffer the MessageSize is set in the DDC RxStatus register signaling the transmitter that the message is available for reading. InstancePtr is a pointer to the XHdcp22_Rx core instance. - XST_SUCCESS if message written successfully. XST_FAILURE if generation of random integer Rrx failed. This message must be available for the transmitter with 100ms after receiving AKEInit.
static int XHdcp22Rx_SendMessageAKESendHPrime(XHdcp22_Rx *InstancePtr)
This function computes HPrime, generates AKE_Send_H_prime message, and writes it into the read message buffer.
After the complete message has been written to the buffer the MessageSize is set in the DDC RxStatus register signaling the transmitter that the message is available for reading. InstancePtr is a pointer to the XHdcp22_Rx core instance. XST_SUCCESS. This message must be available for the transmitter within 1s after receiving AKENoStoredKm or 200ms after receiving AKEStoredKm.
static int XHdcp22Rx_SendMessageAKESendPairingInfo(XHdcp22_Rx *InstancePtr)
This function computes Ekh(Km), generates AKE_Send_Pairing_Info message, and writes it into the read message buffer.
After the complete message has been written to the buffer the MessageSize is set in the DDC RxStatus register signaling the transmitter that the message is available for reading. InstancePtr is a pointer to the XHdcp22_Rx core instance. XST_SUCCESS. The AKESendPairingInfo message is sent only in response to receiving AKENoStoredKm message. This message must be available for the transmitter within 200ms after sending AKESendHPrime.
static int XHdcp22Rx_SendMessageLCSendLPrime(XHdcp22_Rx *InstancePtr)
This function computes LPrime, generates LC_Send_L_prime message, and writes it into the read message buffer.
After the complete message has been written to the buffer the MessageSize is set in the DDC RxStatus register signaling the transmitter that the message is available for reading. InstancePtr is a pointer to the XHdcp22_Rx core instance. XST_SUCCESS. The LCSendLPrime message must be available for the transmitter within 20ms after receiving LCInit.
static int XHdcp22Rx_SendMessageRepeaterAuthSendRxIdList(XHdcp22_Rx *InstancePtr)
This function generates the RepeaterAuth_Send_ReceiverID_List message and writes it into the read message buffer.
After the complete message has been written to the buffer the MessageSize and READY fields are set in the DDC RxStatus register signaling the transmitter that the message is available for reading. When the topology maximums are not exceeded VPrime is computed. seq_num_v is incremented after the transmission of each RepeaterAuth_Send_ReceiverID_List message. The READY bit in the RxStatus register is cleared automatically. InstancePtr is a pointer to the XHdcp22_Rx core instance. - XST_SUCCESS if device count is equal to zero. XST_FAILURE if device count is greater than zero. The RepeaterAuth_Send_ReceiverID_List must be available and READY bit asserted in the RxStatus register for the upstream transmitter within 3 seconds.
static int XHdcp22Rx_SendMessageRepeaterAuthStreamReady(XHdcp22_Rx *InstancePtr)
This function computes MPrime and sends the RepeaterAuth_Stream_Ready message.
InstancePtr is a pointer to the XHdcp22_Rx core instance. XST_SUCCESS. None.
static void XHdcp22Rx_SetTopologyDepth(XHdcp22_Rx *InstancePtr, u8 Depth)
This function sets DEPTH in the repeater topology table.
InstancePtr is a pointer to the XHdcp22_Rx core instance. Depth is the Repeater cascade depth. This value gives the number of attached levels through the connection topology. The depth cannot cannot exceed 4 levels. None. None.
static void XHdcp22Rx_SetTopologyDeviceCnt(XHdcp22_Rx *InstancePtr, u8 DeviceCnt)
This function sets DEVICE_COUNT in the repeater topology table.
InstancePtr is a pointer to the XHdcp22_Rx core instance. DeviceCnt is the Total number of connected downstream devices. Always zero for HDCP Receivers. The device count does not include the HDCP Repeater itself, but only devices downstream from the HDCP Repeater. The device count cannot exceed 31 devices. None. None.
static void XHdcp22Rx_SetTopologyMaxDevsExceeded(XHdcp22_Rx *InstancePtr, u8 Value)
This function sets the MAX_DEVS_EXCEEDED error flag in the repeater topology table used to indicate a topology error.
Setting the flag indicates that more than 31 downstream devices are attached. InstancePtr is a pointer to the XHdcp22_Rx core instance. Value is either TRUE or FALSE. None. None.
static void XHdcp22Rx_SetTopologyMaxCascadeExceeded(XHdcp22_Rx *InstancePtr, u8 Value)
This function sets the MAX_CASCADE_EXCEEDED flag in the repeater topology table used to indicate a topology error.
Setting the error flag indicates that more than four levels of repeaters have been cascaded together. InstancePtr is a pointer to the XHdcp22_Rx core instance. Value is either TRUE or FALSE. None. None.
static void XHdcp22Rx_SetTopologyHdcp2LegacyDeviceDownstream(XHdcp22_Rx *InstancePtr, u8 Value)
This function sets the HDCP2_LEGACY_DEVICE_DOWNSTREAM flag in the repeater topology table used to indicate the presence of an HDCP2.0-compliant Device in the topology.
InstancePtr is a pointer to the XHdcp22_Rx core instance. Value is either TRUE or FALSE. None. None.
static void XHdcp22Rx_SetTopologyHdcp1DeviceDownstream(XHdcp22_Rx *InstancePtr, u8 Value)
This function sets the HDCP1_DEVICE_DOWNSTREAM flag in the repeater topology table used to indicate the presence of an HDCP1.x-compliant device in the topology.
InstancePtr is a pointer to the XHdcp22_Rx core instance. Value is either TRUE or FALSE. None. None.
static void XHdcp22_Rx_StubRunHandler(void *HandlerRef)
This function is a stub for the run handler.
The stub is here in case the upper layer forgot to set the handlers. On initialization, all handlers are set to this callback. It is considered an error for this handler to be invoked. HandlerRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. None. None.
static void XHdcp22_Rx_StubSetHandler(void *HandlerRef, u32 Data)
This function is a stub for the set handler.
The stub is here in case the upper layer forgot to set the handlers. On initialization, all handlers are set to this callback. It is considered an error for this handler to be invoked. HandlerRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. Data is a value to be set. None. None.
static u32 XHdcp22_Rx_StubGetHandler(void *HandlerRef)
This function is a stub for the set handler.
The stub is here in case the upper layer forgot to set the handlers. On initialization, all handlers are set to this callback. It is considered an error for this handler to be invoked. HandlerRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. Returns the get value. None.
int XHdcp22Rx_CfgInitialize(XHdcp22_Rx *InstancePtr, XHdcp22_Rx_Config *ConfigPtr, UINTPTR EffectiveAddr)
Initialize the instance provided by the caller based on the given configuration data.
InstancePtr is a pointer to an XHdcp22_Rx instance. The memory the pointer references must be pre-allocated by the caller. Further calls to manipulate the driver through the HDCP22-RX API must be made with this pointer. ConfigPtr is a reference to a structure containing information about a specific HDCP22-RX device. This function initializes an InstancePtr object for a specific device specified by the contents of Config. This function can initialize multiple instance objects with the use of multiple calls giving different Config information on each call. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS or XST_FAILURE. None.
References XHdcp22_Rx_Handles::AuthenticatedCallback, XHdcp22_Rx_Handles::AuthenticationRequestCallback, XHdcp22_Rx_Info::AuthenticationStatus, XHdcp22_Rx_Info::AuthRequestCnt, XHdcp22_Rx_Config::BaseAddress, XHdcp22_Rx::Config, XHdcp22_Rx_Info::CurrentState, XHdcp22_Rx_Handles::DdcClearReadBufferCallback, XHdcp22_Rx_Handles::DdcClearWriteBufferCallback, XHdcp22_Rx_Info::DdcErrorCnt, XHdcp22_Rx_Handles::DdcGetDataCallback, XHdcp22_Rx_Handles::DdcGetReadBufferSizeCallback, XHdcp22_Rx_Handles::DdcGetWriteBufferSizeCallback, XHdcp22_Rx_Handles::DdcIsReadBufferEmptyCallback, XHdcp22_Rx_Handles::DdcIsWriteBufferEmptyCallback, XHdcp22_Rx_Handles::DdcSetAddressCallback, XHdcp22_Rx_Handles::DdcSetDataCallback, XHdcp22_Rx_Info::ErrorFlag, XHdcp22_Rx_Info::ErrorFlagSticky, XHdcp22_Rx::Handles, XHdcp22_Rx_Info::HasStreamManagementInfo, XHdcp22_Rx::Info, XHdcp22_Rx_Handles::IsAuthenticatedCallbackSet, XHdcp22_Rx_Handles::IsAuthenticationRequestCallbackSet, XHdcp22_Rx_Handles::IsDdcAllCallbacksSet, XHdcp22_Rx_Handles::IsDdcClearReadBufferCallbackSet, XHdcp22_Rx_Handles::IsDdcClearWriteBufferCallbackSet, XHdcp22_Rx_Handles::IsDdcGetDataCallbackSet, XHdcp22_Rx_Handles::IsDdcGetReadBufferSizeCallbackRefSet, XHdcp22_Rx_Handles::IsDdcGetWriteBufferSizeCallbackSet, XHdcp22_Rx_Handles::IsDdcIsReadBufferEmptyCallbackSet, XHdcp22_Rx_Handles::IsDdcIsWriteBufferEmptyCallbackSet, XHdcp22_Rx_Handles::IsDdcSetAddressCallbackSet, XHdcp22_Rx_Handles::IsDdcSetDataCallbackSet, XHdcp22_Rx_Info::IsEnabled, XHdcp22_Rx_Info::IsEncrypted, XHdcp22_Rx_Info::IsNoStoredKm, XHdcp22_Rx::IsReady, XHdcp22_Rx_Handles::IsStreamManageRequestCallbackSet, XHdcp22_Rx_Handles::IsTopologyUpdateCallbackSet, XHdcp22_Rx_Info::IsTopologyValid, XHdcp22_Rx_Info::LCInitAttempts, XHdcp22_Rx_Info::LinkErrorCnt, XHdcp22_Rx_Config::Mode, XHdcp22_Rx_Info::NextState, XHdcp22_Rx_Info::ReauthReq, XHdcp22_Rx_Info::ReauthRequestCnt, XHdcp22_Rx_Info::ReturnState, XHdcp22_Rx::RxCaps, XHdcp22_Rx_Info::SeqNumV, XHdcp22_Rx_Info::SkipRead, XHdcp22_Rx::StateFunc, XHdcp22_Rx_Handles::StreamManageRequestCallback, XHdcp22_Rx_Info::TopologyReady, XHdcp22_Rx_Handles::TopologyUpdateCallback, XHDCP22_RX_ERROR_FLAG_NONE, XHDCP22_RX_RECEIVER, XHDCP22_RX_STATE_B0_WAIT_AKEINIT, XHDCP22_RX_STATE_UNDEFINED, XHDCP22_RX_UNAUTHENTICATED, XHdcp22Rx_LogReset.
int XHdcp22Rx_Reset(XHdcp22_Rx *InstancePtr)
This function resets the HDCP22-RX system to the default state.
The HDCP22-RX DDC registers are set to their default value and the message buffer is reset. InstancePtr is a pointer to the XHdcp22_Rx core instance. XST_SUCCESS or XST_FAILURE. The DDC message handles must be assigned by the XHdcp22Rx_SetDdcHandles function prior to calling this reset function.
References XHdcp22_Rx_Info::AuthenticationStatus, XHdcp22_Rx_Info::AuthRequestCnt, XHdcp22_Rx::CipherInst, XHdcp22_Rx_Info::CurrentState, XHdcp22_Rx_Info::DdcErrorCnt, XHdcp22_Rx_Info::ErrorFlag, XHdcp22_Rx_Info::ErrorFlagSticky, XHdcp22_Rx::Handles, XHdcp22_Rx_Info::HasStreamManagementInfo, XHdcp22_Rx::Info, XHdcp22_Rx_Handles::IsDdcAllCallbacksSet, XHdcp22_Rx_Info::IsEncrypted, XHdcp22_Rx_Info::IsNoStoredKm, XHdcp22_Rx_Info::IsTopologyValid, XHdcp22_Rx_Handles::IsUnauthenticatedCallbackSet, XHdcp22_Rx_Info::LCInitAttempts, XHdcp22_Rx_Info::LinkErrorCnt, XHdcp22_Rx::MessageBuffer, XHdcp22_Rx::MessageSize, XHdcp22_Rx_Info::NextState, XHdcp22_Rx_Info::ReauthReq, XHdcp22_Rx_Info::ReauthRequestCnt, XHdcp22_Rx_Info::ReturnState, XHdcp22_Rx_Info::SeqNumV, XHdcp22_Rx_Info::SkipRead, XHdcp22_Rx::StateFunc, XHdcp22_Rx::Topology, XHdcp22_Rx_Info::TopologyReady, XHdcp22_Rx_Handles::UnauthenticatedCallback, XHdcp22_Rx_Handles::UnauthenticatedCallbackRef, XHDCP22_RX_AUTHENTICATED, XHDCP22_RX_ERROR_FLAG_NONE, XHDCP22_RX_LOG_EVT_INFO, XHDCP22_RX_LOG_INFO_RESET, XHDCP22_RX_STATE_B0_WAIT_AKEINIT, XHDCP22_RX_STATE_UNDEFINED, XHDCP22_RX_UNAUTHENTICATED, XHdcp22Rx_LogWr.
int XHdcp22Rx_Enable(XHdcp22_Rx *InstancePtr)
This function enables the HDCP22-RX state machine.
The HDCP2Version register is set to active. InstancePtr is a pointer to the XHdcp22_Rx core instance. XST_SUCCESS or XST_FAILURE. Before enabling the state machine ensure that the instance has been initialized, DDC message handles have been assigned, and keys have been loaded.
References XHdcp22_Rx::CipherInst, XHdcp22_Rx::Handles, XHdcp22_Rx::Info, XHdcp22_Rx_Handles::IsDdcAllCallbacksSet, XHdcp22_Rx_Info::IsEnabled, XHdcp22_Rx::IsReady, XHdcp22_Rx::MmultInst, XHdcp22_Rx::PrivateKeyPtr, XHdcp22_Rx::PublicCertPtr, XHdcp22_Rx::RngInst, XHdcp22_Rx::TimerInst, XHDCP22_RX_LOG_EVT_INFO, XHDCP22_RX_LOG_INFO_ENABLE, XHdcp22Rx_LogWr.
int XHdcp22Rx_Disable(XHdcp22_Rx *InstancePtr)
This function disables the HDCP22-RX state machine.
The HDCP2Version register is cleared, and the ReauthReq bit is set in the RxStatus register to allow the transmitter to recover when it has already authenticated. Without setting the ReauthReq bit the transmitter will not know that HDCP 2.2 protocol has been disabled by the Receiver after it has already authenticated. InstancePtr is a pointer to the XHdcp22_Rx core instance. XST_SUCCESS or XST_FAILURE. The HDCP22-RX cipher is disabled.
References XHdcp22_Rx::CipherInst, XHdcp22_Rx::Info, XHdcp22_Rx_Info::IsEnabled, XHdcp22_Rx::RngInst, XHDCP22_RX_LOG_EVT_INFO, XHDCP22_RX_LOG_INFO_DISABLE, XHdcp22Rx_LogWr.
void XHdcp22Rx_SetBroadcast(XHdcp22_Rx *InstancePtr, u8 enable)
int XHdcp22Rx_SetCallback(XHdcp22_Rx *InstancePtr, XHdcp22_Rx_HandlerType HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs callback functions for the given HandlerType:
HandlerType Callback Function Type ------------------------- --------------------------- (XHDCP22_RX_HANDLER_DDC_SETREGADDR) DdcSetAddressCallback (XHDCP22_RX_HANDLER_DDC_SETREGDATA) DdcSetDataCallback (XHDCP22_RX_HANDLER_DDC_GETREGDATA) DdcGetDataCallback (XHDCP22_RX_HANDLER_DDC_GETWBUFSIZE) DdcGetWriteBufferSizeCallback (XHDCP22_RX_HANDLER_DDC_GETRBUFSIZE) DdcGetReadBufferSizeCallback (XHDCP22_RX_HANDLER_DDC_ISWBUFEMPTY) DdcIsWriteBufferEmptyCallback (XHDCP22_RX_HANDLER_DDC_ISRBUFEMPTY) DdcIsReadBufferEmptyCallback (XHDCP22_RX_HANDLER_DDC_CLEARRBUF) DdcClearReadBufferCallback (XHDCP22_RX_HANDLER_DDC_CLEARWBUF) DdcClearWriteBufferCallback (XHDCP22_RX_HANDLER_AUTHENTICATED) AuthenticatedCallback (XHDCP22_RX_HANDLER_UNAUTHENTICATED) UnauthenticatedCallback (XHDCP22_RX_HANDLER_AUTHENTICATION_REQUEST) AuthenticationRequestCallback (XHDCP22_RX_HANDLER_STREAM_MANAGE_REQUEST) StreamManageRequestCallback (XHDCP22_RX_HANDLER_TOPOLOGY_UPDATE) TopologyUpdateCallback InstancePtr is a pointer to the HDMI RX core instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XHdcp22_Rx_Handles::AuthenticatedCallback, XHdcp22_Rx_Handles::AuthenticatedCallbackRef, XHdcp22_Rx_Handles::AuthenticationRequestCallback, XHdcp22_Rx_Handles::AuthenticationRequestCallbackRef, XHdcp22_Rx_Handles::DdcClearReadBufferCallback, XHdcp22_Rx_Handles::DdcClearReadBufferCallbackRef, XHdcp22_Rx_Handles::DdcClearWriteBufferCallback, XHdcp22_Rx_Handles::DdcClearWriteBufferCallbackRef, XHdcp22_Rx_Handles::DdcGetDataCallback, XHdcp22_Rx_Handles::DdcGetDataCallbackRef, XHdcp22_Rx_Handles::DdcGetReadBufferSizeCallback, XHdcp22_Rx_Handles::DdcGetReadBufferSizeCallbackRef, XHdcp22_Rx_Handles::DdcGetWriteBufferSizeCallback, XHdcp22_Rx_Handles::DdcGetWriteBufferSizeCallbackRef, XHdcp22_Rx_Handles::DdcIsReadBufferEmptyCallback, XHdcp22_Rx_Handles::DdcIsReadBufferEmptyCallbackRef, XHdcp22_Rx_Handles::DdcIsWriteBufferEmptyCallback, XHdcp22_Rx_Handles::DdcIsWriteBufferEmptyCallbackRef, XHdcp22_Rx_Handles::DdcSetAddressCallback, XHdcp22_Rx_Handles::DdcSetAddressCallbackRef, XHdcp22_Rx_Handles::DdcSetDataCallback, XHdcp22_Rx_Handles::DdcSetDataCallbackRef, XHdcp22_Rx_Handles::EncryptionStatusCallback, XHdcp22_Rx_Handles::EncryptionStatusCallbackRef, XHdcp22_Rx::Handles, XHdcp22_Rx_Handles::IsAuthenticatedCallbackSet, XHdcp22_Rx_Handles::IsAuthenticationRequestCallbackSet, XHdcp22_Rx_Handles::IsDdcAllCallbacksSet, XHdcp22_Rx_Handles::IsDdcClearReadBufferCallbackSet, XHdcp22_Rx_Handles::IsDdcClearWriteBufferCallbackSet, XHdcp22_Rx_Handles::IsDdcGetDataCallbackSet, XHdcp22_Rx_Handles::IsDdcGetReadBufferSizeCallbackRefSet, XHdcp22_Rx_Handles::IsDdcGetWriteBufferSizeCallbackSet, XHdcp22_Rx_Handles::IsDdcIsReadBufferEmptyCallbackSet, XHdcp22_Rx_Handles::IsDdcIsWriteBufferEmptyCallbackSet, XHdcp22_Rx_Handles::IsDdcSetAddressCallbackSet, XHdcp22_Rx_Handles::IsDdcSetDataCallbackSet, XHdcp22_Rx_Handles::IsEncryptionStatusCallbackSet, XHdcp22_Rx_Handles::IsStreamManageRequestCallbackSet, XHdcp22_Rx_Handles::IsTopologyUpdateCallbackSet, XHdcp22_Rx_Handles::IsUnauthenticatedCallbackSet, XHdcp22_Rx_Handles::StreamManageRequestCallback, XHdcp22_Rx_Handles::StreamManageRequestCallbackRef, XHdcp22_Rx_Handles::TopologyUpdateCallback, XHdcp22_Rx_Handles::TopologyUpdateCallbackRef, XHdcp22_Rx_Handles::UnauthenticatedCallback, XHdcp22_Rx_Handles::UnauthenticatedCallbackRef, XHDCP22_RX_HANDLER_AUTHENTICATED, XHDCP22_RX_HANDLER_AUTHENTICATION_REQUEST, XHDCP22_RX_HANDLER_DDC_CLEARRBUF, XHDCP22_RX_HANDLER_DDC_CLEARWBUF, XHDCP22_RX_HANDLER_DDC_GETRBUFSIZE, XHDCP22_RX_HANDLER_DDC_GETREGDATA, XHDCP22_RX_HANDLER_DDC_GETWBUFSIZE, XHDCP22_RX_HANDLER_DDC_ISRBUFEMPTY, XHDCP22_RX_HANDLER_DDC_ISWBUFEMPTY, XHDCP22_RX_HANDLER_DDC_SETREGADDR, XHDCP22_RX_HANDLER_DDC_SETREGDATA, XHDCP22_RX_HANDLER_ENCRYPTION_UPDATE, XHDCP22_RX_HANDLER_INVALID, XHDCP22_RX_HANDLER_STREAM_MANAGE_REQUEST, XHDCP22_RX_HANDLER_TOPOLOGY_UPDATE, XHDCP22_RX_HANDLER_UNAUTHENTICATED, XHDCP22_RX_HANDLER_UNDEFINED.
int XHdcp22Rx_Poll(XHdcp22_Rx *InstancePtr)
This function executes the HDCP22-RX state machine.
InstancePtr is a pointer to the XHdcp22_Rx core instance. None. State transitions are logged.
References XHdcp22_Rx_Info::AuthenticationStatus, XHdcp22_Rx_Info::CurrentState, XHdcp22_Rx::Info, XHdcp22_Rx_Info::IsEnabled, XHdcp22_Rx_Info::NextState, XHdcp22_Rx::StateFunc, XHDCP22_RX_LOG_EVT_INFO_STATE, XHdcp22Rx_LogWr.
u8 XHdcp22Rx_IsEnabled(XHdcp22_Rx *InstancePtr)
This function checks if the HDCP22-RX state machine is enabled.
InstancePtr is a pointer to the XHdcp22_Rx core instance. TRUE or FALSE. None.
References XHdcp22_Rx::Info, XHdcp22_Rx_Info::IsEnabled.
Referenced by XHdcp22Rx_Info.
u8 XHdcp22Rx_IsEncryptionEnabled(XHdcp22_Rx *InstancePtr)
This function checks if the HDCP22-RX cipher encryption is enabled.
InstancePtr is a pointer to the XHdcp22_Rx core instance. TRUE or FALSE. None.
References XHdcp22_Rx::CipherInst.
Referenced by XHdcp22Rx_Info.
u8 XHdcp22Rx_IsInProgress(XHdcp22_Rx *InstancePtr)
This function checks if the HDCP22-RX state machine is enabled but not yet in the Authenticated state.
InstancePtr is a pointer to the XHdcp22_Rx core instance. TRUE or FALSE. None.
References XHdcp22_Rx_Info::AuthenticationStatus, XHdcp22_Rx::Info, XHDCP22_RX_AUTHENTICATION_BUSY.
u8 XHdcp22Rx_IsAuthenticated(XHdcp22_Rx *InstancePtr)
This function checks if the HDCP22-RX state machine is in the Authenticated state.
InstancePtr is a pointer to the XHdcp22_Rx core instance. TRUE or FALSE. None.
References XHdcp22_Rx_Info::AuthenticationStatus, XHdcp22_Rx::Info, XHDCP22_RX_AUTHENTICATED.
u8 XHdcp22Rx_IsError(XHdcp22_Rx *InstancePtr)
This function checks if the HDCP22-RX state machine has detected an error condition.
InstancePtr is a pointer to the XHdcp22_Rx core instance. TRUE or FALSE. None.
References XHdcp22_Rx_Info::ErrorFlagSticky, XHdcp22_Rx::Info, XHDCP22_RX_ERROR_FLAG_NONE.
u8 XHdcp22Rx_IsRepeater(XHdcp22_Rx *InstancePtr)
This function returns the current repeater mode status.
InstancePtr is a pointer to the XHdcp22_Rx core instance. TRUE if the HDCP 2.2 instance is the upstream port of a repeaterFALSE if the HDCP 2.2 instance is a receiver
References XHdcp22_Rx::Config, XHdcp22_Rx_Config::Mode, XHDCP22_RX_RECEIVER.
Referenced by XHdcp22Rx_Info.
void XHdcp22Rx_SetRepeater(XHdcp22_Rx *InstancePtr, u8 Set)
This function sets the repeater mode status.
InstancePtr is a pointer to the XHdcp22_Rx core instance. Set is TRUE to enable repeater mode and FALSE to disable.
References XHdcp22_Rx::Config, XHdcp22_Rx_Config::Mode, XHdcp22_Rx::RxCaps, XHDCP22_RX_RECEIVER, XHDCP22_RX_REPEATER.
void XHdcp22Rx_SetLinkError(XHdcp22_Rx *InstancePtr)
This function is called when 50 consecutive data island ECC errors are detected indicating a link integrity problem.
The error flag is set indicating to the state machine that REAUTH_REQ bit in the RXSTATUS register be set. Setting this flag only takes effect when the authentication state machine is in the Authenticated state B4. InstancePtr is a pointer to the XHdcp22_Rx core instance. This function can be registered as an asynchronous callback.
References XHdcp22_Rx_Info::ErrorFlag, XHdcp22_Rx::Info, XHdcp22_Rx_Info::LinkErrorCnt, XHDCP22_RX_ERROR_FLAG_LINK_INTEGRITY, XHDCP22_RX_LOG_EVT_ERROR, XHdcp22Rx_LogWr.
void XHdcp22Rx_SetDdcError(XHdcp22_Rx *InstancePtr)
This function is called when a DDC read/write burst stops prior to completing the expected message size.
This will cause the message buffers to be flushed and state machine reset. InstancePtr is a pointer to the XHdcp22_Rx core instance. This function can be registered as an asynchronous callback.
References XHdcp22_Rx_Info::DdcErrorCnt, XHdcp22_Rx_Info::ErrorFlag, XHdcp22_Rx::Info, XHDCP22_RX_ERROR_FLAG_DDC_BURST, XHDCP22_RX_LOG_EVT_ERROR, XHdcp22Rx_LogWr.
void XHdcp22Rx_SetWriteMessageAvailable(XHdcp22_Rx *InstancePtr)
This function is called when a complete message is available in the write message buffer.
InstancePtr is a pointer to the XHdcp22_Rx core instance. This function can be registered as an asynchronous callback.
References XHdcp22_Rx_Info::DdcFlag, XHdcp22_Rx::Info, XHDCP22_RX_DDC_FLAG_WRITE_MESSAGE_READY, XHDCP22_RX_LOG_DEBUG_WRITE_MESSAGE_AVAILABLE, XHDCP22_RX_LOG_EVT_DEBUG, XHdcp22Rx_LogWr.
void XHdcp22Rx_SetReadMessageComplete(XHdcp22_Rx *InstancePtr)
This function is called when a message has been read out of the read message buffer.
InstancePtr is a pointer to the XHdcp22_Rx core instance. This function can be registered as an asynchronous callback.
References XHdcp22_Rx_Info::DdcFlag, XHdcp22_Rx::Info, XHDCP22_RX_DDC_FLAG_READ_MESSAGE_READY, XHDCP22_RX_LOG_DEBUG_READ_MESSAGE_COMPLETE, XHDCP22_RX_LOG_EVT_DEBUG, XHdcp22Rx_LogWr.
void XHdcp22Rx_LoadLc128(XHdcp22_Rx *InstancePtr, const u8 *Lc128Ptr)
This function is used to load the Lc128 value by copying the contents of the array referenced by Lc128Ptr into the cipher.
InstancePtr is a pointer to the XHdcp22_Rx core instance. Lc128Ptr is a pointer to an array. None.
References XHdcp22_Rx::CipherInst.
void XHdcp22Rx_LoadPublicCert(XHdcp22_Rx *InstancePtr, const u8 *PublicCertPtr)
This function is used to load the public certificate.
InstancePtr is a pointer to the XHdcp22_Rx core instance. PublicCertPtr is a pointer to an array. None.
References XHdcp22_Rx::PublicCertPtr.
int XHdcp22Rx_LoadPrivateKey(XHdcp22_Rx *InstancePtr, const u8 *PrivateKeyPtr)
This function is used to load the private key.
InstancePtr is a pointer to the XHdcp22_Rx core instance. PrivateKeyPtr is a pointer to an array. - XST_SUCCESS if MMULT keys are calculated correctly. XST_FAILURE if MMULT keys are not calculated correctly. None.
References XHdcp22_Rx::NPrimeP, XHdcp22_Rx::NPrimeQ, XHdcp22_Rx::PrivateKeyPtr, XHdcp22Rx_CalcMontNPrime.
u32 XHdcp22Rx_GetVersion(XHdcp22_Rx *InstancePtr)
This function reads the version.
InstancePtr is a pointer to the XHdcp22_Rx core instance. Returns the version register of the cipher. None.
References XHdcp22_Rx::CipherInst.
XTmrCtr * XHdcp22Rx_GetTimer(XHdcp22_Rx *InstancePtr)
This function returns the pointer to the internal timer control instance needed for connecting the timer interrupt to an interrupt controller.
InstancePtr is a pointer to the XHdcp22_Rx core instance. A pointer to the internal timer control instance. None.
References XHdcp22_Rx::TimerInst.
void XHdcp22Rx_SetTopology(XHdcp22_Rx *InstancePtr, const XHdcp22_Rx_Topology *TopologyPtr)
This function copies a complete repeater topology table into the instance repeater topology table.
InstancePtr is a pointer to the XHdcp22_Rx core instance. TopologyPtr is a pointer to the repeater topology table. None.
References XHdcp22_Rx::Topology.
void XHdcp22Rx_SetTopologyReceiverIdList(XHdcp22_Rx *InstancePtr, const u8 *ListPtr, u32 ListSize)
This function copies the RECEIVER_ID_LIST into the repeater topology table.
Receiver ID list is constructed by appending Receiver IDs in big-endian order. InstancePtr is a pointer to the XHdcp22_Rx core instance. ListPtr is a pointer to the Receiver ID list. The list consists of a contiguous set of bytes stored in big-endian order, with each Receiver ID occuping five bytes with a maximum of 31 Receiver IDs. ListSize is the number of Receiver IDs in the list. The list size cannot exceed 31 devices. None.
References XHdcp22_Rx_Topology::ReceiverIdList, XHdcp22_Rx::Topology.
void XHdcp22Rx_SetTopologyField(XHdcp22_Rx *InstancePtr, XHdcp22_Rx_TopologyField Field, u8 Value)
This function is used to set various fields inside the topology structure.
InstancePtr is a pointer to the XHdcp22_Rx core instance. Field indicates what field of the topology structure to update. Value is the value assigned to the field of the topology structure. None.
void XHdcp22Rx_SetTopologyUpdate(XHdcp22_Rx *InstancePtr)
This function is used to indicate that the topology table has been updated and is ready for upstream propagation.
Before calling this function ensure that all the fields in the repeater topology table have been updated. InstancePtr is a pointer to the XHdcp22_Rx core instance. None.
References XHdcp22_Rx::Info, XHdcp22_Rx_Info::IsTopologyValid, XHDCP22_RX_LOG_EVT_INFO, XHDCP22_RX_LOG_INFO_TOPOLOGY_UPDATE, XHdcp22Rx_LogWr.
u8 XHdcp22Rx_GetContentStreamType(XHdcp22_Rx *InstancePtr)
This function is gets the type information received from the RepeaterAuth_Stream_Manage message for downstream propagation of management information.
This function should be called only after the RepeaterAuth_Stream_Manage message has been received, and can be called inside the user callback function type XHDCP22_RX_HANDLER_STREAM_MANAGE_REQUEST. InstancePtr is a pointer to the XHdcp22_Rx core instance. - 0x00: Type 0 Content Stream. May be transmitted by the HDCP Repeater to all HDCP Devices. 0x01: Type 1 Content Stream. Must not be transmitted by the HDCP Repeater to HDCP 1.x-compliant Devices and HDCP 2.1-compliant Devices.0x02-0xFF: Reserved for future use only. Content Streams with reserved Type values must be treated similar to Type 1 Content Streams. None.
References XHdcp22_Rx::Params.
Referenced by XHdcp22Rx_Info.
void XHdcp22Rx_LogReset(XHdcp22_Rx *InstancePtr, u8 Verbose)
This function clears the log pointers.
InstancePtr is a pointer to the XHdcp22_Rx core instance. Verbose allows to add debug logging. None.
References XHdcp22_Rx_Log::Head, XHdcp22_Rx::Log, XHdcp22_Rx_Log::Tail, XHdcp22_Rx::TimerInst, XHdcp22_Rx_Log::Verbose.
Referenced by XHdcp22Rx_CfgInitialize.
u32 XHdcp22Rx_LogGetTimeUSecs(XHdcp22_Rx *InstancePtr)
This function returns the time expired since a log reset was called.
InstancePtr is a pointer to the XHdcp22_Rx core instance. The expired logging time in useconds. None.
References XHdcp22_Rx::TimerInst.
Referenced by XHdcp22Rx_LogWr.
void XHdcp22Rx_LogWr(XHdcp22_Rx *InstancePtr, u16 Evt, u16 Data)
This function writes HDCP22-RX log event into buffer.
If the log event is of type error, the sticky error flag is set. The sticky error flag is used to keep history of error conditions. InstancePtr is a pointer to the XHdcp22_Rx core instance. Evt specifies an action to be carried out. Data specifies the information that gets written into log buffer. None.
References XHdcp22_Rx_LogItem::Data, XHdcp22_Rx_Info::ErrorFlagSticky, XHdcp22_Rx_Log::Head, XHdcp22_Rx::Info, XHdcp22_Rx::Log, XHdcp22_Rx_LogItem::LogEvent, XHdcp22_Rx_Log::LogItems, XHdcp22_Rx_Log::Tail, XHdcp22_Rx_LogItem::TimeStamp, XHdcp22_Rx_Log::Verbose, XHDCP22_RX_LOG_BUFFER_SIZE, XHDCP22_RX_LOG_EVT_DEBUG, XHDCP22_RX_LOG_EVT_ERROR, XHDCP22_RX_LOG_EVT_INFO_MESSAGE, XHDCP22_RX_LOG_EVT_INVALID, XHdcp22Rx_LogGetTimeUSecs.
Referenced by XHdcp22Rx_Disable, XHdcp22Rx_Enable, XHdcp22Rx_Poll, XHdcp22Rx_Reset, XHdcp22Rx_RsaesOaepDecrypt, XHdcp22Rx_SetDdcError, XHdcp22Rx_SetLinkError, XHdcp22Rx_SetReadMessageComplete, XHdcp22Rx_SetTopologyUpdate, XHdcp22Rx_SetWriteMessageAvailable.
XHdcp22_Rx_LogItem * XHdcp22Rx_LogRd(XHdcp22_Rx *InstancePtr)
This function provides the log information from the log buffer.
InstancePtr is a pointer to the XHdcp22_Rx core instance. Content of log buffer if log pointers are not equal.Otherwise Zero. None.
References XHdcp22_Rx_LogItem::Data, XHdcp22_Rx_Log::Head, XHdcp22_Rx::Log, XHdcp22_Rx_LogItem::LogEvent, XHdcp22_Rx_Log::LogItems, XHdcp22_Rx_Log::Tail, XHdcp22_Rx_LogItem::TimeStamp, XHDCP22_RX_LOG_BUFFER_SIZE.
Referenced by XHdcp22Rx_LogDisplay.
void XHdcp22Rx_LogDisplay(XHdcp22_Rx *InstancePtr)
This function prints the contents of the log buffer.
InstancePtr is a pointer to the XHdcp22_Rx core instance. None.
References XHdcp22_Rx_LogItem::Data, XHdcp22_Rx_LogItem::LogEvent, XHdcp22_Rx_LogItem::TimeStamp, XHDCP22_RX_ERROR_FLAG_DDC_BURST, XHDCP22_RX_ERROR_FLAG_EMPTY_REPEATER_TOPOLOGY, XHDCP22_RX_ERROR_FLAG_FORCE_RESET, XHDCP22_RX_ERROR_FLAG_LINK_INTEGRITY, XHDCP22_RX_ERROR_FLAG_MAX_LCINIT_ATTEMPTS, XHDCP22_RX_ERROR_FLAG_MAX_REPEATER_TOPOLOGY, XHDCP22_RX_ERROR_FLAG_MESSAGE_SIZE, XHDCP22_RX_ERROR_FLAG_PROCESSING_AKEINIT, XHDCP22_RX_ERROR_FLAG_PROCESSING_AKENOSTOREDKM, XHDCP22_RX_ERROR_FLAG_PROCESSING_AKESTOREDKM, XHDCP22_RX_ERROR_FLAG_PROCESSING_LCINIT, XHDCP22_RX_ERROR_FLAG_PROCESSING_REPEATERAUTHSENDACK, XHDCP22_RX_ERROR_FLAG_PROCESSING_REPEATERAUTHSTREAMMANAGE, XHDCP22_RX_ERROR_FLAG_PROCESSING_SKESENDEKS, XHDCP22_RX_LOG_DEBUG_COMPUTE_EKH, XHDCP22_RX_LOG_DEBUG_COMPUTE_EKH_DONE, XHDCP22_RX_LOG_DEBUG_COMPUTE_HPRIME, XHDCP22_RX_LOG_DEBUG_COMPUTE_HPRIME_DONE, XHDCP22_RX_LOG_DEBUG_COMPUTE_KM, XHDCP22_RX_LOG_DEBUG_COMPUTE_KM_DONE, XHDCP22_RX_LOG_DEBUG_COMPUTE_KS, XHDCP22_RX_LOG_DEBUG_COMPUTE_KS_DONE, XHDCP22_RX_LOG_DEBUG_COMPUTE_LPRIME, XHDCP22_RX_LOG_DEBUG_COMPUTE_LPRIME_DONE, XHDCP22_RX_LOG_DEBUG_COMPUTE_MPRIME, XHDCP22_RX_LOG_DEBUG_COMPUTE_MPRIME_DONE, XHDCP22_RX_LOG_DEBUG_COMPUTE_RSA, XHDCP22_RX_LOG_DEBUG_COMPUTE_RSA_DONE, XHDCP22_RX_LOG_DEBUG_COMPUTE_VPRIME, XHDCP22_RX_LOG_DEBUG_COMPUTE_VPRIME_DONE, XHDCP22_RX_LOG_DEBUG_READ_MESSAGE_COMPLETE, XHDCP22_RX_LOG_DEBUG_TIMER_EXPIRED, XHDCP22_RX_LOG_DEBUG_TIMER_START, XHDCP22_RX_LOG_DEBUG_WRITE_MESSAGE_AVAILABLE, XHDCP22_RX_LOG_EVT_DEBUG, XHDCP22_RX_LOG_EVT_ERROR, XHDCP22_RX_LOG_EVT_INFO, XHDCP22_RX_LOG_EVT_INFO_MESSAGE, XHDCP22_RX_LOG_EVT_INFO_STATE, XHDCP22_RX_LOG_EVT_USER, XHDCP22_RX_LOG_INFO_DISABLE, XHDCP22_RX_LOG_INFO_ENABLE, XHDCP22_RX_LOG_INFO_ENCRYPTION_ENABLE, XHDCP22_RX_LOG_INFO_REQAUTH_REQ, XHDCP22_RX_LOG_INFO_RESET, XHDCP22_RX_LOG_INFO_TOPOLOGY_UPDATE, XHDCP22_RX_MSG_ID_AKEINIT, XHDCP22_RX_MSG_ID_AKENOSTOREDKM, XHDCP22_RX_MSG_ID_AKESENDCERT, XHDCP22_RX_MSG_ID_AKESENDHPRIME, XHDCP22_RX_MSG_ID_AKESENDPAIRINGINFO, XHDCP22_RX_MSG_ID_AKESTOREDKM, XHDCP22_RX_MSG_ID_LCINIT, XHDCP22_RX_MSG_ID_LCSENDLPRIME, XHDCP22_RX_MSG_ID_REPEATERAUTHSENDACK, XHDCP22_RX_MSG_ID_REPEATERAUTHSENDRXIDLIST, XHDCP22_RX_MSG_ID_REPEATERAUTHSTREAMMANAGE, XHDCP22_RX_MSG_ID_REPEATERAUTHSTREAMREADY, XHDCP22_RX_MSG_ID_SKESENDEKS, XHDCP22_RX_STATE_B0_WAIT_AKEINIT, XHDCP22_RX_STATE_B1_SEND_AKESENDCERT, XHDCP22_RX_STATE_B1_SEND_AKESENDHPRIME, XHDCP22_RX_STATE_B1_SEND_AKESENDPAIRINGINFO, XHDCP22_RX_STATE_B1_WAIT_AKEKM, XHDCP22_RX_STATE_B1_WAIT_LCINIT, XHDCP22_RX_STATE_B2_SEND_LCSENDLPRIME, XHDCP22_RX_STATE_B2_WAIT_SKESENDEKS, XHDCP22_RX_STATE_B3_COMPUTE_KS, XHDCP22_RX_STATE_B4_AUTHENTICATED, XHDCP22_RX_STATE_C4_WAIT_FOR_DOWNSTREAM, XHDCP22_RX_STATE_C5_SEND_RECEIVERIDLIST, XHDCP22_RX_STATE_C5_SEND_RECEIVERIDLIST_DONE, XHDCP22_RX_STATE_C6_VERIFY_RECEIVERIDLISTACK, XHDCP22_RX_STATE_C7_SEND_STREAM_READY, XHDCP22_RX_STATE_C7_SEND_STREAM_READY_DONE, XHDCP22_RX_STATE_C7_WAIT_STREAM_MANAGEMENT, XHDCP22_RX_STATE_C8_AUTHENTICATED, XHdcp22Rx_LogRd.
void XHdcp22Rx_Info(XHdcp22_Rx *InstancePtr)
This function prints the state machine information.
InstancePtr is a pointer to the XHdcp22_Rx core instance. None.
References XHdcp22_Rx_Info::AuthenticationStatus, XHdcp22_Rx_Info::AuthRequestCnt, XHdcp22_Rx_Info::DdcErrorCnt, XHdcp22_Rx_Topology::Depth, XHdcp22_Rx_Topology::DeviceCnt, XHdcp22_Rx_Topology::Hdcp1DeviceDownstream, XHdcp22_Rx_Topology::Hdcp2LegacyDeviceDownstream, XHdcp22_Rx::Info, XHdcp22_Rx_Info::LinkErrorCnt, XHdcp22_Rx_Topology::MaxCascadeExceeded, XHdcp22_Rx_Topology::MaxDevsExceeded, XHdcp22_Rx_Info::ReauthRequestCnt, XHdcp22_Rx::Topology, XHDCP22_RX_AUTHENTICATED, XHDCP22_RX_AUTHENTICATION_BUSY, XHDCP22_RX_REAUTHENTICATE_REQUESTED, XHDCP22_RX_UNAUTHENTICATED, XHdcp22Rx_GetContentStreamType, XHdcp22Rx_IsEnabled, XHdcp22Rx_IsEncryptionEnabled, XHdcp22Rx_IsRepeater.
XHdcp22_Rx_Config * XHdcp22Rx_LookupConfig(UINTPTR BaseAddress)
This function returns a reference to an XHdcp22_Rx_Config structure based on the core id, DeviceId.
The return value will refer to an entry in the device configuration table defined in the xhdcp22_rx_g.c file. DeviceId is the unique core ID of the HDCP RX core for the lookup operation. XHdcp22Rx_LookupConfig returns a reference to a config record in the configuration table (in xhdmi_tx_g.c) corresponding to DeviceId, or NULL if no match is found. None.
static int XHdcp22Rx_Pkcs1Rsaep(const XHdcp22_Rx_KpubRx *KpubRx, u8 *Message, u8 *EncryptedMessage)
This function implements the RSAEP primitive.
Reference: PKCS#1 v2.1, Section 5.1.1 KpubRx is the RSA public key structure containing the 1024 bit modulus and 24 bit public exponent. Message is the 128 byte octet string to be encrypted. EncryptedMessage is the 128 byte octet string after encryption. XST_SUCCESS or XST_FAILURE. None.
static int XHdcp22Rx_Pkcs1Rsadp(XHdcp22_Rx *InstancePtr, const XHdcp22_Rx_KprivRx *KprivRx, u8 *EncryptedMessage, u8 *Message)
This function implements the RSADP primitive using the Chinese Remainder Theorem (CRT).
Reference: PKCS#1 v2.1, Section 5.1.2 InstancePtr is a pointer to the MMULT instance. KprivRx is the RSA private key structure containing the quintuple. EncryptedMessage is the 128 byte octet string to be decrypted. Message is the 128 byte decrypted octet string. XST_SUCCESS or XST_FAILURE. None.
static int XHdcp22Rx_Pkcs1Mgf1(const u8 *Seed, const u32 SeedLen, u8 *Mask, u32 MaskLen)
This function implements the Mask Generation Function MGF1.
The underlying hash function used is SHA256.Reference: PKCS#1 v2.1, Section B.2.1 Seed is the octet string from which the mask is generated. SeedLen is the length of the seed in octet string. Mask is the output octet string after MGF1. MaskLen is the desired length of the mask with a length less than or equal to 128 bytes. XST_SUCCESS or XST_FAILURE. None.
static int XHdcp22Rx_Pkcs1EmeOaepEncode(const u8 *Message, const u32 MessageLen, const u8 *MaskingSeed, u8 *EncodedMessage)
This function implements EME-OAEP encoding.
The label L is the empty string and the underlying hash function is SHA256.Reference: PKCS#1 v2.1, Section 7.1.1, Part 2 Message is the octet string to be encoded MessageLen is the length of the octet string to be encoded. MaskingSeed is the random octet string seed of length hLen. EncodedMessage is the 128 byte encoded octet string. XST_SUCCESS or XST_FAILURE. None.
static int XHdcp22Rx_Pkcs1EmeOaepDecode(u8 *EncodedMessage, u8 *Message, int *MessageLen)
This function implements EME-OAEP decoding.
The label L is the empty string and the underlying hash function is SHA256.Reference: PKCS#1 v2.1, Section 7.1.2, Part 3 EncodedMessage is the 128 byte encoded octet string. Message is decoded octet string. MessageLen is the length of the decoded octet string. XST_SUCCESS or XST_FAILURE. None.
static void XHdcp22Rx_Pkcs1MontMultFiosInit(XHdcp22_Rx *InstancePtr, u32 *N, const u32 *NPrime, int NDigits)
This function initializes the Montgomery Multiplier (MMULT) hardware by writing the N and NPrime registers.
U = MontMult(A,B,N)Reference: Analyzing and Comparing Montgomery Multiplication Algorithms IEEE Micro, 16(3):26-33,June 1996 By: Cetin Koc, Tolga Acar, and Burton Kaliski InstancePtr is a pointer to the MMULT instance. N is the modulus NPrime is a pre-computed constant, NPrime = (1-R*Rbar)/N NDigits is the integer precision of the arguments (C,A,B,N,NPrime) None. None.
static void XHdcp22Rx_Pkcs1MontMultFios(XHdcp22_Rx *InstancePtr, u32 *U, u32 *A, u32 *B, int NDigits)
This function runs the Montgomery Multiplier (MMULT) hardware to perform the modular multiplication operation required by RSA decryption.
U = MontMult(A,B,N) InstancePtr is a pointer to the MMULT instance. U is the MMM result A is the n-residue input, A' = A*R mod N B is the n-residue input, B' = B*R mod N NDigits is the integer precision of the arguments (C,A,B,N,NPrime) None. None.
static int XHdcp22Rx_Pkcs1MontExp(XHdcp22_Rx *InstancePtr, u32 *C, u32 *A, u32 *E, u32 *N, const u32 *NPrime, int NDigits)
This function performs the modular exponentiation operation using the binary square and multiply method.
C = ModExp(A, E, N) = A^E*mod(N) C is result of the modular exponentiation A is the base E is the exponent N is the modulus NPrime is a constant NDigits is the integer precision of the arguments (C,A,B,N,NPrime). Maximum integer precision is 16. None. None.
static void XHdcp22Rx_ComputeDKey(const u8 *Rrx, const u8 *Rtx, const u8 *Km, const u8 *Rn, u8 *Ctr, u8 *DKey)
This function computes the derived keys used during HDCP 2.2 authentication and key exchange.
Reference: HDCP v2.2, section 2.7 Rrx is the Rx random generated value. Rtx is the Tx random generated value. Km is the master key generated by tx. Rn is the 64-bit psuedo-random nonce generated by the transmitter. Ctr is the 64-bit AES counter value. DKey is the 128-bit derived key. None. None.
static void XHdcp22Rx_Xor(u8 *Cout, const u8 *Ain, const u8 *Bin, u32 Len)
This function calculates XOR for any array.
Cout is the XOR of the input arrays. Ain is the input byte array. Bin is the input byte array. Len is the length of the arrays in bytes. None. None.
int XHdcp22Rx_CalcMontNPrime(u8 *NPrime, const u8 *N, int NDigits)
This function is used to calculate the Montgomery NPrime.
NPrime is calculated from the following equation R*Rinv - N*NPrime == 1. For the HDCP2.2 receiver the modulus N has a fixed size of k = 512bits. Given k, the value R = 2^(k), and Rinv is the modular inverse of R.Reference: Analyzing and Comparing Montgomery Multiplication Algorithms IEEE Micro, 16(3):26-33,June 1996 By: Cetin Koc, Tolga Acar, and Burton Kaliski NPrime is the calculated value and 2*NDigits in Size. N is modulus NDigits is the integer precision of arguments (N, NPrime), which should always be 16 for the HDCP2.2 receiver. XST_SUCCESS or FAILURE. None.
Referenced by XHdcp22Rx_LoadPrivateKey.
int XHdcp22Rx_RsaesOaepEncrypt(const XHdcp22_Rx_KpubRx *KpubRx, const u8 *Message, const u32 MessageLen, const u8 *MaskingSeed, u8 *EncryptedMessage)
This function implements the RSAES-OAEP-Encrypt operation.
The message is encoded using EME-OAEP and then encrypted with the public key using RSAEP.Reference: PKCS#1 v2.1, Section 7.1.1 KpubRx is the RSA public key structure containing the 1024 bit modulus and 24 bit public exponent. Message is the octet string to be encrypted. MessageLen is the length of octet string to be encrypted and must be less than or equal to (nLen - 2*hLen - 2) MaskingSeed is the random octet string seed of length hLen used by EME-OAEP encoding function. EncryptedMessage is the output octet string after encryption. XST_SUCCESS or XST_FAILURE. None.
int XHdcp22Rx_RsaesOaepDecrypt(XHdcp22_Rx *InstancePtr, const XHdcp22_Rx_KprivRx *KprivRx, u8 *EncryptedMessage, u8 *Message, int *MessageLen)
This function implements the RSAES-OAEP-Decrypt operation.
The message is decrypted using RSADP and then decoded using EME-OAEP.Reference: PKCS#1 v2.1, Section 7.1.2 InstancePtr is a pointer to the MMULT instance. KprivRx is the RSA private key structure containing the quintuple. EncryptedMessage is the 128 byte octet string to be decrypted. Message is the octet string after decryption. MessageLen is the length of the message octet string after decryption. XST_SUCCESS or XST_FAILURE. None.
References XHDCP22_RX_LOG_DEBUG_COMPUTE_RSA, XHDCP22_RX_LOG_DEBUG_COMPUTE_RSA_DONE, XHDCP22_RX_LOG_EVT_DEBUG, XHdcp22Rx_LogWr.
void XHdcp22Rx_GenerateRandom(XHdcp22_Rx *InstancePtr, int NumOctets, u8 *RandomNumberPtr)
This function generates random octets.
InstancePtr is a pointer to the XHdcp22_Rx core instance. NumOctets is the number of octets in the random number. RandomNumberPtr is a pointer to the random number. None.
References XHdcp22_Rx::RngInst.
void XHdcp22Rx_ComputeHPrime(const u8 *Rrx, const u8 *RxCaps, const u8 *Rtx, const u8 *TxCaps, const u8 *Km, u8 *HPrime)
This function computes HPrime used during HDCP 2.2 authentication and key exchange.
Reference: HDCP v2.2, section 2.2 Rrx is the Rx random generated value. RxCaps are the capabilities of the receiver. Rtx is the Tx random generated value. TxCaps are the capabilities of the receiver. Km is the master key generated by tx. HPrime is a pointer to the HPrime hash from the HDCP2.2 receiver. None.
void XHdcp22Rx_ComputeEkh(const u8 *KprivRx, const u8 *Km, const u8 *M, u8 *Ekh)
This function computes Ekh used during HDCP 2.2 authentication and key exchange for pairing with receiver.
Reference: HDCP v2.2, section 2.2.1 KprivRx is the RSA private key structure containing the quintuple. Km is the master key generated by tx. M is constructed by concatenating Rtx || Rrx. Ekh is the encrypted Km used for pairing. None.
void XHdcp22Rx_ComputeLPrime(const u8 *Rn, const u8 *Km, const u8 *Rrx, const u8 *Rtx, u8 *LPrime)
This function computes LPrime used during HDCP 2.2 locality check.
Reference: HDCP v2.2, section 2.3 Rn is the 64-bit psuedo-random nonce generated by the transmitter. Km is the 128-bit master key generated by tx. Rrx is the 64-bit pseudo-random number generated by the receiver. Rtx is the 64-bit pseudo-random number generated by the transmitter. LPrime is the 256-bit value generated for locality check. None.
void XHdcp22Rx_ComputeKs(const u8 *Rrx, const u8 *Rtx, const u8 *Km, const u8 *Rn, const u8 *Eks, u8 *Ks)
This function computes the Ks used during HDCP 2.2 session key exchange.
Reference: HDCP v2.2, section 2.4 Rrx is the Rx random generated value. Rtx is the Tx random generated value. Km is the master key generated by the transmitter. Rn is the 64-bit psuedo-random nonce generated by the transmitter. Eks is the encrypted session generated by the transmitter. Ks is the decrypted session key. None.
void XHdcp22Rx_ComputeVPrime(const u8 *ReceiverIdList, u32 ReceiverIdListSize, const u8 *RxInfo, const u8 *SeqNumV, const u8 *Km, const u8 *Rrx, const u8 *Rtx, u8 *VPrime)
This function computes VPrime used during HDCP 2.2 repeater authentication.
Reference: HDCP v2.2, section 2.3 ReceiverIdList is a list of downstream receivers IDs in big-endian order. Each receiver ID is 5 Bytes. ReceiverIdListSize is the number of receiver Ids in ReceiverIdList. There can be between 1 and 31 devices in the list. RxInfo is the 16-bit field in the RepeaterAuth_Send_ReceiverID_List message. SeqNumV is the 24-bit field in the RepeaterAuth_Send_ReceiverID_List Km is the 128-bit master key generated by tx. Rrx is the 64-bit pseudo-random number generated by the receiver. Rtx is the 64-bit pseudo-random number generated by the transmitter. VPrime is the 256-bit value generated for repeater authentication. None.
void XHdcp22Rx_ComputeMPrime(const u8 *StreamIdType, const u8 *SeqNumM, const u8 *Km, const u8 *Rrx, const u8 *Rtx, u8 *MPrime)
This function computes VPrime used during HDCP 2.2 repeater authentication.
Reference: HDCP v2.2, section 2.3 StreamIdType is the 16-bit field in the RepeaterAuth_Send_ReceiverID_List message. SeqNumM is the 24-bit field in the RepeaterAuth_Stream_Manage message. Km is the 128-bit master key generated by tx. Rrx is the 64-bit pseudo-random number generated by the receiver. Rtx is the 64-bit pseudo-random number generated by the transmitter. MPrime is the 256-bit value generated for repeater stream management ready. None.
XHDCP22_RX_H
XHDCP22_RX_MAX_MESSAGE_SIZE
Maximum message size.
XHDCP22_RX_LOG_BUFFER_SIZE
The size of the log buffer.
Referenced by XHdcp22Rx_LogRd, XHdcp22Rx_LogWr.
XHDCP22_RX_ENCRYPTION_STATUS_INTERVAL
1sec encryption status check interval
XHDCP22_RX_REPEATERAUTH_ACK_INTERVAL
2sec RepeaterAuth Ack interval
XHdcp22Rx_MpSizeof
XHDCP22_RX_I_H_
XHDCP22_RX_HASH_SIZE
XHDCP22_RX_N_SIZE
XHDCP22_RX_P_SIZE
XHDCP22_RX_KM_SIZE
XHDCP22_RX_EKH_SIZE
XHDCP22_RX_KD_SIZE
XHDCP22_RX_HPRIME_SIZE
XHDCP22_RX_LPRIME_SIZE
XHDCP22_RX_RN_SIZE
XHDCP22_RX_RIV_SIZE
XHDCP22_RX_KS_SIZE
XHDCP22_RX_AES_SIZE
XHDCP22_RX_RTX_SIZE
XHDCP22_RX_RRX_SIZE
XHDCP22_RX_TXCAPS_SIZE
XHDCP22_RX_RXCAPS_SIZE
XHDCP22_RX_CERT_SIZE
XHDCP22_RX_PRIVATEKEY_SIZE
XHDCP22_RX_LC128_SIZE
XHDCP22_RX_RCVID_SIZE
XHDCP22_RX_SEQNUMV_SIZE
XHDCP22_RX_RXINFO_SIZE
XHDCP22_RX_VPRIME_SIZE
XHDCP22_RX_SEQNUMM_SIZE
XHDCP22_RX_MPRIME_SIZE
XHDCP22_RX_STREAMID_SIZE
XHDCP22_RX_MAX_SEQNUMV
XHDCP22_RX_MAX_LCINIT
XHDCP22_RX_MAX_DEVICE_COUNT
XHDCP22_RX_MAX_DEPTH
XHDCP22_RX_DDC_VERSION_REG
XHDCP22_RX_DDC_WRITE_REG
XHDCP22_RX_DDC_RXSTATUS0_REG
XHDCP22_RX_DDC_RXSTATUS1_REG
XHDCP22_RX_DDC_READ_REG
XHDCP22_RX_TMR_CTR_0
XHDCP22_RX_TMR_CTR_1
XHDCP22_RX_TEST_DDC_REGMAP_SIZE
XPAR_XHDCP22_RX_NUM_INSTANCES