xhdcp22_rx.h
XHDCP22_RX_H
XHDCP22_RX_MAX_MESSAGE_SIZE
Maximum message size.
XHDCP22_RX_LOG_BUFFER_SIZE
The size of the log buffer.
Referenced by XHdcp22Rx_LogRd, XHdcp22Rx_LogWr.
XHDCP22_RX_ENCRYPTION_STATUS_INTERVAL
1sec encryption status check interval
XHDCP22_RX_REPEATERAUTH_ACK_INTERVAL
2sec RepeaterAuth Ack interval
XHdcp22_Rx_Protocol
HDCP22 over HDMI.
XHdcp22_Rx_Mode
HDCP22 receiver.
XHdcp22_Rx_HandlerType
Undefined.
XHdcp22_Rx_StateType
Undefined.
XHdcp22_Rx_AuthenticationType
Unauthenticated.
XHdcp22_Rx_LogEvt
XHdcp22_Rx_TopologyField
typedef void*(* XHdcp22_Rx_StateFunc)(void *InstancePtr))(void *InstancePtr)
Type for pointer to state function.
typedef void(* XHdcp22_Rx_RunHandler)(void *HandlerRef))(void *HandlerRef)
Type for pointer to single input function.
typedef void(* XHdcp22_Rx_SetHandler)(void *HandlerRef, u32 Data))(void *HandlerRef, u32 Data)
Type for pointer to two input function.
typedef u32(* XHdcp22_Rx_GetHandler)(void *HandlerRef))(void *HandlerRef)
Type for pointer to single input function with a return value.
XHdcp22_Rx_Config * XHdcp22Rx_LookupConfig(UINTPTR BaseAddress)
This function returns a reference to an XHdcp22_Rx_Config structure based on the core id, DeviceId.
The return value will refer to an entry in the device configuration table defined in the xhdcp22_rx_g.c file. DeviceId is the unique core ID of the HDCP RX core for the lookup operation. XHdcp22Rx_LookupConfig returns a reference to a config record in the configuration table (in xhdmi_tx_g.c) corresponding to DeviceId, or NULL if no match is found. None.
int XHdcp22Rx_CfgInitialize(XHdcp22_Rx *InstancePtr, XHdcp22_Rx_Config *ConfigPtr, UINTPTR EffectiveAddr)
Initialize the instance provided by the caller based on the given configuration data.
InstancePtr is a pointer to an XHdcp22_Rx instance. The memory the pointer references must be pre-allocated by the caller. Further calls to manipulate the driver through the HDCP22-RX API must be made with this pointer. ConfigPtr is a reference to a structure containing information about a specific HDCP22-RX device. This function initializes an InstancePtr object for a specific device specified by the contents of Config. This function can initialize multiple instance objects with the use of multiple calls giving different Config information on each call. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS or XST_FAILURE. None.
References XHdcp22_Rx_Handles::AuthenticatedCallback, XHdcp22_Rx_Handles::AuthenticationRequestCallback, XHdcp22_Rx_Info::AuthenticationStatus, XHdcp22_Rx_Info::AuthRequestCnt, XHdcp22_Rx_Config::BaseAddress, XHdcp22_Rx::Config, XHdcp22_Rx_Info::CurrentState, XHdcp22_Rx_Handles::DdcClearReadBufferCallback, XHdcp22_Rx_Handles::DdcClearWriteBufferCallback, XHdcp22_Rx_Info::DdcErrorCnt, XHdcp22_Rx_Handles::DdcGetDataCallback, XHdcp22_Rx_Handles::DdcGetReadBufferSizeCallback, XHdcp22_Rx_Handles::DdcGetWriteBufferSizeCallback, XHdcp22_Rx_Handles::DdcIsReadBufferEmptyCallback, XHdcp22_Rx_Handles::DdcIsWriteBufferEmptyCallback, XHdcp22_Rx_Handles::DdcSetAddressCallback, XHdcp22_Rx_Handles::DdcSetDataCallback, XHdcp22_Rx_Info::ErrorFlag, XHdcp22_Rx_Info::ErrorFlagSticky, XHdcp22_Rx::Handles, XHdcp22_Rx_Info::HasStreamManagementInfo, XHdcp22_Rx::Info, XHdcp22_Rx_Handles::IsAuthenticatedCallbackSet, XHdcp22_Rx_Handles::IsAuthenticationRequestCallbackSet, XHdcp22_Rx_Handles::IsDdcAllCallbacksSet, XHdcp22_Rx_Handles::IsDdcClearReadBufferCallbackSet, XHdcp22_Rx_Handles::IsDdcClearWriteBufferCallbackSet, XHdcp22_Rx_Handles::IsDdcGetDataCallbackSet, XHdcp22_Rx_Handles::IsDdcGetReadBufferSizeCallbackRefSet, XHdcp22_Rx_Handles::IsDdcGetWriteBufferSizeCallbackSet, XHdcp22_Rx_Handles::IsDdcIsReadBufferEmptyCallbackSet, XHdcp22_Rx_Handles::IsDdcIsWriteBufferEmptyCallbackSet, XHdcp22_Rx_Handles::IsDdcSetAddressCallbackSet, XHdcp22_Rx_Handles::IsDdcSetDataCallbackSet, XHdcp22_Rx_Info::IsEnabled, XHdcp22_Rx_Info::IsEncrypted, XHdcp22_Rx_Info::IsNoStoredKm, XHdcp22_Rx::IsReady, XHdcp22_Rx_Handles::IsStreamManageRequestCallbackSet, XHdcp22_Rx_Handles::IsTopologyUpdateCallbackSet, XHdcp22_Rx_Info::IsTopologyValid, XHdcp22_Rx_Info::LCInitAttempts, XHdcp22_Rx_Info::LinkErrorCnt, XHdcp22_Rx_Config::Mode, XHdcp22_Rx_Info::NextState, XHdcp22_Rx_Info::ReauthReq, XHdcp22_Rx_Info::ReauthRequestCnt, XHdcp22_Rx_Info::ReturnState, XHdcp22_Rx::RxCaps, XHdcp22_Rx_Info::SeqNumV, XHdcp22_Rx_Info::SkipRead, XHdcp22_Rx::StateFunc, XHdcp22_Rx_Handles::StreamManageRequestCallback, XHdcp22_Rx_Info::TopologyReady, XHdcp22_Rx_Handles::TopologyUpdateCallback, XHDCP22_RX_ERROR_FLAG_NONE, XHDCP22_RX_RECEIVER, XHDCP22_RX_STATE_B0_WAIT_AKEINIT, XHDCP22_RX_STATE_UNDEFINED, XHDCP22_RX_UNAUTHENTICATED, XHdcp22Rx_LogReset.
int XHdcp22Rx_Enable(XHdcp22_Rx *InstancePtr)
This function enables the HDCP22-RX state machine.
The HDCP2Version register is set to active. InstancePtr is a pointer to the XHdcp22_Rx core instance. XST_SUCCESS or XST_FAILURE. Before enabling the state machine ensure that the instance has been initialized, DDC message handles have been assigned, and keys have been loaded.
References XHdcp22_Rx::CipherInst, XHdcp22_Rx::Handles, XHdcp22_Rx::Info, XHdcp22_Rx_Handles::IsDdcAllCallbacksSet, XHdcp22_Rx_Info::IsEnabled, XHdcp22_Rx::IsReady, XHdcp22_Rx::MmultInst, XHdcp22_Rx::PrivateKeyPtr, XHdcp22_Rx::PublicCertPtr, XHdcp22_Rx::RngInst, XHdcp22_Rx::TimerInst, XHDCP22_RX_LOG_EVT_INFO, XHDCP22_RX_LOG_INFO_ENABLE, XHdcp22Rx_LogWr.
int XHdcp22Rx_Disable(XHdcp22_Rx *InstancePtr)
This function disables the HDCP22-RX state machine.
The HDCP2Version register is cleared, and the ReauthReq bit is set in the RxStatus register to allow the transmitter to recover when it has already authenticated. Without setting the ReauthReq bit the transmitter will not know that HDCP 2.2 protocol has been disabled by the Receiver after it has already authenticated. InstancePtr is a pointer to the XHdcp22_Rx core instance. XST_SUCCESS or XST_FAILURE. The HDCP22-RX cipher is disabled.
References XHdcp22_Rx::CipherInst, XHdcp22_Rx::Info, XHdcp22_Rx_Info::IsEnabled, XHdcp22_Rx::RngInst, XHDCP22_RX_LOG_EVT_INFO, XHDCP22_RX_LOG_INFO_DISABLE, XHdcp22Rx_LogWr.
int XHdcp22Rx_Reset(XHdcp22_Rx *InstancePtr)
This function resets the HDCP22-RX system to the default state.
The HDCP22-RX DDC registers are set to their default value and the message buffer is reset. InstancePtr is a pointer to the XHdcp22_Rx core instance. XST_SUCCESS or XST_FAILURE. The DDC message handles must be assigned by the XHdcp22Rx_SetDdcHandles function prior to calling this reset function.
References XHdcp22_Rx_Info::AuthenticationStatus, XHdcp22_Rx_Info::AuthRequestCnt, XHdcp22_Rx::CipherInst, XHdcp22_Rx_Info::CurrentState, XHdcp22_Rx_Info::DdcErrorCnt, XHdcp22_Rx_Info::ErrorFlag, XHdcp22_Rx_Info::ErrorFlagSticky, XHdcp22_Rx::Handles, XHdcp22_Rx_Info::HasStreamManagementInfo, XHdcp22_Rx::Info, XHdcp22_Rx_Handles::IsDdcAllCallbacksSet, XHdcp22_Rx_Info::IsEncrypted, XHdcp22_Rx_Info::IsNoStoredKm, XHdcp22_Rx_Info::IsTopologyValid, XHdcp22_Rx_Handles::IsUnauthenticatedCallbackSet, XHdcp22_Rx_Info::LCInitAttempts, XHdcp22_Rx_Info::LinkErrorCnt, XHdcp22_Rx::MessageBuffer, XHdcp22_Rx::MessageSize, XHdcp22_Rx_Info::NextState, XHdcp22_Rx_Info::ReauthReq, XHdcp22_Rx_Info::ReauthRequestCnt, XHdcp22_Rx_Info::ReturnState, XHdcp22_Rx_Info::SeqNumV, XHdcp22_Rx_Info::SkipRead, XHdcp22_Rx::StateFunc, XHdcp22_Rx::Topology, XHdcp22_Rx_Info::TopologyReady, XHdcp22_Rx_Handles::UnauthenticatedCallback, XHdcp22_Rx_Handles::UnauthenticatedCallbackRef, XHDCP22_RX_AUTHENTICATED, XHDCP22_RX_ERROR_FLAG_NONE, XHDCP22_RX_LOG_EVT_INFO, XHDCP22_RX_LOG_INFO_RESET, XHDCP22_RX_STATE_B0_WAIT_AKEINIT, XHDCP22_RX_STATE_UNDEFINED, XHDCP22_RX_UNAUTHENTICATED, XHdcp22Rx_LogWr.
int XHdcp22Rx_Poll(XHdcp22_Rx *InstancePtr)
This function executes the HDCP22-RX state machine.
InstancePtr is a pointer to the XHdcp22_Rx core instance. None. State transitions are logged.
References XHdcp22_Rx_Info::AuthenticationStatus, XHdcp22_Rx_Info::CurrentState, XHdcp22_Rx::Info, XHdcp22_Rx_Info::IsEnabled, XHdcp22_Rx_Info::NextState, XHdcp22_Rx::StateFunc, XHDCP22_RX_LOG_EVT_INFO_STATE, XHdcp22Rx_LogWr.
int XHdcp22Rx_SetCallback(XHdcp22_Rx *InstancePtr, XHdcp22_Rx_HandlerType HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs callback functions for the given HandlerType:
HandlerType Callback Function Type ------------------------- --------------------------- (XHDCP22_RX_HANDLER_DDC_SETREGADDR) DdcSetAddressCallback (XHDCP22_RX_HANDLER_DDC_SETREGDATA) DdcSetDataCallback (XHDCP22_RX_HANDLER_DDC_GETREGDATA) DdcGetDataCallback (XHDCP22_RX_HANDLER_DDC_GETWBUFSIZE) DdcGetWriteBufferSizeCallback (XHDCP22_RX_HANDLER_DDC_GETRBUFSIZE) DdcGetReadBufferSizeCallback (XHDCP22_RX_HANDLER_DDC_ISWBUFEMPTY) DdcIsWriteBufferEmptyCallback (XHDCP22_RX_HANDLER_DDC_ISRBUFEMPTY) DdcIsReadBufferEmptyCallback (XHDCP22_RX_HANDLER_DDC_CLEARRBUF) DdcClearReadBufferCallback (XHDCP22_RX_HANDLER_DDC_CLEARWBUF) DdcClearWriteBufferCallback (XHDCP22_RX_HANDLER_AUTHENTICATED) AuthenticatedCallback (XHDCP22_RX_HANDLER_UNAUTHENTICATED) UnauthenticatedCallback (XHDCP22_RX_HANDLER_AUTHENTICATION_REQUEST) AuthenticationRequestCallback (XHDCP22_RX_HANDLER_STREAM_MANAGE_REQUEST) StreamManageRequestCallback (XHDCP22_RX_HANDLER_TOPOLOGY_UPDATE) TopologyUpdateCallback InstancePtr is a pointer to the HDMI RX core instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XHdcp22_Rx_Handles::AuthenticatedCallback, XHdcp22_Rx_Handles::AuthenticatedCallbackRef, XHdcp22_Rx_Handles::AuthenticationRequestCallback, XHdcp22_Rx_Handles::AuthenticationRequestCallbackRef, XHdcp22_Rx_Handles::DdcClearReadBufferCallback, XHdcp22_Rx_Handles::DdcClearReadBufferCallbackRef, XHdcp22_Rx_Handles::DdcClearWriteBufferCallback, XHdcp22_Rx_Handles::DdcClearWriteBufferCallbackRef, XHdcp22_Rx_Handles::DdcGetDataCallback, XHdcp22_Rx_Handles::DdcGetDataCallbackRef, XHdcp22_Rx_Handles::DdcGetReadBufferSizeCallback, XHdcp22_Rx_Handles::DdcGetReadBufferSizeCallbackRef, XHdcp22_Rx_Handles::DdcGetWriteBufferSizeCallback, XHdcp22_Rx_Handles::DdcGetWriteBufferSizeCallbackRef, XHdcp22_Rx_Handles::DdcIsReadBufferEmptyCallback, XHdcp22_Rx_Handles::DdcIsReadBufferEmptyCallbackRef, XHdcp22_Rx_Handles::DdcIsWriteBufferEmptyCallback, XHdcp22_Rx_Handles::DdcIsWriteBufferEmptyCallbackRef, XHdcp22_Rx_Handles::DdcSetAddressCallback, XHdcp22_Rx_Handles::DdcSetAddressCallbackRef, XHdcp22_Rx_Handles::DdcSetDataCallback, XHdcp22_Rx_Handles::DdcSetDataCallbackRef, XHdcp22_Rx_Handles::EncryptionStatusCallback, XHdcp22_Rx_Handles::EncryptionStatusCallbackRef, XHdcp22_Rx::Handles, XHdcp22_Rx_Handles::IsAuthenticatedCallbackSet, XHdcp22_Rx_Handles::IsAuthenticationRequestCallbackSet, XHdcp22_Rx_Handles::IsDdcAllCallbacksSet, XHdcp22_Rx_Handles::IsDdcClearReadBufferCallbackSet, XHdcp22_Rx_Handles::IsDdcClearWriteBufferCallbackSet, XHdcp22_Rx_Handles::IsDdcGetDataCallbackSet, XHdcp22_Rx_Handles::IsDdcGetReadBufferSizeCallbackRefSet, XHdcp22_Rx_Handles::IsDdcGetWriteBufferSizeCallbackSet, XHdcp22_Rx_Handles::IsDdcIsReadBufferEmptyCallbackSet, XHdcp22_Rx_Handles::IsDdcIsWriteBufferEmptyCallbackSet, XHdcp22_Rx_Handles::IsDdcSetAddressCallbackSet, XHdcp22_Rx_Handles::IsDdcSetDataCallbackSet, XHdcp22_Rx_Handles::IsEncryptionStatusCallbackSet, XHdcp22_Rx_Handles::IsStreamManageRequestCallbackSet, XHdcp22_Rx_Handles::IsTopologyUpdateCallbackSet, XHdcp22_Rx_Handles::IsUnauthenticatedCallbackSet, XHdcp22_Rx_Handles::StreamManageRequestCallback, XHdcp22_Rx_Handles::StreamManageRequestCallbackRef, XHdcp22_Rx_Handles::TopologyUpdateCallback, XHdcp22_Rx_Handles::TopologyUpdateCallbackRef, XHdcp22_Rx_Handles::UnauthenticatedCallback, XHdcp22_Rx_Handles::UnauthenticatedCallbackRef, XHDCP22_RX_HANDLER_AUTHENTICATED, XHDCP22_RX_HANDLER_AUTHENTICATION_REQUEST, XHDCP22_RX_HANDLER_DDC_CLEARRBUF, XHDCP22_RX_HANDLER_DDC_CLEARWBUF, XHDCP22_RX_HANDLER_DDC_GETRBUFSIZE, XHDCP22_RX_HANDLER_DDC_GETREGDATA, XHDCP22_RX_HANDLER_DDC_GETWBUFSIZE, XHDCP22_RX_HANDLER_DDC_ISRBUFEMPTY, XHDCP22_RX_HANDLER_DDC_ISWBUFEMPTY, XHDCP22_RX_HANDLER_DDC_SETREGADDR, XHDCP22_RX_HANDLER_DDC_SETREGDATA, XHDCP22_RX_HANDLER_ENCRYPTION_UPDATE, XHDCP22_RX_HANDLER_INVALID, XHDCP22_RX_HANDLER_STREAM_MANAGE_REQUEST, XHDCP22_RX_HANDLER_TOPOLOGY_UPDATE, XHDCP22_RX_HANDLER_UNAUTHENTICATED, XHDCP22_RX_HANDLER_UNDEFINED.
u32 XHdcp22Rx_GetVersion(XHdcp22_Rx *InstancePtr)
This function reads the version.
InstancePtr is a pointer to the XHdcp22_Rx core instance. Returns the version register of the cipher. None.
References XHdcp22_Rx::CipherInst.
XTmrCtr * XHdcp22Rx_GetTimer(XHdcp22_Rx *InstancePtr)
This function returns the pointer to the internal timer control instance needed for connecting the timer interrupt to an interrupt controller.
InstancePtr is a pointer to the XHdcp22_Rx core instance. A pointer to the internal timer control instance. None.
References XHdcp22_Rx::TimerInst.
void XHdcp22Rx_SetBroadcast(XHdcp22_Rx *InstancePtr, u8 enable)
u8 XHdcp22Rx_IsEnabled(XHdcp22_Rx *InstancePtr)
This function checks if the HDCP22-RX state machine is enabled.
InstancePtr is a pointer to the XHdcp22_Rx core instance. TRUE or FALSE. None.
References XHdcp22_Rx::Info, XHdcp22_Rx_Info::IsEnabled.
Referenced by XHdcp22Rx_Info.
u8 XHdcp22Rx_IsEncryptionEnabled(XHdcp22_Rx *InstancePtr)
This function checks if the HDCP22-RX cipher encryption is enabled.
InstancePtr is a pointer to the XHdcp22_Rx core instance. TRUE or FALSE. None.
References XHdcp22_Rx::CipherInst.
Referenced by XHdcp22Rx_Info.
u8 XHdcp22Rx_IsInProgress(XHdcp22_Rx *InstancePtr)
This function checks if the HDCP22-RX state machine is enabled but not yet in the Authenticated state.
InstancePtr is a pointer to the XHdcp22_Rx core instance. TRUE or FALSE. None.
References XHdcp22_Rx_Info::AuthenticationStatus, XHdcp22_Rx::Info, XHDCP22_RX_AUTHENTICATION_BUSY.
u8 XHdcp22Rx_IsAuthenticated(XHdcp22_Rx *InstancePtr)
This function checks if the HDCP22-RX state machine is in the Authenticated state.
InstancePtr is a pointer to the XHdcp22_Rx core instance. TRUE or FALSE. None.
References XHdcp22_Rx_Info::AuthenticationStatus, XHdcp22_Rx::Info, XHDCP22_RX_AUTHENTICATED.
u8 XHdcp22Rx_IsError(XHdcp22_Rx *InstancePtr)
This function checks if the HDCP22-RX state machine has detected an error condition.
InstancePtr is a pointer to the XHdcp22_Rx core instance. TRUE or FALSE. None.
References XHdcp22_Rx_Info::ErrorFlagSticky, XHdcp22_Rx::Info, XHDCP22_RX_ERROR_FLAG_NONE.
void XHdcp22Rx_Info(XHdcp22_Rx *InstancePtr)
This function prints the state machine information.
InstancePtr is a pointer to the XHdcp22_Rx core instance. None.
References XHdcp22_Rx_Info::AuthenticationStatus, XHdcp22_Rx_Info::AuthRequestCnt, XHdcp22_Rx_Info::DdcErrorCnt, XHdcp22_Rx_Topology::Depth, XHdcp22_Rx_Topology::DeviceCnt, XHdcp22_Rx_Topology::Hdcp1DeviceDownstream, XHdcp22_Rx_Topology::Hdcp2LegacyDeviceDownstream, XHdcp22_Rx::Info, XHdcp22_Rx_Info::LinkErrorCnt, XHdcp22_Rx_Topology::MaxCascadeExceeded, XHdcp22_Rx_Topology::MaxDevsExceeded, XHdcp22_Rx_Info::ReauthRequestCnt, XHdcp22_Rx::Topology, XHDCP22_RX_AUTHENTICATED, XHDCP22_RX_AUTHENTICATION_BUSY, XHDCP22_RX_REAUTHENTICATE_REQUESTED, XHDCP22_RX_UNAUTHENTICATED, XHdcp22Rx_GetContentStreamType, XHdcp22Rx_IsEnabled, XHdcp22Rx_IsEncryptionEnabled, XHdcp22Rx_IsRepeater.
void XHdcp22Rx_SetLinkError(XHdcp22_Rx *InstancePtr)
This function is called when 50 consecutive data island ECC errors are detected indicating a link integrity problem.
The error flag is set indicating to the state machine that REAUTH_REQ bit in the RXSTATUS register be set. Setting this flag only takes effect when the authentication state machine is in the Authenticated state B4. InstancePtr is a pointer to the XHdcp22_Rx core instance. This function can be registered as an asynchronous callback.
References XHdcp22_Rx_Info::ErrorFlag, XHdcp22_Rx::Info, XHdcp22_Rx_Info::LinkErrorCnt, XHDCP22_RX_ERROR_FLAG_LINK_INTEGRITY, XHDCP22_RX_LOG_EVT_ERROR, XHdcp22Rx_LogWr.
void XHdcp22Rx_SetDdcError(XHdcp22_Rx *InstancePtr)
This function is called when a DDC read/write burst stops prior to completing the expected message size.
This will cause the message buffers to be flushed and state machine reset. InstancePtr is a pointer to the XHdcp22_Rx core instance. This function can be registered as an asynchronous callback.
References XHdcp22_Rx_Info::DdcErrorCnt, XHdcp22_Rx_Info::ErrorFlag, XHdcp22_Rx::Info, XHDCP22_RX_ERROR_FLAG_DDC_BURST, XHDCP22_RX_LOG_EVT_ERROR, XHdcp22Rx_LogWr.
void XHdcp22Rx_SetWriteMessageAvailable(XHdcp22_Rx *InstancePtr)
This function is called when a complete message is available in the write message buffer.
InstancePtr is a pointer to the XHdcp22_Rx core instance. This function can be registered as an asynchronous callback.
References XHdcp22_Rx_Info::DdcFlag, XHdcp22_Rx::Info, XHDCP22_RX_DDC_FLAG_WRITE_MESSAGE_READY, XHDCP22_RX_LOG_DEBUG_WRITE_MESSAGE_AVAILABLE, XHDCP22_RX_LOG_EVT_DEBUG, XHdcp22Rx_LogWr.
void XHdcp22Rx_SetReadMessageComplete(XHdcp22_Rx *InstancePtr)
This function is called when a message has been read out of the read message buffer.
InstancePtr is a pointer to the XHdcp22_Rx core instance. This function can be registered as an asynchronous callback.
References XHdcp22_Rx_Info::DdcFlag, XHdcp22_Rx::Info, XHDCP22_RX_DDC_FLAG_READ_MESSAGE_READY, XHDCP22_RX_LOG_DEBUG_READ_MESSAGE_COMPLETE, XHDCP22_RX_LOG_EVT_DEBUG, XHdcp22Rx_LogWr.
void XHdcp22Rx_LoadLc128(XHdcp22_Rx *InstancePtr, const u8 *Lc128Ptr)
This function is used to load the Lc128 value by copying the contents of the array referenced by Lc128Ptr into the cipher.
InstancePtr is a pointer to the XHdcp22_Rx core instance. Lc128Ptr is a pointer to an array. None.
References XHdcp22_Rx::CipherInst.
void XHdcp22Rx_LoadPublicCert(XHdcp22_Rx *InstancePtr, const u8 *PublicCertPtr)
This function is used to load the public certificate.
InstancePtr is a pointer to the XHdcp22_Rx core instance. PublicCertPtr is a pointer to an array. None.
References XHdcp22_Rx::PublicCertPtr.
int XHdcp22Rx_LoadPrivateKey(XHdcp22_Rx *InstancePtr, const u8 *PrivateKeyPtr)
This function is used to load the private key.
InstancePtr is a pointer to the XHdcp22_Rx core instance. PrivateKeyPtr is a pointer to an array. - XST_SUCCESS if MMULT keys are calculated correctly. XST_FAILURE if MMULT keys are not calculated correctly. None.
References XHdcp22_Rx::NPrimeP, XHdcp22_Rx::NPrimeQ, XHdcp22_Rx::PrivateKeyPtr, XHdcp22Rx_CalcMontNPrime.
void XHdcp22Rx_LogReset(XHdcp22_Rx *InstancePtr, u8 Verbose)
This function clears the log pointers.
InstancePtr is a pointer to the XHdcp22_Rx core instance. Verbose allows to add debug logging. None.
References XHdcp22_Rx_Log::Head, XHdcp22_Rx::Log, XHdcp22_Rx_Log::Tail, XHdcp22_Rx::TimerInst, XHdcp22_Rx_Log::Verbose.
Referenced by XHdcp22Rx_CfgInitialize.
u32 XHdcp22Rx_LogGetTimeUSecs(XHdcp22_Rx *InstancePtr)
This function returns the time expired since a log reset was called.
InstancePtr is a pointer to the XHdcp22_Rx core instance. The expired logging time in useconds. None.
References XHdcp22_Rx::TimerInst.
Referenced by XHdcp22Rx_LogWr.
void XHdcp22Rx_LogWr(XHdcp22_Rx *InstancePtr, u16 Evt, u16 Data)
This function writes HDCP22-RX log event into buffer.
If the log event is of type error, the sticky error flag is set. The sticky error flag is used to keep history of error conditions. InstancePtr is a pointer to the XHdcp22_Rx core instance. Evt specifies an action to be carried out. Data specifies the information that gets written into log buffer. None.
References XHdcp22_Rx_LogItem::Data, XHdcp22_Rx_Info::ErrorFlagSticky, XHdcp22_Rx_Log::Head, XHdcp22_Rx::Info, XHdcp22_Rx::Log, XHdcp22_Rx_LogItem::LogEvent, XHdcp22_Rx_Log::LogItems, XHdcp22_Rx_Log::Tail, XHdcp22_Rx_LogItem::TimeStamp, XHdcp22_Rx_Log::Verbose, XHDCP22_RX_LOG_BUFFER_SIZE, XHDCP22_RX_LOG_EVT_DEBUG, XHDCP22_RX_LOG_EVT_ERROR, XHDCP22_RX_LOG_EVT_INFO_MESSAGE, XHDCP22_RX_LOG_EVT_INVALID, XHdcp22Rx_LogGetTimeUSecs.
Referenced by XHdcp22Rx_Disable, XHdcp22Rx_Enable, XHdcp22Rx_Poll, XHdcp22Rx_Reset, XHdcp22Rx_RsaesOaepDecrypt, XHdcp22Rx_SetDdcError, XHdcp22Rx_SetLinkError, XHdcp22Rx_SetReadMessageComplete, XHdcp22Rx_SetTopologyUpdate, XHdcp22Rx_SetWriteMessageAvailable.
XHdcp22_Rx_LogItem * XHdcp22Rx_LogRd(XHdcp22_Rx *InstancePtr)
This function provides the log information from the log buffer.
InstancePtr is a pointer to the XHdcp22_Rx core instance. Content of log buffer if log pointers are not equal.Otherwise Zero. None.
References XHdcp22_Rx_LogItem::Data, XHdcp22_Rx_Log::Head, XHdcp22_Rx::Log, XHdcp22_Rx_LogItem::LogEvent, XHdcp22_Rx_Log::LogItems, XHdcp22_Rx_Log::Tail, XHdcp22_Rx_LogItem::TimeStamp, XHDCP22_RX_LOG_BUFFER_SIZE.
Referenced by XHdcp22Rx_LogDisplay.
void XHdcp22Rx_LogDisplay(XHdcp22_Rx *InstancePtr)
This function prints the contents of the log buffer.
InstancePtr is a pointer to the XHdcp22_Rx core instance. None.
References XHdcp22_Rx_LogItem::Data, XHdcp22_Rx_LogItem::LogEvent, XHdcp22_Rx_LogItem::TimeStamp, XHDCP22_RX_ERROR_FLAG_DDC_BURST, XHDCP22_RX_ERROR_FLAG_EMPTY_REPEATER_TOPOLOGY, XHDCP22_RX_ERROR_FLAG_FORCE_RESET, XHDCP22_RX_ERROR_FLAG_LINK_INTEGRITY, XHDCP22_RX_ERROR_FLAG_MAX_LCINIT_ATTEMPTS, XHDCP22_RX_ERROR_FLAG_MAX_REPEATER_TOPOLOGY, XHDCP22_RX_ERROR_FLAG_MESSAGE_SIZE, XHDCP22_RX_ERROR_FLAG_PROCESSING_AKEINIT, XHDCP22_RX_ERROR_FLAG_PROCESSING_AKENOSTOREDKM, XHDCP22_RX_ERROR_FLAG_PROCESSING_AKESTOREDKM, XHDCP22_RX_ERROR_FLAG_PROCESSING_LCINIT, XHDCP22_RX_ERROR_FLAG_PROCESSING_REPEATERAUTHSENDACK, XHDCP22_RX_ERROR_FLAG_PROCESSING_REPEATERAUTHSTREAMMANAGE, XHDCP22_RX_ERROR_FLAG_PROCESSING_SKESENDEKS, XHDCP22_RX_LOG_DEBUG_COMPUTE_EKH, XHDCP22_RX_LOG_DEBUG_COMPUTE_EKH_DONE, XHDCP22_RX_LOG_DEBUG_COMPUTE_HPRIME, XHDCP22_RX_LOG_DEBUG_COMPUTE_HPRIME_DONE, XHDCP22_RX_LOG_DEBUG_COMPUTE_KM, XHDCP22_RX_LOG_DEBUG_COMPUTE_KM_DONE, XHDCP22_RX_LOG_DEBUG_COMPUTE_KS, XHDCP22_RX_LOG_DEBUG_COMPUTE_KS_DONE, XHDCP22_RX_LOG_DEBUG_COMPUTE_LPRIME, XHDCP22_RX_LOG_DEBUG_COMPUTE_LPRIME_DONE, XHDCP22_RX_LOG_DEBUG_COMPUTE_MPRIME, XHDCP22_RX_LOG_DEBUG_COMPUTE_MPRIME_DONE, XHDCP22_RX_LOG_DEBUG_COMPUTE_RSA, XHDCP22_RX_LOG_DEBUG_COMPUTE_RSA_DONE, XHDCP22_RX_LOG_DEBUG_COMPUTE_VPRIME, XHDCP22_RX_LOG_DEBUG_COMPUTE_VPRIME_DONE, XHDCP22_RX_LOG_DEBUG_READ_MESSAGE_COMPLETE, XHDCP22_RX_LOG_DEBUG_TIMER_EXPIRED, XHDCP22_RX_LOG_DEBUG_TIMER_START, XHDCP22_RX_LOG_DEBUG_WRITE_MESSAGE_AVAILABLE, XHDCP22_RX_LOG_EVT_DEBUG, XHDCP22_RX_LOG_EVT_ERROR, XHDCP22_RX_LOG_EVT_INFO, XHDCP22_RX_LOG_EVT_INFO_MESSAGE, XHDCP22_RX_LOG_EVT_INFO_STATE, XHDCP22_RX_LOG_EVT_USER, XHDCP22_RX_LOG_INFO_DISABLE, XHDCP22_RX_LOG_INFO_ENABLE, XHDCP22_RX_LOG_INFO_ENCRYPTION_ENABLE, XHDCP22_RX_LOG_INFO_REQAUTH_REQ, XHDCP22_RX_LOG_INFO_RESET, XHDCP22_RX_LOG_INFO_TOPOLOGY_UPDATE, XHDCP22_RX_MSG_ID_AKEINIT, XHDCP22_RX_MSG_ID_AKENOSTOREDKM, XHDCP22_RX_MSG_ID_AKESENDCERT, XHDCP22_RX_MSG_ID_AKESENDHPRIME, XHDCP22_RX_MSG_ID_AKESENDPAIRINGINFO, XHDCP22_RX_MSG_ID_AKESTOREDKM, XHDCP22_RX_MSG_ID_LCINIT, XHDCP22_RX_MSG_ID_LCSENDLPRIME, XHDCP22_RX_MSG_ID_REPEATERAUTHSENDACK, XHDCP22_RX_MSG_ID_REPEATERAUTHSENDRXIDLIST, XHDCP22_RX_MSG_ID_REPEATERAUTHSTREAMMANAGE, XHDCP22_RX_MSG_ID_REPEATERAUTHSTREAMREADY, XHDCP22_RX_MSG_ID_SKESENDEKS, XHDCP22_RX_STATE_B0_WAIT_AKEINIT, XHDCP22_RX_STATE_B1_SEND_AKESENDCERT, XHDCP22_RX_STATE_B1_SEND_AKESENDHPRIME, XHDCP22_RX_STATE_B1_SEND_AKESENDPAIRINGINFO, XHDCP22_RX_STATE_B1_WAIT_AKEKM, XHDCP22_RX_STATE_B1_WAIT_LCINIT, XHDCP22_RX_STATE_B2_SEND_LCSENDLPRIME, XHDCP22_RX_STATE_B2_WAIT_SKESENDEKS, XHDCP22_RX_STATE_B3_COMPUTE_KS, XHDCP22_RX_STATE_B4_AUTHENTICATED, XHDCP22_RX_STATE_C4_WAIT_FOR_DOWNSTREAM, XHDCP22_RX_STATE_C5_SEND_RECEIVERIDLIST, XHDCP22_RX_STATE_C5_SEND_RECEIVERIDLIST_DONE, XHDCP22_RX_STATE_C6_VERIFY_RECEIVERIDLISTACK, XHDCP22_RX_STATE_C7_SEND_STREAM_READY, XHDCP22_RX_STATE_C7_SEND_STREAM_READY_DONE, XHDCP22_RX_STATE_C7_WAIT_STREAM_MANAGEMENT, XHDCP22_RX_STATE_C8_AUTHENTICATED, XHdcp22Rx_LogRd.
void XHdcp22Rx_SetTopology(XHdcp22_Rx *InstancePtr, const XHdcp22_Rx_Topology *TopologyPtr)
This function copies a complete repeater topology table into the instance repeater topology table.
InstancePtr is a pointer to the XHdcp22_Rx core instance. TopologyPtr is a pointer to the repeater topology table. None.
References XHdcp22_Rx::Topology.
void XHdcp22Rx_SetTopologyReceiverIdList(XHdcp22_Rx *InstancePtr, const u8 *ListPtr, u32 ListSize)
This function copies the RECEIVER_ID_LIST into the repeater topology table.
Receiver ID list is constructed by appending Receiver IDs in big-endian order. InstancePtr is a pointer to the XHdcp22_Rx core instance. ListPtr is a pointer to the Receiver ID list. The list consists of a contiguous set of bytes stored in big-endian order, with each Receiver ID occuping five bytes with a maximum of 31 Receiver IDs. ListSize is the number of Receiver IDs in the list. The list size cannot exceed 31 devices. None.
References XHdcp22_Rx_Topology::ReceiverIdList, XHdcp22_Rx::Topology.
void XHdcp22Rx_SetTopologyField(XHdcp22_Rx *InstancePtr, XHdcp22_Rx_TopologyField Field, u8 Value)
This function is used to set various fields inside the topology structure.
InstancePtr is a pointer to the XHdcp22_Rx core instance. Field indicates what field of the topology structure to update. Value is the value assigned to the field of the topology structure. None.
void XHdcp22Rx_SetTopologyUpdate(XHdcp22_Rx *InstancePtr)
This function is used to indicate that the topology table has been updated and is ready for upstream propagation.
Before calling this function ensure that all the fields in the repeater topology table have been updated. InstancePtr is a pointer to the XHdcp22_Rx core instance. None.
References XHdcp22_Rx::Info, XHdcp22_Rx_Info::IsTopologyValid, XHDCP22_RX_LOG_EVT_INFO, XHDCP22_RX_LOG_INFO_TOPOLOGY_UPDATE, XHdcp22Rx_LogWr.
void XHdcp22Rx_SetRepeater(XHdcp22_Rx *InstancePtr, u8 Set)
This function sets the repeater mode status.
InstancePtr is a pointer to the XHdcp22_Rx core instance. Set is TRUE to enable repeater mode and FALSE to disable.
References XHdcp22_Rx::Config, XHdcp22_Rx_Config::Mode, XHdcp22_Rx::RxCaps, XHDCP22_RX_RECEIVER, XHDCP22_RX_REPEATER.
u8 XHdcp22Rx_IsRepeater(XHdcp22_Rx *InstancePtr)
This function returns the current repeater mode status.
InstancePtr is a pointer to the XHdcp22_Rx core instance. TRUE if the HDCP 2.2 instance is the upstream port of a repeaterFALSE if the HDCP 2.2 instance is a receiver
References XHdcp22_Rx::Config, XHdcp22_Rx_Config::Mode, XHDCP22_RX_RECEIVER.
Referenced by XHdcp22Rx_Info.
u8 XHdcp22Rx_GetContentStreamType(XHdcp22_Rx *InstancePtr)
This function is gets the type information received from the RepeaterAuth_Stream_Manage message for downstream propagation of management information.
This function should be called only after the RepeaterAuth_Stream_Manage message has been received, and can be called inside the user callback function type XHDCP22_RX_HANDLER_STREAM_MANAGE_REQUEST. InstancePtr is a pointer to the XHdcp22_Rx core instance. - 0x00: Type 0 Content Stream. May be transmitted by the HDCP Repeater to all HDCP Devices. 0x01: Type 1 Content Stream. Must not be transmitted by the HDCP Repeater to HDCP 1.x-compliant Devices and HDCP 2.1-compliant Devices.0x02-0xFF: Reserved for future use only. Content Streams with reserved Type values must be treated similar to Type 1 Content Streams. None.
References XHdcp22_Rx::Params.
Referenced by XHdcp22Rx_Info.