uartns550
XUN_OPTION_RXLINE_INTR
These constants specify the options that may be set or retrieved with the driver, each is a unique bit mask such that multiple options may be specified.
These constants indicate the function of the option when in the active state.Enable status interrupt
XUN_OPTION_SET_BREAK
Set a break condition.
XUN_OPTION_LOOPBACK
Enable local loopback.
Referenced by UartNs550IntrExample, UartNs550PolledExample.
XUN_OPTION_DATA_INTR
Enable data interrupts.
Referenced by UartNs550IntrExample.
XUN_OPTION_MODEM_INTR
Enable modem interrupts.
XUN_OPTION_FIFOS_ENABLE
Enable FIFOs.
Referenced by UartNs550IntrExample, UartNs550PolledExample.
XUN_OPTION_RESET_TX_FIFO
Reset the transmit FIFO.
XUN_OPTION_RESET_RX_FIFO
Reset the receive FIFO.
XUN_OPTION_ASSERT_OUT2
Assert out2 signal.
XUN_OPTION_ASSERT_OUT1
Assert out1 signal.
XUN_OPTION_ASSERT_RTS
Assert RTS signal.
XUN_OPTION_ASSERT_DTR
Assert DTR signal.
XUN_FORMAT_8_BITS
These constants specify the data format that may be set or retrieved with the driver.
The data format includes the number of data bits, the number of stop bits and parity.8 data bits
Referenced by XUartNs550_CfgInitialize, XUartNs550_SetDataFormat.
XUN_FORMAT_7_BITS
7 data bits
XUN_FORMAT_6_BITS
6 data bits
XUN_FORMAT_5_BITS
5 data bits
XUN_FORMAT_EVEN_PARITY
Even Parity.
Referenced by XUartNs550_GetDataFormat, XUartNs550_SetDataFormat.
XUN_FORMAT_ODD_PARITY
Odd Parity.
Referenced by XUartNs550_GetDataFormat.
XUN_FORMAT_NO_PARITY
No Parity.
Referenced by XUartNs550_GetDataFormat, XUartNs550_SetDataFormat.
XUN_FORMAT_2_STOP_BIT
2 stop bits
Referenced by XUartNs550_GetDataFormat, XUartNs550_SetDataFormat.
XUN_FORMAT_1_STOP_BIT
1 stop bit
Referenced by XUartNs550_GetDataFormat, XUartNs550_SetDataFormat.
XUN_FIFO_TRIGGER_14
14 byte trigger level
Referenced by XUartNs550_SetFifoThreshold.
XUN_FIFO_TRIGGER_08
8 byte trigger level
Referenced by XUartNs550_SetFifoThreshold.
XUN_FIFO_TRIGGER_04
4 byte trigger level
Referenced by XUartNs550_SetFifoThreshold.
XUN_FIFO_TRIGGER_01
1 byte trigger level
Referenced by XUartNs550_SetFifoThreshold.
XUN_MODEM_DCD_DELTA_MASK
These constants specify the modem status that may be retrieved from the driver.
DCD signal changed state
XUN_MODEM_DSR_DELTA_MASK
DSR signal changed state.
XUN_MODEM_CTS_DELTA_MASK
CTS signal changed state.
XUN_MODEM_RINGING_MASK
Ring signal is active.
XUN_MODEM_DSR_MASK
Current state of DSR signal.
XUN_MODEM_CTS_MASK
Current state of CTS signal.
XUN_MODEM_DCD_MASK
Current state of DCD signal.
XUN_MODEM_RING_STOP_MASK
Ringing has stopped.
XUN_EVENT_RECV_DATA
These constants specify the handler events that are passed to a handler from the driver.
These constants are not bit masks such that only one will be passed at a time to the handler.Data has been received
Referenced by UartNs550IntrHandler.
XUN_EVENT_RECV_TIMEOUT
A receive timeout occurred.
Referenced by UartNs550IntrHandler.
XUN_EVENT_SENT_DATA
Data has been sent.
Referenced by UartNs550IntrHandler.
XUN_EVENT_RECV_ERROR
A receive error was detected.
Referenced by UartNs550IntrHandler.
XUN_EVENT_MODEM
A change in modem status.
XUN_ERROR_BREAK_MASK
These constants specify the errors that may be retrieved from the driver using the XUartNs550_GetLastErrors function.
All of them are bit masks, except no error, such that multiple errors may be specified.Break detected
XUN_ERROR_FRAMING_MASK
Receive framing error.
XUN_ERROR_PARITY_MASK
Receive parity error.
XUN_ERROR_OVERRUN_MASK
Receive overrun error.
XUN_ERROR_NONE
No error.
XUN_RBR_OFFSET
Receive buffer, read only.
Referenced by XUartNs550_ReceiveBuffer, XUartNs550_RecvByte.
XUN_THR_OFFSET
Transmit holding register.
Referenced by XUartNs550_SendBuffer, XUartNs550_SendByte.
XUN_IER_OFFSET
Interrupt enable.
Referenced by XUartNs550_Recv, XUartNs550_SelfTest, XUartNs550_Send, XUartNs550_SendBuffer.
XUN_IIR_OFFSET
Interrupt id, read only.
Referenced by XUartNs550_InterruptHandler, XUartNs550_SendBuffer.
XUN_FCR_OFFSET
Fifo control, write only.
Referenced by XUartNs550_CfgInitialize, XUartNs550_GetOptions, XUartNs550_LowLevelExample, XUartNs550_SetFifoThreshold, XUartNs550_SetOptions.
XUN_LCR_OFFSET
Line Control Register.
XUN_MCR_OFFSET
Modem Control Register.
Referenced by XUartNs550_SelfTest.
XUN_LSR_OFFSET
Line Status Register.
XUN_MSR_OFFSET
Modem Status Register.
Referenced by XUartNs550_GetModemStatus.
XUN_DLL_OFFSET
Divisor Register LSB.
Referenced by XUartNs550_SetBaud.
XUN_DLM_OFFSET
Divisor Register MSB.
Referenced by XUartNs550_SetBaud.
XUN_DRLS_OFFSET
Divisor Register LSB.
XUN_DRLM_OFFSET
Divisor Register MSB.
XUN_IER_MODEM_STATUS
Modem status interrupt.
XUN_IER_RX_LINE
Receive status interrupt.
XUN_IER_TX_EMPTY
Transmitter empty interrupt.
Referenced by XUartNs550_Send, XUartNs550_SendBuffer.
XUN_IER_RX_DATA
Receiver data available.
Referenced by XUartNs550_SendBuffer.
XUN_INT_ID_MASK
Only the interrupt ID.
Referenced by XUartNs550_InterruptHandler.
XUN_INT_ID_FIFOS_ENABLED
Only the FIFOs enable.
Referenced by XUartNs550_SendBuffer.
XUN_FIFO_RX_TRIG_MSB
Trigger level MSB.
Referenced by XUartNs550_CfgInitialize.
XUN_FIFO_RX_TRIG_LSB
Trigger level LSB.
XUN_FIFO_TX_RESET
Reset the transmit FIFO.
XUN_FIFO_RX_RESET
Reset the receive FIFO.
XUN_FIFO_ENABLE
Enable the FIFOs.
Referenced by XUartNs550_CfgInitialize, XUartNs550_LowLevelExample, XUartNs550_SetFifoThreshold.
XUN_FIFO_RX_TRIGGER
Both trigger level bits.
Referenced by XUartNs550_GetFifoThreshold, XUartNs550_SetFifoThreshold.
XUN_LCR_DLAB
Divisor latch access.
Referenced by XUartNs550_SetBaud.
XUN_LCR_SET_BREAK
Cause a break condition.
XUN_LCR_STICK_PARITY
Stick Parity.
XUN_LCR_EVEN_PARITY
1 = even, 0 = odd parity
Referenced by XUartNs550_GetDataFormat, XUartNs550_SetDataFormat.
XUN_LCR_ENABLE_PARITY
1 = Enable, 0 = Disable parity
Referenced by XUartNs550_GetDataFormat, XUartNs550_SetDataFormat.
XUN_LCR_2_STOP_BITS
1= 2 stop bits,0 = 1 stop bit
Referenced by XUartNs550_GetDataFormat, XUartNs550_SetDataFormat.
XUN_LCR_8_DATA_BITS
8 Data bits selection
Referenced by XUartNs550_LowLevelExample.
XUN_LCR_7_DATA_BITS
7 Data bits selection
XUN_LCR_6_DATA_BITS
6 Data bits selection
XUN_LCR_LENGTH_MASK
Both length bits mask.
Referenced by XUartNs550_GetDataFormat, XUartNs550_SetDataFormat.
XUN_LCR_PARITY_MASK
Both parity bits mask.
Referenced by XUartNs550_SetDataFormat.
XUN_MCR_LOOP
Local loopback.
Referenced by XUartNs550_SelfTest.
XUN_MCR_OUT_2
General output 2 signal.
XUN_MCR_OUT_1
General output 1 signal.
XUN_MCR_RTS
RTS signal.
XUN_MCR_DTR
DTR signal.
XUN_LSR_RX_FIFO_ERROR
An errored byte is in FIFO.
XUN_LSR_TX_EMPTY
Transmitter is empty.
Referenced by XUartNs550_IsSending, XUartNs550_SendBuffer.
XUN_LSR_TX_BUFFER_EMPTY
Transmit holding reg empty.
Referenced by XUartNs550_SendBuffer.
XUN_LSR_BREAK_INT
Break detected interrupt.
Referenced by XUartNs550_ReceiveBuffer.
XUN_LSR_FRAMING_ERROR
Framing error on current byte.
XUN_LSR_PARITY_ERROR
Parity error on current byte.
XUN_LSR_OVERRUN_ERROR
Overrun error on receive FIFO.
XUN_LSR_DATA_READY
Receive data ready.
Referenced by XUartNs550_ReceiveBuffer, XUartNs550_SelfTest.
XUN_LSR_ERROR_BREAK
Errors except FIFO error and break detected.
Referenced by XUartNs550_GetLastErrors.
typedef void(* XUartNs550_Handler)(void *CallBackRef, u32 Event, unsigned int EventData))(void *CallBackRef, u32 Event, unsigned int EventData)
This data type defines a handler which the application must define when using interrupt mode.
The handler will be called from the driver in an interrupt context to handle application specific processing. CallBackRef is a callback reference passed in by the upper layer when setting the handler, and is passed back to the upper layer when the handler is called. Event contains one of the event constants indicating why the handler is being called. EventData contains the number of bytes sent or received at the time of the call for send and receive events and contains the modem status for modem events.
typedef void(* Handler)(XUartNs550 *InstancePtr))(XUartNs550 *InstancePtr)
XUartNs550_Config XUartNs550_ConfigTable[][]
The configuration table for UART 16550/16450 devices in the table.
Each device should have an entry in this table.
Referenced by XUartNs550_LookupConfig.
XUartNs550_Config XUartNs550_ConfigTable[][]
The configuration table for UART 16550/16450 devices in the table.
Each device should have an entry in this table.
Referenced by XUartNs550_LookupConfig.
Handler HandlerTable[13][13]
Mapping OptionsTable[][]
u8 TestString[XUN_TOTAL_BYTES+1][XUN_TOTAL_BYTES+1]
u8 ReturnString[XUN_TOTAL_BYTES+1][XUN_TOTAL_BYTES+1]
static void XUartNs550_StubHandler(void *CallBackRef, u32 Event, unsigned int ByteCount)
This function is a stub handler that is the default handler such that if the application has not set the handler when interrupts are enabled, this function will be called.
The function interface has to match the interface specified for a handler even though none of the arguments are used. CallBackRef is unused by this function. Event is unused by this function. ByteCount is unused by this function. None. None.
int XUartNs550_CfgInitialize(XUartNs550 *InstancePtr, XUartNs550_Config *Config, UINTPTR EffectiveAddr)
Initializes a specific XUartNs550 instance such that it is ready to be used.
The data format of the device is setup for 8 data bits, 1 stop bit, and no parity by default. The baud rate is set to a default value specified by Config->DefaultBaudRate if set, otherwise it is set to 19.2K baud. If the device has FIFOs (16550), they are enabled and the a receive FIFO threshold is set for 8 bytes. The default operating mode of the driver is polled mode. InstancePtr is a pointer to the XUartNs550 instance. Config is a reference to a structure containing information about a specific UART 16450/16550 device. XUartNs550_Init initializes an InstancePtr object for a specific device specified by the contents f Config. XUartNs550_Init can initialize multiple instance objects with the use of multiple calls giving different Config information on each call. EffectiveAddr is the device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, use Config->BaseAddress for this parameters, passing the physical address instead. XST_SUCCESS if initialization was successful.XST_UART_BAUD_ERROR if the baud rate is not possible because the input clock frequency is not divisible with an acceptable amount of error. None.
References XUartNs550::BaseAddress, XUartNs550_Config::DefaultBaudRate, XUartNs550::Handler, XUartNs550_Config::InputClockHz, XUartNs550::InputClockHz, XUartNs550::IsReady, XUartNs550Buffer::NextBytePtr, XUartNs550::ReceiveBuffer, XUartNs550Buffer::RemainingBytes, XUartNs550Buffer::RequestedBytes, XUartNs550::SendBuffer, XUartNs550_ClearStats, XUartNs550_SetLineControlReg, XUartNs550_WriteReg, XUN_FCR_OFFSET, XUN_FIFO_ENABLE, XUN_FIFO_RX_TRIG_MSB, XUN_FORMAT_8_BITS.
Referenced by XUartNs550_Initialize.
unsigned int XUartNs550_Send(XUartNs550 *InstancePtr, u8 *BufferPtr, unsigned int NumBytes)
This functions sends the specified buffer of data using the UART in either polled or interrupt driven modes.
This function is non-blocking such that it will return before the data has been sent by the UART. If the UART is busy sending data, it will return and indicate zero bytes were sent.In a polled mode, this function will only send as much data as the UART can buffer, either in the transmitter or in the FIFO if present and enabled. The application may need to call it repeatedly to send a buffer.In interrupt mode, this function will start sending the specified buffer and then the interrupt handler of the driver will continue sending data until the buffer has been sent. A callback function, as specified by the application, will be called to indicate the completion of sending the buffer. InstancePtr is a pointer to the XUartNs550 instance. BufferPtr is pointer to a buffer of data to be sent. NumBytes contains the number of bytes to be sent. A value of zero will stop a previous send operation that is in progress in interrupt mode. Any data that was already put into the transmit FIFO will be sent. The number of bytes actually sent. The number of bytes is not asserted so that this function may be called with a value of zero to stop an operation that is already in progress. This function and the XUartNs550_SetOptions() function modify shared data such that there may be a need for mutual exclusion in a multithreaded environment and if XUartNs550_SetOptions() if called from a handler.
References XUartNs550::BaseAddress, XUartNs550::IsReady, XUartNs550Buffer::NextBytePtr, XUartNs550Buffer::RemainingBytes, XUartNs550Buffer::RequestedBytes, XUartNs550::SendBuffer, XUartNs550_ReadReg, XUartNs550_SendBuffer, XUartNs550_WriteReg, XUN_IER_OFFSET, XUN_IER_TX_EMPTY.
Referenced by UartNs550HelloWorldExample, UartNs550IntrExample, UartNs550PolledExample, XUartNs550_SelfTest.
unsigned int XUartNs550_Recv(XUartNs550 *InstancePtr, u8 *BufferPtr, unsigned int NumBytes)
This function will attempt to receive a specified number of bytes of data from the UART and store it into the specified buffer.
This function is designed for either polled or interrupt driven modes. It is non-blocking such that it will return if no data has already received by the UART.In a polled mode, this function will only receive as much data as the UART can buffer, either in the receiver or in the FIFO if present and enabled. The application may need to call it repeatedly to receive a buffer. Polled mode is the default mode of operation for the driver.In interrupt mode, this function will start receiving and then the interrupt handler of the driver will continue receiving data until the buffer has been received. A callback function, as specified by the application, will be called to indicate the completion of receiving the buffer or when any receive errors or timeouts occur. Interrupt mode must be enabled using the SetOptions function. InstancePtr is a pointer to the XUartNs550 instance. BufferPtr is pointer to buffer for data to be received into NumBytes is the number of bytes to be received. A value of zero will stop a previous receive operation that is in progress in interrupt mode. The number of bytes received. The number of bytes is not asserted so that this function may be called with a value of zero to stop an operation that is already in progress.
References XUartNs550::BaseAddress, XUartNs550::IsReady, XUartNs550Buffer::NextBytePtr, XUartNs550::ReceiveBuffer, XUartNs550Buffer::RemainingBytes, XUartNs550Buffer::RequestedBytes, XUartNs550_ReadReg, XUartNs550_ReceiveBuffer, XUartNs550_WriteReg, XUN_IER_OFFSET.
Referenced by UartNs550IntrExample, UartNs550PolledExample, XUartNs550_SelfTest.
unsigned int XUartNs550_SendBuffer(XUartNs550 *InstancePtr)
This function sends a buffer that has been previously specified by setting up the instance variables of the instance.
This function is designed to be an internal function for the XUartNs550 component such that it may be called from a shell function that sets up the buffer or from an interrupt handler.This function sends the specified buffer of data to the UART in either polled or interrupt driven modes. This function is non-blocking such that it will return before the data has been sent by the UART.In a polled mode, this function will only send as much data as the UART can buffer, either in the transmitter or in the FIFO if present and enabled. The application may need to call it repeatedly to send a buffer.In interrupt mode, this function will start sending the specified buffer and then the interrupt handler of the driver will continue until the buffer has been sent. A callback function, as specified by the application, will be called to indicate the completion of sending the buffer. InstancePtr is a pointer to the XUartNs550 instance. NumBytes is the number of bytes actually sent (put into the UART tranmitter and/or FIFO). None.
References XUartNs550::BaseAddress, XUartNs550Stats::CharactersTransmitted, XUartNs550Buffer::NextBytePtr, XUartNs550Buffer::RemainingBytes, XUartNs550::SendBuffer, XUartNs550::Stats, XUartNs550_GetLineStatusReg, XUartNs550_ReadReg, XUartNs550_WriteReg, XUN_IER_OFFSET, XUN_IER_RX_DATA, XUN_IER_TX_EMPTY, XUN_IIR_OFFSET, XUN_INT_ID_FIFOS_ENABLED, XUN_LSR_TX_BUFFER_EMPTY, XUN_LSR_TX_EMPTY, XUN_THR_OFFSET.
Referenced by XUartNs550_Send.
unsigned int XUartNs550_ReceiveBuffer(XUartNs550 *InstancePtr)
This function receives a buffer that has been previously specified by setting up the instance variables of the instance.
This function is designed to be an internal function for the XUartNs550 component such that it may be called from a shell function that sets up the buffer or from an interrupt handler.This function will attempt to receive a specified number of bytes of data from the UART and store it into the specified buffer. This function is designed for either polled or interrupt driven modes. It is non-blocking such that it will return if there is no data has already received by the UART.In a polled mode, this function will only receive as much data as the UART can buffer, either in the receiver or in the FIFO if present and enabled. The application may need to call it repeatedly to receive a buffer. Polled mode is the default mode of operation for the driver.In interrupt mode, this function will start receiving and then the interrupt handler of the driver will continue until the buffer has been received. A callback function, as specified by the application, will be called to indicate the completion of receiving the buffer or when any receive errors or timeouts occur. Interrupt mode must be enabled using the SetOptions function. InstancePtr is a pointer to the XUartNs550 instance. The number of bytes received. None.
References XUartNs550::BaseAddress, XUartNs550Stats::CharactersReceived, XUartNs550Buffer::NextBytePtr, XUartNs550::ReceiveBuffer, XUartNs550Buffer::RemainingBytes, XUartNs550::Stats, XUartNs550_GetLineStatusReg, XUartNs550_ReadReg, XUN_LSR_BREAK_INT, XUN_LSR_DATA_READY, XUN_RBR_OFFSET.
Referenced by XUartNs550_Recv.
int XUartNs550_SetBaudRate(XUartNs550 *InstancePtr, u32 BaudRate)
int XUartNs550_Initialize(XUartNs550 *InstancePtr, UINTPTR BaseAddress)
Initializes a specific XUartNs550 instance such that it is ready to be used.
The data format of the device is setup for 8 data bits, 1 stop bit, and no parity by default. The baud rate is set to a default value specified by XPAR_DEFAULT_BAUD_RATE if the symbol is defined, otherwise it is set to 19.2K baud. If the device has FIFOs (16550), they are enabled and the a receive FIFO threshold is set for 8 bytes. The default operating mode of the driver is polled mode. InstancePtr is a pointer to the XUartNs550 instance . BaseAddress contains the base address of the device - XST_SUCCESS if initialization was successful - XST_DEVICE_NOT_FOUND if the device ID/BaseAddress could not be found in the configuration table - XST_UART_BAUD_ERROR if the baud rate is not possible because the input clock frequency is not divisible with an acceptable amount of error In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XUartNs550_Config::BaseAddress, XUartNs550_Config::DefaultBaudRate, XUartNs550_CfgInitialize, XUartNs550_LookupConfig.
Referenced by UartNs550HelloWorldExample, UartNs550IntrExample, UartNs550PolledExample, UartNs550SelfTestExample.
XUartNs550_Config * XUartNs550_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XUartNs550_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xuartns550.h for the definition of XUartNs550_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XUartNs550_Config::Name, XUartNs550_ConfigTable.
Referenced by UartNs550IntrExample, XUartNs550_Initialize.
int XUartNs550_SetOptions(XUartNs550 *InstancePtr, u16 Options)
Sets the options for the specified driver instance.
The options are implemented as bit masks such that multiple options may be enabled or disabled simultaneously.The GetOptions function may be called to retrieve the currently enabled options. The result is ORed in the desired new settings to be enabled and ANDed with the inverse to clear the settings to be disabled. The resulting value is then used as the options for the SetOption function call. InstancePtr is a pointer to the XUartNs550 instance. Options contains the options to be set which are bit masks contained in the file xuartns550.h and named XUN_OPTION_*. XST_SUCCESS if the options were set successfully.XST_UART_CONFIG_ERROR if the options could not be set because the hardware does not support FIFOs None.
References XUartNs550::BaseAddress, XUartNs550::IsReady, XUartNs550_ReadReg, XUartNs550_WriteReg, XUN_FCR_OFFSET.
Referenced by UartNs550IntrExample, UartNs550PolledExample.
u16 XUartNs550_GetOptions(XUartNs550 *InstancePtr)
Gets the options for the specified driver instance.
The options are implemented as bit masks such that multiple options may be enabled or disabled simultaneously. InstancePtr is a pointer to the XUartNs550 instance. The current options for the UART. The options are bit masks that are contained in the file xuartns550.h and named XUN_OPTION_*. None.
References XUartNs550::BaseAddress, XUartNs550::IsReady, XUartNs550_ReadReg, XUN_FCR_OFFSET.
Referenced by UartNs550IntrExample, UartNs550PolledExample.
int XUartNs550_SetFifoThreshold(XUartNs550 *InstancePtr, u8 TriggerLevel)
This functions sets the receive FIFO trigger level.
The receive trigger level specifies the number of bytes in the receive FIFO that cause a receive data event (interrupt) to be generated. The FIFOs must be enabled to set the trigger level. InstancePtr is a pointer to the XUartNs550 instance. TriggerLevel contains the trigger level to set. Constants which define each trigger level are contained in the file xuartns550.h and named XUN_FIFO_TRIGGER_*. XST_SUCCESS if the trigger level was setXST_UART_CONFIG_ERROR if the trigger level could not be set, either the hardware does not support the FIFOs or FIFOs are not enabled None.
References XUartNs550::BaseAddress, XUartNs550::IsReady, XUartNs550_WriteReg, XUN_FCR_OFFSET, XUN_FIFO_ENABLE, XUN_FIFO_RX_TRIGGER, XUN_FIFO_TRIGGER_01, XUN_FIFO_TRIGGER_04, XUN_FIFO_TRIGGER_08, XUN_FIFO_TRIGGER_14.
u8 XUartNs550_GetFifoThreshold(XUartNs550 *InstancePtr)
This function gets the receive FIFO trigger level.
The receive trigger level indicates the number of bytes in the receive FIFO that cause a receive data event (interrupt) to be generated. InstancePtr is a pointer to the XUartNs550 instance. The current receive FIFO trigger level. Constants which define each trigger level are contained in the file xuartns550.h and named XUN_FIFO_TRIGGER_*. None.
References XUartNs550::BaseAddress, XUartNs550::IsReady, XUN_FIFO_RX_TRIGGER.
int XUartNs550_IsSending(XUartNs550 *InstancePtr)
This function determines if the specified UART is sending data.
If the transmitter register is not empty, it is sending data. InstancePtr is a pointer to the XUartNs550 instance. A value of TRUE if the UART is sending data, otherwise FALSE. None.
References XUartNs550::BaseAddress, XUartNs550_GetLineStatusReg, XUN_LSR_TX_EMPTY.
u8 XUartNs550_GetLastErrors(XUartNs550 *InstancePtr)
This function returns the last errors that have occurred in the specified UART.
It also clears the errors such that they cannot be retrieved again. The errors include parity error, receive overrun error, framing error, and break detection.The last errors is an accumulation of the errors each time an error is discovered in the driver. A status is checked for each received byte and this status is accumulated in the last errors.If this function is called after receiving a buffer of data, it will indicate any errors that occurred for the bytes of the buffer. It does not indicate which bytes contained errors. InstancePtr is a pointer to the XUartNs550 instance. The last errors that occurred. The errors are bit masks that are contained in the file xuartns550.h and named XUN_ERROR_*. None.
References XUartNs550::LastErrors, XUN_LSR_ERROR_BREAK.
Referenced by UartNs550IntrHandler.
u8 XUartNs550_GetModemStatus(XUartNs550 *InstancePtr)
This function gets the modem status from the specified UART.
The modem status indicates any changes of the modem signals. This function allows the modem status to be read in a polled mode. The modem status is updated whenever it is read such that reading it twice may not yield the same results. InstancePtr is a pointer to the XUartNs550 instance . The modem status which are bit masks that are contained in the file xuartns550.h and named XUN_MODEM_*. The bit masks used for the modem status are the exact bits of the modem status register with no abstraction.
References XUartNs550::BaseAddress, XUartNs550_ReadReg, XUN_MSR_OFFSET.
int XUartNs550_SetDataFormat(XUartNs550 *InstancePtr, XUartNs550Format *FormatPtr)
Sets the data format for the specified UART.
The data format includes the baud rate, number of data bits, number of stop bits, and parity. It is the caller's responsibility to ensure that the UART is not sending or receiving data when this function is called. InstancePtr is a pointer to the XUartNs550 instance . FormatPtr is a pointer to a format structure containing the data format to be set. - XST_SUCCESS if the data format was successfully set. - XST_UART_BAUD_ERROR indicates the baud rate could not be set because of the amount of error with the baud rate and the input clock frequency. - XST_INVALID_PARAM if one of the parameters was not valid. The data types in the format type, data bits and parity, are 32 bit fields to prevent a compiler warning that is a bug with the GNU PowerPC compiler. The asserts in this function will cause a warning if these fields are bytes. The baud rates tested include: 1200, 2400, 4800, 9600, 19200, 38400, 57600 and 115200.
References XUartNs550::BaseAddress, XUartNs550Format::BaudRate, XUartNs550Format::DataBits, XUartNs550Format::Parity, XUartNs550Format::StopBits, XUartNs550_GetLineControlReg, XUartNs550_SetLineControlReg, XUN_FORMAT_1_STOP_BIT, XUN_FORMAT_2_STOP_BIT, XUN_FORMAT_8_BITS, XUN_FORMAT_EVEN_PARITY, XUN_FORMAT_NO_PARITY, XUN_LCR_2_STOP_BITS, XUN_LCR_ENABLE_PARITY, XUN_LCR_EVEN_PARITY, XUN_LCR_LENGTH_MASK, XUN_LCR_PARITY_MASK.
void XUartNs550_GetDataFormat(XUartNs550 *InstancePtr, XUartNs550Format *FormatPtr)
Gets the data format for the specified UART.
The data format includes the baud rate, number of data bits, number of stop bits, and parity. InstancePtr is a pointer to the XUartNs550 instance. FormatPtr is a pointer to a format structure that will contain the data format after this call completes. None. None.
References XUartNs550::BaseAddress, XUartNs550Format::BaudRate, XUartNs550::BaudRate, XUartNs550Format::DataBits, XUartNs550::IsReady, XUartNs550Format::Parity, XUartNs550Format::StopBits, XUartNs550_GetLineControlReg, XUN_FORMAT_1_STOP_BIT, XUN_FORMAT_2_STOP_BIT, XUN_FORMAT_EVEN_PARITY, XUN_FORMAT_NO_PARITY, XUN_FORMAT_ODD_PARITY, XUN_LCR_2_STOP_BITS, XUN_LCR_ENABLE_PARITY, XUN_LCR_EVEN_PARITY, XUN_LCR_LENGTH_MASK.
void XUartNs550_SetHandler(XUartNs550 *InstancePtr, XUartNs550_Handler FuncPtr, void *CallBackRef)
This function sets the handler that will be called when an event (interrupt) occurs in the driver.
The purpose of the handler is to allow application specific processing to be performed. InstancePtr is a pointer to the XUartNs550 instance. FuncPtr is the pointer to the callback function. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. None. There is no assert on the CallBackRef since the driver doesn't know what it is (nor should it)
References XUartNs550::CallBackRef, XUartNs550::Handler, XUartNs550::IsReady.
Referenced by UartNs550IntrExample.
void XUartNs550_InterruptHandler(XUartNs550 *InstancePtr)
This function is the interrupt handler for the 16450/16550 UART driver.
It must be connected to an interrupt system by the user such that it is called when an interrupt for any 16450/16550 UART occurs. This function does not save or restore the processor context such that the user must ensure this occurs. InstancePtr contains a pointer to the instance of the UART that the interrupt is for. None. None.
References XUartNs550::BaseAddress, XUartNs550_ReadReg, XUN_IIR_OFFSET, XUN_INT_ID_MASK.
Referenced by UartNs550IntrExample.
void XUartNs550_GetStats(XUartNs550 *InstancePtr, XUartNs550Stats *StatsPtr)
This functions returns a snapshot of the current statistics in the area provided.
InstancePtr is a pointer to the XUartNs550 instance. StatsPtr is a pointer to a XUartNs550Stats structure to where the statistics are to be copied to. None. None.
References XUartNs550Stats::CharactersReceived, XUartNs550Stats::CharactersTransmitted, XUartNs550::IsReady, XUartNs550Stats::ModemInterrupts, XUartNs550Stats::ReceiveBreakDetected, XUartNs550Stats::ReceiveFramingErrors, XUartNs550Stats::ReceiveInterrupts, XUartNs550Stats::ReceiveOverrunErrors, XUartNs550Stats::ReceiveParityErrors, XUartNs550::Stats, XUartNs550Stats::StatusInterrupts, XUartNs550Stats::TransmitInterrupts.
void XUartNs550_ClearStats(XUartNs550 *InstancePtr)
This function zeros the statistics for the given instance.
InstancePtr is a pointer to the XUartNs550 instance. None. None.
References XUartNs550Stats::CharactersReceived, XUartNs550Stats::CharactersTransmitted, XUartNs550::IsReady, XUartNs550Stats::ModemInterrupts, XUartNs550Stats::ReceiveBreakDetected, XUartNs550Stats::ReceiveFramingErrors, XUartNs550Stats::ReceiveInterrupts, XUartNs550Stats::ReceiveOverrunErrors, XUartNs550Stats::ReceiveParityErrors, XUartNs550::Stats, XUartNs550Stats::StatusInterrupts, XUartNs550Stats::TransmitInterrupts.
Referenced by XUartNs550_CfgInitialize, XUartNs550_SelfTest.
int XUartNs550_SelfTest(XUartNs550 *InstancePtr)
This functions runs a self-test on the driver and hardware device.
This self test performs a local loopback and verifies data can be sent and received.The statistics are cleared at the end of the test. The time for this test to execute is proportional to the baud rate that has been set prior to calling this function. InstancePtr is a pointer to the XUartNs550 instance. - XST_SUCCESS if the test was successful - XST_UART_TEST_FAIL if the test failed looping back the data This function can hang if the hardware is not functioning properly.
References XUartNs550::BaseAddress, XUartNs550::IsReady, XUartNs550_ClearStats, XUartNs550_GetLineStatusReg, XUartNs550_ReadReg, XUartNs550_Recv, XUartNs550_Send, XUartNs550_WriteReg, XUN_IER_OFFSET, XUN_LSR_DATA_READY, XUN_MCR_LOOP, XUN_MCR_OFFSET.
Referenced by UartNs550IntrExample, UartNs550PolledExample, UartNs550SelfTestExample.
static void NoInterruptHandler(XUartNs550 *InstancePtr)
This function handles the case when the value read from the interrupt ID register indicates no interrupt is to be serviced.
InstancePtr is a pointer to the XUartNs550 instance . None. None.
static void ReceiveStatusHandler(XUartNs550 *InstancePtr)
This function handles interrupts for receive status updates which include overrun errors, framing errors, parity errors, and the break interrupt.
InstancePtr is a pointer to the XUartNs550 instance. None. If this handler executes and data is not supposed to be received, then this probably means data is being received that contains errors and the the user may need to clear the receive FIFOs to dump the data.
static void ReceiveTimeoutHandler(XUartNs550 *InstancePtr)
This function handles the receive timeout interrupt.
This interrupt occurs whenever a number of bytes have been present in the FIFO for 4 character times, the receiver is not receiving any data, and the number of bytes present is less than the FIFO threshold. InstancePtr is a pointer to the XUartNs550 instance. None. None.
static void ReceiveDataHandler(XUartNs550 *InstancePtr)
This function handles the interrupt when data is received, either a single byte when FIFOs are not enabled, or multiple bytes with the FIFO.
InstancePtr is a pointer to the XUartNs550 instance. None. None.
static void SendDataHandler(XUartNs550 *InstancePtr)
This function handles the interrupt when data has been sent, the transmit FIFO is empty (transmitter holding register).
InstancePtr is a pointer to the XUartNs550 instance. None. None.
static void ModemHandler(XUartNs550 *InstancePtr)
This function handles modem interrupts.
It does not do any processing except to call the application handler to indicate a modem event. InstancePtr is a pointer to the XUartNs550 instance. None. None.
void XUartNs550_SendByte(UINTPTR BaseAddress, u8 Data)
This function sends a data byte with the UART.
This function operates in the polling mode and blocks until the data has been put into the UART transmit holding register. BaseAddress contains the base address of the UART. Data contains the data byte to be sent. None. None.
References XUartNs550_IsTransmitEmpty, XUartNs550_WriteReg, XUN_THR_OFFSET.
Referenced by XUartNs550_LowLevelExample.
u8 XUartNs550_RecvByte(UINTPTR BaseAddress)
This function receives a byte from the UART.
It operates in a polling mode and blocks until a byte of data is received. BaseAddress contains the base address of the UART. The data byte received by the UART. None.
References XUartNs550_IsReceiveData, XUartNs550_ReadReg, XUN_RBR_OFFSET.
Referenced by XUartNs550_LowLevelExample.
void XUartNs550_SetBaud(UINTPTR BaseAddress, u32 InputClockHz, u32 BaudRate)
Set the baud rate for the UART.
BaseAddress contains the base address of the UART. InputClockHz is the frequency of the input clock to the device in Hertz. BaudRate is the baud rate to be set. None. None.
References XUartNs550_GetLineControlReg, XUartNs550_SetLineControlReg, XUartNs550_WriteReg, XUN_DLL_OFFSET, XUN_DLM_OFFSET, XUN_LCR_DLAB.
Referenced by XUartNs550_LowLevelExample.
static u32 ReadFcrRegister(UINTPTR BaseAddress)
This functions reads the FIFO control register.
It's primary purpose is to isolate the special processing for reading this register. It is necessary to write to the line control register, then read the FIFO control register, and then restore the line control register. BaseAddress contains the base address of the registers in the device. The contents of the FIFO control register. None.
XUN_MAX_BAUD_ERROR_RATE
XUARTNS550_H
XUN_NS16550_MAX_RATE
XUN_NS16550_MIN_RATE
XUartNs550_UpdateStats
XUARTNS550_I_H
XUARTNS550_L_H
XUN_REG_OFFSET
XUN_FIFO_SIZE
XUN_DIVISOR_BYTE_MASK
XUartNs550_ReadReg
Read a UART register.
BaseAddress contains the base address of the device. RegOffset contains the offset from the 1st register of the device to select the specific register. The value read from the register. C-Style signature: u32 XUartNs550_ReadReg(u32 BaseAddress, u32 RegOffset);
Referenced by XUartNs550_GetModemStatus, XUartNs550_GetOptions, XUartNs550_InterruptHandler, XUartNs550_ReceiveBuffer, XUartNs550_Recv, XUartNs550_RecvByte, XUartNs550_SelfTest, XUartNs550_Send, XUartNs550_SendBuffer, XUartNs550_SetOptions.
XUartNs550_WriteReg
Write to a UART register.
BaseAddress contains the base address of the device. RegOffset contains the offset from the 1st register of the device to select the specific register. RegisterValue is the value to be written to the register. None. C-Style signature: u32 XUartNs550_WriteReg(u32 BaseAddress, u32 RegOffset, u32 RegisterValue);
Referenced by XUartNs550_CfgInitialize, XUartNs550_LowLevelExample, XUartNs550_Recv, XUartNs550_SelfTest, XUartNs550_Send, XUartNs550_SendBuffer, XUartNs550_SendByte, XUartNs550_SetBaud, XUartNs550_SetFifoThreshold, XUartNs550_SetOptions.
XUartNs550_GetLineStatusReg
Get the UART Line Status Register.
BaseAddress contains the base address of the device. The value read from the register. C-Style signature: u32 XUartNs550_GetLineStatusReg(u32 BaseAddress);
Referenced by XUartNs550_IsSending, XUartNs550_ReceiveBuffer, XUartNs550_SelfTest, XUartNs550_SendBuffer.
XUartNs550_GetLineControlReg
Get the UART Line Status Register.
BaseAddress contains the base address of the device. The value read from the register. C-Style signature: u32 XUartNs550_GetLineControlReg(u32 BaseAddress);
Referenced by XUartNs550_GetDataFormat, XUartNs550_SetBaud, XUartNs550_SetDataFormat.
XUartNs550_SetLineControlReg
Set the UART Line Status Register.
BaseAddress contains the base address of the device. RegisterValue is the value to be written to the register. None. C-Style signature: void XUartNs550_SetLineControlReg(u32 BaseAddress, u32 RegisterValue);
Referenced by XUartNs550_CfgInitialize, XUartNs550_LowLevelExample, XUartNs550_SetBaud, XUartNs550_SetDataFormat.
XUartNs550_EnableIntr
Enable the transmit and receive interrupts of the UART.
BaseAddress contains the base address of the device. None. C-Style signature: void XUartNs550_EnableIntr(u32 BaseAddress);,
XUartNs550_DisableIntr
Disable the transmit and receive interrupts of the UART.
BaseAddress contains the base address of the device. None. C-Style signature: void XUartNs550_DisableIntr(u32 BaseAddress);,
XUartNs550_IsReceiveData
Determine if there is receive data in the receiver and/or FIFO.
BaseAddress contains the base address of the device. TRUE if there is receive data, FALSE otherwise. C-Style signature: int XUartNs550_IsReceiveData(u32 BaseAddress);,
Referenced by XUartNs550_RecvByte.
XUartNs550_IsTransmitEmpty
Determine if a byte of data can be sent with the transmitter.
BaseAddress contains the base address of the device. TRUE if a byte can be sent, FALSE otherwise. C-Style signature: int XUartNs550_IsTransmitEmpty(u32 BaseAddress);,
Referenced by XUartNs550_SendByte.
XUN_NUM_OPTIONS
XUN_TOTAL_BYTES
XPAR_DEFAULT_BAUD_RATE