xuartns550_sinit.c
XPAR_DEFAULT_BAUD_RATE
XUartNs550_Config * XUartNs550_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XUartNs550_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xuartns550.h for the definition of XUartNs550_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XUartNs550_Config::Name, XUartNs550_ConfigTable.
Referenced by UartNs550IntrExample, XUartNs550_Initialize.
int XUartNs550_Initialize(XUartNs550 *InstancePtr, UINTPTR BaseAddress)
Initializes a specific XUartNs550 instance such that it is ready to be used.
The data format of the device is setup for 8 data bits, 1 stop bit, and no parity by default. The baud rate is set to a default value specified by XPAR_DEFAULT_BAUD_RATE if the symbol is defined, otherwise it is set to 19.2K baud. If the device has FIFOs (16550), they are enabled and the a receive FIFO threshold is set for 8 bytes. The default operating mode of the driver is polled mode. InstancePtr is a pointer to the XUartNs550 instance . BaseAddress contains the base address of the device - XST_SUCCESS if initialization was successful - XST_DEVICE_NOT_FOUND if the device ID/BaseAddress could not be found in the configuration table - XST_UART_BAUD_ERROR if the baud rate is not possible because the input clock frequency is not divisible with an acceptable amount of error In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XUartNs550_Config::BaseAddress, XUartNs550_Config::DefaultBaudRate, XUartNs550_CfgInitialize, XUartNs550_LookupConfig.
Referenced by UartNs550HelloWorldExample, UartNs550IntrExample, UartNs550PolledExample, UartNs550SelfTestExample.