xuartns550_selftest.c
XUN_TOTAL_BYTES
u8 TestString[XUN_TOTAL_BYTES+1][XUN_TOTAL_BYTES+1]
u8 ReturnString[XUN_TOTAL_BYTES+1][XUN_TOTAL_BYTES+1]
int XUartNs550_SelfTest(XUartNs550 *InstancePtr)
This functions runs a self-test on the driver and hardware device.
This self test performs a local loopback and verifies data can be sent and received.The statistics are cleared at the end of the test. The time for this test to execute is proportional to the baud rate that has been set prior to calling this function. InstancePtr is a pointer to the XUartNs550 instance. - XST_SUCCESS if the test was successful - XST_UART_TEST_FAIL if the test failed looping back the data This function can hang if the hardware is not functioning properly.
References XUartNs550::BaseAddress, XUartNs550::IsReady, XUartNs550_ClearStats, XUartNs550_GetLineStatusReg, XUartNs550_ReadReg, XUartNs550_Recv, XUartNs550_Send, XUartNs550_WriteReg, XUN_IER_OFFSET, XUN_LSR_DATA_READY, XUN_MCR_LOOP, XUN_MCR_OFFSET.
Referenced by UartNs550IntrExample, UartNs550PolledExample, UartNs550SelfTestExample.