xuartns550.c
XUN_MAX_BAUD_ERROR_RATE
static void XUartNs550_StubHandler(void *CallBackRef, u32 Event, unsigned int ByteCount)
This function is a stub handler that is the default handler such that if the application has not set the handler when interrupts are enabled, this function will be called.
The function interface has to match the interface specified for a handler even though none of the arguments are used. CallBackRef is unused by this function. Event is unused by this function. ByteCount is unused by this function. None. None.
int XUartNs550_CfgInitialize(XUartNs550 *InstancePtr, XUartNs550_Config *Config, UINTPTR EffectiveAddr)
Initializes a specific XUartNs550 instance such that it is ready to be used.
The data format of the device is setup for 8 data bits, 1 stop bit, and no parity by default. The baud rate is set to a default value specified by Config->DefaultBaudRate if set, otherwise it is set to 19.2K baud. If the device has FIFOs (16550), they are enabled and the a receive FIFO threshold is set for 8 bytes. The default operating mode of the driver is polled mode. InstancePtr is a pointer to the XUartNs550 instance. Config is a reference to a structure containing information about a specific UART 16450/16550 device. XUartNs550_Init initializes an InstancePtr object for a specific device specified by the contents f Config. XUartNs550_Init can initialize multiple instance objects with the use of multiple calls giving different Config information on each call. EffectiveAddr is the device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, use Config->BaseAddress for this parameters, passing the physical address instead. XST_SUCCESS if initialization was successful.XST_UART_BAUD_ERROR if the baud rate is not possible because the input clock frequency is not divisible with an acceptable amount of error. None.
References XUartNs550::BaseAddress, XUartNs550_Config::DefaultBaudRate, XUartNs550::Handler, XUartNs550_Config::InputClockHz, XUartNs550::InputClockHz, XUartNs550::IsReady, XUartNs550Buffer::NextBytePtr, XUartNs550::ReceiveBuffer, XUartNs550Buffer::RemainingBytes, XUartNs550Buffer::RequestedBytes, XUartNs550::SendBuffer, XUartNs550_ClearStats, XUartNs550_SetLineControlReg, XUartNs550_WriteReg, XUN_FCR_OFFSET, XUN_FIFO_ENABLE, XUN_FIFO_RX_TRIG_MSB, XUN_FORMAT_8_BITS.
Referenced by XUartNs550_Initialize.
unsigned int XUartNs550_Send(XUartNs550 *InstancePtr, u8 *BufferPtr, unsigned int NumBytes)
This functions sends the specified buffer of data using the UART in either polled or interrupt driven modes.
This function is non-blocking such that it will return before the data has been sent by the UART. If the UART is busy sending data, it will return and indicate zero bytes were sent.In a polled mode, this function will only send as much data as the UART can buffer, either in the transmitter or in the FIFO if present and enabled. The application may need to call it repeatedly to send a buffer.In interrupt mode, this function will start sending the specified buffer and then the interrupt handler of the driver will continue sending data until the buffer has been sent. A callback function, as specified by the application, will be called to indicate the completion of sending the buffer. InstancePtr is a pointer to the XUartNs550 instance. BufferPtr is pointer to a buffer of data to be sent. NumBytes contains the number of bytes to be sent. A value of zero will stop a previous send operation that is in progress in interrupt mode. Any data that was already put into the transmit FIFO will be sent. The number of bytes actually sent. The number of bytes is not asserted so that this function may be called with a value of zero to stop an operation that is already in progress. This function and the XUartNs550_SetOptions() function modify shared data such that there may be a need for mutual exclusion in a multithreaded environment and if XUartNs550_SetOptions() if called from a handler.
References XUartNs550::BaseAddress, XUartNs550::IsReady, XUartNs550Buffer::NextBytePtr, XUartNs550Buffer::RemainingBytes, XUartNs550Buffer::RequestedBytes, XUartNs550::SendBuffer, XUartNs550_ReadReg, XUartNs550_SendBuffer, XUartNs550_WriteReg, XUN_IER_OFFSET, XUN_IER_TX_EMPTY.
Referenced by UartNs550HelloWorldExample, UartNs550IntrExample, UartNs550PolledExample, XUartNs550_SelfTest.
unsigned int XUartNs550_Recv(XUartNs550 *InstancePtr, u8 *BufferPtr, unsigned int NumBytes)
This function will attempt to receive a specified number of bytes of data from the UART and store it into the specified buffer.
This function is designed for either polled or interrupt driven modes. It is non-blocking such that it will return if no data has already received by the UART.In a polled mode, this function will only receive as much data as the UART can buffer, either in the receiver or in the FIFO if present and enabled. The application may need to call it repeatedly to receive a buffer. Polled mode is the default mode of operation for the driver.In interrupt mode, this function will start receiving and then the interrupt handler of the driver will continue receiving data until the buffer has been received. A callback function, as specified by the application, will be called to indicate the completion of receiving the buffer or when any receive errors or timeouts occur. Interrupt mode must be enabled using the SetOptions function. InstancePtr is a pointer to the XUartNs550 instance. BufferPtr is pointer to buffer for data to be received into NumBytes is the number of bytes to be received. A value of zero will stop a previous receive operation that is in progress in interrupt mode. The number of bytes received. The number of bytes is not asserted so that this function may be called with a value of zero to stop an operation that is already in progress.
References XUartNs550::BaseAddress, XUartNs550::IsReady, XUartNs550Buffer::NextBytePtr, XUartNs550::ReceiveBuffer, XUartNs550Buffer::RemainingBytes, XUartNs550Buffer::RequestedBytes, XUartNs550_ReadReg, XUartNs550_ReceiveBuffer, XUartNs550_WriteReg, XUN_IER_OFFSET.
Referenced by UartNs550IntrExample, UartNs550PolledExample, XUartNs550_SelfTest.
unsigned int XUartNs550_SendBuffer(XUartNs550 *InstancePtr)
This function sends a buffer that has been previously specified by setting up the instance variables of the instance.
This function is designed to be an internal function for the XUartNs550 component such that it may be called from a shell function that sets up the buffer or from an interrupt handler.This function sends the specified buffer of data to the UART in either polled or interrupt driven modes. This function is non-blocking such that it will return before the data has been sent by the UART.In a polled mode, this function will only send as much data as the UART can buffer, either in the transmitter or in the FIFO if present and enabled. The application may need to call it repeatedly to send a buffer.In interrupt mode, this function will start sending the specified buffer and then the interrupt handler of the driver will continue until the buffer has been sent. A callback function, as specified by the application, will be called to indicate the completion of sending the buffer. InstancePtr is a pointer to the XUartNs550 instance. NumBytes is the number of bytes actually sent (put into the UART tranmitter and/or FIFO). None.
References XUartNs550::BaseAddress, XUartNs550Stats::CharactersTransmitted, XUartNs550Buffer::NextBytePtr, XUartNs550Buffer::RemainingBytes, XUartNs550::SendBuffer, XUartNs550::Stats, XUartNs550_GetLineStatusReg, XUartNs550_ReadReg, XUartNs550_WriteReg, XUN_IER_OFFSET, XUN_IER_RX_DATA, XUN_IER_TX_EMPTY, XUN_IIR_OFFSET, XUN_INT_ID_FIFOS_ENABLED, XUN_LSR_TX_BUFFER_EMPTY, XUN_LSR_TX_EMPTY, XUN_THR_OFFSET.
Referenced by XUartNs550_Send.
unsigned int XUartNs550_ReceiveBuffer(XUartNs550 *InstancePtr)
This function receives a buffer that has been previously specified by setting up the instance variables of the instance.
This function is designed to be an internal function for the XUartNs550 component such that it may be called from a shell function that sets up the buffer or from an interrupt handler.This function will attempt to receive a specified number of bytes of data from the UART and store it into the specified buffer. This function is designed for either polled or interrupt driven modes. It is non-blocking such that it will return if there is no data has already received by the UART.In a polled mode, this function will only receive as much data as the UART can buffer, either in the receiver or in the FIFO if present and enabled. The application may need to call it repeatedly to receive a buffer. Polled mode is the default mode of operation for the driver.In interrupt mode, this function will start receiving and then the interrupt handler of the driver will continue until the buffer has been received. A callback function, as specified by the application, will be called to indicate the completion of receiving the buffer or when any receive errors or timeouts occur. Interrupt mode must be enabled using the SetOptions function. InstancePtr is a pointer to the XUartNs550 instance. The number of bytes received. None.
References XUartNs550::BaseAddress, XUartNs550Stats::CharactersReceived, XUartNs550Buffer::NextBytePtr, XUartNs550::ReceiveBuffer, XUartNs550Buffer::RemainingBytes, XUartNs550::Stats, XUartNs550_GetLineStatusReg, XUartNs550_ReadReg, XUN_LSR_BREAK_INT, XUN_LSR_DATA_READY, XUN_RBR_OFFSET.
Referenced by XUartNs550_Recv.
int XUartNs550_SetBaudRate(XUartNs550 *InstancePtr, u32 BaudRate)