xuartns550_l.c
void XUartNs550_SendByte(UINTPTR BaseAddress, u8 Data)
This function sends a data byte with the UART.
This function operates in the polling mode and blocks until the data has been put into the UART transmit holding register. BaseAddress contains the base address of the UART. Data contains the data byte to be sent. None. None.
References XUartNs550_IsTransmitEmpty, XUartNs550_WriteReg, XUN_THR_OFFSET.
Referenced by XUartNs550_LowLevelExample.
u8 XUartNs550_RecvByte(UINTPTR BaseAddress)
This function receives a byte from the UART.
It operates in a polling mode and blocks until a byte of data is received. BaseAddress contains the base address of the UART. The data byte received by the UART. None.
References XUartNs550_IsReceiveData, XUartNs550_ReadReg, XUN_RBR_OFFSET.
Referenced by XUartNs550_LowLevelExample.
void XUartNs550_SetBaud(UINTPTR BaseAddress, u32 InputClockHz, u32 BaudRate)
Set the baud rate for the UART.
BaseAddress contains the base address of the UART. InputClockHz is the frequency of the input clock to the device in Hertz. BaudRate is the baud rate to be set. None. None.
References XUartNs550_GetLineControlReg, XUartNs550_SetLineControlReg, XUartNs550_WriteReg, XUN_DLL_OFFSET, XUN_DLM_OFFSET, XUN_LCR_DLAB.
Referenced by XUartNs550_LowLevelExample.