xuartns550_options.c
XUN_NUM_OPTIONS
Mapping OptionsTable[][]
static u32 ReadFcrRegister(UINTPTR BaseAddress)
This functions reads the FIFO control register.
It's primary purpose is to isolate the special processing for reading this register. It is necessary to write to the line control register, then read the FIFO control register, and then restore the line control register. BaseAddress contains the base address of the registers in the device. The contents of the FIFO control register. None.
u16 XUartNs550_GetOptions(XUartNs550 *InstancePtr)
Gets the options for the specified driver instance.
The options are implemented as bit masks such that multiple options may be enabled or disabled simultaneously. InstancePtr is a pointer to the XUartNs550 instance. The current options for the UART. The options are bit masks that are contained in the file xuartns550.h and named XUN_OPTION_*. None.
References XUartNs550::BaseAddress, XUartNs550::IsReady, XUartNs550_ReadReg, XUN_FCR_OFFSET.
Referenced by UartNs550IntrExample, UartNs550PolledExample.
int XUartNs550_SetOptions(XUartNs550 *InstancePtr, u16 Options)
Sets the options for the specified driver instance.
The options are implemented as bit masks such that multiple options may be enabled or disabled simultaneously.The GetOptions function may be called to retrieve the currently enabled options. The result is ORed in the desired new settings to be enabled and ANDed with the inverse to clear the settings to be disabled. The resulting value is then used as the options for the SetOption function call. InstancePtr is a pointer to the XUartNs550 instance. Options contains the options to be set which are bit masks contained in the file xuartns550.h and named XUN_OPTION_*. XST_SUCCESS if the options were set successfully.XST_UART_CONFIG_ERROR if the options could not be set because the hardware does not support FIFOs None.
References XUartNs550::BaseAddress, XUartNs550::IsReady, XUartNs550_ReadReg, XUartNs550_WriteReg, XUN_FCR_OFFSET.
Referenced by UartNs550IntrExample, UartNs550PolledExample.
u8 XUartNs550_GetFifoThreshold(XUartNs550 *InstancePtr)
This function gets the receive FIFO trigger level.
The receive trigger level indicates the number of bytes in the receive FIFO that cause a receive data event (interrupt) to be generated. InstancePtr is a pointer to the XUartNs550 instance. The current receive FIFO trigger level. Constants which define each trigger level are contained in the file xuartns550.h and named XUN_FIFO_TRIGGER_*. None.
References XUartNs550::BaseAddress, XUartNs550::IsReady, XUN_FIFO_RX_TRIGGER.
int XUartNs550_SetFifoThreshold(XUartNs550 *InstancePtr, u8 TriggerLevel)
This functions sets the receive FIFO trigger level.
The receive trigger level specifies the number of bytes in the receive FIFO that cause a receive data event (interrupt) to be generated. The FIFOs must be enabled to set the trigger level. InstancePtr is a pointer to the XUartNs550 instance. TriggerLevel contains the trigger level to set. Constants which define each trigger level are contained in the file xuartns550.h and named XUN_FIFO_TRIGGER_*. XST_SUCCESS if the trigger level was setXST_UART_CONFIG_ERROR if the trigger level could not be set, either the hardware does not support the FIFOs or FIFOs are not enabled None.
References XUartNs550::BaseAddress, XUartNs550::IsReady, XUartNs550_WriteReg, XUN_FCR_OFFSET, XUN_FIFO_ENABLE, XUN_FIFO_RX_TRIGGER, XUN_FIFO_TRIGGER_01, XUN_FIFO_TRIGGER_04, XUN_FIFO_TRIGGER_08, XUN_FIFO_TRIGGER_14.
u8 XUartNs550_GetLastErrors(XUartNs550 *InstancePtr)
This function returns the last errors that have occurred in the specified UART.
It also clears the errors such that they cannot be retrieved again. The errors include parity error, receive overrun error, framing error, and break detection.The last errors is an accumulation of the errors each time an error is discovered in the driver. A status is checked for each received byte and this status is accumulated in the last errors.If this function is called after receiving a buffer of data, it will indicate any errors that occurred for the bytes of the buffer. It does not indicate which bytes contained errors. InstancePtr is a pointer to the XUartNs550 instance. The last errors that occurred. The errors are bit masks that are contained in the file xuartns550.h and named XUN_ERROR_*. None.
References XUartNs550::LastErrors, XUN_LSR_ERROR_BREAK.
Referenced by UartNs550IntrHandler.
u8 XUartNs550_GetModemStatus(XUartNs550 *InstancePtr)
This function gets the modem status from the specified UART.
The modem status indicates any changes of the modem signals. This function allows the modem status to be read in a polled mode. The modem status is updated whenever it is read such that reading it twice may not yield the same results. InstancePtr is a pointer to the XUartNs550 instance . The modem status which are bit masks that are contained in the file xuartns550.h and named XUN_MODEM_*. The bit masks used for the modem status are the exact bits of the modem status register with no abstraction.
References XUartNs550::BaseAddress, XUartNs550_ReadReg, XUN_MSR_OFFSET.
int XUartNs550_IsSending(XUartNs550 *InstancePtr)
This function determines if the specified UART is sending data.
If the transmitter register is not empty, it is sending data. InstancePtr is a pointer to the XUartNs550 instance. A value of TRUE if the UART is sending data, otherwise FALSE. None.
References XUartNs550::BaseAddress, XUartNs550_GetLineStatusReg, XUN_LSR_TX_EMPTY.