xrfclk.c
Xil_AssertNonvoid
PRINTF
RFCLK_I2C1_DEVICE_PATH
RFCLK_I2C_I2C2SPI_BRIDGE_DEVICE_PATH
FD_BRIDGE
FD_I2C1
LOG
SELECT_SPI_SDO
RF_DATA_READ_BIT
LMX_RESET_VAL
LMK_RESET_VAL
LMK_ADDRESS_STEP
LMK_PORT_ID_MAX
LMK_PORT_STATE_MAX
LMK_DCLKOUTX_DIV_MAX
LMK_DCLKOUTX_MUX_MAX
LMK_SDCLKOUTY_MUX_MAX
LMK_SYSREF_DIV_MIN
LMK_SYSREF_DIV_MAX
LMX_ADDRESS_SHIFT
LMX_ADDRESS_BITFIELD
LMK_ADDRESS_SHIFT
LMK_ADDRESS_BITFIELD
I2C_ADDR_BUS_SWITCH
I2C_ADDR_I2C2SPI_BRIDGE
I2C_ADDR_I2C_IO_EXPANDER
I2C_SWITCH_SELECT_I2C2SPI_BRIDGE
I2C_MUX_SEL_0
I2C_MUX_SEL_1
NUM_IIC_RETRIES
DELAY_100uS
LMX_MUXOUT_REG_ADDR
LMX_MUXOUT_REG_VAL
LMK_MUXOUT_REG_ADDR
LMK_MUXOUT_REG_VAL
MUXOUT_LD_SEL_BIT
LMK_CFG_OUTPUT_PORT0_ADDR
LMK_DCLKOUTX_DIV_PORT0_ADDR
LMK_DCLKOUTX_MUX_PORT0_ADDR
LMK_SDCLKOUTY_MUX_PORT0_ADDR
LMK_SYSREF_DIV_MSB_PORT0_ADDR
LMK_SYSREF_DIV_LSB_PORT0_ADDR
GPIO_DATA_REG
GPIO_CONTROL_REG
GPIO_REG_MASK
int fd_i2c1
int fd_bridge
char GPIO_MUX_SEL0[12][12]
char GPIO_MUX_SEL1[12][12]
u32 MuxOutRegStorage[RFCLK_CHIP_NUM][RFCLK_CHIP_NUM]
static int XRFClk_I2CWrData(int Iic, u8 Addr, u8 *Val, u8 Len)
This function is HAL API for I2c write.
If attempt fails function will repeate IIC write protocol again for DELAY_100uS microseconds multiplied by a loop index number. The procedure will be repeated NUM_IIC_RETRIES times. Descriptor for the i2c driver. Addr address to be written to. Val value to write. Len data length. XST_SUCCESS if successful.XST_FAILURE if failed. None
static int XRFClk_I2CRdData(int Iic, u8 Addr, u8 *Val, u8 Len)
This function is HAL API for I2c read.
If attempt fails function will repeate IIC write protocol again for DELAY_100uS microseconds multiplied by a loop index number. The procedure will be repeated NUM_IIC_RETRIES times. File descriptor for the i2c driver. Addr address to be read. Val read value. Len data length. XST_SUCCESS if successful.XST_FAILURE if failed. None
static int XRFClk_InitI2C(void)
This function is used to open and configure i2c drivers.
None XST_SUCCESS if successful.XST_FAILURE if failed. None
static u32 XRFClk_InitGPIO(void)
This function is used to open and configure MUX_SEL GPIO drivers.
None XST_SUCCESS if successful.XST_FAILURE if failed. None
static u32 XRFClk_InitSPI()
This function is used to configure SPI.
None XST_SUCCESS if successful.XST_FAILURE if failed. None
static u32 XRFClk_MUX_SPI_SDO_GPIOPin(u8 ChipId)
This function is used to set MUX_SEL GPIO pins to connect appropriate SPI SDO.
None XST_SUCCESS if successful.XST_FAILURE if failed. None
static int XRFClk_I2CRdData_sub(int File, u8 Addr, u8 *Val, u8 Len)
This function is HAL API for I2c read.
File descriptor for the i2c driver. Addr address to be read. Val read value. Len data length. XST_SUCCESS if successful.XST_FAILURE if failed. None
static int XRFClk_I2CWrData_sub(int File, u8 Addr, u8 *Val, u8 Len)
This function is HAL API for I2c write.
File descriptor for the i2c driver. Addr address to be written to. Val value to write. Len data length. XST_SUCCESS if successful.XST_FAILURE if failed. None
static int XRFClk_GetBusSwitchI2C1(u8 *val)
This function is used to enable clk104 buses on I2C1 bus switch.
ChipId indicates the RF clock chip Id. XST_SUCCESS if successful.XST_FAILURE if failed. None
static int XRFClk_SetBusSwitchI2C1()
static int XRFClk_MuxSPISDO(u8 ChipId)
This function is used to connect MUX for read from the selected chip.
The function also reconfigure the MUXOUT pin to act as a SPI SDO. The previous setting has been saved. ChipId indicates the RF clock chip Id. XST_SUCCESS if successful.XST_FAILURE if failed. None
static u32 XRFClk_MuxSPISDORevert(u32 ChipId)
This function is used to set MUXOUT pin to the original state after read completion.
Usually the pin is set to indicate a lock state of a PLL. ChipId indicates the RF clock chip Id. XST_SUCCESS if successful.XST_FAILURE if failed. None
u32 XRFClk_WriteReg(u32 ChipId, u32 d)
This function is used to write a register on one of LMX2594 or LMX04828.
ChipId indicates the RF clock chip Id. d = {D2, D1, D0} Where [D0,D1,D2] bits are: LMK04282: bit [23] - 1-bit command field (R/W) bits [22:21] - 2-bit multi-byte field (W1, W0) bits [20:8] - 13-bit address field (A12 to A0) bits [7-0]- 8-bit data field (D7 to D0). LMX2594: bit [23] - 1-bit command field (R/W) bits [22:16] - 7-bit address field (A6 to A0) bits [15-0]- 16-bit data field (D15 to D0). XST_SUCCESS if successful.XST_FAILURE if failed. None
Referenced by XRFClk_ConfigOutputDividerAndMUXOnLMK, XRFClk_ControlOutputPortLMK, XRFClk_ResetChip, XRFClk_SetConfigOnOneChip.
u32 XRFClk_ReadReg(u32 ChipId, u32 *d)
This function is used to read a register from one of LMX2594 or LMX04828.
ChipId indicates the RF clock chip Id. d = {D2, D1, D0} Where [D0,D1,D2] bits are: LMK04282: bit [23] - 1-bit command field (R/W) bits [22:21] - 2-bit multi-byte field (W1, W0) bits [20:8] - 13-bit address field (A12 to A0) bits [7-0]- 8-bit data field (D7 to D0). LMX2594: bit [23] - 1-bit command field (R/W) bits [22:16] - 7-bit address field (A6 to A0) bits [15-0]- 16-bit data field (D15 to D0). XST_SUCCESS if successful.XST_FAILURE if failed. None
u32 XRFClk_Init(int GpioId)
This function is used to initialize RFCLK devices on i2c1-bus: i2c1 bus switch, i2c2spi bridge and MUX_SELx GPIOs.
none GpioId gpio ID for Linux build, n/a for baremetal build. None
void XRFClk_Close(void)
This function is used to close RFCLK devices.
none none None
u32 XRFClk_ResetChip(u32 ChipId)
This function is used to reset one of LMX2594 or LMK04828.
ChipId indicates the RF clock chip Id. XST_SUCCESS if successful.XST_FAILURE if failed. None
References XRFClk_WriteReg.
static u32 XRFClk_SetConfigLMK(u32 ConfigId)
This function is used to set config on LMK.
ConfigId indicates the config Id. XST_SUCCESS if successful.XST_FAILURE if failed. None
static u32 XRFClk_SetConfigLMX(u32 ChipID, u32 ConfigId)
This function is used to set config on LMX.
ChipId indicates the RF clock chip Id. ConfigId indicates the config Id. XST_SUCCESS if successful.XST_FAILURE if failed. None
u32 XRFClk_SetConfigOnOneChipFromConfigId(u32 ChipId, u32 ConfigId)
This function is used to set a full configuration on one of LMX2594 or LMX04828 for the requested frequency.where the register settings is provided from the selected hard coded data.
ChipId indicates the RF clock chip Id. ConfigId indicates the RF clock chip configuration Id. XST_SUCCESS if successful.XST_FAILURE if failed. None
Referenced by XRFClk_SetConfigOnAllChipsFromConfigId.
u32 XRFClk_SetConfigOnOneChip(u32 ChipId, u32 *CfgData, u32 Len)
This function is used to set the full configuration data on one of LMX2594 or LMX04828.
The all register values are passed as a pointer CfgData, Len defines a number of data ready for writing. ChipId indicates the RF clock chip Id. CfgData indicates the configuration for all registers. Len indicates a number of data. XST_SUCCESS if successful.XST_FAILURE if failed. None
References XRFClk_WriteReg.
u32 XRFClk_SetConfigOnAllChipsFromConfigId(u32 ConfigId_LMK, u32 ConfigId_1, u32 ConfigId_2)
This function is used to set a full configuration on all LMX2594 and LMK04828 or LMK04208 for the requested frequency.
ConfigId_LMK indicates the LMK configuration Id. ConfigId_RF1 indicates the LMX RF1 configuration Id. ConfigId_RF2 indicates the LMX RF2 configuration Id. ConfigId_RF3 indicates the LMX RF3 configuration Id. XST_SUCCESS if successful.XST_FAILURE if failed. None
References XRFClk_SetConfigOnOneChipFromConfigId.
static u32 XRFClk_getConfig_fromLMK(u32 ChipId, u32 *in, u32 *out)
This function is used to get config from LMK.
ChipId indicates the RF clock chip Id. in pointer to array of data read from the chip registers. out pointer to array of data read from the chip registers. XST_SUCCESS if successful.XST_FAILURE if failed. None
static u32 XRFClk_getConfig_fromLMX(u32 ChipId, u32 *d)
This function is used to get config from LMK.
ChipId indicates the RF clock chip Id. d pointer to array of data read from the chip registers. XST_SUCCESS if successful.XST_FAILURE if failed. None
u32 XRFClk_GetConfigFromOneChip(u32 ChipId, u32 *CfgData)
This function is used to read the full configuration data from one of LMX2594 or LMX04828.
ChipId indicates the RF clock chip Id. CfgData the array of the RF clock chip configuration data. XST_SUCCESS if successful.XST_FAILURE if failed. None
u32 XRFClk_ControlOutputPortLMK(u32 PortId, u32 State)
This function is used to enable or disable the specified output port on LMK04828.
PortId indicates a LMK04828 port id, [1:7]. State indicates the state of the port, see chapter 9.7.2.7 in lmk04828.pdf datasheet, [0:7] XST_SUCCESS if successful.XST_FAILURE if failed. None
References XRFClk_WriteReg.
u32 XRFClk_ConfigOutputDividerAndMUXOnLMK(u32 PortId, u32 DCLKoutX_DIV, u32 DCLKoutX_MUX, u32 SDCLKoutY_MUX, u32 SYSREF_DIV)
This function is used to configure a clock divider and the output port MUX state on LMK04828.
For the details consult tables 16, 18, 19 and 25 in the lmk04828.pdf datasheet. PortId indicates a LMK04828 port id, [1:7]. DCLKoutX_DIV sets divider for the clock output [0:31]. DCLKoutX_MUX selects input to the device clk buffer [0:3]. SDCLKoutY_MUX sets input to SDCLKoutY [0:1]. SYSREF_DIV sets SYSREF output divider [8:8191] XST_SUCCESS if successful.XST_FAILURE if failed. None
References XRFClk_WriteReg.