xsdps.h
XSDPS_BLK_SIZE_512_MASK
Blk Size 512.
Referenced by XSdPs_GetCsd, XSdPs_HostConfig, XSdPs_MmcCardInitialize, XSdPs_SdModeInit, XSdPs_SetupTransfer.
SD_HS_MODE_ENABLE
User configuration option to enable or disable SD HS mode.
By default SD HS mode is disabled for Versal and enabled for other platforms.
XSDPS_CT_ERROR
Command timeout flag.
Referenced by XSdPs_CardIfCond, XSdPs_CmdTransfer.
MAX_TUNING_COUNT
Maximum Tuning count.
Referenced by XSdPs_AutoTuning.
MAX_TIMEOUT
Maximum Timeout.
Referenced by XSdPs_CheckBusHigh.
XSDPS_CMD8_VOL_PATTERN
CMD8 voltage pattern.
Referenced by XSdPs_CardIfCond.
XSDPS_RESPOCR_READY
Ready response.
Referenced by XSdPs_CardOpCond.
XSDPS_ACMD41_HCS
High Capacity Support.
Referenced by XSdPs_CardOpCond, XSdPs_IdentifyCard.
XSDPS_ACMD41_3V3
3.3 voltage support
Referenced by XSdPs_CardOpCond.
XSDPS_CMD1_HIGH_VOL
CMD1 for High voltage.
Referenced by XSdPs_CardOpCond, XSdPs_IdentifyCard.
XSDPS_CMD1_DUAL_VOL
CMD1 for Dual voltage.
HIGH_SPEED_SUPPORT
High Speed support.
Referenced by XSdPs_SdModeInit.
UHS_SDR12_SUPPORT
SDR12 support.
UHS_SDR25_SUPPORT
SDR25 support.
Referenced by XSdPs_Identify_UhsMode.
UHS_SDR50_SUPPORT
SDR50 support.
Referenced by XSdPs_Identify_UhsMode, XSdPs_SdModeInit.
UHS_SDR104_SUPPORT
SDR104 support.
Referenced by XSdPs_Identify_UhsMode.
UHS_DDR50_SUPPORT
DDR50 support.
Referenced by XSdPs_Identify_UhsMode.
WIDTH_4_BIT_SUPPORT
4-bit width support
Referenced by XSdPs_SdModeInit.
SD_CLK_25_MHZ
25MHz clock
Referenced by XSdPs_SdCardEnum.
SD_CLK_19_MHZ
19MHz clock
Referenced by XSdPs_SdCardEnum.
SD_CLK_26_MHZ
26MHz clock
Referenced by XSdPs_MmcCardEnum.
EXT_CSD_DEVICE_TYPE_BYTE
CSD Device Type byte number.
Referenced by XSdPs_IdentifyEmmcMode, XSdPs_MmcModeInit.
EXT_CSD_SEC_COUNT_BYTE1
CSD Sector count byte 1.
Referenced by XSdPs_EmmcModeInit, XSdPs_MmcModeInit.
EXT_CSD_SEC_COUNT_BYTE2
CSD Sector count byte 2.
Referenced by XSdPs_EmmcModeInit, XSdPs_MmcModeInit.
EXT_CSD_SEC_COUNT_BYTE3
CSD Sector count byte 3.
Referenced by XSdPs_EmmcModeInit, XSdPs_MmcModeInit.
EXT_CSD_SEC_COUNT_BYTE4
CSD Sector count byte 4.
Referenced by XSdPs_EmmcModeInit, XSdPs_MmcModeInit.
EXT_CSD_DEVICE_TYPE_HIGH_SPEED
CSD Device type HS.
Referenced by XSdPs_IdentifyEmmcMode, XSdPs_MmcModeInit.
EXT_CSD_DEVICE_TYPE_DDR_1V8_HIGH_SPEED
CSD Dev type DDR 1.8v speed.
Referenced by XSdPs_IdentifyEmmcMode.
EXT_CSD_DEVICE_TYPE_DDR_1V2_HIGH_SPEED
CSD Dev type DDR 1.2v speed.
Referenced by XSdPs_IdentifyEmmcMode.
EXT_CSD_DEVICE_TYPE_SDR_1V8_HS200
CSD SDR 1.8v HS200.
Referenced by XSdPs_IdentifyEmmcMode.
EXT_CSD_DEVICE_TYPE_SDR_1V2_HS200
CSD SDR 1.2v HS200.
Referenced by XSdPs_IdentifyEmmcMode.
EXT_CSD_DEVICE_TYPE_DDR_1V8_HS400
CSD SDR 1.8v HS400.
Referenced by XSdPs_IdentifyEmmcMode.
EXT_CSD_DEVICE_TYPE_DDR_1V2_HS400
CSD SDR 1.2v HS400.
Referenced by XSdPs_IdentifyEmmcMode.
CSD_SPEC_VER_3
CSD card spec ver 3.
Referenced by XSdPs_MmcCardInitialize.
SCR_SPEC_VER_3
SCR spec ver 3.
Referenced by XSdPs_SdModeInit.
ADDRESS_BEYOND_32BIT
Macro used for beyond 32-bit addr.
Referenced by XSdPs_SetupReadDma, XSdPs_SetupWriteDma.
XSDPS_ZYNQMP_SD0_BASE
ZynqMP SD0 Baseaddress.
Referenced by XSdPs_ConfigTapDelay, XSdPs_DllRstCtrl.
XSDPS_ZYNQMP_SD1_BASE
ZynqMP SD1 Baseaddress.
XSDPS_VERSAL_SD0_BASE
Versal SD0 Baseaddress.
XSDPS_VERSAL_SD1_BASE
Versal SD1 Baseaddress.
ENABLE_HS400_MODE
Enable eMMC HS400 mode for Versal Net platform.
XSdPs_Config XSdPs_ConfigTable[][]
XSdPs Configuration Table.
XSdPs Configuration Table.
Referenced by XSdPs_LookupConfig.
XSdPs_Config * XSdPs_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XSdPs_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xsdps.h for the definition of XSdPs_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XSdPs_Config::Name, XSdPs_ConfigTable.
s32 XSdPs_CfgInitialize(XSdPs *InstancePtr, XSdPs_Config *ConfigPtr, UINTPTR EffectiveAddr)
Initializes a specific XSdPs instance so that the driver is ready to use.
InstancePtr Pointer to the XSdPs instance. ConfigPtr Reference to a structure containing information about a specific SD device. This function initializes an InstancePtr object for a specific device specified by the contents of Configuration. EffectiveAddr Device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, use ConfigPtr->Config. BaseAddress for this device. XST_SUCCESS if successful.XST_DEVICE_IS_STARTED if the device is already started. It must be stopped to re-initialize. This function initializes the host controller. Initial clock of 400 KHz is set. Voltage of 3.3 V is selected as that is supported by host. Interrupts status is enabled and signal disabled by default. Default data direction is card to host and 32 bit ADMA2 is selected. Default Block size is 512 bytes.
References XSdPs_Config::BankNumber, XSdPs_Config::BaseAddress, XSdPs::BlkSize, XSdPs_Config::BusWidth, XSdPs_Config::CardDetect, XSdPs::Config, XSdPs::Dma64BitAddr, XSdPs_Config::HasEMIO, XSdPs::HC_Version, XSdPs::Host_Caps, XSdPs_Config::InputClockHz, XSdPs::IsBusy, XSdPs_Config::IsCacheCoherent, XSdPs::IsReady, XSdPs::IsTuningDone, XSdPs::ITapDelay, XSdPs_Config::ITapDly_DDR_Clk50, XSdPs_Config::ITapDly_SDR_Clk50, XSdPs::Mode, XSdPs::OTapDelay, XSdPs_Config::OTapDly_DDR_Clk200, XSdPs_Config::OTapDly_DDR_Clk50, XSdPs_Config::OTapDly_SDR_Clk100, XSdPs_Config::OTapDly_SDR_Clk200, XSdPs_Config::OTapDly_SDR_Clk50, XSdPs_Config::RefClk, XSdPs::SectorCount, XSdPs::SlcrBaseAddr, XSdPs_Config::SlotType, XSdPs_Config::WriteProtect, XSdPs_HostConfig, XSdPs_ResetConfig.
s32 XSdPs_CardInitialize(XSdPs *InstancePtr)
Initializes Card with Identification mode sequence.
InstancePtr Pointer to the instance to be worked on. XST_SUCCESS if initialization was successfulXST_FAILURE if failure - could be because a) SD is already initialized b) There is no card inserted c) One of the steps (commands) in the initialization cycle failed
References XSdPs::BusSpeed, XSdPs::BusWidth, XSdPs::CardType, XSdPs::Config, XSdPs::IsReady, XSdPs_Config::RefClk, XSdPs::Switch1v8, XSdPs_Change_ClkFreq, XSdPs_IdentifyCard, XSdPs_MmcCardInitialize, XSdPs_SdCardInitialize.
s32 XSdPs_ReadPolled(XSdPs *InstancePtr, u32 Arg, u32 BlkCnt, u8 *Buff)
Performs SD read in polled mode.
InstancePtr Pointer to the instance to be worked on. Arg Address passed by the user that is to be sent as argument along with the command. BlkCnt Block count passed by the user. Buff Pointer to the data buffer for a DMA transfer. XST_SUCCESS if initialization was successfulXST_FAILURE if failure - could be because another transfer is in progress or command or data inhibit is set
References XSdPs::BlkSize, XSdPs::Config, XSdPs::IsBusy, XSdPs_Config::IsCacheCoherent, XSdPs::IsReady, XSdPs_Config::RefClk, XSdps_CheckTransferDone, XSdPs_Read, XSdPs_SetupTransfer.
s32 XSdPs_WritePolled(XSdPs *InstancePtr, u32 Arg, u32 BlkCnt, const u8 *Buff)
Performs SD write in polled mode.
InstancePtr Pointer to the instance to be worked on. Arg Address passed by the user that is to be sent as argument along with the command. BlkCnt Block count passed by the user. Buff Pointer to the data buffer for a DMA transfer. XST_SUCCESS if initialization was successfulXST_FAILURE if failure - could be because another transfer is in progress or command or data inhibit is set
References XSdPs::Config, XSdPs::IsBusy, XSdPs::IsReady, XSdPs_Config::RefClk, XSdps_CheckTransferDone, XSdPs_SetupTransfer, XSdPs_Write.
s32 XSdPs_Idle(XSdPs *InstancePtr)
API to idle the SDIO Interface.
InstancePtr Pointer to the XSdPs instance. None
References XSdPs::Config, XSdPs::IsReady, XSdPs_Config::RefClk, XSdPs_CheckBusIdle, XSdPs_DisableBusPower, XSdPs_Reset.
s32 XSdPs_Change_BusSpeed(XSdPs *InstancePtr)
Sets high speed in card and host.
Changes clock in host accordingly. InstancePtr Pointer to the XSdPs instance. XST_SUCCESS if successful.XST_FAILURE if fail.
References XSdPs_Config::BaseAddress, XSdPs::BusSpeed, XSdPs::CardType, XSdPs::Config, XSdPs::IsReady, XSdPs::IsTuningDone, XSdPs::Mode, XSdPs_Change_ClkFreq, XSdPs_Change_MmcBusSpeed, XSdPs_Change_SdBusSpeed, XSdPs_Execute_Tuning.
Referenced by XSdPs_EmmcModeInit, XSdPs_MmcModeInit, XSdPs_SdModeInit.
s32 XSdPs_Change_ClkFreq(XSdPs *InstancePtr, u32 SelFreq)
API to change clock frequency to a given value.
InstancePtr Pointer to the XSdPs instance. SelFreq Clock frequency in Hz. None This API will change clock frequency to the value less than or equal to the given value using the permissible dividers.
References XSdPs_Config::BaseAddress, XSdPs::CardType, XSdPs::Config, XSdPs::HC_Version, XSdPs::IsReady, XSdPs::ITapDelay, XSdPs::Mode, XSdPs::OTapDelay, XSdPs_SetClock, XSdPs_SetTapDelay.
Referenced by XSdPs_CardInitialize, XSdPs_Change_BusSpeed, XSdPs_MmcCardEnum, XSdPs_SdCardEnum.
s32 XSdPs_Pullup(XSdPs *InstancePtr)
Sends pullup command to card before using DAT line 3(using 4-bit bus).
InstancePtr Pointer to the XSdPs instance. XST_SUCCESS if successful.XST_FAILURE if fail.
References XSdPs::IsReady, XSdPs::RelCardAddr, XSdPs_CmdTransfer.
s32 XSdPs_Get_BusWidth(XSdPs *InstancePtr, u8 *ReadBuff)
Gets bus width support by card.
InstancePtr Pointer to the XSdPs instance. ReadBuff Buffer to store SCR register returned by card. XST_SUCCESS if successful.XST_FAILURE if fail. None.
References XSdPs::Config, XSdPs_Config::IsCacheCoherent, XSdPs::IsReady, XSdPs::RelCardAddr, XSdps_CheckTransferDone, XSdPs_CmdTransfer, XSdPs_SetupReadDma.
Referenced by XSdPs_SdModeInit.
s32 XSdPs_Change_BusWidth(XSdPs *InstancePtr)
Sets bus width to 4-bit in card and host.
InstancePtr Pointer to the XSdPs instance. XST_SUCCESS if successful.XST_FAILURE if fail.
References XSdPs_Config::BaseAddress, XSdPs_Config::BusWidth, XSdPs::BusWidth, XSdPs::CardType, XSdPs::Config, XSdPs::HC_Version, XSdPs::IsReady, XSdPs::Mode, XSdPs::RelCardAddr, XSdPs_CmdTransfer, XSdPs_Set_Mmc_ExtCsd.
Referenced by XSdPs_EmmcModeInit, XSdPs_MmcModeInit, XSdPs_SdModeInit.
s32 XSdPs_Get_BusSpeed(XSdPs *InstancePtr, u8 *ReadBuff)
Gets bus speed supported by card.
InstancePtr Pointer to the XSdPs instance. ReadBuff Buffer to store function group support data returned by card. XST_SUCCESS if successful.XST_FAILURE if fail. None.
References XSdPs::Config, XSdPs_Config::IsCacheCoherent, XSdPs::IsReady, XSdps_CheckTransferDone, XSdPs_CmdTransfer, XSdPs_SetupReadDma.
Referenced by XSdPs_SdModeInit.
s32 XSdPs_Get_Mmc_ExtCsd(XSdPs *InstancePtr, u8 *ReadBuff)
Gets EXT_CSD register of eMMC.
InstancePtr Pointer to the XSdPs instance. ReadBuff Buffer to store EXT_CSD XST_SUCCESS if successful.XST_FAILURE if fail.
References XSdPs::Config, XSdPs_Config::IsCacheCoherent, XSdPs::IsReady, XSdps_CheckTransferDone, XSdPs_CmdTransfer, XSdPs_SetupReadDma.
Referenced by XSdPs_CheckEmmcTiming, XSdPs_EmmcModeInit, XSdPs_MmcModeInit.
s32 XSdPs_Set_Mmc_ExtCsd(XSdPs *InstancePtr, u32 Arg)
Writes EXT_CSD register of eMMC.
InstancePtr Pointer to the XSdPs instance. Arg Argument to be sent along with the command. XST_SUCCESS if successful.XST_FAILURE if fail.
References XSdPs::IsReady, XSdps_CheckTransferDone, XSdPs_CmdTransfer.
Referenced by XSdPs_Change_BusWidth, XSdPs_EmmcModeInit, XSdPs_Sanitize.
s32 XSdPs_SetBlkSize(XSdPs *InstancePtr, u16 BlkSize)
Updates Block size for read/write operations.
InstancePtr Pointer to the instance to be worked on. BlkSize Block size passed by the user. None
References XSdPs_Config::BaseAddress, XSdPs::BlkSize, XSdPs::Config, XSdPs::IsReady, XSdPs_CheckBusIdle, XSdPs_CmdTransfer.
Referenced by XSdPs_MmcCardInitialize, XSdPs_SdModeInit, XSdPs_SetupTransfer.
s32 XSdPs_Get_Status(XSdPs *InstancePtr, u8 *SdStatReg)
Gets SD card status information.
InstancePtr Pointer to the XSdPs instance. SdStatReg Buffer to store status data returned by card. XST_SUCCESS if successful.XST_FAILURE if fail.
References XSdPs::Config, XSdPs_Config::IsCacheCoherent, XSdPs::IsReady, XSdPs::RelCardAddr, XSdps_CheckTransferDone, XSdPs_CmdTransfer, XSdPs_SetupReadDma.
s32 XSdPs_Select_Card(XSdPs *InstancePtr)
Selects card and sets default block size.
InstancePtr Pointer to the XSdPs instance. XST_SUCCESS if successful.XST_FAILURE if fail.XSDPS_CT_ERROR if Command Transfer fail.
References XSdPs::IsReady, XSdPs::RelCardAddr, XSdPs_CmdTransfer.
Referenced by XSdPs_MmcCardEnum, XSdPs_SdCardEnum.
s32 XSdPs_StartReadTransfer(XSdPs *InstancePtr, u32 Arg, u32 BlkCnt, u8 *Buff)
Performs SD read in polled mode.
InstancePtr Pointer to the instance to be worked on. Arg Address passed by the user that is to be sent as argument along with the command. BlkCnt Block count passed by the user. Buff Pointer to the data buffer for a DMA transfer. XST_SUCCESS if Transfer initialization was successfulXST_FAILURE if failure - could be because another transfer is in progress or command or data inhibit is set
References XSdPs::IsBusy, XSdPs::IsReady, XSdPs_Read, XSdPs_SetupTransfer.
s32 XSdPs_CheckReadTransfer(XSdPs *InstancePtr)
Checks if the transfer is completed successfully.
InstancePtr Pointer to the instance to be worked on. XST_SUCCESS if transfer was successfulXST_FAILURE if failureXST_DEVICE_BUSY - if the transfer is still in progress
References XSdPs::IsReady, XSdPs_CheckTransferComplete.
s32 XSdPs_StartWriteTransfer(XSdPs *InstancePtr, u32 Arg, u32 BlkCnt, u8 *Buff)
Starts SD write transfer.
InstancePtr Pointer to the instance to be worked on. Arg Address passed by the user that is to be sent as argument along with the command. BlkCnt Block count passed by the user. Buff Pointer to the data buffer for a DMA transfer. XST_SUCCESS if Transfer initialization was successfulXST_FAILURE if failure - could be because another transfer is in progress or command or data inhibit is set
References XSdPs::IsBusy, XSdPs::IsReady, XSdPs_SetupTransfer, XSdPs_Write.
s32 XSdPs_CheckWriteTransfer(XSdPs *InstancePtr)
Checks for the write transfer completed.
InstancePtr Pointer to the instance to be worked on. XST_SUCCESS if transfer was successfulXST_FAILURE if failureXST_DEVICE_BUSY - if the transfer is still in progress
References XSdPs::IsReady, XSdPs_CheckTransferComplete.
s32 XSdPs_Erase(XSdPs *InstancePtr, u32 StartAddr, u32 EndAddr)
Performs Erase operation on the given address range.
InstancePtr Pointer to the instance to be worked on. StartAddr Address of the first write block to be erased. EndAddr Address of the last write block of the continuous range to be erased. XST_SUCCESS if erase is successfulXST_FAILURE if failure - could be because another transfer is in progress or card not present or erase operation failure.
References XSdPs_Config::BaseAddress, XSdPs_Config::CardDetect, XSdPs::CardSpecData, XSdPs::Config, XSdPs::HC_Version, XSdPs::Host_Caps, XSdPs::IsBusy, XSdPs::IsReady, XSdPs_Config::RefClk, XSdPs::TransferMode, XSdPs_SendErase, XSdPs_SetEndAddr, XSdPs_SetStartAddr.
s32 XSdPs_Sanitize(XSdPs *InstancePtr)
Performs Sanitize operation on the unmapped user address range.
InstancePtr Pointer to the instance to be worked on. XST_SUCCESS if Sanitize is successfulXST_FAILURE if failure - could be because another transfer is in progress or card not present or Sanitize operation failure.
References XSdPs::Config, XSdPs::IsBusy, XSdPs::IsReady, XSdPs_Config::RefClk, XSdPs_Set_Mmc_ExtCsd.