xsdps_card.c
s32 XSdPs_Read(XSdPs *InstancePtr, u32 Arg, u32 BlkCnt, u8 *Buff)
Performs SD read in polled mode.
InstancePtr Pointer to the instance to be worked on. Arg Address passed by the user that is to be sent as argument along with the command. BlkCnt - Block count passed by the user. Buff - Pointer to the data buffer for a DMA transfer. XST_SUCCESS if initialization was successfulXST_FAILURE if failure - could be because another transfer is in progress or command or data inhibit is set
References XSdPs::BlkSize, XSdPs_CmdTransfer, XSdPs_SetupReadDma.
Referenced by XSdPs_ReadPolled, XSdPs_StartReadTransfer.
s32 XSdPs_Write(XSdPs *InstancePtr, u32 Arg, u32 BlkCnt, const u8 *Buff)
Performs SD write in polled mode.
InstancePtr Pointer to the instance to be worked on. Arg Address passed by the user that is to be sent as argument along with the command. BlkCnt - Block count passed by the user. Buff - Pointer to the data buffer for a DMA transfer. XST_SUCCESS if initialization was successfulXST_FAILURE if failure - could be because another transfer is in progress or command or data inhibit is set
References XSdPs::BlkSize, XSdPs_CmdTransfer, XSdPs_SetupWriteDma.
Referenced by XSdPs_StartWriteTransfer, XSdPs_WritePolled.
s32 XSdPs_CheckTransferComplete(XSdPs *InstancePtr)
Checks for the transfer complete.
InstancePtr Pointer to the instance to be worked on. XST_SUCCESS if transfer was successfulXST_FAILURE if failureXST_DEVICE_BUSY - if the transfer is still in progress
References XSdPs_Config::BaseAddress, XSdPs::Config, XSdPs::IsBusy.
Referenced by XSdPs_CheckReadTransfer, XSdPs_CheckWriteTransfer.
s32 XSdPs_IdentifyCard(XSdPs *InstancePtr)
Identifies type of card using CMD0 + CMD1 sequence.
InstancePtr Pointer to the XSdPs instance.
References XSdPs_Config::BaseAddress, XSdPs::CardType, XSdPs::Config, XSdPs::HC_Version, XSdPs::Host_Caps, XSDPS_ACMD41_HCS, XSDPS_CMD1_HIGH_VOL, XSdPs_CmdTransfer, XSdPs_Reset.
Referenced by XSdPs_CardInitialize.
s32 XSdPs_SdCardInitialize(XSdPs *InstancePtr)
This function Initializes SD.
InstancePtr Pointer to the instance to be worked on. XST_SUCCESS if initialization was successfulXST_FAILURE if failure - could be because a) SD is already initialized b) There is no card inserted c) One of the steps (commands) in the initialization cycle failed This function initializes the SD card by following its initialization and identification state diagram. CMD0 is sent to reset card. CMD8 and ACDM41 are sent to identify voltage and high capacity support CMD2 and CMD3 are sent to obtain Card ID and Relative card address respectively. CMD9 is sent to read the card specific data.
References XSdPs_Config::BusWidth, XSdPs::Config, XSdPs_SdCardEnum, XSdPs_SdModeInit.
Referenced by XSdPs_CardInitialize.
s32 XSdPs_MmcCardInitialize(XSdPs *InstancePtr)
This function initializes MMC.
InstancePtr Pointer to the instance to be worked on. XST_SUCCESS if initialization was successfulXST_FAILURE if failure - could be because a) MMC is already initialized b) There is no card inserted c) One of the steps (commands) in the initialization cycle failed This function initializes the SD card by following its initialization and identification state diagram. CMD0 is sent to reset card. CMD1 sent to identify voltage and high capacity support CMD2 and CMD3 are sent to obtain Card ID and Relative card address respectively. CMD9 is sent to read the card specific data.
References XSdPs_Config::BaseAddress, XSdPs::BlkSize, XSdPs::Card_Version, XSdPs::CardType, XSdPs::Config, CSD_SPEC_VER_3, XSdPs::HC_Version, XSdPs::Mode, XSDPS_BLK_SIZE_512_MASK, XSdPs_EmmcModeInit, XSdPs_MmcCardEnum, XSdPs_MmcModeInit, XSdPs_SetBlkSize.
Referenced by XSdPs_CardInitialize.
s32 XSdPs_CheckCardDetect(XSdPs *InstancePtr)
Checks if the card is present or not.
InstancePtr Pointer to the instance to be worked on. None
References XSdPs_Config::BaseAddress, XSdPs_Config::CardDetect, XSdPs::Config, XSdPs::HC_Version, XSdPs::Host_Caps.
Referenced by XSdPs_MmcCardEnum, XSdPs_SdCardEnum.
s32 XSdPs_CardReset(XSdPs *InstancePtr)
Sends CMD0 to reset the card.
InstancePtr Pointer to the instance to be worked on. None
References XSdPs_CmdTransfer.
Referenced by XSdPs_MmcCardEnum, XSdPs_SdCardEnum.
s32 XSdPs_CardIfCond(XSdPs *InstancePtr)
Sends command to get the card interface details.
InstancePtr Pointer to the instance to be worked on. None
References XSdPs_Config::BaseAddress, XSdPs::Card_Version, XSdPs::Config, XSDPS_CMD8_VOL_PATTERN, XSdPs_CmdTransfer, XSDPS_CT_ERROR, XSdPs_Reset.
Referenced by XSdPs_SdCardEnum.
s32 XSdPs_CardOpCond(XSdPs *InstancePtr)
Sends command to get the card operating condition.
InstancePtr Pointer to the instance to be worked on. None
References XSdPs_Config::BaseAddress, XSdPs_Config::BusWidth, XSdPs::CardType, XSdPs::Config, XSdPs::HC_Version, XSdPs::HCS, XSdPs::Switch1v8, XSDPS_ACMD41_3V3, XSDPS_ACMD41_HCS, XSDPS_CMD1_HIGH_VOL, XSdPs_CmdTransfer, XSDPS_RESPOCR_READY, XSdPs_Switch_Voltage.
Referenced by XSdPs_MmcCardEnum, XSdPs_SdCardEnum.
s32 XSdPs_GetCardId(XSdPs *InstancePtr)
Gets the card ID.
InstancePtr Pointer to the instance to be worked on. None
References XSdPs_Config::BaseAddress, XSdPs::CardID, XSdPs::CardType, XSdPs::Config, XSdPs::RelCardAddr, XSdPs_CmdTransfer.
Referenced by XSdPs_MmcCardEnum, XSdPs_SdCardEnum.
s32 XSdPs_GetCsd(XSdPs *InstancePtr)
Gets the CSD register from the card.
InstancePtr Pointer to the instance to be worked on. None
References XSdPs_Config::BaseAddress, XSdPs::Card_Version, XSdPs::CardSpecData, XSdPs::CardType, XSdPs::Config, XSdPs::RelCardAddr, XSdPs::SectorCount, XSDPS_BLK_SIZE_512_MASK, XSdPs_CmdTransfer.
Referenced by XSdPs_MmcCardEnum, XSdPs_SdCardEnum.
s32 XSdPs_CardSetVoltage18(XSdPs *InstancePtr)
Sets the card voltage to 1.8 V.
InstancePtr Pointer to the instance to be worked on. None
References XSdPs_Config::BaseAddress, XSdPs::Config, XSdPs_EnableClock, XSdPs_SetVoltage18.
Referenced by XSdPs_SdModeInit, XSdPs_Switch_Voltage.
s32 XSdPs_ResetConfig(XSdPs *InstancePtr)
Configures the initial Reset.
InstancePtr Pointer to the instance to be worked on. None
References XSdPs_Config::BaseAddress, XSdPs::Config, XSdPs::Host_Caps, XSdPs_DisableBusPower, XSdPs_EnableBusPower, XSdPs_Reset.
Referenced by XSdPs_CfgInitialize.
void XSdPs_HostConfig(XSdPs *InstancePtr)
Configures the initial Host.
InstancePtr Pointer to the instance to be worked on. None
References XSdPs_Config::BaseAddress, XSdPs::Config, XSdPs::TransferMode, XSDPS_BLK_SIZE_512_MASK, XSdPs_ConfigDma, XSdPs_ConfigInterrupt, XSdPs_ConfigPower.
Referenced by XSdPs_CfgInitialize.
s32 XSdPs_CheckResetDone(XSdPs *InstancePtr, u8 Value)
Checks for Reset Done bits to be cleared after a reset assert.
InstancePtr Pointer to the instance to be worked on. Value Bits to be checked to be cleared. None
References XSdPs_Config::BaseAddress, XSdPs::Config.
Referenced by XSdPs_Reset.
s32 XSdPs_SetupVoltageSwitch(XSdPs *InstancePtr)
Sets up the voltage switch.
InstancePtr Pointer to the instance to be worked on. None
References XSdPs_Config::BaseAddress, XSdPs::Config, XSdPs_CmdTransfer.
Referenced by XSdPs_Switch_Voltage.
s32 XSdPs_CheckBusHigh(XSdPs *InstancePtr)
Check if the CMD and DAT buses are high.
InstancePtr Pointer to the instance to be worked on. None
References XSdPs_Config::BaseAddress, XSdPs::Config, MAX_TIMEOUT.
Referenced by XSdPs_Switch_Voltage.
void XSdPs_Identify_UhsMode(XSdPs *InstancePtr, u8 *ReadBuff)
API to Identify the supported UHS mode.
This API will assign the corresponding tap delay API to the Config_TapDelay pointer based on the supported bus speed. InstancePtr Pointer to the XSdPs instance. ReadBuff Contains the response for CMD6 None.
References XSdPs::Config, XSdPs_Config::InputClockHz, XSdPs::Mode, UHS_DDR50_SUPPORT, UHS_SDR104_SUPPORT, UHS_SDR25_SUPPORT, UHS_SDR50_SUPPORT, XSdPs_SetTapDelay_DDR50, XSdPs_SetTapDelay_SDR104, XSdPs_SetTapDelay_SDR25, XSdPs_SetTapDelay_SDR50.
Referenced by XSdPs_SdModeInit.
void XSdPs_SetTapDelay(XSdPs *InstancePtr)
API to set Tap Delay with respect to the speed modes.
InstancePtr Pointer to the XSdPs instance. None
References XSdPs::Mode, XSdPs_ConfigTapDelay, XSdPs_DllRstCtrl.
Referenced by XSdPs_Change_ClkFreq.
s32 XSdPs_Change_SdBusSpeed(XSdPs *InstancePtr)
Changes the SD Bus Speed.
InstancePtr Pointer to the instance to be worked on. None
References XSdPs_Config::BaseAddress, XSdPs::Config, XSdPs::Mode, XSdPs::Switch1v8, XSdPs_CalcBusSpeed, XSdps_CheckTransferDone, XSdPs_CmdTransfer, XSdPs_SetupReadDma.
Referenced by XSdPs_Change_BusSpeed.
s32 XSdPs_Change_MmcBusSpeed(XSdPs *InstancePtr)
Changes the eMMC bus speed.
InstancePtr Pointer to the instance to be worked on. None
References XSdPs_CalcBusSpeed, XSdps_CheckTransferDone, XSdPs_CmdTransfer.
Referenced by XSdPs_Change_BusSpeed.
s32 XSdPs_AutoTuning(XSdPs *InstancePtr)
This function is used to do the Auto tuning.
InstancePtr Pointer to the instance to be worked on. None
References XSdPs_Config::BaseAddress, XSdPs::BusWidth, XSdPs::CardType, XSdPs::Config, MAX_TUNING_COUNT, XSdPs::TransferMode, XSdPs_CmdTransfer, XSdPs_SetExecTuning.
Referenced by XSdPs_Execute_Tuning.
void XSdPs_SetupADMA2DescTbl(XSdPs *InstancePtr, u32 BlkCnt, const u8 *Buff)
API to setup ADMA2 descriptor table.
InstancePtr Pointer to the XSdPs instance. BlkCnt Block count. Buff Pointer to data buffer. None
References XSdPs::HC_Version, XSdPs_Setup32ADMA2DescTbl, XSdPs_Setup64ADMA2DescTbl.
Referenced by XSdPs_SetupReadDma, XSdPs_SetupWriteDma.
void XSdPs_SetupADMA2DescTbl64Bit(XSdPs *InstancePtr, u32 BlkCnt)
API to setup ADMA2 descriptor table for 64 Bit DMA.
InstancePtr Pointer to the XSdPs instance. BlkCnt Block count. None
References XSdPs_Adma2Descriptor64::Address, XSdPs::Adma2_DescrTbl64, XSdPs_Adma2Descriptor64::Attribute, XSdPs_Config::BaseAddress, XSdPs::Config, XSdPs::Dma64BitAddr, XSdPs_Config::IsCacheCoherent, XSdPs_Adma2Descriptor64::Length.
Referenced by XSdPs_SetupReadDma, XSdPs_SetupWriteDma.
s32 XSdPs_DllReset(XSdPs *InstancePtr)
API to reset the DLL.
InstancePtr Pointer to the XSdPs instance. None
References XSdPs_Config::BaseAddress, XSdPs::Config, XSdPs_DllRstCtrl, XSdPs_EnableClock.
Referenced by XSdPs_Execute_Tuning.
void XSdPs_IdentifyEmmcMode(XSdPs *InstancePtr, const u8 *ExtCsd)
Identifies the eMMC speed mode.
InstancePtr Pointer to the instance to be worked on. ExtCsd Extended CSD register from the card. None
References XSdPs_Config::BankNumber, XSdPs::BusWidth, XSdPs::Config, EXT_CSD_DEVICE_TYPE_BYTE, EXT_CSD_DEVICE_TYPE_DDR_1V2_HIGH_SPEED, EXT_CSD_DEVICE_TYPE_DDR_1V2_HS400, EXT_CSD_DEVICE_TYPE_DDR_1V8_HIGH_SPEED, EXT_CSD_DEVICE_TYPE_DDR_1V8_HS400, EXT_CSD_DEVICE_TYPE_HIGH_SPEED, EXT_CSD_DEVICE_TYPE_SDR_1V2_HS200, EXT_CSD_DEVICE_TYPE_SDR_1V8_HS200, XSdPs::IsTuningDone, XSdPs::ITapDelay, XSdPs_Config::ITapDly_DDR_Clk50, XSdPs_Config::ITapDly_SDR_Clk50, XSdPs::Mode, XSdPs::OTapDelay, XSdPs_Config::OTapDly_DDR_Clk50, XSdPs_Config::OTapDly_SDR_Clk200, XSdPs_Config::OTapDly_SDR_Clk50.
Referenced by XSdPs_EmmcModeInit.
s32 XSdPs_CheckEmmcTiming(XSdPs *InstancePtr, u8 *ExtCsd)
Checks the eMMC timing.
InstancePtr Pointer to the instance to be worked on. ExtCsd Extended CSD register from the card. None
References XSdPs::Mode, XSdPs_Get_Mmc_ExtCsd.
Referenced by XSdPs_EmmcModeInit.
s32 XSdPs_SetClock(XSdPs *InstancePtr, u32 SelFreq)
Sets the clock to the passed frequency.
InstancePtr Pointer to the instance to be worked on. SelFreq Selected frequency None
References XSdPs_Config::BaseAddress, XSdPs::CardType, XSdPs::Config, XSdPs::Mode, XSdPs_CalcClock, XSdPs_EnableClock.
Referenced by XSdPs_Change_ClkFreq.
s32 XSdPs_CheckVoltage18(XSdPs *InstancePtr)
Checks if the voltage is set to 1.8 V or not.
InstancePtr Pointer to the instance to be worked on. XST_SUCCESS if voltage is 1.8VXST_FAILURE if voltage is not 1.8V
References XSdPs_Config::BaseAddress, XSdPs::Config.
Referenced by XSdPs_SetVoltage18.
s32 XSdPs_SetupCmd(XSdPs *InstancePtr, u32 Arg, u32 BlkCnt)
Initializes the command sequence.
InstancePtr Pointer to the instance to be worked on. Arg Address passed by the user that is to be sent as argument along with the command. BlkCnt - Block count passed by the user. None
References XSdPs_Config::BaseAddress, XSdPs::Config, XSdPs_CheckBusIdle.
Referenced by XSdPs_CmdTransfer.
s32 XSdPs_SendCmd(XSdPs *InstancePtr, u32 Cmd)
Initiates the Cmd transfer to SD card.
InstancePtr Pointer to the instance to be worked on. Cmd Command to be sent XST_SUCCESS if initialization was successfulXST_FAILURE if failure
References XSdPs_Config::BaseAddress, XSdPs::Config, XSdPs::TransferMode, XSdPs_FrameCmd.
Referenced by XSdPs_CmdTransfer.
s32 XSdPs_SetStartAddr(XSdPs *InstancePtr, u32 StartAddr)
Sets the address of the first write block to be erased.
InstancePtr Pointer to the instance to be worked on. StartAddr Address of the first write block. XST_SUCCESS if Set start Address is successfulXST_FAILURE if failure - could be because failed to set EndAddr.
References XSdPs::CardType, XSdPs_CmdTransfer.
Referenced by XSdPs_Erase.
s32 XSdPs_SetEndAddr(XSdPs *InstancePtr, u32 EndAddr)
Sets the address of the last write block to be erased.
InstancePtr Pointer to the instance to be worked on. EndAddr Address of the last write block. XST_SUCCESS if Set End Address is successful.XST_FAILURE if failure - could be because failed to set EndAddr.
References XSdPs::CardType, XSdPs_CmdTransfer.
Referenced by XSdPs_Erase.
s32 XSdPs_SendErase(XSdPs *InstancePtr)
Sends Erase command to the device and wait for transfer complete.
InstancePtr Pointer to the instance to be worked on. XST_SUCCESS if erase operation is successfulXST_FAILURE if failure - could be because erase operation failed.
References XSdps_CheckTransferDone, XSdPs_CmdTransfer.
Referenced by XSdPs_Erase.