xsdps_options.c
s32 XSdPs_Change_ClkFreq(XSdPs *InstancePtr, u32 SelFreq)
API to change clock frequency to a given value.
InstancePtr Pointer to the XSdPs instance. SelFreq Clock frequency in Hz. None This API will change clock frequency to the value less than or equal to the given value using the permissible dividers.
References XSdPs_Config::BaseAddress, XSdPs::CardType, XSdPs::Config, XSdPs::HC_Version, XSdPs::IsReady, XSdPs::ITapDelay, XSdPs::Mode, XSdPs::OTapDelay, XSdPs_SetClock, XSdPs_SetTapDelay.
Referenced by XSdPs_CardInitialize, XSdPs_Change_BusSpeed, XSdPs_MmcCardEnum, XSdPs_SdCardEnum.
s32 XSdPs_SetBlkSize(XSdPs *InstancePtr, u16 BlkSize)
Updates Block size for read/write operations.
InstancePtr Pointer to the instance to be worked on. BlkSize Block size passed by the user. None
References XSdPs_Config::BaseAddress, XSdPs::BlkSize, XSdPs::Config, XSdPs::IsReady, XSdPs_CheckBusIdle, XSdPs_CmdTransfer.
Referenced by XSdPs_MmcCardInitialize, XSdPs_SdModeInit, XSdPs_SetupTransfer.
s32 XSdPs_Get_BusWidth(XSdPs *InstancePtr, u8 *ReadBuff)
Gets bus width support by card.
InstancePtr Pointer to the XSdPs instance. ReadBuff Buffer to store SCR register returned by card. XST_SUCCESS if successful.XST_FAILURE if fail. None.
References XSdPs::Config, XSdPs_Config::IsCacheCoherent, XSdPs::IsReady, XSdPs::RelCardAddr, XSdps_CheckTransferDone, XSdPs_CmdTransfer, XSdPs_SetupReadDma.
Referenced by XSdPs_SdModeInit.
s32 XSdPs_Change_BusWidth(XSdPs *InstancePtr)
Sets bus width to 4-bit in card and host.
InstancePtr Pointer to the XSdPs instance. XST_SUCCESS if successful.XST_FAILURE if fail.
References XSdPs_Config::BaseAddress, XSdPs_Config::BusWidth, XSdPs::BusWidth, XSdPs::CardType, XSdPs::Config, XSdPs::HC_Version, XSdPs::IsReady, XSdPs::Mode, XSdPs::RelCardAddr, XSdPs_CmdTransfer, XSdPs_Set_Mmc_ExtCsd.
Referenced by XSdPs_EmmcModeInit, XSdPs_MmcModeInit, XSdPs_SdModeInit.
s32 XSdPs_Get_BusSpeed(XSdPs *InstancePtr, u8 *ReadBuff)
Gets bus speed supported by card.
InstancePtr Pointer to the XSdPs instance. ReadBuff Buffer to store function group support data returned by card. XST_SUCCESS if successful.XST_FAILURE if fail. None.
References XSdPs::Config, XSdPs_Config::IsCacheCoherent, XSdPs::IsReady, XSdps_CheckTransferDone, XSdPs_CmdTransfer, XSdPs_SetupReadDma.
Referenced by XSdPs_SdModeInit.
s32 XSdPs_Get_Status(XSdPs *InstancePtr, u8 *SdStatReg)
Gets SD card status information.
InstancePtr Pointer to the XSdPs instance. SdStatReg Buffer to store status data returned by card. XST_SUCCESS if successful.XST_FAILURE if fail.
References XSdPs::Config, XSdPs_Config::IsCacheCoherent, XSdPs::IsReady, XSdPs::RelCardAddr, XSdps_CheckTransferDone, XSdPs_CmdTransfer, XSdPs_SetupReadDma.
s32 XSdPs_Change_BusSpeed(XSdPs *InstancePtr)
Sets high speed in card and host.
Changes clock in host accordingly. InstancePtr Pointer to the XSdPs instance. XST_SUCCESS if successful.XST_FAILURE if fail.
References XSdPs_Config::BaseAddress, XSdPs::BusSpeed, XSdPs::CardType, XSdPs::Config, XSdPs::IsReady, XSdPs::IsTuningDone, XSdPs::Mode, XSdPs_Change_ClkFreq, XSdPs_Change_MmcBusSpeed, XSdPs_Change_SdBusSpeed, XSdPs_Execute_Tuning.
Referenced by XSdPs_EmmcModeInit, XSdPs_MmcModeInit, XSdPs_SdModeInit.
s32 XSdPs_Get_Mmc_ExtCsd(XSdPs *InstancePtr, u8 *ReadBuff)
Gets EXT_CSD register of eMMC.
InstancePtr Pointer to the XSdPs instance. ReadBuff Buffer to store EXT_CSD XST_SUCCESS if successful.XST_FAILURE if fail.
References XSdPs::Config, XSdPs_Config::IsCacheCoherent, XSdPs::IsReady, XSdps_CheckTransferDone, XSdPs_CmdTransfer, XSdPs_SetupReadDma.
Referenced by XSdPs_CheckEmmcTiming, XSdPs_EmmcModeInit, XSdPs_MmcModeInit.
s32 XSdPs_Set_Mmc_ExtCsd(XSdPs *InstancePtr, u32 Arg)
Writes EXT_CSD register of eMMC.
InstancePtr Pointer to the XSdPs instance. Arg Argument to be sent along with the command. XST_SUCCESS if successful.XST_FAILURE if fail.
References XSdPs::IsReady, XSdps_CheckTransferDone, XSdPs_CmdTransfer.
Referenced by XSdPs_Change_BusWidth, XSdPs_EmmcModeInit, XSdPs_Sanitize.
s32 XSdPs_Pullup(XSdPs *InstancePtr)
Sends pullup command to card before using DAT line 3(using 4-bit bus).
InstancePtr Pointer to the XSdPs instance. XST_SUCCESS if successful.XST_FAILURE if fail.
References XSdPs::IsReady, XSdPs::RelCardAddr, XSdPs_CmdTransfer.
s32 XSdPs_Select_Card(XSdPs *InstancePtr)
Selects card and sets default block size.
InstancePtr Pointer to the XSdPs instance. XST_SUCCESS if successful.XST_FAILURE if fail.XSDPS_CT_ERROR if Command Transfer fail.
References XSdPs::IsReady, XSdPs::RelCardAddr, XSdPs_CmdTransfer.
Referenced by XSdPs_MmcCardEnum, XSdPs_SdCardEnum.
s32 XSdPs_StartReadTransfer(XSdPs *InstancePtr, u32 Arg, u32 BlkCnt, u8 *Buff)
Performs SD read in polled mode.
InstancePtr Pointer to the instance to be worked on. Arg Address passed by the user that is to be sent as argument along with the command. BlkCnt Block count passed by the user. Buff Pointer to the data buffer for a DMA transfer. XST_SUCCESS if Transfer initialization was successfulXST_FAILURE if failure - could be because another transfer is in progress or command or data inhibit is set
References XSdPs::IsBusy, XSdPs::IsReady, XSdPs_Read, XSdPs_SetupTransfer.
s32 XSdPs_StartWriteTransfer(XSdPs *InstancePtr, u32 Arg, u32 BlkCnt, u8 *Buff)
Starts SD write transfer.
InstancePtr Pointer to the instance to be worked on. Arg Address passed by the user that is to be sent as argument along with the command. BlkCnt Block count passed by the user. Buff Pointer to the data buffer for a DMA transfer. XST_SUCCESS if Transfer initialization was successfulXST_FAILURE if failure - could be because another transfer is in progress or command or data inhibit is set
References XSdPs::IsBusy, XSdPs::IsReady, XSdPs_SetupTransfer, XSdPs_Write.
s32 XSdPs_CheckReadTransfer(XSdPs *InstancePtr)
Checks if the transfer is completed successfully.
InstancePtr Pointer to the instance to be worked on. XST_SUCCESS if transfer was successfulXST_FAILURE if failureXST_DEVICE_BUSY - if the transfer is still in progress
References XSdPs::IsReady, XSdPs_CheckTransferComplete.
s32 XSdPs_CheckWriteTransfer(XSdPs *InstancePtr)
Checks for the write transfer completed.
InstancePtr Pointer to the instance to be worked on. XST_SUCCESS if transfer was successfulXST_FAILURE if failureXST_DEVICE_BUSY - if the transfer is still in progress
References XSdPs::IsReady, XSdPs_CheckTransferComplete.