xsdps_host.c
void XSdPs_SetTapDelay_SDR104(XSdPs *InstancePtr)
Sets the tap delay for SDR104 uhs mode.
InstancePtr Pointer to the instance to be worked on. None
References XSdPs_Config::BankNumber, XSdPs::Config, XSdPs::OTapDelay, XSdPs_Config::OTapDly_SDR_Clk200.
Referenced by XSdPs_Identify_UhsMode.
void XSdPs_SetTapDelay_SDR50(XSdPs *InstancePtr)
Sets the tap delay for SDR50 uhs mode.
InstancePtr Pointer to the instance to be worked on. None
References XSdPs::Config, XSdPs::OTapDelay, XSdPs_Config::OTapDly_SDR_Clk100.
Referenced by XSdPs_Identify_UhsMode.
void XSdPs_SetTapDelay_DDR50(XSdPs *InstancePtr)
Sets the tap delay for DDR50 uhs mode.
InstancePtr Pointer to the instance to be worked on. None
References XSdPs::Config, XSdPs::ITapDelay, XSdPs_Config::ITapDly_DDR_Clk50, XSdPs::OTapDelay, XSdPs_Config::OTapDly_DDR_Clk50, XSdPs_Config::SlotType.
Referenced by XSdPs_Identify_UhsMode.
void XSdPs_SetTapDelay_SDR25(XSdPs *InstancePtr)
Sets the tap delay for SDR25 uhs mode.
InstancePtr Pointer to the instance to be worked on. None
References XSdPs::Config, XSdPs::ITapDelay, XSdPs_Config::ITapDly_SDR_Clk50, XSdPs::OTapDelay, XSdPs_Config::OTapDly_SDR_Clk50, XSdPs_Config::SlotType.
Referenced by XSdPs_Identify_UhsMode.
s32 XSdPs_Switch_Voltage(XSdPs *InstancePtr)
Switches the SD card voltage from 3v3 to 1v8.
InstancePtr Pointer to the XSdPs instance.
References XSdPs_CardSetVoltage18, XSdPs_CheckBusHigh, XSdPs_SetupVoltageSwitch.
Referenced by XSdPs_CardOpCond.
s32 XSdPs_SetupTransfer(XSdPs *InstancePtr)
Initiates the transfer to or from SD card.
InstancePtr Pointer to the instance to be worked on. XST_SUCCESS if initialization was successfulXST_FAILURE if failure
References XSdPs_Config::BaseAddress, XSdPs_Config::CardDetect, XSdPs::Config, XSdPs::HC_Version, XSdPs::Host_Caps, XSDPS_BLK_SIZE_512_MASK, XSdPs_SetBlkSize.
Referenced by XSdPs_ReadPolled, XSdPs_StartReadTransfer, XSdPs_StartWriteTransfer, XSdPs_WritePolled.
s32 XSdPs_Reset(XSdPs *InstancePtr, u8 Value)
Resets the SD card.
InstancePtr Pointer to the instance to be worked on. Value Type of reset XST_SUCCESS if initialization was successfulXST_FAILURE if failure
References XSdPs_Config::BaseAddress, XSdPs::Config, XSdPs_CheckResetDone.
Referenced by XSdPs_CardIfCond, XSdPs_IdentifyCard, XSdPs_Idle, XSdPs_ResetConfig.
void XSdPs_SetExecTuning(XSdPs *InstancePtr)
Sets bit to start execution of tuning.
InstancePtr Pointer to the instance to be worked on. None
References XSdPs_Config::BaseAddress, XSdPs::Config.
Referenced by XSdPs_AutoTuning.
s32 XSdPs_SdModeInit(XSdPs *InstancePtr)
Initializes SD mode.
InstancePtr Pointer to the instance to be worked on. XST_SUCCESS if initialization is successfulXST_FAILURE if failure
References XSdPs_Config::BusWidth, XSdPs::BusWidth, XSdPs::Config, HIGH_SPEED_SUPPORT, XSdPs::ITapDelay, XSdPs_Config::ITapDly_SDR_Clk50, XSdPs::Mode, XSdPs::OTapDelay, XSdPs_Config::OTapDly_SDR_Clk50, SCR_SPEC_VER_3, XSdPs_Config::SlotType, XSdPs::Switch1v8, UHS_SDR50_SUPPORT, WIDTH_4_BIT_SUPPORT, XSDPS_BLK_SIZE_512_MASK, XSdPs_CardSetVoltage18, XSdPs_Change_BusSpeed, XSdPs_Change_BusWidth, XSdPs_Get_BusSpeed, XSdPs_Get_BusWidth, XSdPs_Identify_UhsMode, XSdPs_SetBlkSize.
Referenced by XSdPs_SdCardInitialize.
s32 XSdPs_MmcModeInit(XSdPs *InstancePtr)
Initializes MMC mode.
InstancePtr Pointer to the instance to be worked on. XST_SUCCESS if initialization is successfulXST_FAILURE if failure
References XSdPs::BusWidth, EXT_CSD_DEVICE_TYPE_BYTE, EXT_CSD_DEVICE_TYPE_HIGH_SPEED, EXT_CSD_SEC_COUNT_BYTE1, EXT_CSD_SEC_COUNT_BYTE2, EXT_CSD_SEC_COUNT_BYTE3, EXT_CSD_SEC_COUNT_BYTE4, XSdPs::Mode, XSdPs::SectorCount, XSdPs_Change_BusSpeed, XSdPs_Change_BusWidth, XSdPs_Get_Mmc_ExtCsd.
Referenced by XSdPs_MmcCardInitialize.
s32 XSdPs_EmmcModeInit(XSdPs *InstancePtr)
Initializes eMMC mode.
InstancePtr Pointer to the instance to be worked on. XST_SUCCESS if initialization is successfulXST_FAILURE if failure
References XSdPs_Config::BusWidth, XSdPs::BusWidth, XSdPs::Config, EXT_CSD_SEC_COUNT_BYTE1, EXT_CSD_SEC_COUNT_BYTE2, EXT_CSD_SEC_COUNT_BYTE3, EXT_CSD_SEC_COUNT_BYTE4, XSdPs::HC_Version, XSdPs::Mode, XSdPs::SectorCount, XSdPs_Change_BusSpeed, XSdPs_Change_BusWidth, XSdPs_CheckEmmcTiming, XSdPs_Get_Mmc_ExtCsd, XSdPs_IdentifyEmmcMode, XSdPs_Set_Mmc_ExtCsd.
Referenced by XSdPs_MmcCardInitialize.
void XSdPs_DisableBusPower(XSdPs *InstancePtr)
Disables the bus power.
InstancePtr Pointer to the instance to be worked on. None
References XSdPs_Config::BaseAddress, XSdPs::Config, XSdPs::HC_Version.
Referenced by XSdPs_Idle, XSdPs_ResetConfig.
void XSdPs_EnableBusPower(XSdPs *InstancePtr)
Enables the bus power.
InstancePtr Pointer to the instance to be worked on. None
References XSdPs_Config::BaseAddress, XSdPs::Config, XSdPs::HC_Version.
Referenced by XSdPs_ResetConfig.
s32 XSdPs_SdCardEnum(XSdPs *InstancePtr)
Enumerates the SD card.
InstancePtr Pointer to the instance to be worked on. None
References XSdPs::BusSpeed, XSdPs::HC_Version, SD_CLK_19_MHZ, SD_CLK_25_MHZ, XSdPs_CardIfCond, XSdPs_CardOpCond, XSdPs_CardReset, XSdPs_Change_ClkFreq, XSdPs_CheckCardDetect, XSdPs_GetCardId, XSdPs_GetCsd, XSdPs_Select_Card.
Referenced by XSdPs_SdCardInitialize.
s32 XSdPs_MmcCardEnum(XSdPs *InstancePtr)
Enumerates the MMC card.
InstancePtr Pointer to the instance to be worked on. None
References XSdPs::BusSpeed, SD_CLK_26_MHZ, XSdPs_CardOpCond, XSdPs_CardReset, XSdPs_Change_ClkFreq, XSdPs_CheckCardDetect, XSdPs_GetCardId, XSdPs_GetCsd, XSdPs_Select_Card.
Referenced by XSdPs_MmcCardInitialize.
s32 XSdPs_Execute_Tuning(XSdPs *InstancePtr)
Performs SD tuning.
InstancePtr Pointer to the instance to be worked on. None
References XSdPs_AutoTuning, XSdPs_DllReset.
Referenced by XSdPs_Change_BusSpeed.
s32 XSdPs_EnableClock(XSdPs *InstancePtr, u16 ClockReg)
Enables the clock.
InstancePtr Pointer to the instance to be worked on. ClockReg Clock value to be set. XST_SUCCESS if successXST_FAILURE if failure
References XSdPs_Config::BaseAddress, XSdPs::Config.
Referenced by XSdPs_CardSetVoltage18, XSdPs_DllReset, XSdPs_SetClock.
s32 XSdPs_CalcBusSpeed(XSdPs *InstancePtr, u32 *Arg)
Calculates the bus speed.
InstancePtr Pointer to the instance to be worked on. Arg Argument to be sent along with the command. This could be address or any other information XST_SUCCESS if successXST_FAILURE if failure
References XSdPs::BusSpeed, XSdPs::CardType, XSdPs::IsTuningDone, XSdPs::Mode.
Referenced by XSdPs_Change_MmcBusSpeed, XSdPs_Change_SdBusSpeed.
void XSdPs_SetupReadDma(XSdPs *InstancePtr, u16 BlkCnt, u16 BlkSize, u8 *Buff)
This function is used to do the DMA transfer to or from SD card.
InstancePtr Pointer to the instance to be worked on. BlkCnt Block count passed by the user. BlkSize Block size passed by the user. Buff Pointer to the data buffer for a DMA transfer. XST_SUCCESS if initialization was successfulXST_FAILURE if failure - could be because another transfer is in progress or command or data inhibit is set
References ADDRESS_BEYOND_32BIT, XSdPs_Config::BaseAddress, XSdPs::Config, XSdPs::Dma64BitAddr, XSdPs_Config::IsCacheCoherent, XSdPs::TransferMode, XSdPs_SetupADMA2DescTbl, XSdPs_SetupADMA2DescTbl64Bit.
Referenced by XSdPs_Change_SdBusSpeed, XSdPs_Get_BusSpeed, XSdPs_Get_BusWidth, XSdPs_Get_Mmc_ExtCsd, XSdPs_Get_Status, XSdPs_Read.
void XSdPs_SetupWriteDma(XSdPs *InstancePtr, u16 BlkCnt, u16 BlkSize, const u8 *Buff)
This function is used to do the DMA transfer to or from SD card.
InstancePtr Pointer to the instance to be worked on. BlkCnt Block count passed by the user. BlkSize Block size passed by the user. Buff Pointer to the data buffer for a DMA transfer. XST_SUCCESS if initialization was successfulXST_FAILURE if failure - could be because another transfer is in progress or command or data inhibit is set
References ADDRESS_BEYOND_32BIT, XSdPs_Config::BaseAddress, XSdPs::Config, XSdPs::Dma64BitAddr, XSdPs_Config::IsCacheCoherent, XSdPs::TransferMode, XSdPs_SetupADMA2DescTbl, XSdPs_SetupADMA2DescTbl64Bit.
Referenced by XSdPs_Write.
void XSdPs_Setup32ADMA2DescTbl(XSdPs *InstancePtr, u32 BlkCnt, const u8 *Buff)
API to setup ADMA2 descriptor table for 32-bit DMA.
InstancePtr Pointer to the XSdPs instance. BlkCnt Block count. Buff Pointer to data buffer. None
References XSdPs_Adma2Descriptor32::Address, XSdPs::Adma2_DescrTbl32, XSdPs_Adma2Descriptor32::Attribute, XSdPs_Config::BaseAddress, XSdPs::Config, XSdPs_Config::IsCacheCoherent, XSdPs_Adma2Descriptor32::Length.
Referenced by XSdPs_SetupADMA2DescTbl.
void XSdPs_Setup64ADMA2DescTbl(XSdPs *InstancePtr, u32 BlkCnt, const u8 *Buff)
API to setup ADMA2 descriptor table for 64-bit DMA.
InstancePtr Pointer to the XSdPs instance. BlkCnt Block count. Buff Pointer to data buffer. None
References XSdPs_Adma2Descriptor64::Address, XSdPs::Adma2_DescrTbl64, XSdPs_Adma2Descriptor64::Attribute, XSdPs_Config::BaseAddress, XSdPs::Config, XSdPs_Config::IsCacheCoherent, XSdPs_Adma2Descriptor64::Length.
Referenced by XSdPs_SetupADMA2DescTbl.
u32 XSdPs_CalcClock(XSdPs *InstancePtr, u32 SelFreq)
Calculates the clock divisor value.
InstancePtr Pointer to the instance to be worked on. SelFreq Selected frequency Clock divisor value
References XSdPs::Config, XSdPs::HC_Version, XSdPs_Config::InputClockHz.
Referenced by XSdPs_SetClock.
void XSdPs_DllRstCtrl(XSdPs *InstancePtr, u8 EnRst)
API to Set or Reset the DLL.
InstancePtr Pointer to the XSdPs instance. EnRst Flag indicating whether to Assert or De-assert Reset. None This API is specific to ZynqMP platform.
References XSdPs_Config::BaseAddress, XSdPs::Config, XSdPs::SlcrBaseAddr, XSDPS_ZYNQMP_SD0_BASE.
Referenced by XSdPs_DllReset, XSdPs_SetTapDelay.
void XSdPs_ConfigTapDelay(XSdPs *InstancePtr)
Function to configure the Tap Delays.
InstancePtr Pointer to the XSdPs instance. None
References XSdPs_Config::BaseAddress, XSdPs::Config, XSdPs::ITapDelay, XSdPs::OTapDelay, XSdPs::SlcrBaseAddr, XSDPS_ZYNQMP_SD0_BASE.
Referenced by XSdPs_SetTapDelay.
s32 XSdPs_SetVoltage18(XSdPs *InstancePtr)
Sets voltage to 1.8 V.
InstancePtr Pointer to the instance to be worked on. XST_SUCCESS if successfulXST_FAILURE if failure
References XSdPs_Config::BaseAddress, XSdPs::Config, XSdPs_CheckVoltage18.
Referenced by XSdPs_CardSetVoltage18.
void XSdPs_ConfigPower(XSdPs *InstancePtr)
Configures the Power Level.
InstancePtr Pointer to the instance to be worked on. None
References XSdPs_Config::BaseAddress, XSdPs::Config, XSdPs::Host_Caps.
Referenced by XSdPs_HostConfig.
void XSdPs_ConfigDma(XSdPs *InstancePtr)
Configures the DMA.
InstancePtr Pointer to the instance to be worked on. None
References XSdPs_Config::BaseAddress, XSdPs::Config, XSdPs::HC_Version.
Referenced by XSdPs_HostConfig.
void XSdPs_ConfigInterrupt(XSdPs *InstancePtr)
Configures the Interrupts.
InstancePtr Pointer to the instance to be worked on. None
References XSdPs_Config::BaseAddress, XSdPs::Config.
Referenced by XSdPs_HostConfig.
s32 XSdPs_CmdTransfer(XSdPs *InstancePtr, u32 Cmd, u32 Arg, u32 BlkCnt)
Generates SD command.
InstancePtr Pointer to the instance to be worked on. Cmd Command to be sent. Arg Argument to be sent along with the command. This could be address or any other information BlkCnt Block count passed by the user. XST_SUCCESS if initialization was successfulXST_FAILURE if failure - could be because another transfer is in progress or command or data inhibit is set
References XSdPs_Config::BaseAddress, XSdPs::Config, XSDPS_CT_ERROR, XSdPs_SendCmd, XSdPs_SetupCmd.
Referenced by XSdPs_AutoTuning, XSdPs_CardIfCond, XSdPs_CardOpCond, XSdPs_CardReset, XSdPs_Change_BusWidth, XSdPs_Change_MmcBusSpeed, XSdPs_Change_SdBusSpeed, XSdPs_Get_BusSpeed, XSdPs_Get_BusWidth, XSdPs_Get_Mmc_ExtCsd, XSdPs_Get_Status, XSdPs_GetCardId, XSdPs_GetCsd, XSdPs_IdentifyCard, XSdPs_Pullup, XSdPs_Read, XSdPs_Select_Card, XSdPs_SendErase, XSdPs_Set_Mmc_ExtCsd, XSdPs_SetBlkSize, XSdPs_SetEndAddr, XSdPs_SetStartAddr, XSdPs_SetupVoltageSwitch, XSdPs_Write.
s32 XSdps_CheckTransferDone(XSdPs *InstancePtr)
Checks if the transfer is completed successfully.
InstancePtr Pointer to the instance to be worked on. None
References XSdPs_Config::BaseAddress, XSdPs::Config.
Referenced by XSdPs_Change_MmcBusSpeed, XSdPs_Change_SdBusSpeed, XSdPs_Get_BusSpeed, XSdPs_Get_BusWidth, XSdPs_Get_Mmc_ExtCsd, XSdPs_Get_Status, XSdPs_ReadPolled, XSdPs_SendErase, XSdPs_Set_Mmc_ExtCsd, XSdPs_WritePolled.
s32 XSdPs_CheckBusIdle(XSdPs *InstancePtr, u32 Value)
Checks if the CMD/DATA bus is idle or not.
InstancePtr Pointer to the instance to be worked on. Value Value to be selected Cmd bus or Dat bus. None
References XSdPs_Config::BaseAddress, XSdPs::Config.
Referenced by XSdPs_Idle, XSdPs_SetBlkSize, XSdPs_SetupCmd.
u32 XSdPs_FrameCmd(XSdPs *InstancePtr, u32 Cmd)
This function frames the Command register for a particular command.
InstancePtr Pointer to the instance to be worked on. Cmd Command to be sent. Command register value complete with response type and data, CRC and index related flags. This generates only the command register value i.e. the upper 16 bits of the transfer mode and command register. This value is already shifted to be upper 16 bits and can be directly OR'ed with transfer mode register value.
References XSdPs::CardType.
Referenced by XSdPs_SendCmd.