dfxasm
XDFX_ASM_CTRL_OFFSET
Control register Offset and status register is also mapped to same address as Control register.
Referenced by XDfxasm_GetState, XDfxasm_SetState.
XDFX_ASM_CTRL_SHUTDOWN_MASK
Shutdown manager state mask.
Referenced by XDfxasm_GetState.
XDfxasm_State
XDfxasm_Config XDfxasm_ConfigTable[][]
s32 XDfxasm_CfgInitialize(XDfxasm *InstancePtr, XDfxasm_Config *ConfigPtr, UINTPTR EffectiveAddress)
This function initializes a XDfxasm instance/driver.
InstancePtr is a pointer to the XDfxasm instance. ConfigPtr points to the XDfxasm device configuration structure. EffectiveAddress is the device base address in the virtual memory address space. If the address translation is not used then the physical address is passed. XST_SUCCESS if initialization was successful. None.
References XDfxasm::Config, XDfxasm::IsReady.
Referenced by XDfxasm_Example.
void XDfxasm_SetState(XDfxasm *InstancePtr, XDfxasm_State ShutdownValue)
This function is used to set shutdown manager in shutdown or pass through mode.
InstancePtr is a pointer to the XDfxasm instance. ShutdownValue is to set shutdown manager in shutdown or pass through mode. Value can be either 0 or 1. Values are XDFX_ASM_PASSTHROUGH_MODE(0) if in passthrough mode XDFX_ASM_SHUTDOWN_MODE(1) if in shutdown mode None When Shutdown manager is in shutdown mode it blocks the axi traffic that's going to the Reconfigurable partition from static logic while Partial Reconfiguration occurs.
References XDfxasm::Config, XDfxasm::IsReady, XDFX_ASM_CTRL_OFFSET, XDfxasm_WriteReg.
Referenced by XDfxasm_TestState.
u32 XDfxasm_GetState(XDfxasm *InstancePtr)
This function is used to read the state of the shutdown manager.
InstancePtr is a pointer to the XDfxasm instance. Returns shutdown manager state and its bit significance is as follows. -BIT0 - 0 Entry to Pass Through mode has been requested 1 Entry to Shutdown mode has been requested -BIT1 - 0 The read or the write channel (or both) are in the Pass Through mode1 Both the read and write channels are in the Shutdown Mode -BIT2 - 0 The write channel is in the Pass Through mode1 The write channel is in the Shutdown Mode -BIT3 - 0 The read channel is in the Pass Through mode1 The read channel is in the Shutdown Mode None.
References XDfxasm::Config, XDfxasm::IsReady, XDFX_ASM_CTRL_OFFSET, XDFX_ASM_CTRL_SHUTDOWN_MASK, XDfxasm_ReadReg.
Referenced by XDfxasm_TestState.
XDfxasm_Config * XDfxasm_LookupConfig(UINTPTR BaseAddress)
This function looks for the device configuration based on the unique device ID/BaseAddress.
The table XDfxasm_ConfigTable[] contains the configuration information for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration table entry corresponding to the given device ID/BaseAddress, or NULL if no match is found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
Referenced by XDfxasm_Example.
XDFX_ASM_H_
XDFXASM_HW_H_
XDfxasm_ReadReg
This macro reads a value from the given register.
Address is the address of the register to read from. The 32-bit value read from register. None.
Referenced by XDfxasm_GetState.
XDfxasm_WriteReg
This macro writes a value to the given register.
Address is the address of the register to write to. Data is the 32-bit value to write to the register. None. None.
Referenced by XDfxasm_SetState.