xilmailbox
u32 XMailbox_Initialize(XMailbox *InstancePtr, UINTPTR BaseAddress)
Initialize the XMailbox Instance.
Functions for xilmailbox.c. InstancePtr is a pointer to the instance to be worked on DeviceId is the IPI Instance to be worked on XST_SUCCESS if initialization was successful XST_FAILURE in case of failure
References XIpiPs_Init, XIpiPs_RecvDataById, XIpiPs_SendById, XIpiPs_SendDataById, XMboxTag::XMbox_IPI_RecvById, XMboxTag::XMbox_IPI_SendById, XMboxTag::XMbox_IPI_SendDataById.
u32 XMailbox_Send(XMailbox *InstancePtr, u32 RemoteId, u8 Is_Blocking)
This function triggers an IPI to a destination CPU.
InstancePtr Pointer to the XMailbox instance RemoteId is the Mask of the CPU to which IPI is to be triggered Is_Blocking if set trigger the notification in blocking mode XST_SUCCESS if successfulXST_FAILURE if unsuccessful
References XMboxTag::Agent, XMailbox_Agent::RemoteId, XMboxTag::XMbox_IPI_SendById.
u32 XMailbox_SendData(XMailbox *InstancePtr, u32 RemoteId, void *BufferPtr, u32 MsgLen, u8 BufferType, u8 Is_Blocking)
This function sends an IPI message to a destination CPU.
InstancePtr Pointer to the XMailbox instance RemoteId is the Mask of the CPU to which IPI is to be triggered BufferPtr is the pointer to Buffer which contains the message to be sent MsgLen is the number of messages (each message is 4bytes) BufferType is the type of buffer (XILMBOX_MSG_TYPE_REQ (OR) XILMBOX_MSG_TYPE_RESP) Is_Blocking if set trigger the notification in blocking mode XST_SUCCESS if successfulXST_FAILURE if unsuccessful
References XMboxTag::Agent, XMailbox_Agent::RemoteId, XILMBOX_MSG_TYPE_REQ, XILMBOX_MSG_TYPE_RESP, XMAILBOX_MAX_MSG_LEN, XMboxTag::XMbox_IPI_SendDataById.
u32 XMailbox_Recv(XMailbox *InstancePtr, u32 SourceId, void *BufferPtr, u32 MsgLen, u8 BufferType)
This function reads an IPI message.
InstancePtr Pointer to the XMailbox instance SourceId is the Mask for the CPU which has sent the message BufferPtr is the pointer to Buffer to which the read message needs to be stored MsgLen is the number of messages (each message is 4bytes) BufferType is the type of buffer (XILMBOX_MSG_TYPE_REQ or XILMBOX_MSG_TYPE_RESP) XST_SUCCESS if successfulXST_FAILURE if unsuccessful
References XMboxTag::Agent, XMailbox_Agent::SourceId, XILMBOX_MSG_TYPE_REQ, XILMBOX_MSG_TYPE_RESP, XMAILBOX_MAX_MSG_LEN, XMboxTag::XMbox_IPI_RecvById.
s32 XMailbox_SetCallBack(XMailbox *InstancePtr, XMailbox_Handler HandlerType, void *CallBackFuncPtr, void *CallBackRefPtr)
This routine installs an asynchronous callback function for the given HandlerType.
HandlerType Callback Function Type ----------------------- -------------------------------------------------- XMAILBOX_RECV_HANDLER Recv handler XMAILBOX_ERROR_HANDLER Error handler InstancePtr is a pointer to the XMailbox instance. HandlerType specifies which callback is to be attached. CallBackFuncPtr is the address of the callback function. CallBackRefPtr is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS when handler is installed.XST_FAILURE when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XMboxTag::ErrorHandler, XMboxTag::ErrorRefPtr, XMboxTag::RecvHandler, XMboxTag::RecvRefPtr, XMAILBOX_ERROR_HANDLER, XMAILBOX_RECV_HANDLER.
u32 XMailbox_SetSharedMem(XMailbox *InstancePtr, u64 Address, u32 Size)
This function sets the shared memory location for IPI usage.
InstancePtr is a pointer to the XMailbox instance. Address Address of shared memory location Size Size of the memory location XST_SUCCESS - if memory is set for IPI usageXST_FAILURE - On failure
References XMboxTag::SharedMem, XMAILBOX_SHARED_MEM_INITIALIZED.
u32 XMailbox_GetSharedMem(XMailbox *InstancePtr, u64 **Address)
This function returns the shared memory location for IPI usage.
InstancePtr is a pointer to the XMailbox instance. Address Pointer to the address of the variable for which memory needs to be assigned Size Size of the memory allocated for IPI usage
References XMboxTag::SharedMem, XMAILBOX_SHARED_MEM_INITIALIZED.
int XMailbox_ReleaseSharedMem(XMailbox *InstancePtr)
This function releases the shared memory.
XST_SUCCESS - if memory is releasedXST_FAILURE - if memory is not released
References XMboxTag::SharedMem, XMAILBOX_SHARED_MEM_UNINITIALIZED.
XMailbox_IpiSharedMemState
Shared memory uninitialized.
XMailbox_Handler
For Recv Handler.
typedef void(* XMailbox_RecvHandler)(void *CallBackRefPtr))(void *CallBackRefPtr)
Receive handler.
typedef void(* XMailbox_ErrorHandler)(void *CallBackRefPtr, u32 ErrorMask))(void *CallBackRefPtr, u32 ErrorMask)
Error handler.
typedef struct XMboxTag XMailbox
Data structure used to refer XilMailbox.
: The following function pointers XMbox_IPI_Send, XMbox_IPI_SendData, XMbox_IPI_Recv will be deprecated in 2026.2 and will be made obsolete in 2027.1 release.XilMailbox structure
XIpiPsu XMailbox_Agent::IpiInst
Ipi instance.
Referenced by XIpiPs_Init, XIpiPs_IntrHandler, XIpiPs_PollforDone, XIpiPs_PollforDoneById, XIpiPs_RecvData, XIpiPs_RecvDataById, XIpiPs_RegisterIrq, XIpiPs_Send, XIpiPs_SendById, XIpiPs_SendData, XIpiPs_SendDataById.
XScuGic XMailbox_Agent::GicInst
Interrupt instance.
Referenced by XIpiPs_Init.
u32 XMailbox_Agent::SourceId
Source id.
Referenced by XIpiPs_RecvData, XMailbox_Recv.
u32 XMailbox_Agent::RemoteId
Remote id.
Referenced by XIpiPs_PollforDone, XIpiPs_Send, XIpiPs_SendData, XMailbox_Send, XMailbox_SendData.
u64 XMailbox_IpiSharedMem::Address
Address of the shared memory location.
u32 XMailbox_IpiSharedMem::Size
Size of the shared memory location.
XMailbox_IpiSharedMemState XMailbox_IpiSharedMem::SharedMemState
State of shared memory.
u32(* XMboxTag::XMbox_IPI_Send)(struct XMboxTag *InstancePtr, u8 Is_Blocking))(struct XMboxTag *InstancePtr, u8 Is_Blocking)
Triggers an IPI to a destination CPU.
u32(* XMboxTag::XMbox_IPI_SendData)(struct XMboxTag *InstancePtr, void *BufferPtr, u32 MsgLen, u8 BufferType, u8 Is_Blocking))(struct XMboxTag *InstancePtr, void *BufferPtr, u32 MsgLen, u8 BufferType, u8 Is_Blocking)
Sends an IPI message to a destination CPU.
u32(* XMboxTag::XMbox_IPI_Recv)(struct XMboxTag *InstancePtr, void *BufferPtr, u32 MsgLen, u8 BufferType))(struct XMboxTag *InstancePtr, void *BufferPtr, u32 MsgLen, u8 BufferType)
Reads an IPI message.
u32(* XMboxTag::XMbox_IPI_SendById)(struct XMboxTag *InstancePtr, u32 RemoteId, u8 Is_Blocking))(struct XMboxTag *InstancePtr, u32 RemoteId, u8 Is_Blocking)
Triggers an IPI to a destination CPU.
Referenced by XMailbox_Initialize, XMailbox_Send.
u32(* XMboxTag::XMbox_IPI_SendDataById)(struct XMboxTag *InstancePtr, void *BufferPtr, u32 MsgLen, u8 BufferType, u32 RemoteId, u8 Is_Blocking))(struct XMboxTag *InstancePtr, void *BufferPtr, u32 MsgLen, u8 BufferType, u32 RemoteId, u8 Is_Blocking)
Sends an IPI message to a destination CPU.
Referenced by XMailbox_Initialize, XMailbox_SendData.
u32(* XMboxTag::XMbox_IPI_RecvById)(struct XMboxTag *InstancePtr, void *BufferPtr, u32 MsgLen, u32 SourceId, u8 BufferType))(struct XMboxTag *InstancePtr, void *BufferPtr, u32 MsgLen, u32 SourceId, u8 BufferType)
Reads an IPI message.
Referenced by XMailbox_Initialize, XMailbox_Recv.
XMailbox_RecvHandler XMboxTag::RecvHandler
Receive handler.
Referenced by XIpiPs_IntrHandler, XMailbox_SetCallBack.
XMailbox_ErrorHandler XMboxTag::ErrorHandler
Callback for rx IPI event.
Referenced by XIpiPs_ErrorIntrHandler, XMailbox_SetCallBack.
void* XMboxTag::ErrorRefPtr
To be passed to the error interrupt callback.
Referenced by XIpiPs_ErrorIntrHandler, XMailbox_SetCallBack.
void* XMboxTag::RecvRefPtr
To be passed to the receive interrupt callback.
Referenced by XIpiPs_IntrHandler, XMailbox_SetCallBack.
XMailbox_Agent XMboxTag::Agent
Agent to store IPI channel information.
Referenced by XIpiPs_Init, XIpiPs_IntrHandler, XIpiPs_PollforDone, XIpiPs_PollforDoneById, XIpiPs_RecvData, XIpiPs_RecvDataById, XIpiPs_RegisterIrq, XIpiPs_Send, XIpiPs_SendById, XIpiPs_SendData, XIpiPs_SendDataById, XMailbox_Recv, XMailbox_Send, XMailbox_SendData.
XMailbox_IpiSharedMem XMboxTag::SharedMem
shared memory segment
Referenced by XMailbox_GetSharedMem, XMailbox_ReleaseSharedMem, XMailbox_SetSharedMem.
u32 XIpiPs_Init(XMailbox *InstancePtr, UINTPTR BaseAddress)
Initialize the ZynqMP Mailbox Instance.
InstancePtr is a pointer to the instance to be worked on DeviceId is the IPI Instance to be worked on XST_SUCCESS if initialization was successful XST_FAILURE in case of failure
References XMboxTag::Agent, XMailbox_Agent::GicInst, XMailbox_Agent::IpiInst, XIpiPs_RegisterIrq.
Referenced by XMailbox_Initialize.
u32 XIpiPs_Send(XMailbox *InstancePtr, u8 Is_Blocking)
This function triggers an IPI to a destination CPU.
InstancePtr Pointer to the XMailbox instance. Is_Blocking if set trigger the notification in blocking mode XST_SUCCESS in case of success XST_FAILURE in case of failure This API will be deprecated in 2026.2 and will be made obsolete in 2027.1 release. The functionality of this API can be reproduced with XIpiPs_SendById.
References XMboxTag::Agent, XMailbox_Agent::IpiInst, XMailbox_Agent::RemoteId, XIpiPs_PollforDone.
u32 XIpiPs_SendById(XMailbox *InstancePtr, u32 RemoteId, u8 Is_Blocking)
This function triggers an IPI to a destination CPU.
InstancePtr Pointer to the XMailbox instance. RemoteId Mask of the CPU to which IPI is to be triggered Is_Blocking if set trigger the notification in blocking mode XST_SUCCESS in case of success XST_FAILURE in case of failure
References XMboxTag::Agent, XMailbox_Agent::IpiInst, XIpiPs_PollforDoneById.
Referenced by XMailbox_Initialize.
u32 XIpiPs_SendData(XMailbox *InstancePtr, void *MsgBufferPtr, u32 MsgLen, u8 BufferType, u8 Is_Blocking)
This function sends an IPI message to a destination CPU.
InstancePtr Pointer to the XMailbox instance MsgBufferPtr is the pointer to Buffer which contains the message to be sent MsgLen is the number of messages (each message is 4bytes) BufferType is the type of buffer Is_Blocking if set trigger the notification in blocking mode XST_SUCCESS in case of success XST_FAILURE in case of failure This API will be deprecated in 2026.2 and will be made obsolete in 2027.1 release. The functionality of this API can be reproduced with XIpiPs_SendDataById.
References XMboxTag::Agent, XMailbox_Agent::IpiInst, XMailbox_Agent::RemoteId, XIpiPs_PollforDone.
u32 XIpiPs_SendDataById(XMailbox *InstancePtr, void *MsgBufferPtr, u32 MsgLen, u8 BufferType, u32 RemoteId, u8 Is_Blocking)
This function sends an IPI message to a destination CPU.
InstancePtr Pointer to the XMailbox instance MsgBufferPtr is the pointer to Buffer which contains the message to be sent MsgLen is the number of messages (each message is 4bytes) BufferType is the type of buffer RemoteId Mask of the CPU to which IPI is to be triggered Is_Blocking if set trigger the notification in blocking mode XST_SUCCESS in case of success XST_FAILURE in case of failure
References XMboxTag::Agent, XMailbox_Agent::IpiInst, XIpiPs_PollforDoneById.
Referenced by XMailbox_Initialize.
u32 XIpiPs_RecvData(XMailbox *InstancePtr, void *MsgBufferPtr, u32 MsgLen, u8 BufferType)
This function reads an IPI message.
InstancePtr Pointer to the XMailbox instance MsgBufferPtr is the pointer to Buffer to which the read message needs to be stored MsgLen is the number of messages (each message is 4bytes) BufferType is the type of buffer XST_SUCCESS if successfulXST_FAILURE if unsuccessful This API will be deprecated in 2026.2 and will be made obsolete in 2027.1 release. The functionality of this API can be reproduced with XIpiPs_RecvDataById.
References XMboxTag::Agent, XMailbox_Agent::IpiInst, XMailbox_Agent::SourceId.
u32 XIpiPs_RecvDataById(XMailbox *InstancePtr, void *MsgBufferPtr, u32 MsgLen, u32 SourceId, u8 BufferType)
This function reads an IPI message.
InstancePtr Pointer to the XMailbox instance MsgBufferPtr is the pointer to Buffer to which the read message needs to be stored MsgLen is the number of messages (each message is 4bytes) SourceId Device Mask for the CPU which has sent the message BufferType is the type of buffer XST_SUCCESS if successfulXST_FAILURE if unsuccessful
References XMboxTag::Agent, XMailbox_Agent::IpiInst.
Referenced by XMailbox_Initialize.
void XIpiPs_IntrHandler(void *XMailboxPtr)
This function implements the interrupt handler.
XMailboxPtr Pointer to the XMailbox instance None
References XMboxTag::Agent, XMailbox_Agent::IpiInst, XMboxTag::RecvHandler, XMboxTag::RecvRefPtr.
Referenced by XIpiPs_RegisterIrq.
void XIpiPs_ErrorIntrHandler(void *XMailboxPtr)
This function implements the interrupt handler for errors.
XMailboxPtr Pointer to the XMailbox instance None
References XMboxTag::ErrorHandler, XMboxTag::ErrorRefPtr, IPI_BASEADDRESS.
Referenced by XIpiPs_RegisterIrq.
u32 XIpiPs_PollforDone(XMailbox *InstancePtr)
Poll for an acknowledgement using Observation Register.
InstancePtr Pointer to the XMailbox instance XST_SUCCESS in case of success XST_FAILURE in case of failure This API will be deprecated in 2026.2 and will be made obsolete in 2027.1 release. The functionality of this API can be reproduced with XIpiPs_PollforDoneById.
References XMboxTag::Agent, XMailbox_Agent::IpiInst, XMailbox_Agent::RemoteId, XIPI_DONE_TIMEOUT_VAL, XIPI_IPI_DONE_BIT_SLEEP_IN_US.
Referenced by XIpiPs_Send, XIpiPs_SendData.
u32 XIpiPs_PollforDoneById(XMailbox *InstancePtr, u32 RemoteId)
Poll for an acknowledgement using Observation Register.
InstancePtr Pointer to the XMailbox instance RemoteId Mask of the destination CPU from which ACK is expected XST_SUCCESS in case of success XST_FAILURE in case of failure
References XMboxTag::Agent, XMailbox_Agent::IpiInst, XIPI_DONE_TIMEOUT_VAL, XIPI_IPI_DONE_BIT_SLEEP_IN_US.
Referenced by XIpiPs_SendById, XIpiPs_SendDataById.
XStatus XIpiPs_RegisterIrq(XMailbox *InstancePtr, u32 IpiIntrId)
This function registers an irq.
IntcInstancePtr Pointer to the scugic instance InstancePtr Pointer to the XMailbox instance IpiIntrId is the interrupt id of the IPI XST_SUCCESS if successfulXST_FAILURE if unsuccessful
References XMboxTag::Agent, XMailbox_Agent::IpiInst, XIpiPs_ErrorIntrHandler, XIpiPs_IntrHandler, XMAILBOX_INTR_ID.
Referenced by XIpiPs_Init.
static u32 XMailbox_GetLibVersion(void)
This function returns the version number of xilmailbox library.
32-bit version number
BIT
Bit position.
XIPI_DONE_TIMEOUT_VAL
Timeout for IPI.
Referenced by XIpiPs_PollforDone, XIpiPs_PollforDoneById.
XIPI_IPI_DONE_BIT_SLEEP_IN_US
Sleep for 1Us.
Referenced by XIpiPs_PollforDone, XIpiPs_PollforDoneById.
XMAILBOX_IPI0
IPI0 channel.
XMAILBOX_IPI1
IPI1 channel.
XMAILBOX_IPI2
IPI2 channel.
XMAILBOX_IPI3
IPI3 channel.
XMAILBOX_IPI4
IPI4 channel.
XMAILBOX_IPI5
IPI5 channel.
XMAILBOX_IPI6
IPI6 channel.
XMAILBOX_IPI7
IPI7 channel.
XMAILBOX_IPI8
IPI8 channel.
XMAILBOX_IPI9
IPI9 channel.
XMAILBOX_IPI10
IPI10 channel.
XMAILBOX_MAX_CHANNELS
Maximum channel.
XMAILBOX_INTR_ID
Interrupt id.
Referenced by XIpiPs_RegisterIrq.
IPI_BASEADDRESS
Base Address.
Referenced by XIpiPs_ErrorIntrHandler.
IPI_ADDRDECODE_ERROR
Address decode error.
XILMBOX_MSG_TYPE_REQ
Message type buffer.
Referenced by XMailbox_Recv, XMailbox_SendData.
XILMBOX_MSG_TYPE_RESP
Response type buffer.
Referenced by XMailbox_Recv, XMailbox_SendData.
XMAILBOX_MAX_MSG_LEN
Maximum number of Messages (each 4-bytes long)
Referenced by XMailbox_Recv, XMailbox_SendData.
XMAILBOX_PAYLOAD_LEN_1U
Payload lengths.
Payload length of size 1byte
XMAILBOX_PAYLOAD_LEN_2U
Payload length of size 2byte.
XMAILBOX_PAYLOAD_LEN_3U
Payload length of size 3byte.
XMAILBOX_PAYLOAD_LEN_4U
Payload length of size 4byte.
XMAILBOX_PAYLOAD_LEN_5U
Payload length of size 5byte.
XMAILBOX_PAYLOAD_LEN_6U
Payload length of size 6byte.
XMAILBOX_PAYLOAD_LEN_7U
Payload length of size 7byte.
XMAILBOX_MAJOR_VERSION
XMAILBOX_MINOR_VERSION