xilmailbox_ipips_intr.c
u32 XIpiPs_PollforDone(XMailbox *InstancePtr)
Poll for an acknowledgement using Observation Register.
InstancePtr Pointer to the XMailbox instance XST_SUCCESS in case of success XST_FAILURE in case of failure This API will be deprecated in 2026.2 and will be made obsolete in 2027.1 release. The functionality of this API can be reproduced with XIpiPs_PollforDoneById.
References XMboxTag::Agent, XMailbox_Agent::IpiInst, XMailbox_Agent::RemoteId, XIPI_DONE_TIMEOUT_VAL, XIPI_IPI_DONE_BIT_SLEEP_IN_US.
Referenced by XIpiPs_Send, XIpiPs_SendData.
u32 XIpiPs_PollforDoneById(XMailbox *InstancePtr, u32 RemoteId)
Poll for an acknowledgement using Observation Register.
InstancePtr Pointer to the XMailbox instance RemoteId Mask of the destination CPU from which ACK is expected XST_SUCCESS in case of success XST_FAILURE in case of failure
References XMboxTag::Agent, XMailbox_Agent::IpiInst, XIPI_DONE_TIMEOUT_VAL, XIPI_IPI_DONE_BIT_SLEEP_IN_US.
Referenced by XIpiPs_SendById, XIpiPs_SendDataById.
XStatus XIpiPs_RegisterIrq(XMailbox *InstancePtr, u32 IpiIntrId)
This function registers an irq.
IntcInstancePtr Pointer to the scugic instance InstancePtr Pointer to the XMailbox instance IpiIntrId is the interrupt id of the IPI XST_SUCCESS if successfulXST_FAILURE if unsuccessful
References XMboxTag::Agent, XMailbox_Agent::IpiInst, XIpiPs_ErrorIntrHandler, XIpiPs_IntrHandler, XMAILBOX_INTR_ID.
Referenced by XIpiPs_Init.