xilmailbox_ipips_control.h
u32 XIpiPs_Init(XMailbox *InstancePtr, UINTPTR BaseAddress)
Initialize the ZynqMP Mailbox Instance.
InstancePtr is a pointer to the instance to be worked on DeviceId is the IPI Instance to be worked on XST_SUCCESS if initialization was successful XST_FAILURE in case of failure
References XMboxTag::Agent, XMailbox_Agent::GicInst, XMailbox_Agent::IpiInst, XIpiPs_RegisterIrq.
Referenced by XMailbox_Initialize.
u32 XIpiPs_Send(XMailbox *InstancePtr, u8 Is_Blocking)
This function triggers an IPI to a destination CPU.
InstancePtr Pointer to the XMailbox instance. Is_Blocking if set trigger the notification in blocking mode XST_SUCCESS in case of success XST_FAILURE in case of failure This API will be deprecated in 2026.2 and will be made obsolete in 2027.1 release. The functionality of this API can be reproduced with XIpiPs_SendById.
References XMboxTag::Agent, XMailbox_Agent::IpiInst, XMailbox_Agent::RemoteId, XIpiPs_PollforDone.
u32 XIpiPs_SendById(XMailbox *InstancePtr, u32 RemoteId, u8 Is_Blocking)
This function triggers an IPI to a destination CPU.
InstancePtr Pointer to the XMailbox instance. RemoteId Mask of the CPU to which IPI is to be triggered Is_Blocking if set trigger the notification in blocking mode XST_SUCCESS in case of success XST_FAILURE in case of failure
References XMboxTag::Agent, XMailbox_Agent::IpiInst, XIpiPs_PollforDoneById.
Referenced by XMailbox_Initialize.
u32 XIpiPs_SendData(XMailbox *InstancePtr, void *MsgBufferPtr, u32 MsgLen, u8 BufferType, u8 Is_Blocking)
This function sends an IPI message to a destination CPU.
InstancePtr Pointer to the XMailbox instance MsgBufferPtr is the pointer to Buffer which contains the message to be sent MsgLen is the number of messages (each message is 4bytes) BufferType is the type of buffer Is_Blocking if set trigger the notification in blocking mode XST_SUCCESS in case of success XST_FAILURE in case of failure This API will be deprecated in 2026.2 and will be made obsolete in 2027.1 release. The functionality of this API can be reproduced with XIpiPs_SendDataById.
References XMboxTag::Agent, XMailbox_Agent::IpiInst, XMailbox_Agent::RemoteId, XIpiPs_PollforDone.
u32 XIpiPs_SendDataById(XMailbox *InstancePtr, void *MsgBufferPtr, u32 MsgLen, u8 BufferType, u32 RemoteId, u8 Is_Blocking)
This function sends an IPI message to a destination CPU.
InstancePtr Pointer to the XMailbox instance MsgBufferPtr is the pointer to Buffer which contains the message to be sent MsgLen is the number of messages (each message is 4bytes) BufferType is the type of buffer RemoteId Mask of the CPU to which IPI is to be triggered Is_Blocking if set trigger the notification in blocking mode XST_SUCCESS in case of success XST_FAILURE in case of failure
References XMboxTag::Agent, XMailbox_Agent::IpiInst, XIpiPs_PollforDoneById.
Referenced by XMailbox_Initialize.
u32 XIpiPs_RecvData(XMailbox *InstancePtr, void *MsgBufferPtr, u32 MsgLen, u8 BufferType)
This function reads an IPI message.
InstancePtr Pointer to the XMailbox instance MsgBufferPtr is the pointer to Buffer to which the read message needs to be stored MsgLen is the number of messages (each message is 4bytes) BufferType is the type of buffer XST_SUCCESS if successfulXST_FAILURE if unsuccessful This API will be deprecated in 2026.2 and will be made obsolete in 2027.1 release. The functionality of this API can be reproduced with XIpiPs_RecvDataById.
References XMboxTag::Agent, XMailbox_Agent::IpiInst, XMailbox_Agent::SourceId.
u32 XIpiPs_RecvDataById(XMailbox *InstancePtr, void *MsgBufferPtr, u32 MsgLen, u32 SourceId, u8 BufferType)
This function reads an IPI message.
InstancePtr Pointer to the XMailbox instance MsgBufferPtr is the pointer to Buffer to which the read message needs to be stored MsgLen is the number of messages (each message is 4bytes) SourceId Device Mask for the CPU which has sent the message BufferType is the type of buffer XST_SUCCESS if successfulXST_FAILURE if unsuccessful
References XMboxTag::Agent, XMailbox_Agent::IpiInst.
Referenced by XMailbox_Initialize.
u32 XIpiPs_PollforDone(XMailbox *InstancePtr)
Poll for an acknowledgement using Observation Register.
InstancePtr Pointer to the XMailbox instance XST_SUCCESS in case of success XST_FAILURE in case of failure This API will be deprecated in 2026.2 and will be made obsolete in 2027.1 release. The functionality of this API can be reproduced with XIpiPs_PollforDoneById.
References XMboxTag::Agent, XMailbox_Agent::IpiInst, XMailbox_Agent::RemoteId, XIPI_DONE_TIMEOUT_VAL, XIPI_IPI_DONE_BIT_SLEEP_IN_US.
Referenced by XIpiPs_Send, XIpiPs_SendData.
u32 XIpiPs_PollforDoneById(XMailbox *InstancePtr, u32 RemoteId)
Poll for an acknowledgement using Observation Register.
InstancePtr Pointer to the XMailbox instance RemoteId Mask of the destination CPU from which ACK is expected XST_SUCCESS in case of success XST_FAILURE in case of failure
References XMboxTag::Agent, XMailbox_Agent::IpiInst, XIPI_DONE_TIMEOUT_VAL, XIPI_IPI_DONE_BIT_SLEEP_IN_US.
Referenced by XIpiPs_SendById, XIpiPs_SendDataById.
void XIpiPs_IntrHandler(void *XMailboxPtr)
This function implements the interrupt handler.
XMailboxPtr Pointer to the XMailbox instance None
References XMboxTag::Agent, XMailbox_Agent::IpiInst, XMboxTag::RecvHandler, XMboxTag::RecvRefPtr.
Referenced by XIpiPs_RegisterIrq.
void XIpiPs_ErrorIntrHandler(void *XMailboxPtr)
This function implements the interrupt handler for errors.
XMailboxPtr Pointer to the XMailbox instance None
References XMboxTag::ErrorHandler, XMboxTag::ErrorRefPtr, IPI_BASEADDRESS.
Referenced by XIpiPs_RegisterIrq.
XStatus XIpiPs_RegisterIrq(XMailbox *InstancePtr, u32 IpiIntrId)
This function registers an irq.
IntcInstancePtr Pointer to the scugic instance InstancePtr Pointer to the XMailbox instance IpiIntrId is the interrupt id of the IPI XST_SUCCESS if successfulXST_FAILURE if unsuccessful
References XMboxTag::Agent, XMailbox_Agent::IpiInst, XIpiPs_ErrorIntrHandler, XIpiPs_IntrHandler, XMAILBOX_INTR_ID.
Referenced by XIpiPs_Init.