v_scenechange
static u32 XV_scenechange_get_sad(XV_scenechange *InstancePtr, u8 streamid)
Read SAD value for a specific stream.
This function reads the Sum of Absolute Differences (SAD) value for the specified stream from the hardware register. InstancePtr is a pointer to the XV_scenechange instance streamid is the stream identifier (0-7) SAD value read from the hardware register None
static void XV_scenechange_handler(XV_scenechange *ScdPtr)
Internal handler for scene change detection processing.
This function processes all enabled streams, calculates the normalized SAD threshold factor, and triggers the callback if a scene change is detected on any stream. ScdPtr is a pointer to the XV_scenechange instance None This is an internal handler called by the interrupt service routine
void XV_scenechange_SetCallback(XV_scenechange *InstancePtr, void *CallbackFunc, void *CallbackRef)
This function installs an asynchronous callback function:
InstancePtr is a pointer to the SceneChange IP instance. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. None. Invoking this function for a handler that already has been installed replaces it with the new handler.
Referenced by XV_SceneChange_init.
void XV_scenechange_InterruptHandler(void *InstancePtr)
This function is the interrupt handler for the Scenechange core driver.
This handler clears the pending interrupt and determined if the source is frame done signal. If yes, starts the next scenechange processing and calls the registered callback functionThe application is responsible for connecting this function to the interrupt system. Application beyond this driver is also responsible for providing callbacks to handle interrupts during initialization phase. InstancePtr is a pointer to the core instance that just interrupted. None. None.
References XV_SCENECHANGE_CTRL_ADDR_ISR_AP_DONE, XV_scenechange_InterruptClear, XV_scenechange_InterruptGetStatus.
Referenced by XV_SceneChange_init.
static void XV_scenechange_layer_height(XV_scenechange *InstancePtr, u32 Data, u8 streamid)
Set layer height for a specific stream.
This function writes the height value to the hardware register for the specified stream layer. InstancePtr is a pointer to the XV_scenechange instance Data is the height value to be set streamid is the stream identifier (0-7) None None
static void XV_scenechange_layer_set_width(XV_scenechange *InstancePtr, u32 Data, u8 streamid)
Set layer width for a specific stream.
This function writes the width value to the hardware register for the specified stream layer. InstancePtr is a pointer to the XV_scenechange instance Data is the width value to be set streamid is the stream identifier (0-7) None None
static void XV_scenechange_layer_set_stride(XV_scenechange *InstancePtr, u32 Data, u8 streamid)
Set layer stride for a specific stream.
This function writes the stride value to the hardware register for the specified stream layer. InstancePtr is a pointer to the XV_scenechange instance Data is the stride value to be set streamid is the stream identifier (0-7) None None
static void XV_scenechange_layer_set_vfmt(XV_scenechange *InstancePtr, u32 Data, u8 streamid)
Set video format for a specific stream.
This function writes the video format value to the hardware register for the specified stream layer. InstancePtr is a pointer to the XV_scenechange instance Data is the video format value to be set streamid is the stream identifier (0-7) None None
static void XV_scenechange_layer_set_subsample(XV_scenechange *InstancePtr, u32 Data, u8 streamid)
Set subsample value for a specific stream.
This function writes the subsample value to the hardware register for the specified stream layer. InstancePtr is a pointer to the XV_scenechange instance Data is the subsample value to be set streamid is the stream identifier (0-7) None None
static void XV_scenechange_layer_set_bufaddr(XV_scenechange *InstancePtr, u64 Data, u8 streamid)
Set frame buffer address for a specific stream.
This function writes the 64-bit frame buffer address to the hardware registers for the specified stream layer. The address is written as two 32-bit values. InstancePtr is a pointer to the XV_scenechange instance Data is the 64-bit buffer address to be set streamid is the stream identifier (0-7) None None
static void XV_scenechange_SetFlushbit(XV_scenechange *InstancePtr)
Set the flush bit in the control register.
This function sets the flush bit to initiate flushing of pending transactions in memory-based scene change IP. InstancePtr is a pointer to the XV_scenechange instance None Flush bit should be held until reset and requires hard reset after flush
static u32 XV_scenechange_Get_FlushDone(XV_scenechange *InstancePtr)
Get flush done status.
This function reads and returns the flush done status bit from the control register, indicating whether the flush operation has completed. InstancePtr is a pointer to the XV_scenechange instance Flush done status bit value (non-zero when flush is complete) None
int XV_scenechange_Layer_config(XV_scenechange *InstancePtr, u8 layerid)
Configure layer parameters for a specific stream.
This function validates and configures all layer parameters including width, height, stride, video format, subsample, and buffer address for the specified layer. It performs validation checks against IP capabilities. InstancePtr is a pointer to the XV_scenechange instance layerid is the layer identifier to configure (0-7) XST_SUCCESS if layer configuration is valid and completed XST_FAILURE if configuration parameters are invalid Validates layer ID, width, height, and video format compatibility
References XV_SCD_HAS_Y10, XV_SCD_HAS_Y8.
Referenced by XV_SceneChange_init.
void XV_scenechange_Layer_stream_enable(XV_scenechange *InstancePtr, u32 streams)
Enable specific streams for scene change detection.
This function enables one or more streams for scene change detection by writing the stream enable mask to the hardware register. InstancePtr is a pointer to the XV_scenechange instance streams is the bit mask of streams to enable (bit 0-7) None Each bit in the streams parameter corresponds to one stream
References XV_scenechange_Set_HwReg_stream_enable.
Referenced by XV_SceneChange_init.
u32 XV_scenechange_Stop(XV_scenechange *InstancePtr)
Stop the scene change core instance.
This function stops the core by disabling interrupts, auto-restart, and initiating a flush operation. For memory-based IP, it waits for the flush to complete before returning. InstancePtr is a pointer to the XV_scenechange instance XST_SUCCESS if the core is stopped and flush completed XST_FAILURE if flush operation timed out For memory-based IP, this function waits up to the flush timeout period
References XV_SCD_WAIT_FOR_FLUSH_DELAY, XV_SCD_WAIT_FOR_FLUSH_DONE, XV_SCENECHANGE_CTRL_ADDR_ISR_AP_DONE, XV_scenechange_DisableAutoRestart, XV_scenechange_InterruptDisable, XV_scenechange_InterruptGlobalDisable.
Referenced by main.
u32 XV_scenechange_WaitForIdle(XV_scenechange *InstancePtr)
Wait for the core to reach idle state.
This function polls the core idle status until the core becomes idle or the timeout period is reached. InstancePtr is a pointer to the XV_scenechange instance XST_SUCCESS if the core reached idle state XST_FAILURE if the core did not reach idle within timeout period Timeout is defined by XV_SCD_IDLE_TIMEOUT constant
References XV_SCD_IDLE_TIMEOUT, XV_scenechange_IsIdle.
Referenced by main.
void XV_scenechange_EnableInterrupts(void *InstancePtr)
Enable scene change interrupts.
This function enables the AP_DONE interrupt for the scene change core, allowing the interrupt handler to be triggered when processing completes. InstancePtr is a pointer to the XV_scenechange instance None None
References XV_SCENECHANGE_CTRL_ADDR_ISR_AP_DONE, XV_scenechange_InterruptEnable.
Referenced by XV_SceneChange_init.