xv_scenechange_sinit.c
XV_scenechange_Config XV_scenechange_ConfigTable[][]
Configuration table for SceneChange devices.
This table contains the configuration information for each SceneChange device in the system. Each entry includes device ID, base address, operational mode (memory/stream), and IP capabilities.
XV_scenechange_Config* XV_scenechange_LookupConfig(UINTPTR BaseAddress)
Look up the device configuration based on base address.
This function searches the configuration table for an entry matching the specified base address and returns a pointer to the configuration data. If BaseAddress is 0, returns the first available configuration. BaseAddress is the physical base address of the device Pointer to XV_scenechange_Config structure if found NULL if no matching base address is found This function is used in SDT (System Device Tree) builds
References XV_scenechange_Config::Name.
Referenced by XV_SceneChange_init, XV_scenechange_Initialize.
int XV_scenechange_Initialize(XV_scenechange *InstancePtr, UINTPTR BaseAddress)
Initialize the scene change driver instance using base address.
This function initializes the scene change driver by looking up the configuration data for the specified base address and performing the core initialization. InstancePtr is a pointer to the XV_scenechange instance BaseAddress is the physical base address of the device XST_SUCCESS if initialization succeeds XST_DEVICE_NOT_FOUND if the base address is not found This function is used in SDT (System Device Tree) builds
References XV_scenechange_CfgInitialize, XV_scenechange_LookupConfig.
Referenced by XV_SceneChange_init.