xv_scenechange_stream_mode_ex.c
IP_RESET_MASK
Bit mask for resetting all IPs in the pipeline.
SCD_STREAMS_ENABLE
Number of scene change detection streams to enable (max 8)
MAX_PATTERNS
Maximum number of test patterns supported by the Test Pattern Generator.
Referenced by main.
FB_COLOR_FORMAT
Framebuffer color format (refer to PG278 for format codes)
Referenced by FrameBuf_Config.
FB_CLRFMT_BYTES
Number of bytes per color component in framebuffer format.
Referenced by FrameBuf_Config.
u64 memaddr
u32 scd_height
u32 scd_width
u32 scd_stride
u32 scd_histbits
u32 scd_clrfmt
u32 scd_threshold
XV_tpg Tpg
XV_tpg_Config* Tpg_ConfigPtr
XTpg_PatternId Pattern
Video pattern.
Referenced by main, XV_ConfigTpg.
XV_FrmbufWr_l2 Frmbufwr
XV_frmbufwr_Config* FrmBufWr_ConfigPtr
XScuGic Intc
XV_scenechange ScdPtr
volatile u8 is_detected
volatile u8 sc_detected
void ClearScreen(void)
Clear the terminal screen.
This function clears the terminal screen and resets the cursor to the home position (0,0) using ANSI escape sequences.None Uses ANSI escape sequences which may not work on all terminals.
void SceneChangeDetectedCallback(void *CallbackRef)
Callback function for scene change detection.
This function is called when a scene change is detected by the IP. It prints the layer ID and SAD (Sum of Absolute Differences) value, and sets the detection flag. CallbackRef Pointer to callback reference (not used) None This callback is registered with XV_scenechange_SetCallback().
int XV_SceneChange_init()
Initialize the SceneChange IP.
This function initializes the SceneChange IP for stream mode operation, configures the enabled stream with its parameters (height, width, stride, color format, histogram bits, threshold), sets up interrupts, registers the callback, and starts the IP in auto-restart mode.XST_SUCCESS if initialization succeeds XST_FAILURE if any initialization step fails This function expects stream-based mode. It will fail for memory mode.
void reset_pipe(void)
Reset the video pipeline.
This function performs a hardware reset of the video processing pipeline by writing to the appropriate registers. The reset sequence ensures proper initialization of all IPs in the pipeline.None The reset sequence includes setting reset, clearing it, and setting it again to ensure proper IP initialization.
void XV_ConfigTpg(XV_tpg *InstancePtr)
Configure the Test Pattern Generator (TPG) IP.
This function configures the TPG IP with the specified parameters including height, width, color format, background pattern, and enables auto-restart mode. InstancePtr Pointer to the TPG instance None The TPG is configured for Y-only (grayscale) color format.
References Pattern.
Referenced by main.
void FrameBuf_Config()
Configure the Frame Buffer Write IP.
This function configures the Frame Buffer Write IP with the appropriate width, height, stride, video format, and memory buffer address. It enables auto-restart mode and starts the IP.None The frame buffer is configured to write frames to the memory address specified in the global memaddr variable.
References FB_CLRFMT_BYTES, FB_COLOR_FORMAT.
Referenced by scd_stream_mode_pipe_init.
u32 scd_stream_mode_pipe_init(void)
Initialize the video pipeline for stream mode.
This function initializes and configures the Test Pattern Generator (TPG) and Frame Buffer Write IPs. It looks up configurations, initializes each IP, sets up interrupts for the Frame Buffer Write IP, and configures the frame buffer.XST_SUCCESS if pipeline initialization succeeds XST_DEVICE_NOT_FOUND if device configuration lookup fails XST_FAILURE if initialization or interrupt setup fails This function must be called after XV_SceneChange_init().
References FrameBuf_Config.
Referenced by main.
int main()
Main function for SceneChange stream mode test application.
This application configures the SceneChange IP in stream mode to calculate SAD values between consecutive frames. It initializes the platform, configures the SceneChange IP, sets up a video pipeline with TPG and Frame Buffer Write, and cycles through different test patterns to trigger scene changes.XST_SUCCESS if scene change is detected and test passes XST_FAILURE if initialization fails or no scene change detected The test expects at least one scene change detection within MAX_PATTERNS iterations.
References ClearScreen, init_platform, MAX_PATTERNS, Pattern, reset_pipe, scd_stream_mode_pipe_init, XV_ConfigTpg, XV_SceneChange_init, XV_scenechange_Stop, XV_scenechange_WaitForIdle.