xv_scenechange_memory_mode_ex.c
IP_RESET_MASK
Mask for IP reset operations.
Referenced by reset_pipe.
SCD_STREAMS_ENABLE
Bitmask to enable SceneChange streams.
Referenced by XV_SceneChange_init.
SCD_LAYER_0
Layer index for the first SceneChange stream.
Referenced by main.
MAX_PATTERNS
Maximum number of test patterns to cycle through.
Referenced by main.
volatile u32 local_mem[8][8]
u64 memaddr[8][8]
u32 scd_height[XV_SCD_IP_MAX_STREAMS][XV_SCD_IP_MAX_STREAMS]
u32 scd_width[XV_SCD_IP_MAX_STREAMS][XV_SCD_IP_MAX_STREAMS]
u32 scd_stride[XV_SCD_IP_MAX_STREAMS][XV_SCD_IP_MAX_STREAMS]
u32 scd_histbits[XV_SCD_IP_MAX_STREAMS][XV_SCD_IP_MAX_STREAMS]
u32 scd_clrfmt[XV_SCD_IP_MAX_STREAMS][XV_SCD_IP_MAX_STREAMS]
u32 scd_threshold[XV_SCD_IP_MAX_STREAMS][XV_SCD_IP_MAX_STREAMS]
volatile u8 is_detected
volatile u8 sc_detected
XScuGic Intc
XV_scenechange ScdPtr
void SceneChangeDetectedCallback(void *CallbackRef)
Callback function for scene change detection.
This function is called when a scene change is detected by the IP. It prints the layer ID and SAD (Sum of Absolute Differences) value, and sets the detection flag. CallbackRef Pointer to callback reference (not used) None This callback is registered with XV_scenechange_SetCallback().
Referenced by XV_SceneChange_init.
int XV_SceneChange_init()
Initialize the SceneChange IP.
This function initializes the SceneChange IP, configures all enabled streams with their parameters (height, width, stride, color format, histogram bits, threshold), sets up interrupts, registers the callback, and starts the IP in auto-restart mode.XST_SUCCESS if initialization succeeds XST_FAILURE if any initialization step fails This function expects memory-based mode. It will fail for stream mode. This function initializes the SceneChange IP for stream mode operation, configures the enabled stream with its parameters (height, width, stride, color format, histogram bits, threshold), sets up interrupts, registers the callback, and starts the IP in auto-restart mode.XST_SUCCESS if initialization succeeds XST_FAILURE if any initialization step fails This function expects stream-based mode. It will fail for memory mode.
References SCD_STREAMS_ENABLE, SceneChangeDetectedCallback, XV_SCD_STREAM_MODE, XV_scenechange_EnableAutoRestart, XV_scenechange_EnableInterrupts, XV_scenechange_Initialize, XV_scenechange_InterruptGlobalEnable, XV_scenechange_InterruptHandler, XV_scenechange_Layer_config, XV_scenechange_Layer_stream_enable, XV_scenechange_LookupConfig, XV_scenechange_SetCallback, XV_scenechange_Start.
Referenced by main.
void reset_pipe(void)
Reset the video pipeline.
This function performs a hardware reset of the video processing pipeline. For GPIO-based systems, it toggles the GPIO reset signal. For other systems, it uses register writes to perform the reset sequence.None The reset sequence includes setting reset, clearing it, and setting it again to ensure proper IP initialization. This function performs a hardware reset of the video processing pipeline by writing to the appropriate registers. The reset sequence ensures proper initialization of all IPs in the pipeline.None The reset sequence includes setting reset, clearing it, and setting it again to ensure proper IP initialization.
References IP_RESET_MASK.
Referenced by main.
void ClearScreen(void)
Clear the terminal screen.
This function clears the terminal screen and resets the cursor to the home position (0,0) using ANSI escape sequences.None Uses ANSI escape sequences which may not work on all terminals.
Referenced by main.
int main()
Main function for SceneChange memory mode test application.
This application configures the SceneChange IP in memory mode to calculate SAD values between consecutive frames. It initializes the platform, configures the IP with test patterns, and monitors for scene change detections. The test cycles through different memory patterns to trigger scene changes.XST_SUCCESS if scene change is detected and test passes XST_FAILURE if initialization fails or no scene change detected The test expects at least one scene change detection within MAX_PATTERNS iterations.
References ClearScreen, init_platform, MAX_PATTERNS, reset_pipe, SCD_LAYER_0, XV_SceneChange_init, XV_scenechange_Stop, XV_scenechange_WaitForIdle.