xv_scenechange.h
XV_SCD_LAYER_OFFSET
Layer offset for scene change detection IP.
XV_SCD_IP_MAX_STREAMS
Maximum number of streams supported by scene change IP.
XV_SCD_WAIT_FOR_FLUSH_DONE
Wait count for flush done operation.
Referenced by XV_scenechange_Stop.
XV_SCD_WAIT_FOR_FLUSH_DELAY
Delay in microseconds for flush operation.
Referenced by XV_scenechange_Stop.
XV_SCD_IDLE_TIMEOUT
Idle timeout in microseconds for scene change IP.
Referenced by XV_scenechange_WaitForIdle.
XV_SCD_MEMORY_MODE
Memory based mode for scene change detection.
XV_SCD_STREAM_MODE
Stream mode for scene change detection.
Referenced by XV_SceneChange_init.
XV_scenechange_WriteReg
Write to register at specified offset.
Referenced by XV_scenechange_DisableAutoRestart, XV_scenechange_EnableAutoRestart, XV_scenechange_InterruptClear, XV_scenechange_InterruptDisable, XV_scenechange_InterruptEnable, XV_scenechange_InterruptGlobalDisable, XV_scenechange_InterruptGlobalEnable, XV_scenechange_Set_HwReg_frm_buffer0_V, XV_scenechange_Set_HwReg_frm_buffer1_V, XV_scenechange_Set_HwReg_frm_buffer2_V, XV_scenechange_Set_HwReg_frm_buffer3_V, XV_scenechange_Set_HwReg_frm_buffer4_V, XV_scenechange_Set_HwReg_frm_buffer5_V, XV_scenechange_Set_HwReg_frm_buffer6_V, XV_scenechange_Set_HwReg_frm_buffer7_V, XV_scenechange_Set_HwReg_height_0, XV_scenechange_Set_HwReg_height_1, XV_scenechange_Set_HwReg_height_2, XV_scenechange_Set_HwReg_height_3, XV_scenechange_Set_HwReg_height_4, XV_scenechange_Set_HwReg_height_5, XV_scenechange_Set_HwReg_height_6, XV_scenechange_Set_HwReg_height_7, XV_scenechange_Set_HwReg_stream_enable, XV_scenechange_Set_HwReg_stride_0, XV_scenechange_Set_HwReg_stride_1, XV_scenechange_Set_HwReg_stride_2, XV_scenechange_Set_HwReg_stride_3, XV_scenechange_Set_HwReg_stride_4, XV_scenechange_Set_HwReg_stride_5, XV_scenechange_Set_HwReg_stride_6, XV_scenechange_Set_HwReg_stride_7, XV_scenechange_Set_HwReg_subsample_0, XV_scenechange_Set_HwReg_subsample_1, XV_scenechange_Set_HwReg_subsample_2, XV_scenechange_Set_HwReg_subsample_3, XV_scenechange_Set_HwReg_subsample_4, XV_scenechange_Set_HwReg_subsample_5, XV_scenechange_Set_HwReg_subsample_6, XV_scenechange_Set_HwReg_subsample_7, XV_scenechange_Set_HwReg_video_format_0, XV_scenechange_Set_HwReg_video_format_1, XV_scenechange_Set_HwReg_video_format_2, XV_scenechange_Set_HwReg_video_format_3, XV_scenechange_Set_HwReg_video_format_4, XV_scenechange_Set_HwReg_video_format_5, XV_scenechange_Set_HwReg_video_format_6, XV_scenechange_Set_HwReg_video_format_7, XV_scenechange_Set_HwReg_width_0, XV_scenechange_Set_HwReg_width_1, XV_scenechange_Set_HwReg_width_2, XV_scenechange_Set_HwReg_width_3, XV_scenechange_Set_HwReg_width_4, XV_scenechange_Set_HwReg_width_5, XV_scenechange_Set_HwReg_width_6, XV_scenechange_Set_HwReg_width_7, XV_scenechange_Start.
XV_scenechange_ReadReg
Read from register at specified offset.
Referenced by XV_scenechange_Get_HwReg_frm_buffer0_V, XV_scenechange_Get_HwReg_frm_buffer1_V, XV_scenechange_Get_HwReg_frm_buffer2_V, XV_scenechange_Get_HwReg_frm_buffer3_V, XV_scenechange_Get_HwReg_frm_buffer4_V, XV_scenechange_Get_HwReg_frm_buffer5_V, XV_scenechange_Get_HwReg_frm_buffer6_V, XV_scenechange_Get_HwReg_frm_buffer7_V, XV_scenechange_Get_HwReg_height_0, XV_scenechange_Get_HwReg_height_1, XV_scenechange_Get_HwReg_height_2, XV_scenechange_Get_HwReg_height_3, XV_scenechange_Get_HwReg_height_4, XV_scenechange_Get_HwReg_height_5, XV_scenechange_Get_HwReg_height_6, XV_scenechange_Get_HwReg_height_7, XV_scenechange_Get_HwReg_sad0, XV_scenechange_Get_HwReg_sad0_vld, XV_scenechange_Get_HwReg_sad1, XV_scenechange_Get_HwReg_sad2, XV_scenechange_Get_HwReg_sad3, XV_scenechange_Get_HwReg_sad4, XV_scenechange_Get_HwReg_sad5, XV_scenechange_Get_HwReg_sad6, XV_scenechange_Get_HwReg_sad7, XV_scenechange_Get_HwReg_stream_enable, XV_scenechange_Get_HwReg_stride_0, XV_scenechange_Get_HwReg_stride_1, XV_scenechange_Get_HwReg_stride_2, XV_scenechange_Get_HwReg_stride_3, XV_scenechange_Get_HwReg_stride_4, XV_scenechange_Get_HwReg_stride_5, XV_scenechange_Get_HwReg_stride_6, XV_scenechange_Get_HwReg_stride_7, XV_scenechange_Get_HwReg_subsample_0, XV_scenechange_Get_HwReg_subsample_1, XV_scenechange_Get_HwReg_subsample_2, XV_scenechange_Get_HwReg_subsample_3, XV_scenechange_Get_HwReg_subsample_4, XV_scenechange_Get_HwReg_subsample_5, XV_scenechange_Get_HwReg_subsample_6, XV_scenechange_Get_HwReg_subsample_7, XV_scenechange_Get_HwReg_video_format_0, XV_scenechange_Get_HwReg_video_format_1, XV_scenechange_Get_HwReg_video_format_2, XV_scenechange_Get_HwReg_video_format_3, XV_scenechange_Get_HwReg_video_format_4, XV_scenechange_Get_HwReg_video_format_5, XV_scenechange_Get_HwReg_video_format_6, XV_scenechange_Get_HwReg_video_format_7, XV_scenechange_Get_HwReg_width_0, XV_scenechange_Get_HwReg_width_1, XV_scenechange_Get_HwReg_width_2, XV_scenechange_Get_HwReg_width_3, XV_scenechange_Get_HwReg_width_4, XV_scenechange_Get_HwReg_width_5, XV_scenechange_Get_HwReg_width_6, XV_scenechange_Get_HwReg_width_7, XV_scenechange_InterruptDisable, XV_scenechange_InterruptEnable, XV_scenechange_InterruptGetEnabled, XV_scenechange_InterruptGetStatus, XV_scenechange_IsDone, XV_scenechange_IsIdle, XV_scenechange_IsReady, XV_scenechange_Start.
XVScdClrFmt
Y8 (8-bit grayscale) format support enabled.
XVSceneChange_Callback)(void *InstancePtr)
Callback function pointer type for scene change detection events.
This typedef defines the signature for callback functions that are invoked when a scene change is detected by the XVSceneChange driver. InstancePtr Pointer to the XVSceneChange instance that triggered the callback. This allows the callback handler to identify which scene change detector instance generated the event. void The callback function should not perform time-consuming operations as it may be called from an interrupt context.
int XV_scenechange_Initialize(XV_scenechange *InstancePtr, UINTPTR BaseAddress)
Initialize the scene change driver instance using base address.
This function initializes the scene change driver by looking up the configuration data for the specified base address and performing the core initialization. InstancePtr is a pointer to the XV_scenechange instance BaseAddress is the physical base address of the device XST_SUCCESS if initialization succeeds XST_DEVICE_NOT_FOUND if the base address is not found This function is used in SDT (System Device Tree) builds
References XV_scenechange_CfgInitialize, XV_scenechange_LookupConfig.
Referenced by XV_SceneChange_init.
XV_scenechange_Config* XV_scenechange_LookupConfig(UINTPTR BaseAddress)
Look up the device configuration based on base address.
This function searches the configuration table for an entry matching the specified base address and returns a pointer to the configuration data. If BaseAddress is 0, returns the first available configuration. BaseAddress is the physical base address of the device Pointer to XV_scenechange_Config structure if found NULL if no matching base address is found This function is used in SDT (System Device Tree) builds
References XV_scenechange_Config::Name.
Referenced by XV_SceneChange_init, XV_scenechange_Initialize.
int XV_scenechange_CfgInitialize(XV_scenechange *InstancePtr, XV_scenechange_Config *ConfigPtr)
Initialize the scene change core instance.
This function initializes the scene change hardware instance by setting the base address and marking it as ready for use. InstancePtr is a pointer to the XV_scenechange instance ConfigPtr is a pointer to the configuration structure XST_SUCCESS indicating successful initialization This function is used in bare-metal (non-Linux) environments
References XV_scenechange_Config::Ctrl_BaseAddress.
Referenced by XV_scenechange_Initialize.
void XV_scenechange_Start(XV_scenechange *InstancePtr)
Start the scene change core.
This function starts the scene change hardware core by setting the ap_start bit in the control register while preserving the auto-restart bit. InstancePtr is a pointer to the XV_scenechange instance None None
References XV_SCENECHANGE_CTRL_ADDR_AP_CTRL, XV_scenechange_ReadReg, XV_scenechange_WriteReg.
Referenced by XV_SceneChange_init.
u32 XV_scenechange_IsDone(XV_scenechange *InstancePtr)
Check if core processing is done.
This function checks the ap_done bit in the control register to determine if the scene change core has completed processing. InstancePtr is a pointer to the XV_scenechange instance 1 if processing is done, 0 otherwise None
References XV_SCENECHANGE_CTRL_ADDR_AP_CTRL, XV_scenechange_ReadReg.
u32 XV_scenechange_IsIdle(XV_scenechange *InstancePtr)
Check if core is idle.
This function checks the ap_idle bit in the control register to determine if the scene change core is currently idle. InstancePtr is a pointer to the XV_scenechange instance 1 if core is idle, 0 otherwise None
References XV_SCENECHANGE_CTRL_ADDR_AP_CTRL, XV_scenechange_ReadReg.
Referenced by XV_scenechange_WaitForIdle.
u32 XV_scenechange_IsReady(XV_scenechange *InstancePtr)
Check if core is ready for next input.
This function checks the ap_start bit to determine if the core is ready to accept new input data. InstancePtr is a pointer to the XV_scenechange instance 1 if core is ready for next input, 0 otherwise None
References XV_SCENECHANGE_CTRL_ADDR_AP_CTRL, XV_scenechange_ReadReg.
void XV_scenechange_EnableAutoRestart(XV_scenechange *InstancePtr)
Enable auto-restart mode.
This function enables auto-restart mode by setting bit 7 in the control register, causing the core to automatically restart after completion. InstancePtr is a pointer to the XV_scenechange instance None None
References XV_SCENECHANGE_CTRL_ADDR_AP_CTRL, XV_scenechange_WriteReg.
Referenced by XV_SceneChange_init.
void XV_scenechange_DisableAutoRestart(XV_scenechange *InstancePtr)
Disable auto-restart mode.
This function disables auto-restart mode by clearing the control register, requiring manual restart after each completion. InstancePtr is a pointer to the XV_scenechange instance None None
References XV_SCENECHANGE_CTRL_ADDR_AP_CTRL, XV_scenechange_WriteReg.
Referenced by XV_scenechange_Stop.
void XV_scenechange_Set_HwReg_width_0(XV_scenechange *InstancePtr, u32 Data)
Set width value for Stream 0.
This function sets the width register value for stream 0. InstancePtr is a pointer to the XV_scenechange instance Data is the width value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_WIDTH_0_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_width_0(XV_scenechange *InstancePtr)
Get width value for Stream 0.
This function reads and returns the width register value for stream 0. InstancePtr is a pointer to the XV_scenechange instance Width value for stream 0 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_WIDTH_0_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_height_0(XV_scenechange *InstancePtr, u32 Data)
Set height value for Stream 0.
This function sets the height register value for stream 0. InstancePtr is a pointer to the XV_scenechange instance Data is the height value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_HEIGHT_0_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_height_0(XV_scenechange *InstancePtr)
Get height value for Stream 0.
This function reads and returns the height register value for stream 0. InstancePtr is a pointer to the XV_scenechange instance Height value for stream 0 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_HEIGHT_0_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_stride_0(XV_scenechange *InstancePtr, u32 Data)
Set stride value for Stream 0.
This function sets the stride register value for stream 0. InstancePtr is a pointer to the XV_scenechange instance Data is the stride value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_STRIDE_0_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_stride_0(XV_scenechange *InstancePtr)
Get stride value for Stream 0.
This function reads and returns the stride register value for stream 0. InstancePtr is a pointer to the XV_scenechange instance Stride value for stream 0 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_STRIDE_0_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_video_format_0(XV_scenechange *InstancePtr, u32 Data)
Set video format value for Stream 0.
This function sets the video format register value for stream 0. InstancePtr is a pointer to the XV_scenechange instance Data is the video format value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_VIDEO_FORMAT_0_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_video_format_0(XV_scenechange *InstancePtr)
Get video format value for Stream 0.
This function reads and returns the video format register value for stream 0. InstancePtr is a pointer to the XV_scenechange instance Video format value for stream 0 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_VIDEO_FORMAT_0_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_subsample_0(XV_scenechange *InstancePtr, u32 Data)
Set subsample value for Stream 0.
This function sets the subsample register value for stream 0. InstancePtr is a pointer to the XV_scenechange instance Data is the subsample value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_SUBSAMPLE_0_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_subsample_0(XV_scenechange *InstancePtr)
Get subsample value for Stream 0.
This function reads and returns the subsample register value for stream 0. InstancePtr is a pointer to the XV_scenechange instance Subsample value for stream 0 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_SUBSAMPLE_0_DATA, XV_scenechange_ReadReg.
u32 XV_scenechange_Get_HwReg_sad0(XV_scenechange *InstancePtr)
Get SAD (Sum of Absolute Differences) value for Stream 0.
This function reads and returns the SAD data register value for stream 0. InstancePtr is a pointer to the XV_scenechange instance SAD value for stream 0 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_SAD0_DATA, XV_scenechange_ReadReg.
u32 XV_scenechange_Get_HwReg_sad0_vld(XV_scenechange *InstancePtr)
Get SAD valid flag for Stream 0.
This function reads the SAD control register and returns the valid bit indicating whether the SAD value is valid. InstancePtr is a pointer to the XV_scenechange instance 1 if SAD value is valid, 0 otherwise None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_SAD0_CTRL, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_frm_buffer0_V(XV_scenechange *InstancePtr, u32 Data)
Set frame buffer address for Stream 0.
This function sets the frame buffer address register for stream 0. InstancePtr is a pointer to the XV_scenechange instance Data is the frame buffer address to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_FRM_BUFFER0_V_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_frm_buffer0_V(XV_scenechange *InstancePtr)
Get frame buffer address for Stream 0.
This function reads and returns the frame buffer address register for stream 0. InstancePtr is a pointer to the XV_scenechange instance Frame buffer address for stream 0 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_FRM_BUFFER0_V_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_width_1(XV_scenechange *InstancePtr, u32 Data)
Set width value for Stream 1.
This function sets the width register value for stream 1. InstancePtr is a pointer to the XV_scenechange instance Data is the width value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_WIDTH_1_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_width_1(XV_scenechange *InstancePtr)
Get width value for Stream 1.
This function reads and returns the width register value for stream 1. InstancePtr is a pointer to the XV_scenechange instance Width value for stream 1 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_WIDTH_1_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_height_1(XV_scenechange *InstancePtr, u32 Data)
Set height value for Stream 1.
This function sets the height register value for stream 1. InstancePtr is a pointer to the XV_scenechange instance Data is the height value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_HEIGHT_1_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_height_1(XV_scenechange *InstancePtr)
Get height value for Stream 1.
This function reads and returns the height register value for stream 1. InstancePtr is a pointer to the XV_scenechange instance Height value for stream 1 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_HEIGHT_1_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_stride_1(XV_scenechange *InstancePtr, u32 Data)
Set stride value for Stream 1.
This function sets the stride register value for stream 1. InstancePtr is a pointer to the XV_scenechange instance Data is the stride value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_STRIDE_1_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_stride_1(XV_scenechange *InstancePtr)
Get stride value for Stream 1.
This function reads and returns the stride register value for stream 1. InstancePtr is a pointer to the XV_scenechange instance Stride value for stream 1 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_STRIDE_1_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_video_format_1(XV_scenechange *InstancePtr, u32 Data)
Set video format value for Stream 1.
This function sets the video format register value for stream 1. InstancePtr is a pointer to the XV_scenechange instance Data is the video format value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_VIDEO_FORMAT_1_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_video_format_1(XV_scenechange *InstancePtr)
Get video format value for Stream 1.
This function reads and returns the video format register value for stream 1. InstancePtr is a pointer to the XV_scenechange instance Video format value for stream 1 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_VIDEO_FORMAT_1_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_subsample_1(XV_scenechange *InstancePtr, u32 Data)
Set subsample value for Stream 1.
This function sets the subsample register value for stream 1. InstancePtr is a pointer to the XV_scenechange instance Data is the subsample value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_SUBSAMPLE_1_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_subsample_1(XV_scenechange *InstancePtr)
Get subsample value for Stream 1.
This function reads and returns the subsample register value for stream 1. InstancePtr is a pointer to the XV_scenechange instance Subsample value for stream 1 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_SUBSAMPLE_1_DATA, XV_scenechange_ReadReg.
u32 XV_scenechange_Get_HwReg_sad1(XV_scenechange *InstancePtr)
Get SAD (Sum of Absolute Differences) value for Stream 1.
This function reads and returns the SAD data register value for stream 1. InstancePtr is a pointer to the XV_scenechange instance SAD value for stream 1 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_SAD1_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_frm_buffer1_V(XV_scenechange *InstancePtr, u32 Data)
Set frame buffer address for Stream 1.
This function sets the frame buffer address register for stream 1. InstancePtr is a pointer to the XV_scenechange instance Data is the frame buffer address to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_FRM_BUFFER1_V_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_frm_buffer1_V(XV_scenechange *InstancePtr)
Get frame buffer address for Stream 1.
This function reads and returns the frame buffer address register for stream 1. InstancePtr is a pointer to the XV_scenechange instance Frame buffer address for stream 1 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_FRM_BUFFER1_V_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_width_2(XV_scenechange *InstancePtr, u32 Data)
Set width value for Stream 2.
This function sets the width register value for stream 2. InstancePtr is a pointer to the XV_scenechange instance Data is the width value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_WIDTH_2_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_width_2(XV_scenechange *InstancePtr)
Get width value for Stream 2.
This function reads and returns the width register value for stream 2. InstancePtr is a pointer to the XV_scenechange instance Width value for stream 2 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_WIDTH_2_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_height_2(XV_scenechange *InstancePtr, u32 Data)
Set height value for Stream 2.
This function sets the height register value for stream 2. InstancePtr is a pointer to the XV_scenechange instance Data is the height value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_HEIGHT_2_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_height_2(XV_scenechange *InstancePtr)
Get height value for Stream 2.
This function reads and returns the height register value for stream 2. InstancePtr is a pointer to the XV_scenechange instance Height value for stream 2 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_HEIGHT_2_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_stride_2(XV_scenechange *InstancePtr, u32 Data)
Set stride value for Stream 2.
This function sets the stride register value for stream 2. InstancePtr is a pointer to the XV_scenechange instance Data is the stride value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_STRIDE_2_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_stride_2(XV_scenechange *InstancePtr)
Get stride value for Stream 2.
This function reads and returns the stride register value for stream 2. InstancePtr is a pointer to the XV_scenechange instance Stride value for stream 2 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_STRIDE_2_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_video_format_2(XV_scenechange *InstancePtr, u32 Data)
Set video format value for Stream 2.
This function sets the video format register value for stream 2. InstancePtr is a pointer to the XV_scenechange instance Data is the video format value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_VIDEO_FORMAT_2_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_video_format_2(XV_scenechange *InstancePtr)
Get video format value for Stream 2.
This function reads and returns the video format register value for stream 2. InstancePtr is a pointer to the XV_scenechange instance Video format value for stream 2 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_VIDEO_FORMAT_2_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_subsample_2(XV_scenechange *InstancePtr, u32 Data)
Set subsample value for Stream 2.
This function sets the subsample register value for stream 2. InstancePtr is a pointer to the XV_scenechange instance Data is the subsample value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_SUBSAMPLE_2_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_subsample_2(XV_scenechange *InstancePtr)
Get subsample value for Stream 2.
This function reads and returns the subsample register value for stream 2. InstancePtr is a pointer to the XV_scenechange instance Subsample value for stream 2 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_SUBSAMPLE_2_DATA, XV_scenechange_ReadReg.
u32 XV_scenechange_Get_HwReg_sad2(XV_scenechange *InstancePtr)
Get SAD (Sum of Absolute Differences) value for Stream 2.
This function reads and returns the SAD data register value for stream 2. InstancePtr is a pointer to the XV_scenechange instance SAD value for stream 2 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_SAD2_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_frm_buffer2_V(XV_scenechange *InstancePtr, u32 Data)
Set frame buffer address for Stream 2.
This function sets the frame buffer address register for stream 2. InstancePtr is a pointer to the XV_scenechange instance Data is the frame buffer address to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_FRM_BUFFER2_V_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_frm_buffer2_V(XV_scenechange *InstancePtr)
Get frame buffer address for Stream 2.
This function reads and returns the frame buffer address register for stream 2. InstancePtr is a pointer to the XV_scenechange instance Frame buffer address for stream 2 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_FRM_BUFFER2_V_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_width_3(XV_scenechange *InstancePtr, u32 Data)
Set width value for Stream 3.
This function sets the width register value for stream 3. InstancePtr is a pointer to the XV_scenechange instance Data is the width value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_WIDTH_3_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_width_3(XV_scenechange *InstancePtr)
Get width value for Stream 3.
This function reads and returns the width register value for stream 3. InstancePtr is a pointer to the XV_scenechange instance Width value for stream 3 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_WIDTH_3_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_height_3(XV_scenechange *InstancePtr, u32 Data)
Set height value for Stream 3.
This function sets the height register value for stream 3. InstancePtr is a pointer to the XV_scenechange instance Data is the height value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_HEIGHT_3_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_height_3(XV_scenechange *InstancePtr)
Get height value for Stream 3.
This function reads and returns the height register value for stream 3. InstancePtr is a pointer to the XV_scenechange instance Height value for stream 3 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_HEIGHT_3_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_stride_3(XV_scenechange *InstancePtr, u32 Data)
Set stride value for Stream 3.
This function sets the stride register value for stream 3. InstancePtr is a pointer to the XV_scenechange instance Data is the stride value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_STRIDE_3_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_stride_3(XV_scenechange *InstancePtr)
Get stride value for Stream 3.
This function reads and returns the stride register value for stream 3. InstancePtr is a pointer to the XV_scenechange instance Stride value for stream 3 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_STRIDE_3_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_video_format_3(XV_scenechange *InstancePtr, u32 Data)
Set video format value for Stream 3.
This function sets the video format register value for stream 3. InstancePtr is a pointer to the XV_scenechange instance Data is the video format value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_VIDEO_FORMAT_3_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_video_format_3(XV_scenechange *InstancePtr)
Get video format value for Stream 3.
This function reads and returns the video format register value for stream 3. InstancePtr is a pointer to the XV_scenechange instance Video format value for stream 3 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_VIDEO_FORMAT_3_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_subsample_3(XV_scenechange *InstancePtr, u32 Data)
Set subsample value for Stream 3.
This function sets the subsample register value for stream 3. InstancePtr is a pointer to the XV_scenechange instance Data is the subsample value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_SUBSAMPLE_3_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_subsample_3(XV_scenechange *InstancePtr)
Get subsample value for Stream 3.
This function reads and returns the subsample register value for stream 3. InstancePtr is a pointer to the XV_scenechange instance Subsample value for stream 3 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_SUBSAMPLE_3_DATA, XV_scenechange_ReadReg.
u32 XV_scenechange_Get_HwReg_sad3(XV_scenechange *InstancePtr)
Get SAD (Sum of Absolute Differences) value for Stream 3.
This function reads and returns the SAD register value for stream 3. InstancePtr is a pointer to the XV_scenechange instance SAD value for stream 3 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_SAD3_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_frm_buffer3_V(XV_scenechange *InstancePtr, u32 Data)
Set frame buffer address for Stream 3.
This function sets the frame buffer base address for stream 3. InstancePtr is a pointer to the XV_scenechange instance Data is the frame buffer address to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_FRM_BUFFER3_V_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_frm_buffer3_V(XV_scenechange *InstancePtr)
Get frame buffer address for Stream 3.
This function reads and returns the frame buffer base address for stream 3. InstancePtr is a pointer to the XV_scenechange instance Frame buffer address for stream 3 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_FRM_BUFFER3_V_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_width_4(XV_scenechange *InstancePtr, u32 Data)
Set width value for Stream 4.
This function sets the width register value for stream 4. InstancePtr is a pointer to the XV_scenechange instance Data is the width value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_WIDTH_4_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_width_4(XV_scenechange *InstancePtr)
Get width value for Stream 4.
This function reads and returns the width register value for stream 4. InstancePtr is a pointer to the XV_scenechange instance Width value for stream 4 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_WIDTH_4_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_height_4(XV_scenechange *InstancePtr, u32 Data)
Set height value for Stream 4.
This function sets the height register value for stream 4. InstancePtr is a pointer to the XV_scenechange instance Data is the height value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_HEIGHT_4_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_height_4(XV_scenechange *InstancePtr)
Get height value for Stream 4.
This function reads and returns the height register value for stream 4. InstancePtr is a pointer to the XV_scenechange instance Height value for stream 4 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_HEIGHT_4_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_stride_4(XV_scenechange *InstancePtr, u32 Data)
Set stride value for Stream 4.
This function sets the stride register value for stream 4. InstancePtr is a pointer to the XV_scenechange instance Data is the stride value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_STRIDE_4_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_stride_4(XV_scenechange *InstancePtr)
Get stride value for Stream 4.
This function reads and returns the stride register value for stream 4. InstancePtr is a pointer to the XV_scenechange instance Stride value for stream 4 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_STRIDE_4_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_video_format_4(XV_scenechange *InstancePtr, u32 Data)
Set video format value for Stream 4.
This function sets the video format register value for stream 4. InstancePtr is a pointer to the XV_scenechange instance Data is the video format value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_VIDEO_FORMAT_4_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_video_format_4(XV_scenechange *InstancePtr)
Get video format value for Stream 4.
This function reads and returns the video format register value for stream 4. InstancePtr is a pointer to the XV_scenechange instance Video format value for stream 4 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_VIDEO_FORMAT_4_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_subsample_4(XV_scenechange *InstancePtr, u32 Data)
Set subsample value for Stream 4.
This function sets the subsample register value for stream 4. InstancePtr is a pointer to the XV_scenechange instance Data is the subsample value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_SUBSAMPLE_4_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_subsample_4(XV_scenechange *InstancePtr)
Get subsample value for Stream 4.
This function reads and returns the subsample register value for stream 4. InstancePtr is a pointer to the XV_scenechange instance Subsample value for stream 4 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_SUBSAMPLE_4_DATA, XV_scenechange_ReadReg.
u32 XV_scenechange_Get_HwReg_sad4(XV_scenechange *InstancePtr)
Get SAD (Sum of Absolute Differences) value for Stream 4.
This function reads and returns the SAD register value for stream 4. InstancePtr is a pointer to the XV_scenechange instance SAD value for stream 4 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_SAD4_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_frm_buffer4_V(XV_scenechange *InstancePtr, u32 Data)
Set frame buffer address for Stream 4.
This function sets the frame buffer base address for stream 4. InstancePtr is a pointer to the XV_scenechange instance Data is the frame buffer address to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_FRM_BUFFER4_V_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_frm_buffer4_V(XV_scenechange *InstancePtr)
Get frame buffer address for Stream 4.
This function reads and returns the frame buffer base address for stream 4. InstancePtr is a pointer to the XV_scenechange instance Frame buffer address for stream 4 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_FRM_BUFFER4_V_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_width_5(XV_scenechange *InstancePtr, u32 Data)
Set width value for Stream 5.
This function sets the width register value for stream 5. InstancePtr is a pointer to the XV_scenechange instance Data is the width value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_WIDTH_5_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_width_5(XV_scenechange *InstancePtr)
Get width value for Stream 5.
This function reads and returns the width register value for stream 5. InstancePtr is a pointer to the XV_scenechange instance Width value for stream 5 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_WIDTH_5_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_height_5(XV_scenechange *InstancePtr, u32 Data)
Set height value for Stream 5.
This function sets the height register value for stream 5. InstancePtr is a pointer to the XV_scenechange instance Data is the height value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_HEIGHT_5_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_height_5(XV_scenechange *InstancePtr)
Get height value for Stream 5.
This function reads and returns the height register value for stream 5. InstancePtr is a pointer to the XV_scenechange instance Height value for stream 5 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_HEIGHT_5_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_stride_5(XV_scenechange *InstancePtr, u32 Data)
Set stride value for Stream 5.
This function sets the stride register value for stream 5. InstancePtr is a pointer to the XV_scenechange instance Data is the stride value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_STRIDE_5_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_stride_5(XV_scenechange *InstancePtr)
Get stride value for Stream 5.
This function reads and returns the stride register value for stream 5. InstancePtr is a pointer to the XV_scenechange instance Stride value for stream 5 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_STRIDE_5_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_video_format_5(XV_scenechange *InstancePtr, u32 Data)
Set video format value for Stream 5.
This function sets the video format register value for stream 5. InstancePtr is a pointer to the XV_scenechange instance Data is the video format value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_VIDEO_FORMAT_5_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_video_format_5(XV_scenechange *InstancePtr)
Get video format value for Stream 5.
This function reads and returns the video format register value for stream 5. InstancePtr is a pointer to the XV_scenechange instance Video format value for stream 5 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_VIDEO_FORMAT_5_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_subsample_5(XV_scenechange *InstancePtr, u32 Data)
Set subsample value for Stream 5.
This function sets the subsample register value for stream 5. InstancePtr is a pointer to the XV_scenechange instance Data is the subsample value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_SUBSAMPLE_5_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_subsample_5(XV_scenechange *InstancePtr)
Get subsample value for Stream 5.
This function reads and returns the subsample register value for stream 5. InstancePtr is a pointer to the XV_scenechange instance Subsample value for stream 5 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_SUBSAMPLE_5_DATA, XV_scenechange_ReadReg.
u32 XV_scenechange_Get_HwReg_sad5(XV_scenechange *InstancePtr)
Get SAD (Sum of Absolute Differences) value for Stream 5.
This function reads and returns the SAD register value for stream 5. InstancePtr is a pointer to the XV_scenechange instance SAD value for stream 5 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_SAD5_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_frm_buffer5_V(XV_scenechange *InstancePtr, u32 Data)
Set frame buffer address for Stream 5.
This function sets the frame buffer base address for stream 5. InstancePtr is a pointer to the XV_scenechange instance Data is the frame buffer address to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_FRM_BUFFER5_V_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_frm_buffer5_V(XV_scenechange *InstancePtr)
Get frame buffer address for Stream 5.
This function reads and returns the frame buffer base address for stream 5. InstancePtr is a pointer to the XV_scenechange instance Frame buffer address for stream 5 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_FRM_BUFFER5_V_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_width_6(XV_scenechange *InstancePtr, u32 Data)
Set width value for Stream 6.
This function sets the width register value for stream 6. InstancePtr is a pointer to the XV_scenechange instance Data is the width value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_WIDTH_6_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_width_6(XV_scenechange *InstancePtr)
Get width value for Stream 6.
This function reads and returns the width register value for stream 6. InstancePtr is a pointer to the XV_scenechange instance Width value for stream 6 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_WIDTH_6_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_height_6(XV_scenechange *InstancePtr, u32 Data)
Set height value for Stream 6.
This function sets the height register value for stream 6. InstancePtr is a pointer to the XV_scenechange instance Data is the height value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_HEIGHT_6_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_height_6(XV_scenechange *InstancePtr)
Get height value for Stream 6.
This function reads and returns the height register value for stream 6. InstancePtr is a pointer to the XV_scenechange instance Height value for stream 6 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_HEIGHT_6_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_stride_6(XV_scenechange *InstancePtr, u32 Data)
Set stride value for Stream 6.
This function sets the stride register value for stream 6. InstancePtr is a pointer to the XV_scenechange instance Data is the stride value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_STRIDE_6_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_stride_6(XV_scenechange *InstancePtr)
Get stride value for Stream 6.
This function reads and returns the stride register value for stream 6. InstancePtr is a pointer to the XV_scenechange instance Stride value for stream 6 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_STRIDE_6_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_video_format_6(XV_scenechange *InstancePtr, u32 Data)
Set video format value for Stream 6.
This function sets the video format register value for stream 6. InstancePtr is a pointer to the XV_scenechange instance Data is the video format value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_VIDEO_FORMAT_6_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_video_format_6(XV_scenechange *InstancePtr)
Get video format value for Stream 6.
This function reads and returns the video format register value for stream 6. InstancePtr is a pointer to the XV_scenechange instance Video format value for stream 6 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_VIDEO_FORMAT_6_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_subsample_6(XV_scenechange *InstancePtr, u32 Data)
Set subsample value for Stream 6.
This function sets the subsample register value for stream 6. InstancePtr is a pointer to the XV_scenechange instance Data is the subsample value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_SUBSAMPLE_6_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_subsample_6(XV_scenechange *InstancePtr)
Get subsample value for Stream 6.
This function reads and returns the subsample register value for stream 6. InstancePtr is a pointer to the XV_scenechange instance Subsample value for stream 6 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_SUBSAMPLE_6_DATA, XV_scenechange_ReadReg.
u32 XV_scenechange_Get_HwReg_sad6(XV_scenechange *InstancePtr)
Get SAD (Sum of Absolute Differences) value for Stream 6.
This function reads and returns the SAD register value for stream 6. InstancePtr is a pointer to the XV_scenechange instance SAD value for stream 6 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_SAD6_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_frm_buffer6_V(XV_scenechange *InstancePtr, u32 Data)
Set frame buffer address for Stream 6.
This function sets the frame buffer base address for stream 6. InstancePtr is a pointer to the XV_scenechange instance Data is the frame buffer address to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_FRM_BUFFER6_V_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_frm_buffer6_V(XV_scenechange *InstancePtr)
Get frame buffer address for Stream 6.
This function reads and returns the frame buffer base address for stream 6. InstancePtr is a pointer to the XV_scenechange instance Frame buffer address for stream 6 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_FRM_BUFFER6_V_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_width_7(XV_scenechange *InstancePtr, u32 Data)
Set width value for Stream 7.
This function sets the width register value for stream 7. InstancePtr is a pointer to the XV_scenechange instance Data is the width value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_WIDTH_7_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_width_7(XV_scenechange *InstancePtr)
Get width value for Stream 7.
This function reads and returns the width register value for stream 7. InstancePtr is a pointer to the XV_scenechange instance Width value for stream 7 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_WIDTH_7_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_height_7(XV_scenechange *InstancePtr, u32 Data)
Set height value for Stream 7.
This function sets the height register value for stream 7. InstancePtr is a pointer to the XV_scenechange instance Data is the height value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_HEIGHT_7_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_height_7(XV_scenechange *InstancePtr)
Get height value for Stream 7.
This function reads and returns the height register value for stream 7. InstancePtr is a pointer to the XV_scenechange instance Height value for stream 7 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_HEIGHT_7_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_stride_7(XV_scenechange *InstancePtr, u32 Data)
Set stride value for Stream 7.
This function sets the stride register value for stream 7. InstancePtr is a pointer to the XV_scenechange instance Data is the stride value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_STRIDE_7_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_stride_7(XV_scenechange *InstancePtr)
Get stride value for Stream 7.
This function reads and returns the stride register value for stream 7. InstancePtr is a pointer to the XV_scenechange instance Stride value for stream 7 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_STRIDE_7_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_video_format_7(XV_scenechange *InstancePtr, u32 Data)
Set video format value for Stream 7.
This function sets the video format register value for stream 7. InstancePtr is a pointer to the XV_scenechange instance Data is the video format value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_VIDEO_FORMAT_7_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_video_format_7(XV_scenechange *InstancePtr)
Get video format value for Stream 7.
This function reads and returns the video format register value for stream 7. InstancePtr is a pointer to the XV_scenechange instance Video format value for stream 7 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_VIDEO_FORMAT_7_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_subsample_7(XV_scenechange *InstancePtr, u32 Data)
Set subsample value for Stream 7.
This function sets the subsample register value for stream 7. InstancePtr is a pointer to the XV_scenechange instance Data is the subsample value to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_SUBSAMPLE_7_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_subsample_7(XV_scenechange *InstancePtr)
Get subsample value for Stream 7.
This function reads and returns the subsample register value for stream 7. InstancePtr is a pointer to the XV_scenechange instance Subsample value for stream 7 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_SUBSAMPLE_7_DATA, XV_scenechange_ReadReg.
u32 XV_scenechange_Get_HwReg_sad7(XV_scenechange *InstancePtr)
Get SAD (Sum of Absolute Differences) value for Stream 7.
This function reads and returns the SAD register value for stream 7. InstancePtr is a pointer to the XV_scenechange instance SAD value for stream 7 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_SAD7_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_frm_buffer7_V(XV_scenechange *InstancePtr, u32 Data)
Set frame buffer address for Stream 7.
This function sets the frame buffer base address for stream 7. InstancePtr is a pointer to the XV_scenechange instance Data is the frame buffer address to set None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_FRM_BUFFER7_V_DATA, XV_scenechange_WriteReg.
u32 XV_scenechange_Get_HwReg_frm_buffer7_V(XV_scenechange *InstancePtr)
Get frame buffer address for Stream 7.
This function reads and returns the frame buffer base address for stream 7. InstancePtr is a pointer to the XV_scenechange instance Frame buffer address for stream 7 None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_FRM_BUFFER7_V_DATA, XV_scenechange_ReadReg.
void XV_scenechange_Set_HwReg_stream_enable(XV_scenechange *InstancePtr, u32 Data)
Set stream enable mask.
This function sets the stream enable register to enable/disable specific streams for scene change detection. InstancePtr is a pointer to the XV_scenechange instance Data is the stream enable bitmask (bits 0-7 for streams 0-7) None None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_STREAM_ENABLE_DATA, XV_scenechange_WriteReg.
Referenced by XV_scenechange_Layer_stream_enable.
u32 XV_scenechange_Get_HwReg_stream_enable(XV_scenechange *InstancePtr)
Get stream enable mask.
This function reads and returns the stream enable register indicating which streams are currently enabled. InstancePtr is a pointer to the XV_scenechange instance Stream enable bitmask (bits 0-7 for streams 0-7) None
References XV_SCENECHANGE_CTRL_ADDR_HWREG_STREAM_ENABLE_DATA, XV_scenechange_ReadReg.
void XV_scenechange_InterruptGlobalEnable(XV_scenechange *InstancePtr)
Enable global interrupts.
This function enables the global interrupt output by setting the Global Interrupt Enable (GIE) register. InstancePtr is a pointer to the XV_scenechange instance None None
References XV_SCENECHANGE_CTRL_ADDR_GIE, XV_scenechange_WriteReg.
Referenced by XV_SceneChange_init.
void XV_scenechange_InterruptGlobalDisable(XV_scenechange *InstancePtr)
Disable global interrupts.
This function disables the global interrupt output by clearing the Global Interrupt Enable (GIE) register. InstancePtr is a pointer to the XV_scenechange instance None None
References XV_SCENECHANGE_CTRL_ADDR_GIE, XV_scenechange_WriteReg.
Referenced by XV_scenechange_Stop.
void XV_scenechange_InterruptEnable(XV_scenechange *InstancePtr, u32 Mask)
Enable specific interrupts.
This function enables the interrupts specified by the Mask parameter by setting the corresponding bits in the Interrupt Enable Register (IER). InstancePtr is a pointer to the XV_scenechange instance Mask is the bitmask of interrupts to enable None None
References XV_SCENECHANGE_CTRL_ADDR_IER, XV_scenechange_ReadReg, XV_scenechange_WriteReg.
Referenced by XV_scenechange_EnableInterrupts.
void XV_scenechange_InterruptDisable(XV_scenechange *InstancePtr, u32 Mask)
Disable specific interrupts.
This function disables the interrupts specified by the Mask parameter by clearing the corresponding bits in the Interrupt Enable Register (IER). InstancePtr is a pointer to the XV_scenechange instance Mask is the bitmask of interrupts to disable None None
References XV_SCENECHANGE_CTRL_ADDR_IER, XV_scenechange_ReadReg, XV_scenechange_WriteReg.
Referenced by XV_scenechange_Stop.
void XV_scenechange_InterruptClear(XV_scenechange *InstancePtr, u32 Mask)
Clear pending interrupts.
This function clears the pending interrupts specified by the Mask parameter by writing to the Interrupt Status Register (ISR). InstancePtr is a pointer to the XV_scenechange instance Mask is the bitmask of interrupts to clear None None
References XV_SCENECHANGE_CTRL_ADDR_ISR, XV_scenechange_WriteReg.
Referenced by XV_scenechange_InterruptHandler.
u32 XV_scenechange_InterruptGetEnabled(XV_scenechange *InstancePtr)
Get enabled interrupts.
This function reads and returns the Interrupt Enable Register (IER) indicating which interrupts are currently enabled. InstancePtr is a pointer to the XV_scenechange instance Bitmask of enabled interrupts None
References XV_SCENECHANGE_CTRL_ADDR_IER, XV_scenechange_ReadReg.
u32 XV_scenechange_InterruptGetStatus(XV_scenechange *InstancePtr)
Get interrupt status.
This function reads and returns the Interrupt Status Register (ISR) indicating which interrupts are currently pending. InstancePtr is a pointer to the XV_scenechange instance Bitmask of pending interrupts None
References XV_SCENECHANGE_CTRL_ADDR_ISR, XV_scenechange_ReadReg.
Referenced by XV_scenechange_InterruptHandler.
void XV_scenechange_InterruptHandler(void *InstancePtr)
This function is the interrupt handler for the Scenechange core driver.
This handler clears the pending interrupt and determined if the source is frame done signal. If yes, starts the next scenechange processing and calls the registered callback functionThe application is responsible for connecting this function to the interrupt system. Application beyond this driver is also responsible for providing callbacks to handle interrupts during initialization phase. InstancePtr is a pointer to the core instance that just interrupted. None. None.
References XV_scenechange_InterruptGetStatus, XV_SCENECHANGE_CTRL_ADDR_ISR_AP_DONE, XV_scenechange_InterruptClear.
Referenced by XV_SceneChange_init.
void XV_scenechange_EnableInterrupts(void *InstancePtr)
Enable scene change interrupts.
This function enables the AP_DONE interrupt for the scene change core, allowing the interrupt handler to be triggered when processing completes. InstancePtr is a pointer to the XV_scenechange instance None None
References XV_scenechange_InterruptEnable, XV_SCENECHANGE_CTRL_ADDR_ISR_AP_DONE.
Referenced by XV_SceneChange_init.
void XV_scenechange_SetCallback(XV_scenechange *InstancePtr, void *CallbackFunc, void *CallbackRef)
This function installs an asynchronous callback function:
InstancePtr is a pointer to the SceneChange IP instance. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. None. Invoking this function for a handler that already has been installed replaces it with the new handler.
Referenced by XV_SceneChange_init.
int XV_scenechange_Layer_config(XV_scenechange *InstancePtr, u8 layerid)
Configure layer parameters for a specific stream.
This function validates and configures all layer parameters including width, height, stride, video format, subsample, and buffer address for the specified layer. It performs validation checks against IP capabilities. InstancePtr is a pointer to the XV_scenechange instance layerid is the layer identifier to configure (0-7) XST_SUCCESS if layer configuration is valid and completed XST_FAILURE if configuration parameters are invalid Validates layer ID, width, height, and video format compatibility
References XV_SCD_HAS_Y8, XV_SCD_HAS_Y10.
Referenced by XV_SceneChange_init.
void XV_scenechange_Layer_stream_enable(XV_scenechange *InstancePtr, u32 Data)
Enable specific streams for scene change detection.
This function enables one or more streams for scene change detection by writing the stream enable mask to the hardware register. InstancePtr is a pointer to the XV_scenechange instance streams is the bit mask of streams to enable (bit 0-7) None Each bit in the streams parameter corresponds to one stream
References XV_scenechange_Set_HwReg_stream_enable.
Referenced by XV_SceneChange_init.
u32 XV_scenechange_Stop(XV_scenechange *InstancePtr)
Stop the scene change core instance.
This function stops the core by disabling interrupts, auto-restart, and initiating a flush operation. For memory-based IP, it waits for the flush to complete before returning. InstancePtr is a pointer to the XV_scenechange instance XST_SUCCESS if the core is stopped and flush completed XST_FAILURE if flush operation timed out For memory-based IP, this function waits up to the flush timeout period
References XV_scenechange_InterruptGlobalDisable, XV_scenechange_InterruptDisable, XV_SCENECHANGE_CTRL_ADDR_ISR_AP_DONE, XV_scenechange_DisableAutoRestart, XV_SCD_WAIT_FOR_FLUSH_DELAY, XV_SCD_WAIT_FOR_FLUSH_DONE.
Referenced by main.
u32 XV_scenechange_WaitForIdle(XV_scenechange *InstancePtr)
Wait for the core to reach idle state.
This function polls the core idle status until the core becomes idle or the timeout period is reached. InstancePtr is a pointer to the XV_scenechange instance XST_SUCCESS if the core reached idle state XST_FAILURE if the core did not reach idle within timeout period Timeout is defined by XV_SCD_IDLE_TIMEOUT constant
References XV_scenechange_IsIdle, XV_SCD_IDLE_TIMEOUT.
Referenced by main.