dfeprach
XDfePrach_StateId
Not ready state.
typedef __u32 u32
typedef __u16 u16
typedef __u8 u8
typedef __s32 s32
typedef __s16 s16
typedef __u64 u64
typedef __s64 s64
typedef __s8 s8
typedef enum XDfePrach_StateId XDfePrach_StateId
typedef XDfePrach_StatusMask XDfePrach_InterruptMask
XDfePrach * XDfePrach_InstanceInit(const char *DeviceNodeName)
Initialises an instance of the driver.
Traverse "/sys/bus/platform/device" directory (in Linux), to find registered PRACH device with the name DeviceNodeName. The first available slot in the instance array XDfePrach_Prach[] will be taken as a DeviceNodeName object. On success it moves the state machine to a Ready state, while on failure stays in a Not Ready state. DeviceNodeName Device node name. Pointer to the instance if successful.NULL on error.
References XDfePrach::Device, XDfePrach::NodeName, XDfePrach::StateId, XDFEPRACH_NODE_NAME_MAX_LENGTH, XDFEPRACH_RC_NUM_MAX, XDFEPRACH_STATE_NOT_READY, XDFEPRACH_STATE_READY, XST_FAILURE, XST_SUCCESS.
Referenced by XDfePrach_2CC3RCDynamicTestExample, XDfePrach_2CC3RCReconfigureTestExample, XDfePrach_2CC3RCTestExample, XDfePrach_SelfTestExample.
void XDfePrach_InstanceClose(XDfePrach *InstancePtr)
Closes the instance of a PRACH driver and moves the state machine to a Not Ready state.
InstancePtr Pointer to the PRACH instance.
References XDfePrach::Device, XDfePrach::NodeName, XDfePrach::StateId, XDFEPRACH_STATE_NOT_READY.
Referenced by XDfePrach_2CC3RCDynamicTestExample, XDfePrach_2CC3RCReconfigureTestExample, XDfePrach_2CC3RCTestExample, XDfePrach_SelfTestExample.
void XDfePrach_Reset(XDfePrach *InstancePtr)
Resets PRACH and moves the state machine into a reset state.
InstancePtr Pointer to the PRACH instance.
References XDfePrach::StateId, XDFEPRACH_STATE_NOT_READY, XDFEPRACH_STATE_RESET.
Referenced by XDfePrach_2CC3RCDynamicTestExample, XDfePrach_2CC3RCReconfigureTestExample, XDfePrach_2CC3RCTestExample, XDfePrach_SelfTestExample.
void XDfePrach_Configure(XDfePrach *InstancePtr, XDfePrach_Cfg *Cfg)
Reads configuration from device tree/xparameters.h and IP registers.
Removes S/W reset and moves the state machine to a Configured state. InstancePtr Pointer to the PRACH instance. Cfg Configuration data container.
References XDfePrach::Config, XDfePrach_ModelParameters::HasAxisCtrl, XDfePrach_Config::HasAxisCtrl, XDfePrach_ModelParameters::HasContinuousSched, XDfePrach_Config::HasContinuousSched, XDfePrach_ModelParameters::HasIrq, XDfePrach_Config::HasIrq, XDfePrach_Version::Major, XDfePrach_Version::Minor, XDfePrach_Cfg::ModelParams, XDfePrach_ModelParameters::NumAntenna, XDfePrach_Config::NumAntenna, XDfePrach_ModelParameters::NumAntennaChannels, XDfePrach_Config::NumAntennaChannels, XDfePrach_ModelParameters::NumAntennaSlots, XDfePrach_Config::NumAntennaSlots, XDfePrach_ModelParameters::NumBands, XDfePrach_Config::NumBands, XDfePrach_ModelParameters::NumCCPerAntenna, XDfePrach_Config::NumCCPerAntenna, XDfePrach_ModelParameters::NumRachChannels, XDfePrach_Config::NumRachChannels, XDfePrach_ModelParameters::NumRachLanes, XDfePrach_Config::NumRachLanes, XDfePrach_Version::Patch, XDfePrach_Version::Revision, XDfePrach::StateId, XDfePrach_Cfg::Version, XDFEPRACH_STATE_CONFIGURED, XDFEPRACH_STATE_RESET.
Referenced by XDfePrach_2CC3RCDynamicTestExample, XDfePrach_2CC3RCReconfigureTestExample, XDfePrach_2CC3RCTestExample, XDfePrach_SelfTestExample.
void XDfePrach_Initialize(XDfePrach *InstancePtr, XDfePrach_Init *Init)
DFE PRACH driver one time initialisation also moves the state machine to an Initialised state.
InstancePtr Pointer to the PRACH instance. Init Initialisation data container.
References XDfePrach::Config, XDfePrach_Init::EnableStaticSchedule, XDfePrach_CCSequence::Length, XDfePrach::NotUsedCCID, XDfePrach_Config::NumBands, XDfePrach_Init::Sequence, XDfePrach::SequenceLength, XDfePrach::StateId, XDFEPRACH_STATE_CONFIGURED, XDFEPRACH_STATE_INITIALISED.
Referenced by XDfePrach_2CC3RCDynamicTestExample, XDfePrach_2CC3RCReconfigureTestExample, XDfePrach_2CC3RCTestExample, XDfePrach_SelfTestExample.
void XDfePrach_Activate(XDfePrach *InstancePtr, bool EnableLowPower)
Activates PRACH and moves the state machine to an Activated state.
InstancePtr Pointer to the PRACH instance. EnableLowPower Flag indicating low power.
References XDfePrach::StateId, XDFEPRACH_STATE_INITIALISED, XDFEPRACH_STATE_OPERATIONAL.
Referenced by XDfePrach_2CC3RCDynamicTestExample, XDfePrach_2CC3RCReconfigureTestExample, XDfePrach_2CC3RCTestExample, XDfePrach_SelfTestExample.
void XDfePrach_Deactivate(XDfePrach *InstancePtr)
Deactivates PRACH and moves the state machine to Initialised state.
InstancePtr Pointer to the PRACH instance.
References XDfePrach::StateId, XDFEPRACH_STATE_INITIALISED, XDFEPRACH_STATE_OPERATIONAL.
Referenced by XDfePrach_2CC3RCDynamicTestExample, XDfePrach_2CC3RCReconfigureTestExample, XDfePrach_2CC3RCTestExample, XDfePrach_SelfTestExample.
XDfePrach_StateId XDfePrach_GetStateID(XDfePrach *InstancePtr)
Returns the state machine state id.
InstancePtr Pointer to the PRACH instance. State machine StateID
References XDfePrach::StateId.
void XDfePrach_GetCurrentCCCfg(const XDfePrach *InstancePtr, XDfePrach_CCCfg *CurrCCCfg)
Returns the current CC configuration.
InstancePtr Pointer to the PRACH instance. CurrCCCfg CC configuration container.
References XDfePrach::Config, XDfePrach_Config::NumBands.
void XDfePrach_GetEmptyCCCfg(const XDfePrach *InstancePtr, XDfePrach_CCCfg *CCCfg)
Returns configuration structure CCCfg with CCCfg->Sequence.Length value set in XDfePrach_Configure(), array CCCfg->Sequence.CCID[] members are set to not used value (-1) and the other CCCfg members are set to 0.
InstancePtr Pointer to the PRACH instance. CCCfg CC configuration container.
References XDfePrach_CCSequence::CCID, XDfePrach::Config, XDfePrach_CCSequence::Length, XDfePrach_Config::NumBands, XDfePrach_CCCfg::Sequence, XDfePrach::SequenceLength, XDFEPRACH_CC_NUM_MAX.
Referenced by XDfePrach_2CC3RCDynamicTestExample, XDfePrach_2CC3RCReconfigureTestExample, XDfePrach_2CC3RCTestExample.
void XDfePrach_GetCarrierCfgMB(const XDfePrach *InstancePtr, XDfePrach_CCCfg *CCCfg, s32 CCID, u32 *CCSeqBitmap, XDfePrach_CarrierCfg *CarrierCfg, const u32 BandId)
Returns the current CC configuration of a specific CCID from a selected band in multi band mode.
InstancePtr Pointer to the PRACH instance. CCCfg Component carrier (CC) configuration container. CCID CC ID [0-15]. CCSeqBitmap CC slot position container. CarrierCfg CC configuration container. BandId Band Id.
References XDfePrach_CCCfg::CarrierCfg, XDfePrach_CCSequence::CCID, XDfePrach_CCSequence::Length, XDfePrach_InternalCarrierCfg::SCS, XDfePrach_CarrierCfg::SCS, XDfePrach_CCCfg::Sequence.
Referenced by XDfePrach_GetCarrierCfg.
void XDfePrach_GetCarrierCfg(const XDfePrach *InstancePtr, XDfePrach_CCCfg *CCCfg, s32 CCID, u32 *CCSeqBitmap, XDfePrach_CarrierCfg *CarrierCfg)
Returns the current CC configuration of a specific CCID in single band mode or from band 0 in multi band mode.
InstancePtr Pointer to the PRACH instance. CCCfg Component carrier (CC) configuration container. CCID CC ID [0-15]. CCSeqBitmap CC slot position container. CarrierCfg CC configuration container.
References XDfePrach_GetCarrierCfgMB.
u32 XDfePrach_AddCCtoCCCfgMB(XDfePrach *InstancePtr, XDfePrach_CCCfg *CCCfg, s32 CCID, u32 CCSeqBitmap, const XDfePrach_CarrierCfg *CarrierCfg, const u32 BandId)
Adds specified CCID, with specified configuration, to a local CC configuration structure for the chosen band in multi band mode.
If there is insufficient capacity for the new CC the function will return an error.The returned CCCfg->Sequence must be translated because there is no explicit indication that a slot is unused. A zero value in the register can indicate either a slot with ID = 0 or an unused slot.Therefore, the sequence data returned in CCCfg->Sequence is not identical to what is written in the registers. The translation is as follows: Sequence.CCID[i] = -1 - if [i] is unused slotSequence.CCID[i] = CCID - if [i] is used slota returned Sequence.Length = length in register + 1 InstancePtr Pointer to the PRACH instance. CCCfg Component carrier (CC) configuration container. CCID CC ID [0-15]. CCSeqBitmap CC slot position container. CarrierCfg CC configuration container. BandId Band Id. XST_SUCCESS if successful.XST_FAILURE if error occurs.
References XDfePrach_CCCfg::CarrierCfg, XDfePrach_InternalCarrierCfg::CCRate, XDfePrach_InternalCarrierCfg::Enable, XDfePrach_InternalCarrierCfg::SCS, XDfePrach_CarrierCfg::SCS, XDfePrach_CCCfg::Sequence, XDfePrach::StateId, XDFEPRACH_STATE_OPERATIONAL, XST_FAILURE, XST_SUCCESS.
Referenced by XDfePrach_AddCCtoCCCfg.
u32 XDfePrach_AddCCtoCCCfg(XDfePrach *InstancePtr, XDfePrach_CCCfg *CCCfg, s32 CCID, u32 CCSeqBitmap, const XDfePrach_CarrierCfg *CarrierCfg)
Adds specified CCID, with specified configuration, to a local CC configuration structure for single band mode or on Band 0 for multi band mode.
If there is insufficient capacity for the new CC the function will return an error.The returned CCCfg->Sequence must be translated because there is no explicit indication that a slot is unused. A zero value in the register can indicate either a slot with ID = 0 or an unused slot.Therefore, the sequence data returned in CCCfg->Sequence is not identical to what is written in the registers. The translation is as follows: Sequence.CCID[i] = -1 - if [i] is unused slotSequence.CCID[i] = CCID - if [i] is used slota returned Sequence.Length = length in register + 1 InstancePtr Pointer to the PRACH instance. CCCfg Component carrier (CC) configuration container. CCID CC ID [0-15]. CCSeqBitmap CC slot position container. CarrierCfg CC configuration container. XST_SUCCESS if successful.XST_FAILURE if error occurs.
References XDfePrach::StateId, XDfePrach_AddCCtoCCCfgMB, XDFEPRACH_STATE_OPERATIONAL.
Referenced by XDfePrach_2CC3RCDynamicTestExample, XDfePrach_2CC3RCReconfigureTestExample, XDfePrach_2CC3RCTestExample.
u32 XDfePrach_RemoveCCfromCCCfgMB(XDfePrach *InstancePtr, XDfePrach_CCCfg *CCCfg, s32 CCID, const u32 BandId)
Removes specified CCID from a local CC configuration structure for selected band in multi band mode.
InstancePtr Pointer to the PRACH instance. CCCfg Component carrier (CC) configuration container. CCID CC ID [0-15]. BandId Band Id. XST_SUCCESS if successful.XST_FAILURE if error occurs. For sequence conversion see XDfePrach_AddCCtoCCCfg() comment.
References XDfePrach_CCCfg::CarrierCfg, XDfePrach_InternalCarrierCfg::Enable, XDfePrach_CCCfg::Sequence, XST_SUCCESS.
Referenced by XDfePrach_RemoveCCfromCCCfg.
u32 XDfePrach_RemoveCCfromCCCfg(XDfePrach *InstancePtr, XDfePrach_CCCfg *CCCfg, s32 CCID)
Removes specified CCID from a local CC configuration structure in single band mode or for Band 0 in multi band mode.
InstancePtr Pointer to the PRACH instance. CCCfg Component carrier (CC) configuration container. CCID CC ID [0-15]. XST_SUCCESS if successful.XST_FAILURE if error occurs. For sequence conversion see XDfePrach_AddCCtoCCCfg() comment.
References XDfePrach_RemoveCCfromCCCfgMB.
u32 XDfePrach_UpdateCCinCCCfgMB(const XDfePrach *InstancePtr, XDfePrach_CCCfg *CCCfg, s32 CCID, const XDfePrach_CarrierCfg *CarrierCfg, const u32 BandId)
Updates specified CCID, with specified configuration to a local CC configuration structure for selected band in multi band mode.
InstancePtr Pointer to the PRACH instance. CCCfg Component carrier (CC) configuration container. CCID CC ID [0-15]. CarrierCfg CC configuration container. BandId Band Id. XST_SUCCESS if successful.XST_FAILURE if error occurs.
References XDfePrach_CCCfg::CarrierCfg, XDfePrach_InternalCarrierCfg::SCS, XDfePrach_CarrierCfg::SCS, XST_SUCCESS.
Referenced by XDfePrach_UpdateCCinCCCfg.
u32 XDfePrach_UpdateCCinCCCfg(const XDfePrach *InstancePtr, XDfePrach_CCCfg *CCCfg, s32 CCID, const XDfePrach_CarrierCfg *CarrierCfg)
Updates specified CCID, with specified configuration to a local CC configuration structure in single band mode or for Band 0 in multi band mode.
InstancePtr Pointer to the PRACH instance. CCCfg Component carrier (CC) configuration container. CCID CC ID [0-15]. CarrierCfg CC configuration container. XST_SUCCESS if successful.XST_FAILURE if error occurs.
References XDfePrach_UpdateCCinCCCfgMB.
u32 XDfePrach_SetNextCfg(const XDfePrach *InstancePtr, const XDfePrach_CCCfg *NextCCCfg, XDfePrach_RCCfg *NextRCCfg)
Writes local CC configuration to the shadow (NEXT) registers and triggers copying from shadow to operational registers.
InstancePtr Pointer to the PRACH instance. NextCCCfg CC configuration container. NextRCCfg RC configuration container. XST_SUCCESS if successful.XST_FAILURE if error occurs.
References XDfePrach::Config, XDfePrach_Config::NumBands, XDFEPRACH_RC_NUM_MAX, XST_FAILURE, XST_SUCCESS.
Referenced by XDfePrach_2CC3RCDynamicTestExample, XDfePrach_2CC3RCReconfigureTestExample, XDfePrach_2CC3RCTestExample.
void XDfePrach_GetCurrentRCCfg(const XDfePrach *InstancePtr, XDfePrach_RCCfg *RCCfg)
Returns the current RACH Channel configuration.
InstancePtr Pointer to the PRACH instance. RCCfg RC configuration container.
References XDFEPRACH_RC_NUM_MAX.
void XDfePrach_GetEmptyRCCfg(const XDfePrach *InstancePtr, XDfePrach_RCCfg *RCCfg)
Returns an empty Rach channel configuration.
InstancePtr Pointer to the PRACH instance. RCCfg RC configuration container.
Referenced by XDfePrach_2CC3RCDynamicTestExample, XDfePrach_2CC3RCReconfigureTestExample, XDfePrach_2CC3RCTestExample.
void XDfePrach_GetChannelCfg(const XDfePrach *InstancePtr, XDfePrach_RCCfg *RCCfg, s32 RCId, XDfePrach_ChannelCfg *ChannelCfg)
Returns RACH channel configuration for a specific RCId.
InstancePtr Pointer to the PRACH instance. RCCfg RC configuration container. RCId Chosen RACH channel Id [0-15]. ChannelCfg RACH channel container.
References XDfePrach_ChannelCfg::BandId, XDfePrach_ChannelCfg::CCID, XDfePrach_ChannelCfg::RachChannel, XDfePrach_ChannelCfg::RCId.
u32 XDfePrach_AddRCtoRCCfgMB(const XDfePrach *InstancePtr, XDfePrach_RCCfg *CurrentRCCfg, s32 CCID, u32 RCId, u32 RachChan, XDfePrach_DDCCfg *DdcCfg, XDfePrach_NCO *NcoCfg, XDfePrach_Schedule *StaticSchedule, XDfePrach_CCCfg *NextCCCfg, u32 BandId)
Adds a new RC entry to the RACH Channel configuration for multi band mode.
InstancePtr Pointer to the PRACH instance. CurrentRCCfg Current RACH configuration container. CCID CC ID [0-15]. RCId RC Id [0-15]. RachChan RACH channel [0-15]. DdcCfg DDC data container. NcoCfg NCO data container. StaticSchedule Schedule data container. Unused if operating in "Always On" mode, where internal scheduler is removed at core generation. NextCCCfg CC configuration container. BandId Band id. XST_SUCCESS on successXST_FAILURE on failure This API must be executed only after all CC configurations are done with the API XDfePrach_AddCCtoCCCfg.
References XDfePrach::Config, XDfePrach_Config::NumBands, XDfePrach::StateId, XDFEPRACH_RC_NUM_MAX, XDFEPRACH_STATE_OPERATIONAL, XST_FAILURE, XST_SUCCESS.
Referenced by XDfePrach_AddRCtoRCCfg.
u32 XDfePrach_AddRCtoRCCfgMBDynamic(const XDfePrach *InstancePtr, XDfePrach_RCCfg *CurrentRCCfg, s32 CCID, u32 RCId, u32 RachChan, XDfePrach_CCCfg *NextCCCfg, u32 BandId)
Adds a new RC entry to the RACH Channel configuration for multi band mode in dynamic mode.
InstancePtr Pointer to the PRACH instance. CurrentRCCfg Current RACH configuration container. CCID CC ID [0-15]. RCId RC Id [0-15]. RachChan RACH channel [0-15]. NextCCCfg CC configuration container. BandId Band id. XST_SUCCESS on successXST_FAILURE on failure This API must be executed only after all CC configurations are done with the API XDfePrach_AddCCtoCCCfg.
References XDfePrach::Config, XDfePrach_Config::HasAxisCtrl, XDfePrach_Config::NumBands, XDfePrach::StateId, XDFEPRACH_RC_NUM_MAX, XDFEPRACH_STATE_OPERATIONAL, XST_FAILURE, XST_SUCCESS.
Referenced by XDfePrach_AddRCtoRCCfgDynamic.
u32 XDfePrach_AddRCtoRCCfg(const XDfePrach *InstancePtr, XDfePrach_RCCfg *CurrentRCCfg, s32 CCID, u32 RCId, u32 RachChan, XDfePrach_DDCCfg *DdcCfg, XDfePrach_NCO *NcoCfg, XDfePrach_Schedule *StaticSchedule, XDfePrach_CCCfg *NextCCCfg)
Adds a new RC entry to the RACH Channel configuration.
Must be used when the core is configured with a single band. It can be used to add an RC which captures from a CC in band 0 in multi band mode. InstancePtr Pointer to the PRACH instance. CurrentRCCfg Current RACH configuration container. CCID CC ID [0-15]. RCId RC Id [0-15]. RachChan RACH channel [0-15]. DdcCfg DDC data container. NcoCfg NCO data container. StaticSchedule Schedule Data Container. Not required and can be ignored for "Always On" mode, where the internal scheduler is removed at core configuration. NextCCCfg CC configuration container. XST_SUCCESS on successXST_FAILURE on failure This API must be executed only after all CC configurations are done with the API XDfePrach_AddCCtoCCCfg.
References XDfePrach::StateId, XDfePrach_AddRCtoRCCfgMB, XDFEPRACH_RC_NUM_MAX, XDFEPRACH_STATE_OPERATIONAL.
Referenced by XDfePrach_2CC3RCDynamicTestExample, XDfePrach_2CC3RCReconfigureTestExample, XDfePrach_2CC3RCTestExample.
u32 XDfePrach_AddRCtoRCCfgDynamic(const XDfePrach *InstancePtr, XDfePrach_RCCfg *CurrentRCCfg, s32 CCID, u32 RCId, u32 RachChan, XDfePrach_CCCfg *NextCCCfg)
Adds a new RC entry to the RACH Channel configuration in dynamic mode.
Must be used when the core is configured with a single band. It can be used to add an RC which captures from a CC in band 0 in multi band mode. InstancePtr Pointer to the PRACH instance. CurrentRCCfg Current RACH configuration container. CCID CC ID [0-15]. RCId RC Id [0-15]. RachChan RACH channel [0-15]. NextCCCfg CC configuration container. XST_SUCCESS on successXST_FAILURE on failure This API must be executed only after all CC configurations are done with the API XDfePrach_AddCCtoCCCfg.
References XDfePrach::Config, XDfePrach_Config::HasAxisCtrl, XDfePrach::StateId, XDfePrach_AddRCtoRCCfgMBDynamic, XDFEPRACH_RC_NUM_MAX, XDFEPRACH_STATE_OPERATIONAL.
u32 XDfePrach_RemoveRCfromRCCfg(const XDfePrach *InstancePtr, XDfePrach_RCCfg *CurrentRCCfg, u32 RCId)
Removes an RC configuration entry from the RACH Channel configuration.
InstancePtr Pointer to the PRACH instance. CurrentRCCfg Current RACH configuration container. RCId RC Id [0-15]. XST_SUCCESS on successXST_FAILURE on failure
References XDfePrach::StateId, XDFEPRACH_RC_NUM_MAX, XDFEPRACH_STATE_OPERATIONAL, XST_SUCCESS.
Referenced by XDfePrach_2CC3RCReconfigureTestExample.
void XDfePrach_UpdateRCinRCCfgMB(const XDfePrach *InstancePtr, XDfePrach_RCCfg *CurrentRCCfg, s32 CCID, u32 RCId, u32 RachChan, XDfePrach_DDCCfg *DdcCfg, XDfePrach_NCO *NcoCfg, XDfePrach_Schedule *StaticSchedule, XDfePrach_CCCfg *NextCCCfg, u32 BandId)
Updates an RC entry to the RACH Channel configuration in multi band mode (RC entry updated for an RCId associated with PRACH extraction on a CC of a specific band).
InstancePtr Pointer to the PRACH instance. CurrentRCCfg Current RACH configuration container. CCID CC Id [0-15]. RCId RC Id [0-15]. RachChan RACH channel [0-15]. DdcCfg DDC data container. NcoCfg NCO data container. StaticSchedule Schedule data container. NextCCCfg CC configuration container. BandId Band id. This API must be executed only after all CC configurations are done with the API XDfePrach_AddCCtoCCCfg and XDfePrach_UpdateCCinCCCfg.
References XDfePrach::StateId, XDFEPRACH_RC_NUM_MAX, XDFEPRACH_STATE_OPERATIONAL.
Referenced by XDfePrach_UpdateRCinRCCfg.
void XDfePrach_UpdateRCinRCCfg(const XDfePrach *InstancePtr, XDfePrach_RCCfg *CurrentRCCfg, s32 CCID, u32 RCId, u32 RachChan, XDfePrach_DDCCfg *DdcCfg, XDfePrach_NCO *NcoCfg, XDfePrach_Schedule *StaticSchedule, XDfePrach_CCCfg *NextCCCfg)
Updates an RC entry to the RACH Channel configuration in single band mode (can also be used to update the RC entry of an RCId associated with PRACH extraction on a CC of band 0 in multi band mode).
InstancePtr Pointer to the PRACH instance. CurrentRCCfg Current RACH configuration container. CCID CC Id [0-15]. RCId RC Id [0-15]. RachChan RACH channel [0-15]. DdcCfg DDC data container. NcoCfg NCO data container. StaticSchedule Schedule data container. NextCCCfg CC configuration container. This API must be executed only after all CC configurations are done with the API XDfePrach_AddCCtoCCCfg and XDfePrach_UpdateCCinCCCfg.
References XDfePrach::StateId, XDFEPRACH_RC_NUM_MAX, XDFEPRACH_STATE_OPERATIONAL, XDfePrach_UpdateRCinRCCfgMB.
void XDfePrach_GetTriggersCfg(const XDfePrach *InstancePtr, XDfePrach_TriggerCfg *TriggerCfg)
Returns the current trigger configuration.
InstancePtr Pointer to the PRACH instance. TriggerCfg Trigger configuration container.
References XDfePrach_TriggerCfg::Activate, XDfePrach::Config, XDfePrach_TriggerCfg::FrameInit, XDfePrach_TriggerCfg::LowPower, XDfePrach_Trigger::Mode, XDfePrach_Config::NumBands, XDfePrach_TriggerCfg::RachUpdate, XDfePrach::StateId, XDfePrach_Trigger::StateOutput, XDfePrach_Trigger::TriggerEnable, XDfePrach_Trigger::TUSERBit, XDfePrach_Trigger::TuserEdgeLevel, XDFEPRACH_STATE_NOT_READY.
void XDfePrach_SetTriggersCfg(const XDfePrach *InstancePtr, XDfePrach_TriggerCfg *TriggerCfg)
Sets trigger configuration.
InstancePtr Pointer to the PRACH instance. TriggerCfg Trigger configuration container.
References XDfePrach_TriggerCfg::Activate, XDfePrach::Config, XDfePrach_TriggerCfg::FrameInit, XDfePrach_TriggerCfg::LowPower, XDfePrach_Trigger::Mode, XDfePrach_Config::NumBands, XDfePrach_TriggerCfg::RachUpdate, XDfePrach::StateId, XDfePrach_Trigger::StateOutput, XDfePrach_Trigger::TriggerEnable, XDfePrach_Trigger::TUSERBit, XDfePrach_Trigger::TuserEdgeLevel, XDFEPRACH_STATE_INITIALISED.
Referenced by XDfePrach_2CC3RCDynamicTestExample, XDfePrach_2CC3RCReconfigureTestExample, XDfePrach_2CC3RCTestExample.
void XDfePrach_GetCC(const XDfePrach *InstancePtr, bool Next, s32 CCID, XDfePrach_CarrierCfg *CarrierCfg)
Gets the specified CCID carrier configuration from either Current or Next registers in single band mode or for band 0 in multi band mode.
InstancePtr Pointer to the PRACH instance. Next Boolean flag indicating NEXT(1) or CURRENT(0) register. CCID CC Id [0-15]. CarrierCfg Carrier configuration container.
References XDfePrach_GetCCMB.
void XDfePrach_GetCCMB(const XDfePrach *InstancePtr, bool Next, s32 CCID, XDfePrach_CarrierCfg *CarrierCfg, u32 BandId)
Gets the specified CCID carrier configuration from either Current or Next registers for a selected band in multi-band mode.
InstancePtr Pointer to the PRACH instance. Next Boolean flag indicating NEXT(1) or CURRENT(0) register. CCID CC Id [0-15]. CarrierCfg Carrier configuration container. BandId Band Id.
References XDfePrach_CarrierCfg::SCS.
Referenced by XDfePrach_GetCC.
void XDfePrach_GetStatus(const XDfePrach *InstancePtr, XDfePrach_Status *Status)
Returns the PRACH status registers.
InstancePtr Pointer to the PRACH instance. Status Status data container.
References XDfePrach_DecimatorStatusOverflow::DecimatorOverflow, XDfePrach_Status::DecimatorOverflow, XDfePrach_DecimatorStatusOverrun::DecimatorOverrun, XDfePrach_Status::DecimatorOverrun, XDfePrach_MixerStatusOverflow::FirstAntennaOverflowing, XDfePrach_DecimatorStatusOverflow::FirstAntennaOverflowing, XDfePrach_MixerStatusOverrun::FirstAntennaOverruning, XDfePrach_DecimatorStatusOverrun::FirstAntennaOverruning, XDfePrach_MixerStatusOverflow::FirstRCIdOverflowing, XDfePrach_DecimatorStatusOverflow::FirstRCIdOverflowing, XDfePrach_MixerStatusOverrun::FirstRCIdOverruning, XDfePrach_DecimatorStatusOverrun::FirstRCIdOverruning, XDfePrach_MixerStatusOverflow::MixerOverflow, XDfePrach_Status::MixerOverflow, XDfePrach_MixerStatusOverrun::MixerOverrun, XDfePrach_Status::MixerOverrun, XDfePrach::StateId, XDFEPRACH_STATE_OPERATIONAL.
void XDfePrach_ClearStatus(const XDfePrach *InstancePtr)
Clears the PRACH status registers.
InstancePtr Pointer to the PRACH instance.
References XDfePrach::StateId, XDfePrach_ClearEventStatus, XDFEPRACH_STATE_OPERATIONAL.
void XDfePrach_CapturePhase(const XDfePrach *InstancePtr)
Captures phase for the phase accumulator output of all RACH channels in associated AXI-lite registers.
InstancePtr Pointer to the PRACH instance.
void XDfePrach_GetCapturePhase(const XDfePrach *InstancePtr, u32 RachChan, XDfePrach_NCO *CapturedPhase)
Returns the captured phase accumulator output for a given Rach Channel.
InstancePtr Pointer to the PRACH instance. RachChan RACH channel Id [0-15]. CapturedPhase NCO data container.
References XDfePrach_NCO::DualModCount, XDfePrach_NCO::DualModSel, XDfePrach_NCO::PhaseAcc, XDFEPRACH_RC_NUM_MAX.
void XDfePrach_SetTUserDelay(const XDfePrach *InstancePtr, u32 Delay)
Sets the delay, which is added to TUSER and TLAST (delay matched through the IP) in single band mode or for band 0 in multi band mode.
InstancePtr Pointer to the PRACH instance. Delay Requested delay variable.
References XDfePrach::StateId, XDFEPRACH_STATE_INITIALISED.
void XDfePrach_SetTUserDelayMB(const XDfePrach *InstancePtr, u32 Delay, u32 BandId)
Sets the delay of specified band in multi band mode, which is added to TUSER and TLAST (delay matched through the IP).
InstancePtr Pointer to the PRACH instance. Delay Requested delay variable. BandId Band Id.
References XDfePrach::StateId, XDFEPRACH_STATE_INITIALISED.
u32 XDfePrach_GetTUserDelay(const XDfePrach *InstancePtr)
Returns the delay, which is added to TUSER and TLAST (delay matched through the IP) in single band mode or for band 0 in multi band mode.
InstancePtr Pointer to the PRACH instance. Delay value
u32 XDfePrach_GetTUserDelayMB(const XDfePrach *InstancePtr, u32 BandId)
Returns the delay of specified band in multi band mode, which is added to TUSER and TLAST (delay matched through the IP).
InstancePtr Pointer to the PRACH instance. BandId Band Id. Delay value
u32 XDfePrach_GetTDataDelay(const XDfePrach *InstancePtr)
Returns data latency in single band mode or for band 0 in multi-band mode.
InstancePtr Pointer to the PRACH instance in single band mode or for band 0 in multi-band mode. Data latency value.
u32 XDfePrach_GetTDataDelayMB(const XDfePrach *InstancePtr, u32 BandId)
Returns data latency of specified band in multi band mode.
InstancePtr Pointer to the PRACH instance. BandId Band Id. Data latency value.
void XDfePrach_GetVersions(const XDfePrach *InstancePtr, XDfePrach_Version *SwVersion, XDfePrach_Version *HwVersion)
Returns the driver and HW design version.
InstancePtr Pointer to the PRACH instance. SwVersion Driver version number. HwVersion HW version number.
References XDfePrach_Version::Major, XDfePrach_Version::Minor, XDfePrach_Version::Patch, XDfePrach_Version::Revision, XDfePrach::StateId, XDFEPRACH_DRIVER_VERSION_MAJOR, XDFEPRACH_DRIVER_VERSION_MINOR, XDFEPRACH_STATE_NOT_READY.
Referenced by XDfePrach_2CC3RCDynamicTestExample, XDfePrach_2CC3RCReconfigureTestExample, XDfePrach_2CC3RCTestExample, XDfePrach_SelfTestExample.
void XDfePrach_GetInterruptMask(const XDfePrach *InstancePtr, XDfePrach_InterruptMask *Mask)
Returns interrupt mask status.
InstancePtr Pointer to the PRACH instance. Mask Interrupt masks container.
References XDfePrach_StatusMask::CCSequenceError, XDfePrach_StatusMask::DecimatorOverflow, XDfePrach_StatusMask::DecimatorOverrun, XDfePrach_StatusMask::FrameError, XDfePrach_StatusMask::FrameInitTrigger, XDfePrach_StatusMask::MixerOverflow, XDfePrach_StatusMask::RachUpdate, XDfePrach_StatusMask::SelectorOverrun, XDFEPRACH_BAND_ID_MAX.
void XDfePrach_SetInterruptMask(const XDfePrach *InstancePtr, const XDfePrach_InterruptMask *Mask)
Sets the interrupt mask.
InstancePtr Pointer to the PRACH instance. Mask Interrupt mask flags container. 0 - does not mask corresponding interrupt1 - masks corresponding interrupt
References XDfePrach_StatusMask::CCSequenceError, XDfePrach_StatusMask::DecimatorOverflow, XDfePrach_StatusMask::DecimatorOverrun, XDfePrach_StatusMask::FrameError, XDfePrach_StatusMask::FrameInitTrigger, XDfePrach_StatusMask::MixerOverflow, XDfePrach_StatusMask::RachUpdate, XDfePrach_StatusMask::SelectorOverrun, XDFEPRACH_BAND_ID_MAX.
void XDfePrach_GetEventStatus(const XDfePrach *InstancePtr, XDfePrach_StatusMask *Status)
Returns the event status.
InstancePtr Pointer to the PRACH instance. Status Event status container.
References XDfePrach_StatusMask::CCSequenceError, XDfePrach_StatusMask::DecimatorOverflow, XDfePrach_StatusMask::DecimatorOverrun, XDfePrach_StatusMask::FrameError, XDfePrach_StatusMask::FrameInitTrigger, XDfePrach_StatusMask::MixerOverflow, XDfePrach_StatusMask::RachUpdate, XDfePrach_StatusMask::SelectorOverrun, XDFEPRACH_BAND_ID_MAX.
void XDfePrach_ClearEventStatus(const XDfePrach *InstancePtr, const XDfePrach_StatusMask *Status)
Clears the event status.
InstancePtr Pointer to the PRACH instance. Status Clear event status container. 0 - does not clear corresponding event status1 - clear corresponding event status
References XDfePrach_StatusMask::CCSequenceError, XDfePrach_StatusMask::DecimatorOverflow, XDfePrach_StatusMask::DecimatorOverrun, XDfePrach_StatusMask::FrameError, XDfePrach_StatusMask::FrameInitTrigger, XDfePrach_StatusMask::MixerOverflow, XDfePrach_StatusMask::RachUpdate, XDfePrach_StatusMask::SelectorOverrun, XDFEPRACH_BAND_ID_MAX.
Referenced by XDfePrach_2CC3RCDynamicTestExample, XDfePrach_2CC3RCReconfigureTestExample, XDfePrach_2CC3RCTestExample, XDfePrach_ClearStatus.
XDFEPRACH_DRIVER_VERSION_MINOR
Driver's minor version number.
Referenced by XDfePrach_GetVersions.
XDFEPRACH_DRIVER_VERSION_MAJOR
Driver's major version number.
Referenced by XDfePrach_GetVersions.
XDFEPRACH_PHASE_INCREMENT_PER_HZ
30720000 is the base sample rate
XDFEPRACH_ERROR_MARGIN
Error margin in frequency calculation.
XDFEPRACH_FREQ_MIN
Minimum frequency value.
XDFEPRACH_FREQ_MAX
Maximum frequency value.
XDFEPRACH_MAX_CCRATE
Maximum CC sample rate value (245.76Ms/s)
XDFEPRACH_MAX_NUM_INSTANCES
Maximum number of driver instances running at the same time.
XST_SUCCESS
Success flag.
Referenced by main, XDfePrach_2CC3RCDynamicTestExample, XDfePrach_2CC3RCReconfigureTestExample, XDfePrach_2CC3RCTestExample, XDfePrach_AddCCtoCCCfgMB, XDfePrach_AddRCtoRCCfgMB, XDfePrach_AddRCtoRCCfgMBDynamic, XDfePrach_InstanceInit, XDfePrach_RemoveCCfromCCCfgMB, XDfePrach_RemoveRCfromRCCfg, XDfePrach_SelfTestExample, XDfePrach_SetNextCfg, XDfePrach_UpdateCCinCCCfgMB, XDfeSi570_SetMgtOscillator.
XST_FAILURE
Failure flag.
Referenced by main, XDfePrach_2CC3RCDynamicTestExample, XDfePrach_2CC3RCReconfigureTestExample, XDfePrach_2CC3RCTestExample, XDfePrach_AddCCtoCCCfgMB, XDfePrach_AddRCtoRCCfgMB, XDfePrach_AddRCtoRCCfgMBDynamic, XDfePrach_InstanceInit, XDfePrach_SelfTestExample, XDfePrach_SetNextCfg, XDfeSi570_SetMgtOscillator.
XDFEPRACH_NODE_NAME_MAX_LENGTH
Node name maximum length.
Referenced by XDfePrach_InstanceInit.
XDFEPRACH_CC_NUM_MAX
Maximum CC number.
Referenced by XDfePrach_GetEmptyCCCfg.
XDFEPRACH_RC_NUM_MAX
Maximum number of RACH channels.
Referenced by XDfePrach_AddRCtoRCCfg, XDfePrach_AddRCtoRCCfgDynamic, XDfePrach_AddRCtoRCCfgMB, XDfePrach_AddRCtoRCCfgMBDynamic, XDfePrach_GetCapturePhase, XDfePrach_GetCurrentRCCfg, XDfePrach_InstanceInit, XDfePrach_RemoveRCfromRCCfg, XDfePrach_SetNextCfg, XDfePrach_UpdateRCinRCCfg, XDfePrach_UpdateRCinRCCfgMB.
XDFEPRACH_NCO_NUM_MAX
Maximum NCO number.
XDFEPRACH_ANT_NUM_MAX
Maximum anntena number.
XDFEPRACH_SEQ_LENGTH_MAX
Maximum CC sequence length.
XDFEPRACH_BAND_ID_MAX
Maximum number of bands.
Referenced by XDfePrach_ClearEventStatus, XDfePrach_GetEventStatus, XDfePrach_GetInterruptMask, XDfePrach_SetInterruptMask.
XDFEPRACH_COMPATIBLE_STRING
<
Device name property.
XDFEPRACH_PLATFORM_DEVICE_DIR
Device location in a file system.
XDFEPRACH_COMPATIBLE_PROPERTY
Device tree property.
XDFEPRACH_BUS_NAME
System bus name.
XDFEPRACH_BASEADDR_PROPERTY
Base address property.
XDFEPRACH_NUM_ANTENNA0_CFG
Number of antenna 1-8.
XDFEPRACH_NUM_ANTENNA1_CFG
Number of antenna 1-8.
XDFEPRACH_NUM_ANTENNA2_CFG
Number of antenna 1-8.
XDFEPRACH_NUM_CC_PER_ANTENNA0_CFG
Maximum number of CC's per antenna 16.
XDFEPRACH_NUM_CC_PER_ANTENNA1_CFG
Maximum number of CC's per antenna 16.
XDFEPRACH_NUM_CC_PER_ANTENNA2_CFG
Maximum number of CC's per antenna 16.
XDFEPRACH_NUM_SLOT_CHANNELS0_CFG
Number of Parallel Data Channels 1-4.
XDFEPRACH_NUM_SLOT_CHANNELS1_CFG
Number of Parallel Data Channels 1-4.
XDFEPRACH_NUM_SLOT_CHANNELS2_CFG
Number of Parallel Data Channels 1-4.
XDFEPRACH_NUM_SLOTS0_CFG
Number of Antenna TDM slots, per CC 1-8.
XDFEPRACH_NUM_SLOTS1_CFG
Number of Antenna TDM slots, per CC 1-8.
XDFEPRACH_NUM_SLOTS2_CFG
Number of Antenna TDM slots, per CC 1-8.
XDFEPRACH_NUM_RACH_LINES_CFG
Number of RACH output Lanes 1-2.
XDFEPRACH_NUM_RACH_CHANNELS_CFG
Number of RACH Channels channels 1-16.
XDFEPRACH_HAS_CONTINUOUS_SCHED_CFG
The continuous scheduling is present.
XDFEPRACH_HAS_AXIS_CTRL_CFG
The AXIS dynamic scheduling control interface is present.
XDFEPRACH_HAS_IRQ_CFG
The core has an IRQ port enabled.
XDFEPRACH_NUM_BANDS_CFG
Number of bands.