xdfeprach_examples.c
int XDfeSi570_SetMgtOscillator(double CurrentFrequency, double NewFrequency)
This function: initialize I2C bus, reads current state of si570, calculates parameters for si570 MGT oscillator new frequency, writes them to si570 and resets PL to use the new frequency.
CurrentFrequency MGT oscillator current frequency. NewFrequency MGT oscillator new frequency. None None
References XST_FAILURE, XST_SUCCESS.
Referenced by main.
int XDfePrach_SelfTestExample()
This example runs the DFE Prach device using the driver APIs.
The example goes through the following steps: Create and system initialize the device driver instance.Read SW and HW version numbers.Reset the device.Configure the device.Initialize the device.Activate the device.Deactivate the device. XST_SUCCESS if the example has completed successfully.XST_FAILURE if the example has failed.//! [testexample1]
References XST_SUCCESS, XST_FAILURE, XDfePrach_InstanceInit, XDfePrach_GetVersions, XDfePrach_Version::Major, XDfePrach_Version::Minor, XDfePrach_Version::Revision, XDfePrach_Version::Patch, XDfePrach_Reset, XDfePrach_Configure, XDfePrach_Initialize, XDfePrach_Activate, XDfePrach_Deactivate, XDfePrach_InstanceClose.
Referenced by main.
int XDfePrach_2CC3RCTestExample()
This example runs the DFE Prach device using the driver APIs.
The example goes through the following steps: Create and system initialize the device driver instance.Read SW and HW version numbers.Reset the device.Configure the device.Initialize the device.Activate the device.Get current Component Carrier (CC) configuration.Get current RACH Channel (RC) configuration.add 2 Component Carriers: CCID={5,3}add 3 RACH Channel: RCID={2,4,6}Trigger configuration update.Deactivate the device. XST_SUCCESS if the example has completed successfully.XST_FAILURE if the example has failed.//! [testexample2]
References XDfePrach_CarrierCfg::SCS, XDfePrach_DDCCfg::DecimationRate, XDfePrach_DDCCfg::UserSCS, XDfePrach_DDCCfg::RachGain, XDfePrach_NCO::UserFreq, XDfePrach_NCO::PhaseAcc, XDfePrach_NCO::NcoGain, XDfePrach_NCO::DualModCount, XDfePrach_NCO::DualModSel, XDfePrach_Schedule::PatternPeriod, XDfePrach_Schedule::FrameID, XDfePrach_Schedule::SubframeID, XDfePrach_Schedule::SlotId, XDfePrach_Schedule::Duration, XDfePrach_Schedule::Repeats, XST_SUCCESS, XST_FAILURE, XDfePrach_InstanceInit, XDfePrach_GetVersions, XDfePrach_Version::Major, XDfePrach_Version::Minor, XDfePrach_Version::Revision, XDfePrach_Version::Patch, XDfePrach_Reset, XDfePrach_Configure, XDfePrach_Init::Sequence, XDfePrach_CCSequence::Length, XDfePrach_Cfg::ModelParams, XDfePrach_ModelParameters::NumAntennaSlots, XDfePrach_Initialize, XDfePrach_TriggerCfg::Activate, XDfePrach_Trigger::TUSERBit, XDfePrach_Trigger::TuserEdgeLevel, XDfePrach_Trigger::StateOutput, XDfePrach_Trigger::Mode, XDfePrach_TriggerCfg::RachUpdate, XDfePrach_TriggerCfg::FrameInit, XDfePrach_SetTriggersCfg, XDfePrach_StatusMask::RachUpdate, XDfePrach_ClearEventStatus, XDfePrach_Activate, XDfePrach_GetEmptyCCCfg, XDfePrach_AddCCtoCCCfg, XDfePrach_GetEmptyRCCfg, XDfePrach_AddRCtoRCCfg, XDfePrach_SetNextCfg, XDfePrach_Deactivate, XDfePrach_InstanceClose.
Referenced by main.
int XDfePrach_2CC3RCReconfigureTestExample()
This example runs the DFE Prach device using the driver APIs.
The example goes through the following steps: Create and system initialize the device driver instance.Read SW and HW version numbers.Reset the device.Configure the device.Initialize the device.Activate the device.Get current Component Carrier (CC) configuration.Get current RACH Channel (RC) configuration.add 2 Component Carriers: CCID={5,3}add 3 RACH Channel: RCID={2,4,6}remove one RACH Channelconfigure and add new RACH channelTrigger configuration update.Deactivate the device. XST_SUCCESS if the example has completed successfully.XST_FAILURE if the example has failed.//! [testexample3]
References XDfePrach_CarrierCfg::SCS, XDfePrach_DDCCfg::DecimationRate, XDfePrach_DDCCfg::UserSCS, XDfePrach_DDCCfg::RachGain, XDfePrach_NCO::UserFreq, XDfePrach_NCO::PhaseAcc, XDfePrach_NCO::NcoGain, XDfePrach_NCO::DualModCount, XDfePrach_NCO::DualModSel, XDfePrach_Schedule::PatternPeriod, XDfePrach_Schedule::FrameID, XDfePrach_Schedule::SubframeID, XDfePrach_Schedule::SlotId, XDfePrach_Schedule::Duration, XDfePrach_Schedule::Repeats, XST_SUCCESS, XST_FAILURE, XDfePrach_InstanceInit, XDfePrach_GetVersions, XDfePrach_Version::Major, XDfePrach_Version::Minor, XDfePrach_Version::Revision, XDfePrach_Version::Patch, XDfePrach_Reset, XDfePrach_Configure, XDfePrach_Init::Sequence, XDfePrach_CCSequence::Length, XDfePrach_Cfg::ModelParams, XDfePrach_ModelParameters::NumAntennaSlots, XDfePrach_Initialize, XDfePrach_TriggerCfg::Activate, XDfePrach_Trigger::TUSERBit, XDfePrach_Trigger::TuserEdgeLevel, XDfePrach_Trigger::StateOutput, XDfePrach_Trigger::Mode, XDfePrach_TriggerCfg::RachUpdate, XDfePrach_TriggerCfg::FrameInit, XDfePrach_SetTriggersCfg, XDfePrach_StatusMask::RachUpdate, XDfePrach_ClearEventStatus, XDfePrach_Activate, XDfePrach_GetEmptyCCCfg, XDfePrach_AddCCtoCCCfg, XDfePrach_GetEmptyRCCfg, XDfePrach_AddRCtoRCCfg, XDfePrach_RemoveRCfromRCCfg, XDfePrach_SetNextCfg, XDfePrach_Deactivate, XDfePrach_InstanceClose.
Referenced by main.
int XDfePrach_2CC3RCDynamicTestExample()
This example runs the DFE Prach device using the driver APIs.
The example goes through the following steps: Create and system initialize the device driver instance.Read SW and HW version numbers.Reset the device.Configure the device.Initialize the device.Activate the device.Get current Component Carrier (CC) configuration.Get current RACH Channel (RC) configuration.add 2 Component Carriers: CCID={5,3}add 3 RACH Channel: RCID={2,4,6}Trigger configuration update.Deactivate the device. XST_SUCCESS if the example has completed successfully.XST_FAILURE if the example has failed.//! [testexample4]
References XDfePrach_CarrierCfg::SCS, XDfePrach_DDCCfg::DecimationRate, XDfePrach_DDCCfg::UserSCS, XDfePrach_DDCCfg::RachGain, XDfePrach_NCO::UserFreq, XDfePrach_NCO::PhaseAcc, XDfePrach_NCO::NcoGain, XDfePrach_NCO::DualModCount, XDfePrach_NCO::DualModSel, XDfePrach_Schedule::PatternPeriod, XDfePrach_Schedule::FrameID, XDfePrach_Schedule::SubframeID, XDfePrach_Schedule::SlotId, XDfePrach_Schedule::Duration, XDfePrach_Schedule::Repeats, XST_SUCCESS, XST_FAILURE, XDfePrach_InstanceInit, XDfePrach_GetVersions, XDfePrach_Version::Major, XDfePrach_Version::Minor, XDfePrach_Version::Revision, XDfePrach_Version::Patch, XDfePrach_Reset, XDfePrach_Configure, XDfePrach_Init::Sequence, XDfePrach_CCSequence::Length, XDfePrach_Cfg::ModelParams, XDfePrach_ModelParameters::NumAntennaSlots, XDfePrach_Init::EnableStaticSchedule, XDfePrach_Initialize, XDfePrach_TriggerCfg::Activate, XDfePrach_Trigger::TUSERBit, XDfePrach_Trigger::TuserEdgeLevel, XDfePrach_Trigger::StateOutput, XDfePrach_Trigger::Mode, XDfePrach_TriggerCfg::RachUpdate, XDfePrach_TriggerCfg::FrameInit, XDfePrach_SetTriggersCfg, XDfePrach_StatusMask::RachUpdate, XDfePrach_ClearEventStatus, XDfePrach_Activate, XDfePrach_GetEmptyCCCfg, XDfePrach_AddCCtoCCCfg, XDfePrach_GetEmptyRCCfg, XDfePrach_AddRCtoRCCfg, XDfePrach_SetNextCfg, XDfePrach_Deactivate, XDfePrach_InstanceClose.
Referenced by main.
int main(void)
Main function that invokes the polled example in this file.
None. XST_SUCCESS if the example has completed successfully.XST_FAILURE if the example has failed.
References XDfePrach_2CC3RCDynamicTestExample, XDfePrach_2CC3RCReconfigureTestExample, XDfePrach_2CC3RCTestExample, XDfePrach_SelfTestExample, XDfeSi570_SetMgtOscillator, XST_FAILURE, XST_SUCCESS.