xdfeprach_intr.c
void XDfePrach_GetInterruptMask(const XDfePrach *InstancePtr, XDfePrach_InterruptMask *Mask)
Returns interrupt mask status.
InstancePtr Pointer to the PRACH instance. Mask Interrupt masks container.
References XDfePrach_StatusMask::CCSequenceError, XDfePrach_StatusMask::DecimatorOverflow, XDfePrach_StatusMask::DecimatorOverrun, XDfePrach_StatusMask::FrameError, XDfePrach_StatusMask::FrameInitTrigger, XDfePrach_StatusMask::MixerOverflow, XDfePrach_StatusMask::RachUpdate, XDfePrach_StatusMask::SelectorOverrun, XDFEPRACH_BAND_ID_MAX.
void XDfePrach_SetInterruptMask(const XDfePrach *InstancePtr, const XDfePrach_InterruptMask *Mask)
Sets the interrupt mask.
InstancePtr Pointer to the PRACH instance. Mask Interrupt mask flags container. 0 - does not mask corresponding interrupt1 - masks corresponding interrupt
References XDfePrach_StatusMask::CCSequenceError, XDfePrach_StatusMask::DecimatorOverflow, XDfePrach_StatusMask::DecimatorOverrun, XDfePrach_StatusMask::FrameError, XDfePrach_StatusMask::FrameInitTrigger, XDfePrach_StatusMask::MixerOverflow, XDfePrach_StatusMask::RachUpdate, XDfePrach_StatusMask::SelectorOverrun, XDFEPRACH_BAND_ID_MAX.
void XDfePrach_GetEventStatus(const XDfePrach *InstancePtr, XDfePrach_StatusMask *Status)
Returns the event status.
InstancePtr Pointer to the PRACH instance. Status Event status container.
References XDfePrach_StatusMask::CCSequenceError, XDfePrach_StatusMask::DecimatorOverflow, XDfePrach_StatusMask::DecimatorOverrun, XDfePrach_StatusMask::FrameError, XDfePrach_StatusMask::FrameInitTrigger, XDfePrach_StatusMask::MixerOverflow, XDfePrach_StatusMask::RachUpdate, XDfePrach_StatusMask::SelectorOverrun, XDFEPRACH_BAND_ID_MAX.
void XDfePrach_ClearEventStatus(const XDfePrach *InstancePtr, const XDfePrach_StatusMask *Status)
Clears the event status.
InstancePtr Pointer to the PRACH instance. Status Clear event status container. 0 - does not clear corresponding event status1 - clear corresponding event status
References XDfePrach_StatusMask::CCSequenceError, XDfePrach_StatusMask::DecimatorOverflow, XDfePrach_StatusMask::DecimatorOverrun, XDfePrach_StatusMask::FrameError, XDfePrach_StatusMask::FrameInitTrigger, XDfePrach_StatusMask::MixerOverflow, XDfePrach_StatusMask::RachUpdate, XDfePrach_StatusMask::SelectorOverrun, XDFEPRACH_BAND_ID_MAX.
Referenced by XDfePrach_2CC3RCDynamicTestExample, XDfePrach_2CC3RCReconfigureTestExample, XDfePrach_2CC3RCTestExample, XDfePrach_ClearStatus.