csuma_api
XCSUDMA_ADDR_OFFSET
Address Register Offset.
Referenced by XCsuDma_64BitTransfer, XCsuDma_GetAddr, XCsuDma_Transfer.
XCSUDMA_SIZE_OFFSET
Size Register Offset.
Referenced by XCsuDma_64BitTransfer, XCsuDma_GetSize, XCsuDma_Transfer.
XCSUDMA_STS_OFFSET
Status Register Offset.
XCSUDMA_CTRL_OFFSET
Control Register Offset.
Referenced by XCsuDma_GetConfig, XCsuDma_IsPaused, XCsuDma_Pause, XCsuDma_Resume, XCsuDma_SelfTest, XCsuDma_SetConfig.
XCSUDMA_I_STS_OFFSET
Interrupt Status Register Offset.
Referenced by XCsuDma_IntrClear, XCsuDma_IntrGetStatus, XCsuDma_WaitForDoneTimeout.
XCSUDMA_SIZE_MASK
Mask for size.
XCSUDMA_LAST_WORD_MASK
Last word check bit mask.
Referenced by XCsuDma_64BitTransfer, XCsuDma_Transfer.
XCSUDMA_SIZE_SHIFT
Shift for size.
Referenced by XCsuDma_64BitTransfer, XCsuDma_GetSize, XCsuDma_Transfer.
XCSUDMA_IXR_FIFO_OVERFLOW_MASK
FIFO overflow mask, it is valid only to Destination Channel.
XCSUDMA_IXR_INVALID_APB_MASK
Invalid APB access mask.
XCSUDMA_IXR_FIFO_THRESHHIT_MASK
FIFO threshold hit indicator mask.
XCSUDMA_IXR_TIMEOUT_MEM_MASK
Time out counter expired to access memory mask.
XCSUDMA_IXR_TIMEOUT_STRM_MASK
Time out counter expired to access stream mask.
XCSUDMA_IXR_AXI_WRERR_MASK
AXI Read/Write error mask.
XCSUDMA_IXR_DONE_MASK
Done mask.
Referenced by XCsuDma_WaitForDoneTimeout.
XCSUDMA_IXR_MEM_DONE_MASK
Memory done mask, it is valid only for source channel.
XCSUDMA_IXR_SRC_MASK
((XCSUDMA_IXR_INVALID_APB_MASK)| (XCSUDMA_IXR_FIFO_THRESHHIT_MASK) | (XCSUDMA_IXR_TIMEOUT_MEM_MASK) | (XCSUDMA_IXR_TIMEOUT_STRM_MASK) | (XCSUDMA_IXR_AXI_WRERR_MASK) | (XCSUDMA_IXR_DONE_MASK) | (XCSUDMA_IXR_MEM_DONE_MASK))
All interrupt mask for source
Referenced by XCsuDma_DisableIntr, XCsuDma_EnableIntr, XCsuDma_IntrClear.
XCSUDMA_IXR_DST_MASK
((XCSUDMA_IXR_FIFO_OVERFLOW_MASK) | (XCSUDMA_IXR_INVALID_APB_MASK) | (XCSUDMA_IXR_FIFO_THRESHHIT_MASK) | (XCSUDMA_IXR_TIMEOUT_MEM_MASK) | (XCSUDMA_IXR_TIMEOUT_STRM_MASK) | (XCSUDMA_IXR_AXI_WRERR_MASK) | (XCSUDMA_IXR_DONE_MASK))
All interrupt mask for destination
Referenced by XCsuDma_DisableIntr, XCsuDma_EnableIntr, XCsuDma_IntrClear.
XCSUDMA_DONE_TIMEOUT_VAL
SW timeout loop value for transfer completion.
Referenced by XCsuDma_WaitForDoneTimeout.
XCsuDma_Channel
Source Channel of CSU_DMA.
s32 XCsuDma_CfgInitialize(XCsuDma *InstancePtr, XCsuDma_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes CSU_DMA core.
This function must be called prior using a CSU_DMA core. Initialization of an CSU_DMA includes setting up the instance data and ensuring the hardware is in a quiescent state. InstancePtr Pointer to the XCsuDma instance. CfgPtr Reference to a structure containing information about a specific XCsuDma instance. EffectiveAddr Device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, pass in the physical address instead. XST_SUCCESS if initialization was successful. None.
References XCsuDma_Config::BaseAddress, XCsuDma::Config, XCsuDma_Config::DmaType, XCsuDma::IsReady, XCSUDMA_DMATYPEIS_CSUDMA, XCsuDma_Reset.
Referenced by XCsuDma_SelfTestExample.
void XCsuDma_Transfer(XCsuDma *InstancePtr, XCsuDma_Channel Channel, u64 Addr, u32 Size, u8 EnDataLast)
This function sets the starting address and size of the data to be transferred from/to the memory through the AXI interface.
InstancePtr Pointer to XCsuDma instance to be worked on. Channel Type of channel Source channel - XCSUDMA_SRC_CHANNEL Destination Channel - XCSUDMA_DST_CHANNEL Addr 64 bit variable which holds the starting address of data which needs to write into the memory(DST) (or read from the memory(SRC)). Size 32 bit variable which represents the number of 4 byte words needs to be transferred from starting address. EnDataLast Triggers an end of the message. Enables or disables data_inp_last signal to stream interface when current command is completed. It is applicable only to source channel; ignored for destination channel. 1 - Asserts data_inp_last signal.0 - data_inp_last will not be asserted. None. Data_inp_last signal is asserted simultaneously with the data_inp_valid signal associated with the final 32-bit word transfer.
References XCsuDma_Config::BaseAddress, XCsuDma::Config, XCsuDma::IsReady, XCSUDMA_ADDR_OFFSET, XCSUDMA_DST_CHANNEL, XCSUDMA_LAST_WORD_MASK, XCSUDMA_SIZE_MAX, XCSUDMA_SIZE_OFFSET, XCSUDMA_SIZE_SHIFT, XCSUDMA_SRC_CHANNEL, XCSUDMA_WORD_SIZE, XCsuDma_WriteReg.
void XCsuDma_64BitTransfer(XCsuDma *InstancePtr, XCsuDma_Channel Channel, u32 AddrLow, u32 AddrHigh, u32 Size, u8 EnDataLast)
This function sets the starting address and size of the data to be transferred from/to the memory through the AXI interface.
This function is useful for pmu processor to execute a 64-bit DMA transfer. InstancePtr Pointer to XCsuDma instance to be worked on. Channel Type of channel Source channel - XCSUDMA_SRC_CHANNEL Destination Channel - XCSUDMA_DST_CHANNEL AddrLow Bit variable which holds the starting lower address of data which needs to write into the memory(DST) (or read from the memory(SRC)). AddrHigh 32 bit variable which holds the higher address of data which needs to write into the memory(DST) (or read from the memoroy(SRC)). Size 32 bit variable which represents the number of 4 byte words to be transferred from starting address. EnDataLast Trigger an end of message. Enables or disable data_inp_last signal to stream interface when current command is completed. Only applicable for the source channel; ignored for destination channel. 1 - Asserts data_inp_last signal.0 - data_inp_last will not be asserted. None. Data_inp_last signal is asserted simultaneously with the data_inp_valid signal associated with the final 32-bit word transfer. This API does not invalidate the DMA buffer. It is recommended to call this API only through PMU processor.
References XCsuDma_Config::BaseAddress, XCsuDma::Config, XCsuDma::IsReady, XCSUDMA_ADDR_OFFSET, XCSUDMA_DST_CHANNEL, XCSUDMA_LAST_WORD_MASK, XCSUDMA_SIZE_MAX, XCSUDMA_SIZE_OFFSET, XCSUDMA_SIZE_SHIFT, XCSUDMA_SRC_CHANNEL, XCSUDMA_WORD_SIZE, XCsuDma_WriteReg.
u64 XCsuDma_GetAddr(XCsuDma *InstancePtr, XCsuDma_Channel Channel)
This function returns the current address location of the memory, from where it has to read the data(SRC) or the location where it has to write the data (DST) based on the channel selection.
InstancePtr Pointer to XCsuDma instance to be worked on. Channel Type of channel Source channel - XCSUDMA_SRC_CHANNEL Destination Channel - XCSUDMA_DST_CHANNEL Address is a 64 bit variable which holds the current address. From this location data has to be read(SRC)At this location data has to be written(DST) None.
References XCsuDma_Config::BaseAddress, XCsuDma::Config, XCSUDMA_ADDR_OFFSET, XCSUDMA_DST_CHANNEL, XCsuDma_ReadReg, XCSUDMA_SRC_CHANNEL.
u32 XCsuDma_GetSize(XCsuDma *InstancePtr, XCsuDma_Channel Channel)
This function returns the size of the data yet to be transferred from memory to CSU_DMA or CSU_DMA to memory based on the channel selection.
InstancePtr Pointer to XCsuDma instance to be worked on. Channel Type of channel Source channel - XCSUDMA_SRC_CHANNEL Destination Channel - XCSUDMA_DST_CHANNEL Returns number of bytes of data yet to be transferred. None.
References XCsuDma_Config::BaseAddress, XCsuDma::Config, XCSUDMA_DST_CHANNEL, XCsuDma_ReadReg, XCSUDMA_SIZE_OFFSET, XCSUDMA_SIZE_SHIFT, XCSUDMA_SRC_CHANNEL.
void XCsuDma_Pause(XCsuDma *InstancePtr, XCsuDma_Channel Channel, XCsuDma_PauseType Type)
This function pauses the Channel data transfer to/from memory or to/from stream based on pause type.
InstancePtr Pointer to XCsuDma instance to be worked on. Channel Type of channel Source channel - XCSUDMA_SRC_CHANNEL Destination Channel - XCSUDMA_DST_CHANNEL Type Type of pause to be enabled. XCSUDMA_PAUSE_MEMORY(0) - Pause memory SRC stops issuing new read commands to memory.DST stops issuing new write commands to memory. XCSUDMA_PAUSE_STREAM(1) - Pause stream SRC stops the transfer of data from FIFO to Stream.DST stops the transfer of data from stream to FIFO. None. None.
References XCsuDma_Config::BaseAddress, XCsuDma::Config, XCsuDma::IsReady, XCSUDMA_CTRL_OFFSET, XCSUDMA_DST_CHANNEL, XCSUDMA_PAUSE_MEMORY, XCSUDMA_PAUSE_STREAM, XCsuDma_ReadReg, XCSUDMA_SRC_CHANNEL, XCsuDma_WriteReg.
s32 XCsuDma_IsPaused(XCsuDma *InstancePtr, XCsuDma_Channel Channel, XCsuDma_PauseType Type)
This function checks whether Channel memory/stream is paused based on the given pause type.
InstancePtr Pointer to XCsuDma instance to be worked on. Channel Type of channel Source channel - XCSUDMA_SRC_CHANNEL Destination Channel - XCSUDMA_DST_CHANNEL Type Type of the pause which needs to be checked. XCSUDMA_PAUSE_MEMORY(0) - Pause memory SRC stops issuing new read commands to memory.DST stops issuing new write commands to memory. XCSUDMA_PAUSE_STREAM(1) - Pause stream SRC stops the transfer of data from FIFO to Stream.DST stops the transfer of data from stream to FIFO. Returns the pause status. TRUE if it is in paused state.FALSE if it is not in pause state. None.
References XCsuDma_Config::BaseAddress, XCsuDma::Config, XCSUDMA_CTRL_OFFSET, XCSUDMA_DST_CHANNEL, XCSUDMA_PAUSE_MEMORY, XCSUDMA_PAUSE_STREAM, XCsuDma_ReadReg, XCSUDMA_SRC_CHANNEL.
void XCsuDma_Resume(XCsuDma *InstancePtr, XCsuDma_Channel Channel, XCsuDma_PauseType Type)
This function resumes the channel if it is in paused state and continues where it has left.
Based on the type of pause, there is no effect if it is not in paused state. InstancePtr Pointer to XCsuDma instance to be worked on. Channel Type of channel Source channel - XCSUDMA_SRC_CHANNEL Destination Channel - XCSUDMA_DST_CHANNEL Type Type of pause to be resumed if it is paused. XCSUDMA_PAUSE_MEMORY(0) - Pause memory SRC stops issuing new read commands to memory.DST stops issuing new write commands to memory. XCSUDMA_PAUSE_STREAM(1) - Pause stream SRC stops the transfer of data from FIFO to Stream.DST stops the transfer of data from stream to FIFO. None. None.
References XCsuDma_Config::BaseAddress, XCsuDma::Config, XCsuDma::IsReady, XCSUDMA_CTRL_OFFSET, XCSUDMA_DST_CHANNEL, XCSUDMA_PAUSE_MEMORY, XCSUDMA_PAUSE_STREAM, XCsuDma_ReadReg, XCSUDMA_SRC_CHANNEL, XCsuDma_WriteReg.
u32 XCsuDma_GetCheckSum(XCsuDma *InstancePtr)
This function returns the sum of all the data read from AXI memory.
It is valid only when using the CSU_DMA source channel. InstancePtr Pointer to XCsuDma instance to be worked on. The sum of all the data read from memory. Before the transfer starts, clear this register to get the correct sum. Otherwise, it adds to previous value which results in an incorrect output. Valid only for source channel.
References XCsuDma_Config::BaseAddress, XCsuDma::Config, XCsuDma::IsReady, XCsuDma_ReadReg.
void XCsuDma_ClearCheckSum(XCsuDma *InstancePtr)
This function clears the check sum of the data read from AXI memory.
It is valid only for CSU_DMA source channel. InstancePtr Pointer to XCsuDma instance to be worked on. The sum of all the data read from memory. Before the transfer starts, clear this register to get correct sum. Otherwise, it adds to previous value which results in an incorrect output.
References XCsuDma_Config::BaseAddress, XCsuDma::Config, XCsuDma_WriteReg.
u32 XCsuDma_WaitForDoneTimeout(XCsuDma *InstancePtr, XCsuDma_Channel Channel)
This function polls for completion of data transfer periodically until the DMA done bit set or until the timeout occurs.
InstancePtr Pointer to XCsuDma instance to be worked on. Channel Type of channel Source channel - XCSUDMA_SRC_CHANNEL Destination Channel - XCSUDMA_DST_CHANNEL XST_SUCCESS - In case of Success XST_FAILURE - In case of Timeout. None.
References XCsuDma_Config::BaseAddress, XCsuDma::Config, XCSUDMA_DONE_TIMEOUT_VAL, XCSUDMA_DST_CHANNEL, XCSUDMA_I_STS_OFFSET, XCSUDMA_IXR_DONE_MASK, XCSUDMA_SRC_CHANNEL.
void XCsuDma_SetConfig(XCsuDma *InstancePtr, XCsuDma_Channel Channel, XCsuDma_Configure *ConfigurValues)
This function configures all the values of CSU_DMA Channels with the values of updated XCsuDma_Configure structure.
InstancePtr Pointer to XCsuDma instance to be worked on. Channel Type of channel Source channel - XCSUDMA_SRC_CHANNEL Destination Channel - XCSUDMA_DST_CHANNEL ConfigurValues Pointer to the structure XCsuDma_Configure whose values are used to configure CSU_DMA core. SssFifoThesh: When the DST FIFO level >= this value, the SSS interface signal, "data_out_fifo_level_hit" is asserted. This mechanism can be used by the SSS to flow control data that is being looped back from the SRC DMA. Range is (0x10 to 0x7A) threshold is 17 to 123 entries.It is valid only for DST CSU_DMA IP. ApbErr: When accessed to invalid APB the resulting pslerr will be 0 - 1'b01 - 1'b1 EndianType: Type of endianness 0 doesn't change order1 will flip the order. AxiBurstType: Type of the burst 0 will issue INCR type burst1 will issue FIXED type burst TimeoutValue: Time out value for timers 0x000 to 0xFFE are valid inputs0xFFF clears both timers FifoThresh: Programmed watermark value Range is 0x00 to 0x80 (0 to 128 entries). Acache: Sets the AXI CACHE bits on the AXI Write/Read channel. Cacheable ARCACHE[1] for SRC Channel and AWCACHE[1] for DST channel are always 1, we need to configure remaining 3 signal support (Bufferable, Read allocate and Write allocate). Valid inputs are:0x000 - Cacheable, but do not allocate0x001 - Cacheable and bufferable, but do not allocate0x010 - Cacheable write-through, allocate on reads only0x011 - Cacheable write-back, allocate on reads only0x100 - Cacheable write-through, allocate on writes only0x101 - Cacheable write-back, allocate on writes only0x110 - Cacheable write-through, allocate on both reads and writes0x111 - Cacheable write-back, allocate on both reads and writes RouteBit: To select route 0 : Command will be routed normally1 : Command will be routed to APU's cache controller TimeoutEn: To enable or disable time out counters 0 : The 2 Timeout counters are disabled1 : The 2 Timeout counters are enabled TimeoutPre: Set the prescaler value for the timeout in clk (~2.5ns) cycles Range is 0x000(Prescaler enables timer every cycles) to 0xFFF(Prescaler enables timer every 4096 cycles) MaxOutCmds: Controls the maximumum number of outstanding AXI read commands issued. Range is 0x0(Up to 1 Outstanding Read command allowed) to 0x8 (Up to 9 Outstanding Read command allowed) None. To use timers timeout value Timeout enable field should be enabled. Users should check for the status of existing transfers before making configuration changes.
References XCsuDma_Configure::Acache, XCsuDma_Configure::ApbErr, XCsuDma_Configure::AxiBurstType, XCsuDma_Config::BaseAddress, XCsuDma::Config, XCsuDma_Configure::EndianType, XCsuDma_Configure::FifoThresh, XCsuDma::IsReady, XCsuDma_Configure::MaxOutCmds, XCsuDma_Configure::RouteBit, XCsuDma_Configure::SssFifoThesh, XCsuDma_Configure::TimeoutEn, XCsuDma_Configure::TimeoutPre, XCsuDma_Configure::TimeoutValue, XCSUDMA_CTRL_OFFSET, XCSUDMA_DST_CHANNEL, XCsuDma_ReadReg, XCSUDMA_SRC_CHANNEL, XCsuDma_WriteReg.
void XCsuDma_GetConfig(XCsuDma *InstancePtr, XCsuDma_Channel Channel, XCsuDma_Configure *ConfigurValues)
This function updates XCsuDma_Configure structure members with the configured values of CSU_DMA's Channel.
InstancePtr Pointer to XCsuDma instance to be worked on. Channel Type of channel Source channel - XCSUDMA_SRC_CHANNEL Destination Channel - XCSUDMA_DST_CHANNEL ConfigurValues Pointer to the structure XCsuDma_Configure whose members are updated with configurations of CSU_DMA core. SssFifoThesh: When the DST FIFO level >= this value, the SSS interface signal, "data_out_fifo_level_hit" will be asserted. This mechanism can be used by the SSS to flow control data that is being looped back from the SRC DMA. Range is (0x10 to 0x7A) threshold is 17 to 123 entries.It is valid only for DST CSU_DMA IP. ApbErr: When accessed to invalid APB the resulting pslerr will be 0 - 1'b01 - 1'b1 EndianType: Type of endianness 0 doesn't change order1 will flip the order. AxiBurstType: Type of the burst 0 will issue INCR type burst1 will issue FIXED type burst TimeoutValue: Time out value for timers 0x000 to 0xFFE are valid inputs0xFFF clears both timers FifoThresh: Programmed watermark value Range is 0x00 to 0x80 (0 to 128 entries). Acache: Sets the AXI CACHE bits on the AXI Write/Read channel. Cacheable ARCACHE[1] for SRC Channel and AWCACHE[1] for DST channel are always 1, we need to configure remaining 3 signal support (Bufferable, Read allocate and Write allocate). Valid inputs are:0x000 - Cacheable, but do not allocate0x001 - Cacheable and bufferable, but do not allocate0x010 - Cacheable write-through, allocate on reads only0x011 - Cacheable write-back, allocate on reads only0x100 - Cacheable write-through, allocate on writes only0x101 - Cacheable write-back, allocate on writes only0x110 - Cacheable write-through, allocate on both reads and writes0x111 - Cacheable write-back, allocate on both reads and writes RouteBit: To select route 0 : Command will be routed based normally1 : Command will be routed to APU's cache controller TimeoutEn: To enable or disable time out counters 0 : The 2 Timeout counters are disabled1 : The 2 Timeout counters are enabled TimeoutPre: Set the prescaler value for the timeout in clk (~2.5ns) cycles Range is 0x000(Prescaler enables timer every cycles) to 0xFFF(Prescaler enables timer every 4096 cycles) MaxOutCmds: Controls the maximumum number of outstanding AXI read commands issued. Range is 0x0(Up to 1 Outstanding Read command allowed) to 0x8 (Up to 9 Outstanding Read command allowed) None. None.
References XCsuDma_Configure::Acache, XCsuDma_Configure::ApbErr, XCsuDma_Configure::AxiBurstType, XCsuDma_Config::BaseAddress, XCsuDma::Config, XCsuDma_Configure::EndianType, XCsuDma_Configure::FifoThresh, XCsuDma_Configure::MaxOutCmds, XCsuDma_Configure::RouteBit, XCsuDma_Configure::SssFifoThesh, XCsuDma_Configure::TimeoutEn, XCsuDma_Configure::TimeoutPre, XCsuDma_Configure::TimeoutValue, XCSUDMA_CTRL_OFFSET, XCSUDMA_DST_CHANNEL, XCsuDma_ReadReg, XCSUDMA_SRC_CHANNEL.
u32 XCsuDma_IntrGetStatus(XCsuDma *InstancePtr, XCsuDma_Channel Channel)
This function returns interrupt status read from Interrupt Status Register.
Use the XCSUDMA_IXR_*_MASK constants defined in xcsudma_hw.h to interpret the returned value. InstancePtr Pointer to XCsuDma instance to be worked on. Channel Type of channel Source channel - XCSUDMA_SRC_CHANNEL Destination Channel - XCSUDMA_DST_CHANNEL The pending interrupts of the CSU_DMA. Use th following masks to interpret the returned value. XCSUDMA_IXR_SRC_MASK - For Source channel XCSUDMA_IXR_DST_MASK - For Destination channel None.
References XCsuDma_Config::BaseAddress, XCsuDma::Config, XCSUDMA_DST_CHANNEL, XCSUDMA_I_STS_OFFSET, XCsuDma_ReadReg, XCSUDMA_SRC_CHANNEL.
void XCsuDma_IntrClear(XCsuDma *InstancePtr, XCsuDma_Channel Channel, u32 Mask)
This function clears interrupt(s).
Every bit set in Interrupt Status Register indicates that a specific type of interrupt is occurring, and this function clears one or more interrupts by writing a bit mask to Interrupt Clear Register. InstancePtr Pointer to XCsuDma instance to be worked on. Channel Type of channel Source channel - XCSUDMA_SRC_CHANNEL Destination Channel - XCSUDMA_DST_CHANNEL Mask Mask to clear. Bit positions of 1 will be cleared. Bit positions of 0 will not change the previous interrupt status. This mask is formed by OR'ing XCSUDMA_IXR_* bits defined in xcsudma_hw.h. None.
References XCsuDma_Config::BaseAddress, XCsuDma::Config, XCSUDMA_DST_CHANNEL, XCSUDMA_I_STS_OFFSET, XCSUDMA_IXR_DST_MASK, XCSUDMA_IXR_SRC_MASK, XCSUDMA_SRC_CHANNEL, XCsuDma_WriteReg.
void XCsuDma_EnableIntr(XCsuDma *InstancePtr, XCsuDma_Channel Channel, u32 Mask)
This function enables the interrupt(s).
Use the XCSUDMA_IXR_*_MASK constants defined in xcsudma_hw.h to create the bit-mask to enable interrupts. InstancePtr Pointer to XCsuDma instance to be worked on. Channel Type of channel Source channel - XCSUDMA_SRC_CHANNEL Destination Channel - XCSUDMA_DST_CHANNEL Mask Contains interrupts to be enabled. Bit positions of 1 will be enabled. This mask is formed by OR'ing XCSUDMA_IXR_*_MASK bits defined in xcsudma_hw.h. None. None.
References XCsuDma_Config::BaseAddress, XCsuDma::Config, XCSUDMA_DST_CHANNEL, XCSUDMA_IXR_DST_MASK, XCSUDMA_IXR_SRC_MASK, XCSUDMA_SRC_CHANNEL, XCsuDma_WriteReg.
void XCsuDma_DisableIntr(XCsuDma *InstancePtr, XCsuDma_Channel Channel, u32 Mask)
This function disables the interrupt(s).
Use the XCSUDMA_IXR_*_MASK constants defined in xcsudma_hw.h to create the bit-mask to disable interrupts. InstancePtr Pointer to XCsuDma instance to be worked on. Channel Type of channel Source channel - XCSUDMA_SRC_CHANNEL Destination Channel - XCSUDMA_DST_CHANNEL Mask Contains interrupts to be disabled. Bit positions of 1 will be disabled. This mask is formed by OR'ing XCSUDMA_IXR_*_MASK bits defined in xcsudma_hw.h. None. None.
References XCsuDma_Config::BaseAddress, XCsuDma::Config, XCSUDMA_DST_CHANNEL, XCSUDMA_IXR_DST_MASK, XCSUDMA_IXR_SRC_MASK, XCSUDMA_SRC_CHANNEL, XCsuDma_WriteReg.
u32 XCsuDma_GetIntrMask(XCsuDma *InstancePtr, XCsuDma_Channel Channel)
This function returns the interrupt mask to know which interrupts are enabled and which of them were disabled.
InstancePtr Pointer to XCsuDma instance to be worked on. Channel Type of channel Source channel - XCSUDMA_SRC_CHANNEL Destination Channel - XCSUDMA_DST_CHANNEL The current interrupt mask. The mask indicates which interrupts are enabled/disabled. 0 bit represents that the corresponding interrupt is enabled.1 bit represents that the Corresponding interrupt is disabled. To interpret returned mask useXCSUDMA_IXR_SRC_MASK that the For source channelXCSUDMA_IXR_DST_MASK that the For destination channel None.
References XCsuDma_Config::BaseAddress, XCsuDma::Config, XCSUDMA_DST_CHANNEL, XCsuDma_ReadReg, XCSUDMA_SRC_CHANNEL.
s32 XCsuDma_SelfTest(XCsuDma *InstancePtr)
This function runs a self-test on the driver and hardware device.
Performs reset of both source and destination channels and checks if reset is working properly or not. InstancePtr Pointer to the XCsuDma instance. XST_SUCCESS if the self-test passed. XST_FAILURE otherwise. None.
References XCsuDma_Config::BaseAddress, XCsuDma::Config, XCSUDMA_CTRL_OFFSET, XCsuDma_ReadReg, XCsuDma_WriteReg.
Referenced by XCsuDma_SelfTestExample.
XCsuDma_Config* XCsuDma_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
A table contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration table entry corresponding to the given device ID/BaseAddress, or NULL if no match is found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XCsuDma_Config::Name.
Referenced by XCsuDma_SelfTestExample.
XCSUDMA_WORD_SIZE
Transfer size conversion to bytes for Versal Net.
Referenced by XCsuDma_64BitTransfer, XCsuDma_Transfer.
XCSUDMA_H_
Prevent circular inclusions by using protection macros.
XCSUDMA_HW_H_
Prevent circular inclusions by using protection macros.
XCsuDma_In32
Input operation.
XCsuDma_Out32
Output operation.
XCsuDma_ReadReg
This macro reads the given register.
BaseAddress Base address of the CSU_DMA core. RegOffset Register offset of the register. The 32-bit value of the register. C-style signature: u32 XCsuDma_ReadReg(u32 BaseAddress, u32 RegOffset)
Referenced by XCsuDma_GetAddr, XCsuDma_GetCheckSum, XCsuDma_GetConfig, XCsuDma_GetIntrMask, XCsuDma_GetSize, XCsuDma_IntrGetStatus, XCsuDma_IsPaused, XCsuDma_Pause, XCsuDma_Resume, XCsuDma_SelfTest, XCsuDma_SetConfig.
XCsuDma_WriteReg
This macro writes the value into the given register.
BaseAddress Base address of the CSU_DMA core. RegOffset Register offset of the register. Data 32-bit value to write to the register. None. C-style signature: void XCsuDma_WriteReg(u32 BaseAddress, u32 RegOffset, u32 Data)
Referenced by XCsuDma_64BitTransfer, XCsuDma_ClearCheckSum, XCsuDma_DisableIntr, XCsuDma_EnableIntr, XCsuDma_IntrClear, XCsuDma_Pause, XCsuDma_Resume, XCsuDma_SelfTest, XCsuDma_SetConfig, XCsuDma_Transfer.