xv_warp_init.h
XV_warp_init_WriteReg
Write a value to a register at the specified offset.
Referenced by XV_warp_init_DisableAutoRestart, XV_warp_init_EnableAutoRestart, XV_warp_init_InterruptClear, XV_warp_init_InterruptDisable, XV_warp_init_InterruptEnable, XV_warp_init_InterruptGlobalDisable, XV_warp_init_InterruptGlobalEnable, XV_warp_init_Set_desc_addr, XV_warp_init_Set_maxi_read_write, XV_warp_init_SetFlushbit, XV_warp_init_Start.
XV_warp_init_ReadReg
Read a value from a register at the specified offset.
Referenced by XV_warp_init_Get_desc_addr, XV_warp_init_Get_FlushDone, XV_warp_init_Get_ip_status, XV_warp_init_Get_maxi_read_write, XV_warp_init_InterruptDisable, XV_warp_init_InterruptEnable, XV_warp_init_InterruptGetEnabled, XV_warp_init_InterruptGetStatus, XV_warp_init_IsDone, XV_warp_init_IsIdle, XV_warp_init_IsReady, XV_warp_init_SetFlushbit, XV_warp_init_Start.
XV_warp_init_warp_type
Lens distortion warp type.
typedef void(* XV_warp_init_Callback)(void *CallbackRef))(void *CallbackRef)
Callback function pointer type.
typedef u32 word_type
Word type definition.
int XV_warp_init_Initialize(XV_warp_init *InstancePtr, UINTPTR BaseAddress)
Initialize the warp init driver instance by base address.
This function initializes the XV_warp_init driver instance by looking up the configuration structure based on the base address and calling the configuration initialization function. InstancePtr Pointer to the XV_warp_init instance to initialize BaseAddress Base address to look up in the configuration table, or 0 to use the first available configuration XST_SUCCESS on successful initialization XST_DEVICE_NOT_FOUND if the base address is not found This function is only available in SDT builds. The InstancePtr must not be NULL.
References XV_warp_init::IsReady, XV_warp_init_CfgInitialize, XV_warp_init_LookupConfig.
Referenced by main.
XV_warp_init_Config* XV_warp_init_LookupConfig(UINTPTR BaseAddress)
Lookup configuration structure by base address.
This function searches the configuration table for a matching base address and returns a pointer to the corresponding configuration structure. BaseAddress The base address to search for in the configuration table, or 0 to return the first entry Pointer to the matching XV_warp_init_Config structure, or NULL if no match is found This function is only available in SDT builds
References XV_warp_init_Config::Name.
Referenced by XV_warp_init_Initialize.
int XV_warp_init_CfgInitialize(XV_warp_init *InstancePtr, XV_warp_init_Config *ConfigPtr)
Initialize the warp init instance with configuration.
This function initializes the XV_warp_init driver instance using the provided configuration structure. Sets up base addresses and initializes the descriptor configuration. InstancePtr Pointer to the XV_warp_init instance ConfigPtr Pointer to the configuration structure XST_SUCCESS on successful initialization This function is only available in non-Linux builds. Both pointers must not be NULL.
References XV_warp_init::config, XV_warp_init_Config::Ctrl_BaseAddress, XV_warp_init::Ctrl_BaseAddress, XV_warp_init::IsReady, XV_warp_init::NumDescriptors, XV_warp_init::RemapVectorDesc_BaseAddr.
Referenced by XV_warp_init_Initialize.
void XV_warp_init_Start(XV_warp_init *InstancePtr)
Start the warp init IP core.
This function starts the warp init IP core by setting the AP_START bit in the control register while preserving the auto-restart configuration. InstancePtr Pointer to the XV_warp_init instance None The instance must be ready before calling this function
References XV_warp_init::Ctrl_BaseAddress, XV_warp_init::IsReady, XV_WARP_INIT_CTRL_ADDR_AP_CTRL, XV_warp_init_ReadReg, XV_warp_init_WriteReg.
Referenced by XVWarpInit_start_with_desc.
u32 XV_warp_init_IsDone(XV_warp_init *InstancePtr)
Check if the warp init IP core has finished processing.
This function checks the AP_DONE bit in the control register to determine if the IP core has completed its current operation. InstancePtr Pointer to the XV_warp_init instance 1 if operation is done, 0 otherwise None
References XV_warp_init::Ctrl_BaseAddress, XV_warp_init::IsReady, XV_WARP_INIT_CTRL_ADDR_AP_CTRL, XV_warp_init_ReadReg.
Referenced by XVWarpInit_IntrHandler.
u32 XV_warp_init_IsIdle(XV_warp_init *InstancePtr)
Check if the warp init IP core is idle.
This function checks the AP_IDLE bit in the control register to determine if the IP core is currently idle. InstancePtr Pointer to the XV_warp_init instance 1 if idle, 0 if busy None
References XV_warp_init::Ctrl_BaseAddress, XV_warp_init::IsReady, XV_WARP_INIT_CTRL_ADDR_AP_CTRL, XV_warp_init_ReadReg.
u32 XV_warp_init_IsReady(XV_warp_init *InstancePtr)
Check if the warp init IP core is ready for next input.
This function checks if the IP core is ready to accept new input by verifying that the AP_START bit is not set. InstancePtr Pointer to the XV_warp_init instance 1 if ready for next input, 0 otherwise None
References XV_warp_init::Ctrl_BaseAddress, XV_warp_init::IsReady, XV_WARP_INIT_CTRL_ADDR_AP_CTRL, XV_warp_init_ReadReg.
void XV_warp_init_EnableAutoRestart(XV_warp_init *InstancePtr)
Enable auto-restart mode for the warp init IP core.
This function enables auto-restart mode by setting bit 7 of the control register, allowing the IP to automatically restart after completion. InstancePtr Pointer to the XV_warp_init instance None None
References XV_warp_init::Ctrl_BaseAddress, XV_warp_init::IsReady, XV_WARP_INIT_CTRL_ADDR_AP_CTRL, XV_warp_init_WriteReg.
void XV_warp_init_DisableAutoRestart(XV_warp_init *InstancePtr)
Disable auto-restart mode for the warp init IP core.
This function disables auto-restart mode by clearing the control register, requiring manual restart after each operation completes. InstancePtr Pointer to the XV_warp_init instance None None
References XV_warp_init::Ctrl_BaseAddress, XV_warp_init::IsReady, XV_WARP_INIT_CTRL_ADDR_AP_CTRL, XV_warp_init_WriteReg.
u32 XV_warp_init_Get_FlushDone(XV_warp_init *InstancePtr)
Get the flush done status.
This function checks if the flush operation has completed by reading the flush done status bit from the control register. InstancePtr Pointer to the XV_warp_init instance Flush done status (non-zero if flush is complete, 0 otherwise) None
References AP_CTRL_FLUSH_STATUSBIT, XV_warp_init::Ctrl_BaseAddress, XV_warp_init::IsReady, XV_WARP_INIT_CTRL_ADDR_AP_CTRL, XV_warp_init_ReadReg.
Referenced by XVWarpInit_Stop.
void XV_warp_init_SetFlushbit(XV_warp_init *InstancePtr)
Set the flush bit to initiate IP core flush.
This function sets the flush bit in the control register to initiate a flush operation, clearing any pending data in the IP core pipeline. InstancePtr Pointer to the XV_warp_init instance None Check flush completion using XV_warp_init_Get_FlushDone()
References AP_CTRL_FLUSH_BIT, XV_warp_init::Ctrl_BaseAddress, XV_warp_init::IsReady, XV_WARP_INIT_CTRL_ADDR_AP_CTRL, XV_warp_init_ReadReg, XV_warp_init_WriteReg.
Referenced by XVWarpInit_Stop.
u32 XV_warp_init_Get_ip_status(XV_warp_init *InstancePtr)
Get the IP status register value.
This function reads and returns the IP status register which contains various status flags from the warp init IP core. InstancePtr Pointer to the XV_warp_init instance IP status register value None
References XV_warp_init::Ctrl_BaseAddress, XV_warp_init::IsReady, XV_WARP_INIT_CTRL_ADDR_IP_STATUS_REG_DATA, XV_warp_init_ReadReg.
void XV_warp_init_Set_maxi_read_write(XV_warp_init *InstancePtr, u64 Data)
Set the AXI master read/write address.
This function sets the 64-bit AXI master read/write base address for memory access operations. InstancePtr Pointer to the XV_warp_init instance Data 64-bit address value to set None Address is written as two 32-bit registers
References XV_warp_init::Ctrl_BaseAddress, XV_warp_init::IsReady, XV_WARP_INIT_CTRL_ADDR_MAXI_READ_WRITE_DATA, XV_warp_init_WriteReg.
Referenced by XVWarpInit_start_with_desc.
u64 XV_warp_init_Get_maxi_read_write(XV_warp_init *InstancePtr)
Get the AXI master read/write address.
This function reads and returns the current 64-bit AXI master read/write base address. InstancePtr Pointer to the XV_warp_init instance Current 64-bit address value Address is read from two 32-bit registers
References XV_warp_init::Ctrl_BaseAddress, XV_warp_init::IsReady, XV_WARP_INIT_CTRL_ADDR_MAXI_READ_WRITE_DATA, XV_warp_init_ReadReg.
void XV_warp_init_Set_desc_addr(XV_warp_init *InstancePtr, u64 Data)
Set the descriptor address.
This function sets the 64-bit descriptor base address for the warp initialization descriptor data structure. InstancePtr Pointer to the XV_warp_init instance Data 64-bit descriptor address to set None Address is written as two 32-bit registers
References XV_warp_init::Ctrl_BaseAddress, XV_warp_init::IsReady, XV_WARP_INIT_CTRL_ADDR_DESC_ADDR_DATA, XV_warp_init_WriteReg.
Referenced by XVWarpInit_start_with_desc.
u64 XV_warp_init_Get_desc_addr(XV_warp_init *InstancePtr)
Get the descriptor address.
This function reads and returns the current 64-bit descriptor base address. InstancePtr Pointer to the XV_warp_init instance Current 64-bit descriptor address Address is read from two 32-bit registers
References XV_warp_init::Ctrl_BaseAddress, XV_warp_init::IsReady, XV_WARP_INIT_CTRL_ADDR_DESC_ADDR_DATA, XV_warp_init_ReadReg.
void XV_warp_init_InterruptGlobalEnable(XV_warp_init *InstancePtr)
Enable global interrupts.
This function enables the global interrupt output by setting the Global Interrupt Enable (GIE) register. InstancePtr Pointer to the XV_warp_init instance None None
References XV_warp_init::Ctrl_BaseAddress, XV_warp_init::IsReady, XV_WARP_INIT_CTRL_ADDR_GIE, XV_warp_init_WriteReg.
Referenced by XVWarpInit_EnableInterrupts.
void XV_warp_init_InterruptGlobalDisable(XV_warp_init *InstancePtr)
Disable global interrupts.
This function disables the global interrupt output by clearing the Global Interrupt Enable (GIE) register. InstancePtr Pointer to the XV_warp_init instance None None
References XV_warp_init::Ctrl_BaseAddress, XV_warp_init::IsReady, XV_WARP_INIT_CTRL_ADDR_GIE, XV_warp_init_WriteReg.
void XV_warp_init_InterruptEnable(XV_warp_init *InstancePtr, u32 Mask)
Enable specific interrupts.
This function enables the interrupts specified by the mask parameter by setting the corresponding bits in the Interrupt Enable Register (IER). InstancePtr Pointer to the XV_warp_init instance Mask Interrupt mask with bits set for interrupts to enable None Multiple interrupts can be enabled simultaneously using OR'd mask
References XV_warp_init::Ctrl_BaseAddress, XV_warp_init::IsReady, XV_WARP_INIT_CTRL_ADDR_IER, XV_warp_init_ReadReg, XV_warp_init_WriteReg.
Referenced by XVWarpInit_EnableInterrupts.
void XV_warp_init_InterruptDisable(XV_warp_init *InstancePtr, u32 Mask)
Disable specific interrupts.
This function disables the interrupts specified by the mask parameter by clearing the corresponding bits in the Interrupt Enable Register (IER). InstancePtr Pointer to the XV_warp_init instance Mask Interrupt mask with bits set for interrupts to disable None Multiple interrupts can be disabled simultaneously using OR'd mask
References XV_warp_init::Ctrl_BaseAddress, XV_warp_init::IsReady, XV_WARP_INIT_CTRL_ADDR_IER, XV_warp_init_ReadReg, XV_warp_init_WriteReg.
void XV_warp_init_InterruptClear(XV_warp_init *InstancePtr, u32 Mask)
Clear interrupt status flags.
This function clears the interrupt status flags specified by the mask parameter by writing to the Interrupt Status Register (ISR). InstancePtr Pointer to the XV_warp_init instance Mask Interrupt mask with bits set for interrupts to clear None Write 1 to clear the corresponding interrupt status bit
References XV_warp_init::Ctrl_BaseAddress, XV_warp_init::IsReady, XV_WARP_INIT_CTRL_ADDR_ISR, XV_warp_init_WriteReg.
Referenced by XVWarpInit_IntrHandler.
u32 XV_warp_init_InterruptGetEnabled(XV_warp_init *InstancePtr)
Get enabled interrupts.
This function reads and returns the Interrupt Enable Register (IER) value showing which interrupts are currently enabled. InstancePtr Pointer to the XV_warp_init instance Contents of the Interrupt Enable Register None
References XV_warp_init::Ctrl_BaseAddress, XV_warp_init::IsReady, XV_WARP_INIT_CTRL_ADDR_IER, XV_warp_init_ReadReg.
u32 XV_warp_init_InterruptGetStatus(XV_warp_init *InstancePtr)
Get interrupt status.
This function reads and returns the Interrupt Status Register (ISR) value showing which interrupts are currently pending. InstancePtr Pointer to the XV_warp_init instance Contents of the Interrupt Status Register None
References XV_warp_init::Ctrl_BaseAddress, XV_warp_init::IsReady, XV_WARP_INIT_CTRL_ADDR_ISR, XV_warp_init_ReadReg.
Referenced by XVWarpInit_IntrHandler.