xv_warp_init_l2.h
void XVWarpInit_EnableInterrupts(XV_warp_init *InstancePtr, u32 Mask)
This function Enables the Interrupts for the core instance.
InstancePtr is a pointer to core instance to be worked upon Mask is the Interrupt enable mask none
References XV_warp_init_InterruptEnable, XV_warp_init_InterruptGlobalEnable.
Referenced by main.
void XVWarpInit_SetCallback(XV_warp_init *InstancePtr, void *CallbackFunc, void *CallbackRef)
Install asynchronous callback function.
This function installs an asynchronous callback function for the v_warp_init IP instance. The callback will be invoked when a frame done interrupt occurs. InstancePtr is a pointer to the XV_warp_init IP instance CallbackFunc is the address of the callback function CallbackRef is a user data item that will be passed to the callback function when it is invoked None Invoking this function for a handler that already has been installed replaces it with the new handler
References XV_warp_init::FrameDoneCallback, XV_warp_init::CallbackRef.
Referenced by main.
void* XVWarpInit_IntrHandler(void *InstancePtr)
Interrupt handler for v_warp_init core.
This function is the interrupt handler for the v_warp_init core driver. It clears the pending interrupt and determines if the source is a frame done signal. If yes, it calls the registered callback function. InstancePtr is a pointer to the core instance that just interrupted None The application is responsible for connecting this function to the interrupt system
References XV_warp_init::IsReady, XV_warp_init_InterruptGetStatus, XV_warp_init_IsDone, XV_warp_init_InterruptClear, XV_WARP_INIT_INTR_AP_DONE_MASK, XV_warp_init::FrameDoneCallback, XV_warp_init::CallbackRef.
Referenced by main.
int XVWarpInit_SetNumOfDescriptors(XV_warp_init *InstancePtr, u32 num_descriptors)
This function creates the descriptors.
InstancePtr is a pointer to core instance to be worked upon num_desc is the number of descriptors to be created XST_SUCCESS if Descriptors created successfully XST_FAILURE if Descriptors creation failed
References XV_warp_init_Config::axi_mm_data_width, XV_warp_init::config, XV_warp_init::NumDescriptors, XVWarpInitVector_Hw_Aligned::remap_nextaddr, XV_warp_init::RemapVectorDesc_BaseAddr.
Referenced by main.
void XVWarpInit_ClearNumOfDescriptors(XV_warp_init *InstancePtr)
This function clears and de-allocates all the descriptors.
InstancePtr is a pointer to core instance to be worked upon none
References XV_warp_init::NumDescriptors, XVWarpInitVector_Hw_Aligned::remap_nextaddr, XV_warp_init::RemapVectorDesc_BaseAddr.
Referenced by main.
int XVWarpInit_ProgramDescriptor(XV_warp_init *InstancePtr, u32 Descnum, XVWarpInit_InputConfigs *ConfigPtr)
This function programs a descriptor with given configurations.
InstancePtr is a pointer to core instance to be worked upon Descnum is the descriptor number which to be configured ConfigPtr is the input configuration pointer which to be configured into the descriptor XST_SUCCESS if programming descriptor is successful XST_FAILURE if input configurations are not valid.
References XVWarpInitVector_Hw::bytes_per_pixel, XVWarpInit_InputConfigs::bytes_per_pixel, XVWarpInit_InputConfigs::ctr_pts, DISTORTION_ARBITRARY, XVWarpInitVector_Hw::filter_table_addr_0, XVWarpInit_InputConfigs::filter_table_addr_0, XVWarpInitVector_Hw::filter_table_addr_1, XVWarpInit_InputConfigs::filter_table_addr_1, XVWarpInit_InputConfigs::h, XVWarpInitVector_Hw::height, XVWarpInit_InputConfigs::height, XVWarpInitVector_Hw::height_Q4, XVWarpInitVector_Hw::interm_x, XVWarpInit_ArbParam::interm_x, XVWarpInitVector_Hw::interm_y, XVWarpInit_ArbParam::interm_y, XVWarpInitVector_Hw::k_post, XVWarpInit_InputConfigs::k_post, XVWarpInitVector_Hw::k_pre, XVWarpInit_InputConfigs::k_pre, XVWarpInitVector_Hw::num_ctrl_pts, XVWarpInit_InputConfigs::num_ctrl_pts, XV_warp_init::NumDescriptors, REMAP_FIX_ACC, XVWarpInitVector_Hw_Aligned::remap_nextaddr, XV_warp_init::RemapVectorDesc_BaseAddr, XVWarpInitVector_Hw::src_ctrl_x_pts, XVWarpInit_ArbParam::src_ctrl_x_pts, XVWarpInitVector_Hw::src_ctrl_y_pts, XVWarpInit_ArbParam::src_ctrl_y_pts, XVWarpInitVector_Hw::src_tangents_x, XVWarpInit_ArbParam::src_tangents_x, XVWarpInitVector_Hw::src_tangents_y, XVWarpInit_ArbParam::src_tangents_y, XVWarpInitVector_Hw::warp_type, XVWarpInit_InputConfigs::warp_type, XVWarpInitVector_Hw::width, XVWarpInit_InputConfigs::width, XVWarpInitVector_Hw::width_Q4.
Referenced by main.
int XVWarpInit_start_with_desc(XV_warp_init *InstancePtr, u32 descnum)
This function starts the IP core with a selected descriptor configuration.
InstancePtr is a pointer to core instance to be worked upon descnum is the descriptor number with which configurations the IP { desc.k_pre = ConfigPtr->k_pre; desc.k_post = ConfigPtr->k_post; XVWarpInit_OneTimeCalcs(&desc, ConfigPtr->h); } XVWarpInit_SetDescriptor(descptr, &desc);return XST_SUCCESS; }/* This function starts the IP core with a selected descriptor configuration. InstancePtr is a pointer to core instance to be worked upon descnum is the descriptor number with which configurations the IP shall start XST_SUCCESS if IP core start successful XST_FAILURE if selected descriptor number is not valid.
References XV_warp_init::NumDescriptors, XVWarpInitVector_Hw_Aligned::remap_nextaddr, XV_warp_init::RemapVectorDesc_BaseAddr, XV_warp_init_Set_desc_addr, XV_warp_init_Set_maxi_read_write, XV_warp_init_Start.
Referenced by main.
void XVWarpInit_Stop(XV_warp_init *InstancePtr)
This function stops the core instance.
InstancePtr is a pointer to core instance to be worked upon none
References XV_WAIT_FOR_FLUSH_DONE, XV_WAIT_FOR_FLUSH_DONE_TIMEOUT, XV_warp_init_Get_FlushDone, XV_warp_init_SetFlushbit.