xv_warp_init_l2.c
PTR_OFFSET_SZ
Size of pointer offset in bytes.
REMAP_FIX_ACC
Fixed-point accuracy bits for remap calculations.
Referenced by XVWarpInit_ProgramDescriptor.
REMAP_DESCRIPTOR_SIZE
Descriptor size in bytes.
REMAP_ADDR_WIDTH
Address width in bits.
XV_WAIT_FOR_FLUSH_DONE
Wait iteration count for flush done.
Referenced by XVWarpInit_Stop.
XV_WAIT_FOR_FLUSH_DONE_TIMEOUT
Timeout for flush done in microseconds.
Referenced by XVWarpInit_Stop.
align_up
Macro to align a number up to the nearest multiple of align.
typedef u16 offset_t
Offset type definition.
static void * XVWarpInit_aligned_malloc(size_t align, size_t size)
This function creates aligned void memory pointer.
align is the alignment size. size it is the size of pointer to be created. ptr is memory pointer to be returned.
static void XVWarpInit_aligned_free(void *ptr)
This function frees the allocated aligned memory.
ptr is the memory pointer to be free. None
static void XVWarpInit_OneTimeCalcs(XVWarpInitVector_Hw *initvector_hw, int *proj_trans)
This function does all the ontime calculation for lens distortion which to be done for each input configs change.
initvector_hw is the pointer to initialization vector. proj_trans is the pointer to projective transformation input. None
static void XVWarpInit_OnetimeCalcsArbt(XVWarpInit_ArbParam *arbitrary_param, unsigned short fr_width, unsigned short fr_height)
This function does all the ontime calculation for Arbitrary distortion which to be done for each input configs change.
arbitrary_param is the pointer to input Arbitrary parameters. fr_width is the frame width. fr_height is the frame height. None
static void XVWarpInit_SetDescriptor(XVWarpInitVector_Hw_Aligned *descptr, XVWarpInitVector_Hw *initvector_hw)
This function sets the descriptor into hw.
descptr is pointer to hardware memory(DDR). initvector_hw is the descriptor data to be set in DDR. None
static void XVWarpInit_AllocArbMem(XVWarpInit_ArbParam *arbitrary_param, int grid_size, u16 fr_width, u16 fr_height)
This function allocates the required memory for intermediate arbitrary variables/calculation.
arbitrary_param is the pointer to input Arbitrary parameters. grid_size is the grid size for the arbitrary distortion. fr_width is the frame width. fr_height is the frame height. None
static int XVWarpInit_ParseMeshInfo(XVWarpInit_ArbParam *arbitrary_param, XVWarpInit_ArbParam_MeshInfo *ctrl_pts, short fr_width, short fr_height)
This function parses the input mesinfo for arbitrary distartion.
arbitrary_param is the pointer to input Arbitrary parameters. ctrl_pts is the pointer to the input mesh information. fr_width is the frame width. fr_height is the frame height. XST_SUCCESS if the mesh information parsing successful XST_FAILURE if the control points are not valid in the given mesh information.
static int XVWarpInit_ValidateInputConfigs(XV_warp_init *InstancePtr, XVWarpInit_InputConfigs *ConfigPtr)
This function validates the given configs with IP core configs.
InstancePtr is a pointer to core instance to be worked upon. ConfigPtr is the pointer to input configuration XST_SUCCESS if the validation is successful XST_FAILURE is any input config is invalid.
void XVWarpInit_EnableInterrupts(XV_warp_init *InstancePtr, u32 Mask)
This function Enables the Interrupts for the core instance.
InstancePtr is a pointer to core instance to be worked upon Mask is the Interrupt enable mask none
References XV_warp_init_InterruptEnable, XV_warp_init_InterruptGlobalEnable.
Referenced by main.
int XVWarpInit_SetNumOfDescriptors(XV_warp_init *InstancePtr, u32 num_desc)
This function creates the descriptors.
InstancePtr is a pointer to core instance to be worked upon num_desc is the number of descriptors to be created XST_SUCCESS if Descriptors created successfully XST_FAILURE if Descriptors creation failed
References XV_warp_init_Config::axi_mm_data_width, XV_warp_init::config, XV_warp_init::NumDescriptors, XVWarpInitVector_Hw_Aligned::remap_nextaddr, XV_warp_init::RemapVectorDesc_BaseAddr.
Referenced by main.
void XVWarpInit_ClearNumOfDescriptors(XV_warp_init *InstancePtr)
This function clears and de-allocates all the descriptors.
InstancePtr is a pointer to core instance to be worked upon none
References XV_warp_init::NumDescriptors, XVWarpInitVector_Hw_Aligned::remap_nextaddr, XV_warp_init::RemapVectorDesc_BaseAddr.
Referenced by main.
int XVWarpInit_ProgramDescriptor(XV_warp_init *InstancePtr, u32 Descnum, XVWarpInit_InputConfigs *ConfigPtr)
This function programs a descriptor with given configurations.
InstancePtr is a pointer to core instance to be worked upon Descnum is the descriptor number which to be configured ConfigPtr is the input configuration pointer which to be configured into the descriptor XST_SUCCESS if programming descriptor is successful XST_FAILURE if input configurations are not valid.
References XVWarpInitVector_Hw::bytes_per_pixel, XVWarpInit_InputConfigs::bytes_per_pixel, XVWarpInit_InputConfigs::ctr_pts, DISTORTION_ARBITRARY, XVWarpInitVector_Hw::filter_table_addr_0, XVWarpInit_InputConfigs::filter_table_addr_0, XVWarpInitVector_Hw::filter_table_addr_1, XVWarpInit_InputConfigs::filter_table_addr_1, XVWarpInit_InputConfigs::h, XVWarpInitVector_Hw::height, XVWarpInit_InputConfigs::height, XVWarpInitVector_Hw::height_Q4, XVWarpInitVector_Hw::interm_x, XVWarpInit_ArbParam::interm_x, XVWarpInitVector_Hw::interm_y, XVWarpInit_ArbParam::interm_y, XVWarpInitVector_Hw::k_post, XVWarpInit_InputConfigs::k_post, XVWarpInitVector_Hw::k_pre, XVWarpInit_InputConfigs::k_pre, XVWarpInitVector_Hw::num_ctrl_pts, XVWarpInit_InputConfigs::num_ctrl_pts, XV_warp_init::NumDescriptors, REMAP_FIX_ACC, XVWarpInitVector_Hw_Aligned::remap_nextaddr, XV_warp_init::RemapVectorDesc_BaseAddr, XVWarpInitVector_Hw::src_ctrl_x_pts, XVWarpInit_ArbParam::src_ctrl_x_pts, XVWarpInitVector_Hw::src_ctrl_y_pts, XVWarpInit_ArbParam::src_ctrl_y_pts, XVWarpInitVector_Hw::src_tangents_x, XVWarpInit_ArbParam::src_tangents_x, XVWarpInitVector_Hw::src_tangents_y, XVWarpInit_ArbParam::src_tangents_y, XVWarpInitVector_Hw::warp_type, XVWarpInit_InputConfigs::warp_type, XVWarpInitVector_Hw::width, XVWarpInit_InputConfigs::width, XVWarpInitVector_Hw::width_Q4.
Referenced by main.
int XVWarpInit_start_with_desc(XV_warp_init *InstancePtr, u32 descnum)
This function starts the IP core with a selected descriptor configuration.
InstancePtr is a pointer to core instance to be worked upon descnum is the descriptor number with which configurations the IP { desc.k_pre = ConfigPtr->k_pre; desc.k_post = ConfigPtr->k_post; XVWarpInit_OneTimeCalcs(&desc, ConfigPtr->h); } XVWarpInit_SetDescriptor(descptr, &desc);return XST_SUCCESS; }/* This function starts the IP core with a selected descriptor configuration. InstancePtr is a pointer to core instance to be worked upon descnum is the descriptor number with which configurations the IP shall start XST_SUCCESS if IP core start successful XST_FAILURE if selected descriptor number is not valid.
References XV_warp_init::NumDescriptors, XVWarpInitVector_Hw_Aligned::remap_nextaddr, XV_warp_init::RemapVectorDesc_BaseAddr, XV_warp_init_Set_desc_addr, XV_warp_init_Set_maxi_read_write, XV_warp_init_Start.
Referenced by main.
void XVWarpInit_Stop(XV_warp_init *InstancePtr)
This function stops the core instance.
InstancePtr is a pointer to core instance to be worked upon none
References XV_WAIT_FOR_FLUSH_DONE, XV_WAIT_FOR_FLUSH_DONE_TIMEOUT, XV_warp_init_Get_FlushDone, XV_warp_init_SetFlushbit.
static void estimate_projtrans_Qbits(int *proj_trans, short *h, int *h_trans, unsigned char *h_Qbits)
This function converts projective transform coefficients to fixed-point format.
Processes the first two columns (6 coefficients) and last column (3 coefficients) of a 3x3 projective transformation matrix separately with different Q-bit ranges. proj_trans is the 3x3 projective transformation matrix (9 elements). h is output fixed-point representation of first 2 columns (6 coefficients). h_trans is output fixed-point representation of last column (3 coefficients). h_Qbits is output Q-bit position for each of the 6 h coefficients. None
static void apply_arbt_warp_line(short *knots_x, short *knots_y, int grid_pts, int len, int *remap_row)
apply_arbt_warp_line - Apply arbitrary warp transformation to a line using cubic interpolation
knots_x Array of x-coordinate control points (knots) knots_y Array of y-coordinate control points (knots) grid_pts Number of grid points/control points len Length of the line to process (number of output samples) remap_row Output array containing the warped x-coordinates for each pixel This function applies a cubic spline-based warp transformation to remap pixel positions along a horizontal line. It uses piecewise cubic interpolation with control points (knots) to compute non-linear coordinate transformations.The algorithm: Iterates through each output pixel positionFor each segment between consecutive knots, computes cubic coefficients (a0, a1, a2, a3)Uses fixed-point arithmetic with bit-shifting for efficient inverse calculationsEvaluates the cubic polynomial at each point to determine the remapped x-coordinate None Results are stored in the remap_row output array.
static void creat_src_tangents(unsigned short *src_ctrl_pts, int *src_tangents, short fr_size, short grid_size)
This function creates tangent vectors for source control points.
It calculates tangent values used in cubic spline interpolation for arbitrary warp transformations. The function handles two cases: uniform and non-uniform control point spacing. src_ctrl_pts Pointer to source control points array to be populated src_tangents Pointer to output tangent values array (stores 3 values per segment) fr_size Frame size (width or height depending on usage) grid_size Number of grid divisions/control point segments None. Results are stored in src_ctrl_pts and src_tangents arrays Note: Tangent values are encoded as 16-bit value with 8-bit Q-bit position stored in lower 8 bits, and the actual tangent coefficient in upper bits