xv_hdmitxss.h
ANSI_COLOR_RED
ANSI color code for red.
Referenced by XV_HdmiTxSs_LogDisplay.
ANSI_COLOR_YELLOW
ANSI color code for yellow.
ANSI_COLOR_RESET
ANSI color code to reset.
Referenced by XV_HdmiTxSs_LogDisplay.
XV_HdmiTxSs_LogEvent
Log event none.
XV_HdmiTxSs_HpdToleranceType
Leading edge tolerance.
XV_HdmiTxSs_HdcpProtocol
No content protection.
XV_HdmiTxSs_HandlerType
Handler for connect event.
HDMITXSS_H
< prevent circular inclusions by using protection macros
XV_HDMITXSS_LOG_ENABLE
typedef void(* XV_HdmiTxSs_Callback)(void *CallbackRef))(void *CallbackRef)
Callback type for interrupt.
CallbackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. None. None.
XV_HdmiTxSs_Config* XV_HdmiTxSs_LookupConfig(UINTPTR BaseAddress)
This function looks for the device configuration based on the unique device ID.
The table XV_HdmiTxSs_ConfigTable[] contains the configuration information for each instance of the device in the system. DeviceId is the unique device ID of the device being looked up A pointer to the configuration table entry corresponding to the given device ID, or NULL if no match is found
u32 XV_HdmiTxSs_GetDrvIndex(UINTPTR BaseAddress)
This function returns the Index number of config table using BaseAddress.
A pointer to the instance structure Base address of the instance Index number of the config table
void XV_HdmiTxSS_SetHdmiMode(XV_HdmiTxSs *InstancePtr)
This function sets the core into HDMI mode.
InstancePtr is a pointer to the HDMI TX Subsystem
References XV_HdmiTxSs::HdmiTxPtr.
Referenced by XV_HdmiTxSs_SetVideoStreamType, XV_HdmiTxSs_SubcoreInitHdmiTx.
void XV_HdmiTxSS_SetDviMode(XV_HdmiTxSs *InstancePtr)
This function sets the core into DVI mode.
InstancePtr is a pointer to the HDMI TX Subsystem
References XV_HdmiTxSs::HdmiTxPtr.
Referenced by XV_HdmiTxSs_SetVideoStreamType.
void XV_HdmiTxSS_HdmiTxIntrHandler(XV_HdmiTxSs *InstancePtr)
This function calls the interrupt handler for HDMI TX.
InstancePtr is a pointer to the HDMI TX Subsystem
References XV_HdmiTxSs::HdmiTxPtr.
int XV_HdmiTxSs_CfgInitialize(XV_HdmiTxSs *InstancePtr, XV_HdmiTxSs_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the video subsystem and included sub-cores.
This function must be called prior to using the subsystem. Initialization includes setting up the instance data for top level as well as all included sub-core therein, and ensuring the hardware is in a known stable state. InstancePtr is a pointer to the Subsystem instance to be worked on. CfgPtr points to the configuration structure associated with the subsystem instance. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if initialization is successful else XST_FAILURE
References XV_HdmiTxSs::AppMajVer, XV_HdmiTxSs::AppMinVer, XV_HdmiTxSs::AudioInfoframe, XV_HdmiTxSs::AVIInfoframe, XV_HdmiTxSs_Config::AxiLiteClkFreq, XV_HdmiTxSs_Config::BaseAddress, XV_HdmiTxSs::Config, XV_HdmiTxSs::DrmInfoframe, XV_HdmiTxSs::HdcpProtocol, XV_HdmiTxSs::HdmiTxPtr, XV_HdmiTxSs::IsReady, XV_HdmiTxSs::VSIF, XV_HdmiTxSs::VtcPtr, XV_HDMITXSS_HDCP_BOTH, XV_HDMITXSS_HDCP_NONE, XV_HdmiTxSs_Reset, XV_HdmiTxSs_SubcoreInitHdmiTx, XV_HdmiTxSs_SubcoreInitVtc.
void XV_HdmiTxSS_SetAppVersion(XV_HdmiTxSs *InstancePtr, u8 maj, u8 min)
This function will set the major and minor application version in TXSs struct.
InstancePtr is a pointer to the XV_HdmiTxSs core instance. maj is the major version of the application. min is the minor version of the application. void. None.
References XV_HdmiTxSs::AppMajVer, XV_HdmiTxSs::AppMinVer.
void XV_HdmiTxSs_Start(XV_HdmiTxSs *InstancePtr)
This function starts the HDMI TX subsystem including all sub-cores that are included in the processing pipeline for a given use-case.
Video pipe is started from back to front InstancePtr is a pointer to the Subsystem instance to be worked on. None Cores are started only if the corresponding start flag in the scratch pad memory is set. This allows to selectively start only those cores included in the processing chain
References XV_HDMITXSS_LOG_EVT_START, XV_HdmiTxSs_LogWrite.
void XV_HdmiTxSs_Stop(XV_HdmiTxSs *InstancePtr)
This function stops the HDMI TX subsystem including all sub-cores Stop the video pipe starting from front to back.
InstancePtr is a pointer to the Subsystem instance to be worked on. None
References XV_HdmiTxSs::VtcPtr, XV_HDMITXSS_LOG_EVT_STOP, XV_HdmiTxSs_LogWrite.
void XV_HdmiTxSs_Reset(XV_HdmiTxSs *InstancePtr)
This function resets the video subsystem sub-cores.
There are 2 reset networks within the subsystem For cores that are on AXIS interfaceFor cores that are on AXI-MM interface InstancePtr is a pointer to the Subsystem instance to be worked on. None
References XV_HDMITXSS_LOG_EVT_RESET, XV_HdmiTxSs_LogWrite, XV_HdmiTxSs_SYSRST, XV_HdmiTxSs_TXCore_LRST, XV_HdmiTxSs_TXCore_VRST, XV_HdmiTxSs_VRST.
Referenced by XV_HdmiTxSs_CfgInitialize.
void XV_HdmiTxSs_TXCore_VRST(XV_HdmiTxSs *InstancePtr, u8 Reset)
This function asserts or releases the Internal Video reset of the HDMI subcore within the subsystem.
InstancePtr is a pointer to the Subsystem instance to be worked on. Reset is a flag to assert (TRUE) or release (FALSE) the reset. None
References XV_HdmiTxSs::HdmiTxPtr.
Referenced by XV_HdmiTxSs_RefClockChangeInit, XV_HdmiTxSs_Reset.
void XV_HdmiTxSs_TXCore_LRST(XV_HdmiTxSs *InstancePtr, u8 Reset)
This function asserts or releases the Internal Link reset of the HDMI subcore within the subsystem.
InstancePtr is a pointer to the Subsystem instance to be worked on. Reset is a flag to assert (TRUE) or release (FALSE) the reset. None
References XV_HdmiTxSs::HdmiTxPtr.
Referenced by XV_HdmiTxSs_RefClockChangeInit, XV_HdmiTxSs_Reset.
void XV_HdmiTxSs_VRST(XV_HdmiTxSs *InstancePtr, u8 Reset)
This function asserts or releases the video reset of other blocks within the subsystem.
InstancePtr is a pointer to the Subsystem instance to be worked on. Reset is a flag to assert (TRUE) or release (FALSE) the reset. None
References XV_HdmiTxSs::HdmiTxPtr.
Referenced by XV_HdmiTxSs_RefClockChangeInit, XV_HdmiTxSs_Reset.
void XV_HdmiTxSs_SYSRST(XV_HdmiTxSs *InstancePtr, u8 Reset)
This function asserts or releases the system reset of other blocks within the subsystem.
InstancePtr is a pointer to the Subsystem instance to be worked on. Reset is a flag to assert (TRUE) or release (FALSE) the reset. None
References XV_HdmiTxSs::HdmiTxPtr.
Referenced by XV_HdmiTxSs_RefClockChangeInit, XV_HdmiTxSs_Reset.
void XV_HdmiTxSs_SetGcpAvmuteBit(XV_HdmiTxSs *InstancePtr)
This function sets the HDMI TX AUX GCP register AVMUTE bit.
InstancePtr is a pointer to the Subsystem instance to be worked on. None
References XV_HdmiTxSs::HdmiTxPtr.
void XV_HdmiTxSs_ClearGcpAvmuteBit(XV_HdmiTxSs *InstancePtr)
This function clears the HDMI TX AUX GCP register AVMUTE bit.
InstancePtr is a pointer to the Subsystem instance to be worked on. None
References XV_HdmiTxSs::HdmiTxPtr.
void XV_HdmiTxSs_SetGcpClearAvmuteBit(XV_HdmiTxSs *InstancePtr)
This function sets the HDMI TX AUX GCP register CLEAR_AVMUTE bit.
InstancePtr is a pointer to the Subsystem instance to be worked on. None
References XV_HdmiTxSs::HdmiTxPtr.
void XV_HdmiTxSs_ClearGcpClearAvmuteBit(XV_HdmiTxSs *InstancePtr)
This function clears the HDMI TX AUX GCP register CLEAR_AVMUTE bit.
InstancePtr is a pointer to the Subsystem instance to be worked on. None
References XV_HdmiTxSs::HdmiTxPtr.
int XV_HdmiTxSs_SetCallback(XV_HdmiTxSs *InstancePtr, XV_HdmiTxSs_HandlerType HandlerType, void *CallbackFuncPtr, void *CallbackRef)
This function installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function Type ----------------------- --------------------------------------------- (XV_HDMITXSS_HANDLER_CONNECT) HpdCallback (XV_HDMITXSS_HANDLER_VS) VsCallback (XV_HDMITXSS_HANDLER_STREAM_DOWN) StreamDownCallback (XV_HDMITXSS_HANDLER_STREAM_UP) StreamUpCallback (XV_HDMITXSS_HANDLER_BRDGOVERFLOW) BrdgOverflowCallback (XV_HDMITXSS_HANDLER_BRDGUNDERFLOW) BrdgUnderflowCallback (XV_HDMITXSS_HANDLER_HDCP_AUTHENTICATED) (XV_HDMITXSS_HANDLER_HDCP_DOWNSTREAM_TOPOLOGY_AVAILABLE) (XV_HDMITXSS_HANDLER_HDCP_UNAUTHENTICATED) InstancePtr is a pointer to the HDMI TX Subsystem instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XV_HdmiTxSs::BrdgOverflowCallback, XV_HdmiTxSs::BrdgOverflowRef, XV_HdmiTxSs::BrdgUnderflowCallback, XV_HdmiTxSs::BrdgUnderflowRef, XV_HdmiTxSs::BrdgUnlockedCallback, XV_HdmiTxSs::BrdgUnlockedRef, XV_HdmiTxSs::ConnectCallback, XV_HdmiTxSs::ConnectRef, XV_HdmiTxSs::StreamDownCallback, XV_HdmiTxSs::StreamDownRef, XV_HdmiTxSs::StreamUpCallback, XV_HdmiTxSs::StreamUpRef, XV_HdmiTxSs::ToggleCallback, XV_HdmiTxSs::ToggleRef, XV_HdmiTxSs::VsCallback, XV_HdmiTxSs::VsRef, XV_HDMITXSS_HANDLER_BRDGOVERFLOW, XV_HDMITXSS_HANDLER_BRDGUNDERFLOW, XV_HDMITXSS_HANDLER_BRDGUNLOCK, XV_HDMITXSS_HANDLER_CONNECT, XV_HDMITXSS_HANDLER_HDCP_AUTHENTICATED, XV_HDMITXSS_HANDLER_HDCP_DOWNSTREAM_TOPOLOGY_AVAILABLE, XV_HDMITXSS_HANDLER_HDCP_UNAUTHENTICATED, XV_HDMITXSS_HANDLER_STREAM_DOWN, XV_HDMITXSS_HANDLER_STREAM_UP, XV_HDMITXSS_HANDLER_TOGGLE, XV_HDMITXSS_HANDLER_VS.
int XV_HdmiTxSs_ReadEdid(XV_HdmiTxSs *InstancePtr, u8 *BufferPtr)
This function reads the HDMI Sink EDID.
InstancePtr is a pointer to the XV_HdmiTxSs instance. Buffer is a pointer to the buffer where EDID data will be stored. XST_SUCCESS if EDID read was successful.XST_FAILURE if EDID read failed. None.
References XV_HdmiTxSs::HdmiTxPtr, XV_HdmiTxSs::IsStreamConnected.
int XV_HdmiTxSs_ReadEdidSegment(XV_HdmiTxSs *InstancePtr, u8 *Buffer, u8 segment)
This function reads one block from the HDMI Sink EDID.
InstancePtr is a pointer to the XV_HdmiTxSs instance. Buffer is a pointer to the buffer where EDID data will be stored. segment is the EDID segment number to read. XST_SUCCESS if EDID read was successful.XST_FAILURE if EDID read failed. None.
References XV_HdmiTxSs::HdmiTxPtr, XV_HdmiTxSs::IsStreamConnected.
Referenced by XV_HdmiTxSs_ShowEdid.
void XV_HdmiTxSs_ShowEdid(XV_HdmiTxSs *InstancePtr)
This function shows the HDMI source edid.
InstancePtr is a pointer to the XV_HdmiTxSs instance. None. None.
References XV_HdmiTxSs::IsStreamConnected, XV_HdmiTxSs_ReadEdidSegment.
void XV_HdmiTxSs_SetScrambler(XV_HdmiTxSs *InstancePtr, u8 Enable)
This function enables / disables the TX scrambler.
InstancePtr is a pointer to the Subsystem instance to be worked on. Enable TRUE:Enable scrambler FALSE:Disable scrambler None. The scrambler setting will revert to the default behavior during the next stream configuration (scrambler is enabled for HDMI 2.0 video and disabled when the video is of HDMI 1.4 or lower)
References XV_HdmiTxSs::HdmiTxPtr, XV_HdmiTxSs_SetVideoStreamScramblingFlag.
void XV_HdmiTxSs_StreamStart(XV_HdmiTxSs *InstancePtr)
This function starts the HDMI TX stream.
InstancePtr is a pointer to the XV_HdmiTxSs instance. None. None.
References XV_HdmiTxSs::HdmiTxPtr, XV_HDMITXSS_LOG_EVT_STREAMSTART, XV_HdmiTxSs_LogWrite.
void XV_HdmiTxSs_SendAuxInfoframe(XV_HdmiTxSs *InstancePtr, void *AuxPtr)
This function sends audio info frames.
InstancePtr is a pointer to the XV_HdmiTxSs instance. Aux is a pointer to the auxiliary data to send. None. None.
References XV_HdmiTxSs::HdmiTxPtr.
u32 XV_HdmiTxSs_SendGenericAuxInfoframe(XV_HdmiTxSs *InstancePtr, void *AuxPtr)
This function sends generic info frames.
InstancePtr is a pointer to the XV_HdmiTxSs instance. Aux is a pointer to the auxiliary data structure. XST_SUCCESS if infoframes transmitted successfully.XST_FAILURE if AUX FIFO is full. None.
References XV_HdmiTxSs::HdmiTxPtr.
void XV_HdmiTxSs_SetAudioChannels(XV_HdmiTxSs *InstancePtr, u8 AudioChannels)
This function Sets the HDMI TX SS number of active audio channels.
InstancePtr pointer to XV_HdmiTxSs instance AudioChannels None. None.
References XV_HdmiTxSs::AudioChannels, XV_HdmiTxSs::AudioInfoframe, XV_HdmiTxSs::HdmiTxPtr, XV_HDMITXSS_LOG_EVT_SETAUDIOCHANNELS, XV_HdmiTxSs_LogWrite.
void XV_HdmiTxSs_AudioMute(XV_HdmiTxSs *InstancePtr, u8 Enable)
This function set HDMI TX audio parameters.
InstancePtr is a pointer to the XV_HdmiTxSs instance. Enable 0: Unmute the audio 1: Mute the audio. None. None.
References XV_HdmiTxSs::HdmiTxPtr, XV_HDMITXSS_LOG_EVT_AUDIOMUTE, XV_HDMITXSS_LOG_EVT_AUDIOUNMUTE, XV_HdmiTxSs_LogWrite.
Referenced by XV_HdmiTxSs_SetVideoStreamType.
void XV_HdmiTxSs_SetAudioFormat(XV_HdmiTxSs *InstancePtr, XV_HdmiTx_AudioFormatType format)
This function Sets the HDMI TX SS Audio Format.
InstancePtr pointer to XV_HdmiTxSs instance format 1:HBR 0:L-PCM None. None.
References XV_HdmiTxSs::HdmiTxPtr.
XV_HdmiTx_AudioFormatType XV_HdmiTxSs_GetAudioFormat(XV_HdmiTxSs *InstancePtr)
This function gets the active audio format.
InstancePtr is a pointer to the XV_HdmiTxSs core instance. Active audio format of HDMI Tx Subsystem None.
References XV_HdmiTxSs::HdmiTxPtr.
XHdmiC_Aux* XV_HdmiTxSs_GetAuxiliary(XV_HdmiTxSs *InstancePtr)
This function returns the pointer to HDMI TX SS Aux structure.
InstancePtr pointer to XV_HdmiTxSs instance XVidC_VideoStream pointer None.
References XV_HdmiTxSs::HdmiTxPtr.
XHdmiC_AVI_InfoFrame* XV_HdmiTxSs_GetAviInfoframe(XV_HdmiTxSs *InstancePtr)
This function returns the pointer to HDMI TX SS AVI InfoFrame structure.
InstancePtr pointer to XV_HdmiTxSs instance XHdmiC_AVI_InfoFrame pointer None.
References XV_HdmiTxSs::AVIInfoframe.
XHdmiC_AudioInfoFrame* XV_HdmiTxSs_GetAudioInfoframe(XV_HdmiTxSs *InstancePtr)
This function returns the pointer to HDMI TX SS Audio InfoFrame structure.
InstancePtr pointer to XV_HdmiTxSs instance XHdmiC_AudioInfoFrame pointer None.
References XV_HdmiTxSs::AudioInfoframe.
XHdmiC_VSIF* XV_HdmiTxSs_GetVSIF(XV_HdmiTxSs *InstancePtr)
This function returns the pointer to HDMI TX SS Vendor Specific InfoFrame structure.
InstancePtr pointer to XV_HdmiTxSs instance XHdmiC_VSIF pointer None.
References XV_HdmiTxSs::VSIF.
u32 XV_HdmiTxSs_SetStream(XV_HdmiTxSs *InstancePtr, XVidC_VideoMode VideoMode, XVidC_ColorFormat ColorFormat, XVidC_ColorDepth Bpc, XVidC_3DInfo *Info3D)
This function set HDMI TX subsystem stream parameters.
InstancePtr is a pointer to the XV_HdmiTxSs instance. VideoMode is the video mode to set. ColorFormat is the color format to set. Bpc is the bits per component (color depth). Info3D is a pointer to 3D information structure. Calculated TMDS Clock None.
References XV_HdmiTxSs::Config, XV_HdmiTxSs::HdmiTxPtr, XV_HdmiTxSs_Config::Ppc, XV_HDMITXSS_LOG_EVT_SETSTREAM, XV_HdmiTxSs_LogWrite.
XVidC_VideoStream* XV_HdmiTxSs_GetVideoStream(XV_HdmiTxSs *InstancePtr)
This function returns the pointer to HDMI TX SS video stream.
InstancePtr pointer to XV_HdmiTxSs instance XVidC_VideoStream pointer None.
References XV_HdmiTxSs::HdmiTxPtr.
Referenced by XV_HdmiTxSS_SetBackgroundColor.
void XV_HdmiTxSs_SetVideoStream(XV_HdmiTxSs *InstancePtr, XVidC_VideoStream VidStream)
This function Sets the HDMI TX SS video stream.
InstancePtr pointer to XV_HdmiTxSs instance VidStream is the video stream properties to set. None. None.
References XV_HdmiTxSs::HdmiTxPtr.
void XV_HdmiTxSs_SetSamplingRate(XV_HdmiTxSs *InstancePtr, u8 SamplingRate)
This function Sets the HDMI TX SS video Identification code.
InstancePtr pointer to XV_HdmiTxSs instance SamplingRate Value None. None.
References XV_HdmiTxSs::SamplingRate.
void XV_HdmiTxSs_SetVideoIDCode(XV_HdmiTxSs *InstancePtr, u8 Vic)
This function Sets the HDMI TX SS video Identification code.
InstancePtr pointer to XV_HdmiTxSs instance Vic is the Video Identification Code value to set. None. None.
References XV_HdmiTxSs::HdmiTxPtr.
void XV_HdmiTxSs_SetVideoStreamType(XV_HdmiTxSs *InstancePtr, u8 StreamType)
This function Sets the HDMI TX SS video stream type.
InstancePtr pointer to XV_HdmiTxSs instance StreamType specifies the stream type (1:HDMI 0:DVI) None. None.
References XV_HdmiTxSs_AudioMute, XV_HdmiTxSS_SetDviMode, XV_HdmiTxSS_SetHdmiMode.
void XV_HdmiTxSs_SetVideoStreamScramblingFlag(XV_HdmiTxSs *InstancePtr, u8 IsScrambled)
This function Sets the HDMI TX SS video stream type.
InstancePtr pointer to XV_HdmiTxSs instance IsScrambled 1:IsScrambled 0: not Scrambled None. None.
References XV_HdmiTxSs::HdmiTxPtr.
Referenced by XV_HdmiTxSs_SetScrambler.
void XV_HdmiTxSs_SetVideoStreamScramblingOverrideFlag(XV_HdmiTxSs *InstancePtr, u8 OverrideScramble)
This function Sets the HDMI TX SS video stream scrambling behaviour.
Setting OverrideScramble to true will force enabling/disabling scrambling function based on the value of IsScrambled flag. InstancePtr pointer to XV_HdmiTxSs instance OverrideScramble 0: Scrambling is always enabled for HDMI 2.0 resolutions and is enabled /or disabled for HDMI 1.4 resolutions based on IsScrambled value 1: Enable scrambling if IsScrambled is TRUE and disable scrambling if IsScrambled is FALSE None. None.
References XV_HdmiTxSs::HdmiTxPtr.
void XV_HdmiTxSs_SetTmdsClockRatio(XV_HdmiTxSs *InstancePtr, u8 Ratio)
This function Sets the HDMI TX SS TMDS Cock Ratio.
InstancePtr pointer to XV_HdmiTxSs instance Ratio 0 - 1/10, 1 - 1/40 None. None.
References XV_HdmiTxSs::HdmiTxPtr.
u32 XV_HdmiTxSs_GetTmdsClockFreqHz(XV_HdmiTxSs *InstancePtr)
This function returns the HDMI TX SS TMDS clock frequency.
InstancePtr pointer to XV_HdmiTxSs instance TMDS Clock frequency in Hz. None.
References XV_HdmiTxSs::HdmiTxPtr.
int XV_HdmiTxSs_DetectHdmi20(XV_HdmiTxSs *InstancePtr)
This function detects connected sink is a HDMI 2.0/HDMI 1.4 sink device.
InstancePtr is a pointer to the XV_HdmiTxSs core instance. XST_SUCCESS if HDMI 2.0XST_FAILURE if HDMI 1.4 None.
References XV_HdmiTxSs::HdmiTxPtr.
void XV_HdmiTxSs_RefClockChangeInit(XV_HdmiTxSs *InstancePtr)
This function is called when HDMI TX SS TMDS clock changes.
InstancePtr is a pointer to the XV_HdmiTxSs instance. None. None.
References XV_HdmiTxSs::HdmiTxPtr, XV_HdmiTxSs_SYSRST, XV_HdmiTxSs_TXCore_LRST, XV_HdmiTxSs_TXCore_VRST, XV_HdmiTxSs_VRST.
void XV_HdmiTxSs_ReportInfo(XV_HdmiTxSs *InstancePtr)
This function prints the HDMI TX SS subcore versions.
InstancePtr is a pointer to the XV_HdmiTxSs instance. None. None.
int XV_HdmiTxSs_IsStreamUp(XV_HdmiTxSs *InstancePtr)
This function checks if the video stream is up.
InstancePtr is a pointer to the XV_HdmiTxSs instance. TRUE if stream is up.FALSE if stream is down. None.
References XV_HdmiTxSs::IsStreamUp.
int XV_HdmiTxSs_IsStreamConnected(XV_HdmiTxSs *InstancePtr)
This function checks if the interface is connected.
InstancePtr is a pointer to the XV_HdmiTxSs instance. TRUE if the interface is connected.FALSE if the interface is not connected. None.
References XV_HdmiTxSs::IsStreamConnected.
int XV_HdmiTxSs_IsStreamToggled(XV_HdmiTxSs *InstancePtr)
This function checks if the interface has toggled.
InstancePtr is a pointer to the XV_HdmiTxSs instance. TRUE if the interface HPD has toggled.FALSE if the interface HPD has not toggled. None.
References XV_HdmiTxSs::IsStreamToggled.
u8 XV_HdmiTxSs_IsSinkHdcp14Capable(XV_HdmiTxSs *InstancePtr)
This function determines if the connected HDMI sink is HDCP 1.4 capable.
InstancePtr is a pointer to the XV_HdmiTxSs instance. TRUE if sink is HDCP 1.4 capable and ready to authenticate.FALSE if sink does not support HDCP 1.4 or is not ready.
u8 XV_HdmiTxSs_IsSinkHdcp22Capable(XV_HdmiTxSs *InstancePtr)
This function determines if the connected HDMI sink is HDCP 2.2 capable.
InstancePtr is a pointer to the XV_HdmiTxSs instance. TRUE if sink is HDCP 2.2 capable and ready to authenticate.FALSE if sink does not support HDCP 2.2 or is not ready.
void XV_HdmiTxSs_SetDefaultPpc(XV_HdmiTxSs *InstancePtr, u8 Id)
This function will set the default in HDF.
InstancePtr is a pointer to the XV_HdmiTxSs core instance. Id is the XV_HdmiTxSs ID to operate on. None. None.
References XV_HdmiTxSs::Config, XV_HdmiTxSs_Config::Ppc.
void XV_HdmiTxSs_SetPpc(XV_HdmiTxSs *InstancePtr, u8 Id, u8 Ppc)
This function will set PPC specified by user.
InstancePtr is a pointer to the XV_HdmiTxSs core instance. Id is the XV_HdmiTxSs ID to operate on. Ppc is the PPC to be set. None. None.
References XV_HdmiTxSs::Config, XV_HdmiTxSs_Config::Ppc.
void XV_HdmiTxSs_LogReset(XV_HdmiTxSs *InstancePtr)
This function will reset the driver's logging mechanism.
InstancePtr is a pointer to the xv_hdmitxss core instance. None. None.
References XV_HdmiTxSs_Log::HeadIndex, XV_HdmiTxSs::Log, XV_HdmiTxSs_Log::TailIndex.
void XV_HdmiTxSs_LogWrite(XV_HdmiTxSs *InstancePtr, XV_HdmiTxSs_LogEvent Evt, u8 Data)
This function will insert an event in the driver's logginc mechanism.
InstancePtr is a pointer to the XV_HdmiTxSs core instance. Evt is the event type to log. Data is the associated data for the event. None. None.
References XV_HdmiTxSs_Log::DataBuffer, XV_HdmiTxSs_Log::HeadIndex, XV_HdmiTxSs::Log, XV_HdmiTxSs_Log::TailIndex, XV_HDMITXSS_LOG_EVT_DUMMY.
Referenced by XV_HdmiTxSs_AudioMute, XV_HdmiTxSs_Reset, XV_HdmiTxSs_SetAudioChannels, XV_HdmiTxSs_SetStream, XV_HdmiTxSs_Start, XV_HdmiTxSs_Stop, XV_HdmiTxSs_StreamStart, XV_HdmiTxSs_SubcoreInitHdmiTx, XV_HdmiTxSs_SubcoreInitVtc.
u16 XV_HdmiTxSs_LogRead(XV_HdmiTxSs *InstancePtr)
This function will read the last event from the log.
InstancePtr is a pointer to the XV_HdmiTxSs core instance. The log data. None.
References XV_HdmiTxSs_Log::DataBuffer, XV_HdmiTxSs_Log::HeadIndex, XV_HdmiTxSs::Log, XV_HdmiTxSs_Log::TailIndex.
Referenced by XV_HdmiTxSs_LogDisplay.
void XV_HdmiTxSs_LogDisplay(XV_HdmiTxSs *InstancePtr)
This function will print the entire log.
InstancePtr is a pointer to the XV_HdmiTxSs core instance. None. None.
References ANSI_COLOR_RED, ANSI_COLOR_RESET, XV_HDMITXSS_LOG_EVT_AUDIOMUTE, XV_HDMITXSS_LOG_EVT_AUDIOUNMUTE, XV_HDMITXSS_LOG_EVT_BRDG_UNLOCKED, XV_HDMITXSS_LOG_EVT_CONNECT, XV_HDMITXSS_LOG_EVT_DISCONNECT, XV_HDMITXSS_LOG_EVT_HDCP14_AUTHREQ, XV_HDMITXSS_LOG_EVT_HDCP14_INIT, XV_HDMITXSS_LOG_EVT_HDCP22_AUTHREQ, XV_HDMITXSS_LOG_EVT_HDCP22_INIT, XV_HDMITXSS_LOG_EVT_HDCPTIMER_INIT, XV_HDMITXSS_LOG_EVT_HDMITX_INIT, XV_HDMITXSS_LOG_EVT_NONE, XV_HDMITXSS_LOG_EVT_PIX_REPEAT_ERR, XV_HDMITXSS_LOG_EVT_RESET, XV_HDMITXSS_LOG_EVT_SETAUDIOCHANNELS, XV_HDMITXSS_LOG_EVT_SETSTREAM, XV_HDMITXSS_LOG_EVT_START, XV_HDMITXSS_LOG_EVT_STOP, XV_HDMITXSS_LOG_EVT_STREAMDOWN, XV_HDMITXSS_LOG_EVT_STREAMSTART, XV_HDMITXSS_LOG_EVT_STREAMUP, XV_HDMITXSS_LOG_EVT_TOGGLE, XV_HDMITXSS_LOG_EVT_VTC_INIT, XV_HDMITXSS_LOG_EVT_VTC_RES_ERR, XV_HdmiTxSs_LogRead.
void XV_HdmiTxSS_MaskEnable(XV_HdmiTxSs *InstancePtr)
This function will enable the video masking.
InstancePtr is a pointer to the XV_HdmiTxSs core instance. None. None.
References XV_HdmiTxSs::HdmiTxPtr.
Referenced by XV_HdmiTxSS_SetBackgroundColor.
void XV_HdmiTxSS_MaskDisable(XV_HdmiTxSs *InstancePtr)
This function will disable the video masking.
InstancePtr is a pointer to the XV_HdmiTxSs core instance. None. None.
References XV_HdmiTxSs::HdmiTxPtr.
void XV_HdmiTxSS_MaskNoise(XV_HdmiTxSs *InstancePtr, u8 Enable)
This function will enable or disable the noise in the video mask.
InstancePtr is a pointer to the XV_HdmiTxSs core instance. Enable specifies TRUE/FALSE value to either enable or disable the Noise. None. None.
References XV_HdmiTxSs::HdmiTxPtr.
Referenced by XV_HdmiTxSS_SetBackgroundColor.
void XV_HdmiTxSS_MaskSetRed(XV_HdmiTxSs *InstancePtr, u16 Value)
This function will set the red component in the video mask.
InstancePtr is a pointer to the XV_HdmiTxSs core instance. Value specifies the video mask value set to red component None. None.
References XV_HdmiTxSs::HdmiTxPtr.
Referenced by XV_HdmiTxSS_SetBackgroundColor.
void XV_HdmiTxSS_MaskSetGreen(XV_HdmiTxSs *InstancePtr, u16 Value)
This function will set the green component in the video mask.
InstancePtr is a pointer to the XV_HdmiTxSs core instance. Value specifies the video mask value set to green component None. None.
References XV_HdmiTxSs::HdmiTxPtr.
Referenced by XV_HdmiTxSS_SetBackgroundColor.
void XV_HdmiTxSS_MaskSetBlue(XV_HdmiTxSs *InstancePtr, u16 Value)
This function will set the blue component in the video mask.
InstancePtr is a pointer to the XV_HdmiTxSs core instance. Value specifies the video mask value set to blue component None. None.
References XV_HdmiTxSs::HdmiTxPtr.
Referenced by XV_HdmiTxSS_SetBackgroundColor.
void XV_HdmiTxSS_SetBackgroundColor(XV_HdmiTxSs *InstancePtr, XVMaskColorId ColorId)
This function configures the background color for Video Masking Feature.
InstancePtr is a pointer to the core instance to be worked on. ColorId is the background color requested None
References XV_HdmiTxSs::HdmiTxPtr, XV_HdmiTxSs_GetVideoStream, XV_HdmiTxSS_MaskEnable, XV_HdmiTxSS_MaskNoise, XV_HdmiTxSS_MaskSetBlue, XV_HdmiTxSS_MaskSetGreen, XV_HdmiTxSS_MaskSetRed.
u8 XV_HdmiTxSS_IsMasked(XV_HdmiTxSs *InstancePtr)
This function will get the current video mask mode.
InstancePtr is a pointer to the XV_HdmiTxSs core instance. Current mode. 0 = Video masking is disabled 1 = Video masking is enabled None.
References XV_HdmiTxSs::HdmiTxPtr.
void XV_HdmiTxSS_SetHpdTolerance(XV_HdmiTxSs *InstancePtr, XV_HdmiTxSs_HpdToleranceType Type, u16 ToleranceVal)
This function will Configure Timegrid based on the tolerance value for HPD and Toggle event.
InstancePtr is a pointer to the XV_HdmiTxSs core instance. Type is the tolerance type. ToleranceVal is the tolerance value to be applied. void. None.
References XV_HdmiTxSs_Config::BaseAddress, XV_HdmiTxSs::Config, XV_HDMITXSS_LAGGING_TOLERANCE, XV_HDMITXSS_LEADING_TOLERANCE.