xv_hdmitxss_log.c
void XV_HdmiTxSs_LogReset(XV_HdmiTxSs *InstancePtr)
This function will reset the driver's logging mechanism.
InstancePtr is a pointer to the xv_hdmitxss core instance. None. None.
References XV_HdmiTxSs_Log::HeadIndex, XV_HdmiTxSs::Log, XV_HdmiTxSs_Log::TailIndex.
void XV_HdmiTxSs_LogWrite(XV_HdmiTxSs *InstancePtr, XV_HdmiTxSs_LogEvent Evt, u8 Data)
This function will insert an event in the driver's logginc mechanism.
InstancePtr is a pointer to the XV_HdmiTxSs core instance. Evt is the event type to log. Data is the associated data for the event. None. None.
References XV_HdmiTxSs_Log::DataBuffer, XV_HdmiTxSs_Log::HeadIndex, XV_HdmiTxSs::Log, XV_HdmiTxSs_Log::TailIndex, XV_HDMITXSS_LOG_EVT_DUMMY.
Referenced by XV_HdmiTxSs_AudioMute, XV_HdmiTxSs_Reset, XV_HdmiTxSs_SetAudioChannels, XV_HdmiTxSs_SetStream, XV_HdmiTxSs_Start, XV_HdmiTxSs_Stop, XV_HdmiTxSs_StreamStart, XV_HdmiTxSs_SubcoreInitHdmiTx, XV_HdmiTxSs_SubcoreInitVtc.
u16 XV_HdmiTxSs_LogRead(XV_HdmiTxSs *InstancePtr)
This function will read the last event from the log.
InstancePtr is a pointer to the XV_HdmiTxSs core instance. The log data. None.
References XV_HdmiTxSs_Log::DataBuffer, XV_HdmiTxSs_Log::HeadIndex, XV_HdmiTxSs::Log, XV_HdmiTxSs_Log::TailIndex.
Referenced by XV_HdmiTxSs_LogDisplay.
void XV_HdmiTxSs_LogDisplay(XV_HdmiTxSs *InstancePtr)
This function will print the entire log.
InstancePtr is a pointer to the XV_HdmiTxSs core instance. None. None.
References ANSI_COLOR_RED, ANSI_COLOR_RESET, XV_HDMITXSS_LOG_EVT_AUDIOMUTE, XV_HDMITXSS_LOG_EVT_AUDIOUNMUTE, XV_HDMITXSS_LOG_EVT_BRDG_UNLOCKED, XV_HDMITXSS_LOG_EVT_CONNECT, XV_HDMITXSS_LOG_EVT_DISCONNECT, XV_HDMITXSS_LOG_EVT_HDCP14_AUTHREQ, XV_HDMITXSS_LOG_EVT_HDCP14_INIT, XV_HDMITXSS_LOG_EVT_HDCP22_AUTHREQ, XV_HDMITXSS_LOG_EVT_HDCP22_INIT, XV_HDMITXSS_LOG_EVT_HDCPTIMER_INIT, XV_HDMITXSS_LOG_EVT_HDMITX_INIT, XV_HDMITXSS_LOG_EVT_NONE, XV_HDMITXSS_LOG_EVT_PIX_REPEAT_ERR, XV_HDMITXSS_LOG_EVT_RESET, XV_HDMITXSS_LOG_EVT_SETAUDIOCHANNELS, XV_HDMITXSS_LOG_EVT_SETSTREAM, XV_HDMITXSS_LOG_EVT_START, XV_HDMITXSS_LOG_EVT_STOP, XV_HDMITXSS_LOG_EVT_STREAMDOWN, XV_HDMITXSS_LOG_EVT_STREAMSTART, XV_HDMITXSS_LOG_EVT_STREAMUP, XV_HDMITXSS_LOG_EVT_TOGGLE, XV_HDMITXSS_LOG_EVT_VTC_INIT, XV_HDMITXSS_LOG_EVT_VTC_RES_ERR, XV_HdmiTxSs_LogRead.