AXIDMA
XAXIDMA_DMA_TO_DEVICE
XAXIDMA_DEVICE_TO_DMA
XAXIDMA_BD_MINIMUM_ALIGNMENT
Minimum byte alignment requirement for descriptors to satisfy both hardware/software needs.
Referenced by XAxiDma_BdRingCreate.
XAXIDMA_MICROMODE_MIN_BUF_ALIGN
Minimum byte alignment requirement for buffer address in Micro DMA mode.
Referenced by XAxiDma_BdSetBufAddrMicroMode, XAxiDma_SimpleTransfer.
XAXIDMA_MCHAN_MAX_TRANSFER_LEN
XAXIDMA_TX_OFFSET
TX channel registers base offset.
Referenced by XAxiDma_CfgInitialize, XAxiDma_Reset.
XAXIDMA_RX_OFFSET
RX channel registers base offset.
Referenced by XAxiDma_Busy, XAxiDma_CfgInitialize, XAxiDma_Reset, XAxiDma_SelectCyclicMode, XAxiDma_SelectKeyHole.
XAXIDMA_CR_OFFSET
Channel control.
Referenced by XAxiDma_BdRingDumpRegs, XAxiDma_BdRingGetCoalesce, XAxiDma_BdRingSetCoalesce, XAxiDma_Pause, XAxiDma_Reset, XAxiDma_ResetIsDone, XAxiDma_SelectCyclicMode, XAxiDma_SelectKeyHole, XAxiDma_SimpleTransfer, XAxiDma_StartBdRingHw.
XAXIDMA_SR_OFFSET
Status.
Referenced by XAxiDma_BdRingDumpRegs, XAxiDma_Busy, XAxiDma_SimpleTransfer.
XAXIDMA_CDESC_OFFSET
Current descriptor pointer.
Referenced by XAxiDma_BdRingDumpRegs, XAxiDma_UpdateBdRingCDesc.
XAXIDMA_CDESC_MSB_OFFSET
Current descriptor pointer.
Referenced by XAxiDma_UpdateBdRingCDesc.
XAXIDMA_TDESC_OFFSET
Tail descriptor pointer.
Referenced by XAxiDma_BdRingDumpRegs, XAxiDma_BdRingToHw, XAxiDma_StartBdRingHw.
XAXIDMA_TDESC_MSB_OFFSET
Tail descriptor pointer.
Referenced by XAxiDma_BdRingToHw, XAxiDma_StartBdRingHw.
XAXIDMA_SRCADDR_OFFSET
Simple mode source address pointer.
Referenced by XAxiDma_SimpleTransfer.
XAXIDMA_SRCADDR_MSB_OFFSET
Simple mode source address pointer.
Referenced by XAxiDma_SimpleTransfer.
XAXIDMA_DESTADDR_OFFSET
Simple mode destination address pointer.
Referenced by XAxiDma_SimpleTransfer.
XAXIDMA_DESTADDR_MSB_OFFSET
Simple mode destination address pointer.
Referenced by XAxiDma_SimpleTransfer.
XAXIDMA_BUFFLEN_OFFSET
Tail descriptor pointer.
Referenced by XAxiDma_SimpleTransfer.
XAXIDMA_SGCTL_OFFSET
SG Control Register.
XAXIDMA_RX_CDESC0_OFFSET
Multi-Channel DMA Descriptor Offsets.
Rx Current Descriptor 0
Referenced by XAxiDma_BdRingDumpRegs, XAxiDma_UpdateBdRingCDesc.
XAXIDMA_RX_CDESC0_MSB_OFFSET
Rx Current Descriptor 0.
Referenced by XAxiDma_UpdateBdRingCDesc.
XAXIDMA_RX_TDESC0_OFFSET
Rx Tail Descriptor 0.
Referenced by XAxiDma_BdRingDumpRegs, XAxiDma_BdRingToHw, XAxiDma_StartBdRingHw.
XAXIDMA_RX_TDESC0_MSB_OFFSET
Rx Tail Descriptor 0.
Referenced by XAxiDma_BdRingToHw, XAxiDma_StartBdRingHw.
XAXIDMA_RX_NDESC_OFFSET
Rx Next Descriptor Offset.
Referenced by XAxiDma_BdRingDumpRegs, XAxiDma_BdRingToHw, XAxiDma_StartBdRingHw, XAxiDma_UpdateBdRingCDesc.
XAXIDMA_CR_RUNSTOP_MASK
Start/stop DMA channel.
Referenced by XAxiDma_Pause, XAxiDma_SimpleTransfer, XAxiDma_StartBdRingHw.
XAXIDMA_CR_RESET_MASK
Reset DMA engine.
Referenced by XAxiDma_Reset, XAxiDma_ResetIsDone.
XAXIDMA_CR_KEYHOLE_MASK
Keyhole feature.
Referenced by XAxiDma_SelectKeyHole.
XAXIDMA_CR_CYCLIC_MASK
Cyclic Mode.
Referenced by XAxiDma_SelectCyclicMode.
XAXIDMA_HALTED_MASK
DMA channel halted.
Referenced by XAxiDma_SimpleTransfer.
XAXIDMA_IDLE_MASK
DMA channel idle.
Referenced by XAxiDma_Busy.
XAXIDMA_ERR_INTERNAL_MASK
Datamover internal err.
XAXIDMA_ERR_SLAVE_MASK
Datamover slave err.
XAXIDMA_ERR_DECODE_MASK
Datamover decode err.
XAXIDMA_ERR_SG_INT_MASK
SG internal err.
XAXIDMA_ERR_SG_SLV_MASK
SG slave err.
XAXIDMA_ERR_SG_DEC_MASK
SG decode err.
XAXIDMA_ERR_ALL_MASK
All errors.
XAXIDMA_IRQ_IOC_MASK
Completion intr.
XAXIDMA_IRQ_DELAY_MASK
Delay interrupt.
XAXIDMA_IRQ_ERROR_MASK
Error interrupt.
XAXIDMA_IRQ_ALL_MASK
All interrupts.
Referenced by main, XAxiDma_SimplePollExample.
XAXIDMA_DELAY_MASK
Delay timeout counter.
Referenced by XAxiDma_BdRingGetCoalesce, XAxiDma_BdRingSetCoalesce.
XAXIDMA_COALESCE_MASK
Coalesce counter.
Referenced by XAxiDma_BdRingGetCoalesce, XAxiDma_BdRingSetCoalesce.
XAXIDMA_DELAY_SHIFT
XAXIDMA_COALESCE_SHIFT
XAXIDMA_BD_NDESC_OFFSET
Next descriptor pointer.
Referenced by XAxiDma_BdRingCheck, XAxiDma_BdRingCreate, XAxiDma_DumpBd.
XAXIDMA_BD_NDESC_MSB_OFFSET
Next descriptor pointer.
Referenced by XAxiDma_BdRingCreate.
XAXIDMA_BD_BUFA_OFFSET
Buffer address.
Referenced by XAxiDma_BdSetBufAddr, XAxiDma_BdSetBufAddrMicroMode, XAxiDma_DumpBd.
XAXIDMA_BD_BUFA_MSB_OFFSET
Buffer address.
XAXIDMA_BD_MCCTL_OFFSET
Multichannel Control Fields.
Referenced by XAxiDma_DumpBd.
XAXIDMA_BD_STRIDE_VSIZE_OFFSET
2D Transfer Sizes
Referenced by XAxiDma_DumpBd.
XAXIDMA_BD_CTRL_LEN_OFFSET
Control/buffer length.
Referenced by XAxiDma_BdRingFromHw, XAxiDma_BdRingToHw, XAxiDma_BdSetCtrl, XAxiDma_BdSetLength, XAxiDma_DumpBd.
XAXIDMA_BD_STS_OFFSET
Status.
Referenced by XAxiDma_BdRingClone, XAxiDma_BdRingFromHw, XAxiDma_BdRingToHw, XAxiDma_DumpBd, XAxiDma_StartBdRingHw.
XAXIDMA_BD_USR0_OFFSET
User IP specific word0.
Referenced by XAxiDma_BdGetAppWord, XAxiDma_BdSetAppWord, XAxiDma_DumpBd.
XAXIDMA_BD_USR1_OFFSET
User IP specific word1.
Referenced by XAxiDma_DumpBd.
XAXIDMA_BD_USR2_OFFSET
User IP specific word2.
Referenced by XAxiDma_DumpBd.
XAXIDMA_BD_USR3_OFFSET
User IP specific word3.
Referenced by XAxiDma_DumpBd.
XAXIDMA_BD_USR4_OFFSET
User IP specific word4.
Referenced by XAxiDma_DumpBd.
XAXIDMA_BD_ID_OFFSET
Sw ID.
Referenced by XAxiDma_DumpBd.
XAXIDMA_BD_HAS_STSCNTRL_OFFSET
Whether has stscntrl strm.
Referenced by XAxiDma_BdGetAppWord, XAxiDma_BdRingCreate, XAxiDma_BdSetAppWord, XAxiDma_DumpBd.
XAXIDMA_BD_HAS_DRE_OFFSET
Whether has DRE.
Referenced by XAxiDma_BdRingCreate, XAxiDma_BdSetBufAddr, XAxiDma_DumpBd.
XAXIDMA_BD_HAS_DRE_MASK
Whether has DRE mask.
Referenced by XAxiDma_BdSetBufAddr.
XAXIDMA_BD_WORDLEN_MASK
Whether has DRE mask.
Referenced by XAxiDma_BdSetBufAddr.
XAXIDMA_BD_HAS_DRE_SHIFT
Whether has DRE shift.
Referenced by XAxiDma_BdRingCreate.
XAXIDMA_BD_WORDLEN_SHIFT
Whether has DRE shift.
XAXIDMA_BD_START_CLEAR
Offset to start clear.
Referenced by XAxiDma_BdRingClone.
XAXIDMA_BD_BYTES_TO_CLEAR
BD specific bytes to be cleared.
Referenced by XAxiDma_BdRingClone.
XAXIDMA_BD_NUM_WORDS
Total number of words for one BD.
XAXIDMA_BD_HW_NUM_BYTES
Number of bytes hw used.
XAXIDMA_LAST_APPWORD
XAXIDMA_BD_CTRL_TXSOF_MASK
First tx packet.
Referenced by XAxiDma_BdRingToHw.
XAXIDMA_BD_CTRL_TXEOF_MASK
Last tx packet.
Referenced by XAxiDma_BdRingFromHw, XAxiDma_BdRingToHw.
XAXIDMA_BD_CTRL_ALL_MASK
All control bits.
Referenced by XAxiDma_BdSetCtrl.
XAXIDMA_BD_STS_COMPLETE_MASK
Completed.
Referenced by XAxiDma_BdRingClone, XAxiDma_BdRingFromHw, XAxiDma_BdRingToHw, XAxiDma_StartBdRingHw.
XAXIDMA_BD_STS_DEC_ERR_MASK
Decode error.
XAXIDMA_BD_STS_SLV_ERR_MASK
Slave error.
XAXIDMA_BD_STS_INT_ERR_MASK
Internal err.
XAXIDMA_BD_STS_ALL_ERR_MASK
All errors.
XAXIDMA_BD_STS_RXSOF_MASK
First rx pkt.
XAXIDMA_BD_STS_RXEOF_MASK
Last rx pkt.
Referenced by XAxiDma_BdRingFromHw.
XAXIDMA_BD_STS_ALL_MASK
All status bits.
XAXIDMA_BD_TDEST_FIELD_MASK
XAXIDMA_BD_TID_FIELD_MASK
XAXIDMA_BD_TUSER_FIELD_MASK
XAXIDMA_BD_ARCACHE_FIELD_MASK
XAXIDMA_BD_ARUSER_FIELD_MASK
XAXIDMA_BD_TDEST_FIELD_SHIFT
XAXIDMA_BD_TID_FIELD_SHIFT
XAXIDMA_BD_TUSER_FIELD_SHIFT
XAXIDMA_BD_ARCACHE_FIELD_SHIFT
XAXIDMA_BD_ARUSER_FIELD_SHIFT
XAXIDMA_BD_STRIDE_FIELD_MASK
XAXIDMA_BD_VSIZE_FIELD_MASK
XAXIDMA_BD_STRIDE_FIELD_SHIFT
XAXIDMA_BD_VSIZE_FIELD_SHIFT
typedef struct XAxiDma XAxiDma
The XAxiDma driver instance data.
An instance must be allocated for each DMA engine in use.
typedef u32 XAxiDma_Bd[XAXIDMA_BD_NUM_WORDS][XAXIDMA_BD_NUM_WORDS]
The XAxiDma_Bd is the type for a buffer descriptor (BD).
XAxiDma_Config XAxiDma_ConfigTable[][]
static int XAxiDma_Start(XAxiDma *InstancePtr)
static int XAxiDma_Started(XAxiDma *InstancePtr)
int XAxiDma_CfgInitialize(XAxiDma *InstancePtr, XAxiDma_Config *Config)
This function initializes a DMA engine.
This function must be called prior to using a DMA engine. Initializing a engine includes setting up the register base address, setting up the instance data, and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the DMA engine instance to be worked on. Config is a pointer to an XAxiDma_Config structure. It contains the information about the hardware build, including base address,and whether status control stream (StsCntrlStrm), MM2S and S2MM are included in the build. XST_SUCCESS for successful initializationXST_INVALID_PARAM if pointer to the configuration structure is NULLXST_DMA_ERROR if reset operation failed at the end of initialization We assume the hardware building tool will check and error out for a hardware build that has no transfer channels.
References XAxiDma::AddrWidth, XAxiDma_Config::AddrWidth, XAxiDma_Config::BaseAddr, XAxiDma_BdRing::ChanBase, XAxiDma_Config::HasMm2S, XAxiDma_Config::HasMm2SDRE, XAxiDma_Config::HasS2Mm, XAxiDma_Config::HasS2MmDRE, XAxiDma_Config::HasSg, XAxiDma_BdRing::HasStsCntrlStrm, XAxiDma_Config::HasStsCntrlStrm, XAxiDma_BdRing::IsRxChannel, XAxiDma_Config::MicroDmaMode, XAxiDma_Config::Mm2SBurstSize, XAxiDma_Config::Mm2SDataWidth, XAxiDma_Config::Mm2sNumChannels, XAxiDma_BdRing::RingIndex, XAxiDma_BdRing::RunState, XAxiDma_Config::S2MmBurstSize, XAxiDma_Config::S2MmDataWidth, XAxiDma_Config::S2MmNumChannels, XAxiDma_Config::SgLengthWidth, XAxiDma_Reset, XAxiDma_ResetIsDone, XAXIDMA_RX_OFFSET, XAXIDMA_TX_OFFSET.
Referenced by AxiDMASelfTestExample, main, XAxiDma_SimplePollExample.
void XAxiDma_Reset(XAxiDma *InstancePtr)
Reset both TX and RX channels of a DMA engine.
Reset one channel resets the whole AXI DMA engine.Any DMA transaction in progress will finish gracefully before engine starts reset. Any other transactions that have been submitted to hardware will be discarded by the hardware. InstancePtr is a pointer to the DMA engine instance to be worked on. None After the reset: All interrupts are disabled.Engine is halted
References XAxiDma_BdRing::RunState, XAxiDma_BdRingSnapShotCurrBd, XAXIDMA_CR_OFFSET, XAXIDMA_CR_RESET_MASK, XAxiDma_GetRxIndexRing, XAxiDma_GetTxRing, XAxiDma_HasSg, XAXIDMA_RX_OFFSET, XAXIDMA_TX_OFFSET, XAxiDma_WriteReg.
Referenced by main, XAxiDma_CfgInitialize, XAxiDma_Selftest.
int XAxiDma_ResetIsDone(XAxiDma *InstancePtr)
Check whether reset is done.
InstancePtr is a pointer to the DMA engine instance to be worked on. 1 if reset is done. 0 if reset is not done None
References XAxiDma_BdRing::ChanBase, XAXIDMA_CR_OFFSET, XAXIDMA_CR_RESET_MASK, XAxiDma_GetRxRing, XAxiDma_GetTxRing, XAxiDma_ReadReg.
Referenced by XAxiDma_CfgInitialize, XAxiDma_Selftest.
int XAxiDma_Pause(XAxiDma *InstancePtr)
Pause DMA transactions on both channels.
If the engine is running and doing transfers, this function does not stop the DMA transactions immediately, because then hardware will throw away our previously queued transfers. All submitted transfers will finish. Transfers submitted after this function will not start until XAxiDma_BdRingStart() or XAxiDma_Resume() is called. InstancePtr is a pointer to the DMA engine instance to be worked on. XST_SUCCESS if successfulXST_NOT_SGDMA, if the driver instance is not initialized None
References XAxiDma_BdRing::ChanBase, XAxiDma_BdRing::RunState, XAXIDMA_CR_OFFSET, XAXIDMA_CR_RUNSTOP_MASK, XAxiDma_GetRxIndexRing, XAxiDma_GetTxRing, XAxiDma_HasSg, XAxiDma_ReadReg, XAxiDma_WriteReg.
int XAxiDma_Resume(XAxiDma *InstancePtr)
Resume DMA transactions on both channels.
InstancePtr is a pointer to the DMA engine instance to be worked on. XST_SUCCESS for successXST_NOT_SGDMA if the driver instance has not been initializedXST_DMA_ERROR if one of the channels fails to start None
References XAxiDma_BdRing::RunState, XAxiDma_BdRingStart, XAxiDma_GetRxIndexRing, XAxiDma_GetTxRing, XAxiDma_HasSg.
u32 XAxiDma_Busy(XAxiDma *InstancePtr, int Direction)
This function checks whether specified DMA channel is busy.
InstancePtr is the driver instance we are working on Direction is DMA transfer direction, valid values are XAXIDMA_DMA_TO_DEVICE.XAXIDMA_DEVICE_TO_DMA. - TRUE if channel is busy FALSE if channel is idle None.
References XAXIDMA_IDLE_MASK, XAxiDma_ReadReg, XAXIDMA_RX_OFFSET, XAXIDMA_SR_OFFSET.
Referenced by XAxiDma_SimplePollExample, XAxiDma_SimpleTransfer.
int XAxiDma_SelectKeyHole(XAxiDma *InstancePtr, int Direction, int Select)
This function Enable or Disable KeyHole Feature.
InstancePtr is the driver instance we are working on Direction is DMA transfer direction, valid values are XAXIDMA_DMA_TO_DEVICE.XAXIDMA_DEVICE_TO_DMA. Select is the option to enable (TRUE) or disable (FALSE). - XST_SUCCESS for success None.
References XAXIDMA_CR_KEYHOLE_MASK, XAXIDMA_CR_OFFSET, XAxiDma_ReadReg, XAXIDMA_RX_OFFSET, XAxiDma_WriteReg.
int XAxiDma_SelectCyclicMode(XAxiDma *InstancePtr, int Direction, int Select)
This function Enable or Disable Cyclic Mode Feature.
InstancePtr is the driver instance we are working on Direction is DMA transfer direction, valid values are XAXIDMA_DMA_TO_DEVICE.XAXIDMA_DEVICE_TO_DMA. Select is the option to enable (TRUE) or disable (FALSE). - XST_SUCCESS for success None.
References XAXIDMA_CR_CYCLIC_MASK, XAXIDMA_CR_OFFSET, XAxiDma_ReadReg, XAXIDMA_RX_OFFSET, XAxiDma_WriteReg.
u32 XAxiDma_SimpleTransfer(XAxiDma *InstancePtr, UINTPTR BuffAddr, u32 Length, int Direction)
This function does one simple transfer submission.
It checks in the following sequence: if engine is busy, cannot submitif engine is in SG mode , cannot submit InstancePtr is the pointer to the driver instance BuffAddr is the address of the source/destination buffer Length is the length of the transfer Direction is DMA transfer direction, valid values are XAXIDMA_DMA_TO_DEVICE.XAXIDMA_DEVICE_TO_DMA. XST_SUCCESS for success of submissionXST_FAILURE for submission failure, maybe caused by: Another simple transfer is still goingXST_INVALID_PARAM if:Length out of valid range [1:8M] Or, address not aligned when DRE is not built in This function is used only when system is configured as Simple mode.
References XAxiDma::AddrWidth, XAxiDma_BdRing::ChanBase, XAXIDMA_BUFFLEN_OFFSET, XAxiDma_Busy, XAXIDMA_CR_OFFSET, XAXIDMA_CR_RUNSTOP_MASK, XAXIDMA_DESTADDR_MSB_OFFSET, XAXIDMA_DESTADDR_OFFSET, XAXIDMA_HALTED_MASK, XAxiDma_HasSg, XAXIDMA_MICROMODE_MIN_BUF_ALIGN, XAxiDma_ReadReg, XAXIDMA_SR_OFFSET, XAXIDMA_SRCADDR_MSB_OFFSET, XAXIDMA_SRCADDR_OFFSET, XAxiDma_WriteReg.
Referenced by main, XAxiDma_SimplePollExample.
XAxiDma_Config * XAxiDma_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
A table contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration table entry corresponding to the given device ID/BaseAddress, or NULL if no match is found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XAxiDma_Config::Name.
Referenced by AxiDMASelfTestExample, main, XAxiDma_SimplePollExample.
int XAxiDma_Selftest(XAxiDma *InstancePtr)
Runs a self-test on the driver/device.
This test perform a reset of the DMA device and checks the device is coming out of reset or not InstancePtr is a pointer to the XAxiDma instance. XST_SUCCESS if self-test was successful XST_FAILURE if the device is not coming out of reset. None.
References XAxiDma_Reset, XAxiDma_ResetIsDone.
Referenced by AxiDMASelfTestExample.
int XAxiDma_BdSetLength(XAxiDma_Bd *BdPtr, u32 LenBytes, u32 LengthMask)
Set the length field for the given BD.
Length has to be non-zero and less than LengthMask.For TX channels, the value passed in should be the number of bytes to transmit from the TX buffer associated with the given BD.For RX channels, the value passed in should be the size of the RX buffer associated with the given BD in bytes. This is to notify the RX channel the capability of the RX buffer to avoid buffer overflow.The actual receive length can be equal or smaller than the specified length. The actual transfer length will be updated by the hardware in the XAXIDMA_BD_STS_OFFSET word in the BD. BdPtr is the BD to operate on. LenBytes is the requested transfer length LengthMask is the maximum transfer length XST_SUCCESS for successXST_INVALID_PARAM for invalid BD length This function can be used only when DMA is in SG mode
References XAXIDMA_BD_CTRL_LEN_OFFSET, XAxiDma_BdRead, XAxiDma_BdWrite.
u32 XAxiDma_BdSetBufAddr(XAxiDma_Bd *BdPtr, UINTPTR Addr)
Set the BD's buffer address.
BdPtr is the BD to operate on Addr is the address to set XST_SUCCESS if buffer address set successfullyXST_INVALID_PARAM if hardware has no DRE and address is not aligned This function can be used only when DMA is in SG mode
References XAXIDMA_BD_BUFA_OFFSET, XAXIDMA_BD_HAS_DRE_MASK, XAXIDMA_BD_HAS_DRE_OFFSET, XAXIDMA_BD_WORDLEN_MASK, XAxiDma_BdRead, XAxiDma_BdWrite, XAxiDma_BdWrite64.
u32 XAxiDma_BdSetBufAddrMicroMode(XAxiDma_Bd *BdPtr, UINTPTR Addr)
Set the BD's buffer address when configured for Micro Mode.
The buffer address should be 4K aligned. BdPtr is the BD to operate on Addr is the address to set XST_SUCCESS if buffer address set successfullyXST_INVALID_PARAM if hardware has no DRE and address is not aligned This function can be used only when DMA is in SG mode
References XAXIDMA_BD_BUFA_OFFSET, XAxiDma_BdWrite, XAxiDma_BdWrite64, XAXIDMA_MICROMODE_MIN_BUF_ALIGN.
int XAxiDma_BdSetAppWord(XAxiDma_Bd *BdPtr, int Offset, u32 Word)
Set the APP word at the specified APP word offset for a BD.
BdPtr is the BD to operate on. Offset is the offset inside the APP word, it is valid from 0 to 4 Word is the value to set XST_SUCCESS for successXST_INVALID_PARAM under following error conditions: 1) StsCntrlStrm is not built in hardware 2) Offset is not in valid range If the hardware build has C_SG_USE_STSAPP_LENGTH set to 1, then the last APP word, XAXIDMA_LAST_APPWORD, must have non-zero value when AND with 0x7FFFFF. Not doing so will cause the hardware to stall. This function can be used only when DMA is in SG mode
References XAXIDMA_BD_HAS_STSCNTRL_OFFSET, XAXIDMA_BD_USR0_OFFSET, XAxiDma_BdRead, XAxiDma_BdWrite.
u32 XAxiDma_BdGetAppWord(XAxiDma_Bd *BdPtr, int Offset, int *Valid)
Get the APP word at the specified APP word offset for a BD.
BdPtr is the BD to operate on. Offset is the offset inside the APP word, it is valid from 0 to 4 Valid is to tell the caller whether parameters are valid The APP word. Passed in parameter Valid holds 0 for failure, and 1 for success. This function can be used only when DMA is in SG mode
References XAXIDMA_BD_HAS_STSCNTRL_OFFSET, XAXIDMA_BD_USR0_OFFSET, XAxiDma_BdRead.
void XAxiDma_BdSetCtrl(XAxiDma_Bd *BdPtr, u32 Data)
Set the control bits for a BD.
BdPtr is the BD to operate on. Data is the bit value to set None This function can be used only when DMA is in SG mode
References XAXIDMA_BD_CTRL_ALL_MASK, XAXIDMA_BD_CTRL_LEN_OFFSET, XAxiDma_BdRead, XAxiDma_BdWrite.
void XAxiDma_DumpBd(XAxiDma_Bd *BdPtr)
Dump the fields of a BD.
BdPtr is the BD to operate on. None This function can be used only when DMA is in SG mode
References XAXIDMA_BD_BUFA_OFFSET, XAXIDMA_BD_CTRL_LEN_OFFSET, XAXIDMA_BD_HAS_DRE_OFFSET, XAXIDMA_BD_HAS_STSCNTRL_OFFSET, XAXIDMA_BD_ID_OFFSET, XAXIDMA_BD_MCCTL_OFFSET, XAXIDMA_BD_NDESC_OFFSET, XAXIDMA_BD_STRIDE_VSIZE_OFFSET, XAXIDMA_BD_STS_OFFSET, XAXIDMA_BD_USR0_OFFSET, XAXIDMA_BD_USR1_OFFSET, XAXIDMA_BD_USR2_OFFSET, XAXIDMA_BD_USR3_OFFSET, XAXIDMA_BD_USR4_OFFSET, XAxiDma_BdRead.
int XAxiDma_UpdateBdRingCDesc(XAxiDma_BdRing *RingPtr)
Update Current Descriptor.
RingPtr is the Channel instance to be worked on XST_SUCCESS upon successXST_DMA_ERROR if no valid BD available to put into current BD register This function can be used only when DMA is in SG mode
References XAxiDma_BdRing::AllCnt, XAxiDma_BdRing::BdaRestart, XAxiDma_BdRing::ChanBase, XAxiDma_BdRing::IsRxChannel, XAxiDma_BdRing::RingIndex, XAxiDma_BdRing::RunState, XAxiDma_BdHwCompleted, XAxiDma_BdRingHwIsStarted, XAxiDma_BdRingNext, XAXIDMA_CDESC_MSB_OFFSET, XAXIDMA_CDESC_OFFSET, XAXIDMA_DESC_LSB_MASK, XAXIDMA_RX_CDESC0_MSB_OFFSET, XAXIDMA_RX_CDESC0_OFFSET, XAXIDMA_RX_NDESC_OFFSET, XAxiDma_WriteReg.
Referenced by XAxiDma_BdRingStart.
u32 XAxiDma_BdRingCreate(XAxiDma_BdRing *RingPtr, UINTPTR PhysAddr, UINTPTR VirtAddr, u32 Alignment, int BdCount)
Using a memory segment allocated by the caller, This fundtion creates and setup the BD ring.
RingPtr is the BD ring instance to be worked on. PhysAddr is the physical base address of application memory region. VirtAddr is the virtual base address of the application memory region.If address translation is not being utilized, then VirtAddr should be equivalent to PhysAddr. Alignment governs the byte alignment of individual BDs. This function will enforce a minimum alignment of XAXIDMA_BD_MINIMUM_ALIGNMENT bytes with no maximum as long as it is specified as a power of 2. BdCount is the number of BDs to setup in the application memory region. It is assumed the region is large enough to contain the BDs.Refer to the "SGDMA Ring Creation" section in xaxidma.h for more information. The minimum valid value for this parameter is 1. XST_SUCCESS if initialization was successful XST_NO_FEATURE if the provided instance is a non SGDMA type of DMA channel. XST_INVALID_PARAM under any of the following conditions: 1) BdCount is not positive 2) PhysAddr and/or VirtAddr are not aligned to the given Alignment parameter;3) Alignment parameter does not meet minimum requirements or is not a power of 2 value. XST_DMA_SG_LIST_ERROR if the memory segment containing the list spans over address 0x00000000 in virtual address space. This function can be used only when DMA is in SG mode
References XAxiDma_BdRing::AllCnt, XAxiDma_BdRing::BdaRestart, XAxiDma_BdRing::Cyclic, XAxiDma_BdRing::CyclicBd, XAxiDma_BdRing::FirstBdAddr, XAxiDma_BdRing::FirstBdPhysAddr, XAxiDma_BdRing::FreeCnt, XAxiDma_BdRing::FreeHead, XAxiDma_BdRing::HasStsCntrlStrm, XAxiDma_BdRing::HwCnt, XAxiDma_BdRing::HwHead, XAxiDma_BdRing::HwTail, XAxiDma_BdRing::LastBdAddr, XAxiDma_BdRing::Length, XAxiDma_BdRing::PostCnt, XAxiDma_BdRing::PostHead, XAxiDma_BdRing::PreCnt, XAxiDma_BdRing::PreHead, XAxiDma_BdRing::RunState, XAxiDma_BdRing::Separation, XAXIDMA_BD_HAS_DRE_OFFSET, XAXIDMA_BD_HAS_DRE_SHIFT, XAXIDMA_BD_HAS_STSCNTRL_OFFSET, XAXIDMA_BD_MINIMUM_ALIGNMENT, XAXIDMA_BD_NDESC_MSB_OFFSET, XAXIDMA_BD_NDESC_OFFSET, XAxiDma_BdWrite, XAXIDMA_DESC_LSB_MASK.
int XAxiDma_BdRingClone(XAxiDma_BdRing *RingPtr, XAxiDma_Bd *SrcBdPtr)
Clone the given BD into every BD in the ring.
Only the fields offset from XAXIDMA_BD_START_CLEAR are copied, for XAXIDMA_BD_BYTES_TO_CLEAR bytes. This covers: BufferAddr, Control/Buffer length, status, APP words 0 - 4, and software ID fields.This function can be called only when all BDs are in the free group such as immediately after creation of the ring. This prevents modification of BDs while they are in use by hardware or the application. RingPtr is the BD ring instance to be worked on. SrcBdPtr is the source BD template to be cloned into the list. XST_SUCCESS if the list was modified.XST_DMA_SG_NO_LIST if a list has not been created.XST_DEVICE_IS_STARTED if the DMA channel has not been stopped.XST_DMA_SG_LIST_ERROR if some of the BDs in this channel are under hardware or application control. This function can be used only when DMA is in SG mode
References XAxiDma_BdRing::AllCnt, XAxiDma_BdRing::FirstBdAddr, XAxiDma_BdRing::FreeCnt, XAxiDma_BdRing::RunState, XAxiDma_BdRing::Separation, XAXIDMA_BD_BYTES_TO_CLEAR, XAXIDMA_BD_START_CLEAR, XAXIDMA_BD_STS_COMPLETE_MASK, XAXIDMA_BD_STS_OFFSET, XAxiDma_BdRead, XAxiDma_BdWrite.
int XAxiDma_StartBdRingHw(XAxiDma_BdRing *RingPtr)
Start a DMA channel and Allow DMA transactions to commence on a given channel if descriptors are ready to be processed.
After a DMA channel is started, it is not halted, and it is idle (no active DMA transfers). RingPtr is the Channel instance to be worked on XST_SUCCESS upon successXST_DMA_ERROR if no valid BD available to put into current BD register This function can be used only when DMA is in SG mode
References XAxiDma_BdRing::ChanBase, XAxiDma_BdRing::Cyclic, XAxiDma_BdRing::CyclicBd, XAxiDma_BdRing::HwCnt, XAxiDma_BdRing::HwTail, XAxiDma_BdRing::IsRxChannel, XAxiDma_BdRing::RingIndex, XAxiDma_BdRing::RunState, XAXIDMA_BD_STS_COMPLETE_MASK, XAXIDMA_BD_STS_OFFSET, XAxiDma_BdRead, XAxiDma_BdRingHwIsStarted, XAXIDMA_CR_OFFSET, XAXIDMA_CR_RUNSTOP_MASK, XAXIDMA_DESC_LSB_MASK, XAxiDma_ReadReg, XAXIDMA_RX_NDESC_OFFSET, XAXIDMA_RX_TDESC0_MSB_OFFSET, XAXIDMA_RX_TDESC0_OFFSET, XAXIDMA_TDESC_MSB_OFFSET, XAXIDMA_TDESC_OFFSET, XAxiDma_WriteReg.
Referenced by XAxiDma_BdRingStart.
int XAxiDma_BdRingStart(XAxiDma_BdRing *RingPtr)
Start a DMA channel, updates current descriptors and Allow DMA transactions to commence on a given channel if descriptors are ready to be processed.
After a DMA channel is started, it is not halted, and it is idle (no active DMA transfers). RingPtr is the Channel instance to be worked on XST_SUCCESS upon successXST_DMA_ERROR if no valid BD available to put into current BD register This function can be used only when DMA is in SG mode
References XAxiDma_StartBdRingHw, XAxiDma_UpdateBdRingCDesc.
Referenced by XAxiDma_Resume.
int XAxiDma_BdRingSetCoalesce(XAxiDma_BdRing *RingPtr, u32 Counter, u32 Timer)
Set interrupt coalescing parameters for the given descriptor ring channel.
RingPtr is a pointer to the descriptor ring instance to be worked on. Counter sets the packet counter on the channel. Valid range is 1..255.XAXIDMA_NO_CHANGE to leave this setting unchanged. Timer sets the waitbound timer on the channel. Valid range is 0..255. XAXIDMA_NO_CHANGE to leave this setting unchanged. Each unit depend on hardware building parameter C_DLYTMR_RESOLUTION,which is in the range from 0 to 100,000 clock cycles. A value of 0 disables the delay interrupt. XST_SUCCESS if interrupt coalescing settings updatedXST_FAILURE if Counter or Timer parameters are out of range This function can be used only when DMA is in SG mode
References XAxiDma_BdRing::ChanBase, XAXIDMA_COALESCE_MASK, XAXIDMA_CR_OFFSET, XAXIDMA_DELAY_MASK, XAxiDma_ReadReg, XAxiDma_WriteReg.
void XAxiDma_BdRingGetCoalesce(XAxiDma_BdRing *RingPtr, u32 *CounterPtr, u32 *TimerPtr)
Retrieve current interrupt coalescing parameters from the given descriptor ring channel.
RingPtr is a pointer to the descriptor ring instance to be worked on. CounterPtr points to a memory location where the current packet counter will be written. TimerPtr points to a memory location where the current waitbound timer will be written. The passed in parameters, CounterPtr and TimerPtr, holds the references to the return values. This function can be used only when DMA is in SG mode
References XAxiDma_BdRing::ChanBase, XAXIDMA_COALESCE_MASK, XAXIDMA_CR_OFFSET, XAXIDMA_DELAY_MASK, XAxiDma_ReadReg.
int XAxiDma_BdRingAlloc(XAxiDma_BdRing *RingPtr, int NumBd, XAxiDma_Bd **BdSetPtr)
Reserve locations in the BD ring.
The set of returned BDs may be modified in preparation for future DMA transactions. Once the BDs are ready to be submitted to hardware, the application must call XAxiDma_BdRingToHw() in the same order which they were allocated here. Example: NumBd = 2; Status = XDsma_RingBdAlloc(MyRingPtr, NumBd, &MyBdSet); if (Status != XST_SUCCESS) { // Not enough BDs available for the request } CurBd = MyBdSet; for (i=0; i<NumBd; i++) { // Prepare CurBd..... // Onto next BD CurBd = XAxiDma_BdRingNext(MyRingPtr, CurBd); } // Give list to hardware Status = XAxiDma_BdRingToHw(MyRingPtr, NumBd, MyBdSet); A more advanced use of this function may allocate multiple sets of BDs. They must be allocated and given to hardware in the correct sequence: // Legal XAxiDma_BdRingAlloc(MyRingPtr, NumBd1, &MySet1); XAxiDma_BdRingToHw(MyRingPtr, NumBd1, MySet1); // Legal XAxiDma_BdRingAlloc(MyRingPtr, NumBd1, &MySet1); XAxiDma_BdRingAlloc(MyRingPtr, NumBd2, &MySet2); XAxiDma_BdRingToHw(MyRingPtr, NumBd1, MySet1); XAxiDma_BdRingToHw(MyRingPtr, NumBd2, MySet2); // Not legal XAxiDma_BdRingAlloc(MyRingPtr, NumBd1, &MySet1); XAxiDma_BdRingAlloc(MyRingPtr, NumBd2, &MySet2); XAxiDma_BdRingToHw(MyRingPtr, NumBd2, MySet2); XAxiDma_BdRingToHw(MyRingPtr, NumBd1, MySet1); Use the API defined in xaxidmabd.h to modify individual BDs. Traversal of the BD set can be done using XAxiDma_BdRingNext() and XAxiDma_BdRingPrev(). RingPtr is a pointer to the descriptor ring instance to be worked on. NumBd is the number of BDs to allocate BdSetPtr is an output parameter, it points to the first BD available for modification. XST_SUCCESS if the requested number of BDs were returned in the BdSetPtr parameter.XST_INVALID_PARAM if passed in NumBd is not positiveXST_FAILURE if there were not enough free BDs to satisfy the request. This function should not be preempted by another XAxiDma_BdRing function call that modifies the BD space. It is the caller's responsibility to provide a mutual exclusion mechanism. Do not modify more BDs than the number requested with the NumBd parameter. Doing so will lead to data corruption and system instability.This function can be used only when DMA is in SG mode
References XAxiDma_BdRing::FreeCnt, XAxiDma_BdRing::FreeHead, XAxiDma_BdRing::PreCnt.
int XAxiDma_BdRingUnAlloc(XAxiDma_BdRing *RingPtr, int NumBd, XAxiDma_Bd *BdSetPtr)
Fully or partially undo an XAxiDma_BdRingAlloc() operation.
Use this function if all the BDs allocated by XAxiDma_BdRingAlloc() could not be transferred to hardware with XAxiDma_BdRingToHw().This function releases the BDs after they have been allocated but before they have been given to hardware.This function is not the same as XAxiDma_BdRingFree(). The Free function returns BDs to the free list after they have been processed by hardware, while UnAlloc returns them before being processed by hardware.There are two scenarios where this function can be used. Full UnAlloc or Partial UnAlloc. A Full UnAlloc means all the BDs Alloc'd will be returned: Status = XAxiDma_BdRingAlloc(MyRingPtr, 10, &BdPtr); ... ... if (Error) { Status = XAxiDma_BdRingUnAlloc(MyRingPtr, 10, &BdPtr); } A partial UnAlloc means some of the BDs Alloc'd will be returned: Status = XAxiDma_BdRingAlloc(MyRingPtr, 10, &BdPtr); BdsLeft = 10; CurBdPtr = BdPtr; while (BdsLeft) { if (Error) { Status = XAxiDma_BdRingUnAlloc(MyRingPtr, BdsLeft, CurBdPtr); } CurBdPtr = XAxiDma_BdRingNext(MyRingPtr, CurBdPtr); BdsLeft--; } A partial UnAlloc must include the last BD in the list that was Alloc'd. RingPtr is a pointer to the descriptor ring instance to be worked on. NumBd is the number of BDs to unallocate BdSetPtr points to the first of the BDs to be returned. XST_SUCCESS if the BDs were unallocated.XST_INVALID_PARAM if passed in NumBd is negativeXST_FAILURE if NumBd parameter was greater that the number of BDs in the preprocessing state. This function should not be preempted by another XAxiDma ring function call that modifies the BD space. It is the caller's responsibility to provide a mutual exclusion mechanism. This function can be used only when DMA is in SG mode
References XAxiDma_BdRing::FreeCnt, XAxiDma_BdRing::FreeHead, XAxiDma_BdRing::PreCnt.
int XAxiDma_BdRingToHw(XAxiDma_BdRing *RingPtr, int NumBd, XAxiDma_Bd *BdSetPtr)
Enqueue a set of BDs to hardware that were previously allocated by XAxiDma_BdRingAlloc().
Once this function returns, the argument BD set goes under hardware control. Changes to these BDs should be held until they are finished by hardware to avoid data corruption and system instability.For transmit, the set will be rejected if the last BD of the set does not mark the end of a packet or the first BD does not mark the start of a packet. RingPtr is a pointer to the descriptor ring instance to be worked on. NumBd is the number of BDs in the set. BdSetPtr is the first BD of the set to commit to hardware. XST_SUCCESS if the set of BDs was accepted and enqueued to hardwareXST_INVALID_PARAM if passed in NumBd is negativeXST_FAILURE if the set of BDs was rejected because the first BD does not have its start-of-packet bit set, or the last BD does not have its end-of-packet bit set, or any one of the BDs has 0 length.XST_DMA_SG_LIST_ERROR if this function was called out of sequence with XAxiDma_BdRingAlloc() This function should not be preempted by another XAxiDma ring function call that modifies the BD space. It is the caller's responsibility to provide a mutual exclusion mechanism. This function can be used only when DMA is in SG mode
References XAxiDma_BdRing::ChanBase, XAxiDma_BdRing::Cyclic, XAxiDma_BdRing::CyclicBd, XAxiDma_BdRing::HwCnt, XAxiDma_BdRing::HwTail, XAxiDma_BdRing::IsRxChannel, XAxiDma_BdRing::PreCnt, XAxiDma_BdRing::PreHead, XAxiDma_BdRing::RingIndex, XAxiDma_BdRing::RunState, XAXIDMA_BD_CTRL_LEN_OFFSET, XAXIDMA_BD_CTRL_TXEOF_MASK, XAXIDMA_BD_CTRL_TXSOF_MASK, XAXIDMA_BD_STS_COMPLETE_MASK, XAXIDMA_BD_STS_OFFSET, XAxiDma_BdGetCtrl, XAxiDma_BdGetLength, XAxiDma_BdGetSts, XAxiDma_BdRead, XAxiDma_BdRingNext, XAxiDma_BdWrite, XAXIDMA_DESC_LSB_MASK, XAXIDMA_RX_NDESC_OFFSET, XAXIDMA_RX_TDESC0_MSB_OFFSET, XAXIDMA_RX_TDESC0_OFFSET, XAXIDMA_TDESC_MSB_OFFSET, XAXIDMA_TDESC_OFFSET, XAxiDma_WriteReg.
int XAxiDma_BdRingFromHw(XAxiDma_BdRing *RingPtr, int BdLimit, XAxiDma_Bd **BdSetPtr)
Returns a set of BD(s) that have been processed by hardware.
The returned BDs may be examined by the application to determine the outcome of the DMA transactions. Once the BDs have been examined, the application must call XAxiDma_BdRingFree() in the same order which they were retrieved here.Example: NumBd = XAxiDma_BdRingFromHw(MyRingPtr, XAXIDMA_ALL_BDS, &MyBdSet); if (NumBd == 0) { // hardware has nothing ready for us yet } CurBd = MyBdSet; for (i=0; i<NumBd; i++) { // Examine CurBd for post processing..... // Onto next BD CurBd = XAxiDma_BdRingNext(MyRingPtr, CurBd); } XAxiDma_BdRingFree(MyRingPtr, NumBd, MyBdSet); // Return the list A more advanced use of this function may allocate multiple sets of BDs. They must be retrieved from hardware and freed in the correct sequence: // Legal XAxiDma_BdRingFromHw(MyRingPtr, NumBd1, &MySet1); XAxiDma_BdRingFree(MyRingPtr, NumBd1, MySet1); // Legal XAxiDma_BdRingFromHw(MyRingPtr, NumBd1, &MySet1); XAxiDma_BdRingFromHw(MyRingPtr, NumBd2, &MySet2); XAxiDma_BdRingFree(MyRingPtr, NumBd1, MySet1); XAxiDma_BdRingFree(MyRingPtr, NumBd2, MySet2); // Not legal XAxiDma_BdRingFromHw(MyRingPtr, NumBd1, &MySet1); XAxiDma_BdRingFromHw(MyRingPtr, NumBd2, &MySet2); XAxiDma_BdRingFree(MyRingPtr, NumBd2, MySet2); XAxiDma_BdRingFree(MyRingPtr, NumBd1, MySet1); If hardware has partially completed a packet spanning multiple BDs, then none of the BDs for that packet will be included in the results. RingPtr is a pointer to the descriptor ring instance to be worked on. BdLimit is the maximum number of BDs to return in the set. Use XAXIDMA_ALL_BDS to return all BDs that have been processed. BdSetPtr is an output parameter, it points to the first BD available for examination. The number of BDs processed by hardware. A value of 0 indicates that no data is available. No more than BdLimit BDs will be returned. Treat BDs returned by this function as read-only. This function should not be preempted by another XAxiDma ring function call that modifies the BD space. It is the caller's responsibility to provide a mutual exclusion mechanism. This function can be used only when DMA is in SG mode
References XAxiDma_BdRing::Cyclic, XAxiDma_BdRing::HwCnt, XAxiDma_BdRing::HwHead, XAxiDma_BdRing::HwTail, XAxiDma_BdRing::IsRxChannel, XAxiDma_BdRing::PostCnt, XAXIDMA_BD_CTRL_LEN_OFFSET, XAXIDMA_BD_CTRL_TXEOF_MASK, XAXIDMA_BD_STS_COMPLETE_MASK, XAXIDMA_BD_STS_OFFSET, XAXIDMA_BD_STS_RXEOF_MASK, XAxiDma_BdRead, XAxiDma_BdRingNext, XAxiDma_BdWrite.
int XAxiDma_BdRingFree(XAxiDma_BdRing *RingPtr, int NumBd, XAxiDma_Bd *BdSetPtr)
Frees a set of BDs that had been previously retrieved with XAxiDma_BdRingFromHw().
RingPtr is a pointer to the descriptor ring instance to be worked on. NumBd is the number of BDs to free. BdSetPtr is the head of a list of BDs returned by XAxiDma_BdRingFromHw(). XST_SUCCESS if the set of BDs was freed.XST_INVALID_PARAM if NumBd is negativeXST_DMA_SG_LIST_ERROR if this function was called out of sequence with XAxiDma_BdRingFromHw(). This function should not be preempted by another XAxiDma function call that modifies the BD space. It is the caller's responsibility to ensure mutual exclusion. This function can be used only when DMA is in SG mode
References XAxiDma_BdRing::FreeCnt, XAxiDma_BdRing::PostCnt, XAxiDma_BdRing::PostHead.
int XAxiDma_BdRingCheck(XAxiDma_BdRing *RingPtr)
Check the internal data structures of the BD ring for the provided channel.
The following checks are made: - The BD ring is linked correctly in physical address space. - The internal pointers point to BDs in the ring. - The internal counters add up. The channel should be stopped (through XAxiDma_Pause() or XAxiDma_Reset()) prior to calling this function. RingPtr is a pointer to the descriptor ring to be worked on. XST_SUCCESS if no errors were found.XST_DMA_SG_NO_LIST if the ring has not been created.XST_IS_STARTED if the channel is not stopped.XST_DMA_SG_LIST_ERROR if a problem is found with the internal data structures. If this value is returned, the channel should be reset,and the BD ring should be recreated through XAxiDma_BdRingCreate() to avoid data corruption or system instability. This function can be used only when DMA is in SG mode
References XAxiDma_BdRing::AllCnt, XAxiDma_BdRing::FirstBdAddr, XAxiDma_BdRing::FirstBdPhysAddr, XAxiDma_BdRing::FreeCnt, XAxiDma_BdRing::FreeHead, XAxiDma_BdRing::HwCnt, XAxiDma_BdRing::HwHead, XAxiDma_BdRing::HwTail, XAxiDma_BdRing::LastBdAddr, XAxiDma_BdRing::PostCnt, XAxiDma_BdRing::PostHead, XAxiDma_BdRing::PreCnt, XAxiDma_BdRing::PreHead, XAxiDma_BdRing::RunState, XAxiDma_BdRing::Separation, XAXIDMA_BD_NDESC_OFFSET, XAxiDma_BdRead.
void XAxiDma_BdRingDumpRegs(XAxiDma_BdRing *RingPtr)
Dump the registers for a channel.
RingPtr is a pointer to the descriptor ring to be worked on. None This function can be used only when DMA is in SG mode
References XAxiDma_BdRing::ChanBase, XAxiDma_BdRing::RingIndex, XAXIDMA_CDESC_OFFSET, XAXIDMA_CR_OFFSET, XAxiDma_ReadReg, XAXIDMA_RX_CDESC0_OFFSET, XAXIDMA_RX_NDESC_OFFSET, XAXIDMA_RX_TDESC0_OFFSET, XAXIDMA_SR_OFFSET, XAXIDMA_TDESC_OFFSET.
XAXIDMA_RESET_TIMEOUT
XAxiDma_GetTxRing
Get Transmit (Tx) Ring ptr.
Warning: This has a different API than the LLDMA driver. It now returns the pointer to the BD ring. InstancePtr is a pointer to the DMA engine instance to be worked on. Pointer to the Tx Ring C-style signature: XAxiDma_BdRing * XAxiDma_GetTxRing(XAxiDma * InstancePtr) This function is used only when system is configured as SG mode
Referenced by main, XAxiDma_Pause, XAxiDma_Reset, XAxiDma_ResetIsDone, XAxiDma_Resume.
XAxiDma_GetRxRing
Get Receive (Rx) Ring ptr.
Warning: This has a different API than the LLDMA driver. It now returns the pointer to the BD ring. InstancePtr is a pointer to the DMA engine instance to be worked on. Pointer to the Rx Ring C-style signature: XAxiDma_BdRing * XAxiDma_GetRxRing(XAxiDma * InstancePtr) This function is used only when system is configured as SG mode
Referenced by main, XAxiDma_ResetIsDone.
XAxiDma_GetRxIndexRing
Get Receive (Rx) Ring ptr of a Index.
Warning: This has a different API than the LLDMA driver. It now returns the pointer to the BD ring. InstancePtr is a pointer to the DMA engine instance to be worked on. RingIndex is the channel Index. Pointer to the Rx Ring C-style signature: XAxiDma_BdRing * XAxiDma_GetRxIndexRing(XAxiDma * InstancePtr, int RingIndex) This function is used only when system is configured as SG mode
Referenced by XAxiDma_Pause, XAxiDma_Reset, XAxiDma_Resume.
XAxiDma_HasSg
This function checks whether system is configured as Simple or Scatter Gather mode.
InstancePtr is a pointer to the DMA engine instance to be worked on. TRUE if configured as SG modeFALSE if configured as simple mode None
Referenced by main, XAxiDma_Pause, XAxiDma_Reset, XAxiDma_Resume, XAxiDma_SimplePollExample, XAxiDma_SimpleTransfer.
XAxiDma_IntrEnable
This function enables interrupts specified by the Mask in specified direction, Interrupts that are not in the mask are not affected.
InstancePtr is the driver instance we are working on Mask is the mask for the interrupts to be enabled Direction is DMA transfer direction, valid values are XAXIDMA_DMA_TO_DEVICE.XAXIDMA_DEVICE_TO_DMA. None None
Referenced by main.
XAxiDma_IntrGetEnabled
This function gets the mask for the interrupts that are currently enabled.
InstancePtr is the driver instance we are working on Direction is DMA transfer direction, valid values are XAXIDMA_DMA_TO_DEVICE.XAXIDMA_DEVICE_TO_DMA. The bit mask for the interrupts that are currently enabled None
XAxiDma_IntrDisable
This function disables interrupts specified by the Mask.
Interrupts that are not in the mask are not affected. InstancePtr is the driver instance we are working on Mask is the mask for the interrupts to be disabled Direction is DMA transfer direction, valid values are XAXIDMA_DMA_TO_DEVICE.XAXIDMA_DEVICE_TO_DMA. None None
Referenced by main, XAxiDma_SimplePollExample.
XAxiDma_IntrGetIrq
This function gets the interrupts that are asserted.
InstancePtr is the driver instance we are working on Direction is DMA transfer direction, valid values are XAXIDMA_DMA_TO_DEVICE.XAXIDMA_DEVICE_TO_DMA. The bit mask for the interrupts asserted. None
XAxiDma_IntrAckIrq
This function acknowledges the interrupts that are specified in Mask.
InstancePtr is the driver instance we are working on Mask is the mask for the interrupts to be acknowledge Direction is DMA transfer direction, valid values are XAXIDMA_DMA_TO_DEVICE.XAXIDMA_DEVICE_TO_DMA. None None.
XAXIDMA_CACHE_FLUSH
XAXIDMA_CACHE_INVALIDATE
XAxiDma_BdRead
Read the given Buffer Descriptor word.
BaseAddress is the base address of the BD to read Offset is the word offset to be read The 32-bit value of the field C-style signature: u32 XAxiDma_BdRead(u32 BaseAddress, u32 Offset)
Referenced by XAxiDma_BdGetAppWord, XAxiDma_BdRingCheck, XAxiDma_BdRingClone, XAxiDma_BdRingFromHw, XAxiDma_BdRingToHw, XAxiDma_BdSetAppWord, XAxiDma_BdSetBufAddr, XAxiDma_BdSetCtrl, XAxiDma_BdSetLength, XAxiDma_DumpBd, XAxiDma_StartBdRingHw.
XAxiDma_BdWrite
Write the given Buffer Descriptor word.
BaseAddress is the base address of the BD to write Offset is the word offset to be written Data is the 32-bit value to write to the field None. C-style signature: void XAxiDma_BdWrite(u32 BaseAddress, u32 RegOffset, u32 Data)
Referenced by XAxiDma_BdRingClone, XAxiDma_BdRingCreate, XAxiDma_BdRingFromHw, XAxiDma_BdRingToHw, XAxiDma_BdSetAppWord, XAxiDma_BdSetBufAddr, XAxiDma_BdSetBufAddrMicroMode, XAxiDma_BdSetCtrl, XAxiDma_BdSetLength.
XAxiDma_BdWrite64
Write the given Buffer Descriptor word.
BaseAddress is the base address of the BD to write Offset is the word offset to be written Data is the 64-bit value to write to the field None. C-style signature: void XAxiDma_BdWrite(u64 BaseAddress, u32 RegOffset, u64 Data)
Referenced by XAxiDma_BdSetBufAddr, XAxiDma_BdSetBufAddrMicroMode.
XAxiDma_BdClear
Zero out BD specific fields.
BD fields that are for the BD ring or for the system hardware build information are not touched. BdPtr is the BD to operate on None C-style signature: void XAxiDma_BdClear(XAxiDma_Bd* BdPtr)
XAxiDma_BdGetCtrl
Get the control bits for the BD.
BdPtr is the BD to operate on The bit mask for the control of the BD C-style signature: u32 XAxiDma_BdGetCtrl(XAxiDma_Bd* BdPtr)
Referenced by XAxiDma_BdRingToHw.
XAxiDma_BdGetSts
Retrieve the status of a BD.
BdPtr is the BD to operate on Word at offset XAXIDMA_BD_DMASR_OFFSET. Use XAXIDMA_BD_STS_*** values defined in xaxidma_hw.h to interpret the returned value C-style signature: u32 XAxiDma_BdGetSts(XAxiDma_Bd* BdPtr)
Referenced by XAxiDma_BdRingToHw.
XAxiDma_BdGetLength
Retrieve the length field value from the given BD.
The returned value is the same as what was written with XAxiDma_BdSetLength(). Note that in the this value does not reflect the real length of received data. See the comments of XAxiDma_BdSetLength() for more details. To obtain the actual transfer length, use XAxiDma_BdGetActualLength(). BdPtr is the BD to operate on. LengthMask is the Maximum Transfer Length. The length value set in the BD. C-style signature: u32 XAxiDma_BdGetLength(XAxiDma_Bd* BdPtr)
Referenced by XAxiDma_BdRingToHw.
XAxiDma_BdSetId
Set the ID field of the given BD.
The ID is an arbitrary piece of data the application can associate with a specific BD. BdPtr is the BD to operate on Id is a 32 bit quantity to set in the BD None C-style signature: void XAxiDma_BdSetId(XAxiDma_Bd* BdPtr, void Id)
XAxiDma_BdGetId
Retrieve the ID field of the given BD previously set with XAxiDma_BdSetId.
BdPtr is the BD to operate on None C-style signature: u32 XAxiDma_BdGetId(XAxiDma_Bd* BdPtr)
XAxiDma_BdGetBufAddr
Get the BD's buffer address.
BdPtr is the BD to operate on None C-style signature: u32 XAxiDma_BdGetBufAddr(XAxiDma_Bd* BdPtr)
XAxiDma_BdHwCompleted
Check whether a BD has completed in hardware.
This BD has been submitted to hardware. The application can use this function to poll for the completion of the BD.This function may not work if the BD is in cached memory. BdPtr is the BD to check on 0 if not completeXAXIDMA_BD_STS_COMPLETE_MASK if completed, may contain XAXIDMA_BD_STS_*_ERR_MASK bits. C-style signature: int XAxiDma_BdHwCompleted(XAxiDma_Bd* BdPtr)
Referenced by XAxiDma_UpdateBdRingCDesc.
XAxiDma_BdGetActualLength
Get the actual transfer length of a BD.
The BD has completed in hw.This function may not work if the BD is in cached memory. BdPtr is the BD to check on LengthMask is the Maximum Transfer Length. None C-style signature: int XAxiDma_BdGetActualLength(XAxiDma_Bd* BdPtr)
XAxiDma_BdSetTId
Set the TID field of the TX BD.
Provides a stream identifier and can be used to differentiate between multiple streams of data that are being transferred across the same interface. BdPtr is the BD to operate on TId is a 8 bit quantity to set in the BD None C-style signature: void XAxiDma_BdSetTId(XAxiDma_Bd* BdPtr, void TId)
XAxiDma_BdGetTId
Retrieve the TID field of the RX BD previously set with XAxiDma_BdSetTId.
BdPtr is the BD to operate on None C-style signature: u32 XAxiDma_BdGetTId(XAxiDma_Bd* BdPtr)
XAxiDma_BdSetTDest
Set the TDEST field of the TX BD.
Provides coarse routing information for the data stream. BdPtr is the BD to operate on TDest is a 8 bit quantity to set in the BD None C-style signature: void XAxiDma_BdSetTDest(XAxiDma_Bd* BdPtr, void TDest)
XAxiDma_BdGetTDest
Retrieve the TDest field of the RX BD previously set with i XAxiDma_BdSetTDest.
BdPtr is the BD to operate on None C-style signature: u32 XAxiDma_BdGetTDest(XAxiDma_Bd* BdPtr)
XAxiDma_BdSetTUser
Set the TUSER field of the TX BD.
User defined sideband signaling. BdPtr is the BD to operate on TUser is a 8 bit quantity to set in the BD None C-style signature: void XAxiDma_BdSetTUser(XAxiDma_Bd* BdPtr, void TUser)
XAxiDma_BdGetTUser
Retrieve the TUSER field of the RX BD previously set with XAxiDma_BdSetTUser.
BdPtr is the BD to operate on None C-style signature: u32 XAxiDma_BdGetTUser(XAxiDma_Bd* BdPtr)
XAxiDma_BdSetARCache
Set the ARCACHE field of the given BD.
This signal provides additional information about the cacheable characteristics of the transfer. BdPtr is the BD to operate on ARCache is a 8 bit quantity to set in the BD None C-style signature: void XAxiDma_BdSetARCache(XAxiDma_Bd* BdPtr, void ARCache)
XAxiDma_BdGetARCache
Retrieve the ARCACHE field of the given BD previously set with XAxiDma_BdSetARCache.
BdPtr is the BD to operate on None C-style signature: u32 XAxiDma_BdGetARCache(XAxiDma_Bd* BdPtr)
XAxiDma_BdSetARUser
Set the ARUSER field of the given BD.
Sideband signals used for user defined information. BdPtr is the BD to operate on ARUser is a 8 bit quantity to set in the BD None C-style signature: void XAxiDma_BdSetARUser(XAxiDma_Bd* BdPtr, void ARUser)
XAxiDma_BdGetARUser
Retrieve the ARUSER field of the given BD previously set with XAxiDma_BdSetARUser.
BdPtr is the BD to operate on None C-style signature: u32 XAxiDma_BdGetARUser(XAxiDma_Bd* BdPtr)
XAxiDma_BdSetStride
Set the STRIDE field of the given BD.
It is the address distance between the first address of successive horizontal reads. BdPtr is the BD to operate on Stride is a 32 bit quantity to set in the BD None C-style signature: void XAxiDma_BdSetStride(XAxiDma_Bd* BdPtr, void Stride)
XAxiDma_BdGetStride
Retrieve the STRIDE field of the given BD previously set with XAxiDma_BdSetStride.
BdPtr is the BD to operate on None C-style signature: u32 XAxiDma_BdGetStride(XAxiDma_Bd* BdPtr)
XAxiDma_BdSetVSize
Set the VSIZE field of the given BD.
Number of horizontal lines for strided access. BdPtr is the BD to operate on VSize is a 32 bit quantity to set in the BD None C-style signature: void XAxiDma_BdSetVSize(XAxiDma_Bd* BdPtr, void VSize)
XAxiDma_BdGetVSize
Retrieve the STRIDE field of the given BD previously set with XAxiDma_BdSetVSize.
BdPtr is the BD to operate on None C-style signature: u32 XAxiDma_BdGetVSize(XAxiDma_Bd* BdPtr)
XAXIDMA_STOP_TIMEOUT
XAXIDMA_VIRT_TO_PHYS
XAXIDMA_RING_SEEKAHEAD
XAXIDMA_RING_SEEKBACK
AXIDMA_CHANNEL_NOT_HALTED
AXIDMA_CHANNEL_HALTED
XAXIDMA_NO_CHANGE
XAXIDMA_ALL_BDS
XAxiDma_BdRingCntCalc
Use this macro at initialization time to determine how many BDs will fit within the given memory constraints.
The results of this macro can be provided to XAxiDma_BdRingCreate(). Alignment specifies what byte alignment the BDs must fall on and must be a power of 2 to get an accurate calculation (32, 64, 126,...) Bytes is the number of bytes to be used to store BDs. Number of BDs that can fit in the given memory area C-style signature: int XAxiDma_BdRingCntCalc(u32 Alignment, u32 Bytes) This function is used only when system is configured as SG mode
XAxiDma_BdRingMemCalc
Use this macro at initialization time to determine how many bytes of memory are required to contain a given number of BDs at a given alignment.
Alignment specifies what byte alignment the BDs must fall on. This parameter must be a power of 2 to get an accurate calculation (32, 64,128,...) NumBd is the number of BDs to calculate memory size requirements The number of bytes of memory required to create a BD list with the given memory constraints. C-style signature: int XAxiDma_BdRingMemCalc(u32 Alignment, u32 NumBd) This function is used only when system is configured as SG mode
XAxiDma_BdRingGetCnt
Return the total number of BDs allocated by this channel with XAxiDma_BdRingCreate().
RingPtr is the BD ring to operate on. The total number of BDs allocated for this channel. C-style signature: int XAxiDma_BdRingGetCnt(XAxiDma_BdRing* RingPtr) This function is used only when system is configured as SG mode
XAxiDma_BdRingGetFreeCnt
Return the number of BDs allocatable with XAxiDma_BdRingAlloc() for pre- processing.
RingPtr is the BD ring to operate on. The number of BDs currently allocatable. C-style signature: int XAxiDma_BdRingGetFreeCnt(XAxiDma_BdRing* RingPtr) This function is used only when system is configured as SG mode
XAxiDma_BdRingSnapShotCurrBd
Snap shot the latest BD a BD ring is processing.
RingPtr is the BD ring to operate on. None C-style signature: void XAxiDma_BdRingSnapShotCurrBd(XAxiDma_BdRing* RingPtr) This function is used only when system is configured as SG mode
Referenced by XAxiDma_Reset.
XAxiDma_BdRingGetCurrBd
Get the BD a BD ring is processing.
RingPtr is the BD ring to operate on. The current BD that the BD ring is working on C-style signature: XAxiDma_Bd * XAxiDma_BdRingGetCurrBd(XAxiDma_BdRing* RingPtr) This function is used only when system is configured as SG mode
XAxiDma_BdRingNext
Return the next BD in the ring.
RingPtr is the BD ring to operate on. BdPtr is the current BD. The next BD in the ring relative to the BdPtr parameter. C-style signature: XAxiDma_Bd XAxiDma_BdRingNext(XAxiDma_BdRing RingPtr, XAxiDma_Bd *BdPtr) This function is used only when system is configured as SG mode
Referenced by XAxiDma_BdRingFromHw, XAxiDma_BdRingToHw, XAxiDma_UpdateBdRingCDesc.
XAxiDma_BdRingPrev
Return the previous BD in the ring.
RingPtr is the DMA channel to operate on. BdPtr is the current BD. The previous BD in the ring relative to the BdPtr parameter. C-style signature: XAxiDma_Bd XAxiDma_BdRingPrev(XAxiDma_BdRing RingPtr, XAxiDma_Bd *BdPtr) This function is used only when system is configured as SG mode
XAxiDma_BdRingGetSr
Retrieve the contents of the channel status register.
RingPtr is the channel instance to operate on. Current contents of status register C-style signature: u32 XAxiDma_BdRingGetSr(XAxiDma_BdRing* RingPtr) This function is used only when system is configured as SG mode
XAxiDma_BdRingGetError
Get error bits of a DMA channel.
RingPtr is the channel instance to operate on. Error bits in the status register, they should be interpreted with XAXIDMA_ERR_*_MASK defined in xaxidma_hw.h C-style signature: u32 XAxiDma_BdRingGetError(XAxiDma_BdRing* RingPtr) This function is used only when system is configured as SG mode
XAxiDma_BdRingHwIsStarted
Check whether a DMA channel is started, meaning the channel is not halted.
RingPtr is the channel instance to operate on. 1 if channel is started0 otherwise C-style signature: int XAxiDma_BdRingHwIsStarted(XAxiDma_BdRing* RingPtr)
Referenced by XAxiDma_StartBdRingHw, XAxiDma_UpdateBdRingCDesc.
XAxiDma_BdRingBusy
Check if the current DMA channel is busy with a DMA operation.
RingPtr is the channel instance to operate on. 1 if the DMA is busy.0 otherwise C-style signature: int XAxiDma_BdRingBusy(XAxiDma_BdRing* RingPtr) This function is used only when system is configured as SG mode
XAxiDma_BdRingIntEnable
Set interrupt enable bits for a channel.
This operation will modify the XAXIDMA_CR_OFFSET register. RingPtr is the channel instance to operate on. Mask consists of the interrupt signals to enable.Bits not specified in the mask are not affected. C-style signature: void XAxiDma_BdRingIntEnable(XAxiDma_BdRing* RingPtr, u32 Mask) This function is used only when system is configured as SG mode
XAxiDma_BdRingIntGetEnabled
Get enabled interrupts of a channel.
It is in XAXIDMA_CR_OFFSET register. RingPtr is the channel instance to operate on. Enabled interrupts of a channel. Use XAXIDMA_IRQ_* defined in xaxidma_hw.h to interpret this returned value. C-style signature: u32 XAxiDma_BdRingIntGetEnabled(XAxiDma_BdRing* RingPtr) This function is used only when system is configured as SG mode
XAxiDma_BdRingIntDisable
Clear interrupt enable bits for a channel.
It modifies the XAXIDMA_CR_OFFSET register. RingPtr is the channel instance to operate on. Mask consists of the interrupt signals to disable.Bits not specified in the Mask are not affected. C-style signature: void XAxiDma_BdRingIntDisable(XAxiDma_BdRing* RingPtr, u32 Mask) This function is used only when system is configured as SG mode
XAxiDma_BdRingGetIrq
Retrieve the contents of the channel's IRQ register XAXIDMA_SR_OFFSET.
This operation can be used to see which interrupts are pending. RingPtr is the channel instance to operate on. Current contents of the IRQ_OFFSET register. Use XAXIDMA_IRQ_*** values defined in xaxidma_hw.h to interpret the returned value. C-style signature: u32 XAxiDma_BdRingGetIrq(XAxiDma_BdRing* RingPtr) This function is used only when system is configured as SG mode
XAxiDma_BdRingAckIrq
Acknowledge asserted interrupts.
It modifies XAXIDMA_SR_OFFSET register. A mask bit set for an unasserted interrupt has no effect. RingPtr is the channel instance to operate on. Mask are the interrupt signals to acknowledge C-style signature: void XAxiDma_BdRingAckIrq(XAxiDma_BdRing* RingPtr) This function is used only when system is configured as SG mode
XAxiDma_BdRingEnableCyclicDMA
Enable Cyclic DMA Mode.
RingPtr is the channel instance to operate on. C-style signature: void XAxiDma_BdRingEnableCyclicDMA(XAxiDma_BdRing* RingPtr) This function is used only when system is configured as SG mode
XPAR_AXIDMA_0_INCLUDE_SG
XAXIDMA_DESC_LSB_MASK
LSB Address mask.
Referenced by XAxiDma_BdRingCreate, XAxiDma_BdRingToHw, XAxiDma_StartBdRingHw, XAxiDma_UpdateBdRingCDesc.
XAxiDma_In32
XAxiDma_Out32
XAxiDma_ReadReg
Read the given register.
BaseAddress is the base address of the device RegOffset is the register offset to be read The 32-bit value of the register C-style signature: u32 XAxiDma_ReadReg(u32 BaseAddress, u32 RegOffset)
Referenced by XAxiDma_BdRingDumpRegs, XAxiDma_BdRingGetCoalesce, XAxiDma_BdRingSetCoalesce, XAxiDma_Busy, XAxiDma_Pause, XAxiDma_ResetIsDone, XAxiDma_SelectCyclicMode, XAxiDma_SelectKeyHole, XAxiDma_SimpleTransfer, XAxiDma_StartBdRingHw.
XAxiDma_WriteReg
Write the given register.
BaseAddress is the base address of the device RegOffset is the register offset to be written Data is the 32-bit value to write to the register None. C-style signature: void XAxiDma_WriteReg(u32 BaseAddress, u32 RegOffset, u32 Data)
Referenced by XAxiDma_BdRingSetCoalesce, XAxiDma_BdRingToHw, XAxiDma_Pause, XAxiDma_Reset, XAxiDma_SelectCyclicMode, XAxiDma_SelectKeyHole, XAxiDma_SimpleTransfer, XAxiDma_StartBdRingHw, XAxiDma_UpdateBdRingCDesc.
XAXIDMA_RESET_TIMEOUT