xaxidma_sinit.c
XAxiDma_Config * XAxiDma_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
A table contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration table entry corresponding to the given device ID/BaseAddress, or NULL if no match is found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XAxiDma_Config::Name.
Referenced by AxiDMASelfTestExample, main, XAxiDma_SimplePollExample.