xaxidma.h
XAxiDma_GetTxRing
Get Transmit (Tx) Ring ptr.
Warning: This has a different API than the LLDMA driver. It now returns the pointer to the BD ring. InstancePtr is a pointer to the DMA engine instance to be worked on. Pointer to the Tx Ring C-style signature: XAxiDma_BdRing * XAxiDma_GetTxRing(XAxiDma * InstancePtr) This function is used only when system is configured as SG mode
Referenced by main, XAxiDma_Pause, XAxiDma_Reset, XAxiDma_ResetIsDone, XAxiDma_Resume.
XAxiDma_GetRxRing
Get Receive (Rx) Ring ptr.
Warning: This has a different API than the LLDMA driver. It now returns the pointer to the BD ring. InstancePtr is a pointer to the DMA engine instance to be worked on. Pointer to the Rx Ring C-style signature: XAxiDma_BdRing * XAxiDma_GetRxRing(XAxiDma * InstancePtr) This function is used only when system is configured as SG mode
Referenced by main, XAxiDma_ResetIsDone.
XAxiDma_GetRxIndexRing
Get Receive (Rx) Ring ptr of a Index.
Warning: This has a different API than the LLDMA driver. It now returns the pointer to the BD ring. InstancePtr is a pointer to the DMA engine instance to be worked on. RingIndex is the channel Index. Pointer to the Rx Ring C-style signature: XAxiDma_BdRing * XAxiDma_GetRxIndexRing(XAxiDma * InstancePtr, int RingIndex) This function is used only when system is configured as SG mode
Referenced by XAxiDma_Pause, XAxiDma_Reset, XAxiDma_Resume.
XAxiDma_HasSg
This function checks whether system is configured as Simple or Scatter Gather mode.
InstancePtr is a pointer to the DMA engine instance to be worked on. TRUE if configured as SG modeFALSE if configured as simple mode None
Referenced by main, XAxiDma_Pause, XAxiDma_Reset, XAxiDma_Resume, XAxiDma_SimplePollExample, XAxiDma_SimpleTransfer.
XAxiDma_IntrEnable
This function enables interrupts specified by the Mask in specified direction, Interrupts that are not in the mask are not affected.
InstancePtr is the driver instance we are working on Mask is the mask for the interrupts to be enabled Direction is DMA transfer direction, valid values are XAXIDMA_DMA_TO_DEVICE.XAXIDMA_DEVICE_TO_DMA. None None
Referenced by main.
XAxiDma_IntrGetEnabled
This function gets the mask for the interrupts that are currently enabled.
InstancePtr is the driver instance we are working on Direction is DMA transfer direction, valid values are XAXIDMA_DMA_TO_DEVICE.XAXIDMA_DEVICE_TO_DMA. The bit mask for the interrupts that are currently enabled None
XAxiDma_IntrDisable
This function disables interrupts specified by the Mask.
Interrupts that are not in the mask are not affected. InstancePtr is the driver instance we are working on Mask is the mask for the interrupts to be disabled Direction is DMA transfer direction, valid values are XAXIDMA_DMA_TO_DEVICE.XAXIDMA_DEVICE_TO_DMA. None None
Referenced by main, XAxiDma_SimplePollExample.
XAxiDma_IntrGetIrq
This function gets the interrupts that are asserted.
InstancePtr is the driver instance we are working on Direction is DMA transfer direction, valid values are XAXIDMA_DMA_TO_DEVICE.XAXIDMA_DEVICE_TO_DMA. The bit mask for the interrupts asserted. None
XAxiDma_IntrAckIrq
This function acknowledges the interrupts that are specified in Mask.
InstancePtr is the driver instance we are working on Mask is the mask for the interrupts to be acknowledge Direction is DMA transfer direction, valid values are XAXIDMA_DMA_TO_DEVICE.XAXIDMA_DEVICE_TO_DMA. None None.
typedef struct XAxiDma XAxiDma
The XAxiDma driver instance data.
An instance must be allocated for each DMA engine in use.
XAxiDma_Config * XAxiDma_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
A table contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration table entry corresponding to the given device ID/BaseAddress, or NULL if no match is found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XAxiDma_Config::Name.
Referenced by AxiDMASelfTestExample, main, XAxiDma_SimplePollExample.
int XAxiDma_CfgInitialize(XAxiDma *InstancePtr, XAxiDma_Config *Config)
This function initializes a DMA engine.
This function must be called prior to using a DMA engine. Initializing a engine includes setting up the register base address, setting up the instance data, and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the DMA engine instance to be worked on. Config is a pointer to an XAxiDma_Config structure. It contains the information about the hardware build, including base address,and whether status control stream (StsCntrlStrm), MM2S and S2MM are included in the build. XST_SUCCESS for successful initializationXST_INVALID_PARAM if pointer to the configuration structure is NULLXST_DMA_ERROR if reset operation failed at the end of initialization We assume the hardware building tool will check and error out for a hardware build that has no transfer channels.
References XAxiDma::AddrWidth, XAxiDma_Config::AddrWidth, XAxiDma_Config::BaseAddr, XAxiDma_BdRing::ChanBase, XAxiDma_Config::HasMm2S, XAxiDma_Config::HasMm2SDRE, XAxiDma_Config::HasS2Mm, XAxiDma_Config::HasS2MmDRE, XAxiDma_Config::HasSg, XAxiDma_BdRing::HasStsCntrlStrm, XAxiDma_Config::HasStsCntrlStrm, XAxiDma_BdRing::IsRxChannel, XAxiDma_Config::MicroDmaMode, XAxiDma_Config::Mm2SBurstSize, XAxiDma_Config::Mm2SDataWidth, XAxiDma_Config::Mm2sNumChannels, XAxiDma_BdRing::RingIndex, XAxiDma_BdRing::RunState, XAxiDma_Config::S2MmBurstSize, XAxiDma_Config::S2MmDataWidth, XAxiDma_Config::S2MmNumChannels, XAxiDma_Config::SgLengthWidth, XAxiDma_Reset, XAxiDma_ResetIsDone, XAXIDMA_RX_OFFSET, XAXIDMA_TX_OFFSET.
Referenced by AxiDMASelfTestExample, main, XAxiDma_SimplePollExample.
void XAxiDma_Reset(XAxiDma *InstancePtr)
Reset both TX and RX channels of a DMA engine.
Reset one channel resets the whole AXI DMA engine.Any DMA transaction in progress will finish gracefully before engine starts reset. Any other transactions that have been submitted to hardware will be discarded by the hardware. InstancePtr is a pointer to the DMA engine instance to be worked on. None After the reset: All interrupts are disabled.Engine is halted
References XAxiDma_BdRing::RunState, XAxiDma_BdRingSnapShotCurrBd, XAXIDMA_CR_OFFSET, XAXIDMA_CR_RESET_MASK, XAxiDma_GetRxIndexRing, XAxiDma_GetTxRing, XAxiDma_HasSg, XAXIDMA_RX_OFFSET, XAXIDMA_TX_OFFSET, XAxiDma_WriteReg.
Referenced by main, XAxiDma_CfgInitialize, XAxiDma_Selftest.
int XAxiDma_ResetIsDone(XAxiDma *InstancePtr)
Check whether reset is done.
InstancePtr is a pointer to the DMA engine instance to be worked on. 1 if reset is done. 0 if reset is not done None
References XAxiDma_BdRing::ChanBase, XAXIDMA_CR_OFFSET, XAXIDMA_CR_RESET_MASK, XAxiDma_GetRxRing, XAxiDma_GetTxRing, XAxiDma_ReadReg.
Referenced by XAxiDma_CfgInitialize, XAxiDma_Selftest.
int XAxiDma_Pause(XAxiDma *InstancePtr)
Pause DMA transactions on both channels.
If the engine is running and doing transfers, this function does not stop the DMA transactions immediately, because then hardware will throw away our previously queued transfers. All submitted transfers will finish. Transfers submitted after this function will not start until XAxiDma_BdRingStart() or XAxiDma_Resume() is called. InstancePtr is a pointer to the DMA engine instance to be worked on. XST_SUCCESS if successfulXST_NOT_SGDMA, if the driver instance is not initialized None
References XAxiDma_BdRing::ChanBase, XAxiDma_BdRing::RunState, XAXIDMA_CR_OFFSET, XAXIDMA_CR_RUNSTOP_MASK, XAxiDma_GetRxIndexRing, XAxiDma_GetTxRing, XAxiDma_HasSg, XAxiDma_ReadReg, XAxiDma_WriteReg.
int XAxiDma_Resume(XAxiDma *InstancePtr)
Resume DMA transactions on both channels.
InstancePtr is a pointer to the DMA engine instance to be worked on. XST_SUCCESS for successXST_NOT_SGDMA if the driver instance has not been initializedXST_DMA_ERROR if one of the channels fails to start None
References XAxiDma_BdRing::RunState, XAxiDma_BdRingStart, XAxiDma_GetRxIndexRing, XAxiDma_GetTxRing, XAxiDma_HasSg.
u32 XAxiDma_Busy(XAxiDma *InstancePtr, int Direction)
This function checks whether specified DMA channel is busy.
InstancePtr is the driver instance we are working on Direction is DMA transfer direction, valid values are XAXIDMA_DMA_TO_DEVICE.XAXIDMA_DEVICE_TO_DMA. - TRUE if channel is busy FALSE if channel is idle None.
References XAXIDMA_IDLE_MASK, XAxiDma_ReadReg, XAXIDMA_RX_OFFSET, XAXIDMA_SR_OFFSET.
Referenced by XAxiDma_SimplePollExample, XAxiDma_SimpleTransfer.
u32 XAxiDma_SimpleTransfer(XAxiDma *InstancePtr, UINTPTR BuffAddr, u32 Length, int Direction)
This function does one simple transfer submission.
It checks in the following sequence: if engine is busy, cannot submitif engine is in SG mode , cannot submit InstancePtr is the pointer to the driver instance BuffAddr is the address of the source/destination buffer Length is the length of the transfer Direction is DMA transfer direction, valid values are XAXIDMA_DMA_TO_DEVICE.XAXIDMA_DEVICE_TO_DMA. XST_SUCCESS for success of submissionXST_FAILURE for submission failure, maybe caused by: Another simple transfer is still goingXST_INVALID_PARAM if:Length out of valid range [1:8M] Or, address not aligned when DRE is not built in This function is used only when system is configured as Simple mode.
References XAxiDma::AddrWidth, XAxiDma_BdRing::ChanBase, XAXIDMA_BUFFLEN_OFFSET, XAxiDma_Busy, XAXIDMA_CR_OFFSET, XAXIDMA_CR_RUNSTOP_MASK, XAXIDMA_DESTADDR_MSB_OFFSET, XAXIDMA_DESTADDR_OFFSET, XAXIDMA_HALTED_MASK, XAxiDma_HasSg, XAXIDMA_MICROMODE_MIN_BUF_ALIGN, XAxiDma_ReadReg, XAXIDMA_SR_OFFSET, XAXIDMA_SRCADDR_MSB_OFFSET, XAXIDMA_SRCADDR_OFFSET, XAxiDma_WriteReg.
Referenced by main, XAxiDma_SimplePollExample.
int XAxiDma_SelectKeyHole(XAxiDma *InstancePtr, int Direction, int Select)
This function Enable or Disable KeyHole Feature.
InstancePtr is the driver instance we are working on Direction is DMA transfer direction, valid values are XAXIDMA_DMA_TO_DEVICE.XAXIDMA_DEVICE_TO_DMA. Select is the option to enable (TRUE) or disable (FALSE). - XST_SUCCESS for success None.
References XAXIDMA_CR_KEYHOLE_MASK, XAXIDMA_CR_OFFSET, XAxiDma_ReadReg, XAXIDMA_RX_OFFSET, XAxiDma_WriteReg.
int XAxiDma_SelectCyclicMode(XAxiDma *InstancePtr, int Direction, int Select)
This function Enable or Disable Cyclic Mode Feature.
InstancePtr is the driver instance we are working on Direction is DMA transfer direction, valid values are XAXIDMA_DMA_TO_DEVICE.XAXIDMA_DEVICE_TO_DMA. Select is the option to enable (TRUE) or disable (FALSE). - XST_SUCCESS for success None.
References XAXIDMA_CR_CYCLIC_MASK, XAXIDMA_CR_OFFSET, XAxiDma_ReadReg, XAXIDMA_RX_OFFSET, XAxiDma_WriteReg.
int XAxiDma_Selftest(XAxiDma *InstancePtr)
Runs a self-test on the driver/device.
This test perform a reset of the DMA device and checks the device is coming out of reset or not InstancePtr is a pointer to the XAxiDma instance. XST_SUCCESS if self-test was successful XST_FAILURE if the device is not coming out of reset. None.
References XAxiDma_Reset, XAxiDma_ResetIsDone.
Referenced by AxiDMASelfTestExample.