xaxidma_bdring.h
AXIDMA_CHANNEL_NOT_HALTED
AXIDMA_CHANNEL_HALTED
XAXIDMA_NO_CHANGE
XAXIDMA_ALL_BDS
XAxiDma_BdRingCntCalc
Use this macro at initialization time to determine how many BDs will fit within the given memory constraints.
The results of this macro can be provided to XAxiDma_BdRingCreate(). Alignment specifies what byte alignment the BDs must fall on and must be a power of 2 to get an accurate calculation (32, 64, 126,...) Bytes is the number of bytes to be used to store BDs. Number of BDs that can fit in the given memory area C-style signature: int XAxiDma_BdRingCntCalc(u32 Alignment, u32 Bytes) This function is used only when system is configured as SG mode
XAxiDma_BdRingMemCalc
Use this macro at initialization time to determine how many bytes of memory are required to contain a given number of BDs at a given alignment.
Alignment specifies what byte alignment the BDs must fall on. This parameter must be a power of 2 to get an accurate calculation (32, 64,128,...) NumBd is the number of BDs to calculate memory size requirements The number of bytes of memory required to create a BD list with the given memory constraints. C-style signature: int XAxiDma_BdRingMemCalc(u32 Alignment, u32 NumBd) This function is used only when system is configured as SG mode
XAxiDma_BdRingGetCnt
Return the total number of BDs allocated by this channel with XAxiDma_BdRingCreate().
RingPtr is the BD ring to operate on. The total number of BDs allocated for this channel. C-style signature: int XAxiDma_BdRingGetCnt(XAxiDma_BdRing* RingPtr) This function is used only when system is configured as SG mode
XAxiDma_BdRingGetFreeCnt
Return the number of BDs allocatable with XAxiDma_BdRingAlloc() for pre- processing.
RingPtr is the BD ring to operate on. The number of BDs currently allocatable. C-style signature: int XAxiDma_BdRingGetFreeCnt(XAxiDma_BdRing* RingPtr) This function is used only when system is configured as SG mode
XAxiDma_BdRingSnapShotCurrBd
Snap shot the latest BD a BD ring is processing.
RingPtr is the BD ring to operate on. None C-style signature: void XAxiDma_BdRingSnapShotCurrBd(XAxiDma_BdRing* RingPtr) This function is used only when system is configured as SG mode
Referenced by XAxiDma_Reset.
XAxiDma_BdRingGetCurrBd
Get the BD a BD ring is processing.
RingPtr is the BD ring to operate on. The current BD that the BD ring is working on C-style signature: XAxiDma_Bd * XAxiDma_BdRingGetCurrBd(XAxiDma_BdRing* RingPtr) This function is used only when system is configured as SG mode
XAxiDma_BdRingNext
Return the next BD in the ring.
RingPtr is the BD ring to operate on. BdPtr is the current BD. The next BD in the ring relative to the BdPtr parameter. C-style signature: XAxiDma_Bd XAxiDma_BdRingNext(XAxiDma_BdRing RingPtr, XAxiDma_Bd *BdPtr) This function is used only when system is configured as SG mode
Referenced by XAxiDma_BdRingFromHw, XAxiDma_BdRingToHw, XAxiDma_UpdateBdRingCDesc.
XAxiDma_BdRingPrev
Return the previous BD in the ring.
RingPtr is the DMA channel to operate on. BdPtr is the current BD. The previous BD in the ring relative to the BdPtr parameter. C-style signature: XAxiDma_Bd XAxiDma_BdRingPrev(XAxiDma_BdRing RingPtr, XAxiDma_Bd *BdPtr) This function is used only when system is configured as SG mode
XAxiDma_BdRingGetSr
Retrieve the contents of the channel status register.
RingPtr is the channel instance to operate on. Current contents of status register C-style signature: u32 XAxiDma_BdRingGetSr(XAxiDma_BdRing* RingPtr) This function is used only when system is configured as SG mode
XAxiDma_BdRingGetError
Get error bits of a DMA channel.
RingPtr is the channel instance to operate on. Error bits in the status register, they should be interpreted with XAXIDMA_ERR_*_MASK defined in xaxidma_hw.h C-style signature: u32 XAxiDma_BdRingGetError(XAxiDma_BdRing* RingPtr) This function is used only when system is configured as SG mode
XAxiDma_BdRingHwIsStarted
Check whether a DMA channel is started, meaning the channel is not halted.
RingPtr is the channel instance to operate on. 1 if channel is started0 otherwise C-style signature: int XAxiDma_BdRingHwIsStarted(XAxiDma_BdRing* RingPtr)
Referenced by XAxiDma_StartBdRingHw, XAxiDma_UpdateBdRingCDesc.
XAxiDma_BdRingBusy
Check if the current DMA channel is busy with a DMA operation.
RingPtr is the channel instance to operate on. 1 if the DMA is busy.0 otherwise C-style signature: int XAxiDma_BdRingBusy(XAxiDma_BdRing* RingPtr) This function is used only when system is configured as SG mode
XAxiDma_BdRingIntEnable
Set interrupt enable bits for a channel.
This operation will modify the XAXIDMA_CR_OFFSET register. RingPtr is the channel instance to operate on. Mask consists of the interrupt signals to enable.Bits not specified in the mask are not affected. C-style signature: void XAxiDma_BdRingIntEnable(XAxiDma_BdRing* RingPtr, u32 Mask) This function is used only when system is configured as SG mode
XAxiDma_BdRingIntGetEnabled
Get enabled interrupts of a channel.
It is in XAXIDMA_CR_OFFSET register. RingPtr is the channel instance to operate on. Enabled interrupts of a channel. Use XAXIDMA_IRQ_* defined in xaxidma_hw.h to interpret this returned value. C-style signature: u32 XAxiDma_BdRingIntGetEnabled(XAxiDma_BdRing* RingPtr) This function is used only when system is configured as SG mode
XAxiDma_BdRingIntDisable
Clear interrupt enable bits for a channel.
It modifies the XAXIDMA_CR_OFFSET register. RingPtr is the channel instance to operate on. Mask consists of the interrupt signals to disable.Bits not specified in the Mask are not affected. C-style signature: void XAxiDma_BdRingIntDisable(XAxiDma_BdRing* RingPtr, u32 Mask) This function is used only when system is configured as SG mode
XAxiDma_BdRingGetIrq
Retrieve the contents of the channel's IRQ register XAXIDMA_SR_OFFSET.
This operation can be used to see which interrupts are pending. RingPtr is the channel instance to operate on. Current contents of the IRQ_OFFSET register. Use XAXIDMA_IRQ_*** values defined in xaxidma_hw.h to interpret the returned value. C-style signature: u32 XAxiDma_BdRingGetIrq(XAxiDma_BdRing* RingPtr) This function is used only when system is configured as SG mode
XAxiDma_BdRingAckIrq
Acknowledge asserted interrupts.
It modifies XAXIDMA_SR_OFFSET register. A mask bit set for an unasserted interrupt has no effect. RingPtr is the channel instance to operate on. Mask are the interrupt signals to acknowledge C-style signature: void XAxiDma_BdRingAckIrq(XAxiDma_BdRing* RingPtr) This function is used only when system is configured as SG mode
XAxiDma_BdRingEnableCyclicDMA
Enable Cyclic DMA Mode.
RingPtr is the channel instance to operate on. C-style signature: void XAxiDma_BdRingEnableCyclicDMA(XAxiDma_BdRing* RingPtr) This function is used only when system is configured as SG mode
int XAxiDma_StartBdRingHw(XAxiDma_BdRing *RingPtr)
Start a DMA channel and Allow DMA transactions to commence on a given channel if descriptors are ready to be processed.
After a DMA channel is started, it is not halted, and it is idle (no active DMA transfers). RingPtr is the Channel instance to be worked on XST_SUCCESS upon successXST_DMA_ERROR if no valid BD available to put into current BD register This function can be used only when DMA is in SG mode
References XAxiDma_BdRing::ChanBase, XAxiDma_BdRing::Cyclic, XAxiDma_BdRing::CyclicBd, XAxiDma_BdRing::HwCnt, XAxiDma_BdRing::HwTail, XAxiDma_BdRing::IsRxChannel, XAxiDma_BdRing::RingIndex, XAxiDma_BdRing::RunState, XAXIDMA_BD_STS_COMPLETE_MASK, XAXIDMA_BD_STS_OFFSET, XAxiDma_BdRead, XAxiDma_BdRingHwIsStarted, XAXIDMA_CR_OFFSET, XAXIDMA_CR_RUNSTOP_MASK, XAXIDMA_DESC_LSB_MASK, XAxiDma_ReadReg, XAXIDMA_RX_NDESC_OFFSET, XAXIDMA_RX_TDESC0_MSB_OFFSET, XAXIDMA_RX_TDESC0_OFFSET, XAXIDMA_TDESC_MSB_OFFSET, XAXIDMA_TDESC_OFFSET, XAxiDma_WriteReg.
Referenced by XAxiDma_BdRingStart.
int XAxiDma_UpdateBdRingCDesc(XAxiDma_BdRing *RingPtr)
Update Current Descriptor.
RingPtr is the Channel instance to be worked on XST_SUCCESS upon successXST_DMA_ERROR if no valid BD available to put into current BD register This function can be used only when DMA is in SG mode
References XAxiDma_BdRing::AllCnt, XAxiDma_BdRing::BdaRestart, XAxiDma_BdRing::ChanBase, XAxiDma_BdRing::IsRxChannel, XAxiDma_BdRing::RingIndex, XAxiDma_BdRing::RunState, XAxiDma_BdHwCompleted, XAxiDma_BdRingHwIsStarted, XAxiDma_BdRingNext, XAXIDMA_CDESC_MSB_OFFSET, XAXIDMA_CDESC_OFFSET, XAXIDMA_DESC_LSB_MASK, XAXIDMA_RX_CDESC0_MSB_OFFSET, XAXIDMA_RX_CDESC0_OFFSET, XAXIDMA_RX_NDESC_OFFSET, XAxiDma_WriteReg.
Referenced by XAxiDma_BdRingStart.
u32 XAxiDma_BdRingCreate(XAxiDma_BdRing *RingPtr, UINTPTR PhysAddr, UINTPTR VirtAddr, u32 Alignment, int BdCount)
Using a memory segment allocated by the caller, This fundtion creates and setup the BD ring.
RingPtr is the BD ring instance to be worked on. PhysAddr is the physical base address of application memory region. VirtAddr is the virtual base address of the application memory region.If address translation is not being utilized, then VirtAddr should be equivalent to PhysAddr. Alignment governs the byte alignment of individual BDs. This function will enforce a minimum alignment of XAXIDMA_BD_MINIMUM_ALIGNMENT bytes with no maximum as long as it is specified as a power of 2. BdCount is the number of BDs to setup in the application memory region. It is assumed the region is large enough to contain the BDs.Refer to the "SGDMA Ring Creation" section in xaxidma.h for more information. The minimum valid value for this parameter is 1. XST_SUCCESS if initialization was successful XST_NO_FEATURE if the provided instance is a non SGDMA type of DMA channel. XST_INVALID_PARAM under any of the following conditions: 1) BdCount is not positive 2) PhysAddr and/or VirtAddr are not aligned to the given Alignment parameter;3) Alignment parameter does not meet minimum requirements or is not a power of 2 value. XST_DMA_SG_LIST_ERROR if the memory segment containing the list spans over address 0x00000000 in virtual address space. This function can be used only when DMA is in SG mode
References XAxiDma_BdRing::AllCnt, XAxiDma_BdRing::BdaRestart, XAxiDma_BdRing::Cyclic, XAxiDma_BdRing::CyclicBd, XAxiDma_BdRing::FirstBdAddr, XAxiDma_BdRing::FirstBdPhysAddr, XAxiDma_BdRing::FreeCnt, XAxiDma_BdRing::FreeHead, XAxiDma_BdRing::HasStsCntrlStrm, XAxiDma_BdRing::HwCnt, XAxiDma_BdRing::HwHead, XAxiDma_BdRing::HwTail, XAxiDma_BdRing::LastBdAddr, XAxiDma_BdRing::Length, XAxiDma_BdRing::PostCnt, XAxiDma_BdRing::PostHead, XAxiDma_BdRing::PreCnt, XAxiDma_BdRing::PreHead, XAxiDma_BdRing::RunState, XAxiDma_BdRing::Separation, XAXIDMA_BD_HAS_DRE_OFFSET, XAXIDMA_BD_HAS_DRE_SHIFT, XAXIDMA_BD_HAS_STSCNTRL_OFFSET, XAXIDMA_BD_MINIMUM_ALIGNMENT, XAXIDMA_BD_NDESC_MSB_OFFSET, XAXIDMA_BD_NDESC_OFFSET, XAxiDma_BdWrite, XAXIDMA_DESC_LSB_MASK.
int XAxiDma_BdRingClone(XAxiDma_BdRing *RingPtr, XAxiDma_Bd *SrcBdPtr)
Clone the given BD into every BD in the ring.
Only the fields offset from XAXIDMA_BD_START_CLEAR are copied, for XAXIDMA_BD_BYTES_TO_CLEAR bytes. This covers: BufferAddr, Control/Buffer length, status, APP words 0 - 4, and software ID fields.This function can be called only when all BDs are in the free group such as immediately after creation of the ring. This prevents modification of BDs while they are in use by hardware or the application. RingPtr is the BD ring instance to be worked on. SrcBdPtr is the source BD template to be cloned into the list. XST_SUCCESS if the list was modified.XST_DMA_SG_NO_LIST if a list has not been created.XST_DEVICE_IS_STARTED if the DMA channel has not been stopped.XST_DMA_SG_LIST_ERROR if some of the BDs in this channel are under hardware or application control. This function can be used only when DMA is in SG mode
References XAxiDma_BdRing::AllCnt, XAxiDma_BdRing::FirstBdAddr, XAxiDma_BdRing::FreeCnt, XAxiDma_BdRing::RunState, XAxiDma_BdRing::Separation, XAXIDMA_BD_BYTES_TO_CLEAR, XAXIDMA_BD_START_CLEAR, XAXIDMA_BD_STS_COMPLETE_MASK, XAXIDMA_BD_STS_OFFSET, XAxiDma_BdRead, XAxiDma_BdWrite.
int XAxiDma_BdRingAlloc(XAxiDma_BdRing *RingPtr, int NumBd, XAxiDma_Bd **BdSetPtr)
Reserve locations in the BD ring.
The set of returned BDs may be modified in preparation for future DMA transactions. Once the BDs are ready to be submitted to hardware, the application must call XAxiDma_BdRingToHw() in the same order which they were allocated here. Example: NumBd = 2; Status = XDsma_RingBdAlloc(MyRingPtr, NumBd, &MyBdSet); if (Status != XST_SUCCESS) { // Not enough BDs available for the request } CurBd = MyBdSet; for (i=0; i<NumBd; i++) { // Prepare CurBd..... // Onto next BD CurBd = XAxiDma_BdRingNext(MyRingPtr, CurBd); } // Give list to hardware Status = XAxiDma_BdRingToHw(MyRingPtr, NumBd, MyBdSet); A more advanced use of this function may allocate multiple sets of BDs. They must be allocated and given to hardware in the correct sequence: // Legal XAxiDma_BdRingAlloc(MyRingPtr, NumBd1, &MySet1); XAxiDma_BdRingToHw(MyRingPtr, NumBd1, MySet1); // Legal XAxiDma_BdRingAlloc(MyRingPtr, NumBd1, &MySet1); XAxiDma_BdRingAlloc(MyRingPtr, NumBd2, &MySet2); XAxiDma_BdRingToHw(MyRingPtr, NumBd1, MySet1); XAxiDma_BdRingToHw(MyRingPtr, NumBd2, MySet2); // Not legal XAxiDma_BdRingAlloc(MyRingPtr, NumBd1, &MySet1); XAxiDma_BdRingAlloc(MyRingPtr, NumBd2, &MySet2); XAxiDma_BdRingToHw(MyRingPtr, NumBd2, MySet2); XAxiDma_BdRingToHw(MyRingPtr, NumBd1, MySet1); Use the API defined in xaxidmabd.h to modify individual BDs. Traversal of the BD set can be done using XAxiDma_BdRingNext() and XAxiDma_BdRingPrev(). RingPtr is a pointer to the descriptor ring instance to be worked on. NumBd is the number of BDs to allocate BdSetPtr is an output parameter, it points to the first BD available for modification. XST_SUCCESS if the requested number of BDs were returned in the BdSetPtr parameter.XST_INVALID_PARAM if passed in NumBd is not positiveXST_FAILURE if there were not enough free BDs to satisfy the request. This function should not be preempted by another XAxiDma_BdRing function call that modifies the BD space. It is the caller's responsibility to provide a mutual exclusion mechanism. Do not modify more BDs than the number requested with the NumBd parameter. Doing so will lead to data corruption and system instability.This function can be used only when DMA is in SG mode
References XAxiDma_BdRing::FreeCnt, XAxiDma_BdRing::FreeHead, XAxiDma_BdRing::PreCnt.
int XAxiDma_BdRingUnAlloc(XAxiDma_BdRing *RingPtr, int NumBd, XAxiDma_Bd *BdSetPtr)
Fully or partially undo an XAxiDma_BdRingAlloc() operation.
Use this function if all the BDs allocated by XAxiDma_BdRingAlloc() could not be transferred to hardware with XAxiDma_BdRingToHw().This function releases the BDs after they have been allocated but before they have been given to hardware.This function is not the same as XAxiDma_BdRingFree(). The Free function returns BDs to the free list after they have been processed by hardware, while UnAlloc returns them before being processed by hardware.There are two scenarios where this function can be used. Full UnAlloc or Partial UnAlloc. A Full UnAlloc means all the BDs Alloc'd will be returned: Status = XAxiDma_BdRingAlloc(MyRingPtr, 10, &BdPtr); ... ... if (Error) { Status = XAxiDma_BdRingUnAlloc(MyRingPtr, 10, &BdPtr); } A partial UnAlloc means some of the BDs Alloc'd will be returned: Status = XAxiDma_BdRingAlloc(MyRingPtr, 10, &BdPtr); BdsLeft = 10; CurBdPtr = BdPtr; while (BdsLeft) { if (Error) { Status = XAxiDma_BdRingUnAlloc(MyRingPtr, BdsLeft, CurBdPtr); } CurBdPtr = XAxiDma_BdRingNext(MyRingPtr, CurBdPtr); BdsLeft--; } A partial UnAlloc must include the last BD in the list that was Alloc'd. RingPtr is a pointer to the descriptor ring instance to be worked on. NumBd is the number of BDs to unallocate BdSetPtr points to the first of the BDs to be returned. XST_SUCCESS if the BDs were unallocated.XST_INVALID_PARAM if passed in NumBd is negativeXST_FAILURE if NumBd parameter was greater that the number of BDs in the preprocessing state. This function should not be preempted by another XAxiDma ring function call that modifies the BD space. It is the caller's responsibility to provide a mutual exclusion mechanism. This function can be used only when DMA is in SG mode
References XAxiDma_BdRing::FreeCnt, XAxiDma_BdRing::FreeHead, XAxiDma_BdRing::PreCnt.
int XAxiDma_BdRingToHw(XAxiDma_BdRing *RingPtr, int NumBd, XAxiDma_Bd *BdSetPtr)
Enqueue a set of BDs to hardware that were previously allocated by XAxiDma_BdRingAlloc().
Once this function returns, the argument BD set goes under hardware control. Changes to these BDs should be held until they are finished by hardware to avoid data corruption and system instability.For transmit, the set will be rejected if the last BD of the set does not mark the end of a packet or the first BD does not mark the start of a packet. RingPtr is a pointer to the descriptor ring instance to be worked on. NumBd is the number of BDs in the set. BdSetPtr is the first BD of the set to commit to hardware. XST_SUCCESS if the set of BDs was accepted and enqueued to hardwareXST_INVALID_PARAM if passed in NumBd is negativeXST_FAILURE if the set of BDs was rejected because the first BD does not have its start-of-packet bit set, or the last BD does not have its end-of-packet bit set, or any one of the BDs has 0 length.XST_DMA_SG_LIST_ERROR if this function was called out of sequence with XAxiDma_BdRingAlloc() This function should not be preempted by another XAxiDma ring function call that modifies the BD space. It is the caller's responsibility to provide a mutual exclusion mechanism. This function can be used only when DMA is in SG mode
References XAxiDma_BdRing::ChanBase, XAxiDma_BdRing::Cyclic, XAxiDma_BdRing::CyclicBd, XAxiDma_BdRing::HwCnt, XAxiDma_BdRing::HwTail, XAxiDma_BdRing::IsRxChannel, XAxiDma_BdRing::PreCnt, XAxiDma_BdRing::PreHead, XAxiDma_BdRing::RingIndex, XAxiDma_BdRing::RunState, XAXIDMA_BD_CTRL_LEN_OFFSET, XAXIDMA_BD_CTRL_TXEOF_MASK, XAXIDMA_BD_CTRL_TXSOF_MASK, XAXIDMA_BD_STS_COMPLETE_MASK, XAXIDMA_BD_STS_OFFSET, XAxiDma_BdGetCtrl, XAxiDma_BdGetLength, XAxiDma_BdGetSts, XAxiDma_BdRead, XAxiDma_BdRingNext, XAxiDma_BdWrite, XAXIDMA_DESC_LSB_MASK, XAXIDMA_RX_NDESC_OFFSET, XAXIDMA_RX_TDESC0_MSB_OFFSET, XAXIDMA_RX_TDESC0_OFFSET, XAXIDMA_TDESC_MSB_OFFSET, XAXIDMA_TDESC_OFFSET, XAxiDma_WriteReg.
int XAxiDma_BdRingFromHw(XAxiDma_BdRing *RingPtr, int BdLimit, XAxiDma_Bd **BdSetPtr)
Returns a set of BD(s) that have been processed by hardware.
The returned BDs may be examined by the application to determine the outcome of the DMA transactions. Once the BDs have been examined, the application must call XAxiDma_BdRingFree() in the same order which they were retrieved here.Example: NumBd = XAxiDma_BdRingFromHw(MyRingPtr, XAXIDMA_ALL_BDS, &MyBdSet); if (NumBd == 0) { // hardware has nothing ready for us yet } CurBd = MyBdSet; for (i=0; i<NumBd; i++) { // Examine CurBd for post processing..... // Onto next BD CurBd = XAxiDma_BdRingNext(MyRingPtr, CurBd); } XAxiDma_BdRingFree(MyRingPtr, NumBd, MyBdSet); // Return the list A more advanced use of this function may allocate multiple sets of BDs. They must be retrieved from hardware and freed in the correct sequence: // Legal XAxiDma_BdRingFromHw(MyRingPtr, NumBd1, &MySet1); XAxiDma_BdRingFree(MyRingPtr, NumBd1, MySet1); // Legal XAxiDma_BdRingFromHw(MyRingPtr, NumBd1, &MySet1); XAxiDma_BdRingFromHw(MyRingPtr, NumBd2, &MySet2); XAxiDma_BdRingFree(MyRingPtr, NumBd1, MySet1); XAxiDma_BdRingFree(MyRingPtr, NumBd2, MySet2); // Not legal XAxiDma_BdRingFromHw(MyRingPtr, NumBd1, &MySet1); XAxiDma_BdRingFromHw(MyRingPtr, NumBd2, &MySet2); XAxiDma_BdRingFree(MyRingPtr, NumBd2, MySet2); XAxiDma_BdRingFree(MyRingPtr, NumBd1, MySet1); If hardware has partially completed a packet spanning multiple BDs, then none of the BDs for that packet will be included in the results. RingPtr is a pointer to the descriptor ring instance to be worked on. BdLimit is the maximum number of BDs to return in the set. Use XAXIDMA_ALL_BDS to return all BDs that have been processed. BdSetPtr is an output parameter, it points to the first BD available for examination. The number of BDs processed by hardware. A value of 0 indicates that no data is available. No more than BdLimit BDs will be returned. Treat BDs returned by this function as read-only. This function should not be preempted by another XAxiDma ring function call that modifies the BD space. It is the caller's responsibility to provide a mutual exclusion mechanism. This function can be used only when DMA is in SG mode
References XAxiDma_BdRing::Cyclic, XAxiDma_BdRing::HwCnt, XAxiDma_BdRing::HwHead, XAxiDma_BdRing::HwTail, XAxiDma_BdRing::IsRxChannel, XAxiDma_BdRing::PostCnt, XAXIDMA_BD_CTRL_LEN_OFFSET, XAXIDMA_BD_CTRL_TXEOF_MASK, XAXIDMA_BD_STS_COMPLETE_MASK, XAXIDMA_BD_STS_OFFSET, XAXIDMA_BD_STS_RXEOF_MASK, XAxiDma_BdRead, XAxiDma_BdRingNext, XAxiDma_BdWrite.
int XAxiDma_BdRingFree(XAxiDma_BdRing *RingPtr, int NumBd, XAxiDma_Bd *BdSetPtr)
Frees a set of BDs that had been previously retrieved with XAxiDma_BdRingFromHw().
RingPtr is a pointer to the descriptor ring instance to be worked on. NumBd is the number of BDs to free. BdSetPtr is the head of a list of BDs returned by XAxiDma_BdRingFromHw(). XST_SUCCESS if the set of BDs was freed.XST_INVALID_PARAM if NumBd is negativeXST_DMA_SG_LIST_ERROR if this function was called out of sequence with XAxiDma_BdRingFromHw(). This function should not be preempted by another XAxiDma function call that modifies the BD space. It is the caller's responsibility to ensure mutual exclusion. This function can be used only when DMA is in SG mode
References XAxiDma_BdRing::FreeCnt, XAxiDma_BdRing::PostCnt, XAxiDma_BdRing::PostHead.
int XAxiDma_BdRingStart(XAxiDma_BdRing *RingPtr)
Start a DMA channel, updates current descriptors and Allow DMA transactions to commence on a given channel if descriptors are ready to be processed.
After a DMA channel is started, it is not halted, and it is idle (no active DMA transfers). RingPtr is the Channel instance to be worked on XST_SUCCESS upon successXST_DMA_ERROR if no valid BD available to put into current BD register This function can be used only when DMA is in SG mode
References XAxiDma_StartBdRingHw, XAxiDma_UpdateBdRingCDesc.
Referenced by XAxiDma_Resume.
int XAxiDma_BdRingSetCoalesce(XAxiDma_BdRing *RingPtr, u32 Counter, u32 Timer)
Set interrupt coalescing parameters for the given descriptor ring channel.
RingPtr is a pointer to the descriptor ring instance to be worked on. Counter sets the packet counter on the channel. Valid range is 1..255.XAXIDMA_NO_CHANGE to leave this setting unchanged. Timer sets the waitbound timer on the channel. Valid range is 0..255. XAXIDMA_NO_CHANGE to leave this setting unchanged. Each unit depend on hardware building parameter C_DLYTMR_RESOLUTION,which is in the range from 0 to 100,000 clock cycles. A value of 0 disables the delay interrupt. XST_SUCCESS if interrupt coalescing settings updatedXST_FAILURE if Counter or Timer parameters are out of range This function can be used only when DMA is in SG mode
References XAxiDma_BdRing::ChanBase, XAXIDMA_COALESCE_MASK, XAXIDMA_CR_OFFSET, XAXIDMA_DELAY_MASK, XAxiDma_ReadReg, XAxiDma_WriteReg.
void XAxiDma_BdRingGetCoalesce(XAxiDma_BdRing *RingPtr, u32 *CounterPtr, u32 *TimerPtr)
Retrieve current interrupt coalescing parameters from the given descriptor ring channel.
RingPtr is a pointer to the descriptor ring instance to be worked on. CounterPtr points to a memory location where the current packet counter will be written. TimerPtr points to a memory location where the current waitbound timer will be written. The passed in parameters, CounterPtr and TimerPtr, holds the references to the return values. This function can be used only when DMA is in SG mode
References XAxiDma_BdRing::ChanBase, XAXIDMA_COALESCE_MASK, XAXIDMA_CR_OFFSET, XAXIDMA_DELAY_MASK, XAxiDma_ReadReg.
int XAxiDma_BdRingCheck(XAxiDma_BdRing *RingPtr)
Check the internal data structures of the BD ring for the provided channel.
The following checks are made: - The BD ring is linked correctly in physical address space. - The internal pointers point to BDs in the ring. - The internal counters add up. The channel should be stopped (through XAxiDma_Pause() or XAxiDma_Reset()) prior to calling this function. RingPtr is a pointer to the descriptor ring to be worked on. XST_SUCCESS if no errors were found.XST_DMA_SG_NO_LIST if the ring has not been created.XST_IS_STARTED if the channel is not stopped.XST_DMA_SG_LIST_ERROR if a problem is found with the internal data structures. If this value is returned, the channel should be reset,and the BD ring should be recreated through XAxiDma_BdRingCreate() to avoid data corruption or system instability. This function can be used only when DMA is in SG mode
References XAxiDma_BdRing::AllCnt, XAxiDma_BdRing::FirstBdAddr, XAxiDma_BdRing::FirstBdPhysAddr, XAxiDma_BdRing::FreeCnt, XAxiDma_BdRing::FreeHead, XAxiDma_BdRing::HwCnt, XAxiDma_BdRing::HwHead, XAxiDma_BdRing::HwTail, XAxiDma_BdRing::LastBdAddr, XAxiDma_BdRing::PostCnt, XAxiDma_BdRing::PostHead, XAxiDma_BdRing::PreCnt, XAxiDma_BdRing::PreHead, XAxiDma_BdRing::RunState, XAxiDma_BdRing::Separation, XAXIDMA_BD_NDESC_OFFSET, XAxiDma_BdRead.
void XAxiDma_BdRingDumpRegs(XAxiDma_BdRing *RingPtr)
Dump the registers for a channel.
RingPtr is a pointer to the descriptor ring to be worked on. None This function can be used only when DMA is in SG mode
References XAxiDma_BdRing::ChanBase, XAxiDma_BdRing::RingIndex, XAXIDMA_CDESC_OFFSET, XAXIDMA_CR_OFFSET, XAxiDma_ReadReg, XAXIDMA_RX_CDESC0_OFFSET, XAXIDMA_RX_NDESC_OFFSET, XAXIDMA_RX_TDESC0_OFFSET, XAXIDMA_SR_OFFSET, XAXIDMA_TDESC_OFFSET.