canfd
XCANFD_MAX_SJW_VALUE
Synchronization Jump Width.
Referenced by XCanFd_SetBitTiming.
XCANFD_MAX_TS1_VALUE
Time Segment 1.
Referenced by XCanFd_SetBitTiming.
XCANFD_MAX_TS2_VALUE
Time Segment 2.
Referenced by XCanFd_SetBitTiming.
XCANFD_MAX_F_SJW_VALUE
Synchronization Jump Width for Data Phase.
Referenced by XCanFd_SetFBitTiming.
XCANFD_MAX_F_TS1_VALUE
Time Segment 1 for Data Phase.
Referenced by XCanFd_SetFBitTiming.
XCANFD_MAX_F_TS2_VALUE
Time Segment 2 for Data Phase.
Referenced by XCanFd_SetFBitTiming.
XCANFD_MODE_CONFIG
Configuration mode.
Referenced by main, XCanFd_EnterMode, XCanFd_GetMode, XCanFd_SelfTest, XCanFd_SetBaudRatePrescaler, XCanFd_SetBitTiming, XCanFd_SetFBaudRatePrescaler, XCanFd_SetFBitTiming, XCanFd_SetRxFilterPartition, XCanFd_SetRxIntrWatermark, XCanFd_SetRxIntrWatermarkFifo1, XCanFd_SetTxEventIntrWatermark, XCanFdPolledExample.
XCANFD_MODE_NORMAL
Normal mode.
Referenced by XCanFd_EnterMode, XCanFd_GetMode.
XCANFD_MODE_LOOPBACK
Loop Back mode.
Referenced by main, XCanFd_EnterMode, XCanFd_GetMode, XCanFd_SelfTest, XCanFdPolledExample.
XCANFD_MODE_SLEEP
Sleep mode.
Referenced by XCanFd_EnterMode, XCanFd_GetMode.
XCANFD_MODE_SNOOP
Snoop mode.
Referenced by XCanFd_EnterMode, XCanFd_GetMode.
XCANFD_MODE_ABR
Auto Bus-Off Recovery.
Referenced by XCanFd_EnterMode.
XCANFD_MODE_SBR
Starut Bus-Off Recovery.
Referenced by XCanFd_EnterMode.
XCANFD_MODE_PEE
Protocol Exception mode.
Referenced by XCanFd_EnterMode, XCanFd_GetMode.
XCANFD_MODE_DAR
Disable Auto Retransmission mode.
Referenced by XCanFd_EnterMode.
XCANFD_MODE_BR
Bus-Off Recovery Mode.
XCANFD_RX_FIFO_0
Selection for RX Fifo 0.
Referenced by XCanFd_GetNofMessages_Stored_Rx_Fifo, XCanFd_Recv_Sequential.
XCANFD_RX_FIFO_1
Selection for RX Fifo 1.
Referenced by XCanFd_Recv_Sequential.
XCANFD_HANDLER_SEND
Handler type for frame sending interrupt.
Referenced by main, XCanFd_SetHandler.
XCANFD_HANDLER_RECV
Handler type for frame reception interrupt.
Referenced by main, XCanFd_SetHandler.
XCANFD_HANDLER_ERROR
Handler type for error interrupt.
Referenced by main, XCanFd_SetHandler.
XCANFD_HANDLER_EVENT
Handler type for all other interrupts.
Referenced by main, XCanFd_SetHandler.
XCANFD_SRR_OFFSET
Software Reset Register.
Referenced by XCanFd_EnterMode.
XCANFD_MSR_OFFSET
Mode Select Register.
Referenced by XCanFd_EnterMode, XCanFd_SetBitRateSwitch_DisableNominal, XCanFd_SetBitRateSwitch_EnableNominal.
XCANFD_BRPR_OFFSET
Baud Rate Prescaler Register.
Referenced by XCanFd_GetBaudRatePrescaler, XCanFd_SetBaudRatePrescaler.
XCANFD_BTR_OFFSET
Bit Timing Register.
Referenced by XCanFd_GetBitTiming, XCanFd_SetBitTiming.
XCANFD_ECR_OFFSET
Error Counter Register.
Referenced by XCanFd_GetBusErrorCounter.
XCANFD_ESR_OFFSET
Error Status Register.
XCANFD_SR_OFFSET
Status Register.
XCANFD_ISR_OFFSET
Interrupt Status Register.
Referenced by XCanFd_Recv_Mailbox.
XCANFD_IER_OFFSET
Interrupt Enable Register.
Referenced by XCanFd_InterruptDisable, XCanFd_InterruptEnable.
XCANFD_ICR_OFFSET
Interrupt Clear Register.
Referenced by XCanFd_InterruptClear.
XCANFD_F_BRPR_OFFSET
Data Phase Baud Rate Prescalar Register.
Referenced by XCanFd_Disable_Tranceiver_Delay_Compensation, XCanFd_Enable_Tranceiver_Delay_Compensation, XCanFd_GetFBaudRatePrescaler, XCanFd_Set_Tranceiver_Delay_Compensation, XCanFd_SetFBaudRatePrescaler.
XCANFD_F_BTR_OFFSET
Data Phase Bit Timing Register.
Referenced by XCanFd_GetFBitTiming, XCanFd_SetFBitTiming.
XCANFD_TRR_OFFSET
Tx Buffer Ready Request Register.
Referenced by XCanFd_Addto_Queue, XCanFd_GetFreeBuffer, XCanFd_Pee_BusOff_Handler, XCanFd_Send, XCanFd_Send_Queue, XCanFd_TxBuffer_Cancel_Request.
XCANFD_IETRS_OFFSET
Tx Buffer Ready Request Served Interrupt Enable Register.
Referenced by XCanFd_InterruptDisable_ReadyRqt, XCanFd_InterruptEnable_ReadyRqt.
XCANFD_TCR_OFFSET
Tx Buffer Cancel Request Register.
Referenced by XCanFd_Pee_BusOff_Handler, XCanFd_TxBuffer_Cancel_Request.
XCANFD_IETCS_OFFSET
Tx Buffer Cancel Request Served Interrupt Enable Register.
Referenced by XCanFd_InterruptDisable_CancelRqt, XCanFd_InterruptEnable_CancelRqt.
XCANFD_RSD0_OFFSET
Reserved.
XCANFD_RSD1_OFFSET
Reserved.
XCANFD_RSD2_OFFSET
Reserved.
XCANFD_RSD3_OFFSET
Reserved.
XCANFD_RCS0_OFFSET
Rx Buffer Control Status 0 Register.
XCANFD_RCS1_OFFSET
Rx Buffer Control Status 1 Register.
XCANFD_RCS2_OFFSET
Rx Buffer Control Status 2 Register.
XCANFD_RCS_HCB_MASK
Rx Buffer Control Status Register Host Control Bit Mask.
Referenced by XCanFd_Recv_Mailbox.
XCANFD_RXBFLL1_OFFSET
Rx Buffer Full Interrupt Enable Register.
Referenced by XCanFd_InterruptDisable_RxBuffFull, XCanFd_InterruptEnable_RxBuffFull.
XCANFD_RXBFLL2_OFFSET
Rx Buffer Full Interrupt Enable Register.
Referenced by XCanFd_InterruptDisable_RxBuffFull, XCanFd_InterruptEnable_RxBuffFull.
XCANFD_MAILBOX_RB_MASK_BASE_OFFSET
Mailbox RxBuffer Mask Register.
XCANFD_MAILBOX_NXT_RB
Mailbox Next Buffer.
XCANFD_MBRXBUF_MASK
Mailbox Max Rx Buffer mask.
Referenced by XCanFd_RxBuff_MailBox_DeActive.
XCANFD_DLCR_TIMESTAMP_MASK
Dlc Register TimeStamp Mask.
XCANFD_TXFIFO_0_BASE_ID_OFFSET
Tx Message Buffer Element 0 ID Register.
XCANFD_TXFIFO_0_BASE_DLC_OFFSET
Tx Message Buffer Element 0 DLC Register.
XCANFD_TXFIFO_0_BASE_DW0_OFFSET
Tx Message Buffer Element 0 DW Register.
XCANFD_TXEFIFO_0_BASE_ID_OFFSET
Tx Event Message Buffer Element 0 ID Register.
XCANFD_TXEFIFO_0_BASE_DLC_OFFSET
Tx Event Message Buffer Element 0 DLC Register.
XCANFD_RXFIFO_0_BASE_ID_OFFSET
Rx Message Buffer Element 0 ID Register.
XCANFD_RXFIFO_0_BASE_DLC_OFFSET
Rx Message Buffer Element 0 DLC Register.
XCANFD_RXFIFO_0_BASE_DW0_OFFSET
Rx Message Buffer Element 0 DW Register.
XCANFD_RXFIFO_1_BUFFER_0_BASE_ID_OFFSET
Rx Message Buffer Element 0 ID Register.
XCANFD_RXFIFO_1_BUFFER_0_BASE_DLC_OFFSET
Rx Message Buffer Element 0 DLC Register.
XCANFD_RXFIFO_1_BUFFER_0_BASE_DW0_OFFSET
Rx Message Buffer Element 0 DW Register.
XCANFD_RXFIFO_NEXTID_OFFSET
Rx Message Buffer Element Next ID AT Offset.
XCANFD_RXFIFO_NEXTDLC_OFFSET
Rx Message Buffer Element Next DLC AT Offset.
XCANFD_RXFIFO_NEXTDW_OFFSET
Rx Message Buffer Element Next DW AT Offset.
XCANFD_DLCR_EDL_MASK
EDL Mask in DLC Register.
Referenced by XCanFd_Addto_Queue, XCanFd_Recv_Mailbox, XCanFd_Send.
XCANFD_DLCR_BRS_MASK
BRS Mask in DLC Register.
XCANFD_AFMR_BASE_OFFSET
Acceptance Filter Mask Register.
XCANFD_AFIDR_BASE_OFFSET
Acceptance Filter ID Register.
XCANFD_AFMR_NXT_OFFSET
Acceptance Filter Next Offset.
XCANFD_AFIDR_NXT_OFFSET
Acceptance Filter ID Next Offset.
XCANFD_AFR_OFFSET
Acceptance Filter Register.
Referenced by XCanFd_AcceptFilterDisable, XCanFd_AcceptFilterEnable, XCanFd_AcceptFilterGetEnabled.
XCANFD_FSR_OFFSET
Receive FIFO Status Register.
Referenced by XCanFd_GetNofMessages_Stored_Rx_Fifo, XCanFd_Recv_Sequential.
XCANFD_NOOF_AFR
Number Of Acceptance FIlter Registers.
Referenced by XCanFd_AcceptFilterGet.
XCANFD_WIR_OFFSET
Rx FIFO Water Mark Register.
Referenced by XCanFd_SetRxFilterPartition, XCanFd_SetRxIntrWatermark, XCanFd_SetRxIntrWatermarkFifo1.
XCANFD_WIR_MASK
Rx FIFO Full watermark Mask.
Referenced by XCanFd_SetRxIntrWatermark.
XCANFD_WM_FIFO0_THRESHOLD
Watermark Threshold Value.
Referenced by XCanFd_SetRxIntrWatermark.
XCANFD_WMR_RXFWM_1_SHIFT
RX FIFO 1 Full Watermark Mask.
Referenced by XCanFd_SetRxIntrWatermarkFifo1.
XCANFD_WMR_RXFP_MASK
Receive filter partition Mask.
Referenced by XCanFd_SetRxFilterPartition.
XCANFD_WMR_RXFP_SHIFT
Receive filter partition Mask.
Referenced by XCanFd_SetRxFilterPartition.
XCANFD_TXEVENT_WIR_OFFSET
TX FIFO Watermark Offset.
Referenced by XCanFd_SetTxEventIntrWatermark.
XCANFD_TXEVENT_WIR_MASK
TX Event Watermark Mask.
Referenced by XCanFd_SetTxEventIntrWatermark.
XCANFD_TIMESTAMPR_OFFSET
Time Stamp Register.
XCANFD_CTS_MASK
Time Stamp Counter Clear.
XCANFD_DAR_MASK
Disable AutoRetransmission.
XCANFD_SRR_CEN_MASK
Can Enable Mask.
Referenced by XCanFd_EnterMode, XCanFd_SetBitRateSwitch_DisableNominal, XCanFd_SetBitRateSwitch_EnableNominal.
XCANFD_SRR_SRST_MASK
Reset Mask.
XCANFD_MSR_LBACK_MASK
Loop Back Mode Select Mask.
Referenced by XCanFd_EnterMode.
XCANFD_MSR_SLEEP_MASK
Sleep Mode Select Mask.
Referenced by XCanFd_EnterMode.
XCANFD_MSR_BRSD_MASK
Bit Rate Switch Select Mask.
Referenced by XCanFd_SetBitRateSwitch_DisableNominal, XCanFd_SetBitRateSwitch_EnableNominal.
XCANFD_MSR_DAR_MASK
Disable Auto-Retransmission Select Mask.
Referenced by XCanFd_EnterMode.
XCANFD_MSR_SNOOP_MASK
Snoop Mode Select Mask.
Referenced by XCanFd_EnterMode.
XCANFD_MSR_DPEE_MASK
Protocol Exception Event Mask.
Referenced by XCanFd_EnterMode.
XCANFD_MSR_SBR_MASK
Start Bus-Off Recovery Mask.
Referenced by XCanFd_EnterMode.
XCANFD_MSR_ABR_MASK
Auto Bus-Off Recovery Mask.
Referenced by XCanFd_EnterMode.
XCANFD_MSR_CONFIG_MASK
Configuration Mode Mask.
Referenced by XCanFd_EnterMode.
XCANFD_BRPR_BRP_MASK
Baud Rate Prescaler Mask.
Referenced by XCanFd_GetFBaudRatePrescaler, XCanFd_SetFBaudRatePrescaler.
XCANFD_BTR_SJW_MASK
Sync Jump Width Mask.
Referenced by XCanFd_GetBitTiming, XCanFd_SetBitTiming.
XCANFD_BTR_TS2_MASK
Time Segment 2 Mask.
Referenced by XCanFd_GetBitTiming, XCanFd_SetBitTiming.
XCANFD_BTR_TS1_MASK
Time Segment 1 Mask.
Referenced by XCanFd_GetBitTiming, XCanFd_SetBitTiming.
XCANFD_F_BRPR_TDCMASK
Transceiver Delay compensation Offset Mask.
Referenced by XCanFd_Set_Tranceiver_Delay_Compensation.
XCANFD_BTR_TS2_SHIFT
Time Segment 2 Shift.
Referenced by XCanFd_GetBitTiming, XCanFd_SetBitTiming.
XCANFD_BTR_SJW_SHIFT
Sync Jump Width Shift.
Referenced by XCanFd_GetBitTiming, XCanFd_SetBitTiming.
XCANFD_F_BRPR_TDC_ENABLE_MASK
Transceiver Delay compensation Enable Maskk.
Referenced by XCanFd_Disable_Tranceiver_Delay_Compensation, XCanFd_Enable_Tranceiver_Delay_Compensation.
XCANFD_F_BTR_SJW_MASK
Sync Jump Width Mask.
Referenced by XCanFd_GetFBitTiming, XCanFd_SetFBitTiming.
XCANFD_F_BTR_TS2_MASK
Time Segment 2 Mask.
Referenced by XCanFd_GetFBitTiming, XCanFd_SetFBitTiming.
XCANFD_F_BTR_TS1_MASK
Time Segment 1 Mask.
Referenced by XCanFd_GetFBitTiming, XCanFd_SetFBitTiming.
XCANFD_F_BTR_TS2_SHIFT
Time Segment 2 Shift.
Referenced by XCanFd_GetFBitTiming, XCanFd_SetFBitTiming.
XCANFD_F_BTR_SJW_SHIFT
Sync Jump Width Shift.
Referenced by XCanFd_GetFBitTiming, XCanFd_SetFBitTiming.
XCANFD_ECR_REC_MASK
Receive Error Counter Mask.
Referenced by XCanFd_GetBusErrorCounter.
XCANFD_ECR_REC_SHIFT
Receive Error Counter Shift.
Referenced by XCanFd_GetBusErrorCounter.
XCANFD_ECR_TEC_MASK
Transmit Error Counter Mask.
Referenced by XCanFd_GetBusErrorCounter.
XCANFD_ESR_ACKER_MASK
ACK Error Mask.
Referenced by main.
XCANFD_ESR_BERR_MASK
Bit Error Mask.
Referenced by main.
XCANFD_ESR_STER_MASK
Stuff Error Mask.
Referenced by main.
XCANFD_ESR_FMER_MASK
Form Error Mask.
Referenced by main.
XCANFD_ESR_CRCER_MASK
CRC Error Mask.
Referenced by main.
XCANFD_ESR_F_BERR_MASK
F_Bit Error Mask.
Referenced by main.
XCANFD_ESR_F_STER_MASK
F_Stuff Error Mask.
Referenced by main.
XCANFD_ESR_F_FMER_MASK
F_Form Error Mask.
Referenced by main.
XCANFD_ESR_F_CRCER_MASK
F_CRC Error Mask.
XCANFD_SR_TDCV_MASK
Transceiver Dealy compensation Mask.
XCANFD_SR_SNOOP_MASK
Snoop Mode Mask.
Referenced by XCanFd_GetMode.
XCANFD_SR_ESTAT_MASK
Error Status Mask.
XCANFD_SR_ESTAT_SHIFT
Error Status Shift.
XCANFD_SR_ERRWRN_MASK
Error Warning Mask.
XCANFD_SR_BBSY_MASK
Bus Busy Mask.
XCANFD_SR_BIDLE_MASK
Bus Idle Mask.
XCANFD_SR_NORMAL_MASK
Normal Mode Mask.
Referenced by XCanFd_GetMode.
XCANFD_SR_SLEEP_MASK
Sleep Mode Mask.
Referenced by XCanFd_GetMode.
XCANFD_SR_LBACK_MASK
Loop Back Mode Mask.
XCANFD_SR_CONFIG_MASK
Configuration Mode Mask.
Referenced by XCanFd_GetMode.
XCANFD_SR_PEE_CONFIG_MASK
Protocol Exception Mode Indicator Mask.
Referenced by XCanFd_GetMode.
XCANFD_SR_BSFR_CONFIG_MASK
Bus-Off recovery Mode Indicator Mask.
XCANFD_SR_NISO_MASK
Non-ISO Core Mask.
XCANFD_IXR_RXBOFLW_BI_MASK
Rx Buffer index for Overflow (Mailbox Mode)
Referenced by XCanFd_IntrHandler.
XCANFD_IXR_RXLRM_BI_MASK
Rx Buffer index for Last Received Message (Mailbox Mode)
Referenced by XCanFd_Recv_Mailbox.
XCANFD_RXLRM_BI_SHIFT
Rx Buffer Index Shift Value.
Referenced by XCanFd_Recv_Mailbox.
XCANFD_CSB_SHIFT
Core Status Bit Shift Value.
Referenced by XCanFd_Recv_Mailbox.
XCANFD_IXR_RXMNF_MASK
Rx Match Not Finished Intr Mask.
Referenced by main, XCanFd_IntrHandler.
XCANFD_IXR_RXBOFLW_MASK
Rx Buffer Overflow interrupt Mask (Mailbox mode)
Referenced by main, XCanFd_IntrHandler.
XCANFD_IXR_RXRBF_MASK
Rx Buffer Full Interrupt Mask (Mailbox mode)
Referenced by main, XCanFd_IntrHandler.
XCANFD_IXR_TXCRS_MASK
Tx Cancellation Request Served Interrupt Mask.
Referenced by main, XCanFd_IntrHandler.
XCANFD_IXR_TXRRS_MASK
Tx Buffer Ready Request Served Interrupt Mask.
Referenced by main, XCanFd_IntrHandler.
XCANFD_IXR_RXFWMFLL_MASK
Rx Watermark Full interrupt Mask (FIFO mode)
Referenced by XCanFd_IntrHandler.
XCANFD_IXR_WKUP_MASK
Wake up Interrupt Mask.
Referenced by main, XCanFd_IntrHandler.
XCANFD_IXR_SLP_MASK
Sleep Interrupt Mask.
Referenced by main, XCanFd_IntrHandler.
XCANFD_IXR_BSOFF_MASK
Bus Off Interrupt Mask.
Referenced by main, XCanFd_IntrHandler.
XCANFD_IXR_ERROR_MASK
Error Interrupt Mask.
Referenced by XCanFd_IntrHandler.
XCANFD_IXR_RXFOFLW_MASK
RX FIFO Overflow Intr Mask.
Referenced by main, XCanFd_IntrHandler.
XCANFD_IXR_RXOK_MASK
New Message Received Intr.
Referenced by XCanFd_IntrHandler.
XCANFD_IXR_TXOK_MASK
TX Successful Interrupt Mask.
Referenced by XCanFd_IntrHandler.
XCANFD_IXR_ARBLST_MASK
Arbitration Lost Intr Mask.
Referenced by main, XCanFd_IntrHandler.
XCANFD_IXR_PEE_MASK
Protocol Exception Intr Mask.
Referenced by main, XCanFd_IntrHandler.
XCANFD_IXR_BSRD_MASK
Bus-Off recovery done Intr Mask.
Referenced by XCanFd_IntrHandler.
XCANFD_IXR_TSCNT_OFLW_MASK
Timestamp overflow Mask.
Referenced by main, XCanFd_IntrHandler.
XCANFD_IXR_RXFOFLW_1_MASK
RX FIFO 1 Overflow Intr Mask.
XCANFD_IXR_RXFWMFLL_1_MASK
Rx Watermark Full interrupt Mask for FIFO 1.
Referenced by XCanFd_IntrHandler.
XCANFD_IXR_TXEOFLW_MASK
TX Event FIFO Intr Mask.
Referenced by XCanFd_IntrHandler.
XCANFD_IXR_TXEWMFLL_MASK
TX Event FIFO Watermark Full Intr Mask.
Referenced by XCanFd_IntrHandler.
XCANFD_IXR_ALL
Mask for Basic interrupts.
Referenced by main, XCanFd_InterruptEnable.
XCANFD_TRR_MASK
Transmit Ready request All Mask.
XCANFD_IDR_ID1_MASK
Standard Messg Ident Mask.
XCANFD_IDR_ID1_SHIFT
Standard Messg Ident Shift.
XCANFD_IDR_SRR_MASK
Substitute Remote TX Req.
XCANFD_IDR_SRR_SHIFT
Substitute Remote TX Shift.
XCANFD_IDR_IDE_MASK
Identifier Extension Mask.
XCANFD_IDR_IDE_SHIFT
Identifier Extension Shift.
XCANFD_IDR_ID2_MASK
Extended Message Ident Mask.
XCANFD_IDR_ID2_SHIFT
Extended Message Ident Shift.
XCANFD_IDR_RTR_MASK
Remote TX Request Mask.
XCANFD_DLCR_DLC_MASK
Data Length Code Mask.
Referenced by main, XCanFd_Addto_Queue, XCanFd_Recv_Mailbox, XCanFd_SelfTest, XCanFd_Send.
XCANFD_DLCR_DLC_SHIFT
Data Length Code Shift.
Referenced by XCanFd_GetDlc2len.
XCANFD_DLCR_MM_MASK
Message Marker Mask.
XCANFD_DLCR_MM_SHIFT
Message Marker Shift.
XCANFD_DLCR_EFC_MASK
Event FIFO Control Mask.
XCANFD_DLCR_EFC_SHIFT
Event FIFO Control Shift.
XCANFD_DLC1
Data Length Code 1.
Referenced by XCanFd_GetDlc2len.
XCANFD_DLC2
Data Length Code 2.
Referenced by XCanFd_GetDlc2len.
XCANFD_DLC3
Data Length Code 3.
Referenced by XCanFd_GetDlc2len.
XCANFD_DLC4
Data Length Code 4.
Referenced by XCanFd_GetDlc2len.
XCANFD_DLC5
Data Length Code 5.
Referenced by XCanFd_GetDlc2len.
XCANFD_DLC6
Data Length Code 6.
Referenced by XCanFd_GetDlc2len.
XCANFD_DLC7
Data Length Code 7.
Referenced by XCanFd_GetDlc2len.
XCANFD_DLC8
Data Length Code 8.
Referenced by XCanFd_GetDlc2len.
XCANFD_DLC9
Data Length Code 9.
Referenced by XCanFd_GetDlc2len.
XCANFD_DLC10
Data Length Code 10.
Referenced by XCanFd_GetDlc2len.
XCANFD_DLC11
Data Length Code 11.
Referenced by XCanFd_GetDlc2len.
XCANFD_DLC12
Data Length Code 12.
Referenced by XCanFd_GetDlc2len.
XCANFD_DLC13
Data Length Code 13.
Referenced by XCanFd_GetDlc2len.
XCANFD_DLC14
Data Length Code 14.
Referenced by XCanFd_GetDlc2len.
XCANFD_DLC15
Data Length Code 15.
Referenced by XCanFd_GetDlc2len.
XCANFD_AFR_UAF_ALL_MASK
Acceptance Filter Register.
Referenced by main, XCanFd_SelfTest, XCanFdPolledExample.
XCANFD_FSR_FL_MASK
Fill Level Mask FIFO 0.
Referenced by XCanFd_GetNofMessages_Stored_Rx_Fifo, XCanFd_Recv_Sequential.
XCANFD_FSR_RI_MASK
Read Index Mask FIFO 0.
Referenced by XCanFd_Recv_Sequential.
XCANFD_FSR_FL_1_MASK
Fill Level Mask FIFO 1.
Referenced by XCanFd_GetNofMessages_Stored_Rx_Fifo, XCanFd_Recv_Sequential.
XCANFD_FSR_RI_1_MASK
Read Index Mask FIFO 1.
Referenced by XCanFd_Recv_Sequential.
XCANFD_FSR_IRI_1_MASK
Increment Read Index Mask FIFO1.
XCANFD_FSR_FL_0_SHIFT
Fill Level Mask FIFO 0.
Referenced by XCanFd_GetNofMessages_Stored_Rx_Fifo.
XCANFD_FSR_FL_1_SHIFT
Fill Level Mask FIFO 1.
Referenced by XCanFd_GetNofMessages_Stored_Rx_Fifo.
XCANFD_FSR_RI_1_SHIFT
Read Index Mask FIFO 1.
Referenced by XCanFd_Recv_Sequential.
XCANFD_FSR_IRI_MASK
Increment Read Index Mask.
XCANFD_WMR_RXFWM_1_MASK
RX FIFO 1 Full Watermark Mask.
Referenced by XCanFd_SetRxIntrWatermarkFifo1.
XCANFD_WMR_RXFWM_1_MASK
RX FIFO 1 Full Watermark Mask.
XCANFD_WMR_RXFWM_MASK
RX FIFO 0 Full Watermark Mask.
XCANFD_TXE_FWM_OFFSET
TX Event FIFO watermark Offset.
XCANFD_TXE_FWM_MASK
TX Event FIFO watermark Mask.
XCANFD_TXE_FSR_OFFSET
TX Event FIFO Status Register Offset.
Referenced by XCanFd_GetNofMessages_Stored_TXE_FIFO, XCanFd_Recv_TXEvents_Sequential.
XCANFD_TXE_RI_MASK
TX Event FIFO Read Index Mask.
Referenced by XCanFd_Recv_TXEvents_Sequential.
XCANFD_TXE_IRI_MASK
TX Event FIFO Increment Read Index Mask.
Referenced by XCanFd_Recv_TXEvents_Sequential.
XCANFD_TXE_FL_MASK
TX Event FIFO Fill Level Mask.
Referenced by XCanFd_GetNofMessages_Stored_TXE_FIFO, XCanFd_Recv_TXEvents_Sequential.
XCANFD_TXE_FL_SHIFT
TX Event FIFO Fill Level Shift.
Referenced by XCanFd_GetNofMessages_Stored_TXE_FIFO.
XCANFD_TXE_IRI_SHIFT
TX Event FIFO Increment Read Index SHIFT.
XCANFD_TXBUFFER0_RDY_RQT_MASK
TxBuffer0 Ready Request Mask.
XCANFD_TXBUFFER1_RDY_RQT_MASK
TxBuffer1 Ready Request Mask.
XCANFD_TXBUFFER2_RDY_RQT_MASK
TxBuffer2 Ready Request Mask.
XCANFD_TXBUFFER3_RDY_RQT_MASK
TxBuffer3 Ready Request Mask.
XCANFD_TXBUFFER4_RDY_RQT_MASK
TxBuffer4 Ready Request Mask.
XCANFD_TXBUFFER5_RDY_RQT_MASK
TxBuffer5 Ready Request Mask.
XCANFD_TXBUFFER6_RDY_RQT_MASK
TxBuffer6 Ready Request Mask.
XCANFD_TXBUFFER7_RDY_RQT_MASK
TxBuffer7 Ready Request Mask.
XCANFD_TXBUFFER8_RDY_RQT_MASK
TxBuffer8 Ready Request Mask.
XCANFD_TXBUFFER9_RDY_RQT_MASK
TxBuffer9 Ready Request Mask.
XCANFD_TXBUFFER10_RDY_RQT_MASK
TxBuffer10 Ready Request Mask.
XCANFD_TXBUFFER11_RDY_RQT_MASK
TxBuffer11 Ready Request Mask.
XCANFD_TXBUFFER12_RDY_RQT_MASK
TxBuffer12 Ready Request Mask.
XCANFD_TXBUFFER13_RDY_RQT_MASK
TxBuffer13 Ready Request Mask.
XCANFD_TXBUFFER14_RDY_RQT_MASK
TxBuffer14 Ready Request Mask.
XCANFD_TXBUFFER15_RDY_RQT_MASK
TxBuffer15 Ready Request Mask.
XCANFD_TXBUFFER16_RDY_RQT_MASK
TxBuffer16 Ready Request Mask.
XCANFD_TXBUFFER17_RDY_RQT_MASK
TxBuffer17 Ready Request Mask.
XCANFD_TXBUFFER18_RDY_RQT_MASK
TxBuffer18 Ready Request Mask.
XCANFD_TXBUFFER19_RDY_RQT_MASK
TxBuffer19 Ready Request Mask.
XCANFD_TXBUFFER20_RDY_RQT_MASK
TxBuffer20 Ready Request Mask.
XCANFD_TXBUFFER21_RDY_RQT_MASK
TxBuffer21 Ready Request Mask.
XCANFD_TXBUFFER22_RDY_RQT_MASK
TxBuffer22 Ready Request Mask.
XCANFD_TXBUFFER23_RDY_RQT_MASK
TxBuffer23 Ready Request Mask.
XCANFD_TXBUFFER24_RDY_RQT_MASK
TxBuffer24 Ready Request Mask.
XCANFD_TXBUFFER25_RDY_RQT_MASK
TxBuffer25 Ready Request Mask.
XCANFD_TXBUFFER26_RDY_RQT_MASK
TxBuffer26 Ready Request Mask.
XCANFD_TXBUFFER27_RDY_RQT_MASK
TxBuffer27 Ready Request Mask.
XCANFD_TXBUFFER28_RDY_RQT_MASK
TxBuffer28 Ready Request Mask.
XCANFD_TXBUFFER29_RDY_RQT_MASK
TxBuffer29 Ready Request Mask.
XCANFD_TXBUFFER30_RDY_RQT_MASK
TxBuffer30 Ready Request Mask.
XCANFD_TXBUFFER31_RDY_RQT_MASK
TxBuffer31 Ready Request Mask.
XCANFD_TXBUFFER_ALL_RDY_RQT_MASK
TxBuffer Ready Request Mask for ALL
XCANFD_TXBUFFER0_CANCEL_RQT_MASK
TxBuffer0 Cancel Request Mask.
XCANFD_TXBUFFER1_CANCEL_RQT_MASK
TxBuffer1 Cancel Request Mask.
XCANFD_TXBUFFER2_CANCEL_RQT_MASK
TxBuffer2 Cancel Request Mask.
XCANFD_TXBUFFER3_CANCEL_RQT_MASK
TxBuffer3 Cancel Request Mask.
XCANFD_TXBUFFER4_CANCEL_RQT_MASK
TxBuffer4 Cancel Request Mask.
XCANFD_TXBUFFER5_CANCEL_RQT_MASK
TxBuffer5 Cancel Request Mask.
XCANFD_TXBUFFER6_CANCEL_RQT_MASK
TxBuffer6 Cancel Request Mask.
XCANFD_TXBUFFER7_CANCEL_RQT_MASK
TxBuffer7 Cancel Request Mask.
XCANFD_TXBUFFER8_CANCEL_RQT_MASK
TxBuffer8 Cancel Request Mask.
XCANFD_TXBUFFER9_CANCEL_RQT_MASK
TxBuffer9 Cancel Request Mask.
XCANFD_TXBUFFER10_CANCEL_RQT_MASK
TxBuffer10 Cancel Request Mask.
XCANFD_TXBUFFER11_CANCEL_RQT_MASK
TxBuffer11 Cancel Request Mask.
XCANFD_TXBUFFER12_CANCEL_RQT_MASK
TxBuffer12 Cancel Request Mask.
XCANFD_TXBUFFER13_CANCEL_RQT_MASK
TxBuffer13 Cancel Request Mask.
XCANFD_TXBUFFER14_CANCEL_RQT_MASK
TxBuffer14 Cancel Request Mask.
XCANFD_TXBUFFER15_CANCEL_RQT_MASK
TxBuffer15 Cancel Request Mask.
XCANFD_TXBUFFER16_CANCEL_RQT_MASK
TxBuffer16 Cancel Request Mask.
XCANFD_TXBUFFER17_CANCEL_RQT_MASK
TxBuffer17 Cancel Request Mask.
XCANFD_TXBUFFER18_CANCEL_RQT_MASK
TxBuffer18 Cancel Request Mask.
XCANFD_TXBUFFER19_CANCEL_RQT_MASK
TxBuffer19 Cancel Request Mask.
XCANFD_TXBUFFER20_CANCEL_RQT_MASK
TxBuffer20 Cancel Request Mask.
XCANFD_TXBUFFER21_CANCEL_RQT_MASK
TxBuffer21 Cancel Request Mask.
XCANFD_TXBUFFER22_CANCEL_RQT_MASK
TxBuffer22 Cancel Request Mask.
XCANFD_TXBUFFER23_CANCEL_RQT_MASK
TxBuffer23 Cancel Request Mask.
XCANFD_TXBUFFER24_CANCEL_RQT_MASK
TxBuffer24 Cancel Request Mask.
XCANFD_TXBUFFER25_CANCEL_RQT_MASK
TxBuffer25 Cancel Request Mask.
XCANFD_TXBUFFER26_CANCEL_RQT_MASK
TxBuffer26 Cancel Request Mask.
XCANFD_TXBUFFER27_CANCEL_RQT_MASK
TxBuffer27 Cancel Request Mask.
XCANFD_TXBUFFER28_CANCEL_RQT_MASK
TxBuffer28 Cancel Request Mask.
XCANFD_TXBUFFER29_CANCEL_RQT_MASK
TxBuffer29 Cancel Request Mask.
XCANFD_TXBUFFER30_CANCEL_RQT_MASK
TxBuffer30 Cancel Request Mask.
XCANFD_TXBUFFER31_CANCEL_RQT_MASK
TxBuffer31 Cancel Request Mask.
XCANFD_TXBUFFER_CANCEL_RQT_ALL_MASK
TxBuffer Cancel Request Mask for ALL.
XCANFD_RXBUFFER0_FULL_MASK
RxBuffer0 Full Mask.
XCANFD_RXBUFFER1_FULL_MASK
RxBuffer1 Full Mask.
XCANFD_RXBUFFER2_FULL_MASK
RxBuffer2 Full Mask.
XCANFD_RXBUFFER3_FULL_MASK
RxBuffer3 Full Mask.
XCANFD_RXBUFFER4_FULL_MASK
RxBuffer4 Full Mask.
XCANFD_RXBUFFER5_FULL_MASK
RxBuffer5 Full Mask.
XCANFD_RXBUFFER6_FULL_MASK
RxBuffer6 Full Mask.
XCANFD_RXBUFFER7_FULL_MASK
RxBuffer7 Full Mask.
XCANFD_RXBUFFER8_FULL_MASK
RxBuffer8 Full Mask.
XCANFD_RXBUFFER9_FULL_MASK
RxBuffer9 Full Mask.
XCANFD_RXBUFFER10_FULL_MASK
RxBuffer10 Full Mask.
XCANFD_RXBUFFER11_FULL_MASK
RxBuffer11 Full Mask.
XCANFD_RXBUFFER12_FULL_MASK
RxBuffer12 Full Mask.
XCANFD_RXBUFFER13_FULL_MASK
RxBuffer13 Full Mask.
XCANFD_RXBUFFER14_FULL_MASK
RxBuffer14 Full Mask.
XCANFD_RXBUFFER15_FULL_MASK
RxBuffer15 Full Mask.
XCANFD_RXBUFFER16_FULL_MASK
RxBuffer16 Full Mask.
XCANFD_RXBUFFER17_FULL_MASK
RxBuffer17 Full Mask.
XCANFD_RXBUFFER18_FULL_MASK
RxBuffer18 Full Mask.
XCANFD_RXBUFFER19_FULL_MASK
RxBuffer19 Full Mask.
XCANFD_RXBUFFER20_FULL_MASK
RxBuffer20 Full Mask.
XCANFD_RXBUFFER21_FULL_MASK
RxBuffer21 Full Mask.
XCANFD_RXBUFFER22_FULL_MASK
RxBuffer22 Full Mask.
XCANFD_RXBUFFER23_FULL_MASK
RxBuffer23 Full Mask.
XCANFD_RXBUFFER24_FULL_MASK
RxBuffer24 Full Mask.
XCANFD_RXBUFFER25_FULL_MASK
RxBuffer25 Full Mask.
XCANFD_RXBUFFER26_FULL_MASK
RxBuffer26 Full Mask.
XCANFD_RXBUFFER27_FULL_MASK
RxBuffer27 Full Mask.
XCANFD_RXBUFFER28_FULL_MASK
RxBuffer28 Full Mask.
XCANFD_RXBUFFER29_FULL_MASK
RxBuffer29 Full Mask.
XCANFD_RXBUFFER30_FULL_MASK
RxBuffer30 Full Mask.
XCANFD_RXBUFFER31_FULL_MASK
RxBuffer31 Full Mask.
XCANFD_RXBUFFER32_FULL_MASK
RxBuffer32 Full Mask.
XCANFD_RXBUFFER33_FULL_MASK
RxBuffer33 Full Mask.
XCANFD_RXBUFFER34_FULL_MASK
RxBuffer34 Full Mask.
XCANFD_RXBUFFER35_FULL_MASK
RxBuffer35 Full Mask.
XCANFD_RXBUFFER36_FULL_MASK
RxBuffer36 Full Mask.
XCANFD_RXBUFFER37_FULL_MASK
RxBuffer37 Full Mask.
XCANFD_RXBUFFER38_FULL_MASK
RxBuffer38 Full Mask.
XCANFD_RXBUFFER39_FULL_MASK
RxBuffer39 Full Mask.
XCANFD_RXBUFFER40_FULL_MASK
RxBuffer40 Full Mask.
XCANFD_RXBUFFER41_FULL_MASK
RxBuffer41 Full Mask.
XCANFD_RXBUFFER42_FULL_MASK
RxBuffer42 Full Mask.
XCANFD_RXBUFFER43_FULL_MASK
RxBuffer43 Full Mask.
XCANFD_RXBUFFER44_FULL_MASK
RxBuffer44 Full Mask.
XCANFD_RXBUFFER45_FULL_MASK
RxBuffer45 Full Mask.
XCANFD_RXBUFFER46_FULL_MASK
RxBuffer46 Full Mask.
XCANFD_RXBUFFER47_FULL_MASK
RxBuffer47 Full Mask.
XCANFD_MAX_FRAME_SIZE
Maximum CAN frame length in bytes.
XCANFD_TXE_MESSAGE_SIZE
TX Message Size.
XCANFD_DW_BYTES
Data Word Bytes.
Referenced by XCanFd_Addto_Queue, XCanFd_Recv_Mailbox, XCanFd_Send.
XST_NOBUFFER
All Buffers (32) are filled.
XST_BUFFER_ALREADY_FILLED
Given Buffer is Already filled.
XST_INVALID_DLC
Invalid Dlc code.
Referenced by XCanFd_GetLen2Dlc.
TRR_POS_MASK
TRR Position Mask.
Referenced by XCanFd_PollQueue_Buffer.
MAX_BUFFER_VAL
Max Buffer Value.
Referenced by XCanFd_PollQueue_Buffer.
FAST_MATH_MASK1
Fast Math Mask 1.
FAST_MATH_MASK2
Fast Math Mask 2.
FAST_MATH_MASK3
Fast Math Mask 3.
TRR_INIT_VAL
TRR Initial value.
Referenced by XCanFd_Send_Queue.
TRR_MASK_INIT_VAL
TRR Mask Initial value.
Referenced by XCanFd_Addto_Queue, XCanFd_Send, XCanFd_Send_Queue.
DESIGN_RANGE_1
Design Range 1.
Referenced by XCanFd_RxBuff_MailBox_Active, XCanFd_RxBuff_MailBox_DeActive, XCanFd_Set_MailBox_IdMask.
DESIGN_RANGE_2
Design Range 2.
Referenced by XCanFd_RxBuff_MailBox_Active, XCanFd_RxBuff_MailBox_DeActive, XCanFd_Set_MailBox_IdMask.
CONTROL_STATUS_1
Control Status 1.
Referenced by XCanFd_RxBuff_MailBox_Active, XCanFd_RxBuff_MailBox_DeActive, XCanFd_Set_MailBox_IdMask.
CONTROL_STATUS_2
Control Status 2.
Referenced by XCanFd_RxBuff_MailBox_Active, XCanFd_RxBuff_MailBox_DeActive, XCanFd_Set_MailBox_IdMask.
CONTROL_STATUS_3
Congrol Status 3.
Referenced by XCanFd_RxBuff_MailBox_Active, XCanFd_RxBuff_MailBox_DeActive, XCanFd_Set_MailBox_IdMask.
EXTRACTION_MASK
Extraction Mask.
SHIFT1
Flag for Shift 1.
SHIFT2
Flag for Shift 2.
SHIFT3
Flag for Shift 3.
TDC_MAX_OFFSET
TDC Max Offset.
Referenced by XCanFd_Set_Tranceiver_Delay_Compensation.
TDC_SHIFT
Shift Value for TDC.
Referenced by XCanFd_Set_Tranceiver_Delay_Compensation.
MAX_BUFFER_INDEX
Max Buffer Index.
Referenced by XCanFd_GetFreeBuffer, XCanFd_TxBuffer_Cancel_Request.
MIN_FILTER_INDEX
Minimum Filter Index.
Referenced by XCanFd_AcceptFilterGet, XCanFd_AcceptFilterSet.
MAX_FILTER_INDEX
Maximum Filter Index.
Referenced by XCanFd_AcceptFilterGet, XCanFd_AcceptFilterSet, XCanFd_CfgInitialize.
EDL_CANFD
Extended Data Length for CANFD.
Referenced by main, XCanFd_SelfTest.
EDL_CAN
Extended Data Length for CAN.
typedef void(* XCanFd_SendRecvHandler)(void *CallBackRef))(void *CallBackRef)
Callback type for frame sending and reception interrupts.
CallBackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked.
typedef void(* XCanFd_ErrorHandler)(void *CallBackRef, u32 ErrorMask))(void *CallBackRef, u32 ErrorMask)
Callback type for error interrupt.
CallBackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. ErrorMask is a bit mask indicating the cause of the error. Its value equals 'OR'ing one or more XCANFD_ESR_* values defined in xcan_l.h
typedef void(* XCanFd_EventHandler)(void *CallBackRef, u32 Mask))(void *CallBackRef, u32 Mask)
Callback type for all kinds of interrupts except sending frame interrupt, receiving frame interrupt, and error interrupt.
CallBackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. Mask is a bit mask indicating the pending interrupts. Its value equals 'OR'ing one or more XCANFD_IXR_* defined in xcanfd_hw.h
XCanFd_Config XCanFd_ConfigTable[][]
Config table.
Referenced by XCanFd_LookupConfig.
u32 TxFrame[XCANFD_MAX_FRAME_SIZE_IN_BYTES][XCANFD_MAX_FRAME_SIZE_IN_BYTES]
TxFrame Buffer.
u32 RxFrame[XCANFD_MAX_FRAME_SIZE_IN_BYTES][XCANFD_MAX_FRAME_SIZE_IN_BYTES]
RxFrame Buffer.
static void StubHandler(void)
This function looks for the device configuration based on the device index.
The table XCanFd_ConfigTable[] contains the configuration information for each device in the system. InstanceIndex is a 0-based integer indexing all CAN devices in the system. A pointer to the configuration table entry corresponding to the given device ID, or NULL if no match is found. None. This routine is a stub for the asynchronous callbacks. The stub is here in case the upper layer forgot to set the handler(s). On initialization, all handlers are set to this callback. It is considered an error for this handler to be invoked.None. None.
static int XCanfd_TrrVal_Get_SetBit_Position(u32 u)
This function calculates the index position of the right most set bit.
u is GlobalTrrValue Index location of right most set bit log2 fast Math logic.
static u32 XCanFd_SeqRecv_logic(XCanFd *InstancePtr, u32 ReadIndex, u32 FsrVal, u32 *FramePtr, u8 fifo_no)
This function receives a CAN/CAN FD Frame as per the input Can Read Index value.
InstancePtr is a pointer to the XCanFd instance to be worked on. ReadIndex is Current RI(Read Index) maintained by Can Core. FsrVal is Fifo Status Registor value. FramePtr is a pointer to a 32-bit aligned buffer where the CAN/CAN FD frame is to be written. fifo_no is target fifo number - XST_SUCCESS after all operations This routine has generic logic for sequential receive mode
int XCanFd_CfgInitialize(XCanFd *InstancePtr, XCanFd_Config *ConfigPtr, UINTPTR EffectiveAddr)
This routine initializes a specific XCanFd instance/driver.
This function should only be used when no Virtual Memory support is needed.This initialization entails: Search for device configuration given the device ID.Initialize Base Address field of the XCanFd structure using the deviceaddress in the found device configuration.Populate all other data fields in the XCanFd structureReset the device. InstancePtr is a pointer to the XCanFd instance to be worked on. ConfigPtr is the pointer to XCanFd_Config instance EffectiveAddr is the base address of CANFD - XST_SUCCESS if initialization was successful XST_DEVICE_NOT_FOUND if device configuration information was not found for a device with the supplied device ID. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::ErrorHandler, XCanFd::EventHandler, XCanFd::IsReady, MAX_FILTER_INDEX, XCanFd_Config::Name, XCanFd_Config::NumofRxMbBuf, XCanFd_Config::NumofTxBuf, XCanFd::RecvHandler, XCanFd_Config::Rx_Mode, XCanFd::SendHandler, XCanFd_AcceptFilterSet, XCanFd_Reset.
Referenced by main, XCanFdPolledExample.
int XCanFd_stop(XCanFd *InstancePtr)
This routine releases resources of XCanFd instance/driver.
None - XST_SUCCESS if node release was successful XST_FAILURE or an error code or a reason code if node release was fail None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig.
Referenced by XCanFdPolledExample.
u32 XCanFd_AcceptFilterGetEnabled(XCanFd *InstancePtr)
This function returns enabled acceptance filters.
Use XCANFD_AFR_UAF*_MASK defined in xcanfd_hw.h to interpret the returned value. If no acceptance filters are enabled then all received frames are stored in the RX FIFO. InstancePtr is a pointer to the XCanFd instance to be worked on. The value stored in Acceptance Filter Register. Acceptance Filter Register is an optional register in Xilinx CAN device If it is NOT existing in the device, this function should NOT be used.Calling this function in this case will cause an assertion failure.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_AFR_OFFSET, XCanFd_ReadReg.
Referenced by XCanFd_AcceptFilterSet.
u8 XCanFd_GetMode(XCanFd *InstancePtr)
This routine returns current operation mode the CAN device is in.
InstancePtr is a pointer to the XCanFd instance to be worked on. - XCANFD_MODE_CONFIG if the device is in Configuration Mode. XCANFD_MODE_SLEEP if the device is in Sleep Mode. XCANFD_MODE_NORMAL if the device is in Normal Mode.XCANFD_MODE_LOOPBACK if the device is in Loop Back Mode.XCANFD_MODE_SNOOP if the device is in Snoop Mode.XCANFD_MODE_BR if the device is in Bus-Off recovery Mode.XCANFD_MODE_PEE if the device is in Protocol Exception Event mode. None.
References XCanFd::IsReady, XCanFd_GetStatus, XCANFD_MODE_CONFIG, XCANFD_MODE_LOOPBACK, XCANFD_MODE_NORMAL, XCANFD_MODE_PEE, XCANFD_MODE_SLEEP, XCANFD_MODE_SNOOP, XCANFD_SR_CONFIG_MASK, XCANFD_SR_NORMAL_MASK, XCANFD_SR_PEE_CONFIG_MASK, XCANFD_SR_SLEEP_MASK, XCANFD_SR_SNOOP_MASK.
Referenced by main, XCanFd_EnterMode, XCanFd_SelfTest, XCanFd_SetBaudRatePrescaler, XCanFd_SetBitTiming, XCanFd_SetFBaudRatePrescaler, XCanFd_SetFBitTiming, XCanFd_SetRxFilterPartition, XCanFd_SetRxIntrWatermark, XCanFd_SetRxIntrWatermarkFifo1, XCanFd_SetTxEventIntrWatermark, XCanFdPolledExample.
void XCanFd_EnterMode(XCanFd *InstancePtr, u8 OperationMode)
This function allows the CAN device to enter one of the following operation modes:
Configuration Mode: Pass in parameter XCANFD_MODE_CONFIGSleep Mode: Pass in parameter XCANFD_MODE_SLEEPNormal Mode: Pass in parameter XCANFD_MODE_NORMALLoop Back Mode: Pass in parameter XCANFD_MODE_LOOPBACKSnoop Mode: Pass in Parameter XCANFD_MODE_SNOOPAuto Bus-Off Recovery Mode: Pass in Parameter XCANFD_MODE_ABRStart Bus-Off Recovery Mode: Pass in Parameter XCANFD_MODE_SBRProtocol Exception Event Mode: Pass in Parameter XCANFD_MODE_PEEDisable AutoRetransmission Mode: Pass in Parameter XCANFD_MODE_DAR Read xcanfd.h and device specification for detailed description of each operation mode. InstancePtr is a pointer to the XCanFd instance to be worked on. OperationMode specify which operation mode to enter.Valid value is any of XCANFD_MODE_* defined in xcanfd.h. Please note no multiple modes could be entered at the same time. None. This function does NOT ensure CAN device enters the specified operation mode before returns the control to the caller. The caller is responsible for checking current operation mode using XCanFd_GetMode().
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCanFd_GetMode, XCANFD_MODE_ABR, XCANFD_MODE_CONFIG, XCANFD_MODE_DAR, XCANFD_MODE_LOOPBACK, XCANFD_MODE_NORMAL, XCANFD_MODE_PEE, XCANFD_MODE_SBR, XCANFD_MODE_SLEEP, XCANFD_MODE_SNOOP, XCANFD_MSR_ABR_MASK, XCANFD_MSR_CONFIG_MASK, XCANFD_MSR_DAR_MASK, XCANFD_MSR_DPEE_MASK, XCANFD_MSR_LBACK_MASK, XCANFD_MSR_OFFSET, XCANFD_MSR_SBR_MASK, XCANFD_MSR_SLEEP_MASK, XCANFD_MSR_SNOOP_MASK, XCanFd_ReadReg, XCANFD_SRR_CEN_MASK, XCANFD_SRR_OFFSET, XCanFd_WriteReg.
Referenced by main, XCanFd_SelfTest, XCanFdPolledExample.
void XCanFd_GetBusErrorCounter(XCanFd *InstancePtr, u8 *RxErrorCount, u8 *TxErrorCount)
This function reads Receive and Transmit error counters.
InstancePtr is a pointer to the XCanFd instance to be worked on. RxErrorCount will contain Receive Error Counter value after this function returns. TxErrorCount will contain Transmit Error Counter value after this function returns. None. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_ECR_OFFSET, XCANFD_ECR_REC_MASK, XCANFD_ECR_REC_SHIFT, XCANFD_ECR_TEC_MASK, XCanFd_ReadReg.
int XCanFd_Send(XCanFd *InstancePtr, u32 *FramePtr, u32 *TxBufferNumber)
This function sends a CAN/CANFD Frame.
This function first checks whether free buffer is there or not.if free buffer is there the user data will be written into the free buffer.otherwise it returns error code immediately. This function does not wait for the given frame being sent to CAN bus. InstancePtr is a pointer to the XCanFd instance to be worked on. FramePtr is a pointer to a 32-bit aligned buffer containing the CAN frame to be sent. TxBufferNumber is the buffer where the user data has been written and it is updated by driver. - XST_SUCCESS if TX FIFO was not full and the given frame was written into the FIFO; XST_FIFO_NO_ROOM if there is no room in the TX FIFO for the given frame None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::GlobalTrrMask, XCanFd::IsReady, TRR_MASK_INIT_VAL, XCanFD_Check_TrrVal_Set_Bit, XCANFD_DLCR_DLC_MASK, XCANFD_DLCR_EDL_MASK, XCANFD_DW_BYTES, XCanFd_GetDlc2len, XCanFd_GetFreeBuffer, XCanFd_ReadReg, XCANFD_TRR_OFFSET, XCANFD_TXDLC_OFFSET, XCANFD_TXDW_OFFSET, XCANFD_TXID_OFFSET, XCanFd_WriteReg.
Referenced by main, XCanFd_SelfTest.
int XCanFd_Addto_Queue(XCanFd *InstancePtr, u32 *FramePtr, u32 *TxBufferNumber)
This function writes the Data into specific Buffer.we have 32 TxBuffers we can Add data to each Buffer using this routine.This routine won't transmit the data.
it only adds data to Buffers. InstancePtr is a pointer to the XCanFd instance to be worked on. FramePtr is a pointer to a 32-bit aligned buffer containing the CAN frame to be sent. TxBufferNumber is Buffer Number where the data has written and is given back to user. - XST_SUCCESS if TX FIFO was not full and the given frame was written into the FIFO; XST_FIFO_NO_ROOM if there is no room in the TX FIFO for the given frame None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::GlobalTrrMask, XCanFd::GlobalTrrValue, XCanFd::IsReady, XCanFd::MultiBuffTrr, TRR_MASK_INIT_VAL, XCanFD_Check_TrrVal_Set_Bit, XCANFD_DLCR_DLC_MASK, XCANFD_DLCR_EDL_MASK, XCANFD_DW_BYTES, XCanFd_GetDlc2len, XCanFd_GetFreeBuffer, XCanFd_ReadReg, XCANFD_TRR_OFFSET, XCANFD_TXDLC_OFFSET, XCANFD_TXDW_OFFSET, XCANFD_TXID_OFFSET, XCanFd_WriteReg.
u32 XCanFd_Recv_Sequential(XCanFd *InstancePtr, u32 *FramePtr)
This function receives a CAN/CAN FD Frame.
This function first checks FSR Register.The FL bits tells the Number of Packets received. if FL is non Zero then Read the Packet and store it to user Buffer. InstancePtr is a pointer to the XCanFd instance to be worked on. FramePtr is a pointer to a 32-bit aligned buffer where the CAN/CAN FD frame to be written. - XST_SUCCESS if RX FIFO was not empty and a frame was read from RX FIFO successfully and written into the given buffer; XST_NO_DATA if there is no frame to be received from the FIFO The CANFD has two design modes. ->Sequential Mode - Core writes data sequentially to RxBuffers. ->MailBox Mode - Core writes data to RxBuffers when a ID Match happened. This routine distinguishes receive checking as per the frame availability from either Fifo 0 or Fifo 1.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_FSR_FL_1_MASK, XCANFD_FSR_FL_MASK, XCANFD_FSR_OFFSET, XCANFD_FSR_RI_1_MASK, XCANFD_FSR_RI_1_SHIFT, XCANFD_FSR_RI_MASK, XCanFd_ReadReg, XCANFD_RX_FIFO_0, XCANFD_RX_FIFO_1.
Referenced by main, XCanFd_SelfTest.
u32 XCanFd_Recv_TXEvents_Sequential(XCanFd *InstancePtr, u32 *FramePtr)
This function receives a CAN/CAN FD TX Events.
This function first checks FSR Register.The FL bits tells the Number of TX Event packets received. if FL is non Zero then Read the Packet and store it to user Buffer. InstancePtr is a pointer to the XCanFd instance to be worked on. FramePtr is a pointer to a 32-bit aligned buffer where the CAN/CAN FD frame Event to be written. - XST_SUCCESS if TXE FIFO was not empty and a frame was read from TX FIFO successfully and written into the given buffer; XST_NO_DATA if there is no frame to be received from the TXE FIFO This CANFD has two design modes. ->Sequential Mode - Core writes data sequentially to RxBuffers. ->MailBox Mode - Core writes data to RxBuffers when a ID Match happened. This routine is useful for Both the Modes.This API is meant to be used with IP with CanFD 2.0 spec support only.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCanFd_ReadReg, XCANFD_TXE_FL_MASK, XCANFD_TXE_FSR_OFFSET, XCANFD_TXE_IRI_MASK, XCANFD_TXE_RI_MASK, XCANFD_TXEDLC_OFFSET, XCANFD_TXEID_OFFSET, XCanFd_WriteReg.
u32 XCanFd_Recv_Mailbox(XCanFd *InstancePtr, u32 *FramePtr)
This function receives a CAN Frame in MAIL BOX Mode.
Read Rx Last Buffer Index from ISR Register. This tells which buffer is having data.then read and update the data to user buffer. InstancePtr is a pointer to the XCanFd instance to be worked on. FramePtr is a pointer to a 32-bit aligned buffer where the CAN frame to be receive. - XST_SUCCESS if RX FIFO was not empty and a frame was read from RX FIFO successfully and written into the given buffer; XST_NO_DATA if there is no frame to be received from the FIFO This CANFD has two design modes. ->Sequential Mode - Core writes data sequentially to RxBuffers. ->MailBox Mode - Core writes data to RxBuffers when a ID match happened. This routine is useful for MailBox Mode.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_CSB_SHIFT, XCANFD_DLCR_DLC_MASK, XCANFD_DLCR_EDL_MASK, XCANFD_DW_BYTES, XCanFd_GetDlc2len, XCANFD_ISR_OFFSET, XCANFD_IXR_RXLRM_BI_MASK, XCANFD_RCS_HCB_MASK, XCANFD_RCS_OFFSET, XCanFd_ReadReg, XCANFD_RXDLC_OFFSET, XCANFD_RXDW_OFFSET, XCANFD_RXID_OFFSET, XCANFD_RXLRM_BI_SHIFT, XCanFd_WriteReg.
Referenced by main, XCanFd_SelfTest.
u32 XCanFd_RxBuff_MailBox_Active(XCanFd *InstancePtr, u32 RxBuffer)
This function sets an RxBuffer to Active State.In Mailbox Mode configuration we can set each buffer to receive with specific Id and Mask.inorder compare we need to first Activate the Buffer.Maximum number of RxBuffers depends on Design.Range 48,32,16.
InstancePtr is a pointer to the XCanFd instance to be worked on. RxBuffer Receive Buffer Number defines which Buffer to configure Value ranges from 0 - 48 - XST_SUCCESS if the values were set successfully. none
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, CONTROL_STATUS_1, CONTROL_STATUS_2, CONTROL_STATUS_3, DESIGN_RANGE_1, DESIGN_RANGE_2, XCanFd::IsReady, XCANFD_RCS_OFFSET, XCanFd_ReadReg, XCanFd_WriteReg.
Referenced by main, XCanFd_SelfTest, XCanFdPolledExample.
u32 XCanFd_Set_MailBox_IdMask(XCanFd *InstancePtr, u32 RxBuffer, u32 MaskValue, u32 IdValue)
This function sets the Id and Mask for an RxBuffer to participate in Id match.if a packet is received with an id which is equal to id we configured, then it is stored in RxBuffer.
otherwise it won't. InstancePtr is a pointer to the XCanFd instance to be worked on. RxBuffer Receive Buffer Number defines which Buffer to configure Value ranges from 0 - 48(can get from NumofRxMbBuf) MaskValue is the value to write into the RxBuffer Mask Register IdValue is the value to write into the RxBuffer Id register - XST_SUCCESS if the values were set successfully. none
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, CONTROL_STATUS_1, CONTROL_STATUS_2, CONTROL_STATUS_3, DESIGN_RANGE_1, DESIGN_RANGE_2, XCanFd::IsReady, XCANFD_MAILBOX_ID_OFFSET, XCANFD_MAILBOX_MASK_OFFSET, XCANFD_RCS_OFFSET, XCanFd_ReadReg, XCanFd_WriteReg.
Referenced by main, XCanFd_SelfTest, XCanFdPolledExample.
u32 XCanFd_RxBuff_MailBox_DeActive(XCanFd *InstancePtr, u32 RxBuffer)
This function sets an RxBuffer to InActive State.if we change a buffer to InActive state, then Rx Packet won't store into that buffer, even the Id is matched.
InstancePtr is a pointer to the XCanFd instance to be worked on. RxBuffer Receive Buffer Number defines which Buffer to configure Value ranges from 0 - 48 - XST_SUCCESS if the values were set successfully. XST_FAILURE if the given filter was not disabled, or the CAN device was not ready to accept writes to AFMR and AFIR. none
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, CONTROL_STATUS_1, CONTROL_STATUS_2, CONTROL_STATUS_3, DESIGN_RANGE_1, DESIGN_RANGE_2, XCanFd::IsReady, XCANFD_MBRXBUF_MASK, XCANFD_RCS_OFFSET, XCanFd_ReadReg, XCanFd_WriteReg.
Referenced by main, XCanFd_SelfTest, XCanFdPolledExample.
int XCanFd_TxBuffer_Cancel_Request(XCanFd *InstancePtr, u32 BufferNumber)
This function Cancels a CAN/CAN FD Frame which was already initiated for transmission.This function first checks TRR Bit based on BufferNumber.
if TRR Bit is set, then it cancels the Buffers. InstancePtr is a pointer to the XCanFd instance to be worked on. BufferNumber is which Buffer to cancel out of 32 Buffers. - XST_SUCCESS if RX FIFO was not empty and a frame was read from RX FIFO successfully and written into the given buffer; XST_NO_DATA if there is no frame to be received from the FIFO This function first checks whether TRR bit is set or not if Set, it then checks the corresponding TCR bit ->if Set, then wait until cancellation is performed. ->if Not set, then set the corresponding TCR bit and wait until core clears it. if Not set, Nothing to do.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, MAX_BUFFER_INDEX, XCanFd_ReadReg, XCANFD_TCR_OFFSET, XCANFD_TRR_OFFSET, XCanFd_WriteReg.
void XCanFd_AcceptFilterEnable(XCanFd *InstancePtr, u32 FilterIndexMask)
This routine enables the acceptance filters.
Up to 32 filters can be enabled. InstancePtr is a pointer to the XCanFd instance to be worked on. FilterIndexMask specifies which filter(s) to enable. Use any XCANFD_AFR_UAF*_MASK to enable one filter, and "Or" multiple XCANFD_AFR_UAF*_MASK values if multiple filters need to be enabled. Any filter not specified in this parameter will keep its previous enable/disable setting. None. In Sequential Mode, in order to receive data, we need to enable these filters. if we want to make filtration i.e Id match then we need to set the Id value in AFR Id register.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_AFR_OFFSET, XCanFd_ReadReg, XCanFd_WriteReg.
Referenced by main, XCanFd_SelfTest, XCanFdPolledExample.
void XCanFd_AcceptFilterDisable(XCanFd *InstancePtr, u32 FilterIndexMask)
This routine disables the acceptance filters.
32 filters can be disabled. InstancePtr is a pointer to the XCanFd instance to be worked on. FilterIndexMask specifies which filter(s) to disable. Use any XCANFD_AFR_UAF*_MASK to disable one filter, and "Or" multiple XCANFD_AFR_UAF*_MASK values if multiple filters need to be disabled. Any filter not specified in this parameter will keep its previous enable/disable setting. If all acceptance filters are disabled then all received frames are stored in the RX FIFO. None. None
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_AFR_OFFSET, XCanFd_ReadReg, XCanFd_WriteReg.
Referenced by main, XCanFd_SelfTest, XCanFdPolledExample.
int XCanFd_AcceptFilterSet(XCanFd *InstancePtr, u32 FilterIndex, u32 MaskValue, u32 IdValue)
This function sets values to the Acceptance Filter Mask Register (AFMR) and Acceptance Filter ID Register (AFIR) for the specified Acceptance Filter.
Use XCANFD_IDR_* defined in xcanfd_hw.h to create the values to set the filter. Read xcanfd.h and device specification for details.This function should be called only after: The given filter is disabled by calling XCanFd_AcceptFilterDisable();And the CAN device is ready to accept writes to AFMR and AFIR, i.e., XCanFd_IsAcceptFilterBusy() returns FALSE. InstancePtr is a pointer to the XCanFd instance to be worked on. FilterIndex defines which Acceptance Filter Mask and ID Register to set. Use any single XCANFD_AFR_UAF*_MASK value.ranges from 1 32 MaskValue is the value to write to the chosen Acceptance Filter Mask Register. IdValue is the value to write to the chosen Acceptance Filter ID Register. - XST_SUCCESS if the values were set successfully. XST_FAILURE if the given filter was not disabled, or the CAN device was not ready to accept writes to AFMR and AFIR. Acceptance Filter Mask and ID Registers are optional registers in Xilinx XCanFd device.if they are not configured then device will receive data with any ID.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, MAX_FILTER_INDEX, MIN_FILTER_INDEX, XCanFd_AcceptFilterGetEnabled, XCANFD_AFIDR_OFFSET, XCANFD_AFMR_OFFSET, XCanFd_WriteReg.
Referenced by XCanFd_CfgInitialize.
void XCanFd_AcceptFilterGet(XCanFd *InstancePtr, u32 FilterIndex, u32 *MaskValue, u32 *IdValue)
This function reads the values of the Acceptance Filter Mask and ID Register for the specified Acceptance Filter.
Use XCANFD_IDR_* defined in xcanfd_hw.h to interpret the values. Read xcanfd.h and device specification for details. InstancePtr is a pointer to the XCanFd instance to be worked on. FilterIndex defines which Acceptance Filter Mask Register to get Mask and ID from. Use any single XCANFD_FILTER_* value. MaskValue will store the Mask value read from the chosen Acceptance Filter Mask Register after this function returns. IdValue will store the ID value read from the chosen Acceptance Filter ID Register after this function returns. None. Acceptance Filter Mask and ID Registers are optional registers in Xilinx CAN device. If they are NOT existing in the device, this function should NOT be used. Calling this function in this case will cause an assertion failure.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, MAX_FILTER_INDEX, MIN_FILTER_INDEX, XCANFD_AFIDR_OFFSET, XCANFD_AFMR_OFFSET, XCANFD_NOOF_AFR, XCanFd_ReadReg.
int XCanFd_GetDlc2len(u32 Dlc, u32 Edl)
This function returns Data Length Code(in Bytes),we need to pass DLC Field value in DLC Register.
Dlc Field in Data Length Code Register. Edl and Fdf Field in DLC register. Total Number of Bytes stored in each Buffer. Refer CAN FD Spec about DLC.
References XCANFD_DLC1, XCANFD_DLC10, XCANFD_DLC11, XCANFD_DLC12, XCANFD_DLC13, XCANFD_DLC14, XCANFD_DLC15, XCANFD_DLC2, XCANFD_DLC3, XCANFD_DLC4, XCANFD_DLC5, XCANFD_DLC6, XCANFD_DLC7, XCANFD_DLC8, XCANFD_DLC9, XCANFD_DLCR_DLC_SHIFT.
Referenced by main, XCanFd_Addto_Queue, XCanFd_Recv_Mailbox, XCanFd_SelfTest, XCanFd_Send.
u8 XCanFd_GetLen2Dlc(int len)
This function returns Data Length Code of 4bits,we need to pass length in bytes.
len is the length in bytes. Total Number of Bytes stored in each Buffer. Refer CAN FD Spec about DLC.
References XST_INVALID_DLC.
Referenced by main, XCanFd_SelfTest.
u32 XCanFd_GetFreeBuffer(XCanFd *InstancePtr)
This Routine returns the Free Buffers count out of 32 Transmit Buffers.
InstancePtr is a pointer to the XCanFd instance to be worked on. Returns number of Free buffers count. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, MAX_BUFFER_INDEX, XCanFd_ReadReg, XCANFD_TRR_OFFSET.
Referenced by XCanFd_Addto_Queue, XCanFd_Send.
int XCanFd_Send_Queue(XCanFd *InstancePtr)
This routine sends queue of buffers,when added to queue using Addto_Queue() Basically this will trigger the TRR Bit(s).This routine can be used when user want to send multiple packets at a time.
InstancePtr is a pointer to the XCanFd instance to be worked on. - XST_SUCCESS. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::GlobalTrrMask, XCanFd::GlobalTrrValue, XCanFd::IsReady, XCanFd::MultiBuffTrr, TRR_INIT_VAL, TRR_MASK_INIT_VAL, XCANFD_TRR_OFFSET, XCanFd_WriteReg.
void XCanFd_PollQueue_Buffer(XCanFd *InstancePtr)
This function Polls the TxBuffer(s) whether it is transmitted or not.
This function can call when user sends multiple Buffers using Addto_Queue() and XCanFd_Send_Queue(). InstancePtr is a pointer to the XCanFd instance to be worked on. None. None.
References XCanFd::IsReady, MAX_BUFFER_VAL, XCanFd::MultiBuffTrr, TRR_POS_MASK, XCanFd_IsBufferTransmitted.
int XCanFd_GetNofMessages_Stored_Rx_Fifo(XCanFd *InstancePtr, u8 fifo_no)
This function returns Number of messages Stored.
The FSR Register has Field called FL. this gives number of packets received. InstancePtr is a pointer to the XCanFd instance to be worked on. fifo_no is fifo number. Value is the number of messages stored in FSR Register. Selects either Rx Fifo 0 or Rx Fifo 1
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_FSR_FL_0_SHIFT, XCANFD_FSR_FL_1_MASK, XCANFD_FSR_FL_1_SHIFT, XCANFD_FSR_FL_MASK, XCANFD_FSR_OFFSET, XCanFd_ReadReg, XCANFD_RX_FIFO_0.
int XCanFd_GetNofMessages_Stored_TXE_FIFO(XCanFd *InstancePtr)
This function returns Number of messages Stored in TX Event FIFO The FSR Register has Field called FL.
this gives number of packets received. InstancePtr is a pointer to the XCanFd instance to be worked on. Value is the number of messages stored in FSR Register. This API is meant to be used with IP with CanFD 2.0 spec support only.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCanFd_ReadReg, XCANFD_TXE_FL_MASK, XCANFD_TXE_FL_SHIFT, XCANFD_TXE_FSR_OFFSET.
void XCanFd_Enable_Tranceiver_Delay_Compensation(XCanFd *InstancePtr)
This function Enables the Transceiver delay compensation.
InstancePtr is a pointer to the XCanFd instance to be worked on. None. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_F_BRPR_OFFSET, XCANFD_F_BRPR_TDC_ENABLE_MASK, XCanFd_ReadReg, XCanFd_WriteReg.
void XCanFd_Set_Tranceiver_Delay_Compensation(XCanFd *InstancePtr, u32 TdcOffset)
This function Sets the Transceiver delay compensation offset.
InstancePtr is a pointer to the XCanFd instance to be worked on. TdcOffset is the Delay Compensation Offset. None. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, TDC_MAX_OFFSET, TDC_SHIFT, XCANFD_F_BRPR_OFFSET, XCANFD_F_BRPR_TDCMASK, XCanFd_ReadReg, XCanFd_WriteReg.
void XCanFd_Disable_Tranceiver_Delay_Compensation(XCanFd *InstancePtr)
This function Disables the Transceiver delay compensation.
InstancePtr is a pointer to the XCanFd instance to be worked on. None. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_F_BRPR_OFFSET, XCANFD_F_BRPR_TDC_ENABLE_MASK, XCanFd_ReadReg, XCanFd_WriteReg.
void XCanFd_Pee_BusOff_Handler(XCanFd *InstancePtr)
This function recovers the CAN device from Protocol Exception Event & Busoff Event States.
InstancePtr is a pointer to the XCanFd instance to be worked on. None. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd_ReadReg, XCANFD_TCR_OFFSET, XCANFD_TRR_OFFSET, XCanFd_WriteReg.
Referenced by main.
XCanFd_Config * XCanFd_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XCanFd_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xcanfd.h for the definition of XCanFd_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XCanFd_Config::Name, XCanFd_ConfigTable.
Referenced by main, XCanFdPolledExample.
XCanFd_Config* XCanFd_GetConfig(unsigned int InstanceIndex)
int XCanFd_SetBaudRatePrescaler(XCanFd *InstancePtr, u8 Prescaler)
This routine sets Baud Rate Prescaler value in Arbitration Phse.
The system clock for the CAN controller is divided by (Prescaler + 1) to generate the quantum clock needed for sampling and synchronization. Read the device specification for details.Baud Rate Prescaler could be set only after CAN device entered Configuration Mode. So please call XCanFd_EnterMode() to enter Configuration Mode before using this function. InstancePtr is a pointer to the XCanFd instance to be worked on. Prescaler is the value to set. Valid values are from 0 to 255. - XST_SUCCESS if the Baud Rate Prescaler value is set successfully. XST_FAILURE if CAN device is not in Configuration Mode. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_BRPR_OFFSET, XCanFd_GetMode, XCANFD_MODE_CONFIG, XCanFd_WriteReg.
Referenced by main, XCanFd_SelfTest, XCanFdPolledExample.
u8 XCanFd_GetBaudRatePrescaler(XCanFd *InstancePtr)
This routine gets Baud Rate Prescaler value.
The system clock for the CAN controller is divided by (Prescaler + 1) to generate the quantum clock needed for sampling and synchronization. Read the device specification for details. InstancePtr is a pointer to the XCanFd instance to be worked on. Current used Baud Rate Prescaler value. The value's range is from 0 to 255. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_BRPR_OFFSET, XCanFd_ReadReg.
u8 XCanFd_GetFBaudRatePrescaler(XCanFd *InstancePtr)
This routine gets Baud Rate Prescaler value in Data Phase.
The system clock for the CAN controller is divided by (Prescaler + 1) to generate the quantum clock needed for sampling and synchronization. Read the device specification for details. InstancePtr is a pointer to the XCanFd instance to be worked on. Current used Baud Rate Prescaler value. The value's range is from 1 to 256. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_BRPR_BRP_MASK, XCANFD_F_BRPR_OFFSET, XCanFd_ReadReg.
int XCanFd_SetBitTiming(XCanFd *InstancePtr, u8 SyncJumpWidth, u8 TimeSegment2, u16 TimeSegment1)
This routine sets Bit time.
Time segment 1, Time segment 2 and Synchronization Jump Width are set in this function. Device specification requires the values passed into this function be one less than the actual values of these fields. Read the device specification for details.Bit time could be set only after CAN device entered Configuration Mode. Please call XCanFd_EnterMode() to enter Configuration Mode before using this function. InstancePtr is a pointer to the XCanFd instance to be worked on. SyncJumpWidth is the Synchronization Jump Width value to set. Valid values are from 0 to 3. TimeSegment2 is the Time Segment 2 value to set. Valid values are from 0 to 7. TimeSegment1 is the Time Segment 1 value to set. Valid values are from 0 to 15. - XST_SUCCESS if the Bit time is set successfully. XST_FAILURE if CAN device is not in Configuration Mode.XST_INVALID_PARAM if any value of SyncJumpWidth, TimeSegment2 and TimeSegment1 is invalid. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_BTR_OFFSET, XCANFD_BTR_SJW_MASK, XCANFD_BTR_SJW_SHIFT, XCANFD_BTR_TS1_MASK, XCANFD_BTR_TS2_MASK, XCANFD_BTR_TS2_SHIFT, XCanFd_GetMode, XCANFD_MAX_SJW_VALUE, XCANFD_MAX_TS1_VALUE, XCANFD_MAX_TS2_VALUE, XCANFD_MODE_CONFIG, XCanFd_WriteReg.
Referenced by main, XCanFd_SelfTest, XCanFdPolledExample.
void XCanFd_GetBitTiming(XCanFd *InstancePtr, u8 *SyncJumpWidth, u8 *TimeSegment2, u8 *TimeSegment1)
This routine gets Bit time.
Time segment 1, Time segment 2 and Synchronization Jump Width values are read in this function. According to device specification, the actual value of each of these fields is one more than the value read. Read the device specification for details. InstancePtr is a pointer to the XCanFd instance to be worked on. SyncJumpWidth will store the Synchronization Jump Width value after this function returns. Its value ranges from 0 to 3. TimeSegment2 will store the Time Segment 2 value after this function returns. Its value ranges from 0 to 7. TimeSegment1 will store the Time Segment 1 value after this function returns. Its value ranges from 0 to 15. None. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_BTR_OFFSET, XCANFD_BTR_SJW_MASK, XCANFD_BTR_SJW_SHIFT, XCANFD_BTR_TS1_MASK, XCANFD_BTR_TS2_MASK, XCANFD_BTR_TS2_SHIFT, XCanFd_ReadReg.
void XCanFd_GetFBitTiming(XCanFd *InstancePtr, u8 *SyncJumpWidth, u8 *TimeSegment2, u8 *TimeSegment1)
This routine gets Bit time in Data Phase.
Time segment 1, Time segment 2 and Synchronization Jump Width values are read in this function. According to device specification, the actual value of each of these fields is one more than the value read. Read the device specification for details. InstancePtr is a pointer to the XCanFd instance to be worked on. SyncJumpWidth will store the Synchronization Jump Width value after this function returns. Its value ranges from 0 to 3. TimeSegment2 will store the Time Segment 2 value after this function returns. Its value ranges from 0 to 7. TimeSegment1 will store the Time Segment 1 value after this function returns. Its value ranges from 0 to 15. None. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_F_BTR_OFFSET, XCANFD_F_BTR_SJW_MASK, XCANFD_F_BTR_SJW_SHIFT, XCANFD_F_BTR_TS1_MASK, XCANFD_F_BTR_TS2_MASK, XCANFD_F_BTR_TS2_SHIFT, XCanFd_ReadReg.
int XCanFd_SetFBaudRatePrescaler(XCanFd *InstancePtr, u8 Prescaler)
This routine sets Baud Rate Prescaler value in Data Phase.
The system clock for the CAN controller is divided by (Prescaler + 1) to generate the quantum clock needed for sampling and synchronization. Read the device specification for details.Baud Rate Prescaler could be set only after CAN device entered Configuration Mode. So please call XCanFd_EnterMode() to enter Configuration Mode before using this function. InstancePtr is a pointer to the XCanFd instance to be worked on. Prescaler is the value to set. Valid values are from 1 to 256. - XST_SUCCESS if the Baud Rate Prescaler value is set successfully. XST_FAILURE if CAN device is not in Configuration Mode. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_BRPR_BRP_MASK, XCANFD_F_BRPR_OFFSET, XCanFd_GetMode, XCANFD_MODE_CONFIG, XCanFd_ReadReg, XCanFd_WriteReg.
Referenced by main, XCanFd_SelfTest, XCanFdPolledExample.
int XCanFd_SetFBitTiming(XCanFd *InstancePtr, u8 SyncJumpWidth, u8 TimeSegment2, u8 TimeSegment1)
This routine sets Bit time in Data Phase.
Time segment 1, Time segment 2 and Synchronization Jump Width are set in this function. Device specification requires the values passed into this function be one less than the actual values of these fields. Read the device specification for details.Bit time could be set only after CAN device entered Configuration Mode. Please call XCanFd_EnterMode() to enter Configuration Mode before using this function. InstancePtr is a pointer to the XCanFd instance to be worked on. SyncJumpWidth is the Synchronization Jump Width value to set. Valid values are from 0 to 3. TimeSegment2 is the Time Segment 2 value to set. Valid values are from 0 to 7. TimeSegment1 is the Time Segment 1 value to set. Valid values are from 0 to 15. - XST_SUCCESS if the Bit time is set successfully. XST_FAILURE if CAN device is not in Configuration Mode. XST_INVALID_PARAM if any value of SyncJumpWidth, TimeSegment2 and TimeSegment1 is invalid. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_F_BTR_OFFSET, XCANFD_F_BTR_SJW_MASK, XCANFD_F_BTR_SJW_SHIFT, XCANFD_F_BTR_TS1_MASK, XCANFD_F_BTR_TS2_MASK, XCANFD_F_BTR_TS2_SHIFT, XCanFd_GetMode, XCANFD_MAX_F_SJW_VALUE, XCANFD_MAX_F_TS1_VALUE, XCANFD_MAX_F_TS2_VALUE, XCANFD_MODE_CONFIG, XCanFd_WriteReg.
Referenced by main, XCanFd_SelfTest, XCanFdPolledExample.
void XCanFd_SetBitRateSwitch_DisableNominal(XCanFd *InstancePtr)
This routine Disables the BRSD bit, so that Bit Rate Switch can be happen with Nominal or configured rate.
Read the device specification for details. InstancePtr is a pointer to the XCanFd instance to be worked on. None. if we set BRSD bit in Mode Select Register then CAN Controller transmits CAN FD Frames with Nominal Bit Rate. else with configured bit rate(As specified in Data phase BRPR and BTR Registers.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_MSR_BRSD_MASK, XCANFD_MSR_OFFSET, XCanFd_ReadReg, XCANFD_SRR_CEN_MASK, XCanFd_WriteReg.
Referenced by main, XCanFdPolledExample.
void XCanFd_SetBitRateSwitch_EnableNominal(XCanFd *InstancePtr)
This routine sets the Bit Rate Switch with nominal bit rate.
if we set BRSD bit in Mode Select Register then CAN Controller transmits CAN FD Frames with Nominal Bit Rate. Read the device specification for details. InstancePtr is a pointer to the XCanFd instance to be worked on. None. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_MSR_BRSD_MASK, XCANFD_MSR_OFFSET, XCanFd_ReadReg, XCANFD_SRR_CEN_MASK, XCanFd_WriteReg.
u32 XCanFd_SetRxIntrWatermark(XCanFd *InstancePtr, s8 Threshold)
This routine sets the Rx Full threshold in the Watermark Interrupt Register.
InstancePtr is a pointer to the XCanFd instance. Threshold is the threshold to be set. The valid values are from 1 to 63. - XST_FAILURE - If the CAN device is not in Configuration Mode. XST_SUCCESS - If the Rx Full threshold is set in Watermark Interrupt Register. The threshold can only be set when the CAN device is in the configuration mode.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCanFd_GetMode, XCANFD_MODE_CONFIG, XCanFd_ReadReg, XCANFD_WIR_MASK, XCANFD_WIR_OFFSET, XCANFD_WM_FIFO0_THRESHOLD, XCanFd_WriteReg.
u32 XCanFd_SetRxIntrWatermarkFifo1(XCanFd *InstancePtr, s8 Threshold)
This routine sets the Rx Full threshold in the Watermark Interrupt Register.
InstancePtr is a pointer to the XCanFd instance. Threshold is the threshold to be set. The valid values are from 1 to 63. - XST_FAILURE - If the CAN device is not in Configuration Mode. XST_SUCCESS - If the Rx Full threshold is set in Watermark Interrupt Register. The threshold can only be set when the CAN device is in the configuration mode.This API is meant to be used with IP with CanFD 2.0 spec support only.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCanFd_GetMode, XCANFD_MODE_CONFIG, XCanFd_ReadReg, XCANFD_WIR_OFFSET, XCANFD_WMR_RXFWM_1_MASK, XCANFD_WMR_RXFWM_1_SHIFT, XCanFd_WriteReg.
u32 XCanFd_SetTxEventIntrWatermark(XCanFd *InstancePtr, u8 Threshold)
This routine sets the TX Events Full threshold in the Watermark Interrupt Register.
InstancePtr is a pointer to the XCanFd instance. Threshold is the threshold to be set. The valid values are from 1 to 31. - XST_FAILURE - If the CAN device is not in Configuration Mode. XST_SUCCESS - If the Rx Full threshold is set in Watermark Interrupt Register. The threshold can only be set when the CAN device is in the configuration mode, This API is meant to be used with IP with CanFD 2.0 spec support only.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCanFd_GetMode, XCANFD_MODE_CONFIG, XCanFd_ReadReg, XCANFD_TXEVENT_WIR_MASK, XCANFD_TXEVENT_WIR_OFFSET, XCanFd_WriteReg.
u32 XCanFd_SetRxFilterPartition(XCanFd *InstancePtr, u8 FilterPartition)
This routine sets the Receive filter partition in the Watermark Interrupt Register.
InstancePtr is a pointer to the XCanFd instance. FilterPartition is Filter Mask number, valid values are 0 to 31. - XST_FAILURE - If the CAN device is not in Configuration Mode. XST_SUCCESS - If the Rx Full threshold is set in Watermark Interrupt Register. The RX filter partition can only be set when the CAN device is in the configuration mode, This API is meant to be used with IP with CanFD 2.0 spec support only.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCanFd_GetMode, XCANFD_MODE_CONFIG, XCanFd_ReadReg, XCANFD_WIR_OFFSET, XCANFD_WMR_RXFP_MASK, XCANFD_WMR_RXFP_SHIFT, XCanFd_WriteReg.
int XCanFd_SelfTest(XCanFd *InstancePtr)
This function runs a self-test on the CAN driver/device.
The test resets the device, sets up the Loop Back mode, sends a standard frame, receives the frame, verifies the contents, and resets the device again.Note that this is a destructive test in that resets of the device are performed. Refer to the device specification for the device status after the reset operation. InstancePtr is a pointer to the XCanFd instance to be worked on. - XST_SUCCESS if the self-test passed. i.e., the frame received via the internal loop back has the same contents as the sent frame. XST_FAILURE Otherwise. If the CAN device does not work properly, this function may enter an infinite loop and will never return to the caller. If XST_FAILURE is returned, the device is not reset so that the caller could have a chance to check reason(s) causing the failure.
References EDL_CANFD, TEST_BRPR_BAUD_PRESCALAR, TEST_BTR_FIRST_TIMESEGMENT, TEST_BTR_SECOND_TIMESEGMENT, TEST_BTR_SYNCJUMPWIDTH, TEST_CANFD_DLC, TEST_FBRPR_BAUD_PRESCALAR, TEST_FBTR_FIRST_TIMESEGMENT, TEST_FBTR_SECOND_TIMESEGMENT, TEST_FBTR_SYNCJUMPWIDTH, TEST_MAIL_BOX_MASK, TEST_MESSAGE_ID, XCanFd_AcceptFilterDisable, XCanFd_AcceptFilterEnable, XCANFD_AFR_UAF_ALL_MASK, XCanFd_Create_CanFD_Dlc_BrsValue, XCanFd_CreateIdValue, XCANFD_DLCR_DLC_MASK, XCanFd_EnterMode, XCANFD_GET_RX_MODE, XCanFd_GetDlc2len, XCanFd_GetLen2Dlc, XCanFd_GetMode, XCanFd_IsBufferTransmitted, XCANFD_MODE_CONFIG, XCANFD_MODE_LOOPBACK, XCanFd_Recv_Mailbox, XCanFd_Recv_Sequential, XCanFd_Reset, XCanFd_RxBuff_MailBox_Active, XCanFd_RxBuff_MailBox_DeActive, XCanFd_Send, XCanFd_Set_MailBox_IdMask, XCanFd_SetBaudRatePrescaler, XCanFd_SetBitTiming, XCanFd_SetFBaudRatePrescaler, XCanFd_SetFBitTiming.
Referenced by main, XCanFdPolledExample.
void XCanFd_InterruptEnable(XCanFd *InstancePtr, u32 Mask)
This routine enables interrupt(s).
Use the XCANFD_IXR_* constants defined in xcanfd_hw.h to create the bit-mask to enable interrupts. InstancePtr is a pointer to the XCanFd instance to be worked on. Mask is the mask to enable. Bit positions of 1 will be enabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XCANFD_IXR_* bits defined in xcanfd_hw.h. None. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_IER_OFFSET, XCanFd_InterruptGetEnabled, XCANFD_IXR_ALL, XCanFd_WriteReg.
Referenced by main.
void XCanFd_InterruptDisable(XCanFd *InstancePtr, u32 Mask)
This routine disables interrupt(s).
Use the XCANFD_IXR_* constants defined in xcanfd_hw.h to create the bit-mask to disable interrupt(s). InstancePtr is a pointer to the XCanFd instance to be worked on. Mask is the mask to disable. Bit positions of 1 will be disabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XCANFD_IXR_* bits defined in xcanfd_hw.h. None. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_IER_OFFSET, XCanFd_InterruptGetEnabled, XCanFd_WriteReg.
void XCanFd_InterruptClear(XCanFd *InstancePtr, u32 Mask)
This function clears interrupt(s).
Every bit set in Interrupt Status Register indicates that a specific type of interrupt is occurring, and this function clears one or more interrupts by writing a bit mask to Interrupt Clear Register. InstancePtr is a pointer to the XCanFd instance to be worked on. Mask is the mask to clear. Bit positions of 1 will be cleared. Bit positions of 0 will not change the previous interrupt status. This mask is formed by OR'ing XCANFD_IXR_* bits defined in xcanfd_hw.h. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_ICR_OFFSET, XCanFd_InterruptGetStatus, XCanFd_WriteReg.
Referenced by XCanFd_IntrHandler.
void XCanFd_IntrHandler(void *InstancePtr)
This routine is the interrupt handler for the CAN driver.
This handler reads the interrupt status from the ISR, determines the source of the interrupts, calls according callbacks, and finally clears the interrupts.Application beyond this driver is responsible for providing callbacks to handle interrupts and installing the callbacks using XCanFd_SetHandler() during initialization phase. An example delivered with this driver demonstrates how this could be done. InstancePtr is a pointer to the XCanFd instance that just interrupted. None. None.
References XCanFd::ErrorHandler, XCanFd::ErrorRef, XCanFd::EventHandler, XCanFd::EventRef, XCanFd::IsReady, XCanFd::RecvHandler, XCanFd::RecvRef, XCanFd::SendHandler, XCanFd::SendRef, XCanFd_ClearBusErrorStatus, XCanFd_GetBusErrorStatus, XCanFd_InterruptClear, XCanFd_InterruptGetEnabled, XCanFd_InterruptGetStatus, XCANFD_IXR_ARBLST_MASK, XCANFD_IXR_BSOFF_MASK, XCANFD_IXR_BSRD_MASK, XCANFD_IXR_ERROR_MASK, XCANFD_IXR_PEE_MASK, XCANFD_IXR_RXBOFLW_BI_MASK, XCANFD_IXR_RXBOFLW_MASK, XCANFD_IXR_RXFOFLW_MASK, XCANFD_IXR_RXFWMFLL_1_MASK, XCANFD_IXR_RXFWMFLL_MASK, XCANFD_IXR_RXMNF_MASK, XCANFD_IXR_RXOK_MASK, XCANFD_IXR_RXRBF_MASK, XCANFD_IXR_SLP_MASK, XCANFD_IXR_TSCNT_OFLW_MASK, XCANFD_IXR_TXCRS_MASK, XCANFD_IXR_TXEOFLW_MASK, XCANFD_IXR_TXEWMFLL_MASK, XCANFD_IXR_TXOK_MASK, XCANFD_IXR_TXRRS_MASK, XCANFD_IXR_WKUP_MASK.
Referenced by main.
int XCanFd_SetHandler(XCanFd *InstancePtr, u32 HandlerType, void *CallBackFunc, void *CallBackRef)
This routine installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function Type ----------------------- --------------------------- XCANFD_HANDLER_SEND XCanFd_SendRecvHandler XCANFD_HANDLER_RECV XCanFd_SendRecvHandler XCANFD_HANDLER_ERROR XCanFd_ErrorHandler XCANFD_HANDLER_EVENT XCanFd_EventHandlerHandlerType Invoked by this driver when: ----------------------- -------------------------------------------------- XCANFD_HANDLER_SEND A frame transmitted by a call to XCanFd_Send() has been sent successfully.XCANFD_HANDLER_RECV A frame has been received and is sitting in the RX FIFO.XCANFD_HANDLER_ERROR An error interrupt is occurring.XCANFD_HANDLER_EVENT Any other kind of interrupt is occurring. InstancePtr is a pointer to the XCanFd instance to be worked on. HandlerType specifies which handler is to be attached. CallBackFunc is the address of the callback function. CallBackRef is a user data item that will be passed to the callback function when it is invoked. - XST_SUCCESS when handler is installed. XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XCanFd::ErrorHandler, XCanFd::ErrorRef, XCanFd::EventHandler, XCanFd::EventRef, XCanFd::IsReady, XCanFd::RecvHandler, XCanFd::RecvRef, XCanFd::SendHandler, XCanFd::SendRef, XCANFD_HANDLER_ERROR, XCANFD_HANDLER_EVENT, XCANFD_HANDLER_RECV, XCANFD_HANDLER_SEND.
Referenced by main.
void XCanFd_InterruptEnable_ReadyRqt(XCanFd *InstancePtr, u32 Mask)
This routine enables TxBuffer Ready Request interrupt(s).
InstancePtr is a pointer to the XCanFd instance to be worked on. Mask is the mask to enable. Bit positions of 1 will be enabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XCANFD_IETRS_OFFSET* bits defined in xcanfd_hw.h. None. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_IETRS_OFFSET, XCanFd_ReadReg, XCanFd_WriteReg.
void XCanFd_InterruptEnable_CancelRqt(XCanFd *InstancePtr, u32 Mask)
This routine enables TxBuffer Cancellation interrupt(s).
InstancePtr is a pointer to the XCanFd instance to be worked on. Mask is the mask to enable. Bit positions of 1 will be enabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XCANFD_IETCS_OFFSET* bits defined in xcanfd_hw.h. None. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_IETCS_OFFSET, XCanFd_ReadReg, XCanFd_WriteReg.
void XCanFd_InterruptDisable_ReadyRqt(XCanFd *InstancePtr, u32 Mask)
This routine disables TxBuffer Ready Request interrupt(s).
InstancePtr is a pointer to the XCanFd instance to be worked on. Mask is the mask to disable. Bit positions of 1 will be disabled. Bit positions of 0 will keep the previous setting. This mask is formed by AND'ing XCANFD_IETRS_OFFSET* bits defined in xcanfd_hw.h. None. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_IETRS_OFFSET, XCanFd_ReadReg, XCanFd_WriteReg.
void XCanFd_InterruptDisable_CancelRqt(XCanFd *InstancePtr, u32 Mask)
This routine disables the TxBuffer Cancel Request interrupt(s).
InstancePtr is a pointer to the XCanFd instance to be worked on. Mask is the mask to disable. Bit positions of 1 will be disabled. Bit positions of 0 will keep the previous setting. This mask is formed by AND'ing XCANFD_IETCS_OFFSET* bits defined in xcanfd_hw.h. None. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_IETCS_OFFSET, XCanFd_ReadReg, XCanFd_WriteReg.
void XCanFd_InterruptEnable_RxBuffFull(XCanFd *InstancePtr, u32 Mask, u32 RxBuffNumber)
This routine Enables the RxBuffer Full interrupt(s) in MailBox Mode.
InstancePtr is a pointer to the XCanFd instance to be worked on. Mask is the mask to disable. Bit positions of 1 will be disabled. Bit positions of 0 will keep the previous setting. This mask is formed by AND'ing XCANFD_RXBFLL*_OFFSET bits defined in xcanfd_hw.h. RxBuffNumber has two values if 0 -> Access RxBufferFull0 Reg else -> Access RxBufferFull1 Reg None. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCanFd_ReadReg, XCANFD_RXBFLL1_OFFSET, XCANFD_RXBFLL2_OFFSET, XCanFd_WriteReg.
void XCanFd_InterruptDisable_RxBuffFull(XCanFd *InstancePtr, u32 Mask, u32 RxBuffNumber)
This routine disables the RxBuffer Full interrupt(s) in MailBox Mode.
InstancePtr is a pointer to the XCanFd instance to be worked on. Mask is the mask to disable. Bit positions of 1 will be disabled. Bit positions of 0 will keep the previous setting. This mask is formed by AND'ing XCANFD_RXBFLL*_OFFSET bits defined in xcanfd_hw.h. RxBuffNumber has two values if 0 -> Access RxBufferFull0 Reg. else -> Access RxBufferFull1 Reg. None. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCanFd_ReadReg, XCANFD_RXBFLL1_OFFSET, XCANFD_RXBFLL2_OFFSET, XCanFd_WriteReg.
XCANFD_H
by using protection macros
XCanFd_IsTxDone
This macro checks if the transmission is complete.
InstancePtr is a pointer to the XCanFd instance to be worked on. - TRUE if the transmission is done (completed). FALSE if the transmission is not completed. C-Style signature: int XCanFd_IsTxDone(XCanFd *InstancePtr);
XCanFd_CreateIdValue
This macro calculates CAN message identifier value given identifier field values.
StandardId contains Standard Message ID value. SubRemoteTransReq contains Substitute Remote Transmission Request value. IdExtension contains Identifier Extension value. ExtendedId contains Extended Message ID value. RemoteTransReq contains Remote Transmission Request value. Message Identifier value. C-Style signature: u32 XCanFd_CreateIdValue(u32 StandardId, u32 SubRemoteTransReq, u32 IdExtension, u32 ExtendedId, u32 RemoteTransReq); Read the CAN specification for meaning of each parameter.
Referenced by main, XCanFd_SelfTest, XCanFdPolledExample.
XCanFd_Create_CanFD_DlcValue
This macro calculates value for Data Length Code register given Data Length Code value with EDL set to 1(Only Can FD frames).
DataLengCode indicates Data Length Code value. Value that can be assigned to Data Length Code register. C-Style signature: u32 XCanFd_Create_CanFD_DlcValue(u32 DataLengCode); Read the CAN specification for meaning of Data Length Code.
XCanFd_Create_CanFD_Dlc_BrsValue
This macro calculates value for Data Length Code register given Data Length Code value with EDL set to 1(Only Can FD frames) and Setting the BRS.
DataLengCode indicates Data Length Code value. Value that can be assigned to Data Length Code register. C-Style signature: u32 XCanFd_Create_CanFD_Dlc_BrsValue(u32 DataLengCode); Read the CAN specification for meaning of Data Length Code.
Referenced by main, XCanFd_SelfTest.
XCanFd_CreateDlcValue
This macro calculates value for Data Length Code register given Data Length Code value i.e Only Stand.
. Can frames. DataLengCode indicates Data Length Code value. Value that can be assigned to Data Length Code register. C-Style signature: u32 XCanFd_CreateDlcValue(u32 DataLengCode); Read the CAN specification for meaning of Data Length Code.
XCanFd_IsBufferTransmitted
This macro checks whether Particular Buffer is Transmitted or not.
Transmit Ready Request Register gives which Buffer is transmitted if you trigger the Buffer1 then TRR Reg : 0x00000001 After transmission Core clears the bit TRR Reg : 0x00000000 InstancePtr is a pointer to the XCanFd instance to be worked on. TxBuffer is the buffer where driver has written user data\ - TRUE if the device is busy and NOT ready to accept writes to AFIR and AFMR. FALSE if the device is ready to accept writes to AFIR and AFMR. C-Style signature: int XCanFd_IsAcceptFilterBusy(XCanFd *InstancePtr);
Referenced by XCanFd_PollQueue_Buffer, XCanFd_SelfTest.
MAKE_CURRENTBUFFER_ZERO
This macro initializes CurrentBuffer[32] to zeros.
InstancePtr is a pointer to the XCanFd instance to be worked on. none makes bufferstatus to zero.
XCANFD_TXID_OFFSET
This macro Returns the TXBUFFER ID Offset.
FreeBuffer is the Buffer number to locate the FIFO Index none
Referenced by XCanFd_Addto_Queue, XCanFd_Send.
XCANFD_TXDLC_OFFSET
This macro Returns the TXBUFFER DLC Offset.
FreeBuffer is the Buffer number to locate the FIFO none
Referenced by XCanFd_Addto_Queue, XCanFd_Send.
XCANFD_TXDW_OFFSET
This macro Returns the TXBUFFER DW Offset.
FreeBuffer is the Buffer number to locate the FIFO none
Referenced by XCanFd_Addto_Queue, XCanFd_Send.
XCANFD_TXEID_OFFSET
This macro Returns the TX Event Buffer ID Offset.
TXEVENTIndex is the Buffer number to locate the TXE FIFO Index This API is meant to be used with IP with CanFD 2.0 spec support only.
Referenced by XCanFd_Recv_TXEvents_Sequential.
XCANFD_TXEDLC_OFFSET
This macro Returns the TX Event Buffer DLC Offset.
TXEVENTIndex is the Buffer number to locate the FIFO This API is meant to be used with IP with CanFD 2.0 spec support only.
Referenced by XCanFd_Recv_TXEvents_Sequential.
XCANFD_RXID_OFFSET
This macro Returns the RXBUFFER ID Offset.
ReadIndex is the Buffer number to locate the FIFO none
Referenced by XCanFd_Recv_Mailbox.
XCANFD_RXDLC_OFFSET
This macro Returns the RXBUFFER DLC Offset.
ReadIndex is the Buffer number to locate the FIFO none
Referenced by XCanFd_Recv_Mailbox.
XCANFD_RXDW_OFFSET
This macro Returns the RXBUFFER DW Offset.
ReadIndex is the Buffer number to locate the FIFO none
Referenced by XCanFd_Recv_Mailbox.
XCANFD_FIFO_1_RXID_OFFSET
This macro Returns the RXBUFFER ID Offset for FIFO 1.
ReadIndex is the Buffer number to locate the FIFO This API is meant to be used with IP with CanFD 2.0 spec support only.
XCANFD_FIFO_1_RXDLC_OFFSET
This macro Returns the RXBUFFER DLC Offset for FIFO 1.
ReadIndex is the Buffer number to locate the FIFO This API is meant to be used with IP with CanFD 2.0 spec support only.
XCANFD_FIFO_1_RXDW_OFFSET
This macro Returns the RXBUFFER DW Offset for FIFO 1.
ReadIndex is the Buffer number to locate the FIFO This API is meant to be used with IP with CanFD 2.0 spec support only.
XCANFD_RCS_OFFSET
This macro Returns the RCS Register Offset.
NoCtrlStatus is to locate RCS Registers NoCtrlStatus = 0 -> RCS0 1 -> RCS1 2 -> RCS2
Referenced by XCanFd_Recv_Mailbox, XCanFd_RxBuff_MailBox_Active, XCanFd_RxBuff_MailBox_DeActive, XCanFd_Set_MailBox_IdMask.
XCANFD_AFMR_OFFSET
This macro Returns the AFMR Register Offset.
FilterIndex is the Index number of Mask Register none
Referenced by XCanFd_AcceptFilterGet, XCanFd_AcceptFilterSet.
XCANFD_AFIDR_OFFSET
This macro Returns the AFIDR Registger Offset.
FilterIndex is the Index of Id Register none
Referenced by XCanFd_AcceptFilterGet, XCanFd_AcceptFilterSet.
XCANFD_MAILBOX_MASK_OFFSET
This macro Returns the MAILBOX MODE RXMASK Offset.
BufferNr is the Buffer number to locate the FIFO none
Referenced by XCanFd_Set_MailBox_IdMask.
XCANFD_MAILBOX_ID_OFFSET
This macro Returns the MAILBOX MODE ID Offset.
BufferNr is the Buffer number to locate the FIFO none
Referenced by XCanFd_Set_MailBox_IdMask.
XCANFD_GET_RX_MODE
This macro Returns Design mode 1- Mailbox 0- Sequential.
InstancePtr is a pointer to the XCanFd instance to be worked on. none
Referenced by main, XCanFd_SelfTest, XCanFdPolledExample.
XCanFd_Reset
This function resets the CAN device.
Calling this function resets the device immediately, and any pending transmission or reception is terminated at once. Both Object Layer and Transfer Layer are reset. This function does not reset the Physical Layer. All registers are reset to the default values, and no previous status will be restored. TX FIFO, RX FIFO and TX High Priority Buffer are also reset.When a reset is required due to an internal error, the driver notifies the upper layer software of this need through the error status code or interrupts The upper layer software is responsible for calling this Reset function and then re-configuring the device.The CAN device will be in Configuration Mode immediately after this function returns. InstancePtr is a pointer to the XCanFd instance to be worked on. None. None.
Referenced by XCanFd_CfgInitialize, XCanFd_SelfTest.
XCanFd_GetBusErrorStatus
This function reads Error Status value from Error Status Register (ESR).
Use the XCANFD_ESR_* constants defined in xcanfd_hw.h to interpret the returned value. InstancePtr is a pointer to the XCanFd instance to be worked on. The 32-bit value read from Error Status Register. None.
Referenced by XCanFd_IntrHandler.
XCanFd_GetStatus
This function returns Status value from Status Register (SR).
Use the XCANFD_SR_* constants defined in xcanfd_hw.h to interpret the returned value. InstancePtr is a pointer to the XCanFd instance to be worked on. The 32-bit value read from Status Register. None.
Referenced by XCanFd_GetMode.
XCanFd_ClearBusErrorStatus
This function clears Error Status bit(s) previously set in Error Status Register (ESR).
Use the XCANFD_ESR_* constants defined in xcanfd_hw.h to create the value to pass in. If a bit was cleared in Error Status Register before this function is called, it will not be touched. InstancePtr is a pointer to the XCanFd instance to be worked on. Mask is he 32-bit mask used to clear bits in Error Status Register. Multiple XCANFD_ESR_* values could be 'OR'ed to clear multiple bits None.
Referenced by XCanFd_IntrHandler.
XCanFd_Get_Tranceiver_Delay_CompensationOffset
This function returns the Tranceive delay comensation Offset.
This function can call when user sends multiple Buffers using Addto_Queue() and XCanFd_Send_Queue(). InstancePtr is a pointer to the XCanFd instance to be worked on. None. None.
XCanFd_ClearTImeStamp_Count
This function Clears Time Stamp Counter Value.
InstancePtr is a pointer to the XCanFd instance to be worked on. none None.
XCanFd_GetTImeStamp_Count
This function returns Time Stamp Counter Value.
InstancePtr is a pointer to the XCanFd instance to be worked on. TimeStampCount None.
XCanFd_GetRxIntrWatermark
This routine returns the Rx water Mark threshold Value.
InstancePtr is a pointer to the XCanFd instance. Threshold Value. none
XCanFd_InterruptGetEnabled
This routine returns enabled interrupt(s).
Use the XCANFD_IXR_* constants defined in xcanfd_hw.h to interpret the returned value. InstancePtr is a pointer to the XCanFd instance to be worked on. Enabled interrupt(s) in a 32-bit format. None.
Referenced by XCanFd_InterruptDisable, XCanFd_InterruptEnable, XCanFd_IntrHandler.
XCanFd_InterruptGetStatus
This routine returns interrupt status read from Interrupt Status Register.
Use the XCANFD_IXR_* constants defined in xcanfd_hw.h to interpret the returned value. InstancePtr is a pointer to the XCanFd instance to be worked on. The value stored in Interrupt Status Register. None.
Referenced by XCanFd_InterruptClear, XCanFd_IntrHandler.
XCanFd_Get_NofRxBuffers
This routine returns Number of RCS registers to access because in Mail box mode user can configure 48,32,16 Rx Buffers.
InstancePtr is a pointer to the XCanFd instance to be worked on. The value stored in Interrupt Status Register. None.
XCanFd_Get_RxBuffers
This routine returns Number of RxBuffers user can Design RxBuffers as 48,32,16.
InstancePtr is a pointer to the XCanFd instance to be worked on. The value stored in Interrupt Status Register. None.
Referenced by main, XCanFdPolledExample.
XCanFD_Check_TrrVal_Set_Bit
This routine returns Number with right most bit set from the target input value.
Var is target value. Number with right most bit set from the target value. None.
Referenced by XCanFd_Addto_Queue, XCanFd_Send.
XCANFD_HW_H
by using protection macros
XCanFd_ReadReg
This macro reads the given register.
BaseAddress is the base address of the device RegOffset is the register offset to be read The 32-bit value of the register C-Style signature: u32 XCanFd_ReadReg(u32 BaseAddress, u32 RegOffset);
Referenced by XCanFd_AcceptFilterDisable, XCanFd_AcceptFilterEnable, XCanFd_AcceptFilterGet, XCanFd_AcceptFilterGetEnabled, XCanFd_Addto_Queue, XCanFd_Disable_Tranceiver_Delay_Compensation, XCanFd_Enable_Tranceiver_Delay_Compensation, XCanFd_EnterMode, XCanFd_GetBaudRatePrescaler, XCanFd_GetBitTiming, XCanFd_GetBusErrorCounter, XCanFd_GetFBaudRatePrescaler, XCanFd_GetFBitTiming, XCanFd_GetFreeBuffer, XCanFd_GetNofMessages_Stored_Rx_Fifo, XCanFd_GetNofMessages_Stored_TXE_FIFO, XCanFd_InterruptDisable_CancelRqt, XCanFd_InterruptDisable_ReadyRqt, XCanFd_InterruptDisable_RxBuffFull, XCanFd_InterruptEnable_CancelRqt, XCanFd_InterruptEnable_ReadyRqt, XCanFd_InterruptEnable_RxBuffFull, XCanFd_Pee_BusOff_Handler, XCanFd_Recv_Mailbox, XCanFd_Recv_Sequential, XCanFd_Recv_TXEvents_Sequential, XCanFd_RxBuff_MailBox_Active, XCanFd_RxBuff_MailBox_DeActive, XCanFd_Send, XCanFd_Set_MailBox_IdMask, XCanFd_Set_Tranceiver_Delay_Compensation, XCanFd_SetBitRateSwitch_DisableNominal, XCanFd_SetBitRateSwitch_EnableNominal, XCanFd_SetFBaudRatePrescaler, XCanFd_SetRxFilterPartition, XCanFd_SetRxIntrWatermark, XCanFd_SetRxIntrWatermarkFifo1, XCanFd_SetTxEventIntrWatermark, XCanFd_TxBuffer_Cancel_Request.
XCanFd_WriteReg
This macro writes the given register.
BaseAddress is the base address of the device RegOffset is the register offset to be written Data is the 32-bit value to write to the register None. C-Style signature: u32 XCanFd_WriteReg(u32 BaseAddress, u32 RegOffset, u32 Data);
Referenced by XCanFd_AcceptFilterDisable, XCanFd_AcceptFilterEnable, XCanFd_AcceptFilterSet, XCanFd_Addto_Queue, XCanFd_Disable_Tranceiver_Delay_Compensation, XCanFd_Enable_Tranceiver_Delay_Compensation, XCanFd_EnterMode, XCanFd_InterruptClear, XCanFd_InterruptDisable, XCanFd_InterruptDisable_CancelRqt, XCanFd_InterruptDisable_ReadyRqt, XCanFd_InterruptDisable_RxBuffFull, XCanFd_InterruptEnable, XCanFd_InterruptEnable_CancelRqt, XCanFd_InterruptEnable_ReadyRqt, XCanFd_InterruptEnable_RxBuffFull, XCanFd_Pee_BusOff_Handler, XCanFd_Recv_Mailbox, XCanFd_Recv_TXEvents_Sequential, XCanFd_RxBuff_MailBox_Active, XCanFd_RxBuff_MailBox_DeActive, XCanFd_Send, XCanFd_Send_Queue, XCanFd_Set_MailBox_IdMask, XCanFd_Set_Tranceiver_Delay_Compensation, XCanFd_SetBaudRatePrescaler, XCanFd_SetBitRateSwitch_DisableNominal, XCanFd_SetBitRateSwitch_EnableNominal, XCanFd_SetBitTiming, XCanFd_SetFBaudRatePrescaler, XCanFd_SetFBitTiming, XCanFd_SetRxFilterPartition, XCanFd_SetRxIntrWatermark, XCanFd_SetRxIntrWatermarkFifo1, XCanFd_SetTxEventIntrWatermark, XCanFd_TxBuffer_Cancel_Request.
XCANFD_MAX_FRAME_SIZE_IN_BYTES
Maximum Frame size.
TEST_MESSAGE_ID
Message id.
Referenced by main, XCanFd_SelfTest, XCanFdPolledExample.
TEST_CANFD_DLC
DLC Value.
Referenced by main, XCanFd_SelfTest.
TEST_MAIL_BOX_MASK
Mailbox Filter Index Value.
Referenced by XCanFd_SelfTest.
TEST_BRPR_BAUD_PRESCALAR
Baud Rate Prescalar.
Referenced by main, XCanFd_SelfTest, XCanFdPolledExample.
TEST_BTR_SYNCJUMPWIDTH
Synchronization Jump Width.
Referenced by main, XCanFd_SelfTest, XCanFdPolledExample.
TEST_BTR_SECOND_TIMESEGMENT
Time Segment 2.
Referenced by main, XCanFd_SelfTest, XCanFdPolledExample.
TEST_BTR_FIRST_TIMESEGMENT
Time Segment 1.
Referenced by main, XCanFd_SelfTest, XCanFdPolledExample.
TEST_FBRPR_BAUD_PRESCALAR
Baud Rate Prescalar for canfd.
Referenced by main, XCanFd_SelfTest, XCanFdPolledExample.
TEST_FBTR_SYNCJUMPWIDTH
Synchronization Jump Width for Canfd.
Referenced by main, XCanFd_SelfTest, XCanFdPolledExample.
TEST_FBTR_SECOND_TIMESEGMENT
Time Segment 2 for Canfd.
Referenced by main, XCanFd_SelfTest, XCanFdPolledExample.
TEST_FBTR_FIRST_TIMESEGMENT
Time Segment 1 for Canfd.
Referenced by main, XCanFd_SelfTest, XCanFdPolledExample.