xcanfd.c
static void StubHandler(void)
This function looks for the device configuration based on the device index.
The table XCanFd_ConfigTable[] contains the configuration information for each device in the system. InstanceIndex is a 0-based integer indexing all CAN devices in the system. A pointer to the configuration table entry corresponding to the given device ID, or NULL if no match is found. None. This routine is a stub for the asynchronous callbacks. The stub is here in case the upper layer forgot to set the handler(s). On initialization, all handlers are set to this callback. It is considered an error for this handler to be invoked.None. None.
static int XCanfd_TrrVal_Get_SetBit_Position(u32 u)
This function calculates the index position of the right most set bit.
u is GlobalTrrValue Index location of right most set bit log2 fast Math logic.
static u32 XCanFd_SeqRecv_logic(XCanFd *InstancePtr, u32 ReadIndex, u32 FsrVal, u32 *FramePtr, u8 fifo_no)
This function receives a CAN/CAN FD Frame as per the input Can Read Index value.
InstancePtr is a pointer to the XCanFd instance to be worked on. ReadIndex is Current RI(Read Index) maintained by Can Core. FsrVal is Fifo Status Registor value. FramePtr is a pointer to a 32-bit aligned buffer where the CAN/CAN FD frame is to be written. fifo_no is target fifo number - XST_SUCCESS after all operations This routine has generic logic for sequential receive mode
int XCanFd_CfgInitialize(XCanFd *InstancePtr, XCanFd_Config *ConfigPtr, UINTPTR EffectiveAddr)
This routine initializes a specific XCanFd instance/driver.
This function should only be used when no Virtual Memory support is needed.This initialization entails: Search for device configuration given the device ID.Initialize Base Address field of the XCanFd structure using the deviceaddress in the found device configuration.Populate all other data fields in the XCanFd structureReset the device. InstancePtr is a pointer to the XCanFd instance to be worked on. ConfigPtr is the pointer to XCanFd_Config instance EffectiveAddr is the base address of CANFD - XST_SUCCESS if initialization was successful XST_DEVICE_NOT_FOUND if device configuration information was not found for a device with the supplied device ID. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::ErrorHandler, XCanFd::EventHandler, XCanFd::IsReady, MAX_FILTER_INDEX, XCanFd_Config::Name, XCanFd_Config::NumofRxMbBuf, XCanFd_Config::NumofTxBuf, XCanFd::RecvHandler, XCanFd_Config::Rx_Mode, XCanFd::SendHandler, XCanFd_AcceptFilterSet, XCanFd_Reset.
Referenced by main, XCanFdPolledExample.
int XCanFd_stop(XCanFd *InstancePtr)
This routine releases resources of XCanFd instance/driver.
None - XST_SUCCESS if node release was successful XST_FAILURE or an error code or a reason code if node release was fail None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig.
Referenced by XCanFdPolledExample.
u32 XCanFd_AcceptFilterGetEnabled(XCanFd *InstancePtr)
This function returns enabled acceptance filters.
Use XCANFD_AFR_UAF*_MASK defined in xcanfd_hw.h to interpret the returned value. If no acceptance filters are enabled then all received frames are stored in the RX FIFO. InstancePtr is a pointer to the XCanFd instance to be worked on. The value stored in Acceptance Filter Register. Acceptance Filter Register is an optional register in Xilinx CAN device If it is NOT existing in the device, this function should NOT be used.Calling this function in this case will cause an assertion failure.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_AFR_OFFSET, XCanFd_ReadReg.
Referenced by XCanFd_AcceptFilterSet.
u8 XCanFd_GetMode(XCanFd *InstancePtr)
This routine returns current operation mode the CAN device is in.
InstancePtr is a pointer to the XCanFd instance to be worked on. - XCANFD_MODE_CONFIG if the device is in Configuration Mode. XCANFD_MODE_SLEEP if the device is in Sleep Mode. XCANFD_MODE_NORMAL if the device is in Normal Mode.XCANFD_MODE_LOOPBACK if the device is in Loop Back Mode.XCANFD_MODE_SNOOP if the device is in Snoop Mode.XCANFD_MODE_BR if the device is in Bus-Off recovery Mode.XCANFD_MODE_PEE if the device is in Protocol Exception Event mode. None.
References XCanFd::IsReady, XCanFd_GetStatus, XCANFD_MODE_CONFIG, XCANFD_MODE_LOOPBACK, XCANFD_MODE_NORMAL, XCANFD_MODE_PEE, XCANFD_MODE_SLEEP, XCANFD_MODE_SNOOP, XCANFD_SR_CONFIG_MASK, XCANFD_SR_NORMAL_MASK, XCANFD_SR_PEE_CONFIG_MASK, XCANFD_SR_SLEEP_MASK, XCANFD_SR_SNOOP_MASK.
Referenced by main, XCanFd_EnterMode, XCanFd_SelfTest, XCanFd_SetBaudRatePrescaler, XCanFd_SetBitTiming, XCanFd_SetFBaudRatePrescaler, XCanFd_SetFBitTiming, XCanFd_SetRxFilterPartition, XCanFd_SetRxIntrWatermark, XCanFd_SetRxIntrWatermarkFifo1, XCanFd_SetTxEventIntrWatermark, XCanFdPolledExample.
void XCanFd_EnterMode(XCanFd *InstancePtr, u8 OperationMode)
This function allows the CAN device to enter one of the following operation modes:
Configuration Mode: Pass in parameter XCANFD_MODE_CONFIGSleep Mode: Pass in parameter XCANFD_MODE_SLEEPNormal Mode: Pass in parameter XCANFD_MODE_NORMALLoop Back Mode: Pass in parameter XCANFD_MODE_LOOPBACKSnoop Mode: Pass in Parameter XCANFD_MODE_SNOOPAuto Bus-Off Recovery Mode: Pass in Parameter XCANFD_MODE_ABRStart Bus-Off Recovery Mode: Pass in Parameter XCANFD_MODE_SBRProtocol Exception Event Mode: Pass in Parameter XCANFD_MODE_PEEDisable AutoRetransmission Mode: Pass in Parameter XCANFD_MODE_DAR Read xcanfd.h and device specification for detailed description of each operation mode. InstancePtr is a pointer to the XCanFd instance to be worked on. OperationMode specify which operation mode to enter.Valid value is any of XCANFD_MODE_* defined in xcanfd.h. Please note no multiple modes could be entered at the same time. None. This function does NOT ensure CAN device enters the specified operation mode before returns the control to the caller. The caller is responsible for checking current operation mode using XCanFd_GetMode().
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCanFd_GetMode, XCANFD_MODE_ABR, XCANFD_MODE_CONFIG, XCANFD_MODE_DAR, XCANFD_MODE_LOOPBACK, XCANFD_MODE_NORMAL, XCANFD_MODE_PEE, XCANFD_MODE_SBR, XCANFD_MODE_SLEEP, XCANFD_MODE_SNOOP, XCANFD_MSR_ABR_MASK, XCANFD_MSR_CONFIG_MASK, XCANFD_MSR_DAR_MASK, XCANFD_MSR_DPEE_MASK, XCANFD_MSR_LBACK_MASK, XCANFD_MSR_OFFSET, XCANFD_MSR_SBR_MASK, XCANFD_MSR_SLEEP_MASK, XCANFD_MSR_SNOOP_MASK, XCanFd_ReadReg, XCANFD_SRR_CEN_MASK, XCANFD_SRR_OFFSET, XCanFd_WriteReg.
Referenced by main, XCanFd_SelfTest, XCanFdPolledExample.
void XCanFd_GetBusErrorCounter(XCanFd *InstancePtr, u8 *RxErrorCount, u8 *TxErrorCount)
This function reads Receive and Transmit error counters.
InstancePtr is a pointer to the XCanFd instance to be worked on. RxErrorCount will contain Receive Error Counter value after this function returns. TxErrorCount will contain Transmit Error Counter value after this function returns. None. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_ECR_OFFSET, XCANFD_ECR_REC_MASK, XCANFD_ECR_REC_SHIFT, XCANFD_ECR_TEC_MASK, XCanFd_ReadReg.
int XCanFd_Send(XCanFd *InstancePtr, u32 *FramePtr, u32 *TxBufferNumber)
This function sends a CAN/CANFD Frame.
This function first checks whether free buffer is there or not.if free buffer is there the user data will be written into the free buffer.otherwise it returns error code immediately. This function does not wait for the given frame being sent to CAN bus. InstancePtr is a pointer to the XCanFd instance to be worked on. FramePtr is a pointer to a 32-bit aligned buffer containing the CAN frame to be sent. TxBufferNumber is the buffer where the user data has been written and it is updated by driver. - XST_SUCCESS if TX FIFO was not full and the given frame was written into the FIFO; XST_FIFO_NO_ROOM if there is no room in the TX FIFO for the given frame None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::GlobalTrrMask, XCanFd::IsReady, TRR_MASK_INIT_VAL, XCanFD_Check_TrrVal_Set_Bit, XCANFD_DLCR_DLC_MASK, XCANFD_DLCR_EDL_MASK, XCANFD_DW_BYTES, XCanFd_GetDlc2len, XCanFd_GetFreeBuffer, XCanFd_ReadReg, XCANFD_TRR_OFFSET, XCANFD_TXDLC_OFFSET, XCANFD_TXDW_OFFSET, XCANFD_TXID_OFFSET, XCanFd_WriteReg.
Referenced by main, XCanFd_SelfTest.
int XCanFd_Addto_Queue(XCanFd *InstancePtr, u32 *FramePtr, u32 *TxBufferNumber)
This function writes the Data into specific Buffer.we have 32 TxBuffers we can Add data to each Buffer using this routine.This routine won't transmit the data.
it only adds data to Buffers. InstancePtr is a pointer to the XCanFd instance to be worked on. FramePtr is a pointer to a 32-bit aligned buffer containing the CAN frame to be sent. TxBufferNumber is Buffer Number where the data has written and is given back to user. - XST_SUCCESS if TX FIFO was not full and the given frame was written into the FIFO; XST_FIFO_NO_ROOM if there is no room in the TX FIFO for the given frame None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::GlobalTrrMask, XCanFd::GlobalTrrValue, XCanFd::IsReady, XCanFd::MultiBuffTrr, TRR_MASK_INIT_VAL, XCanFD_Check_TrrVal_Set_Bit, XCANFD_DLCR_DLC_MASK, XCANFD_DLCR_EDL_MASK, XCANFD_DW_BYTES, XCanFd_GetDlc2len, XCanFd_GetFreeBuffer, XCanFd_ReadReg, XCANFD_TRR_OFFSET, XCANFD_TXDLC_OFFSET, XCANFD_TXDW_OFFSET, XCANFD_TXID_OFFSET, XCanFd_WriteReg.
u32 XCanFd_Recv_Sequential(XCanFd *InstancePtr, u32 *FramePtr)
This function receives a CAN/CAN FD Frame.
This function first checks FSR Register.The FL bits tells the Number of Packets received. if FL is non Zero then Read the Packet and store it to user Buffer. InstancePtr is a pointer to the XCanFd instance to be worked on. FramePtr is a pointer to a 32-bit aligned buffer where the CAN/CAN FD frame to be written. - XST_SUCCESS if RX FIFO was not empty and a frame was read from RX FIFO successfully and written into the given buffer; XST_NO_DATA if there is no frame to be received from the FIFO The CANFD has two design modes. ->Sequential Mode - Core writes data sequentially to RxBuffers. ->MailBox Mode - Core writes data to RxBuffers when a ID Match happened. This routine distinguishes receive checking as per the frame availability from either Fifo 0 or Fifo 1.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_FSR_FL_1_MASK, XCANFD_FSR_FL_MASK, XCANFD_FSR_OFFSET, XCANFD_FSR_RI_1_MASK, XCANFD_FSR_RI_1_SHIFT, XCANFD_FSR_RI_MASK, XCanFd_ReadReg, XCANFD_RX_FIFO_0, XCANFD_RX_FIFO_1.
Referenced by main, XCanFd_SelfTest.
u32 XCanFd_Recv_TXEvents_Sequential(XCanFd *InstancePtr, u32 *FramePtr)
This function receives a CAN/CAN FD TX Events.
This function first checks FSR Register.The FL bits tells the Number of TX Event packets received. if FL is non Zero then Read the Packet and store it to user Buffer. InstancePtr is a pointer to the XCanFd instance to be worked on. FramePtr is a pointer to a 32-bit aligned buffer where the CAN/CAN FD frame Event to be written. - XST_SUCCESS if TXE FIFO was not empty and a frame was read from TX FIFO successfully and written into the given buffer; XST_NO_DATA if there is no frame to be received from the TXE FIFO This CANFD has two design modes. ->Sequential Mode - Core writes data sequentially to RxBuffers. ->MailBox Mode - Core writes data to RxBuffers when a ID Match happened. This routine is useful for Both the Modes.This API is meant to be used with IP with CanFD 2.0 spec support only.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCanFd_ReadReg, XCANFD_TXE_FL_MASK, XCANFD_TXE_FSR_OFFSET, XCANFD_TXE_IRI_MASK, XCANFD_TXE_RI_MASK, XCANFD_TXEDLC_OFFSET, XCANFD_TXEID_OFFSET, XCanFd_WriteReg.
u32 XCanFd_Recv_Mailbox(XCanFd *InstancePtr, u32 *FramePtr)
This function receives a CAN Frame in MAIL BOX Mode.
Read Rx Last Buffer Index from ISR Register. This tells which buffer is having data.then read and update the data to user buffer. InstancePtr is a pointer to the XCanFd instance to be worked on. FramePtr is a pointer to a 32-bit aligned buffer where the CAN frame to be receive. - XST_SUCCESS if RX FIFO was not empty and a frame was read from RX FIFO successfully and written into the given buffer; XST_NO_DATA if there is no frame to be received from the FIFO This CANFD has two design modes. ->Sequential Mode - Core writes data sequentially to RxBuffers. ->MailBox Mode - Core writes data to RxBuffers when a ID match happened. This routine is useful for MailBox Mode.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_CSB_SHIFT, XCANFD_DLCR_DLC_MASK, XCANFD_DLCR_EDL_MASK, XCANFD_DW_BYTES, XCanFd_GetDlc2len, XCANFD_ISR_OFFSET, XCANFD_IXR_RXLRM_BI_MASK, XCANFD_RCS_HCB_MASK, XCANFD_RCS_OFFSET, XCanFd_ReadReg, XCANFD_RXDLC_OFFSET, XCANFD_RXDW_OFFSET, XCANFD_RXID_OFFSET, XCANFD_RXLRM_BI_SHIFT, XCanFd_WriteReg.
Referenced by main, XCanFd_SelfTest.
u32 XCanFd_RxBuff_MailBox_Active(XCanFd *InstancePtr, u32 RxBuffer)
This function sets an RxBuffer to Active State.In Mailbox Mode configuration we can set each buffer to receive with specific Id and Mask.inorder compare we need to first Activate the Buffer.Maximum number of RxBuffers depends on Design.Range 48,32,16.
InstancePtr is a pointer to the XCanFd instance to be worked on. RxBuffer Receive Buffer Number defines which Buffer to configure Value ranges from 0 - 48 - XST_SUCCESS if the values were set successfully. none
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, CONTROL_STATUS_1, CONTROL_STATUS_2, CONTROL_STATUS_3, DESIGN_RANGE_1, DESIGN_RANGE_2, XCanFd::IsReady, XCANFD_RCS_OFFSET, XCanFd_ReadReg, XCanFd_WriteReg.
Referenced by main, XCanFd_SelfTest, XCanFdPolledExample.
u32 XCanFd_Set_MailBox_IdMask(XCanFd *InstancePtr, u32 RxBuffer, u32 MaskValue, u32 IdValue)
This function sets the Id and Mask for an RxBuffer to participate in Id match.if a packet is received with an id which is equal to id we configured, then it is stored in RxBuffer.
otherwise it won't. InstancePtr is a pointer to the XCanFd instance to be worked on. RxBuffer Receive Buffer Number defines which Buffer to configure Value ranges from 0 - 48(can get from NumofRxMbBuf) MaskValue is the value to write into the RxBuffer Mask Register IdValue is the value to write into the RxBuffer Id register - XST_SUCCESS if the values were set successfully. none
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, CONTROL_STATUS_1, CONTROL_STATUS_2, CONTROL_STATUS_3, DESIGN_RANGE_1, DESIGN_RANGE_2, XCanFd::IsReady, XCANFD_MAILBOX_ID_OFFSET, XCANFD_MAILBOX_MASK_OFFSET, XCANFD_RCS_OFFSET, XCanFd_ReadReg, XCanFd_WriteReg.
Referenced by main, XCanFd_SelfTest, XCanFdPolledExample.
u32 XCanFd_RxBuff_MailBox_DeActive(XCanFd *InstancePtr, u32 RxBuffer)
This function sets an RxBuffer to InActive State.if we change a buffer to InActive state, then Rx Packet won't store into that buffer, even the Id is matched.
InstancePtr is a pointer to the XCanFd instance to be worked on. RxBuffer Receive Buffer Number defines which Buffer to configure Value ranges from 0 - 48 - XST_SUCCESS if the values were set successfully. XST_FAILURE if the given filter was not disabled, or the CAN device was not ready to accept writes to AFMR and AFIR. none
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, CONTROL_STATUS_1, CONTROL_STATUS_2, CONTROL_STATUS_3, DESIGN_RANGE_1, DESIGN_RANGE_2, XCanFd::IsReady, XCANFD_MBRXBUF_MASK, XCANFD_RCS_OFFSET, XCanFd_ReadReg, XCanFd_WriteReg.
Referenced by main, XCanFd_SelfTest, XCanFdPolledExample.
int XCanFd_TxBuffer_Cancel_Request(XCanFd *InstancePtr, u32 BufferNumber)
This function Cancels a CAN/CAN FD Frame which was already initiated for transmission.This function first checks TRR Bit based on BufferNumber.
if TRR Bit is set, then it cancels the Buffers. InstancePtr is a pointer to the XCanFd instance to be worked on. BufferNumber is which Buffer to cancel out of 32 Buffers. - XST_SUCCESS if RX FIFO was not empty and a frame was read from RX FIFO successfully and written into the given buffer; XST_NO_DATA if there is no frame to be received from the FIFO This function first checks whether TRR bit is set or not if Set, it then checks the corresponding TCR bit ->if Set, then wait until cancellation is performed. ->if Not set, then set the corresponding TCR bit and wait until core clears it. if Not set, Nothing to do.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, MAX_BUFFER_INDEX, XCanFd_ReadReg, XCANFD_TCR_OFFSET, XCANFD_TRR_OFFSET, XCanFd_WriteReg.
void XCanFd_AcceptFilterEnable(XCanFd *InstancePtr, u32 FilterIndexMask)
This routine enables the acceptance filters.
Up to 32 filters can be enabled. InstancePtr is a pointer to the XCanFd instance to be worked on. FilterIndexMask specifies which filter(s) to enable. Use any XCANFD_AFR_UAF*_MASK to enable one filter, and "Or" multiple XCANFD_AFR_UAF*_MASK values if multiple filters need to be enabled. Any filter not specified in this parameter will keep its previous enable/disable setting. None. In Sequential Mode, in order to receive data, we need to enable these filters. if we want to make filtration i.e Id match then we need to set the Id value in AFR Id register.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_AFR_OFFSET, XCanFd_ReadReg, XCanFd_WriteReg.
Referenced by main, XCanFd_SelfTest, XCanFdPolledExample.
void XCanFd_AcceptFilterDisable(XCanFd *InstancePtr, u32 FilterIndexMask)
This routine disables the acceptance filters.
32 filters can be disabled. InstancePtr is a pointer to the XCanFd instance to be worked on. FilterIndexMask specifies which filter(s) to disable. Use any XCANFD_AFR_UAF*_MASK to disable one filter, and "Or" multiple XCANFD_AFR_UAF*_MASK values if multiple filters need to be disabled. Any filter not specified in this parameter will keep its previous enable/disable setting. If all acceptance filters are disabled then all received frames are stored in the RX FIFO. None. None
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_AFR_OFFSET, XCanFd_ReadReg, XCanFd_WriteReg.
Referenced by main, XCanFd_SelfTest, XCanFdPolledExample.
int XCanFd_AcceptFilterSet(XCanFd *InstancePtr, u32 FilterIndex, u32 MaskValue, u32 IdValue)
This function sets values to the Acceptance Filter Mask Register (AFMR) and Acceptance Filter ID Register (AFIR) for the specified Acceptance Filter.
Use XCANFD_IDR_* defined in xcanfd_hw.h to create the values to set the filter. Read xcanfd.h and device specification for details.This function should be called only after: The given filter is disabled by calling XCanFd_AcceptFilterDisable();And the CAN device is ready to accept writes to AFMR and AFIR, i.e., XCanFd_IsAcceptFilterBusy() returns FALSE. InstancePtr is a pointer to the XCanFd instance to be worked on. FilterIndex defines which Acceptance Filter Mask and ID Register to set. Use any single XCANFD_AFR_UAF*_MASK value.ranges from 1 32 MaskValue is the value to write to the chosen Acceptance Filter Mask Register. IdValue is the value to write to the chosen Acceptance Filter ID Register. - XST_SUCCESS if the values were set successfully. XST_FAILURE if the given filter was not disabled, or the CAN device was not ready to accept writes to AFMR and AFIR. Acceptance Filter Mask and ID Registers are optional registers in Xilinx XCanFd device.if they are not configured then device will receive data with any ID.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, MAX_FILTER_INDEX, MIN_FILTER_INDEX, XCanFd_AcceptFilterGetEnabled, XCANFD_AFIDR_OFFSET, XCANFD_AFMR_OFFSET, XCanFd_WriteReg.
Referenced by XCanFd_CfgInitialize.
void XCanFd_AcceptFilterGet(XCanFd *InstancePtr, u32 FilterIndex, u32 *MaskValue, u32 *IdValue)
This function reads the values of the Acceptance Filter Mask and ID Register for the specified Acceptance Filter.
Use XCANFD_IDR_* defined in xcanfd_hw.h to interpret the values. Read xcanfd.h and device specification for details. InstancePtr is a pointer to the XCanFd instance to be worked on. FilterIndex defines which Acceptance Filter Mask Register to get Mask and ID from. Use any single XCANFD_FILTER_* value. MaskValue will store the Mask value read from the chosen Acceptance Filter Mask Register after this function returns. IdValue will store the ID value read from the chosen Acceptance Filter ID Register after this function returns. None. Acceptance Filter Mask and ID Registers are optional registers in Xilinx CAN device. If they are NOT existing in the device, this function should NOT be used. Calling this function in this case will cause an assertion failure.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, MAX_FILTER_INDEX, MIN_FILTER_INDEX, XCANFD_AFIDR_OFFSET, XCANFD_AFMR_OFFSET, XCANFD_NOOF_AFR, XCanFd_ReadReg.
int XCanFd_GetDlc2len(u32 Dlc, u32 Edl)
This function returns Data Length Code(in Bytes),we need to pass DLC Field value in DLC Register.
Dlc Field in Data Length Code Register. Edl and Fdf Field in DLC register. Total Number of Bytes stored in each Buffer. Refer CAN FD Spec about DLC.
References XCANFD_DLC1, XCANFD_DLC10, XCANFD_DLC11, XCANFD_DLC12, XCANFD_DLC13, XCANFD_DLC14, XCANFD_DLC15, XCANFD_DLC2, XCANFD_DLC3, XCANFD_DLC4, XCANFD_DLC5, XCANFD_DLC6, XCANFD_DLC7, XCANFD_DLC8, XCANFD_DLC9, XCANFD_DLCR_DLC_SHIFT.
Referenced by main, XCanFd_Addto_Queue, XCanFd_Recv_Mailbox, XCanFd_SelfTest, XCanFd_Send.
u8 XCanFd_GetLen2Dlc(int len)
This function returns Data Length Code of 4bits,we need to pass length in bytes.
len is the length in bytes. Total Number of Bytes stored in each Buffer. Refer CAN FD Spec about DLC.
References XST_INVALID_DLC.
Referenced by main, XCanFd_SelfTest.
u32 XCanFd_GetFreeBuffer(XCanFd *InstancePtr)
This Routine returns the Free Buffers count out of 32 Transmit Buffers.
InstancePtr is a pointer to the XCanFd instance to be worked on. Returns number of Free buffers count. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, MAX_BUFFER_INDEX, XCanFd_ReadReg, XCANFD_TRR_OFFSET.
Referenced by XCanFd_Addto_Queue, XCanFd_Send.
int XCanFd_Send_Queue(XCanFd *InstancePtr)
This routine sends queue of buffers,when added to queue using Addto_Queue() Basically this will trigger the TRR Bit(s).This routine can be used when user want to send multiple packets at a time.
InstancePtr is a pointer to the XCanFd instance to be worked on. - XST_SUCCESS. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::GlobalTrrMask, XCanFd::GlobalTrrValue, XCanFd::IsReady, XCanFd::MultiBuffTrr, TRR_INIT_VAL, TRR_MASK_INIT_VAL, XCANFD_TRR_OFFSET, XCanFd_WriteReg.
void XCanFd_PollQueue_Buffer(XCanFd *InstancePtr)
This function Polls the TxBuffer(s) whether it is transmitted or not.
This function can call when user sends multiple Buffers using Addto_Queue() and XCanFd_Send_Queue(). InstancePtr is a pointer to the XCanFd instance to be worked on. None. None.
References XCanFd::IsReady, MAX_BUFFER_VAL, XCanFd::MultiBuffTrr, TRR_POS_MASK, XCanFd_IsBufferTransmitted.
int XCanFd_GetNofMessages_Stored_Rx_Fifo(XCanFd *InstancePtr, u8 fifo_no)
This function returns Number of messages Stored.
The FSR Register has Field called FL. this gives number of packets received. InstancePtr is a pointer to the XCanFd instance to be worked on. fifo_no is fifo number. Value is the number of messages stored in FSR Register. Selects either Rx Fifo 0 or Rx Fifo 1
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_FSR_FL_0_SHIFT, XCANFD_FSR_FL_1_MASK, XCANFD_FSR_FL_1_SHIFT, XCANFD_FSR_FL_MASK, XCANFD_FSR_OFFSET, XCanFd_ReadReg, XCANFD_RX_FIFO_0.
int XCanFd_GetNofMessages_Stored_TXE_FIFO(XCanFd *InstancePtr)
This function returns Number of messages Stored in TX Event FIFO The FSR Register has Field called FL.
this gives number of packets received. InstancePtr is a pointer to the XCanFd instance to be worked on. Value is the number of messages stored in FSR Register. This API is meant to be used with IP with CanFD 2.0 spec support only.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCanFd_ReadReg, XCANFD_TXE_FL_MASK, XCANFD_TXE_FL_SHIFT, XCANFD_TXE_FSR_OFFSET.
void XCanFd_Enable_Tranceiver_Delay_Compensation(XCanFd *InstancePtr)
This function Enables the Transceiver delay compensation.
InstancePtr is a pointer to the XCanFd instance to be worked on. None. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_F_BRPR_OFFSET, XCANFD_F_BRPR_TDC_ENABLE_MASK, XCanFd_ReadReg, XCanFd_WriteReg.
void XCanFd_Set_Tranceiver_Delay_Compensation(XCanFd *InstancePtr, u32 TdcOffset)
This function Sets the Transceiver delay compensation offset.
InstancePtr is a pointer to the XCanFd instance to be worked on. TdcOffset is the Delay Compensation Offset. None. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, TDC_MAX_OFFSET, TDC_SHIFT, XCANFD_F_BRPR_OFFSET, XCANFD_F_BRPR_TDCMASK, XCanFd_ReadReg, XCanFd_WriteReg.
void XCanFd_Disable_Tranceiver_Delay_Compensation(XCanFd *InstancePtr)
This function Disables the Transceiver delay compensation.
InstancePtr is a pointer to the XCanFd instance to be worked on. None. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_F_BRPR_OFFSET, XCANFD_F_BRPR_TDC_ENABLE_MASK, XCanFd_ReadReg, XCanFd_WriteReg.
void XCanFd_Pee_BusOff_Handler(XCanFd *InstancePtr)
This function recovers the CAN device from Protocol Exception Event & Busoff Event States.
InstancePtr is a pointer to the XCanFd instance to be worked on. None. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd_ReadReg, XCANFD_TCR_OFFSET, XCANFD_TRR_OFFSET, XCanFd_WriteReg.
Referenced by main.