xcanfd_intr.c
void XCanFd_InterruptEnable(XCanFd *InstancePtr, u32 Mask)
This routine enables interrupt(s).
Use the XCANFD_IXR_* constants defined in xcanfd_hw.h to create the bit-mask to enable interrupts. InstancePtr is a pointer to the XCanFd instance to be worked on. Mask is the mask to enable. Bit positions of 1 will be enabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XCANFD_IXR_* bits defined in xcanfd_hw.h. None. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_IER_OFFSET, XCanFd_InterruptGetEnabled, XCANFD_IXR_ALL, XCanFd_WriteReg.
Referenced by main.
void XCanFd_InterruptEnable_ReadyRqt(XCanFd *InstancePtr, u32 Mask)
This routine enables TxBuffer Ready Request interrupt(s).
InstancePtr is a pointer to the XCanFd instance to be worked on. Mask is the mask to enable. Bit positions of 1 will be enabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XCANFD_IETRS_OFFSET* bits defined in xcanfd_hw.h. None. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_IETRS_OFFSET, XCanFd_ReadReg, XCanFd_WriteReg.
void XCanFd_InterruptEnable_CancelRqt(XCanFd *InstancePtr, u32 Mask)
This routine enables TxBuffer Cancellation interrupt(s).
InstancePtr is a pointer to the XCanFd instance to be worked on. Mask is the mask to enable. Bit positions of 1 will be enabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XCANFD_IETCS_OFFSET* bits defined in xcanfd_hw.h. None. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_IETCS_OFFSET, XCanFd_ReadReg, XCanFd_WriteReg.
void XCanFd_InterruptDisable_ReadyRqt(XCanFd *InstancePtr, u32 Mask)
This routine disables TxBuffer Ready Request interrupt(s).
InstancePtr is a pointer to the XCanFd instance to be worked on. Mask is the mask to disable. Bit positions of 1 will be disabled. Bit positions of 0 will keep the previous setting. This mask is formed by AND'ing XCANFD_IETRS_OFFSET* bits defined in xcanfd_hw.h. None. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_IETRS_OFFSET, XCanFd_ReadReg, XCanFd_WriteReg.
void XCanFd_InterruptDisable_CancelRqt(XCanFd *InstancePtr, u32 Mask)
This routine disables the TxBuffer Cancel Request interrupt(s).
InstancePtr is a pointer to the XCanFd instance to be worked on. Mask is the mask to disable. Bit positions of 1 will be disabled. Bit positions of 0 will keep the previous setting. This mask is formed by AND'ing XCANFD_IETCS_OFFSET* bits defined in xcanfd_hw.h. None. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_IETCS_OFFSET, XCanFd_ReadReg, XCanFd_WriteReg.
void XCanFd_InterruptEnable_RxBuffFull(XCanFd *InstancePtr, u32 Mask, u32 RxBuffNumber)
This routine Enables the RxBuffer Full interrupt(s) in MailBox Mode.
InstancePtr is a pointer to the XCanFd instance to be worked on. Mask is the mask to disable. Bit positions of 1 will be disabled. Bit positions of 0 will keep the previous setting. This mask is formed by AND'ing XCANFD_RXBFLL*_OFFSET bits defined in xcanfd_hw.h. RxBuffNumber has two values if 0 -> Access RxBufferFull0 Reg else -> Access RxBufferFull1 Reg None. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCanFd_ReadReg, XCANFD_RXBFLL1_OFFSET, XCANFD_RXBFLL2_OFFSET, XCanFd_WriteReg.
void XCanFd_InterruptDisable_RxBuffFull(XCanFd *InstancePtr, u32 Mask, u32 RxBuffNumber)
This routine disables the RxBuffer Full interrupt(s) in MailBox Mode.
InstancePtr is a pointer to the XCanFd instance to be worked on. Mask is the mask to disable. Bit positions of 1 will be disabled. Bit positions of 0 will keep the previous setting. This mask is formed by AND'ing XCANFD_RXBFLL*_OFFSET bits defined in xcanfd_hw.h. RxBuffNumber has two values if 0 -> Access RxBufferFull0 Reg. else -> Access RxBufferFull1 Reg. None. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCanFd_ReadReg, XCANFD_RXBFLL1_OFFSET, XCANFD_RXBFLL2_OFFSET, XCanFd_WriteReg.
void XCanFd_InterruptDisable(XCanFd *InstancePtr, u32 Mask)
This routine disables interrupt(s).
Use the XCANFD_IXR_* constants defined in xcanfd_hw.h to create the bit-mask to disable interrupt(s). InstancePtr is a pointer to the XCanFd instance to be worked on. Mask is the mask to disable. Bit positions of 1 will be disabled. Bit positions of 0 will keep the previous setting. This mask is formed by OR'ing XCANFD_IXR_* bits defined in xcanfd_hw.h. None. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_IER_OFFSET, XCanFd_InterruptGetEnabled, XCanFd_WriteReg.
void XCanFd_InterruptClear(XCanFd *InstancePtr, u32 Mask)
This function clears interrupt(s).
Every bit set in Interrupt Status Register indicates that a specific type of interrupt is occurring, and this function clears one or more interrupts by writing a bit mask to Interrupt Clear Register. InstancePtr is a pointer to the XCanFd instance to be worked on. Mask is the mask to clear. Bit positions of 1 will be cleared. Bit positions of 0 will not change the previous interrupt status. This mask is formed by OR'ing XCANFD_IXR_* bits defined in xcanfd_hw.h. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_ICR_OFFSET, XCanFd_InterruptGetStatus, XCanFd_WriteReg.
Referenced by XCanFd_IntrHandler.
void XCanFd_IntrHandler(void *InstancePtr)
This routine is the interrupt handler for the CAN driver.
This handler reads the interrupt status from the ISR, determines the source of the interrupts, calls according callbacks, and finally clears the interrupts.Application beyond this driver is responsible for providing callbacks to handle interrupts and installing the callbacks using XCanFd_SetHandler() during initialization phase. An example delivered with this driver demonstrates how this could be done. InstancePtr is a pointer to the XCanFd instance that just interrupted. None. None.
References XCanFd::ErrorHandler, XCanFd::ErrorRef, XCanFd::EventHandler, XCanFd::EventRef, XCanFd::IsReady, XCanFd::RecvHandler, XCanFd::RecvRef, XCanFd::SendHandler, XCanFd::SendRef, XCanFd_ClearBusErrorStatus, XCanFd_GetBusErrorStatus, XCanFd_InterruptClear, XCanFd_InterruptGetEnabled, XCanFd_InterruptGetStatus, XCANFD_IXR_ARBLST_MASK, XCANFD_IXR_BSOFF_MASK, XCANFD_IXR_BSRD_MASK, XCANFD_IXR_ERROR_MASK, XCANFD_IXR_PEE_MASK, XCANFD_IXR_RXBOFLW_BI_MASK, XCANFD_IXR_RXBOFLW_MASK, XCANFD_IXR_RXFOFLW_MASK, XCANFD_IXR_RXFWMFLL_1_MASK, XCANFD_IXR_RXFWMFLL_MASK, XCANFD_IXR_RXMNF_MASK, XCANFD_IXR_RXOK_MASK, XCANFD_IXR_RXRBF_MASK, XCANFD_IXR_SLP_MASK, XCANFD_IXR_TSCNT_OFLW_MASK, XCANFD_IXR_TXCRS_MASK, XCANFD_IXR_TXEOFLW_MASK, XCANFD_IXR_TXEWMFLL_MASK, XCANFD_IXR_TXOK_MASK, XCANFD_IXR_TXRRS_MASK, XCANFD_IXR_WKUP_MASK.
Referenced by main.
int XCanFd_SetHandler(XCanFd *InstancePtr, u32 HandlerType, void *CallBackFunc, void *CallBackRef)
This routine installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function Type ----------------------- --------------------------- XCANFD_HANDLER_SEND XCanFd_SendRecvHandler XCANFD_HANDLER_RECV XCanFd_SendRecvHandler XCANFD_HANDLER_ERROR XCanFd_ErrorHandler XCANFD_HANDLER_EVENT XCanFd_EventHandlerHandlerType Invoked by this driver when: ----------------------- -------------------------------------------------- XCANFD_HANDLER_SEND A frame transmitted by a call to XCanFd_Send() has been sent successfully.XCANFD_HANDLER_RECV A frame has been received and is sitting in the RX FIFO.XCANFD_HANDLER_ERROR An error interrupt is occurring.XCANFD_HANDLER_EVENT Any other kind of interrupt is occurring. InstancePtr is a pointer to the XCanFd instance to be worked on. HandlerType specifies which handler is to be attached. CallBackFunc is the address of the callback function. CallBackRef is a user data item that will be passed to the callback function when it is invoked. - XST_SUCCESS when handler is installed. XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XCanFd::ErrorHandler, XCanFd::ErrorRef, XCanFd::EventHandler, XCanFd::EventRef, XCanFd::IsReady, XCanFd::RecvHandler, XCanFd::RecvRef, XCanFd::SendHandler, XCanFd::SendRef, XCANFD_HANDLER_ERROR, XCANFD_HANDLER_EVENT, XCANFD_HANDLER_RECV, XCANFD_HANDLER_SEND.
Referenced by main.