xcanfd_config.c
int XCanFd_SetBaudRatePrescaler(XCanFd *InstancePtr, u8 Prescaler)
This routine sets Baud Rate Prescaler value in Arbitration Phse.
The system clock for the CAN controller is divided by (Prescaler + 1) to generate the quantum clock needed for sampling and synchronization. Read the device specification for details.Baud Rate Prescaler could be set only after CAN device entered Configuration Mode. So please call XCanFd_EnterMode() to enter Configuration Mode before using this function. InstancePtr is a pointer to the XCanFd instance to be worked on. Prescaler is the value to set. Valid values are from 0 to 255. - XST_SUCCESS if the Baud Rate Prescaler value is set successfully. XST_FAILURE if CAN device is not in Configuration Mode. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_BRPR_OFFSET, XCanFd_GetMode, XCANFD_MODE_CONFIG, XCanFd_WriteReg.
Referenced by main, XCanFd_SelfTest, XCanFdPolledExample.
u8 XCanFd_GetBaudRatePrescaler(XCanFd *InstancePtr)
This routine gets Baud Rate Prescaler value.
The system clock for the CAN controller is divided by (Prescaler + 1) to generate the quantum clock needed for sampling and synchronization. Read the device specification for details. InstancePtr is a pointer to the XCanFd instance to be worked on. Current used Baud Rate Prescaler value. The value's range is from 0 to 255. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_BRPR_OFFSET, XCanFd_ReadReg.
int XCanFd_SetBitTiming(XCanFd *InstancePtr, u8 SyncJumpWidth, u8 TimeSegment2, u16 TimeSegment1)
This routine sets Bit time.
Time segment 1, Time segment 2 and Synchronization Jump Width are set in this function. Device specification requires the values passed into this function be one less than the actual values of these fields. Read the device specification for details.Bit time could be set only after CAN device entered Configuration Mode. Please call XCanFd_EnterMode() to enter Configuration Mode before using this function. InstancePtr is a pointer to the XCanFd instance to be worked on. SyncJumpWidth is the Synchronization Jump Width value to set. Valid values are from 0 to 3. TimeSegment2 is the Time Segment 2 value to set. Valid values are from 0 to 7. TimeSegment1 is the Time Segment 1 value to set. Valid values are from 0 to 15. - XST_SUCCESS if the Bit time is set successfully. XST_FAILURE if CAN device is not in Configuration Mode.XST_INVALID_PARAM if any value of SyncJumpWidth, TimeSegment2 and TimeSegment1 is invalid. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_BTR_OFFSET, XCANFD_BTR_SJW_MASK, XCANFD_BTR_SJW_SHIFT, XCANFD_BTR_TS1_MASK, XCANFD_BTR_TS2_MASK, XCANFD_BTR_TS2_SHIFT, XCanFd_GetMode, XCANFD_MAX_SJW_VALUE, XCANFD_MAX_TS1_VALUE, XCANFD_MAX_TS2_VALUE, XCANFD_MODE_CONFIG, XCanFd_WriteReg.
Referenced by main, XCanFd_SelfTest, XCanFdPolledExample.
void XCanFd_GetBitTiming(XCanFd *InstancePtr, u8 *SyncJumpWidth, u8 *TimeSegment2, u8 *TimeSegment1)
This routine gets Bit time.
Time segment 1, Time segment 2 and Synchronization Jump Width values are read in this function. According to device specification, the actual value of each of these fields is one more than the value read. Read the device specification for details. InstancePtr is a pointer to the XCanFd instance to be worked on. SyncJumpWidth will store the Synchronization Jump Width value after this function returns. Its value ranges from 0 to 3. TimeSegment2 will store the Time Segment 2 value after this function returns. Its value ranges from 0 to 7. TimeSegment1 will store the Time Segment 1 value after this function returns. Its value ranges from 0 to 15. None. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_BTR_OFFSET, XCANFD_BTR_SJW_MASK, XCANFD_BTR_SJW_SHIFT, XCANFD_BTR_TS1_MASK, XCANFD_BTR_TS2_MASK, XCANFD_BTR_TS2_SHIFT, XCanFd_ReadReg.
int XCanFd_SetFBaudRatePrescaler(XCanFd *InstancePtr, u8 Prescaler)
This routine sets Baud Rate Prescaler value in Data Phase.
The system clock for the CAN controller is divided by (Prescaler + 1) to generate the quantum clock needed for sampling and synchronization. Read the device specification for details.Baud Rate Prescaler could be set only after CAN device entered Configuration Mode. So please call XCanFd_EnterMode() to enter Configuration Mode before using this function. InstancePtr is a pointer to the XCanFd instance to be worked on. Prescaler is the value to set. Valid values are from 1 to 256. - XST_SUCCESS if the Baud Rate Prescaler value is set successfully. XST_FAILURE if CAN device is not in Configuration Mode. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_BRPR_BRP_MASK, XCANFD_F_BRPR_OFFSET, XCanFd_GetMode, XCANFD_MODE_CONFIG, XCanFd_ReadReg, XCanFd_WriteReg.
Referenced by main, XCanFd_SelfTest, XCanFdPolledExample.
u8 XCanFd_GetFBaudRatePrescaler(XCanFd *InstancePtr)
This routine gets Baud Rate Prescaler value in Data Phase.
The system clock for the CAN controller is divided by (Prescaler + 1) to generate the quantum clock needed for sampling and synchronization. Read the device specification for details. InstancePtr is a pointer to the XCanFd instance to be worked on. Current used Baud Rate Prescaler value. The value's range is from 1 to 256. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_BRPR_BRP_MASK, XCANFD_F_BRPR_OFFSET, XCanFd_ReadReg.
int XCanFd_SetFBitTiming(XCanFd *InstancePtr, u8 SyncJumpWidth, u8 TimeSegment2, u8 TimeSegment1)
This routine sets Bit time in Data Phase.
Time segment 1, Time segment 2 and Synchronization Jump Width are set in this function. Device specification requires the values passed into this function be one less than the actual values of these fields. Read the device specification for details.Bit time could be set only after CAN device entered Configuration Mode. Please call XCanFd_EnterMode() to enter Configuration Mode before using this function. InstancePtr is a pointer to the XCanFd instance to be worked on. SyncJumpWidth is the Synchronization Jump Width value to set. Valid values are from 0 to 3. TimeSegment2 is the Time Segment 2 value to set. Valid values are from 0 to 7. TimeSegment1 is the Time Segment 1 value to set. Valid values are from 0 to 15. - XST_SUCCESS if the Bit time is set successfully. XST_FAILURE if CAN device is not in Configuration Mode. XST_INVALID_PARAM if any value of SyncJumpWidth, TimeSegment2 and TimeSegment1 is invalid. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_F_BTR_OFFSET, XCANFD_F_BTR_SJW_MASK, XCANFD_F_BTR_SJW_SHIFT, XCANFD_F_BTR_TS1_MASK, XCANFD_F_BTR_TS2_MASK, XCANFD_F_BTR_TS2_SHIFT, XCanFd_GetMode, XCANFD_MAX_F_SJW_VALUE, XCANFD_MAX_F_TS1_VALUE, XCANFD_MAX_F_TS2_VALUE, XCANFD_MODE_CONFIG, XCanFd_WriteReg.
Referenced by main, XCanFd_SelfTest, XCanFdPolledExample.
void XCanFd_GetFBitTiming(XCanFd *InstancePtr, u8 *SyncJumpWidth, u8 *TimeSegment2, u8 *TimeSegment1)
This routine gets Bit time in Data Phase.
Time segment 1, Time segment 2 and Synchronization Jump Width values are read in this function. According to device specification, the actual value of each of these fields is one more than the value read. Read the device specification for details. InstancePtr is a pointer to the XCanFd instance to be worked on. SyncJumpWidth will store the Synchronization Jump Width value after this function returns. Its value ranges from 0 to 3. TimeSegment2 will store the Time Segment 2 value after this function returns. Its value ranges from 0 to 7. TimeSegment1 will store the Time Segment 1 value after this function returns. Its value ranges from 0 to 15. None. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_F_BTR_OFFSET, XCANFD_F_BTR_SJW_MASK, XCANFD_F_BTR_SJW_SHIFT, XCANFD_F_BTR_TS1_MASK, XCANFD_F_BTR_TS2_MASK, XCANFD_F_BTR_TS2_SHIFT, XCanFd_ReadReg.
void XCanFd_SetBitRateSwitch_EnableNominal(XCanFd *InstancePtr)
This routine sets the Bit Rate Switch with nominal bit rate.
if we set BRSD bit in Mode Select Register then CAN Controller transmits CAN FD Frames with Nominal Bit Rate. Read the device specification for details. InstancePtr is a pointer to the XCanFd instance to be worked on. None. None.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_MSR_BRSD_MASK, XCANFD_MSR_OFFSET, XCanFd_ReadReg, XCANFD_SRR_CEN_MASK, XCanFd_WriteReg.
void XCanFd_SetBitRateSwitch_DisableNominal(XCanFd *InstancePtr)
This routine Disables the BRSD bit, so that Bit Rate Switch can be happen with Nominal or configured rate.
Read the device specification for details. InstancePtr is a pointer to the XCanFd instance to be worked on. None. if we set BRSD bit in Mode Select Register then CAN Controller transmits CAN FD Frames with Nominal Bit Rate. else with configured bit rate(As specified in Data phase BRPR and BTR Registers.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCANFD_MSR_BRSD_MASK, XCANFD_MSR_OFFSET, XCanFd_ReadReg, XCANFD_SRR_CEN_MASK, XCanFd_WriteReg.
Referenced by main, XCanFdPolledExample.
u32 XCanFd_SetRxIntrWatermark(XCanFd *InstancePtr, s8 Threshold)
This routine sets the Rx Full threshold in the Watermark Interrupt Register.
InstancePtr is a pointer to the XCanFd instance. Threshold is the threshold to be set. The valid values are from 1 to 63. - XST_FAILURE - If the CAN device is not in Configuration Mode. XST_SUCCESS - If the Rx Full threshold is set in Watermark Interrupt Register. The threshold can only be set when the CAN device is in the configuration mode.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCanFd_GetMode, XCANFD_MODE_CONFIG, XCanFd_ReadReg, XCANFD_WIR_MASK, XCANFD_WIR_OFFSET, XCANFD_WM_FIFO0_THRESHOLD, XCanFd_WriteReg.
u32 XCanFd_SetRxIntrWatermarkFifo1(XCanFd *InstancePtr, s8 Threshold)
This routine sets the Rx Full threshold in the Watermark Interrupt Register.
InstancePtr is a pointer to the XCanFd instance. Threshold is the threshold to be set. The valid values are from 1 to 63. - XST_FAILURE - If the CAN device is not in Configuration Mode. XST_SUCCESS - If the Rx Full threshold is set in Watermark Interrupt Register. The threshold can only be set when the CAN device is in the configuration mode.This API is meant to be used with IP with CanFD 2.0 spec support only.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCanFd_GetMode, XCANFD_MODE_CONFIG, XCanFd_ReadReg, XCANFD_WIR_OFFSET, XCANFD_WMR_RXFWM_1_MASK, XCANFD_WMR_RXFWM_1_SHIFT, XCanFd_WriteReg.
u32 XCanFd_SetTxEventIntrWatermark(XCanFd *InstancePtr, u8 Threshold)
This routine sets the TX Events Full threshold in the Watermark Interrupt Register.
InstancePtr is a pointer to the XCanFd instance. Threshold is the threshold to be set. The valid values are from 1 to 31. - XST_FAILURE - If the CAN device is not in Configuration Mode. XST_SUCCESS - If the Rx Full threshold is set in Watermark Interrupt Register. The threshold can only be set when the CAN device is in the configuration mode, This API is meant to be used with IP with CanFD 2.0 spec support only.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCanFd_GetMode, XCANFD_MODE_CONFIG, XCanFd_ReadReg, XCANFD_TXEVENT_WIR_MASK, XCANFD_TXEVENT_WIR_OFFSET, XCanFd_WriteReg.
u32 XCanFd_SetRxFilterPartition(XCanFd *InstancePtr, u8 FilterPartition)
This routine sets the Receive filter partition in the Watermark Interrupt Register.
InstancePtr is a pointer to the XCanFd instance. FilterPartition is Filter Mask number, valid values are 0 to 31. - XST_FAILURE - If the CAN device is not in Configuration Mode. XST_SUCCESS - If the Rx Full threshold is set in Watermark Interrupt Register. The RX filter partition can only be set when the CAN device is in the configuration mode, This API is meant to be used with IP with CanFD 2.0 spec support only.
References XCanFd_Config::BaseAddress, XCanFd::CanFdConfig, XCanFd::IsReady, XCanFd_GetMode, XCANFD_MODE_CONFIG, XCanFd_ReadReg, XCANFD_WIR_OFFSET, XCANFD_WMR_RXFP_MASK, XCANFD_WMR_RXFP_SHIFT, XCanFd_WriteReg.