mcdma
XMcdma_Handler
For Done Handler.
XMcdma_ChanHandler
For Done Handler.
XMcdma_QScheduler
typedef void(* XMcdma_DoneHandler)(void *CallBackRef, u32 Chan_Id))(void *CallBackRef, u32 Chan_Id)
typedef void(* XMcdma_ErrorHandler)(void *CallBackRef, u32 Chan_id, u32 ErrorMask))(void *CallBackRef, u32 Chan_id, u32 ErrorMask)
typedef void(* XMcdma_PktDropHandler)(void *CallBackRef, u32 Chan_Id))(void *CallBackRef, u32 Chan_Id)
typedef void(* XMcdma_TxDoneHandler)(void *CallBackRef, u32 Chan_Id))(void *CallBackRef, u32 Chan_Id)
typedef void(* XMcdma_TxErrorHandler)(void *CallBackRef, u32 Chan_id, u32 ErrorMask))(void *CallBackRef, u32 Chan_id, u32 ErrorMask)
typedef void(* XMcdma_ChanDoneHandler)(void *CallBackRef))(void *CallBackRef)
typedef void(* XMcdma_ChanErrorHandler)(void *CallBackRef, u32 ErrorMask))(void *CallBackRef, u32 ErrorMask)
typedef void(* XMcdma_ChanPktDropHandler)(void *CallBackRef))(void *CallBackRef)
typedef u32 XMcdma_Bd[16][16]
s32 XMcDma_CfgInitialize(XMcdma *InstancePtr, XMcdma_Config *CfgPtr)
This function initializes an MCDMA core.
This function must be called prior to using an MCDMA core. Initialization of an MCDMA includes setting up the instance data and ensuring the hardware is in a quiescent state and resets all the hardware configurations. InstancePtr is a pointer to the XMcdma instance. CfgPtr is a reference to a structure containing information about a specific XMcdma instance. XST_SUCCESS if initialization was successful. None.
References XMcDma_Initialize, XMcDma_Reset, XMcdma_ResetIsDone, XMcdma_SetARCache, XMcdma_SetAWCache.
Referenced by main.
s32 XMcDma_Initialize(XMcdma *InstancePtr, XMcdma_Config *CfgPtr)
This function initializes an MCDMA core.
This function must be called prior to using an MCDMA core. Initialization of an MCDMA includes setting up the instance data and updating the driver filed with a proper values. InstancePtr is a pointer to the XMcdma instance. CfgPtr is a reference to a structure containing information about a specific XMcdma instance. XST_SUCCESS if initialization was successful. When user calls this function he should ensure the hardware is in a quiescent state by resetting all the hardware Configurations.
Referenced by XMcDma_CfgInitialize.
void XMcDma_Reset(XMcdma *InstancePtr)
This function resets the MCDMA core.
InstancePtr is a pointer to the XMcdma instance. None. This function resets all the configurations made previously.
Referenced by XMcDma_CfgInitialize, XMcdma_SelfTest.
void XMcdma_SetSGAWCache(XMcdma *InstancePtr, u8 Value)
This function sets the AWCACHE field of the SG interface With the user specified value.
InstancePtr is the driver instance we are working on Value is the AWCACHE value to be written. None None.
void XMcdma_SetSGARCache(XMcdma *InstancePtr, u8 Value)
This function sets the ARCACHE field of the SG interface With the user specified value.
InstancePtr is the driver instance we are working on Value is the ARCACHE value to be written. None None.
u32 XMcdma_ResetIsDone(XMcdma *InstancePtr)
Check whether reset is done.
InstancePtr is a pointer to the DMA engine instance to be worked on. 1 if reset is done. 0 if reset is not done None
References XMcdma_GetMcdmaRxChan, XMcdma_GetMcdmaTxChan.
Referenced by XMcDma_CfgInitialize, XMcdma_SelfTest.
u32 XMcdma_Start(XMcdma_ChanCtrl *Chan)
Start the DMA engine.
Chan is the Channel instance to be worked on XST_SUCCESS for success.XST_FAILURE if starting the hardware fails. None
Referenced by XMcdma_UpdateChanTDesc.
u32 XMcdma_ChanHwStop(XMcdma_ChanCtrl *Chan)
Stops the DMA engine.
Chan is the Channel instance to be worked on XST_SUCCESS for success.XST_FAILURE if hardware fails stop. None
void XMcdma_EnableCh(XMcdma_ChanCtrl *Chan)
Enables a particular channel.
Chan is the Channel instance to be worked on none None
Referenced by XMcDma_ChanToHw.
u16 XMcdma_GetChanServiced(XMcdma *InstancePtr)
Gets the last serviced s2mm channel number.
InstancePtr is a pointer to the DMA engine instance to be worked on. Channel id that last serviced. None
u16 XMcdma_GetTxChanServiced(XMcdma *InstancePtr)
Gets the last serviced mm2s channel number.
InstancePtr is a pointer to the DMA engine instance to be worked on. Channel id that last serviced. None
u32 XMCdma_GetChan_Weight(XMcdma_ChanCtrl *Chan)
u32 XMCdma_SetChan_Weight(XMcdma_ChanCtrl *Chan, u8 Weight)
u32 XMCdma_GetChan_PktDoneCnt(XMcdma_ChanCtrl *Chan)
void XMcdma_DumpChanRegs(XMcdma_ChanCtrl *Chan)
Dump the registers for a channel.
Chan is the MCDMA Channel to be worked on. None
int XMcdma_UpdateChanCDesc(XMcdma_ChanCtrl *Chan)
Update Current Descriptor for the MCDMA Channel.
Chan is the Channel instance to be worked on XST_SUCCESS upon success None.
Referenced by XMcDma_ChanToHw.
int XMcdma_UpdateChanTDesc(XMcdma_ChanCtrl *Chan)
Update Tail Desc for the Channel.
Chan is the MCDMA Channel to be worked on. XST_SUCCESS upon successXST_DMA_ERROR if no valid BD available to put into current BD register
References XMcdma_ChanHwIsStarted, XMcdma_HwIsStarted, XMcdma_Start.
Referenced by XMcDma_ChanToHw.
u32 XMcDma_ChanBdCreate(XMcdma_ChanCtrl *Chan, UINTPTR Addr, u32 Count)
Using a memory segment allocated by the caller, This function creates and setup the BD Chain for the MCDMA Channel.
Chan is the MCDMA Channel to be worked on.. Addr is the address of the application memory region. Count is the number of BDs to setup in the application memory region. XST_SUCCESS if initialization was successfulXST_INVALID_PARAM if Count is not positive.
References XMcdma_BdWrite.
u32 XMcDma_ChanSubmit(XMcdma_ChanCtrl *Chan, UINTPTR BufAddr, u32 len)
This function Populates the BD Chain with the required buffer address and length fields.
User can submit multiple buffers/buffer descriptors by calling this function multiple times Chan is the MCDMA Channel to be worked on.. BufAddr is the buffer address to which data should send/recv. len is the Amount of data user requested to send/recv. XST_SUCCESS if initialization was successfulXST_FAILURE if the BdStartAddress or requested bdlen doesn't match for the driver requirements.
References XMcdma_BdChainNextBd, XMcdma_BdClear, XMcdma_BdSetBufAddr, XMcdma_BdWrite.
u32 XMcDma_Chan_Sideband_Submit(XMcdma_ChanCtrl *ChanPtr, UINTPTR BufAddr, u32 Len, u32 *AppPtr, u16 Tuser, u16 Tid)
This function populates the BD Chain with the required buffer address, length APP(user application), TUSER and TID fields.
User can submit multiple buffers/buffer descriptors by calling this function multiple times ChanPtr is the MCDMA Channel to be worked on.. BufAddr is the buffer address to which data should send/recv. Len is the Amount of data user requested to send/recv. AppPtr is the point to APP fields. Tuser is the value presented on the beat that has TLAST. Tid is the value value presented on the beat that has TLAST. XST_SUCCESS if initialization was successfulXST_FAILURE if the BdStartAddress or requested bdlen doesn't match for the driver requirements.
References XMcdma_BdChainNextBd, XMcdma_BdClear, XMcdma_BdSetBufAddr, XMcDma_BdSetCtrlSideBand, XMcdma_BdWrite.
u32 XMcDma_ChanToHw(XMcdma_ChanCtrl *Chan)
This function triggers/Starts the h/w by programming the Current and Tail Descriptors and enabling the particular channel.
Chan is the MCDMA Channel to be worked on.. XST_SUCCESS if initialization was successfulXST_FAILURE In case of failure
References XMcdma_EnableCh, XMcdma_UpdateChanCDesc, XMcdma_UpdateChanTDesc.
int XMcdma_BdChainFromHW(XMcdma_ChanCtrl *Chan, u32 BdLimit, XMcdma_Bd **BdSetPtr)
Returns a set of BD(s) that have been processed by hardware.
The returned BDs may be examined by the application to determine the outcome of the DMA transactions. Once the BDs have been examined, the application must call XMcdma_BdChainFree() in the same order which they were retrieved here.If hardware has partially completed a packet spanning multiple BDs, then none of the BDs for that packet will be included in the results. Chan is the MCDMA Channel to be worked on.. BdLimit is the maximum number of BDs to return in the set. BdSetPtr is an output parameter, it points to the first BD available for examination. The number of BDs processed by hardware. A value of 0 indicates that no data is available. No more than BdLimit BDs will be returned. Treat BDs returned by this function as read-only.
References XMcdma_BdChainNextBd, XMcdma_BdRead.
int XMcdma_BdChainFree(XMcdma_ChanCtrl *Chan, int BdCount, XMcdma_Bd *BdSetPtr)
Frees a set of BDs that had been previously retrieved with XMcdma_BdChainFromHW().
Chan is the MCDMA Channel to be worked on.. BdCount is the number of BDs to free. BdSetPtr is the head of a list of BDs returned by XMcdma_BdChainFromHW(). XST_SUCCESS if the set of BDs was freed.XST_INVALID_PARAM if NumBd is negative This function should not be preempted by another XAxiMcDma function call that modifies the BD space. It is the caller's responsibility to ensure mutual exclusion.
References XMcdma_BdChainNextBd, XMcdma_BdClear.
u32 XMcdma_BdSetBufAddr(XMcdma_Bd *BdPtr, UINTPTR Addr)
Set the Buffer descriptor buffer address field.
BdPtr is the BD to operate on Addr is the address to set XST_SUCCESS if buffer address set successfullyXST_INVALID_PARAM if hardware has no DRE and address is not aligned
References XMcdma_BdRead, XMcdma_BdWrite, XMcdma_BdWrite64.
Referenced by XMcDma_Chan_Sideband_Submit, XMcDma_ChanSubmit.
void XMcDma_BdSetCtrl(XMcdma_Bd *BdPtr, u32 Data)
Set the control bits for a BD.
BdPtr is the BD to operate on. Data is the bit value to set None None
References XMcdma_BdRead, XMcdma_BdWrite.
int XMcDma_BdSetAppWord(XMcdma_Bd *BdPtr, int Offset, u32 Word)
Set the APP word at the specified APP word offset for a BD.
BdPtr is the BD to operate on Offset is the offset inside the APP word, it is valid from 0 to 4 Word is the value to set XST_SUCCESS for successXST_INVALID_PARAM under following error conditions. 1) StsCntrlStrm is not built in hardware 2) Offset is not in valid range
References XMcdma_BdRead, XMcdma_BdWrite.
u32 XMcDma_BdGetAppWord(XMcdma_Bd *BdPtr, int Offset, int *Valid)
Get the APP word at the specified APP word offset for a BD.
BdPtr is the BD to operate on. Offset is the offset inside the APP word, it is valid from 0 to 4 Valid is to tell the caller whether parameters are valid The APP word. Passed in parameter Valid holds 0 for failure, and 1 for success.
References XMcdma_BdRead.
u32 XMcdma_SetChanCoalesceDelay(XMcdma_ChanCtrl *Chan, u32 IrqCoalesce, u32 IrqDelay)
Set interrupt coalescing parameters for a particular channel.
Chan is the MCDMA Channel to be worked on.. IrqCoalesce is the Irq Threshold value valid ranges are 1 to 255 IrqDelay is the Irq Delay value valid ranges are 1 to 255 XST_SUCCESS if Interrupt Coalescing settings updatedXST_FAILURE if IrqCoalesce and IrqDelay parameters are out of range
void XMcDma_DumpBd(XMcdma_Bd *BdPtr)
Dump the fields of a BD.
BdPtr is the BD to operate on. None
References XMcdma_BdRead.
void XMcdma_ChanIntrHandler(void *Instance)
This function is the Per Channel interrupt handler for the MCDMA core.
This handler reads the pending interrupt from Status register, determines the source of the interrupts and calls the respective callbacks for the interrupts that are enabled in the per channel control register, and finally clears the interrupts.The application is responsible for connecting this function to the interrupt system. Application beyond this driver is also responsible for providing callbacks to handle interrupts and installing the callbacks using XMcdma_ChanSetCallBack() during initialization phase. Instance is a pointer to the Channel instance to be worked on. None. To generate interrupt required interrupts should be enabled.
References XMcdma_ChanAckIrq, XMcdma_ChanGetIrq.
s32 XMcdma_ChanSetCallBack(XMcdma_ChanCtrl *Chan, XMcdma_ChanHandler HandlerType, void *CallBackFunc, void *CallBackRef)
This routine installs an asynchronous callback function for the given HandlerType.
HandlerType Callback Function Type ----------------------- -------------------------------------------------- XMCDMA_HANDLER_DONE Channel Done handler XMCDMA_HANDLER_ERROR Channel Error handler Chan is the Channel instance to be worked on HandlerType specifies which callback is to be attached. CallBackFunc is the address of the callback function. CallBackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS when handler is installed.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XMCDMA_CHAN_HANDLER_DONE, XMCDMA_CHAN_HANDLER_ERROR.
void XMcdma_IntrHandler(void *Instance)
This function is the S2MM(RX) interrupt handler for the MCDMA core.
This handler reads the pending interrupt from Status register, determines the source of the interrupts and calls the respective callbacks for the interrupts that are enabled in global control register, and finally clears the interrupts.The application is responsible for connecting this function to the interrupt system. Application beyond this driver is also responsible for providing callbacks to handle interrupts and installing the callbacks using XMcdma_SetCallBack() during initialization phase. Instance is a pointer to the XMcdma instance to be worked on. None. To generate interrupt required interrupts should be enabled.
References XMcdma_ChanAckIrq, XMcdma_ChanGetIrq, XMcdma_GetMcdmaRxChan.
void XMcdma_TxIntrHandler(void *Instance)
This function is the MM2S interrupt handler for the MCDMA core.
This handler reads the pending interrupt from Status register, determines the source of the interrupts and calls the respective callbacks for the interrupts that are enabled in global control register, and finally clears the interrupts.The application is responsible for connecting this function to the interrupt system. Application beyond this driver is also responsible for providing callbacks to handle interrupts and installing the callbacks using XMcdma_SetCallBack() during initialization phase. Instance is a pointer to the XMcdma instance to be worked on. None. To generate interrupt required interrupts should be enabled.
References XMcdma_ChanAckIrq, XMcdma_ChanGetIrq, XMcdma_GetMcdmaTxChan.
s32 XMcdma_SetCallBack(XMcdma *InstancePtr, XMcdma_Handler HandlerType, void *CallBackFunc, void *CallBackRef)
This routine installs an asynchronous callback function for the given HandlerType.
HandlerType Callback Function Type ----------------------- -------------------------------------------------- XMCDMA_TX_HANDLER_DONE MM2S(TX) Done handler XMCDMA_TX_HANDLER_ERROR MM2S(TX) Error handler XMCDMA_HANDLER_DONE S2MM(RX) Done handler XMCDMA_HANDLER_ERROR S2MM(RX) Error handler XMCDMA_HANDLER_PKTDROP S2MM(RX) Packet drop handler InstancePtr is a pointer to the XMcdma instance to be worked on. HandlerType specifies which callback is to be attached. CallBackFunc is the address of the callback function. CallBackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS when handler is installed.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XMCDMA_HANDLER_DONE, XMCDMA_HANDLER_ERROR, XMCDMA_HANDLER_PKTDROP, XMCDMA_TX_HANDLER_DONE, XMCDMA_TX_HANDLER_ERROR.
s32 XMcdma_SelfTest(XMcdma *InstancePtr)
This file contains a diagnostic self-test function for the MCDMA driver.
Refer to the header file xmcdma.h for more detailed information. InstancePtr is a pointer to XMcDma instance. XST_SUCCESS if the test is successful.XST_FAILURE if the test is failed. None.
References XMcDma_Reset, XMcdma_ResetIsDone.
XMcdma_Config* XMcdma_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
A table contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration table entry corresponding to the given device ID/BaseAddress, or NULL if no match is found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
Referenced by main.
XMCDMA_LOOP_COUNT
XMCDMA_NUM_APP_WORDS
XMCDMA_MAX_CHAN_PER_DEVICE
XMCDMA_CHAN_IDLE
XMCDMA_CHAN_PAUSE
XMCDMA_CHAN_BUSY
XMCDMA_BD_MINIMUM_ALIGNMENT
XMCDMA_AXCACHE
XMCDMA_DEV_TO_MEM
XMCDMA_MEM_TO_DEV
XMcdma_DisableCh
Disable Particular Channel in the MCDMA Core.
Chan is the MCDMA Channel to be worked on. ChanId is the channel to disable. C-style signature: XMcdma_DisableCh(XMcdma_ChanCtrl *Chan, u32 ChanId)
XMcdma_GetChan
Get Channel number that last Serviced.
Chan is the MCDMA Channel to be worked on. Channel Number that last serviced. C-style signature: XMcdma_GetChan(XMcdma_ChanCtrl *Chan)
XMcdma_isidle
This function checks whether DMA is Idle or not.
Chan is the MCDMA Channel to be worked on. TRUE if MCDMA is idleFALSE if MCDMA is not idle None
XMcdma_IntrEnable
This function enables interrupts specified by the Mask in specified direction, Interrupts that are not in the mask are not affected.
Chan is the MCDMA Channel to be worked on. Mask is the mask for the interrupts to be enabled None None
XMcdma_IntrDisable
This function disables interrupts specified by the Mask.
Interrupts that are not in the mask are not affected. Chan is the MCDMA Channel to be worked on. Mask is the mask for the interrupts to be disabled None None
XMcdma_GetPktDrp_cnt
Gets global Packet drop Count.
Chan is the MCDMA Channel to be worked on. Packet Drop Count. C-style signature: XMcdma *XMcdma_GetPktDrp_cnt(XMcdma_ChanCtrl *Chan)
XMcdma_GetMcdmaTxChan
Gets the TX Channel Pointer.
InstancePtr is a pointer to the DMA engine instance to be worked on. ChanId is the channel to operate on Pointer to the Channel C-style signature: XMcdma_ChanCtrl *XMcdma_McdmaTxChan(XMcdma * InstancePtr, u32 ChanId)
Referenced by XMcdma_ResetIsDone, XMcdma_TxIntrHandler.
XMcdma_GetMcdmaRxChan
Gets the RX Channel Pointer.
InstancePtr is a pointer to the DMA engine instance to be worked on. ChanId is the channel to operate on Pointer to the Channel C-style signature: XMcdma_ChanCtrl *XMcdma_McdmaRxChan(XMcdma * InstancePtr, u32 ChanId)
Referenced by XMcdma_IntrHandler, XMcdma_ResetIsDone.
XMcdma_GetChanCurBd
Gets the Channel BD Chain Current BD.
Chan is the MCDMA Channel to Operate on. Channel BD Chain current Buffer descriptor. C-style signature: XMdma_ChanCtrl *XMcdma_GetChanCurBd(XMcdma_ChanCtrl * Chan)
XMcdma_GetChanBdDoneCnt
This functions gives the Buffer descriptor count processed by the h/w.
Chan is the MCDMA Channel to Operate on. Buffer descriptor count processed by the h/w. C-style signature: XMdma_ChanCtrl *XMcdma_GetChanBdDoneCnt(XMcdma_ChanCtrl * Chan)
XMcdma_ChanGetIrq
This function gets the interrupts that are asserted.
Chan is the MCDMA Channel to Operate on. The bit mask for the interrupts asserted. None
Referenced by XMcdma_ChanIntrHandler, XMcdma_IntrHandler, XMcdma_TxIntrHandler.
XMcdma_ChanAckIrq
This function acknowledges the interrupts that are specified in Mask.
Chan is the MCDMA Channel to Operate on. Mask is the mask for the interrupts to be acknowledge None None.
Referenced by XMcdma_ChanIntrHandler, XMcdma_IntrHandler, XMcdma_TxIntrHandler.
XMcdma_GetChanPktDrp_Cnt
Get Packet drop Count for the particular Channel.
Chan is the MCDMA Channel to be worked on. ChanId is the Channel number to be worked on. Packet Drop Count. C-style signature: XMcdma *XMcdma_GetChanPktDrp_Cnt(XMcdma_ChanCtrl *Chan, u32 ChanId)
XMcdma_SetARCache
This function sets the ARCACHE field with the user specified value.
InstancePtr is the driver instance we are working on Value is the ARCACHE value to be written. None None.
Referenced by XMcDma_CfgInitialize.
XMcdma_SetAWCache
This function sets the AWCACHE field with the user specified value.
InstancePtr is the driver instance we are working on Value is the AWCACHE value to be written. None None.
Referenced by XMcDma_CfgInitialize.
XMcdma_GetEgressObserver
Get Egress Channel Observer contents.
InstancePtr is the driver instance we are working on. ObsId is the Egress Channel observer number to be worked on. Channel Observer register contents. C-style signature: XMcdma *XMcdma_GetEgressObserver(XMcdma *InstancePtr, u32 ObsId)
XMcdma_GetIngressObserver
Get Ingress Channel Observer contents.
InstancePtr is the driver instance we are working on. ObsId is the Ingress Channel observer number to be worked on. Channel Observer register contents. C-style signature: XMcdma *XMcdma_GetIngressObserver(XMcdma *InstancePtr, u32 ObsId)
MAX_TRANSFER_LEN
WRR_MASK
XMCDMA_CHAN_SEEKAHEAD
XMCDMA_CACHE_FLUSH
XMCDMA_CACHE_INVALIDATE
XMcdma_BdRead
Read the given Buffer Descriptor word.
BaseAddress is the base address of the BD to read Offset is the word offset to be read The 32-bit value of the field C-style signature: u32 XMcdma_BdRead(u32 BaseAddress, u32 Offset)
Referenced by XMcdma_BdChainFromHW, XMcDma_BdGetAppWord, XMcDma_BdSetAppWord, XMcdma_BdSetBufAddr, XMcDma_BdSetCtrl, XMcDma_DumpBd.
XMcdma_BdRead64
Read the given Buffer Descriptor word.
BaseAddress is the base address of the BD to read Offset is the word offset to be read The 64-bit value of the field C-style signature: u64 XMcdma_BdRead64(u64 BaseAddress, u32 Offset)
XMcdma_BdWrite
Write the given Buffer Descriptor word.
BaseAddress is the base address of the BD to write Offset is the word offset to be written Data is the 32-bit value to write to the field None. C-style signature: void XMcdma_BdWrite(u32 BaseAddress, u32 RegOffset, u32 Data)
Referenced by XMcDma_BdSetAppWord, XMcdma_BdSetBufAddr, XMcDma_BdSetCtrl, XMcDma_Chan_Sideband_Submit, XMcDma_ChanBdCreate, XMcDma_ChanSubmit.
XMcdma_BdWrite64
Write the given Buffer Descriptor double word.
BaseAddress is the base address of the BD to write Offset is the word offset to be written Data is the 64-bit value to write to the field None. C-style signature: void XMcdma_BdWrite(u64 BaseAddress, u32 RegOffset, u64 Data)
Referenced by XMcdma_BdSetBufAddr.
XMcDma_BdGetSts
Retrieve the status of a Ingress(S2MM) BD.
BdPtr is the BD to operate on Use XMDMA_BD_STS_*** values defined in xmdma_hw.h to interpret the returned value C-style signature: u32 XMcDma_BdGetSts(XMcdma_Bd* BdPtr)
XMcdma_BdHwCompleted
Check whether a Ingress(S2MM) BD has completed in hardware.
This BD has been submitted to hardware. The application can use this function To poll for the Completion of the BD.This function may not work if the BD is in cached memory. BdPtr is the BD to check on 0 if not completeXMCDMA_BD_STS_COMPLETE_MASK if completed, may contain XMDMA_BD_STS_*_ERR_MASK bits. C-style signature: int XMcdma_BdHwCompleted(XMcdma_Bd* BdPtr)
XMcDma_BdGetActualLength
Get the actual transfer length of a Ingress (S2MM)BD.
The BD has completed in hw.This function may not work if the BD is in cached memory. BdPtr is the BD to check on LengthMask is the Maximum Transfer Length. None C-style signature: int XMcDma_BdGetActualLength(XMcdma_Bd* BdPtr, u32 LengthMask)
XMcDma_TxBdGetSts
Retrieve the status of a Egress(MM2S) BD.
BdPtr is the BD to operate on Use XMDMA_BD_STS_*** values defined in xmdma_hw.h to interpret the returned value C-style signature: u32 XMcDma_TxBdGetSts(XMcdma_Bd* BdPtr)
XMcdma_TxBdHwCompleted
Check whether a Egress(MM2S) BD has completed in hardware.
This BD has been submitted to hardware. The application can use this function To poll for the Completion of the BD.This function may not work if the BD is in cached memory. BdPtr is the BD to check on 0 if not completeXMCDMA_BD_STS_COMPLETE_MASK if completed, may contain XMDMA_BD_STS_*_ERR_MASK bits. C-style signature: int XMcdma_TxBdHwCompleted(XMcdma_Bd* BdPtr)
XMcDma_TxBdGetActualLength
Get the actual transfer length of a Egress(MM2S) BD.
The BD has completed in hw.This function may not work if the BD is in cached memory. BdPtr is the BD to check on LengthMask is the Maximum Transfer Length. None C-style signature: int XMcDma_TxBdGetActualLength(XMcdma_Bd* BdPtr, u32 LengthMask)
XMcDma_BdGetCtrl
Gets the control bits of a BD.
BdPtr is the BD to operate on control bits of a BD. C-style signature: u32 XMcDma_BdGetCtrl(XMCDMA_Bd* BdPtr)
XMcdma_BdChainNextBd
Return the next BD in the Chain.
Chan is the Channel BD Chain to operate on. BdPtr is the current BD. The next BD in the Chain relative to the BdPtr parameter. C-style signature: XMcdma_Bd XMcdma_BdChainNextBd(XMcdma_ChanCtrl Chan, XMcdma_Bd *BdPtr)
Referenced by XMcdma_BdChainFree, XMcdma_BdChainFromHW, XMcDma_Chan_Sideband_Submit, XMcDma_ChanSubmit.
XMcdma_BdChainPrevBd
Return the previous BD in the Chain.
Chan is the MCDMA channel to operate on. BdPtr is the current BD. The previous BD in the Chain relative to the BdPtr parameter. C-style signature: XMcdma_Bd XMcdma_BdChainPrevBd(XMcdma_ChanCtrl Chan, XMcdma_Bd *BdPtr)
XMcdma_HwIsStarted
Check whether a DMA is started, meaning the channel is not halted.
Chan is the channel instance to operate on. 1 if channel is started0 otherwise C-style signature: int XMcdma_ChanHwIsStarted(XMcdma_ChanCtrl *Chan)
Referenced by XMcdma_UpdateChanTDesc.
XMcdma_ChanHwIsStarted
Check whether a DMA channel is started, meaning the channel is not halted.
Chan is the channel instance to operate on. Chan_id is the channel number to operate on. 1 if channel is started0 otherwise C-style signature: int XMcdma_ChanHwIsStarted(XMcdma_ChanCtrl *Chan, u32 Chan_id)
Referenced by XMcdma_UpdateChanTDesc.
XMcDma_BdSetCtrlSideBand
Set the Tid and Tuser fields of a BD with the user provided values.
BdPtr is the BD to operate on. Tid is Tid value to be written in the Bd field. Tuser is Tuser value to be written in the Bd field. C-style signature: u32 XMcDma_BdSetCtrlSideBand(XMcdma_Bd* BdPtr, u8 Tid, u8 Tuser)
Referenced by XMcDma_Chan_Sideband_Submit.
XMcDma_GetBdSbandStats
Retrieve the side band status of a BD.
BdPtr is the BD to operate on Use XMDMA_BD_STS_*** values defined in xmdma_hw.h to interpret the returned value C-style signature: u32 XMcDma_GetBdSbandStats(XMcdma_Bd* BdPtr)
XMcdma_BdClear
Clears the BD Contents.
BdPtr is the BD to operate on C-style signature: void XMcdma_BdClear(XMcdma_Bd* BdPtr)
Referenced by XMcdma_BdChainFree, XMcDma_Chan_Sideband_Submit, XMcDma_ChanSubmit.
XMcdma_BdSetSwId
Set the Sw ID field of the given BD.
The ID is an arbitrary piece of data the application can associate with a specific BD. BdPtr is the BD to operate on Id is a 32 bit quantity to set in the BD None C-style signature: void XMcdma_BdSetSwId(XMcdma_Bd* BdPtr, void Id)
XMcdma_BdGetSwId
Retrieve the Sw ID field of the given BD previously set with XMcdma_BdSetSwId.
BdPtr is the BD to operate on BD Sw identifier C-style signature: u32 XMcdma_BdGetSwId(XMcdma_Bd* BdPtr)