xmcdma.c
s32 XMcDma_CfgInitialize(XMcdma *InstancePtr, XMcdma_Config *CfgPtr)
This function initializes an MCDMA core.
This function must be called prior to using an MCDMA core. Initialization of an MCDMA includes setting up the instance data and ensuring the hardware is in a quiescent state and resets all the hardware configurations. InstancePtr is a pointer to the XMcdma instance. CfgPtr is a reference to a structure containing information about a specific XMcdma instance. XST_SUCCESS if initialization was successful. None.
References XMcDma_Initialize, XMcDma_Reset, XMcdma_ResetIsDone, XMcdma_SetARCache, XMcdma_SetAWCache.
Referenced by main.
s32 XMcDma_Initialize(XMcdma *InstancePtr, XMcdma_Config *CfgPtr)
This function initializes an MCDMA core.
This function must be called prior to using an MCDMA core. Initialization of an MCDMA includes setting up the instance data and updating the driver filed with a proper values. InstancePtr is a pointer to the XMcdma instance. CfgPtr is a reference to a structure containing information about a specific XMcdma instance. XST_SUCCESS if initialization was successful. When user calls this function he should ensure the hardware is in a quiescent state by resetting all the hardware Configurations.
Referenced by XMcDma_CfgInitialize.
void XMcDma_Reset(XMcdma *InstancePtr)
This function resets the MCDMA core.
InstancePtr is a pointer to the XMcdma instance. None. This function resets all the configurations made previously.
Referenced by XMcDma_CfgInitialize, XMcdma_SelfTest.
void XMcdma_SetSGAWCache(XMcdma *InstancePtr, u8 Value)
This function sets the AWCACHE field of the SG interface With the user specified value.
InstancePtr is the driver instance we are working on Value is the AWCACHE value to be written. None None.
void XMcdma_SetSGARCache(XMcdma *InstancePtr, u8 Value)
This function sets the ARCACHE field of the SG interface With the user specified value.
InstancePtr is the driver instance we are working on Value is the ARCACHE value to be written. None None.
u32 XMcdma_ResetIsDone(XMcdma *InstancePtr)
Check whether reset is done.
InstancePtr is a pointer to the DMA engine instance to be worked on. 1 if reset is done. 0 if reset is not done None
References XMcdma_GetMcdmaRxChan, XMcdma_GetMcdmaTxChan.
Referenced by XMcDma_CfgInitialize, XMcdma_SelfTest.
u32 XMcdma_Start(XMcdma_ChanCtrl *Chan)
Start the DMA engine.
Chan is the Channel instance to be worked on XST_SUCCESS for success.XST_FAILURE if starting the hardware fails. None
Referenced by XMcdma_UpdateChanTDesc.
u32 XMcdma_ChanHwStop(XMcdma_ChanCtrl *Chan)
Stops the DMA engine.
Chan is the Channel instance to be worked on XST_SUCCESS for success.XST_FAILURE if hardware fails stop. None
void XMcdma_EnableCh(XMcdma_ChanCtrl *Chan)
Enables a particular channel.
Chan is the Channel instance to be worked on none None
Referenced by XMcDma_ChanToHw.
u16 XMcdma_GetChanServiced(XMcdma *InstancePtr)
Gets the last serviced s2mm channel number.
InstancePtr is a pointer to the DMA engine instance to be worked on. Channel id that last serviced. None
u16 XMcdma_GetTxChanServiced(XMcdma *InstancePtr)
Gets the last serviced mm2s channel number.
InstancePtr is a pointer to the DMA engine instance to be worked on. Channel id that last serviced. None
u32 XMCdma_GetChan_Weight(XMcdma_ChanCtrl *Chan)
u32 XMCdma_SetChan_Weight(XMcdma_ChanCtrl *Chan, u8 Weight)
u32 XMCdma_GetChan_PktDoneCnt(XMcdma_ChanCtrl *Chan)
void XMcdma_DumpChanRegs(XMcdma_ChanCtrl *Chan)
Dump the registers for a channel.
Chan is the MCDMA Channel to be worked on. None