xmcdma_bd.c
XMCDMA_CHAN_SEEKAHEAD
int XMcdma_UpdateChanCDesc(XMcdma_ChanCtrl *Chan)
Update Current Descriptor for the MCDMA Channel.
Chan is the Channel instance to be worked on XST_SUCCESS upon success None.
Referenced by XMcDma_ChanToHw.
int XMcdma_UpdateChanTDesc(XMcdma_ChanCtrl *Chan)
Update Tail Desc for the Channel.
Chan is the MCDMA Channel to be worked on. XST_SUCCESS upon successXST_DMA_ERROR if no valid BD available to put into current BD register
References XMcdma_ChanHwIsStarted, XMcdma_HwIsStarted, XMcdma_Start.
Referenced by XMcDma_ChanToHw.
u32 XMcDma_ChanBdCreate(XMcdma_ChanCtrl *Chan, UINTPTR Addr, u32 Count)
Using a memory segment allocated by the caller, This function creates and setup the BD Chain for the MCDMA Channel.
Chan is the MCDMA Channel to be worked on.. Addr is the address of the application memory region. Count is the number of BDs to setup in the application memory region. XST_SUCCESS if initialization was successfulXST_INVALID_PARAM if Count is not positive.
References XMcdma_BdWrite.
u32 XMcDma_ChanSubmit(XMcdma_ChanCtrl *Chan, UINTPTR BufAddr, u32 len)
This function Populates the BD Chain with the required buffer address and length fields.
User can submit multiple buffers/buffer descriptors by calling this function multiple times Chan is the MCDMA Channel to be worked on.. BufAddr is the buffer address to which data should send/recv. len is the Amount of data user requested to send/recv. XST_SUCCESS if initialization was successfulXST_FAILURE if the BdStartAddress or requested bdlen doesn't match for the driver requirements.
References XMcdma_BdChainNextBd, XMcdma_BdClear, XMcdma_BdSetBufAddr, XMcdma_BdWrite.
u32 XMcDma_Chan_Sideband_Submit(XMcdma_ChanCtrl *ChanPtr, UINTPTR BufAddr, u32 Len, u32 *AppPtr, u16 Tuser, u16 Tid)
This function populates the BD Chain with the required buffer address, length APP(user application), TUSER and TID fields.
User can submit multiple buffers/buffer descriptors by calling this function multiple times ChanPtr is the MCDMA Channel to be worked on.. BufAddr is the buffer address to which data should send/recv. Len is the Amount of data user requested to send/recv. AppPtr is the point to APP fields. Tuser is the value presented on the beat that has TLAST. Tid is the value value presented on the beat that has TLAST. XST_SUCCESS if initialization was successfulXST_FAILURE if the BdStartAddress or requested bdlen doesn't match for the driver requirements.
References XMcdma_BdChainNextBd, XMcdma_BdClear, XMcdma_BdSetBufAddr, XMcDma_BdSetCtrlSideBand, XMcdma_BdWrite.
u32 XMcDma_ChanToHw(XMcdma_ChanCtrl *Chan)
This function triggers/Starts the h/w by programming the Current and Tail Descriptors and enabling the particular channel.
Chan is the MCDMA Channel to be worked on.. XST_SUCCESS if initialization was successfulXST_FAILURE In case of failure
References XMcdma_EnableCh, XMcdma_UpdateChanCDesc, XMcdma_UpdateChanTDesc.
int XMcdma_BdChainFromHW(XMcdma_ChanCtrl *Chan, u32 BdLimit, XMcdma_Bd **BdSetPtr)
Returns a set of BD(s) that have been processed by hardware.
The returned BDs may be examined by the application to determine the outcome of the DMA transactions. Once the BDs have been examined, the application must call XMcdma_BdChainFree() in the same order which they were retrieved here.If hardware has partially completed a packet spanning multiple BDs, then none of the BDs for that packet will be included in the results. Chan is the MCDMA Channel to be worked on.. BdLimit is the maximum number of BDs to return in the set. BdSetPtr is an output parameter, it points to the first BD available for examination. The number of BDs processed by hardware. A value of 0 indicates that no data is available. No more than BdLimit BDs will be returned. Treat BDs returned by this function as read-only.
References XMcdma_BdChainNextBd, XMcdma_BdRead.
int XMcdma_BdChainFree(XMcdma_ChanCtrl *Chan, int BdCount, XMcdma_Bd *BdSetPtr)
Frees a set of BDs that had been previously retrieved with XMcdma_BdChainFromHW().
Chan is the MCDMA Channel to be worked on.. BdCount is the number of BDs to free. BdSetPtr is the head of a list of BDs returned by XMcdma_BdChainFromHW(). XST_SUCCESS if the set of BDs was freed.XST_INVALID_PARAM if NumBd is negative This function should not be preempted by another XAxiMcDma function call that modifies the BD space. It is the caller's responsibility to ensure mutual exclusion.
References XMcdma_BdChainNextBd, XMcdma_BdClear.
u32 XMcdma_BdSetBufAddr(XMcdma_Bd *BdPtr, UINTPTR Addr)
Set the Buffer descriptor buffer address field.
BdPtr is the BD to operate on Addr is the address to set XST_SUCCESS if buffer address set successfullyXST_INVALID_PARAM if hardware has no DRE and address is not aligned
References XMcdma_BdRead, XMcdma_BdWrite, XMcdma_BdWrite64.
Referenced by XMcDma_Chan_Sideband_Submit, XMcDma_ChanSubmit.
void XMcDma_BdSetCtrl(XMcdma_Bd *BdPtr, u32 Data)
Set the control bits for a BD.
BdPtr is the BD to operate on. Data is the bit value to set None None
References XMcdma_BdRead, XMcdma_BdWrite.
int XMcDma_BdSetAppWord(XMcdma_Bd *BdPtr, int Offset, u32 Word)
Set the APP word at the specified APP word offset for a BD.
BdPtr is the BD to operate on Offset is the offset inside the APP word, it is valid from 0 to 4 Word is the value to set XST_SUCCESS for successXST_INVALID_PARAM under following error conditions. 1) StsCntrlStrm is not built in hardware 2) Offset is not in valid range
References XMcdma_BdRead, XMcdma_BdWrite.
u32 XMcDma_BdGetAppWord(XMcdma_Bd *BdPtr, int Offset, int *Valid)
Get the APP word at the specified APP word offset for a BD.
BdPtr is the BD to operate on. Offset is the offset inside the APP word, it is valid from 0 to 4 Valid is to tell the caller whether parameters are valid The APP word. Passed in parameter Valid holds 0 for failure, and 1 for success.
References XMcdma_BdRead.
u32 XMcdma_SetChanCoalesceDelay(XMcdma_ChanCtrl *Chan, u32 IrqCoalesce, u32 IrqDelay)
Set interrupt coalescing parameters for a particular channel.
Chan is the MCDMA Channel to be worked on.. IrqCoalesce is the Irq Threshold value valid ranges are 1 to 255 IrqDelay is the Irq Delay value valid ranges are 1 to 255 XST_SUCCESS if Interrupt Coalescing settings updatedXST_FAILURE if IrqCoalesce and IrqDelay parameters are out of range
void XMcDma_DumpBd(XMcdma_Bd *BdPtr)
Dump the fields of a BD.
BdPtr is the BD to operate on. None
References XMcdma_BdRead.