bigdigits.c
DPRINTF0
DPRINTF1
max
BITS_PER_HALF_DIGIT
BYTES_PER_DIGIT
LOHALF
HIHALF
TOHIGH
mpNEXTBITMASK
MAX_ALLOC_SIZE
ALLOC_BYTES
FREE_BYTES
B
IS_NONZERO_DIGIT
IS_ZER0_DIGIT
N_SMALL_PRIMES
mpMODSQUARETEMP
mpMODMULTTEMP
mpMODMULTXYTEMP
const int kMajor
const int kMinor
const int kRelease
const int kUseSpasm
const int kUse64with32
const int kUseNoAllocs
u32 SMALL_PRIMES[][]
void mpFail(char *msg)
uint8_t zeroise_bytes(volatile void *v, size_t n)
volatile const char* copyright_notice(void)
int mpVersion(void)
Returns version number = major*1000+minor*100+release*10+PP_OPTIONS.
Returns version number = major*1000+minor*100+release*10+PP_OPTIONSVersion number encoded as integer Version number = major*1000+minor*100+release*10+uses_asm(0|1)+uses_64(0|2)+uses_noalloc(0|5) E.g. Version 2.3.0 will return 230x where x denotes the preprocessor options x | USE_SPASM | USE_64WITH32 | NO_ALLOCS 0 No No No 1 Yes No No 2 No Yes No 3 Yes Yes* No 5 No No Yes 6 Yes No Yes 7 No Yes Yes 8 Yes Yes* Yes USE_SPASM will take precedence over USE_64WITH32.
int spMultiply(u32 p[2], u32 x, u32 y)
Computes product of two single digits: p = x * y.
p Output array to store the product (size: 2) x First single digit multiplicand y Second single digit multiplicand Status code indicating success or failure
Referenced by mpMultiply, mpSquare, mpShortMult.
static void spMultSub(u32 uu[2], u32 qhat, u32 v1, u32 v0)
u32 spDivide(u32 *q, u32 *r, const u32 u[2], u32 v)
Computes quotient and remainder: q = u / v, r = u % v.
q Output pointer to store the quotient (single digit) r Output pointer to store the remainder (single digit) u Input dividend array (size: 2) v Single digit divisor The quotient value
Referenced by mpDivide, mpShortDiv.
u32 mpAdd(u32 w[], const u32 u[], const u32 v[], size_t ndigits)
Computes w = u + v, returns carry.
Add two multi-precision integers. w Output array to store the sum u First input multi-precision integer v Second input multi-precision integer ndigits Number of digits in the integers Carry value from the addition
Referenced by mpDivide, mpModInv, mpSqrt, mpCubeRoot.
u32 mpSubtract(u32 w[], const u32 u[], const u32 v[], size_t ndigits)
Computes w = u - v, returns borrow.
Subtract two multi-precision integers. w Output array to store the result (u - v) u First input array (minuend) v Second input array (subtrahend) ndigits Number of digits in the arrays Borrow value (0 if no borrow, non-zero otherwise)
Referenced by mpModInv, mpGcd.
int mpMultiply(u32 w[], const u32 u[], const u32 v[], size_t ndigits)
Computes w = u * v.
Multiply two multi-precision integers. w Output array to store the result (u - v) u First input array (minuend) v Second input array (subtrahend) ndigits Number of digits in the arrays Borrow value (0 if no borrow, non-zero otherwise
References spMultiply.
Referenced by mpModMult, mpModInv.
static u32 mpMultSub(u32 wn, u32 w[], const u32 v[], u32 q, size_t n)
static int QhatTooBig(u32 qhat, u32 rhat, u32 vn2, u32 ujn2)
int mpDivide(u32 q[], u32 r[], const u32 u[], size_t udigits, u32 v[], size_t vdigits)
Performs integer division: u = q*v + r.
q Output quotient array (size: udigits) r Output remainder array (size: udigits) u Input dividend array (size: udigits) udigits Size of q, r, and u arrays v Input divisor array (size: vdigits) vdigits Size of v array 0 if successful q and r are overwritten without preservation
References mpSetZero, mpSizeof, mpShortDiv, mpSetEqual, mpCompare, mpSetDigit, mpShiftLeft, spDivide, mpAdd, mpShiftRight.
Referenced by mpModulo, mpModInv, mpSqrt, mpCubeRoot.
int mpSquare(u32 w[], const u32 x[], size_t ndigits)
Computes the square of a big digit number.
w Output array to store the result (size: 2 * ndigits) x Input array to be squared (size: ndigits) ndigits Number of digits in input array Overflow value from the squaring operation
References spMultiply.
int mpEqual_q(const u32 a[], const u32 b[], size_t ndigits)
Returns true if a == b, else false.
Returns true if a == b, else false (quick)Not constant-time.
int mpCompare_q(const u32 a[], const u32 b[], size_t ndigits)
Returns sign of (a - b) as 0, +1 or -1.
Returns sign of (a-b) as {-1,0,+1} (quick)Not constant-time.
int mpIsZero_q(const u32 a[], size_t ndigits)
Returns true if a == 0, else false.
Checks if a multi-precision integer is zero (quick version).Not constant-time.
int mpEqual(const u32 a[], const u32 b[], size_t ndigits)
Returns 1 if a == b, else 0 (constant-time)
Returns true if a == b, else false, using constant-time algorithm.
int mpIsZero(const u32 a[], size_t ndigits)
Returns 1 if a == 0, else 0 (constant-time)
Returns true if a is zero, else false, using constant-time algorithm.
Referenced by mpModInv, mpGcd, mpJacobi, mpRabinMiller.
int mpCompare(const u32 a[], const u32 b[], size_t ndigits)
Returns sign of (a - b) as 0, +1 or -1 (constant-time)
Returns sign of (a-b) as {-1,0,+1} using constant-time algorithm.
Referenced by mpDivide, mpGcd, mpSqrt, mpCubeRoot, mpRabinMiller.
size_t mpSizeof(const u32 a[], size_t ndigits)
Returns number of significant digits in a.
Returns number of significant non-zero digits in a.
Referenced by mpDivide, mpBitLength, mpRabinMiller, mpModExp_ct.
size_t mpBitLength(const u32 d[], size_t ndigits)
Returns number of significant bits in a.
Returns number of significant bits in a a Multi-precision integer array ndigits Number of digits in the array Number of significant bits
References mpSizeof.
Referenced by mpConvToOctets.
void mpSetEqual(u32 a[], const u32 b[], size_t ndigits)
Copies one multi-precision integer to another.
a Destination array b Source array to copy from ndigits Number of digits to copy
Referenced by mpDivide, mpAbs, mpModulo, mpModInv, mpGcd, mpSqrt, mpCubeRoot, mpJacobi, mpRabinMiller, mpModExp_ct.
u32 mpSetZero(u32 a[], size_t ndigits)
Sets a multi-precision integer to zero.
a Array to set to zero ndigits Number of digits in array Always returns 0
Referenced by mpDivide, mpConvFromOctets, mpModInv, mpRabinMiller, mpQuickRandBits.
void mpSetDigit(u32 a[], u32 d, size_t ndigits)
Sets a multi-precision integer to a single digit value.
a Array to set d Single digit value to assign ndigits Number of digits in array
Referenced by mpDivide, mpModInv, mpModExp_ct.
u32 mpShiftLeft(u32 a[], const u32 *b, size_t shift, size_t ndigits)
u32 mpShiftRight(u32 a[], const u32 b[], size_t shift, size_t ndigits)
Computes a = b >> x (shift right)
a Output array for result b Input array to shift x Number of bits to shift right ndigits Number of digits in arrays Underflow bits
Referenced by mpDivide, mpGcd, mpSqrt, mpJacobi, mpRabinMiller.
int mpSetBit(u32 a[], size_t ndigits, size_t ibit, int value)
Sets bit n of a with specified value.
a Array to modify ndigits Number of digits in array n Bit position (0..nbits-1) value Bit value (1 or 0) Status code
int mpGetBit(u32 a[], size_t ndigits, size_t ibit)
Returns value of bit n.
a Array to read from ndigits Number of digits in array n Bit position (0..nbits-1) Bit value (1 or 0)
void mpModPowerOf2(u32 a[], size_t ndigits, size_t L)
Computes a = a mod 2^L (clears all bits greater than L)
a Array to modify ndigits Number of digits in array L Bit position threshold
void mpXorBits(u32 a[], const u32 b[], const u32 c[], size_t ndigits)
Computes bitwise a = b XOR c.
a Output array for result b First input array c Second input array ndigits Number of digits in arrays
void mpOrBits(u32 a[], const u32 b[], const u32 c[], size_t ndigits)
Computes bitwise a = b OR c.
a Output array for result b First input array c Second input array ndigits Number of digits in arrays
void mpAndBits(u32 a[], const u32 b[], const u32 c[], size_t ndigits)
Computes bitwise a = b AND c.
a Output array for result b First input array c Second input array ndigits Number of digits in arrays
void mpNotBits(u32 a[], const u32 b[], size_t ndigits)
Computes bitwise a = NOT b.
a Output array for result b Input array ndigits Number of digits in arrays
Referenced by mpChs.
u32 mpShortAdd(u32 w[], const u32 u[], u32 v, size_t ndigits)
Computes w = u + d.
w Output array for result u Input multi-precision integer array d Single digit to add ndigits Number of digits in arrays Carry value from the addition
Referenced by mpChs, mpRabinMiller.
u32 mpShortSub(u32 w[], const u32 u[], u32 v, size_t ndigits)
Computes w = u - d.
w Output array for result u Input multi-precision integer array d Single digit to subtract ndigits Number of digits in arrays Borrow value from the subtraction
Referenced by mpChs, mpRabinMiller.
u32 mpShortMult(u32 w[], const u32 u[], u32 v, size_t ndigits)
Computes product p = x * d.
p Output array for result x Input multi-precision integer array d Single digit multiplier ndigits Number of digits in arrays Overflow from multiplication
References spMultiply.
u32 mpShortDiv(u32 q[], const u32 u[], u32 v, size_t ndigits)
Computes quotient q = u / d.
q Output array for quotient u Input multi-precision integer array (dividend) d Single digit divisor ndigits Number of digits in arrays Remainder from the division
References mpShiftLeft, spDivide.
Referenced by mpDivide, mpShortMod, mpCubeRoot.
u32 mpShortMod(const u32 a[], u32 d, size_t ndigits)
Computes remainder r = a mod d.
a Input multi-precision integer array d Single digit modulus ndigits Number of digits in array Remainder value
References mpShortDiv.
Referenced by mpJacobi, mpIsPrime.
int mpShortCmp(const u32 a[], u32 d, size_t ndigits)
Returns sign of (a - d) where d is a single digit.
Compares multi-precision integer with single digit.
Referenced by mpModInv, mpSqrt, mpCubeRoot, mpJacobi, mpIsPrime, mpRabinMiller.
int mpIsNegative(const u32 x[], size_t ndigits)
Returns TRUE (1) if x < 0, else FALSE (0)
Returns true (1) if x < 0, else false (0)
Referenced by mpChs, mpAbs.
int mpChs(u32 x[], const u32 y[], size_t ndigits)
Sets x = -y.
Sets x = -y (negation)
References mpIsNegative, mpShortSub, mpNotBits, mpShortAdd.
Referenced by mpAbs.
int mpAbs(u32 x[], const u32 y[], size_t ndigits)
Sets x = |y|.
Sets x = |y|, the absolute value of y.
References mpIsNegative, mpChs, mpSetEqual.
void mpPrint(const u32 *p, size_t len)
Print all digits in hexadecimal including leading zeros.
p Multi-precision integer array to print ndigits Number of digits in the array
Referenced by mpPrintTrim.
void mpPrintNL(const u32 *p, size_t len)
Print all digits in hexadecimal with newlines.
p Multi-precision integer array to print ndigits Number of digits in the array
Referenced by mpPrintTrimNL.
void mpPrintTrim(const u32 *p, size_t len)
Print in hexadecimal but trim leading zero digits.
p Multi-precision integer array to print ndigits Number of digits in the array DeprecatedUse mpPrintHex()
References mpPrint.
void mpPrintTrimNL(const u32 *p, size_t len)
Print in hexadecimal, trim leading zeros, and add newlines.
p Multi-precision integer array to print ndigits Number of digits in the array DeprecatedUse mpPrintHex()
References mpPrintNL.
void mpPrintHex(const char *prefix, const u32 *p, size_t len, const char *suffix)
Print multi-precision integer in hexadecimal format.
prefix String to print before the number (can be NULL) p Multi-precision integer array to print ndigits Number of digits in the array suffix String to print after the number (can be NULL)
size_t mpConvFromOctets(u32 a[], size_t ndigits, const unsigned char *c, size_t nbytes)
Converts array of octets to multi-precision integer.
a Output array to store the converted number ndigits Maximum size of output array c Input array of octets (bytes) in big-endian order nbytes Number of bytes in the input array Actual number of digits set in output array
References mpSetZero.
size_t mpConvToOctets(const u32 a[], size_t ndigits, unsigned char *c, size_t nbytes)
Converts multi-precision integer to array of octets.
a Input multi-precision integer array ndigits Number of digits in input array c Output array to store octets (bytes) in big-endian order nbytes Size of output array (will pad or truncate as needed) Number of non-zero octets required
References mpBitLength.
int mpModulo(u32 r[], const u32 u[], size_t udigits, u32 v[], size_t vdigits)
Computes remainder r = u mod v.
r Output remainder array (size: vdigits) u Input dividend array (size: udigits) udigits Size of u array v Input divisor array (size: vdigits) vdigits Size of r and v arrays 0 if successful
References mpDivide, mpSetEqual.
Referenced by mpModMult, mpGcd, mpJacobi.
int mpModMult(u32 a[], const u32 x[], const u32 y[], u32 m[], size_t ndigits)
Computes modular multiplication a = (x * y) mod m.
a Output array to store the result x First input array y Second input array m Modulus array ndigits Number of digits in the arrays Status code indicating success or failure
References mpMultiply, mpModulo.
Referenced by mpRabinMiller.
int mpModInv(u32 inv[], const u32 u[], const u32 v[], size_t ndigits)
Computes the modular multiplicative inverse inv = u^{-1} mod m.
inv Output array to store the inverse u Input array to invert m Modulus array ndigits Number of digits in the arrays Status code indicating success or failure
References mpSetDigit, mpSetEqual, mpSetZero, mpIsZero, mpDivide, mpMultiply, mpAdd, mpSubtract, mpShortCmp.
int mpGcd(u32 d[], const u32 aa[], const u32 bb[], size_t ndigits)
Computes the greatest common divisor g = gcd(x, y)
g Output array to store the GCD x First input array y Second input array ndigits Number of digits in the arrays Status code indicating success or failure
References mpSetEqual, mpCompare, mpIsZero, mpModulo, mpShiftRight, mpSubtract, mpShiftLeft.
int mpSqrt(u32 s[], const u32 n[], size_t ndigits)
Computes integer square root s = floor(sqrt(x))
Computes the square root of a multi-precision integer. s Output array to store the square root result x Input array containing the value to compute square root of ndigits Number of digits in the multi-precision integer Status code indicating success or failure
References mpShortCmp, mpSetEqual, mpDivide, mpAdd, mpShiftRight, mpCompare.
int mpCubeRoot(u32 s[], const u32 n[], size_t ndigits)
Computes integer cube root s = floor(cuberoot(x))
Computes the cube root of a multi-precision integer. s Output array to store the cube root result x Input array containing the value to compute cube root of ndigits Number of digits in the multi-precision integer Status code indicating success or failure
References mpShortCmp, mpSetEqual, mpDivide, mpAdd, mpShortDiv, mpCompare.
int mpJacobi(const u32 a[], const u32 n[], size_t ndigits)
Computes the Jacobi symbol (a/n)
a Input array (numerator) n Input array (denominator, must be odd) ndigits Number of digits in the arrays Jacobi symbol value: -1, 0, or +1 If n is prime then the Jacobi symbol becomes the Legendre symbol (a/p) defined to be (a/p) = +1 if a is a quadratic residue modulo p(a/p) = -1 if a is a quadratic non-residue modulo p(a/p) = 0 if a is divisible by p
References mpIsZero, mpShortCmp, mpSetEqual, mpShiftRight, mpShortMod, mpModulo.
int mpIsPrime(u32 w[], size_t ndigits, size_t t)
Returns true (1) if w is probably prime.
w Number to test ndigits Size of array w t The count of Rabin-Miller primality tests to carry out (recommended at least 80) True (1) if w is probably prime otherwise false (0) Uses FIPS-186-2/Rabin-Miller with trial division by small primes, which is faster in most cases than mpRabinMiller(). mpRabinMiller()
References mpShortCmp, mpShortMod, mpRabinMiller.
static void rand_seed(void)
static u32 rand_between(u32 lower, u32 upper)
int mpRabinMiller(u32 w[], size_t ndigits, size_t t)
Returns true (1) if w is probably prime using just the Rabin-Miller test.
w Number to test ndigits Size of array w t The count of Rabin-Miller primality tests to carry out True (1) if w is probably prime otherwise false (0) mpIsPrime() is preferred
References mpShortCmp, mpShortSub, mpSetEqual, mpSetZero, mpShortAdd, mpShiftRight, mpSizeof, mpCompare, mpModExp, mpIsZero, mpModMult.
Referenced by mpIsPrime.
size_t mpQuickRandBits(u32 a[], size_t ndigits, size_t nbits)
Generate a quick-and-dirty random mp number a <= 2^{nbits}-1 using plain-old-rand.
Generate a quick-and-dirty random mp number a of bit length at most nbits using plain-old-rand.
References mpSetZero, spSimpleRand.
u32 spSimpleRand(u32 lower, u32 upper)
Returns a simple pseudo-random digit between lower and upper.
Not crypto secure. spBetterRand() Returns a simple pseudo-random digit between lower and upper lower Lower bound (inclusive) upper Upper bound (inclusive) Random digit value between lower and upper Not crypto secure. spBetterRand()
Referenced by mpQuickRandBits.
static int mpModExp_1(u32 y[], const u32 x[], const u32 n[], u32 d[], size_t ndigits)
int mpModExp(u32 y[], const u32 x[], const u32 n[], u32 d[], size_t ndigits)
Computes modular exponentiation y = x^e mod m.
y Output array to store the result x Base array e Exponent array m Modulus array ndigits Number of digits in the arrays Status code indicating success or failure
Referenced by mpRabinMiller.
int mpModExp_ct(u32 yout[], const u32 x[], const u32 e[], u32 m[], size_t ndigits)
Computes y = x^e mod m in constant time using Coron's algorithm.
Computes modular exponentiation y = x^e mod m in constant time.
References mpSizeof, mpSetDigit, mpSetEqual.