bigdigits.h
NO_ALLOCS
typedef uint32_t DIGIT_T
The basic BigDigit element, an unsigned 32-bit integer.
u32 mpAdd(u32 w[], const u32 u[], const u32 v[], size_t ndigits)
Computes w = u + v, returns carry.
Add two multi-precision integers. w Output array to store the sum u First input multi-precision integer v Second input multi-precision integer ndigits Number of digits in the integers Carry value from the addition
Referenced by mpCubeRoot, mpDivide, mpModInv, mpSqrt.
u32 mpSubtract(u32 w[], const u32 u[], const u32 v[], size_t ndigits)
Computes w = u - v, returns borrow.
Subtract two multi-precision integers. w Output array to store the result (u - v) u First input array (minuend) v Second input array (subtrahend) ndigits Number of digits in the arrays Borrow value (0 if no borrow, non-zero otherwise)
Referenced by mpGcd, mpModInv.
int mpMultiply(u32 w[], const u32 u[], const u32 v[], size_t ndigits)
Computes w = u * v.
Multiply two multi-precision integers. w Output array to store the result (u - v) u First input array (minuend) v Second input array (subtrahend) ndigits Number of digits in the arrays Borrow value (0 if no borrow, non-zero otherwise
References spMultiply.
Referenced by mpModInv, mpModMult.
int mpDivide(u32 q[], u32 r[], const u32 u[], size_t udigits, u32 v[], size_t vdigits)
Performs integer division: u = q*v + r.
q Output quotient array (size: udigits) r Output remainder array (size: udigits) u Input dividend array (size: udigits) udigits Size of q, r, and u arrays v Input divisor array (size: vdigits) vdigits Size of v array 0 if successful q and r are overwritten without preservation
References mpAdd, mpCompare, mpSetDigit, mpSetEqual, mpSetZero, mpShiftLeft, mpShiftRight, mpShortDiv, mpSizeof, spDivide.
Referenced by mpCubeRoot, mpModInv, mpModulo, mpSqrt.
int mpModulo(u32 r[], const u32 u[], size_t udigits, u32 v[], size_t vdigits)
Computes remainder r = u mod v.
r Output remainder array (size: vdigits) u Input dividend array (size: udigits) udigits Size of u array v Input divisor array (size: vdigits) vdigits Size of r and v arrays 0 if successful
References mpDivide, mpSetEqual.
Referenced by mpGcd, mpJacobi, mpModMult.
int mpSquare(u32 w[], const u32 x[], size_t ndigits)
Computes the square of a big digit number.
w Output array to store the result (size: 2 * ndigits) x Input array to be squared (size: ndigits) ndigits Number of digits in input array Overflow value from the squaring operation
References spMultiply.
int mpSqrt(u32 s[], const u32 x[], size_t ndigits)
Computes integer square root s = floor(sqrt(x))
Computes the square root of a multi-precision integer. s Output array to store the square root result x Input array containing the value to compute square root of ndigits Number of digits in the multi-precision integer Status code indicating success or failure
References mpAdd, mpCompare, mpDivide, mpSetEqual, mpShiftRight, mpShortCmp.
int mpCubeRoot(u32 s[], const u32 x[], size_t ndigits)
Computes integer cube root s = floor(cuberoot(x))
Computes the cube root of a multi-precision integer. s Output array to store the cube root result x Input array containing the value to compute cube root of ndigits Number of digits in the multi-precision integer Status code indicating success or failure
References mpAdd, mpCompare, mpDivide, mpSetEqual, mpShortCmp, mpShortDiv.
int mpEqual(const u32 a[], const u32 b[], size_t ndigits)
Returns true if a == b, else false, using constant-time algorithm.
Constant-time with respect to ndigits Compares two multi-precision integers for equality. a Pointer to first multi-precision integer array b Pointer to second multi-precision integer array ndigits Number of digits to compare Non-zero if equal, zero if not equal Returns true if a == b, else false, using constant-time algorithm.
int mpCompare(const u32 a[], const u32 b[], size_t ndigits)
Returns sign of (a-b) as {-1,0,+1} using constant-time algorithm.
Constant-time with respect to ndigits Compares two multi-precision integers. a First multi-precision integer array b Second multi-precision integer array ndigits Number of digits to compare -1 if a < b, 0 if a == b, +1 if a > b Returns sign of (a-b) as {-1,0,+1} using constant-time algorithm.
Referenced by mpCubeRoot, mpDivide, mpGcd, mpRabinMiller, mpSqrt.
int mpIsZero(const u32 a[], size_t ndigits)
Returns true if a is zero, else false, using constant-time algorithm.
Constant-time with respect to ndigits Checks if a multi-precision integer is zero. a Multi-precision integer array to check ndigits Number of digits in the array Non-zero if a is zero, zero otherwise Returns true if a is zero, else false, using constant-time algorithm.
Referenced by mpGcd, mpJacobi, mpModInv, mpRabinMiller.
int mpEqual_q(const u32 a[], const u32 b[], size_t ndigits)
Returns true if a == b, else false (quick)
Not constant-time. Compares two multi-precision integers for equality. a Pointer to the first multi-precision integer array. b Pointer to the second multi-precision integer array. ndigits Number of digits to compare. Non-zero if equal, 0 if not equal. Returns true if a == b, else false (quick)Not constant-time.
int mpCompare_q(const u32 a[], const u32 b[], size_t ndigits)
Returns sign of (a-b) as {-1,0,+1} (quick)
Not constant-time. Compares two multi-precision integers (quick version). a First multi-precision integer array b Second multi-precision integer array ndigits Number of digits to compare -1 if a < b, 0 if a == b, +1 if a > b Returns sign of (a-b) as {-1,0,+1} (quick)Not constant-time.
int mpIsZero_q(const u32 a[], size_t ndigits)
Checks if a multi-precision integer is zero (quick version).
a Multi-precision integer array to check ndigits Number of digits in the array Non-zero if a is zero, zero otherwise Checks if a multi-precision integer is zero (quick version).Not constant-time.
int mpModExp(u32 y[], const u32 x[], const u32 e[], u32 m[], size_t ndigits)
Computes modular exponentiation y = x^e mod m.
y Output array to store the result x Base array e Exponent array m Modulus array ndigits Number of digits in the arrays Status code indicating success or failure
Referenced by mpRabinMiller.
int mpModExp_ct(u32 yout[], const u32 x[], const u32 e[], u32 m[], size_t ndigits)
Computes modular exponentiation y = x^e mod m in constant time.
yout Output array to store the result x Base array e Exponent array m Modulus array ndigits Number of digits in the arrays Status code indicating success or failure Resistant to simple power analysis attack on private exponent. Slower than mpModExp(). Computes modular exponentiation y = x^e mod m in constant time.
References mpSetDigit, mpSetEqual, mpSizeof.
int mpModMult(u32 a[], const u32 x[], const u32 y[], u32 m[], size_t ndigits)
Computes modular multiplication a = (x * y) mod m.
a Output array to store the result x First input array y Second input array m Modulus array ndigits Number of digits in the arrays Status code indicating success or failure
References mpModulo, mpMultiply.
Referenced by mpRabinMiller.
int mpModInv(u32 inv[], const u32 u[], const u32 m[], size_t ndigits)
Computes the modular multiplicative inverse inv = u^{-1} mod m.
inv Output array to store the inverse u Input array to invert m Modulus array ndigits Number of digits in the arrays Status code indicating success or failure
References mpAdd, mpDivide, mpIsZero, mpMultiply, mpSetDigit, mpSetEqual, mpSetZero, mpShortCmp, mpSubtract.
int mpGcd(u32 g[], const u32 x[], const u32 y[], size_t ndigits)
Computes the greatest common divisor g = gcd(x, y)
g Output array to store the GCD x First input array y Second input array ndigits Number of digits in the arrays Status code indicating success or failure
References mpCompare, mpIsZero, mpModulo, mpSetEqual, mpShiftLeft, mpShiftRight, mpSubtract.
int mpJacobi(const u32 a[], const u32 n[], size_t ndigits)
Computes the Jacobi symbol (a/n)
a Input array (numerator) n Input array (denominator, must be odd) ndigits Number of digits in the arrays Jacobi symbol value: -1, 0, or +1 If n is prime then the Jacobi symbol becomes the Legendre symbol (a/p) defined to be (a/p) = +1 if a is a quadratic residue modulo p(a/p) = -1 if a is a quadratic non-residue modulo p(a/p) = 0 if a is divisible by p
References mpIsZero, mpModulo, mpSetEqual, mpShiftRight, mpShortCmp, mpShortMod.
size_t mpBitLength(const u32 a[], size_t ndigits)
Returns number of significant bits in a.
Returns number of significant bits in a a Multi-precision integer array ndigits Number of digits in the array Number of significant bits
References mpSizeof.
Referenced by mpConvToOctets.
u32 mpShiftLeft(u32 a[], const u32 b[], size_t x, size_t ndigits)
Computes a = b << x (shift left)
a Output array for result b Input array to shift x Number of bits to shift left ndigits Number of digits in arrays Overflow bits
Referenced by mpDivide, mpGcd, mpShortDiv.
u32 mpShiftRight(u32 a[], const u32 b[], size_t x, size_t ndigits)
Computes a = b >> x (shift right)
a Output array for result b Input array to shift x Number of bits to shift right ndigits Number of digits in arrays Underflow bits
Referenced by mpDivide, mpGcd, mpJacobi, mpRabinMiller, mpSqrt.
void mpXorBits(u32 a[], const u32 b[], const u32 c[], size_t ndigits)
Computes bitwise a = b XOR c.
a Output array for result b First input array c Second input array ndigits Number of digits in arrays
void mpOrBits(u32 a[], const u32 b[], const u32 c[], size_t ndigits)
Computes bitwise a = b OR c.
a Output array for result b First input array c Second input array ndigits Number of digits in arrays
void mpAndBits(u32 a[], const u32 b[], const u32 c[], size_t ndigits)
Computes bitwise a = b AND c.
a Output array for result b First input array c Second input array ndigits Number of digits in arrays
void mpNotBits(u32 a[], const u32 b[], size_t ndigits)
Computes bitwise a = NOT b.
a Output array for result b Input array ndigits Number of digits in arrays
Referenced by mpChs.
void mpModPowerOf2(u32 a[], size_t ndigits, size_t L)
Computes a = a mod 2^L (clears all bits greater than L)
a Array to modify ndigits Number of digits in array L Bit position threshold
int mpSetBit(u32 a[], size_t ndigits, size_t n, int value)
Sets bit n of a with specified value.
a Array to modify ndigits Number of digits in array n Bit position (0..nbits-1) value Bit value (1 or 0) Status code
int mpGetBit(u32 a[], size_t ndigits, size_t n)
Returns value of bit n.
a Array to read from ndigits Number of digits in array n Bit position (0..nbits-1) Bit value (1 or 0)
u32 mpSetZero(u32 a[], size_t ndigits)
Sets a multi-precision integer to zero.
a Array to set to zero ndigits Number of digits in array Always returns 0
Referenced by mpConvFromOctets, mpDivide, mpModInv, mpQuickRandBits, mpRabinMiller.
void mpSetDigit(u32 a[], u32 d, size_t ndigits)
Sets a multi-precision integer to a single digit value.
a Array to set d Single digit value to assign ndigits Number of digits in array
Referenced by mpDivide, mpModExp_ct, mpModInv.
void mpSetEqual(u32 a[], const u32 b[], size_t ndigits)
Copies one multi-precision integer to another.
a Destination array b Source array to copy from ndigits Number of digits to copy
Referenced by mpAbs, mpCubeRoot, mpDivide, mpGcd, mpJacobi, mpModExp_ct, mpModInv, mpModulo, mpRabinMiller, mpSqrt.
size_t mpSizeof(const u32 a[], size_t ndigits)
Returns number of significant non-zero digits in a.
a Multi-precision integer array ndigits Number of digits in the array Number of significant non-zero digits Returns number of significant non-zero digits in a.
Referenced by mpBitLength, mpDivide, mpModExp_ct, mpRabinMiller.
int mpIsPrime(u32 w[], size_t ndigits, size_t t)
Returns true (1) if w is probably prime.
w Number to test ndigits Size of array w t The count of Rabin-Miller primality tests to carry out (recommended at least 80) True (1) if w is probably prime otherwise false (0) Uses FIPS-186-2/Rabin-Miller with trial division by small primes, which is faster in most cases than mpRabinMiller(). mpRabinMiller()
References mpRabinMiller, mpShortCmp, mpShortMod.
int mpRabinMiller(u32 w[], size_t ndigits, size_t t)
Returns true (1) if w is probably prime using just the Rabin-Miller test.
w Number to test ndigits Size of array w t The count of Rabin-Miller primality tests to carry out True (1) if w is probably prime otherwise false (0) mpIsPrime() is preferred
References mpCompare, mpIsZero, mpModExp, mpModMult, mpSetEqual, mpSetZero, mpShiftRight, mpShortAdd, mpShortCmp, mpShortSub, mpSizeof.
Referenced by mpIsPrime.
u32 mpShortAdd(u32 w[], const u32 u[], u32 d, size_t ndigits)
Computes w = u + d.
w Output array for result u Input multi-precision integer array d Single digit to add ndigits Number of digits in arrays Carry value from the addition
Referenced by mpChs, mpRabinMiller.
u32 mpShortSub(u32 w[], const u32 u[], u32 d, size_t ndigits)
Computes w = u - d.
w Output array for result u Input multi-precision integer array d Single digit to subtract ndigits Number of digits in arrays Borrow value from the subtraction
Referenced by mpChs, mpRabinMiller.
u32 mpShortMult(u32 p[], const u32 x[], u32 d, size_t ndigits)
Computes product p = x * d.
p Output array for result x Input multi-precision integer array d Single digit multiplier ndigits Number of digits in arrays Overflow from multiplication
References spMultiply.
u32 mpShortDiv(u32 q[], const u32 u[], u32 d, size_t ndigits)
Computes quotient q = u / d.
q Output array for quotient u Input multi-precision integer array (dividend) d Single digit divisor ndigits Number of digits in arrays Remainder from the division
References mpShiftLeft, spDivide.
Referenced by mpCubeRoot, mpDivide, mpShortMod.
u32 mpShortMod(const u32 a[], u32 d, size_t ndigits)
Computes remainder r = a mod d.
a Input multi-precision integer array d Single digit modulus ndigits Number of digits in array Remainder value
References mpShortDiv.
Referenced by mpIsPrime, mpJacobi.
int mpShortCmp(const u32 a[], u32 d, size_t ndigits)
Compares multi-precision integer with single digit.
a Multi-precision integer array d Single digit to compare ndigits Number of digits in array -1 if a < d, 0 if a == d, +1 if a > d Compares multi-precision integer with single digit.
Referenced by mpCubeRoot, mpIsPrime, mpJacobi, mpModInv, mpRabinMiller, mpSqrt.
int spMultiply(u32 p[2], u32 x, u32 y)
Computes product of two single digits: p = x * y.
p Output array to store the product (size: 2) x First single digit multiplicand y Second single digit multiplicand Status code indicating success or failure
Referenced by mpMultiply, mpShortMult, mpSquare.
u32 spDivide(u32 *q, u32 *r, const u32 u[2], u32 v)
Computes quotient and remainder: q = u / v, r = u % v.
q Output pointer to store the quotient (single digit) r Output pointer to store the remainder (single digit) u Input dividend array (size: 2) v Single digit divisor The quotient value
Referenced by mpDivide, mpShortDiv.
u32 spSimpleRand(u32 lower, u32 upper)
Returns a simple pseudo-random digit between lower and upper.
Not crypto secure. spBetterRand() Returns a simple pseudo-random digit between lower and upper lower Lower bound (inclusive) upper Upper bound (inclusive) Random digit value between lower and upper Not crypto secure. spBetterRand()
Referenced by mpQuickRandBits.
size_t mpQuickRandBits(u32 a[], size_t ndigits, size_t nbits)
Generate a quick-and-dirty random mp number a of bit length at most nbits using plain-old-rand.
a Output array to store random number ndigits Number of digits in array nbits Maximum bit length of random number Actual number of significant digits set Not crypto secure. mpRandomBits() Generate a quick-and-dirty random mp number a of bit length at most nbits using plain-old-rand.
References mpSetZero, spSimpleRand.
void mpPrintHex(const char *prefix, const u32 *p, size_t ndigits, const char *suffix)
Print multi-precision integer in hexadecimal format.
prefix String to print before the number (can be NULL) p Multi-precision integer array to print ndigits Number of digits in the array suffix String to print after the number (can be NULL)
void mpPrint(const u32 *p, size_t ndigits)
Print all digits in hexadecimal including leading zeros.
p Multi-precision integer array to print ndigits Number of digits in the array
Referenced by mpPrintTrim.
void mpPrintNL(const u32 *p, size_t ndigits)
Print all digits in hexadecimal with newlines.
p Multi-precision integer array to print ndigits Number of digits in the array
Referenced by mpPrintTrimNL.
void mpPrintTrim(const u32 *p, size_t ndigits)
Print in hexadecimal but trim leading zero digits.
p Multi-precision integer array to print ndigits Number of digits in the array DeprecatedUse mpPrintHex()
References mpPrint.
void mpPrintTrimNL(const u32 *p, size_t ndigits)
Print in hexadecimal, trim leading zeros, and add newlines.
p Multi-precision integer array to print ndigits Number of digits in the array DeprecatedUse mpPrintHex()
References mpPrintNL.
size_t mpConvFromOctets(u32 a[], size_t ndigits, const unsigned char *c, size_t nbytes)
Converts array of octets to multi-precision integer.
a Output array to store the converted number ndigits Maximum size of output array c Input array of octets (bytes) in big-endian order nbytes Number of bytes in the input array Actual number of digits set in output array
References mpSetZero.
size_t mpConvToOctets(const u32 a[], size_t ndigits, unsigned char *c, size_t nbytes)
Converts multi-precision integer to array of octets.
a Input multi-precision integer array ndigits Number of digits in input array c Output array to store octets (bytes) in big-endian order nbytes Size of output array (will pad or truncate as needed) Number of non-zero octets required
References mpBitLength.
int mpIsNegative(const u32 x[], size_t ndigits)
Returns true (1) if x < 0, else false (0)
x Multi-precision integer array to check ndigits Number of digits in the array 1 if x is negative, 0 otherwise Expects a negative number to be stored in two's-complement representation. Returns true (1) if x < 0, else false (0)
Referenced by mpAbs, mpChs.
int mpChs(u32 x[], const u32 y[], size_t ndigits)
Sets x = -y (negation)
x Output array to store the negated result y Input array to negate ndigits Number of digits in the arrays Status code indicating success or failure Expects a negative number to be stored in two's-complement representation. Sets x = -y (negation)
References mpIsNegative, mpNotBits, mpShortAdd, mpShortSub.
Referenced by mpAbs.
int mpAbs(u32 x[], const u32 y[], size_t ndigits)
Sets x = |y|, the absolute value of y.
x Output array to store the absolute value y Input array ndigits Number of digits in the arrays Status code indicating success or failure Expects a negative number to be stored in two's-complement representation. 0 if y >= 0, 1 if y < 0 Sets x = |y|, the absolute value of y.
References mpChs, mpIsNegative, mpSetEqual.
int mpVersion(void)
Returns version number = major*1000+minor*100+release*10+PP_OPTIONS.
Returns version number = major*1000+minor*100+release*10+PP_OPTIONSVersion number encoded as integer Version number = major*1000+minor*100+release*10+uses_asm(0|1)+uses_64(0|2)+uses_noalloc(0|5) E.g. Version 2.3.0 will return 230x where x denotes the preprocessor options x | USE_SPASM | USE_64WITH32 | NO_ALLOCS 0 No No No 1 Yes No No 2 No Yes No 3 Yes Yes* No 5 No No Yes 6 Yes No Yes 7 No Yes Yes 8 Yes Yes* Yes USE_SPASM will take precedence over USE_64WITH32.