xdppsu.c
XDPPSU_AUX_MAX_DEFER_COUNT
XDPPSU_AUX_MAX_TIMEOUT_COUNT
XDPPSU_IS_CONNECTED_MAX_TIMEOUT_COUNT
XDPPSU_AUX_MAX_WAIT
XDpPsu_TrainingState
static void XDpPsu_WaitUs(XDpPsu *InstancePtr, u32 MicroSeconds)
This function is the delay/sleep function for the XDpPsu driver.
InstancePtr is a pointer to the XDpPsu instance. MicroSeconds is the number of microseconds to delay/sleep for. None. None.
static u32 XDpPsu_AuxWaitReply(XDpPsu *InstancePtr)
This function waits for a reply indicating that the most recent AUX request has been received by the RX device.
InstancePtr is a pointer to the XDpPsu instance. XST_SUCCESS if a reply was sent from the RX device.XST_ERROR_COUNT_MAX otherwise, if a timeout has occurred. None.
static u32 XDpPsu_AuxRequestSend(XDpPsu *InstancePtr, XDpPsu_AuxTransaction *Request)
This function submits the supplied AUX request to the RX device over the AUX channel by writing the command, the destination address, (the write buffer for write commands), and the data size to the DisplayPort TX core.
InstancePtr is a pointer to the XDpPsu instance. Request is a pointer to an initialized XDpPsu_AuxTransaction structure containing the required information for issuing an AUX command. XST_SUCCESS if the request was acknowledged.XST_ERROR_COUNT_MAX if waiting for a reply timed out.XST_SEND_ERROR if the request was deferred.XST_FAILURE otherwise, if the request was NACK'ed. None.
static u32 XDpPsu_AuxWaitReady(XDpPsu *InstancePtr)
This function waits until another request is no longer in progress.
InstancePtr is a pointer to the XDpPsu instance. XST_SUCCESS if the the RX device is no longer busy.XST_ERROR_COUNT_MAX otherwise, if a timeout has occurred. None.
static u32 XDpPsu_AuxRequest(XDpPsu *InstancePtr, XDpPsu_AuxTransaction *Request)
This function submits the supplied AUX request to the RX device over the AUX channel.
If waiting for a reply times out, or if the DisplayPort TX core indicates that the request was deferred, the request is sent again (up to a maximum specified by XDPPSU_AUX_MAX_DEFER_COUNT|XDPPSU_AUX_MAX_TIMEOUT_COUNT). InstancePtr is a pointer to the XDpPsu instance. Request is a pointer to an initialized XDpPsu_AuxTransaction structure containing the required information for issuing an AUX command, as well as a write buffer used for write commands, and a read buffer for read commands. XST_SUCCESS if the request was acknowledged.XST_ERROR_COUNT_MAX if resending the request exceeded the maximum for deferral and timeout.XST_FAILURE otherwise (if the DisplayPort TX core sees a NACK reply code or if the AUX transaction failed). None.
static u32 XDpPsu_GetTrainingDelay(XDpPsu *InstancePtr)
This function determines what the RX device's required training delay is for link training.
InstancePtr is a pointer to the XDpPsu instance. The training delay specified in the RX device's DisplayPort Configuration Data (DPCD) register, XDPPSU_DPCD_TRAIN_AUX_RD_INTERVAL. None.
static u32 XDpPsu_SetTrainingPattern(XDpPsu *InstancePtr, u32 Pattern)
This function sets the training pattern to be used during link training for both the DisplayPort TX core and the RX device.
Scrambler isenabled when pattern is turned off. InstancePtr is a pointer to the XDpPsu instance. Pattern selects the pattern to be used. One of the following: XDPPSU_TRAINING_PATTERN_SET_OFFXDPPSU_TRAINING_PATTERN_SET_TP1XDPPSU_TRAINING_PATTERN_SET_TP2XDPPSU_TRAINING_PATTERN_SET_TP3 XST_SUCCESS if setting the pattern was successful.XST_FAILURE otherwise. None.
static u32 XDpPsu_CheckClockRecovery(XDpPsu *InstancePtr, u8 LaneCount)
This function checks if the RX device's DisplayPort Configuration Data (DPCD) indicates that the clock recovery sequence during link training was successful - the RX device's link clock and data recovery unit has realized and maintained the frequency lock for all lanes currently in use.
InstancePtr is a pointer to the XDpPsu instance. LaneCount is the number of lanes to check. XST_SUCCESS if the RX device's clock recovery PLL has achieved frequency lock for all lanes in use.XST_FAILURE otherwise. None.
static u32 XDpPsu_CheckChannelEqualization(XDpPsu *InstancePtr, u8 LaneCount)
This function checks if the RX device's DisplayPort Configuration Data (DPCD) indicates that the channel equalization sequence during link training was successful - the RX device has achieved channel equalization, symbol lock, and interlane alignment for all lanes currently in use.
InstancePtr is a pointer to the XDpPsu instance. LaneCount is the number of lanes to check. XST_SUCCESS if the RX device has achieved channel equalization symbol lock, and interlane alignment for all lanes in use.XST_FAILURE otherwise. None.
static u32 XDpPsu_GetLaneStatusAdjReqs(XDpPsu *InstancePtr)
This function will do a burst AUX read from the RX device over the AUX channel.
The contents of the status registers will be stored for later use by XDpPsu_CheckClockRecovery, XDpPsu_CheckChannelEqualization, and XDpPsu_AdjVswingPreemp. InstancePtr is a pointer to the XDpPsu instance. XST_SUCCESS if the AUX read was successful.XST_FAILURE otherwise. None.
static u32 XDpPsu_AdjVswingPreemp(XDpPsu *InstancePtr)
This function sets new voltage swing and pre-emphasis levels using the adjustment requests obtained from the RX device.
InstancePtr is a pointer to the XDpPsu instance. XST_SUCCESS if the new levels were written successfully.XST_FAILURE otherwise (an AUX transaction failed). None.
static XDpPsu_TrainingState XDpPsu_TrainingStateChannelEqualization(XDpPsu *InstancePtr)
This function runs the channel equalization sequence as part of link training.
The sequence is as follows: 0) Start signaling with the same drive settings used at the end of the clock recovery sequence. 1) Transmit training pattern 2 (or 3) over the main link with symbol scrambling disabled. 2) The channel equalization loop. If channel equalization is unsuccessful after 5 loop iterations, return. 2a) Wait for at least the period of time specified in the RX device's DisplayPort Configuration Data (DPCD) register, TRAINING_AUX_RD_INTERVAL. 2b) Check if all lanes have achieved channel equalization, symbol lock, and interlane alignment. If so, return. 2c) Check if the same voltage swing level has been used 5 consecutive times or if the maximum level has been reached. If so, return. 2d) Adjust the voltage swing, pre-emphasis, and post-cursor levels as requested by the RX device. 2e) Loop back to 2a. For a more detailed description of the channel equalization sequence, see section 3.5.1.2.2 of the DisplayPort 1.2a specification document. InstancePtr is a pointer to the XDpPsu instance. The next training state: XDPPSU_TS_SUCCESS if training succeeded.XDPPSU_TS_FAILURE if writing the drive settings to the RX device was unsuccessful.XDPPSU_TS_ADJUST_LINK_RATE if, after 5 loop iterations, the channel equalization sequence did not complete successfully. None.
static XDpPsu_TrainingState XDpPsu_TrainingStateAdjustLaneCount(XDpPsu *InstancePtr)
This function is reached if either the clock recovery or the channel equalization process failed during training, and a minimal data rate of 1.62 Gbps was being used.
As a result, the number of lanes in use will be reduced, and training will be re-attempted (starting with clock recovery) at this lower lane count.Training will be re-attempted with the maximum data rate being used with the reduced lane count to train at the main link at the maximum bandwidth possible. InstancePtr is a pointer to the XDpPsu instance. The next training state: XDPPSU_TS_FAILURE if only one lane is already in use.XDPPSU_TS_CLOCK_RECOVERY otherwise. Re-attempt training. None.
static XDpPsu_TrainingState XDpPsu_TrainingStateAdjustLinkRate(XDpPsu *InstancePtr)
This function is reached if either the clock recovery or the channel equalization process failed during training.
As a result, the data rate will be downshifted, and training will be re-attempted (starting with clock recovery) at the reduced data rate. If the data rate is already at 1.62 Gbps, a downshift in lane count will be attempted. InstancePtr is a pointer to the XDpPsu instance. The next training state: XDPPSU_TS_ADJUST_LANE_COUNT if the minimal data rate is already in use. Re-attempt training at a reduced lane count.XDPPSU_TS_CLOCK_RECOVERY otherwise. Re-attempt training. None.
static XDpPsu_TrainingState XDpPsu_TrainingStateClockRecovery(XDpPsu *InstancePtr)
This function runs the clock recovery sequence as part of link training.
The sequence is as follows: 0) Start signaling at the minimum voltage swing, pre-emphasis, and post- cursor levels. 1) Transmit training pattern 1 over the main link with symbol scrambling disabled. 2) The clock recovery loop. If clock recovery is unsuccessful after 5 loop iterations, return. 2a) Wait for at least the period of time specified in the RX device's DisplayPort Configuration Data (DPCD) register, TRAINING_AUX_RD_INTERVAL. 2b) Check if all lanes have achieved clock recovery lock. If so, return. 2c) Check if the same voltage swing level has been used 5 consecutive times or if the maximum level has been reached. If so, return. 2d) Adjust the voltage swing, pre-emphasis, and post-cursor levels as requested by the RX device. 2e) Loop back to 2a. For a more detailed description of the clock recovery sequence, see section 3.5.1.2.1 of the DisplayPort 1.2a specification document. InstancePtr is a pointer to the XDpPsu instance. The next training state: XDPPSU_TS_CHANNEL_EQUALIZATION if the clock recovery sequence completed successfully.XDPPSU_TS_FAILURE if writing the drive settings to the RX device was unsuccessful.XDPPSU_TS_ADJUST_LINK_RATE if the clock recovery sequence did not complete successfully. None.
static u32 XDpPsu_RunTraining(XDpPsu *InstancePtr)
This function runs the link training process.
It is implemented as a state machine, with each state returning the next state. First, the clock recovery sequence will be run; if successful, the channel equalization sequence will run. If either the clock recovery or channel equalization sequence failed, the link rate or the number of lanes used will be reduced and training will be re-attempted. If training fails at the minimal data rate, 1.62 Gbps with a single lane, training will no longer re-attempt and fail. InstancePtr is a pointer to the XDpPsu instance. XST_SUCCESS if the training process succeeded.XST_FAILURE otherwise. None.
static u32 XDpPsu_CheckLaneAlign(XDpPsu *InstancePtr)
This function checks the lane alignment status.
InstancePtr is a pointer to the XDpPsu instance. XST_SUCCESS if the lane alignment is complete.XST_FAILURE if the lane alignment is not complete.
static u32 XDpPsu_AuxCommon(XDpPsu *InstancePtr, u32 CmdType, u32 Address, u32 NumBytes, u8 *Data)
This function contains the common sequence of submitting an AUX command for AUX read, AUX write, I2C-over-AUX read, and I2C-over-AUX write transactions.
If required, the reads and writes are split into multiple requests, each acting on a maximum of 16 bytes. InstancePtr is a pointer to the XDpPsu instance. CmdType is the type of AUX command (one of: XDPPSU_AUX_CMD_READ, XDPPSU_AUX_CMD_WRITE, XDPPSU_AUX_CMD_I2C_READ, or XDPPSU_AUX_CMD_I2C_WRITE. Address is the starting address that the AUX transaction will read/write from/to the RX device. NumBytes is the number of bytes to read/write from/to the RX device. Data is a pointer to the data buffer that contains the data to be read/written from/to the RX device. XST_SUCCESS if the AUX transaction request was acknowledged.XST_ERROR_COUNT_MAX if the AUX request timed out.XST_FAILURE otherwise (if the DisplayPort TX core sees a NACK reply code or if the AUX transaction failed).XST_DEVICE_NOT_FOUND if the sink is disconnected from the TX. None.
static u32 XDpPsu_WaitPhyReady(XDpPsu *InstancePtr)
This function waits for the DisplayPort PHY to come out of reset.
InstancePtr is a pointer to the XDpPsu instance. XST_ERROR_COUNT_MAX if the PHY failed to be ready.XST_SUCCESS otherwise. None.
static u32 XDpPsu_SetPhyClkSpeed(XDpPsu *InstancePtr, u32 Speed)
This function sets the clock frequency for the DisplayPort PHY corresponding to a desired data rate.
InstancePtr is a pointer to the XDpPsu instance. Speed determines what clock frequency will be used based on one of the following selects: XDPPSU_PHY_CLOCK_SELECT_162GBPS = 0x01XDPPSU_PHY_CLOCK_SELECT_270GBPS = 0x03XDPPSU_PHY_CLOCK_SELECT_540GBPS = 0x05 XST_SUCCESS if the reset for each lane is done after the clock frequency has been set.XST_FAILURE otherwise. None.
u32 XDpPsu_InitializeTx(XDpPsu *InstancePtr)
This function prepares the DisplayPort TX core for use.
InstancePtr is a pointer to the XDpPsu instance. XST_SUCCESS if the DisplayPort TX core was successfully initialized.XST_FAILURE otherwise. None.
References XDpPsu_Config::BaseAddr, XDpPsu::Config, XDpPsu::IsReady, XDpPsu::SAxiClkHz, XDPPSU_AUX_CLK_DIVIDER, XDPPSU_AUX_CLK_DIVIDER_VAL_MASK, XDPPSU_DP_DISABLE, XDPPSU_DP_ENABLE, XDPPSU_ENABLE, XDPPSU_INTR_HPD_EVENT_MASK, XDPPSU_INTR_HPD_IRQ_MASK, XDPPSU_INTR_HPD_PULSE_DETECTED_MASK, XDPPSU_INTR_MASK, XDPPSU_PHY_CLOCK_SELECT, XDPPSU_PHY_CLOCK_SELECT_540GBPS, XDPPSU_PHY_CONFIG, XDPPSU_PHY_CONFIG_GT_ALL_RESET_MASK, XDpPsu_ReadReg, XDPPSU_SOFT_RESET, XDPPSU_SOFT_RESET_EN, XDpPsu_WriteReg.
Referenced by DpPsu_SetupExample.
void XDpPsu_CfgInitialize(XDpPsu *InstancePtr, XDpPsu_Config *ConfigPtr, u32 EffectiveAddr)
This function retrieves the configuration for this DisplayPort TX instance and fills in the InstancePtr->Config structure.
InstancePtr is a pointer to the XDpPsu instance. ConfigPtr is a pointer to the configuration structure that will be used to copy the settings from. EffectiveAddr is the device base address in the virtual memory space. If the address translation is not used, then the physical address is passed. None. Unexpected errors may occur if the address mapping is changed after this function is invoked.
References XDpPsu_Config::BaseAddr, XDpPsu::Config, XDpPsu::IsReady, XDpPsu::SAxiClkHz.
Referenced by DpPsu_SelfTestExample, DpPsu_SetupExample.
u32 XDpPsu_GetRxCapabilities(XDpPsu *InstancePtr)
This function retrieves the RX device's capabilities from the RX device's DisplayPort Configuration Data (DPCD).
InstancePtr is a pointer to the XDpPsu instance. XST_SUCCESS if the DisplayPort Configuration Data was read successfully.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_FAILURE otherwise. None.
References XDpPsu::Config, XDpPsu_SinkConfig::DpcdRxCapsField, XDpPsu::IsReady, XDpPsu::LinkConfig, XDpPsu_LinkConfig::MaxLaneCount, XDpPsu_LinkConfig::MaxLinkRate, XDpPsu::RxConfig, XDpPsu_LinkConfig::SupportDownspreadControl, XDpPsu_LinkConfig::SupportEnhancedFramingMode, XDPPSU_0_LANE_COUNT, XDpPsu_AuxRead.
Referenced by DpPsu_StartLink.
u32 XDpPsu_CfgMainLinkMax(XDpPsu *InstancePtr)
This function determines the common capabilities between the DisplayPort TX core and the RX device.
InstancePtr is a pointer to the XDpPsu instance. XST_SUCCESS if main link settings were successfully set.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_FAILURE otherwise. None.
References XDpPsu::IsReady, XDpPsu::LinkConfig, XDpPsu_LinkConfig::MaxLaneCount, XDpPsu_LinkConfig::MaxLinkRate, XDpPsu_SetLaneCount, XDpPsu_SetLinkRate.
Referenced by DpPsu_StartLink.
u32 XDpPsu_EstablishLink(XDpPsu *InstancePtr)
This function checks if the link needs training and runs the training sequence if training is required.
InstancePtr is a pointer to the XDpPsu instance. XST_SUCCESS was either already trained, or has been trained successfully.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_FAILURE otherwise. None.
References XDpPsu_Config::BaseAddr, XDpPsu::Config, XDpPsu::IsReady, XDpPsu_LinkConfig::LaneCount, XDpPsu::LinkConfig, XDpPsu_LinkConfig::LinkRate, XDpPsu_CheckLinkStatus, XDPPSU_ENABLE_MAIN_STREAM, XDpPsu_EnableMainLink, XDPPSU_LANE_COUNT_SET_1, XDPPSU_LANE_COUNT_SET_2, XDPPSU_LINK_BW_SET_162GBPS, XDPPSU_LINK_BW_SET_270GBPS, XDPPSU_LINK_BW_SET_540GBPS, XDPPSU_PHY_CONFIG_PHY_RESET_MASK, XDPPSU_PHY_CONFIG_TX_PHY_8B10BEN_MASK, XDpPsu_ReadReg, XDpPsu_ResetPhy, XDPPSU_TRAINING_PATTERN_SET_OFF.
Referenced by DpPsu_StartLink.
u32 XDpPsu_CheckLinkStatus(XDpPsu *InstancePtr, u8 LaneCount)
This function checks if the reciever's DisplayPort Configuration Data (DPCD) indicates the receiver has achieved and maintained clock recovery, channel equalization, symbol lock, and interlane alignment for all lanes currently in use.
InstancePtr is a pointer to the XDpPsu instance. LaneCount is the number of lanes to check. XST_SUCCESS if the RX device has maintained clock recovery, channel equalization, symbol lock, and interlane alignment.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_FAILURE otherwise. None.
References XDpPsu::IsReady, XDPPSU_LANE_COUNT_SET_1, XDPPSU_LANE_COUNT_SET_2.
Referenced by DpPsu_StartLink, XDpPsu_EstablishLink.
u32 XDpPsu_IsConnected(XDpPsu *InstancePtr)
This function checks if there is a connected RX device.
InstancePtr is a pointer to the XDpPsu instance. TRUE if there is a connection.FALSE if there is no connection.
References XDpPsu_Config::BaseAddr, XDpPsu::Config, XDPPSU_INTERRUPT_SIG_STATE, XDPPSU_INTERRUPT_SIG_STATE_HPD_STATE_MASK, XDpPsu_ReadReg.
Referenced by XDpPsu_HpdInterruptHandler.
u32 XDpPsu_AuxRead(XDpPsu *InstancePtr, u32 DpcdAddress, u32 BytesToRead, void *ReadData)
This function issues a read request over the AUX channel that will read from the RX device's DisplayPort Configuration Data (DPCD) address space.
The read message will be divided into multiple transactions which read a maximum of 16 bytes each. InstancePtr is a pointer to the XDpPsu instance. DpcdAddress is the starting address to read from the RX device. BytesToRead is the number of bytes to read from the RX device. ReadData is a pointer to the data buffer that will be filled with read data. XST_SUCCESS if the AUX read request was successfully acknowledged.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_ERROR_COUNT_MAX if the AUX request timed out.XST_FAILURE otherwise. None.
References XDpPsu::IsReady, XDPPSU_AUX_CMD_READ.
Referenced by XDpPsu_GetRxCapabilities, XDpPsu_SetDownspread, XDpPsu_SetEnhancedFrameMode, XDpPsu_SetLaneCount, XDpPsu_SetScrambler.
u32 XDpPsu_AuxWrite(XDpPsu *InstancePtr, u32 DpcdAddress, u32 BytesToWrite, void *WriteData)
This function issues a write request over the AUX channel that will write to the RX device's DisplayPort Configuration Data (DPCD) address space.
The write message will be divided into multiple transactions which write a maximum of 16 bytes each. InstancePtr is a pointer to the XDpPsu instance. DpcdAddress is the starting address to write to the RX device. BytesToWrite is the number of bytes to write to the RX device. WriteData is a pointer to the data buffer that contains the data to be written to the RX device. XST_SUCCESS if the AUX write request was successfully acknowledged.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_ERROR_COUNT_MAX if the AUX request timed out.XST_FAILURE otherwise. None.
References XDpPsu::IsReady, XDPPSU_AUX_CMD_WRITE.
Referenced by XDpPsu_SetDownspread, XDpPsu_SetEnhancedFrameMode, XDpPsu_SetLaneCount, XDpPsu_SetLinkRate, XDpPsu_SetScrambler.
u32 XDpPsu_IicRead(XDpPsu *InstancePtr, u8 IicAddress, u16 Offset, u16 BytesToRead, void *ReadData)
This function performs an I2C read over the AUX channel.
The read message will be divided into multiple transactions if the requested data spans multiple segments. The segment pointer is automatically incremented and the offset is calibrated as needed. E.g. For an overall offset of: 128, an I2C read is done on segptr=0; offset=128.256, an I2C read is done on segptr=1; offset=0.384, an I2C read is done on segptr=1; offset=128.512, an I2C read is done on segptr=2; offset=0.etc. InstancePtr is a pointer to the XDpPsu instance. IicAddress is the address on the I2C bus of the target device. Offset is the offset at the specified address of the targeted I2C device that the read will start from. BytesToRead is the number of bytes to read. ReadData is a pointer to a buffer that will be filled with the I2C read data. XST_SUCCESS if the I2C read has successfully completed with no errors.XST_ERROR_COUNT_MAX if the AUX request timed out.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_FAILURE otherwise. None.
References XDpPsu_Config::BaseAddr, XDpPsu::Config, XDpPsu::IsReady, XDPPSU_AUX_CMD_I2C_READ, XDPPSU_AUX_CMD_I2C_WRITE_MOT, XDpPsu_IicWrite, XDPPSU_INTR_HPD_EVENT_MASK, XDPPSU_INTR_STATUS, XDpPsu_ReadReg.
Referenced by XDpPsu_GetEdidBlock.
u32 XDpPsu_IicWrite(XDpPsu *InstancePtr, u8 IicAddress, u8 BytesToWrite, void *WriteData)
This function performs an I2C write over the AUX channel.
InstancePtr is a pointer to the XDpPsu instance. IicAddress is the address on the I2C bus of the target device. BytesToWrite is the number of bytes to write. WriteData is a pointer to a buffer which will be used as the data source for the write. XST_SUCCESS if the I2C write has successfully completed with no errors.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_ERROR_COUNT_MAX if the AUX request timed out.XST_FAILURE otherwise. None.
References XDpPsu::IsReady, XDPPSU_AUX_CMD_I2C_WRITE.
Referenced by XDpPsu_IicRead.
u32 XDpPsu_SetDownspread(XDpPsu *InstancePtr, u8 Enable)
This function enables or disables 0.5% spreading of the clock for both the DisplayPort and the RX device.
InstancePtr is a pointer to the XDpPsu instance. Enable will downspread the main link signal if set to 1 and disable downspreading if set to 0. XST_SUCCESS if setting the downspread control enable was successful.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_FAILURE otherwise. None.
References XDpPsu_Config::BaseAddr, XDpPsu::Config, XDpPsu_LinkConfig::DownspreadControl, XDpPsu::IsReady, XDpPsu::LinkConfig, XDpPsu_AuxRead, XDpPsu_AuxWrite, XDPPSU_DOWNSPREAD_CTRL, XDpPsu_WriteReg.
Referenced by DpPsu_StartLink.
u32 XDpPsu_SetEnhancedFrameMode(XDpPsu *InstancePtr, u8 Enable)
This function enables or disables the enhanced framing symbol sequence for both the DisplayPort TX core and the RX device.
InstancePtr is a pointer to the XDpPsu instance. Enable will enable enhanced frame mode if set to 1 and disable it if set to 0. XST_SUCCESS if setting the enhanced frame mode enable was successful.XST_DEVICE_NOT_FOUND if no RX is connected.XST_FAILURE otherwise. None.
References XDpPsu_Config::BaseAddr, XDpPsu::Config, XDpPsu_LinkConfig::EnhancedFramingMode, XDpPsu::IsReady, XDpPsu::LinkConfig, XDpPsu_AuxRead, XDpPsu_AuxWrite, XDPPSU_ENHANCED_FRAME_EN, XDpPsu_WriteReg.
Referenced by DpPsu_StartLink.
u32 XDpPsu_SetLaneCount(XDpPsu *InstancePtr, u8 LaneCount)
This function sets the number of lanes to be used by the main link for both the DisplayPort TX core and the RX device.
InstancePtr is a pointer to the XDpPsu instance. LaneCount is the number of lanes to be used over the main link. XST_SUCCESS if setting the new lane count was successful.XST_DEVICE_NOT_FOUND if no RX is connected.XST_FAILURE otherwise. None.
References XDpPsu_Config::BaseAddr, XDpPsu::Config, XDpPsu::IsReady, XDpPsu_LinkConfig::LaneCount, XDpPsu::LinkConfig, XDPPSU_0_LANE_COUNT, XDpPsu_AuxRead, XDpPsu_AuxWrite, XDPPSU_LANE_COUNT_SET, XDpPsu_WriteReg.
Referenced by DpPsu_StartLink, XDpPsu_CfgMainLinkMax.
u32 XDpPsu_SetLinkRate(XDpPsu *InstancePtr, u8 LinkRate)
This function sets the data rate to be used by the main link for both the DisplayPort TX core and the RX device.
InstancePtr is a pointer to the XDpPsu instance. LinkRate is the link rate to be used over the main link based on one of the following selects: XDPPSU_LINK_BW_SET_162GBPS = 0x06 (for a 1.62 Gbps data rate)XDPPSU_LINK_BW_SET_270GBPS = 0x0A (for a 2.70 Gbps data rate)XDPPSU_LINK_BW_SET_540GBPS = 0x14 (for a 5.40 Gbps data rate) XST_SUCCESS if setting the new link rate was successful.XST_DEVICE_NOT_FOUND if no RX device is connected.XST_FAILURE otherwise. None.
References XDpPsu_Config::BaseAddr, XDpPsu::Config, XDpPsu::IsReady, XDpPsu::LinkConfig, XDpPsu_LinkConfig::LinkRate, XDpPsu_AuxWrite, XDPPSU_LINK_BW_SET, XDPPSU_LINK_BW_SET_162GBPS, XDPPSU_LINK_BW_SET_270GBPS, XDPPSU_LINK_BW_SET_540GBPS, XDPPSU_PHY_CLOCK_SELECT_162GBPS, XDPPSU_PHY_CLOCK_SELECT_270GBPS, XDPPSU_PHY_CLOCK_SELECT_540GBPS, XDpPsu_WriteReg.
Referenced by DpPsu_StartLink, XDpPsu_CfgMainLinkMax.
u32 XDpPsu_SetScrambler(XDpPsu *InstancePtr, u8 Enable)
This function enables or disables scrambling of symbols for both the DisplayPort and the RX device.
InstancePtr is a pointer to the XDpPsu instance. Enable will enable or disable scrambling. XST_SUCCESS if setting the scrambling enable was successful.XST_FAILURE otherwise. None.
References XDpPsu_Config::BaseAddr, XDpPsu::Config, XDpPsu::IsReady, XDpPsu::LinkConfig, XDpPsu_LinkConfig::ScramblerEn, XDpPsu_AuxRead, XDpPsu_AuxWrite, XDPPSU_SCRAMBLING_DISABLE, XDpPsu_WriteReg.
void XDpPsu_EnableMainLink(XDpPsu *InstancePtr, u8 Enable)
This function enables the main link.
InstancePtr is a pointer to the XDpPsu instance. Enable is a control flag to enable or disable main link None. Enable = 1, Enable main link Enable =0, Disable main link.
References XDpPsu_Config::BaseAddr, XDpPsu::Config, XDpPsu::IsReady, XDPPSU_ENABLE_MAIN_STREAM, XDPPSU_FORCE_SCRAMBLER_RESET, XDpPsu_WriteReg.
Referenced by XDpPsu_EstablishLink.
void XDpPsu_ResetPhy(XDpPsu *InstancePtr, u32 Reset)
This function does a PHY reset.
InstancePtr is a pointer to the XDpPsu instance. Reset is the type of reset to assert. None. None.
References XDpPsu_Config::BaseAddr, XDpPsu::Config, XDpPsu::IsReady, XDPPSU_ENABLE, XDPPSU_PHY_CONFIG, XDpPsu_ReadReg, XDpPsu_WriteReg.
Referenced by XDpPsu_EstablishLink.