xdppsu_common_example.c
static void DpPsu_StartVideoStream(XDpPsu *InstancePtr)
This function will start sending a video stream over the main link.
The settings to be used are as follows: 8 bits per color.Video timing and screen resolution used:The connected monitor's preferred timing is used to determine the video resolution (and associated timings) for the stream. InstancePtr is a pointer to the XDpPsu instance. None. The DpPsu_StreamSrc* are intentionally left for the user to implement since configuration of the stream source is application-specific. The Extended Display Identification Data (EDID) is read in order to obtain the video resolution and timings. If this read fails, a resolution of 640x480 is used at a refresh rate of 60Hz.
u32 DpPsu_Run(XDpPsu *InstancePtr)
This function will configure and establish a link with the receiver device, afterwards, a video stream will start to be sent over the main link.
InstancePtr is a pointer to the XDpPsu instance. XST_SUCCESS if main link was successfully established.XST_FAILURE otherwise. None.
References DpPsu_StartLink.
u32 DpPsu_SetupExample(XDpPsu *InstancePtr, u32 BaseAddress)
This function will setup and initialize the DisplayPort TX core.
The core's configuration parameters will be retrieved based on the configuration to the DisplayPort TX core instance with the specified device ID. InstancePtr is a pointer to the XDpPsu instance. DeviceId is the unique device ID of the DisplayPort TX core instance. XST_SUCCESS if the device configuration was found and obtained and if the main link was successfully established.XST_FAILURE otherwise. None.
References XDpPsu_Config::BaseAddr, XDpPsu_CfgInitialize, XDpPsu_InitializeTx, XDpPsu_LookupConfig.
Referenced by DpPsu_IntrExample, DpPsu_PollExample.
u32 DpPsu_StartLink(XDpPsu *InstancePtr)
This function will configure and establish a link with the receiver device.
InstancePtr is a pointer to the XDpPsu instance. XST_SUCCESS the if main link was successfully established.XST_FAILURE otherwise. None.
References XDpPsu_Config::BaseAddr, XDpPsu::Config, XDpPsu_LinkConfig::LaneCount, XDpPsu::LinkConfig, XDpPsu_LinkConfig::LinkRate, XDpPsu_LinkConfig::MaxLaneCount, XDpPsu_LinkConfig::MaxLinkRate, XDpPsu_CfgMainLinkMax, XDpPsu_CheckLinkStatus, XDpPsu_EstablishLink, XDpPsu_GetRxCapabilities, XDPPSU_LINK_BW_SET, XDpPsu_ReadReg, XDpPsu_SetDownspread, XDpPsu_SetEnhancedFrameMode, XDpPsu_SetLaneCount, XDpPsu_SetLinkRate.
Referenced by DpPsu_Run.