xdppsu_common_example.h
DPPSU_BASEADDR
TRAIN_USE_LINK_RATE
TRAIN_USE_LANE_COUNT
TRAIN_USE_MAX_LINK
XDpPsu DpPsuInstance
u32 DpPsu_PlatformInit(void)
u32 DpPsu_StreamSrcSync(XDpPsu *InstancePtr)
u32 DpPsu_StreamSrcSetup(XDpPsu *InstancePtr)
u32 DpPsu_StreamSrcConfigure(XDpPsu *InstancePtr)
u32 DpPsu_SetupExample(XDpPsu *InstancePtr, u32 BaseAddress)
This function will setup and initialize the DisplayPort TX core.
The core's configuration parameters will be retrieved based on the configuration to the DisplayPort TX core instance with the specified device ID. InstancePtr is a pointer to the XDpPsu instance. DeviceId is the unique device ID of the DisplayPort TX core instance. XST_SUCCESS if the device configuration was found and obtained and if the main link was successfully established.XST_FAILURE otherwise. None.
References XDpPsu_Config::BaseAddr, XDpPsu_CfgInitialize, XDpPsu_InitializeTx, XDpPsu_LookupConfig.
Referenced by DpPsu_IntrExample, DpPsu_PollExample.
u32 DpPsu_StartLink(XDpPsu *InstancePtr)
This function will configure and establish a link with the receiver device.
InstancePtr is a pointer to the XDpPsu instance. XST_SUCCESS the if main link was successfully established.XST_FAILURE otherwise. None.
References XDpPsu_Config::BaseAddr, XDpPsu::Config, XDpPsu_LinkConfig::LaneCount, XDpPsu::LinkConfig, XDpPsu_LinkConfig::LinkRate, XDpPsu_LinkConfig::MaxLaneCount, XDpPsu_LinkConfig::MaxLinkRate, XDpPsu_CfgMainLinkMax, XDpPsu_CheckLinkStatus, XDpPsu_EstablishLink, XDpPsu_GetRxCapabilities, XDPPSU_LINK_BW_SET, XDpPsu_ReadReg, XDpPsu_SetDownspread, XDpPsu_SetEnhancedFrameMode, XDpPsu_SetLaneCount, XDpPsu_SetLinkRate.
Referenced by DpPsu_Run.
u32 DpPsu_Run(XDpPsu *InstancePtr)
This function will configure and establish a link with the receiver device, afterwards, a video stream will start to be sent over the main link.
InstancePtr is a pointer to the XDpPsu instance. XST_SUCCESS if main link was successfully established.XST_FAILURE otherwise. None.
References DpPsu_StartLink.