csi2txss
XCSI2TXSS_CCM
XCSI2TXSS_NCCM
XCSI2TXSS_HANDLER_WRG_LANE
XCSI2TXSS_HANDLER_GSPFIFO_FULL
XCSI2TXSS_HANDLER_ULPS
XCSI2TXSS_HANDLER_LINEBUF_FULL
XCSI2TXSS_HANDLER_WRG_DATATYPE
XCSI2TXSS_HANDLER_UNDERRUN_PIXEL
XCSI2TXSS_HANDLER_LCERRVC0
XCSI2TXSS_HANDLER_LCERRVC1
XCSI2TXSS_HANDLER_LCERRVC2
XCSI2TXSS_HANDLER_LCERRVC3
XCsi2TxSS_LCStatus
Less no of lines recvd.
typedef void(* XCsi2TxSs_Callback)(void *CallbackRef, u32 Mask))(void *CallbackRef, u32 Mask)
Callback type which acts as a wrapper on top of CSI Callback.
CallbackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. Mask is a bit mask indicating the cause of the event. For current core version, this parameter is "OR" of 0 or more XCSI2TXSS_ISR_*_MASK constants defined in xcsi2txss_hw.h. None. None.
XCsi2TxSs_SubCores Csi2TxSsSubCores[][]
XCsi2TxSs_Config XCsi2TxSs_ConfigTable[][]
XCsi2TxSs Csi2TxSsInst
volatile u32 interrupt_counts
XCsi2TxSs Csi2TxSsInst
static void Csi2TxSs_GetIncludedSubCores(XCsi2TxSs *Csi2TxSsPtr)
This function queries the subsystem instance configuration to determine the included sub-cores.
For each sub-core that is present in the design the sub-core driver instance is binded with the subsystem sub-core driver handle CsiSsPtr is a pointer to the Subsystem instance to be worked. None None
static u32 Csi2TxSs_SubCoreInitCsi(XCsi2TxSs *CsiSsPtr)
This function initializes the included sub-core to it's static configuration.
CsiSsPtr is a pointer to the Subsystem instance to be worked. XST_SUCCESS If CSI sub core is initialised successfullyXST_FAILURE If CSI sub core inititlization fails None
static u32 Csi2TxSs_ComputeSubCoreAbsAddr(UINTPTR SsBaseAddr, UINTPTR SsHighAddr, u32 Offset, UINTPTR *BaseAddr)
This function computes the subcore absolute address on axi-lite interface Subsystem is mapped at an absolute address and all included sub-cores are at pre-defined offset from the subsystem base address.
To access the subcore register map from host CPU an absolute address is required. The subsystem is aligned to 4K address and has address range of max 8K (0x00000-0x2000). By default, CSI is at offset 0x0_0000, and DPHY is at offset 0x0_1000. SsBaseAddr is the base address of the the Subsystem instance SsHighAddr is the max address of the Subsystem instance Offset is the offset of the specified core BaseAddr is the computed absolute base address of the subcore XST_SUCCESS if base address computation is successful and within subsystem address rangeXST_FAILURE Otherwise None
u32 XCsi2TxSs_CfgInitialize(XCsi2TxSs *InstancePtr, XCsi2TxSs_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the MIPI CSI subsystem and included sub-cores.
This function must be called prior to using the subsystem. Initialization includes setting up the instance data for top level as well as all included sub-core therein, and ensuring the hardware is in a known stable state. InstancePtr is a pointer to the Subsystem instance to be worked on. CfgPtr points to the configuration structure associated with the subsystem instance. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if initialization is successfulXST_FAILURE, otherwise None.
References XCsi2TxSs_Config::BaseAddr, XCsi2TxSs::Config, XCsi2TxSs_Config::IsDphyRegIntfcPresent, XCsi2TxSs::IsReady.
Referenced by Csi2TxSs_IntrExample, Csi2TxSs_SelfTestExample.
u32 XCsi2TxSs_Configure(XCsi2TxSs *InstancePtr, u8 ActiveLanes, u32 IntrMask)
This function is used to configure the CSI lanes and interrupts that are to be handled by the application.
Refer to XCsi2Tx.h for interrupt masks. InstancePtr is a pointer to the Subsystem instance to be worked on. ActiveLanes is no of active lanes to be configure. This value ranges between 1 and 4. IntrMask Indicates Mask for enable interrupts. XST_SUCCESS on successful configuration of parameters XST_FAILURE otherwise When EnableActiveLanes is 0, then the ActiveLanes parameter passed should be equal to Max Lanes of design.
References XCsi2TxSs::Config, XCsi2TxSs_Config::FEGenEnabled.
Referenced by Csi2TxSs_IntrExample.
u32 XCsi2TxSs_Activate(XCsi2TxSs *InstancePtr, u8 Flag)
This function is used to activate the CSI Subsystem.
Internally it activates the DPHY and CSI. InstancePtr is a pointer to the Subsystem instance to be worked on. Flag is used to denote whether to enable or disable the subsystem XST_SUCCESS on successful operationXST_FAILURE on failed operation None
References XCsi2TxSs::Config, XCsi2TxSs_Config::IsDphyRegIntfcPresent.
Referenced by Csi2TxSs_IntrExample.
u32 XCsi2TxSs_Reset(XCsi2TxSs *InstancePtr)
This function is used to reset the CSI Subsystem.
Internally it resets the DPHY and CSI InstancePtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS if all the sub core IP resets occur correctlyXST_FAILURE if reset fails for any sub core IP fails None
Referenced by Csi2TxSs_IntrExample.
void XCsi2TxSs_ReportCoreInfo(XCsi2TxSs *InstancePtr)
This function reports list of cores included.
InstancePtr is a pointer to the Subsystem instance to be worked on. None None
References XCsi2TxSs::Config, XCsi2TxSs_Config::IsDphyRegIntfcPresent.
Referenced by Csi2TxSs_IntrExample.
void XCsi2TxSs_GetShortPacket(XCsi2TxSs *InstancePtr)
This function gets the short packets.
InstancePtr is a pointer to the Subsystem instance to be worked on. None None
References XCsi2TxSs::SpktData.
void XCsi2TxSs_LineGen(XCsi2TxSs *InstancePtr, u32 Value)
This function is to set the Line Synchronization packet Generation status.
InstancePtr is a pointer to the CSI2 TX SS Instance to be worked on. Value 0 : DISABLE 1 : ENABLE None None
void XCsi2TxSs_SetGSPEntry(XCsi2TxSs *InstancePtr, u32 Value)
This function is to set Generic Short Packet Entries.
InstancePtr is a pointer to the CSI2 TX SS Instance to be worked on. Value GSP 32 bit Entry None None
u32 XCsi2TxSs_GetPixelMode(XCsi2TxSs *InstancePtr)
This function is used to get the Pixel Mode.
InstancePtr is a pointer to the CSI2TX SS Instance to be worked on. 0x0 - Single Pixel Mode 0x1 - Dual Pixel Mode 0x3 - Quad Pixel Mode None
u32 XCsi2TxSs_GetMaxLaneCount(XCsi2TxSs *InstancePtr)
This function is used to get the number of lanes configured in the IP.
InstancePtr is a pointer to the CSI2TX SS Instance to be worked on. Max number of lanes available in u32 format None
u32 XCsi2TxSs_IsUlps(XCsi2TxSs *InstancePtr)
This function is used to check if lanes are in ulps mode.
InstancePtr is a pointer to the CSI2TX SS Instance to be worked on. 1 - ulps mode enter0 - ulps mode exit None
void XCsi2TxSs_SetUlps(XCsi2TxSs *InstancePtr, u32 Value)
This function is used to set lanes in ulps mode.
InstancePtr is a pointer to the CSI2TX SS Instance to be worked on. Value 1 - ulps mode enter0 - ulps mode exit None None
void XCsi2TxSs_SetClkMode(XCsi2TxSs *InstancePtr, u8 Mode)
This function is used to set the CSI2 Tx Subsystem Clock Mode as either Continuous (0) or Non-Continuous (1) mode.
InstancePtr is a pointer to the Subsystem instance to be worked on. Mode for Continuous Mode (0) or Non-continuous Mode (1) None None
u32 XCsi2TxSs_GetClkMode(XCsi2TxSs *InstancePtr)
This function is used to get the CSI2 Tx Subsystem Clock Mode as either Continuous (0) or Non-Continuous (1) mode.
InstancePtr is a pointer to the Subsystem instance to be worked on. 0 - Continuous Clock Mode 1 - Non-continuous Clock Mode None
u32 XCsi2TxSs_SetLineCountForVC(XCsi2TxSs *InstancePtr, u8 VC, u16 LineCount)
This function sets the Line Count for virtual Channel if Frame End Generation feature is enabled.
This is to be called before starting the core. InstancePtr is a pointer to the Subsystem instance to be worked on. VC is which Virtual channel to be configured for (0-3). LineCount is valid line count for the Virtual channel. XST_NO_FEATURE if Frame End generation is not enabledXST_INVALID_PARAM if any param is invalid e.g. VC is always 0 to 3 and Line Count is 0 to 0xFFFF.XST_FAILURE in case the core is already running.XST_SUCCESS otherwise None.
References XCsi2TxSs::Config, XCsi2TxSs_Config::FEGenEnabled.
u32 XCsi2TxSs_GetLineCountForVC(XCsi2TxSs *InstancePtr, u8 VC, u16 *LineCount)
This function gets the Line Count for virtual Channel if Frame End Generation feature is enabled.
InstancePtr is a pointer to the Subsystem instance to be worked on. VC is which Virtual channel to be configured for (0-3). LineCount is pointer to variable to be filled with line count for the Virtual channel XST_NO_FEATURE if Frame End generation is not enabledXST_INVALID_PARAM if any param is invalid e.g. VC is always 0 to 3 and Line Count is 0 to 0xFFFF.XST_SUCCESS otherwise None.
References XCsi2TxSs::Config, XCsi2TxSs_Config::FEGenEnabled.
XCsi2TxSs_Config * XCsi2TxSs_LookupConfig(UINTPTR BaseAddress)
This function looks for the device configuration based on the unique device ID.
The table XCsi2TxSs_ConfigTable[] contains the configuration information for each instance of the device in the system. DeviceId is the unique device ID of the device being looked up A pointer to the configuration table entry corresponding to the given device ID, or NULL if no match is found None.
Referenced by Csi2TxSs_IntrExample, Csi2TxSs_SelfTestExample.
u32 XCsi2TxSs_GetDrvIndex(XCsi2TxSs *InstancePtr, UINTPTR BaseAddress)
This function returns the Index number of config table using BaseAddress.
A pointer to the instance structure Base address of the instance Index number of the config table
u32 XCsi2TxSs_SelfTest(XCsi2TxSs *InstancePtr)
This function performs self test on MIPI CSI Tx Subsystem sub-cores.
InstancePtr is a pointer to the XCsi2TxSs core instance. XST_SUCCESS if self test passed.XST_FAILURE if self test failed. None.
Referenced by Csi2TxSs_SelfTestExample.
void XCsi2TxSs_IntrHandler(void *InstancePtr)
This function is the interrupt handler for the MIPI CSI2 Tx Subsystem.
The application is responsible for connecting this function to the interrupt system. Application beyond this driver is also responsible for providing callbacks to handle interrupts and installing the callbacks using XCsi2TxSs_SetCallBack() during initialization phase. InstancePtr is a pointer to the XCsi2TxSs core instance that just interrupted. None. None.
Referenced by Csi2TxSs_SetupIntrSystem.
void XCsi2TxSs_IntrDisable(XCsi2TxSs *InstancePtr, u32 IntrMask)
This function is used to disable the interrupts in the CSI core.
InstancePtr is a pointer to the Subsystem instance to be worked on. IntrMask Indicates Mask for enable interrupts. None None
References XCsi2TxSs::Config, XCsi2TxSs_Config::FEGenEnabled.
u32 XCsi2TxSs_SetCallBack(XCsi2TxSs *InstancePtr, u32 HandlerType, void *CallbackFunc, void *CallbackRef)
This routine installs an asynchronous callback function for the given HandlerType:
HandlerType Invoked by this driver when: ------------------------- ------------------------------- (XCSI2TXSS_HANDLER_WRG_LANE) IncorrectLaneCallBack (XCSI2TXSS_HANDLER_GSPFIFO_FULL) GSPFIFOCallBack (XCSI2TXSS_HANDLER_ULPS) DPhyUlpsCallBack (XCSI2TXSS_HANDLER_LINEBUF_FULL) LineBufferCallBack (XCSI2TXSS_HANDLER_WRG_DATATYPE) WrgDataTypeCallBack (XCSI2TXSS_HANDLER_UNDERRUN_PIXEL) UnderrunPixelCallBack (XCSI2TXSS_HANDLER_LCERRVC0 LineCountErrVC0 (XCSI2TXSS_HANDLER_LCERRVC1 LineCountErrVC1 (XCSI2TXSS_HANDLER_LCERRVC2 LineCountErrVC2 (XCSI2TXSS_HANDLER_LCERRVC3 LineCountErrVC3 InstancePtr is the XCsi instance to operate on HandlerType is the type of call back to be registered. CallbackFunc is the pointer to a call back function which is called when a particular event occurs. CallbackRef is a void pointer to data to be referenced to by the CallBackFunc XST_SUCCESS when handler is installed.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XCsi2TxSs::IsReady.
Referenced by Csi2TxSs_SetupIntrSystem.
static u32 XCsi2TxSs_ReadReg(UINTPTR BaseAddress, u32 RegOffset)
This function reads a value from a MIPI CSI2 Tx Subsystem register.
A 32 bit read is performed. If the component is implemented in a smaller width, only the least significant data is read from the register. The most significant data will be read as 0. BaseAddress is the base address of the XCsi2Tx core instance. RegOffset is the register offset of the register (defined at the top of this file). The 32-bit value of the register. None.
static void XCsi2TxSs_WriteReg(UINTPTR BaseAddress, u32 RegOffset, u32 Data)
This function writes a value to a MIPI CSI2 Tx Subsystem register.
A 32 bit write is performed. If the component is implemented in a smaller width, only the least significant data is written. BaseAddress is the base address of the XCsi2Tx core instance. RegOffset is the register offset of the register (defined at the top of this file) to be written. Data is the 32-bit value to write into the register. None. None.
u32 Csi2TxSs_IntrExample(u32 DeviceId)
This function is the main entry point for the interrupt example using the XCsi2TxSs driver.
This function will set up the system with interrupts handlers. DeviceId is the unique device ID of the MIPI CSI2Tx Subsystem core. XST_FAILURE if the system setup failed.XST_SUCCESS should never return since this function, if setup was successful, is blocking. If system setup was successful, this function is blocking in order to illustrate interrupt handling.
References XCsi2TxSs_Config::BaseAddr, Csi2TxSs_PlatformInit, Csi2TxSs_SetupIntrSystem, XCsi2TxSs_Activate, XCsi2TxSs_CfgInitialize, XCsi2TxSs_Configure, XCsi2TxSs_LookupConfig, XCsi2TxSs_ReportCoreInfo, XCsi2TxSs_Reset.
Referenced by main.
u32 Csi2TxSs_PlatformInit(void)
This function initialize required platform-specifc peripherals.
None. XST_SUCCESS if required peripherals are initialized and configured successfully.XST_FAILURE, otherwise. None.
Referenced by Csi2TxSs_IntrExample.
u32 Csi2TxSs_SetupIntrSystem(XINTC *IntcInstPtr)
This function sets up the interrupt system so interrupts can occur for the MIPI CSI2Tx Subsystem core.
The function is application-specific since the actual system may or may not have an interrupt controller. The MIPI CSI Subsystem core could be directly connected to a processor without an interrupt controller. The user should modify this function to fit the application. IntcInstPtr is a pointer to interrupt controller XST_SUCCESS if interrupt setup was successful.A specific error code defined in "xstatus.h" if an error occurs. None.
References Csi2TxSs_GSPFullEventHandler, Csi2TxSs_LinebufEventHandler, Csi2TxSs_UlpsEventHandler, Csi2TxSs_UrunPixelEventHandler, Csi2TxSs_WrgDTypeEventHandler, Csi2TxSs_WrgLaneEventHandler, XCsi2TxSs_IntrHandler, XCsi2TxSs_SetCallBack.
Referenced by Csi2TxSs_IntrExample.
void Csi2TxSs_WrgLaneEventHandler(void *InstancePtr, u32 Mask)
This function is called when Wrong number of lanes are configured by the MIPI CSI2Tx Subsystem core.
InstancePtr is a pointer to the XCsi2TxSs instance. Mask of interrupt which caused this event None. Use the XCsi2TxSs_SetCallback driver function to set this function as the handler for wrong lane configuration event.
Referenced by Csi2TxSs_SetupIntrSystem.
void Csi2TxSs_GSPFullEventHandler(void *InstancePtr, u32 Mask)
This function is called when Generic Short Packet FIFO is found full by the MIPI CSI2Tx Subsystem core.
InstancePtr is a pointer to the XCsi2TxSs instance. Mask of interrupt which caused this event None. Use the XCsi2TxSs_SetCallback driver function to set this function as the handler for Packet level error event.
Referenced by Csi2TxSs_SetupIntrSystem.
void Csi2TxSs_UlpsEventHandler(void *InstancePtr, u32 Mask)
This function is called when there is a change in ULPS state of D-PHY Lanes.
InstancePtr is a pointer to the XCsi2TxSs instance. Mask of interrupt which caused this event None. Use the XCsi2TxSs_SetCallback driver function to set this function as the handler for ULPS mode detection event.
Referenced by Csi2TxSs_SetupIntrSystem.
void Csi2TxSs_LinebufEventHandler(void *InstancePtr, u32 Mask)
This function is called when a Line buffer is full event received by MIPI CSI2Tx Subsystem core.
InstancePtr is a pointer to the XCsi2TxSs instance. Mask of interrupt which caused this event None. Use the XCsi2TxSs_SetCallback driver function to set this function as the handler for Line buffer full event.
Referenced by Csi2TxSs_SetupIntrSystem.
void Csi2TxSs_WrgDTypeEventHandler(void *InstancePtr, u32 Mask)
This function is called when a event generated by unsupported data type in GSP request to the MIPI CSI2Tx Subsystem core.
InstancePtr is a pointer to the XCsi2TxSs instance. Mask of interrupt which caused this event None. Use the XCsi2TxSs_SetCallback driver function to set this function as the handler for Short Packet FIFO error event.
Referenced by Csi2TxSs_SetupIntrSystem.
void Csi2TxSs_UrunPixelEventHandler(void *InstancePtr, u32 Mask)
This function is called when during packet transmission, byte stream FIFO is found to be starves for pixel by the MIPI CSI2Tx Subsystem core.
InstancePtr is a pointer to the XCsi2TxSs instance. Mask of interrupt which caused this event None. Use the XCsi2TxSs_SetCallback driver function to set this function as the handler for Byte stream FIFO starve event.
Referenced by Csi2TxSs_SetupIntrSystem.
static void Delay(u32 Seconds)
For Microblaze we use an assembly loop that is roughly the same regardless of optimization level, although caches and memory access time can make the delay vary.
Just keep in mind that after resetting or updating the PHY modes, the PHY typically needs time to recover. Number of seconds to sleep None None
int main()
This is the main function for XCsi2TxSs interrupt example.
This is the main function for XCsi2TxSs self test example.If the Csi2TxSs_IntrExample function which sets up the system succeeds, this function will wait for the interrupts. Once a connection event or pulse is detected, Csi2TxSs will TX device capabilities and re-start the subsystem. None. XST_FAILURE if the interrupt example was unsuccessful.XST_SUCCESS if the interrupt example was successful. None. XST_SUCCESS if the self test example passed.XST_FAILURE if the self test example was unsuccessful. None.
References Csi2TxSs_IntrExample.
u32 Csi2TxSs_SelfTestExample(u32 DeviceId)
This function is the main entry point for the self test example using the XCsi2TxSs driver.
This function check whether or not its sub-core drivers self test functions are in working state. DeviceId is the unique device ID of the MIPI CSI2 TX Subsystem core. XST_FAILURE if any of MIPI CSI2 TX Subsystem sub-core self test failed.XST_SUCCESS, if all of MIPI CSI2 TX Subsystem sub-core self test passed. None.
References XCsi2TxSs_Config::BaseAddr, XCsi2TxSs_CfgInitialize, XCsi2TxSs_LookupConfig, XCsi2TxSs_SelfTest.
XCSI2TXSS_H_
Prevent circular inclusions by using protection macros.
XCSI2TXSS_MAX_VC
XCSI2TXSS_HW_H_
Prevent circular inclusions by using protection macros.
XCSI2TXSS_ISR_ALLINTR_MASK
XCSI2TXSS_LCSTAT_VC0_IER_MASK
XCSI2TXSS_LCSTAT_VC1_IER_MASK
XCSI2TXSS_LCSTAT_VC2_IER_MASK
XCSI2TXSS_LCSTAT_VC3_IER_MASK
XINTC_DEVICE_ID
XINTC_CSI2TXSS_CSI_INTERRUPT_ID
XINTC
XINTC_HANDLER
XCSI2TXSS_DEVICE_ID
MAX_INTERRUPT_COUNT
XCSI2TXSS_BASE