xcsi2txss.c
XCsi2TxSs_SubCores Csi2TxSsSubCores[][]
static void Csi2TxSs_GetIncludedSubCores(XCsi2TxSs *Csi2TxSsPtr)
This function queries the subsystem instance configuration to determine the included sub-cores.
For each sub-core that is present in the design the sub-core driver instance is binded with the subsystem sub-core driver handle CsiSsPtr is a pointer to the Subsystem instance to be worked. None None
static u32 Csi2TxSs_SubCoreInitCsi(XCsi2TxSs *CsiSsPtr)
This function initializes the included sub-core to it's static configuration.
CsiSsPtr is a pointer to the Subsystem instance to be worked. XST_SUCCESS If CSI sub core is initialised successfullyXST_FAILURE If CSI sub core inititlization fails None
static u32 Csi2TxSs_ComputeSubCoreAbsAddr(UINTPTR SsBaseAddr, UINTPTR SsHighAddr, u32 Offset, UINTPTR *BaseAddr)
This function computes the subcore absolute address on axi-lite interface Subsystem is mapped at an absolute address and all included sub-cores are at pre-defined offset from the subsystem base address.
To access the subcore register map from host CPU an absolute address is required. The subsystem is aligned to 4K address and has address range of max 8K (0x00000-0x2000). By default, CSI is at offset 0x0_0000, and DPHY is at offset 0x0_1000. SsBaseAddr is the base address of the the Subsystem instance SsHighAddr is the max address of the Subsystem instance Offset is the offset of the specified core BaseAddr is the computed absolute base address of the subcore XST_SUCCESS if base address computation is successful and within subsystem address rangeXST_FAILURE Otherwise None
u32 XCsi2TxSs_CfgInitialize(XCsi2TxSs *InstancePtr, XCsi2TxSs_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the MIPI CSI subsystem and included sub-cores.
This function must be called prior to using the subsystem. Initialization includes setting up the instance data for top level as well as all included sub-core therein, and ensuring the hardware is in a known stable state. InstancePtr is a pointer to the Subsystem instance to be worked on. CfgPtr points to the configuration structure associated with the subsystem instance. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if initialization is successfulXST_FAILURE, otherwise None.
References XCsi2TxSs_Config::BaseAddr, XCsi2TxSs::Config, XCsi2TxSs_Config::IsDphyRegIntfcPresent, XCsi2TxSs::IsReady.
Referenced by Csi2TxSs_IntrExample, Csi2TxSs_SelfTestExample.
u32 XCsi2TxSs_Configure(XCsi2TxSs *InstancePtr, u8 ActiveLanes, u32 IntrMask)
This function is used to configure the CSI lanes and interrupts that are to be handled by the application.
Refer to XCsi2Tx.h for interrupt masks. InstancePtr is a pointer to the Subsystem instance to be worked on. ActiveLanes is no of active lanes to be configure. This value ranges between 1 and 4. IntrMask Indicates Mask for enable interrupts. XST_SUCCESS on successful configuration of parameters XST_FAILURE otherwise When EnableActiveLanes is 0, then the ActiveLanes parameter passed should be equal to Max Lanes of design.
References XCsi2TxSs::Config, XCsi2TxSs_Config::FEGenEnabled.
Referenced by Csi2TxSs_IntrExample.
u32 XCsi2TxSs_Activate(XCsi2TxSs *InstancePtr, u8 Flag)
This function is used to activate the CSI Subsystem.
Internally it activates the DPHY and CSI. InstancePtr is a pointer to the Subsystem instance to be worked on. Flag is used to denote whether to enable or disable the subsystem XST_SUCCESS on successful operationXST_FAILURE on failed operation None
References XCsi2TxSs::Config, XCsi2TxSs_Config::IsDphyRegIntfcPresent.
Referenced by Csi2TxSs_IntrExample.
u32 XCsi2TxSs_Reset(XCsi2TxSs *InstancePtr)
This function is used to reset the CSI Subsystem.
Internally it resets the DPHY and CSI InstancePtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS if all the sub core IP resets occur correctlyXST_FAILURE if reset fails for any sub core IP fails None
Referenced by Csi2TxSs_IntrExample.
void XCsi2TxSs_ReportCoreInfo(XCsi2TxSs *InstancePtr)
This function reports list of cores included.
InstancePtr is a pointer to the Subsystem instance to be worked on. None None
References XCsi2TxSs::Config, XCsi2TxSs_Config::IsDphyRegIntfcPresent.
Referenced by Csi2TxSs_IntrExample.
void XCsi2TxSs_GetShortPacket(XCsi2TxSs *InstancePtr)
This function gets the short packets.
InstancePtr is a pointer to the Subsystem instance to be worked on. None None
References XCsi2TxSs::SpktData.
void XCsi2TxSs_LineGen(XCsi2TxSs *InstancePtr, u32 Value)
This function is to set the Line Synchronization packet Generation status.
InstancePtr is a pointer to the CSI2 TX SS Instance to be worked on. Value 0 : DISABLE 1 : ENABLE None None
void XCsi2TxSs_SetGSPEntry(XCsi2TxSs *InstancePtr, u32 Value)
This function is to set Generic Short Packet Entries.
InstancePtr is a pointer to the CSI2 TX SS Instance to be worked on. Value GSP 32 bit Entry None None
u32 XCsi2TxSs_GetPixelMode(XCsi2TxSs *InstancePtr)
This function is used to get the Pixel Mode.
InstancePtr is a pointer to the CSI2TX SS Instance to be worked on. 0x0 - Single Pixel Mode 0x1 - Dual Pixel Mode 0x3 - Quad Pixel Mode None
u32 XCsi2TxSs_GetMaxLaneCount(XCsi2TxSs *InstancePtr)
This function is used to get the number of lanes configured in the IP.
InstancePtr is a pointer to the CSI2TX SS Instance to be worked on. Max number of lanes available in u32 format None
u32 XCsi2TxSs_IsUlps(XCsi2TxSs *InstancePtr)
This function is used to check if lanes are in ulps mode.
InstancePtr is a pointer to the CSI2TX SS Instance to be worked on. 1 - ulps mode enter0 - ulps mode exit None
void XCsi2TxSs_SetUlps(XCsi2TxSs *InstancePtr, u32 Value)
This function is used to set lanes in ulps mode.
InstancePtr is a pointer to the CSI2TX SS Instance to be worked on. Value 1 - ulps mode enter0 - ulps mode exit None None
void XCsi2TxSs_SetClkMode(XCsi2TxSs *InstancePtr, u8 Mode)
This function is used to set the CSI2 Tx Subsystem Clock Mode as either Continuous (0) or Non-Continuous (1) mode.
InstancePtr is a pointer to the Subsystem instance to be worked on. Mode for Continuous Mode (0) or Non-continuous Mode (1) None None
u32 XCsi2TxSs_GetClkMode(XCsi2TxSs *InstancePtr)
This function is used to get the CSI2 Tx Subsystem Clock Mode as either Continuous (0) or Non-Continuous (1) mode.
InstancePtr is a pointer to the Subsystem instance to be worked on. 0 - Continuous Clock Mode 1 - Non-continuous Clock Mode None
u32 XCsi2TxSs_SetLineCountForVC(XCsi2TxSs *InstancePtr, u8 VC, u16 LineCount)
This function sets the Line Count for virtual Channel if Frame End Generation feature is enabled.
This is to be called before starting the core. InstancePtr is a pointer to the Subsystem instance to be worked on. VC is which Virtual channel to be configured for (0-3). LineCount is valid line count for the Virtual channel. XST_NO_FEATURE if Frame End generation is not enabledXST_INVALID_PARAM if any param is invalid e.g. VC is always 0 to 3 and Line Count is 0 to 0xFFFF.XST_FAILURE in case the core is already running.XST_SUCCESS otherwise None.
References XCsi2TxSs::Config, XCsi2TxSs_Config::FEGenEnabled.
u32 XCsi2TxSs_GetLineCountForVC(XCsi2TxSs *InstancePtr, u8 VC, u16 *LineCount)
This function gets the Line Count for virtual Channel if Frame End Generation feature is enabled.
InstancePtr is a pointer to the Subsystem instance to be worked on. VC is which Virtual channel to be configured for (0-3). LineCount is pointer to variable to be filled with line count for the Virtual channel XST_NO_FEATURE if Frame End generation is not enabledXST_INVALID_PARAM if any param is invalid e.g. VC is always 0 to 3 and Line Count is 0 to 0xFFFF.XST_SUCCESS otherwise None.
References XCsi2TxSs::Config, XCsi2TxSs_Config::FEGenEnabled.