xcsi2txss.h
XCSI2TXSS_CCM
XCSI2TXSS_NCCM
XCSI2TXSS_HANDLER_WRG_LANE
XCSI2TXSS_HANDLER_GSPFIFO_FULL
XCSI2TXSS_HANDLER_ULPS
XCSI2TXSS_HANDLER_LINEBUF_FULL
XCSI2TXSS_HANDLER_WRG_DATATYPE
XCSI2TXSS_HANDLER_UNDERRUN_PIXEL
XCSI2TXSS_HANDLER_LCERRVC0
XCSI2TXSS_HANDLER_LCERRVC1
XCSI2TXSS_HANDLER_LCERRVC2
XCSI2TXSS_HANDLER_LCERRVC3
XCSI2TXSS_H_
Prevent circular inclusions by using protection macros.
XCSI2TXSS_MAX_VC
XCsi2TxSS_LCStatus
Less no of lines recvd.
typedef void(* XCsi2TxSs_Callback)(void *CallbackRef, u32 Mask))(void *CallbackRef, u32 Mask)
Callback type which acts as a wrapper on top of CSI Callback.
CallbackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. Mask is a bit mask indicating the cause of the event. For current core version, this parameter is "OR" of 0 or more XCSI2TXSS_ISR_*_MASK constants defined in xcsi2txss_hw.h. None. None.
XCsi2TxSs_Config * XCsi2TxSs_LookupConfig(UINTPTR BaseAddress)
This function looks for the device configuration based on the unique device ID.
The table XCsi2TxSs_ConfigTable[] contains the configuration information for each instance of the device in the system. DeviceId is the unique device ID of the device being looked up A pointer to the configuration table entry corresponding to the given device ID, or NULL if no match is found None.
Referenced by Csi2TxSs_IntrExample, Csi2TxSs_SelfTestExample.
u32 XCsi2TxSs_GetDrvIndex(XCsi2TxSs *InstancePtr, UINTPTR BaseAddress)
This function returns the Index number of config table using BaseAddress.
A pointer to the instance structure Base address of the instance Index number of the config table
u32 XCsi2TxSs_CfgInitialize(XCsi2TxSs *InstancePtr, XCsi2TxSs_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the MIPI CSI subsystem and included sub-cores.
This function must be called prior to using the subsystem. Initialization includes setting up the instance data for top level as well as all included sub-core therein, and ensuring the hardware is in a known stable state. InstancePtr is a pointer to the Subsystem instance to be worked on. CfgPtr points to the configuration structure associated with the subsystem instance. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if initialization is successfulXST_FAILURE, otherwise None.
References XCsi2TxSs_Config::BaseAddr, XCsi2TxSs::Config, XCsi2TxSs_Config::IsDphyRegIntfcPresent, XCsi2TxSs::IsReady.
Referenced by Csi2TxSs_IntrExample, Csi2TxSs_SelfTestExample.
u32 XCsi2TxSs_Configure(XCsi2TxSs *InstancePtr, u8 ActiveLanes, u32 IntrMask)
This function is used to configure the CSI lanes and interrupts that are to be handled by the application.
Refer to XCsi2Tx.h for interrupt masks. InstancePtr is a pointer to the Subsystem instance to be worked on. ActiveLanes is no of active lanes to be configure. This value ranges between 1 and 4. IntrMask Indicates Mask for enable interrupts. XST_SUCCESS on successful configuration of parameters XST_FAILURE otherwise When EnableActiveLanes is 0, then the ActiveLanes parameter passed should be equal to Max Lanes of design.
References XCsi2TxSs::Config, XCsi2TxSs_Config::FEGenEnabled.
Referenced by Csi2TxSs_IntrExample.
u32 XCsi2TxSs_Activate(XCsi2TxSs *InstancePtr, u8 Flag)
This function is used to activate the CSI Subsystem.
Internally it activates the DPHY and CSI. InstancePtr is a pointer to the Subsystem instance to be worked on. Flag is used to denote whether to enable or disable the subsystem XST_SUCCESS on successful operationXST_FAILURE on failed operation None
References XCsi2TxSs::Config, XCsi2TxSs_Config::IsDphyRegIntfcPresent.
Referenced by Csi2TxSs_IntrExample.
u32 XCsi2TxSs_Reset(XCsi2TxSs *InstancePtr)
This function is used to reset the CSI Subsystem.
Internally it resets the DPHY and CSI InstancePtr is a pointer to the Subsystem instance to be worked on. XST_SUCCESS if all the sub core IP resets occur correctlyXST_FAILURE if reset fails for any sub core IP fails None
Referenced by Csi2TxSs_IntrExample.
void XCsi2TxSs_ReportCoreInfo(XCsi2TxSs *InstancePtr)
This function reports list of cores included.
InstancePtr is a pointer to the Subsystem instance to be worked on. None None
References XCsi2TxSs::Config, XCsi2TxSs_Config::IsDphyRegIntfcPresent.
Referenced by Csi2TxSs_IntrExample.
void XCsi2TxSs_GetShortPacket(XCsi2TxSs *InstancePtr)
This function gets the short packets.
InstancePtr is a pointer to the Subsystem instance to be worked on. None None
References XCsi2TxSs::SpktData.
void XCsi2TxSs_LineGen(XCsi2TxSs *InstancePtr, u32 Value)
This function is to set the Line Synchronization packet Generation status.
InstancePtr is a pointer to the CSI2 TX SS Instance to be worked on. Value 0 : DISABLE 1 : ENABLE None None
void XCsi2TxSs_SetGSPEntry(XCsi2TxSs *InstancePtr, u32 Value)
This function is to set Generic Short Packet Entries.
InstancePtr is a pointer to the CSI2 TX SS Instance to be worked on. Value GSP 32 bit Entry None None
u32 XCsi2TxSs_GetPixelMode(XCsi2TxSs *InstancePtr)
This function is used to get the Pixel Mode.
InstancePtr is a pointer to the CSI2TX SS Instance to be worked on. 0x0 - Single Pixel Mode 0x1 - Dual Pixel Mode 0x3 - Quad Pixel Mode None
u32 XCsi2TxSs_GetMaxLaneCount(XCsi2TxSs *InstancePtr)
This function is used to get the number of lanes configured in the IP.
InstancePtr is a pointer to the CSI2TX SS Instance to be worked on. Max number of lanes available in u32 format None
void XCsi2TxSs_SetClkMode(XCsi2TxSs *InstancePtr, u8 Mode)
This function is used to set the CSI2 Tx Subsystem Clock Mode as either Continuous (0) or Non-Continuous (1) mode.
InstancePtr is a pointer to the Subsystem instance to be worked on. Mode for Continuous Mode (0) or Non-continuous Mode (1) None None
u32 XCsi2TxSs_GetClkMode(XCsi2TxSs *InstancePtr)
This function is used to get the CSI2 Tx Subsystem Clock Mode as either Continuous (0) or Non-Continuous (1) mode.
InstancePtr is a pointer to the Subsystem instance to be worked on. 0 - Continuous Clock Mode 1 - Non-continuous Clock Mode None
u32 XCsi2TxSs_IsUlps(XCsi2TxSs *InstancePtr)
This function is used to check if lanes are in ulps mode.
InstancePtr is a pointer to the CSI2TX SS Instance to be worked on. 1 - ulps mode enter0 - ulps mode exit None
void XCsi2TxSs_SetUlps(XCsi2TxSs *InstancePtr, u32 Value)
This function is used to set lanes in ulps mode.
InstancePtr is a pointer to the CSI2TX SS Instance to be worked on. Value 1 - ulps mode enter0 - ulps mode exit None None
u32 XCsi2TxSs_SetLineCountForVC(XCsi2TxSs *InstancePtr, u8 VC, u16 LineCount)
This function sets the Line Count for virtual Channel if Frame End Generation feature is enabled.
This is to be called before starting the core. InstancePtr is a pointer to the Subsystem instance to be worked on. VC is which Virtual channel to be configured for (0-3). LineCount is valid line count for the Virtual channel. XST_NO_FEATURE if Frame End generation is not enabledXST_INVALID_PARAM if any param is invalid e.g. VC is always 0 to 3 and Line Count is 0 to 0xFFFF.XST_FAILURE in case the core is already running.XST_SUCCESS otherwise None.
References XCsi2TxSs::Config, XCsi2TxSs_Config::FEGenEnabled.
u32 XCsi2TxSs_GetLineCountForVC(XCsi2TxSs *InstancePtr, u8 VC, u16 *LineCount)
This function gets the Line Count for virtual Channel if Frame End Generation feature is enabled.
InstancePtr is a pointer to the Subsystem instance to be worked on. VC is which Virtual channel to be configured for (0-3). LineCount is pointer to variable to be filled with line count for the Virtual channel XST_NO_FEATURE if Frame End generation is not enabledXST_INVALID_PARAM if any param is invalid e.g. VC is always 0 to 3 and Line Count is 0 to 0xFFFF.XST_SUCCESS otherwise None.
References XCsi2TxSs::Config, XCsi2TxSs_Config::FEGenEnabled.
u32 XCsi2TxSs_SelfTest(XCsi2TxSs *InstancePtr)
This function performs self test on MIPI CSI Tx Subsystem sub-cores.
InstancePtr is a pointer to the XCsi2TxSs core instance. XST_SUCCESS if self test passed.XST_FAILURE if self test failed. None.
Referenced by Csi2TxSs_SelfTestExample.
void XCsi2TxSs_IntrHandler(void *InstancePtr)
This function is the interrupt handler for the MIPI CSI2 Tx Subsystem.
The application is responsible for connecting this function to the interrupt system. Application beyond this driver is also responsible for providing callbacks to handle interrupts and installing the callbacks using XCsi2TxSs_SetCallBack() during initialization phase. InstancePtr is a pointer to the XCsi2TxSs core instance that just interrupted. None. None.
Referenced by Csi2TxSs_SetupIntrSystem.
void XCsi2TxSs_IntrDisable(XCsi2TxSs *InstancePtr, u32 IntrMask)
This function is used to disable the interrupts in the CSI core.
InstancePtr is a pointer to the Subsystem instance to be worked on. IntrMask Indicates Mask for enable interrupts. None None
References XCsi2TxSs::Config, XCsi2TxSs_Config::FEGenEnabled.
u32 XCsi2TxSs_SetCallBack(XCsi2TxSs *InstancePtr, u32 HandlerType, void *CallbackFunc, void *CallbackRef)
This routine installs an asynchronous callback function for the given HandlerType:
HandlerType Invoked by this driver when: ------------------------- ------------------------------- (XCSI2TXSS_HANDLER_WRG_LANE) IncorrectLaneCallBack (XCSI2TXSS_HANDLER_GSPFIFO_FULL) GSPFIFOCallBack (XCSI2TXSS_HANDLER_ULPS) DPhyUlpsCallBack (XCSI2TXSS_HANDLER_LINEBUF_FULL) LineBufferCallBack (XCSI2TXSS_HANDLER_WRG_DATATYPE) WrgDataTypeCallBack (XCSI2TXSS_HANDLER_UNDERRUN_PIXEL) UnderrunPixelCallBack (XCSI2TXSS_HANDLER_LCERRVC0 LineCountErrVC0 (XCSI2TXSS_HANDLER_LCERRVC1 LineCountErrVC1 (XCSI2TXSS_HANDLER_LCERRVC2 LineCountErrVC2 (XCSI2TXSS_HANDLER_LCERRVC3 LineCountErrVC3 InstancePtr is the XCsi instance to operate on HandlerType is the type of call back to be registered. CallbackFunc is the pointer to a call back function which is called when a particular event occurs. CallbackRef is a void pointer to data to be referenced to by the CallBackFunc XST_SUCCESS when handler is installed.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XCsi2TxSs::IsReady.
Referenced by Csi2TxSs_SetupIntrSystem.