xcsi2txss_intr_example.c
XINTC_DEVICE_ID
XINTC_CSI2TXSS_CSI_INTERRUPT_ID
XINTC
XINTC_HANDLER
XCSI2TXSS_DEVICE_ID
MAX_INTERRUPT_COUNT
XCsi2TxSs Csi2TxSsInst
volatile u32 interrupt_counts
u32 Csi2TxSs_IntrExample(u32 DeviceId)
This function is the main entry point for the interrupt example using the XCsi2TxSs driver.
This function will set up the system with interrupts handlers. DeviceId is the unique device ID of the MIPI CSI2Tx Subsystem core. XST_FAILURE if the system setup failed.XST_SUCCESS should never return since this function, if setup was successful, is blocking. If system setup was successful, this function is blocking in order to illustrate interrupt handling.
References XCsi2TxSs_Config::BaseAddr, Csi2TxSs_PlatformInit, Csi2TxSs_SetupIntrSystem, XCsi2TxSs_Activate, XCsi2TxSs_CfgInitialize, XCsi2TxSs_Configure, XCsi2TxSs_LookupConfig, XCsi2TxSs_ReportCoreInfo, XCsi2TxSs_Reset.
Referenced by main.
u32 Csi2TxSs_PlatformInit(void)
This function initialize required platform-specifc peripherals.
None. XST_SUCCESS if required peripherals are initialized and configured successfully.XST_FAILURE, otherwise. None.
Referenced by Csi2TxSs_IntrExample.
u32 Csi2TxSs_SetupIntrSystem(XINTC *IntcInstPtr)
This function sets up the interrupt system so interrupts can occur for the MIPI CSI2Tx Subsystem core.
The function is application-specific since the actual system may or may not have an interrupt controller. The MIPI CSI Subsystem core could be directly connected to a processor without an interrupt controller. The user should modify this function to fit the application. IntcInstPtr is a pointer to interrupt controller XST_SUCCESS if interrupt setup was successful.A specific error code defined in "xstatus.h" if an error occurs. None.
References Csi2TxSs_GSPFullEventHandler, Csi2TxSs_LinebufEventHandler, Csi2TxSs_UlpsEventHandler, Csi2TxSs_UrunPixelEventHandler, Csi2TxSs_WrgDTypeEventHandler, Csi2TxSs_WrgLaneEventHandler, XCsi2TxSs_IntrHandler, XCsi2TxSs_SetCallBack.
Referenced by Csi2TxSs_IntrExample.
void Csi2TxSs_WrgLaneEventHandler(void *InstancePtr, u32 Mask)
This function is called when Wrong number of lanes are configured by the MIPI CSI2Tx Subsystem core.
InstancePtr is a pointer to the XCsi2TxSs instance. Mask of interrupt which caused this event None. Use the XCsi2TxSs_SetCallback driver function to set this function as the handler for wrong lane configuration event.
Referenced by Csi2TxSs_SetupIntrSystem.
void Csi2TxSs_GSPFullEventHandler(void *InstancePtr, u32 Mask)
This function is called when Generic Short Packet FIFO is found full by the MIPI CSI2Tx Subsystem core.
InstancePtr is a pointer to the XCsi2TxSs instance. Mask of interrupt which caused this event None. Use the XCsi2TxSs_SetCallback driver function to set this function as the handler for Packet level error event.
Referenced by Csi2TxSs_SetupIntrSystem.
void Csi2TxSs_UlpsEventHandler(void *InstancePtr, u32 Mask)
This function is called when there is a change in ULPS state of D-PHY Lanes.
InstancePtr is a pointer to the XCsi2TxSs instance. Mask of interrupt which caused this event None. Use the XCsi2TxSs_SetCallback driver function to set this function as the handler for ULPS mode detection event.
Referenced by Csi2TxSs_SetupIntrSystem.
void Csi2TxSs_LinebufEventHandler(void *InstancePtr, u32 Mask)
This function is called when a Line buffer is full event received by MIPI CSI2Tx Subsystem core.
InstancePtr is a pointer to the XCsi2TxSs instance. Mask of interrupt which caused this event None. Use the XCsi2TxSs_SetCallback driver function to set this function as the handler for Line buffer full event.
Referenced by Csi2TxSs_SetupIntrSystem.
void Csi2TxSs_WrgDTypeEventHandler(void *InstancePtr, u32 Mask)
This function is called when a event generated by unsupported data type in GSP request to the MIPI CSI2Tx Subsystem core.
InstancePtr is a pointer to the XCsi2TxSs instance. Mask of interrupt which caused this event None. Use the XCsi2TxSs_SetCallback driver function to set this function as the handler for Short Packet FIFO error event.
Referenced by Csi2TxSs_SetupIntrSystem.
void Csi2TxSs_UrunPixelEventHandler(void *InstancePtr, u32 Mask)
This function is called when during packet transmission, byte stream FIFO is found to be starves for pixel by the MIPI CSI2Tx Subsystem core.
InstancePtr is a pointer to the XCsi2TxSs instance. Mask of interrupt which caused this event None. Use the XCsi2TxSs_SetCallback driver function to set this function as the handler for Byte stream FIFO starve event.
Referenced by Csi2TxSs_SetupIntrSystem.
static void Delay(u32 Seconds)
For Microblaze we use an assembly loop that is roughly the same regardless of optimization level, although caches and memory access time can make the delay vary.
Just keep in mind that after resetting or updating the PHY modes, the PHY typically needs time to recover. Number of seconds to sleep None None
int main()
This is the main function for XCsi2TxSs interrupt example.
This is the main function for XCsi2TxSs self test example.If the Csi2TxSs_IntrExample function which sets up the system succeeds, this function will wait for the interrupts. Once a connection event or pulse is detected, Csi2TxSs will TX device capabilities and re-start the subsystem. None. XST_FAILURE if the interrupt example was unsuccessful.XST_SUCCESS if the interrupt example was successful. None. XST_SUCCESS if the self test example passed.XST_FAILURE if the self test example was unsuccessful. None.
References Csi2TxSs_IntrExample.