iomodule
typedef void(* XIOModule_Handler)(void *CallBackRef, unsigned int ByteCount))(void *CallBackRef, unsigned int ByteCount)
Callback function.
The first argument is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. The second argument is the ByteCount which is the number of bytes that actually moved from/to the buffer provided in the _Send/_Receive call.
typedef void(* XIOModule_Timer_Handler)(void *CallBackRef, u8 TimerNumber))(void *CallBackRef, u8 TimerNumber)
Signature for the timer callback function.
CallBackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. Its type is unimportant to the driver, so it is a void pointer. TimerNumber is the number of the timer within the device. The device typically contains from one to four timers. The timer number is a zero based number with a range of 0 to (XTC_DEVICE_TIMER_COUNT - 1).
typedef void(* XFastInterruptHandler)(void))(void)
typedef void(* Handler)(XIOModule *InstancePtr))(XIOModule *InstancePtr)
u32 XIOModule_BitPosMask[XPAR_IOMODULE_INTC_MAX_INTR_SIZE][XPAR_IOMODULE_INTC_MAX_INTR_SIZE]
XIOModule_Config XIOModule_ConfigTable[XPAR_XIOMODULE_NUM_INSTANCES][XPAR_XIOMODULE_NUM_INSTANCES]
This table contains configuration information for each iomodule device in the system.
The XIOModule driver must know when to acknowledge the interrupt. The entry which specifies this as a bit mask where each bit corresponds to a specific interrupt. A bit set indicates to ack it before servicing it. Generally, acknowledge before service is used when the interrupt signal is edge-sensitive, and after when the signal is level-sensitive.Refer to the XIOModule_Config data structure in xiomodule.h for details on how this table should be initialized.
Referenced by XIOModule_DeviceInterruptHandler, XIOModule_LookupConfig.
u32 XIOModule_BitPosMask[][]
XIOModule_Config XIOModule_ConfigTable[][]
This table contains configuration information for each iomodule device in the system.
The XIOModule driver must know when to acknowledge the interrupt. The entry which specifies this as a bit mask where each bit corresponds to a specific interrupt. A bit set indicates to ack it before servicing it. Generally, acknowledge before service is used when the interrupt signal is edge-sensitive, and after when the signal is level-sensitive.Refer to the XIOModule_Config data structure in xiomodule.h for details on how this table should be initialized.
Referenced by XIOModule_DeviceInterruptHandler, XIOModule_LookupConfig.
u32 XIOModule_TimerBitPosMask[XTC_DEVICE_TIMER_COUNT][XTC_DEVICE_TIMER_COUNT]
static void StubHandler(void *CallBackRef)
A stub for the asynchronous callback.
The stub is here in case the upper layers forget to set the handler. CallBackRef is a pointer to the upper layer callback reference None. None.
s32 XIOModule_Initialize(XIOModule *InstancePtr, u32 BaseAddress)
Initialize a specific interrupt controller instance/driver.
The initialization entails: - Initialize fields of the XIOModule structure - Initial vector table with stub function calls - All interrupt sources are disabled - Interrupt output is disabled - All timers are initialized InstancePtr is a pointer to the XIOModule instance to be worked on. BaseAddress is the base address of the device XST_SUCCESS if initialization was successfulXST_DEVICE_IS_STARTED if the device has already been startedXST_DEVICE_NOT_FOUND if device configuration information was not found for a device with the supplied device ID/BaseAddress. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XIOModule_Config::BaseAddress, XIOModule::BaseAddress, XIOModule_Config::BaseVector, XIOModule::CfgPtr, XIOModule::CurrentIER, XIOModule::CurrentIMR, XIOModule_Config::FastIntr, XIOModule_Config::GpoInit, XIOModule::GpoValue, XIOModule_Config::IoBaseAddress, XIOModule::IoBaseAddress, XIOModule::IsReady, XIOModule::IsStarted, XIOModule_Config::Options, XIOModule_Config::VectorAddrWidth, XIOModule_CfgInitialize, XIOModule_HandlerTable_Initialize, XIOModule_LookupConfig, XIOModule_Timer_Initialize.
Referenced by IOModuleInterruptSetup, IOModuleIntrExample, IOModuleSelfTestExample.
void XIOModule_HandlerTable_Initialize(XIOModule *InstancePtr)
Initializes all interrupt handlers to default handler for each interrupt ID.
It is necessary for the caller to connect the interrupt handler of this component to the proper interrupt source. InstancePtr is a pointer to the XIOModule instance to be worked on. None. None.
References XIOModule_VectorTableEntry::CallBackRef, XIOModule::CfgPtr, XIOModule_VectorTableEntry::Handler, XIOModule_Config::HandlerTable.
Referenced by XIOModule_Initialize.
s32 XIOModule_Start(XIOModule *InstancePtr)
Starts the IO Module.
Interrupts may be generated by the IO Module after this function is called.It is necessary for the caller to connect the interrupt handler of this component to the proper interrupt source. InstancePtr is a pointer to the XIOModule instance to be worked on. XST_SUCCESS if the device was started successfullyXST_FAILURE if simulation mode was specified and it could not be set because real mode has already been entered. Must be called after XIOModule initialization is completed.
References XIOModule::IsReady, XIOModule::IsStarted.
Referenced by IOModuleInterruptSetup.
void XIOModule_Stop(XIOModule *InstancePtr)
Stops the interrupt controller by disabling the output from the controller so that no interrupts will be caused by the interrupt controller.
InstancePtr is a pointer to the XIOModule instance to be worked on. None. None.
References XIOModule::IsReady, XIOModule::IsStarted.
s32 XIOModule_Connect(XIOModule *InstancePtr, u8 Id, XInterruptHandler Handler, void *CallBackRef)
Makes the connection between the Id of the interrupt source and the associated handler that is to run when the interrupt is recognized.
The argument provided in this call as the Callbackref is used as the argument for the handler when it is called. InstancePtr is a pointer to the XIOModule instance to be worked on. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_IOMODULE_INTC_MAX_INTR_SIZE - 1 with 0 being the highest priority interrupt. Handler to the handler for that interrupt. CallBackRef is the callback reference, usually the instance pointer of the connecting driver. XST_SUCCESS if the handler was connected correctly. Only used with normal interrupt mode. Does not restore normal interrupt mode. WARNING: The handler provided as an argument will overwrite any handler that was previously connected.
References XIOModule_VectorTableEntry::CallBackRef, XIOModule::CfgPtr, XIOModule_VectorTableEntry::Handler, XIOModule_Config::HandlerTable, XIOModule::IsReady.
void XIOModule_Disconnect(XIOModule *InstancePtr, u8 Id)
Updates the interrupt table with the Null Handler and NULL arguments at the location pointed at by the Id.
This effectively disconnects that interrupt source from any handler. The interrupt is disabled also. InstancePtr is a pointer to the XIOModule instance to be worked on. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_IOMODULE_INTC_MAX_INTR_SIZE - 1 with 0 being the highest priority interrupt. None. None.
References XIOModule::BaseAddress, XIOModule_VectorTableEntry::CallBackRef, XIOModule::CfgPtr, XIOModule::CurrentIER, XIOModule_VectorTableEntry::Handler, XIOModule_Config::HandlerTable, XIOModule::IsReady.
void XIOModule_Enable(XIOModule *InstancePtr, u8 Id)
Enables the interrupt source provided as the argument Id.
Any pending interrupt condition for the specified Id will occur after this function is called. InstancePtr is a pointer to the XIOModule instance to be worked on. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_IOMODULE_INTC_MAX_INTR_SIZE - 1 with 0 being the highest priority interrupt. None. None.
References XIOModule::BaseAddress, XIOModule::CurrentIER, XIOModule::IsReady.
Referenced by IOModuleIntrExample.
void XIOModule_Disable(XIOModule *InstancePtr, u8 Id)
Disables the interrupt source provided as the argument Id such that the interrupt controller will not cause interrupts for the specified Id.
The interrupt controller will continue to hold an interrupt condition for the Id, but will not cause an interrupt. InstancePtr is a pointer to the XIOModule instance to be worked on. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_IOMODULE_INTC_MAX_INTR_SIZE - 1 with 0 being the highest priority interrupt. None. None.
References XIOModule::BaseAddress, XIOModule::CurrentIER, XIOModule::IsReady.
Referenced by IOModuleDisableIntr.
void XIOModule_Acknowledge(XIOModule *InstancePtr, u8 Id)
Acknowledges the interrupt source provided as the argument Id.
When the interrupt is acknowledged, it causes the interrupt controller to clear its interrupt condition. InstancePtr is a pointer to the XIOModule instance to be worked on. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_IOMODULE_INTC_MAX_INTR_SIZE - 1 with 0 being the highest priority interrupt. None. None.
References XIOModule::BaseAddress, XIOModule::IsReady.
XIOModule_Config * XIOModule_LookupConfig(u32 BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
A table contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the XIOModule configuration structure for the specified device, or NULL if the device ID/BaseAddress was not found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XIOModule_ConfigTable.
Referenced by XIOModule_DeviceInterruptHandler, XIOModule_Initialize, XIOModule_Timer_Initialize.
s32 XIOModule_ConnectFastHandler(XIOModule *InstancePtr, u8 Id, XFastInterruptHandler Handler)
Makes the connection between the Id of the interrupt source and the associated handler that is to run when the interrupt is recognized.
InstancePtr is a pointer to the XIOModule instance. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_INTC_MAX_NUM_INTR_INPUTS - 1 with 0 being the highest priority interrupt. Handler to the handler for that interrupt. XST_SUCCESS if the handler was connected correctly. Only used with fast interrupt mode. WARNING: The handler provided as an argument will overwrite any handler that was previously connected.
References XIOModule::BaseAddress, XIOModule_VectorTableEntry::CallBackRef, XIOModule::CfgPtr, XIOModule::CurrentIER, XIOModule::CurrentIMR, XIOModule_Config::FastIntr, XIOModule_VectorTableEntry::Handler, XIOModule_Config::HandlerTable, XIOModule::IsReady, XIOModule_Config::VectorAddrWidth.
void XIOModule_SetNormalIntrMode(XIOModule *InstancePtr, u8 Id)
Sets the normal interrupt mode for the specified interrupt in the Interrupt Mode Register, by resetting the vector to (BaseVector & 0xFFFFFF80) | 0x10 and selecting normal mode.
InstancePtr is a pointer to the XIOModule instance. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_INTC_MAX_NUM_INTR_INPUTS - 1 with 0 being the highest priority interrupt. None. Only used with fast interrupt mode.
References XIOModule::BaseAddress, XIOModule_Config::BaseVector, XIOModule_VectorTableEntry::CallBackRef, XIOModule::CfgPtr, XIOModule::CurrentIER, XIOModule::CurrentIMR, XIOModule_Config::FastIntr, XIOModule_VectorTableEntry::Handler, XIOModule_Config::HandlerTable, XIOModule::IsReady, XIOModule_Config::VectorAddrWidth.
u32 XIOModule_DiscreteRead(XIOModule *InstancePtr, u32 Channel)
Read state of discretes for the specified GPI channel.
InstancePtr is a pointer to an XIOModule instance to be worked on. Channel contains the channel of the GPI (1, 2, 3 or 4) to operate on. Current copy of the discretes register.
References XIOModule::BaseAddress, XIOModule::IsReady, XIOModule_ReadReg.
void XIOModule_DiscreteWrite(XIOModule *InstancePtr, u32 Channel, u32 Data)
Write to discretes register for the specified GPO channel.
InstancePtr is a pointer to an XIOModule instance to be worked on. Channel contains the channel of the GPO (1, 2, 3 or 4) to operate on. Data is the value to be written to the discretes register. None.
References XIOModule::BaseAddress, XIOModule::GpoValue, XIOModule::IsReady, XIOModule_WriteReg.
s32 XIOModule_Timer_Initialize(XIOModule *InstancePtr, u32 BaseAddress)
Initializes a specific timer instance/driver.
Initialize fields of the XIOModule structure, then reset the timer InstancePtr is a pointer to the XIOModule instance. BaseAddress is the base address of the device XST_SUCCESS if initialization was successfulXST_DEVICE_IS_STARTED if the device has already been startedXST_DEVICE_NOT_FOUND if the device doesn't exist In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XIOModule_Config::BaseAddress, XIOModule::BaseAddress, XIOModule::CallBackRef, XIOModule::CurrentTCSR, XIOModule::CurrentTLR, XIOModule::Handler, XIOModule_Timer_Stats::Interrupts, XIOModule::IsReady, XIOModule::Timer_Stats, XIOModule_LookupConfig, XIOModule_WriteReg.
Referenced by XIOModule_Initialize.
void XIOModule_Timer_Start(XIOModule *InstancePtr, u8 TimerNumber)
Starts the specified timer counter of the device such that it starts running.
The timer counter is reset before it is started and the reset value is loaded into the timer counter.If interrupt mode is specified in the options, it is necessary for the caller to connect the interrupt handler of the timer to the interrupt source, typically an interrupt controller, and enable the interrupt within the interrupt controller. InstancePtr is a pointer to the XIOModule instance. TimerNumber is the timer of the device to operate on. Each device may contain multiple timers. The timer number is a zero based number with a range of 0 to (XTC_DEVICE_TIMER_COUNT - 1). None. None.
References XIOModule::BaseAddress, XIOModule::CurrentTCSR, XIOModule::IsReady, XIOModule_WriteReg.
Referenced by IOModuleIntrExample, XIOModule_Timer_SelfTest.
void XIOModule_Timer_Stop(XIOModule *InstancePtr, u8 TimerNumber)
Stops the timer by disabling it.
It is the callers' responsibility to disconnect the interrupt handler of the timer from the interrupt source, typically an interrupt controller, and disable the interrupt within the interrupt controller. InstancePtr is a pointer to the XIOModule instance. TimerNumber is the timer counter of the device to operate on. Each device may contain multiple timer counters. The timer number is a zero based number with a range of 0 to (XTC_DEVICE_TIMER_COUNT - 1). None. None.
References XIOModule::BaseAddress, XIOModule::CurrentTCSR, XIOModule::IsReady, XIOModule_WriteReg.
Referenced by IOModuleIntrExample, XIOModule_Timer_SelfTest.
u32 XIOModule_GetValue(XIOModule *InstancePtr, u8 TimerNumber)
Get the current value of the specified timer counter.
The timer counter may be either incrementing or decrementing based upon the current mode of operation. InstancePtr is a pointer to the XIOModule instance. TimerNumber is the timer counter of the device to operate on. Each device may contain multiple timer counters. The timer number is a zero based number with a range of 0 to (XTC_DEVICE_TIMER_COUNT - 1). The current value for the timer counter. None.
References XIOModule::BaseAddress, XIOModule::IsReady, XIOModule_ReadReg.
Referenced by XIOModule_Timer_SelfTest.
void XIOModule_SetResetValue(XIOModule *InstancePtr, u8 TimerNumber, u32 ResetValue)
Set the reset value for the specified timer counter.
This is the value that is loaded into the timer counter when it is reset. This value is also loaded when the timer counter is started. InstancePtr is a pointer to the XIOModule instance. TimerNumber is the timer counter of the device to operate on. Each device may contain multiple timer counters. The timer number is a zero based number with a range of 0 to (XTC_DEVICE_TIMER_COUNT - 1). ResetValue contains the value to be used to reset the timer counter. None. None.
References XIOModule::BaseAddress, XIOModule::CurrentTLR, XIOModule::IsReady, XIOModule_WriteReg.
Referenced by IOModuleIntrExample, XIOModule_Timer_SelfTest.
u32 XIOModule_GetCaptureValue(XIOModule *InstancePtr, u8 TimerNumber)
Returns the timer counter value that was captured the last time the external capture input was asserted.
InstancePtr is a pointer to the XIOModule instance. TimerNumber is the timer counter of the device to operate on. Each device may contain multiple timer counters. The timer number is a zero based number with a range of 0 to (XTC_DEVICE_TIMER_COUNT - 1). The current capture value for the indicated timer counter. None.
References XIOModule::CurrentTLR, XIOModule::IsReady.
void XIOModule_Reset(XIOModule *InstancePtr, u8 TimerNumber)
Resets the specified timer counter of the device.
A reset causes the timer counter to set it's value to the reset value. InstancePtr is a pointer to the XIOModule instance. TimerNumber is the timer counter of the device to operate on. Each device may contain multiple timer counters. The timer number is a zero based number with a range of 0 to (XTC_DEVICE_TIMER_COUNT - 1). None. None.
References XIOModule::BaseAddress, XIOModule::CurrentTCSR, XIOModule::IsReady, XIOModule_WriteReg.
s32 XIOModule_IsExpired(XIOModule *InstancePtr, u8 TimerNumber)
Checks if the specified timer counter of the device has expired.
In capture mode, expired is defined as a capture occurred. In compare mode, expired is defined as the timer counter rolled over/under for up/down counting.When interrupts are enabled, the expiration causes an interrupt. This function is typically used to poll a timer counter to determine when it has expired. InstancePtr is a pointer to the XIOModule instance. TimerNumber is the timer counter of the device to operate on. Each device may contain multiple timer counters. The timer number is a zero based number with a range of 0 to (XTC_DEVICE_TIMER_COUNT - 1). TRUE if the timer has expired, and FALSE otherwise. None.
References XIOModule::BaseAddress, XIOModule::CfgPtr, XIOModule::CurrentTCSR, XIOModule::IsReady, XIOModule_Config::PitMask, XIOModule_Config::PitReadable, XIOModule_ReadReg.
Referenced by IOModuleHandler.
u32 XIOModule_IoReadWord(XIOModule *InstancePtr, u32 ByteOffset)
Read 32-bit word from the IO Bus memory mapped IO.
InstancePtr is a pointer to an XIOModule instance to be worked on. ByteOffset is a byte offset from the beginning of the IO Bus address area Value read from the IO Bus - 32-bit word
References XIOModule::IoBaseAddress, XIOModule::IsReady.
u16 XIOModule_IoReadHalfword(XIOModule *InstancePtr, u32 ByteOffset)
Read 16-bit halfword from the IO Bus memory mapped IO.
InstancePtr is a pointer to an XIOModule instance to be worked on. ByteOffset is a byte offset from the beginning of the IO Bus address area Value read from the IO Bus - 16-bit halfword
References XIOModule::IoBaseAddress, XIOModule::IsReady.
u8 XIOModule_IoReadByte(XIOModule *InstancePtr, u32 ByteOffset)
Read byte from the IO Bus memory mapped IO.
InstancePtr is a pointer to an XIOModule instance to be worked on. ByteOffset is a byte offset from the beginning of the IO Bus address area Value read from the IO Bus - 8-bit byte
References XIOModule::IoBaseAddress, XIOModule::IsReady.
void XIOModule_IoWriteWord(XIOModule *InstancePtr, u32 ByteOffset, u32 Data)
Write 32-bit word to the IO Bus memory mapped IO.
InstancePtr is a pointer to an XIOModule instance to be worked on. ByteOffset is a byte offset from the beginning of the IO Bus address area Data is the value to be written to the IO Bus - 32-bit None.
References XIOModule::IoBaseAddress, XIOModule::IsReady.
void XIOModule_IoWriteHalfword(XIOModule *InstancePtr, u32 ByteOffset, u16 Data)
Write 16-bit word to the IO Bus memory mapped IO.
InstancePtr is a pointer to an XIOModule instance to be worked on. ByteOffset is a byte offset from the beginning of the IO Bus address area Data is the value to be written to the IO Bus - 16-bit None.
References XIOModule::IoBaseAddress, XIOModule::IsReady.
void XIOModule_IoWriteByte(XIOModule *InstancePtr, u32 ByteOffset, u8 Data)
Write 8-bit word to the IO Bus memory mapped IO.
InstancePtr is a pointer to an XIOModule instance to be worked on. ByteOffset is a byte offset from the beginning of the IO Bus address area Data is the value to be written to the IO Bus - 8-bit None.
References XIOModule::IoBaseAddress, XIOModule::IsReady.
void XIOModule_DiscreteSet(XIOModule *InstancePtr, u32 Channel, u32 Mask)
Set output discrete(s) to logic 1 for the specified GPO channel.
InstancePtr is a pointer to an XIOModule instance to be worked on. Channel contains the channel of the GPIO (1, 2, 3 or 4) to operate on. Mask is the set of bits that will be set to 1 in the discrete data register. All other bits in the data register are unaffected. None.
References XIOModule::BaseAddress, XIOModule::GpoValue, XIOModule::IsReady, XIOModule_WriteReg.
void XIOModule_DiscreteClear(XIOModule *InstancePtr, u32 Channel, u32 Mask)
Set output discrete(s) to logic 0 for the specified GPO channel.
InstancePtr is a pointer to an XIOModule instance to be worked on. Channel contains the channel of the GPIO (1, 2, 3 or 4) to operate on. Mask is the set of bits that will be set to 0 in the discrete data register. All other bits in the data register are unaffected. None.
References XIOModule::BaseAddress, XIOModule::GpoValue, XIOModule::IsReady, XIOModule_WriteReg.
s32 XIOModule_CfgInitialize(XIOModule *InstancePtr, XIOModule_Config *Config, u32 EffectiveAddr)
Initialize a XIOModule instance.
This function disables the UART interrupts. The baud rate and format of the data are fixed in the hardware at hardware build time, except if programmable baud rate is selected. InstancePtr is a pointer to the XIOModule instance. Config is a reference to a structure containing information about a specific IO Module device. This function initializes an InstancePtr object for a specific device specified by the contents of Config. This function can initialize multiple instance objects with the use of multiple calls giving different Config information on each call. EffectiveAddr is the device register base address. Use Config->BaseAddress for this parameters, passing the physical address. XST_SUCCESS if everything starts up as expected. The Config and EffectiveAddress arguments are not used by this function, but are provided to keep the function signature consistent with other drivers.
References XIOModule::BaseAddress, XIOModule::CurrentIER, XIOModule::IsReady, XIOModule_Buffer::NextBytePtr, XIOModule::ReceiveBuffer, XIOModule::RecvHandler, XIOModule_Buffer::RemainingBytes, XIOModule_Buffer::RequestedBytes, XIOModule::SendBuffer, XIOModule::SendHandler, XIOModule_ClearStats.
Referenced by XIOModule_Initialize.
void XIOModule_ResetFifos(XIOModule *InstancePtr)
This function does nothing, since the UART doesn't have any FIFOs.
It is included for compatibility with the UART Lite driver. InstancePtr is a pointer to the XIOModule instance . None. None.
References XIOModule::IsReady.
u32 XIOModule_Send(XIOModule *InstancePtr, u8 *DataBufferPtr, u32 NumBytes)
This functions sends the specified buffer of data using the UART in either polled or interrupt driven modes.
This function is non-blocking such that it will return before the data has been sent by the UART. If the UART is busy sending data, it will return and indicate zero bytes were sent.In a polled mode, this function will only send as much data as the UART can buffer in the transmitter. The application may need to call it repeatedly to send a buffer.In interrupt mode, this function will start sending the specified buffer and then the interrupt handler of the driver will continue sending data until the buffer has been sent. A callback function, as specified by the application, will be called to indicate the completion of sending the buffer. InstancePtr is a pointer to the XIOModule instance. DataBufferPtr is pointer to a buffer of data to be sent. NumBytes contains the number of bytes to be sent. A value of zero will stop a previous send operation that is in progress in interrupt mode. Any data that was already put into the transmit FIFO will be sent. The number of bytes actually sent. The number of bytes is not asserted so that this function may be called with a value of zero to stop an operation that is already in progress.
References XIOModule::BaseAddress, XIOModule::CurrentIER, XIOModule::IsReady, XIOModule_Buffer::NextBytePtr, XIOModule_Buffer::RemainingBytes, XIOModule_Buffer::RequestedBytes, XIOModule::SendBuffer, XIOModule_SendBuffer.
u32 XIOModule_Recv(XIOModule *InstancePtr, u8 *DataBufferPtr, u32 NumBytes)
This function will attempt to receive a specified number of bytes of data from the UART and store it into the specified buffer.
This function is designed for either polled or interrupt driven modes. It is non-blocking such that it will return if no data has already received by the UART.In a polled mode, this function will only receive as much data as the UART can buffer in the receiver. The application may need to call it repeatedly to receive a buffer. Polled mode is the default mode of operation for the driver.In interrupt mode, this function will start receiving and then the interrupt handler of the driver will continue receiving data until the buffer has been received. A callback function, as specified by the application, will be called to indicate the completion of receiving the buffer or when any receive errors or timeouts occur. InstancePtr is a pointer to the XIOModule instance. DataBufferPtr is pointer to buffer for data to be received into. NumBytes is the number of bytes to be received. A value of zero will stop a previous receive operation that is in progress in interrupt mode. The number of bytes received. The number of bytes is not asserted so that this function may be called with a value of zero to stop an operation that is already in progress.
References XIOModule::BaseAddress, XIOModule::CurrentIER, XIOModule::IsReady, XIOModule_Buffer::NextBytePtr, XIOModule::ReceiveBuffer, XIOModule_Buffer::RemainingBytes, XIOModule_Buffer::RequestedBytes, XIOModule_ReceiveBuffer.
s32 XIOModule_IsSending(XIOModule *InstancePtr)
This function determines if the specified UART is sending data.
If the transmitter register is not empty, it is sending data. InstancePtr is a pointer to the XIOModule instance. A value of TRUE if the UART is sending data, otherwise FALSE. None.
References XIOModule::BaseAddress, XIOModule_ReadReg.
s32 XIOModule_SetBaudRate(XIOModule *InstancePtr, u32 BaudRate)
Sets the baud rate for the specified UART.
Checks the input value for validity and also verifies that the requested rate can be configured to within the 3 percent error range for RS-232 communications. If the provided rate is not valid, the current setting is unchanged.This function is designed to be an internal function only used within the XIOModule component. It is necessary for initialization and for the user available function that sets the data format. InstancePtr is a pointer to the XIOModule instance. BaudRate to be set in the hardware. XST_SUCCESS if everything configures as expected XST_UART_BAUD_ERROR if the requested rate is not available because there was too much error due to the input clock None.
References XIOModule::BaseAddress, XIOModule_Config::BaudRate, XIOModule::CfgPtr, XIOModule::CurrentUBRR, XIOModule_Config::InputClockHz, XIOModule::IsReady, XIOModule_WriteReg.
void XIOModule_GetStats(XIOModule *InstancePtr, XIOModule_Uart_Stats *StatsPtr)
Returns a snapshot of the current statistics in the structure specified.
InstancePtr is a pointer to the XIOModule instance. StatsPtr is a pointer to a XIOModule_Uart_Stats structure to where the statistics are to be copied. None. None.
References XIOModule_Uart_Stats::CharactersReceived, XIOModule_Uart_Stats::CharactersTransmitted, XIOModule::IsReady, XIOModule_Uart_Stats::ReceiveFramingErrors, XIOModule_Uart_Stats::ReceiveInterrupts, XIOModule_Uart_Stats::ReceiveOverrunErrors, XIOModule_Uart_Stats::ReceiveParityErrors, XIOModule_Uart_Stats::TransmitInterrupts, XIOModule::Uart_Stats.
void XIOModule_ClearStats(XIOModule *InstancePtr)
This function zeros the statistics for the given instance.
InstancePtr is a pointer to the XIOModule instance. None. None.
References XIOModule_Uart_Stats::CharactersReceived, XIOModule_Uart_Stats::CharactersTransmitted, XIOModule::IsReady, XIOModule_Uart_Stats::ReceiveFramingErrors, XIOModule_Uart_Stats::ReceiveInterrupts, XIOModule_Uart_Stats::ReceiveOverrunErrors, XIOModule_Uart_Stats::ReceiveParityErrors, XIOModule_Uart_Stats::TransmitInterrupts, XIOModule::Uart_Stats.
Referenced by XIOModule_CfgInitialize.
void XIOModule_InterruptHandler(XIOModule *InstancePtr)
The interrupt handler for the driver.
This function is provided mostly for backward compatibility. The user should use XIOModule_DeviceInterruptHandler(), defined in xiomodule_l.c when possible and pass the device ID of the interrupt controller device as its argument.The user must connect this function to the interrupt system such that it is called whenever the devices which are connected to it cause an interrupt. InstancePtr is a pointer to the XIOModule instance to be worked on. None. None.
References XIOModule_Config::BaseAddress, XIOModule::CfgPtr, XIOModule_DeviceInterruptHandler.
void XIOModule_Uart_EnableInterrupt(XIOModule *InstancePtr)
This function enables the UART interrupts such that an interrupt will occur when data is received or data has been transmitted.
InstancePtr is a pointer to the XIOModule instance. None. None.
References XIOModule::BaseAddress, XIOModule::CurrentIER, XIOModule::IsReady.
void XIOModule_Uart_DisableInterrupt(XIOModule *InstancePtr)
This function disables the UART interrupt.
After calling this function, data may still be received by the UART but no interrupt will be generated since the hardware device has no way to disable the receiver. InstancePtr is a pointer to the XIOModule instance. None. None.
References XIOModule::BaseAddress, XIOModule::CurrentIER, XIOModule::IsReady.
void XIOModule_SetRecvHandler(XIOModule *InstancePtr, XIOModule_Handler FuncPtr, void *CallBackRef)
This function sets the handler that will be called when an event (interrupt) occurs in the driver for the UART.
The purpose of the handler is to allow application specific processing to be performed. InstancePtr is a pointer to the XIOModule instance. FuncPtr is the pointer to the callback function. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. None. There is no assert on the CallBackRef since the driver doesn't know what it is (nor should it)
References XIOModule::IsReady, XIOModule::RecvCallBackRef, XIOModule::RecvHandler.
void XIOModule_SetSendHandler(XIOModule *InstancePtr, XIOModule_Handler FuncPtr, void *CallBackRef)
This function sets the handler that will be called when an event (interrupt) occurs in the driver for the UART.
The purpose of the handler is to allow application specific processing to be performed. InstancePtr is a pointer to the XIOModule instance . FuncPtr is the pointer to the callback function. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. None. There is no assert on the CallBackRef since the driver doesn't know what it is (nor should it)
References XIOModule::IsReady, XIOModule::SendCallBackRef, XIOModule::SendHandler.
void XIOModule_Uart_InterruptHandler(XIOModule *InstancePtr)
This function is the interrupt handler for the UART.
It must be connected to an interrupt system by the user such that it is called when an interrupt for any UART lite occurs. This function does not save or restore the processor context such that the user must ensure this occurs. InstancePtr contains a pointer to the instance of the IOModule that the interrupt is for. None. None.
References XIOModule::BaseAddress, XIOModule_Buffer::RequestedBytes, XIOModule::SendBuffer, XIOModule_GetStatusReg.
s32 XIOModule_SetOptions(XIOModule *InstancePtr, u32 Options)
Set the options for the interrupt controller driver.
InstancePtr is a pointer to the XIOModule instance to be worked on. Options to be set. The available options are described in xiomodule.h. XST_SUCCESS if the options were set successfullyXST_INVALID_PARAM if the specified option was not valid None.
References XIOModule::CfgPtr, XIOModule::IsReady, XIOModule_Config::Options.
u32 XIOModule_GetOptions(XIOModule *InstancePtr)
Return the currently set options.
InstancePtr is a pointer to the XIOModule instance to be worked on. The currently set options. The options are described in xiomodule.h. None.
References XIOModule::CfgPtr, XIOModule::IsReady, XIOModule_Config::Options.
s32 XIOModule_SelfTest(XIOModule *InstancePtr)
Runs a self-test on the timer and interrupt controller driver/device.
InstancePtr is a pointer to the XIOMOdule instance. XST_SUCCESS if self-test was successful XST_FAILURE if the timer is not incrementing. This is a destructive test using the provided timer. The current settings of the timer are returned to the initialized values and all settings at the time this function is called are overwritten.
References XIOModule::CfgPtr, XIOModule::IsReady, XIOModule_Config::PitPrescaler, XIOModule_Config::PitReadable, XIOModule_Config::PitSize, XIOModule_Config::PitUsed, XIOModule_Intc_SelfTest, XIOModule_Timer_SelfTest.
Referenced by IOModuleInterruptSetup, IOModuleIntrExample, IOModuleSelfTestExample.
void XIOModule_Timer_SetOptions(XIOModule *InstancePtr, u8 TimerNumber, u32 Options)
Enables the specified options for the specified timer .
This function sets the options without regard to the current options of the driver. To prevent a loss of the current options, the user should call XIOModule_Timer_GetOptions() prior to this function and modify the retrieved options to pass into this function to prevent loss of the current options. InstancePtr is a pointer to the XIOModule instance. TimerNumber is the timer of the device to operate on. Each device may contain multiple timers. The timer number is a zero based number with a range of 0 to (XTC_DEVICE_TIMER_COUNT - 1). Options contains the desired options to be set or cleared. Setting the option to '1' enables the option, clearing the to '0' disables the option. The options are bit masks such that multiple options may be set or cleared. The options are described in xiomodule.h. None. None.
References XIOModule::BaseAddress, XIOModule::CurrentTCSR, XIOModule::IsReady, XIOModule_WriteReg.
Referenced by IOModuleHandler, IOModuleIntrExample, XIOModule_Timer_SelfTest.
u32 XIOModel_Timer_GetOptions(XIOModule *InstancePtr, u8 TimerNumber)
Get the options for the specified timer.
InstancePtr is a pointer to the XIOModule instance. TimerNumber is the timer of the device to operate on Each device may contain multiple timer. The timer number is a zero based number with a range of 0 to (XTC_DEVICE_TIMER_COUNT - 1). The currently set options. An option which is set to a '1' is enabled and set to a '0' is disabled. The options are bit masks such that multiple options may be set or cleared. The options are described in xiomodule.h.None.
References XIOModule::CurrentTCSR, XIOModule::IsReady.
s32 XIOModule_Timer_SelfTest(XIOModule *InstancePtr, u8 TimerNumber)
Runs a self-test on the timer driver/device.
This test verifies that the specified programmable interval timer of the device can be enabled and increments. InstancePtr is a pointer to the XIOMOdule instance. TimerNumber is the timer of the device to operate on. Each device may contain multiple timers. The timer number is a zero based number with a range of 0 to (XTC_DEVICE_TIMER_COUNT - 1). XST_SUCCESS if self-test was successful XST_FAILURE if the timer is not incrementing. This is a destructive test using the provided timer. The current settings of the timer are returned to the initialized values and all settings at the time this function is called are overwritten.
References XIOModule::CfgPtr, XIOModule::IsReady, XIOModule_Config::PitSize, XIOModule_GetValue, XIOModule_SetResetValue, XIOModule_Timer_SetOptions, XIOModule_Timer_Start, XIOModule_Timer_Stop.
Referenced by XIOModule_SelfTest.
int XIOModule_Intc_SelfTest(XIOModule *InstancePtr)
Run a self-test on the interrupt controller driver/device.
This is a destructive test.This involves forcing interrupts into the controller (if possible, given the IO Module configuration) and verifying that they are recognized and can be acknowledged. InstancePtr is a pointer to the XIOModule instance to be worked on. XST_SUCCESS if self-test is successful.XST_INTC_FAIL_SELFTEST if the Interrupt controller fails the self-test. It will fail the self test if the device has previously been started in real mode. None.
References XIOModule::BaseAddress, XIOModule::IsReady.
Referenced by XIOModule_SelfTest.
void XIOModule_SetHandler(XIOModule *InstancePtr, XIOModule_Timer_Handler FuncPtr, void *CallBackRef)
Sets the timer callback function, which the driver calls when the specified timer times out.
InstancePtr is a pointer to the XIOModule instance. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. FuncPtr is the pointer to the callback function. None. The handler is called within interrupt context so the function that is called should either be short or pass the more extensive processing off to another task to allow the interrupt to return and normal processing to continue.This function is provided for compatibility, and only allows setting a single handler for all Programmable Interval Timers.
References XIOModule::CallBackRef, XIOModule::CfgPtr, XIOModule_VectorTableEntry::Handler, XIOModule::Handler, XIOModule_Config::HandlerTable, XIOModule::IsReady, XIOModule_Timer_InterruptHandler.
Referenced by IOModuleIntrExample.
void XIOModule_Timer_InterruptHandler(void *InstancePtr)
Interrupt Service Routine (ISR) for the driver.
This function only performs processing for the Programmable Interval Timer and does not save and restore the interrupt context. InstancePtr contains a pointer to the IO Module instance for the interrupt. None. None.
References XIOModule::BaseAddress, XIOModule::CallBackRef, XIOModule::CfgPtr, XIOModule::CurrentIMR, XIOModule::Handler, XIOModule_Timer_Stats::Interrupts, XIOModule_Config::PitUsed, XIOModule::Timer_Stats, XIOModule_ReadReg, XIOModule_WriteReg.
Referenced by XIOModule_SetHandler.
unsigned int XIOModule_SendBuffer(XIOModule *InstancePtr)
This function sends a buffer that has been previously specified by setting up the instance variables of the instance.
This function is designed to be an internal function for the XIOModule component such that it may be called from a shell function that sets up the buffer or from an interrupt handler.This function sends the specified buffer of data to the UART in either polled or interrupt driven modes. This function is non-blocking such that it will return before the data has been sent by the UART.In a polled mode, this function will only send as much data as the UART can buffer in the transmitter. The application may need to call it repeatedly to send a buffer.In interrupt mode, this function will start sending the specified buffer and then the interrupt handler of the driver will continue until the buffer has been sent. A callback function, as specified by the application, will be called to indicate the completion of sending the buffer. InstancePtr is a pointer to the XIOModule instance. NumBytes is the number of bytes actually sent (put into the UART transmitter and/or FIFO). None.
References XIOModule::BaseAddress, XIOModule_Uart_Stats::CharactersTransmitted, XIOModule::CurrentIER, XIOModule_Buffer::NextBytePtr, XIOModule_Buffer::RemainingBytes, XIOModule::SendBuffer, XIOModule::Uart_Stats, XIOModule_GetStatusReg, XIOModule_WriteReg.
Referenced by XIOModule_Send.
unsigned int XIOModule_ReceiveBuffer(XIOModule *InstancePtr)
This function receives a buffer that has been previously specified by setting up the instance variables of the instance.
This function is designed to be an internal function for the XIOModule component such that it may be called from a shell function that sets up the buffer or from an interrupt handler.This function will attempt to receive a specified number of bytes of data from the UART and store it into the specified buffer. This function is designed for either polled or interrupt driven modes. It is non-blocking such that it will return if there is no data has already received by the UART.In a polled mode, this function will only receive as much data as the UART can buffer, either in the receiver or in the FIFO if present and enabled. The application may need to call it repeatedly to receive a buffer. Polled mode is the default mode of operation for the driver.In interrupt mode, this function will start receiving and then the interrupt handler of the driver will continue until the buffer has been received. A callback function, as specified by the application, will be called to indicate the completion of receiving the buffer or when any receive errors or timeouts occur. InstancePtr is a pointer to the XIOModule instance. The number of bytes received. None.
References XIOModule::BaseAddress, XIOModule_Uart_Stats::CharactersReceived, XIOModule::CurrentIER, XIOModule_Buffer::NextBytePtr, XIOModule::ReceiveBuffer, XIOModule_Buffer::RemainingBytes, XIOModule::Uart_Stats, XIOModule_GetStatusReg, XIOModule_ReadReg, XIOModule_UpdateStats.
Referenced by XIOModule_Recv.
static XIOModule_Config * LookupConfigByBaseAddress(UINTPTR BaseAddress)
Looks up the device configuration based on the base address of the device.
A table contains the configuration info for each device in the system. BaseAddress is the unique identifier for a device. A pointer to the configuration structure for the specified device, or NULL if the device was not found.None.
void XIOModule_DeviceInterruptHandler(void *DeviceId)
This function is the primary interrupt handler for the driver.
It must be connected to the interrupt source such that is called when an interrupt of the interrupt controller is active. It will resolve which interrupts are active and enabled and call the appropriate interrupt handler. It uses the AckBeforeService flag in the configuration data to determine when to acknowledge the interrupt. Highest priority interrupts are serviced first. The driver can be configured to service only the highest priority interrupt or all pending interrupts using the {XIOModule_SetOptions()} function or the {XIOModule_SetIntrSrvOption()} function.This function assumes that an interrupt vector table has been previously initialized. It does not verify that entries in the table are valid before calling an interrupt handler, except skipping null handlers that indicate use of fast interrupts where the hardware directly jumps to the handler. DeviceId is the zero-based device ID defined in xparameters.h of the interrupting interrupt controller. It is used as a direct index into the configuration data, which contains the vector table for the interrupt controller. Note that even though the argument is a void pointer, the value is not a pointer but the actual device ID. The void pointer type is necessary to meet the XInterruptHandler typedef for interrupt handlers. None. The constant XPAR_IOMODULE_MAX_INTR_SIZE must be setup for this to compile. Interrupt IDs range from 0 - 31 and correspond to the interrupt input signals for the interrupt controller. XPAR_IOMODULE_MAX_INTR_SIZE specifies the highest numbered interrupt input signal that is used.
References XIOModule_VectorTableEntry::CallBackRef, XIOModule_VectorTableEntry::Handler, XIOModule_AckIntr, XIOModule_ConfigTable, XIOModule_GetIntrStatus, XIOModule_LookupConfig.
Referenced by IOModuleSetupIntrSystem, SetupInterruptSystem, XIOModule_InterruptHandler.
void XIOModule_SetIntrSvcOption(UINTPTR BaseAddress, s32 Option)
Set the interrupt service option, which can configure the driver so that it services only a single interrupt at a time when an interrupt occurs, or services all pending interrupts when an interrupt occurs.
The default behavior when using the driver interface given in xintc.h file is to service only a single interrupt, whereas the default behavior when using the driver interface given in this file is to service all outstanding interrupts when an interrupt occurs. BaseAddress is the unique identifier for a device. Option is XIN_SVC_SGL_ISR_OPTION if you want only a single interrupt serviced when an interrupt occurs, or XIN_SVC_ALL_ISRS_OPTION if you want all pending interrupts serviced when an interrupt occurs. None. Note that this function has no effect if the input base address is invalid.
References XIOModule_Config::Options.
void XIOModule_RegisterHandler(UINTPTR BaseAddress, s32 InterruptId, XInterruptHandler Handler, void *CallBackRef)
Register a handler function for a specific interrupt ID.
The vector table of the interrupt controller is updated, overwriting any previous handler. The handler function will be called when an interrupt occurs for the given interrupt ID.This function can also be used to remove a handler from the vector table by passing in the XIOModule_DefaultHandler() as the handler and NULL as the callback reference. BaseAddress is the base address of the interrupt controller whose vector table will be modified. InterruptId is the interrupt ID to be associated with the input handler. Handler is the function pointer that will be added to the vector table for the given interrupt ID. It adheres to the XInterruptHandler signature found in xbasic_types.h. CallBackRef is the argument that will be passed to the new handler function when it is called. This is user-specific. None. Only used with normal interrupt mode. Does not restore normal interrupt mode. Note that this function has no effect if the input base address is invalid.
References XIOModule_VectorTableEntry::CallBackRef, XIOModule_VectorTableEntry::Handler, XIOModule_Config::HandlerTable.
Referenced by IOModuleLowLevelExample.
void XIOModule_SendByte(UINTPTR BaseAddress, u8 Data)
This functions sends a single byte using the UART.
It is blocking in that it waits for the transmitter to become non-full before it writes the byte to the transmit register. BaseAddress is the base address of the device Data is the byte of data to send None. None.
References XIOModule_IsTransmitFull.
u8 XIOModule_RecvByte(UINTPTR BaseAddress)
This functions receives a single byte using the UART.
It is blocking in that it waits for the receiver to become non-empty before it reads from the receive register. BaseAddress is the base address of the device The byte of data received. None.
References XIOModule_IsReceiveEmpty.
static void StubHandler(void *CallBackRef, unsigned int ByteCount)
This function provides a stub handler such that if the application does not define a handler but enables interrupts, this function will be called.
CallBackRef has no purpose but is necessary to match the interface for a handler. ByteCount has no purpose but is necessary to match the interface for a handler. None. None.
static void ReceiveDataHandler(XIOModule *InstancePtr)
This function handles the interrupt when data is received, either a single byte when FIFOs are not enabled, or multiple bytes with the FIFO.
InstancePtr is a pointer to the XIOModule instance. None. None.
static void SendDataHandler(XIOModule *InstancePtr)
This function handles the interrupt when data has been sent, the transmit FIFO is empty (transmitter holding register).
InstancePtr is a pointer to the XIOModule instance . None. None.
XIOModule_UpdateStats
Update the statistics of the instance.
InstancePtr is a pointer to the XIOMOdule instance. StatusRegister contains the contents of the UART status register to update the statistics with. None. Signature: void XIOModule_UpdateStats(XIOModule *InstancePtr, u32 StatusRegister)
Referenced by XIOModule_ReceiveBuffer.
XIOModule_EnableIntr
Enable specific interrupt(s) in the interrupt controller.
BaseAddress is the base address of the device EnableMask is the 32-bit value to write to the enable register. Each bit of the mask corresponds to an interrupt input signal that is connected to the interrupt controller (INT0 = LSB). Only the bits which are set in the mask will enable interrupts. None. C-style signature: void XIOModule_EnableIntr(UINTPTR BaseAddress, u32 EnableMask);
Referenced by IOModuleLowLevelExample.
XIOModule_DisableIntr
Disable specific interrupt(s) in the interrupt controller.
BaseAddress is the base address of the device DisableMask is the 32-bit value to write to enable register. Each bit of the mask corresponds to an interrupt input signal that is connected to the interrupt controller (INT0 = LSB). Only bits which are set in the mask will disable interrupts. None. C-style signature: void XIOModule_DisableIntr(UINTPTR BaseAddress, u32 DisableMask);
XIOModule_AckIntr
Acknowledge specific interrupt(s) in the interrupt controller.
BaseAddress is the base address of the device AckMask is the 32-bit value to write to the acknowledge register. Each bit of the mask corresponds to an interrupt input signal that is connected to the interrupt controller (INT0 = LSB). Only the bits which are set in the mask will acknowledge interrupts. None. C-style signature: void XIOModule_AckIntr(UINTPTR BaseAddress, u32 AckMask);
Referenced by XIOModule_DeviceInterruptHandler.
XIOModule_GetIntrStatus
Get the interrupt status from the interrupt controller which indicates which interrupts are active and enabled.
BaseAddress is the base address of the device The 32-bit contents of the interrupt status register. Each bit corresponds to an interrupt input signal that is connected to the interrupt controller (INT0 = LSB). Bits which are set indicate an active interrupt which is also enabled. C-style signature: u32 XIOModule_GetIntrStatus(UINTPTR BaseAddress);
Referenced by XIOModule_DeviceInterruptHandler.
XIOModule_GetStatusReg
Get the contents of the UART status register.
Use the XUL_SR_* constants defined above to interpret the bit-mask returned. BaseAddress is the base address of the device A 32-bit value representing the contents of the status register. C-style Signature: u32 XIOModule_GetStatusReg(UINTPTR BaseAddress);
Referenced by XIOModule_ReceiveBuffer, XIOModule_SendBuffer, XIOModule_Uart_InterruptHandler.
XIOModule_IsReceiveEmpty
Check to see if the UART receiver has data.
BaseAddress is the base address of the device TRUE if the receiver is empty, FALSE if there is data present. C-style Signature: int XIOModule_IsReceiveEmpty(UINTPTR BaseAddress);
Referenced by XIOModule_RecvByte.
XIOModule_IsTransmitFull
Check to see if the transmitter is full.
BaseAddress is the base address of the device TRUE if the transmitter is full, FALSE otherwise. C-style Signature: int XIOModule_IsTransmitFull(UINTPTR BaseAddress);
Referenced by XIOModule_SendByte.
XIOModule_WriteReg
Write a value to a GPO register.
A 32 bit write is performed. If the GPO component is implemented in a smaller width, only the least significant data is written. BaseAddress is the base address of the GPO device. RegOffset is the register offset from the base to write to. Data is the data written to the register. None. C-style signature: void XIOModule_WriteReg(UINTPTR BaseAddress, unsigned RegOffset, u32 Data)
Referenced by XIOModule_DiscreteClear, XIOModule_DiscreteSet, XIOModule_DiscreteWrite, XIOModule_Reset, XIOModule_SendBuffer, XIOModule_SetBaudRate, XIOModule_SetResetValue, XIOModule_Timer_Initialize, XIOModule_Timer_InterruptHandler, XIOModule_Timer_SetOptions, XIOModule_Timer_Start, XIOModule_Timer_Stop.
XIOModule_ReadReg
Read a value from a GPI register.
A 32 bit read is performed. If the GPI component is implemented in a smaller width, only the least significant data is read from the register. The most significant data will be read as 0. BaseAddress is the base address of the GPI device. RegOffset is the register offset from the base to read from. Data read from the register. C-style signature: u32 XIOModule_ReadReg(UINTPTR BaseAddress, unsigned RegOffset)
Referenced by XIOModule_DiscreteRead, XIOModule_GetValue, XIOModule_IsExpired, XIOModule_IsSending, XIOModule_ReceiveBuffer, XIOModule_Timer_InterruptHandler.