xiomodule_selftest.c
int XIOModule_Intc_SelfTest(XIOModule *InstancePtr)
Run a self-test on the interrupt controller driver/device.
This is a destructive test.This involves forcing interrupts into the controller (if possible, given the IO Module configuration) and verifying that they are recognized and can be acknowledged. InstancePtr is a pointer to the XIOModule instance to be worked on. XST_SUCCESS if self-test is successful.XST_INTC_FAIL_SELFTEST if the Interrupt controller fails the self-test. It will fail the self test if the device has previously been started in real mode. None.
References XIOModule::BaseAddress, XIOModule::IsReady.
Referenced by XIOModule_SelfTest.
s32 XIOModule_Timer_SelfTest(XIOModule *InstancePtr, u8 TimerNumber)
Runs a self-test on the timer driver/device.
This test verifies that the specified programmable interval timer of the device can be enabled and increments. InstancePtr is a pointer to the XIOMOdule instance. TimerNumber is the timer of the device to operate on. Each device may contain multiple timers. The timer number is a zero based number with a range of 0 to (XTC_DEVICE_TIMER_COUNT - 1). XST_SUCCESS if self-test was successful XST_FAILURE if the timer is not incrementing. This is a destructive test using the provided timer. The current settings of the timer are returned to the initialized values and all settings at the time this function is called are overwritten.
References XIOModule::CfgPtr, XIOModule::IsReady, XIOModule_Config::PitSize, XIOModule_GetValue, XIOModule_SetResetValue, XIOModule_Timer_SetOptions, XIOModule_Timer_Start, XIOModule_Timer_Stop.
Referenced by XIOModule_SelfTest.
s32 XIOModule_SelfTest(XIOModule *InstancePtr)
Runs a self-test on the timer and interrupt controller driver/device.
InstancePtr is a pointer to the XIOMOdule instance. XST_SUCCESS if self-test was successful XST_FAILURE if the timer is not incrementing. This is a destructive test using the provided timer. The current settings of the timer are returned to the initialized values and all settings at the time this function is called are overwritten.
References XIOModule::CfgPtr, XIOModule::IsReady, XIOModule_Config::PitPrescaler, XIOModule_Config::PitReadable, XIOModule_Config::PitSize, XIOModule_Config::PitUsed, XIOModule_Intc_SelfTest, XIOModule_Timer_SelfTest.
Referenced by IOModuleInterruptSetup, IOModuleIntrExample, IOModuleSelfTestExample.