xiomodule_low_level_example.c
IOMODULE_BASEADDR
IOMODULE_DEVICE_INTR_ID
IOMODULE_DEVICE_INT_MASK
volatile u32 InterruptProcessed
XStatus IOModuleLowLevelExample(u32 IOModuleBaseAddress)
This function is an example of how to use the IO Module driver component (XIOModule) and the hardware device.
This function is designed to work without external hardware devices to cause interrupts. It may not return if the IO Module is not properly connected to the processor in either software or hardware. IOModuleBaseAddress is Base Address of the the IO Module Device XST_SUCCESS to indicate success, otherwise XST_FAILURE None.
References DeviceDriverHandler, SetupInterruptSystem, XIOModule_EnableIntr, XIOModule_RegisterHandler.
Referenced by main.
void SetupInterruptSystem()
This function connects the interrupt handler of the IO Module to the processor.
This function is separate to allow it to be customized for each application. Each processor or RTOS may require unique processing to connect the interrupt handler. None. None. None.
References XIOModule_DeviceInterruptHandler.
Referenced by IOModuleLowLevelExample.
void DeviceDriverHandler(void *CallbackRef)
This function is designed to look like an interrupt handler in a device driver.
This is typically a 2nd level handler that is called from the IO Module interrupt handler. This handler would typically perform device specific processing such as reading and writing the registers of the device to clear the interrupt condition and pass any data to an application using the device driver. Many drivers already provide this handler and the user is not required to create it. CallbackRef is passed back to the device driver's interrupt handler by the XIOModule driver. It was given to the XIOModule driver in the XIOModule_Connect() function call. It is typically a pointer to the device driver instance variable if using the Xilinx Level 1 device drivers. In this example, we do not care about the callback reference, so we passed it a 0 when connecting the handler to the XIOModule driver and we make no use of it here. None. None.
Referenced by IOModuleLowLevelExample.
int main(void)
This is the main function for the IO Module Low Level example.
None. XST_SUCCESS to indicate success, otherwise XST_FAILURE. None.
References IOModuleLowLevelExample.