xiomodule_intr_example.c
IOMODULE_DEVICE_ID
MAX_INTR_COUNT
MIN_TIMER_BITS
RESET_VALUE
XIOModule IOModule
volatile int TimerExpired[XTC_DEVICE_TIMER_COUNT][XTC_DEVICE_TIMER_COUNT]
XStatus IOModuleIntrExample(XIOModule *IOModuleInstancePtr, u32 DeviceId)
This function does a minimal test on the IO Module device and driver as a design example.
The purpose of this function is to illustrate how to use the IO Module component. It initializes the Programmable Interval Timers and then sets it up in compare mode with auto reload such that a periodic interrupt is generated.This function uses interrupt driven mode of the IO Module. IOModuleInstancePtr is a pointer to the IO Module driver Instance DeviceId is the XPAR_<IOModule_instance>_DEVICE_ID value from xparameters.h XST_SUCCESS if the Test is successful, otherwise XST_FAILURE This function contains an infinite loop such that if interrupts are not working it may never return.
References XIOModule::CfgPtr, IOModuleDisableIntr, IOModuleHandler, IOModuleSetupIntrSystem, XIOModule_Config::PitPrescaler, XIOModule_Config::PitReadable, XIOModule_Config::PitSize, XIOModule_Config::PitUsed, XIOModule_Enable, XIOModule_Initialize, XIOModule_SelfTest, XIOModule_SetHandler, XIOModule_SetResetValue, XIOModule_Timer_SetOptions, XIOModule_Timer_Start, XIOModule_Timer_Stop.
Referenced by main.
void IOModuleHandler(void *CallBackRef, u8 Timer)
This function is the handler which performs processing for the IO module.
It is called from an interrupt context such that the amount of processing performed should be minimized. It is called when an interrupt occurs if interrupts are enabled.This handler provides an example of how to handle Programmable Interval Timer interrupts but is application specific. CallBackRef is a pointer to the callback function Timer is the number of the interrupt this handler is associated with. None. None.
References XIOModule_IsExpired, XIOModule_Timer_SetOptions.
Referenced by IOModuleIntrExample.
static void IOModuleSetupIntrSystem(void)
This function initializes and enables exception handling for interrupts in the processor.
IOModuleInstancePtr is the reference to the IO Module instance. None. None.
References XIOModule_DeviceInterruptHandler.
Referenced by IOModuleInterruptSetup, IOModuleIntrExample.
void IOModuleDisableIntr(XIOModule *IOModuleInstancePtr)
This function disables the interrupts for the IO Module.
IOModuleInstancePtr is a reference to the IO Module driver Instance. None. None.
References XIOModule_Disable.
Referenced by IOModuleIntrExample.
int main(void)
This is the main function for the IO Module example.
This function is not included if the example is generated from the TestAppGen test tool. None. XST_SUCCESS to indicate success, otherwise XST_FAILURE. None.
References IOModuleIntrExample.