xiomodule_l.h
XIOModule_EnableIntr
Enable specific interrupt(s) in the interrupt controller.
BaseAddress is the base address of the device EnableMask is the 32-bit value to write to the enable register. Each bit of the mask corresponds to an interrupt input signal that is connected to the interrupt controller (INT0 = LSB). Only the bits which are set in the mask will enable interrupts. None. C-style signature: void XIOModule_EnableIntr(UINTPTR BaseAddress, u32 EnableMask);
Referenced by IOModuleLowLevelExample.
XIOModule_DisableIntr
Disable specific interrupt(s) in the interrupt controller.
BaseAddress is the base address of the device DisableMask is the 32-bit value to write to enable register. Each bit of the mask corresponds to an interrupt input signal that is connected to the interrupt controller (INT0 = LSB). Only bits which are set in the mask will disable interrupts. None. C-style signature: void XIOModule_DisableIntr(UINTPTR BaseAddress, u32 DisableMask);
XIOModule_AckIntr
Acknowledge specific interrupt(s) in the interrupt controller.
BaseAddress is the base address of the device AckMask is the 32-bit value to write to the acknowledge register. Each bit of the mask corresponds to an interrupt input signal that is connected to the interrupt controller (INT0 = LSB). Only the bits which are set in the mask will acknowledge interrupts. None. C-style signature: void XIOModule_AckIntr(UINTPTR BaseAddress, u32 AckMask);
Referenced by XIOModule_DeviceInterruptHandler.
XIOModule_GetIntrStatus
Get the interrupt status from the interrupt controller which indicates which interrupts are active and enabled.
BaseAddress is the base address of the device The 32-bit contents of the interrupt status register. Each bit corresponds to an interrupt input signal that is connected to the interrupt controller (INT0 = LSB). Bits which are set indicate an active interrupt which is also enabled. C-style signature: u32 XIOModule_GetIntrStatus(UINTPTR BaseAddress);
Referenced by XIOModule_DeviceInterruptHandler.
XIOModule_GetStatusReg
Get the contents of the UART status register.
Use the XUL_SR_* constants defined above to interpret the bit-mask returned. BaseAddress is the base address of the device A 32-bit value representing the contents of the status register. C-style Signature: u32 XIOModule_GetStatusReg(UINTPTR BaseAddress);
Referenced by XIOModule_ReceiveBuffer, XIOModule_SendBuffer, XIOModule_Uart_InterruptHandler.
XIOModule_IsReceiveEmpty
Check to see if the UART receiver has data.
BaseAddress is the base address of the device TRUE if the receiver is empty, FALSE if there is data present. C-style Signature: int XIOModule_IsReceiveEmpty(UINTPTR BaseAddress);
Referenced by XIOModule_RecvByte.
XIOModule_IsTransmitFull
Check to see if the transmitter is full.
BaseAddress is the base address of the device TRUE if the transmitter is full, FALSE otherwise. C-style Signature: int XIOModule_IsTransmitFull(UINTPTR BaseAddress);
Referenced by XIOModule_SendByte.
XIOModule_WriteReg
Write a value to a GPO register.
A 32 bit write is performed. If the GPO component is implemented in a smaller width, only the least significant data is written. BaseAddress is the base address of the GPO device. RegOffset is the register offset from the base to write to. Data is the data written to the register. None. C-style signature: void XIOModule_WriteReg(UINTPTR BaseAddress, unsigned RegOffset, u32 Data)
Referenced by XIOModule_DiscreteClear, XIOModule_DiscreteSet, XIOModule_DiscreteWrite, XIOModule_Reset, XIOModule_SendBuffer, XIOModule_SetBaudRate, XIOModule_SetResetValue, XIOModule_Timer_Initialize, XIOModule_Timer_InterruptHandler, XIOModule_Timer_SetOptions, XIOModule_Timer_Start, XIOModule_Timer_Stop.
XIOModule_ReadReg
Read a value from a GPI register.
A 32 bit read is performed. If the GPI component is implemented in a smaller width, only the least significant data is read from the register. The most significant data will be read as 0. BaseAddress is the base address of the GPI device. RegOffset is the register offset from the base to read from. Data read from the register. C-style signature: u32 XIOModule_ReadReg(UINTPTR BaseAddress, unsigned RegOffset)
Referenced by XIOModule_DiscreteRead, XIOModule_GetValue, XIOModule_IsExpired, XIOModule_IsSending, XIOModule_ReceiveBuffer, XIOModule_Timer_InterruptHandler.
typedef void(* XFastInterruptHandler)(void))(void)
void XIOModule_SendByte(UINTPTR BaseAddress, u8 Data)
This functions sends a single byte using the UART.
It is blocking in that it waits for the transmitter to become non-full before it writes the byte to the transmit register. BaseAddress is the base address of the device Data is the byte of data to send None. None.
References XIOModule_IsTransmitFull.
u8 XIOModule_RecvByte(UINTPTR BaseAddress)
This functions receives a single byte using the UART.
It is blocking in that it waits for the receiver to become non-empty before it reads from the receive register. BaseAddress is the base address of the device The byte of data received. None.
References XIOModule_IsReceiveEmpty.
void XIOModule_DeviceInterruptHandler(void *DeviceId)
This function is the primary interrupt handler for the driver.
It must be connected to the interrupt source such that is called when an interrupt of the interrupt controller is active. It will resolve which interrupts are active and enabled and call the appropriate interrupt handler. It uses the AckBeforeService flag in the configuration data to determine when to acknowledge the interrupt. Highest priority interrupts are serviced first. The driver can be configured to service only the highest priority interrupt or all pending interrupts using the {XIOModule_SetOptions()} function or the {XIOModule_SetIntrSrvOption()} function.This function assumes that an interrupt vector table has been previously initialized. It does not verify that entries in the table are valid before calling an interrupt handler, except skipping null handlers that indicate use of fast interrupts where the hardware directly jumps to the handler. DeviceId is the zero-based device ID defined in xparameters.h of the interrupting interrupt controller. It is used as a direct index into the configuration data, which contains the vector table for the interrupt controller. Note that even though the argument is a void pointer, the value is not a pointer but the actual device ID. The void pointer type is necessary to meet the XInterruptHandler typedef for interrupt handlers. None. The constant XPAR_IOMODULE_MAX_INTR_SIZE must be setup for this to compile. Interrupt IDs range from 0 - 31 and correspond to the interrupt input signals for the interrupt controller. XPAR_IOMODULE_MAX_INTR_SIZE specifies the highest numbered interrupt input signal that is used.
References XIOModule_VectorTableEntry::CallBackRef, XIOModule_VectorTableEntry::Handler, XIOModule_AckIntr, XIOModule_ConfigTable, XIOModule_GetIntrStatus, XIOModule_LookupConfig.
Referenced by IOModuleSetupIntrSystem, SetupInterruptSystem, XIOModule_InterruptHandler.
void XIOModule_SetIntrSvcOption(UINTPTR BaseAddress, s32 Option)
Set the interrupt service option, which can configure the driver so that it services only a single interrupt at a time when an interrupt occurs, or services all pending interrupts when an interrupt occurs.
The default behavior when using the driver interface given in xintc.h file is to service only a single interrupt, whereas the default behavior when using the driver interface given in this file is to service all outstanding interrupts when an interrupt occurs. BaseAddress is the unique identifier for a device. Option is XIN_SVC_SGL_ISR_OPTION if you want only a single interrupt serviced when an interrupt occurs, or XIN_SVC_ALL_ISRS_OPTION if you want all pending interrupts serviced when an interrupt occurs. None. Note that this function has no effect if the input base address is invalid.
References XIOModule_Config::Options.
void XIOModule_RegisterHandler(UINTPTR BaseAddress, s32 InterruptId, XInterruptHandler Handler, void *CallBackRef)
Register a handler function for a specific interrupt ID.
The vector table of the interrupt controller is updated, overwriting any previous handler. The handler function will be called when an interrupt occurs for the given interrupt ID.This function can also be used to remove a handler from the vector table by passing in the XIOModule_DefaultHandler() as the handler and NULL as the callback reference. BaseAddress is the base address of the interrupt controller whose vector table will be modified. InterruptId is the interrupt ID to be associated with the input handler. Handler is the function pointer that will be added to the vector table for the given interrupt ID. It adheres to the XInterruptHandler signature found in xbasic_types.h. CallBackRef is the argument that will be passed to the new handler function when it is called. This is user-specific. None. Only used with normal interrupt mode. Does not restore normal interrupt mode. Note that this function has no effect if the input base address is invalid.
References XIOModule_VectorTableEntry::CallBackRef, XIOModule_VectorTableEntry::Handler, XIOModule_Config::HandlerTable.
Referenced by IOModuleLowLevelExample.