xiomodule_options.c
s32 XIOModule_SetOptions(XIOModule *InstancePtr, u32 Options)
Set the options for the interrupt controller driver.
InstancePtr is a pointer to the XIOModule instance to be worked on. Options to be set. The available options are described in xiomodule.h. XST_SUCCESS if the options were set successfullyXST_INVALID_PARAM if the specified option was not valid None.
References XIOModule::CfgPtr, XIOModule::IsReady, XIOModule_Config::Options.
u32 XIOModule_GetOptions(XIOModule *InstancePtr)
Return the currently set options.
InstancePtr is a pointer to the XIOModule instance to be worked on. The currently set options. The options are described in xiomodule.h. None.
References XIOModule::CfgPtr, XIOModule::IsReady, XIOModule_Config::Options.
void XIOModule_Timer_SetOptions(XIOModule *InstancePtr, u8 TimerNumber, u32 Options)
Enables the specified options for the specified timer .
This function sets the options without regard to the current options of the driver. To prevent a loss of the current options, the user should call XIOModule_Timer_GetOptions() prior to this function and modify the retrieved options to pass into this function to prevent loss of the current options. InstancePtr is a pointer to the XIOModule instance. TimerNumber is the timer of the device to operate on. Each device may contain multiple timers. The timer number is a zero based number with a range of 0 to (XTC_DEVICE_TIMER_COUNT - 1). Options contains the desired options to be set or cleared. Setting the option to '1' enables the option, clearing the to '0' disables the option. The options are bit masks such that multiple options may be set or cleared. The options are described in xiomodule.h. None. None.
References XIOModule::BaseAddress, XIOModule::CurrentTCSR, XIOModule::IsReady, XIOModule_WriteReg.
Referenced by IOModuleHandler, IOModuleIntrExample, XIOModule_Timer_SelfTest.
u32 XIOModel_Timer_GetOptions(XIOModule *InstancePtr, u8 TimerNumber)
Get the options for the specified timer.
InstancePtr is a pointer to the XIOModule instance. TimerNumber is the timer of the device to operate on Each device may contain multiple timer. The timer number is a zero based number with a range of 0 to (XTC_DEVICE_TIMER_COUNT - 1). The currently set options. An option which is set to a '1' is enabled and set to a '0' is disabled. The options are bit masks such that multiple options may be set or cleared. The options are described in xiomodule.h.None.
References XIOModule::CurrentTCSR, XIOModule::IsReady.