xiomodule.c
u32 XIOModule_BitPosMask[XPAR_IOMODULE_INTC_MAX_INTR_SIZE][XPAR_IOMODULE_INTC_MAX_INTR_SIZE]
static void StubHandler(void *CallBackRef)
A stub for the asynchronous callback.
The stub is here in case the upper layers forget to set the handler. CallBackRef is a pointer to the upper layer callback reference None. None.
s32 XIOModule_Initialize(XIOModule *InstancePtr, u32 BaseAddress)
Initialize a specific interrupt controller instance/driver.
The initialization entails: - Initialize fields of the XIOModule structure - Initial vector table with stub function calls - All interrupt sources are disabled - Interrupt output is disabled - All timers are initialized InstancePtr is a pointer to the XIOModule instance to be worked on. BaseAddress is the base address of the device XST_SUCCESS if initialization was successfulXST_DEVICE_IS_STARTED if the device has already been startedXST_DEVICE_NOT_FOUND if device configuration information was not found for a device with the supplied device ID/BaseAddress. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XIOModule_Config::BaseAddress, XIOModule::BaseAddress, XIOModule_Config::BaseVector, XIOModule::CfgPtr, XIOModule::CurrentIER, XIOModule::CurrentIMR, XIOModule_Config::FastIntr, XIOModule_Config::GpoInit, XIOModule::GpoValue, XIOModule_Config::IoBaseAddress, XIOModule::IoBaseAddress, XIOModule::IsReady, XIOModule::IsStarted, XIOModule_Config::Options, XIOModule_Config::VectorAddrWidth, XIOModule_CfgInitialize, XIOModule_HandlerTable_Initialize, XIOModule_LookupConfig, XIOModule_Timer_Initialize.
Referenced by IOModuleInterruptSetup, IOModuleIntrExample, IOModuleSelfTestExample.
void XIOModule_HandlerTable_Initialize(XIOModule *InstancePtr)
Initializes all interrupt handlers to default handler for each interrupt ID.
It is necessary for the caller to connect the interrupt handler of this component to the proper interrupt source. InstancePtr is a pointer to the XIOModule instance to be worked on. None. None.
References XIOModule_VectorTableEntry::CallBackRef, XIOModule::CfgPtr, XIOModule_VectorTableEntry::Handler, XIOModule_Config::HandlerTable.
Referenced by XIOModule_Initialize.
s32 XIOModule_Start(XIOModule *InstancePtr)
Starts the IO Module.
Interrupts may be generated by the IO Module after this function is called.It is necessary for the caller to connect the interrupt handler of this component to the proper interrupt source. InstancePtr is a pointer to the XIOModule instance to be worked on. XST_SUCCESS if the device was started successfullyXST_FAILURE if simulation mode was specified and it could not be set because real mode has already been entered. Must be called after XIOModule initialization is completed.
References XIOModule::IsReady, XIOModule::IsStarted.
Referenced by IOModuleInterruptSetup.
void XIOModule_Stop(XIOModule *InstancePtr)
Stops the interrupt controller by disabling the output from the controller so that no interrupts will be caused by the interrupt controller.
InstancePtr is a pointer to the XIOModule instance to be worked on. None. None.
References XIOModule::IsReady, XIOModule::IsStarted.
s32 XIOModule_Connect(XIOModule *InstancePtr, u8 Id, XInterruptHandler Handler, void *CallBackRef)
Makes the connection between the Id of the interrupt source and the associated handler that is to run when the interrupt is recognized.
The argument provided in this call as the Callbackref is used as the argument for the handler when it is called. InstancePtr is a pointer to the XIOModule instance to be worked on. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_IOMODULE_INTC_MAX_INTR_SIZE - 1 with 0 being the highest priority interrupt. Handler to the handler for that interrupt. CallBackRef is the callback reference, usually the instance pointer of the connecting driver. XST_SUCCESS if the handler was connected correctly. Only used with normal interrupt mode. Does not restore normal interrupt mode. WARNING: The handler provided as an argument will overwrite any handler that was previously connected.
References XIOModule_VectorTableEntry::CallBackRef, XIOModule::CfgPtr, XIOModule_VectorTableEntry::Handler, XIOModule_Config::HandlerTable, XIOModule::IsReady.
void XIOModule_Disconnect(XIOModule *InstancePtr, u8 Id)
Updates the interrupt table with the Null Handler and NULL arguments at the location pointed at by the Id.
This effectively disconnects that interrupt source from any handler. The interrupt is disabled also. InstancePtr is a pointer to the XIOModule instance to be worked on. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_IOMODULE_INTC_MAX_INTR_SIZE - 1 with 0 being the highest priority interrupt. None. None.
References XIOModule::BaseAddress, XIOModule_VectorTableEntry::CallBackRef, XIOModule::CfgPtr, XIOModule::CurrentIER, XIOModule_VectorTableEntry::Handler, XIOModule_Config::HandlerTable, XIOModule::IsReady.
void XIOModule_Enable(XIOModule *InstancePtr, u8 Id)
Enables the interrupt source provided as the argument Id.
Any pending interrupt condition for the specified Id will occur after this function is called. InstancePtr is a pointer to the XIOModule instance to be worked on. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_IOMODULE_INTC_MAX_INTR_SIZE - 1 with 0 being the highest priority interrupt. None. None.
References XIOModule::BaseAddress, XIOModule::CurrentIER, XIOModule::IsReady.
Referenced by IOModuleIntrExample.
void XIOModule_Disable(XIOModule *InstancePtr, u8 Id)
Disables the interrupt source provided as the argument Id such that the interrupt controller will not cause interrupts for the specified Id.
The interrupt controller will continue to hold an interrupt condition for the Id, but will not cause an interrupt. InstancePtr is a pointer to the XIOModule instance to be worked on. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_IOMODULE_INTC_MAX_INTR_SIZE - 1 with 0 being the highest priority interrupt. None. None.
References XIOModule::BaseAddress, XIOModule::CurrentIER, XIOModule::IsReady.
Referenced by IOModuleDisableIntr.
void XIOModule_Acknowledge(XIOModule *InstancePtr, u8 Id)
Acknowledges the interrupt source provided as the argument Id.
When the interrupt is acknowledged, it causes the interrupt controller to clear its interrupt condition. InstancePtr is a pointer to the XIOModule instance to be worked on. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_IOMODULE_INTC_MAX_INTR_SIZE - 1 with 0 being the highest priority interrupt. None. None.
References XIOModule::BaseAddress, XIOModule::IsReady.
XIOModule_Config * XIOModule_LookupConfig(u32 BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
A table contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the XIOModule configuration structure for the specified device, or NULL if the device ID/BaseAddress was not found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XIOModule_ConfigTable.
Referenced by XIOModule_DeviceInterruptHandler, XIOModule_Initialize, XIOModule_Timer_Initialize.
s32 XIOModule_ConnectFastHandler(XIOModule *InstancePtr, u8 Id, XFastInterruptHandler Handler)
Makes the connection between the Id of the interrupt source and the associated handler that is to run when the interrupt is recognized.
InstancePtr is a pointer to the XIOModule instance. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_INTC_MAX_NUM_INTR_INPUTS - 1 with 0 being the highest priority interrupt. Handler to the handler for that interrupt. XST_SUCCESS if the handler was connected correctly. Only used with fast interrupt mode. WARNING: The handler provided as an argument will overwrite any handler that was previously connected.
References XIOModule::BaseAddress, XIOModule_VectorTableEntry::CallBackRef, XIOModule::CfgPtr, XIOModule::CurrentIER, XIOModule::CurrentIMR, XIOModule_Config::FastIntr, XIOModule_VectorTableEntry::Handler, XIOModule_Config::HandlerTable, XIOModule::IsReady, XIOModule_Config::VectorAddrWidth.
void XIOModule_SetNormalIntrMode(XIOModule *InstancePtr, u8 Id)
Sets the normal interrupt mode for the specified interrupt in the Interrupt Mode Register, by resetting the vector to (BaseVector & 0xFFFFFF80) | 0x10 and selecting normal mode.
InstancePtr is a pointer to the XIOModule instance. Id contains the ID of the interrupt source and should be in the range of 0 to XPAR_INTC_MAX_NUM_INTR_INPUTS - 1 with 0 being the highest priority interrupt. None. Only used with fast interrupt mode.
References XIOModule::BaseAddress, XIOModule_Config::BaseVector, XIOModule_VectorTableEntry::CallBackRef, XIOModule::CfgPtr, XIOModule::CurrentIER, XIOModule::CurrentIMR, XIOModule_Config::FastIntr, XIOModule_VectorTableEntry::Handler, XIOModule_Config::HandlerTable, XIOModule::IsReady, XIOModule_Config::VectorAddrWidth.
u32 XIOModule_DiscreteRead(XIOModule *InstancePtr, u32 Channel)
Read state of discretes for the specified GPI channel.
InstancePtr is a pointer to an XIOModule instance to be worked on. Channel contains the channel of the GPI (1, 2, 3 or 4) to operate on. Current copy of the discretes register.
References XIOModule::BaseAddress, XIOModule::IsReady, XIOModule_ReadReg.
void XIOModule_DiscreteWrite(XIOModule *InstancePtr, u32 Channel, u32 Data)
Write to discretes register for the specified GPO channel.
InstancePtr is a pointer to an XIOModule instance to be worked on. Channel contains the channel of the GPO (1, 2, 3 or 4) to operate on. Data is the value to be written to the discretes register. None.
References XIOModule::BaseAddress, XIOModule::GpoValue, XIOModule::IsReady, XIOModule_WriteReg.
s32 XIOModule_Timer_Initialize(XIOModule *InstancePtr, u32 BaseAddress)
Initializes a specific timer instance/driver.
Initialize fields of the XIOModule structure, then reset the timer InstancePtr is a pointer to the XIOModule instance. BaseAddress is the base address of the device XST_SUCCESS if initialization was successfulXST_DEVICE_IS_STARTED if the device has already been startedXST_DEVICE_NOT_FOUND if the device doesn't exist In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XIOModule_Config::BaseAddress, XIOModule::BaseAddress, XIOModule::CallBackRef, XIOModule::CurrentTCSR, XIOModule::CurrentTLR, XIOModule::Handler, XIOModule_Timer_Stats::Interrupts, XIOModule::IsReady, XIOModule::Timer_Stats, XIOModule_LookupConfig, XIOModule_WriteReg.
Referenced by XIOModule_Initialize.
void XIOModule_Timer_Start(XIOModule *InstancePtr, u8 TimerNumber)
Starts the specified timer counter of the device such that it starts running.
The timer counter is reset before it is started and the reset value is loaded into the timer counter.If interrupt mode is specified in the options, it is necessary for the caller to connect the interrupt handler of the timer to the interrupt source, typically an interrupt controller, and enable the interrupt within the interrupt controller. InstancePtr is a pointer to the XIOModule instance. TimerNumber is the timer of the device to operate on. Each device may contain multiple timers. The timer number is a zero based number with a range of 0 to (XTC_DEVICE_TIMER_COUNT - 1). None. None.
References XIOModule::BaseAddress, XIOModule::CurrentTCSR, XIOModule::IsReady, XIOModule_WriteReg.
Referenced by IOModuleIntrExample, XIOModule_Timer_SelfTest.
void XIOModule_Timer_Stop(XIOModule *InstancePtr, u8 TimerNumber)
Stops the timer by disabling it.
It is the callers' responsibility to disconnect the interrupt handler of the timer from the interrupt source, typically an interrupt controller, and disable the interrupt within the interrupt controller. InstancePtr is a pointer to the XIOModule instance. TimerNumber is the timer counter of the device to operate on. Each device may contain multiple timer counters. The timer number is a zero based number with a range of 0 to (XTC_DEVICE_TIMER_COUNT - 1). None. None.
References XIOModule::BaseAddress, XIOModule::CurrentTCSR, XIOModule::IsReady, XIOModule_WriteReg.
Referenced by IOModuleIntrExample, XIOModule_Timer_SelfTest.
u32 XIOModule_GetValue(XIOModule *InstancePtr, u8 TimerNumber)
Get the current value of the specified timer counter.
The timer counter may be either incrementing or decrementing based upon the current mode of operation. InstancePtr is a pointer to the XIOModule instance. TimerNumber is the timer counter of the device to operate on. Each device may contain multiple timer counters. The timer number is a zero based number with a range of 0 to (XTC_DEVICE_TIMER_COUNT - 1). The current value for the timer counter. None.
References XIOModule::BaseAddress, XIOModule::IsReady, XIOModule_ReadReg.
Referenced by XIOModule_Timer_SelfTest.
void XIOModule_SetResetValue(XIOModule *InstancePtr, u8 TimerNumber, u32 ResetValue)
Set the reset value for the specified timer counter.
This is the value that is loaded into the timer counter when it is reset. This value is also loaded when the timer counter is started. InstancePtr is a pointer to the XIOModule instance. TimerNumber is the timer counter of the device to operate on. Each device may contain multiple timer counters. The timer number is a zero based number with a range of 0 to (XTC_DEVICE_TIMER_COUNT - 1). ResetValue contains the value to be used to reset the timer counter. None. None.
References XIOModule::BaseAddress, XIOModule::CurrentTLR, XIOModule::IsReady, XIOModule_WriteReg.
Referenced by IOModuleIntrExample, XIOModule_Timer_SelfTest.
u32 XIOModule_GetCaptureValue(XIOModule *InstancePtr, u8 TimerNumber)
Returns the timer counter value that was captured the last time the external capture input was asserted.
InstancePtr is a pointer to the XIOModule instance. TimerNumber is the timer counter of the device to operate on. Each device may contain multiple timer counters. The timer number is a zero based number with a range of 0 to (XTC_DEVICE_TIMER_COUNT - 1). The current capture value for the indicated timer counter. None.
References XIOModule::CurrentTLR, XIOModule::IsReady.
void XIOModule_Reset(XIOModule *InstancePtr, u8 TimerNumber)
Resets the specified timer counter of the device.
A reset causes the timer counter to set it's value to the reset value. InstancePtr is a pointer to the XIOModule instance. TimerNumber is the timer counter of the device to operate on. Each device may contain multiple timer counters. The timer number is a zero based number with a range of 0 to (XTC_DEVICE_TIMER_COUNT - 1). None. None.
References XIOModule::BaseAddress, XIOModule::CurrentTCSR, XIOModule::IsReady, XIOModule_WriteReg.
s32 XIOModule_IsExpired(XIOModule *InstancePtr, u8 TimerNumber)
Checks if the specified timer counter of the device has expired.
In capture mode, expired is defined as a capture occurred. In compare mode, expired is defined as the timer counter rolled over/under for up/down counting.When interrupts are enabled, the expiration causes an interrupt. This function is typically used to poll a timer counter to determine when it has expired. InstancePtr is a pointer to the XIOModule instance. TimerNumber is the timer counter of the device to operate on. Each device may contain multiple timer counters. The timer number is a zero based number with a range of 0 to (XTC_DEVICE_TIMER_COUNT - 1). TRUE if the timer has expired, and FALSE otherwise. None.
References XIOModule::BaseAddress, XIOModule::CfgPtr, XIOModule::CurrentTCSR, XIOModule::IsReady, XIOModule_Config::PitMask, XIOModule_Config::PitReadable, XIOModule_ReadReg.
Referenced by IOModuleHandler.
u32 XIOModule_IoReadWord(XIOModule *InstancePtr, u32 ByteOffset)
Read 32-bit word from the IO Bus memory mapped IO.
InstancePtr is a pointer to an XIOModule instance to be worked on. ByteOffset is a byte offset from the beginning of the IO Bus address area Value read from the IO Bus - 32-bit word
References XIOModule::IoBaseAddress, XIOModule::IsReady.
u16 XIOModule_IoReadHalfword(XIOModule *InstancePtr, u32 ByteOffset)
Read 16-bit halfword from the IO Bus memory mapped IO.
InstancePtr is a pointer to an XIOModule instance to be worked on. ByteOffset is a byte offset from the beginning of the IO Bus address area Value read from the IO Bus - 16-bit halfword
References XIOModule::IoBaseAddress, XIOModule::IsReady.
u8 XIOModule_IoReadByte(XIOModule *InstancePtr, u32 ByteOffset)
Read byte from the IO Bus memory mapped IO.
InstancePtr is a pointer to an XIOModule instance to be worked on. ByteOffset is a byte offset from the beginning of the IO Bus address area Value read from the IO Bus - 8-bit byte
References XIOModule::IoBaseAddress, XIOModule::IsReady.
void XIOModule_IoWriteWord(XIOModule *InstancePtr, u32 ByteOffset, u32 Data)
Write 32-bit word to the IO Bus memory mapped IO.
InstancePtr is a pointer to an XIOModule instance to be worked on. ByteOffset is a byte offset from the beginning of the IO Bus address area Data is the value to be written to the IO Bus - 32-bit None.
References XIOModule::IoBaseAddress, XIOModule::IsReady.
void XIOModule_IoWriteHalfword(XIOModule *InstancePtr, u32 ByteOffset, u16 Data)
Write 16-bit word to the IO Bus memory mapped IO.
InstancePtr is a pointer to an XIOModule instance to be worked on. ByteOffset is a byte offset from the beginning of the IO Bus address area Data is the value to be written to the IO Bus - 16-bit None.
References XIOModule::IoBaseAddress, XIOModule::IsReady.
void XIOModule_IoWriteByte(XIOModule *InstancePtr, u32 ByteOffset, u8 Data)
Write 8-bit word to the IO Bus memory mapped IO.
InstancePtr is a pointer to an XIOModule instance to be worked on. ByteOffset is a byte offset from the beginning of the IO Bus address area Data is the value to be written to the IO Bus - 8-bit None.
References XIOModule::IoBaseAddress, XIOModule::IsReady.