xdprxss_debug_example.c
DPRXSS_LINK_RATE
DPRXSS_LANE_COUNT
XDpRxSs DpRxSsInst
u32 DpRxSs_DebugExample(UINTPTR BaseAddress)
This function is the main entry point for the debug example using the XDpRxSs driver.
This function will print values set during DisplayPort RX Subsystem set up to work in MST/SST mode. DeviceId is the unique device ID of the DisplayPort RX Subsystem core. XST_SUCCESS if DisplayPort RX Subsystem prints debug information successfully.XST_FAILURE, otherwise. None.
References XDpRxSs_Config::BaseAddress, DpRxSs_PlatformInit, DpRxSs_Setup, DpRxSs_VideoPhyInit, XDpRxSs_UsrOpt::MstSupport, XDpRxSs::UsrOpt, XDpRxSs_CfgInitialize, XDpRxSs_LookupConfig, XDpRxSs_ReportCoreInfo, XDpRxSs_ReportHdcpInfo, XDpRxSs_ReportLinkInfo, XDpRxSs_ReportMsaInfo, XDpRxSs_SetLaneCount, XDpRxSs_SetLinkRate, XDpRxSs_Start.
Referenced by main.
u32 DpRxSs_PlatformInit(void)
This function initialize required platform specific peripherals.
None. XST_SUCCESS if required peripherals are initialized and configured successfully.XST_FAILURE, otherwise. None.
Referenced by DpRxSs_DebugExample, DpRxSs_HdcpExample, DpRxSs_IntrExample, DpRxSs_MstExample.
u32 DpRxSs_VideoPhyInit(void)
This function configures Video Phy.
None. XST_SUCCESS if Video Phy configured successfully.XST_FAILURE, otherwise. None.
Referenced by DpRxSs_DebugExample, DpRxSs_HdcpExample, DpRxSs_IntrExample, DpRxSs_MstExample.
u32 DpRxSs_Setup(void)
This function configures DisplayPort RX Subsystem.
None. XST_SUCCESS if DPRX Subsystem configured successfully.XST_FAILURE, otherwise. None.
Referenced by DpRxSs_DebugExample, DpRxSs_HdcpExample, DpRxSs_IntrExample, DpRxSs_MstExample.
int main()
This is the main function for XDpRxSs SST/MST example.
None. XST_SUCCESS if the MST/SST example passed.XST_FAILURE if the MST/SST example was unsuccessful. None.
References DpRxSs_DebugExample.