xdprxss_intr_example.c
XINTC_DPRXSS_DP_INTERRUPT_ID
XINTC_DEVICE_ID
XINTC
XINTC_HANDLER
XDPRXSS_DEVICE_ID
DPRXSS_LINK_RATE
DPRXSS_LANE_COUNT
INTRNAME_DPRX
INTRNAME_DPRX_TIMER
INTRNAME_DPRX_CIPHER
XDpRxSs DpRxSsInst
u32 DpRxSs_IntrExample(UINTPTR BaseAddress)
This function is the main entry point for the interrupt example using the XDpRxSs driver.
This function will setup the system with interrupts handlers. DeviceId is the unique device ID of the DisplayPort RX Subsystem core. XST_FAILURE if the system setup failed.XST_SUCCESS should never return since this function, if setup was successful, is blocking. If system setup was successful, this function is blocking in order to illustrate interrupt handling taking place for different types interrupts. Refer xdprxss.h file for more info.
References XDpRxSs_Config::BaseAddress, DpRxSs_PlatformInit, DpRxSs_Setup, DpRxSs_SetupIntrSystem, DpRxSs_VideoPhyInit, XDpRxSs_UsrOpt::MstSupport, XDpRxSs::UsrOpt, XDpRxSs_CfgInitialize, XDpRxSs_LookupConfig, XDpRxSs_SetLaneCount, XDpRxSs_SetLinkRate, XDpRxSs_Start.
Referenced by main.
u32 DpRxSs_PlatformInit(void)
This function initialize required platform specific peripherals.
None. XST_SUCCESS if required peripherals are initialized and configured successfully.XST_FAILURE, otherwise. None.
u32 DpRxSs_VideoPhyInit(void)
This function configures Video Phy.
None. XST_SUCCESS if Video Phy configured successfully.XST_FAILURE, otherwise. None.
u32 DpRxSs_Setup(void)
This function configures DisplayPort RX Subsystem.
None. XST_SUCCESS if DP RX Subsystem configured successfully.XST_FAILURE, otherwise. None.
u32 DpRxSs_SetupIntrSystem(void)
This function sets up the interrupt system so interrupts can occur for the DisplayPort RX Subsystem core.
The function is application-specific since the actual system may or may not have an interrupt controller. The DPRX Subsystem core could be directly connected to a processor without an interrupt controller. The user should modify this function to fit the application. None XST_SUCCESS if interrupt setup was successful.A specific error code defined in "xstatus.h" if an error occurs. None.
Referenced by DpRxSs_IntrExample, DpRxSs_MstExample.
void DpRxSs_VideoModeHandler(void *InstancePtr)
This function is the callback function for when a video mode change interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_PowerChangeHandler(void *InstancePtr)
This function is the callback function for when the power state interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_NoVideoHandler(void *InstancePtr)
This function is the callback function for when a no video interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_VerticalBlankHandler(void *InstancePtr)
This function is the callback function for when a vertical blank interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_TrainingLostHandler(void *InstancePtr)
This function is the callback function for when a training lost interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_VideoHandler(void *InstancePtr)
This function is the callback function for when a valid video interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_InfoPacketHandler(void *InstancePtr)
This function is the callback function for when an info packet interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_ExtPacketHandler(void *InstancePtr)
This function is the callback function for when arrival of external (audio) packet interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_TrainingDoneHandler(void *InstancePtr)
This function is the callback function for when the training done interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_BandwidthChangeHandler(void *InstancePtr)
This function is the callback function for when a bandwidth change interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_DownReqestHandler(void *InstancePtr)
This function is the callback function for when a down request interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
References XDpRxSs_HandleDownReq.
void DpRxSs_DownReplyHandler(void *InstancePtr)
This function is the callback function for when a down reply interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_AudioOverflowHandler(void *InstancePtr)
This function is the callback function for when an audio overflow interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_PayloadAllocationHandler(void *InstancePtr)
This function is the callback function for when a payload allocation interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_ActRxHandler(void *InstancePtr)
This function is the callback function for when an ACT sequence interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_CrcTestHandler(void *InstancePtr)
This function is the callback function for when a CRC test start interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_UnplugHandler(void *InstancePtr)
This function is the callback function for when the unplug event occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_LinkBandwidthHandler(void *InstancePtr)
This function is the callback function for when the link bandwidth change occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_PllResetHandler(void *InstancePtr)
This function is the callback function for PLL reset request.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
int main()
This is the main function for XDpRxSs interrupt example.
If the DpRxSs_IntrExample function which setup the system succeeds, this function will wait for the interrupts. None. XST_FAILURE if the interrupt example was unsuccessful. Unless setup failed, main will never return since DpRxSs_IntrExample is blocking (it is waiting on interrupts).
References DpRxSs_IntrExample.