xdprxss_mst_example.c
INTRNAME_DPRX
XINTC_DPRXSS_DP_INTERRUPT_ID
XINTC_DEVICE_ID
XINTC
XINTC_HANDLER
XTMR_CTRL_DEVICE_ID
XDPRXSS_DEVICE_ID
DPRXSS_LINK_RATE
DPRXSS_LANE_COUNT
XDpRxSs DpRxSsInst
XTmrCtr TmrCtrInst
u32 DpRxSs_MstExample(UINTPTR BaseAddress)
This function is the main entry point for the MST/SST example using the XDpRxSs driver.
DeviceId is the unique device ID of the DisplayPort RX Subsystem core. XST_SUCCESS if DisplayPort RX Subsystem configured in SST/MST successfully.XST_FAILURE, if DisplayPort RX Subsystem failed to configure in SST/MST. None.
References XDpRxSs_Config::BaseAddress, DpRxSs_PlatformInit, DpRxSs_Setup, DpRxSs_SetupIntrSystem, DpRxSs_SetupTimerHandler, DpRxSs_VideoPhyInit, XDpRxSs_UsrOpt::MstSupport, XDpRxSs::UsrOpt, XDpRxSs_CfgInitialize, XDpRxSs_LookupConfig, XDpRxSs_SetLaneCount, XDpRxSs_SetLinkRate, XDpRxSs_Start.
Referenced by main.
u32 DpRxSs_PlatformInit(void)
This function initialize required platform specific peripherals.
None. XST_SUCCESS if required peripherals are initialized and configured successfully.XST_FAILURE, otherwise. None.
u32 DpRxSs_VideoPhyInit(void)
This function configures Video Phy.
None. XST_SUCCESS if Video Phy configured successfully.XST_FAILURE, otherwise. None.
u32 DpRxSs_Setup(void)
This function configures DisplayPort RX Subsystem.
None. XST_SUCCESS if DPRX Subsystem configured successfully.XST_FAILURE, otherwise. None.
u32 DpRxSs_SetupIntrSystem(void)
This function sets up the interrupt system so interrupts can occur for the DisplayPort RX Subsystem core.
The function is application-specific since the actual system may or may not have an interrupt controller. The DPRX Subsystem core could be directly connected to a processor without an interrupt controller. The user should modify this function to fit the application. None XST_SUCCESS if interrupt setup was successful.A specific error code defined in "xstatus.h" if an error occurs. None.
void DpRxSs_VideoModeHandler(void *InstancePtr)
This function is the callback function for when a video mode change interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_NoVideoHandler(void *InstancePtr)
This function is the callback function for when a no video interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_VerticalBlankHandler(void *InstancePtr)
This function is the callback function for when a vertical blank interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_TrainingLostHandler(void *InstancePtr)
This function is the callback function for when a training lost interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_TrainingDoneHandler(void *InstancePtr)
This function is the callback function for when the training done interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_DownReqestHandler(void *InstancePtr)
This function is the callback function for when a down request interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_DownReplyHandler(void *InstancePtr)
This function is the callback function for when a down reply interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_UnplugHandler(void *InstancePtr)
This function is the callback function for when the unplug event occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_LinkBandwidthHandler(void *InstancePtr)
This function is the callback function for when the link bandwidth change occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_PllResetHandler(void *InstancePtr)
This function is the callback function for PLL reset request.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
u32 DpRxSs_SetupTimerHandler(void)
This function sets up a custom timer which the driver will use for MicroBlaze systems.
None. XST_SUCCESS if a timer controller exists for use.XST_FAILURE otherwise. A timer controller must be present in the system.
References XDpRxSs::DpPtr, DpRxSs_CustomWaitUs, XDpRxSs_SetUserTimerHandler.
Referenced by DpRxSs_MstExample.
void DpRxSs_CustomWaitUs(void *InstancePtr, u32 MicroSeconds)
This function is used to override the driver's default sleep functionality.
For MicroBlaze systems, the XDpRxSs_WaitUs driver function's default behavior is to use the MB_Sleep function from microblaze_sleep.h, which is implemented in software and only has millisecond accuracy. For this reason, using a hardware timer is preferable. For ARM/Zynq SoC systems, the SoC's timer is used - XDpRxSs_WaitUs will ignore this custom timer handler. InstancePtr is a pointer to the XDpRxSs core instance. MicroSeconds is the number of microseconds to delay/sleep for. None. Use the XDpRxSs_SetUserTimerHandler driver function to set this function as the handler for when the XDpRxSs_WaitUs driver function is called.
References XDpRxSs::DpPtr.
Referenced by DpRxSs_SetupTimerHandler.
void DpRxSs_DetectResolution(XDpRxSs *InstancePtr)
This function will present the resolution of the incoming video stream.
InstancePtr is a pointer to the XDpRxSs instance. None. The resolution will be rounded up to the nearest resolution present in the XVidC_VideoTimingModes table.
References XDpRxSs::DpPtr, XDPRXSS_MSA_HRES, XDPRXSS_MSA_VRES, XDpRxSs_ReadReg, XDpRxSs_WaitUs.
int main()
This is the main function for XDpRxSs SST/MST example.
None. XST_SUCCESS if the MST/SST example passed.XST_FAILURE if the MST/SST example was unsuccessful. None.
References DpRxSs_MstExample.