xtmrctr_selftest.c
int XTmrCtr_SelfTest(XTmrCtr *InstancePtr, u8 TmrCtrNumber)
Runs a self-test on the driver/device.
This test verifies that the specified timer counter of the device can be enabled and increments. InstancePtr is a pointer to the XTmrCtr instance. TmrCtrNumber is the timer counter of the device to operate on. Each device may contain multiple timer counters. The timer number is a zero based number with a range of 0 - (XTC_DEVICE_TIMER_COUNT - 1). XST_SUCCESS if self-test was successful XST_FAILURE if the timer is not incrementing. This is a destructive test using the provided timer. The current settings of the timer are returned to the initialized values and all settings at the time this function is called are overwritten.
References XTmrCtr::BaseAddress, XTmrCtr::IsReady, XTC_CSR_ENABLE_TMR_MASK, XTC_CSR_INT_OCCURED_MASK, XTC_CSR_LOAD_MASK, XTC_DEVICE_TIMER_COUNT, XTC_TCR_OFFSET, XTC_TCSR_OFFSET, XTC_TLR_OFFSET, XTmrCtr_ReadReg, XTmrCtr_WriteReg.
Referenced by TmrCtrCascadeIntrExample, TmrCtrFastIntrExample, TmrCtrIntrExample, TmrCtrPolledExample, TmrCtrPwmExample, TmrCtrSelfTestExample.