xtmrctr.h
XTC_CASCADE_MODE_OPTION
Used to configure the timer counter device.
XTC_CASCADE_MODE_OPTION Enables the Cascade Mode only valid for TCSRO. XTC_ENABLE_ALL_OPTION Enables all timer counters at once. XTC_DOWN_COUNT_OPTION Configures the timer counter to count down from start value, the default is to count up. XTC_CAPTURE_MODE_OPTION Configures the timer to capture the timer counter value when the external capture line is asserted. The default mode is compare mode. XTC_INT_MODE_OPTION Enables the timer counter interrupt output. XTC_AUTO_RELOAD_OPTION In compare mode, configures the timer counter to reload from the compare value. The default mode causes the timer counter to hold when the compare value is hit. In capture mode, configures the timer counter to not hold the previous capture value if a new event occurs. The default mode cause the timer counter to hold the capture value until recognized. XTC_EXT_COMPARE_OPTION Enables the external compare output signal.
Referenced by TmrCtrCascadeIntrExample.
XTC_ENABLE_ALL_OPTION
XTC_DOWN_COUNT_OPTION
XTC_CAPTURE_MODE_OPTION
XTC_INT_MODE_OPTION
XTC_AUTO_RELOAD_OPTION
XTC_EXT_COMPARE_OPTION
XTMRCTR_H
XTC_ROUND_DIV
XTC_HZ_TO_NS
typedef void(* XTmrCtr_Handler)(void *CallBackRef, u8 TmrCtrNumber))(void *CallBackRef, u8 TmrCtrNumber)
Signature for the callback function.
CallBackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. Its type is unimportant to the driver, so it is a void pointer. TmrCtrNumber is the number of the timer/counter within the device. The device typically contains at least two timer/counters. The timer number is a zero based number with a range of 0 to (XTC_DEVICE_TIMER_COUNT - 1).
void XTmrCtr_CfgInitialize(XTmrCtr *InstancePtr, XTmrCtr_Config *ConfigPtr, UINTPTR EffectiveAddr)
This function populates the timer counter's configuration structure and sets some configurations defaults.
InstancePtr is a pointer to the XTmrCtr instance. ConfigPtr is a pointer to the configuration structure that will be used to copy the settings from. EffectiveAddr is the device base address in the virtual memory space. If the address translation is not used, then the physical address is passed. None. Unexpected errors may occur if the address mapping is changed after this function is invoked.
References XTmrCtr_Config::BaseAddress, XTmrCtr::BaseAddress, XTmrCtr::CallBackRef, XTmrCtr::Config, XTmrCtr::Handler, XTmrCtrStats::Interrupts, XTmrCtr::IsReady, XTmrCtr::Stats.
Referenced by XTmrCtr_Initialize.
int XTmrCtr_InitHw(XTmrCtr *InstancePtr)
(Re-)initializes all timer counters which aren't started already.
InstancePtr is a pointer to the XTmrCtr instance. XST_SUCCESS if at least one timer counter is stopped.XST_DEVICE_IS_STARTED otherwise. None.
References XTmrCtr::BaseAddress, XTmrCtr::IsReady, XTmrCtr::IsStartedTmrCtr0, XTmrCtr::IsStartedTmrCtr1, XTC_CSR_INT_OCCURED_MASK, XTC_CSR_LOAD_MASK, XTC_DEVICE_TIMER_COUNT, XTC_TCSR_OFFSET, XTC_TLR_OFFSET, XTmrCtr_WriteReg.
Referenced by XTmrCtr_Initialize.
int XTmrCtr_Initialize(XTmrCtr *InstancePtr, UINTPTR BaseAddr)
Initializes a specific timer/counter instance/driver.
Initialize fields of the XTmrCtr structure, then reset the timer/counter.If a timer is already running then it is not initialized. InstancePtr is a pointer to the XTmrCtr instance. BaseAddr is the base address of the device XST_SUCCESS if initialization was successfulXST_DEVICE_IS_STARTED if the device has already been startedXST_DEVICE_NOT_FOUND if the device doesn't exist In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XTmrCtr_Config::BaseAddress, XTmrCtr::IsStartedTmrCtr0, XTmrCtr::IsStartedTmrCtr1, XTmrCtr_CfgInitialize, XTmrCtr_InitHw, XTmrCtr_LookupConfig.
Referenced by TmrCtrCascadeIntrExample, TmrCtrFastIntrExample, TmrCtrIntrExample, TmrCtrPolledExample, TmrCtrPwmExample, TmrCtrSelfTestExample.
void XTmrCtr_Start(XTmrCtr *InstancePtr, u8 TmrCtrNumber)
Starts the specified timer counter of the device such that it starts running.
The timer counter is reset before it is started and the reset value is loaded into the timer counter.If interrupt mode is specified in the options, it is necessary for the caller to connect the interrupt handler of the timer/counter to the interrupt source, typically an interrupt controller, and enable the interrupt within the interrupt controller. InstancePtr is a pointer to the XTmrCtr instance. TmrCtrNumber is the timer counter of the device to operate on. Each device may contain multiple timer counters. The timer number is a zero based number with a range of 0 - (XTC_DEVICE_TIMER_COUNT - 1). None. None.
References XTmrCtr::BaseAddress, XTmrCtr::IsReady, XTmrCtr::IsStartedTmrCtr0, XTmrCtr::IsStartedTmrCtr1, XTC_CSR_ENABLE_TMR_MASK, XTC_CSR_LOAD_MASK, XTC_DEVICE_TIMER_COUNT, XTC_TCSR_OFFSET, XTmrCtr_ReadReg, XTmrCtr_WriteReg.
Referenced by TmrCtrCascadeIntrExample, TmrCtrFastIntrExample, TmrCtrIntrExample, TmrCtrPolledExample.
void XTmrCtr_Stop(XTmrCtr *InstancePtr, u8 TmrCtrNumber)
Stops the timer counter by disabling it.
It is the callers' responsibility to disconnect the interrupt handler of the timer_counter from the interrupt source, typically an interrupt controller, and disable the interrupt within the interrupt controller. InstancePtr is a pointer to the XTmrCtr instance. TmrCtrNumber is the timer counter of the device to operate on. Each device may contain multiple timer counters. The timer number is a zero based number with a range of 0 - (XTC_DEVICE_TIMER_COUNT - 1). None. None.
References XTmrCtr::BaseAddress, XTmrCtr::IsReady, XTmrCtr::IsStartedTmrCtr0, XTmrCtr::IsStartedTmrCtr1, XTC_CSR_ENABLE_TMR_MASK, XTC_DEVICE_TIMER_COUNT, XTC_TCSR_OFFSET, XTmrCtr_ReadReg, XTmrCtr_WriteReg.
Referenced by TmrCtrCascadeIntrExample, TmrCtrFastIntrExample, TmrCtrIntrExample, XTmrCtr_PwmConfigure, XTmrCtr_PwmDisable.
u32 XTmrCtr_GetValue(XTmrCtr *InstancePtr, u8 TmrCtrNumber)
Get the current value of the specified timer counter.
The timer counter may be either incrementing or decrementing based upon the current mode of operation. InstancePtr is a pointer to the XTmrCtr instance. TmrCtrNumber is the timer counter of the device to operate on. Each device may contain multiple timer counters. The timer number is a zero based number with a range of 0 - (XTC_DEVICE_TIMER_COUNT - 1). The current value for the timer counter. None.
References XTmrCtr::BaseAddress, XTmrCtr::IsReady, XTC_DEVICE_TIMER_COUNT, XTC_TCR_OFFSET, XTmrCtr_ReadReg.
Referenced by TmrCtrPolledExample.
void XTmrCtr_SetResetValue(XTmrCtr *InstancePtr, u8 TmrCtrNumber, u32 ResetValue)
Set the reset value for the specified timer counter.
This is the value that is loaded into the timer counter when it is reset. This value is also loaded when the timer counter is started. InstancePtr is a pointer to the XTmrCtr instance. TmrCtrNumber is the timer counter of the device to operate on. Each device may contain multiple timer counters. The timer number is a zero based number with a range of 0 - (XTC_DEVICE_TIMER_COUNT - 1). ResetValue contains the value to be used to reset the timer counter. None. None.
References XTmrCtr::BaseAddress, XTmrCtr::IsReady, XTC_DEVICE_TIMER_COUNT, XTC_TLR_OFFSET, XTmrCtr_WriteReg.
Referenced by TmrCtrCascadeIntrExample, TmrCtrFastIntrExample, TmrCtrIntrExample.
u32 XTmrCtr_GetCaptureValue(XTmrCtr *InstancePtr, u8 TmrCtrNumber)
Returns the timer counter value that was captured the last time the external capture input was asserted.
InstancePtr is a pointer to the XTmrCtr instance. TmrCtrNumber is the timer counter of the device to operate on. Each device may contain multiple timer counters. The timer number is a zero based number with a range of 0 - (XTC_DEVICE_TIMER_COUNT - 1). The current capture value for the indicated timer counter. None.
References XTmrCtr::BaseAddress, XTmrCtr::IsReady, XTC_DEVICE_TIMER_COUNT, XTC_TLR_OFFSET, XTmrCtr_ReadReg.
int XTmrCtr_IsExpired(XTmrCtr *InstancePtr, u8 TmrCtrNumber)
Checks if the specified timer counter of the device has expired.
In capture mode, expired is defined as a capture occurred. In compare mode, expired is defined as the timer counter rolled over/under for up/down counting.When interrupts are enabled, the expiration causes an interrupt. This function is typically used to poll a timer counter to determine when it has expired. InstancePtr is a pointer to the XTmrCtr instance. TmrCtrNumber is the timer counter of the device to operate on. Each device may contain multiple timer counters. The timer number is a zero based number with a range of 0 - (XTC_DEVICE_TIMER_COUNT - 1). TRUE if the timer has expired, and FALSE otherwise. None.
References XTmrCtr::BaseAddress, XTmrCtr::IsReady, XTC_CSR_INT_OCCURED_MASK, XTC_DEVICE_TIMER_COUNT, XTC_TCSR_OFFSET, XTmrCtr_ReadReg.
void XTmrCtr_Reset(XTmrCtr *InstancePtr, u8 TmrCtrNumber)
Resets the specified timer counter of the device.
A reset causes the timer counter to set it's value to the reset value. InstancePtr is a pointer to the XTmrCtr instance. TmrCtrNumber is the timer counter of the device to operate on. Each device may contain multiple timer counters. The timer number is a zero based number with a range of 0 - (XTC_DEVICE_TIMER_COUNT - 1). None. None.
References XTmrCtr::BaseAddress, XTmrCtr::IsReady, XTC_CSR_LOAD_MASK, XTC_DEVICE_TIMER_COUNT, XTC_TCSR_OFFSET, XTmrCtr_ReadReg, XTmrCtr_WriteReg.
Referenced by TmrCtrCascadeIntrExample, XTmrCtr_PwmDisable, XTmrCtr_PwmEnable.
u8 XTmrCtr_PwmConfigure(XTmrCtr *InstancePtr, u32 PwmPeriod, u32 PwmHighTime)
Configures timers to generate PWM output.
InstancePtr is a pointer to the XTmrCtr instance. PwmPeriod is the period of pwm signal in nano seconds. PwmHighTime is the high time of pwm signal in nano seconds. the duty cycle that will possibly be achieved. This function needs to be called before enabling PWM otherwise the output of PWM may be indeterminate. Here Down count mode of timers are used for generating PWM output.
References XTmrCtr::BaseAddress, XTmrCtr::Config, XTmrCtr::IsReady, XTmrCtr::IsStartedTmrCtr0, XTmrCtr::IsStartedTmrCtr1, XTmrCtr_Config::SysClockFreqHz, XTC_CSR_AUTO_RELOAD_MASK, XTC_CSR_CAPTURE_MODE_MASK, XTC_CSR_CASC_MASK, XTC_CSR_DOWN_COUNT_MASK, XTC_CSR_EXT_GENERATE_MASK, XTC_TCSR_OFFSET, XTC_TLR_OFFSET, XTmrCtr_ReadReg, XTmrCtr_Stop, XTmrCtr_WriteReg.
Referenced by TmrCtrPwmExample.
void XTmrCtr_PwmEnable(XTmrCtr *InstancePtr)
Enables the PWM output as per configurations set by XTmrCtr_PwmConfigure.
InstancePtr is a pointer to the XTmrCtr instance. none. none.
References XTmrCtr::BaseAddress, XTmrCtr::IsPwmEnabled, XTC_CSR_ENABLE_ALL_MASK, XTC_CSR_ENABLE_PWM_MASK, XTC_CSR_EXT_GENERATE_MASK, XTC_TCSR_OFFSET, XTmrCtr_ReadReg, XTmrCtr_Reset, XTmrCtr_WriteReg.
Referenced by TmrCtrPwmExample.
void XTmrCtr_PwmDisable(XTmrCtr *InstancePtr)
Disables the PWM output.
InstancePtr is a pointer to the XTmrCtr instance. none. Call to this function disables only the PWM output and do not alter any configuration. PWM output can again be enabled by calling XTmrCtr_PwmEnable without the need of re-configuration.
References XTmrCtr::BaseAddress, XTmrCtr::IsPwmEnabled, XTC_CSR_ENABLE_PWM_MASK, XTC_CSR_EXT_GENERATE_MASK, XTC_TCSR_OFFSET, XTmrCtr_ReadReg, XTmrCtr_Reset, XTmrCtr_Stop, XTmrCtr_WriteReg.
Referenced by TmrCtrPwmExample.
XTmrCtr_Config * XTmrCtr_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The table TmrCtr_ConfigTable contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration that matches the given device ID/BaseAddress, or NULL if no match is found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
Referenced by XTmrCtr_Initialize.
void XTmrCtr_SetOptions(XTmrCtr *InstancePtr, u8 TmrCtrNumber, u32 Options)
Enables the specified options for the specified timer counter.
This function sets the options without regard to the current options of the driver. To prevent a loss of the current options, the user should call XTmrCtr_GetOptions() prior to this function and modify the retrieved options to pass into this function to prevent loss of the current options. InstancePtr is a pointer to the XTmrCtr instance. TmrCtrNumber is the timer counter of the device to operate on. Each device may contain multiple timer counters. The timer number is a zero based number with a range of 0 - (XTC_DEVICE_TIMER_COUNT - 1). Options contains the desired options to be set or cleared. Setting the option to '1' enables the option, clearing the to '0' disables the option. The options are bit masks such that multiple options may be set or cleared. The options are described in xtmrctr.h. None. None.
References XTmrCtr::BaseAddress, XTmrCtr::IsReady, XTC_DEVICE_TIMER_COUNT, XTC_TCSR_OFFSET, XTmrCtr_WriteReg.
Referenced by TmrCtrCascadeIntrExample, TmrCtrFastIntrExample, TmrCtrIntrExample, TmrCtrPolledExample, TmrCtrPwmExample.
u32 XTmrCtr_GetOptions(XTmrCtr *InstancePtr, u8 TmrCtrNumber)
Get the options for the specified timer counter.
InstancePtr is a pointer to the XTmrCtr instance. TmrCtrNumber is the timer counter of the device to operate on Each device may contain multiple timer counters. The timer number is a zero based number with a range of 0 - (XTC_DEVICE_TIMER_COUNT - 1). The currently set options. An option which is set to a '1' is enabled and set to a '0' is disabled. The options are bit masks such that multiple options may be set or cleared. The options are described in xtmrctr.h.None.
References XTmrCtr::BaseAddress, XTmrCtr::IsReady, XTC_DEVICE_TIMER_COUNT, XTC_TCSR_OFFSET, XTmrCtr_ReadReg.
void XTmrCtr_GetStats(XTmrCtr *InstancePtr, XTmrCtrStats *StatsPtr)
Get a copy of the XTmrCtrStats structure, which contains the current statistics for this driver.
InstancePtr is a pointer to the XTmrCtr instance. StatsPtr is a pointer to a XTmrCtrStats structure which will get a copy of current statistics. None. None.
References XTmrCtrStats::Interrupts, XTmrCtr::IsReady, XTmrCtr::Stats.
void XTmrCtr_ClearStats(XTmrCtr *InstancePtr)
Clear the XTmrCtrStats structure for this driver.
InstancePtr is a pointer to the XTmrCtr instance. None. None.
References XTmrCtrStats::Interrupts, XTmrCtr::IsReady, XTmrCtr::Stats.
int XTmrCtr_SelfTest(XTmrCtr *InstancePtr, u8 TmrCtrNumber)
Runs a self-test on the driver/device.
This test verifies that the specified timer counter of the device can be enabled and increments. InstancePtr is a pointer to the XTmrCtr instance. TmrCtrNumber is the timer counter of the device to operate on. Each device may contain multiple timer counters. The timer number is a zero based number with a range of 0 - (XTC_DEVICE_TIMER_COUNT - 1). XST_SUCCESS if self-test was successful XST_FAILURE if the timer is not incrementing. This is a destructive test using the provided timer. The current settings of the timer are returned to the initialized values and all settings at the time this function is called are overwritten.
References XTmrCtr::BaseAddress, XTmrCtr::IsReady, XTC_CSR_ENABLE_TMR_MASK, XTC_CSR_INT_OCCURED_MASK, XTC_CSR_LOAD_MASK, XTC_DEVICE_TIMER_COUNT, XTC_TCR_OFFSET, XTC_TCSR_OFFSET, XTC_TLR_OFFSET, XTmrCtr_ReadReg, XTmrCtr_WriteReg.
Referenced by TmrCtrCascadeIntrExample, TmrCtrFastIntrExample, TmrCtrIntrExample, TmrCtrPolledExample, TmrCtrPwmExample, TmrCtrSelfTestExample.
void XTmrCtr_SetHandler(XTmrCtr *InstancePtr, XTmrCtr_Handler FuncPtr, void *CallBackRef)
Sets the timer callback function, which the driver calls when the specified timer times out.
InstancePtr is a pointer to the XTmrCtr instance . CallBackRef is the upper layer callback reference passed back when the callback function is invoked. FuncPtr is the pointer to the callback function. None. The handler is called within interrupt context so the function that is called should either be short or pass the more extensive processing off to another task to allow the interrupt to return and normal processing to continue.
References XTmrCtr::CallBackRef, XTmrCtr::Handler, XTmrCtr::IsReady.
Referenced by TmrCtrCascadeIntrExample, TmrCtrFastIntrExample, TmrCtrIntrExample, TmrCtrPwmExample.
void XTmrCtr_InterruptHandler(void *InstancePtr)
Interrupt Service Routine (ISR) for the driver.
This function only performs processing for the device and does not save and restore the interrupt context. InstancePtr contains a pointer to the timer/counter instance for the interrupt. None. None.
References XTmrCtr::BaseAddress, XTmrCtr::CallBackRef, XTmrCtr::Handler, XTmrCtrStats::Interrupts, XTmrCtr::Stats, XTC_CSR_AUTO_RELOAD_MASK, XTC_CSR_CAPTURE_MODE_MASK, XTC_CSR_ENABLE_INT_MASK, XTC_CSR_ENABLE_TMR_MASK, XTC_CSR_INT_OCCURED_MASK, XTC_CSR_LOAD_MASK, XTC_DEVICE_TIMER_COUNT, XTC_TCSR_OFFSET, XTmrCtr_ReadReg, XTmrCtr_WriteReg.
Referenced by TmrCtrCascadeIntrExample, TmrCtrIntrExample, TmrCtrPwmExample.