xtmrctr_intr.c
void XTmrCtr_SetHandler(XTmrCtr *InstancePtr, XTmrCtr_Handler FuncPtr, void *CallBackRef)
Sets the timer callback function, which the driver calls when the specified timer times out.
InstancePtr is a pointer to the XTmrCtr instance . CallBackRef is the upper layer callback reference passed back when the callback function is invoked. FuncPtr is the pointer to the callback function. None. The handler is called within interrupt context so the function that is called should either be short or pass the more extensive processing off to another task to allow the interrupt to return and normal processing to continue.
References XTmrCtr::CallBackRef, XTmrCtr::Handler, XTmrCtr::IsReady.
Referenced by TmrCtrCascadeIntrExample, TmrCtrFastIntrExample, TmrCtrIntrExample, TmrCtrPwmExample.
void XTmrCtr_InterruptHandler(void *InstancePtr)
Interrupt Service Routine (ISR) for the driver.
This function only performs processing for the device and does not save and restore the interrupt context. InstancePtr contains a pointer to the timer/counter instance for the interrupt. None. None.
References XTmrCtr::BaseAddress, XTmrCtr::CallBackRef, XTmrCtr::Handler, XTmrCtrStats::Interrupts, XTmrCtr::Stats, XTC_CSR_AUTO_RELOAD_MASK, XTC_CSR_CAPTURE_MODE_MASK, XTC_CSR_ENABLE_INT_MASK, XTC_CSR_ENABLE_TMR_MASK, XTC_CSR_INT_OCCURED_MASK, XTC_CSR_LOAD_MASK, XTC_DEVICE_TIMER_COUNT, XTC_TCSR_OFFSET, XTmrCtr_ReadReg, XTmrCtr_WriteReg.
Referenced by TmrCtrCascadeIntrExample, TmrCtrIntrExample, TmrCtrPwmExample.