/**
 * (c) 2013 Xilinx Inc.
 * XREGDB v0.91
 * XREGCHDR v0.15
 *
 * Generated on: 2018-06-19
 *
 * @file: cframe0_reg.h
 *
 *
 * This file contains confidential and proprietary information
 * of Xilinx, Inc. and is protected under U.S. and
 * international copyright and other intellectual property
 * laws.
 *
 * DISCLAIMER
 * This disclaimer is not a license and does not grant any
 * rights to the materials distributed herewith. Except as
 * otherwise provided in a valid license issued to you by
 * Xilinx, and to the maximum extent permitted by applicable
 * law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
 * WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
 * AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
 * BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
 * INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
 * (2) Xilinx shall not be liable (whether in contract or tort,
 * including negligence, or under any other theory of
 * liability) for any loss or damage of any kind or nature
 * related to, arising under or in connection with these
 * materials, including for any direct, or any indirect,
 * special, incidental, or consequential loss or damage
 * (including loss of data, profits, goodwill, or any type of
 * loss or damage suffered as a result of any action brought
 * by a third party) even if such damage or loss was
 * reasonably foreseeable or Xilinx had been advised of the
 * possibility of the same.
 *
 * CRITICAL APPLICATIONS
 * Xilinx products are not designed or intended to be fail-
 * safe, or for use in any application requiring fail-safe
 * performance, such as life-support or safety devices or
 * systems, Class III medical devices, nuclear facilities,
 * applications related to the deployment of airbags, or any
 * other applications that could lead to death, personal
 * injury, or severe property or environmental damage
 * (individually and collectively, "Critical
 * Applications"). Customer assumes the sole risk and
 * liability of any use of Xilinx products in Critical
 * Applications, subject only to applicable laws and
 * regulations governing limitations on product liability.
 *
 * THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
 * PART OF THIS FILE AT ALL TIMES.
 *
 * Naming Convention: <MODULE>_<REGISTER>[_<FIELD>[_<DESC>]]
 *     <MODULE>       Module name (e.g. can or usb)
 *     <REGISTER>     Register within the current module
 *     [_<FIELD>]     Bit field within a register
 *     [_<DESC>]      Type of bit field define:
 *         SHIFT:     Least significant bit for the field
 *         WIDTH:     Size of field in bites
 *         MASK:      A masking over a range of bits or a bit to
 *                    be used for setting or clearing
 *
 */

#ifndef _CFRAME0_REG_H_
#define _CFRAME0_REG_H_

#ifdef __cplusplus
extern "C" {
#endif

/**
 * CFRAME0_REG Base Address
 */
#define CFRAME0_REG_BASEADDR      0XF12D0000

/**
 * Register: CFRAME0_REG_CRC
 */
#define CFRAME0_REG_CRC    ( ( CFRAME0_REG_BASEADDR ) + 0X00000000 )

#define CFRAME0_REG_CRC_CRC_SHIFT   0
#define CFRAME0_REG_CRC_CRC_WIDTH   32
#define CFRAME0_REG_CRC_CRC_MASK    0XFFFFFFFF

/**
 * Register: CFRAME0_REG_FAR
 */
#define CFRAME0_REG_FAR    ( ( CFRAME0_REG_BASEADDR ) + 0X00000010 )

#define CFRAME0_REG_FAR_SEGMENT_SHIFT   23
#define CFRAME0_REG_FAR_SEGMENT_WIDTH   2
#define CFRAME0_REG_FAR_SEGMENT_MASK    0X01800000

#define CFRAME0_REG_FAR_BLOCKTYPE_SHIFT   20
#define CFRAME0_REG_FAR_BLOCKTYPE_WIDTH   3
#define CFRAME0_REG_FAR_BLOCKTYPE_MASK    0X00700000

#define CFRAME0_REG_FAR_FRAME_ADDR_SHIFT   0
#define CFRAME0_REG_FAR_FRAME_ADDR_WIDTH   20
#define CFRAME0_REG_FAR_FRAME_ADDR_MASK    0X000FFFFF

/**
 * Register: CFRAME0_REG_FAR_SFR
 */
#define CFRAME0_REG_FAR_SFR    ( ( CFRAME0_REG_BASEADDR ) + 0X00000020 )

#define CFRAME0_REG_FAR_SFR_BLOCKTYPE_SHIFT   20
#define CFRAME0_REG_FAR_SFR_BLOCKTYPE_WIDTH   3
#define CFRAME0_REG_FAR_SFR_BLOCKTYPE_MASK    0X00700000

#define CFRAME0_REG_FAR_SFR_FRAME_ADDR_SHIFT   0
#define CFRAME0_REG_FAR_SFR_FRAME_ADDR_WIDTH   20
#define CFRAME0_REG_FAR_SFR_FRAME_ADDR_MASK    0X000FFFFF

/**
 * Register: CFRAME0_REG_FAR_MFW
 */
#define CFRAME0_REG_FAR_MFW    ( ( CFRAME0_REG_BASEADDR ) + 0X00000030 )

#define CFRAME0_REG_FAR_MFW_SEGMENT_SHIFT   23
#define CFRAME0_REG_FAR_MFW_SEGMENT_WIDTH   2
#define CFRAME0_REG_FAR_MFW_SEGMENT_MASK    0X01800000

#define CFRAME0_REG_FAR_MFW_BLOCKTYPE_SHIFT   20
#define CFRAME0_REG_FAR_MFW_BLOCKTYPE_WIDTH   3
#define CFRAME0_REG_FAR_MFW_BLOCKTYPE_MASK    0X00700000

#define CFRAME0_REG_FAR_MFW_FRAME_ADDR_SHIFT   0
#define CFRAME0_REG_FAR_MFW_FRAME_ADDR_WIDTH   20
#define CFRAME0_REG_FAR_MFW_FRAME_ADDR_MASK    0X000FFFFF

/**
 * Register: CFRAME0_REG_FDRI
 */
#define CFRAME0_REG_FDRI    ( ( CFRAME0_REG_BASEADDR ) + 0X00000040 )

#define CFRAME0_REG_FDRI_FDRI_SHIFT   0
#define CFRAME0_REG_FDRI_FDRI_WIDTH   128
#define CFRAME0_REG_FDRI_FDRI_MASK    0XFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF

/**
 * Register: CFRAME0_REG_FRCNT
 */
#define CFRAME0_REG_FRCNT    ( ( CFRAME0_REG_BASEADDR ) + 0X00000050 )

#define CFRAME0_REG_FRCNT_FRCNT_SHIFT   0
#define CFRAME0_REG_FRCNT_FRCNT_WIDTH   32
#define CFRAME0_REG_FRCNT_FRCNT_MASK    0XFFFFFFFF

/**
 * Register: CFRAME0_REG_CMD
 */
#define CFRAME0_REG_CMD    ( ( CFRAME0_REG_BASEADDR ) + 0X00000060 )

#define CFRAME0_REG_CMD_CMD_SHIFT   0
#define CFRAME0_REG_CMD_CMD_WIDTH   5
#define CFRAME0_REG_CMD_CMD_MASK    0X0000001F

/**
 * Register: CFRAME0_REG_MASK
 */
#define CFRAME0_REG_MASK    ( ( CFRAME0_REG_BASEADDR ) + 0X00000070 )

#define CFRAME0_REG_MASK_MASK_SHIFT   0
#define CFRAME0_REG_MASK_MASK_WIDTH   96
#define CFRAME0_REG_MASK_MASK_MASK    0XFFFFFFFFFFFFFFFFFFFFFFFF

/**
 * Register: CFRAME0_REG_CTL
 */
#define CFRAME0_REG_CTL    ( ( CFRAME0_REG_BASEADDR ) + 0X00000080 )

#define CFRAME0_REG_CTL_DL_STAGGER_SHIFT   1
#define CFRAME0_REG_CTL_DL_STAGGER_WIDTH   1
#define CFRAME0_REG_CTL_DL_STAGGER_MASK    0X00000002

#define CFRAME0_REG_CTL_PER_FRAME_CRC_SHIFT   0
#define CFRAME0_REG_CTL_PER_FRAME_CRC_WIDTH   1
#define CFRAME0_REG_CTL_PER_FRAME_CRC_MASK    0X00000001

/**
 * Register: CFRAME0_REG_CRAM_WR
 */
#define CFRAME0_REG_CRAM_WR    ( ( CFRAME0_REG_BASEADDR ) + 0X00000090 )

#define CFRAME0_REG_CRAM_WR_WR_WAVE_CNT_DBG_SHIFT   86
#define CFRAME0_REG_CRAM_WR_WR_WAVE_CNT_DBG_WIDTH   6
#define CFRAME0_REG_CRAM_WR_WR_WAVE_CNT_DBG_MASK    0XFC000000000000000000000

#define CFRAME0_REG_CRAM_WR_ROW_DELAY_SHIFT   76
#define CFRAME0_REG_CRAM_WR_ROW_DELAY_WIDTH   10
#define CFRAME0_REG_CRAM_WR_ROW_DELAY_MASK    0X3FF0000000000000000000

#define CFRAME0_REG_CRAM_WR_WRCFG_DELAY_SHIFT   68
#define CFRAME0_REG_CRAM_WR_WRCFG_DELAY_WIDTH   8
#define CFRAME0_REG_CRAM_WR_WRCFG_DELAY_MASK    0XFF00000000000000000

#define CFRAME0_REG_CRAM_WR_MORE_PIPE_EN_SHIFT   67
#define CFRAME0_REG_CRAM_WR_MORE_PIPE_EN_WIDTH   1
#define CFRAME0_REG_CRAM_WR_MORE_PIPE_EN_MASK    0X80000000000000000

#define CFRAME0_REG_CRAM_WR_NEGEDGE_EN_SHIFT   66
#define CFRAME0_REG_CRAM_WR_NEGEDGE_EN_WIDTH   1
#define CFRAME0_REG_CRAM_WR_NEGEDGE_EN_MASK    0X40000000000000000

#define CFRAME0_REG_CRAM_WR_WR_WAVE_CNT_SHIFT   60
#define CFRAME0_REG_CRAM_WR_WR_WAVE_CNT_WIDTH   6
#define CFRAME0_REG_CRAM_WR_WR_WAVE_CNT_MASK    0X3F000000000000000

#define CFRAME0_REG_CRAM_WR_WR_MINICBRK_START_SHIFT   54
#define CFRAME0_REG_CRAM_WR_WR_MINICBRK_START_WIDTH   6
#define CFRAME0_REG_CRAM_WR_WR_MINICBRK_START_MASK    0XFC0000000000000

#define CFRAME0_REG_CRAM_WR_WR_MINICBRK_END_SHIFT   48
#define CFRAME0_REG_CRAM_WR_WR_MINICBRK_END_WIDTH   6
#define CFRAME0_REG_CRAM_WR_WR_MINICBRK_END_MASK    0X3F000000000000

#define CFRAME0_REG_CRAM_WR_WR_ENFADD_START_SHIFT   42
#define CFRAME0_REG_CRAM_WR_WR_ENFADD_START_WIDTH   6
#define CFRAME0_REG_CRAM_WR_WR_ENFADD_START_MASK    0XFC0000000000

#define CFRAME0_REG_CRAM_WR_WR_ENFADD_END_SHIFT   36
#define CFRAME0_REG_CRAM_WR_WR_ENFADD_END_WIDTH   6
#define CFRAME0_REG_CRAM_WR_WR_ENFADD_END_MASK    0X3F000000000

#define CFRAME0_REG_CRAM_WR_WR_RAMENFADD_START_SHIFT   30
#define CFRAME0_REG_CRAM_WR_WR_RAMENFADD_START_WIDTH   6
#define CFRAME0_REG_CRAM_WR_WR_RAMENFADD_START_MASK    0XFC0000000

#define CFRAME0_REG_CRAM_WR_WR_RAMENFADD_END_SHIFT   24
#define CFRAME0_REG_CRAM_WR_WR_RAMENFADD_END_WIDTH   6
#define CFRAME0_REG_CRAM_WR_WR_RAMENFADD_END_MASK    0X3F000000

#define CFRAME0_REG_CRAM_WR_WR_CHARGE_END_SHIFT   18
#define CFRAME0_REG_CRAM_WR_WR_CHARGE_END_WIDTH   6
#define CFRAME0_REG_CRAM_WR_WR_CHARGE_END_MASK    0X00FC0000

#define CFRAME0_REG_CRAM_WR_WR_CHARGE_START_SHIFT   12
#define CFRAME0_REG_CRAM_WR_WR_CHARGE_START_WIDTH   6
#define CFRAME0_REG_CRAM_WR_WR_CHARGE_START_MASK    0X0003F000

#define CFRAME0_REG_CRAM_WR_WR_FORCE_EN_PUG_START_SHIFT   6
#define CFRAME0_REG_CRAM_WR_WR_FORCE_EN_PUG_START_WIDTH   6
#define CFRAME0_REG_CRAM_WR_WR_FORCE_EN_PUG_START_MASK    0X00000FC0

#define CFRAME0_REG_CRAM_WR_WR_FORCE_EN_PUG_END_SHIFT   0
#define CFRAME0_REG_CRAM_WR_WR_FORCE_EN_PUG_END_WIDTH   6
#define CFRAME0_REG_CRAM_WR_WR_FORCE_EN_PUG_END_MASK    0X0000003F

/**
 * Register: CFRAME0_REG_CRAM_RD
 */
#define CFRAME0_REG_CRAM_RD    ( ( CFRAME0_REG_BASEADDR ) + 0X000000A0 )

#define CFRAME0_REG_CRAM_RD_RD_WAVE_CNT_DBG_SHIFT   51
#define CFRAME0_REG_CRAM_RD_RD_WAVE_CNT_DBG_WIDTH   6
#define CFRAME0_REG_CRAM_RD_RD_WAVE_CNT_DBG_MASK    0X1F8000000000000

#define CFRAME0_REG_CRAM_RD_RD_DATAVALID_SHIFT   48
#define CFRAME0_REG_CRAM_RD_RD_DATAVALID_WIDTH   3
#define CFRAME0_REG_CRAM_RD_RD_DATAVALID_MASK    0X7000000000000

#define CFRAME0_REG_CRAM_RD_RD_WAVE_CNT_RIGHT_SHIFT   42
#define CFRAME0_REG_CRAM_RD_RD_WAVE_CNT_RIGHT_WIDTH   6
#define CFRAME0_REG_CRAM_RD_RD_WAVE_CNT_RIGHT_MASK    0XFC0000000000

#define CFRAME0_REG_CRAM_RD_RD_WAVE_CNT_LEFT_SHIFT   36
#define CFRAME0_REG_CRAM_RD_RD_WAVE_CNT_LEFT_WIDTH   6
#define CFRAME0_REG_CRAM_RD_RD_WAVE_CNT_LEFT_MASK    0X3F000000000

#define CFRAME0_REG_CRAM_RD_RD_CHARGE_START_SHIFT   30
#define CFRAME0_REG_CRAM_RD_RD_CHARGE_START_WIDTH   6
#define CFRAME0_REG_CRAM_RD_RD_CHARGE_START_MASK    0XFC0000000

#define CFRAME0_REG_CRAM_RD_RD_KEEPER_START_SHIFT   24
#define CFRAME0_REG_CRAM_RD_RD_KEEPER_START_WIDTH   6
#define CFRAME0_REG_CRAM_RD_RD_KEEPER_START_MASK    0X3F000000

#define CFRAME0_REG_CRAM_RD_RD_ENFADD_START_SHIFT   18
#define CFRAME0_REG_CRAM_RD_RD_ENFADD_START_WIDTH   6
#define CFRAME0_REG_CRAM_RD_RD_ENFADD_START_MASK    0X00FC0000

#define CFRAME0_REG_CRAM_RD_RD_ENFADD_END_SHIFT   12
#define CFRAME0_REG_CRAM_RD_RD_ENFADD_END_WIDTH   6
#define CFRAME0_REG_CRAM_RD_RD_ENFADD_END_MASK    0X0003F000

#define CFRAME0_REG_CRAM_RD_RD_RAMENFADD_START_SHIFT   6
#define CFRAME0_REG_CRAM_RD_RD_RAMENFADD_START_WIDTH   6
#define CFRAME0_REG_CRAM_RD_RD_RAMENFADD_START_MASK    0X00000FC0

#define CFRAME0_REG_CRAM_RD_RD_RAMENFADD_END_SHIFT   0
#define CFRAME0_REG_CRAM_RD_RD_RAMENFADD_END_WIDTH   6
#define CFRAME0_REG_CRAM_RD_RD_RAMENFADD_END_MASK    0X0000003F

/**
 * Register: CFRAME0_REG_CRAM_TRIM
 */
#define CFRAME0_REG_CRAM_TRIM    ( ( CFRAME0_REG_BASEADDR ) + 0X000000B0 )

#define CFRAME0_REG_CRAM_TRIM_SPARE_SHIFT   30
#define CFRAME0_REG_CRAM_TRIM_SPARE_WIDTH   2
#define CFRAME0_REG_CRAM_TRIM_SPARE_MASK    0XC0000000

#define CFRAME0_REG_CRAM_TRIM_DIS_MINICBRK_SHIFT   29
#define CFRAME0_REG_CRAM_TRIM_DIS_MINICBRK_WIDTH   1
#define CFRAME0_REG_CRAM_TRIM_DIS_MINICBRK_MASK    0X20000000

#define CFRAME0_REG_CRAM_TRIM_MCS_SEL_SHIFT   25
#define CFRAME0_REG_CRAM_TRIM_MCS_SEL_WIDTH   4
#define CFRAME0_REG_CRAM_TRIM_MCS_SEL_MASK    0X1E000000

#define CFRAME0_REG_CRAM_TRIM_TM_W2R_LD_SHIFT   24
#define CFRAME0_REG_CRAM_TRIM_TM_W2R_LD_WIDTH   1
#define CFRAME0_REG_CRAM_TRIM_TM_W2R_LD_MASK    0X01000000

#define CFRAME0_REG_CRAM_TRIM_READ_RANGE_SEL_SHIFT   23
#define CFRAME0_REG_CRAM_TRIM_READ_RANGE_SEL_WIDTH   1
#define CFRAME0_REG_CRAM_TRIM_READ_RANGE_SEL_MASK    0X00800000

#define CFRAME0_REG_CRAM_TRIM_RW_WRITE_VOLTAGE_WR_SHIFT   18
#define CFRAME0_REG_CRAM_TRIM_RW_WRITE_VOLTAGE_WR_WIDTH   5
#define CFRAME0_REG_CRAM_TRIM_RW_WRITE_VOLTAGE_WR_MASK    0X007C0000

#define CFRAME0_REG_CRAM_TRIM_RW_READ_VOLTAGE_KPR_SHIFT   14
#define CFRAME0_REG_CRAM_TRIM_RW_READ_VOLTAGE_KPR_WIDTH   4
#define CFRAME0_REG_CRAM_TRIM_RW_READ_VOLTAGE_KPR_MASK    0X0003C000

#define CFRAME0_REG_CRAM_TRIM_RW_READ_VOLTAGE_RD_SHIFT   0
#define CFRAME0_REG_CRAM_TRIM_RW_READ_VOLTAGE_RD_WIDTH   14
#define CFRAME0_REG_CRAM_TRIM_RW_READ_VOLTAGE_RD_MASK    0X00003FFF

/**
 * Register: CFRAME0_REG_COE_TRIM
 */
#define CFRAME0_REG_COE_TRIM    ( ( CFRAME0_REG_BASEADDR ) + 0X000000C0 )

#define CFRAME0_REG_COE_TRIM_COE_TRIM_SHIFT   0
#define CFRAME0_REG_COE_TRIM_COE_TRIM_WIDTH   64
#define CFRAME0_REG_COE_TRIM_COE_TRIM_MASK    0XFFFFFFFFFFFFFFFF

/**
 * Register: CFRAME0_REG_SVDOPT
 */
#define CFRAME0_REG_SVDOPT    ( ( CFRAME0_REG_BASEADDR ) + 0X000000D0 )

#define CFRAME0_REG_SVDOPT_SVD_BOT_SEG_DIS_SHIFT   92
#define CFRAME0_REG_SVDOPT_SVD_BOT_SEG_DIS_WIDTH   1
#define CFRAME0_REG_SVDOPT_SVD_BOT_SEG_DIS_MASK    0X100000000000000000000000

#define CFRAME0_REG_SVDOPT_SVD_TOP_SEG_DIS_SHIFT   91
#define CFRAME0_REG_SVDOPT_SVD_TOP_SEG_DIS_WIDTH   1
#define CFRAME0_REG_SVDOPT_SVD_TOP_SEG_DIS_MASK    0X80000000000000000000000

#define CFRAME0_REG_SVDOPT_SVD_BLK6_END_SHIFT   81
#define CFRAME0_REG_SVDOPT_SVD_BLK6_END_WIDTH   10
#define CFRAME0_REG_SVDOPT_SVD_BLK6_END_MASK    0X7FE00000000000000000000

#define CFRAME0_REG_SVDOPT_SVD_BLK6_START_SHIFT   71
#define CFRAME0_REG_SVDOPT_SVD_BLK6_START_WIDTH   10
#define CFRAME0_REG_SVDOPT_SVD_BLK6_START_MASK    0X1FF800000000000000000

#define CFRAME0_REG_SVDOPT_SVD_BLK5_END_SHIFT   69
#define CFRAME0_REG_SVDOPT_SVD_BLK5_END_WIDTH   2
#define CFRAME0_REG_SVDOPT_SVD_BLK5_END_MASK    0X600000000000000000

#define CFRAME0_REG_SVDOPT_SVD_BLK5_START_SHIFT   67
#define CFRAME0_REG_SVDOPT_SVD_BLK5_START_WIDTH   2
#define CFRAME0_REG_SVDOPT_SVD_BLK5_START_MASK    0X180000000000000000

#define CFRAME0_REG_SVDOPT_SVD_BLK4_END_SHIFT   61
#define CFRAME0_REG_SVDOPT_SVD_BLK4_END_WIDTH   6
#define CFRAME0_REG_SVDOPT_SVD_BLK4_END_MASK    0X7E000000000000000

#define CFRAME0_REG_SVDOPT_SVD_BLK4_START_SHIFT   55
#define CFRAME0_REG_SVDOPT_SVD_BLK4_START_WIDTH   6
#define CFRAME0_REG_SVDOPT_SVD_BLK4_START_MASK    0X1F80000000000000

#define CFRAME0_REG_SVDOPT_SVD_BLK3_END_SHIFT   48
#define CFRAME0_REG_SVDOPT_SVD_BLK3_END_WIDTH   7
#define CFRAME0_REG_SVDOPT_SVD_BLK3_END_MASK    0X7F000000000000

#define CFRAME0_REG_SVDOPT_SVD_BLK3_START_SHIFT   41
#define CFRAME0_REG_SVDOPT_SVD_BLK3_START_WIDTH   7
#define CFRAME0_REG_SVDOPT_SVD_BLK3_START_MASK    0XFE0000000000

#define CFRAME0_REG_SVDOPT_SVD_BLK0_END_SHIFT   21
#define CFRAME0_REG_SVDOPT_SVD_BLK0_END_WIDTH   20
#define CFRAME0_REG_SVDOPT_SVD_BLK0_END_MASK    0X1FFFFE00000

#define CFRAME0_REG_SVDOPT_SVD_BLK0_START_SHIFT   1
#define CFRAME0_REG_SVDOPT_SVD_BLK0_START_WIDTH   20
#define CFRAME0_REG_SVDOPT_SVD_BLK0_START_MASK    0X001FFFFE

#define CFRAME0_REG_SVDOPT_SVD_ENABLE_SHIFT   0
#define CFRAME0_REG_SVDOPT_SVD_ENABLE_WIDTH   1
#define CFRAME0_REG_SVDOPT_SVD_ENABLE_MASK    0X00000001

/**
 * Register: CFRAME0_REG_SEUOPT
 */
#define CFRAME0_REG_SEUOPT    ( ( CFRAME0_REG_BASEADDR ) + 0X000000E0 )

#define CFRAME0_REG_SEUOPT_HB_CNT_SHIFT   8
#define CFRAME0_REG_SEUOPT_HB_CNT_WIDTH   32
#define CFRAME0_REG_SEUOPT_HB_CNT_MASK    0XFFFFFFFF00

#define CFRAME0_REG_SEUOPT_NOCRCC_SHIFT   4
#define CFRAME0_REG_SEUOPT_NOCRCC_WIDTH   1
#define CFRAME0_REG_SEUOPT_NOCRCC_MASK    0X00000010

#define CFRAME0_REG_SEUOPT_RBCRC_ONEROW_SHIFT   3
#define CFRAME0_REG_SEUOPT_RBCRC_ONEROW_WIDTH   1
#define CFRAME0_REG_SEUOPT_RBCRC_ONEROW_MASK    0X00000008

#define CFRAME0_REG_SEUOPT_SWECC_SEL_SHIFT   2
#define CFRAME0_REG_SEUOPT_SWECC_SEL_WIDTH   1
#define CFRAME0_REG_SEUOPT_SWECC_SEL_MASK    0X00000004

#define CFRAME0_REG_SEUOPT_SWCRC_SEL_SHIFT   1
#define CFRAME0_REG_SEUOPT_SWCRC_SEL_WIDTH   1
#define CFRAME0_REG_SEUOPT_SWCRC_SEL_MASK    0X00000002

#define CFRAME0_REG_SEUOPT_RBCRC_EN_SHIFT   0
#define CFRAME0_REG_SEUOPT_RBCRC_EN_WIDTH   1
#define CFRAME0_REG_SEUOPT_RBCRC_EN_MASK    0X00000001

/**
 * Register: CFRAME0_REG_SEU_SEL_SCAN
 */
#define CFRAME0_REG_SEU_SEL_SCAN    ( ( CFRAME0_REG_BASEADDR ) + 0X000000F0 )

#define CFRAME0_REG_SEU_SEL_SCAN_SEU_BLK6_END_SHIFT   81
#define CFRAME0_REG_SEU_SEL_SCAN_SEU_BLK6_END_WIDTH   10
#define CFRAME0_REG_SEU_SEL_SCAN_SEU_BLK6_END_MASK    0X7FE00000000000000000000

#define CFRAME0_REG_SEU_SEL_SCAN_SEU_BLK6_START_SHIFT   71
#define CFRAME0_REG_SEU_SEL_SCAN_SEU_BLK6_START_WIDTH   10
#define CFRAME0_REG_SEU_SEL_SCAN_SEU_BLK6_START_MASK    0X1FF800000000000000000

#define CFRAME0_REG_SEU_SEL_SCAN_SEU_BLK5_END_SHIFT   69
#define CFRAME0_REG_SEU_SEL_SCAN_SEU_BLK5_END_WIDTH   2
#define CFRAME0_REG_SEU_SEL_SCAN_SEU_BLK5_END_MASK    0X600000000000000000

#define CFRAME0_REG_SEU_SEL_SCAN_SEU_BLK5_START_SHIFT   67
#define CFRAME0_REG_SEU_SEL_SCAN_SEU_BLK5_START_WIDTH   2
#define CFRAME0_REG_SEU_SEL_SCAN_SEU_BLK5_START_MASK    0X180000000000000000

#define CFRAME0_REG_SEU_SEL_SCAN_SEU_BLK4_END_SHIFT   61
#define CFRAME0_REG_SEU_SEL_SCAN_SEU_BLK4_END_WIDTH   6
#define CFRAME0_REG_SEU_SEL_SCAN_SEU_BLK4_END_MASK    0X7E000000000000000

#define CFRAME0_REG_SEU_SEL_SCAN_SEU_BLK4_START_SHIFT   55
#define CFRAME0_REG_SEU_SEL_SCAN_SEU_BLK4_START_WIDTH   6
#define CFRAME0_REG_SEU_SEL_SCAN_SEU_BLK4_START_MASK    0X1F80000000000000

#define CFRAME0_REG_SEU_SEL_SCAN_SEU_BLK3_END_SHIFT   48
#define CFRAME0_REG_SEU_SEL_SCAN_SEU_BLK3_END_WIDTH   7
#define CFRAME0_REG_SEU_SEL_SCAN_SEU_BLK3_END_MASK    0X7F000000000000

#define CFRAME0_REG_SEU_SEL_SCAN_SEU_BLK3_START_SHIFT   41
#define CFRAME0_REG_SEU_SEL_SCAN_SEU_BLK3_START_WIDTH   7
#define CFRAME0_REG_SEU_SEL_SCAN_SEU_BLK3_START_MASK    0XFE0000000000

#define CFRAME0_REG_SEU_SEL_SCAN_SEU_BLK0_END_SHIFT   21
#define CFRAME0_REG_SEU_SEL_SCAN_SEU_BLK0_END_WIDTH   20
#define CFRAME0_REG_SEU_SEL_SCAN_SEU_BLK0_END_MASK    0X1FFFFE00000

#define CFRAME0_REG_SEU_SEL_SCAN_SEU_BLK0_START_SHIFT   1
#define CFRAME0_REG_SEU_SEL_SCAN_SEU_BLK0_START_WIDTH   20
#define CFRAME0_REG_SEU_SEL_SCAN_SEU_BLK0_START_MASK    0X001FFFFE

#define CFRAME0_REG_SEU_SEL_SCAN_SEU_SEL_SCAN_SEL_SHIFT   0
#define CFRAME0_REG_SEU_SEL_SCAN_SEU_SEL_SCAN_SEL_WIDTH   1
#define CFRAME0_REG_SEU_SEL_SCAN_SEU_SEL_SCAN_SEL_MASK    0X00000001

/**
 * Register: CFRAME0_REG_SEU_START_CNT
 */
#define CFRAME0_REG_SEU_START_CNT    ( ( CFRAME0_REG_BASEADDR ) + 0X00000100 )

#define CFRAME0_REG_SEU_START_CNT_SEU_START_CNT_SHIFT   0
#define CFRAME0_REG_SEU_START_CNT_SEU_START_CNT_WIDTH   32
#define CFRAME0_REG_SEU_START_CNT_SEU_START_CNT_MASK    0XFFFFFFFF

/**
 * Register: CFRAME0_REG_SEU_SWCRC
 */
#define CFRAME0_REG_SEU_SWCRC    ( ( CFRAME0_REG_BASEADDR ) + 0X00000110 )

#define CFRAME0_REG_SEU_SWCRC_SEU_SWCRC_SS_SHIFT   32
#define CFRAME0_REG_SEU_SWCRC_SEU_SWCRC_SS_WIDTH   32
#define CFRAME0_REG_SEU_SWCRC_SEU_SWCRC_SS_MASK    0XFFFFFFFF00000000

#define CFRAME0_REG_SEU_SWCRC_SEU_SWCRC_SHIFT   0
#define CFRAME0_REG_SEU_SWCRC_SEU_SWCRC_WIDTH   32
#define CFRAME0_REG_SEU_SWCRC_SEU_SWCRC_MASK    0XFFFFFFFF

/**
 * Register: CFRAME0_REG_TESTMODE
 */
#define CFRAME0_REG_TESTMODE    ( ( CFRAME0_REG_BASEADDR ) + 0X00000120 )

#define CFRAME0_REG_TESTMODE_WR_MINICBRK_TMCAP_SHIFT   23
#define CFRAME0_REG_TESTMODE_WR_MINICBRK_TMCAP_WIDTH   6
#define CFRAME0_REG_TESTMODE_WR_MINICBRK_TMCAP_MASK    0X1F800000

#define CFRAME0_REG_TESTMODE_TM_MINICBRK_DBG_SHIFT   22
#define CFRAME0_REG_TESTMODE_TM_MINICBRK_DBG_WIDTH   1
#define CFRAME0_REG_TESTMODE_TM_MINICBRK_DBG_MASK    0X00400000

#define CFRAME0_REG_TESTMODE_TM_MININCBRK_SHIFT   19
#define CFRAME0_REG_TESTMODE_TM_MININCBRK_WIDTH   3
#define CFRAME0_REG_TESTMODE_TM_MININCBRK_MASK    0X00380000

#define CFRAME0_REG_TESTMODE_EN_SPLYREFS_VF_PROBE_SHIFT   18
#define CFRAME0_REG_TESTMODE_EN_SPLYREFS_VF_PROBE_WIDTH   1
#define CFRAME0_REG_TESTMODE_EN_SPLYREFS_VF_PROBE_MASK    0X00040000

#define CFRAME0_REG_TESTMODE_SPARE_SLOW_SHIFT   17
#define CFRAME0_REG_TESTMODE_SPARE_SLOW_WIDTH   1
#define CFRAME0_REG_TESTMODE_SPARE_SLOW_MASK    0X00020000

#define CFRAME0_REG_TESTMODE_CRAM_SELF_CHECK_RPT_SHIFT   13
#define CFRAME0_REG_TESTMODE_CRAM_SELF_CHECK_RPT_WIDTH   4
#define CFRAME0_REG_TESTMODE_CRAM_SELF_CHECK_RPT_MASK    0X0001E000

#define CFRAME0_REG_TESTMODE_CRAM_SELF_CHECK_FRM_SHIFT   9
#define CFRAME0_REG_TESTMODE_CRAM_SELF_CHECK_FRM_WIDTH   4
#define CFRAME0_REG_TESTMODE_CRAM_SELF_CHECK_FRM_MASK    0X00001E00

#define CFRAME0_REG_TESTMODE_CRAM_SELF_CHECK_SHIFT   8
#define CFRAME0_REG_TESTMODE_CRAM_SELF_CHECK_WIDTH   1
#define CFRAME0_REG_TESTMODE_CRAM_SELF_CHECK_MASK    0X00000100

#define CFRAME0_REG_TESTMODE_REGISTER_TEST_SHIFT   7
#define CFRAME0_REG_TESTMODE_REGISTER_TEST_WIDTH   1
#define CFRAME0_REG_TESTMODE_REGISTER_TEST_MASK    0X00000080

#define CFRAME0_REG_TESTMODE_BRAM_SHADOW_MEM_TEST_SHIFT   6
#define CFRAME0_REG_TESTMODE_BRAM_SHADOW_MEM_TEST_WIDTH   1
#define CFRAME0_REG_TESTMODE_BRAM_SHADOW_MEM_TEST_MASK    0X00000040

#define CFRAME0_REG_TESTMODE_FDR_SHIFTREG_READ_SHIFT   5
#define CFRAME0_REG_TESTMODE_FDR_SHIFTREG_READ_WIDTH   1
#define CFRAME0_REG_TESTMODE_FDR_SHIFTREG_READ_MASK    0X00000020

#define CFRAME0_REG_TESTMODE_A_12T_EN_B_SHIFT   3
#define CFRAME0_REG_TESTMODE_A_12T_EN_B_WIDTH   2
#define CFRAME0_REG_TESTMODE_A_12T_EN_B_MASK    0X00000018

#define CFRAME0_REG_TESTMODE_ADRV_SPLY_ENABLE_SHIFT   2
#define CFRAME0_REG_TESTMODE_ADRV_SPLY_ENABLE_WIDTH   1
#define CFRAME0_REG_TESTMODE_ADRV_SPLY_ENABLE_MASK    0X00000004

#define CFRAME0_REG_TESTMODE_ADRV_SPLY_DISABLE_SHIFT   1
#define CFRAME0_REG_TESTMODE_ADRV_SPLY_DISABLE_WIDTH   1
#define CFRAME0_REG_TESTMODE_ADRV_SPLY_DISABLE_MASK    0X00000002

#define CFRAME0_REG_TESTMODE_FIX_EN_THOX_PU_HI_SHIFT   0
#define CFRAME0_REG_TESTMODE_FIX_EN_THOX_PU_HI_WIDTH   1
#define CFRAME0_REG_TESTMODE_FIX_EN_THOX_PU_HI_MASK    0X00000001

/**
 * Register: CFRAME0_REG_BRDOPT
 */
#define CFRAME0_REG_BRDOPT    ( ( CFRAME0_REG_BASEADDR ) + 0X00000130 )

#define CFRAME0_REG_BRDOPT_BROADCAST_OFFSET_BLK6_SHIFT   36
#define CFRAME0_REG_BRDOPT_BROADCAST_OFFSET_BLK6_WIDTH   10
#define CFRAME0_REG_BRDOPT_BROADCAST_OFFSET_BLK6_MASK    0X3FF000000000

#define CFRAME0_REG_BRDOPT_BROADCAST_OFFSET_BLK5_SHIFT   34
#define CFRAME0_REG_BRDOPT_BROADCAST_OFFSET_BLK5_WIDTH   2
#define CFRAME0_REG_BRDOPT_BROADCAST_OFFSET_BLK5_MASK    0XC00000000

#define CFRAME0_REG_BRDOPT_BROADCAST_OFFSET_BLK4_SHIFT   28
#define CFRAME0_REG_BRDOPT_BROADCAST_OFFSET_BLK4_WIDTH   6
#define CFRAME0_REG_BRDOPT_BROADCAST_OFFSET_BLK4_MASK    0X3F0000000

#define CFRAME0_REG_BRDOPT_BROADCAST_OFFSET_BLK3_SHIFT   21
#define CFRAME0_REG_BRDOPT_BROADCAST_OFFSET_BLK3_WIDTH   7
#define CFRAME0_REG_BRDOPT_BROADCAST_OFFSET_BLK3_MASK    0X0FE00000

#define CFRAME0_REG_BRDOPT_BROADCAST_OFFSET_BLK0_SHIFT   1
#define CFRAME0_REG_BRDOPT_BROADCAST_OFFSET_BLK0_WIDTH   20
#define CFRAME0_REG_BRDOPT_BROADCAST_OFFSET_BLK0_MASK    0X001FFFFE

#define CFRAME0_REG_BRDOPT_BROADCAST_OFFSET_EN_SHIFT   0
#define CFRAME0_REG_BRDOPT_BROADCAST_OFFSET_EN_WIDTH   1
#define CFRAME0_REG_BRDOPT_BROADCAST_OFFSET_EN_MASK    0X00000001

/**
 * Register: CFRAME0_REG_VGG_TRIM
 */
#define CFRAME0_REG_VGG_TRIM    ( ( CFRAME0_REG_BASEADDR ) + 0X00000140 )

#define CFRAME0_REG_VGG_TRIM_SPARE_SHIFT   94
#define CFRAME0_REG_VGG_TRIM_SPARE_WIDTH   2
#define CFRAME0_REG_VGG_TRIM_SPARE_MASK    0XC00000000000000000000000

#define CFRAME0_REG_VGG_TRIM_RCLK_VGG_LE_SHIFT   88
#define CFRAME0_REG_VGG_TRIM_RCLK_VGG_LE_WIDTH   6
#define CFRAME0_REG_VGG_TRIM_RCLK_VGG_LE_MASK    0X3F0000000000000000000000

#define CFRAME0_REG_VGG_TRIM_VGG_L_TRIM_ROW10_SHIFT   84
#define CFRAME0_REG_VGG_TRIM_VGG_L_TRIM_ROW10_WIDTH   4
#define CFRAME0_REG_VGG_TRIM_VGG_L_TRIM_ROW10_MASK    0XF000000000000000000000

#define CFRAME0_REG_VGG_TRIM_VGG_L_TRIM_ROW9_SHIFT   80
#define CFRAME0_REG_VGG_TRIM_VGG_L_TRIM_ROW9_WIDTH   4
#define CFRAME0_REG_VGG_TRIM_VGG_L_TRIM_ROW9_MASK    0XF00000000000000000000

#define CFRAME0_REG_VGG_TRIM_VGG_L_TRIM_ROW8_SHIFT   76
#define CFRAME0_REG_VGG_TRIM_VGG_L_TRIM_ROW8_WIDTH   4
#define CFRAME0_REG_VGG_TRIM_VGG_L_TRIM_ROW8_MASK    0XF0000000000000000000

#define CFRAME0_REG_VGG_TRIM_VGG_L_TRIM_ROW7_SHIFT   72
#define CFRAME0_REG_VGG_TRIM_VGG_L_TRIM_ROW7_WIDTH   4
#define CFRAME0_REG_VGG_TRIM_VGG_L_TRIM_ROW7_MASK    0XF000000000000000000

#define CFRAME0_REG_VGG_TRIM_VGG_L_TRIM_ROW6_SHIFT   68
#define CFRAME0_REG_VGG_TRIM_VGG_L_TRIM_ROW6_WIDTH   4
#define CFRAME0_REG_VGG_TRIM_VGG_L_TRIM_ROW6_MASK    0XF00000000000000000

#define CFRAME0_REG_VGG_TRIM_VGG_L_TRIM_ROW5_SHIFT   64
#define CFRAME0_REG_VGG_TRIM_VGG_L_TRIM_ROW5_WIDTH   4
#define CFRAME0_REG_VGG_TRIM_VGG_L_TRIM_ROW5_MASK    0XF0000000000000000

#define CFRAME0_REG_VGG_TRIM_VGG_L_TRIM_ROW4_SHIFT   60
#define CFRAME0_REG_VGG_TRIM_VGG_L_TRIM_ROW4_WIDTH   4
#define CFRAME0_REG_VGG_TRIM_VGG_L_TRIM_ROW4_MASK    0XF000000000000000

#define CFRAME0_REG_VGG_TRIM_VGG_L_TRIM_ROW3_SHIFT   56
#define CFRAME0_REG_VGG_TRIM_VGG_L_TRIM_ROW3_WIDTH   4
#define CFRAME0_REG_VGG_TRIM_VGG_L_TRIM_ROW3_MASK    0XF00000000000000

#define CFRAME0_REG_VGG_TRIM_VGG_L_TRIM_ROW2_SHIFT   52
#define CFRAME0_REG_VGG_TRIM_VGG_L_TRIM_ROW2_WIDTH   4
#define CFRAME0_REG_VGG_TRIM_VGG_L_TRIM_ROW2_MASK    0XF0000000000000

#define CFRAME0_REG_VGG_TRIM_VGG_L_TRIM_ROW1_SHIFT   48
#define CFRAME0_REG_VGG_TRIM_VGG_L_TRIM_ROW1_WIDTH   4
#define CFRAME0_REG_VGG_TRIM_VGG_L_TRIM_ROW1_MASK    0XF000000000000

#define CFRAME0_REG_VGG_TRIM_VGG_L_TRIM_ROW0_SHIFT   44
#define CFRAME0_REG_VGG_TRIM_VGG_L_TRIM_ROW0_WIDTH   4
#define CFRAME0_REG_VGG_TRIM_VGG_L_TRIM_ROW0_MASK    0XF00000000000

#define CFRAME0_REG_VGG_TRIM_VGG_R_TRIM_ROW10_SHIFT   40
#define CFRAME0_REG_VGG_TRIM_VGG_R_TRIM_ROW10_WIDTH   4
#define CFRAME0_REG_VGG_TRIM_VGG_R_TRIM_ROW10_MASK    0XF0000000000

#define CFRAME0_REG_VGG_TRIM_VGG_R_TRIM_ROW9_SHIFT   36
#define CFRAME0_REG_VGG_TRIM_VGG_R_TRIM_ROW9_WIDTH   4
#define CFRAME0_REG_VGG_TRIM_VGG_R_TRIM_ROW9_MASK    0XF000000000

#define CFRAME0_REG_VGG_TRIM_VGG_R_TRIM_ROW8_SHIFT   32
#define CFRAME0_REG_VGG_TRIM_VGG_R_TRIM_ROW8_WIDTH   4
#define CFRAME0_REG_VGG_TRIM_VGG_R_TRIM_ROW8_MASK    0XF00000000

#define CFRAME0_REG_VGG_TRIM_VGG_R_TRIM_ROW7_SHIFT   28
#define CFRAME0_REG_VGG_TRIM_VGG_R_TRIM_ROW7_WIDTH   4
#define CFRAME0_REG_VGG_TRIM_VGG_R_TRIM_ROW7_MASK    0XF0000000

#define CFRAME0_REG_VGG_TRIM_VGG_R_TRIM_ROW6_SHIFT   24
#define CFRAME0_REG_VGG_TRIM_VGG_R_TRIM_ROW6_WIDTH   4
#define CFRAME0_REG_VGG_TRIM_VGG_R_TRIM_ROW6_MASK    0X0F000000

#define CFRAME0_REG_VGG_TRIM_VGG_R_TRIM_ROW5_SHIFT   20
#define CFRAME0_REG_VGG_TRIM_VGG_R_TRIM_ROW5_WIDTH   4
#define CFRAME0_REG_VGG_TRIM_VGG_R_TRIM_ROW5_MASK    0X00F00000

#define CFRAME0_REG_VGG_TRIM_VGG_R_TRIM_ROW4_SHIFT   16
#define CFRAME0_REG_VGG_TRIM_VGG_R_TRIM_ROW4_WIDTH   4
#define CFRAME0_REG_VGG_TRIM_VGG_R_TRIM_ROW4_MASK    0X000F0000

#define CFRAME0_REG_VGG_TRIM_VGG_R_TRIM_ROW3_SHIFT   12
#define CFRAME0_REG_VGG_TRIM_VGG_R_TRIM_ROW3_WIDTH   4
#define CFRAME0_REG_VGG_TRIM_VGG_R_TRIM_ROW3_MASK    0X0000F000

#define CFRAME0_REG_VGG_TRIM_VGG_R_TRIM_ROW2_SHIFT   8
#define CFRAME0_REG_VGG_TRIM_VGG_R_TRIM_ROW2_WIDTH   4
#define CFRAME0_REG_VGG_TRIM_VGG_R_TRIM_ROW2_MASK    0X00000F00

#define CFRAME0_REG_VGG_TRIM_VGG_R_TRIM_ROW1_SHIFT   4
#define CFRAME0_REG_VGG_TRIM_VGG_R_TRIM_ROW1_WIDTH   4
#define CFRAME0_REG_VGG_TRIM_VGG_R_TRIM_ROW1_MASK    0X000000F0

#define CFRAME0_REG_VGG_TRIM_VGG_R_TRIM_ROW0_SHIFT   0
#define CFRAME0_REG_VGG_TRIM_VGG_R_TRIM_ROW0_WIDTH   4
#define CFRAME0_REG_VGG_TRIM_VGG_R_TRIM_ROW0_MASK    0X0000000F

/**
 * Register: CFRAME0_REG_CFRM_ISR
 */
#define CFRAME0_REG_CFRM_ISR    ( ( CFRAME0_REG_BASEADDR ) + 0X00000150 )

#define CFRAME0_REG_CFRM_ISR_READ_BROADCAST_ERROR_SHIFT   21
#define CFRAME0_REG_CFRM_ISR_READ_BROADCAST_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ISR_READ_BROADCAST_ERROR_MASK    0X00200000

#define CFRAME0_REG_CFRM_ISR_CMD_MISSING_ERROR_SHIFT   20
#define CFRAME0_REG_CFRM_ISR_CMD_MISSING_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ISR_CMD_MISSING_ERROR_MASK    0X00100000

#define CFRAME0_REG_CFRM_ISR_RW_ROWOFF_ERROR_SHIFT   19
#define CFRAME0_REG_CFRM_ISR_RW_ROWOFF_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ISR_RW_ROWOFF_ERROR_MASK    0X00080000

#define CFRAME0_REG_CFRM_ISR_READ_REG_ADDR_ERROR_SHIFT   18
#define CFRAME0_REG_CFRM_ISR_READ_REG_ADDR_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ISR_READ_REG_ADDR_ERROR_MASK    0X00040000

#define CFRAME0_REG_CFRM_ISR_READ_BLK_TYPE_ERROR_SHIFT   17
#define CFRAME0_REG_CFRM_ISR_READ_BLK_TYPE_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ISR_READ_BLK_TYPE_ERROR_MASK    0X00020000

#define CFRAME0_REG_CFRM_ISR_READ_FRAME_ADDR_ERROR_SHIFT   16
#define CFRAME0_REG_CFRM_ISR_READ_FRAME_ADDR_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ISR_READ_FRAME_ADDR_ERROR_MASK    0X00010000

#define CFRAME0_REG_CFRM_ISR_WRITE_REG_ADDR_ERROR_SHIFT   15
#define CFRAME0_REG_CFRM_ISR_WRITE_REG_ADDR_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ISR_WRITE_REG_ADDR_ERROR_MASK    0X00008000

#define CFRAME0_REG_CFRM_ISR_WRITE_SEG_ADDR_ERROR_SHIFT   14
#define CFRAME0_REG_CFRM_ISR_WRITE_SEG_ADDR_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ISR_WRITE_SEG_ADDR_ERROR_MASK    0X00004000

#define CFRAME0_REG_CFRM_ISR_WRITE_BLK_TYPE_ERROR_SHIFT   13
#define CFRAME0_REG_CFRM_ISR_WRITE_BLK_TYPE_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ISR_WRITE_BLK_TYPE_ERROR_MASK    0X00002000

#define CFRAME0_REG_CFRM_ISR_WRITE_FRAME_ADDR_ERROR_SHIFT   12
#define CFRAME0_REG_CFRM_ISR_WRITE_FRAME_ADDR_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ISR_WRITE_FRAME_ADDR_ERROR_MASK    0X00001000

#define CFRAME0_REG_CFRM_ISR_MFW_OVERRUN_ERROR_SHIFT   11
#define CFRAME0_REG_CFRM_ISR_MFW_OVERRUN_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ISR_MFW_OVERRUN_ERROR_MASK    0X00000800

#define CFRAME0_REG_CFRM_ISR_FAR_FIFO_UNDERFLOW_SHIFT   10
#define CFRAME0_REG_CFRM_ISR_FAR_FIFO_UNDERFLOW_WIDTH   1
#define CFRAME0_REG_CFRM_ISR_FAR_FIFO_UNDERFLOW_MASK    0X00000400

#define CFRAME0_REG_CFRM_ISR_FAR_FIFO_OVERFLOW_SHIFT   9
#define CFRAME0_REG_CFRM_ISR_FAR_FIFO_OVERFLOW_WIDTH   1
#define CFRAME0_REG_CFRM_ISR_FAR_FIFO_OVERFLOW_MASK    0X00000200

#define CFRAME0_REG_CFRM_ISR_PER_FRAME_SEQ_ERROR_SHIFT   8
#define CFRAME0_REG_CFRM_ISR_PER_FRAME_SEQ_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ISR_PER_FRAME_SEQ_ERROR_MASK    0X00000100

#define CFRAME0_REG_CFRM_ISR_CRC_ERROR_SHIFT   7
#define CFRAME0_REG_CFRM_ISR_CRC_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ISR_CRC_ERROR_MASK    0X00000080

#define CFRAME0_REG_CFRM_ISR_WRITE_OVERRUN_ERROR_SHIFT   6
#define CFRAME0_REG_CFRM_ISR_WRITE_OVERRUN_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ISR_WRITE_OVERRUN_ERROR_MASK    0X00000040

#define CFRAME0_REG_CFRM_ISR_READ_OVERRUN_ERROR_SHIFT   5
#define CFRAME0_REG_CFRM_ISR_READ_OVERRUN_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ISR_READ_OVERRUN_ERROR_MASK    0X00000020

#define CFRAME0_REG_CFRM_ISR_CMD_INTERRUPT_ERROR_SHIFT   4
#define CFRAME0_REG_CFRM_ISR_CMD_INTERRUPT_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ISR_CMD_INTERRUPT_ERROR_MASK    0X00000010

#define CFRAME0_REG_CFRM_ISR_WRITE_INTERRUPT_ERROR_SHIFT   3
#define CFRAME0_REG_CFRM_ISR_WRITE_INTERRUPT_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ISR_WRITE_INTERRUPT_ERROR_MASK    0X00000008

#define CFRAME0_REG_CFRM_ISR_READ_INTERRUPT_ERROR_SHIFT   2
#define CFRAME0_REG_CFRM_ISR_READ_INTERRUPT_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ISR_READ_INTERRUPT_ERROR_MASK    0X00000004

#define CFRAME0_REG_CFRM_ISR_SEU_CRC_ERROR_SHIFT   1
#define CFRAME0_REG_CFRM_ISR_SEU_CRC_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ISR_SEU_CRC_ERROR_MASK    0X00000002

#define CFRAME0_REG_CFRM_ISR_SEU_ECC_ERROR_SHIFT   0
#define CFRAME0_REG_CFRM_ISR_SEU_ECC_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ISR_SEU_ECC_ERROR_MASK    0X00000001

/**
 * Register: CFRAME0_REG_CFRM_IMR
 */
#define CFRAME0_REG_CFRM_IMR    ( ( CFRAME0_REG_BASEADDR ) + 0X00000160 )

#define CFRAME0_REG_CFRM_IMR_READ_BROADCAST_ERROR_SHIFT   21
#define CFRAME0_REG_CFRM_IMR_READ_BROADCAST_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IMR_READ_BROADCAST_ERROR_MASK    0X00200000

#define CFRAME0_REG_CFRM_IMR_CMD_MISSING_ERROR_SHIFT   20
#define CFRAME0_REG_CFRM_IMR_CMD_MISSING_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IMR_CMD_MISSING_ERROR_MASK    0X00100000

#define CFRAME0_REG_CFRM_IMR_RW_ROWOFF_ERROR_SHIFT   19
#define CFRAME0_REG_CFRM_IMR_RW_ROWOFF_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IMR_RW_ROWOFF_ERROR_MASK    0X00080000

#define CFRAME0_REG_CFRM_IMR_READ_REG_ADDR_ERROR_SHIFT   18
#define CFRAME0_REG_CFRM_IMR_READ_REG_ADDR_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IMR_READ_REG_ADDR_ERROR_MASK    0X00040000

#define CFRAME0_REG_CFRM_IMR_READ_BLK_TYPE_ERROR_SHIFT   17
#define CFRAME0_REG_CFRM_IMR_READ_BLK_TYPE_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IMR_READ_BLK_TYPE_ERROR_MASK    0X00020000

#define CFRAME0_REG_CFRM_IMR_READ_FRAME_ADDR_ERROR_SHIFT   16
#define CFRAME0_REG_CFRM_IMR_READ_FRAME_ADDR_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IMR_READ_FRAME_ADDR_ERROR_MASK    0X00010000

#define CFRAME0_REG_CFRM_IMR_WRITE_REG_ADDR_ERROR_SHIFT   15
#define CFRAME0_REG_CFRM_IMR_WRITE_REG_ADDR_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IMR_WRITE_REG_ADDR_ERROR_MASK    0X00008000

#define CFRAME0_REG_CFRM_IMR_WRITE_SEG_ADDR_ERROR_SHIFT   14
#define CFRAME0_REG_CFRM_IMR_WRITE_SEG_ADDR_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IMR_WRITE_SEG_ADDR_ERROR_MASK    0X00004000

#define CFRAME0_REG_CFRM_IMR_WRITE_BLK_TYPE_ERROR_SHIFT   13
#define CFRAME0_REG_CFRM_IMR_WRITE_BLK_TYPE_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IMR_WRITE_BLK_TYPE_ERROR_MASK    0X00002000

#define CFRAME0_REG_CFRM_IMR_WRITE_FRAME_ADDR_ERROR_SHIFT   12
#define CFRAME0_REG_CFRM_IMR_WRITE_FRAME_ADDR_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IMR_WRITE_FRAME_ADDR_ERROR_MASK    0X00001000

#define CFRAME0_REG_CFRM_IMR_MFW_OVERRUN_ERROR_SHIFT   11
#define CFRAME0_REG_CFRM_IMR_MFW_OVERRUN_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IMR_MFW_OVERRUN_ERROR_MASK    0X00000800

#define CFRAME0_REG_CFRM_IMR_FAR_FIFO_UNDERFLOW_SHIFT   10
#define CFRAME0_REG_CFRM_IMR_FAR_FIFO_UNDERFLOW_WIDTH   1
#define CFRAME0_REG_CFRM_IMR_FAR_FIFO_UNDERFLOW_MASK    0X00000400

#define CFRAME0_REG_CFRM_IMR_FAR_FIFO_OVERFLOW_SHIFT   9
#define CFRAME0_REG_CFRM_IMR_FAR_FIFO_OVERFLOW_WIDTH   1
#define CFRAME0_REG_CFRM_IMR_FAR_FIFO_OVERFLOW_MASK    0X00000200

#define CFRAME0_REG_CFRM_IMR_PER_FRAME_SEQ_ERROR_SHIFT   8
#define CFRAME0_REG_CFRM_IMR_PER_FRAME_SEQ_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IMR_PER_FRAME_SEQ_ERROR_MASK    0X00000100

#define CFRAME0_REG_CFRM_IMR_CRC_ERROR_SHIFT   7
#define CFRAME0_REG_CFRM_IMR_CRC_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IMR_CRC_ERROR_MASK    0X00000080

#define CFRAME0_REG_CFRM_IMR_WRITE_OVERRUN_ERROR_SHIFT   6
#define CFRAME0_REG_CFRM_IMR_WRITE_OVERRUN_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IMR_WRITE_OVERRUN_ERROR_MASK    0X00000040

#define CFRAME0_REG_CFRM_IMR_READ_OVERRUN_ERROR_SHIFT   5
#define CFRAME0_REG_CFRM_IMR_READ_OVERRUN_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IMR_READ_OVERRUN_ERROR_MASK    0X00000020

#define CFRAME0_REG_CFRM_IMR_CMD_INTERRUPT_ERROR_SHIFT   4
#define CFRAME0_REG_CFRM_IMR_CMD_INTERRUPT_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IMR_CMD_INTERRUPT_ERROR_MASK    0X00000010

#define CFRAME0_REG_CFRM_IMR_WRITE_INTERRUPT_ERROR_SHIFT   3
#define CFRAME0_REG_CFRM_IMR_WRITE_INTERRUPT_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IMR_WRITE_INTERRUPT_ERROR_MASK    0X00000008

#define CFRAME0_REG_CFRM_IMR_READ_INTERRUPT_ERROR_SHIFT   2
#define CFRAME0_REG_CFRM_IMR_READ_INTERRUPT_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IMR_READ_INTERRUPT_ERROR_MASK    0X00000004

#define CFRAME0_REG_CFRM_IMR_SEU_CRC_ERROR_SHIFT   1
#define CFRAME0_REG_CFRM_IMR_SEU_CRC_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IMR_SEU_CRC_ERROR_MASK    0X00000002

#define CFRAME0_REG_CFRM_IMR_SEU_ECC_ERROR_SHIFT   0
#define CFRAME0_REG_CFRM_IMR_SEU_ECC_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IMR_SEU_ECC_ERROR_MASK    0X00000001

/**
 * Register: CFRAME0_REG_CFRM_IER
 */
#define CFRAME0_REG_CFRM_IER    ( ( CFRAME0_REG_BASEADDR ) + 0X00000170 )

#define CFRAME0_REG_CFRM_IER_READ_BROADCAST_ERROR_SHIFT   21
#define CFRAME0_REG_CFRM_IER_READ_BROADCAST_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IER_READ_BROADCAST_ERROR_MASK    0X00200000

#define CFRAME0_REG_CFRM_IER_CMD_MISSING_ERROR_SHIFT   20
#define CFRAME0_REG_CFRM_IER_CMD_MISSING_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IER_CMD_MISSING_ERROR_MASK    0X00100000

#define CFRAME0_REG_CFRM_IER_RW_ROWOFF_ERROR_SHIFT   19
#define CFRAME0_REG_CFRM_IER_RW_ROWOFF_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IER_RW_ROWOFF_ERROR_MASK    0X00080000

#define CFRAME0_REG_CFRM_IER_READ_REG_ADDR_ERROR_SHIFT   18
#define CFRAME0_REG_CFRM_IER_READ_REG_ADDR_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IER_READ_REG_ADDR_ERROR_MASK    0X00040000

#define CFRAME0_REG_CFRM_IER_READ_BLK_TYPE_ERROR_SHIFT   17
#define CFRAME0_REG_CFRM_IER_READ_BLK_TYPE_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IER_READ_BLK_TYPE_ERROR_MASK    0X00020000

#define CFRAME0_REG_CFRM_IER_READ_FRAME_ADDR_ERROR_SHIFT   16
#define CFRAME0_REG_CFRM_IER_READ_FRAME_ADDR_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IER_READ_FRAME_ADDR_ERROR_MASK    0X00010000

#define CFRAME0_REG_CFRM_IER_WRITE_REG_ADDR_ERROR_SHIFT   15
#define CFRAME0_REG_CFRM_IER_WRITE_REG_ADDR_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IER_WRITE_REG_ADDR_ERROR_MASK    0X00008000

#define CFRAME0_REG_CFRM_IER_WRITE_SEG_ADDR_ERROR_SHIFT   14
#define CFRAME0_REG_CFRM_IER_WRITE_SEG_ADDR_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IER_WRITE_SEG_ADDR_ERROR_MASK    0X00004000

#define CFRAME0_REG_CFRM_IER_WRITE_BLK_TYPE_ERROR_SHIFT   13
#define CFRAME0_REG_CFRM_IER_WRITE_BLK_TYPE_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IER_WRITE_BLK_TYPE_ERROR_MASK    0X00002000

#define CFRAME0_REG_CFRM_IER_WRITE_FRAME_ADDR_ERROR_SHIFT   12
#define CFRAME0_REG_CFRM_IER_WRITE_FRAME_ADDR_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IER_WRITE_FRAME_ADDR_ERROR_MASK    0X00001000

#define CFRAME0_REG_CFRM_IER_MFW_OVERRUN_ERROR_SHIFT   11
#define CFRAME0_REG_CFRM_IER_MFW_OVERRUN_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IER_MFW_OVERRUN_ERROR_MASK    0X00000800

#define CFRAME0_REG_CFRM_IER_FAR_FIFO_UNDERFLOW_SHIFT   10
#define CFRAME0_REG_CFRM_IER_FAR_FIFO_UNDERFLOW_WIDTH   1
#define CFRAME0_REG_CFRM_IER_FAR_FIFO_UNDERFLOW_MASK    0X00000400

#define CFRAME0_REG_CFRM_IER_FAR_FIFO_OVERFLOW_SHIFT   9
#define CFRAME0_REG_CFRM_IER_FAR_FIFO_OVERFLOW_WIDTH   1
#define CFRAME0_REG_CFRM_IER_FAR_FIFO_OVERFLOW_MASK    0X00000200

#define CFRAME0_REG_CFRM_IER_PER_FRAME_SEQ_ERROR_SHIFT   8
#define CFRAME0_REG_CFRM_IER_PER_FRAME_SEQ_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IER_PER_FRAME_SEQ_ERROR_MASK    0X00000100

#define CFRAME0_REG_CFRM_IER_CRC_ERROR_SHIFT   7
#define CFRAME0_REG_CFRM_IER_CRC_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IER_CRC_ERROR_MASK    0X00000080

#define CFRAME0_REG_CFRM_IER_WRITE_OVERRUN_ERROR_SHIFT   6
#define CFRAME0_REG_CFRM_IER_WRITE_OVERRUN_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IER_WRITE_OVERRUN_ERROR_MASK    0X00000040

#define CFRAME0_REG_CFRM_IER_READ_OVERRUN_ERROR_SHIFT   5
#define CFRAME0_REG_CFRM_IER_READ_OVERRUN_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IER_READ_OVERRUN_ERROR_MASK    0X00000020

#define CFRAME0_REG_CFRM_IER_CMD_INTERRUPT_ERROR_SHIFT   4
#define CFRAME0_REG_CFRM_IER_CMD_INTERRUPT_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IER_CMD_INTERRUPT_ERROR_MASK    0X00000010

#define CFRAME0_REG_CFRM_IER_WRITE_INTERRUPT_ERROR_SHIFT   3
#define CFRAME0_REG_CFRM_IER_WRITE_INTERRUPT_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IER_WRITE_INTERRUPT_ERROR_MASK    0X00000008

#define CFRAME0_REG_CFRM_IER_READ_INTERRUPT_ERROR_SHIFT   2
#define CFRAME0_REG_CFRM_IER_READ_INTERRUPT_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IER_READ_INTERRUPT_ERROR_MASK    0X00000004

#define CFRAME0_REG_CFRM_IER_SEU_CRC_ERROR_SHIFT   1
#define CFRAME0_REG_CFRM_IER_SEU_CRC_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IER_SEU_CRC_ERROR_MASK    0X00000002

#define CFRAME0_REG_CFRM_IER_SEU_ECC_ERROR_SHIFT   0
#define CFRAME0_REG_CFRM_IER_SEU_ECC_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IER_SEU_ECC_ERROR_MASK    0X00000001

/**
 * Register: CFRAME0_REG_CFRM_IDR
 */
#define CFRAME0_REG_CFRM_IDR    ( ( CFRAME0_REG_BASEADDR ) + 0X00000180 )

#define CFRAME0_REG_CFRM_IDR_READ_BROADCAST_ERROR_SHIFT   21
#define CFRAME0_REG_CFRM_IDR_READ_BROADCAST_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IDR_READ_BROADCAST_ERROR_MASK    0X00200000

#define CFRAME0_REG_CFRM_IDR_CMD_MISSING_ERROR_SHIFT   20
#define CFRAME0_REG_CFRM_IDR_CMD_MISSING_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IDR_CMD_MISSING_ERROR_MASK    0X00100000

#define CFRAME0_REG_CFRM_IDR_RW_ROWOFF_ERROR_SHIFT   19
#define CFRAME0_REG_CFRM_IDR_RW_ROWOFF_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IDR_RW_ROWOFF_ERROR_MASK    0X00080000

#define CFRAME0_REG_CFRM_IDR_READ_REG_ADDR_ERROR_SHIFT   18
#define CFRAME0_REG_CFRM_IDR_READ_REG_ADDR_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IDR_READ_REG_ADDR_ERROR_MASK    0X00040000

#define CFRAME0_REG_CFRM_IDR_READ_BLK_TYPE_ERROR_SHIFT   17
#define CFRAME0_REG_CFRM_IDR_READ_BLK_TYPE_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IDR_READ_BLK_TYPE_ERROR_MASK    0X00020000

#define CFRAME0_REG_CFRM_IDR_READ_FRAME_ADDR_ERROR_SHIFT   16
#define CFRAME0_REG_CFRM_IDR_READ_FRAME_ADDR_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IDR_READ_FRAME_ADDR_ERROR_MASK    0X00010000

#define CFRAME0_REG_CFRM_IDR_WRITE_REG_ADDR_ERROR_SHIFT   15
#define CFRAME0_REG_CFRM_IDR_WRITE_REG_ADDR_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IDR_WRITE_REG_ADDR_ERROR_MASK    0X00008000

#define CFRAME0_REG_CFRM_IDR_WRITE_SEG_ADDR_ERROR_SHIFT   14
#define CFRAME0_REG_CFRM_IDR_WRITE_SEG_ADDR_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IDR_WRITE_SEG_ADDR_ERROR_MASK    0X00004000

#define CFRAME0_REG_CFRM_IDR_WRITE_BLK_TYPE_ERROR_SHIFT   13
#define CFRAME0_REG_CFRM_IDR_WRITE_BLK_TYPE_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IDR_WRITE_BLK_TYPE_ERROR_MASK    0X00002000

#define CFRAME0_REG_CFRM_IDR_WRITE_FRAME_ADDR_ERROR_SHIFT   12
#define CFRAME0_REG_CFRM_IDR_WRITE_FRAME_ADDR_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IDR_WRITE_FRAME_ADDR_ERROR_MASK    0X00001000

#define CFRAME0_REG_CFRM_IDR_MFW_OVERRUN_ERROR_SHIFT   11
#define CFRAME0_REG_CFRM_IDR_MFW_OVERRUN_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IDR_MFW_OVERRUN_ERROR_MASK    0X00000800

#define CFRAME0_REG_CFRM_IDR_FAR_FIFO_UNDERFLOW_SHIFT   10
#define CFRAME0_REG_CFRM_IDR_FAR_FIFO_UNDERFLOW_WIDTH   1
#define CFRAME0_REG_CFRM_IDR_FAR_FIFO_UNDERFLOW_MASK    0X00000400

#define CFRAME0_REG_CFRM_IDR_FAR_FIFO_OVERFLOW_SHIFT   9
#define CFRAME0_REG_CFRM_IDR_FAR_FIFO_OVERFLOW_WIDTH   1
#define CFRAME0_REG_CFRM_IDR_FAR_FIFO_OVERFLOW_MASK    0X00000200

#define CFRAME0_REG_CFRM_IDR_PER_FRAME_SEQ_ERROR_SHIFT   8
#define CFRAME0_REG_CFRM_IDR_PER_FRAME_SEQ_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IDR_PER_FRAME_SEQ_ERROR_MASK    0X00000100

#define CFRAME0_REG_CFRM_IDR_CRC_ERROR_SHIFT   7
#define CFRAME0_REG_CFRM_IDR_CRC_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IDR_CRC_ERROR_MASK    0X00000080

#define CFRAME0_REG_CFRM_IDR_WRITE_OVERRUN_ERROR_SHIFT   6
#define CFRAME0_REG_CFRM_IDR_WRITE_OVERRUN_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IDR_WRITE_OVERRUN_ERROR_MASK    0X00000040

#define CFRAME0_REG_CFRM_IDR_READ_OVERRUN_ERROR_SHIFT   5
#define CFRAME0_REG_CFRM_IDR_READ_OVERRUN_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IDR_READ_OVERRUN_ERROR_MASK    0X00000020

#define CFRAME0_REG_CFRM_IDR_CMD_INTERRUPT_ERROR_SHIFT   4
#define CFRAME0_REG_CFRM_IDR_CMD_INTERRUPT_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IDR_CMD_INTERRUPT_ERROR_MASK    0X00000010

#define CFRAME0_REG_CFRM_IDR_WRITE_INTERRUPT_ERROR_SHIFT   3
#define CFRAME0_REG_CFRM_IDR_WRITE_INTERRUPT_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IDR_WRITE_INTERRUPT_ERROR_MASK    0X00000008

#define CFRAME0_REG_CFRM_IDR_READ_INTERRUPT_ERROR_SHIFT   2
#define CFRAME0_REG_CFRM_IDR_READ_INTERRUPT_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IDR_READ_INTERRUPT_ERROR_MASK    0X00000004

#define CFRAME0_REG_CFRM_IDR_SEU_CRC_ERROR_SHIFT   1
#define CFRAME0_REG_CFRM_IDR_SEU_CRC_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IDR_SEU_CRC_ERROR_MASK    0X00000002

#define CFRAME0_REG_CFRM_IDR_SEU_ECC_ERROR_SHIFT   0
#define CFRAME0_REG_CFRM_IDR_SEU_ECC_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_IDR_SEU_ECC_ERROR_MASK    0X00000001

/**
 * Register: CFRAME0_REG_CFRM_ITR
 */
#define CFRAME0_REG_CFRM_ITR    ( ( CFRAME0_REG_BASEADDR ) + 0X00000190 )

#define CFRAME0_REG_CFRM_ITR_READ_BROADCAST_ERROR_SHIFT   21
#define CFRAME0_REG_CFRM_ITR_READ_BROADCAST_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ITR_READ_BROADCAST_ERROR_MASK    0X00200000

#define CFRAME0_REG_CFRM_ITR_CMD_MISSING_ERROR_SHIFT   20
#define CFRAME0_REG_CFRM_ITR_CMD_MISSING_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ITR_CMD_MISSING_ERROR_MASK    0X00100000

#define CFRAME0_REG_CFRM_ITR_RW_ROWOFF_ERROR_SHIFT   19
#define CFRAME0_REG_CFRM_ITR_RW_ROWOFF_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ITR_RW_ROWOFF_ERROR_MASK    0X00080000

#define CFRAME0_REG_CFRM_ITR_READ_REG_ADDR_ERROR_SHIFT   18
#define CFRAME0_REG_CFRM_ITR_READ_REG_ADDR_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ITR_READ_REG_ADDR_ERROR_MASK    0X00040000

#define CFRAME0_REG_CFRM_ITR_READ_BLK_TYPE_ERROR_SHIFT   17
#define CFRAME0_REG_CFRM_ITR_READ_BLK_TYPE_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ITR_READ_BLK_TYPE_ERROR_MASK    0X00020000

#define CFRAME0_REG_CFRM_ITR_READ_FRAME_ADDR_ERROR_SHIFT   16
#define CFRAME0_REG_CFRM_ITR_READ_FRAME_ADDR_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ITR_READ_FRAME_ADDR_ERROR_MASK    0X00010000

#define CFRAME0_REG_CFRM_ITR_WRITE_REG_ADDR_ERROR_SHIFT   15
#define CFRAME0_REG_CFRM_ITR_WRITE_REG_ADDR_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ITR_WRITE_REG_ADDR_ERROR_MASK    0X00008000

#define CFRAME0_REG_CFRM_ITR_WRITE_SEG_ADDR_ERROR_SHIFT   14
#define CFRAME0_REG_CFRM_ITR_WRITE_SEG_ADDR_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ITR_WRITE_SEG_ADDR_ERROR_MASK    0X00004000

#define CFRAME0_REG_CFRM_ITR_WRITE_BLK_TYPE_ERROR_SHIFT   13
#define CFRAME0_REG_CFRM_ITR_WRITE_BLK_TYPE_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ITR_WRITE_BLK_TYPE_ERROR_MASK    0X00002000

#define CFRAME0_REG_CFRM_ITR_WRITE_FRAME_ADDR_ERROR_SHIFT   12
#define CFRAME0_REG_CFRM_ITR_WRITE_FRAME_ADDR_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ITR_WRITE_FRAME_ADDR_ERROR_MASK    0X00001000

#define CFRAME0_REG_CFRM_ITR_MFW_OVERRUN_ERROR_SHIFT   11
#define CFRAME0_REG_CFRM_ITR_MFW_OVERRUN_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ITR_MFW_OVERRUN_ERROR_MASK    0X00000800

#define CFRAME0_REG_CFRM_ITR_FAR_FIFO_UNDERFLOW_SHIFT   10
#define CFRAME0_REG_CFRM_ITR_FAR_FIFO_UNDERFLOW_WIDTH   1
#define CFRAME0_REG_CFRM_ITR_FAR_FIFO_UNDERFLOW_MASK    0X00000400

#define CFRAME0_REG_CFRM_ITR_FAR_FIFO_OVERFLOW_SHIFT   9
#define CFRAME0_REG_CFRM_ITR_FAR_FIFO_OVERFLOW_WIDTH   1
#define CFRAME0_REG_CFRM_ITR_FAR_FIFO_OVERFLOW_MASK    0X00000200

#define CFRAME0_REG_CFRM_ITR_PER_FRAME_SEQ_ERROR_SHIFT   8
#define CFRAME0_REG_CFRM_ITR_PER_FRAME_SEQ_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ITR_PER_FRAME_SEQ_ERROR_MASK    0X00000100

#define CFRAME0_REG_CFRM_ITR_CRC_ERROR_SHIFT   7
#define CFRAME0_REG_CFRM_ITR_CRC_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ITR_CRC_ERROR_MASK    0X00000080

#define CFRAME0_REG_CFRM_ITR_WRITE_OVERRUN_ERROR_SHIFT   6
#define CFRAME0_REG_CFRM_ITR_WRITE_OVERRUN_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ITR_WRITE_OVERRUN_ERROR_MASK    0X00000040

#define CFRAME0_REG_CFRM_ITR_READ_OVERRUN_ERROR_SHIFT   5
#define CFRAME0_REG_CFRM_ITR_READ_OVERRUN_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ITR_READ_OVERRUN_ERROR_MASK    0X00000020

#define CFRAME0_REG_CFRM_ITR_CMD_INTERRUPT_ERROR_SHIFT   4
#define CFRAME0_REG_CFRM_ITR_CMD_INTERRUPT_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ITR_CMD_INTERRUPT_ERROR_MASK    0X00000010

#define CFRAME0_REG_CFRM_ITR_WRITE_INTERRUPT_ERROR_SHIFT   3
#define CFRAME0_REG_CFRM_ITR_WRITE_INTERRUPT_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ITR_WRITE_INTERRUPT_ERROR_MASK    0X00000008

#define CFRAME0_REG_CFRM_ITR_READ_INTERRUPT_ERROR_SHIFT   2
#define CFRAME0_REG_CFRM_ITR_READ_INTERRUPT_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ITR_READ_INTERRUPT_ERROR_MASK    0X00000004

#define CFRAME0_REG_CFRM_ITR_SEU_CRC_ERROR_SHIFT   1
#define CFRAME0_REG_CFRM_ITR_SEU_CRC_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ITR_SEU_CRC_ERROR_MASK    0X00000002

#define CFRAME0_REG_CFRM_ITR_SEU_ECC_ERROR_SHIFT   0
#define CFRAME0_REG_CFRM_ITR_SEU_ECC_ERROR_WIDTH   1
#define CFRAME0_REG_CFRM_ITR_SEU_ECC_ERROR_MASK    0X00000001

/**
 * Register: CFRAME0_REG_SEU_SYNDRM0
 */
#define CFRAME0_REG_SEU_SYNDRM0    ( ( CFRAME0_REG_BASEADDR ) + 0X000001A0 )

#define CFRAME0_REG_SEU_SYNDRM0_EFAR_FRAME0_SHIFT   48
#define CFRAME0_REG_SEU_SYNDRM0_EFAR_FRAME0_WIDTH   23
#define CFRAME0_REG_SEU_SYNDRM0_EFAR_FRAME0_MASK    0X7FFFFF000000000000

#define CFRAME0_REG_SEU_SYNDRM0_FRM0_SEG1_VIRT1_SHIFT   36
#define CFRAME0_REG_SEU_SYNDRM0_FRM0_SEG1_VIRT1_WIDTH   12
#define CFRAME0_REG_SEU_SYNDRM0_FRM0_SEG1_VIRT1_MASK    0XFFF000000000

#define CFRAME0_REG_SEU_SYNDRM0_FRM0_SEG1_VIRT0_SHIFT   24
#define CFRAME0_REG_SEU_SYNDRM0_FRM0_SEG1_VIRT0_WIDTH   12
#define CFRAME0_REG_SEU_SYNDRM0_FRM0_SEG1_VIRT0_MASK    0XFFF000000

#define CFRAME0_REG_SEU_SYNDRM0_FRM0_SEG0_VIRT1_SHIFT   12
#define CFRAME0_REG_SEU_SYNDRM0_FRM0_SEG0_VIRT1_WIDTH   12
#define CFRAME0_REG_SEU_SYNDRM0_FRM0_SEG0_VIRT1_MASK    0X00FFF000

#define CFRAME0_REG_SEU_SYNDRM0_FRM0_SEG0_VIRT0_SHIFT   0
#define CFRAME0_REG_SEU_SYNDRM0_FRM0_SEG0_VIRT0_WIDTH   12
#define CFRAME0_REG_SEU_SYNDRM0_FRM0_SEG0_VIRT0_MASK    0X00000FFF

/**
 * Register: CFRAME0_REG_SEU_SYNDRM1
 */
#define CFRAME0_REG_SEU_SYNDRM1    ( ( CFRAME0_REG_BASEADDR ) + 0X000001B0 )

#define CFRAME0_REG_SEU_SYNDRM1_EFAR_FRAME1_SHIFT   48
#define CFRAME0_REG_SEU_SYNDRM1_EFAR_FRAME1_WIDTH   23
#define CFRAME0_REG_SEU_SYNDRM1_EFAR_FRAME1_MASK    0X7FFFFF000000000000

#define CFRAME0_REG_SEU_SYNDRM1_FRM1_SEG1_VIRT1_SHIFT   36
#define CFRAME0_REG_SEU_SYNDRM1_FRM1_SEG1_VIRT1_WIDTH   12
#define CFRAME0_REG_SEU_SYNDRM1_FRM1_SEG1_VIRT1_MASK    0XFFF000000000

#define CFRAME0_REG_SEU_SYNDRM1_FRM1_SEG1_VIRT0_SHIFT   24
#define CFRAME0_REG_SEU_SYNDRM1_FRM1_SEG1_VIRT0_WIDTH   12
#define CFRAME0_REG_SEU_SYNDRM1_FRM1_SEG1_VIRT0_MASK    0XFFF000000

#define CFRAME0_REG_SEU_SYNDRM1_FRM1_SEG0_VIRT1_SHIFT   12
#define CFRAME0_REG_SEU_SYNDRM1_FRM1_SEG0_VIRT1_WIDTH   12
#define CFRAME0_REG_SEU_SYNDRM1_FRM1_SEG0_VIRT1_MASK    0X00FFF000

#define CFRAME0_REG_SEU_SYNDRM1_FRM1_SEG0_VIRT0_SHIFT   0
#define CFRAME0_REG_SEU_SYNDRM1_FRM1_SEG0_VIRT0_WIDTH   12
#define CFRAME0_REG_SEU_SYNDRM1_FRM1_SEG0_VIRT0_MASK    0X00000FFF

/**
 * Register: CFRAME0_REG_SEU_SYNDRM2
 */
#define CFRAME0_REG_SEU_SYNDRM2    ( ( CFRAME0_REG_BASEADDR ) + 0X000001C0 )

#define CFRAME0_REG_SEU_SYNDRM2_EFAR_FRAME2_SHIFT   48
#define CFRAME0_REG_SEU_SYNDRM2_EFAR_FRAME2_WIDTH   23
#define CFRAME0_REG_SEU_SYNDRM2_EFAR_FRAME2_MASK    0X7FFFFF000000000000

#define CFRAME0_REG_SEU_SYNDRM2_FRM2_SEG1_VIRT1_SHIFT   36
#define CFRAME0_REG_SEU_SYNDRM2_FRM2_SEG1_VIRT1_WIDTH   12
#define CFRAME0_REG_SEU_SYNDRM2_FRM2_SEG1_VIRT1_MASK    0XFFF000000000

#define CFRAME0_REG_SEU_SYNDRM2_FRM2_SEG1_VIRT0_SHIFT   24
#define CFRAME0_REG_SEU_SYNDRM2_FRM2_SEG1_VIRT0_WIDTH   12
#define CFRAME0_REG_SEU_SYNDRM2_FRM2_SEG1_VIRT0_MASK    0XFFF000000

#define CFRAME0_REG_SEU_SYNDRM2_FRM2_SEG0_VIRT1_SHIFT   12
#define CFRAME0_REG_SEU_SYNDRM2_FRM2_SEG0_VIRT1_WIDTH   12
#define CFRAME0_REG_SEU_SYNDRM2_FRM2_SEG0_VIRT1_MASK    0X00FFF000

#define CFRAME0_REG_SEU_SYNDRM2_FRM2_SEG0_VIRT0_SHIFT   0
#define CFRAME0_REG_SEU_SYNDRM2_FRM2_SEG0_VIRT0_WIDTH   12
#define CFRAME0_REG_SEU_SYNDRM2_FRM2_SEG0_VIRT0_MASK    0X00000FFF

/**
 * Register: CFRAME0_REG_SEU_SYNDRM3
 */
#define CFRAME0_REG_SEU_SYNDRM3    ( ( CFRAME0_REG_BASEADDR ) + 0X000001D0 )

#define CFRAME0_REG_SEU_SYNDRM3_EFAR_FRAME3_SHIFT   48
#define CFRAME0_REG_SEU_SYNDRM3_EFAR_FRAME3_WIDTH   23
#define CFRAME0_REG_SEU_SYNDRM3_EFAR_FRAME3_MASK    0X7FFFFF000000000000

#define CFRAME0_REG_SEU_SYNDRM3_FRM3_SEG1_VIRT1_SHIFT   36
#define CFRAME0_REG_SEU_SYNDRM3_FRM3_SEG1_VIRT1_WIDTH   12
#define CFRAME0_REG_SEU_SYNDRM3_FRM3_SEG1_VIRT1_MASK    0XFFF000000000

#define CFRAME0_REG_SEU_SYNDRM3_FRM3_SEG1_VIRT0_SHIFT   24
#define CFRAME0_REG_SEU_SYNDRM3_FRM3_SEG1_VIRT0_WIDTH   12
#define CFRAME0_REG_SEU_SYNDRM3_FRM3_SEG1_VIRT0_MASK    0XFFF000000

#define CFRAME0_REG_SEU_SYNDRM3_FRM3_SEG0_VIRT1_SHIFT   12
#define CFRAME0_REG_SEU_SYNDRM3_FRM3_SEG0_VIRT1_WIDTH   12
#define CFRAME0_REG_SEU_SYNDRM3_FRM3_SEG0_VIRT1_MASK    0X00FFF000

#define CFRAME0_REG_SEU_SYNDRM3_FRM3_SEG0_VIRT0_SHIFT   0
#define CFRAME0_REG_SEU_SYNDRM3_FRM3_SEG0_VIRT0_WIDTH   12
#define CFRAME0_REG_SEU_SYNDRM3_FRM3_SEG0_VIRT0_MASK    0X00000FFF

/**
 * Register: CFRAME0_REG_SEU_VIRTUAL_SYNDRM
 */
#define CFRAME0_REG_SEU_VIRTUAL_SYNDRM    ( ( CFRAME0_REG_BASEADDR ) + 0X000001E0 )

#define CFRAME0_REG_SEU_VIRTUAL_SYNDRM_FAR_FRAME0_SHIFT   48
#define CFRAME0_REG_SEU_VIRTUAL_SYNDRM_FAR_FRAME0_WIDTH   23
#define CFRAME0_REG_SEU_VIRTUAL_SYNDRM_FAR_FRAME0_MASK    0X7FFFFF000000000000

#define CFRAME0_REG_SEU_VIRTUAL_SYNDRM_FRM0_SEG1_VIRT1_SHIFT   36
#define CFRAME0_REG_SEU_VIRTUAL_SYNDRM_FRM0_SEG1_VIRT1_WIDTH   12
#define CFRAME0_REG_SEU_VIRTUAL_SYNDRM_FRM0_SEG1_VIRT1_MASK    0XFFF000000000

#define CFRAME0_REG_SEU_VIRTUAL_SYNDRM_FRM0_SEG1_VIRT0_SHIFT   24
#define CFRAME0_REG_SEU_VIRTUAL_SYNDRM_FRM0_SEG1_VIRT0_WIDTH   12
#define CFRAME0_REG_SEU_VIRTUAL_SYNDRM_FRM0_SEG1_VIRT0_MASK    0XFFF000000

#define CFRAME0_REG_SEU_VIRTUAL_SYNDRM_FRM0_SEG0_VIRT1_SHIFT   12
#define CFRAME0_REG_SEU_VIRTUAL_SYNDRM_FRM0_SEG0_VIRT1_WIDTH   12
#define CFRAME0_REG_SEU_VIRTUAL_SYNDRM_FRM0_SEG0_VIRT1_MASK    0X00FFF000

#define CFRAME0_REG_SEU_VIRTUAL_SYNDRM_FRM0_SEG0_VIRT0_SHIFT   0
#define CFRAME0_REG_SEU_VIRTUAL_SYNDRM_FRM0_SEG0_VIRT0_WIDTH   12
#define CFRAME0_REG_SEU_VIRTUAL_SYNDRM_FRM0_SEG0_VIRT0_MASK    0X00000FFF

/**
 * Register: CFRAME0_REG_SEU_CRC
 */
#define CFRAME0_REG_SEU_CRC    ( ( CFRAME0_REG_BASEADDR ) + 0X000001F0 )

#define CFRAME0_REG_SEU_CRC_SEU_HWCRC_SS_SHIFT   96
#define CFRAME0_REG_SEU_CRC_SEU_HWCRC_SS_WIDTH   32
#define CFRAME0_REG_SEU_CRC_SEU_HWCRC_SS_MASK    0XFFFFFFFF000000000000000000000000

#define CFRAME0_REG_SEU_CRC_SEU_HWCRC_SHIFT   64
#define CFRAME0_REG_SEU_CRC_SEU_HWCRC_WIDTH   32
#define CFRAME0_REG_SEU_CRC_SEU_HWCRC_MASK    0XFFFFFFFF0000000000000000

#define CFRAME0_REG_SEU_CRC_SEU_HWCRC_LIVE_SHIFT   32
#define CFRAME0_REG_SEU_CRC_SEU_HWCRC_LIVE_WIDTH   32
#define CFRAME0_REG_SEU_CRC_SEU_HWCRC_LIVE_MASK    0XFFFFFFFF00000000

#define CFRAME0_REG_SEU_CRC_SEU_SWCRC_LIVE_SHIFT   0
#define CFRAME0_REG_SEU_CRC_SEU_SWCRC_LIVE_WIDTH   32
#define CFRAME0_REG_SEU_CRC_SEU_SWCRC_LIVE_MASK    0XFFFFFFFF

/**
 * Register: CFRAME0_REG_CFRAME_FAR_BOT
 */
#define CFRAME0_REG_CFRAME_FAR_BOT    ( ( CFRAME0_REG_BASEADDR ) + 0X00000200 )

#define CFRAME0_REG_CFRAME_FAR_BOT_CFRAME_ADDR_3_SHIFT   60
#define CFRAME0_REG_CFRAME_FAR_BOT_CFRAME_ADDR_3_WIDTH   20
#define CFRAME0_REG_CFRAME_FAR_BOT_CFRAME_ADDR_3_MASK    0XFFFFF000000000000000

#define CFRAME0_REG_CFRAME_FAR_BOT_CFRAME_ADDR_2_SHIFT   40
#define CFRAME0_REG_CFRAME_FAR_BOT_CFRAME_ADDR_2_WIDTH   20
#define CFRAME0_REG_CFRAME_FAR_BOT_CFRAME_ADDR_2_MASK    0XFFFFF0000000000

#define CFRAME0_REG_CFRAME_FAR_BOT_CFRAME_ADDR_1_SHIFT   20
#define CFRAME0_REG_CFRAME_FAR_BOT_CFRAME_ADDR_1_WIDTH   20
#define CFRAME0_REG_CFRAME_FAR_BOT_CFRAME_ADDR_1_MASK    0XFFFFF00000

#define CFRAME0_REG_CFRAME_FAR_BOT_CFRAME_ADDR_0_SHIFT   0
#define CFRAME0_REG_CFRAME_FAR_BOT_CFRAME_ADDR_0_WIDTH   20
#define CFRAME0_REG_CFRAME_FAR_BOT_CFRAME_ADDR_0_MASK    0X000FFFFF

/**
 * Register: CFRAME0_REG_CFRAME_FAR_TOP
 */
#define CFRAME0_REG_CFRAME_FAR_TOP    ( ( CFRAME0_REG_BASEADDR ) + 0X00000210 )

#define CFRAME0_REG_CFRAME_FAR_TOP_CFRAME_ADDR_6_SHIFT   40
#define CFRAME0_REG_CFRAME_FAR_TOP_CFRAME_ADDR_6_WIDTH   20
#define CFRAME0_REG_CFRAME_FAR_TOP_CFRAME_ADDR_6_MASK    0XFFFFF0000000000

#define CFRAME0_REG_CFRAME_FAR_TOP_CFRAME_ADDR_5_SHIFT   20
#define CFRAME0_REG_CFRAME_FAR_TOP_CFRAME_ADDR_5_WIDTH   20
#define CFRAME0_REG_CFRAME_FAR_TOP_CFRAME_ADDR_5_MASK    0XFFFFF00000

#define CFRAME0_REG_CFRAME_FAR_TOP_CFRAME_ADDR_4_SHIFT   0
#define CFRAME0_REG_CFRAME_FAR_TOP_CFRAME_ADDR_4_WIDTH   20
#define CFRAME0_REG_CFRAME_FAR_TOP_CFRAME_ADDR_4_MASK    0X000FFFFF

/**
 * Register: CFRAME0_REG_LAST_FRAME_BOT
 */
#define CFRAME0_REG_LAST_FRAME_BOT    ( ( CFRAME0_REG_BASEADDR ) + 0X00000220 )

#define CFRAME0_REG_LAST_FRAME_BOT_FRAME_ADDR_3_SHIFT   60
#define CFRAME0_REG_LAST_FRAME_BOT_FRAME_ADDR_3_WIDTH   20
#define CFRAME0_REG_LAST_FRAME_BOT_FRAME_ADDR_3_MASK    0XFFFFF000000000000000

#define CFRAME0_REG_LAST_FRAME_BOT_FRAME_ADDR_2_SHIFT   40
#define CFRAME0_REG_LAST_FRAME_BOT_FRAME_ADDR_2_WIDTH   20
#define CFRAME0_REG_LAST_FRAME_BOT_FRAME_ADDR_2_MASK    0XFFFFF0000000000

#define CFRAME0_REG_LAST_FRAME_BOT_FRAME_ADDR_1_SHIFT   20
#define CFRAME0_REG_LAST_FRAME_BOT_FRAME_ADDR_1_WIDTH   20
#define CFRAME0_REG_LAST_FRAME_BOT_FRAME_ADDR_1_MASK    0XFFFFF00000

#define CFRAME0_REG_LAST_FRAME_BOT_FRAME_ADDR_0_SHIFT   0
#define CFRAME0_REG_LAST_FRAME_BOT_FRAME_ADDR_0_WIDTH   20
#define CFRAME0_REG_LAST_FRAME_BOT_FRAME_ADDR_0_MASK    0X000FFFFF

/**
 * Register: CFRAME0_REG_LAST_FRAME_TOP
 */
#define CFRAME0_REG_LAST_FRAME_TOP    ( ( CFRAME0_REG_BASEADDR ) + 0X00000230 )

#define CFRAME0_REG_LAST_FRAME_TOP_FRAME_ADDR_6_SHIFT   40
#define CFRAME0_REG_LAST_FRAME_TOP_FRAME_ADDR_6_WIDTH   20
#define CFRAME0_REG_LAST_FRAME_TOP_FRAME_ADDR_6_MASK    0XFFFFF0000000000

#define CFRAME0_REG_LAST_FRAME_TOP_FRAME_ADDR_5_SHIFT   20
#define CFRAME0_REG_LAST_FRAME_TOP_FRAME_ADDR_5_WIDTH   20
#define CFRAME0_REG_LAST_FRAME_TOP_FRAME_ADDR_5_MASK    0XFFFFF00000

#define CFRAME0_REG_LAST_FRAME_TOP_FRAME_ADDR_4_SHIFT   0
#define CFRAME0_REG_LAST_FRAME_TOP_FRAME_ADDR_4_WIDTH   20
#define CFRAME0_REG_LAST_FRAME_TOP_FRAME_ADDR_4_MASK    0X000FFFFF

/**
 * Register: CFRAME0_REG_STATUS
 */
#define CFRAME0_REG_STATUS    ( ( CFRAME0_REG_BASEADDR ) + 0X00000240 )

#define CFRAME0_REG_STATUS_TM_MINICBRK_AND_SHIFT   29
#define CFRAME0_REG_STATUS_TM_MINICBRK_AND_WIDTH   1
#define CFRAME0_REG_STATUS_TM_MINICBRK_AND_MASK    0X20000000

#define CFRAME0_REG_STATUS_TM_MINICBRK_OR_SHIFT   28
#define CFRAME0_REG_STATUS_TM_MINICBRK_OR_WIDTH   1
#define CFRAME0_REG_STATUS_TM_MINICBRK_OR_MASK    0X10000000

#define CFRAME0_REG_STATUS_ECC_CORRECT_SW_SHIFT   27
#define CFRAME0_REG_STATUS_ECC_CORRECT_SW_WIDTH   1
#define CFRAME0_REG_STATUS_ECC_CORRECT_SW_MASK    0X08000000

#define CFRAME0_REG_STATUS_SPARE_SHIFT   26
#define CFRAME0_REG_STATUS_SPARE_WIDTH   1
#define CFRAME0_REG_STATUS_SPARE_MASK    0X04000000

#define CFRAME0_REG_STATUS_ADDR_WRAP_WRITE_SHIFT   25
#define CFRAME0_REG_STATUS_ADDR_WRAP_WRITE_WIDTH   1
#define CFRAME0_REG_STATUS_ADDR_WRAP_WRITE_MASK    0X02000000

#define CFRAME0_REG_STATUS_SEU_SEL_SCAN_TOO_BIG_SHIFT   24
#define CFRAME0_REG_STATUS_SEU_SEL_SCAN_TOO_BIG_WIDTH   1
#define CFRAME0_REG_STATUS_SEU_SEL_SCAN_TOO_BIG_MASK    0X01000000

#define CFRAME0_REG_STATUS_SVD_SETTING_TOO_BIG_SHIFT   23
#define CFRAME0_REG_STATUS_SVD_SETTING_TOO_BIG_WIDTH   1
#define CFRAME0_REG_STATUS_SVD_SETTING_TOO_BIG_MASK    0X00800000

#define CFRAME0_REG_STATUS_HOUSECLEAN_STATE_SHIFT   19
#define CFRAME0_REG_STATUS_HOUSECLEAN_STATE_WIDTH   4
#define CFRAME0_REG_STATUS_HOUSECLEAN_STATE_MASK    0X00780000

#define CFRAME0_REG_STATUS_MAIN_STATE_SHIFT   15
#define CFRAME0_REG_STATUS_MAIN_STATE_WIDTH   4
#define CFRAME0_REG_STATUS_MAIN_STATE_MASK    0X00078000

#define CFRAME0_REG_STATUS_SEU_STATE_SHIFT   12
#define CFRAME0_REG_STATUS_SEU_STATE_WIDTH   3
#define CFRAME0_REG_STATUS_SEU_STATE_MASK    0X00007000

#define CFRAME0_REG_STATUS_SEU_GO_SHIFT   11
#define CFRAME0_REG_STATUS_SEU_GO_WIDTH   1
#define CFRAME0_REG_STATUS_SEU_GO_MASK    0X00000800

#define CFRAME0_REG_STATUS_ECC_RUN_SHIFT   10
#define CFRAME0_REG_STATUS_ECC_RUN_WIDTH   1
#define CFRAME0_REG_STATUS_ECC_RUN_MASK    0X00000400

#define CFRAME0_REG_STATUS_END_OF_CALIB_SHIFT   9
#define CFRAME0_REG_STATUS_END_OF_CALIB_WIDTH   1
#define CFRAME0_REG_STATUS_END_OF_CALIB_MASK    0X00000200

#define CFRAME0_REG_STATUS_NORMAL_RUN_SHIFT   8
#define CFRAME0_REG_STATUS_NORMAL_RUN_WIDTH   1
#define CFRAME0_REG_STATUS_NORMAL_RUN_MASK    0X00000100

#define CFRAME0_REG_STATUS_ROW_SELECTED_ROWON_SHIFT   7
#define CFRAME0_REG_STATUS_ROW_SELECTED_ROWON_WIDTH   1
#define CFRAME0_REG_STATUS_ROW_SELECTED_ROWON_MASK    0X00000080

#define CFRAME0_REG_STATUS_ROW_SELECTED_CFI_SHIFT   6
#define CFRAME0_REG_STATUS_ROW_SELECTED_CFI_WIDTH   1
#define CFRAME0_REG_STATUS_ROW_SELECTED_CFI_MASK    0X00000040

#define CFRAME0_REG_STATUS_CRAM_WRITE_SHIFT   5
#define CFRAME0_REG_STATUS_CRAM_WRITE_WIDTH   1
#define CFRAME0_REG_STATUS_CRAM_WRITE_MASK    0X00000020

#define CFRAME0_REG_STATUS_CFRM_BUSY_SM_SHIFT   4
#define CFRAME0_REG_STATUS_CFRM_BUSY_SM_WIDTH   1
#define CFRAME0_REG_STATUS_CFRM_BUSY_SM_MASK    0X00000010

#define CFRAME0_REG_STATUS_CFRM_BUSY_RLF_SHIFT   3
#define CFRAME0_REG_STATUS_CFRM_BUSY_RLF_WIDTH   1
#define CFRAME0_REG_STATUS_CFRM_BUSY_RLF_MASK    0X00000008

#define CFRAME0_REG_STATUS_CFRM_BUSY_SEU_SHIFT   2
#define CFRAME0_REG_STATUS_CFRM_BUSY_SEU_WIDTH   1
#define CFRAME0_REG_STATUS_CFRM_BUSY_SEU_MASK    0X00000004

#define CFRAME0_REG_STATUS_SECVIO_SHIFT   1
#define CFRAME0_REG_STATUS_SECVIO_WIDTH   1
#define CFRAME0_REG_STATUS_SECVIO_MASK    0X00000002

#define CFRAME0_REG_STATUS_HC_COMPLETE_SHIFT   0
#define CFRAME0_REG_STATUS_HC_COMPLETE_WIDTH   1
#define CFRAME0_REG_STATUS_HC_COMPLETE_MASK    0X00000001

/**
 * Register: CFRAME0_REG_COE_REPAIR
 */
#define CFRAME0_REG_COE_REPAIR    ( ( CFRAME0_REG_BASEADDR ) + 0X00000250 )

#define CFRAME0_REG_COE_REPAIR_REPAIR_BLK_TYPE_SHIFT   79
#define CFRAME0_REG_COE_REPAIR_REPAIR_BLK_TYPE_WIDTH   3
#define CFRAME0_REG_COE_REPAIR_REPAIR_BLK_TYPE_MASK    0X380000000000000000000

#define CFRAME0_REG_COE_REPAIR_REPAIR_COLUMN_SHIFT   71
#define CFRAME0_REG_COE_REPAIR_REPAIR_COLUMN_WIDTH   8
#define CFRAME0_REG_COE_REPAIR_REPAIR_COLUMN_MASK    0X7F800000000000000000

#define CFRAME0_REG_COE_REPAIR_REPAIR_TILE_SHIFT   64
#define CFRAME0_REG_COE_REPAIR_REPAIR_TILE_WIDTH   7
#define CFRAME0_REG_COE_REPAIR_REPAIR_TILE_MASK    0X7F0000000000000000

#define CFRAME0_REG_COE_REPAIR_REPAIR_VALUE_SHIFT   0
#define CFRAME0_REG_COE_REPAIR_REPAIR_VALUE_WIDTH   64
#define CFRAME0_REG_COE_REPAIR_REPAIR_VALUE_MASK    0XFFFFFFFFFFFFFFFF

#ifdef __cplusplus
}
#endif


#endif /* _CFRAME0_REG_H_ */
