ipipsu_api
XStatus XIpiPsu_CfgInitialize(XIpiPsu *InstancePtr, XIpiPsu_Config *CfgPtr, UINTPTR EffectiveAddress)
Initializes the Instance pointer based on a given Config Pointer.
InstancePtr Pointer to the instance to be worked on CfgPtr Device configuration structure containing required hardware build data EffectiveAddress Base address of the device. If address translation is not utilized, this parameter can be passed in using CfgPtr->Config. BaseAddress to specify the physical base address. XST_SUCCESS if initialization was successful XST_FAILURE in case of failure
References XIpiPsu_Config::BaseAddress, XIpiPsu_Config::BitMask, XIpiPsu_Target::BufferIndex, XIpiPsu_Config::BufferIndex, XIpiPsu::Config, XIpiPsu_Config::IntId, XIpiPsu::IsReady, XIpiPsu_Target::Mask, XIpiPsu_Config::TargetCount, XIpiPsu_Config::TargetList.
Referenced by main.
void XIpiPsu_Reset(XIpiPsu *InstancePtr)
Resets the given IPI register set.
This function can be called to disable the IPIs from all the sources and clear any pending IPIs in status register InstancePtr Pointer to current IPI instance
References XIpiPsu_Config::BaseAddress, XIpiPsu::Config, XIpiPsu::IsReady, XIPIPSU_ALL_MASK, XIPIPSU_IDR_OFFSET, XIPIPSU_ISR_OFFSET, XIpiPsu_WriteReg.
XStatus XIpiPsu_TriggerIpi(XIpiPsu *InstancePtr, u32 DestCpuMask)
Triggers an IPI to a Destination CPU.
InstancePtr Pointer to current IPI instance DestCpuMask Mask of the CPU to which IPI is to be triggered XST_SUCCESS if successful XST_FAILURE if an error occurred
References XIpiPsu_Config::BaseAddress, XIpiPsu::Config, XIpiPsu::IsReady, XIPIPSU_TRIG_OFFSET, XIpiPsu_WriteReg.
XStatus XIpiPsu_PollForAck(const XIpiPsu *InstancePtr, u32 DestCpuMask, u32 TimeOutCount)
Polls for an acknowledgement using Observation Register.
InstancePtr Pointer to current IPI instance DestCpuMask Mask of the destination CPU from which ACK is expected TimeOutCount Count after which the routines returns failure XST_SUCCESS if successful XST_FAILURE if a timeout occurred
References XIpiPsu_Config::BaseAddress, XIpiPsu::Config, XIpiPsu::IsReady, XIPIPSU_OBS_OFFSET, XIpiPsu_ReadReg.
XStatus XIpiPsu_ReadMessage(XIpiPsu *InstancePtr, u32 SrcCpuMask, u32 *MsgPtr, u32 MsgLength, u8 BufferType)
Read an Incoming Message from a Source.
InstancePtr Pointer to current IPI instance SrcCpuMask Device Mask for the CPU which has sent the message MsgPtr Pointer to Buffer to which the read message needs to be stored MsgLength Number of messages (each message is 4bytes) BufferType Type of buffer (XIPIPSU_BUF_TYPE_MSG or XIPIPSU_BUF_TYPE_RESP) XST_SUCCESS if successful XST_FAILURE if an error occurred
References XIpiPsu_Config::BitMask, XIpiPsu::Config, XIpiPsu::IsReady, XIPIPSU_CRC_ERROR, XIPIPSU_CRC_INDEX, XIpiPsu_GetBufferAddress, XIPIPSU_MAX_MSG_LEN, XIPIPSU_W0_TO_W6_SIZE.
Referenced by IpiIntrHandler.
XStatus XIpiPsu_WriteMessage(XIpiPsu *InstancePtr, u32 DestCpuMask, const u32 *MsgPtr, u32 MsgLength, u8 BufferType)
Sends a Message to Destination.
InstancePtr Pointer to current IPI instance DestCpuMask Device Mask for the destination CPU MsgPtr Pointer to Buffer which contains the message to be sent MsgLength Number of messages (each message is 4bytes) BufferType Type of buffer (XIPIPSU_BUF_TYPE_MSG or XIPIPSU_BUF_TYPE_RESP) XST_SUCCESS if successful XST_FAILURE if an error occurred
References XIpiPsu_Config::BitMask, XIpiPsu::Config, XIpiPsu::IsReady, XIPIPSU_CRC_INDEX, XIpiPsu_GetBufferAddress, XIPIPSU_MAX_MSG_LEN, XIPIPSU_W0_TO_W6_SIZE.
Referenced by IpiIntrHandler.
u32* XIpiPsu_GetBufferAddress(XIpiPsu *InstancePtr, u32 SrcCpuMask, u32 DestCpuMask, u32 BufferType)
Gets the Buffer Address for a given pair of CPUs.
InstancePtr Pointer to current IPI instance SrcCpuMask Mask for Source CPU DestCpuMask Mask for Destination CPU BufferType Type of buffer either XIPIPSU_BUF_TYPE_MSG or XIPIPSU_BUF_TYPE_RESP Valid Buffer Address if no error NULL if an error occurs in calculating address
References XIPIPSU_BUF_TYPE_MSG, XIPIPSU_BUF_TYPE_RESP, XIPIPSU_BUFFER_OFFSET_GROUP, XIPIPSU_BUFFER_OFFSET_RESPONSE, XIPIPSU_BUFFER_OFFSET_TARGET, XIpiPsu_GetBufferIndex, XIPIPSU_MAX_BUFF_INDEX, XIPIPSU_MSG_RAM_BASE.
Referenced by XIpiPsu_ReadMessage, XIpiPsu_WriteMessage.
u32 XIpiPsu_GetBufferIndex(const XIpiPsu *InstancePtr, u32 CpuMask)
Gets the Buffer Index for a CPU specified by Mask.
InstancePtr Pointer to current IPI instance CpuMask Mask of the CPU form which Index is required Buffer Index value if CPU Mask is valid XIPIPSU_MAX_BUFF_INDEX+1 if not valid
References XIpiPsu_Target::BufferIndex, XIpiPsu::Config, XIpiPsu_Target::Mask, XIpiPsu_Config::TargetCount, XIpiPsu_Config::TargetList, XIPIPSU_MAX_BUFF_INDEX.
Referenced by XIpiPsu_GetBufferAddress.
XIpiPsu_Config* XIpiPsu_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XIpiPsu_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xipipsu.h for the definition of XIpiPsu_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XIpiPsu_Config::Name, XIpiPsu_ConfigTable.
Referenced by main.
XIPIPSU_HW_H_
< prevent circular inclusions
by using protection macros
XIPIPSU_MSG_RAM_BASE
IPI Message RAM base address.
Referenced by XIpiPsu_GetBufferAddress.
XIPIPSU_MSG_BUF_SIZE
Buffer size for up to 8 messages, each 4-bytes long.
XIPIPSU_MAX_BUFF_INDEX
Maximum Buffer Index.
Referenced by XIpiPsu_GetBufferAddress, XIpiPsu_GetBufferIndex.
XIPIPSU_BUFFER_OFFSET_GROUP
Buffer offset for group.
Referenced by XIpiPsu_GetBufferAddress.
XIPIPSU_BUFFER_OFFSET_TARGET
Buffer offset for target.
Referenced by XIpiPsu_GetBufferAddress.
XIPIPSU_BUFFER_OFFSET_RESPONSE
Buffer offset for response.
Referenced by XIpiPsu_GetBufferAddress.
XIPIPSU_MAX_TARGETS
Maximum number of targets.
XIPIPSU_TRIG_OFFSET
Offset for Trigger register.
Referenced by XIpiPsu_TriggerIpi.
XIPIPSU_OBS_OFFSET
Offset for Observation register.
Referenced by XIpiPsu_PollForAck.
XIPIPSU_ISR_OFFSET
Offset for ISR register.
Referenced by XIpiPsu_Reset.
XIPIPSU_IMR_OFFSET
Offset for Interrupt Mask Register.
XIPIPSU_IER_OFFSET
Offset for Interrupt Enable Register.
XIPIPSU_IDR_OFFSET
Offset for Interrupt Disable Register.
Referenced by XIpiPsu_Reset.
XIPIPSU_ECC_UE_MASK
Uncorrecteble Error mask.
XIPIPSU_ALL_MASK
All valid bit mask.
Referenced by main, XIpiPsu_Reset.