xipipsu.h
XIPIPSU_BUF_TYPE_MSG
Message type buffer.
Referenced by IpiIntrHandler, XIpiPsu_GetBufferAddress.
XIPIPSU_BUF_TYPE_RESP
Response buffer.
Referenced by IpiIntrHandler, XIpiPsu_GetBufferAddress.
XIPIPSU_CRC_INDEX
Index where the CRC is stored.
Referenced by XIpiPsu_ReadMessage, XIpiPsu_WriteMessage.
XIPIPSU_W0_TO_W6_SIZE
Size of the word 0 to word 6.
Referenced by XIpiPsu_ReadMessage, XIpiPsu_WriteMessage.
XIPIPSU_CRC_ERROR
CRC error occurred.
Referenced by XIpiPsu_ReadMessage.
ENABLE_IPI_CRC_VAL
Enable CRC.
XIPIPSU_MAX_MSG_LEN
Maximum message length.
Referenced by XIpiPsu_ReadMessage, XIpiPsu_WriteMessage.
XPAR_XIPIPS_TARGET_PSU_CORTEXA53_0_CH0_MASK
XPAR_XIPIPS_TARGET_PSU_CORTEXA53_1_CH0_MASK
XPAR_XIPIPS_TARGET_PSU_CORTEXA53_2_CH0_MASK
XPAR_XIPIPS_TARGET_PSU_CORTEXA53_3_CH0_MASK
XPAR_XIPIPS_TARGET_PSU_CORTEXR5_0_CH0_MASK
XPAR_XIPIPS_TARGET_PSU_CORTEXR5_1_CH0_MASK
XPAR_XIPIPS_TARGET_PSU_PMU_0_CH0_MASK
XPAR_XIPIPS_TARGET_PSU_PMU_1_CH0_MASK
XPAR_XIPIPS_TARGET_PSU_PMU_2_CH0_MASK
XPAR_XIPIPS_TARGET_PSU_PMU_3_CH0_MASK
XIpiPsu_ReadReg
Reads the register specified by the base address and offset.
BaseAddress Base address of the IPI instance RegOffset Offset of the register relative to base Value of the specified register C-style signature u32 XIpiPsu_ReadReg(UINTPTR BaseAddress, u32 RegOffset)
Referenced by XIpiPsu_PollForAck.
XIpiPsu_WriteReg
Writes a value into a register specified by base address and offset.
BaseAddress Base address of the IPI instance RegOffset Offset of the register relative to base Data 32-bit value that is to be written into the specified register C-style signature void XIpiPsu_WriteReg(UINTPTR BaseAddress, u32 RegOffset, u32 Data)
Referenced by XIpiPsu_Reset, XIpiPsu_TriggerIpi.
XIpiPsu_InterruptEnable
Enable interrupts specified in Mask.
The corresponding interrupt for each bit set to 1 in Mask, will be enabled. InstancePtr Pointer to the instance to be worked on. Mask Contains a bit mask of interrupts to enable. The mask can be formed using a set of bitwise or'd values of individual CPU masks C-style signature void XIpiPsu_InterruptEnable(XIpiPsu *InstancePtr, u32 Mask)
Referenced by main.
XIpiPsu_InterruptDisable
Disable interrupts specified in Mask.
The corresponding interrupt for each bit set to 1 in Mask, will be disabled. InstancePtr Pointer to the instance to be worked on. Mask Contains a bit mask of interrupts to disable. The mask can be formed using a set of bitwise or'd values of individual CPU masks C-style signature void XIpiPsu_InterruptDisable(XIpiPsu *InstancePtr, u32 Mask)
XIpiPsu_GetInterruptStatus
Gets the STATUS REGISTER of the current IPI instance.
InstancePtr Pointer to the instance to be worked on. Returns the Interrupt Status register(ISR) contents User needs to parse this 32-bit value to check the source CPU C-style signature u32 XIpiPsu_GetInterruptStatus(XIpiPsu *InstancePtr)
Referenced by IpiIntrHandler.
XIpiPsu_ClearInterruptStatus
Clears the STATUS REGISTER of the current IPI instance.
The corresponding interrupt status for each bit set to 1 in Mask is cleared. InstancePtr Pointer to the instance to be worked on. Mask Mask corresponding to the source CPU* This function should be used after handling the IPI. Clearing the status will automatically clear the corresponding bit in OBSERVATION register of Source CPU C-style signature void XIpiPsu_ClearInterruptStatus(XIpiPsu *InstancePtr, u32 Mask)
Referenced by IpiIntrHandler, main.
XIpiPsu_GetObsStatus
Gets the OBSERVATION REGISTER of the current IPI instance.
InstancePtr Pointer to the instance to be worked on. Returns the Observation register(OBS) contents User needs to parse this 32-bit value to check the status of individual CPUs C-style signature u32 XIpiPsu_GetObsStatus(XIpiPsu *InstancePtr)
XIpiPsu_Config XIpiPsu_ConfigTable[][]
The IPIPSU configuration table, sized by the number of instances defined in xparameters.h.
Referenced by XIpiPsu_LookupConfig.
XIpiPsu_Config* XIpiPsu_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XIpiPsu_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xipipsu.h for the definition of XIpiPsu_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XIpiPsu_Config::Name, XIpiPsu_ConfigTable.
Referenced by main.
XStatus XIpiPsu_CfgInitialize(XIpiPsu *InstancePtr, XIpiPsu_Config *CfgPtr, UINTPTR EffectiveAddress)
Initializes the Instance pointer based on a given Config Pointer.
InstancePtr Pointer to the instance to be worked on CfgPtr Device configuration structure containing required hardware build data EffectiveAddress Base address of the device. If address translation is not utilized, this parameter can be passed in using CfgPtr->Config. BaseAddress to specify the physical base address. XST_SUCCESS if initialization was successful XST_FAILURE in case of failure
References XIpiPsu_Config::BaseAddress, XIpiPsu_Config::BitMask, XIpiPsu_Target::BufferIndex, XIpiPsu_Config::BufferIndex, XIpiPsu::Config, XIpiPsu_Config::IntId, XIpiPsu::IsReady, XIpiPsu_Target::Mask, XIpiPsu_Config::TargetCount, XIpiPsu_Config::TargetList.
Referenced by main.
void XIpiPsu_Reset(XIpiPsu *InstancePtr)
Resets the given IPI register set.
This function can be called to disable the IPIs from all the sources and clear any pending IPIs in status register InstancePtr Pointer to current IPI instance
References XIpiPsu_Config::BaseAddress, XIpiPsu::Config, XIpiPsu::IsReady, XIPIPSU_ALL_MASK, XIPIPSU_IDR_OFFSET, XIPIPSU_ISR_OFFSET, XIpiPsu_WriteReg.
XStatus XIpiPsu_TriggerIpi(XIpiPsu *InstancePtr, u32 DestCpuMask)
Triggers an IPI to a Destination CPU.
InstancePtr Pointer to current IPI instance DestCpuMask Mask of the CPU to which IPI is to be triggered XST_SUCCESS if successful XST_FAILURE if an error occurred
References XIpiPsu_Config::BaseAddress, XIpiPsu::Config, XIpiPsu::IsReady, XIPIPSU_TRIG_OFFSET, XIpiPsu_WriteReg.
XStatus XIpiPsu_PollForAck(const XIpiPsu *InstancePtr, u32 DestCpuMask, u32 TimeOutCount)
Polls for an acknowledgement using Observation Register.
InstancePtr Pointer to current IPI instance DestCpuMask Mask of the destination CPU from which ACK is expected TimeOutCount Count after which the routines returns failure XST_SUCCESS if successful XST_FAILURE if a timeout occurred
References XIpiPsu_Config::BaseAddress, XIpiPsu::Config, XIpiPsu::IsReady, XIPIPSU_OBS_OFFSET, XIpiPsu_ReadReg.
XStatus XIpiPsu_ReadMessage(XIpiPsu *InstancePtr, u32 SrcCpuMask, u32 *MsgPtr, u32 MsgLength, u8 BufferType)
Read an Incoming Message from a Source.
InstancePtr Pointer to current IPI instance SrcCpuMask Device Mask for the CPU which has sent the message MsgPtr Pointer to Buffer to which the read message needs to be stored MsgLength Number of messages (each message is 4bytes) BufferType Type of buffer (XIPIPSU_BUF_TYPE_MSG or XIPIPSU_BUF_TYPE_RESP) XST_SUCCESS if successful XST_FAILURE if an error occurred
References XIpiPsu_Config::BitMask, XIpiPsu::Config, XIpiPsu::IsReady, XIPIPSU_CRC_ERROR, XIPIPSU_CRC_INDEX, XIpiPsu_GetBufferAddress, XIPIPSU_MAX_MSG_LEN, XIPIPSU_W0_TO_W6_SIZE.
Referenced by IpiIntrHandler.
XStatus XIpiPsu_WriteMessage(XIpiPsu *InstancePtr, u32 DestCpuMask, const u32 *MsgPtr, u32 MsgLength, u8 BufferType)
Sends a Message to Destination.
InstancePtr Pointer to current IPI instance DestCpuMask Device Mask for the destination CPU MsgPtr Pointer to Buffer which contains the message to be sent MsgLength Number of messages (each message is 4bytes) BufferType Type of buffer (XIPIPSU_BUF_TYPE_MSG or XIPIPSU_BUF_TYPE_RESP) XST_SUCCESS if successful XST_FAILURE if an error occurred
References XIpiPsu_Config::BitMask, XIpiPsu::Config, XIpiPsu::IsReady, XIPIPSU_CRC_INDEX, XIpiPsu_GetBufferAddress, XIPIPSU_MAX_MSG_LEN, XIPIPSU_W0_TO_W6_SIZE.
Referenced by IpiIntrHandler.
void XIpiPsu_SetConfigTable(u32 DeviceId, XIpiPsu_Config *ConfigTblPtr)