xipipsu.c
XStatus XIpiPsu_CfgInitialize(XIpiPsu *InstancePtr, XIpiPsu_Config *CfgPtr, UINTPTR EffectiveAddress)
Initializes the Instance pointer based on a given Config Pointer.
InstancePtr Pointer to the instance to be worked on CfgPtr Device configuration structure containing required hardware build data EffectiveAddress Base address of the device. If address translation is not utilized, this parameter can be passed in using CfgPtr->Config. BaseAddress to specify the physical base address. XST_SUCCESS if initialization was successful XST_FAILURE in case of failure
References XIpiPsu_Config::BaseAddress, XIpiPsu_Config::BitMask, XIpiPsu_Target::BufferIndex, XIpiPsu_Config::BufferIndex, XIpiPsu::Config, XIpiPsu_Config::IntId, XIpiPsu::IsReady, XIpiPsu_Target::Mask, XIpiPsu_Config::TargetCount, XIpiPsu_Config::TargetList.
Referenced by main.
void XIpiPsu_Reset(XIpiPsu *InstancePtr)
Resets the given IPI register set.
This function can be called to disable the IPIs from all the sources and clear any pending IPIs in status register InstancePtr Pointer to current IPI instance
References XIpiPsu_Config::BaseAddress, XIpiPsu::Config, XIpiPsu::IsReady, XIPIPSU_ALL_MASK, XIPIPSU_IDR_OFFSET, XIPIPSU_ISR_OFFSET, XIpiPsu_WriteReg.
XStatus XIpiPsu_TriggerIpi(XIpiPsu *InstancePtr, u32 DestCpuMask)
Triggers an IPI to a Destination CPU.
InstancePtr Pointer to current IPI instance DestCpuMask Mask of the CPU to which IPI is to be triggered XST_SUCCESS if successful XST_FAILURE if an error occurred
References XIpiPsu_Config::BaseAddress, XIpiPsu::Config, XIpiPsu::IsReady, XIPIPSU_TRIG_OFFSET, XIpiPsu_WriteReg.
XStatus XIpiPsu_PollForAck(const XIpiPsu *InstancePtr, u32 DestCpuMask, u32 TimeOutCount)
Polls for an acknowledgement using Observation Register.
InstancePtr Pointer to current IPI instance DestCpuMask Mask of the destination CPU from which ACK is expected TimeOutCount Count after which the routines returns failure XST_SUCCESS if successful XST_FAILURE if a timeout occurred
References XIpiPsu_Config::BaseAddress, XIpiPsu::Config, XIpiPsu::IsReady, XIPIPSU_OBS_OFFSET, XIpiPsu_ReadReg.
XStatus XIpiPsu_ReadMessage(XIpiPsu *InstancePtr, u32 SrcCpuMask, u32 *MsgPtr, u32 MsgLength, u8 BufferType)
Read an Incoming Message from a Source.
InstancePtr Pointer to current IPI instance SrcCpuMask Device Mask for the CPU which has sent the message MsgPtr Pointer to Buffer to which the read message needs to be stored MsgLength Number of messages (each message is 4bytes) BufferType Type of buffer (XIPIPSU_BUF_TYPE_MSG or XIPIPSU_BUF_TYPE_RESP) XST_SUCCESS if successful XST_FAILURE if an error occurred
References XIpiPsu_Config::BitMask, XIpiPsu::Config, XIpiPsu::IsReady, XIPIPSU_CRC_ERROR, XIPIPSU_CRC_INDEX, XIpiPsu_GetBufferAddress, XIPIPSU_MAX_MSG_LEN, XIPIPSU_W0_TO_W6_SIZE.
Referenced by IpiIntrHandler.
XStatus XIpiPsu_WriteMessage(XIpiPsu *InstancePtr, u32 DestCpuMask, const u32 *MsgPtr, u32 MsgLength, u8 BufferType)
Sends a Message to Destination.
InstancePtr Pointer to current IPI instance DestCpuMask Device Mask for the destination CPU MsgPtr Pointer to Buffer which contains the message to be sent MsgLength Number of messages (each message is 4bytes) BufferType Type of buffer (XIPIPSU_BUF_TYPE_MSG or XIPIPSU_BUF_TYPE_RESP) XST_SUCCESS if successful XST_FAILURE if an error occurred
References XIpiPsu_Config::BitMask, XIpiPsu::Config, XIpiPsu::IsReady, XIPIPSU_CRC_INDEX, XIpiPsu_GetBufferAddress, XIPIPSU_MAX_MSG_LEN, XIPIPSU_W0_TO_W6_SIZE.
Referenced by IpiIntrHandler.