dfemix
XDfeMix_StateId
Not ready state.
typedef __u32 u32
typedef __u16 u16
typedef __u8 u8
typedef __s32 s32
typedef __s16 s16
typedef __u64 u64
typedef __s64 s64
typedef __s8 s8
typedef enum XDfeMix_StateId XDfeMix_StateId
typedef XDfeMix_Status XDfeMix_InterruptMask
XDfeMix * XDfeMix_InstanceInit(const char *DeviceNodeName)
API initialises one instance of a Mixer driver.
Traverses "/sys/bus/platform/device" directory (in Linux), to find registered XDfeMix device with the name DeviceNodeName. The first available slot in the instances array XDfeMix_Mixer[] will be taken as a DeviceNodeName object. On success it moves the state machine to a Ready state, while on failure stays in a Not Ready state. DeviceNodeName Device node name. Pointer to the instance if successful.NULL on error.
References XDfeMix::Device, XDfeMix::NodeName, XDfeMix::StateId, XDFEMIX_NODE_NAME_MAX_LENGTH, XDFEMIX_STATE_NOT_READY, XDFEMIX_STATE_READY, XST_FAILURE, XST_SUCCESS.
Referenced by XDfeMix_AddCCExample, XDfeMix_MultiAddCCExample, XDfeMix_SelfTestExample.
void XDfeMix_InstanceClose(XDfeMix *InstancePtr)
API closes the instance of a Mixer driver and moves the state machine to a Not Ready state.
InstancePtr Pointer to the Mixer instance.
References XDfeMix::Device, XDfeMix::NodeName, XDfeMix::StateId, XDFEMIX_STATE_NOT_READY.
Referenced by XDfeMix_AddCCExample, XDfeMix_MultiAddCCExample, XDfeMix_SelfTestExample.
void XDfeMix_Reset(XDfeMix *InstancePtr)
Resets Mixer and puts block into a reset state.
InstancePtr Pointer to the Mixer instance.
References XDfeMix::StateId, XDFEMIX_STATE_NOT_READY, XDFEMIX_STATE_RESET.
Referenced by XDfeMix_AddCCExample, XDfeMix_MultiAddCCExample, XDfeMix_SelfTestExample.
void XDfeMix_Configure(XDfeMix *InstancePtr, XDfeMix_Cfg *Cfg)
Reads configuration from device tree/xparameters.h and IP registers.
Removes S/W reset and moves the state machine to a Configured state. InstancePtr Pointer to the Mixer instance. Cfg Configuration data container.
References XDfeMix_ModelParameters::AntennaInterleave, XDfeMix_Config::AntennaInterleave, XDfeMix::Config, XDfeMix_ModelParameters::DataIWidth, XDfeMix_Config::DataIWidth, XDfeMix_ModelParameters::DataOWidth, XDfeMix_Config::DataOWidth, XDfeMix_ModelParameters::Lanes, XDfeMix_Config::Lanes, XDfeMix_Version::Major, XDfeMix_ModelParameters::MaxUseableCcids, XDfeMix_Config::MaxUseableCcids, XDfeMix_Version::Minor, XDfeMix_ModelParameters::MixerCps, XDfeMix_Config::MixerCps, XDfeMix_ModelParameters::Mode, XDfeMix_Config::Mode, XDfeMix_Cfg::ModelParams, XDfeMix_ModelParameters::NumAntenna, XDfeMix_Config::NumAntenna, XDfeMix_ModelParameters::NumAuxiliary, XDfeMix_Config::NumAuxiliary, XDfeMix_Version::Patch, XDfeMix_Version::Revision, XDfeMix::StateId, XDfeMix_ModelParameters::TUserWidth, XDfeMix_Config::TUserWidth, XDfeMix_Cfg::Version, XDFEMIX_STATE_CONFIGURED, XDFEMIX_STATE_RESET.
Referenced by XDfeMix_AddCCExample, XDfeMix_MultiAddCCExample, XDfeMix_SelfTestExample.
void XDfeMix_Initialize(XDfeMix *InstancePtr, XDfeMix_Init *Init)
DFE Mixer driver one time initialisation which sets registers to initialisation values, moves the state machine to Initialised state and in switchable mode sets Uplink registers to initialisation value.
InstancePtr Pointer to the Mixer instance. Init Initialisation data container.
References XDfeMix::Config, XDfeMix_CCSequence::Length, XDfeMix_Config::Mode, XDfeMix::NotUsedCCID, XDfeMix::NotUsedCCID_UL, XDfeMix_Init::Sequence, XDfeMix::SequenceLength, XDfeMix::StateId, XDfeMix_Init::TuserSelect, XDfeMix_SetRegBank, XDFEMIX_STATE_CONFIGURED, XDFEMIX_STATE_INITIALISED.
Referenced by XDfeMix_AddCCExample, XDfeMix_MultiAddCCExample, XDfeMix_SelfTestExample.
void XDfeMix_Activate(XDfeMix *InstancePtr, bool EnableLowPower)
Enables triggers and moves the state machine to an Activated state.
InstancePtr Pointer to the Mixer instance. EnableLowPower Flag indicating low power.
References XDfeMix::Config, XDfeMix_Config::Mode, XDfeMix::StateId, XDFEMIX_STATE_INITIALISED, XDFEMIX_STATE_OPERATIONAL.
Referenced by XDfeMix_AddCCExample, XDfeMix_MultiAddCCExample, XDfeMix_SelfTestExample.
void XDfeMix_Deactivate(XDfeMix *InstancePtr)
Deactivates triggers and moves the state machine to Initialised state.
InstancePtr Pointer to the Mixer instance.
References XDfeMix::Config, XDfeMix_Config::Mode, XDfeMix::StateId, XDFEMIX_STATE_INITIALISED, XDFEMIX_STATE_OPERATIONAL.
Referenced by XDfeMix_AddCCExample, XDfeMix_MultiAddCCExample, XDfeMix_SelfTestExample.
XDfeMix_StateId XDfeMix_GetStateID(XDfeMix *InstancePtr)
Gets a state machine state id.
InstancePtr Pointer to the Mixer instance. State machine StateID
References XDfeMix::StateId.
void XDfeMix_GetCurrentCCCfg(const XDfeMix *InstancePtr, XDfeMix_CCCfg *CurrCCCfg)
Returns the current CC and NCO configurations.
Not used slot ID in a sequence (Sequence.CCID[Index]) are represented as (-1), not the value in registers. InstancePtr Pointer to the Mixer instance. CurrCCCfg CC configuration container.
References XDfeMix_CCSequence::NotUsedCCID, XDfeMix::NotUsedCCID, XDfeMix_CCCfg::Sequence.
Referenced by XDfeMix_AddCC, XDfeMix_MoveCC, XDfeMix_MultiAddCCExample, XDfeMix_RemoveCC, XDfeMix_SetAntennaGain, XDfeMix_UpdateAntennaCfg, XDfeMix_UpdateCC.
void XDfeMix_GetCurrentCCCfgSwitchable(const XDfeMix *InstancePtr, XDfeMix_CCCfg *CCCfgDownlink, XDfeMix_CCCfg *CCCfgUplink)
Returns the current CC and NCO configuration for Downlink and Uplink in switchable mode.
Not used slot ID in a sequence (Sequence.CCID[Index]) are represented as (-1), not the value in registers. InstancePtr Pointer to the Mixer instance. CCCfgDownlink Downlink CC configuration container. CCCfgUplink Uplink CC configuration container.
References XDfeMix::Config, XDfeMix_Config::Mode, XDfeMix_CCSequence::NotUsedCCID, XDfeMix::NotUsedCCID, XDfeMix::NotUsedCCID_UL, XDfeMix_CCCfg::Sequence, XDfeMix_SetRegBank.
Referenced by XDfeMix_SetAntennaGain, XDfeMix_UpdateAntennaCfg.
void XDfeMix_GetEmptyCCCfg(const XDfeMix *InstancePtr, XDfeMix_CCCfg *CCCfg)
Returns configuration structure CCCfg with CCCfg->Sequence.Length value set in XDfeMix_Configure(), array CCCfg->Sequence.CCID[] members are set to not used value (-1) and the other CCCfg members are set to 0.
InstancePtr Pointer to the Mixer instance. CCCfg CC configuration container.
References XDfeMix_CCSequence::CCID, XDfeMix_CCSequence::Length, XDfeMix_CCCfg::Sequence, XDfeMix::SequenceLength, XDFEMIX_CC_NUM.
void XDfeMix_GetCarrierCfgAndNCO(const XDfeMix *InstancePtr, XDfeMix_CCCfg *CCCfg, s32 CCID, u32 *CCSeqBitmap, XDfeMix_CarrierCfg *CarrierCfg, XDfeMix_NCO *NCO)
Returns the current CC sequence bitmap, CCID carrier configuration and NCO configuration.
InstancePtr Pointer to the Mixer instance. CCCfg Component carrier (CC) configuration container. CCID Channel ID for which configuration parameters are returned, range [0-15]. CCSeqBitmap CC slot position container. CarrierCfg CC configuration container. NCO NCO configuration container.
References XDfeMix_InternalDUCDDCCfg::CCGain, XDfeMix_DUCDDCCfg::CCGain, XDfeMix_CCSequence::CCID, XDfeMix_CarrierCfg::DUCDDCCfg, XDfeMix_CCCfg::DUCDDCCfg, XDfeMix_CCSequence::Length, XDfeMix_CCCfg::NCO, XDfeMix_InternalDUCDDCCfg::NCOIdx, XDfeMix_DUCDDCCfg::NCOIdx, XDfeMix_CCCfg::Sequence.
void XDfeMix_SetAntennaCfgInCCCfg(const XDfeMix *InstancePtr, XDfeMix_CCCfg *CCCfg, XDfeMix_AntennaCfg *AntennaCfg)
Set antenna configuration in CC configuration container.
InstancePtr Pointer to the Mixer instance. CCCfg CC configuration container. AntennaCfg Structure containing the array of all antenna gain configurations.
References XDfeMix_CCCfg::AntennaCfg.
u32 XDfeMix_AddCCtoCCCfg(XDfeMix *InstancePtr, XDfeMix_CCCfg *CCCfg, s32 CCID, u32 CCSeqBitmap, const XDfeMix_CarrierCfg *CarrierCfg, const XDfeMix_NCO *NCO)
Adds specified CCID, with specified configuration, to a local CC configuration structure.
If there is insufficient capacity for the new CC the function will return an error. Initiates CC update (enable CCUpdate trigger TUSER Single Shot).The CCID sequence register values 0-15 can define the slot as either used or not used. That's why the register values are translated into CCCfg.Sequence The translation is: Sequence.CCID[i] = -1 - if [i] is unused slotSequence.CCID[i] = CCID - if [i] is used slota returned Sequence.Length = length in register + 1 When the number of usable CC's is greater than four there is an additional restriction on the CC sequence as described in "Component Carrier Sequencing". This will be verified by the API to ensure a violation does not occur. InstancePtr Pointer to the Mixer instance. CCCfg Component carrier (CC) configuration container. CCID Channel ID to be added to configuration, range [0-15]. CCSeqBitmap CC slot position container. CarrierCfg CC configuration container. NCO NCO configuration container. XST_SUCCESS if successful.XST_FAILURE if error occurs.
References XDfeMix_CarrierCfg::DUCDDCCfg, XDfeMix_CCCfg::DUCDDCCfg, XDfeMix_CCCfg::NCO, XDfeMix_InternalDUCDDCCfg::NCOIdx, XDfeMix_DUCDDCCfg::NCOIdx, XDfeMix_CCCfg::Sequence, XST_FAILURE, XST_SUCCESS.
Referenced by XDfeMix_MultiAddCCExample.
void XDfeMix_RemoveCCfromCCCfg(XDfeMix *InstancePtr, XDfeMix_CCCfg *CCCfg, s32 CCID)
Removes specified CCID from a local CC configuration structure and the slots in the sequence for that CCID are set to -1.
InstancePtr Pointer to the Mixer instance. CCCfg Component carrier (CC) configuration container. CCID Channel ID to be removed, range [0-15]. For a sequence conversion see XDfeMix_AddCCtoCCCfg() comment.
References XDfeMix_CCCfg::DUCDDCCfg, XDfeMix_InternalDUCDDCCfg::Rate, XDfeMix_CCCfg::Sequence.
void XDfeMix_AddAuxNCOtoCCCfg(XDfeMix *InstancePtr, XDfeMix_CCCfg *CCCfg, const s32 AuxId, const XDfeMix_NCO *NCO, const XDfeMix_AuxiliaryCfg *AuxCfg)
Adds specified auxiliary NCO, with specified configuration, to a local CCCfg.
InstancePtr Pointer to the Mixer instance. CCCfg CC configuration container. AuxId Auxiliary NCO ID to be enabled, range [0-3]. NCO NCO configuration container. AuxCfg Auxiliary NCO configuration container.
References XDfeMix_CCCfg::AuxiliaryCfg, XDfeMix_CCCfg::NCO.
void XDfeMix_RemoveAuxNCOfromCCCfg(XDfeMix *InstancePtr, XDfeMix_CCCfg *CCCfg, const s32 AuxId)
Disables specified auxiliary NCO configuration structure.
InstancePtr Pointer to the Mixer instance. CCCfg Component carrier (CC) configuration container. AuxId Auxiliary NCO ID to be disabled, range [0-3]. When MAX_USABLE_CCIDS > 4 see XDfeMix_AddCCtoCCCfg().
References XDfeMix_CCCfg::AuxiliaryCfg, XDfeMix_AuxiliaryCfg::Enable.
u32 XDfeMix_UpdateCCinCCCfg(XDfeMix *InstancePtr, XDfeMix_CCCfg *CCCfg, s32 CCID, const XDfeMix_CarrierCfg *CarrierCfg)
Updates specified CCID, with specified configuration to a local CC configuration structure.
An error is generated if the NCOidx selected is already used. InstancePtr Pointer to the Mixer instance. CCCfg Component carrier (CC) configuration container. CCID Channel ID to be updated, range [0-15]. CarrierCfg CC configuration container. XST_SUCCESS if successful.XST_FAILURE if error occurs. When MAX_USABLE_CCIDS > 4 see XDfeMix_AddCCtoCCCfg().
References XDfeMix_CarrierCfg::DUCDDCCfg, XDfeMix_DUCDDCCfg::NCOIdx, XST_FAILURE, XST_SUCCESS.
u32 XDfeMix_SetNextCCCfgAndTrigger(XDfeMix *InstancePtr, const XDfeMix_CCCfg *CCCfg)
Writes local CC configuration to the shadow (NEXT) registers and triggers copying from shadow to operational registers.
InstancePtr Pointer to the Mixer instance. CCCfg CC configuration container. XST_SUCCESS if successful.XST_FAILURE if error occurs.
References XDfeMix_CCSequence::NotUsedCCID, XDfeMix::NotUsedCCID, XDfeMix_CCCfg::Sequence, XST_FAILURE, XST_SUCCESS.
Referenced by XDfeMix_MultiAddCCExample.
u32 XDfeMix_SetNextCCCfgAndTriggerSwitchable(XDfeMix *InstancePtr, XDfeMix_CCCfg *CCCfgDownlink, XDfeMix_CCCfg *CCCfgUplink)
Writes local CC configuration to the shadow (NEXT) registers and triggers copying from shadow to operational (CURRENT) registers for both Downlink and Upling in switchable mode.
InstancePtr Pointer to the Ccf instance. CCCfgDownlink Downlink CC configuration container. CCCfgUplink Uplink CC configuration container. XST_SUCCESS if successful.XST_FAILURE if error occurs.
References XDfeMix::Config, XDfeMix_Config::Mode, XDfeMix_CCSequence::NotUsedCCID, XDfeMix::NotUsedCCID, XDfeMix::NotUsedCCID_UL, XDfeMix_CCCfg::Sequence, XDfeMix_SetRegBank, XST_FAILURE, XST_SUCCESS.
Referenced by XDfeMix_SetAntennaGain, XDfeMix_UpdateAntennaCfg.
u32 XDfeMix_AddCC(XDfeMix *InstancePtr, s32 CCID, u32 CCSeqBitmap, const XDfeMix_CarrierCfg *CarrierCfg, const XDfeMix_NCO *NCO)
Adds specified CCID, with specified configuration.
If there is insufficient capacity for the new CC the function will return an error. Initiates CC update (enable CCUpdate trigger TUSER Single Shot). InstancePtr Pointer to the Mixer instance. CCID Channel ID, range [0-15]. CCSeqBitmap - up to 16 defined slots into which a CC can be allocated. The number of slots can be from 1 to 16 depending on system initialization. The number of slots is defined by the "sequence length" parameter which is provided during initialization. The Bit offset within the CCSeqBitmap indicates the equivalent Slot number to allocate. e.g. 0x0003 means the caller wants the passed component carrier (CC) to be allocated to slots 0 and 1. CarrierCfg CC configuration container. NCO NCO configuration container. XST_SUCCESS if successful.XST_FAILURE if error occurs. Clear event status with XDfeMix_ClearEventStatus() before running this API. When MAX_USABLE_CCIDS > 4 see XDfeMix_AddCCtoCCCfg().: This API is deprecated in the release 2023.2. The functionality of this API can be reproduced with the following API sequence: XDfeMix_GetCurrentCCCfg(InstancePtr, CCCfg); XDfeMix_AddCCtoCCCfg(InstancePtr, CCCfg, CCID, CCSeqBitmap, CarrierCfg, NCO); XDfeMix_SetNextCCCfgAndTrigger(InstancePtr, CCCfg);
References XDfeMix_DUCDDCCfg::CCGain, XDfeMix_CarrierCfg::DUCDDCCfg, XDfeMix_NCO::FrequencyCfg, XDfeMix_NCO::NCOGain, XDfeMix_DUCDDCCfg::NCOIdx, XDfeMix_CCSequence::NotUsedCCID, XDfeMix::NotUsedCCID, XDfeMix_NCO::PhaseCfg, XDfeMix_CCCfg::Sequence, XDfeMix::StateId, XDFEMIX_CC_GAIN_MAX, XDfeMix_GetCurrentCCCfg, XDFEMIX_STATE_OPERATIONAL, XST_FAILURE, XST_SUCCESS.
Referenced by XDfeMix_AddCCExample.
u32 XDfeMix_RemoveCC(XDfeMix *InstancePtr, s32 CCID)
Removes specified CCID.
Initiates CC update (enable CCUpdate trigger TUSER Single Shot). InstancePtr Pointer to the Mixer instance. CCID Channel ID, range [0-15]. XST_SUCCESS if successful.XST_FAILURE if error occurs. Clear event status with XDfeMix_ClearEventStatus() before running this API.: This API is deprecated in the release 2023.2. The functionality of this API can be reproduced with the following API sequence: XDfeMix_GetCurrentCCCfg(InstancePtr, CCCfg); XDfeMix_RemoveCCfromCCCfg(InstancePtr, CCCfg, CCID); XDfeMix_SetNextCCCfgAndTrigger(InstancePtr, CCCfg);
References XDfeMix_CCCfg::DUCDDCCfg, XDfeMix_CCSequence::NotUsedCCID, XDfeMix::NotUsedCCID, XDfeMix_InternalDUCDDCCfg::Rate, XDfeMix_CCCfg::Sequence, XDfeMix::StateId, XDfeMix_GetCurrentCCCfg, XDFEMIX_STATE_OPERATIONAL, XST_FAILURE, XST_SUCCESS.
u32 XDfeMix_MoveCC(XDfeMix *InstancePtr, s32 CCID, u32 Rate, u32 FromNCO, u32 ToNCO)
Moves specified CCID from one NCO to another aligning phase to make it transparent.
Initiates CC update (enable CCUpdate trigger TUSER Single Shot). InstancePtr Pointer to the Mixer instance. CCID Channel ID, range [0-15]. Rate NCO rate value [1,2,4]. FromNCO NCO value moving from, range [0-7]. ToNCO NCO value moving to, range [0-7]. XST_SUCCESS if successful.XST_FAILURE if error occurs. Clear event status with XDfeMix_ClearEventStatus() before running this API. When MAX_USABLE_CCIDS > 4 see XDfeMix_AddCCtoCCCfg(). : This API is deprecated in the release 2023.2. The functionality of this API can be reproduced with the following API sequence: XDfeMix_GetCurrentCCCfg(InstancePtr, CCCfg); XDfeMix_UpdateCCinCCCfg(); XDfeMix_SetNextCCCfgAndTrigger(InstancePtr, CCCfg); This will allow for the CCID to move from one NCO to another but will not allow for phase alignment.
References XDfeMix::Config, XDfeMix_Config::MaxUseableCcids, XDfeMix_CCSequence::NotUsedCCID, XDfeMix::NotUsedCCID, XDfeMix_CCCfg::Sequence, XDfeMix::StateId, XDfeMix_GetCurrentCCCfg, XDFEMIX_STATE_OPERATIONAL, XST_FAILURE, XST_SUCCESS.
u32 XDfeMix_UpdateCC(XDfeMix *InstancePtr, s32 CCID, const XDfeMix_CarrierCfg *CarrierCfg)
Updates specified CCID, with a configuration defined in CarrierCfg structure.
InstancePtr Pointer to the Mixer instance. CCID Channel ID, range [0-15]. CarrierCfg CC configuration container. XST_SUCCESS if successful.XST_FAILURE if error occurs. Clear event status with XDfeMix_ClearEventStatus() before running this API. When MAX_USABLE_CCIDS > 4 see XDfeMix_AddCCtoCCCfg().: This API is deprecated in the release 2023.2. The functionality of this API can be reproduced with the following API sequence: XDfeMix_GetCurrentCCCfg(InstancePtr, CCCfg); XDfeMix_UpdateCCinCCCfg(InstancePtr, CCCfg, CCID, CarrierCfg); XDfeMix_SetNextCCCfgAndTrigger(InstancePtr, CCCfg);
References XDfeMix_InternalDUCDDCCfg::CCGain, XDfeMix_DUCDDCCfg::CCGain, XDfeMix_CarrierCfg::DUCDDCCfg, XDfeMix_CCCfg::DUCDDCCfg, XDfeMix_InternalDUCDDCCfg::NCOIdx, XDfeMix_DUCDDCCfg::NCOIdx, XDfeMix_CCSequence::NotUsedCCID, XDfeMix::NotUsedCCID, XDfeMix_CCCfg::Sequence, XDfeMix::StateId, XDfeMix_GetCurrentCCCfg, XDFEMIX_STATE_OPERATIONAL, XST_FAILURE, XST_SUCCESS.
u32 XDfeMix_SetAntennaGain(XDfeMix *InstancePtr, u32 AntennaId, u32 AntennaGain)
Sets antenna gain.
Initiates CC update (enable CCUpdate trigger TUSER Single Shot). Applies gain to downlink only in switchable mode. InstancePtr Pointer to the Mixer instance. AntennaId Antenna ID, range [0-7]. AntennaGain Antenna gain, 0 for -6dB and 1 for 0dB. XST_SUCCESS if successful.XST_FAILURE if error occurs. Clear event status with XDfeMix_ClearEventStatus() before running this API.
References XDfeMix_CCCfg::AntennaCfg, XDfeMix::Config, XDfeMix_AntennaCfg::Gain, XDfeMix_Config::Mode, XDFEMIX_ANT_NUM_MAX, XDfeMix_GetCurrentCCCfg, XDfeMix_GetCurrentCCCfgSwitchable, XDfeMix_SetNextCCCfgAndTriggerSwitchable.
Referenced by XDfeMix_AddCCExample, XDfeMix_MultiAddCCExample.
u32 XDfeMix_UpdateAntennaCfg(XDfeMix *InstancePtr, XDfeMix_AntennaCfg *AntennaCfg)
Updates antenna configuration of all antennas.
Applies gain to downlink only in switchable mode. InstancePtr Pointer to the Mixer instance. AntennaCfg Structure containing the array of all antenna gain configurations. XST_SUCCESS if successful.XST_FAILURE if error occurs. Clear event status with XDfeMix_ClearEventStatus() before running this API.
References XDfeMix_CCCfg::AntennaCfg, XDfeMix::Config, XDfeMix_Config::Mode, XDfeMix_GetCurrentCCCfg, XDfeMix_GetCurrentCCCfgSwitchable, XDfeMix_SetNextCCCfgAndTriggerSwitchable.
void XDfeMix_GetTriggersCfg(const XDfeMix *InstancePtr, XDfeMix_TriggerCfg *TriggerCfg)
Returns current trigger configuration.
In switchable mode ignores LOW_POWER trigger as it is not used, instead reads SWITCH trigger configuration. InstancePtr Pointer to the Mixer instance. TriggerCfg Trigger configuration container.
References XDfeMix_TriggerCfg::Activate, XDfeMix_TriggerCfg::CCUpdate, XDfeMix::Config, XDfeMix_TriggerCfg::LowPower, XDfeMix_Trigger::Mode, XDfeMix_Config::Mode, XDfeMix::StateId, XDfeMix_Trigger::StateOutput, XDfeMix_TriggerCfg::Switch, XDfeMix_Trigger::TriggerEnable, XDfeMix_Trigger::TUSERBit, XDfeMix_Trigger::TuserEdgeLevel, XDFEMIX_STATE_NOT_READY.
void XDfeMix_SetTriggersCfg(const XDfeMix *InstancePtr, XDfeMix_TriggerCfg *TriggerCfg)
Sets trigger configuration.
In switchable mode ignores LOW_POWER trigger as it is not used, instead sets SWITCH trigger configuration. InstancePtr Pointer to the Mixer instance. TriggerCfg Trigger configuration container.
References XDfeMix_TriggerCfg::Activate, XDfeMix_TriggerCfg::CCUpdate, XDfeMix::Config, XDfeMix_TriggerCfg::LowPower, XDfeMix_Trigger::Mode, XDfeMix_Config::Mode, XDfeMix::StateId, XDfeMix_Trigger::StateOutput, XDfeMix_TriggerCfg::Switch, XDfeMix_Trigger::TriggerEnable, XDfeMix_Trigger::TUSERBit, XDfeMix_Trigger::TuserEdgeLevel, XDFEMIX_STATE_INITIALISED.
Referenced by XDfeMix_AddCCExample, XDfeMix_MultiAddCCExample.
void XDfeMix_GetDUCDDCStatus(const XDfeMix *InstancePtr, XDfeMix_DUCDDCStatus *DUCDDCStatus)
Gets DUC/DDC overflow status.
InstancePtr Pointer to the Mixer instance. DUCDDCStatus DUC/DDC status container.
References XDfeMix_DUCDDCStatus::Antenna, XDfeMix_DUCDDCStatus::NcoId, XDfeMix_DUCDDCStatus::Stage, XDfeMix::StateId, XDFEMIX_STATE_OPERATIONAL.
void XDfeMix_GetMixerStatus(const XDfeMix *InstancePtr, XDfeMix_MixerStatus *MixerStatus)
Gets Mixer overflow status.
InstancePtr Pointer to the Mixer instance. MixerStatus Mixer status container.
References XDfeMix_MixerStatus::Antenna, XDfeMix_MixerStatus::Mode, XDfeMix_MixerStatus::NcoId, XDfeMix_MixerStatus::Stage, XDfeMix::StateId, XDFEMIX_STATE_OPERATIONAL.
void XDfeMix_SetTUserDelay(const XDfeMix *InstancePtr, u32 Delay)
Sets the delay, which will be added to TUSER and TLAST (delay matched through the IP).
InstancePtr Pointer to the Mixer instance. Delay Requested delay in clock cycles.
References XDfeMix::StateId, XDFEMIX_STATE_INITIALISED.
u32 XDfeMix_GetTUserDelay(const XDfeMix *InstancePtr)
Reads the delay, which will be added to TUSER and TLAST (delay matched through the IP).
InstancePtr Pointer to the Mixer instance. Delay value in clock cycles.
u32 XDfeMix_GetTDataDelay(const XDfeMix *InstancePtr, u32 Tap, u32 *TDataDelay)
Returns sum of data latency and number of taps.
InstancePtr Pointer to the Mixer instance. Tap Tap value to be added to the data latency. TDataDelay Returned Data latency value in clock cycles. XST_SUCCESS if successful.XST_FAILURE if error occurs.
References XST_SUCCESS.
u32 XDfeMix_GetCenterTap(const XDfeMix *InstancePtr, u32 Rate, u32 *CenterTap)
Returns predefined Central Tap value for chosen RATE.
This will determine group delay. InstancePtr Pointer to the Mixer instance. Rate Interpolation/decimation rate index value [1-5]. CenterTap Returned Central Tap value. XST_SUCCESS if successful.XST_FAILURE if error occurs.
References XST_SUCCESS.
void XDfeMix_SetRegBank(const XDfeMix *InstancePtr, u32 RegBank)
Enables uplink or downlink register bank.
InstancePtr Pointer to the Channel Filter instance. RegBank Register bank value to be set.
Referenced by XDfeMix_GetCurrentCCCfgSwitchable, XDfeMix_Initialize, XDfeMix_SetNextCCCfgAndTriggerSwitchable.
void XDfeMix_GetVersions(const XDfeMix *InstancePtr, XDfeMix_Version *SwVersion, XDfeMix_Version *HwVersion)
This API gets the driver and HW design version.
SwVersion Driver version number. HwVersion HW version number.
References XDfeMix_Version::Major, XDfeMix_Version::Minor, XDfeMix_Version::Patch, XDfeMix_Version::Revision, XDfeMix::StateId, XDFEMIX_DRIVER_VERSION_MAJOR, XDFEMIX_DRIVER_VERSION_MINOR, XDFEMIX_STATE_NOT_READY.
Referenced by XDfeMix_AddCCExample, XDfeMix_MultiAddCCExample, XDfeMix_SelfTestExample.
void XDfeMix_GetInterruptMask(const XDfeMix *InstancePtr, XDfeMix_InterruptMask *Mask)
Gets interrupt mask status.
InstancePtr Pointer to the Mixer instance. Mask Interrupt masks container.
References XDfeMix_Status::CCSequenceError, XDfeMix_Status::CCUpdate, XDfeMix_Status::CCUpdateError, XDfeMix_Status::DUCDDCOverflow, XDfeMix_Status::LowPower, XDfeMix_Status::LowPowerError, XDfeMix_Status::MixerOverflow, XDfeMix_Status::Switchable, XDfeMix_Status::SwitchableError.
void XDfeMix_SetInterruptMask(const XDfeMix *InstancePtr, const XDfeMix_InterruptMask *Mask)
Sets interrupt mask.
InstancePtr Pointer to the Mixer instance. Mask Interrupt mask flags container. 0 - does not mask corresponding interrupt1 - masks corresponding interrupt
References XDfeMix_Status::CCSequenceError, XDfeMix_Status::CCUpdate, XDfeMix_Status::CCUpdateError, XDfeMix_Status::DUCDDCOverflow, XDfeMix_Status::LowPower, XDfeMix_Status::LowPowerError, XDfeMix_Status::MixerOverflow, XDfeMix_Status::Switchable, XDfeMix_Status::SwitchableError.
void XDfeMix_GetEventStatus(const XDfeMix *InstancePtr, XDfeMix_Status *Status)
Gets event status.
InstancePtr Pointer to the Mixer instance. Status Event status container.
References XDfeMix_Status::CCSequenceError, XDfeMix_Status::CCUpdate, XDfeMix_Status::CCUpdateError, XDfeMix_Status::DUCDDCOverflow, XDfeMix_Status::LowPower, XDfeMix_Status::LowPowerError, XDfeMix_Status::MixerOverflow, XDfeMix_Status::Switchable, XDfeMix_Status::SwitchableError.
void XDfeMix_ClearEventStatus(const XDfeMix *InstancePtr, const XDfeMix_Status *Status)
Clears event status.
InstancePtr Pointer to the Mixer instance. Status Clear event status container. 0 - does not clear corresponding event status1 - clear corresponding event status
References XDfeMix_Status::CCSequenceError, XDfeMix_Status::CCUpdate, XDfeMix_Status::CCUpdateError, XDfeMix_Status::DUCDDCOverflow, XDfeMix_Status::LowPower, XDfeMix_Status::LowPowerError, XDfeMix_Status::MixerOverflow, XDfeMix_Status::Switchable, XDfeMix_Status::SwitchableError.
Referenced by XDfeMix_AddCCExample, XDfeMix_MultiAddCCExample.
int XDfeMix_MultiAddCCExample()
This example configures Mixer driver for one CC with multiAddCC APIs.
This function does the following tasks: Create and system initialize the device driver instance.Read SW and HW version numbers.Reset the device.Configure the device.Initialize the device.Set the triggersActivate the device.Get current configuration.Add CC.Trigger configuration update.DeActivate the device. XST_SUCCESS if the example has completed successfully.XST_FAILURE if the example has failed.//! [testexample2]
References XDfeMix_TriggerCfg::Activate, XDfeMix_DUCDDCCfg::CCGain, XDfeMix_Status::CCSequenceError, XDfeMix_TriggerCfg::CCUpdate, XDfeMix_Status::CCUpdate, XDfeMix::Config, XDfeMix_CarrierCfg::DUCDDCCfg, XDfeMix_Status::DUCDDCOverflow, XDfeMix_NCO::FrequencyCfg, XDfeMix_Frequency::FrequencyControlWord, XDfeMix_CCSequence::Length, XDfeMix_Version::Major, XDfeMix_Config::MaxUseableCcids, XDfeMix_Version::Minor, XDfeMix_Status::MixerOverflow, XDfeMix_Trigger::Mode, XDfeMix_NCO::NCOGain, XDfeMix_DUCDDCCfg::NCOIdx, XDfeMix_Version::Patch, XDfeMix_Version::Revision, XDfeMix_Init::Sequence, XDfeMix_Frequency::TriggerUpdateFlag, XDfeMix_Trigger::TUSERBit, XDfeMix_Trigger::TuserEdgeLevel, XDfeMix_Init::TuserSelect, XDfeMix_Activate, XDfeMix_AddCCtoCCCfg, XDfeMix_ClearEventStatus, XDfeMix_Configure, XDfeMix_Deactivate, XDfeMix_GetCurrentCCCfg, XDfeMix_GetVersions, XDfeMix_Initialize, XDfeMix_InstanceClose, XDfeMix_InstanceInit, XDfeMix_Reset, XDfeMix_SetAntennaGain, XDfeMix_SetNextCCCfgAndTrigger, XDfeMix_SetTriggersCfg, XST_FAILURE, XST_SUCCESS.
Referenced by main.
int XDfeMix_AddCCExample()
This function runs the DFE Mixer device using the driver APIs.
This function does the following tasks: Create and system initialize the device driver instance.Read SW and HW version numbers.Reset the device.Configure the device.Initialize the device.Set the triggersActivate the device.Add CC.DeActivate the device. XST_SUCCESS if the example has completed successfully.XST_FAILURE if the example has failed.//! [testexample1]
References XDfeMix_TriggerCfg::Activate, XDfeMix_DUCDDCCfg::CCGain, XDfeMix_Status::CCSequenceError, XDfeMix_TriggerCfg::CCUpdate, XDfeMix_Status::CCUpdate, XDfeMix::Config, XDfeMix_CarrierCfg::DUCDDCCfg, XDfeMix_Status::DUCDDCOverflow, XDfeMix_NCO::FrequencyCfg, XDfeMix_Frequency::FrequencyControlWord, XDfeMix_CCSequence::Length, XDfeMix_Version::Major, XDfeMix_Config::MaxUseableCcids, XDfeMix_Version::Minor, XDfeMix_Status::MixerOverflow, XDfeMix_Trigger::Mode, XDfeMix_NCO::NCOGain, XDfeMix_DUCDDCCfg::NCOIdx, XDfeMix_Version::Patch, XDfeMix_Version::Revision, XDfeMix_Init::Sequence, XDfeMix_Frequency::TriggerUpdateFlag, XDfeMix_Trigger::TUSERBit, XDfeMix_Trigger::TuserEdgeLevel, XDfeMix_Init::TuserSelect, XDfeMix_Activate, XDfeMix_AddCC, XDfeMix_ClearEventStatus, XDfeMix_Configure, XDfeMix_Deactivate, XDfeMix_GetVersions, XDfeMix_Initialize, XDfeMix_InstanceClose, XDfeMix_InstanceInit, XDfeMix_Reset, XDfeMix_SetAntennaGain, XDfeMix_SetTriggersCfg, XST_FAILURE, XST_SUCCESS.
Referenced by main.
XDFEMIX_DRIVER_VERSION_MINOR
Driver's minor version number.
Referenced by XDfeMix_GetVersions.
XDFEMIX_DRIVER_VERSION_MAJOR
Driver's major version number.
Referenced by XDfeMix_GetVersions.
XDFEMIX_MAX_NUM_INSTANCES
Maximum number of driver instances running at the same time.
XDFEMIX_INSTANCE_EXISTS
XST_SUCCESS
Success flag.
Referenced by main, XDfeMix_AddCC, XDfeMix_AddCCExample, XDfeMix_AddCCtoCCCfg, XDfeMix_GetCenterTap, XDfeMix_GetTDataDelay, XDfeMix_InstanceInit, XDfeMix_MoveCC, XDfeMix_MultiAddCCExample, XDfeMix_RemoveCC, XDfeMix_SelfTestExample, XDfeMix_SetNextCCCfgAndTrigger, XDfeMix_SetNextCCCfgAndTriggerSwitchable, XDfeMix_UpdateCC, XDfeMix_UpdateCCinCCCfg, XDfeSi570_SetMgtOscillator.
XST_FAILURE
Failure flag.
Referenced by main, XDfeMix_AddCC, XDfeMix_AddCCExample, XDfeMix_AddCCtoCCCfg, XDfeMix_InstanceInit, XDfeMix_MoveCC, XDfeMix_MultiAddCCExample, XDfeMix_RemoveCC, XDfeMix_SelfTestExample, XDfeMix_SetNextCCCfgAndTrigger, XDfeMix_SetNextCCCfgAndTriggerSwitchable, XDfeMix_UpdateCC, XDfeMix_UpdateCCinCCCfg, XDfeSi570_SetMgtOscillator.
XDFEMIX_NODE_NAME_MAX_LENGTH
Node name maximum length.
Referenced by XDfeMix_InstanceInit.
XDFEMIX_CC_NUM
Maximum CC number.
Referenced by XDfeMix_GetEmptyCCCfg.
XDFEMIX_ANT_NUM_MAX
Maximum anntena number.
Referenced by XDfeMix_SetAntennaGain.
XDFEMIX_SEQ_LENGTH_MAX
Maximum sequence length.
XDFEMIX_AUX_NCO_MAX
Maximum Fabric NCO number.
XDFEMIX_NCO_MAX
Maximum NCO number, 16 CC NCO + 4 aux NCO.
XDFEMIX_CC_GAIN_MAX
Maximum CC gain.
Referenced by XDfeMix_AddCC.
XDFEMIX_COMPATIBLE_STRING
Device name property.
XDFEMIX_PLATFORM_DEVICE_DIR
Device location in a file system.
XDFEMIX_COMPATIBLE_PROPERTY
Device tree property.
XDFEMIX_BUS_NAME
System bus name.
XDFEMIX_BASEADDR_PROPERTY
Base address property.
XDFEMIX_BASEADDR_SIZE
Base address bit-size.
XDFEMIX_MODE_CFG
Mode: 0 = DOWNLINK, 1 = UPLINK.
XDFEMIX_NUM_ANTENNA_CFG
Number of antenna property.
XDFEMIX_MAX_USABLE_CCIDS_CFG
Maximum number of CC's per antenna.
XDFEMIX_LANES_CFG
Number of parallel data channels required.
XDFEMIX_ANTENNA_INTERLEAVE_CFG
Number of TDM antenna.
XDFEMIX_MIXER_CPS_CFG
Mixer clock per sample property.
XDFEMIX_NUM_AUXILIARY
Number of auxiliary NCO.
XDFEMIX_DATA_IWIDTH_CFG
Input stream data bit width.
XDFEMIX_DATA_OWIDTH_CFG
Output stream data bit width.
XDFEMIX_TUSER_WIDTH_CFG
Width of the tuser input.