xdfemix_examples.c
int XDfeSi570_SetMgtOscillator(double CurrentFrequency, double NewFrequency)
This function: initialize I2C bus, reads current state of si570, calculates parameters for si570 MGT oscillator new frequency, writes them to si570 and resets PL to use the new frequency.
CurrentFrequency MGT oscillator current frequency. NewFrequency MGT oscillator new frequency. None None
References XST_FAILURE, XST_SUCCESS.
Referenced by main.
int XDfeMix_SelfTestExample()
This function runs the DFE Mixer device using the driver APIs.
This function does the following tasks: Create and system initialize the device driver instance.Read SW and HW version numbers.Reset the device.Configure the device.Initialize the device.Activate the device.DeActivate the device. XST_SUCCESS if the example has completed successfully.XST_FAILURE if the example has failed.
References XDfeMix_Version::Major, XDfeMix_Version::Minor, XDfeMix_Version::Patch, XDfeMix_Version::Revision, XDfeMix_Init::TuserSelect, XDfeMix_Activate, XDfeMix_Configure, XDfeMix_Deactivate, XDfeMix_GetVersions, XDfeMix_Initialize, XDfeMix_InstanceClose, XDfeMix_InstanceInit, XDfeMix_Reset, XST_FAILURE, XST_SUCCESS.
Referenced by main.
int XDfeMix_AddCCExample()
This function runs the DFE Mixer device using the driver APIs.
This function does the following tasks: Create and system initialize the device driver instance.Read SW and HW version numbers.Reset the device.Configure the device.Initialize the device.Set the triggersActivate the device.Add CC.DeActivate the device. XST_SUCCESS if the example has completed successfully.XST_FAILURE if the example has failed.//! [testexample1]
References XST_SUCCESS, XST_FAILURE, XDfeMix_InstanceInit, XDfeMix_GetVersions, XDfeMix_Version::Major, XDfeMix_Version::Minor, XDfeMix_Version::Revision, XDfeMix_Version::Patch, XDfeMix_Reset, XDfeMix_Configure, XDfeMix_Init::Sequence, XDfeMix_CCSequence::Length, XDfeMix_Init::TuserSelect, XDfeMix_Initialize, XDfeMix_TriggerCfg::Activate, XDfeMix_Trigger::Mode, XDfeMix_Trigger::TuserEdgeLevel, XDfeMix_Trigger::TUSERBit, XDfeMix_TriggerCfg::CCUpdate, XDfeMix_SetTriggersCfg, XDfeMix_Activate, XDfeMix_Status::DUCDDCOverflow, XDfeMix_Status::MixerOverflow, XDfeMix_Status::CCUpdate, XDfeMix_Status::CCSequenceError, XDfeMix_ClearEventStatus, XDfeMix_SetAntennaGain, XDfeMix::Config, XDfeMix_Config::MaxUseableCcids, XDfeMix_CarrierCfg::DUCDDCCfg, XDfeMix_DUCDDCCfg::NCOIdx, XDfeMix_DUCDDCCfg::CCGain, XDfeMix_NCO::NCOGain, XDfeMix_NCO::FrequencyCfg, XDfeMix_Frequency::FrequencyControlWord, XDfeMix_Frequency::TriggerUpdateFlag, XDfeMix_AddCC, XDfeMix_Deactivate, XDfeMix_InstanceClose.
Referenced by main.
int XDfeMix_MultiAddCCExample()
This example configures Mixer driver for one CC with multiAddCC APIs.
This function does the following tasks: Create and system initialize the device driver instance.Read SW and HW version numbers.Reset the device.Configure the device.Initialize the device.Set the triggersActivate the device.Get current configuration.Add CC.Trigger configuration update.DeActivate the device. XST_SUCCESS if the example has completed successfully.XST_FAILURE if the example has failed.//! [testexample2]
References XST_SUCCESS, XST_FAILURE, XDfeMix_InstanceInit, XDfeMix_GetVersions, XDfeMix_Version::Major, XDfeMix_Version::Minor, XDfeMix_Version::Revision, XDfeMix_Version::Patch, XDfeMix_Reset, XDfeMix_Configure, XDfeMix_Init::Sequence, XDfeMix_CCSequence::Length, XDfeMix_Init::TuserSelect, XDfeMix_Initialize, XDfeMix_TriggerCfg::Activate, XDfeMix_Trigger::Mode, XDfeMix_Trigger::TuserEdgeLevel, XDfeMix_Trigger::TUSERBit, XDfeMix_TriggerCfg::CCUpdate, XDfeMix_SetTriggersCfg, XDfeMix_Activate, XDfeMix_Status::DUCDDCOverflow, XDfeMix_Status::MixerOverflow, XDfeMix_Status::CCUpdate, XDfeMix_Status::CCSequenceError, XDfeMix_ClearEventStatus, XDfeMix_SetAntennaGain, XDfeMix::Config, XDfeMix_Config::MaxUseableCcids, XDfeMix_CarrierCfg::DUCDDCCfg, XDfeMix_DUCDDCCfg::NCOIdx, XDfeMix_DUCDDCCfg::CCGain, XDfeMix_NCO::NCOGain, XDfeMix_NCO::FrequencyCfg, XDfeMix_Frequency::FrequencyControlWord, XDfeMix_Frequency::TriggerUpdateFlag, XDfeMix_GetCurrentCCCfg, XDfeMix_AddCCtoCCCfg, XDfeMix_SetNextCCCfgAndTrigger, XDfeMix_Deactivate, XDfeMix_InstanceClose.
Referenced by main.
int main(void)
Main function that initialise si570 and runs examples.
None. XST_SUCCESS if the example has completed successfully.XST_FAILURE if the example has failed.
References XDfeMix_AddCCExample, XDfeMix_MultiAddCCExample, XDfeMix_SelfTestExample, XDfeSi570_SetMgtOscillator, XST_FAILURE, XST_SUCCESS.