xv_hdmirxss.c
XV_HdmiRxSs_BridgeYuv420
This macro selects the bridge YUV420 mode.
InstancePtr is a pointer to the HDMI RX Subsystem Enable is a flag to enable or disable YUV420 mode
XV_HdmiRxSs_BridgePixelDrop
This macro selects the bridge pixel repeat mode.
InstancePtr is a pointer to the HDMI RX Subsystem Enable is a flag to enable or disable pixel drop mode
XV_HdmiRxSs_SubCores XV_HdmiRxSs_SubCoreRepo[][]
Define Driver instance of all sub-core included in the design.
static void XV_HdmiRxSs_GetIncludedSubcores(XV_HdmiRxSs *HdmiRxSsPtr, UINTPTR BaseAddress)
This function queries the subsystem instance configuration to determine the included sub-cores.
For each sub-core that is present in the design the sub-core driver instance is binded with the subsystem sub-core driver handle HdmiRxSsPtr is a pointer to the Subsystem instance to be worked on. None
static void XV_HdmiRxSs_WaitUs(XV_HdmiRxSs *InstancePtr, u32 MicroSeconds)
This function is the delay/sleep function for the XV_HdmiRxSs driver.
For the Zynq family, there exists native sleep functionality. For MicroBlaze however, there does not exist such functionality. In the MicroBlaze case, the default method for delaying is to use a predetermined amount of loop iterations. This method is prone to inaccuracy and dependent on system configuration; for greater accuracy, the user may supply their own delay/sleep handler, pointed to by InstancePtr->UserTimerWaitUs, which may have better accuracy if a hardware timer is used. InstancePtr is a pointer to the HdmiSsRx instance. MicroSeconds is the number of microseconds to delay/sleep for. None. None.
static void XV_HdmiRxSs_RetrieveVSInfoframe(XV_HdmiRxSs *HdmiRxSs)
This function retrieves the Vendor Specific Info Frame.
None. None. None.
static int XV_HdmiRxSs_RegisterSubsysCallbacks(XV_HdmiRxSs *InstancePtr)
This function register's all sub-core ISR's with interrupt controller and any subsystem level call back function with requisite sub-core.
InstancePtr is a pointer to the Subsystem instance to be worked on.
static void XV_HdmiRxSs_ConnectCallback(void *CallbackRef)
This function is called when a RX connect event has occurred.
None. None. None.
static void XV_HdmiRxSs_BrdgOverflowCallback(void *CallbackRef)
This function is called when a Bridge overflow event has occurred.
None. None. None.
static void XV_HdmiRxSs_AuxCallback(void *CallbackRef)
This function is called when a RX AUX IRQ has occurred.
None. None. None.
static void XV_HdmiRxSs_AudCallback(void *CallbackRef)
This function is called when a RX Audio IRQ has occurred.
None. None. None.
static void XV_HdmiRxSs_LnkStaCallback(void *CallbackRef)
This function is called when a RX Link Status IRQ has occurred.
None. None. None.
static void XV_HdmiRxSs_DdcCallback(void *CallbackRef)
This function is called when a RX DDC IRQ has occurred.
None. None. None.
static void XV_HdmiRxSs_StreamDownCallback(void *CallbackRef)
This function is called when the RX stream is down.
None. None. None.
static void XV_HdmiRxSs_StreamInitCallback(void *CallbackRef)
This function is called when the RX stream init .
None. None. None.
static void XV_HdmiRxSs_StreamUpCallback(void *CallbackRef)
This function is called when the RX stream is up.
None. None. None.
static void XV_HdmiRxSs_SyncLossCallback(void *CallbackRef)
This function is called when a RX Sync Loss IRQ has occurred.
None. None. None.
static void XV_HdmiRxSs_ModeCallback(void *CallbackRef)
This function is called when the mode has transitioned from DVI to HDMI or vice versa.
None. None. None.
static void XV_HdmiRxSs_TmdsClkRatioCallback(void *CallbackRef)
This function is called when the TMDS CLK ratio changes.
None. None. None.
static void XV_HdmiRxSs_VicErrorCallback(void *CallbackRef)
This function is called when the Vic does not match with the detected video timing.
None. None. None.
static void XV_HdmiRxSs_PhyErrorCallback(void *CallbackRef)
This function is called when a PHY error has occurred (e.g.
stream up timeout while locked; application may reset the video PHY). CallbackRef is a reference to the HDMI RX Subsystem instance. None. None.
static void XV_HdmiRxSs_ReportCoreInfo(XV_HdmiRxSs *InstancePtr)
This function reports list of cores included in Video Processing Subsystem.
InstancePtr is a pointer to the Subsystem instance. None
static void XV_HdmiRxSs_ReportTiming(XV_HdmiRxSs *InstancePtr)
This function prints the HDMI RX SS timing information.
None. None. None.
static void XV_HdmiRxSs_ReportLinkQuality(XV_HdmiRxSs *InstancePtr)
This function reports the link quality based on the link error counter.
None. None. None.
static void XV_HdmiRxSs_ReportDRMInfo(XV_HdmiRxSs *InstancePtr)
This function prints the HDMI RX SS DRM If information.
None. None. None.
static void XV_HdmiRxSs_ReportAudio(XV_HdmiRxSs *InstancePtr)
This function prints the HDMI RX SS audio information.
None. None. None.
static void XV_HdmiRxSs_ReportInfoFrame(XV_HdmiRxSs *InstancePtr)
This function prints the HDMI RX SS audio information.
None. None. None.
void XV_HdmiRxSs_ReportSubcoreVersion(XV_HdmiRxSs *InstancePtr)
This function prints the HDMI RX SS subcore versions.
InstancePtr is a pointer to the XV_HdmiRxSs instance. None. None.
static void XV_HdmiRxSs_ConfigBridgeMode(XV_HdmiRxSs *InstancePtr)
This function configures the Bridge for YUV420 functionality and repeater.
InstancePtr Instance Pointer to the main data structure None None.
void XV_HdmiRxSs_ReportInfo(XV_HdmiRxSs *InstancePtr)
void XV_HdmiRxSs_SetUserTimerHandler(XV_HdmiRxSs *InstancePtr, XVidC_DelayHandler CallbackFunc, void *CallbackRef)
This function installs a custom delay/sleep function to be used by the XV_HdmiRxSs driver.
InstancePtr is a pointer to the HdmiSsRx instance. CallbackFunc is the address to the callback function. CallbackRef is the user data item (microseconds to delay) that will be passed to the custom sleep/delay function when it is invoked. None. None.
References XV_HdmiRxSs::UserTimerPtr, XV_HdmiRxSs::UserTimerWaitUs.
void XV_HdmiRxSS_HdmiRxIntrHandler(XV_HdmiRxSs *InstancePtr)
This function calls the interrupt handler for HDMI RX.
InstancePtr is a pointer to the HDMI RX Subsystem
References XV_HdmiRxSs::HdmiRxPtr.
int XV_HdmiRxSs_CfgInitialize(XV_HdmiRxSs *InstancePtr, XV_HdmiRxSs_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the video subsystem and included sub-cores.
This function must be called prior to using the subsystem. Initialization includes setting up the instance data for top level as well as all included sub-core therein, and ensuring the hardware is in a known stable state. InstancePtr is a pointer to the Subsystem instance to be worked on. CfgPtr points to the configuration structure associated with the subsystem instance. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if initialization is successful else XST_FAILURE
References XV_HdmiRxSs::AppMajVer, XV_HdmiRxSs::AppMinVer, XV_HdmiRxSs_Config::BaseAddress, XV_HdmiRxSs::Config, XV_HdmiRxSs::HdmiRxPtr, XV_HdmiRxSs::IsReady, XV_HdmiRxSs_GetDrmInfoframe, XV_HDMIRXSS_HDCP_14, XV_HDMIRXSS_HDCP_22, XV_HDMIRXSS_HDCP_BOTH, XV_HDMIRXSS_HDCP_NOUSERPREF, XV_HdmiRxSs_Reset, XV_HdmiRxSs_SubcoreInitHdmiRx.
void XV_HdmiRxSs_Start(XV_HdmiRxSs *InstancePtr)
This function starts the HDMI RX subsystem including all sub-cores that are included in the processing pipeline for a given use-case.
Video pipe is started from back to front InstancePtr is a pointer to the Subsystem instance to be worked on. None Cores are started only if the corresponding start flag in the scratch pad memory is set. This allows to selectively start only those cores included in the processing chain
References XV_HdmiRxSs::HdmiRxPtr, XV_HDMIRXSS_LOG_EVT_START, XV_HdmiRxSs_LogWrite.
void XV_HdmiRxSs_Stop(XV_HdmiRxSs *InstancePtr)
This function stops the HDMI RX subsystem including all sub-cores Stop the video pipe starting from front to back.
InstancePtr is a pointer to the Subsystem instance to be worked on. None
References XV_HdmiRxSs::HdmiRxPtr, XV_HDMIRXSS_LOG_EVT_STOP, XV_HdmiRxSs_LogWrite.
void XV_HdmiRxSs_Reset(XV_HdmiRxSs *InstancePtr)
This function resets the video subsystem sub-cores.
There are 2 reset networks within the subsystem For cores that are on AXIS interfaceFor cores that are on AXI-MM interface InstancePtr is a pointer to the Subsystem instance to be worked on. None
References XV_HDMIRXSS_LOG_EVT_RESET, XV_HdmiRxSs_LogWrite, XV_HdmiRxSs_RXCore_LRST, XV_HdmiRxSs_RXCore_VRST, XV_HdmiRxSs_SYSRST.
Referenced by XV_HdmiRxSs_CfgInitialize.
void XV_HdmiRxSs_RXCore_VRST(XV_HdmiRxSs *InstancePtr, u8 Reset)
This function asserts or releases the Internal Video reset of the HDMI subcore within the subsystem.
InstancePtr is a pointer to the Subsystem instance to be worked on. Reset is a flag to assert (TRUE) or release (FALSE) the reset. None
References XV_HdmiRxSs::HdmiRxPtr.
Referenced by XV_HdmiRxSs_Reset.
void XV_HdmiRxSs_RXCore_LRST(XV_HdmiRxSs *InstancePtr, u8 Reset)
This function asserts or releases the Internal Link reset of the HDMI subcore within the subsystem.
InstancePtr is a pointer to the Subsystem instance to be worked on. Reset is a flag to assert (TRUE) or release (FALSE) the reset. None
References XV_HdmiRxSs::HdmiRxPtr.
Referenced by XV_HdmiRxSs_Reset.
void XV_HdmiRxSs_VRST(XV_HdmiRxSs *InstancePtr, u8 Reset)
This function asserts or releases the video reset of other blocks within the subsystem.
InstancePtr is a pointer to the Subsystem instance to be worked on. Reset is a flag to assert (TRUE) or release (FALSE) the reset. None
References XV_HdmiRxSs::HdmiRxPtr.
void XV_HdmiRxSs_SYSRST(XV_HdmiRxSs *InstancePtr, u8 Reset)
This function asserts or releases the system reset of other blocks within the subsystem.
InstancePtr is a pointer to the Subsystem instance to be worked on. Reset is a flag to assert (TRUE) or release (FALSE) the reset. None
References XV_HdmiRxSs::HdmiRxPtr.
Referenced by XV_HdmiRxSs_Reset.
int XV_HdmiRxSs_SetCallback(XV_HdmiRxSs *InstancePtr, XV_HdmiRxSs_HandlerType HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs an asynchronous callback function for the given HandlerType:
HandlerTypeCallbackFunctionType ------------------------------------------------------------------------- (XV_HDMIRXSS_HANDLER_CONNECT)HpdCallback (XV_HDMIRXSS_HANDLER_VS)VsCallback (XV_HDMIRXSS_HANDLER_STREAM_DOWN)StreamDownCallback (XV_HDMIRXSS_HANDLER_STREAM_UP)StreamUpCallback (XV_HDMIRXSS_HANDLER_HDCP_AUTHENTICATED) (XV_HDMIRXSS_HANDLER_HDCP_UNAUTHENTICATED) (XV_HDMIRXSS_HANDLER_HDCP_AUTHENTICATION_REQUEST) (XV_HDMIRXSS_HANDLER_HDCP_STREAM_MANAGE_REQUEST) (XV_HDMIRXSS_HANDLER_HDCP_TOPOLOGY_UPDATE) InstancePtr is a pointer to the HDMI RX Subsystem instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XV_HdmiRxSs::AudCallback, XV_HdmiRxSs::AudRef, XV_HdmiRxSs::AuxCallback, XV_HdmiRxSs::AuxRef, XV_HdmiRxSs::BrdgOverflowCallback, XV_HdmiRxSs::BrdgOverflowRef, XV_HdmiRxSs::ConnectCallback, XV_HdmiRxSs::ConnectRef, XV_HdmiRxSs::DdcCallback, XV_HdmiRxSs::DdcRef, XV_HdmiRxSs::HdcpCallback, XV_HdmiRxSs::HdcpRef, XV_HdmiRxSs::LnkStaCallback, XV_HdmiRxSs::LnkStaRef, XV_HdmiRxSs::PhyErrorCallback, XV_HdmiRxSs::PhyErrorRef, XV_HdmiRxSs::StreamDownCallback, XV_HdmiRxSs::StreamDownRef, XV_HdmiRxSs::StreamInitCallback, XV_HdmiRxSs::StreamInitRef, XV_HdmiRxSs::StreamUpCallback, XV_HdmiRxSs::StreamUpRef, XV_HdmiRxSs::TmdsClkRatioCallback, XV_HdmiRxSs::TmdsClkRatioRef, XV_HdmiRxSs::VicErrorCallback, XV_HdmiRxSs::VicErrorRef, XV_HDMIRXSS_HANDLER_AUD, XV_HDMIRXSS_HANDLER_AUX, XV_HDMIRXSS_HANDLER_BRDGOVERFLOW, XV_HDMIRXSS_HANDLER_CONNECT, XV_HDMIRXSS_HANDLER_DDC, XV_HDMIRXSS_HANDLER_HDCP, XV_HDMIRXSS_HANDLER_HDCP_AUTHENTICATED, XV_HDMIRXSS_HANDLER_HDCP_AUTHENTICATION_REQUEST, XV_HDMIRXSS_HANDLER_HDCP_ENCRYPTION_UPDATE, XV_HDMIRXSS_HANDLER_HDCP_STREAM_MANAGE_REQUEST, XV_HDMIRXSS_HANDLER_HDCP_TOPOLOGY_UPDATE, XV_HDMIRXSS_HANDLER_HDCP_UNAUTHENTICATED, XV_HDMIRXSS_HANDLER_LNKSTA, XV_HDMIRXSS_HANDLER_PHY_ERROR, XV_HDMIRXSS_HANDLER_STREAM_DOWN, XV_HDMIRXSS_HANDLER_STREAM_INIT, XV_HDMIRXSS_HANDLER_STREAM_UP, XV_HDMIRXSS_HANDLER_TMDS_CLK_RATIO, XV_HDMIRXSS_HANDLER_VIC_ERROR.
void XV_HdmiRxSs_SetEdidParam(XV_HdmiRxSs *InstancePtr, u8 *EdidDataPtr, u16 Length)
This function Sets the EDID parameters in the HDMI RX SS struct.
InstancePtr is a pointer to the XV_HdmiRxSs instance. EdidDataPtr is a pointer to the EDID data buffer. Length is the length of the EDID data buffer. None. None.
References XV_HdmiRxSs::EdidLength, XV_HdmiRxSs::EdidPtr.
void XV_HdmiRxSs_LoadDefaultEdid(XV_HdmiRxSs *InstancePtr)
This function loads the default EDID to the HDMI RX.
InstancePtr is a pointer to the XV_HdmiRxSs instance. None. None.
References XV_HdmiRxSs::EdidLength, XV_HdmiRxSs::EdidPtr, XV_HdmiRxSs::HdmiRxPtr.
void XV_HdmiRxSs_LoadEdid(XV_HdmiRxSs *InstancePtr, u8 *EdidDataPtr, u16 Length)
This function loads the specified EDID to the HDMI RX.
InstancePtr is a pointer to the XV_HdmiRxSs instance. EdidDataPtr is a pointer to the EDID data buffer to be loaded. Length is the length of the EDID data buffer. None. None.
References XV_HdmiRxSs::HdmiRxPtr.
void XV_HdmiRxSs_SetHpd(XV_HdmiRxSs *InstancePtr, u8 Value)
This function sets the HPD on the HDMI RX.
InstancePtr is a pointer to the XV_HdmiRxSs instance. Value is a flag used to set the HPD. TRUE drives HPD highFALSE drives HPD low None. None.
References XV_HdmiRxSs::HdmiRxPtr.
void XV_HdmiRxSs_ToggleHpd(XV_HdmiRxSs *InstancePtr)
This function toggles the HPD on the HDMI RX.
InstancePtr is a pointer to the XV_HdmiRxSs instance. None. None.
References XV_HdmiRxSs::HdmiRxPtr.
XHdmiC_Aux* XV_HdmiRxSs_GetAuxiliary(XV_HdmiRxSs *InstancePtr)
This function returns the pointer to HDMI RX SS Aux structure.
InstancePtr pointer to XV_HdmiRxSs instance XVidC_VideoStream pointer None.
References XV_HdmiRxSs::HdmiRxPtr.
void XV_HdmiRxSs_Write_ScdcRegister(XV_HdmiRxSs *InstancePtr, u8 address, u8 data)
This function writes to SCDC registers.
InstancePtr is a pointer to the XV_HdmiRxSs instance. address is the SCDC register address to write to. data is the data value to write to the register. None. None.
XHdmiC_AVI_InfoFrame* XV_HdmiRxSs_GetAviInfoframe(XV_HdmiRxSs *InstancePtr)
This function returns the pointer to HDMI RX SS AVI InfoFrame structure.
InstancePtr pointer to XV_HdmiRXSs instance XHdmiC_AVI_InfoFrame pointer None.
References XV_HdmiRxSs::AVIInfoframe.
XHdmiC_GeneralControlPacket* XV_HdmiRxSs_GetGCP(XV_HdmiRxSs *InstancePtr)
This function returns the pointer to HDMI RX SS General Control Packet structure.
InstancePtr pointer to XV_HdmiRXSs instance XHdmiC_GeneralControlPacket pointer None.
References XV_HdmiRxSs::GCP.
XHdmiC_AudioInfoFrame* XV_HdmiRxSs_GetAudioInfoframe(XV_HdmiRxSs *InstancePtr)
This function returns the pointer to HDMI RX SS Audio InfoFrame structure.
InstancePtr pointer to XV_HdmiRXSs instance XHdmiC_AudioInfoFrame pointer None.
References XV_HdmiRxSs::AudioInfoframe.
XHdmiC_VSIF* XV_HdmiRxSs_GetVSIF(XV_HdmiRxSs *InstancePtr)
This function returns the pointer to HDMI RX SS Vendor Specific InfoFrame structure.
InstancePtr pointer to XV_HdmiRxSs instance XHdmiC_VSIF pointer None.
References XV_HdmiRxSs::VSIF.
XHdmiC_DRMInfoFrame* XV_HdmiRxSs_GetDrmInfoframe(XV_HdmiRxSs *InstancePtr)
This function returns the pointer to HDMI RX SS DRM InfoFrame structure.
InstancePtr pointer to XV_HdmiRxSs instance XHdmiC_DRMInfoFrame pointer None.
Referenced by XV_HdmiRxSs_CfgInitialize.
u32 XV_HdmiRxSs_SetStream(XV_HdmiRxSs *InstancePtr, u32 Clock, u32 LineRate)
This function set HDMI RX subsystem stream parameters.
InstancePtr is a pointer to the XV_HdmiRxSs instance. Clock is the TMDS clock value. LineRate is the line rate value. XST_SUCCESS if stream parameters set successfully.XST_FAILURE if Clock is 0. None.
References XV_HdmiRxSs::Config, XV_HdmiRxSs::HdmiRxPtr, XV_HdmiRxSs_Config::Ppc, XV_HDMIRXSS_LOG_EVT_SETSTREAM, XV_HDMIRXSS_LOG_EVT_SETSTREAM_ERR, XV_HdmiRxSs_LogWrite.
XVidC_VideoStream* XV_HdmiRxSs_GetVideoStream(XV_HdmiRxSs *InstancePtr)
This function returns the pointer to HDMI RX SS video stream.
InstancePtr pointer to XV_HdmiRxSs instance XVidC_VideoStream pointer None.
References XV_HdmiRxSs::HdmiRxPtr.
u8 XV_HdmiRxSs_GetVideoIDCode(XV_HdmiRxSs *InstancePtr)
This function returns the pointer to HDMI RX SS video Identification code.
InstancePtr pointer to XV_HdmiRxSs instance VIC None.
References XV_HdmiRxSs::HdmiRxPtr.
u8 XV_HdmiRxSs_GetVideoStreamType(XV_HdmiRxSs *InstancePtr)
This function returns the pointer to HDMI RX SS video stream type.
InstancePtr pointer to XV_HdmiRxSs instance Stream Type 1:HDMI 0:DVI None.
References XV_HdmiRxSs::HdmiRxPtr.
u8 XV_HdmiRxSs_GetVideoStreamScramblingFlag(XV_HdmiRxSs *InstancePtr)
This function returns the pointer to HDMI RX SS video stream type.
InstancePtr pointer to XV_HdmiRxSs instance Stream Type 1:IsScrambled 0: not Scrambled None.
References XV_HdmiRxSs::HdmiRxPtr.
u8 XV_HdmiRxSs_GetAudioChannels(XV_HdmiRxSs *InstancePtr)
This function returns the HDMI RX SS number of active audio channels.
InstancePtr pointer to XV_HdmiRxSs instance Channels None.
References XV_HdmiRxSs::AudioChannels.
XV_HdmiRx_AudioFormatType XV_HdmiRxSs_GetAudioFormat(XV_HdmiRxSs *InstancePtr)
This function returns the HDMI RX SS audio format.
InstancePtr pointer to XV_HdmiRxSs instance Channels None.
References XV_HdmiRxSs::HdmiRxPtr.
void XV_HdmiRxSs_RefClockChangeInit(XV_HdmiRxSs *InstancePtr)
This function is called when HDMI RX SS TMDS clock changes.
InstancePtr is a pointer to the XV_HdmiRxSs instance. None. None.
References XV_HdmiRxSs::HdmiRxPtr, XV_HdmiRxSs::TMDSClockRatio, XV_HDMIRXSS_LOG_EVT_REFCLOCKCHANGE, XV_HdmiRxSs_LogWrite.
int XV_HdmiRxSs_IsStreamUp(XV_HdmiRxSs *InstancePtr)
This function checks if the video stream is up.
InstancePtr is a pointer to the XV_HdmiRxSs instance. TRUE if stream is up.FALSE if stream is down. None.
References XV_HdmiRxSs::IsStreamUp.
int XV_HdmiRxSs_IsStreamConnected(XV_HdmiRxSs *InstancePtr)
This function checks if the interface is connected.
InstancePtr is a pointer to the XV_HdmiRxSs instance. TRUE if interface is connected.FALSE if interface is not connected. None.
References XV_HdmiRxSs::IsStreamConnected.
void XV_HdmiRxSs_SetDefaultPpc(XV_HdmiRxSs *InstancePtr, u8 Id)
This function will set the default in HDF.
InstancePtr is a pointer to the XV_HdmiRxSs core instance. Id is the XV_HdmiRxSs ID to operate on. None. None.
References XV_HdmiRxSs::Config, XV_HdmiRxSs_Config::Ppc.
void XV_HdmiRxSs_SetPpc(XV_HdmiRxSs *InstancePtr, u8 Id, u8 Ppc)
This function will set PPC specified by user.
InstancePtr is a pointer to the XV_HdmiRxSs core instance. Id is the XV_HdmiRxSs ID to operate on. Ppc is the PPC to be set. None. None.
References XV_HdmiRxSs::Config, XV_HdmiRxSs_Config::Ppc.
void XV_HdmiRxSS_SetAppVersion(XV_HdmiRxSs *InstancePtr, u8 maj, u8 min)
This function will set the major and minor application version in RXSs struct.
InstancePtr is a pointer to the XV_HdmiRxSs core instance. maj is the major version of the application. min is the minor version of the application. void. None.
References XV_HdmiRxSs::AppMajVer, XV_HdmiRxSs::AppMinVer.
void XV_HdmiRxSs_AudioMute(XV_HdmiRxSs *InstancePtr, u8 Enable)
This function set HDMI RX audio parameters.
InstancePtr is a pointer to the XV_HdmiRxSs instance. Enable 0: Unmute the audio 1: Mute the audio. None. None.
References XV_HdmiRxSs::HdmiRxPtr.