xv_hdmirxss_log.c
void XV_HdmiRxSs_LogReset(XV_HdmiRxSs *InstancePtr)
This function will reset the driver's logging mechanism.
InstancePtr is a pointer to the xv_hdmirxss core instance. None. None.
References XV_HdmiRxSs_Log::HeadIndex, XV_HdmiRxSs::Log, XV_HdmiRxSs_Log::TailIndex.
void XV_HdmiRxSs_LogWrite(XV_HdmiRxSs *InstancePtr, XV_HdmiRxSs_LogEvent Evt, u8 Data)
This function will insert an event in the driver's logginc mechanism.
InstancePtr is a pointer to the XV_HdmiRxSs core instance. Evt is the event type to log. Data is the associated data for the event. None. None.
References XV_HdmiRxSs_Log::DataBuffer, XV_HdmiRxSs_Log::HeadIndex, XV_HdmiRxSs::Log, XV_HdmiRxSs_Log::TailIndex, XV_HDMIRXSS_LOG_EVT_DUMMY.
Referenced by XV_HdmiRxSs_RefClockChangeInit, XV_HdmiRxSs_Reset, XV_HdmiRxSs_SetStream, XV_HdmiRxSs_Start, XV_HdmiRxSs_Stop, XV_HdmiRxSs_SubcoreInitHdmiRx.
u16 XV_HdmiRxSs_LogRead(XV_HdmiRxSs *InstancePtr)
This function will read the last event from the log.
InstancePtr is a pointer to the XV_HdmiRxSs core instance. The log data. None.
References XV_HdmiRxSs_Log::DataBuffer, XV_HdmiRxSs_Log::HeadIndex, XV_HdmiRxSs::Log, XV_HdmiRxSs_Log::TailIndex.
Referenced by XV_HdmiRxSs_LogDisplay.
void XV_HdmiRxSs_LogDisplay(XV_HdmiRxSs *InstancePtr)
This function will print the entire log.
InstancePtr is a pointer to the XV_HdmiRxSs core instance. None. None.
References ANSI_COLOR_RED, ANSI_COLOR_RESET, ANSI_COLOR_YELLOW, XV_HDMIRXSS_LOG_EVT_CONNECT, XV_HDMIRXSS_LOG_EVT_DISCONNECT, XV_HDMIRXSS_LOG_EVT_DVIMODE, XV_HDMIRXSS_LOG_EVT_HDCP14, XV_HDMIRXSS_LOG_EVT_HDCP14_INIT, XV_HDMIRXSS_LOG_EVT_HDCP22, XV_HDMIRXSS_LOG_EVT_HDCP22_INIT, XV_HDMIRXSS_LOG_EVT_HDCPTIMER_INIT, XV_HDMIRXSS_LOG_EVT_HDMIMODE, XV_HDMIRXSS_LOG_EVT_HDMIRX_INIT, XV_HDMIRXSS_LOG_EVT_LINKSTATUS, XV_HDMIRXSS_LOG_EVT_NONE, XV_HDMIRXSS_LOG_EVT_PIX_REPEAT_ERR, XV_HDMIRXSS_LOG_EVT_REFCLOCKCHANGE, XV_HDMIRXSS_LOG_EVT_RESET, XV_HDMIRXSS_LOG_EVT_SETSTREAM, XV_HDMIRXSS_LOG_EVT_SETSTREAM_ERR, XV_HDMIRXSS_LOG_EVT_START, XV_HDMIRXSS_LOG_EVT_STOP, XV_HDMIRXSS_LOG_EVT_STREAMDOWN, XV_HDMIRXSS_LOG_EVT_STREAMINIT, XV_HDMIRXSS_LOG_EVT_STREAMUP, XV_HDMIRXSS_LOG_EVT_SYNCEST, XV_HDMIRXSS_LOG_EVT_SYNCLOSS, XV_HDMIRXSS_LOG_EVT_VICERROR, XV_HDMIRXSS_LOG_EVT_VTC_INIT, XV_HdmiRxSs_LogRead.