usbps
XUSBPS_TIMEOUT_COUNTER
XUSBPS_EP_DIRECTION_IN
Endpoint direction IN.
Referenced by main, XUsbPs_Ch9HandleSetupPacket, XUsbPs_ClassReq, XUsbPs_EpPrime, XUsbPs_EpSetHandler, XUsbPs_EpSetIsoHandler, XUsbPs_ReconfigureEp, XUsbPs_SetConfiguration, XUsbPs_SetConfigurationApp, XUsbPs_SetInterfaceHandler.
XUSBPS_EP_DIRECTION_OUT
Endpoint direction OUT.
Referenced by main, XUsbPs_Ch9HandleSetupPacket, XUsbPs_ClassReq, XUsbPs_EpPrime, XUsbPs_EpSetHandler, XUsbPs_EpSetIsoHandler, XUsbPs_IntrHandler, XUsbPs_ReconfigureEp, XUsbPs_SetConfiguration, XUsbPs_SetConfigurationApp, XUsbPs_SetInterfaceHandler.
XUSBPS_EP_TYPE_NONE
Endpoint is not used.
XUSBPS_EP_TYPE_CONTROL
Endpoint for Control Transfers.
Referenced by main.
XUSBPS_EP_TYPE_ISOCHRONOUS
Endpoint for isochronous data.
Referenced by main.
XUSBPS_EP_TYPE_BULK
Endpoint for BULK Transfers.
XUSBPS_EP_TYPE_INTERRUPT
Endpoint for interrupt Transfers.
ENDPOINT_MAXP_LENGTH
Endpoint Max Packet Length in DeviceConfig is a coded value, ch9.6.6.
ENDPOINT_MAXP_MULT_MASK
ENDPOINT_MAXP_MULT_SHIFT
XUSBPS_EP_STS_ADDRESS
Address of controller.
XUSBPS_EP_STS_CONTROLLER_STATE
Current controller state.
XUSBPS_DEFAULT_ALT_SETTING
The default alternate setting is 0.
Referenced by XUsbPs_CfgInitialize.
XUSBPS_EP_EVENT_SETUP_DATA_RECEIVED
Setup data has been received on the endpoint.
XUSBPS_EP_EVENT_DATA_RX
Data frame has been received on the endpoint.
XUSBPS_EP_EVENT_DATA_TX
Data frame has been sent on the endpoint.
XUSBPS_dTDNLP_T_MASK
USB dTD Next Link Pointer Terminate Bit.
XUSBPS_dTDNLP_ADDR_MASK
USB dTD Next Link Pointer Address [31:5].
XUSBPS_dTDTOKEN_XERR_MASK
dTD Transaction Error
XUSBPS_dTDTOKEN_BUFERR_MASK
dTD Data Buffer Error
XUSBPS_dTDTOKEN_HALT_MASK
dTD Halted Flag
XUSBPS_dTDTOKEN_ACTIVE_MASK
dTD Active Bit
XUSBPS_dTDTOKEN_MULTO_MASK
Multiplier Override Field [1:0].
XUSBPS_dTDTOKEN_IOC_MASK
Interrupt on Complete Bit.
XUSBPS_dTDTOKEN_LEN_MASK
Transfer Length Field.
XUSBPS_dQHCFG_IOS_MASK
USB dQH Interrupt on Setup Bit.
XUSBPS_dQHCFG_MPL_MASK
USB dQH Maximum Packet Length Field [10:0].
XUSBPS_dQHCFG_MPL_SHIFT
XUSBPS_dQHCFG_ZLT_MASK
USB dQH Zero Length Termination Select Bit.
XUSBPS_dQHCFG_MULT_MASK
XUSBPS_dQHCFG_MULT_SHIFT
XUSBPS_TIMER0_LD_OFFSET
XUSBPS_TIMER0_CTL_OFFSET
XUSBPS_TIMER_RUN_MASK
XUSBPS_TIMER_STOP_MASK
XUSBPS_TIMER_RESET_MASK
XUSBPS_TIMER_REPEAT_MASK
XUSBPS_TIMER_COUNTER_MASK
XUSBPS_HWDEVICE_OFFSET
XUSBPS_EP_NUM_MASK
XUSBPS_EP_NUM_SHIFT
XUSBPS_HCSPARAMS_OFFSET
XUSBPS_CMD_OFFSET
Configuration.
Referenced by XUsbPs_DeviceReset, XUsbPs_Reset, XUsbPs_ResetHw.
XUSBPS_ISR_OFFSET
Interrupt Status.
Referenced by XUsbPs_IntrHandler, XUsbPs_ResetHw.
XUSBPS_IER_OFFSET
Interrupt Enable.
Referenced by XUsbPs_ResetHw.
XUSBPS_FRAME_OFFSET
USB Frame Index.
XUSBPS_LISTBASE_OFFSET
H: Periodic List Base Address.
Referenced by XUsbPs_ResetHw.
XUSBPS_DEVICEADDR_OFFSET
D: Device Address.
Referenced by XUsbPs_SetDeviceAddress.
XUSBPS_ASYNCLISTADDR_OFFSET
H: Async List Address.
Referenced by XUsbPs_ResetHw.
XUSBPS_EPLISTADDR_OFFSET
D: Endpoint List Addr.
Referenced by XUsbPs_ConfigureDevice.
XUSBPS_TTCTRL_OFFSET
TT Control.
XUSBPS_BURSTSIZE_OFFSET
Burst Size.
XUSBPS_TXFILL_OFFSET
Tx Fill Tuning.
XUSBPS_ULPIVIEW_OFFSET
ULPI Viewport.
XUSBPS_EPNAKISR_OFFSET
Endpoint NAK IRQ Status.
Referenced by XUsbPs_IntrHandler.
XUSBPS_EPNAKIER_OFFSET
Endpoint NAK IRQ Enable.
XUSBPS_PORTSCR1_OFFSET
Port Control/Status 1.
XUSBPS_PORTSCRn_OFFSET
XUSBPS_OTGCSR_OFFSET
OTG Status and Control.
Referenced by XUsbPs_ConfigureDevice.
XUSBPS_MODE_OFFSET
USB Mode.
Referenced by XUsbPs_ConfigureDevice.
XUSBPS_EPSTAT_OFFSET
Endpoint Setup Status.
Referenced by XUsbPs_DeviceReset, XUsbPs_EpGetSetupData, XUsbPs_IntrHandler.
XUSBPS_EPPRIME_OFFSET
Endpoint Prime.
Referenced by XUsbPs_DeviceReset, XUsbPs_EpPrime.
XUSBPS_EPFLUSH_OFFSET
Endpoint Flush.
Referenced by XUsbPs_DeviceReset.
XUSBPS_EPRDY_OFFSET
Endpoint Ready.
XUSBPS_EPCOMPL_OFFSET
Endpoint Complete.
Referenced by XUsbPs_DeviceReset, XUsbPs_IntrHandler.
XUSBPS_EPCR0_OFFSET
Endpoint Control 0.
XUSBPS_EPCR1_OFFSET
Endpoint Control 1.
Referenced by XUsbPs_SetConfiguration.
XUSBPS_EPCR2_OFFSET
Endpoint Control 2.
XUSBPS_EPCR3_OFFSET
Endpoint Control 3.
XUSBPS_EPCR4_OFFSET
Endpoint Control 4.
XUSBPS_MAX_ENDPOINTS
Number of supported Endpoints in this core.
XUSBPS_EP_OUT_MASK
OUR (RX) endpoint mask.
Referenced by XUsbPs_IntrHandler.
XUSBPS_EP_IN_MASK
IN (TX) endpoint mask.
Referenced by XUsbPs_IntrHandler.
XUSBPS_EP_ALL_MASK
Mask used for endpoint control registers.
Referenced by XUsbPs_DeviceReset.
XUSBPS_EPCRn_OFFSET
XUSBPS_EPFLUSH_RX_SHIFT
XUSBPS_EPFLUSH_TX_SHIFT
XUSBPS_EPCR_TXT_TYPE_SHIFT
XUSBPS_EPCR_TXT_TYPE_MASK
XUSBPS_EPCR_TXT_CONTROL_MASK
Control Endpoint - TX.
XUSBPS_EPCR_TXT_ISO_MASK
Isochronous.
Endpoint
XUSBPS_EPCR_TXT_BULK_MASK
Bulk Endpoint - TX.
Referenced by XUsbPs_SetConfiguration.
XUSBPS_EPCR_TXT_INTR_MASK
Interrupt Endpoint.
XUSBPS_EPCR_TXS_MASK
Stall TX endpoint.
XUSBPS_EPCR_TXE_MASK
Transmit enable - TX.
XUSBPS_EPCR_TXR_MASK
Data Toggle Reset Bit.
Referenced by XUsbPs_SetConfiguration.
XUSBPS_EPCR_RXT_TYPE_SHIFT
XUSBPS_EPCR_RXT_TYPE_MASK
Endpoint Type - RX read only.
XUSBPS_EPCR_RXT_CONTROL_MASK
Control Endpoint - RX.
XUSBPS_EPCR_RXT_ISO_MASK
Isochronous Endpoint.
XUSBPS_EPCR_RXT_BULK_MASK
Bulk Endpoint - RX.
Referenced by XUsbPs_SetConfiguration.
XUSBPS_EPCR_RXT_INTR_MASK
Interrupt Endpoint.
XUSBPS_EPCR_RXS_MASK
Stall RX endpoint.
XUSBPS_EPCR_RXE_MASK
Transmit enable.
RX
XUSBPS_EPCR_RXR_MASK
Data Toggle Reset Bit.
Referenced by XUsbPs_SetConfiguration.
XUSBPS_CMD_RS_MASK
Run/Stop.
XUSBPS_CMD_RST_MASK
Controller RESET.
Referenced by XUsbPs_DeviceReset, XUsbPs_Reset, XUsbPs_ResetHw.
XUSBPS_CMD_FS01_MASK
Frame List Size bit 0,1.
XUSBPS_CMD_PSE_MASK
Periodic Sched Enable.
XUSBPS_CMD_ASE_MASK
Async Sched Enable.
XUSBPS_CMD_IAA_MASK
IRQ Async Advance Doorbell.
XUSBPS_CMD_ASP_MASK
Async Sched Park Mode Cnt.
XUSBPS_CMD_ASPE_MASK
Async Sched Park Mode Enbl.
XUSBPS_CMD_SUTW_MASK
Setup TripWire.
XUSBPS_CMD_ATDTW_MASK
Add dTD TripWire.
XUSBPS_CMD_FS2_MASK
Frame List Size bit 2.
XUSBPS_CMD_ITC_MASK
IRQ Threshold Control.
XUSBPS_CMD_ITHRESHOLD_0
Immediate interrupt.
XUSBPS_CMD_ITHRESHOLD_1
1 micro-frame
XUSBPS_CMD_ITHRESHOLD_2
2 micro-frames
XUSBPS_CMD_ITHRESHOLD_4
4 micro-frames
XUSBPS_CMD_ITHRESHOLD_8
8 micro-frames
XUSBPS_CMD_ITHRESHOLD_16
16 micro-frames
XUSBPS_CMD_ITHRESHOLD_32
32 micro-frames
XUSBPS_CMD_ITHRESHOLD_64
64 micro-frames
XUSBPS_CMD_ITHRESHOLD_MAX
XUSBPS_CMD_ITHRESHOLD_DEFAULT
XUSBPS_IXR_UI_MASK
USB Transaction Complete.
Referenced by main, XUsbPs_IntrHandler.
XUSBPS_IXR_UE_MASK
Transaction Error.
XUSBPS_IXR_PC_MASK
Port Change Detect.
XUSBPS_IXR_FRE_MASK
Frame List Rollover.
XUSBPS_IXR_AA_MASK
Async Advance.
XUSBPS_IXR_UR_MASK
RESET Received.
Referenced by main, XUsbPs_IntrHandler.
XUSBPS_IXR_SR_MASK
Start of Frame.
XUSBPS_IXR_SLE_MASK
Device Controller Suspend.
XUSBPS_IXR_ULPI_MASK
ULPI IRQ.
XUSBPS_IXR_HCH_MASK
Host Controller Halted Read Only.
XUSBPS_IXR_RCL_MASK
USB Reclamation Read Only.
XUSBPS_IXR_PS_MASK
Periodic Sched Status Read Only.
XUSBPS_IXR_AS_MASK
Async Sched Status Read only.
XUSBPS_IXR_NAK_MASK
NAK IRQ.
Referenced by XUsbPs_IntrHandler.
XUSBPS_IXR_UA_MASK
USB Host Async IRQ.
XUSBPS_IXR_UP_MASK
USB Host Periodic IRQ.
XUSBPS_IXR_TI0_MASK
Timer 0 Interrupt.
XUSBPS_IXR_TI1_MASK
Timer 1 Interrupt.
XUSBPS_IXR_ALL
Mask for ALL IRQ types.
XUSBPS_MODE_CM_MASK
Controller Mode Select.
XUSBPS_MODE_CM_IDLE_MASK
XUSBPS_MODE_CM_DEVICE_MASK
XUSBPS_MODE_CM_HOST_MASK
XUSBPS_MODE_ES_MASK
USB Endian Select.
XUSBPS_MODE_SLOM_MASK
USB Setup Lockout Mode Disable.
Referenced by XUsbPs_ConfigureDevice.
XUSBPS_MODE_SDIS_MASK
XUSBPS_MODE_VALID_MASK
XUSBPS_DEVICEADDR_DEVICEAADV_MASK
Device Addr Auto Advance.
Referenced by XUsbPs_SetDeviceAddress.
XUSBPS_DEVICEADDR_ADDR_MASK
Device Address.
XUSBPS_DEVICEADDR_ADDR_SHIFT
Address shift.
Referenced by XUsbPs_SetDeviceAddress.
XUSBPS_DEVICEADDR_MAX
Biggest allowed address.
Referenced by XUsbPs_SetDeviceAddress.
XUSBPS_TTCTRL_HUBADDR_MASK
TT Hub Address.
XUSBPS_BURSTSIZE_RX_MASK
RX Burst Length.
XUSBPS_BURSTSIZE_TX_MASK
TX Burst Length.
XUSBPS_TXFILL_OVERHEAD_MASK
Scheduler Overhead.
XUSBPS_TXFILL_HEALTH_MASK
Scheduler Health Cntr.
XUSBPS_TXFILL_BURST_MASK
FIFO Burst Threshold.
XUSBPS_ULPIVIEW_DATWR_MASK
ULPI Data Write.
XUSBPS_ULPIVIEW_DATRD_MASK
ULPI Data Read.
XUSBPS_ULPIVIEW_ADDR_MASK
ULPI Data Address.
XUSBPS_ULPIVIEW_PORT_MASK
ULPI Port Number.
XUSBPS_ULPIVIEW_SS_MASK
ULPI Synchronous State.
XUSBPS_ULPIVIEW_RW_MASK
ULPI Read/Write Control.
XUSBPS_ULPIVIEW_RUN_MASK
ULPI Run.
XUSBPS_ULPIVIEW_WU_MASK
ULPI Wakeup.
XUSBPS_PORTSCR_CCS_MASK
Current Connect Status.
XUSBPS_PORTSCR_CSC_MASK
Connect Status Change.
XUSBPS_PORTSCR_PE_MASK
Port Enable/Disable.
XUSBPS_PORTSCR_PEC_MASK
Port Enable/Disable Change.
XUSBPS_PORTSCR_OCA_MASK
Over-current Active.
XUSBPS_PORTSCR_OCC_MASK
Over-current Change.
XUSBPS_PORTSCR_FPR_MASK
Force Port Resume.
XUSBPS_PORTSCR_SUSP_MASK
Suspend.
XUSBPS_PORTSCR_PR_MASK
Port Reset.
XUSBPS_PORTSCR_HSP_MASK
High Speed Port.
XUSBPS_PORTSCR_LS_MASK
Line Status.
XUSBPS_PORTSCR_PP_MASK
Port Power.
XUSBPS_PORTSCR_PO_MASK
Port Owner.
XUSBPS_PORTSCR_PIC_MASK
Port Indicator Control.
XUSBPS_PORTSCR_PTC_MASK
Port Test Control.
XUSBPS_PORTSCR_WKCN_MASK
Wake on Connect Enable.
XUSBPS_PORTSCR_WKDS_MASK
Wake on Disconnect Enable.
XUSBPS_PORTSCR_WKOC_MASK
Wake on Over-current Enable.
XUSBPS_PORTSCR_PHCD_MASK
PHY Low Power Suspend - Clock Disable.
XUSBPS_PORTSCR_PFSC_MASK
Port Force Full Speed Connect.
XUSBPS_PORTSCR_PSPD_MASK
Port Speed.
XUSBPS_OTGSC_VD_MASK
VBus Discharge Bit.
XUSBPS_OTGSC_VC_MASK
VBus Charge Bit.
XUSBPS_OTGSC_HAAR_MASK
HW Assist Auto Reset Enable Bit.
XUSBPS_OTGSC_OT_MASK
OTG Termination Bit.
Referenced by XUsbPs_ConfigureDevice.
XUSBPS_OTGSC_DP_MASK
Data Pulsing Pull-up Enable Bit.
XUSBPS_OTGSC_IDPU_MASK
ID Pull-up Enable Bit.
XUSBPS_OTGSC_HADP_MASK
HW Assist Data Pulse Enable Bit.
XUSBPS_OTGSC_HABA_MASK
USB Hardware Assist B Disconnect to A Connect Enable Bit.
XUSBPS_OTGSC_ID_MASK
ID Status Flag.
XUSBPS_OTGSC_AVV_MASK
USB A VBus Valid Interrupt Status Flag.
XUSBPS_OTGSC_ASV_MASK
USB A Session Valid Interrupt Status Flag.
XUSBPS_OTGSC_BSV_MASK
USB B Session Valid Status Flag.
XUSBPS_OTGSC_BSE_MASK
USB B Session End Status Flag.
XUSBPS_OTGSC_1MST_MASK
USB 1 Millisecond Timer Status Flag.
XUSBPS_OTGSC_DPS_MASK
Data Pulse Status Flag.
XUSBPS_OTGSC_IDIS_MASK
USB ID Interrupt Status Flag.
XUSBPS_OTGSC_AVVIS_MASK
USB A VBus Valid Interrupt Status Flag.
XUSBPS_OTGSC_ASVIS_MASK
USB A Session Valid Interrupt Status Flag.
XUSBPS_OTGSC_BSVIS_MASK
USB B Session Valid Interrupt Status Flag.
XUSBPS_OTGSC_BSEIS_MASK
USB B Session End Interrupt Status Flag.
XUSBPS_OTGSC_1MSS_MASK
1 Millisecond Timer Interrupt Status Flag
XUSBPS_OTGSC_DPIS_MASK
Data Pulse Interrupt Status Flag.
XUSBPS_OTGSC_IDIE_MASK
ID Interrupt Enable Bit.
XUSBPS_OTGSC_AVVIE_MASK
USB A VBus Valid Interrupt Enable Bit.
XUSBPS_OTGSC_ASVIE_MASK
USB A Session Valid Interrupt Enable Bit.
XUSBPS_OTGSC_BSVIE_MASK
USB B Session Valid Interrupt Enable Bit.
XUSBPS_OTGSC_BSEE_MASK
USB B Session End Interrupt Enable Bit.
XUSBPS_OTGSC_1MSE_MASK
1 Millisecond Timer Interrupt Enable Bit
XUSBPS_OTGSC_DPIE_MASK
Data Pulse Interrupt Enable Bit.
XUSBPS_OTG_ISB_ALL
XUSBPS_OTG_IEB_ALL
Mask for All IRQ status masks.
XUsbPs_Config XUsbPs_ConfigTable[][]
Each XUsbPs device in the system has an entry in this table.
XUsbPs_Config XUsbPs_ConfigTable[][]
Each XUsbPs device in the system has an entry in this table.
int XUsbPs_CfgInitialize(XUsbPs *InstancePtr, const XUsbPs_Config *ConfigPtr, u32 VirtBaseAddress)
This function initializes a XUsbPs instance/driver.
Setup / Initialize functions.The initialization entails: Initialize all members of the XUsbPs structure. InstancePtr is a pointer to XUsbPs instance of the controller. ConfigPtr is a pointer to a XUsbPs_Config configuration structure. This structure will contain the requested configuration for the device. Typically, this is a local structure and the content of which will be copied into the configuration structure within XUsbPs. VirtBaseAddress is the base address of the device. For systems with virtual memory, this address must be the virtual address of the device. For systems that do not support virtual memory this address should be the physical address of the device. For backwards compatibility NULL may be passed in systems that do not support virtual memory (deprecated). XST_SUCCESS no errors occurred.XST_FAILURE an error occurred during initialization. After calling XUsbPs_CfgInitialize() the controller IS NOT READY for use. Before the controller can be used its DEVICE parameters must be configured. See xusbps.h for details.
References XUsbPs_Config::BaseAddress, XUsbPs::Config, XUsbPs::CurrentAltSetting, XUsbPs::HandlerFunc, XUSBPS_DEFAULT_ALT_SETTING.
Referenced by XUsbPs_CfgInit.
void XUsbPs_DeviceReset(XUsbPs *InstancePtr)
This function performs device reset, device is stopped at the end.
InstancePtr is a pointer to XUsbPs instance of the controller. None. None.
References XUsbPs_Config::BaseAddress, XUsbPs::Config, XUSBPS_CMD_OFFSET, XUSBPS_CMD_RST_MASK, XUSBPS_EP_ALL_MASK, XUSBPS_EPCOMPL_OFFSET, XUSBPS_EPFLUSH_OFFSET, XUSBPS_EPPRIME_OFFSET, XUSBPS_EPSTAT_OFFSET, XUsbPs_ReadReg, XUsbPs_Stop, XUsbPs_WriteReg.
int XUsbPs_Reset(XUsbPs *InstancePtr)
This function resets the USB device.
Common functions used for DEVICE/HOST mode.All the configuration registers are reset to their default values. The function waits until the reset operation is complete or for a certain duration within which the reset operation is expected to be completed. InstancePtr is a pointer to XUsbPs instance of the controller. XST_SUCCESS Reset operation completed successfully.XST_FAILURE Reset operation timed out. None.
References XUsbPs_Config::BaseAddress, XUsbPs::Config, XUSBPS_CMD_OFFSET, XUSBPS_CMD_RST_MASK, XUsbPs_ReadReg, XUsbPs_WriteReg.
Referenced by XUsbPs_ConfigureDevice.
int XUsbPs_Suspend(const XUsbPs *InstancePtr)
USB Suspend.
Handling Suspend and Resume.In order to conserve power, USB devices automatically enter the suspended state when the device has observed no bus traffic for a specified period. When suspended, the USB device maintains any internal status, including its address and configuration. Attached devices must be prepared to suspend at any time they are powered, regardless of if they have been assigned a non-default address, are configured, or neither. Bus activity may cease due to the host entering a suspend mode of its own. In addition, a USB device shall also enter the suspended state when the hub port it is attached to is disabled.A USB device exits suspend mode when there is bus activity. A USB device may also request the host to exit suspend mode or selective suspend by using electrical signaling to indicate remote wakeup. The ability of a device to signal remote wakeup is optional. If the USB device is capable of remote wakeup signaling, the device must support the ability of the host to enable and disable this capability. When the device is reset, remote wakeup signaling must be disabled. InstancePtr is a pointer to XUsbPs instance of the controller. XST_SUCCESS if the USB device has entered Suspend mode successfullyXST_FAILURE on any error None.
int XUsbPs_Resume(const XUsbPs *InstancePtr)
USB Resume.
If the USB controller is suspended, its operation is resumed when any non-idle signaling is received on its upstream facing port. InstancePtr is a pointer to XUsbPs instance of the controller. XST_SUCCESS if the USB device has Resumed successfullyXST_FAILURE on any error None.
int XUsbPs_RequestHostResume(const XUsbPs *InstancePtr)
USB Assert Resume.
InstancePtr is a pointer to XUsbPs instance of the controller. XST_SUCCESS if the USB device has Resumed successfullyXST_FAILURE on any error None.
int XUsbPs_SetDeviceAddress(XUsbPs *InstancePtr, u8 Address)
This functions sets the controller's DEVICE address.
It also sets the advance bit so the controller will wait for the next IN-ACK before the new address takes effect. InstancePtr is a pointer to XUsbPs instance of the controller. Address is the Address of the device. XST_SUCCESS: Address set successfully.XST_FAILURE: An error occurred.XST_INVALID_PARAM: Invalid parameter passed, e.g. address value too big. None.
References XUsbPs_Config::BaseAddress, XUsbPs::Config, XUSBPS_DEVICEADDR_ADDR_SHIFT, XUSBPS_DEVICEADDR_DEVICEAADV_MASK, XUSBPS_DEVICEADDR_MAX, XUSBPS_DEVICEADDR_OFFSET, XUsbPs_WriteReg.
static void XUsbPs_EpListInit(XUsbPs_DeviceConfig *DevCfgPtr)
This function initializes the endpoint pointer data structure.
The function sets up the local data structure with the aligned addresses for the Queue Head and Transfer Descriptors. DevCfgPtr is pointer to the XUsbPs DEVICE configuration structure. none Endpoints of type XUSBPS_EP_TYPE_NONE are not used in the system. Therefore no memory is reserved for them.
static void XUsbPs_dQHInit(XUsbPs_DeviceConfig *DevCfgPtr)
This function initializes the Queue Head List in memory.
DevCfgPtr is a pointer to the XUsbPs DEVICE configuration structure. None None.
static int XUsbPs_dTDInit(XUsbPs_DeviceConfig *DevCfgPtr)
This function initializes the Transfer Descriptors lists in memory.
DevCfgPtr is a pointer to the XUsbPs DEVICE configuration structure. XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred.
static int XUsbPs_dTDAttachBuffer(XUsbPs_dTD *dTDPtr, const u8 *BufferPtr, u32 BufferLen)
This function associates a buffer with a Transfer Descriptor.
The function will take care of splitting the buffer into multiple 4kB aligned segments if the buffer happens to span one or more 4kB pages. dTDIndex is a pointer to the Transfer Descriptor BufferPtr is pointer to the buffer to link to the descriptor. BufferLen is the length of the buffer. XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred.XST_USB_BUF_TOO_BIG: The provided buffer is bigger than the maximum allowed buffer size (16k). Cache invalidation and flushing needs to be handler by the caller of this function.
static void XUsbPs_dQHSetMaxPacketLenISO(XUsbPs_dQH *dQHPtr, u32 Len)
This function set the Max PacketLen for the queue head for isochronous EP.
If the max packet length is greater than XUSBPS_MAX_PACKET_SIZE, then Mult bits are set to reflect that. dQHPtr is a pointer to the dQH element. Len is the Length to be set.
static void XUsbPs_dQHReinitEp(XUsbPs_DeviceConfig *DevCfgPtr, int EpNum, unsigned short NewDirection)
This function re-initializes the Queue Head List in memory.
The endpoint 1 has been disabled before this call. DevCfgPtr Pointer to the updated XUsbPs DEVICE configuration structure. EpNum The endpoint to be reconfigured. NewDirection The new transfer direction of endpoint 1 none
static int XUsbPs_dTDReinitEp(XUsbPs_DeviceConfig *DevCfgPtr, int EpNum, unsigned short NewDirection)
This function re-initializes the Transfer Descriptors lists in memory.
The endpoint has been disabled before the call. The transfer descriptors list pointer has been initialized too. DevCfgPtr Pointer to the XUsbPs DEVICE configuration structure. EpNum The endpoint to be reconfigured. NewDirection The new transfer direction of endpoint 1 XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred.
static int XUsbPs_EpQueueRequest(XUsbPs *InstancePtr, u8 EpNum, const u8 *BufferPtr, u32 BufferLen, u8 ReqZero)
This function sends a given data buffer and also sends ZLT packet if it is requested.
InstancePtr is a pointer to XUsbPs instance of the controller. EpNum is the number of the endpoint to receive data from. BufferPtr is a pointer to the buffer to send. BufferLen is the Buffer length. ReqZero is the XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred.XST_USB_BUF_TOO_BIG: Provided buffer is too big (>16kB).XST_USB_NO_DESC_AVAILABLE: No TX descriptor is available.
int XUsbPs_ConfigureDevice(XUsbPs *InstancePtr, const XUsbPs_DeviceConfig *CfgPtr)
This function configures the DEVICE side of the controller.
The caller needs to pass in the desired configuration (e.g. number of endpoints) and a DMAable buffer that will hold the Queue Head List and the Transfer Descriptors. The required size for this buffer can be obtained by the caller using the: XUsbPs_DeviceMemRequired() macro. InstancePtr is a pointer to the XUsbPs instance of the controller. CfgPtr is a pointer to the configuration structure that contains the desired DEVICE side configuration. XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred. The caller may configure the controller for both, DEVICE and HOST side.
References XUsbPs_Config::BaseAddress, XUsbPs::Config, XUsbPs::DeviceConfig, XUsbPs_DeviceConfig::DMAMemPhys, XUsbPs_DeviceConfig::PhysAligned, XUSBPS_dQH_BASE_ALIGN, XUSBPS_EPLISTADDR_OFFSET, XUSBPS_MODE_OFFSET, XUSBPS_MODE_SLOM_MASK, XUSBPS_OTGCSR_OFFSET, XUSBPS_OTGSC_OT_MASK, XUsbPs_Reset, XUsbPs_SetBits, XUsbPs_WriteReg.
Referenced by main.
int XUsbPs_EpBufferSend(XUsbPs *InstancePtr, u8 EpNum, const u8 *BufferPtr, u32 BufferLen)
This function sends a given data buffer.
InstancePtr is a pointer to XUsbPs instance of the controller. EpNum is the number of the endpoint to receive data from. BufferPtr is a pointer to the buffer to send. BufferLen is the Buffer length. XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred.XST_USB_BUF_TOO_BIG: Provided buffer is too big (>16kB).XST_USB_NO_DESC_AVAILABLE: No TX descriptor is available.
References XUsbPs_DeviceConfig::NumEndpoints.
Referenced by XUsbPs_ClassReq, XUsbPs_HandleStorageReq.
int XUsbPs_EpBufferSendWithZLT(XUsbPs *InstancePtr, u8 EpNum, const u8 *BufferPtr, u32 BufferLen)
This function sends a given data buffer and also zero length packet if the Bufferlen is in multiples of endpoint max packet size.
InstancePtr is a pointer to XUsbPs instance of the controller. EpNum is the number of the endpoint to receive data from. BufferPtr is a pointer to the buffer to send. BufferLen is the Buffer length. XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred.XST_USB_BUF_TOO_BIG: Provided buffer is too big (>16kB).XST_USB_NO_DESC_AVAILABLE: No TX descriptor is available.
References XUsbPs::DeviceConfig, XUsbPs_DeviceConfig::EpCfg, XUsbPs_EpConfig::In, XUsbPs_EpSetup::MaxPacketSize, XUsbPs_DeviceConfig::NumEndpoints.
void XUsbPs_EpGetData(XUsbPs *InstancePtr, u8 EpNum, u32 BufferLen)
This function receives a data buffer from the endpoint of the given endpoint number and pass it to the application.
InstancePtr is a pointer to the XUsbPs instance of the controller. EpNum is the number of the endpoint to receive data from. BufferLen is holding the buffer length. None. None.
References XUsbPs_EpOut::BufferPtr, XUsbPs_EpSetup::BufSize, XUsbPs_EpOut::BytesTxed, XUsbPs::DeviceConfig, XUsbPs_EpOut::dTDCurr, XUsbPs_DeviceConfig::Ep, XUsbPs_DeviceConfig::EpCfg, XUsbPs_EpOut::HandlerIsoFunc, XUsbPs_EpOut::HandlerRef, XUsbPs_EpSetup::MaxPacketSize, XUsbPs_EpOut::MemAlloted, XUsbPs_Endpoint::Out, XUsbPs_EpConfig::Out, XUsbPs_EpOut::RequestedBytes, XUSBPS_dTDBPTR0, XUsbPs_dTDGetNLP, XUsbPs_dTDGetTransferLen, XUsbPs_dTDInvalidateCache, XUsbPs_dTDIsActive, XUsbPs_dTDSetTransferLen, XUSBPS_dTDUSERDATA, XUsbPs_EpBufferRelease, XUsbPs_ReaddTD, XUsbPs_WritedTD.
Referenced by XUsbPs_EpDataBufferReceive.
int XUsbPs_EpBufferReceive(XUsbPs *InstancePtr, u8 EpNum, u8 **BufferPtr, u32 *BufferLenPtr, u32 *Handle)
This function receives a data buffer from the endpoint of the given endpoint number.
InstancePtr is a pointer to the XUsbPs instance of the controller. EpNum is the number of the endpoint to receive data from. BufferPtr (OUT param) is a pointer to the buffer pointer to hold the reference of the data buffer. BufferLenPtr (OUT param) is a pointer to the integer that will hold the buffer length. Handle is the opaque handle to be used when the buffer is released. XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred.XST_USB_NO_BUF: No buffer available. After handling the data in the buffer, the user MUST release the buffer using the Handle by calling the XUsbPs_EpBufferRelease() function.
References XUsbPs_EpSetup::BufSize, XUsbPs::DeviceConfig, XUsbPs_EpOut::dTDCurr, XUsbPs_DeviceConfig::Ep, XUsbPs_DeviceConfig::EpCfg, XUsbPs_DeviceConfig::NumEndpoints, XUsbPs_Endpoint::Out, XUsbPs_EpConfig::Out, XUSBPS_dTDBPTR0, XUsbPs_dTDGetTransferLen, XUsbPs_dTDInvalidateCache, XUsbPs_dTDIsActive, XUsbPs_dTDSetTransferLen, XUSBPS_dTDUSERDATA, XUsbPs_ReaddTD, XUsbPs_WritedTD.
void XUsbPs_EpBufferRelease(u32 Handle)
This function returns a previously received data buffer to the driver.
Handle is a pointer to the buffer that is returned. None.
References XUSBPS_dTD_ALIGN, XUsbPs_dTDClrTerminate, XUsbPs_dTDInvalidateCache, XUsbPs_dTDSetActive, XUsbPs_dTDSetIOC.
Referenced by XUsbPs_EpGetData.
s32 XUsbPs_EpDataBufferReceive(XUsbPs *InstancePtr, u8 EpNum, u8 *BufferPtr, u32 BufferLen)
This function receives a data buffer from the endpoint of the given endpoint number.
InstancePtr is a pointer to the XUsbPs instance of the controller. EpNum is the number of the endpoint to receive data from. BufferPtr (OUT param) is a pointer to the buffer pointer to hold the reference of the data buffer. BufferLen (OUT param) is a pointer to the integer that will hold the buffer length. XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred.XST_USB_NO_BUF: No buffer available.
References XUsbPs_EpOut::BufferPtr, XUsbPs_EpOut::BytesTxed, XUsbPs::DeviceConfig, XUsbPs_EpOut::dTDCurr, XUsbPs_DeviceConfig::Ep, XUsbPs_EpOut::MemAlloted, XUsbPs_DeviceConfig::NumEndpoints, XUsbPs_Endpoint::Out, XUsbPs_EpOut::RequestedBytes, XUsbPs_dTDInvalidateCache, XUsbPs_dTDIsActive, XUsbPs_EpGetData.
Referenced by XUsbPs_ClassReq.
int XUsbPs_EpSetHandler(XUsbPs *InstancePtr, u8 EpNum, u8 Direction, XUsbPs_EpHandlerFunc CallBackFunc, void *CallBackRef)
This function sets the handler for endpoint events.
InstancePtr is a pointer to the XUsbPs instance of the controller. EpNum is the number of the endpoint to receive data from. Direction is the direction of the endpoint (bitfield): XUSBPS_EP_DIRECTION_OUTXUSBPS_EP_DIRECTION_IN CallBackFunc is the Handler callback function. Can be NULL if the user wants to disable the handler entry. CallBackRef is the user definable data pointer that will be passed back if the handler is called. May be NULL. XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred.XST_INVALID_PARAM: Invalid parameter passed. The user can disable a handler by setting the callback function pointer to NULL.
References XUsbPs::DeviceConfig, XUsbPs_DeviceConfig::Ep, XUsbPs_EpOut::HandlerRef, XUsbPs_EpIn::HandlerRef, XUsbPs_Endpoint::In, XUsbPs_DeviceConfig::NumEndpoints, XUsbPs_Endpoint::Out, XUSBPS_EP_DIRECTION_IN, XUSBPS_EP_DIRECTION_OUT.
Referenced by main.
s32 XUsbPs_EpSetIsoHandler(XUsbPs *InstancePtr, u8 EpNum, u8 Direction, XUsbPs_EpIsoHandlerFunc CallBackFunc)
This function sets the handler for ISO endpoint events.
InstancePtr is a pointer to the XUsbPs instance of the controller. EpNum is the number of the endpoint to receive data from. Direction is the direction of the endpoint (bitfield): XUSBPS_EP_DIRECTION_OUTXUSBPS_EP_DIRECTION_IN CallBackFunc is the Handler callback function. Can be NULL if the user wants to disable the handler entry. XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred.XST_INVALID_PARAM: Invalid parameter passed. The user can disable a handler by setting the callback function pointer to NULL.
References XUsbPs::DeviceConfig, XUsbPs_DeviceConfig::Ep, XUsbPs_EpOut::HandlerIsoFunc, XUsbPs_EpIn::HandlerIsoFunc, XUsbPs_EpOut::HandlerRef, XUsbPs_EpIn::HandlerRef, XUsbPs_Endpoint::In, XUsbPs_DeviceConfig::NumEndpoints, XUsbPs_Endpoint::Out, XUSBPS_EP_DIRECTION_IN, XUSBPS_EP_DIRECTION_OUT.
Referenced by main.
int XUsbPs_EpPrime(XUsbPs *InstancePtr, u8 EpNum, u8 Direction)
This function primes an endpoint.
InstancePtr is pointer to the XUsbPs instance. EpNum is the number of the endpoint to receive data from. Direction is the direction of the endpoint (bitfield): XUSBPS_EP_DIRECTION_OUTXUSBPS_EP_DIRECTION_IN XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred.XST_INVALID_PARAM: Invalid parameter passed. None.
References XUsbPs_Config::BaseAddress, XUsbPs::Config, XUsbPs_DeviceConfig::NumEndpoints, XUSBPS_EP_DIRECTION_IN, XUSBPS_EP_DIRECTION_OUT, XUSBPS_EPPRIME_OFFSET, XUsbPs_WriteReg.
Referenced by XUsbPs_IntrHandler, XUsbPs_SetConfiguration.
int XUsbPs_EpGetSetupData(XUsbPs *InstancePtr, int EpNum, XUsbPs_SetupData *SetupDataPtr)
This function extracts the Setup Data from a given endpoint.
InstancePtr is a pointer to the XUsbPs instance of the controller. EpNum is the number of the endpoint to receive data from. SetupDataPtr is a pointer to the setup data structure to be filled. XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred. None.
References XUsbPs_Config::BaseAddress, XUsbPs_SetupData::bmRequestType, XUsbPs_SetupData::bRequest, XUsbPs::Config, XUsbPs::DeviceConfig, XUsbPs_EpOut::dQH, XUsbPs_DeviceConfig::Ep, XUsbPs_DeviceConfig::NumEndpoints, XUsbPs_Endpoint::Out, XUsbPs_SetupData::wIndex, XUsbPs_SetupData::wLength, XUsbPs_SetupData::wValue, XUsbPs_ClrSetupTripwire, XUSBPS_dQHSUB0, XUSBPS_dQHSUB1, XUSBPS_EPSTAT_OFFSET, XUsbPs_ReaddQH, XUsbPs_ReadReg, XUsbPs_SetSetupTripwire, XUsbPs_SetupTripwireIsSet, XUsbPs_WriteReg.
int XUsbPs_ReconfigureEp(XUsbPs *InstancePtr, XUsbPs_DeviceConfig *CfgPtr, int EpNum, unsigned short NewDirection, int DirectionChanged)
This function reconfigures one Ep corresponding to host's request of setting alternate interface.
The endpoint has been disabled before this call.Both QH and dTDs are updated for the new configuration. InstancePtr is a pointer to the XUsbPs instance of the controller. CfgPtr Pointer to the updated XUsbPs DEVICE configuration structure. EpNum The endpoint to be reconfigured. NewDirection The new transfer direction the endpoint. DirectionChanged A boolean value indicate whether the transfer direction has changed. XST_SUCCESS upon success, XST_FAILURE otherwise.
References XUsbPs_EpOut::dTDBufs, XUsbPs_EpOut::dTDCurr, XUsbPs_EpIn::dTDHead, XUsbPs_EpOut::dTDs, XUsbPs_EpIn::dTDs, XUsbPs_EpIn::dTDTail, XUsbPs_DeviceConfig::Ep, XUsbPs_DeviceConfig::EpCfg, XUsbPs_Endpoint::In, XUsbPs_EpSetup::NumBufs, XUsbPs_Endpoint::Out, XUsbPs_EpConfig::Out, XUSBPS_dTD_ALIGN, XUSBPS_EP_DIRECTION_IN, XUSBPS_EP_DIRECTION_OUT.
void XUsbPs_ResetHw(u32 BaseAddress)
This function perform the reset sequence to the given usbps interface by configuring the appropriate control bits in the usbps specific registers.
the usbps reset sequence involves the below steps Disable the interrupts Clear the status registers Apply the reset command and wait for reset complete status Update the relevant control registers with reset values BaseAddress of the interface N/A. None.
References XUSBPS_ASYNCLISTADDR_OFFSET, XUSBPS_CMD_OFFSET, XUSBPS_CMD_RST_MASK, XUSBPS_IER_OFFSET, XUSBPS_ISR_OFFSET, XUSBPS_LISTBASE_OFFSET, XUsbPs_ReadReg, XUsbPs_WriteReg.
static void XUsbPs_IntrHandleTX(XUsbPs *InstancePtr, u32 EpCompl)
This function handles TX buffer interrupts.
It is called by the interrupt when a transmit complete interrupt occurs. It returns buffers of completed descriptors to the caller. InstancePtr is a pointer to the XUsbPs instance of the controller. EpCompl is the Bit mask of endpoints that caused a transmit complete interrupt. None None.
static void XUsbPs_IntrHandleRX(XUsbPs *InstancePtr, u32 EpCompl)
This function handles RX buffer interrupts.
It is called by the interrupt when a receive complete interrupt occurs. It notifies the callback functions that have been registered with the individual endpoints that data has been received. InstancePtr Pointer to the XUsbPs instance of the controller. EpCompl Bit mask of endpoints that caused a receive complete interrupt. none
static void XUsbPs_IntrHandleReset(XUsbPs *InstancePtr, u32 IrqSts)
This function handles a RESET interrupt.
It will notify the interrupt handler callback of the RESET condition. InstancePtr is pointer to the XUsbPs instance of the controller IrqSts is the Interrupt status register content. To be passed on to the user. None None.
static void XUsbPs_IntrHandleEp0Setup(XUsbPs *InstancePtr)
This function handles a Setup Packet interrupt.
It will notify the interrupt handler callback of the RESET condition. InstancePtr is a pointer to the XUsbPs instance of the controller. None None
void XUsbPs_IntrHandler(void *HandlerRef)
This function is the first-level interrupt handler for the USB core.
All USB interrupts will be handled here. Depending on the type of the interrupt, second level interrupt handler may be called. Second level interrupt handlers will be registered by the user using the: XUsbPs_IntrSetHandler() and/or XUsbPs_EpSetHandler() functions. HandlerRef is a Reference passed to the interrupt register function. In our case this will be a pointer to the XUsbPs instance. None None
References XUsbPs_Config::BaseAddress, XUsbPs::Config, XUsbPs::HandlerFunc, XUsbPs::HandlerMask, XUsbPs::HandlerRef, XUSBPS_EP_DIRECTION_OUT, XUSBPS_EP_IN_MASK, XUSBPS_EP_OUT_MASK, XUSBPS_EPCOMPL_OFFSET, XUSBPS_EPNAKISR_OFFSET, XUsbPs_EpPrime, XUSBPS_EPSTAT_OFFSET, XUSBPS_ISR_OFFSET, XUSBPS_IXR_NAK_MASK, XUSBPS_IXR_UI_MASK, XUSBPS_IXR_UR_MASK, XUsbPs_ReadReg, XUsbPs_WriteReg.
Referenced by main.
int XUsbPs_IntrSetHandler(XUsbPs *InstancePtr, XUsbPs_IntrHandlerFunc CallBackFunc, void *CallBackRef, u32 Mask)
This function registers the user callback handler for controller (non-endpoint) interrupts.
InstancePtr is a pointer to the XUsbPs instance of the controller. CallBackFunc is the Callback function to register. CallBackFunc may be NULL to clear the entry. CallBackRef is the user data reference passed to the callback function. CallBackRef may be NULL. Mask is the User interrupt mask. Defines which interrupts will cause the callback to be called. XST_SUCCESS: Callback registered successfully.XST_FAILURE: Callback could not be registered. None.
References XUsbPs::HandlerFunc, XUsbPs::HandlerMask, XUsbPs::HandlerRef.
XUsbPs_Config* XUsbPs_LookupConfig(u32 BaseAddress)
Looks up the controller configuration based on the unique controller ID/BaseAddress.
A table contains the configuration info for each controller in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified controller ID/BaseAddress was not found. In XSCT/classic flow, DeviceID is used to look up the device configuration.
References XUsbPs_Config::Name.
Referenced by main.
XUSBPS_SPEED_UNKNOWN
XUSBPS_SPEED_LOW
XUSBPS_SPEED_FULL
XUSBPS_SPEED_HIGH
XUSBPS_STATE_ATTACHED
XUSBPS_STATE_POWERED
XUSBPS_STATE_DEFAULT
XUSBPS_STATE_ADDRESS
XUSBPS_STATE_CONFIGURED
XUSBPS_STATE_SUSPENDED
XUSBPS_MAX_PACKET_SIZE
Maximum value can be put into the queue head.
XUSBPS_dTDNLP
Endpoint Device Transfer Descriptor.
The dTD describes to the device controller the location and quantity of data to be sent/received for given transfer. The driver does not attempt to modify any field in an active dTD except the Next Link Pointer.Pointer to the next descriptor
XUSBPS_dTDTOKEN
Descriptor Token.
XUSBPS_dTDBPTR0
Buffer Pointer 0.
Referenced by XUsbPs_EpBufferReceive, XUsbPs_EpGetData.
XUSBPS_dTDBPTR1
Buffer Pointer 1.
XUSBPS_dTDBPTR2
Buffer Pointer 2.
XUSBPS_dTDBPTR3
Buffer Pointer 3.
XUSBPS_dTDBPTR4
Buffer Pointer 4.
XUSBPS_dTDBPTR
XUSBPS_dTDRSRVD
Reserved field.
XUSBPS_dTDUSERDATA
Reserved field.
Referenced by XUsbPs_EpBufferReceive, XUsbPs_EpGetData.
XUsbPs_dTDInvalidateCache
IMPORTANT NOTE:
Many of the following macros modify Device Queue Head (dQH) data structures and Device Transfer Descriptor (dTD) data structures. Those structures can potentially reside in CACHED memory. Therefore, it's the callers responsibility to ensure cache coherency by using provided XUsbPs_dQHInvalidateCache() XUsbPs_dQHFlushCache() XUsbPs_dTDInvalidateCache() XUsbPs_dTDFlushCache() function calls.
Referenced by XUsbPs_EpBufferReceive, XUsbPs_EpBufferRelease, XUsbPs_EpDataBufferReceive, XUsbPs_EpGetData.
XUsbPs_dTDFlushCache
XUsbPs_dQHInvalidateCache
XUsbPs_dQHFlushCache
XUsbPs_dTDSetTransferLen
This macro sets the Transfer Length for the given Transfer Descriptor.
dTDPtr is pointer to the dTD element. Len is the length to be set. Range: 0..16384 C-style signature: void XUsbPs_dTDSetTransferLen(u32 dTDPtr, u32 Len)
Referenced by XUsbPs_EpBufferReceive, XUsbPs_EpGetData.
XUsbPs_dTDGetNLP
This macro gets the Next Link pointer of the given Transfer Descriptor.
dTDPtr is pointer to the dTD element. TransferLength field of the descriptor. C-style signature: u32 XUsbPs_dTDGetTransferLen(u32 dTDPtr)
Referenced by XUsbPs_EpGetData.
XUsbPs_dTDSetNLP
This macro sets the Next Link pointer of the given Transfer Descriptor.
dTDPtr is a pointer to the dTD element. NLP is the Next Link Pointer C-style signature: void XUsbPs_dTDSetTransferLen(u32 dTDPtr, u32 Len)
XUsbPs_dTDGetTransferLen
This macro gets the Transfer Length for the given Transfer Descriptor.
dTDPtr is a pointer to the dTD element. TransferLength field of the descriptor. C-style signature: u32 XUsbPs_dTDGetTransferLen(u32 dTDPtr)
Referenced by XUsbPs_EpBufferReceive, XUsbPs_EpGetData.
XUsbPs_dTDSetIOC
This macro sets the Interrupt On Complete (IOC) bit for the given Transfer Descriptor.
dTDPtr is a pointer to the dTD element. C-style signature: void XUsbPs_dTDSetIOC(u32 dTDPtr)
Referenced by XUsbPs_EpBufferRelease.
XUsbPs_dTDSetTerminate
This macro sets the Terminate bit for the given Transfer Descriptor.
dTDPtr is a pointer to the dTD element. C-style signature: void XUsbPs_dTDSetTerminate(u32 dTDPtr)
XUsbPs_dTDClrTerminate
This macro clears the Terminate bit for the given Transfer Descriptor.
dTDPtr is a pointer to the dTD element. C-style signature: void XUsbPs_dTDClrTerminate(u32 dTDPtr)
Referenced by XUsbPs_EpBufferRelease.
XUsbPs_dTDIsActive
This macro checks if the given descriptor is active.
dTDPtr is a pointer to the dTD element. TRUE: The buffer is active.FALSE: The buffer is not active. C-style signature: int XUsbPs_dTDIsActive(u32 dTDPtr)
Referenced by XUsbPs_EpBufferReceive, XUsbPs_EpDataBufferReceive, XUsbPs_EpGetData.
XUsbPs_dTDSetActive
This macro sets the Active bit for the given Transfer Descriptor.
dTDPtr is a pointer to the dTD element. C-style signature: void XUsbPs_dTDSetActive(u32 dTDPtr)
Referenced by XUsbPs_EpBufferRelease.
XUsbPs_dTDSetMultO
This macro sets the multiplier bit for the Transfer Descriptor.
dTDPtr is a pointer to the dTD element. val is the multiplier value. C-style signature: void XUsbPs_dTDSetMultO(u32 dTDPtr, u32 val)
XUsbPs_ReaddTD
This macro reads the content of a field in a Transfer Descriptor.
dTDPtr is a pointer to the dTD element. Id is the field ID inside the dTD element to read. C-style signature: u32 XUsbPs_ReaddTD(u32 dTDPtr, u32 Id)
Referenced by XUsbPs_EpBufferReceive, XUsbPs_EpGetData.
XUsbPs_WritedTD
This macro writes a value to a field in a Transfer Descriptor.
dTDPtr is pointer to the dTD element. Id is the field ID inside the dTD element to read. Val is the value to write to the field. C-style signature: u32 XUsbPs_WritedTD(u32 dTDPtr, u32 Id, u32 Val)
Referenced by XUsbPs_EpBufferReceive, XUsbPs_EpGetData.
XUSBPS_dQHCFG
Endpoint Device Queue Head.
Device queue heads are arranged in an array in a continuous area of memory pointed to by the ENDPOINTLISTADDR pointer. The device controller will index into this array based upon the endpoint number received from the USB bus. All information necessary to respond to transactions for all primed transfers is contained in this list so the Device Controller can readily respond to incoming requests without having to traverse a linked list.The device Endpoint Queue Head (dQH) is where all transfers are managed. The dQH is a 48-byte data structure, but must be aligned on a 64-byte boundary. During priming of an endpoint, the dTD (device transfer descriptor) is copied into the overlay area of the dQH, which starts at the nextTD pointer DWord and continues through the end of the buffer pointers DWords. After a transfer is complete, the dTD status DWord is updated in the dTD pointed to by the currentTD pointer. While a packet is in progress, the overlay area of the dQH is used as a staging area for the dTD so that the Device Controller can access needed information with little minimal latency.Software must ensure that no interface data structure reachable by the Device Controller spans a 4K-page boundary. The first element of the Endpoint Queue Head List must be aligned on a 4K boundary.dQH Configuration
XUSBPS_dQHCPTR
dQH Current dTD Pointer
XUSBPS_dQHdTDNLP
dTD Next Link Ptr in dQH overlay
XUSBPS_dQHdTDTOKEN
dTD Token in dQH overlay
XUSBPS_dQHSUB0
USB dQH Setup Buffer 0.
Referenced by XUsbPs_EpGetSetupData.
XUSBPS_dQHSUB1
USB dQH Setup Buffer 1.
Referenced by XUsbPs_EpGetSetupData.
XUsbPs_dQHSetMaxPacketLen
This macro sets the Maximum Packet Length field of the give Queue Head.
dQHPtr is a pointer to the dQH element. Len is the length to be set. C-style signature: void XUsbPs_dQHSetMaxPacketLen(u32 dQHPtr, u32 Len)
XUsbPs_dQHSetIOS
This macro sets the Interrupt On Setup (IOS) bit for an endpoint.
dQHPtr is a pointer to the dQH element. C-style signature: void XUsbPs_dQHSetIOS(u32 dQHPtr)
XUsbPs_dQHClrIOS
This macro clears the Interrupt On Setup (IOS) bit for an endpoint.
dQHPtr is a pointer to the dQH element. C-style signature: void XUsbPs_dQHClrIOS(u32 dQHPtr)
XUsbPs_dQHEnableZLT
This macro enables Zero Length Termination for the endpoint.
dQHPtr is a pointer to the dQH element. C-style signature: void XUsbPs_dQHEnableZLT(u32 dQHPtr)
XUsbPs_dQHDisableZLT
This macro disables Zero Length Termination for the endpoint.
dQHPtr is a pointer to the dQH element. C-style signature: void XUsbPs_dQHDisableZLT(u32 dQHPtr)
XUsbPs_ReaddQH
This macro reads the content of a field in a Queue Head.
dQHPtr is a pointer to the dQH element. Id is the Field ID inside the dQH element to read. C-style signature: u32 XUsbPs_ReaddQH(u32 dQHPtr, u32 Id)
Referenced by XUsbPs_EpGetSetupData.
XUsbPs_WritedQH
This macro writes a value to a field in a Queue Head.
dQHPtr is a pointer to the dQH element. Id is the Field ID inside the dQH element to read. Val is the Value to write to the field. C-style signature: u32 XUsbPs_WritedQH(u32 dQHPtr, u32 Id, u32 Val)
XUSBPS_RESET_TIMEOUT
XUSBPS_REG_SPACING
XUSBPS_dQH_BASE_ALIGN
Mask for All IRQ Enable masks.
< Alignment of the Device Queue Head List BASE. Alignment of a Device Queue Head structure.
Referenced by XUsbPs_ConfigureDevice.
XUSBPS_dQH_ALIGN
Alignment of a Device Transfer Descriptor structure.
XUSBPS_dTD_ALIGN
Size of one RX buffer for a OUT Transfer Descriptor.
Referenced by XUsbPs_EpBufferRelease, XUsbPs_ReconfigureEp.
XUSBPS_dTD_BUF_SIZE
Maximum size of one RX/TX buffer.
XUSBPS_dTD_BUF_MAX_SIZE
Alignment requirement for Transfer Descriptor buffers.
XUSBPS_dTD_BUF_ALIGN
XUsbPs_ReadReg
This macro reads the given register.
BaseAddress is the base address for the USB registers. RegOffset is the register offset to be read. The 32-bit value of the register. C-style signature: u32 XUsbPs_ReadReg(u32 BaseAddress, u32 RegOffset)
Referenced by XUsbPs_DeviceReset, XUsbPs_EpGetSetupData, XUsbPs_IntrHandler, XUsbPs_Reset, XUsbPs_ResetHw.
XUsbPs_WriteReg
This macro writes the given register.
BaseAddress is the the base address for the USB registers. RegOffset is the register offset to be written. Data is the the 32-bit value to write to the register. None. C-style signature: void XUsbPs_WriteReg(u32 BaseAddress, u32 RegOffset, u32 Data)
Referenced by XUsbPs_ConfigureDevice, XUsbPs_DeviceReset, XUsbPs_EpGetSetupData, XUsbPs_EpPrime, XUsbPs_IntrHandler, XUsbPs_Reset, XUsbPs_ResetHw, XUsbPs_SetDeviceAddress.