xusbps_endpoint.c
static void XUsbPs_EpListInit(XUsbPs_DeviceConfig *DevCfgPtr)
This function initializes the endpoint pointer data structure.
The function sets up the local data structure with the aligned addresses for the Queue Head and Transfer Descriptors. DevCfgPtr is pointer to the XUsbPs DEVICE configuration structure. none Endpoints of type XUSBPS_EP_TYPE_NONE are not used in the system. Therefore no memory is reserved for them.
static void XUsbPs_dQHInit(XUsbPs_DeviceConfig *DevCfgPtr)
This function initializes the Queue Head List in memory.
DevCfgPtr is a pointer to the XUsbPs DEVICE configuration structure. None None.
static int XUsbPs_dTDInit(XUsbPs_DeviceConfig *DevCfgPtr)
This function initializes the Transfer Descriptors lists in memory.
DevCfgPtr is a pointer to the XUsbPs DEVICE configuration structure. XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred.
static int XUsbPs_dTDAttachBuffer(XUsbPs_dTD *dTDPtr, const u8 *BufferPtr, u32 BufferLen)
This function associates a buffer with a Transfer Descriptor.
The function will take care of splitting the buffer into multiple 4kB aligned segments if the buffer happens to span one or more 4kB pages. dTDIndex is a pointer to the Transfer Descriptor BufferPtr is pointer to the buffer to link to the descriptor. BufferLen is the length of the buffer. XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred.XST_USB_BUF_TOO_BIG: The provided buffer is bigger than the maximum allowed buffer size (16k). Cache invalidation and flushing needs to be handler by the caller of this function.
static void XUsbPs_dQHSetMaxPacketLenISO(XUsbPs_dQH *dQHPtr, u32 Len)
This function set the Max PacketLen for the queue head for isochronous EP.
If the max packet length is greater than XUSBPS_MAX_PACKET_SIZE, then Mult bits are set to reflect that. dQHPtr is a pointer to the dQH element. Len is the Length to be set.
static void XUsbPs_dQHReinitEp(XUsbPs_DeviceConfig *DevCfgPtr, int EpNum, unsigned short NewDirection)
This function re-initializes the Queue Head List in memory.
The endpoint 1 has been disabled before this call. DevCfgPtr Pointer to the updated XUsbPs DEVICE configuration structure. EpNum The endpoint to be reconfigured. NewDirection The new transfer direction of endpoint 1 none
static int XUsbPs_dTDReinitEp(XUsbPs_DeviceConfig *DevCfgPtr, int EpNum, unsigned short NewDirection)
This function re-initializes the Transfer Descriptors lists in memory.
The endpoint has been disabled before the call. The transfer descriptors list pointer has been initialized too. DevCfgPtr Pointer to the XUsbPs DEVICE configuration structure. EpNum The endpoint to be reconfigured. NewDirection The new transfer direction of endpoint 1 XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred.
static int XUsbPs_EpQueueRequest(XUsbPs *InstancePtr, u8 EpNum, const u8 *BufferPtr, u32 BufferLen, u8 ReqZero)
This function sends a given data buffer and also sends ZLT packet if it is requested.
InstancePtr is a pointer to XUsbPs instance of the controller. EpNum is the number of the endpoint to receive data from. BufferPtr is a pointer to the buffer to send. BufferLen is the Buffer length. ReqZero is the XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred.XST_USB_BUF_TOO_BIG: Provided buffer is too big (>16kB).XST_USB_NO_DESC_AVAILABLE: No TX descriptor is available.
int XUsbPs_ConfigureDevice(XUsbPs *InstancePtr, const XUsbPs_DeviceConfig *CfgPtr)
This function configures the DEVICE side of the controller.
The caller needs to pass in the desired configuration (e.g. number of endpoints) and a DMAable buffer that will hold the Queue Head List and the Transfer Descriptors. The required size for this buffer can be obtained by the caller using the: XUsbPs_DeviceMemRequired() macro. InstancePtr is a pointer to the XUsbPs instance of the controller. CfgPtr is a pointer to the configuration structure that contains the desired DEVICE side configuration. XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred. The caller may configure the controller for both, DEVICE and HOST side.
References XUsbPs_Config::BaseAddress, XUsbPs::Config, XUsbPs::DeviceConfig, XUsbPs_DeviceConfig::DMAMemPhys, XUsbPs_DeviceConfig::PhysAligned, XUSBPS_dQH_BASE_ALIGN, XUSBPS_EPLISTADDR_OFFSET, XUSBPS_MODE_OFFSET, XUSBPS_MODE_SLOM_MASK, XUSBPS_OTGCSR_OFFSET, XUSBPS_OTGSC_OT_MASK, XUsbPs_Reset, XUsbPs_SetBits, XUsbPs_WriteReg.
Referenced by main.
int XUsbPs_EpBufferSend(XUsbPs *InstancePtr, u8 EpNum, const u8 *BufferPtr, u32 BufferLen)
This function sends a given data buffer.
InstancePtr is a pointer to XUsbPs instance of the controller. EpNum is the number of the endpoint to receive data from. BufferPtr is a pointer to the buffer to send. BufferLen is the Buffer length. XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred.XST_USB_BUF_TOO_BIG: Provided buffer is too big (>16kB).XST_USB_NO_DESC_AVAILABLE: No TX descriptor is available.
References XUsbPs_DeviceConfig::NumEndpoints.
Referenced by XUsbPs_ClassReq, XUsbPs_HandleStorageReq.
int XUsbPs_EpBufferSendWithZLT(XUsbPs *InstancePtr, u8 EpNum, const u8 *BufferPtr, u32 BufferLen)
This function sends a given data buffer and also zero length packet if the Bufferlen is in multiples of endpoint max packet size.
InstancePtr is a pointer to XUsbPs instance of the controller. EpNum is the number of the endpoint to receive data from. BufferPtr is a pointer to the buffer to send. BufferLen is the Buffer length. XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred.XST_USB_BUF_TOO_BIG: Provided buffer is too big (>16kB).XST_USB_NO_DESC_AVAILABLE: No TX descriptor is available.
References XUsbPs::DeviceConfig, XUsbPs_DeviceConfig::EpCfg, XUsbPs_EpConfig::In, XUsbPs_EpSetup::MaxPacketSize, XUsbPs_DeviceConfig::NumEndpoints.
void XUsbPs_EpGetData(XUsbPs *InstancePtr, u8 EpNum, u32 BufferLen)
This function receives a data buffer from the endpoint of the given endpoint number and pass it to the application.
InstancePtr is a pointer to the XUsbPs instance of the controller. EpNum is the number of the endpoint to receive data from. BufferLen is holding the buffer length. None. None.
References XUsbPs_EpOut::BufferPtr, XUsbPs_EpSetup::BufSize, XUsbPs_EpOut::BytesTxed, XUsbPs::DeviceConfig, XUsbPs_EpOut::dTDCurr, XUsbPs_DeviceConfig::Ep, XUsbPs_DeviceConfig::EpCfg, XUsbPs_EpOut::HandlerIsoFunc, XUsbPs_EpOut::HandlerRef, XUsbPs_EpSetup::MaxPacketSize, XUsbPs_EpOut::MemAlloted, XUsbPs_Endpoint::Out, XUsbPs_EpConfig::Out, XUsbPs_EpOut::RequestedBytes, XUSBPS_dTDBPTR0, XUsbPs_dTDGetNLP, XUsbPs_dTDGetTransferLen, XUsbPs_dTDInvalidateCache, XUsbPs_dTDIsActive, XUsbPs_dTDSetTransferLen, XUSBPS_dTDUSERDATA, XUsbPs_EpBufferRelease, XUsbPs_ReaddTD, XUsbPs_WritedTD.
Referenced by XUsbPs_EpDataBufferReceive.
int XUsbPs_EpBufferReceive(XUsbPs *InstancePtr, u8 EpNum, u8 **BufferPtr, u32 *BufferLenPtr, u32 *Handle)
This function receives a data buffer from the endpoint of the given endpoint number.
InstancePtr is a pointer to the XUsbPs instance of the controller. EpNum is the number of the endpoint to receive data from. BufferPtr (OUT param) is a pointer to the buffer pointer to hold the reference of the data buffer. BufferLenPtr (OUT param) is a pointer to the integer that will hold the buffer length. Handle is the opaque handle to be used when the buffer is released. XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred.XST_USB_NO_BUF: No buffer available. After handling the data in the buffer, the user MUST release the buffer using the Handle by calling the XUsbPs_EpBufferRelease() function.
References XUsbPs_EpSetup::BufSize, XUsbPs::DeviceConfig, XUsbPs_EpOut::dTDCurr, XUsbPs_DeviceConfig::Ep, XUsbPs_DeviceConfig::EpCfg, XUsbPs_DeviceConfig::NumEndpoints, XUsbPs_Endpoint::Out, XUsbPs_EpConfig::Out, XUSBPS_dTDBPTR0, XUsbPs_dTDGetTransferLen, XUsbPs_dTDInvalidateCache, XUsbPs_dTDIsActive, XUsbPs_dTDSetTransferLen, XUSBPS_dTDUSERDATA, XUsbPs_ReaddTD, XUsbPs_WritedTD.
void XUsbPs_EpBufferRelease(u32 Handle)
This function returns a previously received data buffer to the driver.
Handle is a pointer to the buffer that is returned. None.
References XUSBPS_dTD_ALIGN, XUsbPs_dTDClrTerminate, XUsbPs_dTDInvalidateCache, XUsbPs_dTDSetActive, XUsbPs_dTDSetIOC.
Referenced by XUsbPs_EpGetData.
s32 XUsbPs_EpDataBufferReceive(XUsbPs *InstancePtr, u8 EpNum, u8 *BufferPtr, u32 BufferLen)
This function receives a data buffer from the endpoint of the given endpoint number.
InstancePtr is a pointer to the XUsbPs instance of the controller. EpNum is the number of the endpoint to receive data from. BufferPtr (OUT param) is a pointer to the buffer pointer to hold the reference of the data buffer. BufferLen (OUT param) is a pointer to the integer that will hold the buffer length. XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred.XST_USB_NO_BUF: No buffer available.
References XUsbPs_EpOut::BufferPtr, XUsbPs_EpOut::BytesTxed, XUsbPs::DeviceConfig, XUsbPs_EpOut::dTDCurr, XUsbPs_DeviceConfig::Ep, XUsbPs_EpOut::MemAlloted, XUsbPs_DeviceConfig::NumEndpoints, XUsbPs_Endpoint::Out, XUsbPs_EpOut::RequestedBytes, XUsbPs_dTDInvalidateCache, XUsbPs_dTDIsActive, XUsbPs_EpGetData.
Referenced by XUsbPs_ClassReq.
int XUsbPs_EpSetHandler(XUsbPs *InstancePtr, u8 EpNum, u8 Direction, XUsbPs_EpHandlerFunc CallBackFunc, void *CallBackRef)
This function sets the handler for endpoint events.
InstancePtr is a pointer to the XUsbPs instance of the controller. EpNum is the number of the endpoint to receive data from. Direction is the direction of the endpoint (bitfield): XUSBPS_EP_DIRECTION_OUTXUSBPS_EP_DIRECTION_IN CallBackFunc is the Handler callback function. Can be NULL if the user wants to disable the handler entry. CallBackRef is the user definable data pointer that will be passed back if the handler is called. May be NULL. XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred.XST_INVALID_PARAM: Invalid parameter passed. The user can disable a handler by setting the callback function pointer to NULL.
References XUsbPs::DeviceConfig, XUsbPs_DeviceConfig::Ep, XUsbPs_EpOut::HandlerRef, XUsbPs_EpIn::HandlerRef, XUsbPs_Endpoint::In, XUsbPs_DeviceConfig::NumEndpoints, XUsbPs_Endpoint::Out, XUSBPS_EP_DIRECTION_IN, XUSBPS_EP_DIRECTION_OUT.
Referenced by main.
s32 XUsbPs_EpSetIsoHandler(XUsbPs *InstancePtr, u8 EpNum, u8 Direction, XUsbPs_EpIsoHandlerFunc CallBackFunc)
This function sets the handler for ISO endpoint events.
InstancePtr is a pointer to the XUsbPs instance of the controller. EpNum is the number of the endpoint to receive data from. Direction is the direction of the endpoint (bitfield): XUSBPS_EP_DIRECTION_OUTXUSBPS_EP_DIRECTION_IN CallBackFunc is the Handler callback function. Can be NULL if the user wants to disable the handler entry. XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred.XST_INVALID_PARAM: Invalid parameter passed. The user can disable a handler by setting the callback function pointer to NULL.
References XUsbPs::DeviceConfig, XUsbPs_DeviceConfig::Ep, XUsbPs_EpOut::HandlerIsoFunc, XUsbPs_EpIn::HandlerIsoFunc, XUsbPs_EpOut::HandlerRef, XUsbPs_EpIn::HandlerRef, XUsbPs_Endpoint::In, XUsbPs_DeviceConfig::NumEndpoints, XUsbPs_Endpoint::Out, XUSBPS_EP_DIRECTION_IN, XUSBPS_EP_DIRECTION_OUT.
Referenced by main.
int XUsbPs_EpPrime(XUsbPs *InstancePtr, u8 EpNum, u8 Direction)
This function primes an endpoint.
InstancePtr is pointer to the XUsbPs instance. EpNum is the number of the endpoint to receive data from. Direction is the direction of the endpoint (bitfield): XUSBPS_EP_DIRECTION_OUTXUSBPS_EP_DIRECTION_IN XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred.XST_INVALID_PARAM: Invalid parameter passed. None.
References XUsbPs_Config::BaseAddress, XUsbPs::Config, XUsbPs_DeviceConfig::NumEndpoints, XUSBPS_EP_DIRECTION_IN, XUSBPS_EP_DIRECTION_OUT, XUSBPS_EPPRIME_OFFSET, XUsbPs_WriteReg.
Referenced by XUsbPs_IntrHandler, XUsbPs_SetConfiguration.
int XUsbPs_EpGetSetupData(XUsbPs *InstancePtr, int EpNum, XUsbPs_SetupData *SetupDataPtr)
This function extracts the Setup Data from a given endpoint.
InstancePtr is a pointer to the XUsbPs instance of the controller. EpNum is the number of the endpoint to receive data from. SetupDataPtr is a pointer to the setup data structure to be filled. XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred. None.
References XUsbPs_Config::BaseAddress, XUsbPs_SetupData::bmRequestType, XUsbPs_SetupData::bRequest, XUsbPs::Config, XUsbPs::DeviceConfig, XUsbPs_EpOut::dQH, XUsbPs_DeviceConfig::Ep, XUsbPs_DeviceConfig::NumEndpoints, XUsbPs_Endpoint::Out, XUsbPs_SetupData::wIndex, XUsbPs_SetupData::wLength, XUsbPs_SetupData::wValue, XUsbPs_ClrSetupTripwire, XUSBPS_dQHSUB0, XUSBPS_dQHSUB1, XUSBPS_EPSTAT_OFFSET, XUsbPs_ReaddQH, XUsbPs_ReadReg, XUsbPs_SetSetupTripwire, XUsbPs_SetupTripwireIsSet, XUsbPs_WriteReg.
int XUsbPs_ReconfigureEp(XUsbPs *InstancePtr, XUsbPs_DeviceConfig *CfgPtr, int EpNum, unsigned short NewDirection, int DirectionChanged)
This function reconfigures one Ep corresponding to host's request of setting alternate interface.
The endpoint has been disabled before this call.Both QH and dTDs are updated for the new configuration. InstancePtr is a pointer to the XUsbPs instance of the controller. CfgPtr Pointer to the updated XUsbPs DEVICE configuration structure. EpNum The endpoint to be reconfigured. NewDirection The new transfer direction the endpoint. DirectionChanged A boolean value indicate whether the transfer direction has changed. XST_SUCCESS upon success, XST_FAILURE otherwise.
References XUsbPs_EpOut::dTDBufs, XUsbPs_EpOut::dTDCurr, XUsbPs_EpIn::dTDHead, XUsbPs_EpOut::dTDs, XUsbPs_EpIn::dTDs, XUsbPs_EpIn::dTDTail, XUsbPs_DeviceConfig::Ep, XUsbPs_DeviceConfig::EpCfg, XUsbPs_Endpoint::In, XUsbPs_EpSetup::NumBufs, XUsbPs_Endpoint::Out, XUsbPs_EpConfig::Out, XUSBPS_dTD_ALIGN, XUSBPS_EP_DIRECTION_IN, XUSBPS_EP_DIRECTION_OUT.