xusbps.h
XUSBPS_TIMEOUT_COUNTER
XUSBPS_EP_DIRECTION_IN
Endpoint direction IN.
Referenced by main, XUsbPs_Ch9HandleSetupPacket, XUsbPs_ClassReq, XUsbPs_EpPrime, XUsbPs_EpSetHandler, XUsbPs_EpSetIsoHandler, XUsbPs_ReconfigureEp, XUsbPs_SetConfiguration, XUsbPs_SetConfigurationApp, XUsbPs_SetInterfaceHandler.
XUSBPS_EP_DIRECTION_OUT
Endpoint direction OUT.
Referenced by main, XUsbPs_Ch9HandleSetupPacket, XUsbPs_ClassReq, XUsbPs_EpPrime, XUsbPs_EpSetHandler, XUsbPs_EpSetIsoHandler, XUsbPs_IntrHandler, XUsbPs_ReconfigureEp, XUsbPs_SetConfiguration, XUsbPs_SetConfigurationApp, XUsbPs_SetInterfaceHandler.
XUSBPS_EP_TYPE_NONE
Endpoint is not used.
XUSBPS_EP_TYPE_CONTROL
Endpoint for Control Transfers.
Referenced by main.
XUSBPS_EP_TYPE_ISOCHRONOUS
Endpoint for isochronous data.
Referenced by main.
XUSBPS_EP_TYPE_BULK
Endpoint for BULK Transfers.
XUSBPS_EP_TYPE_INTERRUPT
Endpoint for interrupt Transfers.
ENDPOINT_MAXP_LENGTH
Endpoint Max Packet Length in DeviceConfig is a coded value, ch9.6.6.
ENDPOINT_MAXP_MULT_MASK
ENDPOINT_MAXP_MULT_SHIFT
XUSBPS_EP_STS_ADDRESS
Address of controller.
XUSBPS_EP_STS_CONTROLLER_STATE
Current controller state.
XUSBPS_DEFAULT_ALT_SETTING
The default alternate setting is 0.
Referenced by XUsbPs_CfgInitialize.
XUSBPS_EP_EVENT_SETUP_DATA_RECEIVED
Setup data has been received on the endpoint.
XUSBPS_EP_EVENT_DATA_RX
Data frame has been received on the endpoint.
XUSBPS_EP_EVENT_DATA_TX
Data frame has been sent on the endpoint.
XUSBPS_SPEED_UNKNOWN
XUSBPS_SPEED_LOW
XUSBPS_SPEED_FULL
XUSBPS_SPEED_HIGH
XUSBPS_STATE_ATTACHED
XUSBPS_STATE_POWERED
XUSBPS_STATE_DEFAULT
XUSBPS_STATE_ADDRESS
XUSBPS_STATE_CONFIGURED
XUSBPS_STATE_SUSPENDED
XUSBPS_MAX_PACKET_SIZE
Maximum value can be put into the queue head.
XUsbPs_GetFrameNum
This macro returns the current frame number.
InstancePtr is a pointer to the XUsbPs instance of the controller. The current frame number. C-style signature: u32 XUsbPs_GetFrameNum(const XUsbPs *InstancePtr)
XUsbPs_Start
This macro starts the USB engine.
InstancePtr is a pointer to the XUsbPs instance of the controller. C-style signature: void XUsbPs_Start(XUsbPs *InstancePtr)
Referenced by main.
XUsbPs_Stop
This macro stops the USB engine.
InstancePtr is a pointer to the XUsbPs instance of the controller. C-style signature: void XUsbPs_Stop(XUsbPs *InstancePtr)
Referenced by XUsbPs_DeviceReset.
XUsbPs_ForceFS
This macro forces the USB engine to be in Full Speed (FS) mode.
InstancePtr is a pointer to the XUsbPs instance of the controller. C-style signature: void XUsbPs_ForceFS(XUsbPs *InstancePtr)
XUsbPs_StartTimer0
This macro starts the USB Timer 0, with repeat option for period of one second.
InstancePtr is a pointer to XUsbPs instance of the controller. Interval is the interval for Timer0 to generate an interrupt C-style signature: void XUsbPs_StartTimer0(XUsbPs *InstancePtr, u32 Interval)
XUsbPs_StopTimer0
This macro stops Timer 0.
InstancePtr is a pointer to XUsbPs instance of the controller. C-style signature: void XUsbPs_StopTimer0(XUsbPs *InstancePtr)
XUsbPs_ReadTimer0
This macro reads Timer 0.
InstancePtr is a pointer to XUsbPs instance of the controller. C-style signature: void XUsbPs_ReadTimer0(XUsbPs *InstancePtr)
XUsbPs_RemoteWakeup
This macro force remote wakeup on host.
InstancePtr is a pointer to XUsbPs instance of the controller. C-style signature: void XUsbPs_RemoteWakeup(XUsbPs *InstancePtr)
XUsbPs_EpEnable
This macro enables the given endpoint for the given direction.
InstancePtr is a pointer to the XUsbPs instance of the controller. EpNum is number of the endpoint to enable. Dir is direction of the endpoint (bitfield): XUSBPS_EP_DIRECTION_OUTXUSBPS_EP_DIRECTION_IN C-style signature: void XUsbPs_EpEnable(XUsbPs *InstancePtr, u8 EpNum, u8 Dir)
Referenced by XUsbPs_SetConfiguration.
XUsbPs_EpDisable
This macro disables the given endpoint for the given direction.
InstancePtr is a pointer to the XUsbPs instance of the controller. EpNum is the number of the endpoint to disable. Dir is the direction of the endpoint (bitfield): XUSBPS_EP_DIRECTION_OUTXUSBPS_EP_DIRECTION_IN C-style signature: void XUsbPs_EpDisable(XUsbPs *InstancePtr, u8 EpNum, u8 Dir)
Referenced by XUsbPs_SetConfigurationApp, XUsbPs_SetInterfaceHandler.
XUsbPs_EpStall
This macro stalls the given endpoint for the given direction, and flush the buffers.
InstancePtr is a pointer to the XUsbPs instance of the controller. EpNum is number of the endpoint to stall. Dir is the direction of the endpoint (bitfield): XUSBPS_EP_DIRECTION_OUTXUSBPS_EP_DIRECTION_IN C-style signature: void XUsbPs_EpStall(XUsbPs *InstancePtr, u8 EpNum, u8 Dir)
Referenced by XUsbPs_Ch9HandleSetupPacket, XUsbPs_ClassReq.
XUsbPs_EpUnStall
This macro unstalls the given endpoint for the given direction.
InstancePtr is a pointer to the XUsbPs instance of the controller. EpNum is the Number of the endpoint to unstall. Dir is the Direction of the endpoint (bitfield): XUSBPS_EP_DIRECTION_OUTXUSBPS_EP_DIRECTION_IN C-style signature: void XUsbPs_EpUnStall(XUsbPs *InstancePtr, u8 EpNum, u8 Dir)
XUsbPs_EpFlush
This macro flush an endpoint upon interface disable.
InstancePtr is a pointer to the XUsbPs instance of the controller. EpNum is the number of the endpoint to flush. Dir is the direction of the endpoint (bitfield): XUSBPS_EP_DIRECTION_OUTXUSBPS_EP_DIRECTION_IN C-style signature: void XUsbPs_EpFlush(XUsbPs *InstancePtr, u8 EpNum, u8 Dir)
XUsbPs_IntrEnable
This macro enables the interrupts defined by the bit mask.
InstancePtr is a pointer to XUsbPs instance of the controller. IntrMask is the Bit mask of interrupts to be enabled. C-style signature: void XUsbPs_IntrEnable(XUsbPs *InstancePtr, u32 IntrMask)
Referenced by main.
XUsbPs_IntrDisable
This function disables the interrupts defined by the bit mask.
InstancePtr is a pointer to XUsbPs instance of the controller. IntrMask is a Bit mask of interrupts to be disabled. C-style signature: void XUsbPs_IntrDisable(XUsbPs *InstancePtr, u32 IntrMask)
XUsbPs_NakIntrEnable
This macro enables the endpoint NAK interrupts defined by the bit mask.
InstancePtr is a pointer to XUsbPs instance of the controller. NakIntrMask is the Bit mask of endpoint NAK interrupts to be enabled. C-style signature: void XUsbPs_NakIntrEnable(XUsbPs *InstancePtr, u32 NakIntrMask)
XUsbPs_NakIntrDisable
This macro disables the endpoint NAK interrupts defined by the bit mask.
InstancePtr is a pointer to XUsbPs instance of the controller. NakIntrMask is a Bit mask of endpoint NAK interrupts to be disabled. C-style signature: void XUsbPs_NakIntrDisable(XUsbPs *InstancePtr, u32 NakIntrMask)
XUsbPs_NakIntrClear
This function clears the endpoint NAK interrupts status defined by the bit mask.
InstancePtr is a pointer to XUsbPs instance of the controller. NakIntrMask is the Bit mask of endpoint NAK interrupts to be cleared. C-style signature: void XUsbPs_NakIntrClear(XUsbPs *InstancePtr, u32 NakIntrMask)
XUsbPs_SetIntrThreshold
This macro sets the Interrupt Threshold value in the control register.
InstancePtr is a pointer to XUsbPs instance of the controller. Threshold is the Interrupt threshold to be set. Allowed values: XUSBPS_CMD_ITHRESHOLD_0 - Immediate interruptXUSBPS_CMD_ITHRESHOLD_1 - 1 FrameXUSBPS_CMD_ITHRESHOLD_2 - 2 FramesXUSBPS_CMD_ITHRESHOLD_4 - 4 FramesXUSBPS_CMD_ITHRESHOLD_8 - 8 FramesXUSBPS_CMD_ITHRESHOLD_16 - 16 FramesXUSBPS_CMD_ITHRESHOLD_32 - 32 FramesXUSBPS_CMD_ITHRESHOLD_64 - 64 Frames C-style signature: void XUsbPs_SetIntrThreshold(XUsbPs *InstancePtr, u8 Threshold)
XUsbPs_SetSetupTripwire
This macro sets the Tripwire bit in the USB command register.
InstancePtr is a pointer to XUsbPs instance of the controller. C-style signature: void XUsbPs_SetTripwire(XUsbPs *InstancePtr)
Referenced by XUsbPs_EpGetSetupData.
XUsbPs_ClrSetupTripwire
This macro clears the Tripwire bit in the USB command register.
InstancePtr is a pointer to XUsbPs instance of the controller. C-style signature: void XUsbPs_ClrTripwire(XUsbPs *InstancePtr)
Referenced by XUsbPs_EpGetSetupData.
XUsbPs_SetupTripwireIsSet
This macro checks if the Tripwire bit in the USB command register is set.
InstancePtr is a pointer to XUsbPs instance of the controller. TRUE: The tripwire bit is still set.FALSE: The tripwire bit has been cleared. C-style signature: int XUsbPs_TripwireIsSet(XUsbPs *InstancePtr)
Referenced by XUsbPs_EpGetSetupData.
XUsbPs_SetBits
This macro sets the given bit mask in the register.
InstancePtr is a pointer to XUsbPs instance of the controller. RegOffset is the register offset to be written. Bits is the Bits to be set in the register None. C-style signature: void XUsbPs_SetBits(u32 BaseAddress, u32 RegOffset, u32 Bits)
Referenced by XUsbPs_ConfigureDevice, XUsbPs_SetConfiguration.
XUsbPs_ClrBits
This macro clears the given bits in the register.
InstancePtr is a pointer to XUsbPs instance of the controller. RegOffset is the register offset to be written. Bits are the bits to be cleared in the register None. C-style signature: void XUsbPs_ClrBits(u32 BaseAddress, u32 RegOffset, u32 Bits)
typedef void(* XUsbPs_EpHandlerFunc)(void *CallBackRef, u8 EpNum, u8 EventType, void *Data))(void *CallBackRef, u8 EpNum, u8 EventType, void *Data)
typedef void(* XUsbPs_EpIsoHandlerFunc)(void *CallBackRef, u32 RequestedBytes, u32 BytesTxed))(void *CallBackRef, u32 RequestedBytes, u32 BytesTxed)
typedef void(* XUsbPs_IntrHandlerFunc)(void *CallBackRef, u32 IrqMask))(void *CallBackRef, u32 IrqMask)
typedef u8 XUsbPs_dQH[XUSBPS_dQH_ALIGN][XUSBPS_dQH_ALIGN]
typedef u8 XUsbPs_dTD[XUSBPS_dTD_ALIGN][XUSBPS_dTD_ALIGN]
typedef XUsbPs_Config Usb_Config
int XUsbPs_CfgInitialize(XUsbPs *InstancePtr, const XUsbPs_Config *ConfigPtr, u32 BaseAddress)
Setup / Initialize functions.
Implemented in file xusbps.cSetup / Initialize functions.The initialization entails: Initialize all members of the XUsbPs structure. InstancePtr is a pointer to XUsbPs instance of the controller. ConfigPtr is a pointer to a XUsbPs_Config configuration structure. This structure will contain the requested configuration for the device. Typically, this is a local structure and the content of which will be copied into the configuration structure within XUsbPs. VirtBaseAddress is the base address of the device. For systems with virtual memory, this address must be the virtual address of the device. For systems that do not support virtual memory this address should be the physical address of the device. For backwards compatibility NULL may be passed in systems that do not support virtual memory (deprecated). XST_SUCCESS no errors occurred.XST_FAILURE an error occurred during initialization. After calling XUsbPs_CfgInitialize() the controller IS NOT READY for use. Before the controller can be used its DEVICE parameters must be configured. See xusbps.h for details.
References XUsbPs::Config, XUsbPs_Config::BaseAddress, XUsbPs::CurrentAltSetting, XUSBPS_DEFAULT_ALT_SETTING, XUsbPs::HandlerFunc.
Referenced by XUsbPs_CfgInit.
int XUsbPs_ConfigureDevice(XUsbPs *InstancePtr, const XUsbPs_DeviceConfig *CfgPtr)
This function configures the DEVICE side of the controller.
The caller needs to pass in the desired configuration (e.g. number of endpoints) and a DMAable buffer that will hold the Queue Head List and the Transfer Descriptors. The required size for this buffer can be obtained by the caller using the: XUsbPs_DeviceMemRequired() macro. InstancePtr is a pointer to the XUsbPs instance of the controller. CfgPtr is a pointer to the configuration structure that contains the desired DEVICE side configuration. XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred. The caller may configure the controller for both, DEVICE and HOST side.
References XUsbPs::DeviceConfig, XUsbPs_DeviceConfig::PhysAligned, XUsbPs_DeviceConfig::DMAMemPhys, XUSBPS_dQH_BASE_ALIGN, XUsbPs_Reset, XUsbPs_WriteReg, XUsbPs::Config, XUsbPs_Config::BaseAddress, XUSBPS_EPLISTADDR_OFFSET, XUSBPS_MODE_SLOM_MASK, XUSBPS_MODE_OFFSET, XUsbPs_SetBits, XUSBPS_OTGCSR_OFFSET, XUSBPS_OTGSC_OT_MASK.
Referenced by main.
int XUsbPs_Reset(XUsbPs *InstancePtr)
Common functions used for DEVICE/HOST mode.
Common functions used for DEVICE/HOST mode.All the configuration registers are reset to their default values. The function waits until the reset operation is complete or for a certain duration within which the reset operation is expected to be completed. InstancePtr is a pointer to XUsbPs instance of the controller. XST_SUCCESS Reset operation completed successfully.XST_FAILURE Reset operation timed out. None.
References XUsbPs_WriteReg, XUsbPs::Config, XUsbPs_Config::BaseAddress, XUSBPS_CMD_OFFSET, XUSBPS_CMD_RST_MASK, XUsbPs_ReadReg.
Referenced by XUsbPs_ConfigureDevice.
void XUsbPs_DeviceReset(XUsbPs *InstancePtr)
This function performs device reset, device is stopped at the end.
InstancePtr is a pointer to XUsbPs instance of the controller. None. None.
References XUsbPs_WriteReg, XUsbPs::Config, XUsbPs_Config::BaseAddress, XUSBPS_EPSTAT_OFFSET, XUsbPs_ReadReg, XUSBPS_EPCOMPL_OFFSET, XUSBPS_EPPRIME_OFFSET, XUSBPS_EP_ALL_MASK, XUSBPS_EPFLUSH_OFFSET, XUsbPs_Stop, XUSBPS_CMD_OFFSET, XUSBPS_CMD_RST_MASK.
int XUsbPs_BusReset(XUsbPs *InstancePtr)
DEVICE mode specific functions.
int XUsbPs_SetDeviceAddress(XUsbPs *InstancePtr, u8 Address)
This functions sets the controller's DEVICE address.
It also sets the advance bit so the controller will wait for the next IN-ACK before the new address takes effect. InstancePtr is a pointer to XUsbPs instance of the controller. Address is the Address of the device. XST_SUCCESS: Address set successfully.XST_FAILURE: An error occurred.XST_INVALID_PARAM: Invalid parameter passed, e.g. address value too big. None.
References XUSBPS_DEVICEADDR_MAX, XUsbPs_WriteReg, XUsbPs::Config, XUsbPs_Config::BaseAddress, XUSBPS_DEVICEADDR_OFFSET, XUSBPS_DEVICEADDR_ADDR_SHIFT, XUSBPS_DEVICEADDR_DEVICEAADV_MASK.
int XUsbPs_Suspend(const XUsbPs *InstancePtr)
Handling Suspend and Resume.
Implemented in xusbps.cHandling Suspend and Resume.In order to conserve power, USB devices automatically enter the suspended state when the device has observed no bus traffic for a specified period. When suspended, the USB device maintains any internal status, including its address and configuration. Attached devices must be prepared to suspend at any time they are powered, regardless of if they have been assigned a non-default address, are configured, or neither. Bus activity may cease due to the host entering a suspend mode of its own. In addition, a USB device shall also enter the suspended state when the hub port it is attached to is disabled.A USB device exits suspend mode when there is bus activity. A USB device may also request the host to exit suspend mode or selective suspend by using electrical signaling to indicate remote wakeup. The ability of a device to signal remote wakeup is optional. If the USB device is capable of remote wakeup signaling, the device must support the ability of the host to enable and disable this capability. When the device is reset, remote wakeup signaling must be disabled. InstancePtr is a pointer to XUsbPs instance of the controller. XST_SUCCESS if the USB device has entered Suspend mode successfullyXST_FAILURE on any error None.
int XUsbPs_Resume(const XUsbPs *InstancePtr)
USB Resume.
If the USB controller is suspended, its operation is resumed when any non-idle signaling is received on its upstream facing port. InstancePtr is a pointer to XUsbPs instance of the controller. XST_SUCCESS if the USB device has Resumed successfullyXST_FAILURE on any error None.
int XUsbPs_RequestHostResume(const XUsbPs *InstancePtr)
USB Assert Resume.
InstancePtr is a pointer to XUsbPs instance of the controller. XST_SUCCESS if the USB device has Resumed successfullyXST_FAILURE on any error None.
int XUsbPs_EpBufferSend(XUsbPs *InstancePtr, u8 EpNum, const u8 *BufferPtr, u32 BufferLen)
This function sends a given data buffer.
InstancePtr is a pointer to XUsbPs instance of the controller. EpNum is the number of the endpoint to receive data from. BufferPtr is a pointer to the buffer to send. BufferLen is the Buffer length. XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred.XST_USB_BUF_TOO_BIG: Provided buffer is too big (>16kB).XST_USB_NO_DESC_AVAILABLE: No TX descriptor is available.
References XUsbPs_DeviceConfig::NumEndpoints.
Referenced by XUsbPs_ClassReq, XUsbPs_HandleStorageReq.
int XUsbPs_EpBufferSendWithZLT(XUsbPs *InstancePtr, u8 EpNum, const u8 *BufferPtr, u32 BufferLen)
This function sends a given data buffer and also zero length packet if the Bufferlen is in multiples of endpoint max packet size.
InstancePtr is a pointer to XUsbPs instance of the controller. EpNum is the number of the endpoint to receive data from. BufferPtr is a pointer to the buffer to send. BufferLen is the Buffer length. XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred.XST_USB_BUF_TOO_BIG: Provided buffer is too big (>16kB).XST_USB_NO_DESC_AVAILABLE: No TX descriptor is available.
References XUsbPs_DeviceConfig::NumEndpoints, XUsbPs::DeviceConfig, XUsbPs_DeviceConfig::EpCfg, XUsbPs_EpConfig::In, XUsbPs_EpSetup::MaxPacketSize.
int XUsbPs_EpBufferReceive(XUsbPs *InstancePtr, u8 EpNum, u8 **BufferPtr, u32 *BufferLenPtr, u32 *Handle)
This function receives a data buffer from the endpoint of the given endpoint number.
InstancePtr is a pointer to the XUsbPs instance of the controller. EpNum is the number of the endpoint to receive data from. BufferPtr (OUT param) is a pointer to the buffer pointer to hold the reference of the data buffer. BufferLenPtr (OUT param) is a pointer to the integer that will hold the buffer length. Handle is the opaque handle to be used when the buffer is released. XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred.XST_USB_NO_BUF: No buffer available. After handling the data in the buffer, the user MUST release the buffer using the Handle by calling the XUsbPs_EpBufferRelease() function.
References XUsbPs_DeviceConfig::NumEndpoints, XUsbPs::DeviceConfig, XUsbPs_DeviceConfig::Ep, XUsbPs_Endpoint::Out, XUsbPs_dTDInvalidateCache, XUsbPs_EpOut::dTDCurr, XUsbPs_dTDIsActive, XUsbPs_DeviceConfig::EpCfg, XUsbPs_EpConfig::Out, XUsbPs_ReaddTD, XUSBPS_dTDUSERDATA, XUsbPs_EpSetup::BufSize, XUsbPs_dTDGetTransferLen, XUsbPs_WritedTD, XUSBPS_dTDBPTR0, XUsbPs_dTDSetTransferLen.
void XUsbPs_EpBufferRelease(u32 Handle)
This function returns a previously received data buffer to the driver.
Handle is a pointer to the buffer that is returned. None.
References XUSBPS_dTD_ALIGN, XUsbPs_dTDInvalidateCache, XUsbPs_dTDClrTerminate, XUsbPs_dTDSetActive, XUsbPs_dTDSetIOC.
Referenced by XUsbPs_EpGetData.
int XUsbPs_EpSetHandler(XUsbPs *InstancePtr, u8 EpNum, u8 Direction, XUsbPs_EpHandlerFunc CallBackFunc, void *CallBackRef)
This function sets the handler for endpoint events.
InstancePtr is a pointer to the XUsbPs instance of the controller. EpNum is the number of the endpoint to receive data from. Direction is the direction of the endpoint (bitfield): XUSBPS_EP_DIRECTION_OUTXUSBPS_EP_DIRECTION_IN CallBackFunc is the Handler callback function. Can be NULL if the user wants to disable the handler entry. CallBackRef is the user definable data pointer that will be passed back if the handler is called. May be NULL. XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred.XST_INVALID_PARAM: Invalid parameter passed. The user can disable a handler by setting the callback function pointer to NULL.
References XUsbPs_DeviceConfig::NumEndpoints, XUsbPs::DeviceConfig, XUsbPs_DeviceConfig::Ep, XUSBPS_EP_DIRECTION_OUT, XUsbPs_Endpoint::Out, XUsbPs_EpOut::HandlerRef, XUSBPS_EP_DIRECTION_IN, XUsbPs_Endpoint::In, XUsbPs_EpIn::HandlerRef.
Referenced by main.
s32 XUsbPs_EpSetIsoHandler(XUsbPs *InstancePtr, u8 EpNum, u8 Direction, XUsbPs_EpIsoHandlerFunc CallBackFunc)
This function sets the handler for ISO endpoint events.
InstancePtr is a pointer to the XUsbPs instance of the controller. EpNum is the number of the endpoint to receive data from. Direction is the direction of the endpoint (bitfield): XUSBPS_EP_DIRECTION_OUTXUSBPS_EP_DIRECTION_IN CallBackFunc is the Handler callback function. Can be NULL if the user wants to disable the handler entry. XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred.XST_INVALID_PARAM: Invalid parameter passed. The user can disable a handler by setting the callback function pointer to NULL.
References XUsbPs_DeviceConfig::NumEndpoints, XUsbPs::DeviceConfig, XUsbPs_DeviceConfig::Ep, XUSBPS_EP_DIRECTION_OUT, XUsbPs_Endpoint::Out, XUsbPs_EpOut::HandlerIsoFunc, XUsbPs_EpOut::HandlerRef, XUSBPS_EP_DIRECTION_IN, XUsbPs_Endpoint::In, XUsbPs_EpIn::HandlerIsoFunc, XUsbPs_EpIn::HandlerRef.
Referenced by main.
int XUsbPs_EpGetSetupData(XUsbPs *InstancePtr, int EpNum, XUsbPs_SetupData *SetupDataPtr)
This function extracts the Setup Data from a given endpoint.
InstancePtr is a pointer to the XUsbPs instance of the controller. EpNum is the number of the endpoint to receive data from. SetupDataPtr is a pointer to the setup data structure to be filled. XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred. None.
References XUsbPs_DeviceConfig::NumEndpoints, XUsbPs::DeviceConfig, XUsbPs_DeviceConfig::Ep, XUsbPs_Endpoint::Out, XUsbPs_SetSetupTripwire, XUsbPs_EpOut::dQH, XUsbPs_ReaddQH, XUSBPS_dQHSUB0, XUSBPS_dQHSUB1, XUsbPs_SetupTripwireIsSet, XUsbPs_WriteReg, XUsbPs::Config, XUsbPs_Config::BaseAddress, XUSBPS_EPSTAT_OFFSET, XUsbPs_ClrSetupTripwire, XUsbPs_SetupData::bmRequestType, XUsbPs_SetupData::bRequest, XUsbPs_SetupData::wValue, XUsbPs_SetupData::wIndex, XUsbPs_SetupData::wLength, XUsbPs_ReadReg.
int XUsbPs_EpPrime(XUsbPs *InstancePtr, u8 EpNum, u8 Direction)
This function primes an endpoint.
InstancePtr is pointer to the XUsbPs instance. EpNum is the number of the endpoint to receive data from. Direction is the direction of the endpoint (bitfield): XUSBPS_EP_DIRECTION_OUTXUSBPS_EP_DIRECTION_IN XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred.XST_INVALID_PARAM: Invalid parameter passed. None.
References XUsbPs_DeviceConfig::NumEndpoints, XUSBPS_EP_DIRECTION_OUT, XUSBPS_EP_DIRECTION_IN, XUsbPs_WriteReg, XUsbPs::Config, XUsbPs_Config::BaseAddress, XUSBPS_EPPRIME_OFFSET.
Referenced by XUsbPs_SetConfiguration, XUsbPs_IntrHandler.
int XUsbPs_ReconfigureEp(XUsbPs *InstancePtr, XUsbPs_DeviceConfig *CfgPtr, int EpNum, unsigned short NewDirection, int DirectionChanged)
This function reconfigures one Ep corresponding to host's request of setting alternate interface.
The endpoint has been disabled before this call.Both QH and dTDs are updated for the new configuration. InstancePtr is a pointer to the XUsbPs instance of the controller. CfgPtr Pointer to the updated XUsbPs DEVICE configuration structure. EpNum The endpoint to be reconfigured. NewDirection The new transfer direction the endpoint. DirectionChanged A boolean value indicate whether the transfer direction has changed. XST_SUCCESS upon success, XST_FAILURE otherwise.
References XUsbPs_DeviceConfig::Ep, XUsbPs_DeviceConfig::EpCfg, XUSBPS_EP_DIRECTION_OUT, XUsbPs_Endpoint::Out, XUsbPs_EpOut::dTDs, XUsbPs_Endpoint::In, XUsbPs_EpIn::dTDs, XUSBPS_dTD_ALIGN, XUsbPs_EpConfig::Out, XUsbPs_EpSetup::NumBufs, XUsbPs_EpOut::dTDBufs, XUSBPS_EP_DIRECTION_IN, XUsbPs_EpIn::dTDHead, XUsbPs_EpIn::dTDTail, XUsbPs_EpOut::dTDCurr.
void XUsbPs_IntrHandler(void *InstancePtr)
This function is the first-level interrupt handler for the USB core.
All USB interrupts will be handled here. Depending on the type of the interrupt, second level interrupt handler may be called. Second level interrupt handlers will be registered by the user using the: XUsbPs_IntrSetHandler() and/or XUsbPs_EpSetHandler() functions. HandlerRef is a Reference passed to the interrupt register function. In our case this will be a pointer to the XUsbPs instance. None None
References XUsbPs_ReadReg, XUsbPs::Config, XUsbPs_Config::BaseAddress, XUSBPS_ISR_OFFSET, XUsbPs_WriteReg, XUSBPS_IXR_NAK_MASK, XUSBPS_EPNAKISR_OFFSET, XUSBPS_IXR_UR_MASK, XUsbPs::HandlerMask, XUsbPs::HandlerFunc, XUsbPs::HandlerRef, XUSBPS_IXR_UI_MASK, XUSBPS_EPSTAT_OFFSET, XUsbPs_EpPrime, XUSBPS_EP_DIRECTION_OUT, XUSBPS_EPCOMPL_OFFSET, XUSBPS_EP_OUT_MASK, XUSBPS_EP_IN_MASK.
Referenced by main.
int XUsbPs_IntrSetHandler(XUsbPs *InstancePtr, XUsbPs_IntrHandlerFunc CallBackFunc, void *CallBackRef, u32 Mask)
This function registers the user callback handler for controller (non-endpoint) interrupts.
InstancePtr is a pointer to the XUsbPs instance of the controller. CallBackFunc is the Callback function to register. CallBackFunc may be NULL to clear the entry. CallBackRef is the user data reference passed to the callback function. CallBackRef may be NULL. Mask is the User interrupt mask. Defines which interrupts will cause the callback to be called. XST_SUCCESS: Callback registered successfully.XST_FAILURE: Callback could not be registered. None.
References XUsbPs::HandlerFunc, XUsbPs::HandlerRef, XUsbPs::HandlerMask.
void XUsbPs_EpGetData(XUsbPs *InstancePtr, u8 EpNum, u32 BufferLen)
This function receives a data buffer from the endpoint of the given endpoint number and pass it to the application.
InstancePtr is a pointer to the XUsbPs instance of the controller. EpNum is the number of the endpoint to receive data from. BufferLen is holding the buffer length. None. None.
References XUsbPs::DeviceConfig, XUsbPs_DeviceConfig::Ep, XUsbPs_Endpoint::Out, XUsbPs_DeviceConfig::EpCfg, XUsbPs_EpConfig::Out, XUsbPs_dTDInvalidateCache, XUsbPs_EpOut::dTDCurr, XUsbPs_ReaddTD, XUSBPS_dTDUSERDATA, XUsbPs_EpSetup::BufSize, XUsbPs_dTDGetTransferLen, XUsbPs_EpOut::BufferPtr, XUsbPs_EpOut::BytesTxed, XUsbPs_WritedTD, XUSBPS_dTDBPTR0, XUsbPs_dTDSetTransferLen, XUsbPs_EpBufferRelease, XUsbPs_dTDGetNLP, XUsbPs_EpOut::RequestedBytes, XUsbPs_EpSetup::MaxPacketSize, XUsbPs_EpOut::MemAlloted, XUsbPs_EpOut::HandlerIsoFunc, XUsbPs_EpOut::HandlerRef, XUsbPs_dTDIsActive.
Referenced by XUsbPs_EpDataBufferReceive.
s32 XUsbPs_EpDataBufferReceive(XUsbPs *InstancePtr, u8 EpNum, u8 *BufferPtr, u32 BufferLen)
This function receives a data buffer from the endpoint of the given endpoint number.
InstancePtr is a pointer to the XUsbPs instance of the controller. EpNum is the number of the endpoint to receive data from. BufferPtr (OUT param) is a pointer to the buffer pointer to hold the reference of the data buffer. BufferLen (OUT param) is a pointer to the integer that will hold the buffer length. XST_SUCCESS: The operation completed successfully.XST_FAILURE: An error occurred.XST_USB_NO_BUF: No buffer available.
References XUsbPs_DeviceConfig::NumEndpoints, XUsbPs::DeviceConfig, XUsbPs_DeviceConfig::Ep, XUsbPs_Endpoint::Out, XUsbPs_EpOut::RequestedBytes, XUsbPs_EpOut::BytesTxed, XUsbPs_EpOut::BufferPtr, XUsbPs_EpOut::MemAlloted, XUsbPs_dTDInvalidateCache, XUsbPs_EpOut::dTDCurr, XUsbPs_dTDIsActive, XUsbPs_EpGetData.
Referenced by XUsbPs_ClassReq.
XUsbPs_Config* XUsbPs_LookupConfig(u32 BaseAddress)
Looks up the controller configuration based on the unique controller ID/BaseAddress.
A table contains the configuration info for each controller in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified controller ID/BaseAddress was not found. In XSCT/classic flow, DeviceID is used to look up the device configuration.
References XUsbPs_Config::Name.
Referenced by main.