xusbps_ch9.c
u8 Response ALIGNMENT_CACHELINE
static void XUsbPs_StdDevReq(XUsbPs *InstancePtr, XUsbPs_SetupData *SetupData)
This function handles a standard device request.
InstancePtr is a pointer to XUsbPs instance of the controller. SetupData is a pointer to the data structure containing the setup request. None. None.
static int XUsbPs_HandleVendorReq(XUsbPs *InstancePtr, XUsbPs_SetupData *SetupData)
This function handles a vendor request.
InstancePtr is a pointer to XUsbPs instance of the controller. SetupData is a pointer to the data structure containing the setup request. XST_SUCCESS if successful.XST_FAILURE if an Error occurred. This function is a template to handle vendor request for control IN and control OUT endpoints. The control OUT endpoint can receive only 64 bytes of data per dTD. For receiving more than 64 bytes of vendor data on control OUT endpoint, change the buffer size of the control OUT endpoint. Otherwise the results are unexpected.
void XUsbPs_ClassReq(XUsbPs *InstancePtr, XUsbPs_SetupData *SetupData)
This function is called by Chapter9 handler when class request is received from Host.
InstancePtr is pointer to Usb_DevData instance. SetupData is the setup packet received from Host. None. This function is called by Chapter9 handler when class request is received from Host. InstancePtr is a pointer to XUsbPs instance of the controller. SetupData is the setup data structure containing the setup request. None. None.
Referenced by XUsbPs_Ch9HandleSetupPacket.
u32 XUsbPs_Ch9SetupDevDescReply(u8 *BufPtr, u32 BufLen)
This function returns the device descriptor for the device.
InstancePtr is a pointer to the Usb_DevData instance. BufPtr is pointer to the buffer that is to be filled with the descriptor. BufLen is the size of the provided buffer. Length of the descriptor in the buffer on success. 0 on error. BufPtr is pointer to the buffer that is to be filled with the descriptor. BufLen is the size of the provided buffer. Length of the descriptor in the buffer on success. 0 on error.
u32 XUsbPs_Ch9SetupCfgDescReply(u8 *BufPtr, u32 BufLen)
This function returns the configuration descriptor for the device.
InstancePtr is a pointer to the Usb_DevData instance. BufPtr is the pointer to the buffer that is to be filled with the descriptor. BufLen is the size of the provided buffer. Length of the descriptor in the buffer on success. 0 on error. BufPtr is the pointer to the buffer that is to be filled with the descriptor. BufLen is the size of the provided buffer. Length of the descriptor in the buffer on success. 0 on error.
u32 XUsbPs_Ch9SetupStrDescReply(u8 *BufPtr, u32 BufLen, u8 Index)
This function returns a string descriptor for the given index.
InstancePtr is a pointer to the Usb_DevData instance. BufPtr is a pointer to the buffer that is to be filled with the descriptor. BufLen is the size of the provided buffer. Index is the index of the string for which the descriptor is requested. Length of the descriptor in the buffer on success. 0 on error. BufPtr is a pointer to the buffer that is to be filled with the descriptor. BufLen is the size of the provided buffer. Index is the index of the string for which the descriptor is requested. Length of the descriptor in the buffer on success. 0 on error.
void XUsbPs_SetConfiguration(XUsbPs *InstancePtr, int ConfigIdx)
Changes State of Core to USB configured State.
InstancePtr is a pointer to the Usb_DevData instance. Ctrl is a pointer to the Setup packet data. XST_SUCCESS else XST_FAILURE None. Changes State of Core to USB configured State. InstancePtr is a pointer to XUsbPs instance of the controller. ConfigIdx is the Index of the desired configuration. None
void XUsbPs_SetConfigurationApp(XUsbPs *InstancePtr, XUsbPs_SetupData *SetupData)
This function is called by Chapter9 handler when SET_CONFIGURATION command is received from Host.
InstancePtr is pointer to Usb_DevData instance. SetupData is the setup packet received from Host. XST_SUCCESS if successful,XST_FAILURE if unsuccessful. Non control endpoints must be enabled after SET_CONFIGURATION command since hardware clears all previously enabled endpoints except control endpoints when this command is received. InstancePtr is pointer to XUsbPs instance of the controller. SetupData is the setup packet received from Host. XST_SUCCESS if successful,XST_FAILURE if unsuccessful. Non control endpoints must be enabled after SET_CONFIGURATION command since hardware clears all previously enabled endpoints except control endpoints when this command is received.
void XUsbPs_SetInterfaceHandler(XUsbPs *InstancePtr, XUsbPs_SetupData *SetupData)
This function is called by Chapter9 handler when SET_CONFIGURATION command or SET_INTERFACE command is received from Host.
InstancePtr is pointer to Usb_DevData instance. SetupData is the setup packet received from Host. Non control endpoints must be enabled after SET_INTERFACE command since hardware clears all previously enabled endpoints except control endpoints when this command is received. InstancePtr is pointer to XUsbPs instance of the controller. SetupData is the setup packet received from Host.
int XUsbPs_Ch9HandleSetupPacket(XUsbPs *InstancePtr, XUsbPs_SetupData *SetupData)
This function handles a Setup Data packet from the host.
InstancePtr is a pointer to XUsbPs instance of the controller. SetupData is the structure containing the setup request. XST_SUCCESS if the function is successful.XST_FAILURE if an Error occurred. None.
References XUsbPs_SetupData::bmRequestType, XUsbPs_SetupData::bRequest, XUsbPs_ClassReq, XUSBPS_EP_DIRECTION_IN, XUSBPS_EP_DIRECTION_OUT, XUsbPs_EpStall, XUSBPS_REQ_TYPE_MASK.
void XUsbPs_SetConfigDone(void *InstancePtr, u8 Flag)
Set the Config state.
InstancePtr is a private member of Usb_DevData instance. Flag is the config value. None. None.
Referenced by XUsbPs_SetConfiguration, XUsbPs_SetConfigurationApp.
u8 XUsbPs_GetConfigDone(void *InstancePtr)
Get the Config state.
InstancePtr is a private member of Usb_DevData instance. Current configuration value None.