// Copyright (C) 2024 - 2025 Advanced Micro Devices, Inc. All Rights Reserved.
#ifndef _SENSOR_CMD_H_
#define _SENSOR_CMD_H_

#include "mbox_api.h"
#include <return_codes.h>


typedef struct VMix_buff {
	uint32_t baseAddress;
} VMix_input_buffer;


typedef enum {
	MB_CMD_RES_SUCCESS,
	MB_CMD_GET_SUCCESS,
	/*---------------------------------------API CMD------------------------------------*/
	APU_2_RPU_MB_CMD_CREATE_INSTANCE,
	APU_2_RPU_MB_CMD_DESTORY,
	APU_2_RPU_MB_CMD_LOAD_CALIBRATION,
	APU_2_RPU_MB_CMD_SET_OUT_FORMAT,
	APU_2_RPU_MB_CMD_SET_IN_FORMAT,
	APU_2_RPU_MB_CMD_GET_OUT_FORMAT,
	APU_2_RPU_MB_CMD_GET_IN_FORMAT,
	APU_2_RPU_MB_CMD_SET_ISP_WINDOW,
	APU_2_RPU_MB_CMD_GET_ISP_WINDOW,
	APU_2_RPU_MB_CMD_CONNECT_CAMERA,
	APU_2_RPU_MB_CMD_DISCONNECT_CAMERA,
	APU_2_RPU_MB_CMD_START_STREAMING,
	APU_2_RPU_MB_CMD_STOP_STREAMING,
	APU_2_RPU_MB_CMD_SET_PATH_STREAMING,
	APU_2_RPU_MB_CMD_GET_PATH_STREAMING,
	APU_2_RPU_MB_CMD_ALLOC_RES_MEMORY,
	APU_2_RPU_MB_CMD_FREE_RES_MEMORY,
	APU_2_RPU_MB_CMD_WRITE_REGISTER,
	APU_2_RPU_MB_CMD_READ_REGISTER,
	APU_2_RPU_MB_CMD_IMAGE_SET_METADATA,
	APU_2_RPU_MB_CMD_NrRelocEnable,
	APU_2_RPU_MB_CMD_NrRelocDisable,
	APU_2_RPU_MB_CMD_SwFastStop,
	APU_2_RPU_MB_CMD_HwSystemReset,
	APU_2_RPU_MB_CMD_SwFastStart,
	APU_2_RPU_MB_CMD_SET_ISP_LOW_POWER,
	APU_2_RPU_MB_CMD_ModuleAutoCtrlSetConfig,
	APU_2_RPU_MB_CMD_ModuleAutoCtrlGetConfig,

	/*--------------------------------------Buffer API CMD----------------------------------*/
	APU_2_RPU_MB_CMD_INIT_BUF_CHAIN,
	APU_2_RPU_MB_CMD_DEINIT_BUF_CHAIN,
	APU_2_RPU_MB_CMD_GET_BUFFER_SIZE,
	APU_2_RPU_MB_CMD_CREATE_BUFFER_POOL,
	APU_2_RPU_MB_CMD_DESTORY_BUFFER_POOL,
	APU_2_RPU_MB_CMD_SETUP_BUF_MGMT,
	APU_2_RPU_MB_CMD_RELEASE_BUF_MGMT,
	APU_2_RPU_MB_CMD_DEQUE_BUFFER,
	APU_2_RPU_MB_CMD_ENQUE_BUFFER,
	APU_2_RPU_MB_CMD_GET_BUFFER_MGMT,

	/*----------------------------------------SENSOR API-------------------------------------*/
	APU_2_RPU_MB_CMD_SENSOR_OPEN,
	APU_2_RPU_MB_CMD_SENSOR_DRV_HANDLE_REG,
	APU_2_RPU_MB_CMD_SENSOR_DRV_HANDLE_UNREG,
	APU_2_RPU_MB_CMD_SENSOR_CLOSE,
	APU_2_RPU_MB_CMD_SENSOR_MAPPING,
	APU_2_RPU_MB_CMD_SENSOR_QUERY,
	APU_2_RPU_MB_CMD_SENSOR_GET_INFO,
	APU_2_RPU_MB_CMD_SENSOR_SET_TP,  // TEST PATTERN
	APU_2_RPU_MB_CMD_SENSOR_SET_REG,
	APU_2_RPU_MB_CMD_SENSOR_GET_REG,
	APU_2_RPU_MB_CMD_SENSOR_SET_FRAMERATE,
	APU_2_RPU_MB_CMD_SENSOR_GET_FRAMERATE,
	APU_2_RPU_MB_CMD_SENSOR_GET_MODE_INFO,
	APU_2_RPU_MB_CMD_SENSOR_GET_STATUS,
	APU_2_RPU_MB_CMD_SENSOR_SET_GAIN,
	APU_2_RPU_MB_CMD_SENSOR_GET_GAIN,
	APU_2_RPU_MB_CMD_SENSOR_SET_EXP_CTL,
	APU_2_RPU_MB_CMD_SENSOR_GET_EXP_CTL,
	APU_2_RPU_MB_CMD_SENSOR_SetFocusPositon,
	APU_2_RPU_MB_CMD_SENSOR_GetFocusPositon,
	APU_2_RPU_MB_CMD_SENSOR_SET_STREAMING,
	APU_2_RPU_MB_CMD_SENSOR_GET_OPT_INFO,
	APU_2_RPU_MB_CMD_SENSOR_GET_METADATA_ATTR,
	APU_2_RPU_MB_CMD_SENSOR_SET_METADATA_ATTR,
	APU_2_RPU_MB_CMD_SENSOR_GET_METADATA_WIN,
	APU_2_RPU_MB_CMD_SENSOR_GET_NUMBER,
	APU_2_RPU_MB_CMD_SENSOR_GET_LIST_INFO,
	APU_2_RPU_MB_CMD_SENSOR_GET_ConnectPortInfo,
	APU_2_RPU_MB_CMD_SENSOR_SET_BLS,
	APU_2_RPU_MB_CMD_SENSOR_GET_BLS,
	APU_2_RPU_MB_CMD_SENSOR_SET_WB,
	APU_2_RPU_MB_CMD_SENSOR_GET_WB,

	/*----------------------------------------FUSA API----------------------------------------*/
	APU_2_RPU_MB_CMD_Fusa_FaultInject_Enable,
	APU_2_RPU_MB_CMD_Fusa_Ecc_Enable,
	APU_2_RPU_MB_CMD_Fusa_Ecc_Disable,
	APU_2_RPU_MB_CMD_Fusa_Pixel_Count_Enable,
	APU_2_RPU_MB_CMD_Fusa_Pixel_Count_Disable,
	APU_2_RPU_MB_CMD_SET_Fusa_Pixel_Count,
	APU_2_RPU_MB_CMD_GET_Fusa_Pixel_Count,
	APU_2_RPU_MB_CMD_Fusa_Timeout_Enable,
	APU_2_RPU_MB_CMD_Fusa_Timeout_Disable,
	APU_2_RPU_MB_CMD_Fusa_Bist_Enable,
	APU_2_RPU_MB_CMD_Fusa_Bist_Disable,
	APU_2_RPU_MB_CMD_Fusa_Bist_Power_Up_Enable,
	APU_2_RPU_MB_CMD_Fusa_Bist_Power_Up_Disable,
	APU_2_RPU_MB_CMD_Fusa_Crc_Enable,
	APU_2_RPU_MB_CMD_Fusa_Crc_Disable,
	APU_2_RPU_MB_CMD_SET_Fusa_Crc,
	APU_2_RPU_MB_CMD_GET_Fusa_Crc,
	APU_2_RPU_MB_CMD_GET_Fusa_Bist,
	APU_2_RPU_MB_CMD_Fusa_Register_EventCb,
	APU_2_RPU_MB_CMD_Fusa_RESET,
	APU_2_RPU_MB_CMD_Fusa_GET_VERSION,

	/*----------------------------------------TPG API----------------------------------------*/
	APU_2_RPU_MB_CMD_TPG_SetCfg,
	APU_2_RPU_MB_CMD_TPG_GetCfg,
	APU_2_RPU_MB_CMD_TPG_Enable,
	APU_2_RPU_MB_CMD_TPG_Disable,
	APU_2_RPU_MB_CMD_TPG_GetVersion,

	/*---------------------------------------2DNR API V5_2-----------------------------------*/
	APU_2_RPU_MB_CMD_2DNR_ENABLE,
	APU_2_RPU_MB_CMD_2DNR_DISABLE,
	APU_2_RPU_MB_CMD_2DNR_SET_CONFIG,
	APU_2_RPU_MB_CMD_2DNR_GET_CONFIG,
	APU_2_RPU_MB_CMD_2DNR_LUMA_ENABLE,
	APU_2_RPU_MB_CMD_2DNR_LUMA_DISABLE,
	APU_2_RPU_MB_CMD_2DNR_GET_STATUS,
	APU_2_RPU_MB_CMD_2DNR_GET_VERSION,
	APU_2_RPU_MB_CMD_2DNR_RESET,

	/*--------------------------------------------AE API------------------------------------*/
	RPU_2_APU_MB_CMD_REGISTER_AELIB,
	RPU_2_APU_MB_CMD_UNREGISTER_AELIB,
	APU_2_RPU_MB_CMD_AE_SET_CONFIG,
	APU_2_RPU_MB_CMD_AE_GET_CONFIG,
	APU_2_RPU_MB_CMD_AE_SET_MODE,
	APU_2_RPU_MB_CMD_AE_GET_MODE,
	APU_2_RPU_MB_CMD_AE_SET_ROI,
	APU_2_RPU_MB_CMD_AE_GET_ROI,
	APU_2_RPU_MB_CMD_AE_SET_EXPV3_ROI,
	APU_2_RPU_MB_CMD_AE_GET_EXPV3_ROI,
	APU_2_RPU_MB_CMD_AE_SET_FrontGround_CFG,
	APU_2_RPU_MB_CMD_AE_GET_FrontGround_CFG,
	APU_2_RPU_MB_CMD_AE_ENABLE,
	APU_2_RPU_MB_CMD_AE_DISABLE,
	APU_2_RPU_MB_CMD_AE_RESET,
	APU_2_RPU_MB_CMD_AE_GET_STATUS,
	APU_2_RPU_MB_CMD_AE_GET_HISTOGRAM,
	APU_2_RPU_MB_CMD_AE_GET_LUMINANCE,
	APU_2_RPU_MB_CMD_AE_GET_OBJECT_REGION,
	APU_2_RPU_MB_CMD_AE_SET_EXP_TBL,
	APU_2_RPU_MB_CMD_AE_GET_EXP_TBL,
	APU_2_RPU_MB_CMD_AE_GET_VERSION,
	APU_2_RPU_MB_CMD_AE_GET_RES,

	/*--------------------------------------------AF API V1-----------------------------------*/
	APU_2_RPU_MB_CMD_AF_REGISTER,
	APU_2_RPU_MB_CMD_AF_UNREGISTER,
	APU_2_RPU_MB_CMD_AF_SET_MODE,
	APU_2_RPU_MB_CMD_AF_GET_MODE,
	APU_2_RPU_MB_CMD_AF_SET_CONFIG,
	APU_2_RPU_MB_CMD_AF_GET_CONFIG,
	APU_2_RPU_MB_CMD_AF_SET_ROI_INDEX,
	APU_2_RPU_MB_CMD_AF_GET_ROI_INDEX,
	APU_2_RPU_MB_CMD_AF_SET_AFM_V11_ROI,
	APU_2_RPU_MB_CMD_AF_GET_AFM_V11_ROI,
	APU_2_RPU_MB_CMD_AF_SET_AFM_V3_WEIGHT,
	APU_2_RPU_MB_CMD_AF_GET_AFM_V3_WEIGHT,
	APU_2_RPU_MB_CMD_AF_ENABLE,
	APU_2_RPU_MB_CMD_AF_DISABLE,
	APU_2_RPU_MB_CMD_AF_GET_STATUS,
	APU_2_RPU_MB_CMD_AF_GET_VERSION,
	APU_2_RPU_MB_CMD_AF_RESET,

	/*--------------------------------------------AFM API -----------------------------------*/
	APU_2_RPU_MB_CMD_AFM_SET_THRESHOLD,
	APU_2_RPU_MB_CMD_AFM_GET_THRESHOLD,
	APU_2_RPU_MB_CMD_AFM_GET_STATISTICS,
	APU_2_RPU_MB_CMD_AFM_SET_MEASURE_WINDOW,
	APU_2_RPU_MB_CMD_AFM_GET_MEASURE_WINDOW,
	APU_2_RPU_MB_CMD_AFM_ENABLE,
	APU_2_RPU_MB_CMD_AFM_DISABLE,
	APU_2_RPU_MB_CMD_AFM_GET_STATUS,
	APU_2_RPU_MB_CMD_AFM_GET_VERSION,
	APU_2_RPU_MB_CMD_AFM_RESET,

	/*---------------------------------------------AWB API--------------------------------------*/
	APU_2_RPU_MB_CMD_REGISTER_AWB_LIB,
	APU_2_RPU_MB_CMD_UNREGISTER_AWB_LIB,
	APU_2_RPU_MB_CMD_AWB_SET_CONFIG,
	APU_2_RPU_MB_CMD_AWB_GET_CONFIG,
	APU_2_RPU_MB_CMD_AWB_SET_MODE,
	APU_2_RPU_MB_CMD_AWB_GET_MODE,
	APU_2_RPU_MB_CMD_AWB_SET_ROI,
	APU_2_RPU_MB_CMD_AWB_GET_ROI,
	APU_2_RPU_MB_CMD_AWB_ENABLE,
	APU_2_RPU_MB_CMD_AWB_DISABLE,
	APU_2_RPU_MB_CMD_AWB_GET_STATUS,
	APU_2_RPU_MB_CMD_AWB_GET_VERSION,
	APU_2_RPU_MB_CMD_AWB_GET_ColorTempWeight,
	APU_2_RPU_MB_CMD_AWB_RESET,
	APU_2_RPU_MB_CMD_AWB_GET_RES,

	/*----------------------------------------------BLS API-----------------------------------------*/
	APU_2_RPU_MB_CMD_BLS_SET_CONFIG,
	APU_2_RPU_MB_CMD_BLS_GET_CONFIG,
	APU_2_RPU_MB_CMD_BLS_SET_BIT_WIDTH,
	APU_2_RPU_MB_CMD_BLS_GET_BIT_WIDTH,
	APU_2_RPU_MB_CMD_BLS_GET_STATUS,
	APU_2_RPU_MB_CMD_BLS_RESET,
	APU_2_RPU_MB_CMD_BLS_GET_VERSION,

	/*----------------------------------------------CCM API-----------------------------------------*/
	APU_2_RPU_MB_CMD_CCM_ENABLE,
	APU_2_RPU_MB_CMD_CCM_DISABLE,
	APU_2_RPU_MB_CMD_CCM_SET_CONFIG,
	APU_2_RPU_MB_CMD_CCM_GET_CONFIG,
	APU_2_RPU_MB_CMD_CCM_GET_STATUS,
	APU_2_RPU_MB_CMD_CCM_RESET,
	APU_2_RPU_MB_CMD_CCM_GET_VERSION,

	/*-----------------------------------------------CPD API----------------------------------------*/
	APU_2_RPU_MB_CMD_CPD_SET_CONFIG,
	APU_2_RPU_MB_CMD_CPD_GET_CONFIG,
	APU_2_RPU_MB_CMD_CPD_EXPAND_ENABLE,
	APU_2_RPU_MB_CMD_CPD_EXPAND_DISABLE,
	APU_2_RPU_MB_CMD_CPD_EXPAND_GET_STATUS,
	APU_2_RPU_MB_CMD_CPD_COMPRESS_GET_STATUS,
	APU_2_RPU_MB_CMD_CPD_RESET,
	APU_2_RPU_MB_CMD_CPD_GET_VERSION,

	/*-----------------------------------------------CPROC API---------------------------------------*/
	APU_2_RPU_MB_CMD_CPROC_SET_CONFIG,
	APU_2_RPU_MB_CMD_CPROC_GET_CONFIG,
	APU_2_RPU_MB_CMD_CPROC_SET_RANGE,
	APU_2_RPU_MB_CMD_CPROC_GET_RANGE,
	APU_2_RPU_MB_CMD_CPROC_ENABLE,
	APU_2_RPU_MB_CMD_CPROC_DISABLE,
	APU_2_RPU_MB_CMD_CPROC_GET_STATUS,
	APU_2_RPU_MB_CMD_CPROC_GET_RANGE_STATUS,
	APU_2_RPU_MB_CMD_CPROC_RESET,
	APU_2_RPU_MB_CMD_CPROC_GET_VERSION,

	/*---------------------------------------------DG API-----------------------------------------------*/
	APU_2_RPU_MB_CMD_DG_SET_CONFIG,
	APU_2_RPU_MB_CMD_DG_GET_CONFIG,
	APU_2_RPU_MB_CMD_DG_ENABLE,
	APU_2_RPU_MB_CMD_DG_DISABLE,
	APU_2_RPU_MB_CMD_DG_GET_STATUS,
	APU_2_RPU_MB_CMD_DG_RESET,
	APU_2_RPU_MB_CMD_DG_GET_VERSION,

	/*--------------------------------------------DMSC API--------------------------------------------*/
	APU_2_RPU_MB_CMD_DMSC_SET_CONFIG,
	APU_2_RPU_MB_CMD_DMSC_GET_CONFIG,
	APU_2_RPU_MB_CMD_DMSC_ENABLE,
	APU_2_RPU_MB_CMD_DMSC_DISABLE,
	APU_2_RPU_MB_CMD_DMSC_CAC_ENABLE,
	APU_2_RPU_MB_CMD_DMSC_CAC_DISABLE,
	APU_2_RPU_MB_CMD_DMSC_DEMOIRE_ENABLE,
	APU_2_RPU_MB_CMD_DMSC_DEMOIRE_DISABLE,
	APU_2_RPU_MB_CMD_DMSC_DEPURPLE_ENABLE,
	APU_2_RPU_MB_CMD_DMSC_DEPURPLE_DISABLE,
	APU_2_RPU_MB_CMD_DMSC_SHARPEN_ENABLE,
	APU_2_RPU_MB_CMD_DMSC_SHARPEN_DISABLE,
	APU_2_RPU_MB_CMD_DMSC_SHARPEN_LINE_ENABLE,
	APU_2_RPU_MB_CMD_DMSC_SHARPEN_LINE_DISABLE,
	APU_2_RPU_MB_CMD_DMSC_SKIN_ENABLE,
	APU_2_RPU_MB_CMD_DMSC_SKIN_DISABLE,
	APU_2_RPU_MB_CMD_DMSC_GET_STATUS,
	APU_2_RPU_MB_CMD_DMSC_RESET,
	APU_2_RPU_MB_CMD_DMSC_GET_VERSION,

	/*--------------------------------------------DPCC API------------------------------------------*/
	APU_2_RPU_MB_CMD_DPCC_SET_CONFIG,
	APU_2_RPU_MB_CMD_DPCC_GET_CONFIG,
	APU_2_RPU_MB_CMD_DPCC_ENABLE,
	APU_2_RPU_MB_CMD_DPCC_DISABLE,
	APU_2_RPU_MB_CMD_DPCC_GET_STATUS,
	APU_2_RPU_MB_CMD_DPCC_RESET,
	APU_2_RPU_MB_CMD_DPCC_GET_VERSION,

	/*---------------------------------------------EE API-------------------------------------------*/
	APU_2_RPU_MB_CMD_EE_SET_CONFIG,
	APU_2_RPU_MB_CMD_EE_GET_CONFIG,
	APU_2_RPU_MB_CMD_EE_GET_CURVE_EN_CONFIG,
	APU_2_RPU_MB_CMD_EE_ENABLE,
	APU_2_RPU_MB_CMD_EE_DISABLE,
	APU_2_RPU_MB_CMD_EE_CURVE_ENABLE,
	APU_2_RPU_MB_CMD_EE_CURVE_DISABLE,
	APU_2_RPU_MB_CMD_EE_CA_ENABLE,
	APU_2_RPU_MB_CMD_EE_CA_DISABLE,
	APU_2_RPU_MB_CMD_EE_DCI_ENABLE,
	APU_2_RPU_MB_CMD_EE_DCI_DISABLE,
	APU_2_RPU_MB_CMD_EE_GET_STATUS,
	APU_2_RPU_MB_CMD_EE_RESET,
	APU_2_RPU_MB_CMD_EE_GET_VERSION,

	/*-----------------------------------------------EXP V2 API----------------------------------------*/
	APU_2_RPU_MB_CMD_EXP_V2_SET_CONFIG,
	APU_2_RPU_MB_CMD_EXP_V2_GET_CONFIG,
	APU_2_RPU_MB_CMD_EXP_V2_ENABLE,
	APU_2_RPU_MB_CMD_EXP_V2_DISABLE,
	APU_2_RPU_MB_CMD_EXP_V2_SET_MEASURE_WINDOW,
	APU_2_RPU_MB_CMD_EXP_V2_GET_MEASURE_WINDOW,
	APU_2_RPU_MB_CMD_EXP_V2_GET_STATISTICS,
	APU_2_RPU_MB_CMD_EXP_V2_GET_STATUS,
	APU_2_RPU_MB_CMD_EXP_V2_GET_VERSION,
	APU_2_RPU_MB_CMD_EXP_V2_RESET,

	/*----------------------------------------------GC API------------------------------------------*/
	APU_2_RPU_MB_CMD_GC_SET_CONFIG,
	APU_2_RPU_MB_CMD_GC_GET_CONFIG,
	APU_2_RPU_MB_CMD_GC_ENABLE,
	APU_2_RPU_MB_CMD_GC_DISABLE,
	APU_2_RPU_MB_CMD_GC_GET_STATUS,
	APU_2_RPU_MB_CMD_GC_RESET,
	APU_2_RPU_MB_CMD_GC_GET_VERSION,

	/*-----------------------------------------------GE API-----------------------------------------*/
	APU_2_RPU_MB_CMD_GE_SET_CONFIG,
	APU_2_RPU_MB_CMD_GE_GET_CONFIG,
	APU_2_RPU_MB_CMD_GE_ENABLE,
	APU_2_RPU_MB_CMD_GE_DISABLE,
	APU_2_RPU_MB_CMD_GE_GET_STATUS,
	APU_2_RPU_MB_CMD_GE_RESET,
	APU_2_RPU_MB_CMD_GE_GET_VERSION,

	/*-----------------------------------------------GTM API V_1------------------------------------*/
	APU_2_RPU_MB_CMD_GTM_SET_CONFIG,
	APU_2_RPU_MB_CMD_GTM_GET_CONFIG,
	APU_2_RPU_MB_CMD_GTM_ENABLE,
	APU_2_RPU_MB_CMD_GTM_DISABLE,
	APU_2_RPU_MB_CMD_GTM_BWC_ENABLE,
	APU_2_RPU_MB_CMD_GTM_BWC_DISABLE,
	APU_2_RPU_MB_CMD_GTM_BWCEnGetConfig,
	APU_2_RPU_MB_CMD_GTM_GET_STATUS,
	APU_2_RPU_MB_CMD_GTM_GET_VERSION,
	APU_2_RPU_MB_CMD_GTM_RESET,
	APU_2_RPU_MB_CMD_GTM_GETHIST,

	/*---------------------------------------------HIST API ----------------------------------------*/
	APU_2_RPU_MB_CMD_HIST256_SET_CONFIG,
	APU_2_RPU_MB_CMD_HIST256_GET_CONFIG,
	APU_2_RPU_MB_CMD_HIST256_ENABLE,
	APU_2_RPU_MB_CMD_HIST256_DISABLE,
	APU_2_RPU_MB_CMD_HIST256_GET_STATISTIC,
	APU_2_RPU_MB_CMD_HIST256_GET_STATUS,
	APU_2_RPU_MB_CMD_HIST256_GET_VERSION,
	APU_2_RPU_MB_CMD_HIST256_RESET,

	APU_2_RPU_MB_CMD_HIST64_SET_CONFIG,
	APU_2_RPU_MB_CMD_HIST64_GET_CONFIG,
	APU_2_RPU_MB_CMD_HIST64_ENABLE,
	APU_2_RPU_MB_CMD_HIST64_DISABLE,
	APU_2_RPU_MB_CMD_HIST64_GET_STATISTIC,
	APU_2_RPU_MB_CMD_HIST64_GET_STATUS,
	APU_2_RPU_MB_CMD_HIST64_GET_VERSION,
	APU_2_RPU_MB_CMD_HIST64_RESET,

	/*---------------------------------------------LSC API V3--------------------------------------*/
	APU_2_RPU_MB_CMD_LSC_SET_CONFIG,
	APU_2_RPU_MB_CMD_LSC_GET_CONFIG,
	APU_2_RPU_MB_CMD_LSC_ENABLE,
	APU_2_RPU_MB_CMD_LSC_DISABLE,
	APU_2_RPU_MB_CMD_LSC_RESET,
	APU_2_RPU_MB_CMD_LSC_GET_STATUS,
	APU_2_RPU_MB_CMD_LSC_GET_VERSION,

	/*---------------------------------------------RGBIR API V2------------------------------------*/
	APU_2_RPU_MB_CMD_RGBIR_SET_INTERNAL_CONFIG,
	APU_2_RPU_MB_CMD_RGBIR_SET_CONFIG,
	APU_2_RPU_MB_CMD_RGBIR_GET_CONFIG,
	APU_2_RPU_MB_CMD_RGBIR_ENABLE,
	APU_2_RPU_MB_CMD_RGBIR_DISABLE,
	APU_2_RPU_MB_CMD_RGBIR_RCCC_ENABLE,
	APU_2_RPU_MB_CMD_RGBIR_RCCC_DISABLE,
	APU_2_RPU_MB_CMD_RGBIR_IR_RAWOUT_ENABLE,
	APU_2_RPU_MB_CMD_RGBIR_IR_RAWOUT_DISABLE,
	APU_2_RPU_MB_CMD_RGBIR_SET_OutPattern,
	APU_2_RPU_MB_CMD_RGBIR_GET_OutPattern,
	APU_2_RPU_MB_CMD_RGBIR_SET_IrPathSelect,
	APU_2_RPU_MB_CMD_RGBIR_GET_IrPathSelect,
	APU_2_RPU_MB_CMD_RGBIR_GET_STATUS,
	APU_2_RPU_MB_CMD_RGBIR_GET_VERSION,
	APU_2_RPU_MB_CMD_RGBIR_RESET,

	/*-------------------------------------------WB API---------------------------*/
	APU_2_RPU_MB_CMD_WB_ENABLE,
	APU_2_RPU_MB_CMD_WB_DISABLE,
	APU_2_RPU_MB_CMD_WB_SET_CONFIG,
	APU_2_RPU_MB_CMD_WB_GET_CONFIG,
	APU_2_RPU_MB_CMD_WB_GET_STATUS,
	APU_2_RPU_MB_CMD_WB_RESET,
	APU_2_RPU_MB_CMD_WB_GET_VERSION,

	/*-------------------------------------------WDR V5_2-----------------------*/
	APU_2_RPU_MB_CMD_WDR_SET_CONFIG,
	APU_2_RPU_MB_CMD_WDR_GET_CONFIG,
	APU_2_RPU_MB_CMD_WDR_ENABLE,
	APU_2_RPU_MB_CMD_WDR_DISABLE,
	APU_2_RPU_MB_CMD_WDR_HCF_ENABLE,
	APU_2_RPU_MB_CMD_WDR_HCF_DISABLE,
	APU_2_RPU_MB_CMD_WDR_GET_STATUS,
	APU_2_RPU_MB_CMD_WDR_GET_VERSION,
	APU_2_RPU_MB_CMD_WDR_RESET,
	APU_2_RPU_MB_CMD_WDR_SET_GAMMA_UP_CFG,
	APU_2_RPU_MB_CMD_WDR_GET_GAMMA_UP_CFG,
	APU_2_RPU_MB_CMD_WDR_GET_GAMMA_UP_STATUS,

	APU_2_RPU_MB_CMB_INIT_FIRMWARE,		/**< init firmware, no command context */
	APU_2_RPU_MB_CMD_LOADCFG_STREAMING,		/**< load config from sram, no command context */
	APU_2_RPU_MB_CMD_DEINIT_STREAMING,


	/*---------------------------------------------APU SENSOR DRIVER------------------------------------*/

	RPU_2_APU_MB_CMD_IsiCreateIss,
	RPU_2_APU_MB_CMD_IsiReleaseIss,
	RPU_2_APU_MB_CMD_IsiEnumModeIss,
	RPU_2_APU_MB_CMD_IsiCheckConnectionIss,
	RPU_2_APU_MB_CMD_IsiOpenIss,
	RPU_2_APU_MB_CMD_IsiCloseIss,
	RPU_2_APU_MB_CMD_IsiGetModeIss,
	RPU_2_APU_MB_CMD_IsiGetCapsIss,
	RPU_2_APU_MB_CMD_IsiGetRevisionIss,
	RPU_2_APU_MB_CMD_IsiSetStreamingIss,

	RPU_2_APU_MB_CMD_IsiGetAeBaseInfoIss,
	RPU_2_APU_MB_CMD_IsiGetAGainIss,
	RPU_2_APU_MB_CMD_IsiGetDGainIss,
	RPU_2_APU_MB_CMD_IsiSetAGainIss,
	RPU_2_APU_MB_CMD_IsiSetDGainIss,
	RPU_2_APU_MB_CMD_IsiGetIntTimeIss,
	RPU_2_APU_MB_CMD_IsiSetIntTimeIss,
	RPU_2_APU_MB_CMD_IsiGetFpsIss,
	RPU_2_APU_MB_CMD_IsiSetFpsIss,

	RPU_2_APU_MB_CMD_IsiGetIspStatusIss,
	RPU_2_APU_MB_CMD_IsiSetWBIss,
	RPU_2_APU_MB_CMD_IsiGetWBIss,
	RPU_2_APU_MB_CMD_IsiSetBlcIss,
	RPU_2_APU_MB_CMD_IsiGetBlcIss,

	RPU_2_APU_MB_CMD_IsiSetTpgIss,
	RPU_2_APU_MB_CMD_IsiGetTpgIss,
	RPU_2_APU_MB_CMD_IsiGetExpandCurveIss,

	RPU_2_APU_MB_CMD_IsiWriteRegIss,
	RPU_2_APU_MB_CMD_IsiReadRegIss,


	RPU_2_APU_MB_CMD_REPORT_INTERNAL_FAILURE,
	RPU_2_APU_MB_CMD_FULL_BUFFER_INFORM,
	RPU_2_APU_MB_CMD_FUSA_EVENT_CB,

	MB_CMD_RES_ERR,
	MB_CMD_RES_TIMEOUT,
	MB_CMD_END,
	MB_CMD_BUF_RET,
	APU_2_RPU_MB_CMD_I2C_INIT,
	APU_2_RPU_MB_CMD_SLCR_INIT,
	APU_2_RPU_MB_CMD_IBA_INIT,
	APU_2_RPU_MB_CMD_OBA_INIT,
	APU_2_RPU_MB_CMD_SET_ATM,
	APU_2_RPU_MB_CMD_CONFIG_RESIZER,
	RPU_2_APU_MB_CMD_ISP_ERR_REPORT,
	APU_2_RPU_MB_CMD_SOFT_RESET,
	APU_2_RPU_MB_TIME_DELAY_TEST_CMD,
	APU_2_RPU_MB_TEST,
	RPU_2_APU_CMD_DISPLAY_BUFFER,
	APU_2_RPU_MB_LINUX_COMPAT,
	DUMMY_MB_CMD = 0xdeadfeed,
} MBCmdId_E;

typedef enum payload_type {
	CMD,
	RESP,
	dummy_pt = 0xDEADFEED,
} Payload_type;


#define MAX_ITEM 16396

typedef struct response_field {
	uint32_t processed_cmdid;
	uint32_t error_subcode_t;
} response_field_t;


typedef struct payload_template {
	Payload_type type;
	uint32_t cookie;
	uint32_t payload_size;
	response_field_t resp_field;
	uint8_t payload_data[MAX_ITEM];
} Payload_packet;

struct resource_table {
	uint8_t rpu0_ready;
	uint8_t rpu1_ready;
	uint8_t apu_ready;
};
int Send_Command(MBCmdId_E cmd, void *data, uint32_t size, uint8_t dest_cpu, uint8_t src_cpu);
int Send_Response(MBCmdId_E cmd, void *data, uint32_t size, uint8_t dest_cpu, uint8_t src_cpu);

uint8_t apu_wait_for_ACK(uint32_t cookie, void *data);


#endif
