uartpsv
XUARTPSV_OPTION_SET_BREAK
These constants specify the options that may be set or retrieved with the driver, each is a unique bit mask such that multiple options may be specified.
These constants indicate the available options in active state.Starts break transmission
XUARTPSV_OPTION_STOP_BREAK
Stops break transmission.
XUARTPSV_OPTION_RESET_TMOUT
Reset the receive timeout.
XUARTPSV_OPTION_RESET_TX
Reset the transmitter.
XUARTPSV_OPTION_RESET_RX
Reset the receiver.
XUARTPSV_OPTION_ASSERT_RTS
Assert the RTS bit.
XUARTPSV_OPTION_ASSERT_DTR
Assert the DTR bit.
XUARTPSV_OPTION_SET_FCM
Turn on flow control mode.
XUARTPSV_OPER_MODE_NORMAL
Normal Mode.
Referenced by UartPsvIntrExample, UartPsvPolledExample, XUartPsv_GetOperMode, XUartPsv_SetOperMode.
XUARTPSV_OPER_MODE_LOCAL_LOOP
Local Loop back Mode.
Referenced by UartPsvIntrExample, UartPsvPolledExample, XUartPsv_GetOperMode, XUartPsv_SelfTest, XUartPsv_SetOperMode.
XUARTPSV_FORMAT_8_BITS
8 data bits
Referenced by XUartPsv_SetDataFormat.
XUARTPSV_FORMAT_7_BITS
7 data bits
XUARTPSV_FORMAT_6_BITS
6 data bits
XUARTPSV_FORMAT_5_BITS
5 data bits
XUARTPSV_FORMAT_NO_PARITY
No parity.
XUARTPSV_FORMAT_EN_PARITY
Enable parity.
Referenced by XUartPsv_SetDataFormat.
XUARTPSV_FORMAT_EVEN_PARITY
Even parity.
Referenced by XUartPsv_SetDataFormat.
XUARTPSV_FORMAT_ODD_PARITY
Odd parity.
XUARTPSV_FORMAT_EN_STICK_PARITY
Stick parity.
Referenced by XUartPsv_SetDataFormat.
XUARTPSV_FORMAT_NO_STICK_PARITY
Stick parity.
XUARTPSV_FORMAT_PARITY_MASK
Format parity mask.
Referenced by XUartPsv_SetDataFormat.
XUARTPSV_FORMAT_EVEN_PARITY_SHIFT
Even parity shift.
Referenced by XUartPsv_SetDataFormat.
XUARTPSV_FORMAT_EN_STICK_PARITY_SHIFT
Stick parity shift.
Referenced by XUartPsv_SetDataFormat.
XUARTPSV_FORMAT_2_STOP_BIT
2 stop bits
Referenced by XUartPsv_SetDataFormat.
XUARTPSV_FORMAT_1_STOP_BIT
1 stop bit
XUARTPSV_EVENT_RECV_DATA
Data receiving done.
Referenced by Handler.
XUARTPSV_EVENT_RECV_TOUT
A receive timeout occurred.
Referenced by Handler.
XUARTPSV_EVENT_SENT_DATA
Data transmission done.
Referenced by Handler.
XUARTPSV_EVENT_RECV_ERROR
A receive error detected.
Referenced by Handler.
XUARTPSV_EVENT_MODEM
Modem status changed.
XUARTPSV_EVENT_PARE_FRAME_BRKE
A receive parity, frame,break error detected.
Referenced by Handler, XUartPsv_InterruptHandler.
XUARTPSV_EVENT_RECV_ORERR
A receive overrun error detected.
Referenced by Handler.
XUARTPSV_UARTDR_OFFSET
Data.
Referenced by XUartPsv_ReceiveBuffer, XUartPsv_RecvByte, XUartPsv_SendBuffer, XUartPsv_SendByte.
XUARTPSV_UARTRSR_OFFSET
Receive Status Register/Error Clear.
XUARTPSV_UARTFR_OFFSET
Flag Register.
Referenced by XUartPsv_IsSending, XUartPsv_ReceiveBuffer, XUartPsv_SelfTest, XUartPsv_SendBuffer.
XUARTPSV_UARTILPR_OFFSET
IrDA Low-Power Counter.
XUARTPSV_UARTIBRD_OFFSET
Integer Baud Rate.
Referenced by XUartPsv_SetBaudRate.
XUARTPSV_UARTFBRD_OFFSET
Fractional Baud Rate.
Referenced by XUartPsv_SetBaudRate.
XUARTPSV_UARTLCR_OFFSET
Line Control.
Referenced by XUartPsv_CfgInitialize, XUartPsv_GetDataFormat, XUartPsv_ProgramCtrlReg, XUartPsv_SetBaudRate, XUartPsv_SetDataFormat.
XUARTPSV_UARTCR_OFFSET
Control.
Referenced by XUartPsv_GetOperMode, XUartPsv_ProgramCtrlReg, XUartPsv_SelfTest, XUartPsv_SetOperMode.
XUARTPSV_UARTIFLS_OFFSET
Interrupt FIFO Level Select.
Referenced by XUartPsv_CfgInitialize, XUartPsv_GetFifoThreshold, XUartPsv_SetFifoThreshold, XUartPsv_SetRxFifoThreshold, XUartPsv_SetTxFifoThreshold.
XUARTPSV_UARTIMSC_OFFSET
Interrupt Mask Set/Clear.
Referenced by XUartPsv_CfgInitialize, XUartPsv_GetInterruptMask, XUartPsv_InterruptHandler, XUartPsv_SetInterruptMask.
XUARTPSV_UARTRIS_OFFSET
Raw interrupt Status.
Referenced by XUartPsv_GetModemStatus, XUartPsv_InterruptHandler.
XUARTPSV_UARTMIS_OFFSET
Mask interrupt Status.
XUARTPSV_UARTICR_OFFSET
Interrupt Clear.
Referenced by XUartPsv_CfgInitialize, XUartPsv_InterruptHandler.
XUARTPSV_UARTDMACR_OFFSET
DMA Control.
XUARTPSV_UARTRSR_OE
Overrun error.
XUARTPSV_UARTFR_RI
Ring indicator.
XUARTPSV_UARTFR_TXFE
Transmit FIFO empty.
Referenced by XUartPsv_IsSending.
XUARTPSV_UARTFR_RXFF
Receive FIFO full.
XUARTPSV_UARTFR_TXFF
Transmit FIFO full.
XUARTPSV_UARTFR_RXFE
Receive FIFO empty.
Referenced by XUartPsv_ReceiveBuffer, XUartPsv_SelfTest.
XUARTPSV_UARTFR_BUSY
UART Busy.
Referenced by XUartPsv_IsSending, XUartPsv_SendBuffer.
XUARTPSV_UARTFR_DCD
Data carrier detect.
XUARTPSV_UARTFR_DSR
Data set ready.
XUARTPSV_UARTFR_CTS
Clear to send.
XUARTPSV_UARTLCR_SPS
Stick parity select.
XUARTPSV_UARTLCR_FEN
Enable FIFOs.
Referenced by XUartPsv_CfgInitialize, XUartPsv_ProgramCtrlReg.
XUARTPSV_UARTLCR_STP2
Two stop bits selected.
XUARTPSV_UARTLCR_EPS
Even parity select.
XUARTPSV_UARTLCR_PEN
Parity enable.
XUARTPSV_UARTLCR_BRK
Send break.
XUARTPSV_UARTLCR_WLEN_MASK
Word length mask.
Referenced by XUartPsv_CfgInitialize, XUartPsv_GetDataFormat, XUartPsv_SetDataFormat.
XUARTPSV_UARTLCR_WLEN_SHIFT
Word length shift.
Referenced by XUartPsv_GetDataFormat, XUartPsv_SetDataFormat.
XUARTPSV_UARTLCR_WLEN_5_BIT
5 bits data
XUARTPSV_UARTLCR_WLEN_6_BIT
6 bits data
XUARTPSV_UARTLCR_WLEN_7_BIT
7 bits data
XUARTPSV_UARTLCR_WLEN_8_BIT
8 bits data
Referenced by XUartPsv_CfgInitialize.
XUARTPSV_UARTLCR_STP_1_BIT
One stop bits selected.
Referenced by XUartPsv_CfgInitialize.
XUARTPSV_UARTLCR_STP_MASK
Stop bits mask.
Referenced by XUartPsv_CfgInitialize, XUartPsv_GetDataFormat, XUartPsv_SetDataFormat.
XUARTPSV_UARTLCR_STP_SHIFT
Stop bits shift.
Referenced by XUartPsv_GetDataFormat, XUartPsv_SetDataFormat.
XUARTPSV_UARTLCR_PARITY_EVEN
Even parity mode.
XUARTPSV_UARTLCR_PARITY_MASK
Parity mask.
Referenced by XUartPsv_CfgInitialize, XUartPsv_GetDataFormat, XUartPsv_SetDataFormat.
XUARTPSV_UARTLCR_PARITY_SHIFT
Parity shift.
Referenced by XUartPsv_GetDataFormat, XUartPsv_SetDataFormat.
XUARTPSV_UARTLCR_PARITY_NONE
No parity mode.
Referenced by XUartPsv_CfgInitialize.
XUARTPSV_UARTLCR_PARITY_ODD
Odd parity mode.
XUARTPSV_UARTCR_CTSEN
CTS hardware flow control enable.
XUARTPSV_UARTCR_RTSEN
RTS hardware flow control enable.
XUARTPSV_UARTCR_OUT2
UART Out2 modem status output.
XUARTPSV_UARTCR_OUT1
UART Out1 modem status output.
XUARTPSV_UARTCR_RTS
Request to send.
XUARTPSV_UARTCR_DTR
Data transmit ready.
XUARTPSV_UARTCR_RXE
Receive enable.
XUARTPSV_UARTCR_TXE
Transmit enable.
XUARTPSV_UARTCR_LBE
Loop back enable.
Referenced by XUartPsv_GetOperMode, XUartPsv_SetOperMode.
XUARTPSV_UARTCR_SIRLP
SIR low-power IrDA mode.
XUARTPSV_UARTCR_SIREN
SIR enable.
XUARTPSV_UARTCR_UARTEN
UART enable.
Referenced by XUartPsv_ProgramCtrlReg.
XUARTPSV_UARTCR_MODE_MASK
Mode mask.
Referenced by XUartPsv_GetOperMode, XUartPsv_SetOperMode.
XUARTPSV_UARTCR_MODE_SHIFT
Mode shift.
Referenced by XUartPsv_GetOperMode.
XUARTPSV_UARTCR_MODE_NORMAL
Normal Mode.
Referenced by XUartPsv_GetOperMode, XUartPsv_SetOperMode.
XUARTPSV_UARTIFLS_RXIFLSEL_MASK
Receive interrupt FIFO level select mask.
Referenced by XUartPsv_GetFifoThreshold, XUartPsv_SetFifoThreshold, XUartPsv_SetRxFifoThreshold.
XUARTPSV_UARTIFLS_RXIFLSEL_SHIFT
Transmit interrupt FIFO level select shift.
Referenced by XUartPsv_SetFifoThreshold.
XUARTPSV_UARTIFLS_TXIFLSEL_MASK
Receive interrupt FIFO level select mask.
Referenced by XUartPsv_GetFifoThreshold, XUartPsv_SetFifoThreshold, XUartPsv_SetTxFifoThreshold.
XUARTPSV_UARTIFLS_TXIFLSEL_SHIFT
Transmit interrupt FIFO level select shift.
Referenced by XUartPsv_SetFifoThreshold, XUartPsv_SetTxFifoThreshold.
XUARTPSV_UARTIFLS_RXIFLSEL_1_8
Receive FIFO becomes .
1/8 full
XUARTPSV_UARTIFLS_RXIFLSEL_1_4
Receive FIFO becomes .
1/4 full
Referenced by UartPsvIntrExample.
XUARTPSV_UARTIFLS_RXIFLSEL_1_2
Receive FIFO becomes * .
1/2 full
Referenced by XUartPsv_CfgInitialize.
XUARTPSV_UARTIFLS_RXIFLSEL_3_4
Receive FIFO becomes * .
3/4 full
XUARTPSV_UARTIFLS_RXIFLSEL_7_8
Receive FIFO becomes * .
7/8 full
XUARTPSV_UARTIFLS_TXIFLSEL_1_8
Transmit FIFO becomes * .
1/8 full
XUARTPSV_UARTIFLS_TXIFLSEL_1_4
Transmit FIFO becomes * .
1/4 full
XUARTPSV_UARTIFLS_TXIFLSEL_1_2
Transmit FIFO becomes * .
1/2 full
Referenced by UartPsvIntrExample, XUartPsv_CfgInitialize.
XUARTPSV_UARTIFLS_TXIFLSEL_3_4
Transmit FIFO becomes * .
3/4 full
XUARTPSV_UARTIFLS_TXIFLSEL_7_8
Transmit FIFO becomes * .
7/8 full
XUARTPSV_UARTIMSC_OEIM
Overrun Error Interrupt.
Referenced by UartPsvIntrExample.
XUARTPSV_UARTIMSC_BEIM
Break Error Interrupt.
Referenced by UartPsvIntrExample.
XUARTPSV_UARTIMSC_PEIM
Parity Error Interrupt.
Referenced by UartPsvIntrExample.
XUARTPSV_UARTIMSC_FEIM
Framing Error Interrupt.
Referenced by UartPsvIntrExample.
XUARTPSV_UARTIMSC_RTIM
Receive Timeout Interrupt.
Referenced by UartPsvIntrExample.
XUARTPSV_UARTIMSC_TXIM
Transmit Interrupt.
Referenced by UartPsvIntrExample.
XUARTPSV_UARTIMSC_RXIM
Receive Interrupt.
Referenced by UartPsvIntrExample.
XUARTPSV_UARTIMSC_DSRMIM
nUARTDSR modem interrupt
XUARTPSV_UARTIMSC_DCDMIM
nUARTDCD modem interrupt
XUARTPSV_UARTIMSC_CTSMIM
nUARTCTS modem interrupt
XUARTPSV_UARTIMSC_RIMIM
nUARTRI modem interrupt
XUARTPSV_UARTIMSC_MASK
Valid bit mask.
Referenced by XUartPsv_CfgInitialize, XUartPsv_SetInterruptMask.
XUARTPSV_UARTRIS_OERIS
Overrun Error Interrupt.
Referenced by XUartPsv_InterruptHandler.
XUARTPSV_UARTRIS_BERIS
Break Error Interrupt.
Referenced by XUartPsv_InterruptHandler.
XUARTPSV_UARTRIS_PERIS
Parity Error Interrupt.
Referenced by XUartPsv_InterruptHandler.
XUARTPSV_UARTRIS_FERIS
Framing Error Interrupt.
Referenced by XUartPsv_InterruptHandler.
XUARTPSV_UARTRIS_RTRIS
Receive Timeout Interrupt.
Referenced by XUartPsv_InterruptHandler.
XUARTPSV_UARTRIS_TXRIS
Transmit Interrupt.
Referenced by XUartPsv_InterruptHandler.
XUARTPSV_UARTRIS_RXRIS
Receive Interrupt.
Referenced by XUartPsv_InterruptHandler.
XUARTPSV_UARTRIS_DSRRMIS
nUARTDSR modem interrupt
Referenced by XUartPsv_InterruptHandler.
XUARTPSV_UARTRIS_DCDRMIS
nUARTDCD modem interrupt
Referenced by XUartPsv_InterruptHandler.
XUARTPSV_UARTRIS_CTSRMIS
nUARTCTS modem interrupt
Referenced by XUartPsv_InterruptHandler.
XUARTPSV_UARTRIS_RIRMIS
nUARTRI modem interrupt
Referenced by XUartPsv_InterruptHandler.
XUARTPSV_UARTMIS_OEMIS
Overrun Error Interrupt.
XUARTPSV_UARTMIS_BEMIS
Break Error Interrupt.
XUARTPSV_UARTMIS_PEMIS
Parity Error Interrupt.
XUARTPSV_UARTMIS_FEMIS
Framing Error Interrupt.
XUARTPSV_UARTMIS_RTMIS
Receive Timeout Interrupt.
XUARTPSV_UARTMIS_TXMIS
Transmit Interrupt.
XUARTPSV_UARTMIS_RXMIS
Receive Interrupt.
XUARTPSV_UARTMIS_DSRMMIS
nUARTDSR modem interrupt
XUARTPSV_UARTMIS_DCDMMIS
nUARTDCD modem interrupt
XUARTPSV_UARTMIS_CTSMMIS
nUARTCTS modem interrupt
XUARTPSV_UARTMIS_RIRMMIS
nUARTRI modem interrupt
XUARTPSV_UARTICR_OEIC
Overrun Error Interrupt.
XUARTPSV_UARTICR_BEIC
Break Error Interrupt.
XUARTPSV_UARTICR_PEIC
Parity Error Interrupt.
XUARTPSV_UARTICR_FEIC
Framing Error Interrupt.
XUARTPSV_UARTICR_RTIC
Receive Timeout Interrupt.
XUARTPSV_UARTICR_TXIC
Transmit Interrupt.
XUARTPSV_UARTICR_RXIC
Receive Interrupt.
XUARTPSV_UARTICR_DSRMIC
nUARTDSR modem interrupt
XUARTPSV_UARTICR_DCDMIC
nUARTDCD modem interrupt
XUARTPSV_UARTICR_CTSMIC
nUARTCTS modem interrupt
XUARTPSV_UARTICR_RIMIC
nUARTRI modem interrupt
XUARTPSV_UARTDMACR_DMAONERR
DMA on error.
XUARTPSV_UARTDMACR_TXDMAE
Transmit DMA enable.
XUARTPSV_UARTDMACR_RXDMAE
Receive DMA enable.
XUARTPSV_UARTIBRD_BAUD_DIVINT_MASK
16 UARTIBRD bit mask
XUARTPSV_UARTIBRD_BAUD_DIVINT_RESET_VAL
Reset value.
XUARTPSV_UARTFBRD_BAUD_DIVFRAC_MASK
6 UARTFBRD bit mask
XUARTPSV_UARTFBRD_BAUD_DIVFRAC_RESET_VAL
Reset value.
XUARTPSV_RXTOUT_DISABLE
Disable time out.
XUARTPSV_RXTOUT_MASK
Valid bits mask.
XUARTPSV_RXWM_DISABLE
Disable RX trigger interrupt.
XUARTPSV_RXWM_MASK
Valid bits mask.
XUARTPSV_RXWM_RESET_VAL
Reset value.
XUARTPSV_TXWM_MASK
Valid bits mask.
XUARTPSV_TXWM_RESET_VAL
Reset value.
XUARTPSV_MODEMCR_FCM
Flow control mode.
XUARTPSV_MODEMCR_RTS
Request to send.
XUARTPSV_MODEMCR_DTR
Data terminal ready.
XUARTPSV_MODEMSR_FCMS
Flow control mode (FCMS)
XUARTPSV_MODEMSR_DCD
Complement of DCD input.
XUARTPSV_MODEMSR_RI
Complement of RI input.
XUARTPSV_MODEMSR_DSR
Complement of DSR input.
XUARTPSV_MODEMSR_CTS
Complement of CTS input.
XUARTPSV_MODEMSR_DDCD
Delta DCD indicator.
XUARTPSV_MODEMSR_TERI
Trailing Edge Ring Indicator.
XUARTPSV_MODEMSR_DDSR
Change of DSR.
XUARTPSV_MODEMSR_DCTS
Change of CTS.
XUARTPSV_FLOWDEL_MASK
Valid bit mask.
XUARTPSV_RXBS_BYTE3_BRKE
Byte3 Break Error.
XUARTPSV_RXBS_BYTE3_FRME
Byte3 Frame Error.
XUARTPSV_RXBS_BYTE3_PARE
Byte3 Parity Error.
XUARTPSV_RXBS_BYTE2_BRKE
Byte2 Break Error.
XUARTPSV_RXBS_BYTE2_FRME
Byte2 Frame Error.
XUARTPSV_RXBS_BYTE2_PARE
Byte2 Parity Error.
XUARTPSV_RXBS_BYTE1_BRKE
Byte1 Break Error.
XUARTPSV_RXBS_BYTE1_FRME
Byte1 Frame Error.
XUARTPSV_RXBS_BYTE1_PARE
Byte1 Parity Error.
XUARTPSV_RXBS_BYTE0_BRKE
Byte0 Break Error.
XUARTPSV_RXBS_BYTE0_FRME
Byte0 Frame Error.
XUARTPSV_RXBS_BYTE0_PARE
Byte0 Parity Error.
XUARTPSV_RXBS_MASK
3 bit RX byte status mask
typedef void(* XUartPsv_Handler)(void *CallBackRef, u32 Event, u32 EventData))(void *CallBackRef, u32 Event, u32 EventData)
This data type defines a handler that an application defines to communicate with interrupt system to retrieve state information about an application.
CallBackRef is a callback reference passed in by the upper layer when setting the handler, and is passed back to the upper layer when the handler is called. It is used to find the device driver instance. Event contains one of the event constants indicating events that have occurred. EventData contains the number of bytes sent or received at the time of the call for send and receive events and contains the modem status for modem events.
XUartPsv_Config XUartPsv_ConfigTable[][]
Config structure.
Referenced by XUartPsv_LookupConfig.
Mapping XUartPsv_OptionsTable[][]
u8 TestString[XUARTPSV_TOTAL_BYTES][XUARTPSV_TOTAL_BYTES]
u8 ReturnString[XUARTPSV_TOTAL_BYTES][XUARTPSV_TOTAL_BYTES]
static void XUartPsv_StubHandler(void *CallBackRef, u32 Event, u32 ByteCount)
This function is a stub handler that is the default handler such that if the application has not set the handler when interrupts are enabled, this function will be called.
CallBackRef is unused by this function. Event is unused by this function. ByteCount is unused by this function. None. None.
s32 XUartPsv_CfgInitialize(XUartPsv *InstancePtr, XUartPsv_Config *Config, UINTPTR EffectiveAddr)
Initializes a specific XUartPsv instance such that it is ready to be used.
The data format of the device is setup for 8 data bits, 1 stop bit, and no parity by default. The baud rate is set to a default value specified by Config->DefaultBaudRate if set, otherwise it is set to 19.2K baud. The receive FIFO threshold is set for 8 bytes. The default operating mode of the driver is polled mode. InstancePtr is a pointer to the XUartPsv instance. Config is a reference to a structure containing information about a specific XUartPsv driver. EffectiveAddr is the device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, pass in the physical address instead. XST_SUCCESS if initialization was successfulXST_UART_BAUD_ERROR if the baud rate is not possible because the inputclock frequency is not divisible with an acceptable amount of error The default configuration for the UART after initialization is: 19,200 bps or XPAR_DFT_BAUDRATE if defined8 data bits1 stop bitno parityFIFO's are enabled with a threshold of 16 ytesAll interrupts are disabled.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::Handler, XUartPsv_Config::InputClockHz, XUartPsv::IsReady, XUartPsv_Config::ModemPinsConnected, XUartPsvBuffer::NextBytePtr, XUartPsv::ReceiveBuffer, XUartPsvBuffer::RemainingBytes, XUartPsvBuffer::RequestedBytes, XUartPsv::SendBuffer, XUARTPSV_DFT_BAUDRATE, XUartPsv_ReadReg, XUartPsv_SetBaudRate, XUARTPSV_UARTICR_OFFSET, XUARTPSV_UARTIFLS_OFFSET, XUARTPSV_UARTIFLS_RXIFLSEL_1_2, XUARTPSV_UARTIFLS_TXIFLSEL_1_2, XUARTPSV_UARTIMSC_MASK, XUARTPSV_UARTIMSC_OFFSET, XUARTPSV_UARTLCR_FEN, XUARTPSV_UARTLCR_OFFSET, XUARTPSV_UARTLCR_PARITY_MASK, XUARTPSV_UARTLCR_PARITY_NONE, XUARTPSV_UARTLCR_STP_1_BIT, XUARTPSV_UARTLCR_STP_MASK, XUARTPSV_UARTLCR_WLEN_8_BIT, XUARTPSV_UARTLCR_WLEN_MASK, XUartPsv_WriteReg.
Referenced by UartPsvHelloWorldExample, UartPsvIntrExample, UartPsvPolledExample, UartPsvSelfTestExample.
u32 XUartPsv_Send(XUartPsv *InstancePtr, u8 *BufferPtr, u32 NumBytes)
This functions sends the specified buffer using the device in either polled or interrupt driven mode.
This function is non-blocking, if the device is busy sending data, it will return and indicate zero bytes were sent. Otherwise, it fills the TX FIFO as much as it can, and return the number of bytes sent.In a polled mode, this function will only send as much data as TX FIFO can buffer. The application may need to call it repeatedly to send the entire buffer.In interrupt mode, this function will start sending the specified buffer, then the interrupt handler will continue sending data until the entire buffer has been sent. A callback function, as specified by the application, will be called to indicate the completion of sending. InstancePtr is a pointer to the XUartPsv instance. BufferPtr is pointer to a buffer of data to be sent. NumBytes contains the number of bytes to be sent. A value of zero will stop a previous send operation that is in progress in interrupt mode. Any data that was already put into the transmit FIFO will be sent. The number of bytes actually sent. The number of bytes is not asserted so that this function may be called with a value of zero to stop an operation that is already in progress.
References XUartPsv::IsReady, XUartPsvBuffer::NextBytePtr, XUartPsvBuffer::RemainingBytes, XUartPsvBuffer::RequestedBytes, XUartPsv::SendBuffer, XUartPsv_SendBuffer.
Referenced by UartPsvHelloWorldExample, UartPsvIntrExample, UartPsvPolledExample, XUartPsv_SelfTest.
static u32 XUartPsv_SendBuffer_NoWait(XUartPsv *InstancePtr)
This function sends a buffer that has been previously specified by settingup the instance variables of the instance.This function implemented for RTOS environment and it is an internalfunction for the XUartPsv driver such that it's being called fromXUartPsv_Send_NoWait function that sets up the buffer.This function sends the specified buffer in polled mode. This functiononly sends as much data as the TX FIFO can buffer. The application mayneed to call it repeatedly to send the entire buffer. InstancePtr is a pointer to the XUartPsv instance The number of bytes actually sent None.
u32 XUartPsv_Send_NoWait(XUartPsv *InstancePtr, u8 *BufferPtr, u32 NumBytes)
This functions sends the specified buffer using the device in polled mode.This function is non-blocking, if the device is busy sending data, it willreturn and indicate zero bytes were sent. Otherwise, it fills the TX FIFOas much as it can, and return the number of bytes sent. The application mayneed to call it repeatedly to send the entire buffer.This function implemented for RTOS environment, it will check status andreturn without waiting. The caller of XUartPsv_Send_NoWait can waitbased on return value. InstancePtr is a pointer to the XUartPsv instance. BufferPtr is pointer to a buffer of data to be sent. NumBytes contains the number of bytes to be sent. A value of zero will stop a previous send operation that is in progressin interrupt mode. Any data that was already put into thetransmit FIFO will be sent.- The number of bytes actually sent, if data successfully sent - 0, if TX is busy. The caller of XUartPsv_Send_NoWait canwait if return 0. The number of bytes is not asserted so that this function may be called witha value of zero to stop an operation that is already in progress.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUartPsvBuffer::NextBytePtr, XUartPsvBuffer::RemainingBytes, XUartPsvBuffer::RequestedBytes, XUartPsv::SendBuffer, XUartPsv_IsTransmitbusy.
u32 XUartPsv_Recv(XUartPsv *InstancePtr, u8 *BufferPtr, u32 NumBytes)
This function attempts to receive a specified number of bytes of data from the device and store it into the specified buffer.
This function works for both polled or interrupt driven modes. It is non-blocking.In a polled mode, this function will only receive the data already in the RX FIFO. The application may need to call it repeatedly to receive the entire buffer. Polled mode is the default mode of operation for the device.In interrupt mode, this function will start the receiving, if not the entire buffer has been received, the interrupt handler will continue receiving data until the entire buffer has been received. A callback function, as specified by the application, will be called to indicate the completion of the receiving or error conditions. InstancePtr is a pointer to the XUartPsv instance BufferPtr is pointer to buffer for data to be received into NumBytes is the number of bytes to be received. A value of zero will stop a previous receive operation that is in progress in interrupt mode. The number of bytes received. The number of bytes is not asserted so that this function may be called with a value of zero to stop an operation that is already in progress.
References XUartPsv::IsReady, XUartPsvBuffer::NextBytePtr, XUartPsv::ReceiveBuffer, XUartPsvBuffer::RemainingBytes, XUartPsvBuffer::RequestedBytes, XUartPsv_GetInterruptMask, XUartPsv_ReceiveBuffer.
Referenced by UartPsvIntrExample, UartPsvPolledExample, XUartPsv_SelfTest.
u32 XUartPsv_SendBuffer(XUartPsv *InstancePtr)
This function sends a buffer that has been previously specified by setting up the instance variables of the instance.
This function is an internal function for the XUartPsv driver such that it may be called from a shell function that sets up the buffer or from an interrupt handler.This function sends the specified buffer in either polled or interrupt driven modes. This function is non-blocking.In a polled mode, this function only sends as much data as the TX FIFO can buffer. The application may need to call it repeatedly to send the entire buffer.In interrupt mode, this function starts the sending of the buffer, if not the entire buffer has been sent, then the interrupt handler continues the sending until the entire buffer has been sent. A callback function, as specified by the application, will be called to indicate the completion of sending. InstancePtr is a pointer to the XUartPsv instance The number of bytes actually sent None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsvBuffer::NextBytePtr, XUartPsvBuffer::RemainingBytes, XUartPsv::SendBuffer, XUartPsv_IsTransmitFull, XUARTPSV_UARTDR_OFFSET, XUARTPSV_UARTFR_BUSY, XUARTPSV_UARTFR_OFFSET, XUartPsv_WriteReg.
Referenced by XUartPsv_Send.
u32 XUartPsv_ReceiveBuffer(XUartPsv *InstancePtr)
This function receives a buffer that has been previously specified by setting up the instance variables of the instance.
This function is an internal function, and it may be called from a shell function that sets up the buffer or from an interrupt handler.This function attempts to receive a specified number of bytes from the device and store it into the specified buffer. This function works for either polled or interrupt driven modes. It is non-blocking.In polled mode, this function only receives as much data as in the RX FIFO. The application may need to call it repeatedly to receive the entire buffer. Polled mode is the default mode for the driver.In interrupt mode, this function starts the receiving, if not the entire buffer has been received, the interrupt handler will continue until the entire buffer has been received. A callback function, as specified by the application, will be called to indicate the completion of the receiving or error conditions. InstancePtr is a pointer to the XUartPsv instance The number of bytes received. None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsvBuffer::NextBytePtr, XUartPsv::ReceiveBuffer, XUartPsvBuffer::RemainingBytes, XUartPsv_ReadReg, XUARTPSV_UARTDR_OFFSET, XUARTPSV_UARTFR_OFFSET, XUARTPSV_UARTFR_RXFE.
Referenced by XUartPsv_Recv.
s32 XUartPsv_SetBaudRate(XUartPsv *InstancePtr, u32 BaudRate)
Sets the baud rate for the device.
Checks the input value for validity and also verifies that the requested rate can be configured to within the maximum error range specified by XUARTPSV_MAX_BAUD_ERROR_RATE. If the provided rate is not possible, the current setting is unchanged. InstancePtr is a pointer to the XUartPsv instance BaudRate to be set XST_SUCCESS if everything configured as expectedXST_UART_BAUD_ERROR if the requested rate is not available because there was too much error None.
References XUartPsv_Config::BaseAddress, XUartPsv::BaudRate, XUartPsv::Config, XUartPsv_Config::InputClockHz, XUartPsv::IsReady, XUartPsv_DisableUart, XUartPsv_EnableUart, XUARTPSV_MAX_BAUD_ERROR_RATE, XUARTPSV_MAX_RATE, XUARTPSV_MIN_RATE, XUartPsv_ReadReg, XUARTPSV_UARTFBRD_OFFSET, XUARTPSV_UARTIBRD_OFFSET, XUARTPSV_UARTLCR_OFFSET, XUartPsv_WriteReg.
Referenced by XUartPsv_CfgInitialize, XUartPsv_SetDataFormat.
void XUartPsv_ProgramCtrlReg(XUartPsv *InstancePtr, u32 CtrlRegister)
This function reprograms the control register according to the following sequence mentioned in the TRM.
Sequence to Program Control Register. Disable UARTCheck if BusyFlush the transmit FIFOProgram the Control RegisterEnable the Uart InstancePtr is a pointer to the XUartPsv instance CtrlRegister value to be written None. None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv_IsTransmitbusy, XUartPsv_ReadReg, XUARTPSV_UARTCR_OFFSET, XUARTPSV_UARTCR_UARTEN, XUARTPSV_UARTLCR_FEN, XUARTPSV_UARTLCR_OFFSET, XUartPsv_WriteReg.
Referenced by XUartPsv_SelfTest, XUartPsv_SetOperMode.
void XUartPsv_CleanupRx(XUartPsv *InstancePtr)
This function is a cleanup function to allow resetting Rx NextBytePtr, RemainingBytes and RequestedBytes.
None. None.
References XUartPsvBuffer::NextBytePtr, XUartPsv::ReceiveBuffer, XUartPsvBuffer::RemainingBytes, XUartPsvBuffer::RequestedBytes.
void XUartPsv_CleanupTx(XUartPsv *InstancePtr)
This function is a cleanup function to allow resetting Tx NextBytePtr, RemainingBytes and RequestedBytes.
None. None.
References XUartPsvBuffer::NextBytePtr, XUartPsvBuffer::RemainingBytes, XUartPsvBuffer::RequestedBytes, XUartPsv::SendBuffer.
XUartPsv_Config * XUartPsv_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XUartPsv_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xuartpsv.h for the definition of XUartPsv_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XUartPsv_Config::Name, XUartPsv_ConfigTable.
Referenced by UartPsvHelloWorldExample, UartPsvIntrExample, UartPsvPolledExample, UartPsvSelfTestExample.
void XUartPsv_SetOptions(XUartPsv *InstancePtr, u16 Options)
Sets the options for the specified driver instance.
The options are implemented as bit masks such that multiple options may be enabled or disabled simultaneously.The GetOptions function may be called to retrieve the currently enabled options. The result is ORed in the desired new settings to be enabled and ANDed with the inverse to clear the settings to be disabled. The resulting value is then used as the options for the SetOption function call. InstancePtr is a pointer to the XUartPsv instance. Options contains the options to be set which are bit masks contained in the file xuartpsv.h and named XUARTPSV_OPTION_*. None. None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUARTPSV_NUM_OPTIONS, XUartPsv_ReadReg, XUartPsv_WriteReg.
u16 XUartPsv_GetOptions(XUartPsv *InstancePtr)
Gets the options for the specified driver instance.
The options are implemented as bit masks such that multiple options may be enabled or disabled simultaneously. InstancePtr is a pointer to the XUartPsv instance. The current options for the UART. The options are bit masks that are contained in the file xuartpsv.h and named XUARTPSV_OPTION_*. None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUARTPSV_NUM_OPTIONS, XUartPsv_ReadReg.
void XUartPsv_SetFifoThreshold(XUartPsv *InstancePtr, u8 TriggerLevel)
This functions sets the Tx and Rx FIFO trigger level to the 'TriggerLevel' argument.
The same value is set for Tx and Rx FIFOs. The receive or transmit trigger level specifies the number of bytes in the FIFO that cause a receive or transmit data event (interrupt) to be generated. InstancePtr is a pointer to the XUartPsv instance. TriggerLevel contains the trigger level to set. This is a value from 0-7 None None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUartPsv_ReadReg, XUARTPSV_UARTIFLS_OFFSET, XUARTPSV_UARTIFLS_RXIFLSEL_MASK, XUARTPSV_UARTIFLS_RXIFLSEL_SHIFT, XUARTPSV_UARTIFLS_TXIFLSEL_MASK, XUARTPSV_UARTIFLS_TXIFLSEL_SHIFT, XUartPsv_WriteReg.
void XUartPsv_SetTxFifoThreshold(XUartPsv *InstancePtr, u8 TriggerLevel)
This functions sets the Tx FIFO trigger level to the 'TriggerLevel' argument.
This value is set for Tx FIFO. Rx FIFO trigger level is unchanged. The receive or transmit trigger level specifies the number of bytes in the FIFO that cause a receive or transmit data event (interrupt) to be generated. InstancePtr is a pointer to the XUartPsv instance. TriggerLevel contains the trigger level to set. This is a value from 0-4 (XUARTPSV_UARTIFLS_TXIFLSEL_1_8 - XUARTPSV_UARTIFLS_TXIFLSEL_7_8) None None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUartPsv_ReadReg, XUARTPSV_UARTIFLS_OFFSET, XUARTPSV_UARTIFLS_TXIFLSEL_MASK, XUARTPSV_UARTIFLS_TXIFLSEL_SHIFT, XUartPsv_WriteReg.
Referenced by UartPsvIntrExample.
void XUartPsv_SetRxFifoThreshold(XUartPsv *InstancePtr, u8 TriggerLevel)
This functions sets the Rx FIFO trigger level to the 'TriggerLevel' argument.
This value is set for Rx FIFO. Tx FIFO trigger level is unchanged. The receive or transmit trigger level specifies the number of bytes in the FIFO that cause a receive or transmit data event (interrupt) to be generated. InstancePtr is a pointer to the XUartPsv instance. TriggerLevel contains the trigger level to set. This is a value from 0-32 (XUARTPSV_UARTIFLS_RXIFLSEL_1_8 - XUARTPSV_UARTIFLS_RXIFLSEL_7_8) None None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUartPsv_ReadReg, XUARTPSV_UARTIFLS_OFFSET, XUARTPSV_UARTIFLS_RXIFLSEL_MASK, XUartPsv_WriteReg.
Referenced by UartPsvIntrExample.
u8 XUartPsv_GetFifoThreshold(XUartPsv *InstancePtr)
This function gets the Tx and Rx FIFO trigger level.
The receive or transmit trigger level specifies the number of bytes in the FIFO that cause a receive or transmit data event (interrupt) to be generated. InstancePtr is a pointer to the XUartPsv instance. The current receive FIFO trigger level. This is a value from 0-63. None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUartPsv_ReadReg, XUARTPSV_UARTIFLS_OFFSET, XUARTPSV_UARTIFLS_RXIFLSEL_MASK, XUARTPSV_UARTIFLS_TXIFLSEL_MASK.
u16 XUartPsv_GetModemStatus(XUartPsv *InstancePtr)
This function gets the modem status from the specified UART.
The modem status indicates any changes of the modem signals. This function allows the modem status to be read in a polled mode. The modem status is updated whenever it is read such that reading it twice may not yield the same results. InstancePtr is a pointer to the XUartPsv instance. The modem status which are bit masks that are contained in the file xuartpsv.h and named XUARTPSV_UARTRIS_*. The bit masks used for the modem status are the exact bits of the modem status register with no abstraction.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUartPsv_ReadReg, XUARTPSV_UARTRIS_OFFSET.
u32 XUartPsv_IsSending(XUartPsv *InstancePtr)
This function determines if the specified UART is sending data.
InstancePtr is a pointer to the XUartPsv instance. TRUE if the UART is sending dataFALSE if UART is not sending data None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUartPsv_ReadReg, XUARTPSV_UARTFR_BUSY, XUARTPSV_UARTFR_OFFSET, XUARTPSV_UARTFR_TXFE.
u8 XUartPsv_GetOperMode(XUartPsv *InstancePtr)
This function gets the operational mode of the UART.
The UART can operate in one of four modes: Normal, Local Loopback, Remote Loopback, or automatic echo. InstancePtr is a pointer to the XUartPsv instance. The operational mode is specified by constants defined in xuartpsv.h. The constants are named XUARTPSV_OPER_MODE_* None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUARTPSV_OPER_MODE_LOCAL_LOOP, XUARTPSV_OPER_MODE_NORMAL, XUartPsv_ReadReg, XUARTPSV_UARTCR_LBE, XUARTPSV_UARTCR_MODE_MASK, XUARTPSV_UARTCR_MODE_NORMAL, XUARTPSV_UARTCR_MODE_SHIFT, XUARTPSV_UARTCR_OFFSET.
void XUartPsv_SetOperMode(XUartPsv *InstancePtr, u8 OperationMode)
This function sets the operational mode of the UART.
The UART can operate in one of four modes: Normal, Local Loopback, Remote Loopback, or automatic echo. InstancePtr is a pointer to the XUartPsv instance. OperationMode is the mode of the UART. None. None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUARTPSV_OPER_MODE_LOCAL_LOOP, XUARTPSV_OPER_MODE_NORMAL, XUartPsv_ProgramCtrlReg, XUartPsv_ReadReg, XUARTPSV_UARTCR_LBE, XUARTPSV_UARTCR_MODE_MASK, XUARTPSV_UARTCR_MODE_NORMAL, XUARTPSV_UARTCR_OFFSET.
Referenced by UartPsvIntrExample, UartPsvPolledExample, XUartPsv_SelfTest.
s32 XUartPsv_SetDataFormat(XUartPsv *InstancePtr, XUartPsvFormat *FormatPtr)
Sets the data format for the device.
The data format includes the baud rate, number of data bits, number of stop bits, and parity. It is the caller's responsibility to ensure that the UART is not sending or receiving data when this function is called. InstancePtr is a pointer to the XUartPsv instance. FormatPtr is a pointer to a format structure containing the data format to be set. XST_SUCCESS if the data format was successfully set.XST_UART_BAUD_ERROR indicates the baud rate could not be set because of the amount of error with the baud rate and the input clock frequency.XST_INVALID_PARAM if one of the parameters was not valid. The data types in the format type, data bits and parity, are 32 bit fields to prevent a compiler warning. The asserts in this function will cause a warning if these fields are bytes.
References XUartPsv_Config::BaseAddress, XUartPsvFormat::BaudRate, XUartPsv::Config, XUartPsvFormat::DataBits, XUartPsv::IsReady, XUartPsvFormat::Parity, XUartPsvFormat::StopBits, XUARTPSV_FORMAT_2_STOP_BIT, XUARTPSV_FORMAT_8_BITS, XUARTPSV_FORMAT_EN_PARITY, XUARTPSV_FORMAT_EN_STICK_PARITY, XUARTPSV_FORMAT_EN_STICK_PARITY_SHIFT, XUARTPSV_FORMAT_EVEN_PARITY, XUARTPSV_FORMAT_EVEN_PARITY_SHIFT, XUARTPSV_FORMAT_PARITY_MASK, XUartPsv_ReadReg, XUartPsv_SetBaudRate, XUARTPSV_UARTLCR_OFFSET, XUARTPSV_UARTLCR_PARITY_MASK, XUARTPSV_UARTLCR_PARITY_SHIFT, XUARTPSV_UARTLCR_STP_MASK, XUARTPSV_UARTLCR_STP_SHIFT, XUARTPSV_UARTLCR_WLEN_MASK, XUARTPSV_UARTLCR_WLEN_SHIFT, XUartPsv_WriteReg.
void XUartPsv_GetDataFormat(XUartPsv *InstancePtr, XUartPsvFormat *FormatPtr)
Gets the data format for the specified UART.
The data format includes the baud rate, number of data bits, number of stop bits, and parity. InstancePtr is a pointer to the XUartPsv instance. FormatPtr is a pointer to a format structure that will contain the data format after this call completes. None. None.
References XUartPsv_Config::BaseAddress, XUartPsvFormat::BaudRate, XUartPsv::BaudRate, XUartPsv::Config, XUartPsvFormat::DataBits, XUartPsv::IsReady, XUartPsvFormat::Parity, XUartPsvFormat::StopBits, XUartPsv_ReadReg, XUARTPSV_UARTLCR_OFFSET, XUARTPSV_UARTLCR_PARITY_MASK, XUARTPSV_UARTLCR_PARITY_SHIFT, XUARTPSV_UARTLCR_STP_MASK, XUARTPSV_UARTLCR_STP_SHIFT, XUARTPSV_UARTLCR_WLEN_MASK, XUARTPSV_UARTLCR_WLEN_SHIFT.
u32 XUartPsv_GetInterruptMask(XUartPsv *InstancePtr)
This function gets the interrupt mask.
InstancePtr is a pointer to the XUartPsv instance. The current interrupt mask. The mask indicates which interrupts are enabled. None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv_ReadReg, XUARTPSV_UARTIMSC_OFFSET.
Referenced by XUartPsv_Recv.
void XUartPsv_SetInterruptMask(XUartPsv *InstancePtr, u32 Mask)
This function sets the interrupt mask.
InstancePtr is a pointer to the XUartPsv instance Mask contains the interrupts to be enabled or disabled. A '1' enables an interrupt, and a '0' disables. None. None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUARTPSV_UARTIMSC_MASK, XUARTPSV_UARTIMSC_OFFSET, XUartPsv_WriteReg.
Referenced by UartPsvIntrExample.
void XUartPsv_InterruptHandler(XUartPsv *InstancePtr)
This function is the interrupt handler for the driver.
It must be connected to an interrupt system by the application such that it can be called when an interrupt occurs. InstancePtr contains a pointer to the driver instance None. None.
References XUartPsv_Config::BaseAddress, XUartPsv::CallBackRef, XUartPsv::Config, XUartPsv::Handler, XUartPsv::IsReady, XUARTPSV_EVENT_PARE_FRAME_BRKE, XUartPsv_ReadReg, XUARTPSV_UARTICR_OFFSET, XUARTPSV_UARTIMSC_OFFSET, XUARTPSV_UARTRIS_BERIS, XUARTPSV_UARTRIS_CTSRMIS, XUARTPSV_UARTRIS_DCDRMIS, XUARTPSV_UARTRIS_DSRRMIS, XUARTPSV_UARTRIS_FERIS, XUARTPSV_UARTRIS_OERIS, XUARTPSV_UARTRIS_OFFSET, XUARTPSV_UARTRIS_PERIS, XUARTPSV_UARTRIS_RIRMIS, XUARTPSV_UARTRIS_RTRIS, XUARTPSV_UARTRIS_RXRIS, XUARTPSV_UARTRIS_TXRIS, XUartPsv_WriteReg.
Referenced by UartPsvIntrExample.
void XUartPsv_SetHandler(XUartPsv *InstancePtr, XUartPsv_Handler FuncPtr, void *CallBackRef)
This function sets the handler that will be called when an event (interrupt) occurs that needs application's attention.
InstancePtr is a pointer to the XUartPsv instance FuncPtr is the pointer to the callback function. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. None. There is no assert on the CallBackRef since the driver doesn't know what it is (nor should it)
References XUartPsv::CallBackRef, XUartPsv::Handler, XUartPsv::IsReady.
Referenced by UartPsvIntrExample.
s32 XUartPsv_SelfTest(XUartPsv *InstancePtr)
This function runs a self-test on the driver and hardware device.
This self test performs a local loopback and verifies data can be sent and received.The time for this test is proportional to the baud rate that has been set prior to calling this function.The mode and control registers are restored before return. InstancePtr is a pointer to the XUartPsv instance XST_SUCCESS if the test was successfulXST_UART_TEST_FAIL if the test failed looping back the data This function can hang if the hardware is not functioning properly.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUARTPSV_OPER_MODE_LOCAL_LOOP, XUartPsv_ProgramCtrlReg, XUartPsv_ReadReg, XUartPsv_Recv, XUartPsv_Send, XUartPsv_SetOperMode, XUARTPSV_TOTAL_BYTES, XUARTPSV_UARTCR_OFFSET, XUARTPSV_UARTFR_OFFSET, XUARTPSV_UARTFR_RXFE.
Referenced by UartPsvHelloWorldExample, UartPsvIntrExample, UartPsvPolledExample, UartPsvSelfTestExample.
void XUartPsv_SendByte(UINTPTR BaseAddress, u8 Data)
This function sends one byte using the device.
This function operates in polled mode and blocks until the data has been put into the TX FIFO register. BaseAddress contains the base address of the device. Data contains the byte to be sent. None. None.
References XUartPsv_IsTransmitFull, XUARTPSV_UARTDR_OFFSET, XUartPsv_WriteReg.
u8 XUartPsv_RecvByte(UINTPTR BaseAddress)
This function receives a byte from the device.
It operates in polled mode and blocks until a byte has received. BaseAddress contains the base address of the device. The data byte received. None.
References XUartPsv_IsReceiveData, XUartPsv_ReadReg, XUARTPSV_UARTDR_OFFSET.
void XUartPsv_ResetHw(UINTPTR BaseAddress)
This function resets UART.
(To be implemented if needed) BaseAddress contains the base address of the device. None None.
static void XUartPsv_ReceiveErrorHandler(XUartPsv *InstancePtr)
This function handles the interrupt when there is overrun error in Rx path.
InstancePtr is a pointer to the XUartPsv instance None. None.
static void XUartPsv_ReceiveDataHandler(XUartPsv *InstancePtr)
This function handles the interrupt when data is in RX FIFO.
InstancePtr is a pointer to the XUartPsv instance None. None.
static void XUartPsv_SendDataHandler(XUartPsv *InstancePtr)
This function handles the interrupt when data has been sent, the transmit FIFO is empty (transmitter holding register).
InstancePtr is a pointer to the XUartPsv instance None. None.
static void XUartPsv_ModemHandler(XUartPsv *InstancePtr)
This function handles modem interrupts.
It does not do any processing except to call the application handler to indicate a modem event. InstancePtr is a pointer to the XUartPsv instance None. None.
XUARTPSV_MAX_BAUD_ERROR_RATE
max % error allowed
Referenced by XUartPsv_SetBaudRate.
XUARTPSV_H
by using protection macros
XUARTPSV_MAX_RATE
Maximum baud rate.
Referenced by XUartPsv_SetBaudRate.
XUARTPSV_MIN_RATE
Minimum baud rate.
Referenced by XUartPsv_SetBaudRate.
XUARTPSV_DFT_BAUDRATE
Default baud rate.
Referenced by XUartPsv_CfgInitialize.
TIMEOUT_COUNTER
XUartPsv_GetChannelStatus
Get the UART Channel Status Register.
InstancePtr is a pointer to the XUartPsv instance. The value read from the register. C-Style signature: u16 XUartPsv_GetChannelStatus(XUartPsv *InstancePtr)
XUartPsv_GetModeControl
Get the UART Mode Control Register.
InstancePtr is a pointer to the XUartPsv instance. The value read from the register. C-Style signature: u32 XUartPsv_GetControl(XUartPsv *InstancePtr)
XUartPsv_SetModeControl
Set the UART Mode Control Register.
InstancePtr is a pointer to the XUartPsv instance. RegisterValue is the value to be written to the register. None. C-Style signature: void XUartPsv_SetModeControl(XUartPsv *InstancePtr, u16 RegisterValue)
XUartPsv_EnableUart
Enable the transmitter and receiver of the UART.
InstancePtr is a pointer to the XUartPsv instance. None. C-Style signature: void XUartPsv_EnableUart(XUartPsv *InstancePtr)
Referenced by XUartPsv_SetBaudRate.
XUartPsv_DisableUart
Disable the transmitter and receiver of the UART.
InstancePtr is a pointer to the XUartPsv instance. None. C-Style signature: void XUartPsv_DisableUart(XUartPsv *InstancePtr)
Referenced by XUartPsv_SetBaudRate.
XUartPsv_IsTransmitEmpty
Determine if the transmitter FIFO is empty.
InstancePtr is a pointer to the XUartPsv instance. TRUE if a byte can be sentFALSE if the Transmitter Fifo is not empty C-Style signature: u32 XUartPsv_IsTransmitEmpty(XUartPsv InstancePtr)
XUARTPSV_HW_H
by using protection macros
XUartPsv_ReadReg
Read a UART register.
BaseAddress contains the base address of the device. RegOffset contains the offset from the base address of the device. The value read from the register. C-Style signature: u32 XUartPsv_ReadReg(UINTPTR BaseAddress, int RegOffset)
Referenced by XUartPsv_CfgInitialize, XUartPsv_GetDataFormat, XUartPsv_GetFifoThreshold, XUartPsv_GetInterruptMask, XUartPsv_GetModemStatus, XUartPsv_GetOperMode, XUartPsv_GetOptions, XUartPsv_InterruptHandler, XUartPsv_IsSending, XUartPsv_ProgramCtrlReg, XUartPsv_ReceiveBuffer, XUartPsv_RecvByte, XUartPsv_SelfTest, XUartPsv_SetBaudRate, XUartPsv_SetDataFormat, XUartPsv_SetFifoThreshold, XUartPsv_SetOperMode, XUartPsv_SetOptions, XUartPsv_SetRxFifoThreshold, XUartPsv_SetTxFifoThreshold.
XUartPsv_WriteReg
Write a UART register.
BaseAddress contains the base address of the device. RegOffset contains the offset from the base address of the device. RegisterValue is the value to be written to the register. None. C-Style signature: void XUartPsv_WriteReg(UINTPTR BaseAddress, int RegOffset, u16 RegisterValue)
Referenced by XUartPsv_CfgInitialize, XUartPsv_InterruptHandler, XUartPsv_ProgramCtrlReg, XUartPsv_SendBuffer, XUartPsv_SendByte, XUartPsv_SetBaudRate, XUartPsv_SetDataFormat, XUartPsv_SetFifoThreshold, XUartPsv_SetInterruptMask, XUartPsv_SetOptions, XUartPsv_SetRxFifoThreshold, XUartPsv_SetTxFifoThreshold.
XUartPsv_IsReceiveData
Determine if there is receive data in the receiver and/or FIFO.
BaseAddress contains the base address of the device. TRUE if there is receive data, FALSE otherwise. C-Style signature: u32 XUartPsv_IsReceiveData(UINTPTR BaseAddress)
Referenced by XUartPsv_RecvByte.
XUartPsv_IsTransmitFull
Determine if a byte of data can be sent with the transmitter.
BaseAddress contains the base address of the device. TRUE if the TX FIFO is full, FALSE if a byte can be put in the FIFO. C-Style signature: u32 XUartPsv_IsTransmitFull(UINTPTR BaseAddress)
Referenced by XUartPsv_SendBuffer, XUartPsv_SendByte.
XUartPsv_IsTransmitbusy
Determine if a byte of data can be sent with the transmitter.
BaseAddress contains the base address of the device. TRUE if the TX is busy, FALSE if a byte can be put in the FIFO. C-Style signature: u32 XUartPsv_IsTransmitFull(UINTPTR BaseAddress)
Referenced by UartPsvPolledExample, XUartPsv_ProgramCtrlReg, XUartPsv_Send_NoWait.
XUARTPSV_NUM_OPTIONS
No.
of options
Referenced by XUartPsv_GetOptions, XUartPsv_SetOptions.
XUARTPSV_TOTAL_BYTES
No.
of bytes in transfer
Referenced by XUartPsv_SelfTest.