xuartpsv_intr.c
static void XUartPsv_ReceiveErrorHandler(XUartPsv *InstancePtr)
This function handles the interrupt when there is overrun error in Rx path.
InstancePtr is a pointer to the XUartPsv instance None. None.
static void XUartPsv_ReceiveDataHandler(XUartPsv *InstancePtr)
This function handles the interrupt when data is in RX FIFO.
InstancePtr is a pointer to the XUartPsv instance None. None.
static void XUartPsv_SendDataHandler(XUartPsv *InstancePtr)
This function handles the interrupt when data has been sent, the transmit FIFO is empty (transmitter holding register).
InstancePtr is a pointer to the XUartPsv instance None. None.
static void XUartPsv_ModemHandler(XUartPsv *InstancePtr)
This function handles modem interrupts.
It does not do any processing except to call the application handler to indicate a modem event. InstancePtr is a pointer to the XUartPsv instance None. None.
u32 XUartPsv_GetInterruptMask(XUartPsv *InstancePtr)
This function gets the interrupt mask.
InstancePtr is a pointer to the XUartPsv instance. The current interrupt mask. The mask indicates which interrupts are enabled. None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv_ReadReg, XUARTPSV_UARTIMSC_OFFSET.
Referenced by XUartPsv_Recv.
void XUartPsv_SetInterruptMask(XUartPsv *InstancePtr, u32 Mask)
This function sets the interrupt mask.
InstancePtr is a pointer to the XUartPsv instance Mask contains the interrupts to be enabled or disabled. A '1' enables an interrupt, and a '0' disables. None. None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUARTPSV_UARTIMSC_MASK, XUARTPSV_UARTIMSC_OFFSET, XUartPsv_WriteReg.
Referenced by UartPsvIntrExample.
void XUartPsv_SetHandler(XUartPsv *InstancePtr, XUartPsv_Handler FuncPtr, void *CallBackRef)
This function sets the handler that will be called when an event (interrupt) occurs that needs application's attention.
InstancePtr is a pointer to the XUartPsv instance FuncPtr is the pointer to the callback function. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. None. There is no assert on the CallBackRef since the driver doesn't know what it is (nor should it)
References XUartPsv::CallBackRef, XUartPsv::Handler, XUartPsv::IsReady.
Referenced by UartPsvIntrExample.
void XUartPsv_InterruptHandler(XUartPsv *InstancePtr)
This function is the interrupt handler for the driver.
It must be connected to an interrupt system by the application such that it can be called when an interrupt occurs. InstancePtr contains a pointer to the driver instance None. None.
References XUartPsv_Config::BaseAddress, XUartPsv::CallBackRef, XUartPsv::Config, XUartPsv::Handler, XUartPsv::IsReady, XUARTPSV_EVENT_PARE_FRAME_BRKE, XUartPsv_ReadReg, XUARTPSV_UARTICR_OFFSET, XUARTPSV_UARTIMSC_OFFSET, XUARTPSV_UARTRIS_BERIS, XUARTPSV_UARTRIS_CTSRMIS, XUARTPSV_UARTRIS_DCDRMIS, XUARTPSV_UARTRIS_DSRRMIS, XUARTPSV_UARTRIS_FERIS, XUARTPSV_UARTRIS_OERIS, XUARTPSV_UARTRIS_OFFSET, XUARTPSV_UARTRIS_PERIS, XUARTPSV_UARTRIS_RIRMIS, XUARTPSV_UARTRIS_RTRIS, XUARTPSV_UARTRIS_RXRIS, XUARTPSV_UARTRIS_TXRIS, XUartPsv_WriteReg.
Referenced by UartPsvIntrExample.