xuartpsv.c
XUARTPSV_MAX_BAUD_ERROR_RATE
max % error allowed
Referenced by XUartPsv_SetBaudRate.
static void XUartPsv_StubHandler(void *CallBackRef, u32 Event, u32 ByteCount)
This function is a stub handler that is the default handler such that if the application has not set the handler when interrupts are enabled, this function will be called.
CallBackRef is unused by this function. Event is unused by this function. ByteCount is unused by this function. None. None.
s32 XUartPsv_CfgInitialize(XUartPsv *InstancePtr, XUartPsv_Config *Config, UINTPTR EffectiveAddr)
Initializes a specific XUartPsv instance such that it is ready to be used.
The data format of the device is setup for 8 data bits, 1 stop bit, and no parity by default. The baud rate is set to a default value specified by Config->DefaultBaudRate if set, otherwise it is set to 19.2K baud. The receive FIFO threshold is set for 8 bytes. The default operating mode of the driver is polled mode. InstancePtr is a pointer to the XUartPsv instance. Config is a reference to a structure containing information about a specific XUartPsv driver. EffectiveAddr is the device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, pass in the physical address instead. XST_SUCCESS if initialization was successfulXST_UART_BAUD_ERROR if the baud rate is not possible because the inputclock frequency is not divisible with an acceptable amount of error The default configuration for the UART after initialization is: 19,200 bps or XPAR_DFT_BAUDRATE if defined8 data bits1 stop bitno parityFIFO's are enabled with a threshold of 16 ytesAll interrupts are disabled.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::Handler, XUartPsv_Config::InputClockHz, XUartPsv::IsReady, XUartPsv_Config::ModemPinsConnected, XUartPsvBuffer::NextBytePtr, XUartPsv::ReceiveBuffer, XUartPsvBuffer::RemainingBytes, XUartPsvBuffer::RequestedBytes, XUartPsv::SendBuffer, XUARTPSV_DFT_BAUDRATE, XUartPsv_ReadReg, XUartPsv_SetBaudRate, XUARTPSV_UARTICR_OFFSET, XUARTPSV_UARTIFLS_OFFSET, XUARTPSV_UARTIFLS_RXIFLSEL_1_2, XUARTPSV_UARTIFLS_TXIFLSEL_1_2, XUARTPSV_UARTIMSC_MASK, XUARTPSV_UARTIMSC_OFFSET, XUARTPSV_UARTLCR_FEN, XUARTPSV_UARTLCR_OFFSET, XUARTPSV_UARTLCR_PARITY_MASK, XUARTPSV_UARTLCR_PARITY_NONE, XUARTPSV_UARTLCR_STP_1_BIT, XUARTPSV_UARTLCR_STP_MASK, XUARTPSV_UARTLCR_WLEN_8_BIT, XUARTPSV_UARTLCR_WLEN_MASK, XUartPsv_WriteReg.
Referenced by UartPsvHelloWorldExample, UartPsvIntrExample, UartPsvPolledExample, UartPsvSelfTestExample.
u32 XUartPsv_Send(XUartPsv *InstancePtr, u8 *BufferPtr, u32 NumBytes)
This functions sends the specified buffer using the device in either polled or interrupt driven mode.
This function is non-blocking, if the device is busy sending data, it will return and indicate zero bytes were sent. Otherwise, it fills the TX FIFO as much as it can, and return the number of bytes sent.In a polled mode, this function will only send as much data as TX FIFO can buffer. The application may need to call it repeatedly to send the entire buffer.In interrupt mode, this function will start sending the specified buffer, then the interrupt handler will continue sending data until the entire buffer has been sent. A callback function, as specified by the application, will be called to indicate the completion of sending. InstancePtr is a pointer to the XUartPsv instance. BufferPtr is pointer to a buffer of data to be sent. NumBytes contains the number of bytes to be sent. A value of zero will stop a previous send operation that is in progress in interrupt mode. Any data that was already put into the transmit FIFO will be sent. The number of bytes actually sent. The number of bytes is not asserted so that this function may be called with a value of zero to stop an operation that is already in progress.
References XUartPsv::IsReady, XUartPsvBuffer::NextBytePtr, XUartPsvBuffer::RemainingBytes, XUartPsvBuffer::RequestedBytes, XUartPsv::SendBuffer, XUartPsv_SendBuffer.
Referenced by UartPsvHelloWorldExample, UartPsvIntrExample, UartPsvPolledExample, XUartPsv_SelfTest.
static u32 XUartPsv_SendBuffer_NoWait(XUartPsv *InstancePtr)
This function sends a buffer that has been previously specified by settingup the instance variables of the instance.This function implemented for RTOS environment and it is an internalfunction for the XUartPsv driver such that it's being called fromXUartPsv_Send_NoWait function that sets up the buffer.This function sends the specified buffer in polled mode. This functiononly sends as much data as the TX FIFO can buffer. The application mayneed to call it repeatedly to send the entire buffer. InstancePtr is a pointer to the XUartPsv instance The number of bytes actually sent None.
u32 XUartPsv_Send_NoWait(XUartPsv *InstancePtr, u8 *BufferPtr, u32 NumBytes)
This functions sends the specified buffer using the device in polled mode.This function is non-blocking, if the device is busy sending data, it willreturn and indicate zero bytes were sent. Otherwise, it fills the TX FIFOas much as it can, and return the number of bytes sent. The application mayneed to call it repeatedly to send the entire buffer.This function implemented for RTOS environment, it will check status andreturn without waiting. The caller of XUartPsv_Send_NoWait can waitbased on return value. InstancePtr is a pointer to the XUartPsv instance. BufferPtr is pointer to a buffer of data to be sent. NumBytes contains the number of bytes to be sent. A value of zero will stop a previous send operation that is in progressin interrupt mode. Any data that was already put into thetransmit FIFO will be sent.- The number of bytes actually sent, if data successfully sent - 0, if TX is busy. The caller of XUartPsv_Send_NoWait canwait if return 0. The number of bytes is not asserted so that this function may be called witha value of zero to stop an operation that is already in progress.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUartPsvBuffer::NextBytePtr, XUartPsvBuffer::RemainingBytes, XUartPsvBuffer::RequestedBytes, XUartPsv::SendBuffer, XUartPsv_IsTransmitbusy.
u32 XUartPsv_Recv(XUartPsv *InstancePtr, u8 *BufferPtr, u32 NumBytes)
This function attempts to receive a specified number of bytes of data from the device and store it into the specified buffer.
This function works for both polled or interrupt driven modes. It is non-blocking.In a polled mode, this function will only receive the data already in the RX FIFO. The application may need to call it repeatedly to receive the entire buffer. Polled mode is the default mode of operation for the device.In interrupt mode, this function will start the receiving, if not the entire buffer has been received, the interrupt handler will continue receiving data until the entire buffer has been received. A callback function, as specified by the application, will be called to indicate the completion of the receiving or error conditions. InstancePtr is a pointer to the XUartPsv instance BufferPtr is pointer to buffer for data to be received into NumBytes is the number of bytes to be received. A value of zero will stop a previous receive operation that is in progress in interrupt mode. The number of bytes received. The number of bytes is not asserted so that this function may be called with a value of zero to stop an operation that is already in progress.
References XUartPsv::IsReady, XUartPsvBuffer::NextBytePtr, XUartPsv::ReceiveBuffer, XUartPsvBuffer::RemainingBytes, XUartPsvBuffer::RequestedBytes, XUartPsv_GetInterruptMask, XUartPsv_ReceiveBuffer.
Referenced by UartPsvIntrExample, UartPsvPolledExample, XUartPsv_SelfTest.
u32 XUartPsv_SendBuffer(XUartPsv *InstancePtr)
This function sends a buffer that has been previously specified by setting up the instance variables of the instance.
This function is an internal function for the XUartPsv driver such that it may be called from a shell function that sets up the buffer or from an interrupt handler.This function sends the specified buffer in either polled or interrupt driven modes. This function is non-blocking.In a polled mode, this function only sends as much data as the TX FIFO can buffer. The application may need to call it repeatedly to send the entire buffer.In interrupt mode, this function starts the sending of the buffer, if not the entire buffer has been sent, then the interrupt handler continues the sending until the entire buffer has been sent. A callback function, as specified by the application, will be called to indicate the completion of sending. InstancePtr is a pointer to the XUartPsv instance The number of bytes actually sent None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsvBuffer::NextBytePtr, XUartPsvBuffer::RemainingBytes, XUartPsv::SendBuffer, XUartPsv_IsTransmitFull, XUARTPSV_UARTDR_OFFSET, XUARTPSV_UARTFR_BUSY, XUARTPSV_UARTFR_OFFSET, XUartPsv_WriteReg.
Referenced by XUartPsv_Send.
u32 XUartPsv_ReceiveBuffer(XUartPsv *InstancePtr)
This function receives a buffer that has been previously specified by setting up the instance variables of the instance.
This function is an internal function, and it may be called from a shell function that sets up the buffer or from an interrupt handler.This function attempts to receive a specified number of bytes from the device and store it into the specified buffer. This function works for either polled or interrupt driven modes. It is non-blocking.In polled mode, this function only receives as much data as in the RX FIFO. The application may need to call it repeatedly to receive the entire buffer. Polled mode is the default mode for the driver.In interrupt mode, this function starts the receiving, if not the entire buffer has been received, the interrupt handler will continue until the entire buffer has been received. A callback function, as specified by the application, will be called to indicate the completion of the receiving or error conditions. InstancePtr is a pointer to the XUartPsv instance The number of bytes received. None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsvBuffer::NextBytePtr, XUartPsv::ReceiveBuffer, XUartPsvBuffer::RemainingBytes, XUartPsv_ReadReg, XUARTPSV_UARTDR_OFFSET, XUARTPSV_UARTFR_OFFSET, XUARTPSV_UARTFR_RXFE.
Referenced by XUartPsv_Recv.
s32 XUartPsv_SetBaudRate(XUartPsv *InstancePtr, u32 BaudRate)
Sets the baud rate for the device.
Checks the input value for validity and also verifies that the requested rate can be configured to within the maximum error range specified by XUARTPSV_MAX_BAUD_ERROR_RATE. If the provided rate is not possible, the current setting is unchanged. InstancePtr is a pointer to the XUartPsv instance BaudRate to be set XST_SUCCESS if everything configured as expectedXST_UART_BAUD_ERROR if the requested rate is not available because there was too much error None.
References XUartPsv_Config::BaseAddress, XUartPsv::BaudRate, XUartPsv::Config, XUartPsv_Config::InputClockHz, XUartPsv::IsReady, XUartPsv_DisableUart, XUartPsv_EnableUart, XUARTPSV_MAX_BAUD_ERROR_RATE, XUARTPSV_MAX_RATE, XUARTPSV_MIN_RATE, XUartPsv_ReadReg, XUARTPSV_UARTFBRD_OFFSET, XUARTPSV_UARTIBRD_OFFSET, XUARTPSV_UARTLCR_OFFSET, XUartPsv_WriteReg.
Referenced by XUartPsv_CfgInitialize, XUartPsv_SetDataFormat.
void XUartPsv_ProgramCtrlReg(XUartPsv *InstancePtr, u32 CtrlRegister)
This function reprograms the control register according to the following sequence mentioned in the TRM.
Sequence to Program Control Register. Disable UARTCheck if BusyFlush the transmit FIFOProgram the Control RegisterEnable the Uart InstancePtr is a pointer to the XUartPsv instance CtrlRegister value to be written None. None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv_IsTransmitbusy, XUartPsv_ReadReg, XUARTPSV_UARTCR_OFFSET, XUARTPSV_UARTCR_UARTEN, XUARTPSV_UARTLCR_FEN, XUARTPSV_UARTLCR_OFFSET, XUartPsv_WriteReg.
Referenced by XUartPsv_SelfTest, XUartPsv_SetOperMode.
void XUartPsv_CleanupRx(XUartPsv *InstancePtr)
This function is a cleanup function to allow resetting Rx NextBytePtr, RemainingBytes and RequestedBytes.
None. None.
References XUartPsvBuffer::NextBytePtr, XUartPsv::ReceiveBuffer, XUartPsvBuffer::RemainingBytes, XUartPsvBuffer::RequestedBytes.
void XUartPsv_CleanupTx(XUartPsv *InstancePtr)
This function is a cleanup function to allow resetting Tx NextBytePtr, RemainingBytes and RequestedBytes.
None. None.
References XUartPsvBuffer::NextBytePtr, XUartPsvBuffer::RemainingBytes, XUartPsvBuffer::RequestedBytes, XUartPsv::SendBuffer.