xuartpsv_options.c
XUARTPSV_NUM_OPTIONS
No.
of options
Referenced by XUartPsv_GetOptions, XUartPsv_SetOptions.
Mapping XUartPsv_OptionsTable[][]
u16 XUartPsv_GetOptions(XUartPsv *InstancePtr)
Gets the options for the specified driver instance.
The options are implemented as bit masks such that multiple options may be enabled or disabled simultaneously. InstancePtr is a pointer to the XUartPsv instance. The current options for the UART. The options are bit masks that are contained in the file xuartpsv.h and named XUARTPSV_OPTION_*. None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUARTPSV_NUM_OPTIONS, XUartPsv_ReadReg.
void XUartPsv_SetOptions(XUartPsv *InstancePtr, u16 Options)
Sets the options for the specified driver instance.
The options are implemented as bit masks such that multiple options may be enabled or disabled simultaneously.The GetOptions function may be called to retrieve the currently enabled options. The result is ORed in the desired new settings to be enabled and ANDed with the inverse to clear the settings to be disabled. The resulting value is then used as the options for the SetOption function call. InstancePtr is a pointer to the XUartPsv instance. Options contains the options to be set which are bit masks contained in the file xuartpsv.h and named XUARTPSV_OPTION_*. None. None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUARTPSV_NUM_OPTIONS, XUartPsv_ReadReg, XUartPsv_WriteReg.
u8 XUartPsv_GetFifoThreshold(XUartPsv *InstancePtr)
This function gets the Tx and Rx FIFO trigger level.
The receive or transmit trigger level specifies the number of bytes in the FIFO that cause a receive or transmit data event (interrupt) to be generated. InstancePtr is a pointer to the XUartPsv instance. The current receive FIFO trigger level. This is a value from 0-63. None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUartPsv_ReadReg, XUARTPSV_UARTIFLS_OFFSET, XUARTPSV_UARTIFLS_RXIFLSEL_MASK, XUARTPSV_UARTIFLS_TXIFLSEL_MASK.
void XUartPsv_SetFifoThreshold(XUartPsv *InstancePtr, u8 TriggerLevel)
This functions sets the Tx and Rx FIFO trigger level to the 'TriggerLevel' argument.
The same value is set for Tx and Rx FIFOs. The receive or transmit trigger level specifies the number of bytes in the FIFO that cause a receive or transmit data event (interrupt) to be generated. InstancePtr is a pointer to the XUartPsv instance. TriggerLevel contains the trigger level to set. This is a value from 0-7 None None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUartPsv_ReadReg, XUARTPSV_UARTIFLS_OFFSET, XUARTPSV_UARTIFLS_RXIFLSEL_MASK, XUARTPSV_UARTIFLS_RXIFLSEL_SHIFT, XUARTPSV_UARTIFLS_TXIFLSEL_MASK, XUARTPSV_UARTIFLS_TXIFLSEL_SHIFT, XUartPsv_WriteReg.
void XUartPsv_SetTxFifoThreshold(XUartPsv *InstancePtr, u8 TriggerLevel)
This functions sets the Tx FIFO trigger level to the 'TriggerLevel' argument.
This value is set for Tx FIFO. Rx FIFO trigger level is unchanged. The receive or transmit trigger level specifies the number of bytes in the FIFO that cause a receive or transmit data event (interrupt) to be generated. InstancePtr is a pointer to the XUartPsv instance. TriggerLevel contains the trigger level to set. This is a value from 0-4 (XUARTPSV_UARTIFLS_TXIFLSEL_1_8 - XUARTPSV_UARTIFLS_TXIFLSEL_7_8) None None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUartPsv_ReadReg, XUARTPSV_UARTIFLS_OFFSET, XUARTPSV_UARTIFLS_TXIFLSEL_MASK, XUARTPSV_UARTIFLS_TXIFLSEL_SHIFT, XUartPsv_WriteReg.
Referenced by UartPsvIntrExample.
void XUartPsv_SetRxFifoThreshold(XUartPsv *InstancePtr, u8 TriggerLevel)
This functions sets the Rx FIFO trigger level to the 'TriggerLevel' argument.
This value is set for Rx FIFO. Tx FIFO trigger level is unchanged. The receive or transmit trigger level specifies the number of bytes in the FIFO that cause a receive or transmit data event (interrupt) to be generated. InstancePtr is a pointer to the XUartPsv instance. TriggerLevel contains the trigger level to set. This is a value from 0-32 (XUARTPSV_UARTIFLS_RXIFLSEL_1_8 - XUARTPSV_UARTIFLS_RXIFLSEL_7_8) None None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUartPsv_ReadReg, XUARTPSV_UARTIFLS_OFFSET, XUARTPSV_UARTIFLS_RXIFLSEL_MASK, XUartPsv_WriteReg.
Referenced by UartPsvIntrExample.
u16 XUartPsv_GetModemStatus(XUartPsv *InstancePtr)
This function gets the modem status from the specified UART.
The modem status indicates any changes of the modem signals. This function allows the modem status to be read in a polled mode. The modem status is updated whenever it is read such that reading it twice may not yield the same results. InstancePtr is a pointer to the XUartPsv instance. The modem status which are bit masks that are contained in the file xuartpsv.h and named XUARTPSV_UARTRIS_*. The bit masks used for the modem status are the exact bits of the modem status register with no abstraction.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUartPsv_ReadReg, XUARTPSV_UARTRIS_OFFSET.
u32 XUartPsv_IsSending(XUartPsv *InstancePtr)
This function determines if the specified UART is sending data.
InstancePtr is a pointer to the XUartPsv instance. TRUE if the UART is sending dataFALSE if UART is not sending data None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUartPsv_ReadReg, XUARTPSV_UARTFR_BUSY, XUARTPSV_UARTFR_OFFSET, XUARTPSV_UARTFR_TXFE.
u8 XUartPsv_GetOperMode(XUartPsv *InstancePtr)
This function gets the operational mode of the UART.
The UART can operate in one of four modes: Normal, Local Loopback, Remote Loopback, or automatic echo. InstancePtr is a pointer to the XUartPsv instance. The operational mode is specified by constants defined in xuartpsv.h. The constants are named XUARTPSV_OPER_MODE_* None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUARTPSV_OPER_MODE_LOCAL_LOOP, XUARTPSV_OPER_MODE_NORMAL, XUartPsv_ReadReg, XUARTPSV_UARTCR_LBE, XUARTPSV_UARTCR_MODE_MASK, XUARTPSV_UARTCR_MODE_NORMAL, XUARTPSV_UARTCR_MODE_SHIFT, XUARTPSV_UARTCR_OFFSET.
void XUartPsv_SetOperMode(XUartPsv *InstancePtr, u8 OperationMode)
This function sets the operational mode of the UART.
The UART can operate in one of four modes: Normal, Local Loopback, Remote Loopback, or automatic echo. InstancePtr is a pointer to the XUartPsv instance. OperationMode is the mode of the UART. None. None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUARTPSV_OPER_MODE_LOCAL_LOOP, XUARTPSV_OPER_MODE_NORMAL, XUartPsv_ProgramCtrlReg, XUartPsv_ReadReg, XUARTPSV_UARTCR_LBE, XUARTPSV_UARTCR_MODE_MASK, XUARTPSV_UARTCR_MODE_NORMAL, XUARTPSV_UARTCR_OFFSET.
Referenced by UartPsvIntrExample, UartPsvPolledExample, XUartPsv_SelfTest.
s32 XUartPsv_SetDataFormat(XUartPsv *InstancePtr, XUartPsvFormat *FormatPtr)
Sets the data format for the device.
The data format includes the baud rate, number of data bits, number of stop bits, and parity. It is the caller's responsibility to ensure that the UART is not sending or receiving data when this function is called. InstancePtr is a pointer to the XUartPsv instance. FormatPtr is a pointer to a format structure containing the data format to be set. XST_SUCCESS if the data format was successfully set.XST_UART_BAUD_ERROR indicates the baud rate could not be set because of the amount of error with the baud rate and the input clock frequency.XST_INVALID_PARAM if one of the parameters was not valid. The data types in the format type, data bits and parity, are 32 bit fields to prevent a compiler warning. The asserts in this function will cause a warning if these fields are bytes.
References XUartPsv_Config::BaseAddress, XUartPsvFormat::BaudRate, XUartPsv::Config, XUartPsvFormat::DataBits, XUartPsv::IsReady, XUartPsvFormat::Parity, XUartPsvFormat::StopBits, XUARTPSV_FORMAT_2_STOP_BIT, XUARTPSV_FORMAT_8_BITS, XUARTPSV_FORMAT_EN_PARITY, XUARTPSV_FORMAT_EN_STICK_PARITY, XUARTPSV_FORMAT_EN_STICK_PARITY_SHIFT, XUARTPSV_FORMAT_EVEN_PARITY, XUARTPSV_FORMAT_EVEN_PARITY_SHIFT, XUARTPSV_FORMAT_PARITY_MASK, XUartPsv_ReadReg, XUartPsv_SetBaudRate, XUARTPSV_UARTLCR_OFFSET, XUARTPSV_UARTLCR_PARITY_MASK, XUARTPSV_UARTLCR_PARITY_SHIFT, XUARTPSV_UARTLCR_STP_MASK, XUARTPSV_UARTLCR_STP_SHIFT, XUARTPSV_UARTLCR_WLEN_MASK, XUARTPSV_UARTLCR_WLEN_SHIFT, XUartPsv_WriteReg.
void XUartPsv_GetDataFormat(XUartPsv *InstancePtr, XUartPsvFormat *FormatPtr)
Gets the data format for the specified UART.
The data format includes the baud rate, number of data bits, number of stop bits, and parity. InstancePtr is a pointer to the XUartPsv instance. FormatPtr is a pointer to a format structure that will contain the data format after this call completes. None. None.
References XUartPsv_Config::BaseAddress, XUartPsvFormat::BaudRate, XUartPsv::BaudRate, XUartPsv::Config, XUartPsvFormat::DataBits, XUartPsv::IsReady, XUartPsvFormat::Parity, XUartPsvFormat::StopBits, XUartPsv_ReadReg, XUARTPSV_UARTLCR_OFFSET, XUARTPSV_UARTLCR_PARITY_MASK, XUARTPSV_UARTLCR_PARITY_SHIFT, XUARTPSV_UARTLCR_STP_MASK, XUARTPSV_UARTLCR_STP_SHIFT, XUARTPSV_UARTLCR_WLEN_MASK, XUARTPSV_UARTLCR_WLEN_SHIFT.