xuartpsv_sinit.c
XUartPsv_Config * XUartPsv_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XUartPsv_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xuartpsv.h for the definition of XUartPsv_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XUartPsv_Config::Name, XUartPsv_ConfigTable.
Referenced by UartPsvHelloWorldExample, UartPsvIntrExample, UartPsvPolledExample, UartPsvSelfTestExample.