xuartpsv_selftest.c
XUARTPSV_TOTAL_BYTES
No.
of bytes in transfer
Referenced by XUartPsv_SelfTest.
u8 TestString[XUARTPSV_TOTAL_BYTES][XUARTPSV_TOTAL_BYTES]
u8 ReturnString[XUARTPSV_TOTAL_BYTES][XUARTPSV_TOTAL_BYTES]
s32 XUartPsv_SelfTest(XUartPsv *InstancePtr)
This function runs a self-test on the driver and hardware device.
This self test performs a local loopback and verifies data can be sent and received.The time for this test is proportional to the baud rate that has been set prior to calling this function.The mode and control registers are restored before return. InstancePtr is a pointer to the XUartPsv instance XST_SUCCESS if the test was successfulXST_UART_TEST_FAIL if the test failed looping back the data This function can hang if the hardware is not functioning properly.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUARTPSV_OPER_MODE_LOCAL_LOOP, XUartPsv_ProgramCtrlReg, XUartPsv_ReadReg, XUartPsv_Recv, XUartPsv_Send, XUartPsv_SetOperMode, XUARTPSV_TOTAL_BYTES, XUARTPSV_UARTCR_OFFSET, XUARTPSV_UARTFR_OFFSET, XUARTPSV_UARTFR_RXFE.
Referenced by UartPsvHelloWorldExample, UartPsvIntrExample, UartPsvPolledExample, UartPsvSelfTestExample.