xuartpsv.h
XUARTPSV_OPTION_SET_BREAK
These constants specify the options that may be set or retrieved with the driver, each is a unique bit mask such that multiple options may be specified.
These constants indicate the available options in active state.Starts break transmission
XUARTPSV_OPTION_STOP_BREAK
Stops break transmission.
XUARTPSV_OPTION_RESET_TMOUT
Reset the receive timeout.
XUARTPSV_OPTION_RESET_TX
Reset the transmitter.
XUARTPSV_OPTION_RESET_RX
Reset the receiver.
XUARTPSV_OPTION_ASSERT_RTS
Assert the RTS bit.
XUARTPSV_OPTION_ASSERT_DTR
Assert the DTR bit.
XUARTPSV_OPTION_SET_FCM
Turn on flow control mode.
XUARTPSV_OPER_MODE_NORMAL
Normal Mode.
Referenced by UartPsvIntrExample, UartPsvPolledExample, XUartPsv_GetOperMode, XUartPsv_SetOperMode.
XUARTPSV_OPER_MODE_LOCAL_LOOP
Local Loop back Mode.
Referenced by UartPsvIntrExample, UartPsvPolledExample, XUartPsv_GetOperMode, XUartPsv_SelfTest, XUartPsv_SetOperMode.
XUARTPSV_FORMAT_8_BITS
8 data bits
Referenced by XUartPsv_SetDataFormat.
XUARTPSV_FORMAT_7_BITS
7 data bits
XUARTPSV_FORMAT_6_BITS
6 data bits
XUARTPSV_FORMAT_5_BITS
5 data bits
XUARTPSV_FORMAT_NO_PARITY
No parity.
XUARTPSV_FORMAT_EN_PARITY
Enable parity.
Referenced by XUartPsv_SetDataFormat.
XUARTPSV_FORMAT_EVEN_PARITY
Even parity.
Referenced by XUartPsv_SetDataFormat.
XUARTPSV_FORMAT_ODD_PARITY
Odd parity.
XUARTPSV_FORMAT_EN_STICK_PARITY
Stick parity.
Referenced by XUartPsv_SetDataFormat.
XUARTPSV_FORMAT_NO_STICK_PARITY
Stick parity.
XUARTPSV_FORMAT_PARITY_MASK
Format parity mask.
Referenced by XUartPsv_SetDataFormat.
XUARTPSV_FORMAT_EVEN_PARITY_SHIFT
Even parity shift.
Referenced by XUartPsv_SetDataFormat.
XUARTPSV_FORMAT_EN_STICK_PARITY_SHIFT
Stick parity shift.
Referenced by XUartPsv_SetDataFormat.
XUARTPSV_FORMAT_2_STOP_BIT
2 stop bits
Referenced by XUartPsv_SetDataFormat.
XUARTPSV_FORMAT_1_STOP_BIT
1 stop bit
XUARTPSV_EVENT_RECV_DATA
Data receiving done.
Referenced by Handler.
XUARTPSV_EVENT_RECV_TOUT
A receive timeout occurred.
Referenced by Handler.
XUARTPSV_EVENT_SENT_DATA
Data transmission done.
Referenced by Handler.
XUARTPSV_EVENT_RECV_ERROR
A receive error detected.
Referenced by Handler.
XUARTPSV_EVENT_MODEM
Modem status changed.
XUARTPSV_EVENT_PARE_FRAME_BRKE
A receive parity, frame,break error detected.
Referenced by Handler, XUartPsv_InterruptHandler.
XUARTPSV_EVENT_RECV_ORERR
A receive overrun error detected.
Referenced by Handler.
XUARTPSV_H
by using protection macros
XUARTPSV_MAX_RATE
Maximum baud rate.
Referenced by XUartPsv_SetBaudRate.
XUARTPSV_MIN_RATE
Minimum baud rate.
Referenced by XUartPsv_SetBaudRate.
XUARTPSV_DFT_BAUDRATE
Default baud rate.
Referenced by XUartPsv_CfgInitialize.
TIMEOUT_COUNTER
XUartPsv_GetChannelStatus
Get the UART Channel Status Register.
InstancePtr is a pointer to the XUartPsv instance. The value read from the register. C-Style signature: u16 XUartPsv_GetChannelStatus(XUartPsv *InstancePtr)
XUartPsv_GetModeControl
Get the UART Mode Control Register.
InstancePtr is a pointer to the XUartPsv instance. The value read from the register. C-Style signature: u32 XUartPsv_GetControl(XUartPsv *InstancePtr)
XUartPsv_SetModeControl
Set the UART Mode Control Register.
InstancePtr is a pointer to the XUartPsv instance. RegisterValue is the value to be written to the register. None. C-Style signature: void XUartPsv_SetModeControl(XUartPsv *InstancePtr, u16 RegisterValue)
XUartPsv_EnableUart
Enable the transmitter and receiver of the UART.
InstancePtr is a pointer to the XUartPsv instance. None. C-Style signature: void XUartPsv_EnableUart(XUartPsv *InstancePtr)
Referenced by XUartPsv_SetBaudRate.
XUartPsv_DisableUart
Disable the transmitter and receiver of the UART.
InstancePtr is a pointer to the XUartPsv instance. None. C-Style signature: void XUartPsv_DisableUart(XUartPsv *InstancePtr)
Referenced by XUartPsv_SetBaudRate.
XUartPsv_IsTransmitEmpty
Determine if the transmitter FIFO is empty.
InstancePtr is a pointer to the XUartPsv instance. TRUE if a byte can be sentFALSE if the Transmitter Fifo is not empty C-Style signature: u32 XUartPsv_IsTransmitEmpty(XUartPsv InstancePtr)
typedef void(* XUartPsv_Handler)(void *CallBackRef, u32 Event, u32 EventData))(void *CallBackRef, u32 Event, u32 EventData)
This data type defines a handler that an application defines to communicate with interrupt system to retrieve state information about an application.
CallBackRef is a callback reference passed in by the upper layer when setting the handler, and is passed back to the upper layer when the handler is called. It is used to find the device driver instance. Event contains one of the event constants indicating events that have occurred. EventData contains the number of bytes sent or received at the time of the call for send and receive events and contains the modem status for modem events.
XUartPsv_Config XUartPsv_ConfigTable[][]
Config structure.
Referenced by XUartPsv_LookupConfig.
XUartPsv_Config * XUartPsv_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XUartPsv_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xuartpsv.h for the definition of XUartPsv_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XUartPsv_Config::Name, XUartPsv_ConfigTable.
Referenced by UartPsvHelloWorldExample, UartPsvIntrExample, UartPsvPolledExample, UartPsvSelfTestExample.
s32 XUartPsv_CfgInitialize(XUartPsv *InstancePtr, XUartPsv_Config *Config, UINTPTR EffectiveAddr)
Initializes a specific XUartPsv instance such that it is ready to be used.
The data format of the device is setup for 8 data bits, 1 stop bit, and no parity by default. The baud rate is set to a default value specified by Config->DefaultBaudRate if set, otherwise it is set to 19.2K baud. The receive FIFO threshold is set for 8 bytes. The default operating mode of the driver is polled mode. InstancePtr is a pointer to the XUartPsv instance. Config is a reference to a structure containing information about a specific XUartPsv driver. EffectiveAddr is the device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, pass in the physical address instead. XST_SUCCESS if initialization was successfulXST_UART_BAUD_ERROR if the baud rate is not possible because the inputclock frequency is not divisible with an acceptable amount of error The default configuration for the UART after initialization is: 19,200 bps or XPAR_DFT_BAUDRATE if defined8 data bits1 stop bitno parityFIFO's are enabled with a threshold of 16 ytesAll interrupts are disabled.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::Handler, XUartPsv_Config::InputClockHz, XUartPsv::IsReady, XUartPsv_Config::ModemPinsConnected, XUartPsvBuffer::NextBytePtr, XUartPsv::ReceiveBuffer, XUartPsvBuffer::RemainingBytes, XUartPsvBuffer::RequestedBytes, XUartPsv::SendBuffer, XUARTPSV_DFT_BAUDRATE, XUartPsv_ReadReg, XUartPsv_SetBaudRate, XUARTPSV_UARTICR_OFFSET, XUARTPSV_UARTIFLS_OFFSET, XUARTPSV_UARTIFLS_RXIFLSEL_1_2, XUARTPSV_UARTIFLS_TXIFLSEL_1_2, XUARTPSV_UARTIMSC_MASK, XUARTPSV_UARTIMSC_OFFSET, XUARTPSV_UARTLCR_FEN, XUARTPSV_UARTLCR_OFFSET, XUARTPSV_UARTLCR_PARITY_MASK, XUARTPSV_UARTLCR_PARITY_NONE, XUARTPSV_UARTLCR_STP_1_BIT, XUARTPSV_UARTLCR_STP_MASK, XUARTPSV_UARTLCR_WLEN_8_BIT, XUARTPSV_UARTLCR_WLEN_MASK, XUartPsv_WriteReg.
Referenced by UartPsvHelloWorldExample, UartPsvIntrExample, UartPsvPolledExample, UartPsvSelfTestExample.
u32 XUartPsv_Send(XUartPsv *InstancePtr, u8 *BufferPtr, u32 NumBytes)
This functions sends the specified buffer using the device in either polled or interrupt driven mode.
This function is non-blocking, if the device is busy sending data, it will return and indicate zero bytes were sent. Otherwise, it fills the TX FIFO as much as it can, and return the number of bytes sent.In a polled mode, this function will only send as much data as TX FIFO can buffer. The application may need to call it repeatedly to send the entire buffer.In interrupt mode, this function will start sending the specified buffer, then the interrupt handler will continue sending data until the entire buffer has been sent. A callback function, as specified by the application, will be called to indicate the completion of sending. InstancePtr is a pointer to the XUartPsv instance. BufferPtr is pointer to a buffer of data to be sent. NumBytes contains the number of bytes to be sent. A value of zero will stop a previous send operation that is in progress in interrupt mode. Any data that was already put into the transmit FIFO will be sent. The number of bytes actually sent. The number of bytes is not asserted so that this function may be called with a value of zero to stop an operation that is already in progress.
References XUartPsv::IsReady, XUartPsvBuffer::NextBytePtr, XUartPsvBuffer::RemainingBytes, XUartPsvBuffer::RequestedBytes, XUartPsv::SendBuffer, XUartPsv_SendBuffer.
Referenced by UartPsvHelloWorldExample, UartPsvIntrExample, UartPsvPolledExample, XUartPsv_SelfTest.
u32 XUartPsv_Recv(XUartPsv *InstancePtr, u8 *BufferPtr, u32 NumBytes)
This function attempts to receive a specified number of bytes of data from the device and store it into the specified buffer.
This function works for both polled or interrupt driven modes. It is non-blocking.In a polled mode, this function will only receive the data already in the RX FIFO. The application may need to call it repeatedly to receive the entire buffer. Polled mode is the default mode of operation for the device.In interrupt mode, this function will start the receiving, if not the entire buffer has been received, the interrupt handler will continue receiving data until the entire buffer has been received. A callback function, as specified by the application, will be called to indicate the completion of the receiving or error conditions. InstancePtr is a pointer to the XUartPsv instance BufferPtr is pointer to buffer for data to be received into NumBytes is the number of bytes to be received. A value of zero will stop a previous receive operation that is in progress in interrupt mode. The number of bytes received. The number of bytes is not asserted so that this function may be called with a value of zero to stop an operation that is already in progress.
References XUartPsv::IsReady, XUartPsvBuffer::NextBytePtr, XUartPsv::ReceiveBuffer, XUartPsvBuffer::RemainingBytes, XUartPsvBuffer::RequestedBytes, XUartPsv_GetInterruptMask, XUartPsv_ReceiveBuffer.
Referenced by UartPsvIntrExample, UartPsvPolledExample, XUartPsv_SelfTest.
s32 XUartPsv_SetBaudRate(XUartPsv *InstancePtr, u32 BaudRate)
Sets the baud rate for the device.
Checks the input value for validity and also verifies that the requested rate can be configured to within the maximum error range specified by XUARTPSV_MAX_BAUD_ERROR_RATE. If the provided rate is not possible, the current setting is unchanged. InstancePtr is a pointer to the XUartPsv instance BaudRate to be set XST_SUCCESS if everything configured as expectedXST_UART_BAUD_ERROR if the requested rate is not available because there was too much error None.
References XUartPsv_Config::BaseAddress, XUartPsv::BaudRate, XUartPsv::Config, XUartPsv_Config::InputClockHz, XUartPsv::IsReady, XUartPsv_DisableUart, XUartPsv_EnableUart, XUARTPSV_MAX_BAUD_ERROR_RATE, XUARTPSV_MAX_RATE, XUARTPSV_MIN_RATE, XUartPsv_ReadReg, XUARTPSV_UARTFBRD_OFFSET, XUARTPSV_UARTIBRD_OFFSET, XUARTPSV_UARTLCR_OFFSET, XUartPsv_WriteReg.
Referenced by XUartPsv_CfgInitialize, XUartPsv_SetDataFormat.
void XUartPsv_ProgramCtrlReg(XUartPsv *InstancePtr, u32 CtrlRegister)
This function reprograms the control register according to the following sequence mentioned in the TRM.
Sequence to Program Control Register. Disable UARTCheck if BusyFlush the transmit FIFOProgram the Control RegisterEnable the Uart InstancePtr is a pointer to the XUartPsv instance CtrlRegister value to be written None. None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv_IsTransmitbusy, XUartPsv_ReadReg, XUARTPSV_UARTCR_OFFSET, XUARTPSV_UARTCR_UARTEN, XUARTPSV_UARTLCR_FEN, XUARTPSV_UARTLCR_OFFSET, XUartPsv_WriteReg.
Referenced by XUartPsv_SelfTest, XUartPsv_SetOperMode.
void XUartPsv_CleanupRx(XUartPsv *InstancePtr)
This function is a cleanup function to allow resetting Rx NextBytePtr, RemainingBytes and RequestedBytes.
None. None.
References XUartPsvBuffer::NextBytePtr, XUartPsv::ReceiveBuffer, XUartPsvBuffer::RemainingBytes, XUartPsvBuffer::RequestedBytes.
void XUartPsv_CleanupTx(XUartPsv *InstancePtr)
This function is a cleanup function to allow resetting Tx NextBytePtr, RemainingBytes and RequestedBytes.
None. None.
References XUartPsvBuffer::NextBytePtr, XUartPsvBuffer::RemainingBytes, XUartPsvBuffer::RequestedBytes, XUartPsv::SendBuffer.
void XUartPsv_SetOptions(XUartPsv *InstancePtr, u16 Options)
Sets the options for the specified driver instance.
The options are implemented as bit masks such that multiple options may be enabled or disabled simultaneously.The GetOptions function may be called to retrieve the currently enabled options. The result is ORed in the desired new settings to be enabled and ANDed with the inverse to clear the settings to be disabled. The resulting value is then used as the options for the SetOption function call. InstancePtr is a pointer to the XUartPsv instance. Options contains the options to be set which are bit masks contained in the file xuartpsv.h and named XUARTPSV_OPTION_*. None. None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUARTPSV_NUM_OPTIONS, XUartPsv_ReadReg, XUartPsv_WriteReg.
u16 XUartPsv_GetOptions(XUartPsv *InstancePtr)
Gets the options for the specified driver instance.
The options are implemented as bit masks such that multiple options may be enabled or disabled simultaneously. InstancePtr is a pointer to the XUartPsv instance. The current options for the UART. The options are bit masks that are contained in the file xuartpsv.h and named XUARTPSV_OPTION_*. None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUARTPSV_NUM_OPTIONS, XUartPsv_ReadReg.
void XUartPsv_SetFifoThreshold(XUartPsv *InstancePtr, u8 TriggerLevel)
This functions sets the Tx and Rx FIFO trigger level to the 'TriggerLevel' argument.
The same value is set for Tx and Rx FIFOs. The receive or transmit trigger level specifies the number of bytes in the FIFO that cause a receive or transmit data event (interrupt) to be generated. InstancePtr is a pointer to the XUartPsv instance. TriggerLevel contains the trigger level to set. This is a value from 0-7 None None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUartPsv_ReadReg, XUARTPSV_UARTIFLS_OFFSET, XUARTPSV_UARTIFLS_RXIFLSEL_MASK, XUARTPSV_UARTIFLS_RXIFLSEL_SHIFT, XUARTPSV_UARTIFLS_TXIFLSEL_MASK, XUARTPSV_UARTIFLS_TXIFLSEL_SHIFT, XUartPsv_WriteReg.
void XUartPsv_SetTxFifoThreshold(XUartPsv *InstancePtr, u8 TriggerLevel)
This functions sets the Tx FIFO trigger level to the 'TriggerLevel' argument.
This value is set for Tx FIFO. Rx FIFO trigger level is unchanged. The receive or transmit trigger level specifies the number of bytes in the FIFO that cause a receive or transmit data event (interrupt) to be generated. InstancePtr is a pointer to the XUartPsv instance. TriggerLevel contains the trigger level to set. This is a value from 0-4 (XUARTPSV_UARTIFLS_TXIFLSEL_1_8 - XUARTPSV_UARTIFLS_TXIFLSEL_7_8) None None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUartPsv_ReadReg, XUARTPSV_UARTIFLS_OFFSET, XUARTPSV_UARTIFLS_TXIFLSEL_MASK, XUARTPSV_UARTIFLS_TXIFLSEL_SHIFT, XUartPsv_WriteReg.
Referenced by UartPsvIntrExample.
void XUartPsv_SetRxFifoThreshold(XUartPsv *InstancePtr, u8 TriggerLevel)
This functions sets the Rx FIFO trigger level to the 'TriggerLevel' argument.
This value is set for Rx FIFO. Tx FIFO trigger level is unchanged. The receive or transmit trigger level specifies the number of bytes in the FIFO that cause a receive or transmit data event (interrupt) to be generated. InstancePtr is a pointer to the XUartPsv instance. TriggerLevel contains the trigger level to set. This is a value from 0-32 (XUARTPSV_UARTIFLS_RXIFLSEL_1_8 - XUARTPSV_UARTIFLS_RXIFLSEL_7_8) None None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUartPsv_ReadReg, XUARTPSV_UARTIFLS_OFFSET, XUARTPSV_UARTIFLS_RXIFLSEL_MASK, XUartPsv_WriteReg.
Referenced by UartPsvIntrExample.
u8 XUartPsv_GetFifoThreshold(XUartPsv *InstancePtr)
This function gets the Tx and Rx FIFO trigger level.
The receive or transmit trigger level specifies the number of bytes in the FIFO that cause a receive or transmit data event (interrupt) to be generated. InstancePtr is a pointer to the XUartPsv instance. The current receive FIFO trigger level. This is a value from 0-63. None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUartPsv_ReadReg, XUARTPSV_UARTIFLS_OFFSET, XUARTPSV_UARTIFLS_RXIFLSEL_MASK, XUARTPSV_UARTIFLS_TXIFLSEL_MASK.
u16 XUartPsv_GetModemStatus(XUartPsv *InstancePtr)
This function gets the modem status from the specified UART.
The modem status indicates any changes of the modem signals. This function allows the modem status to be read in a polled mode. The modem status is updated whenever it is read such that reading it twice may not yield the same results. InstancePtr is a pointer to the XUartPsv instance. The modem status which are bit masks that are contained in the file xuartpsv.h and named XUARTPSV_UARTRIS_*. The bit masks used for the modem status are the exact bits of the modem status register with no abstraction.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUartPsv_ReadReg, XUARTPSV_UARTRIS_OFFSET.
u32 XUartPsv_IsSending(XUartPsv *InstancePtr)
This function determines if the specified UART is sending data.
InstancePtr is a pointer to the XUartPsv instance. TRUE if the UART is sending dataFALSE if UART is not sending data None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUartPsv_ReadReg, XUARTPSV_UARTFR_BUSY, XUARTPSV_UARTFR_OFFSET, XUARTPSV_UARTFR_TXFE.
u8 XUartPsv_GetOperMode(XUartPsv *InstancePtr)
This function gets the operational mode of the UART.
The UART can operate in one of four modes: Normal, Local Loopback, Remote Loopback, or automatic echo. InstancePtr is a pointer to the XUartPsv instance. The operational mode is specified by constants defined in xuartpsv.h. The constants are named XUARTPSV_OPER_MODE_* None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUARTPSV_OPER_MODE_LOCAL_LOOP, XUARTPSV_OPER_MODE_NORMAL, XUartPsv_ReadReg, XUARTPSV_UARTCR_LBE, XUARTPSV_UARTCR_MODE_MASK, XUARTPSV_UARTCR_MODE_NORMAL, XUARTPSV_UARTCR_MODE_SHIFT, XUARTPSV_UARTCR_OFFSET.
void XUartPsv_SetOperMode(XUartPsv *InstancePtr, u8 OperationMode)
This function sets the operational mode of the UART.
The UART can operate in one of four modes: Normal, Local Loopback, Remote Loopback, or automatic echo. InstancePtr is a pointer to the XUartPsv instance. OperationMode is the mode of the UART. None. None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUARTPSV_OPER_MODE_LOCAL_LOOP, XUARTPSV_OPER_MODE_NORMAL, XUartPsv_ProgramCtrlReg, XUartPsv_ReadReg, XUARTPSV_UARTCR_LBE, XUARTPSV_UARTCR_MODE_MASK, XUARTPSV_UARTCR_MODE_NORMAL, XUARTPSV_UARTCR_OFFSET.
Referenced by UartPsvIntrExample, UartPsvPolledExample, XUartPsv_SelfTest.
s32 XUartPsv_SetDataFormat(XUartPsv *InstancePtr, XUartPsvFormat *FormatPtr)
Sets the data format for the device.
The data format includes the baud rate, number of data bits, number of stop bits, and parity. It is the caller's responsibility to ensure that the UART is not sending or receiving data when this function is called. InstancePtr is a pointer to the XUartPsv instance. FormatPtr is a pointer to a format structure containing the data format to be set. XST_SUCCESS if the data format was successfully set.XST_UART_BAUD_ERROR indicates the baud rate could not be set because of the amount of error with the baud rate and the input clock frequency.XST_INVALID_PARAM if one of the parameters was not valid. The data types in the format type, data bits and parity, are 32 bit fields to prevent a compiler warning. The asserts in this function will cause a warning if these fields are bytes.
References XUartPsv_Config::BaseAddress, XUartPsvFormat::BaudRate, XUartPsv::Config, XUartPsvFormat::DataBits, XUartPsv::IsReady, XUartPsvFormat::Parity, XUartPsvFormat::StopBits, XUARTPSV_FORMAT_2_STOP_BIT, XUARTPSV_FORMAT_8_BITS, XUARTPSV_FORMAT_EN_PARITY, XUARTPSV_FORMAT_EN_STICK_PARITY, XUARTPSV_FORMAT_EN_STICK_PARITY_SHIFT, XUARTPSV_FORMAT_EVEN_PARITY, XUARTPSV_FORMAT_EVEN_PARITY_SHIFT, XUARTPSV_FORMAT_PARITY_MASK, XUartPsv_ReadReg, XUartPsv_SetBaudRate, XUARTPSV_UARTLCR_OFFSET, XUARTPSV_UARTLCR_PARITY_MASK, XUARTPSV_UARTLCR_PARITY_SHIFT, XUARTPSV_UARTLCR_STP_MASK, XUARTPSV_UARTLCR_STP_SHIFT, XUARTPSV_UARTLCR_WLEN_MASK, XUARTPSV_UARTLCR_WLEN_SHIFT, XUartPsv_WriteReg.
void XUartPsv_GetDataFormat(XUartPsv *InstancePtr, XUartPsvFormat *FormatPtr)
Gets the data format for the specified UART.
The data format includes the baud rate, number of data bits, number of stop bits, and parity. InstancePtr is a pointer to the XUartPsv instance. FormatPtr is a pointer to a format structure that will contain the data format after this call completes. None. None.
References XUartPsv_Config::BaseAddress, XUartPsvFormat::BaudRate, XUartPsv::BaudRate, XUartPsv::Config, XUartPsvFormat::DataBits, XUartPsv::IsReady, XUartPsvFormat::Parity, XUartPsvFormat::StopBits, XUartPsv_ReadReg, XUARTPSV_UARTLCR_OFFSET, XUARTPSV_UARTLCR_PARITY_MASK, XUARTPSV_UARTLCR_PARITY_SHIFT, XUARTPSV_UARTLCR_STP_MASK, XUARTPSV_UARTLCR_STP_SHIFT, XUARTPSV_UARTLCR_WLEN_MASK, XUARTPSV_UARTLCR_WLEN_SHIFT.
u32 XUartPsv_GetInterruptMask(XUartPsv *InstancePtr)
This function gets the interrupt mask.
InstancePtr is a pointer to the XUartPsv instance. The current interrupt mask. The mask indicates which interrupts are enabled. None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv_ReadReg, XUARTPSV_UARTIMSC_OFFSET.
Referenced by XUartPsv_Recv.
void XUartPsv_SetInterruptMask(XUartPsv *InstancePtr, u32 Mask)
This function sets the interrupt mask.
InstancePtr is a pointer to the XUartPsv instance Mask contains the interrupts to be enabled or disabled. A '1' enables an interrupt, and a '0' disables. None. None.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUARTPSV_UARTIMSC_MASK, XUARTPSV_UARTIMSC_OFFSET, XUartPsv_WriteReg.
Referenced by UartPsvIntrExample.
void XUartPsv_InterruptHandler(XUartPsv *InstancePtr)
This function is the interrupt handler for the driver.
It must be connected to an interrupt system by the application such that it can be called when an interrupt occurs. InstancePtr contains a pointer to the driver instance None. None.
References XUartPsv_Config::BaseAddress, XUartPsv::CallBackRef, XUartPsv::Config, XUartPsv::Handler, XUartPsv::IsReady, XUARTPSV_EVENT_PARE_FRAME_BRKE, XUartPsv_ReadReg, XUARTPSV_UARTICR_OFFSET, XUARTPSV_UARTIMSC_OFFSET, XUARTPSV_UARTRIS_BERIS, XUARTPSV_UARTRIS_CTSRMIS, XUARTPSV_UARTRIS_DCDRMIS, XUARTPSV_UARTRIS_DSRRMIS, XUARTPSV_UARTRIS_FERIS, XUARTPSV_UARTRIS_OERIS, XUARTPSV_UARTRIS_OFFSET, XUARTPSV_UARTRIS_PERIS, XUARTPSV_UARTRIS_RIRMIS, XUARTPSV_UARTRIS_RTRIS, XUARTPSV_UARTRIS_RXRIS, XUARTPSV_UARTRIS_TXRIS, XUartPsv_WriteReg.
Referenced by UartPsvIntrExample.
void XUartPsv_SetHandler(XUartPsv *InstancePtr, XUartPsv_Handler FuncPtr, void *CallBackRef)
This function sets the handler that will be called when an event (interrupt) occurs that needs application's attention.
InstancePtr is a pointer to the XUartPsv instance FuncPtr is the pointer to the callback function. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. None. There is no assert on the CallBackRef since the driver doesn't know what it is (nor should it)
References XUartPsv::CallBackRef, XUartPsv::Handler, XUartPsv::IsReady.
Referenced by UartPsvIntrExample.
s32 XUartPsv_SelfTest(XUartPsv *InstancePtr)
This function runs a self-test on the driver and hardware device.
This self test performs a local loopback and verifies data can be sent and received.The time for this test is proportional to the baud rate that has been set prior to calling this function.The mode and control registers are restored before return. InstancePtr is a pointer to the XUartPsv instance XST_SUCCESS if the test was successfulXST_UART_TEST_FAIL if the test failed looping back the data This function can hang if the hardware is not functioning properly.
References XUartPsv_Config::BaseAddress, XUartPsv::Config, XUartPsv::IsReady, XUARTPSV_OPER_MODE_LOCAL_LOOP, XUartPsv_ProgramCtrlReg, XUartPsv_ReadReg, XUartPsv_Recv, XUartPsv_Send, XUartPsv_SetOperMode, XUARTPSV_TOTAL_BYTES, XUARTPSV_UARTCR_OFFSET, XUARTPSV_UARTFR_OFFSET, XUARTPSV_UARTFR_RXFE.
Referenced by UartPsvHelloWorldExample, UartPsvIntrExample, UartPsvPolledExample, UartPsvSelfTestExample.