spips
XSPIPS_MASTER_OPTION
Master mode option.
Referenced by SpiPsEepromIntrExample, SpiPsEepromPolledExample, SpiPsFlashIntrExample, SpiPsFlashPolledExample, SpiPsTpmPolledExample.
XSPIPS_CLK_ACTIVE_LOW_OPTION
Active Low Clock option.
XSPIPS_CLK_PHASE_1_OPTION
Clock Phase one option.
XSPIPS_DECODE_SSELECT_OPTION
Select 16 slaves Option.
XSPIPS_FORCE_SSELECT_OPTION
Force Slave Select.
Referenced by SpiPsEepromIntrExample, SpiPsEepromPolledExample, SpiPsFlashIntrExample, SpiPsFlashPolledExample, SpiPsTpmPolledExample.
XSPIPS_MANUAL_START_OPTION
Manual Start mode option.
Referenced by SpiPsFlashIntrExample, SpiPsFlashPolledExample, SpiPsTpmPolledExample.
XSPIPS_CLK_PRESCALE_4
PCLK/4 Prescaler.
XSPIPS_CLK_PRESCALE_8
PCLK/8 Prescaler.
Referenced by SpiPsFlashIntrExample, SpiPsFlashPolledExample.
XSPIPS_CLK_PRESCALE_16
PCLK/16 Prescaler.
Referenced by SpiPsTpmPolledExample.
XSPIPS_CLK_PRESCALE_32
PCLK/32 Prescaler.
XSPIPS_CLK_PRESCALE_64
PCLK/64 Prescaler.
Referenced by SpiPsEepromIntrExample, SpiPsEepromPolledExample.
XSPIPS_CLK_PRESCALE_128
PCLK/128 Prescaler.
XSPIPS_CLK_PRESCALE_256
PCLK/256 Prescaler.
XSPIPS_EVENT_MODE_FAULT
Mode fault error.
XSPIPS_EVENT_TRANSFER_DONE
Transfer done.
XSPIPS_EVENT_TRANSMIT_UNDERRUN
TX FIFO empty.
XSPIPS_EVENT_RECEIVE_OVERRUN
Receive data loss because RX FIFO full.
XSPIPS_CR_OFFSET
Configuration.
Referenced by XSpiPs_GetClkPrescaler, XSpiPs_GetOptions, XSpiPs_InterruptHandler, XSpiPs_PolledTransfer, XSpiPs_Reset, XSpiPs_ResetHw, XSpiPs_SelfTest, XSpiPs_SetClkPrescaler, XSpiPs_SetOptions, XSpiPs_SetSlaveSelect, XSpiPs_Transfer.
XSPIPS_SR_OFFSET
Interrupt Status.
Referenced by XSpiPs_Abort, XSpiPs_InterruptHandler, XSpiPs_PolledTransfer, XSpiPs_ResetHw, XSpiPs_SelfTest, XSpiPs_Transfer.
XSPIPS_IER_OFFSET
Interrupt Enable.
Referenced by XSpiPs_InterruptHandler, XSpiPs_Transfer.
XSPIPS_IDR_OFFSET
Interrupt Disable.
Referenced by XSpiPs_InterruptHandler, XSpiPs_ResetHw.
XSPIPS_IMR_OFFSET
Interrupt Enabled Mask.
XSPIPS_ER_OFFSET
Enable/Disable Register.
Referenced by XSpiPs_ResetHw.
XSPIPS_DR_OFFSET
Delay Register.
Referenced by XSpiPs_GetDelays, XSpiPs_SetDelays.
XSPIPS_TXD_OFFSET
Data Transmit Register.
XSPIPS_RXD_OFFSET
Data Receive Register.
Referenced by XSpiPs_Abort, XSpiPs_ResetHw.
XSPIPS_SICR_OFFSET
Slave Idle Count.
XSPIPS_TXWR_OFFSET
Transmit FIFO Watermark.
Referenced by XSpiPs_ResetHw.
XSPIPS_RXWR_OFFSET
Receive FIFO Watermark.
Referenced by XSpiPs_ResetHw.
XSPIPS_CR_MODF_GEN_EN_MASK
Modefail Generation Enable.
XSPIPS_CR_MANSTRT_MASK
Manual Transmission Start.
Referenced by XSpiPs_InterruptHandler, XSpiPs_PolledTransfer, XSpiPs_Transfer.
XSPIPS_CR_MANSTRTEN_MASK
Manual Transmission Start Enable.
XSPIPS_CR_SSFORCE_MASK
Force Slave Select.
XSPIPS_CR_SSCTRL_MASK
Slave Select Decode.
Referenced by XSpiPs_GetSlaveSelect, XSpiPs_InterruptHandler, XSpiPs_PolledTransfer, XSpiPs_Reset, XSpiPs_ResetHw, XSpiPs_SelfTest, XSpiPs_SetSlaveSelect, XSpiPs_Transfer.
XSPIPS_CR_SSCTRL_SHIFT
Slave Select Decode shift.
Referenced by XSpiPs_GetSlaveSelect, XSpiPs_SetSlaveSelect.
XSPIPS_CR_SSCTRL_MAXIMUM
Slave Select maximum value.
Referenced by XSpiPs_GetSlaveSelect, XSpiPs_SetSlaveSelect.
XSPIPS_CR_SSDECEN_MASK
Slave Select Decode Enable.
XSPIPS_CR_PRESC_MASK
Prescaler Setting.
Referenced by XSpiPs_GetClkPrescaler, XSpiPs_SetClkPrescaler.
XSPIPS_CR_PRESC_SHIFT
Prescaler shift.
Referenced by XSpiPs_GetClkPrescaler, XSpiPs_SetClkPrescaler.
XSPIPS_CR_PRESC_MAXIMUM
Prescaler maximum value.
Referenced by XSpiPs_SetClkPrescaler.
XSPIPS_CR_CPHA_MASK
Phase Configuration.
Referenced by XSpiPs_SetOptions.
XSPIPS_CR_CPOL_MASK
Polarity Configuration.
Referenced by XSpiPs_SetOptions.
XSPIPS_CR_MSTREN_MASK
Master Mode Enable.
XSPIPS_CR_RESET_STATE
Mode Fail Generation Enable.
Referenced by XSpiPs_Reset, XSpiPs_ResetHw, XSpiPs_SelfTest.
XSPIPS_IXR_TXUF_MASK
Tx FIFO Underflow.
Referenced by XSpiPs_InterruptHandler.
XSPIPS_IXR_RXFULL_MASK
Rx FIFO Full.
XSPIPS_IXR_RXNEMPTY_MASK
Rx FIFO Not Empty.
Referenced by XSpiPs_Abort, XSpiPs_ResetHw.
XSPIPS_IXR_TXFULL_MASK
Tx FIFO Full.
XSPIPS_IXR_TXOW_MASK
Tx FIFO Overwater.
Referenced by XSpiPs_InterruptHandler, XSpiPs_PolledTransfer.
XSPIPS_IXR_MODF_MASK
Mode Fault.
Referenced by XSpiPs_Abort, XSpiPs_InterruptHandler, XSpiPs_PolledTransfer.
XSPIPS_IXR_RXOVR_MASK
Rx FIFO Overrun.
Referenced by XSpiPs_InterruptHandler.
XSPIPS_IXR_DFLT_MASK
Default interrupts mask.
Referenced by XSpiPs_InterruptHandler, XSpiPs_Transfer.
XSPIPS_IXR_WR_TO_CLR_MASK
Interrupts which need write to clear.
Referenced by XSpiPs_InterruptHandler, XSpiPs_ResetHw.
XSPIPS_ISR_RESET_STATE
Default to tx/rx reg empty.
Referenced by XSpiPs_SelfTest.
XSPIPS_IXR_DISABLE_ALL_MASK
Disable all interrupts.
Referenced by XSpiPs_ResetHw.
XSPIPS_ER_ENABLE_MASK
SPI Enable Bit Mask.
XSPIPS_DR_NSS_MASK
Delay for slave select de-assertion between word transfers mask.
Referenced by XSpiPs_GetDelays.
XSPIPS_DR_NSS_SHIFT
Delay for slave select de-assertion between word transfers shift.
Referenced by XSpiPs_GetDelays, XSpiPs_SetDelays.
XSPIPS_DR_BTWN_MASK
Delay Between Transfers mask.
Referenced by XSpiPs_GetDelays.
XSPIPS_DR_BTWN_SHIFT
Delay Between Transfers shift.
Referenced by XSpiPs_GetDelays, XSpiPs_SetDelays.
XSPIPS_DR_AFTER_MASK
Delay After Transfers mask.
Referenced by XSpiPs_GetDelays.
XSPIPS_DR_AFTER_SHIFT
Delay After Transfers shift.
Referenced by XSpiPs_GetDelays, XSpiPs_SetDelays.
XSPIPS_DR_INIT_MASK
Delay Initially mask.
Referenced by XSpiPs_GetDelays.
XSPIPS_SICR_MASK
Slave Idle Count Mask.
XSPIPS_TXWR_MASK
Transmit Watermark Mask.
Referenced by XSpiPs_ResetHw.
XSPIPS_TXWR_RESET_VALUE
Transmit Watermark register reset value.
Referenced by XSpiPs_ResetHw.
XSPIPS_RXWR_MASK
Receive Watermark Mask.
Referenced by XSpiPs_ResetHw.
XSPIPS_RXWR_RESET_VALUE
Receive Watermark register reset value.
Referenced by XSpiPs_ResetHw.
XSPIPS_FIFO_DEPTH
FIFO depth of Tx and Rx.
Referenced by XSpiPs_ResetHw.
typedef void(* XSpiPs_StatusHandler)(const void *CallBackRef, u32 StatusEvent, u32 ByteCount))(const void *CallBackRef, u32 StatusEvent, u32 ByteCount)
The handler data type allows the user to define a callback function to handle the asynchronous processing for the SPI device.
The application using this driver is expected to define a handler of this type to support interrupt driven mode. The handler executes in an interrupt context, so only minimal processing should be performed. CallBackRef is the callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. Its type is not important to the driver, so it is a void pointer. StatusEvent holds one or more status events that have occurred. See the XSpiPs_SetStatusHandler() for details on the status events that can be passed in the callback. ByteCount indicates how many bytes of data were successfully transferred. This may be less than the number of bytes requested if the status event indicates an error.
XSpiPs_Config XSpiPs_ConfigTable[XPAR_XSPIPS_NUM_INSTANCES][XPAR_XSPIPS_NUM_INSTANCES]
This table contains configuration information for each SPI device in the system.
OptionsMap OptionsTable[][]
XSpiPs_Config XSpiPs_ConfigTable[][]
This table contains configuration information for each SPI device in the system.
static void StubStatusHandler(const void *CallBackRef, u32 StatusEvent, u32 ByteCount)
This is a stub for the status callback.
The stub is here in case the upper layers forget to set the handler. CallBackRef is a pointer to the upper layer callback reference StatusEvent is the event that just occurred. ByteCount is the number of bytes transferred up until the event occurred. None. None.
s32 XSpiPs_CfgInitialize(XSpiPs *InstancePtr, const XSpiPs_Config *ConfigPtr, u32 EffectiveAddr)
Initializes a specific XSpiPs instance such that the driver is ready to use.
The state of the device after initialization is: Device is disabledSlave modeActive high clock polarityClock phase 0 InstancePtr is a pointer to the XSpiPs instance. Must be zero‑initialized before calling this function. ConfigPtr is a reference to a structure containing information about a specific SPI device. This function initializes an InstancePtr object for a specific device specified by the contents of Config. This function can initialize multiple instance objects with the use of multiple calls giving different Config information on each call. EffectiveAddr is the device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, use ConfigPtr->Config.BaseAddress for this device. XST_SUCCESS if successful.XST_DEVICE_IS_STARTED if the device is already started. It must be stopped to re-initialize. None.
References XSpiPs_Config::BaseAddress, XSpiPs::Config, XSpiPs_Config::FifoDepth, XSpiPs::FifoDepth, XSpiPs::FifoWidth, XSpiPs_Config::InputClockHz, XSpiPs::IsBusy, XSpiPs::IsReady, XSpiPs::RecvBufferPtr, XSpiPs::RemainingBytes, XSpiPs::RequestedBytes, XSpiPs::SendBufferPtr, XSpiPs_Reset.
Referenced by SpiPsEepromIntrExample, SpiPsEepromPolledExample, SpiPsFlashIntrExample, SpiPsFlashPolledExample, SpiPsSelfTestExample, SpiPsSlavePolledExample, SpiPsTpmPolledExample.
void XSpiPs_Reset(XSpiPs *InstancePtr)
Resets the SPI device.
Reset must only be called after the driver has been initialized. The configuration of the device after reset is the same as its configuration after initialization. Any data transfer that is in progress is aborted.The upper layer software is responsible for re-configuring (if necessary) and restarting the SPI device after the reset. InstancePtr is a pointer to the XSpiPs instance. None. None.
References XSpiPs_Config::BaseAddress, XSpiPs::Config, XSpiPs::IsReady, XSpiPs_Abort, XSPIPS_CR_OFFSET, XSPIPS_CR_RESET_STATE, XSPIPS_CR_SSCTRL_MASK, XSpiPs_WriteReg.
Referenced by XSpiPs_CfgInitialize, XSpiPs_SelfTest.
s32 XSpiPs_Transfer(XSpiPs *InstancePtr, u8 *SendBufPtr, u8 *RecvBufPtr, u32 ByteCount)
Transfers specified data on the SPI bus.
If the SPI device is configured as a master, this function initiates bus communication and sends/receives the data to/from the selected SPI slave. If the SPI device is configured as a slave, this function prepares the buffers to be sent/received when selected by a master. For every byte sent, a byte is received. This function should be used to perform interrupt based transfers.The caller has the option of providing two different buffers for send and receive, or one buffer for both send and receive, or no buffer for receive. The receive buffer must be at least as big as the send buffer to prevent unwanted memory writes. This implies that the byte count passed in as an argument must be the smaller of the two buffers if they differ in size. Here are some sample usages: XSpiPs_Transfer(InstancePtr, SendBuf, RecvBuf, ByteCount) The caller wishes to send and receive, and provides two different buffers for send and receive. XSpiPs_Transfer(InstancePtr, SendBuf, NULL, ByteCount) The caller wishes only to send and does not care about the received data. The driver ignores the received data in this case. XSpiPs_Transfer(InstancePtr, SendBuf, SendBuf, ByteCount) The caller wishes to send and receive, but provides the same buffer for doing both. The driver sends the data and overwrites the send buffer with received data as it transfers the data. XSpiPs_Transfer(InstancePtr, RecvBuf, RecvBuf, ByteCount) The caller wishes to only receive and does not care about sending data. In this case, the caller must still provide a send buffer, but it can be the same as the receive buffer if the caller does not care what it sends. The device must send N bytes of data if it wishes to receive N bytes of data. Although this function takes entire buffers as arguments, the driver can only transfer a limited number of bytes at a time, limited by the size of the FIFO. A call to this function only starts the transfer, then subsequent transfers of the data is performed by the interrupt service routine until the entire buffer has been transferred. The status callback function is called when the entire buffer has been sent/received.This function is non-blocking. As a master, the SetSlaveSelect function must be called prior to this function. InstancePtr is a pointer to the XSpiPs instance. SendBufPtr is a pointer to a buffer of data for sending. This buffer must not be NULL. RecvBufPtr is a pointer to a buffer for received data. This argument can be NULL if do not care about receiving. ByteCount contains the number of bytes to send/receive. The number of bytes received always equals the number of bytes sent. XST_SUCCESS if the buffers are successfully handed off to the device for transfer.XST_DEVICE_BUSY indicates that a data transfer is already in progress. This is determined by the driver. This function is not thread-safe. The higher layer software must ensure that no two threads are transferring data on the SPI bus at the same time.
References XSpiPs_Config::BaseAddress, XSpiPs::Config, XSpiPs::FifoDepth, XSpiPs::FifoWidth, XSpiPs::IsBusy, XSpiPs::IsReady, XSpiPs::RecvBufferPtr, XSpiPs::RemainingBytes, XSpiPs::RequestedBytes, XSpiPs::SendBufferPtr, XSpiPs::SlaveSelect, XSPIPS_CR_MANSTRT_MASK, XSPIPS_CR_OFFSET, XSPIPS_CR_SSCTRL_MASK, XSpiPs_Enable, XSPIPS_IER_OFFSET, XSPIPS_IXR_DFLT_MASK, XSpiPs_ReadReg, XSPIPS_SR_OFFSET, XSpiPs_WriteReg.
Referenced by EepromRead, EepromWrite.
s32 XSpiPs_PolledTransfer(XSpiPs *InstancePtr, u8 *SendBufPtr, u8 *RecvBufPtr, u32 ByteCount)
Transfers specified data on the SPI bus in polled mode.
The caller has the option of providing two different buffers for send and receive, or one buffer for both send and receive, or no buffer for receive. The receive buffer must be at least as big as the send buffer to prevent unwanted memory writes. This implies that the byte count passed in as an argument must be the smaller of the two buffers if they differ in size. Here are some sample usages: XSpiPs_PolledTransfer(InstancePtr, SendBuf, RecvBuf, ByteCount) The caller wishes to send and receive, and provides two different buffers for send and receive. XSpiPs_PolledTransfer(InstancePtr, SendBuf, NULL, ByteCount) The caller wishes only to send and does not care about the received data. The driver ignores the received data in this case. XSpiPs_PolledTransfer(InstancePtr, SendBuf, SendBuf, ByteCount) The caller wishes to send and receive, but provides the same buffer for doing both. The driver sends the data and overwrites the send buffer with received data as it transfers the data. XSpiPs_PolledTransfer(InstancePtr, RecvBuf, RecvBuf, ByteCount) The caller wishes to only receive and does not care about sending data. In this case, the caller must still provide a send buffer, but it can be the same as the receive buffer if the caller does not care what it sends. The device must send N bytes of data if it wishes to receive N bytes of data. InstancePtr is a pointer to the XSpiPs instance. SendBufPtr is a pointer to a buffer of data for sending. This buffer must not be NULL. RecvBufPtr is a pointer to a buffer for received data. This argument can be NULL if do not care about receiving. ByteCount contains the number of bytes to send/receive. The number of bytes received always equals the number of bytes sent. XST_SUCCESS if the buffers are successfully handed off to the device for transfer.XST_DEVICE_BUSY indicates that a data transfer is already in progress. This is determined by the driver. This function is not thread-safe. The higher layer software must ensure that no two threads are transferring data on the SPI bus at the same time.
References XSpiPs_Config::BaseAddress, XSpiPs::Config, XSpiPs::FifoDepth, XSpiPs::FifoWidth, XSpiPs::IsBusy, XSpiPs::IsReady, XSpiPs::RecvBufferPtr, XSpiPs::RemainingBytes, XSpiPs::RequestedBytes, XSpiPs::SendBufferPtr, XSpiPs::SlaveSelect, XSPIPS_CR_MANSTRT_MASK, XSPIPS_CR_OFFSET, XSPIPS_CR_SSCTRL_MASK, XSpiPs_Disable, XSpiPs_Enable, XSPIPS_IXR_MODF_MASK, XSPIPS_IXR_TXOW_MASK, XSpiPs_ReadReg, XSPIPS_SR_OFFSET, XSpiPs_WriteReg.
Referenced by SpiPsSlavePolledExample, SpiPsTpmTransfer.
s32 XSpiPs_SetSlaveSelect(XSpiPs *InstancePtr, u8 SlaveSel)
Selects or deselect the slave with which the master communicates.
This setting affects the SPI_ss_outN signals. The behavior depends on the setting of the CR_SSDECEN bit. If CR_SSDECEN is 0, the SPI_ss_outN bits will be output with a single signal low. If CR_SSDECEN is 1, the SPI_ss_outN bits will reflect the value set.The user is not allowed to deselect the slave while a transfer is in progress. If no transfer is in progress, the user can select a new slave, which implicitly deselects the current slave. In order to explicitly deselect the current slave, a value of all 1's, 0x0F can be passed in as the argument to the function. InstancePtr is a pointer to the XSpiPs instance. SlaveSel is the slave number to be selected. Normally, 3 slaves can be selected with values 0-2. In case, 3-8 decode option is set, then up to 8 slaves can be selected. Only one slave can be selected at a time. XST_SUCCESS if the slave is selected or deselected successfully.XST_DEVICE_BUSY if a transfer is in progress, slave cannot be changed. This function only sets the slave which will be selected when a transfer occurs. The slave is not selected when the SPI is idle. The slave select has no affect when the device is configured as a slave.
References XSpiPs_Config::BaseAddress, XSpiPs::Config, XSpiPs::IsBusy, XSpiPs::IsReady, XSpiPs::SlaveSelect, XSPIPS_CR_OFFSET, XSPIPS_CR_SSCTRL_MASK, XSPIPS_CR_SSCTRL_MAXIMUM, XSPIPS_CR_SSCTRL_SHIFT, XSpiPs_ReadReg, XSpiPs_WriteReg.
Referenced by SpiPsEepromIntrExample, SpiPsEepromPolledExample, SpiPsFlashIntrExample, SpiPsFlashPolledExample, SpiPsTpmPolledExample.
u8 XSpiPs_GetSlaveSelect(const XSpiPs *InstancePtr)
Gets the current slave select setting for the SPI device.
InstancePtr is a pointer to the XSpiPs instance. The slave number selected (starting from 0). None.
References XSpiPs::IsReady, XSpiPs::SlaveSelect, XSPIPS_CR_SSCTRL_MASK, XSPIPS_CR_SSCTRL_MAXIMUM, XSPIPS_CR_SSCTRL_SHIFT.
void XSpiPs_SetStatusHandler(XSpiPs *InstancePtr, void *CallBackRef, XSpiPs_StatusHandler FunctionPtr)
Sets the status callback function, the status handler, which the driver calls when it encounters conditions that should be reported to upper layer software.
The handler executes in an interrupt context, so it must minimize the amount of processing performed. One of the following status events is passed to the status handler. XST_SPI_MODE_FAULT A mode fault error occurred, meaning the device is selected as slave while being a master.XST_SPI_TRANSFER_DONE The requested data transfer is doneXST_SPI_TRANSMIT_UNDERRUN As a slave device, the master clocked data but there were none available in the transmit register/FIFO. This typically means the slave application did not issue a transfer request fast enough, or the processor/driver could not fill the transmit register/FIFO fast enough.XST_SPI_RECEIVE_OVERRUN The SPI device lost data. Data was received but the receive data register/FIFO was full.XST_SPI_SLAVE_MODE_FAULT A slave SPI device was selected as a slave while it was disabled. This indicates the master is already transferring data (which is being dropped until the slave application issues a transfer). InstancePtr is a pointer to the XSpiPs instance. CallBackRef is the upper layer callback reference passed back when the callback function is invoked. FunctionPtr is the pointer to the callback function. None. The handler is called within interrupt context, so it should do its work quickly and queue potentially time-consuming work to a task-level thread.
References XSpiPs::IsReady, XSpiPs::StatusRef.
Referenced by SpiPsEepromIntrExample, SpiPsFlashIntrExample.
void XSpiPs_InterruptHandler(XSpiPs *InstancePtr)
The interrupt handler for SPI interrupts.
This function must be connected by the user to an interrupt controller.The interrupts that are handled are: Mode Fault Error. This interrupt is generated if this device is selected as a slave when it is configured as a master. The driver aborts any data transfer that is in progress by resetting FIFOs (if present) and resetting its buffer pointers. The upper layer software is informed of the error.Data Transmit Register (FIFO) Empty. This interrupt is generated when the transmit register or FIFO is empty. The driver uses this interrupt during a transmission to continually send/receive data until the transfer is done.Data Transmit Register (FIFO) Underflow. This interrupt is generated when the SPI device, when configured as a slave, attempts to read an empty DTR/FIFO. An empty DTR/FIFO usually means that software is not giving the device data in a timely manner. No action is taken by the driver other than to inform the upper layer software of the error.Data Receive Register (FIFO) Overflow. This interrupt is generated when the SPI device attempts to write a received byte to an already full DRR/FIFO. A full DRR/FIFO usually means software is not emptying the data in a timely manner. No action is taken by the driver other than to inform the upper layer software of the error.Slave Mode Fault Error. This interrupt is generated if a slave device is selected as a slave while it is disabled. No action is taken by the driver other than to inform the upper layer software of the error. InstancePtr is a pointer to the XSpiPs instance. None. The slave select register is being set to deselect the slave when a transfer is complete. This is being done regardless of whether it is a slave or a master since the hardware does not drive the slave select as a slave.
References XSpiPs_Config::BaseAddress, XSpiPs::Config, XSpiPs::FifoDepth, XSpiPs::FifoWidth, XSpiPs::IsBusy, XSpiPs::IsReady, XSpiPs::RecvBufferPtr, XSpiPs::RemainingBytes, XSpiPs::RequestedBytes, XSpiPs::SendBufferPtr, XSpiPs::StatusRef, XSpiPs_Abort, XSPIPS_CR_MANSTRT_MASK, XSPIPS_CR_OFFSET, XSPIPS_CR_SSCTRL_MASK, XSpiPs_Disable, XSPIPS_IDR_OFFSET, XSPIPS_IER_OFFSET, XSPIPS_IXR_DFLT_MASK, XSPIPS_IXR_MODF_MASK, XSPIPS_IXR_RXOVR_MASK, XSPIPS_IXR_TXOW_MASK, XSPIPS_IXR_TXUF_MASK, XSPIPS_IXR_WR_TO_CLR_MASK, XSpiPs_ReadReg, XSPIPS_SR_OFFSET, XSpiPs_WriteReg.
Referenced by SpiPsEepromIntrExample, SpiPsFlashIntrExample.
void XSpiPs_Abort(XSpiPs *InstancePtr)
Aborts a transfer in progress by disabling the device and resetting the FIFOs if present.
The byte counts are cleared, the busy flag is cleared, and mode fault is cleared. InstancePtr is a pointer to the XSpiPs instance. None. This function does a read/modify/write of the Config register. The user of this function needs to take care of critical sections.
References XSpiPs_Config::BaseAddress, XSpiPs::Config, XSpiPs::FifoDepth, XSpiPs::IsBusy, XSpiPs::RemainingBytes, XSpiPs::RequestedBytes, XSpiPs_Disable, XSPIPS_IXR_MODF_MASK, XSPIPS_IXR_RXNEMPTY_MASK, XSpiPs_ReadReg, XSPIPS_RXD_OFFSET, XSPIPS_SR_OFFSET, XSpiPs_WriteReg.
Referenced by XSpiPs_InterruptHandler, XSpiPs_Reset.
XSpiPs_Config * XSpiPs_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XSpiPs_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xspips.h for the definition of XSpiPs_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XSpiPs_Config::Name.
Referenced by SpiPsEepromIntrExample, SpiPsEepromPolledExample, SpiPsFlashIntrExample, SpiPsFlashPolledExample, SpiPsSelfTestExample, SpiPsSlavePolledExample, SpiPsTpmPolledExample.
s32 XSpiPs_SelfTest(XSpiPs *InstancePtr)
Runs a self-test on the driver/device.
The self-test is destructive in that a reset of the device is performed in order to check the reset values of the registers and to get the device into a known state.Upon successful return from the self-test, the device is reset. InstancePtr is a pointer to the XSpiPs instance. XST_SUCCESS if successful XST_REGISTER_ERROR indicates a register did not read or write correctly. None.
References XSpiPs_Config::BaseAddress, XSpiPs::Config, XSpiPs::IsReady, XSPIPS_CR_OFFSET, XSPIPS_CR_RESET_STATE, XSPIPS_CR_SSCTRL_MASK, XSpiPs_GetDelays, XSPIPS_ISR_RESET_STATE, XSpiPs_ReadReg, XSpiPs_Reset, XSpiPs_SetDelays, XSPIPS_SR_OFFSET.
Referenced by SpiPsEepromIntrExample, SpiPsEepromPolledExample, SpiPsFlashIntrExample, SpiPsFlashPolledExample, SpiPsSelfTestExample, SpiPsTpmPolledExample.
s32 XSpiPs_SetOptions(const XSpiPs *InstancePtr, u32 Options)
This function sets the options for the SPI device driver.
The options control how the device behaves relative to the SPI bus. The device must be idle rather than busy transferring data before setting these device options. InstancePtr is a pointer to the XSpiPs instance. Options contains the specified options to be set. This is a bit mask where a 1 means to turn the option on, and a 0 means to turn the option off. One or more bit values may be contained in the mask. See the bit definitions named XSPIPS_*_OPTIONS in the file xspips.h. XST_SUCCESS if options are successfully set.XST_DEVICE_BUSY if the device is currently transferring data. The transfer must complete or be aborted before setting options. This function is not thread-safe.
References XSpiPs_Config::BaseAddress, XSpiPs::Config, XSpiPs::IsBusy, XSpiPs::IsReady, XSPIPS_CR_CPHA_MASK, XSPIPS_CR_CPOL_MASK, XSPIPS_CR_OFFSET, XSpiPs_Disable, XSpiPs_Enable, XSpiPs_ReadReg, XSpiPs_WriteReg.
Referenced by SpiPsEepromIntrExample, SpiPsEepromPolledExample, SpiPsFlashIntrExample, SpiPsFlashPolledExample, SpiPsTpmPolledExample.
u32 XSpiPs_GetOptions(const XSpiPs *InstancePtr)
This function gets the options for the SPI device.
The options control how the device behaves relative to the SPI bus. InstancePtr is a pointer to the XSpiPs instance. Options contains the specified options currently set. This is a bit value where a 1 means the option is on, and a 0 means the option is off. See the bit definitions named XSPIPS_*_OPTIONS in file xspips.h.None.
References XSpiPs_Config::BaseAddress, XSpiPs::Config, XSpiPs::IsReady, XSPIPS_CR_OFFSET, XSpiPs_ReadReg.
s32 XSpiPs_SetClkPrescaler(const XSpiPs *InstancePtr, u8 Prescaler)
This function sets the clock prescaler for an SPI device.
The device must be idle rather than busy transferring data before setting these device options. InstancePtr is a pointer to the XSpiPs instance. Prescaler is the value that determine how much the clock should be divided by. Use the XSPIPS_CLK_PRESCALE_* constants defined in xspips.h for this setting. XST_SUCCESS if options are successfully set.XST_DEVICE_BUSY if the device is currently transferring data. The transfer must complete or be aborted before setting options. This function is not thread-safe.
References XSpiPs_Config::BaseAddress, XSpiPs::Config, XSpiPs::IsBusy, XSpiPs::IsReady, XSPIPS_CR_OFFSET, XSPIPS_CR_PRESC_MASK, XSPIPS_CR_PRESC_MAXIMUM, XSPIPS_CR_PRESC_SHIFT, XSpiPs_ReadReg, XSpiPs_WriteReg.
Referenced by SpiPsEepromIntrExample, SpiPsEepromPolledExample, SpiPsFlashIntrExample, SpiPsFlashPolledExample, SpiPsTpmPolledExample.
u8 XSpiPs_GetClkPrescaler(const XSpiPs *InstancePtr)
This function gets the clock prescaler of an SPI device.
InstancePtr is a pointer to the XSpiPs instance. The prescaler value. None.
References XSpiPs_Config::BaseAddress, XSpiPs::Config, XSpiPs::IsReady, XSPIPS_CR_OFFSET, XSPIPS_CR_PRESC_MASK, XSPIPS_CR_PRESC_SHIFT, XSpiPs_ReadReg.
s32 XSpiPs_SetDelays(const XSpiPs *InstancePtr, u8 DelayNss, u8 DelayBtwn, u8 DelayAfter, u8 DelayInit)
This function sets the delay register for the SPI device driver.
The delay register controls the Delay Between Transfers, Delay After Transfers, and the Delay Initially. The default value is 0x0. The range of each delay value is 0-255. InstancePtr is a pointer to the XSpiPs instance. DelayNss is the delay for which the chip select outputs will be de-asserted between words when CPHA=0. DelayBtwn is the delay between one Slave Select being de-activated and the activation of another slave. The delay is the number of master clock periods given by DelayBtwn + 2. DelayAfter define the delay between the last bit of the current byte transfer and the first bit of the next byte transfer. The delay in number of master clock periods is given as: CPHA=0:DelayInit+DelayAfter+3 CPHA=1:DelayAfter+1 DelayInit is the delay between asserting the slave select signal and the first bit transfer. The delay int number of master clock periods is DelayInit+1. XST_SUCCESS if delays are successfully set.XST_DEVICE_BUSY if the device is currently transferring data. The transfer must complete or be aborted before setting options. None.
References XSpiPs_Config::BaseAddress, XSpiPs::Config, XSpiPs::IsBusy, XSpiPs::IsReady, XSPIPS_DR_AFTER_SHIFT, XSPIPS_DR_BTWN_SHIFT, XSPIPS_DR_NSS_SHIFT, XSPIPS_DR_OFFSET, XSpiPs_WriteReg.
Referenced by XSpiPs_SelfTest.
void XSpiPs_GetDelays(const XSpiPs *InstancePtr, u8 *DelayNss, u8 *DelayBtwn, u8 *DelayAfter, u8 *DelayInit)
This function gets the delay settings for an SPI device.
The delay register controls the Delay Between Transfers, Delay After Transfers, and the Delay Initially. The default value is 0x0. InstancePtr is a pointer to the XSpiPs instance. DelayNss is a pointer to the delay for which the chip select outputs will be de-asserted between words when CPHA=0. DelayBtwn is a pointer to the Delay Between transfers value. This is a return parameter. DelayAfter is a pointer to the Delay After transfer value. This is a return parameter. DelayInit is a pointer to the Delay Initially value. This is a return parameter. None. None.
References XSpiPs_Config::BaseAddress, XSpiPs::Config, XSpiPs::IsReady, XSPIPS_DR_AFTER_MASK, XSPIPS_DR_AFTER_SHIFT, XSPIPS_DR_BTWN_MASK, XSPIPS_DR_BTWN_SHIFT, XSPIPS_DR_INIT_MASK, XSPIPS_DR_NSS_MASK, XSPIPS_DR_NSS_SHIFT, XSPIPS_DR_OFFSET, XSpiPs_ReadReg.
Referenced by XSpiPs_SelfTest.
void XSpiPs_ResetHw(u32 BaseAddress)
Resets the spi module.
BaseAddress is the base address of the device. None None.
References XSPIPS_CR_OFFSET, XSPIPS_CR_RESET_STATE, XSPIPS_CR_SSCTRL_MASK, XSPIPS_ER_OFFSET, XSPIPS_FIFO_DEPTH, XSPIPS_IDR_OFFSET, XSPIPS_IXR_DISABLE_ALL_MASK, XSPIPS_IXR_RXNEMPTY_MASK, XSPIPS_IXR_WR_TO_CLR_MASK, XSpiPs_ReadReg, XSPIPS_RXD_OFFSET, XSPIPS_RXWR_MASK, XSPIPS_RXWR_OFFSET, XSPIPS_RXWR_RESET_VALUE, XSPIPS_SR_OFFSET, XSPIPS_TXWR_MASK, XSPIPS_TXWR_OFFSET, XSPIPS_TXWR_RESET_VALUE, XSpiPs_WriteReg.
XSpiPs_SendByte
XSpiPs_RecvByte
XSPIPS_H
XSpiPs_IsManualStart
XSpiPs_IsManualChipSelect
XSpiPs_IsDecodeSSelect
XSpiPs_IsMaster
XSpiPs_SetSlaveIdle
Set the contents of the slave idle count register.
InstancePtr is a pointer to the XSpiPs instance. RegisterValue is the value to be written, valid values are 0-255. None C-Style signature: void XSpiPs_SetSlaveIdle(XSpiPs *InstancePtr, u32 RegisterValue)
XSpiPs_GetSlaveIdle
Get the contents of the slave idle count register.
Use the XSPIPS_SICR_* constants defined in xspips_hw.h to interpret the bit-mask returned. InstancePtr is a pointer to the XSpiPs instance. 8-bit value representing the contents of the SIC register. C-Style signature: u32 XSpiPs_GetSlaveIdle(XSpiPs *InstancePtr)
XSpiPs_SetTXWatermark
Set the contents of the transmit FIFO watermark register.
InstancePtr is a pointer to the XSpiPs instance. RegisterValue is the value to be written, valid values are 1-128. None. C-Style signature: void XSpiPs_SetTXWatermark(XSpiPs *InstancePtr, u32 RegisterValue)
XSpiPs_GetTXWatermark
Get the contents of the transmit FIFO watermark register.
Use the XSPIPS_TXWR_* constants defined xspips_hw.h to interpret the bit-mask returned. InstancePtr is a pointer to the XSpiPs instance. 8-bit value representing the contents of the TXWR register. C-Style signature: u32 XSpiPs_GetTXWatermark(u32 *InstancePtr)
XSpiPs_SetRXWatermark
Set the contents of the receive FIFO watermark register.
InstancePtr is a pointer to the XSpiPs instance. RegisterValue is the value to be written, valid values are 1-128. None. C-Style signature: void XSpiPs_SetRXWatermark(XSpiPs *InstancePtr, u32 RegisterValue)
XSpiPs_GetRXWatermark
Get the contents of the receive FIFO watermark register.
Use the XSPIPS_RXWR_* constants defined xspips_hw.h to interpret the bit-mask returned. InstancePtr is a pointer to the XSpiPs instance. A 8-bit value representing the contents of the RXWR register. C-Style signature: u32 XSpiPs_GetRXWatermark(u32 *InstancePtr)
XSpiPs_Enable
Enable the device and uninhibit master transactions.
InstancePtr is a pointer to the XSpiPs instance. None. C-Style signature: void XSpiPs_Enable(u32 *InstancePtr)
Referenced by XSpiPs_PolledTransfer, XSpiPs_SetOptions, XSpiPs_Transfer.
XSpiPs_Disable
Disable the device.
InstancePtr is a pointer to the XSpiPs instance. None. C-Style signature: void XSpiPs_Disable(u32 *InstancePtr)
Referenced by XSpiPs_Abort, XSpiPs_InterruptHandler, XSpiPs_PolledTransfer, XSpiPs_SetOptions.
XSPIPS_HW_H
XSpiPs_In32
XSpiPs_Out32
XSpiPs_ReadReg
Read a register.
BaseAddress contains the base address of the device. RegOffset contains the offset from the 1st register of the device to the target register. The value read from the register. C-Style signature: u32 XSpiPs_ReadReg(u32 BaseAddress. int RegOffset)
Referenced by XSpiPs_Abort, XSpiPs_GetClkPrescaler, XSpiPs_GetDelays, XSpiPs_GetOptions, XSpiPs_InterruptHandler, XSpiPs_PolledTransfer, XSpiPs_ResetHw, XSpiPs_SelfTest, XSpiPs_SetClkPrescaler, XSpiPs_SetOptions, XSpiPs_SetSlaveSelect, XSpiPs_Transfer.
XSpiPs_WriteReg
Write to a register.
BaseAddress contains the base address of the device. RegOffset contains the offset from the 1st register of the device to target register. RegisterValue is the value to be written to the register. None. C-Style signature: void XSpiPs_WriteReg(u32 BaseAddress, int RegOffset, u32 RegisterValue)
Referenced by XSpiPs_Abort, XSpiPs_InterruptHandler, XSpiPs_PolledTransfer, XSpiPs_Reset, XSpiPs_ResetHw, XSpiPs_SetClkPrescaler, XSpiPs_SetDelays, XSpiPs_SetOptions, XSpiPs_SetSlaveSelect, XSpiPs_Transfer.
XSPIPS_NUM_OPTIONS