xspips_sinit.c
XSpiPs_Config XSpiPs_ConfigTable[][]
This table contains configuration information for each SPI device in the system.
XSpiPs_Config * XSpiPs_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XSpiPs_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xspips.h for the definition of XSpiPs_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XSpiPs_Config::Name.
Referenced by SpiPsEepromIntrExample, SpiPsEepromPolledExample, SpiPsFlashIntrExample, SpiPsFlashPolledExample, SpiPsSelfTestExample, SpiPsSlavePolledExample, SpiPsTpmPolledExample.