xspips_tpm_polled_example.c
TPM_SPI_SELECT
XSPIPS_TPM_ACCESS
XSPIPS_TPM_STS
XSPIPS_TPM_DATA_FIFO
XSPIPS_TPM_DID_VID
XSPIPS_TPM_RID
XSPIPS_TPM_ACCESS_VALID
XSPIPS_TPM_ACCESS_ACT_LOCAL
XSPIPS_TPM_ACCESS_REQ_PEND
XSPIPS_TPM_ACCESS_REQ_USE
XSPIPS_TPM_STS_VALID
XSPIPS_TPM_STS_CMD_READY
XSPIPS_TPM_STS_GO
XSPIPS_TPM_STS_DATA_AVAIL
XSPIPS_TPM_STS_DATA_EXPECT
XSPIPS_TPM_TX_HEAD_SIZE
XSPIPS_TPM_RX_HEAD_SIZE
XSPIPS_TPM_SPI_MAX_SIZE
XSPIPS_TPM2_CMD_SELFTEST
XSPIPS_TPM2_CMD_STARTUP
XSPIPS_TPM2_CMD_PCR_READ
XSPIPS_TPM2_CMD_PCR_RESET
XSPIPS_TPM2_CMD_PCR_EXTEND
XSPIPS_EXIT_CMD_LOOP
XSPIPS_TPM_PCR_EXT_CMD_SIZE
XSPIPS_TPM_SHA1_DIGEST_SIZE
XSPIPS_TPM_SHA256_DIGEST_SIZE
XSPIPS_TPM_RESP_MAX_SIZE
XSPIPS_TPM_REQ_MAX_SIZE
XSpiPs SpiInstance
u8 TpmTxBuffer[XSPIPS_TPM_REQ_MAX_SIZE+XSPIPS_TPM_TX_HEAD_SIZE][XSPIPS_TPM_REQ_MAX_SIZE+XSPIPS_TPM_TX_HEAD_SIZE]
u8 TpmRxBuffer[XSPIPS_TPM_RESP_MAX_SIZE+XSPIPS_TPM_TX_HEAD_SIZE][XSPIPS_TPM_RESP_MAX_SIZE+XSPIPS_TPM_TX_HEAD_SIZE]
u8 TpmRespBuffer[XSPIPS_TPM_RESP_MAX_SIZE][XSPIPS_TPM_RESP_MAX_SIZE]
u8 tpm2_getcap[][]
u8 tpm2_selftest[][]
u8 tpm2_startup[][]
u8 tpm2_pcrread[][]
u8 tpm2_pcrreset[][]
u8 tpm2_pcrextend[XSPIPS_TPM_PCR_EXT_CMD_SIZE+XSPIPS_TPM_SHA256_DIGEST_SIZE][XSPIPS_TPM_PCR_EXT_CMD_SIZE+XSPIPS_TPM_SHA256_DIGEST_SIZE]
u8 sha1[XSPIPS_TPM_SHA1_DIGEST_SIZE][XSPIPS_TPM_SHA1_DIGEST_SIZE]
u8 sha256[XSPIPS_TPM_SHA256_DIGEST_SIZE][XSPIPS_TPM_SHA256_DIGEST_SIZE]
int SpiPsReadID(XSpiPs *SpiPtr)
This function reads vendor identification information.
SpiPtr is a pointer to the SPIPS driver component to use. XST_SUCCESS if successful, else XST_FAILURE. None.
References SpiPsTpmTransfer.
Referenced by SpiPsTpmPolledExample.
int SpiPsTpmStatusGet(XSpiPs *SpiPtr, u8 *StatusPtr)
This function gets TPM status.
SpiPtr is a pointer to the SPIPS driver component to use. StatusPtr is pointer to read status XST_SUCCESS if successful, else XST_FAILURE. None.
References SpiPsTpmTransfer.
Referenced by SpiPsTpmDataTransfer.
int SpiPsTpmStatusSet(XSpiPs *SpiPtr, u8 StatusVal)
This function sets the TPM status.
SpiPtr is a pointer to the SPIPS driver component to use. StatusVal is to be written to status register XST_SUCCESS if successful, else XST_FAILURE. None.
References SpiPsTpmTransfer.
Referenced by SpiPsTpmDataTransfer.
int SpiPsTpmAccessGet(XSpiPs *SpiPtr, u8 *AccessPtr)
This function gets TPM access configuration.
SpiPtr is a pointer to the SPIPS driver component to use. AccessPtr is pointer to get access configuration XST_SUCCESS if successful, else XST_FAILURE. None.
References SpiPsTpmTransfer.
Referenced by SpiPsTpmPolledExample.
int SpiPsTpmAccessSet(XSpiPs *SpiPtr, u8 Access)
This function sets TPM access configuration.
SpiPtr is a pointer to the SPIPS driver component to use. Access is set access configuration value XST_SUCCESS if successful, else XST_FAILURE. None.
References SpiPsTpmTransfer.
Referenced by SpiPsTpmPolledExample.
int SpiPsTpmFifoRead(XSpiPs *SpiPtr, u8 *DataPtr, u8 ByteCount)
This function reads data from TPM FIFO.
SpiPtr is a pointer to the SPIPS driver component to use. Data is to be read to data FIFO ByteCount is the number of bytes to read. XST_SUCCESS if successful, else XST_FAILURE. None.
References SpiPsTpmTransfer.
Referenced by SpiPsTpmDataTransfer.
int SpiPsTpmFifoWrite(XSpiPs *SpiPtr, u8 *DataPtr, u8 ByteCount)
This function write the data TPM FIFO.
SpiPtr is a pointer to the SPIPS driver component to use. DataPtr is data pointer to be written to FIFO. ByteCount is the number of bytes to read. XST_SUCCESS if successful, else XST_FAILURE. None.
References SpiPsTpmTransfer.
Referenced by SpiPsTpmDataTransfer.
int SpiPsTpmTransfer(XSpiPs *SpiPtr, u32 Address, u8 *TxBuf, u8 *RxBuf, u16 Length)
This function sets TPM access configuration.
SpiPtr is a pointer to the SPIPS driver component to use. Address register address TxBuf is pointer to transmit buffer RxBuf is pointer to receive buffer Length is transfer length XST_SUCCESS if successful, else XST_FAILURE. None.
References XSpiPs_PolledTransfer.
Referenced by SpiPsReadID, SpiPsTpmAccessGet, SpiPsTpmAccessSet, SpiPsTpmFifoRead, SpiPsTpmFifoWrite, SpiPsTpmStatusGet, SpiPsTpmStatusSet.
int SpiPsTpmDataTransfer(XSpiPs *SpiPtr, u8 *TxBuf, u8 *RxBuf, u16 Txlen)
This function sets TPM access configuration.
SpiPtr is a pointer to the SPIPS driver component to use. TxBuf is pointer to transmit buffer RxBuf is pointer to receive buffer Txlen is data transfer length XST_SUCCESS if successful, else XST_FAILURE. None.
References SpiPsTpmFifoRead, SpiPsTpmFifoWrite, SpiPsTpmStatusGet, SpiPsTpmStatusSet.
Referenced by SpiPsTpmPolledExample.
int SpiPsTpmPolledExample(XSpiPs *SpiInstancePtr, UINTPTR BaseAddress)
SpiInstancePtr is a pointer to the Spi Instance. BaseAddress contains the base address of the device XST_SUCCESS if successful else XST_FAILURE. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XSpiPs_Config::BaseAddress, SpiPsReadID, SpiPsTpmAccessGet, SpiPsTpmAccessSet, SpiPsTpmDataTransfer, XSpiPs_CfgInitialize, XSPIPS_CLK_PRESCALE_16, XSPIPS_FORCE_SSELECT_OPTION, XSpiPs_LookupConfig, XSPIPS_MANUAL_START_OPTION, XSPIPS_MASTER_OPTION, XSpiPs_SelfTest, XSpiPs_SetClkPrescaler, XSpiPs_SetOptions, XSpiPs_SetSlaveSelect.
Referenced by main.
int main(void)
Main function to call the Spi TPM example.
None XST_SUCCESS if successful, otherwise XST_FAILURE. None
References SpiPsTpmPolledExample.