xspips_selftest.c
s32 XSpiPs_SelfTest(XSpiPs *InstancePtr)
Runs a self-test on the driver/device.
The self-test is destructive in that a reset of the device is performed in order to check the reset values of the registers and to get the device into a known state.Upon successful return from the self-test, the device is reset. InstancePtr is a pointer to the XSpiPs instance. XST_SUCCESS if successful XST_REGISTER_ERROR indicates a register did not read or write correctly. None.
References XSpiPs_Config::BaseAddress, XSpiPs::Config, XSpiPs::IsReady, XSPIPS_CR_OFFSET, XSPIPS_CR_RESET_STATE, XSPIPS_CR_SSCTRL_MASK, XSpiPs_GetDelays, XSPIPS_ISR_RESET_STATE, XSpiPs_ReadReg, XSpiPs_Reset, XSpiPs_SetDelays, XSPIPS_SR_OFFSET.
Referenced by SpiPsEepromIntrExample, SpiPsEepromPolledExample, SpiPsFlashIntrExample, SpiPsFlashPolledExample, SpiPsSelfTestExample, SpiPsTpmPolledExample.