xspips_options.c
XSPIPS_NUM_OPTIONS
OptionsMap OptionsTable[][]
s32 XSpiPs_SetOptions(const XSpiPs *InstancePtr, u32 Options)
This function sets the options for the SPI device driver.
The options control how the device behaves relative to the SPI bus. The device must be idle rather than busy transferring data before setting these device options. InstancePtr is a pointer to the XSpiPs instance. Options contains the specified options to be set. This is a bit mask where a 1 means to turn the option on, and a 0 means to turn the option off. One or more bit values may be contained in the mask. See the bit definitions named XSPIPS_*_OPTIONS in the file xspips.h. XST_SUCCESS if options are successfully set.XST_DEVICE_BUSY if the device is currently transferring data. The transfer must complete or be aborted before setting options. This function is not thread-safe.
References XSpiPs_Config::BaseAddress, XSpiPs::Config, XSpiPs::IsBusy, XSpiPs::IsReady, XSPIPS_CR_CPHA_MASK, XSPIPS_CR_CPOL_MASK, XSPIPS_CR_OFFSET, XSpiPs_Disable, XSpiPs_Enable, XSpiPs_ReadReg, XSpiPs_WriteReg.
Referenced by SpiPsEepromIntrExample, SpiPsEepromPolledExample, SpiPsFlashIntrExample, SpiPsFlashPolledExample, SpiPsTpmPolledExample.
u32 XSpiPs_GetOptions(const XSpiPs *InstancePtr)
This function gets the options for the SPI device.
The options control how the device behaves relative to the SPI bus. InstancePtr is a pointer to the XSpiPs instance. Options contains the specified options currently set. This is a bit value where a 1 means the option is on, and a 0 means the option is off. See the bit definitions named XSPIPS_*_OPTIONS in file xspips.h.None.
References XSpiPs_Config::BaseAddress, XSpiPs::Config, XSpiPs::IsReady, XSPIPS_CR_OFFSET, XSpiPs_ReadReg.
s32 XSpiPs_SetClkPrescaler(const XSpiPs *InstancePtr, u8 Prescaler)
This function sets the clock prescaler for an SPI device.
The device must be idle rather than busy transferring data before setting these device options. InstancePtr is a pointer to the XSpiPs instance. Prescaler is the value that determine how much the clock should be divided by. Use the XSPIPS_CLK_PRESCALE_* constants defined in xspips.h for this setting. XST_SUCCESS if options are successfully set.XST_DEVICE_BUSY if the device is currently transferring data. The transfer must complete or be aborted before setting options. This function is not thread-safe.
References XSpiPs_Config::BaseAddress, XSpiPs::Config, XSpiPs::IsBusy, XSpiPs::IsReady, XSPIPS_CR_OFFSET, XSPIPS_CR_PRESC_MASK, XSPIPS_CR_PRESC_MAXIMUM, XSPIPS_CR_PRESC_SHIFT, XSpiPs_ReadReg, XSpiPs_WriteReg.
Referenced by SpiPsEepromIntrExample, SpiPsEepromPolledExample, SpiPsFlashIntrExample, SpiPsFlashPolledExample, SpiPsTpmPolledExample.
u8 XSpiPs_GetClkPrescaler(const XSpiPs *InstancePtr)
This function gets the clock prescaler of an SPI device.
InstancePtr is a pointer to the XSpiPs instance. The prescaler value. None.
References XSpiPs_Config::BaseAddress, XSpiPs::Config, XSpiPs::IsReady, XSPIPS_CR_OFFSET, XSPIPS_CR_PRESC_MASK, XSPIPS_CR_PRESC_SHIFT, XSpiPs_ReadReg.
s32 XSpiPs_SetDelays(const XSpiPs *InstancePtr, u8 DelayNss, u8 DelayBtwn, u8 DelayAfter, u8 DelayInit)
This function sets the delay register for the SPI device driver.
The delay register controls the Delay Between Transfers, Delay After Transfers, and the Delay Initially. The default value is 0x0. The range of each delay value is 0-255. InstancePtr is a pointer to the XSpiPs instance. DelayNss is the delay for which the chip select outputs will be de-asserted between words when CPHA=0. DelayBtwn is the delay between one Slave Select being de-activated and the activation of another slave. The delay is the number of master clock periods given by DelayBtwn + 2. DelayAfter define the delay between the last bit of the current byte transfer and the first bit of the next byte transfer. The delay in number of master clock periods is given as: CPHA=0:DelayInit+DelayAfter+3 CPHA=1:DelayAfter+1 DelayInit is the delay between asserting the slave select signal and the first bit transfer. The delay int number of master clock periods is DelayInit+1. XST_SUCCESS if delays are successfully set.XST_DEVICE_BUSY if the device is currently transferring data. The transfer must complete or be aborted before setting options. None.
References XSpiPs_Config::BaseAddress, XSpiPs::Config, XSpiPs::IsBusy, XSpiPs::IsReady, XSPIPS_DR_AFTER_SHIFT, XSPIPS_DR_BTWN_SHIFT, XSPIPS_DR_NSS_SHIFT, XSPIPS_DR_OFFSET, XSpiPs_WriteReg.
Referenced by XSpiPs_SelfTest.
void XSpiPs_GetDelays(const XSpiPs *InstancePtr, u8 *DelayNss, u8 *DelayBtwn, u8 *DelayAfter, u8 *DelayInit)
This function gets the delay settings for an SPI device.
The delay register controls the Delay Between Transfers, Delay After Transfers, and the Delay Initially. The default value is 0x0. InstancePtr is a pointer to the XSpiPs instance. DelayNss is a pointer to the delay for which the chip select outputs will be de-asserted between words when CPHA=0. DelayBtwn is a pointer to the Delay Between transfers value. This is a return parameter. DelayAfter is a pointer to the Delay After transfer value. This is a return parameter. DelayInit is a pointer to the Delay Initially value. This is a return parameter. None. None.
References XSpiPs_Config::BaseAddress, XSpiPs::Config, XSpiPs::IsReady, XSPIPS_DR_AFTER_MASK, XSPIPS_DR_AFTER_SHIFT, XSPIPS_DR_BTWN_MASK, XSPIPS_DR_BTWN_SHIFT, XSPIPS_DR_INIT_MASK, XSPIPS_DR_NSS_MASK, XSPIPS_DR_NSS_SHIFT, XSPIPS_DR_OFFSET, XSpiPs_ReadReg.
Referenced by XSpiPs_SelfTest.