
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2021.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT

*
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xcsudma.h"

/*
* The configuration table for devices
*/

XCsuDma_Config XCsuDma_ConfigTable[XPAR_XCSUDMA_NUM_INSTANCES] =
{
	{
		XPAR_PSV_PMC_DMA_0_DEVICE_ID,
		XPAR_PSV_PMC_DMA_0_BASEADDR,
		XPAR_PSV_PMC_DMA_0_DMATYPE
	},
	{
		XPAR_PSV_PMC_DMA_1_DEVICE_ID,
		XPAR_PSV_PMC_DMA_1_BASEADDR,
		XPAR_PSV_PMC_DMA_1_DMATYPE
	}
};
