
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2021.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT

*
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xqspipsu.h"

/*
* The configuration table for devices
*/

XQspiPsu_Config XQspiPsu_ConfigTable[XPAR_XQSPIPSU_NUM_INSTANCES] =
{
	{
		XPAR_PSV_PMC_QSPI_0_DEVICE_ID,
		XPAR_PSV_PMC_QSPI_0_BASEADDR,
		XPAR_PSV_PMC_QSPI_0_QSPI_CLK_FREQ_HZ,
		XPAR_PSV_PMC_QSPI_0_QSPI_MODE,
		XPAR_PSV_PMC_QSPI_0_QSPI_BUS_WIDTH,
		XPAR_PSV_PMC_QSPI_0_IS_CACHE_COHERENT
	}
};
