xtmr_inject.h
XTMR_INJECT_H
XTI_STANDARD_LMB_WIDTH
int XTMR_Inject_Initialize(XTMR_Inject *InstancePtr, UINTPTR BaseAddr)
Initialize a XTMR_Inject instance.
InstancePtr is a pointer to the XTMR_Inject instance. DeviceId is the unique id of the device controlled by this XTMR_Inject instance. Passing in a device id associates the generic XTMR_Inject instance to a specific device, as chosen by the caller or application developer. XST_SUCCESS if everything starts up as expected.XST_DEVICE_NOT_FOUND if the device is not found in the configuration table. None.
References XTMR_Inject_Config::RegBaseAddr, XTMR_Inject_CfgInitialize.
Referenced by TMR_InjectSelfTestExample.
XTMR_Inject_Config * XTMR_Inject_LookupConfig(UINTPTR BaseAddr)
int XTMR_Inject_CfgInitialize(XTMR_Inject *InstancePtr, XTMR_Inject_Config *Config, UINTPTR EffectiveAddr)
Initialize a XTMR_Inject instance.
The receive and transmit FIFOs of the core are not flushed, so the user may want to flush them. The hardware device does not have any way to disable the receiver such that any valid data may be present in the receive FIFO. This function disables the core interrupt. The baudrate and format of the data are fixed in the hardware at hardware build time. InstancePtr is a pointer to the XTMR_Inject instance. Config is a reference to a structure containing information about a specific TMR Inject device. This function initializes an InstancePtr object for a specific device specified by the contents of Config. This function can initialize multiple instance objects with the use of multiple calls giving different Config information on each call. EffectiveAddr is the device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, use Config->BaseAddress for this parameters, passing the physical address instead. XST_SUCCESS if everything starts up as expected. The Config pointer argument is not used by this function, but is provided to keep the function signature consistent with other drivers.
References XTMR_Inject::Address, XTMR_Inject::CpuId, XTMR_Inject::Inject, XTMR_Inject::Instruction, XTMR_Inject_Config::LMBAddrWidth, XTMR_Inject::Magic, XTMR_Inject_Config::MagicByte, XTMR_Inject::MagicByte, XTMR_Inject_WriteReg, XTMR_Inject_WriteReg64.
Referenced by XTMR_Inject_Initialize.
void XTMR_Inject_Enable(XTMR_Inject *InstancePtr, u8 CpuId)
This function enables fault injection for the indicated CPU.
InstancePtr is a pointer to the XTMR_Inject instance. CpuId is the CPU ID of the CPU where faults are to be injected. Must be 1 to 3. None.
References XTMR_Inject::CpuId, XTMR_Inject::Inject, XTMR_Inject::Magic, XTMR_Inject::MagicByte, XTMR_Inject_WriteReg.
void XTMR_Inject_Disable(XTMR_Inject *InstancePtr)
This function disables fault injection.
InstancePtr is a pointer to the XTMR_Inject instance. None.
References XTMR_Inject::CpuId, XTMR_Inject::Inject, XTMR_Inject::Magic, XTMR_Inject_WriteReg.
u32 XTMR_Inject_InjectBit(XTMR_Inject *InstancePtr, u32 Value, u8 Bit)
This function can be used to inject a fault in either:
An address bit of a memory or memory mapped register address for any read or write access on AXI or LMB. A data bit written to memory or a memory mapped register on AXI or LMB, as well as output on an AXI Stream. < InstancePtr is a pointer to the XTMR_Inject instance. Value is the memory or register address, oro the data. Bit is the bit where the fault is injected. Must be 0 to 31. Either the unchanged value, or value with the fault injected for the CPU set up for fault injection. None.
u32 XTMR_Inject_InjectMask(XTMR_Inject *InstancePtr, u32 Value, u32 Mask)
This function can be used to inject any number of faults defined by the Mask parameter in either:
Any address bits of a memory or memory mapped register address for any read or write access on AXI or LMB. Any data bits written to memory or a memory mapped register on AXI or LMB, as well as output on an AXI Stream. < InstancePtr is a pointer to the XTMR_Inject instance. Value is the memory or register address, oro the data. Mask defines the bits where faults are injected. A fault is injected for every bit in the mask set to 1. Either the unchanged value, or value with the faults injected for the CPU set up for fault injection. None.
int XTMR_Inject_SelfTest(XTMR_Inject *InstancePtr)
Runs a self-test on the device hardware.
Since there is no way to perform a loopback in the hardware, this test can only check the state of the status register to verify it is correct. This test assumes that the hardware device is still in its reset state, but has been initialized with the Initialize function. InstancePtr is a pointer to the XTMR_Inject instance. XST_SUCCESS if the self-test was successful.XST_FAILURE if the self-test failed, the status register value was not correct None.
Referenced by TMR_InjectSelfTestExample.