bram
XBRAM_ECC_STATUS_OFFSET
ECC status Register.
Referenced by XBram_InterruptClear.
XBRAM_ECC_EN_IRQ_OFFSET
ECC interrupt enable Register.
Referenced by XBram_InterruptDisable, XBram_InterruptEnable, XBram_InterruptGetEnabled, XBram_InterruptGetStatus.
XBRAM_ECC_ON_OFF_OFFSET
ECC on/off register.
XBRAM_CE_CNT_OFFSET
Correctable error counter Register.
XBRAM_CE_FFD_0_OFFSET
Correctable error first failing data Register, 31-0.
XBRAM_CE_FFD_1_OFFSET
Correctable error first failing data Register, 63-32.
XBRAM_CE_FFD_2_OFFSET
Correctable error first failing data Register, 95-64.
XBRAM_CE_FFD_3_OFFSET
Correctable error first failing data Register, 127-96.
XBRAM_CE_FFD_4_OFFSET
Correctable error first failing data Register, 159-128.
XBRAM_CE_FFD_5_OFFSET
Correctable error first failing data Register, 191-160.
XBRAM_CE_FFD_6_OFFSET
Correctable error first failing data Register, 223-192.
XBRAM_CE_FFD_7_OFFSET
Correctable error first failing data Register, 255-224.
XBRAM_CE_FFD_8_OFFSET
Correctable error first failing data Register, 287-256.
XBRAM_CE_FFD_9_OFFSET
Correctable error first failing data Register, 319-288.
XBRAM_CE_FFD_10_OFFSET
Correctable error first failing data Register, 351-320.
XBRAM_CE_FFD_11_OFFSET
Correctable error first failing data Register, 383-352.
XBRAM_CE_FFD_12_OFFSET
Correctable error first failing data Register, 415-384.
XBRAM_CE_FFD_13_OFFSET
Correctable error first failing data Register, 447-416.
XBRAM_CE_FFD_14_OFFSET
Correctable error first failing data Register, 479-448.
XBRAM_CE_FFD_15_OFFSET
Correctable error first failing data Register, 511-480.
XBRAM_CE_FFD_16_OFFSET
Correctable error first failing data Register, 543-512.
XBRAM_CE_FFD_17_OFFSET
Correctable error first failing data Register, 575-544.
XBRAM_CE_FFD_18_OFFSET
Correctable error first failing data Register, 607-576.
XBRAM_CE_FFD_19_OFFSET
Correctable error first failing data Register, 639-608.
XBRAM_CE_FFD_20_OFFSET
Correctable error first failing data Register, 671-640.
XBRAM_CE_FFD_21_OFFSET
Correctable error first failing data Register, 703-672.
XBRAM_CE_FFD_22_OFFSET
Correctable error first failing data Register, 735-704.
XBRAM_CE_FFD_23_OFFSET
Correctable error first failing data Register, 767-736.
XBRAM_CE_FFD_24_OFFSET
Correctable error first failing data Register, 799-768.
XBRAM_CE_FFD_25_OFFSET
Correctable error first failing data Register, 831-800.
XBRAM_CE_FFD_26_OFFSET
Correctable error first failing data Register, 863-832.
XBRAM_CE_FFD_27_OFFSET
Correctable error first failing data Register, 895-864.
XBRAM_CE_FFD_28_OFFSET
Correctable error first failing data Register, 927-896.
XBRAM_CE_FFD_29_OFFSET
Correctable error first failing data Register, 959-928.
XBRAM_CE_FFD_30_OFFSET
Correctable error first failing data Register, 991-960.
XBRAM_CE_FFD_31_OFFSET
Correctable error first failing data Register, 1023-992.
XBRAM_CE_FFE_0_OFFSET
Correctable error first failing ECC Register, 31-0.
XBRAM_CE_FFE_1_OFFSET
Correctable error first failing ECC Register, 63-32.
XBRAM_CE_FFE_2_OFFSET
Correctable error first failing ECC Register, 95-64.
XBRAM_CE_FFE_3_OFFSET
Correctable error first failing ECC Register, 127-96.
XBRAM_CE_FFE_4_OFFSET
Correctable error first failing ECC Register, 159-128.
XBRAM_CE_FFE_5_OFFSET
Correctable error first failing ECC Register, 191-160.
XBRAM_CE_FFE_6_OFFSET
Correctable error first failing ECC Register, 223-192.
XBRAM_CE_FFE_7_OFFSET
Correctable error first failing ECC Register, 255-224.
XBRAM_CE_FFA_0_OFFSET
Correctable error first failing address Register 31-0.
XBRAM_CE_FFA_1_OFFSET
Correctable error first failing address Register 63-32.
XBRAM_UE_FFD_0_OFFSET
Uncorrectable error first failing data Register, 31-0.
XBRAM_UE_FFD_1_OFFSET
Uncorrectable error first failing data Register, 63-32.
XBRAM_UE_FFD_2_OFFSET
Uncorrectable error first failing data Register, 95-64.
XBRAM_UE_FFD_3_OFFSET
Uncorrectable error first failing data Register, 127-96.
XBRAM_UE_FFD_4_OFFSET
Uncorrectable error first failing data Register, 159-128.
XBRAM_UE_FFD_5_OFFSET
Uncorrectable error first failing data Register, 191-160.
XBRAM_UE_FFD_6_OFFSET
Uncorrectable error first failing data Register, 223-192.
XBRAM_UE_FFD_7_OFFSET
Uncorrectable error first failing data Register, 255-224.
XBRAM_UE_FFD_8_OFFSET
Uncorrectable error first failing data Register, 287-256.
XBRAM_UE_FFD_9_OFFSET
Uncorrectable error first failing data Register, 319-288.
XBRAM_UE_FFD_10_OFFSET
Uncorrectable error first failing data Register, 351-320.
XBRAM_UE_FFD_11_OFFSET
Uncorrectable error first failing data Register, 383-352.
XBRAM_UE_FFD_12_OFFSET
Uncorrectable error first failing data Register, 415-384.
XBRAM_UE_FFD_13_OFFSET
Uncorrectable error first failing data Register, 447-416.
XBRAM_UE_FFD_14_OFFSET
Uncorrectable error first failing data Register, 479-448.
XBRAM_UE_FFD_15_OFFSET
Uncorrectable error first failing data Register, 511-480.
XBRAM_UE_FFD_16_OFFSET
Uncorrectable error first failing data Register, 543-512.
XBRAM_UE_FFD_17_OFFSET
Uncorrectable error first failing data Register, 575-544.
XBRAM_UE_FFD_18_OFFSET
Uncorrectable error first failing data Register, 607-576.
XBRAM_UE_FFD_19_OFFSET
Uncorrectable error first failing data Register, 639-608.
XBRAM_UE_FFD_20_OFFSET
Uncorrectable error first failing data Register, 671-640.
XBRAM_UE_FFD_21_OFFSET
Uncorrectable error first failing data Register, 703-672.
XBRAM_UE_FFD_22_OFFSET
Uncorrectable error first failing data Register, 735-704.
XBRAM_UE_FFD_23_OFFSET
Uncorrectable error first failing data Register, 767-736.
XBRAM_UE_FFD_24_OFFSET
Uncorrectable error first failing data Register, 799-768.
XBRAM_UE_FFD_25_OFFSET
Uncorrectable error first failing data Register, 831-800.
XBRAM_UE_FFD_26_OFFSET
Uncorrectable error first failing data Register, 863-832.
XBRAM_UE_FFD_27_OFFSET
Uncorrectable error first failing data Register, 895-864.
XBRAM_UE_FFD_28_OFFSET
Uncorrectable error first failing data Register, 927-896.
XBRAM_UE_FFD_29_OFFSET
Uncorrectable error first failing data Register, 959-928.
XBRAM_UE_FFD_30_OFFSET
Uncorrectable error first failing data Register, 991-960.
XBRAM_UE_FFD_31_OFFSET
Uncorrectable error first failing data Register, 1023-992.
XBRAM_UE_FFE_0_OFFSET
Uncorrectable error first failing ECC Register, 31-0.
XBRAM_UE_FFE_1_OFFSET
Uncorrectable error first failing ECC Register, 63-32.
XBRAM_UE_FFE_2_OFFSET
Uncorrectable error first failing ECC Register, 95-64.
XBRAM_UE_FFE_3_OFFSET
Uncorrectable error first failing ECC Register, 127-96.
XBRAM_UE_FFE_4_OFFSET
Uncorrectable error first failing ECC Register, 159-128.
XBRAM_UE_FFE_5_OFFSET
Uncorrectable error first failing ECC Register, 191-160.
XBRAM_UE_FFE_6_OFFSET
Uncorrectable error first failing ECC Register, 223-192.
XBRAM_UE_FFE_7_OFFSET
Uncorrectable error first failing ECC Register, 255-224.
XBRAM_UE_FFA_0_OFFSET
Uncorrectable error first failing address Register 31-0.
XBRAM_UE_FFA_1_OFFSET
Uncorrectable error first failing address Register 63-32.
XBRAM_FI_D_0_OFFSET
Fault injection Data Register, 31-0.
XBRAM_FI_D_1_OFFSET
Fault injection Data Register, 63-32.
XBRAM_FI_D_2_OFFSET
Fault injection Data Register, 95-64.
XBRAM_FI_D_3_OFFSET
Fault injection Data Register, 127-96.
XBRAM_FI_D_4_OFFSET
Fault injection Data Register, 159-128.
XBRAM_FI_D_5_OFFSET
Fault injection Data Register, 191-160.
XBRAM_FI_D_6_OFFSET
Fault injection Data Register, 223-192.
XBRAM_FI_D_7_OFFSET
Fault injection Data Register, 255-224.
XBRAM_FI_D_8_OFFSET
Fault injection Data Register, 287-256.
XBRAM_FI_D_9_OFFSET
Fault injection Data Register, 319-288.
XBRAM_FI_D_10_OFFSET
Fault injection Data Register, 351-320.
XBRAM_FI_D_11_OFFSET
Fault injection Data Register, 383-352.
XBRAM_FI_D_12_OFFSET
Fault injection Data Register, 415-384.
XBRAM_FI_D_13_OFFSET
Fault injection Data Register, 447-416.
XBRAM_FI_D_14_OFFSET
Fault injection Data Register, 479-448.
XBRAM_FI_D_15_OFFSET
Fault injection Data Register, 511-480.
XBRAM_FI_D_16_OFFSET
Fault injection Data Register, 543-512.
XBRAM_FI_D_17_OFFSET
Fault injection Data Register, 575-544.
XBRAM_FI_D_18_OFFSET
Fault injection Data Register, 607-576.
XBRAM_FI_D_19_OFFSET
Fault injection Data Register, 639-608.
XBRAM_FI_D_20_OFFSET
Fault injection Data Register, 671-640.
XBRAM_FI_D_21_OFFSET
Fault injection Data Register, 703-672.
XBRAM_FI_D_22_OFFSET
Fault injection Data Register, 735-704.
XBRAM_FI_D_23_OFFSET
Fault injection Data Register, 767-736.
XBRAM_FI_D_24_OFFSET
Fault injection Data Register, 799-768.
XBRAM_FI_D_25_OFFSET
Fault injection Data Register, 831-800.
XBRAM_FI_D_26_OFFSET
Fault injection Data Register, 863-832.
XBRAM_FI_D_27_OFFSET
Fault injection Data Register, 895-864.
XBRAM_FI_D_28_OFFSET
Fault injection Data Register, 927-896.
XBRAM_FI_D_29_OFFSET
Fault injection Data Register, 959-928.
XBRAM_FI_D_30_OFFSET
Fault injection Data Register, 991-960.
XBRAM_FI_D_31_OFFSET
Fault injection Data Register, 1023-992.
XBRAM_FI_ECC_0_OFFSET
Fault injection ECC Register, 31-0.
XBRAM_FI_ECC_1_OFFSET
Fault injection ECC Register, 63-32.
XBRAM_FI_ECC_2_OFFSET
Fault injection ECC Register, 95-64.
XBRAM_FI_ECC_3_OFFSET
Fault injection ECC Register, 127-96.
XBRAM_FI_ECC_4_OFFSET
Fault injection ECC Register, 159-128.
XBRAM_FI_ECC_5_OFFSET
Fault injection ECC Register, 191-160.
XBRAM_FI_ECC_6_OFFSET
Fault injection ECC Register, 223-192.
XBRAM_FI_ECC_7_OFFSET
Fault injection ECC Register, 255-224.
XBRAM_IR_CE_MASK
Mask for the correctable error.
Referenced by XBram_SelfTest.
XBRAM_IR_UE_MASK
Mask for the uncorrectable error.
Referenced by XBram_SelfTest.
XBRAM_IR_ALL_MASK
Mask of all bits.
Referenced by BramIntrExample, XBram_SelfTest.
XBram_Config XBram_ConfigTable[][]
This table contains configuration information for each BRAM device in the system.
The order must match the XBram_Config definition.
u32 PrngResult
XBram_Config XBram_ConfigTable[][]
This table contains configuration information for each BRAM device in the system.
The order must match the XBram_Config definition.
int XBram_CfgInitialize(XBram *InstancePtr, XBram_Config *Config, UINTPTR EffectiveAddr)
Initialize the XBram instance provided by the caller based on the given configuration data.
Nothing is done except to initialize the InstancePtr. InstancePtr is a pointer to an XBram instance. The memory the pointer references must be pre-allocated by the caller. Further calls to manipulate the driver through the XBram API must be made with this pointer. Config is a reference to a structure containing information about a specific BRAM device. This function initializes an InstancePtr object for a specific device specified by the contents of Config. This function can initialize multiple instance objects with the use of multiple calls giving different Config information on each call. EffectiveAddr is the device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, use Config->BaseAddress for this parameters, passing the physical address instead. XST_SUCCESS Initialization was successful. None.
References XBram_Config::CorrectableCounterBits, XBram_Config::CorrectableFailingDataRegs, XBram_Config::CorrectableFailingRegisters, XBram_Config::CtrlBaseAddress, XBram_Config::DataWidth, XBram_Config::EccPresent, XBram_Config::EccStatusInterruptPresent, XBram_Config::FaultInjectionPresent, XBram_Config::IntId, XBram_Config::IntrParent, XBram_Config::MemBaseAddress, XBram_Config::MemHighAddress, XBram_Config::UncorrectableFailingDataRegs, XBram_Config::UncorrectableFailingRegisters, XBram_Config::WriteAccess.
Referenced by BramExample, BramIntrExample.
XBram_Config * XBram_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XBram_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xbram.h for the definition of XBram_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XBram_Config::Name.
Referenced by BramExample, BramIntrExample.
int XBram_SelfTest(XBram *InstancePtr, u8 IntMask)
Run a self-test on the driver/device.
Unless fault injection is implemented in hardware, this function only does a minimal test in which available registers (if any) are written and read.With fault injection, all possible single-bit and double-bit errors are injected, and checked to the extent possible, given the implemented hardware. InstancePtr is a pointer to the XBram instance. IntMask is the interrupt mask to use. When testing with interrupts, this should be set to allow interrupt generation, otherwise it should be 0. XST_SUCCESS if fault injection/detection is working properly OR if ECC is Not Enabled in the HW.XST_FAILURE if the injected fault is not correctly detected or the Control Base Address is Zero when ECC is enabled. If the BRAM device is not present in the hardware a bus error could be generated. Other indicators of a bus error, such as registers in bridges or buses, may be necessary to determine if this function caused a bus error. None.
References XBram_Config::CorrectableCounterBits, XBram_Config::CorrectableFailingDataRegs, XBram_Config::CorrectableFailingRegisters, XBram_Config::CtrlBaseAddress, XBram_Config::DataWidth, XBram_Config::EccPresent, XBram_Config::EccStatusInterruptPresent, XBram_Config::FaultInjectionPresent, XBram_Config::MemBaseAddress, XBram_Config::MemHighAddress, XBram_Config::UncorrectableFailingDataRegs, XBram_Config::UncorrectableFailingRegisters, XBram_Config::WriteAccess, XBRAM_IR_ALL_MASK, XBRAM_IR_CE_MASK, XBRAM_IR_UE_MASK.
Referenced by BramExample, BramIntrExample.
void XBram_InterruptEnable(XBram *InstancePtr, u32 Mask)
Enable interrupts.
This function will assert if the hardware device has not been built with interrupt capabilities. InstancePtr is the BRAM instance to operate on. Mask is the mask to enable. Bit positions of 1 are enabled. This mask is formed by OR'ing bits from XBRAM_IR* bits which are contained in xbram_hw.h. None. None.
References XBram_Config::CtrlBaseAddress, XBRAM_ECC_EN_IRQ_OFFSET, XBram_ReadReg, XBram_WriteReg.
void XBram_InterruptDisable(XBram *InstancePtr, u32 Mask)
Disable interrupts.
This function allows each specific interrupt to be disabled. This function will assert if the hardware device has not been built with interrupt capabilities. InstancePtr is the BRAM instance to operate on. Mask is the mask to disable. Bits set to 1 are disabled. This mask is formed by OR'ing bits from XBRAM_IR* bits which are contained in xbram_hw.h. None. None.
References XBram_Config::CtrlBaseAddress, XBRAM_ECC_EN_IRQ_OFFSET, XBram_ReadReg, XBram_WriteReg.
void XBram_InterruptClear(XBram *InstancePtr, u32 Mask)
Clear pending interrupts with the provided mask.
This function should be called after the software has serviced the interrupts that are pending. This function will assert if the hardware device has not been built with interrupt capabilities. InstancePtr is the BRAM instance to operate on. Mask is the mask to clear pending interrupts for. Bit positions of 1 are cleared. This mask is formed by OR'ing bits from XBRAM_IR* bits which are contained in xbram_hw.h. None. None.
References XBram_Config::CtrlBaseAddress, XBRAM_ECC_STATUS_OFFSET, XBram_ReadReg, XBram_WriteReg.
u32 XBram_InterruptGetEnabled(XBram *InstancePtr)
Returns the interrupt enable mask.
This function will assert if the hardware device has not been built with interrupt capabilities. InstancePtr is the BRAM instance to operate on. A mask of bits made from XBRAM_IR* bits which are contained in xbram_hw.h.None. None.
References XBram_Config::CtrlBaseAddress, XBRAM_ECC_EN_IRQ_OFFSET, XBram_ReadReg.
u32 XBram_InterruptGetStatus(XBram *InstancePtr)
Returns the status of interrupt signals.
Any bit in the mask set to 1 indicates that the channel associated with the bit has asserted an interrupt condition. This function will assert if the hardware device has not been built with interrupt capabilities. InstancePtr is the BRAM instance to operate on. A pointer to a mask of bits made from XBRAM_IR* bits which are contained in xbram_hw.h. The interrupt status indicates the status of the device regardless if the interrupts from the devices have been enabled or not through XBram_InterruptEnable().
References XBram_Config::CtrlBaseAddress, XBRAM_ECC_EN_IRQ_OFFSET, XBram_ReadReg.
static u32 PrngData(u32 *PrngResult)
Generate a pseudo random number.
The PrngResult is the previous random number in the pseudo random sequence, also known as the seed. It is modified to the calculated pseudo random number by the function. The generated pseudo random number None.
static u32 CalculateEcc(u32 Data)
Calculate ECC from Data.
The Data Value The calculated ECC None.
static void InjectErrors(XBram *InstancePtr, const UINTPTR Addr, int Index1, int Index2, int Width, u32 *ActualData, u32 *ActualEcc)
Inject errors using the hardware fault injection functionality, and write random data and read it back using the indicated location.
InstancePtr is a pointer to the XBram instance to be worked on. The Addr is the indicated memory location to use The Index1 is the bit location of the first injected error The Index2 is the bit location of the second injected error The Width is the data byte width The ActualData is filled in with expected data for checking The ActualEcc is filled in with expected ECC for checking None None.
XBRAM_H
XBRAM_HW_H
XBram_In32
XBram_Out32
XBram_In16
XBram_Out16
XBram_In8
XBram_Out8
XBram_WriteReg
Write a value to a BRAM register.
A 32 bit write is performed. BaseAddress is the base address of the BRAM device register. RegOffset is the register offset from the base to write to. Data is the data written to the register. None. C-style signature: void XBram_WriteReg(u32 BaseAddress, u32 RegOffset, u32 Data)
Referenced by XBram_InterruptClear, XBram_InterruptDisable, XBram_InterruptEnable.
XBram_ReadReg
Read a value from a BRAM register.
A 32 bit read is performed. BaseAddress is the base address of the BRAM device registers. RegOffset is the register offset from the base to read from. Data read from the register. C-style signature: u32 XBram_ReadReg(u32 BaseAddress, u32 RegOffset)
Referenced by XBram_InterruptClear, XBram_InterruptDisable, XBram_InterruptEnable, XBram_InterruptGetEnabled, XBram_InterruptGetStatus.
TOTAL_BITS
RD
WR
CHECK