xbram.h
XBRAM_H
XBram_Config * XBram_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XBram_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xbram.h for the definition of XBram_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XBram_Config::Name.
Referenced by BramExample, BramIntrExample.
int XBram_CfgInitialize(XBram *InstancePtr, XBram_Config *Config, UINTPTR EffectiveAddr)
Initialize the XBram instance provided by the caller based on the given configuration data.
Nothing is done except to initialize the InstancePtr. InstancePtr is a pointer to an XBram instance. The memory the pointer references must be pre-allocated by the caller. Further calls to manipulate the driver through the XBram API must be made with this pointer. Config is a reference to a structure containing information about a specific BRAM device. This function initializes an InstancePtr object for a specific device specified by the contents of Config. This function can initialize multiple instance objects with the use of multiple calls giving different Config information on each call. EffectiveAddr is the device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, use Config->BaseAddress for this parameters, passing the physical address instead. XST_SUCCESS Initialization was successful. None.
References XBram_Config::CorrectableCounterBits, XBram_Config::CorrectableFailingDataRegs, XBram_Config::CorrectableFailingRegisters, XBram_Config::CtrlBaseAddress, XBram_Config::DataWidth, XBram_Config::EccPresent, XBram_Config::EccStatusInterruptPresent, XBram_Config::FaultInjectionPresent, XBram_Config::IntId, XBram_Config::IntrParent, XBram_Config::MemBaseAddress, XBram_Config::MemHighAddress, XBram_Config::UncorrectableFailingDataRegs, XBram_Config::UncorrectableFailingRegisters, XBram_Config::WriteAccess.
Referenced by BramExample, BramIntrExample.
int XBram_SelfTest(XBram *InstancePtr, u8 IntMask)
Run a self-test on the driver/device.
Unless fault injection is implemented in hardware, this function only does a minimal test in which available registers (if any) are written and read.With fault injection, all possible single-bit and double-bit errors are injected, and checked to the extent possible, given the implemented hardware. InstancePtr is a pointer to the XBram instance. IntMask is the interrupt mask to use. When testing with interrupts, this should be set to allow interrupt generation, otherwise it should be 0. XST_SUCCESS if fault injection/detection is working properly OR if ECC is Not Enabled in the HW.XST_FAILURE if the injected fault is not correctly detected or the Control Base Address is Zero when ECC is enabled. If the BRAM device is not present in the hardware a bus error could be generated. Other indicators of a bus error, such as registers in bridges or buses, may be necessary to determine if this function caused a bus error. None.
References XBram_Config::CorrectableCounterBits, XBram_Config::CorrectableFailingDataRegs, XBram_Config::CorrectableFailingRegisters, XBram_Config::CtrlBaseAddress, XBram_Config::DataWidth, XBram_Config::EccPresent, XBram_Config::EccStatusInterruptPresent, XBram_Config::FaultInjectionPresent, XBram_Config::MemBaseAddress, XBram_Config::MemHighAddress, XBram_Config::UncorrectableFailingDataRegs, XBram_Config::UncorrectableFailingRegisters, XBram_Config::WriteAccess, XBRAM_IR_ALL_MASK, XBRAM_IR_CE_MASK, XBRAM_IR_UE_MASK.
Referenced by BramExample, BramIntrExample.
void XBram_InterruptEnable(XBram *InstancePtr, u32 Mask)
Enable interrupts.
This function will assert if the hardware device has not been built with interrupt capabilities. InstancePtr is the BRAM instance to operate on. Mask is the mask to enable. Bit positions of 1 are enabled. This mask is formed by OR'ing bits from XBRAM_IR* bits which are contained in xbram_hw.h. None. None.
References XBram_Config::CtrlBaseAddress, XBRAM_ECC_EN_IRQ_OFFSET, XBram_ReadReg, XBram_WriteReg.
void XBram_InterruptDisable(XBram *InstancePtr, u32 Mask)
Disable interrupts.
This function allows each specific interrupt to be disabled. This function will assert if the hardware device has not been built with interrupt capabilities. InstancePtr is the BRAM instance to operate on. Mask is the mask to disable. Bits set to 1 are disabled. This mask is formed by OR'ing bits from XBRAM_IR* bits which are contained in xbram_hw.h. None. None.
References XBram_Config::CtrlBaseAddress, XBRAM_ECC_EN_IRQ_OFFSET, XBram_ReadReg, XBram_WriteReg.
void XBram_InterruptClear(XBram *InstancePtr, u32 Mask)
Clear pending interrupts with the provided mask.
This function should be called after the software has serviced the interrupts that are pending. This function will assert if the hardware device has not been built with interrupt capabilities. InstancePtr is the BRAM instance to operate on. Mask is the mask to clear pending interrupts for. Bit positions of 1 are cleared. This mask is formed by OR'ing bits from XBRAM_IR* bits which are contained in xbram_hw.h. None. None.
References XBram_Config::CtrlBaseAddress, XBRAM_ECC_STATUS_OFFSET, XBram_ReadReg, XBram_WriteReg.
u32 XBram_InterruptGetEnabled(XBram *InstancePtr)
Returns the interrupt enable mask.
This function will assert if the hardware device has not been built with interrupt capabilities. InstancePtr is the BRAM instance to operate on. A mask of bits made from XBRAM_IR* bits which are contained in xbram_hw.h.None. None.
References XBram_Config::CtrlBaseAddress, XBRAM_ECC_EN_IRQ_OFFSET, XBram_ReadReg.
u32 XBram_InterruptGetStatus(XBram *InstancePtr)
Returns the status of interrupt signals.
Any bit in the mask set to 1 indicates that the channel associated with the bit has asserted an interrupt condition. This function will assert if the hardware device has not been built with interrupt capabilities. InstancePtr is the BRAM instance to operate on. A pointer to a mask of bits made from XBRAM_IR* bits which are contained in xbram_hw.h. The interrupt status indicates the status of the device regardless if the interrupts from the devices have been enabled or not through XBram_InterruptEnable().
References XBram_Config::CtrlBaseAddress, XBRAM_ECC_EN_IRQ_OFFSET, XBram_ReadReg.