xclk_wiz.c
static void StubErrCallBack(void *CallBackRef, u32 ErrorMask)
This routine is a stub for the asynchronous error interrupt callback.
The stub is here in case the upper layer forgot to set the handler. On initialization, Error interrupt handler is set to this callback. It is considered an error for this handler to be invoked. CallBackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. ErrorMask is a bit mask indicating the cause of the error. Its value equals 'OR'ing one or more XCLK_WIZ_ISR_*_MASK values defined in xclk_wiz_hw.h. None None
u32 XClk_Wiz_CfgInitialize(XClk_Wiz *InstancePtr, XClk_Wiz_Config *CfgPtr, UINTPTR EffectiveAddr)
Initialize the XClk_Wiz instance provided by the caller based on the given Config structure.
InstancePtr is the XClk_Wiz instance to operate on. CfgPtr is the device configuration structure containing information about a specific CLK_WIZ. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS Initialization was successful.XST_FAILURE Initialization was failure. None
References XClk_Wiz_Config::BaseAddr, XClk_Wiz::ClkGlitchCallBack, XClk_Wiz::ClkOutOfRangeCallBack, XClk_Wiz::ClkStopCallBack, XClk_Wiz::Config, XClk_Wiz::ErrorCallBack, XClk_Wiz_Config::IntId, XClk_Wiz_Config::IntrParent, XClk_Wiz::IsReady, XClk_Wiz::MinErr.
Referenced by ClkWiz_Example, ClkWiz_IntrExample.
static u32 XClk_Wiz_CalculateDivisors(XClk_Wiz *InstancePtr, u64 SetRate)
Calculate the M, D, and O values for the given SetRate frequency.
InstancePtr is the XClk_Wiz instance to operate on. SetRate is the frequency for which the M, D and O values are to be calculated. XST_SUCCESS Initialization was successful.XST_FAILURE Initialization was failure. None
static u32 XClk_Wiz_CalculateDivisorsHz(XClk_Wiz *InstancePtr, u64 SetRate)
Calculate the M, D, and O values for the given SetRate frequency.
InstancePtr is the XClk_Wiz instance to operate on. SetRate is the frequency for which the M, D and O values are to be calculated in Hz. XST_SUCCESS Initialization was successful.XST_FAILURE Initialization was failure. None
void XClk_Wiz_SetMinErr(XClk_Wiz *InstancePtr, u64 Minerr)
Set the Minimum error that can be tolerated.
InstancePtr is the XClk_Wiz instance to operate on. Minerr is the error margin that can be tolerated in Hz. None Should be called only if there is only one output clock.
References XClk_Wiz::IsReady, XClk_Wiz::MinErr.
static void XClk_Wiz_UpdateO(XClk_Wiz *InstancePtr, u32 ClockId)
static void XClk_Wiz_UpdateD(XClk_Wiz *InstancePtr)
static void XClk_Wiz_UpdateM(XClk_Wiz *InstancePtr)
u32 XClk_Wiz_SetRateHz(XClk_Wiz *InstancePtr, u64 SetRate)
Change the frequency to the given rate in Hz.
InstancePtr is the XClk_Wiz instance to operate on. SetRate is the frequency in Hz to be set. XST_SUCCESS Frequency setting was successful.XST_FAILURE frequency setting failed. Should be called only if there is only one output clock.
References XClk_Wiz::Config, XClk_Wiz::DVal, XClk_Wiz::IsReady, XClk_Wiz::MVal, XClk_Wiz_Config::NumClocks, XClk_Wiz::OVal, XCLK_WIZ_RECONFIG_OFFSET.
Referenced by ClkWiz_Example.
static u64 XClk_Wiz_GetVco(XClk_Wiz *InstancePtr)
s32 XClk_Wiz_GetRate(XClk_Wiz *InstancePtr, u32 ClockId, u64 *Rate)
Get the clock frequency for the given ClockId.
InstancePtr is the XClk_Wiz instance to operate on. ClockId is the output clock. Rate clock rate in Hz. XST_SUCCESS getting the frequency was successful.XST_FAILURE getting the frequency failed.
References XClk_Wiz::Config, XClk_Wiz_Config::NumClocks, XCLK_WIZ_REG3_PREDIV2.
Referenced by ClkWiz_Example.
s32 XClk_Wiz_SetLeafRateHz(XClk_Wiz *InstancePtr, u32 ClockId, u64 SetRate)
Set the clock rate frequency for the given ClockId.
InstancePtr is the XClk_Wiz instance to operate on. ClockId is the output clock. SetRate clock rate in Hz. XST_SUCCESS Setting the rate was successful.XST_FAILURE Setting rate was failed.
References XClk_Wiz::IsReady, XClk_Wiz::OVal.
Referenced by ClkWiz_Example.
u32 XClk_Wiz_SetRate(XClk_Wiz *InstancePtr, u64 SetRate)
Change the frequency to the given rate.
InstancePtr is the XClk_Wiz instance to operate on. SetRate is the frequency for which is requested in MHz. XST_SUCCESS frequency setting was successful.XST_FAILURE frequency setting failed. Should be called only if there is only one output clock.
References XClk_Wiz::Config, XClk_Wiz::DVal, XClk_Wiz::IsReady, XClk_Wiz::MVal, XClk_Wiz_Config::NumClocks, XClk_Wiz::OVal.
u32 XClk_Wiz_EnableClock(XClk_Wiz *InstancePtr, u32 ClockId)
Enable Clock for the given ClockId.
InstancePtr is the XClk_Wiz instance to operate on. ClockId is the output clock. XST_SUCCESS Initialization was successful.XST_FAILURE Initialization was failure.
References XClk_Wiz_Config::BaseAddr, XClk_Wiz::Config, XClk_Wiz::IsReady, XCLK_WIZ_REG3_USED.
u32 XClk_Wiz_DisableClock(XClk_Wiz *InstancePtr, u32 ClockId)
Disable Clock for the given ClockId.
InstancePtr is the XClk_Wiz instance to operate on. ClockId is the output clock. XST_SUCCESS Initialization was successful.XST_FAILURE Initialization was failure.
References XClk_Wiz_Config::BaseAddr, XClk_Wiz::Config, XClk_Wiz::IsReady, XCLK_WIZ_REG3_USED.
u32 XClk_Wiz_WaitForLock(XClk_Wiz *InstancePtr)
Wait till the clocking wizard is locked to the frequency.
InstancePtr is the XClk_Wiz instance to operate on. XST_SUCCESS if lock was successful.XST_FAILURE on timeout.
References XClk_Wiz_Config::BaseAddr, XClk_Wiz::Config, XClk_Wiz::IsReady, XCLK_WIZ_STATUS_OFFSET.
Referenced by ClkWiz_Example.
void XClk_Wiz_SetInputRate(XClk_Wiz *InstancePtr, double Rate)
Change the Input frequency to the given rate.
InstancePtr is the XClk_Wiz instance to operate on. Rate is the frequency for which is to be set. None Should be called only if the input provider clock is changed eg input clock is si570.
References XClk_Wiz::Config, XClk_Wiz::IsReady, XClk_Wiz_Config::Name, XClk_Wiz_Config::PrimInClkFreq.
u32 XClk_Wiz_GetInputRate(XClk_Wiz *InstancePtr)
Get the Input frequency.
InstancePtr is the XClk_Wiz instance to operate on. Clock frequency in KHz Should be called only if the input provider clock is changed eg input clock is si570.
References XClk_Wiz::Config, XClk_Wiz::IsReady, XClk_Wiz_Config::Name.
void XClk_Wiz_GetInterruptSettings(XClk_Wiz *InstancePtr)
XClk_Wiz_GetInterruptSettings will get the information from clock wizard IER and ISR Registers.
InstancePtr is the XClk_Wiz instance to operate on. None
References XClk_Wiz::ClkIntrEnable, XClk_Wiz::ClkWizIntrStatus, XCLK_WIZ_IER_ALLINTR_MASK, XCLK_WIZ_IER_ALLINTR_SHIFT, XCLK_WIZ_IER_OFFSET, XCLK_WIZ_ISR_ALLINTR_MASK, XCLK_WIZ_ISR_ALLINTR_SHIFT, XCLK_WIZ_ISR_OFFSET.