xclk_wiz_intr_example.c
CLK_LOCK
VCO_FREQ
CLK_WIZ_VCO_FACTOR
DYNAMIC_INPUT_FREQ
DYNAMIC_INPUT_FREQ_FACTOR
DYNAMIC_OUTPUT_FREQ
DYNAMIC_OUTPUT_FREQFACTOR
CLK_WIZ_RECONFIG_OUTPUT
CLK_FRAC_EN
XClk_Wiz ClkWiz_Mon
XClk_Wiz ClkWiz_Dynamic
volatile u8 Clk_Outof_Range_Flag
volatile u8 Clk_Glitch_Flag
volatile u8 Clk_Stop_Flag
u32 ClkWiz_IntrExample(UINTPTR BaseAddress)
This function setups the interrupt system such that interrupts can occur for the CLK_WIZ device.
This function is application specific since the actual system may or may not have an interrupt controller. The CLK_WIZ could be directly connected to a processor without an interrupt controller. The user should modify this function to fit the application. ClkWizPtr contains a pointer to the instance of the CLK_WIZ component which is going to be connected to the interrupt controller. XST_SUCCESS if successful, otherwise XST_FAILURE. None This function is the main entry point for the interrupt example using the XClk_Wiz driver. This function will set up the system with interrupts handlers. BaseAddress contains the base address of the device XST_FAILURE if the system setup failed.XST_SUCCESS should never return since this function, if setup was successful, is blocking. - In XSCT/classic flow, DeviceId is used to look up the device configuration. If system setup was successful, this function is blocking in order to illustrate interrupt handling taking place for HPD events.
References XClk_Wiz_Config::BaseAddr, Clk_Wiz_Reconfig, ClkWiz_ClkGlitchEventHandler, ClkWiz_ClkOutOfRangeEventHandler, ClkWiz_ClkStopEventHandler, XClk_Wiz::Config, Delay, XClk_Wiz_Config::EnableClkMon, XClk_Wiz_Config::IntId, XClk_Wiz_Config::IntrParent, XClk_Wiz_CfgInitialize, XCLK_WIZ_IER_ALLINTR_MASK, XClk_Wiz_InterruptEnable, XClk_Wiz_LookupConfig, XClk_Wiz_SetCallBack.
Referenced by main.
void XClk_Wiz_IntrHandler(void *InstancePtr)
This function is the interrupt handler for the CLK_WIZ core.
This handler reads the pending interrupt from the Interrupt Status register determines the source of the interrupts and calls the respective callbacks for the interrupts that are enabled in Interrupt Enable register and finally clears the interrupts.The application is responsible for connecting this function to the interrupt system. Application beyond this core is also responsible for providing callbacks to handle interrupts and installing the callbacks using XClk_Wiz_SetCallBack() during initialization phase. InstancePtr is a pointer to the XClk_Wiz core instance. None Interrupt should be enabled to execute interrupt handler.
References XClk_Wiz::IsReady, XClk_Wiz_InterruptGetStatus, XCLK_WIZ_ISR_CLKALL_MAXFREQ_MASK, XClk_Wiz::ClkOutOfRangeCallBack, XClk_Wiz::ClkOutOfRangeRef, XCLK_WIZ_ISR_CLKALL_MINFREQ_MASK, XCLK_WIZ_ISR_CLKALL_GLITCH_MASK, XClk_Wiz::ClkGlitchCallBack, XClk_Wiz::ClkGlitchRef, XCLK_WIZ_ISR_CLKALL_STOP_MASK, XClk_Wiz::ClkStopCallBack, XClk_Wiz::ClkStopRef, XClk_Wiz_InterruptClear.
void XClk_Wiz_InterruptEnable(XClk_Wiz *InstancePtr, u32 Mask)
XClk_Wiz_InterruptEnable will enable the interrupts present in the interrupt mask passed onto the function.
InstancePtr is the XClk_Wiz instance to operate on Mask is the interrupt mask which need to be enabled in core None None
References XCLK_WIZ_IER_ALLINTR_MASK.
Referenced by ClkWiz_IntrExample.
int Clk_Wiz_Reconfig(XClk_Wiz_Config *CfgPtr_Dynamic)
This is the Clk_Wiz_Reconfig function, it will reconfigure frequencies as per input array.
CfgPtr_Dynamic provides pointer to clock wizard dynamic config Findex provides the index for Frequency divide register Sindex provides the index for Frequency phase register Error 0 for pass scenarioError > 0 for failure scenario None
References XClk_Wiz_Config::BaseAddr, Wait_For_Lock.
Referenced by ClkWiz_IntrExample.
int Wait_For_Lock(XClk_Wiz_Config *CfgPtr_Dynamic)
This is the Wait_For_Lock function, it will wait for lock to settle change frequency value.
CfgPtr_Dynamic provides pointer to clock wizard dynamic config Error 0 for pass scenarioError > 0 for failure scenario None
References XClk_Wiz_Config::BaseAddr.
Referenced by Clk_Wiz_Reconfig.
void ClkWiz_ClkOutOfRangeEventHandler(void *CallBackRef, u32 Mask)
This function is called when a clock out of range is received by the CLK_WIZ Subsystem core.
CallBackRef contains a callback reference from the driver. In this case it is the instance pointer for the ClkWiz_Mon driver. Mask of interrupt which caused this event None None
References XCLK_WIZ_ISR_CLK0_MAXFREQ_MASK, XCLK_WIZ_ISR_CLK0_MINFREQ_MASK, XCLK_WIZ_ISR_CLK1_MAXFREQ_MASK, XCLK_WIZ_ISR_CLK1_MINFREQ_MASK, XCLK_WIZ_ISR_CLK2_MAXFREQ_MASK, XCLK_WIZ_ISR_CLK2_MINFREQ_MASK, XCLK_WIZ_ISR_CLK3_MAXFREQ_MASK, XCLK_WIZ_ISR_CLK3_MINFREQ_MASK.
Referenced by ClkWiz_IntrExample.
void ClkWiz_ClkGlitchEventHandler(void *CallBackRef, u32 Mask)
This function is called when a clock glitch event is received by the CLK_WIZ Subsystem core.
CallBackRef contains a callback reference from the driver. In this case it is the instance pointer for the ClkWiz_Mon driver. Mask of interrupt which caused this event None None
References XCLK_WIZ_ISR_CLK0_GLITCH_MASK, XCLK_WIZ_ISR_CLK1_GLITCH_MASK, XCLK_WIZ_ISR_CLK2_GLITCH_MASK, XCLK_WIZ_ISR_CLK3_GLITCH_MASK.
Referenced by ClkWiz_IntrExample.
void ClkWiz_ClkStopEventHandler(void *CallBackRef, u32 Mask)
This function is called when a clock stop event is received by the CLK_WIZ Subsystem core.
CallBackRef is a pointer to the XClk_Wiz instance. Mask of interrupt which caused this event None None
References XCLK_WIZ_ISR_CLK0_STOP_MASK, XCLK_WIZ_ISR_CLK1_STOP_MASK, XCLK_WIZ_ISR_CLK2_STOP_MASK, XCLK_WIZ_ISR_CLK3_STOP_MASK.
Referenced by ClkWiz_IntrExample.
void Delay(u32 Seconds)
For Microblaze we use an assembly loop that is roughly the same regardless of optimization level, although caches and memory access time can make the delay vary.
Just keep in mind that after resetting or updating the PHY modes, the PHY typically needs time to recover. Number of seconds to sleep None None
Referenced by ClkWiz_IntrExample.
int main()
This is the main function for XClk_Wiz interrupt example.
If the ClkWiz_IntrExample function which sets up the system succeeds, this function will wait for the interrupts. Notify the events None. XST_FAILURE if the interrupt example was unsuccessful. Unless setup failed, main will never return since ClkWiz_IntrExample is blocking (it is waiting on interrupts for Hot-Plug-Detect (HPD) events.
References ClkWiz_IntrExample.