xclk_wiz_intr.c
void XClk_Wiz_InterruptEnable(XClk_Wiz *InstancePtr, u32 Mask)
XClk_Wiz_InterruptEnable will enable the interrupts present in the interrupt mask passed onto the function.
InstancePtr is the XClk_Wiz instance to operate on Mask is the interrupt mask which need to be enabled in core None None
References XCLK_WIZ_IER_ALLINTR_MASK.
Referenced by ClkWiz_IntrExample.
void XClk_Wiz_InterruptDisable(XClk_Wiz *InstancePtr, u32 Mask)
XClk_Wiz_InterruptDisable will disable the interrupts present in the interrupt mask passed onto the function.
InstancePtr is the XClk_Wiz instance to operate on Mask is the interrupt mask which need to be enabled in core None None
References XCLK_WIZ_IER_ALLINTR_MASK.
u32 XClk_Wiz_InterruptGetEnabled(XClk_Wiz *InstancePtr)
XClk_Wiz_InterruptGetEnabled will get the interrupt mask set (enabled) in the CLK_WIZ core.
InstancePtr is the XClk_Wiz instance to operate on Interrupt Mask with bits set for corresponding interrupt in Interrupt enable register None
u32 XClk_Wiz_InterruptGetStatus(XClk_Wiz *InstancePtr)
XClk_Wiz_InterruptGetStatus will get the list of interrupts pending in the Interrupt Status Register of the CLK_WIZ core.
InstancePtr is the XClk_Wiz instance to operate on Interrupt Mask with bits set for corresponding interrupt in Interrupt Status register None
Referenced by XClk_Wiz_IntrHandler.
void XClk_Wiz_InterruptClear(XClk_Wiz *InstancePtr, u32 Mask)
XClk_Wiz_InterruptClear will clear the interrupts set in the Interrupt Status Register of the CLK_WIZ core.
InstancePtr is the XClk_Wiz instance to operate on Mask is Interrupt Mask with bits set for corresponding interrupt to be cleared in the Interrupt Status register None None
References XCLK_WIZ_IER_ALLINTR_MASK.
Referenced by XClk_Wiz_IntrHandler.
int XClk_Wiz_SetCallBack(XClk_Wiz *InstancePtr, u32 HandleType, void *CallBackFunc, void *CallBackRef)
This routine installs an asynchronous callback function for the given HandlerType:
HandlerType Invoked by this driver when: ----------------------- -------------------------------------------------- XCLK_WIZ_HANDLER_CLK_OUTOF_RANGE Clock under flow/over flow XCLK_WIZ_HANDLER_CLK_GLITCH Clock Glitch XCLK_WIZ_HANDLER_CLK_STOP Clock Stop XCLK_WIZ_HANDLER_OTHERERROR Any other type of interrupts InstancePtr is the XClk_Wiz instance to operate on HandleType is the type of call back to be registered. CallBackFunc is the pointer to a call back function which is called when a particular event occurs. CallBackRef is a void pointer to data to be referenced to by the CallBackFunc XST_SUCCESS when handler is installed. XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XClk_Wiz::ClkGlitchCallBack, XClk_Wiz::ClkGlitchRef, XClk_Wiz::ClkOutOfRangeCallBack, XClk_Wiz::ClkOutOfRangeRef, XClk_Wiz::ClkStopCallBack, XClk_Wiz::ClkStopRef, XClk_Wiz::ErrorCallBack, XClk_Wiz::ErrRef, XClk_Wiz::IsReady.
Referenced by ClkWiz_IntrExample.
void XClk_Wiz_IntrHandler(void *InstancePtr)
This function is the interrupt handler for the CLK_WIZ core.
This handler reads the pending interrupt from the Interrupt Status register determines the source of the interrupts and calls the respective callbacks for the interrupts that are enabled in Interrupt Enable register and finally clears the interrupts.The application is responsible for connecting this function to the interrupt system. Application beyond this core is also responsible for providing callbacks to handle interrupts and installing the callbacks using XClk_Wiz_SetCallBack() during initialization phase. InstancePtr is a pointer to the XClk_Wiz core instance. None Interrupt should be enabled to execute interrupt handler.
References XClk_Wiz::ClkGlitchCallBack, XClk_Wiz::ClkGlitchRef, XClk_Wiz::ClkOutOfRangeCallBack, XClk_Wiz::ClkOutOfRangeRef, XClk_Wiz::ClkStopCallBack, XClk_Wiz::ClkStopRef, XClk_Wiz::IsReady, XClk_Wiz_InterruptClear, XClk_Wiz_InterruptGetStatus, XCLK_WIZ_ISR_CLKALL_GLITCH_MASK, XCLK_WIZ_ISR_CLKALL_MAXFREQ_MASK, XCLK_WIZ_ISR_CLKALL_MINFREQ_MASK, XCLK_WIZ_ISR_CLKALL_STOP_MASK.