xclk_wiz.h
XCLK_WIZ_HANDLER_CLK_OUTOF_RANGE
XCLK_WIZ_HANDLER_CLK_GLITCH
XCLK_WIZ_HANDLER_CLK_STOP
XCLK_WIZ_HANDLER_CLK_OTHER_ERROR
XCLK_M_MIN
XCLK_M_MAX
XCLK_D_MIN
XCLK_D_MAX
XCLK_VCO_MIN
XCLK_VCO_MAX
XCLK_O_MIN
XCLK_O_MAX
XCLK_US_VCO_MAX
XCLK_US_VCO_MIN
XCLK_US_M_MIN
XCLK_US_M_MAX
XCLK_US_D_MAX
XCLK_US_D_MIN
XCLK_US_O_MAX
XCLK_US_O_MIN
XCLK_MHZ
XCLK_KHZ
typedef void(* XClk_Wiz_CallBack)(void *CallBackRef, u32 Mask))(void *CallBackRef, u32 Mask)
Callback type for all interrupts defined.
CallBackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. Mask is a bit mask indicating the cause of the event. For current core version, this parameter is "OR" of 0 or more XCLK_WIZ_ISR_*_MASK constants defined in xclmon_hw.h. None None
static void XCLK_WIZ_BIT_SET(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask)
XCLK_WIZ_BIT_SET is used to set bit in a register.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitName is the part of the bitname before _MASK None None
static void XCLK_WIZ_BIT_RESET(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask)
XCLK_WIZ_BIT_RESET is used to reset bit in a register.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitName is the part of the bitname before _MASK None None
static u32 XCLK_WIZ_GET_BITFIELD_VALUE(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask, u32 BitShift)
XCLK_WIZ_GET_BITFIELD_VALUE is used to get the value of bitfield from register.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitName is the part of the bitname before _MASK or _SHIFT Bit Field Value in u32 format None
static void XCLK_WIZ_SET_BITFIELD_VALUE(UINTPTR BaseAddress, u32 RegisterOffset, u32 BitMask, u32 BitShift, u32 Value)
XCLK_WIZ_SET_BITFIELD_VALUE is used to set the value of bitfield from register.
BaseAddress is a base address of IP RegisterOffset is offset where the register is present BitName is the part of the bitname before _MASK or _SHIFT Value is to be set. Passed in u32 format. None None
static void XClk_Wiz_IntrEnable(XClk_Wiz *InstancePtr, u32 Mask)
XClk_Wiz_IntrEnable is used to set interrupt mask to enable interrupts.
This is done before enabling the core. InstancePtr is a pointer to the CLK_WIZ Instance to be worked on. Mask Interrupts to be enabled. None None
static u32 XClk_Wiz_GetIntrEnable(XClk_Wiz *InstancePtr)
XClk_Wiz_GetIntrEnable is used to find out which interrupts are registered for system.
InstancePtr is a pointer to the CLK_WIZ Instance to be worked on. Bit Mask in u32 format None
static void XClk_Wiz_IntrDisable(XClk_Wiz *InstancePtr, u32 Mask)
XClk_Wiz_IntrDisable is used to disable interrupts.
This is after disabling the core. InstancePtr is a pointer to the CLK_WIZ Instance to be worked on. Mask Interrupts to be disabled. None None
static u32 XClk_Wiz_IntrGetIrq(XClk_Wiz *InstancePtr)
XClk_Wiz_IntrGetIrq is used to find out which events have triggered the interrupt.
InstancePtr is a pointer to the CLK_WIZ Instance to be worked on. Bit Mask in u32 format. None
static void XClk_Wiz_IntrAckIrq(XClk_Wiz *InstancePtr, u32 Value)
XClk_Wiz_IntrAckIrq is acknowledge the events.
InstancePtr is a pointer to the CLK_WIZ Instance to be worked on. Value is Bit Mask for ack of interrupts. None None
XClk_Wiz_Config * XClk_Wiz_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XClk_Wiz_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xclk_wiz.h for the definition of XClk_Wiz_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XClk_Wiz_Config::Name.
Referenced by ClkWiz_Example, ClkWiz_IntrExample.
u32 XClk_Wiz_SetRate(XClk_Wiz *InstancePtr, u64 SetRate)
Change the frequency to the given rate.
InstancePtr is the XClk_Wiz instance to operate on. SetRate is the frequency for which is requested in MHz. XST_SUCCESS frequency setting was successful.XST_FAILURE frequency setting failed. Should be called only if there is only one output clock.
References XClk_Wiz::Config, XClk_Wiz::DVal, XClk_Wiz::IsReady, XClk_Wiz::MVal, XClk_Wiz_Config::NumClocks, XClk_Wiz::OVal.
u32 XClk_Wiz_SetRateHz(XClk_Wiz *InstancePtr, u64 SetRate)
Change the frequency to the given rate in Hz.
InstancePtr is the XClk_Wiz instance to operate on. SetRate is the frequency in Hz to be set. XST_SUCCESS Frequency setting was successful.XST_FAILURE frequency setting failed. Should be called only if there is only one output clock.
References XClk_Wiz::Config, XClk_Wiz::DVal, XClk_Wiz::IsReady, XClk_Wiz::MVal, XClk_Wiz_Config::NumClocks, XClk_Wiz::OVal, XCLK_WIZ_RECONFIG_OFFSET.
Referenced by ClkWiz_Example.
u32 XClk_Wiz_CfgInitialize(XClk_Wiz *InstancePtr, XClk_Wiz_Config *CfgPtr, UINTPTR EffectiveAddr)
Initialize the XClk_Wiz instance provided by the caller based on the given Config structure.
InstancePtr is the XClk_Wiz instance to operate on. CfgPtr is the device configuration structure containing information about a specific CLK_WIZ. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS Initialization was successful.XST_FAILURE Initialization was failure. None
References XClk_Wiz_Config::BaseAddr, XClk_Wiz::ClkGlitchCallBack, XClk_Wiz::ClkOutOfRangeCallBack, XClk_Wiz::ClkStopCallBack, XClk_Wiz::Config, XClk_Wiz::ErrorCallBack, XClk_Wiz_Config::IntId, XClk_Wiz_Config::IntrParent, XClk_Wiz::IsReady, XClk_Wiz::MinErr.
Referenced by ClkWiz_Example, ClkWiz_IntrExample.
void XClk_Wiz_GetInterruptSettings(XClk_Wiz *InstancePtr)
XClk_Wiz_GetInterruptSettings will get the information from clock wizard IER and ISR Registers.
InstancePtr is the XClk_Wiz instance to operate on. None
References XClk_Wiz::ClkIntrEnable, XClk_Wiz::ClkWizIntrStatus, XCLK_WIZ_IER_ALLINTR_MASK, XCLK_WIZ_IER_ALLINTR_SHIFT, XCLK_WIZ_IER_OFFSET, XCLK_WIZ_ISR_ALLINTR_MASK, XCLK_WIZ_ISR_ALLINTR_SHIFT, XCLK_WIZ_ISR_OFFSET.
int XClk_Wiz_SetCallBack(XClk_Wiz *InstancePtr, u32 HandleType, void *CallBackFunc, void *CallBackRef)
This routine installs an asynchronous callback function for the given HandlerType:
HandlerType Invoked by this driver when: ----------------------- -------------------------------------------------- XCLK_WIZ_HANDLER_CLK_OUTOF_RANGE Clock under flow/over flow XCLK_WIZ_HANDLER_CLK_GLITCH Clock Glitch XCLK_WIZ_HANDLER_CLK_STOP Clock Stop XCLK_WIZ_HANDLER_OTHERERROR Any other type of interrupts InstancePtr is the XClk_Wiz instance to operate on HandleType is the type of call back to be registered. CallBackFunc is the pointer to a call back function which is called when a particular event occurs. CallBackRef is a void pointer to data to be referenced to by the CallBackFunc XST_SUCCESS when handler is installed. XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XClk_Wiz::ClkGlitchCallBack, XClk_Wiz::ClkGlitchRef, XClk_Wiz::ClkOutOfRangeCallBack, XClk_Wiz::ClkOutOfRangeRef, XClk_Wiz::ClkStopCallBack, XClk_Wiz::ClkStopRef, XClk_Wiz::ErrorCallBack, XClk_Wiz::ErrRef, XClk_Wiz::IsReady.
Referenced by ClkWiz_IntrExample.
u32 XClk_Wiz_EnableClock(XClk_Wiz *InstancePtr, u32 ClockId)
Enable Clock for the given ClockId.
InstancePtr is the XClk_Wiz instance to operate on. ClockId is the output clock. XST_SUCCESS Initialization was successful.XST_FAILURE Initialization was failure.
References XClk_Wiz_Config::BaseAddr, XClk_Wiz::Config, XClk_Wiz::IsReady, XCLK_WIZ_REG3_USED.
u32 XClk_Wiz_DisableClock(XClk_Wiz *InstancePtr, u32 ClockId)
Disable Clock for the given ClockId.
InstancePtr is the XClk_Wiz instance to operate on. ClockId is the output clock. XST_SUCCESS Initialization was successful.XST_FAILURE Initialization was failure.
References XClk_Wiz_Config::BaseAddr, XClk_Wiz::Config, XClk_Wiz::IsReady, XCLK_WIZ_REG3_USED.
void XClk_Wiz_SetInputRate(XClk_Wiz *InstancePtr, double Rate)
Change the Input frequency to the given rate.
InstancePtr is the XClk_Wiz instance to operate on. Rate is the frequency for which is to be set. None Should be called only if the input provider clock is changed eg input clock is si570.
References XClk_Wiz::Config, XClk_Wiz::IsReady, XClk_Wiz_Config::Name, XClk_Wiz_Config::PrimInClkFreq.
u32 XClk_Wiz_WaitForLock(XClk_Wiz *InstancePtr)
Wait till the clocking wizard is locked to the frequency.
InstancePtr is the XClk_Wiz instance to operate on. XST_SUCCESS if lock was successful.XST_FAILURE on timeout.
References XClk_Wiz_Config::BaseAddr, XClk_Wiz::Config, XClk_Wiz::IsReady, XCLK_WIZ_STATUS_OFFSET.
Referenced by ClkWiz_Example.
s32 XClk_Wiz_GetRate(XClk_Wiz *InstancePtr, u32 ClockId, u64 *Rate)
Get the clock frequency for the given ClockId.
InstancePtr is the XClk_Wiz instance to operate on. ClockId is the output clock. Rate clock rate in Hz. XST_SUCCESS getting the frequency was successful.XST_FAILURE getting the frequency failed.
References XClk_Wiz::Config, XClk_Wiz_Config::NumClocks, XCLK_WIZ_REG3_PREDIV2.
Referenced by ClkWiz_Example.
u32 XClk_Wiz_GetInputRate(XClk_Wiz *InstancePtr)
Get the Input frequency.
InstancePtr is the XClk_Wiz instance to operate on. Clock frequency in KHz Should be called only if the input provider clock is changed eg input clock is si570.
References XClk_Wiz::Config, XClk_Wiz::IsReady, XClk_Wiz_Config::Name.
s32 XClk_Wiz_SetLeafRateHz(XClk_Wiz *InstancePtr, u32 ClockId, u64 SetRate)
Set the clock rate frequency for the given ClockId.
InstancePtr is the XClk_Wiz instance to operate on. ClockId is the output clock. SetRate clock rate in Hz. XST_SUCCESS Setting the rate was successful.XST_FAILURE Setting rate was failed.
References XClk_Wiz::IsReady, XClk_Wiz::OVal.
Referenced by ClkWiz_Example.
void XClk_Wiz_SetMinErr(XClk_Wiz *InstancePtr, u64 Minerr)
Set the Minimum error that can be tolerated.
InstancePtr is the XClk_Wiz instance to operate on. Minerr is the error margin that can be tolerated in Hz. None Should be called only if there is only one output clock.
References XClk_Wiz::IsReady, XClk_Wiz::MinErr.