/******************************************************************************
* Copyright (C) 2010-2022 Xilinx, Inc. All rights reserved.
* Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT
******************************************************************************/

/*****************************************************************************/
/**
*
* @file xcsiss_g.c
* @addtogroup csiss Overview
* @{
*
* This file contains the configuration table for the MIPI CSI Rx Subsystem.
* This table contains configuration information for each MIPI CSI Rx Subsystem
* instance in the system. This file is automatically generated and should not
* be manually edited.
*
* <pre>
* MODIFICATION HISTORY:
*
* Ver Who Date     Changes
* --- --- -------- -------------------------------------------------------
* 1.0 vsa 07/25/15 Initial release
* </pre>
*
******************************************************************************/

/***************************** Include Files *********************************/

#ifndef SDT
#include "xparameters.h"
#else
#include "xcsiss.h"
#endif

/************************** Constant Definitions *****************************/

#ifndef SDT
/**
 * @name Sub-core Presence Definitions
 * @{
 */
/**< List of Sub-cores included in the subsystem.
 * Sub-core device id will be set by its driver in xparameters.h.
 */

#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_MIPI_CSI2_RX_CTRL_0_PRESENT	1	/**< Indicates
						that the MIPI CSI2 RX Controller sub-core is present in
						subsystem instance 0 */
#define XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_MIPI_DPHY_0_PRESENT	1	/**< Indicates that
						the MIPI DPHY sub-core is present in subsystem instance 0 */
/*@}*/

/**
 * @name Sub-core Exclusion Notes
 * @{
 */
/**< List of Sub-cores excluded from the subsystem.
 *   - Excluded sub-core device id is set to 255.
 *   - Excluded sub-core baseaddr is set to 0.
 */
/*@}*/

/************************** Variable Definitions *****************************/

/**
 * @brief MIPI CSI Rx Subsystem configuration table
 *
 * This table contains configuration information for each MIPI CSI Rx Subsystem
 * instance in the system. Each entry describes the hardware configuration for
 * a specific instance including sub-core presence and parameters.
 */
XCsiSs_Config XCsiSs_ConfigTable[] =
{
	{
		XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_DEVICE_ID,
		XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_BASEADDR,
		XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_HIGHADDR,
		XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_CMN_NUM_LANES,
		XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_CMN_NUM_PIXELS,
		XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_CMN_PXL_FORMAT,
		XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_CMN_VC,
		XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_CSI_BUF_DEPTH,
		XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_CSI_EMB_NON_IMG,
		XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_DPY_EN_REG_IF,
		XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_DPY_LINE_RATE,
		XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_CSI_EN_CRC,
		XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_CSI_EN_ACTIVELANES,
		XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_EN_CSI_V2_0,
		XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_EN_VCX,
		{
			XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_MIPI_CSI2_RX_CTRL_0_PRESENT,
			XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_MIPI_CSI2_RX_CTRL_0_DEVICE_ID,
			XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_MIPI_CSI2_RX_CTRL_0_BASEADDR
		},
		{
			XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_MIPI_DPHY_0_PRESENT,
			XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_MIPI_DPHY_0_DEVICE_ID,
			XPAR_MIPI_CSI2_RX_SUBSYSTEM_0_MIPI_DPHY_0_BASEADDR
		},
	}
};

#else

/**
 * @brief MIPI CSI Rx Subsystem configuration table (SDT)
 *
 * This table contains configuration information for each MIPI CSI Rx Subsystem
 * instance in the system when using System Device Tree (SDT). Each entry
 * describes the hardware configuration for a specific instance including
 * sub-core presence and parameters.
 */
XCsiSs_Config XCsiSs_ConfigTable[] __attribute__ ((section (".drvcfg_sec"))) = {

	{
		"xlnx,mipi-csi2-rx-subsystem-5.4", /**< Compatible string */
		0x80000000, /**< Register base address */
		0x8000ffff, /**< High address */
		0x4, /**< Number of common lanes */
		0x2, /**< Number of common pixels */
		0x2b, /**< Common pixel format */
		0x10, /**< Common virtual channel */
		0x4096, /**< CSI buffer depth */
		0x0, /**< CSI embedded non-image data */
		0x1, /**< DPHY enable register interface */
		0x1440, /**< DPHY line rate */
		0x1, /**< CSI enable CRC */
		0x1, /**< CSI enable active lanes */
		0x0, /**< Enable CSI v2.0 */
		0x4, /**< DPHY lanes */
		0x1, /**< CSI RX present flag */
		0x00000000, /**< CSI RX connected address */
		0x1, /**< MIPI DPHY present flag */
		0xb0001000, /**< MIPI DPHY connected address */
		0x1, /**< RX PHY present flag */
		0xb0001000, /**< RX PHY connected address */
		0x405c, /**< Interrupts */
		0xf9010000 /**< Interrupt parent */
	},
	 {
		 NULL /**< Terminator entry */
	}
};

#endif
/** @} */
