xhdmi_example.c
AUX_FIFO_CLEAR
XHdmiphy1 Hdmiphy1
u8 Hdmiphy1ErrorFlag
u8 Hdmiphy1PllLayoutErrorFlag
XVfmc Vfmc[1][1]
XV_HdmiC_VrrInfoFrame VrrInforFrame
XIntc Intc
XHdmi_Menu HdmiMenu
XHdmi_Exdes xhdmi_exdes_ctrlr
Exdes_Debug_Printf exdes_debug_print
Exdes_Debug_Printf exdes_aux_debug_print
Exdes_Debug_Printf exdes_hdcp_debug_print
int I2cMux(void)
int I2cClk(u32 InFreq, u32 OutFreq)
This function setup SI5324 clock generator either in free or locked mode.
Index specifies an index for selecting mode frequency. Mode specifies either free or locked mode. Zero if error in programming external clock.One if programmed external clock. None.
References I2C_CLK_ADDR, I2C_CLK_ADDR1, IDT_8T49N24x_I2cClk.
Referenced by main.
void Info(void)
This function outputs the video timing , Audio, Link Status, HDMI RX state of HDMI RX core.
In addition, it also prints information about HDMI TX, and HDMI GT cores. None. None. None.
References XV_HdmiRxSs1::EnableHDCPLogging, XV_HdmiRxSs1_ReportAudio, XV_HdmiRxSs1_ReportDRMInfo, XV_HdmiRxSs1_ReportLinkQuality, XV_HdmiRxSs1_ReportTiming.
void DetailedInfo(void)
This function prints additional details of the system for debug purpose.
None. None. None.
References XV_HdmiRxSs1::HdmiRx1Ptr, XV_HdmiRxSs1_DebugInfo, XV_HdmiRxSs1_ReportCoreInfo, XV_HdmiRxSs1_ReportSubcoreVersion.
void Hdmiphy1ErrorCallback(void *CallbackRef)
This function is called whenever an error condition in VPHY occurs.
This will fill the FIFO of VPHY error events which will be processed outside the ISR. CallbackRef is the VPHY instance pointer ErrIrqType is the VPHY error type None. None.
Referenced by main.
void Hdmiphy1ProcessError(void)
This function is called in the application to process the pending VPHY errors.
None. None. This function can be expanded to perform necessary actions depending on the error type. For example, XHDMIPHY1_ERR_PLL_LAYOUT can be used to automatically switch in and out of bonded mode for GTXE2 devices
References ANSI_COLOR_RED.
Referenced by main.
u32 Exdes_LoadHdcpKeys(void *IicPtr)
u32 Exdes_SysTmrInitialize(XHdmi_Exdes *InstancePtr, u32 TmrBaseAddr)
This function is used to initialize the system timer that is used to count and generate given periodic interrupts.
InstancePtr is a pointer to the example design handler TmrId is the device id of the system timer TmrIntrId is the interrupt vector id of the system timer XST_SUCCESS if successful. None.
References Exdes_SysTimerIntrHandler, XHdmi_Exdes::SysTmrInst.
Referenced by main.
u32 Exdes_UsToTicks(u32 TimeInUs, u32 TmrCtrClkFreq)
This function time specified in Us to ticks for a specified timer frequency.
TimeInUs is the time in microseconds. TmrCtrClkFreq is the frequency of the clock to be used for counting the ticks. Number of ticks. None.
Referenced by Exdes_StartSysTmr.
void Exdes_StartSysTmr(XHdmi_Exdes *InstancePtr, u32 IntervalInMs)
This function is used to start a the timer to generate periodic pulses of tmrctr interrupt.
InstancePtr is a pointer to the example design handler. IntervalInMs is the user specified period for the timer pulses. None. None.
References Exdes_SysTmrCallback, Exdes_UsToTicks, XHdmi_Exdes::SysTmrInst, XHdmi_Exdes::SysTmrPulseIntervalinMs.
Referenced by main.
void Exdes_SysTmrCallback(void *CallbackRef, u8 TmrCtrNumber)
This function is set as the callback handler from the timer counter interrupt handler.
The counters that are used in the application for timer based control and exclusion are be handled in the this function.The user needs to modify this callback to set the counters and exclusion flags based on the pulse counts in the pulse train generated by the system timer. CallbackRef is the function callback reference. TmrCtrNumber is the timer counter number. None. None.
Referenced by Exdes_StartSysTmr.
void Exdes_SysTimerIntrHandler(void *CallbackRef)
This function is set as the callback handler from the interrupt controller for the system timer interrupts.
InstancePtr is the callback reference. None. None.
References XHdmi_Exdes::SysTmrInst.
Referenced by Exdes_SysTmrInitialize.
u8 Exdes_LookupVic(XVidC_VideoMode VideoMode)
void Exdes_SetDebugPrintf(Exdes_Debug_Printf PrintFunc)
This function is used to enable and additional debugging prints in the application.
Printfunc is the function to enable printing. None.
Referenced by Exdes_InitController.
void Exdes_SetAuxFifoDebugPrintf(Exdes_Debug_Printf PrintFunc)
This function is used to enable and additional debugging prints for the Aux Fifo operations in the application.
Printfunc is the function to enable printing. None.
Referenced by Exdes_InitController.
void Exdes_SetHdcpDebugPrintf(Exdes_Debug_Printf PrintFunc)
This function is used to enable and additional debugging prints for the HDCP operations in the application.
Printfunc is the function to enable printing. None.
Referenced by Exdes_InitController.
void Exdes_InitController(XHdmi_Exdes *InstancePtr)
This function is used to initialize the example design controller data structure that is used to track the presence and instances of the hdmi 2.1 receiver and transmitter.
InstancePtr is the instance of the example design handle data structure. None.
References Exdes_SetAuxFifoDebugPrintf, Exdes_SetDebugPrintf, Exdes_SetHdcpDebugPrintf, XHdmi_Exdes::IsRxPresent, XHdmi_Exdes::IsTxPresent, XHdmi_Exdes::SystemEvent, XHdmi_Exdes::TxStartTransmit.
Referenced by main.
void Exdes_UpdateAuxFifo()
This function updates the global array for AUX fifo with the AUX data from the hdmi receiver.
None. None.
References XV_HdmiRxSs1_GetAuxiliary.
void Exdes_ReadVRRTimingChange()
This function updates the Reads the VRR Video Timing Values from HDMI RX Receiver.
None. None.
void Exdes_ProcessVRRTimingChange()
This function updates the Reads the VRR Video Timing Values from HDMI RX Receiver and updates to HDMI TX when VRR Manual Mode is enabled.
None. None.
References XV_HdmiRxSs1_GetVideoStream.
Referenced by Exdes_ProcessVTEMPacket, main.
void Exdes_VTEMPToSPDIFConversion()
void Exdes_ReadVTEMPacket()
This function updates the Reads the VRR VTEM Packet from HDMI RX Receiver.
None. None.
References XV_HdmiRxSs1_GetVrrIf.
void Exdes_ProcessVTEMPacket()
This function updates the R Reads the VRR VTEM Packet from HDMI RX Receiver and updates to HDMI TX.
None. None.
References Exdes_ProcessVRRTimingChange, XV_HdmiRxSs1_GetVrrIf.
u32 Exdes_CheckforResChange()
This function checks if there has been a change in resolution on the incoming rx stream.
None. None.
References XV_HdmiRxSs1::IsStreamConnected, XHdmi_Exdes::TxStartTransmit, XV_HdmiRxSs1_VRST.
int I2cMuxSel(void *IicPtr, XOnBoard_IicDev Dev)
This function setup sets up the On Board IIC MUX to select device.
None. The number of bytes sent. None.
Referenced by Exdes_SetupClkSrc.
void Xil_AssertCallbackRoutine(u8 *File, s32 Line)
This is the callback for assertion error.
File is string name of the file where the assertion failure occurred. LIne is the line wheer the assertion failure occurred. None. None.
Referenced by main.
u32 Exdes_SetupClkSrc(u32 ps_iic0_baseaddr, u32 ps_iic1_baseaddr)
This function updates the FrameRate for the current video stream.
ps_iic0_deviceid is the device id of the ps iic device. ps_iic1_deviceid is the device id of the ps iic device. XST_SUCCESS if the clock source is successfully set. XST_FAILURE otherwise. None.
References I2cMuxSel, RC21008A_ADDR, Si570_SetFreq.
Referenced by main.
int SetupInterruptSystem(void)
This function setups the interrupt system so interrupts can occur for the HDMI cores.
The function is application-specific since the actual system may or may not have an interrupt controller. The HDMI cores could be directly connected to a processor without an interrupt controller. The user should modify this function to fit the application. None. XST_SUCCESS if interrupt setup was successful.A specific error code defined in "xstatus.h" if an error occurs. This function assumes a Microblaze system and no operating system is used.
Referenced by main.
int main()
Main function to call example with HDMI TX, HDMI RX and HDMI GT drivers.
None. XST_SUCCESS if HDMI example was successfully.XST_FAILURE if HDMI example failed. None.
References Exdes_InitController, Exdes_ProcessVRRTimingChange, Exdes_SetupClkSrc, Exdes_StartSysTmr, Exdes_SysTmrInitialize, XHdmi_Exdes::ForceIndependent, Hdmiphy1ErrorCallback, Hdmiphy1ProcessError, I2cClk, XVfmc::IicPtr, XHdmi_Exdes::IsRxPresent, XHdmi_Exdes::IsTxPresent, XVfmc::Loc, SetupInterruptSystem, XHdmi_Exdes::SystemEvent, XHdmi_Exdes::TxBusy, XHdmi_Exdes::TxStartTransmit, XHdmi_MenuInitialize, XHdmi_MenuProcess, Xil_AssertCallbackRoutine, XV_HdmiRxSs1_DynHDR_SetAddr, XV_HdmiRxSs1_GetVideoStream, XV_HdmiRxSs1_GetVrrIf, XV_HdmiRxSs1_Start.