xv_hdmirxss1.c
XV_HdmiRxSs1_BridgeYuv420
This macro selects the bridge YUV420 mode.
InstancePtr is a pointer to the HDMI RX Subsystem Enable enables or disables YUV420 mode
XV_HdmiRxSs1_BridgePixelDrop
This macros selects the bridge pixel repeat mode.
InstancePtr is a pointer to the HDMI RX Subsystem Enable enables or disables pixel drop mode
XV_HdmiRxSs1_SubCores XV_HdmiRxSs1_SubCoreRepo[XPAR_XV_HDMIRXSS1_NUM_INSTANCES][XPAR_XV_HDMIRXSS1_NUM_INSTANCES]
Define Driver instance of all sub-core included in the design.
static void XV_HdmiRxSs1_GetIncludedSubcores(XV_HdmiRxSs1 *HdmiRxSs1Ptr, UINTPTR BaseAddress)
This function queries the subsystem instance configuration to determine the included sub-cores.
For each sub-core that is present in the design the sub-core driver instance is binded with the subsystem sub-core driver handle HdmiRxSs1Ptr is a pointer to the Subsystem instance to be worked on. DevId specifies device instance number None
static void XV_HdmiRxSs1_WaitUs(XV_HdmiRxSs1 *InstancePtr, u32 MicroSeconds)
This function is the delay/sleep function for the XV_HdmiRxSs1 driver.
For the Zynq family, there exists native sleep functionality. For MicroBlaze however, there does not exist such functionality. In the MicroBlaze case, the default method for delaying is to use a predetermined amount of loop iterations. This method is prone to inaccuracy and dependent on system configuration; for greater accuracy, the user may supply their own delay/sleep handler, pointed to by InstancePtr->UserTimerWaitUs, which may have better accuracy if a hardware timer is used. InstancePtr is a pointer to the HdmiSsRx instance. MicroSeconds is the number of microseconds to delay/sleep for. None. None.
static void XV_HdmiRxSs1_RetrieveVSInfoframe(XV_HdmiRxSs1 *HdmiRxSs1)
This function retrieves the Vendor Specific Info Frame.
None. None. None.
static int XV_HdmiRxSs1_RegisterSubsysCallbacks(XV_HdmiRxSs1 *InstancePtr)
This function register's all sub-core ISR's with interrupt controller and any subsystem level call back function with requisite sub-core.
InstancePtr is a pointer to the Subsystem instance to be worked on. None. None.
static void XV_HdmiRxSs1_ConnectCallback(void *CallbackRef)
This function is called when a RX connect event has occurred.
None. None. None.
static void XV_HdmiRxSs1_BrdgOverflowCallback(void *CallbackRef)
This function is called when a Bridge overflow event has occurred.
None. None. None.
static void XV_HdmiRxSs1_AuxCallback(void *CallbackRef)
This function is called when a RX AUX IRQ has occurred.
None. None. None.
static void XV_HdmiRxSs1_AudCallback(void *CallbackRef)
This function is called when a RX Audio IRQ has occurred.
None. None. None.
static void XV_HdmiRxSs1_LnkStaCallback(void *CallbackRef)
This function is called when a RX Link Status IRQ has occurred.
None. None. None.
static void XV_HdmiRxSs1_DdcCallback(void *CallbackRef)
This function is called when a RX DDC IRQ has occurred.
None. None. None.
static void XV_HdmiRxSs1_StreamDownCallback(void *CallbackRef)
This function is called when the RX stream is down.
None. None. None.
static void XV_HdmiRxSs1_StreamInitCallback(void *CallbackRef)
This function is called when the RX stream init .
None. None. None.
static void XV_HdmiRxSs1_StreamUpCallback(void *CallbackRef)
This function is called when the RX stream is up.
None. None. None.
static void XV_HdmiRxSs1_SyncLossCallback(void *CallbackRef)
This function is called when a RX Sync Loss IRQ has occurred.
None. None. None.
static void XV_HdmiRxSs1_ModeCallback(void *CallbackRef)
This function is called when the mode has transitioned from DVI to HDMI or vice versa.
None. None. None.
static void XV_HdmiRxSs1_TmdsClkRatioCallback(void *CallbackRef)
This function is called when the TMDS CLK ratio changes.
None. None. None.
static void XV_HdmiRxSs1_PhyResetCallback(void *CallbackRef)
This function is called when the RX Phy needs to be reset.
None. None. None.
static void XV_HdmiRxSs1_VicErrorCallback(void *CallbackRef)
This function is called when the Vic does not match with the detected video timing.
None. None. None.
static void XV_HdmiRxSs1_LnkRdyErrorCallback(void *CallbackRef)
This function is called when the Link Ready error happens.
None. None. None.
static void XV_HdmiRxSs1_VidRdyErrorCallback(void *CallbackRef)
This function is called when the Video Ready error happens.
None. None. None.
static void XV_HdmiRxSs1_SkewLockErrorCallback(void *CallbackRef)
This function is called when the Skew Lock error happens.
None. None. None.
static void XV_HdmiRxSs1_VfpChanged(void *CallbackRef)
static void XV_HdmiRxSs1_VrrReady(void *CallbackRef)
static void XV_HdmiRxSs1_DynHdrEvtCallback(void *CallbackRef)
static void XV_HdmiRxSs1_DSCStreamChngCallback(void *CallbackRef)
This function is called internally to handle DSC stream change events.
It logs the event if logging is enabled and then invokes the user-registered DSC stream change event callback, if one is set. CallbackRef Pointer to the HDMI RX Subsystem instance (XV_HdmiRxSs1 *). The user must register a callback function using the appropriate API to receive DSC stream change notifications.
static void XV_HdmiRxSs1_DSCPktErrCallback(void *CallbackRef)
This function logs the DSC packet error event if logging is enabled, and then calls the user-registered DSC packet error callback, if it is set.
CallbackRef Pointer to the XV_HdmiRxSs1 instance passed as callback reference. This function is intended for internal use by the HDMI RX Subsystem driver.
static void XV_HdmiRxSs1_DSCStatusUpdateCallback(void *CallbackRef)
This function is invoked when a DSC status update event occurs.
It logs the event if logging is enabled and then calls the registered DSC status update event callback, if one is set. CallbackRef Pointer to the HDMI RX Subsystem instance (XV_HdmiRxSs1). This function is intended for internal use within the HDMI RX Subsystem driver.
static void XV_HdmiRxSs1_ConfigBridgeMode(XV_HdmiRxSs1 *InstancePtr)
This function configures the Bridge for YUV420 functionality and repeater.
InstancePtr pointer to XV_HdmiRxSs1 instance None None
void XV_HdmiRxSs1_ReportInfo(XV_HdmiRxSs1 *InstancePtr)
This function prints detailed information about the HDMI RX Subsystem, including core info, timing, link quality, audio, HDR metadata, and InfoFrames.
Report subsystem info. InstancePtr Instance Pointer to the main data structure None. None.
References XV_HdmiRxSs1_ReportAudio, XV_HdmiRxSs1_ReportCoreInfo, XV_HdmiRxSs1_ReportDRMInfo, XV_HdmiRxSs1_ReportInfoFrame, XV_HdmiRxSs1_ReportLinkQuality, XV_HdmiRxSs1_ReportSubcoreVersion, XV_HdmiRxSs1_ReportTiming.
void XV_HdmiRxSs1_RegisterDebug(XV_HdmiRxSs1 *InstancePtr)
This function prints out the sub-core register dump.
Display register contents. InstancePtr Instance pointer to the main data structure. None. None.
References XV_HdmiRxSs1::HdmiRx1Ptr.
void XV_HdmiRxSs1_ReportCoreInfo(XV_HdmiRxSs1 *InstancePtr)
This function reports the list of cores included in the HDMI RX Subsystem.
Report core info. InstancePtr is a pointer to the HDMI RX Subsystem instance. None None.
References XV_HdmiRxSs1::HdmiRx1Ptr.
Referenced by DetailedInfo, XV_HdmiRxSs1_ReportInfo.
void XV_HdmiRxSs1_SetUserTimerHandler(XV_HdmiRxSs1 *InstancePtr, XVidC_DelayHandler CallbackFunc, void *CallbackRef)
This function allows the user to specify a custom delay or sleep function, which will be invoked by the driver when a delay is required.
Set user timer handler. InstancePtr is a pointer to the XV_HdmiRxSs1 instance. CallbackFunc is the address of the custom delay/sleep callback function. CallbackRef is the user data (e.g., microseconds to delay) that will be passed to the callback function. None None
References XV_HdmiRxSs1::UserTimerPtr, XV_HdmiRxSs1::UserTimerWaitUs.
void XV_HdmiRxSS1_HdmiRxIntrHandler(XV_HdmiRxSs1 *InstancePtr)
This function calls the interrupt handler for HDMI RX.
HDMI RX interrupt handler. InstancePtr is a pointer to the HDMI RX Subsystem None. None.
References XV_HdmiRxSs1::HdmiRx1Ptr.
int XV_HdmiRxSs1_CfgInitialize(XV_HdmiRxSs1 *InstancePtr, XV_HdmiRxSs1_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the video subsystem and included sub-cores.
Initialize subsystem.This function must be called prior to using the subsystem. Initialization includes setting up the instance data for top level as well as all included sub-core therein, and ensuring the hardware is in a known stable state. InstancePtr is a pointer to the Subsystem instance to be worked on. CfgPtr points to the configuration structure associated with the subsystem instance. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if initialization is successful else XST_FAILURE
References XV_HdmiRxSs1::AppMajVer, XV_HdmiRxSs1::AppMinVer, XV_HdmiRxSs1_Config::AxiLiteClkFreq, XV_HdmiRxSs1_Config::BaseAddress, XV_HdmiRxSs1::Config, XV_HdmiRxSs1_Config::DSC, XV_HdmiRxSs1::EnableHDCPLogging, XV_HdmiRxSs1::EnableHDMILogging, XV_HdmiRxSs1::HdmiRx1Ptr, XV_HdmiRxSs1::IsReady, XV_HdmiRxSs1_GetDrmInfoframe, XV_HDMIRXSS1_HDCP_14, XV_HDMIRXSS1_HDCP_22, XV_HDMIRXSS1_HDCP_NOUSERPREF, XV_HdmiRxSs1_Reset, XV_HdmiRxSs1_SubcoreInitHdmiRx1.
void XV_HdmiRxSs1_Start(XV_HdmiRxSs1 *InstancePtr)
This function starts the HDMI RX subsystem including all sub-cores that are included in the processing pipeline for a given use-case.
Start subsystem.Video pipe is started from back to front InstancePtr is a pointer to the Subsystem instance to be worked on. None Cores are started only if the corresponding start flag in the scratch pad memory is set. This allows to selectively start only those cores included in the processing chain
References XV_HdmiRxSs1::HdmiRx1Ptr, XV_HDMIRXSS1_LOG_EVT_START, XV_HdmiRxSs1_LogWrite.
Referenced by main.
void XV_HdmiRxSs1_Stop(XV_HdmiRxSs1 *InstancePtr)
This function stops the HDMI RX subsystem including all sub-cores.
Stop subsystem.Stop the video pipe starting from front to back. InstancePtr is a pointer to the Subsystem instance to be worked on. None.
References XV_HdmiRxSs1::HdmiRx1Ptr, XV_HDMIRXSS1_LOG_EVT_STOP, XV_HdmiRxSs1_LogWrite.
void XV_HdmiRxSs1_Reset(XV_HdmiRxSs1 *InstancePtr)
This function resets the video subsystem sub-cores.
Reset subsystem.There are 2 reset networks within the subsystem For cores that are on AXIS interfaceFor cores that are on AXI-MM interface InstancePtr is a pointer to the Subsystem instance to be worked on. None
References XV_HDMIRXSS1_LOG_EVT_RESET, XV_HdmiRxSs1_LogWrite, XV_HdmiRxSs1_RXCore_LRST, XV_HdmiRxSs1_RXCore_VRST, XV_HdmiRxSs1_SYSRST.
Referenced by XV_HdmiRxSs1_CfgInitialize.
void XV_HdmiRxSs1_RXCore_VRST(XV_HdmiRxSs1 *InstancePtr, u8 Reset)
This function controls the internal video reset signal for the HDMI subcore inside the subsystem.
RX core video reset - TRUE to assert, FALSE to release.It can either assert (activate) or release (deactivate) the reset based on the value of the Reset parameter. InstancePtr is a pointer to the Subsystem instance to be worked on. Reset is the value indicating whether to assert (non-zero) or release (zero) the reset. None
References XV_HdmiRxSs1::HdmiRx1Ptr.
Referenced by XV_HdmiRxSs1_Reset.
void XV_HdmiRxSs1_RXCore_LRST(XV_HdmiRxSs1 *InstancePtr, u8 Reset)
This function asserts or releases the Internal Link reset of the HDMI subcore within the subsystem.
RX core link reset - TRUE to assert, FALSE to release. InstancePtr is a pointer to the Subsystem instance to be worked on. Reset specifies TRUE/FALSE value to either assert or release reset. None
References XV_HdmiRxSs1::HdmiRx1Ptr.
Referenced by XV_HdmiRxSs1_Reset.
void XV_HdmiRxSs1_VRST(XV_HdmiRxSs1 *InstancePtr, u8 Reset)
This function asserts or releases the video reset of other blocks within the subsystem.
Video reset - TRUE to assert, FALSE to release. InstancePtr is a pointer to the Subsystem instance to be worked on. Reset specifies TRUE/FALSE value to either assert or release reset. None
References XV_HdmiRxSs1::HdmiRx1Ptr.
Referenced by Exdes_CheckforResChange.
void XV_HdmiRxSs1_SYSRST(XV_HdmiRxSs1 *InstancePtr, u8 Reset)
This function asserts or releases the system reset of other blocks within the subsystem.
System reset - TRUE to assert, FALSE to release. InstancePtr is a pointer to the Subsystem instance to be worked on. Reset is the value indicating whether to assert (non-zero) or release (zero) the reset. None
References XV_HdmiRxSs1::HdmiRx1Ptr.
Referenced by XV_HdmiRxSs1_Reset.
int XV_HdmiRxSs1_SetCallback(XV_HdmiRxSs1 *InstancePtr, XV_HdmiRxSs1_HandlerType HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs an asynchronous callback function for the given HandlerType:
Set event callback. HandlerType Callback Function Type ----------------------- --------------------------------------------- (XV_HDMIRXSS1_HANDLER_CONNECT) HpdCallback (XV_HDMIRXSS1_HANDLER_VS) VsCallback (XV_HDMIRXSS1_HANDLER_STREAM_DOWN) StreamDownCallback (XV_HDMIRXSS1_HANDLER_STREAM_UP) StreamUpCallback (XV_HDMIRXSS1_HANDLER_HDCP_AUTHENTICATED) HdcpAuthenticatedCallback (XV_HDMIRXSS1_HANDLER_HDCP_UNAUTHENTICATED) HdcpUnauthenticatedCallback (XV_HDMIRXSS1_HANDLER_HDCP_AUTHENTICATION_REQUEST) HdcpAuthenticationRequestCallback (XV_HDMIRXSS1_HANDLER_HDCP_STREAM_MANAGE_REQUEST) HdcpStreamManageRequestCallback (XV_HDMIRXSS1_HANDLER_HDCP_TOPOLOGY_UPDATE) HdcpTopologyUpdateCallback InstancePtr is a pointer to the HDMI RX Subsystem instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XV_HdmiRxSs1::AudCallback, XV_HdmiRxSs1::AudRef, XV_HdmiRxSs1::AuxCallback, XV_HdmiRxSs1::AuxRef, XV_HdmiRxSs1::BrdgOverflowCallback, XV_HdmiRxSs1::BrdgOverflowRef, XV_HdmiRxSs1::ConnectCallback, XV_HdmiRxSs1::ConnectRef, XV_HdmiRxSs1::DdcCallback, XV_HdmiRxSs1::DdcRef, XV_HdmiRxSs1::DSCPktErrCallback, XV_HdmiRxSs1::DSCStreamChangeEventCallback, XV_HdmiRxSs1::DSCStrmChgEvtRef, XV_HdmiRxSs1::DSCStsUpdtEvtCallback, XV_HdmiRxSs1::DSCStsUpdtEvtRef, XV_HdmiRxSs1::DynHdrCallback, XV_HdmiRxSs1::DynHdrRef, XV_HdmiRxSs1::FrlConfigCallback, XV_HdmiRxSs1::FrlConfigRef, XV_HdmiRxSs1::FrlStartCallback, XV_HdmiRxSs1::FrlStartRef, XV_HdmiRxSs1::HdcpCallback, XV_HdmiRxSs1::HdcpRef, XV_HdmiRxSs1::LnkStaCallback, XV_HdmiRxSs1::LnkStaRef, XV_HdmiRxSs1::PhyResetCallback, XV_HdmiRxSs1::PhyResetRef, XV_HdmiRxSs1::StreamDownCallback, XV_HdmiRxSs1::StreamDownRef, XV_HdmiRxSs1::StreamInitCallback, XV_HdmiRxSs1::StreamInitRef, XV_HdmiRxSs1::StreamUpCallback, XV_HdmiRxSs1::StreamUpRef, XV_HdmiRxSs1::TmdsClkRatioCallback, XV_HdmiRxSs1::TmdsClkRatioRef, XV_HdmiRxSs1::TmdsConfigCallback, XV_HdmiRxSs1::TmdsConfigRef, XV_HdmiRxSs1::VfpChangeCallback, XV_HdmiRxSs1::VfpChangeRef, XV_HdmiRxSs1::VicErrorCallback, XV_HdmiRxSs1::VicErrorRef, XV_HdmiRxSs1::VidRdyErrorCallback, XV_HdmiRxSs1::VidRdyErrorRef, XV_HdmiRxSs1::VrrRdyCallback, XV_HdmiRxSs1::VrrRdyRef, XV_HDMIRXSS1_HANDLER_AUD, XV_HDMIRXSS1_HANDLER_AUX, XV_HDMIRXSS1_HANDLER_BRDGOVERFLOW, XV_HDMIRXSS1_HANDLER_CONNECT, XV_HDMIRXSS1_HANDLER_DDC, XV_HDMIRXSS1_HANDLER_DSC_PKT_ERR, XV_HDMIRXSS1_HANDLER_DSC_STRM_CH, XV_HDMIRXSS1_HANDLER_DSC_STS_UPDT, XV_HDMIRXSS1_HANDLER_DYN_HDR, XV_HDMIRXSS1_HANDLER_FRL_CONFIG, XV_HDMIRXSS1_HANDLER_FRL_START, XV_HDMIRXSS1_HANDLER_HDCP, XV_HDMIRXSS1_HANDLER_HDCP_AUTHENTICATED, XV_HDMIRXSS1_HANDLER_HDCP_AUTHENTICATION_REQUEST, XV_HDMIRXSS1_HANDLER_HDCP_ENCRYPTION_UPDATE, XV_HDMIRXSS1_HANDLER_HDCP_STREAM_MANAGE_REQUEST, XV_HDMIRXSS1_HANDLER_HDCP_TOPOLOGY_UPDATE, XV_HDMIRXSS1_HANDLER_HDCP_UNAUTHENTICATED, XV_HDMIRXSS1_HANDLER_LNKSTA, XV_HDMIRXSS1_HANDLER_PHY_RESET, XV_HDMIRXSS1_HANDLER_STREAM_DOWN, XV_HDMIRXSS1_HANDLER_STREAM_INIT, XV_HDMIRXSS1_HANDLER_STREAM_UP, XV_HDMIRXSS1_HANDLER_TMDS_CLK_RATIO, XV_HDMIRXSS1_HANDLER_TMDS_CONFIG, XV_HDMIRXSS1_HANDLER_VFP_CH, XV_HDMIRXSS1_HANDLER_VIC_ERROR, XV_HDMIRXSS1_HANDLER_VID_RDY_ERR, XV_HDMIRXSS1_HANDLER_VRR_RDY.
int XV_HdmiRxSs1_SetLogCallback(XV_HdmiRxSs1 *InstancePtr, u64 *CallbackFunc, void *CallbackRef)
This function installs an asynchronous callback function for the LogWrite API:
InstancePtr is a pointer to the HDMI RX Subsystem instance. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when callback function is not installed successfully.
References XV_HdmiRxSs1::LogWriteCallback, XV_HdmiRxSs1::LogWriteRef.
void XV_HdmiRxSs1_SetEdidParam(XV_HdmiRxSs1 *InstancePtr, u8 *EdidDataPtr, u16 Length)
This function Sets the EDID parameters in the HDMI RX SS struct.
InstancePtr is a pointer to the HDMI RX Subsystem instance. EdidDataPtr is a pointer to EDID data Length specifies the length of EDID data None. None.
References XV_HdmiRxSs1::EdidLength, XV_HdmiRxSs1::EdidPtr.
void XV_HdmiRxSs1_LoadDefaultEdid(XV_HdmiRxSs1 *InstancePtr)
This function loads the default EDID to the HDMI RX.
InstancePtr is a pointer to the HDMI RX Subsystem instance. None. None.
References XV_HdmiRxSs1::EdidLength, XV_HdmiRxSs1::EdidPtr, XV_HdmiRxSs1::HdmiRx1Ptr.
void XV_HdmiRxSs1_LoadEdid(XV_HdmiRxSs1 *InstancePtr, u8 *EdidDataPtr, u16 Length)
This function loads the default EDID to the HDMI RX.
InstancePtr is a pointer to the HDMI RX Subsystem instance. EdidDataPtr is a pointer to EDID data Length specifies the length of EDID data None. None.
References XV_HdmiRxSs1::HdmiRx1Ptr.
void XV_HdmiRxSs1_SetHpd(XV_HdmiRxSs1 *InstancePtr, u8 Value)
This function sets the HPD on the HDMI RX.
InstancePtr is a pointer to the HDMI RX Subsystem instance. Value is a flag used to set the HPD. TRUE drives HPD highFALSE drives HPD low None. None.
References XV_HdmiRxSs1::HdmiRx1Ptr.
void XV_HdmiRxSs1_ToggleHpd(XV_HdmiRxSs1 *InstancePtr)
This function toggles the HPD on the HDMI RX.
InstancePtr is a pointer to the HDMI RX Subsystem instance. None. None.
References XV_HdmiRxSs1::HdmiRx1Ptr.
XHdmiC_Aux* XV_HdmiRxSs1_GetAuxiliary(XV_HdmiRxSs1 *InstancePtr)
This function returns the pointer to HDMI RX SS Aux structure.
InstancePtr pointer to XV_HdmiRxSs1 instance XHdmiC_Aux pointer None.
References XV_HdmiRxSs1::HdmiRx1Ptr.
Referenced by Exdes_UpdateAuxFifo.
XHdmiC_AVI_InfoFrame* XV_HdmiRxSs1_GetAviInfoframe(XV_HdmiRxSs1 *InstancePtr)
This function returns the pointer to HDMI RX SS AVI InfoFrame structure.
InstancePtr pointer to XV_HdmiRXSs instance XHdmiC_AVI_InfoFrame pointer None.
References XV_HdmiRxSs1::AVIInfoframe.
XHdmiC_GeneralControlPacket* XV_HdmiRxSs1_GetGCP(XV_HdmiRxSs1 *InstancePtr)
This function returns the pointer to HDMI RX SS General Control Packet structure.
InstancePtr pointer to XV_HdmiRXSs instance XHdmiC_GeneralControlPacket pointer None.
References XV_HdmiRxSs1::GCP.
XHdmiC_AudioInfoFrame* XV_HdmiRxSs1_GetAudioInfoframe(XV_HdmiRxSs1 *InstancePtr)
This function returns the pointer to HDMI RX SS Audio InfoFrame structure.
InstancePtr pointer to XV_HdmiRXSs instance XHdmiC_AudioInfoFrame pointer None.
References XV_HdmiRxSs1::AudioInfoframe.
XHdmiC_DRMInfoFrame* XV_HdmiRxSs1_GetDrmInfoframe(XV_HdmiRxSs1 *InstancePtr)
This function returns the pointer to HDMI 2.1 RX SS DRM InfoFrame structure.
InstancePtr pointer to XV_HdmiRxSs1 instance XHdmiC_DRMInfoFrame pointer None.
References XV_HdmiRxSs1::DrmInfoframe.
Referenced by XV_HdmiRxSs1_CfgInitialize, XV_HdmiRxSs1_ReportDRMInfo.
XHdmiC_VSIF* XV_HdmiRxSs1_GetVSIF(XV_HdmiRxSs1 *InstancePtr)
This function returns the pointer to HDMI RX SS Vendor Specific InfoFrame structure.
InstancePtr pointer to XV_HdmiRxSs1 instance XHdmiC_VSIF pointer None.
References XV_HdmiRxSs1::VSIF.
u32 XV_HdmiRxSs1_SetStream(XV_HdmiRxSs1 *InstancePtr, u32 Clock, u32 LineRate)
This function set HDMI RX subsystem stream parameters.
InstancePtr pointer to XV_HdmiRxSs1 instance Clock specifies reference pixel clock frequency. LineRate specifies FRL linerate Calculated TMDS Clock None.
References XV_HdmiRxSs1::Config, XV_HdmiRxSs1::HdmiRx1Ptr, XV_HdmiRxSs1_Config::Ppc, XV_HDMIRXSS1_LOG_EVT_SETSTREAM, XV_HDMIRXSS1_LOG_EVT_SETSTREAM_ERR, XV_HdmiRxSs1_LogWrite.
XVidC_VideoStream* XV_HdmiRxSs1_GetVideoStream(XV_HdmiRxSs1 *InstancePtr)
This function returns the pointer to HDMI RX SS video stream.
InstancePtr pointer to XV_HdmiRxSs1 instance XVidC_VideoStream pointer None.
References XV_HdmiRxSs1::HdmiRx1Ptr.
Referenced by Exdes_ProcessVRRTimingChange, main.
u8 XV_HdmiRxSs1_GetVideoIDCode(XV_HdmiRxSs1 *InstancePtr)
This function returns the pointer to HDMI RX SS video Identification code.
InstancePtr pointer to XV_HdmiRxSs1 instance VIC None.
References XV_HdmiRxSs1::HdmiRx1Ptr.
u8 XV_HdmiRxSs1_GetVideoStreamType(XV_HdmiRxSs1 *InstancePtr)
This function returns the pointer to HDMI RX SS video stream type.
InstancePtr pointer to XV_HdmiRxSs1 instance Stream Type 1:HDMI 0:DVI None.
References XV_HdmiRxSs1::HdmiRx1Ptr.
u8 XV_HdmiRxSs1_GetTransportMode(XV_HdmiRxSs1 *InstancePtr)
This function returns the pointer to HDMI RX SS video stream type.
InstancePtr pointer to XV_HdmiRxSs1 instance Transport Mode 1:FRL 0:TMDS None.
References XV_HdmiRxSs1::HdmiRx1Ptr.
u8 XV_HdmiRxSs1_GetVideoStreamScramblingFlag(XV_HdmiRxSs1 *InstancePtr)
This function returns the pointer to HDMI RX SS video stream type.
InstancePtr pointer to XV_HdmiRxSs1 instance Stream Type 1:IsScrambled 0: not Scrambled None.
References XV_HdmiRxSs1::HdmiRx1Ptr.
u8 XV_HdmiRxSs1_GetAudioChannels(XV_HdmiRxSs1 *InstancePtr)
This function returns the HDMI RX SS number of active audio channels.
InstancePtr pointer to XV_HdmiRxSs1 instance Channels None.
References XV_HdmiRxSs1::AudioChannels.
XV_HdmiRx1_AudioFormatType XV_HdmiRxSs1_GetAudioFormat(XV_HdmiRxSs1 *InstancePtr)
This function returns the HDMI RX SS audio format.
InstancePtr pointer to XV_HdmiRxSs1 instance Channels None.
References XV_HdmiRxSs1::HdmiRx1Ptr.
Referenced by XV_HdmiRxSs1_ReportAudio.
u32 XV_HdmiRxSs1_GetAudioAcrCtsVal(XV_HdmiRxSs1 *InstancePtr)
This function returns the HDMI RX SS CTS value.
InstancePtr pointer to XV_HdmiRxSs1 instance Channels None.
References XV_HdmiRxSs1::HdmiRx1Ptr.
u32 XV_HdmiRxSs1_GetAudioAcrNVal(XV_HdmiRxSs1 *InstancePtr)
This function returns the HDMI RX SS CTS value.
InstancePtr pointer to XV_HdmiRxSs1 instance Channels None.
References XV_HdmiRxSs1::HdmiRx1Ptr.
void XV_HdmiRxSs1_RefClockChangeInit(XV_HdmiRxSs1 *InstancePtr)
This function is called when HDMI RX SS TMDS clock changes.
InstancePtr pointer to XV_HdmiRxSs1 instance None None.
References XV_HdmiRxSs1::HdmiRx1Ptr, XV_HdmiRxSs1::TMDSClockRatio, XV_HDMIRXSS1_LOG_EVT_REFCLOCKCHANGE, XV_HdmiRxSs1_LogWrite.
void XV_HdmiRxSs1_DebugInfo(XV_HdmiRxSs1 *InstancePtr)
This function prints debug information on STDIO/UART console.
InstancePtr is a pointer to the XV_HdmiRxSs1 instance. None. None.
References XV_HdmiRxSs1::HdmiRx1Ptr.
Referenced by DetailedInfo.
void XV_HdmiRxSs1_DdcRegDump(XV_HdmiRxSs1 *InstancePtr)
This function prints out RX's SCDC registers and values on STDIO/UART console.
InstancePtr is a pointer to the XV_HdmiRxSs1 instance. None. None.
References XV_HdmiRxSs1::HdmiRx1Ptr.
void XV_HdmiRxSs1_ReportTiming(XV_HdmiRxSs1 *InstancePtr)
This function prints the HDMI RX SS timing information.
InstancePtr pointer to XV_HdmiRxSs1 instance None. None.
References XV_HdmiRxSs1::HdmiRx1Ptr.
Referenced by Info, XV_HdmiRxSs1_ReportInfo.
void XV_HdmiRxSs1_ReportLinkQuality(XV_HdmiRxSs1 *InstancePtr)
This function reports the link quality based on the link error counter.
InstancePtr pointer to XV_HdmiRxSs1 instance None. None.
References XV_HdmiRxSs1::HdmiRx1Ptr.
Referenced by Info, XV_HdmiRxSs1_ReportInfo.
void XV_HdmiRxSs1_ReportDRMInfo(XV_HdmiRxSs1 *InstancePtr)
This function prints the HDMI 2.1 RX SS static HDR infoframe information.
InstancePtr pointer to XV_HdmiRxSs1 instance None. None.
References XV_HdmiRxSs1_GetDrmInfoframe.
Referenced by Info, XV_HdmiRxSs1_ReportInfo.
void XV_HdmiRxSs1_ReportAudio(XV_HdmiRxSs1 *InstancePtr)
This function prints the HDMI RX SS audio information.
InstancePtr pointer to XV_HdmiRxSs1 instance None. None.
References XV_HdmiRxSs1::HdmiRx1Ptr, XV_HdmiRxSs1_GetAudioFormat.
Referenced by Info, XV_HdmiRxSs1_ReportInfo.
void XV_HdmiRxSs1_ReportInfoFrame(XV_HdmiRxSs1 *InstancePtr)
This function prints the HDMI RX SS audio information.
InstancePtr pointer to XV_HdmiRxSs1 instance None. None.
References XV_HdmiRxSs1::HdmiRx1Ptr.
Referenced by XV_HdmiRxSs1_ReportInfo.
void XV_HdmiRxSs1_ReportSubcoreVersion(XV_HdmiRxSs1 *InstancePtr)
This function prints the HDMI RX SS subcore versions.
InstancePtr pointer to XV_HdmiRxSs1 instance None. None.
References XV_HdmiRxSs1::HdmiRx1Ptr.
Referenced by DetailedInfo, XV_HdmiRxSs1_ReportInfo.
int XV_HdmiRxSs1_IsStreamUp(XV_HdmiRxSs1 *InstancePtr)
This function checks if the video stream is up.
InstancePtr pointer to XV_HdmiRxSs1 instance TRUE if stream is up.FALSE if stream is down. None.
References XV_HdmiRxSs1::IsStreamUp.
int XV_HdmiRxSs1_IsStreamConnected(XV_HdmiRxSs1 *InstancePtr)
This function checks if the interface is connected.
InstancePtr pointer to XV_HdmiRxSs1 instance TRUE if interface is connected.FALSE if interface is not connected. None.
References XV_HdmiRxSs1::IsStreamConnected.
void XV_HdmiRxSs1_SetDefaultPpc(XV_HdmiRxSs1 *InstancePtr, u8 Id)
This function will set the default in HDF.
InstancePtr is a pointer to the XV_HdmiRxSs1 core instance. Id is the XV_HdmiRxSs1 ID to operate on. None. None.
References XV_HdmiRxSs1::Config, XV_HdmiRxSs1_Config::Ppc.
void XV_HdmiRxSs1_SetPpc(XV_HdmiRxSs1 *InstancePtr, u8 Id, u8 Ppc)
This function will set PPC specified by user.
InstancePtr is a pointer to the XV_HdmiRxSs1 core instance. Id is the XV_HdmiRxSs1 ID to operate on. Ppc is the PPC to be set. None. None.
References XV_HdmiRxSs1::Config, XV_HdmiRxSs1_Config::Ppc.
void XV_HdmiRxSS1_SetAppVersion(XV_HdmiRxSs1 *InstancePtr, u8 maj, u8 min)
This function will set the major and minor application version in RXSs struct.
InstancePtr is a pointer to the XV_HdmiRxSs1 core instance. maj is the major version of the application. min is the minor version of the application. None. None.
References XV_HdmiRxSs1::AppMajVer, XV_HdmiRxSs1::AppMinVer.
void XV_HdmiRxSs1_AudioMute(XV_HdmiRxSs1 *InstancePtr, u8 Enable)
This function set HDMI RX audio parameters.
InstancePtr is a pointer to the XV_HdmiRxSs1 core instance. Enable 0: Unmute the audio 1: Mute the audio. None. None.
References XV_HdmiRxSs1::HdmiRx1Ptr.
void XV_HdmiRxSs1_VfpControl(XV_HdmiRxSs1 *InstancePtr, u8 Enable)
This function controls HDMI RX VFP event enable/disable.
InstancePtr is a pointer to the XV_HdmiRxSs1 core instance. Enable 0: disable VFP event 1: enable VFP event. None. None.
References XV_HdmiRxSs1::HdmiRx1Ptr.
XV_HdmiC_VrrInfoFrame* XV_HdmiRxSs1_GetVrrIf(XV_HdmiRxSs1 *InstancePtr)
This function returns VRR infoframe type.
InstancePtr is a pointer to the XV_HdmiRxSs1 instance. XV_HdmiRx1_VrrInfoframeType None.
References XV_HdmiRxSs1::HdmiRx1Ptr.
Referenced by Exdes_ProcessVTEMPacket, Exdes_ReadVTEMPacket, main.
XVidC_PixelsPerClock XV_HdmiRxSs1_GetCorePpc(XV_HdmiRxSs1 *InstancePtr)
This function returns core ppc value.
InstancePtr pointer to XV_HdmiRXSs instance Core pixel per clock value None.
References XV_HdmiRxSs1::HdmiRx1Ptr.
void XV_HdmiRxSs1_DynHDR_DM_Enable(XV_HdmiRxSs1 *InstancePtr)
This function enables the Data mover in Dynamic HDR.
InstancePtr pointer to XV_HdmiRXSs instance None None.
References XV_HdmiRxSs1::Config, XV_HdmiRxSs1_Config::DynamicHDR, XV_HdmiRxSs1::HdmiRx1Ptr.
void XV_HdmiRxSs1_DynHDR_DM_Disable(XV_HdmiRxSs1 *InstancePtr)
This function disables the Data mover in Dynamic HDR.
InstancePtr pointer to XV_HdmiRXSs instance None None.
References XV_HdmiRxSs1::Config, XV_HdmiRxSs1_Config::DynamicHDR, XV_HdmiRxSs1::HdmiRx1Ptr.
void XV_HdmiRxSs1_DynHDR_SetAddr(XV_HdmiRxSs1 *InstancePtr, u64 Addr)
This function sets the buffer address for Dynamic HDR.
InstancePtr pointer to XV_HdmiRXSs instance Addr 64 bit address None None.
References XV_HdmiRxSs1::Config, XV_HdmiRxSs1_Config::DynamicHDR, XV_HdmiRxSs1::HdmiRx1Ptr.
Referenced by main.
void XV_HdmiRxSs1_DynHDR_GetInfo(XV_HdmiRxSs1 *InstancePtr, XV_HdmiRxSs1_DynHDR_Info *RxDynHdrInfo)
This function sets the buffer address for Dynamic HDR.
InstancePtr pointer to XV_HdmiRXSs instance RxDynHdrInfo pointer to dynamic hdr info structure. This is passed by the application. None None.
References XV_HdmiRxSs1::Config, XV_HdmiRxSs1_Config::DynamicHDR, XV_HdmiRxSs1::HdmiRx1Ptr.
u32 XV_HdmiRxSs1_DSC_IsEnableStream(XV_HdmiRxSs1 *InstancePtr)
This function verifies whether the DSC feature is enabled in the HDMI RX subsystem and, if so, queries the underlying HDMI RX core to determine if the DSC stream is active.
InstancePtr Pointer to the XV_HdmiRxSs1 instance. 1 if the DSC stream is enabled.0 if the DSC stream is not enabled or DSC is not supported. The function asserts that both InstancePtr and InstancePtr->HdmiRx1Ptr are valid.
References XV_HdmiRxSs1::Config, XV_HdmiRxSs1_Config::DSC, XV_HdmiRxSs1::HdmiRx1Ptr.
int XV_HdmiRxSs1_DSC_SetDecodeFail(XV_HdmiRxSs1 *InstancePtr)
This function sets the DSC Decode Fail flag in the HDMI RX FRL DDC field.
InstancePtr pointer to XV_HdmiRXSs instance XST_SUCCESS if the operation was successful.XST_NO_FEATURE if DSC is not supported in the current configuration This function uses an assertion to ensure that the input pointer is not NULL.
References XV_HdmiRxSs1::HdmiRx1Ptr.
int XV_HdmiRxSs1_DSC_SetDscFrlMax(XV_HdmiRxSs1 *InstancePtr)
This function sets the DSC FRL Max flag in the HDMI RX FRL DDC field.
This function writes a value of 1 to the DSC_FRL_MAX field using the FRL DDC interface. It is used to indicate that the maximum FRL (Fixed Rate Link) bandwidth is being used for Display Stream Compression (DSC) on the HDMI RX path InstancePtr pointer to XV_HdmiRXSs instance XST_SUCCESS if the operation was successful.XST_NO_FEATURE if DSC is not supported in the current configuration This function uses an assertion to ensure that the input pointer is not NULL.
References XV_HdmiRxSs1::HdmiRx1Ptr.