xdprxss_dbg.c
void XDpRxSs_ReportCoreInfo(XDpRxSs *InstancePtr)
This function reports list of sub-cores included in DisplayPort RX Subsystem.
InstancePtr is a pointer to the XDpRxSs core instance. None.
References XDpRxSs_Config::ColorFormat, XDpRxSs::Config, XDpRxSs::DpPtr, XDpRxSs_Config::HdcpEnable, XDpRxSs_Config::MaxBpc, XDpRxSs_Config::MaxLaneCount, XDpRxSs_Config::MaxNumAudioCh, XDpRxSs_UsrOpt::MstSupport, XDpRxSs_Config::MstSupport, XDpRxSs_Config::NumMstStreams, XDpRxSs_UsrOpt::NumOfStreams, XDpRxSs_Config::SecondaryChEn, XDpRxSs::UsrOpt.
Referenced by DpRxSs_DebugExample, DpRxSs_Main.
void XDpRxSs_ReportLinkInfo(XDpRxSs *InstancePtr)
This function prints the link status, selected resolution, link rate /lane count symbol error.
InstancePtr is a pointer to the XDpRxSs core instance. None.
References XDpRxSs::DpPtr, XDpRxSs_ReadReg.
Referenced by DpRxSs_DebugExample, DpRxSs_Main.
void XDpRxSs_ReportMsaInfo(XDpRxSs *InstancePtr)
This function prints the current main stream attributes from the DisplayPort RX core.
InstancePtr is a pointer to the XDpRxSs core instance. None.
References XDpRxSs::Config, XDpRxSs::DpPtr, XDpRxSs_Config::NumMstStreams.
Referenced by DpRxSs_DebugExample, DpRxSs_Main.
void XDpRxSs_ReportHdcpInfo(XDpRxSs *InstancePtr)
This function prints the debug display info of the HDCP interface.
InstancePtr is a pointer to the XDpRxSs core instance. None.
Referenced by DpRxSs_DebugExample.