xdprxss_sinit.c
XDpRxSs_Config * XDpRxSs_LookupConfig(UINTPTR BaseAddress)
This function returns a reference to an XDpRxSs_Config structure based on the core id, DeviceId.
The return value will refer to an entry in the device configuration table defined in the xdprxss_g.c file. DeviceId is the unique core ID of the XDpRxSs core for the lookup operation. XDpRxSs_LookupConfig returns a reference to a config record in the configuration table (in xdprxss_g.c) corresponding to DeviceId, or NULL if no match is found. None.
Referenced by DpRxSs_DebugExample, DpRxSs_HdcpExample, DpRxSs_IntrExample, DpRxSs_Main, DpRxSs_MstExample, DpRxSs_SelfTestExample.
u32 XDpRxSs_GetDrvIndex(UINTPTR BaseAddress)
This function returns the Index number of config table using BaseAddress.
Base address of the instance Index number of the config table