xdprxss_dp14_rx.c
XPAR_IIC_0_BASEADDR
XINTC_DPRXSS_DP_INTERRUPT_ID
XINTC
XINTC_DEVICE_ID
XINTC_HANDLER
XDPRXSS_DEVICE_ID
XVPHY_DEVICE_ID
XTIMER0_DEVICE_ID
VIDEO_CRC_BASEADDR
UARTLITE_BASEADDR
VIDPHY_BASEADDR
VID_EDID_BASEADDR
IIC_DEVICE_ID
DPRXSS_LINK_RATE
DPRXSS_LANE_COUNT
SET_TX_TO_2BYTE
SET_RX_TO_2BYTE
XDP_RX_CRC_CONFIG
XDP_RX_CRC_COMP0
XDP_RX_CRC_COMP1
XDP_RX_CRC_COMP2
XDP_RX_DPC_LINK_QUAL_CONFIG
XDP_RX_DPC_L01_PRBS_CNTR
XDP_RX_DPC_L23_PRBS_CNTR
XDP_RX_DPCD_LINK_QUAL_PRBS
DP_BS_IDLE_TIMEOUT
VBLANK_WAIT_COUNT
AUX_DEFER_COUNT
LINK_TRAINING_DEBUG
DP12_EDID_ENABLED
XVPHY_RX_SYM_ERR_CNTR_CH1_2_REG
XVPHY_RX_SYM_ERR_CNTR_CH3_4_REG
XVPHY_DRP_CPLL_FBDIV
XVPHY_DRP_CPLL_REFCLK_DIV
XVPHY_DRP_RXOUT_DIV
XVPHY_DRP_RXCLK25
XVPHY_DRP_TXCLK25
XVPHY_DRP_TXOUT_DIV
XVPHY_DRP_RX_DATA_WIDTH
XVPHY_DRP_RX_INT_DATA_WIDTH
XVPHY_DRP_GTHE4_PRBS_ERR_CNTR_LOWER
XVPHY_DRP_GTHE4_PRBS_ERR_CNTR_UPPER
TIMER_RESET_VALUE
INTRNAME_DPRX
XVphy_User_GT_RefClk_Src
XVphy_User_Config PHY_User_Config_Table[][]
XilAudioInfoFrame AudioinfoFrame
XilAudioExtFrame SdpExtFrame
XilAudioExtFrame SdpExtFrame_q
u32 overflow_count
u32 missed_count
XDpRxSs DpRxSsInst
XINTC IntcInst
XVphy VPhyInst
XTmrCtr TmrCtr
Video_CRC_Config VidFrameCRC
DP_Rx_Training_Algo_Config RxTrainConfig
XIic IicInstance
u32 DpRxSs_Main(u32 BaseAddress)
This function is the main entry point for the design example using the XDpRxSs driver.
This function will setup the system with interrupts handlers. DeviceId is the unique device ID of the DisplayPort RX Subsystem core. XST_FAILURE if the system setup failed.XST_SUCCESS should never return since this function, if setup was successful, is blocking. If system setup was successful, this function is blocking in order to illustrate interrupt handling taking place for different types interrupts. Refer xdprxss.h file for more info.
References AppHelp, XDpRxSs_Config::BaseAddress, CalculateCRC, XDpRxSs::DpPtr, DpRxSs_PlatformInit, DpRxSs_Setup, DpRxSs_SetupIntrSystem, DpRxSs_VideoPhyInit, I2C_MCDP6000_ADDR, XDpRxSs_UsrOpt::LaneCount, XDpRxSs_UsrOpt::LinkRate, XDpRxSs_UsrOpt::MstSupport, Print_ExtPkt, Print_InfoPkt, ReportVideoCRC, XDpRxSs::UsrOpt, XDpRxSs::VBlankCount, XDpRxSs_AudioDisable, XDpRxSs_AudioEnable, XDpRxSs_CfgInitialize, XDpRxSs_LookupConfig, XDpRxSs_MCDP6000_GetRegister, XDpRxSs_McDp6000_init, XDpRxSs_MCDP6000_Read_ErrorCounters, XDpRxSs_ReportCoreInfo, XDpRxSs_ReportLinkInfo, XDpRxSs_ReportMsaInfo, XDpRxSs_SetLaneCount, XDpRxSs_SetLinkRate, XDpRxSs_Start, xil_getc.
Referenced by main.
u32 DpRxSs_PlatformInit(void)
This function initialize required platform specific peripherals.
None. XST_SUCCESS if required peripherals are initialized and configured successfully.XST_FAILURE, otherwise. None.
References I2C_IDT8N49_ADDR, IDT_8T49N24x_SetClock, VideoFMC_Init.
Referenced by DpRxSs_DebugExample, DpRxSs_HdcpExample, DpRxSs_IntrExample, DpRxSs_Main, DpRxSs_MstExample.
u32 DpRxSs_VideoPhyInit(u32 Baseaddress)
This function configures Video Phy.
None. XST_SUCCESS if Video Phy configured successfully.XST_FAILURE, otherwise. None.
References PHY_Two_byte_set, PLLRefClkSel.
Referenced by DpRxSs_DebugExample, DpRxSs_HdcpExample, DpRxSs_IntrExample, DpRxSs_Main, DpRxSs_MstExample.
u32 DpRxSs_Setup(void)
This function configures DisplayPort RX Subsystem.
None. XST_SUCCESS if DP RX Subsystem configured successfully.XST_FAILURE, otherwise. None. None. XST_SUCCESS if DPRX Subsystem configured successfully.XST_FAILURE, otherwise. None.
References XDpRxSs::DpPtr, LoadEDID.
Referenced by DpRxSs_DebugExample, DpRxSs_HdcpExample, DpRxSs_IntrExample, DpRxSs_Main, DpRxSs_MstExample.
void PHY_Two_byte_set(XVphy *InstancePtr, u8 Rx_to_two_byte)
This function sets GT in 16-bits (2-Byte) or 32-bits (4-Byte) mode.
InstancePtr is a pointer to the Video PHY instance. None. None.
Referenced by DpRxSs_VideoPhyInit.
void PLLRefClkSel(XVphy *InstancePtr, u8 link_rate)
This function sets proper ref clk frequency and line rate.
InstancePtr is a pointer to the Video PHY instance. None. None.
Referenced by DpRxSs_LinkBandwidthHandler, DpRxSs_VideoPhyInit.
void AppHelp()
This function prints Menu.
None. None. None.
Referenced by DpRxSs_Main.
void ReportVideoCRC()
This function reports CRC values of Video components.
None. None. None.
Referenced by DpRxSs_Main.
void CalculateCRC(void)
This function Calculates CRC values of Video components.
None. None. None.
References CustomWaitUs, XDpRxSs::DpPtr, XDpRxSs_UsrOpt::LaneCount, XDpRxSs::UsrOpt.
Referenced by DpRxSs_Main.
void LoadEDID(void)
This function load EDID content into EDID Memory.
User can change as per their requirement. None. None. None.
Referenced by DpRxSs_Setup.
char XUartPs_RecvByte_NonBlocking()
This function is a non-blocking UART return byte.
None. None. None.
Referenced by xil_getc.
void CustomWaitUs(void *InstancePtr, u32 MicroSeconds)
This function is called when DisplayPort Subsystem core requires delay or sleep.
It provides timer with predefined amount of loop iterations. InstancePtr is a pointer to the XDp instance. None.
Referenced by CalculateCRC, DpRxSs_SetupIntrSystem.
char xil_getc(u32 timeout_ms)
This function to get uart input from user.
timeout_ms received character None.
References XUartPs_RecvByte_NonBlocking.
Referenced by DpRxSs_Main.
u32 DpRxSs_SetupIntrSystem(void)
This function sets up the interrupt system so interrupts can occur for the DisplayPort RX Subsystem core.
The function is application-specific since the actual system may or may not have an interrupt controller. The DPRX Subsystem core could be directly connected to a processor without an interrupt controller. The user should modify this function to fit the application. None XST_SUCCESS if interrupt setup was successful.A specific error code defined in "xstatus.h" if an error occurs. None.
References XDpRxSs::Config, CustomWaitUs, DpRxSs_AccessErrorCounterHandler, DpRxSs_AccessLinkQualHandler, DpRxSs_BWChangeHandler, DpRxSs_CRCTestEventHandler, DpRxSs_ExtPacketHandler, DpRxSs_InfoPacketHandler, DpRxSs_LinkBandwidthHandler, DpRxSs_NoVideoHandler, DpRxSs_PllResetHandler, DpRxSs_PowerChangeHandler, DpRxSs_TrainingDoneHandler, DpRxSs_TrainingLostHandler, DpRxSs_UnplugHandler, DpRxSs_VerticalBlankHandler, DpRxSs_VideoHandler, XDpRxSs_DpIntrHandler, XDPRXSS_HANDLER_ACCESS_ERROR_COUNTER_EVENT, XDPRXSS_HANDLER_ACCESS_LINK_QUAL_EVENT, XDPRXSS_HANDLER_DP_BW_CHG_EVENT, XDPRXSS_HANDLER_DP_CRC_TEST_EVENT, XDPRXSS_HANDLER_DP_EXT_PKT_EVENT, XDPRXSS_HANDLER_DP_INFO_PKT_EVENT, XDPRXSS_HANDLER_DP_NO_VID_EVENT, XDPRXSS_HANDLER_DP_PWR_CHG_EVENT, XDPRXSS_HANDLER_DP_TDONE_EVENT, XDPRXSS_HANDLER_DP_TLOST_EVENT, XDPRXSS_HANDLER_DP_VBLANK_EVENT, XDPRXSS_HANDLER_DP_VID_EVENT, XDPRXSS_HANDLER_LINKBW_EVENT, XDPRXSS_HANDLER_PLL_RESET_EVENT, XDPRXSS_HANDLER_UNPLUG_EVENT, XDpRxSs_SetCallBack, XDpRxSs_SetUserTimerHandler.
Referenced by DpRxSs_IntrExample, DpRxSs_Main, DpRxSs_MstExample.
void DpRxSs_PowerChangeHandler(void *InstancePtr)
This function is the callback function for when the power state interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
Referenced by DpRxSs_SetupIntrSystem.
void DpRxSs_NoVideoHandler(void *InstancePtr)
This function is the callback function for when a no video interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
References XDpRxSs::DpPtr, XDpRxSs::VBlankCount.
Referenced by DpRxSs_SetupIntrSystem.
void DpRxSs_VerticalBlankHandler(void *InstancePtr)
This function is the callback function for when a vertical blank interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
References XDpRxSs::VBlankCount.
Referenced by DpRxSs_SetupIntrSystem.
void DpRxSs_TrainingLostHandler(void *InstancePtr)
This function is the callback function for when a training lost interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
References XDpRxSs::DpPtr, XDpRxSs_AudioDisable.
Referenced by DpRxSs_SetupIntrSystem.
void DpRxSs_VideoHandler(void *InstancePtr)
This function is the callback function for when a valid video interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
Referenced by DpRxSs_SetupIntrSystem.
void DpRxSs_InfoPacketHandler(void *InstancePtr)
This function is the callback function for Info Packet Handling.
This function is the callback function for when an info packet interrupt occurs. InstancePtr is a pointer to the XDpRxSs instance. None. None.
References XDpRxSs::DpPtr.
Referenced by DpRxSs_SetupIntrSystem.
void DpRxSs_ExtPacketHandler(void *InstancePtr)
This function is the callback function for Generic Packet Handling of 32-Bytes payload.
This function is the callback function for when arrival of external (audio) packet interrupt occurs. InstancePtr is a pointer to the XDpRxSs instance. None. None.
References XDpRxSs::DpPtr.
Referenced by DpRxSs_SetupIntrSystem.
void DpRxSs_TrainingDoneHandler(void *InstancePtr)
This function is the callback function for when the training done interrupt occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
Referenced by DpRxSs_SetupIntrSystem.
void DpRxSs_UnplugHandler(void *InstancePtr)
This function is the callback function for when the unplug event occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
References XDpRxSs::DpPtr, XDpRxSs_AudioDisable.
Referenced by DpRxSs_SetupIntrSystem.
void DpRxSs_LinkBandwidthHandler(void *InstancePtr)
This function is the callback function for when the link bandwidth change occurs.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
References XDpRxSs_UsrOpt::LinkRate, PLLRefClkSel, XDpRxSs::UsrOpt.
Referenced by DpRxSs_SetupIntrSystem.
void DpRxSs_PllResetHandler(void *InstancePtr)
This function is the callback function for PLL reset request.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
References XDpRxSs::DpPtr.
Referenced by DpRxSs_SetupIntrSystem.
void DpRxSs_BWChangeHandler(void *InstancePtr)
This function is the callback function for PLL reset request.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
Referenced by DpRxSs_SetupIntrSystem.
void DpRxSs_AccessLaneSetHandler(void *InstancePtr)
This function is the callback function for Access lane set request.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
void DpRxSs_AccessLinkQualHandler(void *InstancePtr)
This function is the callback function for Access link qual request.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
References XDpRxSs::DpPtr, I2C_MCDP6000_ADDR, XDpRxSs_MCDP6000_ClearCounter, XDpRxSs_MCDP6000_DisablePrbs7_Rx, XDpRxSs_MCDP6000_EnablePrbs7_Rx.
Referenced by DpRxSs_SetupIntrSystem.
void DpRxSs_AccessErrorCounterHandler(void *InstancePtr)
This function is the callback function for Access prbs error count.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
References XDpRxSs::DpPtr, I2C_MCDP6000_ADDR, XDpRxSs_MCDP6000_GetRegister, XDpRxSs_MCDP6000_Read_ErrorCounters.
Referenced by DpRxSs_SetupIntrSystem.
void DpRxSs_CRCTestEventHandler(void *InstancePtr)
This function is the callback function for Test CRC Event request.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
References XDpRxSs_Config::BaseAddress, XDpRxSs::Config, XDpRxSs::DpPtr.
Referenced by DpRxSs_SetupIntrSystem.
void XDp_RxInterruptDisable1(XDp *InstancePtr, u32 Mask)
void XDp_RxInterruptEnable1(XDp *InstancePtr, u32 Mask)
int i2c_write_dp141(u32 I2CBaseAddress, u8 I2CSlaveAddress, u16 RegisterAddress, u8 Value)
int VideoFMC_Init(void)
This function initializes VFMC.
None. None. None.
References I2C_IDT8N49_ADDR, I2C_LMK03318_ADDR, I2C_MUX_ADDR, I2C_VFMCEXP_0_ADDR, I2C_VFMCEXP_1_ADDR, IDT_8T49N24x_Init, TI_LMK03318_PowerDown.
Referenced by DpRxSs_PlatformInit.
void Print_InfoPkt()
This function is the callback function for Info Packet Handling.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
Referenced by DpRxSs_Main.
void Print_ExtPkt()
This function is the callback function for Ext Packet Handling.
InstancePtr is a pointer to the XDpRxSs instance. None. None.
Referenced by DpRxSs_Main.
void enable_caches()
void disable_caches()
int main()
This is the main function for XDpRxSs interrupt example.
If the DpRxSs_Main function which setup the system succeeds, this function will wait for the interrupts. None. XST_FAILURE if the interrupt example was unsuccessful. Unless setup failed, main will never return since DpRxSs_Main is blocking (it is waiting on interrupts).
References DpRxSs_Main.
void I2C_Scan(u32 BaseAddress)
This function scans VFMC- IIC.
None. None. None.
u8 i2c_read_dp141(u32 I2CBaseAddress, u8 I2CSlaveAddress, u16 RegisterAddress)
This function reads DP141 VFMC- IIC.
None. None. None.
void read_DP141()