xdprxss_mcdp6000.h
XDPRXSS_MCDP6000_IIC_SLAVE
MCDP6000 slave device.
Referenced by XDpRxSs_McDp6000_init.
u32 XDpRxSs_MCDP6000_GetRegister(XDpRxSs *DpRxSsPtr, u8 I2CSlaveAddress, u16 RegisterAddress)
This function reads a single 32b word from the MCDP6000 device.
DpRxSsPtr is a pointer to the XDpRxSs core instance. I2CSlaveAddress is the 7-bit I2C slave address. RegisterAddress is the 16-bit register address. The read 32b data. None.
References XDpRxSs::Config.
Referenced by DpRxSs_AccessErrorCounterHandler, DpRxSs_Main, XDpRxSs_MCDP6000_ClearCounter, XDpRxSs_MCDP6000_DisablePrbs7_Rx, XDpRxSs_MCDP6000_DpInit, XDpRxSs_MCDP6000_EnableCounter, XDpRxSs_MCDP6000_EnablePrbs7_Rx, XDpRxSs_MCDP6000_ModifyRegister, XDpRxSs_MCDP6000_Read_ErrorCounters, XDpRxSs_MCDP6000_RegisterDump.
int XDpRxSs_MCDP6000_SetRegister(XDpRxSs *DpRxSsPtr, u8 I2CSlaveAddress, u16 RegisterAddress, u32 Value)
This function writes a single 32b word to the MCDP6000 device.
DpRxSsPtr is a pointer to the XDpRxSs core instance. I2CSlaveAddress is the 7-bit I2C slave address. RegisterAddress is the 16-bit register address. Value is the 32b word to write XST_SUCCESS Register write was successful.XST_FAILURE I2C write error. None.
References XDpRxSs::Config.
Referenced by XDpRxSs_MCDP6000_AccessLaneSet, XDpRxSs_MCDP6000_ClearCounter, XDpRxSs_MCDP6000_DisablePrbs7_Rx, XDpRxSs_MCDP6000_DpInit, XDpRxSs_MCDP6000_EnableCounter, XDpRxSs_MCDP6000_EnablePrbs7_Rx, XDpRxSs_MCDP6000_EnablePrbs7_Tx, XDpRxSs_MCDP6000_IbertInit, XDpRxSs_MCDP6000_ModifyRegister, XDpRxSs_MCDP6000_Read_ErrorCounters, XDpRxSs_MCDP6000_ResetDpPath, XDpRxSs_MCDP6000_TransparentMode.
int XDpRxSs_MCDP6000_ModifyRegister(XDpRxSs *DpRxSsPtr, u8 I2CSlaveAddress, u16 RegisterAddress, u32 Value, u32 Mask)
This function modifies a single 32b word from the MCDP6000 device.
DpRxSsPtr is a pointer to the XDpRxSs core instance. I2CSlaveAddress is the 7-bit I2C slave address. RegisterAddress is the 16-bit register address. Value is the 32b word to write Mask is the 32b mask XST_SUCCESS Modification was successful.XST_FAILURE I2C write error. None.
References XDpRxSs_MCDP6000_GetRegister, XDpRxSs_MCDP6000_SetRegister.
Referenced by XDpRxSs_MCDP6000_BWchange, XDpRxSs_MCDP6000_ResetCrPath.
int XDpRxSs_MCDP6000_DpInit(XDpRxSs *DpRxSsPtr, u8 I2CSlaveAddress)
This function initializes the MCDP6000 device with default values for DP use with the Video FMC.
DpRxSsPtr is a pointer to the XDpRxSs core instance. I2CSlaveAddress is the 7-bit I2C slave address. XST_SUCCESS Initialization was successful.XST_FAILURE I2C write error. None.
References XDpRxSs_MCDP6000_GetRegister, XDpRxSs_MCDP6000_SetRegister.
Referenced by XDpRxSs_McDp6000_init.
int XDpRxSs_MCDP6000_IbertInit(XDpRxSs *DpRxSsPtr, u8 I2CSlaveAddress)
This function initializes the MCDP6000 device with default values for IBERT use with the Video FMC.
DpRxSsPtr is a pointer to the XDpRxSs core instance. I2CSlaveAddress is the 7-bit I2C slave address. XST_SUCCESS Initialization was successful.XST_FAILURE I2C write error. None.
References XDpRxSs_MCDP6000_SetRegister.
int XDpRxSs_MCDP6000_ResetDpPath(XDpRxSs *DpRxSsPtr, u8 I2CSlaveAddress)
This function requests a reset of the DP path of the MCDP6000 device.
DpRxSsPtr is a pointer to the XDpRxSs core instance. I2CSlaveAddress is the 7-bit I2C slave address. XST_SUCCESS Reset request was successful.XST_FAILURE I2C error. None.
References XDpRxSs_MCDP6000_SetRegister.
int XDpRxSs_MCDP6000_ResetCrPath(XDpRxSs *DpRxSsPtr, u8 I2CSlaveAddress)
This function requests a reset of the CR path of the MCDP6000 device.
DpRxSsPtr is a pointer to the XDpRxSs core instance. I2CSlaveAddress is the 7-bit I2C slave address. XST_SUCCESS Reset request was successful.XST_FAILURE I2C error. None.
References XDpRxSs_MCDP6000_ModifyRegister.
int XDpRxSs_MCDP6000_EnablePrbs7_Tx(XDpRxSs *DpRxSsPtr, u8 I2CSlaveAddress)
This function enables the PRBS7 output of the MCDP6000 device.
DpRxSsPtr is a pointer to the XDpRxSs core instance. I2CSlaveAddress is the 7-bit I2C slave address. XST_SUCCESS Enable request was successful.XST_FAILURE I2C error. None.
References XDpRxSs_MCDP6000_SetRegister.
int XDpRxSs_MCDP6000_EnablePrbs7_Rx(XDpRxSs *DpRxSsPtr, u8 I2CSlaveAddress)
This function enables the PRBS7 counter mode in MC Rx path Used in DP PHY compliance mode.
DpRxSsPtr is a pointer to the XDpRxSs core instance. I2CSlaveAddress is the 7-bit I2C slave address. XST_SUCCESS Enable request was successful.XST_FAILURE I2C error. None.
References XDpRxSs_MCDP6000_GetRegister, XDpRxSs_MCDP6000_SetRegister.
Referenced by DpRxSs_AccessLinkQualHandler.
int XDpRxSs_MCDP6000_DisablePrbs7_Rx(XDpRxSs *DpRxSsPtr, u8 I2CSlaveAddress)
This function Disables the PRBS7 counter mode in MC Rx path Used in DP PHY compliance mode.
DpRxSsPtr is a pointer to the XDpRxSs core instance. I2CSlaveAddress is the 7-bit I2C slave address. XST_SUCCESS Enable request was successful.XST_FAILURE I2C error. None.
References XDpRxSs_MCDP6000_GetRegister, XDpRxSs_MCDP6000_SetRegister.
Referenced by DpRxSs_AccessLinkQualHandler.
int XDpRxSs_MCDP6000_Read_ErrorCounters(XDpRxSs *DpRxSsPtr, u8 I2CSlaveAddress)
This function reads error counters for all lanes.
DpRxSsPtr is a pointer to the XDpRxSs core instance. I2CSlaveAddress is the 7-bit I2C slave address. XST_SUCCESS Enable request was successful.XST_FAILURE I2C error. None.
References XDpRxSs_MCDP6000_GetRegister, XDpRxSs_MCDP6000_SetRegister.
Referenced by DpRxSs_AccessErrorCounterHandler, DpRxSs_Main.
int XDpRxSs_MCDP6000_EnableCounter(XDpRxSs *DpRxSsPtr, u8 I2CSlaveAddress)
This function enables symbol counter.
DpRxSsPtr is a pointer to the XDpRxSs core instance. I2CSlaveAddress is the 7-bit I2C slave address. XST_SUCCESS Enable request was successful.XST_FAILURE I2C error. None.
References XDpRxSs_MCDP6000_GetRegister, XDpRxSs_MCDP6000_SetRegister.
int XDpRxSs_MCDP6000_ClearCounter(XDpRxSs *DpRxSsPtr, u8 I2CSlaveAddress)
This function clears symbol counter.
DpRxSsPtr is a pointer to the XDpRxSs core instance. I2CSlaveAddress is the 7-bit I2C slave address. XST_SUCCESS Enable request was successful.XST_FAILURE I2C error. None.
References XDpRxSs_MCDP6000_GetRegister, XDpRxSs_MCDP6000_SetRegister.
Referenced by DpRxSs_AccessLinkQualHandler.
void XDpRxSs_MCDP6000_RegisterDump(XDpRxSs *DpRxSsPtr, u8 I2CSlaveAddress)
This function displays a registerdump of the MCDP6000 device.
DpRxSsPtr is a pointer to the XDpRxSs core instance. I2CSlaveAddress is the 7-bit I2C slave address. None.
References XDpRxSs_MCDP6000_GetRegister.
int XDpRxSs_MCDP6000_TransparentMode(XDpRxSs *DpRxSsPtr, u8 I2CSlaveAddress)
This function sets the transparent mode of the MCDP6000 device.
DpRxSsPtr is a pointer to the XDpRxSs core instance. I2CSlaveAddress is the 7-bit I2C slave address. XST_SUCCESS transparent mode was set.XST_FAILURE setting transparent mode failed. None.
References XDpRxSs_MCDP6000_SetRegister.
int XDpRxSs_MCDP6000_BWchange(XDpRxSs *DpRxSsPtr, u8 I2CSlaveAddress)
This function changes the bandwidth of the MCDP6000 device.
DpRxSsPtr is a pointer to the XDpRxSs core instance. I2CSlaveAddress is the 7-bit I2C slave address. XST_SUCCESS BW change successful.XST_FAILURE BW change failed. None.
References XDpRxSs_MCDP6000_ModifyRegister.
int XDpRxSs_MCDP6000_AccessLaneSet(XDpRxSs *DpRxSsPtr, u8 I2CSlaveAddress)
This function sets the access lane register of the MCDP6000 device.
DpRxSsPtr is a pointer to the XDpRxSs core instance. I2CSlaveAddress is the 7-bit I2C slave address. XST_SUCCESS access lane set successful.XST_FAILURE setting access lane failed. None.
References XDpRxSs_MCDP6000_SetRegister.