xdptxss_zcu102_tx.h
XINTC_DPTXSS_DP_INTERRUPT_ID
XINTC_DEVICE_ID
XINTC
XINTC_HANDLER
XDPTXSS_DEVICE_ID
DPTXSS_MST
DPTXSS_LINK_RATE
DPTXSS_LANE_COUNT
DPTXSS_VID_MODE
DPTXSS_BPC
IIC_DEVICE_ID
XVPHY_DEVICE_ID
SET_TX_TO_2BYTE
TIMER_RESET_VALUE
is_TX_CPLL
CLK135MHz_DIVIDER
CLK270MHz_DIVIDER
CLK162MHz_DIVIDER
ENABLE_AUDIO
AV_PAT_GEN_BASE
CLK_WIZ_BASE
PE_VS_ADJUST
XVPHY_DRP_CPLL_FBDIV
XVPHY_DRP_CPLL_REFCLK_DIV
XVPHY_DRP_RXOUT_DIV
XVPHY_DRP_RXCLK25
XVPHY_DRP_TXCLK25
XVPHY_DRP_TXOUT_DIV
XVphy_User_GT_RefClk_Src
XVphy_User_Config PHY_User_Config_Table[][]
XDpTxSs DpTxSsInst
XIic IicInstance
XIic_Config* ConfigPtr_IIC
XScuGic IntcInst
XVphy VPhyInst
XTmrCtr TmrCtr
Video_CRC_Config VidFrameCRC
int tx_is_reconnected
u8 prev_line_rate
u8 hpd_pulse_con_event
void hpd_con(XDpTxSs *InstancePtr, u8 Edid_org[128], u8 Edid1_org[128], u16 res_update)
This function is called when a Hot-Plug-Detect (HPD) event is received by the DisplayPort TX Subsystem core.
InstancePtr is a pointer to the XDpTxSs instance. None. Use the XDpTxSs_SetCallback driver function to set this function as the handler for HPD event.
void hpd_pulse_con(XDpTxSs *InstancePtr)
This function is the main hpd pulse process.
None. None.
char xil_getc(u32 timeout_ms)
This function to get uart input from user.
timeout_ms received character None.
void sendAudioInfoFrame(XilAudioInfoFrame *xilInfoFrame)
This function to send Audio Information Frame.
XilAudioInfoFrame None. None.
void Vpg_Audio_start(void)
This function starts audio pattern generator.
None. None.
void Vpg_Audio_stop(void)
This function stops audio pattern generator.
None. None.
u32 start_tx(u8 line_rate, u8 lane_count, user_config_struct user_config)
This function starts tx process.
line rate lane counts pointer to resolution table bit per components video pattern to output XST_SUCCESS if interrupt setup was successful.A specific error code defined in "xstatus.h" if an error occurs. None.
u32 PHY_Configuration_Tx(XVphy *InstancePtr, XVphy_User_Config PHY_User_Config_Table)
This function sets up PHY.
pointer to VideoPHY User Config table XST_SUCCESS if interrupt setup was successful.A specific error code defined in "xstatus.h" if an error occurs. None.
u32 set_vphy(int LineRate_init_tx)
This function sets VPHY based on the linerate.
user_config_struct. Status. None.
void Vpg_VidgenSetUserPattern(XDp *InstancePtr, u8 Pattern)
This function sets user pattern.
InstancePtr is a pointer to the XDp instance. Pattern number to set with None. None.
void sink_power_down(void)
This function powers down sink.
None. None. None.
void sink_power_up(void)
This function powers down sink.
None. None. None.
u8 get_LineRate(void)
This function returns current line rate.
None. None. None.
u8 get_Lanecounts(void)
This function returns current lane counts.
None. None. None.
void sink_power_cycle(void)
This function power cycle the sink.
user_config_struct. Status. None.
int i2c_write_dp141(u32 I2CBaseAddress, u8 I2CSlaveAddress, u16 RegisterAddress, u8 Value)
void DpPt_pe_vs_adjustHandler(void *InstancePtr)
int VideoFMC_Init(void)
This function initializes VFMC.
None. None. None.
References I2C_MUX_ADDR, I2C_VFMCEXP_0_ADDR, I2C_VFMCEXP_1_ADDR, IDT_8T49N24x_Init, I2C_IDT8N49_ADDR, TI_LMK03318_PowerDown, I2C_LMK03318_ADDR.
Referenced by DpRxSs_PlatformInit.
int IDT_8T49N24x_SetClock(u32 I2CBaseAddress, u8 I2CSlaveAddress, int FIn, int FOut, u8 FreeRun)
This function calculates and sets the IDT 8TN49N24x device with the given clock configuration.
I2CBaseAddress is the baseaddress of the I2C core. I2CSlaveAddress is the 7-bit I2C slave address. FIn specifies the input frequency. FOut specifies the output frequency. FreeRun specifies if the operation mode is locked/synthesizer mode. TRUE Synthesizer mode (Fout only)FALSE Locked mode (Fout locked to Fin) XST_SUCCESS Initialization was successful.XST_FAILURE I2C write error or incorrect parameters detected.
References IDT_8T49N24X_FIN_MIN, IDT_8T49N24X_FIN_MAX, IDT_8T49N24X_FOUT_MIN, IDT_8T49N24X_FOUT_MAX.
Referenced by DpRxSs_PlatformInit.
int IDT_8T49N24x_Init(u32 I2CBaseAddress, u8 I2CSlaveAddress)
This function initializes the IDT 8TN49N24x with default values for use with the Video FMC.
This function set the GPIO outputs. I2CBaseAddress is the baseaddress of the I2C core. I2CSlaveAddress is the 7-bit I2C slave address. XST_SUCCESS Initialization was successful.XST_FAILURE I2C write error. None. I2CBaseAddress is the baseaddress of the I2C core. I2CSlaveAddress is the 7-bit I2C slave address. XST_SUCCESSXST_FAILURE None. This function set the input reference I2CBaseAddress is the baseaddress of the I2C core. I2CSlaveAddress is the 7-bit I2C slave address. XST_SUCCESSXST_FAILURE None. This function set the output drivers I2CBaseAddress is the baseaddress of the I2C core. I2CSlaveAddress is the 7-bit I2C slave address. XST_SUCCESSXST_FAILURE None. This function sets the lock mode I2CBaseAddress is the baseaddress of the I2C core. I2CSlaveAddress is the 7-bit I2C slave address. XST_SUCCESSXST_FAILURE None. This function initializes the IDT 8TN49N24x with default values for use with the Video FMC. I2CBaseAddress is the baseaddress of the I2C core. I2CSlaveAddress is the 7-bit I2C slave address. XST_SUCCESS Initialization was successful.XST_FAILURE I2C write error. None.
Referenced by VideoFMC_Init.
int TI_LMK03318_PowerDown(u32 I2CBaseAddress, u8 I2CSlaveAddress)
This function puts the TI LMK03318 into sleep.
I2CBaseAddress is the baseaddress of the I2C core. I2CSlaveAddress is the 7-bit I2C slave address. XST_SUCCESS Initialization was successful.XST_FAILURE I2C write error. None.
Referenced by VideoFMC_Init.