xv_hdmirx1_frl.c
Timer2MS
Timer5MS
Timer40MS
Timer100MS
Timer200MS
Timer250MS
Timer500MS
ANSI_COLOR_RED
ANSI_COLOR_GREEN
ANSI_COLOR_YELLOW
ANSI_COLOR_BLUE
ANSI_COLOR_MAGENTA
ANSI_COLOR_CYAN
ANSI_COLOR_WHITE
ANSI_COLOR_RESET
const u16 FrlTimeoutLts3[4][4]
This table contains the timeout period of LTS3 for different FFE Levels in Milliseconds.
const XV_HdmiRx1_FrlScdcField FrlScdcField[XV_HDMIRX1_SCDCFIELD_SIZE][XV_HDMIRX1_SCDCFIELD_SIZE]
This table contains the attributes for SCDC fields Each entry consists of: 1) Register Offset 2) Bits Mask 3) Bits Shift.
u32 XV_HdmiRx1_FrlDdcReadField(XV_HdmiRx1 *InstancePtr, XV_HdmiRx1_FrlScdcFieldType Field)
This function reads the specified FRL SCDC Field.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. Field specifies the fields from SCDC channels to be written XST_SUCCESSXST_FAILURE None.
References XV_HdmiRx1_Config::BaseAddress, XV_HdmiRx1::Config, XV_HdmiRx1_FrlScdcField::Offset, XV_HDMIRX1_FRL_SCDC_ADDR_MASK, XV_HDMIRX1_FRL_SCDC_DAT_SHIFT, XV_HDMIRX1_FRL_SCDC_OFFSET, XV_HDMIRX1_FRL_SCDC_RD_MASK, XV_HDMIRX1_FRL_SCDC_RDY_MASK, XV_HdmiRx1_ReadReg, XV_HdmiRx1_WriteReg.
Referenced by XV_HdmiRx1_FrlDdcWriteField, XV_HdmiRx1_UpdateEdFlags.
int XV_HdmiRx1_FrlDdcWriteField(XV_HdmiRx1 *InstancePtr, XV_HdmiRx1_FrlScdcFieldType Field, u8 Value)
This function writes the specified FRL SCDC Field.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. Field specifies the fields from SCDC channels to be written Value specifies the values to be written XST_SUCCESSXST_FAILUREXST_DEVICE_BUSY None.
References XV_HdmiRx1_Config::BaseAddress, XV_HdmiRx1::Config, XV_HdmiRx1_FrlScdcField::Mask, XV_HdmiRx1_FrlScdcField::Shift, XV_HDMIRX1_FRL_SCDC_ADDR_MASK, XV_HDMIRX1_FRL_SCDC_DAT_MASK, XV_HDMIRX1_FRL_SCDC_DAT_SHIFT, XV_HDMIRX1_FRL_SCDC_OFFSET, XV_HDMIRX1_FRL_SCDC_RDY_MASK, XV_HDMIRX1_FRL_SCDC_WR_MASK, XV_HdmiRx1_FrlDdcReadField, XV_HdmiRx1_ReadReg, XV_HdmiRx1_WriteReg.
Referenced by XV_HdmiRx1_CfgInitialize, XV_HdmiRx1_DSC_SetDecodeFail, XV_HdmiRx1_DSC_SetDscFrlMax, XV_HdmiRx1_FrlScdcInit, XV_HdmiRx1_UpdateEdFlags.
void XV_HdmiRx1_FrlScdcInit(XV_HdmiRx1 *InstancePtr)
This function initializes FRL-specific SCDC fields that are required for FRL operation.
This should be called separately from the basic SCDC clear operation when FRL is enabled. InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. This function should only be called when FRL is enabled.
References XV_HdmiRx1_FrlDdcWriteField.
Referenced by XV_HdmiRx1_CfgInitialize.