xv_hdmirx1.h
XV_HdmiRx1_HandlerType
A connect event interrupt type.
XV_HdmiRx1_State
XV_HdmiRx1_SyncStatus
Sync Loss.
XV_HdmiRx1_AudioFormatType
XV_HdmiRx1_EdidSize
XV_HdmiRx1_DynHdrErrType
Sequence id or ECC error.
XV_HDMIRX1_H_
Prevent circular inclusions by using protection macros.
TIME_10MS
Represents a 10 millisecond time interval in clock cycles.
Calculated based on the AXI Lite interface frequency. Useful for short delays or polling intervals.
TIME_200MS
Represents a 200 millisecond time interval in clock cycles.
Useful for medium-duration timeouts or periodic checks.
TIME_16MS
Represents a 16 millisecond time interval in clock cycles.
Equivalent to approximately one frame at 60 Hz refresh rate. Useful for frame-based timing.
TIME_500MS
Represents a 500 millisecond time interval in clock cycles.
Suitable for longer delays or watchdog timers.
XV_HdmiRx1_GetTime10Ms
This macro returns the clock cycles required to count up to 10Ms with respect to AXI Lite Frequency.
InstancePtr is a pointer to the XV_HdmiRX1 core instance. None.
XV_HdmiRx1_GetTime16Ms
This macro returns the clock cycles required to count up to 16Ms with respect to AXI Lite Frequency.
InstancePtr is a pointer to the XV_HdmiRX1 core instance. None.
Referenced by XV_HdmiRx1_CfgInitialize.
XV_HdmiRx1_GetTime200Ms
This macro returns the clock cycles required to count up to 200Ms with respect to AXI Lite Frequency.
InstancePtr is a pointer to the XV_HdmiRX1 core instance. None.
XV_HdmiRx1_GetTime1S
This macro returns the clock cycles required to count up to 1s with respect to AXI Lite Frequency.
InstancePtr is a pointer to the XV_HdmiRX1 core instance. None.
XV_HdmiRx1_GetVersion
This macro reads the RX version.
InstancePtr is a pointer to the XHdmi_RX core instance. RX version. *note C-style signature: u32 XV_HdmiRx1_GetVersion(XV_HdmiRx1 *InstancePtr)
XV_HdmiRx1_Reset
This macro asserts or clears the HDMI RX reset.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. Reset specifies TRUE/FALSE value to either assert or release HDMI RX reset. None. The reset output of the PIO is inverted. When the system is in reset, the PIO output is cleared and this will reset the HDMI RX. Therefore, clearing the PIO reset output will assert the HDMI link and video reset. C-style signature: void XV_HdmiRx1_Reset(XV_HdmiRx1 *InstancePtr, u8 Reset)
XV_HdmiRx1_LinkEnable
This macro asserts or clears the HDMI RX link enable.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. SetClr specifies TRUE/FALSE value to either assert or release HDMI RX link enable. None. C-style signature: void XV_HdmiRx1_Reset(XV_HdmiRx1 *InstancePtr, u8 SetClr)
XV_HdmiRx1_VideoEnable
This macro asserts or clears the HDMI RX video enable.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. SetClr specifies TRUE/FALSE value to either assert or release HDMI RX video enable. None. C-style signature: void XV_HdmiRx1_Reset(XV_HdmiRx1 *InstancePtr, u8 SetClr)
XV_HdmiRx1_SetScrambler
This macro controls the HDMI RX Scrambler.
InstancePtr is a pointer to the XHdmi_Rx core instance. SetClr specifies TRUE/FALSE value to either enable or disable the scrambler. None. C-style signature: void XV_HdmiRx1_SetScrambler(XV_HdmiRx1 *InstancePtr, u8 SetClr)
XV_HdmiRx1_Bridge_yuv420
This macro controls the YUV420 mode for video bridge.
InstancePtr is a pointer to the XHdmi_Rx core instance. SetClr specifies TRUE/FALSE value to either enable or disable the YUV 420 Support. None. C-style signature: void XV_HdmiRx1_Bridge_yuv420(XV_HdmiRx1 *InstancePtr, u8 SetClr)
XV_HdmiRx1_Bridge_pixel
This macro controls the Pixel Drop mode for video bridge.
InstancePtr is a pointer to the XHdmi_Rx core instance. SetClr specifies TRUE/FALSE value to either enable or disable the Pixel Repetition. None. C-style signature: void XV_HdmiRx1_Bridge_pixel(XV_HdmiRx1 *InstancePtr, u8 SetClr)
XV_HdmiRx1_AxisEnable
This macro asserts or clears the AXIS enable output port.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. Enable specifies TRUE/FALSE value to either enable or disable the AXIS output port. None. The reset output of the PIO is inverted. When the system is in reset, the PIO output is cleared and this will reset the HDMI RX. Therefore, clearing the PIO reset output will assert the HDMI link and video reset. C-style signature: void XV_HdmiRx1_AxisEnable(InstancePtr, Enable)
XV_HdmiRx1_PioEnable
This macro enables the HDMI RX PIO peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_PioEnable(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_Start.
XV_HdmiRx1_PioDisable
This macro disables the HDMI RX PIO peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_PioDisable(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_CfgInitialize, XV_HdmiRx1_Stop.
XV_HdmiRx1_PioIntrEnable
This macro enables interrupts in the HDMI RX PIO peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_PioIntrEnable(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_Start.
XV_HdmiRx1_PioIntrDisable
This macro disables interrupts in the HDMI RX PIO peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_PioIntrDisable(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_CfgInitialize, XV_HdmiRx1_Stop.
XV_HdmiRx1_Tmr1Enable
This macro enables the HDMI RX timer peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_Tmr1Enable(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_CfgInitialize.
XV_HdmiRx1_Tmr1Disable
This macro disables the HDMI RX timer peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_Tmr1Disable(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_CfgInitialize.
XV_HdmiRx1_Tmr1IntrEnable
This macro enables interrupts in the HDMI RX timer peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_TmrIntrEnable(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_CfgInitialize.
XV_HdmiRx1_Tmr1IntrDisable
This macro disables interrupt in the HDMI RX timer peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_Tmr1IntrDisable(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_CfgInitialize.
XV_HdmiRx1_Tmr1Start
This macro starts the HDMI RX timer peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. Value specifies the timer's frequency in number of clockcycles None. C-style signature: void XV_HdmiRx1_Tmr1Start(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_TmrStartMs.
XV_HdmiRx1_GetTmr1Value
This macro reads the HDMI RX timer peripheral's remaining timer counter value.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_GetTmr1Value(XV_HdmiRx1 *InstancePtr)
XV_HdmiRx1_Tmr2Enable
This macro enables the HDMI RX timer peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_Tmr2Enable(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_CfgInitialize.
XV_HdmiRx1_Tmr2Disable
This macro disables the HDMI RX timer peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_Tmr2Disable(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_CfgInitialize.
XV_HdmiRx1_Tmr2IntrEnable
This macro enables interrupts in the HDMI RX timer peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_Tmr2IntrEnable(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_CfgInitialize.
XV_HdmiRx1_Tmr2IntrDisable
This macro disables interrupt in the HDMI RX timer peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_Tmr2IntrDisable(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_CfgInitialize.
XV_HdmiRx1_Tmr2Start
This macro starts the HDMI RX timer peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. Value specifies the timer's frequency in number of clockcycles None. C-style signature: void XV_HdmiRx1_Tmr2Start(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_TmrStartMs.
XV_HdmiRx1_GetTmr2Value
This macro reads the HDMI RX timer peripheral's remaining timer counter value.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_GetTmr2Value(XV_HdmiRx1 *InstancePtr)
XV_HdmiRx1_Tmr3Enable
This macro enables the HDMI RX timer peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_Tmr3Enable(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_CfgInitialize.
XV_HdmiRx1_Tmr3Disable
This macro disables the HDMI RX timer peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_Tmr3Disable(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_CfgInitialize, XV_HdmiRx1_Clear.
XV_HdmiRx1_Tmr3IntrEnable
This macro enables interrupts in the HDMI RX timer peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_Tmr3IntrEnable(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_CfgInitialize.
XV_HdmiRx1_Tmr3IntrDisable
This macro disables interrupt in the HDMI RX timer peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_Tmr3IntrDisable(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_CfgInitialize.
XV_HdmiRx1_Tmr3Start
This macro starts the HDMI RX timer peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. Value specifies the timer's frequency in number of clockcycles None. C-style signature: void XV_HdmiRx1_Tmr3Start(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_TmrStartMs.
XV_HdmiRx1_GetTmr3Value
This macro reads the HDMI RX timer peripheral's remaining timer counter value.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_GetTmr3Value(XV_HdmiRx1 *InstancePtr)
XV_HdmiRx1_Tmr4Enable
This macro enables the HDMI RX timer peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_Tmr4Enable(XV_HdmiRx1 *InstancePtr)
XV_HdmiRx1_Tmr4Disable
This macro disables the HDMI RX timer peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_Tmr4Disable(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_CfgInitialize.
XV_HdmiRx1_Tmr4IntrEnable
This macro enables interrupts in the HDMI RX timer peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_Tmr4IntrEnable(XV_HdmiRx1 *InstancePtr)
XV_HdmiRx1_Tmr4IntrDisable
This macro disables interrupt in the HDMI RX timer peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_Tmr4IntrDisable(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_CfgInitialize.
XV_HdmiRx1_Tmr4Start
This macro starts the HDMI RX timer peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. Value specifies the timer's frequency in number of clockcycles None. C-style signature: void XV_HdmiRx1_Tmr4Start(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_TmrStartMs.
XV_HdmiRx1_GetTmr4Value
This macro reads the HDMI RX timer peripheral's remaining timer counter value.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_GetTmr4Value(XV_HdmiRx1 *InstancePtr)
XV_HdmiRx1_VtdEnable
This macro enables the HDMI RX Timing Detector peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_VtdEnable(XV_HdmiRx1 *InstancePtr)
XV_HdmiRx1_VtdDisable
This macro disables the HDMI RX Timing Detector peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_VtdDisable(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_CfgInitialize.
XV_HdmiRx1_VtdIntrEnable
This macro enables interrupt in the HDMI RX Timing Detector peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_VtdIntrEnable(XV_HdmiRx1 *InstancePtr)
XV_HdmiRx1_VtdIntrDisable
This macro disables interrupt in the HDMI RX Timing Detector peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_VtdIntrDisable(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_CfgInitialize.
XV_HdmiRx1_VtdVfpEvent
This macro allow control to enable/disable the HDMI RX VFP event.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. SetClr specifies TRUE/FALSE value to either enable or disable the VFP Event None. C-style signature: void XV_HdmiRx1_VtdVfpEvent(XV_HdmiRx1 *InstancePtr, u8 SetClr)
XV_HdmiRx1_VtdSetTimebase
This macro sets the timebase in the HDMI RX Timing Detector peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. Value specifies the timer's frequency in number of clockcycles None. C-style signature: void XV_HdmiRx1_VtdSetTimebase(XV_HdmiRx1 *InstancePtr, Value)
Referenced by XV_HdmiRx1_CfgInitialize.
XV_HdmiRx1_DdcEnable
This macro enables the HDMI RX Display Data Channel (DDC) peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_DdcEnable(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_CfgInitialize.
XV_HdmiRx1_DdcScdcEnable
This macro enables the SCDC in the DDC peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_DdcScdcEnable(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_CfgInitialize.
XV_HdmiRx1_DdcHdcpEnable
This macro enables the HDCP in the DDC peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_DdcHdcpEnable(XV_HdmiRx1 *InstancePtr)
XV_HdmiRx1_DdcHdcpDisable
This macro disables the HDCP in the DDC peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. C-style signature: void XV_HdmiRx1_DdcHdcpEnable(XV_HdmiRx1 *InstancePtr)
XV_HdmiRx1_DdcHdcp14Mode
This macro sets the DDC peripheral into HDCP 1.4 mode.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_DdcHdcp14Mode(XV_HdmiRx1 *InstancePtr)
XV_HdmiRx1_DdcHdcp22Mode
This macro sets the DDC peripheral into HDCP 2.2 mode.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_DdcHdcp22Mode(XV_HdmiRx1 *InstancePtr)
XV_HdmiRx1_DdcDisable
This macro disables the HDMI RX Display Data Channel (DDC) peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_DdcDisable(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_CfgInitialize.
XV_HdmiRx1_DdcIntrEnable
This macro enables interrupts in the HDMI RX Display Data Channel (DDC) peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_DdcIntrEnable(XV_HdmiRx1 *InstancePtr)
XV_HdmiRx1_DdcIntrDisable
This macro disables interrupts in the HDMI RX Display Data Channel (DDC) peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_DdcIntrDisable(XV_HdmiRx1 *InstancePtr)
XV_HdmiRx1_DdcScdcClear
This macro clears the SCDC registers in the DDC peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_DdcScdcClear(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_CfgInitialize.
XV_HdmiRx1_AuxEnable
This macro enables the HDMI RX Auxiliary (AUX) peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_AuxEnable(XV_HdmiRx1 *InstancePtr)
XV_HdmiRx1_AuxDisable
This macro disables the HDMI RX Auxiliary (AUX) peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_AuxDisable(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_CfgInitialize.
XV_HdmiRx1_AuxIntrEnable
This macro enables interrupts in the HDMI RX Auxiliary (AUX) peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_AuxIntrEnable(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_CfgInitialize.
XV_HdmiRx1_AuxIntrDisable
This macro disables interrupts in the HDMI RX Auxiliary (AUX) peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_AuxIntrDisable(XV_HdmiRx1 *InstancePtr)
XV_HdmiRx1_AuxFSyncVrrChEvtEnable
This macro enables FSync/VRR event interrupt in the HDMI RX Auxiliary (AUX) peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_AuxFSyncVrrChEvtEnable(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_CfgInitialize.
XV_HdmiRx1_AuxFSyncVrrChEvtDisable
This macro disables FSync/VRR event interrupt in the HDMI RX Auxiliary (AUX) peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_AuxFSyncVrrChEvtDisable(XV_HdmiRx1 *InstancePtr)
XV_HdmiRx1_AudioEnable
This macro enables the HDMI RX Audio (AUD) peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_AudioEnable(XV_HdmiRx1 *InstancePtr)
XV_HdmiRx1_AudioDisable
This macro disables the HDMI RX Audio (AUD) peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_AudioDisable(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_CfgInitialize.
XV_HdmiRx1_AudioIntrEnable
This macro enables interrupts in the HDMI RX Audio (AUD) peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_AudioIntrEnable(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_CfgInitialize.
XV_HdmiRx1_AudioIntrDisable
This macro disables interrupts in the HDMI RX Audio (AUD) peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_AudioIntrDisable(XV_HdmiRx1 *InstancePtr)
XV_HdmiRx1_SetAudioAcrUpdateEventEn
This macro enables ACR Update Event in the HDMI RX Audio (AUD) peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None.
XV_HdmiRx1_ClearAudioAcrUpdateEventEn
This macro disables ACR Update Event in the HDMI RX Audio (AUD) peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None.
XV_HdmiRx1_LnkstaEnable
This macro enables the HDMI RX Link Status (LNKSTA) peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_LinkstaEnable(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_CfgInitialize.
XV_HdmiRx1_LnkstaDisable
This macro disables the HDMI RX Link Status (LNKSTA) peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_LinkstaDisable(XV_HdmiRx1 *InstancePtr)
Referenced by XV_HdmiRx1_CfgInitialize.
XV_HdmiRx1_LinkIntrEnable
This macro enables interrupt in the HDMI RX Link Status (LNKSTA) peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_LinkIntrEnable(XV_HdmiRx1 *InstancePtr)
XV_HdmiRx1_LinkIntrDisable
This macro disable interrupt in the HDMI RX Link Status (LNKSTA) peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_LinkIntrDisable(XV_HdmiRx1 *InstancePtr)
XV_HdmiRx1_IsAudioActive
This macro returns true is the audio stream is active else false.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. TRUE if the audio stream is active, FALSE if it is not. C-style signature: u32 XV_HdmiRx1_IsAudioActive(XV_HdmiRx1 *InstancePtr)
XV_HdmiRx1_GetAudioChannels
This macro returns the number of active audio channels.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. Number of active audio channels. C-style signature: u32 XV_HdmiRx1_GetAudioChannels(XV_HdmiRx1 *InstancePtr)
XV_HdmiRx1_DdcHdcpClearWriteMessageBuffer
This macro clears the HDCP write message buffer in the DDC peripheral.
InstancePtr is a pointer to the XHdmi_Rx core instance. None. C-style signature: void XHdmiRx1_DdcHdcpClearWriteMessageBuffer(XHdmi_Rx *InstancePtr)
XV_HdmiRx1_DdcHdcpClearReadMessageBuffer
This macro clears the HDCP read message buffer in the DDC peripheral.
InstancePtr is a pointer to the XHdmi_Rx core instance. None. C-style signature: void XHdmiRx1_DdcHdcpClearReadMessageBuffer(XHdmi_Rx *InstancePtr)
XV_HdmiRx1_DynHDR_DM_Enable
This macro enables the data mover for Dynamic HDR.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_DynHDR_DM_Enable(XV_HdmiRx1 *InstancePtr)
XV_HdmiRx1_DynHDR_DM_Disable
This macro disables the data mover for Dynamic HDR.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. C-style signature: void XV_HdmiRx1_DynHDR_DM_Disable(XV_HdmiRx1 *InstancePtr)
typedef void(* XV_HdmiRx1_Callback)(void *CallbackRef))(void *CallbackRef)
Callback type for interrupt.
CallbackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. None. None.
typedef void(* XV_HdmiRx1_HdcpCallback)(void *CallbackRef, int Data))(void *CallbackRef, int Data)
Callback type for interrupt.
CallbackRef is a callback reference passed in by the upper layer when setting the callback functions, and passed back to the upper layer when the callback is invoked. Data is a type of HDCP event None. None.
XV_HdmiRx1_Config* XV_HdmiRx1_LookupConfig(UINTPTR BaseAddress)
This function returns a reference to an XV_HdmiRx1_Config structure based on the core id, DeviceId.
The return value will refer to an entry in the device configuration table defined in the xv_hdmirx1_g.c file. DeviceId is the unique core ID of the HDMI RX core for the lookup operation. XV_HdmiRx1_LookupConfig returns a reference to a config record in the configuration table (in xv_hdmirx1_g.c) corresponding to DeviceId, or NULL if no match is found. None.
int XV_HdmiRx1_CfgInitialize(XV_HdmiRx1 *InstancePtr, XV_HdmiRx1_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the HDMI RX core.
This function must be called prior to using the HDMI RX core. Initialization of the HDMI RX includes setting up the instance data, and ensuring the hardware is in a quiescent state. InstancePtr is a pointer to the XHdmiRx1 core instance. CfgPtr points to the configuration structure associated with the HDMI RX core. EffectiveAddr is the base address of the device. If address translation is being used, then this parameter must reflect the virtual base address. Otherwise, the physical address should be used. XST_SUCCESS if XV_HdmiRx1_CfgInitialize was successful.XST_FAILURE if HDMI RX PIO ID mismatched. None.
References XV_HdmiRx1::AudCallback, XV_HdmiRx1::AuxCallback, XV_HdmiRx1_Config::BaseAddress, XV_HdmiRx1::Config, XV_HdmiRx1::ConnectCallback, XV_HdmiRx1::DdcCallback, XV_HdmiRx1_Config::DSC, XV_HdmiRx1::FrlConfigCallback, XV_HdmiRx1::FrlStartCallback, XV_HdmiRx1::HdcpCallback, XV_HdmiRx1::HdcpRef, XV_HdmiRx1::IsReady, XV_HdmiRx1::LinkErrorCallback, XV_HdmiRx1::LnkStaCallback, XV_HdmiRx1::ModeCallback, XV_HdmiRx1::Stream, XV_HdmiRx1::StreamDownCallback, XV_HdmiRx1::StreamInitCallback, XV_HdmiRx1::StreamUpCallback, XV_HdmiRx1::SyncLossCallback, XV_HdmiRx1::TmdsClkRatioCallback, XV_HdmiRx1::TmdsConfigCallback, XV_HdmiRx1_AudioDisable, XV_HdmiRx1_AudioIntrEnable, XV_HdmiRx1_AuxDisable, XV_HdmiRx1_AuxFSyncVrrChEvtEnable, XV_HdmiRx1_AuxIntrEnable, XV_HdmiRx1_Clear, XV_HdmiRx1_DdcDisable, XV_HdmiRx1_DdcEnable, XV_HdmiRx1_DdcScdcClear, XV_HdmiRx1_DdcScdcEnable, XV_HdmiRx1_FrlDdcWriteField, XV_HdmiRx1_FrlScdcInit, XV_HdmiRx1_GetTime16Ms, XV_HdmiRx1_LnkstaDisable, XV_HdmiRx1_LnkstaEnable, XV_HDMIRX1_MASK_16, XV_HDMIRX1_PIO_ID, XV_HDMIRX1_PIO_ID_OFFSET, XV_HDMIRX1_PIO_IN_BRDG_OVERFLOW_MASK, XV_HDMIRX1_PIO_IN_DET_MASK, XV_HDMIRX1_PIO_IN_DSC_EN_STRM_CHG_EVT_MASK, XV_HDMIRX1_PIO_IN_DSC_PPS_PKT_ERR_MASK, XV_HDMIRX1_PIO_IN_EVT_FE_OFFSET, XV_HDMIRX1_PIO_IN_EVT_RE_OFFSET, XV_HDMIRX1_PIO_IN_LNK_RDY_MASK, XV_HDMIRX1_PIO_IN_MODE_MASK, XV_HDMIRX1_PIO_IN_SCDC_SCRAMBLER_ENABLE_MASK, XV_HDMIRX1_PIO_IN_SCDC_TMDS_CLOCK_RATIO_MASK, XV_HDMIRX1_PIO_IN_VID_RDY_MASK, XV_HdmiRx1_PioDisable, XV_HdmiRx1_PioIntrDisable, XV_HdmiRx1_ReadReg, XV_HdmiRx1_SetHpd, XV_HDMIRX1_SHIFT_16, XV_HdmiRx1_Tmr1Disable, XV_HdmiRx1_Tmr1Enable, XV_HdmiRx1_Tmr1IntrDisable, XV_HdmiRx1_Tmr1IntrEnable, XV_HdmiRx1_Tmr2Disable, XV_HdmiRx1_Tmr2Enable, XV_HdmiRx1_Tmr2IntrDisable, XV_HdmiRx1_Tmr2IntrEnable, XV_HdmiRx1_Tmr3Disable, XV_HdmiRx1_Tmr3Enable, XV_HdmiRx1_Tmr3IntrDisable, XV_HdmiRx1_Tmr3IntrEnable, XV_HdmiRx1_Tmr4Disable, XV_HdmiRx1_Tmr4IntrDisable, XV_HdmiRx1_VtdDisable, XV_HdmiRx1_VtdIntrDisable, XV_HdmiRx1_VtdSetTimebase, XV_HdmiRx1_WriteReg.
void XV_HdmiRx1_SetAxiClkFreq(XV_HdmiRx1 *InstancePtr, u32 ClkFreq)
This function sets the AXI4-Lite Clock Frequency.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. ClkFreq specifies the value that needs to be set. This is required after a reset or init.
References XV_HdmiRx1::Config.
void XV_HdmiRx1_Clear(XV_HdmiRx1 *InstancePtr)
This function clears the HDMI RX variables and sets them to the defaults.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. This is required after a reset or init.
References XV_HdmiRx1_AudioStream::Active, XV_HdmiRx1::AudCts, XV_HdmiRx1::AudFormat, XV_HdmiRx1::AudN, XV_HdmiRx1::Aux, XV_HdmiRx1_AudioStream::Channels, XV_HdmiRx1::IsErrorPrintCount, XV_HdmiRx1::Stream, XV_HdmiRx1::StreamDownCallback, XV_HdmiRx1::StreamDownRef, XV_HDMIRX1_STATE_STREAM_DOWN, XV_HdmiRx1_Tmr3Disable.
Referenced by XV_HdmiRx1_CfgInitialize.
int XV_HdmiRx1_SetStream(XV_HdmiRx1 *InstancePtr, XVidC_PixelsPerClock Ppc, u32 Clock)
This function sets the HDMI RX stream parameters.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. Ppc specifies the pixel per clock. 4 = XVIDC_PPC_4 Clock specifies reference pixel clock frequency. XST_SUCCESS is always returned. None.
References XV_HdmiRx1::Stream, XV_HdmiRx1_SetPixelRate.
int XV_HdmiRx1_IsStreamUp(XV_HdmiRx1 *InstancePtr)
This function provides status of the stream.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. TRUE = Stream is up.FALSE = Stream is down. None.
References XV_HdmiRx1::Stream, XV_HDMIRX1_STATE_STREAM_UP.
int XV_HdmiRx1_IsStreamScrambled(XV_HdmiRx1 *InstancePtr)
This function provides the stream scrambler status.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. TRUE = Stream is scrambled.FALSE = Stream is not scrambled. None.
References XV_HdmiRx1::Stream.
int XV_HdmiRx1_IsStreamConnected(XV_HdmiRx1 *InstancePtr)
This function provides the stream connected status.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. TRUE = Stream is connected.FALSE = Stream is connected. None.
References XV_HdmiRx1::Stream.
int XV_HdmiRx1_SetHpd(XV_HdmiRx1 *InstancePtr, u8 SetClr)
This function enables/clear Hot-Plug-Detect.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. SetClr specifies TRUE/FALSE value to either enable or clear HPD respectively. XST_SUCCESS is always returned. None.
References XV_HdmiRx1_Config::BaseAddress, XV_HdmiRx1::Config, XV_HDMIRX1_PIO_OUT_CLR_OFFSET, XV_HDMIRX1_PIO_OUT_HPD_MASK, XV_HDMIRX1_PIO_OUT_SET_OFFSET, XV_HdmiRx1_WriteReg.
Referenced by XV_HdmiRx1_CfgInitialize.
void XV_HdmiRx1_INT_VRST(XV_HdmiRx1 *InstancePtr, u8 Reset)
This function asserts or releases the HDMI RX Internal VRST.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. Reset specifies TRUE/FALSE value to either assert or release HDMI RX Internal VRST. None. The reset output of the PIO is inverted. When the system is in reset, the PIO output is cleared and this will reset the HDMI RX. Therefore, clearing the PIO reset output will assert the HDMI Internal video reset. C-style signature: void XV_HdmiRx1_INT_VRST(XV_HdmiRx1 *InstancePtr, u8 Reset)
References XV_HDMIRX1_PIO_OUT_CLR_OFFSET, XV_HDMIRX1_PIO_OUT_INT_VRST_MASK, XV_HDMIRX1_PIO_OUT_SET_OFFSET, XV_HdmiRx1_WriteReg.
void XV_HdmiRx1_INT_LRST(XV_HdmiRx1 *InstancePtr, u8 Reset)
This function asserts or releases the HDMI RX Internal LRST.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. Reset specifies TRUE/FALSE value to either assert or release HDMI RX Internal LRST. None. The reset output of the PIO is inverted. When the system is in reset, the PIO output is cleared and this will reset the HDMI RX. Therefore, clearing the PIO reset output will assert the HDMI Internal link reset. C-style signature: void XV_HdmiRx1_INT_VRST(XV_HdmiRx1 *InstancePtr, u8 Reset)
References XV_HDMIRX1_PIO_OUT_CLR_OFFSET, XV_HDMIRX1_PIO_OUT_INT_LRST_MASK, XV_HDMIRX1_PIO_OUT_SET_OFFSET, XV_HdmiRx1_WriteReg.
void XV_HdmiRx1_EXT_VRST(XV_HdmiRx1 *InstancePtr, u8 Reset)
This function asserts or releases the HDMI RX External VRST.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. Reset specifies TRUE/FALSE value to either assert or release HDMI RX External VRST. None. The reset output of the PIO is inverted. When the system is in reset, the PIO output is cleared and this will reset the HDMI RX. Therefore, clearing the PIO reset output will assert the HDMI external video reset. C-style signature: void XV_HdmiRx1_EXT_VRST(XV_HdmiRx1 *InstancePtr, u8 Reset)
References XV_HDMIRX1_PIO_OUT_CLR_OFFSET, XV_HDMIRX1_PIO_OUT_EXT_VRST_MASK, XV_HDMIRX1_PIO_OUT_SET_OFFSET, XV_HdmiRx1_WriteReg.
void XV_HdmiRx1_EXT_SYSRST(XV_HdmiRx1 *InstancePtr, u8 Reset)
This function asserts or releases the HDMI RX External SYSRST.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. Reset specifies TRUE/FALSE value to either assert or release HDMI RX External SYSRST. None. The reset output of the PIO is inverted. When the system is in reset, the PIO output is cleared and this will reset the HDMI RX. Therefore, clearing the PIO reset output will assert the HDMI External system reset. C-style signature: void XV_HdmiRx1_EXT_SYSRST(XV_HdmiRx1 *InstancePtr, u8 Reset)
References XV_HDMIRX1_PIO_OUT_CLR_OFFSET, XV_HDMIRX1_PIO_OUT_EXT_SYSRST_MASK, XV_HDMIRX1_PIO_OUT_SET_OFFSET, XV_HdmiRx1_WriteReg.
int XV_HdmiRx1_SetPixelRate(XV_HdmiRx1 *InstancePtr)
This function sets the pixel rate.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. XST_SUCCESS is always returned. None.
References XV_HdmiRx1_Config::BaseAddress, XV_HdmiRx1::Config, XV_HdmiRx1::Stream, XV_HDMIRX1_PIO_OUT_MSK_OFFSET, XV_HDMIRX1_PIO_OUT_OFFSET, XV_HDMIRX1_PIO_OUT_PIXEL_RATE_MASK, XV_HDMIRX1_PIO_OUT_PIXEL_RATE_SHIFT, XV_HdmiRx1_WriteReg.
Referenced by XV_HdmiRx1_SetStream.
void XV_HdmiRx1_SetColorFormat(XV_HdmiRx1 *InstancePtr)
This function sets the color format.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. None.
References XV_HdmiRx1_Config::BaseAddress, XV_HdmiRx1::Config, XV_HdmiRx1::Stream, XV_HDMIRX1_PIO_OUT_COLOR_SPACE_MASK, XV_HDMIRX1_PIO_OUT_COLOR_SPACE_SHIFT, XV_HDMIRX1_PIO_OUT_MSK_OFFSET, XV_HDMIRX1_PIO_OUT_OFFSET, XV_HdmiRx1_WriteReg.
int XV_HdmiRx1_IsLinkStatusErrMax(XV_HdmiRx1 *InstancePtr)
This function provides status of one of the link error counters reached the maximum value.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. TRUE = Maximum error counter reached.FALSE = Maximum error counter not reached. None.
References XV_HdmiRx1_Config::BaseAddress, XV_HdmiRx1::Config, XV_HDMIRX1_LNKSTA_STA_ERR_MAX_MASK, XV_HDMIRX1_LNKSTA_STA_OFFSET, XV_HdmiRx1_ReadReg.
void XV_HdmiRx1_ClearLinkStatus(XV_HdmiRx1 *InstancePtr)
This function clears the link error counters.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. None.
References XV_HdmiRx1_Config::BaseAddress, XV_HdmiRx1::Config, XV_HDMIRX1_LNKSTA_CTRL_CLR_OFFSET, XV_HDMIRX1_LNKSTA_CTRL_ERR_CLR_MASK, XV_HDMIRX1_LNKSTA_CTRL_SET_OFFSET, XV_HdmiRx1_WriteReg.
u32 XV_HdmiRx1_GetLinkStatus(XV_HdmiRx1 *InstancePtr, u8 Type)
This function provides status of the HDMI RX core Link Status peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. Type specifies one of the type for which status to be provided: 0 = Link error counter for channel 0.1 = Link error counter for channel 1.2 = Link error counter for channel 2. Link status of the HDMI RX core link. None.
References XV_HdmiRx1_Config::BaseAddress, XV_HdmiRx1::Config, XV_HDMIRX1_LNKSTA_LNK_ERR0_OFFSET, XV_HdmiRx1_ReadReg.
u32 XV_HdmiRx1_GetAcrCts(XV_HdmiRx1 *InstancePtr)
This function provides audio clock regenerating CTS (Cycle-Time Stamp) value at the HDMI sink device.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. Audio clock CTS value. None.
References XV_HdmiRx1_Config::BaseAddress, XV_HdmiRx1::Config, XV_HDMIRX1_AUD_CTS_OFFSET, XV_HdmiRx1_ReadReg.
u32 XV_HdmiRx1_GetAcrN(XV_HdmiRx1 *InstancePtr)
This function provides audio clock regenerating factor N value.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. ACR N value. None.
References XV_HdmiRx1_Config::BaseAddress, XV_HdmiRx1::Config, XV_HDMIRX1_AUD_N_OFFSET, XV_HdmiRx1_ReadReg.
int XV_HdmiRx1_DdcLoadEdid(XV_HdmiRx1 *InstancePtr, u8 *Data, u16 Length)
This function loads the EDID data into the DDC slave.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. EdidData is a pointer to the EDID data array. Length is the length, in bytes, of the EDID array. XST_SUCCESS if the EDID data was loaded successfullyXST_FAILURE if the EDID data load failed None.
References XV_HdmiRx1_Config::BaseAddress, XV_HdmiRx1::Config, XV_HDMIRX1_DDC_CTRL_EDID_EN_MASK, XV_HDMIRX1_DDC_CTRL_SET_OFFSET, XV_HDMIRX1_DDC_EDID_DATA_OFFSET, XV_HDMIRX1_DDC_EDID_WP_OFFSET, XV_HdmiRx1_DdcGetEdidWords, XV_HdmiRx1_WriteReg.
void XV_HdmiRx1_DdcHdcpSetAddress(XV_HdmiRx1 *InstancePtr, u32 Addr)
This function sets the HDCP address in the DDC peripheral.
This is implemented as a function and not a macro, so the HDCP driver can bind the function call with a handler. InstancePtr is a pointer to the XHdmi_Rx core instance. Address is the HDCP address. None. C-style signature: void XHdmiRx1_DdcHdcpSetAddress(XHdmi_Rx *InstancePtr, u8 Address)
References XV_HDMIRX1_DDC_HDCP_ADDRESS_OFFSET, XV_HdmiRx1_WriteReg.
void XV_HdmiRx1_DdcHdcpWriteData(XV_HdmiRx1 *InstancePtr, u32 Data)
This function writes HDCP data in the DDC peripheral.
This is implemented as a function and not a macro, so the HDCP driver can bind the function call with a handler. InstancePtr is a pointer to the XHdmi_Rx core instance. Data is the HDCP data to be written. None. C-style signature: void XHdmiRx1_DdcHdcpWriteData(XHdmi_Rx *InstancePtr, u8 Data)
References XV_HDMIRX1_DDC_HDCP_DATA_OFFSET, XV_HdmiRx1_WriteReg.
u32 XV_HdmiRx1_DdcHdcpReadData(XV_HdmiRx1 *InstancePtr)
This function reads HDCP data from the DDC peripheral.
This is implemented as a function and not a macro, so the HDCP driver can bind the function call with a handler. InstancePtr is a pointer to the XHdmi_Rx core instance. Returns the HDCP data read from the DDC peripheral. C-style signature: u32 XHdmiRx1_DdcHdcpReadData(XHdmi_Rx *InstancePtr)
References XV_HDMIRX1_DDC_HDCP_DATA_OFFSET, XV_HdmiRx1_ReadReg.
u16 XV_HdmiRx1_DdcGetHdcpWriteMessageBufferWords(XV_HdmiRx1 *InstancePtr)
This function gets the number of bytes of the HDCP 2.2 write buffer in the DDC slave.
InstancePtr is a pointer to the XHdmi_Rx core instance. HDCP 2.2 write buffer words None.
References XV_HdmiRx1_Config::BaseAddress, XV_HdmiRx1::Config, XV_HDMIRX1_DDC_HDCP_STA_OFFSET, XV_HDMIRX1_DDC_STA_HDCP_WMSG_WORDS_MASK, XV_HDMIRX1_DDC_STA_HDCP_WMSG_WORDS_SHIFT, XV_HdmiRx1_ReadReg.
int XV_HdmiRx1_DdcIsHdcpWriteMessageBufferEmpty(XV_HdmiRx1 *InstancePtr)
This function returns the status of the HDCP 2.2 write buffer in the DDC slave.
InstancePtr is a pointer to the XHdmi_Rx core instance. TRUE = HDCP 2.2 message buffer is empty.FALSE = HDCP 2.2 message buffer contains data. None.
References XV_HdmiRx1_Config::BaseAddress, XV_HdmiRx1::Config, XV_HDMIRX1_DDC_HDCP_STA_OFFSET, XV_HDMIRX1_DDC_STA_HDCP_WMSG_EP_MASK, XV_HdmiRx1_ReadReg.
u16 XV_HdmiRx1_DdcGetHdcpReadMessageBufferWords(XV_HdmiRx1 *InstancePtr)
This function gets the number of bytes of the HDCP 2.2 read buffer in the DDC slave.
InstancePtr is a pointer to the XHdmi_Rx core instance. HDCP 2.2 read buffer words None.
References XV_HdmiRx1_Config::BaseAddress, XV_HdmiRx1::Config, XV_HDMIRX1_DDC_HDCP_STA_OFFSET, XV_HDMIRX1_DDC_STA_HDCP_RMSG_WORDS_MASK, XV_HDMIRX1_DDC_STA_HDCP_RMSG_WORDS_SHIFT, XV_HdmiRx1_ReadReg.
int XV_HdmiRx1_DdcIsHdcpReadMessageBufferEmpty(XV_HdmiRx1 *InstancePtr)
This function returns the status of the HDCP 2.2 read message buffer in the DDC slave.
InstancePtr is a pointer to the XHdmi_Rx core instance. TRUE = HDCP 2.2 message buffer is empty.FALSE = HDCP 2.2 message buffer contains data. None.
References XV_HdmiRx1_Config::BaseAddress, XV_HdmiRx1::Config, XV_HDMIRX1_DDC_HDCP_STA_OFFSET, XV_HDMIRX1_DDC_STA_HDCP_RMSG_EP_MASK, XV_HdmiRx1_ReadReg.
int XV_HdmiRx1_GetTmdsClockRatio(XV_HdmiRx1 *InstancePtr)
This function gets the SCDC TMDS clock ratio bit.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. TRUE = TMDS clock ratio bit is set.FALSE = TMDS clock ratio bit is cleared. None.
References XV_HdmiRx1_Config::BaseAddress, XV_HdmiRx1::Config, XV_HDMIRX1_PIO_IN_OFFSET, XV_HDMIRX1_PIO_IN_SCDC_TMDS_CLOCK_RATIO_MASK, XV_HdmiRx1_ReadReg.
u8 XV_HdmiRx1_GetAviVic(XV_HdmiRx1 *InstancePtr)
This function returns the AVI VIC (captured by the AUX peripheral)
InstancePtr is a pointer to the XV_HdmiRx1 core instance. The AVI VIC code. None.
References XV_HdmiRx1_Config::BaseAddress, XV_HdmiRx1::Config, XV_HDMIRX1_AUX_STA_AVI_VIC_MASK, XV_HDMIRX1_AUX_STA_AVI_VIC_SHIFT, XV_HDMIRX1_AUX_STA_OFFSET, XV_HdmiRx1_ReadReg.
Referenced by XV_HdmiRx1_GetVideoProperties.
XVidC_ColorFormat XV_HdmiRx1_GetAviColorSpace(XV_HdmiRx1 *InstancePtr)
This function returns the AVI colorspace (captured by the AUX peripheral)
InstancePtr is a pointer to the XV_HdmiRx1 core instance. The AVI colorspace value. None.
References XV_HdmiRx1_Config::BaseAddress, XV_HdmiRx1::Config, XV_HDMIRX1_AUX_STA_AVI_CS_MASK, XV_HDMIRX1_AUX_STA_AVI_CS_SHIFT, XV_HDMIRX1_AUX_STA_OFFSET, XV_HdmiRx1_ReadReg.
Referenced by XV_HdmiRx1_GetVideoProperties.
XVidC_ColorDepth XV_HdmiRx1_GetGcpColorDepth(XV_HdmiRx1 *InstancePtr)
This function returns the GCP color depth (captured by the AUX peripheral)
InstancePtr is a pointer to the XV_HdmiRx1 core instance. The GCP color depth. None.
References XV_HdmiRx1_Config::BaseAddress, XV_HdmiRx1::Config, XV_HDMIRX1_AUX_STA_GCP_CD_MASK, XV_HDMIRX1_AUX_STA_GCP_CD_SHIFT, XV_HDMIRX1_AUX_STA_OFFSET, XV_HdmiRx1_ReadReg.
Referenced by XV_HdmiRx1_GetVideoProperties.
int XV_HdmiRx1_GetVideoProperties(XV_HdmiRx1 *InstancePtr)
This function reads the video properties from the aux peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None.
References XV_HdmiRx1_Config::BaseAddress, XV_HdmiRx1::Config, XV_HdmiRx1::Stream, XV_HDMIRX1_AUX_STA_AVI_MASK, XV_HDMIRX1_AUX_STA_OFFSET, XV_HdmiRx1_GetAviColorSpace, XV_HdmiRx1_GetAviVic, XV_HdmiRx1_GetGcpColorDepth, XV_HdmiRx1_ReadReg.
int XV_HdmiRx1_GetVideoTiming(XV_HdmiRx1 *InstancePtr)
This function reads the video timing from the VTD peripheral.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. Calculates video timing and returns video timing parameters structure None.
References XV_HdmiRx1_Config::BaseAddress, XV_HdmiRx1::Config, XV_HdmiRx1::Stream, XV_HdmiRx1::VrrIF, XV_HdmiRx1_DSC_IsEnableStream, XV_HdmiRx1_ReadReg, XV_HDMIRX1_VTD_ACT_LIN_OFFSET, XV_HDMIRX1_VTD_ACT_PIX_OFFSET, XV_HDMIRX1_VTD_HBP_OFFSET, XV_HDMIRX1_VTD_HFP_OFFSET, XV_HDMIRX1_VTD_HSW_OFFSET, XV_HDMIRX1_VTD_STA_FMT_MASK, XV_HDMIRX1_VTD_STA_HS_POL_MASK, XV_HDMIRX1_VTD_STA_OFFSET, XV_HDMIRX1_VTD_STA_VS_POL_MASK, XV_HDMIRX1_VTD_TOT_LIN_OFFSET, XV_HDMIRX1_VTD_TOT_PIX_OFFSET, XV_HDMIRX1_VTD_VBP_OFFSET, XV_HDMIRX1_VTD_VFP_OFFSET, XV_HDMIRX1_VTD_VSW_OFFSET.
u32 XV_HdmiRx1_Divide(u32 Dividend, u32 Divisor)
This function calculates the divider for the frame calculation.
Dividend is the dividend value to use in the calculation. Divisor is the divisor value to use in the calculation. The result of the calculation. None.
void XV_HdmiRx1_SetPixelClk(XV_HdmiRx1 *InstancePtr)
This function sets the PixelClk based on the current ColorDepth, RefClk and ColorFormatId.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None.
References XV_HdmiRx1::Stream.
void XV_HdmiRx1_Start(XV_HdmiRx1 *InstancePtr)
This function starts the HDMI RX core.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. This is required after a reset or initialization.
References XV_HdmiRx1_PioEnable, XV_HdmiRx1_PioIntrEnable.
void XV_HdmiRx1_Stop(XV_HdmiRx1 *InstancePtr)
This function stops the HDMI RX core.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None.
References XV_HdmiRx1_PioDisable, XV_HdmiRx1_PioIntrDisable.
void XV_HdmiRx1_UpdateEdFlags(XV_HdmiRx1 *InstancePtr)
This function checks if RX's CED or RSED counters are incrementing at the rate of 4 or higher per second or if they first hit the maximum value (0x7FFF) then set the CED_Update or RSED_Update SCDC flags if true.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. This function needs to be called every 1 second to comply with the spec on CED_Update and RSED_Update flags updating.
References XV_HdmiRx1::Stream, XV_HdmiRx1_FrlDdcReadField, XV_HdmiRx1_FrlDdcWriteField.
void XV_HdmiRx1_TmrStartMs(XV_HdmiRx1 *InstancePtr, u32 Milliseconds, u8 TimerSelect)
This function sets the timer of RX Core.
InstancePtr is a pointer to the XHdmi_Rx core instance. Milliseconds specifies the timer's frequency (in milliseconds) TimerSelect selects which of the timer unit to be used None. None.
References XV_HdmiRx1::Config, XV_HdmiRx1_Tmr1Start, XV_HdmiRx1_Tmr2Start, XV_HdmiRx1_Tmr3Start, XV_HdmiRx1_Tmr4Start.
XVidC_VideoMode XV_HdmiRx1_LookupVmId(u8 Vic)
This function searches for the video mode based on the vic.
Vic Vic defined in the VIC table. None.
void XV_HdmiRx1_ParseSrcProdDescInfoframe(XV_HdmiRx1 *InstancePtr)
This function Parses the Source Product Descriptor (SPD) InfoFrame to extract FreeSync and FreeSync Pro information.
InstancePtr is a pointer to the XHdmiRx1 core instance. None.
References XV_HdmiRx1_Config::BaseAddress, XV_HdmiRx1::Config, XV_HDMIRX1_AUX_FSYNC_ACTIVE_MASK, XV_HDMIRX1_AUX_FSYNC_ENABLED_MASK, XV_HDMIRX1_AUX_FSYNC_MAX_REF_RATE_MASK, XV_HDMIRX1_AUX_FSYNC_MIN_REF_RATE_MASK, XV_HDMIRX1_AUX_FSYNC_OFFSET, XV_HDMIRX1_AUX_FSYNC_PRO_BRIGHT_CTRL_ACT_MASK, XV_HDMIRX1_AUX_FSYNC_PRO_BRIGHT_CTRL_MASK, XV_HDMIRX1_AUX_FSYNC_PRO_BT709_EOTF_MASK, XV_HDMIRX1_AUX_FSYNC_PRO_GAMMA_2_2_EOTF_MASK, XV_HDMIRX1_AUX_FSYNC_PRO_GAMMA_2_6_EOTF_MASK, XV_HDMIRX1_AUX_FSYNC_PRO_LDIMM_CTRL_ACT_MASK, XV_HDMIRX1_AUX_FSYNC_PRO_NTV_CS_ACT_MASK, XV_HDMIRX1_AUX_FSYNC_PRO_OF, XV_HDMIRX1_AUX_FSYNC_PRO_PQ_EOTF_MASK, XV_HDMIRX1_AUX_FSYNC_PRO_SRGB_EOTF_MASK, XV_HDMIRX1_AUX_FSYNC_SUPPORT_MASK, XV_HDMIRX1_AUX_FSYNC_VERSION_MASK, XV_HdmiRx1_GetSrcProdDescIF, XV_HdmiRx1_ReadReg.
void XV_HdmiRx1_ParseVideoTimingExtMetaIF(XV_HdmiRx1 *InstancePtr)
This function reads the VTEM (Video Timing Extended Metadatai) InfoFrame data from the HDMI RX auxiliary register and populates the corresponding fields in the XV_HdmiC_VideoTimingExtMeta structure.
The VTEM InfoFrame provides metadata for features like Variable Refresh Rate (VRR), Quick Media Switching (QMS), and other advanced timing parameters. InstancePtr is a pointer to the XHdmiRx1 core instance. None.
References XV_HdmiRx1_Config::BaseAddress, XV_HdmiRx1::Config, XV_HDMIRX1_AUX_VTEM_BASE_REFRESH_RATE_MASK, XV_HDMIRX1_AUX_VTEM_BASE_VFRONT_MASK, XV_HDMIRX1_AUX_VTEM_FVA_FACT_M1_MASK, XV_HDMIRX1_AUX_VTEM_M_CONST_MASK, XV_HDMIRX1_AUX_VTEM_NEXT_TFR_MASK, XV_HDMIRX1_AUX_VTEM_OFFSET, XV_HDMIRX1_AUX_VTEM_QMS_EN_MASK, XV_HDMIRX1_AUX_VTEM_RB_MASK, XV_HDMIRX1_AUX_VTEM_VRR_EN_MASK, XV_HdmiRx1_GetVidTimingExtMeta, XV_HdmiRx1_ReadReg.
u32 XV_HdmiRx1_FrlDdcReadField(XV_HdmiRx1 *InstancePtr, XV_HdmiRx1_FrlScdcFieldType Field)
This function reads the specified FRL SCDC Field.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. Field specifies the fields from SCDC channels to be written XST_SUCCESSXST_FAILURE None.
References XV_HdmiRx1_Config::BaseAddress, XV_HdmiRx1::Config, XV_HdmiRx1_FrlScdcField::Offset, XV_HDMIRX1_FRL_SCDC_ADDR_MASK, XV_HDMIRX1_FRL_SCDC_DAT_SHIFT, XV_HDMIRX1_FRL_SCDC_OFFSET, XV_HDMIRX1_FRL_SCDC_RD_MASK, XV_HDMIRX1_FRL_SCDC_RDY_MASK, XV_HdmiRx1_ReadReg, XV_HdmiRx1_WriteReg.
Referenced by XV_HdmiRx1_FrlDdcWriteField, XV_HdmiRx1_UpdateEdFlags.
int XV_HdmiRx1_FrlDdcWriteField(XV_HdmiRx1 *InstancePtr, XV_HdmiRx1_FrlScdcFieldType Field, u8 Value)
This function writes the specified FRL SCDC Field.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. Field specifies the fields from SCDC channels to be written Value specifies the values to be written XST_SUCCESSXST_FAILUREXST_DEVICE_BUSY None.
References XV_HdmiRx1_Config::BaseAddress, XV_HdmiRx1::Config, XV_HdmiRx1_FrlScdcField::Mask, XV_HdmiRx1_FrlScdcField::Shift, XV_HDMIRX1_FRL_SCDC_ADDR_MASK, XV_HDMIRX1_FRL_SCDC_DAT_MASK, XV_HDMIRX1_FRL_SCDC_DAT_SHIFT, XV_HDMIRX1_FRL_SCDC_OFFSET, XV_HDMIRX1_FRL_SCDC_RDY_MASK, XV_HDMIRX1_FRL_SCDC_WR_MASK, XV_HdmiRx1_FrlDdcReadField, XV_HdmiRx1_ReadReg, XV_HdmiRx1_WriteReg.
Referenced by XV_HdmiRx1_CfgInitialize, XV_HdmiRx1_DSC_SetDecodeFail, XV_HdmiRx1_DSC_SetDscFrlMax, XV_HdmiRx1_FrlScdcInit, XV_HdmiRx1_UpdateEdFlags.
void XV_HdmiRx1_FrlScdcInit(XV_HdmiRx1 *InstancePtr)
This function initializes FRL-specific SCDC fields that are required for FRL operation.
This should be called separately from the basic SCDC clear operation when FRL is enabled. InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. This function should only be called when FRL is enabled.
References XV_HdmiRx1_FrlDdcWriteField.
Referenced by XV_HdmiRx1_CfgInitialize.
void XV_HdmiRx1_Info(XV_HdmiRx1 *InstancePtr)
This function prints stream and timing information on STDIO/UART console.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. None.
References XV_HdmiRx1::Stream.
void XV_HdmiRx1_DebugInfo(XV_HdmiRx1 *InstancePtr)
This function prints debug information on STDIO/UART console.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. None.
References XV_HdmiRx1_Config::BaseAddress, XV_HdmiRx1::Config, XV_HDMIRX1_DBG_STA_OFFSET, XV_HDMIRX1_LNKSTA_STA_OFFSET, XV_HDMIRX1_PIO_IN_ALIGNER_LOCK_MASK, XV_HDMIRX1_PIO_IN_MODE_MASK, XV_HDMIRX1_PIO_IN_OFFSET, XV_HDMIRX1_PIO_IN_SCRAMBLER_LOCKALLL_MASK, XV_HDMIRX1_PIO_IN_SCRAMBLER_LOCKALLL_SHIFT, XV_HDMIRX1_PKT_ECC_ERR_OFFSET, XV_HdmiRx1_ReadReg, XV_HDMIRX1_SR_SSB_ERR_CNT0_OFFSET, XV_HDMIRX1_SR_SSB_ERR_CNT1_OFFSET, XV_HDMIRX1_SR_SSB_ERR_CNT2_OFFSET, XV_HDMIRX1_SR_SSB_ERR_CNT3_OFFSET, XV_HDMIRX1_TRIB_ANLZ_LN_ACT_ACT_SZ_MASK, XV_HDMIRX1_TRIB_ANLZ_LN_ACT_LN_SZ_MASK, XV_HDMIRX1_TRIB_ANLZ_LN_ACT_LN_SZ_SHIFT, XV_HDMIRX1_TRIB_ANLZ_LN_ACT_OFFSET, XV_HDMIRX1_TRIB_ANLZ_TIM_CHGD_CNT_MASK, XV_HDMIRX1_TRIB_ANLZ_TIM_HS_POL_MASK, XV_HDMIRX1_TRIB_ANLZ_TIM_OFFSET, XV_HDMIRX1_TRIB_ANLZ_TIM_VS_POL_MASK, XV_HDMIRX1_TRIB_HBP_HS_HBP_SZ_MASK, XV_HDMIRX1_TRIB_HBP_HS_HBP_SZ_SHIFT, XV_HDMIRX1_TRIB_HBP_HS_HS_SZ_MASK, XV_HDMIRX1_TRIB_HBP_HS_OFFSET, XV_HDMIRX1_VCKE_SYS_CNT_OFFSET, XV_HDMIRX1_VER_ID_OFFSET, XV_HDMIRX1_VER_VERSION_OFFSET.
void XV_HdmiRx1_RegisterDebug(XV_HdmiRx1 *InstancePtr)
This function prints out HDMI RX register.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. None.
References XV_HdmiRx1_Config::BaseAddress, XV_HdmiRx1::Config, XV_HdmiRx1_ReadReg.
void XV_HdmiRx1_DdcRegDump(XV_HdmiRx1 *InstancePtr)
This function prints out RX's SCDC registers and values on STDIO/UART.
InstancePtr is a pointer to the XV_HdmiRx1 core instance. None. None.
References XV_HdmiRx1_Config::BaseAddress, XV_HdmiRx1::Config, XV_HDMIRX1_FRL_SCDC_ADDR_MASK, XV_HDMIRX1_FRL_SCDC_DAT_SHIFT, XV_HDMIRX1_FRL_SCDC_OFFSET, XV_HDMIRX1_FRL_SCDC_RD_MASK, XV_HDMIRX1_FRL_SCDC_RDY_MASK, XV_HdmiRx1_ReadReg, XV_HdmiRx1_WriteReg.
int XV_HdmiRx1_SelfTest(XV_HdmiRx1 *InstancePtr)
This function reads ID of PIO peripheral.
InstancePtr is a pointer to the HDMI RX core instance. XST_SUCCESS if PIO ID was matched.XST_FAILURE if PIO ID was mismatched. None.
References XV_HdmiRx1_Config::BaseAddress, XV_HdmiRx1::Config, XV_HDMIRX1_MASK_16, XV_HDMIRX1_PIO_ID, XV_HDMIRX1_PIO_ID_OFFSET, XV_HdmiRx1_ReadReg, XV_HDMIRX1_SHIFT_16.
void XV_HdmiRx1_IntrHandler(void *InstancePtr)
This function is the interrupt handler for the HDMI RX driver.
This handler reads the pending interrupt from PIO, DDC, TIMDET, AUX, AUD and LNKSTA peripherals, determines the source of the interrupts, clears the interrupts and calls callbacks accordingly.The application is responsible for connecting this function to the interrupt system. Application beyond this driver is also responsible for providing callbacks to handle interrupts and installing the callbacks using XV_HdmiRx1_SetCallback() during initialization phase. An example delivered with this driver demonstrates how this could be done. InstancePtr is a pointer to the XV_HdmiRx1 instance that just interrupted. None. None.
References XV_HdmiRx1_Config::BaseAddress, XV_HdmiRx1::Config, XV_HdmiRx1::IsReady, XV_HDMIRX1_AUD_STA_IRQ_MASK, XV_HDMIRX1_AUD_STA_OFFSET, XV_HDMIRX1_AUX_STA_IRQ_MASK, XV_HDMIRX1_AUX_STA_OFFSET, XV_HDMIRX1_DDC_STA_IRQ_MASK, XV_HDMIRX1_DDC_STA_OFFSET, XV_HDMIRX1_LNKSTA_STA_IRQ_MASK, XV_HDMIRX1_LNKSTA_STA_OFFSET, XV_HDMIRX1_PIO_STA_IRQ_MASK, XV_HDMIRX1_PIO_STA_OFFSET, XV_HdmiRx1_ReadReg, XV_HDMIRX1_TMR_STA_IRQ_MASK, XV_HDMIRX1_TMR_STA_OFFSET, XV_HDMIRX1_VTD_STA_IRQ_MASK, XV_HDMIRX1_VTD_STA_OFFSET.
int XV_HdmiRx1_SetCallback(XV_HdmiRx1 *InstancePtr, XV_HdmiRx1_HandlerType HandlerType, void *CallbackFunc, void *CallbackRef)
This function installs an asynchronous callback function for the given HandlerType:
HandlerType Callback Function Type ------------------------- ----------------------------------------------- (XV_HDMIRX1_HANDLER_VTD) VtdCallback (XV_HDMIRX1_HANDLER_AUX) AuxCallback (XV_HDMIRX1_HANDLER_AUD) AudCallback (XV_HDMIRX1_HANDLER_LNKSTA) LnkStaCallback (XV_HDMIRX1_HANDLER_PIO) PioCallback InstancePtr is a pointer to the HDMI RX core instance. HandlerType specifies the type of handler. CallbackFunc is the address of the callback function. CallbackRef is a user data item that will be passed to the callback function when it is invoked. XST_SUCCESS if callback function installed successfully.XST_INVALID_PARAM when HandlerType is invalid. Invoking this function for a handler that already has been installed replaces it with the new handler.
References XV_HdmiRx1::AudCallback, XV_HdmiRx1::AudRef, XV_HdmiRx1::AuxCallback, XV_HdmiRx1::AuxRef, XV_HdmiRx1::BrdgOverflowCallback, XV_HdmiRx1::BrdgOverflowRef, XV_HdmiRx1::ConnectCallback, XV_HdmiRx1::ConnectRef, XV_HdmiRx1::DdcCallback, XV_HdmiRx1::DdcRef, XV_HdmiRx1::DSCPktErrCallback, XV_HdmiRx1::DSCPktErrRef, XV_HdmiRx1::DSCStreamChangeEventCallback, XV_HdmiRx1::DSCStrmChgEvtRef, XV_HdmiRx1::DSCStsUpdtEvtCallback, XV_HdmiRx1::DSCStsUpdtEvtRef, XV_HdmiRx1::DynHdrCallback, XV_HdmiRx1::DynHdrRef, XV_HdmiRx1::FrlConfigCallback, XV_HdmiRx1::FrlConfigRef, XV_HdmiRx1::FrlLts1Callback, XV_HdmiRx1::FrlLts1Ref, XV_HdmiRx1::FrlLts2Callback, XV_HdmiRx1::FrlLts2Ref, XV_HdmiRx1::FrlLts3Callback, XV_HdmiRx1::FrlLts3Ref, XV_HdmiRx1::FrlLts4Callback, XV_HdmiRx1::FrlLts4Ref, XV_HdmiRx1::FrlLtsLCallback, XV_HdmiRx1::FrlLtsLRef, XV_HdmiRx1::FrlLtsPCallback, XV_HdmiRx1::FrlLtsPRef, XV_HdmiRx1::FrlStartCallback, XV_HdmiRx1::FrlStartRef, XV_HdmiRx1::Hdcp14ProtEvtCallback, XV_HdmiRx1::Hdcp14ProtEvtRef, XV_HdmiRx1::Hdcp22ProtEvtCallback, XV_HdmiRx1::Hdcp22ProtEvtRef, XV_HdmiRx1::HdcpCallback, XV_HdmiRx1::HdcpRef, XV_HdmiRx1::LinkErrorCallback, XV_HdmiRx1::LinkErrorRef, XV_HdmiRx1::LnkRdyErrorCallback, XV_HdmiRx1::LnkRdyErrorRef, XV_HdmiRx1::LnkStaCallback, XV_HdmiRx1::LnkStaRef, XV_HdmiRx1::ModeCallback, XV_HdmiRx1::ModeRef, XV_HdmiRx1::PhyResetCallback, XV_HdmiRx1::PhyResetRef, XV_HdmiRx1::SkewLockErrorCallback, XV_HdmiRx1::SkewLockErrorRef, XV_HdmiRx1::StreamDownCallback, XV_HdmiRx1::StreamDownRef, XV_HdmiRx1::StreamInitCallback, XV_HdmiRx1::StreamInitRef, XV_HdmiRx1::StreamUpCallback, XV_HdmiRx1::StreamUpRef, XV_HdmiRx1::SyncLossCallback, XV_HdmiRx1::SyncLossRef, XV_HdmiRx1::TmdsClkRatioCallback, XV_HdmiRx1::TmdsClkRatioRef, XV_HdmiRx1::TmdsConfigCallback, XV_HdmiRx1::TmdsConfigRef, XV_HdmiRx1::VfpChangeCallback, XV_HdmiRx1::VfpChangeRef, XV_HdmiRx1::VicErrorCallback, XV_HdmiRx1::VicErrorRef, XV_HdmiRx1::VidRdyErrorCallback, XV_HdmiRx1::VidRdyErrorRef, XV_HdmiRx1::VrrRdyCallback, XV_HdmiRx1::VrrRdyRef, XV_HDMIRX1_HANDLER_AUD, XV_HDMIRX1_HANDLER_AUX, XV_HDMIRX1_HANDLER_BRDG_OVERFLOW, XV_HDMIRX1_HANDLER_CONNECT, XV_HDMIRX1_HANDLER_DDC, XV_HDMIRX1_HANDLER_DDC_HDCP_14_PROT, XV_HDMIRX1_HANDLER_DDC_HDCP_22_PROT, XV_HDMIRX1_HANDLER_DSC_PKT_ERR, XV_HDMIRX1_HANDLER_DSC_STRM_CH, XV_HDMIRX1_HANDLER_DSC_STS_UPDT, XV_HDMIRX1_HANDLER_DYN_HDR, XV_HDMIRX1_HANDLER_FRL_CONFIG, XV_HDMIRX1_HANDLER_FRL_START, XV_HDMIRX1_HANDLER_HDCP, XV_HDMIRX1_HANDLER_LINK_ERROR, XV_HDMIRX1_HANDLER_LNK_RDY_ERR, XV_HDMIRX1_HANDLER_LNKSTA, XV_HDMIRX1_HANDLER_MODE, XV_HDMIRX1_HANDLER_PHY_RESET, XV_HDMIRX1_HANDLER_SKEW_LOCK_ERR, XV_HDMIRX1_HANDLER_STREAM_DOWN, XV_HDMIRX1_HANDLER_STREAM_INIT, XV_HDMIRX1_HANDLER_STREAM_UP, XV_HDMIRX1_HANDLER_SYNC_LOSS, XV_HDMIRX1_HANDLER_TMDS_CLK_RATIO, XV_HDMIRX1_HANDLER_TMDS_CONFIG, XV_HDMIRX1_HANDLER_VFP_CHANGE, XV_HDMIRX1_HANDLER_VIC_ERROR, XV_HDMIRX1_HANDLER_VID_RDY_ERR, XV_HDMIRX1_HANDLER_VRR_RDY.
XV_HdmiC_VideoTimingExtMeta* XV_HdmiRx1_GetVidTimingExtMeta(XV_HdmiRx1 *InstancePtr)
This function returns Video Timing Extended Metadata.
InstancePtr is a pointer to the XHdmiRx1 core instance. XV_HdmiC_VideoTimingExtMeta None.
References XV_HdmiRx1::VrrIF.
Referenced by XV_HdmiRx1_ParseVideoTimingExtMetaIF.
XV_HdmiC_SrcProdDescIF* XV_HdmiRx1_GetSrcProdDescIF(XV_HdmiRx1 *InstancePtr)
This function returns AMD Source Product Descriptor Infoframe.
InstancePtr is a pointer to the XHdmiRx1 core instance. XV_HdmiC_SrcProdDescIF None.
References XV_HdmiRx1::VrrIF.
Referenced by XV_HdmiRx1_ParseSrcProdDescInfoframe.
XV_HdmiC_VrrInfoframeType XV_HdmiRx1_GetVrrIfType(XV_HdmiRx1 *InstancePtr)
This function returns VRR infoframe type.
InstancePtr is a pointer to the XHdmiRx1 core instance. XV_HdmiRx1_VrrInfoframeType None.
References XV_HdmiRx1::VrrIF.
void XV_HdmiRx1_SetVrrIfType(XV_HdmiRx1 *InstancePtr, XV_HdmiC_VrrInfoframeType Type)
This function Sets VRR infoframe type.
InstancePtr is a pointer to the XHdmiRx1 core instance. Type of type XV_HdmiRx1_VrrInfoframeType None. None.
References XV_HdmiRx1::VrrIF.
void XV_HdmiRx1_DynHDR_SetAddr(XV_HdmiRx1 *InstancePtr, u64 Addr)
This function sets the Dynamic HDR buffer address.
InstancePtr is a pointer to the XHdmiRx1 core instance. Addr is an address in 64bit format. None.
References XV_HdmiRx1::Config, XV_HdmiRx1_Config::DynamicHDR, XV_HDMIRX1_AUX_DYN_HDR_MEMADDR_LSB_OFFSET, XV_HDMIRX1_AUX_DYN_HDR_MEMADDR_MSB_OFFSET, XV_HdmiRx1_WriteReg.
void XV_HdmiRx1_DynHDR_GetInfo(XV_HdmiRx1 *InstancePtr, XV_HdmiRx1_DynHDR_Info *RxDynInfoPtr)
This function gets the Dynamic HDR packet type, length, whether graphics overlay and errors if any.
InstancePtr is a pointer to the XHdmiRx1 core instance. RxDynHdrInfoPtr is a pointer to XHdmiRx1 Dynamic HDR info instance. None.
References XV_HdmiRx1::Config, XV_HdmiRx1_Config::DynamicHDR, XV_HDMIRX1_AUX_DYN_HDR_INFO_OFFSET, XV_HDMIRX1_AUX_DYN_HDR_STS_ERR_MASK, XV_HDMIRX1_AUX_DYN_HDR_STS_GOF_MASK, XV_HDMIRX1_AUX_DYN_HDR_STS_OFFSET, XV_HdmiRx1_ReadReg.
u32 XV_HdmiRx1_DSC_IsEnableStream(XV_HdmiRx1 *InstancePtr)
This function checks if Display Stream Compression (DSC) is enabled on the HDMI RX stream.
InstancePtr is a pointer to the XHdmiRx1 core instance. 1 if DSC is enabled on the stream.0 if DSC is not enabled or not supported. None.
References XV_HdmiRx1_Config::BaseAddress, XV_HdmiRx1::Config, XV_HdmiRx1_Config::DSC, XV_HDMIRX1_PIO_IN_DSC_EN_STRM_MASK, XV_HDMIRX1_PIO_IN_OFFSET, XV_HdmiRx1_ReadReg.
Referenced by XV_HdmiRx1_GetVideoTiming.
int XV_HdmiRx1_DSC_SetDecodeFail(XV_HdmiRx1 *InstancePtr)
This function sets the DSC Decode Fail flag in the HDMI RX FRL DDC field.
InstancePtr is a pointer to the XHdmiRx1 core instance. XST_SUCCESS if the operation was successful.XST_NO_FEATURE if DSC is not supported in the current configuration This function uses an assertion to ensure that the input pointer is not NULL.
References XV_HdmiRx1::Config, XV_HdmiRx1_Config::DSC, XV_HdmiRx1_FrlDdcWriteField.
int XV_HdmiRx1_DSC_SetDscFrlMax(XV_HdmiRx1 *InstancePtr)
This function sets the DSC FRL Max flag in the HDMI RX FRL DDC field.
This function writes a value of 1 to the DSC_FRL_MAX field using the FRL DDC interface. It is used to indicate that the maximum FRL (Fixed Rate Link) bandwidth is being used for Display Stream Compression (DSC) on the HDMI RX path InstancePtr is a pointer to the XHdmiRx1 core instance. XST_SUCCESS if the operation was successful.XST_NO_FEATURE if DSC is not supported in the current configuration This function uses an assertion to ensure that the input pointer is not NULL.
References XV_HdmiRx1::Config, XV_HdmiRx1_Config::DSC, XV_HdmiRx1_FrlDdcWriteField.