
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2021.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2021 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT

*
* Description: Configurations for Standalone BSP
*
*******************************************************************/

#ifndef BSPCONFIG_H  /* prevent circular inclusions */
#define BSPCONFIG_H  /* by using protection macros */

#define MICROBLAZE_PVR_NONE
#define EL3 1
#define EL1_NONSECURE 0
#define HYP_GUEST 0

#endif /*end of __BSPCONFIG_H_*/
