gpio_api
XGPIO_DATA_OFFSET
Data register for 1st channel.
Referenced by main, XGpio_DiscreteClear, XGpio_DiscreteRead, XGpio_DiscreteSet, XGpio_DiscreteWrite.
XGPIO_TRI_OFFSET
I/O direction reg for 1st channel.
Referenced by main, XGpio_GetDataDirection, XGpio_SetDataDirection.
XGPIO_DATA2_OFFSET
Data register for 2nd channel.
XGPIO_TRI2_OFFSET
I/O direction reg for 2nd channel.
XGPIO_GIE_OFFSET
Glogal interrupt enable register.
Referenced by XGpio_InterruptGlobalDisable, XGpio_InterruptGlobalEnable.
XGPIO_ISR_OFFSET
Interrupt status register.
Referenced by XGpio_InterruptClear, XGpio_InterruptGetStatus.
XGPIO_IER_OFFSET
Interrupt enable register.
Referenced by XGpio_InterruptDisable, XGpio_InterruptEnable, XGpio_InterruptGetEnabled.
XGPIO_IR_MASK
Mask of all bits.
XGPIO_IR_CH1_MASK
Mask for the 1st channel.
XGPIO_IR_CH2_MASK
Mask for the 2nd channel.
XGPIO_GIE_GINTR_ENABLE_MASK
Mask for Global Interrupt.
Referenced by XGpio_InterruptGlobalEnable.
XGpio_Config XGpio_ConfigTable[][]
This table contains configuration information for each GPIO device in the system.
Referenced by XGpio_LookupConfig.
XGpio_Config XGpio_ConfigTable[][]
This table contains configuration information for each GPIO device in the system.
Referenced by XGpio_LookupConfig.
int XGpio_CfgInitialize(XGpio *InstancePtr, XGpio_Config *Config, UINTPTR EffectiveAddr)
Initializes the XGpio instance provided by the caller based on the given configuration data.
Nothing is done except to initialize the InstancePtr. InstancePtr Pointer to an XGpio instance. The memory the pointer references must be pre-allocated by the caller. Further calls to manipulate the driver through the XGpio API must be made with this pointer. Config Reference to a structure containing information about a specific GPIO device. This function initializes an InstancePtr object for a specific device specified by the contents of Config. This function can initialize multiple instance objects with the use of multiple calls giving different Config information on each call. EffectiveAddr Device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, use Config->BaseAddress for this parameters, passing the physical address instead. XST_SUCCESS if the initialization is successful. None.
References XGpio::BaseAddress, XGpio_Config::InterruptPresent, XGpio::InterruptPresent, XGpio_Config::IsDual, XGpio::IsDual, XGpio::IsReady.
Referenced by XGpio_Initialize.
void XGpio_SetDataDirection(XGpio *InstancePtr, unsigned Channel, u32 DirectionMask)
Sets the input/output direction of all discrete signals for the specified GPIO channel.
InstancePtr Pointer to an XGpio instance to be worked on. Channel Contains the channel of the GPIO (1 or 2) to operate on. DirectionMask Bitmask specifying which discretes are input and which are output. Bits set to 0 are output and bits set to 1 are input. None. The hardware must be built for dual channels if this function is used with any channel other than 1. If it is not, this function will assert.
References XGpio::BaseAddress, XGpio::IsDual, XGpio::IsReady, XGPIO_CHAN_OFFSET, XGPIO_TRI_OFFSET, XGpio_WriteReg.
Referenced by GpioInputExample, GpioOutputExample, main.
u32 XGpio_GetDataDirection(XGpio *InstancePtr, unsigned Channel)
Gets the input/output direction of all discrete signals for the specified GPIO channel.
InstancePtr Pointer to an XGpio instance to be worked on. Channel Contains the channel of the GPIO (1 or 2) to operate on. Bitmask specifying which discretes are input and which are output. Bits set to 0 are output and bits set to 1 are input. The hardware must be built for dual channels if this function is used with any channel other than 1. If it is not, this function will assert.
References XGpio::BaseAddress, XGpio::IsDual, XGpio::IsReady, XGPIO_CHAN_OFFSET, XGpio_ReadReg, XGPIO_TRI_OFFSET.
u32 XGpio_DiscreteRead(XGpio *InstancePtr, unsigned Channel)
Reads state of discretes for the specified GPIO channel.
InstancePtr Pointer to an XGpio instance to be worked on. Channel Contains the channel of the GPIO (1 or 2) to operate on. Current copy of the discretes register. The hardware must be built for dual channels if this function is used with any channel other than 1. If it is not, this function will assert.
References XGpio::BaseAddress, XGpio::IsDual, XGpio::IsReady, XGPIO_CHAN_OFFSET, XGPIO_DATA_OFFSET, XGpio_ReadReg.
Referenced by GpioInputExample, XGpio_SelfTest.
void XGpio_DiscreteWrite(XGpio *InstancePtr, unsigned Channel, u32 Mask)
Writes to discretes register for the specified GPIO channel.
InstancePtr Pointer to an XGpio instance to be worked on. Channel Contains the channel of the GPIO (1 or 2) to operate on. Mask Value to be written to the discretes register. None. The hardware must be built for dual channels if this function is used with any channel other than 1. If it is not, this function will assert. See also XGpio_DiscreteSet() and XGpio_DiscreteClear().
References XGpio::BaseAddress, XGpio::IsDual, XGpio::IsReady, XGPIO_CHAN_OFFSET, XGPIO_DATA_OFFSET, XGpio_WriteReg.
Referenced by GpioOutputExample, main.
int XGpio_Initialize(XGpio *InstancePtr, UINTPTR BaseAddress)
Initializes the XGpio instance provided by the caller based on the device ID/BaseAddress.
Only InstancePtr is initialized. InstancePtr Pointer to an XGpio instance. The memory that the pointer references must be pre-allocated by the caller. Further calls to manipulate the instance/driver through the XGpio API must be made with this pointer. BaseAddress contains the base address of the device XST_SUCCESS if the initialization was successful.XST_DEVICE_NOT_FOUND if the device configuration data was not found for a device with the supplied device ID/BaseAddress. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XGpio_Config::BaseAddress, XGpio::IsReady, XGpio_CfgInitialize, XGpio_LookupConfig.
Referenced by GpioInputExample, GpioIntrExample, GpioOutputExample, main.
XGpio_Config * XGpio_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XGpio_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xgpio.h for the definition of XGpio_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XGpio_Config::Name, XGpio_ConfigTable.
Referenced by GpioIntrExample, GpioOutputExample, XGpio_Initialize.
void XGpio_DiscreteSet(XGpio *InstancePtr, unsigned Channel, u32 Mask)
Set output discrete(s) to logic 1 for the specified GPIO channel.
InstancePtr Pointer to an XGpio instance to be worked on. Channel Contains the channel of the GPIO (1 or 2) to operate on. Mask Set of bits that will be set to 1 in the discrete data register. All other bits in the data register are unaffected. None. The hardware must be built for dual channels if this function is used with any channel other than 1. If it is not, this function will assert.This API can only be used if the GPIO_IO ports in the IP are used for connecting to the external output ports.
References XGpio::BaseAddress, XGpio::IsDual, XGpio::IsReady, XGPIO_CHAN_OFFSET, XGPIO_DATA_OFFSET, XGpio_ReadReg, XGpio_WriteReg.
void XGpio_DiscreteClear(XGpio *InstancePtr, unsigned Channel, u32 Mask)
Set output discrete(s) to logic 0 for the specified GPIO channel.
InstancePtr Pointer to an XGpio instance to be worked on. Channel Contains the channel of the GPIO (1 or 2) to operate on. Mask Set of bits that will be set to 0 in the discrete data register. All other bits in the data register are unaffected. None. The hardware must be built for dual channels if this function is used with any channel other than 1. If it is not, this function will assert.This API can only be used if the GPIO_IO ports in the IP are used for connecting to the external output ports.
References XGpio::BaseAddress, XGpio::IsDual, XGpio::IsReady, XGPIO_CHAN_OFFSET, XGPIO_DATA_OFFSET, XGpio_ReadReg, XGpio_WriteReg.
Referenced by GpioOutputExample, main.
int XGpio_SelfTest(XGpio *InstancePtr)
Runs a self-test on the driver/device.
This function performs a minimal test in which the data register is read. It only does a read without any kind of test because the hardware has been parameterized such that it may be only an input and the state of the input is unknown.All other hardware features of the device are not guaranteed to be in the hardware since they are parameterizable. InstancePtr Pointer to the XGpio instance to be worked on. This parameter must be initialized with XGpio_Initialize(). XST_SUCCESS always. If the GPIO device was not present in the hardware a bus error is generated. Other indicators of a bus error, such as registers in bridges or buses, may be necessary to determine if this function caused a bus error. None.
References XGpio::IsReady, XGpio_DiscreteRead.
void XGpio_InterruptGlobalEnable(XGpio *InstancePtr)
Enables the interrupt output signal.
Interrupts enabled through XGpio_InterruptEnable() will not be passed through until the global enable bit is set by this function. This function is designed to allow all interrupts (both channels) to be enabled easily for exiting a critical section. This function will assert if the hardware device has not been built with interrupt capabilities. InstancePtr GPIO instance to operate on. None. None.
References XGpio::BaseAddress, XGpio::InterruptPresent, XGpio::IsReady, XGPIO_GIE_GINTR_ENABLE_MASK, XGPIO_GIE_OFFSET, XGpio_WriteReg.
Referenced by GpioIntrExample.
void XGpio_InterruptGlobalDisable(XGpio *InstancePtr)
Disables the interrupt output signal.
Interrupts enabled through XGpio_InterruptEnable() will no longer be passed through until the global enable bit is set by XGpio_InterruptGlobalEnable(). This function is designed to allow all interrupts (both channels) to be disabled easily for entering a critical section. This function will assert if the hardware device has not been built with interrupt capabilities. InstancePtr GPIO instance to operate on. None.
References XGpio::BaseAddress, XGpio::InterruptPresent, XGpio::IsReady, XGPIO_GIE_OFFSET, XGpio_WriteReg.
void XGpio_InterruptEnable(XGpio *InstancePtr, u32 Mask)
Enable interrupts.
The global interrupt must also be enabled by calling XGpio_InterruptGlobalEnable() for interrupts to occur. This function will assert if the hardware device has not been built with interrupt capabilities. InstancePtr GPIO instance to operate on. Mask Mask to enable. Bit positions of 1 are enabled. This mask is formed by OR'ing bits from XGPIO_IR* bits which are contained in xgpio_l.h. None.
References XGpio::BaseAddress, XGpio::InterruptPresent, XGpio::IsReady, XGPIO_IER_OFFSET, XGpio_ReadReg, XGpio_WriteReg.
Referenced by GpioIntrExample.
void XGpio_InterruptDisable(XGpio *InstancePtr, u32 Mask)
Disable interrupts.
This function allows specific interrupts for each channel to be disabled. This function will assert if the hardware device has not been built with interrupt capabilities. InstancePtr GPIO instance to operate on. Mask Mask to disable. Bits set to 1 are disabled. This mask is formed by OR'ing bits from XGPIO_IR* bits which are contained in xgpio_l.h. None.
References XGpio::BaseAddress, XGpio::InterruptPresent, XGpio::IsReady, XGPIO_IER_OFFSET, XGpio_ReadReg, XGpio_WriteReg.
void XGpio_InterruptClear(XGpio *InstancePtr, u32 Mask)
Clears pending interrupts with the provided mask.
This function should be called after the software has serviced the interrupts that are pending. This function will assert if the hardware device has not been built with interrupt capabilities. InstancePtr GPIO instance to operate on. Mask Mask to clear pending interrupts. Bit positions of 1 are cleared. This mask is formed by OR'ing bits from XGPIO_IR* bits which are contained in xgpio_l.h. None.
References XGpio::BaseAddress, XGpio::InterruptPresent, XGpio::IsReady, XGPIO_ISR_OFFSET, XGpio_ReadReg, XGpio_WriteReg.
Referenced by GpioHandler.
u32 XGpio_InterruptGetEnabled(XGpio *InstancePtr)
Returns the interrupt enable mask.
This function will assert if the hardware device has not been built with interrupt capabilities. InstancePtr GPIO instance to operate on. A mask of bits made from XGPIO_IR* bits which are contained in xgpio_l.h.None.
References XGpio::BaseAddress, XGpio::InterruptPresent, XGpio::IsReady, XGPIO_IER_OFFSET, XGpio_ReadReg.
u32 XGpio_InterruptGetStatus(XGpio *InstancePtr)
Returns the status of interrupt signals.
Any bit in the mask set to 1 indicates that the channel associated with the bit has asserted an interrupt condition. This function will assert if the hardware device has not been built with interrupt capabilities. InstancePtr GPIO instance to operate on. A pointer to a mask of bits made from XGPIO_IR* bits which are contained in xgpio_l.h. The interrupt status indicates the status of the device regardless if the interrupts from the devices have been enabled or not through XGpio_InterruptEnable().
References XGpio::BaseAddress, XGpio::InterruptPresent, XGpio::IsReady, XGPIO_ISR_OFFSET, XGpio_ReadReg.
XGPIO_H
by using protection macros
XGPIO_I_H
by using protection macros
XGPIO_L_H
by using protection macros
XGPIO_CHAN_OFFSET
Channel offeset.
Referenced by main, XGpio_DiscreteClear, XGpio_DiscreteRead, XGpio_DiscreteSet, XGpio_DiscreteWrite, XGpio_GetDataDirection, XGpio_SetDataDirection.
XGpio_In32
Input Operations.
XGpio_Out32
Output Operations.
XGpio_WriteReg
Performs a 32-bit write to a GPIO register.
If the GPIO core is implemented in a smaller width, only the least significant data is written. BaseAddress Base address of the GPIO device. RegOffset Register offset from the base to write to. Data Data written to the register. None. C-style signature: void XGpio_WriteReg(u32 BaseAddress, u32 RegOffset, u32 Data)
Referenced by main, XGpio_DiscreteClear, XGpio_DiscreteSet, XGpio_DiscreteWrite, XGpio_InterruptClear, XGpio_InterruptDisable, XGpio_InterruptEnable, XGpio_InterruptGlobalDisable, XGpio_InterruptGlobalEnable, XGpio_SetDataDirection.
XGpio_ReadReg
Reads a value from a GPIO register.
A 32-bit read is performed. If the GPIO core is implemented in a smaller width, only the least significant data is read from the register. The most significant data will be read as 0. BaseAddress Base address of the GPIO device. RegOffset Register offset from the base to read from. Data read from the register. C-style signature: u32 XGpio_ReadReg(u32 BaseAddress, u32 RegOffset)
Referenced by main, XGpio_DiscreteClear, XGpio_DiscreteRead, XGpio_DiscreteSet, XGpio_GetDataDirection, XGpio_InterruptClear, XGpio_InterruptDisable, XGpio_InterruptEnable, XGpio_InterruptGetEnabled, XGpio_InterruptGetStatus.
XPAR_XGPIO_NUM_INSTANCES
GPIO instances.