xgpio_intr.c
void XGpio_InterruptGlobalEnable(XGpio *InstancePtr)
Enables the interrupt output signal.
Interrupts enabled through XGpio_InterruptEnable() will not be passed through until the global enable bit is set by this function. This function is designed to allow all interrupts (both channels) to be enabled easily for exiting a critical section. This function will assert if the hardware device has not been built with interrupt capabilities. InstancePtr GPIO instance to operate on. None. None.
References XGpio::BaseAddress, XGpio::InterruptPresent, XGpio::IsReady, XGPIO_GIE_GINTR_ENABLE_MASK, XGPIO_GIE_OFFSET, XGpio_WriteReg.
Referenced by GpioIntrExample.
void XGpio_InterruptGlobalDisable(XGpio *InstancePtr)
Disables the interrupt output signal.
Interrupts enabled through XGpio_InterruptEnable() will no longer be passed through until the global enable bit is set by XGpio_InterruptGlobalEnable(). This function is designed to allow all interrupts (both channels) to be disabled easily for entering a critical section. This function will assert if the hardware device has not been built with interrupt capabilities. InstancePtr GPIO instance to operate on. None.
References XGpio::BaseAddress, XGpio::InterruptPresent, XGpio::IsReady, XGPIO_GIE_OFFSET, XGpio_WriteReg.
void XGpio_InterruptEnable(XGpio *InstancePtr, u32 Mask)
Enable interrupts.
The global interrupt must also be enabled by calling XGpio_InterruptGlobalEnable() for interrupts to occur. This function will assert if the hardware device has not been built with interrupt capabilities. InstancePtr GPIO instance to operate on. Mask Mask to enable. Bit positions of 1 are enabled. This mask is formed by OR'ing bits from XGPIO_IR* bits which are contained in xgpio_l.h. None.
References XGpio::BaseAddress, XGpio::InterruptPresent, XGpio::IsReady, XGPIO_IER_OFFSET, XGpio_ReadReg, XGpio_WriteReg.
Referenced by GpioIntrExample.
void XGpio_InterruptDisable(XGpio *InstancePtr, u32 Mask)
Disable interrupts.
This function allows specific interrupts for each channel to be disabled. This function will assert if the hardware device has not been built with interrupt capabilities. InstancePtr GPIO instance to operate on. Mask Mask to disable. Bits set to 1 are disabled. This mask is formed by OR'ing bits from XGPIO_IR* bits which are contained in xgpio_l.h. None.
References XGpio::BaseAddress, XGpio::InterruptPresent, XGpio::IsReady, XGPIO_IER_OFFSET, XGpio_ReadReg, XGpio_WriteReg.
void XGpio_InterruptClear(XGpio *InstancePtr, u32 Mask)
Clears pending interrupts with the provided mask.
This function should be called after the software has serviced the interrupts that are pending. This function will assert if the hardware device has not been built with interrupt capabilities. InstancePtr GPIO instance to operate on. Mask Mask to clear pending interrupts. Bit positions of 1 are cleared. This mask is formed by OR'ing bits from XGPIO_IR* bits which are contained in xgpio_l.h. None.
References XGpio::BaseAddress, XGpio::InterruptPresent, XGpio::IsReady, XGPIO_ISR_OFFSET, XGpio_ReadReg, XGpio_WriteReg.
Referenced by GpioHandler.
u32 XGpio_InterruptGetEnabled(XGpio *InstancePtr)
Returns the interrupt enable mask.
This function will assert if the hardware device has not been built with interrupt capabilities. InstancePtr GPIO instance to operate on. A mask of bits made from XGPIO_IR* bits which are contained in xgpio_l.h.None.
References XGpio::BaseAddress, XGpio::InterruptPresent, XGpio::IsReady, XGPIO_IER_OFFSET, XGpio_ReadReg.
u32 XGpio_InterruptGetStatus(XGpio *InstancePtr)
Returns the status of interrupt signals.
Any bit in the mask set to 1 indicates that the channel associated with the bit has asserted an interrupt condition. This function will assert if the hardware device has not been built with interrupt capabilities. InstancePtr GPIO instance to operate on. A pointer to a mask of bits made from XGPIO_IR* bits which are contained in xgpio_l.h. The interrupt status indicates the status of the device regardless if the interrupts from the devices have been enabled or not through XGpio_InterruptEnable().
References XGpio::BaseAddress, XGpio::InterruptPresent, XGpio::IsReady, XGPIO_ISR_OFFSET, XGpio_ReadReg.