xgpio.c
int XGpio_CfgInitialize(XGpio *InstancePtr, XGpio_Config *Config, UINTPTR EffectiveAddr)
Initializes the XGpio instance provided by the caller based on the given configuration data.
Nothing is done except to initialize the InstancePtr. InstancePtr Pointer to an XGpio instance. The memory the pointer references must be pre-allocated by the caller. Further calls to manipulate the driver through the XGpio API must be made with this pointer. Config Reference to a structure containing information about a specific GPIO device. This function initializes an InstancePtr object for a specific device specified by the contents of Config. This function can initialize multiple instance objects with the use of multiple calls giving different Config information on each call. EffectiveAddr Device base address in the virtual memory address space. The caller is responsible for keeping the address mapping from EffectiveAddr to the device physical base address unchanged once this function is invoked. Unexpected errors may occur if the address mapping changes after this function is called. If address translation is not used, use Config->BaseAddress for this parameters, passing the physical address instead. XST_SUCCESS if the initialization is successful. None.
References XGpio::BaseAddress, XGpio_Config::InterruptPresent, XGpio::InterruptPresent, XGpio_Config::IsDual, XGpio::IsDual, XGpio::IsReady.
Referenced by XGpio_Initialize.
void XGpio_SetDataDirection(XGpio *InstancePtr, unsigned Channel, u32 DirectionMask)
Sets the input/output direction of all discrete signals for the specified GPIO channel.
InstancePtr Pointer to an XGpio instance to be worked on. Channel Contains the channel of the GPIO (1 or 2) to operate on. DirectionMask Bitmask specifying which discretes are input and which are output. Bits set to 0 are output and bits set to 1 are input. None. The hardware must be built for dual channels if this function is used with any channel other than 1. If it is not, this function will assert.
References XGpio::BaseAddress, XGpio::IsDual, XGpio::IsReady, XGPIO_CHAN_OFFSET, XGPIO_TRI_OFFSET, XGpio_WriteReg.
Referenced by GpioInputExample, GpioOutputExample, main.
u32 XGpio_GetDataDirection(XGpio *InstancePtr, unsigned Channel)
Gets the input/output direction of all discrete signals for the specified GPIO channel.
InstancePtr Pointer to an XGpio instance to be worked on. Channel Contains the channel of the GPIO (1 or 2) to operate on. Bitmask specifying which discretes are input and which are output. Bits set to 0 are output and bits set to 1 are input. The hardware must be built for dual channels if this function is used with any channel other than 1. If it is not, this function will assert.
References XGpio::BaseAddress, XGpio::IsDual, XGpio::IsReady, XGPIO_CHAN_OFFSET, XGpio_ReadReg, XGPIO_TRI_OFFSET.
u32 XGpio_DiscreteRead(XGpio *InstancePtr, unsigned Channel)
Reads state of discretes for the specified GPIO channel.
InstancePtr Pointer to an XGpio instance to be worked on. Channel Contains the channel of the GPIO (1 or 2) to operate on. Current copy of the discretes register. The hardware must be built for dual channels if this function is used with any channel other than 1. If it is not, this function will assert.
References XGpio::BaseAddress, XGpio::IsDual, XGpio::IsReady, XGPIO_CHAN_OFFSET, XGPIO_DATA_OFFSET, XGpio_ReadReg.
Referenced by GpioInputExample, XGpio_SelfTest.
void XGpio_DiscreteWrite(XGpio *InstancePtr, unsigned Channel, u32 Mask)
Writes to discretes register for the specified GPIO channel.
InstancePtr Pointer to an XGpio instance to be worked on. Channel Contains the channel of the GPIO (1 or 2) to operate on. Mask Value to be written to the discretes register. None. The hardware must be built for dual channels if this function is used with any channel other than 1. If it is not, this function will assert. See also XGpio_DiscreteSet() and XGpio_DiscreteClear().
References XGpio::BaseAddress, XGpio::IsDual, XGpio::IsReady, XGPIO_CHAN_OFFSET, XGPIO_DATA_OFFSET, XGpio_WriteReg.
Referenced by GpioOutputExample, main.