xgpio_sinit.c
XPAR_XGPIO_NUM_INSTANCES
GPIO instances.
XGpio_Config * XGpio_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
The XGpio_ConfigTable[] contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration found or NULL if the specified device ID/BaseAddress was not found. See xgpio.h for the definition of XGpio_Config. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XGpio_Config::Name, XGpio_ConfigTable.
Referenced by GpioIntrExample, GpioOutputExample, XGpio_Initialize.
int XGpio_Initialize(XGpio *InstancePtr, UINTPTR BaseAddress)
Initializes the XGpio instance provided by the caller based on the device ID/BaseAddress.
Only InstancePtr is initialized. InstancePtr Pointer to an XGpio instance. The memory that the pointer references must be pre-allocated by the caller. Further calls to manipulate the instance/driver through the XGpio API must be made with this pointer. BaseAddress contains the base address of the device XST_SUCCESS if the initialization was successful.XST_DEVICE_NOT_FOUND if the device configuration data was not found for a device with the supplied device ID/BaseAddress. In XSCT/classic flow, DeviceId is used to look up the device configuration.
References XGpio_Config::BaseAddress, XGpio::IsReady, XGpio_CfgInitialize, XGpio_LookupConfig.
Referenced by GpioInputExample, GpioIntrExample, GpioOutputExample, main.