mmi_dc
const XDc_VideoAttribute XDc_SupportedFormats[XDC_NUM_SUPPORTED][XDC_NUM_SUPPORTED]
const XDc_VideoAttribute XDc_SupportedFormats[XDC_NUM_SUPPORTED][XDC_NUM_SUPPORTED]
void XDc_CfgInitialize(XDc *InstancePtr, u32 BaseAddr)
This function initializes the configuration for the DC Instance.
InstancePtr is a pointer to the XDc instance. BaseAddr sets the base address of the DC instance DeviceId is the id of the device from the design. None. Base address and DeviceId is same as the DP Core driver.
Referenced by XDcSub_CfgInitialize.
void XDc_Initialize(XDc *InstancePtr)
This function initializes all the data structures of the XDc Instance.
InstancePtr is a pointer to the XDc instance. None. None.
References XDC_AUD_SOFT_RST, XDc_WriteReg.
void XDc_WriteProtEnable(XDc *InstancePtr)
This function disables writes to DC.
InstancePtr is a pointer to the XDc instance. None.
References XDC_WPROTS, XDc_WriteReg.
void XDc_WriteProtDisable(XDc *InstancePtr)
This function enables writes to DC.
InstancePtr is a pointer to the XDc instance. None.
References XDC_WPROTS, XDc_WriteReg.
Referenced by XDcSub_Initialize.
void XDc_SetVidInterfaceMode(XDc *InstancePtr)
This function sets the mode for DC Instance.
DC can be either in bypass mode or functional mode InstancePtr is a pointer to the XDc instance. None.
References XDC_DC_BYPASS, XDc_WriteReg.
Referenced by XDcSub_Initialize.
void XDc_SetBlenderBgColor(XDc *InstancePtr)
This function sets the blender background color.
InstancePtr is an pointer to the XDc Instance. Color is a pointer to the structure XDc_BlenderBgClr None. None.
References XDC_V_BLEND_BG_CLR_0, XDC_V_BLEND_BG_CLR_1, XDC_V_BLEND_BG_CLR_2, XDc_WriteReg.
void XDc_SetGlobalAlpha(XDc *InstancePtr)
This function enables or disables global alpha.
InstancePtr is an pointer to the XDc Instance. None. GlobalAlphaEn = 1, enables the global alpha. GlobalAlphaEn = 0, disables the global alpha. Alpha = 0, transparent Alpha = 255, Opaque Alpha = 8:1 (Alpha value)
References XDC_V_BLEND_SET_GLOBAL_ALPHA_REG, XDc_WriteReg.
Referenced by XDcSub_ConfigureDcVideo.
void XDc_SetInputVideoSelect(XDc *InstancePtr)
This function selects the source type for the Video and Graphics input streams that are passed on to the blender block.
InstancePtr is a pointer to the XDc instance. None. None.
References XDC_AV_BUF_OUTPUT_AUD_VID_SELECT, XDc_ReadReg, XDc_WriteReg.
Referenced by XDcSub_ConfigureDcVideo.
void XDc_SetInputAudioSelect(XDc *InstancePtr)
This function selects the source type for audio stream.
InstancePtr is a pointer to the XDc instance. None. None.
References XDC_AV_BUF_OUTPUT_AUD_VID_SELECT, XDc_ReadReg, XDc_WriteReg.
Referenced by XDcSub_ConfigureDcVideo.
const XDc_VideoAttribute* XDc_GetNonLiveVideoAttribute(XDc_VideoFormat Format)
This function looks up if the video format is valid NonLiveVideo format or not and returns a pointer to the attributes of the video.
Format takes in the video format for which attributes are being requested. A pointer to the structure XDc_VideoAttribute if the video format is valid, else returns NULL. None.
Referenced by XDcSub_SetInputNonLiveVideoFormat, XDpDc_ConfigureCursorBlend, XDpDc_GenerateFrames, XDpDc_InitDcSubPtr, XDpDc_InitDcSubsystem, XDpDc_SetupStream1Descriptors, XDpDc_SetupStream2Descriptors.
void XDc_SetNonLiveInputFormat(XDc *InstancePtr, u8 VideoSrc, const XDc_VideoAttribute *Video)
This function applies Attributes for Non - Live source(Stream1/Stream2).
InstancePtr is an pointer to the XDc Instance. None.
References XDC_AV_BUF_FORMAT, XDc_ReadReg, XDc_WriteReg.
Referenced by XDc_ConfigureStream.
const XDc_VideoAttribute* XDc_GetLiveVideoAttribute(XDc_VideoFormat Format)
This function looks up if the video format is valid LiveVideo format or not and returns a pointer to the attributes of the video.
Format takes in the video format for which attributes are being requested. A pointer to the structure XDc_VideoAttribute if the video format is valid, else returns NULL. None.
Referenced by main, XDcSub_SetInputLiveStreamFormat.
static void XDc_SetLiveInputFormat(XDc *InstancePtr, u32 RegConfig, const XDc_VideoAttribute *Video)
This function applies Attributes for Live source(Video/Graphics).
InstancePtr is an pointer to the XDc Instance. RegConfig points to LIVE_VID_CONFIG or LIVE_GFX_CONFIG reg Video is a pointer to the attributes of the video to be applied None. BPC values to be programmed are 001: 8BPC 010: 10BPC 011: 12BPC XDc_VideoFormats stores bits per pixel(BPP) value i.e 24 for 8BPC, 30 for 10BPC, 36 for 12BPC. Dividing the BPP by 6 and subtractig with 3 generates the required above values to be programmed.
XDc_VideoAttribute* XDc_GetOutputVideoAttribute(XDc_VideoFormat Format, XDc_VidInterface Mode)
This function looks up if the output video format is valid or not and returns a pointer to the attributes of the video.
Format takes in the output video format for which attributes are being requested. A pointer to the structure XDc_VideoAttribute if the video format is valid, else returns NULL. None.
Referenced by XDcSub_SetOutputVideoFormat, XDpDc_InitDcSubPtr.
void XDc_SetOutputVideoFormat(XDc *InstancePtr)
This function configures the Output of the Video Pipeline.
InstancePtr is an pointer to the XDc Instance. None. None.
References XDC_V_BLEND_OUTPUT_VID_FORMAT, XDc_WriteReg.
Referenced by XDcSub_ConfigureDcVideo.
static void XDc_SetScalingFactors(XDc *InstancePtr, u32 RegOffset, const u32 *ScalingFactors)
This function sets the scaling factors depending on the source video stream.
InstancePtr is a pointer to the XDc instance. RegOffset ScaleFactors is an array with per component scale factor to scale to 12 BPC None. None.
static void XDc_SetInputCSC(XDc *InstancePtr, u32 RegOffset, u32 *CSCCoeffs, u32 *CSCOffset)
This function programs the coefficients for Input Color Space Conversion.
InstancePtr is an pointer to the XDc Instance. RegOffset is a register offset for Video or Graphics config register CSCCoeffs is matrix with coefficient values CSCOffset is offset matrix for Y, Cb, Cr for pre-post matrix multiplication None. None.
static void XDc_SetLayerControl(XDc *InstancePtr, u32 RegOffset, u8 BlendBypass, const XDc_VideoAttribute *Video)
This function sets the Layer Control for Streams.
InstancePtr is a pointer to the XDc instance. RegOffset is the register offset of Video Layer or Graphics Layer from the base address blendbypass is a 8 bit value to set layer as passed through as the blender out Video is a pointer to the XDc_VideoAttribute struct which has been configured for the particular layer None. None.
static void XDc_SetPartialBlend(XDc *InstancePtr, u32 RegOffset, XDc_PartialBlend *Video)
This function enables Partial Blend for both video streams.
InstancePtr is a pointer to the XDc Instance. RegOffset address to program Video contains partial blend coords to set. None. None.
void XDc_EnablePartialBlend(XDc *InstancePtr)
This function enables Partial Blend for corresponding video stream.
InstancePtr is a pointer to the XDc Instance. None. None.
References XDC_V0, XDC_V1.
Referenced by XDcSub_ConfigureDcVideo.
u32 XDc_ConfigureStream(XDc *InstancePtr, u8 StreamSrc)
This function configures DC Blender.
InstancePtr is a pointer to the XDc instance. VideoSrc points to the stream source None.
References XDC_AV_BUF_GRAPHICS_COMP0_SCALE_FACTOR, XDC_AV_BUF_LIVE_GFX_CFG, XDC_AV_BUF_LIVE_GFX_COMP0_SF, XDC_AV_BUF_LIVE_VID_CFG, XDC_AV_BUF_LIVE_VID_COMP0_SF, XDC_AV_BUF_VID_COMP0_SCALE_FACTOR, XDc_SetNonLiveInputFormat, XDC_V_BLEND_IN1CSC_COEFF0, XDC_V_BLEND_IN2CSC_COEFF0, XDC_V_BLEND_LAYER0_CONTROL, XDC_V_BLEND_LAYER1_CONTROL.
Referenced by XDcSub_ConfigureDcVideo.
void XDc_SetOutputCSC(XDc *InstancePtr)
This function converts the Blender output to the desired output format.
InstancePtr is an pointer to the XDc Instance. None. None.
References XDC_V_BLEND_LUMA_OUTCSC_OFFSET, XDC_V_BLEND_RGB2YCBCR_COEFF0, XDc_WriteReg.
Referenced by XDcSub_ConfigureDcVideo.
void XDc_SetChromaKey(XDc *InstancePtr)
This function enables Chroma Keying.
InstancePtr is an pointer to the XDc Instance. None. None.
References XDC_V_BLEND_CHROMA_KEY_COMP1, XDC_V_BLEND_CHROMA_KEY_COMP2, XDC_V_BLEND_CHROMA_KEY_COMP3, XDC_V_BLEND_CHROMA_KEY_ENABLE, XDc_WriteReg.
Referenced by XDcSub_ConfigureDcVideo.
void XDc_SetCursorBlend(XDc *InstancePtr)
This function enables Cursor blending.
InstancePtr is an pointer to the XDc Instance. None. None.
References XDC_CURSOR_COORDINATE, XDC_CURSOR_SIZE, XDc_WriteReg.
Referenced by XDcSub_ConfigureDcVideo.
void XDc_SetAudioVideoClkSrc(XDc *InstancePtr)
This function sets the Audio and Video Clock Source and the video timing source.
InstancePtr is a pointer to the XDc instance. None. System uses PL Clock for Video when Live source is in use.
References XDC_AV_BUF_AUD_VID_CLK_SOURCE, XDc_WriteReg.
Referenced by XDcSub_ConfigureDcVideo.
void XDc_VideoSoftReset(XDc *InstancePtr)
This function applies a soft reset to the Video pipeline.
InstancePtr is a pointer to the XDc instance. None. None.
References XDC_AV_BUF_SRST_REG, XDc_WriteReg.
Referenced by XDpDc_InitDcSubsystem.
void XDc_VidClkSelect(XDc *InstancePtr)
This function configures DC Video Clock Select.
InstancePtr is a pointer to the XDc instance. None.
References XDC_VID_CLK, XDc_WriteReg.
Referenced by XDpDc_InitDcSubsystem.
void XDc_EnableStream1Buffers(XDc *InstancePtr)
This function enables the video channel interface between the DCDMA and the DC.
InstancePtr is a pointer to the XDc Instance. None. None.
References XDC_AV_CHBUF0, XDc_WriteReg.
Referenced by XDcSub_ConfigureDcVideo.
void XDc_EnableStream2Buffers(XDc *InstancePtr)
This function enables the video channel interface between the DCDMA and the DC.
InstancePtr is a pointer to the XDc Instance. None. None.
References XDC_AV_CHBUF3, XDc_WriteReg.
Referenced by XDcSub_ConfigureDcVideo.
void XDc_AudioSoftReset(XDc *InstancePtr)
This function applies a soft reset to the Audio pipeline.
InstancePtr is a pointer to the XDc instance. None. None.
References XDC_AUD_SOFT_RST, XDc_ReadReg, XDc_WriteReg.
Referenced by XDcSub_Initialize, XDpDc_InitDcSubsystem.
void XDc_AudLineResetDisable(XDc *InstancePtr)
This function enables End of Line Reset for reduced blanking resolutions.
InstancePtr is a pointer to the XDc Instance. None. None.
References XDC_AUD_SOFT_RST, XDc_ReadReg, XDc_WriteReg.
void XDc_AudExtraBSControl(XDc *InstancePtr)
This function enables Extra BS Control for AUDIO_SOFT_RESET.
InstancePtr is a pointer to the XDc Instance. None. None.
References XDC_AUD_SOFT_RST, XDc_ReadReg, XDc_WriteReg.
void XDc_SetSdpSource(XDc *InstancePtr)
This function enables SDP from DMA or PL.
InstancePtr is a pointer to the XDc Instance. None. None.
References XDc_ReadReg, XDC_SDP, XDc_WriteReg.
Referenced by XDcSub_ConfigureDcVideo.
void XDc_SetSdpEmptyThreshold(XDc *InstancePtr)
This function sets SDP Empty Threshold value.
InstancePtr is a pointer to the XDc Instance. None. None.
References XDC_SDP_EMPTY, XDc_WriteReg.
void XDc_SetSdpCursorBuffers(XDc *InstancePtr)
This function enables SDP & Cursor buffers.
InstancePtr is a pointer to the XDc Instance. None. None.
References XDC_AV_CHBUF_CURSOR_SDP, XDc_WriteReg.
Referenced by XDcSub_ConfigureDcVideo.
void XDc_SetVidFrameSwitch(XDc *InstancePtr)
This function configures the register to gate input video on/off at video frame boundary.
InstancePtr is a pointer to the XDc instance. None.
References XDc_WriteReg.
Referenced by XDpDc_InitDcSubsystem.
void XDc_SetNonLiveLatency(XDc *InstancePtr)
This function configures the memory fetch latency.
InstancePtr is a pointer to the XDc instance. None.
References XDC_AV_BUF_NON_LIVE_LATENCY, XDc_WriteReg.
Referenced by XDcSub_ConfigureDcVideo.
void XDc_SetStcCtrl(XDc *InstancePtr)
This function enables STC Control.
InstancePtr is a pointer to the XDc instance. None.
References XDC_AV_BUF_STC_CONTROL, XDc_WriteReg.
void XDc_SetStcLoad(XDc *InstancePtr)
This function loads STC Init value.
InstancePtr is a pointer to the XDc instance. None.
References XDC_AV_BUF_STC_INIT_VALUE0, XDC_AV_BUF_STC_INIT_VALUE1, XDc_WriteReg.
void XDc_SetStcAdjust(XDc *InstancePtr)
This function Adjusts STC Control value.
InstancePtr is a pointer to the XDc instance. None.
References XDC_AV_BUF_STC_ADJ, XDc_WriteReg.
u64 XDc_GetStcVSyncTs(XDc *InstancePtr)
This function reads VSync STC value and returns it.
InstancePtr is a pointer to the XDc instance. None.
References XDC_AV_BUF_STC_VID_VSYNC_TS_REG0, XDC_AV_BUF_STC_VID_VSYNC_TS_REG1, XDc_ReadReg.
u64 XDc_GetStcExtVSyncTs(XDc *InstancePtr)
This function reads External VSync STC value and returns it.
InstancePtr is a pointer to the XDc instance. None.
References XDC_AV_BUF_STC_EXT_VSYNC_TS_REG0, XDC_AV_BUF_STC_EXT_VSYNC_TS_REG1, XDc_ReadReg.
u64 XDc_GetStcCustomEventTs(XDc *InstancePtr)
This function reads Custom Event STC value and returns it.
InstancePtr is a pointer to the XDc instance. None.
References XDC_AV_BUF_STC_CUSTOM_EVENT_TS_REG0, XDC_AV_BUF_STC_CUSTOM_EVENT_TS_REG1, XDc_ReadReg.
u64 XDc_GetStcCustomEvent2Ts(XDc *InstancePtr)
This function reads Custom Event2 STC value and returns it.
InstancePtr is a pointer to the XDc instance. None.
References XDC_AV_BUF_STC_CUSTOM_EVENT2_TS_REG0, XDC_AV_BUF_STC_CUSTOM_EVENT2_TS_REG1, XDc_ReadReg.
u64 XDc_GetStcSnapshot(XDc *InstancePtr)
This function reads STC Snapshot value and returns it.
InstancePtr is a pointer to the XDc instance. None.
References XDC_AV_BUF_STC_SNAPSHOT0, XDC_AV_BUF_STC_SNAPSHOT1, XDc_ReadReg.
void XDc_EnableAudioBuffer(XDc *InstancePtr)
This function Enable Audio Buffer channel and sets the burst length.
InstancePtr is a pointer to the XDc instance. None.
References XDC_AV_CHBUF_AUD, XDc_WriteReg.
Referenced by XDcSub_ConfigureDcVideo.
void XDc_AudioChannelSelect(XDc *InstancePtr)
This function enables audio channel select and programs sample rate.
InstancePtr is a pointer to the XDc instance. None.
References XDC_NL_AUD, XDc_WriteReg.
Referenced by XDcSub_ConfigureDcVideo.
void XDc_AudClkSelect(XDc *InstancePtr)
This function configures DC Audio Clock Select.
InstancePtr is a pointer to the XDc instance. None.
References XDC_AUD_CLK, XDc_WriteReg.
Referenced by XDpDc_InitDcSubsystem.
void XDc_SetAudInterface(XDc *InstancePtr)
This function sets the audio mode for DC Instance.
Audio can be either in bypass mode or functional mode InstancePtr is a pointer to the XDc instance. None.
References XDC_DC_AUD, XDc_WriteReg.
void XDc_EnableAudio(XDc *InstancePtr)
This function enables audio to DC.
InstancePtr is a pointer to the XDc instance. None.
References XDC_DC_AUDIO, XDc_WriteReg.
Referenced by XDcSub_ConfigureDcVideo.
void XDc_DisableAudio(XDc *InstancePtr)
This function disables audio to DC.
InstancePtr is a pointer to the XDc instance. None.
References XDC_DC_AUDIO, XDc_WriteReg.
void XDc_SetVideoTiming(XDc *InstancePtr)
This function configures DC Timings register.
InstancePtr is a pointer to the XDc instance. None.
References XDc_WriteReg.
Referenced by XDpDc_InitDcSubsystem.
void XDc_SetAudioChCtrl(XDc *InstancePtr)
This function controls the Audio channel preamble and status bits.
InstancePtr is a pointer to the XDc instance. None.
References XDC_AUD_MIXER_VOLUME_CONTROL, XDc_WriteReg.
Referenced by XDcSub_SetAudioChCtrl.
void XDc_SetAudioSegmentedMode(XDc *InstancePtr)
This function sets Audio Segmented Mode.
InstancePtr is a pointer to the XDc instance. None.
References XDC_AUD_MIXER_META_DATA, XDc_WriteReg.
void XDc_SetCursorSdpRdyInterval(XDc *InstancePtr)
This function sets Cursor Sdp Ready Interval.
InstancePtr is a pointer to the XDc instance. None.
References XDC_RDY_INTERVAL, XDc_WriteReg.
Referenced by XDcSub_ConfigureDcVideo.
void XDc_SetSdpAckSel(XDc *InstancePtr)
This function sets Cursor Sdp Ready Interval.
InstancePtr is a pointer to the XDc instance. None.
References XDC_DP, XDc_WriteReg.
Referenced by XDcSub_ConfigureDcVideo.
XDC_MAX_SF_REG_COUNT
XDC_MAX_CSC_COEFF_REG_COUNT
XDC_MAX_CSC_OFFSET_REG_COUNT
XDC_TOTAL_CSC_REG_COUNT