mmi_dcdma
void XDcDma_CfgInitialize(XDcDma *InstancePtr, u32 BaseAddr)
This function initializes the configuration for the DcDma Instance.
InstancePtr is a pointer to the XDcDma instance. BaseAddr sets the base address of the DcDma instance None. Base address and DeviceId is same as the Dc Timing driver.
Referenced by XDpDc_InitDcSubsystem.
void XDcDma_WriteProtEnable(XDcDma *InstancePtr)
This function enables the write protection for DCDMA registers.
InstancePtr is a pointer to the XDcDma instance. None.
References XDcDma_ReadReg, XDCDMA_WPROTS, XDcDma_WriteReg.
void XDcDma_WriteProtDisable(XDcDma *InstancePtr)
This function disables the write protection for DCDMA registers.
InstancePtr is a pointer to the XDcDma instance. None.
References XDcDma_ReadReg, XDCDMA_WPROTS, XDcDma_WriteReg.
Referenced by XDpDc_InitDcSubsystem.
u32 XDCDma_GetWriteProt(XDcDma *InstancePtr)
This function programs the DPDMA_GLBL register with trigger channels.
InstancePtr is a pointer to the XDcDma instance. XST_SUCCESS or XST_FAILURE.
References XDcDma_ReadReg, XDCDMA_WPROTS.
void XDcDma_SetDescDelay(XDcDma *InstancePtr, XDcDma_ChannelId Id, u16 Val)
This function programs the Desc Delay for required channel.
InstancePtr is a pointer to the XDcDma instance. Channel ID Val specifies desc delay None.
References XDCDMA_CH0_CNTL, XDcDma_ReadModifyWrite.
void XDcDma_SetDataQoS(XDcDma *InstancePtr, XDcDma_ChannelType Channel, u8 Val)
This function programs the data QoS for a channel.
InstancePtr is a pointer to the XDcDma instance. ChannelType is channel number. Val to configure. None.
References XDCDMA_CH0_CNTL, XDcDma_ReadModifyWrite.
void XDcDma_SetDescQoS(XDcDma *InstancePtr, XDcDma_ChannelType Channel, u8 Val)
This function programs the DPDMA_GLBL register with trigger channels.
InstancePtr is a pointer to the XDcDma instance. ChannelType is channel number. Val to configure. None.
References XDCDMA_CH0_CNTL, XDcDma_ReadModifyWrite.
void XDcDma_SetAxCache(XDcDma *InstancePtr, XDcDma_ChannelId Id, u8 Val)
This function programs the Ax Cache register for specific channel.
InstancePtr is a pointer to the XDcDma instance. ChannelId is channel number. Val to configure. None.
References XDCDMA_CH0_CNTL, XDcDma_ReadModifyWrite.
void XDcDma_SetAxProt(XDcDma *InstancePtr, XDcDma_ChannelId Id, u8 Val)
This function programs the AxProt register for specific channel.
InstancePtr is a pointer to the XDcDma instance. ChannelId is channel number. Val to configure. None.
References XDCDMA_CH0_CNTL, XDcDma_ReadModifyWrite.
u32 XDcDma_ConfigChannelState(XDcDma *InstancePtr, XDcDma_ChannelId Id, XDcDma_State Enable)
This function programs the channel state as enable, disable or idle.
InstancePtr is a pointer to the XDcDma instance. ChannelId is channel to configure Enable sets the channel state. XST_SUCCESS or XST_FAILURE.
References XDCDMA_CH0_CNTL, XDcDma_ConfigChannelState, XDcDma_ReadModifyWrite, XDcDma_WaitPendingTransaction.
Referenced by XDcDma_ConfigChannelState, XDcDma_VSyncHandler.
u32 XDcDma_WaitPendingTransaction(XDcDma *InstancePtr, XDcDma_ChannelId Id)
This function checks for any pending transactions for a given channel.
InstancePtr is a pointer to the XDcDma instance. Channel Id is channel number XST_SUCCESS or XST_FAILURE.
References XDCDma_GetOutstandingTxn.
Referenced by XDcDma_ConfigChannelState.
u32 XDCDma_GetOutstandingTxn(XDcDma *InstancePtr, XDcDma_ChannelId Id)
This function programs the DPDMA_GLBL register with trigger channels.
InstancePtr is a pointer to the XDcDma instance. Channel Id is channel number. XST_SUCCESS or XST_FAILURE.
References XDCDMA_CH0_STATUS, XDcDma_ReadReg.
Referenced by XDcDma_WaitPendingTransaction.
void XDcDma_InterruptEnable(XDcDma *InstancePtr, u32 Mask)
This function enables the interrupt.
InstancePtr is a pointer to the XDcDma instance. Mask is interrupt to unmask. None.
References XDCDMA_MISC_IER, XDCDMA_MISC_ISR, XDcDma_WriteReg.
Referenced by XDpDc_SetupInterrupts.
void XDcDma_InterruptDisable(XDcDma *InstancePtr, u32 Mask)
This function disables the interrupt.
InstancePtr is a pointer to the XDcDma instance. None.
References XDCDMA_MISC_IDR, XDcDma_WriteReg.
u32 XDcDma_SetCallBack(XDcDma *InstancePtr, XDcDma_IntHandlerType HandlerType, void *CallbackFunc, void *CallbackRef)
This function sets the callback for different interrupt handlers.
InstancePtr is a pointer to the XDcDma instance. XST_SUCCESS or XST_FAILURE.
u32 XDcDma_Trigger(XDcDma *InstancePtr, XDcDma_ChannelType Channel)
This function programs the DPDMA_GLBL register with trigger channels.
InstancePtr is a pointer to the XDcDma instance. XST_SUCCESS or XST_FAILURE.
Referenced by XDcDma_VSyncHandler.
u32 XDcDma_ReTrigger(XDcDma *InstancePtr, XDcDma_ChannelType Channel)
This function programs the DPDMA_GLBL register with retrigger channels.
InstancePtr is a pointer to the XDcDma instance. XST_SUCCESS or XST_FAILURE.
References XDCDMA_GBL, XDcDma_WriteReg.
Referenced by XDcDma_VSyncHandler.
void XDcDma_InterruptHandler(XDcDma *InstancePtr)
This function calls the VsyncInterrupt Handler.
InstancePtr is a pointer to the XDcDma instance. None.
References XDCDMA_MISC_ISR, XDcDma_ReadReg, XDcDma_VSyncHandler.
void XDcDma_VSyncHandler(XDcDma *InstancePtr)
This function services the VsyncInterrupt.
InstancePtr is a pointer to the XDcDma instance. None.
References XDcDma_ConfigChannelState, XDCDMA_GBL, XDCDMA_MISC_ISR, XDcDma_ReTrigger, XDcDma_SetupChannel, XDcDma_Trigger, XDcDma_WriteReg.
Referenced by XDcDma_InterruptHandler.
static void XDcDma_SetDescriptorAddress(XDcDma *InstancePtr, XDcDma_ChannelId Id)
This function programs the descriptor address for each video stream.
InstancePtr is a pointer to the XDcDma instance. Channel type None.
void XDcDma_SetupChannel(XDcDma *InstancePtr, XDcDma_ChannelType Channel)
This function sets the descriptor address for each video stream.
InstancePtr is a pointer to the XDcDma instance. Channel type None.
Referenced by XDcDma_VSyncHandler.
void XDcDma_DescInit(XDcDma_Descriptor *XDesc)
This function creates the descriptor for the DcDma Instance.
InstancePtr is a pointer to the XDcDma instance. None.
Referenced by XDpDc_CreateDescriptors.
u32 XDcDma_GetNewDescId(XDcDma *InstancePtr)
This function increments the LastDescId of DcDma Instance.
InstancePtr is a pointer to the XDcDma instance. Updated LastDescId.
References XDcDma::LastDescId.
Referenced by XDpDc_CreateDescriptors.
void XDcDma_SetAudioChCtrl(XDcDma *InstancePtr)
This function sets DcDma Audio Channel Control.
InstancePtr is a pointer to the XDcDma instance. None
References XDCDMA_AUD_CTRL, XDcDma_WriteReg.
XDCDMA_CH_OFFSET
XDCDMA_QOS_MIN
XDCDMA_QOS_MAX
XDCDMA_DSCR_DLY_MIN
XDCDMA_DSCR_DLY_MAX
XDCDMA_AXCACHE_MIN
XDCDMA_AXCACHE_MAX
XDCDMA_AXPROT_MIN
XDCDMA_AXPROT_MAX
XDCDMA_WAIT_TIMEOUT