mmi_dp_intr.c
XMMIDP_INTR_ID
XMMIDP_INTR_PARENT
void XDpDc_DisableDpAudioSdpStreams(XMmiDp *DpPtr)
This function disables DP-side audio SDP/timestamp streams.
DpPtr is a pointer to the XMmiDp instance. None.
Referenced by XDpDc_HpdHotplugHandler, XDpDc_HpdIrqHandler, XDpDc_InitDpPsuSubsystem.
void XDpDc_HpdHotplugHandler(void *CallbackRef)
This function is the HPD hot plug (connect) callback.
It reads sink capabilities, runs link training, and sets up the video stream. CallbackRef is a pointer to the RunConfig structure. None.
References RunConfig::AudioEnable, RunConfig::DpPsuPtr, RunConfig::MaxLaneCount, RunConfig::MaxLinkRate, RunConfig::SdpEnable, XDpDc_DisableDpAudioSdpStreams, XMmiDp_SetupAudioStream, XMmiDp_SetupVideoStream, XMmiDp_SinkPowerUp, XMmiDp_StartFullLinkTrainingCapped.
Referenced by XDpDc_SetupDpInterrupts.
void XDpDc_HpdHotunplugHandler(void *CallbackRef)
This function is the HPD hot unplug (disconnect) callback.
It disables the video stream and logs the disconnect event. CallbackRef is a pointer to the RunConfig structure. None.
References RunConfig::DpPsuPtr.
Referenced by XDpDc_SetupDpInterrupts.
void XDpDc_HpdIrqHandler(void *CallbackRef)
This function is the HPD IRQ (short pulse / sink request) callback.
It reads the DPCD Device Service IRQ Vector and Link Service IRQ Vector to determine the cause of the interrupt and takes appropriate action. CallbackRef is a pointer to the RunConfig structure. None.
References RunConfig::AudioEnable, RunConfig::DpPsuPtr, RunConfig::MaxLaneCount, RunConfig::MaxLinkRate, RunConfig::SdpEnable, XDpDc_DisableDpAudioSdpStreams, XMmiDp_SetupAudioStream, XMmiDp_SetupVideoStream, XMmiDp_StartFullLinkTrainingCapped.
Referenced by XDpDc_SetupDpInterrupts.
void XDpDc_SetupDpInterrupts(RunConfig *RunCfgPtr)
This function registers HPD callbacks and connects the DP interrupt to the GIC.
RunCfgPtr is a pointer to the application configuration structure. None.
References RunConfig::DpPsuPtr, XDpDc_HpdHotplugHandler, XDpDc_HpdHotunplugHandler, XDpDc_HpdIrqHandler.
Referenced by XDpDc_SetupInterrupts.