mmi_dpdc_menus.c
void outbyte(char c)
char inbyte(void)
static char read_char(void)
static u32 read_uint(void)
static const char* format_to_string(u32 format)
This function converts XDc_VideoFormat enum to string name.
format - Format enum value String name of the format Returns "UNKNOWN" for unrecognized formats
void XDpDc_ResolutionHelpMenu(void)
This function displays the resolution help menu.
None None None
void XDpDc_FormatHelpMenu(void)
This function displays the format help menu.
None None
void XDpDc_ListNonliveFormats(void)
This function displays all supported non-live input formats.
None None None
Referenced by XDpDc_ConfigureFormat.
void XDpDc_ListLiveFormats(void)
This function displays all supported live output formats.
None None None
Referenced by XDpDc_ConfigureFormat, XDpDc_ConfigureOutputFormat.
void XDpDc_MainHelpMenu(InitRunConfig *config)
This function displays the main help menu.
None None None
References InitRunConfig::operatingmode, InitRunConfig::presentationmode, XDCSUB_OPMODE_FUNCTIONAL, XDCSUB_PPTMODE_LIVE, XDCSUB_PPTMODE_MIXED, XDCSUB_PPTMODE_NONLIVE.
Referenced by XDpDc_MenuLoop.
void XDpDc_DisplayConfig(InitRunConfig *config)
This function displays the current configuration.
config - Pointer to InitRunConfig structure None None
References InitRunConfig::audio_channels, InitRunConfig::audio_enable, InitRunConfig::avpg, AvpgRunConfig::bpc, AvpgRunConfig::colorimetry, InitRunConfig::cursor_coord_x, InitRunConfig::cursor_coord_y, InitRunConfig::cursor_enable, InitRunConfig::cursor_size_x, InitRunConfig::cursor_size_y, InitRunConfig::frame_rate, InitRunConfig::height, InitRunConfig::lane_count, InitRunConfig::link_rate, InitRunConfig::operatingmode, InitRunConfig::output_format, InitRunConfig::partial_plane_blend_enable, AvpgRunConfig::pattern, AvpgRunConfig::pix_fmt, InitRunConfig::ppb_coord_x, InitRunConfig::ppb_coord_y, InitRunConfig::ppb_offset_x, InitRunConfig::ppb_offset_y, InitRunConfig::ppb_size_x, InitRunConfig::ppb_size_y, InitRunConfig::ppb_stream_select, AvpgRunConfig::ppc, InitRunConfig::presentationmode, InitRunConfig::sdp_enable, InitRunConfig::stream1_format, InitRunConfig::stream2_format, InitRunConfig::width, XDCSUB_OPMODE_FUNCTIONAL, XDCSUB_PPTMODE_LIVE, XDCSUB_PPTMODE_MIXED, XDCSUB_PPTMODE_NONLIVE.
Referenced by XDpDc_MenuLoop.
u32 XDpDc_GetWidth(void)
This function gets width from user.
None Width value None
Referenced by XDpDc_ConfigureResolution.
u32 XDpDc_GetHeight(void)
This function gets height from user.
None Height value None
Referenced by XDpDc_ConfigureResolution.
u32 XDpDc_ConfigureResolution(InitRunConfig *config)
This function configures resolution.
config - Pointer to InitRunConfig structure XST_SUCCESS None
References InitRunConfig::frame_rate, InitRunConfig::height, InitRunConfig::width, XDpDc_GetHeight, XDpDc_GetWidth.
Referenced by XDpDc_MenuLoop.
u32 XDpDc_ConfigureFormat(u32 *format, const char *format_name)
This function configures format.
format - Pointer to format variable format_name - Name of the format being configured XST_SUCCESS None
References XDpDc_ConfigureFormat, XDpDc_ListLiveFormats, XDpDc_ListNonliveFormats.
Referenced by XDpDc_ConfigureFormat, XDpDc_MenuLoop.
u32 XDpDc_ConfigureOutputFormat(u32 *format, const char *format_name)
This function configures output format (live stream)
format - Pointer to format variable format_name - Name of the format being configured XST_SUCCESS This is specialized for live output formats
References XDpDc_ConfigureOutputFormat, XDpDc_ListLiveFormats.
Referenced by XDpDc_ConfigureOutputFormat, XDpDc_MenuLoop.
u32 XDpDc_ConfigureCursor(InitRunConfig *config)
This function configures cursor parameters (coordinates and size)
config - Pointer to InitRunConfig structure XST_SUCCESS None
References InitRunConfig::cursor_coord_x, InitRunConfig::cursor_coord_y, InitRunConfig::cursor_size_x, InitRunConfig::cursor_size_y.
Referenced by XDpDc_MenuLoop.
u32 XDpDc_ConfigurePartialPlane(InitRunConfig *config)
This function configures partial plane blend parameters.
config - Pointer to InitRunConfig structure XST_SUCCESS None
References InitRunConfig::ppb_coord_x, InitRunConfig::ppb_coord_y, InitRunConfig::ppb_offset_x, InitRunConfig::ppb_offset_y, InitRunConfig::ppb_size_x, InitRunConfig::ppb_size_y, InitRunConfig::ppb_stream_select.
Referenced by XDpDc_MenuLoop.
static void XDpDc_ConfigureLink(InitRunConfig *config)
This function configures DP link parameters (lane count and link rate)
config - Pointer to InitRunConfig structure None
static void XDpDc_ValidateModeSpecificConfig(InitRunConfig *config)
static void XDpDc_SelectPresentationMode(InitRunConfig *config)
void XDpDc_MenuLoop(InitRunConfig *config)
This function runs the interactive menu loop.
config - Pointer to InitRunConfig structure None None
References InitRunConfig::audio_channels, InitRunConfig::audio_enable, InitRunConfig::cursor_coord_x, InitRunConfig::cursor_coord_y, InitRunConfig::cursor_enable, InitRunConfig::cursor_size_x, InitRunConfig::cursor_size_y, InitRunConfig::operatingmode, InitRunConfig::output_format, InitRunConfig::partial_plane_blend_enable, InitRunConfig::presentationmode, InitRunConfig::sdp_enable, InitRunConfig::stream1_format, InitRunConfig::stream2_format, XDCSUB_OPMODE_FUNCTIONAL, XDCSUB_PPTMODE_LIVE, XDCSUB_PPTMODE_MIXED, XDCSUB_PPTMODE_NONLIVE, XDpDc_ConfigureCursor, XDpDc_ConfigureFormat, XDpDc_ConfigureOutputFormat, XDpDc_ConfigurePartialPlane, XDpDc_ConfigureResolution, XDpDc_DisplayConfig, XDpDc_MainHelpMenu.
Referenced by main.
static u32 read_hex(void)
Reads a hex value from UART input, terminated by Enter.
Accepts 0-9, a-f, A-F. Supports backspace. Optional "0x" prefix is skipped.
void XDpDc_AuxMenu(XMmiDp *DpPtr)
AUX Read/Write submenu.
Allows the user to perform DPCD AUX read and write transactions with configurable address, data, and iteration count. DpPtr - Pointer to the initialized XMmiDp instance
Referenced by main.
void XDpDc_InitConfigDefaults(InitRunConfig *config)
This function initializes the InitRunConfig with default values.
config - Pointer to InitRunConfig structure None None
References InitRunConfig::audio_channels, InitRunConfig::audio_enable, InitRunConfig::avpg, AvpgRunConfig::bpc, InitRunConfig::byp_stream_pix_mode, InitRunConfig::byp_stream_sdp_en, InitRunConfig::byp_stream_vid_mode, InitRunConfig::byp_streams, AvpgRunConfig::colorimetry, InitRunConfig::cursor_coord_x, InitRunConfig::cursor_coord_y, InitRunConfig::cursor_enable, InitRunConfig::cursor_size_x, InitRunConfig::cursor_size_y, DC_BASEADDR, InitRunConfig::frame_rate, InitRunConfig::height, InitRunConfig::lane_count, InitRunConfig::link_rate, InitRunConfig::livevideo01mode, InitRunConfig::livevideo02mode, InitRunConfig::livevideoalphaen, InitRunConfig::livevideosdpen, InitRunConfig::livevidselect, InitRunConfig::operatingmode, InitRunConfig::output_format, InitRunConfig::partial_plane_blend_enable, AvpgRunConfig::pattern, AvpgRunConfig::pix_fmt, InitRunConfig::ppb_coord_x, InitRunConfig::ppb_coord_y, InitRunConfig::ppb_offset_x, InitRunConfig::ppb_offset_y, InitRunConfig::ppb_size_x, InitRunConfig::ppb_size_y, InitRunConfig::ppb_stream_select, AvpgRunConfig::ppc, InitRunConfig::presentationmode, InitRunConfig::sdp_enable, InitRunConfig::stream1_format, InitRunConfig::stream2_format, InitRunConfig::width, XDCSUB_LIVVID_SEL_BOTH, XDCSUB_LIVVID_SEL_NONE, XDCSUB_LIVVID_SEL_V01, XDCSUB_LIVVID_SEL_V02, XDCSUB_OPMODE_BYPASS, XDCSUB_OPMODE_FUNCTIONAL, XDCSUB_PPTMODE_LIVE, XDCSUB_PPTMODE_MIXED, XDCSUB_PPTMODE_NONLIVE, XDCSUB_VIDMODE_AV, XDCSUB_VIDMODE_NONE, XDCSUB_VIDMODE_VONLY.
Referenced by main.