mmi_dc_cursor.h
CURSOR_BUFFER_ADDR
CURSOR_RED_OPAQUE
CURSOR_TRANSPARENT
void XDpDc_InitCursorFrameBuffer(RunConfig *RunCfgPtr)
This function initializes the cursor frame buffer.
RunCfgPtr - Pointer to RunConfig structure None Sets up cursor frame buffer with RGBA4444 format
References FrameInfo::Address, FrameInfo::Bpc, RunConfig::Cursor_FbInfo, FrameInfo::Height, FrameInfo::VideoFormat, FrameInfo::Width, XDpDc_GenerateFrameInfoAttribute.
Referenced by XDpDc_InitFrames.
void XDpDc_FillCursorBuffer(RunConfig *RunCfgPtr)
This function fills the cursor buffer with a red circle pattern.
RunCfgPtr - Pointer to RunConfig structure None RGBA4444 format: 16-bit per pixel, bit layout from MSB to LSB: Bits 15-12: Alpha[3:0] Bits 11-8: Blue[3:0] Bits 7-4: Green[3:0] Bits 3-0: Red[3:0] Red (opaque) = 0xF00F (A=F, B=0, G=0, R=F) Transparent = 0x0000 (all zeros)
References XDc_WriteReg.
Referenced by XDpDc_InitFrames.
void XDpDc_ConfigureCursorBlend(RunConfig *RunCfgPtr)
This function configures cursor blend parameters using DCsub APIs.
RunCfgPtr - Pointer to RunConfig structure None Uses XDcSub_SetCursorBlend and XDcSub_SetSdpCursorBuffers APIs to configure cursor parameters. Must be called BEFORE hardware init. Hardware registers are written during XDcSub_ConfigureDcVideo()
References RunConfig::CursorCoordX, RunConfig::CursorCoordY, RunConfig::CursorSizeX, RunConfig::CursorSizeY, RunConfig::DcSubPtr, XDc_GetNonLiveVideoAttribute, XDcSub_SetCursorBlend, XDcSub_SetSdpCursorBuffers.
Referenced by XDpDc_InitDcSubPtr.
void XDpDc_ConfigureCursorDMA(RunConfig *RunCfgPtr)
This function configures cursor DMA channel.
RunCfgPtr - Pointer to RunConfig structure None Sets up SDP DMA channel for cursor data transfer
References RunConfig::DcSubPtr, RunConfig::Desc7.
Referenced by XDpDc_InitDcSubsystem.