mmi_dp_init.c
XMMIDP_AUX_250US_LIMIT
XMMIDP_AUX_2000US_LIMIT
XMMIDP_AUX_100000US_LIMIT
XMMIDP_PM_CONFIG1_DEFAULT
XMMIDP_PM_CONFIG2_DEFAULT
XMMIDP_GEN_INT_EN_DEFAULT
XMMIDP_HPD_INT_EN_DEFAULT
XMMIDP_SINK_POWER_DOWN
XMMIDP_SINK_POWER_UP
XMMIDP_SINK_POWERDOWN_DELAY
XMMIDP_SINK_POWERUP_DELAY
XMMIDP_DEFAULT_BPC
XMMIDP_PIX_MODE_SINGLE
XMMIDP_VID_STREAM_ENABLE
XMMIDP_AUD_CH_PER_DATA_INPUT
XMMIDP_AUD_DATA_INPUT_LSB
XMMIDP_AUD_DATA_INPUT_ALL
XMMIDP_AUD_HBR_MODE_DISABLE
XMMIDP_AUD_TIMESTAMP_VER
XMMIDP_SDP_STREAM_ENABLE
void XMmiDp_SinkPowerCycle(XMmiDp *DpPsuPtr)
This function power cycles the sink by powering it down and then back up with appropriate delays to allow the monitor to transition states.
DpPsuPtr is a pointer to the XMmiDp instance. None. None.
References XMmiDp_SinkPowerDown, XMmiDp_SinkPowerUp.
void XMmiDp_SinkPowerDown(XMmiDp *DpPsuPtr)
This function puts the sink into power saving mode by writing 0x0 to the DPCD SET_POWER register.
DpPsuPtr is a pointer to the XMmiDp instance. None. None.
Referenced by main, XMmiDp_SinkPowerCycle.
void XMmiDp_SinkPowerUp(XMmiDp *DpPsuPtr)
This function wakes the sink from power saving mode by writing 0x1 to the DPCD SET_POWER register.
DpPsuPtr is a pointer to the XMmiDp instance. None. None.
Referenced by main, XDpDc_HpdHotplugHandler, XMmiDp_SinkPowerCycle.
static void XDpDc_PrintVideoConfigRegs(XMmiDp *InstancePtr, u8 Stream)
static void XDpDc_PrintVideoStreamConfig(XMmiDp *InstancePtr, u8 Stream)
This function prints the video stream, MSA, link, and TU configuration from InstancePtr after XMmiDp_SetVidControllerUseStdVidMode has populated all the fields.
InstancePtr is a pointer to the XMmiDp instance. Stream is the stream ID (XMMIDP_STREAM_ID1..ID4). None.
void XMmiDp_SetupVideoStream(RunConfig *RunCfgPtr)
This function sets up the video stream by clearing the video controller, configuring MSA bits per color, pixel mode, video mapping, and applying the standard 640x480 video mode timing.
RunCfgPtr is a pointer to the application configuration structure. None. None.
References RunConfig::DpPsuPtr, RunConfig::VideoMode.
Referenced by XDpDc_HpdHotplugHandler, XDpDc_HpdIrqHandler.
void XMmiDp_SetupAudioStream(RunConfig *RunCfgPtr)
This function configures the audio stream by setting the audio interface, data input, data width, channel count, mute flag, timestamp, clock multiplier, and enabling SDP vertical/horizontal audio streams.
RunCfgPtr is a pointer to the application configuration structure. None. None.
References RunConfig::AudioChannels, RunConfig::DpPsuPtr.
Referenced by XDpDc_HpdHotplugHandler, XDpDc_HpdIrqHandler.
static const char* XDpDc_LinkBwToStr(u8 LinkBW, u32 *RateMbps)
static void XDpDc_ApplyUserCaps(XMmiDp *InstancePtr, u8 UserMaxLanes, u8 UserMaxLinkBW)
static void XDpDc_PrintSinkCapabilities(XMmiDp *InstancePtr)
static void XDpDc_PrintLinkTrainingResult(XMmiDp *InstancePtr, u32 TrainingStatus)
u32 XMmiDp_StartFullLinkTrainingCapped(XMmiDp *InstancePtr, u8 UserMaxLanes, u8 UserMaxLinkBW)
This function prepares for link training.
It reads receiver capabilities, applies user-configured lane/bandwidth caps, checks current link status, configures link parameters, and runs the clock recovery and channel equalization training sequence. InstancePtr is a pointer to the XMmiDp instance. UserMaxLanes User-configured max lane count (0=auto, 1, 2, or 4). UserMaxLinkBW User-configured max link BW in DPCD format (0=auto, 0x06=RBR, 0x0A=HBR, 0x14=HBR2, 0x1E=HBR3). XST_SUCCESS if the training process succeeded.XST_FAILURE otherwise. None.
Referenced by XDpDc_HpdHotplugHandler, XDpDc_HpdIrqHandler.
u32 XMmiDp_InitDpCore(XMmiDp *InstancePtr)
This function initializes the DP core by performing a PHY soft reset, powering on the PHY, configuring AUX timer limits, PM configuration, disabling SSC, and enabling general/HPD interrupts.
InstancePtr is a pointer to the XMmiDp instance. XST_SUCCESS. None.
Referenced by XDpDc_InitDpPsuSubsystem.
u32 XDpDc_InitDpPsuSubsystem(RunConfig *RunCfgPtr)
This function initializes the DisplayPort subsystem.
It configures the DP core, polls for HPD, power cycles the sink, runs link training, and sets up the video and audio streams. RunCfgPtr is a pointer to the application configuration structure. XST_SUCCESS if successful, otherwise XST_FAILURE. None.
References RunConfig::AudioEnable, DP_BASEADDR, RunConfig::DpPsuPtr, RunConfig::SdpEnable, XDpDc_DisableDpAudioSdpStreams, XMmiDp_InitDpCore.
Referenced by XDpDc_InitPlatform.