mmi_dc_sdp.c
XDPDC_SDP_CHANNELS
XDPDC_SDP_CHANNEL_ALLOC
XDPDC_SDP_SAMPLE_SIZE_16BIT
XDPDC_SDP_AUDIO_FREQ_48K
void XDpDc_InitSdpFrameBuffer(RunConfig *RunCfgPtr)
This function initializes the SDP frame buffer metadata.
RunCfgPtr - Pointer to RunConfig structure None SDP data is generated in memory at XDPDC_SDP_BUFFER_ADDR
References FrameInfo::Address, FrameInfo::LineSize, RunConfig::Sdp_FbInfo, FrameInfo::Size, FrameInfo::Stride.
Referenced by XDpDc_InitFrames.
void XDpDc_FillSdpBuffer(RunConfig *RunCfgPtr)
This function generates SDP packets into the SDP memory buffer.
RunCfgPtr - Pointer to RunConfig structure None RunCfgPtr is unused and kept for API symmetry
References XDc_WriteReg.
Referenced by XDpDc_InitFrames.
void XDpDc_ConfigureSdp(RunConfig *RunCfgPtr)
This function configures SDP controls in DC subsystem.
RunCfgPtr - Pointer to RunConfig structure None Must be called before XDcSub_ConfigureDcVideo()
References RunConfig::DcSubPtr, XDcSub_EnableSdp, XDcSub_SetCursorSdpRdyInterval, XDcSub_SetSdp, XDcSub_SetSdpAckSel, XDcSub_SetSdpCursorBuffers.
Referenced by XDpDc_InitDcSubPtr.
void XDpDc_SetupSdpDescriptor(RunConfig *RunCfgPtr)
This function creates the SDP DMA descriptor (Desc7) and links it to the SDP packet buffer.
RunCfgPtr - Pointer to RunConfig structure None Must be called after XDcDma_CfgInitialize()
References FrameInfo::Address, RunConfig::Desc7, RunConfig::Sdp_FbInfo, XDpDc_CreateDescriptors.
Referenced by XDpDc_InitDcSubsystem.
void XDpDc_ConfigureSdpDMA(RunConfig *RunCfgPtr)
This function configures SDP DMA channel trigger state.
RunCfgPtr - Pointer to RunConfig structure None Desc7 must be initialized before calling this API
References RunConfig::DcSubPtr, RunConfig::Desc7.
Referenced by XDpDc_InitDcSubsystem.