mmi_dc_setup_frames.h
void XDpDc_GenerateFrameInfoAttribute(FrameInfo *Frame)
This function computes the frame buffer Size, LineSize, and Stride attributes from the Width, Height, and Bpc fields of a FrameInfo structure.
Stride is aligned to a 256-byte boundary. Frame is a pointer to the FrameInfo structure to populate. None. None.
References FrameInfo::Bpc, FrameInfo::Height, FrameInfo::LineSize, FrameInfo::Size, FrameInfo::Stride, FrameInfo::Width.
Referenced by XDpDc_InitCursorFrameBuffer.
void XDpDc_CreateDescriptors(RunConfig *RunCfgPtr, XDcDma_Descriptor *XDesc, FrameInfo *FBInfo, XDcDma_Descriptor *NextDesc)
This function initializes a DMA descriptor with source address, data size, line size, stride, and next descriptor linkage from the given FrameInfo.
For cursor descriptors, Target_Addr is also set. RunCfgPtr is a pointer to the application configuration structure. XDesc is a pointer to the DMA descriptor to initialize. FBInfo is a pointer to the FrameInfo containing buffer attributes. NextDesc is a pointer to the next descriptor in the chain, or NULL for a self-linked (last) descriptor. None. None.
References FrameInfo::Address, RunConfig::Cursor_FbInfo, RunConfig::DcSubPtr, RunConfig::Desc7, FrameInfo::LineSize, RunConfig::Sdp_FbInfo, FrameInfo::Size, FrameInfo::Stride, XDcDma_DescInit, XDcDma_GetNewDescId.
Referenced by XDpDc_SetupAudioDescriptors, XDpDc_SetupCursorDescriptor, XDpDc_SetupSdpDescriptor, XDpDc_SetupStream1Descriptors, XDpDc_SetupStream2Descriptors.
void XDpDc_InitFrames(RunConfig *RunCfgPtr)
This function initializes video, cursor, and audio frame buffers.
Buffer initialization is format-aware: the number of planes per stream isdetermined by the video format mode (Interleaved/SemiPlanar/Planar). V1-V3 are Stream1 planes, V4-V6 are Stream2 planes. RunCfgPtr is a pointer to the application configuration structure. None. Descriptor creation is handled separately by XDpDc_SetupStream1Descriptors and XDpDc_SetupStream2Descriptors, which must be called after DMA hardware initialization.
References FrameInfo::Address, RunConfig::AudioEnable, RunConfig::CursorEnable, RunConfig::SdpEnable, FrameInfo::Size, XDpDc_FillCursorBuffer, XDpDc_FillSdpBuffer, XDpDc_GenerateFrames, XDpDc_InitCursorFrameBuffer, XDpDc_InitSdpFrameBuffer, XDpDc_SetupAudioDescriptors.
Referenced by XDpDc_InitializeRunConfig.
void XDpDc_SetupStream1Descriptors(RunConfig *RunCfgPtr)
This function creates DMA descriptors for Stream1 and assigns them to Video DMA channels 0-2.
The number of descriptors depends on the video format mode: Interleaved=1, SemiPlanar=2, Planar=3. Uses switch fall-through from Planar -> SemiPlanar -> Interleaved. RunCfgPtr is a pointer to the application configuration structure. None. Must be called after XDcDma_CfgInitialize().
References FrameInfo::Address, RunConfig::DcSubPtr, RunConfig::Desc1, RunConfig::Desc2, RunConfig::Desc3, RunConfig::Stream1Format, RunConfig::V1_FbInfo, RunConfig::V2_FbInfo, RunConfig::V3_FbInfo, XDc_GetNonLiveVideoAttribute, XDpDc_CreateDescriptors.
Referenced by XDpDc_InitDcSubsystem.
void XDpDc_SetupStream2Descriptors(RunConfig *RunCfgPtr)
This function creates DMA descriptors for Stream2 and assigns them to Graphics DMA channels 3-5.
The number of descriptors depends on the video format mode: Interleaved=1, SemiPlanar=2, Planar=3. Uses switch fall-through from Planar -> SemiPlanar -> Interleaved. RunCfgPtr is a pointer to the application configuration structure. None. Must be called after XDcDma_CfgInitialize().
References FrameInfo::Address, RunConfig::DcSubPtr, RunConfig::Desc4, RunConfig::Desc5, RunConfig::Desc6, RunConfig::Stream2Format, RunConfig::V4_FbInfo, RunConfig::V5_FbInfo, RunConfig::V6_FbInfo, XDc_GetNonLiveVideoAttribute, XDpDc_CreateDescriptors.
Referenced by XDpDc_InitDcSubsystem.
void XDpDc_SetupCursorDescriptor(RunConfig *RunCfgPtr)
This function creates the cursor DMA descriptor (Desc7) and links it to the cursor frame buffer.
RunCfgPtr is a pointer to the application configuration structure. None. Must be called after XDcDma_CfgInitialize() and only when cursor is enabled.
References FrameInfo::Address, RunConfig::Cursor_FbInfo, RunConfig::Desc7, XDpDc_CreateDescriptors.
Referenced by XDpDc_InitDcSubsystem.
void XDpDc_SetupAudioDescriptors(RunConfig *RunCfgPtr)
This function creates the audio DMA descriptors (AudDesc0-7) as a chained ring buffer for audio streaming.
RunCfgPtr is a pointer to the application configuration structure. None. Must be called after XDcDma_CfgInitialize() and only when audio is enabled.
References XDpDc_CreateDescriptors.
Referenced by XDpDc_InitFrames.