mmi_dc_setup_frames.c
UPDATE_ENABLE_SHIFT
IGNORE_DONE_SHIFT
LAST_DESC_SHIFT
LAST_DESC_FRAME_SHIFT
XDcDma_Descriptor* Desc1
XDcDma_Descriptor* Desc2
XDcDma_Descriptor* Desc3
XDcDma_Descriptor* Desc4
XDcDma_Descriptor* Desc5
XDcDma_Descriptor* Desc6
XDcDma_Descriptor* Desc7
XDcDma_Descriptor* AudDesc0
XDcDma_Descriptor* AudDesc1
XDcDma_Descriptor* AudDesc2
XDcDma_Descriptor* AudDesc3
XDcDma_Descriptor* AudDesc4
XDcDma_Descriptor* AudDesc5
XDcDma_Descriptor* AudDesc6
XDcDma_Descriptor* AudDesc7
FrameInfo Aud0_FbInfo
FrameInfo Aud1_FbInfo
FrameInfo Aud2_FbInfo
FrameInfo Aud3_FbInfo
FrameInfo Aud4_FbInfo
FrameInfo Aud5_FbInfo
FrameInfo Aud6_FbInfo
FrameInfo Aud7_FbInfo
static u32 XDpDc_GetFormatBpc(XDc_VideoFormat fmt)
This function returns the per-plane bytes per component for a given video format.
The value represents how many bytes each pixel occupies in a single DMA plane buffer. fmt is the video format enum. Bytes per component for the format. Values are derived from hardware-validated test configurations.
void XDpDc_GenerateFrameInfoAttribute(FrameInfo *Frame)
This function computes the frame buffer Size, LineSize, and Stride attributes from the Width, Height, and Bpc fields of a FrameInfo structure.
Stride is aligned to a 256-byte boundary. Frame is a pointer to the FrameInfo structure to populate. None. None.
References FrameInfo::Bpc, FrameInfo::Height, FrameInfo::LineSize, FrameInfo::Size, FrameInfo::Stride, FrameInfo::Width.
Referenced by XDpDc_InitCursorFrameBuffer.
void XDpDc_CreateDescriptors(RunConfig *RunCfgPtr, XDcDma_Descriptor *XDesc, FrameInfo *FBInfo, XDcDma_Descriptor *NextDesc)
This function initializes a DMA descriptor with source address, data size, line size, stride, and next descriptor linkage from the given FrameInfo.
For cursor descriptors, Target_Addr is also set. RunCfgPtr is a pointer to the application configuration structure. XDesc is a pointer to the DMA descriptor to initialize. FBInfo is a pointer to the FrameInfo containing buffer attributes. NextDesc is a pointer to the next descriptor in the chain, or NULL for a self-linked (last) descriptor. None. None.
References FrameInfo::Address, RunConfig::Cursor_FbInfo, RunConfig::DcSubPtr, RunConfig::Desc7, FrameInfo::LineSize, RunConfig::Sdp_FbInfo, FrameInfo::Size, FrameInfo::Stride, XDcDma_DescInit, XDcDma_GetNewDescId.
Referenced by XDpDc_SetupAudioDescriptors, XDpDc_SetupCursorDescriptor, XDpDc_SetupSdpDescriptor, XDpDc_SetupStream1Descriptors, XDpDc_SetupStream2Descriptors.
static int Is30BitPacked(XDc_VideoFormat fmt)
static void InitFrameBuffer(FrameInfo *FbInfo, u64 Address, u32 Width, u32 Height, XDc_VideoFormat Format, u32 Bpc)
This function initializes a single FrameInfo structure with the given buffer address, dimensions, format, and BPC, then computes derived attributes (Size, LineSize, Stride).
FbInfo is a pointer to the FrameInfo to initialize. Address is the buffer base address. Width is the frame width in pixels. Height is the frame height in pixels. Format is the video format enum. Bpc is the bytes per component for this plane. None. None.
static void InitStream1Buffers(RunConfig *RunCfgPtr)
This function initializes Stream1 frame buffers (V1, V2, V3) based on the video format mode using switch fall-through: Planar -> sets V3, falls through to SemiPlanar -> sets V2, falls through to Interleaved -> sets V1.
BPC is auto-derived from the format. RunCfgPtr is a pointer to the application configuration structure. None. V1-V3 are Stream1 planes (Desc1-3, Video channels 0-2).
static void InitStream2Buffers(RunConfig *RunCfgPtr)
This function initializes Stream2 frame buffers (V4, V5, V6) based on the video format mode using switch fall-through: Planar -> sets V6, falls through to SemiPlanar -> sets V5, falls through to Interleaved -> sets V4.
BPC is auto-derived from the format. RunCfgPtr is a pointer to the application configuration structure. None. V4-V6 are Stream2 planes (Desc4-6, Graphics channels 3-5).
void XDpDc_InitFrames(RunConfig *RunCfgPtr)
This function initializes video, cursor, and audio frame buffers.
Buffer initialization is format-aware: the number of planes per stream isdetermined by the video format mode (Interleaved/SemiPlanar/Planar). V1-V3 are Stream1 planes, V4-V6 are Stream2 planes. RunCfgPtr is a pointer to the application configuration structure. None. Descriptor creation is handled separately by XDpDc_SetupStream1Descriptors and XDpDc_SetupStream2Descriptors, which must be called after DMA hardware initialization.
References FrameInfo::Address, RunConfig::AudioEnable, RunConfig::CursorEnable, RunConfig::SdpEnable, FrameInfo::Size, XDpDc_FillCursorBuffer, XDpDc_FillSdpBuffer, XDpDc_GenerateFrames, XDpDc_InitCursorFrameBuffer, XDpDc_InitSdpFrameBuffer, XDpDc_SetupAudioDescriptors.
Referenced by XDpDc_InitializeRunConfig.
void XDpDc_SetupStream1Descriptors(RunConfig *RunCfgPtr)
This function creates DMA descriptors for Stream1 and assigns them to Video DMA channels 0-2.
The number of descriptors depends on the video format mode: Interleaved=1, SemiPlanar=2, Planar=3. Uses switch fall-through from Planar -> SemiPlanar -> Interleaved. RunCfgPtr is a pointer to the application configuration structure. None. Must be called after XDcDma_CfgInitialize().
References FrameInfo::Address, RunConfig::DcSubPtr, RunConfig::Desc1, RunConfig::Desc2, RunConfig::Desc3, RunConfig::Stream1Format, RunConfig::V1_FbInfo, RunConfig::V2_FbInfo, RunConfig::V3_FbInfo, XDc_GetNonLiveVideoAttribute, XDpDc_CreateDescriptors.
Referenced by XDpDc_InitDcSubsystem.
void XDpDc_SetupStream2Descriptors(RunConfig *RunCfgPtr)
This function creates DMA descriptors for Stream2 and assigns them to Graphics DMA channels 3-5.
The number of descriptors depends on the video format mode: Interleaved=1, SemiPlanar=2, Planar=3. Uses switch fall-through from Planar -> SemiPlanar -> Interleaved. RunCfgPtr is a pointer to the application configuration structure. None. Must be called after XDcDma_CfgInitialize().
References FrameInfo::Address, RunConfig::DcSubPtr, RunConfig::Desc4, RunConfig::Desc5, RunConfig::Desc6, RunConfig::Stream2Format, RunConfig::V4_FbInfo, RunConfig::V5_FbInfo, RunConfig::V6_FbInfo, XDc_GetNonLiveVideoAttribute, XDpDc_CreateDescriptors.
Referenced by XDpDc_InitDcSubsystem.
void XDpDc_SetupCursorDescriptor(RunConfig *RunCfgPtr)
This function creates the cursor DMA descriptor (Desc7) and links it to the cursor frame buffer.
RunCfgPtr is a pointer to the application configuration structure. None. Must be called after XDcDma_CfgInitialize() and only when cursor is enabled.
References FrameInfo::Address, RunConfig::Cursor_FbInfo, RunConfig::Desc7, XDpDc_CreateDescriptors.
Referenced by XDpDc_InitDcSubsystem.
void XDpDc_SetupAudioDescriptors(RunConfig *RunCfgPtr)
This function creates the audio DMA descriptors (AudDesc0-7) as a chained ring buffer for audio streaming.
RunCfgPtr is a pointer to the application configuration structure. None. Must be called after XDcDma_CfgInitialize() and only when audio is enabled.
References XDpDc_CreateDescriptors.
Referenced by XDpDc_InitFrames.