mmi_dpdc_platform.h
MMI_DPDC_PLATFORM_H_
Prevent circular inclusions by using protection macros.
DC_BASEADDR
DC base address.
Referenced by XDpDc_InitConfigDefaults, XDpDc_InitDcSubPtr.
DCDMA_BASEADDR
DC DMA base address.
Referenced by XDpDc_InitDcSubsystem.
DP_BASEADDR
DP base address.
Referenced by XDpDc_InitDpPsuSubsystem.
XDcDma_Descriptor* AudDesc0
u32 XClk_WaitForLock(XClk_Wiz_Config *CfgPtr)
This function waits for the clock wizard to lock.
CfgPtr is a pointer to the clock wizard configuration XST_SUCCESS if locked, else XST_FAILURE None.
Referenced by XDpDc_InitClkWiz.
u32 XDpDc_InitClkWiz(RunConfig *RunCfgPtr)
This function initializes the Clock Wizard IP for video and audio clocks.
RunCfgPtr is a pointer to the application configuration structure XST_SUCCESS if successful, else XST_FAILURE None.
References RunConfig::AudioEnable, RunConfig::PixelClkHz, XClk_WaitForLock.
Referenced by XDpDc_InitPlatform.
u32 XDpDc_InitDcSubsystem(RunConfig *RunCfgPtr)
This function initializes the Display Controller Subsystem.
RunCfgPtr is a pointer to the application configuration structure XST_SUCCESS if successful, else XST_FAILURE None.
References RunConfig::AudioEnable, RunConfig::CursorEnable, DCDMA_BASEADDR, RunConfig::DcSubPtr, RunConfig::operatingmode, RunConfig::presentationmode, RunConfig::SdpEnable, RunConfig::Stream1Format, RunConfig::Stream2Format, XDc_AudClkSelect, XDc_AudioSoftReset, XDc_GetNonLiveVideoAttribute, XDc_SetVideoTiming, XDc_SetVidFrameSwitch, XDc_VidClkSelect, XDc_VideoSoftReset, XDcDma_CfgInitialize, XDcDma_WriteProtDisable, XDcSub_ConfigureDcVideo, XDcSub_Initialize, XDCSUB_OPMODE_FUNCTIONAL, XDCSUB_PPTMODE_LIVE, XDCSUB_PPTMODE_MIXED, XDCSUB_PPTMODE_NONLIVE, XDpDc_ConfigureCursorDMA, XDpDc_ConfigureSdpDMA, XDpDc_SetupCursorDescriptor, XDpDc_SetupSdpDescriptor, XDpDc_SetupStream1Descriptors, XDpDc_SetupStream2Descriptors.
Referenced by XDpDc_InitPlatform.
void XDpDc_SetupInterrupts(RunConfig *RunCfgPtr)
This function sets up interrupt handlers for DMA interrupts.
RunCfgPtr is a pointer to the application configuration structure None. None.
References RunConfig::DcSubPtr, XDcDma_InterruptEnable, XDpDc_SetupDpInterrupts.
Referenced by XDpDc_InitPlatform.
u32 XDpDc_InitPlatform(RunConfig *RunCfgPtr)
This function initializes all platform blocks (clocks, DC, DP, interrupts)
RunCfgPtr is a pointer to the application configuration structure XST_SUCCESS if successful, else XST_FAILURE None.
References XDpDc_InitClkWiz, XDpDc_InitDcSubsystem, XDpDc_InitDpPsuSubsystem, XDpDc_SetupInterrupts.
Referenced by XDpDc_MmiDcNonliveTest.