mmi_dc_nonlive_test.c
CLK_LOCK
PL_AUD_CLK_MULT
NL_LATENCY
V_LINE_LATENCY
XDCDMA_IEN_VSYNC_INT_MASK
XDCDMA_INTR_ID
XDCDMA_INTR_PARENT
RunConfig RunCfg
XDcSub DcSub
XDcDma DcDma
XDc Dc
XMmiDp DpPsuPtr
FrameInfo Video1FbPtr
FrameInfo Video2FbPtr
FrameInfo Video3FbPtr
FrameInfo Video4FbPtr
FrameInfo Video5FbPtr
FrameInfo Video6FbPtr
FrameInfo CursorFbPtr
FrameInfo SdpFbPtr
XDcDma_Descriptor* Desc1
XDcDma_Descriptor* Desc2
XDcDma_Descriptor* Desc3
XDcDma_Descriptor* Desc4
XDcDma_Descriptor* Desc5
XDcDma_Descriptor* Desc6
XDcDma_Descriptor* Desc7
XDcDma_Descriptor* AudDesc0
XDcDma_Descriptor* AudDesc1
XDcDma_Descriptor* AudDesc2
XDcDma_Descriptor* AudDesc3
XDcDma_Descriptor* AudDesc4
XDcDma_Descriptor* AudDesc5
XDcDma_Descriptor* AudDesc6
XDcDma_Descriptor* AudDesc7
u32 CSCCoeff_RGB[][]
u32 CSCOffset_RGB[][]
u32 In_CSCCoeff_YUV[][]
u32 In_CSCOffset_YUV[][]
u32 Out_CSCCoeff_YUV[][]
u32 Out_CSCOffset_YUV[][]
XDc_VideoTiming VidTiming_640_480
u32 XDpDc_InitDcSubPtr(RunConfig *RunCfgPtr)
This function configures the DC subsystem pointer with video timing, stream sources, input/output formats, CSC coefficients, global alpha, audio settings, cursor blend, and partial plane blend parameters.
RunCfgPtr is a pointer to the application configuration structure. XST_SUCCESS if audio/video settings are valid, otherwise XST_FAILURE. Cursor blend and partial plane blend are configured here before hardware init (XDcSub_ConfigureDcVideo).
References RunConfig::AudioChannels, RunConfig::AudioEnable, RunConfig::CursorEnable, DC_BASEADDR, RunConfig::DcSubPtr, RunConfig::OutStreamFormat, RunConfig::SdpEnable, RunConfig::Stream1Format, RunConfig::Stream1PbEnable, RunConfig::Stream2Format, RunConfig::Stream2PbEnable, RunConfig::VideoMode, XDc_GetNonLiveVideoAttribute, XDc_GetOutputVideoAttribute, XDcSub_AudClkSelect, XDcSub_AudioChannelSelect, XDcSub_EnableAudio, XDcSub_EnableAudioBuffer, XDcSub_EnableStream1Buffers, XDcSub_EnableStream2Buffers, XDcSub_SetAudInterfaceMode, XDcSub_SetAudioChCtrl, XDcSub_SetAudioVideoClkSrc, XDcSub_SetGlobalAlpha, XDcSub_SetInputAudioSelect, XDcSub_SetInputNonLiveVideoFormat, XDcSub_SetInputStreamCSC, XDcSub_SetInputStreamLayerControl, XDcSub_SetNonLiveLatency, XDcSub_SetOutputStreamCSC, XDcSub_SetOutputVideoFormat, XDcSub_SetStreamPixelScaling, XDcSub_SetVidFrameSwitch, XDcSub_SetVidInterfaceMode, XDcSub_SetVidStreamSrc, XDcSub_VidClkSelect, XDpDc_ConfigureCursorBlend, XDpDc_ConfigurePartialPlaneBlend, XDpDc_ConfigureSdp.
Referenced by XDpDc_InitializeRunConfig.
u32 XDpDc_InitializeRunConfig(RunConfig *RunCfgPtr)
This function initializes the application configuration by assigning DC subsystem, DMA, DP, and frame buffer pointers, then initializing frames and configuring the DC subsystem.
RunCfgPtr is a pointer to the application configuration structure. XST_SUCCESS if successful, else XST_FAILURE. User-configurable parameters (resolution, format, cursor, audio) are set from the menu in main() before this function is called.
References RunConfig::Cursor_FbInfo, RunConfig::DcSubPtr, RunConfig::Desc1, RunConfig::Desc2, RunConfig::Desc3, RunConfig::Desc4, RunConfig::Desc5, RunConfig::Desc6, RunConfig::Desc7, RunConfig::DpPsuPtr, RunConfig::Sdp_FbInfo, RunConfig::V1_FbInfo, RunConfig::V2_FbInfo, RunConfig::V3_FbInfo, RunConfig::V4_FbInfo, RunConfig::V5_FbInfo, RunConfig::V6_FbInfo, XDpDc_InitDcSubPtr, XDpDc_InitFrames.
Referenced by XDpDc_MmiDcNonliveTest.
u32 XDpDc_MmiDcNonliveTest(RunConfig *RunCfgPtr)
The purpose of this function is to configure the test params and the platform driver & Xdc driver to set DC Mode.
RunCfgPtr is a pointer to the application configuration structure. XST_SUCCESS if successful, else XST_FAILURE. None.
References XDpDc_InitializeRunConfig, XDpDc_InitPlatform.
Referenced by main.