xdc.h
XDC_MAX_IN_STREAMS
Maximum number of input streams allowed.
XDc_VideoFormat
XDc_VidInterface
XDc_AudInterface
XDc_VideoStream1
XDc_VideoStream2
XDc_AudioStream
XDc_AlphaBlend
XDc_ChromaBlend
XDc_ChromaMaster
XDc_VideoModes
XDc_Sdp
XDc_AudEn
XDc_PartialBlendEn
XDc_CursorBlend
void XDc_CfgInitialize(XDc *InstancePtr, u32 BaseAddr)
This function initializes the configuration for the DC Instance.
InstancePtr is a pointer to the XDc instance. BaseAddr sets the base address of the DC instance DeviceId is the id of the device from the design. None. Base address and DeviceId is same as the DP Core driver.
Referenced by XDcSub_CfgInitialize.
void XDc_Initialize(XDc *InstancePtr)
This function initializes all the data structures of the XDc Instance.
InstancePtr is a pointer to the XDc instance. None. None.
References XDc_WriteReg, XDC_AUD_SOFT_RST.
void XDc_WriteProtEnable(XDc *InstancePtr)
This function disables writes to DC.
InstancePtr is a pointer to the XDc instance. None.
References XDc_WriteReg, XDC_WPROTS.
void XDc_WriteProtDisable(XDc *InstancePtr)
This function enables writes to DC.
InstancePtr is a pointer to the XDc instance. None.
References XDc_WriteReg, XDC_WPROTS.
Referenced by XDcSub_Initialize.
void XDc_SetVidInterfaceMode(XDc *InstancePtr)
This function sets the mode for DC Instance.
DC can be either in bypass mode or functional mode InstancePtr is a pointer to the XDc instance. None.
References XDc_WriteReg, XDC_DC_BYPASS.
Referenced by XDcSub_Initialize.
void XDc_SetBlenderBgColor(XDc *InstancePtr)
This function sets the blender background color.
InstancePtr is an pointer to the XDc Instance. Color is a pointer to the structure XDc_BlenderBgClr None. None.
References XDc_WriteReg, XDC_V_BLEND_BG_CLR_0, XDC_V_BLEND_BG_CLR_1, XDC_V_BLEND_BG_CLR_2.
void XDc_SetGlobalAlpha(XDc *InstancePtr)
This function enables or disables global alpha.
InstancePtr is an pointer to the XDc Instance. None. GlobalAlphaEn = 1, enables the global alpha. GlobalAlphaEn = 0, disables the global alpha. Alpha = 0, transparent Alpha = 255, Opaque Alpha = 8:1 (Alpha value)
References XDc_WriteReg, XDC_V_BLEND_SET_GLOBAL_ALPHA_REG.
Referenced by XDcSub_ConfigureDcVideo.
void XDc_SetInputVideoSelect(XDc *InstancePtr)
This function selects the source type for the Video and Graphics input streams that are passed on to the blender block.
InstancePtr is a pointer to the XDc instance. None. None.
References XDc_ReadReg, XDC_AV_BUF_OUTPUT_AUD_VID_SELECT, XDc_WriteReg.
Referenced by XDcSub_ConfigureDcVideo.
void XDc_SetInputAudioSelect(XDc *InstancePtr)
This function selects the source type for audio stream.
InstancePtr is a pointer to the XDc instance. None. None.
References XDc_ReadReg, XDC_AV_BUF_OUTPUT_AUD_VID_SELECT, XDc_WriteReg.
Referenced by XDcSub_ConfigureDcVideo.
const XDc_VideoAttribute* XDc_GetNonLiveVideoAttribute(XDc_VideoFormat Format)
This function looks up if the video format is valid NonLiveVideo format or not and returns a pointer to the attributes of the video.
Format takes in the video format for which attributes are being requested. A pointer to the structure XDc_VideoAttribute if the video format is valid, else returns NULL. None.
Referenced by XDpDc_ConfigureCursorBlend, XDpDc_GenerateFrames, XDpDc_InitDcSubPtr, XDpDc_SetupStream1Descriptors, XDpDc_SetupStream2Descriptors, XDpDc_InitDcSubsystem, XDcSub_SetInputNonLiveVideoFormat.
void XDc_SetNonLiveInputFormat(XDc *InstancePtr, u8 VideoSrc, const XDc_VideoAttribute *Video)
This function applies Attributes for Non - Live source(Stream1/Stream2).
InstancePtr is an pointer to the XDc Instance. None.
References XDc_ReadReg, XDC_AV_BUF_FORMAT, XDc_WriteReg.
Referenced by XDc_ConfigureStream.
const XDc_VideoAttribute* XDc_GetLiveVideoAttribute(XDc_VideoFormat Format)
This function looks up if the video format is valid LiveVideo format or not and returns a pointer to the attributes of the video.
Format takes in the video format for which attributes are being requested. A pointer to the structure XDc_VideoAttribute if the video format is valid, else returns NULL. None.
Referenced by main, XDcSub_SetInputLiveStreamFormat.
void XDc_SetOutputVideoFormat(XDc *InstancePtr)
This function configures the Output of the Video Pipeline.
InstancePtr is an pointer to the XDc Instance. None. None.
References XDc_WriteReg, XDC_V_BLEND_OUTPUT_VID_FORMAT.
Referenced by XDcSub_ConfigureDcVideo.
XDc_VideoAttribute* XDc_GetOutputVideoAttribute(XDc_VideoFormat Format, XDc_VidInterface Mode)
This function looks up if the output video format is valid or not and returns a pointer to the attributes of the video.
Format takes in the output video format for which attributes are being requested. A pointer to the structure XDc_VideoAttribute if the video format is valid, else returns NULL. None.
Referenced by XDpDc_InitDcSubPtr, XDcSub_SetOutputVideoFormat.
void XDc_EnablePartialBlend(XDc *InstancePtr)
This function enables Partial Blend for corresponding video stream.
InstancePtr is a pointer to the XDc Instance. None. None.
References XDC_V0, XDC_V1.
Referenced by XDcSub_ConfigureDcVideo.
u32 XDc_ConfigureStream(XDc *InstancePtr, u8 StreamSrc)
This function configures DC Blender.
InstancePtr is a pointer to the XDc instance. VideoSrc points to the stream source None.
References XDC_AV_BUF_LIVE_VID_COMP0_SF, XDC_V_BLEND_IN1CSC_COEFF0, XDC_V_BLEND_LAYER0_CONTROL, XDC_AV_BUF_LIVE_VID_CFG, XDC_AV_BUF_VID_COMP0_SCALE_FACTOR, XDc_SetNonLiveInputFormat, XDC_AV_BUF_LIVE_GFX_COMP0_SF, XDC_V_BLEND_IN2CSC_COEFF0, XDC_V_BLEND_LAYER1_CONTROL, XDC_AV_BUF_LIVE_GFX_CFG, XDC_AV_BUF_GRAPHICS_COMP0_SCALE_FACTOR.
Referenced by XDcSub_ConfigureDcVideo.
void XDc_SetOutputCSC(XDc *InstancePtr)
This function converts the Blender output to the desired output format.
InstancePtr is an pointer to the XDc Instance. None. None.
References XDC_V_BLEND_RGB2YCBCR_COEFF0, XDC_V_BLEND_LUMA_OUTCSC_OFFSET, XDc_WriteReg.
Referenced by XDcSub_ConfigureDcVideo.
void XDc_SetChromaKey(XDc *InstancePtr)
This function enables Chroma Keying.
InstancePtr is an pointer to the XDc Instance. None. None.
References XDc_WriteReg, XDC_V_BLEND_CHROMA_KEY_ENABLE, XDC_V_BLEND_CHROMA_KEY_COMP1, XDC_V_BLEND_CHROMA_KEY_COMP2, XDC_V_BLEND_CHROMA_KEY_COMP3.
Referenced by XDcSub_ConfigureDcVideo.
void XDc_SetCursorBlend(XDc *InstancePtr)
This function enables Cursor blending.
InstancePtr is an pointer to the XDc Instance. None. None.
References XDc_WriteReg, XDC_CURSOR_COORDINATE, XDC_CURSOR_SIZE.
Referenced by XDcSub_ConfigureDcVideo.
void XDc_SetAudioVideoClkSrc(XDc *InstancePtr)
This function sets the Audio and Video Clock Source and the video timing source.
InstancePtr is a pointer to the XDc instance. None. System uses PL Clock for Video when Live source is in use.
References XDc_WriteReg, XDC_AV_BUF_AUD_VID_CLK_SOURCE.
Referenced by XDcSub_ConfigureDcVideo.
void XDc_VideoSoftReset(XDc *InstancePtr)
This function applies a soft reset to the Video pipeline.
InstancePtr is a pointer to the XDc instance. None. None.
References XDc_WriteReg, XDC_AV_BUF_SRST_REG.
Referenced by XDpDc_InitDcSubsystem.
void XDc_VidClkSelect(XDc *InstancePtr)
This function configures DC Video Clock Select.
InstancePtr is a pointer to the XDc instance. None.
References XDc_WriteReg, XDC_VID_CLK.
Referenced by XDpDc_InitDcSubsystem.
void XDc_InputAudioSelect(XDc *InstancePtr)
void XDc_EnableStream1Buffers(XDc *InstancePtr)
This function enables the video channel interface between the DCDMA and the DC.
InstancePtr is a pointer to the XDc Instance. None. None.
References XDC_AV_CHBUF0, XDc_WriteReg.
Referenced by XDcSub_ConfigureDcVideo.
void XDc_EnableStream2Buffers(XDc *InstancePtr)
This function enables the video channel interface between the DCDMA and the DC.
InstancePtr is a pointer to the XDc Instance. None. None.
References XDC_AV_CHBUF3, XDc_WriteReg.
Referenced by XDcSub_ConfigureDcVideo.
void XDc_AudLineResetDisable(XDc *InstancePtr)
This function enables End of Line Reset for reduced blanking resolutions.
InstancePtr is a pointer to the XDc Instance. None. None.
References XDc_ReadReg, XDC_AUD_SOFT_RST, XDc_WriteReg.
void XDc_AudioSoftReset(XDc *InstancePtr)
This function applies a soft reset to the Audio pipeline.
InstancePtr is a pointer to the XDc instance. None. None.
References XDc_ReadReg, XDC_AUD_SOFT_RST, XDc_WriteReg.
Referenced by XDpDc_InitDcSubsystem, XDcSub_Initialize.
void XDc_AudExtraBSControl(XDc *InstancePtr)
This function enables Extra BS Control for AUDIO_SOFT_RESET.
InstancePtr is a pointer to the XDc Instance. None. None.
References XDc_ReadReg, XDC_AUD_SOFT_RST, XDc_WriteReg.
void XDc_SetSdpSource(XDc *InstancePtr)
This function enables SDP from DMA or PL.
InstancePtr is a pointer to the XDc Instance. None. None.
References XDc_ReadReg, XDC_SDP, XDc_WriteReg.
Referenced by XDcSub_ConfigureDcVideo.
void XDc_SetSdpEmptyThreshold(XDc *InstancePtr)
This function sets SDP Empty Threshold value.
InstancePtr is a pointer to the XDc Instance. None. None.
References XDc_WriteReg, XDC_SDP_EMPTY.
void XDc_SetSdpCursorBuffers(XDc *InstancePtr)
This function enables SDP & Cursor buffers.
InstancePtr is a pointer to the XDc Instance. None. None.
References XDc_WriteReg, XDC_AV_CHBUF_CURSOR_SDP.
Referenced by XDcSub_ConfigureDcVideo.
void XDc_SetVidFrameSwitch(XDc *InstancePtr)
This function configures the register to gate input video on/off at video frame boundary.
InstancePtr is a pointer to the XDc instance. None.
References XDc_WriteReg.
Referenced by XDpDc_InitDcSubsystem.
void XDc_SetNonLiveLatency(XDc *InstancePtr)
This function configures the memory fetch latency.
InstancePtr is a pointer to the XDc instance. None.
References XDc_WriteReg, XDC_AV_BUF_NON_LIVE_LATENCY.
Referenced by XDcSub_ConfigureDcVideo.
void XDc_SetStcCtrl(XDc *InstancePtr)
This function enables STC Control.
InstancePtr is a pointer to the XDc instance. None.
References XDc_WriteReg, XDC_AV_BUF_STC_CONTROL.
void XDc_SetStcLoad(XDc *InstancePtr)
This function loads STC Init value.
InstancePtr is a pointer to the XDc instance. None.
References XDc_WriteReg, XDC_AV_BUF_STC_INIT_VALUE0, XDC_AV_BUF_STC_INIT_VALUE1.
void XDc_SetStcAdjust(XDc *InstancePtr)
This function Adjusts STC Control value.
InstancePtr is a pointer to the XDc instance. None.
References XDc_WriteReg, XDC_AV_BUF_STC_ADJ.
u64 XDc_GetStcVsyncTs(XDc *InstancePtr)
u64 XDc_GetStcExtVsyncTs(XDc *InstancePtr)
u64 XDc_GetStcCustomEventTs(XDc *InstancePtr)
This function reads Custom Event STC value and returns it.
InstancePtr is a pointer to the XDc instance. None.
References XDc_ReadReg, XDC_AV_BUF_STC_CUSTOM_EVENT_TS_REG0, XDC_AV_BUF_STC_CUSTOM_EVENT_TS_REG1.
u64 XDc_GetStcCustomEvent2Ts(XDc *InstancePtr)
This function reads Custom Event2 STC value and returns it.
InstancePtr is a pointer to the XDc instance. None.
References XDc_ReadReg, XDC_AV_BUF_STC_CUSTOM_EVENT2_TS_REG0, XDC_AV_BUF_STC_CUSTOM_EVENT2_TS_REG1.
u64 XDc_GetStcSnapshot(XDc *InstancePtr)
This function reads STC Snapshot value and returns it.
InstancePtr is a pointer to the XDc instance. None.
References XDc_ReadReg, XDC_AV_BUF_STC_SNAPSHOT0, XDC_AV_BUF_STC_SNAPSHOT1.
void XDc_EnableAudioBuffer(XDc *InstancePtr)
This function Enable Audio Buffer channel and sets the burst length.
InstancePtr is a pointer to the XDc instance. None.
References XDc_WriteReg, XDC_AV_CHBUF_AUD.
Referenced by XDcSub_ConfigureDcVideo.
void XDc_AudioChannelSelect(XDc *InstancePtr)
This function enables audio channel select and programs sample rate.
InstancePtr is a pointer to the XDc instance. None.
References XDc_WriteReg, XDC_NL_AUD.
Referenced by XDcSub_ConfigureDcVideo.
void XDc_AudClkSelect(XDc *InstancePtr)
This function configures DC Audio Clock Select.
InstancePtr is a pointer to the XDc instance. None.
References XDc_WriteReg, XDC_AUD_CLK.
Referenced by XDpDc_InitDcSubsystem.
void XDc_SetAudInterfaceMode(XDc *InstancePtr)
void XDc_EnableAudio(XDc *InstancePtr)
This function enables audio to DC.
InstancePtr is a pointer to the XDc instance. None.
References XDc_WriteReg, XDC_DC_AUDIO.
Referenced by XDcSub_ConfigureDcVideo.
void XDc_DisableAudio(XDc *InstancePtr)
This function disables audio to DC.
InstancePtr is a pointer to the XDc instance. None.
References XDc_WriteReg, XDC_DC_AUDIO.
void XDc_SetVideoTiming(XDc *InstancePtr)
This function configures DC Timings register.
InstancePtr is a pointer to the XDc instance. None.
References XDc_WriteReg.
Referenced by XDpDc_InitDcSubsystem.
void XDc_SetAudioChCtrl(XDc *InstancePtr)
This function controls the Audio channel preamble and status bits.
InstancePtr is a pointer to the XDc instance. None.
References XDc_WriteReg, XDC_AUD_MIXER_VOLUME_CONTROL.
Referenced by XDcSub_SetAudioChCtrl.
void XDc_SetAudioSegmentedMode(XDc *InstancePtr)
This function sets Audio Segmented Mode.
InstancePtr is a pointer to the XDc instance. None.
References XDc_WriteReg, XDC_AUD_MIXER_META_DATA.
void XDc_SetCursorSdpRdyInterval(XDc *InstancePtr)
This function sets Cursor Sdp Ready Interval.
InstancePtr is a pointer to the XDc instance. None.
References XDc_WriteReg, XDC_RDY_INTERVAL.
Referenced by XDcSub_ConfigureDcVideo.
void XDc_SetSdpAckSel(XDc *InstancePtr)
This function sets Cursor Sdp Ready Interval.
InstancePtr is a pointer to the XDc instance. None.
References XDc_WriteReg, XDC_DP.
Referenced by XDcSub_ConfigureDcVideo.