xdcdma.h
XDCDMA_DESC_ALIGN
XDCDMA_DESC_PREAMBLE
XDCDMA_VIDEO_CHANNEL0
XDCDMA_VIDEO_CHANNEL1
XDCDMA_VIDEO_CHANNEL2
XDCDMA_GRAPHICS_CHANNEL3
XDCDMA_GRAPHICS_CHANNEL4
XDCDMA_GRAPHICS_CHANNEL5
XDCDMA_AUDIO_CHANNEL
XDCDMA_SDP_CHANNEL
XDCDMA_TRIGGER_DONE
XDCDMA_RETRIGGER_DONE
XDCDMA_TRIGGER_EN
XDCDMA_RETRIGGER_EN
XDcDma_ChannelId
XDcDma_IntHandlerType
XDcDma_State
XDcDma_VideoModes
XDcDma_ChannelType
typedef void(* XDcDma_VSyncIntHandler)(void *InstancePtr))(void *InstancePtr)
typedef void(* XDcDma_DscrDoneIntHandler)(void *InstancePtr))(void *InstancePtr)
typedef void(* XDcDma_DscrErrIntHandler)(void *InstancePtr))(void *InstancePtr)
typedef void(* XDcDma_AxiErrIntHandler)(void *InstancePtr))(void *InstancePtr)
typedef void(* XDcDma_NoOStandErrIntHandler)(void *InstancePtr))(void *InstancePtr)
typedef void(* XDcDma_AxiRd4kErrIntHandler)(void *InstancePtr))(void *InstancePtr)
typedef void(* XDcDma_AddrDecodeErrIntHandler)(void *InstancePtr))(void *InstancePtr)
typedef void(* XDcDma_DscrRdWrErrIntHandler)(void *InstancePtr))(void *InstancePtr)
typedef void(* XDcDma_CrcErrIntHandler)(void *InstancePtr))(void *InstancePtr)
typedef void(* XDcDma_PreambleErrIntHandler)(void *InstancePtr))(void *InstancePtr)
typedef void(* XDcDma_ChanOvrFlowErrIntHandler)(void *InstancePtr))(void *InstancePtr)
XDcDma_Config* XDcDma_LookupConfig(u32 DeviceId)
void XDcDma_CfgInitialize(XDcDma *InstancePtr, u32 EffectiveAddr)
This function initializes the configuration for the DcDma Instance.
InstancePtr is a pointer to the XDcDma instance. BaseAddr sets the base address of the DcDma instance None. Base address and DeviceId is same as the Dc Timing driver.
Referenced by XDpDc_InitDcSubsystem.
void XDcDma_WriteProtEnable(XDcDma *InstancePtr)
This function enables the write protection for DCDMA registers.
InstancePtr is a pointer to the XDcDma instance. None.
References XDcDma_ReadReg, XDCDMA_WPROTS, XDcDma_WriteReg.
void XDcDma_WriteProtDisable(XDcDma *InstancePtr)
This function disables the write protection for DCDMA registers.
InstancePtr is a pointer to the XDcDma instance. None.
References XDcDma_ReadReg, XDCDMA_WPROTS, XDcDma_WriteReg.
Referenced by XDpDc_InitDcSubsystem.
u32 XDCDma_GetWriteProt(XDcDma *InstancePtr)
This function programs the DPDMA_GLBL register with trigger channels.
InstancePtr is a pointer to the XDcDma instance. XST_SUCCESS or XST_FAILURE.
References XDcDma_ReadReg, XDCDMA_WPROTS.
u32 XDcDma_SetCallBack(XDcDma *InstancePtr, XDcDma_IntHandlerType HandlerType, void *CallbackFunc, void *CallbackRef)
This function sets the callback for different interrupt handlers.
InstancePtr is a pointer to the XDcDma instance. XST_SUCCESS or XST_FAILURE.
u32 XDcDma_ConfigChannelState(XDcDma *InstancePtr, XDcDma_ChannelId Id, XDcDma_State Enable)
This function programs the channel state as enable, disable or idle.
InstancePtr is a pointer to the XDcDma instance. ChannelId is channel to configure Enable sets the channel state. XST_SUCCESS or XST_FAILURE.
References XDcDma_ConfigChannelState, XDcDma_WaitPendingTransaction, XDcDma_ReadModifyWrite, XDCDMA_CH0_CNTL.
Referenced by XDcDma_ConfigChannelState, XDcDma_VSyncHandler.
void XDcDma_SetupChannel(XDcDma *InstancePtr, XDcDma_ChannelType Channel)
This function sets the descriptor address for each video stream.
InstancePtr is a pointer to the XDcDma instance. Channel type None.
Referenced by XDcDma_VSyncHandler.
u32 XDcDma_Trigger(XDcDma *InstancePtr, XDcDma_ChannelType Channel)
This function programs the DPDMA_GLBL register with trigger channels.
InstancePtr is a pointer to the XDcDma instance. XST_SUCCESS or XST_FAILURE.
Referenced by XDcDma_VSyncHandler.
u32 XDcDma_ReTrigger(XDcDma *InstancePtr, XDcDma_ChannelType Channel)
This function programs the DPDMA_GLBL register with retrigger channels.
InstancePtr is a pointer to the XDcDma instance. XST_SUCCESS or XST_FAILURE.
References XDcDma_WriteReg, XDCDMA_GBL.
Referenced by XDcDma_VSyncHandler.
void XDcDma_SetDataQoS(XDcDma *InstancePtr, XDcDma_ChannelType Channel, u8 Val)
This function programs the data QoS for a channel.
InstancePtr is a pointer to the XDcDma instance. ChannelType is channel number. Val to configure. None.
References XDcDma_ReadModifyWrite, XDCDMA_CH0_CNTL.
void XDcDma_SetDescQoS(XDcDma *InstancePtr, XDcDma_ChannelType Channel, u8 Val)
This function programs the DPDMA_GLBL register with trigger channels.
InstancePtr is a pointer to the XDcDma instance. ChannelType is channel number. Val to configure. None.
References XDcDma_ReadModifyWrite, XDCDMA_CH0_CNTL.
void XDcDma_SetAxCache(XDcDma *InstancePtr, XDcDma_ChannelId Id, u8 Val)
This function programs the Ax Cache register for specific channel.
InstancePtr is a pointer to the XDcDma instance. ChannelId is channel number. Val to configure. None.
References XDcDma_ReadModifyWrite, XDCDMA_CH0_CNTL.
void XDcDma_SetAxProt(XDcDma *InstancePtr, XDcDma_ChannelId Id, u8 Val)
This function programs the AxProt register for specific channel.
InstancePtr is a pointer to the XDcDma instance. ChannelId is channel number. Val to configure. None.
References XDcDma_ReadModifyWrite, XDCDMA_CH0_CNTL.
void XDcDma_SetDescDelay(XDcDma *InstancePtr, XDcDma_ChannelId Id, u16 Val)
This function programs the Desc Delay for required channel.
InstancePtr is a pointer to the XDcDma instance. Channel ID Val specifies desc delay None.
References XDcDma_ReadModifyWrite, XDCDMA_CH0_CNTL.
u32 XDCDma_GetOutstandingTxn(XDcDma *InstancePtr, XDcDma_ChannelId Id)
This function programs the DPDMA_GLBL register with trigger channels.
InstancePtr is a pointer to the XDcDma instance. Channel Id is channel number. XST_SUCCESS or XST_FAILURE.
References XDcDma_ReadReg, XDCDMA_CH0_STATUS.
Referenced by XDcDma_WaitPendingTransaction.
u32 XDcDma_WaitPendingTransaction(XDcDma *InstancePtr, XDcDma_ChannelId Id)
This function checks for any pending transactions for a given channel.
InstancePtr is a pointer to the XDcDma instance. Channel Id is channel number XST_SUCCESS or XST_FAILURE.
References XDCDma_GetOutstandingTxn.
Referenced by XDcDma_ConfigChannelState.
u32 XDcDma_GenerateChecksum(XDcDma_Descriptor *DescPtr)
void XDcDma_InterruptEnable(XDcDma *InstancePtr, u32 Mask)
This function enables the interrupt.
InstancePtr is a pointer to the XDcDma instance. Mask is interrupt to unmask. None.
References XDcDma_WriteReg, XDCDMA_MISC_IER, XDCDMA_MISC_ISR.
Referenced by XDpDc_SetupInterrupts.
void XDcDma_InterruptDisable(XDcDma *InstancePtr, u32 Mask)
This function disables the interrupt.
InstancePtr is a pointer to the XDcDma instance. None.
References XDcDma_WriteReg, XDCDMA_MISC_IDR.
void XDcDma_InterruptHandler(XDcDma *InstancePtr)
This function calls the VsyncInterrupt Handler.
InstancePtr is a pointer to the XDcDma instance. None.
References XDcDma_ReadReg, XDCDMA_MISC_ISR, XDcDma_VSyncHandler.
void XDcDma_VSyncHandler(XDcDma *InstancePtr)
This function services the VsyncInterrupt.
InstancePtr is a pointer to the XDcDma instance. None.
References XDcDma_SetupChannel, XDcDma_ConfigChannelState, XDcDma_Trigger, XDcDma_ReTrigger, XDcDma_WriteReg, XDCDMA_GBL, XDCDMA_MISC_ISR.
Referenced by XDcDma_InterruptHandler.
void XDcDma_DescInit(XDcDma_Descriptor *XDesc)
This function creates the descriptor for the DcDma Instance.
InstancePtr is a pointer to the XDcDma instance. None.
Referenced by XDpDc_CreateDescriptors.
u32 XDcDma_GetNewDescId(XDcDma *InstancePtr)
This function increments the LastDescId of DcDma Instance.
InstancePtr is a pointer to the XDcDma instance. Updated LastDescId.
References XDcDma::LastDescId.
Referenced by XDpDc_CreateDescriptors.
void XDcDma_SetAudioChCtrl(XDcDma *InstancePtr)
This function sets DcDma Audio Channel Control.
InstancePtr is a pointer to the XDcDma instance. None
References XDcDma_WriteReg, XDCDMA_AUD_CTRL.