xdcsub.h
XDCSUB_AUDIO_CHANNELS_MIN
XDCSUB_AUDIO_CHANNELS_MAX
XDCSUB_OPMODE_FUNCTIONAL
The DC Subsystem can work in functional or in bypass mode.
In functional mode, the 2 video streams are blended together and sent to the DisplayPort. In bypass mode, the input video stream is directly forwarded to the DisplayPort.Functional mode supports blending videos
Referenced by main, XDpDc_DisplayConfig, XDpDc_InitConfigDefaults, XDpDc_InitDcSubsystem, XDpDc_MainHelpMenu, XDpDc_MenuLoop.
XDCSUB_OPMODE_BYPASS
Bypass mode makes DC in pass through mode.
Referenced by XDpDc_InitConfigDefaults.
XDCSUB_PPTMODE_NONLIVE
The DC Subsystem supports three presentation modes: Non-live, Live, and Mixed.
In non-live mode, the video streams are fetched from the memory. In live mode, the video streams are sourced from the live video ports. In mixed mode, one video stream is sourced from memory and the other video stream is sourced from one of the live video ports.In Non live mode, video streams are fetched from memory.
Referenced by main, XDpDc_DisplayConfig, XDpDc_InitConfigDefaults, XDpDc_InitDcSubsystem, XDpDc_MainHelpMenu, XDpDc_MenuLoop.
XDCSUB_PPTMODE_LIVE
In Live mode, video streams come from live video ports.
Referenced by main, XDpDc_DisplayConfig, XDpDc_InitConfigDefaults, XDpDc_InitDcSubsystem, XDpDc_MainHelpMenu, XDpDc_MenuLoop.
XDCSUB_PPTMODE_MIXED
In Mixed mode, one video come from live source and another from memory.
Referenced by main, XDpDc_DisplayConfig, XDpDc_GenerateFrames, XDpDc_InitConfigDefaults, XDpDc_InitDcSubsystem, XDpDc_MainHelpMenu, XDpDc_MenuLoop.
XDCSUB_LIVVID_SEL_V01
In mixed mode, one video stream is sourced from memory and the other video stream is sourced from one of the live video ports.
These macros are to denote which of the live video ports are selected as the video source. In live mode, both the video ports are active.In mixed mode, live video port V01 is selected as video source.
Referenced by XDpDc_InitConfigDefaults.
XDCSUB_LIVVID_SEL_V02
In mixed mode, live video port V02 is selected as video source.
Referenced by XDpDc_InitConfigDefaults.
XDCSUB_LIVVID_SEL_BOTH
In live mode, both live video ports are active.
Referenced by XDpDc_InitConfigDefaults.
XDCSUB_LIVVID_SEL_NONE
In non-live mode, both live video ports are disabled.
Referenced by XDpDc_InitConfigDefaults.
XDCSUB_VIDMODE_AV
The first video port V01 supports both audio and video.
The second video port V02 supports video only. These macros are to denote the mode of operation of the live video ports.Live video port V01 supports both audio and video.
Referenced by XDpDc_InitConfigDefaults.
XDCSUB_VIDMODE_VONLY
Live video port V02 supports video only.
Referenced by XDpDc_InitConfigDefaults.
XDCSUB_VIDMODE_NONE
No video port.
Referenced by XDpDc_InitConfigDefaults.
XDCSUB_LIVVID_ALPHA_EN
These defines are used to denote if alpha channel is enabled or disabled for live video input.
Alpha channel is enabled for live video input.
XDCSUB_LIVVID_ALPHA_DIS
Alpha channel is disabled for live video input.
XDCSUB_LIVVID_SDP_EN
This defines if SDP is enabled or disabled for live video input.
SDP is enabled for live video input.
XDCSUB_LIVVID_SDP_DIS
SDP is disabled for live video input.
XDcSub_Config XDcSub_ConfigTable[][]
The configuration table for devices.
XDcSub_Config* XDcSub_LookupConfig(UINTPTR BaseAddress)
u32 XDcSub_CfgInitialize(XDcSub *InstancePtr)
This function initializes the configuration of all instances part of DC subsystem i.e DC, DCDMA, Interrupts.
InstancePtr is a pointer to the XDcSub instance. DeviceId is the id of the device from the design. XST_SUCCESS or XST_FAILURE. Base address and DeviceId is same as the DP Core driver.
References XDc_CfgInitialize.
u32 XDcSub_Initialize(XDcSub *InstancePtr)
This function initializes all the data structures of the XDcSub Instance.
InstancePtr is a pointer to the XDcSub instance. XST_SUCCESS or XST_FAILURE. None.
References XDc_AudioSoftReset, XDc_SetVidInterfaceMode, XDc_WriteProtDisable.
Referenced by XDpDc_InitDcSubsystem.
u32 XDcSub_SetVidInterfaceMode(XDcSub *InstancePtr, XDc_VidInterface Mode)
This function sets the Interface mode for DCSub DC Instance.
DC can be either in bypass mode or functional mode. InstancePtr is a pointer to the XDc instance. Mode is the enum val to enable or disable bypass mode. XST_SUCCESS or XST_FAILURE.
Referenced by XDpDc_InitDcSubPtr.
u32 XDcSub_SetBlenderBgColor(XDcSub *InstancePtr, XDc_BlenderBgClr *Color)
This function sets the blender background color.
InstancePtr is an pointer to the XDcSub Instance. Color is a pointer to the structure XDc_BlenderBgClr XST_SUCCESS or XST_FAILURE. None.
u32 XDcSub_SetGlobalAlpha(XDcSub *InstancePtr, XDc_AlphaBlend AlphaEnable, u8 Alpha)
This function enables or disables global alpha.
InstancePtr is an pointer to the XDc Instance. XST_SUCCESS or XST_FAILURE. GlobalAlphaEn = 1, enables the global alpha. GlobalAlphaEn = 0, disables the global alpha. Alpha = 0, transparent Alpha = 255, Opaque Alpha = 8:1 (Alpha value)
Referenced by XDpDc_InitDcSubPtr.
u32 XDcSub_SetVidStreamSrc(XDcSub *InstancePtr, XDc_VideoStream1 VidStream1, XDc_VideoStream2 VidStream2)
This function selects the source type for the Video and Graphics input streams that are passed on to the blender block.
InstancePtr is a pointer to the XDc instance. VidStream1 selects the stream coming from the video source1 VidStream2 selects the stream coming from the video source2 XST_SUCCESS or XST_FAILURE. None.
Referenced by XDpDc_InitDcSubPtr.
u32 XDcSub_SetInputNonLiveVideoFormat(XDcSub *InstancePtr, XDc_VideoFormat Format1, XDc_VideoFormat Format2)
This function selects the source type for audio stream.
InstancePtr is a pointer to the XDcSub instance. Format1 selects the nonlive video1 format Format2 selects the nonlive video2 format XST_SUCCESS or XST_FAILURE. None.
References XDc_GetNonLiveVideoAttribute.
Referenced by XDpDc_InitDcSubPtr.
u32 XDcSub_SetInputLiveStreamFormat(XDcSub *InstancePtr, XDc_VideoFormat Format1, XDc_VideoFormat Format2)
This function sets the stream1 format for the live video.
InstancePtr is a pointer to the XDcSub instance. Format1 is the enum for the live video1 format Format2 is the enum for the live video2 format XST_SUCCESS if the correct format has been set. XST_FAILURE if the format is invalid. None.
References XDc_GetLiveVideoAttribute.
u32 XDcSub_SetOutputVideoFormat(XDcSub *InstancePtr, XDc_VideoFormat Format)
This function sets the Output Video Format.
InstancePtr is a pointer to the XDc instance. Format is the enum for the non-live video format XST_SUCCESS if the correct format has been set. XST_FAILURE if the format is invalid. None.
References XDc_GetOutputVideoAttribute.
Referenced by XDpDc_InitDcSubPtr.
u32 XDcSub_SetStreamPixelScaling(XDcSub *InstancePtr, u32 *Stream1_ScaleFactors, u32 *Stream2_ScaleFactors)
This function sets the scaling factors depending on the source video stream.
InstancePtr is a pointer to the XDc instance. Scaling Factors is a pointer to the scaling factors needed for scaling colors to 12 BPC. Scaling Factors is a pointer to the scaling factors needed for scaling colors to 12 BPC. XST_SUCCESS or XST_FAILURE. None.
Referenced by XDpDc_InitDcSubPtr.
u32 XDcSub_SetInputStreamCSC(XDcSub *InstancePtr, u32 *Stream1CSCCoeff, u32 *Stream1CSCOffset, u32 *Stream2CSCCoeff, u32 *Stream2CS)
This function sets the Stream Color space conversion matrix.
InstancePtr is a pointer to the XDc instance. Stream1CSCCoeff is a pointer to the CSCCoeff values Stream1CSCOffset is a pointer to the CSCCOffset values Stream2CSCCoeff is a pointer to the CSCCoeff values Stream2CSCOffset is a pointer to the CSCCOffset values XST_SUCCESS or XST_FAILURE. None.
Referenced by XDpDc_InitDcSubPtr.
u32 XDcSub_SetOutputStreamCSC(XDcSub *InstancePtr, u32 *OutCSCCoeff, u32 *OutCSCOffset)
This function sets the Output Stream Color space conversion matrix.
InstancePtr is a pointer to the XDc instance. OutCSCCoeff is a pointer to the CSCCoeff values OutCSCOffset is a pointer to the CSCOffset values XST_SUCCESS or XST_FAILURE. None.
Referenced by XDpDc_InitDcSubPtr.
u32 XDcSub_SetInputStreamLayerControl(XDcSub *InstancePtr, u8 BlendBypass1, u8 BlendBypass2)
This function sets the Stream1 Blend enable, disable option.
InstancePtr is a pointer to the XDc instance. BlendBypass1 is enables, disables blending for stream BlendBypass2 is enables, disables blending for stream XST_SUCCESS or XST_FAILURE. None.
Referenced by XDpDc_InitDcSubPtr.
u32 XDcSub_SetChromaKey(XDcSub *InstancePtr, u8 ChromaEnable, u8 ChromaMasterSel, XDc_ChromaKey *Key)
This function enables Chroma Keying.
InstancePtr is an pointer to the XDc Instance. XST_SUCCESS or XST_FAILURE. None.
u32 XDcSub_SetCursorBlend(XDcSub *InstancePtr, XDc_CursorBlend Enable, XDc_Cursor *Cursor)
This function enables Cursor Blending.
InstancePtr is a pointer to the XDc Instance. Cursor Coordinates. Cursor Video Attributes. XST_SUCCESS or XST_FAILURE. None.
Referenced by XDpDc_ConfigureCursorBlend.
u32 XDcSub_SetAudioVideoClkSrc(XDcSub *InstancePtr)
This function sets the Audio and Video Clock Source and the video timing source.
InstancePtr is a pointer to the XDc instance. XST_SUCCESS or XST_FAILURE. System uses PL Clock for Video when Live source is in use.
Referenced by XDpDc_InitDcSubPtr.
u32 XDcSub_VidClkSelect(XDcSub *InstancePtr, u8 Stream1Sel, u8 Stream2Sel)
This function configures DC Video Clock Select.
InstancePtr is a pointer to the XDc instance. Select configures Video Clock mode XST_SUCCESS or XST_FAILURE.
Referenced by XDpDc_InitDcSubPtr.
u32 XDcSub_EnableStream1Buffers(XDcSub *InstancePtr, u8 Enable, u8 Burst)
This function enables the video channel interface between the DCDMA and the DC.
InstancePtr is a pointer to the XDc Instance. Enable sets the corresponding buffers. Burst programs burstlength. XST_SUCCESS or XST_FAILURE. None.
Referenced by XDpDc_InitDcSubPtr.
u32 XDcSub_EnableStream2Buffers(XDcSub *InstancePtr, u8 Enable, u8 Burst)
This function enables the video channel interface between the DCDMA and the DC.
InstancePtr is a pointer to the XDc Instance. Enable sets the corresponding buffers. Burst programs burstlength. XST_SUCCESS or XST_FAILURE. None.
Referenced by XDpDc_InitDcSubPtr.
u32 XDcSub_AudLineResetDisable(XDcSub *InstancePtr, u8 Disable)
This function enables End of Line Reset for reduced blanking resolutions.
InstancePtr is a pointer to the XDc Instance. Disable is to be set while using Reduced Blanking Resolutions. XST_SUCCESS or XST_FAILURE. None.
u32 XDcSub_AudExtraBSControl(XDcSub *InstancePtr, u8 Bypass)
This function enables Extra BS Control for AUDIO_SOFT_RESET.
InstancePtr is a pointer to the XDc Instance. Bypass is to be override the extra BS on link. XST_SUCCESS or XST_FAILURE. None.
u32 XDcSub_SetSdp(XDcSub *InstancePtr, XDc_Sdp Sdp)
This function enables SDP from DMA or PL.
InstancePtr is a pointer to the XDc Instance. Enable sets the corresponding buffers. XST_SUCCESS or XST_FAILURE. None.
Referenced by XDpDc_ConfigureSdp.
u32 XDcSub_SetSdpEmptyThreshold(XDcSub *InstancePtr, u8 Threshold)
This function sets SDP Empty Threshold value.
InstancePtr is a pointer to the XDc Instance. Empty Threshold value. XST_SUCCESS or XST_FAILURE. None.
u32 XDcSub_SetSdpCursorBuffers(XDcSub *InstancePtr, u8 Enable, u8 BurstLen)
This function enables SDP & Cursor buffers.
InstancePtr is a pointer to the XDc Instance. Enable. XST_SUCCESS or XST_FAILURE. None.
Referenced by XDpDc_ConfigureCursorBlend, XDpDc_ConfigureSdp.
u32 XDcSub_SetStreamPartialBlend(XDcSub *InstancePtr, XDc_PartialBlendEn Enable1, XDc_PartialBlend *Coords1, XDc_PartialBlendEn Enable2, XDc_PartialBlend *Coords2)
This function enables Partial Blend for both video streams.
InstancePtr is a pointer to the XDc Instance. Stream1_Enable. Stream2_Enable. Stream1 Partial Blend Coordinates. Stream2 Partial Blend Coordinates. XST_SUCCESS or XST_FAILURE. None.
Referenced by XDpDc_ConfigurePartialPlaneBlend.
u32 XDcSub_SetVidFrameSwitch(XDcSub *InstancePtr, u32 Control)
This function configures the register to gate input video on/off at video frame boundary.
InstancePtr is a pointer to the XDc instance. Val bits set different control signals XST_SUCCESS or XST_FAILURE.
Referenced by XDpDc_InitDcSubPtr.
u32 XDcSub_SetNonLiveLatency(XDcSub *InstancePtr, u16 Nl_Latency, u8 V_Line_Latency)
This function configures the memory fetch latency.
InstancePtr is a pointer to the XDc instance. Val bits sets the offset for early timing XST_SUCCESS or XST_FAILURE.
Referenced by XDpDc_InitDcSubPtr.
u32 XDcSub_EnableStcCtrl(XDcSub *InstancePtr)
This function enables STC Control.
InstancePtr is a pointer to the XDc instance. XST_SUCCESS or XST_FAILURE.
u32 XDcSub_ClearStcCtrl(XDcSub *InstancePtr)
This function clears STC Control.
InstancePtr is a pointer to the XDc instance. XST_SUCCESS or XST_FAILURE.
u32 XDcSub_SetStcLoad(XDcSub *InstancePtr, u64 InitVal)
This function loads STC Init value.
InstancePtr is a pointer to the XDc instance. XST_SUCCESS or XST_FAILURE.
u32 XDcSub_SetStcAdjust(XDcSub *InstancePtr, u32 InitVal)
This function Adjust STC value.
InstancePtr is a pointer to the XDc instance. XST_SUCCESS or XST_FAILURE.
u64 XDcSub_GetStcVSyncTs(XDcSub *InstancePtr)
This function reads VSync STC value and returns it.
InstancePtr is a pointer to the XDc instance. XST_SUCCESS or XST_FAILURE.
u64 XDcSub_GetStcExtVSyncTs(XDcSub *InstancePtr)
This function reads External VSync STC value and returns it.
InstancePtr is a pointer to the XDc instance. XST_SUCCESS or XST_FAILURE.
u64 XDcSub_GetStcCustomEventTs(XDcSub *InstancePtr)
This function reads Custom VSync Event STC value and returns it.
InstancePtr is a pointer to the XDc instance. XST_SUCCESS or XST_FAILURE.
u64 XDcSub_GetStcCustomEvent2Ts(XDcSub *InstancePtr)
This function reads Custom VSync Event STC value and returns it.
InstancePtr is a pointer to the XDc instance. XST_SUCCESS or XST_FAILURE.
u64 XDcSub_GetStcSnapshot(XDcSub *InstancePtr)
This function returns StcSnapshot value.
InstancePtr is a pointer to the XDc instance. XST_SUCCESS or XST_FAILURE.
u32 XDcSub_EnableAudioBuffer(XDcSub *InstancePtr, u8 Enable, u8 BurstLen)
This function Enable Audio Buffer channel and sets the burst length.
InstancePtr is a pointer to the XDc instance. XST_SUCCESS or XST_FAILURE.
Referenced by XDpDc_InitDcSubPtr.
u32 XDcSub_AudioChannelSelect(XDcSub *InstancePtr, u8 ChannelSel, u16 SampleRate)
This function enables audio channel select and programs sample rate.
InstancePtr is a pointer to the XDc instance. ChannelSel selects the different audio channels. SampleRate selects the different sample rates. XST_SUCCESS or XST_FAILURE.
Referenced by XDpDc_InitDcSubPtr.
u32 XDcSub_AudClkSelect(XDcSub *InstancePtr, u32 Select)
This function configures DC Audio Clock Select.
InstancePtr is a pointer to the XDc instance. Select configures Audio Clock mode XST_SUCCESS or XST_FAILURE.
Referenced by XDpDc_InitDcSubPtr.
u32 XDcSub_SetAudInterfaceMode(XDcSub *InstancePtr, XDc_AudInterface Mode)
This function sets the Interface mode for DCSub DC Instance.
DC can be either in bypass mode or functional mode. InstancePtr is a pointer to the XDc instance. Mode is the enum val to enable or disable bypass mode. XST_SUCCESS or XST_FAILURE.
Referenced by XDpDc_InitDcSubPtr.
u32 XDcSub_EnableAudio(XDcSub *InstancePtr)
This function enables DC Aud mode.
InstancePtr is a pointer to the XDc instance. XST_SUCCESS or XST_FAILURE.
Referenced by XDpDc_InitDcSubPtr.
u32 XDcSub_DisableAudio(XDcSub *InstancePtr)
This function disable DC Aud mode.
InstancePtr is a pointer to the XDc instance. XST_SUCCESS or XST_FAILURE.
u32 XDcSub_SetInputAudioSelect(XDcSub *InstancePtr, XDc_AudioStream AudStream)
This function selects the source type for audio stream.
InstancePtr is a pointer to the XDcSub instance. AudStream selects the audio stream source type XST_SUCCESS or XST_FAILURE. None.
Referenced by XDpDc_InitDcSubPtr.
u32 XDcSub_ConfigureDcVideo(XDc *InstancePtr)
This function configures Dc Video registers in the required sequence.
InstancePtr is a pointer to the XDc instance. XST_SUCCESS or XST_FAILURE.
References XDc_AudioChannelSelect, XDc_ConfigureStream, XDc_EnableAudio, XDc_EnableAudioBuffer, XDc_EnablePartialBlend, XDc_EnableStream1Buffers, XDc_EnableStream2Buffers, XDc_SetAudioVideoClkSrc, XDc_SetChromaKey, XDc_SetCursorBlend, XDc_SetCursorSdpRdyInterval, XDc_SetGlobalAlpha, XDc_SetInputAudioSelect, XDc_SetInputVideoSelect, XDc_SetNonLiveLatency, XDc_SetOutputCSC, XDc_SetOutputVideoFormat, XDc_SetSdpAckSel, XDc_SetSdpCursorBuffers, XDc_SetSdpSource.
Referenced by XDpDc_InitDcSubsystem.
u32 XDcSub_SetAudioChCtrl(XDcSub *InstancePtr, u8 AudioChannels)
This function sets audio channel-control bits from active channel count.
InstancePtr is a pointer to the XDc instance. AudioChannels is active channel count (1 to 8). XST_SUCCESS or XST_FAILURE.
References XDc_SetAudioChCtrl.
Referenced by XDpDc_InitDcSubPtr.
u32 XDcSub_SetAudioSegmentedMode(XDcSub *InstancePtr, u8 AudSegmentedMode)
This function sets Audio Segmented Mode.
InstancePtr is a pointer to the XDc instance. XST_SUCCESS or XST_FAILURE.
void XDcSub_EnableSdp(XDcSub *InstancePtr)
This function enable DC SDP.
InstancePtr is a pointer to the XDc instance. None.
Referenced by XDpDc_ConfigureSdp.
void XDcSub_SetSdpAckSel(XDcSub *InstancePtr, u8 AckSel)
This function sets SDP ACK from either DP or PL.
InstancePtr is a pointer to the XDc instance. None.
Referenced by XDpDc_ConfigureSdp.
u32 XDcSub_SetCursorSdpRdyInterval(XDcSub *InstancePtr, u16 RdyInterval)
This function sets Cursor Sdp Ready Interval.
InstancePtr is a pointer to the XDc instance. None.
Referenced by XDpDc_ConfigureSdp.