axicdma
typedef void(* XAxiCdma_CallBackFn)(void *CallBackRef, u32 IrqMask, int *NumBdPtr))(void *CallBackRef, u32 IrqMask, int *NumBdPtr)
XAXICDMA_BD_MINIMUM_ALIGNMENT
Minimum byte alignment requirement for descriptors to satisfy both hardware/software needs.
Referenced by XAxiCdma_BdRingCreate, XAxiCdma_BdRingNext, XAxiCdma_BdRingPrev.
XAXICDMA_MAX_TRANSFER_LEN
Max length hw supports.
Referenced by XAxiCdma_CfgInitialize, XAxiCdma_SimpleTransfer.
XAXICDMA_4_1_MAX_TRANSFER_LEN
Max length hw supports.
Referenced by XAxiCdma_CfgInitialize.
XAXICDMA_CR_OFFSET
Control register.
Referenced by XAxiCdma_DumpRegisters, XAxiCdma_GetCoalesce, XAxiCdma_IntrDisable, XAxiCdma_IntrEnable, XAxiCdma_IntrGetEnabled, XAxiCdma_Reset, XAxiCdma_ResetIsDone, XAxiCdma_SelectKeyHole, XAxiCdma_SetCoalesce.
XAXICDMA_SR_OFFSET
Status register.
Referenced by XAxiCdma_CfgInitialize, XAxiCdma_DumpRegisters, XAxiCdma_GetError, XAxiCdma_IntrHandler, XAxiCdma_IsBusy.
XAXICDMA_CDESC_OFFSET
Current descriptor pointer.
Referenced by XAxiCdma_BdRingGetCurrBd, XAxiCdma_BdSetCurBdPtr, XAxiCdma_DumpRegisters.
XAXICDMA_CDESC_MSB_OFFSET
Current descriptor pointer.
Referenced by XAxiCdma_BdRingGetCurrBd, XAxiCdma_BdSetCurBdPtr, XAxiCdma_DumpRegisters.
XAXICDMA_TDESC_OFFSET
Tail descriptor pointer.
Referenced by XAxiCdma_BdSetTailBdPtr, XAxiCdma_DumpRegisters.
XAXICDMA_TDESC_MSB_OFFSET
Tail descriptor pointer.
Referenced by XAxiCdma_BdSetTailBdPtr, XAxiCdma_DumpRegisters.
XAXICDMA_SRCADDR_OFFSET
Source address register.
Referenced by XAxiCdma_DumpRegisters, XAxiCdma_SimpleTransfer.
XAXICDMA_SRCADDR_MSB_OFFSET
Source address register.
Referenced by XAxiCdma_DumpRegisters, XAxiCdma_SimpleTransfer.
XAXICDMA_DSTADDR_OFFSET
Destination address register.
Referenced by XAxiCdma_DumpRegisters, XAxiCdma_SimpleTransfer.
XAXICDMA_DSTADDR_MSB_OFFSET
Destination address register.
Referenced by XAxiCdma_DumpRegisters, XAxiCdma_SimpleTransfer.
XAXICDMA_CR_RESET_MASK
Reset DMA engine.
Referenced by XAxiCdma_Reset, XAxiCdma_ResetIsDone.
XAXICDMA_CR_RESET_MASK
Reset DMA engine.
XAXICDMA_CR_SGMODE_MASK
Scatter gather mode.
Referenced by XAxiCdma_SelectKeyHole.
XAXICDMA_CR_SGMODE_MASK
Scatter gather mode.
XAXICDMA_CR_KHOLE_RD_MASK
Keyhole Read.
Referenced by XAxiCdma_SelectKeyHole.
XAXICDMA_CR_KHOLE_RD_MASK
Keyhole Read.
XAXICDMA_CR_KHOLE_WR_MASK
Keyhole Write.
Referenced by XAxiCdma_SelectKeyHole.
XAXICDMA_CR_KHOLE_WR_MASK
Keyhole Write.
XAXICDMA_BTT_OFFSET
Bytes to transfer.
Referenced by XAxiCdma_DumpRegisters, XAxiCdma_SimpleTransfer.
XAXICDMA_BTT_OFFSET
Bytes to transfer.
XAXICDMA_SR_IDLE_MASK
DMA channel idle.
Referenced by XAxiCdma_IsBusy.
XAXICDMA_SR_IDLE_MASK
DMA channel idle.
XAXICDMA_SR_SGINCLD_MASK
Hybrid build.
Referenced by XAxiCdma_CfgInitialize.
XAXICDMA_SR_SGINCLD_MASK
Hybrid build.
XAXICDMA_SR_ERR_INTERNAL_MASK
Datamover internal err.
XAXICDMA_SR_ERR_INTERNAL_MASK
Datamover internal err.
XAXICDMA_SR_ERR_SLAVE_MASK
Datamover slave err.
XAXICDMA_SR_ERR_DECODE_MASK
Datamover decode err.
XAXICDMA_SR_ERR_SG_INT_MASK
SG internal err.
XAXICDMA_SR_ERR_SG_SLV_MASK
SG slave err.
XAXICDMA_SR_ERR_SG_DEC_MASK
SG decode err.
XAXICDMA_SR_ERR_ALL_MASK
All errors.
Referenced by XAxiCdma_GetError, XAxiCdma_IntrHandler.
XAXICDMA_DESC_LSB_MASK
LSB Address mask.
Referenced by XAxiCdma_BdSetCurBdPtr, XAxiCdma_BdSetNextPtr, XAxiCdma_BdSetTailBdPtr.
XAXICDMA_XR_IRQ_IOC_MASK
Completion interrupt.
XAXICDMA_XR_IRQ_DELAY_MASK
Delay interrupt.
XAXICDMA_XR_IRQ_ERROR_MASK
Error interrupt.
Referenced by XAxiCdma_IntrHandler.
XAXICDMA_XR_IRQ_ALL_MASK
All interrupts.
Referenced by XAxiCdma_HybridIntrExample, XAxiCdma_HybridPollExample, XAxiCdma_IntrDisable, XAxiCdma_IntrEnable, XAxiCdma_IntrGetEnabled, XAxiCdma_IntrHandler, XAxiCdma_SgIntrExample, XAxiCdma_SimpleIntrExample, XAxiCdma_SimplePollExample.
XAXICDMA_XR_IRQ_SIMPLE_ALL_MASK
All interrupts for simple only mode.
Referenced by XAxiCdma_SimpleTransfer.
XAXICDMA_XR_DELAY_MASK
Delay timeout counter.
Referenced by XAxiCdma_GetCoalesce, XAxiCdma_SetCoalesce.
XAXICDMA_XR_COALESCE_MASK
Coalesce counter.
Referenced by XAxiCdma_GetCoalesce, XAxiCdma_SetCoalesce.
XAXICDMA_DELAY_SHIFT
XAXICDMA_COALESCE_SHIFT
XAXICDMA_DELAY_MAX
Maximum delay counter value.
Referenced by XAxiCdma_SetCoalesce.
XAXICDMA_COALESCE_MAX
Maximum coalescing counter value.
Referenced by XAxiCdma_SetCoalesce.
XAXICDMA_BD_NDESC_OFFSET
Next descriptor pointer.
Referenced by XAxiCdma_BdGetNextPtr, XAxiCdma_BdSetNextPtr.
XAXICDMA_BD_NDESC_MSB_OFFSET
Next descriptor pointer.
Referenced by XAxiCdma_BdGetNextPtr, XAxiCdma_BdSetNextPtr.
XAXICDMA_BD_BUFSRC_OFFSET
Buffer source address.
Referenced by XAxiCdma_BdGetSrcBufAddr, XAxiCdma_BdSetSrcBufAddr.
XAXICDMA_BD_BUFSRC_MSB_OFFSET
Buffer source address.
Referenced by XAxiCdma_BdGetSrcBufAddr, XAxiCdma_BdSetSrcBufAddr.
XAXICDMA_BD_BUFDST_OFFSET
Buffer destination address.
Referenced by XAxiCdma_BdGetDstBufAddr, XAxiCdma_BdSetDstBufAddr.
XAXICDMA_BD_BUFDST_MSB_OFFSET
Buffer destination address.
Referenced by XAxiCdma_BdGetDstBufAddr, XAxiCdma_BdSetDstBufAddr.
XAXICDMA_BD_CTRL_LEN_OFFSET
Control/buffer length.
Referenced by XAxiCdma_BdGetLength, XAxiCdma_BdSetLength.
XAXICDMA_BD_STS_OFFSET
Status.
Referenced by XAxiCdma_BdClearSts, XAxiCdma_BdGetSts.
XAXICDMA_BD_PHYS_ADDR_OFFSET
Physical address of the BD.
Referenced by XAxiCdma_BdGetPhysAddr, XAxiCdma_BdSetPhysAddr.
XAXICDMA_BD_PHYS_ADDR_MSB_OFFSET
Physical address of the BD.
Referenced by XAxiCdma_BdGetPhysAddr, XAxiCdma_BdSetPhysAddr.
XAXICDMA_BD_ISLITE_OFFSET
Lite mode hardware build?
Referenced by XAxiCdma_BdSetIsLite, XAxiCdma_DumpBd.
XAXICDMA_BD_HASDRE_OFFSET
Support unaligned transfers?
Referenced by XAxiCdma_BdSetDstBufAddr, XAxiCdma_BdSetHasDRE, XAxiCdma_BdSetSrcBufAddr, XAxiCdma_DumpBd.
XAXICDMA_BD_WORDLEN_OFFSET
Word length in bytes.
Referenced by XAxiCdma_BdSetDstBufAddr, XAxiCdma_BdSetSrcBufAddr, XAxiCdma_BdSetWordLen, XAxiCdma_DumpBd.
XAXICDMA_BD_MAX_LEN_OFFSET
Word length in bytes.
Referenced by XAxiCdma_BdSetLength, XAxiCdma_BdSetMaxLen, XAxiCdma_DumpBd.
XAXICDMA_BD_ADDRLEN_OFFSET
Word length in bytes.
XAXICDMA_BD_START_CLEAR
Offset to start clear.
Referenced by XAxiCdma_BdClear, XAxiCdma_BdClone.
XAXICDMA_BD_TO_CLEAR
BD specific bytes to be cleared.
Referenced by XAxiCdma_BdClear, XAxiCdma_BdClone.
XAXICDMA_BD_NUM_WORDS
Total number of words for one BD.
XAXICDMA_BD_HW_NUM_BYTES
Number of bytes hw used.
XAXICDMA_BD_CTRL_LENGTH_MASK
Requested len.
XAXICDMA_BD_STS_COMPLETE_MASK
Completed.
Referenced by XAxiCdma_BdRingFromHw.
XAXICDMA_BD_STS_DEC_ERR_MASK
Decode error.
XAXICDMA_BD_STS_SLV_ERR_MASK
Slave error.
XAXICDMA_BD_STS_INT_ERR_MASK
Internal err.
XAXICDMA_BD_STS_ALL_ERR_MASK
All errors.
XAXICDMA_BD_STS_ALL_MASK
All status bits.
Referenced by XAxiCdma_BdGetSts.
typedef UINTPTR XAxiCdma_Bd[XAXICDMA_BD_NUM_WORDS][XAXICDMA_BD_NUM_WORDS]
XAxiCdma_Bd.
Buffer descriptor, shared by hardware and software The structure of the BD is as the following, however, the user never directly accesses the fields in the BD. The following shows the fields inside a BD:u32 NextBdPtr; u32 NextBdPtrMsb; u32 SrcAddr; u32 SrcAddrMsb; u32 DstAddr; u32 DstAddrMsb; int Length; u32 Status; u32 PhysAddr; u32 IsLite; u32 HasDRE; u32 WordLen; u32 Addrlen;
XAxiCdma_Config XAxiCdma_ConfigTable[][]
u32 XAxiCdma_GetError(XAxiCdma *InstancePtr)
This function gets the status on error bits.
InstancePtr is the driver instance we are working on The error bits in the status register. Zero indicates no errors. None.
References XAxiCdma_ReadReg, XAXICDMA_SR_ERR_ALL_MASK, XAXICDMA_SR_OFFSET.
Referenced by XAxiCdma_SgIntrExample.
void XAxiCdma_Reset(XAxiCdma *InstancePtr)
This function conducts hardware reset.
Current transfer will finish gracefully. However, all queued SG transfers that have not started will be flushed from the hardware. InstancePtr is the driver instance we are working on None None.
References XAXICDMA_CR_OFFSET, XAXICDMA_CR_RESET_MASK, XAxiCdma_WriteReg.
Referenced by XAxiCdma_CfgInitialize, XAxiCdma_IntrHandler, XAxiCdma_SgPollExample.
int XAxiCdma_ResetIsDone(XAxiCdma *InstancePtr)
This function checks whether the hardware reset is done.
InstancePtr is the driver instance we are working on 1 if the reset has finished successfully0 if the reset is not done None.
References XAXICDMA_CR_OFFSET, XAXICDMA_CR_RESET_MASK, XAxiCdma_ReadReg.
Referenced by XAxiCdma_CfgInitialize, XAxiCdma_IntrHandler, XAxiCdma_SgPollExample.
u32 XAxiCdma_CfgInitialize(XAxiCdma *InstancePtr, XAxiCdma_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the driver.
It should be called before any other function calls to the driver.It sets up the driver according to the hardware build. It resets the hardware at the end. InstancePtr is the driver instance that is working on CfgPtr is the pointer to the hardware configuration structure EffectiveAddr is the virtual address of the hardware instance. If address translation is not in use, please use the physical address XST_SUCCESS for successXST_INVALID_PARAM if word length is less than 4XST_FAILURE for reset failure None.
References XAXICDMA_4_1_MAX_TRANSFER_LEN, XAXICDMA_MAX_TRANSFER_LEN, XAxiCdma_ReadReg, XAxiCdma_Reset, XAxiCdma_ResetIsDone, XAXICDMA_SR_OFFSET, XAXICDMA_SR_SGINCLD_MASK.
Referenced by XAxiCdma_HybridIntrExample, XAxiCdma_HybridPollExample, XAxiCdma_SgIntrExample, XAxiCdma_SgPollExample, XAxiCdma_SimpleIntrExample, XAxiCdma_SimplePollExample.
int XAxiCdma_IsBusy(XAxiCdma *InstancePtr)
This function checks whether the hardware is doing transfer.
InstancePtr is the driver instance we are working on 1 if the hardware is doing a transfer0 if the hardware is idle None.
References XAxiCdma_ReadReg, XAXICDMA_SR_IDLE_MASK, XAXICDMA_SR_OFFSET.
Referenced by XAxiCdma_BdRingClone, XAxiCdma_SelectKeyHole, XAxiCdma_SimpleTransfer.
int XAxiCdma_IsSimpleMode(XAxiCdma *InstancePtr)
int XAxiCdma_SelectKeyHole(XAxiCdma *InstancePtr, u32 Direction, u32 Select)
This function configures KeyHole Write/Read Feature.
InstancePtr is the driver instance we are working on Direction is WRITE/READ Select is the option to enable (TRUE) or disable (FALSE). - XST_SUCCESS for success XST_DEVICE_BUSY when transfer is in progressXST_NO_FEATURE when not configured with feature None.
References XAxiCdma_BdRingGetCurrBd, XAxiCdma_BdRingNext, XAxiCdma_BdSetCurBdPtr, XAXICDMA_CR_KHOLE_RD_MASK, XAXICDMA_CR_KHOLE_WR_MASK, XAXICDMA_CR_OFFSET, XAXICDMA_CR_SGMODE_MASK, XAxiCdma_IsBusy, XAxiCdma_ReadReg, XAxiCdma_WriteReg.
int XAxiCdma_SwitchMode(XAxiCdma *InstancePtr, int Mode)
u32 XAxiCdma_SimpleTransfer(XAxiCdma *InstancePtr, UINTPTR SrcAddr, UINTPTR DstAddr, int Length, XAxiCdma_CallBackFn SimpleCallBack, void *CallBackRef)
This function does one simple transfer submission.
It checks in the following sequence: if engine is busy, cannot submitif software is still handling the completion of the previous simple transfer, cannot submitif engine is in SG mode and cannot switch to simple mode, cannot submit InstancePtr is the pointer to the driver instance SrcAddr is the address of the source buffer DstAddr is the address of the destination buffer Length is the length of the transfer SimpleCallBack is the callback function for the simple transfer CallBackRef is the callback reference pointer XST_SUCCESS for success of submissionXST_FAILURE for submission failure, maybe caused by: Another simple transfer is still going . Another SG transfer is still goingXST_INVALID_PARAM if: Length out of valid range [1: XAXICDMA_MAX_TRANSFER_LEN] Or, address not aligned when DRE is not built in Only set the callback function if using interrupt to signal the completion.If used in polling mode, please set the callback function to be NULL.
References XAXICDMA_BTT_OFFSET, XAXICDMA_DSTADDR_MSB_OFFSET, XAXICDMA_DSTADDR_OFFSET, XAxiCdma_IntrGetEnabled, XAxiCdma_IsBusy, XAXICDMA_MAX_TRANSFER_LEN, XAXICDMA_SRCADDR_MSB_OFFSET, XAXICDMA_SRCADDR_OFFSET, XAxiCdma_WriteReg, XAXICDMA_XR_IRQ_SIMPLE_ALL_MASK.
int XAxiCdma_SetCoalesce(XAxiCdma *InstancePtr, u32 Counter, u32 Delay)
This function tries to set the interrupt coalescing threshold counter and the delay counter.
If to set only one of the counters, set the value of the other counter to be XAXICDMA_COALESCE_NO_CHANGE. InstancePtr is the driver instance we are working on Counter is the coalescing threshold to set to, the valid range is 1 to XAXICDMA_COALESCE_MAX. Delay is the delay timeout counter to set to, the valid range is 0 to XAXICDMA_DELAY_MAX. Setting a value of 0 disables the delay interrupt. XST_SUCCESS for successXST_FAILURE if hardware is in invalid state, for example, reset failedXST_INVALID_PARAM if one of the counters is not in the valid range None.
References XAXICDMA_COALESCE_MAX, XAXICDMA_CR_OFFSET, XAXICDMA_DELAY_MAX, XAxiCdma_ReadReg, XAxiCdma_WriteReg, XAXICDMA_XR_COALESCE_MASK, XAXICDMA_XR_DELAY_MASK.
void XAxiCdma_GetCoalesce(XAxiCdma *InstancePtr, u32 *CounterPtr, u32 *DelayPtr)
This function gets the current setting of the interrupt coalescing threshold counter and the delay counter.
InstancePtr is the driver instance we are working on CounterPtr is the return value for the coalescing counter setting DelayPtr is the return value for the delay counter setting A zero coalescing threshold indicates invalid results None.
References XAXICDMA_CR_OFFSET, XAxiCdma_ReadReg, XAXICDMA_XR_COALESCE_MASK, XAXICDMA_XR_DELAY_MASK.
void XAxiCdma_DumpRegisters(XAxiCdma *InstancePtr)
This function dumps the registers of this DMA instance.
InstancePtr is the driver instance we are working on None None.
References XAXICDMA_BTT_OFFSET, XAXICDMA_CDESC_MSB_OFFSET, XAXICDMA_CDESC_OFFSET, XAXICDMA_CR_OFFSET, XAXICDMA_DSTADDR_MSB_OFFSET, XAXICDMA_DSTADDR_OFFSET, XAxiCdma_ReadReg, XAXICDMA_SR_OFFSET, XAXICDMA_SRCADDR_MSB_OFFSET, XAXICDMA_SRCADDR_OFFSET, XAXICDMA_TDESC_MSB_OFFSET, XAXICDMA_TDESC_OFFSET.
XAxiCdma_Config * XAxiCdma_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
A table contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration table entry corresponding to the given device ID/BaseAddress, or NULL if no match is found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
Referenced by XAxiCdma_HybridIntrExample, XAxiCdma_HybridPollExample, XAxiCdma_SgIntrExample, XAxiCdma_SgPollExample, XAxiCdma_SimpleIntrExample, XAxiCdma_SimplePollExample.
void XAxiCdma_IntrEnable(XAxiCdma *InstancePtr, u32 Mask)
This function enables interrupts specified by the Mask.
Interrupts that are not in the mask are not affected. InstancePtr is the driver instance we are working on Mask is the mask for the interrupts to be enabled None None.
References XAXICDMA_CR_OFFSET, XAxiCdma_ReadReg, XAxiCdma_WriteReg, XAXICDMA_XR_IRQ_ALL_MASK.
Referenced by XAxiCdma_HybridIntrExample, XAxiCdma_SgIntrExample, XAxiCdma_SimpleIntrExample.
u32 XAxiCdma_IntrGetEnabled(XAxiCdma *InstancePtr)
This function gets the mask for the interrupts that are currently enabled.
InstancePtr is the driver instance we are working on The bit mask for the interrupts that are currently enabled None.
References XAXICDMA_CR_OFFSET, XAxiCdma_ReadReg, XAXICDMA_XR_IRQ_ALL_MASK.
Referenced by XAxiCdma_SimpleTransfer.
void XAxiCdma_IntrDisable(XAxiCdma *InstancePtr, u32 Mask)
This function disables interrupts specified by the Mask.
Interrupts that are not in the mask are not affected. InstancePtr is the driver instance we are working on Mask is the mask for the interrupts to be disabled None None.
References XAXICDMA_CR_OFFSET, XAxiCdma_ReadReg, XAxiCdma_WriteReg, XAXICDMA_XR_IRQ_ALL_MASK.
Referenced by XAxiCdma_HybridPollExample, XAxiCdma_SimplePollExample.
void XAxiCdma_IntrHandler(void *HandlerRef)
This function is the interrupt handler for the driver, it handles all the interrupts.
For the completion of a transfer that has a callback function, the callback function is called. HandlerRef is a reference pointer passed to the interrupt registration function. It will be a pointer to the driver instance we are working on None If one transfer does not have all its submitted BDs completed successfully,then a reset is needed to clean up the mess left by that transfer.Otherwise, the wrong interrupt callback maybe called for the following transfers. However, if you always use the same interrupt callback for all the transfers, and you are the only user of the DMA engine, then you do not have to worry about this.
References XAxiCdma_ReadReg, XAxiCdma_Reset, XAxiCdma_ResetIsDone, XAXICDMA_SR_ERR_ALL_MASK, XAXICDMA_SR_OFFSET, XAxiCdma_WriteReg, XAXICDMA_XR_IRQ_ALL_MASK, XAXICDMA_XR_IRQ_ERROR_MASK.
Referenced by XAxiCdma_SimpleIntrExample.
u32 XAxiCdma_BdRingCntCalc(u32 Alignment, u32 Bytes, UINTPTR BdBuffAddr)
This function calculates how many BDs can be built using given number of bytes of memory, according to alignment provided.
Alignment is the preferred alignment for the BDs Bytes is the number of bytes of memory to build BDs with BdBuffAddr is the buffer address allocated for the BDs. This is to check the alignment of the buffer to make sure the the buffer is aligned to the BD alignment. An invalid buffer address results in 0. The number of BDs can be built. 0 means buffer address is not valid. The application is responsible to align the buffer before pass it to this function.
u32 XAxiCdma_BdRingMemCalc(u32 Alignment, int NumBd)
This function calculates how much memory is needed to build requested number of BDs.
Alignment is the preferred alignment for the BDs NumBd is the number of BDs to be built The number of bytes of memory needed to build the BDs None.
u32 XAxiCdma_BdRingGetCnt(XAxiCdma *InstancePtr)
This function gets the total number of BDs in the BD ring.
InstancePtr is the driver instance we are working on The total number of BDs for this instance None.
u32 XAxiCdma_BdRingGetFreeCnt(XAxiCdma *InstancePtr)
This function gets the number of free BDs.
InstancePtr is the driver instance we are working on The total number of free BDs for this instance None.
void XAxiCdma_BdRingSnapShotCurrBd(XAxiCdma *InstancePtr)
This function grabs a copy of the current BD pointer from the hardware.
It is normally used to prepare for the hardware reset. The snapshot of the current BD pointer should be reloaded once the reset is done. InstancePtr is the driver instance we are working on None None.
References XAxiCdma_BdRingGetCurrBd, XAxiCdma_BdRingNext.
XAxiCdma_Bd * XAxiCdma_BdRingGetCurrBd(XAxiCdma *InstancePtr)
This function grabs a copy of the current BD pointer from the hardware.
InstancePtr is the driver instance we are working on The BD pointer in CDESC register None.
References XAXICDMA_CDESC_MSB_OFFSET, XAXICDMA_CDESC_OFFSET.
Referenced by XAxiCdma_BdRingSnapShotCurrBd, XAxiCdma_SelectKeyHole.
XAxiCdma_Bd * XAxiCdma_BdRingNext(XAxiCdma *InstancePtr, XAxiCdma_Bd *BdPtr)
This function gets the next BD of the current BD on the BD ring.
InstancePtr is the driver instance we are working on BdPtr is the current BD The next BD on the ring from the current BD, NULL if passed in BdPtr not valid. None.
References XAXICDMA_BD_MINIMUM_ALIGNMENT.
Referenced by XAxiCdma_BdRingFromHw, XAxiCdma_BdRingSnapShotCurrBd, XAxiCdma_BdRingToHw, XAxiCdma_SelectKeyHole.
XAxiCdma_Bd * XAxiCdma_BdRingPrev(XAxiCdma *InstancePtr, XAxiCdma_Bd *BdPtr)
This function gets the previous BD of the current BD on the BD ring.
InstancePtr is the driver instance we are working on BdPtr is the current BD The previous BD on the ring from the current BD None.
References XAXICDMA_BD_MINIMUM_ALIGNMENT.
Referenced by XAxiCdma_BdRingToHw.
LONG XAxiCdma_BdRingCreate(XAxiCdma *InstancePtr, UINTPTR PhysAddr, UINTPTR VirtAddr, u32 Alignment, int BdCount)
This function creates the BD ring for the driver instance.
If a BD ring pre-exist of this ring, the previous ring is lost. InstancePtr is the driver instance we are working on PhysAddr is the physical address of the memory for the BD ring VirtAddr is the virtual address of the memory for the BD ring Alignment is the alignment for the BDs BdCount is the number of BDs to create in the ring XST_SUCCESS for successXST_INVALID_PARAM for invalid parameterXST_DMA_SG_LIST_ERROR for invalid memory regionXST_FAILURE if the hardware build is simple mode only For a system that has flat memory layout, then the PhysAddr and the VirtAddr are the same.
References XAXICDMA_BD_MINIMUM_ALIGNMENT, XAxiCdma_BdSetHasDRE, XAxiCdma_BdSetIsLite, XAxiCdma_BdSetMaxLen, XAxiCdma_BdSetNextPtr, XAxiCdma_BdSetPhysAddr, XAxiCdma_BdSetWordLen.
LONG XAxiCdma_BdRingClone(XAxiCdma *InstancePtr, XAxiCdma_Bd *TemplateBdPtr)
This function clones all BDs in the BD ring to be the same as the given BD.
InstancePtr is the driver instance we are working on TemplateBdPtr is the BD to be copied from XST_SUCCESS for successXST_DMA_SG_NO_LIST if there is no BD ringXST_DEVICE_IS_STARTED if the hardware is runningXST_DMA_SG_LIST_ERROR is the BD ring is still in use None.
References XAxiCdma_BdClearSts, XAxiCdma_BdClone, XAxiCdma_IsBusy.
LONG XAxiCdma_BdRingAlloc(XAxiCdma *InstancePtr, int NumBd, XAxiCdma_Bd **BdSetPtr)
This function requests number of BDs from the BD ring.
InstancePtr is the driver instance we are working on NumBd is the number of BDs to request BdSetPtr is the pointer to the set of BDs returned XST_SUCCESS for successXST_INVALID_PARAM if requests non-positive number of BDsXST_FAILURE if not enough free BDs available None.
LONG XAxiCdma_BdRingUnAlloc(XAxiCdma *InstancePtr, int NumBd, XAxiCdma_Bd *BdSetPtr)
This function tries to free the number of BDs back to the ring.
InstancePtr is the driver instance we are working on NumBd is the number of BDs to return BdSetPtr is the set of BDs to be returned XST_SUCCESS for successXST_INVALID_PARAM if to free non-positive number of BDsXST_FAILURE if BD ring management shows an error None.
LONG XAxiCdma_BdRingToHw(XAxiCdma *InstancePtr, int NumBd, XAxiCdma_Bd *BdSetPtr, XAxiCdma_CallBackFn CallBackFn, void *CallBackRef)
This function tries to enqueue the number of BDs to the hardware.
InstancePtr is the driver instance we are working on NumBd is the number of BDs to enqueue BdSetPtr is the set of BDs to be enqueued CallBackFn is the callback function for this transfer, NULL is fine CallBackRef is the callback reference pointer XST_SUCCESS for successXST_INVALID_PARAM if enqueues negative number of BDs or zero transfer lenXST_DMA_SG_LIST_ERROR if BD ring management has a problemXST_FIFO_NO_ROOM if the interrupt handler array is fullXST_FAILURE for: Hardware is in invalid state, for example, reset failed Or, the hardware build is simple mode only None.
References XAxiCdma_BdClearSts, XAxiCdma_BdGetLength, XAxiCdma_BdGetPhysAddr, XAxiCdma_BdRingNext, XAxiCdma_BdRingPrev, XAxiCdma_BdSetTailBdPtr.
u32 XAxiCdma_BdRingFromHw(XAxiCdma *InstancePtr, int BdLimit, XAxiCdma_Bd **BdSetPtr)
This function tries to retrieve completed BDs from the hardware.
InstancePtr is the driver instance we are working on BdLimit is the maximum number of completed BDs to retrieve BdSetPtr is the set of completed BDs The number of completed BDs. None.
References XAXICDMA_BD_STS_COMPLETE_MASK, XAxiCdma_BdGetSts, XAxiCdma_BdRingNext.
u32 XAxiCdma_BdRingFree(XAxiCdma *InstancePtr, int NumBd, XAxiCdma_Bd *BdSetPtr)
This function returns the BDs back to the free pool of the BD ring.
InstancePtr is the driver instance we are working on NumBd is the number of BDs to free BdSetPtr is the set of BDs to be freed XST_SUCCESS for successXST_INVALID_PARAM if number of BDs is negativeXST_DMA_SG_LIST_ERROR if the BD ring management has a problem None.
void XAxiCdma_BdSetCurBdPtr(XAxiCdma *InstancePtr, UINTPTR CurBdPtr)
This function set the Current BD ptr of a BD.
BdPtr is the pointer to the BD to set the Next BD ptr CurBdPtr is the valud of Current BD ptr None None.
References XAXICDMA_CDESC_MSB_OFFSET, XAXICDMA_CDESC_OFFSET, XAXICDMA_DESC_LSB_MASK, XAxiCdma_WriteReg.
Referenced by XAxiCdma_SelectKeyHole.
void XAxiCdma_BdSetTailBdPtr(XAxiCdma *InstancePtr, UINTPTR TailBdPtr)
This function set the Tail BD ptr of a BD.
BdPtr is the pointer to the BD to set the Next BD ptr Tail Bd is the value of Tail BD ptr None None.
References XAXICDMA_DESC_LSB_MASK, XAXICDMA_TDESC_MSB_OFFSET, XAXICDMA_TDESC_OFFSET, XAxiCdma_WriteReg.
Referenced by XAxiCdma_BdRingToHw.
void XAxiCdma_BdClear(XAxiCdma_Bd *BdPtr)
This function clears the content of the BD.
BdPtr is the pointer to the BD to be cleared None. None.
References XAXICDMA_BD_START_CLEAR, XAXICDMA_BD_TO_CLEAR.
void XAxiCdma_BdClone(XAxiCdma_Bd *BdPtr, XAxiCdma_Bd *TmpBd)
This function clones the content from the template BD.
BdPtr is the pointer to the BD to be cloned to TmpBd is the pointer to the BD to be cloned from None. None.
References XAXICDMA_BD_START_CLEAR, XAXICDMA_BD_TO_CLEAR.
Referenced by XAxiCdma_BdRingClone.
LONG XAxiCdma_BdGetNextPtr(XAxiCdma_Bd *BdPtr)
This function gets the next BD pointer of the BD.
BdPtr is the pointer to the BD to get the next BD ptr The next BD ptr of the BD. None.
References XAXICDMA_BD_NDESC_MSB_OFFSET, XAXICDMA_BD_NDESC_OFFSET.
Referenced by XAxiCdma_DumpBd.
void XAxiCdma_BdSetNextPtr(XAxiCdma_Bd *BdPtr, UINTPTR NextBdPtr)
This function set the Next BD ptr of a BD.
BdPtr is the pointer to the BD to set the Next BD ptr NextBdPtr is the valud of Next BD ptr None None.
References XAXICDMA_BD_NDESC_MSB_OFFSET, XAXICDMA_BD_NDESC_OFFSET, XAXICDMA_DESC_LSB_MASK.
Referenced by XAxiCdma_BdRingCreate.
u32 XAxiCdma_BdGetSts(XAxiCdma_Bd *BdPtr)
This function gets the completion status of the BD.
BdPtr is the pointer to the BD to get the status The status bits of the BD. None.
References XAXICDMA_BD_STS_ALL_MASK, XAXICDMA_BD_STS_OFFSET.
Referenced by XAxiCdma_BdRingFromHw, XAxiCdma_DumpBd.
void XAxiCdma_BdClearSts(XAxiCdma_Bd *BdPtr)
This function clears the status bits of the BD.
The status bits include the completion bit as well as the error bits.This is the only function that needs to be called to clear a completed BD. All other fields (except reserved words) need to be re-assigned before re-submission. BdPtr is the pointer to the BD to clear the status None None.
References XAXICDMA_BD_STS_OFFSET.
Referenced by XAxiCdma_BdRingClone, XAxiCdma_BdRingToHw.
u32 XAxiCdma_BdSetSrcBufAddr(XAxiCdma_Bd *BdPtr, UINTPTR Addr)
This function sets the source address of the BD.
BdPtr is the pointer to the BD to set the source address Addr is the source address of the buffer XST_SUCCESS if buffer address set successfullyXST_INVALID_PARAM if buffer address is not aligned and hardware build has no DRE or in lite mode None.
References XAXICDMA_BD_BUFSRC_MSB_OFFSET, XAXICDMA_BD_BUFSRC_OFFSET, XAXICDMA_BD_HASDRE_OFFSET, XAXICDMA_BD_WORDLEN_OFFSET.
LONG XAxiCdma_BdGetSrcBufAddr(XAxiCdma_Bd *BdPtr)
This function gets the source address of the BD.
BdPtr is the pointer to the BD to get the source address The source address of the buffer that this BD describes None.
References XAXICDMA_BD_BUFSRC_MSB_OFFSET, XAXICDMA_BD_BUFSRC_OFFSET.
Referenced by XAxiCdma_DumpBd.
u32 XAxiCdma_BdSetDstBufAddr(XAxiCdma_Bd *BdPtr, UINTPTR Addr)
This function sets the destination address of the BD.
BdPtr is the pointer to the BD to set the destination address Addr is the destination address of the buffer XST_SUCCESS if buffer address set successfullyXST_INVALID_PARAM if buffer address is not aligned and hardware build has no DRE or in lite mode None.
References XAXICDMA_BD_BUFDST_MSB_OFFSET, XAXICDMA_BD_BUFDST_OFFSET, XAXICDMA_BD_HASDRE_OFFSET, XAXICDMA_BD_WORDLEN_OFFSET.
LONG XAxiCdma_BdGetDstBufAddr(XAxiCdma_Bd *BdPtr)
This function gets the destination address of the BD.
BdPtr is the pointer to the BD to get the destination address The destination address of the buffer that this BD describes None
References XAXICDMA_BD_BUFDST_MSB_OFFSET, XAXICDMA_BD_BUFDST_OFFSET.
Referenced by XAxiCdma_DumpBd.
u32 XAxiCdma_BdSetLength(XAxiCdma_Bd *BdPtr, int LenBytes)
This function sets the length of the BD.
BdPtr is the pointer to the BD to set the length LenBytes is the length of the buffer XST_SUCCESS for successXST_INVALID_PARAM if invalid length: Length value out of valid range One case that will cause hardware failure is not covered here: If the start address is not at page offset 0, and the length plus the offset crosses the page boundary, this will cause slave error if the hardware is built in lite mode.
References XAXICDMA_BD_CTRL_LEN_OFFSET, XAXICDMA_BD_MAX_LEN_OFFSET.
u32 XAxiCdma_BdGetLength(XAxiCdma_Bd *BdPtr)
This function gets the length of the BD.
BdPtr is the pointer to the BD to get the length The length of the buffer that this BD describes None
References XAXICDMA_BD_CTRL_LEN_OFFSET.
Referenced by XAxiCdma_BdRingToHw, XAxiCdma_DumpBd.
void XAxiCdma_BdSetPhysAddr(XAxiCdma_Bd *BdPtr, UINTPTR PhysAddr)
This function sets the Physical address of the BD.
BdPtr is the pointer to the BD to set the physical address PhysAddr is the physical address of the BD None None
References XAXICDMA_BD_PHYS_ADDR_MSB_OFFSET, XAXICDMA_BD_PHYS_ADDR_OFFSET.
Referenced by XAxiCdma_BdRingCreate.
void XAxiCdma_BdSetIsLite(XAxiCdma_Bd *BdPtr, int IsLite)
This function sets the is lite mode field of the BD.
BdPtr is the pointer to the BD to work on IsLite is the value for whether hardware is in lite mode None None
References XAXICDMA_BD_ISLITE_OFFSET.
Referenced by XAxiCdma_BdRingCreate.
void XAxiCdma_BdSetHasDRE(XAxiCdma_Bd *BdPtr, int HasDRE)
This function sets the has DRE field of the BD.
BdPtr is the pointer to the BD to work on HasDRE is the value for whether hardware has DRE built in None None
References XAXICDMA_BD_HASDRE_OFFSET.
Referenced by XAxiCdma_BdRingCreate.
void XAxiCdma_BdSetWordLen(XAxiCdma_Bd *BdPtr, int WordLen)
This function sets the word length field of the BD.
BdPtr is the pointer to the BD to work on WordLen is the length of word in bytes None None
References XAXICDMA_BD_WORDLEN_OFFSET.
Referenced by XAxiCdma_BdRingCreate.
void XAxiCdma_BdSetMaxLen(XAxiCdma_Bd *BdPtr, int MaxLen)
This function sets the maximum transfer length field of the BD.
BdPtr is the pointer to the BD to work on MaxLen is the maximum transfer length in bytes None None
References XAXICDMA_BD_MAX_LEN_OFFSET.
Referenced by XAxiCdma_BdRingCreate.
LONG XAxiCdma_BdGetPhysAddr(XAxiCdma_Bd *BdPtr)
This function gets the Physical address of the BD.
BdPtr is the pointer to the BD to get the physical address The physical address of the BD None
References XAXICDMA_BD_PHYS_ADDR_MSB_OFFSET, XAXICDMA_BD_PHYS_ADDR_OFFSET.
Referenced by XAxiCdma_BdRingToHw, XAxiCdma_DumpBd.
void XAxiCdma_DumpBd(XAxiCdma_Bd *BdPtr)
This function dumps the BD, it is a debug utility.
BdPtr is the pointer to the BD to get the physical address None None
References XAXICDMA_BD_HASDRE_OFFSET, XAXICDMA_BD_ISLITE_OFFSET, XAXICDMA_BD_MAX_LEN_OFFSET, XAXICDMA_BD_WORDLEN_OFFSET, XAxiCdma_BdGetDstBufAddr, XAxiCdma_BdGetLength, XAxiCdma_BdGetNextPtr, XAxiCdma_BdGetPhysAddr, XAxiCdma_BdGetSrcBufAddr, XAxiCdma_BdGetSts.
static void StubCallBackFn(void *CallBackRef, u32 IrqMask, int *NumBdPtr)
int XAxiCdma_BdRingStartTransfer(XAxiCdma *InstancePtr)
XAXICDMA_COALESCE_NO_CHANGE
XAXICDMA_ALL_BDS
XAXICDMA_SG_MODE
XAXICDMA_SIMPLE_MODE
XAXICDMA_MAXIMUM_MAX_HANDLER
XAXICDMA_KEYHOLE_READ
XAXICDMA_KEYHOLE_WRITE
XAXICDMA_CACHE_FLUSH
XAXICDMA_CACHE_INVALIDATE
XAXICDMA_PAGE_SIZE
XAxiCdma_BdRead
XAxiCdma_BdWrite
XAxiCdma_BdSetAddrLen
XAxiCdma_BdGetAddrLength
XAXICDMA_RING_SEEKAHEAD
XAXICDMA_RING_SEEKBACK
XAxiCdma_In32
XAxiCdma_Out32
XAxiCdma_ReadReg
Read a given register.
BaseAddress is the base virtual address of the device RegOffset is the register offset to be read The 32-bit value of the register C-style signature: u32 XAxiCdma_ReadReg(u32 BaseAddress, u32 RegOffset)
Referenced by XAxiCdma_CfgInitialize, XAxiCdma_DumpRegisters, XAxiCdma_GetCoalesce, XAxiCdma_GetError, XAxiCdma_IntrDisable, XAxiCdma_IntrEnable, XAxiCdma_IntrGetEnabled, XAxiCdma_IntrHandler, XAxiCdma_IsBusy, XAxiCdma_ResetIsDone, XAxiCdma_SelectKeyHole, XAxiCdma_SetCoalesce.
XAxiCdma_WriteReg
Write to a given register.
BaseAddress is the base virtual address of the device RegOffset is the register offset to be written Data is the 32-bit value to write to the register None. C-style signature: void XAxiCdma_WriteReg(u32 BaseAddress, u32 RegOffset, u32 Data)
Referenced by XAxiCdma_BdSetCurBdPtr, XAxiCdma_BdSetTailBdPtr, XAxiCdma_IntrDisable, XAxiCdma_IntrEnable, XAxiCdma_IntrHandler, XAxiCdma_Reset, XAxiCdma_SelectKeyHole, XAxiCdma_SetCoalesce, XAxiCdma_SimpleTransfer.
XAXICDMA_RESET_LOOP_LIMIT