xaxicdma.c
u32 XAxiCdma_GetError(XAxiCdma *InstancePtr)
This function gets the status on error bits.
InstancePtr is the driver instance we are working on The error bits in the status register. Zero indicates no errors. None.
References XAxiCdma_ReadReg, XAXICDMA_SR_ERR_ALL_MASK, XAXICDMA_SR_OFFSET.
Referenced by XAxiCdma_SgIntrExample.
void XAxiCdma_Reset(XAxiCdma *InstancePtr)
This function conducts hardware reset.
Current transfer will finish gracefully. However, all queued SG transfers that have not started will be flushed from the hardware. InstancePtr is the driver instance we are working on None None.
References XAXICDMA_CR_OFFSET, XAXICDMA_CR_RESET_MASK, XAxiCdma_WriteReg.
Referenced by XAxiCdma_CfgInitialize, XAxiCdma_IntrHandler, XAxiCdma_SgPollExample.
int XAxiCdma_ResetIsDone(XAxiCdma *InstancePtr)
This function checks whether the hardware reset is done.
InstancePtr is the driver instance we are working on 1 if the reset has finished successfully0 if the reset is not done None.
References XAXICDMA_CR_OFFSET, XAXICDMA_CR_RESET_MASK, XAxiCdma_ReadReg.
Referenced by XAxiCdma_CfgInitialize, XAxiCdma_IntrHandler, XAxiCdma_SgPollExample.
u32 XAxiCdma_CfgInitialize(XAxiCdma *InstancePtr, XAxiCdma_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the driver.
It should be called before any other function calls to the driver.It sets up the driver according to the hardware build. It resets the hardware at the end. InstancePtr is the driver instance that is working on CfgPtr is the pointer to the hardware configuration structure EffectiveAddr is the virtual address of the hardware instance. If address translation is not in use, please use the physical address XST_SUCCESS for successXST_INVALID_PARAM if word length is less than 4XST_FAILURE for reset failure None.
References XAXICDMA_4_1_MAX_TRANSFER_LEN, XAXICDMA_MAX_TRANSFER_LEN, XAxiCdma_ReadReg, XAxiCdma_Reset, XAxiCdma_ResetIsDone, XAXICDMA_SR_OFFSET, XAXICDMA_SR_SGINCLD_MASK.
Referenced by XAxiCdma_HybridIntrExample, XAxiCdma_HybridPollExample, XAxiCdma_SgIntrExample, XAxiCdma_SgPollExample, XAxiCdma_SimpleIntrExample, XAxiCdma_SimplePollExample.
int XAxiCdma_IsBusy(XAxiCdma *InstancePtr)
This function checks whether the hardware is doing transfer.
InstancePtr is the driver instance we are working on 1 if the hardware is doing a transfer0 if the hardware is idle None.
References XAxiCdma_ReadReg, XAXICDMA_SR_IDLE_MASK, XAXICDMA_SR_OFFSET.
Referenced by XAxiCdma_BdRingClone, XAxiCdma_SelectKeyHole, XAxiCdma_SimpleTransfer.
int XAxiCdma_IsSimpleMode(XAxiCdma *InstancePtr)
int XAxiCdma_SelectKeyHole(XAxiCdma *InstancePtr, u32 Direction, u32 Select)
This function configures KeyHole Write/Read Feature.
InstancePtr is the driver instance we are working on Direction is WRITE/READ Select is the option to enable (TRUE) or disable (FALSE). - XST_SUCCESS for success XST_DEVICE_BUSY when transfer is in progressXST_NO_FEATURE when not configured with feature None.
References XAxiCdma_BdRingGetCurrBd, XAxiCdma_BdRingNext, XAxiCdma_BdSetCurBdPtr, XAXICDMA_CR_KHOLE_RD_MASK, XAXICDMA_CR_KHOLE_WR_MASK, XAXICDMA_CR_OFFSET, XAXICDMA_CR_SGMODE_MASK, XAxiCdma_IsBusy, XAxiCdma_ReadReg, XAxiCdma_WriteReg.
int XAxiCdma_SwitchMode(XAxiCdma *InstancePtr, int Mode)
u32 XAxiCdma_SimpleTransfer(XAxiCdma *InstancePtr, UINTPTR SrcAddr, UINTPTR DstAddr, int Length, XAxiCdma_CallBackFn SimpleCallBack, void *CallBackRef)
This function does one simple transfer submission.
It checks in the following sequence: if engine is busy, cannot submitif software is still handling the completion of the previous simple transfer, cannot submitif engine is in SG mode and cannot switch to simple mode, cannot submit InstancePtr is the pointer to the driver instance SrcAddr is the address of the source buffer DstAddr is the address of the destination buffer Length is the length of the transfer SimpleCallBack is the callback function for the simple transfer CallBackRef is the callback reference pointer XST_SUCCESS for success of submissionXST_FAILURE for submission failure, maybe caused by: Another simple transfer is still going . Another SG transfer is still goingXST_INVALID_PARAM if: Length out of valid range [1: XAXICDMA_MAX_TRANSFER_LEN] Or, address not aligned when DRE is not built in Only set the callback function if using interrupt to signal the completion.If used in polling mode, please set the callback function to be NULL.
References XAXICDMA_BTT_OFFSET, XAXICDMA_DSTADDR_MSB_OFFSET, XAXICDMA_DSTADDR_OFFSET, XAxiCdma_IntrGetEnabled, XAxiCdma_IsBusy, XAXICDMA_MAX_TRANSFER_LEN, XAXICDMA_SRCADDR_MSB_OFFSET, XAXICDMA_SRCADDR_OFFSET, XAxiCdma_WriteReg, XAXICDMA_XR_IRQ_SIMPLE_ALL_MASK.
int XAxiCdma_SetCoalesce(XAxiCdma *InstancePtr, u32 Counter, u32 Delay)
This function tries to set the interrupt coalescing threshold counter and the delay counter.
If to set only one of the counters, set the value of the other counter to be XAXICDMA_COALESCE_NO_CHANGE. InstancePtr is the driver instance we are working on Counter is the coalescing threshold to set to, the valid range is 1 to XAXICDMA_COALESCE_MAX. Delay is the delay timeout counter to set to, the valid range is 0 to XAXICDMA_DELAY_MAX. Setting a value of 0 disables the delay interrupt. XST_SUCCESS for successXST_FAILURE if hardware is in invalid state, for example, reset failedXST_INVALID_PARAM if one of the counters is not in the valid range None.
References XAXICDMA_COALESCE_MAX, XAXICDMA_CR_OFFSET, XAXICDMA_DELAY_MAX, XAxiCdma_ReadReg, XAxiCdma_WriteReg, XAXICDMA_XR_COALESCE_MASK, XAXICDMA_XR_DELAY_MASK.
void XAxiCdma_GetCoalesce(XAxiCdma *InstancePtr, u32 *CounterPtr, u32 *DelayPtr)
This function gets the current setting of the interrupt coalescing threshold counter and the delay counter.
InstancePtr is the driver instance we are working on CounterPtr is the return value for the coalescing counter setting DelayPtr is the return value for the delay counter setting A zero coalescing threshold indicates invalid results None.
References XAXICDMA_CR_OFFSET, XAxiCdma_ReadReg, XAXICDMA_XR_COALESCE_MASK, XAXICDMA_XR_DELAY_MASK.
void XAxiCdma_DumpRegisters(XAxiCdma *InstancePtr)
This function dumps the registers of this DMA instance.
InstancePtr is the driver instance we are working on None None.
References XAXICDMA_BTT_OFFSET, XAXICDMA_CDESC_MSB_OFFSET, XAXICDMA_CDESC_OFFSET, XAXICDMA_CR_OFFSET, XAXICDMA_DSTADDR_MSB_OFFSET, XAXICDMA_DSTADDR_OFFSET, XAxiCdma_ReadReg, XAXICDMA_SR_OFFSET, XAXICDMA_SRCADDR_MSB_OFFSET, XAXICDMA_SRCADDR_OFFSET, XAXICDMA_TDESC_MSB_OFFSET, XAXICDMA_TDESC_OFFSET.