xaxicdma_bd.c
XAXICDMA_PAGE_SIZE
void XAxiCdma_BdClear(XAxiCdma_Bd *BdPtr)
This function clears the content of the BD.
BdPtr is the pointer to the BD to be cleared None. None.
References XAXICDMA_BD_START_CLEAR, XAXICDMA_BD_TO_CLEAR.
void XAxiCdma_BdClone(XAxiCdma_Bd *BdPtr, XAxiCdma_Bd *TmpBd)
This function clones the content from the template BD.
BdPtr is the pointer to the BD to be cloned to TmpBd is the pointer to the BD to be cloned from None. None.
References XAXICDMA_BD_START_CLEAR, XAXICDMA_BD_TO_CLEAR.
Referenced by XAxiCdma_BdRingClone.
LONG XAxiCdma_BdGetNextPtr(XAxiCdma_Bd *BdPtr)
This function gets the next BD pointer of the BD.
BdPtr is the pointer to the BD to get the next BD ptr The next BD ptr of the BD. None.
References XAXICDMA_BD_NDESC_MSB_OFFSET, XAXICDMA_BD_NDESC_OFFSET.
Referenced by XAxiCdma_DumpBd.
void XAxiCdma_BdSetNextPtr(XAxiCdma_Bd *BdPtr, UINTPTR NextBdPtr)
This function set the Next BD ptr of a BD.
BdPtr is the pointer to the BD to set the Next BD ptr NextBdPtr is the valud of Next BD ptr None None.
References XAXICDMA_BD_NDESC_MSB_OFFSET, XAXICDMA_BD_NDESC_OFFSET, XAXICDMA_DESC_LSB_MASK.
Referenced by XAxiCdma_BdRingCreate.
u32 XAxiCdma_BdGetSts(XAxiCdma_Bd *BdPtr)
This function gets the completion status of the BD.
BdPtr is the pointer to the BD to get the status The status bits of the BD. None.
References XAXICDMA_BD_STS_ALL_MASK, XAXICDMA_BD_STS_OFFSET.
Referenced by XAxiCdma_BdRingFromHw, XAxiCdma_DumpBd.
void XAxiCdma_BdClearSts(XAxiCdma_Bd *BdPtr)
This function clears the status bits of the BD.
The status bits include the completion bit as well as the error bits.This is the only function that needs to be called to clear a completed BD. All other fields (except reserved words) need to be re-assigned before re-submission. BdPtr is the pointer to the BD to clear the status None None.
References XAXICDMA_BD_STS_OFFSET.
Referenced by XAxiCdma_BdRingClone, XAxiCdma_BdRingToHw.
u32 XAxiCdma_BdSetSrcBufAddr(XAxiCdma_Bd *BdPtr, UINTPTR Addr)
This function sets the source address of the BD.
BdPtr is the pointer to the BD to set the source address Addr is the source address of the buffer XST_SUCCESS if buffer address set successfullyXST_INVALID_PARAM if buffer address is not aligned and hardware build has no DRE or in lite mode None.
References XAXICDMA_BD_BUFSRC_MSB_OFFSET, XAXICDMA_BD_BUFSRC_OFFSET, XAXICDMA_BD_HASDRE_OFFSET, XAXICDMA_BD_WORDLEN_OFFSET.
LONG XAxiCdma_BdGetSrcBufAddr(XAxiCdma_Bd *BdPtr)
This function gets the source address of the BD.
BdPtr is the pointer to the BD to get the source address The source address of the buffer that this BD describes None.
References XAXICDMA_BD_BUFSRC_MSB_OFFSET, XAXICDMA_BD_BUFSRC_OFFSET.
Referenced by XAxiCdma_DumpBd.
u32 XAxiCdma_BdSetDstBufAddr(XAxiCdma_Bd *BdPtr, UINTPTR Addr)
This function sets the destination address of the BD.
BdPtr is the pointer to the BD to set the destination address Addr is the destination address of the buffer XST_SUCCESS if buffer address set successfullyXST_INVALID_PARAM if buffer address is not aligned and hardware build has no DRE or in lite mode None.
References XAXICDMA_BD_BUFDST_MSB_OFFSET, XAXICDMA_BD_BUFDST_OFFSET, XAXICDMA_BD_HASDRE_OFFSET, XAXICDMA_BD_WORDLEN_OFFSET.
LONG XAxiCdma_BdGetDstBufAddr(XAxiCdma_Bd *BdPtr)
This function gets the destination address of the BD.
BdPtr is the pointer to the BD to get the destination address The destination address of the buffer that this BD describes None
References XAXICDMA_BD_BUFDST_MSB_OFFSET, XAXICDMA_BD_BUFDST_OFFSET.
Referenced by XAxiCdma_DumpBd.
u32 XAxiCdma_BdSetLength(XAxiCdma_Bd *BdPtr, int LenBytes)
This function sets the length of the BD.
BdPtr is the pointer to the BD to set the length LenBytes is the length of the buffer XST_SUCCESS for successXST_INVALID_PARAM if invalid length: Length value out of valid range One case that will cause hardware failure is not covered here: If the start address is not at page offset 0, and the length plus the offset crosses the page boundary, this will cause slave error if the hardware is built in lite mode.
References XAXICDMA_BD_CTRL_LEN_OFFSET, XAXICDMA_BD_MAX_LEN_OFFSET.
u32 XAxiCdma_BdGetLength(XAxiCdma_Bd *BdPtr)
This function gets the length of the BD.
BdPtr is the pointer to the BD to get the length The length of the buffer that this BD describes None
References XAXICDMA_BD_CTRL_LEN_OFFSET.
Referenced by XAxiCdma_BdRingToHw, XAxiCdma_DumpBd.
void XAxiCdma_BdSetPhysAddr(XAxiCdma_Bd *BdPtr, UINTPTR PhysAddr)
This function sets the Physical address of the BD.
BdPtr is the pointer to the BD to set the physical address PhysAddr is the physical address of the BD None None
References XAXICDMA_BD_PHYS_ADDR_MSB_OFFSET, XAXICDMA_BD_PHYS_ADDR_OFFSET.
Referenced by XAxiCdma_BdRingCreate.
void XAxiCdma_BdSetIsLite(XAxiCdma_Bd *BdPtr, int IsLite)
This function sets the is lite mode field of the BD.
BdPtr is the pointer to the BD to work on IsLite is the value for whether hardware is in lite mode None None
References XAXICDMA_BD_ISLITE_OFFSET.
Referenced by XAxiCdma_BdRingCreate.
void XAxiCdma_BdSetHasDRE(XAxiCdma_Bd *BdPtr, int HasDRE)
This function sets the has DRE field of the BD.
BdPtr is the pointer to the BD to work on HasDRE is the value for whether hardware has DRE built in None None
References XAXICDMA_BD_HASDRE_OFFSET.
Referenced by XAxiCdma_BdRingCreate.
void XAxiCdma_BdSetWordLen(XAxiCdma_Bd *BdPtr, int WordLen)
This function sets the word length field of the BD.
BdPtr is the pointer to the BD to work on WordLen is the length of word in bytes None None
References XAXICDMA_BD_WORDLEN_OFFSET.
Referenced by XAxiCdma_BdRingCreate.
void XAxiCdma_BdSetMaxLen(XAxiCdma_Bd *BdPtr, int MaxLen)
This function sets the maximum transfer length field of the BD.
BdPtr is the pointer to the BD to work on MaxLen is the maximum transfer length in bytes None None
References XAXICDMA_BD_MAX_LEN_OFFSET.
Referenced by XAxiCdma_BdRingCreate.
LONG XAxiCdma_BdGetPhysAddr(XAxiCdma_Bd *BdPtr)
This function gets the Physical address of the BD.
BdPtr is the pointer to the BD to get the physical address The physical address of the BD None
References XAXICDMA_BD_PHYS_ADDR_MSB_OFFSET, XAXICDMA_BD_PHYS_ADDR_OFFSET.
Referenced by XAxiCdma_BdRingToHw, XAxiCdma_DumpBd.
void XAxiCdma_DumpBd(XAxiCdma_Bd *BdPtr)
This function dumps the BD, it is a debug utility.
BdPtr is the pointer to the BD to get the physical address None None
References XAXICDMA_BD_HASDRE_OFFSET, XAXICDMA_BD_ISLITE_OFFSET, XAXICDMA_BD_MAX_LEN_OFFSET, XAXICDMA_BD_WORDLEN_OFFSET, XAxiCdma_BdGetDstBufAddr, XAxiCdma_BdGetLength, XAxiCdma_BdGetNextPtr, XAxiCdma_BdGetPhysAddr, XAxiCdma_BdGetSrcBufAddr, XAxiCdma_BdGetSts.