xaxicdma_bdring.c
XAXICDMA_RING_SEEKAHEAD
XAXICDMA_RING_SEEKBACK
u32 XAxiCdma_BdRingCntCalc(u32 Alignment, u32 Bytes, UINTPTR BdBuffAddr)
This function calculates how many BDs can be built using given number of bytes of memory, according to alignment provided.
Alignment is the preferred alignment for the BDs Bytes is the number of bytes of memory to build BDs with BdBuffAddr is the buffer address allocated for the BDs. This is to check the alignment of the buffer to make sure the the buffer is aligned to the BD alignment. An invalid buffer address results in 0. The number of BDs can be built. 0 means buffer address is not valid. The application is responsible to align the buffer before pass it to this function.
u32 XAxiCdma_BdRingMemCalc(u32 Alignment, int NumBd)
This function calculates how much memory is needed to build requested number of BDs.
Alignment is the preferred alignment for the BDs NumBd is the number of BDs to be built The number of bytes of memory needed to build the BDs None.
void XAxiCdma_BdSetCurBdPtr(XAxiCdma *InstancePtr, UINTPTR CurBdPtr)
This function set the Current BD ptr of a BD.
BdPtr is the pointer to the BD to set the Next BD ptr CurBdPtr is the valud of Current BD ptr None None.
References XAXICDMA_CDESC_MSB_OFFSET, XAXICDMA_CDESC_OFFSET, XAXICDMA_DESC_LSB_MASK, XAxiCdma_WriteReg.
Referenced by XAxiCdma_SelectKeyHole.
XAxiCdma_Bd * XAxiCdma_BdRingGetCurrBd(XAxiCdma *InstancePtr)
This function grabs a copy of the current BD pointer from the hardware.
InstancePtr is the driver instance we are working on The BD pointer in CDESC register None.
References XAXICDMA_CDESC_MSB_OFFSET, XAXICDMA_CDESC_OFFSET.
Referenced by XAxiCdma_BdRingSnapShotCurrBd, XAxiCdma_SelectKeyHole.
u32 XAxiCdma_BdRingGetCnt(XAxiCdma *InstancePtr)
This function gets the total number of BDs in the BD ring.
InstancePtr is the driver instance we are working on The total number of BDs for this instance None.
u32 XAxiCdma_BdRingGetFreeCnt(XAxiCdma *InstancePtr)
This function gets the number of free BDs.
InstancePtr is the driver instance we are working on The total number of free BDs for this instance None.
void XAxiCdma_BdRingSnapShotCurrBd(XAxiCdma *InstancePtr)
This function grabs a copy of the current BD pointer from the hardware.
It is normally used to prepare for the hardware reset. The snapshot of the current BD pointer should be reloaded once the reset is done. InstancePtr is the driver instance we are working on None None.
References XAxiCdma_BdRingGetCurrBd, XAxiCdma_BdRingNext.
void XAxiCdma_BdSetTailBdPtr(XAxiCdma *InstancePtr, UINTPTR TailBdPtr)
This function set the Tail BD ptr of a BD.
BdPtr is the pointer to the BD to set the Next BD ptr Tail Bd is the value of Tail BD ptr None None.
References XAXICDMA_DESC_LSB_MASK, XAXICDMA_TDESC_MSB_OFFSET, XAXICDMA_TDESC_OFFSET, XAxiCdma_WriteReg.
Referenced by XAxiCdma_BdRingToHw.
XAxiCdma_Bd * XAxiCdma_BdRingNext(XAxiCdma *InstancePtr, XAxiCdma_Bd *BdPtr)
This function gets the next BD of the current BD on the BD ring.
InstancePtr is the driver instance we are working on BdPtr is the current BD The next BD on the ring from the current BD, NULL if passed in BdPtr not valid. None.
References XAXICDMA_BD_MINIMUM_ALIGNMENT.
Referenced by XAxiCdma_BdRingFromHw, XAxiCdma_BdRingSnapShotCurrBd, XAxiCdma_BdRingToHw, XAxiCdma_SelectKeyHole.
XAxiCdma_Bd * XAxiCdma_BdRingPrev(XAxiCdma *InstancePtr, XAxiCdma_Bd *BdPtr)
This function gets the previous BD of the current BD on the BD ring.
InstancePtr is the driver instance we are working on BdPtr is the current BD The previous BD on the ring from the current BD None.
References XAXICDMA_BD_MINIMUM_ALIGNMENT.
Referenced by XAxiCdma_BdRingToHw.
LONG XAxiCdma_BdRingCreate(XAxiCdma *InstancePtr, UINTPTR PhysAddr, UINTPTR VirtAddr, u32 Alignment, int BdCount)
This function creates the BD ring for the driver instance.
If a BD ring pre-exist of this ring, the previous ring is lost. InstancePtr is the driver instance we are working on PhysAddr is the physical address of the memory for the BD ring VirtAddr is the virtual address of the memory for the BD ring Alignment is the alignment for the BDs BdCount is the number of BDs to create in the ring XST_SUCCESS for successXST_INVALID_PARAM for invalid parameterXST_DMA_SG_LIST_ERROR for invalid memory regionXST_FAILURE if the hardware build is simple mode only For a system that has flat memory layout, then the PhysAddr and the VirtAddr are the same.
References XAXICDMA_BD_MINIMUM_ALIGNMENT, XAxiCdma_BdSetHasDRE, XAxiCdma_BdSetIsLite, XAxiCdma_BdSetMaxLen, XAxiCdma_BdSetNextPtr, XAxiCdma_BdSetPhysAddr, XAxiCdma_BdSetWordLen.
LONG XAxiCdma_BdRingClone(XAxiCdma *InstancePtr, XAxiCdma_Bd *TemplateBdPtr)
This function clones all BDs in the BD ring to be the same as the given BD.
InstancePtr is the driver instance we are working on TemplateBdPtr is the BD to be copied from XST_SUCCESS for successXST_DMA_SG_NO_LIST if there is no BD ringXST_DEVICE_IS_STARTED if the hardware is runningXST_DMA_SG_LIST_ERROR is the BD ring is still in use None.
References XAxiCdma_BdClearSts, XAxiCdma_BdClone, XAxiCdma_IsBusy.
LONG XAxiCdma_BdRingAlloc(XAxiCdma *InstancePtr, int NumBd, XAxiCdma_Bd **BdSetPtr)
This function requests number of BDs from the BD ring.
InstancePtr is the driver instance we are working on NumBd is the number of BDs to request BdSetPtr is the pointer to the set of BDs returned XST_SUCCESS for successXST_INVALID_PARAM if requests non-positive number of BDsXST_FAILURE if not enough free BDs available None.
LONG XAxiCdma_BdRingUnAlloc(XAxiCdma *InstancePtr, int NumBd, XAxiCdma_Bd *BdSetPtr)
This function tries to free the number of BDs back to the ring.
InstancePtr is the driver instance we are working on NumBd is the number of BDs to return BdSetPtr is the set of BDs to be returned XST_SUCCESS for successXST_INVALID_PARAM if to free non-positive number of BDsXST_FAILURE if BD ring management shows an error None.
static void StubCallBackFn(void *CallBackRef, u32 IrqMask, int *NumBdPtr)
LONG XAxiCdma_BdRingToHw(XAxiCdma *InstancePtr, int NumBd, XAxiCdma_Bd *BdSetPtr, XAxiCdma_CallBackFn CallBackFn, void *CallBackRef)
This function tries to enqueue the number of BDs to the hardware.
InstancePtr is the driver instance we are working on NumBd is the number of BDs to enqueue BdSetPtr is the set of BDs to be enqueued CallBackFn is the callback function for this transfer, NULL is fine CallBackRef is the callback reference pointer XST_SUCCESS for successXST_INVALID_PARAM if enqueues negative number of BDs or zero transfer lenXST_DMA_SG_LIST_ERROR if BD ring management has a problemXST_FIFO_NO_ROOM if the interrupt handler array is fullXST_FAILURE for: Hardware is in invalid state, for example, reset failed Or, the hardware build is simple mode only None.
References XAxiCdma_BdClearSts, XAxiCdma_BdGetLength, XAxiCdma_BdGetPhysAddr, XAxiCdma_BdRingNext, XAxiCdma_BdRingPrev, XAxiCdma_BdSetTailBdPtr.
u32 XAxiCdma_BdRingFromHw(XAxiCdma *InstancePtr, int BdLimit, XAxiCdma_Bd **BdSetPtr)
This function tries to retrieve completed BDs from the hardware.
InstancePtr is the driver instance we are working on BdLimit is the maximum number of completed BDs to retrieve BdSetPtr is the set of completed BDs The number of completed BDs. None.
References XAXICDMA_BD_STS_COMPLETE_MASK, XAxiCdma_BdGetSts, XAxiCdma_BdRingNext.
u32 XAxiCdma_BdRingFree(XAxiCdma *InstancePtr, int NumBd, XAxiCdma_Bd *BdSetPtr)
This function returns the BDs back to the free pool of the BD ring.
InstancePtr is the driver instance we are working on NumBd is the number of BDs to free BdSetPtr is the set of BDs to be freed XST_SUCCESS for successXST_INVALID_PARAM if number of BDs is negativeXST_DMA_SG_LIST_ERROR if the BD ring management has a problem None.
int XAxiCdma_BdRingStartTransfer(XAxiCdma *InstancePtr)