xaxicdma_intr.c
void XAxiCdma_IntrEnable(XAxiCdma *InstancePtr, u32 Mask)
This function enables interrupts specified by the Mask.
Interrupts that are not in the mask are not affected. InstancePtr is the driver instance we are working on Mask is the mask for the interrupts to be enabled None None.
References XAXICDMA_CR_OFFSET, XAxiCdma_ReadReg, XAxiCdma_WriteReg, XAXICDMA_XR_IRQ_ALL_MASK.
Referenced by XAxiCdma_HybridIntrExample, XAxiCdma_SgIntrExample, XAxiCdma_SimpleIntrExample.
u32 XAxiCdma_IntrGetEnabled(XAxiCdma *InstancePtr)
This function gets the mask for the interrupts that are currently enabled.
InstancePtr is the driver instance we are working on The bit mask for the interrupts that are currently enabled None.
References XAXICDMA_CR_OFFSET, XAxiCdma_ReadReg, XAXICDMA_XR_IRQ_ALL_MASK.
Referenced by XAxiCdma_SimpleTransfer.
void XAxiCdma_IntrDisable(XAxiCdma *InstancePtr, u32 Mask)
This function disables interrupts specified by the Mask.
Interrupts that are not in the mask are not affected. InstancePtr is the driver instance we are working on Mask is the mask for the interrupts to be disabled None None.
References XAXICDMA_CR_OFFSET, XAxiCdma_ReadReg, XAxiCdma_WriteReg, XAXICDMA_XR_IRQ_ALL_MASK.
Referenced by XAxiCdma_HybridPollExample, XAxiCdma_SimplePollExample.
void XAxiCdma_IntrHandler(void *HandlerRef)
This function is the interrupt handler for the driver, it handles all the interrupts.
For the completion of a transfer that has a callback function, the callback function is called. HandlerRef is a reference pointer passed to the interrupt registration function. It will be a pointer to the driver instance we are working on None If one transfer does not have all its submitted BDs completed successfully,then a reset is needed to clean up the mess left by that transfer.Otherwise, the wrong interrupt callback maybe called for the following transfers. However, if you always use the same interrupt callback for all the transfers, and you are the only user of the DMA engine, then you do not have to worry about this.
References XAxiCdma_ReadReg, XAxiCdma_Reset, XAxiCdma_ResetIsDone, XAXICDMA_SR_ERR_ALL_MASK, XAXICDMA_SR_OFFSET, XAxiCdma_WriteReg, XAXICDMA_XR_IRQ_ALL_MASK, XAXICDMA_XR_IRQ_ERROR_MASK.
Referenced by XAxiCdma_SimpleIntrExample.