xaxicdma.h
typedef void(* XAxiCdma_CallBackFn)(void *CallBackRef, u32 IrqMask, int *NumBdPtr))(void *CallBackRef, u32 IrqMask, int *NumBdPtr)
XAXICDMA_COALESCE_NO_CHANGE
XAXICDMA_ALL_BDS
XAXICDMA_SG_MODE
XAXICDMA_SIMPLE_MODE
XAXICDMA_MAXIMUM_MAX_HANDLER
XAXICDMA_KEYHOLE_READ
XAXICDMA_KEYHOLE_WRITE
XAXICDMA_CACHE_FLUSH
XAXICDMA_CACHE_INVALIDATE
XAxiCdma_Config * XAxiCdma_LookupConfig(UINTPTR BaseAddress)
Looks up the device configuration based on the unique device ID/BaseAddress.
A table contains the configuration info for each device in the system. BaseAddress contains the base address of the device A pointer to the configuration table entry corresponding to the given device ID/BaseAddress, or NULL if no match is found. In XSCT/classic flow, DeviceId is used to look up the device configuration.
Referenced by XAxiCdma_HybridIntrExample, XAxiCdma_HybridPollExample, XAxiCdma_SgIntrExample, XAxiCdma_SgPollExample, XAxiCdma_SimpleIntrExample, XAxiCdma_SimplePollExample.
u32 XAxiCdma_CfgInitialize(XAxiCdma *InstancePtr, XAxiCdma_Config *CfgPtr, UINTPTR EffectiveAddr)
This function initializes the driver.
It should be called before any other function calls to the driver.It sets up the driver according to the hardware build. It resets the hardware at the end. InstancePtr is the driver instance that is working on CfgPtr is the pointer to the hardware configuration structure EffectiveAddr is the virtual address of the hardware instance. If address translation is not in use, please use the physical address XST_SUCCESS for successXST_INVALID_PARAM if word length is less than 4XST_FAILURE for reset failure None.
References XAXICDMA_4_1_MAX_TRANSFER_LEN, XAXICDMA_MAX_TRANSFER_LEN, XAxiCdma_ReadReg, XAxiCdma_Reset, XAxiCdma_ResetIsDone, XAXICDMA_SR_OFFSET, XAXICDMA_SR_SGINCLD_MASK.
Referenced by XAxiCdma_HybridIntrExample, XAxiCdma_HybridPollExample, XAxiCdma_SgIntrExample, XAxiCdma_SgPollExample, XAxiCdma_SimpleIntrExample, XAxiCdma_SimplePollExample.
void XAxiCdma_Reset(XAxiCdma *InstancePtr)
This function conducts hardware reset.
Current transfer will finish gracefully. However, all queued SG transfers that have not started will be flushed from the hardware. InstancePtr is the driver instance we are working on None None.
References XAXICDMA_CR_OFFSET, XAXICDMA_CR_RESET_MASK, XAxiCdma_WriteReg.
Referenced by XAxiCdma_CfgInitialize, XAxiCdma_IntrHandler, XAxiCdma_SgPollExample.
int XAxiCdma_ResetIsDone(XAxiCdma *InstancePtr)
This function checks whether the hardware reset is done.
InstancePtr is the driver instance we are working on 1 if the reset has finished successfully0 if the reset is not done None.
References XAXICDMA_CR_OFFSET, XAXICDMA_CR_RESET_MASK, XAxiCdma_ReadReg.
Referenced by XAxiCdma_CfgInitialize, XAxiCdma_IntrHandler, XAxiCdma_SgPollExample.
int XAxiCdma_IsBusy(XAxiCdma *InstancePtr)
This function checks whether the hardware is doing transfer.
InstancePtr is the driver instance we are working on 1 if the hardware is doing a transfer0 if the hardware is idle None.
References XAxiCdma_ReadReg, XAXICDMA_SR_IDLE_MASK, XAXICDMA_SR_OFFSET.
Referenced by XAxiCdma_BdRingClone, XAxiCdma_SelectKeyHole, XAxiCdma_SimpleTransfer.
int XAxiCdma_SetCoalesce(XAxiCdma *InstancePtr, u32 Counter, u32 Delay)
This function tries to set the interrupt coalescing threshold counter and the delay counter.
If to set only one of the counters, set the value of the other counter to be XAXICDMA_COALESCE_NO_CHANGE. InstancePtr is the driver instance we are working on Counter is the coalescing threshold to set to, the valid range is 1 to XAXICDMA_COALESCE_MAX. Delay is the delay timeout counter to set to, the valid range is 0 to XAXICDMA_DELAY_MAX. Setting a value of 0 disables the delay interrupt. XST_SUCCESS for successXST_FAILURE if hardware is in invalid state, for example, reset failedXST_INVALID_PARAM if one of the counters is not in the valid range None.
References XAXICDMA_COALESCE_MAX, XAXICDMA_CR_OFFSET, XAXICDMA_DELAY_MAX, XAxiCdma_ReadReg, XAxiCdma_WriteReg, XAXICDMA_XR_COALESCE_MASK, XAXICDMA_XR_DELAY_MASK.
void XAxiCdma_GetCoalesce(XAxiCdma *InstancePtr, u32 *CounterPtr, u32 *DelayPtr)
This function gets the current setting of the interrupt coalescing threshold counter and the delay counter.
InstancePtr is the driver instance we are working on CounterPtr is the return value for the coalescing counter setting DelayPtr is the return value for the delay counter setting A zero coalescing threshold indicates invalid results None.
References XAXICDMA_CR_OFFSET, XAxiCdma_ReadReg, XAXICDMA_XR_COALESCE_MASK, XAXICDMA_XR_DELAY_MASK.
u32 XAxiCdma_GetError(XAxiCdma *InstancePtr)
This function gets the status on error bits.
InstancePtr is the driver instance we are working on The error bits in the status register. Zero indicates no errors. None.
References XAxiCdma_ReadReg, XAXICDMA_SR_ERR_ALL_MASK, XAXICDMA_SR_OFFSET.
Referenced by XAxiCdma_SgIntrExample.
void XAxiCdma_IntrEnable(XAxiCdma *InstancePtr, u32 Mask)
This function enables interrupts specified by the Mask.
Interrupts that are not in the mask are not affected. InstancePtr is the driver instance we are working on Mask is the mask for the interrupts to be enabled None None.
References XAXICDMA_CR_OFFSET, XAxiCdma_ReadReg, XAxiCdma_WriteReg, XAXICDMA_XR_IRQ_ALL_MASK.
Referenced by XAxiCdma_HybridIntrExample, XAxiCdma_SgIntrExample, XAxiCdma_SimpleIntrExample.
u32 XAxiCdma_IntrGetEnabled(XAxiCdma *InstancePtr)
This function gets the mask for the interrupts that are currently enabled.
InstancePtr is the driver instance we are working on The bit mask for the interrupts that are currently enabled None.
References XAXICDMA_CR_OFFSET, XAxiCdma_ReadReg, XAXICDMA_XR_IRQ_ALL_MASK.
Referenced by XAxiCdma_SimpleTransfer.
void XAxiCdma_IntrDisable(XAxiCdma *InstancePtr, u32 Mask)
This function disables interrupts specified by the Mask.
Interrupts that are not in the mask are not affected. InstancePtr is the driver instance we are working on Mask is the mask for the interrupts to be disabled None None.
References XAXICDMA_CR_OFFSET, XAxiCdma_ReadReg, XAxiCdma_WriteReg, XAXICDMA_XR_IRQ_ALL_MASK.
Referenced by XAxiCdma_HybridPollExample, XAxiCdma_SimplePollExample.
void XAxiCdma_IntrHandler(void *HandlerRef)
This function is the interrupt handler for the driver, it handles all the interrupts.
For the completion of a transfer that has a callback function, the callback function is called. HandlerRef is a reference pointer passed to the interrupt registration function. It will be a pointer to the driver instance we are working on None If one transfer does not have all its submitted BDs completed successfully,then a reset is needed to clean up the mess left by that transfer.Otherwise, the wrong interrupt callback maybe called for the following transfers. However, if you always use the same interrupt callback for all the transfers, and you are the only user of the DMA engine, then you do not have to worry about this.
References XAxiCdma_ReadReg, XAxiCdma_Reset, XAxiCdma_ResetIsDone, XAXICDMA_SR_ERR_ALL_MASK, XAXICDMA_SR_OFFSET, XAxiCdma_WriteReg, XAXICDMA_XR_IRQ_ALL_MASK, XAXICDMA_XR_IRQ_ERROR_MASK.
Referenced by XAxiCdma_SimpleIntrExample.
u32 XAxiCdma_SimpleTransfer(XAxiCdma *InstancePtr, UINTPTR SrcAddr, UINTPTR DstAddr, int Length, XAxiCdma_CallBackFn SimpleCallBack, void *CallBackRef)
This function does one simple transfer submission.
It checks in the following sequence: if engine is busy, cannot submitif software is still handling the completion of the previous simple transfer, cannot submitif engine is in SG mode and cannot switch to simple mode, cannot submit InstancePtr is the pointer to the driver instance SrcAddr is the address of the source buffer DstAddr is the address of the destination buffer Length is the length of the transfer SimpleCallBack is the callback function for the simple transfer CallBackRef is the callback reference pointer XST_SUCCESS for success of submissionXST_FAILURE for submission failure, maybe caused by: Another simple transfer is still going . Another SG transfer is still goingXST_INVALID_PARAM if: Length out of valid range [1: XAXICDMA_MAX_TRANSFER_LEN] Or, address not aligned when DRE is not built in Only set the callback function if using interrupt to signal the completion.If used in polling mode, please set the callback function to be NULL.
References XAXICDMA_BTT_OFFSET, XAXICDMA_DSTADDR_MSB_OFFSET, XAXICDMA_DSTADDR_OFFSET, XAxiCdma_IntrGetEnabled, XAxiCdma_IsBusy, XAXICDMA_MAX_TRANSFER_LEN, XAXICDMA_SRCADDR_MSB_OFFSET, XAXICDMA_SRCADDR_OFFSET, XAxiCdma_WriteReg, XAXICDMA_XR_IRQ_SIMPLE_ALL_MASK.
int XAxiCdma_SelectKeyHole(XAxiCdma *InstancePtr, u32 Direction, u32 Select)
This function configures KeyHole Write/Read Feature.
InstancePtr is the driver instance we are working on Direction is WRITE/READ Select is the option to enable (TRUE) or disable (FALSE). - XST_SUCCESS for success XST_DEVICE_BUSY when transfer is in progressXST_NO_FEATURE when not configured with feature None.
References XAxiCdma_BdRingGetCurrBd, XAxiCdma_BdRingNext, XAxiCdma_BdSetCurBdPtr, XAXICDMA_CR_KHOLE_RD_MASK, XAXICDMA_CR_KHOLE_WR_MASK, XAXICDMA_CR_OFFSET, XAXICDMA_CR_SGMODE_MASK, XAxiCdma_IsBusy, XAxiCdma_ReadReg, XAxiCdma_WriteReg.
u32 XAxiCdma_BdRingCntCalc(u32 Alignment, u32 Bytes, UINTPTR BdBuffAddr)
This function calculates how many BDs can be built using given number of bytes of memory, according to alignment provided.
Alignment is the preferred alignment for the BDs Bytes is the number of bytes of memory to build BDs with BdBuffAddr is the buffer address allocated for the BDs. This is to check the alignment of the buffer to make sure the the buffer is aligned to the BD alignment. An invalid buffer address results in 0. The number of BDs can be built. 0 means buffer address is not valid. The application is responsible to align the buffer before pass it to this function.
u32 XAxiCdma_BdRingMemCalc(u32 Alignment, int NumBd)
This function calculates how much memory is needed to build requested number of BDs.
Alignment is the preferred alignment for the BDs NumBd is the number of BDs to be built The number of bytes of memory needed to build the BDs None.
u32 XAxiCdma_BdRingGetCnt(XAxiCdma *InstancePtr)
This function gets the total number of BDs in the BD ring.
InstancePtr is the driver instance we are working on The total number of BDs for this instance None.
u32 XAxiCdma_BdRingGetFreeCnt(XAxiCdma *InstancePtr)
This function gets the number of free BDs.
InstancePtr is the driver instance we are working on The total number of free BDs for this instance None.
void XAxiCdma_BdRingSnapShotCurrBd(XAxiCdma *InstancePtr)
This function grabs a copy of the current BD pointer from the hardware.
It is normally used to prepare for the hardware reset. The snapshot of the current BD pointer should be reloaded once the reset is done. InstancePtr is the driver instance we are working on None None.
References XAxiCdma_BdRingGetCurrBd, XAxiCdma_BdRingNext.
XAxiCdma_Bd * XAxiCdma_BdRingGetCurrBd(XAxiCdma *InstancePtr)
This function grabs a copy of the current BD pointer from the hardware.
InstancePtr is the driver instance we are working on The BD pointer in CDESC register None.
References XAXICDMA_CDESC_MSB_OFFSET, XAXICDMA_CDESC_OFFSET.
Referenced by XAxiCdma_BdRingSnapShotCurrBd, XAxiCdma_SelectKeyHole.
XAxiCdma_Bd * XAxiCdma_BdRingNext(XAxiCdma *InstancePtr, XAxiCdma_Bd *BdPtr)
This function gets the next BD of the current BD on the BD ring.
InstancePtr is the driver instance we are working on BdPtr is the current BD The next BD on the ring from the current BD, NULL if passed in BdPtr not valid. None.
References XAXICDMA_BD_MINIMUM_ALIGNMENT.
Referenced by XAxiCdma_BdRingFromHw, XAxiCdma_BdRingSnapShotCurrBd, XAxiCdma_BdRingToHw, XAxiCdma_SelectKeyHole.
XAxiCdma_Bd * XAxiCdma_BdRingPrev(XAxiCdma *InstancePtr, XAxiCdma_Bd *BdPtr)
This function gets the previous BD of the current BD on the BD ring.
InstancePtr is the driver instance we are working on BdPtr is the current BD The previous BD on the ring from the current BD None.
References XAXICDMA_BD_MINIMUM_ALIGNMENT.
Referenced by XAxiCdma_BdRingToHw.
LONG XAxiCdma_BdRingCreate(XAxiCdma *InstancePtr, UINTPTR PhysAddr, UINTPTR VirtAddr, u32 Alignment, int BdCount)
This function creates the BD ring for the driver instance.
If a BD ring pre-exist of this ring, the previous ring is lost. InstancePtr is the driver instance we are working on PhysAddr is the physical address of the memory for the BD ring VirtAddr is the virtual address of the memory for the BD ring Alignment is the alignment for the BDs BdCount is the number of BDs to create in the ring XST_SUCCESS for successXST_INVALID_PARAM for invalid parameterXST_DMA_SG_LIST_ERROR for invalid memory regionXST_FAILURE if the hardware build is simple mode only For a system that has flat memory layout, then the PhysAddr and the VirtAddr are the same.
References XAXICDMA_BD_MINIMUM_ALIGNMENT, XAxiCdma_BdSetHasDRE, XAxiCdma_BdSetIsLite, XAxiCdma_BdSetMaxLen, XAxiCdma_BdSetNextPtr, XAxiCdma_BdSetPhysAddr, XAxiCdma_BdSetWordLen.
LONG XAxiCdma_BdRingClone(XAxiCdma *InstancePtr, XAxiCdma_Bd *TemplateBdPtr)
This function clones all BDs in the BD ring to be the same as the given BD.
InstancePtr is the driver instance we are working on TemplateBdPtr is the BD to be copied from XST_SUCCESS for successXST_DMA_SG_NO_LIST if there is no BD ringXST_DEVICE_IS_STARTED if the hardware is runningXST_DMA_SG_LIST_ERROR is the BD ring is still in use None.
References XAxiCdma_BdClearSts, XAxiCdma_BdClone, XAxiCdma_IsBusy.
LONG XAxiCdma_BdRingAlloc(XAxiCdma *InstancePtr, int NumBd, XAxiCdma_Bd **BdSetPtr)
This function requests number of BDs from the BD ring.
InstancePtr is the driver instance we are working on NumBd is the number of BDs to request BdSetPtr is the pointer to the set of BDs returned XST_SUCCESS for successXST_INVALID_PARAM if requests non-positive number of BDsXST_FAILURE if not enough free BDs available None.
LONG XAxiCdma_BdRingUnAlloc(XAxiCdma *InstancePtr, int NumBd, XAxiCdma_Bd *BdSetPtr)
This function tries to free the number of BDs back to the ring.
InstancePtr is the driver instance we are working on NumBd is the number of BDs to return BdSetPtr is the set of BDs to be returned XST_SUCCESS for successXST_INVALID_PARAM if to free non-positive number of BDsXST_FAILURE if BD ring management shows an error None.
LONG XAxiCdma_BdRingToHw(XAxiCdma *InstancePtr, int NumBd, XAxiCdma_Bd *BdSetPtr, XAxiCdma_CallBackFn CallBackFn, void *CallBackRef)
This function tries to enqueue the number of BDs to the hardware.
InstancePtr is the driver instance we are working on NumBd is the number of BDs to enqueue BdSetPtr is the set of BDs to be enqueued CallBackFn is the callback function for this transfer, NULL is fine CallBackRef is the callback reference pointer XST_SUCCESS for successXST_INVALID_PARAM if enqueues negative number of BDs or zero transfer lenXST_DMA_SG_LIST_ERROR if BD ring management has a problemXST_FIFO_NO_ROOM if the interrupt handler array is fullXST_FAILURE for: Hardware is in invalid state, for example, reset failed Or, the hardware build is simple mode only None.
References XAxiCdma_BdClearSts, XAxiCdma_BdGetLength, XAxiCdma_BdGetPhysAddr, XAxiCdma_BdRingNext, XAxiCdma_BdRingPrev, XAxiCdma_BdSetTailBdPtr.
u32 XAxiCdma_BdRingFromHw(XAxiCdma *InstancePtr, int BdLimit, XAxiCdma_Bd **BdSetPtr)
This function tries to retrieve completed BDs from the hardware.
InstancePtr is the driver instance we are working on BdLimit is the maximum number of completed BDs to retrieve BdSetPtr is the set of completed BDs The number of completed BDs. None.
References XAXICDMA_BD_STS_COMPLETE_MASK, XAxiCdma_BdGetSts, XAxiCdma_BdRingNext.
u32 XAxiCdma_BdRingFree(XAxiCdma *InstancePtr, int NumBd, XAxiCdma_Bd *BdSetPtr)
This function returns the BDs back to the free pool of the BD ring.
InstancePtr is the driver instance we are working on NumBd is the number of BDs to free BdSetPtr is the set of BDs to be freed XST_SUCCESS for successXST_INVALID_PARAM if number of BDs is negativeXST_DMA_SG_LIST_ERROR if the BD ring management has a problem None.
void XAxiCdma_BdSetCurBdPtr(XAxiCdma *InstancePtr, UINTPTR CurBdPtr)
This function set the Current BD ptr of a BD.
BdPtr is the pointer to the BD to set the Next BD ptr CurBdPtr is the valud of Current BD ptr None None.
References XAXICDMA_CDESC_MSB_OFFSET, XAXICDMA_CDESC_OFFSET, XAXICDMA_DESC_LSB_MASK, XAxiCdma_WriteReg.
Referenced by XAxiCdma_SelectKeyHole.
void XAxiCdma_BdSetTailBdPtr(XAxiCdma *InstancePtr, UINTPTR TailBdPtr)
This function set the Tail BD ptr of a BD.
BdPtr is the pointer to the BD to set the Next BD ptr Tail Bd is the value of Tail BD ptr None None.
References XAXICDMA_DESC_LSB_MASK, XAXICDMA_TDESC_MSB_OFFSET, XAXICDMA_TDESC_OFFSET, XAxiCdma_WriteReg.
Referenced by XAxiCdma_BdRingToHw.
void XAxiCdma_DumpRegisters(XAxiCdma *InstancePtr)
This function dumps the registers of this DMA instance.
InstancePtr is the driver instance we are working on None None.
References XAXICDMA_BTT_OFFSET, XAXICDMA_CDESC_MSB_OFFSET, XAXICDMA_CDESC_OFFSET, XAXICDMA_CR_OFFSET, XAXICDMA_DSTADDR_MSB_OFFSET, XAXICDMA_DSTADDR_OFFSET, XAxiCdma_ReadReg, XAXICDMA_SR_OFFSET, XAXICDMA_SRCADDR_MSB_OFFSET, XAXICDMA_SRCADDR_OFFSET, XAXICDMA_TDESC_MSB_OFFSET, XAXICDMA_TDESC_OFFSET.